### ISSUE TITLE
System.Security.Cryptography.AesGcm - decryption allows truncated tags

### ISSUE THREAD

**Issue by sdrapkin** [dotnet/runtime#71366]
_Edited by @vcsjones_

## API Proposal:

As the issue outlines below, this proposes changes to `AesGcm` because it's current design makes it prone to misuse of allowing truncated authentication tags during decryption.

This proposes new constructors that accept the authentication tag size. During decryption or encryption, the `tag` parameter must match this specified exactly. This means the caller must decide at instantiation what tag size is correct, not what callers of `Encrypt` or `Decrypt` are provided.

The current constructors will continue to have the same existing behavior. However, since this is an issue around misuse, this also proposes obsoleting the existing constructors to steer people toward using constructors which take the authentication tag size.

```diff
namespace System.Security.Cryptography;

public partial class AesGcm {

+  public AesGcm(byte[] key, int tagSizeInBytes);
+  public AesGcm(ReadOnlySpan<byte> key, int tagSizeInBytes);

+  [Obsolete("AesGcm should indicate the required tag size for encryption and decryption. Use a constructor that accepts the tag size.", DiagnosticId = "SYSLIB9999")]
   public AesGcm(byte[] key);
+  [Obsolete("AesGcm should indicate the required tag size for encryption and decryption. Use a constructor that accepts the tag size.", DiagnosticId = "SYSLIB9999")]
   public AesGcm(ReadOnlySpan<byte> key);

+  public int? TagSizeInBytes { get; }
}
```

----

## Original issue:

```csharp
void Main()
{
	Span<byte> plaintext = Encoding.UTF8.GetBytes("[Hello World!]");
	Span<byte> key = new byte[32];
	Span<byte> nonce = new byte[12];
	Span<byte> ciphertext = new byte[plaintext.Length];
	Span<byte> tag = new byte[16];

	using var gcm = new AesGcm(key);

	Encoding.UTF8.GetString(plaintext).Dump();

	gcm.Encrypt(nonce, plaintext, ciphertext, tag);
	plaintext.Clear();
	gcm.Decrypt(nonce, ciphertext, tag.Slice(0, 12), plaintext);
	Encoding.UTF8.GetString(plaintext).Dump();
}
```
Scenario:
A naive (documentation-reading) user uses `AesGcm` to encrypt plaintext and produce ciphertext with the maximum allowed tag of 16 bytes (ie. naively expecting ~128 bits of tag strength). However the `Decrypt` API is quite happy to accept truncated 12-byte tags, which means that the attacker can truncate all tags to 12 bytes for ~96 bits of tag strength (assuming decryption oracle is readily available).

* `AesGcm` `n`-bit tags provide only `n-k` bits of authentication security for messages that are `2^k` blocks long
*  Large files at ~64GiB size are quite common, and it's plausible to assume that close to 2^32 blocks are routinely encrypted

Would that suggest that `AesGcm` tags as implemented in .NET realistically provide close to `96-32=64` bits of security? If yes - is anyone concerned about that? (both in terms of implementation/security and in terms of documentation). If no - please explain and help me understand what I'm missing. Thanks.

**Comment by sdrapkin** [comment]
> Since the AES-GCM implementation supports short tags, `Decrypt` can't tell the difference between a tag that was truncated legitimately or illegitimately. Consumers of `AesGcm` should ensure that the tag length that is being supplied is the expected length.

Thanks for confirming that my understanding is correct.

I see 2 issues:

1. Insufficient [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.aesgcm.decrypt), missing guidance on what `AesGcm` consumers are expected to ensure for tag lengths.
2. Let's assume documentation is updated (ex. the above quote is added to it). How are developers supposed to comply?
	- option-1: validate a fixed-tag-of-length-N expectation. This is practical, but already makes `Decrypt` unsafe for direct exposure (ie. requires a tag-length validator in front of it). N must become part of the caller-state/protocol, since it is not part of the `Encrypt` output.
	- option-2: variable-length-tags. This would be very challenging/unsafe/insecure to implement with `AesGcm` primitive API alone. Our key assumption is that `ciphertext` and `tag` are malleable (which is precisely what the tag is supposed to guard against). While the tag-length could be made non-malleable (option-1), ciphertext-length cannot be made non-malleable. While Microsoft (rightfully) does not prescribe how the tag and ciphertext are to be stored, in the vast majority of uses they are concatenated into one bytestream (order is not relevant). Thus, it is not possible to calculate the correct value of tag-length N from the (ciphertext+tag) bytestream. One approach is to call `Decrypt` 5 times for each of the 5 possible values of N (not an appealing idea for obvious reasons).

Given that it seems option-1 is the only practical/reasonable choice, it would also need to be added to `AesGcm` documentation (ie. guidance that N must be explicitly fixed for safe operation of `Decrypt`, which includes tag validation).

Finally, it might be a good idea to also document a caution that `AesGcm` tag of length N bytes should not be assumed to provide N*8 bits of authentication strength in all scenarios.

Thoughts?

**Comment by sdrapkin** [comment]
What GCM specification does `S.S.C.AesGcm` actually implement?

* [RFC 5116](https://datatracker.ietf.org/doc/html/rfc5116) defines and AEAD interface as well as 2 GCM-mode algorithms implementing this interface: `AEAD_AES_128_GCM` and `AEAD_AES_256_GCM`. Both fix the tag-length to 16 bytes.
* [NIST SP800-38D](https://nvlpubs.nist.gov/nistpubs/legacy/sp/nistspecialpublication800-38d.pdf) specifies GCM-mode, and even states that GCM is a "mode of operation of AES algorithm" (thus making the "AES" part of AES-GCM or AesGcm redundant). More importantly, it states that "a single, fixed value for `[tag length t]` from among the supported choices shall be associated with each key." (which `S.S.C.AesGcm` does not do)
* The original [GCM-spec](https://csrc.nist.rip/groups/ST/toolkit/BCM/documents/proposedmodes/gcm/gcm-spec.pdf) by McGrew and Viega defines `T` as the Encryption-step-produced tag, `T'` as the computed Decryption-step-produced tag, and states that "If the two tags match (in both length and value), then the ciphertext is returned. Otherwise, the special symbol **FAIL** is returned." (which is obviously not how `S.S.C.AesGcm` behaves)

**Comment by sdrapkin** [comment]
Proposed improvements to `AesGcm` APIs (non-breaking, backwards-compatible):
```csharp
public class AesGcm
{
	// existing ctors
	public AesGcm(ReadOnlySpan<byte> key) { }
	public AesGcm(byte[] key) { }

	// new field
	int _fixedTagLength = -1;

	// new ctor
	public AesGcm(ReadOnlySpan<byte> key, int fixedTagLength)
	{
		_fixedTagLength = fixedTagLength; // also do [12-16] range check
	}

	// new ctor
	public AesGcm(byte[] key, int fixedTagLength)
	{
		_fixedTagLength = fixedTagLength; // also do [12-16] range check
	}
```

Change internal implementation for
```csharp
static void CheckParameters(ReadOnlySpan<byte> plaintext, ReadOnlySpan<byte> ciphertext, ReadOnlySpan<byte> nonce, ReadOnlySpan<byte> tag)
```
by adding the following check to it:
```csharp
if (tag.Length != _fixedTagLength)
{
	throw new ArgumentException(System.SR.Cryptography_InvalidTagLength, "tag");
}
```

**Comment by bartonjs** [comment]
We're exposing GCM in the same way the underlying providers are, which leaves the algorithms loose tag processing as an application problem.  (I'd've included the tag length in the tag calculation, but I guess the GCM designers disagree)

Generally the application context should know what the tag size is.  In the case of JWA, it's supposed to always be 128 bits (https://datatracker.ietf.org/doc/html/rfc7518#section-4.7), which is up to the implementer to verify.

Adding ctor overloads for the expected tag size is reasonable, and not limiting to anyone following the SP800-38D recommendation, and I guess helps provide a standardized exception message to anyone who chooses to utilize it.

**Comment by sdrapkin** [comment]
Thanks for the response. I would encourage .NET team to consider adding tag-length-fixing constructor overloads to `AesGcm`, based on @bartonjs reply.

Do note that the `AesCcm` behavior does not have the same problem - ie. truncated `AesCcm` tags (that are still length-permitted based on `AesCcm.TagByteSizes`) will fail to decrypt. This creates 2 different (and undocumented) behaviors for `AesGcm` and `AesCcm` APIs in .NET.

Just do a simple sanity test: ask any of your esteemed cryptography-aware colleagues the following simple question:

> I've got an `AesGcm`-encrypted ciphertext, and I'm trying to decrypt it with a truncated tag - will it work?


 ..and watch how many no's you're going to get.

I believe it would be somewhat irresponsible to take the position that "loose AesGcm tag processing" is application's problem. Arguing that .NET team is merely exposing the deficiencies of underlying GCM providers is a dodge at best (at the very least you cannot vouch for all possible GCM providers on all supported current and future .NET-running platforms). However let me provide a specification-based argument:

[NIST SP 800-38D ](https://doi.org/10.6028/NIST.SP.800-38D):
*  Section `5.2.1.2 Output Data`
   * `t` is the bit-length of tag `T`
   * Quote: _"A single, fixed value for t from among the supported choices shall be associated with each key."_
* Section `5.2.2 Authenticated Decryption Function`
   * Quote: _"Given the selection of an approved block cipher, key, and an **associated tag length**, the inputs to
the authenticated decryption function are values for IV, A, C, and T, as described in Sec. 5.2.1 above."_

What this means is that for a specific instance of AesGcm implemented to the spec:
```csharp
var one_gcm = new AesGcm(key);
```
...`one_gcm.Decrypt(...)` MUST NOT accept tag-lengths that differ from those produced by `one_gcm.Encrypt(...)`

Ask any FIPS auditor/validator lab, and they should tell you that the GCM spec wording above is specifically intended to prevent tag truncations under a fixed key. The sister CCM spec (800-38C) which targets the same AEAD behavior has the same constraint:
* (800-38C): _"The MAC that is generated within CCM is an internal variable, denoted T. The bit length of T,
denoted `Tlen`, is a parameter of the mode that shall be fixed for all invocations of CCM with the given key."_

Thus it is quite likely that the current status of `AesGcm` in .NET is that it is not spec-compliant.

**Comment by bartonjs** [comment]
@sdrapkin Your insistence that our implementation is wrong and/or against spec isn't productive.

We have the implementation we have, and we're not going to change it.  The specific example that you cited from JWA nearly automatically requires separate contexts that are only tied together by a specification; and NIST often writes "this is how things are" which only means "this is the only acceptable use for US-Gov and impacted parties" (such as that a single RSA key should be PKCS1 xor PSS, or signing xor encryption... but our underlying providers have the same loosy-goosey model we have (which is what informed ours).

The usability concern behind "let me tell you what tag size I intend to use at construction time to save me the redundancy of checking tag.Length in my code" is valid.  So some new API is justified to enhance that scenario.

The cryptography stack in .NET is also mostly intended as low-level primitives.  It's a key.  Use it however you want.  We don't block duplicated nonces... that's an application problem.  But many specs will tell you they MUST be unique.  At some point things just become a caller/application problem.

**Comment by owlstead** [comment]
To be honest, I don't think much of the previous implementations, leaving such a security detail to users of the libraries. The fact that this kind of thing is not even mentioned in the API's clearly shows a lack of responsibility by the creators of such API's. API's, in my opinion, should contain indication on how to use them correctly. Just brushing this off as something that OpenSSL does as well is dishonest - devs are encouraged to think on their own and know their field. Given the track record of OpenSSL implementation and documentation it is not even a good argument by itself.

Note that the Java implementation defaults to a 128 bit tag size, and that you need to configure the tag size explicitly using `GcmParameterSpec`. So there are certainly implementations that handle this better. Of course, since the tag size is not mentioned explicitly in the list of Java supported algorithms, other providers within that eco-system could choose otherwise. There is also the issue that tag verification is not explicit, so there is a lot of improvement to be made there as well.

That all said, I think adding the constructors is a necessity. But given that the current constructor doesn't indicate a tag size I would strongly suggest to both deprecate it **and** provide a clear warning in the documentation. Otherwise devs will simply choose the easier, insecure option with fewer parameters.

**Comment by vcsjones** [comment]
The top post has been updated with an API proposal.

**Comment by bartonjs** [comment]
Looks good as proposed.

```diff
namespace System.Security.Cryptography;

public partial class AesGcm {

+  public AesGcm(byte[] key, int tagSizeInBytes);
+  public AesGcm(ReadOnlySpan<byte> key, int tagSizeInBytes);

+  [Obsolete("AesGcm should indicate the required tag size for encryption and decryption. Use a constructor that accepts the tag size.", DiagnosticId = "SYSLIB9999")]
   public AesGcm(byte[] key);
+  [Obsolete("AesGcm should indicate the required tag size for encryption and decryption. Use a constructor that accepts the tag size.", DiagnosticId = "SYSLIB9999")]
   public AesGcm(ReadOnlySpan<byte> key);

+  public int? TagSizeInBytes { get; }
}

**Comment by vcsjones** [comment]
Breaking change doc: https://github.com/dotnet/docs/issues/35338
