### ISSUE TITLE
Documentation proposal: How to debug new corelib API

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/runtime#7137]
I am creating new API methods in CoreLib and I need to debug them. See https://github.com/dotnet/coreclr/pull/8615

I read this excellent documentation https://github.com/dotnet/coreclr/blob/master/Documentation/building/debugging-instructions.md but I have issue with step `7. Set Command Arguments=<managed app you wish to run> (e.g. HelloWorld.exe)`. 

I need instructions how to create such  small  app that can be compiled with new API and call this new API to debug new methods.

It will be great if documentation will describe step 7 in more details.

**Comment by ericstj** [comment]
I think this is now pretty easy and should be self-explanatory now that everything is in the same repo.
