### ISSUE TITLE
How should source-build handle the removal of System.Runtime.CompilerServices.Unsafe package in .NET 7.0

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/runtime#71396]
This question stems from https://github.com/dotnet/runtime/pull/64861 which stopped the production of a System.Runtime.CompilerServices.Unsafe package from the runtime.  There are several System.Runtime.CompilerServices.Unsafe 6.0.0 package references in the product which are causing prebuilts in source-build.  How should these be handled?

If I understand things correctly, the runtime is still producing a type forwarding System.Runtime.CompilerServices.Unsafe assembly included in Microsoft.NETCore.App.  Because of this, can source-build utilize a System.Runtime.CompilerServices.Unsafe 6.0.0 reference assembly to compile against?  At runtime the Microsoft.NETCore.App System.Runtime.CompilerServices.Unsafe assembly would get picked up.

cc @dotnet/source-build-internal

**Comment by MichaelSimons** [comment]
@ericstj, @jkotas - Is this something you can provide guidance on?  TIA

**Comment by jkotas** [comment]
> can source-build utilize a System.Runtime.CompilerServices.Unsafe 6.0.0 reference assembly to compile against?

I think so.

This should be handled the same way as any other dead-ended package that is not building anymore, but that may be still referenced by projects that are targeting older runtimes. System.Memory is an example of such package.

**Comment by jkotas** [comment]
@MichaelSimons Can this be closed or is there something left to do in dotnet/runtime?

**Comment by MichaelSimons** [comment]
> @MichaelSimons Can this be closed or is there something left to do in dotnet/runtime?

Nope, this can be closed.  Thanks for the responsive answer.
