### ISSUE TITLE
Static virtual reabstraction doesn't seem to work

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#71414]
I'm working on implementing this with NativeAOT and was looking at how it works in the VM.

Reproed with ~~7.0.100-preview.5.22307.18 SDK~~7.0.100-preview.7.22328.2:

Compile following program:

```csharp
Call<BarClass>();

static void Call<T>() where T : IFoo => T.Frob();

interface IFoo
{
    static virtual void Frob() => throw null;
}

interface IBar : IFoo
{
    static void IFoo.Frob() => throw null;
}

interface IBaz : IFoo
{
    static abstract void IFoo.Frob();
}

class BarClass : IBar
{
}
```

~~This will throw at runtime:~~

```
Unhandled exception. System.TypeLoadException: Method implementation on an interface 'IBar' from assembly 'publishaot2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' must be a final method.
   at Program.<Main>$(String[] args)
```

~~Sure, looks like a Roslyn bug, but it's not what I'm after. (@AlekseyTs is this known?)~~

~~Fix the problem by ildasm-ing the assembly, adding the missing `final` and ILAsm-ing it back. Now the program works as expected.~~

Now, go back to the IL and change BarClass to implement IBaz instead of the IBar (Roslyn wouldn't allow compiling that because the method was reabstracted). Rebuild the IL.

```
Unhandled exception. System.MissingMethodException: Method not found: 'Void IFoo.Frob()'.
   at Program.<Main>$(String[] args)
```

This doesn't look like the experience we would want for reabstraction. For reference, the exception with instance default interface methods is (you have to go back to the IL this generates and replace IBar with IBaz in BarClass interface list, same as for the static virtual case because Roslyn doesn't allow compiling with the reabstraction):

```csharp
IFoo foo = new BarClass();
foo.Frob();

interface IFoo
{
    virtual void Frob() => throw null;
}

interface IBar : IFoo
{
    void IFoo.Frob() => throw null;
}

interface IBaz : IFoo
{
    abstract void IFoo.Frob();
}

class BarClass : IBar
{
}
```

This will print a more descriptive message:

```
Unhandled exception. System.EntryPointNotFoundException: Could not call method 'IFoo.Frob()' on type 'IFoo' with an instance of 'BarClass' from assembly 'publishaot2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' because there is no implementation for the method.
   at IFoo.Frob()
   at Program.<Main>$(String[] args)
```

Cc @trylek @davidwrighton

**Comment by trylek** [comment]
Thanks Michal for reporting this issue. Just to make sure I understand you correctly, are you only concerned about the insufficiently descriptive error message or do you believe that the actual runtime behavior is incorrect?

**Comment by MichalStrehovsky** [comment]
> Thanks Michal for reporting this issue. Just to make sure I understand you correctly, are you only concerned about the insufficiently descriptive error message or do you believe that the actual runtime behavior is incorrect?

I don't know what the runtime is doing that we hit a `MissingMethodException` for a method that exists, so I'm concerned about the runtime behavior too.

**Comment by MichalStrehovsky** [comment]
The Roslyn issue is already fixed. Somehow I switched to a globally installed Preview 5 SDK mid-experimenting with this.

The MissingMethodException still reproes with the latest daily build of the SDK.

**Comment by mangod9** [comment]
Is this something we need to fix in 7?

**Comment by trylek** [comment]
I'm going to try to give it a shot next week; in general I think it's a somewhat corner case, at the very least static virtual method functionality in the .NET 7 runtime libraries hasn't hit this yet.

**Comment by MichalStrehovsky** [comment]
>  at the very least static virtual method functionality in the .NET 7 runtime libraries hasn't hit this yet.

It's in the same bucket as the diamond case. Properly authored apps will never hit it at runtime because Roslyn would never emit it. Mismatched dependencies and incorrectly composed apps can hit it. It's more likely the customers would hit it than us.

**Comment by mangod9** [comment]
moving to 8 at this point.
