### ISSUE TITLE
[API Proposal]: Pass ArrayPool<char> to System.Text.Json

### ISSUE THREAD

**Issue by deeprobin** [dotnet/runtime#71423]
### Background and motivation

Currently System.Text.Json uses `Shared` by default. 
https://github.com/dotnet/runtime/blob/e7f1765fd48554c2618e4010239f59fead9aebde/src/libraries/System.Text.Json/src/System/Text/Json/Writer/Utf8JsonWriter.WriteProperties.Double.cs#L158-L166

### API Proposal

```csharp
namespace System.Text.Json;

public partial struct JsonWriterOptions {
    public ArrayPool<char> ArrayPool { get; set; }
}
```

### API Usage

-

**Comment by eiriktsarpalis** [comment]
What would be the purported benefits of such a knob? Buffer pooling is not strictly limited to serialization and `char` buffers. Honestly, I don't see why we should be adding this.

**Comment by jkotas** [comment]
> ArrayPool is a class you can inherit from

In hindsight, this was a questionable design choice. ArrayPool would be likely sealed if we were to design it again.

Instead of adding infrastructure for passing custom array pools around, it may be better to spend time on making the shared array smarter or more configurable.

**Comment by deeprobin** [comment]
All clear. Thanks.

I'll close this because I can't think of any more use cases in the meantime.
