### ISSUE TITLE
Alternative of Windows Kernel32 API in .NET 6 Linux/MacOS platform

### ISSUE THREAD

**Issue by TapanGhoshRocket** [dotnet/runtime#71437]
Below 3 windows APIs belong to Kernel32.dll, which we use in our .NET Full framework provider code to perform atomic operation on windows OS.

1. InterlockedCompareExchange64
2. InterlockedDecrement64
3. InterlockedIncrement64

For .NET 6 provider (which supports cross platform), do we have anything similar to above API which will work in Linux and MacOS to perform atomic operation. Could you please share insight to how we can achieve the same API functionality in Linux and MacOS platform for .NET 6 provider.

**Comment by teo-tsirpanis** [comment]
Hello @TapanGhoshRocket, the [`System.Threading.Interlocked`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.interlocked) class has the methods you need, and apart from some overloads for unsigned integers, these methods are also available on .NET Framework. Besides being cross-platform they are much faster than P/Invoking into `kernel32.dll`.

**Comment by stephentoub** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.threading.interlocked.increment?view=net-6.0#system-threading-interlocked-increment(system-int64@)

https://docs.microsoft.com/en-us/dotnet/api/system.threading.interlocked.decrement?view=net-6.0#system-threading-interlocked-decrement(system-int64@)

https://docs.microsoft.com/en-us/dotnet/api/system.threading.interlocked.compareexchange?view=net-6.0#system-threading-interlocked-compareexchange(system-int64@-system-int64-system-int64)

**Comment by TapanGhoshRocket** [comment]
Hi @[teo-tsirpanis](https://github.com/teo-tsirpanis),

InterlockedDecrement64( ) windows API belong to Kernel32.dll, which takes pointer as argument which you can see in reference windows documentation: https://docs.microsoft.com/en-us/windows/win32/api/winnt/nf-winnt-interlockeddecrement64

Excerpt: 
LONG64 InterlockedDecrement64(
  [in, out] LONG64 volatile *Addend
);

I am looking for exact API in .NET 6 framework like InterlockedDecrement64( ) windows API which can take pointer type as argument. However, System.Threading.Interlocked class have Decrement( ) and Increment( ) methods which takes only values as argument (not IntPtr type).

Decrement(Int32) - Decrements a specified variable and stores the result, as an atomic operation.
Decrement(Int64) - Decrements the specified variable and stores the result, as an atomic operation.
Decrement(UInt32) - Decrements a specified variable and stores the result, as an atomic operation.
Decrement(UInt64) - Decrements a specified variable and stores the result, as an atomic operation.

Reference link:  https://docs.microsoft.com/en-us/dotnet/api/system.threading.interlocked?view=net-6.0

However, I can see that for only CompareExchange() method, we support argument with IntPtr type.
e.g. CompareExchange(IntPtr, IntPtr, IntPtr)	- Compares two platform-specific handles or pointers for equality and, if they are equal, replaces the first one.

Why don't we have similar APIs for Increment( ) and Decrement( ) methods which support IntPtr type as argument.

**Comment by stephentoub** [comment]
All of these APIs take managed pointers, e.g. `ref`, for the thing to be updated.  If you actually have a pointer, you can pass it in with `ref *ptr`.

**Comment by TapanGhoshRocket** [comment]
As I need to pass the IntPtr value in Interlocked.Increment( ) method. So, as per your suggestion, I have pass the IntPtr value  as below 
Interlocked.Increment(ref  *0x0000000022A100C0)
in watch window during debugging to check if it is working. However, I am getting below error

error CS0193: The * or -> operator must be applied to a pointer

**Comment by teo-tsirpanis** [comment]
You have to cast to a specific pointer type. For example:

```csharp
Interlocked.Increment(ref *(int*)0x0000000022A100C0);
```

**Comment by TapanGhoshRocket** [comment]
Hi @teo-tsirpanis,

I came across the below challenge in using Interlocked.CompareExchange() API.
I have used 3 IntPtr type arguments in overloaded Interlocked.CompareExchange(ref Destination, Exchange, Comperand) API as below

static internal IntPtr InterlockedCompareExchange(
            IntPtr Destination,    // destination address
            IntPtr Exchange,       // exchange value 
            IntPtr Comperand       // value to compare
        )
        {
            unsafe
            {
                return Interlocked.CompareExchange(ref Destination, Exchange, Comperand);
            }
        }

1st arg is Destination= 0x00000000233a00c8 i.e the memory address from which value needs to be fetched and compared with Comperand IntPtr Data(i.e. IntPtr.Zero). If it is equal then replace it with Exchange value(i.e.(IntPtr)1) at Destination (0x00000000233a00c8) pointer

2nd arg is Exchange = (IntPtr)1
3rd arg is Comperand = IntPtr.Zero

In memory address, I am unable to see the value at address 0x00000000233a00c8 being modified with Exchage value (IntPtr)1, even through value at address 0x00000000233a00c8 (i.e. (IntPtr)(*(int*)(Destination))=0x0000000000000000) is equal to Comperand value (IntPtr.Zero).

In the debugger, I could see the below value

		Comperand	=0x0000000000000000	Type=System.IntPtr
		Destination	=0x00000000233a00c8	Type=System.IntPtr
		Exchange	        =0x0000000000000001	Type=System.IntPtr

I casted to extract value at that pointer location and again casted to (IntPtr) in watch window to see the IntPtr value. 
		
 (IntPtr)(*(int*)(Destination))	= 0x0000000000000000	System.IntPtr

However, when I modified the Destination argument in Interlocked.CompareExchange API with casting like below

Interlocked.CompareExchange(ref (IntPtr)(*(int*)(Destination)), Exchange, Comperand);

I started getting the the error i.e. "A ref or out value must be an assignable variable."

I need to update the value at Destination (0x00000000233a00c8) address based on comparison with Comperand(i.e. IntPtr.Zero) and if it is equal then replace with Exchange value(i.e.(IntPtr)1)at Destination (0x00000000233a00c8) pointer
Could you please guide us to modify the value at Destination address.
