### ISSUE TITLE
Break on first-chance exception in Web Assembly debugger

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/runtime#71443]
Looks like this is an issue impacting the community: https://www.reddit.com/r/Blazor/comments/vhrrl1/blazor_wasm_how_to_break_on_unhandled_exception/

Ideally we can hook into the `System.AppDomain.CurrentDomain.UnhandledException` as we do with WebView for WinForms / WPF. 

Repro:

`Index.razor`:

```razor
<button @onclick="ThrowException">Throw Exception</button>

@code {
    public void ThrowException()
    {
        throw new Exception("throwing new ex");
    }
}
```

`Program.cs`:

```csharp
System.AppDomain.CurrentDomain.UnhandledException += (sender, error) =>
{
    System.Console.WriteLine("!!! Encountered exception !!!");
};
```

Expected: `!!! Encountered exception !!!` console output
Actual: The exception breaks the world // stack trace dumps to console

Kind of related: https://github.com/dotnet/maui/issues/5535

**Comment by mkArtakMSFT** [comment]
@lewing FYI

**Comment by radical** [comment]
@javiercn Will this case get added to the manual tests?

**Comment by TanayParikh** [comment]
> @javiercn Will this case get added to the manual tests?

I'll take care of it 😄
