### ISSUE TITLE
The Task.Id is not guaranteed to be stable across threads

### ISSUE THREAD

**Issue by theodorzoulias** [dotnet/runtime#71487]
### Description

Hi! I think that I have found a bug in the implementation of the [`Task.Id`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.id) property. The same `Task` might be observed having different IDs from different threads.

### Reproduction Steps

One thread creates tasks non-stop in a loop, and stores them in a shared variable. Three threads are reading the shared variable non-stop in a loop, and add in a local dictionary the task and its `Id`. Finally the dictionaries are examined for occurrences that the same task has been observed having different `Id` by different threads.

The full demo is [here](https://dotnetfiddle.net/qzZA85). To run it click the **Run** button.

### Expected behavior

All matched pairs of tasks should have the same `Id`. No mismatch should be found.

### Actual behavior

Many mismatches are found. Below is a typical output of the demo:

```none
Starting 500 msec test
Producer produced 334,138 tasks
Consumer #1 observed 309,554 unique tasks on thread 6
Consumer #2 observed 314,690 unique tasks on thread 7
Consumer #3 observed 308,844 unique tasks on thread 8
Pairs found and compared: 880,897
Errors found: 25,645 (2.91%)
First 10 errors:
- Task with Result 4709   has Id = 4234   on thread 6, and Id = 4232   on thread 7
- Task with Result 4786   has Id = 4410   on thread 6, and Id = 4411   on thread 8
- Task with Result 4791   has Id = 4420   on thread 6, and Id = 4419   on thread 7
- Task with Result 4791   has Id = 4420   on thread 6, and Id = 4419   on thread 8
- Task with Result 4802   has Id = 4446   on thread 6, and Id = 4444   on thread 7
- Task with Result 4802   has Id = 4446   on thread 6, and Id = 4444   on thread 8
- Task with Result 4867   has Id = 4596   on thread 6, and Id = 4598   on thread 8
- Task with Result 4871   has Id = 4607   on thread 6, and Id = 4610   on thread 8
- Task with Result 4888   has Id = 4654   on thread 6, and Id = 4655   on thread 8
- Task with Result 4934   has Id = 4740   on thread 6, and Id = 4743   on thread 8
```

### Regression?

The actual behavior on .NET Framework 4.8 is the same.

### Known Workarounds

I am not aware of any.

### Configuration

- .NET 6.0
- Console application
- Release built
- 64-bit operating system, x64-based processor

### Other information

I looked in the source code of the `Task.Id` property, searching for a good pattern for creating a unique ID per object for a personal project. The source code is not looking exactly right:

https://github.com/dotnet/runtime/blob/cd553b7208db0df889d8fbb325de65182443bb31/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs#L1194-L1206

**Comment by theodorzoulias** [comment]
Oops! My demo is buggy. Please ignore this issue!

**Comment by stephentoub** [comment]
Your repro has a bug:
```C#
                var localtask = Volatile.Read(ref publicTask);
                mappings[localtask] = publicTask.Id;
```
That `publicTask` should be `localtask`.

**Comment by stephentoub** [comment]
Ah, you already found it.  Nevermind. :)

**Comment by theodorzoulias** [comment]
@stephentoub yep, it's embarrassing, but what can you do? Winter and summer the same brain. 😃
