### ISSUE TITLE
Rename `up-for-grabs` to `help wanted`

### ISSUE THREAD

**Issue by deeprobin** [dotnet/runtime#71496]
The reason is that GitHub has automatically reserved the name help-wanted for certain automations such as:
![grafik](https://user-images.githubusercontent.com/10373452/176735724-541b9c28-fe00-4efa-9b2b-e52495bbe8a1.png)

GitHub does not recognize other names for this

**Comment by danmoseley** [comment]
Naming of these comes up periodically because there's no general agreement. Our is named that way because https://up-for-grabs.net recommends it, or at least that was one reason:

> We suggest the label up-for-grabs but using a different name is also acceptable.

Are they an outlier? Is everyone converging on this label now? Does github document somewhere that it requires this particular label?

Similarly we also use "easy" while others recommend "first-timers-only" ([eg](https://www.firsttimersonly.com/)) and I've seen "good-first-issue", etc.

cc @tannergooding who has had input in the past. What we cant have is multiple labels for the same thing.

**Comment by danmoseley** [comment]
I also see that github's own default labels for a new repo include "help wanted" (and "good first issue") -- with no hyphens...

**Comment by tannergooding** [comment]
GitHub has docs on this here: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/encouraging-helpful-contributions-to-your-project-with-labels

I think most sites (like up for grabs) support a few different monikers and so we just need to pick one and stabilize on it.

I do think we want the ability to specify both `help wanted` (we'd appreciate and welcome someone picking it up) and a concept of `difficulty` (this is good for a first time contributor vs this is more advanced and likely needs more time investment if it is picked up).

**Comment by danmoseley** [comment]
That link encourages "good first issue" but does not suggest "help wanted" (both without hyphens) has special powers. Of course if they favored any it would likely be those as they're among the default for new repos.

Essentially: we don't care which variation we use, so long as it's only one. But it needs to be clear that one is so much better than another that it's worth changing again. I'm not seeing that here.

**Comment by jkotas** [comment]
> The reason is that GitHub has automatically reserved the name help-wanted for certain automations such as:

What is the automation that this screenshot came from?

**Comment by deeprobin** [comment]
@jkotas The page of the github organization. https://github.com/dotnet

**Comment by jeffhandley** [comment]
The label "help wanted" is covered in the [default labels](https://docs.github.com/en/github-ae@latest/issues/using-labels-and-milestones-to-track-work/managing-labels#applying-labels-to-issues-and-pull-requests) documentation, but I don't see anything calling out this specific behavior. It seems like a reasonable assumption that GitHub is baking this in though, and it'll stick and gain more traction.

I'm supportive of renaming `up-for-grabs` to `help wanted` to gain this functionality.

_I am annoyed however that they use spaces in label names. Except "wontfix". 😖_

**Comment by jeffhandley** [comment]
I've applied this change, renaming `up-for-grabs` to `help wanted`. I also edited the description of https://github.com/dotnet/runtime/labels/help%20wanted to be `"[up-for-grabs] Good issue for external contributors"`. That ensures the `help wanted` label is displayed when adding a label and typing `"up-for-grabs"`.

![image](https://user-images.githubusercontent.com/1031940/184063638-6e990df2-1e19-4e4d-b7bf-490ff218e380.png)

**Comment by deeprobin** [comment]
Great 👍🏼

**Comment by skyoxZ** [comment]
The link on README.md also needs to change.

**Comment by jkotas** [comment]
Yes, there are number of links in the repo that need to be updated.

**Comment by jeffhandley** [comment]
Thanks. On it.

**Comment by danmoseley** [comment]
I noticed the UI shown above falls back to "good first issue" if "help wanted" is not available, as this is the case for MSBuild currently. Still both are good.

Note that if a repo changes these, they may need to make an update of lines like this https://github.com/up-for-grabs/up-for-grabs.net/blob/f19d7297a01f8e46d9a95ab2bc5ec5511135737a/_data/projects/dotnet-winforms.yml#L14-L15
