### ISSUE TITLE
Use readonly/scoped with existing ref structs that accept spans

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#71497]
We have a handful of public ref struct types that have instance methods that accept span arguments.  Callers then run into problems when trying to use these methods with variables of mixed lifetimes, e.g.
```C#
using System;

public class C
{
    public bool M(ref Reader r)
    {
        Span<char> span = stackalloc char[] { 'a' };
        return r.Equals(span);
    }
}

public ref struct Reader
{
    public bool Equals(ReadOnlySpan<char> span) => true;
}
```
This will fail with the warnings:
```
error CS8352: Cannot use variable 'span' in this context because it may expose referenced variables outside of their declaration scope
error CS8350: This combination of arguments to 'Reader.Equals(ReadOnlySpan<char>)' is disallowed because it may expose variables referenced by parameter 'span' outside of their declaration scope
```
because the `r.Equals(span)` call could theoretically store that `span` into `r`, in which case the caller of `M` would then have a `Reader` storing a `Span<char>` that's pointing to invalid memory.

We have a handful of members that get tripped up by this:
```C#
namespace System.Buffers
{
    public ref struct SequenceReader<T> where T : unmanaged, IEquatable<T>
    {
        public long AdvancePastAny(ReadOnlySpan<T> values);
        public bool IsNext(ReadOnlySpan<T> next, bool advancePast = false);
        public bool TryAdvanceToAny(ReadOnlySpan<T> delimiters, bool advancePastDelimiter = true);
        public bool TryReadTo(out ReadOnlySpan<T> span, ReadOnlySpan<T> delimiter, bool advancePastDelimiter = true);
        public bool TryReadToAny(out ReadOnlySequence<T> sequence, ReadOnlySpan<T> delimiters, bool advancePastDelimiter = true);
        public bool TryReadToAny(out ReadOnlySpan<T> span, ReadOnlySpan<T> delimiters, bool advancePastDelimiter = true);
    }
}

namespace System.Text.Json
{
    public ref struct Utf8JsonReader
    {
        public bool ValueTextEquals(ReadOnlySpan<byte> utf8Text);
        public bool ValueTextEquals(ReadOnlySpan<char> text);
    }
}
```

We have two levers we can pull to address these:
1. Mark the member as `readonly`.  This only works if a) the member actually doesn't modify instance state and b) there aren't other ref parameters / ref structs into which something could be stored.
2. Mark the parameter as `scoped`.  This is new in C# 11 and promises that the parameter won't be stored or returned.

I propose the following:
```C#
namespace System.Buffers
{
    public ref struct SequenceReader<T> where T : unmanaged, IEquatable<T>
    {
        public long AdvancePastAny(**scoped** ReadOnlySpan<T> values);
        public bool IsNext(**scoped** ReadOnlySpan<T> next, bool advancePast = false);
        public bool TryAdvanceToAny(**scoped** ReadOnlySpan<T> delimiters, bool advancePastDelimiter = true);
        public bool TryReadTo(out ReadOnlySpan<T> span, **scoped** ReadOnlySpan<T> delimiter, bool advancePastDelimiter = true);
        public bool TryReadToAny(out ReadOnlySequence<T> sequence, **scoped** ReadOnlySpan<T> delimiters, bool advancePastDelimiter = true);
        public bool TryReadToAny(out ReadOnlySpan<T> span, **scoped** ReadOnlySpan<T> delimiters, bool advancePastDelimiter = true);
    }
}

namespace System.Text.Json
{
    public ref struct Utf8JsonReader
    {
        public **readonly** bool ValueTextEquals(ReadOnlySpan<byte> utf8Text);
        public **readonly** bool ValueTextEquals(ReadOnlySpan<char> text);
    }
}
```

**Comment by GrabYourPitchforks** [comment]
The `SequenceReader` proposal LGTM since all those methods are contracted to mutate the instance state anyway. Curious about the JSON APIs, though. Is there ever a situation where we might want the implementations of these methods to access some lazily-computed-and-cached value?

**Comment by Sergio0694** [comment]
Question about this:

```csharp
public ref struct Utf8JsonReader
    {
        public **readonly** bool ValueTextEquals(ReadOnlySpan<byte> utf8Text);
        public **readonly** bool ValueTextEquals(ReadOnlySpan<char> text);
    }
```

I realize that adding `readonly` would be enough to satisfy the compiler as it'd mean those input spans couldn't possibly be stored on the current `Utf8JsonReader`, but wondering if one shouldn't also add `scoped` anyway? As in, to make it explicit that that argument won't escape, regardless of whether that's already implied by `readonly`. Or also, what would the future FXC guidelines be for scenarios like this: when there's two ways you can use to satisfy the compiler, how do you pick which one to use?

**Comment by stephentoub** [comment]
> I realize that adding readonly would be enough to satisfy the compiler as it'd mean those input spans couldn't possibly be stored on the current Utf8JsonReader, but wondering if one shouldn't also add scoped anyway? As in, to make it explicit that that argument won't escape, regardless of whether that's already implied by readonly. Or also, what would the future FXC guidelines be for scenarios like this: when there's two ways you can use to satisfy the compiler, how do you pick which one to use?

My preference is not specify it when it's not necessary.  If I have:
```C#
class C
{
    public void M(Span<byte> span) { ... }
}
```
I _really_ don't want us to be in a position where we need to add `scoped` to that, as doing so is superfluous and will clutter up a huge number of APIs unnecessarily.  It's not necessary here because the span can't be stored into `this`.  The same is true if this is a `readonly ref struct` or if this is a `readonly` method on a mutable `ref struct`, so I think the same principal applies.

**Comment by stephentoub** [comment]
> when there's two ways you can use to satisfy the compiler, how do you pick which one to use?

I think we should say:
- If readonly is valuable anyway, mark the method as readonly.  If that suffices, you're done.
- If scoped is still required, then also use it.

**Comment by Sergio0694** [comment]
Gotcha, yeah that makes perfect sense to me. Thank you for sharing some additional context on this! 😊

**Comment by eiriktsarpalis** [comment]
SGTM. We already added `readonly` to a few new `Utf8JsonReader` APIs so we should probably retrofit some of the older ones as well.

**Comment by stephentoub** [comment]
> We already added readonly to a few new Utf8JsonReader APIs so we should probably retrofit some of the older ones as well.

Thanks, @eiriktsarpalis.  Yeah, it's a bit haphazard as to what members are readonly, as auto-prop getters are automatically readonly, so properties we happened to implement as auto-props are marked as readonly and others aren't.  I propose we make all the property getters readonly.  That means:
```C#
        // Existing readonly
        public readonly bool HasValueSequence { get { throw null; } }
        public readonly long TokenStartIndex { get { throw null; } }
        public readonly bool ValueIsEscaped { get { throw null; } }
        public readonly System.ReadOnlySpan<byte> ValueSpan { get { throw null; } }

        // New readonly
        public readonly long BytesConsumed { get { throw null; } }
        public readonly int CurrentDepth { get { throw null; } }
        public readonly System.Text.Json.JsonReaderState CurrentState { get { throw null; } }
        public readonly bool IsFinalBlock { get { throw null; } }
        public readonly System.SequencePosition Position { get { throw null; } }
        public readonly System.Text.Json.JsonTokenType TokenType { get { throw null; } }
        public readonly System.Buffers.ReadOnlySequence<byte> ValueSequence { get { throw null; } }
``
Some of those are necessary in order to make ValueTextEquals be readonly, e.g. ValueTextEquals uses TokenType.  I've not looked at the other methods to see whether any would make sense; I'll leave that up to you.

I'm going ahead with these changes in a PR that uses scoped in more places in runtime.  I can hold off until we officially approve the changes if folks think it needs a broader discussion, but I'm also happy to just defer to area owners to sign off on these, since there's not a whole lot that needs discussion: if we're happy signing up to have these members not mutate in the future, we should just make them readonly.  Similarly for scoped: if we're happy committing to not storing those arguments, we should just make them scoped.  I think we should be :)
