### ISSUE TITLE
Poor performance/code-gen with struct enumerators, especially when containing ReadOnlySpan

### ISSUE THREAD

**Issue by Chicken-Bones** [dotnet/runtime#71510]
### Description

Struct enumerators have a lot of potential for high-performance iteration of custom structures. I've seen 'struct-linq' discussed in several places. The following is a simple but practical example.

Try changing the type of `arr` to `T[]` and `inds` to `ReadOnlySpan<int>` and observe differences in stack spill and x86.

I'd love a way to write this code fully with spans and have it be performant.

Even the `T[]` and `int[]` version doesn't compare to the equivalent hand-written version (`Test2`). It looks like loop-cloning doesn't see the enumerator as eligible.

```cs
public ref struct FilteredSpanEnumerator<T>
{
	private readonly ReadOnlySpan<T> arr;
	private readonly int[] inds;

	private T current;
	private int i;

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public FilteredSpanEnumerator(ReadOnlySpan<T> arr, int[] inds) {
		this.arr = arr;
		this.inds = inds;
		current = default;
		i = 0;
	}

	public T Current => current;

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public bool MoveNext() {
		if (i >= inds.Length)
			return false;

		current = arr[inds[i++]];
		return true;
	}

	public FilteredSpanEnumerator<T> GetEnumerator() => this;

	public static void Test() => Test3(new T[100], new int[] {0, 5, 6, 12, 47, 99});

	public static void Test(ReadOnlySpan<T> elements, int[] inds) {
		foreach (var s in new FilteredSpanEnumerator<T>(elements, inds)) {
			Console.WriteLine(s);
		}
	}

	public static void Test2(ReadOnlySpan<T> elements, ReadOnlySpan<int> inds) {
		int i = 0;
		while (i < inds.Length) {
			Console.WriteLine(elements[inds[i++]]);
		}
	}
}
```

### Configuration

.NET 6.0.6, Win x64

### Analysis

Probably a duplicate of a number of issues like #68797 #9977 related to struct promotion and loop cloning heuristics.

category:cq
theme:structs
skill-level:expert
cost:large
impact:medium

**Comment by JulieLeeMSFT** [comment]
cc @BruceForstall for further triaging.

> Probably a duplicate of a number of issues like https://github.com/dotnet/runtime/issues/68797 https://github.com/dotnet/runtime/issues/9977 related to struct promotion and **loop cloning heuristics.**

**Comment by BruceForstall** [comment]
Maybe also related? https://github.com/dotnet/runtime/issues/9304

**Comment by Chicken-Bones** [comment]
> Maybe also related? #9304

`CollectionsMarshal.AsSpan` allows for avoiding the versioning overhead and size vs length that list enumerator has, but the "critical block (fork/join)." issue is probably related. 

Additional reasoning about lengths and bound checks is a generally valuable feature, not applicable in this example, but consider a `Zip` enumerator that initializes `int len = a.Length < b.Length ? a.Length : b.Length;` and iterates from `i = 0` to `len`

**Comment by Chicken-Bones** [comment]
Adding to this, the x86 produced by `ReadOnlySpan<T>.Enumerator` is significantly worse/longer than the for-i loop version (which is produced by the compiler when using `foreach` on a span directly). This means that structs/classes which essentially wrap an array or span cannot achieve peak performance with code like `public ReadOnlySpan<T>.Enumerator GetEnumerator() => _span.GetEnumerator();`

**Comment by jakobbotsch** [comment]
@Chicken-Bones Thanks for the example. The problem with the existing JIT is, as you mention, essentially the same as #68797 -- the existing struct promotion the JIT supports cannot handle recursive promotion, so we do not enregister the fields of `FilteredSpanEnumerator`.

I am working on more general handling for struct promotion in #76928, with a (by default disabled) prototype coming in #83388. The prototype can handle the recursive patterns like in this case. I've turned your code into a benchmark [here](https://github.com/dotnet/runtime/pull/83388#issuecomment-1491996316) that shows good results at around 2.5x the speed. 

If you have more examples then please feel free to share them. It is very helpful to have as many concrete cases as possible.

**Comment by Chicken-Bones** [comment]
Thanks, this is great to see! The other benchmark I'd like to provide is simple:
```cs
ref struct SpanWrapper<T>
{
    public ReadOnlySpan<T> span;
    public ReadOnlySpan<T>.Enumerator GetEnumerator() => span.GetEnumerator();
}
```

and then compare `foreach (var s in span)` to `foreach (var s in spanWrapper)`

**Comment by Chicken-Bones** [comment]
Yes absolutely, please do!
