### ISSUE TITLE
Performance implications of StrongBox

### ISSUE THREAD

**Issue by forReason** [dotnet/runtime#71528]
I have some questions in regards of the following post:

>It let's you "box" a value type to the heap but in a strongly-typed manner, e.g. instead of doing:
>```C#
>object box = 42;
>... // some time later
>int i = (int)box;
>```
>and then being able to pass around the weakly-typed `box`, you can do:
>```C#
>var box = new StrongBox<int>(42);
>... // some time later
>int i = box.Value;
>```
>and then pass around `box` and access its `Value`, which is strongly typed as `int` (via the generic `T`).  Hence the name "strong box", i.e. "strongly-typed box". (It's not limited for use with value types, though.)
>
>You can see example uses of it here:
>https://source.dot.net/#System.Private.CoreLib/StrongBox.cs,bdbb335cbbdee41b,references
>
>Some typical (advanced) use cases include:
>- Sharing an individual value type instance between multiple threads in a mutable fashion
>- Enabling value types of arbitrary size to be atomically written as a reference
>- Working around the lack of ref fields (by passing around the box with its mutable contents)

_Originally posted by @stephentoub in https://github.com/dotnet/runtime/discussions/47774#discussioncomment-335156_

What are the Performance implications of StrongBox? For example:
`int i = (int)box;` needs to unbox the value, which has Performance implications. Is this the same for `StrongBox`?

What is the difference between using a StrongBox vs a very simplistic Class as such:
```
class MyBox()
{
    public decimal Value {get; set;}
}
```
In terms of `StrongBox.Value = X` vs `MyBox.Value = X` 
or `X = StrongBox.Value` and `X = MyBox.Value`

**Comment by gfoidl** [comment]
> What are the Performance implications of StrongBox?

No unboxing is needed, as due the generic specialization (at runtime) the `Value` is there in the correct target-type. So it's faster (and strongly typed).

A simple benchmark shows:
```
|         Method |     Mean |     Error |    StdDev | Ratio | RatioSD |  Gen 0 | Allocated |
|--------------- |---------:|----------:|----------:|------:|--------:|-------:|----------:|
|       BoxUnbox | 4.635 ns | 0.1275 ns | 0.1364 ns |  1.00 |    0.00 | 0.0077 |      24 B |
| StrongBoxUnbox | 3.891 ns | 0.1008 ns | 0.0943 ns |  0.84 |    0.04 | 0.0077 |      24 B |
```

<details>
  <summary>benchmark code</summary>

```c#
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

BenchmarkRunner.Run<Bench>();

[MemoryDiagnoser]
public class Bench
{
    private readonly Foo _foo = new();
    private readonly Bar _bar = new();
    private int _value = 42;

    [Benchmark(Baseline = true)]
    public int BoxUnbox()
    {
        object box = _bar.Create(_value);
        return _bar.GetValue(box);
    }

    [Benchmark]
    public int StrongBoxUnbox()
    {
        StrongBox<int> box = _foo.Create(_value);
        return _foo.GetValue(box);
    }
}

public class Foo
{
    public StrongBox<int> Create(int value) => new StrongBox<int>(value);
    public int GetValue(StrongBox<int> strongBox) => strongBox.Value;
}

public class Bar
{
    public object Create(int value) => (object)value;
    public int GetValue(object box) => (int)box;
}

public class StrongBox<T>
{
    public T Value = default!;

    public StrongBox(T value)
    {
        Value = value;
    }
}
```
</details>

> What is the difference between using a StrongBox vs a very simplistic Class as such

`StrongBox` lives in `System.Runtime.CompilerServices` so it's already there. The custom class needs to be coded first.
Basically that's the difference 😉
Depending on your measures StrongBox is a generic type with it's own implications, whilst the custom class can be written already specialized, so that generic implication don't account -- at the price of less re-usability.

**Comment by stephentoub** [comment]
Closing as answered. Thanks.
