### ISSUE TITLE
P/Invoke SetWindowsHookExA not working in PublishSingleFile/self-contained/win-x86 mode

### ISSUE THREAD

**Issue by VladimirKhil** [dotnet/runtime#71522]
### Description

[Demo.zip](https://github.com/dotnet/runtime/files/9026865/Demo.zip)

I have created and attached a minimal project that allows to reproduce the issue. The main part of it is a call to user32.dll: 

```
[DllImport("user32", EntryPoint = "SetWindowsHookExA", CharSet = CharSet.Ansi, SetLastError = true, ExactSpelling = true)]
        internal static extern IntPtr SetWindowsHookEx(int idHook, LowLevelKeyboardProcDelegate lpfn, IntPtr hMod, int dwThreadId);
```

When the project is build in normal Debug/Release configuration, everything is all right. The problem arises when the project is published with a PublishSingleFile/self-contained mode.

### Reproduction Steps

Call publish.ps1:

`dotnet publish .\ConsoleApp2\ConsoleApp2.csproj -c Release -p:PublishSingleFile=true -r win-x86 --self-contained true`

Then run the published app via run.cmd:

`run`

### Expected behavior

Message "Hello, World!" appears.

### Actual behavior

"Error: The specified module could not be found." is displayed.

### Known Workarounds

It is possible to distribute the app without publishing it as a single file but that prevents from using EnableCompressionInSingleFile option resulting in a significantly larger app size.

### Configuration

I have tested such behavior on:

.NET 6.0.6
Windows 10 x64

### Other information

Publishing to win-x64 architecture does not work also.

**Comment by MichalStrehovsky** [comment]
`Marshal.GetHINSTANCE` returns -1 in single file apps and it's not usable. There's no module that corresponds to the assembly because the entire app is in a single file.

We had that API in the list I collected in https://github.com/dotnet/runtime/issues/38405 but somehow it didn't make it into the docs. Updating the docs in https://github.com/dotnet/docs/pull/30067.

**Comment by NN---** [comment]
Acquire HMODULE from the executable itself

```cs
using (Process process = Process.GetCurrentProcess())
using (ProcessModule module = process.MainModule)
 SetWindowsHookEx
```

**Comment by vitek-karas** [comment]
We should also add `RequiresAssemblyFiles` on the `GetHINSTANCE` API - https://github.com/dotnet/runtime/pull/71531

**Comment by VladimirKhil** [comment]
Thank you! Everything is working now.
