### ISSUE TITLE
System.Text.Json source generator failes if type to serialize is named `Options`

### ISSUE THREAD

**Issue by smkanadl** [dotnet/runtime#71547]
### Description

If I try to generate a SerializationContext for a type names `Options`, the source generator failes with a bunch of error messages.

### Reproduction Steps

``` 
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Example
{
    public class Options
    {
        public string Parameter1 { get; set; }

        public int Parameter2 { get; set; }
    }

    [JsonSerializable(typeof(Options))]
    [JsonSerializable(typeof(string))]
    [JsonSerializable(typeof(int))]
    internal partial class ExampleContext : JsonSerializerContext
    {
    }
}
```

### Expected behavior

The generator should generate a context for the given type.

### Actual behavior

I get a bunch of error messages and warnings. Most likely related to a collision with the property `Options` of the `JsonSerializerContext` base class.

System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\ExampleContext.Options.g.cs(12,102,12,109): warning CS0108: 'ExampleContext.Options' hides inherited member 'JsonSerializerContext.Options'. Use the new keyword if hiding was intended.
System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\ExampleContext.String.g.cs(19,33,19,43): error CS1061: 'JsonTypeInfo<Options>' does not contain a definition for 'Converters' and no accessible extension method 'Converters' accepting a first argument of type 'JsonTypeInfo<Options>' could be found (are you missing a using directive or an assembly reference?)
System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\ExampleContext.String.g.cs(21,143,21,150): error CS1503: Argument 1: cannot convert from 'System.Text.Json.Serialization.Metadata.JsonTypeInfo<Example.Options>' to 'System.Text.Json.JsonSerializerOptions'
System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\ExampleContext.String.g.cs(25,143,25,150): error CS1503: Argument 1: cannot convert from 'System.Text.Json.Serialization.Metadata.JsonTypeInfo<Example.Options>' to 'System.Text.Json.JsonSerializerOptions'
System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\ExampleContext.Int32.g.cs(19,33,19,43): error CS1061: 'JsonTypeInfo<Options>' does not contain a definition for 'Converters' and no accessible extension method 'Converters' accepting a first argument of type 'JsonTypeInfo<Options>' could be found (are you missing a using directive or an assembly reference?)
System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\ExampleContext.Int32.g.cs(21,141,21,148): error CS1503: Argument 1: cannot convert from 'System.Text.Json.Serialization.Metadata.JsonTypeInfo<Example.Options>' to 'System.Text.Json.JsonSerializerOptions'
System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\ExampleContext.Int32.g.cs(25,141,25,148): error CS1503: Argument 1: cannot convert from 'System.Text.Json.Serialization.Metadata.JsonTypeInfo<Example.Options>' to 'System.Text.Json.JsonSerializerOptions'
System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\ExampleContext.Options.g.cs(19,33,19,43): error CS1061: 'JsonTypeInfo<Options>' does not contain a definition for 'Converters' and no accessible extension method 'Converters' accepting a first argument of type 'JsonTypeInfo<Options>' could be found (are you missing a using directive or an assembly reference?)
System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\ExampleContext.Options.g.cs(21,146,21,153): error CS1503: Argument 1: cannot convert from 'System.Text.Json.Serialization.Metadata.JsonTypeInfo<Example.Options>' to 'System.Text.Json.JsonSerializerOptions'
System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\ExampleContext.Options.g.cs(35,147,35,154): error CS1503: Argument 1: cannot convert from 'System.Text.Json.Serialization.Metadata.JsonTypeInfo<Example.Options>' to 'System.Text.Json.JsonSerializerOptions'
System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\ExampleContext.g.cs(38,129,38,139): error CS1061: 'JsonTypeInfo<Options>' does not contain a definition for 'Converters' and no accessible extension method 'Converters' accepting a first argument of type 'JsonTypeInfo<Options>' could be found (are you missing a using directive or an assembly reference?)
System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\ExampleContext.g.cs(48,67,48,74): error CS1503: Argument 2: cannot convert from 'System.Text.Json.Serialization.Metadata.JsonTypeInfo<Example.Options>' to 'System.Text.Json.JsonSerializerOptions'

### Configuration

NET 6.0.301 SDK
Visual Studio 2022 17.2.5
Windows 10.0.19044 x64

**Comment by danmoseley** [comment]
Thanks for the report @smkanadl . Any interest in offering a fix?

**Comment by smkanadl** [comment]
@danmoseley Interest yes, but my knowledge in the whole  source generator topic is still very limited. So I have to decline - at least this time.

**Comment by krwq** [comment]
This is interesting... One of the JsonSerializerContext's public API is called `Options` https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonserializercontext.options?view=net-6.0 and we also generate members with same name as every type passed in to JsonSerializerContext which is causing duplicated property. I think we will need to first figure out what the correct fix...

Supposedly you will get similar problem if you have two classes named same but with different namespaces or if name is `GeneratedSerializerOptions`

**Comment by smkanadl** [comment]
@krwq exactly that was my first guess. I was a bit surprised that no one before me ran into this issue.

Same type in different namespaces is also a good point. That would surely cause me trouble as well.

**Comment by krwq** [comment]
@smkanadl I think you should be able to use https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonserializableattribute.typeinfopropertyname?view=net-6.0#system-text-json-serialization-jsonserializableattribute-typeinfopropertyname to workaround this but I'm not sure if this is expected default behavior, I'd expect some kind of suffix to be added by default (i.e. `Options1`)

**Comment by smkanadl** [comment]
@krwq I'll check if that will work for me. Thanks for the hint 👍

**Comment by krwq** [comment]
moving to 8.0 since workaround seem to exist and we likely won't have time to address this in 7.0 timeline. We're open to contributions

**Comment by eiriktsarpalis** [comment]
Related to https://github.com/dotnet/runtime/issues/58198

**Comment by eiriktsarpalis** [comment]
Closing as wontfix. Even though we could try to implement a naming scheme that avoids conflicts with predefined members in `JsonSerializerContext` (e.g. naming the property `Options2`) this also theoretically risks collisions should another `Options2` type exist in the type graph. I believe the best course of action is to have the user provide explicit disambiguation via the workaround suggested in https://github.com/dotnet/runtime/issues/71547#issuecomment-1172701806.
