### ISSUE TITLE
TaskCompletionSource with TaskCreationOptions.RunContinuationsAsynchronously runs synchronously

### ISSUE THREAD

**Issue by radekm** [dotnet/runtime#71556]
### Description

When `TaskCompletionSource` source created with `TaskCreationOptions.RunContinuationsAsynchronously` is used after cancelled task then it runs synchronously.

### Reproduction Steps

Following code

```csharp
void Log(string msg) =>
    Console.WriteLine(
        "{0} [{1} {2}] {3}",
        DateTime.Now.ToString("hh:mm:ss.FFF"),
        Thread.CurrentThread.ManagedThreadId,
        Thread.CurrentThread.IsThreadPoolThread,
        msg
    );

Log("In main thread");

using var cts = new CancellationTokenSource();
var tcs = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);

async Task BackgroundTask()
{
    Log("Background task started");
    try
    {
        await Task.Delay(5000, cts.Token);
    }
    catch (OperationCanceledException)
    {
        Log("Delay cancelled");
    }

    await tcs.Task;

    Log("Value set");
}

// Intentionally don't await.
_ = BackgroundTask();
    
new Thread(() =>
{
    Log("In new thread before set");
    if (tcs.TrySetResult())
        cts.Cancel();
    Log("In new thread after set");

}).Start();

Thread.Sleep(20_000);
```

prints

```
07:56:27.788 [1 False] In main thread
07:56:27.849 [1 False] Background task started
07:56:27.852 [5 False] In new thread before set
07:56:27.858 [5 False] Delay cancelled
07:56:27.858 [5 False] Value set
07:56:27.858 [5 False] In new thread after set
```

which shows that after awaiting `tcs` code continues synchronously on the new thread created by `new Thread`.

### Expected behavior

Code printing `Value set` (and maybe also code printing `Delay cancelled`) should execute in different thread than code printing `In new thread before set`.

### Actual behavior

Code printing `Value set` which is runs after awaiting `tcs.Task` runs in the same thread as code which called `tcs.TrySetResult` even though `tcs` was created with `TaskCreationOptions.RunContinuationsAsynchronously`.

### Configuration

`dotnet --version` shows `7.0.100-preview.5.22307.18`. I have macOS Monterey 12.4, MacBook Pro (16-inch, 2019). Architecture x64.

### Other information

I think that after cancelling the token by `cts.Cancel` code runs on the same thread.

**Comment by stephentoub** [comment]
> When TaskCompletionSource source created with TaskCreationOptions.RunContinuationsAsynchronously is used after cancelled task then it runs synchronously.

That's not what this repro shows.  By the time the code gets to the `await tcs.Task`, the tcs.Task is already completed (because you don't cancel until after having successfully completed the task).  Thus `await`'ing it is a nop; doing so doesn't hook up any continuations that might run synchronous or asynchronously.

**Comment by radekm** [comment]
It still seems counterintuitive that the code after `await tcs.Task;` gets executed synchronously on the same thread. I thought that the reason to use `RunContinuationsAsynchronously` is to avoid blocking current thread with actions which happen after awaiting the `Task` associated with `TaskCompletionSource`.

And it seems strange that something can break this property. Because now I cannot rely on `RunContinuationsAsynchronously` and instead I have to use `Task.Yield` after every `await tcs.Task`.

**Comment by stephentoub** [comment]
> I thought that the reason to use RunContinuationsAsynchronously is to avoid blocking current thread with actions which happen after awaiting the Task associated with TaskCompletionSource.

It's to avoid the code completing the task from running continuations off of the task.  No continuations are being run as part of the completion here.

> Because now I cannot rely on RunContinuationsAsynchronously and instead I have to use Task.Yield after every await tcs.Task.

In this particular case the issue is that the code is being invoked as part of the call to Cancel.  I suspect if you try your repro on .NET 7 you'll find it does what you want because of https://github.com/dotnet/runtime/pull/64217 (you listed your SDK version as being a 7.0 SDK, but I suspect you're actually running using a 6.0 or earlier runtime).  But regardless, you can avoid this by queueing the Cancel to be asynchronous so that it's not invoked from the thread you don't want the code run from.

**Comment by radekm** [comment]
Awesome. You're right, I had target framework `net6.0`. When I change it to `net7.0` it gives the desired behavior

```
10:09:42.878 [1 False] In main thread
10:09:42.936 [1 False] Background task started
10:09:42.939 [5 False] In new thread before set
10:09:42.941 [5 False] In new thread after set
10:09:42.947 [6 True] Delay cancelled
10:09:42.947 [6 True] Value set
```

> But regardless, you can avoid this by queueing the Cancel to be asynchronous so that it's not invoked from the thread you don't want the code run from.

Good point.

Thanks for explanation and advice. I'm closing this issue
