### ISSUE TITLE
required and GenerateReferenceAssemblySource

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#71559]
When using the new `required` keyword, GenerateReferenceAssemblySource generates code like this:
```C#
[System.Runtime.CompilerServices.RequiredMemberAttribute]
public sealed partial class QuicClientConnectionOptions : System.Net.Quic.QuicConnectionOptions
{
    [System.ObsoleteAttribute("Constructors of types with required members are not supported in this version of your compiler.", true)]
    [System.Runtime.CompilerServices.CompilerFeatureRequiredAttribute("RequiredMembers")]
    public QuicClientConnectionOptions() { }
    [System.Runtime.CompilerServices.RequiredMemberAttribute]
    public System.Net.Security.SslClientAuthenticationOptions ClientAuthenticationOptions { get { throw null; } set { } }
    public System.Net.IPEndPoint? LocalEndPoint { get { throw null; } set { } }
    [System.Runtime.CompilerServices.RequiredMemberAttribute]
    public System.Net.EndPoint RemoteEndPoint { get { throw null; } set { } }
}
```
And then compiler complains that required keyword should be used instead:
```
System.Net.Quic.cs(10,6): error CS9033: Do not use 'System.Runtime.CompilerServices.RequiredMemberAttribute'. Use the 'required' keyword on required fields and properties instead.
```

I don't know which way is the correct way. @ViktorHofer  @333fred 

Follow up issue is that if I manually remove the attributes and add `required` keyword, the GeneratePlatformNotSupportedAssemblyMessage generator generates another code that cannot be compiled. See the missing `get` and `set`:
```C#
public sealed partial class QuicClientConnectionOptions : System.Net.Quic.QuicConnectionOptions
{
    public QuicClientConnectionOptions() { throw new System.PlatformNotSupportedException(System.SR.SystemNetQuic_PlatformNotSupported);  }
    public required System.Net.Security.SslClientAuthenticationOptions ClientAuthenticationOptions { throw new System.PlatformNotSupportedException(System.SR.SystemNetQuic_PlatformNotSupported);  }
    public System.Net.IPEndPoint? LocalEndPoint { get { throw new System.PlatformNotSupportedException(System.SR.SystemNetQuic_PlatformNotSupported);  } set { throw new System.PlatformNotSupportedException(System.SR.SystemNetQuic_PlatformNotSupported);  } }
    public required System.Net.EndPoint RemoteEndPoint { throw new System.PlatformNotSupportedException(System.SR.SystemNetQuic_PlatformNotSupported);  }
}
```
Does anyone know where the GeneratePlatformNotSupportedAssemblyMessage lives and whom to contact?

**Comment by 333fred** [comment]
It looks like the runtime's generator needs to be updated.

**Comment by ViktorHofer** [comment]
> Does anyone know where the GeneratePlatformNotSupportedAssemblyMessage lives and whom to contact?

Here is the task: https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.GenFacades/NotSupportedAssemblyGenerator.cs and the msbuild file with the target that invokes the task is here: https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.GenFacades/build/Microsoft.DotNet.GenFacadesNotSupported.targets.

cc @ericstj @tannergooding

**Comment by ViktorHofer** [comment]
I asked @ericstj to take a look as I'm unsure if bumping the CodeAnalysis version is sufficient to make this work.

**Comment by 333fred** [comment]
> I'm surprised the compiler treats the use of those attributes as an error instead of a suppressable warning.

I don't know of an attribute like this that we allow, even with a warning. For example, extension methods are represented by an attribute, but it is illegal to use that attribute in C# itself.

**Comment by ericstj** [comment]
> I don't know of an attribute like this that we allow, even with a warning. For example, extension methods are represented by an attribute, but it is illegal to use that attribute in C# itself.

I noticed some other ones like `AsyncStateMachineAttribute` and `AsyncIteratorStateMachineAttribute`.  I'm not saying I have a huge opinion here, just saying I was surprised.  I think of _errors_ as things that would halt the compilation and this didn't feel like it was that severe.

**Comment by ericstj** [comment]
It looks like `required` is a `LangVersion`=`preview` feature, but GenFacades just uses roslyn without specifying a langversion, so that's another issue here.

**Comment by ericstj** [comment]
I went ahead and fixed this: https://github.com/dotnet/arcade/pull/10021

**Comment by ericstj** [comment]
This should be fixed in arcade now.  You'll be able to use that change once it merges to dotnet/runtime - likely next week.  Check on Monday if it's made it by looking for a build of GenAPI / GenFacades that's *newer* than 7.0.0-beta.22365.1.  If it hasn't landed by then we can manually pick up the new packages to get this functionality before Darc flows the build.
