### ISSUE TITLE
Crossgen2 should publish with NativeAOT at the beginning of the build

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#71557]
Right now we publish Crossgen2 with NativeAOT at the end of the build for publishing. This uses the "live" AOT compiler we just built. But if we compile at the end of the build, we don't get any testing of the results when we run crossgen2 during the build.

We should probably support two publish modes: "live" and "package". When we use "package" we can use the compiler from the SDK or from the Microsoft.Dotnet.ILCompiler package. These modes can probably be controlled by a property that we set somewhere during the build.

Since we probably don't want to AOT crossgen2 every time we build it for inner-loop development, we'll also need an intermediate project that signals that we want to AOT the crossgen2 project. This might be the existing `crossgen-corelib` project.

**Comment by MichalStrehovsky** [comment]
I tried doing a live build approach (instead of LKG) here: https://github.com/dotnet/runtime/pull/63571

**Comment by agocke** [comment]
Thought about this a bit more and I'm not convinced it's the right thing to do. Some benefits, some drawbacks. I'm going to close this out and we can reopen if we find other reasons to do it.
