### ISSUE TITLE
Building CLR with macOS 13 SDK beta does not succeed

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#71561]
Apparently `sprintf` has been deprecated.

<pre>
/Users/vcsjones/Projects/runtime/src/coreclr/debug/createdump/main.cpp:271:5: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
      sprintf(buffer, "(%d)", error);
      ^
  /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
  __deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
  ^
  /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/usr/include/sys/cdefs.h:214:48: note: expanded from macro '__deprecated_msg'
          #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                        ^
  1 error generated.
</pre>

**Comment by mikem8361** [comment]
This should be fixed in PR https://github.com/dotnet/runtime/pull/71569

**Comment by vcsjones** [comment]
> This should be fixed in PR #71569

Thanks. I checked out the PR and confirmed I can build the `clr+libs` subset.
