### ISSUE TITLE
Equal string operation fails with `object?`, but works otherwise

### ISSUE THREAD

**Issue by leo-schick** [dotnet/runtime#71575]
### Description

Ok, this is the strangest thing ever and I can't figure out why.

I compare to strings with the operator `==`.

The left part is of type `object?` (in the screenshot `DataDomainScope.DataPartition["Company"].Value`),
and right part is of type `string` (in the screenshot `journal.CompanyNum`).

When I do the comparison with the `==` operator it failes, but `Equals(... , ...)`, `left.ToString() == right.ToString()` or `left.GetHashCode() == right.GetHashCode()` works.

![image](https://user-images.githubusercontent.com/67712864/176990391-8499acbf-1aff-4fc9-a92a-6146a0549f9b.png)

I do not expect a CPU / hardware failture, because I have the same issue on a remote server.

### Reproduction Steps

I could not create a minimum reproduceable product. I created a test console app, but there it just works:

``` c#
using System.ComponentModel.DataAnnotations;
using System.Reflection;

public class DataPartition
{
    public Type InterfaceType { get; }

    public PropertyInfo PartitionProperty { get; }

    public object? Value { get; set; }

    public DataPartition(Type interfaceType, PropertyInfo partitionProperty)
    {
        InterfaceType = interfaceType;
        PartitionProperty = partitionProperty;
        Value = null;
    }
}

public class Journal
{
    [Key, Required(AllowEmptyStrings = false), StringLength(5)]
    [Display(Name = "CompanyNum")]
    public string CompanyNum { get; set; }

    public override string ToString()
    {
        return $""; // removed code
    }
}

public class App
{

    static void Main()
    {
        var dataPartition = new DataPartition(typeof(Journal), typeof(Journal).GetProperty(nameof(Journal.CompanyNum)));
        dataPartition.Value = "41351";
        var journal = new Journal { CompanyNum = "41351" };
        
        Console.WriteLine(dataPartition.Value == journal.CompanyNum);
        Console.WriteLine(Equals(dataPartition.Value, journal.CompanyNum));

        Console.ReadLine();

    }
}
```

### Expected behavior

I would expected the equal operation (`==`) to be `true`.

### Actual behavior

The equal operation (`==`) returned `false`.

### Configuration

![image](https://user-images.githubusercontent.com/67712864/176990821-552ad63c-ad65-4ec0-87e6-b0bd1b2be499.png)

Debugging with Visual Studio:
```
Microsoft Visual Studio Community 2022
Version 17.2.5
VisualStudio.17.Release/17.2.5+32616.157
Microsoft .NET Framework
Version 4.8.04161

Installierte Version: Community

Visual C++ 2022   00482-90000-00000-AA034
Microsoft Visual C++ 2022

.NET Core-Debugging mit WSL   1.0
.NET Core-Debugging mit WSL

ASP.NET and Web Tools 2019   17.2.393.26812
ASP.NET and Web Tools 2019

Azure App Service-Tools v3.0.0   17.2.393.26812
Azure App Service-Tools v3.0.0

Azure Functions and Web Jobs Tools   17.2.393.26812
Azure Functions and Web Jobs Tools

C#-Tools   4.2.0-4.22281.5+8d3180e5f00d42f0f0295165f756f368f0cbfa44
C#-Komponenten, die in der IDE verwendet werden. Abhängig von Ihrem Projekttyp und den zugehörigen Einstellungen kann eine andere Version des Compilers verwendet werden.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet-Paket-Manager   6.2.1
NuGet-Paket-Manager in Visual Studio. Weitere Informationen zu NuGet finden Sie unter https://docs.nuget.org/.

Razor (ASP.NET Core)   17.0.0.2218101+885a343b00bcab620a90c1550c37dafd730ce984
Stellt Sprachdienste für ASP.NET Core Razor bereit.

SQL Server Data Tools   17.0.62204.01010
Microsoft SQL Server Data Tools

Testadapter für Boost.Test   1.0
Aktiviert Visual Studio-Testtools mit Komponententests, die für Boost.Test geschrieben wurden. Nutzungsbedingungen und Drittanbieterhinweise stehen im Installationsverzeichnis der Erweiterung zur Verfügung.

Testadapter für Google Test   1.0
Ermöglicht die Verwendung von Visual Studio-Testtools mit Komponententests, die für Google Test geschrieben wurden. Die Nutzungsbedingungen und Drittanbieterhinweise stehen im Installationsverzeichnis der Erweiterung zur Verfügung.

TypeScript-Tools   17.0.10418.2001
TypeScript-Tools für Microsoft Visual Studio

Visual Basic-Tools   4.2.0-4.22281.5+8d3180e5f00d42f0f0295165f756f368f0cbfa44
Visual Basic-Komponenten, die in der IDE verwendet werden. Abhängig von Ihrem Projekttyp und den zugehörigen Einstellungen kann eine andere Version des Compilers verwendet werden.

Visual F# Tools   17.1.0-beta.22274.4+211fd760c2315d73cfa0d375fe64abb346bc1096
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
KI-gestützte Entwicklung für Visual Studio.
```

**Comment by Fabi** [comment]
You are comparing an object reference there. that is why it's showing false. That's not a bug, it's intended. Your repo does not deliver the same result because you ahve two hardcoded strings which will point to the same reference when being used.

Making use of the main args and run ith with `dotnet run 41351 41351` will show you that since they are not poiting to the same object reference then.
```csharp
public class App
{
    static void Main(string[] args)
    {
        
        var dataPartitions = new Dictionary<string, DataPartition>();
        dataPartitions["Company"] = new DataPartition { Value = args[0] };
        
        var journal = new Journal { CompanyNum = args[1]  };
        
        Console.WriteLine(dataPartitions["Company"].Value == journal.CompanyNum);
        Console.WriteLine(Equals(dataPartitions["Company"].Value, journal.CompanyNum));

        Console.ReadLine();

    }
}
```

**Comment by EgorBo** [comment]
Furthermore, Roslyn gives you a warning -  `warning CS0252: Possible unintended reference comparison; to get a value comparison, cast the left hand side to type 'string'` when compiles this

**Comment by YoniFei** [comment]
This is not a bug. See https://stackoverflow.com/questions/814878/c-sharp-difference-between-and-equals

The reason your repro attempt resolves to true due to string interning (see https://duongnt.com/string-interning/).
@Fabi gave an example repro, here's another:

`c#
using System.ComponentModel.DataAnnotations;
using System.Reflection;
using System;

public class DataPartition
{
    public PropertyInfo PartitionProperty { get; }

    public object? Value { get; set; }

    public DataPartition(Type interfaceType, PropertyInfo partitionProperty)
    {
        PartitionProperty = partitionProperty;
        Value = null;
    }
}

public class Journal
{
    [Key, Required(AllowEmptyStrings = false), StringLength(5)]
    [Display(Name = "CompanyNum")]
    public string CompanyNum { get; set; }

    public override string ToString()
    {
        return $""; // removed code
    }
}

public class App
{

    static void Main()
    {
        var dataPartition = new DataPartition(typeof(Journal), typeof(Journal).GetProperty(nameof(Journal.CompanyNum)));
        dataPartition.Value = String.Concat("4135", "1");
        var journal = new Journal { CompanyNum = "41351" };
        
        Console.WriteLine(dataPartition.Value == journal.CompanyNum);
        Console.WriteLine(Equals(dataPartition.Value, journal.CompanyNum));

        Console.ReadLine();

    }
}`

**Comment by leo-schick** [comment]
OK. Looks like that this was a misinterpretation of C# from me. We can close the ticket then (and I will have to go through my code and fix this stuff everywhere 😞)..
