### ISSUE TITLE
`libnethost.lib` seems to refer to its PDB even in `Release` builds

### ISSUE THREAD

**Issue by alexrp** [dotnet/runtime#71578]
### Description

It seems that `libnethost.lib` has an associated PDB file even in `Release` builds. This leads to linker warnings when consumed on a system that doesn't have the PDB present.

### Reproduction Steps

Build a ´libnethost.lib` with `./build.sh -c Release -rc Release -s clr+host`. Copy `libnethost.lib` out of the build directory, then rename the build directory so the PDB cannot be found, and try to link `libnethost.lib` into a C program (in this case with `zig cc`).

### Expected behavior

I don't think a `Release` build of `libnethost.lib` should have a PDB at all? It seems very weird when there is a `RelWithDebInfo` configuration.

Alternatively, at least `libnethost.pdb` should be shipped with `libnethost.lib` in the relevant NuGet packages.

### Actual behavior

```
lld-link : error : Cannot use debug info for 'libnethost.lib(nethost.cpp.obj)' [LNK4099]
lld-link : error : Cannot use debug info for 'libnethost.lib(trace.cpp.obj)' [LNK4099]
lld-link : error : Cannot use debug info for 'libnethost.lib(utils.cpp.obj)' [LNK4099]
lld-link : error : Cannot use debug info for 'libnethost.lib(fxr_resolver.cpp.obj)' [LNK4099]
lld-link : error : Cannot use debug info for 'libnethost.lib(pal.windows.cpp.obj)' [LNK4099]
lld-link : error : Cannot use debug info for 'libnethost.lib(fx_ver.cpp.obj)' [LNK4099]
lld-link : error : Cannot use debug info for 'libnethost.lib(longfile.windows.cpp.obj)' [LNK4099]
```

### Regression?

No.

### Known Workarounds

Copy `libnethost.pdb` from the build directory of a runtime build.

**Comment by alexrp** [comment]
There seems to be code in place to ship the PDBs:

https://github.com/dotnet/runtime/blob/6b8d056a665fa20d321ea1d49a93a37a83960663/src/installer/pkg/projects/Microsoft.NETCore.DotNetAppHost/Microsoft.NETCore.DotNetAppHost.pkgproj#L18-L29

Yet, if I grab the latest runtime.win-x64.Microsoft.NETCore.DotNetAppHost package off NuGet, I see only this:

```
   151040  2022-06-02 06:31   runtimes/win-x64/native/apphost.exe
   142976  2022-06-02 06:31   runtimes/win-x64/native/nethost.dll
     1742  2022-06-02 06:31   runtimes/win-x64/native/nethost.lib
     2552  2022-06-02 06:28   runtimes/win-x64/native/coreclr_delegates.h
    11964  2022-06-02 06:28   runtimes/win-x64/native/hostfxr.h
     2942  2022-06-02 06:28   runtimes/win-x64/native/nethost.h
  9505792  2022-06-02 06:30   runtimes/win-x64/native/singlefilehost.exe
   189440  2022-06-02 06:32   runtimes/win-x64/native/comhost.dll
   155264  2022-06-02 06:32   runtimes/win-x64/native/ijwhost.dll
     1716  2022-06-02 06:32   runtimes/win-x64/native/ijwhost.lib
  7724594  2022-06-02 06:31   runtimes/win-x64/native/libnethost.lib
 23590744  2022-06-02 06:31   runtimes/win-x64/native/libhostfxr.lib
```

Unfortunately, I don't really understand the installer projects enough to suggest a fix for this.

**Comment by AaronRobinsonMSFT** [comment]
> I don't think a Release build of libnethost.lib should have a PDB at all?

It should. The CMake `RelWithDebInfo` is an odd duck from a Microsoft perspective. All official product assets should have accompanying symbols, regardless of build flavor.

> Alternatively, at least libnethost.pdb should be shipped with libnethost.lib in the relevant NuGet packages.

Right. We should ship PDBs for all static libs that we expect users to link into their projects.

This is a duplicate issue and is being tracked in https://github.com/dotnet/runtime/issues/63602.

/cc @elinor-fung
