### ISSUE TITLE
SetWindowPosition obsolete?

### ISSUE THREAD

**Issue by HUNTERSCOUTI** [dotnet/runtime#71587]
https://github.com/dotnet/runtime/blob/d04a5899a749316dfb56539d7266a327fe2f2517/src/libraries/System.Console/src/System/ConsolePal.Unix.cs#L384

**Comment by huoyaoyuan** [comment]
The public entry point indicates that it's only supported on Windows:

https://github.com/dotnet/runtime/blob/d04a5899a749316dfb56539d7266a327fe2f2517/src/libraries/System.Console/src/System/Console.cs#L417-L421

**Comment by Jozkee** [comment]
@HUNTERSCOUTI can you please elaborate?
