### ISSUE TITLE
When I try to create a new project referencing the project in this repository it doesn't build properly

### ISSUE THREAD

**Issue by Linlccc** [dotnet/runtime#71582]
I newly created a solution and then referenced the project in that repository, I got the following error,
And when the project is referenced, the bin/obj folder will also be generated in the project code directory instead of the artifacts directory

![image](https://user-images.githubusercontent.com/48354130/177001570-a5be0cda-7cc5-43dc-8e50-f044e8cfb6b4.png)
![image](https://user-images.githubusercontent.com/48354130/177001622-cc169f64-3346-48ec-8d1a-b9ea665c46eb.png)
![image](https://user-images.githubusercontent.com/48354130/177001771-397fa798-e0ac-4b05-8f25-c62438d4374e.png)

But I open the project directly and it builds fine, what should I do to reference the project in this repository in other solutions, thanks

**Comment by AraHaan** [comment]
Why not simply add the built artifact nuget packages from building this repo locally to your new projects nuget feeds (using nuget.config) and tell it to use package version ``7.0.0-dev``?

**Comment by Linlccc** [comment]
> But why use a local build instead of what is in the dotnet7 feed though, unless you have made local changes and are wanting to test them.

yes i need to debug so i need to reference the project directly not the nuget package or dll

**Comment by huoyaoyuan** [comment]
The build process of this project is very complex. You need to target net7.0, add `global.json`, and ensure the libraries has built correctly with `build.cmd libs`.


> yes i need to debug so i need to reference the project directly not the nuget package or dll

The projects here isn't designed to support so. Using source link would be a lot easier.

**Comment by Linlccc** [comment]
@huoyaoyuan  I have successfully built the project, but when I try to use another project to reference a project in this repository, there is a problem and it fails to build

> The projects here isn't designed to support so. Using source link would be a lot easier.
Of course I know this, I have some low-level stuff to debug，How do you use the original link you mentioned?

**Comment by Clockwork-Muse** [comment]
... There are symbol servers for the runtime, which should normally be used, although you may have to disable "only debug my code".

If you're trying to debug a preview/nightly build, you want to refer to the [dogfooding instructions](https://github.com/dotnet/runtime/blob/main/docs/project/dogfooding.md).

**Comment by Linlccc** [comment]
Can't I directly reference the project? A few months ago, when I directly used other projects to reference the library's project, everything was fine, but this time I don't know if it happened because I didn't do it well

**Comment by huoyaoyuan** [comment]
You need to do at least:
- Install the latest preview SDK, not lower than the version specified in https://github.com/dotnet/runtime/blob/main/global.json
- Set the target framework of your project to net7.0
- Provide a `global.json` for your project if needed.

Your screenshot indicates that you are using 6.0 SDK.

**Comment by Linlccc** [comment]
@huoyaoyuan Thank you very much, the problem is solved, it should be because the global.json configuration of the two projects is different, resulting in the difference between some properties in the project props and targets.
