### ISSUE TITLE
Publish error with blazor .7 preview 5 and AOT

### ISSUE THREAD

**Issue by ahmed-salem-me** [dotnet/runtime#71592]
### Description

I get this error when I try to publish a wasm blazor app with .net 7 preview 5 and aot:
```
Exec:  "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.7.Sdk.win-x64\7.0.0-preview.5.22268.1\tools\bin\wasm-emscripten-finalize" -g --dyncalls-i64 D:\Userware\code\SISE.Riva-MyFork\sise.ria\sise.ria.area.laminacion\sise.laminacion.opensilver\OpenSilverApp\OpenSilverApp.Browser\obj\Release\net7.0\wasm\for-publish\dotnet.wasm -o D:\Userware\code\SISE.Riva-MyFork\sise.ria\sise.ria.area.laminacion\sise.laminacion.opensilver\OpenSilverApp\OpenSilverApp.Browser\obj\Release\net7.0\wasm\for-publish\dotnet.wasm --detect-features
emcc(0,0): Error : '"C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.7.Sdk.win-x64\7.0.0-preview.5.22268.1\tools\bin\wasm-emscripten-finalize" -g --dyncalls-i64 D:\Userware\code\SISE.Riva-MyFork\sise.ria\sise.ria.area.laminacion\sise.laminacion.opensilver\OpenSilverApp\OpenSilverApp.Browser\obj\Release\net7.0\wasm\for-publish\dotnet.wasm -o D:\Userware\code\SISE.Riva-MyFork\sise.ria\sise.ria.area.laminacion\sise.laminacion.opensilver\OpenSilverApp\OpenSilverApp.Browser\obj\Release\net7.0\wasm\for-publish\dotnet.wasm --detect-features' failed (returned 3221226505)
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.0-preview.5.22301.12\Sdk\WasmApp.Native.targets(415,5): Error MSB3073: The command "emcc "@C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\7.0.0-preview.5.22301.12\runtimes\browser-wasm\native\src\emcc-default.rsp" "@C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\7.0.0-preview.5.22301.12\runtimes\browser-wasm\native\src\emcc-link.rsp" "@D:\Userware\code\SISE.Riva-MyFork\sise.ria\sise.ria.area.laminacion\sise.laminacion.opensilver\OpenSilverApp\OpenSilverApp.Browser\obj\Release\net7.0\wasm\for-publish\emcc-link.rsp"" exited with code 1.
                Done executing task "Exec" -- FAILED.
                Done building target "_WasmLinkDotNet" in project "OpenSilverApp.Browser.csproj" -- FAILED.
```
### Reproduction Steps

It builds fine in debug an release

### Expected behavior

should publish successfully 

### Actual behavior

publish fails with the mentioned error.

Please don't ask for binlog unless you let me know how to get one while publishing.
I tried this
msbuild OpenSilverApp.Browser.csproj -bl:msbuild.binlog -p:DeployOnBuild=true -p:publishprofile=release.aot7

and it doesn't publish, but here is the bin I get
[msbuild.zip](https://github.com/dotnet/runtime/files/9034617/msbuild.zip)

### Known Workarounds

arch-wasm
area-build-mono

### Configuration

.net version : 7.0.100-preview.5.22307.18
Windows 10 , 64

### Other information

.NET SDK:
 Version:   7.0.100-preview.5.22307.18
 Commit:    bd8b088037

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-preview.5.22307.18\

global.json file:
  Not found

Host:
  Version:      7.0.0-preview.5.22301.12
  Architecture: x64
  Commit:       425fedc0fb

.NET SDKs installed:
  5.0.407 [C:\Program Files\dotnet\sdk]
  6.0.301 [C:\Program Files\dotnet\sdk]
  7.0.100-preview.5.22307.18 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-preview.5.22303.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-preview.5.22301.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-preview.5.22302.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by radical** [comment]
`emcc` is crashing with `(returned 3221226505)`. Are you running this in a container? It might be running out of memory.

**Comment by ahmed-salem-me** [comment]
@radical , no I'm running it on my PC with 16GB.
I will try to run again while no other apps running and see what happens

**Comment by ahmed-salem-me** [comment]
@radical , we have several people failing to publish with .net version on different machines with different projects, even empty ones using our framework which is based on blazor.
it runs for long hours and doesn't give errors

**Comment by radical** [comment]
@ahmed-salem-me can you run the build with `/v:diag`? That will produce a very verbose log on the console, so you need to redirect that to a file, then share that file.
I'm planning to add some stuff to the process so we can show details of the progress when it takes too long.

**Comment by radical** [comment]
> @ahmed-salem-me can you run the build with `/v:diag`? That will produce a very verbose log on the console, so you need to redirect that to a file, then share that file.

Or use `/fl /flp:v=diag`, and that will generate a `msbuild.log`.

**Comment by ahmed-salem-me** [comment]
@radical here is an output from one machine using /v:diag
[Machine 1-empty-os-app-aot-output.zip](https://github.com/dotnet/runtime/files/9103454/Machine.1-empty-os-app-aot-output.zip)

My machine freezes, but I'll leave it running for a while and send you the output as well

**Comment by ahmed-salem-me** [comment]
@radical , all I know is that is seem to freeze after 30mins or so, it builds fine in minutes, someone mentioned it completed for him after 10 hours.
the opensilver.dll used to publish in aot fine with previous .net versions 
here is another output from a different machine
[Machine 2-empty-os-app-aot-output.zip](https://github.com/dotnet/runtime/files/9106499/Machine.2-empty-os-app-aot-output.zip)

**Comment by radical** [comment]
It's the same `OpenSilver.dll` which it is stuck on. Can you confirm that `mono-aot-cross.exe` is still running when you think it is frozen?
cc @vargaz TL;dr `mono-aot-cross` seems to be taking a lot of time to compile `OpenSilver.dll` from the project here. You can find the logs in the comments above.

**Comment by vargaz** [comment]
How can I get that OpenSilver.dll file ?

**Comment by vargaz** [comment]
Thanks, I can reproduce.
