### ISSUE TITLE
Allow Marshalling SafeHandle as other integer sizes. 

### ISSUE THREAD

**Issue by ThadHouse** [dotnet/runtime#71594]
There are cases where some libraries have native handles that are not IntPtr sized. Currently, there is no way I know of pass a safe handle as anything except and IntPtr, which makes it completely unusable for these cases. 

This might be difficult to add to the existing pinvoke infrastructure, but could be nice to be something supported by the new source generated pinvoke setup.

**Comment by AaronRobinsonMSFT** [comment]
It would be helpful if we could see a concrete example where this would apply. Perhaps an existing unmanaged API that would need benefit from this support?

**Comment by ThadHouse** [comment]
I know the library we ships uses ints because they work better in JNI, since there’s no native int sized type in Java, and we wanted to avoid casting. 

I’ve seen some other libraries with similar reasoning for using fixed ints or longs, rather then something native int size.

**Comment by alexrp** [comment]
> It would be helpful if we could see a concrete example where this would apply.

FDs on Unix systems immediately come to mind for me.

**Comment by jkoritzinsky** [comment]
Now that source-generated interop has moved the SafeHandle marshalling to the [SafeHandleMarshaller type and its nested types](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshalling.safehandlemarshaller-1?view=net-8.0), users can write a custom marshaller that uses this logic internally and only replaces the `ToUnmanaged` and `FromUnmanaged` calls to convert the `nint` handle to the correct handle size.
