### ISSUE TITLE
Too high memory usage triggers oom-reaper

### ISSUE THREAD

**Issue by playingoDEERUX** [dotnet/runtime#71606]
Hello,
our .NET Core application uses 3.2 GB VIRT out of 4 GB available, and along with other processes in our linux system (Debian), that use significantly less, but still a moderate amount of memory like ~1.5gb in total for all misc. apps combined, OOM-reaper just triggered and killed one of our critical server applications.

Is there any way of making .NET Core Apps not use such a huge amount of virtual memory?

**Comment by jkotas** [comment]
If the memory is used by the GC heap, you may want to look at the GC heap limit settings: https://docs.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector#heap-limit

**Comment by EgorBo** [comment]
> @EgorBo Hello! It's running Discord.Net and MySqlConnector to serve as a Discord Bot for verification purposes (it keeps track of some 6 digit code in SQL and interacts with the game server that way) Anyways, instantly upon startup it already seems to occupy 3.2 GB Virtual Memory Space, RES+SHR seems to be way lower - however it seems to have triggered linux’s oom-reaper after a while?!

Thanks for the details but it's still not enough to tell anything, you might try to play with the GC config switches Jan suggested, e.g. try to disable GC server mode to see if that caused the issue - it's know to occupy a lot of memory on systems with many cores. You can also try `dotnet trace` or https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-counters specifcially.
