### ISSUE TITLE
.NET 6 [System.Text.Json] Recursive property in collection type results in JsonException

### ISSUE THREAD

**Issue by rafael-herscovici-cko** [dotnet/runtime#71608]
### Description

The serializer throws a JsonException when trying  to deserialize nested objects.

### Reproduction Steps

```csharp
public record Foo(Bar[] Children);
```

```csharp
public class Bar {
  public string Name { get; set;}
   public Bar[] Children { get; set; }
}
```

### Expected behavior

The serializer should deserialize the objects with no exception being thrown.

### Actual behavior

A JsonException is thrown when a self referencing object is used

```json
System.Text.Json.JsonException: The JSON value could not be converted to Foo. Path: $.children[0].children[0] | LineNumber: 11 | BytePositionInLine: 12.
```

### Regression?

Seems to have been addressed before https://github.com/dotnet/runtime/issues/29413

**Comment by eiriktsarpalis** [comment]
Curious why this got closed?

**Comment by Clockwork-Muse** [comment]
@eiriktsarpalis - They probably found the relevant property on `JsonSerializerOptions`.
