### ISSUE TITLE
error when build mono release/6.0 branch on MacCatalyst os

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#71614]
## build mono use `--os MacCatalyst`
I want build mono+libs on macCatayst platform using: ./build.sh mono+libs --os MacCatalyst
but error occured: 
> ld: building for Mac Catalyst, but linking in .tbd built for iOS

![image](https://user-images.githubusercontent.com/5187024/177160781-ab0aff9f-0dec-42fd-8a21-8960ff02f2bc.png)

## build mono use `--os iOS`: ./build.sh mono+libs --os iOS.
hit the error:
> error: 'system' is unavailable: not available on iOS

>>   /Users/game-netease/dotnet/runtime/src/mono/mono/mini/graph.c:231:7: error: 'system' is unavailable: not available on iOS
          _i = system (com);
               ^
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/stdlib.h:184:6: note: 'system' has been explicitly marked unavailable here
  int      system(const char *) __DARWIN_ALIAS_C(system);
           ^
  1 warning and 1 error generated.

**Comment by am11** [comment]
Does this patch fix/workaround the issue:

```diff
diff --git a/src/mono/mono.proj b/src/mono/mono.proj
index a9fc80619da..647cfbe2318 100644
--- a/src/mono/mono.proj
+++ b/src/mono/mono.proj
@@ -313,7 +313,7 @@
       <_MonoCFLAGS Condition="'$(TargetArchitecture)' == 'arm64'" Include="-arch arm64" />
       <_MonoCXXFLAGS Condition="'$(TargetArchitecture)' == 'arm64'" Include="-arch arm64" />
       <!-- Force running as arm64 even when invoked from an x86 msbuild process -->
-      <_MonoBuildEnv Condition="'$(BuildArchitecture)' == 'arm64'" Include="arch -arch arm64" />
+      <_MonoBuildEnv Condition="'$(BuildArchitecture)' == 'arm64' and '$(HostOS)' != 'MacCatalyst'" Include="arch -arch arm64" />
     </ItemGroup>
     <!-- Mac Catalyst specific options -->
     <ItemGroup Condition="'$(TargetsMacCatalyst)' == 'true'">
```
(if not, try commenting out that line)

I don't have access to Mac Catalyst right now, so it's just a guess. :sweat_smile:

ps: in this state, try to delete `artifacts` directory before the rebuild (otherwise, you might end up with unreliable results)

**Comment by srxqds** [comment]
hi, thank you for reply, but I have tried it, it fails agin with the same reason

**Comment by am11** [comment]
Could you share the logs? `arch -arch arm64` prefix shouldn't be there.

**Comment by srxqds** [comment]
[log.txt](https://github.com/dotnet/runtime/files/9042577/log.txt)

**Comment by am11** [comment]
Thanks, please also post the output of `clang -v`.

**Comment by srxqds** [comment]
> Thanks, please also post the output of `clang -v`.

Apple clang version 13.0.0 (clang-1300.0.27.3)
Target: arm64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by am11** [comment]
Thanks. Does it make a difference if you apply this patch:

(undo the previous one)
```diff
diff --git a/src/mono/mono.proj b/src/mono/mono.proj
index a9fc80619da..789af2d2913 100644
--- a/src/mono/mono.proj
+++ b/src/mono/mono.proj
@@ -320,14 +320,10 @@
       <_MonoCMakeArgs Include="-DCMAKE_SYSTEM_VARIANT=MacCatalyst" />
       <!-- https://gitlab.kitware.com/cmake/cmake/-/issues/20132 -->
       <_MonoCPPFLAGS Include="-Wno-overriding-t-option" />
-      <_MonoCFlags Condition="'$(TargetArchitecture)' == 'arm64'" Include="-target arm64-apple-ios14.2-macabi" />
       <_MonoCFlags Condition="'$(TargetArchitecture)' == 'x64'" Include="-target x86_64-apple-ios13.5-macabi" />
       <_MonoCFLAGS Condition="'$(TargetArchitecture)' == 'arm64'" Include="-arch arm64" />
-      <_MonoCXXFlags Condition="'$(TargetArchitecture)' == 'arm64'" Include="-target arm64-apple-ios14.2-macabi" />
       <_MonoCXXFlags Condition="'$(TargetArchitecture)' == 'x64'" Include="-target x86_64-apple-ios13.5-macabi" />
       <_MonoCXXFLAGS Condition="'$(TargetArchitecture)' == 'arm64'" Include="-arch arm64" />
-      <!-- Force running as arm64 even when invoked from an x86 msbuild process -->
-      <_MonoBuildEnv Condition="'$(BuildArchitecture)' == 'arm64'" Include="arch -arch arm64" />
     </ItemGroup>
     <!-- WASM specific options -->
     <PropertyGroup Condition="'$(TargetsBrowser)' == 'true'">
```
(delete `artifacts` and rebuild)

**Comment by srxqds** [comment]
another error hited:
>> [ 15%] Building C object mono/mini/CMakeFiles/monosgen-objects.dir/__/metadata/class-init.c.o
  /Users/game-netease/dotnet/runtime/src/mono/mono/metadata/w32process-unix-osx.c:75:19: error: use of undeclared identifier 'PROC_PIDPATHINFO_MAXSIZE'
                  gchar path_buf [PROC_PIDPATHINFO_MAXSIZE];
                                  ^
  /Users/game-netease/dotnet/runtime/src/mono/mono/metadata/w32process-unix-osx.c:80:14: error: implicit declaration of function 'proc_pidpath' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                  path_len = proc_pidpath (pid, path_buf, sizeof(path_buf));
                             ^
  /Users/game-netease/dotnet/runtime/src/mono/mono/metadata/w32process-unix-osx.c:109:13: error: use of undeclared identifier 'PROC_PIDPATHINFO_MAXSIZE'
          gchar buf [PROC_PIDPATHINFO_MAXSIZE];
                     ^
  /Users/game-netease/dotnet/runtime/src/mono/mono/metadata/w32process-unix-osx.c:112:8: error: implicit declaration of function 'proc_pidpath' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
          res = proc_pidpath (pid, buf, sizeof (buf));
                ^

**Comment by am11** [comment]
OK, so the configuration errors are fixed. Before we move on to compiler error, I think this patch instead of the above would be better:

```diff
diff --git a/src/mono/mono.proj b/src/mono/mono.proj
index a9fc80619da..9acd5c9abed 100644
--- a/src/mono/mono.proj
+++ b/src/mono/mono.proj
@@ -316,7 +316,7 @@
       <_MonoBuildEnv Condition="'$(BuildArchitecture)' == 'arm64'" Include="arch -arch arm64" />
     </ItemGroup>
     <!-- Mac Catalyst specific options -->
-    <ItemGroup Condition="'$(TargetsMacCatalyst)' == 'true'">
+    <ItemGroup Condition="'$(TargetsMacCatalyst)' == 'true' and '$(HostOS)' != 'MacCatalyst'">
       <_MonoCMakeArgs Include="-DCMAKE_SYSTEM_VARIANT=MacCatalyst" />
       <!-- https://gitlab.kitware.com/cmake/cmake/-/issues/20132 -->
       <_MonoCPPFLAGS Include="-Wno-overriding-t-option" />
```

> PROC_PIDPATHINFO_MAXSIZE

It was removed in 26372410d43ebb19220cce868a6f87186f88b2ce. Please pull the latest main and try to build that instead.

```sh
$ git remote add dotnet https://github.com/dotnet/runtime
$ git fetch --all
$ git reset --hard dotnet/main
$ rm -rf artifacts
# apply the aforementioned patch and rebuild
```

**Comment by srxqds** [comment]
I have tried this:
>> diff --git a/src/mono/mono.proj b/src/mono/mono.proj
index a9fc80619da..9acd5c9abed 100644
--- a/src/mono/mono.proj
+++ b/src/mono/mono.proj
@@ -316,7 +316,7 @@
       <_MonoBuildEnv Condition="'$(BuildArchitecture)' == 'arm64'" Include="arch -arch arm64" />
     </ItemGroup>
     
-    <ItemGroup Condition="'$(TargetsMacCatalyst)' == 'true'">
+    <ItemGroup Condition="'$(TargetsMacCatalyst)' == 'true' and '$(HostOS)' != 'MacCatalyst'">
       <_MonoCMakeArgs Include="-DCMAKE_SYSTEM_VARIANT=MacCatalyst" />
       
       <_MonoCPPFLAGS Include="-Wno-overriding-t-option" />

it fails again.

**Comment by srxqds** [comment]
> OK, so the configuration errors are fixed. Before we move on to compiler error, I think this patch instead of the above would be better:
> 
> ```diff
> diff --git a/src/mono/mono.proj b/src/mono/mono.proj
> index a9fc80619da..9acd5c9abed 100644
> --- a/src/mono/mono.proj
> +++ b/src/mono/mono.proj
> @@ -316,7 +316,7 @@
>        <_MonoBuildEnv Condition="'$(BuildArchitecture)' == 'arm64'" Include="arch -arch arm64" />
>      </ItemGroup>
>      
> -    <ItemGroup Condition="'$(TargetsMacCatalyst)' == 'true'">
> +    <ItemGroup Condition="'$(TargetsMacCatalyst)' == 'true' and '$(HostOS)' != 'MacCatalyst'">
>        <_MonoCMakeArgs Include="-DCMAKE_SYSTEM_VARIANT=MacCatalyst" />
>        
>        <_MonoCPPFLAGS Include="-Wno-overriding-t-option" />
> ```
> 
> > PROC_PIDPATHINFO_MAXSIZE
> 
> It was removed in [2637241](https://github.com/dotnet/runtime/commit/26372410d43ebb19220cce868a6f87186f88b2ce). Please pull the latest main and try to build that instead.
> 
> ```shell
> $ git remote add dotnet https://github.com/dotnet/runtime
> $ git fetch --all
> $ git reset --hard dotnet/main
> $ rm -rf artifacts
> # apply the aforementioned patch and rebuild
> ```

the https://github.com/dotnet/runtime/commit/26372410d43ebb19220cce868a6f87186f88b2ce pr is so big changed that I can merge to release/6.0 easy.

**Comment by srxqds** [comment]
you can check here: https://developer.apple.com/forums/thread/100617

**Comment by srxqds** [comment]
> I can't reproduce this on an M1 MacBook on the `main` branch, it builds fine there for me. Can you make sure your shell is also arm64?

yeah, you can found the TARGET_ARCH=arm64
can you try on release/6.0 branch?

**Comment by akoeplinger** [comment]
@srxqds I tried on release/6.0 and it works too there for me.

**Comment by akoeplinger** [comment]
As discussed on Discord, please try upgrading to the latest Xcode. Maybe something in Xcode is broken.

**Comment by srxqds** [comment]
I have upgrade Xcode to 13.4.1, build fails again with the same error.

**Comment by srxqds** [comment]
it is caused by the setting the `sdkroot` env.
thank you @akoeplinger  help figure out the problem.
