### ISSUE TITLE
GC slow since .net 7 Preview 5/6/7 somewhere. 

### ISSUE THREAD

**Issue by tactical-drone** [dotnet/runtime#71627]
### Description
I run cluster tests. This consists of a AMD Ryzen 9 3950X 16 core processor with 64Gb ram running a bunch of nodes sending messages to each other over _localhost TCP_. The application framework is optimized to induce as little GC pressure as possible. This is in fact the point of the framework and this exercise, to see what the GC does with many threads casing very little GC pressure but cumulatively at high rates. 

When using perfview, the alloc that happens the most is on the class `Task`.  All the other allocs that cause GC pressure have been _heapified_ by the framework.

### Configuration

* Which version of .NET is the code running on? **7.0.100-preview.7.22354.3**
* What OS version, and what distro if applicable? **Windows 11**
* What is the architecture (x64, x86, ARM, ARM64)? **AMD Ryzen 9 3950X**
* If relevant, what are the specs of the machine? **Asus x570f with 64Gb Ram**

### Regression?

Ever since around preview 5/6/7 (it felt like it got progressively worse) my tests started experiencing problems. At first the application runs fine, as it is busy injecting nodes into the cluster. At around node 200 (out of 700) the cluster starts to bog down. The logs pump in 1 second intervals, then freezes for 1 second then pumps again for 1 second. It's like the GC goes into overdrive and collects every 1 second pausing the application for a second. If I go into perfview it says that my application is 99% busy with GC. The only object being malloced in mass is `System.Threading.Tasks.Task`. What is strange is that once it goes into this mode, these pause timings are almost exact 1 second pumps. If you leave the app to continue, although making progress super slow, eventually it goes out of this state and suddenly the app starts working as normal again, catching up on things that failed because there was simply no CPU given to userspace. 

### Reproduce

Clone and run https://github.com/tactical-drone/zero and execute `zero.sync` after unsetting those settings defined below.

### Analysis

After adding these settings to the GC, the problem goes away:

```
<ServerGarbageCollection>true</ServerGarbageCollection>
<ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
<GCHeapCount>16</GCHeapCount>
<GCCpuGroup>0</GCCpuGroup>
<GCNoAffinitize>false</GCNoAffinitize>
<GCLOHThreshold>120000</GCLOHThreshold>
<GCConserveMemory>7</GCConserveMemory>
```

I don't expect any fixes, but if there were changes this is how it is affecting us right now. The reason why I run bleeding edge is because I am still in RnD mode and this work is earmarked for long term dominance. Therefor at this stage I test it against bleeding edge reporting any strange things that might come up.

**Comment by EgorBo** [comment]
As far as I know, the most significant change in GC over the last release was gc regions feature, you might try your app with the workaround described here https://github.com/dotnet/runtime/pull/59283 to test if it's the root cause.

**Comment by tactical-drone** [comment]
> 

Looking into this, The timing is roughly the same. My issues started at the end of preview 4 though. I will install .net6 and see what is what. 

Thanks for the info.

**Comment by EgorBo** [comment]
> > 
> 
> Looking into this, The timing is roughly the same. My issues started at the end of preview 4 though. I will install .net6 and see what is what.
> 
> Thanks for the info.

It was enabled, then disabled due to issues and enabled a while after again

**Comment by tactical-drone** [comment]
These stats are generated after all nodes have started, then by typing `loadTest` in the console a waiting a while for heap allocs to settle. 

# Stats with server gc:

 </HEAD><BODY><H3><A name="Stats_39384"><FONT color="blue">GC Stats for Process 39384: Process(39384)</FONT><A></A></H3><A></A><UL><A> <LI>Runtime Version: V 7.0.22.32905</LI><LI>CLR Startup Flags: 8392707</LI><LI>Total CPU Time: 0 msec</LI><LI>Total GC CPU Time: 0 msec</LI><LI>Total Allocs  : 22,386.372 MB</LI><LI>GC CPU MSec/MB Alloc : 0.000 MSec/MB</LI><LI>Total GC Pause: 816.7 msec</LI><LI>% Time paused for Garbage Collection: 2.8%</LI><LI>% CPU Time spent Garbage Collecting: NaN%</LI><LI>Max GC Heap Size: 5,647.597 MB</LI></A><LI><A> <A href="file:///C:/Users/skyca/AppData/Local/Temp/PerfView/zero.sync.exe_20220705_114620_ec62d24f.usersGuide.html#UnderstandingGCPerf">GC Perf Users Guide</A></LI><LI><A href="file:///C:/Users/skyca/AppData/Local/Temp/PerfView/zero.sync.exe_20220705_114620_ec62d24f.GCStats.html#Events_Pause_39384">GCs that &gt; 200 msec Events</A></LI><LI><A href="file:///C:/Users/skyca/AppData/Local/Temp/PerfView/zero.sync.exe_20220705_114620_ec62d24f.GCStats.html#LOH_allocation_Pause_39384">LOH allocation pause (due to background GC) &gt; 200 msec Events</A></LI><LI><A href="file:///C:/Users/skyca/AppData/Local/Temp/PerfView/zero.sync.exe_20220705_114620_ec62d24f.GCStats.html#Events_Gen2_39384">GCs that were Gen2</A></LI><LI><A href="file:///C:/Users/skyca/AppData/Local/Temp/PerfView/zero.sync.exe_20220705_114620_ec62d24f.GCStats.html#Events_39384">Individual GC Events</A> </LI><UL><LI><A href="command:excel/39384">View in Excel</A></LI></UL><LI><A href="command:excel/perGeneration/39384">Per Generation GC Events in Excel</A></LI><LI><A href="command:xml/39384">Raw Data XML file (for debugging)</A></LI><LI><A href="file:///C:/Users/skyca/AppData/Local/Temp/PerfView/zero.sync.exe_20220705_114620_ec62d24f.GCStats.html#Finalization_39384">Finalized Objects</A> </LI><UL><LI><A href="command:excelFinalization/39384">View in Excel</A></LI></UL><UL><LI><A href="file:///C:/Users/skyca/AppData/Local/Temp/PerfView/zero.sync.exe_20220705_114620_ec62d24f.usersGuide.html#UnderstandingFinalization">Finalization Perf Users Guide</A></LI></UL></UL><CENTER><TABLE border="1"><TBODY><TR><TH align="Center" colspan="12">GC Rollup By Generation</TH></TR><TR><TH align="Center" colspan="12">All times are in msec.</TH></TR><TR><TH>Gen</TH><TH>Count</TH><TH>Max<BR>Pause</TH><TH>Max<BR>Peak MB</TH><TH>Max Alloc<BR>MB/sec</TH><TH>Total<BR>Pause</TH><TH>Total<BR>Alloc MB</TH><TH>Alloc MB/<BR>MSec GC</TH><TH>Survived MB/<BR>MSec GC</TH><TH>Mean<BR>Pause</TH><TH>Induced</TH></TR><TR><TD align="Center">ALL</TD><TD align="Center">59</TD><TD align="Center">82.8</TD><TD align="Center">5,647.6</TD><TD align="Center">832.955</TD><TD align="Center">816.7</TD><TD align="Center">22,386.4</TD><TD align="Center">27.4</TD><TD align="Center">∞</TD><TD align="Center">13.8</TD><TD align="Center">0</TD></TR><TR bgcolor="#bdedff"><TD align="Center">0</TD><TD align="Center">0</TD><TD align="Center">0.0</TD><TD align="Center">0.0</TD><TD align="Center">0.000</TD><TD align="Center">0.0</TD><TD align="Center">0.0</TD><TD align="Center">0.0</TD><TD align="Center">NaN</TD><TD align="Center">NaN</TD><TD align="Center">0</TD></TR><TR bgcolor="#82caff"><TD align="Center">1</TD><TD align="Center">59</TD><TD align="Center">82.8</TD><TD align="Center">5,647.6</TD><TD align="Center">832.955</TD><TD align="Center">816.7</TD><TD align="Center">22,386.4</TD><TD align="Center">0.0</TD><TD align="Center">∞</TD><TD align="Center">13.8</TD><TD align="Center">0</TD></TR><TR bgcolor="#56a5ec"><TD align="Center">2</TD><TD align="Center">0</TD><TD align="Center">0.0</TD><TD align="Center">0.0</TD><TD align="Center">0.000</TD><TD align="Center">0.0</TD><TD align="Center">0.0</TD><TD align="Center">0.0</TD><TD align="Center">NaN</TD><TD align="Center">NaN</TD><TD align="Center">0</TD></TR></TBODY></TABLE></CENTER></BODY></HTML>GC Stats for Process 39384: Process(39384)
 
# stock gc:

 </HEAD><BODY><H3><A name="Stats_39848"><FONT color="blue">GC Stats for Process 39848: Process(39848)</FONT><A></A></H3><A></A><UL><A> <LI>Runtime Version: V 7.0.22.32905</LI><LI>CLR Startup Flags: 8388611</LI><LI>Total CPU Time: 0 msec</LI><LI>Total GC CPU Time: 0 msec</LI><LI>Total Allocs  : 478.777 MB</LI><LI>GC CPU MSec/MB Alloc : 0.000 MSec/MB</LI><LI>Total GC Pause: 24,005.9 msec</LI><LI>% Time paused for Garbage Collection: 77.7%</LI><LI>% CPU Time spent Garbage Collecting: NaN%</LI><LI>Max GC Heap Size: 2,798.207 MB</LI></A><LI><A> <A href="file:///C:/Users/skyca/AppData/Local/Temp/PerfView/zero.sync.exe_20220705_115801_803de15d.usersGuide.html#UnderstandingGCPerf">GC Perf Users Guide</A></LI><LI><A href="file:///C:/Users/skyca/AppData/Local/Temp/PerfView/zero.sync.exe_20220705_115801_803de15d.GCStats.html#Events_Pause_39848">GCs that &gt; 200 msec Events</A></LI><LI><A href="file:///C:/Users/skyca/AppData/Local/Temp/PerfView/zero.sync.exe_20220705_115801_803de15d.GCStats.html#LOH_allocation_Pause_39848">LOH allocation pause (due to background GC) &gt; 200 msec Events</A></LI><LI><A href="file:///C:/Users/skyca/AppData/Local/Temp/PerfView/zero.sync.exe_20220705_115801_803de15d.GCStats.html#Events_Gen2_39848">GCs that were Gen2</A></LI><LI><A href="file:///C:/Users/skyca/AppData/Local/Temp/PerfView/zero.sync.exe_20220705_115801_803de15d.GCStats.html#Events_39848">Individual GC Events</A> </LI><UL><LI><A href="command:excel/39848">View in Excel</A></LI></UL><LI><A href="command:excel/perGeneration/39848">Per Generation GC Events in Excel</A></LI><LI><A href="command:xml/39848">Raw Data XML file (for debugging)</A></LI><LI><A href="file:///C:/Users/skyca/AppData/Local/Temp/PerfView/zero.sync.exe_20220705_115801_803de15d.GCStats.html#Finalization_39848">Finalized Objects</A> </LI><UL><LI><A href="command:excelFinalization/39848">View in Excel</A></LI></UL><UL><LI><A href="file:///C:/Users/skyca/AppData/Local/Temp/PerfView/zero.sync.exe_20220705_115801_803de15d.usersGuide.html#UnderstandingFinalization">Finalization Perf Users Guide</A></LI></UL></UL><CENTER><TABLE border="1"><TBODY><TR><TH align="Center" colspan="12">GC Rollup By Generation</TH></TR><TR><TH align="Center" colspan="12">All times are in msec.</TH></TR><TR><TH>Gen</TH><TH>Count</TH><TH>Max<BR>Pause</TH><TH>Max<BR>Peak MB</TH><TH>Max Alloc<BR>MB/sec</TH><TH>Total<BR>Pause</TH><TH>Total<BR>Alloc MB</TH><TH>Alloc MB/<BR>MSec GC</TH><TH>Survived MB/<BR>MSec GC</TH><TH>Mean<BR>Pause</TH><TH>Induced</TH></TR><TR><TD align="Center">ALL</TD><TD align="Center">59</TD><TD align="Center">866.7</TD><TD align="Center">2,798.2</TD><TD align="Center">2,865.501</TD><TD align="Center">24,005.9</TD><TD align="Center">478.8</TD><TD align="Center">0.0</TD><TD align="Center">∞</TD><TD align="Center">406.9</TD><TD align="Center">0</TD></TR><TR bgcolor="#bdedff"><TD align="Center">0</TD><TD align="Center">31</TD><TD align="Center">26.1</TD><TD align="Center">2,798.2</TD><TD align="Center">2,575.107</TD><TD align="Center">698.8</TD><TD align="Center">251.6</TD><TD align="Center">1.5</TD><TD align="Center">∞</TD><TD align="Center">22.5</TD><TD align="Center">0</TD></TR><TR bgcolor="#82caff"><TD align="Center">1</TD><TD align="Center">0</TD><TD align="Center">0.0</TD><TD align="Center">0.0</TD><TD align="Center">0.000</TD><TD align="Center">0.0</TD><TD align="Center">0.0</TD><TD align="Center">0.0</TD><TD align="Center">NaN</TD><TD align="Center">NaN</TD><TD align="Center">0</TD></TR><TR bgcolor="#56a5ec"><TD align="Center">2</TD><TD align="Center">28</TD><TD align="Center">866.7</TD><TD align="Center">2,797.4</TD><TD align="Center">2,865.501</TD><TD align="Center">23,307.2</TD><TD align="Center">227.2</TD><TD align="Center">48.7</TD><TD align="Center">∞</TD><TD align="Center">832.4</TD><TD align="Center">0</TD></TR></TBODY></TABLE></CENTER></BODY></HTML>GC Stats for Process 39848: Process(39848)

**Comment by mrsharm** [comment]
Hi @tactical-drone, would it be possible to provide us with the traces here? It'll be helpful to have them to get a wholistic picture of the regression you are experiencing. Thanks!

**Comment by Maoni0** [comment]
thanks for running on the bleeding edge and helping us discover problems, @tactical-drone!

it'd be great if you could please clarify a couple of things -

what did you mean by "stock gc"? meaning you don't have these set?

```
<ServerGarbageCollection>true</ServerGarbageCollection>
<ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
<GCHeapCount>16</GCHeapCount>
<GCCpuGroup>0</GCCpuGroup>
<GCNoAffinitize>false</GCNoAffinitize>
<GCLOHThreshold>120000</GCLOHThreshold>
<GCConserveMemory>7</GCConserveMemory>
```

when you said "get slower", presumably you meant with the "stock gc" you saw the speed at which your app ran got slower with (approximately) each preview build since preview 5 (I'm not sure what "at the end of preview 4" meant, does that mean you were building the runtime your time and you started observing the slowness when you built the runtime at the end of preview 4)? how much slower would you say you observed? and did you observe the same slowness or did it get progressively worse with each preview build?

**Comment by tactical-drone** [comment]
> Hi @tactical-drone, would it be possible to provide us with the traces here? It'll be helpful to have them to get a wholistic picture of the regression you are experiencing. Thanks!

That is fascinating! But this should not be. There is a discrepancy in the way you ran the test and I ran the test then. I am 100% positive something is not right. Did you take this reading while the cluster was "booting"? Or after it booted and you ran `loadTest`? I would love to know. Regardless let me run some more tests and see where you got those test results from. I will rerun my tests. 

@Maoni0 Correct. I meant stock GC as the GC that comes out of the box, hence those settings commented out.

**Comment by tactical-drone** [comment]
@mrsharm I have constructed a new test that is not so confusing. This test is different that the one above, but still shows the problem. To be clear, I run tests during one of 2 stages normally. Either when the cluster boots or when I run `loadTest`. Lets ignore `loadTest` for now because the problem is visible with the eye on cluster boot. 

I collect stats with `dotnet-trace collect -p 28684 --duration 00:00:30 --profile gc-verbose`

 </HEAD><BODY><H2>GCStats</H2><H3><A name="Stats_28684"><FONT color="blue">GC Stats for Process 28684: Process(28684)</FONT><A></A></H3><A></A><UL><A> <LI>Runtime Version: V 7.0.22.32905</LI><LI>CLR Startup Flags: 8388611</LI><LI>Total CPU Time: 0 msec</LI><LI>Total GC CPU Time: 0 msec</LI><LI>Total Allocs  : 975.257 MB</LI><LI>GC CPU MSec/MB Alloc : 0.000 MSec/MB</LI><LI>Total GC Pause: 24,077.3 msec</LI><LI>% Time paused for Garbage Collection: 80.7%</LI><LI>% CPU Time spent Garbage Collecting: NaN%</LI><LI>Max GC Heap Size: 1,718.977 MB</LI></A><LI><A> <A href="file:///C:/Users/skyca/AppData/Local/Temp/PerfView/zero.sync.exe_20220706_092916_12af20eb.usersGuide.html#UnderstandingGCPerf">GC Perf Users Guide</A></LI><LI><A href="file:///C:/Users/skyca/AppData/Local/Temp/PerfView/zero.sync.exe_20220706_092916_12af20eb.GCStats.html#Events_Pause_28684">GCs that &gt; 200 msec Events</A></LI><LI><A href="file:///C:/Users/skyca/AppData/Local/Temp/PerfView/zero.sync.exe_20220706_092916_12af20eb.GCStats.html#LOH_allocation_Pause_28684">LOH allocation pause (due to background GC) &gt; 200 msec Events</A></LI><LI><A href="file:///C:/Users/skyca/AppData/Local/Temp/PerfView/zero.sync.exe_20220706_092916_12af20eb.GCStats.html#Events_Gen2_28684">GCs that were Gen2</A></LI><LI><A href="file:///C:/Users/skyca/AppData/Local/Temp/PerfView/zero.sync.exe_20220706_092916_12af20eb.GCStats.html#Events_28684">Individual GC Events</A> </LI><UL><LI><A href="command:excel/28684">View in Excel</A></LI></UL><LI><A href="command:excel/perGeneration/28684">Per Generation GC Events in Excel</A></LI><LI><A href="command:xml/28684">Raw Data XML file (for debugging)</A></LI><LI><A href="file:///C:/Users/skyca/AppData/Local/Temp/PerfView/zero.sync.exe_20220706_092916_12af20eb.GCStats.html#Finalization_28684">Finalized Objects</A> </LI><UL><LI><A href="command:excelFinalization/28684">View in Excel</A></LI></UL><UL><LI><A href="file:///C:/Users/skyca/AppData/Local/Temp/PerfView/zero.sync.exe_20220706_092916_12af20eb.usersGuide.html#UnderstandingFinalization">Finalization Perf Users Guide</A></LI></UL></UL><CENTER><TABLE border="1"><TBODY><TR><TH align="Center" colspan="12">GC Rollup By Generation</TH></TR><TR><TH align="Center" colspan="12">All times are in msec.</TH></TR><TR><TH>Gen</TH><TH>Count</TH><TH>Max<BR>Pause</TH><TH>Max<BR>Peak MB</TH><TH>Max Alloc<BR>MB/sec</TH><TH>Total<BR>Pause</TH><TH>Total<BR>Alloc MB</TH><TH>Alloc MB/<BR>MSec GC</TH><TH>Survived MB/<BR>MSec GC</TH><TH>Mean<BR>Pause</TH><TH>Induced</TH></TR><TR><TD align="Center">ALL</TD><TD align="Center">125</TD><TD align="Center">485.3</TD><TD align="Center">1,719.0</TD><TD align="Center">3,460.018</TD><TD align="Center">24,077.3</TD><TD align="Center">975.3</TD><TD align="Center">0.0</TD><TD align="Center">∞</TD><TD align="Center">192.6</TD><TD align="Center">0</TD></TR><TR bgcolor="#bdedff"><TD align="Center">0</TD><TD align="Center">60</TD><TD align="Center">31.6</TD><TD align="Center">1,714.4</TD><TD align="Center">3,401.525</TD><TD align="Center">1,374.0</TD><TD align="Center">466.8</TD><TD align="Center">1.4</TD><TD align="Center">∞</TD><TD align="Center">22.9</TD><TD align="Center">0</TD></TR><TR bgcolor="#82caff"><TD align="Center">1</TD><TD align="Center">12</TD><TD align="Center">21.0</TD><TD align="Center">1,710.6</TD><TD align="Center">1,686.043</TD><TD align="Center">179.5</TD><TD align="Center">94.9</TD><TD align="Center">0.2</TD><TD align="Center">∞</TD><TD align="Center">15.0</TD><TD align="Center">0</TD></TR><TR bgcolor="#56a5ec"><TD align="Center">2</TD><TD align="Center">53</TD><TD align="Center">485.3</TD><TD align="Center">1,719.0</TD><TD align="Center">3,460.018</TD><TD align="Center">22,523.8</TD><TD align="Center">413.6</TD><TD align="Center">23.1</TD><TD align="Center">∞</TD><TD align="Center">425.0</TD><TD align="Center">0</TD></TR></TBODY></TABLE></CENTER></BODY></HTML>

1. Execute zero.sync (with workstation)
2. Wait till nodes around ~400 are adding. You will notice the log starts to pump in intervals
3.  Execute `dotnet-trace collect -p 28684 --duration 00:00:30 --profile gc-verbose`
4. Observe those pause times are massive.

**Comment by tactical-drone** [comment]
@mrsharm Another interesting thing that happens. When the logs starts to pulse like that and you enter `log trace` in the console.... the application stucks for like 10 seconds then suddenly starts pumping at full speed. Setting `log info` on the console you would notice that the pulsing log issue is gone. It's like asking log4net to spam logs kicks the GC out of this mode.

**Comment by tactical-drone** [comment]
Another fun test for you GC guys, after the cluster has been spamming enter `zero` in the console and watch the cluster tear itself down. Proceed with spamming `gc` in the console a couple of times and observe how .net garbage collection performs. I am happy to reports since .net 5 that you guys (and the 3rd libraries that I use )have made significant gains in this area. Good job men!

**Comment by mangod9** [comment]
ok thanks for the update, so assume you mean the regressions were not introduced in preview5+ ?

**Comment by tactical-drone** [comment]
> ok thanks for the update, so assume you mean the regressions were not introduced in preview5+ ?

Correct.

At the same time I was doing massive reshufflings and at one critical junction I was not returning memory to the heap causing massive GC pressure.

**Comment by tactical-drone** [comment]
I dont have electricity for 2h.

**Comment by tactical-drone** [comment]
Wait. But the conclusion could be pretty hilarious. The GC is so good it hides my fundamental memory leak. The server mode is just unbelievable. Holy 🤫

**Comment by tactical-drone** [comment]
Ok, now that I have some electricity. 

I reran the cluster bootstrap in workstation mode, no problems. In my producer consumer pattern the Job carrier was not being returned to the heap, causing an alloc per job. At 2.5 million packets per second, how on earth did it even run. This server GC mode has me moving around in my seat! It is literally able to withstand a deliberate attack. Where did it come from? Absolutely astonishing.

**Comment by Maoni0** [comment]
Server GC has existed since .NET Framework 1.0 (obviously we continued to make improvement to it in every release) 🙂 there are a few reasons why it gives so much boost in performance -

+ you have 16 GC threads to collect instead of 1
+ you also do fewer GCs because the process is allocating on 16 heaps simultaneously instead of 1. we also allow bigger allocation budget in Server GC _per heap_ than Workstation GC - as you can see in Server GC mode you are only doing 6 GCs vs 125 in Workstation. and you allocated way less in WKS mode (~1GB vs 7.7GB in SVR)

also I noticed you collected traces with gc-verbose - this is pretty high overhead. unless you actually make use of the verbose level of events you should never collect with this arg. instead use gc-collect which is very low overhead. this means you are collecting way more events both in and outside of each GC. this is at least part of the reason why your % time in GC diffs so much between SVR and WKS GC whereas when @mrsharm ran it he did not see nearly as much difference.

**Comment by tactical-drone** [comment]
@Maoni0 Thanks for the advice! I will definitely adjust my trace strategy. Had I used this server mode from the beginning I might not have developed `zero.core` which basically introduces memory management and teardown ticks I developed in C++ over the years to .net making the GC a lender of last resort. 

The progressively getting slow part is then because I introduced those turbo bits from the framework causing an overall speedup that eventually saturates the GC workstation mode. But server mode laughs it off. Fascinating data.

**Comment by Maoni0** [comment]
this looks very cool. how would a user make use of this data? is it streaming data from a bunch of IoT devices? is the repo you shared a scaled down version of your app?

**Comment by tactical-drone** [comment]
> 

Basically, IRL it would work as follows.

Every user that runs a node will point their node to an unity project that runs on a workstation (or on the web?). You will then generate such an animation from all their combined effort. 

For now this unity project is in very early stages, and not hosted publicly yet because I still need to separate out the code I bought and used to draw those lines. (I use unity fast line renderer). This code is not supposed to be public. Once I separate it out I will host the project. 

>  is it streaming data from a bunch of IoT devices?

Correct. If all devices in the cluster opt to send their data to the renderer, you will get this picture even if you don't run all nodes on localhost. If some nodes don't offer their data, this mode has to be RnD still. You would have to create gap fillers.

**Comment by Maoni0** [comment]
thanks for the explanation. I wish your project much success! I also wanted to see if this is something we could take as a test case so we can use it as one of the scenarios to validate perf changes (projects that are self contained and easy to run yet represent real customer scenarios aren't that easy to come by so I always keep an eye for them). but it sounds like the answer to that is no.
