### ISSUE TITLE
double Microsoft.UI.Input.PointerPoint.Position should be int

### ISSUE THREAD

**Issue by Padanian** [dotnet/runtime#71665]
### Description

Consider the following

```
` 
        Microsoft.UI.Input.PointerPoint ptrPt;
        IntPtr hWnd;
        WindowId windowId;
        AppWindow appWindow;

        private void Grid_PointerMoved(object sender, PointerRoutedEventArgs e)
        {
             hWnd = WinRT.Interop.WindowNative.GetWindowHandle(this);
             windowId = Microsoft.UI.Win32Interop.GetWindowIdFromWindow(hWnd);
             appWindow = Microsoft.UI.Windowing.AppWindow.GetFromWindowId(windowId);
             ptrPt = e.GetCurrentPoint(null);

             eDiff.X =  appWindow.Position.X + (int)ptrPt.Position.X;
             eDiff.Y =  appWindow.Position.Y + (int)ptrPt.Position.Y;

             // Set the new point
             appWindow.Move(eDiff);

        }

`
```

Is there any good reason why appWindow.Position.X is int while the pointer position is double?

### Reproduction Steps

See example above

### Expected behavior

Pointer should be int.

### Actual behavior

Microsoft.UI.Input.PointerPoint.Position is double

### Regression?

No

### Configuration

.NET SDK  Version:   6.0.301
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.301\

**Comment by Padanian** [comment]
> I couldn't figure out the best area label to add to this issue. If you have write-permissions please help me learn by adding exactly one [area label](https://github.com/dotnet/runtime/blob/master/docs/area-owners.md).

None of those

**Comment by jkotas** [comment]
This repo is not the right place to report WinUI issues. Could you please open this issue in https://github.com/microsoft/microsoft-ui-xaml/ repo instead?
