### ISSUE TITLE
Widespread regressions after #71498 (Spans to use ref fields)

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#71667]
We're seeing a lot of perf regressions (large reports in https://github.com/dotnet/perf-autofiling-issues/issues/6587 and https://github.com/dotnet/perf-autofiling-issues/issues/6588) due to https://github.com/dotnet/runtime/pull/71498

Example of a regression:
![image](https://user-images.githubusercontent.com/523221/177400616-48d32816-177d-41e0-a2c5-f978d208d53b.png)

@DrewScoggins noticed a similar picture on TE:
![image](https://user-images.githubusercontent.com/523221/177400702-39a1cb7c-3609-49fc-addf-4fc6d36d12db.png)

Codegen example:
```csharp
Span<byte> Test(byte[] array) => array;
```
Before https://github.com/dotnet/runtime/pull/71498:
```asm
; Method Program:Test(System.Byte[]):System.Span`1[Byte]:this
G_M42296_IG01:
G_M42296_IG02:
       test     r8, r8
       je       SHORT G_M42296_IG06
G_M42296_IG03:
       lea      rcx, bword ptr [r8+16]
       mov      r8d, dword ptr [r8+8]
G_M42296_IG04:
       mov      bword ptr [rdx], rcx
       mov      dword ptr [rdx+8], r8d
       mov      rax, rdx
G_M42296_IG05:
       ret      
G_M42296_IG06:
       xor      rcx, rcx
       xor      r8d, r8d
       jmp      SHORT G_M42296_IG04
; Total bytes of code: 31
```
After #71498:
```asm
; Method Program:Test(System.Byte[]):System.Span`1[Byte]:this
G_M42296_IG01:
       push     rdi
       push     rsi
       push     rbx
       sub      rsp, 16
       vzeroupper 
       mov      rbx, rdx
G_M42296_IG02:
       vxorps   xmm0, xmm0
       vmovdqu  xmmword ptr [rsp], xmm0
       test     r8, r8
       je       SHORT G_M42296_IG06
G_M42296_IG03:
       lea      rax, bword ptr [r8+16]
       mov      bword ptr [rsp], rax
       mov      eax, dword ptr [r8+8]
       mov      dword ptr [rsp+08H], eax
G_M42296_IG04:
       mov      rdi, rbx
       lea      rsi, bword ptr [rsp]
       call     CORINFO_HELP_ASSIGN_BYREF
       movsq    
       mov      rax, rbx
G_M42296_IG05:
       add      rsp, 16
       pop      rbx
       pop      rsi
       pop      rdi
       ret      
G_M42296_IG06:
       vxorps   xmm0, xmm0
       vmovdqu  xmmword ptr [rsp], xmm0
       jmp      SHORT G_M42296_IG04
; Total bytes of code: 79
```
Obviously, looks like a JIT issue that wasn't ready for that change, the question is - is it fixable in a short term..

/cc @tannergooding @kunalspathak @DrewScoggins @AaronRobinsonMSFT @dotnet/jit-contrib

**Comment by tannergooding** [comment]
I think the PR in general is still fairly critical to properly vetting and shipping `ref fields` in .NET 7/C# 11 and so it should stay in with a planned fix, unless something egregious limits that.

It looks like this is likely coming down to two main points:
1. We now have a call `call     CORINFO_HELP_ASSIGN_BYREF` in the midst which will add several cycles, potentially cause spilling/etc
2. We now have zeroing where we didn't before `vxorps   xmm0, xmm0; vmovdqu  xmmword ptr [rsp], xmm0`. This is potentially due to the field being a `TYP_BYREF` and the normal expectation being that GC tracked types always require zeroing

CC. @AaronRobinsonMSFT as requested

**Comment by EgorBo** [comment]
For history: we also tried to introduce `int __padding;` field in Span and changing `int _length` to `nint _length` to make spans "without holes" and it even worked 😄 (_discussed in the Discord channel_)
