### ISSUE TITLE
Create minidump with nativeaot

### ISSUE THREAD

**Issue by AhmedZero** [dotnet/runtime#71666]
### Discussed in https://github.com/dotnet/runtime/discussions/71555

<div type='discussions-op-text'>

<sup>Originally posted by **AhmedZero** July  1, 2022</sup>
Is there any way to create minidump works with NativeAOT?
because Microsoft.Diagnostics.NETCore.Client API doesn't work with NativeAOT.</div>

**Comment by hoyosjs** [comment]
Since NativeAOT works as a native app, if you are on windows you can call [minidumpwritedump](https://docs.microsoft.com/en-us/windows/win32/api/minidumpapiset/nf-minidumpapiset-minidumpwritedump) on the process or use a utility like procdump.

**Comment by AhmedZero** [comment]
I use SetUnhandledExceptionFilter and MiniDumpWriteDump and minidump doesn't create.
```C#
   public static unsafe int MyUnhandledExceptionFilter(EXCEPTION_POINTERS* ExceptionInfo)
        {
            SafeFileHandle hFile = CreateFile(
                                 "minidump2.dmp",
                                 FILE_ACCESS_FLAGS.FILE_GENERIC_READ | FILE_ACCESS_FLAGS.FILE_GENERIC_WRITE,
                                 FILE_SHARE_MODE.FILE_SHARE_WRITE,
                                 null,
                                 FILE_CREATION_DISPOSITION.CREATE_ALWAYS,
                                 FILE_FLAGS_AND_ATTRIBUTES.FILE_ATTRIBUTE_NORMAL,
                                 null
                             );
            MINIDUMP_EXCEPTION_INFORMATION mei = new();
            mei.ThreadId = GetCurrentThreadId();
            mei.ClientPointers = false;
            mei.ExceptionPointers = ExceptionInfo;
            MiniDumpWriteDump(
                GetCurrentProcess_SafeHandle(),
                GetCurrentProcessId(),
                hFile,
                MINIDUMP_TYPE.MiniDumpNormal,
                mei,
                null,
               null);

            return 1;
        }
        public unsafe static void Main(string[] args)
        {
            SetUnhandledExceptionFilter(MyUnhandledExceptionFilter);
            int* x = (int*)0;
            *x = 0;

        }
```

**Comment by hoyosjs** [comment]
Usually this must be done out of process. If you just want to get a dump due to unhandled exceptions, then https://docs.microsoft.com/en-us/sysinternals/downloads/procdump with the `-i -ma` flags could help here.

**Comment by AhmedZero** [comment]
thanks.

**Comment by AhmedZero** [comment]
I have a problem with an access violation exception and can't handle it, so I ask for anyway with the same process to handle the exception.

**Comment by hoyosjs** [comment]
Generally, access violation exceptions come from many sources that are not things you can easily handle. They are often hardware level exceptions, and we don't offer a way to handle those as far as I know.

**Comment by AhmedZero** [comment]
the problem with the external library, and I think there is a problem with calculation divided by zero and result isnan and the library can't recognize what that means? so there is an access violation exception.
but I can't find where is that line to solve it.

**Comment by hoyosjs** [comment]
Do you know if such library provides symbols? If they do, the dump procdump -i -ma dump will have enough information likely to tell you where things went wrong. Otherwise, you'll likely need to reach out to the developer to help with the diagnosis.
