### ISSUE TITLE
Assertion failed '(shiftAmount == scale) || (shiftAmount == 0)'

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#71684]
```
 Starting:    System.Text.RegularExpressions.Tests (parallel test collections = on, max threads = 4)

Assert failure(PID 21 [0x00000015], Thread: 37 [0x0025]): Assertion failed '(shiftAmount == scale) || (shiftAmount == 0)' in 'Microsoft.CodeAnalysis.DotnetRuntime.Extensions.SyntaxValueProviderExtensions:<GetMatchingNodes>g__matchesAttributeName|4_2(byref,byref,System.String,bool,byref):bool' during 'Generate code' (IL size 286; hash 0x72e8996c; Tier1)

    File: /__w/1/s/src/coreclr/jit/emitarm64.cpp Line: 7028
```

```json
{ "ErrorMessage" : "Assertion failed '(shiftAmount == scale) || (shiftAmount == 0)'" }
```<!--Known issue error report start -->
### Report
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|
<!--Known issue error report end -->

**Comment by jkotas** [comment]
Failed in https://github.com/dotnet/runtime/pull/66413#issuecomment-1175489442

**Comment by jkotas** [comment]
Failed in https://github.com/dotnet/runtime/pull/71633#discussion_r914243383

**Comment by jakobbotsch** [comment]
This looks like a preexisting issue to #71439. In this case we end up with an unused `TYP_REF` indirection with contained address mode and lowering turns it into a `TYP_BYTE` null check due to `gtTypeForNullCheck` not handling `TYP_REF`.

**Comment by noahfalk** [comment]
Failed in #71754
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-71574-merge-331cd82bda144befb3/System.Text.RegularExpressions.Tests/1/console.96857959.log?helixlogtype=result
