### ISSUE TITLE
AppBarButton PointerPressed Event doesn't fire

### ISSUE THREAD

**Issue by Padanian** [dotnet/runtime#71681]
### Description

As per title, AppBarButton UIElement only fires Click, but not PointerPressed

XAML
```

        <AppBarButton HorizontalAlignment="Left" Label="Move" PointerPressed="Window_PointerPressed">
            <AppBarButton.Icon>
                <FontIcon FontFamily="Segoe MDL2 Assets" Glyph="&#xE759;" />
            </AppBarButton.Icon>
        </AppBarButton>



```
C#
```
        private void Window_PointerPressed(object sender, PointerRoutedEventArgs e)
        {
            ptrPtStart=e.GetCurrentPoint(sender as UIElement );
        }
```

### Reproduction Steps

copy and paste provided sample into new solution

### Expected behavior

PointerPressed shall fire before Click, as the latter is fired on release

### Actual behavior

None

### Regression?

No

### Known Workarounds

None

### Configuration

.NET SDK Version: 6.0.301
OS Name: Windows
OS Version: 10.0.22000
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\6.0.301\

**Comment by jkotas** [comment]
This repo is not the right place to report WinUI issues. Could you please open this issue in https://github.com/microsoft/microsoft-ui-xaml/ repo instead?
