### ISSUE TITLE
An extra prompt dialog display during testing ASP.Net symbols on VS 17.4 preview 1

### ISSUE THREAD

**Issue by vdanche** [dotnet/runtime#71704]
### Description

Affected build:
VS Enterprise 2022: Version 17.4.0 preview 1.0[32704.43.main] with .NET7 SDK installed.

 

### Reproduction Steps

Steps to reproduce
Testing on Windows with VS -

Goto Tools -> options -> Debugging
Under General
a. Uncheck 'Enable Just My Code'
b. Check 'Suppress JIT optimization on module load (Managed only)'
Under Symbols
a. Check 'Microsoft Symbol Servers'

Create a new ASP.NET Razor project by doing
mkdir razor
cd razor
dotnet new razor

Double click on the ‘Startup.cs’ file in the ‘Explorer’ pane to bring up that source code.

Add the following line to the Startup.cs file at the beginning of the ‘Configure’ method (at the bottom of the file). When using VS, you can add this line of code on Program.cs file
Console.WriteLine("x " + 3);
![image](https://user-images.githubusercontent.com/65637796/177525101-341ea414-7406-4c27-acdc-68192e90d9dd.png)

Put breakpoint(-(F9)) on this line .if (!app.Environment.IsDevelopment())
F5 to continue debugging. The breakpoint you added above will get hit.
Now F11 

### Expected behavior

Expected Result:
ASP.Net symbols display

### Actual behavior

Actual Result:
An extra prompt dialog display
![image](https://user-images.githubusercontent.com/65637796/177526453-c061ce2a-1638-41b8-9f40-e469f8904d09.png)

But Click yes, ASP.Net symbols can display
![image](https://user-images.githubusercontent.com/65637796/177526672-4451f852-ab0e-40bd-8353-cc743f069b62.png)

Note:
1. Put breakpoint on the line Console.WriteLine("x " + 3);, and then test CoreCLR symbols and CoreFx, no extra prompt dialog.
2.Not repro on 17.3 Preview3[32704.42.d17.3]

dotnet --info:
.NET SDK:
 Version:   7.0.100-preview.6.22352.1
 Commit:    492644e08e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-preview.6.22352.1\

Host:
  Version:      7.0.0-preview.6.22324.4
  Architecture: x64
  Commit:       d3fa592f6d

.NET SDKs installed:
  6.0.400-preview.22330.6 [C:\Program Files\dotnet\sdk]
  7.0.100-preview.6.22352.1 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-preview.6.22330.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-preview.6.22324.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-preview.6.22351.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:

**Comment by AaronRobinsonMSFT** [comment]
@vdanche This is a Visual Studio behavior and not something the .NET runtime controls. I would recommend filing an issue on [Developer Community](https://developercommunity.visualstudio.com/home). I can tag some Visual Studio people here, but this is a really feedback on the Visual Studio experience.

/cc @gregg-miskelly @chuckries

**Comment by tommcdon** [comment]
Closing as this appears to be a Visual Studio issue and not a runtime bug.  Please let us know if this is incorrect and we will re-activate this issue.
