### ISSUE TITLE
Deadlock SemaphoreSlim.WaitAsync/Release when call Release and Dispose from another Task

### ISSUE THREAD

**Issue by eduard-bystrov** [dotnet/runtime#71706]
### Description

not the most popular / standard case, but what is :)
reproduced sometimes

### Reproduction Steps

```cs
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace ConsoleApp1
{
	internal class ConsoleApp1
	{
		public static async Task Main()
		{
			var semaphore = new SemaphoreSlim(1, 1);

			var tasks = new List<Task>();

			for (int i = 0; i < 10; ++i)
			{
				tasks.Add(RunTask());
			}

			await Task.WhenAll(tasks);

			Console.WriteLine("DONE!");

			async Task RunTask()
			{
				await Task.Yield();

				Console.WriteLine("before Task.Delay(100)");
				await Task.Delay(100).ConfigureAwait(false);
				Console.WriteLine("after Task.Delay(100)");

				Exception exception = null;

				try
				{
					Console.WriteLine("before semaphore.WaitAsync()");
					await semaphore.WaitAsync();
					Console.WriteLine("after semaphore.WaitAsync()");
				}
				catch (Exception ex)
				{
					exception = ex;
				}
				finally
				{
					Console.WriteLine("before semaphore.Release()");
					semaphore.Release();
					Console.WriteLine("after semaphore.Release()");

					Console.WriteLine($"before semaphore.Dispose()");
					semaphore.Dispose();
					Console.WriteLine($"after semaphore.WaitAsync()");

					if (exception is not null)
					{
						Console.WriteLine($"Ex: {exception}");
					}
				}
			}
		}
	}
}
```

### Expected behavior

Unhandled exception. System.ObjectDisposedException: The semaphore has been disposed.

### Actual behavior

Deadlock

### Configuration

net6

**Comment by stephentoub** [comment]
As with most managed objects, it's not safe to Dispose of a SemaphoreSlim concurrently with other calls.  It's fine to expect an ObjectDisposedException if you call WaitAsync / Release _after_ it's been Disposed, but calling Dispose _during_ a concurrent call to WaitAsync / Release is unsupported / misuse / incorrect by construction, and there aren't any guarantees about behavior in such cases.  As stated in the docs "Unlike most of the members of [SemaphoreSlim](https://docs.microsoft.com/en-us/dotnet/api/system.threading.semaphoreslim?view=net-6.0), [Dispose](https://docs.microsoft.com/en-us/dotnet/api/system.threading.semaphoreslim.dispose?view=net-6.0) is not thread-safe and may not be used concurrently with other members of this instance."
