### ISSUE TITLE
CORINFO_FLG_CUSTOMLAYOUT semantics

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#71711]
`CORINFO_FLG_CUSTOMLAYOUT` flag on the JIT-EE interface has unclear semantics and it is likely disabling optimizations for no good reason in some cases. We should precisely define the semantics of this change and change the implementation to match. Depending on the definition, rename of the flag may be appropriate too.

- The flag is set for auto-layout structs. It should not be necessary. (See the original change https://github.com/dotnet/runtime/pull/71673.)
- The flag is set for `TypedReference`. `TypedReference` is ordinary struct with two fields. It should not be needed.

category:cq
theme:jit-ee-interface
skill-level:expert
cost:small
impact:small

**Comment by jkotas** [comment]
cc @AaronRobinsonMSFT @EgorBo

**Comment by EgorBo** [comment]
Also, related: https://github.com/dotnet/runtime/pull/64863

**Comment by SingleAccretion** [comment]
Proposed semantics: the flag is set for a struct if the padding in it can be significant to the user.

1) The struct had `Size` or explicit layout in the metadata.
2) And the struct has "holes".

The proposed name would be `CORINFO_FLG_HAS_SIGNIFICANT_PADDING`.

Structs with this flag set would not be promotable - this is unlike today, where we do promote them, but then pessimize some "decomposition" transforms, but not all.

**Comment by SingleAccretion** [comment]
> What about unions?

Currently unions are never promoted, so the behavior for them would not change.

> This means that "small" (1-4 element) fixed-sized buffers of primitive types always have "holes" given they currently have 1 field (of the primitive type) and are explicitly sized otherwise?

Correct.

**Comment by tfenise** [comment]
> Proposed semantics: the flag is set for a struct if the padding in it can be significant to the user.
> 
> 1. The struct had `Size` or explicit layout in the metadata.
> 2. And the struct has "holes".

Consider:
```C#
[StructLayout(LayoutKind.Explicit)]
struct Struct1
{
    [FieldOffset(0)]
    int X;

    [FieldOffset(4)]
    byte Y;
}
```

and

```C#
[StructLayout(LayoutKind.Sequential)]
struct Struct2
{
    int X;

    byte Y;
}
```

Are `Struct1` and `Struct2` to be treated differently? They appear to be equivalent.
Can the padding in `Struct2` really be considered not "significant to the user"? If the padding in `Struct1` is considered significant, and `Struct1` and `Struct2` are basically equivalent, then the padding in `Struct2` should also be.

**Comment by SingleAccretion** [comment]
> Can the padding in Struct2 really be considered not "significant to the user"?

It is a choice to not consider it significant. It would be prohibitively expensive to disqualify structs like `Struct2` from promotion, e. g. `Span<T>` would be non-promotable under such rules.

It does create an asymmetry like you highlight. I do not see an easy way out of that. Considering padding in explicitly laid out structs insignificant seems like too dangerous a breaking change.
