### ISSUE TITLE
[API Proposal]: Add generic version of System.Text.Json.JsonSerializableAttribute

### ISSUE THREAD

**Issue by PaulusParssinen** [dotnet/runtime#71712]
### Background and motivation

In C# 11 generic types have ability to inherit `System.Attribute`. It would be nice to utilize the new feature in `JsonSerializableAttribute`s which are used to instruct the JSON source generator to generate serialization metadata for a specified type at compile time. 

I believe the type proposed here would make these definitions clearer by avoiding the `typeof` being repeated for every attribute. It would be "nice to have".

This is more of an throwaway issue to see what the policy is for such attribute changes now that we have the feature available.

### API Proposal

```csharp
namespace System.Text.Json.Serialization;

[AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
#if BUILDING_SOURCE_GENERATOR // From existing non-generic JsonSerializableAttribute
internal
#else
public
#endif
sealed class JsonSerializableAttribute<T> : JsonAttribute
{
    public string? TypeInfoPropertyName { get; set; } // From existing non-generic JsonSerializableAttribute
    public JsonSourceGenerationMode GenerationMode { get; set; } // From existing non-generic JsonSerializableAttribute
}
```

### API Usage

The example from https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-source-generation

```csharp
public class WeatherForecast
{
    public DateTime Date { get; set; }
    public int TemperatureCelsius { get; set; }
    public string? Summary { get; set; }
}

// Before: [JsonSerializable(typeof(WeatherForecast))]
[JsonSerializable<WeatherForecast>] // After
internal partial class SourceGenerationContext : JsonSerializerContext { }
```

### Alternative Designs

The new generic variant could inherit the existing non-generic `JsonSerializableAttribute` if it were to be unsealed. Unsealing a class is not a binary breaking change(?) but it might complicate the generator implementation.

### Existing `JsonSerializableAttribute`
```diff
namespace System.Text.Json.Serialization;

[AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
#if BUILDING_SOURCE_GENERATOR // Copy from the existing implementation
internal
#else
public
#endif
-sealed class JsonSerializableAttribute : JsonAttribute
+class JsonSerializableAttribute : JsonAttribute
{ /* .. */ }
```

### New `JsonSerializableAttribute<T>`
```csharp
namespace System.Text.Json.Serialization;

[AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
#if BUILDING_SOURCE_GENERATOR // Copy from the existing implementation
internal
#else
public
#endif
sealed class JsonSerializableAttribute<T> : JsonSerializableAttribute
{
    public JsonSerializableAttribute() : base(typeof(T)) { }
}
```

### Risks

None AFAIK.

The implications of the alternative design which unseals the existing type are unknown to me. It could potentially complicate the work Roslyn has to do in the generation implemenation?

**Comment by eiriktsarpalis** [comment]
What would be the benefits of using angle brackets other than saving ourselves a few characters?

**Comment by PaulusParssinen** [comment]
> If JsonSerializableAttribute were not sealed, then developers might define their own classes derived from it and expect the source generator to support them. Although the source generator might be able to detect that the class is derived from JsonSerializableAttribute, it would not be easily able to find out what values the constructor of the derived class passes to the constructor of JsonSerializableAttribute or assigns to properties. I think it would then be best for the source generator to report an error if it sees an attribute whose type is derived from JsonSerializableAttribute but is not supported by the generator.

You're correct and that would be a risk for the alternative design that would require an analyzer, which would be pretty costly. 

> What would be the benefits of using angle brackets other than saving ourselves a few characters?

None. Value brought by this attribute would be purely stylistic and if this does not bring enough value by being just a "nice to have" API to consumers, I'm completely fine with killing the proposal.
