### ISSUE TITLE
ECMA 335 is unclear about Array.Initialize()

### ISSUE THREAD

**Issue by tfenise** [dotnet/runtime#71733]
From ECMA 335 II.13.2:
> The Base Class Library provides the method System.Array.Initialize (see Partition IV) to zero all instances in an array of unboxed value types.

Note the verb "zero".

However, from CLILibrary.xml as part of ECMA 335 Partition IV:
```xml
		<Type Name="Array" FullName="System.Array" FullNameSP="System_Array">
...
			<Members>
...
				<Member MemberName="Initialize">
					<MemberSignature Language="ILAsm" Value=".method public hidebysig instance void Initialize()" />
					<MemberSignature Language="C#" Value="public void Initialize();" />
					<MemberType>Method</MemberType>
					<ReturnValue>
						<ReturnType>System.Void</ReturnType>
					</ReturnValue>
					<Parameters />
					<Docs>
						<summary>
							<para>Initializes every element of the current instance of
      value-type objects by calling the
      default constructor of that value type.</para>
						</summary>
						<remarks>
							<para> This method cannot be used on reference-type arrays.</para>
							<para>If the current instance is not a value-type <see cref="T:System.Array" /> or if the value type does not have a default
   constructor, the current instance is not modified.</para>
							<para>The current instance can have any lower bound and any number of dimensions.</para>
							<para>
								<block subset="none" type="note">This method can be used only
   on value types that have constructors. </block>
							</para>
						</remarks>
					</Docs>
					<Excluded>1</Excluded>
					<ExcludedLibrary>RuntimeInfrastructure</ExcludedLibrary>
				</Member>
```
Note "calling the default constructor of that value type".

Should this be considered in https://github.com/dotnet/runtime/blob/main/docs/design/specs/Ecma-335-Augments.md?

**Comment by jkotas** [comment]
ECMA 335 Partition IV is very old snapshot of the API documentation. It has been superseded by the API documentation at https://github.com/dotnet/dotnet-api-docs that gets published at https://docs.microsoft.com/en-us/dotnet/api/

https://docs.microsoft.com/en-us/dotnet/api/system.array.initialize has the correct description.

**Comment by jkotas** [comment]
#71737

**Comment by jkotas** [comment]
@tfenise I have missed that the wrong description is inline in the text.
