### ISSUE TITLE
GetFromJsonAsync does not respect MaxResponseContentBufferSize property of HttpClient

### ISSUE THREAD

**Issue by ChiragRupani** [dotnet/runtime#71763]
### Description

When using `httpClient.GetFromJsonAsync(string URL)`, it is not considering `MaxResponseContentBufferSize` of HttpClient. It is not throwing exception if content length is more than set content buffer size as per [doc](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.maxresponsecontentbuffersize?view=net-6.0)

### Reproduction Steps

Sample code:

```csharp
public record ToDo(int ID, string Title, bool IsCompleted);

static async Task Main(string[] args)
{
    string requestURI = "https://raw.githubusercontent.com/ChiragRupani/ToDoWebAPIDemo/master/ToDoWebAPI/Samples/Sample.json";
    using HttpClient httpClient = new HttpClient();
    httpClient.MaxResponseContentBufferSize = 100;

    try
    {
        var data = await httpClient.GetFromJsonAsync<ToDo[]>(requestURI);
        Console.WriteLine(string.Join<ToDo>(',', data));
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex.Message);
    }
}
```

### Expected behavior

It should throw HttpRequestException - "Cannot write more bytes to the buffer than the configured maximum buffer size: 100"

### Actual behavior

JSON is parsed successfully

### Known Workarounds

The workaround is to call `GetAsync` and then `ReadFromJsonAsync` on HttpContent. It is properly throwing exception if content is more than `MaxResponseContentBufferSize`

```csharp
try
{
    using var response = await httpClient.GetAsync(requestURI);
    response.EnsureSuccessStatusCode();
    var data = await response.Content.ReadFromJsonAsync<ToDo[]>();
    Console.WriteLine(data);
}
catch (Exception ex)
{
    Console.WriteLine(ex.Message);
}
```

### Configuration

 OS Name:  Windows
 RID:   win10-x64
.NET:  6.0.6

Don't look like specific to configuration

### Other information

The only difference I see in both extension methods [implementation  ](https://github.com/dotnet/runtime/blob/215b39abf947da7a40b0cb137eab4bceb24ad3e3/src/libraries/System.Net.Http.Json/src/System/Net/Http/Json/HttpClientJsonExtensions.Get.cs#L26) is  `HttpCompletionOption.ResponseHeadersRead`. This is causing issue, can be verified by adding the same in above workaround code.

I would like to work on it if code changes is planned to resolve it.

**Comment by stephentoub** [comment]
MaxResponseContentBufferSize is about how much data should be allowed to be buffered in methods like GetStringAsync, LoadIntoBufferAsync, etc.  It does not inherently limit how much data is allowed to be sent as part of a response.  It also doesn't limit any other code reading from the response stream, which is what ReadFromJsonAsync does: it passes the response stream to JsonSerializer.DeserializeAsync, which explicitly tries to avoid buffering the whole response prior to parsing it.

**Comment by ChiragRupani** [comment]
Agree, it would be nice to have - the ability to limit data e.g. in JsonSerializer.DeserializeAsync to deal with untrusted URL or file.

**Comment by stephentoub** [comment]
GetFromJsonAsync is a simple helper meant to help with the super common case.  For anything more complicated, you can always drop down to using JsonSerializer.DeserializeAsync directly, e.g. wrap the HTTP response stream in your own custom stream that limits how much data is allowed to be read (regardless of buffering).

**Comment by MihaZupan** [comment]
This is no longer the case as of #79386, which was backported to 6.0 in #80552 and 7.0 in #80553
