### ISSUE TITLE
Passing a path to a key that doesn't exist to OpenSubKey() causes a SafeRegistryHandle to be finalized

### ISSUE THREAD

**Issue by Erarndt** [dotnet/runtime#71773]
### Description

In cases where the specified registry key doesn't exist, a `SafeRegistryHandle` isn't properly disposed and is finalized. The call to `RegOpenKeyEx()` causes the creation of the `SafeRegistryHandle` which is normally passed to the `RegistryKey` constructor and disposed by the caller. In the error case, `OpenSubKey()` returns `null` and fails to dispose the wrapper around the invalid handle.

https://github.com/dotnet/runtime/blob/6a889d234267a4c96ed21d0e1660dce787d78a38/src/libraries/Microsoft.Win32.Registry/src/Microsoft/Win32/RegistryKey.Windows.cs#L269

Something like this is sufficient to expose the issue:
`const string regKeyPath = "some\\invalaid\\path";`
`using var subKey = Registry.CurrentUser.OpenSubKey(regKeyPath);`

### Regression?

This looks like a long-standing issue. I see finalization happening in both .NET Framework 4.8 and .NET 6.

**Comment by danmoseley** [comment]
@Erarndt thanks for the report. Interested in any other "missed dispose" cases you might find.
