### ISSUE TITLE
I can't create new bitmap.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#71818]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/I-cant-create-new-bitmap/10033360)._

---
I'm getting "Parameter is not valid" error when i create a new bitmap file.
I tried both .NET 5.0 and .NET 6.0

    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Dim b As New Bitmap("Tesp.bmp")
    End Sub

---
#### Feedback Bot on 5/7/2022, 03:09 AM: 

(private comment, text removed)

---
#### Guven Acar solved on 5/7/2022, 03:19 AM, 0 votes: 

<p>I found solution from here <a target='_blank' href="https://stackoverflow.com/a/42120900">https://stackoverflow.com/a/42120900</a></p>
<p>My code should be like this:</p>
<pre><code>  <span class="hljs-attr">Try</span>
            <span class="hljs-attr">Dim</span> <span class="hljs-string">save As Bitmap = New Bitmap(10, 10)</span>
            <span class="hljs-attr">Dim</span> <span class="hljs-string">g As Graphics = Graphics.FromImage(save)</span>
            <span class="hljs-attr">g.Flush()</span>
            <span class="hljs-meta">save.Save("Test.bmp",</span> <span class="hljs-string">System.Drawing.Imaging.ImageFormat.Bmp)</span>
            <span class="hljs-attr">g.Dispose()</span>
  <span class="hljs-attr">Catch</span> <span class="hljs-string">ex As Exception</span>
            <span class="hljs-attr">Dim</span> <span class="hljs-string">st = "Error message : " &amp; ex.Message</span>
  <span class="hljs-attr">End</span> <span class="hljs-string">Try</span>

</code></pre>

**Comment by ViktorHofer** [comment]
As the author notice, passing in a string to the Bitmap constructor reads from an existing file. To create a new Bitmap, a different constructor needs to be used.

https://github.com/dotnet/runtime/blob/2f7fdb9991c580346af0df726017070f0ba2b350/src/libraries/System.Drawing.Common/src/System/Drawing/Bitmap.cs#L26-L51
