### ISSUE TITLE
Math.BigMul(ulong a, ulong b, out ulong low) uses SoftwareFallback even though Bmi2.X64.IsSupported.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#71816]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MathBigMululong-a-ulong-b-out-ulong-/10051594)._

---
Math.BigMul(ulong a, ulong b, out ulong low) uses SoftwareFallback even though Bmi2.X64.IsSupported is true and the mutch faster Bmi2.X64.MultiplyNoFlags function that maps to  _mulx_u64 could be used.
This is the same in Debug as in Release.

Example:

```
static unsafe void test()
{
  ulong low, high = Math.BigMul(7ul, 8ul, out low);

  if (Bmi2.X64.IsSupported)
  {
    high = Bmi2.X64.MultiplyNoFlags(7ul, 8ul, &low);
  }
}
```

![image.png](https://aka.ms/dc/image?name=B5bb4cb902ec44efb9a92a44604d81dd5637890040005677404_20220524-174639-image.png&tid=5bb4cb902ec44efb9a92a44604d81dd5637890040005677404)

![image.png](https://aka.ms/dc/image?name=Bb62081b081af44f698b0e06f678976b6637890042814089560_20220524-175120-image.png&tid=b62081b081af44f698b0e06f678976b6637890042814089560)

---
#### Feedback Bot on 5/24/2022, 07:16 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by filipnavara** [comment]
There's some context missing in the original report.

The code certainly has the optimized code path:
https://github.com/dotnet/runtime/blob/af63ef1fdbdebfb77f1df8c5f3dcbf783ec38970/src/libraries/System.Private.CoreLib/src/System/Math.cs#L177-L183

...and SharpLab shows that it is used:
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgAYBYAKGIEYkACAVwDtdsAzGR4lRjDFwYAFAEoaAbxqMWAGwisA5owUB3NIwAWASyVbGAXl50AdAFlsGLaYBCe88zkiA7E80AOd4wjMMqiDUxAG4aAF8gA

**Comment by EgorBo** [comment]
> Perhaps Ready2Run / tiering is precompiled without BMI2 support and it can be hit?

Right, R2R uses software fallback. So once it's re-jitted (if it's hot) it will start using BMI2

**Comment by AntonLapounov** [comment]
Christian Ohle, thank you for reporting this. Please see @EgorBo's reply above.
