### ISSUE TITLE
Queations about Mono.Data.Sqlite encryption

### ISSUE THREAD

**Issue by suke27** [dotnet/runtime#71811]
Hi, 

we are now use Mono.Data.Sqlite  to manage DB, i have a question that, does Mono.Data.Sqlite support database encryption. is it free? i heard that it is charged.

hope to get your reply, thanks!

**Comment by jkotas** [comment]
This question belongs to https://github.com/mono/mono where Mono.Data.Sqlite lives.

**Comment by roji** [comment]
@suke27 note also the alternative .NET Sqlite drivers: [Microsoft.Data.Sqlite](https://docs.microsoft.com/en-us/dotnet/standard/data/sqlite/?tabs=netcore-cli) (built by @bricelam and used by Entity Framework Core), and [System.Data.Sqlite](https://system.data.sqlite.org/index.html/doc/trunk/www/index.wiki). These may be better options for using Sqlite in a modern .NET application, and should support encryption (definitely without charging anything).

I'm going to go ahead and close this issue as it's not related to the .NET runtime in any way; but feel free to post back here if you have further questions.
