### ISSUE TITLE
[API Proposal]: New interface to allow manual processing of a `SynchronizationContext`

### ISSUE THREAD

**Issue by DaZombieKiller** [dotnet/runtime#71823]
### Background and motivation

Today, if you find yourself in a situation where you either cannot or are struggling to avoid sync-over-async, you put yourself in a position where you may potentially deadlock by blocking the same thread that will queue continuations. You can mitigate this by propagating `ConfigureAwait(false)` through library code (reliant on third parties) or setting the current `SynchronizationContext` to `null`.

When you are able to implement your own `SynchronizationContext`, you can expose APIs to allow you to process queued invocations early to avoid these problems, but APIs such as `Task.Wait` will not be aware of it, leading them to still potentially cause deadlocks.

This interface would provide a way to opt-in to this functionality, and allow BCL APIs to take advantage of it.

### API Proposal

```csharp
namespace System.Threading;

public interface IProcessableSynchronizationContext
{
    bool CurrentThreadCanProcessOperations { get; }
    void ProcessQueuedOperations();
}
```

### API Usage

A simple example of how this interface could be used to synchronously wait on a `Task` without the potential of deadlocking if the current thread is also in charge of invoking continuations:
```csharp
if (SynchronizationContext.Current is IProcessableSynchronizationContext
    { CurrentThreadCanProcessOperations: true } context)
{
    while (!operation.IsCompleted)
    {
        context.ProcessQueuedOperations();
    }
}
else
{
    operation.Wait();
}
```
`Task.Wait` and related APIs could be changed to take advantage of this interface, or new APIs could be introduced.

### Alternative Designs

Rather than an `interface`, a new base class could be introduced:
```cs
public abstract class ProcessableSynchronizationContext : SynchronizationContext
{
    public abstract bool CurrentThreadCanProcessOperations { get; }
    public abstract void ProcessQueuedOperations();
}
```

### Risks

There is potential for misuse of the API, as an improper implementation of this interface would not check `CurrentThreadCanProcessOperations` in `ProcessQueuedOperations`, allowing methods to be invoked on threads that they otherwise would not be.

**Comment by DaZombieKiller** [comment]
Thanks for pointing those out, I had completely skimmed over their intent and usefulness previously. Though I have not tested it extensively, I was able to implement a prototype of the proposed API using them. The return value of `Wait` does not appear to be documented for the `waitAll = true` case (I may have to open a docs issue for that), so there may be potential correctness problems:
```cs
public abstract class ProcessableSynchronizationContext : SynchronizationContext
{
    protected ProcessableSynchronizationContext() => SetWaitNotificationRequired();

    protected abstract bool CurrentThreadCanProcessOperations { get; }

    protected abstract void ProcessQueuedOperations();

    public sealed override int Wait(IntPtr[] waitHandles, bool waitAll, int millisecondsTimeout)
    {
        if (!CurrentThreadCanProcessOperations)
            return WaitHelper(waitHandles, waitAll, millisecondsTimeout);

        int ms = 0;
        int result;

        do
        {
            ProcessQueuedOperations();
            result = WaitHelper(waitHandles, false, WaitHandle.WaitTimeout);
            ms    += WaitHandle.WaitTimeout;

            if (millisecondsTimeout != Timeout.Infinite && ms >= millisecondsTimeout)
                break;

        } while (waitAll && result >= 0);

        return result;
    }
}
```
Since the functionality can be implemented with existing APIs and `SynchronizationContext` is a low-level API, this proposal is probably not as useful as I had initially believed. I'll leave this issue open in the interest of further discussion, perhaps there is interest in exposing a simpler API for this. If not, feel free to close it on my behalf, I'd have no complaints.

**Comment by stephentoub** [comment]
> If not, feel free to close it on my behalf, I'd have no complaints.

Thanks.
