### ISSUE TITLE
[API Proposal]: Make [*]InterpolatedStringHandler implementations usable in user libraries

### ISSUE THREAD

**Issue by dellamonica** [dotnet/runtime#71829]
### Background and motivation

The runtime has implementations of handlers such as Debug.AssertInterpolatedStringHandler which are in the public API since they are types used as arguments in public methods such as Debug.Assert.

However, the method that actually creates a string from the handler is made internal. This means that the type cannot be used by a library in convenient form if one wanted to write methods similar to Asserts (e.g. for conditional logging).

This proposal is to make ToStringAndClear a public method (or create some other public method) that produces the string when needed.

### API Proposal

Either make ToStringAndClear public or create a callable method to produce the interpolated string from the handler.

### API Usage

```csharp
public void LogIf(bool condition, [InterpolatedStringHandlerArgument("condition")] ref AssertInterpolatedStringHandler message)
{
     // The handler ensures that any expensive processing in the string interpolation for the "message" parameter
     // is not evaluated at the call site if the condition is false.
     if (!condition) return;
     string logText = $"{DateTime.Now}: {message.ToStringAndClear()}";
     // append to log...
}
```

### Alternative Designs

Rename the type to something like `ConditionalInterpolatedStringHandler`, expose ToStringAndClear and put it outside of `Debug` so that it can be used not only by Debug.Assert but anywhere else.

### Risks

The internal method clears the inner handler which means that repeated calls might produce unexpected results. However, this API is interesting mostly to library devs and proper documentation should suffice.

**Comment by dellamonica** [comment]
Yes, one can always re-implement it, but that is true of almost anything. My point is that a "canonical" implementation already exists, and perhaps other than naming it something else like, say `ConditionalInterpolatedStringHandler`, it could be reused in the runtime, BCL and user libraries.

Although it is called `AssertInterpolatedStringHandler`, there is nothing in there that is specific to asserts, the only point of that struct is to short-circuit the interpolation if the assert condition is false. That logic is valuable in other applications and there is no point in replicating it. In fact, the code you link looks like a straight copy of `AssertInterpolatedStringHandler`'s implementation.

> You can also achieve this by creating your own interpolated handler types being thin wrappers over `DefaultInterpolatedStringHandler` and just proxying all API calls to the APIs of that handler. I believe the common practice is in fact to just declare domain-specific handlers for different APIs rather than reusing handlers from other APIs. As an example, we're doing this in the `IsTrueInterpolatedStringHandler` type of the .NET Community Toolkit Diagnostics package ([here](https://github.com/CommunityToolkit/dotnet/blob/8528092ed255478db6d794a92829311ed43a52d3/CommunityToolkit.Diagnostics/Guard.Boolean.cs#L128)).

**Comment by stephentoub** [comment]
I honestly don't think you want this. AssertInterpolatedStringHandler _is_ specific to asserts in that it assumes overhead doesn't matter at all when the condition is false because the process is about to die.  As such, it allocates a new StringBuilder every time it logs something (since that's expected to happen at most once).  Your example is using it for logging, which would likely care more about those overheads.  Further, AssertInterpolatedStringHandler and WriteIfInterpolatedStringHandler are just thin wrappers around StringBuilder.AppendInterpolatedStringHandler, which has everything you need to do the same thing in a way that works for your logging needs.

**Comment by dellamonica** [comment]
I hadn't dig enough into the code to realize that it was allocating. It does turn out that my use case would be for treating exceptional situations just like assert, so perf would not matter.

Now I understand better the footguns that you are trying to avoid by making the method internal...

> I honestly don't think you want this. AssertInterpolatedStringHandler _is_ specific to asserts in that it assumes overhead doesn't matter at all when the condition is false because the process is about to die. As such, it allocates a new StringBuilder every time it logs something (since that's expected to happen at most once). Your example is using it for logging, which would likely care more about those overheads. Further, AssertInterpolatedStringHandler and WriteIfInterpolatedStringHandler are just thin wrappers around StringBuilder.AppendInterpolatedStringHandler, which has everything you need to do the same thing in a way that works for your logging needs.
> 
> These Debug builders are intended to be implementation detail; they have to be public in support of the design, but they're not intended to be used in other APIs.
