### ISSUE TITLE
[API Proposal]: Add another entry to JsonNumberHandling to serialize long/ulong as strings

### ISSUE THREAD

**Issue by CheloXL** [dotnet/runtime#71830]
### Background and motivation

When interop with js engines is required, serialization of long/ulong values are problematic. Js engines are limited to 53bit integer, so any number outside that range is trimmed down. This of course changes the value, so roundtripping is not possible (think of DB ids, for example).

I know this can be done right now with a custom JsonConverter, but since interop with js engines is so common, I think this could be a great addition.

### API Proposal

```csharp
namespace System.Text.Json.Serialization;

public enum JsonNumberHandling {
  Strict = 0x0,
  AllowReadingFromString = 0x1,
  WriteAsString = 0x2,
  AllowNamedFloatingPointLiterals = 0x4,
  WriteLongAsString = 0x8 //name TBD
}
```

### API Usage

```csharp
var options = new JsonSerializerOptions();
//sets reading/writing of longs/ulongs as strings
options.NumberHandling = JsonNumberHandling.WriteLongAsString;
```

**Comment by eiriktsarpalis** [comment]
The existing `WriteAsString` value already does this for numeric types, including long/ulong. I'm guessing though that you want to constrain the setting specifically to `long`? 

There are limits to how much mixing and matching an enum like `JsonNumberHandling` could handle, authoring a custom converter is the recommended approach when requiring bespoke configuration.

**Comment by krwq** [comment]
Starting from .NET 7 Preview 6 you can pass following options to change that behavior:

```csharp
JsonSerializerOptions options = new()
{
    TypeInfoResolver = new DefaultJsonTypeInfoResolver()
    {
        Modifiers = { SerializeLongsAsString }
    }
};

static void SerializeLongsAsString(JsonTypeInfo typeInfo)
{
    if (typeInfo.Type == typeof(long) || typeInfo.Type == typeof(ulong))
    {
        typeInfo.NumberHandling = JsonNumberHandling.WriteAsString | JsonNumberHandling.AllowReadingFromString;
    }
}
```

IMO we should close this issue in favor of using contract customization

**Comment by eiriktsarpalis** [comment]
Yeah, that should be another workaround starting with .NET 7. Closing, since it is unlikely we would make a change to the enum as proposed.
