### ISSUE TITLE
Obsolete ServicePointManager

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#71836]
*Edit:* Changed the proposal to obsolete the entire class.

## Background and motivation

Most of the public API-s exposed by `ServicePointManager` are unused, having no effect other than being copied to `ServicePoint` properties. Even properties with actual effect on legacy API-s could be mistakenly used in combo with `HttpClient`. [Team consensus](https://github.com/dotnet/runtime/issues/62770#issuecomment-993830267) is to obsolete the entire `ServicePointManager` class if possible.

## API proposal

```diff

+ [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
  public class ServicePointManager
  {
-     [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
      public static ServicePoint FindServicePoint(Uri address);

-     [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
      public static ServicePoint FindServicePoint(string uriString, IWebProxy? proxy);

-     [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
      public static ServicePoint FindServicePoint(Uri address, IWebProxy? proxy);
  }
```

## Alternative proposal

Obsolete only unused members.

```csharp
namespace System.Net;

public partial class ServicePointManager
{
    // Remaining members:
    // public static bool CheckCertificateRevocationList { get; set; }
    // public static SecurityProtocolType SecurityProtocol { get; set; }
    // public static RemoteCertificateValidationCallback? ServerCertificateValidationCallback { get; set; }

    [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    public const int DefaultNonPersistentConnectionLimit = 4;
    [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    public const int DefaultPersistentConnectionLimit = 2;
    [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    public static int DefaultConnectionLimit { get; set; }
    [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    public static int DnsRefreshTimeout { get; set; }
    [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    public static bool EnableDnsRoundRobin { get; set; }
    [UnsupportedOSPlatform("browser")]
    [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    public static EncryptionPolicy EncryptionPolicy { get; }
    [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    public static bool Expect100Continue { get; set; }
    [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    public static int MaxServicePointIdleTime { get; set; }
    [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    public static int MaxServicePoints { get; set; }
    [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    public static bool ReusePort { get; set; }
    [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    public static bool UseNagleAlgorithm { get; set; }

    // Already obsolete:
    // [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    // public static ServicePoint FindServicePoint(string uriString, IWebProxy? proxy);
    // [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    // public static ServicePoint FindServicePoint(Uri address);
    // [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    // public static ServicePoint FindServicePoint(Uri address, IWebProxy? proxy);
    // [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    // public static void SetTcpKeepAlive(bool enabled, int keepAliveTime, int keepAliveInterval);
}
```

**Comment by terrajobst** [comment]
Is `SYSLIB0014` an existing diagnostic ID? If so, do we think it's good that an existing suppression for it will also suppress these obsoletion or vice versa?

**Comment by bartonjs** [comment]
Unless we're waving a big wand and making the whole type obsolete, why would we bother making the consts obsolete?

**Comment by antonfirsov** [comment]
> Unless we're waving a big wand and making the whole type obsolete, why would we bother making the consts obsolete?

We don't have to. The key value here is to obsolete the members people still use and get surprised that they do nothing. I don't mind obsoleting the whole type either ([should be possible](https://github.com/dotnet/runtime/pull/71833#issuecomment-1179091533)). Whatever we mange to slide in last-minute is better than the current state IMO.

**Comment by terrajobst** [comment]
The only reason to obsolete constants would be if we can't obsolete the method/property but want to make it clear that certain values are no longer supported. The most common example would be enum members. In this case, I assume that's not the case as we made the receiving properties obsolete so the value in obsoleting the constants would be low, if not nil.

**Comment by karelz** [comment]
@antonfirsov I wonder if we should delay it until 8.0.
I think that when we tried last-minute obsoletion in 6.0, it broke .NET Core build, because some teams used the APIs. At minimum we need to communicate. Though, I would prefer to push it to next release.

**Comment by terrajobst** [comment]
I have no objections to moving it to .NET 8, but it feels a tad too conservative IMHO.

**Comment by karelz** [comment]
Triage: Discussed offline. Past experience tells me otherwise though :P
Moved to 8.0. We should do it early on in 8.0.

**Comment by terrajobst** [comment]
* Marking the type seems fine, assuming we believe the three remaining members listed are also obsolete. If we don't believe that, then we should follow the original proposal and only obsolete them proposed members.

```C#
namespace System.Net;

public partial class ServicePointManager
{
    // Remaining members:
    // public static bool CheckCertificateRevocationList { get; set; }
    // public static SecurityProtocolType SecurityProtocol { get; set; }
    // public static RemoteCertificateValidationCallback? ServerCertificateValidationCallback { get; set; }

    [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    public const int DefaultNonPersistentConnectionLimit = 4;
    [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    public const int DefaultPersistentConnectionLimit = 2;
    [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    public static int DefaultConnectionLimit { get; set; }
    [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    public static int DnsRefreshTimeout { get; set; }
    [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    public static bool EnableDnsRoundRobin { get; set; }
    [UnsupportedOSPlatform("browser")]
    [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    public static EncryptionPolicy EncryptionPolicy { get; }
    [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    public static bool Expect100Continue { get; set; }
    [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    public static int MaxServicePointIdleTime { get; set; }
    [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    public static int MaxServicePoints { get; set; }
    [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    public static bool ReusePort { get; set; }
    [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    public static bool UseNagleAlgorithm { get; set; }

    // Already obsolete:
    // [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    // public static ServicePoint FindServicePoint(string uriString, IWebProxy? proxy);
    // [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    // public static ServicePoint FindServicePoint(Uri address);
    // [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    // public static ServicePoint FindServicePoint(Uri address, IWebProxy? proxy);
    // [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
    // public static void SetTcpKeepAlive(bool enabled, int keepAliveTime, int keepAliveInterval);
}
```

**Comment by karelz** [comment]
Sadly, we didn't make it in 8.0. Moving to Future for now.

**Comment by nijasinhycu** [comment]
@karelz 
We are using .NET 6 and HttpC;lientFactory. 
We are sticking to creating short-lived HttpClient objects using factory so that it will not run into issues of not honoring DNS changes. 

In our case, we are parallelly invoking multiple outbound calls to the same service and setting a high value for  ServicePointManager.DefaultConnectionLimit made a lot of sense in previous .NET versions.

Since Microsoft removed the support for ServicePointManager and moved everything to HttpClient, in our case, since we use HttpClientFactory and short-lived httpclients (Almost a new HttpClient per API call, since factory takes care of HttpMessageHandlers), how will we increase this MaxConnections default. Do we even need to ?

Because If I remember, the earlier default maxConnections were 2.

**Comment by antonfirsov** [comment]
> will we increase this MaxConnections default. Do we even need to

Unless you want to limit connections going to the same host, you don't have to configure anything since [`HttpClientHandler.MaxConnectionsPerServer`](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.maxconnectionsperserver) defaults to `int.MaxValue`.

**Comment by nijasinhycu** [comment]
> > will we increase this MaxConnections default. Do we even need to
> 
> Unless you want to limit connections going to the same host, you don't have to configure anything since [`HttpClientHandler.MaxConnectionsPerServer`](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.maxconnectionsperserver) defaults to `int.MaxValue`.

Thanks @antonfirsov 
We were doing the same and wanted to validate once.

Appreciate the quick turnaround!

**Comment by bartonjs** [comment]
* While we generally don't like obsoleting an entire type, this type is functionally a `static class` and so the incidental signature impact concerns don't apply.
* It's unfortunate that three of the properties still have effect in a non-Obsolete type, but it's low usage.

```diff
namespace System.Net;

+ [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
  public class ServicePointManager
  {
-     [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
      public static ServicePoint FindServicePoint(Uri address);

-     [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
      public static ServicePoint FindServicePoint(string uriString, IWebProxy? proxy);

-     [Obsolete(DiagnosticId = Obsoletions.WebRequestDiagId)]
      public static ServicePoint FindServicePoint(Uri address, IWebProxy? proxy);
  }
```
