### ISSUE TITLE
Updating lclmorph to support bitcast

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#71839]
With https://github.com/dotnet/runtime/pull/71567, the front end now has minimal support for `GT_BITCAST` nodes including value numbering and constant folding.

It should now be feasible to address some of the `TODO-ADDR` comments in `LocalAddressVisitor::SelectLocalIndirTransform` and `LocalAddressVisitor::MorphLocalAddress` by recognizing certain indirections as being representable as a `GT_BITCAST` rather than keeping it as a `GT_IND`.

To start we should likely only handle `float<->int/uint` and `double<->long/ulong`. There may also be some benefit in handling conversions surrounding `simd8`.

In the future this could likely be extended to struct types and potentially other primitives as well.

category:cq
theme:morph

**Comment by JulieLeeMSFT** [comment]
cc @dotnet/jit-contrib.

**Comment by AndyAyersMS** [comment]
@tannergooding is this something you hope to see in .net 8?

**Comment by SingleAccretion** [comment]
This is now effectively a one-line change:

https://github.com/dotnet/runtime/blob/fb001c47d8fe6575c390fa7fc47b039917882841/src/coreclr/jit/lclmorph.cpp#L1027-L1035

**Comment by TIHan** [comment]
@SingleAccretion you still working on this one?

**Comment by SingleAccretion** [comment]
Yes, if not "right now". If someone wants to do the (small) amount of work to close this issue though, they should feel free to do so.
