### ISSUE TITLE
Assertion failed 'argsToReverse' in 'Program:<Main>$(System.String[])' during 'Importation'

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#71874]
Compile the following:

```csharp
using System.Runtime.InteropServices;

MessageBoxW();

[DllImport("user32", CallingConvention = CallingConvention.ThisCall)]
static extern void MessageBoxW();
```

With:

```
csc /O /noconfig /nostdlib foo9.cs /r:System.Private.CoreLib.dll
```

And run with CoreRun:

```
Assert failure(PID 26004 [0x00006594], Thread: 33568 [0x8320]): Assertion failed 'argsToReverse' in 'Program:<Main>$(System.String[])' during 'Importation' (IL size 6; hash 0x79b422bf; Tier0)

    File: C:\git\runtime2\src\coreclr\jit\importer.cpp Line: 8567
    Image: C:\git\runtime2\artifacts\bin\coreclr\windows.x64.Debug\corerun.exe
```

Granted the p/invoke is pointless, but I would expect some exception instead of an assert/AV in the JIT.

Cc @dotnet/interop-contrib for suitable exceptions, but I think JIT can just BADCODE it.

This is currently blocking the System.Reflection.MetadataLoadContext.Tests from Native AOT compiling because it has this kind of p/invoke in it that it never calls, but we try to AOT compile it nonetheless, because AOT,

**Comment by jakobbotsch** [comment]
For your example the JIT assert is the first assert hit only on x64. On x86 we assert in the runtime before getting there:
```scala
Assert failure(PID 39604 [0x00009ab4], Thread: 56708 [0xdd84]): cbDstBuffer >= sizeof(SLOT)

CORECLR! NDirectMethodDesc::SetStackArgumentSize + 0x31 (0x785dd131)
CORECLR! NDirect::MarshalingRequired + 0xB17 (0x785d91e7)
CORECLR! NDirectMethodDesc::ComputeMarshalingRequired + 0x23 (0x78365913)
CORECLR! NDirectMethodDesc::MarshalingRequired + 0x191 (0x782f0451)
CORECLR! CEEInfo::pInvokeMarshalingRequired + 0x2FF (0x7832b1cf)
CLRJIT! Compiler::impCheckForPInvokeCall + 0x278 (0x7995aac8)
CLRJIT! Compiler::impImportCall + 0x1598 (0x79974868)
CLRJIT! Compiler::impImportBlockCode + 0x79CD (0x7996930d)
CLRJIT! `Compiler::impImportBlock'::`13'::__Body::Run + 0x60 (0x79952910)
CLRJIT! Compiler::impImportBlock + 0x1AE (0x799608fe)
    File: C:\dev\dotnet\runtime\src\coreclr\vm\method.hpp Line: 3043
    Image: C:\dev\dotnet\runtime\artifacts\tests\coreclr\windows.x86.Debug\Tests\Core_Root\corerun.exe
```

Isn't this just a test bug? The JIT is not particularly robust to many patterns of invalid IL/metadata.
If on the other hand we think thiscall with 0 args is valid, then we need a runtime fix too.

**Comment by AaronRobinsonMSFT** [comment]
> If on the other hand we think thiscall with 0 args is valid, then we need a runtime fix too.

It isn't valid in my opinion. Let me see what I can do on the runtime side.

> but I think JIT can just BADCODE it.

Agree.

**Comment by jakobbotsch** [comment]
It looks like I can have the JIT do the check before we call `pInvokeMarshalingRequired` JIT-EE method without any problems, so then no runtime change is necessary.
