### ISSUE TITLE
ClientWebSocket memory footprint issue on Linux

### ISSUE THREAD

**Issue by StegBrind** [dotnet/runtime#71876]
### Description
I wrote a simple application that connects to the remote Binance websocket API with a method which endlessly receives and writes incoming data into the 100 KB buffer. The problem is that the process starts consuming a lot of memory on Linux. I'm sure this simple application should not make a memory footprint of more than 10 MB. In 20-30 minutes of running this application, the memory usage can reach 100 MB (which is abnormal). On Windows 10 exactly the same code performs way better and overall memory usage of the process doesn't exceed 14.5 MB (according to Task Manager).

I suspect that there is some memory issue hidden in the ReceiveAsync method.

Here's the code (no extra packages required):
```
using System;
using System.Threading.Tasks;
using System.Text;
using System.Net.WebSockets;
using System.Threading;

namespace TestProject
{
    class Program
    {
        static ClientWebSocket Client;

        static async Task Main(string[] args)
        {
            Client = new ClientWebSocket();
            await Client.ConnectAsync(
                new Uri("wss://stream.binance.com:9443/ws/btcusdt@depth@100ms"), CancellationToken.None);

            var json = System.Text.Json.JsonSerializer.Serialize(new
            {
                method = "SUBSCRIBE",
                @params = new string[]
                {
                    "ethusdt@depth@100ms",
                    "bnbusdt@depth@100ms",
                    "bnbbusd@depth@100ms"
                },
                id = (long)(DateTime.Now - new DateTime(1970, 1, 1)).TotalMilliseconds
            });

            await Client.SendAsync(
                Encoding.UTF8.GetBytes(json), WebSocketMessageType.Text, true, CancellationToken.None
            );
            
            Console.WriteLine("Subscribed");
            
            var loopReceiverCancellationToken = new CancellationTokenSource();
            var loopReceiverTask = CreateWebSocketLoopAsync(loopReceiverCancellationToken.Token);
            await loopReceiverTask;
        }

        private static async Task CreateWebSocketLoopAsync(CancellationToken cancellationToken)
        {
            int bufferSize = 102400; // 100 KB
            Task<ValueWebSocketReceiveResult> receiveTask;
            
            ulong totalBytesReceived = 0;
            var buffer = new Memory<byte>(new byte[bufferSize]);

            while (!cancellationToken.IsCancellationRequested)
            {
                receiveTask = Client.ReceiveAsync(buffer, CancellationToken.None).AsTask();

                while (await Task.WhenAny(receiveTask, Task.Delay(500)) != receiveTask)
                {
                    if (cancellationToken.IsCancellationRequested)
                        return;
                }

                // Here in production code, I would handle the received buffer but we will skip it for simplicity

                buffer.Span.Clear(); // Clear the already handled buffer

                totalBytesReceived += (ulong)receiveTask.Result.Count;
                Console.WriteLine("Bytes received: " + totalBytesReceived);
            }
        }
    }
}
```

### Configuration

dotnet version: .NET 6.0.306
OS: Arch Linux 5.18.6-arch1-1
Architecture: x64

**Comment by davidfowl** [comment]
Did you capture a memory dump?

**Comment by StegBrind** [comment]
Here's the dump file captured via dotnet-dump tool:
https://mega.nz/file/4c8TxRTD#e45YowYXmJANmYpc0j1qyD8Ab2YgPiAIUkuPxhWM94I

I had to upload it to Mega because the file weighs 38.9 MB

**Comment by wfurt** [comment]
triage: we should look at the dump, unless you have already some insight @davidfowl. Also we should see if this is new behavior on 6.0.

**Comment by zlatanov** [comment]
I can guarantee that the problem here is the following line:

```c#
while (await Task.WhenAny(receiveTask, Task.Delay(500)) != receiveTask)
```

If the receive loop is faster than 500ms this will end up creating a lot of timers and tasks. Task.WhenAny will not cancel the delayed task. I don't know why windows and linux would behave differently here (assuming they are, because of the observed memory usage) and my only guess would be the underlying implementation for the timers.

The memory dump is no longer available, but I think the aforementioned line of code is the culprit here and the issue can be closed.

**Comment by davidfowl** [comment]
Shameles plug:

- https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#always-dispose-cancellationtokensources-used-for-timeouts
- https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#using-a-timeout

**Comment by wfurt** [comment]
Is this actionable in any way? From the comments above it does not seems to be problem with ClientWebSocket. 
Can you apply the suggestion @StegBrind and let us know?

Any thoughtst on this @stephentoub

**Comment by stephentoub** [comment]
> Any thoughtst on this

Without the memory dump, I have no way of knowing where the actual memory was going. But @zlatanov is correct that such use of WhenAny + Task.Delay in the repro is problematic.
