### ISSUE TITLE
System.Text.Json contract customization: not possible to enable deserialization in properties marked JsonIgnoreCondition.Always

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#71886]
Consider the following test:
```C#
[Fact]
public static void CanEnableDeserializationOnAlwaysIgnoreProperty()
{
    var options = new JsonSerializerOptions
    {
        TypeInfoResolver = new DefaultJsonTypeInfoResolver
        {
            Modifiers =
            {
                jsonTypeInfo =>
                {
                    if (jsonTypeInfo.Type != typeof(ClassWithJsonIgnoreAlwaysProperty))
                    {
                        return;
                    }

                    JsonPropertyInfo jsonPropertyInfo = jsonTypeInfo.Properties[0];
                    jsonPropertyInfo.Set = (obj, value) => ((ClassWithJsonIgnoreAlwaysProperty)obj).Value = (int)value;
                }
            }
        }
    };

    ClassWithJsonIgnoreAlwaysProperty value = JsonSerializer.Deserialize<ClassWithJsonIgnoreAlwaysProperty>("""{"Value":42}""", options);
    Assert.Equal(42, value.Value);
}

public class ClassWithJsonIgnoreAlwaysProperty
{
    [JsonIgnore]
    public int Value { get; set; }
}
```
This happens because the [`DetermineSerializationCapabilities` method](https://github.com/dotnet/runtime/blob/49288b4ebea7f1792fbd1e09726cb7ee21aa1088/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonPropertyInfo.cs#L322-L323) will mark the property as non-serializable/deserializable based on the initial value of `JsonIgnoreCondition`. `JsonIgnoreCondition` is not user-settable so no user modification on the contract model can prevent this.

I would recommend we change this so that all logic in `DetermineSerializationCapabilities` is done at initialization time and can be modified by users. Additionally, I propose we introduce a `ShouldDeserialize` method to `JsonPropertyInfo`:

```diff
public partial class JsonPropertyInfo
{
    public Func<object, object?, bool> ShouldSerialize { get; set; }
+    public Func<object, object?, bool> ShouldDeserialize { get; set; }
}
```
The two delegates would allow mapping all possible `JsonIgnoreCondition` configurations to these two delegates and not require nulling out the `Get` and `Set` delegates as we currently do for `JsonIgnoreCondition.Always`. Contract customization in Json.NET also includes a [`ShouldDeserialize`](https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_Serialization_JsonProperty_ShouldDeserialize.htm) delegate complementing [`ShouldSerialize`](https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_Serialization_JsonProperty_ShouldSerialize.htm) so we should be following a similar approach in `System.Text.Json`.

cc @krwq @jeffhandley

**Comment by eiriktsarpalis** [comment]
The following internal properties are also of interest:

* `IgnoreDefaultValuesOnWrite`
* `IgnoreDefaultValuesOnRead`
* `CanSerialize`
* `CanDeserialize`

These all map from `JsonIgnoreCondition` but are not user modifiable. Their behavior should be mapped to `ShouldSerialize`/`ShouldDeserialize` delegates.

**Comment by krwq** [comment]
I think when Set is set we should simply replace value of ShouldSerialize to delegate (I think it's already set), clear `_ignoreCondition`

**Comment by eiriktsarpalis** [comment]
> I think when Set is set we should simply replace value of ShouldSerialize to delegate

Why should making changes to `Set` have any bearing on the value of `ShouldSerialize`?

**Comment by krwq** [comment]
it won't. if you request `ShouldSerialize` value it will be the same regardless of touching `Set` - the only thing which will change is perf since we can't use internal `enum` which allows us to not having to touch delegate
