### ISSUE TITLE
Can't call NativeLibrary.GetExport with RTLD_DEFAULT on Linux

### ISSUE THREAD

**Issue by kevingosse** [dotnet/runtime#71881]
In an application, I need to call `dlsym(RTLD_DEFAULT, "_ZN4lldb10SBDebugger21GetCommandInterpreterEv")` to dynamically locate a symbol from a library that I didn't load myself. I thought I could do that with `NativeLibrary.GetExport`: 

```csharp
var RTLD_DEFAULT = IntPtr.Zero;
var getCommandInterpreter = NativeLibrary.GetExport(RTLD_DEFAULT, "_ZN4lldb10SBDebugger21GetCommandInterpreterEv");
```

Unfortunately the method does not accept `IntPtr.Zero` and throws an ArgumentNullException: 
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/NativeLibrary.cs#L158

It's easy to work around that by directly calling `dlsym`, but I'm wondering if it would make sense to update the method to accept `IntPtr.Zero` as a valid value on Linux.

**Comment by DaZombieKiller** [comment]
> but I'm wondering if it would make sense to update the method to accept `IntPtr.Zero` as a valid value on Linux.

Given that `NativeLibrary` exists to abstract away platform differences, I don't think introducing a platform difference would be a good idea. I think exposing a new API like `GetExportFromAny` would be more appropriate, provided that it can be implemented on other platforms too (on Windows it could enumerate loaded libraries and call `GetExport` on each.)

**Comment by am11** [comment]
In .NET 7, we can use:

```diff
- var RTLD_DEFAULT = IntPtr.Zero;
+ var RTLD_DEFAULT = NativeLibrary.GetMainProgramHandle();
```

**Comment by AaronRobinsonMSFT** [comment]
Something to consider for 8. I'm inclined to agree with @DaZombieKiller that this is likely best accomplished in a new API proposal, however I'm not convinced it is common enough to warrant even that. Leaving this open for 8 will help us gauge community interest.

**Comment by jkoritzinsky** [comment]
I think this scenario has already been sufficiently supported with the API that @am11 referenced. But if there’s enough interest, I could see adding another convenience API on top of it.

**Comment by jkoritzinsky** [comment]
Given that there has been no additional interest on this in a year, I think the existing `NativeLibrary.GetMainProgramHandle()` API provides a nice enough experience and that we don't need to introduce an additional API here.
