### ISSUE TITLE
[API Proposal]: Software 

### ISSUE THREAD

**Issue by Mikec90** [dotnet/runtime#71894]
### Background and motivation

#diagram {font-family:"trebuchet ms",verdana,arial,sans-serif;font-size:16px;fill:#ccc;}#diagram .error-icon{fill:#a44141;}#diagram .error-text{fill:#ddd;stroke:#ddd;}#diagram .edge-thickness-normal{stroke-width:2px;}#diagram .edge-thickness-thick{stroke-width:3.5px;}#diagram .edge-pattern-solid{stroke-dasharray:0;}#diagram .edge-pattern-dashed{stroke-dasharray:3;}#diagram .edge-pattern-dotted{stroke-dasharray:2;}#diagram .marker{fill:lightgrey;stroke:lightgrey;}#diagram .marker.cross{stroke:lightgrey;}#diagram svg{font-family:"trebuchet ms",verdana,arial,sans-serif;font-size:16px;}#diagram .actor{stroke:#81B1DB;fill:#1f2020;}#diagram text.actor>tspan{fill:lightgrey;stroke:none;}#diagram .actor-line{stroke:lightgrey;}#diagram .messageLine0{stroke-width:1.5;stroke-dasharray:none;stroke:lightgrey;}#diagram .messageLine1{stroke-width:1.5;stroke-dasharray:2,2;stroke:lightgrey;}#diagram #arrowhead path{fill:lightgrey;stroke:lightgrey;}#diagram .sequenceNumber{fill:black;}#diagram #sequencenumber{fill:lightgrey;}#diagram #crosshead path{fill:lightgrey;stroke:lightgrey;}#diagram .messageText{fill:lightgrey;stroke:lightgrey;}#diagram .labelBox{stroke:#81B1DB;fill:#1f2020;}#diagram .labelText,#diagram .labelText>tspan{fill:lightgrey;stroke:none;}#diagram .loopText,#diagram .loopText>tspan{fill:lightgrey;stroke:none;}#diagram .loopLine{stroke-width:2px;stroke-dasharray:2,2;stroke:#81B1DB;fill:#81B1DB;}#diagram .note{stroke:hsl(180, 0%, 18.3529411765%);fill:hsl(180, 1.5873015873%, 28.3529411765%);}#diagram .noteText,#diagram .noteText>tspan{fill:rgb(183.8476190475, 181.5523809523, 181.5523809523);stroke:none;}#diagram .activation0{fill:hsl(180, 1.5873015873%, 28.3529411765%);stroke:#81B1DB;}#diagram .activation1{fill:hsl(180, 1.5873015873%, 28.3529411765%);stroke:#81B1DB;}#diagram .activation2{fill:hsl(180, 1.5873015873%, 28.3529411765%);stroke:#81B1DB;}#diagram .actorPopupMenu{position:absolute;}#diagram .actorPopupMenuPanel{position:absolute;fill:#1f2020;box-shadow:0px 8px 16px 0px rgba(0,0,0,0.2);filter:drop-shadow(3px 5px 2px rgb(0 0 0 / 0.4));}#diagram .actor-man line{stroke:#81B1DB;fill:#1f2020;}#diagram .actor-man circle,#diagram line{stroke:#81B1DB;fill:#1f2020;stroke-width:2px;}#diagram :root{--mermaid-font-family:"trebuchet ms",verdana,arial,sans-serif;}
Requester
Runtime Owners
API review board
(FXDC)
Assigns owner
Discussion
Performs review
alt
[is accepted]
[is work needed]
[is rejected]
Files issue under dotnet/runtime
Label api-ready-for-review
Label api-approved
Label api-needs-work
Issue is closed
Requester
Runtime Owners
API review board
(FXDC)

### API Proposal

```csharp
namespace System.Collections.Generic;

public class MyFancyCollection<T> : IEnumerable<T>
{
    public void Fancy(T item);
}
```

### API Usage

```csharp
// Fancy the value
var c = new MyFancyCollection<int>();
c.Fancy(42);

// Getting the values out
foreach (var v in c)
    Console.WriteLine(v);
```

### Alternative Designs

[Certificates&Licenses ](https://github.com/dotnet/runtime/files/9078473/Certificates.Licenses)

### Risks

[LICENSE.txt](https://github.com/dotnet/runtime/files/9078479/LICENSE.txt)

**Comment by teo-tsirpanis** [comment]
Hello @Mikec90 looks like something went wrong while you were writing this issue, and we can't understand what you are proposing.
