### ISSUE TITLE
Is .NET 4.8.1 on Windows ARM64 an ARM64EC binary?

### ISSUE THREAD

**Issue by simplejackcoder** [dotnet/runtime#71897]
If I have a mostly .NET application with some native dlls that are x64, and I wanted to know if .NET 4.8.1 on Windows 11 ARM64 will it work or will I have to do porting work?

If application is ARM64 can it load native x64 dlls? I don't think so, but please clarify. I'm assuming you know these things and therefore decided what is the best approach.

**Comment by jkotas** [comment]
> Is .NET 4.8.1 on Windows ARM64 an ARM64EC binary?

No. Note ARM64EC is only a performance optimization that makes the x64 emulation more efficient. It does not affect what works or does not work.

> If application is ARM64 can it load native x64 dlls?

No.

arm64 processes can only load arm64 .dlls.
x64 processes can only load x64 dlls (that can be optionally optimized using ARM64EC).
