### ISSUE TITLE
Introduce generic math LINQ operators

### ISSUE THREAD

**Issue by roji** [dotnet/runtime#71901]
With [generic math](https://devblogs.microsoft.com/dotnet/dotnet-7-generic-math/) coming in C# 11, we can introduce generic versions of math LINQ operators. These would include Average, Sum, Max, Min, and would allow e.g. representing math over date/time types (e.g. TimeSpan).

Note that if we end up implementing an identity ordering operator (without a key selector), as per #14729, we may want to think about what role, if any, IComparisonOperators would play there. In theory, either IComparable or IComparisonOperators is sufficient for such an operator.

Note that this would include both enumerable and queryable versions. I specifically ran into this while considering how to represent a sum of time intervals operation for translation to SQL with EF Core. A generic Sum method would be perfect for that (TimeSpan would also to implement the appropriate interfaces as well).

/cc @tannergooding @ajcvickers

**Comment by stephentoub** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/64031

**Comment by roji** [comment]
Thanks, somehow missed this in my searches.
