### ISSUE TITLE
[API Proposal]: IBinaryInteger<TSelf> read methods

### ISSUE THREAD

**Issue by binarycow** [dotnet/runtime#71902]
### Background and motivation

When writing libraries that work with arbitrary types, the new "generic math" types are extremely useful.  There does seem, however, to be a small gap in `IBinaryInteger<TSelf>`.  

The `IBinaryInteger<TSelf>` interface specifies that a binary integer knows how to _write_ itself to a `Span<byte>`, but it doesn't know how to _read_ itself back from the same span - no round-trip read/write is possible, in a generic way.

Without this possibility, any library developers who rely on this feature need to further constrain their generic arguments, use pass type-specific read delegates, or some other solution.

----

This proposal is to add the following methods to `IBinaryInteger<TSelf>`, as counterparts to the `TryWrite` and `Write` methods.

### API Proposal

```diff
namespace System.Numerics;
public interface IBinaryInteger<TSelf>
    : IBinaryNumber<TSelf>,
      IShiftOperators<TSelf, int, TSelf>
    where TSelf : IBinaryInteger<TSelf>
{ 
+    public static abstract TSelf ReadBigEndian(byte[] source, bool isUnsigned);
+    public static abstract TSelf ReadBigEndian(byte[] source, int startIndex, bool isUnsigned);
+    public static abstract TSelf ReadBigEndian(ReadOnlySpan<byte> source, bool isUnsigned);

+    public static abstract TSelf ReadLittleEndian(byte[] source, bool isUnsigned);
+    public static abstract TSelf ReadLittleEndian(byte[] source, int startIndex, bool isUnsigned);
+    public static abstract TSelf ReadLittleEndian(ReadOnlySpan<byte> source, bool isUnsigned);

+    public static abstract bool TryReadBigEndian(ReadOnlySpan<byte> source, bool isUnsigned, out TSelf value);
+    public static abstract bool TryReadLittleEndian(ReadOnlySpan<byte> source, bool isUnsigned, out TSelf value);
}
```

### API Usage

```csharp
var someInputData = new byte[] { 0x00, 0x00, 0x04, 0xD2 };
var outputData = new byte[4];
ProcessData<int>(
   someInputData,
   value => value + 2000,
   outputData
);
Console.WriteLine(outputData); // Prints 00000CA2


static void ProcessData<T>(
    ReadOnlySpan<byte> inputData,
    Func<T, T> process,
    Span<byte> outputData
) where T : IBinaryInteger<T>
{
    var value = T.ReadBigEndian(inputData);
    value = process(value);
    value.WriteBigEndian(outputData);
}
```

At the present time, this example would only work if the `ProcessData` method was implemented in a non-generic way.

```csharp
static void ProcessData(
    ReadOnlySpan<byte> inputData,
    Func<int, int> process,
    Span<byte> outputData
)
{
    var value = BinaryPrimitives.ReadInt32BigEndian(inputData);
    value = process(value);
    BinaryPrimitives.WriteInt32BigEndian(outputData, value);
}
```

**Comment by Sergio0694** [comment]
@binarycow you forgot to add a title to the issue (it just says "[API Proposal]: "), make sure to add one 🙂

**Comment by jeffhandley** [comment]
@tannergooding what do you think about this? Should we consider it for 7.0?

**Comment by tannergooding** [comment]
This would be reasonable to take back to API review for consideration in .NET 7. It's a concept we had discussed briefly in API review but where we didn't have a clear scenario or need for it.

We do notably have "similar" APIs on other types (like the `Vector` types) and in `BinaryPrimitives`, so having parity where the request exists would and since the work is "simple" to expose is likely worth considering.

**Comment by tannergooding** [comment]
Updated the proposal to include the array overloads that would be required.

There is a note that this API has a consideration around handling of inputs. Consider for a generic `TSource, TDestination` given `where TSource : IBinaryInteger<TSource>` and `where TDestination : IBinaryInteger<TDestination>`.

The output of `TryWrite`/`Write` is a contiguous two's complement number that may or may not have non-signficiant data (e.g. `Write` for an `int` always writes `4-bytes` even for the value `0`, while for `BigInteger` it will emit 1-byte representing the shortest sequence).

This requires a consideration on whether `TryRead`/`Read` should work like `BinaryPrimitives` where it reads the first `n-bytes` (e.g. `int` always expects 4-bytes and reads 4-bytes) or if it behaves more like `BigInteger` and expects "any Write output", so `int.Read` could handle the output of `byte.Write` for example.

The latter, to me, seems more useful and intuitive given these will (at least for the BCL types) will only be accessible via the generic context. This would mean that `source` is always treated as an exact two's complement number and would need to handle "shorter" inputs (e.g. `int` could handle spans of `0, 1, 2, 3, or 4` length) and potentially longer inputs where the leading data is zero (e.g. `int` could handle the output of `Write` for `long` provided it "fits").

**Comment by tannergooding** [comment]
There may also be a needed consideration of whether to interpret the input as "signed" or "unsigned". Both `uint.MaxValue` and `-1` (as an `int`) will give back `0xFF, 0xFF, 0xFF, 0xFF`. One is a valid conversion for any signed number but invalid for unsigned numbers.

**Comment by cpurdy999** [comment]
In almost all cases I would be using this I would be writing and reading the same type, so I really like Immo's idea of providing a default of assume source matches `TSelf`

**Comment by terrajobst** [comment]
* Looks good as proposed.
    - Note: The top six will all be DIM'ed

```diff
namespace System.Numerics;

public interface IBinaryInteger<TSelf>
    : IBinaryNumber<TSelf>,
      IShiftOperators<TSelf, int, TSelf>
    where TSelf : IBinaryInteger<TSelf>
{ 
+    public static virtual TSelf ReadBigEndian(byte[] source, bool isUnsigned);
+    public static virtual TSelf ReadBigEndian(byte[] source, int startIndex, bool isUnsigned);
+    public static virtual TSelf ReadBigEndian(ReadOnlySpan<byte> source, bool isUnsigned);

+    public static virtual TSelf ReadLittleEndian(byte[] source, bool isUnsigned);
+    public static virtual TSelf ReadLittleEndian(byte[] source, int startIndex, bool isUnsigned);
+    public static virtual TSelf ReadLittleEndian(ReadOnlySpan<byte> source, bool isUnsigned);

+    public static abstract bool TryReadBigEndian(ReadOnlySpan<byte> source, bool isUnsigned, out TSelf value);
+    public static abstract bool TryReadLittleEndian(ReadOnlySpan<byte> source, bool isUnsigned, out TSelf value);
}
```

**Comment by filipnavara** [comment]
I feel there's a weird disparity between the Write methods (eg. `uint.TryWriteBigEndian`) that write 4 bytes without telling you whether it is signed or unsigned (and which don't zero-prefix unsigned numbers with MSB set). If you wanted to use a combination of a generic write (`TryWriteBigEndian`) followed by generic read (`TryReadBigEndian`) what would you pass for `isUnsigned` if you really know nothing about the source and target type?

I assume it's fine to ignore this if this scenario is not expected to mix signed/unsigned types, or if this scenario is ignored completely. Or is there a way in generic math to determine if the source type was unsigned-only?

**Comment by tannergooding** [comment]
> what would you pass for isUnsigned if you really know nothing about the source and target type?

All number types expose the relevant information here. You can always determine if the source value is positive or negative (and therefore unsigned or signed). You can determine if the destination type is signed or unsigned as well (via properties or via `is IUnsignedNumber` and `is ISignedNumber`).

**Comment by giladfrid009** [comment]
I don't understand the need for `isUnsigned` parameter.
After all, the class / struct that implements the interface knows if it's value is signed or not, and even if it's passed to a generic method as `IBinaryInteger` the implementation itself is already correct.
for example:
`Int32` will implement read methods as `signed`
`UInt32` will implement read methods as `unsigned`

When both passed to a generic method, the behavior will be correct in both cases.

```csharp
T ReadValue<T>(byte[] byteArray) where T : IBinaryInteger<T>
{
    // something happens

    return T.ReadLittleEndian(byteArray); // should read correctly for both Int32 and UInt32
}
```

**Comment by filipnavara** [comment]
> The write API requires it be emitted as a two's complement value that is GetByteCount() bytes in length. This makes it always well-defined and interpretable, provided you also specify if that value was signed or unsigned.

I agree, it just felt awkward at first sight.

> I don't understand the need for `isUnsigned` parameter. After all, the class / struct that implements the interface knows if it's value is signed or not...

It doesn't always know. For `BigInteger` the bytes `0xff_ff_ff` could mean a different thing whether it is defined as signed or unsigned (unless you enforce `0x00`-byte prefix as a differentiator). For other types it could differentiate between negative value and an overflow.

**Comment by cpurdy999** [comment]
After all the confusion over isUnsigned (I also didn't understand the need for it initially) I think it's really important that it's called out in the docs why you need it, and probably a code example of what a user should do if their expectation is that they're consuming the output of an equivalent `Write` call for the TSelf they're given. (Effectively this would be the implementation of the default overload that Immo suggested in the review).

I wouldn't be surprised if this was the most common use case for this code.

**Comment by acaly** [comment]
> If you then want to read it as a `T` via `ReadLittleEndian`

> You also end up with an issue where going from a big type (e.g. `long`) to a small type (e.g. `int`) results in truncation of the bits

In what cases are we supposed to read as a different type? If we support reading a `int` as `uint` and `long`, why shouldn't we support reading `int` as other types like `float`? In that case, what should we check?

You may argue that `int` and `uint` shares some binary representation, but that isn't true for `long`. Note that when you read the `long` `0xFFFFFFFF00000000` into `int`, if you take the low 32-bit, you lost the sign; if you take the high 32-bit, the value you get no longer represents any meaningful `int` value related to the original `long`, except that they somehow have the same sequence of bits. And it is exactly the same when going from `int` to `float`.
