### ISSUE TITLE
GRPC error after upgrading from .netcoreapp3.1 to .net5 or .net6

### ISSUE THREAD

**Issue by bartosz-jarmuz** [dotnet/runtime#71906]
### Description

Hello,

I have a .netcore3.1 integration test project which calls a GRPC service.
**The service is only available via HTTP**. I cannot change the service now.

When I update the project to .net5-windows or .net6-windows **(literally only a *.csproj change),** the calls fail with the following error:

> Grpc.Core.RpcException : Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: An error occurred while sending the request. IOException: The request was aborted. Http2ConnectionException: The HTTP/2 server sent invalid data on the connection. HTTP/2 error code 'PROTOCOL_ERROR' (0x1).", DebugException="System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: The request was aborted. ---> System.Net.Http.Http2ConnectionException: The HTTP/2 server sent invalid data on the connection. HTTP/2 error code 'PROTOCOL_ERROR' (0x1). at System.Net.Http.Http2Connection.ThrowProtocolError(Http2ProtocolErrorCode errorCode) at System.Net.Http.Http2Connection.ReadFrameAsync(Boolean initialFrame) at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync() --- End of inner exception stack trace --- at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException) at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState() at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders() at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken cancellationToken) at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at Grpc.Net.Client.Web.GrpcWebHandler.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.HttpClient.g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) at Grpc.Net.Client.Internal.GrpcCall2.RunCall(HttpRequestMessage request, Nullable1 timeout)") at..

I have tried a few options of setting AppContext (even though they should apply for netcore3.1) like this before initializing a client, but again no help:

```
  AppContext.SetSwitch(“System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport”, true);
  AppContext.SetSwitch(“System.Net.Http.SocketsHttpHandler.Http2Support”, true);
```
The channel is initialized as follows:

```
 var baseUri = new Uri(baseUrl);
        HttpMessageHandler httpMessageHandler = new HttpClientHandler();
        if (baseUri.AbsolutePath != "/")
            httpMessageHandler = new SubDirectoryHandler(httpMessageHandler, baseUri.AbsolutePath);
        var handler = new GrpcWebHandler(GrpcWebMode.GrpcWebText, httpMessageHandler);
        _channel = GrpcChannel.ForAddress(baseUrl, new GrpcChannelOptions { HttpClient = new HttpClient(handler) });
```

Inspecting the GRPC channel before sending the request shows the request version is 1.1 (regardless of AppContext settings and TargetFramework):

![image](https://user-images.githubusercontent.com/33833009/178153574-b5c75b83-416a-415d-afae-b09682af5c7a.png)

### Reproduction Steps

n/a

### Expected behavior

Changing the <TargetFramework> of the project should not affect the GRPC connection.

### Actual behavior

Changing the <TargetFramework> of the project from .netcoreapp3.1 to .net5, .net6 and .net7 causes the error to happen.

### Regression?

Worked in 3.1

### Configuration

Windows 10 64bit

Grpc.Net.Client v. 2.42.0
Grpc.Net.Client.Web v. 2.42.0

### Other information

When the request is sent, the service side is logging the following in the output:

> Exception thrown: 'Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException' in Microsoft.AspNetCore.Server.Kestrel.Core.dll
> Exception thrown: 'Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException' in System.Private.CoreLib.dll 'TradingOrchestrationService.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\6.0.5\Microsoft.AspNetCore.WebUtilities.dll'.
> Exception thrown: 'System.Net.Sockets.SocketException' in Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.dll
> The I/O operation has been aborted because of either a thread exit or an application request.
>

**Comment by wfurt** [comment]
I think the expectation is to use [HttpClient.DefaultVersionPolicy]( https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultversionpolicy?view=net-6.0) that was introduced in 5.0

cc: @JamesNK for more thoughts how to do H2C from GRPC.

**Comment by JamesNK** [comment]
> **The service is only available via HTTP**

What protocol is Kestrel configured to use? HTTP/1.1 or HTTP/2? If you haven't explicitly configured it to only HTTP/2 then it will probably be HTTP/1.1.

`GrpcWebHandler` has a `HttpVersion` property on it that you can set to explicitly specify what HTTP version you want. You could try setting it to `new Version(1, 1)`.

**Comment by JamesNK** [comment]
> And when we migrate the server to use HTTP/2, I suppose it will have to be removed?

Yes

What happened to you: in .NET Core 3.x the client was configuring the gRPC request to be HTTP/2, but because you were using TLS the request was silently downgraded to HTTP/1.1

That was fixed in .NET 5+. The client was now sending HTTP/2 over http, but your server was configured for HTTP/1.1. That creates a protocol error. `GrpcWebHandler.HttpVersion` provides a way to specify exactly what you want (because gRPC-Web works with both HTTP versions).
