### ISSUE TITLE
[jitstress-isas-x86] Assertion failed 'compiler->compIsaSupportedDebugOnly(isa)' during 'Generate code'

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#71928]
The jitstress-isas-x86 pipeline is frequently failing with this assertion failure in many tests.
Example pipeline run: https://dev.azure.com/dnceng/public/_build/results?buildId=1870359&view=results

```scala
Assert failure(PID 7472 [0x00001d30], Thread: 9756 [0x261c]): Assertion failed 'compiler->compIsaSupportedDebugOnly(isa)' in 'HillClimbing:Update(int,double,int):System.ValueTuple`2[Int32,Int32]:this' during 'Generate code' (IL size 1472; hash 0x27d1e134; FullOpts)
```

**Comment by jakobbotsch** [comment]
This is a relatively recent regression, the June 18th run does not have this problem while June 25th does.

**Comment by jakobbotsch** [comment]
From a bisection this seems to be introduced/exposed by #69434. @tannergooding do you have an idea why that could cause this problem?

**Comment by tannergooding** [comment]
I expect there is a mismatched check around the "baseline" ISAs (SSE/SSE2) and `COMPlus_EnableSSE2=0` being set. Will take a look

**Comment by JulieLeeMSFT** [comment]
[runtime-coreclr jitstress-isas-x86](https://runfo.azurewebsites.net/view/definition/664/) is constatnly failing.

![image](https://user-images.githubusercontent.com/63486087/179843348-2f219c23-e470-4769-87b3-901c0383a3de.png)
