### ISSUE TITLE
System.Text.Json fast path serialization not working with combined contexts

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#71933]
**EDIT: See API proposal at the bottom of this post.**

The internal logic governing use of fast path serialization is dependent on `JsonSerializerOptions` encapsulating a `JsonSerializerContext` instance. Consider:

https://github.com/dotnet/runtime/blob/7d2be1e66992c8510b8c4f899cbcfa9e88c22325/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/JsonMetadataServicesConverter.cs#L72-L80

or

https://github.com/dotnet/runtime/blob/7d2be1e66992c8510b8c4f899cbcfa9e88c22325/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/SourceGenJsonTypeInfoOfT.cs#L130-L134

or

https://github.com/dotnet/runtime/blob/26da83df77b2391d6a74a4f24b663dc2fb4eda3f/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs#L452-L455

The introduction of contract customization has made it possible for source generated metadata to be associated with options instances not attached to a `JsonSerializerContext`. This can result in inconsistency, consider:

```C#
[JsonSourceGenerationOptions(GenerationMode = JsonSourceGenerationMode.Serialization)]
[JsonSerializable(typeof(HighLowTemps))]
public partial class SerializationContext : JsonSerializerContext {}

public class HighLowTemps
{
    public int High { get; set; }
    public int Low { get; set; }
}

[Fact]
public static void CombiningContexts_FastPathSerialization()
{
    var value = new HighLowTemps { High = 40, Low = 30 };
    string expectedJson = """{"High":40,"Low":30}""";

    // Sanity check -- default context
    var options = new JsonSerializerOptions { TypeInfoResolver = SerializationContext.Default };
    string json = JsonSerializer.Serialize(value, options);
    Assert.Equal(expectedJson, json);

    // Using a trivial combined context
    options = new JsonSerializerOptions { TypeInfoResolver = JsonTypeInfoResolver.Combine(SerializationContext.Default) };
    json = JsonSerializer.Serialize(value, options);  // 'JsonSerializerContext' '<null>' did not provide property metadata
                                                      // for type 'System.Text.Json.SourceGeneration.Tests.HighLowTemps'.
    Assert.Equal(expectedJson, json);
}
```
In order to get the issue fixed, it is necessary for source gen `JsonTypeInfo<T>` to encapsulate a reference to their originating `JsonSerializerContext`. 

## API Proposal

```C#
namespace System.Text.Json.Serialization.Metadata;

public class JsonTypeInfo
{
    public IJsonTypeInfoResolver? OriginatingResolver { get; set; } = null;
}
```

**Comment by krwq** [comment]
I'm aware of the issue although I'd take slightly different approach to the fix. Rather than trying to preserve this logic I'd focus on what `info.Options.SerializerContext?.CanUseSerializationLogic == true` is doing.

IMO following approach should be taken:
- we change implementation of IJsonTypeInfoResolver.GetTypeInfo for context to compare options with generated options and only if those are equivalent only then we generate SerializeHandler for type info
- SerializeHandler is always used (minus perhaps some some compat layer so that code generated in previous versions continue working)

**Comment by bartonjs** [comment]
Looks good as proposed.  Based on discussion it seems like EditorBrowsable(Never) is justified, since it's mostly distracting to callers outside of the serializer/sourcegen dichotomy.

```C#
namespace System.Text.Json.Serialization.Metadata;

public class JsonTypeInfo
{
    [EditorBrowsable(EditorBrowsableState.Never)]
    public IJsonTypeInfoResolver? OriginatingResolver { get; set; } = null;
}
```
