### ISSUE TITLE
[crossgen2-composite gcstress] OSX x64 failures with "External disassembler is not available"

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#71931]
This pipeline has widespread OSX x64 failures. Does not seem to be anything new.
Example pipeline run: https://dev.azure.com/dnceng/public/_build/results?buildId=1845930&view=results
Helix job name: R2R-CG2 OSX x64 Checked gcstress0xc_zapdisable_jitstress2
Example log (large): https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-48eb053a58cc4b6d93/JIT.Directed/1/console.5620044a.log?helixlogtype=result

```scala
    JIT/Directed/shift/int64_do/int64_do.sh [FAIL]
      cp: /tmp/helix/working/B50D0A38/p/libsuperpmi-shim-simple.dylib is not a directory
      External disassembler is not available.
      BEGIN: coreclr_initialize failed - Error: 0x80004005
      END: coreclr_initialize failed - Error: 0x80004005
```

**Comment by BruceForstall** [comment]
This is unrelated to the main issue, but why do we see `cp: /tmp/helix/working/B50D0A38/p/libsuperpmi-shim-simple.dylib is not a directory`?

**Comment by BruceForstall** [comment]
AFAIK, osx-x64 GCStress has never been enabled. https://github.com/dotnet/runtime/issues/6135 is still open. And our gcstress0x3-gcstress0xc and gcstress-extra pipelines don't do it.

**Comment by jakobbotsch** [comment]
> This is unrelated to the main issue, but why do we see `cp: /tmp/helix/working/B50D0A38/p/libsuperpmi-shim-simple.dylib is not a directory`?

Looks like that is coming from this line of bash:
https://github.com/dotnet/runtime/blob/cf8327316337d7909a00e6207c7335adf1078f04/src/tests/Common/CLRTest.CrossGen.targets#L65
I guess `scriptPath` is not set to anything so this is incorrect syntax, cc @trylek

**Comment by kunalspathak** [comment]
This is also seen to be happening in [runtime-coreclr crossgen2-composite gcstress](https://dev.azure.com/dnceng/public/_build/results?buildId=1928978&view=ms.vss-test-web.build-test-results-tab&runId=49871392&resultId=107162&paneView=debug). 

> AFAIK, osx-x64 GCStress has never been enabled

If that is the case, I will probably disable OSX-x64 from this pipeline?

**Comment by mangod9** [comment]
@jakobbotsch assume this is not required for 8?

**Comment by jakobbotsch** [comment]
No, I've moved it to 9.0.

**Comment by steveisok** [comment]
if this still does not work for osx-x64, I think it's safe to close this issue.
