### ISSUE TITLE
System.Text.Json serialization callbacks not supported by collection types

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#71945]
The System.Text.Json [serialization callbacks](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.ijsononserializing?view=net-6.0) are currently not supported by collection/dictionary converters, even though they could be. The [newly released callback APIs](https://github.com/dotnet/runtime/issues/71123) in the System.Text.Json contract model reflect that behavior, but we should consider changing that in the future.

**Comment by krwq** [comment]
ref: https://github.com/dotnet/runtime/issues/30258

**Comment by eiriktsarpalis** [comment]
Moving to Future as we won't be able to work on this for 8.0
