### ISSUE TITLE
Improve Interop.Sys.ReadLink error handling

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#71970]
Some of the callers ignore all Interop.Sys.ReadLink (including the unexpected errors) and assumed that null means that the link does not exist.

Context: https://github.com/dotnet/runtime/pull/69335#issuecomment-1179212859

**Comment by adamsitnik** [comment]
@pedrobsaila would you be interested in fixing this issue?

**Comment by Jozkee** [comment]
Closing this one as it was investigated in https://github.com/dotnet/runtime/pull/72258#issuecomment-1199985566.
I created individual issues to be addressed by each area:
https://github.com/dotnet/runtime/issues/73812
https://github.com/dotnet/runtime/issues/73813
https://github.com/dotnet/runtime/issues/73815
