### ISSUE TITLE
Error while building main branch of runtime

### ISSUE THREAD

**Issue by mayadav1** [dotnet/runtime#71996]
I am facing below error message while building main branch of runtime .

ninja: error: mkdir(libs-native/System.IO.Compression.Native/CMakeFiles/System.IO.Compression.Native-Static.dir/C_/Us
  ers/mayadav1/Desktop/manoj/net7mainbranch/runtime/src/native/external): No such file or directory
  ninja: build stopped: .
  BUILD: Error: native component build failed. Refer to the build log files for details.
      "C:\Users\mayadav1\Desktop\manoj\net7mainbranch\runtime\src\coreclr\..\..\artifacts\log\Release\CoreCLR_windows__
  x64__Release__x64.log"
      "C:\Users\mayadav1\Desktop\manoj\net7mainbranch\runtime\src\coreclr\..\..\artifacts\log\Release\CoreCLR_windows__
  x64__Release__x64.wrn"
      "C:\Users\mayadav1\Desktop\manoj\net7mainbranch\runtime\src\coreclr\..\..\artifacts\log\Release\CoreCLR_windows__
  x64__Release__x64.err"

**Comment by agocke** [comment]
Is the `src/native/external` directory present, with all the expected files?

**Comment by mayadav1** [comment]
@agocke , Thank you for addressing my issue . Sorry to say, big depth of path was issue of  src/native/external , I reduced depth of path, it works for me.

Thanks.
