### ISSUE TITLE
improve `you must install .NET Desktop Runtime` with the `updater of .NET Framwork` UI, instead of a weird window

### ISSUE THREAD

**Issue by NewUserHa** [dotnet/runtime#71993]
the .NET Framwork has a nice wizard to one-click to install the required version .NET Framwork. However dotnet core has only a simple error window to ask users to download it by hand.

![image](https://user-images.githubusercontent.com/32261870/178409770-6d5b7c85-1fd9-49a6-a831-6cbcc744f4f2.png)
*To users, this seems like a blur and suspicious, and untrust window that also has a sawtooth icon*

Already seen https://github.com/dotnet/core/issues/6411, and in which it does make sense impossible pre-include a best version to windows.

But I think .NET 5+ can use that updater for better integration and can also bringing new features of .NET to Microsoft Windows platform easily, instead of a weird and untrust error window popup to ask to download something, which makes end users feel inconvenient, and also unwilling to use .NET 5+

**Comment by vitek-karas** [comment]
This has been discussed at length here: https://github.com/dotnet/runtime/issues/3816. https://github.com/dotnet/runtime/issues/71288 is also related (and there are other issues about basically the same thing).
We are reconsidering improving this in .NET 8.

Please note that it can't (should not) use the same UI as .NET Framework - .NET Framework is part of Windows OS itself. .NET (5+) is not part of the OS. So there's a general limitation of how much UX we can offer - the code to offer such UX would have to be part of every single .NET application ever built - so there's a very valid size concern (among other things). Unlike .NET Framework where the nice UX is part of the OS (and supports not just .NET Framework but many other parts of Windows).

If you have additional feedback/ideas, probably this issue is the best venue: https://github.com/dotnet/runtime/issues/71284

**Comment by NewUserHa** [comment]
I think since .NET Framework will not get newer versions and .NET 5+ is the successor, so Microsoft Windows should have a nice way to get the cool features from the newer version .NET.
an advantage of .NET is that it does need not users to download runtime, since it's supported by the OS. Therefore I think Microsoft Windows should keep supporting the .NET 5+ just like it supports the old .NET Framework.

BTW, the feature itself is not that important, but it can be a plus that makes .NET become more popular if windows can easily run .NET 5+ apps without installing something manually that other programming languages need.
So maybe still mark this feature as high priority?

I don't think every single .NET app have some built-in code to prompt this. since Windows still should be the main platform, it should support it as always. but for other platforms like *nix, BSD, a error window may be enough, just like other language runtimes.
But on Windows, .NET 5+ shouldn't be treat as a 3rd part software.

**Comment by NewUserHa** [comment]
should post the above one to https://github.com/dotnet/runtime/issues/71284?

**Comment by richlander** [comment]
I'll respond here. 

> But on Windows, .NET 5+ shouldn't be treat as a 3rd part software.

We decided against integrating .NET Core into Windows, back before 1.0 shipped. We want new .NET versions to be available in all supported Windows versions on .NET ship dates. That includes previews. That's not possible with software that is integrated into Windows. While I agree that there would be some advantages if .NET 6 was built into Windows, there would be significant disadvantages.

We also wanted to make clear that Windows was not special. We wanted to offer a cross-platform version of .NET where all OSes were the same. If .NET ended up being more popular on Linux or macOS than on Windows, that was fine with us. We wanted to be open to all possibilities. Making Windows different and special didn't (and still doesn't) seem like a good approach for messaging our intent to the community.

> better UI

We are going to think more about that.

**Comment by NewUserHa** [comment]
> We want new .NET versions to be available in all supported Windows versions on .NET ship dates.

I didn't mean "integrate .NET core to windows", I mean Windows benefit from .NET(including .net framework), so windows should provide a nice way for end-users to update/download .NET 5+ runtime, instead of something like JRE

> We also wanted to make clear that Windows was not special

I didn't say .NET should treat windows special.
I mean since .NET 5+ is the successor of .NET Framework, it should benefit from that updater UI from windows too, which is cool, compared to the built-in code prompt thing.
otherwise, devs may have a chance to prefer .NET Framework since it's friendly to end-users

**Comment by vitek-karas** [comment]
Not a solution, but related: We do offer updates (not clean installs) of .NET through Microsoft Update.

**Comment by NewUserHa** [comment]
but win10 users still get that blur error window, when use .NET 6 apps, so I think the UI updater from .NET Framework should be the better solution.

**Comment by richlander** [comment]
Which UI updater are you thinking of? Is that the one for .NET Framework 3.5 apps? If so, that's only available to Windows components.

**Comment by NewUserHa** [comment]
maybe it is?
because .NET Framework eventually will become outdate, so better make that useful for the new .NET 5+? This way can also make .NET 5+ more popular as well!

**Comment by richlander** [comment]
Are you referencing this dialog?

https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows

We don't have access to that. It isn't a feature available to third parties (which we are in this context).

**Comment by richlander** [comment]
We won't be able to build an experience like feature on demand. Windows does not have a third party solution like that and we don't have a good technical path to building one.

**Comment by NewUserHa** [comment]
know that.

Hope windows team can think about giving some support, to keep ability to update .NET Framework to required versions of .NET 5+

**Comment by richlander** [comment]
We will see if something develops on that front. Thanks for the feedback.

**Comment by NewUserHa** [comment]
Thanks.
