### ISSUE TITLE
TypeConverter.ConvertFrom does not support trimming but is not attributed as such.

### ISSUE THREAD

**Issue by Tanya-Solyanik** [dotnet/runtime#72006]
### Description

For example: https://source.dot.net/#System.ComponentModel.TypeConverter/System/ComponentModel/TypeConverter.cs,49

Type to convert to/from is passed in as a System.Object type which is cast to a string representing type name or a Type descriptor. Object type is not working well with assembly trimming and winforms code has to add opt-out attributes - 
```
            [UnconditionalSuppressMessage(
                "AssemblyLoadTrimming",
                "IL2046",
                Justification = "Will remove this suppression when TypeConverter adds RequiresUnreferencedCode attribute to theits corresponding method.")]
            [RequiresUnreferencedCode(TrimmingConstants.TypeConverterValueWarning)]
            public override object ConvertFrom(
                ITypeDescriptorContext context,
                CultureInfo culture,
                object value)
```

https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.requiresunreferencedcodeattribute?view=net-6.0
and
https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.unconditionalsuppressmessageattribute.-ctor?view=net-6.0

to winforms' implementation of ConvertFrom method. https://github.com/dotnet/winforms/pull/7376/commits/0ff6e85c994992e07d6dc3adc4afd1207ddd0efe in order to enable build against the newest Arcade.

### Reproduction Steps

https://github.com/dotnet/winforms/pull/7376

### Expected behavior

```
        [RequiresUnreferencedCode("TypeConverters might not work correctly when trimming application code because types represented by `value` parameter cannot be statically discovered by the trimmer."
)]
        public virtual object? ConvertFrom(ITypeDescriptorContext? context, CultureInfo? culture, object value)
        {
            if (value is InstanceDescriptor instanceDescriptor)
            {
                return instanceDescriptor.Invoke();
            }
            throw GetConvertFromException(value);
        }
```

### Actual behavior

Convertfrom is not decorated with RequiresUnreferencedCode attribute, thus derived classes are required to suppress [IL2046](https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-warnings/il2046) warning

### Known Workarounds

Suppress IL2046 warning

**Comment by eerhardt** [comment]
Not all TypeConverters require unreferenced code, and the contract itself -`TypeConverter.ConvertFrom` - doesn't inherently require unreferenced code. For example converting the string `"4.5"` to the double `4.5` doesn't require unreferenced code.

I don't think we should mark the virtual method as `RequiresUnreferencedCode`. Instead, if you have a derived TypeConverter that is not trim-safe, you can mark its constructors as `RequiresUnreferencedCode` and suppress the `IL2046` warning. We do that in a lot of places in the BCL.

cc @vitek-karas

**Comment by eerhardt** [comment]
Closing per the above comment. TypeConverter.ConvertFrom can be implemented in trim-friendly fashions. The TypeConverters that inherit from it may not be trim compatible. Those should be marked RequiresUnreferencedCode themselves.
