### ISSUE TITLE
[QUIC] QuicConnection API follow up

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#72027]
- [ ] it should AFAIK. It would be nice to have some assert about it. It differs among platforms but MsQUIC now uses native layout e.g. same as SocketAddress.

_Originally posted by @wfurt in https://github.com/dotnet/runtime/pull/71783#discussion_r919126830_

- [ ] It would be nice to throw or at least log. I know this is what we we in SslStream for historical reasons but the failures when we silently ignore given certificate are annoying IMHO. 
(this could be separate work)

_Originally posted by @wfurt in https://github.com/dotnet/runtime/pull/71783#discussion_r919132734_

**Comment by ManickaP** [comment]
> It would be nice to have some assert about it.

@wfurt how would we assert that the layout is the same? We have an assert about size, but I'm not sure what else we could do, any ideas?

**Comment by wfurt** [comment]
perhaps separate test for the helper? Serialize given buffer as SocketAddress and compare equality? 
AFAIK the only one special case was macOS were the layout was different. Conceptually, test would probably fail on platforms where we do it wrong. Perhaps just remove the comment with the doubts....?
