### ISSUE TITLE
Hitting LibraryImport asserts in VS

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#72036]
I cleaned and sync'd to latest this morning:

![image](https://user-images.githubusercontent.com/2642209/178553745-4d37b62a-5a53-48cc-a92a-a58338de2920.png)

**Comment by elinor-fung** [comment]
I think this from trying to look for v1 shapes on string marshallers - some bad effect of moving to v2 for string marshallers while we still have v1 support?

I expect https://github.com/dotnet/runtime/pull/71989 would fix this, since it removes the v1 path and its asserts.

**Comment by elinor-fung** [comment]
Should be fixed by #71989.
