### ISSUE TITLE
`UpgradeToRegexGeneratorCodeFixer` crashes with `InvalidCastException`

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/runtime#72047]
### Description

Test:

```csharp
        [Fact]
        public async Task TestAsArgument()
        {
            string test = @"using System.Text.RegularExpressions;
public class C
{
    void M1(Regex r) => _ = r;
    void M2() => M1([|new Regex("""")|]);
}
";

            string fixedCode = @"using System.Text.RegularExpressions;
public partial class C
{
    void M1(Regex r) => _ = r;
    void M2() => M1(MyRegex());
    [RegexGenerator("""")]
    private static partial Regex MyRegex();
}
";

            await VerifyCS.VerifyCodeFixAsync(test, fixedCode);
        }
```

### Expected behavior

No crash. The test should pass

### Actual behavior

Test fails

### Other information

The fix here is pass `true` for `getInnermostNodeForTie`. The fix was included in https://github.com/dotnet/runtime/pull/71264, but we're breaking down the PR now.

**Comment by Youssef1313** [comment]
@joperezr I'll take care of this once https://github.com/dotnet/runtime/pull/72046 is merged. You can assign me :)

**Comment by joperezr** [comment]
Good catch, thanks for logging. I've assinged you since you already have the fix ready.
