### ISSUE TITLE
System.Threading.RateLimiting.Tests.PartitionedRateLimiterTests.AllIdleLimitersCleanedUp_DisposeThrows failed in rolling build on net7.0-windows-Release-x86-CoreCLR_checked-Windows.10.Amd64.Open

### ISSUE THREAD

**Issue by jtschuster** [dotnet/runtime#72060]
[Build](https://runfo.azurewebsites.net/view/build/?number=1873896), [Log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-5928ea518b814997b5/System.Threading.RateLimiting.Tests/1/console.d9650dfa.log?%3Fhelixlogtype%3Dresult)

```
Starting:    System.Threading.RateLimiting.Tests (parallel test collections = on, max threads = 4)
    System.Threading.RateLimiting.Tests.PartitionedRateLimiterTests.AllIdleLimitersCleanedUp_DisposeThrows [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.AggregateException)
      Actual:   (No exception was thrown)
      Stack Trace:
        /_/src/libraries/System.Threading.RateLimiting/tests/PartitionedRateLimiterTests.cs(541,0): at System.Threading.RateLimiting.Tests.PartitionedRateLimiterTests.AllIdleLimitersCleanedUp_DisposeThrows()
        --- End of stack trace from previous location ---
```

First instance of the test failing

**Comment by stephentoub** [comment]
@BrennanConroy

**Comment by BrennanConroy** [comment]
Race in test code between the internal timer stopping (and running the heartbeat loop continuation) and the test code running the timer after doing its actions to make the limiters idle. If the initial heartbeat continuation is still running while the test code does its setup then it's possible for that continuation to observe the exception we are expecting in the test code and when the test code runs the heartbeat manually to observe the exception the state has already been cleaned up.

Working on a fix.
