### ISSUE TITLE
HttpStress is not running on Windows in CI

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#72096]
```
##[error]Failed to request agent. Exception Image Build.Windows.Amd64.VS2022.Pre doesn't exist in pool NetCore1ESPool-Public
```

https://dev.azure.com/dnceng/public/_build/results?buildId=1877931&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3

@dotnet/dnceng any idea what happenned to this image and how to address this problem?

**Comment by riarenas** [comment]
@antonfirsov the pipeline looks to be misconfigured. The image should be Build.Windows.Amd64.Pre**.Open.** The non-open versions are exclusively for use by the internal project and cannot be used in pipelines in the public project. 

You can find the valid images for the public project here: https://helix.dot.net/#1ESHostedPoolImagesWestUS-rg-Public

**Comment by MattGal** [comment]
> @riarenas thanks for the info! Looks like #67771 broke this.

I'm interested in how you made this conclusion given that the build image in question is not part of that PR?

**Comment by antonfirsov** [comment]
It changed `http.yml` and `ssl.yml` to use `Build.Windows.Amd64.VS2022.Pre`, at least this is what I found from history.
https://github.com/dotnet/runtime/pull/67771/files#diff-b129ff040baeefd1f9c0455447879e0bfa41edeed681cae64da75fdb6e0d52aa

Is there some piece of information I'm missing?

**Comment by MattGal** [comment]
Oh I see, you're totally right, I missed that because that was outside the scope of an Arcade update (it's not in the eng/common folder).  Should probably fix that.. those were commits from @agocke / @hoyosjs  not the arcade update from the Blame.

**Comment by agocke** [comment]
That was a complicated change -- not surprised there was a typo. Thanks for catching it.

**Comment by riarenas** [comment]
I see that https://helix.dot.net/#1ESHostedPoolImagesWestUS-rg-Public-Windows shows how the old pool has the docker artifact installed, but this one doesn't. 

Two options:

* Open an issue in https://github.com/dotnet/arcade for us to install all the requirements for this pipeline in the new pool (it might be missing more than docker for your scenario)
* Move to using the 1es-windows-2022 image that is the equivalent of the hosted windows-2022 image if that fits your needs: https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md

**Comment by MattGal** [comment]
Worth a shot, it at least has docker & VS 2022 on it.
