### ISSUE TITLE
Incorrect TypeLoadException message for byref field in non-byref-like type

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#72090]
### Description

Due to https://github.com/dotnet/roslyn/issues/62596, I could build a non-byref-like type with a byref field. Trying to load it, I got a `TypeLoadException`, as expected, but the error message seems to be incorrect, or at the very least not phrased great:

<img width="640" alt="image" src="https://user-images.githubusercontent.com/10199417/178726337-7ed74f55-0d8c-42e8-a7d2-6e23fe7d9b1c.png">

> "A ByRef-like type cannot be used as the type for an instance field in a non-ByRef-like type."

Here the field type is not a byref-like type, it's a byref field (of a non-byref-like type). It would be nice if the message was adjusted to reflect this properly, as it would be easier to understand. In fact, I got pinged by a fellow dev that had also stumbled upon this and was left confused by the error message because of this.

### Reproduction Steps

Try to load a type like this:

```csharp
struct Foo
{
    public ref int Bar;
}
```

### Expected behavior

You should get a `TypeLoadException`, but the message should mention the fact there's a byref field specifically.

### Actual behavior

The message is the same as if the field had been of an actual byref-like type, which is not the case.

### Regression?

No.

### Configuration

VS 17.3.0 Preview 3.0, .NET 7.0.100-preview.6.22352.1

**Comment by stephentoub** [comment]
The message looks correct to me. There's an instance field in a non-byref type (Foo), and that field's type is a byref type (ref int)...?

**Comment by Sergio0694** [comment]
> "and that field's type is a byref type (ref int)"

Yes, but the issue is that the message says it's of a byref-_like_ type, which is not true. You can also see that:

```csharp
typeof(int).MakeByRefType().IsByRefLike
```

Prints `false`. What I'm saying is that the message should distinguish fields of a byref type from those of a byref-like type, just like the reflection type does as well (see above). This message is just confusing for users because it's not correct: it's telling them that the field is of a byref-like type, when in fact the field is of a byref type, with the underlying type not being byref-like. Imho the message should reflect the difference and clarify that the field is an actual byref. Otherwise we'd get the same exact message (I mean, we currently do) for both a field of, say `Span<int>`, and one of type `ref int`, but those are not the same.

Does that make sense?

**Comment by Sergio0694** [comment]
Yes, my concern was that right now the message is the same for both byref-like types, and actual ref types (ie. ref fields), and just says "byref-like" in both cases. I got pinged by a dev that stumbled upon this and couldn't understand the message, and I'm thinking a clearer error message might've helped (especially given here it's not just unclear, it's just incorrect) 🙂
