### ISSUE TITLE
The framework 'Microsoft.NETCore.App', version '3.1.1-servicing.19572.8' was not found.

### ISSUE THREAD

**Issue by Varorbc** [dotnet/runtime#721]
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.1-servicing.19572.8' was not found.
  - The following frameworks were found:
      2.2.4 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.0.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.1.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.1-servicing.19572.8&arch=x64&rid=win10-x64

**Comment by vitek-karas** [comment]
@Varorbc can you please describe what you're trying to do and when it fails like that?

**Comment by Varorbc** [comment]
@vitek-karas 

    PS C:\Test> dotnet --info
    .NET Core SDK（反映任何 global.json）:
     Version:   3.1.100
     Commit:    cd82f021f4
    
    运行时环境:
     OS Name:     Windows
     OS Version:  10.0.18363
     OS Platform: Windows
     RID:         win10-x64
     Base Path:   C:\Program Files\dotnet\sdk\3.1.100\
    
    Host (useful for support):
      Version: 3.1.0
      Commit:  65f04fb6db
    
    .NET Core SDKs installed:
      2.2.203 [C:\Program Files\dotnet\sdk]
      3.0.100 [C:\Program Files\dotnet\sdk]
      3.1.100 [C:\Program Files\dotnet\sdk]
    
    .NET Core runtimes installed:
      Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
      Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    
    To install additional .NET Core runtimes or SDKs:
      https://aka.ms/dotnet-download

### Steps to reproduce

1.dotnet new webapi(strangely, the new project is not a target framework of 3.1, but 3.0)

2.modify the target framework in Test.csproj to 3.1

3.dotnet run test.csproj

**Comment by vitek-karas** [comment]
Interesting - thanks.
Can you please try this:
* set `COREHOST_TRACE=1` and `COREHOST_TRACEFILE=t.txt`
* run the project `dotnet run test.csproj`

Look through the t.txt or if you're comfortable with it share it here (note that the file will contain local paths and potentially environment variables - so make sure you're not sharing something you don't want to).

**Comment by Varorbc** [comment]
@vitek-karas how to set it?

**Comment by vitek-karas** [comment]
Sorry - these are environment variables

**Comment by Varorbc** [comment]
Which directory is the file in?

**Comment by vitek-karas** [comment]
You can either specify a full path in the environment variable. Or if you don't it should be in the current directory.

**Comment by Varorbc** [comment]
Doesn't seem to work

**Comment by vitek-karas** [comment]
Can you try this:
```
set COREHOST_TRACE=1
dotnet --info
```

You should see a LOT of output on the command line.
Now in the same window:
```
set COREHOST_TRACEFILE=t.txt
dotnet --info
```

After this you should find t.txt in the current directory.
Delete it and run the project with the problem from the window - it should produce t.txt again.

**Comment by Varorbc** [comment]
![image](https://user-images.githubusercontent.com/5714438/70716098-a1e00f80-1d26-11ea-83bb-edc3c7ae6544.png)
Are you sure this is the setting?

**Comment by Varorbc** [comment]
@vitek-karas I have emailed the file to you

**Comment by vitek-karas** [comment]
This is weird - for some reason `Microsoft.AspNetCore.App 3.1.0` has a framework reference to `Microsoft.NETCore.App 3.1.1-servicing.19572.8`.
When I look at my install of 3.1.0, I see a normal reference to 3.1.0.

@JunTaoLuo - any idea what's going on?

**Comment by Varorbc** [comment]
@vitek-karas Is there any progress? How can I solve this problem?

**Comment by vitek-karas** [comment]
@anurse - can somebody from the ASP.NET side take a look? This feels like some pre-release bits, but they show up as release 3.1.0 on the machine.

@Varorbc just to be 100% sure, can you please look at `C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.0\Microsoft.AspNetCore.App.runtimeconfig.json` - and copy the content here?

**Comment by Varorbc** [comment]
@vitek-karas https://github.com/aspnet/AspNetCore/issues/17727

Microsoft.AspNetCore.App.runtimeconfig.json

    {
      "runtimeOptions": {
        "tfm": "netcoreapp3.1",
        "framework": {
          "name": "Microsoft.NETCore.App",
          "version": "3.1.1-servicing.19572.8"
        },
        "rollForward": "LatestPatch"
      }
    }

**Comment by vitek-karas** [comment]
Thanks @Varorbc .

This feels wrong:
* `3.1.1-servicing.19572.8` is a pre-release version (per SemVer rules).
* Release version `3.1.0` of ASP.NET should not be referencing a pre-release version of NETCore.App.
* I would expect patch version to match across frameworks - as we sim-ship frameworks. So in this case I would expect `3.1.1` NETCoreApp to only by referenced from `3.1.1` ASP.NET framework.
* How come that my local install of `3.1.0` ASP.NET references `3.1.0` NETCoreApp and @Varorbc 's install references a different version?

**Comment by JunTaoLuo** [comment]
I have responded to the AspNetCore issue. It looks like an unreleased servicing build of ASP.NET Core is being installed on the machine but I'm unsure how that happened. This is likely not a dotnet/runtime issue so I think we can close this issue.

**Comment by Varorbc** [comment]
track https://github.com/aspnet/AspNetCore/issues/17727

**Comment by Sm1le291** [comment]
Hi! I have similar problem with Microsoft.NETCore.App 3.1.1 on openSuse Linux
I am trying to execute dotnet solution and it told me that it has found only SDK version 3.1.0

**Comment by ramsresearch** [comment]
I had the same problem. Installing .NET Core 3.1.1 runtime solved the problem. [ link](https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-3.1.1-windows-x64-installer) to install Windows 64 bit version of .NET Core 3.1.1 runtime

**Comment by Sm1le291** [comment]
> I had the same problem. Installing .NET Core 3.1.1 runtime solved the problem. [ link](https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-3.1.1-windows-x64-installer) to install Windows 64 bit version of .NET Core 3.1.1 runtime

I just have fixed it by installing Ubuntu)

**Comment by BhaveshNarain** [comment]
> I had the same problem. Installing .NET Core 3.1.1 runtime solved the problem. [ link](https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-3.1.1-windows-x64-installer) to install Windows 64 bit version of .NET Core 3.1.1 runtime

Thanks. Installing Runtime (v3.1.2) - Windows x64 worked for me.

**Comment by xiongdashan** [comment]
So bad！！！
I had same problem, When i updated dotnet-ef version to  3.1.2

**Comment by danmosemsft** [comment]
@xiongdasha please open a new issue if necessary
