### ISSUE TITLE
[API Proposal] Expose missing BinaryPrimitives APIs

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#72107]
`System.Buffers.Binary.BinaryPrimitives` exposes many APIs but there are few notable ones missing for core number types. We should extend the type to ensure that it supports the basic operations for all basic number types.

```csharp
namespace System.Buffers.Binary;

public static partial class BinaryPrimitives
{
    // Read*BigEndian and Read*LittleEndian

    public static nint ReadIntPtrBigEndian(ReadOnlySpan<byte> source);
    public static nint ReadIntPtrLittleEndian(ReadOnlySpan<byte> source);

    public static Int128 ReadInt128BigEndian(ReadOnlySpan<byte> source);
    public static Int128 ReadInt128LittleEndian(ReadOnlySpan<byte> source);

    public static nuint ReadUIntPtrBigEndian(ReadOnlySpan<byte> source);
    public static nuint ReadUIntPtrLittleEndian(ReadOnlySpan<byte> source);

    public static UInt128 ReadUInt128BigEndian(ReadOnlySpan<byte> source);
    public static UInt128 ReadUInt128LittleEndian(ReadOnlySpan<byte> source);

    // ReverseEndianness

    public static nint ReverseEndianness(nint value);
    public static Int128 ReverseEndianness(Int128 value);
    public static nuint ReverseEndianness(nuint value);
    public static UInt128 ReverseEndianness(UInt128 value);

    // TryRead*BigEndian and TryRead*LittleEndian

    public static bool TryReadIntPtrBigEndian(ReadOnlySpan<byte> source, out nint value);
    public static bool TryReadIntPtrLittleEndian(ReadOnlySpan<byte> source, out nint value);

    public static bool TryReadInt128BigEndian(ReadOnlySpan<byte> source, out Int128 value);
    public static bool TryReadInt128LittleEndian(ReadOnlySpan<byte> source, out Int128 value);

    public static bool TryReadUIntPtrBigEndian(ReadOnlySpan<byte> source, out nuint value);
    public static bool TryReadUIntPtrLittleEndian(ReadOnlySpan<byte> source, out nuint value);

    public static bool TryReadUInt128BigEndian(ReadOnlySpan<byte> source, out UInt128 value);
    public static bool TryReadUInt128LittleEndian(ReadOnlySpan<byte> source, out UInt128 value);

    // TryWrite*BigEndian and TryWrite*LittleEndian

    public static bool TryWriteIntPtrBigEndian(ReadOnlySpan<byte> destination, nint value);
    public static bool TryWriteIntPtrLittleEndian(ReadOnlySpan<byte> destination, nint value);

    public static bool TryWriteInt128BigEndian(ReadOnlySpan<byte> destination, Int128 value);
    public static bool TryWriteInt128LittleEndian(ReadOnlySpan<byte> destination, Int128 value);

    public static bool TryWriteUIntPtrBigEndian(ReadOnlySpan<byte> destination, nuint value);
    public static bool TryWriteUIntPtrLittleEndian(ReadOnlySpan<byte> destination, nuint value);

    public static bool TryWriteUInt128BigEndian(ReadOnlySpan<byte> destination, UInt128 value);
    public static bool TryWriteUInt128LittleEndian(ReadOnlySpan<byte> destination, UInt128 value);

    // Write*BigEndian and Write*LittleEndian

    public static void WriteIntPtrBigEndian(ReadOnlySpan<byte> destination, nint value);
    public static void WriteIntPtrLittleEndian(ReadOnlySpan<byte> destination, nint value);

    public static void WriteInt128BigEndian(ReadOnlySpan<byte> destination, Int128 value);
    public static void WriteInt128LittleEndian(ReadOnlySpan<byte> destination, Int128 value);

    public static void WriteUIntPtrBigEndian(ReadOnlySpan<byte> destination, nuint value);
    public static void WriteUIntPtrLittleEndian(ReadOnlySpan<byte> destination, nuint value);

    public static void WriteUInt128BigEndian(ReadOnlySpan<byte> destination, UInt128 value);
    public static void WriteUInt128LittleEndian(ReadOnlySpan<byte> destination, UInt128 value);
}
```

### Additional Notes

Also missing are some APIs around `char`, `Half`, `float`, and `double`. However, there are concerns around `char` not being a "core" numeric type and around possible normalization issues for the various floating-point types, so they aren't included.

**Comment by tannergooding** [comment]
CC. @dakersnar, @GrabYourPitchforks 

Any concerns here or do you think this is fine to mark `api-ready-for-review`?

**Comment by tannergooding** [comment]
-- Noting that there is still the "downside" that `BinaryPrimitives` isn't very discoverable and its where most of the `Endianness` APIs are, except for `IsLittleEndian` which is on `System.BitConverter`.

These are "split" due to an old layering scenario around .NET Standard and ensuring the APIs were available "downlevel". It might be worth exposing an `static bool IsLittleEndian { get; }` (and `static bool IsBigEndian { get; }`) API on `BinaryPrimitives` for discoverability.

**Comment by dakersnar** [comment]
What does `IsLittleEndian` get called on? The type, the `source` data, or the machine's architecture?

**Comment by tannergooding** [comment]
> char isn't really a core numeric type, so it's weird to me to put endianness-related APIs over it

It's a case that does have endianness considerations in that there is explicitly both `UTF-16 LE` and `UTF-16 BE` so this will be "useful" for manual lexing/parsing scenarios. Also notably, `char->ushort` is an implicit conversion but `ushort->char` is not, so `ushort bits = BinaryPrimitives.ReverseEndianness('c');` works, but not `char bits = BinaryPrimitives.ReverseEndianness('c');`, exposing the API would "fix" that.

> What does IsLittleEndian get called on? The type, the source data, or the machine's architecture?

It refers to the endianness of the host architecture. You use `ReadInt32LittleEndian` when you know the data is in little-endian format, the API will read an `int32` and on big endian platforms will then `ReverseEndianness` before returning the result. If you are doing your own endianness fixups or handling, you would query `IsLittleEndian` directly. `IsBigEndian` is then a "readability" API since it is much clearer then `!IsLittleEndian`.

**Comment by Clockwork-Muse** [comment]
.... a reverse-endianed float/double isn't (likely) to be a valid value, so whether the output gets coerced to something or not is a bit of a mystery.
I could have sworn we just had an issue about it around here...?

**Comment by alexrp** [comment]
> I could have sworn we just had an issue about it around here...?

I don't know about "just", but there was some discussions on the subject in this issue: https://github.com/dotnet/runtime/issues/2365#issuecomment-564274467

**Comment by Clockwork-Muse** [comment]
Sure, but what I was getting at is the possibility the runtime or even the hardware might end up coercing them to a valid `NaN` value, which means you couldn't roundtrip with it, and if you'd been given the "wrong" one to begin with it likely wouldn't be a valid value you could reverse either, in such a scenario.

**Comment by jkotas** [comment]
Reverse-endianes on float/double was discussed in the original set and explicitly rejected for these reasons.

**Comment by tannergooding** [comment]
> Reverse-endianes on float/double was discussed in the original set and explicitly rejected for these reasons.

The same issue exist with `ReadSingleLittleEndian` and other APIs that were approved. While a runtime is free (under the IEEE 754 spec) to normalize NaNs to a single representation, that will in practice break a lot of code. Things like `SIMD` rely on being able to get and produce `AllBitsSet` as do various other APIs throughout the JIT. Various bit manipulation tricks involve using "alternative" NaN representations, etc.

I understand that some runtime "could", but a given runtime shouldn't because it will break existing code and expectations.

**Comment by jkotas** [comment]
> The same issue exist with ReadSingleLittleEndian and other APIs that were already approved and implemented

That's not correct, as long as the number you are reading is well formed. Also notice that ReadSingleLittleEndian are intentionally implemented to read the value as integer, swap endianness on the integer, and finally convert the value with the correct endianness to float.

**Comment by GrabYourPitchforks** [comment]
> It's a case that does have endianness considerations in that there is explicitly both UTF-16 LE and UTF-16 BE so this will be "useful" for manual lexing/parsing scenarios.

Copying chars to/from byte streams is not the correct way to perform UTF-16 conversion. We have existing APIs in the framework that do this the correct way. I really don't want people to think the APIs being proposed here are a blessed (or "fast") way to do this.

**Comment by tannergooding** [comment]
> That's not correct, as long as the number you are reading is well formed. Also notice that APIs like ReadSingleLittleEndian are intentionally implemented to read the value as integer, swap endianness on the integer, and finally convert the value with the correct endianness to float.

Which can still be constant folded and optimized to normalize a value that ends up as a NaN, even temporarily. All these operations are non side-effecting "constant" operations.

**Comment by tannergooding** [comment]
> Copying chars to/from byte streams is not the correct way to perform UTF-16 conversion. We have existing APIs in the framework that do this the correct way. I really don't want people to think the APIs being proposed here are a blessed (or "fast") way to do this.

This entirely depends and there are always two considerations at play. One is having the low level building blocks for our primitive types and the other is providing built in functionality that most users should be pushed towards.

Most users should use the encoding types, but that doesn't also mean that there aren't users and scenarios where you will be doing these operations yourself and where having the relevant helper, especially where the current APIs mostly work but with pain points.

**Comment by jkotas** [comment]
The pain point is very minor. If you know what you are doing, the workaround is trivial, like add a cast or call an extra method. It is the usual question on whether the APIs have enough value given the sharp edges.

**Comment by DaZombieKiller** [comment]
A use case I typically have for a `float`/`double` `ReverseEndianness` is when I'm reading in a bunch of structured data at once, and then want to correct it later if I'm running on a big endian system:
```cs
struct DataBlock
{
    public int Field1;
    public float Field2;
    public float Field3;
}

// ...
var blocks = new DataBlock[count];
stream.ReadExactly(MemoryMarshal.AsBytes(blocks.AsSpan()));

if (!BitConverter.IsLittleEndian)
{
    for (int i = 0; i < blocks.Length; i++)
    {
        blocks[i].Field1 = BinaryPrimitives.ReverseEndianness(blocks[i].Field1);
        blocks[i].Field2 = BinaryPrimitives.ReverseEndianness(blocks[i].Field2);
        blocks[i].Field3 = BinaryPrimitives.ReverseEndianness(blocks[i].Field3);
    }
}
```
What would be the optimal alternative here? Changing the structure to use `int`/`uint` and exposing properties that use `Int32BitsToSingle`/`SingleToInt32Bits`?

**Comment by Clockwork-Muse** [comment]
> What would be the optimal alternative here?

Not sure _how_ optimal, but... write a source generator that writes a method that either just calls `MemoryMarshal.AsBytes(...)` when little endian, or calls separate generated `ReadX` methods when big endian.  Obviously you can't dodge the cost of reversing the endianness, the question would be how much a difference the block blit would save you over separate reads (or other pipeline considerations).

**Comment by jkotas** [comment]
> the possibility the runtime or even the hardware might end up coercing them to a valid NaN value

https://github.com/dotnet/runtime/issues/75221#issuecomment-1240759974 has an example of what can happen with NaNs on x86 today.

**Comment by tannergooding** [comment]
Its worth noting the same "general" issue would be present for doing it manually with `BitConverter.Int32BitsToSingle` and `BitConverter.SingleToInt32Bits`.

If the represented value was at any point a `sNaN`, then it might get normalized and not write/reverse the exact bit value originally represented.

**Comment by tannergooding** [comment]
The general point is that a dedicated API that takes `float` is one we can ensure does the right thing, even if that involves specialization in the JIT to help assert other optimizations don't happen.

The risk of NaN normalization exists regardless, and is likely a bigger "hole" if the user has to consider those edge cases themselves than if we considered it for them.

Because the user has no control over whether the JIT emits an `FLD` or not and therefore no control over whether a normalization could happen at any point. It likewise has no control over whether the JIT decides to optimize certain bitcasts/unions (and we do some of these already minimally today).

**Comment by jkotas** [comment]
Right, depending on bit-to-bit identical roundtripping of floats is a slippery slope. 

It is safe to depend on value roundtripping (e.g. 1.23456 won't turn into NaN silently).

The specific problem with `BinaryPrimitives.ReverseEndianness(float)` API is that you can have a value that happens to be NaN when the bytes are reversed, and that will break even the value roundtripping.

**Comment by tannergooding** [comment]
Right, and the same general issue exists for the `BitConverter` approach on 32-bit.

At a minimum we should likely document this scenario under the `BitConverter` `#remarks` section. But, I think have a `ReverseEndianessUnsafe` API that takes `float`/`double` and helps call out the scenario will make it more visible to users trying to handle this scenario on the potential pitfalls

This isn't a hard stance, and I'd rather pull it from this list to move the API proposal forward. However, I do think its an important discussion point for API review and something we should consider.

**Comment by jkotas** [comment]
> Right, and the same general issue exists for the BitConverter approach (at least on 32-bit x86).

Are you saying that BitConverter breaks value roundtripping? I do not think that it is the case for any of the existing BitConverter APIs. BitConverter may not return the exact bits as what they were in memory, but it will be still the same value.

**Comment by tannergooding** [comment]
Right, I'm saying that `BitConverter` may not preserve the bitwise value and may for example normalize some `NaN` to a different NaN` representation (such as `sNaN` to `qNaN`).

**Comment by DaZombieKiller** [comment]
Am I correct in thinking that the following would not suffer from normalization issues?
```cs
struct S
{
    public int A;
    public float B;
    public float C;
}

S example;
stream.ReadExactly(new(&example, sizeof(S)));
ReverseEndianness32Bits(new Span<S>(&example, 1));

void ReverseEndianness32Bits<T>(Span<T> span)
    where T : unmanaged
{
    foreach (ref uint value in MemoryMarshal.Cast<T, uint>(span))
    {
        value = BinaryPrimitives.ReverseEndianness(value);
    }
}
```
Since the address of `example` is taken, that should prevent it from being enregistered and thus the values being operated on will never be in floating-point registers, right?

**Comment by jkotas** [comment]
>  thinking that the following would not suffer from normalization issues?

Yes, however I do not think you would want to write this code this way, for the structure in your example at least.

> would that mean void ReverseEndianness(ref readonly float value, out float result) would be a "safer" signature at all?

The signature of an API optimized for in-place swapping that you are trying to do here would be `void ReverseEndianness(ref float value) => Unsafe.As<float,uint>(ref float) => ReverseEndianess(Unsafe.As<float,uint>(ref float))`. You can implement this as a one-liner helper yourself if you have a system designed around in-place swapping.

**Comment by tannergooding** [comment]
Updated to exclude `char`, `double`, `Half`, and `float` for the time being.

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System.Buffers.Binary;

public static partial class BinaryPrimitives
{
    // Read*BigEndian and Read*LittleEndian

    public static nint ReadIntPtrBigEndian(ReadOnlySpan<byte> source);
    public static nint ReadIntPtrLittleEndian(ReadOnlySpan<byte> source);

    public static Int128 ReadInt128BigEndian(ReadOnlySpan<byte> source);
    public static Int128 ReadInt128LittleEndian(ReadOnlySpan<byte> source);

    public static nuint ReadUIntPtrBigEndian(ReadOnlySpan<byte> source);
    public static nuint ReadUIntPtrLittleEndian(ReadOnlySpan<byte> source);

    public static UInt128 ReadUInt128BigEndian(ReadOnlySpan<byte> source);
    public static UInt128 ReadUInt128LittleEndian(ReadOnlySpan<byte> source);

    // ReverseEndianness

    public static nint ReverseEndianness(nint value);
    public static Int128 ReverseEndianness(Int128 value);
    public static nuint ReverseEndianness(nuint value);
    public static UInt128 ReverseEndianness(UInt128 value);

    // TryRead*BigEndian and TryRead*LittleEndian

    public static bool TryReadIntPtrBigEndian(ReadOnlySpan<byte> source, out nint value);
    public static bool TryReadIntPtrLittleEndian(ReadOnlySpan<byte> source, out nint value);

    public static bool TryReadInt128BigEndian(ReadOnlySpan<byte> source, out Int128 value);
    public static bool TryReadInt128LittleEndian(ReadOnlySpan<byte> source, out Int128 value);

    public static bool TryReadUIntPtrBigEndian(ReadOnlySpan<byte> source, out nuint value);
    public static bool TryReadUIntPtrLittleEndian(ReadOnlySpan<byte> source, out nuint value);

    public static bool TryReadUInt128BigEndian(ReadOnlySpan<byte> source, out UInt128 value);
    public static bool TryReadUInt128LittleEndian(ReadOnlySpan<byte> source, out UInt128 value);

    // TryWrite*BigEndian and TryWrite*LittleEndian

    public static bool TryWriteIntPtrBigEndian(ReadOnlySpan<byte> destination, nint value);
    public static bool TryWriteIntPtrLittleEndian(ReadOnlySpan<byte> destination, nint value);

    public static bool TryWriteInt128BigEndian(ReadOnlySpan<byte> destination, Int128 value);
    public static bool TryWriteInt128LittleEndian(ReadOnlySpan<byte> destination, Int128 value);

    public static bool TryWriteUIntPtrBigEndian(ReadOnlySpan<byte> destination, nuint value);
    public static bool TryWriteUIntPtrLittleEndian(ReadOnlySpan<byte> destination, nuint value);

    public static bool TryWriteUInt128BigEndian(ReadOnlySpan<byte> destination, UInt128 value);
    public static bool TryWriteUInt128LittleEndian(ReadOnlySpan<byte> destination, UInt128 value);

    // Write*BigEndian and Write*LittleEndian

    public static void WriteIntPtrBigEndian(ReadOnlySpan<byte> destination, nint value);
    public static void WriteIntPtrLittleEndian(ReadOnlySpan<byte> destination, nint value);

    public static void WriteInt128BigEndian(ReadOnlySpan<byte> destination, Int128 value);
    public static void WriteInt128LittleEndian(ReadOnlySpan<byte> destination, Int128 value);

    public static void WriteUIntPtrBigEndian(ReadOnlySpan<byte> destination, nuint value);
    public static void WriteUIntPtrLittleEndian(ReadOnlySpan<byte> destination, nuint value);

    public static void WriteUInt128BigEndian(ReadOnlySpan<byte> destination, UInt128 value);
    public static void WriteUInt128LittleEndian(ReadOnlySpan<byte> destination, UInt128 value);
}
```

**Comment by stephentoub** [comment]
I'm handling:
```C#
    public static nint ReverseEndianness(nint value);
    public static Int128 ReverseEndianness(Int128 value);
    public static nuint ReverseEndianness(nuint value);
    public static UInt128 ReverseEndianness(UInt128 value);
```
as part of #75901.
