### ISSUE TITLE
Packages need to stabilize for shipping .NET 7

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#72111]
1. Product dependencies in the Versions.props files must not be prerelease. Fixed with https://github.com/dotnet/runtime/pull/72068 and https://github.com/dotnet/runtime/pull/72110
2. Product dependencies in the Versions.props files must be on the latest patch version for libraries dependencies. https://github.com/dotnet/runtime/pull/73871
3. We must be using the compiler from the SDK and unpin the compiler if it's pinned. https://github.com/dotnet/runtime/issues/65317
4. The Intellisense package must be up-to-date before we release. @carlossanlop will take care of this gradually until the RC2 snap.

cc @dotnet/runtime-infrastructure

**Comment by jeffschwMSFT** [comment]
@carlossanlop can you take a look at this issue?

**Comment by carlossanlop** [comment]
I'll sync with @ViktorHofer tomorrow on this.

**Comment by carlossanlop** [comment]
I already took care of item no. 1: https://github.com/dotnet/runtime/pull/72068 and https://github.com/dotnet/runtime/pull/72110/

I will take care of item no. 4 gradually until we snap RC2.

Pending clarifying 2 and 3.

**Comment by carlossanlop** [comment]
Item no. 2 has been merged to main. Here is the backport to release/7.0-rc1: https://github.com/dotnet/runtime/pull/74024

**Comment by carlossanlop** [comment]
For item no. 3, @jkoritzinsky wrote in https://github.com/dotnet/runtime/issues/65317#issuecomment-1215829944 👍🏼 
> This wasn't able to be fixed in https://github.com/dotnet/runtime/pull/72145 because of a regression in Roslyn. We'll fix this before we release (likely after RC1).

**Comment by ViktorHofer** [comment]
Closing as completed.
