### ISSUE TITLE
[Question] Type.GetTypeCode And Half Type 

### ISSUE THREAD

**Issue by LiorBanai** [dotnet/runtime#72123]
I was wondering why the call to ``` Type.GetTypeCode(typeof(Half))); ``` returns Object and not the IEEE 16-bit float.

shouldn't the Enum be updated to support it (and maybe also Int128/Uint128))

**Comment by MichalPetryka** [comment]
Technically speaking, updating the enum would be a breaking change. nint, nuint are missing from it too also. So are pointers.

**Comment by MichalPetryka** [comment]
I'd personally advise against using GetTypeCode outside of working with enums, it's just too restricted to represent things exactly. Type equality checks in current runtimes are fast too.

**Comment by huoyaoyuan** [comment]
Related: https://github.com/dotnet/runtime/issues/936#issuecomment-663728243
/cc @tannergooding

In my view, `TypeCode` is a highly legacy concept, together with `IConvertible`.

**Comment by LiorBanai** [comment]
@MichalPetryka  & @huoyaoyuan Thanks for the information. I guess I got my answer :)
