### ISSUE TITLE
[API Proposal]:  Expose  _dayNumber of DateOnly

### ISSUE THREAD

**Issue by LiorBanai** [dotnet/runtime#72138]
### Background and motivation

In my Library (https://github.com/LiorBanai/HDF5-CSharp) I need to write the Type to H5 file.
I can write standard primitives so If I can get the int _DayNumber I could just write it directly
Right now I convert it to DateTime and save the ticks.

### API Proposal

Just expose the 
```cs
 private readonly int _dayNumber;
```
from ```DateOnly```

### API Usage

```csharp
// Fancy the value
var c = new DateOnly();


// Getting the values out
Console.WriteLine(C.DayNumber);
```

**Comment by svick** [comment]
[`DateOnly.DayNumber` already exists.](https://docs.microsoft.com/en-us/dotnet/api/system.dateonly.daynumber)

**Comment by LiorBanai** [comment]
@svick  I'm not sure how I missed it.
Thanks :)

**Comment by tarekgh** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.dateonly.daynumber?view=net-6.0

**Comment by tarekgh** [comment]
@LiorBanai could you please share how you are going to use the `DayNumber`? I want to learn about your scenario.

**Comment by Clockwork-Muse** [comment]
@tarekgh - I would imagine it's being used for something like a calendar dimension in an analysis dataset, given the apparent use of the filetype - in these cases you don't necessarily have a column that's a `Date` type, but an integer epoch day, then a calendar file with the date in multiple formats and with multiple fields pulled out as columns.

The other primary use for an epoch date is for translating between calendar systems.

**Comment by LiorBanai** [comment]
@tarekgh, the H5 type system doesn't have direct .net representation for each type. This force me to use lower level primitive to store (and read back) the data.  So it make sense to use the underline type as the base for the mapping
