### ISSUE TITLE
CreateDump may use too much memory

### ISSUE THREAD

**Issue by leculver** [dotnet/runtime#72148]
Our partner team reports that on Linux, createdump can take up to 150mb of memory usage in a Linux container environment and may cause the container to OOM.  This is surprising because createdump _mostly_ works on small chunks of memory when reading from a process and writing to a dump.

I have not tried to reproduce this myself.  This work item is to investigate this issue and see if we can reproduce it, if not we should reach out to Remi for more details.

Note this is distinct from https://github.com/dotnet/runtime/issues/71472.  https://github.com/dotnet/runtime/issues/71472 asserts that the target process increases in size, whereas this issue is tracking whether createdump itself is using too much memory.

**Comment by mikem8361** [comment]
I've been investigating this and figured out why createdump's memory usage is increasing so much but I don't have any fix yet. I haven't come up with any work around other than creating "full" dumps or any fix especially one that will fit in our 7.0 schedule.

**Comment by mikem8361** [comment]
In 7.0 RC2, the COMPlus_EnableFastHeapDumps=1 environment variable can be used with createdump directly or with the other crash generation  env vars to enable low memory usage and faster generated heap dump.
