### ISSUE TITLE
Request with HttpVersion > 3 and RequestVersionOrHigher policy sent as H/3 request

### ISSUE THREAD

**Issue by greenEkatherine** [dotnet/runtime#72185]
### Description

Request message with HttpVersion higher than currently supported 3.0 is not checked on the HttpVersionPolicy. In case when it is set to RequestVersionOrHigher we get unexpected behavior -- request is treated as H/3 request.

### Reproduction Steps

```c#
var requestMessage = new HttpRequestMessage(HttpMethod.Get, uri)
{
    Version = new Version(4, 0),
    VersionPolicy = HttpVersionPolicy.RequestVersionOrHigher
};
```

### Expected behavior

Throw request version cannot establish

### Actual behavior

No exception from HttpConnection pool and sent via H/3 connection

**Comment by karelz** [comment]
Low priority, moving to 8.0 due to time restrictions.

**Comment by ManickaP** [comment]
Triage: we don't have any customer reports complaining about this, not critical for 8.0. We would take a community PR though.

**Comment by hez2010** [comment]
Nothing is disallowing setting an invalid version in HTTP message, you can even form a http message with invalid versions and send it with curl.  IMO how to handle the version is up to the HTTP handler implementation, it shouldn't be restricted on higher levels.
