### ISSUE TITLE
[Quic] System.Net.Quic.Tests.MsQuicTests.WriteTests timeout in rolling build

### ISSUE THREAD

**Issue by jtschuster** [dotnet/runtime#72196]
[Build](https://runfo.azurewebsites.net/view/build/?number=1880188), [Log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-86f871399ad4442b86/System.Net.Quic.Functional.Tests/2/console.ab8d2f0f.log?%3Fhelixlogtype%3Dresult)

```
 System.Net.Quic.Functional.Tests: [Long Running Test] 'System.Net.Quic.Tests.MsQuicTests.WriteTests', Elapsed: 00:02:11
    System.Net.Quic.Tests.MsQuicTests.WriteTests(writes: [[1000004, 502, 15003, 1, 502, ...], [15003, 1, 15003, 1, 1000004, ...], [1, 1, 1, 1, 502, ...], [1, 1000004, 1000004, 1, 1000004, ...], [1, 502, 15003, 1000004, 502, ...]]) [FAIL]
      System.TimeoutException : The operation has timed out.
      Stack Trace:
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(55,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(281,0): at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(281,0): at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(281,0): at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(281,0): at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs(593,0): at System.Net.Quic.Tests.MsQuicTests.WriteTests(Int32[][] writes)
        --- End of stack trace from previous location ---
```

Runfo Tracking Issue: [system.net.quic.tests.msquictests.writetests](https://runfo.azurewebsites.net/tracking/issue/361)
|Build|Definition|Kind|Run Name|Console|Core Dump|Test Results|Run Client|
|---|---|---|---|---|---|---|---|
|[1882195](https://dev.azure.com/dnceng/public/_build/results?buildId=1882195)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 72235](https://github.com/dotnet/runtime/pull/72235)|net7.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server2022.ES.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72235-merge-62029cf31de1407ba7/System.Net.Quic.Functional.Tests/2/console.7aa0a3a8.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72235-merge-62029cf31de1407ba7/System.Net.Quic.Functional.Tests/b27b087e-e429-45ed-935b-aff45697d059.log?%3F%253Fhelixlogtype%253Dresult)|
|[1882195](https://dev.azure.com/dnceng/public/_build/results?buildId=1882195)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 72235](https://github.com/dotnet/runtime/pull/72235)|net7.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server2022.ES.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72235-merge-62029cf31de1407ba7/System.Net.Quic.Functional.Tests/2/console.7aa0a3a8.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72235-merge-62029cf31de1407ba7/System.Net.Quic.Functional.Tests/b27b087e-e429-45ed-935b-aff45697d059.log?%3F%253Fhelixlogtype%253Dresult)|
|[1881865](https://dev.azure.com/dnceng/public/_build/results?buildId=1881865)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 72129](https://github.com/dotnet/runtime/pull/72129)|net7.0-windows-Debug-x64-CoreCLR_release-Windows.11.Amd64.Client.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72129-merge-3da47510349842ba85/System.Net.Quic.Functional.Tests/2/console.f9c115d5.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72129-merge-3da47510349842ba85/System.Net.Quic.Functional.Tests/758b98f5-15d1-431f-b024-89a139918f99.log?%3F%253Fhelixlogtype%253Dresult)|
|[1881865](https://dev.azure.com/dnceng/public/_build/results?buildId=1881865)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 72129](https://github.com/dotnet/runtime/pull/72129)|net7.0-windows-Debug-x64-CoreCLR_release-Windows.11.Amd64.Client.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72129-merge-3da47510349842ba85/System.Net.Quic.Functional.Tests/2/console.f9c115d5.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72129-merge-3da47510349842ba85/System.Net.Quic.Functional.Tests/758b98f5-15d1-431f-b024-89a139918f99.log?%3F%253Fhelixlogtype%253Dresult)|
|[1881761](https://dev.azure.com/dnceng/public/_build/results?buildId=1881761)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net7.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.Server2022.ES.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-70-preview71d9aab21c3324bcba8/System.Net.Quic.Functional.Tests/2/console.68b9c1ed.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-70-preview71d9aab21c3324bcba8/System.Net.Quic.Functional.Tests/889b132c-e011-465d-859e-6f0e7f676380.log?%3F%253Fhelixlogtype%253Dresult)|
|[1881761](https://dev.azure.com/dnceng/public/_build/results?buildId=1881761)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net7.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.Server2022.ES.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-70-preview71d9aab21c3324bcba8/System.Net.Quic.Functional.Tests/2/console.68b9c1ed.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-70-preview71d9aab21c3324bcba8/System.Net.Quic.Functional.Tests/889b132c-e011-465d-859e-6f0e7f676380.log?%3F%253Fhelixlogtype%253Dresult)|
|[1880188](https://dev.azure.com/dnceng/public/_build/results?buildId=1880188)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net7.0-windows-Release-x64-CoreCLR_release-Windows.11.Amd64.Client.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-86f871399ad4442b86/System.Net.Quic.Functional.Tests/2/console.ab8d2f0f.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-86f871399ad4442b86/System.Net.Quic.Functional.Tests/f647e099-a7d4-47dd-b85b-581ed81605d9.log?%3F%253Fhelixlogtype%253Dresult)|
|[1880188](https://dev.azure.com/dnceng/public/_build/results?buildId=1880188)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net7.0-windows-Release-x64-CoreCLR_release-Windows.11.Amd64.Client.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-86f871399ad4442b86/System.Net.Quic.Functional.Tests/2/console.ab8d2f0f.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-86f871399ad4442b86/System.Net.Quic.Functional.Tests/f647e099-a7d4-47dd-b85b-581ed81605d9.log?%3F%253Fhelixlogtype%253Dresult)|
|[1878908](https://dev.azure.com/dnceng/public/_build/results?buildId=1878908)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 72116](https://github.com/dotnet/runtime/pull/72116)|net7.0-windows-Debug-x64-CoreCLR_release-Windows.10.Amd64.Server2022.ES.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72116-merge-b49c9a7018834aff93/System.Net.Quic.Functional.Tests/2/console.04baf1c1.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72116-merge-b49c9a7018834aff93/System.Net.Quic.Functional.Tests/aea45343-8dac-4528-aeb8-9442c13fba26.log?%3F%253Fhelixlogtype%253Dresult)|
|[1878908](https://dev.azure.com/dnceng/public/_build/results?buildId=1878908)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 72116](https://github.com/dotnet/runtime/pull/72116)|net7.0-windows-Debug-x64-CoreCLR_release-Windows.10.Amd64.Server2022.ES.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72116-merge-b49c9a7018834aff93/System.Net.Quic.Functional.Tests/2/console.04baf1c1.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72116-merge-b49c9a7018834aff93/System.Net.Quic.Functional.Tests/aea45343-8dac-4528-aeb8-9442c13fba26.log?%3F%253Fhelixlogtype%253Dresult)|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|0|5|5|

**Comment by wfurt** [comment]
Do you know if this is windows-11 specific @jtschuster ?

**Comment by jtschuster** [comment]
It looks like it's happened on Windows 10 as well, but only on 2 builds so far.
https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime%20name%3A%22system.net.quic.tests.msquictests.writetests%22

**Comment by ManickaP** [comment]
The windows 10 are reporting success in the console log:
`System.Net.Quic.Functional.Tests  Total: 295, Errors: 0, Failed: 0, Skipped: 2, Time: 64,125s`

The windows 11 are failing and I'll investigate.

**Comment by wfurt** [comment]
`Windows.10.Amd64.Server2022` S2022 is mostly same stack as W11. But all the failures are Windows/schannel e.g. no Linux. But I agree with @ManickaP - the console.log shows pass so I'm not sure why they are even in the list @jtschuster
