### ISSUE TITLE
[Question] CoreCLR debug API usage, evaluation after `ICorDebugController::Stop`.

### ISSUE THREAD

**Issue by viewizard** [dotnet/runtime#72190]
Hello,

I am testing our debugger with simple application (console "hello world", managed only, 1 thread), 
```
        static void Main()
        {
            while (true)
            {
                Thread.Sleep(25000);
            }
        }
```
and found, that in case we stop debuggee process by breakpoint we receive `ICorDebugManagedCallback::Breakpoint` and could create in separate thread (we can't stay in ICorDebugManagedCallback and eval, since eval also use ICorDebugManagedCallback routine) `ICorDebugThread::CreateEval` and after that `ICorDebugEval::NewString`.

In the same time, if debuggee process was stopped by `ICorDebugController::Stop` at `Thread.Sleep(25000);` execution, we could create eval object by `ICorDebugThread::CreateEval` (at `ICorDebugManagedCallback::CreateThread` we store thread ID and get `ICorDebugThread` with `ICorDebugProcess::GetThread`), but in case we try `ICorDebugEval::NewString` we have `CORDBG_E_ILLEGAL_AT_GC_UNSAFE_POINT` return code.

Is there any way we could stop debuggee process with `ICorDebugController::Stop` (or other way) and have thread in consistant for evaluation state?

CC @alpencolt

**Comment by alpencolt** [comment]
cc @jkotas

**Comment by viewizard** [comment]
@jkotas thank you for explanation!
But, do we have any assure way for `ICorDebugEval` usage in this case, when debuggee application stopped by `ICorDebugController::Stop` call?

I am asking, because I see, that VScode C# debugger (vsdbg, developed by MS) can evaluate (call managed method and get result) in this case.
```
    class Program
    {
        static int test_func()
        {
            return 5;
        }

        static void Main()
        {
            while (true)
            {
                Thread.Sleep(25000);
            }
        }
    }
```
![1](https://user-images.githubusercontent.com/15098562/179262627-1911327a-5050-4f8b-ae60-09eae7ecc369.png)
I am just worry now, is vsdbg use `ICorDebugEval` at all... or it use not user debuggee process managed thread.

**Comment by jkotas** [comment]
Visual Studio debugger tries hard to evaluate expressions non-invasively, without running any code in the debuggee. It uses `ICorDebugEval` only as the last resort when non-invasive evaluation is not possible.

**Comment by viewizard** [comment]
@jkotas the point in code execution (function evaluation, that could be done only by code execution). In case of Visual Studio C# debugger we see "This expression causes side effects and will not be evaluated." in this case (in case code execution during pause at `Thread.Sleep(25000)` line), look like it try use `ICorDebugEval` and fail (same as we see in our debugger), but VSCode C# debugger in some way can execute code at this point (see picture I attached in my previous post). I thought this could be done by some CoreCLR debug API trick, but looks like this is VSCode C# magic.

**Comment by tommcdon** [comment]
@viewizard closing as it looks like the question in this issue has been answered.
