### ISSUE TITLE
Please revert PR #57561

### ISSUE THREAD

**Issue by masonwheeler** [dotnet/runtime#72220]
Brotli compression defines several compression levels, with each higher level providing a greater degree of compression at the cost of a larger amount of processing time.  The `CompressionLevel` enum is mapped onto it in [BrotliUtils.cs](https://github.com/dotnet/runtime/blob/main/src/libraries/System.IO.Compression.Brotli/src/System/IO/Compression/BrotliUtils.cs) in an extremely unforgiving manner: the only choices available are all quite bad.  Level 0 is no compression at all, level 1 has terrible characteristics when writing data to the stream in small quantities, -- often producing output that's larger than the input! -- and level 11 is *extremely* slow.

In .NET 6, it was possible to work around this problem by casting an arbitrary int to `CompressionLevel`, which would be cast back to an int in `BrotliUtils` if it didn't match a predefined `CompressionLevel` value.  [This PR](https://github.com/dotnet/runtime/pull/57561) stripped away this incredibly important piece of functionality, causing a major regression in .NET 7 that makes `BrotliStream` essentially worthless, subjecting API consumers to a no-win choice between negative compression rates or eating a two-order-of-magnitude(!) performance regression.

This PR appears to have been created with worthwhile goals in mind, but its actual effect is severely harmful.  Please revert it.

**Comment by stephentoub** [comment]
The intent of https://github.com/dotnet/runtime/issues/46595 was to both fix the silent passthrough (which makes the abstraction leaky and which leads to really weird behavior in that the value is treated very differently based on its value) _and_ to reset CompressionLevel.Optimal to map to Brotli's 6 rather than 11.  What is the value you wanted to use?

**Comment by masonwheeler** [comment]
I agree, there's some weirdness there.  In particular, under the existing scheme it's not possible to access levels 2 or 3.  This could likely be rectified by adding a new constructor that takes an int rather than a `CompressionLevel` and validates that it's within the accepted range.  (The `CompressionLevel` constructor could be easily rewritten to call this one with the mapped value.)

I have existing code that's using level 4.  I haven't tested its performance characteristics with 6 yet.  Looking at published benchmarks, it probably wouldn't be particularly bad, but being able to keep the fine-tunability would be greatly appreciated.

**Comment by stephentoub** [comment]
> but being able to keep the fine-tunability would be greatly appreciated

The intent is to expose such fine-grained configuration via APIs like https://github.com/dotnet/runtime/issues/42820.

**Comment by masonwheeler** [comment]
That would probably be acceptable, though the current state that PR left the code in is still quite bad.  In particular, it throws an exception with a generic "argument out of range" message.  If you're making a breaking change to existing code *and* providing a better way to do the same thing, it would really help if the error message said "try using this new API instead."  (And yes, I understand that the new API isn't in the system yet.  Just something to keep in mind in order to minimize future damage.)

**Comment by masonwheeler** [comment]
@stephentoub  BTW it looks like you reopened issue #46595 after I posted this, but the issue remains in "locked as resolved and limited to collaborators" status, with non-team members unable to comment.

**Comment by stephentoub** [comment]
> issue remains in "locked 

fixed
