### ISSUE TITLE
Will loading IJW (mixed C++/CLI) assemblies into a collectible AssemblyLoadContext be supported?

### ISSUE THREAD

**Issue by williamfigtree** [dotnet/runtime#72237]
Currently attempts to load an IJW (mixed C++/CLI) assembly into a collectible assembly load context throws the following exception:

> BadImageFormatException: Cannot load a mixed assembly into a collectible AssemblyLoadContext.

It is not clear to me why this is the current behaviour. I have only been able to find https://github.com/dotnet/runtime/issues/11164 which offers no explanation.

I have a scenario which dynamically loads plugins (consisting of multiple assemblies) into assembly load contexts. I would like to unload the plugins when they are no longer in use however as some of the dlls are IJW assemblies I am forced to use a non-collectible assembly load context.

Are there any plans to support loading IJW assemblies in a collectible assembly load context? If not why?

**Comment by teo-tsirpanis** [comment]
Quoting from #23430:

> IJW (mixed assemblies) have many potential issues with unloadability. They can run arbitrary native code that the runtime knows nothing about, they can have data structures that the runtime knows nothing about etc. So attempt to unload them could easily result in memory leaks and crashes.

**Comment by alexrp** [comment]
> Quoting from #23430:

That doesn't look like the right issue.

**Comment by teo-tsirpanis** [comment]
Ahh. 😩 Fixed, thanks for spotting it.
