### ISSUE TITLE
[RyuJIT] Unnecessary reg-to-reg moves in method prolog in pi-digits benchmark methods

### ISSUE THREAD

**Issue by sivarv** [dotnet/runtime#7225]
Here is the prolog of next_term() method from pi-digits benchmark:

```
IN009b: 000000 push     r15
IN009c: 000002 push     r14
IN009d: 000004 push     r13
IN009e: 000006 push     r12
IN009f: 000008 push     rdi
IN00a0: 000009 push     rsi
IN00a1: 00000A push     rbp
IN00a2: 00000B push     rbx
IN00a3: 00000C sub      rsp, 152
IN00a4: 000013 mov      rsi, rcx
IN00a5: 000016 lea      rdi, [rsp+28H]
IN00a6: 00001B mov      ecx, 28
IN00a7: 000020 xor      rax, rax
IN00a8: 000022 rep stosd 
// The below two are unecessary moves
IN00a9: 000024 mov      rcx, rsi
IN00aa: 000027 mov      rsi, rcx
IN00ab: 00002A mov      edi, edx
```

These unnecessary moves materialize in prolog whenever zero-init of the frame needs to use block-init (rep stosd).  In this case, rcx is preserved by moving to rsi and later restored.  Later LSRA could set entry point conditions of the first basic block to have rcx param moved to rsi.

Such unnecessary moves are present in the following methods of pi-digits benchmark:
Calculate
next_term
eliminate_digit
extract_digit

This issue is present on all RyuJIT targets.

category:cq
theme:register-allocator
skill-level:expert
cost:medium

**Comment by CarolEidt** [comment]
This should be at least be analyzed; it may have been fixed

**Comment by benaadams** [comment]
The pi-digits is different I think; but looking at the `extract` method it doesn't have the repeated shuffle
```asm
; Lcl frame size = 144

G_M43618_IG01:
       push     r14
       push     rdi
       push     rsi
       push     rbp
       push     rbx
       sub      rsp, 144
       vzeroupper 
       vxorps   xmm4, xmm4
       mov      rax, -96
       vmovdqa  xmmword ptr [rsp+rax+90H], xmm4
       vmovdqa  xmmword ptr [rsp+rax+A0H], xmm4
       vmovdqa  xmmword ptr [rsp+rax+B0H], xmm4
       add      rax, 48
       jne      SHORT  -5 instr
       mov      rsi, rcx
       mov      edi, edx
						;; bbWeight=1    PerfScore 11.58
G_M43618_IG02:
       lea      rcx, bword ptr [rsi+32]
       mov      rbx, gword ptr [rcx]
       mov      ebp, dword ptr [rcx+8]
       lea      rcx, bword ptr [rsp+80H]
```

**Comment by CarolEidt** [comment]
@benadams - thanks for taking a look at so many of these issues! As you may have inferred, we're doing planning for .NET 6, and in the process going through the backlog. For #5785 I had to go back to an old version of the benchmark to find the version of the benchmark at the time the issue was submitted; this is probably the same or similar version.
