### ISSUE TITLE
False positive for `SYSLIB1006` when user haven't specified `EventID`

### ISSUE THREAD

**Issue by maxkoshevoi** [dotnet/runtime#72263]
### Description

Related to discussion in https://github.com/dotnet/runtime/discussions/70147#discussioncomment-3156868
CC: @davidfowl

[SYSLIB1006](https://docs.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib1006) warning states that multiple logging methods cannot use the same event ID.

But it also fires when EventID isn't specified at all. I've annotated my methods without event id:
```cs
[LoggerMessage(Level = LogLevel.Information, Message = "Hi there")]
...
[LoggerMessage(Level = LogLevel.Information, Message = "Hi there2")]
```

and still get a `SYSLIB1006` warning. 
![image](https://user-images.githubusercontent.com/6609929/171640795-c93cd333-e794-41c8-bcb7-7d0edfb23f79.png)

### Reproduction Steps

Shown above 

### Expected behavior

No warning or at least lower severity event

### Actual behavior

Warning which fails the build (since we have `Treat warnings as errors` enabled)

### Regression?

No

### Known Workarounds

Disable the warning

**Comment by havocbcn** [comment]
According to https://docs.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line#log-event-id
the same EventId could be repeated in different logs.

**Comment by davidfowl** [comment]
Event ids are per category

**Comment by ShreyasJejurkar** [comment]
When this would get addressed? I just now hit this issue!
