### ISSUE TITLE
HttpClient.SendAsync ignores set Content-Type header in Blazor Web Assembly

### ISSUE THREAD

**Issue by fsuk** [dotnet/runtime#72264]
### Description

When calling HttpClient.SendAsync(HttpRequestMessage httpRequestMessage) the ContentType header on the content is ignored and "text/plain" is always sent.

This works in a .NET 6 console application but not in a Blazor Web Assembly (client) project.

### Reproduction Steps

```
        HttpClient httpClient = new HttpClient();
        MyRequest request = new MyRequest();

        var content = new StringContent(System.Text.Json.JsonSerializer.Serialize(request), System.Text.Encoding.UTF8, "application/json");

        HttpRequestMessage httpRequestMessage = new HttpRequestMessage
        {
            RequestUri = new Uri("http://localhost:8000/api/action"),
            Content = content,
            Method = HttpMethod.Post          
        };
      
        httpRequestMessage.SetBrowserRequestMode(BrowserRequestMode.NoCors);
            
        await httpClient.SendAsync(httpRequestMessage);
```

### Expected behavior

The "Content-Type" header should be send in the request as "application/json;charset=UTF-8"

### Actual behavior

The "Content-Type" header is sent as "text/plain;charset=UTF-8"

### Configuration

.NET 6
Blazor Web Assembly (client)
Chrome and Firefox

**Comment by radical** [comment]
cc @TanayParikh

**Comment by fsuk** [comment]
Possibly related to base fetch method
https://github.com/aurelia/http-client/issues/186

**Comment by fsuk** [comment]
Issue may be a limitation of using nocors and the base js fetch method

**Comment by fsuk** [comment]
Assuming HttpClient in WebAssembly calls the standard fetch method.

As per the fetch specification when using no-cors only a limited number of content-types can be used: https://fetch.spec.whatwg.org/#simple-header

"application/x-www-form-urlencoded"
"multipart/form-data"
"text/plain"

Whilst this is not technically a bug with the HttpClient this isn't an obvious limitation on Web Assembly.

I would suggest that HttpClient throws an invalid header exception in this scenario.

**Comment by pavelsavara** [comment]
Is this worth breaking change and complexity of added non-trivial validation logic ?

**Comment by fsuk** [comment]
Possibly not but a note in the documentation would be helpful.

**Comment by lewing** [comment]
I agree It would be useful to get the limitations that fetch imposes on the content-type under different scenarios documented

cc @danroth27

**Comment by pavelsavara** [comment]
Anything marked `UnsupportedOSPlatformAttribute("browser")` 
in HTTP API
https://github.com/dotnet/runtime/blob/c21ae04d923a1e5d2964fed61cc919571cce2efe/src/libraries/System.Net.Http/ref/System.Net.Http.cs#L116
in WS API
https://github.com/dotnet/runtime/blob/c21ae04d923a1e5d2964fed61cc919571cce2efe/src/libraries/System.Net.WebSockets.Client/ref/System.Net.WebSockets.Client.cs#L33

Just from top of my head: things like, streaming `fetch` response. HTTP redirects, proxy, end-headers, cookies, all CORS limitations.
On WS no partial messages. No one-side close.
