### ISSUE TITLE
readytorun\coreroot_determinism\coreroot_determinism\coreroot_determinism.cmd test failure

### ISSUE THREAD

**Issue by jtschuster** [dotnet/runtime#72276]
[Build](https://runfo.azurewebsites.net/view/build/?number=1881535)
[Log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-de6bb606c9244711b8/PayloadGroup0/1/console.20ad0b2c.log?%3Fhelixlogtype%3Dresult)

Runfo Tracking Issue: [readytorun\\coreroot_determinism\\coreroot_determinism\\coreroot_determinism.cmd](https://runfo.azurewebsites.net/tracking/issue/372)
|Build|Definition|Kind|Run Name|Console|Core Dump|Test Results|Run Client|
|---|---|---|---|---|---|---|---|
|[1881771](https://dev.azure.com/dnceng/public/_build/results?buildId=1881771)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 72172](https://github.com/dotnet/runtime/pull/72172)|coreclr windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72172-merge-1d4d042051c8465d8e/PayloadGroup0/1/console.17085daa.log?%3F%253Fhelixlogtype%253Dresult)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72172-merge-1d4d042051c8465d8e/PayloadGroup0/1/corerun.exe.1920.dmp?%3F%253Fhelixlogtype%253Dresult)||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72172-merge-1d4d042051c8465d8e/PayloadGroup0/b2e5db35-4cea-46c8-b83f-01cae1260b75.log?%3F%253Fhelixlogtype%253Dresult)|
|[1881535](https://dev.azure.com/dnceng/public/_build/results?buildId=1881535)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|coreclr windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-de6bb606c9244711b8/PayloadGroup0/1/console.20ad0b2c.log?%3F%253Fhelixlogtype%253Dresult)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-de6bb606c9244711b8/PayloadGroup0/1/corerun.exe.8788.dmp?%3F%253Fhelixlogtype%253Dresult)||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-de6bb606c9244711b8/PayloadGroup0/2f1799ed-8a20-4650-8b9e-ff2a19fb8b89.log?%3F%253Fhelixlogtype%253Dresult)|
|[1877656](https://dev.azure.com/dnceng/public/_build/results?buildId=1877656)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 72082](https://github.com/dotnet/runtime/pull/72082)|coreclr windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72082-merge-efbbeb6e6fe746d9b7/PayloadGroup0/1/console.81663f2f.log?%3F%253Fhelixlogtype%253Dresult)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72082-merge-efbbeb6e6fe746d9b7/PayloadGroup0/1/corerun.exe.2420.dmp?%3F%253Fhelixlogtype%253Dresult)||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72082-merge-efbbeb6e6fe746d9b7/PayloadGroup0/60fe4148-d32d-4442-8ffb-ec5d62acf528.log?%3F%253Fhelixlogtype%253Dresult)|
|[1877656](https://dev.azure.com/dnceng/public/_build/results?buildId=1877656)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 72082](https://github.com/dotnet/runtime/pull/72082)|coreclr windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72082-merge-b9e2be01d2f24994b2/PayloadGroup0/1/console.1dfe3a05.log?%3F%253Fhelixlogtype%253Dresult)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72082-merge-b9e2be01d2f24994b2/PayloadGroup0/1/corerun.exe.5324.dmp?%3F%253Fhelixlogtype%253Dresult)||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72082-merge-b9e2be01d2f24994b2/PayloadGroup0/c8823da1-87e9-45b2-9dd5-9be927080c41.log?%3F%253Fhelixlogtype%253Dresult)|
|[1877656](https://dev.azure.com/dnceng/public/_build/results?buildId=1877656)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 72082](https://github.com/dotnet/runtime/pull/72082)|coreclr windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72082-merge-9f8c53916b3a430697/PayloadGroup0/1/console.8f1199bd.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72082-merge-9f8c53916b3a430697/PayloadGroup0/0d8a05f1-e5eb-4a57-abeb-5988b5b590b6.log?%3F%253Fhelixlogtype%253Dresult)|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|0|3|3|

**Comment by jakobbotsch** [comment]
Looks like a dup of #70231
