### ISSUE TITLE
AV x64 dotnet.exe on windows arm64

### ISSUE THREAD

**Issue by MarcoRossignoli** [dotnet/runtime#72284]
### Description

Full description inside the [item](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1576188)

**Comment by MarcoRossignoli** [comment]
cc : @jkotas

**Comment by jkotas** [comment]
Potentially related to https://github.com/dotnet/runtime/issues/64884

**Comment by mangod9** [comment]
assume this is a dupe of https://github.com/dotnet/runtime/issues/71856. @janvorli is looking into it.

**Comment by mangod9** [comment]
the related https://github.com/dotnet/runtime/issues/71856 is closed. Please validate on latest rc1 builds.
