### ISSUE TITLE
Microsoft.Extensions.FileProviders.Physical.Tests Failure on Mono in runtime-extra-platforms

### ISSUE THREAD

**Issue by jtschuster** [dotnet/runtime#72288]
[Build](https://runfo.azurewebsites.net/view/build/?number=1880254)

**Comment by danmoseley** [comment]
@jtschuster could you please include diagnostic info - relevant log etc when opening issues for failed tests?

in this case
```

C:\h\w\B6A70A14\w\B1E60953\e>powershell -ExecutionPolicy ByPass -NoProfile -File "xharness-helix-job.android.ps1" -app "Microsoft.Extensions.FileProviders.Physical.Tests.apk" -command_timeout 2280 -timeout "00:30:00" -package_name "net.dot.Microsoft.Extensions.FileProviders.Physical.Tests" -instrumentation "net.dot.MonoRunner"  
Thread failed to start.

C:\h\w\B6A70A14\w\B1E60953\e>set _commandExitCode=1 

```
You believe this is a bug Microsoft.Extensions.FileSystem?

**Comment by danmoseley** [comment]
I'm going to guess more likely a quirk/issue in Android, our infrastructure, or the Mono runtime itself, or perhaps some low memory condition.

**Comment by steveisok** [comment]
From the logs, this appears to be an infrastructure failure when trying to install the app.  Closing this issue as it appears to be no longer happening.

https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-70db570bc8eb4e429a/Microsoft.Extensions.FileProviders.Physical.Tests/1/console.c55d0a34.log?helixlogtype=result
