### ISSUE TITLE
Path.GetFileNameWithoutExtension() does not throw ArgumentException ("Illegal characters in path") on Windows

### ISSUE THREAD

**Issue by arvindshmicrosoft** [dotnet/runtime#72307]
### Description

I'm migrating a project from .NET Framework 4.7.2 to .NET 6.0. One of my tests is failing, and I have isolated the issue to Path.GetFileNameWithoutExtension seemingly handling the path like it is a Unix path. Consequently, it returns the entire path except the extension, and does not throw if I had invalid (for Windows) characters in the path.

### Reproduction Steps
```csharp
string fileName = @"<<System32\KERNELBASE.dll>>";
string result;
Console.WriteLine(Environment.OSVersion);
Console.WriteLine(Environment.OSVersion.Platform);
result = Path.GetFileNameWithoutExtension(fileName);
Console.WriteLine("GetFileNameWithoutExtension('{0}') returns '{1}'", fileName, result);
```

The csproj is below:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
```

### Expected behavior

ArgumentException should be thrown as the `<` and `>` characters are invalid for Windows. In .NET Framework 4.7.2 for example, the above code results in the following exception:
```
[System.ArgumentException: Illegal characters in path.]
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at System.IO.Path.GetFileNameWithoutExtension(String path)
```

### Actual behavior
```
Microsoft Windows NT 10.0.22000.0
Win32NT
GetFileNameWithoutExtension('<<System32\KERNELBASE.dll>>') returns 'KERNELBASE'
```
### Regression?

Maybe?

### Configuration

.NET 6.0.7
OS: Windows 11 - 10.0.22000 Build 22000
Architecture: x64

**Comment by Fabi** [comment]
Can't reproduce on macOS, linux and w10/11 with latest .net6 and .net 7 prefiew. All return the expected result.

**Comment by jkotas** [comment]
I am not able to reproduce it either. @arvindshmicrosoft Could you please double check the repro steps and the result that you are seeing?

**Comment by stephentoub** [comment]
I can't repro it either, and from looking at the code, it's not clear to me how this could happen.

**Comment by arvindshmicrosoft** [comment]
Thank you all for looking. Something must be very specific to my case. I will investigate further and get back.

**Comment by arvindshmicrosoft** [comment]
@Fabi @jkotas @stephentoub - in the process of distilling the repro down, I had missed the core issue, which seems to be that the erstwhile `Illegal characters in path` ArgumentException, which used to be raised from `CheckInvalidPathChars`, does not happen on .NET 6.0 on Windows. I have updated the repro in the first comment in this Issue. I hope it helps understand what might be happening here.

**Comment by jkotas** [comment]
That was intentional breaking change in .NET Core 2.1. More details in https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.1#path-apis-dont-throw-an-exception-for-invalid-characters

**Comment by stephentoub** [comment]
> Illegal characters in path ArgumentException, which used to be raised from CheckInvalidPathChars, does not happen on .NET 6.0 on Windows

That was changed in .NET Core 2.1:
https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.1#path-apis-dont-throw-an-exception-for-invalid-characters
We rely on the OS now for path validation, rather than trying to guess what's valid.

**Comment by arvindshmicrosoft** [comment]
@jkotas and @stephentoub thank you for pointing this out. I really appreciate the help.
