### ISSUE TITLE
Wrong Enter/Leave callbacks for DispatchTailCalls on Linux ARM32

### ISSUE THREAD

**Issue by k15tfu** [dotnet/runtime#72333]
Same as https://github.com/dotnet/runtime/issues/70013, but it turned out it doesn't work for .NET 5/6 on Linux ARM32 either (however works for .NET 7.0.0-preview.4).

cc @jakobbotsch

**Comment by jakobbotsch** [comment]
It is expected that you see this function being called in situations involving tail calls where the runtime needs to insert them. It is what I was trying to say in https://github.com/dotnet/runtime/issues/70013#issuecomment-1142398677.

**Comment by JulieLeeMSFT** [comment]
@k15tfu, does it answer your question? Can we close this issue?

**Comment by k15tfu** [comment]
@jakobbotsch @JulieLeeMSFT Okay, thank you for the explanation!
