### ISSUE TITLE
[NativeAOT] We should be able to hijack in funclets

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#72343]
Currently both Windows and Unix check for funclets in `GetReturnAddressHijackInfo` and bail.

The check existed in Windows and was copied to Unix. 
Since we can stackwalk out of funclets, it is unclear why the check is needed. This needs a follow up.

**Comment by VSadov** [comment]
The difficulty comes from the scenario when funclets are invoked exceptionally and the caller is a native stub. Handling that might be possible. Since the stub is not a random piece of code, we could "unwind" the stub when starting the stack walk. We would also need to know which funclet was hijacked, which is possible if we store some extra info when hijacking. (this is the difference from polling/interrupting inside a funclet - then we do know which funclet it is).

At the moment I am not sure if this worth the effort. We need to examine if it is possible to have a scenario when inability to hijack may result in abnormal pauses. 
(Something like a tight loop that involves a funclet, but if that triggers fully interruptible code, we would be still ok).

**Comment by jkotas** [comment]
We do not hijack in standard CoreCLR either: https://github.com/dotnet/runtime/blob/3303bd326fded4310e9febacc88e9edc223bcfc5/src/coreclr/vm/threadsuspend.cpp#L4874-L4879 .

**Comment by VSadov** [comment]
Yes, "for simplicity". Since we evidently can unwind through funclets if suspended in some inner frame, I was wondering if hijacking in funclets could be allowed. 
Hijacking is certainly possible, but initiating a stackwalk from such hijack seems a bit involved, so, if there are no scenarios where it could cause a pause, I think it is not worth it. 

I will try to construct a scenario. Perhaps some loop that involves a finally, but no calls... And see if it can cause a trouble. Otherwise this may be not interesting.

**Comment by VSadov** [comment]
I have tried to abuse the fact that we do not hijack in funclets to intentionally cause long suspensions, but could not find a way.

When the funclet is entered non-exceptionally (i.e. regular finally) that is not considered a call and if there are no other calls the containing method, it is emitted as fully interruptible, so we can suspend at safe points.

A case when a funclet is entered exceptionally is even less interesting since throwing an exception makes method calls that are hijackable.

I think we can close this.
