### ISSUE TITLE
[NativeAOT] update libunwind

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#72344]
Our copy is 3 years old possibly missing on some bug fixes and improvements.

We need to update our copy with the latest stable snapshot.

**Comment by am11** [comment]
Ideally, we should first extract all the patches which were applied on the original llvm-libunwind code and list their commits in a txt file, as we have done for HP libunwiind (https://github.com/dotnet/runtime/blob/main/src/native/external/libunwind-version.txt) and other external dependencies. Then move `src/coreclr/nativeaot/libunwind` to `src/native/external/llvm-libunwind` and update it to latest version. Finally, upstream all the local patches (or as many as possible).

I can help here.
