### ISSUE TITLE
Type initializer call ordering w.r.t. static field stores does not look right

### ISSUE THREAD

**Issue by SingleAccretion** [dotnet/runtime#72354]
Reproduction:
```cs
using System;
using System.Runtime.CompilerServices;

Problem();

[MethodImpl(MethodImplOptions.NoInlining)]
static void Problem()
{
    [MethodImpl(MethodImplOptions.NoInlining)]
    static int Call() => throw new Exception("Thrown from 'Call'");

    var a = Call();
    ClassWithCctor.StaticField = a;
}

class ClassWithCctor
{
    public static int StaticField;
    static ClassWithCctor() => throw new Exception("Thrown from 'ClassWithCctor'");
}
```
Compile and run.

Expected result: the exception from `Call` is thrown.

Actual result: the type initializer throws instead:
```scala
Unhandled exception. System.TypeInitializationException: The type initializer for 'ClassWithCctor' threw an exception.
 ---> System.Exception: Thrown from 'ClassWithCctor'
```

Cause - the insertion point of the helper here:

https://github.com/dotnet/runtime/blob/aafa91036e1efd3d4dcb67eeb261cb6d8f774685/src/coreclr/jit/importer.cpp#L16140-L16143

category:correctness
theme:basic-cq

**Comment by jakobbotsch** [comment]
Is this a bug? I'm not sure we make any guarantees about when static constructors will run except for "some time before the class is accessed".

**Comment by alexrp** [comment]
This seems spec-compliant to me, but probably fairly unintuitive to most users.

**Comment by SingleAccretion** [comment]
In the standard we have:
```
If not marked BeforeFieldInit then that type’s initializer method is executed at (i.e., 
is triggered by): 

a. first access to any static field of that type, or
b. first invocation of any static method of that type, or
c. first invocation of any instance or virtual method of that type if it is a value 
type or 
d. first invocation of any constructor for that type.
```
I. e. not-beforefieldinit types have "precise" semantics on when the `.cctor` runs.

I agree that it is not clear whether "access" means load instructions only, hence name of the issue.

**Comment by markples** [comment]
cc @SingleAccretion who opened this issue before I close this

**Comment by SingleAccretion** [comment]
> I don't see that behavior with your test case as `Call` is invoked before the static field write, but that's irrelevant to the general question of whether a write should trigger type initialization.

The main point of the issue is that we see the `.cctor` throw before `Call` and not the other way around. We are on the same page about whether "write access" (`stsfld`) should trigger type initialization (it should), so that is encouraging.

Could you share the IR for `Problem` that you observe?

For reference, I tried with a recent-ish runtime build and have:
```scala
***** BB01
STMT00000 ( 0x000[E-] ... 0x005 )
               [000007] --CXG+-----                         *  CALL help long   CORINFO_HELP_GETSHARED_NONGCSTATIC_BASE
               [000005] -----+----- arg0 in rcx             +--*  CNS_INT   long   0x7ffc86b70a88
               [000006] -----+----- arg1 in rdx             \--*  CNS_INT   int    6

***** BB01
STMT00001 ( ??? ... ??? )
               [000003] -ACXG+-----                         *  ASG       int
               [000002] n---G+-N---                         +--*  IND       int
               [000001] I----+-----                         |  \--*  CNS_INT(h) long   0x7ffc86b70b3c static Fseq[StaticField]
               [000000] --CXG+-----                         \--*  CALL      int    RyuJitReproduction.Program:<Problem>g__Call|27_0():int

***** BB01
STMT00002 ( 0x00A[E-] ... 0x00A )
               [000008] -----+-----                         *  RETURN    void
```
(With a `TypeInitializationException` as expected)

**Comment by markples** [comment]
This is a difference between C# code that has been compiled with /optimize vs not.  Without it, we get call / stloc / ldloc / stsfld, and it is fine.  With it, we get call / stsfld, and the importer incorrectly adds the type initialization call before the tree for them.  I'm testing a fix that properly runs this case.
