### ISSUE TITLE
Profiling, profile-guided optimization, and deoptimization

### ISSUE THREAD

**Issue by DemiMarie** [dotnet/runtime#7235]
This is a proposal for profile-guided optimization and deoptimization, much as is performed by the JVM.  This will allow all of the following:

- Devirtualization when (given the currently loaded classes) only one type could be the target of the method invocation.
- Speculative branch analysis: If profiling data shows that a branch is always/never taken, it is possible to assume that the branch will continue to be always/never taken, and not generate code for the other path, instead generating a bailout.
- Speculative devirtualization: if a virtual/interface method has only had one callee seen so far, the call site can be replaced with a test and then a direct call.

**Comment by trylek** [comment]
@AndyAyersMS / @davidwrighton - is this issue still relevant or are we tracking it elsewhere?

**Comment by AndyAyersMS** [comment]
Most of this is now implemented, though we don't fully support partial compilation (we can only do it when not optimizing, and it's not really driven by profile data), and we still haven't enabled partial compilation by default.

So I think we can close this.
