### ISSUE TITLE
Add APIs to make operator ! to implement conjugate operation of Complex struct

### ISSUE THREAD

**Issue by EMROF-H** [dotnet/runtime#72380]
### Background and motivation

Operator override can greatly improve code brevity. Conjugation is a very common operation for complex numbers. Method Conjugate() is too long and not intuitive. Consider we have a unary operators '!', it's really good for conjugate operations. Like bar or asterisk in math. This makes writing programs with complex numbers as straightforward as writing mathematical expressions.

### API Proposal

```csharp
namespace System.Numerics
{
    public readonly struct Complex : IEquatable<Complex>, IFormattable
    {
        public static Complex operator !(Complex value)
        {
            return Complex.Conjugate(value);
        }
    }
}
```

### API Usage

```csharp
class QuadraticEquation
{
    public (Complex, Complex) Solve()
    {
        (Complex, Complex) result;
        float Δ = B * B - 4 * A * C;
        result.Item1 = (-B - Complex.Sqrt(Δ)) / (2 * A);
        result.Item2 = ! result.Item1;
        return result;
    }
}
```

### Risks

It is true that operator ! does not mean conjugate or anything like that. But its function is too single, can only be used for boolean inverse. Adding conjugate does not result in an operator ! is obfuscated. Besides, it can take advantage of the operators ! make him more valuable.

**Comment by tfenise** [comment]
I think `operator !` in C# may become `Not` in VB.Net, or `not` in F#, which does not sound good.

If this is going to be a C#-only thing, maybe one should rather ask for a C# feature to overload operators outside the corresponding type definitions. That way, one can define and use `static Complex operator !(Complex value)` in one's own C#-only codes.

**Comment by tannergooding** [comment]
The .NET Framework Design Guidelines covers this as 
> ❌ DO NOT be cute when defining operator overloads.

That is, you should only use an operator where that mathematically makes sense so using `/` for "path concatenation" or `<<` for "stream output" is a non-starter. In the same way we don't want to use `!` which stands for "logical not" as a stand in for another operation ("conjugate").
