### ISSUE TITLE
Improve build error when python isn't installed

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#72395]
right now on Windows I get
```
C:\git\runtime\eng\python.targets(8,5): error MSB3073: The command "..." exited with code 9009. [C:\git\runtime\src\coreclr\System.Private.CoreLib\System.Private.CoreLib.csproj]
```
which comes from
```xml
    <Exec Command="py -3 $(_PythonLocationScript) 2&gt; nul || python3 $(_PythonLocationScript) 2&gt; nul || python $(_PythonLocationScript) 2&gt; nul" ... 
```

Is there a central place where we make prereq checks of this sort -- for cmake, ninja etc? if we put something right here, one day someone will try to use python before this is reached.

compare eg
```
  BUILD: Error: Visual Studio 2019 or 2022 with C++ tools required. Please see https://github.com/dotnet/runtime/blob/main/docs/workflow/requirements/windows-requirements.md for build requirements.
```
or
```
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
```
which are both helpful

**Comment by huoyaoyuan** [comment]
I wonder that can we reduce dependencies on other scripting languages? There is also Perl script (`coreclr\inc\genrops.pl`) that generates file.

**Comment by laurencee** [comment]
I just ran into this one myself and ended up here, resulting in me installing the latest python and continuing with the build. 
Thanks for raising this issue 👍

**Comment by danmoseley** [comment]
dupe of https://github.com/dotnet/runtime/issues/59724
