### ISSUE TITLE
System.Runtime.Intrinsics.X86.Bmi2 - ADCX and ADOX instructions missing.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#72423]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/SystemRuntimeIntrinsicsX86Bmi2---ADC/10091429)._

---
System.Runtime.Intrinsics.X86.Bmi2.X64 supports MULX as:

```  
public static ulong MultiplyNoFlags(ulong left, ulong right);
public static ulong MultiplyNoFlags(ulong left, ulong right, ulong\* low);
  
```

But **not** the corresponding instructions: [ADCX and ADOX](https://en.wikipedia.org/wiki/Intel_ADX).

It could help to improve a new NET7 development: **[dotnet/runtime/71791](https://github.com/dotnet/runtime/issues/71791)**

Or is it that the compiler generates corresponding code automatically?  
I haven’t found anything documented about this.  
Is there any other way to use the feature or is somthing planned?

---
#### Feedback Bot on 7/10/2022, 11:22 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by c-ohle** [comment]
I can offer to test trial-versions since I have currently the perfect environment for this. Multiply is the main bottleneck in my solution for arbitrary arithmetic, could I double the speed the overall performance would double. I know it's difficult, I've implemented special algorithms in C++ before and this was difficult enough and not possible without inline ASM and lot of trials. But once it works and the right sequences found, the effect is amazing. It would be so nice to see the same in C#.

**Comment by c-ohle** [comment]
@danmoseley Many thanks for the help with the issue - delegated to the right ones. 
There is another main issue what is currently in the pipe: [.NET7 C# CLR support for op_Assign](https://developercommunity.visualstudio.com/home?port=1025&fsid=339c21ca-1992-48fa-88a9-f4343860faaf&entry=myfeedback).
I found a [solution to bypass this ](https://github.com/dotnet/runtime/issues/71791#issuecomment-1188447458) but it does not match the styling rules. 
But it can show how easy it would be to get a dramatic performance boost, not only for special cases. 
It could save so much work and time, would avoid entire builder classes for the user to deal with.
Only some lines of code for the compiler-devs and could be done in hour (or two).

**Comment by c-ohle** [comment]
@tannergooding Sure. this is difficult for C#, I have done this in C++ and there it was difficult too, lots of trials and inline ASM to find the right sequences in combination with the right algorithms. Found something like a standard sequence that works for several multiplier. Maybe this could exposed as meta function for X64.Bmi2. I will write a proposal.

**Comment by dakersnar** [comment]
Closing this in favor of a future formal API proposal, as discussed above.
