### ISSUE TITLE
[wasm][wbt] - Microsoft.Playwright.PlaywrightException : net::ERR_UNSAFE_PORT

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#72436]
We probably allocate random port number.

During CI `Microsoft.Playwright.PlaywrightException : net::ERR_UNSAFE_PORT at http://localhost:5061/`
[Log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72275-merge-ffa6da6bb5f9444697/Workloads-.WasmTemplateTests/1/console.cd39eae8.log?helixlogtype=result)

More info 
chrome - https://superuser.com/questions/188006/how-to-fix-err-unsafe-port-error-on-chrome-when-browsing-to-unsafe-ports
FF - https://www-archive.mozilla.org/projects/netlib/portbanning#portlist

**Comment by pavelsavara** [comment]
cc @radical

**Comment by radical** [comment]
@pavelsavara where did you hit this error?

**Comment by lewing** [comment]
judging by the url wasm template tests for #72275

**Comment by radical** [comment]
Hit another instance of this https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72626-merge-114042c2e0a849789e/Workloads-.WasmTemplateTests/1/console.75a8b2c9.log?helixlogtype=result . I'll fix.

**Comment by pavelsavara** [comment]
Re-opening for new occurence:
`Microsoft.Playwright.PlaywrightException : net::ERR_UNSAFE_PORT at http://localhost:5060/`
[Log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-74441-merge-ab49bf0f70764e48a6/Workloads-.WasmTemplateTests/1/console.ed584191.log?helixlogtype=result)

**Comment by radical** [comment]
@pavelsavara could you please share the link for the build too?

**Comment by radical** [comment]
Hm looks like the fix needs to be enabled for !windows too.
