### ISSUE TITLE
When building coreclr in M1 OSX (arm64), the symbols of corprof artifacts is in amd64 NOT arm64 and that causes build error when building a dotnet profiler for m1 environment

### ISSUE THREAD

**Issue by kgorro** [dotnet/runtime#72432]
### Description

Dotnet Profiler for arm64 in MAC os m1: 
- When building a dotnet profiler it tries to find a icorprofiler symbol for arm64 in corprof but the symbols when building coreclr in m1 is amd64.
Sample build:
Undefined symbols for architecture arm64:
  "_IID_ICorProfilerCallback", referenced from:
      CorProfiler::QueryInterface(_GUID const&, void**) in CorProfiler-ffe494.o
  "_IID_ICorProfilerCallback2", referenced from:
      CorProfiler::QueryInterface(_GUID const&, void**) in CorProfiler-ffe494.o
  "_IID_ICorProfilerCallback3", referenced from:
      CorProfiler::QueryInterface(_GUID const&, void**) in CorProfiler-ffe494.o
  "_IID_ICorProfilerCallback4", referenced from:
      CorProfiler::QueryInterface(_GUID const&, void**) in CorProfiler-ffe494.o
  "_IID_ICorProfilerCallback5", referenced from:
      CorProfiler::QueryInterface(_GUID const&, void**) in CorProfiler-ffe494.o
  "_IID_ICorProfilerCallback6", referenced from:
      CorProfiler::QueryInterface(_GUID const&, void**) in CorProfiler-ffe494.o
  "_IID_ICorProfilerCallback7", referenced from:
      CorProfiler::QueryInterface(_GUID const&, void**) in CorProfiler-ffe494.o
  "_IID_ICorProfilerInfo7", referenced from:
      CorProfiler::Initialize(IUnknown*) in CorProfiler-ffe494.o
ld: symbol(s) not found for architecture arm64

### Reproduction Steps

1.) built coreclr using :
./build.sh -a arm64 -c release

Note: This is built in Mac osx m1.
arm64-apple-darwin21.1.0
The coreclr got built without error but the corprof in artifacts is in amd64.

2.) My build script for my profiler:
#!/bin/bash

pushd $(dirname $0)

[ -z "${CORECLR_PATH:-}" ] && CORECLR_PATH=~/git/runtime
[ -z "${BoostPath:-}"      ] && BoostPath=~/boost/boost_1_76_0
[ -z "${BuildOS:-}"      ] && BuildOS=OSX
[ -z "${BuildArch:-}"    ] && BuildArch=arm64
[ -z "${BuildType:-}"    ] && BuildType=Debug
[ -z "${TargetRID:-}"       ] && TargetRID=OSX.arm64
[ -z "${Output:-}"       ] && Output=StackifyProfiler.dylib
[ -z "${HomePath:-}"       ] && HomePath=~/
printf '  CORECLR_PATH : %s\n' "$CORECLR_PATH"
printf '  BuildOS      : %s\n' "$BuildOS"
printf '  BuildArch    : %s\n' "$BuildArch"
printf '  BuildType    : %s\n' "$BuildType"
printf '  HomePath    : %s\n' "$HomePath"

mkdir -p $BuildType

CXX_FLAGS="$CXX_FLAGS -Wduplicate-decl-specifier -Wno-invalid-noreturn -Wno-error -Wno-unused-local-typedefs -fPIC -fms-extensions -fvisibility=hidden -DOSX=1 -DBIT64 -DPAL_STDCPP_COMPAT -DPLATFORM_UNIX -Wno-narrowing -Wnull-conversion -std=c++11 -Wunused-value -Wno-pragma-pack -Wno-deprecated-declarations --target=arm64-apple-darwin21.1.0"
INCLUDES="-I include -I $BoostPath -I rapidjson/include -I $CORECLR_PATH/src/coreclr/pal/inc/rt -I $CORECLR_PATH/src/coreclr/pal/prebuilt/inc -I $CORECLR_PATH/src/coreclr/pal/inc -I  $CORECLR_PATH/src/coreclr/inc -I $CORECLR_PATH/artifacts/bin/coreclr/$BuildOS.$BuildArch.Release/inc " 
LINK="-L $CORECLR_PATH/artifacts/obj/coreclr/$BuildOS.$BuildArch.Release/pal/src -lcoreclrpal  -L $BoostPath/stage/lib -lpthread -lboost_locale -lboost_log_setup -lboost_log -lboost_thread -lboost_filesystem -lboost_system -liconv -framework CoreFoundation -framework Security "
SRC=$(find $PWD -type d -name "Stackify.ClrProfiler")
SOURCES=$(find $SRC -type f \( -iname "*.cpp" ! -iname "Assembly*" \))

printf '  Includes: %s\n' "$INCLUDES"
printf '  Sources %s\n' "$SOURCES"
printf '  Link %s\n' "$LINK"
printf '  Building %s ... ' "$TargetRID/$Output"

#gcc -fPIC -c ./asm/AsmHelpers.S -o ./asm/AsmHelpers.o
if [ "$BuildType" == "Debug" ] 
then
 echo "Enable Macro DEBUG" 
 MACRO="DEBUG=1"
else
 echo "Disable Macro DEBUG"
 MACRO="DEBUG=0"
fi
mkdir -p $BuildType/$TargetRID
clang++ -D $MACRO -g -shared -o $BuildType/$TargetRID/$Output $CXX_FLAGS $INCLUDES $SOURCES $LINK

printf 'Done.\n'

popd

### Expected behavior

corprof in artifacts should be in arm64 not in amd64 arch

### Actual behavior

corprof artifacts is built in amd64 not in arm64.

**Comment by am11** [comment]
> ./build.sh -arm64 -c release

Do you get the same error with: `./build.sh -arch arm64 -c release`? (delete `artifacts` directory before running the command)

**Comment by kgorro** [comment]
> > ./build.sh -arm64 -c release
> 
> Do you get the same error with: `./build.sh -arch arm64 -c release`? (delete `artifacts` directory before running the command)

I just a have typo but I built it the coreclr using ./build.sh -a arm64 -c release, so the coreclr got built but the corprof is built in amd64

**Comment by tommcdon** [comment]
>  ...I built it the coreclr using ./build.sh -a arm64 -c release, so the coreclr got built but the corprof artifacts is built in amd64

Adding @davmason who might have some thoughts on how to resolve the issue

**Comment by davmason** [comment]
Hi @kgorro,

When you say the corprof is amd64, do you mean that after building coreclr the corprof.h is located in the build output  for amd64, or do you mean after taking corprof.h and including it in your profiler there are types defined for amd64?

corprof.h should be the same across all architectures, it relies on other headers and defines to set the sizes and layouts for types.

**Comment by kgorro** [comment]
@davmason , after building coreclr, it is indeed the build directory is arm64 for the artifacts but when I included it in my build corprof.h seems to be in amd64 (especially for CorProfilerCallback) and it throws an error :

2 warnings generated.
Undefined symbols for architecture arm64:
  "_IID_ICorProfilerCallback", referenced from:
      CorProfiler::QueryInterface(_GUID const&, void**) in CorProfiler-ffe494.o
  "_IID_ICorProfilerCallback2", referenced from:
      CorProfiler::QueryInterface(_GUID const&, void**) in CorProfiler-ffe494.o
  "_IID_ICorProfilerCallback3", referenced from:
      CorProfiler::QueryInterface(_GUID const&, void**) in CorProfiler-ffe494.o
  "_IID_ICorProfilerCallback4", referenced from:
      CorProfiler::QueryInterface(_GUID const&, void**) in CorProfiler-ffe494.o
  "_IID_ICorProfilerCallback5", referenced from:
      CorProfiler::QueryInterface(_GUID const&, void**) in CorProfiler-ffe494.o
  "_IID_ICorProfilerCallback6", referenced from:
      CorProfiler::QueryInterface(_GUID const&, void**) in CorProfiler-ffe494.o
  "_IID_ICorProfilerCallback7", referenced from:
      CorProfiler::QueryInterface(_GUID const&, void**) in CorProfiler-ffe494.o
  "_IID_ICorProfilerInfo7", referenced from:
      CorProfiler::Initialize(IUnknown*) in CorProfiler-ffe494.o
ld: symbol(s) not found for architecture arm64

I did not encounter this issue in building our dotnet profiler in linux arm64 only in M1 OSX.

**Comment by davmason** [comment]
@kgorro what makes you say that it is in amd64? The error that you posted is missing symbols, which means you don't have the corprof_i.cpp included in your build.

The interface definitions in arm64 and amd64 should be the same since they use the same sizes for pointers.

**Comment by kgorro** [comment]
@davmason I added that corprof_i.cpp in my first try a month ago and it works but if you check the generated corprof.h is amd64. I am just curious if this is the reason why moduleID in my previous inquiry has incorrect size:
![image](https://user-images.githubusercontent.com/49682861/181565062-bb7a1f70-e172-4462-86e3-4c065b2bbd0a.png)

**Comment by davmason** [comment]
That should not matter, there shouldn't be anything architecture specific in corprof.h, the only thing that matters is 64 or 32 bit.

The best way to track this sort of thing down is to find the whole command line for building the particular file the method is in, then using the preprocess only argument to your compiler (-E in clang) and then looking at the resulting file. You should be able to track typedefs etc to their underlying types.

**Comment by kgorro** [comment]
@davmason this is fix on our side, we brute force the compilation by adding all arm64 related compiler setting. This suppose to be close but we are seeing: 
Profiling API: Profiler was prevented from loading notification 0x2509 (_Actually this does not affect the functionality of the profiler._) We are receiving callbacks with module load and jit callbacks but we just want to make sure why is this occurring.

**Comment by davmason** [comment]
@kgorro that was a bug where we would inadvertently emit that error message, it should not impact your profiler. It is also fixed in .net 7
