### ISSUE TITLE
MultipartFormDataContent potentially not compliant with RFC 6266 and RFC 7578

### ISSUE THREAD

**Issue by Embo1** [dotnet/runtime#72447]
### Description

https://github.com/microsoft/referencesource/blob/master/System/net/System/Net/Http/MultipartFormDataContent.cs

 public void Add(HttpContent content, string name)  Adds the name parameter without enclosing quotes "

https://datatracker.ietf.org/doc/html/rfc7578
https://datatracker.ietf.org/doc/html/rfc6266

This issue is causing the WAF at certain clients to block these requests as non compliant. 

See difference in bolded text in Expected and Actual behavior

### Reproduction Steps

```

using (var client = new HttpClient() { Timeout = TimeSpan.FromSeconds(10) })
{
    using (var content = new MultipartFormDataContent())
    {
        content.Add(new StringContent("abc"), "token");
        var response = await client.PostAsync("http://localhost", content);
        var result = await response.Content.ReadAsStringAsync();
    }
}
```

### Expected behavior

```
POST http://localhost/ HTTP/1.1
Host: localhost
Content-Type: multipart/form-data; boundary="4b39ed14-752b-480a-9846-fc0019132d15"
Content-Length: 174

--4b39ed14-752b-480a-9846-fc0019132d15
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name="token"

abc
--4b39ed14-752b-480a-9846-fc0019132d15--
```

### Actual behavior

```
POST http://localhost/ HTTP/1.1
Host: localhost
Content-Type: multipart/form-data; boundary="4b39ed14-752b-480a-9846-fc0019132d15"
Content-Length: 174

--4b39ed14-752b-480a-9846-fc0019132d15
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=token

abc
--4b39ed14-752b-480a-9846-fc0019132d15-
```

### Regression?

Unsure

### Configuration

.Net 6 
Windows 11 
X 64
I don't think this is specific to this configuration.
Not Blazor related

**Comment by ManickaP** [comment]
@Embo1 where in the spec did you found **name** needs to quoted?

BTW, as a workaround, you can pass quoted name as a parameter, it should get encoded and re-quoted:
https://source.dot.net/#System.Net.Http/System/Net/Http/Headers/ContentDispositionHeaderValue.cs,d24ba545a7430a38,references

**Comment by MihaZupan** [comment]
The RFC you link explicitly allows the un-quoted form:

> value = token | quoted-string

> Use the 'token' form of the filename parameter only when it does
  not contain disallowed characters (e.g., spaces); in such cases,
  the quoted-string form should be used.

**Comment by karelz** [comment]
Triage: We behave according to RFC. There is a workaround. Closing.
Let us know if there is anything we missed. Thanks!
