### ISSUE TITLE
Windows Server 2022 - Setting affinity in .NET 6 application errors

### ISSUE THREAD

**Issue by Marcus-Smallman** [dotnet/runtime#72441]
Hi,

I have a Windows Server 2022 machine with 40 cores and 80 logical processors. Whenever I try and run my application on this machine and attempt to set it's affinity in code or via Task Manager, I get errors.

The error I get in code is:
![image](https://user-images.githubusercontent.com/10182314/179731539-0497f9f5-f1dd-419f-a237-0efe593cb4b3.png)
`Win32Exception (87): The parameter is incorrect`

When I try and set it via Task Manager (as an admin with UAC disabled) I get:
![image](https://user-images.githubusercontent.com/10182314/179731910-a9db8ed0-d872-4f3b-9fcc-d008c04f476b.png)
`Unable to access or set process affinity`

Also, when I try and get the affinity mask for the process in code, I get `0` back.
After reading the docs:
https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getprocessaffinitymask
https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setprocessaffinitymask
https://docs.microsoft.com/en-us/windows/win32/procthread/processor-groups
It is clear that on Windows 11 and Server 2022 that threads are not bound to a single processor group any more if there are more than 64 processors and can run across multiple processor groups.

My theory is that I am unable to set the affinity for my application because it is performing actions on threads across multiple processor groups.
I have tried setting the affinity mask at startup in my application using:
```
Process proc = Process.GetCurrentProcess();
long affinityMask = (long)proc.ProcessorAffinity;
affinityMask &= 15; // First 4 processors
proc.ProcessorAffinity = (IntPtr)affinityMask;
```
But I just get the `Win32Exception (87): The parameter is incorrect`
And when I try to get the affinity mask at start up it is set to `0` meaning it was unable to get it because there are threads in multiple groups.

**So for me, is it possible to set a .NET 6 application to ONLY run in a single processor group on Windows Server 2022 before the application runs, so I can then set its affinity mask?**

**Comment by jkotas** [comment]
Related conversation: https://github.com/dotnet/runtime/pull/68639#issuecomment-1112086741

cc @AntonLapounov @stephentoub @kouvel @Maoni0 @kunalspathak

**Comment by AntonLapounov** [comment]
Do you have `DOTNET_GCCpuGroup` / `DOTNET_Thread_UseAllCpuGroups` environment variables or corresponding configuration settings defined for your app?  Setting `ProcessorAffinity` should work unless you have explicitly asked the runtime to use multiple processor groups via configuration settings.

**Comment by jkotas** [comment]
> Setting ProcessorAffinity should work unless you have explicitly asked the runtime to use multiple processor groups via configuration settings.

Chances are that there are other non-.NET components loaded into the process that do not follow this restriction. For example, what is the [Windows threadpool](https://docs.microsoft.com/en-us/windows/win32/api/threadpoolapiset/nf-threadpoolapiset-createthreadpool) behavior - does it restrict itself from creating threads in multiple processor groups?

**Comment by AntonLapounov** [comment]
That OS behavior change has been implemented in backward compatible manner.  A process must explicitly declare itself multigroup-aware (by calling a relevant API) to break the existing APIs like `SetProcessAffinityMask`.  Otherwise, the legacy affinity APIs should continue to work even if the process is currently running on multiple processor groups (but not explicitly multigroup-aware).

> So for me, is it possible to set a .NET 6 application to ONLY run in a single processor group

One can use `start /affinity ...` for that purpose.

**Comment by kunalspathak** [comment]
> what is the [Windows threadpool](https://docs.microsoft.com/en-us/windows/win32/api/threadpoolapiset/nf-threadpoolapiset-createthreadpool) behavior - does it restrict itself from creating threads in multiple processor groups?

I tried it on machine that has 26 physical cores and 52 logical processors (with Hyperthreading ON) and `CreateThreadPool()` works fine. Is there something specific that you want me to check @jkotas ?

**Comment by jkotas** [comment]
If you flood the Windows threadpool with workitem, are all of them going to be scheduled on the primary processor group, or is the threadpool going to schedule them across all processor groups by default?

**Comment by jkotas** [comment]
> I tried it on machine that has 26 physical cores and 52 logical processors

Do you see multiple processor groups on this machine? I would expect that this machine has 1 processor group. I think one needs a machine with >64 logical processors to investigate this.

**Comment by AntonLapounov** [comment]
> or is the threadpool going to schedule them across all processor groups by default

It will use other processor groups as well; however, that doesn't make the process multigroup-aware.

FWIW, I just tried the code snippet below on an 80 core Windows Server 2022 Build 25058.1000 with the latest ARM64 SDK 6.0.302 and it worked fine:
```C#
Process proc = Process.GetCurrentProcess();
long affinityMask = (long)proc.ProcessorAffinity;
affinityMask &= 15; // First 4 processors
proc.ProcessorAffinity = (IntPtr)affinityMask;
```

**Comment by kunalspathak** [comment]
> I think one needs a machine with >64 logical processors to investigate this.

Ah, true.

**Comment by jkotas** [comment]
> Do you have DOTNET_GCCpuGroup / DOTNET_Thread_UseAllCpuGroups environment variables or corresponding configuration settings defined for your app? 

Another possibility is that something in your app calls `SetThreadGroupAffinity` Windows API that makes the process multigroup-aware but also breaks the old process affinity APIs. You should be able to find out by running your app under debuggers and setting a breakpoint at `kernelbase!SetThreadGroupAffinity`.

We would appreciate a lot if you can help us to find out what's causing the affinity setting to fail in your app.

**Comment by Marcus-Smallman** [comment]
Thanks for the responses,
The application does not have the `DOTNET_GCCpuGroup` / `DOTNET_Thread_UseAllCpuGroups` environment variables set, or the corresponding config settings.

I am also unable to run the app under a debugger on that machine as it is a machine that can not be used for development.

Another point that I should mention, is that when we downgrade the app to .NET 5, it works fine and affinity can be set.
I understand that it should work with .NET 6 and I have tried to reproduce the issue in a barebones application too, but I am unable to reproduce what we see in this specific application.

I will keep looking but if there is anything you know I could try without using a debugger, that would be really great, Thanks.

**Comment by Marcus-Smallman** [comment]
That makes sense. So how would one go about setting a multi-group aware process to be affinitised to the first 4 cores in a single processor group?

**Comment by jkotas** [comment]
I do not think that there is a way to do that today. The affinity has to be set during process startup or before the process becomes multi-group aware. @AntonLapounov Is that right?

**Comment by Marcus-Smallman** [comment]
Ok, thanks very much for the help. I will do some more testing to see if it can be worked around. It would maybe be a good idea to have a kestrel option to disable the use of Quic? so that when upgrading to .NET 6 it can be ignored until an appropriate time to implement support for multi-group awareness. Also, from my reading it wasn't made clear in any breaking changes document that on Windows 11/Server 2022 with more than 64 processors that upgrading to .NET 6 would break setting the process affinity after a kestral host has been instantiated. Possibly an addition in the docs there too.

**Comment by jkotas** [comment]
> It would maybe be a good idea to have a kestrel option to disable the use of Quic?

Quic is just a tip of the iceberg. There are number of other components that call `SetThreadGroupAffinity` API. If the app happens to use any of these components, it will again become multi-group aware. It means that setting the proces affinity using the old APIs is unlikely going to work on any large app on machines with more than 64 process.

I agree that this needs to be documented better.

**Comment by Marcus-Smallman** [comment]
> I do not think that there is a way to do that today. The affinity has to be set during process startup or before the process becomes multi-group aware. @AntonLapounov Is that right?

If this is true, then that would good to know.

**Comment by AntonLapounov** [comment]
That is correct, once the process becomes multigroup-aware, the `SetProcessAffinityMask` Win32 function (that is what `Process.ProcessorAffinity`'s setter uses underneath) would always fail with `ERROR_INVALID_PARAMETER` (error 87).  Even if you successfully set an affinity mask, some components may break away by replacing that mask or calling `SetThreadGroupAffinity`.  In case you need to enforce a limit on CPU usage, a Win32 job object or a Docker container should be used.

**Comment by AntonLapounov** [comment]
Closing this issue as external to the runtime.
