### ISSUE TITLE
ArgumentNullException in dotnet.6.0.7.hr41unoldr.js

### ISSUE THREAD

**Issue by Norsotec** [dotnet/runtime#72457]
### Description

my simple blazor wasm AOT application throwing ArgumentNullExceptions in dotnet.6.0.7.hr41unoldr.js
it only happens to me on Android Devices on chrome, not on windows 10 chrome desktop.

```
Uncaught (in promise) Error: System.ArgumentNullException: ArgumentNull_String Arg_ParamName_Name, s
    at Object._convert_exception_for_method_call (dotnet.6.0.7.hr41unoldr.js:1:159071)
    at Object._handle_exception_for_call (dotnet.6.0.7.hr41unoldr.js:1:161040)
    at managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS (mono-wasm.invalid/ma…e_EndInvokeJS:17:21)
    at Object.endInvokeJSFromDotNet (blazor.webassembly.js:1:42191)
    at blazor.webassembly.js:1:3371
_convert_exception_for_method_call	@	dotnet.6.0.7.hr41unoldr.js:1
_handle_exception_for_call	@	dotnet.6.0.7.hr41unoldr.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS	@	mono-wasm.invalid/ma…time_EndInvokeJS:17
endInvokeJSFromDotNet	@	blazor.webassembly.js:1
(anonymous)
```

### Reproduction Steps

i don't know how to reproduce this, it worked already for weeks without this problem.

### Expected behavior

 the expected behavior is not to trow this exception

### Actual behavior

the app is showing up without a error msg, but not responding if i try to navigate to another page, it looks like the OnInitializedAsync is also not raised.

### Known Workarounds

none till now

### Configuration

the newst .net 6 hosted server releases
OS = Win Server 2019 Essentials
x64

**Comment by lewing** [comment]
can you share your code to reproduce this?

**Comment by Norsotec** [comment]
this ticket can be closed, i can not reproduce the problem
