### ISSUE TITLE
[API Proposal]: Provide a result returning Parallel.ForEachAsync overload

### ISSUE THREAD

**Issue by Sossenbinder** [dotnet/runtime#72489]
### Background and motivation

Recently there was a very welcome addition of the ForEachAsync method in the Parallel class, which merges the well known scheduling capabilities of the Parallel class with the async compatible Task stack.

I had various use cases in which I wanted to have something like this, with configurable degree of parallelism in order to throttle an async operation, may it be to avoid ddosing our own server endpoints or for other reasons.

However, right now the Parallel.ForEachAsync only works for this use case when the data flows one way, since all existing methods simply return a Task. Let's assume I want to receive data from this endpoint however. The best way to do this right now is probably something like:

```
static Task<int> DoComplexWork(int source) => Task.FromResult(source * 2);

var workItems = new List<int>() { 0, 1, 2, 3, 4 };
var foreachAsyncResult = new ConcurrentBag<int>();
await Parallel.ForEachAsync(workItems, async (x, _) => foreachAsyncResult.Add(await DoComplexWork(x)));
```

This works well, but it feels like this is something which might just be embedded as a Parallel overload. While the Parallel.ForEachAsync was probably meant as an async counterpart to Parallel.ForEach, it also is a bit special since to me it feels like it is a natural addition to `Task.WhenAll`, just with throttling capabilities on top. When you draw this comparison, it's a bit unnatural that with WhenAll you can simply grab results in a one-liner:

```
var workItems = new List<int>() { 0, 1, 2, 3, 4 };
var whenAllResult = await Task.WhenAll(workItems.Select(DoComplexWork));
```

I read up a bit in the proposals for ForEachAsync whether there was a discussion about breaking the counterpart-compatible method signature, but I did not find a concrete decision regarding what happens to it.

Baseline, it would be great to have both an overload which returns `IReadOnlyList<T>` as a simple, plain counterpart of what Task.WhenAll providers.

I'm tempted to also propose an overload which returns `IAsyncEnumerable<T>`, since it sounds like a natural fit - A throttled process will most likely finish some tasks earlier than others and the consumer could already get going while waiting for the remaining items.

### API Proposal

```csharp
namespace System.Threading.Tasks
{
	public static partial class Parallel
	{
		public static Task<IReadOnlyList<TResult>> ForEachAsync<TSource, TResult>(IEnumerable<TSource> source, Func<TSource, CancellationToken, ValueTask<TResult>> body);

		public static Task<IReadOnlyList<TResult>> ForEachAsync<TSource, TResult>(IEnumerable<TSource> source, CancellationToken cancellationToken, Func<TSource, CancellationToken, ValueTask<TResult>> body);

		public static Task<IReadOnlyList<TResult>> ForEachAsync<TSource, TResult>(IEnumerable<TSource> source, ParallelOptions parallelOptions, Func<TSource, CancellationToken, ValueTask<TResult>> body);

		public static Task<IReadOnlyList<TResult>> ForEachAsync<TSource, TResult>(IAsyncEnumerable<TSource> source, Func<TSource, CancellationToken, ValueTask<TResult>> body);

		public static Task<IReadOnlyList<TResult>> ForEachAsync<TSource, TResult>(IAsyncEnumerable<TSource> source, CancellationToken cancellationToken, Func<TSource, CancellationToken, ValueTask<TResult>> body);

		public static Task<IReadOnlyList<TResult>> ForEachAsync<TSource, TResult>(IAsyncEnumerable<TSource> source, ParallelOptions parallelOptions, Func<TSource, CancellationToken, ValueTask<TResult>> body);

		public static IAsyncEnumerable<TResult> ForEachAsync<TSource, TResult>(IEnumerable<TSource> source, Func<TSource, CancellationToken, ValueTask<TResult>> body);

		public static IAsyncEnumerable<TResult> ForEachAsync<TSource, TResult>(IEnumerable<TSource> source, CancellationToken cancellationToken, Func<TSource, CancellationToken, ValueTask<TResult>> body);

		public static IAsyncEnumerable<TResult> ForEachAsync<TSource, TResult>(IEnumerable<TSource> source, ParallelOptions parallelOptions, Func<TSource, CancellationToken, ValueTask<TResult>> body);

		public static IAsyncEnumerable<TResult> ForEachAsync<TSource, TResult>(IAsyncEnumerable<TSource> source, Func<TSource, CancellationToken, ValueTask<TResult>> body);

		public static IAsyncEnumerable<TResult> ForEachAsync<TSource, TResult>(IAsyncEnumerable<TSource> source, CancellationToken cancellationToken, Func<TSource, CancellationToken, ValueTask<TResult>> body);

		public static IAsyncEnumerable<TResult> ForEachAsync<TSource, TResult>(IAsyncEnumerable<TSource> source, ParallelOptions parallelOptions, Func<TSource, CancellationToken, ValueTask<TResult>> body);
	}
}
```

### API Usage
```
static ValueTask<int> DoStuff(int param, CancellationToken _) => ValueTask.FromResult(param * 2);

var workItems = new List<int>() { 0, 1, 2, 3, 4 };
var resultItems = await Parallel.ForEachAsync(workItems, DoStuff);
resultItems.Dump();

await foreach (var result in Parallel.ForEachAsync(workItems, DoStuff))
{
	result.Dump();
}
```

### Risks

- Adding this would break the matching signatures with the Parallel.ForEach counterpart.
- Potentially confusing signature, since `ForEach` usually does not go hand in hand with returning values which is rather connected to a .Select() or generally a map-like operation

**Comment by theodorzoulias** [comment]
​What about the order of the results? Will they be in the same order as the `IEnumerable<TSource> source` and the `IAsyncEnumerable<TSource> source`?

**Comment by Sossenbinder** [comment]
> ​What about the order of the results? Will they be in the same order as the `IEnumerable<TSource> source` and the `IAsyncEnumerable<TSource> source`?

Yeah, good point, that would probably mean that the order might not necessarily be stable.

> ... Is [PLINQ](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/introduction-to-plinq) an option for you?

Honestly, I did not really think of PLINQ in this context, and it's been a while since I used it, but I was under the impression that it does not work quite well with async/await, right?

**Comment by theodorzoulias** [comment]
@Sossenbinder I've posted [here](https://stackoverflow.com/questions/30907650/foreachasync-with-result/71129678#71129678 "ForEachAsync with Result") a `ForEachAsync` variant that collects the results in the original order of the `source`. Of course it would be nice if such a method was available in the standard .NET libraries, but most likely the `System.Threading.Tasks.Parallel` class is not the correct place to host this functionality. The `System.Linq` namespace seems more suitable, with an operator named `AsParallelAsync` (or similar) that would enable parallel operations with asynchronous delegates on enumerable sequences. I am assuming that Microsoft is not interested at going this way, because it would be a massive undertaking (like PLINQ, but harder), disproportional to the current demand for such a feature.

**Comment by Sossenbinder** [comment]
@theodorzoulias Yep, that pretty much looks similar to what I use over and over as well. I can absolutely understand why this might not be a good fit for the Parallel class, I think I also mentioned that I was unsure whether it would fit the existing signatures over there. Would be lovely to see something like this in another section though. I see your point for sure

**Comment by stephentoub** [comment]
> I can absolutely understand why this might not be a good fit for the Parallel class

Yeah, until/unless there's a huge clamoring for this, it'd be better left out.  Parallel.ForEach has existed for over a decade without such support and with few-to-no requests for such a feature in that interim; I don't think ForEachAsync is particularly different.
