### ISSUE TITLE
Blazor hosted app gets compile warnings of call unavailable in the browser but no warning of calls that may not be supported in a docker container

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#72513]
**Main problem:** `System.Net.NetworkInformation.UnixUnicastIPAddressInformation.IsDnsEligible` throws PlatformNotSupoprtedException on **Linux**, but it does not give build-time warning (via Platform analyzers).

_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-hosted-app-gets-compile-warnings-/10080222)._

---
[severity:It's more difficult to complete my work]
I am building a Blazor Hosted app. At compile time I get warnings of calls that are not supported in the browser eg 
_Sensor.cs(32,23,32,39): warning CA1416: This call site is reachable on all platforms. 'UdpClient' is unsupported on: 'browser'._
I get no warnings or errors in regards use of API calls at the server that will fail at runtime in a Linux (docker) container. eg
_fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.PlatformNotSupportedException: The information requested is unavailable on the current platform.
         at System.Net.NetworkInformation.UnixUnicastIPAddressInformation.get_IsDnsEligible()_
This is presumably a restriction of .Net on this linux platform. In an application to which Docker support has been added could this problem not be flagged at compile time?

---
#### Feedback Bot on 6/27/2022, 05:05 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by karelz** [comment]
The API was annotated in #51301 as part of .NET 6.0.

**Comment by karelz** [comment]
Triage: @rzikm will try it on Console app and/or on Blazor app (HelloWorld style) to see if it is a problem with 7.0.

**Comment by ManickaP** [comment]
The annotations are there:
https://source.dot.net/#System.Net.NetworkInformation/System/Net/NetworkInformation/UnixUnicastIPAddressInformation.cs,f99cbf4e8bd46426,references

**Comment by jkotas** [comment]
These annotations are on internal implementation detail. The unsupported platform analyzer does not look at internal implementation details. It looks at annotations that are in the reference assembly only: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.NetworkInformation/ref/System.Net.NetworkInformation.cs

**Comment by ViktorHofer** [comment]
We should check why ApiCompat doesn't flag these differences. cc @ericstj

**Comment by ericstj** [comment]
The annotations are on derived types instead of the base type.  The base type is missing annotations present on the derived types.  Ideally the base type should be the superset of the compatibility annotations of all derived types, or to look at it another way, the base type defines platforms the derived types must implement (and derived types are not permitted to have additional  annotations).

APICompat can't know the "meaning" of every attribute.  Here the meaning of the platform compatibility attributes defines the rules around how they should be used.  API  Compat could enforce this, but we might want to put such validation in an analyzer since it's less around the compatibility of changes to applying the attribute between versions and more around the semantics of applying the attribute in a single version.  @buyaa-n  @jeffhandley

**Comment by buyaa-n** [comment]
> but we might want to put such validation in an analyzer since it's less around the compatibility of changes to applying the attribute between versions and more around the semantics of applying the attribute in a single version.

We might consider adding that scenario in CA1418 ([Use valid platform string analyzer](https://github.com/dotnet/roslyn-analyzers/blob/main/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/UseValidPlatformString.cs)). For now it is only about valid platform name and version, the intention was to add other scenarios for usage correctness of the OSPlatform attributes

**Comment by antonfirsov** [comment]
Triage: we should annotate the API-s with `[UnsupportedOSPlatform]`. Not critical.
