### ISSUE TITLE
Error Starting any blazor wasm app in browser with .net 7 preview 5 

### ISSUE THREAD

**Issue by ahmed-salem-me** [dotnet/runtime#72523]
### Description

I get the following error when I try to start any blazor wasm app with .net v. 7.0.0-preview.5.22268.1
![image](https://user-images.githubusercontent.com/95217221/180007098-2b9ff320-5cf3-4a66-8fae-c8b8f071f213.png)

Unless I remove this from the launchSettings.json :
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",

### Reproduction Steps

Create a new blazor wasm project, choose .net 7

### Expected behavior

App should start fine in browser

### Actual behavior

App fail to start everytime even after a clean or rebuild

### Regression?

Yes it used to work, but happened randomly, not it seem to always happen

### Configuration

Windows 10
Visual Studio V. 17.2.5

### Other information

@radical

**Comment by thaystg** [comment]
@ahmed-salem-me have you tried this workaround?

https://github.com/dotnet/core/blob/main/release-notes/7.0/known-issues.md#unable-to-debug-a-blazor-webassembly-app

**Comment by lewing** [comment]
closing as a known issue, feel free to reopen if the workaround does not resolve the problem
