### ISSUE TITLE
Test failure: [error] The job running on agent NetCore1ESPool-Public 31 ran longer than the maximum time of 270 minutes

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#72531]
The Windows Arm64 seems time-out in [runtime-jit-experimental](https://runfo.azurewebsites.net/view/definition/793/) test. 

- [Pipeline](https://dev.azure.com/dnceng/public/_build/results?buildId=1886506&view=results) 

![image](https://user-images.githubusercontent.com/63486087/180031092-3d6a24e1-3f3d-4af7-992a-585dbf3d1155.png)

**Comment by JulieLeeMSFT** [comment]
cc @dotnet/jit-contrib.

**Comment by JulieLeeMSFT** [comment]
Another timeout:

- [Pipelines - Runs for runtime-jit-experimental (azure.com)](https://dev.azure.com/dnceng/public/_build?definitionId=793)
- https://dev.azure.com/dnceng/public/_build/results?buildId=1900613&view=results

```scala
Time out error: ##[error]The job running on agent NetCore1ESPool-Public 83 ran longer than the maximum time of 270 minutes. For more information, see https://go.microsoft.com/fwlink/?linkid=2077134
```

**Comment by jakobbotsch** [comment]
The timeouts are on win-arm64. According to first responders chat there was a lab outage for win-arm64 recently causing many machines to not accept work. I can see that normally these win-arm64 test runs take 2.5 hours, but in these cases they are timing out after 4.5 hours. So I think we can close this and if we see it again, we should talk to the Helix folks about the win-arm64 queue.
