### ISSUE TITLE
In Mono runtime, `Type.GetTypeCode` returns improper value for an enum nested in a generic class

### ISSUE THREAD

**Issue by mathieubourgeois** [dotnet/runtime#72543]
### Description

When using the Mono runtime (repro-ed on iOS, but from my tests I'm pretty sure it's true in the Mono runtime in general), calling `Type.GetTypeCode()` on the type of an enum nested in a generic class will return `TypeCode.Object` instead of `TypeCode.Int32` (or whatever integral backing type is actually used).

If testing with the Debug runtime, it will also trigger an assert when calling `Enum.TryParse(string, out T)` for the same enum, i.e. the one from `TryParseRareEnum` (https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Enum.cs#L890). It should not reach that function, but it does because `TypeCode.Object` is returned.

### Reproduction Steps

Run the following code on iOS (simulator provokes the problem, pretty sure other uses of Mono would provoke it but haven't tested all of them) :

```
using System;

namespace Program
{
	public class TestClass
	{
	}
	
	public class TestContainer<T>
	{
		T t;
		public enum TestEnum
		{
			A,
			B,
			C
		}
	}
	
	public class Program
	{
		public static void Main()
		{
			Console.WriteLine($"Enum TypeCode is {Type.GetTypeCode(typeof(TestContainer<TestClass>.TestEnum))}");
		}
	}
}
```

### Expected behavior

Writes `Enum TypeCode is Int32` (this is what happens on CoreClr windows as well, and what tracks with the official definition of `Type.GetTypeCode`

### Actual behavior

Writes `Enum TypeCode is Object`

### Regression?

Unsure, I never hit the issue on non-dotnet Mono, but I didn't test `Type.GetTypeCode` before (I hit the Enum.TryParse assert first, which led me to this issue, and on non-dotnet Mono, the parsing doesn't use that function).

### Known Workarounds

In theory, someone could check if the type is an enum and call `Enum.GetUnderlyingType` and call `Type.GetTypeCode` on it I guess? This would help for direct calls, but if there are calls in the runtime, then they can't be circumvented. For `Enum.TryParse`, however, other than the fact that we end up in the wrong function, the function still seems to work (as long as you don't have asserts enabled in your runtime)

### Configuration

- Windows 10, dotnet 6.0.302 (for working version), x64
- macOS Monterey 12.1, Xcode 13.4.1, dotnet 6.0.302, iOS Simulator (i.e. x64)

I also triggered the `Enum.TryParse` in a custom version of the Mono runtime, my gut feeling is that it happens in all usage of the Mono runtime in .Net.

### Other information

From my testing, it looks like the issue stems from `ves_icall_RuntimeTypeHandle_GetCorElementType` in icall.c which considers its type to be a `MONO_TYPE_GENERICINST`. Not sure if the type is in the wrong here or if the function should just have a special case for enums to look for the underlying type.

**Comment by mathieubourgeois** [comment]
I've just tried the following variation for `GetCorElementType` by searching for the underlying type before returning the type, and it works, at least on my end. `Type.GetTypeCode` return `Int32` and `Enum.TryParse` avoids the assert.

```
guint32
ves_icall_RuntimeTypeHandle_GetCorElementType (MonoReflectionTypeHandle ref_type, MonoError *error)
{
	MonoType *type = MONO_HANDLE_GETVAL (ref_type, type);

	// Otherwise, enums in generic classes don't work
	type = mono_type_get_underlying_type(type);

	if (type->byref)
		return MONO_TYPE_BYREF;
	else
		return (guint32)type->type;
}
```

I'm open to creating a PR for this if it actually is a proper fix, but I'm really not sure if it is since `GetCorElementType` isn't really documented (at least, as far as I can tell).

**Comment by marek-safar** [comment]
@lambdageek could you comment on the suggested fix?

**Comment by lambdageek** [comment]
> ves_icall_RuntimeTypeHandle_GetCorElementType

Proposed change LGTM. AFAICT CoreCLR ends up in `TypeDesc::GetInternalCorElementType` which has this comment:
```
    // This is the ELEMENT_TYPE* that would be used in the type sig for this type
    // For enums this is the uderlying type
    inline CorElementType GetInternalCorElementType() {
```

**Comment by mathieubourgeois** [comment]
> > ves_icall_RuntimeTypeHandle_GetCorElementType
> 
> Proposed change LGTM. AFAICT CoreCLR ends up in `TypeDesc::GetInternalCorElementType` which has this comment:
> 
> ```
>     // This is the ELEMENT_TYPE* that would be used in the type sig for this type
>     // For enums this is the uderlying type
>     inline CorElementType GetInternalCorElementType() {
> ```

Excellent! I'll try to add a test case for this and do a PR as soon as I am able
