### ISSUE TITLE
Bad test input in `UpgradeToRegexGeneratorAnalyzerTests`

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/runtime#72544]
### Description

https://github.com/dotnet/runtime/blob/671fe42d8a5eb90556d60238cfdf28c0753fdae1/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/UpgradeToRegexGeneratorAnalyzerTests.cs#L48

https://github.com/dotnet/runtime/blob/671fe42d8a5eb90556d60238cfdf28c0753fdae1/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/UpgradeToRegexGeneratorAnalyzerTests.cs#L59

None of the constructors has a "timeout" parameter. I believe the test wanted to refer to this constructor, but the parameter was misspelled. I'm not sure though if the lack of `options` parameter is an intentional error scenario to test.

```csharp
public Regex (string pattern, System.Text.RegularExpressions.RegexOptions options, TimeSpan matchTimeout);
```

@joperezr What was the intention here?

I discovered this while enabling validation of compiler diagnostics in tests.

**Comment by Youssef1313** [comment]
After determining the tests intention, https://github.com/Youssef1313/runtime/commit/37753ea2e647f494d4d6597b0668176a2f1e6004 could be cherry-picked to ensure we verify diagnostics for tests.

**Comment by joperezr** [comment]
thanks for catching the issue with the misspelling of the parameter, that was indeed not intended. As for the missing options, that was also not intended. It would be great to cherry-pick from your PR 😄
