### ISSUE TITLE
Developers stuck with .NET 5 need a fix for #43675 in .NET 5

### ISSUE THREAD

**Issue by jeffhuckins** [dotnet/runtime#72540]
### Description

The referenced bug was closed when, for some reason, nobody spoke up when asked if the fix should be added to .NET 5. Well, our company is currently stuck on .NET 5 and need the XmlSerializer to work for enums. It would be a huge hit to our development and release schedule to be required to migrate to .NET 6

### Reproduction Steps

Read issue #43675 here: [https://github.com/dotnet/runtime/issues/43675](url)

### Expected behavior

No crash in constructor of XmlSerializer

### Actual behavior

KeyNotFoundException thrown

### Regression?

Yes

### Known Workarounds

NONE!

### Configuration

.NET 5

**Comment by jeffhuckins** [comment]
area-Serialization

Regards,

Jeff Huckins
Senior Staff Software Engineer
Calibration Software Development
Desk: (503) 601-1503
Cell: (503) 317-8060

***@***.***
9100 SW Gemini Drive
Beaverton, Oregon 97008
www.formfactor.com<http://www.formfactor.com/>

**Comment by jkotas** [comment]
.NET 5 reached end of support on May 10, 2022.

**Comment by jeffhuckins** [comment]
I understand, but you guys left a major bug in it back in 2021 that projects can live with. It’s a show-stopper. No work-around. We have no way to move to .NET 6.

Regards,

Jeff Huckins
Senior Staff Software Engineer
Calibration Software Development
Desk: (503) 601-1503
Cell: (503) 317-8060

***@***.***
9100 SW Gemini Drive
Beaverton, Oregon 97008
www.formfactor.com<http://www.formfactor.com/>

**Comment by jeffhuckins** [comment]
I went ahead and migrated to .NET 6, so we’ll just take a minor hit to our release schedule.

Regards,

Jeff Huckins
Senior Staff Software Engineer
Calibration Software Development
Desk: (503) 601-1503
Cell: (503) 317-8060

***@***.***
9100 SW Gemini Drive
Beaverton, Oregon 97008
www.formfactor.com<http://www.formfactor.com/>
