### ISSUE TITLE
`string.StartsWith` with `OrdinalIgnoreCase` appears to become `Equals` after optimization

### ISSUE THREAD

**Issue by SeeminglyScience** [dotnet/runtime#72550]
### Description

When a method contains `string.StartsWith`, the instance is a constant, and `OrdinalIgnoreCase` is specificed, it works when `QuickJitted` but when `OptimizedTier1` hits it acts like `string.Equals`.

Possibly related to #66095

Also note I believe this is the cause of an issue we're hitting in PowerShell/PowerShell#17665

### Reproduction Steps

In a console app

```csharp
namespace App;

public static class Program
{
    public static void Main(string[] args)
    {
        for (int i = 0; i < 100; i++)
        {
            DoTheThing(args[0]);
        }

        Thread.Sleep(500);

        for (int i = 0; i < 100; i++)
        {
            DoTheThing(args[0]);
        }
    }

    public static void DoTheThing(string arg)
    {
        if ("Command".StartsWith(arg, StringComparison.OrdinalIgnoreCase))
        {
            Console.WriteLine("true");
            return;
        }

        Console.WriteLine("false");
    }
}
```

Then run

```powershell
app.exe command
app.exe c
```

### Expected behavior

Repeats `true` 400 times

### Actual behavior

Repeats `true` 300 times, and then `false` 100 times.

### Regression?

Yes, I cannot repro this in preview.2

### Configuration

> Which version of .NET is the code running on?

.NET 7.0.0-preview.6.22324.4

> What OS and version, and what distro if applicable?

Microsoft Windows 10.0.19044

> What is the architecture (x64, x86, ARM, ARM64)?

x64

> Do you know whether it is specific to that configuration?

I have not been able to test personally but it was reported to be Windows only in the linked PowerShell issue.

**Comment by stephentoub** [comment]
cc: @EgorBo

**Comment by EgorBo** [comment]
😢 a bug in the logic, for `StartsWith` is not commutative so while for `Equals` it doesn't matter which argument is a constant string, for `StartsWith` it has to be only op2. I thought I had a good coverage for all cases in https://github.com/dotnet/runtime/blob/main/src/tests/JIT/opt/Vectorization/UnrollEqualsStartsWIth_Tests.cs but apparently I forgot about this case. File file a PR in a moment.

**Comment by EgorBo** [comment]
@SeeminglyScience thank you so much for the bug-report, somewhere in P4/P5 we started to perform "unroll & SIMDify" operations for half-constant input for various string/span APIs (https://github.com/dotnet/runtime/pull/65288 + https://github.com/dotnet/runtime/pull/66095 + https://github.com/dotnet/runtime/pull/66095)
but apparently I completely forgot that StartsWith is not commutative like Equals.

**Comment by SeeminglyScience** [comment]
> @SeeminglyScience thank you so much for the bug-report, somewhere in P4/P5 we started to perform "unroll & SIMDify" operations for half-constant input for various string/span APIs (#65288 + #66095 + #66095) but apparently I completely forgot that StartsWith is not commutative like Equals.

Hey no problem, FWIW it was a fun bug to track down! I do wish I found the PR before [writing up a whole thing](https://gist.github.com/SeeminglyScience/ee8627b354d42f187be13c4716fd88bd)... but glad it was somewhat simple in the end 😁

**Comment by EgorBo** [comment]
> > @SeeminglyScience thank you so much for the bug-report, somewhere in P4/P5 we started to perform "unroll & SIMDify" operations for half-constant input for various string/span APIs (#65288 + #66095 + #66095) but apparently I completely forgot that StartsWith is not commutative like Equals.
> 
> Hey no problem, FWIW it was a fun bug to track down! I do wish I found the PR before [writing up a whole thing](https://gist.github.com/SeeminglyScience/ee8627b354d42f187be13c4716fd88bd)... but glad it was somewhat simple in the end 😁

I am really sorry that you had to waste a lot of time on it 😢 but with your help it didn't make it to the GA build 👍

**Comment by SeeminglyScience** [comment]
No worries, that's what previews are for! Glad I could help ❤️

**Comment by EgorBo** [comment]
@SeeminglyScience Do we need to backport the fix to the upcoming Preview7 or RC1 is fine? Presumably `"const".StartsWith(nonConst` is a rare pattern

cc @stephentoub

**Comment by stephentoub** [comment]
> Presumably "const".StartsWith(nonConst is a rare pattern

https://grep.app/search?q=%22%5C.StartsWith%5C%28%5B%5E%22%5D&regexp=true&filter[lang][0]=C%23

**Comment by SeeminglyScience** [comment]
It surfaces in PowerShell a pretty obscure way that likely won't be too problematic until it hits wide spread use. I think RC1 would be fine on our end
