### ISSUE TITLE
[API Proposal]: Add leaveOpen concept to PartitionedRateLimiter.TranslateKey

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/runtime#72551]
### Background and motivation

Originally proposed and approved in https://github.com/dotnet/runtime/issues/65400#issuecomment-1075473959, the `PartitionedRateLimiter<TResource>.TranslateKey(...)` method wraps and returns a new instance of `PartitionedRateLimiter`. Currently we are assuming no ownership of the wrapped limiter to be on the safe side. The proposal is to add a flag to give ownership to the wrapper so `Dispose` and `DisposeAsync` will cleanup the wrapped limiter.

A few examples of prior-art for this type of API:
https://github.com/dotnet/runtime/blob/dc2db86e368082bafc38b476e78d2d60f3638729/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.cs#L181
https://github.com/dotnet/runtime/blob/dc2db86e368082bafc38b476e78d2d60f3638729/src/libraries/System.Private.CoreLib/src/System/IO/StreamWriter.cs#L93
https://github.com/dotnet/runtime/blob/b12e288a143c2986f81aa7c025beac9f5a4c7c29/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/PipeReader.cs#L100

### API Proposal

```diff
namespace System.Threading.RateLimiting;

public abstract class PartitionedRateLimiter<TResource> : IAsyncDisposable, IDisposable
{
-    public PartitionedRateLimiter<TOuter> TranslateKey<TOuter>(Func<TOuter, TResource> keyAdapter);
+    public PartitionedRateLimiter<TOuter> TranslateKey<TOuter>(Func<TOuter, TResource> keyAdapter, bool leaveOpen = false);
}
```

### API Usage

```csharp
var limiter = PartitionedRateLimiter.Create<string, int>(resource =>
{
    if (resource == "1")
    {
        return RateLimitPartition.GetConcurrencyLimiter(1,
            _ => new ConcurrencyLimiterOptions(1, QueueProcessingOrder.NewestFirst, 1));
    }
    return RateLimitPartition.GetNoLimiter(2);
});

var translateLimiter = limiter.TranslateKey<int>(i => i.ToString(), leaveOpen: false);
translateLimiter.Acquire(1);

translateLimiter.Dispose();
```

### Alternative Designs

Leave as-is and require user to keep track of the inner limiter and call Dispose/DisposeAsync on that when done.

### Risks

If more options are added for `TranslateKey` then we'll end up with additional overloads. Like how `StreamWriter` and `SslStream` have a bunch of overloads.

I am unable to think of options we might want to add in the future though.

**Comment by terrajobst** [comment]
* Let's make the parameter explicit to ensure people understand the transfer of ownership
    - Let's also rename it to `WithTranslatedKey`

```diff
namespace System.Threading.RateLimiting;

public abstract class PartitionedRateLimiter<TResource> : IAsyncDisposable, IDisposable
{
-    public PartitionedRateLimiter<TOuter> TranslateKey<TOuter>(Func<TOuter, TResource> keyAdapter);
+    public PartitionedRateLimiter<TOuter> WithTranslatedKey<TOuter>(Func<TOuter, TResource> keyAdapter, bool leaveOpen);
}
```
