### ISSUE TITLE
System.Net.Mail in .net 6 is almost 5 times slower compared to .net 4.7.2

### ISSUE THREAD

**Issue by yogigrantz** [dotnet/runtime#72555]
### Description

For testing I created two console programs that sends out 100 emails using System.net.Mail. I put the exact code (except for the labeling) in two different solutions: .net 4.7.2 and .net 6. At the beginning and end, I logged the hour stamp. Here is the result in the log file:
For .net 6: 
13:54:42.99 Start (.Net 6) ---
13:54:50.34 End (.Net 6) --- 100 emails sent

For .net 4.7.2:
13:55:31.28 Start (.Net 4.7) ---
13:55:32.79 End (.Net 4.7) --- 100 emails sent

My dotnet --info:
 6.0.302 [C:\Program Files\dotnet\sdk]
  

### Configuration

.net 6.0.302 compared with .net 4.7.2
  

### Regression?

in .net 6: It takes 7.3 seconds to send 100 emails
in .net 4.7.2: It takes 1.5 seconds to send 100 emails
  

### Source code - .net 6

host, username, and password are not the real values here

```c#
            using System.Net.Mail;

            try
            {
                string dotnetVersion = ".net 6";
                string host = "hostname";
                string username = "username";
                string password = "password";
                int port = 25;
                bool ssl = false;
                using (StreamWriter sw = new StreamWriter(@"C:\Temp\Log.txt", true))
                {
                    sw.WriteLine($"{DateTime.Now.ToString("HH:mm:ss.ff")} Start ({dotnetVersion}) ---");
                       int i = 0;
                    using (SmtpClient smtp = new SmtpClient())
                    {
                        smtp.Port = port;
                        smtp.Host = host;
                        smtp.Credentials = new System.Net.NetworkCredential(username, password);
                        smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                        smtp.EnableSsl = ssl;

                        for (i = 0; i < 100; i++)
                        {
                            using (MailMessage mm = new MailMessage(username, $"EmailTester{i}@mailinator.com", $"This is a {dotnetVersion} performance test ", $"<h1>Performance Test Email </h1> {dotnetVersion} version. The time is now: {DateTime.Now.ToString("HH: mm:ss.ff")}. <br />Thank you for reading this"))
                            {
                                smtp.Send(mm);
                            }
                        }
                    }

                    sw.WriteLine($"{DateTime.Now.ToString("HH:mm:ss.ff")} End ({dotnetVersion}) --- {i} emails sent");

                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
```

### Analysis

Not sure where the problem is, the code is identical, the performance is quite different

**Comment by karelz** [comment]
Triage:
- For more reliable perf measurements, incl. across multiple .NET implementations, we highly recommend to use BenchmarkDotNet
- System.Net.Mail is in maintenance mode - the API is not modern, not fast, and overall we do not change it unless it is a critical bug. We recommend customers to use MailKit, or other modern and fast mail libraries.

Closing as Won't Fix.

**Comment by yogigrantz** [comment]
Hello Karel, thank you for clarifying, that was helpful.
I followed your advice to use MailKit. But it is even much slower than System.Net.Mail. It takes almost a minute for MailKit to send 100 emails, whereas for System.Net.Mail in .net 6 takes only 7 seconds. Here is my code for Mailkit

        using MailKit.Net.Smtp;
        using MailKit.Security;
        using MimeKit;
        using (ISmtpClient smtp = new SmtpClient())
        {
            smtp.Connect(host, port, SecureSocketOptions.StartTls);
            smtp.Authenticate(username, password);
            for (i = 0; i < 100; i++)
            {
                using (MimeMessage mm = new MimeMessage())
                {
                    mm.From.Add(MailboxAddress.Parse(username));
                    mm.To.Add(MailboxAddress.Parse($"EmailTester{i}@mailinator.com"));
                    mm.Subject = $"Email sent at {DateTime.Now.ToString("HH: mm:ss.ff")} ";
                    mm.Body = new TextPart($"<h1>Performance Test Email </h1> {dotnetVersion} version. The time is now: {DateTime.Now.ToString("HH: mm:ss.ff")}. <br />Thank you for reading this");
                    smtp.Send(mm);
                }
            }

            smtp.Disconnect(true);
        }
 

I made the subject line display the second and hundreth of a second so I can clearly see the time in between emails. It shows 0.6 second difference between emails

**Comment by danmoseley** [comment]
@yogigrantz  can you report this at https://github.com/jstedfast/MailKit and ask for guidance? Perhaps they have a suggestion or can fix a bug.

**Comment by yogigrantz** [comment]
Will do, thank you Dan!

**Comment by danmoseley** [comment]
@yogigrantz I hear you. We would like to know why it is slower, and would potentially consider a fix if you were to investigate and offer one. But the triage comment above means we do not plan to look at it ourselves anytime soon.

**Comment by yogigrantz** [comment]
@danmoseley  yes I completely understand, no I don't expect you to fix that. What I meant was, I'm hoping that maybe MailKit could improve their performance or at least give suggestion. I was just about to check System.net.Mail under the hood, but after reading the posts in StackOverflow: https://stackoverflow.com/questions/43517434/is-system-net-mail-smtpclient-obsolete-in-4-7#:~:text=that%20said%20System.-,Net.Mail.,and%20MimeKit%20is%20replacing%20it , I'm not sure if looking into it is a good idea

**Comment by ManickaP** [comment]
@yogigrantz is it possible that your SMTP server is throttling you?

I did a quick test, with only 9 mails since it won't let me send more in such a short time, and it took:
```
Total for 9 mails 00:00:00.4459677
```
So it'd take like 5 seconds for 100.

I tested it with MailKit.

**Comment by yogigrantz** [comment]
@Manicka : you may be right. This may be SMTP issue, but I have no way of knowing whether the SMTP is throttling me. One thing I know, is that initially I tested MailKit with ethereal SMTP (https://ethereal.email) . For 9 emails it took 7.75 seconds. Then I tried smtp.office365.com. This time for 9 emails it took 3.35 seconds. And then I tried our  old SMTP but I could not get it to work yet because it is not setup to accept authentication. Which SMTP server did you use that would send 9 emails in .446 seconds?

**Comment by ManickaP** [comment]
The one attached to my personal email.

**Comment by yogigrantz** [comment]
@ManickaP : Just to make sure we are comparing apple to apple, I ran 3 tests with the same SMTP and same destination, sending 9 emails to the same destination. 

If the SMTP is throttling me, then it would be throttling me in all 3 tests. My test result is as follows:

09:36:58.16 Start (.net 4.7.2 with System.net.Mail - port 25) ---
09:36:58.44 End (.net 4.7.2 with System.net.Mail - port 25) --- 9 emails sent. Elapse time: 0.2840162 seconds
09:37:59.49 Start (.net 6 with System.net.Mail - port 25) ---
09:38:00.36 End (.net 6 with System.net.Mail - port 25) --- 9 emails sent. Elapse time: 0.8662199 seconds
09:38:32.91 Start (.net 6 with MailKit 3.3.0 - port 25) ---
09:38:34.29 End (.net 6 with MailKit 3.3.0 - port 25) --- 9 emails sent. Elapse time: 1.3823187 seconds

So, between .net 4.7.2 and .net 6, the lapse time grew from 0.28 seconds to 0.87 seconds. Between .net 6 with System.Net.Mail and .net 6 with MailKit, the lapse time grew from 0.87 to 1.38 seconds .

All 3 tests include the time it takes to write the log file with StreamWriter, and the destination is a mailinator email address.

If you could send 9 emails in 0.45 seconds with MailKit, then you could probably send the same emails in 0.17 seconds with System.Net.Mail in .net 4.7.2. Unfortunately, both System.Net.Mail and .net 4 are getting old. And please don't get me wrong, I am not a proponent of older technology, in fact I a fan of, and am required to use bleeding edge technology at all times. That is the reason I am reporting this findings to you guys.
