### ISSUE TITLE
System.Security.Cryptography.Native.Android-static is braking JNI libs compiled with NativeAOT.

### ISSUE THREAD

**Issue by josephmoresena** [dotnet/runtime#72556]
The current implementation of System.Security.Cryptography.Native.Android requires the exportation of JNI_onLoad method in order to getting things ready: https://github.com/dotnet/runtime/blob/ddded2f18c6556d2c6039b513f40010390919c81/src/native/libs/System.Security.Cryptography.Native.Android/pal_jni.c#L647-L1045

That has problems when it is used in a NativeAOT project:
* Attempting to export an own JNI_onLoad method results in a compile error due to a method override when using System.Security.Cryptography.Native.Android.
* The JNI_onLoad method in System.Security.Cryptography.Native.Android will never exported because it isn't in the .exports file https://github.com/dotnet/corert/pull/7929.
* When we are building an executable binary we can't use JNI so we need use the invocation API in order to create an virtual machine instance and getting things ready.

The problem is more than the Android build, in fact our problem is our way of work with JNI.
We need a proper way to work around static libraries that require initialization with JNI initialization (not just this one), allow .NET code to define its own JNI initialization without any effect on the JNI initialization implementation in static libraries and, in case we are builing an executable, allow .NET code to provide/recive a virtual machine instance to/from those JNI initialization.

Exactly the same should be guaranteed for JNI_onUnload.

**Comment by MichalStrehovsky** [comment]
Did you try exploring building the runtime for Bionic instead of Android (https://github.com/dotnet/runtime/issues/63384#issuecomment-1154775856)? Bionic was recently added - it builds System.Security against libssl (same as other Linuxes) instead of using JNI. Might be a better alternative.

You'll need to provide your own libssl build since Android doesn't have one inbox. https://github.com/dotnet/runtime/pull/66147 mentions "As an errata, it is incumbent upon the end user to supply this in their OS environment (we download one ad-hoc for testing purposes, which was compiled by Google)" - so there's a way to get this without building it yourself.

**Comment by josephmoresena** [comment]
> Did you try exploring building the runtime for Bionic instead of Android ([#63384 (comment)](https://github.com/dotnet/runtime/issues/63384#issuecomment-1154775856))? Bionic was recently added - it builds System.Security against libssl (same as other Linuxes) instead of using JNI. Might be a better alternative.

No. I haven't done it yet! I'll be checking it out next week for sure. It would be the best way to proceed since we are not in the domain of JNI.

> You'll need to provide your own libssl build since Android doesn't have one inbox. #66147 mentions "As an errata, it is incumbent upon the end user to supply this in their OS environment (we download one ad-hoc for testing purposes, which was compiled by Google)" - so there's a way to get this without building it yourself.

At the moment and according to the review I did, these are the libraries that we haven't compiled for Android yet.
* System.Globalization.Native-Static
* System.Net.Security.Native-Static
* System.Security.Cryptography.Native.OpenSsl-Static

Compiling with bionic would all of them be possible? I really don't that a completely native solution is possible for Android but we have to try to make it that way as much as possible.

By the way, at my experiment applying a patch I have achieved to use the JNI_OnLoad definition from libSystem.Security.Cryptography.Native.Android and now I'm getting a controlled exception when trying to connect to a database using SQL Client (Related to globalization, I'm using Invariant mode).

**Comment by MichalStrehovsky** [comment]
We don't have plans for JNI interop right now. This library is not used when targeting Bionic instead.
