### ISSUE TITLE
Hang calling Environment.FailFast on multiple threads at the same time

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#72565]
`dotnet run -c Release` on  .NET 6.0

```csharp
class Test
{
    static void Main()
    {
        new Thread(GCWork).Start();

        for (int i = 0; i < 3; i++) new Thread(FailFastWork).Start();
        for (int i = 0; i < 10_000_000; i++) GC.KeepAlive(new object());

        flag = 1;

        for (;;) GC.KeepAlive(new object());
    }

    static volatile int flag;

    static void GCWork()
    {
        for (;;)
        {
            GC.Collect();
            Thread.Sleep(1);
        }
    }

    static void FailFastWork()
    {
        Recursion<int>(500);
    }

    static void Recursion<T>(int i)
    {
        if (i > 0) Recursion<T>(i - 1);
        while (flag == 0) { }
        Environment.FailFast("Crash");
    }
}

**Comment by danmoseley** [comment]
Is any test feasible here? ie., can the above just turn into a test that should no longer hang?

**Comment by jkotas** [comment]
The repro that I have created was manually tweaked to repro the problem in .NET 6. It does not repro the problem in .NET 7 due to the timing and runtime implementation details changing in .NET 7.

We have two tests exercising the paralel crash already: https://github.com/dotnet/runtime/tree/main/src/tests/baseservices/exceptions/simple

And we have two issues opened on the intermittent failures (including timeouts/hangs) hit by the existing tests: https://github.com/dotnet/runtime/issues/56950 https://github.com/dotnet/runtime/issues/57621 . I think that it is pretty good chance that some of the intermittent failures tracked by these two issues are dups of this one.
