### ISSUE TITLE
Long running test: ReadAsync_CancelPendingTask_ThrowsCancellationException and ReadAsync_CancelPendingValueTask_ThrowsCancellationException

### ISSUE THREAD

**Issue by tlakollo** [dotnet/runtime#72586]
Long running tests:
- **CancelPendingTask** - `ReadAsync_CancelPendingTask_ThrowsCancellationException` (disabled in PR #72596 on 7/21)
    - `System.Net.Http.Functional.Tests.Http1CloseResponseStreamConformanceTests.ReadAsync_CancelPendingTask_ThrowsCancellationException` - Http1**Close**ResponseStreamConformanceTests
    - `System.Net.Http.Functional.Tests.Http1RawResponseStreamConformanceTests.ReadAsync_CancelPendingTask_ThrowsCancellationException` - Http1**Raw**ResponseStreamConformanceTests
- **CancelPendingValueTask** - `ReadAsync_CancelPendingValueTask_ThrowsCancellationException` (disabled in PR #72854 on 7/27)
    - `System.Net.Http.Functional.Tests.Http1RawResponseStreamConformanceTests.ReadAsync_CancelPendingValueTask_ThrowsCancellationException` - Http1**Raw**ResponseStreamConformanceTests
    - `System.Net.Http.Functional.Tests.Http1CloseResponseStreamConformanceTests.ReadAsync_CancelPendingValueTask_ThrowsCancellationException` - Http1**Close**ResponseStreamConformanceTests

Regression on **7/20**

Failures 6/30-8/5:
Date | Runs
-- | --
8/5 | 1x PR occurrence - likely older source code
8/4 | 1x PR occurrence - likely older source code
8/3 | 1x PR occurrence - likely older source code
7/27 | 24x (1x in Official runs)
7/26 | 29x (2x in Official runs)
7/25 | 12x (2x in Official runs)
7/24 | 8x (3x in Official runs)
7/23 | 5x (1x in Official runs)
7/22 | 20x (0x in Official runs)
7/21 | 61x (5x in Official runs)
7/20 | 35x (7x in Official runs)

Given the high frequency, we should disable the test ASAP.

```kusto
let timeouts = (includePR : bool) {
cluster('engsrvprod.kusto.windows.net').database('engineeringdata').WorkItems
| where Status == "Timeout"
| where FriendlyName startswith "System.Net.Http.Functional.Tests"
//| where Finished > datetime('2021-09-07')
| distinct JobId, WorkItemId, Name, FriendlyName, ConsoleUri
| join kind=inner (cluster('engsrvprod.kusto.windows.net').database('engineeringdata').Jobs
    | where ((Branch == 'refs/heads/main') or (Branch == 'refs/heads/master') or (includePR and (Source startswith "pr/")) or (Branch startswith 'refs/heads/release/6.0'))
    | where Type startswith "test/functional/cli/"
        and not(Properties contains "runtime-staging")
    | summarize arg_max(Finished, Properties, Type, Branch, Source, Started, QueueName) by JobId
| project-rename JobType = Type) on JobId
| order by Finished desc
};
timeouts(true);
```

### Original report

Couldn't add runfo information since the work item has the same name as previously fixed issues. But this timeout behavior has occurred in the following rolling build runs:
https://dev.azure.com/dnceng/public/_build/results?buildId=1893373&view=results
https://dev.azure.com/dnceng/public/_build/results?buildId=1893617&view=results
https://dev.azure.com/dnceng/public/_build/results?buildId=1893157&view=results
https://dev.azure.com/dnceng/public/_build/results?buildId=1893763&view=results

The timeout occurs when executing the long-running test `System.Net.Http.Functional.Tests.Http1RawResponseStreamConformanceTests.ReadAsync_CancelPendingTask_ThrowsCancellationException`
These timeout are occurring on both runtime and runtime-extra-platforms

Related to #72209

```json
{
  "ErrorMessage": "[Long Running Test] 'System.Net.Http.Functional.Tests.Http1RawResponseStreamConformanceTests.ReadAsync_CancelPending",
  "BuildRetry": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[64914](https://dev.azure.com/dnceng-public/public/_build/results?buildId=64914)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=64914&view=ms.vss-test-web.build-test-results-tab&runId=1320870&resultId=199633)|dotnet/runtime#77169|
|[64782](https://dev.azure.com/dnceng-public/public/_build/results?buildId=64782)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=64782&view=ms.vss-test-web.build-test-results-tab&runId=1317908&resultId=199632)|dotnet/runtime#77487|
|[64481](https://dev.azure.com/dnceng-public/public/_build/results?buildId=64481)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=64481&view=ms.vss-test-web.build-test-results-tab&runId=1317492&resultId=199637)|dotnet/runtime#76859|
|[64009](https://dev.azure.com/dnceng-public/public/_build/results?buildId=64009)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=64009&view=ms.vss-test-web.build-test-results-tab&runId=1303626&resultId=199631)|dotnet/runtime#77449|
|[63786](https://dev.azure.com/dnceng-public/public/_build/results?buildId=63786)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=63786&view=ms.vss-test-web.build-test-results-tab&runId=1298934&resultId=199627)|dotnet/runtime#77386|
|[63754](https://dev.azure.com/dnceng-public/public/_build/results?buildId=63754)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=63754&view=ms.vss-test-web.build-test-results-tab&runId=1298338&resultId=199631)|dotnet/runtime#77261|
|[62760](https://dev.azure.com/dnceng-public/public/_build/results?buildId=62760)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=62760&view=ms.vss-test-web.build-test-results-tab&runId=1282016&resultId=199563)|dotnet/runtime#77398|
|[62577](https://dev.azure.com/dnceng-public/public/_build/results?buildId=62577)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=62577&view=ms.vss-test-web.build-test-results-tab&runId=1280384&resultId=199563)|dotnet/runtime#74820|
|[62186](https://dev.azure.com/dnceng-public/public/_build/results?buildId=62186)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=62186&view=ms.vss-test-web.build-test-results-tab&runId=1273038&resultId=199559)||
|[61912](https://dev.azure.com/dnceng-public/public/_build/results?buildId=61912)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=61912&view=ms.vss-test-web.build-test-results-tab&runId=1267506&resultId=199563)|dotnet/runtime#77398|
|[61472](https://dev.azure.com/dnceng-public/public/_build/results?buildId=61472)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=61472&view=ms.vss-test-web.build-test-results-tab&runId=1261630&resultId=199559)|dotnet/runtime#77400|
|[60736](https://dev.azure.com/dnceng-public/public/_build/results?buildId=60736)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=60736&view=ms.vss-test-web.build-test-results-tab&runId=1245180&resultId=199562)|dotnet/runtime#77245|
|[60520](https://dev.azure.com/dnceng-public/public/_build/results?buildId=60520)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=60520&view=ms.vss-test-web.build-test-results-tab&runId=1240656&resultId=199558)||
|[60215](https://dev.azure.com/dnceng-public/public/_build/results?buildId=60215)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=60215&view=ms.vss-test-web.build-test-results-tab&runId=1234054&resultId=199563)|dotnet/runtime#77336|
|[59963](https://dev.azure.com/dnceng-public/public/_build/results?buildId=59963)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=59963&view=ms.vss-test-web.build-test-results-tab&runId=1229414&resultId=199563)|dotnet/runtime#77336|
|[59761](https://dev.azure.com/dnceng-public/public/_build/results?buildId=59761)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=59761&view=ms.vss-test-web.build-test-results-tab&runId=1226586&resultId=199562)|dotnet/runtime#77196|
|[59151](https://dev.azure.com/dnceng-public/public/_build/results?buildId=59151)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=59151&view=ms.vss-test-web.build-test-results-tab&runId=1211890&resultId=199825)|dotnet/runtime#77293|
|[59055](https://dev.azure.com/dnceng-public/public/_build/results?buildId=59055)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=59055&view=ms.vss-test-web.build-test-results-tab&runId=1208916&resultId=199560)|dotnet/runtime#77196|
|[58799](https://dev.azure.com/dnceng-public/public/_build/results?buildId=58799)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=58799&view=ms.vss-test-web.build-test-results-tab&runId=1205072&resultId=199560)|dotnet/runtime#74820|
|[58224](https://dev.azure.com/dnceng-public/public/_build/results?buildId=58224)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=58224&view=ms.vss-test-web.build-test-results-tab&runId=1195388&resultId=199557)|dotnet/runtime#72717|
|[57227](https://dev.azure.com/dnceng-public/public/_build/results?buildId=57227)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=57227&view=ms.vss-test-web.build-test-results-tab&runId=1174172&resultId=199932)|dotnet/runtime#77219|
|[57205](https://dev.azure.com/dnceng-public/public/_build/results?buildId=57205)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=57205&view=ms.vss-test-web.build-test-results-tab&runId=1173910&resultId=195003)|dotnet/runtime#77220|
|[56479](https://dev.azure.com/dnceng-public/public/_build/results?buildId=56479)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=56479&view=ms.vss-test-web.build-test-results-tab&runId=1157826&resultId=199544)|dotnet/runtime#77149|
|[56287](https://dev.azure.com/dnceng-public/public/_build/results?buildId=56287)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=56287&view=ms.vss-test-web.build-test-results-tab&runId=1154884&resultId=199544)|dotnet/runtime#77052|
|[55730](https://dev.azure.com/dnceng-public/public/_build/results?buildId=55730)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=55730&view=ms.vss-test-web.build-test-results-tab&runId=1141264&resultId=199540)||
|[55653](https://dev.azure.com/dnceng-public/public/_build/results?buildId=55653)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=55653&view=ms.vss-test-web.build-test-results-tab&runId=1138780&resultId=199544)|dotnet/runtime#77107|
|[55580](https://dev.azure.com/dnceng-public/public/_build/results?buildId=55580)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=55580&view=ms.vss-test-web.build-test-results-tab&runId=1137460&resultId=202312)|dotnet/runtime#77127|
|[55028](https://dev.azure.com/dnceng-public/public/_build/results?buildId=55028)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=55028&view=ms.vss-test-web.build-test-results-tab&runId=1129830&resultId=199544)|dotnet/runtime#76942|
|[54938](https://dev.azure.com/dnceng-public/public/_build/results?buildId=54938)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=54938&view=ms.vss-test-web.build-test-results-tab&runId=1128108&resultId=199544)|dotnet/runtime#62863|
|[54792](https://dev.azure.com/dnceng-public/public/_build/results?buildId=54792)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=54792&view=ms.vss-test-web.build-test-results-tab&runId=1124700&resultId=199544)|dotnet/runtime#77116|
|[54391](https://dev.azure.com/dnceng-public/public/_build/results?buildId=54391)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=54391&view=ms.vss-test-web.build-test-results-tab&runId=1113802&resultId=199543)|dotnet/runtime#76361|
|[54104](https://dev.azure.com/dnceng-public/public/_build/results?buildId=54104)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=54104&view=ms.vss-test-web.build-test-results-tab&runId=1106600&resultId=199543)|dotnet/runtime#76361|
|[53859](https://dev.azure.com/dnceng-public/public/_build/results?buildId=53859)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=53859&view=ms.vss-test-web.build-test-results-tab&runId=1102390&resultId=199542)|dotnet/runtime#77088|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|3|18|33|

**Comment by karelz** [comment]
Triage: regression introduced on 7/20. High frequency, we should disable it ASAP.

**Comment by karelz** [comment]
@stephentoub I asked @rzikm to disable the test. Do you plan to do more (curious about your self-assignment).

**Comment by stephentoub** [comment]
I changed this test yesterday.

**Comment by stephentoub** [comment]
I'm having trouble reproing locally.  The changes I made yesterday were:

- Updating the test to be a theory and passing in both 0 and 100 (whereas previously it effectively only did the equivalent of 0)
https://github.com/dotnet/runtime/blob/0a7d601180256e1edd83631c0a42fd9128929a22/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs#L1678-L1679

- Changing a call to Cancel() to instead be to CancelAfter(delay) using those 0 or 100 values
https://github.com/dotnet/runtime/blob/0a7d601180256e1edd83631c0a42fd9128929a22/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs#L542

Re-reviewing, I think the tests are valid.  Most likely there's some race condition somewhere in the implementation of either SocketsHttpHandler or the test stream it's using that causes the waiting for cancellation in these tests to hang.  But it's hard to say for sure without a repro.

I've unassigned myself.

**Comment by CarnaViire** [comment]
`System.Net.Http.Functional.Tests.Http1CloseResponseStreamConformanceTests.ReadAsync_CancelPendingValueTask_ThrowsCancellationException` disabled in #72854

**Comment by stephentoub** [comment]
The issue here stems from HttpConnection not passing the CancellationToken down into the underlying Stream.ReadAsync operations and instead registering with the token to Dispose of the stream if cancellation is requested.  That causes a problem for this specific test because the test is simply issuing a read (with no writes) and waiting for a cancellation request.  And while it sounds like the issue there has to do with the token not canceling the read, it's actually that the token is the only thing keeping alive all of the state associated with the test.  By not passing the token in, everything becomes available for collection because the timer that would be rooting the whole operation doesn't get handed a reference to the leaf async state machine.

**Comment by wfurt** [comment]
I was running with change @stephentoub suggested as try and the issue disappears
```
+++ b/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs
@@ -536,6 +536,7 @@ protected async Task ValidateCancelableReadAsyncTask_AfterInvocation_ThrowsCance
             }

             var cts = new CancellationTokenSource();
+            cts.Token.Register(_ => { }, stream);

             Task<int> t = stream.ReadAsync(new byte[1], 0, 1, cts.Token);
```

While this is test change, we should still keep this issue open for product fix. Since this is now understood and it seems like it is very corner case specific to not using the stream after cancelation and using special in-memory stream, I'm going to move it to future (and leave the tests disabled for now)

**Comment by karelz** [comment]
@wfurt can you please clarify what kind of product change is needed?
Is it "just": `HttpConnection` should pass `CancellationToken` to `Stream.ReadAsync` operations?

**Comment by wfurt** [comment]
yes @karelz. HttpConnection use token registration to dispose underlying stream on cancelation. However, because we don't pass it into the stream, it is not root and eligible for collection in this particular test. When the finalizer runs, we skip the cleanup logic in Dispose and the task hangs. 
There may be perf penalty or other consequences for changing the cancelation so we should approach it carefully.

**Comment by MihaZupan** [comment]
@stephentoub isn't the issue more so that when we register for cancellation on `HttpConnection`, [we do so using a weak reference](https://github.com/dotnet/runtime/blob/916f1ad5b391764e964b271f80b915869e1afed0/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L902-L912)?
If we had passed a strong ref to the connection instead, the CTS would be rooting the connection (and therefore also the stream).

I am not sure I understand this comment given that we always control the registrations ourselves internally:
https://github.com/dotnet/runtime/blob/916f1ad5b391764e964b271f80b915869e1afed0/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L902-L903

**Comment by jkotas** [comment]
Hit in #77088

**Comment by stephentoub** [comment]
> I am not sure I understand this comment given that we always control the registrations ourselves internally:

If memory serves, the concern was that we're awaiting on the Read/WriteAsync operations on the underlying stream, and if those operations didn't end up rooting their continuations, the connection object could get collected, but storing a strong reference to it into the token would thwart that.  Basically exactly what this test is showing is a possibility.

We could decide we no longer care about that, of course.
