### ISSUE TITLE
Make public surface area of different CoreLibs consistent

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#72594]
In https://github.com/dotnet/runtime/pull/72143 we're adding a reference assembly for System.Private.CoreLib but right now the three different implementations (mono, coreclr and nativeaot) don't have consistent public API.

**Comment by ericstj** [comment]
I wonder how much of a goal it is to make them all exactly consistent, or just all support an intersection of API?  cc @jkotas @stephentoub @ViktorHofer

**Comment by jkotas** [comment]
Intersection is good enough. I do not think they need to be exactly consistent. There are good reasons for runtime-specific public surface, one example are runtime-specific hosting APIs.

**Comment by ericstj** [comment]
In that case I'm not sure what this would be tracking since I would expect that to be achieved by creating the contract and committing any baselines.

**Comment by ericstj** [comment]
@akoeplinger can you clarify what you think should happen, or close this if you agree with what's said here?

**Comment by agocke** [comment]
I think this is mostly done
