### ISSUE TITLE
.NET not properly shut down when using a mixed-mode assembly in a native process

### ISSUE THREAD

**Issue by IRebo** [dotnet/runtime#72610]
Im trying to migrate a big native application which uses mixed-mode libraries. After the migration to .net6 im running into an issue that when closing the process the C++ global objects are not properly destroyed.

The main .exe is an older MFC native executable which loads and uses mixed-mode dlls.

In .net framework when process if ending it normally calls CorExitProcess which causes the app-domain to unload and all the mixed-mode modules get uninitialized which includes destroying any static/global objects in C++ mixed-mode library.

In .net6 i see that the module subscribes to the domain unload but the event never occurs.

Is this intentional behaviour for .net6 ? Is there some way I can unload the domain from native code when the process is finishing to simulate the old behaviour ?

**Comment by AaronRobinsonMSFT** [comment]
> In .net6 i see that the module subscribes to the domain unload but the event never occurs.

Correct, the unload event is no longer fired. I believe this was done a long time ago in .NET Core.

> Is this intentional behaviour for .net6 ?

Yes.

> Is there some way I can unload the domain from native code when the process is finishing to simulate the old behaviour ?

The concept of multiple AppDomains is gone from .NET Core. There is now only one and that is a shell of what it meant in .NET Framework. Attempting to unload it will cause an exception stating it is not supported. The unloadability concept was moved to the [`AssemblyLoadContext`](https://docs.microsoft.com/dotnet/api/system.runtime.loader.assemblyloadcontext) - which is unloadable. As far as getting the same behavior, I am not sure it is possible automatically using C++ clean-up semantics. Is it possible to clean them up manually?

/cc @jkotas

**Comment by IRebo** [comment]
i should probably note that the unloading works just fine if the main executable is a C# managed one. When closing the app that loaded the mixed-mode library i get everything cleaned up properly :
>	MFCLibrary1.dll!<CrtImplementationDetails>::ModuleUninitializer::SingletonDomainUnload(System::Object^ source, System::EventArgs^ arguments) Line 275	C++
 	System.Private.CoreLib.dll!System.AppContext.OnProcessExit() Line 84	C#
 	[Native to Managed Transition]	
 	kernel32.dll!BaseThreadInitThunk()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown

**Comment by AaronRobinsonMSFT** [comment]
> Only if my main exe is a native app and .NET gets loaded with ijwhost i get the issue and the globals are not properly cleaned up

That is because runtime clean-up is being done independent of process shutdown or rather it needs to be. When the process is managed by the runtime clean-up is well-defined.

**Comment by AaronRobinsonMSFT** [comment]
Cleaning these resources up manually is the recommended solution for all C++/CLI binaries that are used to activate the runtime.
