### ISSUE TITLE
MarshallingAttributeAnalyzers throws InvalidOperationException

### ISSUE THREAD

**Issue by sbomer** [dotnet/runtime#72622]
### Description

NativeMarshallingAttributeAnalyzer and CustomMarshallerAttributeAnalyzer are throwing exceptions when building the runtime repo.

### Reproduction Steps

Set `dotnet_diagnostic.AD0001.severity = error` in `eng/CodeAnalysis.src.globalconfig`, and run `build.cmd`

### Expected behavior

No errors

### Actual behavior

I get lots of errors like the following:

```
CSC : error AD0001: Analyzer 'Microsoft.Interop.Analyzers.CustomMarshallerAttributeAnalyzer' threw an exception of type 'System.InvalidOperationException' with me 
ssage 'Sequence contains no elements'. [C:\Users\svbomer\src\runtime\src\coreclr\System.Private.CoreLib\System.Private.CoreLib.csproj]
```
```
CSC : error AD0001: Analyzer 'Microsoft.Interop.Analyzers.NativeMarshallingAttributeAnalyzer' threw an exception of type 'System.InvalidOperationException' with m 
essage 'Sequence contains no elements'. [C:\Users\svbomer\src\runtime\src\coreclr\System.Private.CoreLib\System.Private.CoreLib.csproj]
```
```
CSC : error AD0001: Analyzer 'Microsoft.Interop.Analyzers.CustomMarshallerAttributeAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.ArrayTypeSymbol' to type 'Microsoft.CodeAnalysis.INamedTypeSymbol'.'. [C:\Users\svbomer\src\runtime\src\coreclr\nativeaot\System.Private.CoreLib\src\System.Private.CoreLib.csproj]
```

@jkoritzinsky

**Comment by jkoritzinsky** [comment]
This will be fixed by https://github.com/dotnet/runtime/pull/72620

**Comment by jkoritzinsky** [comment]
:( Why did I decide to try to be a kinder citizen in the VS ecosystem and work off of syntax instead of symbols until I can use operations???

I'll take a look

**Comment by jkoritzinsky** [comment]
Also I didn't realize we had AD0001 disabled locally. That will make this much easier to debug

**Comment by jkoritzinsky** [comment]
Actually, this looks like a different bug. I'll include this one in my PR that adds more support for other things to the analyzer, as I'm about to put out the PR for it and the work would conflict.
