### ISSUE TITLE
[API Proposal]: `ImmutableArray<T>.Builder.ToImmutableAndClear()`

### ISSUE THREAD

**Issue by 333fred** [dotnet/runtime#72625]
### Background and motivation

In basically every project I use `ImmutableArray` in, I end up creating an extension for `ToImmutableAndClear` on the builder type, which takes advantage of `MoveToImmutable()` if the current builder has right size, and otherwise falls back to `ToImmutable()/Clear()` if not. I would really love it if we added this to the BCL itself.

### API Proposal

```csharp
namespace System.Collections.Immutable;

public struct ImmutableArray<T>
{
    public class Builder
    {
        public ImmutableArray<T> ToImmutableAndClear()
        {
            if (Capacity == Count) return MoveToImmutable();
            else
            {
                var result = ToImmutable();
                Clear();
                return result;
            }
       }
    }
}
```

### API Usage

```csharp
var builder = ImmutableArray.CreateBuilder<string>(/* max possible values */ 42);

foreach (var x in thingGettingMapped)
{
    if (x.Frob) builder.Add(x);
}

return builder.ToImmutableAndClear();
```

**Comment by Sergio0694** [comment]
I also use something like this quite often in my generators and would very much welcome this API 🙂

Nit: the proposal says `ToImmutableAndClear` but the example uses `ToImmutableAndFree`, old snippet?

**Comment by 333fred** [comment]
> Nit: the proposal says ToImmutableAndClear but the example uses ToImmutableAndFree, old snippet?

No, force of habit. Roslyn also pools builders.

**Comment by eiriktsarpalis** [comment]
Sounds useful enough. If we do add such a method, we might want to explicitly document that any perf benefits are predicated on `Capacity == Count`.

**Comment by terrajobst** [comment]
The challenge is that `MoveToImmutable()` results in `Capacity` becoming `0`, while `ToImmutable(); Clear();` would preserve the capacity. This can result in cases where we need go through various resize cycles, making the `Capacity == Count` potentially more expensive.

```C#
namespace System.Collections.Immutable;

public partial struct ImmutableArray<T>
{
    public partial class Builder
    {
        public ImmutableArray<T> ToImmutableAndClear();
    }
}
```

**Comment by bartonjs** [comment]
* ToImmutableAndClear, as proposed, has a problem where when Capacity==Count Capacity changes to 0, and otherwise it remains.
* We instead think the "do the cheapest thing possible" would be DrainToImmutable, always making Capacity 0 as a result of being called.
  * We debated many verbs (Drain, Extract, Empty) and prefix vs post-fix, but prefix matched the existing MoveToImmutable vs ToImmutable choice.

```C#
namespace System.Collections.Immutable;

public struct ImmutableArray<T>
{
    public partial class Builder
    {
        public ImmutableArray<T> DrainToImmutable();
    }
}
```
