### ISSUE TITLE
[mono][wasi] Add a CI lane for a new wasi RID

### ISSUE THREAD

**Issue by thaystg** [dotnet/runtime#72641]
As discussed with @radical offline :)

**Comment by pavelsavara** [comment]
We already have build step for WASI here 
https://github.com/dotnet/runtime/blob/9a138bf5cb4a9055e4e0370a3eb3883514555fcd/eng/pipelines/common/templates/wasm-library-tests.yml#L77

But I think we need new RID and separate CI lane.
