### ISSUE TITLE
WebAssembly Blazor Breakpoint stopping after it is removed.

### ISSUE THREAD

**Issue by qsdfplkj** [dotnet/runtime#72663]
### Description

When I try to debug my blazor application it keeps breaking at breakpoints after I remove them. (Within the same debug session. After I restart my application it works again.)

Exactly this issue which is closed and resolved 2 years ago: https://github.com/dotnet/runtime/pull/41479

### Reproduction Steps

Put a breakpoint in some razor file hit it. Remove the breakpoint continue running and the breakpoint is being hit again and again.

### Expected behavior

After removing the breakpoint it should not hit the breakpoint again.

### Actual behavior

It keeps breaking even though the breakpoint is removed/

### Known Workarounds

Restart the application :(

**Comment by radical** [comment]
What IDE are you using for this? And what version of dotnet?

**Comment by qsdfplkj** [comment]
Vs 2022 up-to-date 17.2.6 .net 6.  And update all relevant nugget packages.  I cannot reproduce it in a new application which is really odd. Maybe i should Do a clean checkout . Or delete the vs folder.

**Comment by thaystg** [comment]
Can you attach this log?
C:\Users\[USER_NAME]\AppData\Local\Temp\visualstudio-js-debugger.txt

**Comment by qsdfplkj** [comment]
I want to keep the logs private as they seem to contain personal information are you looking for anything particular? After looking myself a bit in the log I think it has to do with a secondary session after I log in (through our internal authentication portal and get directed back) the issue becomes present as the redirect loads the whole page again. Pressing another Ctrl+F5 will reload everything again and the issue disappears.

I cannot reproduce it in the default blazor project (cmdline: dotnet new  blazorwithidentity). Where I opened another tab to simulate another session but then the enabling and disabling of the breakpoints does work correct.

**Comment by lewing** [comment]
we need a way to reproduce this problem
