### ISSUE TITLE
[QUIC] Surface transport error code in QuicException

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#72666]
In case of `SHUTDOWN_INITIATED_BY_TRANSPORT` we now get transport level error code, but we don't use it.

We also get it in `SHUTDOWN_COMPLETE.ConnectionShutdown` case where we would throw the same exception as in `SHUTDOWN_INITIATED_BY_TRANSPORT` in ideal case.

There might still be necessity to expand msquic data to avoid holding stream -> connection link to solve this properly.

https://www.rfc-editor.org/rfc/rfc9000.html#name-transport-error-codes

**Comment by karelz** [comment]
@wfurt shouldn't this be resolved by your changes?

**Comment by wfurt** [comment]
fixed by  #88550 (community contribution)
