### ISSUE TITLE
Use custom GC PAL for all GC build flavors

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#72684]
The standalone GC is using custom PAL on Unix: https://github.com/dotnet/runtime/blob/main/src/coreclr/gc/unix/gcenv.unix.cpp

The built-in GC is using PAL from https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/gcenv.os.cpp. This PAL runs on top Win32 emulated APIs that come with extra overhead (extra tracking structures and extra locks). We have observed cases where this overhead is fairly significant.

We should switch the default built-in GC to use the custom PAL to eliminate the overhead of Win32 API emulation on Unix.

**Comment by Maoni0** [comment]
note that this extra overhead is contributing to the extra 64mb committed/working set on linux for regions.

**Comment by jkotas** [comment]
This is fixed on Unix. There is still work left to do to switch to the standalone PAL layer on Windows and delete all duplicated code.
