### ISSUE TITLE
X500DistinguishedName object with ForceUTF8Encoding flag produces different ASN.1 encoding on different platforms

### ISSUE THREAD

**Issue by darjanbogdan** [dotnet/runtime#72691]
### Description

`X500DistinguishedName` object created using `X500DistinguishedNameFlags.ForceUTF8Encoding` flag produces inconsistent ASN.1 encoded data bytes that represent it, when running on different platforms, Windows or Linux.

Given the following example:
```csharp
X500DistinguishedName subjectNameUtf8 = new($"CN=subject", X500DistinguishedNameFlags.ForceUTF8Encoding);
Console.WriteLine($"{Convert.ToHexString(subjectNameUtf8.RawData)}");
```
On Windows it will output the following hex representation:
30 12 31 10 30 0E 06 03 55 04 03 **0C** 07 73 75 62 6A 65 63 74

On Linux it produces following:
30 12 31 10 30 0E 06 03 55 04 03 **13** 07 73 75 62 6A 65 63 74

However, that is the same output which Windows produces when `ForceUTF8Encoding` flag isn't specified in the first place.

So, it looks to me that underlying platform specific implementations differ, or Linux implementation doesn't take flag into account. 

For Windows platform, distinguished name encoding is implemented via [X500DistinguishedNameEncode](https://github.com/dotnet/runtime/blob/c12bea880a/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/X509Pal.Windows.X500DistinguishedName.cs#L43) method, using native OS implementation. It takes flag into account in [MapNameToStrFlag](https://github.com/dotnet/runtime/blob/c12bea880a/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/X509Pal.Windows.X500DistinguishedName.cs#L129) method.

On the other hand, for Linux platform (if I'm not mistaken), [OpenSslX509Encoder.X500DistinguishedNameEncode](https://github.com/dotnet/runtime/blob/c12bea880a/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/OpenSslX509Encoder.cs#L50) method is used, that is relying on `X500NameEncoder` implementation. That implementation doesn't seem to take into account `ForceUTF8Encoding` flag.

Is there any other explanation for such discrepancy?

### Reproduction Steps

Compile and run this code on Windows and Linux platform.

```csharp
X500DistinguishedName subjectNameUtf8 = new($"CN=subject", X500DistinguishedNameFlags.ForceUTF8Encoding);
Console.WriteLine($"{Convert.ToHexString(subjectNameUtf8.RawData)}");
```

### Expected behavior

Expecting the same output on both platforms 30 12 31 10 30 0E 06 03 55 04 03 **0C** 07 73 75 62 6A 65 63 74

### Actual behavior

Linux produces 30 12 31 10 30 0E 06 03 55 04 03 **13** 07 73 75 62 6A 65 63 74 output for `X500DistinguishedName` object with `ForceUTF8Encoding`

**Comment by vcsjones** [comment]
Looks like we ignore the ForceUTF8Encoding flag here, and always try encoding as a `PrintableString` first:

https://github.com/dotnet/runtime/blob/945b82848aa0209f59d65d21cfe3c0be010dd7c7/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/X500NameEncoder.cs#L549-L556

I think it's reasonable to account for the flag here.

**Comment by vcsjones** [comment]
I threw up a PR to see if we can start respecting that flag.

In the mean time, with the `System.Formats.Asn1` namespace / package, you can convert your distinguished name to use UTF8 strings. Here is an example I threw together to do so.

```C#
static X500DistinguishedName ReEncodeAsUtf8(X500DistinguishedName dn)
{
    AsnReader reader = new(dn.RawData, AsnEncodingRules.DER);
    AsnWriter writer = new(AsnEncodingRules.DER);
    AsnReader outerSeq = reader.ReadSequence();
    reader.ThrowIfNotEmpty();

    using (writer.PushSequence())
    {
        while (outerSeq.HasData)
        {
            AsnReader rdn = outerSeq.ReadSetOf(skipSortOrderValidation: true); // Skip to match Window's behavior.

            using (writer.PushSetOf()) // Push an RDN.
            {
                while (rdn.HasData)
                {
                    using (writer.PushSequence())
                    {
                        AsnReader valueReader = rdn.ReadSequence();
                        string oid = valueReader.ReadObjectIdentifier();
                        writer.WriteObjectIdentifier(oid);

                        Asn1Tag tag = valueReader.PeekTag();

                        if (tag == new Asn1Tag(TagClass.Universal, (int)UniversalTagNumber.PrintableString))
                        {
                            string printableString = valueReader.ReadCharacterString(UniversalTagNumber.PrintableString);
                            writer.WriteCharacterString(UniversalTagNumber.UTF8String, printableString);
                        }
                        else if (tag == new Asn1Tag(TagClass.Universal, (int)UniversalTagNumber.UniversalString))
                        {
                            string universalString = valueReader.ReadCharacterString(UniversalTagNumber.UniversalString);
                            writer.WriteCharacterString(UniversalTagNumber.UTF8String, universalString);
                        }
                        else if (tag == new Asn1Tag(TagClass.Universal, (int)UniversalTagNumber.NumericString))
                        {
                            string universalString = valueReader.ReadCharacterString(UniversalTagNumber.NumericString);
                            writer.WriteCharacterString(UniversalTagNumber.UTF8String, universalString);
                        }
                        else
                        {
                            // Don't know what it is, pass it through.
                            writer.WriteEncodedValue(valueReader.ReadEncodedValue().Span);
                        }

                        valueReader.ThrowIfNotEmpty();
                    }
                }
            }
        }
    }

    return new X500DistinguishedName(writer.Encode());
}
```

**Comment by vcsjones** [comment]
In addition to the pull request to address this for .NET 7, .NET 7 will also have [`X500DistinguishedNameBuilder`](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x500distinguishednamebuilder?view=net-7.0) which will make it easier to create distinguished names, an also choose their encoding.

**Comment by darjanbogdan** [comment]
Thank you very much for the quick response and helpful workaround!
