### ISSUE TITLE
[libraries-jitstressregs] Assertion failure !CREATE_CHECK_STRING(!"Detected use of a corrupted OBJECTREF. Possible GC hole.")

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#72697]
runtime-coreclr libraries-jitstressregs pipeline is 0% pass for the past 21 days. 

It failed with an assert:
```scala
Assert failure(PID 12076 [0x00002f2c], Thread: 7132 [0x1bdc]): !CREATE_CHECK_STRING(!"Detected use of a corrupted OBJECTREF. Possible GC hole.")
```

- [Pipeline](https://dev.azure.com/dnceng/public/_build/results?buildId=1886123&view=results)
- [Console Log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-7e75c58712f24aa299/System.Text.Json.Tests/1/console.f0058568.log?helixlogtype=result)

**Comment by JulieLeeMSFT** [comment]
cc @dotnet/jit-contrib.

**Comment by kunalspathak** [comment]
I don't see it reproing in latest https://dev.azure.com/dnceng/public/_build/results?buildId=1900130&view=results or it could be inconsistent. Let us keep an eye to check if we see more of these. For now, closing it.

**Comment by JulieLeeMSFT** [comment]
This failure is hit in many tests in [runtime-coreclr gcstress-extra](https://dev.azure.com/dnceng-public/public/_build?definitionId=113&_a=summary)/[20240714.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=740628).

**Comment by kunalspathak** [comment]
@JulieLeeMSFT - can you confirm for which test/build/configuration is this? The tests link is pointing to `gcstress-extra` which makes me wonder if it is duplicate of #104924

**Comment by JulieLeeMSFT** [comment]
Basically almost all the test configs that failed with Regressions/coreclr/GitHub_45929/test45929/**test45929.cmd**

![image](https://github.com/user-attachments/assets/c14e731f-29bd-41f0-ba9a-48c53c42a8e1)

![image](https://github.com/user-attachments/assets/e8b5c2fe-6897-432b-bf22-09abbf7caa9c)

![image](https://github.com/user-attachments/assets/bdbc1d17-72f9-4d9d-9a82-5c5a5ff1f098)

**Comment by JulieLeeMSFT** [comment]
Green: https://dev.azure.com/dnceng-public/public/_build/results?buildId=754383&view=results.
Monitor some more weeks.

**Comment by JulieLeeMSFT** [comment]
Fixed by https://github.com/dotnet/runtime/pull/104912. Not failing anymore.
