### ISSUE TITLE
JsonStringEnumConverter does not properly serialize properties with default value (i.e. not set)

### ISSUE THREAD

**Issue by VagyokC4** [dotnet/runtime#72699]
### Description

JsonStringEnumConverter fails to convert the value to the string equivalent when the value is not set.

### Reproduction Steps

Given the following model
```csharp
public record SampleModel
{
	[JsonConverter(typeof(JsonStringEnumConverter))]
	public EnumType EnumType { get; set; }
}

public enum EnumType
{
	Type1 = 1,
	Type2 = 2,
}
```
using the following code produces two different results:
```csharp
System.Text.Json.JsonSerializer.Serialize(new SampleModel());
System.Text.Json.JsonSerializer.Serialize(new SampleModel { EnumType = EnumType.Type1 });
```

### Expected behavior

I would expect both results to be identical:
```json
{"EnumType":"Type1"}
{"EnumType":"Type1"}
```

### Actual behavior

```json
{"EnumType":0}
{"EnumType":"Type1"}
```

### Other information

Maybe this goes deeper and not just the coverter as I get the same issue when not using the StringConverter.  For example:
```csharp
public record SampleModel
{
	public EnumType EnumType { get; set; }
}

public enum EnumType
{
	Type1 = 1,
	Type2 = 2,
}
```
and
```csharp
System.Text.Json.JsonSerializer.Serialize(new SampleModel());
System.Text.Json.JsonSerializer.Serialize(new SampleModel { EnumType = EnumType.Type1 });
```
Produces inaccurate results, as there is no Enum Value = 0:
```json
{"EnumType":0}
{"EnumType":1}
```

**Comment by gregsdennis** [comment]
The issue is that your `SampleModel.EnumType` is initializing to the default value of `EnumType` on the first line.  The default value of an enum type is the 0-equivalent.  Since you don't define a 0 value in your enum, it serializes as the number.

**Comment by VagyokC4** [comment]
> The issue is that your `SampleModel.EnumType` is initializing to the default value of `EnumType` on the first line. The default value of an enum type is the 0-equivalent. Since you don't define a 0 value in your enum, it serializes as the number.

Shouldn't the logic then be to use the first value in the enum that is above zero?  I would expect the default value of the enum to be serialized (regardless of 0 value).  Is there a configuration option to change this behaviour?

**Comment by gregsdennis** [comment]
This is a matter of how .Net works rather than serialization.  When you _instantiate_ the object, the default value is set.  The serializer just converting what it gets.

Try this:

```c#
var model = new SampleModel();
```

When you inspect `model.EnumType`, you'll see that the value is 0, even in the debugger.

**Comment by VagyokC4** [comment]
> This is a matter of how .Net works rather than serialization. When you _instantiate_ the object, the default value is set. The serializer just converting what it gets.
> 
> Try this:
> 
> ```cs
> var model = new SampleModel();
> ```
> 
> When you inspect `model.EnumType`, you'll see that the value is 0, even in the debugger.

I see, so the default value is 0, and if you have a 0 option defined, all is well, otherwise it saves it's value as 0, even though no option exists with value 0.

This means my only option here to get accurate data is to go and set a default value to all my enums within all my models?
```csharp
	[JsonConverter(typeof(JsonStringEnumConverter))]
	public EnumType EnumType { get; set; } = EnumType.Type1;
```
or go add a Zero option,
```csharp
public enum EnumType
{
	None,
	Type1=1,
	Type2=2,
}
```
Both seem non ideal, but I think option 1 is a valid work-around.

Still seems like maybe the issue then is with .Net?  I feel like I should be able to create a non zero enum, and if I don't set it, the value should still be a valid enum value, as opposed to a breaking value.  When we want to show the enum as not set, we use an EnumType? and set it to null, otherwise I would expect the enum value to be a valid enum value.

**Comment by gregsdennis** [comment]
> Still seems like maybe the issue then is with .Net? I feel like I should be able to create a non zero enum, and if I don't set it, the value should still be a valid enum value, as opposed to a breaking value. When we want to show the enum as not set, we use an EnumType? and set it to null, otherwise I would expect the enum value to be a valid enum value.

It's not an issue. This is as designed.

0 _is_ a valid enum value; it's just not _named_.

If you want `Type1` to be your default value, then just assign it 0:

```c#
enum EnumType
{
    Type1 = 0,
    Type2 = 1
}
```

or better yet, don't assign values at all:

```c#
enum EnumType
{
    Type1,
    Type2
}
```

You can read more about how enums work in .Net [here](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/enum).

**Comment by VagyokC4** [comment]
> It's not an issue. This is as designed.
> 
> 0 _is_ a valid enum value; it's just not _named_.

Very good, I will close this issue out.  Thank-you for your time and attention to this matter.
