### ISSUE TITLE
When I added authorization request header to HttpClient.DefaultRequestHeaders, runtime threw the System.FormatException

### ISSUE THREAD

**Issue by hbhsb** [dotnet/runtime#727]
We use custom authentication method when authenticating HTTP requests. Then we find that when the authorization schema is empty and there is a slash in the token, HttpHeaderParser.Parsevalue will throw this exception:
`System.FormatException: The format of value 'et3ggt/teg2trtrg' is invalid.
   at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor descriptor, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(String name, String value)`

**Comment by davidsh** [comment]
>We use custom authentication method when authenticating HTTP requests.

What kind of Authentication method?  

You probably might need to encode the '/' character.

**Comment by hbhsb** [comment]
@davidsh After I encode the '/' character,it runs.Tanks

**Comment by davidsh** [comment]
>@davidsh After I encode the '/' character,it runs.Thanks

Great to hear it's working now.

Using the '/' character directly in an HTTP request header value is against RFC specification for allowed characters in the header value. So, percent encoding (or other encoding such as Base64) is required.

Closing this issue since behavior is by-design.

**Comment by daniel-munch-cko** [comment]
> Using the '/' character directly in an HTTP request header value is against RFC specification for allowed characters in the header value. So, percent encoding (or other encoding such as Base64) is required.

I think this comment is misleading - It's not that the '/' character is not allowed in any HTTP request headers per se - It's mostly that the .NET implementation enforces very special formating rules on specific HTTP headers. I.e. for Authentication, an`/` might not be allowed. The `User-Agent` header on the other hand usually contains plenty of spaces. But also there, the above-mentioned Exception would be thrown in certain cases, i.e. when you have a trailing slash. I.e. "key/value" would be valid, but "key/" with a trailing slash wouldn't. 

See also: http://bizcoder.com/the-much-maligned-user-agent-header

An improvement would be to be more specific in the Exception message.
