### ISSUE TITLE
Composite R2R binaries do not have a copyright in the PE 

### ISSUE THREAD

**Issue by mmitche** [dotnet/runtime#72701]
### Description

Composite r2r images seem to be missing a copyright. 

### Reproduction Steps

See https://dev.azure.com/dnceng/internal/_build/results?buildId=1897698&view=artifacts&pathAsName=false&type=publishedArtifacts, under BlobArtifacts, dotnet-runtime-composite-*win* zip files. See shared/Microsoft.NETCore.App/<version>/Microsoft.NETCore.App.Composite.r2r.dll

The pe copyright field is empty. This causes the signing infrastructure to warn/error about signing a 3rd party binary with a MIcrosoft cert.

### Expected behavior

Copyright should be non-empty

### Actual behavior

Copyright is empty

**Comment by hoyosjs** [comment]
cc: @trylek @mangod9

**Comment by ivdiazsa** [comment]
I took a look at this and, apparently the composite images are being copyrighted accordingly.

For example, this one: https://dev.azure.com/dnceng/_apis/resources/Containers/11216388/BlobArtifacts?itemPath=BlobArtifacts%2Fdotnet-runtime-composite-7.0.0-rc.1.22372.2-win-x64.zip

This is what I observed:

<img width="863" alt="Screenshot 2022-07-25 135415" src="https://user-images.githubusercontent.com/52939971/180874515-9ec9522a-756d-492f-ac2c-9d90db1366e3.png">

**Comment by mmitche** [comment]
There might be something else going on. I'll dig further into why it thinks the PE file doesn't have a copyright.

Btw, I noticed something else odd. The Composite package appears to be named in a rid-agnostic way on NuGet.org, but has RID specific binaries. It ends up only published from win-x64 because the build is claiming it is RID agnostic, Is this correct?

![image](https://user-images.githubusercontent.com/8725170/180884433-f149ba67-5246-4c6f-8aa2-12975dd99ebc.png)

**Comment by hoyosjs** [comment]
@mmitche I see what happened, I'll ping you offline.

**Comment by mangod9** [comment]
I believe a rid is required since its clearly generating native code :)
