### ISSUE TITLE
`Match.NextMatch` returns incorrect `Index` values for `Regex.Match(string, int, int)`

### ISSUE THREAD

**Issue by bgrainger** [dotnet/runtime#72704]
### Description

In .NET 7.0, the `Match` object returned from `Regex.Match(string, int, int)` returns incorrect values for `Match.Index` after `Match.NextMatch()` is called.

The first value of `Match.Index` is correct, but all subsequent values are relative to the `beginning` parameter that was passed to `Regex.Match`.

### Reproduction Steps

```csharp
using System.Text.RegularExpressions;

var str = "a.b.c.d.e.f";
var period = new Regex(@"\.");

var match = period.Match(str, 4, str.Length - 4); // NOTE: doesn't fail for period.Match(str, 4)
while (match.Success)
{
	Console.WriteLine(match.Index);
	match = match.NextMatch();
}
```

### Expected behavior

.NET 6.0 prints:

```
5
7
9
```

### Actual behavior

.NET 7.0 prints:

```
5
3
5
```

### Regression?

Yes; this works correctly in .NET 6.0.7 and .NET Framework 4.8.

### Known Workarounds

The `Regex.Match(string, int)` overload doesn't exhibit this bug, so if the substring being matched happens to extend through the end of the string (i.e., the third parameter is equal to `input.Length - beginning`), you can call the two-argument overload instead.

### Configuration

7.0.0-preview.6.22351.3
Windows 10 21H2, x64

**Comment by bgrainger** [comment]
This bug also affects a Regex using source generators:

```csharp
public partial class Program
{
	public static void Main()
	{
		var str = "a.b.c.d.e.f";

		var match = PeriodRegex().Match(str, 4, str.Length - 4);
		while (match.Success)
		{
			Console.WriteLine(match.Index);
			match = match.NextMatch();
		}
	}

	[RegexGenerator(@"\.")]
	private static partial Regex PeriodRegex();
}
```

**Comment by stephentoub** [comment]
Thanks for the good repro.  Fixed in https://github.com/dotnet/runtime/pull/72728.
