### ISSUE TITLE
[API Proposal]: Span<byte> constructor for MemoryStream

### ISSUE THREAD

**Issue by RedIODev** [dotnet/runtime#72723]
### Background and motivation

A memory stream should work with a span of bytes. When you have a span of bytes as your data and need a MemoryStream for another api you shouldn't need to copy the data from the span to a new byte array to get a "view" in form of a memory stream to it. This conversion from one type of memory view to another should be seamlessly possible.

### API Proposal

```csharp
namespace System.IO;

public class MemoryStream : Stream
{
    public MemoryStream(Span<byte> buffer) 
    {
        ...
    }
    ...
}
```

### API Usage

```csharp
Span<byte> someData = ...;
using MemoryStream ms = new MemoryStream(someData);
//The FromImage is just an example for an API that uses a stream and doesn't take a span. I don't propose a change to the creation of an Image from bytes.
Image imgFromData = Image.FromStream(ms);
```

### Alternative Designs

Alternatively the byte array constructor of MemoryStream could be changed to a Span<bytes> with likely braking no code since a byte array can implicitly be converted to a Span<bytes>.

**Comment by EgorBo** [comment]
MemoryStream has to copy your data to its field on the heap so you can't avoid it.
In your case you can do `new MemoryStream(someData.ToArray())` - there won't be a redundant copy we can avoid here.

**Comment by tfenise** [comment]
If you really need a `Stream` backed by a `Span<byte>`, you may pin the `Span<byte>`, get a `byte*`, and create an `UnmanagedMemoryStream`. A more hacky solution is maybe to somehow get a pointer to the `Span<byte>` and use that pointer to access the `Span<byte>` in your own implementation of `Stream`. However, I don't recommend these solutions, as extra attention is needed to preserve memory safety.

**Comment by teo-tsirpanis** [comment]
A `MemoryStream` constructor that takes a span and does not copy the data is simply _impossible_ to have due to `ref struct` restrictions.

A stream that reads a `Memory<byte>` is possible and has been proposed in #22838.
