### ISSUE TITLE
Random System.ArgumentOutOfRangeException in HttpListener

### ISSUE THREAD

**Issue by MontoyaTech** [dotnet/runtime#72748]
### Description

I'm not sure what causes this but our Rest API server that uses HttpListener randomly crashes under Linux x64 (Ubuntu Server latest) running DotNet 6.

![image](https://user-images.githubusercontent.com/48062411/180668529-cabd53b0-7cb4-4804-8cfe-ee6ad8109b27.png)

### Reproduction Steps

We are not sure what causes this, randomly happens.

### Expected behavior

Shouldn't crash.

### Actual behavior

Crashes.

### Configuration

.NET SDK (reflecting any global.json):
 Version:   6.0.302
 Commit:    c857713418

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.302/

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  6.0.302 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by stephentoub** [comment]
From a quick look at https://github.com/dotnet/runtime/blob/0c32267664e1b9913f2329827d998646fecafd91/src/libraries/System.Net.HttpListener/src/System/Net/HttpListenerRequestUriBuilder.cs#L357, it looks like this exception could occur erroneously if the host contains a question mark.  Is it possible that's occurring? e.g. `GetPath("http://www.example.com?/this/is/a/test")` will result in this exception.

**Comment by MontoyaTech** [comment]
@stephentoub Thanks for the reply. I tried to recreate the exception by crafting a url like the one you sent but by sending a custom request to the HttpListener directly and nothing happens. I'm not sure how this keeps happening.

**Comment by jdufaud** [comment]
I have exactly the same problem since 2 days every 6 hours, very random without any change, has been working for 2 years in production. And since a disaster ...

**Comment by MontoyaTech** [comment]
@jdufaud I have a similar experience, our Api has been running great for months no issues no crashes ever. We did a upgrade on our server recently which also upgraded DotNet automatically and ever since then we keep seeing these exceptions every few days. 

@stephentoub Wouldn't a simple solution be to put a try catch around the GetPath's body and on exception return a empty string? The function guarantee's a non null string, according to the doc. In my mind since this function is critical it should not be able to throw an exception.

**Comment by stephentoub** [comment]
> Wouldn't a simple solution be to put a try catch around the GetPath's body and on exception return a empty string?

For the issue I cited there a much cleaner one-line fix, which we'll do. But it sounds like that may not be the sole issue here, which we'd want to bettee understand, e.g. what changed recently to cause this, or else we're just suppressing an indication of something potentially more impactful.

**Comment by MontoyaTech** [comment]
@stephentoub I agree, it does appear that [This line](https://github.com/dotnet/runtime/blob/0c32267664e1b9913f2329827d998646fecafd91/src/libraries/System.Net.HttpListener/src/System/Net/HttpListenerRequestUriBuilder.cs#L423) is the issue, somehow `queryIndex - pathStartIndex` is getting to be negative, but according to our nginx reverse proxy logs we don't see any requests with a ? before the path slash. It could be that it's not getting logged, I am hoping this crash happens again so I can get more information for you.

If it helps, here is a snippet of our code that uses the HttpListener GetContext method:
`private void Listen()
{
    ThreadPool.QueueUserWorkItem((o) =>
    {
        while (this.HttpListener.IsListening)
        {
            //Try catch around the thread pool, don't allow it to die.
            try
            {
                ThreadPool.QueueUserWorkItem((item) =>
                {
                    var ctx = item as HttpListenerContext;
                    try
                    {
                        //Process the request....
                    }
                    catch (Exception ex)
                    {
                        ctx.Response.WithStatus(HttpStatusCode.InternalServerError);
                        ctx.Response.Close();
                    }
                }, this.HttpListener.GetContext());
            }
            catch { }
        }
    });
}`

The interesting thing is we have a try-catch around the GetContext queue but the exception I posted above kills the entire Api. I am going to try to catch it through the AppDomain UnhandledException event.

**Comment by jdufaud** [comment]
> 
Same than you @MontoyaTech I have a try-catch around the GetContext
I tried with the AppDomain UnhandledException event and these are my logs just before the crash:

07/25/2022 05:34:20  url:  http://xxx.net:8081/health
07/25/2022 05:34:20  url:  http://xxx.net:8081/health
07/25/2022 05:34:20  IsTerminating: True
System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at System.Net.HttpListenerRequestUriBuilder.GetPath(String uriString)
   at System.Net.HttpListenerRequestUriBuilder.BuildRequestUriUsingRawPath()
   at System.Net.HttpListenerRequestUriBuilder.Build()
   at System.Net.HttpListenerRequest.FinishInitialization()
   at System.Net.HttpConnection.OnReadInternal(IAsyncResult ares)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Threading.ThreadPoolWorkQueue.Dispatch() crash manager

**Comment by stephentoub** [comment]
Here's an example of the exception being triggered (and apparently eaten somewhere in the listener implementation):
```C#
using System;
using System.IO;
using System.Net;
using System.Net.Sockets;
using System.Text;
using System.Threading.Tasks;

internal class Program
{
    private static void Main()
    {
        AppDomain.CurrentDomain.FirstChanceException += (s, e) => Console.WriteLine(e.Exception);

        using HttpListener listener = new HttpListener();
        listener.Prefixes.Add("http://*:8080/");
        listener.Start();

        Task.Run(() =>
        {
            try
            {
                using var s = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
                s.Connect(new IPEndPoint(IPAddress.Loopback, 8080));
                s.Send(Encoding.ASCII.GetBytes("GET http://ab?cd/ HTTP/1.1\r\nHost: localhost:8080\r\n\r\n"));
                byte[] buffer = new byte[1000];
                while (true)
                {
                    int n = s.Receive(buffer);
                    if (n == 0) break;
                    Console.WriteLine(Encoding.ASCII.GetString(buffer.AsSpan(0, n)));
                }
            }
            catch (Exception e)
            {
                Console.WriteLine($"Request failed: {e}");
            }
        });

        HttpListenerContext context = listener.GetContext();
        HttpListenerRequest request = context.Request;
        using HttpListenerResponse response = context.Response;
        byte[] buffer = Encoding.UTF8.GetBytes("<HTML><BODY> Hello world!</BODY></HTML>");
        response.ContentLength64 = buffer.Length;
        using (Stream output = response.OutputStream)
        {
            output.Write(buffer);
            output.Flush();
        }
    }
}
```
The fix for this would just be to pass `pathStartIndex` as the second argument to:
https://github.com/dotnet/runtime/blob/0c32267664e1b9913f2329827d998646fecafd91/src/libraries/System.Net.HttpListener/src/System/Net/HttpListenerRequestUriBuilder.cs#L416

This doesn't explain, however, what's changed recently that's causing you to see this and for it to crash.  If it's only ever few days, it's of course possible it's just a latent issue and the performance of something elsewhere in the stack changed causing it to show up.

**Comment by MontoyaTech** [comment]
@jdufaud Dang yeah this is the exact behavior I am seeing. Do you have any logs about what request might be causing this? We are still trying to see if it's a malicious request that triggers this exception.

@stephentoub This couldn't be some sort of memory related issue could it?

**Comment by jdufaud** [comment]
@MontoyaTech no malicious request, everything seems normal.
Just like you I'm on Linux with the same version, and using nginx reverse proxy.

**Comment by MontoyaTech** [comment]
@stephentoub Thanks for that snippet, I tried something similar but had no luck, even yours didn't work at first, but I put it in a loop like this and at request #10 my Api crashed. 😲

`
for (int i = 0; i < 1000; i++)
{
    Console.WriteLine("Sending bad payload " + i);
    using var s = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
    s.Connect(new IPEndPoint(IPAddress.Parse("137.184.122.131"), 8081));
    s.Send(Encoding.ASCII.GetBytes("GET http://ab?cd/ HTTP/1.1\r\nHost: api.yayday.fun\r\n\r\n"));
}
`

**Comment by MontoyaTech** [comment]
@stephentoub I did some testing on Windows and using DotNet 6 with the same codebase this exception doesn't happen. Just thought I'd let you know in case it helps.

**Comment by MontoyaTech** [comment]
@stephentoub Thanks for working on a fix and helping us. I do have a question though, is there something else wrong besides the issue with the HttpListener? I had try catches around the thread pool cool and the listener itself but it still caused my entire exe to abort and exit. Shouldn't this exception have been thrown but the application as a whole could have recovered by a try catch?

**Comment by stephentoub** [comment]
It's happening inside the HttpListener implementation at a point where exceptions weren't expected; it's thus bubbling out of a queued work item where there's no user code currently on the stack.

**Comment by MontoyaTech** [comment]
@stephentoub Ah okay that's what I was wondering. Thanks for the quick reply.

**Comment by Oyshoboy** [comment]
Looks like we experiencing same issue:
<img width="1468" alt="image" src="https://user-images.githubusercontent.com/23486183/183226080-538ed588-a252-42d9-b078-0798d324bc51.png">
