### ISSUE TITLE
Graphics.MeasureString returns negative width for a string of spaces

### ISSUE THREAD

**Issue by vkrevs** [dotnet/runtime#72766]
### Description

Graphics.MeasureString returns negative width for a string of spaces when printing documents using System.Drawing.Printing APIs.

### Reproduction Steps

This simple project [[WindowsFormsApp1.zip](https://github.com/dotnet/runtime/files/9179851/WindowsFormsApp1.zip)] prints 3 lines of text. It is based on the [PrintDocument.PrintPageEvent example code](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.printing.printdocument.printpage?view=dotnet-plat-ext-6.0). 

The second line is hard-coded to be a line of 50 spaces. Each line's dimensions are measured using [System.Drawing.Graphics.Measurestring](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.graphics.measurestring?view=dotnet-plat-ext-6.0)

The result of System.Drawing.Graphics.Measurestring for a string of 50 spaces is surprisingly a SizeF struct with a very small negative width: 9.996211E-05. The height is as expected: 15.51649

### Expected behavior

I'd expect the measured width of a 50 space string to be similar to that of a string consisting of 50 underscores.

### Actual behavior

The measured width of a 50 space string is a SizeF struct with a very small negative width: 9.996211E-05.

### Configuration

.NET SDK 6.0 201 (x64)
Windows 10 (21H2)

**Comment by huoyaoyuan** [comment]
`MeasureString`  and most `System.Drawing` members ends up calls the OS. You may include more detailed OS version here to confirm if there is a OS bug.

**Comment by hypeartist** [comment]
@vkrevs Try adding this flag:
```csharp 
formatStyle.FormatFlags |= StringFormatFlags.MeasureTrailingSpaces; 
```

**Comment by vkrevs** [comment]
@huoyaoyuan OS version is 19044.1826

@hypeartist Thank you very much - this fixes the issue.
