### ISSUE TITLE
Support for ClearLinux?

### ISSUE THREAD

**Issue by markrendle** [dotnet/runtime#7276]
Just been reading up on [ClearLinux](https://clearlinux.org/) after an official VM image for Azure was published. It looks great, an Intel-optimized Linux designed for (a) running containers and (b) being the base image for containers.

Obviously I can run the existing Debian-based `microsoft/dotnet` image on a ClearLinux host, possibly to great effect, but I guess the CoreCLR build and native-compiled libraries wouldn't be taking advantage of whatever the Intel optimizations are? Or would it? I don't know about these things.

Assuming there would be performance benefits, can ClearLinux be added to the never-ending list of "please support this Linux"?

**Comment by danmosemsft** [comment]
There seems no more action here.
