### ISSUE TITLE
Unix Domain Sockets: deleting file at sockPath is allowed while socket is listening for connections

### ISSUE THREAD

**Issue by pkindruk** [dotnet/runtime#72774]
### Description

I was testing AF_UNIX for some production cases in my IPC code. And I found that you can always delete file at `sockPath` even if there is a socket listening to it and there are no exceptions on `AcceptAsync` method. I can delete that file from another instance of my app or even from File Explorer.

My issue here is that I can't really tell if there is a program is listening to a socket and I have bad configuration, or it crashed/was killed due to unresponsiveness and couldn't delete file.

### Reproduction Steps

```csharp
const string sockPath = "tmp.sock";

if (File.Exists(sockPath))
    File.Delete(sockPath);

var socket1 = new Socket(AddressFamily.Unix, SocketType.Stream, ProtocolType.IP);
socket1.Bind(new UnixDomainSocketEndPoint(sockPath));

socket1.Listen(100);

var acceptTask = socket1.AcceptAsync();

Console.WriteLine("Ready");
Console.ReadKey();

File.Delete(sockPath);
Console.WriteLine(acceptTask.Status); // prints WaitingForActivation

Console.ReadKey();

socket1.Close();
socket1.Dispose();
```

### Expected behavior

Standard file locked exception when trying to delete file used by unix socket.

### Actual behavior

File can be deleted by any process while socket is listening.

### Configuration

.NET SDK (reflecting any global.json):
 Version:   6.0.302
 Commit:    c857713418

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.302\

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

### Other information

For my case I can work this around by introducing a convention for my IPC: Keep different file open while I need that socket and check if can delete that file. You can still delete socket file manually, but we can call that malicious behavior for now.

**Comment by stephentoub** [comment]
> Standard file locked exception when trying to delete file used by unix socket.

This would be up to Windows' implementation of domain sockets. The OS handles interaction with the file... the .NET wrapping layer doesn't interact with the file at all.

**Comment by pkindruk** [comment]
I was pretty sure it is about WinSock API implementation. I just don't know where to put issues about that.

**Comment by antonfirsov** [comment]
I think this is by-design, if you are afraid of malicious behavior, you should solve it by configuring permissions on the file:
https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/#security

**Comment by wfurt** [comment]
I don't think permission would be sufficient @antonfirsov. Certainly on Unix `root` can do anything. 
Conceptually this is IMHO similar to listening on TCP port but blocking traffic with packet filter. 
I don't think it is job of the socket to guard agains misuse.

**Comment by pkindruk** [comment]
As @wfurt said having enough rights you can override permissions.

I was treating unix sockets similar to tcp sockets. In tcp sockets you can't listen on the same `(protocol, src_address, src_port)` tuple (unless you use `SO_REUSEPORT`). So I thought OS keeps some sort of file handle associated with listening socket to keep track of used resources. However that's not the case.

After looking up this issue on unix world, I came to conclusion that it was designed like that originally and stayed over years. So even if Windows adds something to fix it, this will introduce behavior difference between different OS. There is probably zero chance that smth will be done.

Community proposes a way to check if smth is listening to unix socket: try connect to socket and then immediately disconnect. However server implementation should be able to handle that, also accept loop might be blocked by smth.

**Comment by antonfirsov** [comment]
Triage: closing, since we do not want to override OS behavior in .NET code.

@tmds any ideas / best practices regarding the topic?
