### ISSUE TITLE
GetGetMethod().MethodHandle.GetFunctionPointer()

### ISSUE THREAD

**Issue by kefyru** [dotnet/runtime#72781]
### Description

```cs
public unsafe class Getter<TTarget, TProperty> 
{
  private delegate*<TTarget, TProperty> _mptr   
  public Getter(string propName) {
    _mptr = (delegate*<TTarget, TProperty>) typeof(TTarget).GetProperty(propName).GetGetMethod().MethodHandle.GetFunctionPointer();
  }
  public TProperty Get(TTarget target) 
  { 
    var v = _mptr(target);
    return v;
  }
}
```

I did something like that.
In Mac OS works as expected;

In widows:
if TProperty is value type, a see strange behaviour
```cs
...
public TProperty Get(TTarget target) { // target: some object (generic class)
 var v _mptr(target); // target: some object, v: default (generic struct)
 // after call _mptr,
 // v: default (struct),
 // target: 'the value is not an object'
 return v;
}
...
```

I tried to add managed keyword: delegate* managed<...> - the same result.

### Reproduction Steps

Get function pointer for getter of struct type property
Call this function pointer

### Expected behavior

Return property value

### Actual behavior

See description

### Known Workarounds

If replace code with ```propInfo.GetGetMethod().CreateDelegate()``` everything ok

### Configuration

net 6.0.302
aspnetcore app

**Comment by svick** [comment]
I have trouble reproducing this. Can you share full code for a program that demonstrates the issue?

**Comment by kevingosse** [comment]
I tried to reproduce the issue, I get some inconsistent values when the struct is big enough:

```csharp
    public unsafe class Getter<TTarget, TProperty>
    {
        private delegate*<TTarget, TProperty> _mptr;
        private Func<TTarget, TProperty> _delegate;

        public Getter(string propName)
        {
            _mptr = (delegate*<TTarget, TProperty>)typeof(TTarget).GetProperty(propName).GetGetMethod().MethodHandle.GetFunctionPointer();
            _delegate = typeof(TTarget).GetProperty(propName).GetGetMethod().CreateDelegate<Func<TTarget, TProperty>>();
        }
        public TProperty Get(TTarget target)
        {
            var v = _mptr(target);
            return v;
        }

        public TProperty GetFromDelegate(TTarget target)
        {
            var v = _delegate(target);
            return v;
        }
    }

    public struct SomeStruct
    {
        public int Value1;
        public int Value2;
        public int Value3;
        public int Value4;
    }

    public class Obj
    {
        public SomeStruct Property { get; set; }
    }

    class Program
    {
        static async Task Main(string[] args)
        {
            var obj = new Obj { Property = new SomeStruct { Value1 = 42 } };

            var getter = new Getter<Obj, SomeStruct>("Property");

            var a2 = getter.GetFromDelegate(obj);
            var a1 = getter.Get(obj);

            Console.WriteLine($"Function pointer: {a1.Value1}");
            Console.WriteLine($"Delegate: {a2.Value1}");
        }
    }
```

Result:
```
Function pointer: 0
Delegate: 42
```

I haven't checked the assembly yet, but my guess is that the issue starts happening when the struct get too big to fit in a register.

**Comment by kevingosse** [comment]
After re-reading the documentation, it looks like function pointers are just not supported on instance methods? https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/function-pointers#allow-instance-methods

**Comment by jakobbotsch** [comment]
> After re-reading the documentation, it looks like function pointers are just not supported on instance methods?

Right, C# does not support function pointers pointing to instance methods. There is a difference between where the return buffer goes for instance methods and static methods on some ABI's, so you get this difference in behavior.

**Comment by sakno** [comment]
@kefyru , because your code violates runtime [ABI](https://github.com/dotnet/runtime/blob/main/docs/design/coreclr/botr/clr-abi.md). Currently, method pointers in C# can be used for **static** method only. It's not possible to represent a pointer to the instance method (in IL it's still possible). The runtime uses calling convention of the underlying platform. However, **this** is treated as special argument that is not covered in ABI:

> The managed this pointer is treated like a new kind of argument not covered by the native ABI, so we chose to always pass it as the first argument in (AMD64) RCX or (ARM, ARM64) R0.

This leads to incorrect passing of **this** pointer at the call site because you trying to call instance method (property getter) as a static method with explicit first argument.

Check #13165 for more information.

**Comment by kevingosse** [comment]
@sakno Just for my personal understanding, if you have a few minutes to spare. As I understand it, the issue is that the ABI expects `this` as the first parameter and the return buffer as the second parameter, whereas the function pointer will store the return buffer in the first argument. Is that correct?

In that case, this code would emulate the right behavior for structs that need a return buffer?

```csharp
        private delegate*<Obj, SomeStruct*, SomeStruct*> _mptr;

        public Getter(string propName)
        {
            var ptr = typeof(Obj).GetProperty(propName).GetGetMethod().MethodHandle.GetFunctionPointer();
            _mptr = (delegate*<Obj, SomeStruct*, SomeStruct*>)ptr;
        }

        public SomeStruct Get(Obj target)
        {
            SomeStruct returnValue = default;
            var v = _mptr2(target, &returnValue);
            return *v;
        }
```

(there again, it's just for my personal understanding, not to actually use)

**Comment by jakobbotsch** [comment]
> In that case, am I right to think that this code would emulate the right behavior for structs that need a return buffer?

No, this is not portable. On ARM64 platforms the ABI passes the return buffer in `x8` in most cases. This will pass the return buffer in `x1` in those cases.
