### ISSUE TITLE
Blazor WebAssembly error with new build: Can't find bindings module assembly: System.Private.Runtime.InteropServices.JavaScript

### ISSUE THREAD

**Issue by W0GER** [dotnet/runtime#72803]
### Description

We have a previous build that when deployed to a production server runs correctly. 

A new build of the same code yields an error when the Blazor WebAssembly attempts to load.

Error:
Uncaught (in promise) Can't find bindings module assembly: System.Private.Runtime.InteropServices.JavaScript [blazor.webassembly.js:1:13091](http://selector.outsell.cloud/_framework/blazor.webassembly.js?version=5)
    a http://selector.outsell.cloud/_framework/blazor.webassembly.js:1

We have attempted to resolve this issue by upgrading the following packages
- Upgraded WebAssembly from 5.0.0 (deprecated) to 5.0.17
- Upgraded Blazored.LocalStorage from 3.8.0 to 4.2.0
- Upgraded Blazorise.Bootstrap from 0.9.2.3 to 0.9.5.7
- Upgraded Blazorise.Icons.FontAwesome from 0.9.2.3 to 0.9.5.7

We have also attempted the resolution mentioned in [GitHub issue](https://github.com/dotnet/aspnetcore/issues/38436#issuecomment-992223262)  attempting to add the `?version=5` to the blazer.webassembly.js script import.

### Reproduction Steps

Build application - no warnings no errors
Run locally - runs without issue
Deploy to production server (where previous version runs fine) - encounters error above.

### Expected behavior

Recompiling a Blazor WebAssembly with no code changes should continue to work

### Actual behavior

The WebAssembly crashes and logs the following to the console:
Uncaught (in promise) Can't find bindings module assembly: System.Private.Runtime.InteropServices.JavaScript blazor.webassembly.js:1:13091
    a http://selector.outsell.cloud/_framework/blazor.webassembly.js?version=5:1

No indication is given to the user that something went wrong (very poor UI) and leaves the user with a blank page.

### Regression?

A previous build works, recompiling the app and deploying it causes the error. This seems to have been some change in the tool chain. 

### Known Workarounds

not that I have found

### Configuration

I've attempted the following .NET SDK:
5.0.406
5.0.408

Windows-x86

All browers are effected (Safari, Edge, Chrome, Firefox)

**Comment by lewing** [comment]
Does it work correctly with trimming disabled (PublishTrimmed=false)

**Comment by W0GER** [comment]
Added the following to the csproj file: 
<PublishTrimmed>false</PublishTrimmed>

Built and deployed; seems to be working
This seems indicates it's a problem with the trimming.

**Comment by lewing** [comment]
could try sticking [DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Runtime.InteropServices.JavaScript.Runtime", "System.Private.Runtime.InteropServices.JavaScript")] on main or some other method that is definitely not linked out, hopefully that will work around the issue.

Also given that .net5 is rapidly nearing the end of support, I would encourage you to try out targeting net6 or net7 if possible.

**Comment by W0GER** [comment]
We've got moving this tool to .NET 6 on our roadmap. I've got it working with the trimming disabled, as this was unplanned work it put us behind in our current sprint, so I won't have time to test out other solutions, but thank you for the suggestion.
