### ISSUE TITLE
NativeAOT will not generate a RUC warning if its inside an attribute

### ISSUE THREAD

**Issue by tlakollo** [dotnet/runtime#72805]
### Description

NativeAOT will bypass warning generation for Requires if it's embedded in a custom attribute. The usage of the custom attribute should generate a warning

### Reproduction Steps

```C#
public class RequiresOnAttributeCtorAttribute : Attribute
{
  [RequiresUnreferencedCode ("Message from attribute's ctor.")]
  public RequiresOnAttributeCtorAttribute ()
  {
  }
}

[RequiresUnreferencedCode ("Message from attribute's type.")]
public class RequiresOnAttributeTypeAttribute : Attribute
{
}

// Not generated warnings:
// [ExpectedWarning ("IL2026", "Message from attribute's ctor.")]
// [ExpectedWarning ("IL2026", "Message from attribute's type.")]
[RequiresOnAttributeCtor]
[RequiresOnAttributeType]
public void Method ()
{
}
```

### Expected behavior

Warnings are generated when accessing a custom attribute with members annotated with Requires

### Actual behavior

Warnings are not generated when accessing a custom attribute with members annotated with Requires

**Comment by vitek-karas** [comment]
This has been fixed in #83550.
