### ISSUE TITLE
Microsoft.NETCore.App.Composite packaging misauthored - currently only win-x64 packages get published

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#72828]
The Microsoft.NETCore.App Composite package appears to be named in a rid-agnostic way on NuGet.org, but has RID specific binaries.

_Originally posted by @mmitche in https://github.com/dotnet/runtime/issues/72701#issuecomment-1194715438_

**Comment by mmitche** [comment]
This might be a situation where we should put some checks in place to avoid this mistake in the future?

/cc @ericstj This is pretty close to what we were talking about last week. This is a partial package that is being published under a rid-agnostic name.

**Comment by ericstj** [comment]
Perhaps, I have no idea what this package is for so I can't say for certain.

**Comment by mangod9** [comment]
Since the composite packages are still experimental and not consumed downstream yet, moving this to 8, unless its blocking any builds. fyi @davidwrighton

**Comment by mmitche** [comment]
@mangod9 They're shipping to customers on nuget.org though? Should that be removed for now?

**Comment by mangod9** [comment]
> They're shipping to customers on nuget.org though?

I am not aware of anyone consuming these so should be ok to remove. @davidwrighton to confirm.

**Comment by mmitche** [comment]
Okay. We should mark these packages as non-shipping then, too, if we're not going to fix the authoring error.

**Comment by mangod9** [comment]
this packages is actually not being used. Perhaps we should remove from building in the runtime repo?
