### ISSUE TITLE
GenericCatchInterfaceProgram fails on mono

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#72827]
The test I added in https://github.com/dotnet/runtime/pull/72721 (https://github.com/dotnet/runtime/blob/5c7c1579afecfa53b18f2fe1df80fef0bc807144/src/tests/JIT/Generics/Exceptions/GenericCatchInterfaceProgram.il) fails on all mono runtimes e.g. https://dev.azure.com/dnceng/public/_build/results?buildId=1902704&view=ms.vss-test-web.build-test-results-tab&runId=49488840&resultId=101261&paneView=debug

Filing to track the issue in issues.target

**Comment by am11** [comment]
We have a coreclr label <kbd>area-ExceptionHandling-coreclr</kbd> but not for mono. Perhaps we should have one?

cc @vargaz

**Comment by vargaz** [comment]
What is the correct behavior here ? Not possible to have an interface as the catch class ?

**Comment by am11** [comment]
Test was disabled against this issue:
https://github.com/dotnet/runtime/blob/4cd3e780c469e2416b6ebaba903dbea7c411a5b8/src/tests/JIT/Generics/Exceptions/GenericCatchInterfaceProgram.il#L8
https://github.com/dotnet/runtime/blob/4cd3e780c469e2416b6ebaba903dbea7c411a5b8/src/tests/issues.targets#L1438-L1440

**Comment by jkotas** [comment]
Catch clauses in CoreCLR always only matched against base type hierarchy. 

No matching of interfaces, variance, etc. You can use interface in the catch clause, but it won't ever catch anything.
