### ISSUE TITLE
Newbie help on debugging libraries: Looking for a working vscode+linux debug setup for libraries

### ISSUE THREAD

**Issue by martencassel** [dotnet/runtime#72841]
I'm trying to debug specific libraries with vscode on linux. 
Trying to setup a .devcontainer setup with vscode and launch.json 
docs/workflow/debugging/libraries/unix-instructions.md
I haven't managed to replicate this setup yet...

Anyone have a working setup of this in a fork somewhere ? Where i can do some of the following tasks:
  * Debug unit tests for libraries with vscode in a devcontainer
  * Debug library code 
  * Debug library code with lldb and sos (code that uses external C libraries)

**Comment by carlossanlop** [comment]
We have a document related to devcontainer setup: https://github.com/dotnet/runtime/blob/c3e1d21c2fb30436ae24ef7ef4f458e3270bb7e3/docs/workflow/Codespaces.md

But it doesn't explain how to debug. @eerhardt is this something you could help with?

**Comment by eerhardt** [comment]
> But it doesn't explain how to debug. @eerhardt is this something you could help with?

Unfortunately, no. I don't have any experience debugging in VS Code.

**Comment by ViktorHofer** [comment]
@martencassel please see https://github.com/dotnet/runtime/blob/main/docs/workflow/debugging/libraries/debugging-vscode.md

**Comment by martencassel** [comment]
LGTM

**Comment by danmoseley** [comment]
@martencassel  as you use that doc, if you find any places it could be improved we would welcome a PR. Docs tend to get stale!
