### ISSUE TITLE
There are circumstances where ListEquality is broken on net7.0

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/runtime#72845]
There are circumstances where ListEquality is broken on net7.0

Repro:
1. install a dotnet 7.0
2. unzip this file 
[repro.zip](https://github.com/dotnet/fsharp/files/9185052/repro.zip)
3. cd to where you unzipped it:
4. Type dotnet run
5. Observe the output:
C:\temp\repro>dotnet run
Version: .NET 7.0.0-preview.7.22369.4
**failure: vwnwer-e**

Then either uninstall net7.0 or rename the directory containing the shared runtime: 
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.0-preview.7.22369.4 to something like:
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\XXXXXX7.0.0-preview.7.22369.4

6. And type dotnet run
7. observe the output:
C:\temp\repro>dotnet run
Version: .NET 6.0.7
**success: vwnwer-e**

**Comment by vzarytovskii** [comment]
> Looks like I don't have necessary rights in this repo to do that. Feel free to transfer it if you do.

Moved, thanks!

**Comment by jakobbotsch** [comment]
``Microsoft.FSharp.Collections.FSharpList`1[Int32][System.Int32]:Equals`` gets an OSR variant at IL offset 0 which probably is hitting some edge case somewhere.

**Comment by vzarytovskii** [comment]
Just to add, this works (note the upper boundary of the list):
```fsharp
open System.Runtime.InteropServices

[<EntryPoint>]
let main _ =
    printfn $"Version: {RuntimeInformation.FrameworkDescription}"
    let l1 = [0 .. 9997]
    let l2 = [0 .. 9997]
    let eq = l1 = l2
    printfn $"Lists equal: {eq}"

    0
```
and this fails
```fsharp
open System.Runtime.InteropServices

[<EntryPoint>]
let main _ =
    printfn $"Version: {RuntimeInformation.FrameworkDescription}"
    let l1 = [0 .. 9998]
    let l2 = [0 .. 9998]
    let eq = l1 = l2
    printfn $"Lists equal: {eq}"

    0
```

**Comment by AndyAyersMS** [comment]
Codegen for the method bodies of the eagerly optimized and OSR `Equals` are identical, only the prolog/epilog differs. So maybe some issue with the register save / restore or the arg fetch in the OSR version.

**Comment by AndyAyersMS** [comment]
`Equals` contains an assignment to `this` (that is, `stloc.0`) so likely the bug is that the OSR method is not getting the properly updated value.

**Comment by AndyAyersMS** [comment]
Yes, that's the bug. It's easy enough to report the updated `this` slot, but I also need to figure out if the OSR method also needs access to the original `this`.
