### ISSUE TITLE
Assert.Null failed for mono in System.Reflection.Emit.Tests

### ISSUE THREAD

**Issue by JosieBigler** [dotnet/runtime#72858]
### Description

Asserts fail in `System.Reflection.Emit\ModuleBuilder\ModuleBuilderDefineInitializedData.cs` and `System.Reflection.Emit\TypeBuilder\TypeBuilderCreateType.cs`

The return for `TypeBuilder.CreateType()` is changing to be non-nullable (so from `Type?` to `Type`) 

 

https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72180-merge-437d30d8adc24f8fb1/System.Reflection.Emit.Tests/1/console.5d48a2e1.log?helixlogtype=result

### Reproduction Steps

Run System.Reflection.Emit Tests with the mono runtime. 

### Expected behavior

The Asserts should be non-null for `System.Reflection.Emit\TypeBuilder\TypeBuilderCreateType.cs`  

And null for `System.Reflection.Emit\ModuleBuilder\ModuleBuilderDefineInitializedData.cs`

The problem tests have been annotated with the attribute `[ActiveIssue("https://github.com/dotnet/runtime/issues/72858", TestRuntimes.Mono)]` 

### Actual behavior

The Asserts fail.

### Regression?

This issue was caused based on PR https://github.com/dotnet/runtime/pull/72180.

**Comment by jkotas** [comment]
The problem is that Mono returns non-null DeclaringType for module global methods. It should return null according to https://docs.microsoft.com/en-us/dotnet/api/system.reflection.memberinfo.declaringtype

**Comment by SamMonoRT** [comment]
cc @lambdageek

**Comment by JosieBigler** [comment]
I think I have a fix for this? I need to clean up my code a bit before the PR.  

But it more or less borrows concepts from the CoreCLR  CoreLib and replicates them in Mono. 

The highlights include 

1. add a new field on `TypeBuilder` called `bool is_hidden_global_type`. This defaults to false, except when ModuleBuilder creates TypeBuilder in `CreateGlobalType()`. 
2. `DeclaringType` property on MethodBuilder and FieldBuilder have some extra logic to check for `is_hidden_global_type`. If true, returns null, otherwise returns `type`. 
3. Change `global_type_created` to `bool` to check if we're trying to create the GlobalFunctions a 2nd time.  Use `global_type.AsType()` for all the places `global_type_created` was previously used. 

If that sounds reasonable I would be more than happy to submit a PR.
