### ISSUE TITLE
Profile Blazor WASM using Mono log profiler

### ISSUE THREAD

**Issue by Chris-D-Turk** [dotnet/runtime#72870]
AFAIK there's currently no built-in option to profile Blazor WASM apps (cpu sampling). see dotnet/runtime#76316
But as Blazor WASM uses a Mono Runtime it should be possible to use the [Mono log profiler](https://www.mono-project.com/docs/debug+profile/profile/profiler/)?!
The devs of Uno WASM somehow managed to do this: https://platform.uno/blog/uno-platform-4-1-30-perf-boost-android-12-net-6-mobile-preview-13-and-more/

But I don't know how to pass the necessary arguments to the runtime environment: 
`--profile=log:sample,output=xxx.mlpd`

Is there any way to start a Blazor App with Mono arguments?

**Comment by jacob-l** [comment]
Hi @Chris-D-Turk , @lewing ,

What is the status of this issue? Is there any way to pass arguments to environment?

**Comment by pavelsavara** [comment]
I implemented browser profiler based on mono profiler here https://github.com/dotnet/runtime/pull/77449
There is also HOWTO-use in the PR description.

**Comment by pavelsavara** [comment]
Closing this in favor of https://github.com/dotnet/runtime/issues/72870
