### ISSUE TITLE
All codefix providers should have `SharedAttribute`

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/runtime#72876]
### Description

`[Shared]` is missing here:

https://github.com/dotnet/runtime/blob/39d82c99b44db470f43fc12498c1aec082e5c6e2/src/libraries/System.Text.RegularExpressions/gen/UpgradeToRegexGeneratorCodeFixer.cs#L27

and here:

https://github.com/dotnet/runtime/blob/39d82c99b44db470f43fc12498c1aec082e5c6e2/src/libraries/System.Runtime.InteropServices/gen/LibraryImportGenerator/Analyzers/ConvertToLibraryImportFixer.cs#L23

**Comment by stephentoub** [comment]
What is `[Shared]`?

**Comment by jkoritzinsky** [comment]
`CodeFixProvider`s are MEF components. Since they don't hold state (as per guidelines from Roslyn around their design), we can share a single instance in VS for all use cases. That's why we can mark it with `[Shared]`.

**Comment by stephentoub** [comment]
Is "All codefix providers should have SharedAttribute" documented somewhere?

**Comment by Youssef1313** [comment]
I don't think it's documented. But roslyn and roslyn-analyzers follow this for the reason @jkoritzinsky stated.

**Comment by jkoritzinsky** [comment]
There's an analyzer and code-fix for it in Roslyn.Diagnostics.Analyzers at https://github.com/dotnet/roslyn-analyzers/blob/main/src/Roslyn.Diagnostics.Analyzers/Core/PartsExportedWithMEFv2MustBeMarkedAsShared.cs that should be tripping on the CodeFixProviders in dotnet/runtime, but I'm not sure why it isn't firing

**Comment by stephentoub** [comment]
> that should be tripping on the CodeFixProviders in dotnet/runtime, but I'm not sure why it isn't firing

To my knowledge the Roslyn.Diagnostics.Analyzers are consumed by Roslyn.  I don't believe we pull in or enable anything from that package.

**Comment by jkoritzinsky** [comment]
That would explain why it isn't firing in this repo. I must have had it fire one time when I was working in the Roslyn repo, which lead me to point out the guidance for roslyn-analyzers.
