### ISSUE TITLE
The browser-wasm SDK should automatically reference the threading/perf-tracing ref assemblies

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#72872]
Some property property that uses the `multithreaded` runtime pack for the runtime artifacts and that adds a `<PackageReference Include="Microsoft.NET.WebAssembly.Threading" IncludeAssets="compile" PrivateAssets="none" />` package to use the right ref assemblies.

And the same thing for the `perftrace` runtime pack and the `System.Diagnostics.Tracing.WebAssembly.PerfTracing` ref assemblies

**Comment by lambdageek** [comment]
I think this is @radical 's https://github.com/dotnet/runtime/pull/72815

**Comment by lewing** [comment]
it is https://github.com/dotnet/runtime/pull/72412 but yes that is blocked on wbt at the moment

**Comment by radical** [comment]
The ref assemblies should be same for all the 3 variants, correct?

**Comment by lambdageek** [comment]
we have extra ref assemblies (`Microsoft.NET.WebAssembly.Threading` and `System.Diagnostics.Tracing.WebAssembly.PerfTracing`). Original plan was to place these in separate nugets that would get referenced when a user .csproj did some gesture. Does that make sense to do as part of the work you're doing?

**Comment by radical** [comment]
> we have extra ref assemblies (`Microsoft.NET.WebAssembly.Threading` and `System.Diagnostics.Tracing.WebAssembly.PerfTracing`). Original plan was to place these in separate nugets that would get referenced when a user .csproj did some gesture. Does that make sense to do as part of the work you're doing?

So, we need 3 ref pack nugets then?

**Comment by radical** [comment]
We also need a few Wasm.Build.Tests to exercise using the threaded runtimes, and the extra ref assemblies.

**Comment by lambdageek** [comment]
> > we have extra ref assemblies (`Microsoft.NET.WebAssembly.Threading` and `System.Diagnostics.Tracing.WebAssembly.PerfTracing`). Original plan was to place these in separate nugets that would get referenced when a user .csproj did some gesture. Does that make sense to do as part of the work you're doing?
> 
> So, we need 3 ref pack nugets then?

No? we need the SDK to add a PackageReference to one of the two new nugets when the corresponding runtime variant is selected that just has the handful of updated ref assemblies.

**Comment by radical** [comment]
- What would be a good test that would confirm that the correct runtime is being used?
- For the extra ref assemblies, I guess, we could use something from them

**Comment by lambdageek** [comment]
This is now mostly done (see https://github.com/lambdageek/hithread)

I think the only remaining thing is to automatically add a `<PackageReference Include=Microsoft.NET.WebAssembly.Threading"/>` that will pull in the threading-enabled reference assemblies which will quiet down the platform compatibility analyzer warnings about "unsupported" threading operations

https://github.com/lambdageek/hithread/blob/f7118d19ac88472576bd55671a33cfe9e5c2c099/hithread.csproj#L25

**Comment by lewing** [comment]
done
