### ISSUE TITLE
JIT: Optimize "and" of small type with larger constant

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/runtime#7288]
Prior to dotnet/coreclr#8672, for this code:
```
if ((p[i] & 0xffffff00) != 0) 
```
The JIT was generating this:
```
movsxd   r9, r8d
test     byte  ptr [rcx+r9], 0
```
And now it is generating this:
```
movsxd   r9, r8d
movzx    r9, byte  ptr [rcx+r9]
test     r9d, -256
```
This is probably an optimization that should be done prior to `Lowering`, but it may just be that it is not frequent enough to matter. However, the code has been captured in tests/src/JIT/Regression/JitBlue/DevDiv_1206929/DevDiv_1206929.cs (which was derived from a customer bug), just in case we should decide to pursue this.

category:cq
theme:basic-cq
skill-level:intermediate
cost:medium

**Comment by TIHan** [comment]
The `movzx` is not occuring anymore, closing. Filed an issue based on this example though: https://github.com/dotnet/runtime/issues/81520
