### ISSUE TITLE
Performance decrease when using interfaces

### ISSUE THREAD

**Issue by Thealexbarney** [dotnet/runtime#7291]
The general guidelines that I see for writing in C# usually say something like, "Accept as general of an object as you can for your parameters." For example, instead of requiring a List<T> as a parameter when you don't actually use List<T> specific methods, accept an IList<T>, or even an IEnumerable<T> if you can. This way you're not tied to a specific implementation. The basic concept of interfaces.

This works well in theory, but in practice, I've found that it's usually a bad idea when it comes to interfaces like IList, ICollection, or IEnumerable. In many of my projects, I've found that changing methods' parameter types from arrays or Lists to interfaces such as IList result in a 2-4x increase in execution time for the program.

Because virtual calls are used when using interfaces, making it so the JIT doesn't inline them, indexer access time is greatly increased. I was curious just how big the performance decrease was, so I put together a [little demo program](https://gist.github.com/Thealexbarney/ecd8f08aed994cd8c9076475b06cab07) to try and benchmark this, and the results were worse than I expected:
```
Times are in milliseconds

18       Array
218      Array as IList
26       List
223      List as IList
19       ArrayWrapper
188      ArrayWrapper as IList
```

Using an IList resulted in about an order of magnitude longer execution time than not using an IList. I wondered if some of this was due to the extra stuff the CLR does when accessing an Array or List as an IList, so I made a simple wrapper class around an array. This resulted in some improvement, but not much.

This virtually negates the advantage of something like accepting an IList<T> as a parameter instead of a T[] to decouple the code from any specific implementation. A new developer might expect that passing an object to a method accepting an IList would result in the same performance as if the method accepted that object's concrete type.

Is there any way to lessen this kind of performance loss? Or is it unavoidable without changing the JIT to be able to inline virtual calls?

category:cq
theme:devirtualization
skill-level:expert
cost:large
impact:large

**Comment by mangod9** [comment]
@AndyAyersMS the last question here was about whether its possible to inline indirect calls. Should this be moved to codegen area for future consideration?

**Comment by AndyAyersMS** [comment]
Sure ... we are slowly building up the needed tech to improve here.

Didn't reread all the upthread but one of the things that can get overlooked is that optimizing the cost of the dispatch is not the real prize -- it's being able to inline the method being called, and all the knock-on optimizations that enables.

**Comment by AndyAyersMS** [comment]
@Thealexbarney if you still have those original tests around I have some changes to try out (see #43607). On your simple test above I get numbers like:

```
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.572 (2004/?/20H1)
Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.100-rc.2.20479.15
  [Host]     : .NET Core 5.0.0 (CoreCLR 5.0.20.47505, CoreFX 5.0.20.47505), X64 RyuJIT
  Job-BMVYOC : .NET Core 5.0 (CoreCLR 42.42.42.42424, CoreFX 42.42.42.42424), X64 RyuJIT

EnvironmentVariables=COMPlus_TieredPgo=1,COMPlus_JitEnableGuardedDevirtualization=1,COMPlus_JitClassProfiling=1,COMPlus_TC_QuickJitForLoops=1  Toolchain=CoreRun  IterationCount=20

```
|         Method |     Mean |    Error |   StdDev | Code Size |
|--------------- |---------:|---------:|---------:|----------:|
|   RunInterface | 54.36 ms | 2.801 ms | 3.113 ms |     572 B |
| RunNoInterface | 49.08 ms | 4.439 ms | 5.112 ms |     357 B |

**Comment by Thealexbarney** [comment]
The only tests I still have around now are the gists I posted on this issue. [Gist 1](https://gist.github.com/Thealexbarney/ecd8f08aed994cd8c9076475b06cab07) [Gist 2](https://gist.github.com/Thealexbarney/1ef65271b88a8c20aa2428a3c1a95eef)

I've read your PGO docs over the past week or two and I've been interested in seeing the improvements it would bring. The numbers from your prototype are already looking pretty good.

**Comment by Uzivatel919** [comment]
Speed of _List<T>_ indexer is not good in any case so taking it for performance critical test where virtual calls are taken into consideration is little awkward. ([Array vs. List Performance](https://www.jacksondunstan.com/articles/3058))

@Thealexbarney You pointed out JVM capability that make these thing fine but you did can just make you way using abstract classes.

```
public abstract class AC<T>
{
    public abstract T this[int index] { get; set; }
}

public class PerfAbstractedArray<T> : AC<T>
{
    private readonly T[] valuesMadeToArray;

    public PerfAbstractedArray(T[] valuesMadeToArray)
    {
        this.valuesMadeToArray = valuesMadeToArray;
    }

    public override T this[int index] 
    {
        get => valuesMadeToArray[index];
        set => valuesMadeToArray[index] = value;
    }
}

public class PerfAbstractedList<T> : AC<T>
{
    private readonly T[] valuesMadeToList;

    public PerfAbstractedList(T[] valuesMadeToList)
    {
        this.valuesMadeToList = valuesMadeToList;
    }

    public override T this[int index]
    {
        get => valuesMadeToList[index];
        set => valuesMadeToList[index] = value;
    }
}
```

FMPOV framework guidelines are fit for particular purpose so if you are interested in performance you are going to be tuner all the time. Even in the future. Other told well there are trade-offs, costs and priorities. On the other hand autogained performance for no research is not hurting nobody at all.

**Comment by AndyAyersMS** [comment]
Things continue to look good with recent builds and TieredPGO (and TC_QuickJitForLoops). The tests linked above do a fair amount of work per iteration (`sqrt`) so it is possible with PGO to get close to the direct call perf.

If the work payload is cut down to something like an integer sum reduction, we can see the residual costs more clearly
```C#
            for (int i = 0; i < length; i++)
            {
                r += a[i] + b[i];
            }
```
and here the PGO version is about 2x slower.

|         Method |     Mean |    Error |   StdDev |
|--------------- |---------:|---------:|---------:|
|   RunInterface | 25.71 us | 0.476 us | 0.446 us |
| RunNoInterface | 11.33 us | 0.224 us | 0.210 us |

BDN results can be a bit inconsistent at times, however. I am not sure why.

```asm
;; no-interface inner loop (both PGO and no PGO)
G_M44880_IG03:              ;; offset=0015H
       443BD1               cmp      r10d, ecx
       7338                 jae      SHORT G_M44880_IG07
						;; bbWeight=10000.90 PerfScore 12501.13
G_M44880_IG04:              ;; offset=001AH
       4C8B5A08             mov      r11, gword ptr [rdx+8]
       453B5308             cmp      r10d, dword ptr [r11+8]
       7334                 jae      SHORT G_M44880_IG08
       4963F2               movsxd   rsi, r10d
       458B5CB310           mov      r11d, dword ptr [r11+4*rsi+16]
       453B5010             cmp      r10d, dword ptr [r8+16]
       7320                 jae      SHORT G_M44880_IG07
						;; bbWeight=10000.90 PerfScore 102509.25
G_M44880_IG05:              ;; offset=0032H
       4103C3               add      eax, r11d
       4D8B5808             mov      r11, gword ptr [r8+8]
       453B5308             cmp      r10d, dword ptr [r11+8]
       7319                 jae      SHORT G_M44880_IG08
       410344B310           add      eax, dword ptr [r11+4*rsi+16]
       41FFC2               inc      r10d
       453BD1               cmp      r10d, r9d
       7CC9                 jl       SHORT G_M44880_IG03
```

```asm
;; interface dot-product innner loop (no PGO)

G_M18393_IG03:              ;; offset=0030H
       488BCE               mov      rcx, rsi
       418BD6               mov      edx, r14d
       49BBF004A443FC7F0000 mov      r11, 0x7FFC43A404F0
       FF158A4CC8FF         call     [IList`1:get_Item(int):int:this]
       448BF8               mov      r15d, eax
       488BCF               mov      rcx, rdi
       418BD6               mov      edx, r14d
       49BBF804A443FC7F0000 mov      r11, 0x7FFC43A404F8
       FF15794CC8FF         call     [IList`1:get_Item(int):int:this]
       4103EF               add      ebp, r15d
       03E8                 add      ebp, eax
       41FFC6               inc      r14d
       443BF3               cmp      r14d, ebx
       7CC4                 jl       SHORT G_M18393_IG03
```

```asm
;; interface dot-product inner loop (PGO)

G_M18393_IG04:              ;; offset=0039H
       48B8D016D343FC7F0000 mov      rax, 0x7FFC43D316D0    ;; test type of "a"
       483BD8               cmp      rbx, rax
       0F8591000000         jne      G_M18393_IG13
       488BC7               mov      rax, rdi
       443B7810             cmp      r15d, dword ptr [rax+16]    ;; length check
       0F83A2000000         jae      G_M18393_IG14
						;; bbWeight=10006.84 PerfScore 47532.50
G_M18393_IG05:              ;; offset=0059H
       488B4708             mov      rax, gword ptr [rdi+8]
       443B7808             cmp      r15d, dword ptr [rax+8]    ;; bounds check
       0F83B5000000         jae      G_M18393_IG16
       4963CF               movsxd   rcx, r15d
       448B648810           mov      r12d, dword ptr [rax+4*rcx+16]    ;; fetch element "a"
						;; bbWeight=10006.84 PerfScore 72549.60
G_M18393_IG06:              ;; offset=006FH
       48B8D016D343FC7F0000 mov      rax, 0x7FFC43D316D0     ;; test type of "b"
       483906               cmp      qword ptr [rsi], rax
       0F857F000000         jne      G_M18393_IG15
						;; bbWeight=10006.84 PerfScore 32522.24
G_M18393_IG07:              ;; offset=0082H
       488BC6               mov      rax, rsi
       443B7810             cmp      r15d, dword ptr [rax+16]     ;; length check
       7370                 jae      SHORT G_M18393_IG14
						;; bbWeight=10006.84 PerfScore 32522.24
G_M18393_IG08:              ;; offset=008BH
       488B4608             mov      rax, gword ptr [rsi+8]
       443B7808             cmp      r15d, dword ptr [rax+8]     ;; bounds check
       0F8383000000         jae      G_M18393_IG16
       4963CF               movsxd   rcx, r15d
       448B6C8810           mov      r13d, dword ptr [rax+4*rcx+16]    ;; fetch element b
						;; bbWeight=10006.84 PerfScore 72549.60
G_M18393_IG09:              ;; offset=00A1H
       4503F4               add      r14d, r12d
       4503F5               add      r14d, r13d
       41FFC7               inc      r15d
       443BFD               cmp      r15d, ebp
       7C8A                 jl       SHORT G_M18393_IG04

;; cold blocks 13 and 15 (not shown) make the residual interface calls if the type tests fail.
```
Compared with the no-interface version, the extra overhead in the PGO version comes from the two type checks and the slightly more expensive test against `a.Count`. That plus higher branch density (though all but the last should be not taken) and larger code likely explains the perf cost.

Note in the non-interface version `a.Count()` is treated as a loop invariant; it is not treated that way in the optimized PGO loop (possibly this is a dependent LICM hoist, ala #35735?).

Also in the PGO loop above we don't hoist the type fetch for `b` because of all the potential exceptions (that is if `b` is `null`) we don't want to check its type too early. This is an example where loop peeling (while costly) would unblock CSEs, as all those first-iteration exceptions would happen outside the loop. But it would be a lot of duplicated code.

As an alternative  with less code duplication we could clone / unswitch on the type tests... that is instead of producing
```C#
for (...)
{
     if (a.GetType() == typeof(...))
     ...
     if (a.GetType() == typeof(...))
     ...
}
```
we'd produce
```C#
if ((a.GetType() == typeof(...)) && (b != null) && (b.GetType() == typeof(...)))
{
     for (...)    //  no type checks or interface calls
}
else
{
    for (...)   // interface calls
}
```
I'm going to keep this open for now but don't expect much to change for the remainder of 6.0, so will move to future.

cc @BruceForstall

**Comment by Uzivatel919** [comment]
@Thealexbarney,

I made up some simple quick tests using tight loop as you designed it. It seems that at least at my configuration I get ⅓ better resolution with abstract class design (compared to interface design). I guess it is not enough for you case. 👎🏻

```
public abstract class MyCollectionBase {
	public abstract int Length { get; }
	public abstract int this [int i] { get; }
}
public interface IMyCollection {
	public int Length { get; }
	public int this [int i] { get; }
}
public class MyCollection : MyCollectionBase, IMyCollection {
	readonly int[] ints;
	public MyCollection ( int [] ints ) => this.ints = ints;
	public override int Length => ints.Length;
	public override int this [int i] => ints[i];
}
```

Even better results I get for the generics. Circa ½.

```
public abstract class MyCollectionBase<T> {
    public abstract int Length { get; }
    public abstract T this [int i] { get; }
}
public interface IMyCollection<T> {
	public int Length { get; }
	public T this [int i] { get; }
}
public class MyCollectionOfT<T> : MyCollectionBase<T>, IMyCollection<T> {
	T[] ints;
	public MyCollectionOfT ( T [] ints ) => this.ints = ints;
	public override int Length => ints.Length;
	public override T this [int i] => ints [i];
}
 ```
 
 … still the burden is 5× for virtual method in generics case (while interface takes 10×).

**Comment by benaadams** [comment]
Running the LinqBenchmarks at https://github.com/NetFabric/LinqBenchmarks; the improvement for `IEnumerable<int>` is very significant:

[EnumerableInt32Select](https://github.com/NetFabric/LinqBenchmarks/blob/master/LinqBenchmarks/Enumerable/Int32/EnumerableInt32Select.cs)

|               Method |              EnvironmentVariables |  Runtime | Count |         Mean | Ratio | Allocated |
|--------------------- |---------------------------------- |--------- |------ |-------------:|------:|----------:|
|          ForeachLoop |                                 - | .NET 5.0 |  1000 |  4,114.66 ns |  1.00 |      40 B |
|          ForeachLoop | TC_QuickJitForLoops=1,TieredPGO=1 | .NET 6.0 |  1000 |  3,109.91 ns |  0.76 |      40 B |
|                 Linq |                                 - | .NET 5.0 |  1000 | 10,036.04 ns |  2.44 |      96 B |
|                 Linq | TC_QuickJitForLoops=1,TieredPGO=1 | .NET 6.0 |  1000 |  5,429.17 ns |  1.32 |      96 B |
|               LinqAF |                                 - | .NET 5.0 |  1000 |  6,956.42 ns |  1.69 |      40 B |
|               LinqAF | TC_QuickJitForLoops=1,TieredPGO=1 | .NET 6.0 |  1000 |  4,926.36 ns |  1.20 |      40 B |
|           StructLinq |                                 - | .NET 5.0 |  1000 |  5,805.81 ns |  1.41 |      64 B |
|           StructLinq | TC_QuickJitForLoops=1,TieredPGO=1 | .NET 6.0 |  1000 |  3,631.02 ns |  0.88 |      64 B |
| StructLinq_IFunction |                                 - | .NET 5.0 |  1000 |  4,140.51 ns |  1.01 |      40 B |
| StructLinq_IFunction | TC_QuickJitForLoops=1,TieredPGO=1 | .NET 6.0 |  1000 |  2,867.47 ns |  0.70 |      40 B |
|            Hyperlinq |                                 - | .NET 5.0 |  1000 |  5,916.27 ns |  1.44 |      40 B |
|            Hyperlinq | TC_QuickJitForLoops=1,TieredPGO=1 | .NET 6.0 |  1000 |  3,845.47 ns |  0.93 |      40 B |
|  Hyperlinq_IFunction |                                 - | .NET 5.0 |  1000 |  4,128.19 ns |  1.00 |      40 B |
|  Hyperlinq_IFunction | TC_QuickJitForLoops=1,TieredPGO=1 | .NET 6.0 |  1000 |  3,115.01 ns |  0.76 |      40 B |

**Comment by AndyAyersMS** [comment]
@benaadams thanks for the ongoing interest in PGO!

FWIW I am starting to look at impact of PGO on various TechEmpower scenarios. Some seem to speed up nicely (plaintext/mvc), others not so much (json)... suspect we're not seeing anywhere near the full potential yet.

**Comment by benaadams** [comment]
> various TechEmpower scenarios. Some seem to speed up nicely (plaintext/mvc), others not so much (json)... 

.NET 6.0 + PGO allows "Ben"; essentially a Kestrel stack, to pull ahead of the lighter .NET 5.0 "platform" on the TE database tests 😎

![image](https://user-images.githubusercontent.com/1142958/114467313-a69a2980-9be1-11eb-9e36-d8dd377fddba.png)

>  suspect we're not seeing anywhere near the full potential yet.

Love to hear it 💜

**Comment by AndyAyersMS** [comment]
Json 😢 

![image](https://user-images.githubusercontent.com/10121823/114469713-84cd8200-9ba2-11eb-8d07-eed84e9a2c08.png)

**Comment by benaadams** [comment]
> Json 😢

Isn't like for like; for Json "platform" is using 3 additional options:
* `DOTNET_SYSTEM_NET_SOCKETS_INLINE_COMPLETIONS = 1`
* `UnsafePreferInlineScheduling = true`
* `WaitForDataBeforeAllocatingBuffer = false`

Whereas "Ben" is just using the vanilla defaults; and implementation-wise its closer to "middleware" than "platform" (was mostly a demonstration that the ASP.NET Core stack was layered well enough that you could build a stack on top of Kestrel without having to "buy-in" to its opinionated Dependency Injection and Hosting model)

**Comment by AndyAyersMS** [comment]
So that's good news, then? Is this with recent builds?

**Comment by benaadams** [comment]
> So that's good news, then?

Yes. its fairly miraculous it overtook "platform" in the DB Single Query; expected it to be a little faster than "middleware"; but... 😲

> Is this with recent builds?

Is using the public releases; so I assume is preview 3?

Docker settings are
```
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
ENV COMPlus_ReadyToRun 0
ENV COMPlus_TC_QuickJitForLoops 1
ENV COMPlus_TieredPGO 1
```
Though might not need to switch off ReadyToRun anymore?

**Comment by AndyAyersMS** [comment]
My hope is that we can eventually drop the need for ` COMPlus_ReadyToRun=0`  without losing too much perf. Hard to be sure just yet how things will play out. Each preview should be better than the one before.

For 6p4 ` COMPlus_ReadyToRun=0` should be less important for apps that spend a good deal of time in core framework code, as we aim to have static PGO data for key prejitted methods.

By 6p6 we plan have static PGO data flowing into ASP.NET assemblies as well, and maybe by then we ccan ease off `COMPlus_ReadyToRun=0` for TE scenarios.

With current main the gap between enabling R2R and disabling on TE it is still pretty large, at least in my measurements. For example plaintext/mvc is 18% faster with the options above, but only 1% faster if R2R is left enabled.

I need to do more investigation into what all needs fixing and where these numbers should be; that's going to be my focus for the next few weeks.

**Comment by AndyAyersMS** [comment]
cc @davidfowl since Julie says you want to know what we're up to over here.

**Comment by mangod9** [comment]
why is `COMPlus_ReadyToRun=0` required? Shouldnt Tiering replace the R2R methods?

**Comment by benaadams** [comment]
> why is `COMPlus_ReadyToRun=0` required? Shouldnt Tiering replace the R2R methods?

Lack of PGO data for the R2R methods; switching it off runs them at Tier0 which generates the PGO data for Tier1

**Comment by HyVong007** [comment]
Using the Interface vs using the specific type (class/struct) always have tradeoffs. So can i inline my method of a class which impl an interface ? So when i use the interface, JIT Compiler will inline my method if the interface is my class ? 
I use attribute  System.Runtime.CompilerServices.MethodImpl(MethodImplOptions.AggressiveInlining) for the method and it will be inlined ?

What are the criterias for the method to be inlined ? always inlined ?

Sorry for my bad english.

**Comment by AndyAyersMS** [comment]
@HyVong007 thanks for the questions. Let me know if the information below helps.

### Devirtualization

Generally if the jit can determine the type of the `this` object at an interface call, it can devirtualize and then potentially inline. There are two main mechanisms for determining types:
* deduce the type from flow analysis within a method
* enable PGO, have that observe the possible types for `this`, and then test for the most likely type when rejitting or in a future run of the process.

Last I looked flow analysis can enable devirualization and inlining in a relatively small fraction of interface call cases (say no more than 10%). Success here requires that there be some "organic" evidence of type identity (constructor call or type test) upstream from the interface site. Inlining can help bring together the needed information but currently the inlining heuristics do not include increased devirtualization potential as part of their evaluation. That may change soon (see eg #53670).

PGO is quite effective at devirtualizing interface calls; most studies I have done show upwards of 80% of interface call sites have one dominant implementing class for `this`.

### Inlining

The inlining heuristics are complicated and difficult to summarize concisely. Roughly speaking a method will be inlined if:
* there is a direct call to the method, OR the jit can devirtualize an interface or virtual call, AND
  * the method being invoked is small (16 bytes of IL or fewer), OR
  * the method being invoked is marked with `AggressiveInlining`, OR
  * the method is medium sized (17 to ~100 bytes of IL) and the inline heuristics determine the inline is worthwhile

**Comment by HyVong007** [comment]
> @HyVong007 thanks for the questions. Let me know if the information below helps.
> 
> ### Devirtualization
> Generally if the jit can determine the type of the `this` object at an interface call, it can devirtualize and then potentially inline. There are two main mechanisms for determining types:
> 
> * deduce the type from flow analysis within a method
> * enable PGO, have that observe the possible types for `this`, and then test for the most likely type when rejitting or in a future run of the process.
> 
> Last I looked flow analysis can enable devirualization and inlining in a relatively small fraction of interface call cases (say no more than 10%). Success here requires that there be some "organic" evidence of type identity (constructor call or type test) upstream from the interface site. Inlining can help bring together the needed information but currently the inlining heuristics do not include increased devirtualization potential as part of their evaluation. That may change soon (see eg #53670).
> 
> PGO is quite effective at devirtualizing interface calls; most studies I have done show upwards of 80% of interface call sites have one dominant implementing class for `this`.
> 
> ### Inlining
> The inlining heuristics are complicated and difficult to summarize concisely. Roughly speaking a method will be inlined if:
> 
> * there is a direct call to the method, OR the jit can devirtualize an interface or virtual call, AND
>   
>   * the method being invoked is small (16 bytes of IL or fewer), OR
>   * the method being invoked is marked with `AggressiveInlining`, OR
>   * the method is medium sized (17 to ~100 bytes of IL) and the inline heuristics determine the inline is worthwhile

Ok thank you, i understand something now. And here for some example i found, which cases will be inlined ? Thank so much !

`public int a { get; set; } // 1

	private int bakingField;
	public int b => bakingField; // 2

	public int c // 3
	{
		get => bakingField;
		set => bakingField = value;
	}

	public int Method() => a; // 4

	public int Method2() => a > 0 ? a : b; // 5

	public int Method3(int i, float f, string s, char c) => a * 2 + 5 - 7 + b; // 6
`

**Comment by tanveerbadar** [comment]
A long time has passed since this thread was opened. I am wondering how big of a difference still remains with all the improvements going in JIT like PGO, OSR, tiered compilation, GDV, frozen object heap and what-nots.

**Comment by maximilien-noal** [comment]
```
First run: .NET 8.
Second run: .NET 7

C:\Users\max>cd source && cd repos && mkdir perftest && cd perftest && dotnet new console
Le modèle « Application console » a bien été créé.

Traitement des actions postérieures à la création en cours... Merci de patienter.
Restauration de C:\Users\max\source\repos\perftest\perftest.csproj :
  Identification des projets à restaurer...
  Restauration effectuée de C:\Users\max\source\repos\perftest\perftest.csproj (en 493 ms).
Restauration réussie.

C:\Users\max\source\repos\perftest>notepad program.cs

C:\Users\max\source\repos\perftest>dotnet run -c Release
Direct: 1019ms
As base class: 1003ms
As interface: 1082ms

C:\Users\max\source\repos\perftest>notepad perftest.csproj

C:\Users\max\source\repos\perftest>dotnet run -c Release
Direct: 1048ms
As base class: 2329ms
As interface: 3888ms 

```

Seems pretty good to me.

Test program:
```

namespace PerfTest;

using System.Diagnostics;

internal static class Program {
    public static void Main(string[] args) {
        var sw = new Stopwatch();
        const int iterations = int.MaxValue;

        var direct = new Tester();
        ISlowThingsDown asInterface = direct;
        var asBaseClass = asInterface as MyAbstractBaseClass;

        sw.Start();
        for (int i = 0; i < iterations; i++) {
            direct.Property = i;
        }
        Console.WriteLine($"Direct: {sw.ElapsedMilliseconds}ms");
        sw.Restart();
        for (int i = 0; i < iterations; i++) {
            asBaseClass!.Property = i;
        }
        Console.WriteLine($"As base class: {sw.ElapsedMilliseconds}ms");
        sw.Restart();
        for (int i = 0; i < iterations; i++) {
            asInterface.Property = i;
        }
        Console.WriteLine($"As interface: {sw.ElapsedMilliseconds}ms");
        sw.Stop();
    }
}

public interface IAmBaseInterface {
    public long Property { set; }
}

public interface ISlowThingsDown : IAmBaseInterface {
}

public class Tester : MyAbstractBaseClass, ISlowThingsDown {
}

public abstract class MyAbstractBaseClass : IAmBaseInterface {
    public long Property { get; set; }
}
```

Maybe it's possible to measure this with Benchmark.net instead ?

This is left as an exercise to the reader.

**Comment by jkotas** [comment]
Your micro-benchmark showcases profile guided devirtualization and inlining. Yes, we made a lot of progress improving various cases discussed here and we will continue the improvements.  

I do not see anything concrete actionable left in this issue. Closing.
