### ISSUE TITLE
WindowsServiceHelpers.IsWindowsService() always returns false on Windows Server 2022

### ISSUE THREAD

**Issue by twofingerrightclick** [dotnet/runtime#72915]
### Description

WindowsServiceHelpers.IsWindowsService() returns false on Windows Server 2022 when the app is initiated from a service.

### Reproduction Steps

Create a service that starts a dotnet exe. Start the service and log the whether or not the app is running via service via `WindowsServiceHelpers.IsWindowsService()`. Then view the output in windows system event viewer.

### Expected behavior

If a dotnet app is running from a service on Windows Server 2022 calls to `WindowsServiceHelpers.IsWindowsService()` should return true.

### Actual behavior

If a dotnet app is running from a service on Windows Server 2022 calls to `WindowsServiceHelpers.IsWindowsService()` return false.

### Configuration

net 6.0 
winx64

**Comment by ericstj** [comment]
Here's the pattern that this library uses to implement the API:
https://github.com/dotnet/runtime/blob/9a0b8f339ddb5cd6d4f7e8c333afc9a74dc545e5/src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceHelpers.cs#L27-L32

I suspect that either a) the process doesn't have the right privileges to get the parent process or b) the name of the parent process changed.

Regardless that seems like a pretty fragile heuristic.  I wonder what task manager go to service does?  Perhaps it enumerates service Process IDs to find the ones that match the current process ID.  Probably that could be done using https://docs.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-queryservicestatusex with https://docs.microsoft.com/en-us/dotnet/api/system.serviceprocess.servicecontroller.servicehandle?view=dotnet-plat-ext-6.0 for each service returned from https://docs.microsoft.com/en-us/dotnet/api/system.serviceprocess.servicecontroller.getservices?view=dotnet-plat-ext-6.0.  It would be important to understand why that wasn't done to begin with.

**Comment by danmoseley** [comment]
@twofingerrightclick Could you write a small console app that pinvokes to GetParentProcess (as in the first link above - you can paste in what you need from this repo) and let us know what you get? And if it's not null, use the handle to find out what the process name is?

**Comment by danmoseley** [comment]
In the meantime this may work for you as an alternative:

https://docs.microsoft.com/en-us/dotnet/api/system.environment.userinteractive?view=net-6.0#system-environment-userinteractive

**Comment by eerhardt** [comment]
@twofingerrightclick - what version of .NET and `Microsoft.Extensions.Hosting.WindowsServices` are you using? There have been some changes in 7.0 that could be affecting this.

**Comment by twofingerrightclick** [comment]
Thank you for the suggestions. I apologize, but I was told by a colleague this was an issue... I have taken the time to investigate and spun up a server a 2022 vm, and the results are that `WindowsServiceHelpers.IsWindowsService()` is returning true when the parent process is "service".
"Microsoft.Extensions.Hosting.WindowsServices" Version="6.0.0"
