### ISSUE TITLE
./src/tests/build.sh: No such file or directory

### ISSUE THREAD

**Issue by monstercatss** [dotnet/runtime#72921]
![image](https://user-images.githubusercontent.com/45393763/181199267-e1884c19-1b37-40fd-a236-6fca79b32eda.png)
 Im build the libraries subset (-subset libs)    , ./build.sh libs,but i cant find build.sh in ./src/tests
![image](https://user-images.githubusercontent.com/45393763/181199974-e2b9c4db-c8d9-448e-94e8-0b2479fc9b03.png)
but i can find output in /CORE_ROOT

**Comment by monstercatss** [comment]
linux

**Comment by ViktorHofer** [comment]
cc @trylek

**Comment by AaronRobinsonMSFT** [comment]
@monstercatss The file is in the repo and can be observed at https://github.com/dotnet/runtime/blob/main/src/tests/build.sh. Is it possible execute permissions aren't set on the file?

**Comment by ViktorHofer** [comment]
The execution permissions are correctly set:

```sh
vihofer:~/git/runtime$ ls -l src/tests/build.sh
-rwxr-xr-x 1 vihofer vihofer 13863 Jul 28 15:24 src/tests/build.sh
```

**Comment by AaronRobinsonMSFT** [comment]
@monstercatss Is it possible some part of the repo is missing or has been accidently deleted?

**Comment by monstercatss** [comment]
> 
I try  build v5.0.8 ，its build-tests.sh,w

**Comment by AaronRobinsonMSFT** [comment]
> I try build v5.0.8 ，its build-tests.sh,w

@monstercatss I don't understand this response. Are you starting from a full clone of this repo? I recommend going to the root of your repo, stashing any current work, and running `git checkout .`.
