### ISSUE TITLE
Assertion failed 'retVal->OperIs(GT_LCL_VAR)' during 'Lowering nodeinfo'

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#72926]
Hit in recent jitstress-isas-arm run.
Pipeline run: https://dev.azure.com/dnceng/public/_build/results?buildId=1905701&view=results
Test failure: https://dev.azure.com/dnceng/public/_build/results?buildId=1905701&view=ms.vss-test-web.build-test-results-tab&runId=49527848&resultId=109615&paneView=debug
Console log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72893-merge-0992787cb8a6487f81/JIT.Directed/1/console.03ebb829.log?helixlogtype=result

```scala
    JIT/Directed/StructABI/structreturn/structreturn.sh [FAIL]
      
      Assert failure(PID 2630 [0x00000a46], Thread: 2630 [0x0a46]): Assertion failed 'retVal->OperIs(GT_LCL_VAR)' in 'TestHFAandHVA:ReturnVector64Double():System.Runtime.Intrinsics.Vector64`1[Double]' during 'Lowering nodeinfo' (IL size 15; hash 0xdb77c6ef; FullOpts)
      
          File: /__w/1/s/src/coreclr/jit/lower.cpp Line: 3605
          Image: /root/helix/work/correlation/corerun
```

**Comment by jakobbotsch** [comment]
Introduced by fb1d318935e57c48e6d018d67b2bade74e020cef, cc @EgorBo

**Comment by EgorBo** [comment]
Hard to say how a x86 only change affected arm here

**Comment by jakobbotsch** [comment]
> Hard to say how a x86 only change affected arm here

Maybe it's the managed changes? Or maybe I messed up the bisection.

**Comment by SingleAccretion** [comment]
Simple reproduction:
```cs
private static Vector64<double> Problem()
{
    var value = 0l;
    return Unsafe.As<long, Vector64<double>>(ref value);
}
```

Testing a fix right now.
