### ISSUE TITLE
Marshal.PtrToStructure<T>(IntPtr) throws NullReferenceException if IntPtr.Zero is used

### ISSUE THREAD

**Issue by pluskal** [dotnet/runtime#72929]
### Description

According to [documentation/remarks](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.ptrtostructure?view=net-6.0#system-runtime-interopservices-marshal-ptrtostructure-1(system-intptr)) `Marshal.PtrToStructure<T>` shoul accept `value types`.

> [PtrToStructure<T>(IntPtr)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.ptrtostructure?view=net-6.0#system-runtime-interopservices-marshal-ptrtostructure-1(system-intptr)) is often necessary in COM interop and platform invoke when structure parameters are represented as [System.IntPtr](https://docs.microsoft.com/en-us/dotnet/api/system.intptr?view=net-6.0) values. You can pass a value type to this method overload. If the ptr parameter equals [IntPtr.Zero](https://docs.microsoft.com/en-us/dotnet/api/system.intptr.zero?view=net-6.0), null will be returned.

Calling `Marshal.PtrToStructure<T>` with `IntPtr.Zero` throws `NullReferenceException` instead of returning `null`.

### Reproduction Steps

```
using System.Runtime.InteropServices;

public class MarshalPtrToStructureTests
{
    public struct MyStruct
    {
    }
    
    [Fact]
    public void IntPtrZero_PtrToStructureMyStruct_ShouldBeNull()
    {
       Assert.Null(Marshal.PtrToStructure<MyStruct>(IntPtr.Zero));
    }
}
```

### Expected behavior

`Marshal.PtrToStructure<T>` to return `null`

### Actual behavior

Throws `NullReferenceException`

### Regression?

Same behavior on .NET 3.1, .NET 5.

### Known Workarounds

Explicit null check

### Configuration

```
> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.302
 Commit:    c857713418

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.302\

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  6.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by huoyaoyuan** [comment]
> ### Expected behavior
> `Marshal.PtrToStructure<T>` to return `null`

Technically, it does return `null`, and the `NullReferenceException` happens when trying to cast the `null` to the `struct`.
You can observe this by trying `(MyStruct)(object)(null)`.

The behavior is by design, since there's no way to represent `null` for a value type. The documentation may get updated, but there are much more scenarios. For example, `JsonSerializer.Deserialize<T>("null")` will throw `NullReferenceException` if T is a value type, which isn't mentioned by the document.

By the way, the whole `PtrToStructure` family is highly legacy and should be avoided in new applications. You can just declare a pointer or `ref` to your structure if it contains only blittable data.

**Comment by hez2010** [comment]
What you are doing is dereferencing a zero pointer, which definitely yields a NRE.

**Comment by AaronRobinsonMSFT** [comment]
> According to [documentation/remarks](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.ptrtostructure?view=net-6.0#system-runtime-interopservices-marshal-ptrtostructure-1(system-intptr)) Marshal.PtrToStructure<T> shoul accept value types.

> The documentation may get updated, but there are much more scenarios. 

Right, I think the documentation should be updated.

**Comment by AaronRobinsonMSFT** [comment]
Documentation update PR https://github.com/dotnet/dotnet-api-docs/pull/8261
