### ISSUE TITLE
`BrotliCompress` task uses only timestamp to decide which files to skip

### ISSUE THREAD

**Issue by ahmed-salem-me** [dotnet/runtime#72938]
### Description

This is a question and if not present then a feature request.

Does aot compilation utilize a cache of aot'ed compiled assemblies?

With the current very long time it takes to do aot compilation, can't there be some sort of cache of precompiled assemblies that have not changed?
Having to compile a 100 assemblies when only one has changed is an absolute time killer, specially when you're investigating performance and need aot to disable native strip of function names.

### Reproduction Steps

- Compile/publish aot two projects that use the same exact packages
takes double amount of time

### Expected behavior

previously aote'd assemblies that has not changed should be used

### Actual behavior

aot every time

### Configuration

.net 7 preview 5

**Comment by fanyang-mono** [comment]
@vargaz Any thoughts?

**Comment by vargaz** [comment]
There is caching done during the wasm AOT build. However, AOT images currently depend on the exact versions of their input assemblies and the assemblies referenced, so if something changes they need to be recompiled. Another issue is that the linker creates one of a kind assemblies so it's hard to share them between projects.

**Comment by ahmed-salem-me** [comment]
> There is caching done during the wasm AOT build. However, AOT images currently depend on the exact versions of their input assemblies and the assemblies referenced, so if something changes they need to be recompiled. Another issue is that the linker creates one of a kind assemblies so it's hard to share them between projects.

If by input assemblies you mean my project assemblies or any assemblies they reference, then I don't really notice caching happening for them, otherwise the compilation would have been very fast in subsequent publishing.

One proof of this, is that publishing the exact same project two times without making any changes, take roughly the same time to publish.
Or changing one single line in one single assembly, still roughly takes the same time.

**Comment by radical** [comment]
Can you share the binlogs for:

1. Clean publish
2. Second publish with no changes
3. Publish with the one line change that you mentioned.

**Comment by ahmed-salem-me** [comment]
> Can you share the binlogs for:
> 
> 1. Clean publish
> 2. Second publish with no changes
> 3. Publish with the one line change that you mentioned.

@radical , Everytime you ask me to give you a binlog from an aot publish, I ask you the same question with no answer from you, how can I do an aot publish from a command line??
the following doesn't seem to actually publish :
msbuild OpenSilverApp.Browser.csproj -bl:msbuild.binlog -p:DeployOnBuild=true -p:publishprofile=aot.w2xp

here is the publish profile file and binlog for above command
[profile-and-binlog.zip](https://github.com/dotnet/runtime/files/9397381/profile-and-binlog.zip)

Again, this takes about 3 mins and finishes with no errors and doesn't do any publishing to the folder specified in the publish profile !!!

**Comment by radical** [comment]
Sorry I seem to have missed your question.

To publish from command line:
`dotnet publish -bl -p:RunAOTCompilation=true`

**Comment by ahmed-salem-me** [comment]
@radical no worries, ok that seem to publish but it doesn't pick the publishprofile param and so donesn't publish to desired folder , any ideas?
Anyway here are the binlogs for the 3 builds , not much caching if any seems to be happening
[binlogs for 3 aot builds.zip](https://github.com/dotnet/runtime/files/9403746/binlogs.for.3.aot.builds.zip)

**Comment by radical** [comment]
The second, and third builds are AOT'ing only 2 assemblies, and the rest are skipped because of caching.

This is the second publish:
```
  AOT'ing 118 assemblies
  [1/117] OS.Test.Tlrk.Browser_withoutTelerik.dll -> OS.Test.Tlrk.Browser_withoutTelerik.dll.bc
  [2/117] OS.Test.Tlrk_withoutTelerik.dll -> OS.Test.Tlrk_withoutTelerik.dll.bc
  [115/117] skipped unchanged assemblies.
  Compiling native assets with emcc with -O0 -s ASSERTIONS=0. This may take a while ...
  Compiling assembly bitcode files with -O0 -s ASSERTIONS=0 ...
  [1/2] OS.Test.Tlrk.Browser_withoutTelerik.dll.bc -> OS.Test.Tlrk.Browser_withoutTelerik.dll.o [took 0.55s]
  [2/2] OS.Test.Tlrk_withoutTelerik.dll.bc -> OS.Test.Tlrk_withoutTelerik.dll.o [took 3.21s]
  Linking with emcc with -O0 -s ASSERTIONS=0. This may take a while ...
   "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.7.Sdk.win-x64\7.0.0-preview.6.22320.1\tools\bin\wasm-ld.exe" @C:\Users\ams\AppD>
   "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.7.Sdk.win-x64\7.0.0-preview.6.22320.1\tools\bin\wasm-emscripten-finalize" -g -->
   "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.7.Node.win-x64\7.0.0-preview.6.22320.1\tools\bin\node.exe" "C:\Program Files\do>
   "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.7.Sdk.win-x64\7.0.0-preview.6.22320.1\tools\bin\llvm-objcopy.exe" D:\Userware\c
```

This is the 3rd publish:
```
  AOT'ing 118 assemblies
  [1/117] OS.Test.Tlrk.Browser_withoutTelerik.dll -> OS.Test.Tlrk.Browser_withoutTelerik.dll.bc
  [2/117] OS.Test.Tlrk_withoutTelerik.dll -> OS.Test.Tlrk_withoutTelerik.dll.bc
  [115/117] skipped unchanged assemblies.
  Compiling native assets with emcc with -O0 -s ASSERTIONS=0. This may take a while ...
  Compiling assembly bitcode files with -O0 -s ASSERTIONS=0 ...
  [1/2] OS.Test.Tlrk.Browser_withoutTelerik.dll.bc -> OS.Test.Tlrk.Browser_withoutTelerik.dll.o [took 0.52s]
  [2/2] OS.Test.Tlrk_withoutTelerik.dll.bc -> OS.Test.Tlrk_withoutTelerik.dll.o [took 2.92s]
  Linking with emcc with -O0 -s ASSERTIONS=0. This may take a while ...
   "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.7.Sdk.win-x64\7.0.0-preview.6.22320.1\tools\bin\wasm-ld.exe" @C:\Users\ams\AppD>
   "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.7.Sdk.win-x64\7.0.0-preview.6.22320.1\tools\bin\wasm-emscripten-finalize" -g -->
   "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.7.Node.win-x64\7.0.0-preview.6.22320.1\tools\bin\node.exe" "C:\Program Files\do>
   "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.7.Sdk.win-x64\7.0.0-preview.6.22320.1\tools\bin\llvm-objcopy.exe" D:\Userware\
```

.. but the `BrotliCompress` task seems to be compressing lot of assemblies because the timestamp of the linked assemblies has changed. In at least some of the cases the contents would likely be unchanged, so it should compare that too.

cc @TanayParikh @javiercn

**Comment by radical** [comment]
> how can I do an aot publish from a command line?? the following doesn't seem to actually publish : msbuild OpenSilverApp.Browser.csproj -bl:msbuild.binlog -p:DeployOnBuild=true -p:publishprofile=aot.w2xp

You need to pass `-p:RunAOTCompilation=true` here, to AOT during publish.

> publishProfile

@TanayParikh does blazor support this? Is there anything else needed to use this from command line?

**Comment by ahmed-salem-me** [comment]
@radical So you're saying it takes 20 mins to aot just 2 assemblies? that sounds like a lot
I tried with disabled blazor compression it took 6 mins, so is all this time really consumed by compression?

**Comment by javiercn** [comment]
@radical if the outputs did not change, the expectation from MSBuild in general is that you don't write the outputs again, otherwise you break incrementalism for targets that depend on your outputs.

**Comment by radical** [comment]
> @radical if the outputs did not change, the expectation from MSBuild in general is that you don't write the outputs again, otherwise you break incrementalism for targets that depend on your outputs.

Here on incremental builds, the compression is being run for a lot of assemblies that don't seem to have changed.

**Comment by radical** [comment]
> @radical So you're saying it takes 20 mins to aot just 2 assemblies? that sounds like a lot
> 
> I tried with disabled blazor compression it took 6 mins, so is all this time really consumed by compression?

Yeah. You can look at the timings with msbuildlog.com and the binlog that you have.

**Comment by javiercn** [comment]
> Here on incremental builds, the compression is being run for a lot of assemblies that don't seem to have changed.

But their timestamp has, hasn't it?

**Comment by radical** [comment]
> > Here on incremental builds, the compression is being run for a lot of assemblies that don't seem to have changed.
> 
> But their timestamp has, hasn't it?

Hm that's true. And for a compression task you don't have a "older" uncompressed file to compare against. Would it make sense to store the hashes, and compare those? Is incremental publish, a common scenario?

**Comment by javiercn** [comment]
@radical not when it comes to copying to the final folder (AFAIK, if you publish two times to the same folder, we do not guarantee that the output is correct, for example, we wouldn't remove files that were removed from the previous publish) but the pipeline in general should be/remain incremental otherwise.

WRT to the hashes, maybe that is something we could do if we have to (I believe we already compute the hashes anyway) but ideally, we shouldn't have to.

**Comment by radical** [comment]
If we don't support the scenario, then nothing needs to be done here.

Re:hashes, I meant store hashes when compressing, and next time you can compare with the old one to see the contents have changed.

**Comment by javiercn** [comment]
> **but the pipeline in general should be/remain incremental otherwise.**

**Comment by radical** [comment]
> > **but the pipeline in general should be/remain incremental otherwise.**

Ok, so should this moved to aspnetcore then?

**Comment by javiercn** [comment]
> Ok, so should this moved to aspnetcore then?

Our leg is already incremental, is our inputs that are changing even though their contents aren't that breaks incrementalism here.

We could address it at our layer by doing the hashing ourselves, but that's not something we want to be generally doing. Otherwise, we become responsible for implementing incrementalism from scratch on every leg of the build.

I don't think we would do work on our side to fix this, so I would suggest you evaluate how much you care about it to prioritize it accordingly. As far as I understand, the outputs are correct, it's more of an it takes longer than needed for the build to go through.

**Comment by radical** [comment]
I understand. This is all blazor, so I don't have any opinion here, simply facilitating the discussion.

**Comment by maraf** [comment]
Notes to myself `MonoAOTCompiler` -> `_WasmAssembliesInternal` -> `WasmAssembliesFinal` -> `WasmNestedPublishApp` returns `TargetOutputs` -> `WasmNestedPublishAppResultItems` -> `WasmNativeAsset`

**Comment by lewing** [comment]
@maraf what is the status here?

**Comment by maraf** [comment]
I want to check if you correctly set timestamp for AOT. I'll investigate it tomorrow

**Comment by maraf** [comment]
I'm going to close the issue the extra layer of caching is present in webcil transformation.
