### ISSUE TITLE
IdnMapping.GetAscii throws ArgumentException

### ISSUE THREAD

**Issue by lchen3-atlassian** [dotnet/runtime#72962]
### Description

I ran into `Decoded string is not a valid IDN name. (Parameter 'unicode')` when testing this string out.

```C#
using System;
using System.Globalization;
					
public class Program
{
	public static void Main()
	{
		string name = "testuser123+2m4v7kxvwqsry21ct6s+2t7epyi9agymtur55og+0vi7sk0xkz@test.example.com";
      	IdnMapping idn = new IdnMapping();
        try {
            string punyCode = idn.GetAscii(name);
            string name2 = idn.GetUnicode(punyCode);
			Console.WriteLine("CONVERTED: " + name2);
         }
         catch (ArgumentException e) {
            Console.WriteLine("{0} is not a valid domain name.", name);
			 Console.WriteLine(e);
         }
	}
}
```

### Reproduction Steps

To reproduce: 

1. Use current DotNet version
2. Get the ASCII from the string
3. ```testuser123+2m4v7kxvwqsry21ct6s+2t7epyi9agymtur55og+0vi7sk0xkz@test.example.com is not a valid domain name.
System.ArgumentException: Decoded string is not a valid IDN name. (Parameter 'unicode')
   at System.Globalization.IdnMapping.IcuGetAsciiCore(String unicodeString, Char* unicode, Int32 count)
   at System.Globalization.IdnMapping.GetAscii(String unicode, Int32 index, Int32 count)
   at System.Globalization.IdnMapping.GetAscii(String unicode, Int32 index)
   at System.Globalization.IdnMapping.GetAscii(String unicode)
   at Program.Main()
```

### Expected behavior

Ascii to convert to punycode correctly (which should since they're all letters and numbers)

### Actual behavior

 `Decoded string is not a valid IDN name. (Parameter 'unicode')` 

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

Runs into this issue on .NET 6 and .NET 4.7.2

### Other information

_No response_

**Comment by tarekgh** [comment]
You are using too long domain name. If you look at [rfc1034](https://datatracker.ietf.org/doc/html/rfc1034) it is clearly state the following:

```
The labels must follow the rules for ARPANET host names.  They must
start with a letter, end with a letter or digit, and have as interior
characters only letters, digits, and hyphen.  There are also some
restrictions on the length.  Labels must be 63 characters or less.
```

**Comment by lchen3-atlassian** [comment]
`test.example.com` is under 63 characters though. Is `testuser123+2m4v7kxvwqsry21ct6s+2t7epyi9agymtur55og+0vi7sk0xkz` too long?

**Comment by tarekgh** [comment]
`GetAscii` assumes you are passing the domain's name. it is not expected to have it split it at the `@` character. So, the input of `GetAscii` will be split into labels which are separated by `.`. In your case, the first label will be `testuser123+2m4v7kxvwqsry21ct6s+2t7epyi9agymtur55og+0vi7sk0xkz@test` which is greater than 63 in length.

You may look [rfc3490](https://datatracker.ietf.org/doc/html/rfc3490#section-4.1) for more info how toAscii work.
