### ISSUE TITLE
JsonSerializer.Deserialize<T>() in Blazor wasm is very slow

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#72969]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/JsonSerializerDeserializeT-in-Blazo/10097477)._

---
I've got a piece of code that downloads some objects from Blazor in the browser calling a WebApi.

The process of calling the server + using EF to retrieve the data from SQL server  + Serializing the data in the service + downloading the JSON as string in the client takes 200ms.

Once in the browser, the deserialization takes 5.2 seconds. It doesn't make sense. That is using System.Text in .net6. Using Newtonsoft takes 5.6s. It makes the whole thing extremely slow, and that is not even a large number of objects.

The same deserialization in the server takes 61ms.

---
#### Feedback Bot on 7/18/2022, 00:30 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by eiriktsarpalis** [comment]
This may or may not depend on the specifics of your application. Could you share a minimal reproducing project that we could take a look at?

**Comment by lewing** [comment]
I would recommend you try net7 preview6 and enable AOT, there has been considerable improvement in the json performance since net6
