### ISSUE TITLE
[NativeAOT] Runtime Directives (rd.xml) file not applied?

### ISSUE THREAD

**Issue by gerardog** [dotnet/runtime#72989]
### Description

Using VS 2022 Community 17.3.0 Preview 5.0 + .net sdk 7.0.100-preview.6.22352.1.
I am unable to fix a MissingInteropDataException via a `Default.rd.xml`.

Not sure if the runtime directive is processed or not. I don't see any difference in build output or build warnings/errors regardless of whatever I put inside the rd.xml. Even invalid xml has same build output.

I've tried setting the `default.rd.xml` as `Embedded resource` and still getting the same error.
How can I debug/verify what metadata is published? 

### Reproduction Steps

```
git clone https://github.com/gerardog/NativeAotRepro.git
cd NativeAotRepro\NativeAotRepro
dotnet publish -r win-x64 -c Debug
.\bin\Debug\net7.0\win-x64\publish\NativeAotRepro.exe

Hello, World!
Unhandled Exception: EETypeRva:0x004E71B0(System.Runtime.InteropServices.MissingInteropDataException): System.IO.Pipes.SECURITY_ATTRIBUTES is missing structure marshalling data. To enable structure marshalling data, add a MarshalStructure directive to the application rd.xml file. For more information, please visit http://go.microsoft.com/fwlink/?LinkID=393965
   at Internal.Runtime.CompilerHelpers.RuntimeInteropData.GetStructUnsafeStructSize(RuntimeTypeHandle) + 0xc4
   at System.Runtime.InteropServices.Marshal.SizeOfHelper(Type, Boolean) + 0x36
   at System.Runtime.InteropServices.Marshal.SizeOf(Object) + 0x42
   at System.IO.Pipes.NamedPipeServerStreamConstructors.GetSecAttrs(HandleInheritability, PipeSecurity, Object&) + 0x8a
   at System.IO.Pipes.NamedPipeServerStreamConstructors.New(String, PipeDirection, Int32, PipeTransmissionMode, PipeOptions, Int32, Int32, PipeSecurity, HandleInheritability, PipeAccessRights) + 0x3e2
   at Program.<Main>$(String[]) + 0x91
   at NativeAotRepro!<BaseAddress>+0x3a5167
   at NativeAotRepro!<BaseAddress>+0x3a51f0
```

Alternative repro:
- Create dotnet 7.0 console app
- Add `<PublishAot>true</PublishAot>` to `.csproj` file
- Add reference to nuget package `NamedPipeServerStream.NetFrameworkVersion` (it is .NetStandard 2.0)
- Add code:
```
using System.IO.Pipes;

var ps = new PipeSecurity();

using (var dataPipe = NamedPipeServerStreamConstructors.New("test", PipeDirection.InOut, 10,
    PipeTransmissionMode.Message, PipeOptions.Asynchronous, 1024, 1024, ps))
{
    Console.WriteLine("Named pipe created");
} 
```
- Add proper `.rd.xml` file
- run `dotnet publish -r win-x64 -c Debug`
- run generated `.exe` file

### Expected behavior

The `default.rd.xml` should add type metadata to the build

### Actual behavior

I don't see any difference regardless of the content of the rd.xml file.

### Configuration

Win11 21H2 + VS 2022 Community 17.3.0 Preview 5.0 + .net sdk 7.0.100-preview.6.22352.1.

**Comment by gerardog** [comment]
Just in case... Here is one of the `default.rd.xml` files that I've used: https://github.com/gerardog/NativeAotRepro/blob/master/NativeAotRepro/Properties/Default.rd.xml

**Comment by hez2010** [comment]
rd.xml won't be included in the build by default. You need to specify them in your csproj manually:

```xml
<ItemGroup>
    <RdXmlFile Include="path/to/rd.xml" />
</ItemGroup>

**Comment by gerardog** [comment]
Oh, that fixed it.
Nonetheless... There is no mention of `<RdXmlFile>` tag in neither:

- https://docs.microsoft.com/en-us/windows/uwp/dotnet-native/runtime-directives-rd-xml-configuration-file-reference
- Nor any docs.microsoft.com: https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fdocs.microsoft.com%2F+%2B%22rdxmlfile%22
- Link from the Exception: http://go.microsoft.com/fwlink/?LinkID=393965
- https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/rd-xml-format.md
- Native troubleshooters https://dotnet.github.io/native/troubleshooter/type.html

I guess all documentation was conceived for UWP apps, that I assume have the <RdXmlFile> tag by default.

I would say this is a bug in the documentation that needs fixing.

**Comment by jkotas** [comment]
I have submitted https://github.com/HavenDV/NamedPipeServerStream.NetFrameworkVersion/pull/2 that makes rd.xml unnecessary with this library.

I agree we should document rd.xml better, however it is always going to be a last resort fragile workaround that does not provide good experience. We strongly prefer to fix the libraries to make them compatible out-of-the-box just like I have done, so that the rd.xml workarounds are not necessary.

**Comment by gerardog** [comment]
Thanks for the PR. Never would have figured that out on my own.
I agree fixing the the library is best.

Still, rd.xml is mentioned in several places. Please mention the tag too!

**Comment by MichalStrehovsky** [comment]
I'd like to fix this one together with #69746.

We'll probably have to rename this from RD.XML to something else. The RD.XML file format is specific to .NET Native. What we use in NativeAOT is a strange dialect; we need to call it differently because the docs don't match.

We'll make all these places throw a `PlatformNotSupportedException` with no mention of RD.XML or links.

We'll probably not document the RD.XML dialect on docs.microsoft.com either. It will be there - but only for very determined users. RD.XML is not how NativeAOT should be consumed.

**Comment by HavenDV** [comment]
Fixed in NamedPipeServerStream.NetFrameworkVersion 1.1.9. Thanks to @jkotas for the PR.

**Comment by MichalStrehovsky** [comment]
We removed the links to .NET Native. The format is still called RD.XML but we will not mention its existence anywhere in the docs or exception messages. It's unsupported.

**Comment by teo-tsirpanis** [comment]
BTW @gerardog since you are in .NET 7 I recommend you to use [`NamedPipeServerStreamAcl.Create`](https://docs.microsoft.com/en-us/dotnet/api/system.io.pipes.namedpipeserverstreamacl.create) instead of this package.
