### ISSUE TITLE
[API Proposal]: Add a BitArray.Contains method

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#72999]
### Background and motivation

The `BitArray` class has been optimized to take advantage of hardware vectorization but it doesn't appear to have an efficient way to check if all flags within the array are either set or unset. The only suggested workaround I could find is to use Linq, i.e.
```C#
input.Cast<bool>().Contains(true);
```
which is far from optimal. The type could really benefit from a dedicated `Contains` implementation that uses vectorization.

### API Proposal

```csharp
namespace System.Collections;

public class BitArray
{
    public bool Contains(bool value);
}
```

### API Usage

```csharp
BitArray value;
BitArray mask;

value.And(mask).Contains(true);
```

**Comment by eiriktsarpalis** [comment]
cc @krwq @stephentoub

**Comment by krwq** [comment]
I'd only recommend renaming Contains into `AllBitsEqual`, otherwise LGTM

**Comment by eiriktsarpalis** [comment]
Exposing an `All` method is equivalent to an `Any`/`Contains` method, since you can express it as 
```C#
public AllBitsEqual(bool value) => !Contains(!value);
```
and vice versa. I feel `Contains` is more appropriate since this is a collection type but we could expose both variants.

**Comment by danmoseley** [comment]
I had the same expectation as @krwq. 

What do other platforms/implementations name it?

Also, if I was translating an algorithm would I generally be thinking in terms of "are any bits set" (in which case Contains might be what I look for) or "are all bits false"?

**Comment by Tornhoof** [comment]
> What do other platforms/implementations name it?
Java only implements IsEmpty() -> https://docs.oracle.com/javase/7/docs/api/java/util/BitSet.html#isEmpty()

The other way round is not implemented, there is a discussion around that here: https://stackoverflow.com/questions/36308666/check-if-all-bits-in-bitset-are-set-to-true

**Comment by EgorBo** [comment]
Alternatives:
```csharp
bool AllBitsSet { get; }
bool IsZero { get; } // AllBitsUnset
```

**Comment by tannergooding** [comment]
> Alternatives:

We wouldn't want this as a property. Properties are typically used for things that are "as cheap as a field read" and not for some potentially expensive algorithm that needs to check every element in the collection.

> since you can express it as

While you can express it as this, I personally find comparing against a negative much harder to read/understand.

Not only can `!` in `if (!value.Contains(...))` get easily missed or misread, but you have to remember to read this as "if value does not contain" which while still not difficult, it is much clearer to me when it is `if (value.DoesNotContain(...))` or `if (value.AllBitsEqual(false))`.

There are several other cases where I really wish we had both `positive` and `negative` APIs for binary cases (e.g. rather than `IsLittleEndian` and `!IsLittleEndian` it should've been `IsLittleEndian` and `IsBigEndian`) and since this is strictly a binary case (and always will be), I think it might be beneficial to expose it as such.

**Comment by eiriktsarpalis** [comment]
> bool AllBitsUnset => !AllBitsSet;

> There are several other cases where I really wish we had both positive and negative APIs for binary cases

FWIW `AllBitsEqual` is not a direct negation of `Contains`, one is expressible in terms of the other using De Morgan transformations. But I think that further proves the point that both existential and universal quantification are useful as first-class APIs here. 

If we do ship both variants, I think the names should complement each other, following existing .NET terminology it could look as follows:
```C#
public bool Any(bool value);
public bool All(bool value);
```

**Comment by danmoseley** [comment]
[golang](https://pkg.go.dev/github.com/golang-collections/go-datastructures/bitarray) bit array doesn't seem to have this
[rust](https://docs.rs/bit-array/0.4.3/bit_array/struct.BitArray.html) has `all()` and `none()1`
[c++](https://cplusplus.com/reference/bitset/bitset/) bitset has `all()` and `none()`
[Python](https://pypi.org/project/bitarray/) has `all()` but for none, you have to negate `any()`

**Comment by sakno** [comment]
`LeadingZeroCount()` and/or `TrailingZeroCount()` can do the same but reusable for other purposes.

**Comment by tannergooding** [comment]
> FWIW AllBitsEqual is not a direct negation of Contains

Right. I meant for the case people are requesting of `array.All(true)`, we shouldn't need to represent it as `!array.Contains(false)` nor as `!array.Contains(true)` for `array.All(false)`. It makes it immensely harder to read/etc.

`Contains()` (or `Any()`) is the "minimum" API and then there is a common/requested scenario of `All()` (but possibly with a better/longer name).

**Comment by danmoseley** [comment]
> `LeadingZeroCount()` and/or `TrailingZeroCount()` can do the same but reusable for other purposes.

`none()` can be implemented as `LeadingZeroCount() == Length;` but how do you implement `all()` with those?

**Comment by sakno** [comment]
> `none()` can be implemented as `LeadingZeroCount() == Length;` but how do you implement `all()` with those?

Yes, you're right. Probably, these methods are subjects to different proposal.

**Comment by tannergooding** [comment]
You'd need something like `BitArray.PopCount(bitArray) == bitArray.Length)`.

But, that's also not strictly speaking the best or optimal implementation. `Any`/`All`/`None` can "early exit" where-as `PopCount` must process the entire array. Likewise `LeadingZeroCount` and `TrailingZeroCount` must process up to the first set bit from opposite sides of the array.

**Comment by bartonjs** [comment]
* The proposed API and the proposed reason are logical opposites... "has all bits set" is `!arr.Contains(false)`.  So we came up with more direct questions.
* Count == 0 almost certainly wants both of these methods to return `false`.

```C#
namespace System.Collections
{
    public partial class BitArray
    {
        public bool HasAllSet();
        public bool HasAnySet();
    }
}
```

**Comment by eiriktsarpalis** [comment]
> Count == 0 almost certainly wants both of these methods to return false.

Can you elaborate? Generally speaking "All" quantifiers return `true` on empty sets.

**Comment by bartonjs** [comment]
Heh, should've left it as my original "needs careful attention".  Enumerable.All is the only "all" I know of in .NET, and it returns true on empty, so I guess true makes sense here, too.

The trouble is, with an empty set, All is the same as divide by zero to a mathematician: it means "this isn't answerable in a general context, but you might have a specific interpretation to fall back on" (so, had I been the author if it, the LINQ All it would have thrown on empty).  (`if (blockingIssues.HasAllSet()) { panic(); }` clearly thinks that blockingIssues is non-empty)

**Comment by eiriktsarpalis** [comment]
See https://en.wikipedia.org/wiki/Universal_quantification#The_empty_set

By convention/definition, "forall" over empty is true and "exists" over empty is false. This makes sense if you look at inductive definitions of such quantifiers.

**Comment by stephentoub** [comment]
>> Count == 0 almost certainly wants both of these methods to return false.

> Can you elaborate? Generally speaking "All" quantifiers return true on empty sets.

`HasAllSet` should return true for an empty collection.  That's what `Enumerable.All` does, that's what `List<T>.TrueForAll` does, that's what `Array.TrueForAll` does, etc.
