### ISSUE TITLE
Interop+Crypto+OpenSslCryptographicException instead of CryptographicException (AsnContentException)

### ISSUE THREAD

**Issue by RyanGaudion** [dotnet/runtime#72994]
### Description

I have a Unit test that on windows throws a AsnContentException which is a System.Security.Cryptography.CryptographicException. This is the expected behavior and the exception is caught with `Assert.Throws<CryptographicException>(() => privKeyString.ToRSAPrivateKey());`.

When running this test in a Linux container, the test fails as the exception is of type `typeof(Interop+Crypto+OpenSslCryptographicException): error:0606F091:digital envelope routines:EVP_PKCS82PKEY:private key decode error` which is then not caught by my Assert statement, causing the test to fail.

### Reproduction Steps

Here is the test to reproduce:
```
RSA rsa = RSA.Create();
var privKey = rsa.ExportPkcs8PrivateKey();
var privKeyString = Convert.ToBase64String(privKey);

//TODO - More Specific Exception details
Assert.Throws<CryptographicException>(() => privKeyString.ToRSAPrivateKey());
```

```
public static RSA ToRSAPrivateKey(this string input)
{
    var privateKey = Convert.FromBase64String(input);
    RSA rsa = RSA.Create();
    rsa.ImportRSAPrivateKey(privateKey, out _);
    return rsa;
}
```

### Expected behavior

Expected a CryptographicException, more specifically a AsnContentException

### Actual behavior

Instead, I receive `typeof(Interop+Crypto+OpenSslCryptographicException): error:0606F091:digital envelope routines:EVP_PKCS82PKEY:private key decode error`

**Comment by vcsjones** [comment]
In general, the cryptographic APIs will throw a `CryptographicException` or an internal exception that is derived from `CryptographicException` depending on the platform. Linux may use `OpenSslCryptograhicException`, Apple may use `AppleCommonCryptoCryptographicException`, etc, but they are derive from `CryptographicException`.

Assuming your test framework is xunit, your assert should change to `Assert.ThrowsAny<CryptographicException>(...)`.
