### ISSUE TITLE
Incorrect behaviour of String.StartsWith(String)

### ISSUE THREAD

**Issue by sijk** [dotnet/runtime#72992]
### Description

`String.StartsWith(String)` gives an incorrect result when the argument is a string containing a single character in the ranges 0x00-0x08, 0x0E-0x1F, 0x7F. 

### Reproduction Steps

```c#
for (int i = 0x00; i < 0x80; i++)
{
    var s = new string((char)i, 1);
    bool result = "Hello".StartsWith(s);
    System.Console.WriteLine("{0:X2}: {1}", i, result);
}
```

### Expected behavior

```
00: False
01: False
02: False
03: False
04: False
05: False
06: False
07: False
08: False
09: False
0A: False
0B: False
0C: False
0D: False
0E: False
0F: False
10: False
11: False
12: False
13: False
14: False
15: False
16: False
17: False
18: False
19: False
1A: False
1B: False
1C: False
1D: False
1E: False
1F: False
20: False
21: False
22: False
23: False
24: False
25: False
26: False
27: False
28: False
29: False
2A: False
2B: False
2C: False
2D: False
2E: False
2F: False
30: False
31: False
32: False
33: False
34: False
35: False
36: False
37: False
38: False
39: False
3A: False
3B: False
3C: False
3D: False
3E: False
3F: False
40: False
41: False
42: False
43: False
44: False
45: False
46: False
47: False
48: True
49: False
4A: False
4B: False
4C: False
4D: False
4E: False
4F: False
50: False
51: False
52: False
53: False
54: False
55: False
56: False
57: False
58: False
59: False
5A: False
5B: False
5C: False
5D: False
5E: False
5F: False
60: False
61: False
62: False
63: False
64: False
65: False
66: False
67: False
68: False
69: False
6A: False
6B: False
6C: False
6D: False
6E: False
6F: False
70: False
71: False
72: False
73: False
74: False
75: False
76: False
77: False
78: False
79: False
7A: False
7B: False
7C: False
7D: False
7E: False
7F: False
```

### Actual behavior

```
00: True
01: True
02: True
03: True
04: True
05: True
06: True
07: True
08: True
09: False
0A: False
0B: False
0C: False
0D: False
0E: True
0F: True
10: True
11: True
12: True
13: True
14: True
15: True
16: True
17: True
18: True
19: True
1A: True
1B: True
1C: True
1D: True
1E: True
1F: True
20: False
21: False
22: False
23: False
24: False
25: False
26: False
27: False
28: False
29: False
2A: False
2B: False
2C: False
2D: False
2E: False
2F: False
30: False
31: False
32: False
33: False
34: False
35: False
36: False
37: False
38: False
39: False
3A: False
3B: False
3C: False
3D: False
3E: False
3F: False
40: False
41: False
42: False
43: False
44: False
45: False
46: False
47: False
48: True
49: False
4A: False
4B: False
4C: False
4D: False
4E: False
4F: False
50: False
51: False
52: False
53: False
54: False
55: False
56: False
57: False
58: False
59: False
5A: False
5B: False
5C: False
5D: False
5E: False
5F: False
60: False
61: False
62: False
63: False
64: False
65: False
66: False
67: False
68: False
69: False
6A: False
6B: False
6C: False
6D: False
6E: False
6F: False
70: False
71: False
72: False
73: False
74: False
75: False
76: False
77: False
78: False
79: False
7A: False
7B: False
7C: False
7D: False
7E: False
7F: True
```

### Regression?

This gives the expected output in .NET Framework 4.7 and gives the actual output above in .NET 6. 

### Other information

`String.StartsWith(char)` behaves correctly. That is, if you replace `"Hello".StartsWith(s)` with `"Hello".StartsWith((char)i)` in the snippet above then the output is correct in .NET 6.

**Comment by EgorBo** [comment]
Looks ICU related, doesn't repro with NLS

**Comment by tarekgh** [comment]
You are calling the linguistic `StartsWith` and not passing the `StringComparison.Ordinal`. This means the operation will be performed according to the sorting weight of the characters. Unicode defines some characters which are marked as [ignored characters](https://www.unicode.org/charts/collation/chart_Ignored.html). Which means these characters act as if they don't exist in the string at all. If your intention is to not use the linguistic comparisons, you need to pass `StringComparison.Ordinal` to the call and you'll get the desired behavior. Review the doc https://docs.microsoft.com/en-us/dotnet/core/extensions/globalization-icu to understand the change switching using ICU instead of NLS. The doc mention how to get back the old behavior if desired (which we are strongly not recommending that because it will deviate from the globalization Unicode standard and will lose other functionality).

**Comment by sijk** [comment]
Thanks for the explanation @tarekgh. The remarks in the documentation do recommend that you pass a culture argument but intuitively I'd expected the culture to affect equality comparison only for combining unicode accents etc. — I found it very surprising that it affected equality of characters within the ASCII range. Perhaps it would be worth mentioning the option of using `StringComparison.Ordinal` in the *Notes to Callers* alongside the mention of `CurrentCulture`? 

For anyone else that comes across this, see https://docs.microsoft.com/en-us/dotnet/standard/base-types/string-comparison-net-5-plus.

**Comment by tarekgh** [comment]
@sijk feel free to submit a doc PR to add any more info that can help users when run into this situation.

**Comment by Clockwork-Muse** [comment]
> I found it very surprising that it affected equality of characters within the ASCII range.

They're in the ASCII range, sure, but everything below `0x21` is whitespace/a control character.  Which would also fit into "like a character used for combining" (for some of them, at least).  The ASCII range isn't special in that regard.  Further, if you expand the range a bit, and allow case-insensitive comparisons, there are cultures that have weird effects with characters in the ASCII range - see the [Turkish 'i' problem](https://en.wikipedia.org/wiki/Dotted_and_dotless_I_in_computing).
