### ISSUE TITLE
Add System.Reflection.PathAssemblyResolver support for 'retargetable' assemblies

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/runtime#730]
https://github.com/dotnet/corefx/issues/40523#issue-484261911

> .assembly extern retargetable mscorlib
> {
> .publickeytoken = (7C EC 85 D7 BE A7 79 8E ) // |.....y.
> .ver 2:0:5:0
> }
> 
> If any assemblies loaded by `MetadataLoadContext` were built against some older versions of mscorlib, `PathAssemblyResolver` will fail to match any newer versions of mscorlib present in `assemblyPaths`, due to a public key token mismatch. `PathAssemblyResolver` already supports taking the most recent version for target assemblies with an empty public key token.
> 
> https://github.com/dotnet/corefx/blob/master/src/System.Reflection.MetadataLoadContext/src/System/Reflection/PathAssemblyResolver.cs#L80
> 
> Add support for most-recent assembly match when assembly being resolved is 'retargetable'.

This was fixed in .NET 5 - https://github.com/dotnet/corefx/pull/40581.  We did not take this change into .NET Core 3.1 since the evidence was not clear at that time that this would be a big problem. 
 
Since the release of .NET Core 3.1, several WPF customers have reported that this is a blocking problem. 

- https://developercommunity.visualstudio.com/content/problem/806211/wpf-apps-fail-to-compile-after-updating-to.html
- https://developercommunity.visualstudio.com/content/problem/845412/vs2019-164-fails-to-build-windowsdesktop-project-t.html
- https://github.com/dotnet/wpf/issues/2274
- https://github.com/dotnet/wpf/issues/2277

We would like this fix backported to .NET Core 3.1 as part of an upcoming servicing update. 

/cc @ericstj, @nguerrera, @rladuca, @steveharter

**Comment by danmosemsft** [comment]
Moved to dotnet/runtime for centralized query.

cc @ericstj, @nguerrera, @rladuca, @steveharter since notifications will have gotten lost.

**Comment by ericstj** [comment]
Picking this up, discussed in tactics and approved if it makes it in today.

**Comment by ericstj** [comment]
Per @mmitche https://github.com/dotnet/corefx/pull/42768#issuecomment-564342764

> Hold this until 3.1.2, as I think the other fix is slipping too, and aspnetcore is just about ready to go.

**Comment by ericstj** [comment]
This was fixed in 3.1.2 with package System.Reflection.MetadataLoadContext\4.7.1.

WPF is still working on picking up the fix in the SDK.
