### ISSUE TITLE
DllImport Issue on Maca64

### ISSUE THREAD

**Issue by jnkarate** [dotnet/runtime#73039]
### Describe the bug
The word lib is prepended to the .dylib file by default on Maca64.  For example lets say that there is a file fibLibrary.dylib that I am trying to invoke through DllImport.  On Maca64 .NET will search for libfibLibrary.dylib instead.

### To Reproduce
I have a sample C++ library and C# calling code, to reproduce the issue.
-->

**C# calling code:**

```csharp
using System;
using System.Runtime.InteropServices;

namespace CallUnmanagedCode
{
    class Program
    {
        //change to your path of sample code
        const string path= "SampleUnmanagedCode";
        [DllImport(path)]
        static extern void fibonacci_init(ulong a, ulong b);

        [DllImport(path)]
        static extern ulong fibonacci_current();

        static void Main(string[] args)
        {
            fibonacci_init(1, 2);
            Console.WriteLine(fibonacci_current());
        }
    }
}
```

**Sample C++ Library:

MathLibrary.h file**
```cpp
#pragma once

#ifdef MATHLIBRARY_EXPORTS
#define MATHLIBRARY_API __declspec(dllexport)
#else
#define MATHLIBRARY_API __declspec(dllimport)
#endif


// Initialize a Fibonacci relation sequence
// such that F(0) = a, F(1) = b.
// This function must be called before any other function.
extern "C" MATHLIBRARY_API void fibonacci_init(
    const unsigned long long a, const unsigned long long b);

// Produce the next value in the sequence.
// Returns true on success and updates current value and index;
// false on overflow, leaves current value and index unchanged.
extern "C" MATHLIBRARY_API bool fibonacci_next();

// Get the current value in the sequence.
extern "C" MATHLIBRARY_API unsigned long long fibonacci_current();

// Get the position of the current value in the sequence.
extern "C" MATHLIBRARY_API unsigned fibonacci_index();
```

**MathLibrary.cpp file:**

```cpp
// MathLibrary.cpp : Defines the exported functions for the DLL.
#ifdef _WIN32
    #include "pch.h" // use stdafx.h in Visual Studio 2017 and earlier
#endif
#include <utility>
#include <limits.h>
#include "MathLibrary.h"

// DLL internal state variables:
static unsigned long long previous_;  // Previous value, if any
static unsigned long long current_;   // Current sequence value
static unsigned index_;               // Current seq. position

// Initialize a Fibonacci relation sequence
// such that F(0) = a, F(1) = b.
// This function must be called before any other function.
void fibonacci_init(
    const unsigned long long a,
    const unsigned long long b)
{
    index_ = 0;
    current_ = a;
    previous_ = b; // see special case when initialized
}

// Produce the next value in the sequence.
// Returns true on success, false on overflow.
bool fibonacci_next()
{
    // check to see if we'd overflow result or position
    if ((ULLONG_MAX - previous_ < current_) ||
        (UINT_MAX == index_))
    {
        return false;
    }

    // Special case when index == 0, just return b value
    if (index_ > 0)
    {
        // otherwise, calculate next sequence value
        previous_ += current_;
    }
    std::swap(current_, previous_);
    ++index_;
    return true;
}

// Get the current value in the sequence.
unsigned long long fibonacci_current()
{
    return current_;
}

// Get the current index position in the sequence.
unsigned fibonacci_index()
{
    return index_;
}
```

The one macro in this file just checks for windows.
This code works as expected on windows but throws a DllNotFoundException on Maca64.

### Exceptions (if any)
DLLNotFoundException

### Further technical details
I placed the dynamic link library in the same directory as the calling .NET application on Windows and Maca64, on Windows it was found on Maca64 it was not because of the prepend.

**Comment by AaronRobinsonMSFT** [comment]
@jnkarate I have not attempted to reproduce this locally yet, that is for tomorrow. In the meantime we have documentation on how to create cross-platform native libraries for use with `DllImport`. https://docs.microsoft.com/dotnet/standard/native-interop/cross-platform

**Comment by liebasam** [comment]
@AaronRobinsonMSFT the doc you linked states:

> When running on Linux **or macOS**, the runtime will try prepending lib and appending the canonical shared library extension. On these OSes, library name variations are tried in the following order:
> 
> 1. nativedep.so / nativedep.dylib
> 2. libnativedep.so / libnativedep.dylib
> 3. nativedep
> 4. libnativedep

Points 1 and 3 do not appear to be searched on Mac ARM (maca64). I think that's the issue being highlighted here.

**Comment by AaronRobinsonMSFT** [comment]
> Points 1 and 3 do not appear to be searched on Mac ARM (maca64). I think that's the issue being highlighted here.

Agree. I'm looking for the OP to confirm this understanding. I'm planning on trying this today to confirm nothing has regressed, but I want to ensure we communicate the current documented behavior.

**Comment by AaronRobinsonMSFT** [comment]
@jnkarate Can you share an example of what is placed in `const string path= "SampleUnmanagedCode";`?

For example, `fibLibrary.dylib` or `fibLibrary` or `subdir/fibLibrary.dylib` or `subdir/fibLibrary`

**Comment by AaronRobinsonMSFT** [comment]
Another question to confirm, what version of .NET is being used in this scenario? A list of the currently installed runtimes and SDKs would be helpful.

`$ dotnet --list-runtimes`
`$ dotnet --list-sdks`

**Comment by AaronRobinsonMSFT** [comment]
Starting with [`DllImportPathTest`](https://github.com/dotnet/runtime/blob/main/src/tests/Interop/DllImportAttribute/DllImportPath/DllImportPathTest.cs), I modified the resulting native library with and without the `lib` prefix - the runtime was able to discover both. I also quickly audited the discovery logic for this and I don't see anything obviously incorrect either.

https://github.com/dotnet/runtime/blob/44f1c1ec1eed7662d47dfbbf506d55d0152029eb/src/coreclr/vm/nativelibrary.cpp#L518-L526

Knowing what version of the runtime is being used, an example of what is passed to `DllImport`, and the specific error/exception being observed would be helpful to move the investigation forward.

**Comment by jnkarate** [comment]
@AaronRobinsonMSFT I apologize for the late response.

To answer your questions

1) fibLibrary is placed in the variable const string path. 

2) I can confirm what @liebasam stated as the issue.

3. The version of the dotnetsdk used is 6.0.300

**Comment by AaronRobinsonMSFT** [comment]
@jnkarate Can you supply the exception you are observing in this case? I tried this with latest (`dotnet/runtime/main`) and it works as expected but will now also try with 6.0.300 to confirm.

**Comment by AaronRobinsonMSFT** [comment]
Also, please ensure the bitness of everything matches in this case (i.e., the runtime and native binary are both `x64` or `arm64`).

**Comment by AaronRobinsonMSFT** [comment]
I just retried this with .NET 6 and am unable to reproduce this. Can you provide a screenshot of the failing console application to we can see the actual error being shown as well as a directory listing.

**Comment by jnkarate** [comment]
I have ensured that the runtime is the maca64 runtime and sdk, both the native library and sdk are built on maca64 for maca64.  The exact exception is --DllNotFoundException.  I will provide more information when I can.

**Comment by AaronRobinsonMSFT** [comment]
One more thing to consider is that the file system on macOS is case sensitive so that also must match. This is different from Windows.

**Comment by jnkarate** [comment]
After looking at this further I do not believe that the case sensitive file system is to blame.  The application works fine on Maci
( I recompiled the C++ library for Maci).  The application works on every platform except for Maca.   The name of the library here is libfibLibrary.dylib, The output is:

 System.DllNotFoundException : Unable to load shared library lib'libfibLibrary.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(lib'libfibLibrary.dylib 0x0001): 

the rest of the message is the contents of the DYLD_LIBRARY_PATH environment variable, it is worth noting that liblibfibLibrary.dylib is what is searched for on the path.

This app works on every platform except for Maca.  I tried this on a genuine Maca machine (no rosetta) targeting native Maca.
Please let me know if this answers the question.

**Comment by AaronRobinsonMSFT** [comment]
> System.DllNotFoundException : Unable to load shared library lib'libfibLibrary.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(lib'libfibLibrary.dylib 0x0001):

There is something very odd with that error message. Our message is defined as 

https://github.com/dotnet/runtime/blob/6e07ea4dc0d26c4a33f321cbe70bbd13307b5d3a/src/coreclr/dlls/mscorrc/mscorrc.rc#L165

So, the "lib" prior to the first single quote is an oddity. 

I am unable to reproduce this on the Mac arm64 locally. Can you share the full source in a repo form? There is something very odd going on here and the error messages makes this more confusing.
