### ISSUE TITLE
Stack traces should include parameter names

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#73051]
`EnvironmentStackTrace.StackTraceTest` test expects parameter names to show up. We don't print them even if we have them.

The original motivation was consistency - we don't necessarily have them.

But since then, IL Linker started removing parameter names for methods that are not demonstratable targets of reflection. This matches what we do. We can just start printing them if we have MethodDefinition metadata (and keep not printing them if we don't have it).

The fix will be in src\coreclr\nativeaot\System.Private.StackTraceMetadata\src\Internal\StackTraceMetadata\MethodNameFormatter.cs.

**Comment by jasper-d** [comment]
I would like to take a stab at it. Feel free to assign me.

**Comment by jkotas** [comment]
It is yours!
