### ISSUE TITLE
[API Proposal]: IServiceCollection.Configure<T>(Action<T, IServiceProvider>)

### ISSUE THREAD

**Issue by LazyTarget** [dotnet/runtime#73050]
### What
Be able to use `IServiceProvider` to resolve a dependency within an `services.Configure<MyOptions>()` registration.

### Why
Currently the only way to resolve a dependency inside of `ConfigureServices` you will need to create an intermediate `IServiceProvider` using the BuildServiceProvider() method. The big issue with this, apart from performance, is that different instances of the service provider can give different singleton services.

### How
Enables the user to configure an options instance using a factory that exposes the `IServiceProvider` instance.
Making it possible to lazily resolve dependencies inside an options class.

I have already sketched up a draft PR here:
#72942 

### API Proposal

Adding the following methods to `OptionsServiceCollectionExtensions.cs`

```csharp
namespace Microsoft.Extensions.DependencyInjection
{
    /// <summary>
    /// Extension methods for adding options services to the DI container.
    /// </summary>
    public static class OptionsServiceCollectionExtensions
    {
		public static IServiceCollection Configure<TOptions>(this IServiceCollection services, Action<TOptions, IServiceProvider> configureOptions) where TOptions : class
			=> services.Configure<TOptions>((IServiceProvider sp) => new ConfigureNamedOptions<TOptions>(Options.Options.DefaultName, (o) => configureOptions(o, sp)));

		public static IServiceCollection Configure<TOptions>(this IServiceCollection services, string? name, Action<TOptions, IServiceProvider> configureOptions) where TOptions : class
			=> services.Configure<TOptions>((IServiceProvider sp) => new ConfigureNamedOptions<TOptions>(name, (o) => configureOptions(o, sp)));

		internal static IServiceCollection Configure<TOptions>(this IServiceCollection services, Func<IServiceProvider, IConfigureOptions<TOptions>> optionsFactory) where TOptions : class
		{
			ThrowHelper.ThrowIfNull(services);
			ThrowHelper.ThrowIfNull(optionsFactory);

			services.AddOptions();
			services.AddSingleton<IConfigureOptions<TOptions>>(sp => optionsFactory(sp));

			return services;
		}
    }
}
```

### API Usage

```csharp

public class MyOptions
{
	public double Threshold { get; set; }
}

public static IServiceCollection ConfigureServices(this IServiceCollection services)
{
	return services
		.AddSingleton<Random>()

		// #1 Resolving dependency inside of an options configurator (by creating an intermediate service provider(
		.Configure<MyOptions>((opt) =>
		{
			var sp = services.BuildServiceProvider();
			var random = sp.GetRequiredService<Random>(),
			opt.Threshold = random.NextDouble();
		})

		// #2 You could use the `AddSingleton` method directly (which is how `Configure` works) and passing the service provider
		.AddSingleton<IConfigureOptions<ApiKeyAuthenticationOptions>>(
			(sp) => new ConfigureNamedOptions<ApiKeyAuthenticationOptions>("", (o) =>
			{
				o.Threshold = sp.GetRequiredService<Random>().NextDouble();
			})
		)

		// #3 This variant is a result of this PR, allowing for a much simpler syntax
		.Configure<MyOptions>((opt, sp) =>
		{
			var random = sp.GetRequiredService<Random>(),
			opt.Threshold = random.NextDouble();
		})
}
```

NOTE: That _alternative 2_ is what is actually happening behind the scenes when writing the _alternative 3_. 
It is just easier to read, more future-proof and it also resembles the classic _alternative 1_

### Alternative Designs

The `internal` method that takes an `Func<IServiceProvider, IConfigureOptions<TOptions>> optionsFactory` could be removed.

I am primarily interested in taking the `Action<TOptions, IServiceProvider>` argument.

### Risks

No breaking changes, this would extend the API surface.

**Comment by pinkfloydx33** [comment]
Is this really needed? You could just "long-form" it with `OptionsBuilder`

```csharp 
services.AddOptions<MyOptions>()
 .Configure<Random>((o, r) => o.Threshold = r.NextDouble());
```

`Configure`/`PostConfigure` currently have overloads accepting [up to 5 dependencies](https://github.com/dotnet/runtime/blob/53315683e9be6c87814149bdea05b06a412cbfd2/src/libraries/Microsoft.Extensions.Options/src/OptionsBuilder.cs#L156) . If anything I'd just be delegating through them.

If you need more than five (and maybe if you don't) you're probably better off writing a custom `IConfigureOptions<MyOptions>` class and injecting all the dependencies you need in its constructor. If *really* necessary you could inject the `IServiceProvider`.

**Comment by davidfowl** [comment]
Agree with @pinkfloydx33

**Comment by LazyTarget** [comment]
@pinkfloydx33 Nice! To be honest, I didn't know that it was one equivalent way to do it.
This is sufficient in my case

**Comment by eerhardt** [comment]
Closing as this functionality already exists (although it is slightly more verbose).
