### ISSUE TITLE
.NET 7 interface INumberBuilder

### ISSUE THREAD

**Issue by c-ohle** [dotnet/runtime#73062]
### .NET7 C# INumberBuilder

To improve and to keep the .NET 7 API simple, in [discussion with dotnet devs](https://github.com/dotnet/runtime/issues/71791), we came back to an old problem.  
To implement numeric types in C# with numeric- and conversion operators is great - so long the type is simple, has fixed size and don’t need normalization.

But if it starts with numerics eg. arbitrary size types, there is a problem.
Let’s take as example - the well known type `System.Numerics.BigInteger`.  
A simple expressions like `x = a * b;` is no problem.  
But in practice we have expressions like `x = (a * b + c * d) / e;`  
The compiler generates a sequence of operator calls but the operator has no hint if this is for a final result or for a intermediate result only. In result, it leads to memory allocation for each temporary individual intermediate result and for more complex types, eg. rational numbers,  to unnecessary performance costs for normalizations etc.

The System.Numerics devs plan at this point to provide a special `public class BigIntegerBuilder` ([discussion below](https://github.com/dotnet/runtime/issues/71791)), similar to other NET Builder solutions, to at least give the user the opportunity to code more memory-efficient and better-performing solutions.

* My proposal: an `interface System.Numerics.INumberBuilder` supporting `System.Numerics.INumber<T>`.

I would prefer a stack-like instruction set, but I know other ideas from discussions and there are many different implementations thinkable based on different systems and with different priorities.
Therefore, a final interface specification is a point of discussion.
But it should support `System.Numerics.INumber<T>`, which Builder and INumber-based templates can benefit from.

A full working test implementation for a minimalistic interface already exists. ([interface](https://github.com/c-ohle/RationalNumerics/blob/e99c22dd5bb91309bc7163a6623bc5d87c53c217/Test/math/NumberBuilder.cs#L7)) ([implementation](https://github.com/c-ohle/RationalNumerics/blob/e99c22dd5bb91309bc7163a6623bc5d87c53c217/Test/math/NumberBuilder.cs#L24))
Test project is available ([GitHub](https://github.com/c-ohle/RationalNumerics)) and can be used to check and debug. (requires compilation with Target framework .NET 7.0.)

### API Proposal

```csharp
  // This is just an outline for a stack-like approach
  // only a minimum of standard operations.
  public interface INumberBuilder
  {
    void Push<Number>(Number value) where Number : INumber<Number>;
    Number Pop<Number>() where Number : INumber<Number>;
    void Pop();
    // binary operations
    void Add();
    void Subtract();
    void Multiply();
    void Divide();
    // unary operations
    void Negate();
    void Sqr();
  }
```

### API Usage

```csharp
    static void test_INumberBuilder()
    {
      var builder = (INumberBuilder)new MyNumberBuilder();

      // 2 * 3 + 4 * 5
      builder.Push(2.0f);
      builder.Push(3.0m);
      builder.Multiply();
      builder.Push(4UL);
      builder.Push(5L);
      builder.Multiply();
      builder.Add();
      var intval = builder.Pop<Int128>();

      // PI * 10^10000
      builder.Push(Math.PI);
      builder.Push(BigInteger.Pow(10, 10000));
      builder.Multiply();
      var ratval = builder.Pop<BigRational>();

      // result / 10^10000
      builder.Push(ratval);
      builder.Push(BigRational.Pow(10, 10000));
      builder.Divide();
      var dblval = builder.Pop<double>();
    }
```

**Comment by tannergooding** [comment]
Thanks again for the interest. As per the discussion in https://github.com/dotnet/runtime/issues/71791, exposing a stack like mechanism for supporting arithmetic operations is not something we are interested in doing at this time.

**Comment by c-ohle** [comment]
@tannergooding did you read this?

> I would prefer a stack-like instruction set, but I know other ideas from discussions and there are many different implementations thinkable based on different systems and with different priorities.
Therefore, a final interface specification is a point of discussion.

**Comment by tannergooding** [comment]
Yes. A general number builder interface itself has many complexities and may cause other issues. For example, builders are often unique to the type and frequently expose operations or helpers that are specialized for the `T` they are building. I do not believe it is something we'd want to expose at this point in time.

**Comment by c-ohle** [comment]
@tannergooding  I just wanted to bring it up for discussion and  not as BigRational topic. If you're interested, it works great in directions with INumber. Of course I have a lot more test code. There are also completely new solutions.

**Comment by c-ohle** [comment]
@tannergooding Please think again and give the suggestion a chance.

**Comment by tannergooding** [comment]
I understand that it is working well for you and your code.

As indicated in the other thread (https://github.com/dotnet/runtime/issues/71791), a `BigRational` type itself is a fine proposal to have and is likely something we should consider. But, it needs to fit in with our existing patterns, follow the framework design guidelines, and take into consideration the typical usage scenario to ensure that users can achieve success.

This proposal and several of the suggestions in the other thread don't fit those requirements and so I don't think they are the right direction for us to take for anything we expose within the BCL.

**Comment by c-ohle** [comment]
@tannergooding It could be ready some days if I had only a interface. That ihis is very easy with rational is because all other types can perfectly convert. Therfore it could be something like a reference for test.
The "existing patterns solution" is ready. For this please it would be nice to get short feedbeck for my last requests. Are the details ok? It's so easy to change. I need only to know.

**Comment by c-ohle** [comment]
@tannergooding and I found new BigInteger bugs, very bad ones, wrong calculations from time to time, therefore difficult to reproduce. Where is the right place to report this? My reports here were always deleted immediately.

**Comment by tannergooding** [comment]
One issues per bug should be logged here on dotnet/runtime with reproduction steps.

Reports should not get deleted and I'm not aware of any that have had this happen.

**Comment by c-ohle** [comment]
@tannergooding the links are gone. It's on my plane to make the new bugs reproducible. Maybe they forgot a span.Clear() but it looks more like it's a Buffer<>.Rent problem because 2x an exception came from there.
