### ISSUE TITLE
FileStream creates a file in incorrect folder, when starting as UNC path

### ISSUE THREAD

**Issue by Fluttercom** [dotnet/runtime#73075]
### Description
When you create a FileStream with relative path (two folders up) and then start application via UNC path, the file is getting created in wrong folder (one level up).

The code to reproduce:
```
string appdir = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
Directory.SetCurrentDirectory(appdir); \\here we get  '\\myserver\apps\myapp'
Console.WriteLine(appdir);
using (FileStream fs = new FileStream(@"..\..\Logs\testlog.log", FileMode.Append))
  {
      string s = "test";
      var bytes = Encoding.UTF8.GetBytes(s);
      fs.Write(bytes);
  }
```
So if you start your app as \\\myserver\apps\myapp\myapp.exe, the expected log path should be \\\myserver\Logs\testlog.log,
but the file is created at \\\myserver\apps\Logs

### Configuration
net5.0, net6.0 console app

**Comment by Jozkee** [comment]
What does `Console.WriteLine(appdir);` prints? 
Can you also verify the current directory is updated properly i.e: `Console.WriteLine(Directory.GetCurrentDirectory());`?

**Comment by Fluttercom** [comment]
Verified, current directory is app directory.

**Comment by Jozkee** [comment]
Does `\\myserver\Logs` folder exists? 
It appears that even if you traverse the path beyond the shared folder it will resolve to the shared folder and will never reach server's root. see `Console.WriteLine(Path.GetFullPath(@"..\..\..\..\..\..\Logs\testlog.log"));`. 
 
Can you workaround it if you use an absolute path i.e: `\\myserver\Logs\testlog.log`?

**Comment by Fluttercom** [comment]
Seems your explanation is reasonable, might be related to security. Ok.I'll use then absolute path per environment.
Thanks.

**Comment by Jozkee** [comment]
You can also move `apps` one folder deeper and keep using the same relative paths, that way the `Logs` folder will be under this new folder and will be sibling to `apps`.  
Or you can also write the logs under your apps folder with your current structure and just remove one `..\`.
