### ISSUE TITLE
mono ARM64 llvmfullaot builds are often timing out

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#73081]
## Build Information
Build: https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=1908792
Build error leg: mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release
Pull request: https://github.com/dotnet/runtime/pull/72993

## Error Message

```json
{
  "ErrorMessage": "ran longer than the maximum time of 200 minutes",
  "BuildRetry": false
}
```

### Report
|Build|Definition|Step Name|Console log|
|---|---|---|---|
|[1911947](https://dev.azure.com/dnceng/public/_build/results?buildId=1911947)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1911947/logs/1506)
|[1913265](https://dev.azure.com/dnceng/public/_build/results?buildId=1913265)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1913265/logs/2325)
|[1913428](https://dev.azure.com/dnceng/public/_build/results?buildId=1913428)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1913428/logs/2304)
|[1913487](https://dev.azure.com/dnceng/public/_build/results?buildId=1913487)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1913487/logs/2310)
|[1921124](https://dev.azure.com/dnceng/public/_build/results?buildId=1921124)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1921124/logs/2323)
|[1920967](https://dev.azure.com/dnceng/public/_build/results?buildId=1920967)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1920967/logs/1735)
|[1920881](https://dev.azure.com/dnceng/public/_build/results?buildId=1920881)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1920881/logs/2258)
|[1920824](https://dev.azure.com/dnceng/public/_build/results?buildId=1920824)|dotnet/runtime|coreclr  Pri0 Runtime Tests Run  Linux arm checked|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1920824/logs/2373)
|[1920726](https://dev.azure.com/dnceng/public/_build/results?buildId=1920726)|dotnet/runtime|coreclr  Pri0 Runtime Tests Run  Linux arm checked|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1920726/logs/2045)
|[1920739](https://dev.azure.com/dnceng/public/_build/results?buildId=1920739)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1920739/logs/2348)
|[1920293](https://dev.azure.com/dnceng/public/_build/results?buildId=1920293)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1920293/logs/1507)
|[1920262](https://dev.azure.com/dnceng/public/_build/results?buildId=1920262)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1920262/logs/2344)
|[1908792](https://dev.azure.com/dnceng/public/_build/results?buildId=1908792)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1908792/logs/1757)
|[1920159](https://dev.azure.com/dnceng/public/_build/results?buildId=1920159)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1920159/logs/2525)
|[1920049](https://dev.azure.com/dnceng/public/_build/results?buildId=1920049)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1920049/logs/2237)
|[1916561](https://dev.azure.com/dnceng/public/_build/results?buildId=1916561)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1916561/logs/1494)
|[1916483](https://dev.azure.com/dnceng/public/_build/results?buildId=1916483)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1916483/logs/2365)
|[1916465](https://dev.azure.com/dnceng/public/_build/results?buildId=1916465)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1916465/logs/2330)
|[1916473](https://dev.azure.com/dnceng/public/_build/results?buildId=1916473)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1916473/logs/2328)
|[1915223](https://dev.azure.com/dnceng/public/_build/results?buildId=1915223)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1915223/logs/2318)
|[1914847](https://dev.azure.com/dnceng/public/_build/results?buildId=1914847)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1914847/logs/2364)
|[1915172](https://dev.azure.com/dnceng/public/_build/results?buildId=1915172)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1915172/logs/1721)
|[1914932](https://dev.azure.com/dnceng/public/_build/results?buildId=1914932)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1914932/logs/1700)
|[1914294](https://dev.azure.com/dnceng/public/_build/results?buildId=1914294)|dotnet/runtime|coreclr  Pri0 Runtime Tests Run  Linux arm checked|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1914294/logs/1458)
|[1915025](https://dev.azure.com/dnceng/public/_build/results?buildId=1915025)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1915025/logs/2353)
|[1915087](https://dev.azure.com/dnceng/public/_build/results?buildId=1915087)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux x64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1915087/logs/2477)
|[1915136](https://dev.azure.com/dnceng/public/_build/results?buildId=1915136)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1915136/logs/1727)
|[1915149](https://dev.azure.com/dnceng/public/_build/results?buildId=1915149)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1915149/logs/1489)
|[1915217](https://dev.azure.com/dnceng/public/_build/results?buildId=1915217)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1915217/logs/1506)
|[1915444](https://dev.azure.com/dnceng/public/_build/results?buildId=1915444)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1915444/logs/2323)
|[1915309](https://dev.azure.com/dnceng/public/_build/results?buildId=1915309)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1915309/logs/2295)
|[1915875](https://dev.azure.com/dnceng/public/_build/results?buildId=1915875)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1915875/logs/2028)
|[1915907](https://dev.azure.com/dnceng/public/_build/results?buildId=1915907)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1915907/logs/2385)
|[1916266](https://dev.azure.com/dnceng/public/_build/results?buildId=1916266)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1916266/logs/2335)
|[1916331](https://dev.azure.com/dnceng/public/_build/results?buildId=1916331)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1916331/logs/2511)
|[1916290](https://dev.azure.com/dnceng/public/_build/results?buildId=1916290)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1916290/logs/1506)
|[1916394](https://dev.azure.com/dnceng/public/_build/results?buildId=1916394)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1916394/logs/1514)
|[1916454](https://dev.azure.com/dnceng/public/_build/results?buildId=1916454)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1916454/logs/2334)
|[1916538](https://dev.azure.com/dnceng/public/_build/results?buildId=1916538)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1916538/logs/1501)
|[1916590](https://dev.azure.com/dnceng/public/_build/results?buildId=1916590)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1916590/logs/1738)
|[1916718](https://dev.azure.com/dnceng/public/_build/results?buildId=1916718)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1916718/logs/2351)
|[1916856](https://dev.azure.com/dnceng/public/_build/results?buildId=1916856)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1916856/logs/2330)
|[1916825](https://dev.azure.com/dnceng/public/_build/results?buildId=1916825)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1916825/logs/2328)
|[1917321](https://dev.azure.com/dnceng/public/_build/results?buildId=1917321)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux x64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1917321/logs/2342)
|[1917349](https://dev.azure.com/dnceng/public/_build/results?buildId=1917349)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1917349/logs/2033)
|[1917403](https://dev.azure.com/dnceng/public/_build/results?buildId=1917403)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1917403/logs/1692)
|[1917500](https://dev.azure.com/dnceng/public/_build/results?buildId=1917500)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1917500/logs/2342)
|[1917636](https://dev.azure.com/dnceng/public/_build/results?buildId=1917636)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1917636/logs/2318)
|[1917730](https://dev.azure.com/dnceng/public/_build/results?buildId=1917730)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1917730/logs/2238)
|[1917822](https://dev.azure.com/dnceng/public/_build/results?buildId=1917822)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1917822/logs/2335)
|[1918735](https://dev.azure.com/dnceng/public/_build/results?buildId=1918735)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1918735/logs/2330)
|[1919972](https://dev.azure.com/dnceng/public/_build/results?buildId=1919972)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1919972/logs/2384)
|[1920044](https://dev.azure.com/dnceng/public/_build/results?buildId=1920044)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1920044/logs/2237)
|[1920313](https://dev.azure.com/dnceng/public/_build/results?buildId=1920313)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1920313/logs/2355)
|[1920364](https://dev.azure.com/dnceng/public/_build/results?buildId=1920364)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1920364/logs/1491)
|[1920421](https://dev.azure.com/dnceng/public/_build/results?buildId=1920421)|dotnet/runtime|coreclr  Pri0 Runtime Tests Run  Linux arm64 checked|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1920421/logs/1538)
|[1920417](https://dev.azure.com/dnceng/public/_build/results?buildId=1920417)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1920417/logs/2338)
|[1920454](https://dev.azure.com/dnceng/public/_build/results?buildId=1920454)|dotnet/runtime|coreclr  Pri0 Runtime Tests Run  Linux arm checked|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1920454/logs/2348)
|[1920738](https://dev.azure.com/dnceng/public/_build/results?buildId=1920738)|dotnet/runtime|mono monointerpreter Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1920738/logs/940)
|[1920773](https://dev.azure.com/dnceng/public/_build/results?buildId=1920773)|dotnet/runtime|mono monointerpreter Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1920773/logs/758)
|[1920782](https://dev.azure.com/dnceng/public/_build/results?buildId=1920782)|dotnet/runtime|coreclr  Pri0 Runtime Tests Run  Linux arm64 checked|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1920782/logs/1444)
|[1920801](https://dev.azure.com/dnceng/public/_build/results?buildId=1920801)|dotnet/runtime|coreclr  Pri0 Runtime Tests Run  Linux arm checked|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1920801/logs/1515)
|[1920813](https://dev.azure.com/dnceng/public/_build/results?buildId=1920813)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1920813/logs/1506)
|[1920831](https://dev.azure.com/dnceng/public/_build/results?buildId=1920831)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1920831/logs/1506)
|[1920920](https://dev.azure.com/dnceng/public/_build/results?buildId=1920920)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1920920/logs/2314)
|[1920993](https://dev.azure.com/dnceng/public/_build/results?buildId=1920993)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1920993/logs/1712)
|[1921175](https://dev.azure.com/dnceng/public/_build/results?buildId=1921175)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux x64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1921175/logs/1480)
|[1921231](https://dev.azure.com/dnceng/public/_build/results?buildId=1921231)|dotnet/runtime|mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1921231/logs/1480)
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|28|68|68|

|Build|Kind|Start Time|
|---|---|---|
[1911075](https://dev.azure.com/dnceng/public/_build/results?buildId=1911075)|Rolling|2022-29-07|
[1915087](https://dev.azure.com/dnceng/public/_build/results?buildId=1915087)|Rolling|2022-01-08|
[1916331](https://dev.azure.com/dnceng/public/_build/results?buildId=1916331)|Rolling|2022-01-08|

**Comment by agocke** [comment]
FYI @noahfalk

**Comment by noahfalk** [comment]
@agocke Yep, it just hit the rolling build from earlier today.

**Comment by agocke** [comment]
@markwilkie I just created this issue to track timeouts, but it looks like it only has one failure, but the runfo log shows a bunch more (https://runfo.azurewebsites.net/search/timelines/?q=started%3A%7E7+definition%3Aruntime+text%3A%22ran+longer+than+the+maximum+time+of+200+minutes%22). Is there some filtering that I'm doing wrong?

**Comment by SamMonoRT** [comment]
This is one of our slowest lanes, but equally important given the focus on ARM64 perf this release. I agree, we need to bump the timeout.

**Comment by lambdageek** [comment]
It looks like the "LLVM AOT cross-compile CoreCLR tests" step is taking the most time (1hr 54m on an arbitrary build that I looked at).  But this is also the step that doesn't need to run on arm64 machines.  Can we farm out the AOT cross-compilation to some beefy x64 linux VMs?

**Comment by akoeplinger** [comment]
Note that the "LLVM AOT cross-compile CoreCLR tests" step happens on the AzDO build machine so that is already running on an x64 Linux VM. The timeouts are mostly due to the ARM64 Helix queue which runs the tests not having enough capacity to finish in time.

We can a) increase the timeout or b) only run a subset of tests on PRs.

**Comment by naricc** [comment]
Here is a PR to increase the timeout: https://github.com/dotnet/runtime/pull/73265

**Comment by fanyang-mono** [comment]
Note that the timeout count for 1 month is the same as 7 days. I suspect that a recent change caused this. I did some digging and found that full AOT lanes on both Arm64 and X64 started to slow down since the build on July 19th (https://dev.azure.com/dnceng/public/_build/results?buildId=1889738&view=results)

Comparing to the previous build (https://dev.azure.com/dnceng/public/_build/results?buildId=1889157&view=results), these are the possible PR's https://github.com/dotnet/runtime/compare/e47ffcb3...c0ddf0.

https://github.com/dotnet/runtime/commit/f48bc15556c30c1024e6a03d99ffc8067e2db606 looks the most relevant. @vargaz Do you think your PR could possibly slowing down the Full AOT process?

**Comment by vargaz** [comment]
It's possible, it does add some instances which were not there before, therefore slowing down the AOT process.

**Comment by SamMonoRT** [comment]
This issue is to ensure no build time outs. Any other code changes to actually reduce aot compilation times should be tracked via linked issue
