### ISSUE TITLE
Http2Connection over async NamedPipe transport hangs when writing preface when Server is waiting for the client to Synchronize.

### ISSUE THREAD

**Issue by danespinosa** [dotnet/runtime#73097]
### Description

HTTP/2 over async NamedPipes could face a deadlock when the HTTP/2 NamedPipe server is waiting for the client to read after connection, just before the client sends the preface.

### Reproduction Steps

This might be a little convoluted but hopefully this helps.
Run the containerd service in a PowerShell CLI.
```
$Version="1.6.6"
curl.exe -L https://github.com/containerd/containerd/releases/download/v$Version/containerd-$Version-windows-amd64.tar.gz -o containerd-windows-amd64.tar.gz
tar.exe xvf .\containerd-windows-amd64.tar.gz

# Copy and configure
Copy-Item -Path ".\bin\" -Destination "$Env:ProgramFiles\containerd" -Recurse -Force
cd $Env:ProgramFiles\containerd\
.\containerd.exe 
```
Create a minimal gRPC client or you can get the minimal reproduction by runnig the GrpcClient project here https://github.com/danespinosa/containerdclient/tree/namedPipeRepro

The client tries to connect using a named pipe and the handshake fails since both the Client and Server were in a deadlock. The client will fail with the error: "An error occurred while sending the request. IOException: An HTTP/2 connection could not be established because the server did not complete the HTTP/2 handshake. IOException: Pipe is broken"

### Expected behavior

The expected behavior is for the Http2Connection class to start the [ProcessIncomingFramesAsync ](https://github.com/dotnet/runtime/blob/1dc6524d3d4dc9ba2b661ffd9689dcca6bcebf55/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L476) task just before the [SetupAsync ](https://github.com/dotnet/runtime/blob/1dc6524d3d4dc9ba2b661ffd9689dcca6bcebf55/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L191)method awaits the [WriteAsync](https://github.com/dotnet/runtime/blob/1dc6524d3d4dc9ba2b661ffd9689dcca6bcebf55/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L225) operation of sending the Preface and Settings frames on [line 225](https://github.com/dotnet/runtime/blob/1dc6524d3d4dc9ba2b661ffd9689dcca6bcebf55/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L225)

This would be the proposed change that I could send a PR for. Move ProcessIncomingFramesAsync from line 244 to line 224
``` C#
_ = ProcessIncomingFramesAsync();
await _stream.WriteAsync(_outgoingBuffer.ActiveMemory, cancellationToken).ConfigureAwait(false);

```

This behavior would match the http2_client.go behavior that google has implemented for ther HTTP/2 client that regardless of the transport https://github.com/grpc/grpc-go/blob/02f1a7ac92e65e7d5fe11be77a8060c177b1c064/internal/transport/http2_client.go#L197
Lines 367-370
``` Go
	// Start the reader goroutine for incoming message. Each transport has
	// a dedicated goroutine which reads HTTP2 frame from network. Then it
	// dispatches the frame to the corresponding stream entity.
	go t.reader()

	// Send connection preface to server.
	n, err := t.conn.Write(clientPreface)
```

### Actual behavior

The Http2Connection is waiting for the [WriteAsync](https://github.com/dotnet/runtime/blob/1dc6524d3d4dc9ba2b661ffd9689dcca6bcebf55/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L225) operation to finish but this will never finish because it's blocked by the NamedPipe Server read operation.

### Regression?

No

### Known Workarounds

There's a good workaround, the stream being passed to Http2Connection could read and buffer the first message the NamedPipe server sends that contains the settings frame and headers soon as the NamedPipe client connects. 
The stream should return the buffered message at first read and then return the messages directly from the stream.

``` C#
 public async ValueTask<Stream> ConnectAsync(SocketsHttpConnectionContext socketsHttpConnectionContext, CancellationToken cancellationToken)
    {
        // Reading the first frame that the server sends to unblock the first write that the client will do.
        // The Http2Stream will respond with this preface response at first read.
        // This is the same behavior that http2_client in go. Line 367 t.reader()
        // https://github.com/grpc/grpc-go/blob/master/internal/transport/http2_client.go
        // Start the reader goroutine for incoming message. Each transport has
        // a dedicated goroutine which reads HTTP2 frame from network. Then it
        // dispatches the frame to the corresponding stream entity.
        var http2Stream = new Http2Stream(_pipe, InitialReadAsync());
        return http2Stream;
    }

    private async Task<Memory<byte>> InitialReadAsync()
    {
        var buffer = new byte[32];
        var readCount = await _pipe.ReadAsync(buffer);
        Console.WriteLine($"Read {readCount} from named pipe to avoid blocking further calls.");
        Memory<byte> prefaceResponse = new Memory<byte>(buffer, 0, readCount);
        return prefaceResponse;
    }

class Http2Stream : Stream
{

    private Task<Memory<byte>> initialReadTask;

    public Http2Stream(NamedPipeClientStream namedPipeClientStream, Task<Memory<byte>> initialReadTask)
    {
        namedpipeClientStream = namedPipeClientStream;
        this.initialReadTask = initialReadTask;
        this.isFirstRead = true;
    }

   public override async ValueTask<int> ReadAsync(Memory<byte> buffer, CancellationToken cancellationToken = default)
    {
        /// We do the first read at connection time and when the httpclient calls we respond with that same response.
        if (isFirstRead)
        {
            var initialRead = await initialReadTask;

            // TODO: What happens if buffer passed to ReadAsync isn't big enough for initial read data.
            // Could save the initial read data and keep replaying in ReadAsync calls until empty.
            initialRead.CopyTo(buffer);

            isFirstRead = false;
            return initialRead.Length;
        }

        var readBytes = await this.namedpipeClientStream.ReadAsync(buffer, cancellationToken);
        return readBytes;
    }

}
```
See full Example here https://github.com/danespinosa/containerdclient/blob/5615a9e0b728a0ac1b74d1b594b89e21ff015421/Program.cs#L80

### Configuration

NET Version: 6.0
OS: WIN 11 22000.795
Arch x64
Grpc NamedPipe server: Containerd: 1.6.6

**Comment by MihaZupan** [comment]
@dotnet/area-system-io is it expected that the first `WriteAsync` on a `NamedPipeClientStream` would block until a concurrent read is also issued?

**Comment by wfurt** [comment]
That may depend on size of the write and size of socket buffer IMHO. If amount of data exceed the socket buffer there is not good way how to complete the write IMHO.

**Comment by MihaZupan** [comment]
Right, I'm just surprised in this case since we're talking about only ~60 bytes of data (plus TLS overhead).

**Comment by stephentoub** [comment]
> is it expected that the first WriteAsync on a NamedPipeClientStream would block until a concurrent read is also issued?

The synchronous call to WriteAsync blocks, or the WriteAsync synchronous call returns immediately but the task doesn't complete until the data is read?  The former is not expected.  The latter is likely.

**Comment by JamesNK** [comment]
Because it's not apparent what is going on (the error message says the HTTP/2 connection handshake timed out without any indication why), and the workaround is quite involved, it's unlikely that someone will come up with this solution without spending a lot of time on it.

There is value in .NET+HTTP/2+named pipes just working. And it brings .NET into parity with golang.

It would be great if some changes could be made to HttpClient's Http2Connection to support it.

**Comment by JamesNK** [comment]
> This would be the proposed change that I could send a PR for. Move ProcessIncomingFramesAsync from line 244 to line 224
> 
> ```cs
> _ = ProcessIncomingFramesAsync();
> await _stream.WriteAsync(_outgoingBuffer.ActiveMemory, cancellationToken).ConfigureAwait(false);
> ```

I think the line setting `_expectingSettingsAck` to true would need to move before the call to `ProcessIncomingFramesAsync` to avoid a race:
https://github.com/dotnet/runtime/blob/1dc6524d3d4dc9ba2b661ffd9689dcca6bcebf55/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L229

**Comment by MihaZupan** [comment]
> The synchronous call to WriteAsync blocks, or the WriteAsync synchronous call returns immediately but the returned task doesn't complete until the data is read?

I haven't tried the repro to see which, but the observable behavior would be pretty much the same in this case.

What I am confused by here is that we are talking about requiring reads in order for writes to complete **on the same side of the pipe**. If this is the case, wouldn't all other protocols (e.g. HTTP/1.1) be broken in the same fashion?

**Comment by stephentoub** [comment]
> If this is the case, wouldn't all other protocols (e.g. HTTP/1.1) be broken in the same fashion?

Presumably the common case for HTTP/1.1 is for the server to always read before writing and the client to always write before reading.  If the server were to ignore the request and simply write out a response, you'd likely hit the same issue.

**Comment by danespinosa** [comment]
Hi everyone, thanks a lot for your input, based on the repros that @stephentoub  and myself provided.

Do we need more repros? If so, how can I help?
If we are ok with the repros that we have, would it be ok if I start a draft PR including the changes @JamesNK  and myself suggested?

**Comment by MihaZupan** [comment]
I don't see a reason not to make the change here. Feel free to open a PR @danespinosa, thanks!

**Comment by karelz** [comment]
Triage: It is transport (NamedPipe) problem, but given that the fix is simple, we should just swap the read and write calls (while adding comment explaining the order requirement).
