### ISSUE TITLE
Assertion failed 'compCanHavePatchpoints()' during 'Importation'

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#73090]
Lots of jitstress/libraries-jitstress tests are failing with this assert.
Example run: https://dev.azure.com/dnceng/public/_build/results?buildId=1911013&view=results

cc @dotnet/jit-contrib @AndyAyersMS

**Comment by AndyAyersMS** [comment]
I think there's a jit stress mode that introduces assignments to `this`.
