### ISSUE TITLE
Windows and Linux results are different when using the Process.GetCurrentProcess function.

### ISSUE THREAD

**Issue by dngur807** [dotnet/runtime#731]
The result of GetCurrentProcess for each os.

![image](https://user-images.githubusercontent.com/14495376/70487711-9c71a200-1b39-11ea-8d95-babf3ff2c96d.png)

![image](https://user-images.githubusercontent.com/14495376/70487725-aa272780-1b39-11ea-98b9-7d81bd4e4fa2.png)

centos7 some information is missing.

I've been told that this issue is fixed in dotnet core 3.1.
However, the issue also occurs after applying dotnet core 3.1.

If you know the reason for that, please share it.

**Comment by wfurt** [comment]
As far as I know Linux does not keep any track of Peak usage.  It may be similar for rest.

cc @tmds

**Comment by tmds** [comment]
@dngur807 when you report an issue, please include code (so I can copy-paste :smile: ) and copy text output instead of making screenshots.

For me:
```cs
Process p = Process.GetCurrentProcess();
Console.WriteLine(p.PeakVirtualMemorySize64);
```
outputs a non-zero value with .NET Core 3.1 on Fedora 31:
```
$ $ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     fedora
 OS Version:  31
 OS Platform: Linux
 RID:         fedora.31-x64
 Base Path:   /home/tmds/Downloads/dotnet-31/sdk/3.1.100/
...
$ dotnet run
2868670464
```

**Comment by tmds** [comment]
ping @dngur807

**Comment by adamsitnik** [comment]
No response since January and @tmds was not able to reproduce it - I am closing this issue.

@dngur807 please feel free to reopen it if you can provide the missing information
