### ISSUE TITLE
Keeping byref on stack gives InvalidProgramException

### ISSUE THREAD

**Issue by jl0pd** [dotnet/runtime#73102]
### Description

During investigation of https://stackoverflow.com/questions/73170801/clr-throws-invalidprogramexception, I've found problem in span-related part of code: if you want to create object that take 2 byref arguments, you should store each into local variable and load them onto stack before constructor call.

Example code which works:

```csharp
public readonly ref struct TwoSpans
{
    public readonly Span<int> First;
    public readonly Span<int> Second;

    public TwoSpans(Span<int> first, Span<int> second)
    {
        First = first;
        Second = second;
    }
}

public static class Program
{
    public static void Main()
    {
        var s = new TwoSpans(stackalloc int[10], stackalloc int[20]);
    }
}
```

It produces following IL:

```cil
ldc.i4.s 40
conv.u
localloc
ldc.i4.s 10
newobj instance void valuetype [System.Runtime]System.Span`1<int32>::.ctor(void*, int32)
stloc.0
ldc.i4.s 80
conv.u
localloc
ldc.i4.s 20
newobj instance void valuetype [System.Runtime]System.Span`1<int32>::.ctor(void*, int32)
stloc.1
ldloc.0
ldloc.1
newobj instance void TwoSpans::.ctor(valuetype [System.Runtime]System.Span`1<int32>, valuetype [System.Runtime]System.Span`1<int32>)
pop
ret
```

Notice `stloc` after `newobj` on `Span`. To create `TwoSpans`, both spans are loaded from stack with `ldloc.0` & `ldloc.1`

### Reproduction Steps

1. Compile same code without storing to temporary variables. It would be valid code if values wasn't byref types

```cil
ldc.i4.s 40
conv.u
localloc
ldc.i4.s 10
newobj instance void valuetype [System.Runtime]System.Span`1<int32>::.ctor(void*, int32)
//stloc.0
ldc.i4.s 80
conv.u
localloc
ldc.i4.s 20
newobj instance void valuetype [System.Runtime]System.Span`1<int32>::.ctor(void*, int32)
//stloc.1
//ldloc.0
//ldloc.1
newobj instance void TwoSpans::.ctor(valuetype [System.Runtime]System.Span`1<int32>, valuetype [System.Runtime]System.Span`1<int32>)
pop
ret
```

2. Run

### Expected behavior

Program completes successfully

### Actual behavior

Program throws `InvalidProgramException`

### Configuration

Dotnet 6, sdk 6.0.302

<details>
.NET SDK (reflecting any global.json):
 Version:   6.0.302
 Commit:    c857713418

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.302\

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  3.1.421 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]
  6.0.107 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
</details>

### Other information

MSIL code can be taken from this repo https://github.com/jl0pd/SpanInvalidProg

**Comment by jkotas** [comment]
What is the OS/architecture and the exact runtime version that you are running into this issue?

It does not repro for me on Windows x64, runtime version 6.0.7.

**Comment by jl0pd** [comment]
* Windows 10 Pro x64 21H1, build 19043.1826, cpu Intel(R) Core(TM) i7-9750H. 
* host 6.0.7, x64, commit 0ec02c8c96

Posted output from `dotnet --info` into details spoiler in configuration section. 

Sharplab always fails with `InvalidProgramException`, even with [correct code](https://sharplab.io/#v2:DYLglsA0AuIE4FcB2AfAAgNgAQFMAe0OcSWAygJ4DOhAtgHQBKy0YNOAsAFADeXAkHQAOCAEbAwAYwDWOctAD2MkgF4sACn58RABiwBmAGZYArEYDsRgIyWsAE2NZtAQ31P+ASn50AbkSwYQbUDArgBfLkxcAiISCmocegBheSRKeWAOHi9hMUkZOUUcFXVNHX0jUywLLGs7B2dXDy9fOH9goO0wrgjsUkEnJABJJG8ncVsABTh5AHMuXk4BCQRqeRosMFToAYkcLG95MFssAG042kZmVhwAXXOEy6QWNjpkmkEIIlIib0kcSleaw+wCcLBSDBwILwoLAKUoAEFoNA4GARAhCCAQHQJAo4GpNtA9AAmdxYVQaRZ8bQ2bS6bQADkcdOZTKZTUW2JWCnWm2oOz2ByOp3u9CYT2udyoFzFzxwgPenzg3zgv12AJl1ze/RYIggYGg5ERyNR6JwmOxuLUpPJmmprLttJMABZHESathjGYqm6MDYzLonXsMEYMHsnQ4zPTNBg9P4I7ozC6MABOfwhvbGJOMsw+8xesyx6nspZctYbLb8/aHY5nKUPDVsSXxegAETAThmSHk1EkAJbODRMxmTjEOCNKLRGKxOPkeNGwAQOANgj2tebj1lTYubY7XZ7Ej7A4QQ5HGXHJsIAHp+4OZpsZgBZeS2f7WkqUh10t2On8s2nFzlVh5CskF2KshTXaUrkbEUN2uOgADUiEoWEkHvOgABUnDgGYlwAMTgJw2AAd1nKRz0nM1p0tagUSQGY3wpPgqRpXRLEZIkwzDBxMywJ1Y2Db04z4v0E10IkJBMDBowjN0C38VNBNDfRjjMbA9GwTj9DpVjnUcPZLCdTQnWwHN/BsDBjgwCMvUEsyMBEPik1TeT/X8STfSqZNjKDCyrPqTpFk8DlliA8s+VAgVq2FOtRWg25YIhAwMhxVC6HhShKASMRyC1AZDSRCdTXNGc8Vo+9GNtXTtAqWM3M85SnUUvY1PM9yFP8F1jATIloxDL1fwA0LuXC7ZIvAmtEvird6xwZKcFSlJ0sy7LgFylIDDAGYEEIsEkAo4rqNnNRyvoyqP2q/MfQcDAPJuv0BICtkgq8Yay15MawMFSbYrgmDfqSlK9uWrKaByvDPiQuAUJSA6pwtY7ToYsl32Yz9HC9PQbC0vRxL2XGsBxv9Ar4YKSzCj7K2+mL1wbBKAbmoG0oy0GcuGAxZxoGEUjGKGYf2wqLyohGyuNM6UaYlj7QcLHCfxvHtPtEmycAkbKfG6nIPrabEsZhbgZZ1byCmZ8EBxOHhdKk6xeRm0LvtWqql0Bqw2aqpsAajzFK6nq+v8AbmSG0tgIir7oq1uLxX+2m9cWpAQaNjD9TPQXKJKmibfOtHqsd+qLNd/wWo9iyvc6kxfcpJSA+e0mvAACycSg66wMYZlnfU6/WbQ8FpWl6VpF1L0vMgAAl4UsZo/EsdoQk4cJOC4OgaFNjIyH6IYRjGI4TZmOhbGAYBF9YDsB0bvZu4H3v/04OhNtXrfOzYJ5HB7q+iWvug+WkOB/h+c/X8sFfQKn9RCUFii/XusYh5YAAOqbFsPIYilBEgIDAIvCQs5kodkoBAoBdpoGDAADIAHkkBrW6AvG+EgQSZSwIIFEoxCAt3RPIFuqQwBYAAOQAB4ny2AQBkAAfJw+YXRKHYhoTgnI4hJJZQAI6LnFGMNhKEsBZTGDgY4Ig5qzjmmASEthNj6iwBhUifQBiUH4PgQgSBbA4Ijn9em64EJjEXBhcgK5REhWDqNKm4cppRycVBQJ8pgRfB+H8AEgxKAACFyBJUIWAGQFt07HSzlLX8NcVZvRDp9KKEEAmblgsQkQaQMiEBSUdUWdEZiQCwCIeQ6R0no2MG6XiZgXLOwjLGd+VRbIuSzITLp/hbDRmumXDASYboul6fZG6HtZLCWUjGOMmh5K9M8nMoZhc0xVBmQmOq8Yna7JzGsqZZcNlu1mYMlMVQekJgWUJAs0ZFLpm2UpTSCZXlVEWRsgSIZVIkz4Lc26wkzJaXRtfWu3iKYgTDgUgGOtEUhK1IqZUqp/h0GiRCJwthSFrUqSLK0EsqpKyyV4TaBi6GiBkeWfUKQ1r7FcUuDxq5CkSlguYpAAADSw3CCTEkEVgCG0NoAUv0cAY40jJB0oUGQ8gTKFwspXDTYJRTfpct5fyp4gqyALRSKMyhfA0CpkoCuCQ7ZgBICInsOA0AzULUtdatgmh1bwuOCLVGzF5yLmXGy5F6r1yar5QKokQrNqisgJoPgPrlX+tpkioN68tWhqFVlDBtjNCkjQHofgCxmJoAcFGI1fAiEAH0r4gCwJK7Cu8gXlt7tPattha10AnpSBttIiRVuoMlY4sa/Wqu1oEma9Bg3asJGGkxZj16UExCK6gmhO3aDMFWmtOE6D1sIRWvua6W0bt6h27dvdkw9ugH2xVvrWVDsjoGi447U3TvkFyudIBvgZsNcxZdZosA/zFYsee88Iheh3oRGgVjoi2Psey6OFwSkACt9ZeONaa7YLAJCaGpmgXQOa82aELVgYtBajKUjoMAeQEgxg4KMdAL1fATjaBuJeuNN7HGjroA+nVYao2Uno5YJjA7r0OLpuxzjk7BFZoocxSVEg6BgCdJ/PiQKM3eDoAgTQ5HKMHwoxp2wsn5OKcAZoJAOBSIiHg74jW0VBMquE4m+9yaQ1ccEakuc1YABUdTQ1kz4NQTTm7dP6YUzg/umgVNqY0xRsYmnAtyeC0M4zpn5Dmcs+65jg67Mjs5Y5idgrXNqG+p58sk6fN+Yo223T/mgWSv8+25iJmzMWbdfk44pjn2zvyzZ+NaqOUapy6mupXXWMieywMFNzmfOCHkIITQf7+CAa4EAA==)

**Comment by jkotas** [comment]
Sharplab is using 6.0.0: https://sharplab.io/#v2:C4LgTgrgdgPgAgJgIwFgBQ65IJwAoCiUAbgJZgD2UAtgKZTAB0AajWAM4mUCUA3EA=== . Number of critical bug fixes have been backported between 6.0.0 and 6.0.7.

**Comment by jl0pd** [comment]
Found place where exception is thrown: clrjit -> importer.cpp -> line 16489. Unable to put link to file, because it takes eternity to open.
Stackdepth before `localloc` is one, that's why it throws invalid program.
![image](https://user-images.githubusercontent.com/36221916/181903316-864467e1-0800-43d1-8609-45244acb90a5.png)

If this is by-design and cannot be fixed, I can close issue

**Comment by jkotas** [comment]
Yes, this limitation is documented in ECMA-335 stack: "Correct CIL requires that the evaluation stack be empty, apart from the size item". We do not have plans to remove it.

**Comment by jl0pd** [comment]
Alright, then this problem should be handled on F#'s side. Thanks!
