### ISSUE TITLE
Question: Is there any document about the dotnet dump/gcdump file specification

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/runtime#73107]
Hi there, I want to implement a custom dotnet dump analysis tool, wondering that is there any document about the dotnet dump/gcdump file specification

**Comment by En3Tho** [comment]
https://github.com/dotnet/diagnostics/blob/main/documentation/dotnet-dump-instructions.md

https://github.com/dotnet/diagnostics - repo

**Comment by WeihanLi** [comment]
@En3Tho thanks very much
