### ISSUE TITLE
HTTP/3: Alt-Used incorrectly added to request

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#73123]
### Description

I've noticed that alt-used is being sent with HTTP/3 request headers even though HTTP/3 is pre-negotiated.

### Reproduction Steps

See unit test: https://github.com/dotnet/aspnetcore/commit/f080ac3f90b4bbc8c65bfe78d5b5cfff1ac5caa7

The second request headers contains alt-used header when it shouldn't:
```cs
Assert.True(request2Headers.ContainsKey("alt-used")); // This passes. It should fail
```

Note that the first request's is sending alt-svc response header (perhaps it shouldn't? Possible bug in Kestrel), but I don't see why the client would decide to use it. The client's already talking HTTP/3.

### Expected behavior

alt-used should only be present when alt-svc is used.

### Actual behavior

alt-used is present when HTTP/3 is pre-negotiated.

**Comment by JamesNK** [comment]
I came across a related issue - https://github.com/dotnet/runtime/issues/56876 - but it's from last year.

**Comment by karelz** [comment]
Duplicate of #56876
