### ISSUE TITLE
Lock contention issue in Reflection backport to full framework

### ISSUE THREAD

**Issue by jimmycartrette** [dotnet/runtime#73130]
There is a lock contention issue in Reflection in MemberInfoCache. It has been fixed in 3.1+.
Currently it is significantly impacting us, through usage of Autofac which can call this concurrently, which has brought down our servers a few times, that are all in this Monitor lock for reading.
Original pull request here: https://github.com/dotnet/runtime/pull/40116

Can we request a backport to .NET framework for this?

**Comment by ConcernedCitizen** [comment]
This is an issue for us as well.

**Comment by buyaa-n** [comment]
We have very high bar for servicing changes into .NET framework, as far as I know only security related servicing allowed, so most likely this will not approved for servicing. CC @GrabYourPitchforks @jeffhandley 

We would suggest instead to upgrade your code into .NET 6
