### ISSUE TITLE
NativeMemory.Realloc crashes

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#73143]
This is crashing on Windows because malloc calls into the app-local CRT, but realloc calls the OS provided implementation in ucrtbase.dll.

This is fallout from #68950 where malloc/free were added to WindowsAPIs.txt, but realloc wasn't. So the former two get resolved to a definition by the linker, but the latter goes through LoadLibrary/GetProcAddress at runtime.

An obvious fix would be to add realloc to the list.

But a question is whether `NativeLibrary.Alloc` shouldn't actually call into the OS provided implementation instead (would that be the canonical Windows libc?).

```csharp
using System;
using System.Runtime.InteropServices;

class Program
{
    static unsafe void Main()
    {
        void* ptr = NativeMemory.Alloc(16);

        for (int i = 0; i < 16; i++)
        {
            ((byte*)ptr)[i] = (byte)i;
        }

        NativeMemory.Realloc(ptr, 32);
    }
}
```

**Comment by jkotas** [comment]
We link to dynamic CRT in the shipping config after #71182. It means that we will use the OS provided CRT implementation by default. 

The mismatch is only problem for debug builds of the runtime where it only affects our own internal testing.

**Comment by MichalStrehovsky** [comment]
I think we'll still want to do something about this. It was very easy to root cause in a test. If someone hits it elsewhere, they're going to switch to the "we have a heap corruption" investigation mode and those are not fun.

**Comment by jkotas** [comment]
> I think we'll still want to do something about this. 

@MichalStrehovsky Anything else you would like to see done about this beyond what I have done #73190?

**Comment by MichalStrehovsky** [comment]
> > I think we'll still want to do something about this.
> 
> @MichalStrehovsky Anything else you would like to see done about this beyond what I have done in #73190?

That addresses the concern! Thank you!
