### ISSUE TITLE
[QUIC] Internal error (USER_CANCELLED) when trying to establish a connection

### ISSUE THREAD

**Issue by rzikm** [dotnet/runtime#73151]
When server QUIC Connection options callback throws an exception, the client-side connect call will throw `QuicException` with `QuicError.InternalError`

```
 System.Net.Quic.Tests.MsQuicTests.ConnectWithClientCertificate(sendCertificate: False, useClientSelectionCallback: False) [FAIL]
      System.Net.Quic.QuicException : An internal error has occurred. Status code: QUIC_STATUS_USER_CANCELED
      Stack Trace:
        C:\source\runtime\src\libraries\System.Net.Quic\src\System\Net\Quic\QuicConnection.cs(458,0): at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data)
        C:\source\runtime\src\libraries\System.Net.Quic\src\System\Net\Quic\QuicConnection.cs(515,0): at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent)
        C:\source\runtime\src\libraries\System.Net.Quic\src\System\Net\Quic\QuicConnection.cs(549,0): at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
        --- End of stack trace from previous location ---
```

Because this is something which is not under client's control, InternalError does not feel right. Possible solutions:
- Throw AuthenticationException (as user_canceled is a TLS alert)
- Expose the `UserCanceled` status as first-class `QuicError`
- map it to `ConnectionRefused` (probably bad decision, as the two signals come from different levels and it may confuse users when diagnosing what is going on)

**Comment by karelz** [comment]
Triage: We agree with `AuthenticationException` as stated above - in principal whatever bad happens during the handshake means that the authentication failed (same in `SslStream`).
If simple, we should get it in 7.0.
