### ISSUE TITLE
HttpStress and SslStress Windows builds failing in dotnet-install

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#73154]
https://dev.azure.com/dnceng/public/_build/results?buildId=1914390&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=abae1f68-3c73-5bff-491f-f2b908580ce6&l=5555

```
Get-CimInstance: C:\dotnet-install.ps1:208
Line |
 208 |      if( ((Get-CimInstance -ClassName CIM_OperatingSystem).OSArchitect …
     |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | FAILED
```

**Comment by antonfirsov** [comment]
@dotnet/dnceng since I can't reproduce this locally, I'm assuming the problem is that CIM is not available on `1es-windows-2022`. 

Is there an easy way to install it? Alternatively we can wait and see if https://github.com/dotnet/install-scripts/issues/298 will be addressed.

**Comment by adiaaida** [comment]
I don't think that it is because of the 1es pool, but because you are running the command on a nano server docker image. I think we will need to let the install-scripts team manage this one.

**Comment by MattGal** [comment]
> I don't think that it is because of the 1es pool, but because you are running the command on a nano server docker image. I think we will need to let the install-scripts team manage this one.

+1 here, but also you should absolutely be able to reproduce this locally with an appropriate local docker config. If you get stuck with this stop by the First Responders Teams channel and ask for help, and we'll try our best to walk you through it.

**Comment by antonfirsov** [comment]
This is fixed now with https://github.com/dotnet/website/pull/4218:
https://dev.azure.com/dnceng/public/_build/results?buildId=1925398&view=results
