### ISSUE TITLE
Invalid docker tag used on 7.0-preview5 testing

### ISSUE THREAD

**Issue by MattGal** [dotnet/runtime#73162]
@rzikm FYI.

This commit: https://github.com/dotnet/runtime/commit/8aac5ee2e821498684b385f443d2474db215b2ae from https://github.com/dotnet/runtime/pull/69603 moved testing of some scenarios in 7.0-preview5 to `mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-34-helix-20220523150939-4f64125`, which causes all Helix test runs trying to use this to fail and waste time trying to run.  (it doesn't exist)

This should be removed, or updated to latest from mcr.microsoft.com, e.g. `mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-34-helix-20220728174613-4f64125`

**Comment by ViktorHofer** [comment]
AFAIK, we can delete the old preview branches and they shouldn't enqueue builds anymore anyway. Does this also happen on main?

**Comment by ViktorHofer** [comment]
I just deleted the old branches which already have their corresponding tag:
- release/7.0-preview4
- release/7.0-preview5
- release/7.0-preview6

**Comment by hoyosjs** [comment]
Closing since the branches were deleted. Please reopen if we see more branches using images that don't exist. Main branch has moved from such one.
