### ISSUE TITLE
System.IO.Compression.GZipStream encrypt then decrypt results in diff byte sizes from original file

### ISSUE THREAD

**Issue by robcamer** [dotnet/runtime#73192]
ISSUE WITH System.IO.Compression.GZipStream 

# DESCRIPTION

When encrypting a file using GZipStream, we found that the resulting .zip when decrypted was a different byte size.

## REPRO STEPS

Sample project attached with three different size files: [net6compressionissue.zip](https://github.com/dotnet/core/files/9237700/net6compressionissue.zip)

1. Unzip project into a folder
2. Open Visual Studio Code
3. Type dotnet build | dotnet run
4. See results

## EXPECTED RESULTS

For each file when decrypted, the byte size is the same as the original file.

### ACTUAL RESULTS

Only the smallest file size resulted in byte size the same as the original file:

```bash
FIleName: test-files/TIP1.WAV --> Failure Size MisMatch: Original bytes differ from decompressed bytes at index 21179
FIleName: test-files/7fe2c7c5-4118-4580-91b7-a22167bfb0da.wav --> Failure Size MisMatch: Original bytes differ from decompressed bytes at index 11546
FIleName: test-files/89b2d923-02b9-49a9-9d98-f79c5327d063.wav --> Success: Decompressed bytes match original bytes
```

**Comment by Tornhoof** [comment]
Looking at your code, you ignore the return value of the ``Read`` method. It does not guarantee that read fills your array exactly. That's why .NET 7 will have a ``ReadExactly`` method.
https://devblogs.microsoft.com/dotnet/announcing-dotnet-7-preview-5/#readexactly-and-readatleast

**Comment by stephentoub** [comment]
What @Tornhoof said.  Stream.Read doesn't guarantee to read as much as requested, only that if you request more than 0 bytes and the stream hasn't yet reached EOF, it'll return at least 1.  If in your repro you change:
```C#
zipStream.Read(buffer, 0, size);
```
to instead be:
```C#
int total = 0;
while (total < size)
{
	int read = zipStream.Read(buffer, total, size - total);
	if (read == 0) break;
	total += read;
}
```
it then outputs:
```
FIleName: test-files/TIP1.WAV --> Success: Decompressed bytes match original bytes
FIleName: test-files/7fe2c7c5-4118-4580-91b7-a22167bfb0da.wav --> Success: Decompressed bytes match original bytes
FIleName: test-files/89b2d923-02b9-49a9-9d98-f79c5327d063.wav --> Success: Decompressed bytes match original bytes
```
Thanks.

**Comment by robcamer** [comment]
Thanks for the quick feedback
