### ISSUE TITLE
[mono][android] TargetSDKVersion=31 run on android12 os will hit assert.

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#73197]
Hi, I have embedded the old mono version with ue, when set android TargetSDKVersion=31 will hit assert in mini-arm64.c at line:

https://github.com/dotnet/runtime/blob/68bd58e0e68b22a3cbcc67a3f1218a6c8f623bcf/src/mono/mono/mini/mini-arm64.c#L5485

![image](https://user-images.githubusercontent.com/5187024/182264355-65bce033-9813-495d-afff-0a647888f203.png)

if only occurred on android12 os, and if the TargetSDKVersion=30 the error will disappear.

I think it may occur in dotnet/runtime too, so I open the issue here.

Don't know if it's been fixed or what the problem is.

**Comment by srxqds** [comment]
@vargaz  @lambdageek  can you help me?

**Comment by srxqds** [comment]
![image](https://user-images.githubusercontent.com/5187024/182568765-0756b358-993b-4cb6-b3c7-7fa00f428e6d.png)

I found the code - buf == buf_len， it must be < ?

**Comment by vargaz** [comment]
It was fixed by:
https://github.com/mono/mono/pull/18195

**Comment by srxqds** [comment]
ok thank you 
but what the reason about it?
