### ISSUE TITLE
Want to contribute to the Project but don't know where to start

### ISSUE THREAD

**Issue by freesix** [dotnet/runtime#732]
Hi,

Can I contribute to the Project? 

I'd like to improve my .Net skills.

I running VS 2017.

Where do I start? do I need to clone this repo to my PC?

**Comment by danmosemsft** [comment]
Hi @freesix we welcome new contributors!

Yes, please start with the document above. Note that our code is now in the dotnet/runtime repo, although most issues are still not moved there.

Here's some possible issues:
https://github.com/dotnet/corefx/labels/up-for-grabs
https://github.com/dotnet/runtime/labels/up-for-grabs

In particular
https://github.com/dotnet/corefx/issues?q=is%3Aopen+label%3Aup-for-grabs+label%3Aeasy
https://github.com/dotnet/runtime/issues?q=is%3Aopen+label%3Aup-for-grabs+label%3Aeasy

Do post here, or in the issue you're tackling, if you have any trouble.
