### ISSUE TITLE
JSON needs object initializer equivalent APIs

### ISSUE THREAD

**Issue by krwq** [dotnet/runtime#73219]
Recently C# has added two features which rely on the object initializer syntax:
- init-only properties
- `required` keyword

In the current state JSON reflection APIs can ignore the fact that property is `init-only` and still set it and `required` constraint is not enforced. For source-gen on the other hand regular setter code simply won't compile and similarly for `required` properties constructor will cause compile errors.

We should:
- update the contract model to allow for such construction - most likely this will be the same work as https://github.com/dotnet/runtime/issues/71944
- update source-gen code to use those APIs for init-only/required properties - this will likely need rather major refactoring of source-gen code which currently uses reflection APIs (reflection implementation over Roslyn APIs) which is missing a way to check if property is required - we will likely need to change it to use Roslyn APIs directly
- possibly, adjust reflection code to behave consistently with source-gen

One way to solve this problem is to treat `init-only` and `required` properties the same way as arguments to parametrized constructor, then passing them to parametrized constructor assigns them in the object initializer.

Relevant issues:
- https://github.com/dotnet/runtime/issues/58770
- https://github.com/dotnet/runtime/issues/70945
- https://github.com/dotnet/runtime/issues/71944
- https://github.com/dotnet/runtime/issues/71984
- https://github.com/dotnet/runtime/issues/46088

**Comment by jkotas** [comment]
> (reflection implementation over Roslyn APIs) which is missing a way to check if property is required

The reflection object does allow you to check whether the property is required by looking for `System.Runtime.CompilerServices.RequiredMemberAttribute`.

**Comment by eiriktsarpalis** [comment]
We might want to address this in combination with #71944.

**Comment by eiriktsarpalis** [comment]
Fixed in https://github.com/dotnet/runtime/pull/83147. Any outstanding work is tracked by the issues linked in the description.

**Comment by amis92** [comment]
So it's completed, but still in Future milestone - that's intentional?
