### ISSUE TITLE
Blazor WASM System.Text.Json memory leak with custom converter

### ISSUE THREAD

**Issue by m-chandler** [dotnet/runtime#73217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In production we observed an out of memory exception from our Blazor WASM apps on an abnormally busy day. The app was running for about 6 hours prior to the exception, and we were able to simply refresh the app. It never happened again. I have finally gotten around to investigating the cause of the memory leak (thinking it may have been our code).

There seems to be a memory leak when deserialising objects via custom converters. The string content being deserialised does not seem to matter, nor does the code within the custom converter. Simply the act of using a custom converter causes the issue. The number of properties on the object you're deserialising _to_ also seems to matter. More properties seems to exacerbate the issue. I have reproduced this issue in a minimal sample project.

Via Chrome dev tools I was able to take the following memory snapshots over 5 minutes with the sample project:
T+0: 79MB
T+1M: 187MB
T+2M: 267MB
T+3M: 382MB
T+4M: 547MB
T+5M: 647MB

![2022-08-02_8-35-13](https://user-images.githubusercontent.com/2039337/182258582-3348bb9a-a004-4a21-b034-f4557e693469.png)

### Expected Behavior

I would expect all memory to be released after deserialising JSON.

### Steps To Reproduce

Sample project with the issue here: https://github.com/m-chandler/blazor-wasm-system-text-json-custom-converter-memory-leak

When started, the sample project starts a loop which deserialises an empty JSON object using a custom converter every 10ms.

1. Clone project
2. Run project over a period of 5 minutes.
3. At 1 minute intervals, take memory snapshots via Chrome dev tools. Memory > Take snapshot.
4. Note increased memory utilisation.

### .NET Version

6.0.302

### Anything else?

dotnet --info

> .NET SDK (reflecting any global.json):
>  Version:   6.0.302
>  Commit:    c857713418
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.19044> .NET SDK (reflecting any global.json):
>  Version:   6.0.302
>  Commit:    c857713418
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.19044
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\6.0.302\
> 
> global.json file:
>   Not found
> 
> Host:
>   Version:      6.0.7
>   Architecture: x64
>   Commit:       0ec02c8c96
> 
> .NET SDKs installed:
>   5.0.302 [C:\Program Files\dotnet\sdk]
>   5.0.408 [C:\Program Files\dotnet\sdk]
>   6.0.102 [C:\Program Files\dotnet\sdk]
>   6.0.107 [C:\Program Files\dotnet\sdk]
>   6.0.202 [C:\Program Files\dotnet\sdk]
>   6.0.203 [C:\Program Files\dotnet\sdk]
>   6.0.302 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\6.0.302\
> 
> global.json file:
>   Not found
> 
> Host:
>   Version:      6.0.7
>   Architecture: x64
>   Commit:       0ec02c8c96
> 
> .NET SDKs installed:
>   5.0.302 [C:\Program Files\dotnet\sdk]
>   5.0.408 [C:\Program Files\dotnet\sdk]
>   6.0.102 [C:\Program Files\dotnet\sdk]
>   6.0.107 [C:\Program Files\dotnet\sdk]
>   6.0.202 [C:\Program Files\dotnet\sdk]
>   6.0.203 [C:\Program Files\dotnet\sdk]
>   6.0.302 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by lewing** [comment]
You are allocating in a relatively tight loop and there is some caching that happens in the json code for various reasons that might be causing the GC some difficulty in collecting collecting things https://github.com/dotnet/runtime/pull/51160

**Comment by m-chandler** [comment]
Hi @javiercn and @lewing thanks for the response and for looking into this.

My sample project was an attempt to highlight the issue I'm seeing in our app. I certainly didn't want to invent an issue because of bad code in the sample project 😂. When I noticed the climbing memory utilisation via the custom JSON converter (and that this didn't happen without the custom JSON converter), I thought I was onto something.

In our app we have a websocket connection which receives a relatively large amount of data in the span of about 20 minutes, but then this tapers off dramatically for the rest of the day. I can observe this app chewing up about 640MB of RAM towards the end of the day, whereas other similar apps which do not process as much data sit at around 200MB.

This doesn't preclude our apps from having some other memory leak...

--

I adjusted the sample project and:
1. Called GC.Collect(0) every ~ 1 second (100 loop iterations).
2. Exited after ~ 1 minute (6000 loop iterations).

After the loop finishes the app is still consuming a reported 268MB in chrome (up from 80-odd MB at startup).

If I can do anything to assist or test further please let me know.

**Comment by eiriktsarpalis** [comment]
I'd honestly be very surprised if adding the custom converter played a substantial role in the performance issue you're experiencing, considering it is not being used at all by the type your reproduction is deserializing. To illustrate, this console app will execute without any exceptions being thrown:
```C#
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

JsonSerializer.Deserialize<TestModel>("{}", new JsonSerializerOptions
{
    Converters = { new CustomJsonConverter() }
});

public class CustomJsonConverter : JsonConverter<object>
{
    public override object? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        => throw new NotImplementedException("should never be reached");

    public override void Write(Utf8JsonWriter writer, object value, JsonSerializerOptions options)
        => throw new NotImplementedException("should never be reached");
}

public class TestModel
{
    public string PropertyA { get; set; }
    public string PropertyB { get; set; }
    public string PropertyC { get; set; }
}
```
will deserialize successfully. 

The only substantially difference at runtime when registering a custom converter that won't be used is one added `JsonConverter.CanConvert` check, which will only be done once at initialization:

https://github.com/dotnet/runtime/blob/188fa93c85a1171372261f552f8561c36f992f3c/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Converters.cs#L192-L201

**Comment by eiriktsarpalis** [comment]
I think the problem here is not specfic to Blazor WASM or using custom converters. It would seem like the loop in your application is instantiating a new `JsonSerializerOptions` instance on each iteration:
```C#
while (true)
{
    var deserialised = JsonSerializer.Deserialize<TestModel>("{}", new JsonSerializerOptions
    {
        Converters = { new CustomJsonConverter() }
    });
    await Task.Delay(10);
}
```
This is [not recommended](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-configure-options?pivots=dotnet-6-0#reuse-jsonserializeroptions-instances) since every fresh options instance will have to recompute its metadata caches from scratch, which is substantially resource intensive compared to the serialization operation itself.

The simple workaround in your case would be to hoist the options instance outside the loop:

```C#
var options = new JsonSerializerOptions
{
    Converters = { new CustomJsonConverter() }
};

while (true)
{
    var deserialised = JsonSerializer.Deserialize<TestModel>("{}", options);
    await Task.Delay(10);
}
```

I'm fairly confident that once this change is made, you will see performance numbers drop back to what you were seeing before registering the custom converter.

**Comment by m-chandler** [comment]
@eiriktsarpalis thanks for your response and help / explanation.

That indeed does fix the issue in my sample project, and presumably fixes the issue in our app, as I'm doing the same thing there.

I'm not sure why I thought it was okay to construct a new JsonSerializerOptions every time. Should have read the manual I guess.

Thanks to all for your help, hope I didn't waste too much of your time!

I'll close this issue now.
