### ISSUE TITLE
[QUIC] CONNECTION_TIMEOUT may be misreported as IDLE_TIMEOUT

### ISSUE THREAD

**Issue by rzikm** [dotnet/runtime#73229]
when handling SHUTDOWN_COMPLETE event in QuicStream, we assume that an immediate local shutdown on a transport level is due to an idle timeout

https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs#L549

However, as https://github.com/dotnet/runtime/issues/73141 shows, we can hit the same branch due to CONNECTION_TIMEOUT. The difference between the two is that CONNECTION_TIMEOUT happens when we fail to get an ACK for a packet in some window of time (16s by default), so MsQuic assumes that the path to the peer is dead. CONNECTION_IDLE is a "graceful" close of connection due to inactivity.

**Comment by karelz** [comment]
Triage: Desired behavior is reporting consistently `CONNECTION_TIMEOUT` also from `QuicStream` (consistency with `QuicConnection`).
We need msquic change -- which has been merged and then 2 lines of code. If it is that simple, we should do it in 7.0 to make error conditions (although rare) consistent.

**Comment by rzikm** [comment]
MsQuic-side of the change was done in https://github.com/microsoft/msquic/pull/2932
