### ISSUE TITLE
[dotnet-sdk-7.0.100-rc.1.22379.5] NamedPipeServerStream.WaitForConnectionAsync() method throw "The operation was canceled." exception

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/runtime#73220]
**Application Name**:  ScreenToGif
**OS**: Windows 10 RS5
**CPU**: X64
**.NET Build Number**: dotnet-sdk-7.0.100-rc.1.22379.5
**App or App Source checking at**: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1585543
**Github Link**:
https://github.com/NickeManarin/ScreenToGif

**Verify Scenarios**:
1). Windows rs5 x64 + dotnet-sdk-7.0.100-rc.1.22401.1: Fail
2). Windows rs5 x64 + dotnet-sdk-7.0.100-rc.1.22379.5: Fail
3). Windows10 RS5 x64+dotnet-sdk-7.0.100-preview.7.22377.5: Pass
4). Windows10 RS5 x64+dotnet-sdk-6.0.400-win-x64: Pass

**Minimal repro steps**:
The machine only has dotnet-sdk-7.0.100-rc.1.22379.5 installed. Demo app attached 
[NamedPipeServerStreamDemo.zip](https://github.com/dotnet/runtime/files/9241156/NamedPipeServerStreamDemo.zip)

1.Create a .NET 7.0 Console app with default project template.
2.Replace with following source code in Programs.cs file:
```
using System.IO.Pipes;

public class PipeServer
{
    public static async Task Main()
    {
        NamedPipeServerStream pipeServer =
                new NamedPipeServerStream("testpipe", PipeDirection.In);

        CancellationTokenSource _source = new CancellationTokenSource();
        Console.WriteLine("Application has started. Ctrl-C to end");
        Console.CancelKeyPress += (sender, eventArgs) =>
        {
            Console.WriteLine("Cancel event triggered");
            _source.Cancel();
            eventArgs.Cancel = true;
        };

        await pipeServer.WaitForConnectionAsync(_source.Token);
        Console.WriteLine("Hello, World!");
    }
}
```
3. Press F5 to launch the app.
4. Press Ctrl + C to end the app.

**Expected Result**: 
The app will be ended without exception.

**Actual Result**:
“The operation was canceled” exception will be thrown.
![image](https://user-images.githubusercontent.com/83067197/182330309-21f6fd28-5959-4737-a442-b4e96dd61a04.png)

**Findings**:
When we remove "_source.Cancel();" from source code, the exception will not repro.

**Repro steps for app**:
**The machine only has dotnet-sdk-7.0.100-rc.1.22379.5 installed and DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX set as 2 in environment variable**.

1. Copy the app from ..../ScreenToGif to local machine.
2. Launch ScreenToGif.exe.
3. Click "Options".
4. Select "Allow multiple instances" in Startup part.

Expected Result: 
The "Allow multiple instances" will be selected.

Actual Result:
An "Unhandled exception" window will pop up and the app is crashed.
![image](https://user-images.githubusercontent.com/83067197/182330466-3ec60558-6f7c-4bb0-a6aa-99f926fc11d5.png)

After clicking "Show details" button on the window, it shows below stack trace:
```
   at System.IO.Pipes.NamedPipeServerStream.WaitForConnection()
   at System.Threading.AsyncOverSyncWithIoCancellation.InvokeAsync[TState](Action`1 action, TState state, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at System.Threading.AsyncOverSyncWithIoCancellation.InvokeAsync[TState](Action`1 action, TState state, CancellationToken cancellationToken)
   at System.Threading.AsyncOverSyncWithIoCancellation.InvokeAsync[TState](Action`1 action, TState state, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at ScreenToGif.Util.InterProcessChannel.PipeServer`1.ServerLoop() in C:\Users\v-altunc\Downloads\ScreenToGif-2.36\ScreenToGif-2.36\ScreenToGif.Util\InterProcessChannel\PipeServer.cs:line 40
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

```

**DotNet Info:**
```
.NET SDK:
 Version:   7.0.100-rc.1.22379.5
 Commit:    c674772706

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-rc.1.22379.5\

Host:
  Version:      7.0.0-rc.1.22378.2
  Architecture: x64
  Commit:       97749c034e

.NET SDKs installed:
  7.0.100-rc.1.22379.5 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0-rc.1.22379.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0-rc.1.22378.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 7.0.0-rc.1.22377.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```
@dotnet-actwx-bot @dotnet/compat

**Comment by stephentoub** [comment]
I'm not understanding the problem.  A cancellation token is passed in to WaitForConnectionAsync so that if cancellation is requested it'll be canceled.  Cancellation is requested.  The await on the WaitForConnectionAsync throws a cancellation exception, which is how cancellation is communicated in every API throughout .NET that accepts a cancellation token.  This is all by design.

**Comment by stephentoub** [comment]
> a bug where a cancellation request was frequently ignored

You can see this with your repro, actually.  The repro cites "Expected Result: The app will be ended without exception.", but if you try your repro on .NET 6, you'll see that after pressing ctrl-C, the app doesn't actually end.  It just hangs forever waiting for a connection.

**Comment by Junjun-zhao** [comment]
@stephentoub Thanks for your detailed clarification and confirmation. Since this behavior change is by design, we will close this bug.
