### ISSUE TITLE
NativeAOT Symbol Stripping on OSX with binutils

### ISSUE THREAD

**Issue by jamsoft** [dotnet/runtime#73280]
I have a NativeAOT application compiling on Windows, Linux and OSX.

On Linux post compilation I can run this command and strip successfully:

```
objcopy --strip-unneeded MyExecutable
```

When I tried the same on OSX at first it couldn't find the command and doing a few `mdfind` searches didn't turn anything up. So I installed `binutils` using `brew install`.

Once I'd run the same command against the OSX executable it processed the executable without any errors but the executable could no longer launch.

Not sure of how to proceed. Is there an alternative to `binutils` that should be used for NativeAOT executables?

**Comment by MichalStrehovsky** [comment]
The latest builds support setting `<StripSymbols>true</StripSymbols>` in your project file to do this for you: https://docs.microsoft.com/en-us/dotnet/core/deploying/native-aot#native-debug-information

You need pretty bleeding edge latest NativeAOT since this is relatively new (Preview 7 builds might have it, RC1 for sure).

**Comment by jamsoft** [comment]
Right, thanks for the reply.

Due to some other issues in the libraries and frameworks I'm using I can't currently switch from the preview to RC versions. I think I have a bit of a waiting game on my hands.

**Comment by MichalStrehovsky** [comment]
You can reverse engineer what it does on OSX from the targets; https://github.com/dotnet/runtime/blob/6251d496e307ed39f1e600cd036106cc1bd7e340/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Unix.targets

Looks like it's dsymutil and strip.

**Comment by jamsoft** [comment]
Ahhhhh, many thanks. Will investigate.

**Comment by MichalStrehovsky** [comment]
I think we can close this.

**Comment by jamsoft** [comment]
Just a quick follow up for anyone else reading.

```
dsymutil <executable>
strip <executable>
```

Works like a charm!
