### ISSUE TITLE
[wasm][debugger] Detect when overriding field is overridden on `GetProperties`

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#73298]
Continuation of https://github.com/dotnet/runtime/issues/69788 for VOO case. 

Problem:
having derived classes of the structure as in DebuggerTests.GetProperties, where "X <- Y" means "X inherits from Y":
DerivedClass2 <- BaseClass2 <- BaseBaseClass2 ; that have member properties, correspondingly:
override prop <- override prop <- virtual prop
should result in displaying 1 property on GetProperies called on DerivedClass2 and these propery is:
prop from DerivedClass2.
However, currently we are displaying BaseClass2's property as well. We lack information how to detect an overridden overriding field.

short pseudocode to picture VOH, VHO and VOO cases:
```
BaseBaseClass2 {
  virtual VOH; // isNewSlot: True, should be hidden, OK
  virtual VHO; // isNewSlot: True, should be visible, OK
  virtual VOO; // isNewSlot: True, should be hidden, OK
}
BaseClass2 {
  override VOH; // isNewSlot: False, should be visible, OK
  new virtual VHO; // isNewSlot: True, should be hidden, OK
  override VOO; // isNewSlot: False, should be hidden, FAIL (is visible!)
}
DerivedClass2 {
  new VOH; // isNewSlot: False, should be visible, OK
  override VHO; // isNewSlot: False, should be visible, OK
  override VOO; // isNewSlot: False, should be visible, OK
}
```

Reproduction:
find in GetPropertiesTests test all the comments: // FixMe: Issue #69788 and uncomment them. They contain VOO testcases.

**Comment by thaystg** [comment]
This is fixed by the new debugger.
