### ISSUE TITLE
AndroidManifest can not be set to an absolute path

### ISSUE THREAD

**Issue by Falco20019** [dotnet/runtime#73311]
### Description

`Microsoft.Android.Sdk.DefaultProperties.targets` is always settings `$(AndroidManifest)` to `AndroidManifest.xml` if empty. `Xamarin.Android.Common.targets` is settings `_AndroidManifestAbs` always to `$(ProjectDir)$(AndroidManifest)` as long as `$(AndroidManifest)` is not empty.

There is no clean way to set the path to an absolute one (as part of an SDK) besides hooking in before `_GetAndroidPackageName` and resetting `$(AndroidManifest)` and defining `$(_AndroidManifestAbs)` myself. This feels a bit hacky.

### Reproduction Steps

Set `<AndroidManifest>C:\...\AndroidManifest.xml</AndroidManifest>`

### Expected behavior

`'$(_AndroidManifestAbs)' == 'C:\...\AndroidManifest.xml'`

### Actual behavior

`'$(_AndroidManifestAbs)' == '$(ProjectDir)C:\...\AndroidManifest.xml'`

### Known Workarounds

```xml
<Target Name="_FixAndroidManifest" BeforeTargets="_GetAndroidPackageName" Condition="$(TargetFramework.StartsWith('net6.0-android'))">
  <PropertyGroup>
    <_AndroidManifestAbs Condition=" '$(AndroidManifest)' != '' ">$(AndroidManifest)</_AndroidManifestAbs>
    <AndroidManifest Condition=" '$(AndroidManifest)' != '' "></AndroidManifest>
  </PropertyGroup>
  <Message Importance="High" Text="Patched path for manifest" />
</Target>
```

**Comment by SamMonoRT** [comment]
Tracked via https://github.com/xamarin/xamarin-android/issues/7243   -  Closing this issue.
