### ISSUE TITLE
Old account

### ISSUE THREAD

**Issue by ErhanAtesoglu** [dotnet/runtime#73313]
Hi,

I made a few contribution under the eanova account.  I got locked out of that account and was hoping someone could stop the emails from coming through.  I believe a simple ban can remove the emails.

Thanks,

Erhan Atesoglu

**Comment by Clockwork-Muse** [comment]
I'd first recommend attempting to contact GitHub customer support about recovering the old account (Especially since you do have access to the email account).

That aside, you should be able to configure your email provider to auto-delete emails based on the username.

**Comment by ErhanAtesoglu** [comment]
Thanks everyone,  I'll give it another go with GitHub support.
