### ISSUE TITLE
Remove Microsoft.NETCore.Platforms from test_runtime\project.json

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/runtime#7332]
We shouldn't need https://github.com/dotnet/coreclr/blob/master/tests/src/Common/test_runtime/project.json#L3 this entry here, as the entry in test_dependencies/project.json should take care of this dependency - removing that line from test_runtime causes build breaks that look like:

> error : One or more packages are incompatible with .NETCoreApp,Version=v1.1 (ubuntu.16.10-x64). [D:\j\workspace\debug_windows---17180f1b\tests\build.proj]

So something must be overwriting the Microsoft.NETCore.Platforms from test_depencies/project.json.

**Comment by jkoritzinsky** [comment]
With the live builds in the consolidated repo, this no longer exists, so we can close this issue.
