### ISSUE TITLE
TypeEquivalence - value types with a `static` method shouldn't fail to load

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#73322]
If an assembly is marked with `PrimaryInteropAssemblyAttribute`, all public value types are validated for TypeEquivalence. This works without issue unless the value type contains a method, at which point a failure will occur:

```
  System.TypeLoadException: Could not load the structure '<TYPE_NAME>' from assembly '<ASSEMBLY_NAME>'. The structure is marked as eligible for type equivalence, but it has a method.
```

However, if the type only has methods that are marked `static`, this should be permitted.

Fails as expected:
```csharp
struct T
{
    public int F;
    public void M() { }
}
```

Consider supported:
```csharp
struct T
{
    public int F;
    public static void M() { }
}
```

**Comment by jkotas** [comment]
> However, if the type only has methods that are marked static, this should be permitted.

Is there an end-to-end scenario that this would enable? 

Roslyn would not be able to copy the method over for no-PIA embedding, so you would be able to really take advantage of the static methods in end-to-end scenarios that the type equivalence was designed for.

**Comment by AaronRobinsonMSFT** [comment]
> Is there an end-to-end scenario that this would enable?

This was something I noticed while updating some tests. It wasn't obvious why this is the case.

> Roslyn would not be able to copy the method over for no-PIA embedding

The shape/layout of the struct should still be copiable though. If this idea blocks Roslyn though then I agree it should be kept as is.

**Comment by jkotas** [comment]
Roslyn seems to be handling it just fine. I guess we can delete the superfluous validation if we care around.

**Comment by AaronRobinsonMSFT** [comment]
Failing repro code:

```csharp
using System;
using System.Runtime.InteropServices;

[assembly:PrimaryInteropAssembly(1,0)]

public struct T
{
    public int F;
    public static void M() { }
}

public class Program
{
    public static void Main()
    {
        Console.WriteLine(typeof(T).Name);
    }
}
```
