### ISSUE TITLE
CI build failed: "Agent was purged, cancelling the pipeline"

### ISSUE THREAD

**Issue by noahfalk** [dotnet/runtime#73339]
CI build [1918768](https://dev.azure.com/dnceng/public/_build/results?buildId=1918768) failed with a cryptic error "Agent was purged, cancelling the pipeline"

https://dev.azure.com/dnceng/public/_build/results?buildId=1918768&view=logs&j=86357178-b8b8-53d0-d37b-335a1e08c946

This issue was reported in another build as well and there is an unconfirmed hypothesis that it relates to an underlying issue in Azure scale sets. The infra team is investigating.

|Build|Kind|Start Time|
|---|---|---|
[1918768](https://dev.azure.com/dnceng/public/_build/results?buildId=1918768)|Rolling|2022-02-08|

**Comment by BruceForstall** [comment]
Closing, as tracking issue https://github.com/dotnet/arcade/issues/10279 was closed
