### ISSUE TITLE
JIT: Assertion failed '!m_VariableLiveRanges->back().m_EndEmitLocation.Valid()'

### ISSUE THREAD

**Issue by cshung** [dotnet/runtime#73355]
[This](https://github.com/dotnet/runtime/issues/57752) is happening again when compiling `System.Private.CoreLib` targetting ARM64.

Here is the repro command:

```
dotnet.cmd artifacts\bin\coreclr\windows.x64.Debug\crossgen2\crossgen2.dll -o:artifacts\bin\coreclr\windows.x64.Debug\System.Private.CoreLib.dll -r:artifacts\bin\coreclr\windows.x64.Debug\IL\*.dll --targetarch:x64 -O --verify-type-and-field-layout artifacts\bin\coreclr\windows.x64.Debug\IL\System.Private.CoreLib.dll --pdb --pdb-path:artifacts\bin\coreclr\windows.x64.Debug\PDB --map --targetarch:arm64
```

And here is the assertion:
```
Assertion failed '!m_VariableLiveRanges->back().m_EndEmitLocation.Valid()' in 'System.Numerics.Matrix4x4:<Invert>g__SseImpl|68_0(System.Numerics.Matrix4x4,byref):bool' during 'Generate code' (IL size 1493; hash 0xb8fd39db; FullOpts)
```

The repros on 197ae4c596553f7e6acb327ca2e31cc00c794c4d.

When the assertion happens, we have a curious case that a variable is dying but also spilled. This doesn't make sense to me, why would we spill a variable if we know it is dying?

```
0:024> .frame 0x08
08 000000d1`fc77c950 00007ffd`19de642a     clrjit_universal_arm64_x64!TreeLifeUpdater<1>::UpdateLifeVar+0xfb6 [D:\runtime\src\coreclr\jit\treelifeupdater.cpp @ 446] 
0:024> dv
           this = 0x0000028e`05dd0c78
           tree = 0x0000028e`056044d0 963: [[GT_LCL_VAR, TYP_SIMD16]
         varDsc = 0x0000028e`05b4df58 [V22: TYP_SIMD16]
        isDying = true
         isBorn = false
     lclVarTree = 0x0000028e`056044d0 963: [[GT_LCL_VAR, TYP_SIMD16]
 indirAddrLocal = 0x00000000`00000000
          spill = true
         lclNum = 0x16
isMultiRegLocal = false
```

The `isDying` flag is causing `siStartOrCloseVariableLiveRanges` to close the range, so the subsequent `spill` caused `siUpdateVariableLiveRange` to expect the range is still open, thus leading to the assertion.

This was found in an issue [here](https://github.com/dotnet/runtimelab/issues/1946) in the hot-cold-splitting experiment [here](https://github.com/dotnet/runtimelab/tree/feature/hot-cold-splitting), but this has nothing to do with hot cold splitting, the JIT dump indicates the function is not split at all and it repros without any hot-cold splitting related changes.

@amanasifkhalid, @EugenioPena 

@BrianBohe - just FYI

category:correctness
theme:debug-info
skill-level:intermediate
cost:small
impact:small

**Comment by jakobbotsch** [comment]
Note that you are compiling x64 SPC for Arm64. So it is probably the same as https://github.com/dotnet/runtime/issues/57752#issuecomment-910769048 where crossgen2 is telling the JIT that a lot of x64-only intrinsics might be supported in an Arm64 compilation. So this probably ends up being some kind of ABI stress test for the JIT, with all these intrinsics becoming regular calls taking vectors.
Just to confirm, but you do not see this assert compiling an Arm64 SPC targeting Arm64, right?

**Comment by jakobbotsch** [comment]
Andy has a note here on the cause:
https://github.com/dotnet/runtime/pull/38894#issuecomment-655840714

**Comment by JulieLeeMSFT** [comment]
Thanks @jakobbotsch for triaging this issue.

**Comment by BrianBohe** [comment]
I am happy to say that this no longer reproduces. Related examples issue [57752](https://github.com/dotnet/runtime/issues/57752) are working correctly also. Probably fixed after [79182](https://github.com/dotnet/runtime/pull/79182).
