### ISSUE TITLE
.Net SMTP client throttling outgoing mail

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#73353]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Net-SMTP-client-throttling-outgoing-mai/1283706)._

---
<p>We have an application that uses the .net smtp client class to send email notifications.  This is a multi-threaded process and should be sending out numerous emails, however it seems that on windows server 2016,  the .net smtp client is throttling the number of emails that are being sent to 2 per second.  Is there a way to increase the number of emails the smtp client will send out? </p><p>Thanks in advance.    </p>

---
#### Feedback Bot on 12/10/2020, 00:22 AM: 

(private comment, text removed)

**Comment by karelz** [comment]
Triage: System.Net.Mail does not have any built-in throttling. It is usually the server doing the throttling. Please check it first.
Closing. If there is more evidence there is something wrong with System.Net.Mail on .NET Core, feel free to reopen with additional info. Thanks!
