### ISSUE TITLE
High CPU usage in docker when service is not doing anything

### ISSUE THREAD

**Issue by black-empower** [dotnet/runtime#73361]
### Description

Hi,
currently we are experiencing the problem that our dotnet api run with 200% CPU on linux if they are contained in a docker container and not doing anything at the moment.
This problem does not seem to happen if the application is run natively on the system.
But it happens if the application is startetd through kubernetes or as a normal docker container.

### Configuration
The base image used is mcr.microsoft.com/dotnet/aspnet:6.0-alpine but the same issue can be reproduced with mcr.microsoft.com/dotnet/sdk:6.0-alpine and the 6.0-focal build.
This problem only started happening after updating our base system from ubuntu 18.04. to ubuntu 20.04.

### Data
Looking at top in linux you see the following situation:
![grafik](https://user-images.githubusercontent.com/51812248/182778371-5b7237a7-36dd-4dfb-a3f6-8a286164b942.png)
Looking at counters we can see the following picture:
![grafik](https://user-images.githubusercontent.com/51812248/182796467-9ecba288-f396-4dd6-b975-c41026b649c1.png)

### Analysis
After we first encountered the problem we did a performance profile using dottrace in the container it was happening.
We could see that over 70% of the used CPU is consumed by a method called WaitNative in the LowLevelLifoSemaphore.
![grafik](https://user-images.githubusercontent.com/51812248/182797257-fe16a46f-84dc-4b83-9a71-d9605de5d66a.png)
So our current assumption would be that there is some kind of problem with the call there when the dotnet application is running in a container.

Could you please take a look.
Thanks.

Best regards

**Comment by EgorBo** [comment]
Just curious what does `Environment.ProcessorCount` return in your container vs native?

**Comment by black-empower** [comment]
I created a test application and let it run both on the system and in the container.
Both times it returned the following output:

No of CPUs: 4

**Comment by quan0zhou** [comment]
Is there a dead loop in the program, it feels like the cpu is always in a busy state

**Comment by mangod9** [comment]
Hi @black-empower, 

do you have a standalone repro available? Or would it be possible to share a dump/trace you have collected? Thx

**Comment by black-empower** [comment]
@mangod9 : i found out what the problem is. There was some code in the application which regularly is reading Console.OpenStandardInput() regularly to stop an application if its run as a service outside of a container.
This works fine if the application is running nativly on Windows or Linux, but results in very large CPU Times if the application is run in a docker container.

**Comment by black-empower** [comment]
Hi, i only know that the team responsible for that part of the software implementing something to check for the keypress of "q" to quit the application and they do this using that method.
But we can close this case since everyone agreed that this should not be relevant when the application is deployed as a container.
