### ISSUE TITLE
STJ source generation fails when class contains a property of type JsonSerializerOptions

### ISSUE THREAD

**Issue by jeanplevesque** [dotnet/runtime#73371]
### Description

System.Text.Json source generation fails when a class containing a property of type `JsonSerializerOptions` is registered to a `JsonSerializerContext`.

### Reproduction Steps

1. Create a class like this:
```csharp
public class SomeClass
{
	[JsonConverter(typeof(JsonSerializerOptionsConverter))]
	public JsonSerializerOptions SerializerOptions { get; set; }
}
```

2. Create a JsonConverter like this:
```csharp
/// <summary>
/// This converter can be used to capture the <see cref="JsonSerializerOptions"/> used during deserialization.
/// </summary>
public class JsonSerializerOptionsConverter : JsonConverter<JsonSerializerOptions>
{
	public override JsonSerializerOptions Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
	{
		return options;
	}

	public override void Write(Utf8JsonWriter writer, JsonSerializerOptions value, JsonSerializerOptions options)
	{
		return;
	}
}
```

3. Enable source generation for the original class:
```csharp
[JsonSerializable(typeof(SomeClass))]
public partial class JsonContext : JsonSerializerContext
{
}
```

### Expected behavior

Source generation should work.

### Actual behavior

Source generation fails with the following error.
```
1>C:\...\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\JsonContext.ConverterStrategy.g.cs(12,102,12,119): error CS0122: 'ConverterStrategy' is inaccessible due to its protection level
```

### Configuration

- This is a .Net Standard 2.0 library.
- The issue happens in all configurations and architectures.
- I'm using System.Text.Json version 6.0.5.

#### Why I am doing this?
I'm trying to lazy-deserialize a JWT.
This is a more complete version of my code:
```csharp
public class AuthenticationData
{
	[JsonIgnore]
	public AuthenticationToken AccessTokenPayload => AccessToken == null ? null : new JwtData<AuthenticationToken>(AccessToken, SerializerOptions).Payload;

	[JsonPropertyName("access_token")]
	public string AccessToken { get; set; }

	[JsonPropertyName("refresh_token")]
	public string RefreshToken { get; set; }

	[JsonConverter(typeof(JsonSerializerOptionsConverter))]
	public JsonSerializerOptions SerializerOptions { get; set; }
}
```
The `JwtData<T>` class simply uses System.Text.Json to deserialize the payload from an access token string. I want to pass it the same `JsonSerializerOptions` that were used to deserialize the class itself.

**Comment by eiriktsarpalis** [comment]
I can reproduce, strangely enough it only occurs when using the source generator from the NuGet package. `ConverterStrategy` is an internal type inside System.Text.Json, so presumably the source generator gets something wrong on accessibility modifiers, but only for the NuGet build.

Minimal reproduction:
```C#
using System.Text.Json;
using System.Text.Json.Serialization;

[JsonSerializable(typeof(JsonSerializerOptions))]
public partial class JsonContext : JsonSerializerContext
{
}
```
Project configuration
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="7.0.0-preview.6.22324.4" />
  </ItemGroup>
</Project>
```

**Comment by krwq** [comment]
I understand the issue now.

The actual minimum repro is:

```csharp
    [JsonSerializable(typeof(JsonConverter))]
    public partial class JsonContext : JsonSerializerContext
    {
    }
```

but minimum repro where nuget package or lack of it doesn't make any difference is following:

```csharp
    [JsonSerializable(typeof(Foo))]
    public partial class JsonContext : JsonSerializerContext
    {
    }

    public class Foo
    {
        internal Bar Asd { get; set; }
    }

    internal class Bar
    {
    }
```

so essentially following conditions have to be met:
- context is public
- type on JsonSerializable (or one of the members of any of the types which end up being serialized) is public
- the type mentioned above has to have any non-public members

the reason NuGet package makes a difference in the original repro is because we compile against ref assembly which doesn't have any public members.

I'll investigate if there is any easy fix. If this turns out more complex (or too much code churn) I'll move this issue to 8.0.

**Comment by maksimnarkevichdp** [comment]
Hi there! We are experiencing the same problem with internal types and members of the source-generated class. Since it is going to be released only together with .NET 7, are there any feasible workarounds for that issue atm?

**Comment by eiriktsarpalis** [comment]
My recommendation would be to use dedicated DTOs for the source generated models that don't contain any internal members that might interfere with the source generator.
