### ISSUE TITLE
BigInteger.TrailingZeroCount(0) returns 32 

### ISSUE THREAD

**Issue by c-ohle** [dotnet/runtime#73376]
### Description

BigInteger.TrailingZeroCount(0) returns 32.

### Reproduction Steps

```C#
var c = BigInteger.TrailingZeroCount(0);
Debug.WriteLine(c); 
```

### Expected behavior

The return value should be -1 like in professional c++ math packages.

### Actual behavior

BigInteger.TrailingZeroCount(0) returns 32.

**Comment by c-ohle** [comment]
@dakersnar I guess GNU GMP is the most common.

**Comment by tannergooding** [comment]
The exact value returned by `TrailingZeroCount(0)` is often left up to be "undefined".

.NET normalized, quite some time back, on it being a value between `0` and `GetByteCount() * 8` and since `BigInteger` is variable length, this means that it will currently return "32".

**Comment by c-ohle** [comment]
@tannergooding Yes, many things are currently "undefined" or not really logical - and not to be changed later - I will do my best not to make such mistakes for the BigRatioan spec.
Please, if there is time - big progress on BigRational, builder obsolete and the new approach could easily be applied to BigInteger - at least to solve the buffer problem and reduce memory wastage.

**Comment by tannergooding** [comment]
.NET 7 has already reached "code complete" and no more significant changes are planned, only minor bug fixes and perf improvements.

.NET 8 may get perf improvements for BigInteger and other scenarios, but as indicated on the other issue it will likely not use a stack based or similar approach. It will likely use something like a standard builder pattern instead.

**Comment by c-ohle** [comment]
@tannergooding Just to make sure - it works for `BigInteger` and oll other cases, **without stack**, simply using the standard arithmetic syntax. 
This is what I'm simulating in the examples. A "standard builder pattern" approach to numerics would simply mean overhead.
