### ISSUE TITLE
Illegal runtime behavior in C++ code taking reference to null pointer

### ISSUE THREAD

**Issue by RobertHenry6bev** [dotnet/runtime#73392]
### Description

On linux-x64 using clang-11 -fsanitize-undefine -O3 -g ... to compile the runtime at tag v7.0.0-preview.6.22324.4 shows several (more) cases at runtime where a reference is created by going through a null pointer.  Since this is a runtime check (inserted by the C++ compiler), there is no guarantee that there are not more cases of this in code I didn't happen to execute in my trivial test app.

Here are cut&pastes of diffs of my local modd'ed source tree to shut up the sanitizer, rather than fixing the underling problem.

```diff
diff --git a/src/coreclr/jit/gentree.h b/src/coreclr/jit/gentree.h
index afd71a684..82a006ecf 100644
--- a/src/coreclr/jit/gentree.h
+++ b/src/coreclr/jit/gentree.h
@@ -4715,7 +4715,10 @@ public:
         }

         // clang-format off
-        CallArg& operator*() const { return *m_arg; }
+        CallArg&
+        __attribute__((no_sanitize("undefined")))
+        operator*() const { return *m_arg; }
+
         CallArg* operator->() const { return m_arg; }
         CallArg* GetArg() const { return m_arg; }

diff --git a/src/coreclr/jit/jitstd/list.h b/src/coreclr/jit/jitstd/list.h
index 734158147..b8c40f0c5 100644
--- a/src/coreclr/jit/jitstd/list.h
+++ b/src/coreclr/jit/jitstd/list.h
@@ -971,9 +971,12 @@ T& list<T, Allocator>::iterator::operator*()
 }

 template <typename T, typename Allocator>
-T* list<T, Allocator>::iterator::operator&()
+T*
+__attribute__((no_sanitize("undefined")))
+list<T, Allocator>::iterator::operator&()
 {
     return &(m_pNode->m_value);
```

### Reproduction Steps

Compile and run the test suite with clang-11 -g -O0 -fsanitize=undefined

### Expected behavior

no runtime errors discovered

### Actual behavior

runtime errors discovered

### Known Workarounds

Use suppressions to silence the undefined behavior sanitizer.  It is possible that nothing "bad" happens in actuality in the runtime, but who knows?

### Configuration

See above.

### Other information

https://github.com/dotnet/runtime/pull/73113/files removed a similar issue by mechanical transformation (I think...)

**Comment by jakobbotsch** [comment]
I believe @AaronRobinsonMSFT fixed these in #73424, #73507 and #74378.
