### ISSUE TITLE
Crossgen2 determinism issue found in Roslyn

### ISSUE THREAD

**Issue by davidwrighton** [dotnet/runtime#73403]
### Description

Crossgen2 isn't always producing the same results every time.

### Reproduction Steps

See issue dotnet/roslyn#63145 for details.

### Expected behavior

Crossgen2 should produce the same file every time

### Actual behavior

Sometimes it doesn't.

**Comment by mangod9** [comment]
Is this just because we are parallelizing compilation? Does it occur with `--parallelism 1` ?

**Comment by davidwrighton** [comment]
This probably caused by parallelizing compilation, yes. In particular, the problem here is that the field symbol computation is based on FieldDesc instead of FieldDescAndToken. This dependence on FieldDesc to drive the hashtable opens us up to ordering dependency problems, however, it is fairly desirable in several ways. I'm going to look into what the appropriate fix is tomorrow.

**Comment by davidwrighton** [comment]
In particular, there are several different MemberRefs in the dll which refer to the same field (but with different generic instantiations).  (Tokens 0A00011F, 0A000129, 0A000132, 0A00013E, and 0A000251) With the design of the R2R file format, it is possible to use any of these MemberRefs to refer to the same field. However, the path to doing so is not stabilized properly and so we lose determinism. I'll be looking into what it takes to stabilize this.
