### ISSUE TITLE
CI build: Slow macs causing random legs to timeout

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#73401]
Our OSX legs are sometimes given an extremely slow mac from the pool, resulting in the “Build Product” stage timing out. In most cases, the build will only make it half-way through the runtime portion and make it seem like there is something fundamentally wrong.  
 
When we get an impacted machine, I’ve noticed the following behaviors:
 
	•	Checkout of dotnet/runtime takes longer than normal
	•	Install build dependencies (if the leg has it) takes around double the time it normally would
	•	dotnet restore takes around 10 minutes or longer to complete
	•	The build will not make it through the runtime portion before timing out
 
In the past 30 days, legs starting with Build OSX, iOS, tvOS, and MacCatalyst have been impacted 84 times. This includes legs on the dev-innerloop, linker-tests, runtime, and runtime-official.  Here’s the Kusto query I’ve used to track this down.  You’ll need access to the engineeringdata to use it:

```
let osxbuilds=
  TimelineRecords
  | where Name startswith "Build OSX" or Name startswith "Build iOS" or Name startswith "Build tvOS" or Name startswith "Build MacCatalyst"
  | where Result == "canceled"
  | project RecordId;

TimelineIssues
| where Message == "The operation was canceled."
| join kind=inner(
  TimelineRecords 
  | where StartTime > ago(30d) and Name == "Build product" and Result == "canceled" and Name == "Build product"
  | where ParentId in (osxbuilds)
) on TimelineId,RecordId
| extend runtime = FinishTime - StartTime
| where runtime > 60m
| order by TimelineId
```
Example azdo builds:

https://dev.azure.com/dnceng/public/_build/results?buildId=1892946&view=results (runtime-innerdev-loop osx x64)

https://dev.azure.com/dnceng/public/_build/results?buildId=1915976&view=results (runtime ios-arm)

https://dev.azure.com/dnceng/public/_build/results?buildId=1914841&view=results (dotnet-linker-tests osx x64)

Example log:

https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1892946/logs/89 

We’ve raised this issue with the AzDo team managing the macs.  When we did so previously, they were not able to find any indication.  I think this issue might have to be pinned as a known issue.

### Error message
```json
{
   "errorMessage" : "Slow macs causing random legs to timeout"
}
```

#### Manually calculated
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
3 | 36 | 112

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by agocke** [comment]
Closing this out because it doesn't seem to be reproing right now.
