### ISSUE TITLE
[wasm] WBT test failure - `SimpleSourceChangeRebuildTest.SimpleStringChangeInSource`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#73419]
[Rolling build](https://dev.azure.com/dnceng/public/_build/results?buildId=1923908), and [log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-d05c7af00b554824ba/Workloads-.SimpleSourceChangeRebuildTest/1/console.4a0a724a.log?helixlogtype=result).

```
    Wasm.Build.NativeRebuild.Tests.SimpleSourceChangeRebuildTest.SimpleStringChangeInSource(buildArgs: BuildArgs { ProjectName = placeholder, Config = Release, AOT = True, ProjectFileContents = placeholder, ExtraBuildArgs =  }, nativeRelink: False, invariant: False, host: Chrome, id: "kfqswgdd.hbi") [FAIL]
      CompareStat failed:
      [Expected unchanged file: System.Private.CoreLib.dll.bc]
         old: FileStat { Exists = True, LastWriteTimeUtc = 8/4/2022 9:01:26 PM, Length = 16570448, FullPath = /datadisks/disk1/work/AEEC0971/w/AF8A095A/e/kfqswgdd.hbi/obj/Release/net7.0/browser-wasm/wasm/for-publish/System.Private.CoreLib.dll.bc }
         new: FileStat { Exists = True, LastWriteTimeUtc = 8/4/2022 9:02:39 PM, Length = 16570448, FullPath = /datadisks/disk1/work/AEEC0971/w/AF8A095A/e/kfqswgdd.hbi/obj/Release/net7.0/browser-wasm/wasm/for-publish/System.Private.CoreLib.dll.bc }
```

Some of the source assemblies are getting aot'ed again, when rebuilding with no changes. This seems to have been introduced in https://github.com/dotnet/runtime/pull/72394 which disabled caching:
https://github.com/dotnet/runtime/blob/bf362e876cba86a19fd6a721a4e694526361e661/src/tasks/Common/FileCache.cs#L32

It didn't get caught because the WBT tests were failing to build because of https://github.com/dotnet/runtime/issues/73312 .

cc @steveisok @mdh1418

**Comment by karelz** [comment]
Thanks @radical for quick fix! I removed blocking-clean-ci label, assuming the problem is now gone.
