### ISSUE TITLE
[NativeAot] OverlappedTests.PropertyTest3

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#73422]
Linux specific:

```
/root/helix/work/workitem/e /root/helix/work/workitem/e
Running assembly:System.Threading.Overlapped.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
[SKIP] OverlappedTests.PropertyTest2
[SKIP] ThreadPoolBoundHandleTests.PreAllocatedOverlapped_NonBlittableTypeAsPinData_Throws
[SKIP] ThreadPoolBoundHandleTests.PreAllocatedOverlapped_ObjectArrayWithNonBlittableTypeAsPinData_Throws
[FAIL] OverlappedTests.PropertyTest3
System.OverflowException : Arithmetic operation resulted in an overflow.
   at Internal.Runtime.CompilerHelpers.ThrowHelpers.ThrowOverflowException() + 0x28
   at OverlappedTests.PropertyTest3() + 0x258
   at System.Threading.Overlapped!<BaseAddress>+0x7a6078
   at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0xd8
Finished System.Threading.Overlapped.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51

Tests run: 21, Errors: 0, Failures: 1, Skipped: 3. Time: 0.0348331s
/root/helix/work/workitem/e
```

**Comment by davidfowl** [comment]
These aren't supposed to run on linux right?

**Comment by MichalStrehovsky** [comment]
> These aren't supposed to run on linux right?

Most of the tests pass on Linux. I didn't debug it, but it likely fails on the line where the test wants to ToInt32 the handle and it doesn't fit. That wouldn't be a fundamental problem, but also I have several thousands of other tests to get running for 7.0.

**Comment by jkotas** [comment]
> These aren't supposed to run on linux right?

Overlapped is just a piece of memory that you can allocate/free. Nobody bothered to replace it with PNSE on non-Windows, it works just fine.

`ThreadPool.UnsafeQueueNativeOverlapped` is the piece that does not work on non-Windows. It is properly annotated as Windows-specific and throws PNSE on non-Windows.
