### ISSUE TITLE
Annotate System.Security.Cryptography.Xml for trimming

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#73432]
Hitting following test failure in Microsoft.Extensions.Configuration tests.

The underlying problem seems to be that GetDecryptionKey has a string with the crypto algorithm name and calls into an API annotated as RequiresUnreferencedCode.

I don't want to block the test on aggressive trimming (it will probably be the ultimate fix for that) because the test is currently not calling into anything annotated as RequiresUnreferencedCode. So it's a conditional ActiveIssue conditioned on this.

If this API is annotated, the test can be converted to ConditionalFact conditioned on trimming.

```
[FAIL] Microsoft.Extensions.Configuration.Xml.Test.XmlConfigurationTest.LoadKeyValuePairsFromValidEncryptedXml
System.Security.Cryptography.CryptographicException : Symmetric algorithm is not specified.
   at System.Security.Cryptography.Xml.EncryptedXml.GetDecryptionKey(EncryptedData, String) + 0x44e
   at System.Security.Cryptography.Xml.EncryptedXml.DecryptDocument() + 0xf1
   at Microsoft.Extensions.Configuration.Xml.XmlDocumentDecryptor.DecryptDocumentAndCreateXmlReader(XmlDocument) + 0x4f
   at Microsoft.Extensions.Configuration.Xml.XmlStreamConfigurationProvider.Read(Stream, XmlDocumentDecryptor) + 0xa0
   at Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider.Load(Stream) + 0x14
   at Microsoft.Extensions.Configuration.Xml.Test.XmlConfigurationTest.LoadKeyValuePairsFromValidEncryptedXml() + 0x1ee
   at Microsoft.Extensions.Configuration.Xml.Tests!<BaseAddress>+0x8b10dc
   at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0xf1
Finished Microsoft.Extensions.Configuration.Xml.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
```

**Comment by jkotas** [comment]
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Security.Cryptography.Xml/src/ILLink/ILLink.Suppressions.xml lists all places that have trimming issues in this library.

**Comment by bartonjs** [comment]
I don't think there's anything in System.Security.Cryptography.Xml that /is/ trimmer friendly.

**Comment by jeffhandley** [comment]
@MichalStrehovsky Is there anything related to 7.0 where addressing this would notably help, or can this be scheduled for 8.0?

**Comment by MichalStrehovsky** [comment]
8.0 is fine. We already shipped this experience in 6.0.

(The experience is that instead of the customer getting a warning from Roslyn analyzer at the time of writing their code, highlighting the problematic line in their code, they'll get an unactionable "System.Security.Cryptography.Xml is not compatible with trimming" warning message at the time of publish with either PublishTrimmed or PublishAot).

**Comment by jeffhandley** [comment]
@eerhardt brought this to my attention as still being in the 8.0.0 milestone, but we were chatting about other possible options since this is a large and unknown effort. @eerhardt please let me know if we can punt this out to 9.0.0. Thanks!

**Comment by eerhardt** [comment]
I've opened https://github.com/dotnet/aspnetcore/issues/47410 to try to remove the need in ASP.NET for annotating this library in .NET 8. If that ASP.NET issue can be resolved in .NET 8, we shouldn't need to bring in `System.Security.Cryptography.Xml` in a NativeAOT app.

However, almost all of the auth solutions in ASP.NET require DataProtection, which uses `System.Security.Cryptography.Xml`. It just so happens that we are only targeting JWT bearer tokens in .NET 8, and JWT bearer tokens don't need DataProtection. So while we may be able to delay this work until after .NET 8, we will probably for sure need it in .NET 9 (assuming we want to enable more scenarios in ASP.NET for NativeAOT).

**Comment by eerhardt** [comment]
FYI @jeffhandley - I ended up doing this work in https://github.com/dotnet/runtime/pull/84426 and https://github.com/dotnet/runtime/pull/84468.
