### ISSUE TITLE
`System.Threading.Tasks.Dataflow.Tests` failing with NRE in `S.T.Tasks.ConcurrentExclusiveSchedulerPair.ProcessConcurrentTasks`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#73433]
Failures per Runfo - [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime+name%3A%22system.threading.tasks.dataflow.tests+work+item%22) - status as of 8/24 (unrelated failures omitted):

Day | Run | Details
-- | -- | --
8/13 | PR [1942101](https://runfo.azurewebsites.net/view/build/?number=1942101) | Alpine.314.Arm32.Open
8/13 | PR [1941527](https://runfo.azurewebsites.net/view/build/?number=1941527) | Alpine.314.Arm32.Open
8/11 | PR [1936915](https://runfo.azurewebsites.net/view/build/?number=1936915) | Alpine.314.Arm32.Open
8/10 | PR [1935321](https://runfo.azurewebsites.net/view/build/?number=1935321) | Alpine.314.Arm32.Open
8/6 | PR [1927814](https://runfo.azurewebsites.net/view/build/?number=1927814) | Alpine.314.Arm32.Open
8/4 | **Rolling run** AM [1922656](https://runfo.azurewebsites.net/view/build/?number=1922656) - extra-platforms | [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-7c8a5fbf491f4569a6/System.Threading.Tasks.Dataflow.Tests/1/console.7ef486be.log?%3Fhelixlogtype%3Dresult) - Debian.10.Arm32.Open
8/4 | PR [1924659](https://runfo.azurewebsites.net/view/build/?number=1924659) | [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-73423-merge-c514cedf967f49608b/System.Threading.Tasks.Dataflow.Tests/1/console.a047e8a7.log?%3Fhelixlogtype%3Dresult) - Alpine.314.Arm32.Open
8/2 | PR [1919458](https://runfo.azurewebsites.net/view/build/?number=1919458) | Alpine.314.Arm32.Open
8/1 | PR [1916028](https://runfo.azurewebsites.net/view/build/?number=1916028) | Alpine.314.Arm32.Open
7/29 | **Rolling run** [1912276](https://runfo.azurewebsites.net/view/build/?number=1912276) | Alpine.314.Arm32.Open
7/28 | PR [1909906](https://runfo.azurewebsites.net/view/build/?number=1909906) | Alpine.314.Arm32.Open

Potentially related: #73247 also begins failing on arm32 on 7/28. This issue first failed at 12:18pm, and #73247 starts ~5 hours later at 5:25pm. Both tests continue to fail ~once a day from this point onwards.

Hit on an unrelated PR - https://github.com/dotnet/runtime/pull/73423 .
[Build(Libraries Test Run checked coreclr Linux_musl arm Release)](https://dev.azure.com/dnceng/public/_build/results?buildId=1924659&view=logs&jobId=e03af94b-11f0-51a8-61f8-a4bc955f9c96&j=62876419-b96e-5483-94d3-b47175c1afe7&t=69034341-3a68-59aa-c247-b3e7d2608abb), and [log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-73423-merge-c514cedf967f49608b/System.Threading.Tasks.Dataflow.Tests/1/console.a047e8a7.log?helixlogtype=result):

```
===========================================================================================================
/root/helix/work/workitem/e /root/helix/work/workitem/e
  Discovering: System.Threading.Tasks.Dataflow.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Threading.Tasks.Dataflow.Tests (found 328 of 336 test cases)
  Starting:    System.Threading.Tasks.Dataflow.Tests (parallel test collections = on, max threads = 4)
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ProcessConcurrentTasks() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/ConcurrentExclusiveSchedulerPair.cs:line 461
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 938
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.WorkerThread.cs:line 77
   at System.Threading.Thread.StartCallback() in /_/src/coreclr/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs:line 105
./RunTests.sh: line 168:    21 Aborted                 (core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.Threading.Tasks.Dataflow.Tests.runtimeconfig.json --depsfile System.Threading.Tasks.Dataflow.Tests.deps.json xunit.console.dll System.Threading.Tasks.Dataflow.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
/root/helix/work/workitem/e
----- end Fri Aug 5 03:50:48 UTC 2022 ----- exit code 134 ----------------------------------------------------------
exit code 134 means SIGABRT Abort. Managed or native assert, or runtime check such as heap corruption, caused call to abort(). Core dumped.
```

I could not find an existing issue for this.

|Build|Kind|Start Time|
|---|---|---|
[1912276](https://dev.azure.com/dnceng/public/_build/results?buildId=1912276)|Rolling|2022-29-07|

**Comment by joperezr** [comment]
I'm taking a look at this by trying to analyze the dump so I can get which test is causing this.

**Comment by karelz** [comment]
@joperezr FYI: I updated top post -- it didn't seem to happen 8/13-8/24 at all.

**Comment by jkotas** [comment]
Likely fixed as part of https://github.com/dotnet/runtime/issues/73405#issuecomment-1206151902
