### ISSUE TITLE
The default deserializer is not working properly

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#73470]
### Description

The default deserializer will deserialize dson incorrectly.Json is in the example repository
https://github.com/Mr0N/ExampleJsonException/blob/master/ExampleJsonException/Program.cs
https://github.com/Mr0N/ExampleJsonException/blob/master/ExampleJsonException/load.txt
### Reproduction Steps

-

### Expected behavior

-

### Actual behavior

-

### Regression?

-

### Known Workarounds

--

### Configuration

-

### Other information

-

**Comment by eiriktsarpalis** [comment]
The JSON doesn't match the property names. In order for your example to work you need to specify a [property naming policy](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.propertynamingpolicy?view=net-6.0). The following should work in your example:

```C#
string json = """[{"tag":"cityscape","probability":1},{"tag":"buildings","probability":1}]""";

var options = new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase };
var result = JsonSerializer.Deserialize<IEnumerable<TagsPhoto>>(json, options);
Console.WriteLine(result.First().Tag ?? "null");

public class TagsPhoto
{
    public string Tag { set; get; }
    public float Probability { set; get; }
}
```

**Comment by Mr0N** [comment]
> The JSON doesn't match the property names. In order for your example to work you need to specify a [property naming policy](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.propertynamingpolicy?view=net-6.0). The following should work in your example:
> 
> ```cs
> string json = """[{"tag":"cityscape","probability":1},{"tag":"buildings","probability":1}]""";
> 
> var options = new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase };
> var result = JsonSerializer.Deserialize<IEnumerable<TagsPhoto>>(json, options);
> Console.WriteLine(result.First().Tag ?? "null");
> 
> public class TagsPhoto
> {
>     public string Tag { set; get; }
>     public float Probability { set; get; }
> }
> ```



> The JSON doesn't match the property names. In order for your example to work you need to specify a [property naming policy](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.propertynamingpolicy?view=net-6.0). The following should work in your example:
> 
> ```cs
> string json = """[{"tag":"cityscape","probability":1},{"tag":"buildings","probability":1}]""";
> 
> var options = new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase };
> var result = JsonSerializer.Deserialize<IEnumerable<TagsPhoto>>(json, options);
> Console.WriteLine(result.First().Tag ?? "null");
> 
> public class TagsPhoto
> {
>     public string Tag { set; get; }
>     public float Probability { set; get; }
> }
> ```

![image](https://user-images.githubusercontent.com/61237140/183123492-62087c21-c67f-45e5-9d68-f34cafbbef56.png)

**Comment by Mr0N** [comment]
![image](https://user-images.githubusercontent.com/61237140/183124259-c3dbb946-d82a-4bca-b836-de8c76e1949c.png)

**Comment by eiriktsarpalis** [comment]
Your class defines two properties called tag which collide when collapsed using the camel case naming policy.

**Comment by Mr0N** [comment]
> Your class defines two properties called tag which collide when collapsed using the camel case naming policy.

Why does Newtonsoft.Json work fine, but the system library does not work in this case?

**Comment by eiriktsarpalis** [comment]
"work fine" is debatable, they are two different libraries that have different semantics. Json.NET allows case-insensitive binding whereas Json.NET is case sensitive unless a naming policy is specified. Matching the behavior of Json.NET is not a design goal for System.Text.Json.

**Comment by Mr0N** [comment]
> "work fine" is debatable, they are two different libraries that have different semantics. Json.NET allows case-insensitive binding whereas Json.NET is case sensitive unless a naming policy is specified. Matching the behavior of Json.NET is not a design goal for System.Text.Json.

Oh well, I thought System.Text.json is a copy of Newtonsoft.Json, if not, I will use Newtonsoft.Json. Okay, the question is closed!
