### ISSUE TITLE
Document to explain what each FEATURE_XXXX is

### ISSUE THREAD

**Issue by mattwarren** [dotnet/runtime#7347]
In [clr.defines.targets](https://github.com/dotnet/coreclr/blob/master/clr.defines.targets) there are over 100 `FEATURE_XXXX` switches that are in operation within the CoreCLR source (which is [less than there once was](https://github.com/dotnet/coreclr/issues/8857)).

Is there a document available that explains what they all are, when they're useful (or not)? If there isn't, is it worth the effort to create one?

(There's some info in [Host Configuration Knobs](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/clr-configuration-knobs.md) if the feature has some config settings, but this doesn't seem to cover all features)

Also a bonus question, is there any more info available on [StackSampler (`FEATURE_STACK_SAMPLING`)](https://github.com/dotnet/coreclr/blob/master/src/vm/stacksampler.cpp#L5-L28), is seems like a really cool feature, similar to HotSpot in the JVM. Was it something that was tried out and didn't work, is its still work-in-progress or something else?

**Comment by danmosemsft** [comment]
Up for grabs.
