### ISSUE TITLE
 Linux and Mac have CryptographicException with generic HResult for bad password opening a PFX

### ISSUE THREAD

**Issue by heng-liu** [dotnet/runtime#735]
The Invalid ASN and bad password have both generic HResult in netcore5.0, so we're not able to differentiate them as we did in netcore3.0.
Can you pls help us change HResult for bad password? Thanks!

**Comment by bartonjs** [comment]
> Is this a change from 3.0 to 3.1 then?

No, 3.x -> 5 (the custom PFX loader change)

**Comment by danmosemsft** [comment]
Thanks, misread.

**Comment by vcsjones** [comment]
Windows appears to use `ERROR_INVALID_PASSWORD` converted to an HRESULT (0x80070056). Is this basically just adding the HRESULT to this line? 

https://github.com/dotnet/runtime/blob/73eec1b1223eb5d974a3ceff2419f2dc425ae4d1/src/libraries/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/UnixPkcs12Reader.cs#L228

**Comment by bartonjs** [comment]
@vcsjones Yep.  You wanna take it? :)

**Comment by vcsjones** [comment]
@bartonjs sure.

**Comment by vcsjones** [comment]
Looking at this a bit more, the Win32 PAL is inconsistent between the PAL using an HRESULT and a Win32 status code when setting the HResult on the `CryptographicException`. 

In some cases, `Marshal.GetHRForLastWin32Error().ToCryptographicException()` is used:

https://github.com/dotnet/runtime/blob/de12f85a9452c7b10e1e5c0f69c2d959f698ba10/src/libraries/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Windows/CertificatePal.Import.cs#L153

So `HResult` will be 0x80070056.

In another case, `Marshal.GetLastWin32Error().ToCryptographicException()` is used:

https://github.com/dotnet/runtime/blob/de12f85a9452c7b10e1e5c0f69c2d959f698ba10/src/libraries/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Windows/StorePal.Import.cs#L77

So `HResult` will be 0x56 and won't really be an HR.

I suppose a question for @bartonjs then is, which is preferable for the Unix PAL to do? The Windows PAL seems to be inconsistent whether HResult contains win32 statuses or an HR. Do we want to do anything about the Windows PAL?

**Comment by bartonjs** [comment]
Looks like .NET Framework threw with HResult=0x80070056 in both the collection and the single-cert case.  (Largely because in .NET Framework we or-in 80070000 if the high bit isn't already set: https://referencesource.microsoft.com/#mscorlib/system/security/cryptography/crypto.cs,108; perhaps that's missing in the ToCryptographicException extension method)
