### ISSUE TITLE
[MONO][TEST] Android arm64 Runtime tests run.sh doesn't use the right script name

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#73510]
### Description

`

### Reproduction Steps

```
> ./build.sh -os Android -arch arm64 -subset mono+libs+packs -c Debug 
> cd src/tests
> ./build.sh -mono -os Android arm64 -test:baseservices/invalid_operations/InvalidOperations.csproj /p:LibrariesConfiguration=Debug
 > ./run.sh Android arm64 Debug 
 ```

### Expected behavior

Runs the test.

### Actual behavior

Produces this error message:

```    /bin/bash: /Users/naricc/workspace/runtime-marshal-component/artifacts/tests/coreclr/Android.arm64.Debug/baseservices/invalid_operations/InvalidOperations/InvalidOperations.sh: No such file or directory ``` 

The file does not seem to exist. There is one named `InvalidOperations.cmd_Android_arm64_Debug.sh`, but that doesn't seem to have the right contents.

### Known Workarounds

You can build for x64, get the correct script generated, copy it to the right folder and edit it to change the architecture.

### Configuration

Build machine was MacOSX x64

### Other information

Must have android preqs described here to build for android: https://github.com/dotnet/runtime/blob/main/docs/workflow/testing/libraries/testing-android.md

**Comment by mdh1418** [comment]
Building on OSX arm64 for Android arm64, it doesn't seem to generate the `sh` file either. I somehow managed to generate the `<test>.cmd_Android_arm64_Debug.sh` but that was giving me some errors such as 
```
        /Users/mihw/runtime_droid/artifacts/tests/coreclr/Android.arm64.Debug/JIT/Performance/CodeQuality/Inlining/NoThrowInline/NoThrowInline.cmd: line 1: @ECHO: command not found
        /Users/mihw/runtime_droid/artifacts/tests/coreclr/Android.arm64.Debug/JIT/Performance/CodeQuality/Inlining/NoThrowInline/NoThrowInline.cmd: line 2: setlocal: command not found
        /Users/mihw/runtime_droid/artifacts/tests/coreclr/Android.arm64.Debug/JIT/Performance/CodeQuality/Inlining/NoThrowInline/NoThrowInline.cmd: line 4: pushd: %~dp0: No such file or directory
        /Users/mihw/runtime_droid/artifacts/tests/coreclr/Android.arm64.Debug/JIT/Performance/CodeQuality/Inlining/NoThrowInline/NoThrowInline.cmd: line 8: REM: command not found
        /Users/mihw/runtime_droid/artifacts/tests/coreclr/Android.arm64.Debug/JIT/Performance/CodeQuality/Inlining/NoThrowInline/NoThrowInline.cmd: line 9: :NextArg: command not found
        /Users/mihw/runtime_droid/artifacts/tests/coreclr/Android.arm64.Debug/JIT/Performance/CodeQuality/Inlining/NoThrowInline/NoThrowInline.cmd: line 11: IF: command not found
        /Users/mihw/runtime_droid/artifacts/tests/coreclr/Android.arm64.Debug/JIT/Performance/CodeQuality/Inlining/NoThrowInline/NoThrowInline.cmd: line 12: IF: command not found
        /Users/mihw/runtime_droid/artifacts/tests/coreclr/Android.arm64.Debug/JIT/Performance/CodeQuality/Inlining/NoThrowInline/NoThrowInline.cmd: line 13: IF: command not found
        /Users/mihw/runtime_droid/artifacts/tests/coreclr/Android.arm64.Debug/JIT/Performance/CodeQuality/Inlining/NoThrowInline/NoThrowInline.cmd: line 14: IF: command not found
        /Users/mihw/runtime_droid/artifacts/tests/coreclr/Android.arm64.Debug/JIT/Performance/CodeQuality/Inlining/NoThrowInline/NoThrowInline.cmd: line 17: IF: command not found
        /Users/mihw/runtime_droid/artifacts/tests/coreclr/Android.arm64.Debug/JIT/Performance/CodeQuality/Inlining/NoThrowInline/NoThrowInline.cmd: line 18: IF: command not found
        /Users/mihw/runtime_droid/artifacts/tests/coreclr/Android.arm64.Debug/JIT/Performance/CodeQuality/Inlining/NoThrowInline/NoThrowInline.cmd: line 19: syntax error near unexpected token `('
        /Users/mihw/runtime_droid/artifacts/tests/coreclr/Android.arm64.Debug/JIT/Performance/CodeQuality/Inlining/NoThrowInline/NoThrowInline.cmd: line 19: `IF %cond% EQU 1 ('
```
But I have not been able to figure out how to regenerate the `.cmd_Android_arm64_Debug.sh` file anymore.

**Comment by directhex** [comment]
That’s a .cmd batch file. Something somewhere is probably doing an “if Linux then Bash, else CMD” instead of “if Windows then CMD, else Bash”

Sent from Mail for Windows

**Comment by mdh1418** [comment]
> That’s a .cmd batch file. Something somewhere is probably doing an “if Linux then Bash, else CMD” instead of “if Windows then CMD, else Bash”

Right, I think that might be here https://github.com/dotnet/runtime/blob/d2c991effcdf543cc60632e5588984aa22dd6772/src/tests/Directory.Build.props#L176-L178 that sets it to `.cmd` instead of `.sh`.
https://github.com/dotnet/runtime/pull/44560#discussion_r546304915
Is this because the android devices on CI are only on Windows? And so we need to add support to run Android runtime tests on OSX?

**Comment by fanyang-mono** [comment]
It is supposed to generate a `.cmd` file for runtime tests running on Android arm64, because on CI, Android arm64 devices are connected to windows machines.

**Comment by fanyang-mono** [comment]
I am closing the issue now as the current behavior is correct w.r.t the original design.
