### ISSUE TITLE
Support for [LibraryImport] on local functions

### ISSUE THREAD

**Issue by DaZombieKiller** [dotnet/runtime#73532]
This is something that came to mind while re-reading https://github.com/dotnet/runtime/issues/63590. I would likely wrap such methods to have control over the function pointer parameter, meaning they would see no direct use outside of the wrapper. This makes them suitable to be defined as local functions.

Today, a `DllImport` defined as a local function has no _in-place_ equivalent with `LibraryImport`. To provide a contrived example:
```cs
static unsafe void* GetSomeModuleHandle()
{
    fixed (char* pName = "SomeModule.dll")
        return GetModuleHandleW((ushort*)pName);

    [DllImport("kernel32", ExactSpelling = true)]
    static extern void* GetModuleHandleW(ushort* lpModuleName);
}
```
I'm not sure if it's possible to expose a way to do this without language changes, as a `partial` local function is not a valid concept in C#.

**Comment by teo-tsirpanis** [comment]
Closing as this is blocked by the C# language and there is nothing to be done in the runtime.

I can't find a corresponding language proposal for local partial functions. Feel free to open one in `dotnet/csharplang`, and to include this use case as a motivating factor.
