### ISSUE TITLE
Mono crashes test runs

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#73539]
8/7 - occurrences on Android, tvOS, MacCatalyst, iOS, iOSSimulator, tvOSSimulator - only those **without Test Results** associated
Test suite | # | Details
-- | -- | --
**JIT.Directed Work Item** | 50x | (all without Test Results) in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime-extra-platforms+name%3A%22jit.directed+work+item%22+targetBranch%3Amain) - first on 8/2<br/><br/> `JIT/Directed/aliasing_retbuf/aliasing_retbuf/aliasing_retbuf.sh` test failed in logs - sometimes recognized as specific failure - see [Runfo](https://runfo.azurewebsites.net/search/tests/?q=started%3A~30%20definition%3Aruntime-extra-platforms%20name%3A%22jit%2Fdirected%2Faliasing_retbuf%2Faliasing_retbuf%2Faliasing_retbuf.sh%22)
**System.Text.Json.Tests Work Item** | 49x | (without Test Results) in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime-extra-platforms+name%3A%22system.text.json.tests+work+item%22+targetbranch%3Amain) - first one on 7/24
**System.Runtime.Tests Work Item** | 15x | (without Test Results) in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime-extra-platforms+name%3A%22system.runtime.tests+work+item%22+targetBranch%3Amain) - first on 7/27
**System.Security.Cryptography.Tests Work Item** | 44x | (all without Test Results) in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime-extra-platforms+name%3A%22system.security.cryptography.tests+work+item%22+targetBranch%3Amain) - first on 7/24
**System.ComponentModel.Tests Work Item** | 10x | (all without Test Results) in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime-extra-platforms+name%3A%22system.componentmodel.tests+work+item%22+targetBranch%3Amain) - first on 8/1
**System.IO.Hashing.Tests Work Item** | 11x | (all without Test Results) (excluded 1 with different error) in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime-extra-platforms+name%3A%22system.io.hashing.tests+work+item%22+targetBranch%3Amain) - first on 8/1
**System.IO.FileSystem.Primitives.Tests Work Item** | 10x | (all without Test Results) in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime-extra-platforms+name%3A%22system.io.filesystem.primitives.tests+work+item%22+targetBranch%3Amain) - first on 8/1
**System.Xml.RW.WrappedReader.Tests Work Item** | 4x | (all without Test Results) (excluded 1 with different error) in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime-extra-platforms+name%3A%22system.xml.rw.wrappedreader.tests+work+item%22+targetBranch%3Amain) - first on 8/3
**System.Threading.Tasks.Dataflow.Tests Work Item** | 22x | (without Test Results and Core Dump) in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime-extra-platforms+name%3A%22system.threading.tasks.dataflow.tests+work+item%22+targetBranch%3Amain) - first on 7/26
**System.Net.WebSockets.Tests Work Item** | 9x | (without Test Results) in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime-extra-platforms+name%3A%22system.net.websockets.tests+work+item%22+targetBranch%3Amain) - first on 8/1
**System.Linq.Parallel.Tests Work Item** | ~20x | (some logs have different failure) in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime-extra-platforms+name%3A%22system.linq.parallel.tests+work+item%22+targetBranch%3Amain) - first on 7/26
**Microsoft.Extensions.Logging.Generators.Roslyn4.0.Tests Work Item** | 8x | (some logs have different failure) in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime-extra-platforms+name%3A%22microsoft.extensions.logging.generators.roslyn4.0.tests+work+item%22+targetBranch%3Amain) - first on 8/1
**System.Runtime.Numerics.Tests Work Item** | 12x | (without Test Runs and Core Dump) in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime-extra-platforms+name%3A%22system.runtime.numerics.tests+work+item%22+targetBranch%3Amain) - first on 7/22
**System.Xml.Linq.Events.Tests Work Item** | 3x | (some logs have different failure) in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime-extra-platforms+name%3A%22system.xml.linq.events.tests+work+item%22+targetBranch%3Amain) - first on 8/3
**System.Numerics.Tensors.Tests Work Item** | 9x | (some logs have different failure) in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime-extra-platforms+name%3A%22system.numerics.tensors.tests+work+item%22+targetBranch%3Amain) - first on 8/1
**System.Net.Http.Json.Unit.Tests Work Item** | 11x | (some logs have different failure) in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime-extra-platforms+name%3A%22system.net.http.json.unit.tests+work+item%22+targetBranch%3Amain) - first on 8/1

Example:
- Rolling run on 8/7 AM - [1928273](https://runfo.azurewebsites.net/view/build/?number=1928273)
    - JIT.Directed - [Console log 1](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-b45450a16ee944f4a4/JIT.Directed.Attempt.3/1/console.91842505.log?%3Fhelixlogtype%3Dresult) and [Console log 2](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-b28f1938f3914004bd/JIT.Directed.Attempt.3/1/console.999df5f3.log?%3Fhelixlogtype%3Dresult)
    - System.Security.Cryptography.Tests - [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-3317bcdfa72a4fc48c/System.Security.Cryptography.Tests/1/console.2e1eb430.log?%3Fhelixlogtype%3Dresult)
- Rolling run on 8/16 PM - [1927956](https://runfo.azurewebsites.net/view/build/?number=1927956)
    - JIT.Directed - [Console log 1](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-e27f65ef4bb64eeb88/JIT.Directed.Attempt.3/1/console.16834d91.log?%3Fhelixlogtype%3Dresult) and [Console log 2](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-e82f89e8ff1f49058f/JIT.Directed.Attempt.3/1/console.f1644921.log?%3Fhelixlogtype%3Dresult)
    - System.Console.Manual.Tests - [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-8c0cc100331f483699/System.Console.Manual.Tests/1/console.75d6ad8c.log?%3Fhelixlogtype%3Dresult)
    - System.Runtime.Tests - [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-8c0cc100331f483699/System.Runtime.Tests/1/console.fb3bd14d.log?%3Fhelixlogtype%3Dresult)

**Comment by karelz** [comment]
@lewing can you please help route it? This is massive test failure, causing significant noise in Rolling runs and PRs.

**Comment by karelz** [comment]
From offline discussion with @steveisok - this is being already looked at buy somebody.

**Comment by karelz** [comment]
The **JIT.Directed** failures are consistent in EVERY Rolling run starting with 8/2 PM [1918913](https://runfo.azurewebsites.net/view/build/?number=1918913) -- the error is somewhat different, is it perhaps different problem?

**Comment by akoeplinger** [comment]
@simonrozsival will look at the `JIT.Directed` failure as I agree it looks unrelated to the TCP tunnel problem.

**Comment by simonrozsival** [comment]
The JIT.Directed logs contain stack traces showing null pointer dereferencing when `unhandled_exception_handler` is called. This reminds me of https://github.com/dotnet/runtime/issues/69601. I'll continue digging tomorrow.
