### ISSUE TITLE
Cache most popular string objects in String.InternalSubString

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#73540]
I've analyzed a couple of memory snapshots using dotMemory and it feels to me that `String.InternalSubString` is the main source of duplicated strings on the heap, e.g. total heap statistics for `dotnet publish -c Release ...` (msbuild+roslyn+nuget+illink+crossgen) over a medium-size project:

![image](https://user-images.githubusercontent.com/523221/183310835-b72809de-d86d-45db-83f2-3cd1584160c8.png)

500K string objects, mostly from Substring

And here is a memory snapshot taken in a random place during that `dotnet publish`:

![image](https://user-images.githubusercontent.com/523221/183310097-81813524-7ec4-41e5-92c5-19462c5117af.png)

Also, checked VS2022's snapshot, AvaloniaILSpy if you have good example to look at - please share

My impression that it's worth special casing `"0"`, `"1"`, `"true"`, `"false"` in `String.InternalSubString` and those paths should not hurt perf much since string compare operations are unrolled, e.g.:

![image](https://user-images.githubusercontent.com/523221/183310737-ea035771-13c9-4b5f-90a8-e74fc9e4fd13.png)

here it polls span's length and if it's 1 or 4 it runs a single compare with a constant to check if it's a known string.

Related: "Improve Density of GC heap by String Interning (de-duping) on Gen2 GC" https://github.com/dotnet/runtime/issues/9022

**Comment by EgorBo** [comment]
![image](https://user-images.githubusercontent.com/523221/183310795-d39e9819-da37-4f86-8b18-2f5a84a5b2ee.png)

^ for `dotnet publish` - 500K string objects, mostly from Substring

**Comment by EgorBo** [comment]
Prototype: https://github.com/EgorBo/runtime-1/commit/1c73b3efbaee85147278e307ec04b19ccc618620

**Comment by jkotas** [comment]
String substring does not feel like the right place to do this optimization. Have you looked ať the top callers that create these strings? Would it make more sense to fix the callers instead? We do caller specific de-duplication in number of places, for example in integer formatting.

**Comment by EgorBo** [comment]
In case of `dotnet publish` it's

![image](https://user-images.githubusercontent.com/523221/183314350-8761be28-09c6-489e-b86c-c49e219de597.png)

I assume it's here: https://github.com/dotnet/msbuild/blob/3ade6423189769545ddff2ffeeed37010ec57f4d/src/Build/Evaluation/Conditionals/Scanner.cs#L561-L641

**Comment by EgorBo** [comment]
Still, I think at least these two lines of code worth adding: https://github.com/EgorBo/runtime-1/blob/c487556f0a1131833ce22dfe40cb89fca88b5dcf/src/libraries/System.Private.CoreLib/src/System/String.Manipulation.cs#L1850-L1854 - cheap handling for '0'..'9', right?

**Comment by jkotas** [comment]
I am not sure. Substrings of this shape are likely going to produced by allocation heavy parsers, they are unlikely to survive gen gc, and so getting rid of them is unlikely to make a difference in the app high water mark that tends to be dominated by gen2.

This optimization is trying to improve certain inefficient allocation heavy parsers a tiny bit, but makes all substring calls to pay for it.

**Comment by danmoseley** [comment]
We used to intern some hard coded strings like true and false in MSBuild including in that codepath ("OpportunisticIntern"). I can't look at the code at the moment but I believe it was removed a little while ago. @Forgind @rainersigwald

**Comment by danmoseley** [comment]
https://github.com/dotnet/msbuild/pull/5663/files#diff-8b918fc3cf86a6bcec4ce6b6c0adce1f61dd3bb09b19c61320cf6fb51aa0ec76L331

**Comment by EgorBo** [comment]
Thanks for the feedback, I'll check what if it's worth special-casing on msbuild's side

> We used to intern some hard coded strings like true and false in MSBuild including in that codepath ("OpportunisticIntern"). I can't look at the code at the moment but I believe it was removed a little while ago. @Forgind @rainersigwald

From my understanding, string interning doesn't help with String.Concat/String.Substring which are the main sources of string allocations

**Comment by rainersigwald** [comment]
> In case of `dotnet publish` and `"true"` `"false"` it's
> 
> ![image](https://user-images.githubusercontent.com/523221/183314350-8761be28-09c6-489e-b86c-c49e219de597.png)

For this callsite we definitely have some work to do spanifying the parsing, but the strings themselves should be extremely short-lived because of the deduplication engine @jkotas mentioned.
