### ISSUE TITLE
Cleanup __Error vs Win32Marshal duplication

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#7355]
In CoreCLR  __Error is duplicate of the new refactored Win32Marshal.GetExceptionForWin32Error that was copied from corefx. The mapping for DriveNotFoundException was removed from Win32Marshal.GetExceptionForWin32Error as part of this refactoring. This duplication and inconsistency should be fixed.

https://github.com/dotnet/coreclr/pull/9269#pullrequestreview-19763413

**Comment by jkotas** [comment]
`__Error` does not exist anymore.
