### ISSUE TITLE
System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time,

### ISSUE THREAD

**Issue by Jawadahmed200** [dotnet/runtime#73561]
I have created ASP.NET Web App Using MVC and Asp.Net Web Api. Both projects build using .Net Core 6. When I run both projects on local, They are working fine. But When I deployed both projects on my server (IIS), and Accessing the api from web, it is throwing below error.

```
System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (193.117.201.74).
```
After that I host My Api on different hosting server and Web on different hosting server. when access it is still throwing the same error.

```
System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (irfanjanan-001-site1.btempurl.com:80)
```

*Note: The Same Api is working from postman and flutter mobile app and browser(for Get Method) using both IP(193.117.201.74) and Domain name (irfanjanan-001-site1.btempurl.com:80)

For test : http://irfanjanan-001-site1.btempurl.com/weatherforecast

```
public static async Task<object> CustomHttp1(string BaseUrl, string Url, string content, HttpContext httpContext, IWebHostEnvironment env, IHttpClientFactory httpClientFactory)
        {
            using (var client = new HttpClient())
            {

                client.BaseAddress = new Uri(BaseUrl);

                client.DefaultRequestHeaders
                      .Accept
                      .Add(new MediaTypeWithQualityHeaderValue("application/json"));

                HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, Url);
                if (!String.IsNullOrEmpty(httpContext.Session.GetString("authorization")))
                    request.Headers.Add("authorization", httpContext.Session.GetString("authorization"));
                request.Content = new StringContent(content, Encoding.UTF8, "application/json");

                try
                {

                    var Res = await client.SendAsync(request);
                    if (Res.IsSuccessStatusCode)
                    {
                        var response = Res.Content.ReadAsStringAsync().Result;
                        var obj = JsonConvert.DeserializeObject<Response>(response);
                        httpContext.Session.SetString("authorization", obj.Token == null ? "" : obj.Token);
                        return response;

                    }
                    else
                    {
                        return null;
                    }
                }
                catch (Exception ex)
                {
                    var path = env.WebRootPath + "\\MyLogs\\Error.txt";
                    if (!System.IO.File.Exists(path))
                    {
                        using (StreamWriter sw = System.IO.File.CreateText(path))
                        {
                            sw.WriteLine(ex.InnerException);
                            sw.WriteLine(ex.Message);
                        }
                    }
                    return null;
                }

            }
}
```

**Above is my method for calling my Api.

Note :**

    I have created new projects for both Api & Web And Deployed. But still same issue.
    Same Hosted API Working fine when calling from local Asp.net Web project.

Please Suggest Solution.

**Comment by Jawadahmed200** [comment]
> Does the "client" code work when run locally?
> 
> I tried to reproduce this with a console app and it works without problems:
> 
> ```cs
> using System.Net.Http.Headers;
> using System.Text;
> 
> HttpClient client = new HttpClient();
> client.DefaultRequestHeaders
>                    .Accept
>                    .Add(new MediaTypeWithQualityHeaderValue("application/json"));
> 
> HttpRequestMessage request = new HttpRequestMessage()
> {
>     RequestUri = new Uri("http://irfanjanan-001-site1.btempurl.com/weatherforecast"),
>     Method = HttpMethod.Get,
> };
> 
> request.Content = new StringContent("{}", Encoding.UTF8, "application/json");
> 
> 
> var response = await client.SendAsync(request);
> System.Console.WriteLine(response);
> System.Console.WriteLine(await response.Content.ReadAsStringAsync());
> ```
> 
> ```
> ❯ dotnet run
> StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
> {
>   Transfer-Encoding: chunked
>   Server: Microsoft-IIS/10.0
>   X-Powered-By: ASP.NET
>   Date: Mon, 08 Aug 2022 12:11:40 GMT
>   Content-Type: application/json; charset=utf-8
> }
> [{"Date":"2022-08-09T05:11:40.6027995-07:00","TemperatureC":29,"TemperatureF":84,"Summary":"Warm"},{"Date":"2022-08-10T05:11:40.6028084-07:00","TemperatureC":27,"TemperatureF":80,"Summary":"Sweltering"},{"Date":"2022-08-11T05:11:40.6028091-07:00","TemperatureC":5,"TemperatureF":40,"Summary":"Balmy"},{"Date":"2022-08-12T05:11:40.6028097-07:00","TemperatureC":5,"TemperatureF":40,"Summary":"Warm"},{"Date":"2022-08-13T05:11:40.6028102-07:00","TemperatureC":10,"TemperatureF":49,"Summary":"Cool"}]
> ```
> 
> Can you make requests to other websites from the hosted app? it may be that the app is prevented from making outbound requests.

Yes It is working fine when try to hit Api from local.. But When deploying same code on hosting platform, it is throwing error.

**Comment by rzikm** [comment]
Then it seems to me like an environmental problem. Can you make requests to other websites from the hosted app? it may be that the app is prevented from making outbound requests by the hosting platform.

**Comment by Jawadahmed200** [comment]
https://catfact.ninja/fact

I tried this open api which is working fine in browser and postman. But when try to call from my project which is deployed on IONOS Hosting service. It is throwing same error.

**Comment by Jawadahmed200** [comment]
I think app is blocking outbound calls. how to solve this issue ?

**Comment by Jawadahmed200** [comment]
@rzikm Any solution for this ?

**Comment by MihaZupan** [comment]
@Jawadahmed200 this appears to be an issue with your hosting setup.
I see [this article](https://www.ionos.co.uk/help/hosting/net/script-examples-for-establishing-external-http-connections-windows/) in their docs suggesting that you must use their proxy when making outbound calls.
You can also check that the hosting service's firewall is not blocking outbound traffic (outbound TCP on ports 80 and 443).

If this does not solve the issue, please contact IONOS support.

**Comment by Jawadahmed200** [comment]
> @Jawadahmed200 this appears to be an issue with your hosting setup. I see [this article](https://www.ionos.co.uk/help/hosting/net/script-examples-for-establishing-external-http-connections-windows/) in their docs suggesting that you must use their proxy when making outbound calls. You can also check that the hosting service's firewall is not blocking outbound traffic (outbound TCP on ports 80 and 443).
> 
> If this does not solve the issue, please contact IONOS support.

Thank You @MihaZupan  For You Kind Help. It is Working after enabling proxy.
