### ISSUE TITLE
Microsoft.Extensions.Configuration.EnvironmentVariables 6.0.1 fails reading environment variables

### ISSUE THREAD

**Issue by mauriciomagni** [dotnet/runtime#73570]
### Description

Up to version 6.0.0 these code works:
```f#
open Microsoft.Extensions.Configuration
open Microsoft.Extensions.Configuration.EnvironmentVariables

let c = ConfigurationBuilder()
let cbuilder = c.AddEnvironmentVariables("AppVars__")
let config = cbuilder.Build()
let value = config.GetValue<string>("VarName")

printfn $"Environment Variable Value = {value}"
```
but in version 6.0.1 it starts failing

### Reproduction Steps

copy the source code in the message and upgrade named nuget to version 6.0.1

### Expected behavior

Read the environment variable value

### Actual behavior

returns null

### Regression?

yes, it works in version 6.0.0

### Known Workarounds

downgrade to version 6.0.0

### Other information

using .NET SDK version 6.0.302

**Comment by tarekgh** [comment]
@mauriciomagni This issue existed in `.NET 5.0`, and we have tried to fix it in `.NET 6.0.0` through the [PR](https://github.com/dotnet/runtime/pull/42932). Unfortunately, the fix caused other bad regressions and we had to revert the fix back in `.NET 6.0.1` through the [PR](https://github.com/dotnet/runtime/pull/62916). Therefore, you still see the issue in 6.0.1.

We already fixed this issue in a clean way in .NET 7.0 in the [commit](https://github.com/dotnet/runtime/commit/9cd49ff735341e8f0eb2f7898a7f612941bb297b).

Now you have the options, either start referencing the .NET 7.0 preview version of [Microsoft.Extensions.Configuration.EnvironmentVariables](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.EnvironmentVariables) package, or you can reference version `6.0.0` of this package in your app to get back the original fix which we reverted.
