### ISSUE TITLE
Bitwise operations on enum's used in generics not working despite the constraint being applied

### ISSUE THREAD

**Issue by jesperkp** [dotnet/runtime#73579]
When creating a class with a generic T where T: enum it is not possible to perform bitwise operations

A class like this fail on bitwise operations within the class 

```C#
    public class Options<T> where T: System.Enum
    {
        public T status;

        public Options()
        {
            // Asumption is that enum have at least 1 value - and select the first value in the list as default
            status = (T) typeof(T).GetEnumValues().GetValue(typeof(T).GetEnumValues().GetLowerBound(0))!;
        }

        public bool isActive(T check)
        {
            return status.HasFlag(check);
        }

        public void SetOption(T stat)
        {
            // This gives compiler error
            **status = status | stat;**
            
            // Equal operator of course works
            status = stat;
        }
    }
```

An example instantiation with the following enum show that bitwise operations are allowed on T status from outside the class

```C#
    [System.Flags]
    public enum Options
    {
        None     = 0b_0000_0001,
        OPTION1  = 0b_0000_0010,
        OPTION2  = 0b_0000_0100,
        OPTION3  = 0b_0000_1000,
        OPTION4  = 0b_0001_0000,
        OPTION5  = 0b_0010_0000,
        OPTION6  = 0b_0100_0000
    }
```

Instantiation and test

```C#
var myOptions = new Options<Options>();

myOptions.status = myOptions.status | Options.OPTION5;
```

This gives no compiler error.

**This is on:**
Running Ubuntu 20.04.4 LTS
dotnet --version     6.0.302  (latest from

**Comment by tannergooding** [comment]
You'll likely want to open a proposal on dotnet/csharplang requesting a language feature to support this.

Notably, `where T : Enum` constrains it to be the `System.Enum` class or a concrete `enum` type, the former doesn't have any operators. 

Using `where T : struct, Enum` would constrain it only to being a concrete `enum` type; however there are also no actual operators exposed by such types. The bitwise operators are instead supported by knowing the underlying type and emitting the relevant `int32/int64/uint32/uint64` opcode instead.

This would likely require a combination of runtime and language changes to support, but it needs language buy off before anything could be done.
