### ISSUE TITLE
Bug when renaming a DataTable column to the same name, but with different case

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#73575]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Bug-when-renaming-a-DataTable-column-to-/10109015)._

---
DataTable dt = new();
dt.Columns.Add("ABN");
dt.Columns["ABN"].ColumnName = "Abn";
dt.Columns["Abn"].ColumnName = "Abn_old";

//this line will error:
dt.Columns.Add("ABN");

**Exception thrown: 'System.Data.DuplicateNameException' in System.Data.Common.dll
An unhandled exception of type 'System.Data.DuplicateNameException' occurred in System.Data.Common.dll
A column named 'ABN' already belongs to this DataTable.**

---
#### Tracy Wang [MSFT] on 8/2/2022, 09:28 AM: 

(private comment, text removed)
#### Daniel Barnes on 8/3/2022, 00:23 AM: 

(private comment, text removed)
#### Feedback Bot on 8/3/2022, 02:59 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
Column names are often case insensitive; differing only by case is not supported.
