### ISSUE TITLE
Debugger c# net 7 not native file request broken AND Breakpoint error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#73591]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Debugger-c-net-7-not-native-file-reques/10113851)._

---
[severity:I'm unable to use this version]
Hello dear team
I just tried your debugger
and unfortunately found that he requests a file that I do not have.

We'll take a pointless code

 static void Main(string[] args)
    {
        Console. WriteLine("Hello World");
    }

Ok settings:
debugger

Enable traversal of Net framework
Enable debugging at address level and sub-item.
Debugging properties Disable native code.

Start the program with F11
Then press F11 until line (1189) comes up with the error

 if (useFileAPIs)
                    {
                        int numBytesWritten;
                        writeSuccess = (0 != Interop.Kernel32.WriteFile(hFile, p, bytes.Length, out numBytesWritten, IntPtr.Zero));

This is in the Console.Pal.Windows.cs file

Now set the breakpoint to the line with the Interop.Kernel32. Now press F11 and it asks on the PC for a file that is probably missing.
Where can I get this file? Why is it asking me for an autogenerated file? (Nevermind)

This is the file I am asked for:
/_/src/libraries/System.Console/src/Microsoft.Interop.LibraryImportGenerator/Microsoft.Interop.LibraryImportGenerator/LibraryImports.g.cs

The same file not found on git

In addition, I discovered a 2nd error.
I also noticed a breakpoint error.
Unfortunately, if you want to set a breakpoint on int numBytesWritten, you can't do that either. My files may be out of date. how can i do that
fix problem?

Please give me a link to get the file I seem to be missing and please fix the breakpoint error.

Many Thanks

Kind regards

Sascha Bothe

---
#### Sascha Bothe on 8/8/2022, 00:23 PM: 

(private comment, text removed)

---
#### Sascha Bothe solved on 8/8/2022, 00:31 PM, 0 votes: 

<p>PARTIAL SOLUTION<br>
At the breakpoint before asking for the file in the call stack go to the module and decompile it<br>
then make it available to the debugger. ( System.Console.dll )</p>
<p>But that doesn’t fix the error with the breakpoint.</p>

**Comment by tommcdon** [comment]
@jkoritzinsky this issue seems to be related to the pinvoke source generator.  Is it possible to embed the source info into the PDB so the interop stubs are debuggable?  cc @hoyosjs

**Comment by jkoritzinsky** [comment]
We don't (and can't) do anything special as part of the P/Invoke source generator to embed sources. They should already be debuggable as that's one of the big draws of using source generators. Roslyn does embed the sources, so they should be in the PDB. Maybe ILLink or the source-link step is stripping the embedded documents?

**Comment by tommcdon** [comment]
> Maybe ILLink or the source-link step is stripping the embedded documents?

@vitek-karas do you know if ILLink removes PInvoke source generated sources from the System.Private.Corelib PDB?

**Comment by hoyosjs** [comment]
Sourcelink embedded the generated source into the IL PDB. I see:

```
5481880814ac67dd7df6be9aee02dbcfd6491ee9 sha1 csharp /_/src/libraries/System.Console/src/Microsoft.Interop.LibraryImportGenerator/Microsoft.Interop.LibraryImportGenerator/LibraryImports.g.cs
embedded
```

This is a byproduct of optimized debugging of the runtime. Both the breakpoint and the issue with source mapping. Once I turn off jit opt and r2r I get to the source by stepping:

![image](https://user-images.githubusercontent.com/19413848/183550926-c7f2552f-ec8b-4610-87a1-a3e6ee7be5f8.png)

**Comment by tommcdon** [comment]
Closing via analysis from @hoyojs
