### ISSUE TITLE
Assertion failed in loader: , condition `<disabled>' not met

### ISSUE THREAD

**Issue by 3HMonkey** [dotnet/runtime#73617]
### Description

I am currently working on a dotnet app migration from console app over to wasm. Setup is providing the wasm using asp.net. All compiled with latest net7 preview. The app is loading until it reaches the assertion failed error.

![image](https://user-images.githubusercontent.com/4610892/183638827-2a745a86-0552-4172-8fb8-8c537e2fd298.png)

### Reproduction Steps

- compiled app to wasm
- provide app with asp.net

### Expected behavior

Detailed debugging or error shouldnt occur

### Actual behavior

```
Error: [MONO] * Assertion at /__w/1/s/src/mono/mono/metadata/loader.c:1817, condition `<disabled>' not met

    at mono_wasm_stringify_as_error_with_stack (dotnet.js:3:23817)
    at Object.mono_wasm_trace_logger (dotnet.js:3:24188)
    at _mono_wasm_trace_logger (dotnet.js:11593:67)
    at wasm_trace_logger (dotnet.wasm:0x3418a5)
    at eglib_log_adapter (dotnet.wasm:0x1cb475)
    at monoeg_g_logstr (dotnet.wasm:0x31e294)
    at monoeg_g_logv_nofree (dotnet.wasm:0x31e236)
    at monoeg_assertion_message (dotnet.wasm:0x31e317)
    at mono_assertion_message (dotnet.wasm:0x31e362)
    at mono_assertion_message_disabled (dotnet.wasm:0x31e331)
```

### Known Workarounds

none yet

### Configuration

- 7.0.100-preview.6.22352.1 SDK

```xml
<TargetFramework>net7.0</TargetFramework>
    <TargetArchitecture>wasm</TargetArchitecture>
    <TargetOS>browser</TargetOS>
    <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
    <UseMonoRuntime>true</UseMonoRuntime>
    <WasmMainJSPath>wwwroot/main.js</WasmMainJSPath>
    <OutputType>Exe</OutputType>
    <WasmEnableES6>true</WasmEnableES6>
    <PublishTrimmed>true</PublishTrimmed>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    
    <WasmAppDir>../output/wwwroot</WasmAppDir>
    <RunAOTCompilation>true</RunAOTCompilation>
```

**Comment by 3HMonkey** [comment]
`<PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <TargetArchitecture>wasm</TargetArchitecture>
    <TargetOS>browser</TargetOS>
    <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
    <UseMonoRuntime>true</UseMonoRuntime>
    <WasmMainJSPath>wwwroot/main.js</WasmMainJSPath>
    <OutputType>Exe</OutputType>
    <WasmEnableES6>true</WasmEnableES6>
    <PublishTrimmed>true</PublishTrimmed>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <WasmAppDir>../output/wwwroot</WasmAppDir>
    <RunAOTCompilation>true</RunAOTCompilation>
    
    <EmccFlags>-sFULL_ES3</EmccFlags>
  </PropertyGroup>`

**Comment by radical** [comment]
- Do you have a small test project that reproduces this issue?
- Also, what exactly do you mean by the two steps - `compiled app to wasm, provide app with asp.net`?

**Comment by 3HMonkey** [comment]
The app what I am talking about is a game/engine which was original wrote for net5/6/7 and FNA. These are now compiled to wasm as target framework. The wasm is provided with asp.net what is running so far. We also provided the game files which are using the memfs. The wasm starts fine, loads the files successfully, initialize everything as expected and outputs to console in browser. The same like the original net7 app does. Then that error occurs. Since the game files would be included in the Demo case we have so far it would suggest that we can show you the topic?

**Comment by radical** [comment]
> so far it would suggest that we can show you the topic?

What do you mean by "topic" ?
- Is there more of that stack trace? Expand that block in the js console, it should have more frames.
- Also, is this with AOT? I know the property is set, but are you publishing, and then running the app?

**Comment by 3HMonkey** [comment]
Here are all the frames of the stacktrace

dotnet.js:3 Error: [MONO] * Assertion at /__w/1/s/src/mono/mono/metadata/loader.c:1817, condition `<disabled>' not met

    at mono_wasm_stringify_as_error_with_stack (dotnet.js:3:23817)
    at Object.mono_wasm_trace_logger (dotnet.js:3:24188)
    at _mono_wasm_trace_logger (dotnet.js:11593:67)
    at wasm_trace_logger (dotnet.wasm:0x3418a5)
    at eglib_log_adapter (dotnet.wasm:0x1cb475)
    at monoeg_g_logstr (dotnet.wasm:0x31e294)
    at monoeg_g_logv_nofree (dotnet.wasm:0x31e236)
    at monoeg_assertion_message (dotnet.wasm:0x31e317)
    at mono_assertion_message (dotnet.wasm:0x31e362)
    at mono_assertion_message_disabled (dotnet.wasm:0x31e331)
mono_wasm_trace_logger @ dotnet.js:3
_mono_wasm_trace_logger @ dotnet.js:11593
$wasm_trace_logger @ dotnet.wasm:0x3418a5
$eglib_log_adapter @ dotnet.wasm:0x1cb475
$monoeg_g_logstr @ dotnet.wasm:0x31e294
$monoeg_g_logv_nofree @ dotnet.wasm:0x31e236
$monoeg_assertion_message @ dotnet.wasm:0x31e317
$mono_assertion_message @ dotnet.wasm:0x31e362
$mono_assertion_message_disabled @ dotnet.wasm:0x31e331
$mono_method_signature_checked_slow @ dotnet.wasm:0x1895cb
$mono_method_signature_checked.3 @ dotnet.wasm:0x171087
$mono_method_get_name_full @ dotnet.wasm:0x170e75
$mono_method_get_full_name @ dotnet.wasm:0x1710a8
$interp_create_method_pointer @ dotnet.wasm:0x10e672
$mono_jit_compile_method_with_opt @ dotnet.wasm:0x2fa885
$jit_compile_method_with_opt_cb @ dotnet.wasm:0x2f6fd1
invoke_vi @ dotnet.js:13266
$mono_llvm_cpp_catch_exception @ dotnet.wasm:0x1408c8
$jit_compile_method_with_opt @ dotnet.wasm:0x2f6f91
$mono_jit_compile_method @ dotnet.wasm:0x2f6e31
$mono_compile_method_checked @ dotnet.wasm:0x1a1249
$mono_delegate_to_ftnptr_impl @ dotnet.wasm:0x18c5ba
$mono_delegate_to_ftnptr @ dotnet.wasm:0x184526
$do_icall @ dotnet.wasm:0x11f735
$do_icall_wrapper @ dotnet.wasm:0x11e737
$interp_exec_method @ dotnet.wasm:0x119ff4
$interp_runtime_invoke @ dotnet.wasm:0x10ea38
$mono_jit_runtime_invoke @ dotnet.wasm:0x2f8095
$do_runtime_invoke @ dotnet.wasm:0x1a0045
$mono_runtime_try_invoke @ dotnet.wasm:0x1a0789
$mono_runtime_invoke @ dotnet.wasm:0x1a291b
$mono_wasm_invoke_method_ref @ dotnet.wasm:0x341c18
Module._mono_wasm_invoke_method_ref @ dotnet.js:12799
o.<computed> @ dotnet.js:3
_call_method_with_converted_args @ dotnet.js:3
call_method_ref @ dotnet.js:3
(anonymous) @ dotnet.js:3
mono_call_assembly_entry_point @ dotnet.js:3
mono_run_main @ dotnet.js:3
App.init @ main.js:5
onDotnetReady @ app-support.js:222
finalize_startup @ dotnet.js:3
mono_wasm_after_runtime_initialized @ dotnet.js:3
callRuntimeCallbacks @ dotnet.js:1572
postRun @ dotnet.js:1235
doRun @ dotnet.js:13411
run @ dotnet.js:13424
runCaller @ dotnet.js:13378
removeRunDependency @ dotnet.js:1304
mono_wasm_pre_init @ dotnet.js:3
await in mono_wasm_pre_init (async)
(anonymous) @ dotnet.js:13453
(anonymous) @ app-support.js:174
Promise.then (async)
(anonymous) @ app-support.js:171
Show 20 more frames
index.html:1 Uncaught (in promise) ExitStatus {name: 'ExitStatus', message: 'Program terminated with exit(1)', status: 1}
Promise.then (async)
onDotnetReady @ app-support.js:223
finalize_startup @ dotnet.js:3
mono_wasm_after_runtime_initialized @ dotnet.js:3
callRuntimeCallbacks @ dotnet.js:1572
postRun @ dotnet.js:1235
doRun @ dotnet.js:13411
run @ dotnet.js:13424
runCaller @ dotnet.js:13378
removeRunDependency @ dotnet.js:1304
mono_wasm_pre_init @ dotnet.js:3
await in mono_wasm_pre_init (async)
(anonymous) @ dotnet.js:13453
(anonymous) @ app-support.js:174
Promise.then (async)
(anonymous) @ app-support.js:171

**Comment by radical** [comment]
@BrzVlad @vargaz Any idea what might be going on here?

**Comment by pavelsavara** [comment]
Note: `mono_call_assembly_entry_point` is not part of the template anymore in Net7 RC1. 
I'm not saying it will fix the underlying problem, just that there is different code path now.

**Comment by 3HMonkey** [comment]
> Note: `mono_call_assembly_entry_point` is not part of the template anymore in Net7 RC1. I'm not saying it will fix the underlying problem, just that there is different code path now.

Thx for reply. What does that mean in detail?

**Comment by danmoseley** [comment]
@3HMonkey Can you try with the latest build from the dotnet/installer repo, and post that stack?

**Comment by 3HMonkey** [comment]
> @3HMonkey Can you try with the latest build from the dotnet/installer repo, and post that stack?

I gonna test it with the latest installer build soon. I was testing with preview 7 this morning with the same effect:

![image](https://user-images.githubusercontent.com/4610892/187073948-a6b1bf41-0ae7-49cb-aaeb-8950831d94e1.png)

**Comment by danmoseley** [comment]
There is no preview 8: next is RC1. You could test with that (Release/7.0.1xx-RC1) or Release/7.0.1xx which is slightly newer.

https://github.com/dotnet/installer

**Comment by 3HMonkey** [comment]
> There is no preview 8: next is RC1. You could test with that (Release/7.0.1xx-RC1) or Release/7.0.1xx which is slightly newer.
> 
> https://github.com/dotnet/installer

Yeah this is already installed. Do I need to switch something?

![image](https://user-images.githubusercontent.com/4610892/187090457-de331043-ae53-4118-957d-dd490a809b97.png)

**Comment by 3HMonkey** [comment]
Hello, here is some additional info about this. I prepared the same stacktrace in firefox:

> 09/08/2022 06:59:24 |   Trace    | Running game... dotnet.js:2292:16
FNA3D Driver: OpenGL dotnet.js:2292:16
OpenGL Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0) dotnet.js:2292:16
OpenGL Driver: OpenGL ES 3.0 (WebGL 2.0) dotnet.js:2292:16
OpenGL Vendor: Mozilla dotnet.js:2292:16
MojoShader Profile: glsles dotnet.js:2292:16
vt@http://localhost:5000/dotnet.js:3:19686
At@http://localhost:5000/dotnet.js:3:19969
_mono_wasm_trace_logger@http://localhost:5000/dotnet.js:11518:67
wasm_trace_logger@http://localhost:5000/dotnet.wasm:wasm-function[20426]:0x341e1f
eglib_log_adapter@http://localhost:5000/dotnet.wasm:wasm-function[8011]:0x1cc4c3
monoeg_g_logstr@http://localhost:5000/dotnet.wasm:wasm-function[19504]:0x31e5da
monoeg_g_logv_nofree@http://localhost:5000/dotnet.wasm:wasm-function[19502]:0x31e57c
monoeg_assertion_message@http://localhost:5000/dotnet.wasm:wasm-function[19507]:0x31e65d
mono_assertion_message@http://localhost:5000/dotnet.wasm:wasm-function[19509]:0x31e6a8
mono_assertion_message_disabled@http://localhost:5000/dotnet.wasm:wasm-function[19508]:0x31e677
mono_method_signature_checked_slow@http://localhost:5000/dotnet.wasm:wasm-function[5567]:0x18a465
mono_method_signature_checked.3@http://localhost:5000/dotnet.wasm:wasm-function[4727]:0x171725
mono_method_get_name_full@http://localhost:5000/dotnet.wasm:wasm-function[4726]:0x171513
mono_method_get_full_name@http://localhost:5000/dotnet.wasm:wasm-function[4729]:0x171746
interp_create_method_pointer@http://localhost:5000/dotnet.wasm:wasm-function[2846]:0x10e719
mono_jit_compile_method_with_opt@http://localhost:5000/dotnet.wasm:wasm-function[18539]:0x2fad44
jit_compile_method_with_opt_cb@http://localhost:5000/dotnet.wasm:wasm-function[18449]:0x2f7497
invoke_vi@http://localhost:5000/dotnet.js:13137:29
mono_llvm_cpp_catch_exception@http://localhost:5000/dotnet.wasm:wasm-function[3478]:0x1410c2
jit_compile_method_with_opt@http://localhost:5000/dotnet.wasm:wasm-function[18448]:0x2f7457
mono_jit_compile_method@http://localhost:5000/dotnet.wasm:wasm-function[18446]:0x2f72f7
mono_compile_method_checked@http://localhost:5000/dotnet.wasm:wasm-function[6375]:0x1a2129
mono_delegate_to_ftnptr_impl@http://localhost:5000/dotnet.wasm:wasm-function[5656]:0x18d438
mono_delegate_to_ftnptr@http://localhost:5000/dotnet.wasm:wasm-function[5376]:0x18535a
do_icall@http://localhost:5000/dotnet.wasm:wasm-function[2980]:0x11feaf
do_icall_wrapper@http://localhost:5000/dotnet.wasm:wasm-function[2927]:0x11eec7
interp_exec_method@http://localhost:5000/dotnet.wasm:wasm-function[2856]:0x11a71b
interp_runtime_invoke@http://localhost:5000/dotnet.wasm:wasm-function[2855]:0x10eadb
mono_jit_runtime_invoke@http://localhost:5000/dotnet.wasm:wasm-function[18474]:0x2f8567
do_runtime_invoke@http://localhost:5000/dotnet.wasm:wasm-function[6344]:0x1a0f11
mono_runtime_try_invoke@http://localhost:5000/dotnet.wasm:wasm-function[6355]:0x1a1655
mono_runtime_invoke@http://localhost:5000/dotnet.wasm:wasm-function[6432]:0x1a37f0
mono_wasm_invoke_method_ref@http://localhost:5000/dotnet.wasm:wasm-function[20437]:0x3421e7
createDotnetRuntime</</Module._mono_wasm_invoke_method_ref@http://localhost:5000/dotnet.js:12670:129
__dotnet_runtime</t[e[0]]@http://localhost:5000/dotnet.js:3:4905
Ao@http://localhost:5000/dotnet.js:3:52768
bo@http://localhost:5000/dotnet.js:3:52268
To/<@http://localhost:5000/dotnet.js:3:53419
No@http://localhost:5000/dotnet.js:3:53482
Xo@http://localhost:5000/dotnet.js:3:59548
App.init@http://localhost:5000/main.js:5:20
onDotnetReady@http://localhost:5000/app-support.js:222:35
Bi@http://localhost:5000/dotnet.js:3:89491
Ii@http://localhost:5000/dotnet.js:3:86145
callRuntimeCallbacks@http://localhost:5000/dotnet.js:1525:19
postRun@http://localhost:5000/dotnet.js:1186:23
doRun@http://localhost:5000/dotnet.js:13282:5
run@http://localhost:5000/dotnet.js:13295:5
runCaller@http://localhost:5000/dotnet.js:13249:19
removeRunDependency@http://localhost:5000/dotnet.js:1255:7
ji@http://localhost:5000/dotnet.js:3:86046
dotnet.js:3:19963
    At http://localhost:5000/dotnet.js:3
    _mono_wasm_trace_logger http://localhost:5000/dotnet.js:11518
    wasm_trace_logger http://localhost:5000/dotnet.wasm:3415583
    eglib_log_adapter http://localhost:5000/dotnet.wasm:1885379
    monoeg_g_logstr http://localhost:5000/dotnet.wasm:3270106
    monoeg_g_logv_nofree http://localhost:5000/dotnet.wasm:3270012
    monoeg_assertion_message http://localhost:5000/dotnet.wasm:3270237
    mono_assertion_message http://localhost:5000/dotnet.wasm:3270312
    mono_assertion_message_disabled http://localhost:5000/dotnet.wasm:3270263
    mono_method_signature_checked_slow http://localhost:5000/dotnet.wasm:1614949
    3 http://localhost:5000/dotnet.wasm:1513253
    mono_method_get_name_full http://localhost:5000/dotnet.wasm:1512723
    mono_method_get_full_name http://localhost:5000/dotnet.wasm:1513286
    interp_create_method_pointer http://localhost:5000/dotnet.wasm:1107737
    mono_jit_compile_method_with_opt http://localhost:5000/dotnet.wasm:3124548
    jit_compile_method_with_opt_cb http://localhost:5000/dotnet.wasm:3110039
    invoke_vi http://localhost:5000/dotnet.js:13137
    mono_llvm_cpp_catch_exception http://localhost:5000/dotnet.wasm:1315010
    jit_compile_method_with_opt http://localhost:5000/dotnet.wasm:3109975
    mono_jit_compile_method http://localhost:5000/dotnet.wasm:3109623
    mono_compile_method_checked http://localhost:5000/dotnet.wasm:1712425
    mono_delegate_to_ftnptr_impl http://localhost:5000/dotnet.wasm:1627192
    mono_delegate_to_ftnptr http://localhost:5000/dotnet.wasm:1594202
    do_icall http://localhost:5000/dotnet.wasm:1179311
    do_icall_wrapper http://localhost:5000/dotnet.wasm:1175239
    interp_exec_method http://localhost:5000/dotnet.wasm:1156891
    interp_runtime_invoke http://localhost:5000/dotnet.wasm:1108699
    mono_jit_runtime_invoke http://localhost:5000/dotnet.wasm:3114343
    do_runtime_invoke http://localhost:5000/dotnet.wasm:1707793
    mono_runtime_try_invoke http://localhost:5000/dotnet.wasm:1709653
    mono_runtime_invoke http://localhost:5000/dotnet.wasm:1718256
    mono_wasm_invoke_method_ref http://localhost:5000/dotnet.wasm:3416551
    _mono_wasm_invoke_method_ref http://localhost:5000/dotnet.js:12670
    e[0] http://localhost:5000/dotnet.js:3
    Ao http://localhost:5000/dotnet.js:3
    bo http://localhost:5000/dotnet.js:3
    To http://localhost:5000/dotnet.js:3
    No http://localhost:5000/dotnet.js:3
    Xo http://localhost:5000/dotnet.js:3
    init http://localhost:5000/main.js:5
    onDotnetReady http://localhost:5000/app-support.js:222
    Bi http://localhost:5000/dotnet.js:3
    Ii http://localhost:5000/dotnet.js:3
    callRuntimeCallbacks http://localhost:5000/dotnet.js:1525
    postRun http://localhost:5000/dotnet.js:1186
    doRun http://localhost:5000/dotnet.js:13282
    run http://localhost:5000/dotnet.js:13295
    runCaller http://localhost:5000/dotnet.js:13249
    removeRunDependency http://localhost:5000/dotnet.js:1255
    ji http://localhost:5000/dotnet.js:3
WebGL warning: getInternalfomratParameter: `internalformat` must be color-, depth-, or stencil-renderable, was: 0x83f1.
WebGL warning: getInternalfomratParameter: `internalformat` must be color-, depth-, or stencil-renderable, was: 0x83f2.
WebGL warning: getInternalfomratParameter: `internalformat` must be color-, depth-, or stencil-renderable, was: 0x83f3.
WebGL warning: getInternalfomratParameter: `internalformat` must be color-, depth-, or stencil-renderable, was: 0x822c.
WebGL warning: getInternalfomratParameter: `internalformat` must be color-, depth-, or stencil-renderable, was: 0x805b.
WebGL warning: getInternalfomratParameter: `internalformat` must be color-, depth-, or stencil-renderable, was: 0x1906.
Uncaught (in promise) 
Object { name: "ExitStatus", message: "Program terminated with exit(1)", status: 1 }

And in edge:

> Error: [MONO] * Assertion at /__w/1/s/src/mono/mono/metadata/loader.c:1817, condition `<disabled>' not met
    at vt (dotnet.js:3:19686)
    at Object.At (dotnet.js:3:19969)
    at _mono_wasm_trace_logger (dotnet.js:11518:67)
    at wasm_trace_logger (dotnet.wasm:0x341e1f)
    at eglib_log_adapter (dotnet.wasm:0x1cc4c3)
    at monoeg_g_logstr (dotnet.wasm:0x31e5da)
    at monoeg_g_logv_nofree (dotnet.wasm:0x31e57c)
    at monoeg_assertion_message (dotnet.wasm:0x31e65d)
    at mono_assertion_message (dotnet.wasm:0x31e6a8)
    at mono_assertion_message_disabled (dotnet.wasm:0x31e677)
At @ dotnet.js:3
_mono_wasm_trace_logger @ dotnet.js:11518
$wasm_trace_logger @ dotnet.wasm:0x341e1f
$eglib_log_adapter @ dotnet.wasm:0x1cc4c3
$monoeg_g_logstr @ dotnet.wasm:0x31e5da
$monoeg_g_logv_nofree @ dotnet.wasm:0x31e57c
$monoeg_assertion_message @ dotnet.wasm:0x31e65d
$mono_assertion_message @ dotnet.wasm:0x31e6a8
$mono_assertion_message_disabled @ dotnet.wasm:0x31e677
$mono_method_signature_checked_slow @ dotnet.wasm:0x18a465
$mono_method_signature_checked.3 @ dotnet.wasm:0x171725
$mono_method_get_name_full @ dotnet.wasm:0x171513
$mono_method_get_full_name @ dotnet.wasm:0x171746
$interp_create_method_pointer @ dotnet.wasm:0x10e719
$mono_jit_compile_method_with_opt @ dotnet.wasm:0x2fad44
$jit_compile_method_with_opt_cb @ dotnet.wasm:0x2f7497
invoke_vi @ dotnet.js:13137
$mono_llvm_cpp_catch_exception @ dotnet.wasm:0x1410c2
$jit_compile_method_with_opt @ dotnet.wasm:0x2f7457
$mono_jit_compile_method @ dotnet.wasm:0x2f72f7
$mono_compile_method_checked @ dotnet.wasm:0x1a2129
$mono_delegate_to_ftnptr_impl @ dotnet.wasm:0x18d438
$mono_delegate_to_ftnptr @ dotnet.wasm:0x18535a
$do_icall @ dotnet.wasm:0x11feaf
$do_icall_wrapper @ dotnet.wasm:0x11eec7
$interp_exec_method @ dotnet.wasm:0x11a71b
$interp_runtime_invoke @ dotnet.wasm:0x10eadb
$mono_jit_runtime_invoke @ dotnet.wasm:0x2f8567
$do_runtime_invoke @ dotnet.wasm:0x1a0f11
$mono_runtime_try_invoke @ dotnet.wasm:0x1a1655
$mono_runtime_invoke @ dotnet.wasm:0x1a37f0
$mono_wasm_invoke_method_ref @ dotnet.wasm:0x3421e7
Module._mono_wasm_invoke_method_ref @ dotnet.js:12670
t.<computed> @ dotnet.js:3
Ao @ dotnet.js:3
bo @ dotnet.js:3
(anonym) @ dotnet.js:3
No @ dotnet.js:3
Xo @ dotnet.js:3
App.init @ main.js:5
onDotnetReady @ app-support.js:222
Bi @ dotnet.js:3
Ii @ dotnet.js:3
callRuntimeCallbacks @ dotnet.js:1525
postRun @ dotnet.js:1186
doRun @ dotnet.js:13282
run @ dotnet.js:13295
runCaller @ dotnet.js:13249
removeRunDependency @ dotnet.js:1255
ji @ dotnet.js:3
Show 20 more frames
index.html:1 
Uncaught (in promise) ExitStatus {name: 'ExitStatus', message: 'Program terminated with exit(1)', status: 1}
Promise.then (asynchron)
onDotnetReady @ app-support.js:223
Bi @ dotnet.js:3
Ii @ dotnet.js:3
callRuntimeCallbacks @ dotnet.js:1525
postRun @ dotnet.js:1186
doRun @ dotnet.js:13282
run @ dotnet.js:13295
runCaller @ dotnet.js:13249
removeRunDependency @ dotnet.js:1255
ji @ dotnet.js:3

I do not know if this helps, since this message is very generic. Any idea how to debug this more in detail?

**Comment by 3HMonkey** [comment]
Finally found the methode/function what causes the error. But I still do not know why this occurs and/or how to prevent it. I'll try to explain a bit more in detail. As you guys know I am using FNA/SDL2.

1. I have a private variable what inits the SDL_EventFilter
```csharp
private SDL_EventFilter _filter;
```
2. In an initialize methode we set the filters for handling SDL-Events. Afterwards the methode what sets these filters in SDL. Example:
```csharp
protected override void Initialize()
        {
            // ...
            _filter = HandleSdlEvent;
            SDL_SetEventFilter(_filter, IntPtr.Zero);
            base.Initialize();

        }
```

`HandleSdlEvent` consumes two integer pointers. Here the example:
```csharp
private int HandleSdlEvent(IntPtr userData, IntPtr ptr)
        {

            SDL_Event* sdlEvent = (SDL_Event*)ptr;

            if (Plugin.ProcessWndProc(sdlEvent) != 0)
            {
                if (sdlEvent->type == SDL_EventType.SDL_MOUSEMOTION)
                {
                    if (GameCursor != null)
                    {
                        GameCursor.AllowDrawSDLCursor = false;
                    }
                }

                return 1;
            }

            switch (sdlEvent->type)
            {
                case SDL_EventType.SDL_AUDIODEVICEADDED:
                    Console.WriteLine("AUDIO ADDED: {0}", sdlEvent->adevice.which);

                    break;

                case SDL_EventType.SDL_AUDIODEVICEREMOVED:
                    Console.WriteLine("AUDIO REMOVED: {0}", sdlEvent->adevice.which);

                    break;
//...
```

SDL_EventFilter and SDL_SetEventFilter are inside native and consume these pointers
```csharp
[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
		public delegate int SDL_EventFilter(
			IntPtr userdata, // void*
			IntPtr sdlevent // SDL_Event* event, lolC#
		);
```

```csharp
/* userdata refers to a void* */
		[DllImport(nativeLibName, CallingConvention = CallingConvention.Cdecl)]
		public static extern void SDL_SetEventFilter(
			SDL_EventFilter filter,
			IntPtr userdata
		);
```

When commenting `SDL_SetEventFilter(_filter, IntPtr.Zero);` in code or passing "NULL" as filters no error occurs. Only when passing the `HandleSdlEvent` the assertion not met error comes up. I expect that mono/emscripten is cutting something out that the pointer of  `HandleSdlEvent` cannot be found anymore.

**Comment by lewing** [comment]
Are you still able to reproduce this?
