### ISSUE TITLE
JIT incorrectly reorders constrained call 'this' indirections with other arguments

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#73615]
Small example:
```csharp
using InlineIL;
using System;
using System.Runtime.CompilerServices;

public class Program
{
    public static void Main()
    {
        Foo(new C("A"));
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private static void Foo(C arg)
    {
        IL.Emit.Ldarga(nameof(arg));
        IL.Emit.Ldarga(nameof(arg));
        IL.Emit.Call(new MethodRef(typeof(Program), nameof(Bar)));
        IL.Emit.Constrained<C>();
        IL.Emit.Callvirt(new MethodRef(typeof(C), nameof(arg.Baz)));
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private static int Bar(ref C o)
    {
        o = new C("B");
        return 0;
    }
}

public record class C(string Name)
{
    public void Baz(int arg)
    {
        Console.WriteLine(Name);
    }
}
```
Expected: B
Actual: A

Seen in https://github.com/dotnet/runtime/issues/73606#issuecomment-1209210990

category:correctness
theme:importer
skill-level:intermediate
cost:small
impact:small

**Comment by jakobbotsch** [comment]
This needs to wait for https://github.com/dotnet/roslyn/issues/63221 for a runtime side fix. As of writing this the C# compiler has been fixed, but not the VB.NET compiler.

**Comment by jakobbotsch** [comment]
I'm going to move this to 9.0 since it's blocked waiting for a Roslyn VB.NET fix.

**Comment by AlekseyTs** [comment]
@jakobbotsch FYI, the fix for https://github.com/dotnet/roslyn/issues/63221 for VB got merged into Roslyn.
