### ISSUE TITLE
[blazor] canot debug blazor client when using custom domain name / "Unbound breakpoint"

### ISSUE THREAD

**Issue by d00lar** [dotnet/runtime#73614]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

hi
im building some Blazor wasm project

and to access OIDC i had to make my dev iis expres to run under https:/xxx.localhost and OIDC is veryfying this callback url so it mus be like that

so i had to add to my hosts xxx.localhost 127.0.0.1 and then edit applicationhost.config and add
 ```
<bindings>
          <binding protocol="http" bindingInformation="*:80:localhost" />
	  <binding protocol="https" bindingInformation="*:443:localhost" />
	  <binding protocol="http" bindingInformation="*:80:xx.localhost" />
                    <binding protocol="https" bindingInformation="*:443:xx.localhost" />
 </bindings>
```

then
i generated local cert (not shure if it is needed but i was searching for solution)

`New-SelfSignedCertificate -DnsName "xx.localhost" -CertStoreLocation "cert:\LocalMachine\My"  CN=xx.localhost
`
then i moved it  to trusted.

` netsh http add sslcert ipport=0.0.0.0:443 certhash=hash....... appid={214124cd-d05b-4309-9af9-9caa44b2b74a}
`
then added lisener
```
  netsh 
  http
  add urlacl url=https://xx.localhost:443/ user=everyone
  add urlacl url=http://xx.localhost:80/ user=everyone
```

and it is wotking - now i can run it on xxx.localhost , cert is ok 
but still i canot debug.

i updatet launchserrings.json
```

  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://xx.localhost:80",
      "sslPort": 443
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "launchUrl": "http://xx.localhost:80",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
      //"applicationUrl": "http://xx.localhost;https://xx.localhost", 
      "nativeDebugging": false
    },
    "xx.Server": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
      "applicationUrl": "http://xx.localhost;https://xx.localhost",
      "dotnetRunMessages": "true"
    }
  }
}
```

and still on debug on client i have
![lPNHi](https://user-images.githubusercontent.com/22784835/183581537-0f6a76d3-3f4a-48f7-9ef7-3d1f63b2b028.png)

here is my visualstudio-js-debugger
[visualstudio-js-debugger.txt](https://github.com/dotnet/aspnetcore/files/9287615/visualstudio-js-debugger.txt)

am i missing something or debugging on custom domain is not possible ? 
thanks and regards

### Expected Behavior

debugging on custom domain name should also be possible 

### Steps To Reproduce

as above. new project. , new hosts entry , new bindings. new cert. and breakpoint in any place in client project.

### Exceptions (if any)

domain blazor "message":"Unbound breakpoint"}, - in verbouse log

### .NET Version

6

### Anything else?

asp.net.core 6
visual studio 2022

C:\Users\xx>dotnet --info
Zestaw .NET SDK (odzwierciedlenie dowolnego pliku global.json):
 Version:   6.0.302
 Commit:    c857713418

Środowisko uruchomieniowe:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.302\

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  6.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by d00lar** [comment]
> I couldn't figure out the best area label to add to this issue. If you have write-permissions please help me learn by adding exactly one [area label](https://github.com/dotnet/runtime/blob/master/docs/area-owners.md).

i do not have but maybe area-Debugger-mono?

**Comment by radical** [comment]
cc @javiercn Are the non-debugger changes described correct? If so, then we can look at it from the debugger pov.

**Comment by radical** [comment]
cc @thaystg

**Comment by thaystg** [comment]
@javiercn as we can see in the screen shot the breakpoint that is not being bound is on server side. on S2Mud.Server.dll, so I think it's not related to mono debugger.

**Comment by javiercn** [comment]
@radical @thaystg let me take a look.

**Comment by d00lar** [comment]
ok sory for trouble. it is working like that
is its not working when im connected to vpn so guess cisco somehow block this connection when not on localhost directly.

**Comment by radical** [comment]
Closing this based on @d00lar's comment. This was a network issue, with VPN software causing an issue here.

> does anyone of You known exacly what can be blocked so i could report this to vpn teem

Maybe @javiercn will know?

Also, @javiercn feel free to re-open this if there is anything to be done here. Could there be better error detection about this kind of a case?

**Comment by d00lar** [comment]
edit...
it was even easier. it was proxy issue
when using xx.localhost it was trying go via proxy...
