### ISSUE TITLE
`xunit.extensibility.execution 2.4.2-pre.22` - ` primary signature's signing certificate is not trusted by the trust provider.`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#73646]
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1930800&view=logs&jobId=eb51b6b1-acd4-5d0e-ec03-d6dd16ab13c9&j=eb51b6b1-acd4-5d0e-ec03-d6dd16ab13c9&t=01d65644-2e0a-5b21-5167-e35202b4b294) for `Libraries Build windows x64 Debug` on unrelated https://github.com/dotnet/runtime/pull/73435 :

`D:\a\_work\1\s\src\libraries\Microsoft.Extensions.HostFactoryResolver\tests\Microsoft.Extensions.HostFactoryResolver.Tests.csproj : error NU3018: Package 'xunit.extensibility.execution 2.4.2-pre.22' from source 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json': The author primary signature's signing certificate is not trusted by the trust provider. [D:\a\_work\1\s\Build.proj]`

Runfo Tracking Issue: [NU3018 when restoring Xunit packages](https://runfo.azurewebsites.net/tracking/issue/427)
|Definition|Build|Kind|Job Name|
|---|---|---|---|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|0|0|0|

**Comment by carlossanlop** [comment]
@dotnet/dnceng is this something you could help with?

**Comment by MattGal** [comment]
> ...  is this something you could help with?

If this is isn't a transient error, you can try a different build... this version is specified by https://github.com/dotnet/runtime/blob/main/eng/Versions.props#L157 and not controlled by the dnceng team.

**Comment by ericstj** [comment]
This package was built by @clairernovotny for us and has been working just fine.   What would have changed to make this no longer work?

Something about trusted certificates on the machines?  @radical this wasn't hitting on all machines was it?  Was it specific to a single machine or machine type?

cc @mmitche

**Comment by radical** [comment]
I didn't see this anywhere else, but I'm don't track `Libraries Build windows x64 Debug` builds, so I don't know if it has been seen on any other PRs/branches.

**Comment by ericstj** [comment]
I added runfo tracking to this.  I don't think this is a product issue - more likely machine configuration around certificates.  Moving this out to 8.0.0.

**Comment by karelz** [comment]
Looks like it happened only 2x in last month - 8/15 and 8/19.
