### ISSUE TITLE
React to ref escape changes in interpolated string handlers

### ISSUE THREAD

**Issue by 333fred** [dotnet/runtime#73642]
The BCL's interpolated string handlers (any type that is attributed with `InterpolatedStringHandlerAttribute`) need to updated to react to the changes in https://github.com/dotnet/roslyn/pull/63263, which is fixing the calculation of ref escape scopes for arguments passed to `AppendFormatted`. Specifically, all handler methods that meet the following criteria need to be updated to have `scoped` parameters:

1. The handler type is a `ref struct`.
2. The parameter to `AppendFormatted` is a ref struct (most commonly this will be a `ReadOnlySpan<T>`).

**Comment by jeffhandley** [comment]
FYI @dotnet/area-infrastructure-libraries

**Comment by bartonjs** [comment]
Assuming that `ref struct` types still can't be used as a generic parameter, the places that need to be updated are

* `MemoryExtensions.TryWriteInterpolatedStringHandler.AppendFormatted(ReadOnlySpan<char>)`
  * https://source.dot.net/#System.Private.CoreLib/MemoryExtensions.cs,cb65b541ddc53a6b
* `MemoryExtensions.TryWriteInterpolatedStringHandler.AppendFormatted(ReadOnlySpan<char>, int, string)`
  * https://source.dot.net/#System.Private.CoreLib/MemoryExtensions.cs,c924775969f2dd9e
* `DefaultInterpolatedStringHandler.AppendFormatted(ReadOnlySpan<char>)`
  * https://source.dot.net/#System.Private.CoreLib/DefaultInterpolatedStringHandler.cs,09cdd5dbe6eed421
* `DefaultInterpolatedStringHandler.AppendFormatted(ReadOnlySpan<char>, int, string)`
  * https://source.dot.net/#System.Private.CoreLib/DefaultInterpolatedStringHandler.cs,6f7fc2345aad037c
