### ISSUE TITLE
Assert (g_gc_lowest_address <= address) && (address < g_gc_highest_address) File: /__w/1/s/src/coreclr/gc/gc.cpp Line: 3571

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/runtime#73653]
### Description

Assert failure(PID 26453 [0x00006755], Thread: 26453 [0x6755]): (g_gc_lowest_address <= address) && (address < g_gc_highest_address)
File: /__w/1/s/src/coreclr/gc/gc.cpp Line: 3571
Image: /datadisks/disk1/work/B6590997/p/corerun

/datadisks/disk1/work/B6590997/w/A91F0981/e/GC/API/Frozen/Frozen/Frozen.sh: line 391: 26453 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /datadisks/disk1/work/B6590997/w/A91F0981/uploads/Reports/GC.API/Frozen/Frozen/Frozen.output.txt
Raw output:
BEGIN EXECUTION
/datadisks/disk1/work/B6590997/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false Frozen.dll ''
[createdump] Gathering state for process 26453 corerun
[createdump] Crashing thread 00006755 signal 00000006
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.26453.dmp
[createdump] Written 142417920 bytes (34770 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 770ms
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/datadisks/disk1/work/B6590997/p
/datadisks/disk1/work/B6590997/w/A91F0981/e/GC/API/Frozen/Frozen/Frozen.sh
Expected: True
Actual:   False

### Reproduction Steps

Failing in the coreclr outerloop
GC/API/Frozen/Frozen/Frozen.sh

### Expected behavior

GC/API/Frozen/Frozen/Frozen.sh

### Actual behavior

GC/API/Frozen/Frozen/Frozen.sh

### Regression?

Yes
https://github.com/dotnet/runtime/pull/67389

**Comment by jeffschwMSFT** [comment]
cc @mangod9

**Comment by mangod9** [comment]
fixed by https://github.com/dotnet/runtime/pull/73761
