### ISSUE TITLE
Microsoft.Extensions.DependencyInjection internal constructor

### ISSUE THREAD

**Issue by ScottKane** [dotnet/runtime#73652]
I have the following classes in `ProjectA`:

```c#
public class ApplicationBuilder
{
    private readonly IServiceCollection _services;
    
    internal ApplicationBuilder() => _services = new ServiceCollection();

    public ApplicationBuilder ConfigureServices(Action<IServiceCollection> services)
    {
        _services.AddSingleton<ILoggerFactory, LoggerFactory>();
        _services.AddSingleton(typeof(ILogger<>), typeof(Logger<>));
        _services
            .AddLogging(builder => builder
                .AddConsole()
                .SetMinimumLevel(LogLevel.Information));
        
        _services.AddSingleton<Application>();

        services.Invoke(_services);
        
        return this;
    }
    
    public Application Build()
    {
        var provider = _services.BuildServiceProvider();
        
        return provider.GetRequiredService<Application>();
    }
}

[assembly: InternalsVisibleTo("Microsoft.Extensions.DependencyInjection")]

public class Application
{
    private readonly ILogger<Application> _logger;
    internal Application(ILogger<Application> logger) => _logger = logger;
    
    public static ApplicationBuilder Create() => new();

    public void Run()
    {
        _logger.LogInformation("Application started");
        while (true)
        {
            
        }
    }
}
```

And the following in `ProjectB`:

```c#
Application.Create()
    .ConfigureServices(services =>
    {
        
    })
    .Build()
    .Run();
```

I had hoped using `[assembly: InternalsVisibleTo("Microsoft.Extensions.DependencyInjection")]` would give access to the constructor but as it's not explicitly public it is ignored.

Is there any way to override the constructor resolution for `Microsoft.Extensions.DependencyInjection` so that I can use internal constructors? I could use `_services.AddSingleton(new Application(provider.GetRequiredService<ILogger<Application>>()));` but I'm sure this is an anti pattern and will just be a pain as the dependencies for `Application` grow.

**Comment by ScottKane** [comment]
I'm getting around this using reflection for now:

```c#
var constructor = typeof(Application).GetConstructors(BindingFlags.NonPublic | BindingFlags.Instance).First();
_services.AddSingleton((Application)constructor.Invoke(constructor.GetParameters().Select(p => provider.GetRequiredService(p.ParameterType)).ToArray()));
```

But I feel like there must be a nicer way to achieve this.

**Comment by eerhardt** [comment]
https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection#constructor-injection-behavior

> When services are resolved by IServiceProvider or ActivatorUtilities, constructor injection requires a public constructor.

The nicer way to achieve this is to make the constructor public. Beyond that you can use the other overloads to AddSingleton - which accept either `object implementationInstance` or `Func<IServiceProvider, object> implementationFactory` so you can create the object yourself. Microsoft.Extensions.DependencyInjection doesn't use private reflection to create the objects.

**Comment by ScottKane** [comment]
@eerhardt You shouldn't be just closing the issue without customer response. You haven't solved the underlying issue here. The constructor is specifically internal for a reason (it gets services from DI that the user can't provide) hence using a builder to do this properly. The point is that DI should allow for registering internals that are visible to it so that use cases like this where the consumer shouldn't have knowledge about construction can still work.

**Comment by eerhardt** [comment]
> You haven't solved the underlying issue here.

The "underlying issue" is not an issue, but it is "by design". Microsoft.Extensions.DependencyInjection doesn't use private reflection to create the objects. We have no plans on changing this design.

> The point is that DI should allow for registering internals that are visible to it so that use cases like this where the consumer shouldn't have knowledge about construction can still work.

A simple way to solve that would be to add a static method to the `Application` class:

```C#
public class Application
{
    internal Application(ILogger<Application> logger) => _logger = logger;

    public static void Register(IServiceCollection services)
    {
        services.AddSingleton(sp => new Application(sp.GetService<ILogger<Application>>()));
    }
```

The consumer still needs no knowledge about construction and the constructor can remain internal. The consumer just delegates to the `Application.Register(services)` method to register it.

**Comment by ScottKane** [comment]
I am well aware you are able to do that, but as the dependency graph for `Application` grows, you are forced into manually modifying the extension method to support each new dependency, if DI were to treat internals it has visibility of as public and act on them in the same way it does for everything else, you would be able to register `Application` knowing as long as it's dependencies are also registered, the service will be resolved.

At least doing this with reflection provides a similar experience to `services.AddSingleton<Application>()`, where you could inject something else to `Application` without the concern of modifying some additional extension method.

**Comment by eerhardt** [comment]
> as the dependency graph for Application grows

The nice thing of the above is that when you modify the `Application` constructor to add more dependencies you will immediately get a build error in the Register method - since these two are in the same class. Yes it is one more line that needs editing, but it is basically automatic.

**Comment by ScottKane** [comment]
I think it would be good if when this API moves to source generators (which I'm guessing it eventually will), allowing internals with explicit visibility to DI could be considered (would be extremely easy from roslyn).
