### ISSUE TITLE
area-ILTools-coreclr  ilasm.exe failing - Failed to add user string using DefineUserString, hr=0x80131198, data: 'presence'

### ISSUE THREAD

**Issue by dotfurther** [dotnet/runtime#73656]
### Description
area-ILTools-coreclr

EDIT:  This may be a total combined number of strings issue across all assembly HashSet strings (all using object initializers).

For .NET 6 Windows x64:
Is there a limit in ilasm source code for the number of strings that can be in a HashSet<string> object initializer?
I use HashSet object initializers that have 10's of thousands of strings, and I think I recently just bumped into some kind of
internal ilsam limit because now it is failing after adding more strings to HashSet initializer (ilasm was working for months until 
just recently).

The ilasm.exe error I get is in the subject line.

Note:  I am not using ILASM directly, my use case (obfuscation) was failing with Preemptive's Dotfuscator and so I tested the IL temp file directly against ILASM and received the error in the subject line.

Example:
static HashSet<string> Numbers = new HashSet<string>()
{
    "nineteen" ,
    "twenty-three" 
    "forty-two" 
...
many many more strings
};

### Reproduction Steps

static HashSet<string> Numbers = new HashSet<string>()
{
    "1",
    "2" 
    "3" 
...
try with 300k unique strings
};

### Expected behavior

ILASM.exe to write assembly without failing with error:
Failed to add user string using DefineUserString, hr=0x80131198, data: 'presence'

### Actual behavior

ilasm.exe failing, error:
 Failed to add user string using DefineUserString, hr=0x80131198, data: 'presence'

**Comment by jkotas** [comment]
>  This may be a total combined number of strings issue across all assembly HashSet strings (all using object initializers

Yes, the total combined size of strings has to be less than 256MB. It is a limitation of the .NET metadata format. C# is going to hit similar error if you try to produce strings that have combined size of more than 256MB.

**Comment by dotfurther** [comment]
> > This may be a total combined number of strings issue across all assembly HashSet strings (all using object initializers
> 
> Yes, the total combined size of strings has to be less than 256MB. It is a limitation of the .NET metadata format. C# is going to hit similar error if you try to produce strings that have combined size of more than 256MB.

Thanks.

There is no issue building or running the un-obfuscated assembly. Dotfuscator string encryption must be increasing the total size of the string considerably.

The 256 MB metadata limit likely was set in the x32 days. I hope the .net team increases it soon.

**Comment by TIHan** [comment]
Closing this as it is a current limitation for the .NET metadata format.

**Comment by jkotas** [comment]
```
static HashSet Numbers = new HashSet()
{
"1",
"2"
"3"
...
try with 300k unique strings
};
```

Note that large static initialization patterns like this have very bad performance characteristics. They generate a giant method that takes forever to JIT-compile and the JIT gives up on any optimizations. It is better to initialize large hash tables like this from a file or by slicing a large constant ReadOnlySpan.

> The 256 MB metadata limit likely was set in the x32 days. I hope the .net team increases it soon.

I do not expect that we will lift this limit anytime soon.

**Comment by dotfurther** [comment]
> ```
> static HashSet Numbers = new HashSet()
> {
> "1",
> "2"
> "3"
> ...
> try with 300k unique strings
> };
> ```
> 
> Note that large static initialization patterns like this have very bad performance characteristics. They generate a giant method that takes forever to JIT-compile and the JIT gives up on any optimizations. It is better to initialize large hash tables like this from a file or by slicing a large constant ReadOnlySpan.
> 
> > The 256 MB metadata limit likely was set in the x32 days. I hope the .net team increases it soon.
> 
> I do not expect that we will lift this limit anytime soon.

Thanks. When I first read your original comment I read it as a PE limit (no sleep) but our merged PE is only 50MB.  The temporary IL file that Dotfuscator creates before running ILASM on it to create the final PE for this merged assembly is greater than 300 MB.  So the 256 MB metadata limit you are talking about is in the IL metadata section, correct?

My work-around will be breaking the master merged assembly into 2 or more assemblies.  
Thanks again, Jan.

**Comment by jkotas** [comment]
> So the 256 MB metadata limit you are talking about is in the IL metadata section, correct?

This limit is very fundamental to the current metadata encoding. Lifting it would mean introducing new incompatible metadata encoding, introducing a number of new managed APIs that work with this encoding, changing the runtime and compilers to read and write files in this encoding, etc.
