### ISSUE TITLE
SudoInstall-Package Microsoft.Extensions.Primitives -Version 6.0.0

### ISSUE THREAD

**Issue by tunsira** [dotnet/runtime#73660]

**Comment by huoyaoyuan** [comment]
`Install-Package` is a command for Package Manager console in Visual Studio. You wouldn't have a change to use it with `sudo`.

For command to use in normal shell, you can use `dotnet add package Microsoft.Extensions.Primitives --version 6.0.0`. See also the `.NET CLI` tab on [nuget site](https://www.nuget.org/packages/Microsoft.Extensions.Primitives/6.0.0).
