### ISSUE TITLE
Improve experience when using PublishAot with unsupported RID

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#73678]
https://github.com/dotnet/runtime/issues/61231#issuecomment-1210291307

E.g. win-x86, win-arm, linux-arm, osx-x64, all work with .NET, but we current don't support them in NativeAOT. We should make it more obvious that that's the problem.

Also, we should add linux-musl-arm64 to the list of supported RIDs.

Cc @LakshanF

**Comment by kamyker** [comment]
Using net7.0-rc1 I'm unable to build for unsupported RIDs. With PublishAot=true (and with or without package reference) it says runtime is missing. With no PublishAot and package reference it doesn't compile native code at all. I've heard it works in .net 8 but that's not available using Azure Pipelines that only support main releases https://github.com/dotnet/core/blob/main/release-notes/releases-index.json

**Comment by jkotas** [comment]
> Using net7.0-rc1 I'm unable to build for unsupported RIDs

This should be fixed in rc2 by https://github.com/dotnet/installer/pull/14464

**Comment by kamyker** [comment]
> > Using net7.0-rc1 I'm unable to build for unsupported RIDs
> 
> This should be fixed in rc2 by [dotnet/installer#14464](https://github.com/dotnet/installer/pull/14464)

Ok thanks, would be nice to add all RIDs in docs https://docs.microsoft.com/en-us/dotnet/core/deploying/native-aot/ and https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/compiling.md.

Supported/unsupported wording is a bit confusing, I'd call RIDs that can be compiled but aren't supported 'experimental'.

**Comment by kamyker** [comment]
> > Using net7.0-rc1 I'm unable to build for unsupported RIDs
> 
> This should be fixed in rc2 by [dotnet/installer#14464](https://github.com/dotnet/installer/pull/14464)

In rc2 osx-64x started working but osx-arm64 doesn't. Is it not possible to build in net7?

I've tried to reference dotnet8 nuget package but that seems impossible as PublishAot always removes it:
`<PackageReference Include="Microsoft.DotNet.ILCompiler; runtime.osx-arm64.Microsoft.DotNet.ILCompiler" Version="8.0.0-alpha.1.22461.3" />`
`/Users/runner/.nuget/packages/microsoft.dotnet.ilcompiler/8.0.0-alpha.1.22461.3/build/Microsoft.DotNet.ILCompiler.SingleEntry.targets(49,5): warning : Delete explicit 'Microsoft.DotNet.ILCompiler' package reference in your project file. Explicit 'Microsoft.DotNet.ILCompiler' package reference can run into version errors.`

Without PublishAot it doesn't compile native code.

**Comment by kamyker** [comment]
> > Using net7.0-rc1 I'm unable to build for unsupported RIDs
> 
> This should be fixed in rc2 by [dotnet/installer#14464](https://github.com/dotnet/installer/pull/14464)

In rc2 osx-64x started working but osx-arm64 doesn't. Is it not possible to build in net7? @jkotas 

I've tried to reference dotnet8 nuget package but that seems impossible as PublishAot always removes it:
`<PackageReference Include="Microsoft.DotNet.ILCompiler; runtime.osx-arm64.Microsoft.DotNet.ILCompiler" Version="8.0.0-alpha.1.22461.3" />`

Gets removed during compilation (and replaced with rc2 ilcompiler):
`/Users/runner/.nuget/packages/microsoft.dotnet.ilcompiler/8.0.0-alpha.1.22461.3/build/Microsoft.DotNet.ILCompiler.SingleEntry.targets(49,5): warning : Delete explicit 'Microsoft.DotNet.ILCompiler' package reference in your project file. Explicit 'Microsoft.DotNet.ILCompiler' package reference can run into version errors.`

Without PublishAot it doesn't compile native code.

**Comment by jkotas** [comment]
> I've tried to reference dotnet8 nuget package but that seems impossible as PublishAot always removes it:

@agocke @LakshanF Is this going to be fixed by https://github.com/dotnet/sdk/pull/28495 ?

**Comment by agocke** [comment]
There are a couple questions here, let me pull some of them apart.

1. How can I publish for AOT on OSX in .NET 7?
2. How can I use the latest AOT bits?
3. What about the NuGet packages?

For (1) the answer is: no, you cannot publish using NativeAOT in .NET 7. That's not a supported scenario.

But, we will support OSX in .NET 8. To use .NET 8, you'll need to download a .NET 8 SDK. At the moment, we have not publicly shipped a .NET 8 preview. When we do, that will be the recommended path. If you want to live on the bleeding edge, you can download nightlies from https://github.com/dotnet/installer#table.

Lastly, how do the Microsoft.NET.ILCompiler packages relate? The intent is that they should provide a similar experience to the SDK, but give you more fine-grained version control, in case there's a specific bug. The packages aren't meant to be a supported experience and aren't meant to substitute for the SDK. In particular, using packages mismatched with the target framework they were built for would not be supported. So, using .NET 8 packages with the .NET 7 SDK to target net7.0 would not be supported.

At the moment it appears that the packages have some strange behavior when interacting with the SDK. I'm not sure of all the issues there, but we'll have to work through them.

Lastly, the change in https://github.com/dotnet/sdk/pull/28495 is intended to improve the experience when building and not actually publishing with AOT. It wouldn't help with using AOT on unsupported platforms.

**Comment by kamyker** [comment]
> (1) the answer is: no, you cannot publish using NativeAOT in .NET 7. That's not a supported scenario.
As I said I can publish osx-64x but not osx-arm64. This comment also says something else: https://github.com/dotnet/runtime/pull/75264#issuecomment-1243456033
> It missed the 7.0 deadline by a lot. However, it is possible to consume the ILCompiler package from NuGet so I think the realistic goal is to make it possible to use that with .NET 7 SDK.

Anyway I've tried dotnet8 sdk and got error:
> The PrivateSdkAssemblies ItemGroup is required for _ComputeAssembliesToCompileToNative
command:
> dotnet publish -output $(Build.ArtifactStagingDirectory)/arm --configuration $(buildConfiguration) -r osx-arm64 /p:NativeLib=Shared /p:SelfContained=true
Using Azure Pipelines microsoft host, newest mac 12 that's x64. Is it possible to crosscompile arm64?

**Comment by kamyker** [comment]
Oh wow, removed 
> <PackageReference Include="Microsoft.DotNet.ILCompiler; runtime.osx-x64.Microsoft.DotNet.ILCompiler" Version="8.0.0-alpha.1.22461.3" />
Error is gone and building arm64 works fine with NET 8. 

https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/compiling.md should be updated.

**Comment by AhmedZero** [comment]
Any news about win-x86?

**Comment by jkotas** [comment]
> Any news about win-x86?

We would accept community contributions towards enabling it, but we don't have current x86 plans for NativeAOT. https://github.com/dotnet/runtimelab/issues/1471 has more discussion about it.

**Comment by kamyker** [comment]
> Oh wow, removed
> 
> ```
> <PackageReference Include="Microsoft.DotNet.ILCompiler; runtime.osx-x64.Microsoft.DotNet.ILCompiler" Version="8.0.0-alpha.1.22461.3" />
> ```
> 
> Error is gone and building arm64 works fine with NET 8.
> 
> https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/compiling.md should be updated.

Fails again,
Version that was working before: 
.NET SDK 8.0.100-alpha.1.22514.14 (x64)
Doesn't work:
.NET SDK 8.0.100-alpha.1.23060.5 (x64)

Error:
```
.nuget/packages/microsoft.dotnet.ilcompiler/8.0.0-alpha.1.23058.2/build/Microsoft.NETCore.Native.Publish.targets(74,5): error : The PrivateSdkAssemblies ItemGroup is required for _ComputeAssembliesToCompileToNative
```

**Comment by lemonmojo** [comment]
I'm also running into the same error using .NET 8 Preview 1.

While cross-compiling to x64 from an M1 machine works fine for me, I can't get the reverse (cross-compiling to ARM64 from an Intel machine) to work.

I'm not using any packages in this project. In fact, the issue is very easy to reproduce:
```
dotnet new classlib -n "AOTTest"
cd AOTTest
dotnet publish -p "PublishAot=true" -r osx-x64
dotnet publish -p "PublishAot=true" -r osx-arm64
```

Publishing using `dotnet publish -r osx-x64` and `dotnet publish -r osx-arm64` works fine from an M1 machine.
While on an Intel machine only the x64 build works and the ARM64 one fails with the error message:

```
/Users/redacted/.nuget/packages/microsoft.dotnet.ilcompiler/8.0.0-preview.1.23110.8/build/Microsoft.NETCore.Native.Publish.targets(74,5): error : The PrivateSdkAssemblies ItemGroup is required for _ComputeAssembliesToCompileToNative [/Path/to/Project.csproj].
```

So here's what works and what doesn't work in my testing:
ARM64 -> x64: OK
ARM64 -> ARM64: OK
x64 -> x64: OK
x64 -> ARM64: Error

**Comment by kant2002** [comment]
Adding `<PackageReference Include="runtime.osx-arm64.Microsoft.DotNet.ILCompiler" Version="8.0.0-preview.1.23110.8" />` as workaround solve issue which @lemonmojo has. Not sure if this is intended experience.

**Comment by lemonmojo** [comment]
@kant2002 Many thx for debugging this with me.
I can only add that I think it's unlikely that this is intended experience as the other way around (cross-compiling from ARM64 to x64) does not require the workaround.

**Comment by kant2002** [comment]
It's quite possible that other combinations was started from different setup where their respective packages was already downloaded in previous not working attempts, and thus it appears as it was working.

**Comment by lemonmojo** [comment]
@kant2002 You're right, I haven't considered that.

**Comment by lemonmojo** [comment]
@kant2002 I guess taking that into account it would make sense to, at least for the time being add package references to the ILCompiler package for all architectures that are used in the project.

**Comment by jkotas** [comment]
> While cross-compiling to x64 from an M1 machine works fine for me, I can't get the reverse (cross-compiling to ARM64 from an Intel machine) to work.

This issue is about unsupported RIDs. Both osx-x64 and osx-arm64 are supported RIDs in .NET 8 Preview 1, so we would track it as a different issues. I have opened https://github.com/dotnet/runtime/issues/82542

**Comment by kant2002** [comment]
Can we also add `browser-wasm` to https://github.com/dotnet/runtime/blob/b4c1a099be69fce0e4354453c2181b06144400fc/eng/targetingpacks.targets#L61 ?
That would make consuming NativeAOT-LLVM package slightly more natural. For context: https://github.com/dotnet/runtimelab/pull/2203

**Comment by MichalStrehovsky** [comment]
Yes, I think we can close.
