### ISSUE TITLE
Repoint URL's to docs from corefx to runtime repo

### ISSUE THREAD

**Issue by N0D4N** [dotnet/runtime#73682]
Some comments, on classes primarily related to EventSource/DiagnosticSource, have urls in them that point to docs located in archived corefx repo, perhaps they should be repointed to docs that are at runtime repo? Or is it intended to have docs point to corefx repo?

An alternative would be to extract such docs to separate docs pages at dotnet/docs repo for example rather than having them at corefx/runtime repo.

Here are urls that i found:
https://github.com/dotnet/runtime/blob/6da2046387798432f471036a94b3ea1352bb844b/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L211
https://github.com/dotnet/runtime/blob/6da2046387798432f471036a94b3ea1352bb844b/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L249
https://github.com/dotnet/runtime/blob/6da2046387798432f471036a94b3ea1352bb844b/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L282
https://github.com/dotnet/runtime/blob/6da2046387798432f471036a94b3ea1352bb844b/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L1760
https://github.com/dotnet/runtime/blob/6da2046387798432f471036a94b3ea1352bb844b/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticListener.cs#L26
https://github.com/dotnet/runtime/blob/6da2046387798432f471036a94b3ea1352bb844b/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSource.cs#L14
https://github.com/dotnet/runtime/blob/6da2046387798432f471036a94b3ea1352bb844b/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventCounter.cs#L13
https://github.com/dotnet/runtime/blob/6da2046387798432f471036a94b3ea1352bb844b/src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/Ecma335/MetadataBuilder.Heaps.cs#L301
https://github.com/dotnet/runtime/blob/6da2046387798432f471036a94b3ea1352bb844b/src/mono/mono/metadata/debug-mono-ppdb.c#L783

**Comment by danmoseley** [comment]
Thanks for pointing this out. Would you be interested in offering a PR to point them to runtime repo?

**Comment by N0D4N** [comment]
Yeah, sure. I assume I should just change XMLdocs or are there other places that require changes too?

**Comment by danmoseley** [comment]
I assumed you could just Grep the repo for coreclr/corefx links? And fix some or all as you prefer. I don't think there is any reason for such links. All code and issues were migrated here.

**Comment by N0D4N** [comment]
Sure, got it.
