### ISSUE TITLE
Bug in the .NET Blog https://devblogs.microsoft.com/dotnet/

### ISSUE THREAD

**Issue by HSchwichtenberg** [dotnet/runtime#73690]
Repo:
1. Go to https://devblogs.microsoft.com/dotnet/
It will display the blog entries of August 2022 --> Image 1
2. Click "2" or ">"
It will display the blog entries of June 2022 --> Image 2
All blog entries of July 2022 are missing in that list, although there are 11 of them: https://devblogs.microsoft.com/dotnet/2022/07/

Testet with current versions of Edge, Chrome and Firefox

Image 1:
![image](https://user-images.githubusercontent.com/3673169/183907103-e4bfd5d5-6b7b-43e5-acae-bd682ea0975d.png)

Image 2:
![image](https://user-images.githubusercontent.com/3673169/183907116-13abd5ce-af8c-4602-a760-ab7cf1e41f4e.png)

**Comment by danmoseley** [comment]
@JeremyLikness @JonDouglas

**Comment by jeffhandley** [comment]
Thanks for reporting this, @HSchwichtenberg. I've logged a bug in the internal issue tracker for our blog site capturing the helpful details you provided.

**Comment by HSchwichtenberg** [comment]
My pleasure!
