### ISSUE TITLE
Assert: slot_table[slot_index] == nullptr

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#73692]
Affected tests:
- JIT\\Regression\\JitBlue\\GitHub_27924\\GitHub_27924\\**GitHub_27924.cmd**
- GC/Scenarios/FinalizeTimeout/FinalizeTimeout/**FinalizeTimeout.sh**

Recent regression (started on 8/9):
- 8/11 status:
    - **GitHub_27924.cmd** - 5x failures in [last 120 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E120+definition%3Aruntime+name%3A%22jit%5C%5Cregression%5C%5Cjitblue%5C%5Cgithub_27924%5C%5Cgithub_27924%5C%5Cgithub_27924.cmd%22) (note the oldest 2 asserts are different on the same PR - that was specific to the PR)
    - **FinalizeTimeout.sh** - 10x failures in [last 120 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E120+definition%3Aruntime+name%3A%22gc%2Fscenarios%2Ffinalizetimeout%2Ffinalizetimeout%2Ffinalizetimeout.sh%22) (note the oldest 2 asserts are different on the same PR - that was specific to the PR) -- failures on 2x OSX.1200.**ARM64**.Open and 8x OSX.1200.**Amd64**.Open

Day | Run | Details
-- | -- | --
8/10 | Rolling run [1933914](https://runfo.azurewebsites.net/view/build/?number=1933914) | GitHub_27924.cmd - coreclr **windows arm64** Checked no_tiered_compilation @ Windows.10.Arm64v8.Open
8/9 | PR build [1933770](https://runfo.azurewebsites.net/view/build/?number=1933770) - PR #73605 | GitHub_27924.cmd - coreclr **windows x86** Checked no_tiered_compilation @ Windows.10.Amd64.Open
8/9 | PR build [1932986](https://runfo.azurewebsites.net/view/build/?number=1932986) - PR #73661 | FinalizeTimeout.sh - coreclr **OSX arm64** Checked no_tiered_compilation @ OSX.1200.ARM64.Open
8/9 | PR build [1933526](https://runfo.azurewebsites.net/view/build/?number=1933526) - PR #73670 | GitHub_27924.cmd- coreclr **windows arm64** Checked no_tiered_compilation @ Windows.10.Arm64v8.Open
~7/21~ | ~2x PR build [1895796](https://runfo.azurewebsites.net/view/build/?number=1895796) - PR #72229~ | GitHub_27924.cmd - Unrelated assert `committed_by_oh[oh] == committed`
```
    JIT\Regression\JitBlue\GitHub_27924\GitHub_27924\GitHub_27924.cmd [FAIL]
      
      Assert failure(PID 10172 [0x000027bc], Thread: 6156 [0x180c]): slot_table[slot_index] == nullptr
      
      CORECLR! `dynamic atexit destructor for 'WKS::gc_heap::mark_queue'' + 0x3C (0x00007ff8`6189f42c)
      CORECLR! <lambda_d121dba8a4adeaf3a9819e48611155df>::operator() + 0x13C (0x00007ff8`617b20ec)
      CORECLR! _crt_seh_guarded_call<int>::operator()<<lambda_6a47f4c8fd0152770a780fc1d70204eb>,<lambda_d121dba8a4adeaf3a9819e48611155df> &,<lambda_6aaa2265f5b6a89667e7d7630012e97a> > + 0x34 (0x00007ff8`617b1804)
      CORECLR! _acrt_lock_and_call<<lambda_d121dba8a4adeaf3a9819e48611155df> > + 0x50 (0x00007ff8`617b1938)
      CORECLR! execute_onexit_table + 0x38 (0x00007ff8`617b2300)
      CORECLR! <lambda_6e4b09c48022b2350581041d5f6b0c4c>::operator() + 0xC0 (0x00007ff8`617af668)
      CORECLR! _crt_seh_guarded_call<void>::operator()<<lambda_d80eeec6fff315bfe5c115232f3240e3>,<lambda_6e4b09c48022b2350581041d5f6b0c4c> &,<lambda_2358e3775559c9db80273638284d5e45> > + 0x2C (0x00007ff8`617af33c)
      CORECLR! _acrt_lock_and_call<<lambda_6e4b09c48022b2350581041d5f6b0c4c> > + 0x50 (0x00007ff8`617af3a0)
      CORECLR! common_exit + 0x80 (0x00007ff8`617af8d0)
      CORECLR! cexit + 0x1C (0x00007ff8`617afc0c)
          File: D:\a\_work\1\s\src\coreclr\gc\gc.cpp Line: 23968
          Image: D:\h\w\ADC409C9\p\corerun.exe
```

Related to #73668

**Comment by karelz** [comment]
Affects CI (more than 1x failure per day), we should disable the tests ASAP.

**Comment by jakobbotsch** [comment]
Dup of #73679 and #73668?

**Comment by JulieLeeMSFT** [comment]
@kunalspathak PTAL with high priority.

**Comment by kunalspathak** [comment]
@JulieLeeMSFT  - This is not a codegen issue but assert hit in GC code. https://github.com/dotnet/runtime/issues/73679 is already assigned to @PeterSolMS.

**Comment by JulieLeeMSFT** [comment]
Cc @mangod9 and @PeterSolMS for the GC issue.

**Comment by karelz** [comment]
I added 1 more affected test -- that one fails on OSX only.

**Comment by mangod9** [comment]
Fixed by https://github.com/dotnet/runtime/pull/73761
