### ISSUE TITLE
NativeAOT test ` ThreadLocalStatics.TLSTesting.ThreadLocalStatics_Test` failing on OSX/x64

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#73698]
Failing on unrelated https://github.com/dotnet/runtime/pull/67272/ . [Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1932360&view=logs&jobId=2de479a8-eae7-5324-c49d-bebaef329288&j=2de479a8-eae7-5324-c49d-bebaef329288&t=bb577e75-8247-55f1-4164-04f3b0f2d1eb):

```
Running Test: ThreadLocalStatics.TLSTesting.ThreadLocalStatics_Test
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
```

**Comment by MichalStrehovsky** [comment]
Dup of #73299.
