### ISSUE TITLE
System.Net.WebProxy Bypass regex list reconstructed for every call to IsBypassed

### ISSUE THREAD

**Issue by onehourlate** [dotnet/runtime#73703]
### Description

System.Net.WebProxy takes a list of strings for Uris that should bypass the proxy.
This list of strings is compiled into a list of Regex by the method [UpdateRegexList](https://source.dot.net/System.Net.WebProxy/System/Net/WebProxy.cs.html#850d23113aacd0b8)

This method is called in the constructor and in the [BypassList](https://referencesource.microsoft.com/system/R/eb0d74cc9c1b1691.html) property setter.
This is normal.

However, this method is also called in [IsMatchInBypassList](https://source.dot.net/System.Net.WebProxy/R/25a518410abb8bfd.html), which is called by [IsBypassed](https://source.dot.net/System.Net.WebProxy/R/282c1aa0937eccad.html)
This feels wrong. I don't see why it needs to systematically refresh the regex list in this call.
It re-allocates the array and all the regex, for no reason (as far as I can see anyway).

### Regression?

This behavior seems to be copy-pasted from the .Net Framework code, which is also wrong.
https://referencesource.microsoft.com/#system/net/system/Net/webproxy.cs

### Analysis

The following code shows a significant difference between the proxy1 et proxy2 execution time
(typically ~230ms vs ~2100ms)
Since the call to IsBypassed returns true for the first regex, the length of the Bypasslist should not matter.
```
Uri uri = new Uri("https://a.com/");

System.Diagnostics.Stopwatch sw = new System.Diagnostics.Stopwatch();
bool r1 = true;
System.Net.WebProxy proxy1 = new System.Net.WebProxy("http://localhost:9999", true, new string[] { "a" });
sw.Restart();
for (int i = 0; i < 100000; i++) {
    r1 &= proxy1.IsBypassed(uri);
}
sw.Stop();
Console.WriteLine($"Proxy1 : {sw.ElapsedMilliseconds}ms ({r1})");

bool r2 = true;
System.Net.WebProxy proxy2 = new System.Net.WebProxy("http://localhost:9999", true, new string[] { "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z" });
sw.Restart();
for (int i = 0; i < 100000; i++) {
    r2 &= proxy2.IsBypassed(uri);

}
sw.Stop();
Console.WriteLine($"Proxy2 : {sw.ElapsedMilliseconds}ms ({r2})");
```

**Comment by MihaZupan** [comment]
I also don't see any reason to rebuild the list in this case. Doing so looks like just a waste of compute.

Should be a simple change - marking as up for grabs. @onehourlate would you be interested in contributing a fix for this?

**Comment by campersau** [comment]
It looks like the underlying `_bypassList` is publicly exposed as `BypassArrayList` which means that it could be modified from the outside:

https://github.com/dotnet/runtime/blob/de32c4466489090fdd41574d1be2945fd03ab7f2/src/libraries/System.Net.WebProxy/src/System/Net/WebProxy.cs#L85

**Comment by MihaZupan** [comment]
You're right... yay legacy APIs :)

We can still do a lot better here than creating all Regex objects on every request though.
At a minimum have a flag checking whether that property was ever accessed and skip `UpdateRegexList` on the hot path.

**Comment by onehourlate** [comment]
Or even subclass ArrayList for the BypassArrayList  with something that keeps a dirty flag.
Since all methods of an ArrayList that modify the list are virtual, that's easily done.
(what's a bit frustrating is that the ArrayList does that for us already, via the version, but it's private)

And then check the dirty flag to see if we need to rebuild the regex list.

```
class DirtyTrackingArrayList : System.Collections.ArrayList {

    public bool IsDirty { get; private set; }

    public bool CheckDirty() {
        var dirty = IsDirty;
        IsDirty = false;
        return dirty;
    }
    public override object? this[int index] {
        get {
            return base[index];
        }
        set {
            IsDirty = true;
            base[index] = value;
        }
    }


    public override int Add(object? value) {
        IsDirty = true;
        return base.Add(value);
    }

    public override void AddRange(ICollection c) {
        IsDirty = true;
        base.AddRange(c);
    }

    public override void Insert(int index, object? value) {
        IsDirty = true;
        base.Insert(index, value);
    }

    public override void InsertRange(int index, ICollection c) {
        IsDirty = true;
        base.InsertRange(index, c);
    }

    public override void SetRange(int index, ICollection c) {
        IsDirty = true;
        base.SetRange(index, c);
    }

    public override void Remove(object? obj) {
        IsDirty = true;
        base.Remove(obj);
    }

    public override void RemoveAt(int index) {
        IsDirty = true;
        base.RemoveAt(index);
    }

    public override void RemoveRange(int index, int count) {
        IsDirty = true;
        base.RemoveRange(index, count);
    }

    public override void Clear() {
        IsDirty = true;
        base.Clear();
    }

    public override void Sort() {
        IsDirty = true;
        base.Sort();
    }

    public override void Sort(IComparer? comparer) {
        IsDirty = true;
        base.Sort(comparer);
    }

    public override void Sort(int index, int count, IComparer? comparer) {
        IsDirty = true;
        base.Sort(index, count, comparer);
    }

    public override void Reverse() {
        IsDirty = true;
        base.Reverse();
    }

    public override void Reverse(int index, int count) {
        IsDirty = true;
        base.Reverse(index, count);
    }
}
```

**Comment by onehourlate** [comment]
Made a PR (https://github.com/dotnet/runtime/pull/73803), if it helps
(I just skimmed the guidelines, so sorry if I missed something ...)

Changes in the BypassArrayList are tracked by a DirtyFlag
RegexList is only updated if DirtyFlag is set
Added a few unit tests (one unit test uses reflexion : not sure if it's "allowed")
