### ISSUE TITLE
[API Proposal]: Add a property or method that can be used to check if there is an error in the process

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#73709]
### Background and motivation

Add a property or method that can be used to check if there is an error in the process
https://github.com/Mr0N/ExampleProcessStart/blob/master/ExampleProcessStart/Program.cs

### API Proposal

```csharp
static class Info
{ 
    public static void CheckException(this Process process)
    {
        if (string.IsNullOrEmpty(process.StandardError.ReadToEnd()))
            throw new Exception();
    }
}
```

### API Usage

```csharp
var info = new ProcessStartInfo()
{
    FileName = "cmd.exe",
    RedirectStandardError = true,
    RedirectStandardOutput = true,
    RedirectStandardInput = true
};
var process = Process.Start(info);
process.CheckException();

string text = process.StandardOutput.ReadToEnd();
```

**Comment by Mr0N** [comment]
![image](https://user-images.githubusercontent.com/61237140/183989658-2c9ff0a2-e0d8-43f1-a61f-e1894903838f.png)

**Comment by alexrp** [comment]
Standard error is used by many programs for non-fatal logging.

**Comment by danmoseley** [comment]
As @alexrp points out this is typically not what you would want - i can't think of a case I've seen where this code was written. Also we would not throw the base exception - what to throw? Finally, this code is trivial to write yourself: a new API adds cognitive load and the possibility of adding a bug without adding significant value.

**Comment by Mr0N** [comment]
> Standard error is used by many programs for non-fatal logging.

The code is just for example, it still needs to be edited

**Comment by Mr0N** [comment]
> As @alexrp points out this is typically not what you would want - i can't think of a case I've seen where this code was written. Also we would not throw the base exception - what to throw? Finally, this code is trivial to write yourself: a new API adds cognitive load and the possibility of adding a bug without adding significant value.

It is not very clear, to be honest, why two streams? Maybe it has something to do with technical capabilities, I don’t know
Can a user who has not read the documentation understand that the main stream will not output anything if there was an error?

**Comment by Clockwork-Muse** [comment]
> Can a user who has not read the documentation understand that the main stream will not output anything if there was an error?

Whether or not the process ends with a non-zero (or other error) exit code has no bearing on whether `StandardError` or `StandardOutput` have any content.  That's a decision made by the process that gets started.

**Comment by Mr0N** [comment]
> > Can a user who has not read the documentation understand that the main stream will not output anything if there was an error?
> 
> Whether or not the process ends with a non-zero (or other error) exit code has no bearing on whether `StandardError` or `StandardOutput` have any content. That's a decision made by the process that gets started.
Why not throw an error if the process did not return a 0 code if the property is enabled

**Comment by Mr0N** [comment]
> > Can a user who has not read the documentation understand that the main stream will not output anything if there was an error?
> 
> Whether or not the process ends with a non-zero (or other error) exit code has no bearing on whether `StandardError` or `StandardOutput` have any content. That's a decision made by the process that gets started.

Why not throw an error if the process did not return a 0 code if the property is enabled

**Comment by Mr0N** [comment]
and in the error message, there will be all (or part of) what was in the error stream,

**Comment by Clockwork-Muse** [comment]
> Why not throw an error if the process did not return a 0 code if the property is enabled

What constitutes an error depends on the process - 0 is only the usual convention, it's not actually required.

> and in the error message, there will be all (or part of) what was in the error stream,

You're also not guaranteed there will be anything in a specific stream on error, either.

**Comment by Mr0N** [comment]
> > Why not throw an error if the process did not return a 0 code if the property is enabled
> 
> What constitutes an error depends on the process - 0 is only the usual convention, it's not actually required.
> 
> > and in the error message, there will be all (or part of) what was in the error stream,
> 
> You're also not guaranteed there will be anything in a specific stream on error, either.

well, if so, then everything is now recorded in the main thread, what's the difference.

**Comment by Mr0N** [comment]
Well, as if it is already doing it now, why not add a property for convenience

**Comment by huoyaoyuan** [comment]
The definition of "error" looks extremely unclear.

When is it involved? A business logic failure, or the process fails to load some necessary library?
What about error level? Some errors are recoverable, some are fatal, and some are simply ignorable - some programs reports "nothing to do" as error.
Where to achieve the state of the process? Stderr is very often used for informational logging. Some programs use return code to represent meaningful information. GUI program may not use neither of them.

**Comment by huoyaoyuan** [comment]
> It is not very clear, to be honest, why two streams? Maybe it has something to do with technical capabilities, I don’t know
Can a user who has not read the documentation understand that the main stream will not output anything if there was an error?

For example: `curl.exe -v` uses stdout for HTTP payload, and stderr for verbose information about connection. Stderr is used as a "control" stream in fact.

**Comment by Mr0N** [comment]
> > It is not very clear, to be honest, why two streams? Maybe it has something to do with technical capabilities, I don’t know
> > Can a user who has not read the documentation understand that the main stream will not output anything if there was an error?
> 
> For example: `curl.exe -v` uses stdout for HTTP payload, and stderr for verbose information about connection. Stderr is used as a "control" stream in fact.

That is why I say that it is necessary to add a property, and not to change the default logic.

**Comment by Mr0N** [comment]
> 

An error is when information is recorded in the error stream.

**Comment by Mr0N** [comment]
> The definition of "error" looks extremely unclear.
> 
> When is it involved? A business logic failure, or the process fails to load some necessary library? What about error level? Some errors are recoverable, some are fatal, and some are simply ignorable - some programs reports "nothing to do" as error. Where to achieve the state of the process? Stderr is very often used for informational logging. Some programs use return code to represent meaningful information. GUI program may not use neither of them.

An error is when information is recorded in the error stream.

**Comment by Mr0N** [comment]
And what processes record errors there are their problems, and what these errors are, is the problem of those processes.

**Comment by alexrp** [comment]
> An error is when information is recorded in the error stream.

Your definition of error doesn't fit the convention that the vast majority of software uses. By your definition, informational or warning messages printed to stderr would be considered errors.

The *overwhelming* majority of programs use a non-zero exit code to indicate errors. If you have a program where that is not the case, you're going to have to handle that yourself. It's not appropriate for the framework to handle an extremely rare anti-pattern like that, especially when all the tools are there for you to do it very easily.

**Comment by Mr0N** [comment]
> > An error is when information is recorded in the error stream.
> 
> Your definition of error doesn't fit the convention that the vast majority of software uses. By your definition, informational or warning messages printed to stderr would be considered errors.
> 
> The _overwhelming_ majority of programs use a non-zero exit code to indicate errors. If you have a program where that is not the case, you're going to have to handle that yourself. It's not appropriate for the framework to handle an extremely rare anti-pattern like that, especially when all the tools are there for you to do it very easily.

![image](https://user-images.githubusercontent.com/61237140/184403284-b1addb2b-7bd0-4bfc-8040-dbc33e89b59b.png)

**Comment by Mr0N** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.standarderror?view=net-6.0

**Comment by Mr0N** [comment]
There is not a word about any log.

**Comment by Mr0N** [comment]
![image](https://user-images.githubusercontent.com/61237140/184404353-fae10c8a-4a32-4e93-9827-cdecd3ac6d5a.png)

**Comment by Mr0N** [comment]
Why an empty string and not null?

**Comment by Mr0N** [comment]
> > > An error is when information is recorded in the error stream.
> > 
> > 
> > Your definition of error doesn't fit the convention that the vast majority of software uses. By your definition, informational or warning messages printed to stderr would be considered errors.
> > The _overwhelming_ majority of programs use a non-zero exit code to indicate errors. If you have a program where that is not the case, you're going to have to handle that yourself. It's not appropriate for the framework to handle an extremely rare anti-pattern like that, especially when all the tools are there for you to do it very easily.
> 
> ![image](https://user-images.githubusercontent.com/61237140/184403284-b1addb2b-7bd0-4bfc-8040-dbc33e89b59b.png)

Why not name this stream something like StandardLogErrors

**Comment by MichalPetryka** [comment]
Cause standard error is the general convention (together with stderr), see [wikipedia](https://en.wikipedia.org/wiki/Standard_streams#Standard_error_(stderr)).

**Comment by Mr0N** [comment]
> Cause standard error is the general convention (together with stderr), see [wikipedia](https://en.wikipedia.org/wiki/Standard_streams#Standard_error_(stderr)).
> 
> > Standard error is another output stream typically used by programs to output [error messages](https://en.wikipedia.org/wiki/Error_message) or diagnostics. It is a stream independent of standard output and can be redirected separately.

Then you need to change the documentation.)

**Comment by Mr0N** [comment]
> 

dot net documentation

**Comment by danmoseley** [comment]
Feel free to offer a PR to clarify documentation if you think it would be helpful. I will close this for the reasons described by others above.

**Comment by Mr0N** [comment]
> Feel free to offer a PR to clarify documentation if you think it would be helpful. I will close this for the reasons described by others above.

In the documentation it says that only errors can be read from the stream, and it is for errors, I suggest adding to the documentation that you can read the log and errors from the stream, since you can read the log and errors from this stream, according to Wikipedia, if indeed from stream can read the log and not the errors, then you don't have the right documentation!

**Comment by Mr0N** [comment]
And the name of the method for the stream from which you can read errors and the log is very strange!

**Comment by Mr0N** [comment]
> And the name of the method for the stream from which you can read errors and the log is very strange!

properties

**Comment by Mr0N** [comment]
https://en.wiktionary.org/wiki/stderr there is also a thread from wikipedia where it is written that it is only for errors

**Comment by Mr0N** [comment]
https://docs.microsoft.com/en-us/cpp/c-runtime-library/stdin-stdout-stderr?view=msvc-170 there are also errors

**Comment by Mr0N** [comment]
https://www.howtogeek.com/435903/what-are-stdin-stdout-and-stderr-on-linux/

**Comment by Mr0N** [comment]
> https://docs.microsoft.com/en-us/cpp/c-runtime-library/stdin-stdout-stderr?view=msvc-170 there are also errors

On the official website of the Windows OS developer, it is written that this thread is only for errors!

**Comment by Mr0N** [comment]
https://linux.die.net/man/3/stderr Linux documentation also says that this thread is only for errors

**Comment by Mr0N** [comment]
https://developer.apple.com/documentation/foundation/filehandle/1411001-standarderror IOS

**Comment by Mr0N** [comment]
I trust the documentation more than some people from wikipedia
