### ISSUE TITLE
Undocumented 7.0 APIs in System.Data

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#73722]
@ajcvickers @davoudeshtehari @david-engel

Below is the list of APIs that were introduced in 7.0 and have not yet been fully documented.

Relevant dates:
-	The last day to merge API documentation directly into triple slash comments in dotnet/runtime is before the RC1 snap on August 15th.
-	After the RC1 snap, all pending documentation changes need to be merged directly into dotnet-api-docs, and the last day to do so is before the RC2 snap on September 13th.

#### Undocumented System.Data APIs as of Preview6

| Summary  | Parameters | TypeParameters | ReturnValue | API                                                                                                                                                                                        |
|----------|------------|----------------|-------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Missing  | NA         | NA             | NA          | [M:System.Data.Common.DbDataSource.#ctor](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Data.Common/DbDataSource.xml)                                                     |
| Missing  | NA         | NA             | NA          | [P:System.Data.Common.DbDataSource.ConnectionString](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Data.Common/DbDataSource.xml)                                          |
| Missing  | NA         | NA             | Missing     | [M:System.Data.Common.DbDataSource.CreateBatch](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Data.Common/DbDataSource.xml)                                               |
| Missing  | Missing    | NA             | Missing     | [M:System.Data.Common.DbDataSource.CreateCommand(System.String)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Data.Common/DbDataSource.xml)                              |
| Missing  | NA         | NA             | Missing     | [M:System.Data.Common.DbDataSource.CreateConnection](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Data.Common/DbDataSource.xml)                                          |
| Missing  | NA         | NA             | Missing     | [M:System.Data.Common.DbDataSource.CreateDbBatch](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Data.Common/DbDataSource.xml)                                             |
| Missing  | Missing    | NA             | Missing     | [M:System.Data.Common.DbDataSource.CreateDbCommand(System.String)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Data.Common/DbDataSource.xml)                            |
| Missing  | NA         | NA             | Missing     | [M:System.Data.Common.DbDataSource.CreateDbConnection](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Data.Common/DbDataSource.xml)                                        |
| Missing  | NA         | NA             | NA          | [T:System.Data.Common.DbDataSource](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Data.Common/DbDataSource.xml)                                                           |
| Missing  | Missing    | NA             | NA          | [M:System.Data.Common.DbDataSource.Dispose(System.Boolean)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Data.Common/DbDataSource.xml)                                   |
| Missing  | NA         | NA             | Missing     | [M:System.Data.Common.DbDataSource.DisposeAsyncCore](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Data.Common/DbDataSource.xml)                                          |
| Missing  | NA         | NA             | Missing     | [M:System.Data.Common.DbDataSource.OpenConnection](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Data.Common/DbDataSource.xml)                                            |
| Missing  | Missing    | NA             | Missing     | [M:System.Data.Common.DbDataSource.OpenConnectionAsync(System.Threading.CancellationToken)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Data.Common/DbDataSource.xml)   |
| Missing  | NA         | NA             | Missing     | [M:System.Data.Common.DbDataSource.OpenDbConnection](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Data.Common/DbDataSource.xml)                                          |
| Missing  | Missing    | NA             | Missing     | [M:System.Data.Common.DbDataSource.OpenDbConnectionAsync(System.Threading.CancellationToken)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Data.Common/DbDataSource.xml) |
| Missing  | Missing    | NA             | Missing     | [M:System.Data.Common.DbProviderFactory.CreateDataSource(System.String)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Data.Common/DbProviderFactory.xml)                 |

**Comment by roji** [comment]
Thanks, I'll be doing this before the 15th.

**Comment by roji** [comment]
Sorry, I ended up missing the deadline... https://github.com/dotnet/dotnet-api-docs/pull/8311 adds the directly to dotnet-api-docs.

What's the status on the source code being the source of truth for API docs? :wink:
