### ISSUE TITLE
Path.GetTempFileName() sometimes fails on WASM due to insufficient randomness

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#73721]
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1934834&view=logs&jobId=a07e672c-d717-5036-7657-9f851d8c04dc&j=a07e672c-d717-5036-7657-9f851d8c04dc&t=95c8462d-76dc-506a-26a4-fefb7abc2e07), seen on multiple PRs with no related changes. Which suggests that this is on `main`. Failures like:

```
[19:23:32] info: Starting:    System.CodeDom.Tests.dll
[19:23:39] fail: [FAIL] System.CodeDom.Compiler.Tests.CodeCompilerTests.FromSource_ValidSource_ReturnsExpected(source: "")
[19:23:39] info: System.IO.IOException : File exists
[19:23:39] info:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory)
[19:23:39] info:    at Interop.ThrowIOExceptionForLastError()
[19:23:39] info:    at System.IO.Directory.CreateTempSubdirectoryCore(String prefix)
[19:23:39] info:    at System.IO.Directory.CreateTempSubdirectory(String prefix)
[19:23:39] info:    at System.CodeDom.Compiler.TempFileCollection.GetTempDirectory()
[19:23:39] info:    at System.CodeDom.Compiler.TempFileCollection.EnsureTempNameCreated()
[19:23:39] info:    at System.CodeDom.Compiler.TempFileCollection.get_BasePath()
[19:23:39] info:    at System.CodeDom.Compiler.TempFileCollection.AddExtension(String fileExtension, Boolean keepFile)
[19:23:39] info:    at System.CodeDom.Compiler.TempFileCollection.AddExtension(String fileExtension)
[19:23:39] info:    at System.CodeDom.Compiler.CodeCompiler.FromSourceBatch(CompilerParameters options, String[] sources)
[19:23:39] info:    at System.CodeDom.Compiler.CodeCompiler.FromSource(CompilerParameters options, String source)
[19:23:39] info:    at System.CodeDom.Compiler.Tests.CodeCompilerTests.Compiler.FromSourceEntryPoint(CompilerParameters options, String source)
[19:23:39] info:    at System.CodeDom.Compiler.Tests.CodeCompilerTests.FromSource_ValidSource_ReturnsExpected(String source)
[19:23:39] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
```

.. and ..
```
[19:27:13] info: Starting:    System.Diagnostics.TextWriterTraceListener.Tests.dll
[19:27:14] fail: [FAIL] System.Diagnostics.TextWriterTraceListenerTests.CtorsDelimiterTests.TestConstructorWithFileNameAndName(testName: "")
[19:27:14] info: System.IO.IOException : File exists
[19:27:14] info:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory)
[19:27:14] info:    at Interop.CheckIo(Int64 result, String path, Boolean isDirectory)
[19:27:14] info:    at Interop.CheckIo(IntPtr result, String path, Boolean isDirectory)
[19:27:14] info:    at System.IO.Path.GetTempFileName()
[19:27:14] info:    at System.Diagnostics.TextWriterTraceListenerTests.CtorsDelimiterTests.TestConstructorWithFileNameAndName(String testName)
[19:27:14] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
[19:27:14] fail: [FAIL] System.Diagnostics.TextWriterTraceListenerTests.CtorsDelimiterTests.TestConstructorWithFileNameAndName(testName: "><&")
[19:27:14] info: System.IO.IOException : File exists
[19:27:14] info:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory)
[19:27:14] info:    at Interop.CheckIo(Int64 result, String path, Boolean isDirectory)
[19:27:14] info:    at Interop.CheckIo(IntPtr result, String path, Boolean isDirectory)
[19:27:14] info:    at System.IO.Path.GetTempFileName()
[19:27:14] info:    at System.Diagnostics.TextWriterTraceListenerTests.CtorsDelimiterTests.TestConstructorWithFileNameAndName(String testName)
[19:27:14] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
```

Just for people reading this in the future, the list of failed tests:
```
System.CodeDom.Compiler.Tests.CodeCompilerTests.FromDom_ValidCodeCompileUnit_ReturnsExpected(compilationUnit: CodeCompileUnit { AssemblyCustomAttributes = [], EndDirectives = [], Namespaces = [], ReferencedAssemblies = ["assembly1", "assembly2"], StartDirectives = [], ... })
System.CodeDom.Compiler.Tests.CodeCompilerTests.GetResponseFileCmdArgs_ValidCmdArgs_ReturnsExpected(cmdArgs: "")
System.CodeDom.Compiler.Tests.CodeCompilerTests.CompileAssemblyFromSourceBatch_ValidSources_ReturnsExpected(sources: [null])
System.CodeDom.Compiler.Tests.CodeCompilerTests.FromSource_ValidSource_ReturnsExpected(source: "")
System.CodeDom.Compiler.Tests.CodeCompilerTests.FromSourceBatch_ValidSources_ReturnsExpected(sources: [""])
System.CodeDom.Compiler.Tests.CodeCompilerTests.FromSource_ValidSource_ThrowsPlatformNotSupportedException(source: "")
System.CodeDom.Compiler.Tests.CodeCompilerTests.FromDom_ValidCodeCompileUnit_ThrowsPlatformNotSupportedException(compilationUnit: CodeCompileUnit { AssemblyCustomAttributes = [], EndDirectives = [], Namespaces = [], ReferencedAssemblies = ["referenced", "assembly1"], StartDirectives = [], ... })
System.CodeDom.Compiler.Tests.CodeCompilerTests.FromSourceBatch_ValidSources_ThrowsPlatformNotSupportedException(sources: [""])

System.Diagnostics.TextWriterTraceListenerTests.CtorsDelimiterTests.TestConstructorWithFileNameAndName(testName: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"...)
System.Diagnostics.TextWriterTraceListenerTests.CtorsDelimiterTests.TestConstructorWithFileNameAndName(testName: "><&")
System.Diagnostics.TextWriterTraceListenerTests.XmlWriterTraceListenerTests.SingleArgumentConstructorTest

 ystem.ServiceModel.Syndication.Tests.BasicScenarioTests.SyndicationFeed_Write_RSS_Atom
```

The full set can be seen with that build url. I think https://github.com/dotnet/runtime/pull/73408 broke these tests.

@eerhardt

**Comment by eerhardt** [comment]
I can't repro this locally. Is it possible the machine's TEMP directories are full?

**Comment by radical** [comment]
I will try to repro this too. Locally, and on CI.

**Comment by radical** [comment]
I tried debugging this on helix with https://github.com/dotnet/runtime/pull/73743 .

With the exception, I also printed the list of files, and directories in the temp path, before and after the `mkdtemp` call.
[Log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-73743-merge-acebb43380d445c183/WasmTestOnNodeJs-System.CodeDom.Tests/1/console.056de6e8.log?helixlogtype=result):

1.
```
[06:39:10] fail: [FAIL] System.CodeDom.Compiler.Tests.CodeCompilerTests.FromSource_ValidSource_ThrowsPlatformNotSupportedException(source: "")
[06:39:10] info: Assert.Throws() Failure
[06:39:10] info: Expected: typeof(System.PlatformNotSupportedException)
[06:39:10] info: Actual:   typeof(System.Exception): io: System.IO.IOException: File exists
[06:39:10] info:              at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory)
[06:39:10] info:              at Interop.ThrowIOExceptionForLastError()
[06:39:10] info:              at System.IO.Directory.CreateTempSubdirectoryCore(String prefix) (hresult: 20 $
[06:39:10] info:           debug: Tries to create /tmp/XXXXXX in /tmp/
[06:39:10] info:           before: files:
[06:39:10] info:           before: directories: /tmp/iBahFK,/tmp/OLKNPB,/tmp/GnFpaC
[06:39:10] info:           after: files:
[06:39:10] info:           after: directories: /tmp/iBahFK,/tmp/OLKNPB,/tmp/GnFpaC
```

- One thing to note here is that it was expecting a PNSE, so the native function shouldn't have been called at all?
- Another, is that it says `File exists`, but the `hresult` from the error is `20` (`  at System.IO.Directory.CreateTempSubdirectoryCore(String prefix) (hresult: 20`) - which corresponds to `ENODIR`, IIUC.
   - so that looks like at least one issue
- I think `ENODIR` here means that some part of the `/tmp/` path doesn't exist? But I'm not sure what to make of it
- As can be seen, the list of dirs is the same before, and after the call
- And if you look farther in the log, for other tests, and you can see that there were other directories created too in `/tmp`

I'm not sure what exactly might be going on. Maybe somebody familiar with node/windows can help.

cc @pavelsavara @maraf

**Comment by danmoseley** [comment]
Also note that CreateTempSubdirectoryCore ought to be passing the path to ThrowExceptionForIoErrno so that it appears in the error message.

**Comment by danmoseley** [comment]
I may be misunderstanding the translation that node is doing here but if 20 is a windows error (and if it isn’t then we generally won’t throw the right exception) it means “ The system cannot find the device specified.”.

**Comment by danmoseley** [comment]
Dumping some notes.

https://github.com/dotnet/runtime/pull/73743/files#diff-adfbd90ca2109cd4336860b1887e017b91ee3222515e9a762963b3bfb3b54086R58
->
https://github.com/nodesource/mkdtemp/blob/master/index.js#L119
->
https://github.com/libuv/libuv/blob/v1.x/src/win/fs.c#L1228
->
https://github.com/libuv/libuv/blob/d54c92e3e68f0b8152617d8e97f704dd1e586bd6/src/win/fs.c#L79
->
https://cs.github.com/libuv/libuv/blob/7bccb562e415030050cfbd1e69eeefd69ce57aca/src/win/error.c?q=uv_translate_sys_error#L96
Which does not translate to ENOTDIR.

Searching for UV_ENOTDIR, perhaps somehow it comes from here

https://cs.github.com/libuv/libuv/blob/7bccb562e415030050cfbd1e69eeefd69ce57aca/src/win/fs.c?q=_enotdir#L2333

**Comment by danmoseley** [comment]
Also where is "File exists" coming from? Not libuv's strerror, for either ENODIR or EEXIST:

https://github.com/libuv/libuv/blob/8bcd689c048af5aab26842ac5ff903fa3192d57c/src/uv-common.c#L212
->

https://github.com/libuv/libuv/blob/06948c6ee502862524f233af4e2c3e4ca876f5f6/include/uv.h#L122

**Comment by eerhardt** [comment]
> Also note that CreateTempSubdirectoryCore ought to be passing the path to ThrowExceptionForIoErrno so that it appears in the error message.

What path is that? We are building up a path template like:

`/tmp/XXXXXX`

And then passing that to `mkdtemp`, which will replace the `XXXXXX` with random letters. Would you really expect `/tmp/XXXXXX` to appear in the error message?

**Comment by pavelsavara** [comment]
https://github.com/emscripten-core/emscripten/blob/e05e72d9c49fe15578e73934ce525a894d1b712a/system/lib/libc/musl/src/temp/mkdtemp.c#L6

The NodeJS doesn't have built-in `crypto` unless you get package for it. We have following polyfill just for unit tests
```
globalThis.crypto = {
        getRandomValues: function (buffer) {
            for (let i = 0; i < buffer.length; i++)
                buffer[i] = (Math.random() * 256) | 0;
        }
    }
```

So I think it's not random enough.

**Comment by pavelsavara** [comment]
oh, it's even more direct to timer, which is not very precise.

https://github.com/emscripten-core/emscripten/blob/e05e72d9c49fe15578e73934ce525a894d1b712a/system/lib/libc/musl/src/temp/__randname.c

**Comment by danmoseley** [comment]
> Would you really expect /tmp/XXXXXX to appear in the error message?

I figured it would prove it had /tmp on it, but fair enough.

**Comment by danmoseley** [comment]
Seems I didn't understand how the stack fits together here 🙂

**Comment by pavelsavara** [comment]
I'm wondering how CLOCK_MONOTONIC works here

**Comment by eerhardt** [comment]
So it gives 100 retries of random names, and then gives up. Do we need to clean some `/tmp` folders in between runs? or ensure tests are cleaning out their tmp folders?

**Comment by eerhardt** [comment]
Would one option here be:

For wasm only, in SystemNative_MkdTemp, write a loop of calls to `mkdtemp`, check if the error is EEXIST, delay for a bit, and then try again?

**Comment by pavelsavara** [comment]
busy wait ? no thank you :)

**Comment by eerhardt** [comment]
> busy wait ? no thank you :)

It's better to throw an exception?

@tmds @omajid - do you happen to know how many retries a "normal" `mkdtemp` implementation tries before giving up? [100 retries](https://github.com/emscripten-core/emscripten/blob/e05e72d9c49fe15578e73934ce525a894d1b712a/system/lib/libc/musl/src/temp/mkdtemp.c#L6) seems to be awfully small.

**Comment by omajid** [comment]
The posix implementation of glibc tries `max(62 * 62 * 62, TMP_MAX)` times. [TMP_MAX](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/stdio.h.html) varies by OS.

**Comment by eerhardt** [comment]
`62 * 62 * 62` is a lot, almost a quarter million. Maybe we wouldn't even need a delay on WASM, but just try again a set number of times immediately if we get EEXIST error.

I see the above is linked to `musl` sources, would we have this same problem on alpine?

**Comment by danmoseley** [comment]
> busy wait ? no thank you :)

It's already doing this, we're just discussing how much it should do it, right? 

Another option is to implement mkdtemp ourselves, but with more reasonable randomness.

**Comment by radical** [comment]
So, the hypothesis right now is that it isn't able to find a unique name which doesn't already exist? In the tests we are listing the existing files, and directories, and it showed only 2 in the first failing, and subsequent ones increased by a handful only.
That would mean the random name generation is really bad! I guess like Pavel was pointing out in https://github.com/dotnet/runtime/issues/73721#issuecomment-1212036955 .

- If it's only depending on `tv_nsec` then would a little delay help much?

> Another option is to implement mkdtemp ourselves, but with more reasonable randomness.

That might be better than doing up to half a million exists checks, *shrug*.

**Comment by danmoseley** [comment]
stepping back, should we be disabling the tests, or implementing some hackaround promptly, as this presumably is impacting test runs?b

**Comment by eerhardt** [comment]
How often is this failing? And is it only on Windows/NodeJS? Looking at https://github.com/dotnet/runtime/issues/702 I currently see `N/A` for the "Build Count".

![image](https://user-images.githubusercontent.com/8291187/184263013-5cb8cd4b-ffa4-4ce1-baaa-29b04b6a38d1.png)

**Comment by radical** [comment]
```kusto
WorkItems
| where Queued >= ago(12h)
| where Status != "Pass" and Status != 'Error' and Status != 'DeadLetter'
| where ExitCode != -1234
| where FriendlyName == 'WasmTestOnNodeJs-System.CodeDom.Tests'
| limit 100
| project JobId, Status, ConsoleUri, ExitCode, WorkItemId
| join kind=inner (
    Jobs
    | extend PropertiesJson = parse_json(Properties)
    | where PropertiesJson ['architecture'] == 'wasm'
    ) on JobId
| project-away JobId1
| where PropertiesJson ['System.PhaseName'] !has '_Threading'
| extend JobName = PropertiesJson['System.PhaseName']
| extend PRNumber = replace_regex(Source, @'.*/(\d+)/merge', @'\1')
| extend PR = strcat('https://www.github.com/', Repository, '/pull/', PRNumber)
| project-reorder Queued, Status, PR, ConsoleUri, ExitCode, JobName, JobId, QueueName
| join kind=inner (
    TestResults
    | where Method != 'WorkItemExecution'
    ) on WorkItemId
| extend TestName=strcat(Method, ' - ', Type1)
| where TestName has 'FromSource_ValidSource_ReturnsExpected'
| project-reorder Queued, TestName, Message, PR, ConsoleUri, StackTrace
| order by Queued desc
| limit 100
```

In the last 12hours, these were the unique PRs with the specific failure:
<img width="651" alt="Screen Shot 2022-08-11 at 8 25 18 PM" src="https://user-images.githubusercontent.com/1472/184263686-f8571d84-d5e1-4f9b-a4ab-c5b60f68dfb1.png">

**Comment by radical** [comment]
Also, this is not seen on rolling builds because we don't run tests on nodejs in rolling builds, yet.

**Comment by danmoseley** [comment]
Removing the FriendlyName filter on your query above, and just using `| where StackTrace contains "CreateTempSubdirectory"` I still only see results for `FromSource_ValidSource_ReturnsExpected - System.CodeDom.Compiler.Tests.CodeCompilerTests`. Do we just need to disable this one? at the top, you listed other tests?

**Comment by radical** [comment]
```kusto
WorkItems
| where Queued >= ago(12h)
| where Status != "Pass" and Status != 'Error' and Status != 'DeadLetter'
| where ExitCode != -1234
//| where FriendlyName == 'WasmTestOnNodeJs-System.CodeDom.Tests'
| where FriendlyName  startswith "WasmTestOnNodeJs-"
| limit 100
| project JobId, Status, ConsoleUri, ExitCode, WorkItemId
| join kind=inner (
    Jobs
    | extend PropertiesJson = parse_json(Properties)
    | where PropertiesJson ['architecture'] == 'wasm'
    ) on JobId
| project-away JobId1
| where PropertiesJson ['System.PhaseName'] !has '_Threading'
| where PropertiesJson ['System.PhaseName'] !has '_PerfTracing'
| extend JobName = PropertiesJson['System.PhaseName']
| extend PRNumber = replace_regex(Source, @'.*/(\d+)/merge', @'\1')
| extend PR = strcat('https://www.github.com/', Repository, '/pull/', PRNumber)
| project-reorder Queued, Status, PR, ConsoleUri, ExitCode, JobName, JobId, QueueName
| join kind=inner (
    TestResults
    | where Method != 'WorkItemExecution'
    ) on WorkItemId
| extend TestName=strcat(Type1, '.', Method)
//| where TestName has 'FromSource_ValidSource_ReturnsExpected'
| project-reorder Queued, TestName, Message, PR, ConsoleUri, StackTrace
| order by Queued desc
| limit 100
```

<img width="1250" alt="Screen Shot 2022-08-12 at 12 42 42 AM" src="https://user-images.githubusercontent.com/1472/184286410-cd416797-7354-44f5-89c1-69d2839954d8.png">

Others are essentially for `Path.GetTempFileName` - `File exists`
1.
```
[19:27:14] fail: [FAIL] System.Diagnostics.TextWriterTraceListenerTests.CtorsDelimiterTests.TestConstructorWithFileNameAndName(testName: "")
[19:27:14] info: System.IO.IOException : File exists
[19:27:14] info:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory)
[19:27:14] info:    at Interop.CheckIo(Int64 result, String path, Boolean isDirectory)
[19:27:14] info:    at Interop.CheckIo(IntPtr result, String path, Boolean isDirectory)
[19:27:14] info:    at System.IO.Path.GetTempFileName()
[19:27:14] info:    at System.Diagnostics.TextWriterTraceListenerTests.CtorsDelimiterTests.TestConstructorWithFileNameAndName(String testName)
[19:27:14] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
```

2.
```
[19:29:23] fail: [FAIL] System.ServiceModel.Syndication.Tests.BasicScenarioTests.SyndicationFeed_Write_RSS_Atom
[19:29:23] info: System.IO.IOException : File exists
[19:29:23] info:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory)
[19:29:23] info:    at Interop.CheckIo(Int64 result, String path, Boolean isDirectory)
[19:29:23] info:    at Interop.CheckIo(IntPtr result, String path, Boolean isDirectory)
[19:29:23] info:    at System.IO.Path.GetTempFileName()
[19:29:23] info:    at System.ServiceModel.Syndication.Tests.BasicScenarioTests.SyndicationFeed_Write_RSS_Atom()
[19:29:23] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
```

I can open a PR to disable these, but I think do need to fix this. It's not just a testing thing. Though @eerhardt , and I tried to reproduce this locally, and we weren't able to.

**Comment by pavelsavara** [comment]
> > Another option is to implement mkdtemp ourselves, but with more reasonable randomness.
> 
> That might be better than doing up to half a million exists checks, _shrug_.

I think that would be better option.

Disabling the tests for now is OK.

**Comment by akoeplinger** [comment]
with which nodejs version did you try reproducing? I don't remember exactly how we install node for helix tests but it could be an older one

**Comment by eerhardt** [comment]
> with which nodejs version did you try reproducing? I don't remember exactly how we install node for helix tests but it could be an older one

I tried it with `v14.16.1`.

**Comment by eerhardt** [comment]
I've also tried `v16.16.0` and `v18.7.0`.  System.CodeDom tests pass on both versions as well. What version does the CI machines have?

An interesting observation is that on `v14` and `v16`, the tests take about 7s to run.  But on `v18`, the tests are taking about 43s to run. Nothing else changed but the NodeJS version, so I'm assuming we are hitting a pretty bad perf regression in Node here.

**Comment by maraf** [comment]
> I've also tried `v16.16.0` and `v18.7.0`. System.CodeDom tests pass on both versions as well. What version does the CI machines have?

14.18.2_64bit

**Comment by radical** [comment]
@pavelsavara do we need to fix this in 7? The console template uses node, but it is still in `wasm-experimental`.

**Comment by radical** [comment]
.. and we don't even always run tests with nodejs, or on linux.

**Comment by lewing** [comment]
this isn't urgent at all and we will be looking at the fs related syscalls for wasi in 8

**Comment by tmds** [comment]
> So it gives 100 retries of random names, and then gives up.

_100 retries ought to be enough for anybody_ :smile: 

> I see the above is linked to musl sources, would we have this same problem on alpine?

The random function that is used is different: https://github.com/bminor/musl/blob/master/src/temp/__randname.c.
vs https://github.com/emscripten-core/emscripten/blob/e05e72d9c49fe15578e73934ce525a894d1b712a/system/lib/libc/musl/src/temp/__randname.c.

**Comment by eerhardt** [comment]
> The random function that is used is different

This gave me some insight as to why #73408 affected `Path.GetTempFileName()` on WASM and why it started failing. In the emscripten version, the random function uses:

```
	r = ts.tv_nsec*65537 ^ (uintptr_t)&ts / 16 + (uintptr_t)template;
```

Note that last part: `+ (uintptr_t)template`, they are adding the **pointer value** into the randomness.

Looking at my change in #73408:

```diff
-            byte[] name = Encoding.UTF8.GetBytes(template);
+            string tempPath = Path.GetTempPath();
+            int tempPathByteCount = Encoding.UTF8.GetByteCount(tempPath);
+            int totalByteCount = tempPathByteCount + fileTemplate.Length + 1;

+            Span<byte> path = totalByteCount <= 256 ? stackalloc byte[256].Slice(0, totalByteCount) : new byte[totalByteCount];
```

Previously, we were always allocating the `byte[]` on the heap. Thus the pointer value was more than likely different every time we called `GetTempFileName()`. But, in order to reduce allocations, I changed the function to stackalloc the `byte[]`, which means if `GetTempFileName()` is called twice in a row from the same method, the pointer value is going to be the same, because it will occupy the same space on the stack.

**Comment by danmoseley** [comment]
Wow!

**Comment by danmoseley** [comment]
Who owns next step on this one, and what is it?

**Comment by tmds** [comment]
I think the next step is to create our own random name function for wasm that has more entropy.

**Comment by danmoseley** [comment]
Yup. Anyone interested..

**Comment by danmoseley** [comment]
This, or some form of it, will need a backport into 7.0..

**Comment by pavelsavara** [comment]
Fixing it upstream would take long time and we don't have easy way how to patch it in C code on our side.
Perhaps WASM specific version of `SystemNative_MkdTemp` would do it ?

**Comment by eerhardt** [comment]
We could also use a WASM specific C# method that always called `Encoding.UTF8.GetBytes` on the string. This would allocate memory on the heap, which would change the `template` pointer passed into the `__randname` function every time GetTempFileName was called.

**Comment by danmoseley** [comment]
Depending on what other allocations are happening concurrently perhaps it might also need a random sized dummy allocation (e.g. after the first try)

**Comment by lewing** [comment]
@maraf what is the status on this?  SyndicationFeed_Write_RSS_Atom is failing pretty frequently now
