### ISSUE TITLE
Generic attributes lack testing

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#73735]
We need reflection tests that test generic attributes.

https://github.com/dotnet/linker/issues/2963 made it clear that we don't have any targeted reflection tests for the new scenario in the libraries partition. The newly added test is not a targeted reflection test - it's a S.R.Metadata test.

**Comment by buyaa-n** [comment]
We[ have some tests,](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Runtime/tests/System/Attributes.cs#L243-L323 ) but might need to improve the coverage

**Comment by MichalStrehovsky** [comment]
The specific tests that are needed are tests that are using the generic type's T in the signatures (that's the bug we ran into).

So things like:

```csharp
class FooAttribute<T>: Attribute { public FooAttribute(T value, T[] othervalue) { } }
class BarAttribute<T> : Attribute { public T SomeValue { get; set; } }
```

The existing tests are not testing much because they don't use the T.

**Comment by MichalStrehovsky** [comment]
I would definitely at least put it in 8.0 but AFAIK generic attributes are new in C# for .NET 7.0 so we should have testing in place to make sure reflection on them actually works in various scenarios.

Cc @333fred

**Comment by buyaa-n** [comment]
> I would definitely at least put it in 8.0 but AFAIK generic attributes are new in C# for .NET 7.0 so we should have testing in place to make sure reflection on them actually works in various scenarios.

Sure, we will reevaluate all issue during 8.0 planning

**Comment by 333fred** [comment]
> AFAIK generic attributes are new in C# for .NET 7.0

That's correct.

**Comment by steveharter** [comment]
Moving to 9; the mono bug linked above unfortunately didn't add a test that would have helped here.
