### ISSUE TITLE
FileSystemWatcher Notifications / Wait for Completion

### ISSUE THREAD

**Issue by Varorbc** [dotnet/runtime#73746]
> There seems to be a common scenario where people use the FileSystemWatcher to trigger an action upon a file's creation. However, as this trigger is fired when the file starts to be created, rather than once that process completes (and thus the file is complete / the lock is removed), people have often had to write custom code to loop, checking whether the file's locked, before eventually performing some action on it.
> 
> Examples:
> 
> * https://www.intertech.com/Blog/avoiding-file-concurrency-using-system-io-filesystemwatcher/
> * https://stackoverflow.com/questions/44583244/copy-item-does-not-work
> 
> One possible solution would be to have another NotifyFilter which could trigger the FileSystemWatcher event once the file had been fully written to; or once locks were removed.
> 
> Example code illustrating the current workaround quoted from above InterTech blog:
> 
> ```
> 
> class WatcherService
> {
>     System.IO.FileSystemWatcher watcher;
>     public WatcherService()
>     {
>         watcher = new System.IO.FileSystemWatcher();
>         watcher.EnableRaisingEvents = true;
>         watcher.Filter = "*.zip";
>         watcher.NotifyFilter = System.IO.NotifyFilters.LastWrite;
>         watcher.Changed += new System.IO.FileSystemEventHandler(FileChanged);
>     }
> 
>     private void FileChanged(object sender, FileSystemEventArgs e)
>     {
>         if (!IsFileReady(e.FullPath)) return; //first notification the file is arriving
> 
>         //The file has completed arrived, so lets process it
>         DoWorkOnFile(e.FullPath);
>     }
> 
>     private bool FileIsReady(string path)
>     {
>         //One exception per file rather than several like in the polling pattern
>         try
>         {
>              //If we can't open the file, it's still copying
>              using (var file = File.Open(path, FileMode.Open, FileAccess.Read, FileShare.Read))
>              {
>                  return true;
>              }
>         }
>         catch (IOException)
>         {
>              return false;
>         }
>     }
> }
> ```

Copied from original issue: https://github.com/Microsoft/dotnet/issues/437

**Comment by adamsitnik** [comment]
@Jozkee does the sys-call that we use by `FSW` allows for this kind of filtering?

**Comment by Jozkee** [comment]
@adamsitnik no it doesn't, and with the current state of the sys-call, I don't think we could make something better than the workaround mentioned of looping until the file is no longer locked.
