### ISSUE TITLE
ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by mayadav1** [dotnet/runtime#73755]
Command failed with following error :
  build.cmd clr+libs -c debug -a x64

Error :
  waiting for C:/Users/mayadav1/runtime/artifacts/obj/win-x64.Debug/corehost/test/typelibs\dlldata.c ...
  ninja: build stopped: subcommand failed.
  Failed to generate native component build project!

dlldata.c is present above path.

**Comment by huoyaoyuan** [comment]
For any build issue, it's better to clean your `artifacts` directory (or `artifacts\obj`) and try a clean build again.

**Comment by mayadav1** [comment]
@huoyaoyuan Thanks for addressing my issue . I tried to clean build before build. I tried again but faced the same issue.
I tried to clean the build with the help of "git clean -xdf".
Please extend your help .

**Comment by danmoseley** [comment]
@mayadav1 What version of ninja do you have? Are you building the latest main or something else?

**Comment by mayadav1** [comment]
I am trying to build latest main.

**Comment by mayadav1** [comment]
I refined the cause of error and found below error as cause of failure .

C:\Users\mayadav1\Desktop\runtime\src\native\corehost\test\ijw\ijw.cpp(22): error C2253: 'System::Numerics::INumberBa
  se<TSelf>::IsImaginaryNumber': pure specifier or abstract override specifier only allowed on virtual function

**Comment by hoyosjs** [comment]
I thought for a second it was going to be python and the comment didn't get posted. But no, your error is you need a newer version of VS installed (17.2 Preview 2) with a v143 compiler installed.
