### ISSUE TITLE
COM event with recursion .net 6 problem

### ISSUE THREAD

**Issue by maciejpieprzyk** [dotnet/runtime#73754]
### Description

We are using a system that exposes UI interface using COM objects. It is an external application so I cannot send a minimal reproduction source code of a problem.  I will try to explain the whole workflow.

#### Background information

There is an application interface (COM) that exposes event.

Event declaration in the App interface:

```c#
event _IApplicationEvents_StatusBarEventEventHandler StatusBarEvent;
```

Delegate definition:

```c#
public delegate void _IApplicationEvents_StatusBarEventEventHandler([In][MarshalAs(UnmanagedType.BStr)] string Text, [In] BoStatusBarMessageType messageType);
```

There is also a StatusBarControl that allows us to set up the ProgressBarMessage:

```c#
application.StatusBar.SetText(“some text”);
```

When we set the text to the status bar Event is fired.

### Reproduction Steps

UseCase: When the StatusBarEvent fires with text equal to “crush” we want to change this to "****" on the status bar

EventHandler implementation:

```c#
public override void OnStatusBarDisplayed(string text, BoStatusBarMessageType messageType)
{
    if (text.Equals("crush",StringComparison.CurrentCultureIgnoreCase))
    {
        application.StatusBar.SetText("*****");
    }
}
```

I will provide some screenshots of the debugging session:

1. Set "crush" to the status bar. ![image](https://user-images.githubusercontent.com/11562129/183669932-142a27de-d396-46d6-af17-028fabef3b5c.png)
2. We get the Event notification and call the setText("****").
3. System freezes. We can see that the event handler thread freezes on the set text method. ![image](https://user-images.githubusercontent.com/11562129/183670295-a1fd1989-ec16-44db-88b8-9276995fca18.png)
4. We can see that in the separate thread invoking a method the foreach loop of _delegateWrapper. ![image](https://user-images.githubusercontent.com/11562129/183670408-a912b540-42d3-401b-abe8-633cb8b21d7d.png)

### Expected behavior

What should happen: this thread @29816 should invoke this method and Call the OnStatusBarDisplayed event again. This is working correctly when running in the .net framework.

Below is the same call stack of the .net framework debugging session. ![image](https://user-images.githubusercontent.com/11562129/183670717-228d0842-c11f-49f4-ae78-182c29f6afe6.png)

Calling SetText in another thread is not an option for us.

### Actual behavior

System freezes. We can see that the event handler thread freezes on the set text method. ![image](https://user-images.githubusercontent.com/11562129/183670295-a1fd1989-ec16-44db-88b8-9276995fca18.png)

### Regression?

This is working correctly when running in the .net framework.

### Known Workarounds

Calling SetText in another thread but this is not an option for us.

### Configuration

.NET 6.0
Windows 11
x64

**Comment by MichalWeczorek** [comment]
Hello 
I was having a similar issue. This is critical from my point of view, please consider fixing this problem with the COM object in the .net core 6 version as it is in the extended therm support.
Here is the reproduction repository link
https://github.com/MichalWeczorek/COM-event-with-recursion-.net-6-problem
if you debug the .net6 version it freezes
if you debug in .net framework 4.72 all works correctly.

Thanks

**Comment by lukaszch** [comment]
Hi @jeffschwMSFT,
Is there any chance that somebody will check if there is any chance to fix this issue in .NET 6, which is LTS, and we would love to use it now, instead of waiting for .NET 8?

We are completely stuck with our migration from .NET Framework to .NET 6 until this issue is resolved, or we have some workable workaround. Unfortunately, so far, we haven't found any.
The code is working fine on the .NET Framework. Still, it hangs on .NET 6. @MichalWeczorek, in his previous comment, provided reproduction on the Excel COM library, so this problem is not specific to our code base or any particular external API.

I highly appreciate any support which you can provide.
Thank you very much!

**Comment by jeffschwMSFT** [comment]
Thank you for providing details on the impact.  On process is to first fix it in our primary branch and then consider backporting.  Adding some folks that might be able to offer a suggested workaround in the meantime.

cc @jkoritzinsky  @elinor-fung @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
I don't know of the correct fix here as I've just not had time to take a look. To be honest I was considering this very low priority because of COM Events. I can make some time when I get back if this is a priority. I don't know of a workaround without debugging.

arr


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by lukaszch** [comment]
Thank you for your prompt reaction!

@AaronRobinsonMSFT, from our point of view, it's critical as the application hangs, and there is no known workaround.

In the repo https://github.com/MichalWeczorek/COM-event-with-recursion-.net-6-problem, there's ready code for debugging. We are also happy to provide any required feedback to resolve this issue.

Keeping our fingers crossed for your findings and fixing this issue :). Thank you.

**Comment by AaronRobinsonMSFT** [comment]
@MichalWeczorek Thank you for the simple reproduction. I was able to immediately root out the issue. This has been present since we introduced COM events back in .NET Core 3.1. As soon as I get sign-off for .NET 8, I will work to get it into .NTE 7 and possibly .NET 6.

**Comment by MichalWeczorek** [comment]
I'm pleased that this issue is moving forward. I am waiting to hear more good news soon. 
Thank you @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
@MichalWeczorek and @lukaszch This has been checked into .NET 8. I have filed servicing requests for .NET 6 and .NET 7. You can following them at: https://github.com/dotnet/runtime/pull/76035 and https://github.com/dotnet/runtime/pull/76034.

**Comment by lukaszch** [comment]
Thank you @AaronRobinsonMSFT for your quick reaction to fix this issue.
It's simply amazing :).
