### ISSUE TITLE
[NativeAOT] Timeout: System.Net.Http.Functional.Tests

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#73776]
Failures in [last 120 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A~120%20definition%3Aruntime-extra-platforms%20name%3A%22system.net.http.functional.tests%20work%20item%22) - 8/5-8/24 (incl. PRs):

Day | Run | Details
-- | -- | --
~8/21~ | ~Rolling run [1957446](https://runfo.azurewebsites.net/view/build/?number=1957446) (7.0-rc1)~ | ~net7.0-Linux-Release-arm64-NativeAOT_Release-(Ubuntu.1804.ArmArch.Open)~ - different error with [Core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-70-rc1-b49b757c823a457a9b/System.Net.Http.Functional.Tests/1/core.1001.25?%3Fhelixlogtype%3Dresult) ([Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-70-rc1-b49b757c823a457a9b/System.Net.Http.Functional.Tests/1/console.b407d63e.log?%3Fhelixlogtype%3Dresult)): SIGILL Illegal Instruction. Core dumped.
8/10 | PR [1935402](https://runfo.azurewebsites.net/view/build/?number=1935402) - PR #73416 | net7.0-windows-Release-x64-NativeAOT_Release-(Windows.Nano.1809.Amd64.Open)
8/10 | Rolling run [1935157](https://runfo.azurewebsites.net/view/build/?number=1935157) | net7.0-windows-Release-x64-NativeAOT_Release-Windows.10.Amd64.Server2022.ES.Open
~8/10~ | ~Rolling run [1935157](https://runfo.azurewebsites.net/view/build/?number=1935157)~ | ~net7.0-windows-Release-x64-NativeAOT_Release-Windows.81.Amd64.Open~ - different error ([Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-2a718b83a21749b78d/System.Net.Http.Functional.Tests/1/console.42d54869.log?%3Fhelixlogtype%3Dresult)): System.Exception : Connection stream closed while attempting to read frame body. at System.Net.Test.Common.Http2LoopbackConnection.<ReadFrameAsync>d__27.MoveNext() + 0xa68
8/8 | PR [1931024](https://runfo.azurewebsites.net/view/build/?number=1931024) - PR #73547 | net7.0-windows-Release-x64-NativeAOT_Release-Windows.11.Amd64.Client.Open

**Comment by CarnaViire** [comment]
Triage: we might want to figure out the root cause of timeout to find out how critical is it for 7.0

**Comment by karelz** [comment]
Triage: We need to check CI results after the suspicious test was disabled (#73772).
If it is gone, we should treat it as duplicate of the issue. In such case it won't be critical as it is feature with pipes that didn't work in 6.0, so not a regression.

**Comment by karelz** [comment]
The problem is gone - no hits in last 2 weeks (since 8/10). Marking as duplicate per triage info above.

**Comment by karelz** [comment]
Duplicate of #73772
