### ISSUE TITLE
Codespaces prebuild often fails with msbuild "Child node "2" exited prematurely"

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#73774]
If you look at the [recent runs of the Codespaces prebuild](https://github.com/dotnet/runtime/actions/workflows/codespaces/create_codespaces_prebuilds) workflow you'll see that almost all of them failed with this error near the end of the build:

```
MSBUILD : error MSB4166: Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in "/tmp/" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to
```

It doesn't seem to be a timeout issue. Maybe it runs out of memory or something?

I couldn't find a way how to upload custom files during a Codespaces prebuild so not sure how we can grab these MSBuild logs.

The problem got bad about a month ago though it happened occasionally before that too.

**Comment by akoeplinger** [comment]
@eerhardt do you know how to upload files during a Codespaces prebuild?

**Comment by danmoseley** [comment]
Is there some log we can append the content to?

BTW I clicked on some of the failures at the link, and they fail this way --
```
[2022-08-03 05:07:53.844 DockerImagePrune I] Terminal text: '$ docker rmi vsc-runtime-f7efa0c7885b1c4a4329ddd27c526697:latest'
[2022-08-03 05:07:53.944 DockerImagePrune I] Error response from daemon: conflict: unable to remove repository reference "vsc-runtime-f7efa0c7885b1c4a4329ddd27c526697:latest" (must force) - container 4def87081295 is using its referenced image 04d11e078878
[2022-08-03 05:07:53.950 DockerImagePrune I] docker process exited with exit code 1
```

**Comment by danmoseley** [comment]
with respect to MSB4166, funnily enough a previous me had this problem and submitted a change to MSBuild that perhaps should have made it easier:

https://github.com/dotnet/msbuild/pull/3632

I guess not.

**Comment by agocke** [comment]
Looks resolved.
