### ISSUE TITLE
Compile error in TypeUtilTests.cs: The type 'Uri' exists in both System.Private.Uri and System.Runtime

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#73792]
This only seems to happen in iOS/tvOS/Android jobs: https://dev.azure.com/dnceng/public/_build/results?buildId=1936445&view=logs&j=b6e5d97f-d4f8-506b-9e47-e3e32385754a&t=19675e64-e10d-5dfb-008e-ff58b683bfa1

```
/Users/runner/work/1/s/src/libraries/System.Configuration.ConfigurationManager/tests/System/Configuration/TypeUtilTests.cs(25,45): error CS0433: The type 'Uri' exists in both 'System.Private.Uri, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [/Users/runner/work/1/s/src/libraries/System.Configuration.ConfigurationManager/tests/System.Configuration.ConfigurationManager.Tests.csproj]
    0 Warning(s)
    1 Error(s)
```

Presumably it is related to https://github.com/dotnet/runtime/pull/73087

**Comment by steveharter** [comment]
cc @CoffeeFlux @steveisok thoughts here? The test project is using System.Uri which is also embedded in System.Runtime.

I'll create a PR to at least remove the test project from CI.

**Comment by akoeplinger** [comment]
I was able to repro locally and have some leads, I'll look into it together with @ViktorHofer later today.

**Comment by ericstj** [comment]
We should never have these tests using a System.Private reference.  Something is leaking in from a ProjectReference. 

Is this ProjectReference actually required:
https://github.com/dotnet/runtime/pull/73087/files#diff-4d639cb37fe53cdeae4262c1f5be7936cdd81e3b4f256f9c59ad02ec69b300d9R101

We don't use ProjectReferences for any other libraries which are part of the shared framework (System.Runtime, System.Collections, etc).

**Comment by akoeplinger** [comment]
@ericstj if I remove that ProjectReference then the error doesn't happen anymore. I can send a PR if you think that's the correct fix.

**Comment by steveharter** [comment]
@akoeplinger I'll go ahead and create a PR for that thanks.
