### ISSUE TITLE
AccessViolationException should not be catchable

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#73794]
### Description

When an AccessViolationException is thrown, the exception is supposed to be uncatchable. With recent changes in the reflection-invoke machinery, an AccessViolationException that is thrown through reflection-invoke is wrapped in a catchable TargetInvocationException.

This was discovered when updating dotnet/arcade to Preview 7 from Preview 5 (I've validated that the regression started in Preview 6).

### Simplified Repro Steps
(Added by @AntonLapounov.)
```C#
using System;

try
{
    unsafe { *(int*)0x10000 = 0; }
}
catch (AccessViolationException)
{
    Console.WriteLine("Shouldn't be able to catch this exception.");
}
```

### Reproduction Steps

```csharp
using System;
using System.Reflection;
try
{
    typeof(A).GetMethod(nameof(A.AV)).Invoke(null, null);
}
catch (TargetInvocationException ex) when(ex.InnerException is AccessViolationException)
{
      Console.WriteLine("Shouldn't be able to catch this exception.");
}

class A
{
     public unsafe static void AV()
     {
          *(int*)0x10000 = 0;
     }
} 
```

### Expected behavior

The process crashes

### Actual behavior

"Shouldn't be able to catch this exception." is written to the console.

### Regression?

This is a regression from .NET 7 Preview 5 and earlier

### Known Workarounds

Explicitly check for a TargetInvocationException with an inner AV and don't catch it.

### Configuration

Windows 11 x64

**Comment by jkoritzinsky** [comment]
It looks like an `AccessViolationException` even unwrapped can be caught now in a `catch` clause as well. Changing the area to ExceptionHandling.

cc: @janvorli

**Comment by jkotas** [comment]
Regression likely introduced by https://github.com/dotnet/runtime/pull/70428

**Comment by mangod9** [comment]
adding Anton since JanV is out.

**Comment by AntonLapounov** [comment]
Confirmed that undoing #70428 fixes the issue.

**Comment by AntonLapounov** [comment]
The new code path always sets `ExceptionCode` to `EXCEPTION_COMPLUS`, so hardware exceptions are no longer recognized by `IsProcessCorruptedStateException` (which expects `STATUS_ACCESS_VIOLATION` for an AV).

**Comment by jkotas** [comment]
I would recommend reverting the change. IIRC, it will regress GC stress with CET, but that is more acceptable than the current state.

**Comment by mangod9** [comment]
Yeah believe this only affects CET GCStress. Looking back at the change both codepaths are calling `clrexception::GetThrowableFromException`. Is there some translation for hardware exceptions which is now missing?

**Comment by jkotas** [comment]
>  Is there some translation for hardware exceptions which is now missing?

It is the other way around: There is too much of a translation being done for hardware exceptions too early. The hardware exception gets rethrown as ordinary managed exception here: https://github.com/dotnet/runtime/pull/70428/files#diff-47cbfa47fb88845e5e76fd4df0a84e9da494508ffe80da116511fc2d0becd9baR6678 . None of the special casing for hardware exceptions is going to kick in once that happens.

**Comment by AntonLapounov** [comment]
Even if we revert the change, the new code path would still be used for Windows x64 with CET and one would still be able to catch `AccessViolationException`s there.  (I have no hardware to verify, but that is what I see from the code.)  I feel that if we could stash the original exception code in `HandleManagedFault` and then check it in `ProcessCLRException`, that would solve the issue.

**Comment by mangod9** [comment]
Adding @kouvel who can provide details on hardware

**Comment by AntonLapounov** [comment]
Not familiar with this code, but I am wondering if the following modification of `HandleManagedFault` would work (the new steps are marked):
* Create and link a `FaultingExceptionFrame`.
* (**New**) Check whether the `ExceptionCode` corresponds to one of process-corrupted-state exceptions.
* (**New**) If yes, re-raise the exception by calling `RaiseException` with exactly the same exception data — that is what `LinkFrameAndThrow` would do before [#70428](https://github.com/dotnet/runtime/pull/70428).
* If no, create the managed exception with `GetThrowableFromException` and throw it by calling `RaiseTheExceptionInternalOnly`.

Another thing I tried is to do nothing for process-corrupted-state exceptions in `HandleManagedFault` and return `EXCEPTION_CONTINUE_SEARCH` from the vectored exception handler.  That makes `ProcessCLRException` terminate the process as expected; however, it cannot dump the crash call stack as we have not linked the frame.
