### ISSUE TITLE
Runtime_72845 timing out in gcstress

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#73808]
https://dev.azure.com/dnceng/public/_build/results?buildId=1935562&view=ms.vss-test-web.build-test-results-tab

This is a recently added test so not a regression. The test is comparing two large lists, so likely to be gcstress incompatible, but we should probably verify that there is no deadlock.

**Comment by jakobbotsch** [comment]
@JulieLeeMSFT can you assign this? GCStress is still failing due to this one.

**Comment by jakobbotsch** [comment]
Actually I'll just look at this, I have some cycles available.

**Comment by jakobbotsch** [comment]
This test takes a long time to run on x64 too, so I think it is just GC stress incompatible and nothing inherent about arm64 here.

**Comment by JulieLeeMSFT** [comment]
Thanks @jakobbotsch.
