### ISSUE TITLE
Determine readlink result whether should be validated or not

### ISSUE THREAD

**Issue by Jozkee** [dotnet/runtime#73812]
From @pedrobsaila https://github.com/dotnet/runtime/pull/72258#issuecomment-1199985566:

> libraries\Common\src\System\Net\NetworkInformation\UnixCommandLinePing.cs : I validate result because ping executable should be check (ex: file exists) before it can be used as a command line
> https://github.com/dotnet/runtime/blob/953fd351ae1c5c8c11ba865b3613b63f8f774624/src/libraries/Common/src/System/Net/NetworkInformation/UnixCommandLinePing.cs#L39-L49

**Comment by CarnaViire** [comment]
Triage: We should fix it in 8.0
