### ISSUE TITLE
OpenSslCachedSystemStoreProvider: Determine readlink result whether should be validated or not

### ISSUE THREAD

**Issue by Jozkee** [dotnet/runtime#73815]
From @pedrobsaila https://github.com/dotnet/runtime/pull/72258#issuecomment-1199985566:
> libraries\System.Security.Cryptography\src\System\Security\Cryptography\X509Certificates\OpenSslCachedSystemStoreProvider.cs : seems to handle case where link is not resolved. I'm not sure whether I should validate or not.
> 
> https://github.com/dotnet/runtime/blob/c12bea880a2f1290d16adf97ec1000aa63631da2/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/OpenSslCachedSystemStoreProvider.cs#L323-L385

**Comment by bartonjs** [comment]
I don't quite know what validated or not means here; but the code seems correct as-is.

**Comment by Jozkee** [comment]
> what validated or not means here

I meant, look at the error set by `Interop.Sys.ReadLink()`, e.g: `if (Interop.Sys.GetLastError() == Interop.Error.EINVAL) throw SomeException();`

**Comment by bartonjs** [comment]
Yeah, we don't care why it failed.  If ReadLink says success then we use the destination's modified time, otherwise we use the source's modified time.
