### ISSUE TITLE
Configuring Console Json Formatting with JsonWriterOptions doesn't work with Trimming

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#73822]
### Description

We are suppressing a trimming warning here:

https://github.com/dotnet/runtime/blob/d8226260c9630c2fb196acaa6af7f5dbb45685ee/src/libraries/Microsoft.Extensions.Logging.Console/src/ConsoleLoggerExtensions.cs#L25-L27

But we aren't taking the correct steps to ensure all the properties that can be configured through the IConfiguration binder are being preserved. For example, properties on `JsonWriterOptions` can be trimmed causing the configuration to stop working.

### Reproduction Steps

Publish the following app both with and without trimming
`dotnet publish -r win-x64`
`dotnet publish -r win-x64 -p:PublishTrimmed=true`

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="6.0.0" />
  </ItemGroup>
</Project>
```

```C#
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

IServiceCollection services = new ServiceCollection();

IConfiguration config = new ConfigurationBuilder()
    .AddInMemoryCollection(
        new[]
        {
            new KeyValuePair<string, string>("Logging:Console:FormatterName", "json"),
            new KeyValuePair<string, string>("Logging:Console:FormatterOptions:JsonWriterOptions:Indented", "true"),
        })
    .Build();

services.AddLogging(logging =>
{
    logging.AddConfiguration(config.GetSection("Logging"));
    logging.AddConsole();
});

var sp = services.BuildServiceProvider();

var logger = sp.GetRequiredService<ILogger<int>>();

logger.LogCritical("Press any key to continue");

Console.ReadKey();
```

### Expected behavior

The output of both apps is identical. Trimming shouldn't affect the behavior of the app.

### Actual behavior

When untrimmed, the output is:

```
{
  "EventId": 0,
  "LogLevel": "Critical",
  "Category": "int",
  "Message": "Press any key to continue",
  "State": {
    "Message": "Press any key to continue",
    "{OriginalFormat}": "Press any key to continue"
  }
}
```

When trimmed, the output is:

```
{"EventId":0,"LogLevel":"Critical","Category":"int","Message":"Press any key to continue","State":{"Message":"Press any key to continue","{OriginalFormat}":"Press any key to continue"}}
```

### Regression?

No

### Known Workarounds

You can manually preserve all the properties on `JsonWriterOptions`.

**Comment by MichalStrehovsky** [comment]
Oh! Would this also explain #73436?

**Comment by eerhardt** [comment]
> Oh! Would this also explain #73436?

It could very well explain the first error in the description:

```
[FAIL] Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerExtensionsTests.AddJsonConsole_ChangeProperties_IsReadFromLoggingConfiguration
Assert.True() Failure
Expected: True
Actual:   False
   at Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerExtensionsTests.AddJsonConsole_ChangeProperties_IsReadFromLoggingConfiguration() + 0x277
   at Microsoft.Extensions.Logging.Console.Tests!<BaseAddress>+0x88e32c
   at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0xf1
```

Unfortunately, there are no line numbers, so I can't tell which `Assert.True` is failing. But if it is the one at

https://github.com/dotnet/runtime/blob/231255dac0fe015ebc6fb55466c75cf5b4e05f56/src/libraries/Microsoft.Extensions.Logging.Console/tests/Microsoft.Extensions.Logging.Console.Tests/ConsoleLoggerExtensionsTests.cs#L299

Then this issue could definitely explain that failure.
