### ISSUE TITLE
RuntimeType.GetGenericTypeDefinition() performance issue

### ISSUE THREAD

**Issue by israellot** [dotnet/runtime#73860]
`RuntimeType.GetGenericTypeDefinition()` is a bit expensive. 
As in a Dictionary<type,type> cache lookup is faster. 
I would naively expect that the generic definition of a type is stored in a field of the constructed type and GetGenericTypeDefinition to be a simple field access.

**Comment by deeprobin** [comment]
@israellot I assume you are using the CoreCLR implementation (Mono and CoreCLR have different implementations here).

Could you give us a benchmark (using BenchmarkDotNet or similar) / minimal reproducible example?
The problem is most likely in the method behind the QCall "RuntimeTypeHandle_GetGenericTypeDefinition".
https://github.com/dotnet/runtime/blob/ef2938999a4a528fc4b0ca719e4438520ba52100/src/coreclr/System.Private.CoreLib/src/System/RuntimeHandles.cs#L687-L701

---

https://github.com/dotnet/runtime/blob/9d6396deb02161f5ee47af72ccac52c2e1bae458/src/coreclr/vm/runtimehandles.cpp#L1493-L1514

**Comment by israellot** [comment]
Of course @deeprobin . This is a very naive, minimal example.
The generic type cache is unfair in the context, but it the generic type definition were to be a field of the type itself this is the ballpark of timing I would expect.

`using System;
using System.Diagnostics;

public class Program
{
    static Dictionary<Type, Type> _dictionaryCache = new Dictionary<Type, Type>();

    static void Main(string[] args)
    {

        var run = 100_000_000;

        //just 10 random types
        var constructedTypes = new[] {
            typeof(GenericType<string>),
            typeof(GenericType<int>),
            typeof(GenericType<long>),
            typeof(GenericType<double>),
            typeof(GenericType<float>),
            typeof(GenericType<decimal>),
            typeof(GenericType<uint>),
            typeof(GenericType<ulong>),
            typeof(GenericType<byte>),
            typeof(GenericType<char>)
        };

        var sw = Stopwatch.StartNew();
        for (var i = run; i >= 0; i--)
        {
            var genericTypeDefinition = constructedTypes[i%10].GetGenericTypeDefinition();
        }
        sw.Stop();
        Console.WriteLine($"GetGenericTypeDefinition() : {sw.ElapsedMilliseconds:f2}ms");

        

        sw.Restart();
        for (var i = run; i >= 0; i--)
        {
            if(!_dictionaryCache.TryGetValue(constructedTypes[i % 10], out var genericTypeDefinition))
            {
                genericTypeDefinition= constructedTypes[i % 10].GetGenericTypeDefinition();
                _dictionaryCache[constructedTypes[i % 10]] = genericTypeDefinition;
            }
        }
        sw.Stop();
        Console.WriteLine($"Dictionary Cache : {sw.ElapsedMilliseconds:f2}ms");

        sw.Restart();
        for (var i = run; i >= 0; i--)
        {
            var genericTypeDefinition = GenericTypeDefinitionCache<GenericType<int>>.GenericTypeDefinition;
        }
        sw.Stop();
        Console.WriteLine($"GenericTypeDefinitionCache<T> : {sw.ElapsedMilliseconds:f2}ms");

        Console.ReadKey();

    }
}

class GenericType<T>
{

}

static class GenericTypeDefinitionCache<T>
{
    public static readonly Type GenericTypeDefinition;

    static GenericTypeDefinitionCache()
    {
        GenericTypeDefinition = typeof(T).GetGenericTypeDefinition();
    }
}`

**Comment by deeprobin** [comment]
@israellot Thank you.

Profiling results:

![grafik](https://user-images.githubusercontent.com/10373452/185197375-7e92c4ae-045b-4748-a9af-353f5c0dd05f.png)

Here you can see that the whole thing is not the C# side part to execute the QCalls but it is the CLR part.

---

![grafik](https://user-images.githubusercontent.com/10373452/185200066-674b154a-b388-4633-9e50-36e761131ed6.png)

The bottleneck is `ClassLoader::LoadTypeDefThrowing`.
@Maoni0 And 15,4% for GC is also a lot, isn't it?

**Comment by israellot** [comment]
Thanks @deeprobin . 
This method in particular is used a lot by serializers. I actually figured out analyzing json.net library. I imagine it could be an interesting improvement.

**Comment by jkotas** [comment]
It should be fine to cache this in RuntimeTypeCache . The translation between type loader data structures and reflection data structures is always going to add non-trivial cost.

> @Maoni0 And 15,4% for GC is also a lot, isn't it?

This is cost of transitioning between thread modes. Not much to do with GC.

**Comment by jkotas** [comment]
> I would naively expect that the generic definition of a type is stored in a field of the constructed type

The type loader does not need to materialize the generic type definition for code execution. The generic type definition is materialized by the type loader only for abstract things like reflection.

BTW: It is possible to go even further, stop materializing generic type definition as runtime type and turn generic type definitions into a reflection-only concept. It is how it works in native aot.

**Comment by steveharter** [comment]
[israellot](https://github.com/israellot) thanks for the suggestion and information. We'll consider this for 8.0.

> This method in particular is used a lot by serializers. I actually figured out analyzing json.net library. I imagine it could be an interesting improvement.

I can see why serializers would need to do this to identify certain generic collections, for example. However, it also seems like that information, or the end result, would normally be cached by the serializer.

**Comment by NinoFloris** [comment]
Dapper also ends up calling this a lot, for instance through Nullable.GetUnderlyingType.

See LookupDbType for all cases, this is called per parameter, for every execution.
https://github.com/DapperLib/Dapper/blob/b272cc664d933b4b65703d26a79272d549576dff/Dapper/SqlMapper.cs#L365

**Comment by steveharter** [comment]
Just a note for potential implementation: we should be able to keep the size of `System.Type` the same by using this existing field which is used to cache information for special types:

https://github.com/dotnet/runtime/blob/f52d8c59bb49360eb2cbeeb863c5856ebd62adda/src/coreclr/System.Private.CoreLib/src/System/RuntimeType.CoreCLR.cs#L1492
