### ISSUE TITLE
[wasm] warning WASM0001: Could not get pinvoke, or callbacks for method 'EnumUILanguages' because 'Parsing function pointer types in signatures is not supported.'

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#73880]
Repro:

build wasm (I built commit e94f7ceb73244d9c4bf7a0d38fb59d01e300ef00), run the `System.Runtime` tests:
```
./build.sh --os browser -c Release
./dotnet.sh build /t:Test /p:TargetOS=Browser /p:TargetArchitecture=wasm /p:RunAOTCompilation=true -c Release src/libraries/System.Runtime/tests
```

result - success, but during compilation we see:
```
  [195/195] System.Runtime.Tests.dll -> System.Runtime.Tests.dll.bc
warning WASM0001: Could not get pinvoke, or callbacks for method 'EnumUILanguages' because 'Parsing function pointer types in signatures is not supported.'
```

**Comment by lambdageek** [comment]
This might be harmless... It's a DllImport from kernel32 which isn't a thing on WASM

**Comment by radical** [comment]
> ` Could not get pinvoke, or callbacks for method 'EnumUILanguage`
Also, @maraf, this should show the full type also. I'm guessing that this fails to get the parameters, so we can't show that anyway.

**Comment by maraf** [comment]
> This might be harmless... It's a DllImport from kernel32 which isn't a thing on WASM

The usage of the DllImport is guarded by the `OperatingSystem.IsWindows()` condition, anyway the pinvoke generator still see it and tries to generate a trampoline. It was always there, I only made it more visible in the https://github.com/dotnet/runtime/pull/71477.

**Comment by lambdageek** [comment]
oh, I missed that that's in the test assembly, not in the libraries.

I think we can close this.

**Comment by radical** [comment]
> I think we can close this.

Closing.
