### ISSUE TITLE
Performance has doubled since a couple of days ago.

### ISSUE THREAD

**Issue by tactical-drone** [dotnet/runtime#73891]
According to my numbers since 7.0.100-rc.1.22412.1 my performance doubled.

Can this be?

I need to know maybe I broke something. The runtime has since forever had a hot (contested from many CPU) locking speed limit of ~`28, 000 FPS`. Now it is ~`54, 000 FPS`. Either I broke something or something spectacular has taken place inside the runtime. I would love to know, or I will have to walk back changes.

**Comment by EgorBo** [comment]
@tactical-drone what is the latest SDK version you used where you had lower FPS?

**Comment by tactical-drone** [comment]
@EgorBo Its on a AMD 3950x

I am not sure, it felt like the change came in over a nuget update from `<add key="dotnet7" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json" />`

It happened like yesterday during development. I am still a little bit confused. Everything was working, then everything broke. So I had to start from basics again, but this time performance went sky high. 

I am very sure it is near or around the version stated above, 7.0.100-rc.1.22412.1, the one that broke `Task.Unwrap` completely.

**Comment by stephentoub** [comment]
When you profile your app, is there a particular method consuming a significant percentage of the time?

**Comment by tactical-drone** [comment]
@stephentoub No.

I think I know now what happened. 2 things:

1. Performance suddenly doubled
2. My program hung.

After further debugging today I located the problem:

`Awaiting	System.Threading.Tasks.UnwrapPromise<TResult>.Invoke(completingTask)`

The debugger says it is waiting for task 37, which if I click on it is the first line of my closure.

```
var testTask = Task.Factory.StartNew(async () =>
(*){
   //TODO: control does not reach here always. Different values to my scheduler HEAP buffer `Capacities` would influence the outcome here, but had no bearing on what is going on here. This seemed like a critical failure.
    await SemTestAsync();
    //await QueueTestAsync();
    //await ZeroQTestAsync();
    //await BagTestAsync();
}, CancellationToken.None, TaskCreationOptions.DenyChildAttach, IoZeroScheduler.ZeroDefault).Unwrap();
```
The rest of my program seems to still work, with `Unwrap`. But those `Task.Factory.StartNew`s are being called from an async context. The one above, is executing from main and broke yesterday. Replacing with

```
var j = new JoinableTaskFactory(new JoinableTaskContext());
{
   var t = j.RunAsync(async () =>
   {
      await SemTestAsync();
      //await QueueTestAsync();
      //await ZeroQTestAsync();
      //await BagTestAsync();)
   });
   t.Join();
}
```

IMO `Unwrap` is broken from non async contexts now. 

CAUTION!!!!

Note I am using a custom scheduler there so. I think I got the custom scheduler down, but I would understand if you were skeptical. There be dragons. What I could see is `protected override void QueueTask(Task task)` is never called after doing the `Task.Factory.StartNew`. As mentioned before, debugging it led to my "main" thread being bricked on startup by that `Awaiting	System.Threading.Tasks.UnwrapPromise<TResult>.Invoke(completingTask)` awaiting another task that is the at (`*`) with a blue exclamation mark in the IDE which I don't know what that means. 

Please let me know if you don't understand some of my explanations. I am trying to keep it brief.

**Comment by stephentoub** [comment]
> IMO Unwrap is broken from non async contexts now.

Nothing has changed here. You will need to provide a concise isolated repro for us to be able to help further.

**Comment by tactical-drone** [comment]
> 

Fascinating. 

What is even more fascinating is how it broke. I installed the nightly, developed a bit. All was well. Then at the end I was doing the basic house keeping stuff, like bumping nugets. Then while doing regfactoring cleanup in preparation for the commit everything just broke. Stashing my changes did not work. The problem was in the runtime.

**Comment by tactical-drone** [comment]
Update.

A complete fresh checkout in a completely new directory works. This explains why my stashing changes step might not have worked. I am starting to think the compiler left artifacts in the original work `dir` that broke everything.

**Comment by tactical-drone** [comment]
Ok so I think the compiler broken in a recent version. 

The IDE is not happy most of the time, many crashes etc. Code won't build. The errors I am seeing is severe enough that you guys should pick it up too.

**Comment by stephentoub** [comment]
@tactical-drone, again, we'd need an isolated repro.  Just saying the compiler is broken isn't something we can act on.  And if this is about the C# compiler, that should be handled with an issue in the dotnet/roslyn repo instead.

I'm going to close this issue, as there's nothing we can actually follow-up on here.

Thanks.

**Comment by tactical-drone** [comment]
@stephentoub Sounds good.

BTW you were asking about `When you profile your app, is there a particular method consuming a significant percentage of the time?`

I am seeing strange things in my task manger now. Never seen anything like it, I can just post a picture.

![image](https://user-images.githubusercontent.com/1815319/184535779-7c658795-b6e7-4ca9-960d-d7deb238af38.png)

**Comment by tactical-drone** [comment]
@stephentoub Just FYI. I figured out what the problem was. My scheduler was being boostrap from a static constructor that was affected by timing issues because of the framework upgrades. What caused the compiler issues with it, I have no idea.
