### ISSUE TITLE
ChannelReader documentation error

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#73904]
See this link:

https://docs.microsoft.com/en-us/dotnet/api/system.threading.channels.channelreader-1.waittoreadasync?view=net-6.0#system-threading-channels-channelreader-1-waittoreadasync(system-threading-cancellationtoken)

The documentation incorrectly stated that the return type is a valuetask tresult that is either true or false. It should be a valuetask bool.

**Comment by stephentoub** [comment]
Can you please quote the exact text you briefcase to be incorrect?

**Comment by stephentoub** [comment]
Oh, you're referring to it rendering as TResult in the text instead of the more specific bool? Feel free to open an issue on the docs repo.
