### ISSUE TITLE
Configuration binding swallows the conversion exception

### ISSUE THREAD

**Issue by jvmlet** [dotnet/runtime#73915]
### Description

Configuration binding still swallows the conversion exception  (#36502 ,#36129 and #36015 are still reproducible with `6.0.0`,  )

### Reproduction Steps

``` c#
public enum  Ingredients {
A,
B
}

public class  MyModel{
public  Ingredients[] {get;set;}
}
```
Starting the app with  `myapp.exe --MyModel:Ingredients:0 A --MyModel:Ingredients:1 C` starts up with `Ingredients == [A]`

### Expected behavior

Exception should be thrown when calling `iConfiguration.GetSection("MyModel").Bind(new MyModel(),opts => opts.ErrorOnUnknownConfiguration = true))`

### Actual behavior

application starts with `Ingredients == [A]`

### Configuration

`net5.0` , `   <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="6.0.0" />`

### Other information

(https://github.com/dotnet/runtime/blob/c0dabb527176d1fdb6ba7bdca75fd80d69482be2/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L543)

**Comment by tarekgh** [comment]
Looks there are some places in the ConfigurationBinder.cs which we swallow the exception. We may consider using `BinderOptions.ErrorOnUnknownConfiguration` in such places and allow throwing there. 

https://github.com/dotnet/runtime/blob/8be2105118b3743a968fd9b8ad4d0c490172b7ca/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L614
https://github.com/dotnet/runtime/blob/8be2105118b3743a968fd9b8ad4d0c490172b7ca/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L647
https://github.com/dotnet/runtime/blob/8be2105118b3743a968fd9b8ad4d0c490172b7ca/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L696
https://github.com/dotnet/runtime/blob/8be2105118b3743a968fd9b8ad4d0c490172b7ca/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L755

We may consider the fix in the future releases.

**Comment by jvmlet** [comment]
Is there **NEAREST** Future milestone ?
You ship the application documenting all the configuration options and have no chance to validate them at runtime.
No observability at all 
Sounds like a **blocker issue.**
BTW, don't you have static code analysis  as build-pipeline step ? Sonar has no issue to catch this violation 
![image](https://user-images.githubusercontent.com/6664858/184803352-e64ae4c1-d908-4406-9656-037345d2100e.png)

**Comment by fnajera-rac-de** [comment]
I just wasted 4 hours debugging until I arrived at this issue. I agree with @jvmlet that this should be a blocker and at the very minimum a binding option should be provided to fail on children error.

**Comment by jvmlet** [comment]
@tarekgh , would you please prioritize it ?

**Comment by tarekgh** [comment]
@jvmlet I marked with the next release milestone. Are you interested to submit a PR for it?

**Comment by SteveDunn** [comment]
I'm happy to look at this as I vageuly remember adding `ErrorOnUnknownConfiguration`. I'm guessing there's no real urgency for this as time is a bit short at the moment.

**Comment by SteveDunn** [comment]
The comments for `ErrorOnUnknownConfiguration` say:

```csharp
/// <summary>
/// When false (the default), no exceptions are thrown when a configuration key is found for which the
/// provided model object does not have an appropriate property which matches the key's name.
/// When true, an <see cref="System.InvalidOperationException"/> is thrown with a description
/// of the missing properties.
/// </summary>
```

So, technically, in this case, the key exists, and the config exists, so 🙈 

Of course, that config option implies that an error should be thrown, not just on missing properties in config, but also _invalid_ properties in config.

By making `ErrorOnUnknownConfiguration` dual-purpose might now introduce unexpected breaking changes.

Maybe we need another property named `ErrorOnInvalidConfiguration`.

What do you think? Would this require another API Proposal?

**Comment by tarekgh** [comment]
I don't think we need to complicate the options by adding one more property like that. We can use `ErrorOnUnknownConfiguration` and clarify the documentation. Yes, it will be a breaking change, but I don't think anyone using `ErrorOnUnknownConfiguration` was not trying to catch all thrown exception when loading the configuration. Let me know if you think otherwise.

**Comment by tarekgh** [comment]
This is already done by the PR https://github.com/dotnet/runtime/pull/77708
