### ISSUE TITLE
Parsing NumberStyles.HexNumber with "0x" prefix fails

### ISSUE THREAD

**Issue by cove** [dotnet/runtime#73924]
### Description

Unable to parse numbers such as 0xed, despite using NumberStyles.HexNumber and the [docs ](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.numberstyles?view=net-6.0#fields)"Strings that are parsed using this style cannot be prefixed with "0x" or "&h". "

### Reproduction Steps

```
using System;

public class Program
{
	public static void Main()
	{
		string hex = "0xed";
		int intValue = int.Parse(hex, System.Globalization.NumberStyles.HexNumber);
		Console.WriteLine($"{intValue}");	
	}
}
```

### Expected behavior

The number is parsed without throwing an exception.

### Actual behavior

An exception is thrown:
```
Unhandled exception. System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Int32.Parse(String s, NumberStyles style)
   at Program.Main()
Command terminated by signal 6
```

### Regression?

Not sure.

### Known Workarounds

Omit 0x from the hex numbers, but then it's not a standard format for hex, so it's possible someone could think the string is dec instead of hex without the 0x. And &number looks like an address to C++ devs, so 0x is really better.

### Configuration

.Net 6 Windows 10 x64

### Other information

Seems like either the docs should be updated or the code.

**Comment by stephentoub** [comment]
> Seems like either the docs should be updated or the code.

> the [docs ](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.numberstyles?view=net-6.0#fields)"Strings that are parsed using this style cannot be prefixed with "0x" or "&h". "

Which aspect of the cited docs is incorrect?

**Comment by cove** [comment]
Oh I read that backwards, I read it as saying 0x was supported, instead of not supported.
