### ISSUE TITLE
Determinism for NativeAOT

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#73931]
Deterministic binaries should be supported for NativeAOT and we should have tests.

In short, the feature is that identical inputs to the exact same compiler toolchain should produce bit-for-bit identical results.

**Comment by MichalStrehovsky** [comment]
We produce deterministic object files, but the linker then messes it all up with timestamps and GUIDs, so there's well understood diffs in the final output. The VC++ team has been dragging their feet adding support for this: https://developercommunity.visualstudio.com/t/support-for-cls-experimentaldeterministic-becoming/426033

Experimentally adding `/EXPERIMENTAL:DETERMINISTIC` to the linker command line produces even more diffs so there's probably a secret handshake with cl that we'll need to reproduce.

I'm reluctant adding undocumented link.exe switches to our targets. We need to revisit in 8.0 and we likely need a link.exe feature. I'm starting an email thread.

**Comment by MichalStrehovsky** [comment]
The diffs are possible to patch out. A tool like this could be used: https://github.com/jasonwhite/ducible (Haven't actually tried)

**Comment by MichalStrehovsky** [comment]
It was pointed out to me by someone over email that when link.exe is passed a res file, it will run cvtres to generate an obj file with a random name and the random name messes up some of the determinism. So we might need to fix #79634 to help the determinism. We're still limited by what link.exe can do though.

**Comment by agocke** [comment]
Moving to `future` as we're fundamentally constrained on Windows
