### ISSUE TITLE
[dotnet-sdk-7.0.100-rc.1.22413.1] When calling Socket.EndReceiveFrom method throws SocketException in .NET 7.0 but throws ObjectDisposedException in .NET 6.0

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/runtime#73936]
### Description

When running the 3rd party app with latest .NET 7 RC build, it gets System.ObjectDisposedException when closing socket

### Reproduction Steps

**Repro steps for app:**
**The machine only has dotnet-sdk-7.0.100-rc.1.22413.1 installed and DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX environment variable set as 2.**

1. Copy app from SourceShare\InputShare to local machine.
2. Launch Inputshare.exe.
3. Click "Server" button.
4. Click "Start" button.
5. Click "Stop server" button.

### Expected behavior

App returns to the Start server window without app crash.

### Actual behavior

App crashes with following error:
```
Object name: 'System.Net.Sockets.Socket'.
Verbose:    at System.Net.Sockets.Socket.BeginReceiveFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint& remoteEP, AsyncCallback callback, Object state)
   at InputshareLib.Server.ISUdpServer.SocketReceiveFromCallback(IAsyncResult ar) in C:\Users\Sam\Documents\Inputshare\InputshareLib\Server\ISUdpServer.cs:line 57
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Verbose: System.Private.CoreLib
Verbose: --------------------------------------
Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.BeginReceiveFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint& remoteEP, AsyncCallback callback, Object state)
   at InputshareLib.Server.ISUdpServer.SocketReceiveFromCallback(IAsyncResult ar) in C:\Users\Sam\Documents\Inputshare\InputshareLib\Server\ISUdpServer.cs:line 57
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

### Regression?

Yes
**Verify Scenarios:**
1). Windows rs5 x64 + dotnet-sdk-7.0.100-rc.1.22413.1: Fail
2). Windows10 RS5 x64+dotnet-sdk-7.0.100-rc.1.22408.5: Pass
3). Windows10 RS5 x64+dotnet-sdk-3.1.422-win-x64: Pass
4). Windows10 RS5 x64+dotnet-sdk-3.0.103-win-x64: Pass

### Configuration

**Application Name**:  Inputshare
**OS**: Windows 10 RS5
**CPU**: X64
**.NET Build Number**: dotnet-sdk-7.0.100-rc.1.22413.1

**App or App Source checking at**: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1592646

### Other information

**Minimal Repro steps with sample app**:

1.Create a .NET 7.0 WPF app with default project template.
2. Open MainWindow.xaml and drag two buttons to the window and change the button's Content as "Start" and the button1's Content as "Stop".
3. Double click two buttons to generate button_Click() and button1_Click() methods.
4. Add following code to MainWindow.xaml.cs:
```c#
private Socket udpSocket;
private byte[] readBuff = new byte[4096];
private EndPoint _recvAddrBuffer = new IPEndPoint(IPAddress.Any, 0);

public MainWindow()
{
            InitializeComponent();
}

private void button_Click(object sender, RoutedEventArgs e)
{
            udpSocket = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);
            udpSocket.Bind(new IPEndPoint(IPAddress.Any, 4441));
            udpSocket.BeginReceiveFrom(readBuff, 0, readBuff.Length, 0, ref _recvAddrBuffer, SocketReceiveFromCallback, null);
            button.Content = "Started";
}

private void SocketReceiveFromCallback(IAsyncResult ar)
{
            try
            {
                int bytesIn = udpSocket.EndReceiveFrom(ar, ref _recvAddrBuffer);
                
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
                MessageBox.Show(ex.StackTrace);
            }
}

private void button1_Click(object sender, RoutedEventArgs e)
{
            udpSocket.Dispose();
            
}
```
6. Press F5 to launch the app in Visual Studio.
7. Click "Start" button and the button content becomes "Started".
8. Click "Stop" button.

**Excepted Result**:
App pops up "System.ObjectDisposedException: 'Cannot access a disposed object.'" exception.

**Actual Result**:
App get "The I/O operation has been aborted because of either a thread exit or an application request" exception.

Stack Trace:
```
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Net.Sockets.SocketReceiveFromResult>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskToApm.End[TResult](IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndReceiveFrom(IAsyncResult asyncResult, EndPoint& endPoint)
   at WpfApp2.MainWindow.SocketReceiveFromCallback(IAsyncResult ar) in E:\App Source\WpfApp2\MainWindow.xaml.cs:line 46
```
**Findings:**
In .NET 6.0, Socket.EndReceiveFrom() method will throw ObjectDisposedException when socket is disposed. But in .NET 7.0, Socket.EndReceiveFrom() method will throw SocketException.

We found this pull request related to ObjectDisposedException was changed recently.
https://github.com/dotnet/runtime/pull/73335

@dotnet-actwx-bot @dotnet/compat

**Comment by stephentoub** [comment]
Yes, this is because of https://github.com/dotnet/runtime/pull/73335.

This repro code is broken.  If the EndXx method throws an exception, the implementation shouldn't eat it and proceed to issue another receive, regardless of whether the exception was an ObjectDisposedException.

We discussed whether #73335 should be marked as a breaking change and I'd argued it didn't need to be because we don't consider it to be "breaking" to remove an exception throw and we could wait for evidence.  Obviously some apps though are depending on this ObjectDisposedException being thrown.  So, maybe we should treat it as "breaking".

cc: @antonfirsov

**Comment by Junjun-zhao** [comment]
> Yes, this is because of #73335.
> 
> This repro code is broken. If the EndXx method throws an exception, the implementation shouldn't eat it and proceed to issue another receive, regardless of whether the exception was an ObjectDisposedException.
> 
> We discussed whether #73335 should be marked as a breaking change and I'd argued it didn't _need_ to be because we don't consider it to be "breaking" to remove an exception throw and we could wait for evidence. Obviously some apps though are depending on this ObjectDisposedException being thrown. So, maybe we should treat it as "breaking".
> 

> cc: @antonfirsov

Thanks for your quick reply. Yes. We have done some little change to the demo.  In .NET 6.0, Socket.EndReceiveFrom() method will throw ObjectDisposedException when socket is disposed. But in .NET 7.0, Socket.EndReceiveFrom() method will throw SocketException.

**Comment by stephentoub** [comment]
> But in .NET 7.0, Socket.EndReceiveFrom() method will throw SocketException.

Right,  the code was effectively:
```
if (socket is disposed) throw object disposed exception;
if (operation failed) throw exception that caused it to fail;
```
We removed the first line to avoid throwing the disposed exception,  so you're now seeing the actual result of the operation.

The repro code is both ignoring an exception and using an object after it's been disposed.  Both are improper.

**Comment by Junjun-zhao** [comment]
That make sense. We will share the information to the customer to update their code.
Can you confirm whether team will create a breaking change document for this?

**Comment by Junjun-zhao** [comment]
@CarnaViire Can you please confirm if the breaking change document has been created for this issue? Thanks.

**Comment by rzikm** [comment]
@Junjun-zhao AFAIK the document wasn't created yet, it is on our todo list

**Comment by antonfirsov** [comment]
Opened https://github.com/dotnet/docs/issues/30977 and will file a dotnet-api-docs PR to document the changes.

**Comment by Junjun-zhao** [comment]
Thank you very much for your update!
