### ISSUE TITLE
Open up internal JsonConfigurationFileParser to be public

### ISSUE THREAD

**Issue by grrttedwards** [dotnet/runtime#73946]
## Background and Motivation

I would like to consume JSON-string values from files written to the filesystem, and flatten them into the format that the configuration system understands. For example: `{"foo":["bar1","bar2"]}` cannot be understood by or bound to POCO's unless the keys are mapped into the config dictionary like `"foo:0" = "bar1"` and `"foo:1" = "bar2"`.

This functionality is already written in the `internal sealed JsonConfigurationFileParser`, but can't be used.

Other projects have had to implement their own flattening logic, e.g. here: https://github.com/Kralizek/AWSSecretsManagerConfigurationExtensions/blob/master/src/Kralizek.Extensions.Configuration.AWSSecretsManager/Internal/SecretsManagerConfigurationProvider.cs#L104-L154

This has been historically discussed once here: https://github.com/dotnet/extensions/issues/1074 however this does not provide exactly what's being asked for here.

## Proposed API

```diff
namespace Microsoft.Extensions.Configuration.Json
{
-    internal sealed class JsonConfigurationFileParser
+    public sealed class JsonConfigurationFileParser
    {

...

        public static IDictionary<string, string?> Parse(Stream input)
            => new JsonConfigurationFileParser().ParseStream(input);
```

## Usage Examples

In a configuration provider (very roughly):

```csharp
public class JsonFlatteningKeyPerFileConfigurationProvider : ConfigurationProvider
{
...
    private void Load(bool reload)
    {
        foreach (var file in Source.directory)
        {
            using fileStream = file.CreateReadStream();
            var flattenedJson = JsonConfigurationFileParser.Parse(fileStream);
            Data = Data.Concat(flattenedJson).ToDictionary(kvp => kvp.Key, kvp => kvp.Value);
        }
```

## Alternative Designs

Example user who could be using this public API: https://github.com/Kralizek/AWSSecretsManagerConfigurationExtensions/blob/master/src/Kralizek.Extensions.Configuration.AWSSecretsManager/Internal/SecretsManagerConfigurationProvider.cs#L104-L154

## Risks

Best discussed by the experts here, as to why this class has been left internal.

**Comment by davidfowl** [comment]
Copy the source? It's ~100 lines of code.

**Comment by grrttedwards** [comment]
@davidfowl I have for now, just would prefer not to have to copy the source -- provided there's not a good reason not to expose this class.

**Comment by davidfowl** [comment]
I don’t see a reason to expose it. It’s an implementation detail.

**Comment by eerhardt** [comment]
I'm going to close this issue as "not planned". New public APIs are expensive (to create, test, doc, maintain, etc.) and need strong justification for making a new one. Helper functionality typically isn't exposed publicly unless there is a strong justification.

You can consider inheriting from `JsonConfigurationProvider` or `JsonStreamConfigurationProvider` if you really don't want to copy and modify the source to meet your needs.
