### ISSUE TITLE
Visual Studio 2022 Remote Testing -.NET Framework 4.8 is installed, yet the.NET cannot be found during testing.

### ISSUE THREAD

**Issue by BarPupko** [dotnet/runtime#73940]
### Description

I am trying a new feature on a Visual Studio called "remote testing", I install Docker and started a new project of "xunit" or "nunit" after initialize the project, I try to run the tests on my machine first, and it succeeds.

[setting to use docker][1]

[Xunit][2]

[Nunit][3]

When I try to start the test on the Linux environment, I get the next message that I don't have a .NET on my machine, although I do have.

[.NET not installed][4]

I tried looking for an answer to this issue, tried installing the .NET from installer and tried downloading the SDK, but nothing so far.
I find a resemblance between my issue and [this post][5], but It didn't help me either.
Hope you can help me.

### Reproduction Steps

**What I tried?**
* install several images from docker that include Linux
* tried to run it on Visual Studio Pro 2022/2019 , Visual Studio Community.
* tried to check if I have an .NET version on my machine. Using this [documnatation][6]
* tried to uninstall all programs and install
* tried to uninstall all dotnet versions and install again.
* tried to install .net using [runtime][7].

  [1]: https://i.stack.imgur.com/BgZpN.png

  [2]: https://i.stack.imgur.com/NOzph.png

  [3]: https://i.stack.imgur.com/r151o.png

  [4]: https://i.stack.imgur.com/mmCop.png

  [5]: https://stackoverflow.com/questions/72318242/net-framework-4-8-is-installed-but-not-showing-in-visual-studio-2019-community

  [6]: https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed

  [7]: https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime

### Expected behavior

expected behaviour is that the test can run on linux docker image and returen with results

### Actual behavior

when trying to start test using ssh , I got the next error:
`streamJsonRPpc.RemoteInvocationException: Test enviroment is missing required prerequisites. libfuse3 must be installed`

and after checking and installing still no effect.

### Regression?

yes I tried to install and uninstall still got the 'issue' 
```
This remote runtime environment is missing prerequisites (.NET/vsdbg or related tooling) required to discover/run/debug tests. Attempting to install them automatically. More details can be found at https://aka.ms/remotetesting
=========================== Installing .NET runtime ===========================
: Information: Install Unit Testing Prerequisites script
: Information: dotnet not installed
: Information: Installing curl

### Known Workarounds
```

Visual Studio 2022
Visual Studio 2019

### Configuration

```
3.1.422 [C:\Program Files\dotnet\sdk]
5.0.411 [C:\Program Files\dotnet\sdk]
6.0.400 [C:\Program Files\dotnet\sdk]

dotnet version
6.0.400


.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400\

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  3.1.422 [C:\Program Files\dotnet\sdk]
  5.0.411 [C:\Program Files\dotnet\sdk]
  6.0.400 [C:\Program Files\dotnet\sdk]

```
```
.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

### Other information

```
_No response_

**Comment by jeffschwMSFT** [comment]
@BarPupko can you file this issue via VS Feedback?  That is the best way to get this feedback to the right team.  Please post the issue back here.  Thanks

**Comment by BarPupko** [comment]
> @BarPupko can you file this issue via VS Feedback? That is the best way to get this feedback to the right team. Please post the issue back here. Thanks
Hi, jeff.
I can't add a label or redirect the issue.

**Comment by jeffschwMSFT** [comment]
Sorry, what I meant is file a feedback item in Visual Studio.  Then you can add a comment with the link to the issue on https://developercommunity.visualstudio.com/.

**Comment by BarPupko** [comment]
OK Jeff ,Thank you , I will post my issue there,hope someone in the vs team will answer me.
have a great day.
I think you can close this Issue.

**Comment by BarPupko** [comment]
OK Jeff ,Thank you , I will post my issue there,hope someone in the vs team will answer me.
have a great day.
I think you can close this Issue.

**Comment by jeffschwMSFT** [comment]
Thanks.  Please link the issue back to this issue and we can check on it internally.
