### ISSUE TITLE
.NET 6 and .NET Framework 4.8.1 return different value for `OSArchitecture` when running emulated as x86 

### ISSUE THREAD

**Issue by richlander** [dotnet/runtime#73974]
Update: Looks like .NET 7 and .NET Framework 4.8.1 have the expected behavior and .NET 6 differs. Seems like we'll need to leave that behavior as-is at this point. This situation should be documented as a known issue and breaking change.

Intentional? Bug?

> Hmmm. That's interesting. OSArchitecture is reported differently for .NET 6 and .NET Framework 4.8.1 when running x86 apps. .NET Framework and .NET 6 use different Windows APIs to report OSArchitecture. They don't all report the same thing.

See: https://github.com/dotnet/core/issues/7709

.NET 6:

```bash
C:\Users\rich\git\dotnet-docker\samples\dotnetapp>dotnet run -a x86
         42
         42              ,d                             ,d
         42              42                             42
 ,adPPYb,42  ,adPPYba, MM42MMM 8b,dPPYba,   ,adPPYba, MM42MMM
a8"    `Y42 a8"     "8a  42    42P'   `"8a a8P_____42   42
8b       42 8b       d8  42    42       42 8PP"""""""   42
"8a,   ,d42 "8a,   ,a8"  42,   42       42 "8b,   ,aa   42,
 `"8bbdP"Y8  `"YbbdP"'   "Y428 42       42  `"Ybbd8"'   "Y428

.NET 6.0.8
Microsoft Windows 10.0.22621

OSArchitecture: X64
ProcessArchitecture: X86
ProcessorCount: 8
TotalAvailableMemoryBytes: 2.00 GiB
```

.NET 7:

```bash
C:\Users\rich\git\dotnet-docker\samples\dotnetapp>dotnet run -a x86
         42
         42              ,d                             ,d
         42              42                             42
 ,adPPYb,42  ,adPPYba, MM42MMM 8b,dPPYba,   ,adPPYba, MM42MMM
a8"    `Y42 a8"     "8a  42    42P'   `"8a a8P_____42   42
8b       42 8b       d8  42    42       42 8PP"""""""   42
"8a,   ,d42 "8a,   ,a8"  42,   42       42 "8b,   ,aa   42,
 `"8bbdP"Y8  `"YbbdP"'   "Y428 42       42  `"Ybbd8"'   "Y428

.NET 7.0.0-preview.7.22375.6
Microsoft Windows 10.0.22621

OSArchitecture: Arm64
ProcessArchitecture: X86
ProcessorCount: 8
TotalAvailableMemoryBytes: 2.00 GiB
```

.NET Framework 4.8.1:

```bash
C:\Users\rich\git\dotnet-framework-docker\samples\dotnetapp>dotnet run -a x86
                                 ad88
                        ,d      d8"
                        88      88
8b,dPPYba,   ,adPPYba, MM88MMM MM88MMM 8b,     ,d8
88P'   `"8a a8P_____88   88      88     `Y8, ,8P'
88       88 8PP"""""""   88      88       )888(
88       88 "8b,   ,aa   88,     88     ,d8" "8b,
88       88  `"Ybbd8"'   "Y888   88    8P'     `Y8

.NET Framework 4.8.9065.0
Microsoft Windows 10.0.22621

OSArchitecture: Arm64
ProcessArchitecture: X86
ProcessorCount: 8
```

**Comment by AntonLapounov** [comment]
Hmm, according to my old issue #26612, it used to return `OSArchitecture: X86`.

**Comment by danmoseley** [comment]
.NET Framework through .NET 6 get OSArchitecture from wProcessorArchitecture out of GetNativeSystemInfo.

In .NET 7 [this changed ](https://github.com/dotnet/runtime/pull/60910) to use IsWow64Process2 if available, otherwise fall back to the previous method.  (Aside, it seems inconsistent that if IsWow64Process2 is found but fails, we [fall back](https://github.com/dotnet/runtime/blob/53312adb2873114a8a7f4ccd9351acc9d50bc270/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/RuntimeInformation.Windows.cs#L57) to preprocessor define, rather than GetNativeSystemInfo -- @am11  was that intentional?). I don't have a machine to try, but I'd expect .NET 7 to return 'Arm64'.

Docs for GetNativeSystemInfo says this

> If the function is called from an x86 or x64 application running on a 64-bit system that does not have an Intel64 or x64 processor (such as ARM64), it will return information as if the system is x86 only if x86 emulation is supported (or x64 if x64 emulation is also supported).

That's rather unclear. In https://github.com/dotnet/runtime/issues/26612 Anton observed that x86 emulated on Windows Arm64 returned X86. In the same issue, another poster observed that after x64 emulation was added in 21277, Windows began to return X64.

So what you see on .NET 6 is explained, but what you see on .NET Framework is not. Did it switch to using IsWow64Process2? I am looking at /DevDiv/FX/Rel/Net481Rel1/NDP/clr/src/BCL/System/Runtime/InteropServices/RuntimeInformation/RuntimeInformation.cs and it does not seem to be.

**Comment by am11** [comment]
> @am11 was that intentional?

I think the idea was to use new API and fallback consistently on the Windows versions which support `IsWow64Process2` (1511 onwards). Thus, both `isWow64Process2()` and `MapMachineConstant()` fallback to `ProcessArchitecture`.

**Comment by richlander** [comment]
I tested .NET 7. It matches .NET Framework 4.8.1 behavior. I updated the bug. Seems like this behavior needs to be documented as a known issue and (good) breaking change. Fair?

**Comment by danmoseley** [comment]
Well I'm still wondering why you are seeing the .NET Framework result.

**Comment by richlander** [comment]
I just re-ran the .NET Framework sample and it is the same (just to double-check).

**Comment by AaronRobinsonMSFT** [comment]
> Seems like this behavior needs to be documented as a known issue and (good) breaking change. Fair?

@richlander Are the thoughts here in the official "Release Notes" or in the official documentation for `OSArchitecture` or both?

**Comment by danmoseley** [comment]
I think it is worth documenting in both.

**Comment by AaronRobinsonMSFT** [comment]
@danmoseley @richlander Please review https://github.com/dotnet/dotnet-api-docs/pull/8312

**Comment by richlander** [comment]
Looks good. Thanks for doing that!

**Comment by AaronRobinsonMSFT** [comment]
Since tags for breaking changes were added to #60910, I think we can close this issue. Please let me know if I am mistaken.

**Comment by danmoseley** [comment]
@jkotas  any idea why .NET Framework shows what it does?

**Comment by jkotas** [comment]
> @jkotas any idea why .NET Framework shows what it does?

The best way to tell would be to step through the code using windbg. My guess is that .NET Framework gets a quirked version of the `GetNativeSystemInfo` that returns `PROCESSOR_ARCHITECTURE_ARM64` in emulated processes.

**Comment by danmoseley** [comment]
Ah - yes, that's likely there's some quirk. Thanks. No need to investigate, I think.
