### ISSUE TITLE
[NativeAot] Devirtualization opportunity around field loads

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#74000]
Notice the first interface call is not devirtualized, only the second, after storing to a local.

```csharp
using System;
using System.Runtime.CompilerServices;

interface IFoo
{
    void Frob();
}

class Program : IFoo
{
    static IFoo theFoo = new Program();

    public void Frob() => Console.WriteLine("Hello");

    [MethodImpl(MethodImplOptions.NoInlining)]
    static void Main()
    {
        theFoo.Frob();
        IFoo i = theFoo;
        i.Frob();
    }
}
```

```fasm
00007FF796607C10 56                   push        rsi  
00007FF796607C11 48 83 EC 20          sub         rsp,20h  
00007FF796607C15 E8 8B A8 D4 FF       call        __GetGCStaticBase_repro_Program (07FF7963524A5h)  
00007FF796607C1A 48 8B F0             mov         rsi,rax  
00007FF796607C1D 48 8B 4E 08          mov         rcx,qword ptr [rsi+8]  
00007FF796607C21 4C 8D 15 A8 EC 27 00 lea         r10,[__InterfaceDispatchCell_repro_IFoo__Frob_repro_Program__Main (07FF7968868D0h)]  
00007FF796607C28 41 FF 12             call        qword ptr [r10]  
00007FF796607C2B 48 8B 4E 08          mov         rcx,qword ptr [rsi+8]  
00007FF796607C2F 38 09                cmp         byte ptr [rcx],cl  
00007FF796607C31 48 8D 0D 30 47 26 00 lea         rcx,[__Str_Hello (07FF79686C368h)]  
00007FF796607C38 E8 13 26 00 00       call        System_Console_System_Console__WriteLine_12 (07FF79660A250h)  
00007FF796607C3D 90                   nop  
00007FF796607C3E 48 83 C4 20          add         rsp,20h  
00007FF796607C42 5E                   pop         rsi  
00007FF796607C43 C3                   ret  
```

Cc @EgorBo

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky is there any known build issues for NativeAOT in Main - for some reason I can't run ilc from VS, it throws

Weird, I see this too.

I narrowed this down to #73987. If I comment out the `<PublishSingleFile>` line debugging works again.

@dotnet/dotnet-diag is it known that `<PublishSingleFile>` in the project file would break debugging in VS? We're using Preview 7 in the repo.

The repro steps are:
1. Build at least the clr.aot subset of the repo (e.g. `build.cmd clr.aot -rc Debug -lc Release`, but if you build all of `clr`, that's fine too)
2. Open the src\coreclr\tools\aot\ilc.sln solution in VS.
3. Choose the configuration you built (Debug in my case)
4. Hit F5 to run under debugger.

**Comment by noahfalk** [comment]
@mikem8361 should probably take a look

Mike and Juan did work earlier in this release to make single file debugging work so no, I wouldn't expect it to be failing here.

**Comment by MichalStrehovsky** [comment]
I'm submitting a workaround for the debugging issue in https://github.com/dotnet/runtime/pull/74138.

**Comment by hoyosjs** [comment]
VS merged support for it - I'm not sure if it's made it's way to public previews yet.
