### ISSUE TITLE
Access Violation in CastHelpers.ChkCastClassSpecial

### ISSUE THREAD

**Issue by elliottp6** [dotnet/runtime#74005]
### Description

I received this error the other night after hundreds of hours of stress testing a .NET project:

Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is
corrupt.
   at System.Runtime.CompilerServices.CastHelpers.ChkCastClassSpecial(Void*, System.Object)

However, the project is 100% in safe C# code, so the AV must be on the CLR side. 

I took a look at the CLR code at https://github.com/dotnet/runtime/blob/0e30a6fda24575d0c9387ebff3675f65d2411cf7/src/coreclr/System.Private.CoreLib/src/System/Runtime/CompilerServices/CastHelpers.cs

The first thing I noticed is that while the inner loop has a null check for the parent method tables, there is no null check for the base method table. I bet that's where the AV happened.

A potential fix is to simplify this code down, which by doing so naturally lends itself to adding the missing null check... I would personally write this function like so. 
That said, I don't understand the surrounding context, and perhaps RuntimeHelpers.GetMethodTable is guaranteed to never return null, even in low-memory situations. So I'm re-writing this function in isolation:

```csharp
[DebuggerHidden]
[StackTraceHidden]
[DebuggerStepThrough]
private static object? ChkCastClassSpecial( void* toTypeHnd, object obj )
{
    // get the base method table for the object
    MethodTable* table = RuntimeHelpers.GetMethodTable( obj );

    // if the table matches the 'toType', then we can safely return the object b/c it can cast into the 'toType'
    // keep looking at parent tables until we find the one we're looking for
    for(; null != table; table = table->ParentMethodTable ) {
        if( table == toTypeHnd ) return obj;
    }
            
    // if we didn't find it, rely on ChkCast_Helper to resolve the object
    return ChkCast_Helper( toTypeHnd, obj );
}
```

Here is the current version. Note that the first "mt" access is not null checked before being used to access its parent table:

```csharp
[DebuggerHidden]
        [StackTraceHidden]
        [DebuggerStepThrough]
        private static object? ChkCastClassSpecial(void* toTypeHnd, object obj)
        {
            MethodTable* mt = RuntimeHelpers.GetMethodTable(obj);

            // Normally, this case is expected to be handled by JIT inline.
            // However, with PGO data JIT might decide to check a different type instead
            // so this one has to be always checked here
            if (toTypeHnd == mt)
                goto done;

            for (; ; )
            {
                mt = mt->ParentMethodTable; // <== BUG? MT NOT NULL CHECKED
                if (mt == toTypeHnd)
                    goto done;

                if (mt == null)
                    break;

                mt = mt->ParentMethodTable;
                if (mt == toTypeHnd)
                    goto done;

                if (mt == null)
                    break;

                mt = mt->ParentMethodTable;
                if (mt == toTypeHnd)
                    goto done;

                if (mt == null)
                    break;

                mt = mt->ParentMethodTable;
                if (mt == toTypeHnd)
                    goto done;

                if (mt == null)
                    break;
            }

            goto slowPath;

        done:
            return obj;

        slowPath:
            return ChkCast_Helper(toTypeHnd, obj);
        }
```

### Reproduction Steps

Unfortunately, this bug only manifests in a resource-constrained environment after many hours of automated stress-testing 100% safe C# code, so I cannot reliably repro it. However, just take a quick look at the function. There's clearly a missing null-check for "mt" before the first access. This is the only place where an AV could occur within this function. I included a suggested re-write of the code.

### Expected behavior

CastHelpers.ChkCastClassSpecial should not throw an AccessViolation

### Actual behavior

CastHelpers.ChkCastClassSpecial throws an AccessViolation

**Comment by AaronRobinsonMSFT** [comment]
> there is no null check for the base method table. 

A `null` check here isn't needed because an `object` instance without a `MethodTable` is invalid. If this is failing because of a `null` value, what has happened here is a GC hole has been discovered - entirely possible. Adding a check would hide that case when the value wasn't `null` and make for a potentially much worse situation.

Agree this is likely a runtime issue if the user application with the behavior is pure managed code - no P/Invokes or any uses of unsafe` code. Tracking this down is going to be rather difficult. A few questions:

* Is this a new failure case?
* What version of the runtime is being used?
* What processor architecture and OS is being used?

**Comment by MichalPetryka** [comment]
Keep in mind that AllowUnsafeBlocks set to false doesn't mean your code is safe, APIs like Unsafe.As can still cause GC holes and crashes.
