### ISSUE TITLE
System.Text.Json -> Deserialize Null to Integer Property

### ISSUE THREAD

**Issue by jogibear9988** [dotnet/runtime#74008]
### Description

We hav the following Code:

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public virtual int OrderIndex { get; set; }

But it throws a exception when we deserialize a "null" value to a Object with this et

### Reproduction Steps

see code above

### Expected behavior

should use default value for int

### Actual behavior

does not work

**Comment by layomia** [comment]
`JsonIgnoreCondition.WhenWritingNull` is only applied to writing/serialization, not deserialization. There's a proposal to extend the enum to include something like `JsonIgnoreCondition.WhenReadingNull` - https://github.com/dotnet/runtime/issues/66490. I'll close this as part of that larger issue.

The [custom serialization contracts](https://github.com/dotnet/runtime/issues/63686) features provides a predicate `JsonPropertyInfo.ShouldSerialize` to determine whether a property's value should be serialized. I believe the same was considered for deserialization. It would be helpful for scenarios like this. cc @krwq, @eiriktsarpalis.

**Comment by krwq** [comment]
could you simply customize JsonPropertyInfo so that `Set` ignores null value and does custom behavior?

**Comment by jogibear9988** [comment]
> could you simply customize JsonPropertyInfo so that `Set` ignores null value and does custom behavior?

we don't use the source code generators at the moment.

**Comment by krwq** [comment]
@jogibear9988 that's a contract customization feature we're shipping in 7.0 it works with both code-gen and reflection, it should be in pre-release nuget package `7.0.0-preview.6` or higher

```csharp
JsonSerializerOptions options =...;
options.TypeInfoResolver = new DefaultJsonTypeInfoResolver()
{
  Modifiers = { typeInfo => { if (typeInfo.Type == typeof(...)) { /* typeInfo.Properties modification here */ } } }
};
```
