### ISSUE TITLE
[Regression] System.Diagnostics.ActivityLink Equals broken in net7 preview

### ISSUE THREAD

**Issue by CodeBlanch** [dotnet/runtime#74026]
### Description

[This change](https://github.com/dotnet/runtime/pull/68933/files#diff-eef69be4a844643e414d513125fb6191d01faebe1875819008e4e87a756e579eR28) on #68933 broke the `ActivityLink.Equals` [behavior](https://github.com/dotnet/runtime/pull/68933/files#diff-eef69be4a844643e414d513125fb6191d01faebe1875819008e4e87a756e579eR43) which previously was doing a reference check on the tags passed into ctor.

Talking offline with @tarekgh it probably makes more sense to check the contents of tags instead of doing a reference check.

### Reproduction Steps

This test previously passed and now fails:

```csharp
        [Fact]
        public void ActivityLinkEqualsTest()
        {
            ActivityTagsCollection tags = new()
            {
                new KeyValuePair<string, object>("tag1", "value1"),
            };

            ActivityLink link1 = new ActivityLink(default, tags);
            ActivityLink link2 = new ActivityLink(default, tags);

            Assert.True(link1.Equals(link2));
        }
```

### Expected behavior

Two links with same context & tags should be considered equal.

### Actual behavior

Two links with same context & tags are considered non-equal.

### Regression?

Yes

**Comment by tommcdon** [comment]
@tarekgh @noahfalk  is this a test issue or should this bug be .net 7 blocking?

**Comment by tarekgh** [comment]
@tommcdon we discussed this issue today in our sync up meeting. This is not a test issue, but we are not going to make any changes to .NET 7.0. Instead, we'll document the behavior. I am keeping this for now as I am discussing more with @CodeBlanch and want to open a doc PR too.

**Comment by tarekgh** [comment]
I have opened the doc PR https://github.com/dotnet/dotnet-api-docs/pull/8316 to clarify the behavior. We can close this issue now.
