### ISSUE TITLE
crash in JIT/Methodical/Coverage/copy_prop_byref_to_native_int on Mono

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#74049]
Again
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-73983-merge-490a59077c1d4a9185/Methodical_others/1/console.c4adfd07.log?helixlogtype=result

Console log: 'Methodical_others' from job 490a5907-7c1d-4a91-85f3-10f4d174b436 workitem ebe0903c-5588-4a64-b6f7-a5314aeeb274 (ubuntu.1804.amd64.open.rt) executed on machine a002K59 running Linux-5.4.0-1086-azure-x86_64-with-Ubuntu-18.04-bionic

There is a core dump
https://dev.azure.com/dnceng/public/_build/results?buildId=1946845&view=ms.vss-test-web.build-test-results-tab&runId=50137760&resultId=102876&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by jakobbotsch** [comment]
Dup of #69832? Seems like the test was expected to have been disabled on Mono.

**Comment by SamMonoRT** [comment]
@naricc @trylek - any ideas why a disabled test is still running in CI legs ?

**Comment by akoeplinger** [comment]
@SamMonoRT looks like the test was only disabled on mono interpreter, fixed in https://github.com/dotnet/runtime/pull/74265
