### ISSUE TITLE
NetworkStream.BeginWrite has different buffer usage safety on Windows and Linux

### ISSUE THREAD

**Issue by Chicken-Bones** [dotnet/runtime#74050]
### Description

On Windows `NetworkStream.BeginWrite` makes a copy of the buffer if it does not complete synchronously
On Linux, it's the responsibility of the caller to either defensively copy before calling `BeginWrite` or check if the async-call has completed before writing new data into the old buffer (with some pooling/reclaimation)

It would be nice if either:
- The windows behavior was brought to Linux (improved ease of use, less memory control)
- or, The difference in behavior was mentioned in relevant documentation
- or, Documentation could warn that it is unsafe to use the buffer until the `AsyncCallback` is invoked (ownership is transferred to the stream)

Maybe it is documented somewhere, but I couldn't find it.

### Reproduction Steps

On Linux:
1. Open a tcp connection between two applications.
2. On the reading side, consume data slowly, so flow control is invoked (eg, with 1kb at a time, with a 10ms sleep between each read)
3. On the sending side, Use `NetworkStream.BeginWrite` to send a large amount of data (eg 50MB) using the same `byte[]` buffer.
4. (Optional) Log the current thread, and total sent byte count in the `AsyncCallback` before calling `EndWrite`
5. Observe the correct amount of data is received, but buffer overwrites have occurred at the point where writes started completing asynchronously.

On Windows:
repeat the above steps, but no buffer overruns occur (process memory usage should increase instead).

### Expected behavior

Platform consistency
- or, The difference in behavior mentioned in relevant documentation
- or, Documentation warning that it is unsafe to use the buffer until the `AsyncCallback` is invoked (ownership is transferred to the stream)

### Actual behavior

See reproduction steps. 
The buffer passed to `BeginWrite` is 'owned' by the socket until the `AsyncCallback` returns on Linux.

### Regression?

None, consistent with the Mono days.

### Known Workarounds

Implement your own defensive copying, eg via `System.Buffers.ArrayPool` 
Optionally, only do this `if (!OperatingSystem.IsWindows())`

### Configuration

```
Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa
```

Replicated on
```
  Virtualization: openvz
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0
      Architecture: x86-64
```

**Comment by stephentoub** [comment]
> ownership is transferred to the stream

This is the case with every Stream. Ownership of the array/span/memory is transferred as part of calling Read/Write/BeginRead/BeginWrite/ReadAsync/WriteAsync and is not transferred back until the operation completes.  NetworkStream nor Socket on Windows are doing any defensive copying of the data; if that's happening, it's happening in Windows itself and is not a documented nor in any way a guaranteed behavior of .NET.

**Comment by CarnaViire** [comment]
Triage: this is an implementation detail no one should depend on.
Closing as answered above.
