### ISSUE TITLE
Quic Connect fails with weird error when connecting to IPv6 and AF not available  

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#74053]
I bump to if while investigating some CI test failures. The repro machine (ARM64) did not have IPv6 configured so in the container I see
```
root@182754f0e955:/# ifconfig -a
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.3  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:ac:11:00:03  txqueuelen 0  (Ethernet)
        RX packets 14994  bytes 123227032 (117.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 12147  bytes 693509 (677.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1  (Local Loopback)
        RX packets 1764271  bytes 813818841 (776.1 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1764271  bytes 813818841 (776.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
Then running test,
```
    System.Net.Quic.Tests.MsQuicTests.ConnectWithCertificateForLoopbackIP_IndicatesExpectedError(ipString: "::1", expectsError: True) [FAIL]
      System.Net.Quic.QuicException : An internal error has occurred. Status code: Unknown (0x63)
      Stack Trace:
        /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(460,0): at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data)
        /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(517,0): at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent)
        /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(551,0): at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
        --- End of stack trace from previous location ---
``` 

error 0x63 -> `EADDRNOTAVAIL`. We should be able to handle it and provide reasonable exception. (similar to TCP)

**Comment by karelz** [comment]
Triage: We should throw better error when IPv6 is disabled on the OS. Not critical for 7.0.

**Comment by rzikm** [comment]
Note that the MsQuic status codes are platform specific, so a clean solution would be
- add a status define on the MsQuic side first (e.g. `#define QUIC_STATUS_ADDRESS_NOT_AVAILABLE    ((QUIC_STATUS)EADDRNOTAVAIL)`)
    - update the C# interop sources as well (for status codes this process is manual AFAICT)
 - Port the updated interop to .NET runtime and fix what is necessary (it may require adding a new `QuicError` member)

**Comment by wfurt** [comment]
Is this the `QUIC_STATUS_INVALID_ADDRESS` ??? (I did not try on Windows so I'm not sure.

**Comment by rzikm** [comment]
> Is this the `QUIC_STATUS_INVALID_ADDRESS` ??? (I did not try on Windows so I'm not sure)

No, it is a different status code. INVALID_ADDRESS is returned when the address family byte of the sockaddr struct is not valid I think.

**Comment by pedrobsaila** [comment]
I looked for QUIC_STATUS_INVALID_ADDRESS "This error is returned if the specified address pointed to by the name parameter is not a valid local IP address on this computer."
https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-bind
It does seem like the equivalent of EADDRNOTAVAIL

**Comment by karelz** [comment]
Triage: We still need to find out definitive error code on Windows when IPv6 is disabled. @rzikm can you please help? Thanks!

**Comment by karelz** [comment]
@wfurt didn't you address it already?

**Comment by wfurt** [comment]
This waits for https://github.com/microsoft/msquic/pull/3093. We could proceed but I think it would be best to get MsQuic changes in first.

**Comment by ManickaP** [comment]
Isn't this moot point since https://github.com/dotnet/runtime/pull/87208/files#diff-40b4af42663a9c4cb83bbbe8633435b86eaef928401b449a82050af4590b9683R73-R79???

**Comment by wfurt** [comment]
that depends on how exactly this is surfaced. We should write test IMHO or at least verify with recent builds before closing.
