### ISSUE TITLE
Deserialize a JSON string with the property name had no quotes

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/runtime#74055]
### Description

When I try to deserialize a JSON string with the property name had no `"`, it would throw an exception now, while it works with `Newtonsoft.Json`

Not sure if it's a problem, it may not a standard JSON

json sample:

``` json
{ CustomerId: "2929064f-1a22-4ece-947f-00eed7efed35"}
```

### Reproduction Steps

Deserialize the previous JSON with system text json
``` c#
System.Text.Json.JsonSerializer.Deserialize<JsonObject>(json);
```

### Expected behavior

Success with `JsonObject` returned

### Actual behavior

Got an exception likes follows:

```
System.Text.Json.JsonException: 
'C' is an invalid start of a property name. Expected a '"'. LineNumber: 0 | BytePositionInLine: 2.
```

### Configuration

.NET 6

**Comment by WeihanLi** [comment]
relates to https://github.com/dotnet/runtime/issues/32291

**Comment by eiriktsarpalis** [comment]
Property names lacking quotes is not valid JSON, but we might consider offering an optional flag that enables support. Closing as duplicate of #32291.
