### ISSUE TITLE
cannot open include file 'version_info.h'

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#74060]
Steps (windows) on a clean repo:
```
.\build.cmd Clr -c Checked
```

Build failure
```
  C:\prj\runtime\src\native\corehost\native.rc(1): fatal error RC1015: cannot open include file 'version_info.h'. 
[C:\prj\runtime\artifacts\obj\win-x64.Debug\corehost\ide\nethost\nethost.vcxproj]

```

**Comment by EgorBo** [comment]
cc @am11 @elinor-fung @alexrp if it rings a bell since you touched corehost project more or less recently

**Comment by am11** [comment]
It is strange that `--subset clr` is also building nethost, when it should only build singlefilehost from corehost directory.

**Comment by EgorBo** [comment]
Then sounds like it's likely something from:
https://github.com/dotnet/runtime/pull/73269
https://github.com/dotnet/runtime/pull/72688
https://github.com/dotnet/runtime/pull/73800

cc @elinor-fung

**Comment by am11** [comment]
Actually, I think it is from #73095, now that `host` subset is built as part of `DefaultCoreClrSubsets`, and we probably don't have checked configuration for host.

cc @agocke
