### ISSUE TITLE
SIMD tests should include invoking by Reflection

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/runtime#7406]
We need to validate that all the IL implementations are correct when `Vector<T>` is accelerated (i.e. its size is selected according to the hardware, e.g. AVX), but the method is invoked by Reflection. We should add tests to check this.

category:correctness
theme:testing
skill-level:beginner
cost:medium

impact:small

**Comment by tannergooding** [comment]
Tests were updated to consistently invoke a reflection path some time back.
