### ISSUE TITLE
MakeNewCustomDelegate is not supported by NativeAOT

### ISSUE THREAD

**Issue by hez2010** [dotnet/runtime#74067]
### Description

The CsWinRT 2.0 update fixed the trimming issue, so I'm trying to AOT compile my app which uses WinRT APIs. But I immediately hit another issue where the implementation of Vftbl in CsWinRT uses `Expression.GetDelegateType` to get the delegate type and create it at runtime.

So it yielded:

```
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Linq.Expressions.Compiler.DelegateHelpers.MakeNewCustomDelegate(Type[]) + 0x24
   at System.Linq.Expressions.Compiler.DelegateHelpers.MakeDelegateType(Type[]) + 0x6f
   at ABI.Windows.Foundation.IAsyncOperation`1.Vftbl..cctor() + 0xf5
```

Related source:

```csharp
Expression.GetDelegateType(typeof(void*), Marshaler<TResult>.AbiType.MakeByRefType(), typeof(int));
```

Is this possible to be supported by NativeAOT? 
If not, does rd.xml help in this case? And if it does help, can NativeAOT change the exception message to include the delegate type so that I can workaround it with rd.xml? 

/cc: @MichalStrehovsky 

### Reproduction Steps

N/A

### Expected behavior

N/A

### Actual behavior

N/A

**Comment by MichalStrehovsky** [comment]
On my phone but IIRC this is ref emit without saying ref.emit. We need to create a brand new delegate type that matches the signature the caller is asking for. It's not supportable without ref.emit. CsWinRT is doing source gen - it needs to include the one-liner to declare a delegate instead.

**Comment by hez2010** [comment]
Thanks for reply. 
Issue fired: https://github.com/microsoft/CsWinRT/issues/1248

**Comment by MichalStrehovsky** [comment]
Double checked and there isn't much we can do on the NativeAOT side, especially if the delegate gets then passed to GetFunctionPointerForDelegate. We would need to not only generate the delegate dynamically, but also generate the marshalling code/p/invoke transition for that signature that was never statically seen. Hopefully CsWinRT will fix this.
