### ISSUE TITLE
Test failures on runtime-extra-platforms on Android/iOS/tvOS/MacCatalyst

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#74076]
We introduced a couple test failures, see https://dev.azure.com/dnceng/public/_build/results?buildId=1948701&view=results

**Comment by simonrozsival** [comment]
Android:
- System.Net.Http.Functional.Tests.SocketsHttpHandler_SecurityTest (and derived classes) are failing - introduced in #73745 
- several System.Formats.Tar tests are failing - introduced in #72078
- JIT.Directed AliasingRetBufNative test is failing - this test was supposed to be disabled by #73704 but the test is still being run

iOS, MacCatalyst, tvOS:
- iOS.Simulator.XmlSerializer_Deserialize.Test fails - likely introduced in #73729

tvOS:
- System.Diagnostics.TraceSource.Config.Tests test is failing - introduced in #73087
- System.Security.Cryptography.Tests - test app crashes
- System.Xml.RW.FactoryReader.Tests - test app crashes
- System.Reflection.Extensions.Tests - test app crashes

**Comment by akoeplinger** [comment]
Closing this in favor of the individual issues that @simonrozsival created.
