### ISSUE TITLE
Environment variable for summary of JIT info output to console

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#74084]
The ability to set DOTNET_JitDisasm in release now is _awesome_.  However, sometimes it can be tricky to figure out the exact name to use (e.g. for anything the compiler name mangles, like async methods, iterators, local functions, top-level statements main, etc.), and setting DOTNET_JitDisasm to * to dump everything can be prohibitory in terms of how much it spews.  It can also be helpful to get a top-level picture of exactly what the JIT is compiling, e.g. to know what it ends up tiering up and what it doesn't, what gets inlined and what doesn't, what ends up getting used from an R2R image and what doesn't, etc.  It'd be helpful if there were some sort of DOTNET_JitDisasm_Short switch that could be set to 1 which would then limit the output for DOTNET_JitDisasm to a single line per method, showing only the most pertinent information, like method full name and tier.

**Comment by SingleAccretion** [comment]
Essentially, this would involve exposing `DOTNET_DumpJittedMethods=1` in Release.

**Comment by JulieLeeMSFT** [comment]
cc @EgorBo @dotnet/jit-contrib.

**Comment by BruceForstall** [comment]
> Essentially, this would involve exposing `DOTNET_DumpJittedMethods=1` in Release.

And/or `DOTNET_JitFunctionTrace`. Not sure why we DumpJittedMethods uses `info.compClassName, info.compMethodName` instead of `info.compFullName` like JitFunctionTrace does. In fact, we should probably make them display the same data, the only difference being JitFunctionTrace displays "end" info and nesting.

**Comment by EgorBo** [comment]
I am doing some cosmetic changes around JitDisasm so will include these too

**Comment by jakobbotsch** [comment]
We also have `DOTNET_JitOrder` that I frequently use for this, I wonder why we have so many different mechanisms for this :-)

**Comment by BruceForstall** [comment]
> We also have `DOTNET_JitOrder` that I frequently use for this, I wonder why we have so many different mechanisms for this :-)

IIRC, JitOrder was initially used for NGEN optimization. JitFunctionTrace was added mostly for the nesting functionality. Don't know about DumpJittedMethods :)
