### ISSUE TITLE
Cannot run .NET Core 3.1 apps in directories that end in dot on macOS

### ISSUE THREAD

**Issue by valentiniliescu** [dotnet/runtime#74105]
### Description

On macOS, if the path of a .NET Core 3.1 app contains a directory name with a `.` at the end, then that app cannot be run.

If the directory names has dots in any other places, the app runs fine. Also, running on .NET 6 is fine. 

Found the issue for a self-contained app, but it reproduces for regular, framework-dependent apps too.

### Reproduction Steps

- `dotnet new console -f netcoreapp3.1`
- _Framework-Dependent scenario:_
  - `dotnet publish`
  - `cd bin/Debug/netcoreapp3.1/`
  - Run app, it outputs: `Hello World!`
  - Rename `Debug` to `Debug.` and run the app again, it errors with: `Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly '/Users/valenti/Documents/HelloWorld/bin/Debug./netcoreapp3.1/HelloWorld.dll'. The system cannot find the file specified.`
- _Self-contained scenario:_
  - `dotnet publish -r osx-x64`
  - `cd bin/Debug/netcoreapp3.1/osx-x64/`
  - Run app, it outputs: `Hello World!`
  - Rename `Debug` to `Debug.` and run the app again, it errors with: `Failed to create CoreCLR, HRESULT: 0x80004005`

### Expected behavior

The sample apps run fine and output `Hello World!`

### Actual behavior

_Framework-Dependent scenario:_
The app errors with `Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly '/Users/valenti/Documents/HelloWorld/bin/Debug./netcoreapp3.1/HelloWorld.dll'. The system cannot find the file specified.`

 _Self-contained scenario:_
The app errors with: `Failed to create CoreCLR, HRESULT: 0x80004005`

### Configuration

.NET SDK (reflecting any global.json):
 Version:   6.0.302
 Commit:    c857713418

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.5
 OS Platform: Darwin
 RID:         osx.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.302/

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  3.1.418 [/usr/local/share/dotnet/sdk]
  5.0.407 [/usr/local/share/dotnet/sdk]
  6.0.301 [/usr/local/share/dotnet/sdk]
  6.0.302 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.24 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.16 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.24 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by danmoseley** [comment]
@valentiniliescu note that .NET 3.1 is nearing the end of its lifecycle, and we are only patching security issues in it. Can you migrate your app to .NET 6?

https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-and-net-core

**Comment by valentiniliescu** [comment]
It's not our app. There are plans for migration, but don't know when it will happen.

**Comment by vitek-karas** [comment]
I don't think we should fix this. The risk associated with servicing this doesn't seem to justify the reward. It seems a relatively low probability case when this happens with a workaround. And as Dan mentions above, 3.1 is in security-only fixing mode right now.

**Comment by danmoseley** [comment]
> It's not our app. There are plans for migration, but don't know when it will happen.

I understand, but please make sure the customer/vendor is aware this is in the last months of support, and they should move to 6.0. Which is likely the only way to get the fix for this also.

**Comment by vitek-karas** [comment]
Closing this as we're not planing to fix this in 3.1 given the current situation.
