### ISSUE TITLE
Remove dotnet8 feeds from NuGet.config when dependencies publish into dotnet9 feeds

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#74100]
Past similar changes:
- dotnet7->dotnet8: https://github.com/dotnet/runtime/issues/63375
- dotnet6->dotnet7: https://github.com/dotnet/runtime/issues/57716

**Comment by ViktorHofer** [comment]
@carlossanlop we don't need this tracking issue for future release. We only need it for the current release to not forget to remove the previous release matching nuget feeds. There's already https://github.com/dotnet/runtime/issues/63375 open for that so we can close this issue.
