### ISSUE TITLE
Why is CompressionLevel in ZipArchive sometimes nullable?

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#74146]
In ZipArchive related classes CompressionLevel is non-nullable on public method signatures but nullable in internal methods.
https://github.com/dotnet/runtime/blob/e71a9583b4d6c9bd97edd87cda7f98f232f63530/src/libraries/System.IO.Compression/src/System/IO/Compression/ZipArchive.cs#L273-L276

First, it is misleading for users because it is not clear what the default value is.
Second, it leads to several levels of conversions like:
https://github.com/dotnet/runtime/blob/e71a9583b4d6c9bd97edd87cda7f98f232f63530/src/libraries/System.IO.Compression/src/System/IO/Compression/ZipArchive.cs#L405-L407

If we look ZipArchiveEntry implementation:
https://github.com/dotnet/runtime/blob/e71a9583b4d6c9bd97edd87cda7f98f232f63530/src/libraries/System.IO.Compression/src/System/IO/Compression/ZipArchiveEntry.cs#L636

`CompressionLevel.Optimal` is used as default.

If we look low level implementation:
https://github.com/dotnet/runtime/blob/e71a9583b4d6c9bd97edd87cda7f98f232f63530/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/Deflater.cs#L41-L42

`CompressionLevel.Optimal` is used as default too.

My proposal is to use `CompressionLevel.Optimal` on top level and remove nullables in implementation and explicitly document that `CompressionLevel.Optimal` is default.

**Comment by stephentoub** [comment]
> In ZipArchive related classes CompressionLevel is non-nullable on public method signatures but nullable in internal methods.

That's an internal implementation detail.  Why does it matter?

> First, it is misleading for users because it is not clear what the default value is.

All the other compression types do this as well, e.g. when you do `new DeflateStream(stream, CompressionMode.Compress)`, you're getting a default value.

> and explicitly document that CompressionLevel.Optimal is default

The docs for types like DeflateStream say "By default, the compression level is set to [Optimal](https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.compressionlevel?view=net-6.0#system-io-compression-compressionlevel-optimal) when the compression mode is [Compress](https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.compressionmode?view=net-6.0#system-io-compression-compressionmode-compress).".  If you'd like to add something similar to the ZipArchive docs in an appropriate place, I think that'd be fine; that's an issue for https://github.com/dotnet/dotnet-api-docs.

**Comment by iSazonov** [comment]
> > In ZipArchive related classes CompressionLevel is non-nullable on public method signatures but nullable in internal methods.
> 
> That's an internal implementation detail. Why does it matter?

This provoked me to do the same thing in my code. Then I discovered that it was an unreasonable complication. I perceive it as a bad pattern.

Without it the .Net Runtime code could be cleaner here - why do we need these null checks and HasValue checks when we can get rid of them.

**Comment by stephentoub** [comment]
> Without it the .Net Runtime code could be cleaner here

Prove it :)  If you can demonstrably clean up the code, please submit a PR to do so.  We don't need an issue tracking it, though.

**Comment by Zintom** [comment]
Sorted 👍
