### ISSUE TITLE
PropertyInfo.GetCustomAttributes does not respect `inherit` flag, when provided

### ISSUE THREAD

**Issue by fluffynuts** [dotnet/runtime#74149]
### Description

Whilst trying to write some generic extension methods for Type, MethodInfo and PropertyInfo to be able to call `.HasAttribute` on them, I've discovered that PropertyInfo.GetCustomAttributes provides a surprising behavior:
- when `inherit` is not specified, inherited property attributes are returned (good)
- when `inherit` is specifed `false`, inherited property attributes are not returned (good)
- when `inherit` is specified `true`, inherited property attributes are _not_ returned (surprise!)

This looks like it's been there a while - the demo project shows the same behavior for net6.0 and net462

### Reproduction Steps

see demo at https://github.com/fluffynuts/dotnet-propertyinfo-getcustomattributes

### Expected behavior

When `inherit` is provided as `true`, returned attributes on overridden properties should include those of the base type, as is the case with `MethodInfo.GetCustomAttributes(true)`

### Actual behavior

When `inherit` provided, for any value, base property attributes are omitted in the result

### Regression?

This has been there since at least net462

### Known Workarounds

Knowing the behaviors, I can ensure that I call without any `inherit` flag when I want inherited attributes

### Configuration

dotnet version is 6.0.400, but this also occurs with a net462 target.

**Comment by svick** [comment]
This looks like a duplicate of https://github.com/dotnet/runtime/issues/30219.

**Comment by fluffynuts** [comment]
You're mentioning `MemberInfo.GetCustomAttributes`, but I'm talking about `PropertyInfo.GetCustomAttributes` - which has different documentation: https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices._propertyinfo.getcustomattributes - note the part:

![image](https://user-images.githubusercontent.com/4669340/185446628-80b73e6a-dc05-4d26-acbb-14e0c159ab0f.png)

In addition, even if it were documented as such, it doesn't really _ignore_ the `inherit` - when that parameter is provided, it _always_ strips out inherited members. When it's not provided _at all_, then you get inherited members. It doesn't _ignore_ the parameter so much as _do the wrong thing with it_. The variant without a parameter shows that the underlying logic is quite capable of traveling the inheritance chain.

This is a broken api: the interface and documentation say one thing, but the runtime does another.

**Comment by fluffynuts** [comment]
Still, I see from #30219, which was closed _long_ ago, that this bug will not be fixed. Thank goodness I can write my own libraries which do the right thing, and use the methods from there, without having to care about behavior that goes against the documentation (apart from just making no sense).

**Comment by svick** [comment]
@fluffynuts Note that you linked documentation for the `_PropertyInfo` interface. I've never seen that interface used (it seems to exists for COM interop) and it doesn't even exist on .Net Core/.Net 5+.

If you call `GetCustomAttributes(true)` on a `PropertyInfo` (no underscore), you're calling the inherited method from `MemberInfo`.

**Comment by fluffynuts** [comment]
So, for COM interop, the documentation is misleading; for other scenarios, the fallback is on `MemberInfo` and the parameters are misleading. Good to know.

I'll say it again: this is a broken api.

Better yet, it doesn't have to be, because it's quite clear that `GetCustomAttributes()` can traverse the hierarchy, so it's a bug kept in place because "that's how it always was", I guess?

At any rate, I closed this because I can see there's no point laboring the issue - everyone has accepted that this is broken and no change will happen. Again, I'm glad I can shim out correct behavior in my own libraries.
