### ISSUE TITLE
[RC1] System.AggregateException: One or more errors occurred. (Relative package path exceeds the maximum length (182): MonoToolChainManifest-7.0.100.7.0.0-rc.1.22417.10,version=56.3.47130,chip=arm64,productarch=neutral\Microsoft.NET.Workload.Mono.ToolChain.Manifest-7.0.100.7.0.0-rc.1.22417.10-arm64.msi.)

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/runtime#74151]
### Description

The RC1 official build has hit an error when building the workloads.

https://dev.azure.com/dnceng/internal/_build/results?buildId=1949892&view=logs&j=ad7bcd52-9916-5a50-47a2-92ef15ba97c4&t=7534b7fe-9656-5b8a-cdd1-9eb22fad156e

D:\a\_work\1\s\src\workloads\workloads.csproj(97,5): error : System.AggregateException: One or more errors occurred. (Relative package path exceeds the maximum length (182): MonoToolChainManifest-7.0.100.7.0.0-rc.1.22417.10,version=56.3.47130,chip=arm64,productarch=neutral\Microsoft.NET.Workload.Mono.ToolChain.Manifest-7.0.100.7.0.0-rc.1.22417.10-arm64.msi.)
D:\a\_work\1\s\src\workloads\workloads.csproj(97,5): error :  ---> System.Exception: Relative package path exceeds the maximum length (182): MonoToolChainManifest-7.0.100.7.0.0-rc.1.22417.10,version=56.3.47130,chip=arm64,productarch=neutral\Microsoft.NET.Workload.Mono.ToolChain.Manifest-7.0.100.7.0.0-rc.1.22417.10-arm64.msi.
D:\a\_work\1\s\src\workloads\workloads.csproj(97,5): error :    at Microsoft.DotNet.Build.Tasks.Workloads.Swix.SwixProjectBase.ValidateRelativePackagePath(String relativePackagePath) in /_/src/Microsoft.DotNet.Build.Tasks.Workloads/src/Swix/SwixProjectBase.cs:line 82
D:\a\_work\1\s\src\workloads\workloads.csproj(97,5): error :    at Microsoft.DotNet.Build.Tasks.Workloads.Swix.MsiSwixProject..ctor(ITaskItem msi, String baseIntermediateOutputPath, String baseOutputPath, String visualStudioProductArchitecture) in /_/src/Microsoft.DotNet.Build.Tasks.Workloads/src/Swix/MsiSwixProject.wix.cs:line 49
D:\a\_work\1\s\src\workloads\workloads.csproj(97,5): error :    at Microsoft.DotNet.Build.Tasks.Workloads.CreateVisualStudioWorkload.<>c__DisplayClass69_0.<Execute>b__2(WorkloadManifestMsi msi) in /_/src/Microsoft.DotNet.Build.Tasks.Workloads/src/CreateVisualStudioWorkload.wix.cs:line 440
D:\a\_work\1\s\src\workloads\workloads.csproj(97,5): error :    at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
D:\a\_work\1\s\src\workloads\workloads.csproj(97,5): error : --- End of stack trace from previous location ---
D:\a\_work\1\s\src\workloads\workloads.csproj(97,5): error :    at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
D:\a\_work\1\s\src\workloads\workloads.csproj(97,5): error :    at System.Threading.Tasks.TaskReplicator.Replica.Execute()
D:\a\_work\1\s\src\workloads\workloads.csproj(97,5): error :    --- End of inner exception stack trace ---
D:\a\_work\1\s\src\workloads\workloads.csproj(97,5): error :    at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
D:\a\_work\1\s\src\workloads\workloads.csproj(97,5): error :    at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
D:\a\_work\1\s\src\workloads\workloads.csproj(97,5): error : --- End of stack trace from previous location ---
D:\a\_work\1\s\src\workloads\workloads.csproj(97,5): error :    at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
D:\a\_work\1\s\src\workloads\workloads.csproj(97,5): error :    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
D:\a\_work\1\s\src\workloads\workloads.csproj(97,5): error :    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
D:\a\_work\1\s\src\workloads\workloads.csproj(97,5): error :    at Microsoft.DotNet.Build.Tasks.Workloads.CreateVisualStudioWorkload.Execute() in /_/src/Microsoft.DotNet.Build.Tasks.Workloads/src/CreateVisualStudioWorkload.wix.cs:line 435
##[error]src\workloads\workloads.csproj(97,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) System.AggregateException: One or more errors occurred. (Relative package path exceeds the maximum length (182): MonoToolChainManifest-7.0.100.7.0.0-rc.1.22417.10,version=56.3.47130,chip=arm64,productarch=neutral\Microsoft.NET.Workload.Mono.ToolChain.Manifest-7.0.100.7.0.0-rc.1.22417.10-arm64.msi.)

### Reproduction Steps

Build RC1

### Expected behavior

Pass

### Actual behavior

System.AggregateException: One or more errors occurred. (Relative package path exceeds the maximum length (182): MonoToolChainManifest-7.0.100.7.0.0-rc.1.22417.10,version=56.3.47130,chip=arm64,productarch=neutral\Microsoft.NET.Workload.Mono.ToolChain.Manifest-7.0.100.7.0.0-rc.1.22417.10-arm64.msi.)

### Regression?

No

**Comment by jeffschwMSFT** [comment]
@lewing

**Comment by lewing** [comment]
I thought this was fixed in rc1 atm but I backported the fix from main anyway
