### ISSUE TITLE
Setting PooledConnectionLifetime on HttpClient handlers created using HttpClientFactory 

### ISSUE THREAD

**Issue by sanpate** [dotnet/runtime#74173]
Our service is using HttpClientFactory to create HttpClients as typed clients with handler lifetime of 5 minutes. We inject these http clients into singleton adapters. We realized that this setup doesn't help with DNS changes on downstream service as HttpClient is getting lifetime of holding singleton adapter referencing expired http handlers.

As per guidelines here on addressing DNS issues: https://docs.microsoft.com/en-us/dotnet/fundamentals/networking/httpclient-guidelines we are looking into setting PooledConnectionLifetime on http handlers as we do not want to convert all of of our adapters (and other services in the chain) into transient. At the same time, we also want to continue using typed clients from http factory which allows us to easily integrate Polly policies and setup configs per service.

Question we have is - can we set PooledConnectionLifetime on HttpClient handlers created using HttpClientFactory like below:

            IHttpClientBuilder httpClientBuilder = services.AddHttpClient<THTTPCLIENT>(c =>
            {
                c.Timeout = TimeSpan.FromMilliseconds(httpFactoryClientOptions.CurrentValue.TimeoutMs);
            })
            .ConfigurePrimaryHttpMessageHandler(() =>
            {
                return new SocketsHttpHandler()
                {
                    PooledConnectionLifetime = TimeSpan.FromMinutes(5),
                };;
            })
            .SetHandlerLifetime(TimeSpan.FromMinutes(httpClientOptions.HttpHandlerLifetimeMinutes));

Will above work as intended where underlying connections should be recycled from connection pool helping addressing DNS change issues? Any downside of setting both PooledConnectionLifetime and HandlerLifetime? Any other alternatives to address DNS changes with this setup?

Thanks in advance!

**Comment by sanpate** [comment]
Thanks @CarnaViire, that makes sense. We will try this out and let you know if any issues.

**Comment by CarnaViire** [comment]
Closing as answered.
Feel free to reopen if there are any issues,

**Comment by akshay-zz** [comment]
Currently, I'm caching the HTTP clients on the basis of the base URL/named client. While injecting them with IHttpClientFactory. But when I went through the articles of Stevej Gordon.
https://www.stevejgordon.co.uk/httpclient-connection-pooling-in-dotnet-core
https://www.stevejgordon.co.uk/introduction-to-httpclientfactory-aspnetcore

 I found out that IHttpClientFactory is managing the HttpClientHandler and reusing it. Also, we can configure the `PooledConnectionLifetime`  & `PooledConnectionIdleTimeout`. That will solve the issue we use to get while treating HTTP clients as a singleton.

So my question do I need to cache my HTTP clients? Or I'm unnecessarily managing and caching them.

@CarnaViire

**Comment by CarnaViire** [comment]
Hi @akshay-zz, thanks for the question.
I am sorry that the guidance is very confusing right now.

From what I understand from your usage, you need to have several clients with different configurations, that you might need to inject into singletons. In that case, you can either:
1) Let HttpClientFactory cache them for you, and fix singleton usage by setting PooledConnectionLifetime and disabling rotation in the factory, as described in the issue above. In that case, you don't need to have additional cache on your side.
2) You can also opt for original usage pattern of HttpClientFactory, where you would inject not the client, but the factory itself in a singleton service and call factory.CreateClient(name) every time you need one, so the factory can handle the caching and rotation (in that case you would not need PooledConnectionLifetime). Here, you also don't need an additional cache.
3) If you don't actually need configurability HttpClientFactory offers, you can do the other way around: you can have only your singleton cache, where you would create HttpClients (with PooledConnectionLifetime) by yourself and then hold them throughout lifetime of your application.

Does that help? Or did I confuse you further 😄

Point is, you either need a **long**-living client with **PooledConnectionLifetime**, or a **short**-living client created by **HttpClientFactory**.

FYI: Comments in a closed issue is not the best place to have discussions 😄
I may suggest opening a new issue with a question, or using Discussions tab, next time 🙂

**Comment by akshay-zz** [comment]
Thanks for replying @CarnaViire . From next time I will keep in mind to start a new discussion.
Just to sum up things. If I'm injecting `IHttpClientFactory` to my scoped/transient services and creating a client by  `factory.CreateClient(name)`. HttpFactory will handle the HttpMessageHandler internally according to the pool time that has been configured for the named client.

Also disposing of the Httpclient will not harm as we have configured the pool time. Am I correct ?

**Comment by akshay-zz** [comment]
Opening a new thread
