### ISSUE TITLE
Is it possible to add a method that kills the process tree?

### ISSUE THREAD

**Issue by ymh199478** [dotnet/runtime#74198]
.Net standard does not provide any method to kill a process tree.

**Comment by Jozkee** [comment]
This issue is asking to port Process.Kill(bool entireProcessTree) to standard, but AFAIK there are no plans of a netstandard2.2.

**Comment by terrajobst** [comment]
That's why I moved to dotnet/runtime. We should treat it as a feature request for `Process`.

**Comment by terrajobst** [comment]
Never mind. I just realized we already have the API in .NET 5.
