### ISSUE TITLE
The state of X509Certificate management with netstandard, xamarin, win & macOS

### ISSUE THREAD

**Issue by manijak** [dotnet/runtime#74194]
First, my apologies if this is the wrong channel to post this. I've been digging and trying to understand for weeks where the issue/limitation is to our problem, figured this would be the most suitable place to ask. We are not sure if this is a limitation with the frameworks, or the platform, or due to our limited knowledge, or a combination of all. But things are very confusing right now, and we just need proper guidance on what direction to take.

EDIT: Would appreciate if @bartonjs or @filipnavara could pitch in 👍 

### **Background** 💡 
We are creating a small, cross-platform (win & macos), desktop application that will act as a websocket server running only on localhost (https). This application is a bridge between our web applications and the local machine hardware (e.g. printers). In order to provide a secure connection, `SslStream` requires a `X509Certificate2` class with a `PrivateKey`.

The idea is to let the app itself generate a self-signed certificate with private key and use that to start the secure websocket service. After the certificate has been generated for the first time, we store it in the local certificate store and reuse it when the app restarts. 

### **Project structure & frameworks** 📦 
This is how our solution is defined. `SharedProject` is a shared lib referenced by both `AppWin` & `AppMac`. The Win & Mac projects are startup-projects for their respective platform. 
```
OurApp.sln
  |---- SharedProject (netstandard2.1)
        Creates & runs the websocket service, generates certificate (win), communicates with local hardware, ect

  |---- AppWin (netcore3.0)
        Startup project for Windows platform. Contains platform-specific code, if any.

  |---- AppMac (Xamarin.Mac)
        Startup project for macOS platform. Contains platform-specific code (generates certificate).
```

### **How it runs** 🏃 
In our `SharedProject` we have a class taking care of certificate generation and storing. The idea was that both the Win & Mac platforms could use this to manage the certificates. It uses the `X509Certificate2` & `CertificateRequest` provided by the framework. Plus the `X509Store` to save and retrieve the certificate.

**Windows** ✔️ 
On Windows there are no issues. With minimum amount of code we are able to generate a self-signed certificate with private-key, store it, and run the service with it. Also re-using the certificate when the app restarts by retrieving the certificate works very well. The `X509Store` returns the certificate with the _private key_, and we can easily use it with our `SslStream`. 

**macOS** ❌ 
Things are not so clear here... We could not use the above mentioned shared class to manage certificates (that works just fine on Windows):
* First issue was that we got a `PlatformNotSupportedException` when the application was trying to use the `CertificateRequest`. 
* Second "issue" was that the `X509Store` did not store or retrieve certificates from the macOS keychain, but instead it uses some local mono certificate-store that the browsers do not see (at least in our tests). And it only stored the certificate (.cer) not the private-key that was included in the `X509Certificate2` object. Plus it seemed difficult to "Trust" the stored certificate.

So we created a separate class to take care of certificate management for macOS inside the `AppMac (Xamarin.Mac)` project. By using `BouncyCastle` we generated an identical self-signed certificate with private-key and used that to run our secure websocket service:

* When launching our Secure Websocket service on macOS, the certificate used here is automatically added to the local macOS login keychain. For us this is great, since we could not use `X509Store` to add it there in the first place.
* The only way we could retrieve the certificate from the keychain was to use the `SecKeyChain` class and query for it. Thankfully the `SecCertificate` object has a `ToX509Certificate2()` function. But that still left us without the `PrivateKey` that is needed by `SslStream`. 
* We also tried using `SecKeyChain.FindIdentity` to retrieve both, but even tho it is easy to convert `SecCertificate` to `X509Certificate2`, there seems to be no way to convert a `SecKey` to something useful like `RSA` or `RSACryptoServiceProvider` or something that can be embedded to the `X509Certificate2`

### What to do? 😭 
We are pretty much stuck when it comes to the macOS platform. There seems to be no way for us to retrieve our own X509Certificate2 with the private-key embedded. Not sure if this is because we are using Xamarin.Mac & netstandard2.1, perhaps things are easier on netcore3? But still, Xamarin & mono have been around for a long time, there should be a way for us to do this today. Must be something we are missing here and would appreciate if someone could guide us.

**Comment by bartonjs** [comment]
I hate to just play pass the parcel, but if the issue is in Xamarin.macOS, that's not us.

I know Xamarin was trying to unify on CoreFX instead of having their own implementation of everything, but don't know where that ended up.

If Xamarin.macOS is still a current product, and it still has this problem, you will need to open an issue at (I'm guessing) https://github.com/xamarin/xamarin-macios.

**Comment by bartonjs** [comment]
I don't think there's anything actionable that we can do here, so I'm going to go ahead and close the issue.  It won't lock for a while, so if @filipnavara had more data that just didn't get shared a couple years ago, there's still time to write it down here :smile:.
