### ISSUE TITLE
Memory leak when build X509 chain

### ISSUE THREAD

**Issue by Mordahlhuilhulh** [dotnet/runtime#74200]
I have .net standard project and my project is running on Linux 
I can see that there is a memory leak problem on the following lines:

using (X509Chain x509Chain = new X509Chain())
{	
	x509Chain.ChainPolicy.RevocationMode = X509RevocationMode.NoCheck;
	x509Chain.ChainPolicy.ExtraStore.AddRange(_trustedStore.ToArray());

	x509Chain.Build(Certificate);

	// Check if the returned errors in the build are acceptable
	if (x509Chain.ChainStatus.Any())
	{
	}
}

When running with a high load, the memory of the process starts at %MEM = 1.1 and after a few hours, the %MEM is  2.0

Any help will be highly appreciated.

**Comment by bartonjs** [comment]
This seems like a duplicate of #55672.

Based on our testing, there are no leaks, just a combination of .NET Server GC and glibc's local-buffered `free()` that makes the memory usage go high; but it goes stable, so there's no leak.
