### ISSUE TITLE
Why is System.Threading.Task.TaskToApm internal?

### ISSUE THREAD

**Issue by merarischroeder** [dotnet/runtime#74201]
I saw it being used here today https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs

I'm building a few stream types and I would like to define a stream wrapper too. I would have thought, with the advent of async Tasks this kind of tooling would have been made available to all programmers.

**Comment by stephentoub** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/61729
