### ISSUE TITLE
Tar: behavior for symbolic links to directories

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#74214]
Unlike `tar`, currently these links are being followed.
If the file linked to is in the archive it will be duplicated. If it is outside the archived directory it will be included as if it were.
Symbolic links to directories can also cause loops which will cause the archive creation to hang.

Can we behave like `tar` and not follow symlinks by default?
`tar` does provide an option to follow the links (`--dereference`).

cc @carlossanlop @dotnet/area-system-io

**Comment by Jozkee** [comment]
@carlossanlop did we deliberately choose to follow, and if so, what was the reason for it?

**Comment by carlossanlop** [comment]
The `TarFile.ExtractToDirectory` methods should extract symlinks without following them. I'll submit a fix.

**Comment by tmds** [comment]
@carlossanlop the issue about creation of the archive.

**Comment by carlossanlop** [comment]
> the issue about creation of the archive.

Oh I see. Re-reading the issue description, I made the assumption it was about extraction. Looking at the code again, extraction won't have a problem with following a symlink. The symlink will get created pointing at a destination, regardless if it exists or not.

I'll fix this for archive creation.

**Comment by carlossanlop** [comment]
Fixing this would require implementing the logic proposed in https://github.com/dotnet/runtime/issues/52666 

Due to the amount of work and the API proposal dependency, this won't make it to 7.0, so I'll move it to 8.0.

We may have to also fix this in `ZipFile.CreateFromDirectory`: https://github.com/dotnet/runtime/blob/main/src/libraries/System.IO.Compression.ZipFile/src/System/IO/Compression/ZipFile.Create.cs#L378

**Comment by tmds** [comment]
It should be possible to implement this using [RecursePredicate](https://docs.microsoft.com/en-us/dotnet/api/system.io.enumeration.filesystemenumerable-1.shouldrecursepredicate?view=net-6.0) or [ShouldRecurseIntoEntry](https://docs.microsoft.com/en-us/dotnet/api/system.io.enumeration.filesystemenumerator-1.shouldrecurseintoentry?view=net-6.0).

If this is pushed to 8.0 it will be a breaking change.

**Comment by carlossanlop** [comment]
OK let me try.

**Comment by carlossanlop** [comment]
@lewing I'm including this in this draft: https://github.com/dotnet/runtime/pull/74414 

We can close the automated one.
