### ISSUE TITLE
Easier way to upload Images using PostAsync

### ISSUE THREAD

**Issue by jrahma** [dotnet/runtime#74229]
Hi,

It will be great if you provide an easier way to directly uplaod images using PosyAsync without having to use MediaTypeHeaderValue

For example:

```c#
var content = new FormUrlEncodedContent(new[]
{
    new KeyValuePair<string, string>("channel", TextBoxNewChannelName.Text),
    new KeyValuePair<string, ImageStream>("logo", channel_logo),
});

```

**Comment by karelz** [comment]
@jrahma what exactly would you expect? How does it look today?
`HttpClient` is trying to provide flexibility - it is up to the callers to decide media type, etc. Is there something more we could/should detect?

**Comment by karelz** [comment]
Triage: No reply in 10 days, closing. Feel free to reopen if there is more info available. Thanks!
