### ISSUE TITLE
When will .NET support RFC 7232?

### ISSUE THREAD

**Issue by MalcolmCrowe** [dotnet/runtime#74232]
At present it appears that the implementation of ETag in System.Net.Http.Headers imposes some restrictions on usage that are unwarranted under RFC 7232. I know it is done for the best of reasons (I love optimistic concurrency control). I have a big server that runs fine with .NET 2.0 and I would like to use .NET 6 or later instead.
But I am unhappy with the following restrictions:
(In https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-odata/c4d715eb-10f6-47fa-9ccc-2ebf926558a6)
"The server MUST NOT include an ETag header in a response to any request performed against a URI that does not identify, as specified in URI Format: Resource Addressing Rules (section 2.2.3), a single entity, properties of an entity, or a Media Resource. In addition, the server MUST NOT include an ETag header if the request URI identifies a single entity whose type is not enabled for optimistic concurrency control. Server response requests performed against URIs that do not return single entities MUST provide concurrency tokens in the response payload for any entities that are enabled for concurrency control."
I get error messages from .NET when my server code tries to add the ETag header that it wants to add.
As I understand RFC 7232 all HTTP servers SHOULD include an ETag on all GET requests. The current restrictions are in violation of RFC 7232.
It is also annoying that the documentation continually refers to RFC 2616 when this RFC is obsoleted by the RFCs 7230-7237. Will this issue be fixed in a future version of .NET?

**Comment by Tornhoof** [comment]
The restriction you list is from OData, a specific protocol.

Where do you think this applies to .NET in general?

System.Net.Http.Headers does not provide much more than an ETag Header type ``EntityTagHeaderValue`` , nothing related to the use of ETags.

The only thing implemented oob with ETag, which comes to my mind atm, is the new OutputCaching Middleware in ASP.NET Core 7. You might want to ask there, if you think your findings apply there.

**Comment by MalcolmCrowe** [comment]
OK, I take the point. When I found the document it seemed to apply generally to the use of HttpClient. 
It would be nice to see an example that adds headers to a request (e.g. If-Match and other now-standard headers). As it is, the warning in Visual Studio is not very helpful. It simply says
"'WebRequest.Create(string)' is obsolete: 'WebRequest, HttpWebRequest, ServicePoint, and WebClient are obsolete. Use HttpClient instead.'"
There is no tutorial that I can see that explains how to performs something like WebRequest.Create using the System.Net.Http namespace. Is there a sample in the github repository?  I expect I will eventually be able to use the HttpMessageHandler and other classes to add standard headers, but the current library doesn't look like support of RFC 7232 to me.

**Comment by Tornhoof** [comment]
I still don't follow, why this has anything to do with RFC 7232, anyway:

As an introduction to HttpClient, I recommend https://docs.microsoft.com/en-us/dotnet/fundamentals/networking/httpclient

The easy shortcut APIs only cover the basic stuff, without e.g. headers.

But I think you're correct, that at least on that page, with all the examples, there is none adding headers. I'm sure the docs repo accepts PRs with improved examples though.


The one you're interested in is:
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.sendasync?view=net-6.0

There you build up an ``HttpRequestMessage`` where you can control headers, the body etc in a very fine granular way.

**Comment by MalcolmCrowe** [comment]
Stefan,
Many thanks, that is helpful.
Best wishes
Malcolm

**Comment by karelz** [comment]
Looks like it was answered above - closing. Thanks @Tornhoof!
