### ISSUE TITLE
Add support for decimal in attribute parameters

### ISSUE THREAD

**Issue by davidgrupp** [dotnet/runtime#7426]
It's long been know that you cannot use decimal as in attribute parameters. Since only primitive constants or arrays of primitives can be used as attribute parameters you can't use decimal as a parameter. However, it's more and more being recommended to use decimal over double for many common uses which seems it would indicate that adding support for decimals as attribute parameters has become more important. I'd like to see the CLR restriction of only using primitive constants or arrays of primitives changed to adding and exemption for decimals as well.

**Comment by jkotas** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/4525
