### ISSUE TITLE
Spmi-diff is showing diffs that are not related to the PR

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#74287]
I believe there is something wrong with spmi-diff pipeline. Even for PRs that shouldn't have code diffs is showing diffs. 
- [Pipelines - Run 20220819.5 (azure.com)](https://dev.azure.com/dnceng/public/_build/results?buildId=1954728&view=ms.vss-build-web.run-extensions-tab) shows x64 diffs for my change in [Use the register of CAST for contained index operator by kunalspathak · Pull Request #74275 · dotnet/runtime (github.com)](https://github.com/dotnet/runtime/pull/74275) that was just done under TARGET_ARM64.
- [Pipelines - Run 20220819.2 (azure.com)](https://dev.azure.com/dnceng/public/_build/results?buildId=1953841&view=ms.vss-build-web.run-extensions-tab) shows diff for a change in that is mostly renaming macros (and hoping that nothing missed out that would trigger the diff)
- And FINALLY, the biggest one [Pipelines - Run 20220819.12 (azure.com)](https://dev.azure.com/dnceng/public/_build/results?buildId=1954972&view=ms.vss-build-web.run-extensions-tab) shows -16436 code size improvements from Egor Bogatov [Improve JitDisasm for top-level statements, expose DumpJittedMethods in Release by EgorBo · Pull Request #74090 · dotnet/runtime (github.com)](https://github.com/dotnet/runtime/pull/74090).

I looked into the `spmi-diff` for #74090 and the diffs looks unrelated. The following diff is coming from https://github.com/dotnet/runtime/pull/74110, but is reported in #74090.

![image](https://user-images.githubusercontent.com/12488060/185723087-4f7c4ab4-9db9-4b04-8c2f-06a0b74e0b9f.png)

Likewise, below diff is unrelated to #74090 as well as #74110.

![image](https://user-images.githubusercontent.com/12488060/185723124-cbfd9963-118e-41c0-bf23-fe0510aea2b9.png)

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
Interesting. The second diff looks like RBO. Maybe the baseline jit is not getting updated or something?

**Comment by kunalspathak** [comment]
I did check the GUIDs and they look accurate. For example, https://github.com/dotnet/runtime/pull/74090 the baseline is supposed to be `1b9551b8-21f4-4233-9c90-f3eabd6a322b` which is the case as seen in https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-74090-merge-f0df5552204b43709e/win-x64/1/console.56c5c11e.log?helixlogtype=result. 

Even the `superpmi-collect` seems to be uploading to the right guid. This one is from last successful run.

```
[21:50:55] Using JIT/EE Version from jiteeversionguid.h: 1b9551b8-21f4-4233-9c90-f3eabd6a322b
[21:50:55] SuperPMI upload

```

**Comment by kunalspathak** [comment]
Seems like those are GUIDs for `.mch`. I don't see logging for baseline jit. May be we should add it.

**Comment by AndyAyersMS** [comment]
Locally (making changes on top of 9cd1a32332daec34ca6a8b13d638b2904e797ae7) I don't see any spurious diffs.

**Comment by kunalspathak** [comment]
By the way, from past few days, I am seeing this error on AzDo, not sure what it meant:

![image](https://user-images.githubusercontent.com/12488060/185723832-1657d78c-8eb1-4aa9-81a7-ea2f7e7377b1.png)

**Comment by kunalspathak** [comment]
> Locally (making changes on top of [9cd1a32](https://github.com/dotnet/runtime/commit/9cd1a32332daec34ca6a8b13d638b2904e797ae7)) I don't see any spurious diffs.

And for that even superpmi diff is clean. https://dev.azure.com/dnceng/public/_build/results?buildId=1950687&view=ms.vss-build-web.run-extensions-tab

**Comment by AndyAyersMS** [comment]
Look in the "setup" leg for the jit download from the cloud -- eg from https://dev.azure.com/dnceng/public/_build/results?buildId=1954972&view=logs&jobId=011e1ec8-6569-5e69-4f06-baf193d1351e&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=bf6cf4cf-6432-59cf-d384-6b3bcf32ede2

We should surface this warning more visibly

<img width="979" alt="image" src="https://user-images.githubusercontent.com/10121823/185723917-7cc9d20e-3cda-4371-8976-17e187863a82.png">

**Comment by AndyAyersMS** [comment]
So evidently, we're missing some baseline jits.

**Comment by kunalspathak** [comment]
> Look in the "setup" leg for the jit download from the cloud -- eg from https://dev.azure.com/dnceng/public/_build/results?buildId=1954972&view=logs&jobId=011e1ec8-6569-5e69-4f06-baf193d1351e&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=bf6cf4cf-6432-59cf-d384-6b3bcf32ede2
> 
> We should surface this warning more visibly
> 
> <img alt="image" width="979" src="https://user-images.githubusercontent.com/10121823/185723917-7cc9d20e-3cda-4371-8976-17e187863a82.png">

Yep, I was trying to find where that is logged. Thanks for finding it.

**Comment by kunalspathak** [comment]
I see that they are getting uploaded correctly in the rolling jit build job.

**Comment by kunalspathak** [comment]
> he baseline is supposed to be `1b9551b8-21f4-4233-9c90-f3eabd6a322b` which is the case as seen

I forgot that for baseline jit, we go with the git_hash.

**Comment by BruceForstall** [comment]
If I look at the (internal) baseline JIT pipeline https://dev.azure.com/dnceng/internal/_build?definitionId=902, it hasn't built all the JIT changes merged to public 'main'.

**Comment by BruceForstall** [comment]
> We should surface this warning more visibly

It would help if we suppressed some of the download progress status messages.

**Comment by BruceForstall** [comment]
@kunalspathak This has been understood and resolved, so I'm going to close it.
