### ISSUE TITLE
.NET 7 Preview 7 - Polymorphic Deserialization Fails When Base Type Is Abstract

### ISSUE THREAD

**Issue by Im5tu** [dotnet/runtime#74294]
### Description

If a base class is declared abstract, deserialization fails with: 

```
Unhandled exception. System.NotSupportedException: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'Base'. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
 ---> System.NotSupportedException: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'Base'.
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(ReadStack& state, Utf8JsonReader& reader, NotSupportedException ex)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
```

When you remove the `abstract` keyword from `Base` everything works as expected.

### Reproduction Steps

```csharp
JsonSerializer.Deserialize<Base>(JsonSerializer.Serialize(new Derived1()));
JsonSerializer.Deserialize<Base>(JsonSerializer.Serialize(new Derived2()));    

[JsonDerivedType(typeof(Derived1))]
[JsonDerivedType(typeof(Derived2))]
public abstract class Base
{}

public class Derived1 : Base
{
    public int X { get; set; } = 42;
}

public class Derived2 : Base
{
    public int Y { get; set; } = 42;
}

```

### Expected behavior

Deserializes correctly without error

### Actual behavior

Exception (above)

### Configuration

```bash
> dotnet --version
7.0.100-preview.7.22377.5
```

**Comment by eiriktsarpalis** [comment]
This is by design -- polymorphic _deserialization_ is not supported unless your derived types specify a type discriminator. It therefore tries to deserialize using the contract for `Base` without polymorphism, resulting in an expected error message concerning abstract type deserialization. If you change your contract into something like:
```C#
[JsonDerivedType(typeof(Derived1), "derived1")]
[JsonDerivedType(typeof(Derived2), "derived2")]
public abstract class Base
{}
```
it should be possible to roundtrip the values you specify.

**Comment by Im5tu** [comment]
<img width="1837" alt="image" src="https://user-images.githubusercontent.com/20248180/185759993-788fdd04-d848-42a8-936b-9701c865d050.png">

Thanks @eiriktsarpalis - I just tried this again with the discriminator as you described and still the result is the same

**Comment by eiriktsarpalis** [comment]
You're serializing the values as `Derived1` and `Derived2`, respectively. These types are not polymorphic and therefore no type discriminator is emitted over the wire. If you change your code into:
```C#
JsonSerializer.Deserialize<Base>(JsonSerializer.Serialize<Base>(new Derived1()));
JsonSerializer.Deserialize<Base>(JsonSerializer.Serialize<Base>(new Derived2()));
```
Everything should work as expected.

**Comment by Im5tu** [comment]
Ugh - yes that now works. 

IMO, this feature is not as intuitive as it should be. The discriminator is there on the base type but it's not written out when it should be. I know that this is because it's consistent with how STJ already handles inheritance - but I don't think this is good from a consumers perspective. :(
