### ISSUE TITLE
[wasm][aot] Uncaught errors in `System.Runtime.Tests`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#74302]
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1955898&view=results), and [log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-0d3d3473a76a48449a/WasmTestOnBrowser-System.Runtime.Tests/1/console.b121922f.log?helixlogtype=result):

```
info: Discovering: System.Runtime.Tests.dll (method display = ClassAndMethod, method display options = None)
info: Discovered:  System.Runtime.Tests.dll (found 8909 of 9059 test cases)
info: Using random seed for test cases: 867690635
info: Using random seed for collections: 867690635
info: Starting:    System.Runtime.Tests.dll
fail: 143503392
fail: 143503392
fail: 143503392
fail: 143503392
info: WASM EXIT 1
info: Waiting to flush log messages with a timeout of 120 secs ..
fail: Application has finished with exit code TESTS_FAILED but 0 was expected
fail: [out of order message from the browser]: http://127.0.0.1:49190/test-main.js 342:0 Uncaught (in promise)
fail: [out of order message from the browser]: http://127.0.0.1:49190/dotnet.js 1882:6 Uncaught
XHarness exit code: 71 (GENERAL_FAILURE)
```

This is when building `[wasm] Unwrap exception when calling entrypoint (#74235)` on `main`.
/cc @maraf @pavelsavara

**Comment by pavelsavara** [comment]
This seems that there is `throw 143503392` which is probably pointer ? Do we know what could throw like this ?

**Comment by pavelsavara** [comment]
Could this be 
```
function ___cxa_throw(ptr, type, destructor) {
      ...
      throw ptr;
```

**Comment by pavelsavara** [comment]
@vargaz do you have any ideas ? Thanks!

**Comment by carlossanlop** [comment]
@pavelsavara @radical @vargaz I am seeing this failure in this 7.0 backport PR: https://github.com/dotnet/runtime/pull/74971

Can you please determine if this is something that needs a fix to get backported to 7.0?

- Pipeline results: https://dev.azure.com/dnceng-public/public/_build/results?buildId=2240&view=logs&j=7f41eb05-1c5f-5922-38da-d308f495fb31&t=142a4cb7-24ad-543f-6942-1fea62d34e98&l=58
- Queue: `Build Browser wasm Linux Release LibraryTests_AOT`
- Artifacts: https://dev.azure.com/dnceng-public/public/_build/results?buildId=2240&view=ms.vss-test-web.build-test-results-tab&runId=31826&resultId=100001&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab

From [console.f9376408.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-74971-merge-7c992f49fbdf4dd796/normal-System.Runtime.Tests/1/console.f9376408.log?helixlogtype=result) in the artifacts:
```
[02:06:01] info: Starting:    System.Runtime.Tests.dll
[02:06:57] info: /datadisks/disk1/work/BAC30A50/w/AD8509D5/e/wasm_build/AppBundle/dotnet.js:1883: 138656096
[02:06:57] info:       throw ptr;
```

The `wasm-console.log` file in the artifacts seems to tell that the execution suddenly crashed (I would've expected a summary at the end, not an abrupt stop):

```
[PASS] System.Tests.RealFormatterTests.TestFormatterDouble_P20(value: 65747.125, expectedResult: "6,574,712.50000000000000000000 %")
[PASS] System.Tests.RealFormatterTests.TestFormatterDouble_P20(value: 1844674407370955.2, expectedResult: "184,467,440,737,095,525.00000000000000000000 %")
/datadisks/disk1/work/BAC30A50/w/AD8509D5/e/wasm_build/AppBundle/dotnet.js:1883: 138656096
      throw ptr;
      ^
```

**Comment by radical** [comment]
It happens on `main` too, and it's not fixed yet.

**Comment by radical** [comment]
[Rolling build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=11973&view=results), and [log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-70-47717c4d76814b0291/WasmTestOnBrowser-System.Collections.Tests/1/console.2d28fe92.log?helixlogtype=result):

```
[20:25:44] info: Using random seed for test cases: 2136378125
[20:25:44] info: Using random seed for collections: 2136378125
[20:25:44] info: Starting:    System.Collections.Tests.dll
[20:27:01] fail: 737314736
[20:27:01] fail: 737314736
[20:27:01] fail: 737314736
[20:27:01] fail: 737314736
[20:27:01] info: WASM EXIT 1
[20:27:01] info: Waiting to flush log messages with a timeout of 120 secs ..
[20:27:02] fail: Application has finished with exit code TESTS_FAILED but 0 was expected
[20:27:02] fail: [out of order message from the browser]: http://127.0.0.1:49189/test-main.js 342:0 Uncaught (in promise)
[20:27:02] fail: [out of order message from the browser]: http://127.0.0.1:49189/dotnet.js 1882:6 Uncaught
XHarness exit code: 71 (GENERAL_FAILURE)
```

**Comment by pavelsavara** [comment]
I can reproduce it on my machine. It takes ~60 attempts to get one failure. I'm trying to capture better trace now.

**Comment by vargaz** [comment]
Does it only fail when run from the browser ?

**Comment by pavelsavara** [comment]
[This one](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-74971-merge-7c992f49fbdf4dd796/normal-System.Runtime.Tests/1/console.f9376408.log?helixlogtype=result) is V8  @vargaz

**Comment by pavelsavara** [comment]
@vargaz is it actionable now ?

**Comment by lewing** [comment]
this is showing up regularly and we need to resolve it

cc @marek-safar @lambdageek

**Comment by lambdageek** [comment]
Looking at this one, https://github.com/dotnet/runtime/issues/74302#issuecomment-1247760180, I think `mono_wasm_invoke_method_bound` or maybe `mono_runtime_invoke` (on wasm?) needs a C++ catch clause. because our LLVM code assumes it can throw and unwind until we get back to the interpreter (to `do_jit_call`), but in this case we have JS->C->C# and there's no C# code to get back to.  it's happening with `call_entry_point` but it could probalby happen with other JS export entrypoints.

Actually I wonder if we're missing a `do_jit_call` (or really `mono_llvm_cpp_catch_exception`) for some opcode?

Another thought: do we load/register AOT images asynchronously? is it possible we executed `main` before all the AOT images were loaded os the interp thought it was doing a normal call, but by the time the exception is thrown we registered AOT images and they throw a C++ exception?

**Comment by vargaz** [comment]
Disabling random testcase ordering for this assembly would probably work around the problem.

**Comment by vargaz** [comment]
Does this still happen ?

**Comment by vargaz** [comment]
-> Fixed
