### ISSUE TITLE
Git error when checking out repo

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#74327]
```
{
  "ErrorMessage": "Git fetch failed with exit code: 128",
  "BuildRetry": true
}
```

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[32745](https://dev.azure.com/dnceng-public/public/_build/results?buildId=32745)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/76234/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/32745/logs/11)||
|[30538](https://dev.azure.com/dnceng-public/public/_build/results?buildId=30538)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/76206/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/30538/logs/1885)||
|[28758](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28758)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/76114/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/28758/logs/11)||
|[28655](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28655)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/76043/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/28655/logs/362)||
|[28659](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28659)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75872/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/28659/logs/200)||
|[28656](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28656)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/76043/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/28656/logs/58)||
|[28621](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28621)|dotnet/runtime|Checkout dotnet/runtime@main to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/28621/logs/397)||
|[24081](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24081)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75816/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24081/logs/1306)||
|[24210](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24210)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75846/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24210/logs/116)||
|[24360](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24360)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75573/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24360/logs/30)||
|[24354](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24354)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75939/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24354/logs/91)||
|[23797](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23797)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75914/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23797/logs/2184)||
|[24134](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24134)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75928/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24134/logs/1162)||
|[24148](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24148)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75932/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24148/logs/80)||
|[23953](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23953)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75908/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23953/logs/1358)||
|[23744](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23744)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75220/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23744/logs/2158)||
|[23816](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23816)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75913/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23816/logs/1868)||
|[24120](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24120)|dotnet/runtime|Checkout dotnet/runtime@release/7.0-rc2 to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24120/logs/111)||
|[24236](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24236)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75937/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24236/logs/1002)||
|[24039](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24039)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75922/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24039/logs/1325)||
|[24176](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24176)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75935/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24176/logs/56)||
|[24175](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24175)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75935/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24175/logs/113)||
|[23765](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23765)|dotnet/runtime|Checkout dotnet/runtime@release/7.0-rc2 to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23765/logs/1882)||
|[24252](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24252)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75102/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24252/logs/30)||
|[24246](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24246)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75248/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24246/logs/35)||
|[23840](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23840)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75918/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23840/logs/1158)||
|[24245](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24245)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75248/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24245/logs/30)||
|[24243](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24243)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75248/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24243/logs/221)||
|[23729](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23729)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75912/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23729/logs/2045)||
|[23781](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23781)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75858/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23781/logs/2008)||
|[24239](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24239)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75937/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24239/logs/35)||
|[24247](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24247)|dotnet/runtime|Checkout dotnet/runtime@release/7.0-rc2 to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24247/logs/184)||
|[23764](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23764)|dotnet/runtime|Checkout dotnet/runtime@release/7.0-rc2 to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23764/logs/1119)||
|[24238](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24238)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75937/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24238/logs/30)||
|[24237](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24237)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75937/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24237/logs/38)||
|[24146](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24146)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75932/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24146/logs/90)||
|[24240](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24240)|dotnet/runtime|Checkout dotnet/runtime@release/7.0-rc2 to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24240/logs/53)||
|[23784](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23784)|dotnet/runtime|Checkout dotnet/runtime@main to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23784/logs/1296)||
|[24089](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24089)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75546/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24089/logs/114)||
|[24082](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24082)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75816/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24082/logs/113)||
|[24135](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24135)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75928/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24135/logs/112)||
|[24224](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24224)|dotnet/runtime|Checkout dotnet/runtime@release/7.0-rc2 to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24224/logs/8)||
|[24068](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24068)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75917/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24068/logs/114)||
|[24004](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24004)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75363/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24004/logs/677)||
|[23780](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23780)|dotnet/runtime|Checkout dotnet/runtime@release/7.0-rc2 to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23780/logs/764)||
|[24209](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24209)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75846/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24209/logs/132)||
|[24155](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24155)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75934/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24155/logs/669)||
|[23779](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23779)|dotnet/runtime|Checkout dotnet/runtime@release/7.0 to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23779/logs/773)||
|[24077](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24077)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75816/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24077/logs/56)||
|[24114](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24114)|dotnet/runtime|Checkout dotnet/runtime@release/7.0-rc2 to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24114/logs/44)||
|[24136](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24136)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75928/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24136/logs/56)||
|[24076](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24076)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75816/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24076/logs/112)||
|[23957](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23957)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75452/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23957/logs/1143)||
|[23782](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23782)|dotnet/runtime|Checkout dotnet/runtime@release/5 to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23782/logs/784)||
|[24069](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24069)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75917/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24069/logs/56)||
|[24040](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24040)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75922/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24040/logs/113)||
|[23715](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23715)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75911/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23715/logs/1443)||
|[23925](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23925)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75915/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23925/logs/1161)||
|[23767](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23767)|dotnet/runtime|Checkout dotnet/runtime@release/7.0-rc2 to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23767/logs/115)||
|[24041](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24041)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75922/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24041/logs/56)||
|[24173](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24173)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75935/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24173/logs/200)||
|[24177](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24177)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75935/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24177/logs/28)||
|[24150](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24150)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75856/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24150/logs/467)||
|[23859](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23859)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75919/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23859/logs/1180)||
|[24156](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24156)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75934/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24156/logs/37)||
|[23959](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23959)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75452/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23959/logs/56)||
|[23955](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23955)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75908/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23955/logs/56)||
|[23747](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23747)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75220/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23747/logs/122)||
|[23926](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23926)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75915/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23926/logs/113)||
|[24153](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24153)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75856/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24153/logs/28)||
|[24151](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24151)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75856/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24151/logs/37)||
|[24145](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24145)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75932/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24145/logs/193)||
|[23717](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23717)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75911/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23717/logs/64)||
|[23609](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23609)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75806/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23609/logs/2088)||
|[23909](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23909)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/74963/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23909/logs/113)||
|[23943](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23943)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/74935/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23943/logs/110)||
|[24065](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24065)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75929/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24065/logs/35)||
|[23927](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23927)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75915/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23927/logs/56)||
|[24087](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24087)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75546/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24087/logs/193)||
|[24096](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24096)|dotnet/runtime|Checkout dotnet/runtime@main to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24096/logs/74)||
|[24067](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24067)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75917/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24067/logs/186)||
|[24070](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24070)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75917/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24070/logs/28)||
|[24063](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24063)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75929/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24063/logs/37)||
|[24062](https://dev.azure.com/dnceng-public/public/_build/results?buildId=24062)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75929/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24062/logs/239)||
|[23910](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23910)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/74963/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23910/logs/56)||
|[23758](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23758)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75894/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23758/logs/1202)||
|[23817](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23817)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75913/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23817/logs/89)||
|[23860](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23860)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75919/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23860/logs/112)||
|[23892](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23892)|dotnet/runtime|Checkout dotnet/runtime@main to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23892/logs/50)||
|[23798](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23798)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75914/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23798/logs/89)||
|[23711](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23711)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75237/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23711/logs/933)||
|[23664](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23664)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75142/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23664/logs/592)||
|[23835](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23835)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75363/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23835/logs/118)||
|[23692](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23692)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75902/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23692/logs/1187)||
|[23861](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23861)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75919/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23861/logs/56)||
|[23731](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23731)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75912/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23731/logs/64)||
|[23799](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23799)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75914/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23799/logs/44)||
|[23783](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23783)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75858/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23783/logs/113)||
|[23760](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23760)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/75894/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23760/logs/112)||
|[23945](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23945)|dotnet/runtime|Checkout dotnet/runtime@refs/pull/74935/merge to s|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/23945/logs/35)||
Displaying 100 of 183 results
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|183|

**Comment by hoyosjs** [comment]
@dotnet/dnceng FYI

**Comment by dkurepa** [comment]
This appears to be a common issue when trying to clone many times at the same time, I think there's valuable info on this thread https://developercommunity.visualstudio.com/t/git-clone-fails-with-tf4000733-error-code-when-man/489440

**Comment by hoyosjs** [comment]
The messages are of the sort of `fatal: could not read Username for 'https://github.com': terminal prompts disabled`, `fatal: unable to access 'https://github.com/dotnet/runtime/': transfer closed with outstanding read data remaining`, and RPC issues. Not about `This request was blocked because there are too many clones running at the same time.`

**Comment by danmoseley** [comment]
Why is this in the runtime repo -- wouldn't arcade be a better place? Is there anything specific to this repo?

**Comment by premun** [comment]
I think this issue is here because of the `Known Build Error` label and the Build Analysis check is then looking this up when this happens on PRs in this repo

**Comment by danmoseley** [comment]
@premun  the known build error system doesn't look at known build errors in the arcade repo as well? I would expect it to be quite common for a runtime PR to encounter a build error being tracked in arcade.

**Comment by premun** [comment]
Ah, apologies, I just found this one: https://github.com/dotnet/arcade/issues/9009

**Comment by premun** [comment]
Yeah, let's
