### ISSUE TITLE
Disabling/filtering query parameters for URIs in HTTP tracing

### ISSUE THREAD

**Issue by CarnaViire** [dotnet/runtime#74340]
Similar to #68675, we should consider some kind of configuration for disabling/filtering query parameters for URIs in HTTP tracing.

We should also discuss whether it should be a single config for tracing and logging, or they should be different.

Last time we discussed it, we believed it will be better to keep them separate for discoverability -- configuring HttpClientFactory's logging would make more sense as a part of general HttpClientFactory configuration.

Consuming tracing requires more conscious effort, so a setting there might be less evident (e.g. AppContext switch).

We also discussed that we generally don't like messing with all Uris at once (e.g. setting that will apply globally to all Uri.ToString)

Note that Barry's opinion was to have a single setting:

> It’s difficult, because I can see folks taking trace events and saving them for debugging or security parsing. And once that happens it’s exactly the same problem. I’d say match the two.

So I wonder maybe tracing's setting can apply to logging, but not the other way around.

**Comment by MihaZupan** [comment]
Just to confirm, are we are only concerned about the `pathAndQuery` parameter of the [`RequestStart` event](https://github.com/dotnet/runtime/blob/3c21cc5a0a486d08b5a7a4fdc2e1c2f9b02dbc9f/src/libraries/System.Net.Http/src/System/Net/Http/HttpTelemetry.cs#L32) for `System.Net.Http`?

If we were to consider the path as well, we should work with ASP.NET as they also have tracing that includes such info (e.g. [`KestrelEventSource.RequestStart`](https://github.com/dotnet/aspnetcore/blob/b883b451b02876b9adaf3c4ce7ae0ac441f471bb/src/Servers/Kestrel/Core/src/Internal/Infrastructure/KestrelEventSource.cs#L116)).

**Comment by karelz** [comment]
Triage: Would be nice to get it in 8.0 as it makes security easier for specific set of users.
