### ISSUE TITLE
[NativeAOT] Crash during gen1 GC

### ISSUE THREAD

**Issue by tomcashman** [dotnet/runtime#74355]
I've been contributing to NativeAOT port on game consoles by @TheSpydog . With our current project, we are receiving a crash during gen1 GC using .NET 7 preview 7 on an ARM64 platform.

```
	Bootstrap.nss!WKS::WaitLonger(int i) Line 1490 (0x33B9216E00)	C++
 	Bootstrap.nss!WKS::gc_heap::background_mark_phase() Line 34085 (0x33B922AB10)	C++
 	Bootstrap.nss!WKS::gc_heap::gc1() Line 20663 (0x33B9229830)	C++
 	Bootstrap.nss!WKS::gc_heap::bgc_thread_function() Line 35184 (0x33B92402F8)	C++
```

We're unsure if this is an upstream issue or perhaps a misconfiguration of NativeAOT on our side. I've included the info that I was able to find below. Any additional pointers to help diagnose further would be much appreciated.

IsCurrentThreadInCooperativeMode is returning false, triggering the assert in WaitLonger(int i).

```
bool Thread::IsCurrentThreadInCooperativeMode()
{
#ifndef DACCESS_COMPILE
    ASSERT(ThreadStore::GetCurrentThread() == this);
#endif // !DACCESS_COMPILE
    return (m_pTransitionFrame == NULL);
}
```

I think the issue is related to volatile read/write of m_pTransitionFrame in thread.cpp.

```
void Thread::EnablePreemptiveMode()
{
    ASSERT(ThreadStore::GetCurrentThread() == this);
#if !defined(HOST_WASM)
    ASSERT(m_pDeferredTransitionFrame != NULL);
#endif

    Unhijack();

    // set preemptive mode
    VolatileStoreWithoutBarrier(&m_pTransitionFrame, m_pDeferredTransitionFrame);
}
```

**Comment by EgorBo** [comment]
Could be related to https://github.com/dotnet/runtime/issues/72645 ? (with a fix in https://github.com/dotnet/runtime/pull/74325)

**Comment by VSadov** [comment]
`bgc_thread_function` - I do not think background GC works on NativeAOT yet.  

(cc @MichalStrehovsky, @jkotas  is that true?  I do not see write watch support in Windows-arm64 barriers, so I assume it is not something that we support/test yet)

Regardless, for an initial port, I'd suggest not enabling "extras" such as background GC or card bundles.

**Comment by tomcashman** [comment]
At the moment we're using software write watch.

These are all the preprocessor definitions we're using. Perhaps we need to add/remove some?

```
TARGET_UNIX;TARGET_ARM64;_ARM64_;_aarch64_;HOST_ARM64;HOST_64BIT;_LIBUNWIND_DISABLE_ZERO_COST_APIS=1;_LIBUNWIND_IS_NATIVE_ONLY;_LIBUNWIND_HAS_NO_THREADS;_LIBUNWIND_USE_DLADDR=0;_LIBUNWIND_IS_BAREMETAL;_LIBUNWIND_USE_ONLY_DWARF_INDEX;PAL_STDCPP_COMPAT;FEATURE_BASICFREEZE;FEATURE_USE_SOFTWARE_WRITE_WATCH_FOR_GC_HEAP;FEATURE_CONSERVATIVE_GC;FEATURE_CUSTOM_IMPORTS;FEATURE_NATIVEAOT;FEATURE_FIXED_POOL_THUNKS;VERIFY_HEAP;NATIVEAOT;FEATURE_CACHED_INTERFACE_DISPATCH;_LIB;NO_UI_ASSERT;FEATURE_GC_STRESS;
```

**Comment by jkotas** [comment]
> I do not think background GC works on NativeAOT yet.

It should work when software write watch is available (ie Windows). It does not work when software write watch is not available. 

> I do not see write watch support in Windows-arm64 barriers

We should fix that (it is missing on all platforms) but it unlikely to be be the root cause of this crash.

**Comment by VSadov** [comment]
@tomcashman the easiest way to disable background GC is by configuring GC (https://docs.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector).  The knob that controls background GC is `gcConcurrent`

i.e.
`export COMPlus_gcConcurrent=0`

Even if it is supposed to work, it may be a good idea to disable it during initial bring up.

**Comment by tomcashman** [comment]
> It should work when software write watch is available (ie Windows). It does not work when software write watch is not available.

@jkotas is software write watch not supported on Linux? When we originally looked through the code we thought it would work.

@VSadov  I'll test without background GC but not ideal as we're porting video games which can't really pause on the main thread without killing frame rate.

**Comment by jkotas** [comment]
> @jkotas is software write watch not supported on Linux? When we originally looked through the code we thought it would work.

We are missing a bit of assembly code required to make it work.

**Comment by tomcashman** [comment]
> We are missing a bit of assembly code required to make it work.

This section of src\coreclr\nativeaot\Runtime\gcrhenv.cpp:1171 stated that only UNIX/ARM64 is supported for software write watch.

```
#if defined(FEATURE_USE_SOFTWARE_WRITE_WATCH_FOR_GC_HEAP) && (!defined(TARGET_ARM64) || !defined(TARGET_UNIX))
#error FEATURE_USE_SOFTWARE_WRITE_WATCH_FOR_GC_HEAP is only implemented for ARM64 and UNIX
#endif
```

That was what led us to enabling it for background GC. Now we're confused 😄

**Comment by VSadov** [comment]
@jkotas - yes the crash is because background GC threads are expected to be in cooperative mode. Somehow that is not happening in @tomcashman`s scenario, but it can't be a race since this is an assert from the same thread. It is a separate issue.

I just wanted to be sure we do expect background GC to run. I have never seen background threads while debugging or looking at the dumps so I assumed we might not be enabling BGC. BGC threads are created and destroyed on demand though, so I might just never seen them in action. 

I also noticed that some barriers are missing the parts that update the write watch (I think it is the Windows that is missing these parts, but Unix has them, at least on arm64). It is possible that Windows may be using hardware writewatch.

**Comment by VSadov** [comment]
>  I'll test without background GC but not ideal as we're porting video games which can't really pause on the main thread without killing frame rate.

@tomcashman   Let me dig a bit further whether BGC should/can/does work. 
it looks like the support for background GC is there, at least on Unix+arm64, so it might work. It is strange that we do not see the same assert in tests though.

**Comment by tomcashman** [comment]
If there's anything I can do to help diagnose, please let me know.

**Comment by tomcashman** [comment]
We just noticed a warning for one of the static asserts in our environment in thread.cpp

Not sure why it was a warning instead of a compile time error, we don't have anything set that would disable it....perhaps we're missing a flag related to this?

```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E1574	static assertion failed with "OFFSETOF__Thread__m_pTransitionFrame == (offsetof(Thread, m_pTransitionFrame))"	Runtime	src\coreclr\nativeaot\Runtime\thread.cpp	253	
```

**Comment by VSadov** [comment]
On my part I tried setting `FEATURE_USE_SOFTWARE_WRITE_WATCH_FOR_GC_HEAP` on Linux+arm64.  

While runtime was able to build with that, tests would fail to build with missing exports of write watch table and related globals. It does not look like this is normally enabled.

Windows barriers do not have support for writewatch. 
I think I will add that. It would make sense to have all supported platforms on roughly the same functionality level and could be easier to debug.

**Comment by VSadov** [comment]
@tomcashman - I do not see the static assert error in the builds (I checked Windows/x64 and Linux/arm6). 
It does look strange. If the error was correct (i.e. the values would not be matching), the runtime would be rather unusable.

**Comment by MichalStrehovsky** [comment]
It's possible background GC/software write watch was only enabled in the console patchset that Thomas probably got from Ralf:
https://github.com/dotnet/corert/pull/8331, https://github.com/dotnet/corert/pull/8293. At that time we didn't have any Unix arm64 build configuration so this added the ifdefs, but we never enabled them when Linux ARM64 was enabled. The console patchset likely enables a different set of `#defines` than we do in the product. It would be good to look at what other upstreamable things there are (I don't have the patchset).

**Comment by tomcashman** [comment]
Yes we enabled that ourselves. In general we try to use as much of upstream as possible and only implement the PAL APIs to use console-specific calls. And with that we try keep the calls in line with what the Unix PAL code is doing. The only API I can think that is not implemented and possibly related is PalHijack which returns false from the method. But looking at the GC code that should be ok?

@TheSpydog is the repo owner who got the initial version working and would be able to provide further insights and possible access.

**Comment by TheSpydog** [comment]
> The console patchset likely enables a different set of `#defines` than we do in the product.

Yes, Tom posted the full list of defines earlier in this thread:
`TARGET_UNIX;TARGET_ARM64;_ARM64_;_aarch64_;HOST_ARM64;HOST_64BIT;_LIBUNWIND_DISABLE_ZERO_COST_APIS=1;_LIBUNWIND_IS_NATIVE_ONLY;_LIBUNWIND_HAS_NO_THREADS;_LIBUNWIND_USE_DLADDR=0;_LIBUNWIND_IS_BAREMETAL;_LIBUNWIND_USE_ONLY_DWARF_INDEX;PAL_STDCPP_COMPAT;FEATURE_BASICFREEZE;FEATURE_USE_SOFTWARE_WRITE_WATCH_FOR_GC_HEAP;FEATURE_CONSERVATIVE_GC;FEATURE_CUSTOM_IMPORTS;FEATURE_NATIVEAOT;FEATURE_FIXED_POOL_THUNKS;VERIFY_HEAP;NATIVEAOT;FEATURE_CACHED_INTERFACE_DISPATCH;_LIB;NO_UI_ASSERT;FEATURE_GC_STRESS;`

The only notable differences compared to the regular product are the absence of `FEATURE_DYNAMIC_CODE` and the additions of `FEATURE_FIXED_POOL_THUNKS` (required for consoles, since they're very picky about executable permissions), and `FEATURE_USE_SOFTWARE_WRITE_WATCH_FOR_GC_HEAP` (for background GC). Also worth noting the `FEATURE_GC_STRESS` flag is only enabled in debug builds, as it is in the regular runtime.

> It would be good to look at what other upstreamable things there are (I don't have the patchset).

Unfortunately there's not much that can be upstreamed, since most of the new stuff uses NDA'd console-specific APIs. The changeset really isn't that sizeable anyway -- it's just platform-specific implementations of PAL files in System.Native and friends, as well as a custom implementation of PalRedhawkUnix and gcenv. The new files exist almost entirely to work around missing POSIX calls in the platform standard libraries; we use upstream's PAL/runtime implementations wherever possible to avoid diverging too much.

The only parts that might be upstreamable are some assembly files for Unix versions of `ThunkPoolThunks.asm`.

**Comment by tomcashman** [comment]
Investigating further I've found that the issue does not occur when the DEBUG flag is set. This is because a different implementation of enter_spin_lock in gc.cpp is used if DEBUG is set..

What stands out to me as a key different in the implementations if usage of Interlocked::CompareExchange when in Release mode.

Digging a bit I found that this method depends on an inline _InterlockedCompareExchange function. But looking at the asm files I don't think it exists for ARM64? It seems that this is provided by winwrap.h? This is just my undestanding, please let me know if I am misunderstanding.

**Comment by VSadov** [comment]
Interlocked::CompareExchange is implemented in src\coreclr\gc\env\gcenv.interlocked.inl, it should call __sync_val_compare_and_swap on unix.

**Comment by VSadov** [comment]
@tomcashman - here is a PR https://github.com/dotnet/runtime/pull/74735 to enable background GC on Unix (both arm64 and x64). 
I did have to fix a few things to make it work, but I did not see the issues as you describe.

**Comment by tomcashman** [comment]
Thanks @VSadov we can test after it's merged in 😃

**Comment by VSadov** [comment]
From the stack trace I see that the asset comes from background GC. Background GC threads typically report their mode as cooperative. Blocking GC requires that background GC threads are stopped, so in that sense it fits that background GC happens in coop mode. I wonder what could cause it to return a different mode.

**Comment by VSadov** [comment]
I am bit confused - how can `WaitLonger(int i)` trigger an assert? 
It looks like the whole method is in an `#else //_DEBUG` section.

**Comment by tomcashman** [comment]
> I am bit confused - how can `WaitLonger(int i)` trigger an assert? It looks like the whole method is in an `#else //_DEBUG` section.

Is line 1440 meant to be #ifndef ? The assert happens on line 1491.

![image](https://user-images.githubusercontent.com/1745420/203530524-facd4a74-bb85-48c1-b24d-2d957fbe5bf8.png)

**Comment by jkotas** [comment]
`assert` is expected to be no-op for release builds. If you are doing your own custom build, do you have `NDEBUG` defined for release build?

**Comment by tomcashman** [comment]
*facepalm* NDEBUG wasn't defined. Not hitting this crash anymore.

Though is it ok for bToggleGC to be false?

**Comment by jkotas** [comment]
I think that assert is wrong. It should be ok for `bToggleGC` to be false. Would you like to submit PR to delete it?

**Comment by tomcashman** [comment]
Will do
