### ISSUE TITLE
Debug is not working in ASPNET 7.0.100-preview7 when dotnet 6 is installed

### ISSUE THREAD

**Issue by timbze** [dotnet/runtime#74361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I can run `dotnet watch` and I can `Run` my ASP.NET core application, but if I try debugging, I get the error message below. I have .NET 7 sdk installed (otherwise `dotnet watch` and `Run` in my app wouldn't work either)

```
/home/timmy/Repos/myaspnetapp/src/Application/bin/Debug/net7.0/Application 
You must install or update .NET to run this application.

App: /home/timmy/Repos/myaspnetapp/src/Application/bin/Debug/net7.0/BlazorDebugProxy/BrowserDebugHost.dll
Architecture: x64
Framework: 'Microsoft.AspNetCore.App', version '7.0.0-preview.5.22303.8' (x64)
.NET location: /usr/lib/dotnet/dotnet6-6.0.108/

The following frameworks were found:
  6.0.8 at [/usr/lib/dotnet/dotnet6-6.0.108/shared/Microsoft.AspNetCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed
```

**More info**
- I am running this on Ubuntu 22.04 and Rider 2022.2.1, but it seems VS Code has the same issue so I think it's a dotnet issue.
- I have dotnet6 installed in `/usr/lib/dotnet`, subfolder `dotnet6-6.0.108`
- I've had dotnet7 in multiple different folders to see if that would make any difference
- In Rider the `Toolset and Build` path for `.NET CLI executable path` is `/usr/lib/dotnet/dotnet7-7.0.100/dotnet` and the MSBuild path is that same folder but `sdk` subdirectory

It's worth noting that debugging a .NET 7 console project works fine, but not ASP.NET core.

I may uninstall .NET 6 to see if that would help but my hopes are a bit low after spending hours trying to get this to work. Any help would be appreciated.

### .NET Version

7.0.100-preview.7.22377.5

**Comment by DerekZiemba** [comment]
I also have this issue except it's with a console app. I can publish and build the app just fine, but if I try debugging:
![image](https://user-images.githubusercontent.com/7283693/186413948-d90ddff3-ae1d-4815-85e8-2cea6b2f71c4.png)

I went to net7.0 because I read debugging self contained single file apps worked.  But if I have `<SelfContained>true</SelfContained>`  I get 
![image](https://user-images.githubusercontent.com/7283693/186414314-540454a6-bc12-479e-ba9b-60010e495dc2.png)
So debugging self contains apps still seems to be broken...

**Comment by timbze** [comment]
Here's how to reproduce on Ubuntu 22.04:
1. Download both dotnet6 and dotnet7 sdks (both folders contain `dotnet` binary)
```
timmy@pc:~$ ls /usr/lib/dotnet
dotnet6-6.0.108  dotnet7
```
2. Link dotnet6 binary to `/usr/bin/dotnet` -- `sudo ln -s /usr/bin/dotnet6-6.0.108/dotnet /usr/bin/dotnet`
3. Try debugging Blazor WASM hosted app (`dotnet new blazorwasm -ho`)
4. **After app.Run() is called it exits with error "frameworks not found"**
5. Now link dotnet7 binary to `/usr/bin/dotnet` and debugging works -- `sudo ln -s /usr/bin/dotnet7/dotnet /usr/bin/dotnet`

Building and publishing works find with either dotnet7 or dotnet6 binary linked to `/usr/bin/dotnet`. I have Rider configured to use the right binaries and MSBuild files.

**Comment by lewing** [comment]
It's hard to know the exact scenario that is failing here without more details but if you want to target net6 with net7 sdk before rc1 I would suggest following the instructions here: https://github.com/dotnet/maui/wiki/.NET-7-and-.NET-MAUI

@thaystg can you verify debugging is working in the lastest rc1 builds in vs in 6 and 7 from VS

**Comment by timbze** [comment]
Since I found how to get it to work I'm fine now. It just seems there's an issue in the debug tooling someplace. **Maybe** it's not even related to dotnet since I'm using Rider on Ubuntu. I just thought it likely was because I had issues on VS Code as well.

**Comment by thaystg** [comment]
> It's hard to know the exact scenario that is failing here without more details but if you want to target net6 with net7 sdk before rc1 I would suggest following the instructions here: https://github.com/dotnet/maui/wiki/.NET-7-and-.NET-MAUI
> 
> @thaystg can you verify debugging is working in the lastest rc1 builds in vs in 6 and 7 from VS

It's working from VS, I'll test from VSCode and comment here.

**Comment by thaystg** [comment]
Yeah, it works on VS and VSCode.
