### ISSUE TITLE
[NativeAOT] Fail if a ILCompiler package runtime major version is different from target runtime

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#74387]
We support letting the user add an explicit `ILCompiler` package reference without specifying `PublishAOT` property (see test scenario [here](https://github.com/dotnet/sdk/blob/main/src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAnAotApp.cs#L312)). This is as part of the user story for native AOT [scenarios](https://github.com/dotnet/runtime/issues/72415#issuecomment-1205540035).

But we should generate an error when the targeted runtime major version is different from the package version as indicated in this issue [comment](https://github.com/dotnet/runtime/issues/74380#issuecomment-1222968875).

**Comment by jkotas** [comment]
The same problem can occur even when targeting the same major version, especially when updating between preview versions.

I think we should produce a warning when somebody specifies an explicit ILCompiler package reference. The explicit ILCompiler package references should be only used when one needs to validate a bug fix or similar situations.
