### ISSUE TITLE
ubsan discovers out of bounds array access in runtime/src/native/external/libunwind/src/aarch64/Ginit.c

### ISSUE THREAD

**Issue by RobertHenry6bev** [dotnet/runtime#74390]
### Description

Running on linux on ARM64 metal, running the gcperfsim workload, there' a single call into:
```
runtime/src/native/external/libunwind/src/aarch64/Ginit.c:50
50	    return &uc->uc_mcontext.regs[reg];
```
where the value of reg==32, and the array regs is declared to have 31 elements.

However, looking at the containing structure, unw_sigcontext, there's a declaration run like:
          uint64_t regs[31];
        uint64_t sp;
        uint64_t pc;
Which makes a little sense, in that indexing regs[31] will actually pick up the sp, as intended, and then a "shortcut" of regs[32] picks up the pc.  Maybe..

It's 3rd party code.

### Reproduction Steps

Compile for host machine ARM64 with g++-12 -fsanitize  Run gcperfsim.  Observe a runtime error at the source line.

### Expected behavior

no runtime error, perhaps because it is suppressed in the function uc_addr containing the miscreant.

### Actual behavior

a runtime error

### Other information

/cc @AaronRobinsonMSFT

**Comment by am11** [comment]
Lets report it upstream https://github.com/libunwind/libunwind/issues and we will  cherrypick the fix once there is one there.

**Comment by am11** [comment]
Lets report it upstream https://github.com/libunwind/libunwind/issues and we will  cherrypick the fix once there is one upstream.

**Comment by RobertHenry6bev** [comment]
I opened an issue upstream

https://github.com/libunwind/libunwind/issues/412

**Comment by RobertHenry6bev** [comment]
https://github.com/libunwind/libunwind/commit/612ebb80368ef69f713de06eaa3d924403ba9288 when applied to the copy of aarch64/Ginit.c in the dotnet/runtime seems to "work", in the sense that ubsan no longer notices an illegal index.
