### ISSUE TITLE
Directories created by extracting from a tar file do not have timestamps set

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#74398]
Related to https://github.com/dotnet/runtime/issues/73825

Extracting a tar file does not set timestamps on the directories it creates. Unix tar do set it.

As an aside, it appears our existing zip implementation doesn't do this either, whereas the zip/unzip tools do set it.

**Comment by danmoseley** [comment]
I made a start at fixing this: https://github.com/danmoseley/runtime/tree/tar.set.directory.time

However, I'm putting it aside because what I see happening (on Windows) is that the directory last written timestamp gets reset to current when a file is written to it. So as it is, the order in which extraction happens will affect the final timestamp. Taking this further would require some inspection of whether `tar` tries to deal with this (eg., by making a second pass through to set timestamps) or has the same problem.

**Comment by tmds** [comment]
`tar` sets the times on a directory when it finished adding items to it.

For out-of-order archives, a user can manually specify `--delay-directory-restore` which causes `tar` to apply the timestamps when all extraction is done.

**Comment by danmoseley** [comment]
Interesting. How important do you believe it is to set the directory timestamps? I guess some users expect the extracted tree to look exactly like the original.

**Comment by danmoseley** [comment]
As the gnu man page describes it, it sets the timestamp on each directory when it encounters the first file not in the directory. Does not sound too difficult. Any interest, @tmds 🙂

https://www.gnu.org/software/tar/manual/html_node/Directory-Modification-Times-and-Permissions.html

**Comment by tmds** [comment]
Yes, you can assign this to me.

> How important do you believe it is to set the directory timestamps? I guess some users expect the extracted tree to look exactly like the original.

I think if this works in .NET 8 that is fine.

**Comment by prettybits** [comment]
From a digital preservation standpoint having the ability to stay as close as possible to the original metadata incl. folder modification times would be ideal, so if a behaviour akin to `tar`'s `--delay-directory-restore` could be provided this would be much appreciated. If there is even a slim chance to move this ahead of the .NET 8 release this would be even better. Thanks for all the great work on tarfile support so far in any case!

**Comment by danmoseley** [comment]
@tmds are you still planning on this one? else we can mark up for grabs.
