### ISSUE TITLE
Unable to run binaries located on network shares

### ISSUE THREAD

**Issue by Const-me** [dotnet/runtime#74418]
### Description

The Linux runtime doesn't run binaries located on network shares.

### Reproduction Steps

Using Visual Studio, compile a hello, world console app based on .NET 3.1 runtime.

Share the output folder: right click in explorer, properties, Sharing, Advanced sharing

Mount that folder on a Linux computer with a command like that:
```
sudo mount -t cifs //192.168.0.***/share$/bin/Release /home/linaro/release -o 'username=***,password=*****,uid=1000,gid=1000' -o vers=2.0
```

Install .NET Runtime 3.1.28 on Linux.

Run the binary with the following command:
```
dotnet /home/linaro/release/helloworld.dll
```

### Expected behavior

Should print hello, world

### Actual behavior

```
$ dotnet /home/linaro/release/helloworld.dll
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/home/linaro/release/'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the /home/linaro/release/helloworld.runtimeconfig.json file specifying the appropriate framework.
```

### Regression?

No, still not fixed since at least .NET Core 2.1

### Known Workarounds

After copying the binaries to any Linux native file system, like `tmpfs` under `/tmp`, same binaries run fine despite the lack of `libhostpolicy.so` in that folder.

### Configuration

```
$ dotnet --info
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

Host (useful for support):
  Version: 3.1.28
  Commit:  ce3350c1cc

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.NETCore.App 3.1.28 [/opt/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### Other information

The target computer is a 32-bit ARM Linux, running Debian 10 "buster"

**Comment by wfurt** [comment]
can you check permissions and type on the `libhostpolicy.so` (ls -al libhostpolicy.so && file libhostpolicy.so)

**Comment by Const-me** [comment]
@vitek-karas Here’s the `HelloWorld.runtimeconfig.json` for a hello, world app based on .NET 3.1 and built with VS2022.

```
{
  "runtimeOptions": {
    "tfm": "netcoreapp3.1",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "3.1.0"
    },
    "configProperties": {
      "System.Reflection.Metadata.MetadataUpdater.IsSupported": false
    }
  }
}
```

I never publish anything, I build my stuff, and deploy the built DLLs along with `*.deps.json` and `*.runtimeconfig.json`. In case of ARM Linux, I also package the runtime into OS-specific packages, here’s [an old example](https://github.com/Const-me/Vrmac/blob/master/net-core/package) for Debian Linux.

**Comment by Const-me** [comment]
@vitek-karas Tried that trace thing, attaching the output: [host.txt](https://github.com/dotnet/runtime/files/9428591/host.txt)

As you see, the error says `Dependency manifest [/home/linaro/z/Test/HelloWorld.deps.json] does not exist`, but that’s not true:

```
$ ls -l /home/linaro/z/Test/
total 13
-rwxr-xr-x 1 linaro linaro  422 Aug 25 15:02 HelloWorld.deps.json
-rwxr-xr-x 1 linaro linaro 4608 Aug 25 22:32 HelloWorld.dll
-rwxr-xr-x 1 linaro linaro  260 Aug 25 15:02 HelloWorld.runtimeconfig.json
-rwxr-xr-x 1 linaro linaro 2068 Aug 25 22:34 host.txt
```

**Comment by wfurt** [comment]
You can try `trace -f  dotnet /home/linaro/release/helloworld.dll` @Const-me. (possibly add `-e trace=%file,%desc` if output is too verbose) (and perhaps try mount with `nobrl`)

**Comment by Const-me** [comment]
@wfurt nobrl changed nothing.

I don't have trace, but here's interesting lines from the end of the log made by `strace` tool.

```
getcwd("/home/linaro/z/Test", 4096)     = 20
lstat64("/home/linaro/z/Test/HelloWorld.dll", {st_mode=S_IFREG|0755, st_size=4608, ...}) = 0
stat64("/home/linaro/z/Test/HelloWorld.runtimeconfig.dev.json", 0xbedd3ef0) = -1 ENOENT (No such file or directory)
stat64("/home/linaro/z/Test/HelloWorld.runtimeconfig.json", {st_mode=S_IFREG|0755, st_size=260, ...}) = 0
stat64("/home/linaro/z/Test/HelloWorld.deps.json", {st_mode=S_IFREG|0755, st_size=422, ...}) = 0
stat64("/home/linaro/z/Test/libhostpolicy.so", 0xbedd4070) = -1 ENOENT (No such file or directory)
write(2, "A fatal error was encountered. T"..., 138A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/home/linaro/z/Test/'.) = 138
```

As you see, the runtime didn’t even bother to read the content of any files. It failed because it didn’t like something in the result of the `stat64()` system call.

Here's a few bits of information which might help.

`stat HelloWorld.deps.json` in a mounted folder:

```
  File: HelloWorld.deps.json
  Size: 422             Blocks: 1          IO Block: 16384  regular file
Device: 24h/36d Inode: 2251799816323074  Links: 1
Access: (0755/-rwxr-xr-x)  Uid: ( 1000/  linaro)   Gid: ( 1000/  linaro)
Access: 2022-08-25 22:33:32.720376500 +0000
Modify: 2022-08-25 15:02:54.484840100 +0000
Change: 2022-08-25 15:02:54.484840100 +0000
 Birth: -
```

`stat` of a copy in /tmp:

```
  File: /tmp/HelloWorld.deps.json
  Size: 422             Blocks: 8          IO Block: 4096   regular file
Device: b308h/45832d    Inode: 526         Links: 1
Access: (0755/-rwxr-xr-x)  Uid: ( 1000/  linaro)   Gid: ( 1000/  linaro)
Access: 2022-08-26 19:09:00.640924903 +0000
Modify: 2022-08-26 19:09:00.640924903 +0000
Change: 2022-08-26 19:09:00.640924903 +0000
 Birth: -
```

**Comment by wfurt** [comment]
The host logs
```
Executing as a self-contained app as per config file [/home/linaro/z/Test/HelloWorld.runtimeconfig.json]
```
that comes from the `stat`. @vitek-karas  would probably know why we are looking for the policy.

You an try to set 
```
export DOTNET_ROOT=/opt/dotnet
export DOTNET_MULTILEVEL_LOOKUP=0
```
This is not area of my expertise. I was mostly trying to see if there is anything fishy at the OS level.

**Comment by danmoseley** [comment]
It's not relevant to the issue, but please note that 3.1 is now in the last months of support.

**Comment by Const-me** [comment]
@danmoseley Well, I can reliably reproduce in .NET 6.0.8:

```
~/z/Test$ /tmp/dotnet/dotnet HelloWorld.dll
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/home/linaro/z/Test/'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because '/home/linaro/z/Test/HelloWorld.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the '/home/linaro/z/Test/HelloWorld.runtimeconfig.json' file and specify the appropriate framework.
~/z/Test$ /tmp/dotnet/dotnet --info

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: arm
  Commit:       55fb7ef977
```

This is despite I first reported the bug for .NET Core 2.1, see #33034, almost 2.5 years ago.

**Comment by elinor-fung** [comment]
> '/home/linaro/z/Test/HelloWorld.runtimeconfig.json' was not found.

This is why we end up assuming the app is self-contained (not having a `runtimeconfig.json` is treated as self-contained) and looking for `hostpolicy` next to it.

We use `access` and `realpath` for look for files - maybe they don't handle the mounted network share on that OS environment?

The error message from .NET 6.0.8 is based on `access` returning non-zero:

https://github.com/dotnet/runtime/blob/84454ad44d5f91c40b8cdd04e4df2b90a50d49cb/src/native/corehost/fxr/standalone/hostpolicy_resolver.cpp#L315-L318

https://github.com/dotnet/runtime/blob/84454ad44d5f91c40b8cdd04e4df2b90a50d49cb/src/native/corehost/hostmisc/pal.unix.cpp#L965-L968

When actually trying to read the runtime config, we use `realpath` to check for the file - I guess that is returning null for some reason:

https://github.com/dotnet/runtime/blob/84454ad44d5f91c40b8cdd04e4df2b90a50d49cb/src/native/corehost/runtime_config.cpp#L405-L409

https://github.com/dotnet/runtime/blob/84454ad44d5f91c40b8cdd04e4df2b90a50d49cb/src/native/corehost/hostmisc/pal.unix.cpp#L942-L945

**Comment by wfurt** [comment]
`realpath` will work only on symbolic links, right @elinor-fung ?

**Comment by elinor-fung** [comment]
I don't actually know. We also use it to look for the app dll itself though:
https://github.com/dotnet/runtime/blob/d5e3a5c2ca46691d65c81d520cb95f13f7a94652/src/native/corehost/fxr/command_line.cpp#L172-L175

**Comment by elinor-fung** [comment]
I had been trying to get a local repro without much luck using .NET 6.

I switched to 3.1 and was able to repro. Haven't had a chance to look more, but the trace looks similar, where `stat64` returns 0, but we don't attempt opening the runtime config.
```
# strace ~/dotnet-3-arm32/dotnet release/netcoreapp3.1/HelloWorld.dll 2>&1 | grep Hello
execve("/home/pi/dotnet-3-arm32/dotnet", ["/home/pi/dotnet-3-arm32/dotnet", "release/netcoreapp3.1/HelloWorld"...], 0xff8e64f4 /* 10 vars */) = 0
lstat64("/home/pi/release/netcoreapp3.1/HelloWorld.dll", {st_mode=S_IFREG|0755, st_size=4608, ...}) = 0
stat64("/home/pi/release/netcoreapp3.1/HelloWorld.runtimeconfig.dev.json", {st_mode=S_IFREG|0755, st_size=238, ...}) = 0
stat64("/home/pi/release/netcoreapp3.1/HelloWorld.runtimeconfig.json", {st_mode=S_IFREG|0755, st_size=260, ...}) = 0
stat64("/home/pi/release/netcoreapp3.1/HelloWorld.deps.json", {st_mode=S_IFREG|0755, st_size=422, ...}) = 0
stat64("/home/pi/release/netcoreapp3.1/HelloWorld.runtimeconfig.json", {st_mode=S_IFREG|0755, st_size=260, ...}) = 0
write(2, "Failed to run as a self-containe"..., 195Failed to run as a self-contained app. If this should be a framework-dependent app, add the /home/pi/release/netcoreapp3.1/HelloWorld.runtimeconfig.json file specifying the appropriate framework.) = 195
```

For .NET 6 (where it is working for me), we end up calling `lstat64` and do open/read the runtime config:
```
# strace ~/dotnet-6-arm32/dotnet release/net6.0/HelloWorld.dll 2>&1 | grep Hello
execve("/home/pi/dotnet-6-arm32/dotnet", ["/home/pi/dotnet-6-arm32/dotnet", "release/net6.0/HelloWorld.dll"], 0xffa721a4 /* 10 vars */) = 0
lstat64("/home/pi/release/net6.0/HelloWorld.dll", {st_mode=S_IFREG|0755, st_size=4608, ...}) = 0
lstat64("/home/pi/release/net6.0/HelloWorld.runtimeconfig.dev.json", 0xff99d518) = -1 ENOENT (No such file or directory)
lstat64("/home/pi/release/net6.0/HelloWorld.runtimeconfig.json", {st_mode=S_IFREG|0755, st_size=253, ...}) = 0
openat(AT_FDCWD, "/home/pi/release/net6.0/HelloWorld.runtimeconfig.json", O_RDONLY|O_LARGEFILE) = 3
lstat64("/home/pi/release/net6.0/HelloWorld.dll", {st_mode=S_IFREG|0755, st_size=4608, ...}) = 0
lstat64("/home/pi/release/net6.0/HelloWorld.deps.json", {st_mode=S_IFREG|0755, st_size=422, ...}) = 0
openat(AT_FDCWD, "/home/pi/release/net6.0/HelloWorld.deps.json", O_RDONLY|O_LARGEFILE) = 3
stat64("/home/pi/release/net6.0/HelloWorld.dll", {st_mode=S_IFREG|0755, st_size=4608, ...}) = 0
openat(AT_FDCWD, "/home/pi/release/net6.0/HelloWorld.dll", O_RDONLY|O_LARGEFILE) = 13
write(19, "Hello, World!\n", 14Hello, World!
```

We did have a [fix in 6.0](https://github.com/dotnet/runtime/pull/56224/files#diff-132e9dc7b24fef683059dc79c2f41ef25561275f0a4c6f0d4a2973c92e8e5088) such that we do a `realpath` check/conversion for the runtime config.

@Const-me would you be able collect/share a host trace (`COREHOST_TRACE`) and strace from your repro with .NET 6?

**Comment by elinor-fung** [comment]
Also checked that I could only repro on 32-bit ARM (used the arm32v7/debian:buster docker container). I wasn't able to repro with arm64 or x64.

**Comment by elinor-fung** [comment]
For the repro I had with 3.1, the `stat` call was failing with `Value too large for defined data type`. In 6.0+, we have https://github.com/dotnet/runtime/blob/71adfb003aa57f4c8801fc9079c9339342c58524/eng/native/configurecompiler.cmake#L307
I verified that if I rebuild 3.1 sources for `hostfxr` with that define and patch my 3.1 install, my repro goes away. Since you mentioned consistently hitting this with 6.0, it is likely not the same as what I hit.

Hopefully a host trace (`COREHOST_TRACE`) and strace from your .NET 6 repro can get us closer.
