### ISSUE TITLE
ClientWebSocket options are potentially silently ignored in case an invoker is passed

### ISSUE THREAD

**Issue by CarnaViire** [dotnet/runtime#74416]
Also discovered while looking at ClientWebSocket code.

If the user both passes a custom HttpMessageInvoker and sets security options like Credentials or RemoteCertificateValidationCallback, they seem to be just silently ignored, as the passed HttpMessageInvoker will be used without checking the options.
https://github.com/dotnet/runtime/blob/3824cb2931453d7818c6fff0762cc6f1c536a147/src/libraries/System.Net.WebSockets.Client/src/System/Net/WebSockets/WebSocketHandle.Managed.cs#L51

This might result in security issues.

Unless I miss something and there are checks somewhere that I haven't found, I believe we should forbid setting the security options in case a custom invoker is passed.

cc @greenEkatherine

**Comment by greenEkatherine** [comment]
Security options can be modified before invoker is passed. Should we throw in the case if they have different options?

**Comment by CarnaViire** [comment]
1. If it's possible to check whether all the options are same on the passed invoker, we should do that.
2. If it's not possible, I think we should throw in case they are set and user is passing an invoker.

cc @wfurt @stephentoub 
It is not enough to check that the following options are the same on the passed invoker, is it? There are things like LocalCertificateSelectionCallback that can override whatever is set in ClientCertificates, and it is always set by default, if I remember correctly, so would that mean we have only second option (throw without checking) available?
https://github.com/dotnet/runtime/blob/3824cb2931453d7818c6fff0762cc6f1c536a147/src/libraries/System.Net.WebSockets.Client/src/System/Net/WebSockets/WebSocketHandle.Managed.cs#L269-L291

**Comment by MihaZupan** [comment]
The invoker hides access to the underlying handler. Outside of reflection, you can't inspect its settings.

**Comment by CarnaViire** [comment]
Right, then the only option is to throw

**Comment by MihaZupan** [comment]
Reopening for 7.0 backport

**Comment by karelz** [comment]
Fixed in 8.0 (main) in PR #74473 and in 7.0 (RC2) in #75014.
