### ISSUE TITLE
RyuJIT: Allow promotions of structs with fields of struct containing a single primitive field.

### ISSUE THREAD

**Issue by sivarv** [dotnet/runtime#7441]
Right now the existing implementation allows only structs with pointer sized fields.  This would mean int/uint/ref/byref on 32-bit and long/ulong/ref/byref on 64-bit.  We should be able to permit promotion of a following struct on 64-bit, for example

`struct Foo { struct Bar { int a }, int b}`

Similarly the following struct both on 32-bit and 64-bit targets

`struct Foo { struct Bar { short a }, short b, int c }`
category:cq
theme:structs
skill-level:expert
cost:medium

**Comment by jakobbotsch** [comment]
I believe we are able to do this today, they don't need to be pointer sized anymore.
