### ISSUE TITLE
NonBacktracking treats timeout check boundaries as end-of-input for anchors

### ISSUE THREAD

**Issue by olsaarik** [dotnet/runtime#74467]
I found a bug related to the handling of timeout checks in `RegexOptions.NonBacktracking`, where the end of the innermost matching loop is treated as an end-of-input for anchors even if the matcher is just popping out of it to check for a timeout. The code below reproduces the bug for the current limit of 1000 characters between timeout checks. The assertion fails only with NonBacktracking and a timeout specified.

```
Regex testPattern = new Regex("^a*b$", RegexOptions.NonBacktracking, TimeSpan.FromHours(1));
string input = string.Concat(new string('a', 999), "bc");
Assert.False(testPattern.IsMatch(input));
```

I'll add a test for this, fix it and do some additional timeout improvements for NonBacktracking in a PR soon.

cc: @veanes @joperezr @stephentoub

**Comment by joperezr** [comment]
Great catch @olsaarik. If possible, can we separate the PRs where you are fixing this particular issue and the one about timeout checks in third phase? It is easier to make a case for a PR to meet the bar when changes are atomic and just addressing single issues. To me, seems like this one is about correctness, while the other one is more about reliability/expectations.

**Comment by olsaarik** [comment]
> Great catch @olsaarik. If possible, can we separate the PRs where you are fixing this particular issue and the one about timeout checks in third phase? It is easier to make a case for a PR to meet the bar when changes are atomic and just addressing single issues. To me, seems like this one is about correctness, while the other one is more about reliability/expectations.

Makes sense, I can do that. I should get both PRs out today.
