### ISSUE TITLE
Add ProcessInfo3 diagnostic IPC command to include libc type or equivalent

### ISSUE THREAD

**Issue by jander-msft** [dotnet/runtime#74476]
For diagnostic tools that want to load an ICorProfilerCallback implementation using the diagnostic communication channel's [AttachProfiler](https://github.com/dotnet/diagnostics/blob/main/documentation/design-docs/ipc-protocol.md#attachprofiler) command need to understand the architecture and libc type (glibc vs musl libc) in order to provide a path to profiler assembly with the matching architecture and libc type.

For tools that are not running in the same process namespace (e.g. dotnet-monitor), this is nearly impossible to determine based on any of the information available while the target process is suspended. The latest process info ([ProcessInfo2](https://github.com/dotnet/diagnostics/blob/main/documentation/design-docs/ipc-protocol.md#processinfo2)) command has OS and architecture information, but lacks libc type information. The environment block doesn't contain enough information to form a heuristic either; the following is an example environment block of an ASP.NET 6 Alpine container:

```json
{
  "PATH":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
  "HOSTNAME":"deploy-exampleapp-75cc844674-62w2q",
  "ASPNETCORE_URLS":"http://+:8080",
  "DOTNET_RUNNING_IN_CONTAINER":"true",
  "DOTNET_SYSTEM_GLOBALIZATION_INVARIANT":"true",
  "DOTNET_VERSION":"6.0.8",
  "ASPNET_VERSION":"6.0.8",
  "DOTNET_DiagnosticPorts":"/diag/port",
  "KUBERNETES_PORT_443_TCP_PORT":"443",
  "KUBERNETES_PORT_443_TCP_ADDR":"10.0.0.1",
  "KUBERNETES_SERVICE_HOST":"10.0.0.1",
  "KUBERNETES_SERVICE_PORT":"443",
  "KUBERNETES_SERVICE_PORT_HTTPS":"443",
  "KUBERNETES_PORT":"tcp://10.0.0.1:443",
  "KUBERNETES_PORT_443_TCP":"tcp://10.0.0.1:443",
  "KUBERNETES_PORT_443_TCP_PROTO":"tcp",
  "HOME":"/root"
}
```

The diagnostic pipe protocol should be updated with a new command (`ProcessInfo3`) that contains enough information to differentiate the libc type. Alternatively, this command could return the non-distribution specific runtime identifier (e.g. `linux-x64`, `linux-musl-x64`, `osx-arm64`, `win-x86`, etc), which is commonly used for packing assets for platform variations into the same package.

**Comment by tommcdon** [comment]
cc @davmason

**Comment by hoyosjs** [comment]
cc @steveisok @lambdageek since you all had brought up a RID - holding event.

**Comment by lambdageek** [comment]
Can we add some kind of extensible ProcessInfo3 command with a request version field or a list of requested values or something? I know there's a 64k namespace for commands, but I'm not sure if it's a great idea to burn it up for what is at core an inherently extensible query.

**Comment by davmason** [comment]
I think it makes sense to add an extensible ProcessInfo command. 

@jander-msft - for this particular use case, would it make more sense to build your profiler with a statically linked crt so you only have to have one per architecture?

**Comment by jander-msft** [comment]
> @jander-msft - for this particular use case, would it make more sense to build your profiler with a statically linked crt so you only have to have one per architecture?

My immediate concerns with doing that would be licensing incompatibilities, severe bloating of the profiler assembly, possible compiler incompatibilities, and distro compatibility. Not sure about the other technical aspects since I haven't tried statically linking the crt.

**Comment by davmason** [comment]
I think those are all valid concerns, it might be worth trying it out since it should just be a few changes to the build. If you statically link the world then it should run on any distro as long as the architecture matches, but size on disk is a concern. I would be interested to see how drastically it changes the size. I would hope that the linker would be able to aggressively trim unused code.

For licenses, IANAL but libc++ is MIT and libstdc++ has a GPL exception to allow static linking so it should be fine from the CRT perspective.

In case it's not clear, I'm just trying to get more data about your scenario - the static linking discussion is independent of the new ProcessInfo command that I am in favor of. If static linking is not a good idea I'd like to understand why so in future conversations with profiler authors I can give the best advice.

**Comment by jkotas** [comment]
>  libc++ is MIT and libstdc++ has a GPL exception

You need a libc. glibc is GPL. It does not have any exceptions for static linking, and also it is not designed for static linking.

You would need to use musl that is alternative MIT libc implementation designed for static linking: https://www.musl-libc.org/how.html

**Comment by jander-msft** [comment]
> I think those are all valid concerns, it might be worth trying it out since it should just be a few changes to the build. If you statically link the world then it should run on any distro as long as the architecture matches, but size on disk is a concern. I would be interested to see how drastically it changes the size. I would hope that the linker would be able to aggressively trim unused code.
> 
> For licenses, IANAL but libc++ is MIT and libstdc++ has a GPL exception to allow static linking so it should be fine from the CRT perspective.
> 
> In case it's not clear, I'm just trying to get more data about your scenario - the static linking discussion is independent of the new ProcessInfo command that I am in favor of. If static linking is not a good idea I'd like to understand why so in future conversations with profiler authors I can give the best advice.

I'm not opposed to it and will try to explore if this is a viable option for us. I had a brief discussion with one my teammates today about this and we think it has potential to solve a few problems, namely not needing to target specific crt, it might possibly reduce our package size at the end of it all if we are going from two profilers down to one + statically linked crt, and may give us a path to reduce dependencies in general. I think there are two main concerns that we have:
- if the crt has any dependencies on other libraries or if the other potential dependencies that our library has can be met on all Linux distros. It might be difficult to get into a position where all of our dependencies are statically linked. I still have to catalog them so I don't have data at this time.
- if the version of crt that we do statically link has any vulnerabilities, then we need a means to know when those vulnerabilities are disclosed and fixed. I'm sure that's a solved problem in some sense, but we'll want to tap into some automated way of being notified and somehow picking up the new version of the library

**Comment by jander-msft** [comment]
> > libc++ is MIT and libstdc++ has a GPL exception
> 
> You need a libc. glibc is GPL. It does not have any exceptions for static linking, and also it is not designed for static linking.
> 
> You would need to use musl that is alternative MIT libc implementation designed for static linking: https://www.musl-libc.org/how.html

That was my thought as well, that we could use libc++ since its license is compatible. Do you know of any prior art in the dotnet repos where statically linking a crt is being done? My quick search hasn't yielded anything.

**Comment by jkotas** [comment]
We do not statically link libc anywhere in the dotnet repos. Static linking libc is not a good fit for the .NET runtime.

**Comment by jander-msft** [comment]
@jkotas, I'm going to be taking over @davmason's work for this issue and wanted to get your opinion on this given your comments [here](https://github.com/dotnet/runtime/pull/86610#discussion_r1202925150).

### Option 1: Reporting portable RID
Your reservation I believe is that what if the reported RID was not something clearly understood e.g. `void-x64`. I was thinking that this property could report the non-distro portable OS RIDs (with architecture included):
- `linux-<arch>`
- `linux-musl-<arch>`
- `osx-<arch>`
- `win-<arch>`

It would fallback to `unknown` if a value could not be deterministically reported.

Depending on how the runtime is built for Void Linux (their [main page](https://voidlinux.org/) implies it supports both?), it would return either `linux-<arch>` or `linux-musl-<arch>`.

These could probably be calculated via build defines and reported as-is without dynamically interrogating some aspect of the process.

As evidence of this existing usage, using the portable RIDs seems fairly used pattern in NuGet packages when indicating what platform a native library works on:
- https://github.com/dotnet/build-sourcecontrol/blob/af797c6fa204099110a3fa2b1ac58c435243f8d2/src/Microsoft.Build.Tasks.Git/Microsoft.Build.Tasks.Git.nuspec#L21
- https://github.com/dotnet/jitutils/blob/c38952cdc42aeb3f6ce5dcb4091a951ca20a1a79/src/coredistools/.nuget/Microsoft.NETCore.CoreDisTools.nuspec#L18
- https://github.com/dotnet/ClangSharp/blob/2ccd672ee16097691deb9a447483c7e9d17586e6/packages/libClangSharp/libClangSharp.runtime.linux-arm64/libClangSharp.runtime.linux-arm64.nuspec#L18
- https://github.com/dotnet/Nerdbank.GitVersioning/blob/f9b3dbb8601e26d4d0522d48eec1aeed162a7754/src/Nerdbank.GitVersioning.Tasks/Nerdbank.GitVersioning.nuspec#L35

The portable RID is also how we represent our supported profiler scenarios within the .NET Monitor tool packages.

### Option 2: Reporting "libc" variant
For Linux, I know there's glibc and musl libc; there are probably others but I don't know. This could report `gnu` or `musl` for a libc property. This matters less for Windows and OSX, but we'd have to have some moniker in place (or just fallback to `unknown`). These probably could be determined from the build defines; another option is to dynamically lookup the c library somehow, map that into a known list of c library to libc monikers, and then report that value.

It would fallback to `unknown` if a value could not be deterministically reported.

**Comment by jkotas** [comment]
> These could probably be calculated via build defines and reported as-is without dynamically interrogating some aspect of the process.

Returning the portable RID that is baked-in as a constant string at build time sounds reasonable to me.

This won't give you information about libc version. You won't be able to tell whether the available libc version is compatible with what you need (e.g. whether it is too old). Is that ok?

> For Linux, I know there's glibc and musl libc; there are probably others but I don't know. 

The third main one is bionic libc.
