### ISSUE TITLE
JIT: register shuffles after the null inlinee gc refs change

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#7447]
dotnet/coreclr#9479 created some cases where the RA did back to back register shuffles that weren't there before. Would be nice to get rid of these.

Some examples from the core library:
```asm
System.CurrentSystemTimeZone:.ctor():this

       call     CachedData:CreateLocal():ref:this
       mov      rdi, rax
G_M12143_IG03:
       mov      rax, rdi
       mov      rdi, rax

System.String:Concat(ref):ref

       call     CORINFO_HELP_ASSIGN_REF
G_M54378_IG15:
       mov      rax, rdi
       mov      rdi, rax

System.DateTime:FromBinary(long):struct

       call     CachedData:CreateLocal():ref:this
       mov      rbp, rax
G_M34503_IG04:
       mov      rcx, rbp
```
category:cq
theme:register-allocator
skill-level:expert
cost:medium

**Comment by kunalspathak** [comment]
@AndyAyersMS  - I tried to double check the disassembly for `Concat` and `FromBinary` using `superpmi replay libraries.crossgen.mch` and I don't see duplicate movs. Could you confirm how you verified this just to make sure I am checking the right thing? Also, is this for Windows / x64?

**Comment by AndyAyersMS** [comment]
Yes, this was windows x64. 

I don't have notes for that issue or PR. Likely this was something I noticed while running jit diffs via crossgen. Likely a lot has changed in the past 3 years; if you don't see those same issues now, then I'd just close this.

**Comment by kunalspathak** [comment]
Ok, Thanks!
