### ISSUE TITLE
[API Proposal]: Convenient integers reading

### ISSUE THREAD

**Issue by vorotynsky** [dotnet/runtime#74489]
### Background and motivation

C# doesn't have an API to read rows of integers from the console nicely.

One of the solutions is:
```csharp
var array = Console.ReadLine()!.Split(' ', StringSplitOptions.RemoveEmptyEntries);
array = Array.ConvertAll(array, Int32.Parse);
```
Such a code is necessary for solving problems at codeforces or olympiads.

### API Proposal

```csharp
namespace System.IO;

public static class ReaderExtensions
{
    public static Int32 ReadInt32(this TextReader reader) { throw null; }

    // methods for other types
}
```

### API Usage

```csharp
var array = new int[10];

for (var i = 0; i < 10; i++)
    array[i] = Console.In.ReadInt32();
```

#### C++ operators

```cpp
int arr[10];

for (int i = 0; i < 10; i++)
    std::cin >> arr[i];
```

#### Java's `Scanner`

```java
Scanner scanner = new Scanner(System.in);
int[] arr = new int[10];

for (int i = 0; i < 10; i++)
    arr[i] = scanner.nextInt();
```

#### Text format

C has function `scanf`, and F#, Go has the same API.

C# can adopt it like this:
```csharp
Console.In.Scanf("%i", ref arr[i]);
```

#### Just read a word
```csharp
for (int i = 0; i < 10; i++)
    arr[i] = Int32.Parse(Console.ReadWord());
```

**Comment by svick** [comment]
Related: https://github.com/dotnet/runtime/issues/64621, which proposes a different API with the same goal.

**Comment by adamsitnik** [comment]
Hi @vorotynsky 

Thank you for your proposal. Since #64621 was opened first and includes proposal for other types as well I am going to close this issue as a duplicate. Please follow #64621 for updates.
