### ISSUE TITLE
Add source-build leg to llvm-project

### ISSUE THREAD

**Issue by crummel** [dotnet/runtime#74505]
Following https://github.com/dotnet/runtime/issues/69611, we added llvm-project to the source-build in installer.  There are two things remaining to truly add llvm-project:
- llvm-project needs to build and publish a source-build leg.
- After this has been done, runtime needs to take a dependency on that and add it to Version.Details.xml.

The documentation for this process is at https://github.com/dotnet/source-build/tree/main/Documentation/planning/arcade-powered-source-build and the dotnet/source-build-internal group can help with any issues.

**Comment by akoeplinger** [comment]
Note: the objwriter packages are produced by the `objwriter/12.x` branch: https://github.com/dotnet/llvm-project/tree/objwriter/12.x

**Comment by steveisok** [comment]
@hoyosjs Do you know who is the right person to tag?  The objwriter branch is pulled in by NativeAOT and is not something we manage.

**Comment by hoyosjs** [comment]
fyi @MichalStrehovsky  @jkotas @LakshanF

**Comment by jkotas** [comment]
> llvm-project needs to build and publish a source-build leg.

@crummel Do you have a simple example of it is about from other repos? I was not able to figure it out from the linked documentation.

**Comment by jkotas** [comment]
Also, is it still going to be required for 8.0 given the planned source build changes?

**Comment by crummel** [comment]
I've summarized what I believe to be the current state of play and the agreed-upon solution for NativeAOT in 7.0 in https://github.com/dotnet/runtime/pull/76206.  Please check this out and let me know if you have any concerns.

**Comment by TIHan** [comment]
Resolved by https://github.com/dotnet/runtime/pull/99733
