### ISSUE TITLE
NET-6 - Error on loading default value of My.Settings

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#74528]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-6---Error-on-loading-default-value-o/1668022)._

---
[regression] [worked-in:17.1]
Hi.
I'm running a Net-6 Windows Forms application. I configured a "string setting" using its default, as below:

! [image.png] (https://aka.ms/dc/image?name=Bccf250bb4b8044cfa8992dff97c51fbd637806271714123796_20220216-135251-image.png&tid=ccf250bb4b8044cfa8992dff97c51fbd637806271714123796)

When I load the system, at Module1 I read this value into a Friend variable:

**Friend Cert_Folder As String = My.Settings.CertFolder & ""**

... and I get this error on DEBUG RUN the project:

! [image.png] (https://aka.ms/dc/image?name=Bdfcd7ab536104847b76d96747af16c85637806273588083016_20220216-135558-image.png&tid=dfcd7ab536104847b76d96747af16c85637806273588083016)

I appreciate for any help.

---
#### Feedback Bot on 2/16/2022, 06:06 PM: 

(private comment, text removed)
#### Feedback Bot on 6/1/2022, 11:59 PM: 

(private comment, text removed)
#### Fiona Niu[MSFT] on 6/30/2022, 03:18 AM: 

(private comment, text removed)
#### David Svaiter on 7/4/2022, 08:03 AM: 

(private comment, text removed)
#### David Svaiter on 7/20/2022, 06:36 PM: 

(private comment, text removed)
#### Feedback Bot on 7/4/2022, 11:53 PM: 

(private comment, text removed)
#### Viktor Hofer [MSFT] on 7/20/2022, 03:01 AM: 

(private comment, text removed)
#### David Svaiter on 7/20/2022, 06:37 PM: 

(private comment, text removed)

---
#### David Svaiter solved on 2/17/2022, 05:32 AM, 0 votes: 

<p>Searching for any help in internet, I found a post as of Dec 2021 in NET-CORE Github, advising to simply DELETE THE “APP.CONFIG” file and execute the application. It solved the problem.</p>
<p>But, as I could see, neither the problem ieself had been solved, not this solution is implemented into NET 6.0.xx as a “detour”.</p>

#### Dan Moseley [MSFT] on 7/8/2022, 10:54 AM: 

(private comment, text removed)
#### Buyaa Namnan [MSFT] solved on 8/24/2022, 02:44 PM, 0 votes: 

<p><a target='_blank' href="https://developercommunity.visualstudio.com/user/20047/profile">David Svaiter</a> thanks for providing a repro project.</p>
<p>Looks .NET Core doesn’t pre-register config section for system.diagnostics. You need to add <code>&lt;section name=&quot;system.diagnostics&quot; type=&quot;System.Diagnostics.DiagnosticsConfigurationHandler&quot;/&gt;</code> section in your App.config file within <code>&lt;configSections&gt; ... &lt;/configSections&gt;</code> like below:</p>
<pre><code>    <span class="hljs-tag">&lt;<span class="hljs-name">configSections</span>&gt;</span>
	<span class="hljs-tag">&lt;<span class="hljs-name">section</span> <span class="hljs-attr">name</span>=<span class="hljs-string">"system.diagnostics"</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"System.Diagnostics.DiagnosticsConfigurationHandler"</span>/&gt;</span>
    <span class="hljs-tag">&lt;/<span class="hljs-name">configSections</span>&gt;</span>
  
</code></pre>
<p>Please let us know if you encounter other issue, this workaround works well with the small repro you provided</p>

**Comment by buyaa-n** [comment]
This is quite similar to https://github.com/dotnet/runtime/issues/930

**Comment by buyaa-n** [comment]
Closing this issue as `system.diagnostics` is added to the implicit machine config list with https://github.com/dotnet/runtime/pull/73087 
https://github.com/dotnet/runtime/blob/40df8f6a4c1a1b0b1b731f2a8023b5bb10357790/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ImplicitMachineConfigHost.cs#L84

Startin from .Net 7.0 you don't need to do the workaround, if you had a workaround already added, need to remove it now
