### ISSUE TITLE
HttpClientHandler.AllowAutoRedirect is not working as expected on servers

### ISSUE THREAD

**Issue by sumit84mca** [dotnet/runtime#74548]
### Description

I have a requirement that I need to capture intermediate redirects. I used HttpClientHandler.AllowAutoRedirect Property and set it false. It working as expected when I am running the application on my laptop. 

But when I run same app on the server (Window-Server 2019) it not capturing the intermediate responses. It just returns final response with 200. All redirect responses 300-399 are skipped. 

### Reproduction Steps

Use below code and create console app and run

```c#
using System.Net;
HttpClientHandler handler = new HttpClientHandler();
handler.AllowAutoRedirect = false;
// Create an HttpClient object
HttpClient httpClient = new HttpClient(handler);
var InitialUrl = "any url that returns redirect responses";

while (true)
{
    Console.WriteLine(InitialUrl);

    var clickResponse = await httpClient.GetAsync(InitialUrl);
    int responseStatus = (int)clickResponse.StatusCode;
    if (responseStatus >= 300 && responseStatus <= 308)
    {
        // continue on redirect        
        InitialUrl = clickResponse.Headers.Location.AbsoluteUri;
    }
    else if (responseStatus >= 400 && responseStatus <= 511)
    {        
        //break because of error
        break;
    }
    else if (clickResponse.IsSuccessStatusCode)
    {     
        // break on success
        break;
    }
}
Console.ReadLine();
```

### Expected behavior

The code must work similarly on Client OS and Server OS. It should capture intermediate redirect responses on the server.

### Actual behavior

It is not capturing intermediate redirect responses but the final response with status 200 on server OS.

### Regression?

Don't know working on it first time.

### Known Workarounds

Don't know

### Configuration

My PC (Client PC Configuration)
OS Name:                       Window 10 Pro
OS Version:                    10.0.19044 N/A Build 19044
OS Configuration:          Standalone Workstation
System Type:                  x64-based PC
Processor(s):                  1 Processor(s) Installed. 
                                      [01]: Intel64 Family 6 Model 142 Stepping 10 GenuineIntel ~1910 Mhz
Installed NetCoreSDK:   6.0.107 

Server
OS Name:                       Microsoft Windows Server 2019 Datacenter
OS Version:                    10.0.17763 N/A Build 17763
OS Configuration:          Standalone Server
System Type:                  x64-based PC
Processor(s):                  8 Processor(s) Installed.
                                      [01]: Intel64 Family 6 Model 45 Stepping 7 GenuineIntel ~2900 Mhz
                                      [02]: Intel64 Family 6 Model 45 Stepping 7 GenuineIntel ~2900 Mhz
                                      [03]: Intel64 Family 6 Model 45 Stepping 7 GenuineIntel ~2900 Mhz
                                      [04]: Intel64 Family 6 Model 45 Stepping 7 GenuineIntel ~2900 Mhz
                                      [05]: Intel64 Family 6 Model 45 Stepping 7 GenuineIntel ~2900 Mhz
                                      [06]: Intel64 Family 6 Model 45 Stepping 7 GenuineIntel ~2900 Mhz
                                      [07]: Intel64 Family 6 Model 45 Stepping 7 GenuineIntel ~2900 Mhz
                                      [08]: Intel64 Family 6 Model 45 Stepping 7 GenuineIntel ~2900 Mhz
BIOS Version:                 Xen 4.13, 1/26/2021
Installed NetCoreSDK:   6.0.302

**Comment by wfurt** [comment]
is there chance that there is some proxy that resolves the redirects @sumit84mca? Do you have packet captures for plain HTTP?

**Comment by sumit84mca** [comment]
I am not aware of proxies on servers. but on my PC there is a zscalar proxy. I have tested same code on Azure VM, AWS EC2 instance and some other Cloud VM. It not running on any server.

By the pls let me know how can I capture the packet for HTTP?

**Comment by wfurt** [comment]
https://www.wireshark.org/ set filter to `host my.site`

**Comment by sumit84mca** [comment]
Hi,
Just figured it out why it was not working. There was location filter on the server. It was accepting requests from India only. And our server was out on India. Hence it was not forwarding any request to other server. 
Thank you all for your time.
