### ISSUE TITLE
Test failure GC\\Scenarios\\muldimjagary\\muldimjagary\\muldimjagary.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#74541]
Run: [runtime-coreclr jitstress 20220823.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1963172&view=ms.vss-test-web.build-test-results-tab&runId=50395902&resultId=106970&paneView=debug)

Failed test:
```
coreclr windows x64 Checked jitminopts @ Windows.10.Amd64.Open

- GC\\Scenarios\\muldimjagary\\muldimjagary\\muldimjagary.cmd
```
**Error message:**
```
Assert failure(PID 6684 [0x00001a1c], Thread: 7292 [0x1c7c]): !"should not happen for regions!"

CORECLR! WKS::gc_heap::allocate_in_condemned_generations + 0xA8C (0x00007fff54afebbc) CORECLR! WKS::gc_heap::plan_phase + 0x2F5C (0x00007fff54b21c4c)
CORECLR! WKS::gc_heap::gc1 + 0x240 (0x00007fff54b11570) CORECLR! WKS::gc_heap::garbage_collect + 0x731 (0x00007fff54b112d1)
CORECLR! WKS::GCHeap::GarbageCollectGeneration + 0x452 (0x00007fff54af90c2) CORECLR! WKS::gc_heap::trigger_gc_for_alloc + 0x62 (0x00007fff54b2c4e2)
CORECLR! WKS::gc_heap::try_allocate_more_space + 0x31D (0x00007fff54b2c98d) CORECLR! WKS::GCHeap::Alloc + 0x301 (0x00007fff54af7b51)
CORECLR! Alloc + 0x1E9 (0x00007fff54788699) CORECLR! AllocateObject + 0x422 (0x00007fff54789e92)
File: D:\a_work\1\s\src\coreclr\gc\gc.cpp Line: 19429
Image: C:\h\w\B3AB09C5\p\corerun.exe

Return code:      1
Raw output file:      C:\h\w\B3AB09C5\w\B22009EA\uploads\Reports\GC.Scenarios\muldimjagary\muldimjagary\muldimjagary.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\B3AB09C5\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  muldimjagary.dll
Test should return with ExitCode 100 ...
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\B3AB09C5\p
C:\h\w\B3AB09C5\w\B22009EA\e\GC\Scenarios\muldimjagary\muldimjagary\muldimjagary.cmd
Expected: True
Actual:   False


Stack trace
   at GC_Scenarios._muldimjagary_muldimjagary_muldimjagary_._muldimjagary_muldimjagary_muldimjagary_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by mangod9** [comment]
@mrsharm could you please check if this can be reproed and/or dump is available?

**Comment by AntonLapounov** [comment]
+@Maoni0 regarding `"should not happen for regions!"`.  Please see `corerun.exe.6684.dmp`.

**Comment by mrsharm** [comment]
Thanks, @AntonLapounov! Was taking a look at the dump a bit back and unfortunately some of the important stress log messages are not enabled for these Jit stress tests; these messages could have given us some indication about a hypothesized condition that's causing this assertion i.e. an OOM that's causing the assertion failure.

The pertinent code is the following that indicates that ``next_seg`` is null and this can be possible if ``generation_start_segment`` is null; this is hypothesized to be only possible if we OOM.

```c++
#ifdef USE_REGIONS
                        set_region_plan_gen_num (seg, to_gen_number);
                        if ((next_seg == 0) && (heap_segment_gen_num (seg) > 0))
                        {
                            // We need to switch to a younger gen's segments so the allocate seg will be in
                            // sync with the pins.
                            next_seg = generation_start_segment (generation_of (heap_segment_gen_num (seg) - 1));
                            dprintf (REGIONS_LOG, ("h%d aic: switching to next gen%d start %Ix(%Ix)",
                                heap_number, heap_segment_gen_num (next_seg), (size_t)next_seg,
                                heap_segment_mem (next_seg)));
                        }
#endif //USE_REGIONS

                        if (next_seg)
                        {
                            init_alloc_info (gen, next_seg);
                        }
                        else
                        {
#ifdef USE_REGIONS
                            assert (!"should not happen for regions!");
#else
                            return 0; //should only happen during allocation of generation 0 gap
                            // in that case we are going to grow the heap anyway
#endif //USE_REGIONS
                        }
                    }
```

Our next best bet is to repro this issue. From the frequency [here](https://dev.azure.com/dnceng/public/_build/results?buildId=1963172&view=ms.vss-test-web.build-test-results-tab&runId=50395902&resultId=106970&paneView=history), it seems like this issue doesn't occur often; will run this repro overnight to see if we can get a dump with the gc stress logs enabled:

![image](https://user-images.githubusercontent.com/68247673/186948364-ac261e66-6b89-42c7-95e9-6356d9772333.png)

**Comment by mrsharm** [comment]
@mangod9, this bug isn't actionable and as a result, I'll be closing this since:

1. The Jit Stress Bugs don't have Trace GC enabled for us to peer into the GC logs from the dumps.
2. This failure hasn't repro'd since the one and only time. 

My follow ups are to reach out to the Jit Stress team and get the Trace GCs enabled.

**Comment by mrsharm** [comment]
@v-wenyuxu, please reopen this issue if this repros. Seems like it was hit only once and I am unable to repro this locally.

**Comment by AntonLapounov** [comment]
"Can't repro" bugs should be closed as "not planned":
![image](https://user-images.githubusercontent.com/21268817/188332010-9ad40567-2897-4698-adfa-017a6f3c10b7.png)

**Comment by mrsharm** [comment]
Thanks, @AntonLapounov! Done.
