### ISSUE TITLE
LoggerMessageGenerator and JsonSourceGenerator not using incremental generator caching

### ISSUE THREAD

**Issue by 3schwartz** [dotnet/runtime#74557]
While reading up upon `IIncrementalGenerator` I saw the implementation of `LoggerMessageGenerator` and `JsonSourceGenerator`. See 
https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Logging.Abstractions/gen/LoggerMessageGenerator.Roslyn4.0.cs and https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/gen/JsonSourceGenerator.Roslyn4.0.cs.

I was reading this [blog](https://www.thinktecture.com/en/net/roslyn-source-generators-performance/) and the [main documentation](https://github.com/dotnet/roslyn/blob/main/docs/features/incremental-generators.md#authoring-a-cache-friendly-generator) and both describes one shouldn't combine with the whole compilation, since this will trigger the flow of every key stroke in the IDE.

As an example, create a new library `ExampleGenerator` and have `ExampleGenerator.csproj` look like

```Xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <LangVersion>Latest</LangVersion>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.3" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.2.0" PrivateAssets="all" />
	</ItemGroup>
	
</Project>
```

Create file `ExampleGenerator.cs` with the following incremental generator
```C#
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

namespace ExampleGenerator
{
    [Generator]
    public class ExampleGenerator : IIncrementalGenerator
    {
        private static int counter;

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(context => context.AddSource(
                "ExampleExtensionAttribute.g.cs", SourceText.From(@"
namespace Example
{
    [System.AttributeUsage(System.AttributeTargets.Enum)]
    public class ExampleExtensionAttribute : System.Attribute
    {}
}", Encoding.UTF8)));

            var classProvider = context.SyntaxProvider
                .CreateSyntaxProvider(
                    static (node, _) => node is EnumDeclarationSyntax m && m.AttributeLists.Count > 0,
                    static (c, _) => GetEnumDeclarationSyntax(c))
                .Where(static e => e is not null)
                .Collect()
                .Combine(context.CompilationProvider);

            context.RegisterSourceOutput(classProvider,
                static (spc, source) => Execute(source.Left, source.Right, spc));
        }

        private static void Execute(ImmutableArray<EnumDeclarationSyntax?> classes, Compilation compilation, SourceProductionContext context)
        {
            foreach (var c in classes)
            {
                context.AddSource($"Example.{c.Identifier.Text}.cs", $@"
// Counter: {Interlocked.Increment(ref counter)}

namespace Example
{{
   partial class {c.Identifier.Text}
   {{
   }}
}}
");
            }
        }

        private static EnumDeclarationSyntax? GetEnumDeclarationSyntax(GeneratorSyntaxContext context)
        {
            var enumDeclarationSyntax = (EnumDeclarationSyntax)context.Node;

            foreach (AttributeListSyntax attributeListSyntax in enumDeclarationSyntax.AttributeLists)
            {
                foreach (AttributeSyntax attributeSyntax in attributeListSyntax.Attributes)
                {
                    if (context.SemanticModel.GetSymbolInfo(attributeSyntax).Symbol is not IMethodSymbol attributeSymbol)
                    {
                        continue;
                    }

                    INamedTypeSymbol attributeContainingTypeSymbol = attributeSymbol.ContainingType;
                    string fullName = attributeContainingTypeSymbol.ToDisplayString();

                    if (fullName == "Example.ExampleExtensionAttribute")
                    {
                        return enumDeclarationSyntax;
                    }
                }
            }
            return null;
        }
    }
}
```

*Thanks to [Pawel Gerr](https://www.thinktecture.com/en/net/roslyn-source-generators-performance/) for the counter idea and [Andrew Lock](https://andrewlock.net/creating-a-source-generator-part-1-creating-an-incremental-source-generator/) for example how find enums with attributes.*

Now create a console project `ExampleConsole` and have `ExampleConsole.csproj` look like
```Xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExampleGenerator\ExampleGenerator.csproj"
					      ReferenceOutputAssembly="false"
                          OutputItemType="Analyzer" />
  </ItemGroup>

</Project>
```

Create three files with enums, two which have the attribute.

`SomeOther.cs`
```C#
namespace ExampleConsole
{
    internal enum SomeOther
    {
    }
}
```
`Bar.cs`
```C#
namespace ExampleConsole
{
    [ExampleExtension]
    internal enum Bar
    {
    }
}
```
`Foo.cs`
```C#
namespace ExampleConsole
{
    [ExampleExtension]
    internal enum Foo
    {
    }
}
```

Now if you do ANY changes to any file, you can see in Dependencies->Analyzers->ExampleGenerator that both `Example.Bar.cs` and `Example.Foo.cs` have their counter increased.

Hence the caching of the incremental generator isn't used and the generator behave much like the  old source generator. The old implementation has performance issues, https://github.com/dotnet/runtime/issues/56702, and I expect this isn't seen now due to some better filtering in the predicate and target - but I'm not sure why.

## Proposed solution
To get caching I suggest adding a custom comparer. Update the incremental generator with the code below and rebuild the project (possible also reload the IDE).

```C#
namespace ExampleGenerator
{
    [Generator]
    public class ExampleGenerator : IIncrementalGenerator
    {
        private static int counter;
        private readonly CustomComparer comparer = new();

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            ...

            var classProvider = context.SyntaxProvider
                .CreateSyntaxProvider(
                    static (node, _) => node is EnumDeclarationSyntax m && m.AttributeLists.Count > 0,
                    static (c, _) => GetEnumDeclarationSyntax(c))
                .Where(static e => e is not null)
                .Collect()
                .Combine(context.CompilationProvider)!
                .WithComparer(comparer);

            context.RegisterSourceOutput(classProvider,
                static (spc, source) => Execute(source.Left, source.Right, spc));
        }

        ....

        internal class CustomComparer : IEqualityComparer<(ImmutableArray<EnumDeclarationSyntax> Left, Compilation Right)>
        {
            public bool Equals((ImmutableArray<EnumDeclarationSyntax> Left, Compilation Right) x, (ImmutableArray<EnumDeclarationSyntax> Left, Compilation Right) y)
            {
                return x.Left.Equals(y.Left);
            }

            public int GetHashCode((ImmutableArray<EnumDeclarationSyntax> Left, Compilation Right) obj)
            {
                return obj.Left.GetHashCode();
            }
        }
    }
}
```

Now the counter in the generated files isn't incremental an any changes in the IDE. The counter only change when there are changes to some of the classes with the attribute.

Syntax Node are now used for caching and comparison, from [Pawel Gerr](https://www.thinktecture.com/en/net/roslyn-source-generators-performance/) this is immutable between recompilation. I tried validating this statement in Microsoft general documentation but couldn't find this elsewhere. The above however works.

## Better solution but needs more refactoring

Due to the `.Collect()` the comparing isn't done on single files. To solve this one could provide a `IncrementalValuesProvider` instead of a `IncrementalValueProvider`.

Following the example from above this would be to update the generator with code as below

```C#
namespace ExampleGenerator
{
    [Generator]
    public class ExampleGenerator : IIncrementalGenerator
    {
        private static int counter;
        private readonly CustomComparer comparer = new();

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {

            ....

            var classProvider = context.SyntaxProvider
                .CreateSyntaxProvider(
                    static (node, _) => node is EnumDeclarationSyntax m && m.AttributeLists.Count > 0,
                    static (c, _) => GetEnumDeclarationSyntax(c))
                .Where(static e => e is not null)
                .Combine(context.CompilationProvider)!
                .WithComparer(comparer);

            context.RegisterSourceOutput(classProvider,
                static (spc, source) => Execute(source.Left, source.Right, spc));
        }

        private static void Execute(EnumDeclarationSyntax c, Compilation compilation, SourceProductionContext context)
        {
            context.AddSource($"Example.{c.Identifier.Text}.cs", $@"
// Counter: {Interlocked.Increment(ref counter)}

namespace Example
{{
   partial class {c.Identifier.Text}
   {{
   }}
}}
");
        }
        
        ....

        internal class CustomComparer : IEqualityComparer<(EnumDeclarationSyntax Left, Compilation Right)>
        {
            public bool Equals((EnumDeclarationSyntax Left, Compilation Right) x, (EnumDeclarationSyntax Left, Compilation Right) y)
            {
                return x.Left.Equals(y.Left);
            }

            public int GetHashCode((EnumDeclarationSyntax Left, Compilation Right) obj)
            {
                return obj.Left.GetHashCode();
            }
        }
    }
}
```

Now the counter in the generated files only increment when changes are done to their respective files.

This solution would however need a bigger refactoring due to the way 'LoggerMessageGenerator' store generated code. All code is stored within a single file `LoggerMessage.g.cs`, https://github.com/dotnet/runtime/blob/dc55d613ec60e3db9c7117689ff3161019a709cf/src/libraries/Microsoft.Extensions.Logging.Abstractions/gen/LoggerMessageGenerator.Roslyn4.0.cs#L53,

If one should succeed by passing a `IncrementalValuesProvider` one would need some kind of name for file partitioning like `LoggerMessage.{SOME_NAME}.g.cs`.

## Performance gains

I don't now how to benchmark the changes but I would expect a significant gain could be obtained since one avoid recreating of files in every key stroke.

## PR

I have made a PR which adds comparison as a suggestion. Please let me know any thoughts and comments.
https://github.com/dotnet/runtime/pull/74558

**Comment by tarekgh** [comment]
CC @dotnet/area-system-text-json as this is related to `System.Text.Json` too.

**Comment by jkoritzinsky** [comment]
I would highly recommend that any fixes be coupled with tests using the step tracking infrastructure to validate that the fixed incremental behavior is preserved in the future. We added this testing for LibraryImportGenerator and it has been quite valuable already.

**Comment by eiriktsarpalis** [comment]
Related to #68353.

**Comment by 3schwartz** [comment]
Close - see https://github.com/dotnet/runtime/pull/74558#issuecomment-1229129001 for details.
