### ISSUE TITLE
Protection against assembly tampering

### ISSUE THREAD

**Issue by Sylvain2703** [dotnet/runtime#74569]
# General description
In any .NET Core/5+ application, it is possible to tamper an assembly since the CLR doesn't do any assembly validation before loading it.
As a result, any DLL can be replaced and embed malicious code.

## A real world example
We have a WinForms application (the _App_) that we sell under license and distribute to our customers. We use a home-made .NET Standard 2.0 library (the _LicenseLib_) to do the license validation (_LicenseLib_ is `PackageReference`-d by _App_). Also, both are obfuscated to make the attacker job harder.

Unfortunately, without having the original source-code and thanks to ILSpy, I was able to recreate a malicious version of _LicenseLib_ (the _FakeLicenseLib_) that just contains the same **public** classes, interfaces, methods and properties to, let's say, _respond "ok, you are licensed"_.

# Non-working solutions
- [Strong-naming](https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named)
  At the beginning an obvious solution seemed to sign the assemblies.

  We quickly found assembly strong-naming: according to the [2nd paragram this doc](https://docs.microsoft.com/en-us/dotnet/standard/assembly/enhanced-strong-naming) ("_Strong name signatures help prevent malicious parties from tampering with an assembly and then re-signing the assembly with the original signer’s key._"), it is a good solution.
  Unfortunately, [_the [.NET Core/5+] runtime never validates the strong-name signature, nor does it use the strong-name for assembly binding_](https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named#why-strong-name-your-assemblies).
  Even worse, with .NET Framework, finding and replacing an assembly's public key (with any hexadecimal editor) is enough to pass strong-naming validation.

- [Dotfuscator's Tamper Check](https://www.preemptive.com/dotfuscator/ce/docs/help/checks_tamper.html)
  [Not supported](https://www.preemptive.com/dotfuscator/ce/docs/help/checks_tamper.html#unsupported-application-types) for .NET Core/5 assemblies.

# Other ideas
- Checksum: we can probably implement a checksum mechanism during our _App_ startup to ensure that _LicenseLib_ is the original one.
- Integrate our _LicenseLib_ code inside our _App_: no more assembly loading involved but code reuse more difficult!

# Questions
1. Is there any official (or recommended) way to protected our assemblies against tampering?
2. Why Microsoft doesn't integrate a runtime validation (thanks to a checksum or an asymmetric encryption) to ensure the assembly authenticity?

Thanks for your help 😀

**Comment by svick** [comment]
In my opinion, this is ultimately impossible to do. Once you distribute your code to someone, they can do whatever they want with it. (See for example game companies spending millions on DRM, which is anyway often defeated quite quickly.)

As such, I don't think any kind of anti-tamper technology belongs in .Net itself.

**Comment by Clockwork-Muse** [comment]
> Why Microsoft doesn't integrate a runtime validation (thanks to a checksum or an asymmetric encryption) to ensure the assembly authenticity?

They could, but it wouldn't help your case, since people could just compile a version of the runtime without it.  "Malicious" here refers to people attacking the end user, not the end user themselves.

>Integrate our LicenseLib code inside our App: no more assembly loading involved but code reuse more difficult!

You can make a source-only nuget package, which would solve that problem.  Or use git submodules to the library repo.
That said, if someone is interested enough they can still patch your application binary to remove the checks altogether.

**Comment by Joe4evr** [comment]
> (See for example game companies spending millions on DRM, which is anyway often defeated quite quickly.)

In addition to this, we now have a record that a malicious actor can *use an anti-tamper driver as an attack vector:* https://www.trendmicro.com/en_us/research/22/h/ransomware-actor-abuses-genshin-impact-anti-cheat-driver-to-kill-antivirus.html

The thing that businesses spend millions (if not billions) of dollars on (in futility, IMO) to prevent end-users from tampering with software is what allows attackers to gain full control over an end-user's machine.
![ironic](https://user-images.githubusercontent.com/1058562/186894976-602e0830-7207-427d-8ae4-4d1f7a3f8457.gif)
