### ISSUE TITLE
Send mail via System.Net.Mail.SmtpClient isn't working on .NET MAUI Android, but on .NET MAUI Windows and Xamarin.Forms Android

### ISSUE THREAD

**Issue by tsjdev-apps** [dotnet/runtime#74576]
### Description

I've created a small sample trying to send an email using the `System.Net.Mail.SmtpClient`. The sample is working on Windows, but not on Android. An `Interop+AndroidCrypto+SslException` is thrown. The same code is working on Xamarin.Forms for both platforms.

### Reproduction Steps

1. Create a File > New .NET MAUI App
2. Create a `System.Net.Mail.SmtpClient` and calling the `SendMailAsync()` on Android
3. An `Interop+AndroidCrypto+SslException` is thrown
4. Run the same code on Windows and the email is sent

I've tried using an `outlook.com` mail address with the `smtp-mail.outlook.com` host.

See the following basic sample:
[MauiSendMailSample.zip](https://github.com/dotnet/runtime/files/9425157/MauiSendMailSample.zip)

### Expected behavior

Mail was sent on Android

### Actual behavior

`Interop+AndroidCrypto+SslException` is thrown

### Regression?

The same code is working on Xamarin.Forms for Android and iOS.

### Configuration

Which version of .NET is the code running on?
.NET MAUI Version: 6.0.486 (current)

What OS and version, and what distro if applicable?
Android

What is the architecture (x64, x86, ARM, ARM64)?
ARM, ARM64

### Other information

```
{System.Net.Mail.SmtpException: Failure sending mail.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+AndroidCrypto+SslException: Exception of type 'Interop+AndroidCrypto+SslException' was thrown.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.<ForceAuthenticationAsync>d__175`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Threading.Tasks.TaskToApm.End(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.TlsStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.TlsStreamAuthenticateCallback(IAsyncResult result)
--- End of stack trace from previous location ---
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.End(IAsyncResult result)
   at System.Net.Mail.SmtpConnection.EndGetConnection(IAsyncResult result)
   at System.Net.Mail.SmtpTransport.EndGetConnection(IAsyncResult result)
   at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at MauiSendMailSample.MainPage.OnMailButtonClicked(Object sender, EventArgs e) in MauiSendMailSample\MauiSendMailSample\MainPage.xaml.cs:line 36}
```

**Comment by tsjdev-apps** [comment]
I've also create an issue in the .NET MAUI repository:
https://github.com/dotnet/maui/issues/9587

Maybe also related to:
https://github.com/xamarin/xamarin-android/issues/7277

**Comment by steveisok** [comment]
@tsjdev-apps What version of Android / api level are you using?

**Comment by simonrozsival** [comment]
I tried to reproduce this problem on my device and the message was successfully sent (Samsung Galaxy S10 Lite, Android 12)

**Comment by ComptonAlvaro** [comment]
I have debugging the the MAUI application in a android device (a phone) and it works perfectly.
![photo_2022-08-25_17-01-11](https://user-images.githubusercontent.com/20024410/186700439-214e7e14-19c7-4579-8288-a9279968d922.jpg)

I am using ionos as priveder, instead of outlook, but I guess the problem is with the data that you use to ahutenticate.

**Comment by ComptonAlvaro** [comment]
I have with outlook.com account (really a hotmail account) and it works too, using this data:

```
var smtpClient = new SmtpClient("smtp-mail.outlook.com", 587)
            {
                Port = 587,
                Credentials = new NetworkCredential("xxx@hotmail.com", "YYYY"),
                EnableSsl = true,
            };
```

**Comment by janseris** [comment]
Android 5 should be tested as it is the lowest supported Android version by MAUI

**Comment by tsjdev-apps** [comment]
I've tried now on several real devices and it is working.
Before I was testing on different emulators and on the emulators I recieve the exception.

**Comment by wfurt** [comment]
firewall setting....?

**Comment by simonrozsival** [comment]
I've done some further testing on emulators with various API levels and encrypted SMTP consistently worked on API levels 28 and newer and failed on 26 and lower. For some reason emulator with API 27 didn't work on my PC today so I couldn't test it.

I'm not sure what exactly the problem is, but it seems that the problem is support on lower API levels and not emulator vs. device or firewall settings.

**Comment by janseris** [comment]
@simonrozsival this exactly matches API levels with issues with SSL when connecting to SQL Server. It works for Android 9+ which is API 28+ and fails for all lower versions.

**Comment by janseris** [comment]
> I've tried now on several real devices and it is working. Before I was testing on different emulators and on the emulators I recieve the exception.

What Android version?

**Comment by tsjdev-apps** [comment]
> > I've tried now on several real devices and it is working. Before I was testing on different emulators and on the emulators I recieve the exception.
> 
> 
> 
> What Android version? 

I've tested with Android 11 and Android 12.

**Comment by janseris** [comment]
> > > I've tried now on several real devices and it is working. Before I was testing on different emulators and on the emulators I recieve the exception.
> > 
> > 
> > What Android version?
> 
> I've tested with Android 11 and Android 12.

Could you test Android 8.1 or lower?

**Comment by tsjdev-apps** [comment]
> > > > I've tried now on several real devices and it is working. Before I was testing on different emulators and on the emulators I recieve the exception.
> > > 
> > > 
> > > What Android version?
> > 
> > 
> > I've tested with Android 11 and Android 12.
> 
> Could you test Android 8.1 or lower?

Unfortunately I don't have access to an Android device running Android 8.1 or lower.
