### ISSUE TITLE
[mono] Re-enable passing Vector128 arguments in SIMD registers

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#74583]
Due to mixing LLVM and non-LLVM code (see https://github.com/dotnet/runtime/issues/73454) we disabled the work done for https://github.com/dotnet/runtime/pull/68991 to pass arguments in SIMD registers.  Once the JIT (and interp?) can also use the SIMD registers, we should re-enable that code.

https://github.com/dotnet/runtime/pull/74582

**Comment by SamMonoRT** [comment]
Assigning to @fanyang-mono for tracking and consolidating related issues for 8.0.0
