### ISSUE TITLE
[API Proposal]: FormattableStringBuilder

### ISSUE THREAD

**Issue by mariusz96** [dotnet/runtime#74653]
### Background and motivation

Recently I run into a legacy web api (who hasn't had one of these?) that constructs injection-vulnerable sql as plain strings.

After some looking around I found in ef core documentation that I can use `FormattableString` to parametrize this.

And it turned out that `ConcreteFormattableString` is just a simple class with a `string` and an `object[]` in it and gets used all the time but there's also no way to concat two of them in C#.

So I think it would be pretty essential addition, a way to achieve this in an official library and it would get plenty of uses besides parametrizing legacy sqls.

### API Proposal

```csharp
public class FormattableStringBuilder
{
    public FormattableStringBuilder() { }
    public FormattableStringBuilder(FormattableString  fs) { }
    public FormattableStringBuilder(string format, params object?[] args) { }

    public FormattableStringBuilder AppendFormat(FormattableString fs) { }
    public FormattableStringBuilder AppendFormat(string format, params object?[] args) { }
    public FormattableStringBuilder Append(FormattableStringBuilder fsb) { }

    public FormattableString ToFormattableString() { }
    public string ToString() { }
}
```

### API Usage

```csharp
FormattableStringBuilder fsb = new FormattableStringBuilder();
int[] args = new[] { 1, 2, 3 };

FormattableString fs = fsb
    .AppendFormat("SELECT * FROM [Table1]")
    .AppendFormat(" WHERE ([Column1] = {0} OR [Column2] = {1})", args[0], args[1])
    .AppendFormat(" AND [Column3] = {0}", args[2])
    .AppendFormat(" ORDER BY [Column1]")
    .ToFormattableString();
```

**Comment by Clockwork-Muse** [comment]
This proposal does not solve your problem - **THIS IS STILL VULNERABLE TO SQL INJECTION**.

You **ABSOLUTELY MUST** [follow the guidance on this page](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql#passing-parameters):

> `FromSqlInterpolated` is similar to `FromSqlRaw` but allows you to use string interpolation syntax. Just like `FromSqlRaw`, `FromSqlInterpolated` can only be used on query roots. As with the previous example, the value is converted to a `DbParameter` and isn't vulnerable to SQL injection.
> ```csharp
> var user = "johndoe";
>
> var blogs = context.Blogs
>     .FromSqlInterpolated($"EXECUTE dbo.GetMostPopularBlogsForUser {user}")
>     .ToList();
>```

To be more clear, your proposal provides a general string formatter that has no way to know that parameters need to be escaped, so will still allow for SQL Injection.  Additionally, it will be forced to convert them to strings, which is **not** correct - for example `DateTime(Offset)` values will be converted to a culture-aware formatted string value, which may not be a value the server can correctly handle (and is likely to lose information regardless).

<hr />

> After some looking around I found in efcore documentation that I can use `FormattableString` to parametrize this.

Where did you find the documentation that suggested this?  Perhaps it's a misunderstanding?  Otherwise it should be changed.

Note that there are already overrides of [`StringBuilder.Append(...)`](https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.append?view=net-6.0#system-text-stringbuilder-append(system-text-stringbuilder-appendinterpolatedstringhandler@)) that provide interpolated formatting handling.  
**Under NO circumstances should these be used to supply parameters for SQL queries.**

**Comment by mariusz96** [comment]
> 



> This proposal does not solve your problem - **THIS IS STILL VULNERABLE TO SQL INJECTION**.
> 
> You **ABSOLUTELY MUST** [follow the guidance on this page](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql#passing-parameters):
> 
> > `FromSqlInterpolated` is similar to `FromSqlRaw` but allows you to use string interpolation syntax. Just like `FromSqlRaw`, `FromSqlInterpolated` can only be used on query roots. As with the previous example, the value is converted to a `DbParameter` and isn't vulnerable to SQL injection.
> > ```cs
> > var user = "johndoe";
> > 
> > var blogs = context.Blogs
> >     .FromSqlInterpolated($"EXECUTE dbo.GetMostPopularBlogsForUser {user}")
> >     .ToList();
> > ```
> 
> To be more clear, your proposal provides a general string formatter that has no way to know that parameters need to be escaped, so will still allow for SQL Injection. Additionally, it will be forced to convert them to strings, which is **not** correct - for example `DateTime(Offset)` values will be converted to a culture-aware formatted string value, which may not be a value the server can correctly handle (and is likely to lose information regardless).
> 
> > After some looking around I found in efcore documentation that I can use `FormattableString` to parametrize this.
> 
> Where did you find the documentation that suggested this? Perhaps it's a misunderstanding? Otherwise it should be changed.
> 
> Note that there are already overrides of [`StringBuilder.Append(...)`](https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.append?view=net-6.0#system-text-stringbuilder-append(system-text-stringbuilder-appendinterpolatedstringhandler@)) that provide interpolated formatting handling. **Under NO circumstances should these be used to supply parameters for SQL queries.**

Yes, I meant it more like a general tool, but that's just the example use case I found - just like StringBuilder but for `FormattableString` class.

So for example this overload:
 ```cs
var user = "johndoe";

var blogs = context.Blogs
    .FromSqlInterpolated($"EXECUTE dbo.GetMostPopularBlogsForUser {user}")
    .ToList();
```
accepts `FormattableString` which [to my understanding is just a format string + object array](https://github.com/dotnet/runtime/blob/v6.0.8/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/FormattableStringFactory.cs#L39-L55): 

The equivalent with the proposed tool would be like this:
 ```cs
var user = "johndoe";

var builder = new FormattableStringBuilder();
FormattableString sql = builder.AppendFormat($"EXECUTE dbo.GetMostPopularBlogsForUser {user}").ToFormattableString();

var blogs = context.Blogs
    .FromSqlInterpolated(sql)
    .ToList();
```

and you could do:
```cs
string format = sql.Format;
var arguments = sql.GetArguments();
```
on it since this is what `FormattableString` supports.

And it would allow chaining and constructing longer formattable strings perhaps with some optional parts.

**Comment by Clockwork-Muse** [comment]
... I'm sorry, I misunderstood what the base type you were using was/how it was handling strings.  

You are correct, this would work as you want, and would be **extremely** useful in dynamic SQL scenarios.  Although note that at least some providers support composing raw query with LINQ operators, so may not require the entire query to be written raw.

The one caveat is that it may make it more likely people will try to include non-parameterizable tokens, eg table names:
```csharp
FormattableString fs = fsb
    .AppendFormat($"SELECT * FROM {tableNameVariable}")
    .ToFormattableString();
```
... although this is something that's already possible with the existing `FromSqlInterpolated(...)`.  Note than a `.Append(FormattableString)` method that would realize any such formatted parameters would **not** be safe.

**Comment by mariusz96** [comment]
Yes, the intent of the API is to build a `FormattableString`, not necessarily realize it - hence it's mainly meant for building `FormattableString`s, not `string`s.

Some other scenarios where this might get used:
- source generation, code templates, e-mails, etc
- parsing custom classes into csv strings and similar, possibly custom formats
- letting client code build long `FormattableString`s with the `FormattalbeStringBuilder` and then securing `object` array from `FormattableString` as "secrets"
- building urls with many optional query strings for web apis and maybe passing them around before realization (could be useful in, for example, HATEOAS)
- anything that has strings with special values in it / needs to build long `FormattableString`s conditionally (ie connection strings, dynamic SQL, HTTP headers with values, string-based configurations, etc)
- ??

Right now, some of those use cases might be already possible with just a single compiler-generated `FormattableString` or a realized, formatted `string` or even a normal `string` concatenated with right values or parsing a normal `string` into a format string and values but this solution would not demand that - immediate `string` realization - and would allow much more readable and intent-revealing code in such scenarios.

What's more, `FormattableString` is already a part of the publicly-shipped API so builder would just complement it and make more complicated scenarios possible. It would allow developers much more flexibility while still providing the same syntax. And then, putting it in the main library would make the proper implementation possible - since for example translation of `$"EXECUTE dbo.GetMostPopularBlogsForUser {user}"` to `FormattableString` gets done at a compiler level and cannot be reliably predicted by a third-party code (ie some sort of `StringBuilder` nuget package).

The implementation of the basic use case would work like this:
```cs.
var fs = new FormattableStringBuilder()
    .AppendFormat("{0}, {1},", val0, val1)
    .AppendFormat(" {0},", val2)
    .AppendFormat("{0}, {1}, {2}", val3, val4, val5)
    .ToFormattableString();

    // fs.Format: "{0}, {1}, {2}, {3}, {4}, {5}"
    // fs.GetArguments(): { val0, val1, val2, val3, val4, val5 }
```
ie at the result it would just return concated items from the object array and incremented format item indexes.

It would also be necessary to store original formatting ie `$"{DateTime.Now:R}"` in case someone wants to materialize the string after all and do any validations that `StringBuilder.AppendFormat` / `DefaultInterpolatedStringHandler` already does - in the case of the `:R` it would store it just like `FormattableString` does: ie the original value (`object`) and then the format item from the `Format` property.

**Comment by stephentoub** [comment]
I'm not understanding what value this adds. In the most recent example, why wouldn't you just write that as:
```C#
FormattableString fs = $"{val0}, {val1}, {val2}, {val3}, {val4}, {val5}";
```
? 

Or better yet, don't use FormattableString at all and instead use a custom interpolated string handler.
https://devblogs.microsoft.com/dotnet/string-interpolation-in-c-10-and-net-6/

**Comment by Clockwork-Muse** [comment]
@stephentoub - True, for the most recent example that probably makes more sense.  The real use-case would be for situations where you need to determine at runtime whether you need to make any of those `AppendFormat(...)` calls at all:

```cs
FormattableStringBuilder fsb = new FormattableStringBuilder()
    .AppendFormat("SELECT * FROM [Table1]")
    .AppendFormat(" WHERE ([Column1] = {arga} OR [Column2] = {argb})");

if (someVariable)
{
    fsb.AppendFormat(" AND [Column3] = {argc}");
}
```

> Or better yet, don't use FormattableString at all and instead use a custom interpolated string handler.

The intent here is that this feeds into methods that aren't taking just plain string, so that's not an option.  They either take `FormattableString`, or `string`+an array of arguments.

**Comment by mariusz96** [comment]
> @stephentoub - True, for the most recent example that probably makes more sense. The real use-case would be for situations where you need to determine at runtime whether you need to make any of those `AppendFormat(...)` calls at all:
> 
> ```cs
> FormattableStringBuilder fsb = new FormattableStringBuilder()
>     .AppendFormat("SELECT * FROM [Table1]")
>     .AppendFormat(" WHERE ([Column1] = {arga} OR [Column2] = {argb})");
> 
> if (someVariable)
> {
>     fsb.AppendFormat(" AND [Column3] = {argc}");
> }
> ```
> 
> > Or better yet, don't use FormattableString at all and instead use a custom interpolated string handler.
> 
> The intent here is that this feeds into methods that aren't taking just plain string, so that's not an option. They either take `FormattableString`, or `string`+an array of arguments.

Yes, exactly - and imagine that the current method is not even a final destination, it might just as well be a step in a pipeline and I want to create `FormattableString` (or multiple ones) there and pass them somewhere else and do something special with the values.

So with the proposed tool I could:
```cs
public class Command
{
    public int? Id { get; set; }
    public bool Option { get; set; }
    public IEnumerable<AdditionalOption> AdditionalOptions { get; set; }
}
```
```cs
public class StepInThePipeline
{
    public Handle(Command cmd)
    {
        var fsb = new FormattableStringBuilder();

        if (cmd.Id.HasValue)
        {
            ...
        }

        if (cmd.Option)
        {
            ...
        }

        foreach (var additionalOption in cmd.AdditionalOptions)
        {
            ...
        }

       return PassSomewhereElse(fsb or fsb.ToFormattableString());
    }
}
```

In fact this is exactly how real life SQL example would work and in that particular case `FormattableString` would never be realized directly and instead would be used to parametrize SQL through some other code.

And as far as I'm aware it is not possible to build `FormattableString`s like that with the current tools.

**Comment by stephentoub** [comment]
> And as far as I'm aware it is not possible to implement the above example with the current tools

Here's an implementation in under 30 lines.
```C#
public sealed class FormattableStringBuilder
{
    private readonly StringBuilder _format = new StringBuilder();
    private readonly List<object?> _args = new List<object?>();

    public FormattableString ToFormattableString() => FormattableStringFactory.Create(_format.ToString(), _args.ToArray());

    public FormattableStringBuilder AppendFormat([InterpolatedStringHandlerArgument("")] Handler handler) => this;

    [InterpolatedStringHandler]
    public struct Handler
    {
        internal readonly FormattableStringBuilder _builder;
        
        public Handler(int literalLength, int formattedCount, FormattableStringBuilder builder) => _builder = builder;
        
        public void AppendLiteral(string value) => _builder._format.Append(value.Replace("{", "{{").Replace("}", "}}"));

        public void AppendFormatted(object? value, int alignment = 0, string? format = null)
        {
            _builder._format.Append('{').Append(_builder._args.Count);
            if (alignment != 0) _builder._format.Append(CultureInfo.InvariantCulture, $",{alignment}");
            if (format is not null) _builder._format.Append(':').Append(format);
            _builder._format.Append('}');
            _builder._args.Add(value);
        }
    }
}
```

Using the previous example, for example:
```C#
int arga = 42;
int argb = 84;
int argc = 168;
foreach (bool someVariable in new[] { false, true })
{
    FormattableStringBuilder fsb = new FormattableStringBuilder()
        .AppendFormat($"SELECT * FROM [Table1]")
        .AppendFormat($" WHERE ([Column1] = {arga} OR [Column2] = {argb})");
    if (someVariable)
    {
        fsb.AppendFormat($" AND [Column3] = {argc}");
    }

    FormattableString fs = fsb.ToFormattableString();
    Console.WriteLine(fs.Format);
    Console.WriteLine(fs.ArgumentCount);
    Array.ForEach(fs.GetArguments(), arg => Console.WriteLine(arg));
    Console.WriteLine();
}
```
yields:
```
SELECT * FROM [Table1] WHERE ([Column1] = {0} OR [Column2] = {1})
2
42
84

SELECT * FROM [Table1] WHERE ([Column1] = {0} OR [Column2] = {1}) AND [Column3] = {2}
3
42
84
168
```

From my perspective, this is too niche to add to the core libraries, especially as `FormattableString` is largely considered legacy (from before interpolated string handlers existed), and anyone who wants something like this can use code like shown above.

**Comment by mariusz96** [comment]
> > And as far as I'm aware it is not possible to implement the above example with the current tools
> 
> Here's an implementation in under 30 lines.
> 
> ```cs
> public sealed class FormattableStringBuilder
> {
>     private readonly StringBuilder _format = new StringBuilder();
>     private readonly List<object?> _args = new List<object?>();
> 
>     public FormattableString ToFormattableString() => FormattableStringFactory.Create(_format.ToString(), _args.ToArray());
> 
>     public FormattableStringBuilder AppendFormat([InterpolatedStringHandlerArgument("")] Handler handler) => this;
> 
>     [InterpolatedStringHandler]
>     public struct Handler
>     {
>         internal readonly FormattableStringBuilder _builder;
>         
>         public Handler(int literalLength, int formattedCount, FormattableStringBuilder builder) => _builder = builder;
>         
>         public void AppendLiteral(string value) => _builder._format.Append(value.Replace("{", "{{").Replace("}", "}}"));
> 
>         public void AppendFormatted(object? value, int alignment = 0, string? format = null)
>         {
>             _builder._format.Append('{').Append(_builder._args.Count);
>             if (alignment != 0) _builder._format.Append(CultureInfo.InvariantCulture, $",{alignment}");
>             if (format is not null) _builder._format.Append(':').Append(format);
>             _builder._format.Append('}');
>             _builder._args.Add(value);
>         }
>     }
> }
> ```
> 
> Using the previous example, for example:
> 
> ```cs
> int arga = 42;
> int argb = 84;
> int argc = 168;
> foreach (bool someVariable in new[] { false, true })
> {
>     FormattableStringBuilder fsb = new FormattableStringBuilder()
>         .AppendFormat($"SELECT * FROM [Table1]")
>         .AppendFormat($" WHERE ([Column1] = {arga} OR [Column2] = {argb})");
>     if (someVariable)
>     {
>         fsb.AppendFormat($" AND [Column3] = {argc}");
>     }
> 
>     FormattableString fs = fsb.ToFormattableString();
>     Console.WriteLine(fs.Format);
>     Console.WriteLine(fs.ArgumentCount);
>     Array.ForEach(fs.GetArguments(), arg => Console.WriteLine(arg));
>     Console.WriteLine();
> }
> ```
> 
> yields:
> 
> ```
> SELECT * FROM [Table1] WHERE ([Column1] = {0} OR [Column2] = {1})
> 2
> 42
> 84
> 
> SELECT * FROM [Table1] WHERE ([Column1] = {0} OR [Column2] = {1}) AND [Column3] = {2}
> 3
> 42
> 84
> 168
> ```
> 
> From my perspective, this is too niche to add to the core libraries, especially as `FormattableString` is largely considered legacy (from before interpolated string handlers existed), and anyone who wants something like this can use code like shown above.

Yay! Split by value, alignment and format like that's what I wanted and you can even add your own formats ie `ex` for `excluded from SQL parameters`, great.

You see I thought based on [SO](https://stackoverflow.com/questions/71005770/given-a-formattable-string-is-there-a-clean-way-to-get-the-formatting-string-fo) and [StringBuilder.AppendFormat](https://github.com/dotnet/runtime/blob/v6.0.8/src/libraries/System.Private.CoreLib/src/System/Text/StringBuilder.cs#L1549-L1830) that the parsing needs to be done manually but now I understand that that is not the case and what you meant by "custom interpolated string handler".

Say though, as there is no interface and the [tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/interpolated-string-handler) only mentions that the compiler will pick the best overload and I can use [DefaultInterpolatedStringHandler](https://github.com/dotnet/runtime/blob/v6.0.8/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/DefaultInterpolatedStringHandler.cs) as a reference, if I put this class in the project, will the two current overloads be enough for it to work in the next .NET versions?

I think other developers might have a hard time if they were to understand or edit it.

**Comment by stephentoub** [comment]
> if I put this class in the project today, will the two current method overloads be enough for it to work in the next .NET versions?

You mean the AppendLiteral and the AppendFormat methods?  Yes, they will continue working fine.  All the other AppendFormat overloads you see on DefaultInterpolatedStringHandler are optimizations, e.g. to avoid boxing a value type being formatted, but you're explicitly asking for that boxing anyway because you wanted all the arguments as an object[].

**Comment by mariusz96** [comment]
Superb, I see how this is far more flexible than my proposition.

Thanks to all the participants - I think the issue can be closed now.

**Comment by stephentoub** [comment]
Thanks.
