### ISSUE TITLE
[wasm-mt] Issues with enabling threads in .NET 7 RC 1

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#74654]
Using the `wasm-experimental` workload it shoudl be possible to create multi-threaded `wasmbrowser` projects in .NET 7 RC1

Issues:

- [x] First group - fixed on `main` by https://github.com/dotnet/runtime/pull/75162 and on `release/7.0` by https://github.com/dotnet/runtime/pull/75171
   - `WasmGenerateAppBundle` doesn't create multi-threaded builds with `WasmEnableThreads` - only `WasmBuildNative` does - due to `dotnet.worker.js` missing from the runtime pack
   - [`WorkloadManifest.targets.in`](https://github.com/dotnet/runtime/blob/536f34d9ab88e153aa11329e789afe6975fbe9a9/src/mono/nuget/Microsoft.NET.Workload.Mono.Toolchain.Manifest/WorkloadManifest.targets.in#L92) uses `WasmEnableThreading` instead of `WasmEnableThreads`
   - The CoreLibs in the `multithread` and `perftrace` build variants don't define the correct feature flags.
   - `dotnet new wasmbrowser` creates `browser.csproj`, not `<dirname>.csproj`
- [x] ~`dotnet new wasmbrowser` does not create `runtimeconfig.template.json` required for `dotnet run`~ this looks like a local caching issue
- [x] https://github.com/dotnet/runtime/issues/75263 

## Detailed reproduction steps

1. Download a net7 RC 1 nightly tar.gz from [dotnet/installer](https://github.com/dotnet/installer)  (I used the "Release/7.0.1xx-rc1 (7.0.x Runtime)" column)
2. Unpack into `${HOME}/work/net7-nightly`
3. Set `DOTNET_ROOT` and `PATH`:
   ```console
   export DOTNET_ROOT="${HOME}/work/net7-nightly"
   export PATH="${DOTNET_ROOT}:${PATH}"
   ```
4. Create the directory `${HOME}/work/net7-playground` and add the following into `${HOME}/work/net7-playground/NuGet.config`
   ```xml
   <configuration>
     <packageSources>
       <add key="dotnet7" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json" />
     </packageSources>
   </configuration>
   ```
4. From the `net7-playground` directory (so that `NuGet.config` is in the current dir), install the `wasm-experimental` workload:
   ```console
   cd ~/work/net7-playground
   dotnet workload install wasm-experimental
   ```
5. Make a sample project directory `${HOME}/work/net7-playground/hithread` and create a `wasmbrowser` project:
   ```console
   cd ~/work/net7-playground
   mkdir hithread
   cd hithread
   dotnet new wasmbrowser
   ```
6. **Bug 1** note that there is `browser.csproj` not `hithread.csproj` - other templates create a .csproj file with the same name as the directory.
6. **Bug 2** create the missing `runtimeconfig.template.json` with teh following content
   ```json
   {
       "wasmHostProperties": {
           "perHostConfig": [
               {
                   "name": "browser",
                   "html-path": "index.html",
                   "Host": "browser"
               }
           ]
       }
   }
   ```
7. Add the follwoing to your `browser.csproj`
   ```xml
   <PropertyGroup>
     <WasmEnableThreads>true</WasmEnableThreads>
     <WasmEnableThreading>true</WasmEnableThreading>
     <WasmBuildNative>true</WasmBuildNative>
   </PropertyGroup>
   ```
   **Bug 3** note that [`WorkloadManifest.targets.in`](https://github.com/dotnet/runtime/blob/536f34d9ab88e153aa11329e789afe6975fbe9a9/src/mono/nuget/Microsoft.NET.Workload.Mono.Toolchain.Manifest/WorkloadManifest.targets.in#L92) has a typo and uses `WasmEnableThreading` instead of `WasmEnableThreads`
8. Run `dotnet build`
  ```console
  $ dotnet build
  MSBuild version 17.4.0-preview-22416-02+5d102ae37 for .NET
  Determining projects to restore...
  Restored /Users/alklig/work/net7-playground/hithread/browser.csproj (in 2 ms).
/Users/alklig/work/net7-nightly/sdk/7.0.100-rc.2.22425.5/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(219,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/Users/alklig/work/net7-playground/hithread/browser.csproj]
  browser -> /Users/alklig/work/net7-playground/hithread/bin/Debug/net7.0/browser-wasm/browser.dll
  Compiling native assets with emcc with -O0. This may take a while ...
  [2/3] corebindings.c -> corebindings.o [took 0.384s]
  [1/3] pinvoke.c -> pinvoke.o [took 0.384s]
  [3/3] driver.c -> driver.o [took 0.416s]
  Linking for initial memory $(EmccInitialHeapSize)=536870912 bytes. Set this msbuild property to change the value.
  Linking with emcc with -O0. This may take a while ...
  ...
  Exception: FROZEN_CACHE is set, but cache file is missing: "sysroot/lib/wasm32-emscripten/libGL-mt.a" (in cache root path "/Users/alklig/work/net7-nightly/packs/Microsoft.NET.Runtime.Emscripten.3.1.12.Sdk.osx-x64/8.0.0-alpha.1.22415.5/tools/emscripten/cache")
/Users/alklig/work/net7-nightly/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-rc.1.22422.12/Sdk/WasmApp.Native.targets(422,5): error MSB3073: The command "emcc "@/Users/alklig/work/net7-nightly/packs/Microsoft.NETCore.App.Runtime.Mono.multithread.browser-wasm/7.0.0-rc.1.22422.12/runtimes/browser-wasm/native/src/emcc-default.rsp" "@/Users/alklig/work/net7-nightly/packs/Microsoft.NETCore.App.Runtime.Mono.multithread.browser-wasm/7.0.0-rc.1.22422.12/runtimes/browser-wasm/native/src/emcc-link.rsp" "@/Users/alklig/work/net7-playground/hithread/obj/Debug/net7.0/browser-wasm/wasm/for-build/emcc-link.rsp"" exited with code 1. [/Users/alklig/work/net7-playground/hithread/browser.csproj]
   ```
  **Bug 4** We [removed the `*-mt.a` static libraries](https://github.com/dotnet/emsdk/pull/43) in our EMSDK pack
9. Copy `*-mt.a` from an upstream EMSDK install into the emsdk pack:
   ```console
   cp ~/work/dotnet-runtime/runtime/src/mono/wasm/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/*-mt.a ~/work/net7-nightly/packs/Microsoft.NET.Runtime.Emscripten.3.1.12.Sdk.osx-x64/8.0.0-alpha.1.22415.5/tools/emscripten/cache/sysroot/lib/wasm32-emscripten
   ```
10. `dotnet build` should now succeed.
    `dotnet run` shoudl serve the app.  Open the URL in Chrome and open dev tools and hit reload.  You should see something like this in the console:
   ```console
   MONO_WASM: worker initializing essential C exports and APIs
   MONO_WASM: worker initializing essential C exports and APIs
   MONO_WASM: worker initializing essential C exports and APIs
   MONO_WASM: worker initializing essential C exports and APIs
   dotnet.js:5 MONO_WASM: afterLoadWasmModuleToWorker added message event handler Worker {onmessage: ƒ, onerror: ƒ}
   dotnet.js:5 MONO_WASM: afterLoadWasmModuleToWorker added message event handler Worker {onmessage: ƒ, onerror: ƒ}
   dotnet.js:5 MONO_WASM: afterLoadWasmModuleToWorker added message event handler Worker {onmessage: ƒ, onerror: ƒ}
   dotnet.js:5 MONO_WASM: afterLoadWasmModuleToWorker added message event handler Worker {onmessage: ƒ, onerror: ƒ}
   dotnet.js:5 MONO_WASM: worker initializing essential C exports and APIs
   dotnet.js:5 MONO_WASM: worker initializing essential C exports and APIs
   dotnet.js:5 MONO_WASM: worker initializing essential C exports and APIs
   dotnet.js:5 MONO_WASM: worker initializing essential C exports and APIs
   dotnet.js:3 mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
   dotnet.js:2013 Hello, Console!
   ```
11. Clean the `bin` and `obj` directories.
    Change the `browser.csproj` like this:
   ```xml
   <PropertyGroup>
     <WasmEnableThreads>true</WasmEnableThreads>
     <WasmEnableThreading>true</WasmEnableThreading>
     <WasmGenerateAppBundle>true</WasmGenerateAppBundle>
   </PropertyGroup>
   ```
   That is, replace `WasmBuildNative` by `WasmGenerateAppBundle`
12. run `dotnet build` again. Note that  `dotnet.worker.js` isn't in the AppBundle directory. When running
    the app prints 404s when trying to load it. From the Chrome DevTools console:
   ```console
   GET http://127.0.0.1:9000/dotnet.worker.js 404 (Not Found)
dotnet.worker.js:1          GET http://127.0.0.1:9000/dotnet.worker.js 404 (Not Found)
dotnet.worker.js:1          GET http://127.0.0.1:9000/dotnet.worker.js 404 (Not Found)
dotnet.worker.js:1          GET http://127.0.0.1:9000/dotnet.worker.js 404 (Not Found)
dotnet.js:5 MONO_WASM: afterLoadWasmModuleToWorker added message event handler Worker {onmessage: ƒ, onerror: ƒ}
dotnet.js:5 MONO_WASM: afterLoadWasmModuleToWorker added message event handler Worker {onmessage: ƒ, onerror: ƒ}
dotnet.js:5 MONO_WASM: afterLoadWasmModuleToWorker added message event handler Worker {onmessage: ƒ, onerror: ƒ}
dotnet.js:5 MONO_WASM: afterLoadWasmModuleToWorker added message event handler Worker {onmessage: ƒ, onerror: ƒ}
   ```

**Comment by lambdageek** [comment]
@lewing @steveisok @radical

**Comment by lambdageek** [comment]
@radekdoulik @lewing I guess our biggest problem is going to be
> EMSDK nuget is missing *-mt.a libs needed for multi-threaded builds

because that runs up against the nuget size limit?

**Comment by radical** [comment]
> @radekdoulik @lewing I guess our biggest problem is going to be
> 
> > EMSDK nuget is missing *-mt.a libs needed for multi-threaded builds
> 
> 
> 
> because that runs up against the nuget size limit?

I can take care of the rest.

**Comment by lambdageek** [comment]
Maybe for net7 RC2 we can focus on `WasmGenerateAppBundle`+`WasmEnableThreads` as the "golden path" - that way we don't have to put the `*-mt.a` libs back in the Emscripten nuget.  Anyone who wants to P/Invoke native code will be broken, but simple experiments with threading will work.

for net7 RTM we probably should have the `*-mt.a` stuff back in the Emscripten nuget, but if that's hard, maybe `WasmBuildNative`+`WasmEnableThreads` will have to wait for net8

**Comment by lambdageek** [comment]
Ah there's one more issue:

```csharp
public class MyClass {
    [MethodImpl(MethodImplOptions.NoInlining)]
    public static string CallMeFromJS()
    {
        new Thread(Loop).Start();

        return "Hello, World!";
    }

    public static void Loop() {
        for (int i = 0; i < 5; ++i) {
            Console.WriteLine ("Thread ping!");
            Thread.Sleep (100);
        }
    }
}
```

results in

<img width="923" alt="Screen Shot 2022-09-06 at 11 54 26" src="https://user-images.githubusercontent.com/480437/188681645-82ec3fe7-c798-4589-b607-62922d07e2f5.png">

Which means we didn't build CoreLib for threading.  Probably needs to check for `MonoWasmBuildVariant` when defining `FeatureWasmThreads` in the CoreLib proj. I'll start a PR

**Comment by lambdageek** [comment]
I'm not sure how to fix 
> `dotnet new wasmbrowser` does not create `runtimeconfig.template.json` required for dotnet run

As far as I can tell the file is in the template directory https://github.com/dotnet/runtime/tree/main/src/mono/wasm/templates/templates/browser

Note also that `README.md` didn't get installed either.  Do we need to do something to `.template.config\template.json` ?  I think the default `sources.include` should have copied us.  And neither `*.md` or `runtimeconfig.template.json` is in `sources.exclude` by default.

**Comment by lambdageek** [comment]
@sayedihashimi Do you know why `dotnet new wasmbrowser` wouldn't install `runtimeconfig.template.json` from our template https://github.com/dotnet/runtime/tree/main/src/mono/wasm/templates/templates/browser by default?  Should we be using `sources.copyOnly` ?

**Comment by sayedihashimi** [comment]
@lambdageek do you have a nuget package that I can try out? Or is there some specific steps that I should follow to try it out?

**Comment by sayedihashimi** [comment]
@lambdageek I cloned the repo and ran `dotnet pack` in the `runtime\src\mono\wasm\templates` folder to create the nuget package. I used `dotnet new --install` to install and try out the `wasmbrowser` template. It appears to be dropping that file, see the gif at the end of this. You may be running into a caching issue. There are two levels of caches when working with NuGet packages, the NuGet cache and the Template Engine cache. What I would recommend is to change the version of the package, create a new package and then try it. If it works that confirms there is a caching issue. From there we can engage the Template Engine team. They have made some updates in .net 7 to decrease the caching issues.

![2022 08 wasmbrowser template](https://user-images.githubusercontent.com/1283154/188742068-84409685-e19b-4566-baa7-3c94f0683ab1.gif)

**Comment by lambdageek** [comment]
> @lambdageek I cloned the repo and ran `dotnet pack` in the `runtime\src\mono\wasm\templates` folder to create the nuget package. I used `dotnet new --install` to install and try out the `wasmbrowser` template. It appears to be dropping that file, see the gif at the end of this. You may be running into a caching issue. There are two levels of caches when working with NuGet packages, the NuGet cache and the Template Engine cache. What I would recommend is to change the version of the package, create a new package and then try it. If it works that confirms there is a caching issue. From there we can engage the Template Engine team. They have made some updates in .net 7 to decrease the caching issues.
> 
> ![2022 08 wasmbrowser template](https://user-images.githubusercontent.com/1283154/188742068-84409685-e19b-4566-baa7-3c94f0683ab1.gif)
> 
> 

Thanks @sayedihashimi, I'll try your simplified repro steps. It's entirely possible that it's some old cache on my machine. (Our existing repro steps involve a local .net sdk install followed by workload installation from artifacts/, so it may be that my local install has some older bits in it)

**Comment by sayedihashimi** [comment]
@lambdageek after you give it a try, let me know if you have any more questions.

**Comment by lambdageek** [comment]
> @lambdageek after you give it a try, let me know if you have any more questions.

I'm all set. it works on another machine. I think I had an older build

**Comment by lambdageek** [comment]
Looks like we will probably get AOT in RC2, also :tada:

**Comment by lewing** [comment]
are we done here?

**Comment by lambdageek** [comment]
We're done.  Using an RC2 installer from https://github.com/dotnet/installer, we now have RC2 runtime packs where `-p:WasmEnableThreads=true` works.  AOT (`-p:WasmEnableThreads=true -p:RunAOTCompilation=true`) works too.

```
$ dotnet workload install wasm-experimental
...
Installing pack Microsoft.NET.Runtime.Emscripten.3.1.12.Cache.osx-x64 version 7.0.0-rc.2.22459.3...
...
Installing pack Microsoft.NETCore.App.Runtime.AOT.osx-x64.Cross.browser-wasm version 7.0.0-rc.2.22463.21...
```
