### ISSUE TITLE
SqliteException: SQLite Error 1: 'no such table: Movie'

### ISSUE THREAD

**Issue by Mustafalb** [dotnet/runtime#74659]
When I tried to access the website using https://localhost:7281/movies 
and this the line of code that caused the error: Movie = await _context.Movie.ToListAsync();

**Comment by Clockwork-Muse** [comment]
There's nowhere near enough detail for us to reproduce this problem.  We need a minimal (otherwise) working example.

**Comment by Mustafalb** [comment]
> There's nowhere near enough detail for us to reproduce this problem. We need a minimal (otherwise) working example.
This the link for the file
https://drive.google.com/file/d/1qojd9MfRprpPgR0ASMR_KlOWbRs_P8DI/view?usp=sharing

**Comment by onurkanbakirci** [comment]
Hi @Mustafalb . I think that this repo is not suitable for your question nevertheless i looked your codes. The codes looks like good but `.db` file is empty. You added migrations but possibly you forgot to apply migrations to db. By the way, if there is no table named `movie`, program will throw an exception such like you mentioned.

**Comment by Mustafalb** [comment]
I tried to update the database by using this command 

`dotnet ef database update`

and it worked.
