### ISSUE TITLE
Proposal: Allow alternate names for ActivatorUtilityConstructorAttribute

### ISSUE THREAD

**Issue by mnmr** [dotnet/runtime#74655]
Orleans is using ActivatorUtilities to recreate serialized objects, but would prefer to have internalized attributes so that they can follow a consistent naming scheme (for ease of discovery).

It would therefore be useful with a mechanism that allows Orleans to tell ActivatorUtilities that its OrleansConstructorAttribute corresponds to the ActivatorUtilitiesConstructorAttribute. 

To support this, ActivatorUtilities would effectively have to match attribute names against a list of possible names, rather than looking for a single name match. It would also need a mechanism to register the alternative names to look for.

Given the broad utility of ActivatorUtilities, I can see how quite a few projects (serializers in particular) could benefit from being able to reuse this logic without sacrificing discoverability.

**Comment by svick** [comment]
I *think* that an attribute that inherits from `ActivatorUtilitiesConstructorAttribute` should also work. Does that help your use case?

**Comment by mnmr** [comment]
> I _think_ that an attribute that inherits from `ActivatorUtilitiesConstructorAttribute` should also work. Does that help your use case?

It does indeed, thank you. I can confirm that the code seems to use `ConstructorInfo.IsDefined` to check for the attribute, and it isn't sealed, so this should already work - nice! 

Apologies for not checking this before creating an issue.
