### ISSUE TITLE
UriBuilder should percent-encode its UserName or Password properties

### ISSUE THREAD

**Issue by 0xced** [dotnet/runtime#74662]
### Description

Constructing a URI with the [UriBuilder ](docs.microsoft.com/en-us/dotnet/api/system.uribuilder) class should produce valid URIs when setting valid `UserName` and/or `Password` properties. Instead, an `UriFormatException`  is thrown if the user name or password contains a character that should be percent-encoded.

It should be the responsibility of the UriBuilder to properly percent-encode characters in the `UserName` and/or `Password` properties. Note that the documentation of the properties does not mention anything about percent-escaping so by the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) I'd expect the UriBuilder to properly escape what needs to be escaped.

### Reproduction Steps

Run the following code:

```csharp
var builder = new UriBuilder("https://www.microsoft.com")
{
    UserName = "mallory@hackers.net",
    Password = "hunter2",
};
Console.WriteLine(builder.Uri);
```

### Expected behavior

The following URI is written to the console.

```
https://mallory%40hackers.net:hunter2@www.microsoft.com/
```

### Actual behavior

An `UriFormatException`  is thrown with the following message.
> Invalid URI: Invalid port specified.

### Regression?

I don't know whether this is a regression or not.

### Known Workarounds

Manually percent-escaping the `UserName` and `Password` but that should not be necessary.

### Configuration

Version of .NET: .NET 6.0.8
OS: All
Architecture: All

**Comment by MihaZupan** [comment]
I agree that throwing when accessing `builder.Uri` is odd and the exception message is not ideal.

The spec defines user-info as `unreserved / pct-encoded / sub-delims / ":"`.
The problematic characters are `"/" / "\" / "?" / "#" / "@"` (`gen-delims` excluding `[` and `]`).

Blindly encoding the input (`Uri.EscapeDataString`) would be a breaking change, as we would start double-encoding already-encoded values.

The options here are:
- Do nothing (users already can and do call `Uri.EscapeDataString` on the input)
- Throw for invalid characters when `UserName` or `Password` are set
- Only percent-encode the problematic characters

Given that the implementation already encodes some characters (e.g. spaces or non-encoded non-ASCII), I am leaning towards the latter.

<details>
<summary>Example replacement code that you could use (or that could live in UriBuilder)</summary>

```c#
string Encode(string input)
{
    if (input.AsSpan().IndexOfAny(@"/\?$@") < 0) return input;

    return input
        .Replace("/", "%2F", StringComparison.Ordinal)
        .Replace(@"\", "%5C", StringComparison.Ordinal)
        .Replace("?", "%3F", StringComparison.Ordinal)
        .Replace("#", "%23", StringComparison.Ordinal)
        .Replace("@", "%40", StringComparison.Ordinal);
}
```

</details>

**Comment by karelz** [comment]
Triage: Should be fairly straightforward (see code in https://github.com/dotnet/runtime/issues/74662#issuecomment-1230916173 - bunch of Replace calls), but not critical.
