### ISSUE TITLE
Clang LLVM emitting float instrinsics for bitwise operation for every input

### ISSUE THREAD

**Issue by matouskozak** [dotnet/runtime#74661]
### Description

Clang compiler is emitting float instruction for all bitwise operations both for floating point numbers and integers.

### Reproduction Steps

BuildMono HelloWorld project and run it under LLVM while calling Vector128 intrinsics e.g.:

`var vectorA = Vector128.Create<int>(0);
 var vectorB = Vector128.Create<int>(0);
 Vector128.BitwiseAnd(vectorA, vectorB);
`

Generates `vandps %xmm1,%xmm0,%xmm0` which is a single precision floating point instruction.

### Expected behavior

Expected to generate integer variants of floating point instructions for integer inputs.

### Actual behavior

The example generates `vandps %xmm1,%xmm0,%xmm0` which is a single precision floating point instruction.

### Configuration

.NET 6.0.8
OS Ubuntu
amd64 machine

**Comment by matouskozak** [comment]
https://github.com/llvm/llvm-project/issues/57499 looks like intended behavior.

**Comment by jandupej** [comment]
This may have a minor performance impact when processing int data (ICL/TGL adds a 1-clock latency when using the result of vec int operation in a vec float operation, Zen3 incurs the 1-clock delay when a register transitions between int and fp vec domains). Otherwise, this does not break abything.

**Comment by jandupej** [comment]
Like @matouskozak noted, this issue is already known by the LLVM team and active there. I believe GLC does not even have the fp/int transition penalty, not sure about Zen4. Additionally the existing code (e.g. `xorps`) is 1 B shorter than int-specific opcode (e.g. `pxor`). The performance implications for us would be negligible and the code is correct both ways. Closing.

**Comment by tannergooding** [comment]
> This may have a minor performance impact when processing int data (ICL/TGL adds a 1-clock latency when using the result of vec int operation in a vec float operation, Zen3 incurs the 1-clock delay when a register transitions between int and fp vec domains).

Just noting that modern CPUs don't necessarily classify them as `integer` vs `floating-point` based solely on the suffix (e.g. `*ps/q` vs `p*b/d/w/q`). Rather, they sometimes get categorized based on what type of operation they perform. Blends, shuffles, and other bitwise operations are often categorized as `integer` or freely allowed to be in either the `f` or the `i` domain depending on the CPU in question.
