### ISSUE TITLE
IDBFS is Not defined

### ISSUE THREAD

**Issue by sajjadarashhh** [dotnet/runtime#74664]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

i've been use IDBFS File system module to use sqlite in blazor wasm .net 7 preview 7 
but IDBFS is not defined in release mode.
also i've add : `<EmccExtraLDFlags>-lidbfs.js</EmccExtraLDFlags>`
to my .csproject file

**Comment by SamMonoRT** [comment]
@lewing @radical @kg - please triage

**Comment by radical** [comment]
> i've been use IDBFS File system module to use sqlite in blazor wasm .net 7 preview 7
but IDBFS is not defined in release mode.

- how does it fail?
- how are you building this? If it is from the command line, then can you please add `-bl`, and share the generated `msbuild.binlog`?

**Comment by sajjadarashhh** [comment]
@radical i migrate my code from .net 6 to .net 7
FS in js files is replaced with window.Module.FS
but IDBFS is no longer accessible.
i build my project in release mode with visual studio 2022 latest preview currently

**Comment by radical** [comment]
Can you share a small test project that reproduces this issue?

**Comment by sajjadarashhh** [comment]
yep wait i produce this

**Comment by sajjadarashhh** [comment]
https://github.com/sajjadarashhh/Test.net7
i've created this repo to described another problems and now make few changes to described this problem.
when start debugging error logged to console in browser.
problems is about my codes in wwwroot/file.js
@radical  thanks.

**Comment by sajjadarashhh** [comment]
@lewing  sorry but it's available in .net 6 and have breaking changes in .net 7.
this not better to solve this in .net 7?
I think this not a bug or new feature this is changed in .net 7 but I don't know how to use it in .net 7 and i dont find any documentation about this

**Comment by radical** [comment]
> [sajjadarashhh/Test.net7](https://github.com/sajjadarashhh/Test.net7)
> i've created this repo to described another problems and now make few changes to described this problem.
> when start debugging error logged to console in browser.

I tried this repo, and it fails with:
<img width="1821" alt="Screen Shot 2022-08-29 at 5 39 38 PM" src="https://user-images.githubusercontent.com/1472/187304193-7770db57-85b1-4476-96a6-1807beeb4985.png">

Is this the error that you were talking about?

@pavelsavara Does this look related to the new interop API? Maybe MudBlazor needs to make changes for that.

> problems is about my codes in wwwroot/file.js

I don't see this file. Also, I don't see any `-lidbfs.js`, or `window.Module.*`.

@TanayParikh I don't see a runtime issue as yet. Should I move this to `aspnetcore`?

**Comment by sajjadarashhh** [comment]
@radical  Oh sorry no!
this issue is not about .net,wait i check repo and take again

**Comment by sajjadarashhh** [comment]
![image](https://user-images.githubusercontent.com/72276897/187310301-4ae6513e-9506-411f-a606-e66c8d3fb404.png)
i dont know how do you get this error.
but i have this problem.
@radical

**Comment by sajjadarashhh** [comment]
please get latest changes of repo i have few changes for your problem

**Comment by radical** [comment]
With `wasm-tools` workload installed, and using `<WasmBuildNative>true</WasmBuildNative>`, I can reproduce the issue.
@pavelsavara does `IDBFS` need to be exported in our API?

**Comment by lewing** [comment]
> @lewing sorry but it's available in .net 6 and have breaking changes in .net 7. this not better to solve this in .net 7? I think this not a bug or new feature this is changed in .net 7 but I don't know how to use it in .net 7 and i dont find any documentation about this

@sajjadarashhh we plan to investigate this and fix it if possible. Marking the issue for net8.0 does not mean we won't fix it in net7.0.  Once we have a fix it will be considered for net7.0 but specific emscripten features are not a part of the supported api.

**Comment by pavelsavara** [comment]
The Net7 runtime is not spilling the emscripten guts into JS global namespace anymore.
In your code 
https://github.com/sajjadarashhh/Test.net7/blob/f8280d225d1f4e549c129fc94cfa8b101ce9763a/MultipleEventHandlers/MultipleEventHandlers/wwwroot/file.js#L3-L4 


The `IDBFS` is not global anymore. Please try to replace it with `window.Module.FS.filesystems.IDBFS`

Please re-open, if that doesn't help.

**Comment by sajjadarashhh** [comment]
sorry.
theres no documentation about this for .net?
@pavelsavara
