### ISSUE TITLE
Regex auto-atomicity too aggressive about \w and \b

### ISSUE THREAD

**Issue by mathy-plutoflume** [dotnet/runtime#74686]
### Description

`System.Text.RegularExpressions.Regex.Matches` not returning expected matches. It returns no matches at all.

### Reproduction Steps

```csharp
var stringToMatch = "sydney bogota berlin tokyo nairobi denver rio";
Console.WriteLine($"Input: {stringToMatch}");

GetMatches(@"(\b(?!bogo|nai)\w*\b)\w+", stringToMatch);
GetMatches(@"\w*\b\w+", stringToMatch);

void GetMatches(string expression, string stringToMatch)
{
    var reg = new System.Text.RegularExpressions.Regex(expression);

    Console.WriteLine($"\nOutput:");
    foreach (var match in reg.Matches(stringToMatch))
    {
        Console.WriteLine(match);
    }
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net6.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>
```

### Expected behavior

```
Input: sydney bogota berlin tokyo nairobi denver rio

Output:
sydney
berlin
tokyo
denver
rio

Output:
sydney
bogota
berlin
tokyo
nairobi
denver
rio
```

Example 1: https://regex101.com/r/Xn7X3w/2
Example 2: https://regex101.com/r/Q10441/1

### Actual behavior

```
Input: sydney bogota berlin tokyo nairobi denver rio

Output:

Output:
```

### Regression?

When running the same code pointing to `netstandard2.0` and `net472` it's returning correct matches. 

Whereas `.net5` and `.net6.0` returns no match at all.

### Known Workarounds

_None_

### Configuration

* .NET 6.0
* Windows 11
* x64

### Other information

Other community members in Stackoverflow were also able to reproduce this issue: https://stackoverflow.com/questions/73498919/regex-match-differs-between-net-versions

**Comment by stephentoub** [comment]
The update bumpalong optimization is broken in this case. We end up bumping the next starting position for the \w* until after the first word, but that word can match the \w+ after the boundary.

**Comment by stephentoub** [comment]
Or, actually, the issue may just be that we're making the starting loop atomic, and we shouldn't be, as doing so visibly affects the behavior.
