### ISSUE TITLE
COSE needs to enforce that only NIST P-{256,384,521} are used

### ISSUE THREAD

**Issue by bartonjs** [dotnet/runtime#74684]
In the COSE spec section on ECDSA it says (https://www.rfc-editor.org/rfc/rfc8152#section-8.1)

>    This document defines ECDSA to work only with the curves P-256,
   P-384, and P-521. 

It also suggests that for interoperability the curve size and hash size be aligned, but since that's a suggestion (vs a declarative statement) we shouldn't be limiting.

**Comment by bartonjs** [comment]
The check for this would be something like

```C#
if (key is ECDsa ecdsa)
{
    ECParameters ecParams = ecdsa.ExportParameters(false);

    if (ecParams.Curve.CurveType != NamedCurve)
    {
        throw new ArgumentException("ECDSA signing keys must use a named curve that is one of NIST P-256, NIST P-384, or NIST P-521", nameof(key));
    }

    switch (ecParams.Curve.Oid.Value)
    {
        case "1.2.840.10045.3.1.7":
        case "1.3.132.0.34":
        case "1.3.132.0.35":
            break;
        default:
            throw that same exception;
    }
}
```

in `CoseSigner`'s constructor.

**Comment by vcsjones** [comment]
@Jozkee Do you want me to pick this one up? Happy to knock it out if you haven't started it.

**Comment by Jozkee** [comment]
@vcsjones I think the crypto board is still debating whether we should address it or not.

**Comment by jeffhandley** [comment]
@bartonjs Have you gotten any updates from the crypto board on whether or not we should take this change?

**Comment by bartonjs** [comment]
@jeffhandley Sort of. A "yes, enforce it" followed by two "no, don't enforce it"s :smile:.

We're not helped by me saying "be forward flexible, don't take this change" and @blowdart saying "take this change".  Something something pocket veto, something something.  ::whistles innocently::

**Comment by blowdart** [comment]
Jeremy you know I don't want to veto you in public but ... 👿

**Comment by jeffhandley** [comment]
Thank you both. Let's come to a conclusion on this by end of week so that if we do decide to take the change we can get it in before the RC2 snap on Tuesday.

**Comment by Jozkee** [comment]
Seems like we finally got the nod for keep as-is from @blowdart on the crypto board offline thread. Closing this issue now. Thanks, Jeremy.
