### ISSUE TITLE
incorrect computation of build parallelism

### ISSUE THREAD

**Issue by RobertHenry6bev** [dotnet/runtime#74691]
### Description

When running on Linux, https://github.com/dotnet/runtime/blob/9a1debd4f021ba2143d3e37caf9197793d92ab86/eng/native/build-commons.sh#L248 computes the amount of available parallelism by running `nproc -all`.  However, when `nproc -all` returns *all* available parallelism, not the parallelism clamps done by `/usr/bin/taskset $cpu_mask ...job invocation`.  Arguably, just `nproc` should be used here, not `nproc -all` since `nproc` returns the number of processors asked for by the parent `/usr/bin/taskset`

```
/usr/bin/taskset 0xf nproc -all
```
Returns 36 (that's what the hardware on my workstation has), but
```
/usr/bin/taskset 0xf nproc
```
returns 4, eg the popcount(0xf).

### Reproduction Steps

See above

### Expected behavior

There's a reason I clamp the number of cores I give to the build process tree.  I wish the build process followed my wishes.

### Actual behavior

uses number of hardware cores, not the number of cores I clamped it to

### Other information

Introduced in commit bad6ea00b5abe011deb2002d07551b95e526b07d by /cc @glebBalyk

**Comment by jkotas** [comment]
cc @am11

**Comment by jkotas** [comment]
`nproc -all` was introduced in https://github.com/dotnet/coreclr/pull/13909

**Comment by am11** [comment]
This is a good point, and that's how brotli's build uses it https://github.com/dotnet/runtime/blob/13d8d2ecfa0d6b2766ffb8ceaf4d1779bf03fb1b/src/native/external/brotli/fuzz/test_fuzzer.sh#L17

Lets update all three places:
```
eng/native/build-commons.sh  (mirrored from dotnet/arcade)
src/tests/Common/scripts/bringup_runtest.sh
src/tests/build.sh
```
