### ISSUE TITLE
Helix test results are not getting uploaded for a lot of jobs

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#74699]
For `runtime` pipeline, with rolling [builds](https://dev.azure.com/dnceng/public/_build/results?buildId=1970276&view=results).

[Working case in wasm/runtime-tests](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-ddf74c289d6e4e02bb/JIT.CodeGenBringUpTests/1/console.39732105.log?helixlogtype=result):

```
   JIT.CodeGenBringUpTests.XUnitWrapper  Total: 29, Errors: 0, Failed: 0, Skipped: 0, Time: 30.775s
+ export _commandExitCode=0
+ /usr/bin/python3 -u /datadisks/disk1/work/BB7B0A43/w/A9DB096A/u/xharness-event-processor.py
/usr/bin/python3: can't open file '/datadisks/disk1/work/BB7B0A43/w/A9DB096A/u/xharness-event-processor.py': [Errno 2] No such file or directory
+ /usr/bin/python3 /datadisks/disk1/work/BB7B0A43/p/reporter/run.py https://dev.azure.com/dnceng/ public 50501656 eyJ0eXAiOiJKV1 ....
2022-08-26T21:27:53.422Z	INFO   	run.py	run(48)	main	Beginning reading of test results.
2022-08-26T21:27:53.422Z	INFO   	run.py	__init__(42)	read_results	Searching '/datadisks/disk1/work/BB7B0A43/w/A9DB096A/e' for test results files
2022-08-26T21:27:53.422Z	INFO   	run.py	__init__(48)	read_results	Found results file /datadisks/disk1/work/BB7B0A43/w/A9DB096A/e/testResults.xml with format xunit
2022-08-26T21:27:53.427Z	INFO   	run.py	__init__(42)	read_results	Searching '/datadisks/disk1/work/BB7B0A43/w/A9DB096A/uploads' for test results files
2022-08-26T21:27:53.428Z	INFO   	run.py	packing_test_reporter(30)	report_results	Packing 29 test reports to '/datadisks/disk1/work/BB7B0A43/w/A9DB096A/e/__test_report.json'
2022-08-26T21:27:53.428Z	INFO   	run.py	packing_test_reporter(33)	report_results	Packed 7735 bytes
```

### Broken cases

1. [Wasm/AOT/windows](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-7fe0006661664ba3a5/WasmTestOnBrowser-System.Runtime.Tests/1/console.d21a3b3a.log?helixlogtype=result):

```
XHarness exit code: 0

C:\helix\work\workitem\e\wasm_build\AppBundle>set EXIT_CODE=0 
----- end Fri 08/26/2022 21:54:44.42 ----- exit code 0 ----------------------------------------------------------
XHarness artifacts: C:\helix\work\workitem\uploads\xharness-output
python: can't open file 'C:\helix\work\workitem\u\xharness-event-processor.py': [Errno 2] No such file or directory
ERROR: The process "corerun.exe" not found.

[END EXECUTION]
Exit Code:0
```

2. [Wasm/linux](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-5d06d13627bf4dabaf/normal-Microsoft.CSharp.Tests/1/console.9a024754.log?helixlogtype=result):

```
XHarness exit code: 0
/datadisks/disk1/work/B24B0983/w/A9D4099F/e /datadisks/disk1/work/B24B0983/w/A9D4099F/e
----- end Fri Aug 26 21:08:51 UTC 2022 ----- exit code 0 ----------------------------------------------------------
XHarness artifacts: /datadisks/disk1/work/B24B0983/w/A9D4099F/uploads/xharness-output
+ export _commandExitCode=0
+ /usr/bin/python3 -u /datadisks/disk1/work/B24B0983/w/A9D4099F/u/xharness-event-processor.py
/usr/bin/python3: can't open file '/datadisks/disk1/work/B24B0983/w/A9D4099F/u/xharness-event-processor.py': [Errno 2] No such file or directory
+ exit 0
['normal-Microsoft.CSharp.Tests' END OF WORK ITEM LOG: Command exited with 0]
```

- The above 2 cases are not running `reporter/run.py`. The test results can't be seen via kusto.
- It seems to be working with [this](https://dev.azure.com/dnceng/public/_build/results?buildId=1966033&view=results), but failing on the [next rolling build](https://dev.azure.com/dnceng/public/_build/results?buildId=1967489&view=results). And the changes between those - https://github.com/dotnet/runtime/compare/7b0227d5...8755447e .

- This is for wasm, rolling builds, and each column represents a different CI job:

<img width="2053" alt="Screen Shot 2022-08-27 at 5 23 12 AM" src="https://user-images.githubusercontent.com/1472/187024078-27bb269c-5c24-4ed4-ab8a-de492525b61f.png">

Note: the `xharness-event-processor.py` error can be ignored.

cc @lewing @steveisok @akoeplinger @ViktorHofer @premun

**Comment by ChadNedzlek** [comment]
This is caused by https://github.com/dotnet/runtime/commit/7a4b0afcc30a57ce5565a34fb4020c0b9e3bcd3e#diff-1d68a522b60c1ab69fb537ce06f5d7e9a176fa4f75e16425fc164d4b738d7678 from PR https://github.com/dotnet/runtime/pull/73060 (which, if you look at the last run of it, didn't run hardly any tests)

It made breaking changes in "sendtohelixhelper.proj". Currently runtime has almost ZERO test coverage, so that change should be reverted immediately.
