### ISSUE TITLE
a field evaluates to null but passes a null check!

### ISSUE THREAD

**Issue by AndrewRober** [dotnet/runtime#74706]
### Description

Okay i'm not sure how that is even possible, tested using .NET 6.0 and 7.0

this is a single threaded library, no threading, no tasks, no concurrency, no parallelism, nothing even changes those values

i paused the execution, no background threads are running, i tested on the immediate window and it looks as if it's javascript not C#

![image](https://user-images.githubusercontent.com/54873972/187032048-838aa242-2e78-420d-9930-19d7e226c0a4.png)

![image](https://user-images.githubusercontent.com/54873972/187031075-fd423651-a401-4cde-9b2a-3c18a3bebaf7.png)

Currently using Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.4.0 Preview 1.0

### Reproduction Steps

not sure of exact steps to reproduce

### Expected behavior

segment.ParentLoop
null
segment.ParentLoop != null
true <--- this should be false

### Actual behavior

segment.ParentLoop
null
segment.ParentLoop != null
true

**Comment by jeffschwMSFT** [comment]
@AndrewRober can you share the repro?

**Comment by AndrewRober** [comment]
turns out to be a bad override to the != operator, closed for being incorrect
