### ISSUE TITLE
[API Proposal]: Get period from PeriodicTimer

### ISSUE THREAD

**Issue by KieranDevvs** [dotnet/runtime#74716]
### Background and motivation

Currently I don't see a way to know what tick period was given to a `PeriodicTimer` without tracking this externally.

I want to query a `PeriodicTimer` and find out how long `WaitForNextTickAsync` will last.

### API Proposal

```diff
namespace System.Collections.Generic;

namespace System.Threading
{
    public sealed class PeriodicTimer : IDisposable
    {
        public PeriodicTimer(TimeSpan period);

+       public TimeSpan Period { get; }
        public void Dispose();
        public ValueTask<bool> WaitForNextTickAsync(CancellationToken cancellationToken = default);
    }
}
```

### API Usage

```csharp
var periodicTimer = new PeriodicTimer(TimeSpan.FromSeconds(10));

Console.WriteLine($"Timer interval is set at: {periodicTimer.Period}");
```

### Risks

None

**Comment by KieranDevvs** [comment]
If https://github.com/dotnet/runtime/issues/60384 is implemented as a property then this might be redundant, however if the proposal is accepted as it stands, then there is also a need for this proposal.

**Comment by stephentoub** [comment]
Thanks, @KieranDevvs. I've updated https://github.com/dotnet/runtime/issues/60384 to change that to be a get/set property, and so will close this one. Thanks.
