### ISSUE TITLE
[API Proposal]: Add DateTime support overload for ToDateTime in PersianCalendar

### ISSUE THREAD

**Issue by sajjadsaharkhan** [dotnet/runtime#74713]
### Background and motivation

hi.
I'm using `System.Globalization.PersianCalendar` class in my code to convert Utc or system time zone date time to Persian date time.
its have a method and gets a date-time from year , month ,day,...
It pollutes my code.

```csharp
var toDay = persianCalendar.ToDateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day,
            DateTime.Now.Hour, DateTime.Now.Minute, DateTime.Now.Second, DateTime.Now.Millisecond);

// i prefer to use this code:

var toDay = persianCalendar.ToDateTime(DateTime.Now);

```

i think `PersianCalendar` need a new overload for `ToDateTime` api

### API Proposal

```csharp
namespace System.Globalization;

public class PersianCalendar : Calendar
{
    public DateTime ToDateTime(DateTime dateTime)
    {
        return ToDateTime(dateTime.Year, dateTime.Month, dateTime.Day,
            dateTime.Hour, dateTime.Minute, dateTime.Second, dateTime.Millisecond);
    }
}
```

### API Usage

```csharp
var persianCalendar = new PersianCalendar();
var toDay = persianCalendar.ToDateTime(DateTime.Now);
```

**Comment by sajjadsaharkhan** [comment]
@dotnet/area-system-globalization

**Comment by sajjadsaharkhan** [comment]
> I couldn't figure out the best area label to add to this issue. If you have write-permissions please help me learn by adding exactly one [area label](https://github.com/dotnet/runtime/blob/master/docs/area-owners.md).

@dotnet/area-system-globalization

**Comment by sajjadsaharkhan** [comment]
@ericstj 
@dotnet/area-system-globalization

**Comment by Clockwork-Muse** [comment]
It's not there because this:

> ```cs
> namespace System.Globalization;
> 
> public class PersianCalendar : Calendar
> {
>     public DateTime ToDateTime(DateTime dateTime)
>     {
>         return ToDateTime(dateTime.Year, dateTime.Month, dateTime.Day,
>             dateTime.Hour, dateTime.Minute, dateTime.Second, dateTime.Millisecond);
>     }
> }
> ```

isn't correct and doesn't work.  You can't encode calendars other than ISO/Gregorian into `DateTime` - for instance, `DateTime` will prevent day-of-month being higher than 29 for month 2 (and often it being 29 as well).

The anticipated usage pattern for the calendars is that you get the raw numeric values from whatever input source and immediately convert it to `DateTime`, then keep it there with the various `PersianCalendar.AddXXX` methods.

**Comment by sajjadsaharkhan** [comment]
> It's not there because this:
> 
> > ```cs
> > namespace System.Globalization;
> > 
> > public class PersianCalendar : Calendar
> > {
> >     public DateTime ToDateTime(DateTime dateTime)
> >     {
> >         return ToDateTime(dateTime.Year, dateTime.Month, dateTime.Day,
> >             dateTime.Hour, dateTime.Minute, dateTime.Second, dateTime.Millisecond);
> >     }
> > }
> > ```
> 
> isn't correct and doesn't work. You can't encode calendars other than ISO/Gregorian into `DateTime` - for instance, `DateTime` will prevent day-of-month being higher than 29 for month 2 (and often it being 29 as well).
> 
> The anticipated usage pattern for the calendars is that you get the raw numeric values from whatever input source and immediately convert it to `DateTime`, then keep it there with the various `PersianCalendar.AddXXX` methods.
> 
> `DateTime.Now` is essentially "already" a Persian calendar date, because that's the anticipated unit of storage/transmission; it's during display/manipulation you need to use the calendars.

it's true and I got it
it's true and I got it
thanks
