### ISSUE TITLE
Using hostfxr.h to Host Core AppDomain.CurrentDomain.BaseDirectory is empty

### ISSUE THREAD

**Issue by DavuKnight** [dotnet/runtime#74720]
### Description

I'm Hosting a DotNetCore Dll from umanaged c++ using hostfxr.h. 
AppDomain.CurrentDirectory.BaseDirectory appears to be empty not sure if this is a config setting I missed or a by product of the dymac host but given some applications rely on it if there isnt a way to set it that would be helpful.

### Reproduction Steps

Download 
https://github.com/dotnet/samples/tree/main/core/hosting
Change
https://github.com/dotnet/samples/blob/b905b2e667cd9c7a7afac8aa20173ebddb739ff0/core/hosting/src/DotNetLib/Lib.cs#L25
and or
https://github.com/dotnet/samples/blob/b905b2e667cd9c7a7afac8aa20173ebddb739ff0/core/hosting/src/DotNetLib/Lib.cs#L33
To Read
  `          Console.WriteLine($"AppDomain.CurrentDomain.BaseDirectory- {AppDomain.CurrentDomain.BaseDirectory}-");
`

### Expected behavior

A valid path either the path of the assembly or the path of the hosting assembly. 

### Actual behavior

Returns blank

**Comment by reflectronic** [comment]
It is expected that unmanaged hosts set the `APP_CONTEXT_BASE_DIRECTORY` runtime property themselves. This can be done through `AppDomain.SetData`/`AppContext.SetData` in managed code, or through `hostfxr_set_runtime_property_value` in the host itself.

**Comment by DavuKnight** [comment]
Thanks much a ppreciated.

**Comment by rseanhall** [comment]
It's worth noting that the `APP_CONTEXT_BASE_DIRECTORY` property is automatically set when using the `hostfxr_initialize_*` methods.

**Comment by DavuKnight** [comment]
The sample code provided above is using hostfxr_initialize_for_runtime_config_fn and it is not setting the  APP_CONTEXT_BASE_DIRECTORY

**Comment by rseanhall** [comment]
Ah, you're right. It does always set it here: https://github.com/dotnet/runtime/blob/41419131095d36fb5b811600ad0dab3b0d804269/src/native/corehost/hostpolicy/hostpolicy_context.cpp#L243. But the value is set to empty for `hostfxr_initialize_for_runtime_config_fn` here: https://github.com/dotnet/runtime/blob/c8a4e180abd7e0517709592f610010c33f020329/src/native/corehost/hostpolicy/deps_resolver.h#L191. The value is valid when using `hostfxr_initialize_for_dotnet_command_line`, though.

**Comment by vitek-karas** [comment]
Just wanted to add the reason for this difference. The `hostfxr_initialize_for_runtime_config` is frequently used when loading "components" into a host application (COM, IJW both use it). As such the "component" can't define (or know) the "Application base" directory for the entire app. Also, if the process already has runtime running in it, then it can't modify the "application base" anyway (nor should it).

If you're using `hostfxr_initialize_for_runtime_config` for a scenario where it's always starting the runtime in the process, you can set the "application base" as you probably know what it should be.
