### ISSUE TITLE
DateTime.Now.ToString("yyyy/MM/dd") is not working

### ISSUE THREAD

**Issue by ajaypathak** [dotnet/runtime#74737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When i am trying to use DateTime.Now.ToString("yyyy/MM/dd"), it is always returning the response in "2022-08-29" format

following are examples 

?DateTime.Now.ToString("yyyy/MM/dd")
"2022-08-29"
?DateTime.Now.ToString("yyyy%MM%dd")
"2022882929"
?DateTime.Now.ToString("yyyyMMdd")
"20220829"
?DateTime.Now.ToString("yyyy MM dd")
"2022 08 29"
?DateTime.Now.ToString(@"yyyy#MM#dd")
"2022#08#29"
?DateTime.Now.ToString(@"yyyy#MM#dd")
"2022#08#29"
?DateTime.Now.ToString("yyyy MM dd")
"2022 08 29"
?DateTime.Now.ToString("yyyyMMdd")
"20220829"
?DateTime.Now.ToString("yyyy/MM/dd")
"2022-08-29"

### Expected Behavior

It should convert the date to given format.

### Steps To Reproduce

When i am trying to use DateTime.Now.ToString("yyyy/MM/dd"), it is always returning the response in "2022-08-29" format

following are examples 

?DateTime.Now.ToString("yyyy/MM/dd")
"2022-08-29"
?DateTime.Now.ToString("yyyy%MM%dd")
"2022882929"
?DateTime.Now.ToString("yyyyMMdd")
"20220829"
?DateTime.Now.ToString("yyyy MM dd")
"2022 08 29"
?DateTime.Now.ToString(@"yyyy#MM#dd")
"2022#08#29"
?DateTime.Now.ToString(@"yyyy#MM#dd")
"2022#08#29"
?DateTime.Now.ToString("yyyy MM dd")
"2022 08 29"
?DateTime.Now.ToString("yyyyMMdd")
"20220829"
?DateTime.Now.ToString("yyyy/MM/dd")
"2022-08-29"

### Exceptions (if any)

No

### .NET Version

6

### Anything else?

No

**Comment by skyoxZ** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.globalization.datetimeformatinfo.dateseparator?view=net-6.0#remarks

> If a custom format string includes the "/" format specifier, the DateTime.ToString method displays the value of DateSeparator in place of the "/" in the result string.
  The DateSeparator property defines the string that replaces the date separator ("/" custom date and time format specifier) in a result string in a formatting operation. It also defines the date separator string in a parsing operation.

**Comment by Clockwork-Muse** [comment]
While @skyoxZ is correct about the reason you're seeing this behavior, I want to ask why you want that format.
Generally when dealing with formatting you want one of two things:
 - If you're displaying to an end user, you should be using their local culture settings, and should just display whatever formatting outputs without inspecting it.
 - If you're doing data interchange, you should be using the invariant culture (and in the case of `DateTime(Offset)`, be using the ISO format).
 - 
If you're attempting to do the second one, but you're dealing with a legacy application/specification, then the previous solution is what you'll need to do for a workaround.

**Comment by huoyaoyuan** [comment]
> * If you're doing data interchange, you should be using the invariant culture

Unfortunately invariant culture uses `mmddyyyy` which can be more misinterpreted than `yyyymmdd`. There is a concrete reason to write logs as `yyyymmdd` to avoid misinterpreting as possible.

**Comment by Clockwork-Muse** [comment]
> > * If you're doing data interchange, you should be using the invariant culture
> 
> Unfortunately invariant culture uses `mmddyyyy` which can be more misinterpreted than `yyyymmdd`. There is a concrete reason to write logs as `yyyymmdd` to avoid misinterpreting as possible.

Yes, which is why I call out that the ISO format should be used....

**Comment by ufcpp** [comment]
https://github.com/ufcpp/UfcppSample/blob/master/Demo/2021/Csharp10/InterpolatedStrings/InvariantGlobalization/Iso8601.cs

**Comment by speed2048** [comment]
Interesting  it was working ( according to spec )  incorrectly before  .NET 6.0.7.

I have the following code to create subdirectories  of yyyy\mm\dd and after the .update it would create a single directory called 2022-08-07. 

`private static string setFileDirectoryTimeStamp(DateTime dt) => dt.ToString("yyyy/MM/dd").Replace('/', Path.DirectorySeparatorChar);`

I looked at the release notes for 6.0.7 there is a mention of an IOS fix to DateTIme.Now but unsure how if this  effects  other platforms. IE Windows.

Rant on
I have run into these runtime changes before where .net core changes developers  code and it may take a significant time to debug them and especially if all the ramifications of a code change are not documented.
Rant Off

**Comment by tarekgh** [comment]
@speed2048 `dt.ToString("yyyy/MM/dd")` will treat the `/` as the date separator and not treating it as a literal `/`. meaning when formatting the date will replace every `/` with the formatting culture date separator. I don't know what exactly the culture used in the formatting in your case but for sure that culture is using `-` as a date separator. That is why you ended up with something like `2022-08-07`.

Starting from .NET 5.0, .NET is using ICU library by default. This means the culture data (including the date separator) will be derived from ICU. Before that we used to depend on NLS legacy APIs when running on Windows. It is possible you can find culture data changes between NLS and ICU. Culture data changes are not listed as a breaking change because it is almost impossible to document that with every change in ICU. Instead, you can track the culture data changes in every version in the [CLDR site](https://cldr.unicode.org/).

**Comment by ajaypathak** [comment]
Thanks for the reply will the proposed method and confirm if it works.
