### ISSUE TITLE
BigInteger.Parse creates invalid instances from hex strings

### ISSUE THREAD

**Issue by adetunji-david** [dotnet/runtime#74758]
### Description

By design, the following expression creates an instance of BigInteger with the value of -2
`var x = BigInteger.Parse("FFFFFFFFE", NumberStyles.HexNumber);`
However, x is not equal to another instance with a value of -2.

### Reproduction Steps

`var x = BigInteger.Parse("FFFFFFFFE", NumberStyles.HexNumber);`
`var minusTwo = new BigInteger(-2);`
`Console.WriteLine(x);`
`Console.WriteLine(x == minusTwo);`
`Console.WriteLine(x == -2);`

### Expected behavior

Output is
-2
True
True

### Actual behavior

Output is
-2
True
False

### Configuration

.Net version: 6.0.300
Operating System: Microsoft Windows 10 Pro
Architecture: x64

**Comment by tannergooding** [comment]
This bug also repro's in .NET 6.

**Comment by speshuric** [comment]
It seems I found the cause of the bug. I've fixed it locally, but it needs to be tested. I think I'll send PR in a couple of days.
