### ISSUE TITLE
AppContext.BasedDirectory can not return a valid file directory info

### ISSUE THREAD

**Issue by RNONGFU001** [dotnet/runtime#74750]
Hi,

I am trying to migrate a winform app to a new blazor wasm app. In my winform app, the project referenced a dll lib.  Inside of dll lib, it would call AppContext.BasedDirectory method to get current app directory, in order to location some other files.

the problem is the new blazor app hits a runtime error, coz AppContext.BasedDirectory returns a virtual path as "/", instead of a real file directory info like "C:\kkkk\jjj"

I wonder how to add some codes in my blazor app to make  AppContext.BasedDirectory works as i expect

any idea?

**Comment by SamMonoRT** [comment]
@RNONGFU001 - please can you add more details on .NET version etc ?

@radical - please help triage this issue.

**Comment by radical** [comment]
@RNONGFU001 this is the expected behavior. You can't access the host filesystem in the blazor web assembly app, as it is running in a browser. That is why `AppContext.BaseDirectory` returns `"/`".

@TanayParikh What is the recommended way to make extra files available to the app?

**Comment by TanayParikh** [comment]
> What is the recommended way to make extra files available to the app?

This may be helpful depending on the specific functionality you'd like to achieve: https://docs.microsoft.com/aspnet/core/blazor/fundamentals/static-files?view=aspnetcore-6.0

**Comment by radical** [comment]
> > What is the recommended way to make extra files available to the app?
> 
> This may be helpful depending on the specific functionality you'd like to achieve: [docs.microsoft.com/aspnet/core/blazor/fundamentals/static-files?view=aspnetcore-6.0](https://docs.microsoft.com/aspnet/core/blazor/fundamentals/static-files?view=aspnetcore-6.0)

Local paths are not accessible in a blazorwasm app. The above is one way you can get the files in to your app.
Closing.
