### ISSUE TITLE
JIT: get rid of shortName for phases

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#74768]
As it was discussed, remove shortName column from https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/compphases.h and use actual name (enumName) for e.g. flowgraphs and per-phase dumps. Without PHASE_ prefix.

**Comment by BrianBohe** [comment]
@EgorBo Is the purpose of this issue just to remove the shortName column on compphases.h. Are we ok if the new name is bigger than shortName? For example: ["EDG-WGT" would become "COMPUTE_EDGE_WEIGHTS"](https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/compphases.h#L53).

**Comment by EgorBo** [comment]
> @EgorBo Is the purpose of this issue just to remove the shortName column on compphases.h. Are we ok if the new name is bigger than shortName? For example: ["EDG-WGT" would become "COMPUTE_EDGE_WEIGHTS"](https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/compphases.h#L53).

Yep, it's better than having e.g. `IBCPREP` that doesn't speak of itself much
The idea is to use more meaningful names then for per-phase JitDump/Flowgraph

**Comment by BrianBohe** [comment]
Solved this issue when merging [PR#76030](https://github.com/dotnet/runtime/pull/76030).
