### ISSUE TITLE
VectorSingle and VectorDoubleEqualsNonCanonicalNaNTest fails on Mono

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#74781]
From the logs, the `Assert.False` is failing https://github.com/dotnet/runtime/blob/51f76399be3775c72ccf3134f3ac67549a11e934/src/libraries/System.Numerics.Vectors/tests/GenericVectorTests.cs#L893 

It is tough to tell which nan value is the cause:
https://github.com/dotnet/runtime/blob/51f76399be3775c72ccf3134f3ac67549a11e934/src/libraries/System.Numerics.Vectors/tests/GenericVectorTests.cs#L881-L884

Stack trace:

```
Assert.False() Failure\nExpected: False\nActual:   True
at System.Numerics.Tests.GenericVectorTests.VectorSingleEqualsNonCanonicalNaNTest() in /_/src/libraries/System.Numerics.Vectors/tests/GenericVectorTests.cs:line 893
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)]]
``` 
```
Assert.False() Failure\nExpected: False\nActual:   True
at System.Numerics.Tests.GenericVectorTests.VectorDoubleEqualsNonCanonicalNaNTest() in /_/src/libraries/System.Numerics.Vectors/tests/GenericVectorTests.cs:line 869
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)]]
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by akoeplinger** [comment]
I think this fails on all Mono platforms/configs, we just didn't see it due to the issue that will be fixed by https://github.com/dotnet/runtime/pull/74788.

I'll disable the tests for Mono for now.

**Comment by tannergooding** [comment]
Do we know why or how Mono is failing here?

**Comment by steveisok** [comment]
> Do we know why or how Mono is failing here?

Not yet.  I was primarily trying to keep CI clean.

/cc @SamMonoRT

**Comment by MichalPetryka** [comment]
Should we maybe add custom messages to the asserts that will say which nans are failing?

**Comment by SamMonoRT** [comment]
removing blocking-clean-ci tag as tests have been disabled till we identify the cause/fix.

**Comment by fanyang-mono** [comment]
@steveisok Do you happen to remember which platform the test failed?

**Comment by steveisok** [comment]
> @steveisok Do you happen to remember which platform the test failed?

Looks like they fail for all platforms.

**Comment by dakersnar** [comment]
Is this the right label for this issue?

**Comment by matouskozak** [comment]
The failing cases are when comparing the same elements with each other from the `nans` array using the `==` operator (return `True` instead of `False`). This issue seems to be caused by MiniJIT `OP_XEQUAL`: https://github.com/dotnet/runtime/blob/5333727242ce5357c78bf268a9e4ed8a621bb4b4/src/mono/mono/mini/mini-amd64.c#L3882-L3897. Investigating further.

I can confirm that the tests work correctly when using LLVM JIT or software fallback.

**Comment by matouskozak** [comment]
This issue is fixed by https://github.com/dotnet/runtime/pull/77770.
