### ISSUE TITLE
Investigate changes in Buffer.MemCopy to bring into Span.Clear

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/runtime#7478]
From PR dotnet/coreclr#9598 

https://github.com/dotnet/coreclr/pull/9598#issuecomment-280528642

> I see you copied some of the code from `Buffer.MemoryCopy`... you may want to take a look at https://github.com/dotnet/coreclr/pull/9143 for the managed part of the implementation. It should be more efficient especially on AMD64 because it writes things out in 16/32/64-byte blocks and does not have the extra branches at the beginning/end to check for alignment. (For lengths >= 512/1024 it is probably better to stick to the native implementation.)

**Comment by stephentoub** [comment]
Closing per @GrabYourPitchforks' comment.
