### ISSUE TITLE
Recommended Linux LLDB version

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#74790]
The linux requirements document https://github.com/dotnet/runtime/blob/main/docs/workflow/requirements/linux-requirements.md suggests depending on lldb-6.0. Is that correct? It says we depend on clang-9/llvm-9 for building; shouldn't they be in sync? My Ubuntu 20.04 machine seems to default "lldb" to lldb 10.0.0 and it looks like the latest is version 14 (https://apt.llvm.org/).

Should the docs be updated?

@mikem8361?

**Comment by mikem8361** [comment]
I'm not sure why it is still on lldb 6.0. SOS will work with any version > 4.  It could match the clang/llvm version to be consistent or what every is the latest for the distro which would be just "lldb"/"liblldb-dev". 

In the end, the later lldb version the better.
