### ISSUE TITLE
Four crossgen-comparison jobs are failing regularly in runtime-coreclr crossgen2 outerloop runs

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#74842]
OS-architecture combinations:

**windows-x64-Release-to-x64-linux**
**linux-x64-Release-to-x64-windows**
**linux-x64-Release-to-x86-windows**
**windows-x86-Release-to-x86-windows**

Example run: all recent runtime-coreclr crossgen2 outerloop runs; the most recent one that has already finished and otherwise seems to pass:

https://dev.azure.com/dnceng/public/_build/results?buildId=1972399&view=results

/cc @dotnet/crossgen-contrib, @davidwrighton

**Comment by ivdiazsa** [comment]
> Are these jobs still required given that crossgen2 has been operational since 6?

Ping for visibility @trylek

**Comment by trylek** [comment]
I believe the purpose of these tests is different - they don't compare Crossgen2 with Crossgen1 (they have no way to as Crossgen1 has been gone for more than a year as Manish mentioned), they are about cross-platform compilation, e.g. comparing that Windows x64 Crossgen2 build targeting Linux arm64 produces the same output as running Crossgen2 directly on the Linux arm64 machine. David recently fixed this issue and I have double-checked that the tests are now passing, closing.
