### ISSUE TITLE
Blazor wasm aot is not ahead of time

### ISSUE THREAD

**Issue by sajjadarashhh** [dotnet/runtime#74864]
in this benchmark:
https://krausest.github.io/js-framework-benchmark/2022/table_chrome_102.0.5005.61.html
show's many frameworks to compare them performance
Blazor wasm aot is not compare to wasm native and this very slower than that...
how we can improved blazor wasm runtime performance?

**Comment by lewing** [comment]
Have you tried the benchmarks with .NET 7 preview 7 or later?

**Comment by sajjadarashhh** [comment]
no!

**Comment by sajjadarashhh** [comment]
@lewing for this issue dotnet/linker#3028 I cant test in my solution and i have tried to get .net 7 rc1 but i cant found download links for that...
However thank you for tracking I test when .net 7 rc 1 is released and comment again here

**Comment by lewing** [comment]
Thanks, we're working on it.  Considering this issue closed
