### ISSUE TITLE
[API Proposal]: System.Text.WildcardExpressions  api  

### ISSUE THREAD

**Issue by John0King** [dotnet/runtime#74862]
### Background and motivation

There alwasy need wildcard match in application,   forexample :  `Microsoft.Extensions.Logging`'s  categories  .
and  the  `Operators.LikeString`   is not avaliable in .net core., and there is the new `Span<char>` stuff there.
I think maybe it's time to have the `WildcardExpressions` now.

### API Proposal

```csharp
namespace System.Text.WildcardExpressions;

public class Wildcard
{
       public Wildcard(Span<char> pattern, WildcardOption option){}
    
    public bool IsMatch(Span<char> str){}

    public WildcardMatch Match(Span<char> str, MatchOption option){}

    public static bool IsMatch(Span<char> pattern, Span<char> str, WildcardOption option){}

    public static WildcardMatch Match(Span<char> pattern, Span<char> str, MatchOption option){}

}
```

### API Usage

```csharp
var pattern = new Wildcard("abc*ij".AsSpan());
Console.WriteLine(pattern.IsMatch("abcdefghij".AsSpan()));


```

**Comment by svick** [comment]
> There alwasy need wildcard match in application

Is that true? I'm not convinced a single example is enough to establish that.

Also, if a developer needs a wildcard, they can fairly easily use a regex instead. If a user-facing wildcard is needed, how much code would this save?

---

>  forexample : Ms.Di.Login 's categories

I don't know what this is. Can you explain more, or add a link to what you mean by this?

---

Also, you should consider including more detail in your proposal: What is the exact behavior of these wildcards? How do the types like `WildcardOption` and `WildcardMatch` look like?

**Comment by stephentoub** [comment]
> and the Operators.LikeString is not avaliable in .net core

It is, actually.

**Comment by Tornhoof** [comment]
Depending on where you want to use it, there is the ``FileSystemName`` type for matching file names with wildcards.
https://docs.microsoft.com/en-us/dotnet/api/system.io.enumeration.filesystemname?view=net-6.0

**Comment by John0King** [comment]
@stephentoub   I'll use the `LikeOperator` for now.

@svick 
>  forexample : Ms.Di.Login 's categories

for sorry for  spell error , it should be `Microsoft.Extension.Logging`   
```json
{
    "logging":{
        "Microsoft.*":"Warning"
    }
}
```

> Also, if a developer needs a wildcard, they can fairly easily use a regex instead.

I think `Regex` is slower and  have different behavior when user  enter `.()[]\?*`

> Regex doesn't suffice?
> 
> var pattern = new Regex("abc*ij");
Console.WriteLine(pattern.IsMatch("abcdefghij".AsSpan()));

the pattern should be `abc.*ij` ,  so there is a big challenge for  safely convert  wildcard expression to regular expression.

**Comment by stephentoub** [comment]
> I think Regex is slower

Slower than what? Do you have benchmarks?

> and have different behavior when user enter `.()[]\?*`

Different behavior from what?  This proposal didn't specify any behaviors.

**Comment by John0King** [comment]
@stephentoub 
>  Slower than what? Do you have benchmarks?

this is my benchmarks, because you typeclly use dynamic pattern  when u use wildcard match  so the  RegExp  version is not use `Compiled` flag.
```
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.22000
12th Gen Intel Core i7-12700H, 1 CPU, 20 logical and 14 physical cores
.NET Core SDK=6.0.401
  [Host]     : .NET Core 6.0.9 (CoreCLR 6.0.922.41905, CoreFX 6.0.922.41905), X64 RyuJIT
  Job-VXUFWM : .NET Core 6.0.9 (CoreCLR 6.0.922.41905, CoreFX 6.0.922.41905), X64 RyuJIT

IterationCount=50

|   Method |         sampleString |              pattern |       Mean |    Error |    StdDev |     Median |
|--------- |--------------------- |--------------------- |-----------:|---------:|----------:|-----------:|
|   RegExp | Micro(...)tions [40] | Micro(...)s\..* [25] | 1,349.9 ns | 23.10 ns |  46.67 ns | 1,334.4 ns |
| Wildcard | Micro(...)tions [40] | Micro(...)s\..* [25] |   486.7 ns |  6.37 ns |  12.86 ns |   479.7 ns |
| Wildcard |              abc*def |               abcdef |   186.7 ns |  2.95 ns |   5.82 ns |   185.4 ns |
|   RegExp |               abcdef |             abc.*def | 1,339.7 ns | 76.19 ns | 153.91 ns | 1,349.4 ns |


```

with the source code 

```C#

[SimpleJob(targetCount:50)]
    public class Benchmarks
    {
        

        [Benchmark]
        [Arguments("abcdef", "abc.*def")]
        [Arguments("Microsoft.Extensions.Logging.Abstrations", "Microsoft\\.Extensions\\..*")]
        public void RegExp(string sampleString, string pattern)
        {
            var reg = new Regex(pattern, RegexOptions.IgnoreCase);

            reg.IsMatch(sampleString);
        }

        [Benchmark]
        
        [Arguments("abc*def", "abcdef")]
        [Arguments("Microsoft.Extensions.Logging.Abstrations", "Microsoft\\.Extensions\\..*")]
        public void Wildcard(string sampleString, string pattern)
        {
            LikeOperator.LikeString(sampleString, pattern, Microsoft.VisualBasic.CompareMethod.Text);
        }
    }

```

**Comment by stephentoub** [comment]
> his is my benchmarks, because you typeclly use dynamic pattern when u use wildcard match so the RegExp version is not use Compiled flag.

Even in the case of something that's dynamic, it's very rarely used for only a single matching operation against a short input.  On top of that, the second benchmark pattern (`"Microsoft\\.Extensions\\..*"`) to Wildcard is incorrect and would actually return false from LikeString, and the regex pattern is searching more comprehensively in part because it's not anchored whereas the LikeString input is implicitly anchored.  When I run this:
```C#
[Benchmark]
[Arguments("abcdef", "abc.*def")]
[Arguments("Microsoft.Extensions.Logging.Abstrations", "^Microsoft\\.Extensions\\..*$")]
public void RegExp(string sampleString, string pattern)
{
    Regex.IsMatch(sampleString, pattern, RegexOptions.IgnoreCase);
}

[Benchmark]
[Arguments("abcdef", "abc.*def")]
[Arguments("Microsoft.Extensions.Logging.Abstrations", "^Microsoft\\.Extensions\\..*$")]
public void RegExpCompiled(string sampleString, string pattern)
{
    Regex.IsMatch(sampleString, pattern, RegexOptions.IgnoreCase | RegexOptions.Compiled);
}

[Benchmark]
[Arguments("abcdef", "abc*def")]
[Arguments("Microsoft.Extensions.Logging.Abstrations", "Microsoft.Extensions.*")]
public void Wildcard(string sampleString, string pattern)
{
    LikeOperator.LikeString(sampleString, pattern, Microsoft.VisualBasic.CompareMethod.Text);
}
```

on .NET 7, I get this:

|         Method |         sampleString |              pattern |        Mean |
|--------------- |--------------------- |--------------------- |------------:|
|       Wildcard | Micro(...)tions [40] | Micro(...)ons.* [22] | 1,334.81 ns |
|         RegExp | Micro(...)tions [40] | ^Micr(...)\..*$ [27] |   242.02 ns |
| RegExpCompiled | Micro(...)tions [40] | ^Micr(...)\..*$ [27] |    64.86 ns |
|       Wildcard |               abcdef |              abc*def |   496.17 ns |
|         RegExp |               abcdef |             abc.*def |   175.66 ns |
| RegExpCompiled |               abcdef |             abc.*def |    67.91 ns |

**Comment by John0King** [comment]
I have change my  benmarks  to use the same pattern and sample(all use the same wildcard pattern). 
from the result,  that `Regex` is actully have great result when use static method , but  the problem became  **how to map the wildcard pattern into regex pattern**.

## and here is my result:
```
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.22000
12th Gen Intel Core i7-12700H, 1 CPU, 20 logical and 14 physical cores
.NET Core SDK=6.0.401
  [Host]     : .NET Core 6.0.9 (CoreCLR 6.0.922.41905, CoreFX 6.0.922.41905), X64 RyuJIT
  Job-MJLBPV : .NET Core 6.0.9 (CoreCLR 6.0.922.41905, CoreFX 6.0.922.41905), X64 RyuJIT

IterationCount=50

|    Method |         sampleString |              pattern |       Mean |    Error |    StdDev |     Median |        Min |        Max |
|---------- |--------------------- |--------------------- |-----------:|---------:|----------:|-----------:|-----------:|-----------:|
|    RegExp | Micro(...)tions [40] | Micro(...)ons.* [22] |   425.4 ns | 20.60 ns |  40.19 ns |   413.4 ns |   364.3 ns |   530.5 ns |
|  Wildcard | Micro(...)tions [40] | Micro(...)ons.* [22] |   900.1 ns | 57.80 ns | 116.75 ns |   852.1 ns |   784.6 ns | 1,208.3 ns |
| StartWith | Micro(...)tions [40] | Micro(...)ons.* [22] | 1,116.1 ns |  7.95 ns |  16.06 ns | 1,113.6 ns | 1,090.1 ns | 1,150.9 ns |
|    RegExp |               abcdef |              abcdef* |   164.4 ns |  1.75 ns |   3.50 ns |   164.0 ns |   158.9 ns |   173.4 ns |
|  Wildcard |               abcdef |              abcdef* |   251.8 ns |  3.73 ns |   7.54 ns |   250.6 ns |   238.0 ns |   265.0 ns |
| StartWith |               abcdef |              abcdef* |   574.1 ns | 35.10 ns |  70.90 ns |   565.3 ns |   483.2 ns |   734.5 ns |
```
## and the source
```C#

        [Benchmark]
        [Arguments("abcdef", "abcdef*")]
        [Arguments("Microsoft.Extensions.Logging.Abstrations", "Microsoft.Extensions.*")]
        public void RegExp(string sampleString, string pattern)
        {
            var regPattern = pattern;
            regPattern = regPattern.Replace("\\", "\\\\");
            regPattern = regPattern.Replace(".", "\\.");
            regPattern = regPattern.Replace("*", ".*"); // wildcard keyword
            regPattern = regPattern.Replace("[", "\\[");
            regPattern = regPattern.Replace("]", "\\]");
            regPattern = regPattern.Replace("(", "\\(");
            regPattern = regPattern.Replace(")", "\\)");
            regPattern = regPattern.Replace("?=", "\\?=");
            regPattern = regPattern.Replace("?", ".{1}"); // wildcard keyword
            regPattern = regPattern.Replace("^", "\\^");
            regPattern = regPattern.Replace("!", "\\!");
            regPattern = regPattern.Replace("$", "\\$");
            regPattern = regPattern.Replace("-", "\\-");
            Regex.IsMatch(sampleString, regPattern, RegexOptions.IgnoreCase| RegexOptions.CultureInvariant);
        }

        [Benchmark]

        [Arguments("abcdef", "abcdef*")]
        [Arguments("Microsoft.Extensions.Logging.Abstrations", "Microsoft.Extensions.*")]
        public void Wildcard(string sampleString, string pattern)
        {
            LikeOperator.LikeString(sampleString, pattern, Microsoft.VisualBasic.CompareMethod.Text);
        }

        [Benchmark]
        [Arguments("abcdef", "abcdef*")]
        [Arguments("Microsoft.Extensions.Logging.Abstrations", "Microsoft.Extensions.*")]
        public void StartWith(string sampleString, string pattern)
        {
            var startPos = pattern.LastIndexOf('*');
            if(startPos >= 0)
            {
                pattern = pattern.Substring(0, startPos);
            }

            sampleString.StartsWith(pattern);
        }
    }

```

**Comment by danmoseley** [comment]
You can do most of that with Regex.Escape() followed by special treatment of the escaped * and ?

**Comment by John0King** [comment]
@danmoseley   not sure how I used it ,  escape first and then replace `\\*`  and `\\?`

**Comment by danmoseley** [comment]
Yes replace \* and and \? with .* and .

**Comment by joperezr** [comment]
@John0King are you able to be unblocked by Regex for your scenarios? If so, given the above discussion, let us know so we can close this proposal.

**Comment by John0King** [comment]
yes, and thanks
