### ISSUE TITLE
JIT: GC\API\GC\GetTotalPauseDuration failing in experimental pipeline

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#74877]
Quite a few different test modes see failures in this test.

https://dev.azure.com/dnceng/public/_build/results?buildId=1957581&view=ms.vss-test-web.build-test-results-tab

coreclr windows arm64 Checked jit_stress_splitting @ Windows.10.Arm64v8.Open
coreclr windows arm64 Checked jitobjectstackallocation @ Windows.10.Arm64v8.Open
... (more) ...

Failure is just an unexpected return code:
```
BEGIN EXECUTION
"D:\h\w\9A12086B\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  GetTotalPauseDuration.dll
Expected: 100
Actual: 101
END EXECUTION - FAILED
```

**Comment by AndyAyersMS** [comment]
Also failing in jitstress-random:

https://dev.azure.com/dnceng/public/_build/results?buildId=1972745&view=ms.vss-test-web.build-test-results-tab

(still all on arm64)

**Comment by jakobbotsch** [comment]
Dup of #74631?

**Comment by AndyAyersMS** [comment]
Could be, yes. Seems likely this test is just broken on arm64.

**Comment by AndyAyersMS** [comment]
Note this test has been disabled for now (https://github.com/dotnet/runtime/pull/75141). 

Since this issue is a dup of https://github.com/dotnet/runtime/issues/74631, I'll close.
