### ISSUE TITLE
Assert failure: RawGetMethodTable() on linux-arm (LibraryImportGenerator.Unit.Tests)

### ISSUE THREAD

**Issue by AntonLapounov** [dotnet/runtime#74895]
```
Assert failure(PID 22 [0x00000016], Thread: 59 [0x003b]): RawGetMethodTable()
    File: /__w/1/s/src/coreclr/gc/gc.cpp Line: 4539
    Image: /root/helix/work/correlation/dotnet
```
https://dev.azure.com/dnceng/public/_build/results?buildId=1977495&view=logs&jobId=62876419-b96e-5483-94d3-b47175c1afe7

Additionally, `Assert failure: m_alignpad == 0` on linux-arm was reported in https://github.com/dotnet/runtime/issues/70231#issuecomment-1209618725.

**Comment by mangod9** [comment]
Closing since looks like the fix was merged.

**Comment by AntonLapounov** [comment]
@mangod9 If you meant #74847, it was a fix for a different issue.  Jan asked me to create this issue here: https://github.com/dotnet/runtime/pull/74847#issuecomment-1233049944.
