### ISSUE TITLE
System.Media.SystemSounds.Beep.Play fails silently on Windows Server 2022 20348

### ISSUE THREAD

**Issue by riverar** [dotnet/runtime#74909]
### Description

Attempting to emit a beep via `System.Media.SystemSounds.Beep.Play` fails silently on Windows Server 2022 20348.xxx. (The underlying `user32!MessageBeep(0)` also fails but because there's no monitored location to file OS bugs at this time and this issue impacts .NET, I'm filing this here.)

Affects .NET Framework 4.x and .NET 5+ (via System.Windows.Extensions.SystemSounds).

Original report https://github.com/File-New-Project/EarTrumpet/issues/1210.

### Reproduction Steps

1. Create a new C# .NET 5+ console project with top-level statement support
2. Paste in the following code, replacing any existing templated code

    ```csharp
    Console.WriteLine("Beep.");
    System.Media.SystemSounds.Beep.Play();
    ```
3. Compile/run app on affected OS version
4. Observe no sound emitted

### Expected behavior

Beep.

### Actual behavior

No beep.

### Configuration

Tested, not working:
Windows Server 2022 20348.261
Windows Server 2022 20348.887

Tested, working:
Windows 11 22000.739
Windows 11 25188.1000

**Comment by brabebhin** [comment]
Maybe the servers are missing the media support packages. 🤔

**Comment by feiyun0112** [comment]
please make sure `Windows Audio Service` is started

**Comment by riverar** [comment]
The audio service is started and audio is working throughout the OS.

**Comment by feiyun0112** [comment]
did you connect the server use RDP?

**Comment by riverar** [comment]
@feiyun0112 Yep. All audio working over RDP except MessageBeep.

**Comment by riverar** [comment]
@ViktorHofer Did some sort of discussion occur that put this on the map for 8.0? Just curious, thanks!

**Comment by riverar** [comment]
Any updates on this? Need to know if I need to make plans to move off this now broken API.

**Comment by riverar** [comment]
@richlander Can I get an assist here? Maybe an OS ADO bug to track?

**Comment by danmoseley** [comment]
> The underlying user32!MessageBeep(0) also fails but because there's no monitored location to file OS bugs at this time and this issue impacts .NET, I'm filing this here.)

The place to file OS bugs is the Windows feedback tool, category likely Developer Platform. Did you try that?

**Comment by riverar** [comment]
@danmoseley I'm told the owners of that area do not monitor that area for feedback.

**Comment by riverar** [comment]
Also, seeing as this affects a .NET API, I'd imagine the onus of filing an upstream bug is on the .NET team, not me.

**Comment by danmoseley** [comment]
@Jkotas do you know of a public way to report win32 bugs?

**Comment by jkotas** [comment]
@danmoseley Windows feedback tool that you have mentioned.

**Comment by danmoseley** [comment]
@riverar I got a response from Windows that this is by design. "On Server, the Microsoft\Windows\Multimedia\SystemSoundsService task is disabled. This task will need to be enabled for MessageBeep to function."
Hope this helps.
