### ISSUE TITLE
Binary search on SortedSet/Dict

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/runtime#74934]
It seems to me that binary search(std::lowerbound) is still not provided out of box in current implementation of SortedSet/Dict. Is it by design? Can we consider add it if it's indeed not available?

**Comment by stephentoub** [comment]
Can you elaborate @StephenBonikowsky? `SortedDictionary/Set<>.Contains(TKey)` does a binary search, starting at the root node and walking down through the left or right child based on a compare at each node.

**Comment by eiriktsarpalis** [comment]
I'm guessing this concerns binary search scoped to particular ranges, built-in lookup is implemented using binary search. For `SortedSet` it should be possible to implement to achieve this using a combination of the [`GetViewBetween`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.sortedset-1.getviewbetween?view=net-6.0) method and regular lookups (but it currently requires both a lower and an upper bound). Related to #55510.

**Comment by StephenBonikowsky** [comment]
@stephentoub I opened this on behalf of someone else, unfortunately they have been unreachable, I don't have any other context to add.

**Comment by eiriktsarpalis** [comment]
In that case, I think we should close the issue for now. We can always reopen if new feedback comes by.
