### ISSUE TITLE
[wasm] `Wasm.Build.Tests` failing with `Generator 'JSExportGenerator' failed to initialize`.. `FileNotFoundException`.. `Microsoft.Interop.SourceGeneration`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#74944]
`Wasm.Build.Tests.WasmTemplateTests` failing on multiple PRs. On https://github.com/dotnet/runtime/pull/74704 it [failed with](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-74704-merge-1c48b28f96a64a229f/Workloads-.WasmTemplateTests/1/console.df3a1156.log?helixlogtype=result):

```
/datadisks/disk1/work/ABD10942/w/B5030994/e/dotnet-workload/sdk/7.0.100-rc.2.22426.5/MSBuild.dll /nologo -maxcpucount -property:_IsPublishing=true --property:WasmBuildOnlyAfterPublish=true --property:AppRefDir=/datadisks/disk1/work/ABD10942/p/microsoft.netcore.app.ref --property:Configuration=Debug -restore -target:Publish -verbosity:m /v:minimal /bl:/datadisks/disk1/work/ABD10942/w/B5030994/uploads/xharness-output/logs/Debug_rgbarhvz.zdp/Debug_rgbarhvz.zdp.binlog ./Debug_rgbarhvz.zdp.csproj
  Determining projects to restore...
  Restored /datadisks/disk1/work/ABD10942/w/B5030994/e/Debug_rgbarhvz.zdp/Debug_rgbarhvz.zdp.csproj (in 4 ms).

CSC : warning CS8784: Generator 'JSExportGenerator' failed to initialize. It will not contribute to the output and compilation errors may occur as a result.
	Exception was of type 'FileNotFoundException' with message 'Could not load file or assembly
		'Microsoft.Interop.SourceGeneration, Version=42.42.42.42, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. [/datadisks/disk1/work/ABD10942/w/B5030994/e/Debug_rgbarhvz.zdp/Debug_rgbarhvz.zdp.csproj]
CSC : warning CS8784: Generator 'JSImportGenerator' failed to initialize. It will not contribute to the output and compilation errors may occur as a result.
	Exception was of type 'FileNotFoundException' with message 'Could not load file or assembly
		'Microsoft.Interop.SourceGeneration, Version=42.42.42.42, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. [/datadisks/disk1/work/ABD10942/w/B5030994/e/Debug_rgbarhvz.zdp/Debug_rgbarhvz.zdp.csproj]
CSC : warning CS8784: Generator 'LibraryImportGenerator' failed to initialize. It will not contribute to the output and compilation errors may occur as a result.
	Exception was of type 'FileNotFoundException' with message 'Could not load file or assembly
		'Microsoft.Interop.SourceGeneration, Version=42.42.42.42, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. [/datadisks/disk1/work/ABD10942/w/B5030994/e/Debug_rgbarhvz.zdp/Debug_rgbarhvz.zdp.csproj]

/datadisks/disk1/work/ABD10942/w/B5030994/e/Debug_rgbarhvz.zdp/Program.cs(21,36):
	error CS8795: Partial method 'MyClass.GetNodeVersion()' must have an implementation part because it has accessibility modifiers. [/datadisks/disk1/work/ABD10942/w/B5030994/e/Debug_rgbarhvz.zdp/Debug_rgbarhvz.zdp.csproj]
```

Also seen on https://github.com/dotnet/runtime/pull/74705 .

cc @maraf @pavelsavara 

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by radical** [comment]
@ericstj could this be related to https://github.com/dotnet/runtime/pull/74897 ? This is a wasm template project being built with a rc2 sdk, and `wasm-tools` workload installed.

This is effectively what's being run:

1. `dotnet new wasmconsole`
2. `dotnet publish -p:WasmBuildOnlyAfterPublish=true  /p:AppRefDir=/datadisks/disk1/work/ABD10942/p/microsoft.netcore.app.ref /p:Configuration=Debug /nologo /v:minimal`

**Comment by ericstj** [comment]
Yes, you need https://github.com/dotnet/runtime/pull/74943

**Comment by lewing** [comment]
It is a bit disheartening that #74897 landed without running a test of the JSImport generator

**Comment by radical** [comment]
`dotnet-runtime-perf` pipeline is also completely broken because of this.

**Comment by radical** [comment]
The PR didn't run *any* pipelines at all - https://github.com/dotnet/runtime/pull/74897/checks . Probably because of the recent CI issues.

**Comment by ericstj** [comment]
Yeah, that's my working theory.  I hope we have some coverage in place that we produce a ref-pack that can be compiled against.  I could imagine a gap here though, and it's something that ought to be filled.

**Comment by mdh1418** [comment]
@ericstj @radical this seems to be hit in https://dev.azure.com/dnceng/internal/_build/results?buildId=2025986&view=logs&j=e03514e4-7a9e-5ba7-bee9-ca11f22f7633&t=a10fe5e9-c3be-575c-60d2-714e40563a72 on a branch that already has the fix from https://github.com/dotnet/runtime/pull/74943. Any idea why it would be hit?
