### ISSUE TITLE
ServerNoEncryption_ClientRequireEncryption_NoConnect passes on Ubuntu 22.04 with message about error:0A0000C1:SSL routines::no shared cipher

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#74970]
This running in Ubuntu 22.04 WSL, the test passes but writes error output here. I'm not sure what the reason is for logging, if the exception is caught as here.

https://github.com/dotnet/runtime/blob/7a45201181d37329b7ab0bee541ed7c42b5d94b6/src/libraries/System.Net.Security/tests/FunctionalTests/ServerNoEncryptionTest.cs#L39-L47
```
    <test name="System.Net.Security.Tests.ServerNoEncryptionTest.ServerNoEncryption_ClientRequireEncryption_NoConnect" type="System.Net.Security.Tests.ServerNoEncryptionTest" method="ServerNoEncryption_ClientRequireEncryption_NoConnect" time="0.2489706" result="Pass">
        <output><![CDATA[System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:0A0000C1:SSL routines::no shared cipher
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount) in /home/dan/git/runtime/src/libraries/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs:line 545
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions, SelectClientCertificate clientCertificateSelectionCallback) in /home/dan/git/runtime/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Unix.cs:line 167
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken) in /home/dan/git/runtime/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.IO.cs:line 323
   at System.Net.Security.Tests.ServerNoEncryptionTest.ServerNoEncryption_ClientRequireEncryption_NoConnect() in /home/dan/git/runtime/src/libraries/System.Net.Security/tests/FunctionalTests/ServerNoEncryptionTest.cs:line 41
]]></output>
      </test>
```

**Comment by wfurt** [comment]
It will be dumped to console output if test fails. (_log is `ITestOutputHelper`) That makes it easier to troubleshoot.

**Comment by danmoseley** [comment]
Right but it's logging when it's passing here?

**Comment by rzikm** [comment]
When the test fails for some reason, the log message makes it easier to diagnose. Unfortunately, it is not possible to know inside the catch block if the test will pass or not (the server throws on "success" case as well), so we log the exception always.

**Comment by karelz** [comment]
Perhaps we should log text explaining that it is nothing to worry about and it is only for diagnostics purposes?

**Comment by danmoseley** [comment]
When it fails, that means ThrowsAsync throws XunitException? Could we catch that, log the output there that we captured in the existing catch, and returned?

**Comment by danmoseley** [comment]
Right, I'm suggesting at the point we currently log the output , to instead capture it into a string. Then later, if the test will fail (XunitException is thrown) log that string then rethrow the exception so the test fails.

**Comment by wfurt** [comment]
We could @danmoseley. But that seems line unnecessary complication. The decision on failure is somewhere else so we would need to check if we _would_ fail and then we would need to spit it out before actual failure. AFAIK we don't store this anywhere in Kusto so I really see no penalty for using `ITestOutputHelper`. It is not just this particular test. If we have real concern. we should fix Unit IMHO to not write out `ITestOutputHelper` output on pass.

**Comment by danmoseley** [comment]
Whatever you prefer is of course fine by me. 

@MattGal can you confirm that stuff inside (in xunit terms)  `<output>` in testResults.xml is not ingested into Helix/Kusto systems?

**Comment by MattGal** [comment]
> Whatever you prefer is of course fine by me.
> 
> @MattGal can you confirm that stuff inside (in xunit terms) `<output>` in testResults.xml is not ingested into Helix/Kusto systems?

Correct, I think because often times this would be excessive to fit into the Kusto DB.  One can easily get back the result XML though for reading this as needed.

**Comment by wfurt** [comment]
triage: thanks @MattGal. We will keep it to make it easier to diagnose any possible failures.
