### ISSUE TITLE
Cross-Compilation from Arm64 to x64 fails on M1 Mac

### ISSUE THREAD

**Issue by ivdiazsa** [dotnet/runtime#74973]
### Description

I was running some inter-architecture experiments with multiple OS's, when I bumped across this bug. I can't get an OSX x64 build using my M1 Mac anymore because the cross-building fails now.

Running the following command:

```bash
./build.sh --subset clr --configuration Release --cross --arch x64
```

Yields the following error:

```bash
[  9%] Preprocessing /path/to/runtime/src/coreclr/dlls/mscorrc/include.rc. Outputting to /path/to/runtime/artifacts/obj/coreclr/OSX.x64.Release/dlls/mscorrc/mscorrc.rc.i
  In file included from /path/to/runtime/src/coreclr/dlls/mscorrc/include.rc:4:
  In file included from /path/to/runtime/src/coreclr/dlls/mscorrc/mscorrc.rc:7:
  In file included from /path/to/runtime/src/coreclr/pal/prebuilt/inc/corerror.h:7:
  In file included from /path/to/runtime/src/coreclr/pal/inc/rt/winerror.h:12:
  In file included from /path/to/runtime/src/coreclr/pal/inc/rt/palrt.h:136:
  /path/to/runtime/src/coreclr/pal/inc/pal.h:2659:2: error: PAL_CS_NATIVE_DATA_SIZE is not defined for this architecture
  #error  PAL_CS_NATIVE_DATA_SIZE is not defined for this architecture
   ^
  [  9%] Building C object /path/to/runtime/artifacts/obj/external/libunwind/CMakeFiles/libunwind_dac.dir/path/to/runtime/src/native/external/libunwind/src/remote/mac/missing-functions.c.o
  [  9%] Building CXX object md/ceefilegen/CMakeFiles/ceefgen_obj.dir/ceegentokenmapper.cpp.o
  1 error generated.
  make[2]: *** [dlls/mscorrc/mscorrc.rc.i] Error 1
  make[1]: *** [dlls/mscorrc/CMakeFiles/mscorrc_obj.dir/all] Error 2
  make[1]: *** Waiting for unfinished jobs....
```

It worked fine until recently, so this is a very recent failure.

### Reproduction Steps

1. Clone the runtime repo to your machine
2. Issue the build command from the repo's root: `./build.sh --subset clr --cross --arch x64`

### Expected behavior

Build should complete successfully without any issues.

### Actual behavior

Build fails at about 9%.

### Regression?

Yes. Don't know exactly when it broke, but for example, it works on the Preview 7 codebase.

### Known Workarounds

No workaround.

**Comment by janvorli** [comment]
@am11, `git bisect` shows that this got broken by your change #73530. Could you please take a look?

**Comment by janvorli** [comment]
Btw, even before the problematic change, there is another issue. The coreclr build completes ok, but the cross components build fails here:
https://github.com/dotnet/runtime/blob/04ca89d9fb963a2f57582e85bb0c6e626f64c96f/eng/native/configureplatform.cmake#L449
The problem here is that the check is missing the arm64 host / amd64 target check as valid combination.
And even with that fixed, we hit a problem while compiling `src/coreclr/pal/src/exception/seh-unwind.cpp`. 
There are many errors like the following:
```
  /Users/janvorli/git/runtime/src/coreclr/pal/src/exception/seh-unwind.cpp:263:25: error: use of undeclared identifier 'UNW_AARCH64_X29'; did you mean 'UNW_ARM64_X29'?
      unw_set_reg(cursor, UNW_AARCH64_X29, winContext->Fp);
                          ^~~~~~~~~~~~~~~
                          UNW_ARM64_X29
```

**Comment by janvorli** [comment]
I'll fix the other problems once the current issue with PAL_CS_NATIVE_DATA_SIZE is fixed.

**Comment by am11** [comment]
> that this got broken by your change https://github.com/dotnet/runtime/pull/73530.

@janvorli, I admit this got worsen, but did you continue bisecting to find out when was this happening:

> It worked fine until recently, so this is a very recent failure.

with `./build.sh --subset clr --configuration Release --cross --arch x64`? The  `check if host & target os/arch combination are valid` is super old and I think it never would have succeeded the cross components part.

**Comment by am11** [comment]
> it works on the Preview 7 codebase.

that also fails on my M1:
```sh
$ git pull --tags --all
$ git checkout v7.0.0-preview.7.22375.6
$ ./build.sh --subset clr --configuration Release --cross --arch x64
...
  -- Detecting CXX compile features - done
  CMake Error at /runtime/eng/native/configureplatform.cmake:440 (message):
    Invalid platform and target arch combination TARGET_ARCH=x64
    HOST_ARCH=arm64
```

@ivdiazsa, can you give us the reference where this was working? I don't think it is a regression at all.

**Comment by janvorli** [comment]
These are the other issues I've mentioned in my comment above. I've found they are caused by that check in the configureplatform.cmake and just two places in code where we use HOST_ARM64 instead of TARGET_ARM64 at one place and vice versa at the other. 
I believe this cross build used to work when I have enabled build on macos arm64 initially, but I might be mistaken.

**Comment by am11** [comment]
@janvorli, could you apply this patch with rest your changes:
```diff
-#elif defined(__APPLE__) && defined(__x86_64__)
+#elif defined(__APPLE__) && defined(HOST_AMD64)
```

**Comment by janvorli** [comment]
Thanks a lot @am11, that did the trick. With our changes combined, the build now works. I'll create a PR for the whole fix.

**Comment by ivdiazsa** [comment]
Thanks a lot for the help @janvorli!
