### ISSUE TITLE
blazor wasm and efcorepreview 7 SQLitePCLRaw.bundle_e_sqlite3 ver 2.1.0 and 2.1.1 preview fails in runtime

### ISSUE THREAD

**Issue by sajjadarashhh** [dotnet/runtime#74988]
### Description

when I want to use a sqlite and efcore db in blazor wasm .net 7 preview 7
I use [Patrick Jahr approach](https://www.thinktecture.com/en/blazor/ef-core-and-sqlite-in-browser/) but it's failure with this issue:
![image](https://user-images.githubusercontent.com/72276897/188121816-2f5119e7-b46d-4624-beda-2d02f69451f2.png)
something is wrong in that tutorial!?
.net 7 have breaking changes or this is a bug?

### Reproduction Steps

1. create .net 7 preview 7 blazor wasm project
2. install ef Core latest preview version and efCore.sqlite same version
3. install SQLitePCLRAW.bundle_e_sqlite3
4. use Patrick jar steps and execute In release mode

### Expected behavior

throws exception on select query and create dbCommand

### Actual behavior

this is in .net 6 works prefect

**Comment by radical** [comment]
cc @SteveSandersonMS

**Comment by SteveSandersonMS** [comment]
@radical I don't see any definite indication that this is Blazor specific. I know the @sajjadarashhh is reporting it in the context of a Blazor app, but the error is coming from SQLitePCLRAW.bundle_e_sqlite3 - a package that should work on wasm whether or not Blazor is being used, and apparently does work on .NET 6.

Perhaps I'm missing something, but this seems like *either*:

 * A runtime regression
 * Or, something about `SQLitePCLRAW.bundle_e_sqlite3` that is hardcoded to work on .NET 6 only. For example it might rely on a `net6.0` path, or worse, might embed a `NativeFileReference` binary built with a specific Emscripten version that isn't compatible with .NET 7. It would be pretty unfortunate if the ecosystem gets split on every major version, so if this is the case we should prioritize providing guidance about how to make packages that work independently of the SDK's Emscripten version and work with existing package authors to ensure that existing popular packages are updated. cc @lewing @danroth27

**Comment by sajjadarashhh** [comment]
there's any way to change path's manually!?

**Comment by sajjadarashhh** [comment]
this resolved from ericsinc SQLitePCL package

**Comment by bricelam** [comment]
> ...or worse, might embed a NativeFileReference binary built with a specific Emscripten version that isn't compatible with .NET 7. It would be pretty unfortunate if the ecosystem gets split on every major version, so if this is the case we should prioritize providing guidance about how to make packages that work independently of the SDK's Emscripten version and work with existing package authors to ensure that existing popular packages are updated.

+1 to all of this. This was the issue, and I totally did forget that we needed to do this until this issue eventually reached me.

**Comment by SteveSandersonMS** [comment]
Excellent, thanks for resolving this!
