### ISSUE TITLE
[API Proposal]: Add Constructors to Initialize AsyncLocal<T> to Specified Initial Value

### ISSUE THREAD

**Issue by JCropsey-Clearwave** [dotnet/runtime#74997]
### Background and motivation

Currently, the AsyncLocal<T> doesn't have a way to initialize the Value property to a specified initial value (besides default(T)) like ThreadLocal<T> does https://docs.microsoft.com/en-us/dotnet/api/system.threading.threadlocal-1.-ctor?view=net-6.0#system-threading-threadlocal-1-ctor(system-func((-0)))

My request is to add to constructor overrides:
* AsyncLocal<T>(T initialValue)
* AsyncLocal<T>(Func<T> initialValueFactory)

Whenever the AsyncLocal<T> is accessed in the current async control flow, and it has not been initialized, then it would be set to the initial value provided by one of those two constructors rather than default(T).

### API Proposal

```csharp
namespace System.Threading;

public sealed class AsyncLocal<T>
{
  public AsyncLocal<T>(T initialValue);
  public AsyncLocal<T>(Func<T> valueFactory);  // We would also need overrides to preserve the ability to receive notifications from changes within the ambiance.
}
```

### API Usage

```csharp
public class MyClass
{
  private readonly AsyncLocal<int> countDownCount1;
  private readonly AsyncLocal<int> countDownCount2;
  
  public MyClass()
  {
    countDownCount1 = new AsyncLocal<int>(10);  // Initializes every new ambiance of countDownCount1 to 10.
    countDownCount2 = new AsyncLocal<int>(() => GetValueFromSomewhere());  // Initializes every new ambiance of countDownCount2 to whatever GetValueFromSomewhere() provides. This could be different for every ambiance.
  }
}
```

### Risks

This shouldn't have performance impact other than the consequences of calling the valueFactory. The system already has a means of determining whether Value has been initialized in the current async control flow, so we're not introducing any additional burden there.

**Comment by davidfowl** [comment]
When would it get the initial value?

**Comment by stephentoub** [comment]
Presumably the request is that here:
https://github.com/dotnet/runtime/blob/8b73164bf51047edc078c5e67dffa085b1f3b89e/src/libraries/System.Private.CoreLib/src/System/Threading/AsyncLocal.cs#L38
instead of returning default, if a default override was provided, it's both stored and returned there?

>  My request is to add to constructor overrides:

Can you provide more details about the scenarios you have requiring this?

**Comment by davidfowl** [comment]
I see so this isn’t about mutating the execution context per se.

**Comment by stephentoub** [comment]
> I see so this isn’t about mutating the execution context per se.

It would change what is set as the current EC, e.g. instead of
```C#
return default;
```
it would be:
```C#
T result = default;
if (_defaultFunc is Func<T> f)
{
    result = f();
    Value = result; // sets current EC
}
return result;
```
I'm still not clear when/why this would be needed, though.

**Comment by davidfowl** [comment]
I don’t like the idea of mutating the execution context as a side effect of reading the property. I know it can happen today but I agree but we should wait for the scenario…

**Comment by JCropsey-Clearwave** [comment]
Two original use cases:
* Suppose we want to have a limit as to the number of times a certain event can happen in an async context. E.g., we can have 5 failures before aborting. The goal was to seed the AsyncLocal<int>(5) and then deduct one whenever a failure occurs. (I realize this is trivial since it can be implemented as a count-up instead of a count-down.) However, for variables that include 0 in their range instead of as a default and/or terminal value, it becomes difficult to distinguish between whether the AsyncLocal is still with an initial value or a later-assigned value.
* Suppose we have a by-reference object that we never want to be nullable. E.g., a logging context. The current constructor prevents this since we can't provide any initialization reference. By adding a AsycnLocal<LoggingContext>(loggingContextInstance), we can remove the necessity of checking for whether this is null at every access since the compiler can confirm that it's never possible to be null.
