### ISSUE TITLE
PrincipalContext.ValidateCredentials for PIN not Password

### ISSUE THREAD

**Issue by youss2017** [dotnet/runtime#74992]
area: area-System.DirectoryServices

PrincipalContext.ValidateCredentials works fine for password, however, is there a version of this function that works with a PIN not a password. Thanks. [area-System.DirectoryServices]

**Comment by youss2017** [comment]
@area-System.DirectoryServices

**Comment by youss2017** [comment]
If that is not possible, is there a way to read the PIN hash from the active directory server.

**Comment by SteveSyfuhs** [comment]
PINs are not centralized credentials. They do not get stored in Active Directory and are relative to the underlying credential that the PIN protects. A PIN is only ever used to unlock another credential, such as a smart card, Windows Hello key, or FIDO device. Once that credential is unlocked by the PIN, the credential itself is the thing that authenticates to Active Directory or Windows. The PIN never leaves the machine.

As such, the correct action that needs to happen is that you need to select the underlying credential to use, and if that credential is protected by a PIN, then it will automatically prompt for creds through Windows UI that way you are never entering a PIN into a 3rd party application.

**Comment by youss2017** [comment]
Thanks, I was looking in the wrong place. I need research smart card authentication.

**Comment by joperezr** [comment]
@SteveSyfuhs thanks for the reply. @youss2017 even if the issue gets closed, you can still post how you worked around your issue. If it's ok with you, I'd rather close this issue for now due to housekeeping purposes, but feel free to re-open or comment after the issue gets closed.
