### ISSUE TITLE
Add more granular pipelines for mobile configurations

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#75002]
When trying to validate a specific mobile change, we'll manually trigger `runtime-extra-platforms` to run all tests.  This results in running a large swath of configurations that, more often than not, do not need to run.  The goal of this issue is to offer more granular pipelines by configuration and determine if we should go deeper (libraries vs runtime tests, for example).

All libraries and runtime tests
- [ ] Android emulators
- [ ] Android devices
- [ ] iOS/tvOS simulators
- [ ] iOS/tvOS devices
- [ ] MacCatalyst

https://github.com/dotnet/runtime/pull/74859 can be used for inspiration

**Comment by directhex** [comment]
So we want

a) not smoke-tests-only. These new pipelines should run all tests. or only run all tests when called directly, otherwise run smoke tests when run as a template include into runtime-extra-platforms?

b) only move the things we're testing in runtime-extra-platforms (e.g. interp vs not, sandbox vs not, AOT vs not, etc etc etc) - don't touch things we're testing in other pipelines like runtime.yml?

**Comment by directhex** [comment]
@steveisok ^^ ?

**Comment by steveisok** [comment]
For mobile, we want to take what's in runtime-extra-platforms and split the mobile configurations into different pipelines.  

To answer your questions directly: 

a.) yes, the pipelines should run all tests when triggered manually. We don't want to run these on a schedule.  

b.) correct

**Comment by carlossanlop** [comment]
@dotnet/area-infrastructure-libraries should we consider doing something similar for runtime libraries legs?

**Comment by ViktorHofer** [comment]
> should we consider doing something similar for runtime libraries legs?

Can you please elaborate on what you mean by that? If I'm not misunderstanding, libraries testing is part of what this issue is tracking.

**Comment by directhex** [comment]
Dunno why this wasn't closed with the merge

**Comment by directhex** [comment]
Aha, merged into feature branch not main
