### ISSUE TITLE
Mono Bionic Android arm64 CI failure - Failed to get device's property SupportedArchitectures / Device unauthorized / $ADB_VENDOR_KEYS is not set

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#75022]
Found in a release/7.0 PR: https://github.com/dotnet/runtime/pull/74926

- Queue: `net7.0-Linux-Release-arm64-Mono_Release_LinuxBionic-Windows.10.Amd64.Android.Open`
- Artifacts: https://dev.azure.com/dnceng-public/public/_build/results?buildId=1392&view=ms.vss-test-web.build-test-results-tab&runId=19052&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab&resultId=180803
- Affected the `System.Diagnostics.Contracts.Tests` work item.
Log file: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-74926-merge-0416eef15c6a45a1a6/System.Diagnostics.Contracts.Tests/1/console.fa330ef5.log?helixlogtype=result
Callstack:
```
[11:56:41] fail: Failed to get device's property SupportedArchitectures. Check if a device is attached / emulator is started
                 error: device unauthorized.
                 This adb server's $ADB_VENDOR_KEYS is not set
                 Try 'adb kill-server' if that seems wrong.
                 Otherwise check for a confirmation dialog on your device.
                 
[11:56:41] fail: No attached device supports one of required architectures arm64-v8a
[11:56:41] dbug: No suitable devices found
[11:56:41] crit: Failed to find compatible device: arm64-v8a
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by directhex** [comment]
Any other bad builds from DNCENGWIN-081?

**Comment by akoeplinger** [comment]
haven't seen this recently, closing
