### ISSUE TITLE
WASM CI failure in `DebuggerTests.BreakpointTests.ConditionalBreakpoint2`

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#75020]
Found in a release/7.0 PR: https://github.com/dotnet/runtime/pull/74926

Please help determine if this needs a fix backported to 7.0.

- Queue: `net7.0-Browser-Release-wasm-Mono_firefox_Release-WasmDebuggerTests-(Ubuntu.1804.Amd64)`
- Artifacts: https://dev.azure.com/dnceng-public/public/_build/results?buildId=1392&view=ms.vss-test-web.build-test-results-tab&runId=18640&paneView=debug&resultId=100002
- Log file: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-74926-merge-b804a8ffd359492593/firefox-DebuggerTests/1/console.9989d601.log?helixlogtype=result
- Callstack: 
```
[xUnit.net 00:04:27.16]     DebuggerTests.BreakpointTests.ConditionalBreakpoint2(function_to_call: "invoke_add()", method_to_stop: "IntAdd", condition: "c == \"xyz\"", bp_stop_expected: False) [FAIL]
  Failed DebuggerTests.BreakpointTests.ConditionalBreakpoint2(function_to_call: "invoke_add()", method_to_stop: "IntAdd", condition: "c == \"xyz\"", bp_stop_expected: False) [775 ms]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at DebuggerTests.DebuggerTestFirefox.SetBreakpointInMethod(String assembly, String type, String method, Int32 lineOffset, Int32 col, String condition) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestFirefox.cs:line 415
   at DebuggerTests.BreakpointTests.ConditionalBreakpoint2(String function_to_call, String method_to_stop, String condition, Boolean bp_stop_expected) in /_/src/mono/wasm/debugger/DebuggerTestSuite/BreakpointTests.cs:line 211
--- End of stack trace from previous location ---
```

**Comment by radical** [comment]
Closing this as firefox tests are known to be unstable, because of which we the `runtime-staging` job ignores the test failures.
