### ISSUE TITLE
Build failure in Microsoft.Extensions.HostFactoryResolver.Tests: xunit.assert 2.4.2 - author primary signature's signing certificate is not trusted by the trust provider

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#75040]
Found in this backport PR for 7.0: https://github.com/dotnet/runtime/pull/75004

- Queue: Libraries Build windows x86 Release
- Job results: https://dev.azure.com/dnceng-public/public/_build/results?buildId=3088&view=logs&j=3258e425-c037-59ba-e3ca-218fa6e3ed33&t=76cb4e3c-6e9e-5caf-ce6b-8e12bca87c99
- Step that failed: Restore and build product
- Error message:
```
##[error]src\libraries\Microsoft.Extensions.HostFactoryResolver\tests\Microsoft.Extensions.HostFactoryResolver.Tests.csproj(0,0):
error NU3018: (NETCORE_ENGINEERING_TELEMETRY=Restore) Package 'xunit.assert 2.4.2' from source 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json':
The author primary signature's signing certificate is not trusted by the trust provider.
```

**Comment by tarekgh** [comment]
@carlossanlop do you see this happened again or just one failure instance? looks not a real failure and something was happening during the run. 

CC @MattGal @dotnet/dnceng any idea what could be the problem?

**Comment by MattGal** [comment]
> @carlossanlop do you see this happened again or just one failure instance? looks not a real failure and something was happening during the run.
> 
> CC @MattGal dotnet/dceng any idea what could be the problem?

This is the second time, out of many thousands of instances, that I've seen this.  I think it's a very brief transient issue in certificate validation happening but without a repro it's quite difficult to investigate.

**Comment by tarekgh** [comment]
Thanks @MattGal. I am closing it as it looks like no action for now. We can look more if we get it again.

**Comment by carlossanlop** [comment]
FYI I just saw it again in a release/7.0 backport PR: https://github.com/dotnet/runtime/pull/75308

- Queue: Libraries Build windows arm64 Release
- Job results: https://dev.azure.com/dnceng-public/public/_build/results?buildId=9466&view=logs&j=da825fe5-de3c-5b40-c5a9-57db49ac53e0&t=12e813f5-e306-5337-95e5-a913cd66313d&l=75
```
src\libraries\Microsoft.Extensions.HostFactoryResolver\tests\Microsoft.Extensions.HostFactoryResolver.Tests.csproj(0,0): error NU3018: (NETCORE_ENGINEERING_TELEMETRY=Restore) Package 'xunit.extensibility.execution 2.4.2' from source 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json': The author primary signature's signing certificate is not trusted by the trust provider.
```
