### ISSUE TITLE
Unintuitive requirement to specify /unsafe with [LibraryImport] when use code does not use unsafe itself

### ISSUE THREAD

**Issue by martincostello** [dotnet/runtime#75051]
### Description

While trying out the `[LibraryImport]` source generator out with an existing project (https://github.com/martincostello/sqllocaldb/commit/f3d3b72422d4ed4878aedfb101608df1a2d118e5), I found the following unintuitive behaviour when trying to use it.

Despite the original or migrated user code not using any `unsafe` features directly, the generated code does, causing the compilation to fail, with one compiler warning for each instance of such usage.

While not an issue with the generator itself (although in some cases it emits the `unsafe` keyword where it isn't required), I think this highlights a bit of a rough edge to adoption that could benefit from a diagnostic of some sort (and mentioning in any final documentation for this feature) to help guide the user to the correct resolution for getting the project to compile successfully, particularly if they're not already familiar with unsafe code and interop.

For my own use case the research was ultimately redundant as actually I can just use the `NativeLibrary` class added in .NET 6 for all the P/Invoke calls anyway, so don't need to use the source generator. The below repro is based on the original code referenced above as it illustrates the point regardless of it not being the best way to actually call those particular Windows OS functions.

### Reproduction Steps

Clone [this repository](https://github.com/martincostello/LibraryImport-Repros) and run the following command:

```sh
dotnet build .\UnintuitiveUnsafeCode\UnintuitiveUnsafeCode.csproj
```

### Expected behavior

The source generator emits a diagnostic or other warning/error that informs the user that they need to use `<AllowUnsafeBlocks>true</AllowUnsafeBlocks>` in their project files when using `[LibraryImport]`.

### Actual behavior

The compilation fails with `CS0227` errors:

```sh
dotnet build .\UnintuitiveUnsafeCode\UnintuitiveUnsafeCode.csproj
MSBuild version 17.4.0-preview-22368-02+c8492483a for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
C:\Program Files\dotnet\sdk\7.0.100-preview.7.22377.5\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(219,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [C:\Coding\martincostello\LibraryImport-Repros\UnintuitiveUnsafeCode\UnintuitiveUnsafeCode.csproj]
C:\Coding\martincostello\LibraryImport-Repros\UnintuitiveUnsafeCode\NativeMethods.cs(3,31): error CS0227: Unsafe code may only appear if compiling with /unsafe [C:\Coding\martincostello\LibraryImport-Repros\UnintuitiveUnsafeCode\UnintuitiveUnsafeCode.csproj]
C:\Coding\martincostello\LibraryImport-Repros\UnintuitiveUnsafeCode\Microsoft.Interop.LibraryImportGenerator\Microsoft.Interop.LibraryImportGenerator\LibraryImports.g.cs(5,6): error CS0227: Unsafe code may only appear if compiling with /unsafe [C:\Coding\martincostello\LibraryImport-Repros\UnintuitiveUnsafeCode\UnintuitiveUnsafeCode.csproj]
C:\Coding\martincostello\LibraryImport-Repros\UnintuitiveUnsafeCode\Microsoft.Interop.LibraryImportGenerator\Microsoft.Interop.LibraryImportGenerator\LibraryImports.g.cs(29,6): error CS0227: Unsafe code may only appear if compiling with /unsafe [C:\Coding\martincostello\LibraryImport-Repros\UnintuitiveUnsafeCode\UnintuitiveUnsafeCode.csproj]
C:\Coding\martincostello\LibraryImport-Repros\UnintuitiveUnsafeCode\Microsoft.Interop.LibraryImportGenerator\Microsoft.Interop.LibraryImportGenerator\LibraryImports.g.cs(62,6): error CS0227: Unsafe code may only appear if compiling with /unsafe [C:\Coding\martincostello\LibraryImport-Repros\UnintuitiveUnsafeCode\UnintuitiveUnsafeCode.csproj]

Build FAILED.
```

### Regression?

No.

### Known Workarounds

The user researches how to specify `/unsafe` to the C# compiler and adds `<AllowUnsafeBlocks>true</AllowUnsafeBlocks>` to their project file(s) if they are unfamiliar with the relationship between the compiler switch and the MSBuild property related to it.

### Configuration

```sh
> dotnet --info
.NET SDK:
 Version:   7.0.100-preview.7.22377.5
 Commit:    ba310d9309

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-preview.7.22377.5\

Host:
  Version:      7.0.0-preview.7.22375.6
  Architecture: x64
  Commit:       eecb028078
```

**Comment by stephentoub** [comment]
The refactoring from DllImport to LibraryImport now supports automatically enabling AllowUnsafeBlocks:
<img width="604" alt="image" src="https://user-images.githubusercontent.com/2642209/188271838-beb48eb1-6c51-4efe-8a5f-70fdeaffcdd9.png">
and if you use LibraryImport without enabling AllowUnsafeBlocks, you will get a diagnostic specific to LibraryImport:
<img width="608" alt="image" src="https://user-images.githubusercontent.com/2642209/188271875-59d0d6ff-a831-438d-8e42-79277b5c7bfd.png">

**Comment by martincostello** [comment]
Nice - that's a much more informative.

**Comment by stephentoub** [comment]
Can this be closed? Is there something else you believe is needed?

**Comment by martincostello** [comment]
Yep, happy for this to be closed based on that.
