### ISSUE TITLE
native build, missing meta exception

### ISSUE THREAD

**Issue by MichealDanida** [dotnet/runtime#75053]
### Description

I'm trying to build application using ILComplier with IdentityServer4 package, when I run the application I got the following error when running the application after the build
..
'IdentityServer4.Configuration.DependencyInjection.Decorator<Microsoft.AspNetCore.Authentication.IAuthenticationService,Microsoft.AspNetCore.Authentication.AuthenticationService>' is missing metadata. For more information, please visit http://go.microsoft.com/fwlink/?LinkID=392859
..
using Net 7
used rd.xml
reference:
PackageReference Include="AspNetCore.Identity.MongoDbCore" Version="3.1.2" />
PackageReference Include="IdentityServer4" Version="4.1.2" />
PackageReference Include="IdentityServer4.AccessTokenValidation" Version="3.0.1" />
PackageReference Include="IdentityServer4.AspNetIdentity" Version="4.1.2" />
PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.2.0" />
PackageReference Include="Microsoft.AspNetCore.Authentication.Abstractions" Version="2.2.0" />
PackageReference Include="Microsoft.AspNetCore.Authentication.Core" Version="2.2.0" />
PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.8" />
PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="6.0.8" />
PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />

Could you help me?
[michealdanida@gmail.com](mailto:michealdanida@gmail.com)

### Reproduction Steps

using Net 7 and aot setting

### Expected behavior

identity4 run well in native build

### Actual behavior

'IdentityServer4.Configuration.DependencyInjection.Decorator<Microsoft.AspNetCore.Authentication.IAuthenticationService,Microsoft.AspNetCore.Authentication.AuthenticationService>' is missing metadata.

**Comment by jkotas** [comment]
Any chance you can share a small project that reproduces the problem?

**Comment by MichealDanida** [comment]
> Any chance you can share a small project that reproduces the problem?

please check github, just invited -> https://github.com/MichealDanida/Native-Build/invitations

**Comment by jkotas** [comment]
Try to apply this patch to your rd.xml: 
```diff
-               <Assembly Name="IdentityServer4" Dynamic="Required All" Serialize="Required All"/>
+               <Assembly Name="IdentityServer4" Dynamic="Required All" Serialize="Required All">
+                       <Type Name="IdentityServer4.Configuration.DependencyInjection.Decorator`2[[Microsoft.AspNetCore.Authentication.IAuthenticationService, Microsoft.AspNetCore.Authentication.Abstractions],[Microsoft.AspNetCore.Authentication.AuthenticationService, Microsoft.AspNetCore.Authentication.Core]]" Dynamic="Required All" />
+               </Assembly>
```

**Comment by MichealDanida** [comment]
thanks for your support, that bug is resolved.
Unfortunately, I still got an error -> No parameterless constructor defined for type 'System.ArgumentNullException'.
Reproduce:
1. build and run the firsttime -> ok,
2. Ctrl+C and run again -> throw that exception and can not run
3. delete all build folder and rebuild it again -> it run ok, once time

**Comment by jkotas** [comment]
What is the stacktrace of the latest crash?

**Comment by MichealDanida** [comment]
please check my-git, you can reproduce by run, stop and re-run

**Comment by jkotas** [comment]
This is the stacktrace of the crash:
```
webapi!S_P_CoreLib_System_ActivatorImplementation__CreateInstance_0+0x350
webapi!Microsoft_IdentityModel_Logging_Microsoft_IdentityModel_Logging_LogHelper__LogExceptionImpl<System___Canon>+0x21f
webapi!Microsoft_IdentityModel_Logging_Microsoft_IdentityModel_Logging_LogHelper__LogArgumentNullException+0x51
webapi!Microsoft_IdentityModel_Tokens_Microsoft_IdentityModel_Tokens_SigningCredentials__set_Algorithm+0x38
webapi!IdentityServer4_Microsoft_Extensions_DependencyInjection_IdentityServerBuilderExtensionsCrypto__AddDeveloperSigningCredential+0x93
webapi!webapi_Program___Main__+0x184
```
The problem is this library creates exceptions using reflection here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/59d1307a260829c0f8609a183a962aceaeffba89/src/Microsoft.IdentityModel.Logging/LogHelper.cs#L318

As always, you can workaround by adding the ArgumentNullException constructor to rdxml. Given the number of trimming and AOT warnings that are produced during compilation, I expect that you have a long way to go to find all places where the libraries referenced by the app use reflection. It will be a ton of work and very fragile.

I would recommend that you instead focus on working with maintainers of the libraries that you are trying to use to make them compatible with trimming and AOT (file issues requesting trimming and AOT in their repos, adding annotations, etc.). It is the proper way to fix the issues that you are seeing, and also much less fragile and more sustainable.

**Comment by MichealDanida** [comment]
thanks for your advise. 
We can close this topic.
Many Thanks jkotas
