### ISSUE TITLE
Migrating existing working P/Invoke from [DllImport] to [LibraryImport] causes exception at runtime

### ISSUE THREAD

**Issue by martincostello** [dotnet/runtime#75052]
### Description

While trying out the `[LibraryImport]` source generator out with an existing project (https://github.com/martincostello/sqllocaldb/commit/f3d3b72422d4ed4878aedfb101608df1a2d118e5) I ran into an unexpected exception at runtime when running the tests due to one of the P/Invoke functions failing to be found.

If a user is not aware of the `A` vs `W` underlying function declaration differences in the Windows OS functions, the difference in behaviour is surprising and may take some time for the user to discover the fix that needs to be made to their code.

I found in the case of the runtime itself, this has been handled by having the P/Invoke call map to `LoadLibraryExW` via the `EntryPoint` property.

https://github.com/dotnet/runtime/blob/c2ec86b1c552ac8a1749f9f98e012f707e325660/src/libraries/Common/src/Interop/Windows/Kernel32/Interop.LoadLibraryEx_IntPtr.cs#L14-L15

In this case, this feels like a rough-edge that users inexperienced with P/Invoke may come across when adopting this feature that would benefit from mentioning in any final documentation for this feature (I did a quick search but couldn't find anything specific to this topic).

For my own use case the research was ultimately redundant as actually I can just use the `NativeLibrary` class added in .NET 6 for all the P/Invoke calls anyway, so don't need to use the source generator. The below repro is based on the original code referenced above as it illustrates the point regardless of it not being the best way to actually call this particular Windows OS function.

### Reproduction Steps

Clone [this repository](https://github.com/martincostello/LibraryImport-Repros) and run the following command on Windows:

```sh
dotnet run --project .\FunctionNotFound\FunctionNotFound.csproj
```

### Expected behavior

The application prints the following to the console:

```sh
Loaded kernel32.dll
FreeLibrary() found
Unloaded kernel32.dll
```

### Actual behavior

An exception is printed to the console:

```sh
Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'LoadLibraryEx' in DLL 'kernel32.dll'.
   at NativeMethods.<LoadLibraryEx>g____PInvoke|2_0(Byte* lpFileName, IntPtr hFile, Int32 dwFlags)
   at NativeMethods.LoadLibraryEx(String lpFileName, IntPtr hFile, Int32 dwFlags) in C:\Coding\martincostello\LibraryImport-Repros\FunctionNotFound\Microsoft.Interop.LibraryImportGenerator\Microsoft.Interop.LibraryImportGenerator\LibraryImports.g.cs:line 79
   at Program.<Main>$(String[] args) in C:\Coding\martincostello\LibraryImport-Repros\FunctionNotFound\Program.cs:line 3
```

### Regression?

Only in the sense that a like-for-like function name no longer works.

### Known Workarounds

Either the user changes the code to add an `EntryPoint` value to the attribute pointing to either `LoadLibraryExA` or `LoadLibraryExW` to minimise any code churn, or renames the method to `LoadLibraryExA` or `LoadLibraryExW`.

```diff
- [LibraryImport("kernel32.dll", SetLastError = true, StringMarshalling = StringMarshalling.Utf8)]
+ [LibraryImport("kernel32.dll", EntryPoint = "LoadLibraryExA", SetLastError = true, StringMarshalling = StringMarshalling.Utf8)]
```

```diff
- [LibraryImport("kernel32.dll", SetLastError = true, StringMarshalling = StringMarshalling.Utf8)]
+ [LibraryImport("kernel32.dll", EntryPoint = "LoadLibraryExW", SetLastError = true, StringMarshalling = StringMarshalling.Utf16)]
```

### Configuration

```sh
> dotnet --info
.NET SDK:
 Version:   7.0.100-preview.7.22377.5
 Commit:    ba310d9309

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-preview.7.22377.5\

Host:
  Version:      7.0.0-preview.7.22375.6
  Architecture: x64
  Commit:       eecb028078
```

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky or @elinor-fung I thought our fixer handled this. Just looking to confirm. The OP doesn't mention the fixer specifically.

**Comment by martincostello** [comment]
FYI in this case I didn’t use the fixer (I also wasn’t aware there was one, unless it’s coming in RC1).

As I was specifically looking to use it based on reading about it in the recent perf-related post for 7.0, I wrote the code by hand.

I’d have probably had to do that anyway in my use case (if it wasn’t redundant due to `NativeLibrary`) even with the fixer due to multi-targeting.

**Comment by AaronRobinsonMSFT** [comment]
@martincostello We haven't pushed out all our docs, but the design docs do mention this https://github.com/dotnet/runtime/blob/main/docs/design/libraries/LibraryImportGenerator/Compatibility.md#semantic-changes-compared-to-dllimportattribute. Definitely not helpful for searching and will make sure we get our docs updated mentioning this.

**Comment by martincostello** [comment]
Thanks Aaron. Looks like this is the bit that would have been relevant in this case:

> [`ExactSpelling`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.dllimportattribute.exactspelling) will not be supported for `LibraryImportAttribute`. If `ExactSpelling` is used on an existing `DllImport`, the offered code-fix will provide users with additional options for using `A` or `W` suffixed variants depending on the provided `CharSet` so they can explicitly choose which spelling is correct for their scenario.

TIL, as I although I knew about the A and W variants, I didn't know _how_ it actually worked.

**Comment by elinor-fung** [comment]
The analyzer/fixer for converting `DllImport` to `LibraryImport` is only enabled by default in RC1. Most of the analyzer/fixer experience for p/invokes and custom marshalling source generation did not make Preview 7 and is only in RC1.

The one for converting to `LibraryImport` is `SYSLIB1054` and can be explicitly in an .editorconfig, but it had some known issues that would result in false positives / code breaks - @jkoritzinsky made some fixes in RC1 for them.

> will make sure we get our docs updated mentioning this.

We have an overview of p/invoke source generation that points this out now: https://docs.microsoft.com/dotnet/standard/native-interop/pinvoke-source-generation#differences-from-dllimport

**Comment by AaronRobinsonMSFT** [comment]
@elinor-fung Should we add explicit mention of the `A` and `W` mechanism?

**Comment by danmoseley** [comment]
@martincostello It would be great if you could pick up RC1 when it lands this week and try it out including the fixer. Let us know how it goes.
