### ISSUE TITLE
[Bug]: At runtime sometimes the wrong overload is selected.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/runtime#75069]
### Description

For some reason in my code (my code looks fine to me), however at runtime somehow it calls the wrong overload effectively making the implementationFactory not run.

In my code I do:

```cs
/// <summary>
/// Service Collection Extensions for Loading Remora Plugins.
/// </summary>
[PublicAPI]
public static class ServiceCollectionExtensions
{
    /// <summary>
    /// Loads plugin services into the service collection.
    /// </summary>
    /// <param name="serviceCollection">The service collection.</param>
    /// <param name="options">The options.</param>
    /// <returns>The same service collection for chaining.</returns>
    /// <remarks>
    /// This also watches the plugin assemblies for modifications and then reloads/unloads
    /// them automatically.
    /// </remarks>
    public static IServiceCollection AddPlugins(
        this IServiceCollection serviceCollection,
        PluginServiceOptions options)
    {
        var pluginService = new PluginService(options);
        pluginService.LoadPlugins(
            collection: serviceCollection);
        return serviceCollection
            .AddSingleton<PluginService>((serviceProvider) =>
            {
                pluginService.MigratePlugins(serviceProvider);
                return pluginService;
            })
            .AddFileSystemWatcher(options);
    }

    private static IServiceCollection AddFileSystemWatcher(
        this IServiceCollection serviceCollection,
        PluginServiceOptions options)
    {
        return serviceCollection
            .AddSingleton<FileSystemWatcher>(
                (serviceProvider) =>
                {
                    var pluginService = serviceProvider.GetRequiredService<PluginService>();
                    var fileSystemWatcher = new FileSystemWatcher(
                        PluginService.GetApplicationDirectory(),
                        options.Filter)
                    {
                        EnableRaisingEvents = true,
                        IncludeSubdirectories = true,
                        NotifyFilter = NotifyFilters.Attributes
                                       | NotifyFilters.CreationTime
                                       | NotifyFilters.DirectoryName
                                       | NotifyFilters.FileName
                                       | NotifyFilters.LastAccess
                                       | NotifyFilters.LastWrite
                                       | NotifyFilters.Security
                                       | NotifyFilters.Size,
                    };
                    fileSystemWatcher.Changed += (_, e) =>
                    {
                        // Unload old plugin (file changed).
                        pluginService.UnloadPlugin(Path.GetFileNameWithoutExtension(e.FullPath));

                        // Load new one.
                        pluginService.LoadPlugin(e.FullPath);
                    };
                    fileSystemWatcher.Created += (_, e) =>

                        // Load Plugin (file created).
                        pluginService.LoadPlugin(e.FullPath);
                    fileSystemWatcher.Deleted += (_, e) =>

                        // Unload plugin (file deleted).
                        pluginService.UnloadPlugin(Path.GetFileNameWithoutExtension(e.FullPath));
                    fileSystemWatcher.Renamed += (_, e) =>
                    {
                        // Unload old plugin (file renamed).
                        pluginService.UnloadPlugin(Path.GetFileNameWithoutExtension(e.OldFullPath));

                        // Load new one.
                        pluginService.LoadPlugin(e.FullPath);
                    };
                    return fileSystemWatcher;
                });
    }
}
```

However for some reason both ``serviceCollection.AddSingleton<T>(implementationFactory)`` calls get changed to ``serviceCollection.AddSingleton(Type serviceType)`` calls.

### Reproduction Steps

It might be because I am using 7.0.100 preview 7 SDK to compile, but it might not be that though.

### Expected behavior

For the implementationFactory code in both calls to be ran right on build of the service provider.

### Actual behavior

What happens is that at runtime, it calls the wrong overload.

### Regression?

I think it worked with the 6.0.4xx .NET SDK, just when I installed the 7.0.1xx SDK is when I started having issues.

### Known Workarounds

Currently I can only think about 1 thing: Uninstall the .NET 7 SDK temporarily (again).

### Configuration

Version of .NET when the code runs: 6.0.8 (used 7.0.1xx SDK to compile .NET 6 application)
OS: Windows 11 22H1 Dev Insiders
Arch: x64
Specific to configuration: Unknown
Blazor: Not using Blazor.

### Other information

When I go to look at the above code in ILSpy I see this:

```cs
using System;
using System.IO;
using Microsoft.Extensions.DependencyInjection;
using Remora.Plugins.Services;

public static class ServiceCollectionExtensions
{
	public static IServiceCollection AddPlugins(this IServiceCollection serviceCollection, PluginServiceOptions options)
	{
		PluginService pluginService = new PluginService(options);
		pluginService.LoadPlugins(serviceCollection);
		return AddFileSystemWatcher(serviceCollection.AddSingleton(delegate(IServiceProvider serviceProvider)
		{
			pluginService.MigratePlugins(serviceProvider);
			return pluginService;
		}), options);
	}

	private static IServiceCollection AddFileSystemWatcher(this IServiceCollection serviceCollection, PluginServiceOptions options)
	{
		PluginServiceOptions options2 = options;
		return serviceCollection.AddSingleton(delegate(IServiceProvider serviceProvider)
		{
			PluginService pluginService = serviceProvider.GetRequiredService<PluginService>();
			FileSystemWatcher fileSystemWatcher = new FileSystemWatcher(PluginService.GetApplicationDirectory(), options2.Filter)
			{
				EnableRaisingEvents = true,
				IncludeSubdirectories = true,
				NotifyFilter = (NotifyFilters.FileName | NotifyFilters.DirectoryName | NotifyFilters.Attributes | NotifyFilters.Size | NotifyFilters.LastWrite | NotifyFilters.LastAccess | NotifyFilters.CreationTime | NotifyFilters.Security)
			};
			fileSystemWatcher.Changed += delegate(object _, FileSystemEventArgs e)
			{
				pluginService.UnloadPlugin(Path.GetFileNameWithoutExtension(e.FullPath));
				pluginService.LoadPlugin(e.FullPath);
			};
			fileSystemWatcher.Created += delegate(object _, FileSystemEventArgs e)
			{
				pluginService.LoadPlugin(e.FullPath);
			};
			fileSystemWatcher.Deleted += delegate(object _, FileSystemEventArgs e)
			{
				pluginService.UnloadPlugin(Path.GetFileNameWithoutExtension(e.FullPath));
			};
			fileSystemWatcher.Renamed += delegate(object _, RenamedEventArgs e)
			{
				pluginService.UnloadPlugin(Path.GetFileNameWithoutExtension(e.OldFullPath));
				pluginService.LoadPlugin(e.FullPath);
			};
			return fileSystemWatcher;
		});
	}
}
```

Even the ILSpy code calls the right overload, however at runtime it does not for some reason. Perhaps the JIT is responsible?

**Comment by AraHaan** [comment]
cc: @dotnet/jit-contrib

**Comment by teo-tsirpanis** [comment]
The JIT calling a different method than the one specified in IL seems like a wild scenario, let's see what the DI owners think. In the meantime @AraHaan can you test your code with more cases (Debug vs Release, and various versions of .NET) and provide a small complete repro?

**Comment by AraHaan** [comment]
I will see what I can do then.

**Comment by AraHaan** [comment]
Yep, Debug and Release builds for .NET 6 both fail with the same issues. Let's see if ``net7.0``'s version of DI also fails.

**Comment by jkotas** [comment]
> However for some reason both serviceCollection.AddSingleton<T>(implementationFactory) calls get changed to serviceCollection.AddSingleton(Type serviceType) calls.

Are you sure that it is not just a JIT inlining the generic AddSingleton call? The generic AddSingleton is a thin wrapper around the non-generic AddSingleton.

**Comment by AraHaan** [comment]
7.0 also fails.

**Comment by AraHaan** [comment]
The repo (aka the discord bot I use and should be small, excluding code generated by ``dotnet ef scaffold``): [MyBot.zip](https://github.com/dotnet/runtime/files/9501677/MyBot.zip)

Note: SQL Database connection strings is to my local PC and cannot be accessed externally from our own private wifi and I even use Windows Authentication so there is no risk for any passwords being leaked. Also a little bit of effort to set up the database for the repo is needed as well as:
- A test discord bot application being made (api token)
- A test Discord server be made with some roles and a test emoji.
- Change the files under the Inserts folder in the SSDT project to the ID's of the Discord Server, roles, emoji, and the emoji's name.
- Change the connection strings in a few (3 files), and publish the database to your local test pc.

After that the application should be possible to be ran. I also included the sources to my local edits to Remora.Plugins which happen to seem to have an issue.

Also in the zip file under ``MyBot\Extensions\Hosting\BotServiceConfigurator.cs`` should contain some comments about where problems seems to happen.

**Comment by eerhardt** [comment]
Is there any way you can narrow the repo down further? There aren't many of us that can take the time to learn how to create a discord bot and test Discord server.

Eliminating all external dependencies is ideal, if possible.

**Comment by AraHaan** [comment]
I would have to see if I can reproduce it by commenting out the Discord stuff, but that might be possible as well.

**Comment by AraHaan** [comment]
This is odd but after I eliminated Remora.Plugins from my discord bot (the version that I added some changes to) the issue seems to have gone away. Perhaps it was something I did which caused it.

**Comment by tarekgh** [comment]
Closing per last reply. @AraHaan feel free to ping us again if you face any other problem you thinking we can help with.
