### ISSUE TITLE
The framework 'Microsoft.AspNetCore.App', version '6.0.0' (x64) was not found

### ISSUE THREAD

**Issue by aqweeva** [dotnet/runtime#75062]
Description: A .NET application failed.
Application: myservice.exe
Path: C:\xyz
Message: It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '6.0.0' was not found.
  - The following frameworks were found:
      3.1.20 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.4 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=win81-x64

**Comment by aqweeva** [comment]
NOTE: I've already installed AspNetCore.App 6.0.0 and verified it's install using 'dotnet --info'

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspN
etCore.App]
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspN
etCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore
.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.W
indowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by vitek-karas** [comment]
Note that it's complaining about `Microsoft.NETCore.App`, not `Microsoft.AspNetCore.App` (I know the names are a bit confusing).

How did you install the `AspNetCore.App` 6.0? All our installers should also include the required `NETCore.App` of a matching version.

**Comment by aqweeva** [comment]
sheesh! well now that you pointed it out, it's very obvious what I missed.
Installed: aspnetcore-runtime-6.0.0-win-x64.exe
Yeah, I'm confused where to get the correct version it's complaining about:  Microsoft.NETCore.App?

**Comment by vitek-karas** [comment]
You can get it here: https://dotnet.microsoft.com/en-us/download/dotnet/6.0
Look for the ".NET Runtime 6.0.8" section.

@joeloff any idea why the ASP.NET installer didn't also install runtime?

**Comment by vitek-karas** [comment]
Leaving open to try to get to the bottom of the installer behavior, but the product behavior is as expected.

**Comment by elinor-fung** [comment]
> Installed: aspnetcore-runtime-6.0.0-win-x64.exe

The ASP.NET runtime installer only includes the ASP.NET runtime, not .NET runtime, while the hosting bundle (for example, from the Hosting Bundle link on https://dotnet.microsoft.com/download/dotnet/6.0) includes both the ASP.NET and .NET runtime. I believe this is intentional - @wtgodbe can confirm.

**Comment by wtgodbe** [comment]
> The ASP.NET runtime installer only includes the ASP.NET runtime, not .NET runtime, while the hosting bundle (for example, from the Hosting Bundle link on https://dotnet.microsoft.com/download/dotnet/6.0) includes both the ASP.NET and .NET runtime. I believe this is intentional - @wtgodbe can confirm.

That's correct

**Comment by vitek-karas** [comment]
Thanks for confirmation - closing as resolved.
