### ISSUE TITLE
Cache Task.FromResult(String.Empty) or Task.FromResult("")

### ISSUE THREAD

**Issue by alex-jitbit** [dotnet/runtime#75077]
### Background and motivation

I review a lot of .NET code at many companies at my day job and see a lot of calls to `Task.FromResult("")`

TPL already offers some precompiled tasks cache for `bool`s, some `int`s and value type defaults here https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskCache.cs

I suggest to cache an "empty string" task too. This is a trivial change that will benefit a lot (less task allocations etc.).

Basically adding just one line to TaskCache.cs

`internal static readonly Task<string> s_emptyStringTask = CreateCacheableTask(result: "");`

And corresponding change in `Task.FromResult` and others.

I'm ready to submit a PR if the change is approved.

P.S. even within the ,.NET runtime there's a lot of methods that return a `Task<string>` (stream readers etc) that could benefit from this.

### API Proposal

Since it's not an external API but an internal performance optimization change, I'm leaving this empty

### API Usage

Since it's not an external API but an internal change, I'm leaving this empty

**Comment by stephentoub** [comment]
This would make Task.FromResult more expensive for every reference type. I don't think it's an appropriate tradeoff.

**Comment by MichalPetryka** [comment]
> This would make Task.FromResult more expensive for every reference type. I don't think it's an appropriate tradeoff.

Could be worked around with IsKnownConstant if the method's inlineable though.

**Comment by alex-jitbit** [comment]
OK, closing the suggestion then.
