### ISSUE TITLE
NET7 Int128, UInt128 - bugs in ToString 

### ISSUE THREAD

**Issue by c-ohle** [dotnet/runtime#75072]
## Wrong ToString results for Int128, UInt128 

Self explaining, in UInt128ToDecStr(UInt128) since CountDigits ignores the highword.
CountDigits and its variants should be rewritten as it is the most stupid and slowest implementation I ever saw. 

![image](https://user-images.githubusercontent.com/63112403/188355611-0a05ef84-356d-44cd-b0c4-a3707dc6b55e.png)

### Reproduction Steps

```csharp
var x = Int128.MaxValue / Int64.MaxValue; var ss = x.ToString(); // => "2"
var y = UInt128.MaxValue / UInt64.MaxValue; var sy = y.ToString(); // => "1"
```

### Expected behavior

```csharp
var x = Int128.MaxValue / Int64.MaxValue; var ss = x.ToString(); // => "18446744073709551618"
var y = UInt128.MaxValue / UInt64.MaxValue; var sy = y.ToString(); // => "18446744073709551617"
```

### Actual behavior

```csharp
var x = Int128.MaxValue / Int64.MaxValue; var ss = x.ToString(); // => "2"
var y = UInt128.MaxValue / UInt64.MaxValue; var sy = y.ToString(); // => "1"
```

**Comment by Wraith2** [comment]
> CountDigits and its variants should be rewritten as it is the most stupid and slowest implementation I ever saw.

This is inflamatory and unhelpful. Please learn to communicate more effectively with others.

**Comment by c-ohle** [comment]
@Wraith2 ok, can I help you?

**Comment by EgorBo** [comment]
I guess it's fixed with https://github.com/dotnet/runtime/pull/74501
