### ISSUE TITLE
There is room for improvement in the performance of the Stream.Write

### ISSUE THREAD

**Issue by wch1618** [dotnet/runtime#75076]
I found the performance of Stream.Write(byte[], 0, length)  is better than Stream.Write(byte[]). This is very strange. I found that Write(byte[]) automatically converts to Write(ReadOnlySpan<byte>), 
```
public virtual void Write(ReadOnlySpan<byte> buffer)
{
	byte[] array = ArrayPool<byte>.Shared.Rent(buffer.Length);
	try
	{
		buffer.CopyTo(array);
		Write(array, 0, buffer.Length);
	}
	finally
	{
		ArrayPool<byte>.Shared.Return(array);
	}
}
```
This is the reason for the problem.
 It was simple for Write(byte[] buffer)=>Write(buffer, 0, buffer.length), but for some reason it becamed Write(ReadOnlySpan<byte>).

**Comment by teo-tsirpanis** [comment]
There is no `Write(byte[])` method in the `Stream` class. The byte array gets casted to a `ReadOnlySpan<byte>` and `Write(ReadOnlySpan<byte>)` gets called.

`Write(ReadOnlySpan<byte>)` has this inefficient default implementation for compatibility reasons; when `Stream` got introduced spans did not exist and so we forward the new overload's default implementation to the old overload. This is not a problem if the stream you are using overrides the span-based methods, and all streams in .NET do that.

**Comment by wch1618** [comment]
If 'this inefficient default implementation for compatibility reasons', it is default so why my `public static void Write(this Stream s, byte[] buffer) => s.Write(buffer, 0, buffer.Length);` didn't work!

This is a performance problem. Don't deny it.

**Comment by teo-tsirpanis** [comment]
What do you mean by "it didn't work"? The extension method you wrote seems fine to me.

**Comment by wch1618** [comment]
This is not one example. Many system classes like BinaryWriter also use write (buffer) directly.

**Comment by wch1618** [comment]
Thank you for your reply.
You can do it in vs2022 net6.0. The compiler does not use the extension method I wrote, but calls Write(ReadOnlySpan<>)

**Comment by teo-tsirpanis** [comment]
Can you provide a simple repro? You can use https://sharplab.io.

**Comment by gfoidl** [comment]
@wch1618 can you show a benchmark that manifests the perf-problem?

Most (all?) stream derived types in .NET use a pattern like
```c#
public override void Write(ReadOnlySpan<byte> buffer)
{
    if (GetType != typeof(MyStream))
    {
        base.Write(buffer);     // -> Stream.Write(buffer)
        return;
    }

    // Specialized implementation for MyStream and sending the buffer as efficient as possible
}
```
So it doesn't matter if `MyStream.Write(ROS)` or `Stream.Write(ROS)` is used on the call-site.
The rest is as @teo-tsirpanis said.

**Comment by wch1618** [comment]
@teo-tsirpanis 
https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwHQEkDyA3MslAMyYzoDC6yA3sus5hVACzoCyAFAJR0kLdIyHCWAZQAuAJwCmAQwC26AM6zFKgLzoAYgEsANnOz4ADnIB2AdRn6pcngCInfYmPHoARgE8HAbQBdbwBXADMwuRl0HUs5AHdvPzl/OED3T2Z1eWVsW3tHL3DImTcmFgBfZCqkUjY4ADZKdGkcpQBRAA8pBnLmckxGzE58hx4pAAt9VRaNZTUAGiSA4KKIqL4tAD5VPLsxtZKl1CXDqOwAGSsAc0mypAqgA=

**Comment by gfoidl** [comment]
This is normal C# method-binding rules. Instance methode are favored over extension methods.
Cf. [Binding Extension Methods at Compile Time](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods#binding-extension-methods-at-compile-time).

Give it a different signature (e.g. different name) and C# will pick the extension-method.

**Comment by wch1618** [comment]
@gfoidl 
You right. Although this is a small problem, it does cause a redundant copy operation when Stream.Writes(byte[]).

**Comment by gfoidl** [comment]
> it does cause a redundant copy operation

It doesn't -- see https://github.com/dotnet/runtime/issues/75076#issuecomment-1236682728
The `FileStream` follow that pattern (in fact a more sophisticated one) so it has special and performant code to write the buffer to the (file-) stream.

Can you show a benchmark or perf-numbers to demonstrate that there's a perf-hit?
(again: there's no perf-hit in the common .NET stream-derived types, the base implementation in Stream.Write(ROS) is for compat (see above).)

**Comment by wch1618** [comment]
FileStream MemoryStream NetWorkStream all override Write(ReadOnlySpan<>), it won't has this problem. All that has the problem is user defined Stream to inherit the Stream, it can be solved it by [gfoidl](https://github.com/dotnet/runtime/issues/75076#issuecomment-1236682728). @gfoidl, Thanks .

@teo-tsirpanis, Thanks .
