### ISSUE TITLE
IConfiguration.GetValue<T>() is no longer defined in .NET 6

### ISSUE THREAD

**Issue by ygoe** [dotnet/runtime#75089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm upgrading an application from ASP.NET Core 3.1 to 6.0. I've read the migration documents completely but this issue wasn't mentioned anywhere. I'm not sure in which repository to report it, so I'll go with what I'm using.

This is the code that worked fine in 3.1:

```cs
IConfiguration configuration = ...;
string pin = configuration.GetValue<string>("internet:pin");
```

Now I get a compile error on the `GetValue<string>` part saying the method does not exist (CS1061). I see no similar methods and VS suggests me no options so I assume the configuration values can no longer be read. That would be a complete failure of the configuration system, which is a critical bug. It's rather unlikely that this happened but I cannot rule it out now. And my code no longer compiles.

What should I do to use the above code in .NET 6.0? Do I need to wait for a bugfix update that brings back that method? Is there an alternative that I just can't find? Should it be added to the list of incompatible migration changes?

### .NET Version

6.0.400 (probably means 6.0.8)

**Comment by davidfowl** [comment]
It's still there https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.configurationbinder.getvalue?view=dotnet-plat-ext-6.0#microsoft-extensions-configuration-configurationbinder-getvalue-1(microsoft-extensions-configuration-iconfiguration-system-string-0)

**Comment by ygoe** [comment]
@davidfowl Tell that Visual Studio, it probably hasn't read the documentation. I have that compile error anyway after upgrading the project (changing target framework and updating all NuGet packages). Is there anything else I have to do here that isn't in the migration docs?

**Comment by davidfowl** [comment]
It's possible there's some detail missing here. Let me see if I can help by asking more questions:

- What type of project is this? (class library, console app, web application)
- What package references does this project have? 
- What usings are included in the file with this code?

**Comment by ygoe** [comment]
This project in particular targets `net6.0`. It's a library that is used by an ASP.NET Core web application and a console app.

This project has these package references (not showing internal packages):

```xml
    <PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.8" />
    <PackageReference Include="Mono.Posix.NETStandard" Version="1.0.0" />
    <PackageReference Include="MQTTnet" Version="3.0.16" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Nito.AsyncEx" Version="5.1.2" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="6.0.6" />
    <PackageReference Include="SSH.NET" Version="2020.0.2" />
    <PackageReference Include="System.Device.Gpio" Version="2.1.0" />
    <PackageReference Include="System.IO.Ports" Version="6.0.0" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="6.0.0" />
    <PackageReference Include="System.Threading.Timer" Version="4.3.0" />
```

The file with the compile error has these usings (not showing internal namespaces):

```cs
using System;
using System.Net;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
```

**Comment by davidfowl** [comment]
Excellent, that helps alot! A couple of things:

-  `<PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="2.2.0" />` You shouldn't be using a 2.2.0 reference to ASP.NET Core when writing a library that targets ASP.NET Core 6.0 (or 3.1 for that matter). The migration guide explains how to move libraries that support ASP.NET Core >= 3.x https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-6.0&tabs=visual-studio#migrate-libraries-via-multi-targeting

- I would double check to see if you need some of those System.* packages. That System.Thread.Timer package I'm guessing isn't needed at all for example.

- The extension method you're looking for is in the package [**Microsoft.Extensions.Configuration.Binder**](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.Binder) package.

**Comment by ygoe** [comment]
Thanks a lot for the missing package. It's always hard to find stuff that needs extra packages before it's even discoverable, especially when it's moved into nowhere from one version to the other.

I'll look into the 2.2.0 package. I've never cared about it since there was no upgrade for it and it did the job. This is required for a part that does the view model input handling in the Web UI but also provides the processing methods (being configured in the web) for the separate console app. Multi-targeting sounds like it could help but is also more work.

The System.* packages for codepages and timer seem unnecessary now, but the build won't complete because of another migration blocker in EF (asked about that in the other repo), so I can't tell for sure yet.

**Comment by eerhardt** [comment]
https://www.nuget.org/packages/Microsoft.Extensions.Logging/3.1.28#dependencies-body-tab

`Microsoft.Extensions.Logging` in `3.1` depended on Microsoft.Extensions.Configuration.Binder directly. This was removed in 5.0 when these libraries were ported to dotnet/runtime.

To get your code to work again, you can add

```xml
<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="6.0.0" />
```

to your list above.
