### ISSUE TITLE
[NativeAOT] Implement thin locks

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#75108]
CoreClr is able to use object header bits for locking in trivial cases. That makes typical use of `lock` fairly cheap. NativeAOT does not have that and `lock(obj)` is always a "fat lock".

This is likely the reason for regressions in ConcurrentDictionary benchmarks.
(re: https://github.com/dotnet/runtime/issues/68891)

**Comment by tomcashman** [comment]
Where would be a starting point for this? I’d be interested in attempting an implementation to improve concurrency performance on our console ports.

**Comment by VSadov** [comment]
@tomcashman this is already in progress, sorry. 
There is already an implementation at a stage where I know it is correct (as in "passing all tests"), but I do not know yet if the perf is acceptable.

**Comment by tomcashman** [comment]
No worries I’ll keep an eye out for the PR and we can test performance on consoles 😄
