### ISSUE TITLE
Fails Reflection to System.Private.CoreLib at Generic method on IIS

### ISSUE THREAD

**Issue by maikami** [dotnet/runtime#75103]
### Description

Attempting to get MethodInfo with GenericMethod returned null.
It happened only in production environment.

- If type is System.DateTime, returned null
- fine in debug on VS2022
- If call succeeds even once, it will work properly after that

### Reproduction Steps

```
private MethodInfo? _method;
protected override void OnInitialized()
{
    // OK
    //_method = typeof(System.DateTime).GetMethod("Parse", BindingFlags.Static | BindingFlags.Public, new Type[] { typeof(string) });

    // null
    _method = getParseMethod<DateTime>();
}
private MethodInfo? getParseMethod<T>()
    => typeof(T).GetMethod("Parse", BindingFlags.Static | BindingFlags.Public, new Type[] { typeof(string) });
```

### Expected behavior

_method is assigned an instance.

### Actual behavior

_method is null.

### Known Workarounds

Call GetMethod() once first outside Generic method.

### Configuration

- Windows Server 2019
- IIS 10
- .NET 6.0.8
- Blazor WebAssembly

### Tried
- nuget cache clear
- cleand publish folder

_No response_

**Comment by jkotas** [comment]
The behavior that you are seeing is caused by trimming. See https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/configure-trimmer .

You may want to set `SuppressTrimAnalysisWarnings` to false in your project file to see all places that have potential problems with trimming in your app.
