### ISSUE TITLE
The IDataRecord interface does not have methods to get the value of an unsigned integer field.

### ISSUE THREAD

**Issue by PopeyeZhong** [dotnet/runtime#75116]
Are there plans to add `GetSByte(int i)`, `GetUInt16(int i)`, `GetUInt32(int i)`, and `GetUInt64(int i)` methods to the `IDataRecord` interface and its implementation classes?

Because now we can only use the `GetValue(int i)` method to process unsigned integer types in data access to MySQL, but this will lead to boxing/unboxing, which is not good for high-frequency data access.

**Comment by huoyaoyuan** [comment]
Adding members (without default implementation) to existing interfaces is a breaking change, which is not going to happen.

**Comment by roji** [comment]
@PopeyeZhong IDataRecord is generaly considered obsolete; when working against a database, [DbDataReader](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbdatareader) is typically used instead. That base class has a generic [`GetFieldValue<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbdatareader.getfieldvalue?view=net-7.0#system-data-common-dbdatareader-getfieldvalue-1(system-int32)) which in principle allows reading value types without boxing. However, many ADO.NET providers box internally anyway, so whether or not this actually helps depends on which provider you use.

I'm going to go ahead and close this as we're not going to be adding APIs to IDataRecord. But if you can provide more details on exactly how you're trying to use IDataRecord, I can provide further assistance.

**Comment by PopeyeZhong** [comment]
@roji Thanks a lot for your answer, now I understand why those methods were not added to the `IDataRecord` interface.

This problem is because of the problems we encounter when accessing some new databases such as ClickHouse/TDengine through some third-party data drivers, because they do not provide data reader inherited from `DbDataReader`, but directly implement `IDataReader` / `IDataRecord` interface general classes .

And thanks again for your answer. 谢谢~
