### ISSUE TITLE
[browser][mt] XmlSystemPathResolverTests.TestResolveInvalidPath timeout

### ISSUE THREAD

**Issue by simonrozsival** [dotnet/runtime#75129]
The `XmlReader.Create(invalidUri)` function blocks indefinitely and the test eventually timeouts. This failure seems to be the same as in #75123

Ref #74406

**Comment by pavelsavara** [comment]
@ilonatommy this is possibly working now, could you please test/enable ?

**Comment by ilonatommy** [comment]
It is not blocked and it's passing, closing.
