### ISSUE TITLE
SerialPort is not supported on Mac Catalyst

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#75120]
_From @trantamcdt92 on Tue, 06 Sep 2022 09:07:49 GMT_

### Steps to Reproduce

1. Create a SerialPort class
2. Configure the serial port settings
3. Open the serial port

### Expected Behavior
Can connect to device
### Actual Behavior
Exception "System.DllNotFoundException: libSystem.IO.Ports.Native" occurred
### Environment
Monterey, Visual Studio Preview

<details>
<summary>Version information</summary>

```
```

</details>

### Example Project (If Possible)

[Archive.zip](https://github.com/xamarin/xamarin-macios/files/9495140/Archive.zip)

_Copied from original issue xamarin/xamarin-macios#15874_

**Comment by rolfbjarne** [comment]
_From @rolfbjarne on Tue, 06 Sep 2022 09:48:57 GMT_

The SerialPort class is currently not supported on Mac Catalyst:

```
/Users/rolf/Downloads/Archive/MainPage.xaml.cs(16,9): warning CA1416: This call site is reachable on: 'MacCatalyst' 14.0 and later. 'SerialPort.PortName' is unsupported on: 'maccatalyst' all versions.
/Users/rolf/Downloads/Archive/MainPage.xaml.cs(14,9): warning CA1416: This call site is reachable on: 'MacCatalyst' 14.0 and later. 'SerialPort.DataBits' is unsupported on: 'maccatalyst' all versions.
/Users/rolf/Downloads/Archive/MainPage.xaml.cs(19,13): warning CA1416: This call site is reachable on: 'MacCatalyst' 14.0 and later. 'SerialPort.Open()' is unsupported on: 'maccatalyst' all versions.
/Users/rolf/Downloads/Archive/MainPage.xaml.cs(15,9): warning CA1416: This call site is reachable on: 'MacCatalyst' 14.0 and later. 'SerialPort.StopBits' is unsupported on: 'maccatalyst' all versions.
/Users/rolf/Downloads/Archive/MainPage.xaml.cs(13,9): warning CA1416: This call site is reachable on: 'MacCatalyst' 14.0 and later. 'SerialPort.Parity' is unsupported on: 'maccatalyst' all versions.
/Users/rolf/Downloads/Archive/MainPage.xaml.cs(12,9): warning CA1416: This call site is reachable on: 'MacCatalyst' 14.0 and later. 'SerialPort.BaudRate' is unsupported on: 'maccatalyst' all versions.
/Users/rolf/Downloads/Archive/MainPage.xaml.cs(13,23): warning CA1416: This call site is reachable on: 'MacCatalyst' 14.0 and later. 'Parity.None' is unsupported on: 'maccatalyst' all versions.
/Users/rolf/Downloads/Archive/MainPage.xaml.cs(15,25): warning CA1416: This call site is reachable on: 'MacCatalyst' 14.0 and later. 'StopBits.One' is unsupported on: 'maccatalyst' all versions.
/Users/rolf/Downloads/Archive/MainPage.xaml.cs(11,27): warning CA1416: This call site is reachable on: 'MacCatalyst' 14.0 and later. 'SerialPort' is unsupported on: 'maccatalyst' all versions.
```

Since this works for macOS apps, it seems to me that it just needs to be implemented for Mac Catalyst, so I'm moving this to dotnet/runtime where that code lives.

**Comment by trantamcdt92** [comment]
@rolfbjarne 
Are you planning to support SerialPort on MacOS? if you are, when it will be officially released?
I copied  libSystem.IO.Ports.Native.dylib from Visual Studio (Preview) to my application and could communicate with my device.
Is this safe to use it now?

**Comment by Therzok** [comment]
> I copied libSystem.IO.Ports.Native.dylib from Visual Studio (Preview)

VSMac pulls that from the System.IO.Ports nuget: https://www.nuget.org/packages/System.IO.Ports/7.0.0-preview.7.22375.6

**Comment by trantamcdt92** [comment]
@Therzok  yes, I know. I'd like to confirm whether using System.IO.Ports on MacOS is OK?

**Comment by liulunjnu** [comment]
> @rolfbjarne
> Are you planning to support SerialPort on MacOS? if you are, when it will be officially released?
> I copied libSystem.IO.Ports.Native.dylib from Visual Studio (Preview) to my application and could communicate with my device.
> Is this safe to use it now?

where the "libSystem.IO.Ports.Native.dylib" Copy to debug/release directory? why when I copied to my Macbook Pro M2 can't run?

**Comment by newt0ns** [comment]
> @rolfbjarne Are you planning to support SerialPort on MacOS? if you are, when it will be officially released? I copied libSystem.IO.Ports.Native.dylib from Visual Studio (Preview) to my application and could communicate with my device. Is this safe to use it now?

Where did you copy this from and to? I have copied it over from other working MacOS projects (from the runtime folders) and into the same folder as my Mac Catalyst app, but am met with the same System.DllNotFoundException error.

**Comment by trantamcdt92** [comment]
When you have installed Visual Studio Preview app in your Mac PC, the Visual Studio.app appears in the Desktop folder. You can see libSystem.IO.Ports.Native.dylib in the framework folder inside Visual Studio.app. Then copy this file to your executable folder.

**Comment by newt0ns** [comment]
We're currently on the normal installation of VS 2022 v17.5. No Preview versions here, just a normal up to date install.

I have libSystem.IO.Ports.Native.dylib from the same version of a MacOS app of our libraries that works fine, compiled just minutes ago. If I copy and place that in the same folder as our Mac Catalyst maui app it isn't loaded/found

**Comment by bxdint** [comment]
Hi, We are developing MAUI multi platform desktop focused app, app needs to connect to a serial port to read UART data, we are able to achieve this on Win but Mac side is not working. It becomes major blocker for our project. How soon are you going to support mac and android platforms? For any update regarding this issue please let us know, thanks.

**Comment by jenswet** [comment]
Hi

I am wondering if there is any progress with this issue?

I've included
```xml
<PackageReference Include="System.IO.Ports" Version="7.0.0" />
```
in my dependencies.

This has a dependency to https://www.nuget.org/packages/runtime.osx-arm64.runtime.native.System.IO.Ports/
This library contains `libSystem.IO.Ports.Native.dylib`.

If I copy the `libSystem.IO.Ports.Native.dylib` file into my debug/release directory everything works. But the build process doesn't copy it automatically.

So the whole ticket is not really about supporting MacCatalyst, but about fixing the build process to copy the required libraries, no?

Is this related to the efforts made in https://github.com/dotnet/runtime/issues/63187? I tried [8.0.0-preview.2.23128.3](https://www.nuget.org/packages/System.IO.Ports/8.0.0-preview.2.23128.3) without success.

Thanks

**Comment by krwq** [comment]
cc: @carlossanlop can you help us get this fixed?

**Comment by filipnavara** [comment]
FWIW the native lib would compile just fine on iOS/tvOS/MacCatalyst if it was enabled (https://github.com/dotnet/runtime/blob/e1afb22f6749da255d343c427ac3488ba0dcc842/src/native/libs/CMakeLists.txt#L145-L147). Then the NuGet packaging would need to be sorted out since it's OOB but that's relatively trivial copy & paste.

**Comment by nterreaux** [comment]
Any updates? It still doesn't work on my mac (Ventura 13.4) ... (Windows works perfectly)

**Comment by asi-evin** [comment]
I am also very interested in getting Serial Port working in MacCatalyst.

@jenswet 

> Hi
> 
> I am wondering if there is any progress with this issue?
> 
> I've included
> 
> ```
> <PackageReference Include="System.IO.Ports" Version="7.0.0" />
> ```
> 
> in my dependencies.
> 
> This has a dependency to https://www.nuget.org/packages/runtime.osx-arm64.runtime.native.System.IO.Ports/ This package contains `libSystem.IO.Ports.Native.dylib`.
> 
> If I copy the `libSystem.IO.Ports.Native.dylib` file into my debug/release directory everything works. But the build process doesn't copy it automatically.
> 
> So the whole ticket is not really about supporting MacCatalyst, but about fixing the build process to copy the required libraries, no?
> 
> Is this related to the efforts made in #63187? I tried [8.0.0-preview.2.23128.3](https://www.nuget.org/packages/System.IO.Ports/8.0.0-preview.2.23128.3) without success.
> 
> Thanks

I attempted your work around, copying both the SerialPort DLL and the native DYLIB files into the bin/debug. However, I get a "System.DllNotFoundException: libSystem.IO.Ports.Native" error. I tried with both the OSX-x64 and OSX-Arm64 native libraries to no avail. Are there any other steps I need to do?

**Comment by asi-evin** [comment]
@nterreaux No dice unfortunately. Still get the following message:

> Error while opening port: libSystem.IO.Ports.Native
System.DllNotFoundException: libSystem.IO.Ports.Native
   at Interop.Serial.SerialPortOpen(String name)
   at System.IO.Ports.SafeSerialDeviceHandle.Open(String portName)
   at System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
   at System.IO.Ports.SerialPort.Open()

**Comment by nterreaux** [comment]
@asi-evin Are your dependencies like mine?

<img width="271" alt="Screenshot 2023-07-07 at 18 41 18" src="https://github.com/dotnet/runtime/assets/52403645/e83b0c86-18c7-40e4-90d8-4394cb891963">

If not, I had to delete the output folder and restart the application... it didn't work the first time either, but now it does.

This solution is by far not optimal, but in my case it does the job.

**Comment by asi-evin** [comment]
Yeah, everything described is the same, but it still doesn't work. Thanks for the help, I'm just going to abandon this for now.

**Comment by scottkdavis** [comment]
Has anyone found a work around to the issue? It appears the DLL packaging been resolved, however now I am getting an explicit "Platform not supported" error message. It appears support is intentionally blocked. 

I have tried using SerialPortNet and SerialPortLibNetCore nuget packages, I couldn't get either to work on Maui Mac. I have an ORSSerialPort binding library from a Xamarin project that works fine in Xamarin, but have been unable to figure out how to get it ported to Maui. There is virtually no documentation or samples on binding libraries for Maui, let along Mac Maui. I've tried to get some native calls to work and only see Mac hard crashes with nothing helpful in the Apple crash report.

Anyone have any solutions? This is holding up our port from Xamarin to Maui. It is a project that communicates over USB Serial to control heavy equipment via modbus protocol.

**Comment by scottkdavis** [comment]
The documentation on the Nuget package needs to be updated to remove Mac. Should that be a separate bug? 
https://www.nuget.org/packages/System.IO.Ports/8.0.0-preview.7.23375.6#supportedframeworks-body-tab

It also lists support for Xamarin.Mac which is also not true.

**Comment by ronimizy** [comment]
@jeffhandley hi, any updates on this issue? it became a blocker for our project as well

**Comment by wfurt** [comment]
It should be similar to #63187 + change @filipnavara suggested. I can take a look next week.

**Comment by scottkdavis** [comment]
@wfurt @akoeplinger does the merged pull request for #86619, which fixes the serial port issues for Android and Linux include a fix for Mac Catalyst?

**Comment by akoeplinger** [comment]
No, Catalyst is a different story but as far as I know @wfurt is working on it.

**Comment by 00000vish** [comment]
> Hi
> 
> I am wondering if there is any progress with this issue?
> 
> I've included
> 
> ```
> <PackageReference Include="System.IO.Ports" Version="7.0.0" />
> ```
> 
> in my dependencies.
> 
> This has a dependency to https://www.nuget.org/packages/runtime.osx-arm64.runtime.native.System.IO.Ports/ This package contains `libSystem.IO.Ports.Native.dylib`.
> 
> If I copy the `libSystem.IO.Ports.Native.dylib` file into my debug/release directory everything works. But the build process doesn't copy it automatically.
> 
> So the whole ticket is not really about supporting MacCatalyst, but about fixing the build process to copy the required libraries, no?
> 
> Is this related to the efforts made in #63187? I tried [8.0.0-preview.2.23128.3](https://www.nuget.org/packages/System.IO.Ports/8.0.0-preview.2.23128.3) without success.
> 
> Thanks

@asi-evin @ronimizy 

This did not work for me either.  



Instead i got it working by copying the `libSystem.IO.Ports.Native.dylib` into `/bin/debug/*/*/MyApp.app/Content/MonoBundle` folder.

And make sure you have `com.apple.security.device.serial` in the app entitlement for it to work properly.

**Comment by akoeplinger** [comment]
If anyone wants to try the fix from #96492 then you can add the following nuget feed to nuget.config:

```xml
<add key="dotnet9" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json" />
```

and use version 9.0.0-alpha.1.24058.11 or higher of the package:

```xml
<PackageReference Include="System.IO.Ports" Version="9.0.0-alpha.1.24058.11" />
```

**Comment by wfurt** [comment]
Any luck with the updated package @00000vish?

**Comment by 00000vish** [comment]
> Any luck with the updated package @00000vish?

Yes, its working as expected!


Tested on Apple M1, Sonoma 14.1.1
