### ISSUE TITLE
[browser][MT] System.Xml.Tests.TC_SchemaSet_Add_URL.v4

### ISSUE THREAD

**Issue by simonrozsival** [dotnet/runtime#75123]
The test internally calls the `XmlDownloadManager` which makes a GET HTTP request to `http://bla/` and at that point the test execution gets stuck and eventually timeouts. I assume that this is caused by making a HTTP request on a non-browser thread but there might be something else going on.

Ref #74408

Stack:
```
-> using (Stream respStream = await client.GetStreamAsync(uri).ConfigureAwait(false))
-> return GetNonFileStreamAsync(uri, credentials, proxy).GetAwaiter().GetResult();
-> XmlDownloadManager.GetStream(absoluteUri, _credentials, _proxy);
-> stream = (Stream?)_laterInitParam.inputUriResolver.GetEntity(_laterInitParam.inputbaseUri, string.Empty, typeof(Stream));
-> FinishInitUriString();
-> XmlResolver tmpResolver = GetXmlResolver() ?? GetDefaultPermissiveResolver();
-> XmlReader reader = XmlReader.Create(schemaUri, _readerSettings);
-> sc.Add("xsdauthor", "http://Bla");
```

`GetNonFileStreamAsync` is called with a comment:
```
// This code should be changed if HttpClient ever gets real synchronous methods.  For now,
// we just use the asynchronous methods and block waiting for them to complete.
```
Expected exception form the hanging function: `[out of order message from the browser]: http://bla/ - Failed to load resource: net::ERR_NAME_NOT_RESOLVED`

**Comment by lewing** [comment]
@pavelsavara @lambdageek @kg this would be a good first issue for threaded js interop

**Comment by kg** [comment]
I wonder if unhandled exceptions in workers get forwarded to the console during tests?

**Comment by pavelsavara** [comment]
> I wonder if unhanded exceptions in workers get forwarded to the console during tests?

We improved it here https://github.com/dotnet/runtime/pull/74751

**Comment by pavelsavara** [comment]
@ilonatommy this is possibly working now, could you please test/enable ?

**Comment by ilonatommy** [comment]
It still hangs but ST works, I am changing the blocking condition in https://github.com/dotnet/runtime/pull/94558

**Comment by ilonatommy** [comment]
The problem is this operation: `.GetAwaiter().GetResult()`, not HTTP request alone. When we make a HTTP request directly from the test (converted to async), it passes with the expected exception. 
```
public async Task v4()
{
     try
     {
         var handler = new HttpClientHandler();
         string uri = "http://Bla";
         using (var client = new HttpClient(handler))
         {
              using (Stream respStream = await client.GetStreamAsync("http://Bla").ConfigureAwait(false)){} // Exception, correct!
         }
         XmlSchemaSet sc = new XmlSchemaSet();
         sc.Add("xsdauthor", "http://Bla");
     }
...
```
However, when we wrap the HTTP request in a helper async function and we use block-waiting for that function in the sync test, it hangs.
```
public void v4()
{
     try
     {
         AsyncHttpWrapper().GetAwaiter().GetResult(); // hangs
         XmlSchemaSet sc = new XmlSchemaSet();
         sc.Add("xsdauthor", "http://Bla");
     }
....
```

**Comment by pavelsavara** [comment]
I think `GetResult()` will (spin) block-wait the thread and the same threads needs event loop to resolve HTTP promise. This is nasty.
