### ISSUE TITLE
Add an analyzer warning of erroneous usage of MaxResponseHeadersLength

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#75137]
`HttpClientHandler` has a `MaxResponseHeadersLength` property that controls how much data we'll buffer for the response headers before giving up.

The value is in KB, not bytes, so it's easy for users to set it way too high by mistake (e.g. #73848).
The default is 64 KB which should be plenty for the vast majority of use cases, but users sometimes choose to set it even lower.

I propose that we add an analyzer that warns the user if they set `MaxResponseHeadersLength` to a constant higher than 128 (or 512 or 1024 - the exact number doesn't matter all that much).
In the rare case where the change was intentional, the user should suppress the warning.

```c#
new SocketsHttpHandler()
{
    MaxResponseHeadersLength = 16 * 1024 // Do you really mean 16 MB?
};
```

**Comment by karelz** [comment]
Triage: We believe it is going to help prevent mistakes by developers where they might thing the unit is Bytes, while we are multiplying it by 1024.

**Comment by bartonjs** [comment]
Looks good as proposed

Category: Usage
Level: Info

**Comment by amiru3f** [comment]
@MihaZupan @karelz 
Hey guys,

Is anyone going to write this analyzer?
I can pick it up, work on it, and submit a pull request (Btw, that's my first time writing an analyzer so maybe I would ask for some help)

**Comment by MihaZupan** [comment]
Hey @amiru3f, thanks, this one isn't currently assigned to anyone, so you're welcome to pick it up.
I'll assign the issue to you for now (no pressure, just to avoid others doing duplicate work).

https://github.com/dotnet/roslyn-analyzers/blob/main/GuidelinesForNewRules.md includes some basic information about what is expected for new analyzer rules.

**Comment by amiru3f** [comment]
Thanks @MihaZupan

**Comment by amiru3f** [comment]
Hey guys,

@MihaZupan Just a quick check, shall we support this as well?


```c#
new SocketsHttpHandler()
{
    MaxResponseHeadersLength = GetValue();
};

static int GetValue() =>  2 * 16 * 1024;
```
