### ISSUE TITLE
S.T.J. Source Generation serialization to stream fails for record types

### ISSUE THREAD

**Issue by pinkfloydx33** [dotnet/runtime#75139]
### Description

With System.Text.Json `7.0.0-preview.7.22375.6`, source generation fails to serialize to a `Stream` for `record` types with `JsonSourceGenerationMode.Serialization`. Serialization succeeds when serializing to a `string` or when changing the generation mode to `Metadata` or `Default`

> System.InvalidOperationException: 'TypeInfoResolver 'MyNamespace.FooContext' did not provide constructor parameter metadata for type 'MyNamespace.Foo'.'

I am not deserializing in my application, only serializing. I shouldn't need the constructor parameter metadata especially since everything works properly if serializing to a `string`

### Reproduction Steps

```csharp
public record Foo(int Baz, int Bar);

[JsonSerializable(typeof(Foo), GenerationMode = JsonSourceGenerationMode.Serialization)]
public partial class FooContext : JsonSerializerContext { }

var foo = new Foo(1, 2);

// succeeds
_ = JsonSerializer.Serialize(foo, FooContext.Default.Foo);

// fails
var ms = new MemoryStream();
JsonSerializer.Serialize(ms, foo, FooContext.Default.Foo);
```

### Expected behavior

Serializing to a `Stream` should succeed as it does when serializing to a `string`. Constructor parameter metadata should not be required as we are serializing *only*

### Actual behavior

Exception is thrown when serializing to `Stream`

> System.InvalidOperationException: 'TypeInfoResolver 'MyNamespace.FooContext' did not provide constructor parameter metadata for type 'MyNamespace.Foo'.'

### Regression?

Unknown

### Known Workarounds

- Serialize to a `string`
  -  not possible in my situation, as I am serializing to Http Response body
- Change serialization mode

### Configuration

- .NET 6.0 
- System.Text.Json `7.0.0-preview.7.22375.6`

**Comment by layomia** [comment]
Fast-path logic isn't used for async serialization. Due to the overload being used, the serializer assumes an async mode and wants to fall back to metadata-based serialization, hence the exception. I'm looking into whether we can use fast-path in this case since it is "sync-over-async". If not, we might just improve the exception message here.

**Comment by layomia** [comment]
Marking this as 8.0 given that there's a workaround for 7.0 (using a different generation mode).

**Comment by pinkfloydx33** [comment]
I'm actually using the async overload in my project. I figured they have the same bits since they both throw, so didn't bother including both in the repro.

Either way, makes sense. Thanks for looking.
