### ISSUE TITLE
PauseWriterThreshold and ResumeWriterThreshold options of PipeOptions not validated properly

### ISSUE THREAD

**Issue by alhimik45** [dotnet/runtime#75166]
### Description

It is possible to pass values of _ResumeWriterThreshold_ and _PauseWriterThreshold_ that causes program to hang. There is a check that disallows _ResumeWriterThreshold_ to be greater than _PauseWriterThreshold_ ([code](https://github.com/dotnet/runtime/blob/108d82802754e81e972079fc17c5bcab283031b6/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/PipeOptions.cs#L66)), but it doesn't work in case when _ResumeWriterThreshold_ left to default **-1** value and _PauseWriterThreshold_ passed explicitly and less than _DefaultResumeWriterThreshold_. In this case options contains _ResumeWriterThreshold_ that greater than _PauseWriterThreshold_ and writer resume never happens.

Similar situation come when passed _ResumeWriterThreshold_ equal to **0**. In this case [this](https://github.com/dotnet/runtime/blob/2fc910805404d4ae0c3123379a0f9571361a064b/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/Pipe.cs#L500) check is not true even if __unconsumedBytes_ is zero and writer is not resumed. Not sure is it lack of validation of wrong options value or bug in code that should work with zero value.

### Reproduction Steps

Here is small program that successfully completes with correct values and hangs forever in cases described above
```csharp
using System.Buffers;
using System.IO.Pipelines;
using System.Text;

//correct values for immediate backpressure
// var pipe = new Pipe(new PipeOptions(pauseWriterThreshold: 1, resumeWriterThreshold: 1));

//using default resumeWriterThreshold gives incorrect combination of values
var pipe = new Pipe(new PipeOptions(pauseWriterThreshold: 1, resumeWriterThreshold: -1));

//with zero resumeWriterThreshold program also hangs
var pipe = new Pipe(new PipeOptions(pauseWriterThreshold: 1, resumeWriterThreshold: 0));

var readTask = Task.Run(async () =>
{
    ReadResult read;
    do
    {
        read = await pipe.Reader.ReadAsync();
        Console.WriteLine($"Read {Encoding.UTF8.GetString(read.Buffer.ToArray())}");
        pipe.Reader.AdvanceTo(read.Buffer.End);
    } while (!read.IsCompleted);
});

var writeTask = Task.Run(async () =>
{
    await pipe.Writer.WriteAsync(Encoding.UTF8.GetBytes("qwerty1"));
    await Task.Delay(100);
    await pipe.Writer.WriteAsync(Encoding.UTF8.GetBytes("qwerty2"));
    await pipe.Writer.CompleteAsync();
});

await Task.WhenAll(readTask, writeTask);
```

### Expected behavior

PipeOptions constructor should throw ArgumentOutOfRangeException for such invalid values

### Actual behavior

PipeWriter not resumed after pause

**Comment by wtgodbe** [comment]
Thanks for the report - we think this is a good candidate for a community contribution, so applying the `help wanted` label

**Comment by cdbullard** [comment]
Hi all,
I have opened a PR that I believe should correct this behavior, please let me know if anything was missed or if any changes might be required.

**Comment by cdbullard** [comment]
Hello,
Just wanted to check in to see if anyone was able to review my PR, let me know if there are any questions. Thanks!
