### ISSUE TITLE
Codegen difference: Local vs IL Stack

### ISSUE THREAD

**Issue by deeprobin** [dotnet/runtime#75206]
[Sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYQYG8aHunGBLAHYYGAQQAUg4XwCUHLjwV8GAagC8DUgG55C7krUMU26rp7EA7Az7GFAXx28rQhgCEJzmXJOmGAN2xQDABWDOrWDgohBloRPFHqRrHcFsE2PPbeyfzOLBACuACu+DDiklayqgB8ohLSaVlOwrn5RTBuZZ5VrrXGtkA=)

```cs
public class C {
    public int A(int i) {
        i += 2;
        i += 4;
        return i;
    }
    public int B(int i) {
        var j = i;
        j += 2;
        j += 4;
        return j;
    }
    public int ConsumeA(int i) => A(i);
    public int ConsumeB(int i) => B(i);
}
```

According to @SingleAccretion, this is because Roslyn prefers to use the IL stack for locals instead of parameters.
So an optimization would make sense for this.

I would argue that there is a real-world case, as I have seen code where no new variable was created but the parameter was modified directly.

**Comment by SingleAccretion** [comment]
The optimization for locals is fairly simple and can be done in global morph (a bit like the SIMD assignment coalescence works right now). The perhaps more interesting case is making this work for indirect (aka field) stores:
```cs
*p += 4;
*p += 4;
=>
*p += 8;
```
This would have the benefit of avoiding relatively expensive memory operations, but would also require more thorough analysis to determine legality.

**Comment by AndyAyersMS** [comment]
Forward sub and or VN prop might also be places to consider.

Forward sub is currently blocked by the fact that these sorts of locals have many appearances, but if there are adjacent statements that both def the same local.....
