### ISSUE TITLE
[Docs] When can `AssemblyName.Version` be null

### ISSUE THREAD

**Issue by lonix1** [dotnet/runtime#75228]
The docs show that [`AssemblyName.Version`](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assemblyname.version?view=net-6.0) is nullable. So this could be null:
````cs
Assembly.GetExecutingAssembly().GetName().Version
````

Under what conditions could `Version` be null?

(Please also consider updating that page in the docs.)

I asked on [SO](https://stackoverflow.com/q/73642734/9971404) too. Thank you.

**Comment by stephentoub** [comment]
This will print true:
```C#
using System.Reflection;

var an = new AssemblyName("MyAssembly");
Console.WriteLine(an.Version is null);
```

**Comment by danmoseley** [comment]
@lonix1 You would be welcome to offer a PR to the docs repo to clarify if you wish. Click edit on the doc page. I'll close as this seems answered.
