### ISSUE TITLE
HostingEnvironmentExtensions.IsDevelopment() etc. seem more strict than necessary

### ISSUE THREAD

**Issue by andrau** [dotnet/runtime#75256]
In our project, we have different development configuration flavors which we select by setting the environment name to Development.Flavor and naming the config files accordingly so we can load $"appsettings.{environmentName}, e.g appsettings.Development.Vanilla.json, appsettings.Development.Chocolate.json

This together with run configurations for VS has proven quite useful

In addition we make use of env.IsDevelopement() in some parts of the code to toggle special behavior. However, this falls short because HostingEnvironmentExtensions.IsDevelopment() (and the underlying hostingEnvironment.IsEnvironment(environmentName)) use an exact match so it yields false for our "flavored" environment names.

This seems more strict than necessary: a test using StartsWith() in IsEnvironment() would offer more flexibility without any obvious sacrifice in accuracy. After all any Environment name starting with "Development" should be considered to be a dev environment, no? And if we are paranoid about mismatches, we could add a "." in the check, i.e. only accept anything starting with "Development."

This seems like a trivial improvement that I would glad to see implemented

**Comment by andrau** [comment]
seems to fit area-Extensions-Configuration

**Comment by pinkfloydx33** [comment]
We have a similar case, although our additional environments don't fall into the same naming pattern (rather they *end* with "Development"). We also have a QA environment that we classify similarly--sometimes.

We ended up writing our own extension methods to cover 
`IsAnyDevelopment` and `IsDevelopmentOrQa` which works, although we've had to override/replace spots in the runtime/asp that default to `IsDevelopment` to use our custom method instead. It unfortunately requires knowing when `IsDevelopment` gets used and ensuring we override the defaults (ie. User secrets  for Dev-only and Asp exception pages for dev/qa). Thanks to open-source that's easy enough to determine, albeit with a little leg work.

Point being I don't think there's a one size fits all rule that can be applied. It's easy enough to write your own extension methods. I'm not sure there's value here.

**Comment by andrau** [comment]
Well, at the very least there is no harm in catering at least to some of those special needs by being less strict since there seems to be no downside/risk. Also, it seems your case could also be covered by doing something like 

return environment.Equals("Development") || environment.StartsWith("Development.") || environment.EndsWith(".Development")

Those who completely break from the convention by not using "Development" in their environment at all still can go their own work with a fork, but it seems the extra work for creating building and keeping that up to date is rather high. Instead of this, I would rather stick to "Development" as the base environment name and use an additional env-variable for the "flavor"...

**Comment by eerhardt** [comment]
See also https://github.com/dotnet/runtime/issues/36376, which is very related to this (almost a duplicate).

**Comment by tarekgh** [comment]
Closing the issue. If there is a demand for that we can reconsider it in the future.
