### ISSUE TITLE
Android app size regression in .NET 7 RC 1

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/runtime#75267]
### Description

We noticed this here: https://github.com/xamarin/xamarin-android/pull/7303

It has changes in both linker and runtime:
* https://github.com/dotnet/linker/compare/6252a21...313671b
* https://github.com/dotnet/runtime/compare/f52d8c5...516f061

If you `dotnet new android` and then `dotnet build -c Release -r android-arm64`, then new assemblies are now present:

```
System.Diagnostics.Tracing.dll		 2084 bytes
System.Runtime.InteropServices.dll	 3741 bytes
System.Threading.dll			 5480 bytes
System.Threading.Thread.dll		 1974 bytes
System.Threading.ThreadPool.dll		 2003 bytes
System.Transactions.Local.dll		62998 bytes
```

The overall app size change of a non-AOT build is:
```diff
--"PackageSize": 2664509
++"PackageSize": 2820744
```
This is likely a lot worse on iOS and AOT builds.

### Reproduction Steps

`dotnet new android` with .NET 7 RC 1, and then `dotnet build -c Release -r android-arm64`

### Expected behavior

"hello world" Android apps app size hopefully would get smaller each .NET release.

### Actual behavior

"hello world" Android apps now include `System.Transactions.Local.dll` and friends.

### Regression?

Yes, seems to have been fine in earlier .NET 7 builds (and .NET 6).

### Configuration

.NET SDK 7.0.100-rc.1.22423.7
.NET Runtime 7.0.0-rc.1.22421.12

### Other information

Here is an example of linker output:

[linked.zip](https://github.com/dotnet/runtime/files/9527328/linked.zip)

**Comment by danmoseley** [comment]
@eerhardt

**Comment by stephentoub** [comment]
Fixed by https://github.com/dotnet/runtime/pull/74828?

**Comment by jonathanpeppers** [comment]
This appears to be fixed in .NET 7 RC 2, as seen in https://github.com/xamarin/xamarin-android/pull/7391
