### ISSUE TITLE
What is the intended way to ship System.Memory.dll for use in a .NET Framework app?

### ISSUE THREAD

**Issue by chrarnoldus** [dotnet/runtime#75280]
We maintain an application that targets .NET Framework 4.6.2. We would like to use a third-party library that is available on NuGet, let's call it X. X lists .NET Framework 4.5 as a supported target framework. X also has a dependency on System.Memory. As far as I can tell, this now requires us to ship the following DLLs with our application, to be deployed next to the EXE, which are the direct and indirect dependencies of X:

* System.Buffers.dll
* System.Memory.dll
* System.Numerics.Vectors.dll
* System.Runtime.CompilerServices.Unsafe.dll

My superiors are uncomfortable with shipping DLLs that have System in the name with our application and they prefer a redistributable installer instead. I am not aware of such an installer existing.

I would like an authoritative answer on the following question:

What is the intended way to ship System.Memory.dll and related DLLs for use in a .NET Framework application?

**Comment by Clockwork-Muse** [comment]
>  ...to be deployed next to the EXE...

> My superiors are uncomfortable with shipping DLLs that have System in the name with our application and they prefer a redistributable installer instead.

This implies that what they _want_ is to install/use `System.Whatever` DLLs as part of the actual .NET Framework install, not as part of the application install.... so it sounds like you have a conflict of intentions here.  You might try asking them if renaming the DLLs would solve the issue.

Fundamentally, DLL name/package name/code namespace is not a security boundary.  It makes no difference what the any of the things are named (other than managing conflicts); it's completely legal (although often discouraged) for third parties to write `System.Anything` packages/DLLs/code namespaces.

**Comment by jkotas** [comment]
> What is the intended way to ship System.Memory.dll and related DLLs for use in a .NET Framework application?

Next to the application .EXE.
