### ISSUE TITLE
All build legs need to move off macOS 10.15

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#75292]
There's currently a brownout and the image is scheduled to be decommissioned by 9.30; we need to patch all pertinent servicing branches.

- [x] Main
- [x] 7.0
- [x] 6.0
- [ ] 3.1 (corefx + coreclr + core-setup)

cc: @dotnet/runtime-infra

**Comment by steveisok** [comment]
https://github.com/dotnet/runtime/pull/75294 is for 6.0

**Comment by akoeplinger** [comment]
This is done.
