### ISSUE TITLE
System.Tests.AppDomainTests.MonitoringIsEnabled - Assert.InRange - on NativeAOT arm64

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#75302]
Affected test:
- **MonitoringIsEnabled** - `System.Tests.AppDomainTests.MonitoringIsEnabled`

Frequency:
- 9/8 - **21x** occurrences in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime-extra-platforms+name%3A%22system.tests.appdomaintests.monitoringisenabled%22) on Runfo -- first occurrence on **8/30** in run [1977040](https://runfo.azurewebsites.net/view/build/?number=1977040) ([Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-5792f1de16bf410799/System.Runtime.Extensions.Tests/1/console.32a94eda.log?%3Fhelixlogtype%3Dresult))

Output:
```
[FAIL] System.Tests.AppDomainTests.MonitoringIsEnabled
Assert.InRange() Failure
Range:  (1234567 - 9223372036854775807)
Actual: 0
   at System.Tests.AppDomainTests.MonitoringIsEnabled() + 0xc4
   at System.Runtime.Extensions.Tests!<BaseAddress>+0x961d14
   at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0xd8
```

**Comment by jkotas** [comment]
Likely the same underlying problem as https://github.com/dotnet/runtime/issues/74902

**Comment by jkotas** [comment]
Test disabled by https://github.com/dotnet/runtime/pull/75306
