### ISSUE TITLE
`[System.Console]::ReadKey()` returns escape sequence characters when pressing arrow keys in PowerShell on Linux

### ISSUE THREAD

**Issue by daxian-dbw** [dotnet/runtime#75305]
### Description

This is with PowerShell 7.3.0-preview.7, which runs on top of .NET 7-preview.7.

Running `[System.Console]::ReadKey()` in PowerShell, and then press <kbd>UpArrow</kbd>, it returns the escape sequences character by character -- `Escape` and then `A`.
It's the same to other arrow keys: <kbd>DownArrow</kbd>, <kbd>LeftArrow</kbd>, <kbd>RightArrow</kbd>

However, when using `Console.ReadKey` in an EXE built against .NET 7-preview.7, it returns `UpArrow` (and other arraow keys) as expected. **Any ideas about what may cause this difference?**

Related PowerShell issue: https://github.com/PowerShell/PowerShell/issues/16443

### Reproduction Steps

1. Run PowerShell 7.3.0-preview.3, which runs on top of .NET 7-preview.7.
2. Run `[System.Console]::ReadKey()`
3. Press <kbd>UpArrow</kbd>

### Expected behavior

`[System.Console]::ReadKey()` returns a `ConsoleKeyInfo` with those values: `KeyChar: 0, Key: UpArrow, Modifier: 0`

### Actual behavior

`[System.Console]::ReadKey()` returns a `ConsoleKeyInfo` with the `Escape` key, and then a second `ReadKey` returns `A`

![image](https://user-images.githubusercontent.com/127450/189208485-76c84e15-4482-466e-900f-71671fd06282.png)

However, when using `Console.ReadKey` from an EXE that's built against .NET 7-preview.7, it works as expected:

![image](https://user-images.githubusercontent.com/127450/189220167-e2ae8796-232a-4673-a1f5-a244d5c7b96b.png)

### Regression?

Not as far as I know. I observe the same behavior in .NET 6.

### Configuration

> Which version of .NET is the code running on?
.NET 7-preview.7

> What OS and version, and what distro if applicable?
Ubuntu 18.04

> What is the architecture (x64, x86, ARM, ARM64)?
x64

**Comment by daxian-dbw** [comment]
Is this also addressed by https://github.com/dotnet/runtime/commit/f1de614c74589fe8f682dda39889d189f2522504?

**Comment by adamsitnik** [comment]
> Any ideas about what may cause this difference?

Is there any chance PowerShell could set `TERM` env variable? 

> Is this also addressed by https://github.com/dotnet/runtime/commit/f1de614c74589fe8f682dda39889d189f2522504?

I am not 100% sure as I don't know what caused the difference in first place. Could you please test it with RC1?

**Comment by daxian-dbw** [comment]
PowerShell doesn't set `TERM` env variable, it just derives that env variable:
```
PS:6> $env:TERM
xterm-256color
```

**Comment by adamsitnik** [comment]
@daxian-dbw RC1 was shipped yesterday, could you please check if it works as expected now?

**Comment by daxian-dbw** [comment]
Thanks @adamsitnik, we are preparing a release targeting RC1. Will verify this soon.

**Comment by daxian-dbw** [comment]
This is fixed with the .NET 7-RC1 release ❤️ Thanks @adamsitnik!
But I'm still curious about why it only doesn't work when running in PowerShell directly for the previous .NET versions ... what a mystery 😵‍💫 

![image](https://user-images.githubusercontent.com/127450/190515493-4acf1993-b1ad-4a61-834c-a2838f337d9f.png)

**Comment by adamsitnik** [comment]
> But I'm still curious about why it only doesn't work when running in PowerShell directly for the previous .NET versions ... what a mystery 

Based on https://github.com/dotnet/runtime/issues/75289#issuecomment-1248741119 it looks that I'll have to solve this mystery anyway ;)

**Comment by adamsitnik** [comment]
@daxian-dbw thanks for testing it and letting me know!
