### ISSUE TITLE
Calling GetControllingUnknown () generates an assert

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#75312]
Reported by @ocallesp. 

[severity:I’m unable to use this version]

I have a project dll ATL (COM).

The project has enabled .NET Core Runtime Support (/ clr: netcore) (NET 6.0).

In this project when the GetControllingUnknown() function is called we have an assert.

![image](https://user-images.githubusercontent.com/63486087/189236271-85da19cf-5acc-4c5c-b3a2-074118c3a7f5.png)

IUnknown* _GetRawUnknown() throw() 

{ ATLASSERT(_GetEntries()[0].pFunc == _ATL_SIMPLEMAPENTRY); return (IUnknown*)((INT_PTR)this+_GetEntries()->dw); } \

**Comment by JulieLeeMSFT** [comment]
CC @EgorBo, @dotnet/jit-contrib, @AaronRobinsonMSFT, @jeffschwMSFT, @ocallesp.

**Comment by JulieLeeMSFT** [comment]
@kunalspathak please help debug this issue with EgorBo.

**Comment by kunalspathak** [comment]
@ocallesp - can you share some more details, repro steps, environment, etc?
