### ISSUE TITLE
Memory leaking with Serializing JSON on Large Objects

### ISSUE THREAD

**Issue by AhmedZero** [dotnet/runtime#75314]
now there is Memory leaks with `JsonSerializer.Serialize` when i convert list of objects, the memory increases from 950 MB to 2.5 GB.
```C#
var list = JsonSerializer.Serialize(MainWindowViewModel.Tabs, options);
File.WriteAllText(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "products.json"), list);
GC.Collect();

```
before  `JsonSerializer.Serialize` 
![image](https://user-images.githubusercontent.com/26312527/189248348-3169e369-1f6d-4da2-a437-4ec5808f1cb1.png)
after  `JsonSerializer.Serialize` 
![image](https://user-images.githubusercontent.com/26312527/189248418-ed92ff4e-5ba4-4d45-9130-f2584f4e749c.png)

i test with .NET 7.0.0-rc.2.22451.11
my OS is Windows 11
the app is X86

**Comment by stephentoub** [comment]
Is it actually a leak? Has the GC run? If you look at the objects still alive, where are they rooted?

My guess is these are large arrays in the ArrayPool, and there simply hasn't been enough memory pressure and/or GCs to cause it to release them all.

**Comment by AhmedZero** [comment]
I don't know but I build the app again with x64 and my PC rams 16GB and the same problem.
![IMG_20220909_040616.jpg](https://user-images.githubusercontent.com/26312527/189257088-cc16adc7-f4ed-44c1-8c04-f62391fe898d.jpg)

**Comment by stephentoub** [comment]
Working set doesn't mean there's a leak.  In a managed environment, the GC gets to decide when to decommit memory.

I'd recommend taking a memory profile:
https://docs.microsoft.com/en-us/visualstudio/profiling/memory-usage-without-debugging2?view=vs-2022
and in the resulting snapshot looking to see what objects are taking up all the space and what their "roots" are.  That will tell you if there's actually a leak or not.

**Comment by eiriktsarpalis** [comment]
Couple of questions:

* Is this a regression from .NET 6?
* Can you share a console app containing a minimal reproduction of the issue?

Thanks!

**Comment by AhmedZero** [comment]
1- No, it's .NET 7.0.0-rc.2.22451.11
2- anyway it's Avalonia, not console, and I think the problem is caused by serialization of the class inherited from `ReactiveObject`. and it has a list containing more than 100,000 Objects.
anyway, I'll specify which cause the memory leak in JsonSerializer.Serialize by using dotmemory.
`public sealed class ProductInformations : ReactiveObject`

**Comment by AhmedZero** [comment]
![IMG_20220910_012655.jpg](https://user-images.githubusercontent.com/26312527/189458557-a5832fa2-eb51-4988-894d-a82fe62ec28d.jpg)

**Comment by stephentoub** [comment]
The title of that view is missing, but it appears to be the stack that allocated the objects. What's more interesting is the path to root that's keeping the objects alive.

**Comment by AhmedZero** [comment]
Is it related to the same problem or not?
https://github.com/dotnet/runtime/issues/66102

**Comment by AhmedZero** [comment]
Do you need any more information???

**Comment by stephentoub** [comment]
> Is it related to the same problem or not?

I'm not yet convinced there's a problem.

> Do you need any more information???

Yes, what I asked for above:
"in the resulting snapshot looking to see what objects are taking up all the space and what their "roots" are"
"What's more interesting is the path to root that's keeping the objects alive."

Alternatively if you have a dump of the process to share that's fine, too.

**Comment by AhmedZero** [comment]
![IMG_20220910_025841.jpg](https://user-images.githubusercontent.com/26312527/189462530-f109d7b9-d917-4ebe-8e12-284c496636a6.jpg)
There is anyway to serialize only specific fields only?

**Comment by davidfowl** [comment]
https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-ignore-properties?pivots=dotnet-7-0#ignore-individual-properties

**Comment by AhmedZero** [comment]
![IMG_20220910_025841.jpg](https://user-images.githubusercontent.com/26312527/189462530-f109d7b9-d917-4ebe-8e12-284c496636a6.jpg)
There is anyway to serialize only specific fields only?
I known that but I need ignore all and add attribute like [Jsonspecific] to serialize that.

**Comment by davidfowl** [comment]
Maybe you should [write a custom JSON converter](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to?pivots=dotnet-7-0). It looks like we don't have any memory leak here though, so the issue is resolve right?

**Comment by AhmedZero** [comment]
But why duplicates when I serialize it and still alive even I don't use it or create it?

**Comment by AhmedZero** [comment]
I will test serialize with Newtonsoft JSON.NET if the same case I'll use custom converter.

**Comment by AhmedZero** [comment]
I use Newtonsoft JSON.NET
before `Newtonsoft.Json.JsonConvert.SerializeObject`
![image](https://user-images.githubusercontent.com/26312527/189482910-40cdd5a6-0387-4418-aa5b-cc5056a28ef9.png)
after `Newtonsoft.Json.JsonConvert.SerializeObject`
![image](https://user-images.githubusercontent.com/26312527/189482960-a4a5096f-eaf7-4885-8145-bb684e936fb7.png)

**Comment by AhmedZero** [comment]
comparison before and after using System.Text.Json serialize
![image](https://user-images.githubusercontent.com/26312527/189483118-0ccb439a-a58d-44f1-86f6-4055006f808f.png)

**Comment by davidfowl** [comment]
The serializer uses pooled memory so it’s allocated and reused for future calls. As for your specific situation, I’m still not clear on what the leak is… Maybe providing a runnable sample would be the next step here.

**Comment by stephentoub** [comment]
>> comparison before and after using System.Text.Json serialize

> The serializer uses pooled memory so it’s allocated and reused for future calls

Right, this is what I was expecting we'd see. 
"My guess is these are large arrays in the ArrayPool, and there simply hasn't been enough memory pressure and/or GCs to cause it to release them all."

**Comment by AhmedZero** [comment]
why newtonsoft  reverse 400 MB and system.text.json reverses 1.6 GB? After serializing

**Comment by AhmedZero** [comment]
https://github.com/AhmedZero/ReactiveObjectSerializeTest
that's my sample.

**Comment by davidfowl** [comment]
Most of the memory seems to be coming from the fact that you're deriving from this ReactiveObject type. I'm not sure if that's just a convenience but the entire object graph is being serialized that that's not what you want. There's no leak here. 

I'm pretty sure the difference between this an JSON.NET is the fact that it respects `IgnoreDataMemberAttribute` which is used by ReactiveUI to ignore specific members.

**Comment by AhmedZero** [comment]
> 1- No, it's .NET 7.0.0-rc.2.22451.11
> 2- anyway it's Avalonia, not console, and I think the problem is caused by serialization of the class inherited from `ReactiveObject`. and it has a list containing more than 100,000 Objects.
> anyway, I'll specify which cause the memory leak in JsonSerializer.Serialize by using dotmemory.
> `public sealed class ProductInformations : ReactiveObject`

I told you that.
it's problem from ReactiveObject. and I want to ignore them.

**Comment by davidfowl** [comment]
I told you how to ignore them, but you don't own ReactiveObject so the attributes won't do you any good. Write a custom JSON converter and be done with it 😄.

**Comment by AhmedZero** [comment]
I already write a custom JSON converter, but I hope to support it soon like JSON.NET
`[JsonObject(MemberSerialization.OptIn)]`

**Comment by davidfowl** [comment]
Maybe there's some clever way to use [JsonInclude](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonincludeattribute?view=net-6.0) that I'm not aware of to solve this problem.

cc @eiriktsarpalis

**Comment by eiriktsarpalis** [comment]
There's not much that can be done with base types in third-party libraries using attributes. Starting with .NET 7 it should be possible to influence what properties do get serialized using [contract customization](https://github.com/dotnet/runtime/issues/63686), which removes the need (and pitfalls) of writing a custom converter. Here's what such a contract resolver could look like: (NB this hasn't been tested)
```C#
var options = new JsonSerializerOptions
{
      TypeInfoResolver = new DefaultJsonTypeInfoResolver()
      {
            Modifiers =
            {
                  static jsonTypeInfo =>
                  {
                        if (typeof(ReactiveObject).IsAssignableFrom(jsonTypeInfo.Type))
                        {
                              foreach (JsonPropertyInfo property in jsonTypeInfo.Properties)
                              {
                                     if (property.PropertyType.IsGenericType && property.PropertyType.GetGenericTypeDefinition() == typeof(IObservable<>))
                                     {
                                          jsonTypeInfo.Properties.Remove(property);
                                     }
                              }
                        }
                  }
            }
      }
}
```

**Comment by AhmedZero** [comment]
it's better than JSON.NET now.
