### ISSUE TITLE
[API Proposal]: MemoryExtensions.Replace(Span<T>, T, T)

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#75322]
### Background and motivation

`string.Replace(char, char)` is useful for replacing every occurrence of a character value.  When using spans/arrays to build up strings, that capability is also useful, but today it needs to be hand-rolled, e.g.
```C#
Span<char> tmp = ...;
int pos;
while ((pos = tmp.IndexOf(oldValue)) >= 0)
{
    tmp[pos] = newValue;
    tmp = tmp.Slice(pos + 1);
}
```
It'd be good to have this as a reusable helper on MemoryExtensions so that such open-coded loops can be replaced.  There are other more complicated variations of this as well, but this is a simple and common one we can include.

e.g.
https://github.com/dotnet/runtime/blob/e8b149109c8b04161b83d0e4c997b63759c6d936/src/libraries/System.Private.Uri/src/System/Uri.cs#L1037-L1043
https://github.com/dotnet/runtime/blob/e8b149109c8b04161b83d0e4c997b63759c6d936/src/libraries/Common/src/System/IO/Archiving.Utils.Windows.cs#L79-L84

### API Proposal

```diff
namespace System
{
    public static class MemoryExtensions
    {
+        public static void Replace<T>(this Span<T> span, T oldValue, T newValue) where T : IEquatable<T>?;
    }
}
```

### API Usage

```C#
char[] result = ...;
result.AsSpan().Replace('\\', '/');
return new string(result);
```

**Comment by gfoidl** [comment]
I'm looking forward that this API gets approved -- so I can implement it 😉

**Comment by bartonjs** [comment]
* We discussed whether Replace should also return the replacement count, and the answer was no, because it has a nontrivial cost that exceeds its value (a counting variant could be added in the future, if needed)
  * If someone wants to try experimenting with this and show it's actually negligible, please change it to returning `int`.
* We discussed whether we needed a more complicated name, like ReplaceInPlace, to avoid a confusing overload with future potential replaces.  The feeling was "no".

```C#
namespace System
{
    public static class MemoryExtensions
    {
        public static void Replace<T>(this Span<T> span, T oldValue, T newValue) where T : IEquatable<T>?;
    }
}
```

**Comment by stephentoub** [comment]
One issue we didn't discuss today but should:
This is doing in-place replacement.  What do we do for code that wants to replace into something else, e.g. to be able to use this from string.Replace?  Currently string.Replace uses a conditional select to copy/replace from the source into the destination in one pass.  With the approved shape of this API, for string to use it, presumably it would need to copy to the destination and then in-place replace in the destination. Will that perform measurably worse?  Of course, the other approach is have Replace take two spans, a source and a destination, and we'd allow the input to be the same for each, but then we have the complication of what do we do if the arguments are overlapping but not the same, do we need to check for that or just say it's undefined behavior, etc.  We could also consider having both overloads.

We should come up with a pattern we want to use for these sorts of things, as it's going to start showing up more often, e.g. in https://github.com/dotnet/runtime/issues/75901, in https://github.com/dotnet/runtime/issues/26651, etc.

**Comment by stephentoub** [comment]
> I'm looking forward that this API gets approved -- so I can implement it 😉

Ok :smile: I assigned it to you.
