### ISSUE TITLE
The type 'Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[xxx]' can only be serialized using async serialization methods. Path: $.

### ISSUE THREAD

**Issue by JavaScript-zt** [dotnet/runtime#75327]
### Description

serialized  Task<IQueryable<xxx>>  get a error：
```
The type 'Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[xxx]' can only be serialized using async serialization methods. Path: $.

 at System.Text.Json.ThrowHelper.ThrowNotSupportedException_TypeRequiresAsyncSerialization(Type propertyType)
   at System.Text.Json.Serialization.Converters.IAsyncEnumerableOfTConverter`2.OnTryWrite(Utf8JsonWriter writer, TAsyncEnumerable value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
```
source code：
```c#
        internal override bool OnTryWrite(Utf8JsonWriter writer, TAsyncEnumerable value, JsonSerializerOptions options, ref WriteStack state)
        {
            if (!state.SupportContinuation)
            {
                ThrowHelper.ThrowNotSupportedException_TypeRequiresAsyncSerialization(TypeToConvert);
            }

            return base.OnTryWrite(writer, value, options, ref state);
        }
```

how to fix it?

### Reproduction Steps

    var iQueryable = await _bookRepository.GetEntity();
    retrun new {Data=iQueryable ;};

### Expected behavior

e

### Actual behavior

e

**Comment by danmoseley** [comment]
@JavaScript-zt I edited your post with ``` fences to make it more readable. Thanks for the issue.

**Comment by eiriktsarpalis** [comment]
This is by design; types implementing `IAsyncEnumerable` can only be serialized using one of the `JsonSerializer.SerializeAsync` overloads and cannot be handled using the sync methods. As a workaround you might consider registering a custom converter for the type in question that serializes using sync-over-async.

**Comment by JavaScript-zt** [comment]
how？

**Comment by JavaScript-zt** [comment]
> This is by design; types implementing `IAsyncEnumerable` can only be serialized using one of the `JsonSerializer.SerializeAsync` overloads and cannot be handled using the sync methods. As a workaround you might consider registering a custom converter for the type in question that serializes using sync-over-async.
  
Wrong interpretation！！！
why System.Text.Json dont use JsonSerializer.SerializeAsync ?

**Comment by eiriktsarpalis** [comment]
Excuse me? Please, behave yourself.

It might be possible for us to provide you with a workaround, but for that we would require a minimal reproduction and you being more respectful.

**Comment by danmoseley** [comment]
@JavaScript-zt we expect everyone in this repo to follow the code of conduct:

https://dotnetfoundation.org/about/code-of-conduct

Abusive language is not acceptable and may result in being banned from this repo.
