### ISSUE TITLE
Unable to run WebAssembly Browser App from VS or CLI

### ISSUE THREAD

**Issue by danroth27** [dotnet/runtime#75356]
### Description

I'm unable to run a new WebAssembly Browser App from VS or the CLI. 

### Reproduction Steps

```
dotnet workload install wasm-experimental
dotnet new wasmbrowser
dotnet run
```

Or create the project from VS and try to run in VS.

### Expected behavior

App runs successfully

### Actual behavior

The application to execute does not exist: 'C:\Program'

### Configuration

7.0.100-rc.1.22429.3
VS 17.4 P1

**Comment by radical** [comment]
Fix is being backported for rc2: https://github.com/dotnet/runtime/pull/75295

**Comment by lewing** [comment]
With that fix

```

A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Users\daroth\source\repos\WasmBrowserApp\WasmBrowserApp\bin\Debug\net7.0\browser-wasm\'.
Failed to run as a self-contained app.  - The application was run as a self-contained app because 'C:\Users\daroth\source\repos\WasmBrowserApp\WasmBrowserApp\bin\Debug\net7.0\browser-wasm\WasmBrowserApp.runtimeconfig.json' did not specify a framework.  - If this should be a framework-dependent app, specify the appropriate framework in 'C:\Users\daroth\source\repos\WasmBrowserApp\WasmBrowserApp\bin\Debug\net7.0\browser-wasm\WasmBrowserApp.runtimeconfig.json'.

```

**Comment by lewing** [comment]
@thaystg can you take a look?

**Comment by radical** [comment]
Looks like it is not running the WasmAppHost, and instead trying to find an apphost as it normally would. @thaystg do confirm the `$(RunArguments)` are correct. You can also try running the command manually to check that it isn't something else.

**Comment by danroth27** [comment]
Once build and run from VS and the CLI Just Works:tm: do we still need the README? The README could use some cleanup, or maybe it could just be removed.

Some suggested README updates if we want to keep it:

![image](https://user-images.githubusercontent.com/1874516/189421633-0e34bad5-322a-429b-8c84-da232224caa6.png)

## .NET WebAssembly Browser app

## Build

You can build the app from Visual Studio or from the command-line:

```
dotnet build -c Debug/Release -r browser-wasm
```

After building the app, the result is in the `bin/$(Configuration)/net7.0/browser-wasm/AppBundle` directory.

## Run

You can build the app from Visual Studio or the command-line:

```
dotnet run -c Debug/Release -r browser-wasm
```

Or you can start any static file server from the AppBundle directory:

```
dotnet tool install dotnet-serve
dotnet serve -d:bin/$(Configuration)/net7.0/browser-wasm/AppBundle
```

**Comment by danroth27** [comment]
It would also be great if the displayed app URLs on the command line used "localhost" instead of 127.0.0.1. Otherwise, I don't think the ASP.NET Core dev certificate gets used and user can get HTTPS errors in the browser. Let me know if you want me to open separate issues for this feedback.
