### ISSUE TITLE
SendFileGetsCanceledByDispose failed with ObjectDisposedException 

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#75354]
I'm not sure whether this is specific to the test, or just random timing that could affect any test (in which case this issue could be closed as a dupe maybe).

Was running locally, with today's main, on Windows 21H2.

```xml
      <test name="System.Net.Sockets.Tests.SendFile_CancellableTask.SendFileGetsCanceledByDispose(owning: True)" type="System.Net.Sockets.Tests.SendFile_CancellableTask" method="SendFileGetsCanceledByDispose" time="0.2562016" result="Fail">
        <failure exception-type="System.ObjectDisposedException">
          <message><![CDATA[System.ObjectDisposedException : Cannot access a disposed object.\r\nObject name: 'System.Net.Sockets.Socket'.]]></message>
          <stack-trace><![CDATA[   at System.Net.Sockets.Socket.ThrowIfDisposed() in C:\git\runtime\src\libraries\System.Net.Sockets\src\System\Net\Sockets\Socket.cs:line 3760
   at System.Net.Sockets.Socket.SendPacketsAsync(SocketAsyncEventArgs e, CancellationToken cancellationToken) in C:\git\runtime\src\libraries\System.Net.Sockets\src\System\Net\Sockets\Socket.cs:line 2984
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendPacketsAsync(Socket socket, CancellationToken cancellationToken) in C:\git\runtime\src\libraries\System.Net.Sockets\src\System\Net\Sockets\Socket.Tasks.cs:line 1141
   at System.Net.Sockets.Socket.SendFileAsync(String fileName, ReadOnlyMemory`1 preBuffer, ReadOnlyMemory`1 postBuffer, TransmitFileOptions flags, CancellationToken cancellationToken) in C:\git\runtime\src\libraries\System.Net.Sockets\src\System\Net\Sockets\Socket.Tasks.cs:line 730
   at System.Net.Sockets.Socket.SendFileAsync(String fileName, CancellationToken cancellationToken) in C:\git\runtime\src\libraries\System.Net.Sockets\src\System\Net\Sockets\Socket.Tasks.cs:line 655
   at System.Net.Sockets.Tests.SocketHelperCancellableTask.SendFileAsync(Socket s, String fileName) in C:\git\runtime\src\libraries\System.Net.Sockets\tests\FunctionalTests\SocketTestHelper.cs:line 287
   at System.Net.Sockets.Tests.SocketTestHelperBase`1.SendFileAsync(Socket s, String fileName) in C:\git\runtime\src\libraries\System.Net.Sockets\tests\FunctionalTests\SocketTestHelper.cs:line 445
   at System.Net.Sockets.Tests.SendFile`1.<>c__DisplayClass10_1.<<SendFileGetsCanceledByDispose>b__2>d.MoveNext() in C:\git\runtime\src\libraries\System.Net.Sockets\tests\FunctionalTests\SendFile.cs:line 270
--- End of stack trace from previous location ---
   at System.Net.Sockets.Tests.SendFile`1.<>c__DisplayClass10_0.<<SendFileGetsCanceledByDispose>b__0>d.MoveNext() in C:\git\runtime\src\libraries\System.Net.Sockets\tests\FunctionalTests\SendFile.cs:line 285
--- End of stack trace from previous location ---
   at System.RetryHelper.ExecuteAsync(Func`1 test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen, String testName) in C:\git\runtime\src\libraries\Common\tests\TestUtilities\System\RetryHelper.cs:line 94
   at System.Net.Sockets.Tests.SendFile`1.SendFileGetsCanceledByDispose(Boolean owning) in C:\git\runtime\src\libraries\System.Net.Sockets\tests\FunctionalTests\SendFile.cs:line 254
--- End of stack trace from previous location ---]]></stack-trace>
        </failure>
```

**Comment by liveans** [comment]
There is another report (windows x86 release) in one of the 7.0 backport PR's CI run on #75702 (@carlossanlop comment).
I couldn't be able to repro this unfortunately. We need to investigate it.

**Comment by karelz** [comment]
Triage: Happens very rarely -> 8.0. We should investigate.

**Comment by liveans** [comment]
Another hit (from @danmoseley in #75702)

> Hit on net7.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server2022.ES.Open in https://github.com/dotnet/runtime/pull/76652/checks?check_run_id=8730006416
> 
> ```
>     System.Net.Sockets.Tests.SendFile_Apm.SendFileGetsCanceledByDispose(owning: True) [FAIL]
>       System.ObjectDisposedException : Cannot access a disposed object.
>       Object name: 'System.Net.Sockets.Socket'.
>       Stack Trace:
>         /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(3760,0): at System.Net.Sockets.Socket.ThrowIfDisposed()
>         /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(2984,0): at System.Net.Sockets.Socket.SendPacketsAsync(SocketAsyncEventArgs e, CancellationToken cancellationToken)
>         /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs(1141,0): at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendPacketsAsync(Socket socket, CancellationToken cancellationToken)
>         /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs(730,0): at System.Net.Sockets.Socket.SendFileAsync(String fileName, ReadOnlyMemory`1 preBuffer, ReadOnlyMemory`1 postBuffer, TransmitFileOptions flags, CancellationToken cancellationToken)
>         /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(2356,0): at System.Net.Sockets.Socket.BeginSendFile(String fileName, Byte[] preBuffer, Byte[] postBuffer, TransmitFileOptions flags, AsyncCallback callback, Object state)
>         /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(2342,0): at System.Net.Sockets.Socket.BeginSendFile(String fileName, AsyncCallback callback, Object state)
>         /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SocketTestHelper.cs(203,0): at System.Net.Sockets.Tests.SocketHelperApm.<>c__DisplayClass14_0.<SendFileAsync>b__0(AsyncCallback callback, Object state)
>         /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/FutureFactory.cs(776,0): at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
>         /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskFactory.cs(880,0): at System.Threading.Tasks.TaskFactory.FromAsync(Func`3 beginMethod, Action`1 endMethod, Object state)
>         /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SocketTestHelper.cs(202,0): at System.Net.Sockets.Tests.SocketHelperApm.SendFileAsync(Socket s, String fileName)
>         /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SocketTestHelper.cs(445,0): at System.Net.Sockets.Tests.SocketTestHelperBase`1.SendFileAsync(Socket s, String fileName)
>         /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SendFile.cs(270,0): at System.Net.Sockets.Tests.SendFile`1.<>c__DisplayClass10_1.<<SendFileGetsCanceledByDispose>b__2>d.MoveNext()
>         --- End of stack trace from previous location ---
>         /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SendFile.cs(285,0): at System.Net.Sockets.Tests.SendFile`1.<>c__DisplayClass10_0.<<SendFileGetsCanceledByDispose>b__0>d.MoveNext()
>         --- End of stack trace from previous location ---
>         /_/src/libraries/Common/tests/TestUtilities/System/RetryHelper.cs(94,0): at System.RetryHelper.ExecuteAsync(Func`1 test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen, String testName)
>         /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SendFile.cs(254,0): at System.Net.Sockets.Tests.SendFile`1.SendFileGetsCanceledByDispose(Boolean owning)
>         --- End of stack trace from previous location ---
> Unhandled exception. System.TimeoutException: Timeout waiting for client connection.
>    at System.Net.Sockets.Tests.SocketTestServerAsync.StartAccept(SocketAsyncEventArgs acceptEventArg) in /_/src/libraries/Common/tests/System/Net/Sockets/SocketTestServerAsync.cs:line 141
>    at System.Net.Sockets.Tests.SocketTestServerAsync.ProcessAccept(SocketAsyncEventArgs e) in /_/src/libraries/Common/tests/System/Net/Sockets/SocketTestServerAsync.cs:line 178
>    at System.Net.Sockets.Tests.SocketTestServerAsync.StartAccept(SocketAsyncEventArgs acceptEventArg) in /_/src/libraries/Common/tests/System/Net/Sockets/SocketTestServerAsync.cs:line 141
>    at System.Net.Sockets.Tests.SocketTestServerAsync.ProcessAccept(SocketAsyncEventArgs e) in /_/src/libraries/Common/tests/System/Net/Sockets/SocketTestServerAsync.cs:line 178
>    at System.Net.Sockets.Tests.SocketTestServerAsync.StartAccept(SocketAsyncEventArgs acceptEventArg) in /_/src/libraries/Common/tests/System/Net/Sockets/SocketTestServerAsync.cs:line 141
>    at System.Net.Sockets.Tests.SocketTestServerAsync.ProcessAccept(SocketAsyncEventArgs e) in /_/src/libraries/Common/tests/System/Net/Sockets/SocketTestServerAsync.cs:line 178
>    at System.Net.Sockets.Tests.SocketTestServerAsync.StartAccept(SocketAsyncEventArgs acceptEventArg) in /_/src/libraries/Common/tests/System/Net/Sockets/SocketTestServerAsync.cs:line 141
>    at System.Net.Sockets.Tests.SocketTestServerAsync.ProcessAccept(SocketAsyncEventArgs e) in /_/src/libraries/Common/tests/System/Net/Sockets/SocketTestServerAsync.cs:line 178
>    at System.Net.Sockets.Tests.SocketTestServerAsync.StartAccept(SocketAsyncEventArgs acceptEventArg) in /_/src/libraries/Common/tests/System/Net/Sockets/SocketTestServerAsync.cs:line 141
>    at System.Net.Sockets.Tests.SocketTestServerAsync.ProcessAccept(SocketAsyncEventArgs e) in /_/src/libraries/Common/tests/System/Net/Sockets/SocketTestServerAsync.cs:line 178
>    at System.Net.Sockets.Tests.SocketTestServerAsync.AcceptEventArg_Completed(Object sender, SocketAsyncEventArgs e) in /_/src/libraries/Common/tests/System/Net/Sockets/SocketTestServerAsync.cs:line 174
>    at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs:line 216
>    at System.Net.Sockets.SocketAsyncEventArgs.OnCompletedInternal() in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs:line 211
>    at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs:line 454
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 163
> --- End of stack trace from previous location ---
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 163
>    at System.Net.Sockets.SocketAsyncEventArgs.<>c.<.cctor>b__176_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Windows.cs:line 1261
>    at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolBoundHandleOverlapped.cs:line 49
>    at System.Threading.ThreadPoolTypedWorkItemQueue`2.System.Threading.IThreadPoolWorkItem.Execute() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 1134
>    at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 919
>    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.WorkerThread.cs:line 77
>    at System.Threading.Thread.StartCallback() in /_/src/coreclr/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs:line 105
> ```
