### ISSUE TITLE
[API Proposal]: Type.HasDefaultConstructor method

### ISSUE THREAD

**Issue by AnteaterStudios** [dotnet/runtime#75362]
### Background and motivation

The purpose of the method is to check whether a type has a default (parameterless) constructor of not.

An example of usage is to check whether `Activator.CreateInstance(Type type)` method with return an exception due to missing necessary argument or not before it is called.

### API Proposal

```csharp
namespace System;

public static class TypeExtensions
{
    public static bool HasDefaultConstructor(this Type t)
    {
      return t.IsValueType || t.GetConstructor(Type.EmptyTypes) != null;
    }
}
```

#### IPlugin interface

```csharp

public interface IPlugin
{
	string HandlesDataFromSource { get; }
	void ProcessData(string data);
}

```

#### Loading the IPlugin types with default constructors
The following code gets all IPlugin types in the current assembly, then creates an instance if the type has a default constructor. 

```csharp

static void Main(string[] args)
{
	var candidateTypes = GetAllTypesThatImplementInterface<IPlugin>();

	Dictionary<string, IPlugin> routingTable = new Dictionary<string, IPlugin>();

	foreach(var type in candidateTypes)
	{
		if(HasDefaultConstructor(type))
		{
			var plugin = (IPlugin)Activator.CreateInstance(type);
			routingTable.Add(plugin.HandlesDataFromSource, plugin);
			Console.WriteLine($"Created type {type.Name}");

		}
		else
		{
			Console.WriteLine($"Not creating type {type.Name} - it doesn't have a default constructor");
		}
	}
}

private static IEnumerable<Type> GetAllTypesThatImplementInterface<T>()
{
	return System.Reflection.Assembly.GetExecutingAssembly()
	  .GetTypes()
	  .Where(type => typeof(T).IsAssignableFrom(type) && !type.IsInterface);
}

```

Note: It’s creating a routing table based on what the plugin says it can handle.

##### FileSystemDataHandler plugin – has compiler-generated default constructor

When you don’t declare a constructor, the compiler automatically creates a default constructor for you. When I run the code, it’ll load this plugin because it has a default constructor.

```csharp

public class FileSystemDataHandler : IPlugin
{
	public string HandlesDataFromSource => "FileSys";

	public void ProcessData(string data)
	{
		//process data
	}
}

```

##### HttpDataHandler plugin – has user-defined declared default constructor

In this class I declared a constructor that has no parameters – therefore it’s a default constructor, and this plugin will be loaded when I run the code.

```csharp

public class HttpDataHandler : IPlugin
{
	public string HandlesDataFromSource => "Http";

	public void ProcessData(string data)
	{
		//process data
	}
	private HashSet<string> wordFilterSet;
	public HttpDataHandler()
	{
		var wordFilterList = ConfigurationManager.AppSettings["wordFilter"].Split(',');
		wordFilterSet = new HashSet<string>(wordFilterList);
	}
}

```

##### SqlDataHandler plugin – no default constructor

The following plugin has a constructor with parameters, which means it doesn’t have a default constructor. Because it doesn’t have a default constructor, it will not be loaded.

```csharp

public class SqlDataHandler : IPlugin
{
	private ConnectionStringSettings ConnectionStringSettings;

	public SqlDataHandler(ConnectionStringSettings connectionStringSetting)
	{
		ConnectionStringSettings = connectionStringSetting;
	}

	public string HandlesDataFromSource => "Sql";

	public void ProcessData(string data)
	{
		//process data
	}
}

```

#### Results

Running the code results in the following output (attached image). As you can see it doesn’t load SqlDataHandler (because it doesn’t have a default constructor, therefore it’s filtered out).

![loading-plugins-with-default-constructor](https://user-images.githubusercontent.com/80472493/207629342-36fe5e16-c7a4-4dbb-a0ec-13a483b97985.png)

_API usage example from [here](https://makolyte.com/csharp-how-to-check-if-a-type-has-a-default-constructor/)._

### Alternative Designs

```csharp

public static bool HasDefaultConstructor(this Type t) => 
                t.IsValueType || !t.IsAbstract && t.GetConstructor(Type.EmptyTypes) != null;

```

Notice the check for `t.IsAbstract`.

It is also possible to expand the `GetConstructor` call out as follows, if you feel like optimizing away one stack frame:

```csharp

…t.GetConstructor(BindingFlags.Public|BindingFlags.Instance, null, Type.EmptyTypes, null)…

```

#### Alternative method name

`CanCreateInstanceUsingDefaultConstructor(this Type type)`

**Comment by AnteaterStudios** [comment]
The method would be directly implemented into the Type class. Ignore the fact that I have written it as an extension method.

**Comment by grbell-ms** [comment]
Now that value types can have explicit parameterless constructors, should `HasDefaultConstructor` return true for a value type without such a constructor?

**Comment by AnteaterStudios** [comment]
> Now that value types can have explicit parameterless constructors, should `HasDefaultConstructor` return true for a value type without such a constructor?

I imagine that someone would potentially use it to try to instantiate a new object using the "default" constructor (the one without parameters). In that case, I think that checking for value type is valid. But indeed, maybe that's not what the developer will want anyway.

Well, the method checks whether the type can be instantiated with no parameters or not. Since that is the purpose of the method, I suppose returning true when the type is a value type can be considered as valid (since value types can always be instantiated with no parameters).

Anyway, I'm not sure. What's your opinion on the case?

**Comment by dakersnar** [comment]
Can you elaborate a bit on potential use cases for this API? I'm having trouble understanding why this needs to be queried at runtime.

**Comment by AnteaterStudios** [comment]
> Can you elaborate a bit on potential use cases for this API? I'm having trouble understanding why this needs to be queried at runtime.

I just edited my issue to provide an use case for this API. It would be used mainly with reflection. In the example I gave (from [here](https://makolyte.com/csharp-how-to-check-if-a-type-has-a-default-constructor/)) the API helps avoiding any potential exceptions being thrown before a certain type derived from IPlugin interface is instantiated using the `Activator.CreateInstance(Type type)` method.

**Comment by jkotas** [comment]
> the API helps avoiding any potential exceptions being thrown before a certain type derived from IPlugin interface is instantiated using the Activator.CreateInstance(Type type) method

There are number of other situations where `Activator.CreateInstance` fails. For example, it is going to fail for abstract types.

**Comment by AnteaterStudios** [comment]
> > the API helps avoiding any potential exceptions being thrown before a certain type derived from IPlugin interface is instantiated using the Activator.CreateInstance(Type type) method
> 
> There are number of other situations where `Activator.CreateInstance` fails. For example, it is going to fail for abstract types.

I edited my issue again to consider this scenario.

**Comment by AnteaterStudios** [comment]
Also provided alternative design to optimize method.

**Comment by jkotas** [comment]
> I edited my issue again to consider this scenario

There are number of other situations in addition to that. It sounds like the method you would actually want is `static bool CanBeCreatedUsingActivatorCreateInstance(Type type)`.

> Also provided alternative design to optimize method.

The JIT will do this optimization for you for free. This won't make anything materially faster.

**Comment by AnteaterStudios** [comment]
> There are number of other situations in addition to that.

@jkotas please tell me a situation that this API wouldn't work as intended. That way I can try to fix it or change it's purpose.

>  It sounds like the method you would actually want is static bool CanBeCreatedUsingActivatorCreateInstance(Type type).

Good suggestion. Personally, if it was to change the name I would switch to `CanCreateInstanceUsingDefaultConstructor(this Type type)` for specifying that the method checks if a instance of the type could be created with no arguments. I'm going to edit my issue to insert this suggestion on Alternative Designs. Thank you!

**Comment by jkotas** [comment]
> please tell me a situation that this API wouldn't work as intended.

You can go through the implementation of Activator.CreateInstance for find the full set of conditions: https://github.com/dotnet/runtime/blob/983c8f239a98812498d874ed36b7001bd764fdfe/src/coreclr/nativeaot/System.Private.CoreLib/src/System/ActivatorImplementation.cs#L117-L137

> CanCreateInstanceUsingDefaultConstructor

Value types (structs in C#) do not have default constructor, but they can still be created using activator create instance.
