### ISSUE TITLE
[P/Invoke] Tuples should be marked with LayoutKind.Sequential instead of LayoutKind.Auto

### ISSUE THREAD

**Issue by Unknown6656** [dotnet/runtime#75388]
Tuples have been marked with the Attribute `[StructLayout(LayoutKind.Auto)]` since #18250 in order to improve performance.

The trouble is, that using `[StructLayout(LayoutKind.Auto)]` on tuples makes them unable to be used in P/Invoke APIs. I therefore propose to change tuples to be annotated with `[StructLayout(LayoutKind.Sequential)]` instead of `[StructLayout(LayoutKind.Auto)]`, making them usable in any P/Invoke-code.

**Comment by DaZombieKiller** [comment]
Personally, I don't find `ValueTuple<...>` to be a suitable set of types for interop scenarios. Changing them to `LayoutKind.Sequential` _purely_ to allow them in interop sounds like a "square peg in round hole" situation to me.

The use case doesn't seem compelling enough to eschew the benefits of giving them auto layout to me, either.

If you're writing interop code, you should probably be defining your own interop structures alongside it.

**Comment by Unknown6656** [comment]
OK, thank you very much. I'd try to avoid creating new structs (such as e.g. `COORD` or `RECT`) if they are reasonably small and I only use them in P/Inovke  - instead preferring tuples (if they were supported)....

Just purely out of interest - how much is the performance improvement of using `[StructLayout(LayoutKind.Auto)]` on tuples? Do you have some kind benchmark or statistics? :)

**Comment by stephentoub** [comment]
> how much is the performance improvement of using [StructLayout(LayoutKind.Auto)] on tuples? Do you have some kind benchmark or statistics? :)

It's about size and allocation, and in particular when an instance of the struct is boxed or contained in another object, e.g. in this example it saves 8 bytes per object on 64-bit:
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwGIAHKAQwHMBbcgAgHdyo8BLPSugE1YGdzgAGxh0AjEgCcAWABQAAQBMo2XIAMdOaIB0AJXwZW1GFoCSeDDCgQSAZUsA3VmBi8A3LNlneJGGAxaACRhyEgAKLhgAM3IcQQxQgEEASiT3GS8fP0DgsIjo2PiAIRS02V4MXD86BNkAb1k6RrpgCAhBOkjRNKa6QQgODoVuppa2joBmNIBfDxkAbRsKnD8AGXIATwgceLXN7YBpdi4tBO2IJIBdMqWqwrqGkdb2zuHGvoHIoYfG0efJ2SmdCAA=

**Comment by Unknown6656** [comment]
Ah ok, thank you vey much!
