### ISSUE TITLE
Try improved method for generating bounded random integers

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#75395]
https://github.com/apple/swift/pull/39143 (Apache license)

Currently we use a simple rejection loop for generating int/long in a range https://github.com/dotnet/runtime/blob/c746b8bad1af001351efa2056c35c51597998724/src/libraries/System.Private.CoreLib/src/System/Random.Xoshiro128StarStarImpl.cs#L91 and other overloads. It may be that the Swift algorithm above is faster. 

(Note that our existing algorithm is dropping high bits of the raw random result to minimize the rejections. If we can avoid doing that possibly it would improve the distribution?).

(I'm ignoring our legacy seeded impl which prefers reproducibility)

**Comment by MichalPetryka** [comment]
Looking at that impl, we'd need the `TryAdd` intrinsics that were discussed a few times with @GrabYourPitchforks on discord to avoid the `catch(OverflowException)` cost here.

**Comment by danmoseley** [comment]
Is there an issue for those? I'm not familiar with that proposal.

**Comment by MichalPetryka** [comment]
I don't think one has been opened in the end.

**Comment by tannergooding** [comment]
We have a couple proposals covering `AddWithCarry` which achieves the same thing.

The usage in this particular scenario also looks simple enough we can just do the pattern of:
```csharp
uint result = left + right;

if (result < left)
{
    // overflow occurred
}
```

**Comment by lemire** [comment]
Reference: [Fast Random Integer Generation in an Interval](https://arxiv.org/pdf/1805.10941.pdf) ACM Transactions on Modeling and Computer Simulation 29 (1), 2019

**Comment by mla-alm** [comment]
Hi, I'd be interested in doing this.

By making a simple console implementation I did not find the referred apple/swift way as the the fastest. I even found it slower than the current for 64-bit.

I found Lemire's algorithm to be the fastest (on my setup). My simple testing gave these estimates:
32-bit:
Overall:           -15 %
(1 << 30) + 1: -35 %
(1 << 30) - 1:     0 %
64-bit:
Overall:          -10 %
(1 << 62) + 1: -35 %
(1 << 62) - 1: +12 %
(Where overall means that the max value is taken as randomly distributed numbers, otherwise it is the number to the left.)

**Comment by danmoseley** [comment]
@mla-alm great, I assigned to you!

You will want to probably first check we have the right benchmarks to validate what you do. Take a look dotnet/performance -- they are there, and good docs on how to run them. The benchmarks could go in first - or after - so long as you have something to validate with.

**Comment by mla-alm** [comment]
The implementation of Lemire's algorithm in https://github.com/dotnet/runtime/pull/79790 gave the following results using dotnet/performance.
https://github.com/apple/swift/pull/39143/commits/87b3f607042e653a42b505442cc803ec20319c1c with the optional early out (line 209) was implemented and gave approximately the same results - however being slightly biased.

**Comment by mla-alm** [comment]
|                  Method |     Mean |     Error |    StdDev |   Median |      Min |      Max | Allocated |
|------------------------ |---------:|----------:|----------:|---------:|---------:|---------:|----------:|
|           Next_unseeded | 1.975 ns | 0.0079 ns | 0.0074 ns | 1.976 ns | 1.960 ns | 1.986 ns |         - |
|       Next_int_unseeded | 1.960 ns | 0.0044 ns | 0.0041 ns | 1.959 ns | 1.955 ns | 1.970 ns |         - |
|   Next_int_int_unseeded | 2.232 ns | 0.0156 ns | 0.0146 ns | 2.231 ns | 2.213 ns | 2.262 ns |         - |
|      Next_long_unseeded | 2.636 ns | 0.0123 ns | 0.0115 ns | 2.636 ns | 2.616 ns | 2.653 ns |         - |
| Next_long_long_unseeded | 3.205 ns | 0.0136 ns | 0.0120 ns | 3.208 ns | 3.183 ns | 3.226 ns |         - |

**Comment by mla-alm** [comment]
| Faster                                           | base/diff | Base Median (ns) | Diff Median (ns) | Modality|
| ------------------------------------------------ | ---------:| ----------------:| ----------------:| --------:|
| System.Tests.Perf_Random.Next_int_unseeded       |      3.25 |             6.38 |             1.96 |         |
| System.Tests.Perf_Random.Next_int_int_unseeded   |      2.99 |             6.66 |             2.23 |         |
| System.Tests.Perf_Random.Next_long_long_unseeded |      2.02 |             6.48 |             3.21 |         |
| System.Tests.Perf_Random.Next_long_unseeded      |      1.46 |             3.84 |             2.64 |         |

**Comment by mla-alm** [comment]
As compared to the main using ResultsComparer with threshold = 2%.

Please advise if I should change https://github.com/dotnet/runtime/pull/79790 from draft or if you are more interested in the algorithm from https://github.com/apple/swift/pull/39143/commits/87b3f607042e653a42b505442cc803ec20319c1c .

**Comment by danmoseley** [comment]
Nice improvements!

**Comment by danmoseley** [comment]
> https://github.com/apple/swift/commit/87b3f607042e653a42b505442cc803ec20319c1c with the optional early out (line 209) was implemented and gave approximately the same results - however being slightly biased.

The swift algorithm claims to be unbiased, by making the bias immeasurably small. Do you believe otherwise?

It's curious you find the Swift one slower, since it was designed to be faster, but no matter -- clearly, Lemire is substantially faster than what we have today, so I think it's fine to go with that.

**Comment by mla-alm** [comment]
No, I guess slightly biased and immeasurably small is same-same here.
It will be faster when Lemire's reject a lot. So depends on the benchmarks.

**Comment by IDisposable** [comment]
Was this actually completed with https://github.com/dotnet/runtime/pull/79790

**Comment by lemire** [comment]
Shouldn't this issue be closed?

**Comment by danmoseley** [comment]
I think so
