### ISSUE TITLE
[release/7.0][wasm] Debugger test `ExceptionTestUncaughtWithReload` failing

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#75392]
[Build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=11459), and
[log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-70-86cf3625b0f44c3a9a/chrome-DebuggerTests/1/console.a62cc7da.log?helixlogtype=result):
```
[xUnit.net 00:39:47.90]     DebuggerTests.ExceptionTests.ExceptionTestUncaughtWithReload [FAIL]
  Failed DebuggerTests.ExceptionTests.ExceptionTestUncaughtWithReload [1 s]
  Error Message:
   [pause1]

Expected: DebuggerTests.ExceptionTestsClass.TestUncaughtException.run
Actual:   invoke_static_method
  Stack Trace:
     at DebuggerTests.DebuggerTestBase.AssertEqual(Object expected, Object actual, String label) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 1184
   at DebuggerTests.ExceptionTests.ExceptionTestUncaughtWithReload() in /_/src/mono/wasm/debugger/DebuggerTestSuite/ExceptionTests.cs:line 251
--- End of stack trace from previous location ---
[Result: IsOk: True, IsErr: False, Value: {
  "breakpointId": "1:539:8:dotnet://debugger-test.dll//_/src/mono/wasm/debugger/tests/debugger-test/debugger-test.cs",
  "locations": [
    {
      "scriptId": "dotnet://27014_1",
      "lineNumber": 542,
      "columnNumber": 8
    }
  ]
}, Error:  ]
[Result: IsOk: True, IsErr: False, Value: {
  "breakpointId": "1:1272:8:dotnet://debugger-test.dll//_/src/mono/wasm/debugger/tests/debugger-test/debugger-test.cs",
  "locations": []
}, Error:  ]
```

**Comment by ilonatommy** [comment]
I can't reproduce, neither on `release/7.0` nor on `main`.

**Comment by radical** [comment]
@ilonatommy this test is racy because it uses `Thread.Sleep(1000)`(https://github.com/dotnet/runtime/blob/main/src/mono/wasm/debugger/DebuggerTestSuite/ExceptionTests.cs#L241). The test is sending a `Page.reload`, and wants to run rest of the test once that is complete. But at the end of `Thread.Sleep(1000)`, the page might not have completed reloading.

To avoid that we want to use some deterministic signal that the page is ready. you could use `await insp.WaitFor(Inspector.APP_READY)`.

https://github.com/dotnet/runtime/blob/a889912cf71f13fec142a33e0cdbf8b1120ed8b3/src/mono/wasm/debugger/DebuggerTestSuite/BreakpointTests.cs#L792-L797

This is one example. And in fact `CreateGoodBreakpointAndHitGoToNonWasmPageComeBackAndHitAgain` needs a similar fix:

https://github.com/dotnet/runtime/blob/a889912cf71f13fec142a33e0cdbf8b1120ed8b3/src/mono/wasm/debugger/DebuggerTestSuite/BreakpointTests.cs#L507-L514
