### ISSUE TITLE
JsonSerializer.Serialize does not serialize properties as interface data type

### ISSUE THREAD

**Issue by oliveira-alexdias** [dotnet/runtime#75402]
### Description

**Library**: System.Text.Json
**Version**: 6.0.0.0
**Class**: JsonSerializer
**File**: [JsonSerializer.Write.String.cs](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.String.cs)

`JsonSerializer.Serialize` is not able to proper serialize an object when its properties are interfaces data type.

### Reproduction Steps

Consider the following code:

``` csharp
public class MyClass
{
     public int Count { get; set; }
     public IContract Contract { get; set; }
}

public class Implementation: IContract
{
     public string Value { get; set; }
}

public class Program
{
     public static string GetObjectSerialized()
     {
          var myClass = new MyClass()
          {
               Count = 10,
               Contract = new Implementation()
               {
                    Value = "This is a value"
                }
           };

           var json = JsonSerializer.Serialize(myClass);
           return json;
     }
}
```

### Expected behavior

A proper JSON value.
In the refered example the method `GetObjectSerialized` should return `{"Count":10,"Contract":{"Value":"This is a value"}}`.

### Actual behavior

An incorrect JSON value. 
In the refered example the method `GetObjectSerialized` returns `{"Count":10,"Contract":{}}`

### Regression?

I ran the same code in .NET 5 and the behavior is the same one.

### Known Workarounds

Use `JsonConvert.SerializeObject` of **Newtonsoft.Json** (v. 13.0.2-beta2).

### Configuration

- .NET 6 (I also tried in .NET Core 5)
- Windows 10 64 bits

### Other information

The same goes to abstract classes. In the refered example, if I replace `public interface IContract` to `public abstract class Contract` the behavior is exactly the same.

**Comment by ovska** [comment]
You can work around this by using a custom converter:
```cs
public class IContractConverter : JsonConverter<IContract>
{
    public override IContract Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options)
    {
        return JsonSerializer.Deserialize<Implementation>(ref reader, options);
    }

    public override void Write(
        Utf8JsonWriter writer,
        IContract value,
        JsonSerializerOptions options)
    {
        var type = value.GetType();
        JsonSerializer.Serialize(writer, value, type, options);
    }
}
```
https://gist.github.com/ovska/6bab3cb39ff63f23daa11fe5a4235929

**Comment by krwq** [comment]
you can:
- custom converter as mentioned above

for 7.0 (or 7.0 nuget package) you also have options of:
- setup polymorphic behavior for your type if you want different behavior per type: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/ref/System.Text.Json.cs#L881-L888
- contract customization if you want it to serialize/deserialize in specific way
(you can also combine polymorphism with contract customization)

**Comment by krwq** [comment]
Closing this issue. Please re-open if you feel this didn't answer the question or you have further
