### ISSUE TITLE
bugs: System.Int128 operator * and % at overflow

### ISSUE THREAD

**Issue by c-ohle** [dotnet/runtime#75416]
### In case of an overflow for multiplication `*` and remainder `%`  `System.Int128` gives wrong results.
All other C# integer types behave in this case correctly like standard on all machines and platforms.
The problem is that there are many algorithms that assume correct partial results in case of an overflow as part of the calculation.
All these algorithms can fail with Int128 and it's dangerous because the user wouldn't expect it.

The bug is in `public static Int128 operator *(Int128 left, Int128 right)`
Easy to see that the case is simply not handled and the final `return new Int128(result.Upper | sign, result.Lower);` copys the sign always. 
This is like a proof as the sign of the result shouldn't be affected in this case.
It also follows that the error occurs in large number ranges, in other ranges not and in sub-ranges alternating.

Exactly the same issue in `public static Int128 operator %(Int128 left, Int128 right)`.

As reference, to reproduce and test the following code can be used: [Test System.Int128 functions, operator and INumber implementation](https://github.com/c-ohle/RationalNumerics/blob/5cdc322b5d06be62718e1f653bc41afe678ab2b1/Test/Program.cs#L496).
A template solution for arbitrary number type for NET7 is used, which of course also supports int128. 
An correct implementation for multiplication and remainder can be taken from there.
The tests also show that all other `System.Int128` functions and operators handle the overflows correctly. 

### Reproduction Steps

```csharp
var a = (Int128.MaxValue - 10) * +100; // -1100 ok
var b = (Int128.MaxValue - 10) * -100; // -170141183460469231731687303715884104628 wrong, should be +1100
```

### Expected behavior

```csharp
var a = (Int128.MaxValue - 10) * +100; // -1100 
var b = (Int128.MaxValue - 10) * -100; // +1100

```

### Actual behavior

```csharp
var a = (Int128.MaxValue - 10) * +100; // -1100 ok
var b = (Int128.MaxValue - 10) * -100; // -170141183460469231731687303715884104628 wrong, should be +1100
```

**Comment by jeffhandley** [comment]
@tannergooding / @dotnet/area-system-numerics Since this is broken new functionality, I'm going to apply the `blocking-release` label. If the fix comes in this week, we can request servicing into RC2. Next week and beyond we'd be looking at the GA milestone.

**Comment by hamarb123** [comment]
I just ran into this as well lol, I downloaded the newest daily build but I guess it wasn't new enough.
