### ISSUE TITLE
buiLd   runtime  C:\WINDOWS was unexpected at this time.

### ISSUE THREAD

**Issue by liujian1368928** [dotnet/runtime#75410]
Executing "F:\SourceCode\Net\runtime\src\coreclr\build-runtime.cmd" -x64 -debug -os windows
  BUILD: Starting Build at 16:51:22.72
  BUILD: Commencing CoreCLR product build
  BUILD: Checking prerequisites
  BUILD: Using CMake from E:\WorkingSoftware\VS2022\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe
  BUILD: Number of processor cores 6
  BUILD: Commencing build of native components for windows.x64.Debug
  BUILD: Using environment: "E:\WorkingSoftware\VS2022\VC\Auxiliary\Build\vcvarsall.bat" amd64
  C:\WINDOWS was unexpected at this time.
F:\SourceCode\Net\runtime\src\coreclr\runtime.proj(61,5): error MSB3073: 命令“"F:\SourceCode\Net\runtime\src\coreclr\buil
d-runtime.cmd" -x64 -debug -os windows” exit，code 255。

Generate failure
F:\SourceCode\Net\runtime\src\coreclr\runtime.proj(61,5): error MSB3073: 命令“"F:\SourceCode\Net\runtime\src\coreclr\buil
d-runtime.cmd" -x64 -debug -os windows”exit，code255。

I Using Docs \ Workflow \ Building \ CoreClr \ Document compilation This is my first compilation, I don't know why this is happening. This has been bothering me for days

Please help me. This is machine translation and also the first time I add Issue. If there is any mistake, please tell me

**Comment by huoyaoyuan** [comment]
I think most of the contributors install VS at default path, so there may be something we are unaware of when VS is installed into another drive.

**Comment by liujian1368928** [comment]
> 我认为大多数贡献者都在默认路径上安装VS，因此当VS安装到另一个驱动器中时，我们可能不知道某些事情。

thanks I'll try it tomorrow

**Comment by AntonLapounov** [comment]
If you run the following command from a command prompt, does it fail as well?
```
"E:\WorkingSoftware\VS2022\VC\Auxiliary\Build\vcvarsall.bat" amd64
```
If yes, you may `set VSCMD_DEBUG=3` to get verbose output from it.  If that command does not fail, you may `set _echo=1` to get verbose output from `build-runtime.cmd`.

**Comment by liujian1368928** [comment]
> If you run the following command from a command prompt, does it fail as well?
> 
> ```
> "E:\WorkingSoftware\VS2022\VC\Auxiliary\Build\vcvarsall.bat" amd64
> ```
> 
> If yes, you may `set VSCMD_DEBUG=3` to get verbose output from it. If that command does not fail, you may `set _echo=1` to get verbose output from `build-runtime.cmd`.




F:\SourceCode\Net\runtime\src\coreclr>if "" NEQ "" (
set __VCVARS_SCRIPT_ERROR=
 exit /B 1
)

F:\SourceCode\Net\runtime\src\coreclr>exit /B 0

F:\SourceCode\Net\runtime\src\coreclr>set "__VSCMD_INTERNAL_INIT_STATE="

F:\SourceCode\Net\runtime\src\coreclr>set "VSCMD_ARG_STARTDIR="

F:\SourceCode\Net\runtime\src\coreclr>goto :end

F:\SourceCode\Net\runtime\src\coreclr>set __VSCMD_ARG_APP_PLAT=

F:\SourceCode\Net\runtime\src\coreclr>set __VSCMD_ARG_CLEAN_ENV=

F:\SourceCode\Net\runtime\src\coreclr>set __VSCMD_ARG_HELP=

F:\SourceCode\Net\runtime\src\coreclr>set __VSCMD_ARG_HOST_ARCH=

F:\SourceCode\Net\runtime\src\coreclr>set __VSCMD_ARG_NO_EXT=

F:\SourceCode\Net\runtime\src\coreclr>set __VSCMD_ARG_NO_LOGO=

F:\SourceCode\Net\runtime\src\coreclr>set __VSCMD_ARG_TEST=

F:\SourceCode\Net\runtime\src\coreclr>set __VSCMD_ARG_TGT_ARCH=

F:\SourceCode\Net\runtime\src\coreclr>set __VSCMD_ARG_WINSDK=

F:\SourceCode\Net\runtime\src\coreclr>set __VSCMD_ARG_STARTDIR=

F:\SourceCode\Net\runtime\src\coreclr>if "0" NEQ "0" (
set __local_parse_error=
 exit /B 1
)

F:\SourceCode\Net\runtime\src\coreclr>set __local_parse_error=

F:\SourceCode\Net\runtime\src\coreclr>exit /B 0

F:\SourceCode\Net\runtime\src\coreclr>if "0" NEQ "0" set /A __vscmd_vsdevcmd_errcount=__vscmd_vsdevcmd_errcount+1

F:\SourceCode\Net\runtime\src\coreclr>if /I "" == "none" set "__VSCMD_CURRENT_DIR=F:\SourceCode\Net\runtime\src\coreclr"

F:\SourceCode\Net\runtime\src\coreclr>if "3" GEQ "2" (




)
[DEBUG:vsdevcmd_start] Parsing results...
[DEBUG:vsdevcmd_start] -clean_env :
[DEBUG:vsdevcmd_start] -test      :
[DEBUG:vsdevcmd_start] -help      :

F:\SourceCode\Net\runtime\src\coreclr>if "" == "1" goto :end

F:\SourceCode\Net\runtime\src\coreclr>if "" NEQ "" (
if "3" NEQ "" ()

 set  1>C:\Users\孤海飞雁\AppData\Local\Temp\test_dd_vsdevcmd17_env.log

 setlocal
 if "" NEQ "" (

 if "0" NEQ "" set /A __vscmd_vsdevcmd_errcount=__vscmd_vsdevcmd_errcount+1
)
 goto :end
)

F:\SourceCode\Net\runtime\src\coreclr>if "" NEQ "" goto :end
C:\WINDOWS was unexpected at this time.

F:\SourceCode\Net\runtime\src\coreclr>if "E:\WorkingSoftware\VMWare\bin\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\nodejs\;E:\WorkingSoftware\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;"C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem";C:\Users\孤海飞雁\AppData\Local\Microsoft\WindowsApps;;C:\Users\孤海飞雁\AppData\Local\Programs\Microsoft VS Code\bin;E:\WorkingSoftware\VsCode\Microsoft VS Code\bin;C:\Users\孤海飞雁\AppData\Roaming\npm;C:\Program Files\Azure Data Studio\bin;C:\Users\孤海飞雁\.dotnet\tools"=="" (

This is part of the details of build-runtime. CMD, the error should be here, please check how I should solve it

**Comment by liujian1368928** [comment]
> 如果从命令提示符运行以下命令，它是否也会失败？
> 
> ```
> "E:\WorkingSoftware\VS2022\VC\Auxiliary\Build\vcvarsall.bat" amd64
> ```
> 
> 如果是，您可以从中获取详细的输出。如果该命令没有失败，则可以从 中获取详细输出。`set VSCMD_DEBUG=3``set _echo=1``build-runtime.cmd`

[1.txt](https://github.com/dotnet/runtime/files/9544767/1.txt)

**Comment by liujian1368928** [comment]
> I think most of the contributors install VS at default path, so there may be something we are unaware of when VS is installed into another drive.

The default installation still doesn't work

**Comment by AntonLapounov** [comment]
Thank you for the verbose output.  There is an issue with the `Path` variable in your environment:
```
Path=E:\WorkingSoftware\VMWare\bin\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\nodejs\;E:\WorkingSoftware\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;"C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem";C:\Users\孤海飞雁\AppData\Local\Microsoft\WindowsApps;;C:\Users\孤海飞雁\AppData\Local\Programs\Microsoft VS Code\bin;E:\WorkingSoftware\VsCode\Microsoft VS Code\bin;C:\Users\孤海飞雁\AppData\Roaming\npm;C:\Program Files\Azure Data Studio\bin;C:\Users\孤海飞雁\.dotnet\tools
```
You need to remove this part (including quotes) from its value:
```
"C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem";
```
Having quotes in `Path` breaks batch scripts.

**Comment by liujian1368928** [comment]
> Thank you for the verbose output. There is an issue with the `Path` variable in your environment:
> 
> ```
> Path=E:\WorkingSoftware\VMWare\bin\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\nodejs\;E:\WorkingSoftware\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;"C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem";C:\Users\孤海飞雁\AppData\Local\Microsoft\WindowsApps;;C:\Users\孤海飞雁\AppData\Local\Programs\Microsoft VS Code\bin;E:\WorkingSoftware\VsCode\Microsoft VS Code\bin;C:\Users\孤海飞雁\AppData\Roaming\npm;C:\Program Files\Azure Data Studio\bin;C:\Users\孤海飞雁\.dotnet\tools
> ```
> 
> You need to remove this part (including quotes) from its value:
> 
> ```
> "C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem";
> ```
> 
> Having quotes in `Path` breaks batch scripts.

Thanks for your reply. I have been solving this problem after upgrading Win11. It may be because I use Win10 LTSC version, but I will try your solution in the virtual machine
