### ISSUE TITLE
Extend the MinOpts/GCtracking tweak to more platforms

### ISSUE THREAD

**Issue by pkukol** [dotnet/runtime#7542]
Currently "simplified GC root tracking with MinOpts" is only enabled by default for CoreCLR builds for AMD64 targets; we should widen reach to more platforms/configs over time.
category:throughput
theme:gc-info
skill-level:expert
cost:large

**Comment by TIHan** [comment]
We need a bit more info and discussion regarding this as it seems like a big cost. Keeping as future and asking for more info.

**Comment by jakobbotsch** [comment]
Going to close as a duplicate of #103917 since that one has a bit more context now (didn't realize this issue existed before I opened it).
