### ISSUE TITLE
HttpClientHandler always set LocalCertificateSelectionCallback delegate in SslOptions

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#75434]
Besides extra work this prevents TLS resume on Linux so HttpClient won't be able to benefit from #64369

https://github.com/dotnet/runtime/blob/855c475fd9c0b3a303e3de15785b63456108f7e3/src/libraries/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs#L298-L310

Since the delegate _could_ return different certificate, we would somehow need to track what was actually selected and resume accordingly (if possible)

It seems like the best option wold be not set the delegate unless there is actual need e.g. client certificate is in use.

**Comment by karelz** [comment]
Triage: Would be nice to make sure TLS resume works also with HTTP, not just with SSL.
