### ISSUE TITLE
Get,Post,Put methods......

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#75446]
I suggest adding synchronous Get, Post, Put,....methods to HttpClient, since there is an implemented Send method, well, there are no synchronous access methods to it, in fact, it will not be difficult to add such methods, and they are useful in some situations.
Making a Result on a task is not very good!

**Comment by MihaZupan** [comment]
We want to discourage developers from using synchronous APIs as they come with many limitations (e.g. only HTTP/1.1 support) and should only be used as a last resort when `async` is not an option.
Adding convenience APIs directly works against that.

What is the use case that is preventing you from using the async APIs?

If you need such helpers, they are trivial to add as your own extension methods
```c#
public static class HttpClientExtensions
{
    public HttpResponseMessage Get(this HttpClient client, string? requestUri, CancellationToken cancellationToken = default) =>
        Get(client, new Uri(requestUri, UriKind.RelativeOrAbsolute), cancellationToken);

    public HttpResponseMessage Get(this HttpClient client, Uri? requestUri, CancellationToken cancellationToken = default) =>
        Get(client, requestUri, HttpCompletionOption.ResponseContentRead, cancellationToken);

    public HttpResponseMessage Get(this HttpClient client, Uri? requestUri, HttpCompletionOption completionOption, CancellationToken cancellationToken = default) =>
        client.Send(CreateRequestMessage(client, HttpMethod.Get, requestUri), completionOption, cancellationToken);

    public HttpResponseMessage Delete(this HttpClient client, Uri? requestUri, HttpCompletionOption completionOption, CancellationToken cancellationToken = default) =>
        client.Send(CreateRequestMessage(client, HttpMethod.Delete, requestUri), completionOption, cancellationToken);

    private static HttpRequestMessage CreateRequestMessage(HttpClient client, HttpMethod method, Uri? uri) =>
        new HttpRequestMessage(method, uri) { Version = client.DefaultRequestVersion, VersionPolicy = client.DefaultVersionPolicy };
}
```

**Comment by Mr0N** [comment]
> 

The program is not always asynchronous! And Result, on the contrary, reduces performance

**Comment by MihaZupan** [comment]
Not every project should be using these APIs. As I said, they should only be used as a last resort when `async` is not available (e.g. running in a callback of a legacy API that is out of your control and doesn't support `async`).

While not every program is asynchronous, every program *can* be.
Using sync APIs is better than "sync over async" (`.Result`), but it is not better than properly using async.

**Comment by Mr0N** [comment]
> 

Apparently, due to asynchrony, the program slows down by 20 percent more than without it, if I don't want my program to not do very well, at all 100 percent, what should I do in this case?

**Comment by MihaZupan** [comment]
Can you share the benchmark you used to determine that using sync APIs is 20% faster than using async ones?

**Comment by Mr0N** [comment]
using System.Net;
using System.Net.Http;
using System;
using BenchmarkDotNet.Running;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Jobs;

var summary = BenchmarkRunner.Run<Test>();

Console.ReadKey();
[SimpleJob(RuntimeMoniker.Net60)]
public class Test
{
    private void Set() { }
    [Benchmark]
    public void Get()
    {
        for (int i = 0; i < 100000; i++)
        {
            Set();
        }
    }
    private async Task SetAsync() { }
    [Benchmark]
    public async Task GetAsync() 
    {
        for (int i = 0; i < 100000; i++)
        {
            await SetAsync();
        }
    }
    
}
![image](https://user-images.githubusercontent.com/61237140/189680247-b45cdd16-aaea-44de-87fa-b653eb878271.png)

**Comment by stephentoub** [comment]
That benchmark doesn't include anything to do with HttpClient.  The `Set()` in your benchmark will also be completely removed such that your `Get()` function will be an empty loop.

**Comment by Mr0N** [comment]
> public class Test
> {
>     private void Set() { }
>     [Benchmark]
>     public void Get()
>     {
>         for (int i = 0; i < 100000; i++)
>         {
>             Set();
>         }
>     }
>     private async Task SetAsync() { }
>     [Benchmark]
>     public async Task GetAsync() 
>     {
>         for (int i = 0; i < 100000; i++)
>         {
>             await SetAsync();
>         }
>     }
>     
> }

![image](https://user-images.githubusercontent.com/61237140/189682137-9190e96b-5f28-43d2-bbe6-3ff20658939f.png)
https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQBMCWUA2B7Ac1RgAsIBbTAOwIB8ABAJgEYBYAKHoAYACe5gKwBuDvQDMfRjwAqKGBwDeHHip4AHBJgBusCHwAsPAMoQYACgCUPBTwC+HZavEGeAcVOXHKpe1V+eYHgIPGbUMDyYPAC8PFxCETwAPDzMXGlp8ZgA1FkWXv4+/kXGHhYivsX2FSpVfhraunwAHHwAbCUwAILIAJ5UAMaW1nbK+c70LfTt7l29A0P5hcWBwaFU4ZExcQnJqenb2bn5fkvFTgCcHd19g2XHqrUP+Ry2QA===

**Comment by Mr0N** [comment]
> That benchmark doesn't include anything to do with HttpClient. The `Set()` in your benchmark will also be completely removed such that your `Get()` function will be an empty loop.

and what's the point of HttpClient here, I'm talking about the concept of making the entire program asynchronous

**Comment by stephentoub** [comment]
I'm not sure what that's trying to show.  It'll be removed by the JIT, not the C# compiler:
[SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gVgG4biBmJ0hgFRi4MNAN40GkhgAcoASwBu2DDCYoGAZRgYAFAEoGohgF8aEqdzUMA4tv3nJ46lJcMAZtAY65AOwwM5BgBeBjo2AIYAHgZyOji48LkAaiS9B1cnVyzNOz0OZ2zTAskil1lFZVViAA4mJByMAEFcAE8fMH1DEwl0yxq6m21mto6DdMzsjygvX39AkLCI6Nj4xeTU9JcJ7IsATgbh9v18ndKpM8kaYyA=)
```
Test.Get()
    L0000: xor eax, eax
    L0002: inc eax
    L0004: cmp eax, 0x186a0
    L0009: jl short L0002
    L000b: ret
```

**Comment by stephentoub** [comment]
> and what's the point of HttpClient here, I'm talking about the concept of making the entire program asynchronous

The point is you're asking for synchronous methods on HttpClient, and you claimed that "the program slows down by 20 percent more than without it", so Miha asked for a benchmark showing that your program using HttpClient slows down by 20% when using async rather than sync.

**Comment by Mr0N** [comment]
![image](https://user-images.githubusercontent.com/61237140/189684380-e0433ed9-f9f3-4dd7-a9da-a0b46d981fc4.png)
using System.Net;
using System.Net.Http;
using System;
using BenchmarkDotNet.Running;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Jobs;

var summary = BenchmarkRunner.Run<Test>();

Console.ReadKey();
[SimpleJob(RuntimeMoniker.Net60)]
public class Test
{
    public int setIntSync { set; get; }
    public int setIntAsync { set; get; }
    private void Set() {
        setIntSync++;
    }
    [Benchmark]
    public void Get()
    {
        for (int i = 0; i < 100000; i++)
        {
            Set();
        }
    }
    private async Task SetAsync() {
        setIntAsync++;
    }
    [Benchmark]
    public async Task GetAsync() 
    {
        for (int i = 0; i < 100000; i++)
        {
            await SetAsync();
        }
    }
    
}

**Comment by Mr0N** [comment]
> > and what's the point of HttpClient here, I'm talking about the concept of making the entire program asynchronous
> 
> The point is you're asking for synchronous methods on HttpClient, and you claimed that "the program slows down by 20 percent more than without it", so Miha asked for a benchmark showing that your program using HttpClient slows down by 20% when using async rather than sync. Presumably you were drawing a distinction between `AsyncMethod().Result` and `SyncMethod()`... can you show that benchmark?

it is difficult to conduct such a test

**Comment by Mr0N** [comment]
> ![image](https://user-images.githubusercontent.com/61237140/189684380-e0433ed9-f9f3-4dd7-a9da-a0b46d981fc4.png) using System.Net; using System.Net.Http; using System; using BenchmarkDotNet.Running; using BenchmarkDotNet.Attributes; using BenchmarkDotNet.Jobs;
> 
> var summary = BenchmarkRunner.Run();
> 
> Console.ReadKey(); [SimpleJob(RuntimeMoniker.Net60)] public class Test { public int setIntSync { set; get; } public int setIntAsync { set; get; } private void Set() { setIntSync++; } [Benchmark] public void Get() { for (int i = 0; i < 100000; i++) { Set(); } } private async Task SetAsync() { setIntAsync++; } [Benchmark] public async Task GetAsync() { for (int i = 0; i < 100000; i++) { await SetAsync(); } }
> 
> }

Well, I think that's enough

**Comment by rzikm** [comment]
@Mr0n You do realize that your benchmarks only measure the overhead of calling an async method vs non-async method (if they measure anything). Like Clockwork-Muse said, when you call the actual HttpClient methods, the "overhead" of async call is negligible compared to the implementation of the methods and the network stack underneath.

**Comment by Mr0N** [comment]
> > Well, I think that's enough
> 
> Not really. The problem is that once you get the actual network stack involved, actual IO is going to dominate, so your performance numbers are going to be closer to each other.
> 
> You're also only considering single-task performance. That is, you assume that the number of things your program does is less than the number of threads available to the process, and that you can tie up a thread until the IO completes. This is not a realistic assumption for modern applications, especially for one that touches the network. `async` allows your application to have faster _overall_, whole-application, performance, at a slight per-task cost.

And if I have a lot of resources, and I don’t want to save them, but I want speed? And I don’t want the il code for async to be executed

**Comment by Mr0N** [comment]
> 

yes, I understand, and I want to have a choice of what to save on

**Comment by Clockwork-Muse** [comment]
> And if I have a lot of resources, and I don’t want to save them, but I want speed? And I don’t want the il code for async to be executed

We don't change things for a single unknown customer.
 It is unrealistic for us to assume that the majority of our customers will have the sort of resources you're claiming here.  For that matter, it's likely unrealistic for _you_ to assume your customers have the sort of resources you're claiming as well.  If they do, absent some compelling use-case you haven't yet disclosed, they're most likely better spent by using the capabilities `async` provides.  And if that isn't sufficient, looking at using `ValueTask` and some of the surrounding infrastructure.

As it stands, you still haven't articulated a reasonable explanation or justification for why you want this (that is, you still haven't shown that a synchronous version of actual IO calls has a significant performance gain), or that having this capability improves the  library or meets needs for a sufficient number of customers.

**Comment by Mr0N** [comment]
using System.Net;
using System.Net.Http;
using System;
using BenchmarkDotNet.Running;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Jobs;

//var test = new Test();
//test.Setup();
//Console.ReadKey();
//test.Clear();
//return;
var summary = BenchmarkRunner.Run<Test>();

Console.ReadKey();
[SimpleJob(RuntimeMoniker.Net60)]
public class Test
{
    [GlobalSetup]
    public void Setup()
    {
        listenerAsyncSync = new HttpListener();
        listenerAsyncSync.Prefixes.Add("http://*:5/");
        Task.Run(() =>
        {
            listenerAsyncSync.Start();
            while (listenerAsyncSync.IsListening)
            {
                var result = listenerAsyncSync.GetContext();
                result.Response.OutputStream.WriteByte((byte)222);
                result.Response.Close();
            }
        });
        listenerAsync = new HttpListener();
        listenerAsync.Prefixes.Add("http://*:3/");
        Task.Run(() =>
        {
            listenerAsync.Start();
            while (listenerAsync.IsListening)
            {
               var result = listenerAsync.GetContext();
                result.Response.OutputStream.WriteByte((byte)222);
                result.Response.Close();
            }
        });
        listener = new HttpListener();
        listener.Prefixes.Add("http://*:4/");
        Task.Run(() =>
        {
            listener.Start();
            while (listener.IsListening)
            {
                var result = listener.GetContext();
                result.Response.OutputStream.WriteByte((byte)222);
                result.Response.Close();
            }
        });
        client = new HttpClient();
        clientAsyncSync = new HttpClient();
        clientAsync = new HttpClient();
    }

    HttpClient clientAsyncSync;


    HttpListener listenerAsync;
    HttpListener listenerAsyncSync;

    HttpClient clientAsync;
    HttpListener listener;
    HttpClient client;

    [GlobalCleanup]
    public void Clear()
    {
        client.Dispose();
        clientAsync.Dispose();
        clientAsyncSync.Dispose();
        this.listener.Stop();
        this.listener.Close();
        this.listenerAsync.Stop();
        this.listenerAsync.Close();
    }
    [Benchmark]
    public void Get()
    {
        var message = new HttpRequestMessage(HttpMethod.Get, "http://127.0.0.1:3");
        message.Version = HttpVersion.Version11;
        new StreamReader(client.Send(message).Content.ReadAsStream()).ReadToEnd();
    }
    [Benchmark]
    public async Task GetAsync()
    {
        var message = new HttpRequestMessage(HttpMethod.Get, "http://127.0.0.1:4");
        message.Version = HttpVersion.Version11;
        new StreamReader(await(await clientAsync.SendAsync(message)).Content.ReadAsStreamAsync())
            .ReadToEnd();
    }
    [Benchmark]
    public void GetAsyncSync()
    {
        var message = new HttpRequestMessage(HttpMethod.Get, "http://127.0.0.1:5");
        message.Version = HttpVersion.Version11;
        new StreamReader(clientAsyncSync.SendAsync(message).Result.Content.ReadAsStreamAsync().Result)
            .ReadToEnd();
    }
}
![image](https://user-images.githubusercontent.com/61237140/189720174-ff2ee515-0a6d-4f01-9508-ed3af6c1c2bf.png)

**Comment by Mr0N** [comment]
It turns out better to use the result than the synchronous Send method, it's somehow strange.......
