### ISSUE TITLE
HttpClient crashes app with no error

### ISSUE THREAD

**Issue by eusebiu** [dotnet/runtime#75483]
### Description

Using the sample from https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-6.0 just crashes the app with no error message in either console or Event Viewer.

### Reproduction Steps

Create a console app with VS 2022 17.3.3
Run code from https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-6.0

### Expected behavior

HTTP error/success is returned

### Actual behavior

App crashes with no logs anywhere

### Configuration

.net 6.0.8 (tried also with 3.1.28), Any CPU
OS:
Edition	Windows 10 Enterprise
Version	20H2
Installed on	‎25-‎May-‎22
OS build	19042.1889
Experience	Windows Feature Experience Pack 120.2212.4180.0

**Comment by wfurt** [comment]
It is unlikely the application would crash without any feedback. Can you try it will `dotnet build` & `dotnet run` from command line?

**Comment by eusebiu** [comment]
> It is unlikely the application would crash without any feedback. Can you try it will `dotnet build` & `dotnet run` from command line?

Yes, I thought that too. Ran those commands also, but the same result.

**Comment by karelz** [comment]
Is it happening on more than 1 machine? This is highly suspicious.
Did you try to run it under debugger to see waht is happening? (if VS doesn't show anything, you can try windbg)

**Comment by eusebiu** [comment]
Yes, tried it only on 1 machine under VS debugger.
Will try windbg too...

**Comment by karelz** [comment]
FYI: One machine problems are time consuming to root cause -- especially when they are suspicious.
Based on my experience, it can be anything ranging from installation corruption to HW error. If you want to root cause it, go ahead. We will most likely not invest into it, unless it is confirmed problem on multiple machines.

**Comment by wfurt** [comment]
what `dotnet --info` gives you? I assume the build you give you see feedback ... and that looks right?
You can `set COREHOST_TRACE=1` -> that should give you some insight to runtime initializetion. 

You can also write and run simple "Hello World!" app and check if that runs OK

**Comment by eusebiu** [comment]
```
 dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400\

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  3.1.415 [C:\Program Files\dotnet\sdk]
  6.0.400 [C:\Program Files\dotnet\sdk]

  Microsoft.AspNetCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

Where should I get the logs from COREHOST_TRACE=1?

**Comment by wfurt** [comment]
console
.NET does not log to event log. 
Alternatively you can set `COREHOST_TRACEFILE=trace.txt`

**Comment by eusebiu** [comment]
Nothing is displayed in console and no file is generated in bin/Debug...

**Comment by wfurt** [comment]
that suggest the `dotnet` even does not run. I assume this is same for the "hello world" e.g. this is nit HTTP specific?
cc: @vitek-karas for any more insight how to debug this. Perhaps run it under debugger.

**Comment by eusebiu** [comment]
I know it sounds strange because I cannot believe it myself but still no file. The app is just a console app which outputs in Console if I use the WriteLine(..) method.
```
PS App> set COREHOST_TRACE=1
PS App> set COREHOST_TRACEFILE=host.txt
PS App> .\App.exe
PS App> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614
```

Will try with WinDbg later and come back with the results.

**Comment by vitek-karas** [comment]
Oh - this is in PowerShell - in that case you have to run
```Console
$env:COREHOST_TRACE=1
$env:COREHOST_TRACEFILE="host.txt"
.\App.exe
```

**Comment by eusebiu** [comment]
Now, the file is created - see attached. But it is different than the dotnet --info one (ends differently).
[host.txt](https://github.com/dotnet/runtime/files/9560848/host.txt)

**Comment by vitek-karas** [comment]
`dotnet --info` is special , so don't read too much into the difference :-)

That log is "normal" - there are no errors there, and it says the app started and finished with exit code 0.

Can you try to debug the app - from VS start it by hitting F10 - this should start the program and stop on the first statement. Then you can try to step through it (F10 again) and see what happens.

**Comment by eusebiu** [comment]
I did debug it but when it reaches the httpClient.GetAsync(...), the debugger detaches as the app exists/crashes.

**Comment by fmaeseele** [comment]
Hi,
I have exactly the same issue since I installed latest net7 rc sdk
[sdk-7.0.100-rc.1-windows-x64-installer](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-7.0.100-rc.1-windows-x64-installer)
with the latest Visual Studio 2022 Preview 17.4.0 Preview 2.0

the line which make my application crash with no information at all:
        `var response = await _httpClient.SendAsync(httpRequestMessage);`

This is very high show stopper as I don't know what to do.

**Comment by vitek-karas** [comment]
I tried this locally with RC2 nightly build and it seems to work OK (the example from the original issue above).

Could you please try:
* Run the app from command line - `dotnet run` or similar.
* Run it under the debugger, and ask debugger to stop on all managed exceptions - this can be done by going to the exceptions window and check the Common Language Runtime Exceptions:
<img width="206" alt="image" src="https://user-images.githubusercontent.com/10670590/190398132-2a64d7ab-8515-4d0f-8b92-59e1df738a14.png">

**Comment by eusebiu** [comment]
In my case it did nothing... no stop, no message... just clean exit...

**Comment by fmaeseele** [comment]
For my case, I have the feeling this is due to the uninstallation of .net7 preview7.
After that, my application is crashing whatever I use .Net 7 RC1 or .Net6

**Comment by wfurt** [comment]
You can try to re-install .NET 6 @fmaeseele. Do you get any visible error?

**Comment by fmaeseele** [comment]
Hi,
Like others, I don't have any error.
But, I managed to workaround this issue:
I'm using async Task Main(string[] args) method, with System.CommandLine definitions to managed the app options.

```
    static async Task Main(string[] args)
    {
        .... my argument/options definitions

        rootCommand.SetHandler(
            RunCommand,
            myArg1,
            myArg2);

        await rootCommand.InvokeAsync(args);
   }

Before (cause app to crash while calling httpClient.SendMessageAsync inside the Action):
    static Action<string,string> RunCommand = async (myArg1, myArg2) => {
       ....
       await httpClient.SendMessageAsync(myHttpMessage);
       => Crash the application, instead I expect an UnknownHost exception
    }

After (still calling httpClient.SendMessageAsync inside the method RunCommand but no crash):
    static async Task RunCommand(string arg1, string arg2) {{
       ....
       await httpClient.SendMessageAsync(myHttpMessage);
       => No Crash!! But an expected exception with unknown hostname. 
    }

```

Don't ask me why....

I didn't have this issue 2 days ago before uninstalling .net7 preview7 and installing the new .net7 rc1

:-)

**Comment by eusebiu** [comment]
Hi, Indeed, I also found out that I had a "wrong" signature:
```async Task GetDepartments(IEnumerable<string> users)``` vs ```async void GetDepartments(IEnumerable<string> users)```
and I didn't use await:
```await GetDepartments(ParseUserList("users.txt"));``` vs ```GetDepartments(ParseUserList("users.txt"));```
So, now it works - no more silent exit!

But the behavior is misleading... 

@ dotnet-team - you can close this issue but maybe you should take a look and see why the app is exiting just like that (both in debug and build).

**Comment by wfurt** [comment]
can you post small repro @eusebiu ?
If you miss await, than the application will simply finish and not crash. 
the build _should_ warn you...

**Comment by eusebiu** [comment]
Indeed, it does not crash - it simply exists with no warning in VS2022!
```
    internal class Program
    {
        static void Main(string[] args)
        {
            GetDepartments(ParseUserList("users.txt"));
        }

        private static async void GetDepartments(IEnumerable<string> users)
        {
            var deps = new List<string>();

            await System.IO.File.WriteAllLinesAsync("userdeps.txt", deps);
        }

        private static IEnumerable<string> ParseUserList(string file)
        {
            if (!System.IO.File.Exists(file))
                throw new ArgumentException("users.txt does not exist!");

            return System.IO.File.ReadAllText(file).Split(Environment.NewLine);
        }
    }
```

**Comment by wfurt** [comment]
Oh. This is because you use `void`.  If you change it to 
```c#
        private static async Task GetDepartments(IEnumerable<string> users)
```

you will get the warning.
```
/home/furt/test/Program.cs(7,13): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call. [/home/furt/test/test.c
```
