### ISSUE TITLE
FileNotFoundException for Microsoft.SqlServer.Types 10.0.0.0 when trying to use SQL Server geography data

### ISSUE THREAD

**Issue by nyctef** [dotnet/runtime#75481]
Hopefully this is the right place to post this-

We've been hitting an issue using [System.Data.SqlClient](https://www.nuget.org/packages/System.Data.SqlClient/) through a netstandard2.0 project where Microsoft.SqlServer.Types 10.0.0.0 will fail to load when trying to fetch geography data from SQL Server. I think we can work around this problem by [getting the dll from nuget](https://www.nuget.org/packages/Microsoft.SqlServer.Types/), but since the nuget package only has a `net40` version, this means the project we're installing the nuget package into can't be `netstandard2.0` any more.

I've created an example repo here: https://github.com/nyctef/geography-repro to try and demonstrate the problem - it should crash on machines were Microsoft.SqlServer.Types 10.0.0.0 isn't in the GAC already.

**Comment by David-Engel** [comment]
System.Data.SqlClient is unlikely to ever see support for that Microsoft.SqlServer.Types package. System.Data.SqlClient is in strict maintenance mode and not receiving anything other than critical security and bug fixes. Migrate to Microsoft.Data.SqlClient for the latest features and support.

We have an issue in the SqlClient repo to track the status of spatial support: https://github.com/dotnet/SqlClient/issues/30

Regards,
David
