### ISSUE TITLE
net6-android targets - SslStream connectivity issues with self-signed certificates

### ISSUE THREAD

**Issue by ransagy** [dotnet/runtime#75536]
A continuation of #74066 with a more specific case:

I am trying to use `TcpClient` and `SslStream` in a .NET MAUI application to connect to an endpoint that only has a self-signed certificate by design (Google [Chrome]Cast device auth protocol - The first step is always done with a 24h self refreshing self-signed certificate made by the receiver device - Closest doc i can find is unofficial - https://yingtongli.me/blog/2019/12/20/gcast-auth.html ).

When trying to connect using the `net6-windows` head, there are no issues at all - Since the supplied `ServerCertificateCustomValidationCallback` takes effect and ignores the validation for the certificate.

When trying to connect from the `net6-android` head (deployed as a debug version on a real android device as mDNS/cast discovery does not work in the emulator) the connection failes with an error on the client side that connection has been closed. I have yet to be able to extract information from the server side similarly to the parent issue to see if that's the reason for the connection failure, But it's very likely given the rest of the information so far.

This is an excerpt of what that code does:
```csharp
        TcpClient _client = new();
        await _client.ConnectAsync(ViewModel.SelectedCastDevice.DeviceUri.Host, ViewModel.SelectedCastDevice.Port);
        SslStream secureStream = new(_client.GetStream(), leaveInnerStreamOpen: true, (object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) => true);
        await secureStream.AuthenticateAsClientAsync(ViewModel.SelectedCastDevice.DeviceUri.Host);
```

Which results in the very similar exception stack for the client:

```
[0:] System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.<<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0>d`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Net.Security.SslStream.<ReceiveBlobAsync>d__176`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Net.Security.SslStream.<ForceAuthenticationAsync>d__175`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at Sharpcaster.ChromecastClient.ConnectChromecast(ChromecastReceiver chromecastReceiver)
   at MauiApp1.MainPage.WithSharpCast() in C:\Temp\Experiments\MauiTest\MauiApp1\MainPage.xaml.cs:line 106
   at MauiApp1.MainPage.StartCasting() in C:\Temp\Experiments\MauiTest\MauiApp1\MainPage.xaml.cs:line 95
```

as per @simonrozsival 's comments - This is likely because on android the validation callback is ignored.

Is there any way to make self-signed SSL connections work on net6-android? Are there plans to support/make the callback usable on those targets?

Any suggestions would be welcome.

**Comment by simonrozsival** [comment]
The best way to support self-signed certificates in net6-android apps at the moment is using [`network_security_config.xml`](https://developer.android.com/training/articles/security-config). The problem with that solution is that the app needs to include the CA key during the build. Based on the unofficial docs you mention, I think you could get the _platform certificate_ from the chromecast device using `openssl s_client` and bundle the PEM certificate with the app.

Unfortunately, I don't have an access to a chromecast device so I can't try it myself.

**Comment by ransagy** [comment]
I will give that a try, but i imagine since both certificates are dynamic in nature - The peer one is regenerated constantly and the platform one is per-device - That won't work beyond an isolated test.

So back to the secondary question i guess - Is it feasible and/or planned to make custom validation work or is that simply the nature of Android's security layer and cannot be modified/overriden even with platform-specific code, etc?

**Comment by simonrozsival** [comment]
I see. The solution I suggested might not be suitable for this use case then.

This is a know limitation of .NET 6 on Android and it's tracked here: https://github.com/dotnet/runtime/issues/45741. It's currently assigned to the .NET 8 milestone so hopefully we'll manage to make improvements in this area next year.

**Comment by ransagy** [comment]
I see those specifics are listed under `Not Supported` though, and that is explained as needing to be documented as such; Not specifically that it COULD be implemented. Am i misreading that?

**Comment by ComptonAlvaro** [comment]
@ransagy I have read the documentation that you give how authetication works in google chromecast. It gives code to can authenticate. As MAUI allows to use native code of Android. Could you try to use the implementation of the document in the code for android in the MAUI project?

**Comment by simonrozsival** [comment]
@ransagy You are right, the documentation is incomplete at the moment. The functionality can be implemented, although it will be fairly complicated. There have been several reports from customers who need that functionality so I think we will be looking into in the near future.

**Comment by ransagy** [comment]
@simonrozsival great, i read that initially as "can't be implemented, we just need to update docs to say that". So if it can be, "just" requires the priority/planning/work, that's fine. Would you want me to track that item and close this issue, in that case?

@ComptonAlvaro It's kinda out of scope for both this issue/repo and my problem domain - The code there relies on a very specific scenario of rooting an android device, installing a hook of sorts (Xposed framework) to allow hijacking code calls in real time and replacing them, sort of hot patching. Not really feasible for anything to be ran by an average user/customer.

**Comment by simonrozsival** [comment]
Yes, I think we should close this issue now. Feel free to reopen it or open a new one if you run into some further problems.
