### ISSUE TITLE
Improve test coverage for TLS resume

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#75545]
fix for #75079 did not have test as I was unable to construct one. 
But in general, most tests do verify given behavior once but that may not be sufficient.
The behavior may change because of 
- session cache (primarily windows)
- TLS resume (primarily Linux)

we should add test for  #75079 as well as improve test coverage in general.

**Comment by rzikm** [comment]
Triage:
- Look at the covearge we already have and see if something is missing
- consider adding tests which check if session was actually resumed, there is Debug-only property which we can check via Reflection.

**Comment by rzikm** [comment]
Test covering #75079 was added as part of https://github.com/dotnet/runtime/pull/79898, since then, multiple other changes have explicitly added checks with TLS resume as well, e.g. https://github.com/dotnet/runtime/pull/86047. I don't think there are any missing tests at this point.
