### ISSUE TITLE
[wasm][debugger] Support IEnumerable Visualizer when debugging on wasm

### ISSUE THREAD

**Issue by thaystg** [dotnet/runtime#75552]
Probably we need to send some hint over the protocol to tell VS that may use IEnumerable Visualizer 

This question came from Asp.net community standup.

**Comment by teo-tsirpanis** [comment]
The community standup question in question was referring to multi-dimensional arrays [which do not implement `IEnumerable<T>`](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmABgFgAoUgRmqLIAIjaUBuah2gTgAo8MAO5MAlngwBtWgA40KALpiAzi1oBmADziMAPgCU7IA===). The visualizer does not appear on multi-dimensional arrays in ordinary .NET code either.

Can you try debugging some code on the browser that creates a single-dimensional array on browser and see if it shows this <kbd>🔍View</kbd> button?

![image](https://user-images.githubusercontent.com/12659251/189978303-352899f8-a00c-4c5b-b860-1298ed38ae77.png)

**Comment by thaystg** [comment]
> The community standup question in question was referring to multi-dimensional arrays [which do not implement `IEnumerable<T>`](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmABgFgAoUgRmqLIAIjaUBuah2gTgAo8MAO5MAlngwBtWgA40KALpiAzi1oBmADziMAPgCU7IA===). The visualizer does not appear on multi-dimensional arrays in ordinary .NET code either.
> 
> Can you try debugging some code on the browser that creates a single-dimensional array on browser and see if it shows this 🔍View button?
> 
> ![image](https://user-images.githubusercontent.com/12659251/189978303-352899f8-a00c-4c5b-b860-1298ed38ae77.png)

No 
![image](https://user-images.githubusercontent.com/4503299/189980579-4db27760-fc58-423a-9435-23ab5a7182e7.png)

**Comment by thaystg** [comment]
This is not possible. If we want to support it we need to open an issue for Typescript team. We cannot reuse the Visualizers used by coreclr.
