### ISSUE TITLE
Android: Next Steps

### ISSUE THREAD

**Issue by qmfrederik** [dotnet/runtime#7556]
With dotnet/runtime#7544 resolved, .NET Core on 64-bit Android can now run a basic "Hello World" app.

I'm opening this issue to see what the next steps would be. That would include:
- CI builds (or at least standardized builds which can be used to create NuGet packages)
- Assigning a RID for Android

**Comment by agocke** [comment]
We don't have any current plans to use CoreCLR on Android. Mono is fully supported on Android and iOS and is where we focus our efforts. CoreCLR may work just fine, but we don't plan to support it in infrastructure.
