### ISSUE TITLE
NTLM fails for HTTP only connection

### ISSUE THREAD

**Issue by marcino239** [dotnet/runtime#75579]
### Description

Ntlm authentication fails when connecting to HTTP servers in .Net6.0 .  The typical scenario is that transport is secured by some other means (example IPSec).  In such case .Net6.0 is unable to connect to the server

### Reproduction Steps

```c#
using System.Net;

var host = Host.CreateDefaultBuilder(args);

// https works, but http does not
var uri = new Uri("http://server");
var username = "username";
var password = "password";
var domain = "domain";

var credentialsCache = new CredentialCache();
credentialsCache.Add(uri, "NTLM", new NetworkCredential(username, password, domain));
var handler = new HttpClientHandler() { Credentials = credentialsCache, PreAuthenticate = true};
var httpClient = new HttpClient(handler) { Timeout = new TimeSpan(0, 0, 10) };
var response = await httpClient.GetAsync(uri);

var result = await response.Content.ReadAsStringAsync();
Console.WriteLine(result);
```

### Expected behavior

http connection should be authenticated when using NTLM authentication scheme

### Actual behavior

Runtime throws error that only supported schemes are NTLM or Negotiate without attempting to go through full authentication cycle.  I.e. GET -> 401 -> GET with NTLM -> 200

### Known Workarounds

Https works

### Configuration

Version=.Net 6.0
OS=Ubuntu 20.04
Arch=x64

**Comment by wfurt** [comment]
do you have `gss-ntlmssp` installed? And the subject somehow suggest it works with HTTPS? if not, I don't understand the "HTTP only" part.

It would be useful to get packet capture to see what is going on the wire.

**Comment by wfurt** [comment]
Also note that the way how it is written, it would not work if the sever only offers "Negotiate" scheme. You can try to set the `NetworkCredential` directly as `Credentials`

**Comment by marcino239** [comment]
Hi @wfurt  - thanks for coming back.  To answer your questions:

1. gss-ntlmssp is installed
2. Works: net6 app when connecting to the endpoint like "https://server"
3. Does not work: net6 app when connecting to the endpoint "http://server"
![image](https://user-images.githubusercontent.com/6017403/190142862-ca197e4d-ed5a-4a89-b3bd-3d50cca5bdb1.png)
4. Works: net3.1 app when connecting to the endpoint "http://server" with System.Net.Http.UseSocketsHttpHandler=false
![image](https://user-images.githubusercontent.com/6017403/190142098-2bcf1e9d-1402-47b5-8709-5e03e8c74685.png)
Looks like HttpClient does not retry when auth failes in scenario 3 or maybe the client does not advertise NTLMSSP_NEGOTIATE?

Best Regards,
Marcin

**Comment by wfurt** [comment]
How is the response looks like in case 3? 
It is really hard to see without the pcap file but in the example 4, you get back NTLM challenge but that is missing 3. 
The SocketsHttpHandler does `PreAuthenticate`  only fo basic auth so you should see list of supported mechanisms in the initial 401 response.

**Comment by marcino239** [comment]
Let me mock up a server with NTLM auth and get back to you

**Comment by marcino239** [comment]
Ok, so I did create a mock up server with NTLM using http.sys on Windows and observed the following:

1. Ntlm auth works when using no proxy in HttpClient
2. Ntlm auth works when using Socks5 WebProxy implemented in [PR 48883](https://github.com/dotnet/runtime/pull/48883)
3. Ntlm auth does not work in net6 when using [HttpToSocks5Proxy](https://github.com/MihaZupan/HttpToSocks5Proxy)

Thanks a lot @wfurt for pushing me into the right direction and thanks to @MihaZupan @huoyaoyuan for WebProxy
