### ISSUE TITLE
runtime build should use python3 instead of failing

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#75584]
I was trying to make build on macOS 13 and it failed out of the box while building coreclr:
```
-- Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE)
  CMake Error at pal/src/eventprovider/dummyprovider/CMakeLists.txt:15 (message):
    Failed to generate dummy event provider:

  -- Configuring incomplete, errors occurred!
```

pythons is available as python3. ~~I end-up setting `PYTHON=python3` variable~~ but that should not be necessary IMHO.
For example, Alpine 3.16 has same setup e.g. `python` is gone superseded by `python3`
(I created symbolic link in /usr/bin)

```
furt@macos-13% which python
python not found
furt@macos-13 % which python3
/usr/bin/python3
furt@macos-13 % python3 --version
Python 3.9.6
```

**Comment by danmoseley** [comment]
I don't have a mac to try, but on the face of it it seems to be looking for python3

https://github.com/dotnet/runtime/blob/main/eng/python.targets#L21
