### ISSUE TITLE
use a string inside RegexGenerator attribute 

### ISSUE THREAD

**Issue by developerss** [dotnet/runtime#75583]
`static string GetflllNames { get; set; }
        [RegexGenerator(@"(?!h\.)" + @GetflllNames + @"=flll\(\w+\)\{(.*?)\}", RegexOptions.IgnoreCase)]
        public static partial Regex GetflllPattern();`

when i use it , it give me a error say RegexGeneratorAttribute is maleformed

**Comment by stephentoub** [comment]
Attributes require constant arguments. You can't access a property from an attribute argument.
