### ISSUE TITLE
improve the gc-heap-size counter

### ISSUE THREAD

**Issue by Maoni0** [dotnet/runtime#75580]
currently the gc-heap-size counter is doing this -

`_gcHeapSizeCounter ??= new PollingCounter("gc-heap-size", this, () => ((double)GC.GetTotalMemory(false) / 1_000_000)) { DisplayName = "GC Heap Size", DisplayUnits = "MB" };`

this GetTotalMemory API isn't great - it's (heap size - fragmentation) so it's only useful when combined with the fragmentation. unfortunately we also don't expose fragmentation as an absolutely value but rather as a percentage. so it requires some conversion to get to the actual heap size. it's better to just convert it to by calling the GC.GetGCMemoryInfo API and reading the [HeapSizeBytes](https://docs.microsoft.com/en-us/dotnet/api/system.gcmemoryinfo.heapsizebytes?view=net-6.0#system-gcmemoryinfo-heapsizebytes) it returns.

**Comment by tommcdon** [comment]
@cshung would you be interesting in taking a look?

**Comment by tommcdon** [comment]
We have added new Metrics-based performance counters and believe we have made the requested improvement in that.  Please let us know if that is not true and we will be happy to re-evaluate.
