### ISSUE TITLE
[wasm-mt] Revisit the size of pthread pool for CI

### ISSUE THREAD

**Issue by simonrozsival** [dotnet/runtime#75602]
Current values are:
`pthreadPoolInitialSize` = 7
`pthreadPoolUnusedSize` = 3;

which allows even some very natry threading unit tests to pass.
But WebWorker is expensive resource, especially on Mobile device.
What would be minimum which still works ?

**Comment by pavelsavara** [comment]
`navigator.hardwareConcurrency`

**Comment by pavelsavara** [comment]
- portable timer
- finalizer
- there could be GC workers in sgen, I'm not sure about it
- thread pool, I think there is one "gate" thread and maybe 2 workers
- we may have debugger thread ?
- we may have event pipe thread ?
- we may have sampling profiler ?
