### ISSUE TITLE
E2E scenario: ASP.NET minimal Web API applications can be NativeAOT compiled for size and performance

### ISSUE THREAD

**Issue by samsp-msft** [dotnet/runtime#75621]
We need to grow the list of workloads which are supported by NativeAOT. The target for .NET 8 should be to enable ASP.NET Minimal Web API applications to be supported for compiling for NativeAOT.

This is a follow on from #61231

The developer of those applications should be able to follow the standard patterns supported by minimal APIs, without major changes, such as needing to replace the DI container implementation. Any corner-case limitations should be flagged with compiler errors when the ` <PublishAot>true</PublishAot>` flag is included.

This initiative will be driven by using a set of prototypical sample applications that need to work for NativeAOT. These include:
[ ] https://github.com/DamianEdwards/MinimalApiPlayground/tree/main/src/Todo.Dapper (The dapper ORM, not Dapr)
[ ] https://github.com/DamianEdwards/MinimalApiPlayground/tree/main/src/Todo.EFCore

**Comment by samsp-msft** [comment]
Related Items:
- https://github.com/dotnet/aspnetcore/issues/27384
- #69739
- #44432
- #43543

**Comment by samsp-msft** [comment]
Tagging @davidfowl, @vitek-karas, @agocke, @MichalStrehovsky, @jkotas, @eerhardt

**Comment by tommcdon** [comment]
Related diagnostic items:
- https://github.com/dotnet/runtime/issues/43390
- https://github.com/dotnet/runtime/issues/56154

**Comment by agocke** [comment]
Closing as the top-line goals for this are completed.
