### ISSUE TITLE
bug in IRootFunctions double.Hypot

### ISSUE THREAD

**Issue by c-ohle** [dotnet/runtime#75651]
### The double.Hypot function returns negative results.

`public static double Hypot(double x, double y) `
It is in the line `result = x + y;` where the abs values should be used.

Just as note: I've found that the algorithm used is less precise and slower than a common implementation.

### Reproduction Steps

```csharp
  x = double.Hypot(1, +1e20); // 1E+20 ok
  x = double.Hypot(1, -1e10); // 1E+10 ok
  x = double.Hypot(1, -1e20); // -1E+20 wrong
```

### Expected behavior

```csharp
  x = double.Hypot(1, +1e20); // 1E+20 ok
  x = double.Hypot(1, -1e10); // 1E+10 ok
  x = double.Hypot(1, -1e20); // 1E+20 
```

### Actual behavior

```csharp
  x = double.Hypot(1, +1e20); // 1E+20 ok
  x = double.Hypot(1, -1e10); // 1E+10 ok
  x = double.Hypot(1, -1e20); // -1E+20 wrong
```

**Comment by jeffhandley** [comment]
This will be considered for backporting to 7.0 since it's a bug in new 7.0 functionality.

**Comment by c-ohle** [comment]
Is it ok if I report the other NET7 numeric bugs I've found as a collection in a case list with no detailed explanation for each case? 
It would save a lot of time.

**Comment by tannergooding** [comment]
We need reproduction steps for each of the cases that have bugs so that regression tests can be added.

Not providing them will cause it to take more time overall to get the fix in and risk the fix not making it into .NET 7 RTM.

**Comment by c-ohle** [comment]
@tannergooding ok, next week.
