### ISSUE TITLE
System.NullReferenceException when using System.Speech 7.0.0-rc.1.22426.10 from Windows Forms 

### ISSUE THREAD

**Issue by Shkyrockett** [dotnet/runtime#75667]
### .NET version

.NET 7.0.0

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

.NET 6.0.0

### Issue description

When trying to use the latest version of [System.Speech](https://www.nuget.org/packages/System.Speech) from Windows Forms, it throws a System.NullReferenceException while trying to access the SpeechSynthesizer class.  

### Steps to reproduce

Run the attached project and click the button.

```csharp
        private void Button_Click(object sender, EventArgs e)
        {
            label.Text = string.Empty;
            using var speech = new SpeechSynthesizer();

            // System.Speech 7.0.0-rc.1.22426.10 throws System.NullReferenceException exception here.
            speech.SetOutputToDefaultAudioDevice();
            speech.SelectVoiceByHints(VoiceGender.Female);
            speech.SpeakProgress += (sender, e) => { label.Text += $"{e.Text} "; };

            speech.Speak("This is a test of the SpeechSynthesizer class.");

            label.Text += "\r\nFinished speaking...\r\n";
        }
```

Expected: The speech synthesizer should read out the contents of the string.

Actual: Accessing the newly created speech SpeechSynthesizer object throws a System.NullReferenceException exception.

Repro project:
[WinFormsSpeechRepro.zip](https://github.com/dotnet/winforms/files/9570983/WinFormsSpeechRepro.zip)

**Comment by stephentoub** [comment]
> I am afraid I can't repro the issue

I can't either.

@jkoritzinsky, does anything in marshaling ring a bell here for an issue that may have existed but has since been fixed?

**Comment by danmoseley** [comment]
@Shkyrockett Does 6.0 work on the exact same machine/configuration today? That would exclude a change to the OS/drivers between when you tested 6.0 and you tried 7.0.

Also, could you install earlier 7.0 previews and help us narrow down when it broke for you?

**Comment by jkoritzinsky** [comment]
I don't know why it isn't reproing, but I think I found the bug.

https://github.com/dotnet/runtime/blob/bfcd16bd851f78a138f927e648887129d519039e/src/libraries/Common/src/Interop/Windows/WinMm/Interop.waveOutGetDevCaps.cs#L53

We aren't checking if `managed.szPname` is `null`, and the following call passes a default instance by-ref (so the `szPname` field would be null):
https://github.com/dotnet/runtime/blob/983c8f239a98812498d874ed36b7001bd764fdfe/src/libraries/System.Speech/src/Internal/Synthesis/AudioDeviceOut.cs#L314

I'll put out a PR very soon.

**Comment by danmoseley** [comment]
Thanks @jkoritzinsky. Was this due to something we changed recently? It wasn't speech. Maybe c99b5b067cf438a9b718f432876fe3e7b095b889

**Comment by jkoritzinsky** [comment]
Yes, when we moved to source-generated marshalling, we manually wrote the new marshaller here that had the bug. Beforehand, the marshaller was generated by the runtime.

**Comment by jkoritzinsky** [comment]
Reopening to track the fix in .NET 7.0

**Comment by stephentoub** [comment]
@Shkyrockett, thanks for the bug report and helping us to get this fixed.

**Comment by Shkyrockett** [comment]
> @Shkyrockett Does 6.0 work on the exact same machine/configuration today? That would exclude a change to the OS/drivers between when you tested 6.0 and you tried 7.0.
> 
> Also, could you install earlier 7.0 previews and help us narrow down when it broke for you?

It stopped working in System.Speech 7.0.0-preview.7.22375.6, The Windows Forms .NET version number does not matter.

On the same machine running the code found in #69776 with System.Speech 7.0.0-rc.1.22426.10 from a console application works perfectly.

**Comment by danmoseley** [comment]
The fix should be in RC2 - it would be great if you could check that when it comes out a month from now.

**Comment by Shkyrockett** [comment]
Since the changes look like they are confined to the System.Speech library in the System.Speech NuGet package; would there happen to be a public nightly feed that could be tested against?

**Comment by danmoseley** [comment]
@jkoritzinsky  could you point to how?

**Comment by jkoritzinsky** [comment]
An RC2 package with the fix is building now. I'll add a comment with instructions on how to pull it down once the pipeline finishes.

**Comment by jkoritzinsky** [comment]
@Shkyrockett You can use version `7.0.0-rc.2.22466.3` of the System.Speech package from the https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json package feed. That package has the fix.

**Comment by Shkyrockett** [comment]
Confirmed fixed in System.Speech 7.0.0-rc.2.22466.3.

**Comment by danmoseley** [comment]
Thanks @Shkyrockett . Just curious what do you use speech for in your app?

**Comment by Shkyrockett** [comment]
So far just a fun hobby project converting English to Deseret through IPA by replacing the IPA phonemes with the equivalent characters from the Deseret alphabet. I use the speech synthesizer to read out the English and IPA text to hear the differences.
