### ISSUE TITLE
dotnet command line argument --additional-deps (Windows and mac)

### ISSUE THREAD

**Issue by anil-shrestha** [dotnet/runtime#75670]
### Description

dotnet version 6.0.400

In windows --additional-deps does not support wildcard while in mac wildcard is working. Please suggest.

In windows following command does not work
dotnet --additional-deps C:\deps\*.deps.json consoleapp.dll

while following command works
dotnet --additional-deps C:\deps\mydeps.deps.json consoleapp.dll

while in mac following command works
dotnet --additional-deps /deps/*.deps.json consoleapp.dll

### Reproduction Steps

In windows :
dotnet --additional-deps C:\deps\*.deps.json consoleapp.dll

In mac:
dotnet --additional-deps /deps/*.deps.json consoleapp.dll

### Expected behavior

It should pick all the deps file from the location specified in --additional-deps argument

### Actual behavior

It should only works in mac. In windows, only single file is working.

### Configuration

dotnet version 6.0.400

**Comment by anil-shrestha** [comment]
@elinor-fung Thank you for the reply.
You are right. It is indeed expanding to single file.

I am trying host this application in IIS where I am sending --additional-deps in arguments attribute in web.config.

I want to add new deps.json file but if I change in web.config, application will restart. I want to do it without application restart. Is there any way to achieve that?

**Comment by elinor-fung** [comment]
The deps.json file(s) only get read at the start of the application. There isn't a mechanism to apply another deps.json to the set of application dependencies after startup.

What is your scenario where you want a new deps.json file while the application is running?

For the dynamically loaded components/plugins scenario, there is [`AssemblyDependencyResolver`](https://learn.microsoft.com/dotnet/api/system.runtime.loader.assemblydependencyresolver) which will resolve paths to dependencies using the deps.json next to the component - and then you can do what you need with those paths.

**Comment by anil-shrestha** [comment]
@elinor-fung Thank you. 

I am trying to load dependencies dynamically during runtime which is similar to plugin. 

I'll look into AssemblyDependencyResolver.

**Comment by elinor-fung** [comment]
Got it. I think `AssemblyDependencyResolver` should put you on the right path. I'm going to close this particular issue then.

@anil-shrestha please do open new issues with any questions or problems you encounter as you look into APIs like `AssemblyDependencyResolver`.
