### ISSUE TITLE
Consider setting hostRequirements for Codespaces

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#75680]
Today, if I go to the `dotnet/runtime` repository to create a Codespace with the default configuration from the Code button (without clicking the chevron):

<img width="30%" alt="image" src="https://user-images.githubusercontent.com/361677/190438187-2e32b09e-e518-4471-a2c9-676b06d56d8b.png">

This will create a codespaces with 2 cores and 4 GB of RAM. Even with a pre-built container, this offers a somewhat rough experience. Between the VS Code and server-side extensions using some resources, running `./dotnet.sh test src/libraries/System.Security.Cryptography/tests` will OOM.

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/361677/190440850-3d790137-519f-4c2f-9479-c48c54a02315.png">

While it would be nice if things worked in this configuration for folks that want to use the lowest possible billing rate, the frequent OOMs I encountered while using this configuration make me think we need to set a floor on the Codespaces configuration.

You can do this with the `hostRequirements` section in `.devcontainer/devcontainer.json`. I am proposing we add this:

```json
"hostRequirements": {
   "cpus": 4,
   "memory": "8gb"
}
```

Folks can always change the specs after they create the codespaces, but it just ends up in a little bit of wasted time and friction trying to do it with the minimum spec.

Documentation on is available [on our docs](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/setting-a-minimum-specification-for-codespace-machines).

/cc @eerhardt

**Comment by eerhardt** [comment]
I'm updating the Codespaces configuration with https://github.com/dotnet/runtime/pull/74683. I can include this change in there as well.
