### ISSUE TITLE
Massive failure tvOS - System.Xml

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#75697]
- 9/14 Rolling run [17272](https://runfo.azurewebsites.net/view/build/?number=17272)
    - 1,635x failures

```
System.ExecutionEngineException : Attempting to JIT compile method '(wrapper dynamic-method) void object:Execute (System.Xml.Xsl.Runtime.XmlQueryRuntime)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by karelz** [comment]
Happened only once, but the number of failures is making build analysis super-annoying. Marking as blocking-clean-ci

**Comment by danmoseley** [comment]
https://github.com/dotnet/runtime/issues/75699 ?

**Comment by steveisok** [comment]
> #75699 ?

Yes, that is the issue.

**Comment by danmoseley** [comment]
closing as dupe...
