### ISSUE TITLE
[wasm] Perf regression of Span.IndexOf

### ISSUE THREAD

**Issue by radekdoulik** [dotnet/runtime#75709]
The performance of `Span`'s `IndexOf` got worse with https://github.com/dotnet/runtime/pull/73768 on wasm.

Visible in https://github.com/dotnet/perf-autofiling-issues/issues/7981, https://github.com/dotnet/perf-autofiling-issues/issues/7976 and here:
![image](https://user-images.githubusercontent.com/4147484/190492419-3a08febd-38d0-4b55-88b5-6bfaf1575a50.png)

I think what is happening is that after the change we end up calling a shared generic method in the span helper, instead of an inflated one.

Stack trace before:
```
$corlib_System_SpanHelpers_IndexOf_byte__byte_int (dotnet.wasm:0x64acc)
$Wasm_Browser_Bench_Sample_Sample_SpanTask_IndexOfByte_RunStep (dotnet.wasm:0x4bddf0)
invoke_vii (dotnet.js:7557)
$Wasm_Browser_Bench_Sample_BenchTask_Measurement__RunBatchd__13_MoveNext (dotnet.wasm:0x4c0162)
...
```
after:
```
$corlib_System_SpanHelpers_IndexOfValueType_TValue_BYTE_TNegator_INST_TValue_BYTE__TValue_BYTE_int (dotnet.wasm:0x66aca)
$Wasm_Browser_Bench_Sample_Sample_SpanTask_IndexOfByte_RunStep (dotnet.wasm:0x4f9be2)
invoke_vii (dotnet.js:7557)
$Wasm_Browser_Bench_Sample_BenchTask_Measurement__RunBatchd__13_MoveNext (dotnet.wasm:0x4fbf53)
...
```

**Comment by lewing** [comment]
discussion happening at https://github.com/dotnet/runtime/issues/74395

**Comment by vargaz** [comment]
One possible cause:
https://github.com/dotnet/runtime/issues/75801

**Comment by stephentoub** [comment]
Reopening to track 7.0 fix

**Comment by marek-safar** [comment]
Closing as the 7.0 fix was merged
