### ISSUE TITLE
Make Sure LLVM Zero Extends Word in JIT Mode

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#75712]
LLVM doesn't zero extend words, but JIT expects it. This is a problem when using a mixture of AOT and JIT. Right now we have a work around in place to always zero extend if there is a possibility the architecture *might* use llvm: https://github.com/dotnet/runtime/blob/f723d4630d2465bd9a90618e172af4bb2ba1588d/src/mono/mono/mini/method-to-ir.c#L2235

 but this has caused some perf regressions:

https://github.com/dotnet/perf-autofiling-issues/issues/8355
https://github.com/dotnet/perf-autofiling-issues/issues/8361

**Comment by SamMonoRT** [comment]
cc @BrzVlad

**Comment by vargaz** [comment]
LLVM generated code will only uses the lower bits of return registers. So the only way to force llvm to zero extend them if to change the return types to 32/64 bits. That would slow down llvm generated code.

**Comment by jandupej** [comment]
The regressions on the JIT side are mostly up to 20 %, with a few benchmarks slowed down up to 2x. (The worst benchmark has recovered, though.) At the time `mono_emit_widen_call_res` is called, we do not know yet if the callee will fail LLVM compilation, so we cannot optimize the zero-extension there. Having LLVM always zero-extend would hurt performance, like @vargaz noted. A majority of methods successfully compile with LLVM, so I think the zero extension code is correctly placed on the JIT-side. Closing.
