### ISSUE TITLE
Improve LoggerMessageGenerator parser to check for invalid partial method body when LoggerMessageAttribute is on method definition

### ISSUE THREAD

**Issue by weichch** [dotnet/runtime#75731]
### Description

In this PR #75601, there is discussion about adding tests to check for invalid method body for the below scenarios: 

**Invalid method body**

```
[LoggerMessage(EventId = 0, Level = LogLevel.Debug, Message = "M1")]
static partial void M1(ILogger logger);

static partial void M1(ILogger logger) { }

```

**Invalid method with expression body**

```
[LoggerMessage(EventId = 0, Level = LogLevel.Debug, Message = "M1")]
static partial void M1(ILogger logger);

static partial void M1(ILogger logger) => throw new Exception();
```

Currently, `LoggerMessageGenerator.Parser` does not generate any diagnostics for all of the above scenarios because the [checks are only performed on methods with the `LoggerMessageAttribute` applied](https://github.com/dotnet/runtime/blob/9028dc2d715a827a21a5ffbd029bc7a24073406b/src/libraries/Microsoft.Extensions.Logging.Abstractions/gen/LoggerMessageGenerator.Parser.cs#L102) in a `foreach`.

User will see a [CS0756 compile error](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0756) due to multiple of implementations generated.

### Reproduction Steps

Generate logging method for the below class:

```
partial class C
{
    [LoggerMessage(EventId = 0, Level = LogLevel.Debug, Message = "M1")]
    static partial void M1(ILogger logger);

    static partial void M1(ILogger logger) { }
}
```

or 

```
partial class C
{
    [LoggerMessage(EventId = 0, Level = LogLevel.Debug, Message = "M1")]
    static partial void M1(ILogger logger);

    static partial void M1(ILogger logger) => throw new Exception();
}
```

### Expected behavior

An invalid body diagnostic should be generated.

### Actual behavior

No diagnostic generated, instead a compile error is seen.

### Known Workarounds

Add/move the `LoggerMessageAttribute` to the method with body.

**Comment by tarekgh** [comment]
The current behavior is acceptable as the compiler will error telling there are two bodies for the same method and users can easily fix the error.
