### ISSUE TITLE
[NativeAOT] Handle variable page size on Linux Arm64

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#75737]
Linux Arm64 can run with 64kB pages. More context: https://github.com/dotnet/runtime/pull/75513#issuecomment-1248756877 and https://github.com/dotnet/runtime/pull/75513#issuecomment-1248798080

**Comment by tmds** [comment]
fyi, RHEL 8 arm64 has 64kB pages.

cc @omajid
