### ISSUE TITLE
STJ deserializes DateTime with Kind set to DateTimeKind.Unspecified when no time zone information is provided

### ISSUE THREAD

**Issue by collinstevens** [dotnet/runtime#75739]
### Description

System.Text.Json deserializes DateTime with Kind set to DateTimeKind.Unspecified when no time zone information is provided.

As far as I can tell, without access to ISO 8601-1:2019, if a time zone information is provided, the date and time should be assumed as the local time of the machine.

https://github.com/dotnet/runtime/blob/4cf1383c8458945b7eb27ae5f57338c10ed25d54/src/libraries/System.Text.Json/src/System/Text/Json/JsonHelpers.Date.cs#L71

Although, if you deserialize a DateTimeOffset, without time zone information, the date and time is assumed as the local time of the machine.

https://github.com/dotnet/runtime/blob/4cf1383c8458945b7eb27ae5f57338c10ed25d54/src/libraries/System.Text.Json/src/System/Text/Json/JsonHelpers.Date.cs#L95

### Reproduction Steps

```csharp
[Theory]
[InlineData("2019-04-24T14:50:17.101")]
public void ShouldSetKindToUnspecified(string value)
{
    // Arrange
    var json = $"\"{value}\"";

    // Act
    var dateTime= JsonSerializer.Deserialize<DateTime>(json);

    // Assert
    Assert.Equal(DateTimeKind.Unspecified, dateTime.Kind);
}
```

### Expected behavior

DateTime.Kind should be set to DateTimeKind.Local

### Actual behavior

DateTime.Kind is set to DateTimeKind.Unspecified

### Configuration

.NET SDK 6.0.304

**Comment by danmoseley** [comment]
What does Newtonsoft do?

**Comment by collinstevens** [comment]
> What does Newtonsoft do?

It exhibits the same behavior.

**Comment by Clockwork-Muse** [comment]
>  the date and time should be assumed as the local time of the machine.

... which may not exist, such as during daylight savings time (ie, the value returned would be an "invalid" `DateTime`).  Maybe that's why?  Note that the BCL has no built-in way to resolve/adjust the time in such a case.

`DateTimeOffset` somewhat gets a pass because there can be a time at that offset, regardless of whether there's any zone with that local time.

This is besides the fact that such a use is inherently dangerous in a web/communications format, because the local zone of the other end of the channel is almost certainly not yours...

**Comment by collinstevens** [comment]
@Clockwork-Muse I think I'm misunderstanding what you're trying to explain. I don't know what you mean when the local time of the machine may not exist.

On my machine, the local time zone is Mountain Standard Time and .NET shows the `BaseUtcOffset` property as "-07:00:00". This is the standard offset, not the daylight savings offset, which is "-06:00:00", although this is still the correct time zone.

Yet, I can still retrieve a DateTime from the DateTimeOffset as I would expect in the following snippet.

```
[Fact]
public void ShouldReturnLocalDateTimeInDaylightSavings()
{
    // Arrange
    var utcDateTimeOffset = DateTimeOffset.UtcNow;
    var localDateTimeOffset = DateTimeOffset.Now;
    
    var timeZone = TimeZoneInfo.Local;
    var standardOffset = timeZone.BaseUtcOffset;
    var daylightSavingsOffset = timeZone.GetUtcOffset(DateTime.UtcNow);
    
    Assert.Equal(TimeSpan.Parse("-07:00:00"), standardOffset);
    Assert.Equal(TimeSpan.Parse("-06:00:00"), daylightSavingsOffset);

    // Act
    var dateTime = utcDateTimeOffset.LocalDateTime;
    
    // Assert
    Assert.Equal(DateTimeKind.Local, dateTime.Kind);
    Assert.Equal(daylightSavingsOffset, localDateTimeOffset.Offset);
}
```

The deserialization of DateTime happens by deserializing the JSON as DateTimeOffset and then creating the DateTime from the DateTimeOffset.

https://github.com/dotnet/runtime/blob/4cf1383c8458945b7eb27ae5f57338c10ed25d54/src/libraries/System.Text.Json/src/System/Text/Json/JsonHelpers.Date.cs#L41-L72

We can see it return `LocalDateTime` off of the DateTimeOffset as my tests do at the top, my bug report is around that we only do this in the case where time zone information is provided when the specification, as far as I can tell, says to assume the time of local machine if it isn't provided.

**Comment by eiriktsarpalis** [comment]
> my bug report is around that we only do this in the case where time zone information is provided when the specification, as far as I can tell, says to assume the time of local machine if it isn't provided.

What specification are you referring to? Parsing dates without a UTC offset will produce `DateTimeKind.Unspecified` whether using the `DateTime.Parse` method, Json.NET or System.Text.Json. 

> Yet, I can still retrieve a DateTime from the DateTimeOffset

A local DateTime can be safely inferred from a DateTimeOffset instance, since the latter represents an absolute point in time, likewise with ISO date strings containing a UTC offset. The same cannot be said for date strings lacking a UTC offset, since they might have been produced by machines in other TZs. It is therefore right that no attempt should be made to convert to the local timezone, and the value is labeled as `DateTimeKind.Unspecified`.

I'd be inclined to close this as by-design behavior, and because changing this now would be a breaking change and diverge from established behavior in other components.

**Comment by collinstevens** [comment]
> What specification are you referring to?

I'm referring to ISO 8601-1:2019 which is documented as how System.Text.Json `JsonSerializer, Utf8JsonReader, Utf8JsonWriter, and JsonElement types parse and write DateTime and DateTimeOffset text representations`.

> It is therefore right that no attempt should be made to convert to the local timezone

I'm sorry, but I'm very confused by this statement from reading the source of System.Text.Json; from what I can tell, we're not inferring a local DateTime from a DateTimeOffset from an ISO date string with a UTC offset. It seems to _explicitly_ state it creates a DateTime with the DateTimeKind set as Local from the raw data if an offset wasn't present.

Please see the following code snippets and I think it will make it clear where the confusion is coming from.

https://github.com/dotnet/runtime/blob/4cf1383c8458945b7eb27ae5f57338c10ed25d54/src/libraries/System.Text.Json/src/System/Text/Json/JsonHelpers.Date.cs#L94-L95

https://github.com/dotnet/runtime/blob/4cf1383c8458945b7eb27ae5f57338c10ed25d54/src/libraries/System.Text.Json/src/System/Text/Json/JsonHelpers.Date.cs#L467-L491

**Comment by eiriktsarpalis** [comment]
> from what I can tell, we're not inferring a local DateTime from a DateTimeOffset from an ISO date string with a UTC offset.

`DateTimeOffset` doesn't convert to a local timezone on deserialization because it doesn't need to; the type largely has a 1:1 correspondence with ISO date representations so no information is lost when mapping to the deserialized instance. The local date can be safely obtained using the [`ToLocalDate`](https://docs.microsoft.com/en-us/dotnet/api/system.datetimeoffset.tolocaltime?view=net-6.0) method if so required.

The same cannot be said for `DateTime`, since projecting a full ISO date results in loss of information. As such, the deserializer will opportunistically make the conversion where it can, consider:
```C#
string jsonDate = "\"2022-09-16T11:22:56.8799552+05:00\"";
DateTime value = JsonSerializer.Deserialize<DateTime>(jsonDate);
Console.WriteLine(value.Kind); // Local
```
But it won't do so if a UTC offset is missing. It will mark the instance as unspecified to convey the ambiguity:
```C#
string jsonDate = "\"2022-09-16T11:22:56.8799552\"";
DateTime value = JsonSerializer.Deserialize<DateTime>(jsonDate);
Console.WriteLine(value.Kind); // Unspecified
```
NB this differs from `DateTimeOffset`, since the type doesn't include a concept of unspecified datetimes. As such, the deserializer will map the datetime to the offset of the local timezone:
```C#
string jsonDate = "\"2022-09-16T11:22:56.8799552\"";
DateTimeOffset value = JsonSerializer.Deserialize<DateTimeOffset>(jsonDate);
Console.WriteLine(value);
```

> Please see the following code snippets

It might more helpful if you could share deserialization examples of your own, highlighting expected vs. actual behavior.

**Comment by danmoseley** [comment]
It may be that deserialization is happening on a server, which you generally want to be oblivious to its own local time and instead use the client's.

**Comment by collinstevens** [comment]
> It might more helpful if you could share deserialization examples of your own, highlighting expected vs. actual behavior.

The below shows a section of asserts which pass, the actual behavior, and a an assert which fails, the expected behavior.

I _expected_ the assert which fails to pass because the [documentation](https://docs.microsoft.com/en-us/dotnet/standard/datetime/system-text-json-support#support-for-the-iso-8601-12019-format) says it implements [ISO 8601-1:2019](https://www.iso.org/standard/70907.html), which from what I can tell, states date and times are the local time zone of the machine if no time zone information provided.

I understand there is a lossy conversion from a DateTimeOffset to a DateTime and I don't disagree that it is probably bad to assume the local time zone of the machine.

Although if the [.NET documentation](https://docs.microsoft.com/en-us/dotnet/standard/datetime/system-text-json-support#support-for-the-iso-8601-12019-format) is stating it implements the parsing according to the [ISO 8601-1:2019 specification](https://www.iso.org/standard/70907.html), I would expect parsing DateTimes to be parsed as Local even though it probably makes much more sense to be Unspecified.

```csharp
[Theory]
[InlineData("2022-01-01T00:00:00.000")] // Mountain Standard Time
[InlineData("2022-04-01T00:00:00.000")] // Mountain Daylight Time
public void ShouldNotSetDateTimeKindEqualToDateTimeKindFromToLocalTime(string value)
{
    // Arrange
    var json = $"\"{value}\"";

    // Act
    var dateTime = JsonSerializer.Deserialize<DateTime>(json);
    var dateTimeOffset = JsonSerializer.Deserialize<DateTimeOffset>(json);
    var dateTimeFromDateTimeOffset = dateTimeOffset.LocalDateTime;
    
    // Assert - Passes
    Assert.Equal("Mountain Standard Time", TimeZoneInfo.Local.StandardName);
    Assert.Equal("Mountain Daylight Time", TimeZoneInfo.Local.DaylightName);
    Assert.Equal(DateTimeKind.Unspecified, dateTime.Kind);
    Assert.Equal(DateTimeKind.Local, dateTimeFromDateTimeOffset.Kind);
    Assert.NotEqual(dateTime.Kind, dateTimeFromDateTimeOffset.Kind);
    Assert.Equal(dateTime, dateTimeFromDateTimeOffset);
    
    // Assert - Fails
    Assert.Equal(DateTimeKind.Local, dateTime.Kind);
}
```

**Comment by eiriktsarpalis** [comment]
> I _expected_ the assert which fails to pass because the [documentation](https://docs.microsoft.com/en-us/dotnet/standard/datetime/system-text-json-support#support-for-the-iso-8601-12019-format) says it implements [ISO 8601-1:2019](https://www.iso.org/standard/70907.html), which from what I can tell, states date and times are the local time zone of the machine if no time zone information provided.

AFAICT the spec doesn't state this. While it does define a notion of "Local time of day" (section 5.3.2) it doesn't clarify or mandate relative to what machine/TZ that date is local in. It almost certainly is local relative to the machine that _generated_ the date string but might not be local relative to the machine that deserializes it. On the other hand, `DateTimeKind.Local` always signifies dates that are local relative to the current machine, and as such `DateTime.Parse`, Json.NET and System.Text.Json are correct in marking parsed date strings without offsets as ambiguous vis a vis their timezone.

**Comment by eiriktsarpalis** [comment]
Tagging @tarekgh since this is not an issue specific to System.Text.Json

**Comment by collinstevens** [comment]
> AFAICT the spec doesn't state this. While it does define a notion of "Local time of day" (section 5.3.2) it doesn't clarify or mandate relative to what machine/TZ that date is local in.

Unfortunately I don't have access to the entire specification, I only have the [reference listed on Wikipedia](https://web.archive.org/web/20171020084445/https://www.loc.gov/standards/datetime/ISO_DIS%208601-1.pdf).

Reading through section 4.2.2 and it's subsections it appears to me this scenario falls under the bolded within 4.3.2.

<pre><b>The zone designator is empty if use is made of local time in accordance with 4.2.2.2 through 4.2.2.4</b>, it is
the UTC designator [Z] if use is made of UTC of day in accordance with 4.2.4 and it is the difference-
component if use is made of local time and the difference from UTC in accordance with 4.2.5.2.</pre>

Interestingly, 4.2.2.1 calls out the following:

<pre>
In the representations of local time as defined below no provisions have been made to prevent
ambiguities in expressions that result from discontinuities in the time scale of local time (e.g. daylight
saving time). When an application identifies the need to prevent these ambiguities, use can be made of
the provision of 4.2.5.2.
</pre>

While there is no explicit statement of which local time zone should be used, I can only read it as though it must mean the local time zone of the actor parsing an ISO 8601-1:2019 string.
