### ISSUE TITLE
Proxy doesn't authenticate on .NET 6

### ISSUE THREAD

**Issue by aov-mx** [dotnet/runtime#75745]
### Description

I'm working on an issue where a customer cannot authenticate into their proxy. I don't have access to their machine but I have been able to run a few tests and that's what I've found:

1. This is not an issue on .NET Framework 4.8 (it works), but it is an issue on .NET 6
2. `netsh winhttp show proxy` returns "Direct access (no proxy server)" for this customer
3. `WinHttpGetIEProxyConfigForCurrentUser` and `WinInetProxyHelper` return valid proxy information
4. The only handler that works is `WinHttpHandler`, only when `WindowsProxyUsePolicy` is set to `UseWinInetProxy`
5. I have tried manually creating a `WebProxy` instance and assigning it to both `SocketsHttpHandler` and `WinHttpHandler`, but it doesn't work
6. I have tried using reflection to create an instance of `HttpWindowsProxy` and using it as a custom proxy but it doesn't work either
7. ...
8. I'm out of ideas

### Reproduction Steps

_Prerequisites_: Have a proxy (it is clearly a very special setup) with authentication enabled

1. Create a `SocketsHttpHandler`
2. Set `UseProxy = true` and `DefaultProxyCredentials` to the correct credentials
3. Make a request

\- or -

1. Create a `SocketsHttpHandler`
2. Set `Proxy` to a custom `WebProxy` instance
3. Make a request

\- or -

1. Create a `WinHttpHandler`
2. Set `WindowsProxyUsePolicy` to `UseCustomProxy`
3. Set `Proxy` to a custom `WebProxy` instance
4. Make a request

### Expected behavior

The request succeeds.

### Actual behavior

```
System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

- or -

System.Net.Http.WinHttpException: Error 12002 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The operation timed out'.
```

### Regression?

Yes, from .NET Framework

### Known Workarounds

Use `WinHttpHandler` with `WindowsProxyUsePolicy = UseWinInetProxy`

### Configuration

.NET 6.0 (all versions)
Windows 10 21H2 / Windows 11 21H2
x64
It is specific to that customer's proxy configuration, but we've seen more complaints from other customers

**Comment by wfurt** [comment]
From the logs, it seems like the client is failing to connect to the proxy. Check that your `WebProxy` is right including port. 
And get packet captures with Wireshark to see what his going on on network.

**Comment by aov-mx** [comment]
Hi @wfurt , thanks for the response.

I've tried creating a `HttpWindowsProxy` instance using the `HttpWindowsProxy.TryCreate` method and then assigning it to the `Proxy` property of both `SocketsHttpHandler` and `WinHttpHandler` (with the latter's `WindowsProxyUsePolicy` and set to `UseCustom`), to no avail.

I haven't tried creating a new `WebProxy` using the data I got from `WinInetProxyHelper` / `WinHttpGetIEProxyConfigForCurrentUser`. Do you think it's worth trying, given that `HttpWindowsProxy` fails?

> get packet captures with Wireshark to see what his going on on network

As I mentioned, I don't have access to the customer's machine so I cannot do it on my own, but I can try to ask the customer to collect the logs. I can't promise it will be possible though.

**Comment by wfurt** [comment]
There is not enough details to make this actionable. From the posted message it does not seems like it is failing to authenticate but it is failing to even connect. 

You can read old https://github.com/dotnet/runtime/issues/23811 and https://github.com/dotnet/runtime/issues/24755 for background.

**Comment by karelz** [comment]
Triage: We do not have actionable information, closing for now. If/when you have something actionable for us (a repro or wireshark traces), please reopen the issue. Thanks!
