### ISSUE TITLE
Port CoreCLR PAL to linux-riscv64

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#75749]
The first component in [coreclr port](https://github.com/dotnet/runtime/blob/main/docs/design/coreclr/botr/guide-for-porting.md#components-of-the-runtime-affected-by-a-port-to-a-new-architecture) is the abstraction layer located at `src/coreclr/pal`. That enables us to port other components of coreclr such as `src/coreclr/vm`, `src/coreclr/unwinder` and ultimately `src/coreclr/jit`.

We have riscv64 cross-toolchain with prerequisites set up for building the runtime. Some initial strokes to port coreclr are checked into the `main` branch (cmake configurations, libunwind, a few definitions in pal.h etc.).

Here is a gist for cross compilation:

```sh
#!/bin/sh

# on Ubuntu amd64 - with curl, jq and docker installed

tag="$(curl -sSL "https://raw.githubusercontent.com/dotnet/versions/main/build-info/docker/image-info.dotnet-dotnet-buildtools-prereqs-docker-main.json" |\
  jq -r '.repos[] | .images[] | .platforms [] | select(.dockerfile | contains("riscv64")).simpleTags[0]')"

URN="mcr.microsoft.com/dotnet-buildtools/prereqs:$tag"

cd runtime  # current main branch of dotnet/runtime

# Only build coreclr PAL and its tests:
docker run --rm -e ROOTFS_DIR=/crossrootfs/riscv64 -v"$(pwd)":/runtime "$URN" \
  /runtime/src/coreclr/build-runtime.sh -cross -a riscv64 -component paltests

# note: /crossrootfs/riscv64 has Debian sid bootstrap environment with llvm 14 and few other dependencies
# and the host has llvm 15 toolchain, which will be used by cmake for compilation with
# -sysroot=/crossrootfs/riscv64
#
# the relevant code to build this prerequisites docker image are:
#   * https://github.com/dotnet/arcade/blob/2e7521a/eng/common/cross/build-rootfs.sh#L155
#   * https://github.com/dotnet/arcade/blob/2e7521a/eng/common/cross/toolchain.cmake#L64
#   * https://github.com/dotnet/dotnet-buildtools-prereqs-docker/tree/main/src/ubuntu/22.04/cross/riscv64
```

The missing parts are architecture-specific assembly code under `src/coreclr/pal/src/arch/riscv64`, `src/coreclr/pal/inc/unixasmmacrosriscv64.inc` among other things. We added placeholder assembly files with `#error TODO-RISCV64​` which can be reviewed and deleted as part of the port.

Once PAL port is completed, we can copy `artifacts/bin​` to riscv64 machine (or virtual machine) and [run its tests](https://github.com/dotnet/runtime/blob/main/docs/workflow/testing/coreclr/unix-test-instructions.md#pal-tests) to verify the state of port:

```sh
$ artifacts/bin/coreclr/Linux.riscv64.Debug/paltests/runpaltests.sh \
    $(pwd)/artifacts/bin/coreclr/Linux.riscv64.Debug/paltests
```

**Comment by alexrp** [comment]
> Once PAL port is completed, we can copy `artifacts/bin​` to riscv64 machine (or virtual machine)

For porting of this nature, `qemu-riscv64` is your best friend. You can write code on an x86-based Linux system, build with a RISC-V cross toolchain, and then just run the resulting binary with QEMU's user mode emulation. I wrote a bit about this [here](https://github.com/mono/mono/blob/main/docs/riscv.md) for Mono a few years back.

**Comment by am11** [comment]
Yup, I am using with debian sid riscv64 VM. They also have good documentation in their wiki: https://wiki.debian.org/RISC-V#Qemu

RISC-V laptops are rumored to be available in coming weeks. :)

**Comment by archanox** [comment]
Fantastic work @am11! Looking forward to seeing how far dotnet support on RISC-V goes!

**Comment by am11** [comment]
I will defer to someone with experience to take the lead. I am new to RISC-V assembly but can lend hand wherever possible. :)

**Comment by am11** [comment]
cc @NKnusperer, mainly the next step for CoreCLR is to write assembly code under coreclr/pal; a few assembly stubs are left in PAL and then coreclr/vm; there is _a lot_ of assembly code to be written by hand. Unfortunately we don't have C/C++ fallback for the assembly code (as some projects do) so it's mainly about reading existing assembly code of similar architecture (arm64 or loongarch64) and manual transpilation. You can search with: `git grep TODO-RISCV` to see what's left under `src/coreclr/pal`.

Roughly, the order of porting is: PAL, VM and then JIT, (followed by / optionally: crossgen, AOT etc.). https://github.com/dotnet/runtime/blob/main/docs/design/coreclr/botr/guide-for-porting.md

**Comment by jkotas** [comment]
Anything left to do here?

**Comment by gbalykov** [comment]
> Anything left to do here?

@jkotas I think all is done. I'll share current pal tests status here soon.

**Comment by am11** [comment]
@gbalykov we can continue at https://github.com/dotnet/runtime/issues/84834 and close this one?

**Comment by gbalykov** [comment]
Current pal tests results on main

### 1) x64
```
PAL Test Results:
  Passed: 435
  Failed: 0
```

### 2) riscv visionfive2 with `HAVE_FUNCTIONAL_PTHREAD_ROBUST_MUTEXES_EXITCODE 1`
```
PAL Test Results:
  Passed: 436
  Failed: 0
```

### 3) riscv visionfive2 with `HAVE_FUNCTIONAL_PTHREAD_ROBUST_MUTEXES_EXITCODE 0`
```
PAL Test Results:
  Passed: 436
  Failed: 0
```

So, all is done.

**Comment by am11** [comment]
Amazing progress! Lets continue the status of overall runtime tests at https://github.com/dotnet/runtime/issues/84834. Closing.
