### ISSUE TITLE
JsonWriterHelper.Transcoding.cs replacement

### ISSUE THREAD

**Issue by kasperk81** [dotnet/runtime#75779]
old discussion: https://github.com/dotnet/corefx/pull/34425#discussion_r245931534

https://github.com/dotnet/runtime/blob/eeef4b14c5a137c2f665a9be4f30e4383d1038da/src/libraries/System.Text.Json/src/System/Text/Json/Writer/JsonWriterHelper.Transcoding.cs#L28

the corelib implementation this `ToUtf8` method was shadowing back in 2018-2019 is accelerated with hardware intrinsics since and code was heavily refactored, but `JsonWriterHelper.Transcoding` is stuck in time. should it be replaced by corelib version?

**Comment by stephentoub** [comment]
>  should it be replaced by corelib version?

Yes. At least in builds where it can be.

**Comment by kasperk81** [comment]
> @kasperk81 would you be interested in contributing a prototype targeting the shared framework routine?

https://github.com/dotnet/runtime/pull/75834/files has the prototype. some tests which are relying on impl details of JsonWriterHelper.Transcoding.cs are failing.. idk how realistic those tests are. feel free to use it.

**Comment by eiriktsarpalis** [comment]
@kasperk81 I just posted #77400 which should address the test issues.
