### ISSUE TITLE
[wasm][debugger] Object members that are protected accessors are not displayed in debugger window even though proxy is informed about them

### ISSUE THREAD

**Issue by thaystg** [dotnet/runtime#75778]
Code:
```
    private void IncrementCount()
    {
        JObject myObj = new JObject();
        myObj.Add("thays", new JObject());
    }
```
Disable JustMyCode in Debugger settings.

Try to look at myObj in locals, you will not see the property ChildrenTokens, and we are able to see it in a .net6 app.

This is the definition of it:
`protected override IList<JToken> ChildrenTokens => _properties;`

**Comment by ilonatommy** [comment]
Current behavior:
![image](https://user-images.githubusercontent.com/32700855/191242534-d0196462-8875-4b9d-8ae4-e610a321401d.png)

It looks that some accessors have wrong names (type instead of name, e.g. `ƒ System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<System.String,Newtonsoft.Json.Linq.JToken>>.IsReadOnly ()` looks like `ChildrenTokens`). Working on it.

**Comment by ilonatommy** [comment]
Mininal repro:
```
    public class ObjectWithNoInheritance //OK
    {
        public int publicVar = 0;
        internal int internalVar = 1;
        protected int protectedVar = 2;
    }

    public abstract class ObjectWithInheritanceBase
    {
        public abstract int publicVar { get; }
        internal abstract int internalVar { get; }
        protected abstract int protectedVar { get; }
    }
    
    public class ObjectWithInheritance : ObjectWithInheritanceBase
    {
        public override int publicVar => 0;
        internal override int internalVar => 1;
        protected override int protectedVar => 2;
    }
    
    private void IncrementCount()
    {
        ObjectWithInheritance testMe = new ObjectWithInheritance(); // NOT OK
    }
```
![image](https://user-images.githubusercontent.com/32700855/191265508-e260b0ba-8ff2-4129-b4e1-e0389c024780.png)

We can't have tests for it because the Debugger Proxy response is correct and contains all 3 members.

**Comment by ilonatommy** [comment]
CDP is sending the information correctly. I opened an issue to fix DAP: https://github.com/microsoft/vscode-js-debug/issues/1395

**Comment by ilonatommy** [comment]
The reason:
while grouping the members by protection level we were populating `internalProperties` part of response with internal/protected members. In fact, `internalProperties` does not correspond with C#'s protection level `internal` and describes only properties in the js code that are not acessible to the programmer. When debugging a simple js class:
![image](https://user-images.githubusercontent.com/32700855/191302118-3f865989-8fca-4dfd-8337-4ac34b4830bd.png)
we can see that protected member is returned along with public member - in `results`:
![image](https://user-images.githubusercontent.com/32700855/191302060-fa5d598c-79fc-4b2d-8b66-91831d022f58.png). In this issue we should remove populating `internalProperties` and move its contents to `result`.
