### ISSUE TITLE
Vector128 and Vector256 General purpose DotProduct tests fail

### ISSUE THREAD

**Issue by davidwrighton** [dotnet/runtime#75791]
### Description

These tests fail when upgraded to the new xunit based test system. This issue will be visible once #74886 is merged.

### Reproduction Steps

Run the hardwareintrinsics_ro merged test project located in src/tests/JIT/HardwareIntrinsics/HardwareIntrinsics_ro.csproj 

### Expected behavior

Test should reliably pass.

### Actual behavior

It fails where the difference in behavior is a floating point accuracy issue. (The algorithm is ... close in result) The expected result is within a small fraction of the actual result.

Console output looks like

```
21:26:27.767 Running test: global::JIT.HardwareIntrinsics.General._Vector128.Program.DotSingle()
Beginning scenario: RunBasicScenario_UnsafeRead
Vector128.Dot<Single>(Vector128<Single>, Vector128<Single>): RunBasicScenario_UnsafeRead failed:
    left: (0.3433865, 0.9667737, 0.12783496, 0.37054372)
   right: (0.98444676, 0.49922475, 0.64575523, 0.07723055)
  result: 0.93185043

Beginning scenario: RunReflectionScenario_UnsafeRead
Beginning scenario: RunClsVarScenario
Beginning scenario: RunLclVarScenario_UnsafeRead
Vector128.Dot<Single>(Vector128<Single>, Vector128<Single>): RunLclVarScenario_UnsafeRead failed:
    left: (0.3433865, 0.9667737, 0.12783496, 0.37054372)
   right: (0.98444676, 0.49922475, 0.64575523, 0.07723055)
  result: 0.93185043

Beginning scenario: RunClassLclFldScenario
Beginning scenario: RunClassFldScenario
Vector128.Dot<Single>(Vector128<Single>, Vector128<Single>): RunClassFldScenario failed:
    left: (0.74744684, 0.2090859, 0.9512482, 0.5400413)
   right: (0.558003, 0.40041316, 0.7649265, 0.91902465)
  result: 1.7247446

Beginning scenario: RunStructLclFldScenario
Beginning scenario: RunStructFldScenario
21:26:28.001 Failed test: global::JIT.HardwareIntrinsics.General._Vector128.Program.DotSingle()
```

### Regression?

Unlikely.

category:correctness
theme:vector-codegen
skill-level:beginner
cost:small
impact:small

**Comment by JulieLeeMSFT** [comment]
@kunalspathak PTAL. cc @dotnet/jit-contrib.
@davidwrighton, setting it to .net 8.0. Please get back to me if it needs to be 7.0.

**Comment by tannergooding** [comment]
I'd guess there is some subtle difference in addition ordering for the pre SSE4.1 codegen and that is causing it to be slightly off as compared to `dpps`.

**Comment by BruceForstall** [comment]
Why do they only fail when converted to the new test system? Are we not properly running them in the current test system?

**Comment by markples** [comment]
Is this #76280?  It looks like there are numerous failure symptoms there (all zeroes, all ones, inverted max, etc.), but https://github.com/dotnet/runtime/issues/76280#issuecomment-1261448127 shows a small value change.
