### ISSUE TITLE
[NativeAOT] Unnecessary lookup in TrailingEpilogueInstructionsCount

### ISSUE THREAD

**Issue by filipnavara** [dotnet/runtime#75807]
`UnixNativeCodeManager::TrailingEpilogueInstructionsCount` for `TARGET_ARM64` calls `FindMethodInfo` which is rather expensive. When called from `UnixNativeCodeManager::GetReturnAddressHijackInfo` it is already known so it can be passed over instead of doing extra lookup.

**Comment by jkotas** [comment]
cc @VSadov
