### ISSUE TITLE
[libraries-pgo] BBF_HAS_IDX_LEN is not set ... but is required because of the following tree

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#75827]
Failure in System.Globalization.Extensions.Tests on multiple Linux configurations.

Work item: https://dev.azure.com/dnceng-public/public/_build/results?buildId=21469&view=ms.vss-test-web.build-test-results-tab&runId=432716&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab&resultId=192990
Console log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-7b6005bf99b2486999/System.Globalization.Extensions.Tests/1/console.8d45794a.log?helixlogtype=result

```scala
BBF_HAS_IDX_LEN is not set on BB10 but is required because of the following tree 
N002 (  3,  3) [000126] ---X-------                         *  ARR_LENGTH int   
N001 (  1,  1) [000125] -----------                         \--*  LCL_VAR   ref    V11 tmp8         u:2

Assert failure(PID 21939 [0x000055b3], Thread: 21945 [0x55b9]): Assertion failed 'false' in 'Xunit.Assert:RecordException(System.Func`1[System.Object]):System.Exception' during 'Early Value Propagation' (IL size 48; hash 0xd54f2d8c; Tier1)

    File: /__w/1/s/src/coreclr/jit/earlyprop.cpp Line: 66
    Image: /datadisks/disk1/work/A44E0904/p/dotnet
```

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib

**Comment by EgorBo** [comment]
@jakobbotsch didn't you want to remove the check in https://github.com/dotnet/runtime/pull/71707 ? 🙂

**Comment by jakobbotsch** [comment]
Yes, in a follow-up change to #71707 I would remove it. But I have run into some regressions in #71707 that I need to think about how to fix before that can be merged.

**Comment by jakobbotsch** [comment]
But I will assign to myself, it should give me some motivation to work on fixing that. 😉

**Comment by jakobbotsch** [comment]
#71707 will probably take a while, so we should look at this separately given that it is failing often.

From a preliminary look this is some case of nested inlining not correctly propagating BB flags back.

**Comment by jakobbotsch** [comment]
At one point here inlining ends up replacing the inline candidate call node with the return expression in-place:

https://github.com/dotnet/runtime/blob/10fc8ae9a2af0a0ced69de92bb0d7734ff35946b/src/coreclr/jit/fginline.cpp#L1420

The return expression here is itself a `GT_RET_EXPR` node. This means we end up with multiple copies of that particular node, and the flags are not propagated through the right one.

Not yet sure how to fix it, this is all very convoluted.
