### ISSUE TITLE
warning CS1685: The predefined type 'System.ObsoleteAttribute' is defined in multiple assemblies in the global alias

### ISSUE THREAD

**Issue by wxommzwsdao** [dotnet/runtime#75859]
### Description

Hi.

I have an old ASP.NET MVC project.  I was trying to update the Nugets to the last version, and I get a warning:

    ASPNETCOMPILER : warning CS1685: The predefined type 'System.ObsoleteAttribute' is defined
      in multiple assemblies in the global alias; using definition from 
     'c:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\mscorlib.dll'

I attached a small version of this project:
    [ProblemObsoleteAttribute.zip](https://github.com/dotnet/runtime/files/9601986/ProblemObsoleteAttribute.zip)
Please, **don't run it, only compile it**.

Ok, if I use this version:
        `System.Text.Json" version="6.0.0-preview.4.21253.7"`
it compiles without any warning.

But if I update to this version:
        `System.Text.Json" version="6.0.0-preview.5.21301.5" `
then I get that warning.

And if I update to the latest version, I get the same warning.

Thanks in advance.

### Reproduction Steps

Please, unzip the file, and compile the project with Visual Studio 2022.  In the output window you will see that warning.

### Expected behavior

The `preview.4` don't has that warning.  The next version should not have this warning.

### Actual behavior

With `preview.5`, at compile time, I get this warning:

`ASPNETCOMPILER : warning CS1685: The predefined type 'System.ObsoleteAttribute' is defined in multiple assemblies in the global alias; using definition from 'c:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\mscorlib.dll'`

Also, with the latest version (`6.0.6`  or `7.0.0-rc.1.22426.10` ), I get that warning.

### Regression?

In the `System.Text.Json` Nuget, version`v6.0.0-preview.4.21253.7`, at compile time, don't show that warning.  Version `6.0.0-preview.5.21301.5`  (and all the next till the last version), they show that warning.

### Known Workarounds

Hide the warning `CS1685`.

### Configuration

- .NET Framework 4.8 and 4.8.1
- Windows 10
- x86, x64

**Comment by teo-tsirpanis** [comment]
New versions of `System.Text.Json` have an internal `ObsoleteAttribute` with the new properties defined in .NET 5. Does `aspnet_compiler` not recognize that?

I can't find the tool's sources anywhere and it seems to be exclusive to classic ASP.NET. Maybe you should [open a bug report on Developer Community](https://developercommunity.visualstudio.com/report?space=61&entry=problem).

**Comment by wxommzwsdao** [comment]
> New versions of `System.Text.Json` have an internal `ObsoleteAttribute` with the new properties defined in .NET 5. Does `aspnet_compiler` not recognize that?
> 
> I can't find the tool's sources anywhere and it seems to be exclusive to classic ASP.NET. Maybe you should [open a bug report on Developer Community](https://developercommunity.visualstudio.com/report?space=61&entry=problem).

Yes, this bug happens in classic ASP.NET.

I created a bug: [warning CS1685: The predefined type 'System.ObsoleteAttribute' is defined in multiple assemblies in the global alias](https://developercommunity.visualstudio.com/t/warning-CS1685:-The-predefined-type-Sys/10152556?space=61&entry=problem).

Thank you very much.
