### ISSUE TITLE
RyuJIT: tail call stress assert in importer on Linux

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#7586]
With `COMPlus_TailcallStress=1`, on non-Windows (Ubuntu, Mac, CentOS), the following assertion fires:
```
Assertion failed 'impTailCallRetTypeCompatible(info.compRetNativeType, info.compMethodInfo->args.retTypeClass, (var_types)callee->gtReturnType, callee->callSig->retTypeClass)' in 'System.Numerics.Vector:SquareRoot(struct):struct' (IL size 7)
```

in test JIT/SIMD/SqrtGeneric_r/SqrtGeneric_r.sh

You can trigger these with:
```
@dotnet-bot test CentOS7.1 tailcallstress
@dotnet-bot test OSX tailcallstress
@dotnet-bot test Ubuntu tailcallstress
```

category:correctness
theme:tail-call
skill-level:intermediate
cost:medium

**Comment by jakobbotsch** [comment]
Closing this since it seems stale and we had a fix already.
