### ISSUE TITLE
The HttpClient hangs with GetProxyForUrl

### ISSUE THREAD

**Issue by lindexi** [dotnet/runtime#75873]
### Description

I find my application can not get any web response with HttpClient in the special devices. And I debug my application and find the HttpClient hangs with GetProxy and the `GetProxy` method wait the `GetMultiProxy`. The `GetMultiProxy` wait the `WinInetProxyHelper.GetProxyForUrl`

https://github.com/dotnet/runtime/blob/156c373079eba9b7513bad607de3bd3a2b63bb96/src/libraries/Common/src/System/Net/Http/WinInetProxyHelper.cs#L79-L82

### Reproduction Steps

Sorry, I didn't find a good step. It seems that this problem can only occur on the special device.

### Expected behavior

How about add the timeout to GetProxyForUrl? 

### Actual behavior

The HttpClient hangs.

### Known Workarounds

Maybe the `GetProxyForUrl` are waiting for [WinHttpGetProxyForUrl function (winhttp.h) - Win32 apps | Microsoft Learn](https://learn.microsoft.com/en-us/windows/win32/api/winhttp/nf-winhttp-winhttpgetproxyforurl ) 

And the WinHttpGetProxyForUrl wait the DHCP or DNS  by [WINHTTP_AUTOPROXY_AUTO_DETECT](https://learn.microsoft.com/en-us/windows/win32/api/winhttp/ns-winhttp-winhttp_autoproxy_options)

### Configuration

Which version of .NET is the code running on? .NET 6.0.5

What OS and version, and what distro if applicable? Win10 19044

What is the architecture (x64, x86, ARM, ARM64)? x86

Do you know whether it is specific to that configuration? A special device that I can't describe

### Other information

This is a feedback from my user and he re-install the system and re-config the network now and fix this issues.

Sorry, this is not a good issues.

**Comment by lindexi** [comment]
@ManickaP Thank you. It means that the issue may got resolved by reinstalling the system, not the app. The GetProxyForUrl will wait [WinHttpGetProxyForUrl function (winhttp.h) - Win32 apps | Microsoft Learn](https://learn.microsoft.com/en-us/windows/win32/api/winhttp/nf-winhttp-winhttpgetproxyforurl). The WinHttpGetProxyForUrl equires a lot of work, some of which can be particularly time-consuming. On different computers, due to the different network configurations and the different LAN environments where the computers are located, the time required for WinHttpGetProxyForUrl  to complete the work will be different. That is why you do not repro.

And the google chromium solves this by setting a timeout, see https://chromium.googlesource.com/chromium/chromium/+/3a22d113c52e11e2159e90608cea55b89db0241a/net/proxy/proxy_resolver_winhttp.cc#166

Replace it with our code as follows:

```
            Interop.WinHttp.WinHttpSetTimeouts(sessionHandle, resolveTimeout: 10_000, connectTimeout: 10_000, sendTimeout: 5_000, receiveTimeout: 5_000);

```

Another bad thing is: when entering this method, no asynchronous thread switching has occurred. This means that if the time to acquire the proxy is long enough, the original calling thread will wait for a long time. In most cases, the client application will initiate a network request on the main thread, which means that the client application may freeze.

**Comment by karelz** [comment]
Triage: Seems to be solved by machine re-install. Closing.
If it happens more often and if there is something actionable, we can reopen in future. Thanks!

**Comment by lindexi** [comment]
@karelz In my opinion, asking the user to reinstall the system is unrealistic. In other words, what do you think about the software requires you to reinstall the system, when you want to use the software. Such software cannot be sold.

**Comment by karelz** [comment]
@lindexi we were not asking to reinstall the system. However, without a repro we have no chance to debug the problem.
That's what we ment by saying:
> If it happens more often and if there is something actionable, we can reopen in future.

Also, debugging one-machine problems is super hard and often waste of time - see my talk [War Stories from .NET Team (seeked to the right point)](https://youtu.be/ntGBRi_I3MM?t=515). They can be HW bugs, or corrupted installations, which might have been your case without further evidence.
.NET does not strive to be resilient against corrupted installations.
