### ISSUE TITLE
net6.0-ios/debugging: no listener on any ipv6 address on port 10000 but debugged app try to connect to ipv6 addresses

### ISSUE THREAD

**Issue by softlion** [dotnet/runtime#75877]
### Description

From a mac, with visual studio mac, trying to debug a maui app on an iOS device shows this log:

![image](https://user-images.githubusercontent.com/190756/191183724-354c3577-b9ec-4b12-ad5f-952d0119660e.png)

The app tries to connect to the debugger using ipv6 addresses. But the debugger listens only on ipv4.

> netstat -an -ptcp

![image](https://user-images.githubusercontent.com/190756/191184452-bf4f988c-6751-47c6-b466-3d469960e3dc.png)

### Reproduction Steps

* Create a maui app on a mac
* Start debugging it with visual studio mac
* Open the console app and filter on the mobile app's process
* Read the log

### Expected behavior

Either the debugger's server should listen to both ipv4 and ipv6, or the debugger's client should filter out ipv6 when trying to connect to its server.

### Actual behavior

 the debugger's server listen only to ipv4 on port 10000

### Regression?

no

### Known Workarounds

none. If ipv4 is disabled or not routed correctly, the debugger won't be able to connect.

Also, using ipv6 should improve a lot the connection speed, thus improving the whole debugging experience.

### Configuration

![image](https://user-images.githubusercontent.com/190756/191185415-3032298b-4c93-4fee-823e-e70a96b0a541.png)

**Comment by lewing** [comment]
cc @steveisok

**Comment by thaystg** [comment]
@mauroa is investigating it, it looks like it's an issue on windows too.

**Comment by thaystg** [comment]
It looks likes to be completely not related with mono debugger, because it's before runtime or debugger-libs code
In this line: https://github.com/xamarin/maciostools/blob/16e286fefc262d21e27884f19d55ffb40771823e/Xamarin.MacDev.Ide/IPhoneDevice.cs#L591
It's not connecting, returns error 22

**Comment by thaystg** [comment]
Moved to https://github.com/xamarin/maciostools/ repo
