### ISSUE TITLE
Release-only build has errors due to ResolvedMatchingContract when re-compiling in Visual Studio

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#75897]
When opening a library project with Visual Studio against a previously-built release-only (runtime and libraries) build the following error occurs:
```
Error		ResolvedMatchingContract 'C:\git\runtime\artifacts\bin\System.Private.CoreLib\ref\Debug\net7.0\System.Private.CoreLib.dll' did not exist.	System.Private.CoreLib	C:\Users\sharter\.nuget\packages\microsoft.dotnet.apicompat\8.0.0-beta.22455.1\build\Microsoft.DotNet.ApiCompat.targets	35	
```

So it is trying to use the `debug` version of `System.Private.CoreLib` (which does not exist) instead of the `release` version.

Not sure if this applies to all libraries or not.

## Repro
On a clean enlistment:
```
build -s clr+libs+libs.tests -c Release
```

- Open `C:\git\runtime\src\libraries\System.Reflection\System.Reflection.sln` in VS
- Change VS build type to `Release`
- Build within VS

Result: the above error plus attempting to run the tests from withing VS results in a silent failure because the default is to not run when there is a build error. The `Test` error output shows:
```
Aborting test run due to build failures. Please see the build output for more details.
```

**Comment by ericstj** [comment]
@akoeplinger looks like this could be related to your changes to add the CoreLib reference assembly?

**Comment by akoeplinger** [comment]
yeah it's probably triggered by that but I'm not sure why it's not respecting the configuration override we do here: https://github.com/dotnet/runtime/blob/main/eng/references.targets#L19-L25

@ViktorHofer any idea?

**Comment by ViktorHofer** [comment]
OK I misread what this is about. My above comment was about how to target the CoreLib that you already built inside VS.

This seems to be about that the ProjectReference from src/CoreLib to ref/CoreLib doesn't respect the set configuration.

> yeah it's probably triggered by that but I'm not sure why it's not respecting the configuration override we do here:

@akoeplinger that code path is conditioned to only run for the src/CoreLib but not when there's a P2P to the ref/CoreLib. I think we want to change the condition run for both ProjectReferences.

**Comment by ViktorHofer** [comment]
Closing because ref/CoreLib is now part of the solution files and hence this shouldn't happen anymore.
