### ISSUE TITLE
JIT: better optimization for CORINFO_HELP_RUNTIMEHANDLE_METHOD

### ISSUE THREAD

**Issue by JosephTremoulet** [dotnet/runtime#7590]
This helper depends on the (exact) type of the object passed to it, not the contents/fields of that objects.  Since an object's type is initialized anywhere the object pointer is available and is immutable for the lifetime of the object, we should therefore be able to give this helper call a value number that is a function of the pointer argument, rather than the memory the argument points to, and eliminate redundant calls such as we see in shared generic code.
category:cq
theme:helpers
skill-level:expert
cost:medium

**Comment by AndyAyersMS** [comment]
@EgorBo I think #81635 may have covered this?
