### ISSUE TITLE
IOS CultureInfo does not contain NativeName

### ISSUE THREAD

**Issue by harrykontopoulos** [dotnet/runtime#75927]
### Description

Initialising a CurrentInfo object for a given culture and binding to the NativeName is throwing an exception.
Upon debugging on the simulator the object doesn't look to have the NativeName and other properties included.

![image](https://user-images.githubusercontent.com/9673121/191357181-82b4329e-fbbf-425b-938f-2398b01adf25.png)

Same result found uppon deploying on a real device and logging the error.

### Reproduction Steps

1. Crate a new template MAUI project.
`dotnet new maui -n "MyMauiApp"`
2. Initialise a CultureInfo object on the MainPage constructor.
`var info = new CultureInfo("en-GB");`
3. Debug and check the object with a breakpoint.

### Expected behavior

The NativeName property should be populated with the respective value.

On Android (Device and Emulator) CultureInfo contains the properties as expected:

![image](https://user-images.githubusercontent.com/9673121/191359041-99be6ed9-ade8-44f3-bba9-6d759084ad0a.png)

### Actual behavior

Exception is thrown similar to this `'"NativeName"' property not found on '"en-GB"'`

**Comment by tarekgh** [comment]
CC @steveisok

**Comment by steveisok** [comment]
This is similar to https://github.com/dotnet/runtime/issues/70028.

**Comment by steveisok** [comment]
@mkhamoyan can you test whether hybrid globalization fixes this or not?

**Comment by mkhamoyan** [comment]
> @mkhamoyan can you test whether hybrid globalization fixes this or not?

Yes this will work on hybrid globalization mode.
Implemented by https://github.com/dotnet/runtime/pull/81470 and https://github.com/dotnet/runtime/issues/83514
