### ISSUE TITLE
Where is System.UInt128?

### ISSUE THREAD

**Issue by HSchwichtenberg** [dotnet/runtime#75924]
### Description

According to https://learn.microsoft.com/en-us/dotnet/api/system.uint128?view=net-7.0 and https://github.com/dotnet/core/issues/7454 there is a new type `public readonly struct UInt128` in the System namespace

However, with
` System.UInt128 x;`
 I get the error
**The type or namespace name 'UInt128' does not exist in the namespace 'System'** 
when running `dotnet build`

### Configuration

.NET 7.0.100-rc.1.22431.12

**Comment by stephentoub** [comment]
> Configuration
> .NET 7.0.100-rc.1.22431.12

What does your csproj look like?

**Comment by HSchwichtenberg** [comment]
I found the problem: I still had a PackageReference to System.Runtime.Experimental.
After removing that, System.Int128 is available!

Sorry for disturbing you with the question I could have answered myself 🤯

**Comment by stephentoub** [comment]
Glad you got it sorted out.
