### ISSUE TITLE
Windows server 2016, Windows 10: Whether this C# API System.Diagnostics.Eventing.Reader uses MSEVEN6 Protocol under the hood or not?

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#75949]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Windows-server-2016-Windows-10:-Whether/1606028)._

---
[severity:Other]
I am actually struggling to understand what communication protocol being used under the hood for C# API System.Diagnostics.Eventing.Reader. I did browse through official documentation **https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.eventing.reader?view=dotnet-plat-ext-6.0**
no where it is mentioning about protocol used under the hood.

How can i confirm this API mentioned above uses MS-EVEN6 ( MS Eventing protocol version6) or not ? Can you please provides me any pointer around it?

---
#### Feedback Bot on 12/7/2021, 03:50 AM: 

(private comment, text removed)
#### Feedback Bot on 4/2/2022, 02:57 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ericstj** [comment]
Here's a pointer to the source project: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.EventLog/src/System.Diagnostics.EventLog.csproj

It uses the Win32 methods like [ReadEventLog](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-readeventlogw) to read events.  This library itself doesn't implement any protocols, it just uses the public API exposed by Windows.
