### ISSUE TITLE
Kerberos  Authentication failure in HTTP Client in Linux (.NET6)

### ISSUE THREAD

**Issue by velmohan** [dotnet/runtime#75951]
### Description

Kerberos authentication works fine with the following code in Windows but fails in Linux (Ubuntu 18.04.6 LTS). 

```
  using (var handler = new HttpClientHandler())
           {
            handler.PreAuthenticate = true;
            handler.UseDefaultCredentials = true;
            var vaultUri = new Uri("https://someapi.domain:8200", UriKind.Absolute);

            var client = new HttpClient(handler)
            {
                BaseAddress = vaultUri
            };

            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            client.DefaultRequestHeaders.Host = vaultUri.Host;   // See the description below

            const string uriString = "someuri/v1";

            HttpResponseMessage resp = null;
            try
            {
                resp = await client.PostAsync(new Uri(uriString, UriKind.Relative), null).ConfigureAwait(false);

                resp.EnsureSuccessStatusCode();
                return 1;
            }
            catch (Exception e)
            {
                Console.Error.WriteLine(e);
                return 0;
            }
  }
```

The error we get in Linux:

```
System.ComponentModel.Win32Exception (0x80090020): GSSAPI operation failed with error - Unspecified GSS failure.  Minor code may provide more information (Server not found in Kerberos database).
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal& statusCode)
   at System.Net.NTAuthentication.GetOutgoingBlob(String incomingBlob)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
```

I have seen similar issues like #51980 but the current issue seems to be different and this occurs in netcore3.1 and net6.

I have also checked we have the following SPNS added already:

1. HTTP/someapi.domain:8200
2. HTTP/someapi.domain

Also, interestingly, if we do not add the following in the code above, the code fails in Windows too, with 401 error.

`            client.DefaultRequestHeaders.Host = vaultUri.Host;  
`

### Reproduction Steps

1. Run the above code in Windows and Linux after replacing "someapi.domain:8200" with a valid server name/port where Kerberos has been enabled.
2. The code will work in Windows but fail in Linux

### Expected behavior

The code should work in Linux. In the very least, the behavior should be consistent across platforms.

### Actual behavior

Code fails in Linux

**Comment by filipnavara** [comment]
Would it be possible to run your sample with `KRB5_TRACE="/dev/stdout"` set? The additional Kerberos logs from the native library may give a clue on what's happening.

**Comment by wfurt** [comment]
You can also try to log in with 'kinit` to make sure the native environment works. Things get trickier when the name points to CNAME.

**Comment by velmohan** [comment]
Thank you @filipnavara and @wfurt. The trace (that I am not able to share here I am afraid) indicates that the Linux implementation looks for SPN in the A record whereas we have added SPNs in CNAME (i.e. "someapi.domain"). This configuration works in Windows. We are going to try adding SPNs for A record and see. Any idea why Windows implementation is different?

**Comment by SteveSyfuhs** [comment]
Here: https://github.com/dotnet/runtime/issues/27415#issuecomment-432793800

Try setting `dns_canonicalize_hostname` to false in `krb5.conf`: https://web.mit.edu/kerberos/krb5-1.12/doc/admin/conf_files/krb5_conf.html#libdefaults

**Comment by wfurt** [comment]
.NET really sits on top of OS layer and calls GSSAPI @velmohan. Since the implementations are different, you may get different outcomes with same code. (unfortunately) 

HttpClient will derive SPN from the `Host` header if present and falls-back to host from `URI`.

**Comment by velmohan** [comment]
Thank you all for the help. Adding SPNs for A records of the servers resolved the issue. This fixed the issue in Windows and so we do not need to populate Host` header anymore.
