### ISSUE TITLE
[Feature Request] System.Text.Json: Built-in Converter of Serializing/Deserializing generic ObservableCollection<T> properties of custom classes

### ISSUE THREAD

**Issue by SunshineSpring666** [dotnet/runtime#75977]
Hi everyone,
One thing that block us migrating from [Newtonsoft Json.NET](https://www.newtonsoft.com/json) to [System.Text.Json](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-overview?pivots=dotnet-7-0) is the lack of built-in Converter to serialize/deserializing any ObservableCollection<T> properties of any custom classes. I assume many people encounters this problem, since it's quite common.

Suppose we have many classes that needs to serialize/deserialize their objects when communicating with server.
One of these classes may look like:
```C#
public class Car
{
    public int Id { get; set; } = 1;
  
    [JsonConverter(typeof(ObservableConverter<Link>))]
    public ObservableCollection<Link> Links { get; set; } = new ObservableCollection<Link>();

    [JsonConverter(typeof(ObservableConverter<Attribute>))]
    public ObservableCollection<Attribute> Attributes { get; set; } = new ObservableCollection<Attribute>();
}
```
In  [Newtonsoft Json.NET](https://www.newtonsoft.com/json) , we may simply write one Custom Converter for all types of ObservableCollections<T>  (generic type) to use by reusing the converter:
```C#
 public class ObservableConverter<T> : DateTimeConverterBase
    {
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            string str = reader.Value as string;
            str = str != "" ? str : "[]";
            List<T> ls = JsonConvert.DeserializeObject<List<T>>(str);
            ObservableCollection<T> obs = new ObservableCollection<T>(ls);
            return obs;
        }

        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteValue(JsonConvert.SerializeObject(((value as ObservableCollection<T>).ToList())));
        }
    }
```
These simple lines of code solves the problem of serializing/deserializing all types of ObservableCollection properties in any custom classes.

I tried to migrate from Newtonsoft to [System.Text.Json](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-overview?pivots=dotnet-7-0) following the [Custom Converters](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to?pivots=dotnet-7-0), but failed to write such reusable converter for ObservableCollection<T>.

Could you please considering adding such converter as built-in, or illustrating such code? Writing [Custom Converters](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to?pivots=dotnet-7-0) for each custom classes which contains different ObservableCollection<A>, ObservableCollection<B>... would be difficult, since there are so many such classes. A out-of-the-box  [JsonConverter(typeof(ObservableConverter<SomeCustomType>))] would be very helpful.

Thanks a lot.
Best Regards

**Comment by eiriktsarpalis** [comment]
> the lack of built-in Converter to serialize/deserializing any ObservableCollection properties of any custom classes.

Can you elaborate? AFAICT `ObservableCollection<T>` serialization and deserialization works out of the box without issue, as the following example illustrates:

```C#
var value = new MyPoco { Collection = new() { 1, 2, 3 } };
string json = JsonSerializer.Serialize(value);
Console.WriteLine(json);

value = JsonSerializer.Deserialize<MyPoco>(json);
Console.WriteLine(value.Collection.Count);

public class MyPoco
{
    public ObservableCollection<int> Collection { get; set; }
}
```

**Comment by SunshineSpring666** [comment]
It works in current version. Sorry I just posted this issue based on the migration experience back in 2020. 
Thanks a lot. I'll close it for now.
