### ISSUE TITLE
[WASM] Check if we can still skip GC critical method check in WASM

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#75970]
There is an ifdef here to skip the critical method check in wasm: https://github.com/dotnet/runtime/blob/77bf509ab733114a04936cc6688c369f0dd2c090/src/mono/mono/metadata/sgen-mono.c#L237. 

Its not clear if this can still be safely skipped when wasm is multithreaded. Wasm uses co-op suspend, so *if* the managed code has no GC safepoints, this should still be ok. If it does have safepoints, the runtime might need to do the critical method check.

If we are able to safely skip it, the comment should be updated to say it can be skipped because of co-op suspend and the lack of safepoints (rather than single threadedness).

**Comment by lewing** [comment]
cc @pavelsavara
