### ISSUE TITLE
JIT does not eliminate null check for "o ??= new()"

### ISSUE THREAD

**Issue by tfenise** [dotnet/runtime#75987]
### Description

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYQYG8aHunHjykTFAwCy5ABQRgAKxhgMDCAEoOXHuoCWAMwbjJDAPwGAvAwB2MAO6KZcjOKUqNucwFcANu5UYAFlAjWFtYAoghgMAAOGBoQZg4A3GrcAL5JDGn0TAJCoqSStvKKKpzU6po6ehAMpkE2svIOTi5mHl4Mvv6BVgyh4VExcUqJpTypI9wZfNnEwiJ04hpmChrFaeW6GgwAPAwADE7Ve8NlPNob23vefgHm3b2R0bEJaWPqk1mCM6Io+fUKyqpxgwxskgA=
```C#
static void M1(object o) {
    if ((o ??= new object()) is null) throw new Exception();
}
    
static void M2(object o) {
    if ((o = new object()) is null) throw new Exception();
}

static void M3(int i) {
    if (i < 0) i = 0;
    if (i < 0) throw new Exception();
}
    
static void M4(object o) {
}
```

While the JIT can optimize `M2`(almost, but still curiously worse than `M4`) and `M3` to a nop, it cannot optimize `M1` similarly.

Found while discussing #75936.

### Configuration

sharplab says "Core CLR 6.0.822.36306 on amd64".

I also tried 7.0.100-rc.1.22431.12 on amd64. The codegen for `M1` was not really better.

### Regression?

Probably not.

**Comment by EgorBo** [comment]
Looks like Jump-Threading + PHI issue?

![image](https://user-images.githubusercontent.com/523221/191600260-42271bea-8206-4839-a4b9-4bd7ff189922.png)

BB03 is never true because V02 is either come form `V02 != 0` == true or it comes from BB02 where it's set to non-null
cc @AndyAyersMS to confirm

**Comment by AndyAyersMS** [comment]
Likely `BB03` has some side effecting code; this currently blocks jump threading.

**Comment by AndyAyersMS** [comment]
> Likely `BB03` has some side effecting code; this currently blocks jump threading.

No, you were right, this is the PHI case.
```
optRedundantRelop in BB03; jump tree is
N004 (  7,  6) [000012] -----------                         *  JTRUE     void   $VN.Void
N003 (  5,  4) [000011] J------N---                         \--*  NE        int    $101
N001 (  3,  2) [000009] -----------                            +--*  LCL_VAR   ref    V02 tmp1         u:2 (last use) $1c0
N002 (  1,  1) [000010] -----------                            \--*  CNS_INT   ref    null $VN.Null
 ... checking previous tree
N005 (  0,  0) [000038] -A------R--                         *  ASG       ref    $VN.Void
N004 (  0,  0) [000036] D------N---                         +--*  LCL_VAR   ref    V02 tmp1         d:2 $VN.Void
N003 (  0,  0) [000037] -----------                         \--*  PHI       ref    $1c0
N001 (  0,  0) [000040] ----------- pred BB02                  +--*  PHI_ARG   ref    V02 tmp1         u:3 $180
N002 (  0,  0) [000039] ----------- pred BB01                  \--*  PHI_ARG   ref    V02 tmp1         u:1 $80
 -- prev tree is a phi
Relop [000011] BB03 value unknown, trying inference
```
