### ISSUE TITLE
No runtime error raised while using Generics of an unreferenced class

### ISSUE THREAD

**Issue by FanSaaStic** [dotnet/runtime#75984]
Asked to add area: **area-Infrastructure-libraries**.

I hope the title makes sense so here it is...  

Here are the components of what I believe is an issue in C#, using .NET 6.0, Visual Studio 2022 in a Web.API app using standard controllers:

The AccountModel is simple public POCO with non-complex simple properties such as strings and ints in it's own class file in a sub-folder from the root named "Models".

I have a public class within the root named "DoJson.cs" that performs JSON work exclusively with the System.Text.Json library.  A public method named Json2Object<T>(string jsonString) (note that there is a generic T after Json2Object but this does not show here) exists to return the AccountModel object.  The JsonString param has been tested and it's properties are fully populated.  Pretty straight forward however, it does not work and compiles/runs without error.  Using an NUnit test, it can be seen by intellisense and runs but only returns an empty AccountModel object without the property values within the Json and without any runtime errors

After troubleshooting, it works after placing a "using" reference of my Models folder which contained the AccountModel.cs  class in the DoJson.cs class.  Simple I know but... I feel that a runtime error should be thrown when the object T can not find the actual object class it represents.  Before I corrected the issue and added the using reference, the method returned the right object with the right default values but did not consider the populated JSON properties within the string at all without error.  I could have left this alone with a huge gap in the data, again, without any errors.  By using typeof(T).Name within the failing method, I was able to see the name and properties of the Generic T object (the AccountModel class) so that information should be used to find the correct reference and if the reference is missing, should error out on runtime.  I've seen this type of error in other places with the "...are you missing a reference?" statement in the error.

Thanks in advance for your comments pro and con!  

Thank you for your consideration,
Mark Sullivan
mark.sullivan@fansaastic.com

**Comment by jeffschwMSFT** [comment]
@FanSaaStic can you share a repro for the issue you are seeing?

**Comment by eiriktsarpalis** [comment]
@FanSaaStic [here's more info](https://github.com/dotnet/runtime/blob/main/CONTRIBUTING.md#writing-a-good-bug-report) on how to share a minimal reproduction.
