### ISSUE TITLE
DynamicDependency to property doesn't work with NativeAOT

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#75994]
### Description

When using a DynamicDependency attribute on a constructor of a class, NativeAOT is not preserving the PropertyInfo being depended on. We use this in our Diagnostics code here:

https://github.com/dotnet/runtime/blob/2f3fcca06499725469b6ae021be960e08d808c75/src/libraries/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs#L217-L226

cc @vitek-karas @MichalStrehovsky 

### Reproduction Steps

```
dotnet publish -p:PublishAot=true -c Release -r win-x64
```

The following program:

```C#
using System.Diagnostics.CodeAnalysis;
using System.Net;
using System.Reflection;

Console.WriteLine("Hello, World!");

var c = new MyDataClass();
Console.WriteLine(c);

SeeIfItWorks();

void SeeIfItWorks()
{
    var p = GetProperty(typeof(ResponseMessage), "StatusCode");
    Console.WriteLine(p ?? (object)"Doesn't work");
}

PropertyInfo GetProperty(Type type, string v)
{
    return type.GetProperty(v)!;
}

public class MyDataClass
{
    [DynamicDependency(nameof(ResponseMessage.StatusCode), typeof(ResponseMessage))]
    internal MyDataClass()
    {

    }
}

internal class ResponseMessage
{
    public HttpStatusCode StatusCode { get; set; }
}
```

### Expected behavior

The app should print

```
Hello, World!
MyDataClass
System.Net.HttpStatusCode StatusCode
```

### Actual behavior

The app prints

```
Hello, World!
MyDataClass
Doesn't work
```

### Regression?

I am not sure. Probably not.

**Comment by MichalStrehovsky** [comment]
"I'll ifdef this one out and revisit once we have a representation for properties". Sigh.

https://github.com/dotnet/runtime/blob/3303bd326fded4310e9febacc88e9edc223bcfc5/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Logging/DocumentationSignatureParser.cs#L213-L220

**Comment by vitek-karas** [comment]
This should be fixed now with https://github.com/dotnet/runtime/pull/79398 (which added lot of tests from linker and some product fixes).
