### ISSUE TITLE
build-android-rootfs.sh Must be fix the "termux" URL

### ISSUE THREAD

**Issue by lvzuoxin** [dotnet/runtime#76002]
The
https://github.com/dotnet/runtime/blob/main/eng/common/cross/build-android-rootfs.sh

Go line: 100

Find string:
http://termux.net/
Replace all to:
https://packages.termux.dev/termux-main-21/

Build succeeded test:
    ./build.sh --os Android 
or
    ROOTFS_DIR=$(realpath /Home/runtime_linux/.tools/android-rootfs/android-ndk-r21/sysroot) ./build.sh --cross --arch arm64 --subset mono

@steveisok

**Comment by steveisok** [comment]
@lvzuoxin this only applies to building coreclr on android and I'm not sure how actively maintained it is.

**Comment by akoeplinger** [comment]
https://github.com/dotnet/arcade/pull/11290 was merged which fixes this, it'll flow into dotnet/runtime in the next few days.
