### ISSUE TITLE
Permissions in ZipArchive Missing on Linux - Regression in .Net 7 RC1?

### ISSUE THREAD

**Issue by Webreaper** [dotnet/runtime#76006]
### Description

I'm creating a zip archive in my app, and hit the bug mentioned in https://github.com/dotnet/runtime/issues/17912 and https://github.com/dotnet/runtime/pull/70735. My archive permissions are missing, so that when I download onto MacOS and extract, the resulting files are all inaccessible.

I _think_ this might have been fixed with an earlier .Net 7 preview (or possibly .Net 6) but it's broken again now. This is from an archive created with my code and .Net 7 RC1. 

<img width="621" alt="Screenshot 2022-09-22 at 08 48 31" src="https://user-images.githubusercontent.com/4901102/191689185-c90602e9-b59f-4a20-8431-91918c5f8ac8.png">

Adding the code (per the comment in issue 17912) fixes the problem (see commit https://github.com/Webreaper/Damselfly/commit/98812c3971015e1c6bbc42776d6f1837cf14ba5f).

### Reproduction Steps

This is the code I'm using to create the zip (from https://github.com/Webreaper/Damselfly/blob/develop/Damselfly.Core/Services/DownloadService.cs#L157):

```
    using ( var zip = ZipFile.Open(serverZipPath, ZipArchiveMode.Create) )
    {
        int count = 1, total = filesToZip.Count();

        foreach ( var imagePath in filesToZip )
        {
            if ( imagePath.Exists )
            {
                var exportUnchanged = true;
                var internalZipPath = imagePath.Name;

                if ( config.KeepFolders )
                    internalZipPath = Path.Combine(imagePath.Directory.Name, internalZipPath);

                ZipArchiveEntry entry;

                // Export the original file, as-is
                entry = zip.CreateEntryFromFile(imagePath.FullName, internalZipPath);
            }
        }
    }
```

### Expected behavior

When the zip is downloaded from the web service onto a Windows or Mac desktop, and extracted, the files should have read permissions.

### Actual behavior

The files extracted from the archive have no read permissions.

### Regression?

I think this may have been working in earlier previews of .Net 7.

These two issues indicate that it's fixed, as they're closed.

- https://github.com/dotnet/runtime/issues/17912
- https://github.com/dotnet/runtime/pull/70735

### Known Workarounds

Adding this line:
```
    entry.ExternalAttributes = entry.ExternalAttributes | ( Convert.ToInt32( "664", 8 ) << 16 );
```

gives the files the correct permissions so they're accessible after download/extraction:

<img width="556" alt="Screenshot 2022-09-22 at 09 01 18" src="https://user-images.githubusercontent.com/4901102/191691498-ad21bff0-4bc6-41c1-a8a1-b9b09c86f05a.png">

### Configuration

- Running on a Synology NAS (Debian)
- Compiled with .Net 7 RC1 (v7.0.100-rc.1.22431.12), x64
- Self-contained Hosted Blazor WASM app, deployed via Docker (Ubuntu 20.04 base image)
- The issue happens when running the app on Linux, and downloading the zip file to a MacOS laptop

**Comment by tmds** [comment]
With
```
$ dotnet --version
7.0.100-rc.1.22431.12
```
running
```cs
using System.IO.Compression;

using var zip = ZipFile.Open(Path.Combine(Path.GetTempPath(), Path.GetRandomFileName()), ZipArchiveMode.Create);

var randomFile = Path.GetTempFileName();

var entry = zip.CreateEntryFromFile(randomFile, randomFile);

Console.WriteLine(File.GetUnixFileMode(randomFile));
Console.WriteLine(Convert.ToString((uint)entry.ExternalAttributes >> 16, 8));
```
gives me:
```
$ dotnet run
UserWrite, UserRead
100600
```
`100600` is the expected value for a regular file with rw permissions for the owner.

If you add a similar `WriteLine` for the `UnixFileMode` and `ExternalAttributes`, what do you get?

**Comment by Webreaper** [comment]
Okay, added the logging in the commit above. Output:
```
[07:43:12.693-.NET ThreadPool Worker-INF] Preparing zip file from 3 files.
[07:43:12.861-.NET ThreadPool Worker-INF]  Opening zip archive: /app/wwwroot/downloads/DamselflyImages-23-Sep-22_07_43_12.zip
[07:43:13.180-.NET ThreadPool Worker-INF]  Adding file to zip: /pictures/Thursley Common Adventure 10-Aug-2018/A8109756.JPG
[07:43:14.023-.NET ThreadPool Worker-INF] Unix File Perms: UserExecute, UserWrite, UserRead
[07:43:14.023-.NET ThreadPool Worker-INF] Zip file entry attributes: 100700
[07:43:14.069-.NET ThreadPool Worker-INF]  Adding file to zip: /pictures/Kew Orchid Festival (macro) 8-Feb-2019/P2080929.JPG
[07:43:15.180-.NET ThreadPool Worker-INF] Unix File Perms: UserExecute, UserWrite, UserRead
[07:43:15.180-.NET ThreadPool Worker-INF] Zip file entry attributes: 100700
[07:43:15.236-.NET ThreadPool Worker-INF]  Adding file to zip: /pictures/Kew Orchid Festival (macro) 8-Feb-2019/P2080931.JPG
[07:43:16.020-.NET ThreadPool Worker-INF] Unix File Perms: UserExecute, UserWrite, UserRead
[07:43:16.020-.NET ThreadPool Worker-INF] Zip file entry attributes: 100700
```
Which I think seems okay. So then I added logging before and after I make the file permission change:
```
    entry.ExternalAttributes = entry.ExternalAttributes | ( Convert.ToInt32( "664", 8 ) << 16 );
```
([commit](https://github.com/Webreaper/Damselfly/commit/a9b4c1de5c8bc346fce59369b6e89352cfc31672)) and the log is like this:
```
[08:32:44.275-.NET ThreadPool Worker-INF] Unix File Perms: None
[08:32:44.275-.NET ThreadPool Worker-INF] Zip file entry attributes: 100000
[08:32:44.275-.NET ThreadPool Worker-INF] Zip file entry attributes after change: 100664
[08:32:44.275-.NET ThreadPool Worker-INF]  Adding file to zip: /pictures/More Apple Harvest 19-Sep-2022/P9191550.JPG
[08:32:44.918-.NET ThreadPool Worker-INF] Unix File Perms: None
[08:32:44.918-.NET ThreadPool Worker-INF] Zip file entry attributes: 100000
[08:32:44.918-.NET ThreadPool Worker-INF] Zip file entry attributes after change: 100664
[08:32:44.918-.NET ThreadPool Worker-INF]  Adding file to zip: /pictures/More Apple Harvest 19-Sep-2022/P9191549.JPG
[08:32:45.527-.NET ThreadPool Worker-INF] Unix File Perms: None
[08:32:45.527-.NET ThreadPool Worker-INF] Zip file entry attributes: 100000
[08:32:45.527-.NET ThreadPool Worker-INF] Zip file entry attributes after change: 100664
```
This is somewhat baffling, as I can't see how the unix file perms can change. So I've no idea what's going on here.

**Comment by tmds** [comment]
```
`Unix File Perms: None`
```
It looks like the permissions of these files is `000`. That is what gets stored in the archive, and then restored on macOS.

Can you check permissions on the files on your NAS?

fyi, if your app runs as `root`, it will be able to read the files, even if they have zero-read permissions.

**Comment by Webreaper** [comment]
Yes, I was just rummaging around in that. What's happened is that I migrated my server and in the process the user 'admin' got replaced with another user. Some of these files are still owned by 'admin', so as you say, there are no appropriate file permissions - and because the app runs as root in the docker container, it's obviously able to read the files.

So I guess the zip behaviour is sensible, but worth checking what the expectation is here. Would we expect the .Net zip process to apply read attributes on the files in the zip, regardless of the permissions of the files on disk? Or is it reasonable to expect the developer to explicitly create permissions for end-user zipped files. I'm not sure what is a sensible default.

I'm quite happy to leave the explicit application of RW permissions to the files, but I wonder if the intuitive default behaviour of the zip archive classes should be to add some sensible R/W permissions if the files being zipped have none?

**Comment by tmds** [comment]
I think the default behavior makes sense.

The issue you have isn't a common one. None of the source files have read permissions, and the zip-file gets created as `root` which makes that go undetected.

**Comment by Webreaper** [comment]
I guess the challenge is the discoverability of why it happens - I only found the fix after a lot of googling. Perhaps a sensible compromise would be to do something like:
```
using var zip = ZipFile.Open(serverZipPath, ZipArchiveMode.Create |  ZipArchiveMode.ApplyDefaultRWPermissions );
```
or something similar, so it's discoverable and relatively straightforward for callers to ensure that their zipped files will get sensible permissions regardless of their source? (disclaimer: I'm rubbish at designing APIs so it could be much better, e.g., an additional parameter to the ZipArchive constructor, or something).

**Comment by Jozkee** [comment]
Thanks for digging in @tmds.

This is not a regresion after all. 
Seems like what you are asking for is a flag to force archiving with r/w permissions. I don't think is something we currently want to invest or directly support in ZipArchive.
