### ISSUE TITLE
Out Of Memory From Pinned byte[] used in SslStream

### ISSUE THREAD

**Issue by kevin-montrose** [dotnet/runtime#76029]
### Description

A [rented `byte[]` in `SslStream`](https://github.com/dotnet/runtime/blob/531f715f281e7a6456375635c02b6dd301d95996/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs#L1217) ends up pinned for I/O, contributing to `OutOfMemoryException`s under high memory pressure scenarios.

The scenario we've encountered is:
 1. Our application dedicates ~50% of its heap to a cache
    * Over time most of this ends up in Gen2, but at any point in time some of it is in Gen1 and Gen0.
    * We run with a hard memory limit imposed by a Job.
 2. The application is also handling a lot of http requests, with underlying `SslStream`s.
 3. As part of handling these requests some large object heap (LOH) and pinned object heap (POH) allocations are sometimes needed.
    * Most of the POH allocations actually come from Kestrel code.
 4. Occasionally a LOH or POH allocation triggers a GC, but fails to free up enough space for the allocation in the existing heap and so the GC attempts to reclaim space from the ephemeral segment to grow the heap.
 5. Despite the ephemeral segments being mostly free space, this **fails** because of pinned arrays obtained in that `ResetReadBuffer()` method.
    * More precisely, the ephemeral segments are shrunk as far as the pins allow but enough space is not freed up.
 6. Runtime raises an `OutOfMemoryException`, and our application crashes.

I waffled between whether this is a bug or a performance concern.  Everything is technically functioning correctly, so I settled on performance concern.

### Configuration

This is observed under various .NET 6 point releases, running under Windows, on Intel x64 hardware.  We are using the concurrent server GC.

This appears to be possible <strike>under all OS</strike> (_per discussion below, this is Windows specific_) on Windows for all hardware combinations, but we have not reproduced it elsewhere.

### Regression?

This is **not** a regression, however recent versions of .NET introduce the pinned object heap (POH) which offers a mitigation.

### Data

We diagnosed this by looking at crash dumps and observing that pinned `byte[]`s with 32,768 elements were always at the end of the ephemeral segments, and then using Perfview to try and catch pinning in the act.  That led us to `SslStream`, and then a close reading of the source found an appropriately sized array (recall that `ArrayPool` rounds up to nearest power of 2, so [`ReadBufferSize == 4_096 * 4 + FrameOverhead == 16_448`](https://github.com/dotnet/runtime/blob/531f715f281e7a6456375635c02b6dd301d95996/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs#L44) will get a `byte[]`s with 32,768 elements).

### Analysis

While our particular issue appears to be caused by that array, in theory any `byte[]` (which is not on the POH) used for I/O in `SslStream` could also cause it.

Starting in .NET 5.0 the POH is available, which enables keeping pins out of the ephemeral segments.  Kestrel has adopted the POH (via its [`PinnedBlockMemoryPool`](https://github.com/dotnet/aspnetcore/blob/main/src/Shared/Buffers.MemoryPool/PinnedBlockMemoryPool.cs)) for much of it I/O, which neatly avoids this problem (while also providing some performance benefits, potentially).

I'm not familiar enough with `SslStream`'s implementation to say whether adopting a similar approach as a simple drop in is viable, so I have not created a PR.

**Comment by stephentoub** [comment]
> This appears to be possible under all OS & hardware combinations, but we have not reproduced it elsewhere.

There shouldn't be any long-lived pinning happening on other OSes.  This is inherent to the Windows model for overlapped I/O, where the buffers are supplied to the receive/read calls performing the I/O; on Linux/macOS/etc., a buffer is only supplied under the covers once the implementation is notified data is available.  I realize this isn't the intent of your issue, but if you have evidence of this happening anywhere other than Windows, I'd be interested in seeing it.

> The application is also handling a lot of http requests, with underlying SslStreams.

Are these SslStreams in your control, or are they underlying a component like HttpClient you don't own? You might try using zero-byte reads, e.g. first perform a read with `ReadOnlySpan/Memory<byte>.Empty`, and then only issue the actual read when you know data is available.  That should avoid the pinning.

**Comment by kevin-montrose** [comment]
> There shouldn't be any long-lived pinning happening on other OSes. This is inherent to the Windows model for overlapped I/O, where the buffers are supplied to the receive/read calls performing the I/O; on Linux/macOS/etc., a buffer is only supplied under the covers once the implementation is notified data is available. I realize this isn't the intent of your issue, but if you have evidence of this happening anywhere other than Windows, I'd be interested in seeing it.

Ah, this is good to know - I assumed other OS's were similar, but if that is incorrect then there is no evidence this can happen on other OS's.  I'll update the issue accordingly.

> Are these SslStreams in your control, or are they underlying a component like HttpClient you don't own? You might try using zero-byte reads, e.g. first perform a read with `ReadOnlySpan/Memory<byte>.Empty`, and then only issue the actual read when you know data is available. That should avoid the pinning.

Technically we don't control the underlying component, but enough of the reads are simple passthroughs that this might also be a viable mitigation.  Given the way our app is structure it might be a bit painful to apply to everything that matters, but that's our problem not .NET's.

Just to be clear, you're suggesting we switch:

```csharp
// stream is some Stream
// mem is some Memory<byte>
// token is some CancellationToken
var foo = await stream.ReadAsync(mem, token);
// use foo
```

with

```csharp
// stream is some Stream
// mem is some Memory<byte>
// token is some CancellationToken
await stream.ReadAsync(Memory<byte>.Empty, someCancellationToken); 
var foo = await stream.ReadAsync(someMemory, someCancellationToken);
// use foo
```

**Comment by stephentoub** [comment]
> Just to be clear, you're suggesting we switch

Correct, at least as an experiment.

It's a tradeoff, of course, but if memory is your issue, it's likely a good one.  This goes beyond pinning, as it's really about how much memory is consumed at any point in time.

**Comment by davidfowl** [comment]
@kevin-montrose Are you running into this with Kestrel or are you writing manual code to deal with SSL Stream? Or are you doing something with SSLStream on as well? The memory behavior should be much improved in .NET 6 since we introduced zero byte reads for TLS as well.

[This](https://github.com/dotnet/aspnetcore/issues/27394) is a long standing issue in Kestrel that we need to fix but I'd love to see this repro. It would help us narrow in on a scenario where it happens frequently.

Another option is to throttle concurrency to protect the server from OOMing.

**Comment by kevin-montrose** [comment]
@davidfowl the code using `SslStream` is outside of Kestrel, but we are using Kestrel in the app. In the cases we've seen where the POH is the heap that fails to grow it's Kestrel that's trying to allocate, and Kestrel that's making the most use of the POH.

We've seen incidents where it's the LOH that fails to grow, in those cases it's been our own code trying to allocate.

This reproduces pretty rarely (on the order of once a month or so, though we're concerned it could happen more frequently under higher load), unfortunately, as it's sensitive to GC and request timing.   It took us a few months to come to this conclusion, in part because we didn't have an easy repro to test hypotheses - as noted in the issue, we ended up using Perfview to find where appropriately sized pins were happening and then interrogating the source.

**Comment by davidfowl** [comment]
> @davidfowl the code using SslStream is outside of Kestrel, but we are using Kestrel in the app. In the cases we've seen where the POH is the heap that fails to grow it's Kestrel that's trying to allocate, and Kestrel that's making the most use of the POH.

Can you collect some usage statistics around the POH and the concurrent requests? 

> We've seen incidents where it's the LOH that fails to grow, in those cases it's been our own code trying to allocate.

I would assume this is your code then?

> @davidfowl the code using SslStream is outside of Kestrel, but we are using Kestrel in the app.

I'm trying to tease apart the pinning problem (GC not being able to clean these up at all), and the SSLStream pinning problem, which I don't quite understand. 

> This reproduces pretty rarely (on the order of once a month or so, though we're concerned it could happen more frequently under higher load), unfortunately, as it's sensitive to GC and request timing. It took us a few months to come to this conclusion, in part because we didn't have an easy repro to test hypotheses - as noted in the issue, we ended up using Perfview to find where appropriately sized pins were happening and then interrogating the source.

Got it. Correlating some of the metrics might help as well.

**Comment by wfurt** [comment]
I think suggestion from @stephentoub is good one if you have situation when you waiting for data to arrive e.g. have large number of idle stream. https://github.com/dotnet/runtime/pull/49743 tried to make it possible that you can hand in buffer and `SslStream` would avoid using intermediate arrays when possible. However, we would still need enough to fit in full TLS frame. We _could_ use less but we don't know the size until we read frame header. so if we start with small buffer we would need to do something about it.

**Comment by davidfowl** [comment]
> We could use less but we don't know the size until we read frame header. so if we start with small buffer we would need to do something about it.

Shouldn't we model this after what we do with websockets? Allocate enough buffer for the header frame only and delegate everything else to the user buffer.

**Comment by wfurt** [comment]
We could but if we read header separate it would be extra system call. (likely) 
While we generally optimize for throughput I start wondering if we _could_ have some toggle to make it more memory conservative - perhaps with AppContext to start with.

**Comment by davidfowl** [comment]
Please no app context switch. Make it local to the instance 😄. Also we should measure before adding switches. There's no syscall on linux (ffi but not syscall)

**Comment by davidfowl** [comment]
> When an OOM is encountered it's because one of the LOH or POH were full, and when the GC did a full collection it was unable to shrink the ephemeral segment sufficiently to grow the needed heap.

I'm struggling with this part.

cc @Maoni0

**Comment by Maoni0** [comment]
yeh, that's possible. if you have pins that have "stretched" the heap out and those pins are still alive, we could do a full blocking GC and since we can't move those pins they will be there. and that means all the space before the last pin on the segment will be considered in use (since we can't let go of that free space). 

this situation will be better with regions. if you are using .net 6.0 already I can give you a clrgc.dll with the 7.0 GC implementation that you can load with an env var with your 6.0 build. are you interested in trying that?

I only read the last 2 comments but just wanted to point this out - 

> That Gen0 almost entirely free space hints that the GC recently ran a full collection.

this is very common with a collection of any generation, not just a full collection. as long as it's a compacting GC (and most ephemeral GCs are compacting GCs), you'd observe this when you have pins in gen0.

**Comment by davidfowl** [comment]
@kevin-montrose how many concurrent pending reads do you have today and are these SSLStream instances backed by a NetworkStream?

**Comment by kevin-montrose** [comment]
@davidfowl looking at GC handles the most recent crash had 1,790 `AsyncPinned` pins, which should be the upper bound on pending socket reads.  Tricky to say how many of those originate in `SslStream` vs Kestrel vs other app code - and unfortunately it looks like Watson has culled that dump, so all we've got are my notes and I can't go spelunking for more information.

Going off of the code, all the `SslStream`'s I've found _should_ be backed by `NetworkStream`s but I cannot prove that from my notes.

> this is very common with a collection of any generation, not just a full collection.

@Maoni0 I see, so I conflated "full" and "compacting" here.  Good to know.

> this situation will be better with regions. if you are using .net 6.0 already I can give you a clrgc.dll with the 7.0 GC implementation that you can load with an env var with your 6.0 build. are you interested in trying that?

I don't _think_ we're equipped to exercise that, but I'll double check.  Regardless, if this is less likely in upcoming .NET versions then that is good news.

**Comment by karelz** [comment]
Triage: Looks like a symptom that might justify changes in our SslStream - either 0-byte reads or renting buffers based on frame size.
We should investigate in 8.0.

**Comment by davidfowl** [comment]
I think we should invest in [this](https://github.com/dotnet/runtime/issues/76029#issuecomment-1256573336) essentially what @wfurt's PR tries to do to reduce the amount of buffering in SslStream. The pinning problem can be mitigated by user code (the caller owns the buffer). I assume this problem also exists on the write side but is much more unlikely unless there's TCP back pressure.

This would also improve the memory usage of SslStream in general.

**Comment by Maoni0** [comment]
@kevin-montrose if you could set an env var to load an additional dll, you could try it :) but I know your env is very strict so maybe that's not possible. let me know if you can try it!

**Comment by kevin-montrose** [comment]
@Maoni0 unfortunately, it doesn't look like we'll be able to try swapping out the GC.

**Comment by kevin-montrose** [comment]
@stephentoub it is slowly inching its way to production - testing suggests its effective, but we won't know definitively for a bit longer.

**Comment by stephentoub** [comment]
Cool, thanks.

**Comment by stephentoub** [comment]
Yes:
https://github.com/dotnet/runtime/issues/76029#issuecomment-1259781772

**Comment by kevin-montrose** [comment]
> @stephentoub it is slowly inching its way to production - testing suggests its effective, but we won't know definitively for a bit longer.

We've had this in production long enough, and gathered enough dumps, to say that zero-byte-read option has removed these pins.
