### ISSUE TITLE
DateTime.ParseExact randomly yielding wrong DateTime.Kind

### ISSUE THREAD

**Issue by DierkDroth** [dotnet/runtime#76037]
I have evidence that
`DateTime.ParseExact("20220922T140000", new[] { "yyyyMMddTHHmmss" }, null).Kind == Kind.Utc`

Expected as per [here ](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.parseexact?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(System.DateTime.ParseExact)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=net-6.0)would be
`DateTime.ParseExact("20220922T140000", new[] { "yyyyMMddTHHmmss" }, null).Kind == Kind.Unspecified`

> If s does not represent a time in a particular time zone and the parse operation succeeds, the [Kind](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.kind?view=net-6.0) property of the returned [DateTime](https://learn.microsoft.com/en-us/dotnet/api/system.datetime?view=net-6.0) value is [DateTimeKind.Unspecified](https://learn.microsoft.com/en-us/dotnet/api/system.datetimekind?view=net-6.0#system-datetimekind-unspecified).

However - and that's the weird part - I can't reproduce but only see it in my traces as I traced out the parameter from method call above.

I have no idea what's going on and why I only see this once in a while. Any guidance on what might be going wrong would be appreciated.

**Comment by DierkDroth** [comment]
@Jozkee I'm not sure: is there anything expected from me before someone would be able to look into that issue?

**Comment by dakersnar** [comment]
cc @tarekgh as this is DateTime related

**Comment by tarekgh** [comment]
@DierkDroth I spent some time looking and reviewing the runtime code to see if it can produce the result you are seeing, I couldn't find anyway produce it. 

I suggest you add more logs when you get this case like capture `CultureInfo.CurrentCulture` , `TimeZoneInfo.Local.Id`, and the parsed string.

**Comment by Clockwork-Muse** [comment]
Side note: the documentation recommends you use the invariant culture when parsing without date and time separators.  I don't expect this to solve your problem, but really any time there isn't a culture-aware value that should likely be the case anyways (for date/times, no month or day names, mostly).

**Comment by DierkDroth** [comment]
Thanks guys. I'll follow up as I have more information

**Comment by tarekgh** [comment]
@DierkDroth I am closing the issue but feel free to ping back when you have more info, and we can reopen. Thanks for your report.
