### ISSUE TITLE
[API Proposal]: Add System.Runtime.CompilerServices.RefSafetyRulesAttribute

### ISSUE THREAD

**Issue by cston** [dotnet/runtime#76032]
### Background and motivation

The C# compiler emits a `[module: RefSafetyRules(11)]` attribute to modules compiled with `-langversion:11` or above, or compiled with .NET 7 or above, to indicate that the module was compiled with C#11 ref safety rules.

The `RefSafetyRulesAttribute` type definition should be added to the BCL to avoid having the compiler emit the attribute definition to each module.

See [RefSafetyRulesAttribute](https://github.com/dotnet/csharplang/blob/main/proposals/low-level-struct-improvements.md#refsafetyrulesattribute).

### API Proposal

```csharp
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Module, AllowMultiple = false, Inherited = false)]
    public sealed class RefSafetyRulesAttribute : Attribute
    {
        public RefSafetyRulesAttribute(int version) { Version = version; }
        public int Version;
    }
}
```

### API Usage

The `RefSafetyRulesAttribute` type is for compiler use only - it is not permitted in source.

**Comment by cston** [comment]
cc @jaredpar, @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
@cston This looks like a .NET 7 need, correct?

**Comment by cston** [comment]
@AaronRobinsonMSFT, this can wait until .NET 8.

**Comment by stephentoub** [comment]
There are other attributes the compiler will emit as internal into an assembly and that we haven't exposed from corelib, e.g. `NullableAttribute`, `NullableContextAttribute`, `EmbeddedAttribute`, maybe others?  They are similarly not meant to be uttered in source.  Are we interested in bringing them all into corelib as public?  I'm wondering if/how RefSafetyRules is special.

**Comment by jaredpar** [comment]
> I'm wondering if/how RefSafetyRules is special

The other ones require some level of opt in. For instance you aren't going to see any of the `Nullable*` ones unless you opt into nullability in some way. It's pay for play in that way. 

The ref safety rules one though we include on almost all assemblies. There isn't as much of a trigger to opt into ref rules. Originally we conditioned the rule on a signature having a `out`, `ref` or `ref struct` parameter or return. That didn't sit 100% right with us. There was worry about missing checks, future proofing, etc ... and eventually felt it was better to just emit always. At that point it felt like it was better to have in corelib. 

Also if there was a better trigger for when to emit this, be willing to listen to that option 😄

**Comment by vitek-karas** [comment]
Is the `RefSafetyRulesAttribute` used for anything at runtime? If not we should probably add it to the list of attributes aggressive trimming removes by default - otherwise this adds two types into every assembly (`RefSafetyRulesAttribute` and `EmbeddedAttribute`), yes they are small... but still.

/cc @marek-safar

**Comment by AaronRobinsonMSFT** [comment]
No, it is not. It can be removed during trimming of a final application. It must be kept on assemblies that will be used during build or else things could be very very very ... bad.

**Comment by bartonjs** [comment]
* We changed the Version field to a Version get-only property
* Otherwise, looks good as proposed.

```C#
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Module, AllowMultiple = false, Inherited = false)]
    public sealed class RefSafetyRulesAttribute : Attribute
    {
        public RefSafetyRulesAttribute(int version) { Version = version; }
        public int Version { get; }
    }
}
```

**Comment by deeprobin** [comment]
@AaronRobinsonMSFT 
Does this API require a special handling in coreclr or is it just the implementation of this attribute?

**Comment by stephentoub** [comment]
It's just the attribute.

**Comment by AaronRobinsonMSFT** [comment]
> It's just the attribute.

Right. This issue is just about adding it to the product and updating the appropriate ref assembly. We typically add a test too, for completeness and verifying it works with reflection.

**Comment by stephentoub** [comment]
> We typically add a test too, for completeness and verifying it works with reflection.

In this case, we'll also want to validate that the compiler recognizes this attribute and stops emitting into all of our assemblies its own internal copy.

**Comment by hamarb123** [comment]
Out of curiosity, is there any reason to not do this for the other generated attribute types that always seem to be generated?
<img width="235" alt="image" src="https://user-images.githubusercontent.com/25316035/213859530-24608f52-165b-4b44-8c18-50df56cf1413.png">

**Comment by Zastai** [comment]
> Out of curiosity, is there any reason to not do this for the other generated attribute types that always seem to be generated? <img alt="image" width="235" src="https://user-images.githubusercontent.com/25316035/213859530-24608f52-165b-4b44-8c18-50df56cf1413.png">

As mentioned near the top of this issue, the nullability ones are opt-in (usually by having `<Nullable>enable</Nullable>` in the project). I think `EmbeddedAttribute` only gets emitted when used, i.e. when any other embedded attribute is emitted.
