### ISSUE TITLE
HttpStress is broken on Windows (CAP_SYS_PTRACE)

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#76045]
CI runs are broken since 9/22, ~need to check local runs~.

https://dev.azure.com/dnceng-public/public/_build/results?buildId=26259&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=abae1f68-3c73-5bff-491f-f2b908580ce6

```
Creating httpstress_server_1 ... error
ERROR: for httpstress_server_1  Cannot create container for service server: invalid CapAdd: unknown capability: "CAP_SYS_PTRACE"
ERROR: for server  Cannot create container for service server: invalid CapAdd: unknown capability: "CAP_SYS_PTRACE"
```

*Edit (pasting comment from below):*

I cannot reproduce this locally. dotnet/dnceng was there any change around  9/22 that may have affected
- the `NetCore-Public` pool -OR-
- the `1es-windows-2022-open` image -OR-
- the [`stress/http.yml`](https://github.com/dotnet/runtime/blob/main/eng/pipelines/libraries/stress/http.yml) pipeline
?

Seeing an error about `CAP_SYS_PTRACE` on Windows is super esoteric.

**Comment by antonfirsov** [comment]
I cannot reproduce this locally. @dotnet/dnceng was there any change around  9/22 that may have affected
- the `NetCore-Public` pool -OR-
- the `1es-windows-2022-open` image -OR-
- the [`stress/http.yml`](https://github.com/dotnet/runtime/blob/main/eng/pipelines/libraries/stress/http.yml) pipeline
?

Seeing and error about `CAP_SYS_PTRACE` on Windows is super esoteric.

**Comment by jonfortescue** [comment]
There was a rollout yesterday, but I don't know of anything that would affect the first two things. Looks like nothing has changed in the pipeline for the last 22 days. cc/ @alexperovich who might know if there was anything going on in NetCore-Public.

**Comment by antonfirsov** [comment]
> nothing has changed in the pipeline for the last 22 days

I didn't mean direct changes to the pipeline, but any infrastructure change that may have affected it. There were no changes around the tests at all in the last few weeks.

**Comment by MattGal** [comment]
@antonfirsov , the "`1es-windows-2022-open`" image changes dynamically with the (weekly) rollouts of the hosted build images.    From looking at the "git blame" on this file: https://github.com/actions/runner-images/blame/main/images/win/Windows2022-Readme.md that's the most likely thing that broke you.  Specifically:


```
| Announcements |
|-|
| [[Windows] Docker EE will be replaced with Docker CE / Moby on September, 19](https://github.com/actions/runner-images/issues/6181) |
```
... changing the docker engine's date correlates suspiciously with your docker problem. What I would try in this circumstance is either fiddling with the settings you're using starting docker, or trying the `build.server.amd64.vs2019.open` image, upon which we install docker from the Windows gallery and so things may work differently there.

**Comment by wfurt** [comment]
thanks for looking @MattGal. I don't know if we really need `CAP_SYS_PTRACE` -> I would expect it is mostly for debugging e.g. nice to have.

**Comment by antonfirsov** [comment]
`CAP_SYS_PTRACE` seems to be Linux-specific, seeing it on Windows doesn't make sense to me.

**Comment by ManickaP** [comment]
> thanks for looking @MattGal. I don't know if we really need `CAP_SYS_PTRACE` -> I would expect it is mostly for debugging e.g. nice to have.

It comes from here: https://github.com/dotnet/runtime/blob/c6f5267686688aeabaa84aeb02efc2b411e7d64b/src/libraries/System.Net.Http/tests/StressTests/HttpStress/docker-compose.yml#L11
I added it to within PR that collected dumps from the docker.

**Comment by wfurt** [comment]
It would be nice to get dumps but we may roll it out temporarily to at least get the stress running @antonfirsov.

**Comment by antonfirsov** [comment]
I will try to make this `cap_add` conditional to Linux, since it doesn't look like ptrace is a thing on Windows:

https://github.com/dotnet/runtime/blob/c6f5267686688aeabaa84aeb02efc2b411e7d64b/src/libraries/System.Net.Http/tests/StressTests/HttpStress/docker-compose.yml#L23-L24
