### ISSUE TITLE
ILGenerator.Emit produces Method not found

### ISSUE THREAD

**Issue by Kation** [dotnet/runtime#76082]
### Description

Reference to #25958, it is not over yet.

I got a `MissingMethodException` exception with message：
Method not found: 'Void Wodsoft.ComBoost.DomainExecutionContext..ctor(Wodsoft.ComBoost.Wodsoft.ComBoosIDomainService, Wodsoft.ComBoost.IDomainContext, System.Reflection.MethodInfo, System.Object[])'
Which method is: https://github.com/Kation/ComBoost/blob/b3bc17747b4dcf40cda7450b7e5c1c68dcb5b0ec/src/Wodsoft.ComBoost/DomainExecutionContext.cs#L26-L39
There is no generic types/methods
And emit code is there: https://github.com/Kation/ComBoost/blob/b3bc17747b4dcf40cda7450b7e5c1c68dcb5b0ec/src/Wodsoft.ComBoost/DomainServiceInvokerBuilder.cs#L209

### Reproduction Steps

I have no way to reproduction, it is random.

### Expected behavior

Execute correctly

### Actual behavior

Throw a `MissingMethodException` in random with very low probability.

### Known Workarounds

Restart program

### Configuration

.NET 6 Runtime

**Comment by Kation** [comment]
I got a message with `Method not found: 'Void Wodsoft.ComBoost.DomainExecutionContext..ctor(t.IDomainService, Wodsoft.ComBoost.IDomainContext, System.Reflection.ection, System.Object[])` a month ago.

**Comment by steveharter** [comment]
In regards to https://github.com/dotnet/runtime/issues/25958, that assumed the issue was only with `in` modifier + generic types.

**Comment by steveharter** [comment]
The exception has "Wodsoft.ComBoost.Wodsoft.ComBoosIDomainService" for the first parameter type but I can't seem to find that type. Is that a dynamically or externally created type? Does it implement [IDomainService](https://github.com/Kation/ComBoost/blob/bc688f6f1374618578e0c12d85000a2b5f4ef157/src/Wodsoft.ComBoost.Core/IDomainService.cs)  since the first parameter [is defined as `IDomainService`](https://github.com/Kation/ComBoost/blob/b3bc17747b4dcf40cda7450b7e5c1c68dcb5b0ec/src/Wodsoft.ComBoost/DomainServiceInvokerBuilder.cs#L19)?

Also after the call to the ctor, the IL attempts to [call `Initialize()`](https://github.com/Kation/ComBoost/blob/b3bc17747b4dcf40cda7450b7e5c1c68dcb5b0ec/src/Wodsoft.ComBoost/DomainServiceInvokerBuilder.cs#L210) on the new object which is declared as
```protected internal static readonly MethodInfo _Initialize = typeof(IDomainService).GetMethod("Initialize");```
but `IDomainServive` doesn't have an `Initialize`:
https://github.com/Kation/ComBoost/blob/bc688f6f1374618578e0c12d85000a2b5f4ef157/src/Wodsoft.ComBoost.Core/IDomainService.cs#L12.

**Comment by Kation** [comment]
@steveharter `Wodsoft.ComBoost.Wodsoft.ComBoosIDomainService` is not exists. This is way I post this bug. When it throw `MissingMethodException`, there must be a parameter with wrong. And the emit code is never changed.

The code is in `next` branch.  https://github.com/Kation/ComBoost/blob/bcca31eadcbd7dbcb04861b4335f108af9bb8162/src/Wodsoft.ComBoost.Core/IDomainService.cs#L23

**Comment by steveharter** [comment]
> `Wodsoft.ComBoost.Wodsoft.ComBoosIDomainService is not exist`

Thanks. So there is some sort of corruption with the token or type name.

> The code is in next branch.

I see - the types make sense now

**Comment by steveharter** [comment]
@Kation what type of environment is the code running in that fails? I see you said in the issue description that the configuration was ".NET 6 Runtime" but the projects are set up to use NetStandard. Mostly ensuring that Mono, Native AOT or .NET Framework is not being used. Any other detail here around the configuration may be useful.

Also does the exception seem to occur once the application has been running for a while (after the `newobj` already was previously successful) , or does it seem to occur during startup or the first time the `newobj` was encountered?

**Comment by Kation** [comment]
@steveharter  Now we use .NET 6.0.5 runtime from officially docker image.

A dynamic class is creating mean there is a calling first time to a method of `IDomainService` right now. Then exception occurred.  It is only occurred in this dynamic class although they are creating together by [`DomainServiceInvokerBuilder cctor`](https://github.com/Kation/ComBoost/blob/b3bc17747b4dcf40cda7450b7e5c1c68dcb5b0ec/src/Wodsoft.ComBoost/DomainServiceInvokerBuilder.cs#L131), not all of them.

And I found that there is an exception too at [there](https://github.com/Kation/ComBoost/blob/b3bc17747b4dcf40cda7450b7e5c1c68dcb5b0ec/src/Wodsoft.ComBoost/DomainTemplateBuilder.cs#L213). Message is:   
Method not found: 'System.Type System.Type.GetTypeFromHandle(System.request)'.

**Comment by Kation** [comment]
I have confirmed that exception is not only occurring while application startup, but also happened in 2 hours later after startup when first time to call method of `IDomainService`.

**Comment by steveharter** [comment]
@Kation can you verify the issue still occurs in 7.0?

If it does, then we'll need to get a repro of some form.

Thanks

**Comment by Kation** [comment]
@steveharter I catch the wrong IL code of this dynamic [`method`](https://github.com/Kation/ComBoost/blob/b3bc17747b4dcf40cda7450b7e5c1c68dcb5b0ec/src/Wodsoft.ComBoost/DomainServiceInvokerBuilder.cs#L166-L229) by `MethodInfo.GetMethodBody().GetILAsByteArray()`

This time the message is:
`System.MissingMethodException: Method not found: 'Void Wodsoft.ComBoost.DomainExecutionContext..ctor(Wodsoft.ComBoost.Wodsoft.ComBoosIDomainService, Wodsoft.ComBoost.IDomainContext, System.Reflection.System.ReflMethodInfo, System.Object[])'.`

[InvokeAsync.zip](https://github.com/dotnet/runtime/files/9771637/InvokeAsync.zip)

**Comment by Kation** [comment]
@steveharter I have tried to use .NET 7 RC2, it is still occurred.  
`System.MissingMethodException: Method not found: 'Void Wodsoft.ComBoost.DomainExecutionContext..ctor(Wodsoft.ComBoost.IDomainService, Wodsoft.ComBoost.IDomainContext, System.Reflection.System.ReflMethodInfo, System.Object[])'.`

**Comment by steveharter** [comment]
> @steveharter I have tried to use .NET 7 RC2, it is still occurred.

Thanks. It looks like the name of the type still gets corrupted:
_Void Wodsoft.ComBoost.DomainExecutionContext..ctor(Wodsoft.ComBoost.IDomainService, Wodsoft.ComBoost.IDomainContext, **System.Reflection.System.ReflMethodInfo**, System.Object[])_

Here's the original corruption (from the issue description)
_Void Wodsoft.ComBoost.DomainExecutionContext..ctor(**Wodsoft.ComBoost.Wodsoft.ComBoosIDomainService**, Wodsoft.ComBoost.IDomainContext, System.Reflection.MethodInfo, System.Object[])_

and the more recent find above:
_Void Wodsoft.ComBoost.DomainExecutionContext..ctor(**Wodsoft.ComBoost.Wodsoft.ComBoosIDomainService**, Wodsoft.ComBoost.IDomainContext, **System.Reflection.System.ReflMethodInfo**, System.Object[])_

**Comment by steveharter** [comment]
> [InvokeAsync.zip](https://github.com/dotnet/runtime/files/9771637/InvokeAsync.zip)

What does this zip file contain (or supposed to contain)? It just has a single "InvokeAsync" file with no extension.

**Comment by steveharter** [comment]
@Kation can you provide a consistent repo or at least repo instructions?

**Comment by Kation** [comment]
@steveharter `InvokeAsync` file is an IL binary content from `MethodInfo.GetMethodBody().GetILAsByteArray()` of corruption method.
I can't make a simple project to reproduce corruption. It seems occur in complicated conditions.
I try to make a simple concurrent environment but not working.

[EmitCallBug.zip](https://github.com/dotnet/runtime/files/9856857/EmitCallBug.zip)
