### ISSUE TITLE
[External] zlib has suppressed warnings

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#76095]
The following externally consumed projects require suppression of warnings that are unadvised. We should be fixing these issues and offering those fixes upstream.

## zlib
https://github.com/dotnet/runtime/blob/89962a54d60e4d9c9837012d1729c5a72ec748cd/src/native/external/zlib-intel.cmake#L2
https://github.com/dotnet/runtime/blob/89962a54d60e4d9c9837012d1729c5a72ec748cd/src/native/external/zlib.cmake#L2
https://github.com/dotnet/runtime/blob/6c3c2347bd99582fc42a62e5b68edba2e0ab1483/src/mono/mono/mini/CMakeLists.txt#L341

**Comment by danmoseley** [comment]
Could this be help wanted label?

**Comment by GrabYourPitchforks** [comment]
C4244 was addressed via https://github.com/dotnet/runtime/pull/91245 and the zlib patch will be merged upstream in 1.3.1.1.

IIRC the mono build work is still outstanding.

**Comment by ericstj** [comment]
I believe this is now resolved with the move to zlib-ng and https://github.com/dotnet/runtime/pull/105433  cc @carlossanlop
