### ISSUE TITLE
Mono interpreter crashing when calling constructor with 1000 parameters

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#76093]
> Do the crashes with large number of constructor arguments go away when you use reflection-based path?

It appears that the crashes persist, even when reflection is used. So @jkotas is right, the 1000 parameter test class must be hitting limits inherent in the interpreter. I'll simply disable the test for the interpreter and revert the fallback commit.

_Originally posted by @eiriktsarpalis in https://github.com/dotnet/runtime/pull/75982#discussion_r978900267_

**Comment by filipnavara** [comment]
Related: https://github.com/dotnet/runtime/pull/76092

**Comment by jkotas** [comment]
Fixed by #76092
