### ISSUE TITLE
Address-exposure of promoted struct fields used by instance methods

### ISSUE THREAD

**Issue by SingleAccretion** [dotnet/runtime#76096]
There exists this bit of code in the compiler:

https://github.com/dotnet/runtime/blob/d0559e6e33906e4e6db675e646b47ab36eb5bffc/src/coreclr/jit/lclmorph.cpp#L611-L616

Which avoids marking the whole struct local address-exposed in case only one of its field locals would become such due to being used by an instance method. The rationale given is that it would be "highly unusual" for an instance method to reach outside the owner object and modify other fields of the struct.

However, much less unusual (and certainly not UB) would be for this method to return a reference to itself:
```cs
struct ParentStruct
{
    public SmallStruct Field;
    public int AnotherField;
}

struct SmallStruct
{
    public int Value;

    [UnscopedRef]
    [MethodImpl(MethodImplOptions.NoInlining)]
    public ref int GetSelfRef() => ref Value;
}
```
...which the caller could then use with ref arithmetic, confusing the Jit in the process.

Historically, we have been "generous" in supporting various patterns of unsafe code in the Jit (for example, we fully anticipate people to reach across promoted fields with out-of-bounds writes). Should we allow this one too?

FWIW, local SPMI shows disabling this optimization to have rather small impact (e. g. `(2 improved, 0 regressed)` for benchmarks, `(0 improved, 4 regressed)` for aspnet).

@dotnet/jit-contrib

**Comment by jakobbotsch** [comment]
I think removing the special case is fine if the diffs are so small. It's a little odd though, the comments indicate that the diffs were large at some point, so I wonder what changed.
