### ISSUE TITLE
[API Proposal]: {Last}IndexOf{AnyExcept}Range

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#76106]
### Background and motivation

In looking over various code bases, it's relatively common to want to search for things in or out of a particular range.

For example, check whether the input contains anything outside of the range [0x20, 0x7e]:
https://github.com/dotnet/runtime/blob/fa5dcda23c681031b5d2bd68482702baef80b836/src/libraries/Common/src/System/Net/HttpValidationHelpers.cs#L26-L33

Or find the next index that's not an ASCII digit:
https://github.com/dotnet/runtime/blob/239ff8686ff921f48f74c7a292c1231c7d444130/src/libraries/Common/src/System/Net/IPv6AddressHelper.Common.cs#L188-L194

Or find the index of the first ASCII digit:
https://github.com/dotnet/runtime/blob/239ff8686ff921f48f74c7a292c1231c7d444130/src/libraries/System.Private.CoreLib/src/System/Environment.OSVersion.Unix.cs#L32-L39

Or determine whether the input contains anything outside of the range of a byte:
https://github.com/dotnet/runtime/blob/239ff8686ff921f48f74c7a292c1231c7d444130/src/libraries/System.Net.Http/src/System/Net/Http/Headers/UriHeaderParser.cs#L68-L79

Or find the index of the first upper-case ASCII letter:
https://github.com/dotnet/runtime/blob/239ff8686ff921f48f74c7a292c1231c7d444130/src/libraries/System.Private.CoreLib/src/System/Globalization/TextInfo.cs#L431-L439

Or find the first index of a value that's at least some integer:
https://github.com/dotnet/runtime/blob/239ff8686ff921f48f74c7a292c1231c7d444130/src/libraries/System.Private.CoreLib/src/System/Globalization/EastAsianLunisolarCalendar.cs#L387-L393

Etc.  Today we don't provide an IndexOfXx method that makes it easy to search for such ranges.  And even if/when we provide a more general and vectorized IndexOfAny that supports more than 5 characters (https://github.com/dotnet/runtime/issues/68328), it's likely that such a method will be both harder to use (e.g. an initialization method and the actual method) and less efficient (because it's more complicated) than if we just have an IndexOfRange that lets you search for a simple range of values.

### API Proposal

```diff
namespace System

public static class MemoryExtensions
{
+    public static int IndexOfRange<T>(this ReadOnlySpan<T> span, T lowInclusive, T highInclusive) where T : IComparable<T>;
+    public static int IndexOfRange<T>(this Span<T> span, T lowInclusive, T highInclusive) where T : IComparable<T>;

+    public static int IndexOfAnyExceptRange<T>(this ReadOnlySpan<T> span, T lowInclusive, T highInclusive) where T : IComparable<T>;
+    public static int IndexOfAnyExceptRange<T>(this Span<T> span, T lowInclusive, T highInclusive) where T : IComparable<T>;

+    public static int LastIndexOfRange<T>(this ReadOnlySpan<T> span, T lowInclusive, T highInclusive) where T : IComparable<T>;
+    public static int LastIndexOfRange<T>(this Span<T> span, T lowInclusive, T highInclusive) where T : IComparable<T>;

+    public static int LastIndexOfAnyExceptRange<T>(this ReadOnlySpan<T> span, T lowInclusive, T highInclusive) where T : IComparable<T>;
+    public static int LastIndexOfAnyExceptRange<T>(this Span<T> span, T lowInclusive, T highInclusive) where T : IComparable<T>;
}
```

- There are 8 methods/overloads here for: Span vs ReadOnlySpan, inclusive vs exclusive, first vs last.
- We can vectorize these, but only for built-in types where we know the semantics of the vector comparisons matches the semantics of the `INumber<T>` implementations.  That's the same set of types as what we already vectorize in other operations, but as we're able to open up that set further (e.g. https://github.com/dotnet/runtime/issues/75642), it likely won't extend to these.
- I've marked the constraint as being non-nullable; I don't know what it would mean to have a null low/high value. But if we think there's a good reason to allow it, we could make the constraints be `?`. My intent is the implementation will validate that the range values are non-null.
- With char.IsBetween, we decided to consider it undefined behavior if high < low, and we don't validate high >= low.  My intent here is to do the same.

### API Usage

```C#
internal static bool IsOnlyDigits(string str, int offset, int count) =>
    str.AsSpan(offset, count).IndexOfAnyExceptRange('0', '9') < 0;
```

**Comment by danmoseley** [comment]
Based on past experience of vectorizing similar methods, there'll potentially be a penalty for the shortest inputs. Is it possible that some of the above examples would be faster remaining in their current form?

**Comment by stephentoub** [comment]
> Is it possible that some of the above examples would be faster remaining in their current form? (Eg the IP address example)

Possible, sure. There may be an extra few nanoseconds if the input is really small.

**Comment by terrajobst** [comment]
* We should rename the methods to say `InRange` and include `Any` for consistency.

```C#
namespace System;

public partial class MemoryExtensions
{
    public static int IndexOfAnyInRange<T>(this ReadOnlySpan<T> span, T lowInclusive, T highInclusive) where T : IComparable<T>;
    public static int IndexOfAnyInRange<T>(this Span<T> span, T lowInclusive, T highInclusive) where T : IComparable<T>;

    public static int IndexOfAnyExceptInRange<T>(this ReadOnlySpan<T> span, T lowInclusive, T highInclusive) where T : IComparable<T>;
    public static int IndexOfAnyExceptInRange<T>(this Span<T> span, T lowInclusive, T highInclusive) where T : IComparable<T>;

    public static int LastIndexOfAnyInRange<T>(this ReadOnlySpan<T> span, T lowInclusive, T highInclusive) where T : IComparable<T>;
    public static int LastIndexOfAnyInRange<T>(this Span<T> span, T lowInclusive, T highInclusive) where T : IComparable<T>;

    public static int LastIndexOfAnyExceptInRange<T>(this ReadOnlySpan<T> span, T lowInclusive, T highInclusive) where T : IComparable<T>;
    public static int LastIndexOfAnyExceptInRange<T>(this Span<T> span, T lowInclusive, T highInclusive) where T : IComparable<T>;
}
```
