### ISSUE TITLE
System.Text.Encoding.CodePages

### ISSUE THREAD

**Issue by DenGhostYY** [dotnet/runtime#76102]
I have a problem. I have downloaded the library System.Text.Encoding.CodePages with Package Manager in console application in Visual Studio 2022
```
NuGet\Install-Package System.Text.Encoding.CodePages -Version 6.0.0
```
The library has been successfully installed. But when I wrote
```using System.Text.Encoding.CodePages;```
and tried to compile, I got an error "error CS0426: Type name 'CodePages' does not exist in type 'Encoding'.". As far as I understood, the subspace "Encoding" conflicts with the class "System.Text.Encoding". There has already been a discussion of this issue https://github.com/dotnet/core/issues/2754, but ```using .Text;``` not suitable for solving this problem. Can you please tell me how to make the compiler correctly consider this ```using```?

**Comment by tarekgh** [comment]
>  have downloaded the library System.Text.Encoding.CodePages with Package Manager in console application in Visual Studio 2022

You don't need to do that anymore. This library is part of the shared framework so you can just use it. 

> using System.Text.Encoding.CodePages;

use `using System.Text`. That all what you need.

I am closing the issue but feel free to send any more questions we can help with.
