### ISSUE TITLE
List<> should use faster write barriers

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#76104]
I wonder if we can special-case `List<>` for e.g. final types like `string` to avoid slow `stelm.ref` helpers and use `CORINFO_HELP_ASSIGN_REF` directly.
```csharp
void SetValue(List<string> l) => l[0] = "hello";
```

```asm
; Method SetValue(List`1[System.String])
G_M28131_IG01:              
       56                   push     rsi
       4883EC20             sub      rsp, 32
       488BF1               mov      rsi, rcx
G_M28131_IG02:              
       837E1000             cmp      dword ptr [rsi+10H], 0
       761E                 jbe      SHORT G_M28131_IG04
       488B4E08             mov      rcx, gword ptr [rsi+08H]
       33D2                 xor      edx, edx
       49B86824D8F3A7020000 mov      r8, 0x2A7F3D82468      ; 'hello'
       E8BD1EFFFF           call     CORINFO_HELP_ARRADDR_ST
       FF4614               inc      dword ptr [rsi+14H]
G_M28131_IG03:              
       4883C420             add      rsp, 32
       5E                   pop      rsi
       C3                   ret      
G_M28131_IG04:              
       FF150EB90E00         call     [System.ThrowHelper:ThrowArgumentOutOfRange_IndexMustBeLessException()]
       CC                   int3     
```
Same for other List's methods like Add, etc.

PS: technically, it can be fixed if we introduce ref-type generic specialization? (custom attribute or PGO driven)

**Comment by dubiousconst282** [comment]
I believe this is caused by the array covariance curse. There's a trick with wrapper structs which results in a call to ASSIGN_REF instead of ARR_ST, see https://github.com/dotnet/coreclr/pull/23571.

Also related: https://github.com/dotnet/runtime/issues/23393, https://github.com/dotnet/runtime/issues/32879.

**Comment by EgorBo** [comment]
> I believe this is caused by the array covariance curse.

Yes it is, it was implied by faster barriers (where we don't perform type check). Didn't know about https://github.com/dotnet/coreclr/pull/23571 since it was closed as "no interest" let me close this too then
