### ISSUE TITLE
Why TrimEndChars was removed?

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#76122]
PowerShell does still cleanup paths from special chars and a comment say this was copied from .Net Framework ` System.IO.Path`.
https://github.com/PowerShell/PowerShell/blob/7d6a79891364c1f6f7ed7f661d1110519af4affa/src/System.Management.Automation/engine/Utils.cs#L1477-L1480

I don't see this in current .Net. Last where I found this is https://github.com/dotnet/corefx/pull/3549. After that PR it seems the `TrimEndChars` is not used.

@stephentoub @JeremyKuhne @ericstj Could you please explain why this was removed if you remember the context? Was this done for performance as a compromise or conclusion was "no need at all"? Or current .Net still does the cleanup but I don't see?

I'd want to understand can we safely remove this from PowerShell or should keep.

**Comment by stephentoub** [comment]
It was for correctness; we defer to the OS now rather than trying to enforce additional constraints that might be superfluous and otherwise prevent valid paths.

**Comment by iSazonov** [comment]
Thank you! That's enough to make a decision for PowerShell.
