### ISSUE TITLE
[Bug] System.Text.Json can't parse Json ( returned from server using Python json.dumps() ) ?

### ISSUE THREAD

**Issue by SunshineSpring666** [dotnet/runtime#76130]
### Description

Python server returns the following Json string ( using Python json.dumps() ):
"{\"code\":0,\"data\":\"[{\\\"Names\\\":\\\"[\\\\\\\"\\\\u5f91\\\\u9a78\\\\\\\", \\\\\\\"\\\\u5f25\\\\u6622\\\\u6656\\\\\\\"]\\\", \\\"registry\\\": null}]\"}"

System.Text.Json fails to deserialize it, due to its strict format requirement:    
(backward slash)\"  should be  "
"[  should be  [
]"  should be  ]

But doing such string replacement is not safe. 
 [json.dumps(](https://docs.python.org/3/library/json.html)) is widely used in Python server, so I'm wondering if anyone faces such issues?
Are there any ways to directly parse the above Json format, without the need of any custom converter or string replacement?

### Reproduction Steps

Please run the attached demo project:
[maapp.zip](https://github.com/dotnet/runtime/files/9639248/maapp.zip)

Code clips:
```C#
    public string JsonReturnedFromServer { get; set; } = "{\"code\":0,\"data\":\"[{\\\"Names\\\":\\\"[\\\\\\\"\\\\u5f91\\\\u9a78\\\\\\\", \\\\\\\"\\\\u5f25\\\\u6622\\\\u6656\\\\\\\"]\\\", \\\"registry\\\": null}]\"}";
    public string DataStrUseSystemTextJsonServerJson { get; set; }
    public string DataStrUseNewtonsoftServerJson { get; set; }
    public string DataStrUseSystemTextJsonSerialization { get; set; }


    private void UseSystemTextJson(object sender, EventArgs e)
    {
        try
        {
            JsonSerializerOptions options = new JsonSerializerOptions()
            {
                AllowTrailingCommas = true,
                NumberHandling = JsonNumberHandling.AllowReadingFromString
            };
            options.Converters.Add(new StringConverter());
            var dict = System.Text.Json.JsonSerializer.Deserialize<Dictionary<string, object>>(JsonReturnedFromServer, options);
            DataStrUseSystemTextJsonServerJson = dict["data"].ToString();
            // NOT SAFE to do such replacement for injection / parsing failure possibilities
            string parsedData = DataStrUseSystemTextJsonServerJson.Replace("\\\"", "\"").Replace("\"[", "[").Replace("]\"", "]");
            var dat = System.Text.Json.JsonSerializer.Deserialize<ObservableCollection<MyPoco>>(parsedData);
            Console.WriteLine(dat.Count);
        }
        catch (Exception ex)
        { Toast.Make(ex.Message).Show(); }
    }

    private void UseNewtonsoft(object sender, EventArgs e)
    {
        try
        {
            var dict = JsonConvert.DeserializeObject<Dictionary<string, string>>(JsonReturnedFromServer);
            DataStrUseNewtonsoftServerJson = dict["data"].ToString();
            var dat = JsonConvert.DeserializeObject<ObservableCollection<MyPoco>>(DataStrUseNewtonsoftServerJson);
            Console.WriteLine(dat.Count);
        }
        catch (Exception ex)
        { Toast.Make(ex.Message).Show(); }
    }

    private void SystemTextJsonTest(object sender, EventArgs e)
    {
        try
        {
            var value = new ObservableCollection<MyPoco>() { new MyPoco() };
            Dictionary<string, object> data = new Dictionary<string, object>() { { "code", 0 }, { "data", value } };

            JsonSerializerOptions options = new JsonSerializerOptions()
            {
                AllowTrailingCommas = true,
                NumberHandling = JsonNumberHandling.AllowReadingFromString
            };
            //options.Converters.Add(new StringConverter());
            string json = System.Text.Json.JsonSerializer.Serialize(data, options);
            Console.WriteLine(json);

            var dict = System.Text.Json.JsonSerializer.Deserialize<Dictionary<string, object>>(json, options);
            DataStrUseSystemTextJsonSerialization = dict["data"].ToString();
            var dat = System.Text.Json.JsonSerializer.Deserialize<ObservableCollection<MyPoco>>(DataStrUseSystemTextJsonSerialization);
            Console.WriteLine(dat.Count);
        }
        catch (Exception ex)
        { Toast.Make(ex.Message).Show(); }
    }
}

public class MyPoco
{
    //[System.Text.Json.Serialization.JsonConverter(typeof(ObservableConverter<string>))]
    public ObservableCollection<string> Names { get; set; } = new ObservableCollection<string> { "徑驸", "弥昢晖" };
}

public class ObservableConverter<T> : System.Text.Json.Serialization.JsonConverter<ObservableCollection<T>>
{
    public override ObservableCollection<T> Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        string str = reader.GetString();
        str = str != "" ? str : "[]";
        List<T> ls = System.Text.Json.JsonSerializer.Deserialize<List<T>>(str);
        ObservableCollection<T> obs = new ObservableCollection<T>(ls);
        return obs;
    }

    public override void Write(Utf8JsonWriter writer, ObservableCollection<T> value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(System.Text.Json.JsonSerializer.Serialize(((value as ObservableCollection<T>).ToList())));
    }
}


public class StringConverter : System.Text.Json.Serialization.JsonConverter<string>
{
    public override string Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {

        if (reader.TokenType == JsonTokenType.Number)
        {
            var stringValue = reader.GetInt32();
            return stringValue.ToString();
        }
        else if (reader.TokenType == JsonTokenType.String)
        {
            return reader.GetString();
        }
        else if (reader.TokenType == JsonTokenType.StartArray)
        {
            return reader.GetString();
        }

        throw new System.Text.Json.JsonException();
    }

    public override void Write(Utf8JsonWriter writer, string value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value);

    }

}
```
### Expected behavior

Such Json string from Python server should be able to be parsed directly, without any manual parsing of the original string.

### Actual behavior

Custom converter needs to be added on each and every ObservableCollection<T> properties.

### Configuration

.Net 7
Windows 11 preview beta
x64

**Comment by startewho** [comment]
your string is a escaped json string string,not a json object.
you firstly should remove the json escaped.

**Comment by SunshineSpring666** [comment]
The escaped Json is what we got directly from Python server. Are there any way to make JsonSerializer directly consume this escaped Json string?

If not, how can we manually pre-parse this escaped json safely? Regex.Unescape() won't work if unicode characters are encoded in the escaped Json (Tried in above demo project).

**Comment by krwq** [comment]
you can write converter for data and call JsonSerializer on it although probably best solution would be to change python server to not nest json as a string inside json

**Comment by SunshineSpring666** [comment]
@krwq Yes. Hope System.Text.Json could update to handle such situation without any manual pre-parsing, like the Json.NET lib.

**Comment by krwq** [comment]
That would need API proposal to hint parser to handle such case i.e. `ObjectAsStringConverter<T>` or attribute or some attribute to hint serializer to do this unwrapping. I don't guarantee suggested API will get approved. We will need some data to suggest this is common enough to justify it.

**Comment by eiriktsarpalis** [comment]
I might be misunderstanding what the exact issue might be (the attached repro is doing too many things, and it's not clear what the expected vs. actual behavior should be). Juding by your input string however, I don't see any difference in how System.Text.Json is treating it vs. Json.NET:

```C#
string json = "{\"code\":0,\"data\":\"[{\\\"Names\\\":\\\"[\\\\\\\"\\\\u5f91\\\\u9a78\\\\\\\", \\\\\\\"\\\\u5f25\\\\u6622\\\\u6656\\\\\\\"]\\\", \\\"registry\\\": null}]\"}";
string nestedJson = JsonSerializer.Deserialize<JsonDocument>(json).RootElement.GetProperty("data").GetString();

var value1 = Newtonsoft.Json.JsonConvert.DeserializeObject<Poco[]>(nestedJson);
Console.WriteLine(value1[0].Names); // "[\"徑驸\", \"弥昢晖\"]"

var value2 = JsonSerializer.Deserialize<Poco[]>(nestedJson);
Console.WriteLine(value2[0].Names); // "[\"徑驸\", \"弥昢晖\"]"

Console.WriteLine(value1[0].Names == value2[0].Names); // True

// Poco following the shape of the provided data
public class Poco
{
    public string Names { get; set; }
}
```

**Comment by svick** [comment]
It seems to me that the actual problem is that the core data is triple (!) JSON encoded. The proper way to read it is:

```c#
using System.Text.Json;

string jsonReturnedFromServer = "{\"code\":0,\"data\":\"[{\\\"Names\\\":\\\"[\\\\\\\"\\\\u5f91\\\\u9a78\\\\\\\", \\\\\\\"\\\\u5f25\\\\u6622\\\\u6656\\\\\\\"]\\\", \\\"registry\\\": null}]\"}";

var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };

var serverResponse = JsonSerializer.Deserialize<ServerResponse>(jsonReturnedFromServer, options);

var data = JsonSerializer.Deserialize<DataItem[]>(serverResponse.Data, options);

foreach (DataItem item in data)
{
    var names = JsonSerializer.Deserialize<string[]>(item.Names, options);
    foreach (string name in names)
    {
        Console.WriteLine(name);
    }
    Console.WriteLine();
}

record ServerResponse(int Code, string Data);
record DataItem(string Names, object Registry);
```

**Comment by SunshineSpring666** [comment]
Thanks for all comments and help. For now, I have to implement a custom converter, and explicitly apply it on each property of type ObservableCollection<T>, in each custom model class. (Because this custom converter with generic type ObservableCollection<T> can't be added via Serializer options if the generic type is not specified to be a fixed type.)

Hope System.Text.Json can make things easier by directly let Serializer consume such nested escaped Json string.
These strings contain the direct output of Python json.dumps(PoCo), which is a quite comment scenario of receiving server data.  There may be many other custom classes other than PoCo, which also contain ObservableCollection properties like ObservableCollection<Apple> Apples; ObservableCollection<Bear> Bears; etc. So manual pre-parsing or custom converters a lot of work.

Note that using Regex.Unescape() for pre-parsing json sring with no unicode is ok, but with encoded unicode characters it ends up not parsable by Serializer again

**Comment by Clockwork-Muse** [comment]
> These strings contain the direct output of Python json.dumps(PoCo), which is a quite comment scenario of receiving server data.

.... Press X to doubt.
If a server isn't returning it as "raw" JSON, it's more likely a bug.  If it's treating it like a string, you should probably leave it that way.

> There may be many other custom classes other than PoCo, which also contain ObservableCollection properties like ObservableCollection Apples; ObservableCollection Bears; etc. So manual pre-parsing or custom converters a lot of work.

.... I don't see why this is relevant.  If the real issue is multiple encoding layers, `ObservableCollection` isn't relevant.  You also shouldn't need a custom converter for `ObservableCollection`, [since it's natively supported](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/supported-collection-types?pivots=dotnet-6-0#systemcollectionsobjectmodel-namespace).  If you're doing something "extra", that's on you/the API provider, and you should perhaps consider changes.

> Note that using Regex.Unescape() for pre-parsing json sring with no unicode is ok, but with encoded unicode characters it ends up not parsable by Serializer again

Well don't do that.  
When you get to the relevant properties in a custom converter you should just be able to deserialized the byte stream at that point, because it will have removed one level of the encoding.  See the prior example.

**Comment by SunshineSpring666** [comment]
Thanks. I may also dig into why the Python server using json.dumps() would give me an unescaped string in such scenarios.

**Comment by SunshineSpring666** [comment]
Thanks for all the discussions. I use Json.NET before but meets no such situation back then. Guess I need more time to get to know the differences of these two libs.
Best regards

**Comment by krwq** [comment]
@SunshineSpring666 if you'd like to create proposal to handle nested JSONs as string please create new issue (we'll need strong evidence this is useful if we were to add it, i.e. large number of upvotes, people saying scenarios to justify it etc.). I'll close this issue in the meantime since there doesn't seem there is any action we can take from this. Feel free to re-open if you feel three is anything we should do here.

**Comment by eiriktsarpalis** [comment]
Looks like a race condition between area owners :-) Let's keep this one open as it contains more context.

**Comment by eiriktsarpalis** [comment]
One thing that isn't entirely clear to me yet is how Json.NET is different compared to System.Text.Json here. Does it have functionality that somehow makes the reader understand strings with JSON and automatically handles unescaping?

For the record, I don't think we should be supporting such a scenario. In scenaria where JSON strings require further parsing (be it JSON or XML) users should be explicit about it and write a custom converter that performs the operation within the precise parameters required.

**Comment by SunshineSpring666** [comment]
Thanks for all the discussion on this topic. In summary, for now, such situation needs to be handled by applying custom converter on each ObservableCollection<CustomType> property in a custom class. I don't know why Python's json.dumps would return such a serialized object in this escaped format. I'm working full stack, both server-end and client-end. I don't know whether other developers face such returned data from a Python server (or servers with other language and framework)

**Comment by Clockwork-Muse** [comment]
You're probably getting the escaped output because your code likely manually dumps specific subproperties into some other string property.  You probably shouldn't be doing that, if you are.

For that matter, you almost certainly shouldn't be calling `dumps` at all.  Your output should be to some sort of file handle (that is, `dump`), which would allow the results to be streamed and to avoid large allocations.  That you're manually calling `dumps` implies you're not using an existing Python server framework, which would handle this for you.
( I'm also surprised you're writing the server in Python instead of C#, because using the same language in both places can have benefits...)

**Comment by SunshineSpring666** [comment]
Thanks. Yes, I'm currently storing the list property's data in a string field in database. This is a bad design. 
Thanks for the hint. I'll dig into that and learn C# server framework later.

**Comment by eiriktsarpalis** [comment]
It looks like we can close this issue. Feel free to continue the conversation if more questions arise.

**Comment by SunshineSpring666** [comment]
Yes. It's escaped json string but it is what we got directly from Python server.&nbsp;


How can we directly let the de serializer consume this escaped json string? Or, are there any safer way to make the string not escaped?



---Original---
From: ***@***.***&gt;
Date: Mon, Sep 26, 2022 13:11 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [dotnet/runtime] [Bug] System.Text.Json can't parse Json (returned from server using Python json.dumps() ) ? (Issue #76130)




 
your string is a escaped json string string,not a json object.
 you firstly should remove the json escaped.

**Comment by Clockwork-Muse** [comment]
> Yes. It's escaped json string but it is what we got directly from Python server.&nbsp;
>
> How can we directly let the de serializer consume this escaped json string? Or, are there any safer way to make the string not escaped?

If the **entire** string is escaped JSON, this implies that you have a non-compliant JSON endpoint of some sort, which should be fixed.  At minimum, as I mentioned before, you shouldn't be using `dumps` in such a situation.

If it's specific sub-properties, the bigger question is going to be whether they should be serialized as a string property, or just a dynamic JSON sub-object.  If it's a string property, you're going to have to manually desierialize via a custom converter.  Otherwise, you need to stop calling `dumps` on those properties.

That said, I'm not sure why you're writing the server in python in the first place, if you're writing the client in C#, and would recommend that you consider writing both client and server in the same language.

**Comment by SunshineSpring666** [comment]
Hi Stephen,
    As you said, the issue is caused by doing customized json serialize on server side, which contains redundant nested json dumps on list properties.
    Thanks a lot for your kind help.

    Best regards,
    Joe
