### ISSUE TITLE
Сhunk method Linq

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#76148]
I suggest adding or changing this method in Linq

```
using System.Linq;

var result = Enumerable.Range(0, 100).СhunkLazy(12);

foreach (var collection in result)
{
    Console.WriteLine(new String('-',50));
    foreach (var item in collection)
    {
        Console.Write("|"+item+"|");
    }
    Console.WriteLine();
}
Console.ReadKey();




static class EnumeratorExt
{
    public static IEnumerable<IEnumerable<T>> СhunkLazy<T>(this IEnumerable<T> enumerable,int size)
    {
        int count = 0;
        return enumerable.GroupBy(a =>
        {
            count++;
            if (count >= size)
                count = 0;
            return count;
        }).Select(a => a.AsEnumerable());
    }

}
```

**Comment by Suchiman** [comment]
Your proposed method is actually less lazy and efficient than the current Chunk method. GroupBy evaluates the entire source sequence when the first item is requested because it needs to check the entire sequence for whether there's an item that belongs to the first group while the current Chunk method will just grab the first N elements put them into an array and return that lazily

**Comment by Mr0N** [comment]
> Your proposed method is actually less lazy and efficient than the current Chunk method. GroupBy evaluates the entire source sequence when the first item is requested because it needs to check the entire sequence for whether there's an item that belongs to the first group while the current Chunk method will just grab the first N elements put them into an array and return that lazily

And as if there will be the same allocation of memory for these two methods?

**Comment by Mr0N** [comment]
![image](https://user-images.githubusercontent.com/61237140/192153764-c2e47ace-ceaa-4129-96bc-87fac67e814f.png)
https://github.com/Mr0N/testSpeed/blob/master/testSpeed/Program.cs

**Comment by Mr0N** [comment]
![image](https://user-images.githubusercontent.com/61237140/192154046-c67dd03f-60dc-4017-aee6-e4a5b92a0574.png)
now it is necessary to rewrite GroupBy), well I am closing the account

**Comment by Mr0N** [comment]
![image](https://user-images.githubusercontent.com/61237140/192153661-eda69864-f3e6-47d4-8c1e-3b6eeadd1534.png)

**Comment by Clockwork-Muse** [comment]
@Mr0N - that the initial implementation is inefficient is not a reflection on whether the actual API should be abandoned.

That said, [lazy chunking was apparently considered and rejected](https://github.com/dotnet/runtime/issues/67132#issuecomment-1085924041), so the API has previously been rejected on those grounds....
