### ISSUE TITLE
[API Proposal]: add StartTime property, or the elapsed time seconds method, to per thread.

### ISSUE THREAD

**Issue by kasini3000** [dotnet/runtime#76145]
### Background and motivation

How to know how long each thread has been running?
 
Processes have a StartTime property for counting process running time, but threads have not for many years, which is very unreasonable.

### API Proposal

none

### API Usage

none

**Comment by danmoseley** [comment]
Hello, could you say more about why you need this information? Are you looking for the time spent executing, or walk clock time since the thread was first created?

**Comment by kasini3000** [comment]
hi 
see https://github.com/PowerShell/PowerShell/issues/18027

Calculate the total execution time of each thread. If the time is too long, kill the thread to avoid thread hang.

**Comment by Clockwork-Muse** [comment]
Thread != `Task`.

In general in C#, you're supposed to use `Task`, which might run on multiple threads, and may be paused for an indeterminate amount of time in `async` scenarios.  For this scenario, you're advised to use cancellation tokens.

That's ignoring the fact that long "alive" times don't necessarily have any relationship to being stuck.
The longest alive threads being things like your main application window and the GC thread...

**Comment by kasini3000** [comment]
? Has nothing to do with tasks, 
I'm only talking about 1 thread, or multiple threads

**Comment by danmoseley** [comment]
I've read your original issue and I'm not sure what you're trying to achieve. It sounds like perhaps you're using `ForEach-Object -Parallel` and want a global timeout, which, if it expires before all objects have been processes, terminates remaining work in some way -- or at least, does not start any new work?

Looking briefly through their implementation, it is quite custom (PSTask, etc) and seems like ultimately ends in QueueUserWorkItem. So these are threads, not tasks. Nevertheless there's no evidence that for Powershell to add more control over these things they need more primitives in the core libraries. I suggest to pursue your original request in their repo, and design it there (if they want to pursue it).

**Comment by kasini3000** [comment]
> ForEach-Object -Parallel and want a global timeout

ForEach-Object -Parallel allready has  a global timeout,It now wants a timeout for each thread.
How to know how long each thread has been running time?  At least there should be starttime property

**Comment by Clockwork-Muse** [comment]
> because this is what all .net users need!

No, because it's extremely rare that .net users should ever need to directly touch `Thread` (and are advised instead to use `Task`).

> How to know how long each thread has been running time?

The method can internally keep track of when it started the thread, but...

> The idea of limiting the maximum execution time of threads makes .net programs stronger!

Not really.  You're asking for a way for a thread to be able to kill arbitrary code that it's running.  That's extremely dangerous - we removed `Thread.Abort` for a reason - and trying to do this is almost certainly going to result in corrupted program state in some form.

**Comment by kasini3000** [comment]
Don't tell me task, Thread.Abort. Users just want to limit thread 1 to only survive 100 seconds and thread 2 to survive 200 seconds, ext. . .

**Comment by danmoseley** [comment]
> And the recommended way to do this sort of thing in C# is to use Task and cancellation tokens (assuming well behaved code).

Right, but in this case Powershell is abstracting things via "for-each" I guess. That is why the discussion should occur there -- because if there is a feature missing from that, the design work needs to happen in Powershell.

@kasini3000 as @Clockwork-Muse says, it is not technically possible to abruptly terminate a managed thread - at least without causing potential corruption, hangs, crashes. etc. Cancelation within a process always needs to be cooperative. The core framework provides ways to do this, and Powershell folks are undoubtedly knowledgeable about this. So it's best to continue the conversation with them.

**Comment by kasini3000** [comment]
hi all,thanks first,

.net has no coroutines. So is there a **time-based**, graceful (cacnel), brute force (kill) way to end a thread?

Q: i found golang has [The scheme of closing the coroutine based on time], does .net have a similar way?

---

golang

Any application that needs to maintain an SLA (Service Level Agreement) for the requested maximum duration should use time-based cancellation. The API is nearly identical to the previous example, with a few additions:

// This context will be cancelled after 3 seconds
// If you need to cancel before expiration you can use the cancel function as in the previous example
ctx, cancel := context.WithTimeout(ctx, 3*time.Second)

// The context will be cancelled at 2009-11-10 23:00:00
ctx, cancel := context.WithDeadline(ctx, time.Date(2009, time.November, 10, 23, 0, 0, 0, time.UTC))

Source of this article: Code Agricultural Network
Link to this article : chinese
https://www.codercto.com/a/110327.html

**Comment by huoyaoyuan** [comment]
> .net has no coroutines. So is there a **time-based**, graceful (cancel), brute force (kill) way to end a thread?

The standard way to handle a timeout is using `CancellationToken`. In CPU-bound tasks, the worker has to check for timeout periodically. In IO tasks, the timeout is passed to appropriate OS handler.

Killing a task/thread/worker that *is not aware of the kill* is extremely dangerous - it may set invalid intermediate state to objects.

**Comment by stephentoub** [comment]
> Q: i found golang has [The scheme of closing the coroutine based on time], does .net have a similar way?

golang doesn't have magical powers here.  It's effectively doing the same thing that .NET does, with a cancellation context / token that's passed around (either explicitly or implicitly) and that code can cooperatively monitor.  It similarly doesn't provide a supported mechanism for reliably interrupting a blocking operation that's chosen to ignore cancellation.
