### ISSUE TITLE
FOH (Frozen Object Heap) work items

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#76151]
A tracking issue for FOH-related tasks (Frozen Object Heap). It's a special heap for immortal objects such as string literals, Type objects, etc (see the list below). Conceptually similar to POH but it doesn't have a public API thus it never contains short-living objects + there are some relaxations in GC for FOH. It provides two advantages:
1) Makes GC's life easier by moving immortal objects out of normal heap
2) For some objects VM no longer needs to allocate pinned handles
3) JIT can "bake" direct references to FOH objects in codegen, see [example](https://github.com/dotnet/runtime/pull/75573).
4) Unlocks some JIT optimizations like folding field accesses for immutable objects, fold objects comparisons, etc.

## .NET 8.0
- [x] Allocate string literals on FOH https://github.com/dotnet/runtime/pull/49576
- [x] Allocate Type objects on FOH https://github.com/dotnet/runtime/pull/75573 (and https://github.com/dotnet/runtime/pull/76112)
- [x] Optimize `static readonly` fields holding frozen objects to const handles https://github.com/dotnet/runtime/pull/76112
- [x] Don't use write-barriers for FOH objects https://github.com/dotnet/runtime/pull/76135
- [x]  Allocate simple `static readonly` fields on FOH e.g. `static readonly object SyncObj = new();` and arrays https://github.com/dotnet/runtime/pull/85559
- [x] Allocate boxes statics on FOH https://github.com/dotnet/runtime/pull/77737
- [ ] **[In PR]** Diagnostic support https://github.com/dotnet/runtime/issues/75836 (and thread in https://github.com/dotnet/runtime/pull/49576)
- [x] Better heuristics for size of frozen segments: https://github.com/dotnet/runtime/pull/76870
- [x] Testing on real-world workloads (1P/3P)
  - How many objects end up in FOH, what's the ratio between SOH and FOH typically.
  - Standalone GC
  - Hard heap limit
  - Performance impact/savings
 - [x] Bug-fixes:
   - [x] https://github.com/dotnet/runtime/pull/76645
   - [x] https://github.com/dotnet/runtime/pull/76586
   - [x] https://github.com/dotnet/runtime/pull/76496
   - [x] https://github.com/dotnet/runtime/pull/76251

Suggestions are very welcome!

category:planning
theme:memory-usage
skill-level:expert
cost:medium
impact:medium

**Comment by jkotas** [comment]
> Potential good/bad ideas

Same ideas have been discussed multiple times. E.g.: https://github.com/dotnet/runtime/issues/7079#issuecomment-546050757 . They have been always punted so far.

(These ideas are not FOH specific. They can be implemented without FOH by paying for one extra indirection that is a minuscule cost.)

**Comment by stephentoub** [comment]
> Always allocate new T[0] on FOH

We ourselves have places we don't use Array.Empty because the use is relying on reference equality/inequality.

**Comment by EgorBo** [comment]
> We ourselves have places we don't use Array.Empty because the use is relying on reference equality/inequality.

Thanks, good to know, updated the item.

> Same ideas have been discussed multiple times. E.g.: https://github.com/dotnet/runtime/issues/7079#issuecomment-546050757 . They have been always punted so far.

Right, it's just that since we now have FOH we don't need to fragmentate POH/SOH with that pinned cache. I agree that the idea is dangerous, although I still think it could be an opt-in feature for some large projects (e.g. for those who had to do it by hands today), the implementation should be relatively simple.

**Comment by jkotas** [comment]
> I still think it could be an opt-in feature for some large projects

Doubt it. Dangerous opt-ins do not work for large projects. It is impossible (prohibitively expensive) to audit their code to validate that it is safe to opt-in.

**Comment by EgorBo** [comment]
> > I still think it could be an opt-in feature for some large projects
> 
> Doubt it. Dangerous opt-ins do not work for large projects. It is impossible (prohibitively expensive) to audit their code to validate that it is safe to opt-in.

fair enough!

**Comment by GSPP** [comment]
> Optimize str == "" as just cmp reg, 0xFOHREFERENCE - it turns out that it's still possible to produce new empty strings so

I'm curious how that is possible. If memory serves correctly, @jkotas stated on this issue tracker a long time ago that the policy is to have the empty string be a singleton.

**Comment by EgorBo** [comment]
> > Optimize str == "" as just cmp reg, 0xFOHREFERENCE - it turns out that it's still possible to produce new empty strings so
> 
> I'm curious how that is possible. If memory serves correctly, @jkotas stated on this issue tracker a long time ago that the policy is to have the empty string be a singleton.

That is exactly what is written in that item, isn't? I just decided to put some ideas from the past to, probably, inspire for new ones.

**Comment by jkotas** [comment]
> I'm curious how that is possible. 

For example:
```csharp
var s = string.Copy("");

Console.WriteLine(s == "");
Console.WriteLine(ReferenceEquals(s, ""));
```

**Comment by EgorBo** [comment]
Ah, the question was "how is it possible to create a unique empty string" and I read it as "how the optimization you propose is possible" 🙂

**Comment by EgorBo** [comment]
Idea: try to reserve memory for the first segment (4mb) next to coreclr in memory, the way we do currently for 4Gb for loader heap, I guess it won't hurt if we first try to reserve 4mb and then those 4Gb.

**Comment by EgorBo** [comment]
@jkotas am I correct that actually we can handle `static readonly object SyncObj = new object();` (common idiom for synchronization objects) in JIT?

If we're in a static constructor and see pattern like
```
newobj instance void [System.Runtime]System.Object::.ctor()
stsfld object myReadonField
```
we can replace `newobj` with a helper that allocates on FOH, right?

![image](https://user-images.githubusercontent.com/523221/194418297-af223135-e136-4adb-beb7-ca8651fa143a.png)

**Comment by EgorBo** [comment]
Same for empty arrays:
```
ldc.i4.0
newarr [System.Runtime]System.Int32
stsfld int32[] C::x
```
so we won't have to special-case Array.Empty

**Comment by jkotas** [comment]
You can only do this if this is a non-collectible code. Also, you can do the same thing for arrays of length 0. It would cover the Array.Empty case without special casing.

> Or actually, as an initial impl, it can be just:

I am not sure what you mean by this.

**Comment by EgorBo** [comment]
> I am not sure what you mean by this.

I meant that if a static constructor is complicated then 
```
newarr/newobj
stsfld
```
pattern might be set in a loop so we'll end up allocating immortal frozen object each iteration, etc. So I mean that if we see

```
newarr/newobj
stsfld
ret
```
then it's definitely just a simple cctor that only sets one field 🙂 - I meant it as an initial quick/safe implementation.

**Comment by EgorBo** [comment]
Idea: make pinning no-op for frozen objects since we plan to move `static readonly` arrays there.

**Comment by MichalPetryka** [comment]
Idea: provide higher alignment for arrays on FOH in order to achieve higher perf with SIMD operations.

**Comment by EgorBo** [comment]
> Idea: provide higher alignment for arrays on FOH in order to achieve higher perf with SIMD operations.

Definitely will require changes on GC side where gc assumes fixed alignment for all objects when it iterates them, e.g:
```c
void gc_heap::seg_set_mark_bits (heap_segment* seg)
{
    uint8_t* o = heap_segment_mem (seg);
    while (o < heap_segment_allocated (seg))
    {
        set_marked (o);
        o = o + Align (size(o));
    }
}
```

**Comment by jkotas** [comment]
I would also say that this is very niche. `NativeMemory.AlignedAlloc` and `GC.AllocateArray` variant that allocates on POH with specific alignment should sufficiently cover this space.

Note that the embedding of the object references from readonly fields can be also extended to objects allocated on POH.

```
readonly static int[] a = GC.AllocateArray(..., pinned: true); // This can be treated the same way as if the array was allocated on FOH

**Comment by EgorBo** [comment]
> You can do this for non-collectible code only

@jkotas do I understand it correctly that in order to detect that, I need to add an additional argument to my custom alloc helper - `StackCrawlMarkHandle` to then get Assembly object inside the alloc via stack walking and find out whether it's collectible or not?

**Comment by jkotas** [comment]
Stack crawling to find caller is a anti-pattern. You should do it all at JIT time, something like:
- Add `CORJIT_FLAG_FROZEN_ALLOCATIONS_ALLOWED` that is set for cctors in non-collectible code
- Add `CORINFO_HELP_NEW_FROZEN` and `CORINFO_HELP_NEWARRAY_1_FROZEN` JIT helpers that the JIT replaces allocations eligible for freezing with.
- Add `READYTORUN_HELPER_NewFrozenObject` and `READYTORUN_HELPER_NewFrozenArray` helpers for R2R that map to the above JIT helpers, so that R2R code does this optimization too and allows the eventual tiered-compilation to benefit.

**Comment by MichalPetryka** [comment]
> Stack crawling to find caller is an anti-pattern. You should do it all at JIT time, something like:
> 
> * Add `CORJIT_FLAG_FROZEN_ALLOCATIONS_ALLOWED` that is set for cctors in non-collectible code
> * Add `CORINFO_HELP_NEW_FROZEN` and `CORINFO_HELP_NEWARRAY_1_FROZEN` JIT helpers that the JIT replaces allocations eligible for freezing with.
> * Add `READYTORUN_HELPER_NewFrozenObject` and `READYTORUN_HELPER_NewFrozenArray` helpers for R2R that map to the above JIT helpers, so that R2R code does this optimization too and allows the eventual tiered-compilation to benefit.

Can't R2R assemblies be loaded into collectible ALCs?

**Comment by jkotas** [comment]
> Can't R2R assemblies be loaded into collectible ALCs?

They cannot today: https://github.com/dotnet/runtime/blob/fec0221b37b74ba1aa2f6119ea9b49f123ca5777/src/coreclr/vm/readytoruninfo.cpp#L527 . And even if it was allowed, this scheme would be still compatible with it. We would substitute the frozen allocation helper with a regular allocation helper when loading the R2R image into collectible context.

**Comment by EgorBo** [comment]
@jkotas @Maoni0 you asked for numbers - I downloaded BingSNR, updated to net8 and ran its benchmarks locally with bombardier (that simulates load):
338000 objects were allocated on FOH, total size is 17Mb (=5 frozen segments since size of a segment is hard-coded to 4Mb).

And here is general performance counters:
```
[System.Runtime]
    % Time in GC since last GC (%)                                 1
    Allocation Rate (B / 1 sec)                                8,160
    CPU Usage (%)                                                  0
    Exception Count (Count / 1 sec)                                0
    GC Committed Bytes (MB)                                    2,587.238
    GC Fragmentation (%)                                           5.389
    GC Heap Size (MB)                                          2,033.518
    Gen 0 GC Count (Count / 1 sec)                                 0
    Gen 0 Size (B)                                         8,245,392
    Gen 1 GC Count (Count / 1 sec)                                 0
    Gen 1 Size (B)                                        17,739,352
    Gen 2 GC Count (Count / 1 sec)                                 0
    Gen 2 Size (B)                                            1.4631e+09
    IL Bytes Jitted (B)                                   21,699,370
    LOH Size (B)                                              6.1376e+08
    Monitor Lock Contention Count (Count / 1 sec)                  0
    Number of Active Timers                                       14
    Number of Assemblies Loaded                                5,167
    Number of Methods Jitted                                 237,451
    POH (Pinned Object Heap) Size (B)                      2,897,848
    ThreadPool Completed Work Item Count (Count / 1 sec)           6
    ThreadPool Queue Length                                        0
    ThreadPool Thread Count                                        3
    Time spent in JIT (ms / 1 sec)                                 0
    Working Set (MB)                                           7,083.553
```
My env vars in `setup.bat`:
```
REM fix for .NET 7 to use segments instead of regions due to overcommit in net7rc1
SET xxCOMPlus_GCName=clrgc.dll
SET DOTNET_ReadyToRun=0
SET DOTNET_TieredCompilation=1
```
NOTE: I commented GCName to enable gc regions (just to test net8).

**Comment by jkotas** [comment]
> total size is 17Mb (=5 frozen segments since size of a segment is hard-coded to 4Mb).

Should we double the frozen segment reservations (ie 4mb, 8mb, 16mb, ...) to have a fewer of these?

**Comment by EgorBo** [comment]
> > total size is 17Mb (=5 frozen segments since size of a segment is hard-coded to 4Mb).
> 
> Should we double the frozen segment reservations (ie 4mb, 8mb, 16mb, ...) to have a fewer of these?

Makes sense!

Btw, it's impressive how much GC Regions save for the service, GC Heap with regions: 2Gb, without 3.5-4.5Gb

**Comment by jkotas** [comment]
> SET DOTNET_ReadyToRun=0

I do not think that Bing is disabling R2R. Was there a particular reason you have disabled it?

**Comment by Maoni0** [comment]
thanks for the data!

> Btw, it's impressive how much GC Regions save for the service, GC Heap with regions: 2Gb, without 3.5-4.5Gb 

♥

> I would also say that this is very niche. NativeMemory.AlignedAlloc and GC.AllocateArray variant that allocates on POH with specific alignment should sufficiently cover this space.

exactly, you don't need the GC support for this.

fewer FOH segs would be good.

**Comment by EgorBo** [comment]
More insights from the bing service - among those 17Mb of objects in the FOH, 9mb of them are RuntimeType and 8mb are string literals, the longest string literal is 24kb

**Comment by stephentoub** [comment]
> the longest string literal is 24kb

So... curious...

**Comment by EgorBo** [comment]
> > the longest string literal is 24kb
> 
> So... curious...
> 
> Some sort of lookup table?

The content looks like a huge set of coordinates (comma-separated floating points) for that one 🙂

**Comment by mjsabby** [comment]
I'm familiar with this service, and the FOH should be significantly larger than 17MB, it should be in the order of ~800MB or so. It contains all the RESX strings, and significant other object graphs. Perhaps we can chat offline to see why you're not seeing that size.

One question I did have is, will this collection of work regress performance of file-backed segments in the FOH?

**Comment by EgorBo** [comment]
@mjsabby 

> I'm familiar with this service, and the FOH should be significantly larger than 17MB

I was only counting objects in FOH segments added by runtime. Potentially, for your service we can hard-code the initial FOH size to e.g. 20Mb to have only just one extra frozen segment (currently it's 3).

> One question I did have is, will this collection of work regress performance of file-backed segments in the FOH?

I'd not expect any regressions. Perhaps, only if you're not on GC Regions as we had to enable scanning for _in-range_ FOH segments there.

**Comment by EgorBo** [comment]
All items except https://github.com/dotnet/runtime/issues/75836 are closed, so closing it for .NET 8.0 and leave https://github.com/dotnet/runtime/issues/75836 open (working on it now)
