### ISSUE TITLE
Group By Lazy

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#76152]
I suggest making GroupBy, making Lazy for IEnumerable, you can call it GroupBy a little bit later. I haven’t tested the code much, it may need refinement
```
using System;
using System.Collections.Generic;

var result = Ext.GroupByLazy(Enumerable.Range(0, 10).ToList(), a => (a%2).ToString());
foreach (var collection in result)
{
    Console.WriteLine(new String('0',30));
    foreach (var item in collection)
    {
        Console.Write("|"+item+"|");
    }
}
Console.Read();

public static class Ext
{
    public static IEnumerable<IEnumerable<T>> GroupByLazy<T, R>(this IEnumerable<T> enumerable,
        Func<T, R> selector)
    {
        int count = 0;
        var result = enumerable.ToDictionary(a => count++, a => selector.Invoke(a));
        List<R> ls = new List<R>();
        foreach (var item in result)
        {
            if (ls.Contains(item.Value))
                continue;
            ls.Add(item.Value);
            int page = 0;
            yield return enumerable.Where(a =>
            {
                var key = result[item.Key];
                var pageObj = result[page];
                page++;
                if (key == null && pageObj == null)
                    return true;
                if (key == null || page == null)
                    return false;
                bool check = key.Equals(pageObj);
              
                return check;
            });
        }
    }
}
```

**Comment by Clockwork-Muse** [comment]
The actual LINQ `GroupBy` method returns `IEnumerable<IGrouping<TKey,TSource>>`, and [`IGrouping`](https://learn.microsoft.com/en-us/dotnet/api/system.linq.igrouping-2?view=net-6.0) is an `IEnumerable`.  In other words, grouping can already be lazy from an API standpoint, but performance and practical reasons make it hard or impossible to actually implement such a setup.  In particular, serving succeeding elements of the first group requires that the entire source collection be enumerated to ensure they are returned in the proper group, at which point the entire grouping structure may as well be realized anyways.

This line:
```cs
yield return enumerable.Where
```
... Should have been an immediate red flag to you.  You cannot guarantee an enumerable is safe to enumerate multiple times (even ignoring the O(n ^ 2) issue), which means it's impossible to build the groupings lazily in the general case anyways.

<hr />
Probably the only way to do a completely lazy grouping would be a `NonContiguousGroupBy` (or, how the method works in Python), but I don't know how much call for that there would be....

**Comment by Mr0N** [comment]
> The actual LINQ `GroupBy` method returns `IEnumerable<IGrouping<TKey,TSource>>`, and [`IGrouping`](https://learn.microsoft.com/en-us/dotnet/api/system.linq.igrouping-2?view=net-6.0) is an `IEnumerable`. In other words, grouping can already be lazy from an API standpoint, but performance and practical reasons make it hard or impossible to actually implement such a setup. In particular, serving succeeding elements of the first group requires that the entire source collection be enumerated to ensure they are returned in the proper group, at which point the entire grouping structure may as well be realized anyways.
> 
> This line:
> 
> ```cs
> yield return enumerable.Where
> ```
> 
> ... Should have been an immediate red flag to you. You cannot guarantee an enumerable is safe to enumerate multiple times (even ignoring the O(n ^ 2) issue), which means it's impossible to build the groupings lazily in the general case anyways.
> 
> Probably the only way to do a completely lazy grouping would be a `NonContiguousGroupBy` (or, how the method works in Python), but I don't know how much call for that there would be....

Well, I originally wrote it for IList, then I managed to make it for IEnumerable, for IList there is a guarantee of repeatability

**Comment by eiriktsarpalis** [comment]
@Mr0N It might help if you could share your motivation for writing this method instead of using the existing `GroupBy` implementation.

**Comment by eiriktsarpalis** [comment]
> I always thought that Group By Lazy, then I realized that it was not

Technically speaking `GroupBy` is lazy, as no grouping calculations occur before its enumerator has materialized. I'm curious though what prompted you to write a different variant? Can you point to an example where the current `GroupBy` implementation is failing?

**Comment by Mr0N** [comment]
https://user-images.githubusercontent.com/61237140/192153764-c2e47ace-ceaa-4129-96bc-87fac67e814f.png
https://github.com/Mr0N/testSpeed/blob/master/testSpeed/Program.cs

**Comment by Mr0N** [comment]
![image](https://user-images.githubusercontent.com/61237140/192333275-6376f1f7-6cae-4c16-934d-ab2f25e2994d.png)

**Comment by Mr0N** [comment]
this method used so much memory even though I didn't materialize the group by part

**Comment by Mr0N** [comment]
![image](https://user-images.githubusercontent.com/61237140/192333610-fae03f77-a087-4cf4-ba36-bbd8d0914ec8.png)

**Comment by eiriktsarpalis** [comment]
I'm not sure I follow entirely. The benchmark you shared compares `Enumerable.Chunk` with a custom implementation that groups elements by their index modulo `size`. These are not identical methods and I don't see how they relate to the proposed `GroupBy` implementation.

If the issue is performance related, consider sharing a benchmark that compares identical code -- only changing the underlying GroupBy method should differ.
