### ISSUE TITLE
FileCheck error: '__jit_disasm.out' is empty for outerloop tests

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#76150]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=29112&view=ms.vss-test-web.build-test-results-tab&runId=586768&resultId=109553&paneView=debug

Runtime_33972
Runtime_73681
Runtime_33972

cc @TIHan Seems to be related to FileCheck tests recently merged, right?

**Comment by EgorBo** [comment]
Same for PGO pipelines: https://dev.azure.com/dnceng-public/public/_build/results?buildId=29291&view=ms.vss-test-web.build-test-results-tab&runId=589060&resultId=109669&paneView=debug

where it doesn't expect instrumentation in codegen:
```
__tmp0_Runtime_73681.cs:19:16: error: CHECK-NOT: excluded string found in input
// CHECK-NOT: CORINFO_HELP
^
__jit_disasm.out:31:7: note: found here
call CORINFO_HELP_CLASSPROFILE32
^~~~~~~~~~~~

Input file: __jit_disasm.out
Check file: __tmp0_Runtime_73681.cs

-dump-input=help explains the following input dump.

Input was:
<<<<<<
```

**Comment by TIHan** [comment]
Yup, will need to figure this out ASAP.

**Comment by TIHan** [comment]
Outerloop and PGO runs do not show this error in the latest runs. Closing.
