### ISSUE TITLE
[API Proposal]: String.SplitAny

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#76165]
### Background and motivation

There are now a number of `string.Split` methods that have a `char[]` parameter. This forces developers to allocate arrays and store them in static variables. It is desirable to avoid all this.

_This pattern is often used in applications_. This pattern is found even in .Net
https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/String.Manipulation.cs,1ff97959e1d46a53,references

Although there is a #934 proposal which uses ReadOnlySpan to avoid unwanted allocations, the current proposal still has benefits. First, **it makes it easy to fix existing code without significant rewriting**. Second, this API is already implemented internally and only needs to be made public. Third, there is already `IndexOfAny(string)`.

### API Proposal

```csharp
namespace System
{
    public partial class String
    {
        public string[] SplitAny(ReadOnlySpan<char> separator, StringSplitOptions options);
        public string[] SplitAny(ReadOnlySpan<char> separator, int count);
        public string[] SplitAny(ReadOnlySpan<char> separator, int count, StringSplitOptions options);

    }
}
```

### API Usage

```csharp
// New code
string[] parts = path.SplitAny("\\/", StringSplitOptions.RemoveEmptyEntries);

// Old code
private readonly static separators = new char[] { '\\', '/' };
...
string[] parts = path.Split(separators , StringSplitOptions.RemoveEmptyEntries);
// or
string[] parts = path.Split(new char[] { '\\', '/' }, StringSplitOptions.RemoveEmptyEntries);

```

### Alternative Designs

```csharp
namespace System
{
    public partial class String
    {
        public string[] SplitAny(string separator, StringSplitOptions options);
        public string[] SplitAny(string separator, int count);
        public string[] SplitAny(string separator, int count, StringSplitOptions options);

    }
}
```

```csharp
namespace System
{
    public partial class String
    {
        public string[] Split(ReadOnlySpan<char> separator, StringSplitOptions options);
        public string[] Split(ReadOnlySpan<char> separator, int count);
        public string[] Split(ReadOnlySpan<char> separator, int count, StringSplitOptions options);

    }
}
```

### Risks

No risks.

**Comment by kasini3000** [comment]
String. Split 
Inconsistencies in powershell v5 and powershell v7 have greatly affected powershell customers and will continue to affect them.

It is recommended to split into two independent methods:
String.SplitStringArray()
String.SplitCharArray()

**Comment by stephentoub** [comment]
> First, it makes it easy to fix existing code without significant rewriting

"Fix it" how? The cost of a static readonly array is a pittance compared to the per-invocation costs of the proposed API.

We do need span-based splitting APIs, but personally I don't see enough value in the proposed one, especially not to warrant introducing yet another name.

**Comment by iSazonov** [comment]
> "Fix it" how? The cost of a static readonly array for the separators is a pittance compared to the per-invocation costs of the proposed API.

To be precise, I started to rid PowerShell of a lot of static variables. They all require initialization. I expect this will have a positive effect on startup scenario.

**Comment by stephentoub** [comment]
> To be precise, I started to rid PowerShell of a lot of static variables. They all require initialization. I expect this will have a positive effect on startup scenario.

Using Split on startup is more expensive than the cost of that cached allocation.

**Comment by stephentoub** [comment]
> But if we can not allocate at all

The proposed API _does_ allocate.

> why not do it

Because the cons outweigh the pros. Naming it Split would be dangerous, as someone refactors their code to use `ReadOnlySpan<char>`, and while it compiles fine, it behaves very differently. And naming it SplitAny implies the existing char[] overloads are not splitting on any, which also breeds confusion and misunderstandings and bugs. From my perspective, this is an example of something starting off at - 100 points and not working its way back to being net positive.

**Comment by iSazonov** [comment]
> > But if we can not allocate at all
> 
> The proposed API _does_ allocate.

The argument `char[]` itself is meant. This is what the proposal is for. Because there is _no alternative_. 

As for the name, perhaps there is a better option. But it seems clearer to me than the existing`public static ReadOnlySpan<char> TrimEnd(this ReadOnlySpan<char> span, ReadOnlySpan<char> trimChars)`

**Comment by stephentoub** [comment]
> Because there is no alternative.

There are multiple pending proposals about splitting spans that do so with zero allocation, both for the separators and for the results.  We should focus on shipping one or more of those in .NET 8, not on removing a tiny portion of the cost of the existing thing that will still have non-trivial overheads on the code paths you're trying to improve.

**Comment by stephentoub** [comment]
Thanks for the suggestions.  There are now multiple proposals for split-related APIs, and we're not going to pursue this one.
