### ISSUE TITLE
SPMI should avoid DASM roundtrip for analysis

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#76178]
For large diffs it is prohibitively slow to produce disassembly for all method contexts with diffs, and most of us are probably familiar with superpmi-diffs timing out for a jit change with a large amount of diffs.

We are already returning a list of contexts with diffs when using `-diffMCList`. This is how we figure out which contexts to produce .dasm files for. It should not be that much extra work to produce a comma-separated file instead that also includes metrics like diff size for each of the contexts. Then we can create jit-analyze-spmi that can analyze this, or enhance jit-analyze with support for this, to produce output similar to jit-analyze directly from the .csv file, without having to go through intermediate disassembly.

As a final step we'll probably want to produce .dasm files for the most important contexts identified by jit-analyze-spmi.

**Comment by BruceForstall** [comment]
Related: https://github.com/dotnet/runtime/issues/52877
