### ISSUE TITLE
RawDefaultValue is resolved differently between runtimes 

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/runtime#76174]
# The issue

The following code gives different results when executed on different runtime flavours:

- coreCLR -> outputs: `SomeOtherValue`
- Mono -> outputs: `SomeValue`
- NativeAOT -> outputs: `SomeValue`

``` csharp
using System;
using System.Reflection;
using System.Runtime.CompilerServices;

public class Program
{
    internal abstract class UsableCustomConstantAttribute : CustomConstantAttribute
    {
        public sealed override object Value => RealValue;
        protected object RealValue { get; set; }
    }

    private class StringCustomConstantAttribute : UsableCustomConstantAttribute
    {
        public new object Value { get { return RealValue; } set { RealValue = value; } }
    }

    private class AnotherStringCustomConstantAttribute : UsableCustomConstantAttribute
    {
        public new object Value { get { return RealValue; } set { RealValue = value; } }
    }

    public void Foo([StringCustomConstant(Value = "SomeValue")] [AnotherStringCustomConstant(Value = "SomeOtherValue")] object param) { }

    static void Main()
    {
        Console.WriteLine(typeof(Program).GetMethod("Foo").GetParameters()[0].RawDefaultValue);
    }
}
```

# Expected
All runtimes should produce the same result.

# TODO
Align the implementation of `RawDefaultValue` resolution between runtimes.
Mono: https://github.com/dotnet/runtime/blob/19c5d17a5d71134bd774496a80d43fe13184ba09/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeParameterInfo.cs#L158
CoreCLR:
https://github.com/dotnet/runtime/blob/19c5d17a5d71134bd774496a80d43fe13184ba09/src/coreclr/System.Private.CoreLib/src/System/Reflection/RuntimeParameterInfo.cs#L297
NativeAOT:
https://github.com/dotnet/runtime/blob/19c5d17a5d71134bd774496a80d43fe13184ba09/src/coreclr/nativeaot/System.Private.CoreLib/src/System/Reflection/Runtime/General/Helpers.cs#L206

---
This is related to: https://github.com/dotnet/runtime/issues/49806

**Comment by ivanpovazan** [comment]
cc @jkotas

**Comment by teo-tsirpanis** [comment]
(we use only one area per issue)

**Comment by steveharter** [comment]
Like CoreClr, .NET Framework also returns "SomeOtherValue" so assuming this is the expected result, Mono and NativeAOT should be changed to return the last parameter attribute.

If we agree that is the case, then this issue should be moved to `[area-System.Reflection-mono]` and another tracking issue logged for NativeAOT.

This does seem like a niche issue, however, since it requires multiple parameter attributes.

**Comment by jkotas** [comment]
@steveharter Ivan is fixing this in https://github.com/dotnet/runtime/pull/75612

**Comment by ivanpovazan** [comment]
Closing as completed via https://github.com/dotnet/runtime/commit/05b8bab6f00a292db68a4142c8b2d318ee247334
