### ISSUE TITLE
Suspicious values in GenerationInfo SizeBeforeBytes / SizeAfterBytes

### ISSUE THREAD

**Issue by timothycoleman** [dotnet/runtime#76188]
### Description

The GenerationInfo SizeBeforeBytes and SizeAfterBytes grow to suspiciously large values (hundreds of GB) while the TotalCommittedBytes remains stable and correct around 200mb

The FragmentationBefore/AfterBytes also become large.

This is with workstation gc - I haven't tried with server.

### Reproduction Steps

Run the following in a console app. It continually writes new strings to an array of strings, creating garbage to be collected as it goes. Every 5 seconds it prints some stats from GetGCMemoryInfo.

```
static bool PrintGCMemoryInfo(GCKind kind)
{
    Console.WriteLine();
    GCMemoryInfo memoryInfo = GC.GetGCMemoryInfo(kind);
    Console.WriteLine("last recorded {0} GC#{1}, collected gen{2}, concurrent: {3}, compact: {4}, promoted {5:N0} bytes",
        kind, memoryInfo.Index, memoryInfo.Generation, memoryInfo.Concurrent, memoryInfo.Compacted, memoryInfo.PromotedBytes);
    Console.WriteLine("Total committed {0:N0}, % Pause time in GC: {1}",
        memoryInfo.TotalCommittedBytes, memoryInfo.PauseTimePercentage);
    int numGenerations = memoryInfo.GenerationInfo.Length;
    Console.WriteLine("there are {0} generations", numGenerations);
    for (int i = 0; i < numGenerations; i++)
    {
        Console.WriteLine("gen#{0}, size {1:N0}->{2:N0}, frag {3:N0}->{4:N0}", i,
            memoryInfo.GenerationInfo[i].SizeBeforeBytes, memoryInfo.GenerationInfo[i].SizeAfterBytes,
            memoryInfo.GenerationInfo[i].FragmentationBeforeBytes, memoryInfo.GenerationInfo[i].FragmentationAfterBytes);
    }
    return true;
}

async Task PrintLoop()
{
    while (true)
    {
        PrintGCMemoryInfo(GCKind.Background);
        await Task.Delay(5000);
    }
}

_ = PrintLoop();

var strings = new string[1_000_000];

while (true) {
    for (int i = 0; i < strings.Length; i++)
    {
        strings[i] = $"{Guid.NewGuid()}";
    }
}
```

### Expected behavior

SizeAfterBytes shows the number of bytes in that generation after the collection.

### Actual behavior

The SizeAfterBytes values rise and keep rising. After a few minutes they are into the hundreds of GB range, far larger than the TotalCommittedBytes which remains around 200mb and appears to be correct.

The machine has 64gb of RAM and is not paging

```
last recorded Background GC#40063, collected gen2, concurrent: True, compact: False, promoted 120,158,712 bytes
Total committed 192,028,672, % Pause time in GC: 27.19
there are 5 generations
gen#0, size 24,008,516,112->5,667,952,296, frag 202,016->16,565,312
gen#1, size 48,016,787,984->24,008,288,856, frag 141,179,248->70,404,528
gen#2, size 455,993,561,080->456,027,115,872, frag 112,228,719,208->207,947,402,664
gen#3, size 22,896,228,960->22,896,228,960, frag 91,584->91,584
gen#4, size 55,843,344->55,843,344, frag 0->0
```

### Regression?

Same behaviour in net5

### Configuration

net6
Windows 10
x64

**Comment by Maoni0** [comment]
this was fixed with this [PR](https://github.com/dotnet/runtime/pull/60309)

**Comment by mangod9** [comment]
Hi @timothycoleman ,

We could look into porting to 6 if this blocking any prod scenario, or if its just for internal testing/validation perhaps you could build the runtime locally? 

Thx!

**Comment by timothycoleman** [comment]
Thanks @mangod9, for now just testing. I should be able to get what I need by running it in net7. Thanks both for you help, I'll close this issue
