### ISSUE TITLE
CLR: static const inline std::map causing System.AccessViolationException in xtree on application exit

### ISSUE THREAD

**Issue by mckooper** [dotnet/runtime#76210]
### Description

Class containing a static const inline std::map is included in a CLR/CLI application. On exit, System.AccessViolationException exceptions are thrown as xtree attempts to _Erase the std::map

### Reproduction Steps

Create new CLR Console App
Add new Class to Project and include header in main cpp
```
#include "pch.h"
#include "static_map.h"

using namespace System;

int main(array<System::String ^> ^args)
{
    return 0;
}
```
Add static const inline std::map to new class
````
#pragma once

#include <map>

class static_map
{
public:
  enum my_enum_e {
    one,
    two
  };
  static const inline std::map<my_enum_e, int> my_enum_map = {
    { one, 1 },
    { two, 2 }
  };
};
````
Build and Debug (F5)

### Expected behavior

Application should run without any issues.

### Actual behavior

On exit, System.AccessViolationException exceptions occur in C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\xtree

### Configuration

Windows SDK Version: 8.1
Platform Toolset: Visual Studio 2017 (v141)
.NET Target Framdwork Version: v4.8
C++ Language Standard: ISO C++17 Standard (/std:c++17) 
Platform: x64

**Comment by AaronRobinsonMSFT** [comment]
@tgani-msft Any thoughts on this? Is C++/CLI compatible with C++17?

**Comment by AaronRobinsonMSFT** [comment]
@mckooper Since this is specifically for .NET Framework and seems likely to be a MSVC compiler issue, please file an issue using [VS Developer Community](https://developercommunity.visualstudio.com/home) instead of Github. The MSVC team tracks the VS Developer Community very closely and is their primary vector for customer interaction.

**Comment by tgani-msft** [comment]
> @tgani-msft Any thoughts on this? Is C++/CLI compatible with C++17?

Yes it is but two-phase name lookup has to be disabled with `/Zc:twoPhase-` which you can add in Project Properties > Configuration Properties > C/C++ > Command Line

**Comment by tgani-msft** [comment]
I've tried to repro the bug using the step  outlined above but I cannot repro it: the project compiles, links and runs correctly in {x86,x64} x {Debug, Release}. Maybe getting access to the user's repro project would show more.

The OP is encouraged to report the bug at: https://developercommunity.visualstudio.com/report?port=1025&fsid=a2601109-ccbb-4157-9d79-68d3bc3ad9d9&entry=problem&space=62

**Comment by mckooper** [comment]
Already fixed in newer versions of MSVC: https://developercommunity.visualstudio.com/t/Inline-static-std::map-member-throws-exc/339685
