### ISSUE TITLE
[API Proposal]: System.Text.Json: Add ReferenceHandler.IgnoreAllCycles to also ignore cycles in collections

### ISSUE THREAD

**Issue by ascott18** [dotnet/runtime#76211]
### Background and motivation

This is a continuation of https://github.com/dotnet/runtime/issues/66187. In order to achieve parity with Newtonsoft to allow for porting of legacy apps, we need an option to be able to omit the writing of `null` when reference loops are encountered in a collection.

### API Proposal

I don't know what a good name here would be, but something that indicates that it _also_ affects reference loops inside collections, unlike `IgnoreCycles`.

```csharp
namespace System.Text.Json.Serialization;

public abstract class ReferenceHandler
{
    public static ReferenceHandler IgnoreAllCycles { get; }
}
```

### API Usage

```csharp
string json = JsonSerializer.Serialize(value, options: new JsonSerializerOptions {
    ReferenceHandler = ReferenceHandler.IgnoreAllCycles,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
});
```

**Comment by ascott18** [comment]
Comparison of current functionality between STJ and Newtonsoft:

``` c#
using System.Text.Json;
using System.Text.Json.Serialization;
using Newtonsoft.Json;

var list = new List<object>();
list.Add(list);

string jsonString = System.Text.Json.JsonSerializer.Serialize(list, options: new JsonSerializerOptions{
    ReferenceHandler = ReferenceHandler.IgnoreCycles
});
Console.WriteLine($"       STJ: {jsonString}");

JsonConvert.DefaultSettings = () => new JsonSerializerSettings{
    ReferenceLoopHandling = ReferenceLoopHandling.Ignore
};
string newtonsoftString = JsonConvert.SerializeObject(list);
Console.WriteLine($"Newtonsoft: {newtonsoftString}");
```

Output:
```
       STJ: [null]
Newtonsoft: []
```

**Comment by layomia** [comment]
Dup of https://github.com/dotnet/runtime/issues/66187. This is by design - the consensus in API review for the feature was to always write `null` for duplicate references, regardless of where they occur in the type graph. Also see https://github.com/dotnet/runtime/issues/66187#issuecomment-1059029558.


> In order to achieve parity with Newtonsoft

Please note that this is not a goal for System.Text.Json.

**Comment by ascott18** [comment]
@layomia Would a feature be considered that adds a new option that is an analogue of `JsonIgnoreCondition.WhenWritingNull`, but for collection items?
