### ISSUE TITLE
[.NET 7.0.0-rc.1]System.Drawing WebP support does not work

### ISSUE THREAD

**Issue by koszeggy** [dotnet/runtime#76237]
### Description
In .NET 7 the WebP format has been [appeared](https://github.com/dotnet/runtime/blob/007563949e53bad52dfcdf95927b0ce00101df4d/src/libraries/System.Drawing.Common/src/System/Drawing/Imaging/ImageFormat.cs#L154) in the `ImageFormat` class for Windows 10.0.17763.0 and above. But neither `ImageCodecInfo.GetImageDecoders`, nor `ImageCodecInfo.GetImageEncoders` return the newly added WebP (and HEIF) codecs.

### Actual Behavior
I know that System.Drawing encoders and decoders are just thin wrappers of WIC codecs. It seems that WebP codecs are not installed by default in Windows 10 so I manually installed Google's WIC-compatible [codecs](https://storage.googleapis.com/downloads.webmproject.org/releases/webp/WebpCodecSetup.exe), which made the WebP format available for Windows Explorer, Paint, Photo Viewer and other applications:

![image](https://user-images.githubusercontent.com/27336165/192505232-5949404f-eea9-45a9-ac27-bf7aac7bf708.png)

But `System.Drawing` still cannot use the installed codecs:
* `ImageCodecInfo` still does not return it in encoders or decoders
* `Image.FromStream` and the `Bitmap` constructors throw `ArgumentException`: Parameter is not valid.
* `Image.Save(string, ImageFormat.WebP)` still uses the PNG encoder as a fallback

### Expected Behavior
I actually expect that for Windows 10.0.17763 and above WebP and HEIF codecs are available at least as decoders. But I could live with it if it worked only after installing the WIC codecs manually. But as I demonstrated above, it didn't work either.

Is there any missing step or how is it supposed to work anyway?

### Known Workarounds

> 📝 _Note:_ I know there are alternative libraries that I could use. I also do have [separate packages](https://docs.kgysoft.net/drawing/html/N_KGySoft_Drawing.htm) for the different environments but this issue is specifically for GDI+.

### Configuration
* Windows version: 10.0.19044.2006
* .NET version: 7.0.100-rc.1.22431.12

**Comment by hez2010** [comment]
Try this instead?
https://apps.microsoft.com/store/detail/webp-%E7%94%BB%E5%83%8F%E6%8B%A1%E5%BC%B5%E6%A9%9F%E8%83%BD/9PG2DK419DRG

**Comment by koszeggy** [comment]
@hez2010: Thank you for the suggestion. I tried it but the result is exactly the same.

Except that I cannot remove it anymore because Uninstall is disabled in Apps & Features for some reason:

![image](https://user-images.githubusercontent.com/27336165/192847415-95c4bc81-f0ac-4b45-b609-46cd0b4732b8.png)

But I actually don't mind it as long as it will not cause any conflicts in the future.

**Comment by JeremyKuhne** [comment]
Unfortunately, there isn't anything we can do here as we're interacting directly with GDI+, which doesn't support this. Please see our [recommendations](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only#recommended-action) for other libraries to consider for more modern graphics support.
