### ISSUE TITLE
为何开源基金会要参与政治？？为何不曾支持伊拉克 利比亚 叙利亚？？

### ISSUE THREAD

**Issue by AngelShaka** [dotnet/runtime#76231]
![0ffbf639e86d98b24e98407b1b0aa92](https://user-images.githubusercontent.com/96106724/192454392-e2977eeb-2da4-4b65-bd58-fcdda72bcfaf.jpg)
这实在令人沮丧，一个宣称开放包容的开源框架却要参与政治。

**Comment by teo-tsirpanis** [comment]
Closing, this repository does not have anything to do with the .NET _Foundation_.
