### ISSUE TITLE
Option to Disable JIT Optimizations for specific .NET Core Assembly

### ISSUE THREAD

**Issue by danstur** [dotnet/runtime#76240]
For Full Framework assemblies one can disable JIT optimizations by adding a ini file with the same name as the assembly (e.g. Foo.dll and Foo.dll.ini) with the following content:

```
[.NET Framework Debugging Control]
AllowOptimize=0
```

In .NET Core I can disable optimizations of all assemblies by setting the `COMPlus_JITMinOpts` environment variable to 1 for the process. 

There does not currently seem to be a way to disable optimizations for specific assemblies. This is a problem when trying to debug into specific NuGets in a large application, because disabling JIT optimizations for the whole process causes large slowdowns for the whole application.

**Comment by teo-tsirpanis** [comment]
Can't you use [`DebuggableAttribute.DebuggingModes.NoOptimization`](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.debuggableattribute.debuggingmodes)? You might need to manually edit the assembly in question if you don't compile it from source.

**Comment by tommcdon** [comment]
It may be possible to implement this feature in Visual Studio.  Adding @caslan to determine if this feature request is something the Visual Studio team is considering.

**Comment by AaronRobinsonMSFT** [comment]
Isn't this already supported by VS via ['Suppress JIT optimization on module load (Managed only)' option](https://learn.microsoft.com/visualstudio/debugger/jit-optimization-and-debugging#the-suppress-jit-optimization-on-module-load-managed-only-option)?

**Comment by danstur** [comment]
@AaronRobinsonMSFT Is there an option to disable optimization only for specific modules there? As far as I know this is an all or nothing setting which is equivalent to setting `COMPlus_JITMinOpts`.

**Comment by AaronRobinsonMSFT** [comment]
@danstur Sorry about that. I got distracted by the Debug/Release comments in https://github.com/dotnet/runtime/issues/76240#issuecomment-1259479003. The specific scenario is selective disabling, which isn't presently a scenario in VS, at least that I am aware of. I believe it is possible but I think you need to use SOS inside of WinDBG.

**Comment by danstur** [comment]
@AaronRobinsonMSFT No worries. You don't happen to have some pointers for what to search?

I googled around a bit about disabling optimization during assembly load in windbg, but came up empty handed. The [official msdn documentation](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/sos-debugging-extension#commands) also didn't list anything that'd be helpful as far as I could see.

**Comment by tommcdon** [comment]
Hi @danstur!  Sorry for the late follow-up.  Since this is a Visual Studio feature request, please create a [Visual Studio Suggestion](https://learn.microsoft.com/visualstudio/ide/suggest-a-feature?view=vs-2022) to request per-module optimization when debugging.
