### ISSUE TITLE
oData Client "JIT compile method in AOT mode" error when build to IOS device

### ISSUE THREAD

**Issue by FirewizzNL** [dotnet/runtime#76261]
### Description

When using the ODAta client and build to an IOS device ARM64 the code crashes because an "JIT COMPILE" error. This is caused because the IOS compiler (nano) builds AOT(ahead of time).
Info:
 - https://learn.microsoft.com/nl-nl/xamarin/ios/internals/limitations
 - https://www.mono-project.com/docs/advanced/aot/#full-aot

### Steps to Reproduce

Simple oData GET, using library on release build IOS using:
```
var context = new Container(new Uri("API _URI"));
var employee = context.Employees.Where(e => e.Id == 433).Single();
```

### Expected result
OData returning the result. Which it does in debug/simulator, but not when compiled as release.

### Actual result
Error/Exception:
`Attempting to JIT compile method '(wrapper delegate-invoke) void <Module>:invoke_callvirt_void_EmployeeModel_int(EcotouchApi.Models.EcoTouchDbModels.EmployeeModel,int)' while running in aot-only mode.`

*What is actually happening.*
Attemptint a JIT compile method in AOT mode.

### Additional detail
This is not only here, I see multiple issues regarding JIT compile in AOT mode without proper solutions.

### Link to public reproduction project repository

https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Client/Microsoft.OData.Client.cs

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

IOS, ARM64

### Did you find any workaround?

No workaround found

### Expected result
OData returning the result. Which it does in debug/simulator, but not when compiled as release.

### Error/Exception:
```
Attempting to JIT compile method '(wrapper delegate-invoke) void <Module>:invoke_callvirt_void_EmployeeModel_int(EcotouchApi.Models.EcoTouchDbModels.EmployeeModel,int)' while running in aot-only mode.
```

**Comment by LeVladIonescu** [comment]
@FirewizzNL This should be fixed by https://github.com/dotnet/runtime/pull/85643.
Can we validate this with the latest .Net8 preview and close it?

**Comment by SamMonoRT** [comment]
Closing this as Fixed. Please re-open if the issue reproes on .NET8 Preview 7 or later builds.
