### ISSUE TITLE
Adding JsonIgnoreAttribute to `new` property fails with ArgumentException

### ISSUE THREAD

**Issue by liuliang-wt** [dotnet/runtime#76268]
### Description

```C#
using System.Text.Json;
using System.Text.Json.Serialization;

ClassB b = new ClassB();
var test = JsonSerializer.Serialize(b);
Console.ReadLine();

public class ClassA
{
    [JsonIgnore]
    public string test { get; set; }
}

public class ClassB : ClassA
{
    [JsonIgnore]
    public new string test { get; set; }
}
```

The above code will throw an exception: System.ArgumentException:“An item with the same key has already been added. Key: test”

When both base class and derived class has a property with the same name (derived class using new to override property in base class),  and both of this two properties marked as [JsonIgnore], Serialize function throw this exception.

**Comment by eiriktsarpalis** [comment]
I can reproduce -- this belongs in the same class of bugs as #73255. This one is more interesting as it's actually failing with an exception during contract resolution.
