### ISSUE TITLE
Using hostfxr_initialize_for_runtime_config returns code: 2147450733	

### ISSUE THREAD

**Issue by wingchunninja** [dotnet/runtime#76292]
I want to call a function from a .net6.0 application from an unmanaged code (Objective-C).

I was following this documentation: https://github.com/dotnet/runtime/blob/main/docs/design/features/native-hosting.md

The .net 6 application has the following runtimeconfig:
![Screenshot 2022-09-28 at 10 05 46](https://user-images.githubusercontent.com/39628532/192724187-13c22e5c-5933-46d5-82c1-e2c67dc963e2.png)

This application also has references to other projects & nuget packages.

Back to the unmanaged code, I am calling the following steps:
1. using the libhostfxr.dylib
2. using dlopen to 1.
3. calling hostfxr_initialize_for_runtime_config with the config from above

This results into receive and error code 2147450733. 
I am working on a macOS. And so far this is the only clue that I got. 

When I run the app in a console and before that I set the properties for 
`export COREHOST_TRACE=1 
export COREHOST_TRACEFILE=host.txt
`
I get an output that tells me, that it can find the runtimeconfig file and that the application is self-contained.

I have tried using hostfxr_initialize_for_dotnet_command_line and that results to success and i get a return code of 0. Can I still call functions from .net, when i previously initialized the app with hostfxr_initialize_for_dotnet_command_line?

Is there something that i am not quite following from the docs?

**Comment by vitek-karas** [comment]
The managed project in question was built as self-contained. We currently don't support loading self-contained components with `hostfxr_initialize_for_runtime_config`. There's also the question of how you built it, as SDK doesn't really support producing self-contained class libs.

You can load self-contained application using `hostfxr_initialize_for_command_line`.

We currently also don't support loading two different .NET runtimes into the same process, so if you already loaded something through `hostfxr_initialize_for_command_line`, you can only load things which are framework dependent and through `hostfxr_initialize_for_runtime_config` - in that case the hosting layer will check that the already loaded runtime is high enough version for the component you're trying to load and it will run it on the existing runtime.

**Comment by vitek-karas** [comment]
The error codes from the hosting layer are described here: https://github.com/dotnet/runtime/blob/main/docs/design/features/host-error-codes.md

In your case -2147450733 it's: InvalidConfigFile.

**Comment by wingchunninja** [comment]
The output of the project is an exe. But for sure, the application is a self-contained one.

Exactly, I already checked the well known error codes that lead to the InvalidConfigFile. Validating the file (as seen on the screenshot in the question), I could not find an issue with it.

I have tried the following case as well:
1. Initialize the app with hostfxr_initialize_for_command_line
2. Getting the runtime delegate from the initialized host, hostfxr_get_runtime_delegate
3. Defining the return function as following
![Screenshot 2022-09-28 at 10 09 19](https://user-images.githubusercontent.com/39628532/192725015-99870f6d-340c-4cf9-85bc-ec4c844d8a86.png)
4. Calling the function and receive the following error code: 2146233054

Is this a case that I can even consider, getting a pointer to a managed function when initializing the app with hostfxr_initialize_for_command_line?

**Comment by vitek-karas** [comment]
0x80131522	-2146233054	COR_E_TYPELOAD	Could not find or load a specific type (class, enum, etc).

What you describe is definitely supported and should work. The error you get typically means that the type_name specified was not correct. Please note that it must be assembly qualified name, so something like `Namespace.Type, Assembly`.
Same goes for the `deleagte_type_name` (unless you're using `UnmanagedCallersOnly`).

**Comment by wingchunninja** [comment]
Thanks for the guidelines, using the right namespace did its magic.
