### ISSUE TITLE
Runtime_34937 and Runtime_33972 JITBlue runtime test failures on the rolling build

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#76314]
This applies to the coreclr x64 and arm64 legs for both Linux and OSX.

Rolling build [example](https://dev.azure.com/dnceng-public/public/_build/results?buildId=32985&view=ms.vss-test-web.build-test-results-tab&runId=663962&resultId=102684&paneView=debug)

A couple examples, but there are more:

**Runtime_33972**
```
__tmp22_Runtime_33972.cs:176:11: error: CHECK: expected string not found in input
// CHECK: Program:AdvSimd_CompareEqual_Vector128_Single_CreateZeroZeroZeroZero_AsVariable({{.*}})
^
__jit_disasm.out:1718:2: note: scanning from here
;; size=8 bbWeight=1 PerfScore 3.00
^
```

**Runtime_34937.sh**
```
__tmp1_Runtime_34937.cs:36:12: error: ARM64: expected string not found in input
// ARM64: {{^ *}} and w1, w0, #15{{$}}
^
__jit_disasm.out:31:56: note: scanning from here
; Assembly listing for method Program:PerformMod_2(int):int
^
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by EgorBo** [comment]
Should be fixed with https://github.com/dotnet/runtime/pull/76276 am I right, @TIHan?

**Comment by TIHan** [comment]
Yes, it should hopefully be fixed by https://github.com/dotnet/runtime/pull/76276 - the crossgen2 outerloop is failing for unrelated reasons due to an azure bad access token. The other outloop tests are still running.

**Comment by steveisok** [comment]
Confirmed the failure have gone away in the latest rolling build run.
