### ISSUE TITLE
Potential perf improvements for Mono AOT

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#76318]
https://github.com/dotnet/runtime/pull/73768 has brought a lot of improvements for CLR, but regressed Mono. It was "reverted" in https://github.com/dotnet/runtime/pull/75917 to fix Mono.

When looking at the WASM and Mono data in the [Reporting System](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/TestHistoryIndexIndex.html) I've noticed that Mono AOT (regular one, not WASM) was actually benefiting from #73768 

Example:

[Span.IndexOf<byte> for Mono AOT x64](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04_LLVM%3dfalse_MonoAOT%3dtrue_MonoInterpreter%3dfalse_RunKind%3dmicro_mono%2fSystem.Memory.Span(Byte).IndexOfValue(Size%3a%20512).html)

![image](https://user-images.githubusercontent.com/6011991/192855427-202cf8e3-eb82-45ad-95af-d4b14e7b1311.png)

I am not 100% sure that it applies to all architectures, as [Mono AOT arm64](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_arm64_ubuntu%2018.04_LLVM%3dfalse_MonoAOT%3dtrue_MonoInterpreter%3dfalse_RunKind%3dmicro_mono%2fSystem.Memory.Span(Byte).IndexOfValue(Size%3a%20512).html) has not received any new data inputs in the last few weeks (cc @naricc @DrewScoggins).

It does not apply to [Mono Interpeter](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04_LLVM%3dfalse_MonoAOT%3dfalse_MonoInterpreter%3dtrue_RunKind%3dmicro_mono%2fSystem.Memory.Span(Byte).IndexOfValue(Size%3a%20512).html):

![image](https://user-images.githubusercontent.com/6011991/192856420-f3b672d1-53c9-4d4e-964f-a33a8209d227.png)

@vargaz @jkotas should we modify the `#if` defs introduced in #75917 to not be applied to Mono AOT? I think that doing this for `main` branch should be relatively safe (as long as we benchmark the change before merging).

**Comment by adamsitnik** [comment]
We could also apply it to WASM AOT config (https://github.com/dotnet/runtime/issues/75801)

**Comment by jkotas** [comment]
We do not build separate libraries for Mono AOT vs. non-AOT config. We have one set of managed libraries per architecture, for all codegen strategies. You would not be able to do this using `#ifdef`. It would need to be some sort of new intrinsic.

Also, there are mixed partially AOTed configs where the AOT vs. non-AOT is difference is per method. It makes the switch even harder.

**Comment by naricc** [comment]
I don't think there is a way to distinguish aot/non-aot in an `#ifdef`

@lewing

**Comment by jkotas** [comment]
I think this can be closed. 

We need to fix the Mono limitations that lead to the bad perf regressions, and delete the forked implementation that was added as a workaround for .NET 7. It is ok to take small perf regressions in some scenarios.

**Comment by jeffhandley** [comment]
Great; thanks for the clarification that we cannot distinguish aot/non-aot in that manner. @adamsitnik and I wanted to confirm we weren't overlooking a different way to dial this for 7.0.

**Comment by lewing** [comment]
https://github.com/dotnet/runtime/pull/76033 will likely fix the wasm AOT case were we to revert but we don't yet have a solution for the interpreter

**Comment by adamsitnik** [comment]
@lewing do we have an issue for tracking this? #76033 has closed #75801 and I can't find interpreter issue
