### ISSUE TITLE
The 3.1 and 5.0 SDKs do not support musl/Alpine Linux anymore

### ISSUE THREAD

**Issue by mattleibow** [dotnet/runtime#76338]
### Describe the bug

I am building an app for Alpine 3.15 and/or 3.16, but those versions of Alpine can no longer load the .so files from the linux-musl-x64 folders. I had a look at the runtime.json on those installs and I notice the version of alpine in the json is only 3.14.

### To Reproduce

Just try use SkiaSharp - or any other NuGet that has a musl-specific binary.

Se also these issues:
 - https://github.com/mono/SkiaSharp/issues/2169
 - https://github.com/mono/SkiaSharp/issues/2215

I can work around this by adding/editing the json file to include alpine.3.15 and alpine.3.16. 

### Exceptions (if any)

```
System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library liblibSkiaSharp: No such file or directory
```

### Further technical details
- Using the dotnet docker image which was Alpine 3.16 and had SDK 3.1.28 installed.
- I also see the Alpine version in the json on GitHub: https://github.com/dotnet/corefx/blob/v3.1.28/pkg/Microsoft.NETCore.Platforms/runtime.json#L80

**Comment by NikolaMilosavljevic** [comment]
[Triage] @Anipik there is a build flag that controls build/publishing of individual packages. I believe your team owns the use of that configuration logic.

**Comment by ViktorHofer** [comment]
@NikolaMilosavljevic, @Anipik isn't part of the .NET team anymore. cc @dotnet/area-infrastructure-libraries, @carlossanlop

**Comment by carlossanlop** [comment]
Both PRs have been merged internally.
