### ISSUE TITLE
Runtime_34937 and Runtime_33972 JITMinOpts test failures

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#76344]
Affected tests:
- `JIT/Regression/JitBlue/Runtime_34937/Runtime_34937/Runtime_34937.sh`
- `JIT/Regression/JitBlue/Runtime_33972/Runtime_33972/Runtime_33972.sh`

Error: `expected string not found in input`

Runfo failures in [last 30 days (Runtime_34937)](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime+name%3A%22jit%2Fregression%2Fjitblue%2Fruntime_34937%2Fruntime_34937%2Fruntime_34937.sh%22) and in [last 30 days (Runtime_33972)](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime+name%3A%22jit%2Fregression%2Fjitblue%2Fruntime_33972%2Fruntime_33972%2Fruntime_33972.sh%22) as of 10/3:
- First occurrences of both failures are in Rolling run [28591](https://runfo.azurewebsites.net/view/build/?number=28591) on 9/24
- 10x Rolling runs affected 9/24-9/28 + couple of PRs (no occurrences 9/28-10/3)

Error example from [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-37a52ae3999b4a9085/JIT.Regression/1/console.a10ce08f.log?%3Fhelixlogtype%3Dresult):
```
  Starting:    JIT.Regression.XUnitWrapper (parallel test collections = on, max threads = 8)
    JIT/Regression/JitBlue/Runtime_34937/Runtime_34937/Runtime_34937.sh [FAIL]
      __tmp1_Runtime_34937.cs:36:12: error: ARM64: expected string not found in input
       // ARM64: {{^ *}} and w1, w0, #15{{$}}
                 ^
      __jit_disasm.out:31:56: note: scanning from here
      ; Assembly listing for method Program:PerformMod_2(int):int
                                                             ^
      __jit_disasm.out:52:2: note: possible intended match here
       and w0, w0, #15
       ^
      
      Input file: __jit_disasm.out
      Check file: __tmp1_Runtime_34937.cs
      
      -dump-input=help explains the following input dump.
      
      Input was:
      <<<<<<
```

## Original Report

Various Linux/Mac arm64/x64 JITMinOpts legs of the jitstress pipeline fail these tests.

https://dev.azure.com/dnceng-public/public/_build/results?buildId=32864&view=ms.vss-test-web.build-test-results-tab&runId=660270&resultId=108719&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by karelz** [comment]
FYI: This hit also regular Rolling runs (not JitStress) between 9/24-9/28 ... so I removed the JitStress label. It disappeared on 9/28 and there were no hits since then (until 10/3).

**Comment by BruceForstall** [comment]
This has been fixed
