### ISSUE TITLE
Assertion failed '!IsSSEOrAVXInstruction(ins)' in 'JIT.HardwareIntrinsics.X86.Program:ExtractInt32129()' during 'Generate code'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#76343]
Run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=32864&view=ms.vss-test-web.build-test-results-tab&runId=660104&resultId=100276&paneView=debug

jitstress1/jitstress2, x86/x64

Failure in:
JIT\\HardwareIntrinsics\\X86\\Sse41\\Sse41_ro\\Sse41_ro.cmd
JIT\\HardwareIntrinsics\\X86\\Sse41.X64\\Sse41.X64_ro\\Sse41.X64_ro.cmd

```
JIT\HardwareIntrinsics\X86\Sse41\Sse41_ro\Sse41_ro.cmd [FAIL]
      
      Assert failure(PID 12188 [0x00002f9c], Thread: 1928 [0x0788]): Assertion failed '!IsSSEOrAVXInstruction(ins)' in 'JIT.HardwareIntrinsics.X86.Program:ExtractInt32129()' during 'Generate code' (IL size 147; hash 0xb1d85492; FullOpts)
      
          File: D:\a\_work\1\s\src\coreclr\jit\emitxarch.cpp Line: 2799
          Image: C:\h\w\AA02095B\p\corerun.exe
```

@tannergooding @dotnet/jit-contrib

**Comment by tannergooding** [comment]
This is probably https://github.com/dotnet/runtime/pull/76212

Looks like a path isn't expecting extract to be a `store`
