### ISSUE TITLE
FileCheck error: '__jit_disasm.out' is empty.

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#76352]
Related: https://github.com/dotnet/runtime/issues/76150

Pipeline: runtime-coreclr jitstress-isas-arm
https://dev.azure.com/dnceng-public/public/_build/results?buildId=34242&view=ms.vss-test-web.build-test-results-tab

Runtime_33972 fails on jitstress_isas_nohwintrinsic legs (arm64, windows/Linux/OSX) with:

```
    JIT\Regression\JitBlue\Runtime_33972\Runtime_33972\Runtime_33972.cmd [FAIL]
      FileCheck error: '__jit_disasm.out' is empty.
      FileCheck command line:  D:\h\w\9B950822\p\SuperFileCheck\runtimes/win-arm64\native\FileCheck.exe __tmp0_Runtime_33972.cs --allow-unused-prefixes --check-prefixes=CHECK,ARM64,ARM64-WINDOWS --dump-input-context 40 --input-file __jit_disasm.out
...
... many more FileCheck errors
...
```

Note that this configuration sets:

```
set COMPlus_TieredCompilation=0
set COMPlus_EnableHWIntrinsic=0
```

**Comment by TIHan** [comment]
This looks to be resolved as this error is not showing up in the latest jitstress runs.
