### ISSUE TITLE
Memory leak in COM interop (IDispatch↔IReflect)

### ISSUE THREAD

**Issue by ClearScriptLib** [dotnet/runtime#76350]
### Description

When an object that implements [`IReflect`](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.ireflect) is queried for [`IDispatch`](https://learn.microsoft.com/en-us/windows/win32/api/oaidl/nn-oaidl-idispatch), the runtime enumerates the object's members and constructs a CCW. This operation seems to create managed arrays that outlive the CCW, and subsequent short-lived CCWs leak increasing amounts of managed memory.

### Reproduction Steps

The following program reproduces the leak:

``` C#
using System.Globalization;
using System.Reflection;
using System.Runtime.InteropServices;

while (true)
{
    var pDispTest = Marshal.GetIDispatchForObject(new Test());
    Marshal.Release(pDispTest);
    GC.Collect();
    GC.WaitForPendingFinalizers();
}

internal sealed class Test : IReflect
{
    private static readonly FieldInfo[] _fields = Enumerable.Range(0, 10).Select(i => (FieldInfo)new Field($"f{i}")).ToArray();
    private static readonly MethodInfo[] _methods = Enumerable.Range(0, 10).Select(i => (MethodInfo)new Method($"m{i}")).ToArray();
    private static readonly PropertyInfo[] _properties = Enumerable.Range(0, 10).Select(i => (PropertyInfo)new Property($"p{i}")).ToArray();

    public FieldInfo[] GetFields(BindingFlags bindingAttr) => _fields;
    public MethodInfo[] GetMethods(BindingFlags bindingAttr) => _methods;
    public PropertyInfo[] GetProperties(BindingFlags bindingAttr) => _properties;
    // all other IReflect members throw NotImplementedException

    private sealed class Property : PropertyInfo
    {
        public Property(string name) => Name = name;
        public override string Name { get; }
        // all other required overrides throw NotImplementedException
    }

    private sealed class Field : FieldInfo
    {
        public Field(string name) => Name = name;
        public override string Name { get; }
        // all other required overrides throw NotImplementedException
    }

    private sealed class Method : MethodInfo
    {
        public Method(string name) => Name = name;
        public override string Name { get; }
        // all other required overrides throw NotImplementedException
    }
}
```

### Expected behavior

No memory leak.

### Actual behavior

Snapshots at program start and after 10,000 iterations:

![image](https://user-images.githubusercontent.com/12966733/192929612-f111d452-24d3-4f3e-b1b8-e7843345e074.png)

Managed heap diff:

![image](https://user-images.githubusercontent.com/12966733/192930245-5a307efa-16cc-4e71-92c7-14fedf515295.png)

Leaked arrays:

![image](https://user-images.githubusercontent.com/12966733/192930875-dfdb9592-419b-46d6-ae63-9aaae79e133d.png)

Leaked array contents:

![image](https://user-images.githubusercontent.com/12966733/192931336-47ed3e4d-1a50-4fa3-9970-4f99c7b171fe.png)

Our best guess: It looks like each CCW adds all reflected member references to a long-lived, ever-growing managed collection that uses arrays under the hood.

### Regression?

Unknown.

### Known Workarounds

None.

### Configuration

- .NET SDK 6.0.401
- Windows 11 21H2
- x64

### Other information

None.

**Comment by ClearScriptLib** [comment]
This is just a guess, but [this](https://github.com/dotnet/runtime/blob/9d6396deb02161f5ee47af72ccac52c2e1bae458/src/coreclr/vm/dispatchinfo.cpp#L2859) looks suspicious:

``` C++
m_DispIDToMemberInfoMap.InsertValue(DispID2HashKey(MemberID), pMemberToAdd);
pMemberToAdd.SuppressRelease();
```

Since `m_DispIDToMemberInfoMap` appears to be a dictionary of raw pointers, it isn't clear how or where the `DispatchMemberInfo` instances are released.

**Comment by AaronRobinsonMSFT** [comment]
@ClearScriptLib This seems to have been introduced in https://github.com/dotnet/coreclr/pull/20919, so has been around since at least .NET Core 3.1, boo.

Is it possible for you to move up to .NET 7 or is .NET 6 a requirement in this case?

/cc @janvorli

**Comment by ClearScriptLib** [comment]
>Is it possible for you to move up to .NET 7 or is .NET 6 a requirement in this case?

Our project is a library, so it supports lots of runtimes. We've implemented an optimization that greatly reduces the impact of this issue. Most users of our library – including the one that originally reported the leak – will no longer be affected at all.

**Comment by AaronRobinsonMSFT** [comment]
> A fix would still be nice, though 😁

Indeed. .NET 7 isn't hard to justify, but .NET 6 is going to require more effort. I'll submit a PR today for .NET 8 and then a fix for .NET 7 post-GA.

**Comment by ClearScriptLib** [comment]
>I'll submit a PR today for .NET 8 and then a fix for .NET 7 post-GA.

That sounds great. Thank you!

**Comment by AaronRobinsonMSFT** [comment]
@ClearScriptLib I don't see any issue with getting this into .NET 7 - https://github.com/dotnet/runtime/pull/77570.
