### ISSUE TITLE
Generic method constrained by struct & interface can not see readonly modifier

### ISSUE THREAD

**Issue by bollhals** [dotnet/runtime#76355]
### Description

If you have a generic method with a struct & interface constrain and that interface contains a method, it is not able to see that the method implemented in the struct is readonly, so it ends up creating defensive copies even though it shouldn't need to.

### Configuration

Any version, even on main

### Regression?

No.

### Data

[Example on SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzmAPgAQEwEYCwAUJgAwAEAygBYQBOADgDITAB0ASgK4wJRgCmAbiKkymXB268BrAMIB7MPSgAbfrQrqAblADG/FMMIiAzGOxlZZAN5Ey9sgG0AUlAQBxfjHV6AFAgBPen55ADNfCgBKSIBdOwdMM0wAFjIAWQBJGAAeABUAPl9YMlyyFEj4hwcAdyp1fhKyEDKEWk5dBDgyDKyEdVCIfUqbYaqqlFZcgwRfSKMqgF9h4Zc3T29aP0DgsIjouMIqxLFUtPZ+ULzC2gvG8tGaupvG5pRW9s7u3v7B/mHbQ5jIETKZvWbzBxLQhQ0xkWB9WgDfRfHg/ZEAo6pUEzOZEGHEMw3CAAE3kMBUARabQ6lCaKIRSL+hAxCUJ/BJZIpZBUZIA5mQAAq4CH2Y5E0nkyk8mD8gXYEViNkcyXcvmCkwKsXsiVc6Wy5IKlZpfgIKjyYkZJQqXzG03my30FQAeXovDJEwAcvIsipYLBebFhlrlVyUiVprN/sMoQsgA==): 

```cs
using System;
using SharpLab.Runtime;
using System.Runtime.CompilerServices;

public class C {
    [JitGeneric(typeof(S))]
    public void MIn<T>(in T s)
        where T : struct, IInterface
    {
            s.Test();
    }
    
    [JitGeneric(typeof(S))]
    public void MRef<T>(ref T s)
        where T : struct, IInterface
    {
            s.Test();
    }
}

public interface IInterface {
    void Test();
}

public readonly struct S : IInterface
{
    public readonly long P1;
    public readonly long P2;
    public readonly long P3;
    public readonly long P4;
    
    [MethodImpl(MethodImplOptions.NoInlining)]
    public readonly void Test()
    {
    }
}
```
```
C.MIn[[S, _]](S ByRef)
    L0000: sub esp, 0x20
    L0003: vzeroupper
    L0006: vmovdqu xmm0, [edx]
    L000a: vmovdqu [esp], xmm0
    L000f: vmovdqu xmm0, [edx+0x10]
    L0014: vmovdqu [esp+0x10], xmm0
    L001a: lea ecx, [esp]
    L001d: call dword ptr [0xf51ccd0]
    L0023: add esp, 0x20
    L0026: ret

C.MRef[[S, _]](S ByRef)
    L0000: mov ecx, edx
    L0002: call dword ptr [0xf51ccd0]
    L0008: ret

```

**Comment by tfenise** [comment]
This is rather a problem with C#. The IL already includes codes to create a defensive copy, as the C# compiler does not know whether `T` is `readonly`, so it generates codes according to the worst case. `struct` being `readonly` is only a concept of C#, not the runtime. You could argue that maybe the C# feature should have better support from the runtime, though.

**Comment by tfenise** [comment]
See also https://github.com/dotnet/csharplang/issues/3055.

**Comment by bollhals** [comment]
Ah, there was that issue that I once saw ... I know I read it somewhere, but I couldn't find it anymore. Thanks for linking it.

**Comment by jakobbotsch** [comment]
I don't think there is much the JIT can do here. From the IL it sees the proposed optimization would be illegal -- it would change output of a program such as the following:
```csharp
public class C
{
    public void MIn<T>(in T s)
        where T : struct, IInterface
    {
        s.Test();
    }

    public void MRef<T>(ref T s)
        where T : struct, IInterface
    {
        s.Test();
    }

    public unsafe static void Main()
    {
        S s = new S();
        S.F = &s;
        new C().MIn(in s);
    }
}

public interface IInterface
{
    void Test();
}

public unsafe readonly struct S : IInterface
{
    public readonly long P1;
    public readonly long P2;
    public readonly long P3;
    public readonly long P4;

    [MethodImpl(MethodImplOptions.NoInlining)]
    public readonly void Test()
    {
        fixed (S* pThis = &this)
            Console.WriteLine(pThis == F);
    }

    public static S* F;
}

```

**Comment by JulieLeeMSFT** [comment]
Closing the issue. @bollhals, please reopen if you still think that JIT has to change something.  

> I don't think there is much the JIT can do here. From the IL it sees the proposed optimization would be illegal -- it would change output of a program such as the following:
