### ISSUE TITLE
incorrect kind of datetime data

### ISSUE THREAD

**Issue by masaru-uchida-fuji** [dotnet/runtime#76353]
### Description

I'm trying to handle datetime data with MySQL C# connector. The kind of data seems to be incorrectly set. [The same problem happens in Npgsql.](https://github.com/npgsql/npgsql/issues/4145) I believe .Net doesn't properly set a kind of datetime data.

### Reproduction Steps

```
List<string> sqlCommands = new List<string>();
sqlCommands.Add("drop table if exists type_test;");
sqlCommands.Add("create table type_test(tz timestamp, notz datetime);");
sqlCommands.Add("insert into type_test select now(),now();");
sqlCommands.Add("SET TIME_ZONE = '+00:00';");

MySql.Data.MySqlClient.MySqlConnection cn = new MySql.Data.MySqlClient.MySqlConnection(connectionString);
MySql.Data.MySqlClient.MySqlCommand com = new MySql.Data.MySqlClient.MySqlCommand();
com = new MySqlCommand("", cn);
cn.Open();

for (int i1 = 0; i1 < sqlCommands.Count; i1++)
{
     com.CommandText = sqlCommands[i1];
     com.ExecuteNonQuery();
}
MySqlDataAdapter da = new MySqlDataAdapter("SELECT * FROM type_test", cn);
DataTable dt = new DataTable();

da.Fill(dt);

DateTime tz = (DateTime)dt.Rows[0]["tz"];
DateTime notz = (DateTime)dt.Rows[0]["notz"];

Debug.WriteLine($"TZ: {tz} Kind={tz.Kind}");
Debug.WriteLine($"NOTZ: {notz} Kind={notz.Kind}");

cn.Close();
```

### Expected behavior

```
TZ: 2022/09/28 6:15:44 Kind=Utc
NOTZ: 2022/09/28 15:15:44 Kind=Unspecified
```

### Actual behavior

```
TZ: 2022/09/28 6:15:44 Kind=Unspecified
NOTZ: 2022/09/28 15:15:44 Kind=Unspecified
```

**Comment by Clockwork-Muse** [comment]
A 00:00 offset isn't actually the same thing as UTC.  If you instead run 
```cs
sqlCommands.Add("SET TIME_ZONE = 'UTC';");
```
... Does that change anything?

That aside, the driver maybe doesn't actually know whether the column you retrieved is supposedly in UTC or not.  

Note that auto-converting columns are often dangerous, so from a practical standpoint I would advise using `DATETIME` on the MySQL side and (probably) `DateTimeOffset` on the C# side.

**Comment by David-Engel** [comment]
You are using the wrong type. DateTime doesn't hold timezone info.

For more information on which date/time types to use and when, see:
https://learn.microsoft.com/en-us/dotnet/standard/datetime/choosing-between-datetime

Regards,
David
