### ISSUE TITLE
[API Proposal]: Add compat source generator for System.Text.RegularExpressions.Generator to .net Framework

### ISSUE THREAD

**Issue by davhdavh** [dotnet/runtime#76369]
### Background and motivation

It is quite annoying having to write
```
      private const string CountryCodeFormat = /*language=regex*/"^\\s*\\(?\\+\\s*(\\d{2,4})";
#if NETFRAMEWORK
      private static readonly Regex _countryCodeFormat = new(CountryCodeFormat, RegexOptions.Compiled);
      private static          Regex CountryCodeFormatRegex() => _countryCodeFormat;
#else
      [GeneratedRegex(CountryCodeFormat, RegexOptions.Compiled, -1)]
      private static partial Regex CountryCodeFormatRegex();
#endif
```
when having to support .net framework in same source code. Please let us just write

```
      [GeneratedRegex("^\\s*\\(?\\+\\s*(\\d{2,4})", RegexOptions.Compiled, -1)]
      private static partial Regex CountryCodeFormatRegex();
```

The source generator already supports just making stubs when it doesn't support some option, so there is no reason it shouldn't just do the same if the build target doesn't support the new regex extensions.

### API Proposal

NA

### API Usage

NA

### Risks

Some people might be surprised nothing is actually generated... Perhaps issue a warning when falling back to just calling regex constructor.

**Comment by teo-tsirpanis** [comment]
I would love this feature too but I find it unlikely for the team to bother with it. The most important problem is how to distribute it. Inbox source generators come with the .NET 6/7 reference pack; there is no precedent for inbox source generators in .NET Framework or .NET Standard, and there's zero chance of backporting `RegexGeneratorAttribute`.

**Comment by davhdavh** [comment]
I'm not requesting the full feature of source generating the regex. Just a
shim to be able to use the same syntax in my source code for all build
targets.

**Comment by stephentoub** [comment]
@teo-tsirpanis's point is that neither the generator nor the attribute are even available when targeting .NET Framework.  In other words, this wouldn't just be about changing the generator's logic, but rather it would require an entirely different distribution mechanism for the generator as well as shipping a separate assembly for the attribute.  I understand the desire, but we don't currently have any plans to do either.
