### ISSUE TITLE
Strange IPAddress.Parse result with extra zero

### ISSUE THREAD

**Issue by hopix** [dotnet/runtime#76368]
### Description

Parsing IP4 address with `IPAddress.Parse` seems to produce strange results when extra leading zero is included IP address string. 

### Reproduction Steps

`System.Net.IPAddress.Parse("10.10.1.011").ToString();`

### Expected behavior

The `IPAddress.Parse("10.10.1.011").ToString()` should produce `"10.10.1.11"`.

### Actual behavior

The `IPAddress.Parse("10.10.1.011").ToString()` produces `"10.10.1.9"`.

### Configuration

.NET 6.0 on Windows 11 64-bit

**Comment by hopperpl** [comment]
The behavior is actual correct. Due to the specification, a leading zero in an IP string has to be interpreted as an octal literal. 

This means, ```011``` which is lead by a 0 and therefore has to be interpreted as octal.  ```1 * 8^1 + 1 * 8^0 = 8 + 1 = 9```

See: https://www.rfc-editor.org/rfc/rfc6943.txt  (3.1.1.  IPv4 Literals)

**Comment by karelz** [comment]
Triage: Looks like by design based on the RFC.
If it is not explicitly documented in our docs, we might consider adding it there if it would help ...
