### ISSUE TITLE
[API Proposal]: Recording from the stream

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#76399]
### Background and motivation

I suggest adding these apis

### API Proposal

public void File.WriteAllStream(string path,Stream stream);
public void File.WriteAllStreamAsync(string path,Stream stream);

### API Usage

using var stream = File.OpenRead("file.txt");
File.WriteAllStream("myFile",stream);

**Comment by stephentoub** [comment]
Thanks for the proposal.  This is to save a line so that you can write:
```C#
using var stream = File.OpenRead("file.txt");
File.WriteAllStream("myFile",stream);
```
instead of:
```C#
using var stream = File.OpenRead("file.txt");
using var output = File.OpenWrite("myFile");
stream.CopyTo(output);
```
?  Or is there another motivation?

**Comment by Mr0N** [comment]
> Thanks for the proposal. This is to save a line so that you can write:
> 
> ```cs
> using var stream = File.OpenRead("file.txt");
> File.WriteAllStream("myFile",stream);
> ```
> 
> instead of:
> 
> ```cs
> using var stream = File.OpenRead("file.txt");
> using var output = File.OpenWrite("myFile");
> stream.CopyTo(output);
> ```
> 
> ? Or is there another motivation?



> 



> 

```
var array = new byte[] { 1, 2 };
using var file = File.OpenWrite("file.txt");
file.Write(new Span<byte>(array));
```
there seems to be not much code either, but there is File.WriteAllBytes

**Comment by Mr0N** [comment]
```
var obj = new string[5];
using var stream = new StreamWriter("file.txt");
foreach (var item in obj)
    stream.WriteLine(item);
```

**Comment by stephentoub** [comment]
> there seems to be not much code either, but there is File.WriteAllBytes

There is, but it's also _super_ commonly needed, which is why it was added maybe 15 years ago.

I'm not dismissing your suggestion as not being something someone might find useful. Rather, it saves so little and it's not so common a need that I don't see it being worth adding. (Your usage example would also be better served with File.Copy.)

**Comment by Mr0N** [comment]
> > there seems to be not much code either, but there is File.WriteAllBytes
> 
> There is, but it's also _super_ commonly needed, which is why it was added maybe 15 years ago.
> 
> I'm not dismissing your suggestion as not being something someone might find useful. Rather, it saves so little and it's not so common a need that I don't see it being worth adding. (Your usage example would also be better served with File.Copy.)

Well, it would not be so difficult to add it, it can save a student a couple of minutes of his life.

**Comment by teo-tsirpanis** [comment]
> Well, it would not be so difficult to add it, it can save a student a couple of minutes of his life.)

This is not the bar to add new APIs to the BCL. We need to answer "why?", not "why not?".

**Comment by Mr0N** [comment]
> Thanks for the proposal. This is to save a line so that you can write:
> 
> ```cs
> using var stream = File.OpenRead("file.txt");
> File.WriteAllStream("myFile",stream);
> ```
> 
> instead of:
> 
> ```cs
> using var stream = File.OpenRead("file.txt");
> using var output = File.OpenWrite("myFile");
> stream.CopyTo(output);
> ```
> 
> ? Or is there another motivation?

Not all streams support CopyTo

**Comment by teo-tsirpanis** [comment]
Which don't? [`Stream.CopyTo` has a default implementation.](https://github.com/dotnet/runtime/blob/8ff1bd04dfce1ca7e80401053b8983e22798a29d/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs#L51-L79)

**Comment by Mr0N** [comment]
> Which don't? [`Stream.CopyTo` has a default implementation.](https://github.com/dotnet/runtime/blob/8ff1bd04dfce1ca7e80401053b8983e22798a29d/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs#L51-L79)

Previously, it would not have been, now it seems to be added to the base CopyTO class

**Comment by adamsitnik** [comment]
```cs
using var stream = File.OpenRead("file.txt");
File.WriteAllStream("myFile",stream);
```

For that we already have [File.Copy](https://learn.microsoft.com/dotnet/api/system.io.file.copy):

```cs
File.Copy("file.txt", "myFile");
```

> it saves so little and it's not so common a need that I don't see it being worth adding.

I agree.

@Mr0N thank you for your proposal! Since I don't see the need for it I am closing the issue.

**Comment by Mr0N** [comment]
> ```cs
> using var stream = File.OpenRead("file.txt");
> File.WriteAllStream("myFile",stream);
> ```
> 
> For that we already have [File.Copy](https://learn.microsoft.com/dotnet/api/system.io.file.copy):
> 
> ```cs
> File.Copy("file.txt", "myFile");
> ```
> 
> > it saves so little and it's not so common a need that I don't see it being worth adding.
> 
> I agree.
> 
> @Mr0N thank you for your proposal! Since I don't see the need for it I am closing the issue.

With Stream, which is in RAM and is not a file, can you do the same? File.Copy

**Comment by adamsitnik** [comment]
> With Stream, which is in RAM and is not a file, can you do the same?) File.Copy

You can always do `stream.CopyTo(anotherStream)`

**Comment by Mr0N** [comment]
> > With Stream, which is in RAM and is not a file, can you do the same?) File.Copy
> 
> You can always do `stream.CopyTo(anotherStream)`

CopyTo can be written from scratch.
