### ISSUE TITLE
[x86/Linux] Reverse P/Invoke Performance

### ISSUE THREAD

**Issue by parjong** [dotnet/runtime#7641]
x86 native and managed code uses different stack layout (which results in dotnet/runtime#7627) 

dotnet/coreclr#10217 attempts to fix dotnet/runtime#7627, but degrades reverse P/Invoke performance. 

We need to improve reverse P/Invoke performance.

**Comment by jkoritzinsky** [comment]
A change similar to the one proposed in https://github.com/dotnet/coreclr/pull/11165 was implemented when we moved the Reverse P/Invoke entry thunks into the JIT as part of enabling UnmanagedCallersOnly optimizations on x86.
