### ISSUE TITLE
superpmi unit test dependencies build issue

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#76421]
The superpmi unit test, src/tests/JIT/superpmi, has a project reference to two other projects (currently):

Performance\CodeQuality\Bytemark\Bytemark.csproj
Methodical\fp\exgen\10w5d_cs_do.csproj

These get built and copied into the superpmi unit test directory. The superpmi unit test then invokes them while doing a superpmi collection.

As part of the new test execution system, 10w5d_cs_do was converted to not build as standalone, and so it no longer has a .cmd/.sh wrapper script. As a result, the superpmi unit test driver can't execute it.

We need a way to build 10w5d_cs_do (and/or other tests) for use with the superpmi unit test, such that they are built with `BuildAsStandalone=true`, or some other mechanism.

This change didn't cause a failure in the superpmi unit test itself due to insufficient error checking, fixed by https://github.com/dotnet/runtime/pull/76411.

**Comment by BruceForstall** [comment]
@BrianBohe @markples fyi, this will be an issue when converting more of the test tree to the new merged model.

**Comment by markples** [comment]
For now, I'm pretty sure that you can set `<RequiresProcessIsolation>true</RequiresProcessIsolation>` on it.  I'm not sure if setting `BuildAsStandalone` (which would be a better self-documenting name to use) is good enough.  Either way, pulling a few tests out of the merged groups will be fine.  If we need a substantial fraction of the tests changed this way, then we'll need something more clever.
