### ISSUE TITLE
The DontFragment SocketOptionName doesn't appear to work on macOS

### ISSUE THREAD

**Issue by vulppine** [dotnet/runtime#76422]
### Description

Attempting to set DontFragment on a socket using `SetSocketOption` will cause a SocketException with error code 45, making it so that you can't have a socket that doesn't send fragmented packets without an exception occurring.

### Reproduction Steps

```cs
var socket = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);
socket.Bind(IPEndPoint.Parse("0.0.0.0:6500");
socket.SetSocketOption(SocketOptionLevel.IP, SocketOptionName.DontFragment, true);
```

### Expected behavior

The socket option to be correctly set.

### Actual behavior

```
Unhandled exception. System.Net.Sockets.SocketException (45): Operation not supported
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Boolean optionValue)
```

### Known Workarounds

None, that I know of. I cannot currently figure out how to actually set the raw option (it seems to be a boolean according to examples I've seen, but I've been having issues with passing in a read only span of bytes where it refuses to accept the byte span).

### Configuration

- NET 6.0.400
- macOS 11 (Big Sur)
- x64

**Comment by wfurt** [comment]
AFAIK this is limitation of macOS. There is nothing .NET can really when kernel does not support it. We did some tricks to construct full IP header for `Ping` but that really does not work for TCP & UDP.

**Comment by karelz** [comment]
@vulppine do you know which macOS versions already support this flag? That would be very useful for us.

Triage: Reasonable to test and do. Not high pri.

**Comment by antonfirsov** [comment]
> but I've been having issues with passing in a read only span of bytes where it refuses to accept the byte span

@vulppine can you share your code and error you get? `SetRawSocketOption()` is really just a wrapper around `setsockopt`, if there is an error, it should mean either incorrect usage, or an error reported by the OS.
