### ISSUE TITLE
JsonDocument.GetString implementation is not thread safe

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#76440]
Even though `JsonDocument` is nominally immutable (modulo disposability), the internal `GetString` implementation employs a caching scheme that is not thread safe:

https://github.com/dotnet/runtime/blob/5c8aade5384cbad2d086e7fae482ba0b692d3601/src/libraries/System.Text.Json/src/System/Text/Json/Document/JsonDocument.cs#L30

Since the cached field is a struct that cannot be written to or read from atomically. It might be that we could fix this in the code using a regular `System.Tuple`, thus ensuring atomic access to cached entries. Obviously this has the downside of incurring one additional allocation, but at least we can guarantee immutability (modulo disposability of course).

Related to https://github.com/dotnet/runtime/issues/17975

cc @layomia @krwq

_Originally posted by @eiriktsarpalis in https://github.com/dotnet/docs/issues/20563#issuecomment-1263202217_

**Comment by eiriktsarpalis** [comment]
Related issues: https://github.com/dotnet/runtime/issues/17975, https://github.com/dotnet/runtime/issues/31911, https://github.com/dotnet/runtime/issues/28711

**Comment by stephentoub** [comment]
Do we document JsonDocument as being thread-safe?  We generally don't make any guarantees about thread-safety of instance members unless otherwise explicitly documented, and there are many places where instance members do non-thread-safe caching.  What makes this one special enough to be worth adding cost?

And, what is this particular cache used for?  Is it really common to ask for the same string at the same index multiple times in a row with no intervening other requests?

**Comment by eiriktsarpalis** [comment]
> Do we document JsonDocument as being thread-safe? 

[We do](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/overview?pivots=dotnet-7-0#thread-safety), the [original issue}(https://github.com/dotnet/docs/issues/20563#issuecomment-1263202217) in docs was opened to account for that discrepancy. I created this separate issue to track potentially making the type thread safe in the future.

**Comment by rymeskar** [comment]
@stephentoub 
Because of the possible cross-polination of values, should this fix be marked as security fix?

**Comment by stephentoub** [comment]
I don't believe that's warranted.
