### ISSUE TITLE
[HTTP/3] Initialize MsQuic only when HTTP3 will be used to send the request.

### ISSUE THREAD

**Issue by rzikm** [dotnet/runtime#76445]
Based on discussions around https://github.com/dotnet/runtime/issues/74629, https://github.com/dotnet/runtime/pull/75163 and others. Concrete feedback in https://github.com/dotnet/runtime/pull/75330#issuecomment-1243921873

Currently, we initialize MsQuic even if HTTP3 is not considered, e.g., a lower HTTP version is set and the VersionPolicy does not allow upgrade. We do so because we precompute some data for use in HTTP3 if HTTP3 is supported (like serialized SETTINGS frame to be sent over the wire).

We should look at those places and see if it is possible to initialize MsQuic only if HTTP3 ends up actually being used to send the request.

**Comment by ManickaP** [comment]
Triage: we already solved the main issue in #74629, this is nice to have on top of that. Leaving in 8.0, but with low priority.
