### ISSUE TITLE
Investigate optimizing away Span<class> type checks

### ISSUE THREAD

**Issue by JosephTremoulet** [dotnet/runtime#7646]
The Span constructors that take arrays have [checks](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Span.cs#L45-L46) to ensure that the dynamic type of the `T[]` argument is exactly `T[]` (as opposed to `U[]` for some subtype `U` of `T`), since Spans, unlike arrays, aren't covariant.  We should see if there are cases where the JIT can optimize away this check (when the constructor gets inlined), such as when `T` is a sealed type or when we can propagate an exact type from a `new T[]` expression.
category:cq
theme:optimization
skill-level:expert
cost:medium

**Comment by EgorBo** [comment]
@AndyAyersMS @JosephTremoulet isn't it fixed in https://github.com/dotnet/runtime/pull/32790 ?

**Comment by AndyAyersMS** [comment]
Yes. Thanks again for the fix!
