### ISSUE TITLE
AV under coreclr!GlobalStringLiteralMap::AddStringLiteral

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#76494]
Stacktrace:
```
coreclr!memcpy+0x470 [D:\a\_work\1\s\src\vctools\crt\vcruntime\src\string\i386\memcpy.asm @ 596] 
coreclr!memcpyNoGCRefs+0x9 [D:\a\_work\1\s\src\coreclr\vm\common.h @ 248] 
coreclr!AllocateStringObject+0xc9 [D:\a\_work\1\s\src\coreclr\vm\stringliteralmap.cpp @ 478] 
coreclr!GlobalStringLiteralMap::AddStringLiteral+0xa6 [D:\a\_work\1\s\src\coreclr\vm\stringliteralmap.cpp @ 500] 
coreclr!GlobalStringLiteralMap::AddInternedString+0xb7 [D:\a\_work\1\s\src\coreclr\vm\stringliteralmap.cpp @ 551] 
coreclr!GlobalStringLiteralMap::GetInternedString+0x325 [D:\a\_work\1\s\src\coreclr\vm\stringliteralmap.cpp @ 433] 
coreclr!LCGMethodResolver::GetOrInternString+0xe4 [D:\a\_work\1\s\src\coreclr\vm\dynamicmethod.cpp @ 1278] 
coreclr!LCGMethodResolver::ConstructStringLiteral+0xfb [D:\a\_work\1\s\src\coreclr\vm\dynamicmethod.cpp @ 1212] 
coreclr!CEEJitInfo::constructStringLiteral+0x10c [D:\a\_work\1\s\src\coreclr\vm\jitinterface.cpp @ 11640] 
```
```
coreclr!memcpy+0x470:
721d99d0 660f6f06        movdqa  xmm0,xmmword ptr [esi] ds:002b:12239780=????????????????????????????????
```
Hit in #76466. Dump: https://dev.azure.com/dnceng-public/public/_build/results?buildId=36807&view=ms.vss-test-web.build-test-results-tab&runId=734726&resultId=194901&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab

**Comment by jkotas** [comment]
@EgorBo Looks like there may be a race condition introduced by the frozen string changes.

**Comment by EgorBo** [comment]
> @EgorBo Looks like there may be a race condition introduced by the frozen string changes.

Ah, I think I know why, let me check

**Comment by jkotas** [comment]
This change in `GlobalStringLiteralMap::AddInternedString` introduced the problem: https://github.com/dotnet/runtime/pull/49576/files#diff-d86558f39cd09fa14c22d6e7ec315bb6dcd717784d90a69680508862ea7d893cR551 . The new code has a GC hole. Also, it is inefficient to allocate a new string object if we have one already.

**Comment by EgorBo** [comment]
@jkotas yes, that was exactly my first though when I saw this issue - it was supposed to be remove "duplicated" code that is not actually dup.
