### ISSUE TITLE
[Discussion] ServiceController API needs some improvements

### ISSUE THREAD

**Issue by Fs00** [dotnet/runtime#765]
I've been using the ServiceController class for some time now in an application of mine and I personally find that some features of the API could be improved. Here they are:

- **Timeout for stopping dependent services in Stop() is extremely long (30 secs).**
Which service takes even half of that time to stop itself? In my experience, when a stop request timed out instead of taking a couple of seconds to complete, it was because the dependent service somehow ignored it and refused to stop, causing my application to wait 30 seconds uselessly without having the ability to prevent it.
I would suggest to reduce the timeout to something around 10 secs and/or add an overload to Stop that accepts a TimeSpan that specifies the timeout.
- **Stop method could be more convenient to use.**
The function `DoStopSvc` [in this official WinAPI example](https://docs.microsoft.com/en-us/windows/win32/services/stopping-a-service) checks if a stop is already pending before sending the stop control to the service, and in any case it waits for the service to stop before returning. Could ServiceController.Stop do the same? Waiting for a service to become stopped after a stop request is such a common use case that would be very convenient if Stop did it (it already does it when stopping dependent services).
- **System.ServiceProcess.TimeoutException message lacks the name of the service.**
The Stop method can raise a TimeoutException when a dependent service can't be stopped in time. The problem is that the exception doesn't tell which is the service that caused the timeout. Could this information be added in the message?

If you decide it's ok to proceed with these changes, I can take care of implementing them (for the last one I'd need some guidance on how to change exception messages resources).

*PS: I wasn't sure whether to split this issue in multiple ones at this time since it is meant as a discussion on the topic.*

**Comment by danmosemsft** [comment]
We would certainly be interested in  a PR that makes the exception(s) more useful.

**Comment by Fs00** [comment]
Ok, I'll look into it when I have some time. Can you point me in the right direction on how to change/add new exception message resources? (is some special operation needed?)
And what about the other two proposals?

**Comment by danmosemsft** [comment]
No special process for the exceptions..just a PR.

@Anipik is owner of this area and could comment on the other two suggestions

**Comment by Anipik** [comment]
@Fs00 I will take a look at the two proposals and update the issue.

**Comment by Fs00** [comment]
@Anipik Any news on those two proposals?

**Comment by Anipik** [comment]
> and/or add an overload to Stop that accepts a TimeSpan that specifies the timeout.

You can write api proposal for it and we will happy to take it.  Here is goo example of an proposal https://github.com/dotnet/runtime/issues/15725
Changing the default value of 30 secs would be an issue as it might break some body else.

> Stop method could be more convenient to use.

Feel free to throw up a pr to improve this.

**Comment by Fs00** [comment]
@Anipik After some thoughts, I've decided that it's better for consistency and compatibility to leave the Stop() method as-is, and instead I've made a proposal for a new Stop overload with the improvements I'd like to see.

**Comment by Fs00** [comment]
@Anipik After some thoughts, I've decided that it's better for consistency and compatibility to leave the Stop() method as-is. I've made a proposal for a new Stop overload with the improvements I'd like to see.

**Comment by Fs00** [comment]
#33927 and #52519 solved the biggest pain points of this API, therefore I think that this issue can be closed now.
Thank you all for your guidance! It's been great to be able to contribute 😃
