### ISSUE TITLE
Incompatible with .NET Framework 4.8.1 runtime. Loading the wrong DLL.

### ISSUE THREAD

**Issue by TokuNaNa** [dotnet/runtime#76518]
### Description
Applications programmed .NET Framework 4 do not work with .NET 4.8.1 Framework runtime. With .NET 4.8 Framework runtime works fine. so, compatibility issue with .NET 4.8.1.

### Configuration
.NET 4.8 v4.8.04161 Windows 11 21H2 x64
.NET 4.8.1 v4.8.09032 Windows 11 22H2 x64
The Applications Pegasys Inc TMPGEnc MPEG Smart Renderer 4 v4.2.4.68 x86

### Regression?
.NET Framework v4.8.09032 has issue. Known versions that work .NET Framework v4.8.04161.

### Data
Logs examined by Microsoft Detours
[net4.8 log.zip](https://github.com/dotnet/runtime/files/9693751/net4.8.zip)
[net4.8.1 log.zip](https://github.com/dotnet/runtime/files/9693750/net4.8.1.zip)

### Analysis
.NET 4.8 loading the application's own .dll (TMSR4Component.dll)
`20221002221433465 7612 50.60: trcapi32: 001 +GetFileAttributesExW(C:\WINDOWS\Microsoft.Net\assembly\GAC_32\TMSR4Component\v4.0_4.2.4.68__7000348cf46b3b30\TMSR4Component.dll,0,113b698)`

.NET 4.8.1 loading VCRUNTIME140_CLR0400.dll.
`20221002221029600 6388 50.60: trcapi32: 003 +LoadLibraryExW(C:\WINDOWS\Microsoft.Net\assembly\GAC_32\PresentationCore\v4.0_4.0.0__31bf3856ad364e35\VCRUNTIME140_CLR0400.dll,0,800)`

**Comment by jeffschwMSFT** [comment]
@TokuNaNa can you create an issue via Visual Studio send feedback (https://developercommunity.visualstudio.com/)?  That way you can privately share the source code for the failing case and we can route to the right place.

Once you create the issue, please paste the link on this issue once it is created.  Thanks

**Comment by jeffschwMSFT** [comment]
Closing this issue and moving the discussion to vs feedback.
