### ISSUE TITLE
Dispose on singleton services is not called automatically by DI Container

### ISSUE THREAD

**Issue by janseris** [dotnet/runtime#76568]
### Description

This table:
https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection#service-registration-methods
states that classes registered as singleton whose instance is created by the DI container, are disposed.
This does not work for me.
Singleton class instance disposes if and only if I manually call `Dispose `on the `ServiceProvider `as well (e.g. via wrapping the application in a `using `block).

### Reproduction Steps

Try run sample application and observe that dispose is not printed to console and a breakpoint placed in the `Dispose` function in `MyClass` is never hit in cases when `Dispose `is not called explicitly on the `ServiceProvider`

[DisposeDITest.zip](https://github.com/dotnet/runtime/files/9700885/DisposeDITest.zip)

### Expected behavior

According to the table, `Dispose` method is always called on class instances registered as singleton when the program stops correctly.
I am stopping the program using "Stop Debugging" button in Visual Studio.

Expected is that Program run in all 3 application variations calls `Dispose() `automatically.

### Actual behavior

Dispose is not called in cases where `Dispose `is not called explicitly on the ServiceProvider which is `IDisposable`

### Known Workarounds

call `Dispose()` manually

### Configuration

```
Host:
  Version:      6.0.9
  Architecture: x64
  Commit:       163a63591c
```
  
  `Microsoft.Extensions.DependencyInjection` and other packages v`6.0.0`
  
Windows 10 Home x64

**Comment by En3Tho** [comment]
Stop debugging can easily kill you process so I wouldn't count that as "stopped correctly". Does it reproduce in a simple minimal api app for example? You can stop it with default ctrl+c combination.

**Comment by janseris** [comment]
> Stop debugging can easily kill you process so I wouldn't count that as "stopped correctly". Does it reproduce in a simple minimal api app for example? You can stop it with default ctrl+c combination.

Could you give an example what is the correct way to stop program so that this automatic disposing works?

**Comment by En3Tho** [comment]
I will try to run your example tomorrow. Will reply after

**Comment by En3Tho** [comment]
I've looked at your example and I can say that not all 3 of them should call dispose.
1. At least in ServiceProviderTest project dispose isn't called at all so stuff not being disposed is expected.
2. UsingServiceProviderTest is straightforward too: dispose is called and everything is disposed.
3. HostTest project is tricky... The trick is the same as in UsingServiceProviderTest - you have to dispose host itself.

``` csharp
// this
var host = builder.Build();
// should be instead
using var host = builder.Build();
// code
```

**Comment by tarekgh** [comment]
Closing per @En3Tho comments. @janseris feel free to send more questions or tell if there is still a problem and we can reopen the issue again.
