### ISSUE TITLE
Threadpool: CLR threadpool practically deadlocks on a large number of blockign work items

### ISSUE THREAD

**Issue by ghost** [dotnet/runtime#7657]
# Symptom
For a large n (depending on the server), the following script starts a few VMs, then the server sits idle for up to several minutes, then all VMs start up nearly instantly:
```powershell
for ($i=1; $i -le n; $i++) {
    start-vm -name TestVM$i -asjob 
}
```
Adding a short pause eliminates the delay:
```powershell
for ($i=1; $i -le n; $i++) {
    start-vm -name TestVM$i -asjob 
    start-sleep -milliseconds 100 
}
```
# Analysis
Start-VM tasks each block on a task retrieving the host's name. Ordinarily, this is not impactful since the task completes very quickly. However, the task's completion callback is also a task, queued to the same thread pool. So, when a large number of blocked Start-VM tasks exhaust the supply of runnable threads, the callback has nowhere to run and the entire operation deadlocks. It eventually recovers because thread pool creates new threads not only on task completion but also on the background, although very slowly.
# Recommendation
The Windows thread pool handles this much better by increasing threads quickly when it suspects a dependency on a queued work item and then introducing delays between creating threads when it suspects an actual deadlock. It also generally compensates for blocking work much more quickly since it knows when blocking occurs. Consider switching to using the OS's thread pool, at least in .Net Core.

**Comment by kouvel** [comment]
Blocking on tasks should have improved in .NET 6 to inject threads more quickly with some backoff (https://github.com/dotnet/runtime/pull/53471). The heuristics can also be [configured](https://docs.microsoft.com/en-us/dotnet/core/runtime-config/threading#thread-injection-in-response-to-blocking-work-items).
