### ISSUE TITLE
Personalized ICU is not being used by CultureInfo

### ISSUE THREAD

**Issue by jmroyb** [dotnet/runtime#76570]
(NET 6.0.401, Windows 11 Version 10.0.22621.521 x64)

Related to:
   [https://github.com/dotnet/runtime/issues/76413](url)
   [https://github.com/dotnet/runtime/issues/75880](url)
   
Hi again,

To fix the CultureInfo months I have decided to use ICU instead of UseNls as it is deprecated since .NET 5.
But CultureInfo does not load my custom ICU.

The goal remains:
A) Have a personalized version of month of CultureInfo("ca-es").
B) Add new cultures of minories.
C) Avoid third-party interference in custom cultures.

To get the custom ICU I followed these steps:

1. Download the latest version of
   [https://github.com/unicode-org/icu/releases/tag/release-71-1](url)

2. Manipulate the ca.txt file where the literal is "d´agost" changed to "d'agost"
   icu-release-71-1\icu4c\source\data\locales\ca.txt
   (I attach file)
   
3. Compiling from the command line:
   [https://unicode-org.github.io/icu/userguide/icu4c/build.html#skipping-the-uwp-projects-on-the-command-line](url)
   msbuild source\allinone\allinone.sln /p:Configuration=Release /p:Platform=x64 /p:SkipUWP=true

4. In prova.csproj I added:
  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="71.1" />
  </ItemGroup>

5. Copy the resulting dlls from bin64 to prova.csproj.

The project compiles and runs correctly. But CultureInfo does not load the custom ICU so the character 0x2019 is still present.
Where did I go wrong?

Thanks.

[Prova.zip](https://github.com/dotnet/runtime/files/9701251/Prova.zip)

**Comment by MichalPetryka** [comment]
See this for using [app-local ICU](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#app-local-icu).

**Comment by jmroyb** [comment]
> See this for using [app-local ICU](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#app-local-icu).

Thanks, but these steps were followed and did not work

**Comment by tarekgh** [comment]
If you build your copy of ICU, you can use the [app-local](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#app-local-icu) feature. Just ensure the files are placed correctly inside the binaries folder. as example if running on Windows, place the binaries under `runtime\win-x64\native` folder. And ensure you include the following item in your csproj

```Xml
<ItemGroup>
  <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="71.0" />
</ItemGroup>
```

By the way, your ICU should produce the binaries with version number (e.g. `icudt71.dll`, `icuin71`, and `icuuc71.dll`). And the exposed API inside the modules have the postfix version too like `ucurr_forLocale_71` as an example.
	
Let me know if you have any more questions.

**Comment by jmroyb** [comment]
> ```
> <ItemGroup>
>   <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="71.0" />
> </ItemGroup>
> ```

Changed to:

<ItemGroup>
  <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="71.0" />
</ItemGroup>

Still failing

**Comment by tarekgh** [comment]
@jmroyb did you place the ICU binaries under `runtime\win-x64\native` folder inside the app folder? did the built ICU binaries has the notations as described in my comment https://github.com/dotnet/runtime/issues/76570#issuecomment-1266127002?

**Comment by jmroyb** [comment]
ICU binaries under runtime\win-x64\native:
![image](https://user-images.githubusercontent.com/4932314/193697468-6ce7afe5-b48e-4aef-b3fb-bd937c14fd33.png)
But I don't know how copy them at bin\x64\Debug\net6.0 keeping runtime\win-x64\native structure. For this reason I copied them at bin\x64\Debug\net6.0.

Change at System.Globalization.AppLocalIcu is done:

<ItemGroup>
  <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="71.0" />
</ItemGroup>

**Comment by tarekgh** [comment]
Add the following to your csproj:

```Xml
  <ItemGroup>
    <Content Include="runtimes\win-x64\native\icudt71.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="runtimes\win-x64\native\icuin71.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="runtimes\win-x64\native\icuuc71.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
```

**Comment by jmroyb** [comment]
@tarekgh:

after your item group suggestion (thanks a million!) is raised an exception at System.Globalization.GlobalizationMode:

![image](https://user-images.githubusercontent.com/4932314/193700514-b8debfad-c559-469a-8cb5-dbd12a1b1fc4.png)

[Prova2.zip](https://github.com/dotnet/runtime/files/9701562/Prova2.zip)

**Comment by tarekgh** [comment]
I'll take a look.

**Comment by tarekgh** [comment]
I didn't look deeply yet but one thing you may try quickly is placing the ICU DLLs next to your built executable. I mean on the root of the app.

**Comment by tarekgh** [comment]
Here is the complete working project that can load your built ICU. 

[Project.zip](https://github.com/dotnet/runtime/files/9702627/Project.zip)

It looks you didn't override the month names correctly in ICU though.

**Comment by jmroyb** [comment]
Thanks a lot @tarekgh. Now works. I'll check again month name.

**Comment by jmroyb** [comment]
Thanks a lot @tarekgh. Now works. I'll check again month name.
