### ISSUE TITLE
File Operation in Ubuntu 22.04

### ISSUE THREAD

**Issue by PKYADAV** [dotnet/runtime#76572]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I am facing issue in .Net Core Worker Project where I am processing image on Ubuntu Server. It's working on Windows but on Ubuntu FileStream is showing Zero Length.

//filepath: /var/www/html/sambashare/PI100,111.jpg

 var targetFile = new FileInfo(filePath);
                _logger.LogInformation($"File Info: Full Name:{targetFile.FullName} Size:{targetFile.Length} IsReadOnly:{targetFile.IsReadOnly} IsExist:{targetFile.Exists}");

Output: File Info: Full Name:/var/www/html/sambashare/PI100,111.jpg Size:0 IsReadOnly:False IsExist:True
              

### Expected Behavior

File Info: Full Name:C:\var\www\html\sambashare\PI144,11.jpg Size:114746 IsReadOnly:False IsExist:True

### .NET Version

6.0.400

**Comment by PKYADAV** [comment]
Hi Team,

Update from Debugging

Please note, same code is running successfully in WSL 2.

It's not working on Ubuntu 22.04 Server with hosting in systemd.

**Comment by danmoseley** [comment]
@PKYADAV please use `strace` to capture relevant IO events (eg, filter to this path only). You can share them here.

**Comment by PKYADAV** [comment]
[trace55.log](https://github.com/dotnet/runtime/files/9718087/trace55.log)

Hi, I am new to Ubuntu Depolyment, hence tried to trace the log. PFA for your ready reference or let me know if any specific command for the same !!

Also, found one more abnormal behaviours that is whenever I restart service, very first time it's working but next time it's not working !!

**Comment by PKYADAV** [comment]
`public async Task<bool> ReadFileData(string? filePath, CancellationToken cancellationToken)
        {
            _logger.LogInformation($"Reading File Data: {Path.GetFullPath(filePath)} ");
            try
            {
                var targetFile = new FileInfo(filePath);
                _logger.LogDebug($"File Info: Full Name:{targetFile.FullName} Size:{targetFile.Length} IsReadOnly:{targetFile.IsReadOnly} IsExist:{targetFile.Exists}");
                byte[]? imageBytes = null;
                using (FileStream fs = targetFile.OpenRead())
                {
                    try
                    {
                        _logger.LogDebug($"Read Image in byte[] {filePath} of Size: {fs?.Length} Can Read:{fs?.CanRead} Position:{fs?.Position}");
                        using var inputStream = new SKManagedStream(fs);
                        _logger.LogDebug($"Reading Image in SKBitmap {filePath} InputStream:{inputStream?.Length}");
                        using var newImage = SKBitmap.Decode(inputStream);
                        if (newImage == null)
                        {
                            _logger.LogInformation("Something went wrong while decoding SKBitmap Image from FilePath. Please try again !!");
                            return false;
                        }
                        _logger.LogDebug($"Checking Resize Option of Image in SKBitmap {filePath}");
                        using var resized = newImage.Resize(new SKImageInfo(400, 400), SKFilterQuality.High);
                        if (resized == null)
                        {
                            _logger.LogInformation("Something went wrong while resizing image. Please try again !!");
                            return false;
                        }
                        using var image = SKImage.FromBitmap(resized);
                        var data = image.Encode(SKEncodedImageFormat.Jpeg, 90);
                        using var stream = new MemoryStream();
                        data.SaveTo(stream);
                        imageBytes = stream.ToArray();
                        inputStream?.Dispose();
                        newImage?.Dispose();
                        image?.Dispose();
                        data?.Dispose();
                        stream?.Dispose();
                        stream?.Close();
                    }
                    catch (Exception ex)
                    {
                        _logger.LogError(ex, ex.Message);
                    }
                    finally
                    {
                        fs.Close();
                        fs.Dispose();
                    }
                }
              
                if (imageBytes != null)
                {
                    
                    File.Copy(filePath, ( "/Archive/" + Path.GetFileName(filePath)), true);
                    File.Delete(filePath);
                    return true;
                }
                _logger.LogDebug($"Finished Image without Processing in SKBitmap {filePath}");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
            }
            return false;
        }`

**Comment by PKYADAV** [comment]
`public async Task<bool> ReadFileData(string? filePath, CancellationToken cancellationToken)
        {
            _logger.LogInformation($"Reading File Data: {Path.GetFullPath(filePath)} ");
            try
            {
                var targetFile = new FileInfo(filePatah);
                _logger.LogDebug($"File Info: Full Name:{targetFile.FullName} Size:{targetFile.Length} IsReadOnly:{targetFile.IsReadOnly} IsExist:{targetFile.Exists}");
                byte[]? imageBytes = null;
                using (FileStream fs = targetFile.OpenRead())
                {
                    try
                    {
                        _logger.LogDebug($"Read Image in byte[] {filePath} of Size: {fs?.Length} Can Read:{fs?.CanRead} Position:{fs?.Position}");
                        using var inputStream = new SKManagedStream(fs);
                        _logger.LogDebug($"Reading Image in SKBitmap {filePath} InputStream:{inputStream?.Length}");
                        using var newImage = SKBitmap.Decode(inputStream);
                        if (newImage == null)
                        {
                            _logger.LogInformation("Something went wrong while decoding SKBitmap Image from FilePath. Please try again !!");
                            return false;
                        }
                        _logger.LogDebug($"Checking Resize Option of Image in SKBitmap {filePath}");
                        using var resized = newImage.Resize(new SKImageInfo(400, 400), SKFilterQuality.High);
                        if (resized == null)
                        {
                            _logger.LogInformation("Something went wrong while resizing image. Please try again !!");
                            return false;
                        }
                        using var image = SKImage.FromBitmap(resized);
                        var data = image.Encode(SKEncodedImageFormat.Jpeg, 90);
                        using var stream = new MemoryStream();
                        data.SaveTo(stream);
                        imageBytes = stream.ToArray();
                        inputStream?.Dispose();
                        newImage?.Dispose();
                        image?.Dispose();
                        data?.Dispose();
                        stream?.Dispose();
                        stream?.Close();
                    }
                    catch (Exception ex)
                    {
                        _logger.LogError(ex, ex.Message);
                    }
                    finally
                    {
                        fs.Close();
                        fs.Dispose();
                    }
                }
              
                if (imageBytes != null)
                {
                    
                    File.Copy(filePath, ( "/Archive/" + Path.GetFileName(filePath)), true);
                    File.Delete(filePath);
                    return true;
                }
                _logger.LogDebug($"Finished Image without Processing in SKBitmap {filePath}");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
            }
            return false;
        }`

**Comment by danmoseley** [comment]
I don't think I see `PI100,111.jpg` in that trace. You'll need to run the problematic scenario under strace - you may need to play with the flags, eg., if your scenario forks then you may need `-f`. Check your trace contains a lot of file accesses to `PI100,111.jpg`. you may also find the `-P` flag helpful to filter to that. 

https://www.man7.org/linux/man-pages/man1/strace.1.html

**Comment by PKYADAV** [comment]
Hi Team,

I thought problem has been resolved. Let me get feedback from testing team and update you with resolution asap. Thank you all for your time and support !!

**Comment by Jozkee** [comment]
@PKYADAV are you still facing this issue? And if not, do you know what solved it?

**Comment by PKYADAV** [comment]
Hi Team, sorry for the delay in response!! 

Actually, our scenario was monitoring FTP folder and read image file and process it. Whenever camera is triggered image is uploaded to FTP running on Ubuntu. 

I don't know root cause but when we have delayed the each operation by 100 ms then it is working fine. May be read operation not allowed very frequently?

**Comment by adamsitnik** [comment]
> monitoring FTP folder

How is the monitoring implemented?

> when we have delayed the each operation by 100 ms then it is working fine

I would expect that the monitoring lets you know that a new file has been just created, not created, written and flushed to disk (at this moment the length should be known). Or there might be some samba-specific `stat()` issue.

**Comment by PKYADAV** [comment]
@adamsitnik I am using filewatcher for monitoring ftp folder:

` _fileSystemWatcher = new FileSystemWatcher(new string(activeDevice?.ImageSetting?.FolderPath));
                    _fileSystemWatcher.IncludeSubdirectories = false;

                    _fileSystemWatcher.Filter = new string(activeDevice?.ImageSetting?.FileTypeFilters);
                    _fileSystemWatcher.EnableRaisingEvents = true;
                    _fileSystemWatcher.Created += async (e, args) =>
                    {
                        _logger.LogInformation($"Processing Image {args.FullPath} of {activeMachine?.Name}");
                        await Task.Delay(imageDelay);
                        await _imageFolderClient.PublishAsync(0, args.FullPath, activeMachine, activeDevice, stoppingToken);
                    };
`

and below is code of handling file operation:

`try
            {
                var targetFile = new FileInfo(filePath);
                _logger.LogDebug($"File Info: Full Name:{targetFile.FullName} Size:{targetFile.Length} IsReadOnly:{targetFile.IsReadOnly} IsExist:{targetFile.Exists}");
                byte[]? imageBytes = null;
                var newImage = SKBitmap.Decode(filePath);

                if (newImage == null)
                {
                    _logger.LogInformation("Something went wrong while decoding SKBitmap Image from SKCodec. Retrying with Renaming File !!");
                    return false;
                }

                _logger.LogDebug($"Checking Resize Option of Image in SKBitmap {filePath}");
                using var resized = newImage?.Resize(new SKImageInfo(Convert.ToInt32(ActiveDevice?.ImageSetting?.TargetWidth), Convert.ToInt32(ActiveDevice?.ImageSetting?.TargetHeight)), SKFilterQuality.High);
                if (resized == null)
                {
                    _logger.LogInformation("Something went wrong while resizing image. Please try again !!");
                    return false;
                }

                using var image = SKImage.FromBitmap(resized);
                _logger.LogDebug("Encoding Image.");
                var data = image.Encode(SKEncodedImageFormat.Jpeg, 90);
                _logger.LogDebug("Reading Image in Stream.");
                using var stream = new MemoryStream();
                data.SaveTo(stream);
                _logger.LogDebug("Converting Image in byte[].");
                imageBytes = stream?.ToArray();

                if (imageBytes != null)
                {
                    
                    var responseData = taskIndex + ActiveDevice?.DataSeperator + Convert.ToBase64String(imageBytes);
                    _logger.LogDebug($"Response Received from Network Stream (Image):{responseData}");
                    
                    File.Copy(filePath, (ActiveDevice?.ImageSetting?.FolderPath + "/Archive/" + Path.GetFileName(filePath)), true);
                    File.Delete(filePath);
                    return true;
                }

                _logger.LogDebug($"Finished Image without Processing in SKBitmap {filePath}");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
            }`

**Comment by adamsitnik** [comment]
@PKYADAV Thanks for sharing the code! You are registering for the `Created` event, I expect that it's raised right after the file gets created (so length == 0), not after the writing to the file is finished. I doubt we can do anything about it (.NET just asks the OS for the file size, OS asks file system and 0 is the answer at this moment).

Is logging 0 size an issue in the following line:

```cs
_logger.LogDebug($"File Info: Full Name:{targetFile.FullName} Size:{targetFile.Length} IsReadOnly:{targetFile.IsReadOnly} IsExist:{targetFile.Exists}");
```

Or the next one fails?

```cs
var newImage = SKBitmap.Decode(filePath);
```
