### ISSUE TITLE
A DateTime.ToString with CultureInfo("nb-NO") gives the wrong datetime string output on iOS

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#76596]
_From @jfversluis on Mon, 03 Oct 2022 14:31:01 GMT_

---
**Issue moved from dotnet/maui#10441**
- Please respond to @sith-ikjetil.

---

_From @sith-ikjetil on Saturday, October 1, 2022 2:39:32 PM_

### Description

If you compile a .NET MAUI project for iOS, you get the wrong datetime format string for Norwegian output.
If you compile a .NET MAUI project for Windows or Android, you get the correct datetime format string for Norwegian output.

I use dotnet --version 6.0.401

### Steps to Reproduce

1. Create a new .NET MAUI APP and compile for iOS.
2. Anywhere like in 'MauiProgram.cs' do something like:
3. var dt = DateTime.Now.ToString( new CultureInfo("nb-NO"));
4. dt will look like: 10/1/2022 4:00:28 PM
5. dt should look like: 01.10.2022 16:00:286

### Link to public reproduction project repository

https://github.com/sith-ikjetil/maui-cultureinfo-no-bug

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.4

_Copied from original issue xamarin/xamarin-macios#16217_

**Comment by rolfbjarne** [comment]
_From @jfversluis on Mon, 03 Oct 2022 14:31:02 GMT_

---
**Issue moved from dotnet/maui#10441**
- Please respond to @drasticactions.

---

_From @drasticactions on Monday, October 3, 2022 4:43:21 AM_

I doubt this is an issue specific with MAUI (The UI Framework) and (probably) more to do with either the runtime or SDK.

@rolfbjarne @dalexsoto Does that sound correct?

**Comment by rolfbjarne** [comment]
_From @jfversluis on Mon, 03 Oct 2022 14:31:04 GMT_

---
**Issue moved from dotnet/maui#10441**
- Please respond to @rolfbjarne.

---

_From @rolfbjarne on Monday, October 3, 2022 8:38:14 AM_

Looks like this could be a duplicate of https://github.com/dotnet/runtime/issues/68321.

@sith-ikjetil can you try printing out the current culture and see what you get?

```cs
Console.WriteLine ($"CurrentUICulture: {GetString (Thread.CurrentThread.CurrentUICulture)}");
Console.WriteLine ($"CurrentCulture: {GetString (Thread.CurrentThread.CurrentCulture)}");

static string GetString (CultureInfo ci)
{
	return $"Name: {ci.Name} NativeName: '{ci.NativeName}' DisplayName: '{ci.DisplayName}' EnglishName: '{ci.EnglishName}'";
}
```

**Comment by rolfbjarne** [comment]
_From @sith-ikjetil on Mon, 03 Oct 2022 14:39:40 GMT_

I would like to point out that I forward a CultureInfo(“nb-NO”) to DateTime ToString method, so the current thread culture and uiculture should not matter. FYI.

**Comment by rolfbjarne** [comment]
_From @rolfbjarne on Tue, 04 Oct 2022 08:32:27 GMT_

Looks like we're not shipping culture info at all for Norwegian (nor a bunch of other languages).

These languages do not show in `CultureInfo.GetCultures (CultureTypes.AllCultures)`.

Some test code: https://gist.github.com/rolfbjarne/cd23c871acb6bfd6fab9acb75c285fa3#file-appdelegate-cs

Shows that there are [238 cultures for Mac Catalyst](https://gist.github.com/rolfbjarne/cd23c871acb6bfd6fab9acb75c285fa3#file-maccatalyst-md) (and likely the same for iOS and tvOS), while there are [940 cultures for macOS](https://gist.github.com/rolfbjarne/cd23c871acb6bfd6fab9acb75c285fa3#file-macos-md) - including Norwegian (and the date is also formatted as expected)

The culture data is shipped from the runtime, so I'm moving this bug there.

**Comment by rolfbjarne** [comment]
CC @steveisok @akoeplinger

**Comment by Clockwork-Muse** [comment]
Culture info usually comes from the OS, via the ICU.  Is that not the case here?

**Comment by ufcpp** [comment]
[Invariant Mode](https://github.com/dotnet/runtime/blob/main/docs/design/features/globalization-invariant-mode.md)?

**Comment by tarekgh** [comment]
I think the ICU used in iOS is our custom build library. I am seeing the source there have data for `nb` cultures https://github.com/dotnet/icu/blob/dotnet/main/icu/icu4c/source/data/locales/nb.txt. Looking at the date format there, looks what we are getting is what is listed in the data https://github.com/dotnet/icu/blob/0795bb52b2f5f34accd97aff24255b432907c501/icu/icu4c/source/data/locales/nb.txt#L3903. 

For sure Invariant mode is not turned on.

**Comment by tarekgh** [comment]
@steveberdy @mkhamoyan I put this for 8 milestone, feel free to change it as needed.
