### ISSUE TITLE
[Question]ReadOnlySequence<T> and SequencePosition

### ISSUE THREAD

**Issue by MarcoRossignoli** [dotnet/runtime#766]
I'm working on https://github.com/dotnet/corefx/issues/31807

```cs
var bufferSegment1 = new BufferSegment<T>(new T[100]);
BufferSegment<T> bufferSegment2 = bufferSegment1.Append(new T[50]);
var buffer = new ReadOnlySequence<T>(bufferSegment1, 0, bufferSegment2, 50);
var buffer2 = new ReadOnlySequence<T>(new T[100]);
var res = buffer.Slice(0, buffer2.GetPosition(10));
```

Code above throws `System.InvalidCastException : Unable to cast object of type 'System.Byte[]' to type 'System.Buffers.ReadOnlySequenceSegment``1[System.Byte]'`
I understood that `SequencePosition` is an [index+index's fragment object] so pass a `SequencePosition` generated by on ROSeq to another ROSeq doesn't make sense(https://docs.microsoft.com/en-us/dotnet/standard/io/buffers), it's like pass a index of one array context to another array instance in another context, but I wonder if the missing check+clear exception is wanted and related to perfs.

Again in `Slice` in case of single segment there isn't any check if `SequencePosition.GetObject()` is actually equals to startObject/endObject, so I can pass a `SequencePosition` of another ROSeq  and I'll get a valid ROSeq with start from one segment and end with one of my passed `SequencePosition`

```cs
var buffer1 = new ReadOnlySequence<T>(new T[100]);
var buffer2 = new ReadOnlySequence<T>(new T[50]);
ReadOnlySequence<T> res = buffer1.Slice(0, buffer2.GetPosition(10));
```

On multisegment seem not possible because we seek(`SeekMultiSegment`) the end object.

cc: @ahsonkhan @JeremyKuhne @davidfowl

**Comment by scalablecory** [comment]
@GrabYourPitchforks

**Comment by ahsonkhan** [comment]
If I recall correctly, this was discussed in a PR during implementation and we ended up avoiding an explicit check/throw to keep the slice method as small as possible (particularly for single segment), for perf.

Like you mentioned, it isn't valid to use a sequenceposition from one ROSequence to slice another. We could consider revisting this, add the appropriate checks, and see the perf impact:
https://github.com/dotnet/performance/blob/2d44305d0a4ae098d57663bf8fd7800e82ccb9f7/src/benchmarks/micro/corefx/System.Memory/ReadOnlySequence.cs#L28
https://github.com/dotnet/performance/blob/2d44305d0a4ae098d57663bf8fd7800e82ccb9f7/src/benchmarks/micro/corefx/System.Buffers/ReadOnlySequenceTests.cs#L12

**Comment by MarcoRossignoli** [comment]
Understood...fair, hope nobody do the error in my snipped...found the bug would be nightmare 😄 because could work.

**Comment by adamsitnik** [comment]
I am closing as it looks like the question was answered.
