### ISSUE TITLE
[wasm] dotnet run doesn't work for relative path

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#76609]
### Description

dotnet run doesn't work for relative path to project file

### Reproduction Steps

- pull `dotnet-wasm-todo-mvc` sample
- move the project into `src` folder
- run `C:\Dev\dotnet-wasm-todo-mvc>dotnet run --project src\TodoMVC.csproj`

### Expected behavior

it should be `C:\Dev\dotnet-wasm-todo-mvc\src\bin\Debug\net7.0\browser-wasm\AppBundle\`

### Actual behavior

fails with `An error occurred trying to start process 'dotnet' with working directory 'C:\Dev\dotnet-wasm-todo-mvc\bin\Debug\net7.0\browser-wasm\AppBundle\'. The directory name is invalid.`

### Regression?

no

### Known Workarounds

step into src diretory

**Comment by pavelsavara** [comment]
cc @radical

**Comment by radical** [comment]
@pavelsavara which version are you using? The fix for this was backported to `release/7.0` in https://github.com/dotnet/runtime/pull/75508 .

**Comment by pavelsavara** [comment]
`7.0.0-rc.1.22427.1` so this is RC1. 
And I also tested that applying the fix helps. Thanks!
