### ISSUE TITLE
Json.Text - Unable to deserialize ObservableCollection with Preserve option

### ISSUE THREAD

**Issue by Rayzbam** [dotnet/runtime#76602]
### Description

We're trying to serialize deserialize ObservableCollection.
We encountered an issue when the following option is setted : 
`new JsonSerializerOptions() { ReferenceHandler = ReferenceHandler.Preserve }`

We added this option to handle our cyclic reference (recursive parent for example) and can't remove it.

### Reproduction Steps

Create an object with an ObservableCollection of integer (for example) as Property of this class.

Try serialize the object with following options : 
`new JsonSerializerOptions() { ReferenceHandler = ReferenceHandler.Preserve }`

Then deserialize as usual and you won't be able to retrieve the ObservableCollection

### Expected behavior

I would like to handle my cyclic references AND deserialize my ObsevableCollection.

### Actual behavior

Throw a "The JSON value could not be converted to System.Collections.ObjectModel.ObservableCollection`1[System.Int32]" error.

### Regression?

I don't think so.

### Known Workarounds

Nop.

**Comment by eiriktsarpalis** [comment]
Could you share a standalone console app that demonstrates the problem? Thanks.

**Comment by Rayzbam** [comment]
> Could you share a standalone console app that demonstrates the problem? Thanks.

[https://gist.github.com/Rayzbam/aa2d7c834055e2c64a67a9b8475bf30d.js](url)

**Comment by eiriktsarpalis** [comment]
Your reproduction is not passing the same options configuration in the deserialize method. As soon as I change it, round tripping works as expected.

**Comment by Rayzbam** [comment]
Thank for your help, and sorry for the inconvenience.

Can be closed.
