### ISSUE TITLE
Cannot load symbols for release project when "Publish Single File" is set to true - it want's to load "singlefilehost.pdb". 

### ISSUE THREAD

**Issue by okipol88** [dotnet/runtime#76601]
I have a project which is set as so:

``` xml
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <PlatformTarget>x64</PlatformTarget>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <PlatformTarget>x64</PlatformTarget>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>pdbonly</DebugType>
    <PublishSingleFile>false</PublishSingleFile>
    <SelfContained>true</SelfContained>
  </PropertyGroup>
```

I can attach to it  and debug when running it in release. 
When I change `<PublishSingleFile>false</PublishSingleFile>` to true it doesnt work while failing with failed to load modules and it wants to load `singlefilehost.pdb`.

I have added a minimal reproduction repository (Publish Single File is set to true): 
https://github.com/okipol88/NET6Test

Am I missing some crucial information/option?

**Comment by elinor-fung** [comment]
Are you trying to do managed debugging or native debugging (or both)?

The symbol file for the native executable is `singlefilehost.pdb` - that represents the host/runtime itself, not your managed code. It should be available on the [Microsoft public symbol server](https://learn.microsoft.com/windows-hardware/drivers/debugger/microsoft-public-symbols).

For your managed application code, PDBs should be generated just as in non-single-file and [a debugger attached to the application](https://learn.microsoft.com/dotnet/core/deploying/single-file/overview?tabs=cli#attach-a-debugger) should be able to use them. Are you unable to load symbols for your managed assemblies?

**Comment by okipol88** [comment]
@elinor-fung 
I added a vanilla example of how this fails in the attached repo.
I use the NET6Test in the VS terminal and run `dotnet run -c Release`.
Then I try to attach to it:

![image](https://user-images.githubusercontent.com/8424432/195548637-4aae87e1-1f8d-4baa-853d-32e36c8015da.png)

When attached I get this:

![image](https://user-images.githubusercontent.com/8424432/195548760-cea33d24-3a23-4763-aeb4-78403eaf506e.png)

When I open the modules I get:

![image](https://user-images.githubusercontent.com/8424432/195548990-fab8d2a6-cfd9-4b01-a4eb-d53a9b7bb529.png)

When trying to load I get:

![image](https://user-images.githubusercontent.com/8424432/195549085-e96581b8-23f6-4f1b-bfe3-7056edc5a48f.png)

When switching by hand to Managed (.NET 5+):
![image](https://user-images.githubusercontent.com/8424432/195549360-8bef8a58-f3f7-4bb2-8883-389c08faa50b.png)

I get this:
![image](https://user-images.githubusercontent.com/8424432/195549426-3c7c7691-f052-4461-9ded-1968c18d59ad.png)

**Comment by elinor-fung** [comment]
For the `singlefilehost` symbols in native debugging - do you have the Microsoft symbol server included in your symbol paths?

For the error with managed debugging - what version of VS are you using?

@dotnet/dotnet-diag Which versions of VS should have single-file debugging support? Thoughts on the 'debugger protocol is incompatible with the debuggee' error?

**Comment by okipol88** [comment]
I am using `Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.3.0`
OK enabling Microsoft Symbol Servers helped with one error...
I did run the app from the publish which has the `mscordbi.dll` and also the specific `pdb` files included.
Still no luck:

![image](https://user-images.githubusercontent.com/8424432/195682138-41799c58-eddb-4ad8-a9ab-6ba9271843c3.png)

**Comment by hoyosjs** [comment]
Debugging single file has a few fixes slated for 17.4, I am not sure if 17.3 had full support for it yet. @gregg-miskelly, do you happen to know?

**Comment by gregg-miskelly** [comment]
Single file debugging support will first ship with Visual Studio 2022 version 17.4. You can install it now from the Preview channel (see [here](https://visualstudio.microsoft.com/vs/preview/)).

**Comment by elinor-fung** [comment]
Thanks, @gregg-miskelly.
@okipol88 Could you try out the latest Visual Studio 2022 version 17.4 preview?

**Comment by okipol88** [comment]
@elinor-fung Downloading...

**Comment by okipol88** [comment]
@elinor-fung Still no luck:
![vs2017_4](https://user-images.githubusercontent.com/8424432/197245233-f15cc7dc-6d05-4efe-b410-de2aa9298237.png)

**Comment by elinor-fung** [comment]
Can you check that you have managed debugging enabled?

I only see native modules in the screenshot. For native debugging, `singlefilehost.pdb` is (and will remain) the symbol file for the executable itself and should be found if you use the Microsoft Symbol Servers.

In Visual Studio 2022 17.4.0 Preview 4.0, I was able to debug the managed code in your project with the below:
- Publish the project either `dotnet publish` or the through VS
- Debug > Attach to Process > Select 'Managed (.NET Core, .NET 5+) code' > Attach to NET6Test.exe
- Set a breakpoint in Program.cs (turn off Just My Code as necessary for Release)

**Comment by okipol88** [comment]
@elinor-fung 
Manually setting .NET 5+ when attaching and disabling "Just my code" made it debugable in "Release" using Visual Studio 2022 17.4.0 Preview 4.0. Wo hoo :) waiting for official update.

![giphy](https://user-images.githubusercontent.com/8424432/197347723-070690bb-3bff-441c-98f0-138a6407b2a5.gif)
