### ISSUE TITLE
[API Proposal]: Use Predicate<T> instead of Func<T, bool>

### ISSUE THREAD

**Issue by undrcrxwn** [dotnet/runtime#76627]
### Background and motivation

At the moment, `Func<T, bool>` is used all over the standard library, even though the `Predicate<T>` delegate exists. If you search for all `Func<T, bool>`-typed parameters in the current version of the standard library, you will instantly notice that they share the same name that is `predicate`. So why not to use a more concrete and semantically accurate type? `Predicate<T>` that is.

I think this wouldn't be a big deal to replace all `Func<T, bool>` parameters named `predicate` since no human attention is needed while separating occasional collisions between the two types (thanks to the naming).

This would help `System.*` become a much more user-friendly and unambiguous API that keeps up with time.

### Source references:
- [`TResult Func<in T, out TResult>(T)`](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Private.CoreLib/src/System/Function.cs#L7)
- [`bool Predicate<in T>(T)`](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Private.CoreLib/src/System/Action.cs#L33)

### API Proposal

```csharp
namespace System.Linq;

public static partial class Enumerable
{
    // The predicate parameter is actually a Predicate
    public static bool All<TSource>(this IEnumerable<TSource> source, Predicate<TSource> predicate)
    {
        // ...
    }
}
```

### API Usage

```csharp
var xs = Enumerable.Range(0, 10);

// IDE suggests Predicate instead of Func
var arePositive = xs.All(x => x > 0);
```

### Alternative Designs

Func is not an alternative. Migrating to Predicate is just a matter of time.

### Risks

Not a single risk. Believe me, I don't lie.
UPD: there are **zero** issues regarding compatibility.

**Comment by alexrp** [comment]
This is a breaking change for very little benefit, making it kind of a "big deal" indeed.

Also, if anything, new code prefers `Func<T, bool>` over `Predicate<T>`.

**Comment by teo-tsirpanis** [comment]
As @alexrp said, this is a breaking change and cannot happen so I'm closing it. One of the benefits of `Func` and `Action` over explicit delegate types is that you immediately know the delegate's parameters and return type.
