### ISSUE TITLE
Remove runtime dependencies on libstdc++

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#76655]
Transferred from https://github.com/dotnet/corert/issues/3564.

NativeAOT runtime does not use any C++ features (exception handling, etc.), but it still depends on libstdc++ here and there for no good reason. Consider cleaning these up and remove dependency on libstdc++ to improve minimal footprint.

**Comment by am11** [comment]
This removes the dependency from linux (clang, gcc) and osx (clang) https://github.com/dotnet/runtime/compare/main...am11:runtime:feature/nativeaot/nostdlib++.

I haven't tested on windows, but I am sure its support needs work.

**Comment by MichalStrehovsky** [comment]
Neat! Thank you for looking into it! Could you please submit it as a pull request?

We probably don't need to worry about Windows - Windows doesn't distinguish between C and C++ runtime support - it's all in a single library that is present on all OSes. It's most interesting on Linux because the most minimal distros only come with a libc and C++ is an extra dependency one needs to install (as demonstrated here: https://github.com/eerhardt/Albums/blob/104ae182f72dccf522092ec33a340b8eb02529b7/AlbumsNetCore/Dockerfile#L2).

**Comment by driver1998** [comment]
> We probably don't need to worry about Windows - Windows doesn't distinguish between C and C++ runtime support 

Is it possible to only rely on UCRT on Windows?

**Comment by josephmoresena** [comment]
Would this remove the libc++_shared.so library dependency on Android?

**Comment by am11** [comment]
> Would this remove the libc++_shared.so library dependency on Android?

@josephmoresena, this issue is for coreclr NativeAOT. Android NativeAOT is related to mono runtime (different sources and configurations). @lambdageek, do you know if `libc++_shared.so` dependency removal is feasible? I do not have a developer environment for Android, so it is hard to assess from reading the code. 😁

> Is it possible to only depend on UCRT on Windows?

@driver1998, yes it is possible as a next step to work out the differences and add them to stdc++compat object we introduced in #76705 and use it on Windows as well. `stdc++compat` is a very slim object supporting Unix (Linux and macOS). This indicates that we do not need much from C++ runtime library in NativeAOT apps. @MichalStrehovsky was pointing to a pragmatic approach  to tackle Linux target first, where C++ runtime library is optional and minimal containerized scenario will benefit more by dependency removal.

macOS is in the same category that the system comes installed with C++ runtime library. With stdc++compat, this is the difference reported by `otool -L crossgen2`:

```diff
--- before
+++ after

-	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1856.105.0)
-	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 1141.1.0)
+	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1858.112.0)
 	/System/Library/Frameworks/CryptoKit.framework/Versions/A/CryptoKit (compatibility version 1.0.0, current version 1.0.0)
-	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1856.105.0)
+	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1858.112.0)
 	/System/Library/Frameworks/GSS.framework/Versions/A/GSS (compatibility version 1.0.0, current version 1.0.0)
-	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 60157.60.19)
-	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
-	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1200.3.0)
+	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 60158.100.133)
+	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
+	/usr/lib/libicucore.A.dylib (compatibility version 1.0.0, current version 70.1.0)
 	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
 	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
-	/usr/lib/swift/libswiftCore.dylib (compatibility version 1.0.0, current version 1300.0.46)
-	/usr/lib/swift/libswiftCoreFoundation.dylib (compatibility version 1.0.0, current version 14.0.0, weak)
-	/usr/lib/swift/libswiftCoreGraphics.dylib (compatibility version 1.0.0, current version 2.0.0, weak)
-	/usr/lib/swift/libswiftDarwin.dylib (compatibility version 1.0.0, current version 0.0.0, weak)
-	/usr/lib/swift/libswiftDispatch.dylib (compatibility version 1.0.0, current version 11.0.0, weak)
-	/usr/lib/swift/libswiftFoundation.dylib (compatibility version 1.0.0, current version 70.101.0)
-	/usr/lib/swift/libswiftIOKit.dylib (compatibility version 1.0.0, current version 1.0.0, weak)
-	/usr/lib/swift/libswiftObjectiveC.dylib (compatibility version 1.0.0, current version 3.0.0, weak)
-	/usr/lib/swift/libswiftXPC.dylib (compatibility version 1.0.0, current version 1.1.0, weak)
+	/usr/lib/swift/libswiftCore.dylib (compatibility version 1.0.0, current version 5.6.0)
+	/usr/lib/swift/libswiftFoundation.dylib (compatibility version 1.0.0, current version 72.105.0)
```
(C++ is gone, but Swift is still there 😅 but overall, it is better)

**Comment by jkotas** [comment]
> Is it possible to only depend on UCRT on Windows?

We are statically linking the tiny bit of C++ runtime that we need on Windows already. We do not depend on any C++ runtime .dll on Windows.

**Comment by josephmoresena** [comment]
> @josephmoresena, this issue is for coreclr NativeAOT. Android NativeAOT is related to mono runtime (different sources and configurations). @lambdageek, do you know if libc++_shared.so dependency removal is feasible? I do not have a developer environment for Android, so it is hard to assess from reading the code. 😁

I actually talk about coreclr. @MichalStrehovsky made a branch to allow build it using the NDK.

Currently for some reason the upgrade of that branch is broken but it was usefull in order to create JNI libraries with pure C#.

**Comment by am11** [comment]
> I actually talk about coreclr.

OK, then it shouldn't have that dependency as long as user does not set `<LinkStandardCPlusPlusLibrary>true`. I haven't tested Android.
