### ISSUE TITLE
`Monitor.TryEnter` sometimes fails even if `Monitor.IsEntered` returns `true`

### ISSUE THREAD

**Issue by ForNeVeR** [dotnet/runtime#76660]
### Description

In a large code base, we have a snippet like this:
```csharp
object myMutex = new object();

void Foo()
{
    if (Monitor.IsEntered(myMutex))
    {
        if (!Monitor.TryEnter(myMutex))
            LogError("Fail"); // #1
    }
}
```

Theortically, line `#1` should never be visited, right? But we observe that it actually gets visited sometimes.

Initially, we weren't checking `Monitor.TryEnter` inside of `Monitor.IsEntered`, of course, and this code was added for diagnostic purposes after we've noticed deadlocks related to this piece of code: the thread holding the monitor was receiving `false` from `Monitor.TryEnter`, despite it should theoretically always succeed and return `true`.

### Reproduction Steps

This was initially reported by the user of our product, and we were able to track it down to the described code.

We are occasionally able to trigger the code to enter this line locally, during a debug session, but so far were unable to prepare an isolated MCVE. We are able to share more code if this helps.

### Expected behavior

`Monitor.TryEnter` should always succeed if the calling thread is holding the lock (i.e. if `Monitor.IsEntered` returns `true`).

### Actual behavior

`Monitor.TryEnter` occasionally returns `false` despite the calling thread holding the lock (i.e. if `Monitor.IsEntered` returns `true`).

### Known Workarounds

Replace a call to `Monitor.TryEnter(myMutex)` with the following block:
```csharp
if (Monitor.IsEntered(myMutex))
  Monitor.Enter(myMutex);
```

Surprisingly, this works so far.

### Configuration

- **.NET version:** .NET 6.0.8
- **OS:** Windows 10
- **Architecture**: x64

**Comment by Clockwork-Muse** [comment]
> `Monitor.TryEnter` should always succeed if the calling thread is holding the lock (i.e. if `Monitor.IsEntered` returns true).

You're describing a re-entrant lock.  They're almost always a bad idea, and you should attempt to adjust things so that you don't attempt to re-take the lock.  At minimum, it's unclear why you're reacquiring the lock here at all.  Depending on your actual code, the ideal situation would include removing `Monitor.Entered` - you would **know** the current thread and execution path have the lock.

> Surprisingly, this works so far.

Not really.
It's a blocking API, so it's going to wait until it can take the lock, whereas `TryEnter` doesn't.  You may be opening yourself up to deadlocks at some point, though.

All this aside, my initial guess is that you're using `Monitor` in some `async` code; if `Entered` is being called before a suspension point (ie, `await`), that would explain the symptoms.  That's... usually a bad idea.  We'd have to see more of your code, but you'd likely need to switch to an async-capable lock type, or change strategies altogether.

**Comment by kevingosse** [comment]
> We are occasionally able to trigger the code to enter this line locally, during a debug session, but so far were unable to prepare an isolated MCVE. We are able to share more code if this helps.

If you manage to capture a memory dump when that happens during a debug session, it could help understanding what's happening.

**Comment by igor-akhmetov** [comment]
> You're describing a re-entrant lock. They're almost always a bad idea, and you should attempt to adjust things so that you don't attempt to re-take the lock. 

This is a very strong statement. I don't see what is wrong with using the `Monitor` API as a reentrant lock if it advertises itself as such.

> It's a blocking API, so it's going to wait until it can take the lock, whereas TryEnter doesn't. You may be opening yourself up to deadlocks at some point, though.

Why would `Enter` block or cause a deadlock on the thread that is already holding the lock?

> All this aside, my initial guess is that you're using Monitor in some async code.

No, the code is not async.

> If you manage to capture a memory dump when that happens during a debug session, it could help understanding what's happening.

So we need to collect a process dump when the process gets stopped on the breakpoint at line #1, is that correct?

**Comment by kevingosse** [comment]
> So we need to collect a process dump when the process gets stopped on the breakpoint at line https://github.com/dotnet/runtime/pull/1, is that correct?

That would be great, yes. If you're using Visual Studio, you can use Debug -> Save Dump As: https://learn.microsoft.com/en-us/visualstudio/debugger/using-dump-files?view=vs-2022#BKMK_Create_a_dump_file

**Comment by Mr0N** [comment]
> ```cs
> object myMutex = new object();
> 
> void Foo()
> {
>     if (Monitor.IsEntered(myMutex))
>     {
>         if (!Monitor.TryEnter(myMutex))
>             LogError("Fail"); // #1
>     }
> }
> ```

```
static object myMutex = new object();

void Foo()
{
    if (Monitor.IsEntered(myMutex))
    {
        if (!Monitor.TryEnter(myMutex))
            LogError("Fail"); // #1
    }
}
```

**Comment by Mr0N** [comment]
it can slip through if many threads use this method in one instance, it might be lucky or not, it’s better to make the field static so that all threads have their own blocking object

**Comment by Mr0N** [comment]
Well, maybe it's not static, maybe two streams get he
![image](https://user-images.githubusercontent.com/61237140/194133236-fa075c8f-2d40-48f3-8d5d-40ed001a51d7.png)
re at once

**Comment by Mr0N** [comment]
Then one blocks the object, and the second cannot block it because the object is already blocked

**Comment by filipnavara** [comment]
@Mr0N `Monitor.IsEntered` is documented to return `true` if the *current* thread is holding the lock.

**Comment by Mr0N** [comment]
> 



> @Mr0N `Monitor.IsEntered` is documented to return `true` if the _current_ thread is holding the lock.

I am not talking about the fact that when two threads execute if, the blocking object is not yet free for them, they enter the if together

**Comment by AndreyG** [comment]
I have collected process dump, where could I upload it to?

**Comment by AndreyG** [comment]
[Dump](https://drive.google.com/file/d/1QP3oowXqDQCM41bg2wTrXcxaXDJc9uBD/view?usp=sharing).

**Comment by kevingosse** [comment]
That's indeed really weird. I can confirm that the offending thread entered the `if (!Monitor.TryEnter(myMutex))` block despite owning the lock:

```
0:053> !syncblk
Index         SyncBlock MonitorHeld Recursion Owning Thread Info          SyncBlock Owner
  814 000001FB2E3F4B68            5         1 000001FB2FD7A190 1d38  53   000001faa154b288 System.Object
```

I saw nothing wrong in the disassembly, so that sounds like an issue in `Monitor.TryEnter`. There are two other threads competing for the lock so I wonder if that's part of the story 🤔

**Comment by kouvel** [comment]
It could be this path or maybe other similar races while the sync block is transitioning:
https://github.com/dotnet/runtime/blob/e01db30f8631d8bc6612453fb44792384ec9fa21/src/coreclr/vm/syncblk.inl#L631-L635

It doesn't seem right to return `false` from `TryEnter` due to internal synchronization races, I think it should be based on the lock state. I'll scan over the implementation and look into a fix.

**Comment by kouvel** [comment]
Thanks for the dump, from that it looks like the sync block has transitioned already and based on the state of it at the time of the dump, I didn't see any way for TryEnter to return false. So likely it's a race during transition.

**Comment by Mr0N** [comment]
> Thanks for the dump, from that it looks like the sync block has transitioned already and based on the state of it at the time of the dump, I didn't see any way for TryEnter to return false. So likely it's a race during transition.

https://github.com/dotnet/runtime/blob/215b39abf947da7a40b0cb137eab4bceb24ad3e3/src/coreclr/System.Private.CoreLib/src/System/Threading/Monitor.CoreCLR.cs#L84 Maybe the problem is that the object is somehow unavailable for 0 nanoseconds, for example, the second thread is reading it

**Comment by kevingosse** [comment]
> Thanks for the dump, from that it looks like the sync block has transitioned already and based on the state of it at the time of the dump, I didn't see any way for TryEnter to return false. So likely it's a race during transition.

Do you mean the transition from thin-lock to syncblock? Based on that assumption I managed to repro the issue:

```csharp
class Program
{
    private static volatile object _mutex;

    static async Task Main()
    {
        _mutex = new();

        for (int i = 0; i < 8; i++)
        {
            var t = new Thread(() =>
            {
                while (true)
                {
                    var m = _mutex;

                    Monitor.Enter(m);

                    if (!Monitor.TryEnter(m))
                    {
                        Debugger.Break();
                    }

                    Monitor.Exit(m);
                    Monitor.Exit(m);

                    _mutex = new();
                }
            });

            t.Start();
        }

        Console.WriteLine("Running");
        Console.ReadLine();
}
```

**Comment by Mr0N** [comment]
> > Thanks for the dump, from that it looks like the sync block has transitioned already and based on the state of it at the time of the dump, I didn't see any way for TryEnter to return false. So likely it's a race during transition.
> 
> Do you mean the transition from thin-lock to syncblock? Based on that assumption I managed to repro the issue:
> 
> ```cs
> class Program
> {
>     private static volatile object _mutex;
> 
>     static async Task Main()
>     {
>         _mutex = new();
> 
>         for (int i = 0; i < 8; i++)
>         {
>             var t = new Thread(static () =>
>             {
>                 while (true)
>                 {
>                     var m = _mutex;
> 
>                     Monitor.Enter(m);
> 
>                     if (!Monitor.TryEnter(m))
>                     {
>                         Debugger.Break();
>                     }
> 
>                     Monitor.Exit(m);
>                     Monitor.Exit(m);
> 
>                     _mutex = new();
>                 }
>             });
> 
>             t.Start();
>         }
> 
>         Console.WriteLine("Running");
>         Console.ReadLine();
> }
> ```
> 
> I was not able to reproduce the issue without recreating a new object every time (so very likely an issue during the promotion of the thin lock).

It's not a problem, it's just a volatile field

**Comment by kevingosse** [comment]
> It's not a problem, it's just a volatile field

That's completely irrelevant. You can use Interlocked operations instead if that makes you feel better:

```csharp
class Program
{
    private static object _mutex;

    static async Task Main()
    {
        Interlocked.CompareExchange(ref _mutex, new object(), null);
        for (int i = 0; i < 32; i++)
        {
            var t = new Thread(static () =>
            {
                while (true)
                {
                    var m = Interlocked.CompareExchange(ref _mutex, null, null);

                    Monitor.Enter(m);

                    if (!Monitor.TryEnter(m))
                    {
                        Debugger.Break();
                    }

                    Monitor.Exit(m);
                    Monitor.Exit(m);

                    _mutex = Interlocked.CompareExchange(ref _mutex, new object(), m);
                }
            });

            t.Start();
        }

        Console.WriteLine("Running");
        Console.ReadLine();
}

**Comment by Mr0N** [comment]
> Contributor

![image](https://user-images.githubusercontent.com/61237140/196505122-4ac07bad-0bd8-4a8b-b6db-ff2bf4e7922a.png)

**Comment by kevingosse** [comment]
@Mr0N Yes it means you reproduced the issue. Since you're not stopping the execution in the `if (!Monitor.TryEnter(m))` block, you end up with one `Monitor.Exit` too many. If you want to fix that:

```csharp
var m = Interlocked.CompareExchange(ref _mutex, null, null);

Monitor.Enter(m);

if (!Monitor.TryEnter(m))
{
    Console.WriteLine("Shouldn't happen");
}
else
{
    Monitor.Exit(m);
}

Monitor.Exit(m);

_mutex = Interlocked.CompareExchange(ref _mutex, new object(), m);
```

**Comment by EgorBo** [comment]
Reminds me that issue I faced with frozen segments recently - GC could collect a sync block from a live object and potentially allocate a new syncblock on that place for a different object resulting that live object started pointing to a different sync object. Just in case if it potentially can be a similar issue.

**Comment by Mr0N** [comment]
> > It's not a problem, it's just a volatile field
> 
> That's completely irrelevant. You can use Interlocked operations instead if that makes you feel better:
> 
> ```cs
> class Program
> {
>     private static object _mutex;
> 
>     static async Task Main()
>     {
>         Interlocked.CompareExchange(ref _mutex, new object(), null);
>         for (int i = 0; i < 32; i++)
>         {
>             var t = new Thread(static () =>
>             {
>                 while (true)
>                 {
>                     var m = Interlocked.CompareExchange(ref _mutex, null, null);
> 
>                     Monitor.Enter(m);
> 
>                     if (!Monitor.TryEnter(m))
>                     {
>                         Debugger.Break();
>                     }
> 
>                     Monitor.Exit(m);
>                     Monitor.Exit(m);
> 
>                     _mutex = Interlocked.CompareExchange(ref _mutex, new object(), m);
>                 }
>             });
> 
>             t.Start();
>         }
> 
>         Console.WriteLine("Running");
>         Console.ReadLine();
> }
> ```


 if (Monitor.IsEntered(myMutex))
Monitor.IsEntered

Reference

Monitor.IsEntered is not here

**Comment by Mr0N** [comment]
> @Mr0N Yes it means you reproduced the issue. Since you're not stopping the execution in the `if (!Monitor.TryEnter(m))` block, you end up with one `Monitor.Exit` too many. If you want to fix that:
> 
> ```cs
> var m = Interlocked.CompareExchange(ref _mutex, null, null);
> 
> Monitor.Enter(m);
> 
> if (!Monitor.TryEnter(m))
> {
>     Console.WriteLine("Shouldn't happen");
> }
> else
> {
>     Monitor.Exit(m);
> }
> 
> Monitor.Exit(m);
> 
> _mutex = Interlocked.CompareExchange(ref _mutex, new object(), m);
> ```

Monitor.IsEntered is not here

**Comment by Mr0N** [comment]
And it works through object replacement, probably

**Comment by Mr0N** [comment]
```
using System;
class Program
{
    static object myMutex = new object();
    static void Start()
    {
        for (int i = 0; i < 15; i++)
        {
            Task.Run(() =>
            {
                while (true)
                {
                    myMutex = new object();
                    Monitor.Enter(myMutex);
                }
            });
        }
    }
    static  void Main()
    {
        
        Monitor.Enter(myMutex);
        if (Monitor.IsEntered(myMutex))
        {
            myMutex = new object();
            Start();
            while (true)
            {
                if (!Monitor.TryEnter(myMutex))
                    Console.WriteLine("log");
            }
        }
        Monitor.Exit(myMutex);
        Console.ReadKey();

    }
}
```

**Comment by Mr0N** [comment]
I think the problem is that the chunk of memory is locked, so TryEnter can't access it in 0 nanoseconds, i.e. quickly

**Comment by kevingosse** [comment]
@ForNeVeR Just a thought: as an alternative workaround, you can call `GetHashCode` on the objects used for locking after allocating them:

```
    public CppPriorityMutex(CppPriorityMutex.TagT tag)
    {
      myMutex = new object();
      _ = myMutex.GetHashCode();
      myPrioritisedMutex = new object();
      _ = myPrioritisedMutex .GetHashCode();
      myLockRequestPriority = CppPriorityMutex.Priority.Low;
    }
```

This will force the promotion to a syncblock as soon as a thread tries locking those objects (instead of waiting for the first moment the lock is contended). In my tests this seems to fix the race condition.

**Comment by ForNeVeR** [comment]
Couldn't this `_ = myMutex.GetHashCode()` be optimized away at some point?

**Comment by kevingosse** [comment]
> Couldn't this `_ = myMutex.GetHashCode()` be optimized away at some point?

I could be wrong, but given that `Object.GetHashCode()` has a side-effect, I don't think it can be optimized away.

**Comment by Mr0N** [comment]
> ```cs
> Exit
> ```

Why are there two Monitor.Exit?

**Comment by Mr0N** [comment]
> > It's not a problem, it's just a volatile field
> 
> That's completely irrelevant. You can use Interlocked operations instead if that makes you feel better:
> 
> ```cs
> class Program
> {
>     private static object _mutex;
> 
>     static async Task Main()
>     {
>         Interlocked.CompareExchange(ref _mutex, new object(), null);
>         for (int i = 0; i < 32; i++)
>         {
>             var t = new Thread(static () =>
>             {
>                 while (true)
>                 {
>                     var m = Interlocked.CompareExchange(ref _mutex, null, null);
> 
>                     Monitor.Enter(m);
> 
>                     if (!Monitor.TryEnter(m))
>                     {
>                         Debugger.Break();
>                     }
> 
>                     Monitor.Exit(m);
>                     Monitor.Exit(m);
> 
>                     _mutex = Interlocked.CompareExchange(ref _mutex, new object(), m);
>                 }
>             });
> 
>             t.Start();
>         }
> 
>         Console.WriteLine("Running");
>         Console.ReadLine();
> }
> ```



Why are there two Monitor.Exit?

**Comment by filipnavara** [comment]
> Why are there two Monitor.Exit?

Because there are two Enters (Enter and TryEnter).

**Comment by Mr0N** [comment]
> 

The ones that seem like if you do 100 Monitor.Enter on the object, then you need to do 100 Monitor.Exit? This is already some kind of queue)

**Comment by Clockwork-Muse** [comment]
> `_mutex = Interlocked.CompareExchange(ref _mutex, new object(), m);`

Regardless of the rest of this issue, isn't this just ensuring you're re-using the same object each round?  Since you're re-assigning the replacement to the old value.
Although it's buggy, because the value that got replaced may have been picked up by one of the other threads, and so you could potentially have multiple dueling mutexes being used.
Shouldn't the assignment be removed, and just retain the interlocked operation at that point (eg: `Interlocked.CompareExchange(ref _mutex, new object(), m);`)?

**Comment by kevingosse** [comment]
> > `_mutex = Interlocked.CompareExchange(ref _mutex, new object(), m);`
> 
> Regardless of the rest of this issue, isn't this just ensuring you're re-using the same object each round? Since you're re-assigning the replacement to the old value. Although it's buggy, because the value that got replaced may have been picked up by one of the other threads, and so you could potentially have multiple dueling mutexes being used. Shouldn't the assignment be removed, and just retain the interlocked operation at that point (eg: `Interlocked.CompareExchange(ref _mutex, new object(), m);`)?

Yeah you're right 👍

**Comment by Mr0N** [comment]
> ```cs
> TryEnter
> ```

Is it possible to block the object twice?

**Comment by Mr0N** [comment]
> > Why are there two Monitor.Exit?
> 
> Because there are two Enters (Enter and TryEnter).

Is it possible to block the object twice?

**Comment by Mr0N** [comment]
![image](https://user-images.githubusercontent.com/61237140/196906634-a4fe5a4d-cdd3-4bac-8e4c-0bffa8c0cf5f.png)

**Comment by Mr0N** [comment]
In these tests, everything works normally, before it enters for, where Exit is called, then the waiting thread blocks its own thread, and then TryEnter is called in this thread

**Comment by igor-akhmetov** [comment]
@Mr0N Everybody would really appreciate if you stopped spamming this issue. 
@kevingosse @kouvel Thanks a lot for the quick investigation and the fix!

**Comment by Mr0N** [comment]
> 

I started this test, something doesn't work, it probably depends on the processor or something else. When I added another Monitor.Exit then it started doing it.

**Comment by filipnavara** [comment]
@Mr0N The enters/exits have to be paired. The general concept is known as recursive mutex. If you enter it twice within the same thread then it just increments an internal counter since you know it's already locked.

As for the actual product bug... .NET / CoreCLR uses an optimization called "thin locks". Under specific set of circumstances (eg. no previous call to `GetHashCode`) there is a fast code path for Monitor.Enter/TryEnter/Exit as long as there is no contention on the lock. It simply updates flags in the object header to record the state of the lock. Once a contention happens though (ie. one thread has already acquired the lock through Monitor.Enter and another thread tries to acquire the lock through Monitor.Enter) the "thin lock" optimization is abandoned and it transitions into a new state where the lock is tracked through indirect entry in a "sync table". Under normal circumstances this optimization should be entirely unobservable. Unfortunately it was not...

Consider the following scenario:
- Thread 1 enters the lock through Monitor.Enter, the lock is still represented as thin lock
- Thread 2 tries to acquire the same lock. It realizes that it is acquired and represented as "thin lock". It starts the transition from "thin lock" into "full lock" representation.
- Thread 1 calls Monitor.TryEnter precisely at the same moment as Thread 2 is in middle of the transition. Instead of waiting for the transition to complete (in thread 2) it incorrectly bails out and returns `false`

**Comment by Mr0N** [comment]
```
using System;


for (int i = 0; i < 1000; i++)
{
    Start();
}

 void Start()
{
    object objLock = new object();
    bool begin = true;
    var thread = new Thread(() =>
    {
        Monitor.Enter(objLock);
        while (begin) { }
        if (!Monitor.TryEnter(objLock))
            global::System.Console.WriteLine("TryEnter");
        global::System.Console.WriteLine("thread 1");
    });
    var threadSecond = new Thread(() =>
    {
        while (begin) { }
        if(Monitor.TryEnter(objLock,100))
            Console.WriteLine("TryEnter Block enter");
        global::System.Console.WriteLine("thread 2");
    });
    var threadThree = new Thread(() =>
    {
        while (begin) { }
        Monitor.Enter(objLock);
        global::System.Console.WriteLine("thread 3");
    });
    thread.Start();
    threadSecond.Start();
    threadThree.Start();
    Thread.Sleep(100);
    begin = false;
}
//mutex.Dispose();
Console.ReadKey();
```
Yes, this code is already working

**Comment by kouvel** [comment]
> I can’t do something to repeat the result of what is on the test code, what is on this, probably it depends on the PC or something else

The test case from the fix repros fairly frequently on my machine when using a debug build of coreclr, a lot less frequently when using a release build. Also, .NET Framework doesn't have the issue.
