### ISSUE TITLE
Improve Networking docs

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#76661]
We just started effort to improve Networking docs over next few weeks.

We will welcome contributions and help if you are interested!

Here are queries we are working on:
- **dotnet/docs** repo:
    - [Networking tech area](https://github.com/dotnet/docs/issues?q=is%3Aopen+is%3Aissue+label%3Adotnet-networking%2Ftech)
    - Other issues in the repo are not properly marked by Networking label, we will have to do a sweep
- **dotnet/dotnet-api-docs** repo: [Networking areas](https://issuesof.net/?q=is%3Aissue%20is%3Aopen%20repo%3Adotnet%2Fdotnet-api-docs%20%28label%3Aarea-System.Net%20OR%20label%3Aarea-System.Net.Http%20OR%20label%3Aarea-System.Net.Sockets%20OR%20label%3Aarea-System.Net.Security%20OR%20label%3Aarea-Extensions-HttpClientFactory%29%20group%3Aarea%20sort%3Acreated-desc)
- **dotnet/runtime** repo: [Networking areas](https://issuesof.net/?q=is%3Aissue%20is%3Aopen%20repo%3Adotnet%2Fruntime%20area-lead%3Akarelz%20group%3Aarea%20sort%3Acreated-desc%20label%3Adocumentation)

We will welcome any PRs. Or even suggestions what to change, where and how to make our docs easier for developers.

Note: We internally track work in a project board (private due to org-level limitations). If you are serious about doing more contributions over next few weeks, we could add you there.

**Comment by GSPP** [comment]
This is very commendable. I am linking to a previous issue that contains some discussion and ideas:

- https://github.com/dotnet/dotnet-api-docs/issues/7609

Are these efforts targeted at fixing individual shortcomings, or will there be "no stone left unturned"?

**Comment by karelz** [comment]
It depends on each area and the needs there. This one I will leave to @antonfirsov @liveans to decide / recommend approach.

**Comment by liveans** [comment]
> * [Rewrite socket documentation entirely, leave no stone unturned dotnet-api-docs#7609](https://github.com/dotnet/dotnet-api-docs/issues/7609)

I think, we need to discuss this with @antonfirsov and make a decision on it, since this is a lot of work to do. We need to do prioritization.

**Comment by wfurt** [comment]
Complete rewrites may not be better than old one. I would be more in favor of improvements by area of importance. For example, we replaced some of the APM does with not not to use it when possible. 
It is also easier IMHO with some specific plan. Feel free to contribute @GSPP with specific PRs. Documentation is open to community contributions same way as code is.

**Comment by karelz** [comment]
We addressed most pressing feedback, incl. conceptual docs for most important areas. 68 finished issues / PRs: https://github.com/orgs/dotnet/projects/180/views/1

Closing as done for 8.0.
