### ISSUE TITLE
Why is `CCKeyDerivationPBKDF` not used in non-macOS Apple platforms?

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/runtime#76684]
In iOS, tvOS and Mac Catalyst we use [the managed implementation of PBKDF2](https://github.com/dotnet/runtime/blob/0c9bd9bef97d0ff618541cc068aec01d93c66596/src/libraries/System.Security.Cryptography/src/System.Security.Cryptography.csproj#L1329) for some reason. Why don't we use the native `CCKeyDerivationPBKDF` function, as we do on macOS? [BitWarden has been using it on iOS without problems.](https://github.com/bitwarden/mobile/blob/1e5eab057476295184a97102696a765a2b4387e6/src/iOS.Core/Services/CryptoPrimitiveService.cs)

c.c. @vcsjones who originally wrote the native code.

**Comment by vcsjones** [comment]
According to the PR that added the one-shots for iOS (the crypto bringup for iOS happened after I did the PBKDF2 implementation) https://github.com/dotnet/runtime/pull/51714, the APIs are private.


Looking at the [header definition](https://github.com/apple-oss-distributions/CommonCrypto/blob/06c4e37bc508d502031035d8606ade275d6c0d82/include/CommonKeyDerivation.h#L96-L100):

```c
int
CCKeyDerivationPBKDF( CCPBKDFAlgorithm algorithm, const char *password, size_t passwordLen,
                      const uint8_t *salt, size_t saltLen,
                      CCPseudoRandomAlgorithm prf, unsigned rounds,
                      uint8_t *derivedKey, size_t derivedKeyLen)
                      API_AVAILABLE(macos(10.7), ios(5.0));
```

It's available as of iOS 5.0, but not tvOS.

I suppose it could be done so that iOS used that implementation and keep using the managed implemented for tvOS.

**Comment by vcsjones** [comment]
I'll submit a change for iOS. /cc @filipnavara since you did the original iOS work.

**Comment by filipnavara** [comment]
It certainly was marked as not available at some point: 

```c
int 
CCKeyDerivationPBKDF( CCPBKDFAlgorithm algorithm, const char *password, size_t passwordLen,
                      const uint8_t *salt, size_t saltLen,
                      CCPseudoRandomAlgorithm prf, uint rounds, 
                      uint8_t *derivedKey, size_t derivedKeyLen)
                      __OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_NA);
```

(Source: https://opensource.apple.com/source/CommonCrypto/CommonCrypto-55010/CommonCrypto/CommonKeyDerivation.h)

**Comment by vcsjones** [comment]
Yeah, thanks for finding that. That is what I recalled, too. At some point Apple started making it a non-private API in their SDK.

**Comment by filipnavara** [comment]
> It's available as of iOS 5.0, but not tvOS.

@vcsjones Looking at the header again, isn't tvOS implied by the iOS if not specified explicitly?

**Comment by vcsjones** [comment]
@filipnavara hmm. Is that how those available declarations work?

**Comment by filipnavara** [comment]
> @filipnavara hmm. Is that how those available declarations work?

There's some implication like that but I am never quite sure. There's definitely iOS -> MacCatalyst so maybe I just confused it in my mind, but maybe not...

**Comment by vcsjones** [comment]
I was able to build a tvOS project with it without issue, so, I think yes this is available in tvOS. I will correct the PR.

**Comment by filipnavara** [comment]
https://nshipster.com/available/

> When an API is marked as available in iOS, it’s implicitly marked available on tvOS and Mac Catalyst, because both of those platforms are derivatives of iOS. That’s why, for example, the (missing) documentation for UICollectionViewCompositionalLayout reports availability in iOS 13.0+, Mac Catalyst 13.0+, and tvOS 13.0+ despite its declaration only mentions iOS 13.0.
