### ISSUE TITLE
Linq is missing some optimizations for readonly collections

### ISSUE THREAD

**Issue by jhinder** [dotnet/runtime#76709]
### Description
Some Linq operations like `Any()` and `Count()` have optimizations that check for known types like `ICollection<T>`, `ICollection` etc and use their `Count` property as an optimization to avoid the slow path via the enumerator (which can also lead to allocation). [Example: `Count()`](https://source.dot.net/#System.Linq/System/Linq/Count.cs,41ef9e39e54d0d0b).

If the source only implements `IReadOnlyCollection<T>` but not `ICollection<T>` (or their nongeneric siblings), the optimization cannot occur, despite these interfaces also offering a `Count` property.

`Count()` is probably the worst offender here, as it performs a full enumeration to determine the count, i.e. it has linear runtime.

### Configuration
```
BenchmarkDotNet=v0.13.2, OS=Windows 10 (10.0.19044.2006/21H2/November2021Update)
Intel Core i7-8850H CPU 2.60GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
.NET SDK=6.0.401
  [Host]     : .NET 6.0.9 (6.0.922.41905), X64 RyuJIT AVX2
  DefaultJob : .NET 6.0.9 (6.0.922.41905), X64 RyuJIT AVX2
```

### Regression?
Probably not a regression, as .NET Framework also only checked for `ICollection` etc, not the readonly variants -- see [the code for `Count()`](https://referencesource.microsoft.com/#System.Core/System/Linq/Enumerable.cs,41ef9e39e54d0d0b) as an example.

### Data
**`Any()`:**
|             Method |      Mean |     Error |    StdDev | Ratio | RatioSD |   Gen0 | Allocated | Alloc Ratio |
|------------------- |----------:|----------:|----------:|------:|--------:|-------:|----------:|------------:|
| ReadonlyCollection | 19.163 ns | 0.1669 ns | 0.1480 ns |  3.28 |    0.03 | 0.0051 |      24 B |          NA |
|         Collection |  5.844 ns | 0.0314 ns | 0.0278 ns |  1.00 |    0.00 |      - |         - |          NA |

**`Count()`:**
|             Method |       Mean |     Error |    StdDev | Ratio | RatioSD |   Gen0 | Allocated | Alloc Ratio |
|------------------- |-----------:|----------:|----------:|------:|--------:|-------:|----------:|------------:|
| ReadonlyCollection | 327.058 ns | 6.4056 ns | 5.9918 ns | 62.35 |    0.98 | 0.0048 |      24 B |          NA |
|         Collection |   5.251 ns | 0.0255 ns | 0.0226 ns |  1.00 |    0.00 |      - |         - |          NA |

### Analysis
An obvious fix would be to add corresponding typechecks to the methods. The downside would be an increase in code size, both in IL and JITted code
([SharpLab example](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBLANgHwAEAmARgFgAoQgBgAJDSUBuKqwgZgdKQeLoDCdAN5U64ugG0AygAsAhlAAOAGXnAAdACUArgDsM2ALYwNAKWwYA4jD0wo2MAAoMATyUwIAMyfYDASn8AXTEJTm5ePwxBCH0MAB4AFQA+F1lsAGduDiTkugzYqDAYfxFQiQlsLzonAp0imDpMugBJLRh5ABMAeT1cVwEIXFwYMEMIPVy6KAh/coqyygXlhgB2aYgNQbjWJZWAX3mKo4kAelO6RO6AEW66dozo7zoTDFkITpPxQnWaXYrDpR9kA)).

### Benchmark code
```csharp
using System.Collections;
using System.Collections.Generic;

namespace Performance;

[MemoryDiagnoser]
public class LinqOptimizations
{
    private ICollection<string> _mutable;
    private IReadOnlyCollection<string> _readonly;

    [Benchmark]
    public void ReadonlyCollection()
    {
        // _ = _readonly.Any();
        _ = _readonly.Count();
    }

    [Benchmark(Baseline = true)]
    public void Collection()
    {
        // _ = _mutable.Any();
        _ = _mutable.Count();
    }

    [GlobalSetup]
    public void Setup()
    {
        const int count = 128;
        _mutable = Enumerable.Repeat<string>(default, count).ToList();
        _readonly = new RoCollection<string>(count);
    }
}

public sealed class RoCollection<T> : IReadOnlyCollection<T>
{
    public RoCollection(int count)
    {
        Count = count;
    }

    public IEnumerator<T> GetEnumerator() => new DummyEnumerator(Count);

    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

    public int Count { get; }

    private sealed class DummyEnumerator : IEnumerator<T>
    {
        public DummyEnumerator(int count)
        {
            _maxCount = count;
        }

        private int _count;
        private readonly int _maxCount;

        public bool MoveNext() => _count++ < _maxCount;

        public void Reset() => _count = 0;

        public T Current => default;

        object IEnumerator.Current => Current;

        public void Dispose()
        {
        }
    }
}
```

**Comment by tfenise** [comment]
https://github.com/dotnet/runtime/issues/42254
