### ISSUE TITLE
Wasm AOT can produce functions with too many parameters

### ISSUE THREAD

**Issue by kg** [dotnet/runtime#76719]
At present, if a wasm function has more than 1000 parameters, v8 (and as a result Chrome and Edge) will refuse to compile it. Right now our AOT pipeline can generate a function with more parameters than that if the original C# function has too many parameters.

Binaryen is being updated to generate a build-time warning about this ( see https://github.com/emscripten-core/emscripten/issues/17988#issuecomment-1270466673 ) but we should detect it during the build process and either not AOT the method or fail the build.

I'm unaware of any way that this would affect customer applications, but we have code in our automated tests ( https://github.com/dotnet/runtime/blob/3f0106aed2ece86c56f9f49f0191e94ee5030bff/src/libraries/System.Text.Json/tests/Common/TestClasses/TestClasses.Constructor.cs#L2393 for example) that does this and as a result right now the test suites don't start under console when run with AOT enabled.

**Comment by lewing** [comment]
see https://github.com/dotnet/runtime/issues/76093 and https://github.com/dotnet/runtime/issues/71984 (and the linked issues) for background on the test

**Comment by kg** [comment]
Can we fix this test?

**Comment by lewing** [comment]
fixed in https://github.com/dotnet/runtime/pull/80243
