### ISSUE TITLE
[wasm] Link all the documentation on wasm in the repo, in a single top level document

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#76722]
We have the documentation for wasm builds, debugging, library tests, CI etc spread all over the repository, to be close to the relevant bits. But that makes it difficult to find anything. The top level documents in `docs/` should link to all the wasm docs, so they can be found from a single starting point.

**Comment by teo-tsirpanis** [comment]
(@radical FYI `untriaged` means without a milestone. If you set a milestone the bot will remove the label. I set it to 8.0.0.)
