### ISSUE TITLE
[System.IO.Hashing] crc32 hash does not match

### ISSUE THREAD

**Issue by onefreddy** [dotnet/runtime#76720]
Hi I tried this library (Version 6.0.2 in net 6 project). And the result it gives is wrong. For comparison
1) HashTab result: B8FF80ED
![image](https://user-images.githubusercontent.com/73015418/194400683-5174e9ec-b094-4802-a53f-f9a42d6315f8.png)

2) php result: B8FF80ED
```
<?php

$data = file_get_contents("diary-now.json");
$hash = strtoupper(hash('crc32b', $data));
echo $hash;
```

3) c# result (wrong): ed80ffb8
```
        static async Task Main(string[] args)
        {
            var crc32 = new Crc32();

            using (var fs = File.OpenRead("diary-now.json"))
            {
                await crc32.AppendAsync(fs);
            }

            var checkSum = crc32.GetCurrentHash();
            var hash = BitConverter.ToString(checkSum).Replace("-", "").ToLower();

            Console.WriteLine(hash);
        }
```

**Comment by vcsjones** [comment]
It looks like the endianness is backward. The bytes are backward.

```
B8-FF-80-ED
 
ED-80-FF-B8
```

According to the [.NET docs](https://learn.microsoft.com/en-us/dotnet/api/system.io.hashing.crc32?view=dotnet-plat-ext-7.0):

> This implementation emits the answer in the Little Endian byte order so that the CRC residue relationship 

I suspect those other tools are showing the CRC32 value in big endian.

I think you just need to reverse the bytes:


```C#
var checkSum = crc32.GetCurrentHash();
Array.Reverse(checkSum);
var hash = BitConverter.ToString(checkSum).Replace("-", "").ToLower();
```
