### ISSUE TITLE
Possible to detect AOT mode during runtime?

### ISSUE THREAD

**Issue by sengiv** [dotnet/runtime#76739]
This can be helpful when doing A/B testing or when showing AOT version of the app only to desktop users.

_For example_, we are using Azure CDN to mask 2 versions of the same app,
mobile users get the normal Blazor & desktop users get the AOT version.
With the same domain name.

_The obvious solution_ is to set a flag during the build process of the AOT version.
And this is the direction we are heading. 

**_But is there another straightforward way?_**

**Comment by huoyaoyuan** [comment]
Is `RuntimeFeature.IsDynamicCodeCompiled` sufficient?

**Comment by Suchiman** [comment]
Benchmark.NET uses this trick to detect which runtime it's running on https://github.com/dotnet/BenchmarkDotNet/blob/1f5637c784ad9887a2d5abdba54d1337655281b1/src/BenchmarkDotNet/Portability/RuntimeInformation.cs#L44-L47

**Comment by hez2010** [comment]
The BenchmarkDotNet trick is incorrect because PublishSingleFile also produces `null` for Assembly.Location.

**Comment by sengiv** [comment]
@huoyaoyuan 
> Is `RuntimeFeature.IsDynamicCodeCompiled` sufficient?

After multiple tests, this does not work (tried in .NET 6 & .NET 7)

I tried the line below just before `await webAssemblyHost.RunAsync();`
`Console.WriteLine(RuntimeFeature.IsDynamicCodeCompiled?"AOT MODE":"NORMAL MODE");`
Unfortunately, it only returns false both in AOT and Interpreted.

**Comment by hez2010** [comment]
How about `RuntimeFeature.IsDynamicCodeSupported`?

**Comment by sengiv** [comment]
> How about `RuntimeFeature.IsDynamicCodeSupported`?
> 
> Mode	IsDynamicCodeSupported	IsDynamicCodeCompiled
> JIT	True	True
> Interpret	True	False
> AOT	False	False

Thanks a lot @hez2010, `RuntimeFeature.IsDynamicCodeSupported` is working perfectly.
Tested working in .NET 7
