### ISSUE TITLE
[x86/Linux] Call with an struct argument having long member

### ISSUE THREAD

**Issue by seanshpark** [dotnet/runtime#7674]
While working with `FEATURE_FIXED_OUT_ARGS`, dotnet/coreclr#10034, I'm now with this problem.
This sample program shows the issue.
```
    public struct MyStruct
    {
        public static readonly MyStruct Zero = new MyStruct();
        internal long _ticks;
    }

    public class Program
    {
        public static void DoIt(string id, MyStruct bb)
        {
        }

        public static void DoTest()
        {
            DoIt("a", MyStruct.Zero);
        }

        public static void Main(string[] args)
        {
            DoTest();
        }
    }
```
Calling `MyStruct.Zero` which is a structure object as a parameter in `DoIt("a", MyStruct.Zero);` fails.
But sending through a variable is OK. Current implementation doesn't seem to handle this case.
```
        public static void DoTest()
        {
            MyStruct temp = MyStruct.Zero;
            DoIt("a", temp);
        }
```

Failing point is at [src/jit/lower.cpp#L968](https://github.com/dotnet/coreclr/blob/900113351c78d676d0d853df24bdc51a1f1171df/src/jit/lower.cpp#L968)
category:correctness
theme:structs
skill-level:expert
cost:small

**Comment by jakobbotsch** [comment]
This seems stale, will close it. Please reopen if necessary.
