### ISSUE TITLE
[API Proposal]: jagged arrays should be allowed to be initialized with second length

### ISSUE THREAD

**Issue by Rand-Random** [dotnet/runtime#76742]
### Background and motivation

One line initialization of a jagged array with uniform length.

### API Proposal

    var jaggedArray = new int[10][20];

### API Usage

To initial the array without the necessity to do this: 

    var jaggedArray = new int[10][];
    for (int i = 0; i < 10; i++) 
        jaggedArray[i] = new int[20]

**Comment by teo-tsirpanis** [comment]
Thanks for the suggestion. It is however a suggestion to the C# language and should be proposed as a discussion on https://github.com/dotnet/csharplang.

**Comment by Rand-Random** [comment]
Never sure if runtime, compiler, cslang feature.
Thanks.
