### ISSUE TITLE
Emit Contention/Start and Contention/Stop Events on Native AOT Apps

### ISSUE THREAD

**Issue by brianrob** [dotnet/runtime#76754]
Currently, native AOT apps don't emit Contention events.  We should add these events for native AOT apps so that we can see how long each waiter waits on a contended lock.

**Comment by VSadov** [comment]
related to https://github.com/dotnet/runtime/issues/75108

**Comment by MichalStrehovsky** [comment]
Native AOT lock type was replaced with a new shared lock that generates these events. I believe we can close this.
