### ISSUE TITLE
Update WebAssembly Browser and Console App templates to display localhost app URLs instead of 127.0.0.1

### ISSUE THREAD

**Issue by danroth27** [dotnet/runtime#76769]
### Description

The output from running the WebAssembly Browser and Console App templates shows the app URLs using 127.0.0.1 for the host instead of localhost, which causes a browser error when using the HTTPS address due to a mismatch with the developer certificate.

### Reproduction Steps

Create a WebAssembly Browser App, run it, and look at the app URLs in the output.

### Expected behavior

App URLs use localhost for the host instead of 127.0.0.1, and browser to the app over HTTPS doesn't result in an unfriendly certificate error.

### Actual behavior

```
App url: http://127.0.0.1:9000/index.html
App url: https://127.0.0.1:60191/index.html
```

![image](https://user-images.githubusercontent.com/1874516/194676095-998a8edb-1815-4ae3-a80d-97540db52bce.png)

### Configuration

7.0.100-rc.2.22477.23

**Comment by radical** [comment]
@danroth27 @javiercn I need some help with this.

We are currently picking the urls with:
https://github.com/dotnet/runtime/blob/f156fb9dcf121e536b93ae90bcc5e8e6d5336062/src/mono/wasm/host/BrowserHost.cs#L74-L76
This is how we configure the WebHostBuilder, and set the urls with `UseUrls`:
https://github.com/dotnet/runtime/blob/f156fb9dcf121e536b93ae90bcc5e8e6d5336062/src/mono/wasm/host/WebServer.cs#L21-L45

IIUC, I can't use `localhost:0` to use a dynamic port. I tried `.UseUrls(new string[] { "http://[::1]:0", "https://[::1]:0" });`, which works but then I get:
```
App url: http://[::1]:46451/index.html?arg=-vm
App url: https://[::1]:33577/index.html?arg=-vm
```
.. which doesn't have the expanded host part, even though we are reading these addresses in `IHostApplicationLifetime.ApplicationStarted` event handler:
https://github.com/dotnet/runtime/blob/f156fb9dcf121e536b93ae90bcc5e8e6d5336062/src/mono/wasm/host/WebServerStartup.cs#L171-L178

What am I missing? And what's the correct way of doing this?
I wasn't able to find the equivalent code in `dotnet/aspnetcore`. I also tried `WebHost.CreateDefaultBuilder(Array.Empty<string>())`, which didn't help.

**Comment by radical** [comment]
And IIUC, I can't use `ListenLocalhost(0)` to use a dynamic port.

**Comment by danroth27** [comment]
@Tratcher Can you help out with this?

**Comment by Tratcher** [comment]
In the normal templates we pre-generate the ports and store them in the launchsettings.json. Can you do something like that?

Otherwise, I suggest not specifying the url at all so that the server can use the default `http://localhost:5000`.

**Comment by maraf** [comment]
> I think I also implemented this in our new templates, pre-generate the portst and store them in the launchsettings.json.

Yes, I can confirm that. The generated `launchSettings.json` contains pre-generated ports.

@radical Can we also support a document root `/` instead of `index.html`?

**Comment by thaystg** [comment]
@lewing can someone from your team work on it?

**Comment by ilonatommy** [comment]
Fixed by https://github.com/dotnet/runtime/pull/88985. Current state:
![image](https://github.com/user-attachments/assets/d9974c8b-8146-468a-8a40-12794484397d)
