### ISSUE TITLE
CoreCLR failed to build with error Failed to retrieve information about 'Microsoft.DotNet.Arcade.Sdk' on MSVC

### ISSUE THREAD

**Issue by fangzhouxia** [dotnet/runtime#76776]
### Description

Hi all,
CoreCLR fails to build with error Failed to retrieve information about 'Microsoft.DotNet.Arcade.Sdk'.  Could you help look?

**detail log**
[build (40).log](https://github.com/dotnet/runtime/files/9738752/build.40.log)

### Reproduction Steps

1. git clone https://github.com/dotnet/runtime F:\gitP\dotnet\runtime
2. cd F:\gitP\dotnet\runtime
3. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=x86 -arch=x86
4. cd F:\gitP\dotnet\runtime
5. .\build.cmd -subset clr+libs -c release -arch x86 2>&1
6. cd F:\gitP\dotnet\runtime\src\coreclr
7. .\build-runtime.cmd x86 release 2>&1

### Expected behavior

Build successfully

### Actual behavior

GET https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.ps1
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Extracting the archive.
dotnet-install: Adding to current process PATH: "F:\gitP\dotnet\runtime\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://docs.microsoft.com/dotnet/core/install/windows#dependencies
dotnet-install: Installed version is 6.0.100-rc.1.21411.28
dotnet-install: Installation finished
F:\gitP\dotnet\runtime\artifacts\toolset\restore.proj : error : Failed to retrieve information about 'Microsoft.DotNet.Arcade.Sdk' from remote source 'https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/45bacae2-5efb-47c8-91e5-8ec20c22b4f8/nuget/v3/flat2/microsoft.dotnet.arcade.sdk/index.json'.
F:\gitP\dotnet\runtime\artifacts\toolset\restore.proj : error : Failed to retrieve information about 'Microsoft.DotNet.Arcade.Sdk' from remote source 'https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/d1622942-d16f-48e5-bc83-96f4539e7601/nuget/v3/flat2/microsoft.dotnet.arcade.sdk/index.json'.

### Regression?

 .NET  6.0

### Configuration

VS version: VS2019 (16.11.18)
windows server 2019
.NET 6.0
the commit of CoreCLR we use is 9703660

**Comment by jkotas** [comment]
This is caused by infrastructure maintenance that is taking longer than expected.

**Comment by kasperk81** [comment]
it's a questionable design to not be able to build any dotnet repo locally or in ci, when single cloud service breaks down. what's more frustrating is the lack of transparency on azure devops part. https://status.dev.azure.com/_event/340223455 is underplaying the effect of this issue: "Some Pypi packages fail to download returning 500 error" when pkgs service is simply unavailable for any nuget package.

serious cloud services don't just breakdown and shutdown for hours / days every other week. it's a continuous pain with no resolution in sight:
* 429s https://github.com/NuGet/Home/issues/10558
* 503s https://github.com/dotnet/arcade/issues/10943

using other package hosting service (myget, cloudsmith) as a backup plan will save everyone's time.

**Comment by jkotas** [comment]
This is not a general Azure DevOps outage. This problem is specific to .NET engineering infrastructure. The .NET engineering team is reconfiguring the feeds.

@dotnet/dncenghot Any updates?

**Comment by kasperk81** [comment]
it doesn't seem like the case https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/49a1bb2b-12b0-475f-adbd-1560fc76be38/nuget/v3/flat2/microsoft.net.illink.tasks/index.json

> "TF10216: Azure DevOps services are currently unavailable. Try again later. Activity Id: da34957e-3f39-4f5c-ad29-c9adda116c58"

**Comment by jkotas** [comment]
Do you see the same problem for any feeds that are not under https://pkgs.dev.azure.com/dnceng/ ?

**Comment by kasperk81** [comment]
no problem in other feeds. it is dnceng specific. sorry. :)

**Comment by jkotas** [comment]
The feeds are online.
