### ISSUE TITLE
Cannot hit breakpoint when Blazor wasm project path contains special characters

### ISSUE THREAD

**Issue by fzh233** [dotnet/runtime#76777]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

This problem occurs when the created project path contains the # character

### Expected Behavior

Hit breakpoint

### Steps To Reproduce

Create a Blazor WASM project with the # character in the project path

### .NET Version

6.0.400

### Anything else?

![image](https://user-images.githubusercontent.com/43662175/194699126-c3f5e19c-38de-4934-87f1-f815d5e0ccce.png)
![image](https://user-images.githubusercontent.com/43662175/194699137-06fd05c8-0ac3-4f70-8c8b-e7a99001f08d.png)

**Comment by thaystg** [comment]
@lewing this is fixed on .net7, do we want to backport?

**Comment by ChristianLindkvist** [comment]
I just upgraded my WASM-project to .net 7 and now I cannot hit breakpoints if there are special characters in the path. Doesnt seem fixed, it worked in .net 6. See attached image, if I set a breakpoint I get a blank page and I can see weird characters when I hover the path. 

![image](https://user-images.githubusercontent.com/12038695/201096496-494d752f-9a99-487b-af1a-511f3c8576d2.png)
