### ISSUE TITLE
[API Proposal]: Allocate blittable objects on stack memory

### ISSUE THREAD

**Issue by kgb7711** [dotnet/runtime#76787]
### Background and motivation

In a game loop, if we want to display fps, the game app will generate tons of string instances, thus has a huge impact on performance.
If we can allocate blittable object on stack, the impact will be greatly alleviated. We need the following:
char* ptr = stackalloc $"The frame per second is :{fps}."; //Because string is an array of chars,it is blittable

### API Proposal

using System;

public class Game
{
      private bool running = true;

       private void ShowFPS()
       {
             char* ptr = stackalloc $"The frame per second is :{fps}."; //Because string is an array of chars,it is blittable
             .......
       }

       public void Render()
       {
            while (running)
            {
                  DrawScene();
                  ShowFPS();
            } 

       }

}

### API Usage

char* ptr = stackalloc $"The frame per second is :{fps}."; //Because string is an array of chars,it is blittable

**Comment by stephentoub** [comment]
This is possible today:
```C#
Span<char> ptr = stackalloc char[512]; // however much state you're comfortable using
ptr.TryWrite($"The frame per second is :{fps}.", out int charsWritten);
```

**Comment by Clockwork-Muse** [comment]
> If we can allocate blittable object on stack, the impact will be greatly alleviated.

It'll be alleviated on the C# side.  It might not be alleviated on the engine side, depending on what your graphics frontend/backend is using.  
More specifically, `char` in C# is 16 bits (specifically UTF-16), whereas a native graphics api will be using.... could be many things, but if you want multi-culture support and multi-platform support, you're looking at either UTF-8 (variable width) or some 32-bit representation (UTF-32, or just the unicode character code directly).

**Comment by srxqds** [comment]
we also want to allocate objects on the stack from the engine side, avoid the gc object.

the scenario show below:
```
// engine call c# code
void Test(ClassA a)
{
    MonoObject* obj = allocate obj bind to a;
    MonoObject* Target;
    MonoMethod* Method;
    void* Params[1] = {obj};

    mono_runtime_invoke(Method, Target, &Params);
}

```

if we can allocate obj on stack memory, it can reduce many gc pressure

**Comment by Clockwork-Muse** [comment]
> we also want to allocate objects on the stack from the engine side, avoid the gc object.

Strictly speaking, C# `struct`s are value objects, and will be on the stack if declared inside a method.  
If you're trying to interface to native memory you're going to want blittable/pinnable structs/objects (which is a fairly involved topic).

That said, you can eliminate a lot of GC issues just by doing what most native-only game engines do for "heap" objects - pool them.  Engines like Unreal prefer you not `new`-up in-game objects directly, instead mandating that you call specific object-creation (and destruction) routines, for a variety of reasons.  Essentially, these engines have a (relatively simple) GC that tends to run at end-of-frame.

**Comment by srxqds** [comment]
yeah, I know struct, but the struct can't be inherited, we should define object with class.
In other words, we need to allocate objects that can be quickly gc at the stack end.

**Comment by Clockwork-Muse** [comment]
> but the struct can't be inherited

In general, prefer composition over inheritance.  If your engine is using a classical Entity Component System, you likely don't need inheritance for the main "game object" (although arbitrarily sized arrays can't be used in a blittable object).

> In other words, we need to allocate objects that can be quickly gc at the stack end.

The clr does a reasonably good job of handling small short-lived objects (gen 0) already.  That aside, it's apparently possible to have blittable/pinned objects with the same layout in both managed/unmanaged memory, meaning copies aren't required.

**Comment by EgorBo** [comment]
> This is possible today:
> 
> ```cs
> Span<char> ptr = stackalloc char[512]; // however much state you're comfortable using
> ptr.TryWrite($"The frame per second is :{fps}.", out int charsWritten);
> ```

@stephentoub is it possible to add interpolation handlers for CopyTo/TryCopyTo? e.g.:
```csharp
Span<char> ptr = stackalloc char[512];
$"fps: {fps}".TryCopyTo(ptr);
```
this code is simpler but it allocates

**Comment by stephentoub** [comment]
> this code is simpler

Even if were possible, I'm not sure how it's simpler. You'd still need to know how many chars were written to know how much of the output buffer is valid, at which point its exactly the same as the existing TryWrite just with argument positions reversed.
