### ISSUE TITLE
[API Proposal]: add global await

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#76789]
### Background and motivation

I suggest adding block 
```
await{
}
```
For asynchronous methods in this block, await will be supplied exactly.
I have given two methods below, they should work the same

### API Proposal

```csharp
  public async Task ExampleNotAwait()
        {
            await{
                Task.Delay(100);
                Task.Delay(100);
                Task.Delay(100);
                Task.Delay(100);
                Task.Delay(100);
            }
        }
```

### API Usage

```csharp
    class Example
    {
        public async Task ExampleWithAwait()
        {
            await Task.Delay(100);
            await Task.Delay(100);
            await Task.Delay(100);
            await Task.Delay(100);
            await Task.Delay(100);
        }
        public async Task ExampleNotAwait()
        {
            await{
                Task.Delay(100);
                Task.Delay(100);
                Task.Delay(100);
                Task.Delay(100);
                Task.Delay(100);
            }
        }
    }
```

**Comment by teo-tsirpanis** [comment]
I find this syntax confusing and not very useful. It will come in value only when we have a series of `await`s immediately one after the other. And what if some of these `await`s return a value?

Regardless, this is a proposal to the C# language and should be proposed as a discussion item in https://github.com/dotnet/csharplang.

**Comment by Mr0N** [comment]
public async Task<string> Get()
        {
            await{
                var client = new HttpClient();
               return client.GetAsync("")
                    .Content.
                    ReadAsStringAsync();
            }
        }

**Comment by Mr0N** [comment]
https://github.com/dotnet/csharplang/discussions/6520
