### ISSUE TITLE
System.Text.Json code generation fails on recursive IReadOnlyDictionary

### ISSUE THREAD

**Issue by ejball** [dotnet/runtime#76802]
### Description

System.Text.Json code generation fails with `error CS1031: Type expected` if the serializable class has an `IReadOnlyDictionary` whose value type is that same serializable class.

### Reproduction Steps

Include these two classes in a C# library or console app that references System.Text.Json 6.0.6:
```csharp
public class Dto
{
    public IReadOnlyDictionary<string, Dto>? Data { get; set; }
}

[JsonSerializable(typeof(Dto))]
public partial class JsonContext : JsonSerializerContext
{
}
```

### Expected behavior

Compilation fails with: `...\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\JsonContext.IReadOnlyDictionaryStringDto.g.cs(27,128,27,129): error CS1031: Type expected`

That badly generated line of code looks like this: `ObjectCreator = () => new global::System.Collections.Generic.Dictionary<global::System.String, >(),`

### Actual behavior

It should succeed without error, as it does if `Dictionary` is used instead of `IReadOnlyDictionary`.

### Known Workarounds

Use `Dictionary` instead of `IReadOnlyDictionary`.

### Configuration

.NET 6.0.401 on Windows x64.

**Comment by eiriktsarpalis** [comment]
I can repro the issue -- fundamentally the issue stems from the fact that the source generator's "parser" component eagerly evaluates properties of the recursive type, even though it hasn't been fully populated yet:

https://github.com/dotnet/runtime/blob/957f76f4a701fbdde3ace704e01ff6d43ba7ec49/src/libraries/System.Text.Json/gen/JsonSourceGenerator.Parser.cs#L957-L960

I suspect that this issue has the potential to surface in other cases as well, so in fixing this we should carefully audit the parser code for any other instances where it could be reading from uninitialized metadata, perhaps by making such scenaria impossible by construction.
