### ISSUE TITLE
[bug] dotnet warns CA1416 even though TargetFramework is Windows

### ISSUE THREAD

**Issue by winstxnhdw** [dotnet/runtime#76824]
I get the following warning on running `dotnet publish`

```
 warning CA1416: This call site is reachable on all platforms. 'Image.FromStream(Stream)' is only supported on: 'windows'.
```

CA1416 usually disappears after setting the TargetFramework to `-windows`. However, for whatever reason, the `Image` class from the `System.Drawing` namespace still throws this warning. I believe this is not intended. I have bypassed this temporarily by adding the following preprocessors, before and after the class: `#pragma warning disable CA1416` and `#pragma warning restore CA1416`

Here's the .csproj file
```xml
  <PropertyGroup>

    <Configuration Condition=" '$(Configuration)' == 'Debug' ">Release</Configuration>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <PublishDir>../bin</PublishDir>
    <OutputType>winexe</OutputType>
    <ApplicationIcon>Resources/icon.ico</ApplicationIcon>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
    <PublishTrimmed>true</PublishTrimmed>
    <_SuppressWinFormsTrimError>true</_SuppressWinFormsTrimError>

  </PropertyGroup>

```

**Comment by JeremyKuhne** [comment]
@ViktorHofer I think the libraries team is much better equipped to investigate/understand this.

**Comment by ViktorHofer** [comment]
@buyaa-n and @jeffhandley any idea why the analyzer flags this call site even though the TargetFramework explicitly targets the Windows platform?

**Comment by jeffhandley** [comment]
This is most likely happening because of `<GenerateAssemblyInfo>false</>`. We've seen this before (comment by @buyaa-n): https://github.com/dotnet/roslyn-analyzers/issues/6543#issuecomment-1482047510

> By design the analyzer only check if `SupportedOSPlatform( "platform")` `SupportedOSPlatform( "platform")` attributes applied to the API/type/assembly. When a project targeting windows (`<TargetFramework>net7.0-windows</TargetFramework>`) MSBuild would add assembly level attribute `<Assembly: System.Runtime.Versioning.SupportedOSPlatform("windows")>` to the generated `AssemblyInfo.vb` file which then consumed by the analyzer. I see your project is disabled generating AssemblyInfo.vb: `<GenerateAssemblyInfo>false</GenerateAssemblyInfo>`. [MSBuild team suggest to not disable it](https://github.com/dotnet/sdk/issues/14502#issuecomment-828805675), anyway as you have disabled it the attribute could not be added automatically and so you need to add it manually anywhere in you project source, [read more](https://learn.microsoft.com/de-de/dotnet/fundamentals/code-analysis/quality-rules/ca1416#tfm-target-platforms)
> 
> > only writes a solution for C#, which doesn't work in vb Net
>

**Comment by ViktorHofer** [comment]
Thanks a lot Jeff. @winstxnhdw I hope that solves your question. Feel free to open a new issues if you need more help.
