### ISSUE TITLE
JSON source generator emits CS0612 warnings if serialized types use [Obsolete]

### ISSUE THREAD

**Issue by ejball** [dotnet/runtime#76829]
### Description

The JSON source generator should not trigger warnings when used with obsolete types. See [#62076](https://github.com/dotnet/runtime/issues/62076), which only fixed the bug when the `Obsolete` attribute includes a message.

### Reproduction Steps

Same as [#62076](https://github.com/dotnet/runtime/issues/62076), but with `[Obsolete]` instead of `[Obsolete("Use NewValue instead")]`.

### Expected behavior

No warnings.

### Actual behavior

`warning CS0612: 'MyObject.OldValue' is obsolete`

**Comment by layomia** [comment]
Up for grabs. Same fix as https://github.com/dotnet/runtime/pull/63496, but we're disabling `CS0612` warnings this time.

**Comment by jeffhandley** [comment]
Even more generally... what if our generated code triggers a diagnostic from a completely different diagnostic, even one that is user-defined and intentionally running over generated code? How would customers suppress any arbitrary diagnostic within our generated code? How would that be configured?

**Comment by eiriktsarpalis** [comment]
This could be added to the existing [`JsonSourceGenerationOptionsAttribute`](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonsourcegenerationoptionsattribute?view=net-6.0) via a new property:

```C#
public class JsonSourceGenerationOptionsAttribute
{
    public string[]? SuppressedWarnings { get; set; }
}
```

The source generator reads that attribute at compile time to configure source gen. Usage of the new property would look as follows:

```C#
[JsonSourceGenerationOptions(SuppressedWarnings = new string[] { "CS0612" } )]
[JsonSerializable(typeof(Foo))]
public partial class MyContext : JsonSerializerContext { }
```

**Comment by eiriktsarpalis** [comment]
Alternatively we could employ a convention where suppressions active in the partial class are applied to the extra generated code:
```C#
#pragma warning disable CS0618 // gets replicated in all generated instantiations of the partial class

[JsonSerializable(typeof(Foo))]
public partial class MyContext : JsonSerializerContext { }

#pragma warning restore CS0618
```

**Comment by Hellevar** [comment]
> This could be added to the existing [`JsonSourceGenerationOptionsAttribute`](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonsourcegenerationoptionsattribute?view=net-6.0) via a new property:
> 
> ```cs
> public class JsonSourceGenerationOptionsAttribute
> {
>     public string[]? SuppressedWarnings { get; set; }
> }
> ```
> 
> The source generator reads that attribute at compile time to configure source gen. Usage of the new property would look as follows:
> 
> ```cs
> [JsonSourceGenerationOptions(SuppressedWarnings = new string[] { "CS0612" } )]
> [JsonSerializable(typeof(Foo))]
> public partial class MyContext : JsonSerializerContext { }
> ```

Hi, @eiriktsarpalis !
Is it a final shape of expected API, so it can be implemented in a such way, or should it go through api review process as per https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md ?

**Comment by eiriktsarpalis** [comment]
@Hellevar this needs to go through API review before an implementation PR can be submitted.
