### ISSUE TITLE
Test failure in System.Transactions.Tests.OleTxTests.* tests

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#76836]
These tests are failing in various JitStress pipelines on Windows arm64:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=45833&view=ms.vss-test-web.build-test-results-tab&runId=920554&paneView=debug&resultId=191806

e.g.,
```
    System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments(volatileCount: 0) [FAIL]
      System.AggregateException : One or more errors occurred. (The operation is not valid for the state of the transaction.) (The following constructor parameters did not have matching fixture data: OleTxFixture fixture)
      ---- System.Transactions.TransactionException : The operation is not valid for the state of the transaction.
      -------- System.Transactions.TransactionManagerCommunicationException : Communication with the underlying transaction manager has failed.
      ------------ System.Runtime.InteropServices.COMException : The Transaction Manager is not available. (0x8004D01B)
      ---- The following constructor parameters did not have matching fixture data: OleTxFixture fixture
      Stack Trace:
        
        ----- Inner Stack Trace #1 (System.Transactions.TransactionException) -----
        /_/src/libraries/System.Transactions.Local/src/System/Transactions/TransactionState.cs(203,0): at System.Transactions.TransactionState.EnlistDurable(InternalTransaction tx, Guid resourceManagerIdentifier, IEnlistmentNotification enlistmentNotification, EnlistmentOptions enlistmentOptions, Transaction atomicTransaction)
        /_/src/libraries/System.Transactions.Local/src/System/Transactions/Transaction.cs(513,0): at System.Transactions.Transaction.EnlistDurable(Guid resourceManagerIdentifier, IEnlistmentNotification enlistmentNotification, EnlistmentOptions enlistmentOptions)
        /_/src/libraries/System.Transactions.Local/tests/OleTxTests.cs(569,0): at System.Transactions.Tests.OleTxTests.OleTxFixture.<>c.<.ctor>b__0_0()
        /_/src/libraries/System.Transactions.Local/tests/OleTxTests.cs(512,0): at System.Transactions.Tests.OleTxTests.Test(Action action)
        /_/src/libraries/System.Transactions.Local/tests/OleTxTests.cs(558,0): at System.Transactions.Tests.OleTxTests.OleTxFixture..ctor()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/ConstructorInvoker.cs(86,0): at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Transactions.Local/src/System/Transactions/Oletx/OletxTransactionManager.cs(610,0): at System.Transactions.Oletx.OletxTransactionManager.ProxyException(COMException comException)
        /_/src/libraries/System.Transactions.Local/src/System/Transactions/Oletx/DtcTransactionManager.cs(67,0): at System.Transactions.Oletx.DtcTransactionManager.Initialize()
        /_/src/libraries/System.Transactions.Local/src/System/Transactions/Oletx/DtcTransactionManager.cs(83,0): at System.Transactions.Oletx.DtcTransactionManager.get_ProxyShimFactory()
        /_/src/libraries/System.Transactions.Local/src/System/Transactions/Oletx/OletxTransactionManager.cs(481,0): at System.Transactions.Oletx.OletxTransactionManager.CreateTransaction(TransactionOptions properties)
        /_/src/libraries/System.Transactions.Local/src/System/Transactions/TransactionState.cs(2234,0): at System.Transactions.TransactionStatePromoted.EnterState(InternalTransaction tx)
        ----- Inner Stack Trace -----
           at System.Transactions.DtcProxyShim.DtcInterfaces.ITransactionImportWhereabouts.GetWhereaboutsSize(UInt32& pcbSize)
        /_/src/libraries/System.Transactions.Local/src/System/Transactions/DtcProxyShim/OletxHelper.cs(54,0): at System.Transactions.DtcProxyShim.OletxHelper.Retry(Action action)
        /_/src/libraries/System.Transactions.Local/src/System/Transactions/DtcProxyShim/DtcProxyShimFactory.cs(140,0): at System.Transactions.DtcProxyShim.DtcProxyShimFactory.ConnectToProxyCore(String nodeName, Guid resourceManagerIdentifier, Object managedIdentifier, Boolean& nodeNameMatches, Byte[]& whereabouts, ResourceManagerShim& resourceManagerShim)
        /_/src/libraries/System.Transactions.Local/src/System/Transactions/Oletx/DtcTransactionManager.cs(67,0): at System.Transactions.Oletx.DtcTransactionManager.Initialize()
        ----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
   
```

This looks like the same issue as https://github.com/dotnet/runtime/issues/75822, theoretically fixed by https://github.com/dotnet/runtime/pull/76310. However, it seems the fix isn't sufficient.

@roji Can you please take a look?

```json
{
  "ErrorMessage": "System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments",
  "BuildRetry": false
}
```

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[55940](https://dev.azure.com/dnceng-public/public/_build/results?buildId=55940)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/55940/logs/289)|dotnet/runtime#77103|
|[55707](https://dev.azure.com/dnceng-public/public/_build/results?buildId=55707)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/55707/logs/323)||
|[54855](https://dev.azure.com/dnceng-public/public/_build/results?buildId=54855)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/54855/logs/268)|dotnet/runtime#77103|
|[54385](https://dev.azure.com/dnceng-public/public/_build/results?buildId=54385)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/54385/logs/324)||
|[54100](https://dev.azure.com/dnceng-public/public/_build/results?buildId=54100)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/54100/logs/321)||
|[54038](https://dev.azure.com/dnceng-public/public/_build/results?buildId=54038)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/54038/logs/324)||
|[54017](https://dev.azure.com/dnceng-public/public/_build/results?buildId=54017)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/54017/logs/324)||
|[53798](https://dev.azure.com/dnceng-public/public/_build/results?buildId=53798)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/53798/logs/322)||
|[53768](https://dev.azure.com/dnceng-public/public/_build/results?buildId=53768)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/53768/logs/322)||
|[53591](https://dev.azure.com/dnceng-public/public/_build/results?buildId=53591)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/53591/logs/324)||
|[53566](https://dev.azure.com/dnceng-public/public/_build/results?buildId=53566)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/53566/logs/323)||
|[52661](https://dev.azure.com/dnceng-public/public/_build/results?buildId=52661)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/52661/logs/289)|dotnet/runtime#75140|
|[52628](https://dev.azure.com/dnceng-public/public/_build/results?buildId=52628)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/52628/logs/289)|dotnet/runtime#75634|
|[52442](https://dev.azure.com/dnceng-public/public/_build/results?buildId=52442)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/52442/logs/323)||
|[51029](https://dev.azure.com/dnceng-public/public/_build/results?buildId=51029)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/51029/logs/321)||
|[50934](https://dev.azure.com/dnceng-public/public/_build/results?buildId=50934)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/50934/logs/323)||
|[49280](https://dev.azure.com/dnceng-public/public/_build/results?buildId=49280)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/49280/logs/324)||
|[48224](https://dev.azure.com/dnceng-public/public/_build/results?buildId=48224)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/48224/logs/289)|dotnet/runtime#76883|
|[47531](https://dev.azure.com/dnceng-public/public/_build/results?buildId=47531)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/47531/logs/323)||
|[47404](https://dev.azure.com/dnceng-public/public/_build/results?buildId=47404)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/47404/logs/324)||
|[45833](https://dev.azure.com/dnceng-public/public/_build/results?buildId=45833)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/45833/logs/324)||

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[55940](https://dev.azure.com/dnceng-public/public/_build/results?buildId=55940)|dotnet/runtime|[System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments](https://dev.azure.com/dnceng-public/public/_build/results?buildId=55940&view=ms.vss-test-web.build-test-results-tab&runId=1148236&resultId=197530)|dotnet/runtime#77103|
|[55707](https://dev.azure.com/dnceng-public/public/_build/results?buildId=55707)|dotnet/runtime|[System.Transactions.Tests.OleTxTests.ImplicitDistributedTransactions_cannot_be_changed_after_being_read_as_true](https://dev.azure.com/dnceng-public/public/_build/results?buildId=55707&view=ms.vss-test-web.build-test-results-tab&runId=1140510&resultId=197531)||
|[54855](https://dev.azure.com/dnceng-public/public/_build/results?buildId=54855)|dotnet/runtime|[System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments](https://dev.azure.com/dnceng-public/public/_build/results?buildId=54855&view=ms.vss-test-web.build-test-results-tab&runId=1126484&resultId=192907)|dotnet/runtime#77103|
|[54385](https://dev.azure.com/dnceng-public/public/_build/results?buildId=54385)|dotnet/runtime|[System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments](https://dev.azure.com/dnceng-public/public/_build/results?buildId=54385&view=ms.vss-test-web.build-test-results-tab&runId=1113736&resultId=197529)||
|[54100](https://dev.azure.com/dnceng-public/public/_build/results?buildId=54100)|dotnet/runtime|[System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments](https://dev.azure.com/dnceng-public/public/_build/results?buildId=54100&view=ms.vss-test-web.build-test-results-tab&runId=1106644&resultId=197191)||
|[54038](https://dev.azure.com/dnceng-public/public/_build/results?buildId=54038)|dotnet/runtime|[System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments](https://dev.azure.com/dnceng-public/public/_build/results?buildId=54038&view=ms.vss-test-web.build-test-results-tab&runId=1105136&resultId=197526)||
|[54017](https://dev.azure.com/dnceng-public/public/_build/results?buildId=54017)|dotnet/runtime|[System.Transactions.Tests.OleTxTests.GetDtcTransaction](https://dev.azure.com/dnceng-public/public/_build/results?buildId=54017&view=ms.vss-test-web.build-test-results-tab&runId=1104576&resultId=197541)||
|[53798](https://dev.azure.com/dnceng-public/public/_build/results?buildId=53798)|dotnet/runtime|[System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments](https://dev.azure.com/dnceng-public/public/_build/results?buildId=53798&view=ms.vss-test-web.build-test-results-tab&runId=1100878&resultId=198524)||
|[53768](https://dev.azure.com/dnceng-public/public/_build/results?buildId=53768)|dotnet/runtime|[System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments](https://dev.azure.com/dnceng-public/public/_build/results?buildId=53768&view=ms.vss-test-web.build-test-results-tab&runId=1100028&resultId=197529)||
|[53591](https://dev.azure.com/dnceng-public/public/_build/results?buildId=53591)|dotnet/runtime|[System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments](https://dev.azure.com/dnceng-public/public/_build/results?buildId=53591&view=ms.vss-test-web.build-test-results-tab&runId=1095736&resultId=198524)||
|[53566](https://dev.azure.com/dnceng-public/public/_build/results?buildId=53566)|dotnet/runtime|[System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments](https://dev.azure.com/dnceng-public/public/_build/results?buildId=53566&view=ms.vss-test-web.build-test-results-tab&runId=1095008&resultId=197527)||
|[52661](https://dev.azure.com/dnceng-public/public/_build/results?buildId=52661)|dotnet/runtime|[System.Transactions.Tests.OleTxTests.GetDtcTransaction](https://dev.azure.com/dnceng-public/public/_build/results?buildId=52661&view=ms.vss-test-web.build-test-results-tab&runId=1076968&resultId=197541)|dotnet/runtime#75140|
|[52628](https://dev.azure.com/dnceng-public/public/_build/results?buildId=52628)|dotnet/runtime|[System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments](https://dev.azure.com/dnceng-public/public/_build/results?buildId=52628&view=ms.vss-test-web.build-test-results-tab&runId=1076218&resultId=197529)|dotnet/runtime#75634|
|[52442](https://dev.azure.com/dnceng-public/public/_build/results?buildId=52442)|dotnet/runtime|[System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments](https://dev.azure.com/dnceng-public/public/_build/results?buildId=52442&view=ms.vss-test-web.build-test-results-tab&runId=1069808&resultId=197526)||
|[51029](https://dev.azure.com/dnceng-public/public/_build/results?buildId=51029)|dotnet/runtime|[System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments](https://dev.azure.com/dnceng-public/public/_build/results?buildId=51029&view=ms.vss-test-web.build-test-results-tab&runId=1037698&resultId=208411)||
|[50934](https://dev.azure.com/dnceng-public/public/_build/results?buildId=50934)|dotnet/runtime|[System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments](https://dev.azure.com/dnceng-public/public/_build/results?buildId=50934&view=ms.vss-test-web.build-test-results-tab&runId=1034792&resultId=197515)||
|[49280](https://dev.azure.com/dnceng-public/public/_build/results?buildId=49280)|dotnet/runtime|[System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments](https://dev.azure.com/dnceng-public/public/_build/results?buildId=49280&view=ms.vss-test-web.build-test-results-tab&runId=991980&resultId=197510)||
|[48224](https://dev.azure.com/dnceng-public/public/_build/results?buildId=48224)|dotnet/runtime|[System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments](https://dev.azure.com/dnceng-public/public/_build/results?buildId=48224&view=ms.vss-test-web.build-test-results-tab&runId=975198&resultId=184277)|dotnet/runtime#76883|
|[47531](https://dev.azure.com/dnceng-public/public/_build/results?buildId=47531)|dotnet/runtime|[System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments](https://dev.azure.com/dnceng-public/public/_build/results?buildId=47531&view=ms.vss-test-web.build-test-results-tab&runId=956146&resultId=184930)||
|[47404](https://dev.azure.com/dnceng-public/public/_build/results?buildId=47404)|dotnet/runtime|[System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments](https://dev.azure.com/dnceng-public/public/_build/results?buildId=47404&view=ms.vss-test-web.build-test-results-tab&runId=953004&resultId=193349)||
|[45833](https://dev.azure.com/dnceng-public/public/_build/results?buildId=45833)|dotnet/runtime|[System.Transactions.Tests.OleTxTests.TransmitterPropagationToken](https://dev.azure.com/dnceng-public/public/_build/results?buildId=45833&view=ms.vss-test-web.build-test-results-tab&runId=918864&resultId=197145)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|4|34|42|

**Comment by BruceForstall** [comment]
More cases in another JitStress run:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=47404&view=ms.vss-test-web.build-test-results-tab

**Comment by roji** [comment]
Am trying to increase the timeout again in #76892, let's see if that makes it go away for good.

**Comment by BruceForstall** [comment]
There are still failures after #76892:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=49280&view=ms.vss-test-web.build-test-results-tab&runId=991986&resultId=197182&paneView=debug

**Comment by markples** [comment]
Failures are not limited to JITStress.  For example:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=51029&view=logs&j=f9affed7-8d82-5c58-eb09-b33088a0b629&t=841cba2d-9b8a-52d6-e2e0-be8034011045

https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-02e36dcb1adc47a284/System.Transactions.Local.Tests/1/console.94f94a03.log?helixlogtype=result

```
D:\h\w\B22D09C8\w\A6F5097B\e>set COMPlus 
COMPlus_TieredCompilation=1

D:\h\w\B22D09C8\w\A6F5097B\e>call RunTests.cmd --runtime-path D:\h\w\B22D09C8\p 
----- start Thu 10/13/2022  3:57:27.62 ===============  To repro directly: ===================================================== 
pushd D:\h\w\B22D09C8\w\A6F5097B\e\
"D:\h\w\B22D09C8\p\dotnet.exe" exec --runtimeconfig System.Transactions.Local.Tests.runtimeconfig.json --depsfile System.Transactions.Local.Tests.deps.json xunit.console.dll System.Transactions.Local.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================

D:\h\w\B22D09C8\w\A6F5097B\e>"D:\h\w\B22D09C8\p\dotnet.exe" exec --runtimeconfig System.Transactions.Local.Tests.runtimeconfig.json --depsfile System.Transactions.Local.Tests.deps.json xunit.console.dll System.Transactions.Local.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Transactions.Local.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Transactions.Local.Tests (found 137 of 149 test cases)
  Starting:    System.Transactions.Local.Tests (parallel test collections = on, max threads = 8)
    System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments(volatileCount: 0) [FAIL]
      System.AggregateException : One or more errors occurred. (The operation is not valid for the state of the transaction.) (The following constructor parameters did not have matching fixture data: OleTxFixture fixture)
```

**Comment by roji** [comment]
Thanks, I'll finish #77023 in the next few days.
