### ISSUE TITLE
Strange performance loss when using conditional Vector<T> and CopyBlockUnaligned

### ISSUE THREAD

**Issue by dn9090** [dotnet/runtime#76844]
### Description

I am trying to implement a memory replicate (or "fill") function and have encountered strange measurements when optimizing using `Vector<T>`.
The function takes a source byte array and replicates it `n` times in the destination array.
In the first step I used the `Unsafe.CopyBlockUnaligned` interface which emitted a `movsb`, which is not very efficient for small structures and data types. 
After other attempts I thought of filling a `Vector<byte>` with the source byte pattern (as often as possible) and using `Unsafe.CopyBlockUnaligned` only for large data types, since the measurement showed that the old version performs well there in comparison.
Now to the problem: as soon as I jump to the old version with an if-else condition for "big" datatypes (more than 32 byte), the measurements show a significant increase in runtime, even compared to the "old version".
Here are the simplified snippets of both functions from my code:
```CSharp
public static void CopyRepeat(byte* destination, byte* source, int byteCount, int count) {
  while(count-- > 0) {
    Unsafe.CopyBlockUnaligned(destination, source, (uint)byteCount);
    destination += byteCount;
  }
}

public static void VectorRepeat(byte* destination, byte* source, int byteCount, int count) {
  var dst = destination;
  var src = source;
  var numElements = Vector<byte>.Count / byteCount;

  if(count > numElements && numElements > 0) {	
    Unsafe.SkipInit(out Vector<byte> vector);
    var ptr = (byte*)&vector;
    var bytesInVector = numElements * byteCount;
								
    for(int i = 0; i < numElements; ++i) {
      Unsafe.CopyBlockUnaligned(ptr, src, (uint)byteCount);
      ptr += byteCount;
    }

    do
    {
      Unsafe.WriteUnaligned(dst, vector);
      count-= numElements;
      dst += bytesInVector;
    } while(count > numElements);
  }

  // CopyRepeat for big byte patterns
  while(count-- > 0)
  {
    Unsafe.CopyBlockUnaligned(dst, src, (uint)byteCount);
    dst += byteCount;
  }
}
```

### Configuration

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19044.2006 (21H2)
AMD Ryzen 5 5600X, 1 CPU, 12 logical and 6 physical cores
.NET SDK=6.0.202
  [Host]     : .NET 6.0.4 (6.0.422.16404), X64 RyuJIT
  DefaultJob : .NET 6.0.4 (6.0.422.16404), X64 RyuJIT

### Data
Measured with _4 (4 byte size like "int") and _64 (struct with 64 byte size), `Vector<byte>.Count` is 32.
Every method is called once with an increasing "count"-parameter.

[MemRepeatBench.zip](https://github.com/dotnet/runtime/files/9754146/MemRepeatBench.zip)

|                Method |  count |              Mean |          Error |         StdDev |
|---------------------- |------- |------------------:|---------------:|---------------:|
|          **CopyRepeat_4** |      **1** |         **0.6842 ns** |      **0.0017 ns** |      **0.0016 ns** |
|        VectorRepeat_4 |      1 |         3.6747 ns |      0.0006 ns |      0.0005 ns |
|         CopyRepeat_64 |      1 |         7.8997 ns |      0.0214 ns |      0.0201 ns |
|       VectorRepeat_64 |      1 |        10.8613 ns |      0.0238 ns |      0.0223 ns |
|          **CopyRepeat_4** |     **10** |         **2.7798 ns** |      **0.0008 ns** |      **0.0007 ns** |
|        VectorRepeat_4 |     10 |        18.9626 ns |      0.0017 ns |      0.0014 ns |
|         CopyRepeat_64 |     10 |        12.5428 ns |      0.0053 ns |      0.0050 ns |
|       VectorRepeat_64 |     10 |        31.6811 ns |      0.0139 ns |      0.0109 ns |
|          **CopyRepeat_4** |   **1000** |       **220.0730 ns** |      **0.0299 ns** |      **0.0250 ns** |
|        VectorRepeat_4 |   1000 |        60.1969 ns |      0.2313 ns |      0.2164 ns |
|         CopyRepeat_64 |   1000 |       879.7102 ns |      0.0957 ns |      0.0849 ns |
|       VectorRepeat_64 |   1000 |     2,830.5207 ns |      0.3888 ns |      0.3447 ns |
|          **CopyRepeat_4** | **100000** |    **21,585.6565 ns** |      **2.2372 ns** |      **1.7467 ns** |
|        VectorRepeat_4 | 100000 |     5,208.0257 ns |     19.8988 ns |     18.6134 ns |
|         CopyRepeat_64 | 100000 |    90,058.8802 ns |    219.0564 ns |    204.9055 ns |
|       VectorRepeat_64 | 100000 |   305,977.1940 ns |    743.0606 ns |    695.0594 ns |

VectorRepeat_64 should be equal to CopyRepeat_64 with just a little overhead for the if-else  because 64 byte do not fit in my Vector<byte> (on my machine) but the measurements show a massive increase in execution time.

### Analysis
Maybe I'm missing something simple, but I've been testing different variants for a few days and I always run into the same problem with the Vector<T> interface. Also a quick look at Sharplab showed that for example the vector registers are always used before the if-else test which I also find strange:
```
    L0000: push ebp
    L0001: mov ebp, esp
    L0003: push edi
    L0004: push esi
    L0005: push ebx
    L0006: sub esp, 0x30
    L0009: vzeroupper
    L000c: vxorps xmm4, xmm4, xmm4
    L0011: vmovdqu [ebp-0x34], xmm4
    L0017: vmovdqu [ebp-0x24], xmm4
    L001d: mov ebx, [ebp+8]
    L0020: mov [ebp-0x10], ecx
    L0023: mov [ebp-0x14], edx
    L0026: mov eax, 0x20
    L002b: mov esi, [ebp+0xc]
    L002e: xor edx, edx
    L0030: idiv esi
    L0032: cmp ebx, eax
    L0034: jle L00df
    L003a: test eax, eax
    L003c: jle L00d7
...
```
I would appreciate help, hopefully it's not a stupid mistake on my part.

**Comment by EgorBo** [comment]
> VectorRepeat_64 should be equal to CopyRepeat_64 with just a little overhead for the if-else because 64 byte do not fit in my Vector (on my machine) but the measurements show a massive increase in execution time.

I don't see how it should not step into that if-else, it seems to always use that path so you compare different things

> Vector registers are always used before the if-else test which I also find strange:

That is expected, it zeroes memory for locals.

**Comment by dn9090** [comment]
> I don't see how it should not step into that if-else, it seems to always use that path so you compare different things.

My byte pattern is 64 byte in length so `Vector<byte>.Count / byteCount` is 0. And in all my tests the if-else is never entered. So just the `CopyBlockUnaligned` loop is executed (as expected) but it has a much worse execution time than just running the "old version" above which contains only the loop. See my benchmark code below.

> That is expected, it zeroes memory for locals.

For locals in general? Because I thought `Unsafe.SkipInit` gets rid of the initialization.

```CSharp
[Arguments(1)]
[Arguments(10)]
[Arguments(1_000)]
[Arguments(100_000)]
[Benchmark]
public void VectorRepeat_4(int count) {
  fixed(int* ptr = intArray) {
    var value = 10101010;
    VectorRepeat((byte*)ptr, (byte*)&value, sizeof(int), count);
  }
}

[Arguments(1)]
[Arguments(10)]
[Arguments(1_000)]
[Arguments(100_000)]
[Benchmark]
public void VectorRepeat_64(int count) {
  fixed(Byte64* ptr = byte64Array) {
    var value = new Byte64 { a = 1000, h = -1000 };
    VectorRepeat((byte*)ptr, (byte*)&value, sizeof(Byte64), count);
  }
}
```

```CSharp
public static void VectorRepeat(byte* destination, byte* source, int byteCount, int count) {
  // ...
  var numElements = Vector<byte>.Count / byteCount; // = 8 for byteCount = 4
                                                    // = 0 for byteCount = 64

  // Skip vector copy when byteCount is too large to fit in a Vector<byte>,
  // this is the case when numElements equals 0.
  if(count > numElements && numElements > 0) {	
    Unsafe.SkipInit(out Vector<byte> vector);
    // ...
  }

  // The same CopyBlockUnaligned loop as in the old version.
  while(count-- > 0)
  {
    Unsafe.CopyBlockUnaligned(dst, src, (uint)byteCount);
    dst += byteCount;
  }
}
```

**Comment by dn9090** [comment]
Updated my issue (see [MemRepeatBench.zip](https://github.com/dotnet/runtime/files/9754146/MemRepeatBench.zip))

**Comment by EgorBo** [comment]
Thanks, I was able to repro the results, the problem is fixed if you enable `DOTNET_TieredPGO=1` so the unused branch will be emitted in the cold section. You can also re-order blocks by hands to make your hot loop first.

**Comment by dn9090** [comment]
Thanks for the hint, I will try my best.

**Comment by dn9090** [comment]
Seems that just calling the "old version" with the modified count and destination fixes the issue, no clue why:
```CSharp
public static void VectorRepeat(byte* destination, byte* source, int byteCount, int count) {
  var dst = destination;
  var src = source;
  var numElements = Vector<byte>.Count / byteCount;
  
  if(numElements > 0 && count > numElements) {
    Unsafe.SkipInit(out Vector<byte> vector);
    var ptr = (byte*)&vector;
    var bytesInVector = numElements * byteCount;
    count += bytesInVector;

    for(int i = 0; i < numElements; ++i) {
      Unsafe.CopyBlockUnaligned(ptr, src, (uint)byteCount);
      ptr += byteCount;
    }

    do
    {
      Unsafe.WriteUnaligned(dst, vector);
      count -= numElements;
      dst += bytesInVector;
    } while(count > numElements);
  }

  CopyRepeat(dst, src, byteCount, count);
}
```
|          Method |  count |           Mean |         Error |        StdDev |
|---------------- |------- |---------------:|--------------:|--------------:|
|    **CopyRepeat_4** |      **1** |      **0.6630 ns** |     **0.0018 ns** |     **0.0015 ns** |
|  VectorRepeat_4 |      1 |      1.2530 ns |     0.0008 ns |     0.0007 ns |
|   CopyRepeat_64 |      1 |      7.7393 ns |     0.0142 ns |     0.0133 ns |
| VectorRepeat_64 |      1 |      7.8994 ns |     0.0014 ns |     0.0014 ns |
|    **CopyRepeat_4** |     **10** |      **2.7839 ns** |     **0.0014 ns** |     **0.0012 ns** |
|  VectorRepeat_4 |     10 |      6.8442 ns |     0.0013 ns |     0.0012 ns |
|   CopyRepeat_64 |     10 |     13.1052 ns |     0.0077 ns |     0.0060 ns |
| VectorRepeat_64 |     10 |     13.8721 ns |     0.0077 ns |     0.0072 ns |
|    **CopyRepeat_4** |   **1000** |    **220.4521 ns** |     **0.3309 ns** |     **0.2933 ns** |
|  VectorRepeat_4 |   1000 |     42.1297 ns |     0.0180 ns |     0.0168 ns |
|   CopyRepeat_64 |   1000 |    891.4646 ns |     0.6535 ns |     0.5793 ns |
| VectorRepeat_64 |   1000 |    878.6282 ns |     0.0834 ns |     0.0781 ns |
