### ISSUE TITLE
Test failure: GC\\API\\Frozen\\Frozen\\Frozen.cmd

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#76856]
win-arm64 random JitStress

```
set COMPlus_TieredCompilation=0
set COMPlus_JitStress=1cf

    GC\API\Frozen\Frozen\Frozen.cmd [FAIL]
      Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
         at HelloFrozenSegment.Program.Main(String[] args)
      
      Return code:      1
```

https://dev.azure.com/dnceng-public/public/_build/results?buildId=46805&view=ms.vss-test-web.build-test-results-tab&runId=941878&resultId=109785&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

@dotnet/jit-contrib

**Comment by jkotas** [comment]
cc @EgorBo

**Comment by EgorBo** [comment]
Smells like a gc hole in the test itself: 
https://github.com/dotnet/runtime/blob/main/src/tests/GC/API/Frozen/Frozen.cs#L141-L142
