### ISSUE TITLE
Assert failure: (last_plug_size & (sizeof(PTR_PTR) - 1)) == 0

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#76858]
Config:
`coreclr Linux arm Checked no_tiered_compilation @ (Alpine.314.Arm32.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm32v7-20210910135806-8a6f4f3`

Test: GC/Scenarios/muldimjagary/muldimjagary/muldimjagary.sh

https://dev.azure.com/dnceng-public/public/_build/results?buildId=46801&view=ms.vss-test-web.build-test-results-tab&runId=941472&paneView=debug&resultId=110112

```
    GC/Scenarios/muldimjagary/muldimjagary/muldimjagary.sh [FAIL]
      
      Assert failure(PID 5763 [0x00001683], Thread: 5763 [0x1683]): (last_plug_size & (sizeof(PTR_PTR) - 1)) == 0
          File: /__w/1/s/src/coreclr/gc/gc.cpp Line: 33973
          Image: /root/helix/work/correlation/corerun
      
      [createdump] waitpid() returned successfully (wstatus 00000000)
      /root/helix/work/workitem/e/GC/Scenarios/muldimjagary/muldimjagary/muldimjagary.sh: line 412:  5763 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      
      Return code:      1
      Raw output file:      /root/helix/work/workitem/uploads/Reports/GC.Scenarios/muldimjagary/muldimjagary/muldimjagary.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false muldimjagary.dll ''
      Test should return with ExitCode 100 ...
      [createdump] Gathering state for process 5763 corerun
      [createdump] Crashing thread 00001683 signal 00000006
      [createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.5763.dmp
      [createdump] Written 85061632 bytes (20767 pages) to core file
      [createdump] Target process is alive
      [createdump] Dump successfully written in 2058ms
      Expected: 100
      Actual: 134
      END EXECUTION - FAILED
```

**Comment by Maoni0** [comment]
how often are these tests run in this config? it's surprising that you are suddenly seeing these failures considering they are in 32-bit so not even using regions. 

where can get the symbols? I see dumps in the artifacts. if only we could add a link to the runtime symbols...

**Comment by BruceForstall** [comment]
This is the normal outerloop job, which is scheduled to run 3 times per day. Unless something has recently changed, presumably this particular OS configuration is run every time.

I don't know anything about the dumps. Maybe this helps: https://github.com/dotnet/diagnostics/blob/main/documentation/debugging-coredump.md

**Comment by jkotas** [comment]
You can download the dumps by running `runfo get-helix-payload -j 7c6d715c-ac95-41eb-8c4d-dd51d64ade58 -w PayloadGroup0 -o c:\bone_yard\runtime76858`

**Comment by Maoni0** [comment]
ahh the runfo command, I forgot about it. thanks @jkotas! 

I still maintain it would be very helpful to those of us on the runtime team to just have a link to (or simply include it in the artifacts) the runtime symbols - coreclr.pdb/clrjit.pdb, instead of having to use this command to download stuff. we are already saving dumps which are usually way bigger anyway.

**Comment by mangod9** [comment]
perhaps this was enabled as part of issues.target cleanup? @eduardo-vp as fyi, looks similar to other arm failure.

**Comment by trylek** [comment]
As the last and only known repro is seven months old, I believe this is no longer actually blocking outerloop.

**Comment by mangod9** [comment]
closing for now since this is a few months old.
