### ISSUE TITLE
[API Proposal]: A ALC must be unload.

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/runtime#76864]
### Background and motivation

The metadata in AssemblyLoadContext is referenced by other class libraries and can't be unloaded. In a frequent dynamic compilation scenario, plug-in scenario, it will take up system resources and can't be released. I hope a new API will help ALC force uninstall, although this will lead to exceptions in the operations that occupy it. When to unload by developers and GC.

Or

Added the ALC global unload event, which is triggered when any ALC uses the unload function.
Force class library developers to implement the uninstall interface!

If my description is not clear, please remind me to correct it.

### API Proposal

```csharp
var domain = MyAssemblyLoadContext("fooDomain");

//Force uninstall alc
AssemblyLoadContext.Unload( domain );
AssemblyLoadContext.Unload( assembly.Domain );
AssemblyLoadContext.Unload( type.Domain );
```

OR

```csharp
var domain = MyAssemblyLoadContext("fooDomain");
domain.Unload();
```

### API Usage

Option 1:

Forced unloading

```csharp
var domain = MyAssemblyLoadContext("fooDomain");

//Force unload alc
AssemblyLoadContext.Unload( domain );
AssemblyLoadContext.Unload( assembly.Domain );
AssemblyLoadContext.Unload( type.Domain );
``` 

<br/>  

Option 2:

Unload constrain

#### make a  a.dll
```csharp
public class MySqlUnloadAlc : IAssemblyLoadContextUnload
{
    public void Unload (AssemblyLoadContext alc)
    { 
         var asms = alc.GetAssemblys();
         foreach(var asm in asms)
         {
            foreach(var type = asm.GetTypes())
            {
                // remove metadata reference
                LibraryTypeCache.Dict.TryRemove(type);
                LibraryTypeCache.Event.Clear();
                LibraryTypeCache.List.TryRemove(type);
                LibraryTypeCache.Func = null;
                LibraryRebuildFunction();
            }
        }
   }
}
```

#### use a.dll in alc

```csharp
var domain = MyAssemblyLoadContext("fooDomain");

//load dll and register IAssemblyLoadContextUnload Interface
domain.Load("xxx/a.dll");

domain.Unload();
```

### Alternative Designs

ALC adds an event. Force library developers to bind plug-in unload events so that they can help remove references in plug-in scenarios. The class library developer provides an extension package to help users uninstall ALC.
`AssemblyLoadContext.GlobalUnloadEvent + = (AssemblyLoadContext alc) = > {/ *... remove reference...*/}`

### Risks

There may be many unknown problems, such as Dictionary < Type,string >. Type is generated by dynamic compilation. If the domain in which Type resides is unloaded, a null key will appear in the dictionary.

**Comment by teo-tsirpanis** [comment]
Forceful unloading of assembly load contexts is [an explicit non-goal of the unloadability design](https://github.com/dotnet/runtime/blob/main/docs/design/features/unloadability.md#non-goals). Supporting it would mean supporting `Thread.Abort` which is also not supported and a fundamentally unreliable API.

If you want your code to be unloadable, it unfortunately has to be designed to support unloadability. There is no other way.

**Comment by huoyaoyuan** [comment]
> Officially create an interface or solution for developers to implement the unload function in their class libraries.

This is still impractical. A reference to an object in the assembly can be stored in unexpected location.

If you have control of the whole application, diagnostic tool that helps finding such reference should be useful.

**Comment by teo-tsirpanis** [comment]
@NMSAzulX there is this already. A library can write `AssemblyLoadContext.GetAssemblyLoadContext(typeof(C).Assembly)!.Unloading += _ => {};` to register an event when its assembly load context is going to be unloaded.

**Comment by huoyaoyuan** [comment]
> Is there an API that allows developers to find all references to an object?

I'm afraid not, and it can be hard to represent "`IEnumerable<ref T>`".

**Comment by Clockwork-Muse** [comment]
And even if there was, an ALC is almost certainly going to be accessed from multiple threads, so any method return would be immediately out-of-date anyways.

**Comment by NMSAzulX** [comment]
@huoyaoyuan  @Clockwork-Muse  Thanks.
