### ISSUE TITLE
Consider expanding number formatting cache to larger values

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#76888]
Several releases ago, we added to number formatting a cache of strings for the values 0 through 9:
https://github.com/dotnet/runtime/blob/20d4e309ec4f081e4b1d47a8f937abfbb763a4d4/src/libraries/System.Private.CoreLib/src/System/Number.Formatting.cs#L269
Since with the default format non-negative values aren't impacted by culture, this cache is used for all numerical types for all single digit values as part of `value.ToString()`.  We should consider expanding the cache to larger values, e.g. up to 300 to account for other frequently used values on success paths, like HTTP success status codes.

The upside to this is significantly less allocation as well as better throughput for formatting such values.  The primary downside is increased memory costs for a larger table, e.g. caching all values 0 through 299 would add ~12K in allocated objects (caching all through 1000 would add ~39K).  If the full cost is deemed prohibitive, it could be made lazy, such that at the expense of an additional null check on each access, we could populate only the strings actually used.  We could also clear the table under certain conditions if it was deemed an issue. And we could choose to not include the table in corelib builds where we expect memory to be at a premium.

cc: @marklio

**Comment by jkotas** [comment]
> caching all through 1000 would add ~39K

This math looks off. You need an array holding the string objects (1000 * pointer size) = 80kB on 64-bit. And you need to account for minimal object size (1000 * 24) = 240kB on 64-bit CoreCLR. The total size of this cache would be 320kB.

> If the full cost is deemed prohibitive, it could be made lazy

Yes, I think it should be definitely lazy.

**Comment by stephentoub** [comment]
> (1000 * pointer size) = 80kB

1000 * 8 bytes is 8,000, not 80,000.  Have I misunderstood?

This wasn't actually based on math but rather on:
```C#
while (true)
{
    long m = GC.GetAllocatedBytesForCurrentThread();
    string[] values = new string[1000];
    for (int i = 0; i < values.Length; i++) values[i] = i.ToString();
    Console.WriteLine((GC.GetAllocatedBytesForCurrentThread() - m) / 1024);
}
```

**Comment by jkotas** [comment]
You are right, I got an extra zero somewhere. It is ~39k as you have said.

**Comment by stephentoub** [comment]
I think it would end up looking something like this:
https://github.com/dotnet/runtime/compare/main...stephentoub:runtime:smallnumberscache
potentially with some tweaks to avoid accessing the static when it won't be used.

```C#
[Params(1, 12, 123, 1234, 12345)]
public int Value { get; set; }

[Benchmark]
public string ValueToString() => Value.ToString();
```

|        Method |         Toolchain | Value |      Mean | Ratio | Allocated | Alloc Ratio |
|-------------- |------------------ |------ |----------:|------:|----------:|------------:|
| ValueToString | \main\corerun.exe |     1 |  1.355 ns |  1.00 |         - |          NA |
| ValueToString |   \pr\corerun.exe |     1 |  3.367 ns |  2.49 |         - |          NA |
|               |                   |       |           |       |           |             |
| ValueToString | \main\corerun.exe |    12 |  8.940 ns |  1.00 |      32 B |        1.00 |
| ValueToString |   \pr\corerun.exe |    12 |  3.317 ns |  0.37 |         - |        0.00 |
|               |                   |       |           |       |           |             |
| ValueToString | \main\corerun.exe |   123 |  9.522 ns |  1.00 |      32 B |        1.00 |
| ValueToString |   \pr\corerun.exe |   123 |  3.323 ns |  0.35 |         - |        0.00 |
|               |                   |       |           |       |           |             |
| ValueToString | \main\corerun.exe |  1234 | 10.012 ns |  1.00 |      32 B |        1.00 |
| ValueToString |   \pr\corerun.exe |  1234 | 10.375 ns |  1.04 |      32 B |        1.00 |
|               |                   |       |           |       |           |             |
| ValueToString | \main\corerun.exe | 12345 | 10.655 ns |  1.00 |      32 B |        1.00 |
| ValueToString |   \pr\corerun.exe | 12345 | 11.213 ns |  1.05 |      32 B |        1.00 |

**Comment by EgorBo** [comment]
👍 
![image](https://user-images.githubusercontent.com/523221/195214867-39a4cdc2-7e0f-4a1b-b145-f95cc2182b8e.png)

from a memory dump of bingsnr (string objects - number of them in the current snapshot). But I can't say if they come from this formatting.

**Comment by stephentoub** [comment]
@EgorBo shared with me the dump he was looking at, and I did some querying of it using clrmd.

It has 8.7M strings, of which 177K are parseable with `long.TryParse(s, NumberStyles.None, CultureInfo.InvariantCulture, out long value)`, and of those, ~25% are < 300.  Of the 5.2MB consumed by all the number strings, ~1.2MB are consumed by these strings for values <300.

If I increase the threshold from 300 to 1000, that ~25% goes up to ~40%.

**Comment by geeknoid** [comment]
Can the size of the cache be determined at startup based on some environmental state?

Clearly, the cache memory is a trivial cost for a service application so in that environment it is warranted to make it large. But for constrained environments, the extra memory may be problematic.
