### ISSUE TITLE
[Perf] Regressions in System.Collections.Tests.Perf_PriorityQueue<Int32, Int32>

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#76887]
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [fb5f07f9c580bdcd5d0726d1391c2a52a01030f8](https://github.com/dotnet/runtime/commit/fb5f07f9c580bdcd5d0726d1391c2a52a01030f8)
Compare | [ae4dc9cef942258098164beae987589c9d569215](https://github.com/dotnet/runtime/commit/ae4dc9cef942258098164beae987589c9d569215)
Diff | [Diff](https://github.com/dotnet/runtime/compare/fb5f07f9c580bdcd5d0726d1391c2a52a01030f8...ae4dc9cef942258098164beae987589c9d569215)

### Regressions in System.Collections.Tests.Perf_PriorityQueue&lt;Int32, Int32&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[K_Max_Elements - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04/System.Collections.Tests.Perf_PriorityQueue(Int32%2c%20Int32).K_Max_Elements(Size%3a%20100).html>) | 419.83 ns | 442.70 ns | 1.05 | 0.00 | False | | |
[HeapSort - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04/System.Collections.Tests.Perf_PriorityQueue(Int32%2c%20Int32).HeapSort(Size%3a%201000).html>) | 52.78 μs | 55.83 μs | 1.06 | 0.03 | False | | |
[HeapSort - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04/System.Collections.Tests.Perf_PriorityQueue(Int32%2c%20Int32).HeapSort(Size%3a%20100).html>) | 1.70 μs | 1.87 μs | 1.10 | 0.01 | False | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/10_11_2022/refs/heads/main_x64_ubuntu%2018.04_Regression/System.Collections.Tests.Perf_PriorityQueue(Int32,%20Int32)_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/10_11_2022/refs/heads/main_x64_ubuntu%2018.04_Regression/System.Collections.Tests.Perf_PriorityQueue(Int32,%20Int32)_2.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/10_11_2022/refs/heads/main_x64_ubuntu%2018.04_Regression/System.Collections.Tests.Perf_PriorityQueue(Int32,%20Int32)_3.png>)
[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/10_11_2022/refs/heads/main_x64_ubuntu%2018.04_Regression/System.Collections.Tests.Perf_PriorityQueue(Int32,%20Int32).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net6.0 --filter 'System.Collections.Tests.Perf_PriorityQueue&lt;Int32, Int32&gt;*'
```

#### Regressions

* [[Perf] Windows/x86: 24 Regressions on 10/2/2022 4:42:49 PM](<https://github.com/DrewScoggins/performance-2/issues/8283>)
* [[Perf] Alpine/x64: 21 Regressions on 10/2/2022 4:42:49 PM](<https://github.com/DrewScoggins/performance-2/issues/8277>)
* [[Perf] Linux/x64: 37 Regressions on 10/2/2022 4:42:49 PM](<https://github.com/DrewScoggins/performance-2/issues/8239>)
#### Improvements
* [[Perf] Linux/x64: 20 Improvements on 10/2/2022 4:42:49 PM](<https://github.com/DrewScoggins/performance-2/issues/8245>)

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-f5fa79af-e7e5-4efe-89b6-6118e2fadd52b3a1c1499934728bd/2b5e50da-82f0-4817-a9a2-a5b7609d3112.zip?sv=2021-08-06&se=2022-11-01T08%3A10%3A20Z&sr=c&sp=rl&sig=OfzKp1vlFXQRK62CDgKSjIo2WLFj%2BDUS%2Ba7QpObrFek%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-5b1eb47a-40a6-42c5-8038-dd05c0f2b5d927aa931db5f42c388/279714a7-f165-4218-b4bb-bd103e9f228d.zip?sv=2021-08-06&se=2022-11-02T00%3A59%3A02Z&sr=c&sp=rl&sig=36550zskUoHWo%2BTTqycjYNUOXRvzQX2yZuIuR26yvmw%3D>)
### Edge Detector Info

[Collection Data](<https://pvscmdupload.blob.core.windows.net/autofilereport/reports/10_11_2022/refs/heads/main_x64_ubuntu 18.04/System.Collections.Tests.Perf_PriorityQueue-Int32, Int32-.HeapSort(Size- 100).txt?sv=2018-03-28&sr=c&sig=1gp3y5y988UD3%2BZvrzEehBIVYrmWJiqJPm3ln6HFgL4%3D&se=2022-11-09T00%3A13%3A03Z&sp=racwdl>)
#### System.Collections.Tests.Perf_PriorityQueue&lt;Int32, Int32&gt;.K_Max_Elements(Size: 100)

```log

```
### Description of detection logic
```IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionWindowed: Marked as regression because 442.70104704328384 > 440.7245315214986.
IsChangePoint: Marked as a change because one of 10/2/2022 4:08:26 PM, 10/11/2022 2:16:14 AM falls between 10/2/2022 5:38:34 AM and 10/11/2022 2:16:14 AM.
IsRegressionStdDev: Marked as regression because -43.82269926441918 (T) = (0 -443.35472183754894) / Math.Sqrt((1.4099182202912361 / (18)) + (7.7759195658518 / (35))) is less than -2.007583770314729 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (18) + (35) - 2, .025) and -0.05728774395496787 = (419.3321301343226 - 443.35472183754894) / 419.3321301343226 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked not as a regression because Edge Detector said so.
IsChangeEdgeDetector: Marked not as a regression because Edge Detector said so.

```#### System.Collections.Tests.Perf_PriorityQueue&lt;Int32, Int32&gt;.HeapSort(Size: 1000)

```log

```
### Description of detection logic
```IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionWindowed: Marked as regression because 55.826369119802784 > 55.34462434146614.
IsChangePoint: Marked as a change because one of 9/3/2022 11:44:47 AM, 9/23/2022 1:16:35 AM, 10/2/2022 5:38:34 AM, 10/11/2022 2:16:14 AM falls between 10/2/2022 5:38:34 AM and 10/11/2022 2:16:14 AM.
IsRegressionStdDev: Marked as regression because -29.270366449344046 (T) = (0 -55822.14208501988) / Math.Sqrt((35281.66684117917 / (14)) + (315056.12359184 / (35))) is less than -2.011740513728388 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (14) + (35) - 2, .025) and -0.05964015689879864 = (52680.28181226355 - 55822.14208501988) / 52680.28181226355 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked not as a regression because Edge Detector said so.
IsChangeEdgeDetector: Marked not as a regression because Edge Detector said so.

```#### System.Collections.Tests.Perf_PriorityQueue&lt;Int32, Int32&gt;.HeapSort(Size: 100)

```log

```
### Description of detection logic
```IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionWindowed: Marked as regression because 1.866617259837963 > 1.7848844771642938.
IsChangePoint: Marked as a change because one of 10/2/2022 5:38:34 AM, 10/11/2022 2:16:14 AM falls between 10/2/2022 5:38:34 AM and 10/11/2022 2:16:14 AM.
IsRegressionStdDev: Marked as regression because -19.536857311570802 (T) = (0 -1858.4396812229638) / Math.Sqrt((645.542544125046 / (16)) + (408.03389280808665 / (35))) is less than -2.0095752371279447 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (16) + (35) - 2, .025) and -0.08202864547093051 = (1717.5512764859534 - 1858.4396812229638) / 1717.5512764859534 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked not as a regression because Edge Detector said so.
IsChangeEdgeDetector: Marked not as a regression because Edge Detector said so.

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by DrewScoggins** [comment]
Seems related to https://github.com/dotnet/runtime/pull/76439

**Comment by JulieLeeMSFT** [comment]
> Seems related to #76155

@SingleAccretion could you take a look?

**Comment by JulieLeeMSFT** [comment]
Hi @SingleAccretion, 8/14 is RC1 code snap and 0 bug date. Do you plan to look into [these 5 issues ](https://github.com/dotnet/runtime/issues?q=label%3Aarea-codegen-coreclr+is%3Aissue+is%3Aopen+milestone%3A8.0.0+assignee%3Asingleaccretion)assigned to you or do you need help from our team?

**Comment by SingleAccretion** [comment]
> Do you plan to look into [these 5 issues ](https://github.com/dotnet/runtime/issues?q=label%3Aarea-codegen-coreclr+is%3Aissue+is%3Aopen+milestone%3A8.0.0+assignee%3Asingleaccretion)assigned to you or do you need help from our team?

I will be doing that, though not sure if I will be get to them all.

**Comment by JulieLeeMSFT** [comment]
> > Do you plan to look into [these 5 issues ](https://github.com/dotnet/runtime/issues?q=label%3Aarea-codegen-coreclr+is%3Aissue+is%3Aopen+milestone%3A8.0.0+assignee%3Asingleaccretion)assigned to you or do you need help from our team?
> 
> I will be doing that, though not sure if I will be get to them all.

Thanks @SingleAccretion. I talked to @AndyAyersMS and he will help. Please reassign to Andy for the items that you want him to look into by early this week.

**Comment by AndyAyersMS** [comment]
The first was "fixed" by dynamic PGO:

![newplot - 2023-07-31T115752 166](https://github.com/dotnet/runtime/assets/10121823/e2868fab-87d5-432d-b35e-eba672d25014)

This next one is just noisy; the June 8 regression is evidently https://github.com/dotnet/runtime/pull/87115 and the June 29th is likely https://github.com/dotnet/runtime/pull/88090

![newplot - 2023-07-31T115849 746](https://github.com/dotnet/runtime/assets/10121823/f71123d2-8a87-4c50-b497-ee0c352da077)

The last was also "fixed" by dynamic PGO:

![newplot - 2023-07-31T120032 761](https://github.com/dotnet/runtime/assets/10121823/4f3e54c0-bb97-4bf4-89c6-829a5c79e279)

**Comment by DrewScoggins** [comment]
We are still seeing a regression from this change on Windows x86.

https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x86_Windows%2010.0.18362%2fSystem.Collections.Tests.Perf_PriorityQueue(Int32%2c%20Int32).HeapSort(Size%3a%20100).html
