### ISSUE TITLE
Decimal calculations not rounding to even in all cases

### ISSUE THREAD

**Issue by gregli-msft** [dotnet/runtime#76909]
### Description

My understanding is that the Decimal data type should round to even.  And mostly it does, but about 10% of the time it does not in my measurements.  If round to even isn't the law of the land, can you tell me more about what rules are being used?  This could easily be my misunderstanding.

Examples:

`-31279.6023354305 / 0.0651005386212378 `
results in (approximately):
`-480481.467556185943572750013585765...`
Decimal is rounding toward odd:
`-480481.46755618594357275001359`

`96270.981103308 - 0.0000000000328805555276948`
results in (exactly):
`96270.9811033079671194444723052`
Decimal is rounding toward odd:
`96270.98110330796711944447231`

`97090.2396352451 * 0.00000360555626154205`
results in (exactly):
`0.350064321451476090968855706455`
Decimal is rounding toward odd:
`0.3500643214514760909688557065`

`0.0000000887090946029449 + -1793621593.05886`
results in (exactly):
`-1793621593.0588599112909053970551`
Decimal is rounding toward odd:
`-1793621593.0588599112909053971`

### Reproduction Steps

using System;
					
public class Program
{
	public static void Main()
	{
		Console.WriteLine( -31279.6023354305M / 0.0651005386212378M );
	}
}

### Expected behavior

`-480481.46755618594357275001358`

### Actual behavior

`-480481.46755618594357275001359`

### Regression?

Unknown

### Configuration

.NET 4.7.2 (.NET Fiddle)
ASP.NET 4.8

**Comment by Fabi** [comment]
That is mathematically correct if rounded from the last decimal to the one you round to. You round up at 5 so…

**Comment by gregli-msft** [comment]
Yes, I just realized my mistake.  Thanks for confirming.
