### ISSUE TITLE
Need help identifying types which need Custom Converter to be implemented when using System.Text.Json 

### ISSUE THREAD

**Issue by snjosephms** [dotnet/runtime#76914]
We are migrating our codebase from Newtonsoft to System.Text.Json. This codebase is used for serialization and de-serialization of Azure Service Bus messages and uses .Net Framework 4.6.2
We found that deserialization of certain types is leading to polymorphic deserialization issues and hence we need to identify the types for which Custom Converters need to be created. 
Since there are 140+ types to be analyzed to see if any scenario would cause polymorphic deserialization issue, we are looking for a **static analysis tool** which can help identify the types which need Custom Converter to be implemented when using System.Text.Json 

Can anyone share a tool which can be used in this regard?

**Comment by eiriktsarpalis** [comment]
Generally speaking, I don't think there could be a tool that provides recommendations on if and how the serialization contract of a type should be customized. System.Text.Json will attempt to produce a default contract for every type using a number of conventions. These defaults work for most applications, but where and how they fail is highly dependent on the requirements of the particular domain.

> We found that deserialization of certain types is leading to polymorphic deserialization issues and hence we need to identify the types for which Custom Converters need to be created.

It would help if you could share an example of such a type and the issue in question. We can provide relevant recommendations depending on that information. FWIW the upcoming release of System.Text.Json comes with support for a restricted mode of [polymorphic serialization](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/polymorphism?pivots=dotnet-7-0).

**Comment by snjosephms** [comment]
Thanks for the revert. Here is an example of the code snippet where we found issues due to polymorphic deserialization.  The below example was **one** instance where we identified issues due to Polymorphic deserialization. To handle this we will be creating a Custom Converter for the ContextItem type.

We are now trying to identify all other types for which deserialization will fail due to polymorphism. Since there are 140+ Service Bus message types we are looking at, it is not feasible to do this manually by looking at the code structure and hence we are trying to identify static analysis tools for this. 

 

    public class AServiceBusMessage
    {
        public List<ContextItem> contextItems {  get; set; }
    }

    public class ContextItem
    {
        public virtual object GetValue()
        {
            return null;
        }
        public Guid? Id { get; private set; }
    }

    public class StringContextItem: ContextItem
    {
        public string Value { get; set; }

        public override object GetValue()
        {
            return this.Value;
        }
    }

    public class IntegerContextItem : ContextItem
    {
        public int Value { get; set; }

        public override object GetValue()
        {
            return this.Value;
        }
    }

    public class EntityRecordReferenceContextItem : ContextItem
    {
        public List<EntityRecordReference> Value { get; set; }

        public override object GetValue()
        {
            return this.Value;
        }
    }

    public class EntityRecordReference
    {
        public Guid RecordId;

        public string PrimaryDisplayValue;
    }

    class Program
    {
        static void Main(string[] args)
        {
            // Creating string context item
            StringContextItem stringContextItem = new StringContextItem();
            stringContextItem.Value = "StringContextItem";
            AServiceBusMessage serviceBusMessage = new AServiceBusMessage();
            serviceBusMessage.contextItems = new List<ContextItem>() { stringContextItem };

            string jsonString = JsonSerializer.Serialize(serviceBusMessage);

            AServiceBusMessage deserializedServiceBusMessage =
                JsonSerializer.Deserialize<AServiceBusMessage>(jsonString);
            // On deserialization, the recievedContextItem variable is NULL  
            object recievedContextItem = deserializedServiceBusMessage.contextItems[0].GetValue();
        }
    }

**Comment by eiriktsarpalis** [comment]
We have no such analysis tool, I'm afraid we won't be able to help you with that. If manual auditing of your type hierarchies isn't feasible, you might consider using Roslyn or perhaps even a [reflection-based search](https://stackoverflow.com/questions/2362580/discovering-derived-types-using-reflection) to determine what types in your assembly define derived types.

> To handle this we will be creating a Custom Converter for the ContextItem type.

As mentioned, the upcoming System.Text.Json will have built-in support for [polymorphism](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/polymorphism?pivots=dotnet-7-0) so writing custom converters is not necessary; it would be as simple as adding a few attributes to the base types you are looking to serialize. You can start using the new version [right away](https://www.nuget.org/packages/System.Text.Json/7.0.0-rc.2.22472.3) the nuget package does support .NET 4.6.2.

**Comment by snjosephms** [comment]
Thanks for the revert. We explored further and were able to use reflection to find all types which have derived types in our assembly. 
Before closing this thread can you please confirm on the following? : My understanding is that only types in our assembly which define derived types will cause issues due to polymorphic deSerialization. Is there **any** other hierarchy/implementation that is needed to be taken care of when handling polymorphic deSerialization scenarios?

**Comment by eiriktsarpalis** [comment]
It depends on what types you have opted into in your custom contract resolver. Unless explicitly opted in, no types will be handled polymorphically.
