### ISSUE TITLE
Collapse official build legs into one per configuration 

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#76911]
In order to make the runtime more source build friendly, we need to try to eliminate as many "join points" as possible.  The current approach to the desktop build is to build the runtime and then feed that into both the libraries and the installer builds.  Where applicable, we should collapse these legs into one per configuration, building all subsets.

CoreCLR Release builds:
- [ ] linux-arm
- [ ] linux-arm64
- [ ] linux-musl-x64
- [ ] linux-musl-arm
- [ ] linux-musl-arm64
- [ ] linux-x64
- [ ] osx-arm64
- [ ] osx-x64
- [ ] windows-x64
- [ ] windows-x86
- [ ] windows-arm
- [ ] windows-arm64

CoreCLR PGO Release builds:
- [ ] linux-arm64
- [ ] linux-x64
- [ ] windows-x64
- [ ] windows-x86
- [ ] windows-arm64

**Comment by steveisok** [comment]
We should also consider what we can do with the workloads build.  That is a join point where we need to collect runtime artifacts from multiple builds in order to prepare them for VS. Do we *really* have to build this in runtime?  

Perhaps this should be in an issue on its own.

**Comment by akoeplinger** [comment]
I don't think there's anything left to do here, closing.
