### ISSUE TITLE
Native Runtime Repository Crash Issue

### ISSUE THREAD

**Issue by alhad-deshpande** [dotnet/runtime#76938]
### Description

This issue occurs while building runtime repository on ppc64le. The issue occurs while building System.Data.Odbc.dll project. Analyzing the stack trace below are the findings:

1. The ExecuteSuppressionAction method in rosyln/src/compilers/core/portable/DiagnosticAnalyzer/AnalyzerExecutor.cs file sets up SuppressionAnalysisContext and passes isSupportedSuppression delegate using below line:
Func<SuppressionDescriptor, bool> isSupportedSuppression = supportedSuppressions.Contains;

2. While calling this delegate i.e. Contains method of ImmutableArray class from ReportSuppression method (file - rosyln/src/compilers/core/portable/DiagnosticAnalyzer/DiagnosticAnalyzorContext.cs) in second if block using below line:
if (!_isSupportedSuppressionDescriptor(suppression.Descriptor)) the crash occurs.

The mono code is using MONO_JUMP_TRAMPOLINE and thats why the need_unbox_trampoline flag in common_call_trampoline method is flase while calling the Contains method using the above delegate and hence the unboxing is not happening which might be a problem. 

Also, if we change the setup of isSupportedSuppression using lambda expression as below then this issue does not occur.
Func<SuppressionDescriptor, bool> isSupportedSuppression = x => supportedSuppressions.Contains(x);

### Reproduction Steps

This issue occurs while building runtime repository on ppc64le.

### Expected behavior

The issue should not occur and runtime repository build on ppc64le should be successful.

### Actual behavior

=================================================================
        Managed Stacktrace:
=================================================================
          at System.Collections.Generic.GenericEqualityComparer`1:Equals <0x000b0>
          at System.Collections.Generic.EqualityComparer`1:IndexOf <0x000e8>
          at System.Array:IndexOf <0x001a0>
          at System.Collections.Immutable.ImmutableArray`1:IndexOf <0x003f8>
          at System.Collections.Immutable.ImmutableArray`1:IndexOf <0x001d4>
          at System.Collections.Immutable.ImmutableArray`1:Contains <0x000b4>
          at Microsoft.CodeAnalysis.Diagnostics.SuppressionAnalysisContext:ReportSuppression <0x000c4>
          at Microsoft.Interop.Analyzers.ShapeBreakingDiagnosticSuppressor:SuppressMarkMethodsAsStaticDiagnosticIfNeeded <0x0040c>
          at Microsoft.Interop.Analyzers.ShapeBreakingDiagnosticSuppressor:ReportSuppressions <0x0023c>
          at <>c:<ExecuteSuppressionAction>b__46_0 <0x000e4>
          at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor:ExecuteAndCatchIfThrows_NoLock <0x00120>
          at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor:ExecuteAndCatchIfThrows <0x00258>
          at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor:ExecuteSuppressionAction <0x00720>
          at <>c__DisplayClass107_1:<ApplyProgrammaticSuppressionsCore>b__4 <0x000cc>
          at System.Threading.Tasks.Task:InnerInvoke <0x000b0>
          at <>c:<.cctor>b__273_0 <0x00064>
          at System.Threading.ExecutionContext:RunFromThreadPoolDispatchLoop <0x000e0>
          at System.Threading.Tasks.Task:ExecuteWithThreadLocal <0x00490>
          at System.Threading.Tasks.Task:ExecuteEntryUnsafe <0x0013c>
          at System.Threading.Tasks.Task:ExecuteFromThreadPool <0x00074>
          at System.Threading.ThreadPoolWorkQueue:Dispatch <0x005ac>
          at WorkerThread:WorkerThreadStart <0x002d4>
          at System.Threading.Thread:StartCallback <0x0016c>
          at System.Object:runtime_invoke_void__this__ <0x00110>
=================================================================

**Comment by janani66** [comment]
@jaredpar / @uweigand  -- any thoughts on why unboxing is not happening ?

**Comment by jaredpar** [comment]
No. The IL looks correct so I would assume it's the runtime having an issue with this pattern.

**Comment by janani66** [comment]
@jaredpar  -- 

Like Alhad said in the description, replacing 
Func<SuppressionDescriptor, bool> isSupportedSuppression = supportedSuppressions.Contains;
by 
Func<SuppressionDescriptor, bool> isSupportedSuppression = x => supportedSuppressions.Contains(x);
seems to get past the problem.  Would you be able to explain why this may be happening only on Power runtime

**Comment by jaredpar** [comment]
> Would you be able to explain why this may be happening only on Power runtime

Can't really comment here. The IL for the two cases is different but not in any strange way. They're common patterns that occur in C# all in the ecosystem. 

The runtime team would need to comment here as it appears it's having an issue with this pattern in this case.

**Comment by jaredpar** [comment]
@davidwrighton

**Comment by davidwrighton** [comment]
@lambdageek Can you route this to whoever contributed the ppc64le port of mono?

**Comment by jaredpar** [comment]
If you want to see the rough diff in the IL for this scenario you can see this sharplab 

https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoBAGABAlAFgG5NNlcBhXAb01wdwHtgArAUwGMAXXAWRQAKADJQAztwA8AZQCuAB3kAndmLFQmMACKrOSqPO5MlAPlxiF8493YATOYpVqNMMQEpa9RgwQBWGZZO6po6YnoGRkoANLjATEwANmbiDlZKNvaBqsEwuAC85pbWdqlBLmIAdJSa3NCupBjePgDsuClF6SVZzprETbheDAC+gwONjCwcPPxIIuJSpdkuoeGGxmYWisWZjkua7p7j3n4Buz3auvpr0bHxSW1iqduL5/m4AB75Gx0ZLzmV1RgtVgYkE7zcDX6CFa7S2nR2yj2MD6/TG3hGGAxYwof2WlwixlouCxjCAA=

**Comment by lambdageek** [comment]
Ping @directhex

**Comment by SamMonoRT** [comment]
Fixed via - https://github.com/dotnet/runtime/pull/77308  Closing the issue, please re-open if this still reproes. cc @directhex
