### ISSUE TITLE
PlaceSafepoints pass removed from LLVM

### ISSUE THREAD

**Issue by vargaz** [dotnet/runtime#76936]
### Description

LLVM support in mono depends on this pass, it was removed by this commit:

https://github.com/llvm/llvm-project/commit/cb66e123c6bc82a793300b6fb3ecbed79c58f557

### Reproduction Steps

.

### Expected behavior

.

### Actual behavior

.

**Comment by lambdageek** [comment]
> If someone wants to use this, restoring it would not be hard. The immediate motivation for removal is that this is one of the last passes remaining which hasn't been ported to the new pass manager and the (straight forward) work to do so is not justified for unused code.

They're open to bringing it back, but we'd need to switch it over to the new pass manager.

Also for reference, the differential was https://reviews.llvm.org/D135371

**Comment by jandupej** [comment]
It appears that they reverted the removal of safepoints pass. https://reviews.llvm.org/rGfe755af3a9a56a23494ed231d1b007a9a7b91174

**Comment by jandupej** [comment]
There is a PR open with the LLVM team: https://reviews.llvm.org/D136163

**Comment by jandupej** [comment]
The changes to keep PlaceSafepoints have been accepted to the LLVM codebase https://reviews.llvm.org/D136163. Closing.
