### ISSUE TITLE
System.Text.Json code generator creates metadata for classes that are explicitly ignored

### ISSUE THREAD

**Issue by dotMorten** [dotnet/runtime#76937]
### Description

I have a few classes I'm trying to convert to using System.Text.Json codegenerator to better support trimming.
However I'm having trouble getting the code generator to _not_ create metadata for classes that are ignored. This causes sometimes 100s of classes to get metadata generated which would never be used, as well as often hitting code it can't even generate correct code for.

Issue is likely related to this .net7 specific issue: https://github.com/dotnet/runtime/issues/76807

### Reproduction Steps

Add the following code to a .NET 6 app/library:

```cs
    [JsonSerializable(typeof(MyObject))]
    [JsonSourceGenerationOptions(GenerationMode = JsonSourceGenerationMode.Metadata, IgnoreReadOnlyFields = true)]
    internal partial class MyObjectSerializationContext : JsonSerializerContext
    {
    }
    public class MyObject
    {
        [JsonPropertyName("test")]
        public string? Test { get; set; }
        [JsonIgnore]
        private readonly ComplexObject? _data; // Metadata generated for this type. Why?!?
    }

    public class ComplexObject
    {
        private protected object _thisLock = new object(); // This causes code gen problem
    }
```
Compile and observe the build errors and the classes that metadata is generated for.

### Expected behavior

Project builds with out errors. No metadata generated for `ComplexObject` or anything else ignored.

### Actual behavior

```
1>E:\sources.tmp\TrimTest\ClassLibrary1\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\MyObjectSerializationContext.ComplexObject.g.cs(58,85,58,94): error CS0122: 'ComplexObject._thisLock' is inaccessible due to its protection level
1>E:\sources.tmp\TrimTest\ClassLibrary1\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\MyObjectSerializationContext.ComplexObject.g.cs(59,92,59,101): error CS0122: 'ComplexObject._thisLock' is inaccessible due to its protection level
```

I don't get why it is even trying to generate anything for `ComplexObject` - I explicitly told it to ignore that field. This happens with .net6 also though (also tested 6.0.6 nuget package).

In my specific case, `ComplexObject` is potentially a huge object graph and the result is I'm getting metadata generated for hundreds of classes.

![image](https://user-images.githubusercontent.com/1378165/195389073-152961e1-3b6a-49b6-8c86-3d242a29e8b6.png)

### Known Workarounds

I could add [JsonIgnore] on `_thisLock`, but that only addresses this specific class - I don't really want to add json ignore to every field in all my classes that causes problems, when these classes aren't even meant for JSON serialization, and I don't want to bloat my assembly size with all this extraneous metadata generated.

### Configuration

.NET 6.0.404

**Comment by eiriktsarpalis** [comment]
Thanks for opening the issue. It looks like @krwq beat you to it and opened another issue based on your twitter report:

https://github.com/dotnet/runtime/issues/76919

With that, I'm going close this one as a duplicate. Feel free to continue the conversation in that other thread.

**Comment by dotMorten** [comment]
Thanks I totally missed that. Was tweeting hoping I'd wake up to someone telling me I'm doing it wrong, and if not, I was going to log it :-)
