### ISSUE TITLE
[wasm-mt] Improved experience when SharedArrayBuffer is not available

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#76961]
Runtime JS should check that `SharedArrayBuffer` is available and if it isn't diagnose whether [CORS headers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#security_requirements) are being served, and provide a nice error message.

For Blazor and Uno we should provide some kind of callback that can be triggered if the runtime's requirements are not met

**Comment by maraf** [comment]
@pavelsavara Is this resolved with the mentioned PR? Or should we do more?
