### ISSUE TITLE
Localized string needed for `workloads/wasm-experimental/description`

### ISSUE THREAD

**Issue by danroth27** [dotnet/runtime#76968]
Looks like the new wasm-experimental workload is currently missing a description:

![image](https://user-images.githubusercontent.com/1874516/182718826-9d424d93-2992-4d26-8c37-9512241902b2.png)

7.0.100-preview.7.22370.3

@lewing

**Comment by ilonatommy** [comment]
current status:
```
Workload ID                 Description                                     
----------------------------------------------------------------------------
wasm-experimental           workloads/wasm-experimental/description         
wasm-experimental-net7      .NET WebAssembly experimental tooling for net7.0
wasm-experimental-net8      .NET WebAssembly experimental tooling for net8.0
wasm-tools                  .NET WebAssembly build tools                    
wasm-tools-net6             .NET WebAssembly build tools for net6.0         
wasm-tools-net7             .NET WebAssembly build tools for net7.0         
wasm-tools-net8             .NET WebAssembly build tools for net8.0 
```
https://github.com/dotnet/runtime/pull/83223 was trying to fix it but used `workloads/wasm-tools-experimental/description` instead of `workloads/wasm-experimental/description`.

**Comment by ilonatommy** [comment]
@lewing, we have the `wasm-experimental` description for English only and your PR added it only for that language. Shouldn't we have it for all the languages listed in `src/mono/nuget/Microsoft.NET.Workload.Mono.Toolchain.Current.Manifest/localize`? `workloads/wasm-tools/description` has them translated.
Same story with `workloads/runtimes-windows/description` - only English.
