### ISSUE TITLE
[wasm-mt] Option to package threaded runtime as CommonJS

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#76962]
Firefox doesn't like `import(uri).then(callback)` [Bugzilla #1540913](https://bugzilla.mozilla.org/show_bug.cgi?id=1540913). Consider compiling `dotnet.worker.js` and `dotnet.js` without ES6

**Comment by lewing** [comment]
@maraf lets explore the options here and figure out the path forward

**Comment by maraf** [comment]
I'll try to use [babel-plugin-transform-modules-commonjs](https://babeljs.io/docs/en/babel-plugin-transform-modules-commonjs) to transpile our ES6 to commonjs. It will be possible to have it as commonjs only for Firefox.

**Comment by maraf** [comment]
Firefox added support for modules
