### ISSUE TITLE
CoreCLR 7.0 have changed public Debug API. Why?

### ISSUE THREAD

**Issue by viewizard** [dotnet/runtime#76960]
Hello,

could you please clarify, why in https://github.com/dotnet/runtime/commit/3ea30ed321949d238bf97534a2a8cbabf580f238
public Debug API was changed:

`ICorDebugArrayValue::GetBaseIndicies` https://learn.microsoft.com/en-us/dotnet/framework/unmanaged-api/debugging/icordebugarrayvalue-getbaseindicies-method?view=aspnetcore-2.1
was changed from `GetBaseIndicies` to `GetBaseIndices`

`ICorDebugArrayValue::HasBaseIndicies` https://learn.microsoft.com/en-us/dotnet/framework/unmanaged-api/debugging/icordebugarrayvalue-hasbaseindicies-method?view=aspnetcore-2.1
was changed from `HasBaseIndicies` to `HasBaseIndices`

CC @alpencolt  @jkotas

**Comment by jkotas** [comment]
Right, the typo is in this API name for 20+ years, so there is a quite a bit code written that depends on it.
