### ISSUE TITLE
Equivalent to WebRequestHandler in .NET 6

### ISSUE THREAD

**Issue by houyuansha** [dotnet/runtime#76977]
Our current project is in .NET framework 4.6.2, which outputs a library. We'd like to make this library compatible with .NET 6. When trying to use our library in a .NET 6 test project, we got the following error: 
_System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http.WebRequest, Version=4.0.0.0, Culture=neutral, PublicKeyToken=xxxxx'. The system cannot find the file specified. File name: 'System.Net.Http.WebRequest, Version=4.0.0.0, Culture=neutral, PublicKeyToken=xxxxx_
After investigation, our project is using WebRequestHandler in one of the dependencies. WebRequestHandler is only available in .NET framework. We tried to switch to use HttpClientHandler but could not found the ClientCertificates property that we need to use.
What should we do in this kind of situation? What's the equivalent of WebRequestHandler in NET6 that is also available in .NET framework?

**Comment by wfurt** [comment]
`ClientCertificates` should be available....
https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.clientcertificates?view=net-6.0

**Comment by houyuansha** [comment]
Yes, but our project is still in .NET framework 4.6.2 at the moment. We cannot migrate to .NET 6 for now. 
https://learn.microsoft.com/en-us/dotnet/core/porting/
It says here that .NET 6 projects can refer .NET framework libraries, which is what we are trying to do.

**Comment by davidfowl** [comment]
You need to compile your library for both .NET Framework and .NET 6+ and use different code to support each of those scenarios. See https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting#multi-targeting for more information.

**Comment by karelz** [comment]
@huoyaoyuan what is `ClientCertificateHandler`?

**Comment by huoyaoyuan** [comment]
> @huoyaoyuan what is `ClientCertificateHandler`?

Oops, typo. It's `ClientCertificates `.

**Comment by MihaZupan** [comment]
@houyuansha after multi-targeting for .NET Framework and .NET 6 as [David had suggested](https://github.com/dotnet/runtime/issues/76977#issuecomment-1277121772), are you missing any other functionality?
