### ISSUE TITLE
Semaphore.WaitOne() does not wait on Android

### ISSUE THREAD

**Issue by NilsHoyer** [dotnet/runtime#76989]
### Description

I'm developing an App with Xamarin for Android with .Net Runtime 6.0.

I have the following code part:

    Semaphore semaphore;
    semaphore = new(100, 1024);
    semaphore.WaitOne();

I expect, this will block the current thread, but it doesn't.

### Reproduction Steps

See above.

### Expected behavior

See above.

But the same code, executed with UWP waits.

### Actual behavior

See above.

### Regression?

This is my first try developing with VS and on Android. So I don't know.

### Configuration

Visual Studio Community 2022 17.3.5
Development machine: MacBook Pro 2011 with Windows 10 Pro 21H2 19044.2075 64 bit
Execution machine: Samsung Galaxy A20e with Android 11.0 - API 30
On Windows installed .Net Runtime 6.0.9.

### Other information

If I'm wrong here with my bug report, please excuse me. I'm new on developing with VS.

**Comment by NilsHoyer** [comment]
The problem still exists in VS 17.3.6 with .Net Runtime 6.0.10.

**Comment by stephentoub** [comment]
> I expect, this will block the current thread, but it doesn't.

That should _not_ block. ` new Semaphore(100, 1024)` says that the semaphore currently has 100 resources available. WaitOne will consume one of those and return immediately. It only blocks when the resource count hits zero. That's the case regardless of OS.

**Comment by NilsHoyer** [comment]
Sorry, my mistake. 😥

**Comment by NilsHoyer** [comment]
Sorry, my mistake. 😥
