### ISSUE TITLE
Mono cygwin eglib build failed direct.h not found

### ISSUE THREAD

**Issue by alexander-toschev** [dotnet/runtime#76993]
### Description

Hello,
I am building the mono under cygwin library and got the following error  Error: direct.h: No such file or directory

Branch https://github.com/mono/mono/tree/mono-3.12.0-tls-hotfix . I need old version to build

### Reproduction Steps

# 1
`./autogen.sh --prefix="C:\monobin" --with-preview=yes --enable-msvc --disable-boehm`

# 2
`./configure --host=i686-pc-mingw32  `

Git submodules updated successfully

   mcs source:    mcs

   Engine:
        Host:          i686-pc-mingw32
        Target:        i686-pc-mingw32
        GC:            sgen and Included Boehm GC with typed GC and parallel mark
        TLS:           pthread
        SIGALTSTACK:   no
        Engine:        Building and using the JIT
        oprofile:      no
        BigArrays:     no
        DTrace:        no
        LLVM Back End: no (dynamically loaded: no)

   Libraries:
        .NET 2.0/3.5:  yes
        .NET 4.0:      yes
        .NET 4.5:      yes
        MonoDroid:     no
        MonoTouch:     no
        Xamarin.Mac:   no
        JNI support:   no
        libgdiplus:    assumed to be installed
        zlib:          system zlib

# 3
`make`

goutput.c:135:1:  «noreturn» function does return
 }
 ^
  CC       libeglib_la-gqsort.lo
  CC       libeglib_la-gstr.lo
  CC       libeglib_la-gslist.lo
  CC       libeglib_la-gstring.lo
  CC       libeglib_la-gptrarray.lo
  CC       libeglib_la-glist.lo
  CC       libeglib_la-gqueue.lo
  CC       libeglib_la-gpath.lo
gpath.c:34:21:Error: direct.h: No such file or directory

make[4]: *** [Makefile:959: libeglib_la-gpath.lo]

### Expected behavior

Build success

### Actual behavior

Build failed

### Regression?

No

### Known Workarounds

No

### Configuration

Windows XP, Cygwin

**Comment by alexander-toschev** [comment]
Label area-Build-mono

**Comment by marek-safar** [comment]
Please report mono build issues at https://github.com/mono/mono
