### ISSUE TITLE
File.Copy leads to deadlocks on Ubuntu Linux

### ISSUE THREAD

**Issue by abulhol** [dotnet/runtime#76999]
### Description

After having upgraded to the latest version of Mono 6.12.0.182, we experience that threads in our console application get stuck and lead to deadlocks. 
Our thread dumps show that these seem to be due to calls to `System.IO.FileSystem.CopyFile`.

### Reproduction Steps

The behavior is random and hard to reproduce. In our application, it happens every few hours, and sometimes only after a few days. 

Here are the specs of our setup:
Ubuntu 22.04.1 LTS
Kernel 5.15.0-48-generic
Mono JIT compiler version 6.12.0.182

We run an application compiled for .NET Framework 3.5. 

The server also runs Samba with various shares. Our applications reads and writes to these. 

### Expected behavior

No deadlocks.

### Actual behavior

Threads not proceeding as usual and deadlocking other workers that are waiting for shared locks. 
`top` shows that Mono completely uses 1 or 2 CPUs constantly (likely 1 CPU per hanging thread). 

Here is an example of a stack trace we captured via `mono_threads_request_thread_dump` for the locking thread:
````
"Worker03"  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) Interop/Sys.CopyFile (Microsoft.Win32.SafeHandles.SafeFileHandle,Microsoft.Win32.SafeHandles.SafeFileHandle) [0x0004c] in <12b418a7818c4ca0893feeaaf67f1e7f>:0
  at System.IO.FileSystem.CopyFile (string,string,bool) [0x00063] in <12b418a7818c4ca0893feeaaf67f1e7f>:0
  at System.IO.File.Copy (string,string,bool) [0x0006e] in <12b418a7818c4ca0893feeaaf67f1e7f>:0
````

### Regression?

We were previously using:
Ubuntu 18.04.6 LTS
Kernel  4.15.0-177-generic
Mono JIT compiler version 5.14.0.177

We never experienced the issue there. 

We suspect that the issue is due to the changes in the `File.Copy` implementation for Unix systems, in particular with the implementation for `sendfile` (`HAVE_SENDFILE_4`). 
See e.g. https://github.com/dotnet/runtime/commit/9b83294a307347d175628b8582776b2d3d03088b?diff=split

We assume that Mono has issues when the file changes while it is being copied. This could happen because e.g. Samba is modifying files at the same time. 

### Known Workarounds

We have replaced all calls to `File.Copy` with the a custom method that uses the code below, which basically works as the legacy method `CopyFile_ReadWrite(int inFd, int outFd)`.
We are currently monitoring the application to determine if this fixes the issue.
````
const int BufLength = 4096;
byte[] DataArray = new byte[BufLength];
using (FileStream FSRead = new FileStream (SourceFilePath, FileMode.Open, FileAccess.Read, FileShare.None, BufLength))
{
	using (BinaryReader BWRead = new BinaryReader (FSRead))
	{
		using (FileStream FSWrite = new FileStream  (DestinationFilePath, FileMode.Create, FileAccess.Write, FileShare.None, BufLength))
		{
			using (BinaryWriter BWWrite = new BinaryWriter (FSWrite))
			{
				for (; ; )
				{
					int R = BWRead.Read (DataArray, 0, BufLength);
					if (0 == R)
						break;
					BWWrite.Write (DataArray, 0, R);
				}
			}
		}
	}
}		
````

**Comment by adamsitnik** [comment]
@marek-safar @akoeplinger could you please transfer this issue to https://github.com/mono/mono ?

**Comment by abulhol** [comment]
Sorry for posting in the wrong project, please move as suggested.

**Comment by abulhol** [comment]
I have opened the issue myself in the Mono project: https://github.com/mono/mono/issues/21564
Therefore closing it here.

**Comment by adamsitnik** [comment]
> Therefore closing it here.

@abulhol thank you!
