### ISSUE TITLE
Blazor WebAssembly  -AOT - NET 7 Release candidate 2

### ISSUE THREAD

**Issue by dkboon01** [dotnet/runtime#76992]
I'm trying to publish my Blazor WASM program and use AOT.  I'm getting this error
```
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.0-rc.2.22472.3\Sdk\WasmApp.Native.targets(583,5):
Error : Precompiling failed for C:\Users\dboone\source\previewNet7\ABCApps\ABCBlazor\obj\Release\net7.0\linked\Microsoft.SqlServer.Types.dll with exit code 1.
  Failed to load method 0x6000001 from 'C:\Users\dboone\source\previewNet7\ABCApps\ABCBlazor\obj\Release\net7.0\linked\Microsoft.SqlServer.Types.dll' due to
  Could not resolve type with token 01000010 from typeref (expected class 'Microsoft.Data.SqlClient.Server.IBinarySerialize' in assembly 'Microsoft.Data.SqlClient, Version=3.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5') assembly:Microsoft.Data.SqlClient, Version=3.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5 type:Microsoft.Data.SqlClient.Server.IBinarySerialize member:(null).
Mono Ahead of Time compiler - compiling assembly C:\Users\dboone\source\previewNet7\ABCApps\ABCBlazor\obj\Release\net7.0\linked\Microsoft.SqlServer.Types.dll
```

How can I fix this?

**Comment by marek-safar** [comment]
This looks like a trimming issue, do you have a repro we could use to diagnose this problem further?

**Comment by dkboon01** [comment]
What is the best way to send the repro?

**Comment by marek-safar** [comment]
For example attach it here or create GH repo

**Comment by eerhardt** [comment]
> We have some azure keys in our program.cs file that will need to be changed

Note that this typically isn't a good idea. With Blazor WebAssembly, your WASM .dlls gets downloaded to the client's machine, which anyone can disassembly and view the strings in your app. So anyone who can load your website (even if they aren't logged in to your app) will be able to see these keys.

**Comment by lewing** [comment]
I believe this issue is out of date, if there is a still a problem please file a new issue
