### ISSUE TITLE
Should we revise implementation of Environment.UserInteractive?

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#770]
This is currently implemented as `return true;` but since in 3.0 we're adding UI stacks to .NET Core, maybe we should implement this since this is usually used before popping a UI?

The Windows version of the algorithm is copied all over the place (touching it in dotnet/corefx#39285, dotnet/winforms#1247).

**Comment by danmosemsft** [comment]
@jkotas do you have any remaining concern about implementing this? Per offline thread, there was also a request for this through support channels.

I assume we would paste in the .NET Framework implementation (and hard code false for Unix)
https://referencesource.microsoft.com/#mscorlib/system/environment.cs,87db1f60fca84037

But for anyone reading this -- if you just want to check you're not in a Windows Service, and need a workaround, it may be easier to paste in the ASP.NET code:
https://github.com/aspnet/Extensions/blob/master/src/Hosting/WindowsServices/src/WindowsServiceHelpers.cs

**Comment by danmosemsft** [comment]
Although, perhaps another option (that is less Windowsy) is to determine whether a console is attached. Presumably that would be well defined on Unix as well.

In [reference source](https://referencesource.microsoft.com/#mscorlib/system/environment.cs,87db1f60fca84037,references) it seems to be used to determine whether to pop a dialog (for an assert, credentials prompt etc). Rather than to decide whether to write to console vs some log.

I'll find out what the need was from the customer with the support request.

**Comment by jkotas** [comment]
> Unix

I see this API as Windows-specific legacy API. If we really have to fill it in for Windows for compat, I can live with it. But I do not think we should be touching this API for Unix ever.

If we want an API that checks whether console is attached to the process, we should add a new cross-platform for it with clearly defined semantics (if the existing `IsInputRedirected` is not enough...).

Note that the .NET Framework implementation of the API has interesting behaviors that should be re-examined as part of the port:
- Once the process becomes non-interactive, it is always non-interactive. The API won't ever re-check whether the process became interactive. Is it a feature or a bug?
- The comment about win station handles not leaking does not sound right.
- The implementation probably won't work on Nano server. What the behavior should be there?

**Comment by danmosemsft** [comment]
@gmatzen 

> Aside from logging, I need to know when it is appropriate to call ServiceBase.Run

Can you clarify? Isn't it your code's choice whether to register as a service? In what circumstances is this returning false for you, when you are not already running as a service?

**Comment by gmatzen** [comment]
@danmosemsft 

It is not the program's choice when to run as as service.  "static int Main()" is the entry point of the application whether it runs as a service or it runs interactively.  

Environment.IsUserInteractive is always hard coded to return the same thing whether or not the application is running as a service.

The code needs to know whether or not to call ServiceBase.Run.

**Comment by danmosemsft** [comment]
> Once the process becomes non-interactive, it is always non-interactive. The API won't ever re-check whether the process became interactive. Is it a feature or a bug?

I actually cannot find how to transition these states. If I call SetUserObjectInformation to change the value of WSF_VISIBLE, I get access denied - even elevated. Anyway -- this is easily handled by getting the value every time. I don't have evidence it's slow.

> The comment about win station handles not leaking does not sound right.

GetProcessWindowStation docs say to not close the handle.

> The implementation probably won't work on Nano server. What should the behavior be there?

According to https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/mt588480(v=vs.85), there are no window station functions available on Nano. It is documented to be totally non interactive, with no local logon capability, so it can't show dialogs. It does have traditional services. So I think on Nano we can return non-interactive.

**Comment by danmosemsft** [comment]
I verified in a Nano server container that `GetProcessWindowStation()` returns a null handle. `EnumWindowStations()` also returns false. Basically what you expect from the stubs they have when they don't export functions.

**Comment by gmatzen** [comment]
@danmosemsft 

With regard to...
 https://github.com/dotnet/runtime/issues/770#issuecomment-564704216
...
I'm not exactly sure where the confusion is.  It is not the program's choice whether to run as a service or not.  A user chooses to run the same program either as a service or as a console application.  If the program is running as a service (which I can tell via Environment.IsUserInteractive for a full-framework application), then I need to call ServiceBase.Run.  

Perhaps this question is already resolved because there seems now to be a link to #1234 for purposes of fixing this issue.

**Comment by danmosemsft** [comment]
@gmatzen that makes sense. The PR is pretty much implementing what was done on .NET Framework. However it has deficiencies

1. For detecting whether it is appropriate to show UI. This implementation will return true on SKU's without a shell, on all Unix's, potentially when there is no user at the machine, and potentially when your thread is missing rights to show UI like DESKTOP_CREATEMENU 

2. For detecting whether the code is within a Windows Service, for some of the reasons above.

For 2 maybe there should be a way (eg on ServiceBase.IsInWindowsService or some better name) that does (by some means) what the ASP.NET code linked above attempts to do. If you think that would be useful feel free to open a new issue with an API proposal.

**Comment by gmatzen** [comment]
@danmosemsft I don't think I have any concerns, especially if you are implementing what was done on .NET Framework.  That code works for our program because we don't support Nanoserver implementation.

**Comment by danmosemsft** [comment]
@gmatzen OK. Note this would not ship until .NET 5.0 near the end of this year. In the near term, it should be fairly easy for you to paste this code temporarily into your own product.
