### ISSUE TITLE
SocketsHttpHandler is inconsistent with header value trimming on HTTP/1.1

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#77001]
From https://github.com/dotnet/runtime/pull/74393#discussion_r992509854

The [spec](https://www.rfc-editor.org/rfc/rfc9112#name-field-syntax) defines field lines as
```
  field-line   = field-name ":" OWS field-value OWS
  OWS          = *( SP / HTAB )
```

We currently [trim leading SP and HTAB](https://github.com/dotnet/runtime/blob/d2d5ad3ffb51d345c5c3fa31d7dac118355cfe0d/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L1199-L1204), but only [trailing SP](https://github.com/dotnet/runtime/blob/d2d5ad3ffb51d345c5c3fa31d7dac118355cfe0d/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L1206-L1218).
It should be much more common to encounter an HTAB before the value (following the `name:`), as there usually isn't any whitespace after the value.

Do we care about this inconsistency?
Filing this so we can make a conscious decision we can point to in the future.

**Comment by karelz** [comment]
Triage: Should be simple - match one skipping of whitespaces with the other one.
Not critical, but we would welcome PR.
