### ISSUE TITLE
Blazor Web Assembly (.NET 7 RC2) - Debugger crashes on VS 2022 after OIDC redirect, again

### ISSUE THREAD

**Issue by robertmclaws** [dotnet/runtime#77013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Exact same issue as dotnet/aspnetcore#39301. Same bug, same triggers, same result.

### Expected Behavior

I expect debugging Blaxor WebAssembly apps to be able to survive OIDC redirects.

### Steps To Reproduce

See previous issue.

### Exceptions (if any)

See uploaded log file.

### .NET Version

7.0.100-rc.2.22477.23

### Anything else?

My JsDebugger log file is attached.

[visualstudio-js-debugger.txt](https://github.com/dotnet/aspnetcore/files/9777976/visualstudio-js-debugger.txt)

**Comment by robertmclaws** [comment]
No problem. Just an FYI on tracking this, clearing the browser cache temporarily solves the issue. But it comes back on the next OIDC expiration.

**Comment by thaystg** [comment]
Which exactly version of the DevServer package are you using?
<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="7.0.0" PrivateAssets="all" />

Can you help us to reproduce it?

**Comment by robertmclaws** [comment]
I just upgraded to 7.0.1 and am no longer seeing the issue. If it crops back up I'll let you know. Thanks!
