### ISSUE TITLE
System.Text.Json Source generator improvements for .NET 8.0

### ISSUE THREAD

**Issue by layomia** [dotnet/runtime#77019]
**User story tracking source generator improvements for .NET 8.**

#### Features

- [x] https://github.com/dotnet/runtime/issues/58770
- [x] https://github.com/dotnet/runtime/issues/77016
- [x] https://github.com/dotnet/runtime/issues/87431

#### Diagnostics

- [x] https://github.com/dotnet/runtime/issues/76829
- [x] https://github.com/dotnet/runtime/issues/87140
- [x] https://github.com/dotnet/runtime/issues/61782

#### IDE Experience / generation speed

- [x] https://github.com/dotnet/runtime/issues/68353

#### Runtime performance

- [x] https://github.com/dotnet/runtime/issues/71933
- [x] https://github.com/dotnet/runtime/issues/59043
- [x] https://github.com/dotnet/runtime/issues/59041

#### AOT / size

- [x] https://github.com/dotnet/runtime/issues/79122

##### Property visibility issues

- [x] https://github.com/dotnet/runtime/issues/79161

##### Contract configuration

- [x] https://github.com/dotnet/runtime/issues/58638

##### Other

- [x] https://github.com/dotnet/runtime/issues/65361
- [x] https://github.com/dotnet/runtime/issues/76802
- [x] https://github.com/dotnet/runtime/issues/63802

#### By-design / won't fix

- [x] https://github.com/dotnet/runtime/issues/58938
- [x] https://github.com/dotnet/runtime/issues/58134

#### Future

- [ ] https://github.com/dotnet/runtime/issues/58698
- [x] https://github.com/dotnet/runtime/issues/59424
- [x] https://github.com/dotnet/runtime/issues/73714
- [x] https://github.com/dotnet/runtime/issues/54005
- [x] https://github.com/dotnet/runtime/issues/69207
- [x] https://github.com/dotnet/runtime/issues/55043
- [x] #58943
- [x] https://github.com/dotnet/runtime/issues/56206

**Comment by eiriktsarpalis** [comment]
Closing as completed.
