### ISSUE TITLE
VS Code failed to run .NET runtime on Ubuntu 20.04 on WSL2

### ISSUE THREAD

**Issue by QCHighing** [dotnet/runtime#77048]
### Description

I have manually installed dotnet according to the tutorial，<https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install>
and installed dependencies, <https://github.com/dotnet/core/blob/main/release-notes/6.0/linux-packages.md>
but the vscode plugin ".NET Install Tool for Extension Authors" still prompts the error：
`Failed to run .NET runtime. You may be missing key Linux libraries. Install them now?`

### Reproduction Steps

1. Install WSL2 Ubuntu 20.04
2. Install vscode on WIN11, then start vscode
3. Install dotnet on WSL: <https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install>
4. Install dependencies: <https://github.com/dotnet/core/blob/main/release-notes/6.0/linux-packages.md>

### Expected behavior

The  vscode plugin ".NET Install Tool for Extension Authors"  runs correctly.

### Actual behavior

ERROR message:  `Failed to run .NET runtime. You may be missing key Linux libraries. Install them now?`

**Comment by danmoseley** [comment]
Hi there. Does "LD_DEBUG" or "strace" give hints as to what is missing, if you are comfortable trying those (there are various pages that describe how to use them)

However, the code for this extension seems to be in dotnet/vscode-dotnet-runtime. I do not have the power to transfer this issue there. I'll close this -- please open an issue there so you can get the right assistance.
