### ISSUE TITLE
Blazor: Generic attributes do not work in Mono

### ISSUE THREAD

**Issue by Code-Chops** [dotnet/runtime#77047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

At the moment I am running a C# 10 .NET 6 Blazor Webassembly app with EnablePreviewFeatures so I can use generic attributes. Unfortunately when running the app, I get the following error:
`dotnet..w98fhuowzh.js:1430 * Assertion: should not be reached at /__w/1/s/src/mono/mono/metadata/custom-attrs.c:2433`

which leads to this code in the Mono repository: https://github.com/mono/mono/blob/main/mono/metadata/custom-attrs.c#L2451

Apparently generic attributes are not supported at the moment in Mono. And even won't be supported in .NET 7, here is the issue: https://github.com/dotnet/runtime/issues/56887

I have the following questions:

- Shouldn't this be implemented in Mono for .NET 7, because .NET 7 will support generic attributes?
- I guess this is the runtime crashing. I don't know which part of the code crashes now because I don't see a stacktrace. How can I discover what part of my code causes this error?
- My generic attributes are only used for source generation. Is there a way to exclude the attributes in the IL output? For example by putting the attribute in a different file (partial) and excluding the file somehow?

### Expected Behavior

The Mono runtime can handle generic attributes.

### Steps To Reproduce

I don't know how I can reproduce this problem as it happens in the Mono runtime and not on the IL-level.

### Exceptions (if any)

* Assertion: should not be reached at /__w/1/s/src/mono/mono/metadata/custom-attrs.c:2433

### .NET Version

6.0.402

**Comment by Code-Chops** [comment]
Does anybody have a temporary workaround for me?

**Comment by vargaz** [comment]
Is there a testcase which would allow us to reproduce the problem ?

**Comment by Code-Chops** [comment]
I tried some stuff and it took me a while to reproduce the problem. Apparently the exception only gets triggered when using the generic attribute on a struct.

Steps to reproduce:

- Create a new BlazorWebassembly project from the template
- Add `<Enablepreviewfeatures>true</EnablePreviewFeatures>` to the project
- Add the folowing code to Program.cs and run the application:


```
[TestAttribute<int>]
public struct Testing
{
}

public class TestAttribute<T> : Attribute
{
}
```

Note: If you change 'struct' to 'class' the application works just fine.

**Comment by Code-Chops** [comment]
Thank you for your fix! I am looking forward to it.

**Comment by SteveDunn** [comment]
The call stack (as mentioned in #78255 ) is:

```
dotnet.7.0.0.cvrgq2nq1g.js:5 
        
       Error: [MONO] * Assertion: should not be reached at /__w/1/s/src/mono/mono/metadata/custom-attrs.c:2699

    at xe (dotnet.7.0.0.cvrgq2nq1g.js:5:509)
    at Object.je (dotnet.7.0.0.cvrgq2nq1g.js:5:792)
    at _mono_wasm_trace_logger (dotnet.7.0.0.cvrgq2nq1g.js:14:104923)
    at 009924a6:0x9a42
    at 009924a6:0xa585d
    at 009924a6:0x1bfc4a
    at 009924a6:0x1bfcd9
    at 009924a6:0x1bfd42
    at 009924a6:0x9ba77
    at 009924a6:0x3f984
```

**Comment by SteveDunn** [comment]
I'd be keen on trying to fix this myself but I'd need a fair amount of guidance as a I literally haven't got a clue where to start nor what the workflow would look like!

**Comment by Code-Chops** [comment]
They already made a fix, see the pull request above.

**Comment by Code-Chops** [comment]
@SteveDunn do you maybe know a workaround?

**Comment by SteveDunn** [comment]
@Code-Chops - sorry, I don't have a workaround. But if the fix has been merged in, I would guess that it'll be in the next release, which should be due very shortly (7.0.200 or whatever it'll be). @vargaz could probably confirm..?

**Comment by vargaz** [comment]
Right now, the fix is only on the main branch, it couldn't be backported right now as it causes some perf regressions:
https://github.com/dotnet/runtime/pull/78091#issuecomment-1326596920
