### ISSUE TITLE
Query on Migrating from Newtonsoft to System.Text.Json

### ISSUE THREAD

**Issue by snjosephms** [dotnet/runtime#77040]
We are migrating our codebase from Newtonsoft to System.Text.Json. This codebase is used for serialization and de-serialization of Azure Service Bus messages and uses .Net Framework 4.6.2
I need help with the following queries:

1. The data model which is used for the Service Bus message has been decorated with  System.Runtime.Serialization attributes. During the migration from Newtonsoft to System.Text.Json how do we provide support for the below System.Runtime.Serialization attributes? 
Does anything need to be done explicitly here as we migrate to System.Text.Json? 
      - 'DataMember',
      - EnumMember'
      - 'DataContract'
      - 'Required'
      - 'KnownType'
      - 'EnumMember with Value property set'
      - 'DataMember attribute with Name property set'

2. How do we support properties with private setters and properties with default values with System.Text.Json?

4. Does anything need to be done explicitly for support for enum types in System.Text.Json?

5. If the max depth is limit is reached during runtime, is an exception thrown?

6. I have primarily been referring [Migrate from Newtonsoft.Json to System.Text.Json - .NET | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/migrate-from-newtonsoft?pivots=dotnet-6-0#table-of-differences-between-newtonsoftjson-and-systemtextjson) table. Can you please share any other recommended resources we should be following for this migration?

**Comment by eiriktsarpalis** [comment]
Hi Sneha, regarding your questions

1. Per #29975 we don't have any plans for supporting System.Runtime.Serialization attributes out of the box. However, it should be possible to add support on your own using a custom contract resolver, [like the one described here](https://github.com/dotnet/runtime/issues/29975#issuecomment-1187188015).

2. For public properties with non-public setters you can try applying the [JsonIncludeAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonincludeattribute?view=net-6.0), but that would not be supported in source gen. I'm not sure what you mean by "properties with default values".

3. By default, enum types are serialized using their numeric representations. You can opt into string-based serialization using the built-in [`JsonStringEnumConverter`](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonstringenumconverter?view=net-6.0).

4. Yes, and the max depth can be configured using [`JsonSerializerOptions.MaxDepth`](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.maxdepth?view=net-6.0).

5. I believe that's the only official guide we maintain. I suspect you might be able to locate unofficial guidance on an issue-by-issue basis in other places.
