### ISSUE TITLE
[FullPGO] Regressions in LinqBenchmarks due to delegate GDV

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#77041]
A couple of the LinqBenchmarks show regressions in FullPGO mode starting when delegate GDV was introduced:
https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_Windows%2010.0.18362_PGOType%3dfullpgo%2fLinqBenchmarks.Where01LinqQueryX.html
https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_Windows%2010.0.18362_PGOType%3dfullpgo%2fLinqBenchmarks.Where01LinqMethodX.html

The following shows an improvement, so I wonder if the profiles are being conflated in some way:
https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_Windows%2010.0.18362_PGOType%3dfullpgo%2fLinqBenchmarks.Where01LinqMethodNestedX.html

**Comment by jakobbotsch** [comment]
Just opening this so I don't lose track of this. cc @AndyAyersMS (and I think @EgorBo may have pointed it out too at some point)

**Comment by EgorBo** [comment]
it's interesting why this was never reported cc @DrewScoggins

**Comment by DrewScoggins** [comment]
I will have to look, but I am fairly certain that we do not do auto-filing for the FullPGO runs. Also @AndyAyersMS do you remember if it was the FullPGO or the NoPGO runs that we hijacked for the OSR work?

**Comment by AndyAyersMS** [comment]
> I will have to look, but I am fairly certain that we do not do auto-filing for the FullPGO runs. Also @AndyAyersMS do you remember if it was the FullPGO or the NoPGO runs that we hijacked for the OSR work?

It was NoPGO.

**Comment by jakobbotsch** [comment]
These show good improvements in the standard perf lab runs coinciding with the default enabling of tiered PGO. Rechecking the FullPGO lab runs, I can see that they improved with #70941 and #84427, so the original regression here may have just been due to BDN not benchmarking tier1 code? In any case will close.
