### ISSUE TITLE
String.StartsWith("\0") behavior change between .NET Framework and .NET 6

### ISSUE THREAD

**Issue by Austin-Lamb** [dotnet/runtime#77050]
### Description

Take the following code:

```csharp
Console.WriteLine("/    ".StartsWith("\0", StringComparison.InvariantCulture));
```

On .NET Framework (specifically, I tested net472) this produces `False` but on .NET 6 it produces `True`.

Surprisingly, if the thread's current culture is set to `InvariantCulture`, then these two lines:

```csharp
Console.WriteLine("/    ".StartsWith("\0"));
Console.WriteLine("/    ".StartsWith(`\0`);
```

Produce `True` and `False` on .NET 6 - it's surprising to me that a single character string's behavior would differ from the same `char`

### Reproduction Steps

```csharp
Console.WriteLine("/    ".StartsWith("\0", StringComparison.InvariantCulture));
```

### Expected behavior

That behavior matches .NET Framework in this case.

### Actual behavior

Behavior does not match - see description.

### Regression?

Yes, it worked in net472 as expected.

### Known Workarounds

Use `StringComparison.Ordinal` in this case - but this was a surprising find when porting a large .NET Framework codebase to modern .NET.

### Configuration

.NET versions: `.NET 6.0.10` and `.NET Framework 4.7.2` for what I tested.
OS: Windows 10 22H2 22621.674
Architecture: x64

### Other information

I'm wondering if this is somehow related to [this breaking change](https://learn.microsoft.com/en-us/dotnet/core/compatibility/globalization/6.0/culture-creation-invariant-mode), but it doesn't seem clear that it is in this case.

**Comment by tarekgh** [comment]
Starting from .NET 5.0 we have switched to using the ICU library which is using the Unicode Standard behavior for string collation. You can read more about that in the article https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu.

As you are using linguistic comparison (not passing `StringComparison.Ordinal`, teh operation will be performed linguistically. Per Unicode standard https://www.unicode.org/charts/collation/chart_Ignored.html, `\0` is ignored character. This means this character is fully ignored during the comparison. If you don't like this behavior, you have the option to revert back to old behavior https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#use-nls-instead-of-icu (which we don't recommend) or you use ordinal comparison instead.

**Comment by Austin-Lamb** [comment]
@tarekgh - isn't it surprising that `StartsWith('\0')` and `StartsWith("\0")` return different results, at a minimum?

**Comment by tarekgh** [comment]
> isn't it surprising that StartsWith('\0') and StartsWith("\0") return different results, at a minimum?

It is not surprising. Please look at the doc of this API https://learn.microsoft.com/en-us/dotnet/api/system.string.startswith?view=net-6.0#system-string-startswith(system-char) which is clearly stating:

```
Remarks
This method performs an ordinal (case-sensitive and culture-insensitive) comparison.
```

**Comment by tarekgh** [comment]
Also, we have this discussion https://github.com/dotnet/designs/pull/207/files?short_path=07b100e#diff-07b100e7ddb067a1231e42ff4ad8f0359fd0c900cac5e6044fdf36fd845811c5 to improve the experience.
