### ISSUE TITLE
Why SemaphoreSlims are not as optimized as Channels?

### ISSUE THREAD

**Issue by ziaulhasanhamim** [dotnet/runtime#77098]
I've noticed that in .Net Semaphoreslim is not so optimized compared to channels. Like semaphore slim uses tasks. Can't it just use value tasks like channels? I did some benchmarks where I tried to use a `Channel<bool>` like a semaphore. Channels ended up allocating less than semaphore. Although the performance was the same Channels have to do more work to transfer data. So practically channels are faster. But why is that?

**Comment by gfoidl** [comment]
> Like semaphore slim uses tasks. Can't it just use value tasks like channels?

Historic reasons. SemaphoreSlim was there long before ValueTask came into play, thus they return Task.
Now this can't be changed, as that would be a breaking change.

Aside: if there's huge demand for a "SemaphoreSlimSlim" (of course with a better name 😉) that returns VT someone should create a [API proposal](https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md).

**Comment by ziaulhasanhamim** [comment]
There should be a better optimized one that complements modern architecture of applications.

**Comment by danmoseley** [comment]
@ziaulhasanhamim Perhaps you are interested in prototyping something and sharing comparative benchmarks. That would the best way to advance things if it interests you.

**Comment by ziaulhasanhamim** [comment]
Ok I will do some research on that

**Comment by stephentoub** [comment]
Closing as not actionable.  As noted, if there's a need for additional specific API, please open a new issue for that. Thanks.
