### ISSUE TITLE
[Mono] System.Text.RegularExpressions.Tests source generator tests crash in DeflateInit2_

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#77090]
```
=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at <unknown> <0xffffffff>
	  at ZLibStreamHandle:DeflateInit2_ <0x00073>
	  at System.IO.Compression.ZLibNative:CreateZLibStreamForDeflate <0x000a3>
	  at System.IO.Compression.Deflater:.ctor <0x00133>
	  at System.IO.Compression.DeflateStream:InitializeDeflater <0x00087>
	  at System.IO.Compression.DeflateStream:.ctor <0x0006b>
	  at System.IO.Compression.DeflateStream:.ctor <0x0004b>
	  at System.Reflection.PortableExecutable.DebugDirectoryBuilder:WriteEmbeddedPortablePdbData <0x00107>
	  at System.Reflection.PortableExecutable.DebugDirectoryBuilder:AddEmbeddedPortablePdbEntry <0x00087>
	  at Microsoft.Cci.PeWriter:WritePeToStream <0x00cdb>
	  at Microsoft.CodeAnalysis.Compilation:SerializePeToStream <0x001b7>
	  at Microsoft.CodeAnalysis.Compilation:SerializeToPeStream <0x006f7>
	  at Microsoft.CodeAnalysis.Compilation:Emit <0x00587>
```

## Build Information
Log: https://dev.azure.com/dnceng-public/public/_build/results?buildId=53859&view=ms.vss-test-web.build-test-results-tab&runId=1102432&paneView=debug&resultId=196512
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=53859
Build error leg or test failing: System.Text.RegularExpressions.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/77088

```json
{
  "ErrorMessage": "at ZLibStreamHandle:DeflateInit2_",
  "BuildRetry": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[56035](https://dev.azure.com/dnceng-public/public/_build/results?buildId=56035)|dotnet/runtime|[System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=56035&view=ms.vss-test-web.build-test-results-tab&runId=1149346&resultId=196550)|dotnet/runtime#77170|
|[53859](https://dev.azure.com/dnceng-public/public/_build/results?buildId=53859)|dotnet/runtime|[System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=53859&view=ms.vss-test-web.build-test-results-tab&runId=1102432&resultId=196512)|dotnet/runtime#77088|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|2|

**Comment by marek-safar** [comment]
Is this MonoVM issue, or could this be zlib bug not handling e.g. OOM?

**Comment by jkotas** [comment]
According to the log, the crash is caused by something `emit_native_wrapper_ilgen` calling a null function pointer
```
#0  0x0000007f9dd62d5c in __waitpid (pid=<optimized out>, stat_loc=0x7f9169b560, options=<optimized out>) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  0x0000007f9d737bb8 in dump_native_stacktrace (signal=<optimized out>, mctx=<optimized out>) at /__w/1/s/src/mono/mono/mini/mini-posix.c:843
#2  mono_dump_native_crash_info (signal=<optimized out>, mctx=0x7f9169bfc0, info=<optimized out>) at /__w/1/s/src/mono/mono/mini/mini-posix.c:870
#3  0x0000007f9d6f6448 in mono_handle_native_crash (signal=0x7f9d4f4483 "SIGSEGV", mctx=0x7f9169bfc0, info=0x7f9169c320) at /__w/1/s/src/mono/mono/mini/mini-exceptions.c:3005
#4  0x0000007f9d65fd70 in mono_sigsegv_signal_handler_debug (_dummy=11, _info=0x7f9169c320, context=0x7f9169c3a0, debug_fault_addr=0x0) at /__w/1/s/src/mono/mono/mini/mini-runtime.c:3773
#5  <signal handler called>
#6  0x0000000000000000 in ?? ()
#7  0x0000007f9d5e3ed8 in emit_native_wrapper_ilgen (image=<optimized out>, mb=0x7f74e7b260, sig=0x7f64d9c7c8, piinfo=<optimized out>, mspecs=<optimized out>, func=0x7f08bd10cc <CompressionNative_DeflateInit2_>, flags=(EMIT_NATIVE_WRAPPER_CHECK_EXCEPTIONS | EMIT_NATIVE_WRAPPER_RUNTIME_MARSHALLING_ENABLED)) at /__w/1/s/src/mono/mono/metadata/marshal-lightweight.c:937
#8  0x0000007f9d5738a0 in mono_marshal_emit_native_wrapper (image=0x558ade8da0, mb=<optimized out>, sig=<optimized out>, piinfo=0x7f70d3e8e0, mspecs=<optimized out>, func=0x7f08bd10cc <CompressionNative_DeflateInit2_>, flags=(EMIT_NATIVE_WRAPPER_CHECK_EXCEPTIONS | EMIT_NATIVE_WRAPPER_RUNTIME_MARSHALLING_ENABLED)) at /__w/1/s/src/mono/mono/metadata/marshal.c:6237
```

Potentially related to #74603

**Comment by lambdageek** [comment]
Yea this looks like the same race as #74603.  @naricc I think the underlying race was there before the component move (that has been reverted already), right?  I think the idea of doing a CAS to initialize still makes sense independent of the componentization progress.  It should be a small change.
