### ISSUE TITLE
[API Proposal]: add internal function `hostfxr_get_active_host_context()`

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [dotnet/runtime#77091]
### Background and motivation

I ran into a problem when I needed to inject custom code into an application written in NET Core 5. It can also be useful for custom debuggers written by users.

Let's say you have a running NET Core application. Problem: you have access to process memory and you want to load custom assembly written in C#. To solve this you need to have "host context". But the debugger doesn't have access to the context because it (context) was created during the initialization of the NET Core app.

In existing internal hostfxr API `fx_muxer_t::get_active_host_context()` isn't marked as exported. 

Do you know what I had to do to solve this problem? So, there is two ways:
1. hardcoded address of the function and access to it using pointers
2. `GetProcAddress("hostfxr_get_runtime_properties")` gets pointer to `hostfxr_get_runtime_properties`. Then developer need to parse x86_64 assembly code to find function pointer to ``fx_muxer_t::get_active_host_context()``

https://github.com/dotnet/runtime/blob/482049ad9c6b84a45e291a30f7ac7308bce17e76/src/native/corehost/fxr/hostfxr.cpp#L748-L770

### API Proposal

It would be cool if you add the exported function `hostfxr_get_active_host_context()`

```cpp
SHARED_API const host_context_t *HOSTFXR_CALLTYPE hostfxr_get_active_host_context() {
    return fx_muxer_t::get_active_host_context();
}
```

### API Usage

This would allow developers to access the existing host context without writing the cursed code that goes through x86_64 assembly instructions.

![before](https://user-images.githubusercontent.com/109800286/196027875-40d94ecc-4d79-4997-94aa-9a5601fbbc8d.png)

Usage: https://github.com/StackOverflowExcept1on/how-to-hack-github-actions/blob/ccbcf73137024d024b39510ab7763fe3c5cd7709/projects/cpp/app/bootstrapper/src/main.cpp#L98-L134

### Risks

This will not cause backward compatibility breaks in any way. All responsibility for the use of this function will be on the developer.

This function is intended to gain access to the host context for those who do not own it. As I said this is useful for user debuggers. For example, you go to make your own dnSpy debugger.

**Comment by elinor-fung** [comment]
> you want to load custom assembly written in C#. To solve this you need to have "host context". But the debugger doesn't have access to the context because it (context) was created during the initialization of the NET Core app.

`hostfxr_initialize_for_runtime_config` is intended to allow using an existing / already running .NET. If it is called when the runtime is already loaded, it will give you a 'secondary' host context. That context can be used to do things like load an assembly and get a function pointer. The [native hosting doc](https://github.com/dotnet/runtime/blob/main/docs/design/features/native-hosting.md#initialize-host-context) has more info about secondary contexts.

Would you be able to use that (instead of looking through instructions)? It does require a .runtimeconfig.json for your component - the intent of that is validation that the framework(s) that are used in the existing runtime are compatible with the one(s) required by your component.

**Comment by StackOverflowExcept1on** [comment]
hmm, looks like you're right. It returns secondary context and I haven't noticed it first time due to `rc != 0` check. Exit code 1 is also success code
![image](https://user-images.githubusercontent.com/109800286/197223378-4da83c2b-7338-4fbf-a65a-1c28728a8a95.png)

application is also running fine btw
![image1](https://user-images.githubusercontent.com/109800286/197223803-a318e21b-489c-4b9a-a6fa-a9979ef4f646.png)
