### ISSUE TITLE
System.Runtime.Caching.MemoryCache In ASP.NET WEB API - Error Instantiating

### ISSUE THREAD

**Issue by jpatel107** [dotnet/runtime#77101]
### Discussed in https://github.com/dotnet/runtime/discussions/77100

<div type='discussions-op-text'>

<sup>Originally posted by **jpatel107** October 16, 2022</sup>
I am in process of converting WCF based REST API service to ASP.NET WEB API hosted in IIS. When I try to instantiate System.Runtime.Caching.MemoryCache instance, it throws below error:
"Configuration system failed to initialize, Unrecognized configuration section system.web".

- Is System.Runtime.Caching.MemoryCache  allowed to be used in ASP.NET WEB API project?
- If yes, how can I avoid above mentioned issue?

Note: I am aware of IMemoryCache in ASP.NET WEB API, but it does not exactly provide what I need. For instance, there is no limit on max memory it's allowed to be used. Also, it's sliding expiration removes an entry when it's getting accessed. I use  System.Runtime.Caching.MemoryCache user session data (chart data/dataset etc. for user specific data analysis app), and cannot regenerate data, so we write data to disk when it gets removed from the cache and reload it to cache when user ask for it and cannot be found in the cache. IMemoryCache removes the data after it's being asked for, making it harder to make this work. This works perfectly fine in  System.Runtime.Caching.MemoryCache implementatiion.</div>

**Comment by Tornhoof** [comment]
Why do you think it is not allowed?

You might want to post the full exception stack trace of that error you're mentioning, the actual type System.Runtime.Caching.MemoryCache has nothing to do with system.web. You might still have some legacy configuration code of using the old System.Web stuff somewhere and that throws the error.

**Comment by jpatel107** [comment]
Thanks for the quick response. I found the culprit. it was including original app.config file in the converted project which contained syste.web entries like below. Once these are removed, it stopped throwing exception. Thanks again for quick reply.

  <system.web>
    <sessionState mode="InProc" cookieless="false" regenerateExpiredSessionId="true" timeout="60" />
    <httpRuntime maxUrlLength="10240" maxRequestLength="51200" maxQueryStringLength="10240" />
  </system.web>
