### ISSUE TITLE
End of life support of 'System.ComponentModel.Annotations | 5.0.0' package

### ISSUE THREAD

**Issue by korteksz** [dotnet/runtime#77109]
Hi, 

In our product we get a vulnerability analysis notification that the 'System.ComponentModel.Annotations' with version 5.0.0 has EOL date in 08/05/2022. On nuget.org there is already a preview version of the newer version ([6.0.0-preview.4.21253.7](https://www.nuget.org/packages/System.ComponentModel.Annotations/6.0.0-preview.4.21253.7)) but the problem is that we don't use preview versions, only stable ones. This preview version has been published in 5/24/2021 which means it is also quite old. 

Is it planned to publish a stable version of this package in the near future? 

Thanks for your reply in advance,
Zoltán

**Comment by patrickklaeren** [comment]
They will no longer ship this, as it is part of .NET 6, as per https://github.com/dotnet/announcements/issues/190

**Comment by roji** [comment]
@korteksz you shouldn't need to reference the System.ComponentModel.Annotations nuget package - all the types are available in .NET itself. Try removing the package reference.

**Comment by korteksz** [comment]
Thanks for the quick answers. The package of ours which references that old System.ComponentModel.Annotations nuget package is a multitargeted project (net6.0;net48;net462;netstandard2.0) which is used in older versions as well. What can I do in case of the older versions? Do you have any suggestion? What options I see currently is that I either use it and accept that it is EOL support or try to get rid of that package. Is that correct or there is something else which I am not aware of?

**Comment by roji** [comment]
@korteksz ideally, you'd reference the package for the old TFMs, and not reference it for the newer ones where it's not needed. 

For example, you'd do the following in your csproj:

```xml
<ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="System.ComponentModel.Annotations" Version="..." />
</ItemGroup>
```

**Comment by korteksz** [comment]
Clear. Thank you very much for the support.
