### ISSUE TITLE
Source Genereate Error not provided by TypeInfoResolver of type 'MyJsonContext'. If using source generation, ensure that all root types passed to the serializer have been indicated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically.

### ISSUE THREAD

**Issue by qssq1** [dotnet/runtime#77115]
```
    [JsonSerializable(typeof(JSONResultInfo))]
    [JsonSerializable(typeof(VersionModel))]
    internal partial class MyJsonContext : JsonSerializerContext { }



```

NotSupportedException: Metadata for type 'System.Object' was not provided by TypeInfoResolver of type 'webapi_mes.api.aot.MyJsonContext'. If using source generation, ensure that all root types passed to the serializer have been indicated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically.

NotSupportedException: Metadata for type 'System.Object' was not provided by TypeInfoResolver of type 'webapi_mes.api.aot.MyJsonContext'. If using source generation, ensure that all root types passed to the serializer have been indicated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically.

waggerGeneratorException: Failed to generate schema for type - System.String. See inner exception
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, PropertyInfo propertyInfo, ParameterInfo parameterInfo)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateParameter(ApiParameterDescription apiParameter, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator+<>c__DisplayClass10_0.<GenerateParameters>b__1(ApiParameterDescription apiParam)
System.Linq.Enumerable+WhereSelectListIterator<TSource, TResult>.ToList()
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateParameters(ApiDescription apiDescription, SchemaRepository schemaRespository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)

SwaggerGeneratorException: Failed to generate Operation for action - asepnetcorewebapi.AMaterialController.AddToSheet_InvAuxHold (webapi_mes). See inner exception
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable<ApiDescription> apiDescriptions, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable<ApiDescription> apiDescriptions, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(string documentName, string host, string basePath)
Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

**Comment by jkotas** [comment]
This does not appear to be a problem with AOT. I expect that you will see the same problem when you try to use json source generators with ASP.NET swagger without AOT as well.

@dotnet/area-system-text-json What is the correct way to use json source generators with ASP.NET swagger?

**Comment by eiriktsarpalis** [comment]
> NotSupportedException: Metadata for type 'System.Object' was not provided by TypeInfoResolver of type 'webapi_mes.api.aot.MyJsonContext'. If using source generation, ensure that all root types passed to the serializer have been indicated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically.

Does adding a `[JsonSerializable(typeof(object))]` annotation in `MyJsonContext` address the issue?

> Why does.NET 7 r2 need to override method ?

It might help if you could share a project that reproduces the error, including the VS and .NET sdk versions you are using.

**Comment by tsmoreland** [comment]
I'm seeing this issue with a net6 project recently migrated to net7, seeing the exception for Object and int32.  While I can't say for sure if I've missed a type in the Serialize Context at the very least the error could be more useful than saying Object (or int32) - so way to trace back to which of my types is causing the problem

Apologies it's not a small sample but it does show the issue (RestApi.App specifically as it's a multi-project solution): https://github.com/tsmoreland/issue-tracker-net/tree/main/server/net7

**Comment by tsmoreland** [comment]
This may be a documentation point, one in part raised by a question further up in the comments, or at least I thought it was (can't find it now) specifically what is the correct usage of JsonSerializerContext in NET7?

Previous usage showed something like (from MS blog posts)

```C#
builder.Services
    .AddControllers( ... )
    .AddJsonOptions(jsonOptions =>
    {
        jsonOptions.JsonSerializerOptions.AddContext<MyJsonSerializerContext>();
    });
```

This is what I was using in .NET6 listing off a few DTOs I had defined but not any primitive types or enums which was working near as I could tell (everything serialized as I expected while I may not have been gaining full benefit of the generated code)

That same approach leads to the exceptions mentioned above regarding Object not appearing in the TypeInfoResolver (or more specific types as in my case with int32, Enums and some Microsoft types (relating to use of JsonPatch))

I've updated this now to something like the following which on the surface appears to resolve the problem but still leaves the question - when would I used AddContext vs. when to set the TypeInfoResolver directly

```C#
builder.Services
    .AddControllers( ... )
    .AddJsonOptions(jsonOptions =>
    {
        jsonOptions.JsonSerializerOptions.TypeInfoResolver = JsonTypeInfoResolver.Combine(
            MyJsonSerializerContext.Default,
            new DefaultJsonTypeInfoResolver());
    });
```

Presumably this means use my serializer context for types I've listed and for any I haven't it falls back to reflection based which offers the same behaviour as NET6 (again near as I can tell)

**Comment by springy76** [comment]
This change by the way killed ANY USAGE of IAsyncEnumerable on the server side (controllers) when using AddContext<> - because always  the real object either is on anonymous hidden AsyncIteratorStateMachine attributed class or some internal class out of LINQ like `AsyncEnumerablePartition<T>` which I can't add as root to tje JsonSerializerContext derived class - GREAT WORK GUYS!

**Comment by eiriktsarpalis** [comment]
> And this JsonTypeInfoResolver.Combine thing not even helps here.

I would question that this is the case. Could you open a new issue with a reproduction?
