### ISSUE TITLE
[API Proposal]: Parity between Date-/TimeOnly And DateTime(Offset)

### ISSUE THREAD

**Issue by WhatzGames** [dotnet/runtime#77114]
### Background and motivation

The intention is to bring DateTime and DateTimeOffset more parity compared to DateOnly And TimeOnly.
This would provide more convenience for creating some custom behaviour like in [#2505](/npgsql/efcore.pg/issues/2505).

Edit:
For some more context: Postgres offers to_date (date is comparable to DateOnly) and to_timestamp (timestamp is comparable to DateTime/DateTimeOffset).
So the goal in the end is to map DateOnly.ParseExact(...) and DateTime.ParseExact(...) directly into their corresponding postgres translation.

### API Proposal

```csharp
namespace System;

public struct DateTime
{
  public static DateTime ParseExact(string s, string format);
  public static DateTime TryParseExact(string? s, string? format, out DateTime);
}

public struct DateTimeOffset
{
  public static DateTimeOffset ParseExact(string s, string format);
  public static DateTimeOffset TryParseExact(string? s, string?, out DateTimeOffset);
}
```

### API Usage

```csharp

string input = "01.01.2022";
string format = "dd.MM.yyyy";

DateTime dateTime = DateTime.ParseExact(input, format);
DateTimeOffset dateTimeOffset = DateTimeOffset.ParseExact(input, format);

if(DateTimeOffset.TryParseExact(input, format))
{
//Do Something
}

if(DateTime.TryParseExact(input, format))
{
//Do Something
}
```

### Risks

No Risks came to mind, since the behavior could just be the same as the DateOnly/TimeOnly implementations.

**Comment by tarekgh** [comment]
@WhatzGames I am seeing this is something nice to have but not necessarily needed. Why can't you always use the overload which takes `(string, string, IFormatProvider)` and pass `null` for the third parameter. You should be able to do so across `DateTime`, `DateTimeOffset`, and `DateOnly`. 

In general, I prefer users calling the overload that takes `IFormatProvider` to be conscious about the culture senstivity parsing.

**Comment by WhatzGames** [comment]
@tarekgh Yes it is a nice to have and I could/would probably do it the way you said, if this is not gonna work out. But then in that case I question myself, why DateOnly and TimeOnly do actually provide such a Method?

Providing the same APIs also provides consistency and clarity among the Datatypes that work on the same kind if Data, in this case: Date and Time.
And users can expect these APIs to behave the same as well.

**Comment by tarekgh** [comment]
> Providing the same APIs also provides consistency and clarity among the Datatypes that work on the same kind of Data, in this case: Date and Time.

This is true if the newly proposed API is desirable over other provided overloads. As I mentioned, I prefer to have the user pay attention to cultural parsing. We have been trying to direct users to pay attention to differentiate between the cultural and not cultural operations. 

> why DateOnly and TimeOnly do actually provide such a Method?

It was overlooking. If we thought more about it before exposing it, we wouldn't have it. It is not wise to expose more APIs with same concerns. 

 By that, I am closing this issue for the reason I mentioned. Feel free to send any more comments if you have any. Thanks for your report!
