### ISSUE TITLE
System.Text.RegularExpressions mono regressions

### ISSUE THREAD

**Issue by Jozkee** [dotnet/runtime#77129]
Found regressions on mono on benchmark `System.Text.RegularExpressions.Tests.Perf_Regex_Industry_BoostDocs_Simple.IsMatch(Id: 0, Options: Compiled)`

[Mono Ubuntu 18.04](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04_LLVM%3dfalse_MonoAOT%3dfalse_MonoInterpreter%3dfalse_RunKind%3dmicro_mono%2fSystem.Text.RegularExpressions.Tests.Perf_Regex_Industry_BoostDocs_Simple.IsMatch(Id%3a%200%2c%20Options%3a%20Compiled).html):

![newplot (4)](https://user-images.githubusercontent.com/16040868/196281927-a8c22d0f-ff3d-44f9-b3e1-376dca76e075.png)

[Ubuntu x64 Mono AOT](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04_LLVM%3dfalse_MonoAOT%3dtrue_MonoInterpreter%3dfalse_RunKind%3dmicro_mono%2fSystem.Text.RegularExpressions.Tests.Perf_Regex_Industry_BoostDocs_Simple.IsMatch(Id%3a%200%2c%20Options%3a%20Compiled).html):

![newplot (5)](https://user-images.githubusercontent.com/16040868/196282244-08112e87-f717-4f9c-869b-722392137d29.png)

[Ubuntu Arm64 Mono AOT](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_arm64_ubuntu%2018.04_LLVM%3dfalse_MonoAOT%3dtrue_MonoInterpreter%3dfalse_RunKind%3dmicro_mono%2fSystem.Text.RegularExpressions.Tests.Perf_Regex_Industry_BoostDocs_Simple.IsMatch(Id%3a%200%2c%20Options%3a%20Compiled).html)

![newplot (6)](https://user-images.githubusercontent.com/16040868/196282433-e52d8b2a-bad7-4a68-961c-d3aef1ff706e.png)

We've explained similar jumps on regex benchmarks with this reason https://github.com/dotnet/runtime/issues/65187#issuecomment-1036287653, @stephentoub @joperezr do you know if this has the same root casue or/if it can be explained as "By design" due to the number of regex changes of this release?

**Comment by stephentoub** [comment]
> We've explained similar jumps on regex benchmarks with this reason https://github.com/dotnet/runtime/issues/65187#issuecomment-1036287653, @stephentoub @joperezr do you know if this has the same root casue or/if it can be explained as "By design" due to the number of regex changes of this release?

I don't think so, and I don't see any relevant regex, string, span, etc. changes in the relevant window.

**Comment by stephentoub** [comment]
Non-actionable at this point.
