### ISSUE TITLE
System.ComponentModel.Win32Exception (0x80090308): The token supplied to the function is invalid" when TLS13 is enabled

### ISSUE THREAD

**Issue by ramsubbaraoc** [dotnet/runtime#77124]
After adding the below registry key to enable TLS1.3 on Windows Server 2022

```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Client]
"DisabledByDefault"=dword:00000000
"Enabled"=dword:00000001
```

The .NET 6.0 Client application throws the below exception

```
System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090308): The token supplied to the function is invalid
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)

```
Is there anything i am missing? In the .NET Client application i had set the protocol version to TLS13.

Thanks in advance.

**Comment by wfurt** [comment]
Can you do packet capture @ramsubbaraoc? Server 2022 should not need registry to do TLS 1.3 so it is surprising that made any difference. 

https://learn.microsoft.com/en-us/windows/win32/secauthn/protocols-in-tls-ssl--schannel-ssp-

Are you confident the peer can handle Tls 1.3? If you force it will fail if the peer is not willing/able to do it.

**Comment by ramsubbaraoc** [comment]
@wfurt Thank you very much for responding. Yes the peer supports TLS1.3.Yes i did a packet capture and after the Client Hello and Server Hello handshake, there was the "Change Cipher Spec" info sent by the Server, then the server has sent some "Application Data" to the client following which the client had thrown "Invalid Token" exception.

Earlier the server team told that the algorithms sent by the .NET Client doesn't have "RSA-PSS+SHA256" in its algorithm list. This was sometime back. When i had run recently i still see the same issue. The Windows registry contains the following algorithm list

```
RSAE-PSS/SHA256
RSAE-PSS/SHA384
RSAE-PSS/SHA512
RSA/SHA256
RSA/SHA384
RSA/SHA1
ECDSA/SHA256
ECDSA/SHA384
ECDSA/SHA1
DSA/SHA1
RSA/SHA512
ECDSA/SHA512

```

Is there a way i could send the packet capture securely to you? 

Thanks again for your help

**Comment by ramsubbaraoc** [comment]
I was able to successfully execute the same program on Linux. The difference i could find was the list of the supported algorithms

With Client running on Linux
                    ```
                    Signature Algorithm: ecdsa_secp256r1_sha256 (0x0403)
                    Signature Algorithm: ecdsa_secp384r1_sha384 (0x0503)
                    Signature Algorithm: ecdsa_secp521r1_sha512 (0x0603)
                    Signature Algorithm: ed25519 (0x0807)
                    Signature Algorithm: ed448 (0x0808)
                    Signature Algorithm: rsa_pss_pss_sha256 (0x0809)
                    Signature Algorithm: rsa_pss_pss_sha384 (0x080a)
                    Signature Algorithm: rsa_pss_pss_sha512 (0x080b)
                    Signature Algorithm: rsa_pss_rsae_sha256 (0x0804)
                    Signature Algorithm: rsa_pss_rsae_sha384 (0x0805)
                    Signature Algorithm: rsa_pss_rsae_sha512 (0x0806)
                    Signature Algorithm: rsa_pkcs1_sha256 (0x0401)
                    Signature Algorithm: rsa_pkcs1_sha384 (0x0501)
                    Signature Algorithm: rsa_pkcs1_sha512 (0x0601)
```

With Client running on Windows:

                  ```
                   Signature Algorithm: rsa_pss_rsae_sha256 (0x0804)
                    Signature Algorithm: rsa_pss_rsae_sha384 (0x0805)
                    Signature Algorithm: rsa_pss_rsae_sha512 (0x0806)
                    Signature Algorithm: rsa_pkcs1_sha256 (0x0401)
                    Signature Algorithm: rsa_pkcs1_sha384 (0x0501)
                    Signature Algorithm: rsa_pkcs1_sha1 (0x0201)
                    Signature Algorithm: ecdsa_secp256r1_sha256 (0x0403)
                    Signature Algorithm: ecdsa_secp384r1_sha384 (0x0503)
                    Signature Algorithm: ecdsa_sha1 (0x0203)
                    Signature Algorithm: SHA1 DSA (0x0202)
                    Signature Algorithm: rsa_pkcs1_sha512 (0x0601)
                    Signature Algorithm: ecdsa_secp521r1_sha512 (0x0603)
```

**Comment by wfurt** [comment]
.NET relies on capabilities of underlying OS e.g. Schannel or OpenSSL
Here is list of ciphers supported ciphers in s 2022
https://learn.microsoft.com/en-us/windows/win32/secauthn/tls-cipher-suites-in-windows-server-2022

To make it work, server would have to support at least one TLS 1.3 cipher from the list.

**Comment by ramsubbaraoc** [comment]
@wfurt Yes i had used TLS_AES_128_GCM_SHA256 cipher, the same cipher is set on the server as well. The server is same in both the cases. But for a Linux client(openssl config) it works fine,but for Windows client it fails.

Please can you suggest how do i debug it on Windows

**Comment by wfurt** [comment]
can you post complete captures for both cases @ramsubbaraoc? There may be other things besides the cipher. 
You can also verify this with `openssl s_client -connect www.github.com:443  -cipher TLS_AES_128_GCM_SHA256` to be sure.

**Comment by ramsubbaraoc** [comment]
@wfurt Thanks for your help. There was an issue at the server side because of which it wasn't working with the Windows Client. After the fix on the server side, the Windows Client was able to communicate successfully.
