### ISSUE TITLE
Assertion failed 'data->GetRegNum() != REG_ARG_0'

### ISSUE THREAD

**Issue by markples** [dotnet/runtime#77141]
runtime-coreclr libraries-pgo
Libraries Test Run checked coreclr Linux arm Release

This is pretty consistently failing in System.Runtime.Serialization.Xml.ReflectionOnly.Tests (4 out of last 5, in the other run #75827 hit)

```
+ printenv
+ grep COMPlus
COMPlus_TC_QuickJitForLoops=1
COMPlus_TieredCompilation=1
COMPlus_DbgMiniDumpName=/home/helixbot/dotnetbuild/dumps/coredump.%d.dmp
COMPlus_TieredPGO=1
COMPlus_DbgEnableMiniDump=1
...
  Starting:    System.Runtime.Serialization.Xml.ReflectionOnly.Tests (parallel test collections = on, max threads = 4)

Assert failure(PID 62 [0x0000003e], Thread: 69 [0x0045]): Assertion failed 'data->GetRegNum() != REG_ARG_0' in 'System.Runtime.Serialization.ReflectionClassWriter:ReflectionWriteClass(System.Runtime.Serialization.XmlWriterDelegator,System.Object,System.Runtime.Serialization.XmlObjectSerializerWriteContext,System.Runtime.Serialization.DataContracts.ClassDataContract,System.Xml.XmlDictionaryString[]):this' during 'Generate code' (IL size 100; hash 0xce1c5028; Tier1)

    File: /__w/1/s/src/coreclr/jit/codegenarm.cpp Line: 1340
    Image: /root/helix/work/correlation/dotnet
```
cc @dotnet/jit-contrib

**Comment by markples** [comment]
one example

https://dev.azure.com/dnceng-public/public/_build/results?buildId=54100&view=results

https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-92a91dbd8dad4d3ca9/System.Runtime.Serialization.Xml.ReflectionOnly.Tests/1/console.d60cdb0c.log?helixlogtype=result

**Comment by jakobbotsch** [comment]
I haven't seen this while monitoring this pipeline, so will remove blocking label.

**Comment by BrianBohe** [comment]
This just [happen yesterday again](https://dev.azure.com/dnceng-public/public/_build/results?buildId=119709&view=logs&j=d38c1e35-fd06-5dba-0f06-2e0807d50a53&t=d109a4a9-a295-5758-d174-129b1567dfb2). [Full log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-babdba34e6cc4e4984/System.Runtime.Serialization.Xml.ReflectionOnly.Tests/1/console.7158ac08.log?helixlogtype=result).

**Comment by jakobbotsch** [comment]
Will unmark this a blocking again... I was able to reproduce this back then, but only once, and I did not manage to capture enough information to get to the bottom of the issue. I will try again once/if we see this again (so I can get the bits from helix).
