### ISSUE TITLE
[pgo] Assert failure: (pCtx->Pc < codestart) || (pCtx->Pc >= codeend)

### ISSUE THREAD

**Issue by markples** [dotnet/runtime#77156]
runtime-coreclr pgo
coreclr Pri1 Runtime Tests Run windows arm checked

https://dev.azure.com/dnceng-public/public/_build/results?buildId=54029&view=logs&j=eda44ab5-7cb6-5671-b837-8dd5eacc7454&t=a8961235-5e03-5321-0061-4ab51c2c5bc2
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-03717c5a723446f6a0/JIT.Regression.JitBlue/1/console.86671ea5.log?helixlogtype=result

```
    JIT\Regression\JitBlue\GitHub_27924\GitHub_27924\GitHub_27924.cmd [FAIL]
      
      Assert failure(PID 3484 [0x00000d9c], Thread: 14568 [0x38e8]): (pCtx->Pc < codestart) || (pCtx->Pc >= codeend)
      
      <no module>! <no symbol> + 0x0 (0x00000000)
          File: D:\a\_work\1\s\src\coreclr\vm\arm\singlestepper.cpp Line: 370
          Image: D:\h\w\A175099F\p\corerun.exe
```
cc @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
FYI this test runs under GCStress=0xC. Seems a bit odd we'd have a normal test that enables GC stress but evidently, we do.

**Comment by BruceForstall** [comment]
> FYI this test runs under GCStress=0xC. Seems a bit odd we'd have a normal test that enables GC stress but evidently, we do.

fwiw, I noticed this once before and thought it was odd, but then again, it's useful to have a GCStress smoke test run every PR (or outerloop)

**Comment by EgorBo** [comment]
Didn't see it in last 5 runs, will re-open if it shows up again
