### ISSUE TITLE
MediaTypeHeaderValue.Parse throws FormatException with null string

### ISSUE THREAD

**Issue by dduede** [dotnet/runtime#77160]
Hey,
I'm not sure if this should be classified as a bug or documentation error or simply a misunderstanding of nullable.

The api documentation in Visual Studio for the `MediaTypeHeaderValue.Parse` Method shows the following signature:
![image](https://user-images.githubusercontent.com/57986566/196402940-97849a2b-ca41-41ad-9171-b10bf13f316d.png)
If I understand this correctly, the `input` string is allowed to be null as indicated by the `?` at the end of the type (nullable string).
When passing a null string into the `Parse` method, it throws a `System.FormatException` with the message `The format of value '<null>' is invalid.`.

I'm fine with it throwing this exception, since there is no good return value - but the method signature is misleading since it suggests `null` is a valid value.

Am I missing something here or am I misunderstanding how nullable should be interpreted by developers?

Dotnet 6.0.402
Visual Studio 17.3.6

**Comment by MihaZupan** [comment]
All `*HeaderValue` types (except `CacheControlHeaderValue`) will throw for `Parse(null)`.

I don't see a good reason these should be annotated as nullable, though fixing it may be noisy for users.

**Comment by MihaZupan** [comment]
Triage: We believe the current annotations are wrong and we'd take a change to correct them (all values except for `CacheControl`). Moving this to future and marking as up-for-grabs.
