### ISSUE TITLE
Interface Promise Comments! [API Proposal]: 

### ISSUE THREAD

**Issue by Asivaprasadam** [dotnet/runtime#77179]
### Background and motivation

Interface Implementation supports auto-complete of function with function subs containing
` throw new NotImplementedException();` 
The request is for a new feature, where the feature allows adding comments to interface stubs, which will be available during the auto-implementation of the body of the function.

### API Proposal

```csharp

public interface IMyInterface 
{
       public void MyMethod() 
      {
            // TODO - Add this functionality to this stub...
      }
}
```

### API Usage

```csharp

// Auto Implement auto-completes the function with the comments from the interface function stub.
public class MyClass : IMyInterface
{
      public void MyMethod()
      {
            // TODO - Add this functionality to this stub...
            
            throw new NotImplementedException();
      }
}
```

**Comment by teo-tsirpanis** [comment]
Closing, this is not a proposal for a new API in the BCL. I'm not sure where this issue belongs though. 🤔

**Comment by svick** [comment]
> I'm not sure where this issue belongs though. 🤔

Technically, it's proposing a language feature, which would belong on [the csharplang repo](https://github.com/dotnet/csharplang/). But I think it's very unlikely that the language would be changed just to slightly improve one refactoring, so I suggest changing the syntax to something that's valid code today, e.g.:

```c#
public interface IMyInterface 
{
        //! TODO - Add this functionality to this stub...
        public void MyMethod();
}
```

Then the refactoring could be changed without having to change the language, and such a request would belong on [the roslyn repo](https://github.com/dotnet/roslyn). And even if this suggestion wasn't accepted, I think that's also the right place to discuss how you could do this yourself.

**Comment by Asivaprasadam** [comment]
Perfect! I wasn't quite sure where this belongs, and that confusion lead me to reopen the closed issue. I got this hacked and working through XML documentation comments.
