### ISSUE TITLE
Lack of CS0165 (Use of unassigned local variable) for DateOnly and TimeOnly types

### ISSUE THREAD

**Issue by Wojmik** [dotnet/runtime#77177]
**Version Used**:
.Net 6. Visual Studio 17.3.6.

**Steps to Reproduce**:

```C#
DateOnly date;
TimeOnly time;

Console.WriteLine(date);//Lack of CS0165 - unassigned local variable
Console.WriteLine(time);//Same here
```

**Expected Behavior**:
You should have CS0165 error (Use of unassigned local variable).
If you change a type to e.g. DateTime, the error appears like it should.

**Actual Behavior**:
No error, you can compile and run it.

**Comment by tarekgh** [comment]
This is fixed in .NET `7.0`. Please try it and let's know if you still see the problem there. Thanks for your report.
