### ISSUE TITLE
System.Threading.RateLimiting Rate Limiting internal queue does not check the queued request status while replenishment process

### ISSUE THREAD

**Issue by AliKhalili** [dotnet/runtime#77180]
### Description

`System.Threading.RateLimiting` limiter's algorithms are using an internal queue, for queueing async acquire permit requests.
In the replenishment process, the rate limiter tries to gain a lease for the queued request without considering their request status. Sometimes the client can cancel a queued lease request with a specific permit count, and on the replenishment, the limiter needs to check the status of the request before examining the following line:
```c#
// If we have enough permits after replenishing to serve the queued requests
if (_permitCount >= nextPendingRequest.Count)
{
   ...
}
```

For fixing this issue, we need to check the task status and in case it was canceled, it should be removed from the queue.
```c#
if (nextPendingRequest.Tcs.Task.IsCompleted)
{
    nextPendingRequest = _options.QueueProcessingOrder == QueueProcessingOrder.OldestFirst
    ? _queue.DequeueHead()
        : _queue.DequeueTail();
}
// If we have enough permits after replenishing to serve the queued requests
else if (_permitCount >= nextPendingRequest.Count)
{
   ...
}
```

### Reproduction Steps

We can apply the following scenario on the sliding window, token bucket, concurrency algorithms.
```c#
var limiter = new ConcurrencyLimiter(new ConcurrencyLimiterOptions
{
    PermitLimit = 3,
    QueueProcessingOrder = QueueProcessingOrder.OldestFirst,
    QueueLimit = 3,
});

var request1 = limiter.AttemptAcquire(2);
var request2 = limiter.AttemptAcquire(1);

var cts = new CancellationTokenSource();
var request3 = limiter.AcquireAsync(3, cts.Token);
cts.Cancel();

var request4 = limiter.AcquireAsync(2);

request1.Dispose();
lease = await request4; // lease should be acquired but wait on the queue
```
![image](https://user-images.githubusercontent.com/524539/196512264-2bd30c68-99f8-47e9-bc93-05dadfdf118f.png)

### Expected behavior

Request4 should be able to acquire log after disposing of request 1.

### Actual behavior

Request4 waits on the queue.

**Comment by BrennanConroy** [comment]
Great issue write-up, thanks for fixing this!
