### ISSUE TITLE
make GC's PAL implementation include the right dump info

### ISSUE THREAD

**Issue by Maoni0** [dotnet/runtime#77184]
since we want to use GC's [own PAL impl for all GC build flavors](https://github.com/dotnet/runtime/issues/72684) I took a look at it to see if there's any gaps. the only gap seems to be the dump info where we call `madvise` to include committed memory (`MADV_DODUMP`) and exclude reserved/reset memory (`MADV_DONTDUMP`). after we add those calls we should be good to go. 

CC @janvorli @mangod9

**Comment by mangod9** [comment]
I have added a call to `madvise` here: https://github.com/dotnet/runtime/pull/76985/commits/a585fc3a0df6c4da8eeae64911374dc1855c7f3a. Dont believe `MADV_DONTDUMP` is required for the GC case. @janvorli ?

**Comment by mangod9** [comment]
Oh I guess its required for the reserve case. Will update.

**Comment by mangod9** [comment]
have updated the PR to include the `MADV_DONTDUMP` though `VirtualDecommit` seems to need more changes as mentioned here: https://github.com/dotnet/runtime/pull/76985#discussion_r999812402

**Comment by Maoni0** [comment]
fixed by [76985](https://github.com/dotnet/runtime/pull/76985)
