### ISSUE TITLE
Immutable base type

### ISSUE THREAD

**Issue by BoysheO** [dotnet/runtime#77195]
Today,we have record,readonly,ImmutableArray...but why we do not have any base type immutable?
see:
```
        public static void Test(IList<int> immutable)
        {
            int count = immutable.Count;
            count++;//coder make mistake
            for (int i = 0; i < count; i++)
            {
                var item = immutable[i];
                Debug.Log(item);
            }
        }
```
If I have a base type like 'imint',mistake can be stop while coding.

**Comment by eiriktsarpalis** [comment]
All immutable list-like types should implement [`IReadOnlyList<T>`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.ireadonlylist-1?view=net-6.0). I believe that abstraction should cover your use case.

**Comment by huoyaoyuan** [comment]
See also the discussion about immutable instances at https://github.com/dotnet/csharplang/discussions/421 .

**Comment by BoysheO** [comment]
The point is about immutable base type.We can't stop coder change the base type.Is not about collection,immutable keyword or immutable object.

**Comment by eiriktsarpalis** [comment]
In that case I might not be understanding what you are proposing. Some further examples might help.

**Comment by BoysheO** [comment]
The [Discussion](https://github.com/dotnet/csharplang/issues/188)  is more closer what I want.The different point is about keep the base value immutable when it copy as a new value.
see
```
imint Id = 1;//imint is a new type,not a keyword.
var id2 = Id;//type of 'id2' is imint
var id3 = Id + 1;//type of `id3` is imint
id2++;//IDE can notify coder making a mistake
id3++;//mistake
```
If I want a mutable value,I can code this:
```
imint Id = 1;
int a = Id + 0;
a++;//ok
```
or
```
imint Id = 1;
var a = 2;//typeof a is int
var b = Id + a;//typeof b is int
```
This future will be very useful.

This issue will be close and I move to [The Discussion](https://github.com/dotnet/csharplang/issues/188)~

**Comment by eiriktsarpalis** [comment]
Yes, this is clearly something that should be addressed at the language level rather than runtime libraries.
