### ISSUE TITLE
[NETSDKE2E] With .NET 7.0.100 GA installed, the CoreCLR symbols are missing for IL symbols 

### ISSUE THREAD

**Issue by WenJunJi01** [dotnet/runtime#77207]
### Description

**Affected Build:** 
VS Enterprise 2022 Preview: Version 17.4.0 Preview 4.0 [33018.223.d17.4]
.NET 7 GA SDK 7.0.100(runtime-7.0.0)

### Reproduction Steps

Testing on Windows with VS -
1.	Goto Tools -> options -> Debugging
Under General
a. Uncheck 'Enable Just My Code'
b. Check 'Suppress JIT optimization on module load (Managed only)'
Under Symbols
a. Check 'Microsoft Symbol Servers'
2.	Create a new ASP.NET Razor project by doing
mkdir razor
cd razor
dotnet new razor
3.	Double click on the ‘Startup.cs’ file in the ‘Explorer’ pane to bring up that source code.
4.	Add the following line to the Startup.cs file at the beginning of the ‘Configure’ method (at the bottom of the file). When using VS, you can add this line of code on Program.cs file
Console.WriteLine("x " + 3);
5.	Place a breakpoint on that line (F9).
6.	Run the application until it hit that breakpoint (F5). It will load symbols from the Microsoft symbol server, and may take a few seconds to hit the breakpoint. You should see 20-30 lines of ‘Loaded XXX Symbols loaded’.
7.	Step into the concatination method (F11). Select 'Download Source and Continue Debugging' from the popup
This tests CoreCLR symbols AT THIS POINT IT SHOULD SHOW YOU THE SOURCE CODE FOR Concat().

### Expected behavior

CoreCLR symbols are displayed in step7.

### Actual behavior

CoreCLR symbols are missing in step7.
![image](https://user-images.githubusercontent.com/87680983/196651713-6bab2365-e7a9-40e9-b273-fe8c79b6dd6c.png)

**Dotnet info:**
.NET SDK:
Version:   7.0.100
Commit:    7d9eddf1c0

Runtime Environment:
OS Name:     Windows
OS Version:  10.0.22621
OS Platform: Windows
RID:         win10-x64
Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       bebb59597c

.NET SDKs installed:
  7.0.100-rc.2.22477.23 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-rc.2.22476.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-rc.2.22472.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-rc.2.22472.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by NikolaMilosavljevic** [comment]
[Triage] @rbhanda @mmitche is this expected to work right now, for release candidate build?

**Comment by mmitche** [comment]
Shouldn't work except if using internal symbol servers.

**Comment by NikolaMilosavljevic** [comment]
By design.
