### ISSUE TITLE
Implement the logic to support SoftwareWriteWatch in NativeAOT

### ISSUE THREAD

**Issue by cshung** [dotnet/runtime#77225]
Right now, we are building Windows NativeAOT without `FEATURE_MANUALLY_MANAGED_CARD_BUNDLES ` and `FEATURE_USE_SOFTWARE_WRITE_WATCH_FOR_GC_HEAP` defined. 

Short term, this configuration exposed a bug in the implementation causing #76801

Long term, it would be a good idea to turn them on so that we can eventually get rid of the code.

**Comment by jkotas** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/75110
