### ISSUE TITLE
Create the published AppBundle for a WebAssembly Browser App in the publish folder

### ISSUE THREAD

**Issue by danroth27** [dotnet/runtime#77222]
When you publish a WebAssembly Browser App it creates an AppBundle folder with all the files that need to be deployed. It looks like the AppBundle folder is created as a sibling to the publish folder instead of as a subfolder of the publish folder, which is a bit odd. It made me second guess if it was the actual published AppBundle or not. Consider creating the published AppBundle folder as a subfolder of the publish folder.

**Comment by radical** [comment]
The reason for this right now is that the wasm targets are essentially running "after publish", and then produce a self-contained `AppBundle`. And the contents of `publish/` are not needed for deployment.

But I agree that we should change this, because it is confusing.

**Comment by maraf** [comment]
This is resolved with migration to WasmSDK
