### ISSUE TITLE
IDBFS NOT FOUND ISSUE again

### ISSUE THREAD

**Issue by sajjadarashhh** [dotnet/runtime#77235]
### Description

when i migrate from .net 7 preview 7 to .net 7 rc2 i getting this problem that : window.Module.Fs.filesystems.IDBFS is undefined

### Reproduction Steps

expected in #74664

### Expected behavior

expected in #74664

### Actual behavior

expected in #74664

**Comment by pavelsavara** [comment]
Most likely this is just typo in your code. Case matters in JS, please use uppercase `FS` as in `Module.FS.filesystems.IDBFS`

![image](https://user-images.githubusercontent.com/271576/196872561-00fe1810-a4d8-4d50-94cb-800123424643.png)

**Comment by sajjadarashhh** [comment]
no my problem not solved by this!
i test window.Module.FS.filesystems.IDBFS and  Module.FS.filesystems.IDBFS theres undefined

**Comment by sajjadarashhh** [comment]
@pavelsavara

**Comment by sajjadarashhh** [comment]
![Uploading image.png…]()
![Uploading image.png…]()
