### ISSUE TITLE
[release/3.1] CI Failure: System.Diagnostics.EventLog

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#77234]
Two tests consistently fail in 3.1 PRs.

- System.Diagnostics.Tests.ProviderMetadataTests.ProviderNameTests(true|false)
- System.Diagnostics.Tests.EventLogRecordTests.ExceptionOnce()

Considering 3.1 will be out of support after December, we might just leave these two tests disabled since a fix might be external and/or will probably not meet the bar.

- OS: Windows 10
- Queue: `Build arm64_Release`
- Log file: https://helixri107v0xdeko0k025g8.blob.core.windows.net/dotnet-corefx-refs-pull-26813-merge-b0be4cfe46fb4271ab/System.Diagnostics.EventLog.Tests/1/console.b1e3e2e9.log?sv=2021-08-06&se=2023-01-17T01%3A16%3A32Z&sr=c&sp=rl&sig=Dnp7Y1nNsE0VYBaBR%2BSWe8o%2B9Da3e%2FUY%2FMrBgGIAVfY%3D
- Callstack examples:

<details>
<summary>ProviderNameTest</summary>

The code that fails is the p/invoke to Windows to retrieve the event enum via `EvtOpenEventMetadataEnum`:
- https://github.com/dotnet/corefx/blob/227d834f25498c8a2c1802fe6185765c338b89d5/src/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/UnsafeNativeMethods.cs#L533
- Documentation: 
- https://learn.microsoft.com/en-us/windows/win32/api/winevt/nf-winevt-evtopeneventmetadataenum

The passed handle was previously filled out in the constructor, via `EvtOpenPublisherMetadata`:
- https://github.com/dotnet/corefx/blob/227d834f25498c8a2c1802fe6185765c338b89d5/src/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/UnsafeNativeMethods.cs#L494
- Documentation: https://learn.microsoft.com/en-us/windows/win32/api/winevt/nf-winevt-evtopenpublishermetadata

```
System.Diagnostics.Tests.ProviderMetadataTests.ProviderNameTests(noProviderName: True) [FAIL]
      System.Diagnostics.Eventing.Reader.EventLogNotFoundException : The system cannot find the file specified.
      Stack Trace:
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/EventLogException.cs(47,0): at System.Diagnostics.Eventing.Reader.EventLogException.Throw(Int32 errorCode)
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/ProviderMetadata.cs(511,0): at System.Diagnostics.Eventing.Reader.ProviderMetadata.get_Events()
        /_/src/System.Diagnostics.EventLog/tests/System/Diagnostics/Reader/ProviderMetadataTests.cs(40,0): at System.Diagnostics.Tests.ProviderMetadataTests.ProviderNameTests(Boolean noProviderName)
    System.Diagnostics.Tests.ProviderMetadataTests.ProviderNameTests(noProviderName: False) [FAIL]
      System.Diagnostics.Eventing.Reader.EventLogNotFoundException : The system cannot find the file specified.
      Stack Trace:
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/EventLogException.cs(47,0): at System.Diagnostics.Eventing.Reader.EventLogException.Throw(Int32 errorCode)
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/ProviderMetadata.cs(511,0): at System.Diagnostics.Eventing.Reader.ProviderMetadata.get_Events()
        /_/src/System.Diagnostics.EventLog/tests/System/Diagnostics/Reader/ProviderMetadataTests.cs(40,0): at System.Diagnostics.Tests.ProviderMetadataTests.ProviderNameTests(Boolean noProviderName)
```
</details>

<details>
<summary>ExceptionOnce</summary>

Similar to the other issue, it fails in the P/Invoke to Windows `EvtFormatMessage` via:
- https://github.com/dotnet/corefx/blob/227d834f25498c8a2c1802fe6185765c338b89d5/src/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/UnsafeNativeMethods.cs#L705
- Documentation: https://learn.microsoft.com/en-us/windows/win32/api/winevt/nf-winevt-evtformatmessage

```
    System.Diagnostics.Tests.EventLogRecordTests.ExceptionOnce [FAIL]
      System.Diagnostics.Eventing.Reader.EventLogException : The specified resource type cannot be found in the image file.
      Stack Trace:
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/EventLogException.cs(47,0): at System.Diagnostics.Eventing.Reader.EventLogException.Throw(Int32 errorCode)
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/NativeWrapper.cs(934,0): at System.Diagnostics.Eventing.Reader.NativeWrapper.EvtFormatMessageRenderName(EventLogHandle pmHandle, EventLogHandle eventHandle, EvtFormatMessageFlags flag)
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/ProviderMetadataCachedInformation.cs(221,0): at System.Diagnostics.Eventing.Reader.ProviderMetadataCachedInformation.GetLevelDisplayName(String ProviderName, EventLogHandle eventHandle)
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/EventLogRecord.cs(320,0): at System.Diagnostics.Eventing.Reader.EventLogRecord.get_LevelDisplayName()
        /_/src/System.Diagnostics.EventLog/tests/System/Diagnostics/Reader/EventLogRecordTests.cs(101,0): at System.Diagnostics.Tests.EventLogRecordTests.<>c__DisplayClass4_0.<ExceptionOnce>b__0()
        /_/src/System.Diagnostics.EventLog/tests/System/Diagnostics/Reader/EventLogRecordTests.cs(115,0): at System.Diagnostics.Tests.EventLogRecordTests.ThrowsMaxOnce[T](Action action)
        /_/src/System.Diagnostics.EventLog/tests/System/Diagnostics/Reader/EventLogRecordTests.cs(101,0): at System.Diagnostics.Tests.EventLogRecordTests.ExceptionOnce()
```
</details>

**Comment by ericstj** [comment]
@carlossanlop can you take a look at this when you have a chance and decide if we need to do anything?

**Comment by ViktorHofer** [comment]
Given that 3.1 is already out-of-support and we deleted its publish branch I vote for closing the issue.

**Comment by ericstj** [comment]
Closing this - we should strive for a clean CI in our active servicing branches.  If any tests are failing in servicing let's make sure we follow the CI Known Issue Report process to record them.
