### ISSUE TITLE
Fix CacheEntryExtensions.SetValue()'s signature to allow null values

### ISSUE THREAD

**Issue by kevinchalet** [dotnet/runtime#77264]
While `ICacheEntry.Value`'s signature allows null values, `CacheEntryExtensions.SetValue()` doesn't, which forces using the null forgiving operator on .NET 7.0. I suspect it's just an oversight so it's likely something that should be easy to fix in 7.0 RTM.

https://github.com/dotnet/runtime/blob/24813dc41dd3d573458e710292a109f8ffa4f415/src/libraries/Microsoft.Extensions.Caching.Abstractions/src/CacheEntryExtensions.cs#L121-L133

(discovered while testing OpenIddict on .NET 7.0: https://github.com/openiddict/openiddict-core/pull/1545/files#diff-34b88d587f9dab7cd5fc8458b9e228b3ba4b5a104edeb5a04050ac53fe7a8d54R295)

**Comment by tarekgh** [comment]
@eerhardt what you think about this one?

**Comment by eerhardt** [comment]
This looks like an oversight in https://github.com/dotnet/runtime/pull/64018.  Thoughts @maxkoshevoi?

**Comment by maxkoshevoi** [comment]
Hm, if I specified that `ICacheEntry.Value` is nullable, there must've been a reason for it. Possibly some implementation(s) of `ICacheEntry` (in different project) sets it to `null`. 
In any case this should be easy to figure out by just making `ICacheEntry.Value` non-nullable, and building the solution. 
I'll be able to do this tomorrow

**Comment by kevinchalet** [comment]
@maxkoshevoi `ICacheEntry.Value` is perfectly fine: `null` values have always been supported and there's no reason to change that.

This ticket is about the `CacheEntryExtensions.SetValue(object value)` helper, that also allows `null` value at runtime (since there's no null-checks), but hasn't been updated to declare `value` as nullable. In other words, it should be declared as `public static ICacheEntry SetValue(this ICacheEntry entry, object? value)` instead of `public static ICacheEntry SetValue(this ICacheEntry entry, object value)`.

**Comment by maxkoshevoi** [comment]
> This ticket is about the `CacheEntryExtensions.SetValue(object value)` helper, that also allows `null`

Oh, sorry, misread that 😅 Yeah, this can totally be an oversight. If it makes sense to allow setting `null` cache values, I'm ok with the change. 
Guess, my thought process was that we can `get` null values (since they might not exist), and `ICacheEntry` with null `Value` might represent non-existant entry or something, so `setting` null might not be ok. In any case, there no null-checks in `SetValue` and if people do it in the wild, `value` should definitely be nullable.

**Comment by tarekgh** [comment]
@kevinchalet we'll fix this in .NET 8.0 as we already done with .NET 7.0. Is this something blocking you or is it ok to wait?

**Comment by tarekgh** [comment]
@maxkoshevoi are you interested to submit a PR to fix the issue?

**Comment by kevinchalet** [comment]
Nothing blocking, I can live with a few additional `!` 😄 
That said, since it's literally a one-char change, I thought it could be included in RTM. But if it can't be, no big deal.

**Comment by maxkoshevoi** [comment]
> @maxkoshevoi are you interested in submitting a PR to fix the issue? 

Sure, I'll do it first thing tomorrow

**Comment by tarekgh** [comment]
> Hm, why then SetSlidingExpiration, and SetAbsoluteExpiration don't accept nulls? (their parameters are value types, so it's not a nullability oversight)

Yes, it is because is a value type and changed that will change the method signature. I don't think we can accept this kind of breaking. By the way, the same note applies to all methods taking value types (`SetSize`, SetAbsoluteExpiration,...)` too.

**Comment by maxkoshevoi** [comment]
@tarekgh @eerhardt Yes, my point was, why it was designed from the beginning to not accept nulls?

> The backing properties are nullable - null meaning they haven't been set yet. The intuition is that if you are setting these values, you are providing a value, and not setting them to null. If they are already set, and you want to null them out, just set the properties.

This is what I also was thinking about, but why the logic for `SetValue` should be different?

**Comment by eerhardt** [comment]
> but why the logic for SetValue should be different?

1. Because caching `null` is valid. It isn't "unsetting" the value. It is setting the value explicitly to `null`.
2. Because it is a reference type - `object`.
