### ISSUE TITLE
Published Browser-Wasm with optimization and trimming enabled works on chrome but not safari

### ISSUE THREAD

**Issue by danwalmsley** [dotnet/runtime#77271]
### Description

Deployed a browser-wasm app using net7 rc2.

Available here: https://play.avaloniaui.net/

edge, chrome, firefox all run, but safari gives:

![telegram-cloud-photo-size-4-5947162110519785859-y](https://user-images.githubusercontent.com/4672627/196994414-1f869152-5f9f-4d0a-b219-ea80f419e2b0.jpg)

### Reproduction Steps

repo can be cloned and build from here: src/xamlplayground.wasm, dotnet publish -c Release.. then open in safari.
https://github.com/avaloniaui/xamlplayground

### Expected behavior

no issue.

### Actual behavior

doesnt run

**Comment by danwalmsley** [comment]
more information: I turned off optimisations, and trimming:

[Error] Unhandled Promise Rejection: LinkError: import function env:_ZNKSt3__220__vector_base_commonILb1EE20__throw_length_errorEv must be callable
	(anonymous function) (dotnet.js:5:46724)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob

**Comment by danwalmsley** [comment]
<WasmEnableSIMD>true</WasmEnableSIMD>

was the cause, docs say not supported on Safari.

**Comment by radical** [comment]
@pavelsavara @radekdoulik do you we know why it fails like this on Safari? What is the real underlying error here?

**Comment by pavelsavara** [comment]
Safari doesn't support the instructions yet.
https://bugs.webkit.org/show_bug.cgi?id=222382

**Comment by radical** [comment]
ok! Can we log an error if we have simd enabled during the build, and are running on Safari? Log an error, and maybe even cancel rest of the loading?

**Comment by pavelsavara** [comment]
wasm feature detection is way to go https://web.dev/webassembly-feature-detection/
