### ISSUE TITLE
`perf-pipeline` broken because of `Signature not valid in the specified time frame:`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#77278]
The results are failing to upload because of an expired certificate (?). [Build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2025805&view=logs&j=10348dd7-5cd6-5c42-fc55-e890e0795f10&t=3fe50c48-466c-5f5d-0411-aa33700b2a9d):

```xml
Srrver failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. 
RequestId:... 
Time:2022-10-20T11:52:19.6212166Z

Signature not valid in the specified time frame:
            Start [Wed, 20 Oct 2021 18:07:04 GMT] - Expiry [Thu, 20 Oct 2022 02:07:04 GMT]
               - Current [Thu, 20 Oct 2022 11:52:19 GMT]
```

cc @DrewScoggins @LoopedBard3 @adamsitnik @lewing @steveisok 

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by lewing** [comment]
cc @sblom

**Comment by LoopedBard3** [comment]
Working on this.

**Comment by LoopedBard3** [comment]
Already seeing green again for a Linux test run. Will report back once windows is showing proper uploading.

**Comment by LoopedBard3** [comment]
Windows is also coming back green, uploads should succeed now.

**Comment by radical** [comment]
Closing as this is fixed now. Thank you, @LoopedBard3 !
