### ISSUE TITLE
System.Speech NuGet package for .NET Standard target?

### ISSUE THREAD

**Issue by MaxWang-MS** [dotnet/runtime#77292]
### Description

Hi there! I am trying to get the `System.Speech` API to work inside the Unity game engine. The most viable path seems to be leveraging the System.Speech NuGet package and include the DLL targeting .NET standard in Unity. However, apparently all DLLs in the lib folder of the NuGet packages are just facades and the "real" ones are in the runtime folder. However, those DLLs inside the runtime folder either target .NET Core or .NET 6+.

### Reproduction Steps

Go to the runtime folder and note there is no DLL targeting .NET standard

### Expected behavior

I am hoping to get a "real" DLL targeting .NET Standard.

### Actual behavior

There is only a facade DLL for .NET Standard in the lib folder.

**Comment by ericstj** [comment]
System.Speech was brought back for compatibility with .NETFramework apps moving to .NET (Core).  It's implementation remains largely untouched from .NETFramework - it depends on types not present in .NETStandard as well as [Windows-specific APIs](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/ee125663(v=vs.85)).  Porting it to a cross-platform netstandard2.0 implementation is not planned.

This was discussed in the original issue which brought System.Speech sources back.  Have a look at https://github.com/dotnet/runtime/issues/46730#issuecomment-743554414.
