### ISSUE TITLE
arm64 altjit and HW intrinsics

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#77294]
Recently changes (https://github.com/dotnet/runtime/pull/75912) allow hardware intrinsics to work with altjit. However, it looks like there are still cases where the generated code is different.

E.g.,
```
    [MethodImpl(MethodImplOptions.NoInlining)]
    public static Vector128<byte> TestHva(hva2 h1, hva2 h2)
    {
        return Vector128.Add<byte>(h1.hf1, h2.hf2);
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    public static Vector128<byte> TestVector128Args(Vector128<byte> a, Vector128<byte> b)
    {
        return Vector128.Add<byte>(a, b);
    }

    public static Vector128<byte> Test()
    {
        Vector128<byte> a = default, b = default;
        Vector128<byte> x = TestVector128Args(a, b);

        hva2 h1 = default, h2 = default;
        Vector128<byte> y = TestHva(h1, h2);

        return Vector128.Add(x, y);
    }
```
Under altjit (using Disasmo), in `Test`, the first call passes args in vector registers, the 2nd passes on the stack:
```
        4F000400          movi    v0.4s, #0
        4F000401          movi    v1.4s, #0
        D29FC800          movz    x0, #0xFE40      // code for Program:TestVector128Args
        F2A5EF20          movk    x0, #0x2F79 LSL #16
        F2CFFF00          movk    x0, #0x7FF8 LSL #32
        F9400000          ldr     x0, [x0]
        D63F0000          blr     x0
        4EA01C08          mov     v8.16b, v0.16b
        4F000410          movi    v16.4s, #0
        3D800FB0          str     q16, [fp, #0x30]
        4F000410          movi    v16.4s, #0
        3D8013B0          str     q16, [fp, #0x40]
        4F000410          movi    v16.4s, #0
        3D8007B0          str     q16, [fp, #0x10]
        4F000410          movi    v16.4s, #0
        3D800BB0          str     q16, [fp, #0x20]
        9100C3A0          add     x0, fp, #48
        910043A1          add     x1, fp, #16
        D29FC502          movz    x2, #0xFE28      // code for Program:TestHva
        F2A5EF22          movk    x2, #0x2F79 LSL #16
        F2CFFF02          movk    x2, #0x7FF8 LSL #32
        F9400042          ldr     x2, [x2]
        6E084509          mov     v9.d[0], v8.d[1]
        D63F0040          blr     x2
```
Using crossgen, the second call is via vector registers due to each argument being an HVA:
```
        4F000401          movi    v1.4s, #0
        4F000400          movi    v0.4s, #0
        9000000B          adrp    x11, [HIGH RELOC #0x40000000004202e0]      // function address
        9100016B          add     x11, x11, [LOW RELOC #0x40000000004202e0]
        F9400160          ldr     x0, [x11]
        D63F0000          blr     x0
        4EA01C08          mov     v8.16b, v0.16b
        4F000402          movi    v2.4s, #0
        4F000403          movi    v3.4s, #0
        4F000400          movi    v0.4s, #0
        4F000401          movi    v1.4s, #0
        9000000B          adrp    x11, [HIGH RELOC #0x40000000004202e8]      // function address
        9100016B          add     x11, x11, [LOW RELOC #0x40000000004202e8]
        6E084509          mov     v9.d[0], v8.d[1]
        F9400160          ldr     x0, [x11]
        D63F0000          blr     x0
```

@tannergooding @kunalspathak

**Comment by jkotas** [comment]
> However, it looks like there are still cases where the generated code is different.

altjit is not designed to have 100% fidelity. You are always going to have cases where the code generated with altjit is different from the code generated natively.

**Comment by BruceForstall** [comment]
> altjit is not designed to have 100% fidelity. You are always going to have cases where the code generated with altjit is different from the code generated natively.

I would refine this to say, we would like it to be as close to 100% fidelity as we can make it. We've made various changes over the years to improve it. It seems like perhaps we should consider making the altjit hard fail or otherwise indicate cases where we can determine it is not 100% fidelity, if possible.

It turns out I use altjit much less than before because we have true cross-compilers, and crossgen2 that uses them, but also, mostly, because we can use those cross compilers to replay native SuperPMI collections.

**Comment by tannergooding** [comment]
One common issue here is mismatching corelib

Since we trim and the IsSupported checks for “mismatched” platforms are treated as constant false as part of trimming, things won’t line up

**Comment by BruceForstall** [comment]
Related: https://github.com/dotnet/runtime/issues/38980

**Comment by BruceForstall** [comment]
I'm going to close this as I don't see us ever fixing it.
