### ISSUE TITLE
[wasm[debugger] Support `DebuggerTypeProxyAttribute(string)`

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#77315]
We have support only for `DebuggerTypeProxyAttribute(Type)`.

We are missing support for this overload:
https://github.com/microsoft/referencesource/blob/master/mscorlib/system/diagnostics/debuggerattributes.cs#L178

Where to start the fix:
https://github.com/dotnet/runtime/blob/50f7ab606775184eeb6d1a7eeb6e5c4e7814ef24/src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs#L2170

**Comment by ilonatommy** [comment]
When we enable `ElementType.String`
```
if ((ValueTypeId)monoParamTypeId != ValueTypeId.Type && (ElementType)monoParamTypeId != ElementType.String)
{
                    logger.LogDebug($"DebuggerTypeProxy attribute is only supported with a System.Type or System.String parameter type. Got {(ValueTypeId)monoParamTypeId}");
                    return -1;
}
```
We can see that for ProxyAttribute constructed with a string:

```
    // added this to debugger-custom-view-test.cs:
    [DebuggerTypeProxy("DebuggerTests.TheProxy")]
    class WithProxyConstructedByString
    {
        public string Val1 {
            get { return "string two"; }
        }
    }

    [DebuggerTypeProxy("DebuggerTests.TheProxy")]
    class WithProxyStructConstructedByString
    {
        public string Val1 {
            get { return "string two struct"; }
        }
    }
```
We are getting, in response to `CMD_TYPE_GET_CATTRS`, a typeProxyTypeId
https://github.com/dotnet/runtime/blob/84873e6c4e38b87185ad64beb95c6b76ec7f8d60/src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs#L2308
that exceeds the allowed id range in 
https://github.com/dotnet/runtime/blob/84873e6c4e38b87185ad64beb95c6b76ec7f8d60/src/mono/mono/component/debugger-agent.c#L1882

e.g. in
https://github.com/dotnet/runtime/blob/84873e6c4e38b87185ad64beb95c6b76ec7f8d60/src/mono/mono/component/debugger-agent.c#L2048

id=76, type=2, ids [type]=27962056, GINT_TO_UINT(id)=76, ids [type]->len=55.

Error details:
```
console.error: Error: [MONO] * Assertion at /workspaces/runtime/src/mono/mono/component/debugger-agent.c:2049, condition `<disabled>' not met
```

So far I did not find the reason for ID values out of range for strings.

**Comment by thaystg** [comment]
This is fixed by the new debugger.
