### ISSUE TITLE
[wasm][debugger] Add support for `DebuggerStepThrough` attribute

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#77318]
Prevent users from stepping into `MulticastDelegate`. Add `StepThrough` attributes like in this PR: https://github.com/dotnet/runtime/pull/77132/files and write tests for it.

**Comment by ilonatommy** [comment]
Cannot reproduce the faulty behavior in our case. Used the same scenario as described for coreclr: https://github.com/dotnet/runtime/issues/77131.

**Comment by thaystg** [comment]
Please, also test in a maui app, which also uses mono runtime.

**Comment by ilonatommy** [comment]
I don't fully understand the big-picture connections in MAUI. I created a Blazor Maui App from VS template with net 7 (finally succeeded) and used the reproduction code. Result: I am indeed stepping in while I should not but the code I am stepping in is:
https://github.com/dotnet/runtime/blob/e4471c1238499c752ccd06381c7179c10696441d/src/coreclr/System.Private.CoreLib/src/System/MulticastDelegate.cs#L572
so not Mono's `MulticastDelegate`. Maybe we are using `coreclr` for this case in Maui after all?
Same for non-blazor Maui.

**Comment by ilonatommy** [comment]
Update: my bad, I was not testing on a mobile device. Mono MulticastDelegate code is hidden as it should. Closing.
