### ISSUE TITLE
Post build events and the VS publish wizard

### ISSUE THREAD

**Issue by 0xC0000054** [dotnet/runtime#77311]
I have a .NET 6.0 project that I am packaging as a single-file executable using the VS publish wizard.

I need to run post-build commands on the published single-file executable, and I have not been able to find any MSBuild event that can be hooked to allow this.
Before the conversion to a .NET 6.0 single-file executable I was using the VS post-build event for this purpose.

For reference the project is [PSFilterShim](https://github.com/0xC0000054/PSFilterPdn/blob/pdn5/src/PSFilterShim/PSFilterShim.csproj), it is part of my PSFilterPdn plugin that allows Paint.NET to run Photoshop-compatible filters.
Because PSFilterShim is used to run x86 plugins I need to run a post-build event that calls `editbin /NXCOMPAT:NO` on the published single-file executable for the older plugins that are not compatible with DEP.

Alternatively, is there a way to invoke the single-file publish step as part of the normal VS build process and then run my additional commands after it completes?

**Comment by vitek-karas** [comment]
You should be able to simply add a target after Publish:
```XML
  <Target Name="TestAfterPublish" AfterTargets="Publish">
    <Message Text="Hello"/>
  </Target>
```

This worked for me (it ran after Publish was done).

**Comment by 0xC0000054** [comment]
The `Publish` target runs before the single-file executable is built and copied to the output folder.

**Comment by vitek-karas** [comment]
All of the work to create and copy single-file to the output is done before the `Publish` target executes (the Publish target itself does basically nothing).

You can see that here in msbuild binlog:
![image](https://user-images.githubusercontent.com/10670590/198101938-780eec6f-107d-4b61-899d-cd04d938ea29.png)

Also - if you use a custom target like this:
```XML
  <Target Name="TestAfterPublish" AfterTargets="Publish">
    <Message Condition="Exists('$(PublishDir)$(PublishedSingleFileName)')" Text="File exists $(PublishDir)$(PublishedSingleFileName)" Importance="high"/>
  </Target>
```

It will print out that the file exists at the time the target executes (I did manually delete the output directory before running publish to verify).

**Comment by 0xC0000054** [comment]
> It will print out that the file exists at the time the target executes (I did manually delete the output directory before running publish to verify).

It works if I delete the output directory before publishing, but my post-publish command fails if I do not do that.
For reference, the command I am using is: 

```xml
<Target Name="AfterPublishCommands" AfterTargets="Publish">
    <Exec Command="call &quot;$(DevEnvDir)..\tools\VsDevCmd.bat&quot; &amp;&amp; editbin.exe /NXCOMPAT:NO &quot;$(ProjectDir)$(PublishDir)$(PublishedSingleFileName)&quot;" />
</Target>
```

If the publish directory is not deleted the `editbin` command fails with `cannot open file '<path>'`.
I am not sure why it works correctly after deleting the publish directory, perhaps there is some kind of race condition that is locking the file.

In any case I managed to solve the issue by deleting the publish directory before the `PrepareForPublish` creates it.

```xml
<Target Name="DeleteExistingPublishedFiles" BeforeTargets="PrepareForPublish">
    <RemoveDir Directories="$(ProjectDir)$(PublishDir)"/>
</Target>
```
