### ISSUE TITLE
In net6 /net5 , when checking variable/property is string, and the property has null notation ?, the test is false.

### ISSUE THREAD

**Issue by moh-hassan** [dotnet/runtime#77313]
I have created a [fiddle demo](https://dotnetfiddle.net/Wf0tqp) to show the issue.
------------
In net6(or net5), I try to to check a variable is string, like:
```
if (name1 is string s1)
	Console.WriteLine($"name1 is string with value {s1}");
```

I expect name1 to be  string, but net6 is not aware it's string.
I tried the test with different string properties in a class, but every string property with nullable notation ? (and its value is null) can not be tested in pattern expression: ` variable is string s`

I know that I can check with length >0: `name1?.length >0`, but actually I use switch with pattern matching.
How to fix this issue using pattern matching ?

The complete c# code:
```
using System;
#nullable enable
public class Program
{
	public static void Main()
	{
		Test1();
	}


	static void Test1()
	{
		string? name1 = null !;
		string name2 = "abc";
		if (name1 is string s1)
			Console.WriteLine($"name1 is string with value {s1}");
		if (name2 is string s2)
			Console.WriteLine($"name2 is string with value {s2}");
		var person = new Person{Name = "Jack"};	
		if (person.Name is string s3)
			Console.WriteLine($"person.Name is string with value {s3}");
		if (person.FirstName is string s4)
			Console.WriteLine($"person.FirstName is string with value {s4}");
	}
}

class Person
{
	public string Name { get; set; }

	public string? FirstName { get; set; }

	public string? LastName { get; set; } = null !;
	public string? FullName { get; set; } = "Jack";
}
```

**Comment by moh-hassan** [comment]
Area may be: 
area-System.Reflection 
or area-TypeSystem-coreclr

**Comment by EgorBo** [comment]
@moh-hassan see https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/type-testing-and-cast#is-operator, namely this part:

> The `is` operator returns true when an expression result is non-`null` and any of the following conditions are true:
