### ISSUE TITLE
IDBFS undefined issue!

### ISSUE THREAD

**Issue by sajjadarashhh** [dotnet/runtime#77329]
### Description

i create this issue twice and now third time i maked this!
i solved this in .net 7 preview with this : window.Module.FS.filesystems.IDBFS and window.Module.FS.filesystems.IDBFS
i that window.Module.FS.filesystems just i found MEMFS but i dont find IDBFS
but now thats not defined in .net 7 rc 2 template blazor wasm
and i tried Module.FS.filesystems.IDBFS thats again show undefined error 
### Reproduction Steps

create browser wasm .net 7 rc 2 use <EmccExtraLDFlags>-lidbfs.js</EmccExtraLDFlags>
and try to use IDBFS

### Expected behavior

IDBFS not defined error

### Actual behavior

IDBFS defined

**Comment by jkotas** [comment]
cc @pavelsavara

**Comment by pavelsavara** [comment]
Duplicate https://github.com/dotnet/runtime/issues/74664 and https://github.com/dotnet/runtime/issues/77235

@sajjadarashhh could you please give us minimal code of the project which doesn't work ?

Also, note that this is NOT supported API

**Comment by sajjadarashhh** [comment]
ok i re-produce that and comment here again

**Comment by sajjadarashhh** [comment]
i dont know why but after 3day its ok without any changes :|
sorry pavel!
thank you for your describes and replication ♥
