### ISSUE TITLE
[wasm] `S.R.IS.JavaScript.Tests.JSImportExportTest.JsImportTaskTypes`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#77334]
Build: https://github.com/dotnet/runtime/pull/87959/checks?check_run_id=15010861292

```
fail: [FAIL] System.Runtime.InteropServices.JavaScript.Tests.JSImportExportTest.JsImportTaskTypes
info: System.ObjectDisposedException : Cannot access a disposed object.
info: Object name: 'value'.
info:    at System.Runtime.InteropServices.JavaScript.Tests.JSImportExportTest.JsImportTaskTypes()
info: --- End of stack trace from previous location ---
```
[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-87959-merge-09436ace6d1440ecb1/normal-System.Runtime.InteropServices.JavaScript.Tests/1/console.b6a096ea.log?helixlogtype=result)

cc @pavelsavara

```json
{
  "ErrorMessage": "[FAIL] System.Runtime.InteropServices.JavaScript.Tests.JSImportExportTest.JsImportTaskTypes",
  "BuildRetry": false
}
```

 ### Known issue validation
**Build: :mag_right:** 
**Result validation: :warning:** Validation could not be done without an Azure DevOps build URL on the issue. Please add it to the "**Build: :mag_right:**" line.
**Validation performed at:** 7/13/2023 1:57:15 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[338245](https://dev.azure.com/dnceng-public/public/_build/results?buildId=338245)|dotnet/runtime|[normal-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=338245&view=ms.vss-test-web.build-test-results-tab&runId=7038762&resultId=180173)|dotnet/runtime#87260|
|[338230](https://dev.azure.com/dnceng-public/public/_build/results?buildId=338230)|dotnet/runtime|[normal-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=338230&view=ms.vss-test-web.build-test-results-tab&runId=7038524&resultId=170580)|dotnet/runtime#87959|
|[337739](https://dev.azure.com/dnceng-public/public/_build/results?buildId=337739)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=337739&view=ms.vss-test-web.build-test-results-tab&runId=7025240&resultId=185618)|dotnet/runtime#88794|
|[337641](https://dev.azure.com/dnceng-public/public/_build/results?buildId=337641)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=337641&view=ms.vss-test-web.build-test-results-tab&runId=7023160&resultId=185618)|dotnet/runtime#88503|
|[337476](https://dev.azure.com/dnceng-public/public/_build/results?buildId=337476)|dotnet/runtime|[normal-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=337476&view=ms.vss-test-web.build-test-results-tab&runId=7018760&resultId=180199)|dotnet/runtime#88415|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|5|

**Comment by radical** [comment]
More rolling build hits on [chrome](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-8da70013d9c6482fb3/WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests/1/console.b51bff8d.log?helixlogtype=result), and [v8](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-8da70013d9c6482fb3/WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests/1/console.b51bff8d.log?helixlogtype=result).

**Comment by radical** [comment]
This is happening irrespective of the host OS, and AOT/interpreter.

**Comment by pavelsavara** [comment]
I tried to reproduce [here](https://github.com/dotnet/runtime/compare/main...pavelsavara:wasm_77334?expand=1), no dice.
Any hints ?

**Comment by radical** [comment]
This is being hit on PRs too.
- Does running the entire test a hundred times locally help?
- Or maybe doing the same thing on CI, but running the helix work item many times

**Comment by jkotas** [comment]
Hit in #78593

**Comment by radical** [comment]
Hit on rolling build again (https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-306e7af446bb45f18e/normal-System.Runtime.InteropServices.JavaScript.Tests/1/console.f713aed3.log?helixlogtype=result). @pavelsavara we should disable the test till it is fixed.
