### ISSUE TITLE
Set-AzKeyVaultSecret Socket Exception and timeout

### ISSUE THREAD

**Issue by ahmad-masalha** [dotnet/runtime#77374]
### Description

When trying to execute Set-AzKeyVaultSecret PS command, I consistently get a timeout/socket exception. Retries do not help. I usually have to wait multiple hours before retying and succeeding,

### Reproduction Steps

Set-AzKeyVaultSecret -VaultName $VaultName -Name $SecretName -SecretValue $secureStringForKV -ContentType 'text/plain' -Expires $expires -NotBefore $notBefore -Tag $tags

### Expected behavior

As detailed in the document: [Set-AzKeyVaultSecret
](https://learn.microsoft.com/en-us/powershell/module/az.keyvault/set-azkeyvaultsecret?view=azps-9.0.1)

### Actual behavior

Getting the following exception:
```
Set-AzKeyVaultSecret : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond X.X.X.X:443
At line:179 char:20
+ ... etDetails = Set-AzKeyVaultSecret -VaultName $VaultName -Name $SecretN ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzKeyVaultSecret], SocketException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultSecret
```

**Comment by jeffschwMSFT** [comment]
I don't think that this is the right repo for this issue.  @ericstj @jeffhandley @danmoseley thoughts on where this question could be answered?

**Comment by ericstj** [comment]
Maybe either https://github.com/Azure/azure-powershell or https://github.com/Azure/azure-sdk-for-net?  cc @pallavit @heaths

**Comment by heaths** [comment]
If it's a timeout and intermittent, this could be a service issue; however, given that the Az cmdlets are using deprecated APIs, it might be better to move this issue to their repo for now and we can aide in migration to our supported client libraries e.g., Azure.Security.KeyVault.Secrets.

https://github.com/Azure/azure-powershell/blob/0d2e025004dfdfc99c7391d5b1158cb2531fc673/src/KeyVault/KeyVault/KeyVault.csproj#L18-L20

**Comment by jeffhandley** [comment]
@ahmad-masalha We cannot move this issue to the Azure/azure-powershell repository. I'm going to close the issue here; please file a new issue in that repository as needed. Thanks.

**Comment by BethanyZhou** [comment]
Thanks for the information. @heaths 

Hi @ahmad-masalha , please upgrade your Az.KeyVault to latest one by `Update-Module -Name Az.KeyVault -Scope CurrentUser` and try your commands again. Please feel free to open issue in https://github.com/Azure/azure-powershell if you have further questions about Az cmdlets.
