### ISSUE TITLE
Buffered file stream doesn't flush data right

### ISSUE THREAD

**Issue by emayevski** [dotnet/runtime#77373]
### Description

In BufferedFileStreamStrategy.cs, the Flush(bool flushToDisk) method does not perform flushing to disk when flushToDisk == true and there is data in the read or write buffer. I.e., both conditional blocks marked as "// Has write data ..." and "// Has read data ... " return without calling the underlying strategy's flush(flushToDisk).

### Reproduction Steps

No simple reproduction is available but the problem is obvious from the method itself. 

### Expected behavior

The underlying strategy's flush(flushToDisk) must be called in all cases.

### Actual behavior

As described above. 

### Known Workarounds

Setting the buffer size to 0 causes no buffering and correct flushing. But this is not really a workaround since it requires disabling of buffering. 

### Configuration

.NET 6.

**Comment by emayevski** [comment]
This belongs to area-System.IO

**Comment by adamsitnik** [comment]
Hi @emayevski 

Big thanks for a detailed bug report! I've sent a fix: #77384

> Setting the buffer size to 0 causes no buffering and correct flushing. But this is not really a workaround since it requires disabling of buffering.

Another workaround is to call this this method twice (I know it's dirty).

**Comment by emayevski** [comment]
Thank you! 

The workaround is good too :).
