### ISSUE TITLE
Microsoft.Extensions work planned for .NET 8

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/runtime#77390]
**This issue captures the planned work for .NET 8. This list is expected to change throughout the release cycle according to ongoing planning and discussions, with possible additions and subtractions to the scope.**

Related overlapping Epic issue 
- https://github.com/dotnet/runtime/issues/78518

## Summary

For .NET 8 we are prioritizing the work to improve code reliability and minimize the number of high-impact bugs in the codebase. There's also some bottom up planned community requested feature requests available in the list.

## Planned for .NET 8

* [![area-Extensions-Hosting](https://img.shields.io/github/issues-search/dotnet/runtime?label=area-Extensions-Hosting&query=is%3Aissue%20is%3Aopen%20milestone%3A8.0.0%20label%3Aarea-Extensions-Hosting)](https://github.com/dotnet/runtime/issues?q=is%3Aissue+is%3Aopen+milestone%3A8.0.0+label%3Aarea-Extensions-Hosting)
* [![area-Extensions-DependencyInjection](https://img.shields.io/github/issues-search/dotnet/runtime?label=area-Extensions-DependencyInjection&query=is%3Aissue%20is%3Aopen%20milestone%3A8.0.0%20label%3Aarea-Extensions-DependencyInjection)](https://github.com/dotnet/runtime/issues?q=is%3Aissue+is%3Aopen+milestone%3A8.0.0+label%3Aarea-Extensions-DependencyInjection)
* [![area-Extensions-Configuration](https://img.shields.io/github/issues-search/dotnet/runtime?label=area-Extensions-Configuration&query=is%3Aissue%20is%3Aopen%20milestone%3A8.0.0%20label%3Aarea-Extensions-Configuration)](https://github.com/dotnet/runtime/issues?q=is%3Aissue+is%3Aopen+milestone%3A8.0.0+label%3Aarea-Extensions-Configuration)
* [![area-Extensions-Logging](https://img.shields.io/github/issues-search/dotnet/runtime?label=area-Extensions-Logging&query=is%3Aissue%20is%3Aopen%20milestone%3A8.0.0%20label%3Aarea-Extensions-Logging)](https://github.com/dotnet/runtime/issues?q=is%3Aissue+is%3Aopen+milestone%3A8.0.0+label%3Aarea-Extensions-Logging)
* [![area-Extensions-Options](https://img.shields.io/github/issues-search/dotnet/runtime?label=area-Extensions-Options&query=is%3Aissue%20is%3Aopen%20milestone%3A8.0.0%20label%3Aarea-Extensions-Options)](https://github.com/dotnet/runtime/issues?q=is%3Aissue+is%3Aopen+milestone%3A8.0.0+label%3Aarea-Extensions-Options)
* [![area-Extensions-Caching](https://img.shields.io/github/issues-search/dotnet/runtime?label=area-Extensions-Caching&query=is%3Aissue%20is%3Aopen%20milestone%3A8.0.0%20label%3Aarea-Extensions-Caching)](https://github.com/dotnet/runtime/issues?q=is%3Aissue+is%3Aopen+milestone%3A8.0.0+label%3Aarea-Extensions-Caching)
* [![area-Extensions-Primitives](https://img.shields.io/github/issues-search/dotnet/runtime?label=area-Extensions-Primitives&query=is%3Aissue%20is%3Aopen%20milestone%3A8.0.0%20label%3Aarea-Extensions-Primitives)](https://github.com/dotnet/runtime/issues?q=is%3Aissue+is%3Aopen+milestone%3A8.0.0+label%3Aarea-Extensions-Primitives)

### Hosting
- [x] dotnet/runtime#68036

### Dependency Injection
- [ ] dotnet/runtime#66153
- [x] dotnet/runtime#65145
- [x] dotnet/runtime#46132
- [x] dotnet/runtime#34471

### Configuration
- [x] dotnet/runtime#77660
- [ ] dotnet/runtime#67616
- [x] dotnet/runtime#44493
- [ ] dotnet/runtime#44517
- [x] dotnet/runtime#42643
- [ ] dotnet/runtime#35989
- [ ] dotnet/runtime#36123
- [x] dotnet/runtime#73915
- [x] dotnet/runtime#77677
- [x] dotnet/runtime#77246
- [x] dotnet/runtime#43869

### Logging
- [ ] dotnet/runtime#76718
- [ ] dotnet/runtime#55525

### Logging Source Generator (also listed in https://github.com/dotnet/runtime/issues/52549)

- [x] dotnet/runtime#78013
- [x] dotnet/runtime#77525
- [x] dotnet/runtime#69490
- [x] dotnet/runtime#64667
- [x] dotnet/runtime#64665
- [x] dotnet/runtime#52226
- [x] ~~#52225~~

### Options
- [x] dotnet/runtime#77404
- [x] dotnet/runtime#85475 
- [ ] dotnet/runtime#43359

### Caching
- [ ] dotnet/runtime#76340
- [ ] dotnet/runtime#44512
- [ ] dotnet/runtime#43868
- [ ] dotnet/runtime#36402
- [ ] dotnet/runtime#36568

### Primitives
- [x] dotnet/runtime#36617

### Future considered Issues
- [ ] dotnet/runtime#52228
- [ ] dotnet/runtime#61947

**Comment by tarekgh** [comment]
Closing this as we tracked items in the linked issue.
