### ISSUE TITLE
String.IndexOf and String.LastIndexOf do not behave consistently across OS platforms

### ISSUE THREAD

**Issue by NightOwl888** [dotnet/runtime#774]
Here are a couple of tests that have different behavior on Windows, macOS and Linux. The failure always seems to happen when `StringComparison.CurrentCulture` is used. The results on Azure DevOps are as follows:

|  Platform | OS  |  Result |
|---|---|---|
| .netcoreapp3.0 | Windows  |  Pass  |
| .netcoreapp3.0 | Linux | Fail  |
| .netcoreapp3.0 | macOS  | Fail |
| .netcoreapp2.2 | Windows  |  Pass  |
| .netcoreapp2.2 | Linux | Fail  |
| .netcoreapp2.2 | macOS  | Fail |
| .netcoreapp2.0 | Windows  |  Pass  |
| .netcoreapp2.0 | Linux | Fail  |
| .netcoreapp2.0 | macOS  | Fail |
| .net451 | Windows | Pass |

```c#
[Test]
public void Test_IndexOf_String_Int32_CultureSensitivity_()
{
    string fixture = "ዬ፡ዶጶቝአሄኢቌጕኬ\u124fቖኋዘዻ፡ሆገኅጬሷ\u135cቔቿ፺ዃጫቭዄ";
    string searchFor = "ሄኢቌጕኬ\u124fቖኋዘዻ";

    CultureInfo originalCulture = CultureInfo.CurrentCulture;
    try
    {
        CultureInfo.CurrentCulture = new CultureInfo("ru-MD");

        Assert.AreEqual(6, fixture.IndexOf(searchFor, 4, StringComparison.Ordinal));
        Assert.AreEqual(-1, fixture.IndexOf(searchFor, 4, StringComparison.CurrentCulture));

    }
    finally
    {
        CultureInfo.CurrentCulture = originalCulture;
    }
}

[Test]
public void Test_LastIndexOf_String_Int32_CultureSensitivity_()
{
    string fixture = "ዬ፡ዶጶቝአሄኢቌጕኬ\u124fቖኋዘዻ፡ሆገኅጬሷ\u135cቔቿ፺ዃጫቭዄ";
    string searchFor = "ሄኢቌጕኬ\u124fቖኋዘዻ";

    CultureInfo originalCulture = CultureInfo.CurrentCulture;
    try
    {
        CultureInfo.CurrentCulture = new CultureInfo("ru-MD");

        Assert.AreEqual(6, fixture.LastIndexOf(searchFor, 20, StringComparison.Ordinal));
        Assert.AreEqual(-1, fixture.LastIndexOf(searchFor, 20, StringComparison.CurrentCulture));

    }
    finally
    {
        CultureInfo.CurrentCulture = originalCulture;
    }
}
```

Do note these tests were intentionally made evil to try to find bugs in our own `IndexOf` implementations, they aren't intended as real-world data, but extreme edge cases. Whatever the case, I would expect `StringComparison.CurrentCulture` to behave consistently across operating systems.

I briefly scanned the [documentation for `IndexOf`](https://docs.microsoft.com/en-us/dotnet/api/system.string.indexof?view=netcore-3.0) and the [Best Practices for Using Strings in .NET](https://docs.microsoft.com/en-us/dotnet/standard/base-types/best-practices-strings?view=netcore-3.0), but don't see any obvious references to this difference in behavior across operating systems. Is this intentional, or a bug?

**Comment by Clockwork-Muse** [comment]
> Whatever the case, I would expect StringComparison.CurrentCulture to behave consistently across operating systems.

[This is by design](https://github.com/dotnet/corefx/issues/26293).  Perhaps we should surface this more in the documentation?

As much as I think I may have preferred to have consistent behavior as well, you're not even guaranteed consistent behavior on Windows either (for a variety of reasons).

**Comment by NightOwl888** [comment]
Great. Exactly what I needed to know. Inconsistent behavior does seem to make `StringComparer.CurrentCulture` practically useless for applications built on .NET Core/.NET Stanadard, though.

Yes, I suggest improving visibility of this behavior in the docs so it can be taken into account when designing tests.

**Comment by tarekgh** [comment]
As indicated in the discussions this is by design as .NET depends on the OS or ICU for globalization support. We are improving the story in .NET 5.0 as we started supporting ICU on Windows which will allow getting more consistent results when running on different OS's. Also, we are going to support App local ICU which can be used to ensure exact behavior when running anywhere.
