### ISSUE TITLE
NativeAOT symbols are broken on linux when publishing Release

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#77407]
I would expect symbols to be *worse*, but not *broken* in this configuration.

~~It looks like change is caused by passing `-O` to clang when linking the binaries. Without `-O`, debugging symbols are present and functional. With `-O`, all symbols and stacks are broken.~~

It's something in the DWARF info emitted by ILC.

**Comment by MichalStrehovsky** [comment]
> With `-O`, all symbols and stacks are broken.

Do you have repro steps? I just debugger a coredump in https://github.com/dotnet/runtime/pull/77522#issuecomment-1293197828 and stacks looked fine.

I can't find where we would be passing `-O` to clang in our build targets.

**Comment by agocke** [comment]
Repro is in an Ubuntu 22.04 WSL instance with RC2, publishing helloworld using `dotnet publish -r linux-x64 -c Release -bl`.

Afterwards I open up the exe in GDB and I get the following:

```
GNU gdb (Ubuntu 12.0.90-0ubuntu1) 12.0.90
Reading symbols from ./bin/Release/net7.0/linux-x64/publish/aot1...
Dwarf Error: Could not find abbrev number 94 in CU at offset 0x0 [in module /home/andy/tmp/aot1/bin/Release/net7.0/linux-x64/publish/aot1]
(No debugging symbols found in ./bin/Release/net7.0/linux-x64/publish/aot1)
```

Function names are still around, but line number and file info is lost, as well as the symbol table.

You're right about `-O` though, I can't see that in the command line. I must have accidentally added that manually when altering the linking command to build against local bits. My clang invocation is

```
"clang" "obj/Release/net7.0/linux-x64/native/aot1.o" -o "bin/Release/net7.0/linux-x64/native/aot1" /home/andy/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.0-rc.2.22472.3/sdk/libbootstrapper.a /home/andy/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.0-rc.2.22472.3/sdk/libRuntime.WorkstationGC.a /home/andy/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.0-rc.2.22472.3/framework/libSystem.Native.a /home/andy/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.0-rc.2.22472.3/framework/libSystem.Globalization.Native.a /home/andy/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.0-rc.2.22472.3/framework/libSystem.IO.Compression.Native.a /home/andy/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.0-rc.2.22472.3/framework/libSystem.Net.Security.Native.a /home/andy/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.0-rc.2.22472.3/framework/libSystem.Security.Cryptography.Native.OpenSsl.a -g -Wl,-rpath,'$ORIGIN' -Wl,--build-id=sha1 -Wl,--as-needed -pthread -lstdc++ -ldl -lm -lz -lrt -pie -Wl,-z,relro -Wl,-z,now -Wl,--discard-all -Wl,--gc-sections
```

**Comment by agocke** [comment]
AH, my mistake, it's not the linking command that makes a difference, it's passing `-O` to ILC. Without it, debugging info is fine.

**Comment by agocke** [comment]
Re-opening to track servicing fix.

**Comment by MichalStrehovsky** [comment]
The fix is in the LLVM objwriter release branch and we picked up the change in release/7.0 of this repo. I think this can be closed.

**Comment by TheSpydog** [comment]
Did this fix make it into .NET 7.0.1? I'm still running into this problem in a non-trivial project with the 7.0.1 tooling.

(Interestingly, upgrading from 7.0.0 to 7.0.1 did fix this issue for a simple Hello World app, but I'm not sure if it's a direct result of this change or if it was a complete fluke.)

**Comment by MichalStrehovsky** [comment]
I think it will only be in 7.0.2.

7.0.1 happened in mid-november: https://github.com/dotnet/runtime/milestone/107?closed=1 and this change only landed after: https://github.com/dotnet/llvm-project/pull/321
