### ISSUE TITLE
The mscordbi.dll is missing from symbol servers

### ISSUE THREAD

**Issue by Macsimka** [dotnet/runtime#77432]
### Description

mscordbi.dll 4.700.20.11803 is missing.

![clTXu1n](https://user-images.githubusercontent.com/5254521/197794068-ba2ce078-aef8-45c6-ae91-cf692209eb25.png)
Same issue https://github.com/dotnet/runtime/issues/62962, but other lib version - 4.700.20.11803.

### Reproduction Steps

Try debugging a minidump from Linux running .NET 4.700.20.11803 in Visual Studio -- open it and then try to start Managed Debugging.

### Expected behavior

The debugging works as usual.

### Actual behavior

The VS hangs with the message about mscordbi.dll not available (see Description above).

**Comment by tommcdon** [comment]
@hoyosjs

**Comment by hoyosjs** [comment]
4.700.20.11803 corresponds to runtime version 3.1.3, which is before we added support for opening Linux dumps through Windows tools - I believe 3.1.7 was the first one. This would need to be opened directly on Linux under LLDB. Also, not sure if you are looking at a historical dump, but 3.1.3 is several security releases behind. I'll close this as this is not something we support.
