### ISSUE TITLE
[pgo] Assertion failed '((-slop) <= diff) && (diff <= slop)' during 'Compute edge weights (2, false)'

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#77450]
Pipeline: runtime-coreclr pgo
Config: win-arm64 Checked fullpgo_random_gdv_methodprofiling_only
Link: https://dev.azure.com/dnceng-public/public/_build/results?buildId=62149&view=ms.vss-test-web.build-test-results-tab&runId=1274480&resultId=108923&paneView=debug

```scala
Assert failure(PID 11476 [0x00002cd4], Thread: 7904 [0x1ee0]): Assertion failed '((-slop) <= diff) && (diff <= slop)' in 'System.RuntimeType:GetConstructorCandidates(System.String,int,int,System.Type[],bool):ListBuilder`1[System.Reflection.ConstructorInfo]:this' during 'Compute edge weights (2, false)' (IL size 103; hash 0xfc7100fa; Tier1)

File: D:\a\_work\1\s\src\coreclr\jit\fgprofile.cpp Line: 3941
Image: D:\h\w\BE4A09E7\p\corerun.exe
```

cc @AndyAyersMS

**Comment by AndyAyersMS** [comment]
I just loosened the threshold recently: https://github.com/dotnet/runtime/pull/76409. Looks like we'll have to loosen even more.

**Comment by AndyAyersMS** [comment]
I'm not able to repro this so far. Probably timing dependent. Will keep trying.

It's no longer happening in the CI runs. So, removing the blocking label.

**Comment by AndyAyersMS** [comment]
I still can't repro, either with locally built bits or runfo downloaded bits, so am going to close this. 

Would not be surprising if further tweaks are needed to this assert, but don't want to modify it blindly. So a fix will have to wait for a more consistent repro.

**Comment by jakobbotsch** [comment]
> It's no longer happening in the CI runs. So, removing the blocking label.

Looks like it happened again on Saturday's run:
https://dev.azure.com/dnceng-public/public/_build/results?buildId=67103&view=ms.vss-test-web.build-test-results-tab&runId=1365674&resultId=192095&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-7abbdb10ea47480a83/System.Collections.Concurrent.Tests/1/console.6aec2436.log?helixlogtype=result

**Comment by AndyAyersMS** [comment]
This one was also intermittent, but I now have it captured via SPMI.

**Comment by AndyAyersMS** [comment]
In this latest case we just slightly over the tolerance limit:
```
BB78->BB80 (1) diff 1.040404 slop 1.040404 delta 2.220446e-16
```

**Comment by kunalspathak** [comment]
This again happened lately. https://dev.azure.com/dnceng-public/public/_build/results?buildId=94427&view=ms.vss-test-web.build-test-results-tab&runId=1990586&resultId=195188&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by BrianBohe** [comment]
This happened again on 12/24 with pipeline [runtime-coreclr libraries-pgo](https://dev.azure.com/dnceng-public/public/_build/results?buildId=119598&view=logs&j=90b83595-294f-5012-aa73-2e7af0be6394&t=51866677-f9ae-5538-b7aa-4c8484d0a9b9) > "checked coreclr Linux arm64 Release". [Full log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-f2ee1b90bbc84f2785/System.Private.Xml.Tests/1/console.eb92d847.log?helixlogtype=result).
