### ISSUE TITLE
FileInfo.CreateText and FileInfo.AppendText don't invalidate cache

### ISSUE THREAD

**Issue by hangy** [dotnet/runtime#77453]
### Description

The `CreateText` and `AppendText` methods on the `FileInfo` class don't invalidate the cache. The `Create` method does, though. This results in an inconsistent developer experience.

### Reproduction Steps

```csharp
FileInfo fileInfoForCreateText = new("foo.txt");
Console.WriteLine("File exists before CreateText: {0}", fileInfoForCreateText.Exists);
using (StreamWriter streamWriter = fileInfoForCreateText.CreateText())
{
    Console.WriteLine("File exists after CreateText: {0}", fileInfoForCreateText.Exists);
}

FileInfo fileInfoForCreate = new("foo2.txt");
Console.WriteLine("File exists before Create: {0}", fileInfoForCreate.Exists);
using (FileStream fileStream = fileInfoForCreate.Create())
{
    Console.WriteLine("File exists after Create: {0}", fileInfoForCreate.Exists);
}
```

### Expected behavior

The output should be
```
File exists before CreateText: False
File exists after CreateText: True
File exists before Create: False
File exists after Create: True
```

### Actual behavior

The output is
```
File exists before CreateText: False
File exists after CreateText: False
File exists before Create: False
File exists after Create: True
```

### Regression?

Before 1b683ecaa0838cc8626d4124a8bfeb7a9f4610fa, there was no difference between `CreateText` and `Create` considering the invalidation of the `FileInfo` object. Even if the methods now behave differently than in ie. .NET Framework 4.x, they should behave consistently.

### Known Workarounds

You can get the correct information by creating a new instance of `FileInfo` for the same path.

### Configuration

- .NET 7.0.100-rc.2.22477.23
- Windows 10 21H1 (Build 19043.2130)
- x64
- Configuration shouldn't matter, as the [relevant code](https://github.com/dotnet/runtime/blob/v7.0.0-rc.2.22472.3/src/libraries/System.Private.CoreLib/src/System/IO/FileInfo.cs#L84-L88) is platform agnostic

### Other information

The invalidation is a new feature added in #34229.

**Comment by adamsitnik** [comment]
@hangy thank you for a detailed bug report! Would you be interested in sending a PR with a fix?

**Comment by hangy** [comment]
@adamsitnik Yes, I am. Basically got it done, but I'm still trying to actually run the tests locally. (Turns out setting up my machine to build and test this repo is not trivial. 😉)

**Comment by adamsitnik** [comment]
> Yes, I am.

Awesome!

> I'm still trying to actually run the tests locally.

Please let me know if you need some help.

Once you install all build requirements listed in the [docs](https://github.com/dotnet/runtime/blob/main/docs/workflow/README.md) you should be able to build the product and run the tests. This is how I typically do it:

```cmd
.\build.cmd -c Release -subset clr+libs+libs.tests
.\dotnet.cmd build .\src\libraries\System.IO.FileSystem\tests\System.IO.FileSystem.Tests.csproj /t:Test /p:Configuration=Release
```
