### ISSUE TITLE
Is AuthenticationManager obsolete

### ISSUE THREAD

**Issue by yul-zhou** [dotnet/runtime#77459]
Edited by @MihaZupan to add the proposed obsoletion changes to the API.

The `AuthenticationManager` class currently has `Obsolete` annotations on two of its methods, where the rest of them are no-ops.
```c#
public partial class AuthenticationManager
{
    internal AuthenticationManager() { }

    // You can get/set these, but nothing else will consume them.
    public static System.Net.ICredentialPolicy? CredentialPolicy { get { throw null; } set { } }
    public static System.Collections.Specialized.StringDictionary CustomTargetNameDictionary { get { throw null; } }

    // These are no-op
    public static System.Collections.IEnumerator RegisteredModules { get { throw null; } }
    public static void Register(System.Net.IAuthenticationModule authenticationModule) { }
    public static void Unregister(System.Net.IAuthenticationModule authenticationModule) { }
    public static void Unregister(string authenticationScheme) { }

    // These are marked as Obsolete and throw PlatformNotSupportedException
    [System.ObsoleteAttribute("The AuthenticationManager Authenticate and PreAuthenticate methods are not supported and throw PlatformNotSupportedException.", DiagnosticId = "SYSLIB0009", UrlFormat = "https://aka.ms/dotnet-warnings/{0}")]
    public static System.Net.Authorization? Authenticate(string challenge, System.Net.WebRequest request, System.Net.ICredentials credentials) { throw null; }
    [System.ObsoleteAttribute("The AuthenticationManager Authenticate and PreAuthenticate methods are not supported and throw PlatformNotSupportedException.", DiagnosticId = "SYSLIB0009", UrlFormat = "https://aka.ms/dotnet-warnings/{0}")]
    public static System.Net.Authorization? PreAuthenticate(System.Net.WebRequest request, System.Net.ICredentials credentials) { throw null; }
}
```

I propose we move the `[Obsolete]` annotation to the whole class.
We can use the existing diagnostic ID and update the message.
```c#
[System.ObsoleteAttribute(
    "AuthenticationManager is not supported. Methods will no-op or throw PlatformNotSupportedException.",
    DiagnosticId = "SYSLIB0009",
    UrlFormat = "https://aka.ms/dotnet-warnings/{0}")]
public partial class AuthenticationManager
```

---

**_Original post_**

### Package Id

System.Net.AuthenticationManager

### Package Version(s)

.Net 6

### Additional details

I am not quite sure if this is the right place to ask this question. Please redirect me to the right place if I am wrong. 

So, when I tried out System.Net.AuthenticationManager Class, .Net Core 6 shows different behaviors with .Net Framework 4.8. The RegisteredModules properties are empty by default in .Net Core 6 and even I register a new module, it is still empty. So have System.Net.AuthenticationManager already been deprecated?

**Comment by MihaZupan** [comment]
Yes, the `PreAuthenticate` and `Authenticate` are marked as obsolete, and the rest of the members are no-ops. See https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Requests/src/System/Net/AuthenticationManager.cs

Perhaps we should mark the whole class as obsolete?

**Comment by Nirvana-Y** [comment]
Thanks for reply. I recheck the documents and see the "obsolete" in the method. It is more straightforward if you can mark the entire class as obsolete.

**Comment by MihaZupan** [comment]
I marked this as `api-ready-for-review` to extend the obsoletion to the whole class and update the obsoletion message.

@dotnet/ncl feel free to move it back if you disagree.

**Comment by bartonjs** [comment]
While the class isn't declared as `static class`, it only has `static` members, so it effectively is.  As such, the member-signature concerns of obsoleting a type don't apply, and obsoleting the type seems correct.

Using the existing SYSLIB0009 diagnostic ID seems fine, provided the docs for that code get updated along with this change.

```C#
namespace System.Net;

[System.ObsoleteAttribute(
    "AuthenticationManager is not supported. Methods will no-op or throw PlatformNotSupportedException.",
    DiagnosticId = "SYSLIB0009",
    UrlFormat = "https://aka.ms/dotnet-warnings/{0}")]
public partial class AuthenticationManager
```

**Comment by deeprobin** [comment]
Happy to assign to me. Would have a look at it in Hacktober.

**Comment by MihaZupan** [comment]
Reopening to track updating the `SYSLIB0009` docs: https://github.com/dotnet/docs/blob/main/docs/fundamentals/syslib-diagnostics/syslib0009.md
