### ISSUE TITLE
Default out filename of crossgen is confusing

### ISSUE THREAD

**Issue by hqueue** [dotnet/runtime#7746]
I made a helloworld.dll example as follows. Default extension of helloword application is `dll`.

```
$ uname -a
Linux 48b709a6472b 3.13.0-107-generic dotnet/runtime#3928-Ubuntu SMP Tue Dec 20 09:57:27 UTC 2016 x86_64 GNU/Linux
$ dotnet --info
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.1
$ dotnet new console
Content generation time: 52.2026 ms
The template "Console Application" created successfully.
$ dotnet restore
...
$ dotnet build
...
$ ls bin/Debug/netcoreapp1.1/
helloworld.deps.json  helloworld.pdb                     helloworld.runtimeconfig.json
helloworld.dll        helloworld.runtimeconfig.dev.json
```

Make native image from helloworld.dll using crossgen.
```
$ ./crossgen /ReadyToRun /Platform_Assemblies_Paths `pwd` helloworld.dll 
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Native image /home/hqueue/tmp/coreoverlay/helloworld.ni.exe generated successfully.
```

# Expected Result
Expected out filename is `helloworld.ni.dll`, since input filename is `helloworld.dll`.

# Actual Result
Actual out filename is `helloworld.ni.exe`

It was quite confusing that input filename and output filename have different extension.

Is this intended behavior of crossgen ?
Or should helloworld have `exe` as extension at the first place when generated from dotnet cli?

**Comment by AaronRobinsonMSFT** [comment]
The `crossgen` tool has been replaced with `crossgen2`. This query represents a retired workflow. @hqueue If this remains with `crossgen2`, please let us know.
