### ISSUE TITLE
[API Proposal]:  Expose maybe first-entry of internal Enum values

### ISSUE THREAD

**Issue by Shpendicus** [dotnet/runtime#77463]
### Background and motivation

The purpose is, to avoid completely Enum.GetValues() and give us direct "ref" the first slot, so one can iterate manually over them and can spare the allocation cost.

In my current example, I have a GUI render backend which has an enum of 280 enum values, and foreach of those there is a command buffer which is filled so that the renderer can call into specific commands and render the appropriate stuff, note that that is API based, its not my enum. But I wished actually to avoid the array of 280 * sizeof(int) and allow just to get a pointer to the 1.slot and iterate over that thing, cause iteration has to be done on each frame, to check the possible commands. So that would be actually something, like you allowed ppl to use 
"Nullable.GetValueByRef()".

### API Proposal

```csharp
namespace System.Collections.Generic;

public static ref readonly <T, TEnum> GetValueByRef<T, TEnum>(TEnum start)
{
       //pseudo-code:
       return ref __internal_Slots[this.IndexOf(start)];
}
```

### API Usage

```csharp
public enum Alphabet
{
   a=23,b=10,c=100,d=56,e=98,f=8, Length = 6
}

ref readonly first = Enum.GetValueByRef<Alphabet>(Alphabet.a);

for(int i = 0; i < (int)Alphabet.Length; I++)
{
      first = ref Unsafe.Add(first, 1);
      Console.WriteLine(first);  //
}


//should print:
//23, 10, 100, 56, 98, 8

```

### Alternative Designs

-

### Risks

To be honest, I don't know of any risk this could provide, I am here to learn that more from you guys haha, if this could indeed cause such. Since I only want to expose details of the internals of the enum in a readonly fashion I think its safe actually, but lets hear more out ...

**Comment by DaZombieKiller** [comment]
Wouldn't it make more sense for the API to return `ReadOnlySpan<T>` instead of `ref T`? An API like this has no real reason to be so unsafe. You can quite easily implement this yourself by caching the result of `Enum.GetValues` to avoid paying for an allocation each time:
```cs
using System;
using System.Runtime.CompilerServices;

foreach (var value in EnumMarshal.GetValues<Alphabet>())
    Console.WriteLine((int)value);

public static class EnumMarshal
{
    static readonly ConditionalWeakTable<Type, object> s_ValueCache = new();
    
    public static ReadOnlySpan<T> GetValues<T>()
        where T : Enum
    {
        return (T[])s_ValueCache.GetValue(typeof(T), Enum.GetValues);
    }
}

public enum Alphabet
{
   A = 23,
   B = 10,
   C = 100,
   D = 56,
   E = 98,
   F = 8,
}
```
(The implementation above uses `ConditionalWeakTable` so that it doesn't prevent unloading of collectible assemblies.)

**Comment by Shpendicus** [comment]
> Wouldn't it make more sense for the API to return `ReadOnlySpan<T>` instead of `ref T`? An API like this has no real reason to be so unsafe. You can quite easily implement this yourself by caching the result of `Enum.GetValues` to avoid paying for an allocation each time:
> 
> ```cs
> using System;
> using System.Runtime.CompilerServices;
> 
> foreach (var value in EnumMarshal.GetValues<Alphabet>())
>     Console.WriteLine((int)value);
> 
> public static class EnumMarshal
> {
>     static readonly ConditionalWeakTable<Type, object> s_ValueCache = new();
>     
>     public static ReadOnlySpan<T> GetValues<T>()
>         where T : struct, Enum
>     {
>         return (T[])s_ValueCache.GetValue(typeof(T), Enum.GetValues);
>     }
> }
> 
> public enum Alphabet
> {
>    A = 23,
>    B = 10,
>    C = 100,
>    D = 56,
>    E = 98,
>    F = 8,
> }
> ```
> 
> (The implementation above uses `ConditionalWeakTable` so that it doesn't prevent unloading of collectible assemblies.)

Hi mate, 

yea I know that I can cache the result, but I would like to avoid it all together, and returning a rf readonly can be easily transferred as a ReadOnlySpan<> so I think that's not to bad.

**Comment by DaZombieKiller** [comment]
> yea I know that I can cache the result, but I would like to avoid it all together

The API you have proposed would most likely do something very similar to what I posted if it were implemented.

The values of each entry in the enum are not necessarily stored linearly in an array. Even if they were (and I'm pretty sure they aren't), that would be an implementation detail of the runtime.

As a result, you cannot avoid allocating at least once for the array that stores the values unless you are on a runtime that already stores them in this way (which, to my knowledge, none of them do).

> returning a rf readonly can be easily transferred as a ReadOnlySpan<> so I think that's not to bad.

The problem with returning a `ref readonly T` instead of a `ReadOnlySpan<T>` is that the length of the buffer is not provided to the caller, so they need to know it in advance. They also need to use unsafe `ref` arithmetic to access anything other than the first value, which opens up the potential for buffer overruns.

**Comment by Shpendicus** [comment]
> access

So yea to the point that the array ofc must be allocated **internally** already once. 
But then, and  I agree fully, returning a ROS is better than just ref readonly so yea, good idea :-) 

But either way, avoiding the a) reflection to find the proper enum type and b) allocating that said array **twice** would be huge.

**Comment by Shpendicus** [comment]
So just to be clear: I do not want that there happens further unnessecary allocations, since the Enum class does have knowledge of its constants, in whatever form, and I only want, well lets take a ROS, a ROS from that internals.

**Comment by svick** [comment]
Can you explain why avoiding the 1kB one-time temporary allocation is important here?

**Comment by Shpendicus** [comment]
> Can you explain why avoiding the 1kB one-time temporary allocation is important here?

because I think its completely unnessecary, since the runtime already has knowledge of its underlying array so it could just expose that, don't u think?

**Comment by Shpendicus** [comment]
expose in readonly way ofc..

**Comment by svick** [comment]
> because I think its completely unnecessary

Personally, I don't think that's a sufficient reason. Adding new alternative APIs has significant costs, both for maintainers of .Net and for users (like confusion about which version to use) and so should be done only when there is a clear benefit.

**Comment by Shpendicus** [comment]
> > because I think its completely unnecessary
> 
> Personally, I don't think that's a sufficient reason. Adding new alternative APIs has significant costs, both for maintainers of .Net and for users (like confusion about which version to use) and so should be done only when there is a clear benefit.

Which costs exactly?
U have one Function, returning a readonlyspan and that's it, internally nothing has to be changed, its literally the same as with CollectionsMarshal.GetValueOrAddDefault() or Nullable.GetValueByRef()

and the "confusion" can be dealt easily with a comment above the function, which says that you can use this, to avoid explicit array allocs, and if ur big project is full with those then u can freely decide wether to use the new function and avoid all the Enum.GetValues() and use the new function OR u let it as is and don't bother concerning with it.

**Comment by Shpendicus** [comment]
You have 3 benefits:

1) No array alloc
2) No reflection
3) No GC hits (cause it has to release those at some point)

**Comment by Shpendicus** [comment]
Also, u spare X-times what I wrote just above, cause I have seen like 10x  or more calls of Enum.GetValues<T> in decent large projects so u get every time the loss of these allocs. And iterating over them must happen anyway, so why not just getting a span and iterating that thing.

**Comment by stephentoub** [comment]
> U have internally the array

Which array exactly are you referring to that's already available internally?  Please point to it in the source.  Thanks.

**Comment by Shpendicus** [comment]
Yoo  @stephentoub  

I actually did refer to this here: 
https://github.com/dotnet/runtime/blob/129982ef61894433867f0ea593281fc069284ade/src/libraries/System.Private.CoreLib/src/System/Enum.EnumInfo.cs#L8

as I can see there, the values are in the long[] values array. Or is this smth else and not related to my approach?

**Comment by stephentoub** [comment]
> the values are in the long[] values array

Right, which doesn't match up to the kind of array you're asking for.

It's also an implementation detail.  We're likely to change this, and change it over time (there's an open issue about a possible change, for example).

Better for you to just cache an array for what you want.

**Comment by stephentoub** [comment]
They're accessed from metadata binary blobs the values are stored in that transient long[] you already referenced. Nothing is stored in the shape you're hoping for.

**Comment by stephentoub** [comment]
I'm going to close this. Thanks for the interest.
