### ISSUE TITLE
Tracing a very simple .NET 6 Android app with AOT shows calls to RuntimeHelpers.CompileMethod

### ISSUE THREAD

**Issue by opcodewriter** [dotnet/runtime#77479]
I created an "Android Application" project in VS2022, and I'm only adding a button and a label by code:

![image](https://user-images.githubusercontent.com/15019084/197984707-47475e08-5738-46a8-a756-f5616dbe3c25.png)

Looking at the tracing log when running in **Release** (AOT is enabled), I can see a call to `RuntimeHelpers.CompileMethod` when setting the text on the button and the label:

![image](https://user-images.githubusercontent.com/15019084/197985934-af4ea9c2-21e9-44a9-8eae-7292b1cd1d93.png)

Are these calls to `RuntimeHelpers.CompileMethod` expected?

**Comment by opcodewriter** [comment]
Are these calls to `RuntimeHelpers.CompileMethod` expected?

**Comment by steveisok** [comment]
@opcodewriter Android is using what we call profiled AOT for apps. That means a subset of the runtime will be aot'd and the rest JIT'd.  

This looks expected to me.
