### ISSUE TITLE
.NET 8 per-preview performance overview

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#77490]
## Description

This issue provides an overview of the all performance regressions from microbenchmark automated runs in WASM, Mono AOT, and Interpreter during the timeframe of .NET 8 preview releases. WASM regressions are tracked separately at https://github.com/dotnet/perf-autofiling-issues/issues/9652.

List of queries for autofilling issues:
 - Mono AOT autofilling issues: https://github.com/dotnet/perf-autofiling-issues/issues?q=is%3Aissue+is%3Aopen+label%3Amono-aot
 - Interpreter autofilling issues: https://github.com/dotnet/perf-autofiling-issues/issues?q=is%3Aopen+is%3Aissue+label%3Amono-interpreter
 - WASM autofilling issues: https://github.com/dotnet/perf-autofiling-issues/issues?q=is%3Aopen+is%3Aissue+label%3Aarch-wasm
 - WASM AOT autofilling issues: https://github.com/dotnet/perf-autofiling-issues/issues?q=is%3Aopen+is%3Aissue+label%3Awasm-aot
 - Mono JIT autofilling issues: https://github.com/dotnet/perf-autofiling-issues/issues?q=is%3Aopen+is%3Aissue+label%3Amono-jit

## Mono AOT

Within the .NET 8 timeframe about 100 microbenchmarks regressed more than 10%. Summary of the most impactful issues to be resolved:
- Vector2/3/4 intrinsics - https://github.com/dotnet/runtime/issues/80569, https://github.com/dotnet/perf-autofiling-issues/issues/12546, https://github.com/dotnet/perf-autofiling-issues/issues/12660, https://github.com/dotnet/perf-autofiling-issues/issues/12660
 - Further investigation is needed - https://github.com/dotnet/perf-autofiling-issues/issues/13978
 - PackedSimd API not supported - https://github.com/dotnet/perf-autofiling-issues/issues/13992
 - Deduplicated binary logic - https://github.com/dotnet/perf-autofiling-issues/issues/16604, https://github.com/dotnet/perf-autofiling-issues/issues/16945
 - BitArray with Vector512 - https://github.com/dotnet/perf-autofiling-issues/issues/22179

<details><summary>Details</summary>

### RC2
Issue  | Status
-- | -- 
https://github.com/dotnet/perf-autofiling-issues/issues/22179 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/21818, https://github.com/dotnet/perf-autofiling-issues/issues/21820 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/22174 | **Resolved**

### RC 1

Issue  | Status
-- | -- 
https://github.com/dotnet/runtime/issues/91361, https://github.com/dotnet/perf-autofiling-issues/issues/20290 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/20971 | **Resolved**

### Preview 7

Issue  | Status
-- | -- 
https://github.com/dotnet/perf-autofiling-issues/issues/19469, https://github.com/dotnet/perf-autofiling-issues/issues/19517 | **Resolved**

### Preview 6

Issue  | Status
-- | -- 

### Preview 5

Issue  | Status
-- | -- 
https://github.com/dotnet/perf-autofiling-issues/issues/17874, https://github.com/dotnet/perf-autofiling-issues/issues/17870 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/17202, https://github.com/dotnet/perf-autofiling-issues/issues/17311 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/18385, https://github.com/dotnet/perf-autofiling-issues/issues/18384 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/18023 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/17208, https://github.com/dotnet/perf-autofiling-issues/issues/17312 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/17505, https://github.com/dotnet/perf-autofiling-issues/issues/17553 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/17201, https://github.com/dotnet/perf-autofiling-issues/issues/17310 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/17200 | **Resolved**

### Preview 4

Issue  | Status
-- | -- 
https://github.com/dotnet/perf-autofiling-issues/issues/17004, https://github.com/dotnet/perf-autofiling-issues/issues/16946, https://github.com/dotnet/perf-autofiling-issues/issues/16945, https://github.com/dotnet/perf-autofiling-issues/issues/16604 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/16359 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/16481 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/16361 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/14907 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/14523 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/15689, https://github.com/dotnet/perf-autofiling-issues/issues/15694, https://github.com/dotnet/perf-autofiling-issues/issues/15769, https://github.com/dotnet/perf-autofiling-issues/issues/15794, https://github.com/dotnet/perf-autofiling-issues/issues/15764, https://github.com/dotnet/perf-autofiling-issues/issues/15659 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/16943, https://github.com/dotnet/perf-autofiling-issues/issues/16433, https://github.com/dotnet/perf-autofiling-issues/issues/16603 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/15660  | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/17003, https://github.com/dotnet/perf-autofiling-issues/issues/15697, https://github.com/dotnet/perf-autofiling-issues/issues/15795, https://github.com/dotnet/perf-autofiling-issues/issues/15774, https://github.com/dotnet/perf-autofiling-issues/issues/15798 | **Resolved**

### Preview 3

Issue  | Status
-- | -- 
https://github.com/dotnet/perf-autofiling-issues/issues/13978 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/12060 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/14017, https://github.com/dotnet/perf-autofiling-issues/issues/13977, https://github.com/dotnet/perf-autofiling-issues/issues/14016, https://github.com/dotnet/perf-autofiling-issues/issues/13992 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/14569 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/14286 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/14570 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/14520 | **Resolved**

### Preview 2

Issue  | Status
-- | -- 
https://github.com/dotnet/perf-autofiling-issues/issues/12660 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/12546 | **Resolved**
https://github.com/dotnet/runtime/issues/80569 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/12957 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/13187 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/13500 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/13770 | **Resolved**

### .NET 7 / Preview 1

Issue  | Status
-- | -- 
https://github.com/dotnet/perf-autofiling-issues/issues/14015 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/11536 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/11539 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/13980 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/13774 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/13771 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/13499 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/13497 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/13495 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/13494 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/13772 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/13984 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/12058 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/11780 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/11812 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/12054 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/12073 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/12484 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/12307 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/10951 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/11779 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/11811 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/12056 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/12057 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/8834 |  **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/9173 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/9599 | **Resolved**
https://github.com/dotnet/runtime/issues/77900 | **Resolved**
https://github.com/dotnet/runtime/issues/78804 | **Resolved**
</details>

## Mono Interpreter

Within the .NET 8 timeframe about 250 microbenchmarks regressed more than 10%. Summary of the most impactful issues to be resolved:
 - PackedSimd API not supported - https://github.com/dotnet/perf-autofiling-issues/issues/13992
 - Vector128.Widen intrinsic - https://github.com/dotnet/perf-autofiling-issues/issues/19225
 - ActivatorUtilitiesBenchmark - https://github.com/dotnet/perf-autofiling-issues/issues/17235
 - IUtf8SpanParsable - https://github.com/dotnet/perf-autofiling-issues/issues/19919
 - DependencyInjection - https://github.com/dotnet/perf-autofiling-issues/issues/19921
 - Utf8Encoding - https://github.com/dotnet/perf-autofiling-issues/issues/20737
 - FrozenDictionary missing optimizations - https://github.com/dotnet/perf-autofiling-issues/issues/26185
 - SSA improvements - https://github.com/dotnet/perf-autofiling-issues/issues/16642

<details><summary>Details</summary>

### RC2
Issue  | Status
-- | -- 
https://github.com/dotnet/perf-autofiling-issues/issues/20737 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/21828, https://github.com/dotnet/perf-autofiling-issues/issues/21829, https://github.com/dotnet/perf-autofiling-issues/issues/21830, https://github.com/dotnet/perf-autofiling-issues/issues/21872, https://github.com/dotnet/perf-autofiling-issues/issues/22250 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/21832 | **Resolved**

### Preview 7
Issue  | Status
-- | -- 
https://github.com/dotnet/perf-autofiling-issues/issues/19921 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/19919 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/19225 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/19923 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/19918 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/19756 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/19486 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/19484 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/19227 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/19228 | **Resolved**

### Preview 6
Issue  | Status
-- | -- 
https://github.com/dotnet/perf-autofiling-issues/issues/19016 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/19018 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/18528 | **Resolved**

### Preview 5
Issue  | Status
-- | -- 
https://github.com/dotnet/perf-autofiling-issues/issues/18318 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/17235 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/18040 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/17237 | **Resolved**

### Preview 4
Issue | Status
--|--
https://github.com/dotnet/perf-autofiling-issues/issues/16642 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/15719 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/17018 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/16546 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/15724 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/15626 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/15154 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/14530 | **Resolved**

### Preview 3
Issue | Status
--|--
https://github.com/dotnet/perf-autofiling-issues/issues/13992 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/13993 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/13747 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/13749 | **Resolved**

### Preview 2
Issue | Status
--|--
https://github.com/dotnet/perf-autofiling-issues/issues/12707, https://github.com/dotnet/perf-autofiling-issues/issues/11453 | **Resolved**
https://github.com/dotnet/runtime/issues/79973 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/12299 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/13746 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/13199 | **Resolved**

### .NET 7 / Preview 1
Issue | Status
--|--
https://github.com/dotnet/runtime/issues/79876 | **Resolved**
https://github.com/dotnet/runtime/issues/79336 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/11449 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/11147 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/12501 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/12965 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/12081 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/12962 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/12080 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/11791 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/11790 | **Resolved**
https://github.com/dotnet/runtime/issues/78807 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/12047 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/11451 | **Resolved**
https://github.com/dotnet/runtime/issues/79604 | **Resolved**
https://github.com/dotnet/runtime/issues/78820 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/11293 | **Resolved**
https://github.com/dotnet/runtime/issues/79606 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/10933 | **Resolved**
https://github.com/dotnet/runtime/issues/79877 | **Resolved**
https://github.com/dotnet/runtime/issues/78815  | **Resolved**
https://github.com/dotnet/runtime/issues/79605 | **Resolved**
https://github.com/dotnet/runtime/issues/79607 | **Resolved**
https://github.com/dotnet/runtime/issues/78838 | **Resolved**
https://github.com/dotnet/runtime/issues/78826 |  **Resolved**
https://github.com/dotnet/runtime/issues/78821 |  **Resolved**
https://github.com/dotnet/runtime/issues/78980 |  **Resolved**
https://github.com/dotnet/runtime/issues/78809 |  **Resolved**
https://github.com/dotnet/runtime/issues/78812 | **Resolved**
https://github.com/dotnet/runtime/issues/78813 | **Resolved**
https://github.com/dotnet/runtime/issues/78814 |**Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/8641 |  **Resolved**
https://github.com/dotnet/runtime/issues/79337 |  **Resolved**
https://github.com/dotnet/runtime/issues/78810 |  **Resolved**
https://github.com/dotnet/runtime/issues/78836 | **Resolved**
https://github.com/dotnet/runtime/issues/78825 |  **Resolved**
https://github.com/dotnet/runtime/issues/78824 |  **Resolved**
https://github.com/dotnet/runtime/issues/78823 |  **Resolved**
https://github.com/dotnet/runtime/issues/78822 |  **Resolved**
https://github.com/dotnet/runtime/issues/78837 |  **Resolved**
https://github.com/dotnet/runtime/issues/78827 | **Resolved**
https://github.com/dotnet/runtime/issues/78835 | **Resolved**
https://github.com/dotnet/runtime/issues/78805 |  **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/10158 |  **Resolved**
https://github.com/dotnet/runtime/issues/78804 |  **Resolved**
https://github.com/dotnet/runtime/issues/78811 |  **Resolved**
https://github.com/dotnet/runtime/issues/78808 |  **Resolved**
https://github.com/dotnet/runtime/issues/78806 |  **Resolved**
https://github.com/dotnet/runtime/issues/78819 |  **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/9346 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/8642 | **Resolved**
https://github.com/dotnet/runtime/issues/77900  | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/8870 |  **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/9029 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/9030 | **Resolved**
https://github.com/dotnet/perf-autofiling-issues/issues/9199 | **Resolved**
</details>

## Mono On Disk Size - iOS
![Screenshot 2023-04-27 at 10 03 04](https://user-images.githubusercontent.com/11523312/234798934-9444948a-8050-4d90-8cd3-9d667121beff.png)

<details><summary>Details</summary>

### .NET 8
Date | Diff | Change | Size increase (bytes) | Size increase (%) | Tracking issue | Status
--|--|--|--|--|--|--
06 Dec 2022 | https://github.com/dotnet/runtime/compare/b399eed41e575b5d03d0901e9d4776aa9a93b9a9...fcf0a09a47ee75bc33731b8c3358f6de78fbc211 | https://github.com/dotnet/runtime/commit/62f3eb2878c3e82631b91dd02ee4fb655d23a2b1 | - |	- | https://github.com/dotnet/runtime/issues/79285
12 Apr 2022 | https://github.com/dotnet/runtime/compare/e7ed417c...7526a4c6a | https://github.com/dotnet/runtime/pull/84289  |   590688 | 2.11 | https://github.com/dotnet/runtime/issues/85450
14 Apr 2022 |  https://github.com/dotnet/runtime/compare/2d833f43...9c02b25f | https://github.com/dotnet/runtime/pull/84587   |     351776 |	1.25 | https://github.com/dotnet/runtime/issues/85451
24 Apr 2022 | https://github.com/dotnet/runtime/compare/223d15287...9aefa9d | https://github.com/dotnet/runtime/pull/84582 | 385449 |	1.32 | https://github.com/dotnet/runtime/issues/85452

</details>

**Comment by lewing** [comment]
cc @artl93 @stevisok@jeffschwMSFT

**Comment by kotlarmilos** [comment]
The .NET 9 issues have been moved to https://github.com/dotnet/runtime/issues/98209. This issue will be closed after remaining regressions are addressed.

**Comment by lewing** [comment]
@DrewScoggins @kotlarmilos why aren't the wasm being labeled as interpreter runs and being tracked in #98209 ?

**Comment by kotlarmilos** [comment]
They are tracked separately in https://github.com/dotnet/runtime/issues/96444.

**Comment by kotlarmilos** [comment]
@matouskozak Do we plan to triage tracked issues?

**Comment by matouskozak** [comment]
> @matouskozak Do we plan to triage tracked issues?

I took a look at some MonoAOT ones, closed the ones that are no-longer regressed in .NET 9. We should align on what to do with the rest. Let's sync on Wednesday call on decide.

**Comment by kotlarmilos** [comment]
All issues have been transferred/resolved to .NET 9+.
