### ISSUE TITLE
For HttpClient with HttpMessageHandler is getting called multiple times for single SendAsync

### ISSUE THREAD

**Issue by vj19us** [dotnet/runtime#77495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi, I have below code -
Program.cs 
```
builder.Services.AddHttpClient("myClient", httpClient =>
{
    httpClient.BaseAddress = new Uri(url);
}).AddHttpMessageHandler<HttpMessageHandler>();
```

HttpMessageHandler.cs
```
protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
{
    Console.WriteLine($"request log {request.ToJson()}");
    var response = await base.SendAsync(request, cancellationToken);
    var responsMsg = response.ToJson();
    // Log Response here
    Console.WriteLine($"response log {responsMsg}");
    return response;
}
```

ServiceClient.cs
```
var client1 = _httpClientFactory.CreateClient("myClient");
string path= _configuration["path"];
HttpRequestMessage request1 = new HttpRequestMessage(HttpMethod.Get, path);
using (var response1 = await client1.SendAsync(request1))
{
    response1.EnsureSuccessStatusCode();
    Console.WriteLine("response success");

string path2= _configuration["path2"]";
HttpRequestMessage request2 = new HttpRequestMessage(HttpMethod.Get, path2);
var client2 = _httpClientFactory.CreateClient("myClient");
using (var response2 = await client2.SendAsync(request2))
{
    response.EnsureSuccessStatusCode();
    Console.WriteLine("response success");
}
}
```
Issue - when I debug handler is invoked while executing - using (var response1 = await client1.SendAsync(request1)) twice.

### Expected Behavior

Expectation is  for each SendAsync handler should be invoked once.

### .NET Version

.NET core 6

**Comment by MihaZupan** [comment]
> when I debug handler is invoked while executing - using (var response1 = await client1.SendAsync(request1)) twice.

Are you sure that it's executing the `SendAsync` twice, or are you just seeing that the debugger highlights this line twice?

The `using` statement is rewritten by the compiler to something like
```c#
var response1 = await client1.SendAsync(request1);
try
{
    response1.EnsureSuccessStatusCode();
    Console.WriteLine("response success");
}
finally
{
    response1.Dispose();
}
```
So the debugger may highlight the `using` statement again when you reach the `finally` block, but that doesn't mean that the program is executing the `SendAsync`.

**Comment by vj19us** [comment]
yes It is executing twice.  do you recommend trying without using statements? Its same client but with multiple endpoints/paths.

**Comment by CarnaViire** [comment]
Do you mean that in console you would see "request log {*first* request}" printed twice @vj19us? And then "request log {*second* request}" twice again?

> when I debug handler

Does it happen only when you use the attached debugger? Does it happen when running by `dotnet run`?

**Comment by vj19us** [comment]
In this example, first request itself logs 2 times.  I have another method in same class where I am calling httpClient.sendAsync only one there handler works fine.

**Comment by davidfowl** [comment]
@vj19us can you provide a runnable sample?

**Comment by vj19us** [comment]
In a prototype sample not able to reproduce this. will re-open this if i find something new.
