### ISSUE TITLE
StreamReader array allocations should be pool-able

### ISSUE THREAD

**Issue by Austin-Lamb** [dotnet/runtime#77515]
### Description

I have an application that uses a lot of `StreamReader` objects to read in many files.  In performance profiles I'm noticing that the `char[]` and `byte[]` allocated by `StreamReader` are really adding up.  I wish I could have a hook allowing these to be pooled with something like `ArrayPool` since I am specifying a buffer size manually so I know the arrays will be the same size anyway, and I don't have that many concurrently.

### Configuration

.NET Version: 6.0 (from reading the 7.0 code, it's the same here)
OS Version: Windows 11 22H2
Architecture: x64

### Regression?

No, this is not a regression.

**Comment by huoyaoyuan** [comment]
Duplicate of #60694.

**Comment by adamsitnik** [comment]
@huoyaoyuan is right, this issue is a duplicate. Please follow  #23486 for updates. Thanks!
