### ISSUE TITLE
[LSG] warning CS8785: Generator 'LoggerMessageGenerator' failed to generate source.

### ISSUE THREAD

**Issue by pengweiqhca** [dotnet/runtime#77525]
### Description

LoggerMessageGenerator not support [Obsolete] with argment(s).

### Reproduction Steps

``` C#
public static partial class LoggerExtensions
{
	[LoggerMessage((int)LogLevel.Trace, LogLevel.Trace, "{Msg}")]
	[Obsolete("test")]
	public static partial void Trace(this ILogger logger, string msg, Exception? ex = null);
}
```

### Expected behavior

Not error.

### Actual behavior

warning CS8785: Generator 'LoggerMessageGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidCastException' with message 'Specified cast is not valid.'

### Known Workarounds

Delete [Obsolete] argment.

**Comment by danmoseley** [comment]
Thanks for the report. Would you be interested to offer a PR?

**Comment by allantargino** [comment]
I wasn't able to reproduce this error using `Microsoft.Extensions.Logging` version `7.0.0`.

I don't get any compilation errors, and I can confirm the annotations are being added by the compiler to the assembly:
![image](https://user-images.githubusercontent.com/13934447/208674592-47fcecd5-8d07-490b-b828-253d6ad222f1.png)

Do you have more information about your environment/runtime?

**Comment by pengweiqhca** [comment]
@allantargino Sorray, I test again, dotnet sdk 7.0.100, `Microsoft.Extensions.Logging` 7.0.0 no error, 6.0.0 is error.

**Comment by tarekgh** [comment]
@allantargino @pengweiqhca how this is important to port to 6.0? We have a servicing bar which needs some justification to port it. I am seeing there is an easy workaround to reference 7.0 version of the logging libraries. right?

**Comment by pengweiqhca** [comment]
I have solved in other way. But I think it's a compatibility issue, and .NET 6 still servicing.

**Comment by allantargino** [comment]
@tarekgh I'd say this isn't a critical fix. Like you said, the workaround is just to reference the new version. Given it doesn't have any [breaking changes](https://learn.microsoft.com/en-us/dotnet/core/compatibility/7.0), I believe it is fair to not port it back.

**Comment by tarekgh** [comment]
Per the replies I am going to close this issue and the PR and we can consider the porting to 6.0 if we see more demands on it in the future.
