### ISSUE TITLE
Launch Without Debugging Doesn't Block BackgroundService and Whole App but Debug Does

### ISSUE THREAD

**Issue by seikosantana** [dotnet/runtime#77523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a BackgroundService that looks like this
```cs
using RemoteMonitor.Classes;
using RemoteMonitor.DatabaseContexts;

namespace RemoteMonitor.Services;

public class MonitoringEventTriggeringService : BackgroundService
{
    private IServiceProvider ServiceProvider { get; }
    private ILogger<MonitoringEventTriggeringService> Logger { get; }

    private Queue<MonitoringEvent> EventQueue { get; }

    public MonitoringEventTriggeringService(IServiceProvider provider, ILogger<MonitoringEventTriggeringService> logger)
    {
        ServiceProvider = provider;
        Logger = logger;
        EventQueue = new Queue<MonitoringEvent>();
    }

    public void QueueEventTrigger(MonitoringEvent monitoringEvent)
    {
        EventQueue.Enqueue(monitoringEvent);
    }

    private Thread? _workerThread;
    private Task LongRunningTask;

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        if (LongRunningTask is not null) throw new InvalidOperationException("Already running");

        Logger.LogInformation("Monitoring Event Triggering Start");
        LongRunningTask = Task.Run(async () =>
            {
                Logger.LogInformation("Task Start");
                try
                {
                    while (!stoppingToken.IsCancellationRequested)
                    {
                        if (EventQueue.Count == 0)
                        {
                            continue;
                        }

                        var monitoringEvent = EventQueue.Dequeue();
                        using (var scope = ServiceProvider.CreateScope())
                        {
                            var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
                            await db.MonitoringEvents.AddAsync(monitoringEvent, stoppingToken);
                            await db.SaveChangesAsync(stoppingToken);
                        }

                        // TODO Trigger events, notifications
                        Logger.LogInformation($"{monitoringEvent.DateTime} Rule {monitoringEvent.Message} triggered");
                    }
                }
                catch (Exception ex)
                {
                    Logger.LogError(ex, "Something went wrong");
                }
            },
            stoppingToken
        );
        Logger.LogInformation("Task is running");
    }
}
```

I also commented out any other irrelevant things in my entry point
```cs
using RemoteMonitor.DatabaseContexts;
using RemoteMonitor.Services;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllersWithViews();
builder.Services.AddDbContext<AppDbContext>();
builder.Services.AddHostedService<MonitoringEventTriggeringService>();

var app = builder.Build();

if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Home/Error");
    app.UseHsts();
}

// app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseRouting();
app.UseAuthorization();

app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}"
);

app.Run();
```

The application seems to be stuck somewhere so that the `Host` doesn't get to initialize the web service
Here's the output
![image](https://user-images.githubusercontent.com/35630407/197503786-c10156af-788b-44cb-90c3-a6534a078a90.png)

I have also tried it with using `Thread` with `IsBackground` set to true, and still no luck. I also tried putting `Task.Yield() in the beginning of the task and in the while loop` and once i got this:
![image](https://user-images.githubusercontent.com/35630407/197504109-58bc8864-4e3c-4423-8a82-9cf145d12e4e.png)

I also tried stepping into Host.cs with Jetbrains Rider and the loop seems to be stuck after this statement
![image](https://user-images.githubusercontent.com/35630407/197504352-ec456956-bf42-42a5-b451-031770b8f9bb.png)

I am developing on Linux, and I tried on Windows with the same Jetbrains Rider version and .NET 6 SDK version and debugging works just normally, meanwhile on Linux everything runs normally only if started without debugging.

### Expected Behavior

App initiation does not block, proceeds to initiate the next hosted services

### Steps To Reproduce

[Minimum reproducable repo](https://github.com/seikosantana/DebugLaunchIssue)

### .NET Version

6.0.402

### Anything else?

ASP.NET Core Version: 6.0.10
IDE: Jetbrains Rider 2022.2.3, similar behavior also happens on VSCode 1.72.2

Output of `dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   6.0.402
 Commit:    6862418796

Runtime Environment:
 OS Name:     zorin
 OS Version:  16
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.402/

global.json file:
  Not found

Host:
  Version:      6.0.10
  Architecture: x64
  Commit:       5a400c212a

.NET SDKs installed:
  6.0.402 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

**Comment by hoyosjs** [comment]
This is purely #33561 it looks like, so I'll close this issue. For your particular implementation a simple workaround might be to have a SemaphoreSlim that you await on that loop and you can Release it when someone writes the `MonitoringEvent`, or a Channel with a SingleReader option, that way you don't block the thread in the Task.Run and it's not a CPU heavy loop. If you have any further doubt feel free to comment or open a new isssue.

**Comment by seikosantana** [comment]
For now I am using `await Task.Yield()`, but about SemaphoreSlim, how does awaiting it makes the thread does not block?

**Comment by hoyosjs** [comment]
Something like this from your sample modified assumes single reader (Or that the order of reads is not important) and many writers. Since ExecuteAsync kicks off your task and returns to the ASP infrastructure as soon as your code blocks async, the await on the semaphore will cause it to go away and then that task will get scheduled into a thread pool thread as long as some producer set the semaphore slim and there's data available to consume. As soon as the data is drained, the task will get kicked off the threadpool until there's more available. This is in general better if you don't see this being too CPU intensive of a task and you don't get a lot of those messages.

<details>
<summary>Modified Repro</summary>

```csharp
using System.Collections.Concurrent;

namespace DebugLaunchIssue;

public class QueueProcessingService : BackgroundService
{
    private readonly ILogger<QueueProcessingService> _logger;
    private readonly ConcurrentQueue<string> _queue;
    private readonly SemaphoreSlim _semaphore;

    public QueueProcessingService(ILogger<QueueProcessingService> logger)
    {
        _logger = logger;
        _queue = new ();
        _semaphore = new (0);
    }

    public void EnqueueMessage(string message)
    {
        _queue.Enqueue(message);
        _semaphore.Release();
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        _logger.LogInformation("Starting queue processor");
        try {
            while (!stoppingToken.IsCancellationRequested)
            {
                await _semaphore.WaitAsync(stoppingToken);
                if (_queue.TryDequeue(out string? content))
                {
                    _logger.LogInformation("{Content} has been processed", content);
                }
            }
        }
        catch (TaskCanceledException)
        {
            _logger.LogInformation("Cancellation received");
        }
        _logger.LogInformation("Stopping queue processor");
    }
}
```

</details>
