### ISSUE TITLE
[bug]incorrect alignment for elements in array

### ISSUE THREAD

**Issue by bysdxt** [dotnet/runtime#77539]
### Description

Elements in array have incorrect alignment,even the type of element has StructLayout with Pack field set.

### Reproduction Steps

code:
```C#
using System.Runtime.InteropServices;
namespace ConsoleApp1 {
    [StructLayout(LayoutKind.Sequential, Pack = 16, Size = 16)] struct A { }
    unsafe internal class Program {
        static void Main() {
            fixed (A* ptr = new A[1]) {
                Console.WriteLine(((ulong)ptr) % 16);
            }
        }
    }
}

```

### Expected behavior

output:
0

### Actual behavior

output:
8

### Regression?

.net core 3.1 has no problem
but .net 6(win10 x64) has.
.net 6 at Linux has no problem too.

### Known Workarounds

code changes to:
```C#
using System.Runtime.InteropServices;
namespace ConsoleApp1 {
    [StructLayout(LayoutKind.Sequential, Pack = 16, Size = 16)] struct A { }
    unsafe internal class Program {
        static void Main() {
            fixed (A* ptr = new A[1]) {
                Console.WriteLine($"{(ulong)ptr:X}");
                Console.WriteLine(((ulong)ptr) % 16);
            }
        }
    }
}
```

and output will be correct......

### Configuration

Windows 10 21H2:

.NET SDK:
 Version:   6.0.401
 Commit:    0906eae6f8

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.401\

global.json file:
  Not found

Host:
  Version:      6.0.10
  Architecture: x64
  Commit:       5a400c212a

.NET SDKs installed:
  3.1.424 [C:\Program Files\dotnet\sdk]
  6.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

---

Linux(ubuntu 22.04-x64):
.NET SDK (reflecting any global.json):
 Version:   6.0.401
 Commit:    0906eae6f8

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /home/bysdxt/.dotnet/sdk/6.0.401/

global.json file:
  Not found

Host:
  Version:      6.0.9
  Architecture: x64
  Commit:       163a63591c

.NET SDKs installed:
  6.0.401 [/home/bysdxt/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.9 [/home/bysdxt/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.9 [/home/bysdxt/.dotnet/shared/Microsoft.NETCore.App]

**Comment by bysdxt** [comment]
C++/CLI(.net framework 4.8.1) also has problem
![1](https://user-images.githubusercontent.com/13766766/198340928-dac9d6c1-4575-4530-91d0-066b159b701f.png)
![2](https://user-images.githubusercontent.com/13766766/198340946-17e6cef2-017e-4bc4-9952-e027be5fda70.png)

**Comment by SingleAccretion** [comment]
`Pack` does not specify minimal alignment for the whole structure:
```
The .pack directive specifies that fields should be placed within the runtime object at byte addresses 
which are a multiple of the specified number, or at natural alignment for that field type, whichever is 
smaller. For example, .pack 2 would allow 32-bit-wide fields to be started on even addresses, whereas 
without any .pack directive, they would be naturally aligned; that is, placed on addresses that are a 
multiple of 4.
```
So the behavior you're seeing is expected.

Additionally, as a matter of implementation detail, CoreCLR does not support alignment larger than 8 bytes for managed types (which would include arrays).

**Comment by tannergooding** [comment]
It's also worth noting that "over-packing" isn't supported. That is, you cannot force packing a struct that contains an `int` to `16-bytes`. Instead, `Packing` is effectively picked as the `Min(SpecifiedPacking, NaturalPacking)`.

The only types that can have packings greater than `8` are `Vector128<T>`, `Vector256<T>`, and soon `Vector512<T>`. These also only have the "higher" packing when the underlying ABI requires it (as these types map to the `__m128`, `__m256`, and `__m512` ABI primitive types).

**Comment by bysdxt** [comment]
@tannergooding I just know that Vector128<T> maybe pack 8 in array

![1](https://user-images.githubusercontent.com/13766766/198871580-639f289f-d030-4f42-925b-2db927a1d398.png)
