### ISSUE TITLE
[wasm][debugger] Support indexing by `object` schema

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#77536]
- [x] indexing with class instance - working, tests added in https://github.com/dotnet/runtime/pull/92268
- [ ] indexing with value type - https://github.com/dotnet/runtime/pull/92334
- [x] indexing with array - https://github.com/dotnet/runtime/pull/92337

**Comment by thaystg** [comment]
This is fixed by the new debugger.
