### ISSUE TITLE
PAX GEA constructor setting the name value to the unformatted string

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#77555]
When constructing a Pax GEA entry, we internally call the `base` constructor by passing the formattable string `GlobalHeadFormatPrefix`:
https://github.com/dotnet/runtime/blob/434e7f6e613ca723247725151355b6c4843a7d8f/src/libraries/System.Formats.Tar/src/System/Formats/Tar/PaxGlobalExtendedAttributesTarEntry.cs#L28-L29

But it is not getting filled out anywhere yet. At that point, the name value would be mostly useless. If the user consults the `Name` property to see the value, it will be malformed/incomplete.

The place where we properly fill out the `name` field for this entry is when we the entry to the archive:

https://github.com/dotnet/runtime/blob/434e7f6e613ca723247725151355b6c4843a7d8f/src/libraries/System.Formats.Tar/src/System/Formats/Tar/TarHeader.Write.cs#L902-L917

At that point, we should know the counter position number of the current GEA entry, as well as the tmp folder path, both which get formatted into that string.

So we should just set the name to empty in that `base` constructor name.

Thanks @stephentoub for finding this.

**Comment by stephentoub** [comment]
> So we should just set the name to empty in that base constructor name.

That would throw here:
https://github.com/dotnet/runtime/blob/13f648fa15c2989455415f4941dad2abfbaa6bba/src/libraries/System.Formats.Tar/src/System/Formats/Tar/TarEntry.cs#L36
