### ISSUE TITLE
Test using Random() should be seeded

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#7756]
There are many tests using unseeded Random number generators.  When failures happen it is difficult to debug/repro.

Here are examples which are currently causing intermittent failures in arm64...
```
tests/src/JIT/Methodical/MDArray/basics/classarr.cs
tests/src/JIT/Methodical/MDArray/basics/doublearr.cs
tests/src/JIT/Methodical/MDArray/basics/jaggedarr.cs
tests/src/JIT/Methodical/MDArray/basics/stringarr.cs
tests/src/JIT/Methodical/MDArray/basics/structarr.cs
```

Many tests are using seeded random number generators using code in tests/src/Common/CoreCLRTestLibrary/TestFramework.cs.

It would be nice to use simialr code in place of all tests using Random() without a seed.
category:correctness
theme:testing
skill-level:beginner
cost:small

**Comment by PeteBoyRocket** [comment]
I've been looking for some easy code changes I can do to contribute - this one seems to fit the bill...except I'm not clear If a decision has been reached on the best way to fix this?

1. Output the seed used to the trace log
2. Use a fixed seed
3. Use a fixed seed if injected in from the commandline (if not injected use a hardcoded fixed seed...or continue to use a random one?)
4. Investigate why some tests fail for certain random numbers (how frequent are the intermittent failures -> would some simple brute force running of the tests a lot, with some logging be a practical way to find the problems?)

...or another solution?

**Comment by sdmaclea** [comment]
@PeteBoyRocket I think the consensus was reached on this prior to @tannergooding's last comment.  We are driving to make CI reproducible.  

I would suggest the preferred solution would be to use:
+  a fixed seed, unless a random one is provided by the environment variable `CORECLR_SEED`.
+ print the seed used in the logs

This will allow the preferred default behavior and possibly enable us to set up random coverage legs at a later time.

**Comment by AndyAyersMS** [comment]
We've lived with this so hard to argue we have to fix it now.

Still a good up-for-grabs issue, if somebody out there wants to pick it up.

**Comment by ADustyOldMuffin** [comment]
I'd like to make my first contribution and pick this up, seems simple enough.

**Comment by danmoseley** [comment]
Welcome @ADustyOldMuffin  it's all yours
