### ISSUE TITLE
[System.Text.Json] Allow `TimeOnly` as Dictionary key

### ISSUE THREAD

**Issue by maxkoshevoi** [dotnet/runtime#77566]
### Description

Currently (.NET 7 RC2) both `DateTime` and `DateOnly` are allowed as Dictionary keys, but not `TimeOnly`. This seems strange.

![image](https://user-images.githubusercontent.com/6609929/198391251-86620a39-2411-4739-9bcd-d4dbc868e8f8.png)
![image](https://user-images.githubusercontent.com/6609929/198390054-2c784244-b938-4bc6-9c36-76910fb007b7.png)
![image](https://user-images.githubusercontent.com/6609929/198390382-072183e9-2ce1-4d19-8a1c-644c310fa4f8.png)

### Reproduction Steps

Try returning Dictionary that has at least one item with TimeOnly as a key from an API action.

### Expected behavior

Getting the serialized response 

### Actual behavior

Exception

### Regression?

No

### Known Workarounds

Creating custom convertor

### Configuration

.NET 7 RC2

**Comment by eiriktsarpalis** [comment]
Thanks. As it happens, I have a PR #77488 open that is meant to address this issue.

**Comment by eiriktsarpalis** [comment]
@maxkoshevoi NB this won't be backported to .NET 7. You might be able to work around the issue by overriding the `JsonConverter.WriteAsPropertyName`/`ReadAsPropertyName` methods in a custom converter for `TimeOnly`.

**Comment by maxkoshevoi** [comment]
@eiriktsarpalis yep, working on that for https://github.com/maxkoshevoi/DateOnlyTimeOnly.AspNet/issues/10
