### ISSUE TITLE
Can't load managed library in natively hosted .NET runtime

### ISSUE THREAD

**Issue by matteoumili** [dotnet/runtime#77587]
Following the guide provided by [Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting) the loading of a managed (load_assembly_and_get_function_pointer) library fails with the error code 0x80070002 that seems undocumented (only error codes description I found is [here](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/native/corehost/error_codes.h) and that code is not mentioned).

[Here](https://github.com/matteoumili/unmanaged-to-net6) is a repository that reproduces the issue. Just download, open in VS (without upgrading SDK version if prompted) and run

**Comment by DaZombieKiller** [comment]
The hosting API will return HRESULT error codes in addition to those listed in the `error_codes.h` header. `0x80070002` is the value for `E_FILENOTFOUND`, so your managed assembly (or the associated `.runtimeconfig.json` file) was not found at the path you passed in.

**Comment by matteoumili** [comment]
That's quite strange, because files are there
1) Location where `.runtimeconfig.json` is searched
![image](https://user-images.githubusercontent.com/66167607/198551816-0b7cc260-5b54-4964-960f-a44f1348f94f.png)
2) Location where assembly is searched
![image](https://user-images.githubusercontent.com/66167607/198551680-cb6eb791-efcf-4375-9ebe-e2b5a0cb859b.png)
3) Proof that files are there
![image](https://user-images.githubusercontent.com/66167607/198551962-1f7e83f3-2516-4943-9554-b35b49632ab8.png)

**Comment by DaZombieKiller** [comment]
From a brief read of the code code, I believe it is failing to find `Managed.Library.Foo.dll`, because your `dotnet_type` string is backwards. You have `Managed.Library, Managed.Library.Foo` when you should have `Managed.Library.Foo, Managed.Library`.

**Comment by matteoumili** [comment]
Yeah, that was the problem! Thank you!
