### ISSUE TITLE
CultureInfo - Difference In Behaviour Between Windows 10 And WSL

### ISSUE THREAD

**Issue by yngndrw** [dotnet/runtime#77591]
### Description

When instantiating `CultureInfo` with an invalid (Custom) culture (Specifically: `tc-sjfdhjkahfjkda`, the behaviour differs between Windows and Linux. This has knock-on effects on parameter validation within asp.net.

Within a Windows environment (Tested in Windows 10), this culture name is rejected with an exception being thrown: `CultureNotFoundException` 
```
Culture is not supported. (Parameter 'name')
tc - sjfdhjkahfjkda is an invalid culture identifier.
  at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
  at System.Globalization.CultureInfo..ctor(String name)
  at Program.<Main>$(String[] args) in C:\Repos\CultureInfoIssue\CultureInfoIssue\Program.cs:line 5
```

In a Linux environment however (Tested in WSL2 with Ubuntu 20.04.3, Docker with the image `mcr.microsoft.com/dotnet/aspnet:6.0` and Docker with the image `mcr.microsoft.com/dotnet/aspnet:6.0-Alpine` and ICU installed), the custom culture name is accepted and parsed as a custom culture:
```
Calendar: {System.Globalization.GregorianCalendar}
CompareInfo: '(new CultureInfo("tc-sjfdhjkahfjkda")).CompareInfo' threw an exception of type 'System.Globalization.CultureNotFoundException'
CultureTypes: NeutralCultures | UserCustomCulture
DateTimeFormat: {System.Globalization.DateTimeFormatInfo}
DisplayName: "tc (SJFDHJKAHFJKDA)"
EnglishName: "tc (SJFDHJKAHFJKDA)"
IetfLanguageTag: "tc--SJFDHJKAHFJKDA"
IsNeutralCulture: true
IsReadOnly: false
KeyboardLayoutId: 1033
LCID: 4096
Name: "tc--SJFDHJKAHFJKDA"
NativeName: "tc (SJFDHJKAHFJKDA)"
NumberFormat: {System.Globalization.NumberFormatInfo}
OptionalCalendars: {System.Globalization.Calendar[1]}
Parent: {}
TextInfo: {TextInfo - tc--SJFDHJKAHFJKDA}
- ANSICodePage: 1252
- CultureName: "tc--SJFDHJKAHFJKDA"
- EBCDICCodePage: 37
- IsReadOnly: false
- IsRightToLeft: false
- LCID: '(new CultureInfo("tc-sjfdhjkahfjkda")).TextInfo.LCID' threw an exception of type 'System.Globalization.CultureNotFoundException'
- ListSeparator: ","
- MacCodePage: 10000
- OEMCodePage: 437
ThreeLetterISOLanguageName: ""
ThreeLetterWindowsLanguageName: "ZZZ"
TwoLetterISOLanguageName: "tc"
UseUserOverride: true
```

I've tried both `new CultureInfo("tc-sjfdhjkahfjkda")` and `new CultureInfo("tc-sjfdhjkahfjkda", useUserOverride: false)` but the behaviour remains.

---

The following issue appears to be related, but was raised from an opposite point of view (Parsing LCIDs) and therefore appears with the opposite results:
https://github.com/dotnet/runtime/issues/71124

### Reproduction Steps

Create a new dotnet 6 console app with the following: (Run natively in Windows 10 and within WLS2 on Ubuntu, I couldn't work out how to get WSL2 to open a console window so I used the debugger to check its output)
```cs
using System.Globalization;

try
{
    var cultureInfo = new CultureInfo("tc-sjfdhjkahfjkda");
    Console.WriteLine($"Parsed CultureInfo: {cultureInfo.Name}");
    // In Windows: (Tested: Windows 10)
    //   Throws CultureNotFoundException:
    //     Culture is not supported. (Parameter 'name')
    //     tc - sjfdhjkahfjkda is an invalid culture identifier.
    //       at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
    //       at System.Globalization.CultureInfo..ctor(String name)
    //       at Program.<Main>$(String[] args) in C:\Repos\CultureInfoIssue\CultureInfoIssue\Program.cs:line 5
    //
    // In Linux: (Tested on: WSL2 {Ubuntu 20.04.3}, Docker {mcr.microsoft.com/dotnet/aspnet:6.0 & mcr.microsoft.com/dotnet/aspnet:6.0-Alpine with ICU} )
    //   Returns a CultureInfo object with the following properties:
    //   - Calendar: {System.Globalization.GregorianCalendar}
    //   - CompareInfo: '(new CultureInfo("tc-sjfdhjkahfjkda")).CompareInfo' threw an exception of type 'System.Globalization.CultureNotFoundException'
    //   - CultureTypes: NeutralCultures | UserCustomCulture
    //   - DateTimeFormat: {System.Globalization.DateTimeFormatInfo}
    //   - DisplayName: "tc (SJFDHJKAHFJKDA)"
    //   - EnglishName: "tc (SJFDHJKAHFJKDA)"
    //   - IetfLanguageTag: "tc--SJFDHJKAHFJKDA"
    //   - IsNeutralCulture: true
    //   - IsReadOnly: false
    //   - KeyboardLayoutId: 1033
    //   - LCID: 4096
    //   - Name: "tc--SJFDHJKAHFJKDA"
    //   - NativeName: "tc (SJFDHJKAHFJKDA)"
    //   - NumberFormat: {System.Globalization.NumberFormatInfo}
    //   - OptionalCalendars: {System.Globalization.Calendar[1]}
    //   - Parent: {}
    //   - TextInfo: {TextInfo - tc--SJFDHJKAHFJKDA}
    //     - ANSICodePage: 1252
    //     - CultureName: "tc--SJFDHJKAHFJKDA"
    //     - EBCDICCodePage: 37
    //     - IsReadOnly: false
    //     - IsRightToLeft: false
    //     - LCID: '(new CultureInfo("tc-sjfdhjkahfjkda")).TextInfo.LCID' threw an exception of type 'System.Globalization.CultureNotFoundException'
    //     - ListSeparator: ","
    //     - MacCodePage: 10000
    //     - OEMCodePage: 437
    //   - ThreeLetterISOLanguageName: ""
    //   - ThreeLetterWindowsLanguageName: "ZZZ"
    //   - TwoLetterISOLanguageName: "tc"
    //   - UseUserOverride: true
}
catch (CultureNotFoundException exception)
{
    Console.WriteLine($"CultureNotFoundException: {exception}");
}
```

### Expected behavior

I would expect the behaviour to be consistent between the two platforms, although I'm not entirely sure which behaviour is intended.

### Actual behavior

Within a Windows environment (Tested in Windows 10), this culture name is rejected with an exception being thrown: `CultureNotFoundException` 
```
Culture is not supported. (Parameter 'name')
tc - sjfdhjkahfjkda is an invalid culture identifier.
  at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
  at System.Globalization.CultureInfo..ctor(String name)
  at Program.<Main>$(String[] args) in C:\Repos\CultureInfoIssue\CultureInfoIssue\Program.cs:line 5
```

---

Within a Linux environment (Tested in WSL2 with Ubuntu 20.04.3, Docker with the image `mcr.microsoft.com/dotnet/aspnet:6.0` and Docker with the image `mcr.microsoft.com/dotnet/aspnet:6.0-Alpine` and ICU installed), the custom culture name is accepted and parsed as a custom culture:
```
Calendar: {System.Globalization.GregorianCalendar}
CompareInfo: '(new CultureInfo("tc-sjfdhjkahfjkda")).CompareInfo' threw an exception of type 'System.Globalization.CultureNotFoundException'
CultureTypes: NeutralCultures | UserCustomCulture
DateTimeFormat: {System.Globalization.DateTimeFormatInfo}
DisplayName: "tc (SJFDHJKAHFJKDA)"
EnglishName: "tc (SJFDHJKAHFJKDA)"
IetfLanguageTag: "tc--SJFDHJKAHFJKDA"
IsNeutralCulture: true
IsReadOnly: false
KeyboardLayoutId: 1033
LCID: 4096
Name: "tc--SJFDHJKAHFJKDA"
NativeName: "tc (SJFDHJKAHFJKDA)"
NumberFormat: {System.Globalization.NumberFormatInfo}
OptionalCalendars: {System.Globalization.Calendar[1]}
Parent: {}
TextInfo: {TextInfo - tc--SJFDHJKAHFJKDA}
- ANSICodePage: 1252
- CultureName: "tc--SJFDHJKAHFJKDA"
- EBCDICCodePage: 37
- IsReadOnly: false
- IsRightToLeft: false
- LCID: '(new CultureInfo("tc-sjfdhjkahfjkda")).TextInfo.LCID' threw an exception of type 'System.Globalization.CultureNotFoundException'
- ListSeparator: ","
- MacCodePage: 10000
- OEMCodePage: 437
ThreeLetterISOLanguageName: ""
ThreeLetterWindowsLanguageName: "ZZZ"
TwoLetterISOLanguageName: "tc"
UseUserOverride: true
```

### Regression?

Unsure

### Known Workarounds

Unknown

### Configuration

- Dotnet 6.0.5
- Windows 10 (Version: 21H1, OS Build: 19043.1949), WLS2 (Ubuntu-20.04), Docker (Debian & Alpine /w ICU)
- x64 Processor
- AnyCPU build

### Other information

In Windows, it appears that the exception is thrown here:
https://github.com/microsoft/referencesource/blob/master/mscorlib/system/globalization/cultureinfo.cs#L354

...which implies that the following method has returned `null`:
https://github.com/microsoft/referencesource/blob/master/mscorlib/system/globalization/culturedata.cs#L511

...which implies that the following method has returned `null`:
https://github.com/microsoft/referencesource/blob/master/mscorlib/system/globalization/culturedata.cs#L578

...which ultimately appears to be calling a native method:
```cs
// Get our initial minimal culture data (name, parent, etc.)
[System.Security.SecuritySafeCritical]  // auto-generated
[ResourceExposure(ResourceScope.None)]
[MethodImplAttribute(MethodImplOptions.InternalCall)]
internal static extern bool nativeInitCultureData(CultureData cultureData);
```

**Comment by tarekgh** [comment]
This is a known limitation. ICU allows using locales with the names like `tc-sjfdhjkahfjkda` while Windows doesn't allow such invalid names. This occurs only with such corner cases and with such bad locale names.  
We are providing the API [CultureInfo.Getcultureinfo](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.getcultureinfo?view=net-7.0#system-globalization-cultureinfo-getcultureinfo(system-string-system-boolean)) which you can use and pass `true` to the `predefinedOnly` to ensure using only the cultures that has real data and not any fake culture. Doing that, you should get a consistent result. 

Per that, I am closing the issue but feel free to send any question we can happily help with. Thanks for your report.
