### ISSUE TITLE
EndSilenceTimeout and EndSilenceTimeoutAmbiguous for SpeechRecognitionEngine is 10 seconds instead of 100 seconds

### ISSUE THREAD

**Issue by ChrisSippel** [dotnet/runtime#77598]
### Description

The upper limit for both EndSilenceTimeout  and EndSilenceTimeoutAmbiguous  is supposed to be 100 seconds based upon the resource "EndSilenceOutOfRange". However, it looks like a '0' was missed, and the upper limit is actually 10 seconds.

### Reproduction Steps

1. Create a `SpeechRecognitionEngine` object
2. Set `SpeechRecognitionEngine.EndSilenceTimeout` to a value greater than 10 seconds
3. `ArgumentOutOfRangeException` is thrown

### Expected behavior

A `ArgumentOutOfRangeException` is only thrown if the provided `TimeSpan` is greater than 100 seconds.

### Actual behavior

A `ArgumentOutOfRangeException` is thrown if the provided `TimeSpan` is greater than 10 seconds.

### Regression?

This is not a regression. I tested this on .NET Framework 4.8 and the issue was there as well.

### Known Workarounds

The only work around is to use a `TimeSpan` that is 10 seconds or less.

### Configuration

- Which version of .NET is the code running on?
   - .NET 6.0
- What OS and version, and what distro if applicable?
    - Windows 10 Pro v21H1 OS build 19043.2130
- What is the architecture (x64, x86, ARM, ARM64)?
    - x64
- Do you know whether it is specific to that configuration?
    - I don't believe it is

**Comment by ChrisSippel** [comment]
@ericstj @jeffhandley as owners of this area

**Comment by danmoseley** [comment]
Hello. I guess this bug has existed for a long time. The docs seem to all indicate 10 seconds:

https://learn.microsoft.com/en-us/search/?terms=endsilencetimeout&category=Reference&scope=.NET

Do you want to offer a PR to fix the error string?

**Comment by danmoseley** [comment]
Alternatively if you can find SAPI documentation indicating it accepts 100 seconds that would suggest the code and docs should be updated instead.

**Comment by ChrisSippel** [comment]
I couldn't find any SAPI documentation saying the limit should be 100 seconds. I'll create a PR for updating the string

**Comment by danmoseley** [comment]
This SAPI doc says 10 seconds. https://learn.microsoft.com/en-us/previous-versions/windows/desktop/ms717035(v=vs.85)
