### ISSUE TITLE
[API Proposal]: Proxy for HttpClient

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#77608]
### Background and motivation

I suggest adding a convenient class for creating clients with proxy servers
Proxy formats for parsing, method [host]:[port]:[login]:[password],
[host]:[port]:[login],
[host]:[port]

### API Proposal

```csharp
public static class Proxy
{
    public static IWebProxy Parse(string proxy,TypeProxy typeProxy)
    {
        throw new NotImplementedException();
    }
    public static IWebProxy Create(TypeProxy typeProxy,string host
                                    ,short? port ,
                                    string login = null,
                                    string password = null)
    {
        throw new NotImplementedException();
    }
}
public enum TypeProxy
{
    Socks5,Socks4,Socks4a,Http
}
```

### API Usage

```csharp
using System;
using System.Net;
using System.Net.Http;


using var obj = new HttpClientHandler();
obj.Proxy = Proxy.Parse("127.0.0.1:8888:login:password",TypeProxy.Socks4a);
//format [host]:[port]:[login]:[password]
//format [host]:[port]:[login]
//format [host]:[port]
using var client = new HttpClient(obj);
client.GetAsync("");

public static class Proxy
{
    public static IWebProxy Parse(string proxy,TypeProxy typeProxy)
    {
        throw new NotImplementedException();
    }
    public static IWebProxy Create(TypeProxy typeProxy,string host
                                    ,short? port ,
                                    string login = null,
                                    string password = null)
    {
        throw new NotImplementedException();
    }
}
public enum TypeProxy
{
    Socks5,Socks4,Socks4a,Http
}
```

**Comment by MihaZupan** [comment]
> Proxy.Parse("127.0.0.1:8888:login:password",TypeProxy.Socks4a);

Why is this better than

```c#
new WebProxy("socks4a://127.0.0.1:8888")
{
    Credentials = new NetworkCredential("login", "password")
}
```

**Comment by Mr0N** [comment]
> > Proxy.Parse("127.0.0.1:8888:login:password",TypeProxy.Socks4a);
> 
> Why is this better than
> 
> ```cs
> new WebProxy("socks4a://127.0.0.1:8888")
> {
>     Credentials = new NetworkCredential("login", "password")
> }
> ```

api is very scary.

**Comment by MihaZupan** [comment]
I'm afraid that's not a good enough reason to duplicate the existing API surface.

What _is_ scary to me is introducing another string format to represent a proxy when Uri can already do the job.
As all the required APIs already exist, we will not be adding the proposed ones.

**Comment by Mr0N** [comment]
> I'm afraid that's not a good enough reason to duplicate the existing API surface.
> 
> What _is_ scary to me is introducing another string format to represent a proxy when Uri can already do the job. As all the required APIs already exist, we will not be adding the proposed ones.

Then complete this format as it is.

**Comment by Mr0N** [comment]
The format is strange now, why is the proxy passed through the constructor. What to do if the proxy is not valid? Throw an error in the constructor? Why is there no TryParse method? Why can't the password and login from the proxy be passed in the line from the proxy? Why is there no method that will validate the proxy for suitability?

**Comment by Mr0N** [comment]
```
using System;
using System.Net;
using System.Net.Http;
using System.Text.RegularExpressions;

var pars = new Pars();
var proxy = pars.Parse("socks4a://127.0.0.1:8888:login:password");
Console.WriteLine(proxy.ToString());
 proxy = pars.Parse("socks4a://127.0.0.1:8888:login");
Console.WriteLine(proxy.ToString());
 proxy = pars.Parse("socks4a://127.0.0.1:8888");
Console.WriteLine(proxy.ToString());
Console.ReadKey();
class Pars
{
    public Proxy Parse(string str)
    {

        if (this.TryParse(str, out var proxy))
            return proxy;
        throw new Exception();
    }
    public bool TryParse(string str, out Proxy proxy)
    {
        proxy = default;
        var obj = _regex.Match(str);
        if (!obj.Success)
        {
            proxy = default;
            return false;
        }
       
         proxy = new Proxy(obj.Groups["protocol"].Value,
                    obj.Groups["ip"].Value,
                    short.Parse(obj.Groups["port"].Value),
                    Validation(obj.Groups["login"].Value),
                    Validation(obj.Groups["password"].Value));
        return true;
    }
    Regex _regex;
    private string Validation(string obj)
    {
        return string.IsNullOrEmpty(obj) ? null : obj;
    }
    public Pars()
    {
        this._regex =
            new Regex(@"(?<protocol>.+):\/\/(?<ip>[^:]+):(?<port>[0-9]{1,5}):?(?<login>[^:]+)?:?(?<password>[^:]+)?");
    }
}
record Proxy(string protocol, string host, short? port, string? login, string? password);
```

**Comment by MihaZupan** [comment]
> The format is strange now

It's a Uri. Basic knowledge of its format is assumed for users working with proxies/HttpClient.

> why is the proxy passed through the constructor. 

You are creating an instance of `WebProxy`, so you have to provide the proxy information in the constructor. That's how constructors work, I don't understand the concern here.

> What to do if the proxy is not valid? Throw an error in the constructor?

Sure.

> Why is there no TryParse method?

Because there is nothing to parse. You supply pre-parsed values to the constructor.

> Why can't the password and login from the proxy be passed in the line from the proxy?

You can. I just showed one of the many available constructors. See the documentation: https://learn.microsoft.com/dotnet/api/system.net.webproxy.-ctor

> Why is there no method that will validate the proxy for suitability?

What makes a proxy (un)suitable? If you have your own logic to determine that, you can do such checks before calling into these APIs.

> Why is there no factory to create an object?

Because you have a constructor, there's no need for a factory here.
