### ISSUE TITLE
Feature Request: Auto-Vectorization

### ISSUE THREAD

**Issue by Daniel-Svensson** [dotnet/runtime#77617]
Since we now have some SIMD support via the SIMD nuget package it should be possible for roslyn to include an Auto Vectorizer for simple scenarios. While you could argue that such a feature could be included in the jit compiler I believe that it is a better match for the compiler which have much more time to spend on these kinds of optimizations.

The feature could be controlled by a compiler switch and require that the SIMD assembly is referenced by the project. 

For som details about auto-vectorization se for example the Visual C++ documentation at https://msdn.microsoft.com/en-us/library/hh872235.aspx

**Comment by JulieLeeMSFT** [comment]
cc @BruceForstall.

**Comment by BruceForstall** [comment]
@CyrusNajmabadi This issue was specifically about Roslyn implementation of auto vectorization, not JIT implementation.

Anyway, since it's now in the runtime repo, it's a dup of https://github.com/dotnet/runtime/issues/11263, so closing.
