### ISSUE TITLE
Is it possible for roslyn to support wasm as compiling target

### ISSUE THREAD

**Issue by Thaina** [dotnet/runtime#77610]
In addition to IL I would like a C# compiler able to compile as WASM directly, not need any conversion from IL to WASM again (ilwasm project also compile from C# -> IL -> JS -> WASM)

Is it possible?
Are there any C# feature missing from WASM?
Are there any wasm feature incapable to do from C#?

**Comment by JulieLeeMSFT** [comment]
CC @TIHan.

**Comment by TIHan** [comment]
Closing this as Roslyn itself will not support WASM as a compiling target.
