### ISSUE TITLE
TimeZoneInfoTests.ConvertTimeFromToUtc_UnixOnly test fails around DST change

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#77648]
```
    System.Tests.TimeZoneInfoTests.ConvertTimeFromToUtc_UnixOnly [FAIL]
      Assert.Equal() Failure
      Expected: 2022-10-30T01:47:13.3836230Z
      Actual:   2022-10-30T00:47:13.3836230Z
      Stack Trace:
        /_/src/libraries/System.Runtime/tests/System/TimeZoneInfoTests.cs(2199,0): at System.Tests.TimeZoneInfoTests.ConvertTimeFromToUtc_UnixOnly()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs(64,0): at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Log https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-71685-merge-500a167b9a3b414ca5/System.Runtime.Tests/1/console.5cee5309.log?helixlogtype=result

Failed in #71685

**Comment by jkotas** [comment]
We hit this regularly at the end of October (see e.g. #19144).

**Comment by hopperpl** [comment]
for reference

all of Europe switched timezone at 2022-10-30T01:00:00Z

contrary to NA, which will switch 1 week later

**Comment by Clockwork-Muse** [comment]
> contrary to NA, which will switch 1 week later

Also contrary to US/Canada, which switches at 2AM local time, the entire EU switches at the same instant.

[Code in question](https://github.com/dotnet/runtime/blob/d30ab115f049ecb7f0d2a7d9ca980442f00c5ad9/src/libraries/System.Runtime/tests/System/TimeZoneInfoTests.cs#L2184-L2199):

```cs
// convert to London time and back
DateTime utc = DateTime.UtcNow;
Assert.Equal(DateTimeKind.Utc, utc.Kind);
DateTime converted = TimeZoneInfo.ConvertTimeFromUtc(utc, london);
Assert.Equal(DateTimeKind.Unspecified, converted.Kind);
DateTime back = TimeZoneInfo.ConvertTimeToUtc(converted, london);
Assert.Equal(DateTimeKind.Utc, back.Kind);


if (london.IsAmbiguousTime(converted))
{
    // if the time is ambiguous this will not round trip the original value because this ambiguous time can be mapped into
    // 2 UTC times. usually we return the value with the DST delta added to it.
    back = back.AddTicks(-london.GetAdjustmentRules()[0].DaylightDelta.Ticks);
}


Assert.Equal(utc, back);
```

.... do we really need to be using the current time here?  And at least half of this test is covered by the case immediately before it.
Additionally, although this is labeled as "Unix Only", we're using a custom timezone here, not anything loaded from the environment, so I would expect this test to work (or not) on the other platforms.

**Comment by dakersnar** [comment]
cc @tarekgh

**Comment by tarekgh** [comment]
I'll take a look.
