### ISSUE TITLE
`Directory.GetFileSystemEntries` returns nonexistent paths when given a volume only

### ISSUE THREAD

**Issue by carlreinke** [dotnet/runtime#77657]
### Description

On Windows, `Directory.GetFileSystemEntries` (and similar APIs) return invalid paths when given a volume only (ex. `C:`) if the current directory for the volume is not the root of the volume.

### Reproduction Steps

```
using System;
using System.IO;

internal static class Program
{
    private static void Main()
    {
        Directory.SetCurrentDirectory(@"C:\Windows");
        foreach (var path in Directory.GetFileSystemEntries("C:", "explorer.*"))
            Console.WriteLine(path);
    }
}
```

### Expected behavior

Return a path that exists.
```
C:explorer.exe
```

### Actual behavior

.NET 7 returns a path that does not exist.
```
C:\explorer.exe
```

### Regression?

It works as expected on .NET Framework 4.8.

.NET 6 has the same wrong behavior as .NET 7.

I did not test other versions.

### Configuration

* .NET 7 RC2

**Comment by skyoxZ** [comment]
Possible duplicate #69785

**Comment by carlreinke** [comment]
Could be, but there's another even closer issue linked from there that I didn't manage to find when searching.

Duplicate of #68503.
