### ISSUE TITLE
The Uri class has a lot of functionality, which does not need a proxy and which is executed

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#77654]
### Description

The Uri class performs too much extra work on proxy parsing, the proxy does not need so much functionality, that is, unnecessary work is done that could not be performed. I suggest you write your own class for proxy parsing, and mark the WebProxy class as deprecated.
https://github.com/dotnet/runtime/blob/6c913736f692b351cee0d504817088a2b3133732/src/libraries/System.Net.WebProxy/src/System/Net/WebProxy.cs#L22

### Reproduction Steps

-

### Expected behavior

-

### Actual behavior

-

**Comment by MihaZupan** [comment]
> unnecessary work is done that could not be performed

What work? The `Uri` will parse the scheme and authority upfront. Both of which you need for the `IWebProxy`.

> The Uri class performs too much extra work on proxy parsing, the proxy does not need so much functionality, that is, unnecessary work is done that could not be performed.

Any cost here is effectively 0 compared to the cost of everything else going on in an application that makes requests over a proxy.

> I suggest you write your own class for proxy parsing, and mark the WebProxy class as deprecated.

No.
Creating additional APIs comes with risk and it takes time.
Deprecating an API like this would cause a lot of pain for consumers of the API.
The reasons cited provide virtually zero benefit.

If this parsing overhead is detrimental to your application's performance (it's not), there is a workaround available. You can write your own class that implements the `IWebProxy` interface.
