### ISSUE TITLE
Excess memory allocation.

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#77652]
### Description

https://github.com/dotnet/runtime/blob/6c913736f692b351cee0d504817088a2b3133732/src/libraries/System.Net.WebProxy/src/System/Net/WebProxy.cs#L107
https://github.com/dotnet/runtime/blob/6c913736f692b351cee0d504817088a2b3133732/src/libraries/System.Net.WebProxy/src/System/Net/WebProxy.cs#L40
Excess memory allocation, the port cannot be larger than 65535, the type is ideal for this ushort

### Reproduction Steps

-

### Expected behavior

-

### Actual behavior

-

**Comment by filipnavara** [comment]
The `WebProxy` constructor is a public API and changing it would be a breaking change. It doesn't really consume more memory either. On all supported platforms (except WASM) the parameter is passed through processor register. Since processor registers are fixed size (32-bit or 64-bit) there is no difference between passing `ushort` or `int` except for how it is interpreted. Even if the parameter was passed on the stack it would have to be aligned according to the platform ABI which usually means that it is aligned to 32-bit or larger boundaries.

For the other case you have `int?`, or `Nullable<int>`, which is struct. Depending on ABI that can be passed in registers or on a stack but it still doesn't make much of a difference because of alignment and the fact that it's on a stack.

**Comment by Mr0N** [comment]
> The `WebProxy` constructor is a public API and changing it would be a breaking change. It doesn't really consume more memory either. On all supported platforms (except WASM) the parameter is passed through processor register. Since processor registers are fixed size (32-bit or 64-bit) there is no difference between passing `ushort` or `int` except for how it is interpreted. Even if the parameter was passed on the stack it would have to be aligned according to the platform ABI which usually means that it is aligned to 32-bit or larger boundaries.
> 
> For the other case you have `int?`, or `Nullable<int>`, which is struct. Depending on ABI that can be passed in registers or on a stack but it still doesn't make much of a difference because of alignment and the fact that it's on a stack.

The ones that ushort came up with just for fun) You can't write a new class for a proxy.

**Comment by teo-tsirpanis** [comment]
Closing, as @filipnavara said changing it would be a breaking change and it would not make the code any more efficient.

**Comment by Mr0N** [comment]
> Contributor

`using System;
using System.Net;
using System.Net.Http;
using System.Text.RegularExpressions;

string proxy = "socks://127.0.0.1";

var webProxy = new WebProxy(proxy, 1000000);
Console.WriteLine("End");
Console.ReadKey();
//    throw new Exception();
//var client = new HttpClient(webProxy);

`

**Comment by Mr0N** [comment]
Is it possible to create new issues here?
You can create a proxy with a million port, which is not possible with the tcp protocol

**Comment by teo-tsirpanis** [comment]
> You can create a proxy with a million port

No you can't, it will eventually throw an exception. https://github.com/dotnet/runtime/blob/e6700ea21bbb17ca5058801259bc2d05957814d4/src/libraries/System.Private.Uri/src/System/UriBuilder.cs#L180-L188

**Comment by Mr0N** [comment]
> 

It seems to me that this class should do this, not HttpClient, if you specify the port using the string, then an exception is immediately made, this class does not behave very unambiguously.

**Comment by Mr0N** [comment]
```
using System;
using System.Net;
using System.Net.Http;
using System.Text.RegularExpressions;

string proxy = "socks://127.0.0.1:1000000";

var webProxy = new WebProxy(proxy);
Console.WriteLine("End");
Console.ReadKey();
//    throw new Exception();
//var client = new HttpClient(webProxy);


```

**Comment by Mr0N** [comment]
> 

![image](https://user-images.githubusercontent.com/61237140/198895531-9b70db33-c8b5-457d-8b57-efbaa21618a4.png)

**Comment by Mr0N** [comment]
There will be no exception, the port is written as 80

**Comment by filipnavara** [comment]
As I already explained in your other issue - https://github.com/dotnet/runtime/issues/77653#issuecomment-1296315898 - the constructor does NOT take an address with a scheme. It takes a host name. It should probably validate that host name better and throw an exception right away but that's unrelated to the passed port.

**Comment by Mr0N** [comment]
> As I already explained in your other issue - [#77653 (comment)](https://github.com/dotnet/runtime/issues/77653#issuecomment-1296315898) - the constructor does NOT take an address with a scheme. It takes a host name (ie. it takes `foo`, not `socks://foo`). It should probably validate that host name better and throw an exception right away but that's unrelated to the passed port.

Well maybe.

**Comment by Mr0N** [comment]
constructors are very strange , the constructor parses the protocol, here it doesn't, it's very easy to get confused.horror api
