### ISSUE TITLE
The port is incorrect.

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#77653]
### Description

The port is incorrect.

### Reproduction Steps

```
using System;
using System.Net;
using System.Net.Http;
using System.Text.RegularExpressions;

string proxy = "socks://[1fff:0:a88:85a3::ac1f]/";

var webProxy = new WebProxy(proxy,1212);
if (webProxy.Address.Port != 1212)
    throw new Exception();
//var client = new HttpClient(webProxy);




```

### Expected behavior

-

### Actual behavior

-

**Comment by filipnavara** [comment]
The `WebProxy` constructor is a public API and changing it would be a breaking change. It doesn't really consume more memory either. On all supported platforms (except WASM) the parameter is passed through processor register. Since processor registers are fixed size (32-bit or 64-bit) there is no difference between passing `ushort` or `int` except for how it is interpreted. Even if the parameter was passed on the stack it would have to be aligned according to the platform ABI which usually means that it is aligned to 32-bit or larger boundaries.

For the other case you have `int?`, or `Nullable<int>`, which is struct. Depending on ABI that can be passed in registers or on a stack but it still doesn't make much of a difference because of alignment and the fact that it's on a stack.

**Comment by filipnavara** [comment]
That's not how this particular constructor is supposed to be used. You are not supposed to pass a host name with a protocol specified.

It constructs the following address: `http://socks//[1fff:0:a88:85a3::ac1f]/:1212`. I would argue that the constructor itself should throw [UriFormatException](https://learn.microsoft.com/en-us/dotnet/api/system.uriformatexception?view=net-6.0) per documentation.

**Comment by Mr0N** [comment]
> That's not how this particular constructor is supposed to be used. You are not supposed to pass a host name with a protocol specified.
> 
> It constructs the following address: `http://socks//[1fff:0:a88:85a3::ac1f]/:1212`. I would argue that the constructor itself should throw [UriFormatException](https://learn.microsoft.com/en-us/dotnet/api/system.uriformatexception?view=net-6.0) per documentation.

Well, there should probably be an exception, or it parses normally, because this is in principle a normal format from the point of view of the proxy, not from the point of view of Uri

**Comment by MihaZupan** [comment]
This was fixed in https://github.com/dotnet/runtime/pull/62338, which is included as part of .NET 7.

**Comment by Mr0N** [comment]
![image](https://user-images.githubusercontent.com/61237140/198897301-d2be2e99-8200-4a83-9597-19cd2c2c9b14.png)

**Comment by Mr0N** [comment]
And if such a string is transferred there? http://host.ua/page?=://

**Comment by MihaZupan** [comment]
Try it out. `"http://host.ua/page?=://".Contains("://")` returns true.

Do you have an example of an input that produces an unexpected output?
If so, what exact input and what was the expected output?

**Comment by Mr0N** [comment]
> Try it out. `"http://host.ua/page?=://".Contains("://")` returns true.
> 
> Do you have an example of an input that produces an unexpected output? If so, what exact input and what was the expected output?

https://sharplab.io/#gist:f14c0a75dfe4e59be78536ea569deaec

**Comment by Mr0N** [comment]
https://sharplab.io/#gist:5fdd2505cb32506f9682d7530188855e

**Comment by MihaZupan** [comment]
See the documentation: https://learn.microsoft.com/dotnet/api/system.net.webproxy.-ctor?view=net-6.0#system-net-webproxy-ctor(system-string-system-int32)

This constructor takes the `Host`, not the whole address. The implementation here tries to be helpful and account for common mistakes (e.g. doing `new WebProxy("socks5://127.0.0.1", 9050)`).
But it's of course possible to misuse the API even further, in which case I would argue that getting a `UriFormatException` is acceptable behavior.

If you wish to avoid it, use the correct constructor that accepts the whole address.

**Comment by Mr0N** [comment]
> See the documentation: https://learn.microsoft.com/dotnet/api/system.net.webproxy.-ctor?view=net-6.0#system-net-webproxy-ctor(system-string-system-int32)
> 
> This constructor takes the `Host`, not the whole address. The implementation here tries to be helpful and account for common mistakes (e.g. doing `new WebProxy("socks5://127.0.0.1", 9050)`). But it's of course possible to misuse the API even further, in which case I would argue that getting a `UriFormatException` is acceptable behavior.
> 
> If you wish to avoid it, use the correct constructor overload that accepts the whole address.

Well, I'm leading to the fact that the Uri class is not very suitable for proxies, and for me to use it for proxies is a bit wrong.
