### ISSUE TITLE
[QUIC]  QUIC how to use  port reuse，and QuicListener  send unconnected message

### ISSUE THREAD

**Issue by snltty** [dotnet/runtime#77664]
### Background and motivation

like title
QUIC how to use  port reuse，and QuicListener send unconnected message,

sometime, we need port reuse and send unconnected message

### API Proposal

```csharp
QuicListener quicListener = await  QuicListener.ListenAsync(new QuicListenerOptions{
ReuseAddress : true
});
quicListener.SendUnConnectdMessage(data,endpoint);

```

### API Usage

```csharp
QuicListener quicListener = await  QuicListener.ListenAsync(new QuicListenerOptions{
ReuseAddress : true
});
quicListener.SendUnConnectdMessage(data,endpoint);

```

**Comment by ManickaP** [comment]
AFAIK there's no way to send unconnected message over QUIC. The closest is probably DATAGRAM support: https://www.ietf.org/archive/id/draft-ietf-quic-datagram-10.html, it still requires a connection. We already have an issue for this: https://github.com/dotnet/runtime/issues/53533
And with port reuse, it is ON for all servers via underlying msquic implementation: https://github.com/microsoft/msquic/issues/3177, and this is not configurable atm.

Does this cover your questions?

**Comment by snltty** [comment]
im trying udp nat transfer，maybe quic is not are good way

**Comment by ManickaP** [comment]
Quic is a protocol above UDP, it's also always encrypted. This really might not be a good fit for your purpose. I'm closing this for now. Feel free to re-open or open a new issue if you hit any problems with Quic. Thanks.
