### ISSUE TITLE
Configuration binding with nested types and readonly properties not working

### ISSUE THREAD

**Issue by glucaci** [dotnet/runtime#77677]
### Description

With #67258 the binding of immutable types is working but with nested types seams not to work.

### Reproduction Steps

```csharp
public record RootConfig(NestedConfig Nested);

public record NestedConfig(string MyProp);

public RootConfig GetConfiguration()
{
    IConfiguration configuration = new ConfigurationBuilder()
        .AddInMemoryCollection(new Dictionary<string, string?>
        {
            { "Nested:MyProp", "Dummy" }
        })
        .Build();

    return configuration.Get<RootConfig>();            
}
```

In the above case the following exception will be thrown:
```
Cannot create instance of type 'RootConfig' because parameter 'Nested' has no matching config. 
Each parameter in the constructor that does not have a default value must have a corresponding config entry.
```

If the `Nested` property is declared with `init` modifier like bellow it will work.
```csharp
public record RootConfig
{
    public NestedConfig Nested { get; init; }
}
```

### Expected behavior

No exception.

### Actual behavior

Throws `InvalidOperationException`.

### Known Workarounds

Declare the `Nested` property with `init` modifier.

### Configuration

.NET 7 RC2

**Comment by tarekgh** [comment]
@SteveDunn will you have some spare time to look at this one?

**Comment by SteveDunn** [comment]
@tarekgh / @glucaci - hi - I just got main and added this test and it passed without the exception described above

![image](https://user-images.githubusercontent.com/263416/199112167-b2e491f6-86b1-4179-be00-0ffddbd12e6f.png)

Admittedly, this was a very quick exercise as my time is rather limited with my day job.

Have I missed something?

**Comment by tarekgh** [comment]
@SteveDunn thanks for the follow up. I am trying that with .NET 7.0 rc2 and I am seeing it failing. I'll try the rtm bits to see if it reproduces there. 

```
FrameworkDescription: .NET 7.0.0-rc.2.22472.3
RuntimeIdentifier: win10-x64

Unhandled exception. System.InvalidOperationException: Cannot create instance of type 'NetCoreApp.Program+RootConfig' because parameter 'Nested' has no matching config. Each parameter in the constructor that does not have a default value must have a corresponding config entry.
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindParameter(ParameterInfo parameter, Type type, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.CreateInstance(Type type, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, BindingPoint bindingPoint, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Get(IConfiguration configuration, Type type, Action`1 configureOptions)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Get[T](IConfiguration configuration, Action`1 configureOptions)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Get[T](IConfiguration configuration)
   at NetCoreApp.Program.BindWithNestedTypesWithReadOnlyProperties() in C:\Temp\NetCoreApp\Program.cs:line 114
   at NetCoreApp.Program.Main(String[] args) in C:\Temp\NetCoreApp\Program.cs:line 159
```

**Comment by tarekgh** [comment]
Interesting, it looks something has been changed in .NET 8.0 which fixed the issue. We need to understand what has changed.

**Comment by SteveDunn** [comment]
It is this:

![image](https://user-images.githubusercontent.com/263416/199168016-148730c3-1f6f-4d0a-9483-2121e0ab9710.png)

Left is RC2, right is Main as of yesterday (31st October '22)

I'm happy if you want to close this PR.

**Comment by SteveDunn** [comment]
Actually, it might be worth merging in as the test is useful as a regression.

**Comment by glucaci** [comment]
> It is this:
> 
> ![image](https://user-images.githubusercontent.com/263416/199168016-148730c3-1f6f-4d0a-9483-2121e0ab9710.png)
> 
> Left is RC2, right is Main as of yesterday (31st October '22)
> 
> The commit on the right is [ca0d3e4d ](https://github.com/dotnet/runtime/commit/ca0d3e4ddd50311ebb4320db0637713cb1ec23ce)by @Saalvage
> 
> I'm happy if you want to close this PR.

@tarekgh could this be cherry-picked into .NET 7?

**Comment by tarekgh** [comment]
> Actually, it might be worth merging in as the test is useful as a regression.

Agree. Thanks for pointing at the change that fixed this issue. 

> could this be cherry-picked into .NET 7?

.NET 7.0 is done. It is going to be released in a few days. We may consider servicing this later if proven it is a blocker to important scenarios. Considering the workaround is trivial and it is not a regression, this will be difficult to meet the servicing bar.

**Comment by aradalvand** [comment]
Hey, I just encountered the same problem.

> Considering the workaround is trivial 

What is the workaround?!

**Comment by tarekgh** [comment]
@aradalvand 

In the issue description, it mentioned the following 

```
Known Workarounds
Declare the Nested property with init modifier.
```
