### ISSUE TITLE
Hang with WindowsFormsSynchronizationContext

### ISSUE THREAD

**Issue by AndrejBunjac** [dotnet/runtime#77673]
### Description

I've encountered a strange bug with WindowsFormsSynchronizationContext in which it creates a hang for a very simple async call and never completes the task.

I wasn't able to find any documentation about it but it definitely seems strange.

If this context gets set to main thread and the same thread makes creates a runs an async method (without awaiting) that has a CopyToAsync between a filestream and a memorystream - the task will never finish. I'll give minimum reproduction in the next section.

### Reproduction Steps

   Create a console app.
    Run the following code:

    private static int Main(string[] args)
    {
        var wfctx = new WindowsFormsSynchronizationContext();
        System.Threading.SynchronizationContext.SetSynchronizationContext(wfctx);
        var task = HangTestAsync();
        task.Wait();
        // something else
     }

     public static async Task HangTestAsync()
     {
        string path = @"path-to-some-file";
        await using Stream stream = File.OpenRead(path);
        await using Stream ms = new MemoryStream();
        await stream.CopyToAsync(ms);
        ms.Seek(0, SeekOrigin.Begin);
     }
     
    Put a breakpoint after task.Wait(), the breakpoint never gets reached, hang happens at stream.CopyToAsync();

### Expected behavior

Regardless whether I'm running this in a windows forms app or not I would expect a simple task to run to completion normally - instead it hangs.

### Actual behavior

The task with copyToAsync hangs.

**Comment by kevingosse** [comment]
This is a common cause of deadlocks. When running with a synchronization context, either use `ConfigureAwait(false)` or don't wait synchronously on a task: https://devblogs.microsoft.com/dotnet/configureawait-faq/

**Comment by stephentoub** [comment]
Closing as answered.
