### ISSUE TITLE
ToUpper not working as intended with Turkish Culture

### ISSUE THREAD

**Issue by sencagri** [dotnet/runtime#77689]
### Description

In our tests ToUpper() method returns false characters. The lowercase "i" character should be "İ" but we are getting "I" only in .NET MAUI apps. Other project types are working fine.

### Steps to Reproduce

1. Create a new .NET MAUI project (.Net 6 or preview both are same)
2. We have added CodePages nuget (System.Text.Encoding.CodePages)
3. Add the following code at MauiProgram.cs
```csharp
            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance); // don't know if this helps, just tried...
            CultureInfo tr = new CultureInfo("tr-TR", false);
            string test = "i";
            var test2 = test.ToUpper(tr);
            var testResult = test2 == "İ"; // result is false because test2 is "I" instead of "İ"
```

### Link to public reproduction project repository

https://github.com/sencagri/MauiAppToUpper

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All android versions

**Comment by sencagri** [comment]
Windows works fine

**Comment by sencagri** [comment]
> Related: [xamarin/xamarin-android#5425](https://github.com/xamarin/xamarin-android/issues/5425)

Is this really related? I have tested both Xamarin.Forms and Xamarin.Android project, they are working fine.

**Comment by tarekgh** [comment]
@marek-safar could you get someone look at this as it is mono runtime?

**Comment by tarekgh** [comment]
@sencagri just fyi, upper and lower casing strings have nothing to do with the Encoding. 

doing 
```C# 
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance); // don't know if this helps, just tried... 
```

is not needed anyway.

**Comment by marek-safar** [comment]
@steveisok please prioritize

**Comment by steveisok** [comment]
I'm not sure there's a whole lot we can do here as we are fully relying on the version of ICU that is packaged with Android.  We are going to experiment on a few ideas and see if they make a difference.

**Comment by NightOwl888** [comment]
> 

What version of Xamarin.Android is it succeeding in? We can't get a single test run to pass testing

- `netstandard2.1` library with `MonoAndroid100`
- `netstandard2.0` library with `MonoAndroid90`

https://dev.azure.com/NightOwl888/J2N/_build/results?buildId=249&view=ms.vss-test-web.build-test-results-tab&runId=18330&resultId=134521&paneView=debug

**Comment by NightOwl888** [comment]
> > Related: [xamarin/xamarin-android#5425](https://github.com/xamarin/xamarin-android/issues/5425)
> 
> Is this really related? I have tested both Xamarin.Forms and Xamarin.Android project, they are working fine.

> 

What version of Xamarin.Android is it succeeding in? We can't get a single test run to pass testing

- `netstandard2.1` library with `MonoAndroid100`
- `netstandard2.0` library with `MonoAndroid90`

https://dev.azure.com/NightOwl888/J2N/_build/results?buildId=249&view=ms.vss-test-web.build-test-results-tab&runId=18330&resultId=134521&paneView=debug

**Comment by sencagri** [comment]
> > > Related: [xamarin/xamarin-android#5425](https://github.com/xamarin/xamarin-android/issues/5425)
> > 
> > 
> > Is this really related? I have tested both Xamarin.Forms and Xamarin.Android project, they are working fine.
> 
> > 
> 
> What version of Xamarin.Android is it succeeding in? We can't get a single test run to pass testing
> 
> * `netstandard2.1` library with `MonoAndroid100`
> * `netstandard2.0` library with `MonoAndroid90`
> 
> https://dev.azure.com/NightOwl888/J2N/_build/results?buildId=249&view=ms.vss-test-web.build-test-results-tab&runId=18330&resultId=134521&paneView=debug

Hi,
I just created a Xamarin.Android app now and put the code inside MainActivity.cs. If you can tell me how to check Xamarin.Android version I can check it.
![image](https://user-images.githubusercontent.com/7950917/199982509-067f5023-f8d7-4c9a-91d6-897f832ffce8.png)

**Comment by steveisok** [comment]
There's unfortunately not a lot we can do to control this behavior since we are relying on Android ICU. We had originally wanted to ship our own like we do for iOS, but we didn't want to take on a few dependencies.

**Comment by hartez** [comment]
> relying on Android ICU

Relying on it how? What's the mechanism?

**Comment by steveisok** [comment]
> Relying on it how? What's the mechanism?

The entire globalization interop calls into ICU functions.  In the case of Android, it's the one they ship.

**Comment by sencagri** [comment]
Any kind of workaround?

**Comment by Clockwork-Muse** [comment]
You'd have to include your own copies of the ICU libraries, essentially (as @steveisok mentioned).

[There are some relatively simple instructions for including them for your application](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#app-local-icu).  They only specifically list Windows/Linux (ie, intending it to be server/desktop applications), though, so I don't know how it would go for Android.

Keep in mind that if you go that route, you will have to make sure to update and distribute your application regularly to account for ICU updates, which is multiple times a year.

That said, in at least some cases some of the Turkish characters might be created via [combining characters](https://stackoverflow.com/a/42887898/812837).  Have you checked the actual length of the string and characters actually present?

**Comment by hartez** [comment]
> The entire globalization interop calls into ICU functions. In the case of Android, it's the one they ship.

So presumably there's a bug in the functions they ship, and at some point in the future they'll fix it and `ToUpper()` will work correctly again?

**Comment by Clockwork-Muse** [comment]
> So presumably there's a bug in the functions they ship

More likely there's something up with their data tables (there's two parts to ICU - a set of functions, and a set of data tables)

> Is it a known bug? Is it being tracked?

I doubt it.
The reason being that there are multiple updates per year, and you're normally just supposed to include the update when you can.
