### ISSUE TITLE
KB5011048 breaks PowerShell in Windows Sandboxes

### ISSUE THREAD

**Issue by pnorms** [dotnet/runtime#77681]
### Description

.NET Framework 4.8.1 update KB5011048 breaks PowerShell in Windows Sandboxes. 

While this update is installed the following error is encountered:
C:\Users\WDAGUtilityAccount>powershell
Version v4.0.30319 of the .NET Framework is not installed and it is required to run version 3 of Windows PowerShell.

### Reproduction Steps

On Windows 10 21H2
Enabled Sandboxing: Enable-WindowsOptionalFeature -FeatureName 'Containers-DisposableClientVM' -Online

Install .NET Framework 4.8.1 update KB5011048

Start the Sandbox: WindowsSandbox.exe

Open cmd (to see the error), run PowerShell

### Expected behavior

PowerShell should launch

### Actual behavior

An error is thrown:
Version v4.0.30319 of the .NET Framework is not installed and it is required to run version 3 of Windows PowerShell.

### Regression?

Yes

### Known Workarounds

Uninstall KB5011048, but this leads to other workflow breakages

### Configuration

Which version of .NET is the code running on? 4.8.1
What OS and version, and what distro if applicable? Win10 21H2
What is the architecture (x64, x86, ARM, ARM64)? x64
Do you know whether it is specific to that configuration? No
If you're using Blazor, which web browser(s) do you see this issue in? NA

### Other information

This seems to be a re-occuring issue with .Net updates breaking the sandbox

**Comment by kasperk81** [comment]
https://github.com/microsoft/dotnet/issues is the right place for .net framework issues.

**Comment by Symbai** [comment]
> https://github.com/microsoft/dotnet/issues is the right place for .net framework issues.

Nope, see their announcement: https://github.com/microsoft/dotnet/issues/1275

**Comment by hoyosjs** [comment]
cc @marklio

**Comment by jkotas** [comment]
> Nope, see their announcement: https://github.com/microsoft/dotnet/issues/1275

The announcement and https://github.com/dotnet/core/blob/main/Documentation/core-repos.md#net-framework says to use 
 [Dev Community](https://developercommunity.visualstudio.com/spaces/61/index.html) for .NET Framework .

**Comment by pnorms** [comment]
> > Nope, see their announcement: [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
> 
> The announcement and https://github.com/dotnet/core/blob/main/Documentation/core-repos.md#net-framework says to use [Dev Community](https://developercommunity.visualstudio.com/spaces/61/index.html) for .NET Framework issues.

Thanks @jkotas ,
In the announcement it says: [dotnet/runtime](https://github.com/dotnet/runtime/issues) - for runtime, API, or installer issues and questions.

I view this as a runtime / installer issue, do you agree?

**Comment by jkotas** [comment]
I agree that the announcement has a great deal of ambiguity. @kalaskarsanket Could you please edit the text of the pinned announcement to fix this ambiguity?

As a general principle, we track issues next to the code in question. If the code in question is open source on github, the issue should be filled in the github repo where the code lives. If the code in question is closed source (like it is the case here), the issue should be filled in Dev Community.

**Comment by marklio** [comment]
Orthogonal to the appropriate filing location, this issue has alerted us to the potential of problems with Windows Sandbox, so thank you.  We're looking into whether we can reproduce the issue. Don't expect that we will track that progress with this issue here though.

**Comment by pnorms** [comment]
Ack, thank you both! I will open in the Dev Community.

**Comment by pnorms** [comment]
Breadcrumbs for anyone else having this issue:
https://developercommunity.visualstudio.com/t/KB5011048-breaks-PowerShell-in-Windows-S/10187046

**Comment by jeffhandley** [comment]
Thanks for getting this filed in the Dev Community forum, @pnorms.
