### ISSUE TITLE
Consolidate Microsoft.DotNet.Cecil* libraries into one nuget package

### ISSUE THREAD

**Issue by tlakollo** [dotnet/runtime#77692]
Currently, there are two NuGet packages being produced in order to be able to support linker in runtime. The Microsoft.DotNet.Cecil package and the Microsoft.DotNet.Cecil.Pdb package. The official Cecil package has Mono.Cecil, Mono.Cecil.Mdb, Mono.Cecil.Pdb, and Mono.Cecil.Rocks libraries inside a single NuGet package Mono.Cecil. This is because Mono.Cecil doesnt use arcade and instead uses a nuspec file to define which projects are going to be included inside the nuget package. 
In the case of arcade the nuspec file gets automatically generated, there are some solutions around to be able to bundle the libraries into a single package as the nugetizer project see [the serde project config](https://github.com/agocke/serde-dn/blob/main/src/pack/Serde.Pkg.proj) as an example.
This might not be the best solution for the Microsoft cecil package but this issue tracks to get a similar solution for it.

**Comment by ViktorHofer** [comment]
> This is because Mono.Cecil doesnt use arcade and instead uses a nuspec file to define which projects are going to be included inside the nuget package.

Arcade isn't required for that. There are many ways to include multiple assemblies in a single package in a normal customer project. See https://github.com/NuGet/Home/issues/3891

**Comment by tlakollo** [comment]
Closed via https://github.com/dotnet/cecil/pull/66
