### ISSUE TITLE
AssemblyName.ProcessorArchitecture no longer returns the correct result

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#77697]
### Description

Starting in .NET 7.0 AssemblyName.ProcessorArchitecture is not correct.

Build tools like ResolveAssemblyReferences in MSBuild used this to determine if an application was referencing an assembly for a different architecture than what it targeted.  https://github.com/dotnet/msbuild/blob/3777dcaf7edb3e86a070037ba53e742dd1872873/src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs#L2578-L2599  cc @rainersigwald 

I noticed that starting with .NET 7.0 MSBuild stopped warning in this case.  I was able to trace it down to https://github.com/dotnet/runtime/pull/63915 which moved the AssemblyName.GetAssemblyName implementation to use the one in System.Reflection.Metadata https://github.com/dotnet/runtime/blob/3dbc850af3e8bfd6d529ed90cf00247dc9a24512/src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/MetadataReader.netstandard.cs#L14-L45

That version never set ProcessorArchitecture, for whatever reason, but it could.  So that might be the fix for this if we want to fix it.

@jkotas you obsoleted this member in https://github.com/dotnet/runtime/issues/59061.  Given what you said about this, should we also proceed with obsoleting the PlatformTarget support [in the compiler](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/output#platformtarget) and references as well?  If not, shouldn't we bring back this part of AssemblyName since our tools support building assemblies with it, and using it?

### Reproduction Steps

Run attached project.
[archConsole.zip](https://github.com/dotnet/runtime/files/9905265/archConsole.zip)

### Expected behavior

It emits `Amd64` for both the `net6.0` and `net7.0` builds.

### Actual behavior

It emits `Amd64` for the `net6.0` build and `None` for the `net7.0` build.

### Regression?

Yes, from .NET 6.0

### Known Workarounds

Calculate the ProcessorArchitecture of the assembly yourself?  This would imply we find all the places in the dotnet tooling (like MSBuild or the compiler) that might use this property and fix them to avoid this regression.

### Configuration

.NET 7.0 RC2, x64

**Comment by ericstj** [comment]
cc @VSadov

**Comment by rainersigwald** [comment]
Related discussion in dotnet/runtime#74040

**Comment by jkotas** [comment]
I do not think that this was intentional behavior change. We should be able to make it return what it returned before if it is important. @VSadov ?

> Given what you said about this, should we also proceed with obsoleting the PlatformTarget support [in the compiler](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/output#platformtarget) and references as well?

The target support has to stay in compiler for as long the compiler targets .NET Framework. 

Compiler targeting is superfluous in .NET Core. It was replaced by RID targeting. Use of compiler targeting in .NET Core only leads to problems. For example, see warning that we have added in https://github.com/dotnet/sdk/pull/27776 .

> Calculate the ProcessorArchitecture of the assembly yourself? This would imply we find all the places in the dotnet tooling (like MSBuild or the compiler) that might use this property and fix them to avoid this regression.

Note that the code fragment that you have linked won't work well for .NET Framework Arm64 targeting. The only way to make it work well for .NET Framework Arm64 targeting is to switch to reading PE header Machine architecture directly.

**Comment by VSadov** [comment]
> I do not think that this was intentional behavior change.

no, I think this should be fixed for compat reasons.

**Comment by VSadov** [comment]
Will keep this open to track backporting to 7.0

**Comment by karelz** [comment]
@VSadov looks like the backporting to 7.0 didn't happen. Can we close it as 8.0 now?

**Comment by VSadov** [comment]
Yes, since 7.0 is out of support, I think this is no longer actionable.
