### ISSUE TITLE
[API Proposal]: Utf8JsonReader.TryCopyString

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#77714]
### Background and motivation

`Utf8JsonReader` has a `CopyString` but not "Try" overload, meaning the only way to get an unescaped, UTF8 `string` value into a buffer safely is to manually check the possible length of the current token, and then call `GetString` on a large enough buffer. This is not ideal, as there might be cases where one is looking for a given token value with a given length (say, "$type"), and values that are larger can just be ignored. Currently you have to check the length and preemptively ignore it if it's too large, instead of just always calling `TryGetString` and handling the return either way.

### API Proposal

```diff
namespace System.Text.Json;

public ref struct Utf8JsonReader
{
+   public readonly bool TryCopyString(Span<byte> utf8Destination, out int bytesWritten);
+   public readonly bool TryCopyString(Span<char> destination, out int charsWritten);
}
```

### API Usage

```csharp
Span<byte> buffer = stackalloc byte[6]; // Or whatever length is enough for what we want

if (!reader.TryGetString(buffer, out int bytesWritten))
{
    return;
}

// Rest of the code...
```

### Alternative Designs

Do the check manually beforehand:

```csharp
long utf8TextLength = reader.HasValueSequence ? reader.ValueSequence.Length : reader.ValueSpan.Length;

if (utf8TextLength > 6)
{
    return false;
}

Span<byte> buffer = stackalloc byte[6];

_ = reader.CopyString(buffer);
```

### Risks

Low. It's just one more pair of overloads exposing functionality that's already available, just in a nicer way. The functionality is already implemented internally and it's used by `GetString()`, would just need to be exposed properly. No functional changes.

**Comment by Sergio0694** [comment]
Appreciate the enthusiasm, but that's not how it works 😅
This needs to first be marked as ready to review by an area owner, then go through API review, then if approved it can be potentially marked as up for grabs so that a community member can contribute it. You can read more about the process [here](https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md).

**Comment by eiriktsarpalis** [comment]
We intentionally steered away from exposing `Try` variants precisely because of the workaround you listed in your "alternative designs" section. The raw UTF-8 length is a cheap and good-enough upper bound estimate for the unescaped string length. OTOH such a `Try` method would need to run the full unescaping routine before it can definitely determine if the result fits in the destination buffer.

**Comment by eiriktsarpalis** [comment]
Hi @balazsberes, if you'd like to contribute I would recommend taking a look at the issues marked with the `help wanted` label: 

https://github.com/dotnet/runtime/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22+label%3Aarea-System.text.Json
