### ISSUE TITLE
Setting NullabilityInfoContextSupport=false in NativeAOT doesn't remove NullableAttribute/NullableContextAttribute ctors

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#77753]
`dotnet publish -c Release -r win-x64 -p:PublishAot=true -p:NullabilityInfoContextSupport=false -p:IlcGenerateMstatFile=true` the following app:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="7.0.0-*" />
  </ItemGroup>
</Project>
```

```C#
Console.WriteLine(new Microsoft.Extensions.DependencyInjection.ServiceCollection());
```

Inspect the `.\obj\Release\net7.0\win-x64\native\HelloWorld.mstat` using `ildasm` and open the `Methods()` method, which lists all the methods left in the app.

### Expected results

The `System.Runtime.CompilerServices.NullableAttribute::.ctor(uint8)` and `System.Runtime.CompilerServices.NullableContextAttribute::.ctor(uint8)` methods should be trimmed from the app, so they should not be in the mstat file.

### Actual results

These attributes are left in the app.

**Comment by MichalStrehovsky** [comment]
This is because of https://github.com/dotnet/runtimelab/issues/1381.

We need to add support for `assembly fullname="*"`. Can be done, just wasn't completely straightforward and I don't expect this to have meaningful savings. Custom attributes are a lot less costly in NativeAOT metadata format than in IL.
