### ISSUE TITLE
Setting the TCP keep alive for an HttpClient should be significantly simpler

### ISSUE THREAD

**Issue by Epic-Santiago** [dotnet/runtime#77755]
### Background and motivation

In .NET Framework, setting up the TCP timeout is trivial. It's a single line of code:
```csharp
ServicePointManager.SetTcpKeepAlive(true, 100, 200);
```

SetTcpKeepAlive() does not work on .NET 6 even though it is not marked as obsolete (this is another issue that I will report separately).

To get the same behaviour in .NET 6 it is significantly more complex. Here is the code:
```csharp
public static IHttpClientFactory CreateHttpClientFactory()
    => new ServiceCollection()
        .AddHttpClient("Test")
        .ConfigurePrimaryHttpMessageHandler(CreateHttpMessageHandler)
        .Services
        .BuildServiceProvider()
        .GetService<IHttpClientFactory>();

private static HttpMessageHandler CreateHttpMessageHandler()
{
    var handler = new SocketsHttpHandler
    {
        ConnectCallback = (context, token) => ConfigureSocketTcpKeepAlive(context, token),
    };

    return handler;
}

private static async ValueTask<Stream> ConfigureSocketTcpKeepAlive(
    SocketsHttpConnectionContext context,
    CancellationToken token)
{
    var socket = new Socket(SocketType.Stream, ProtocolType.Tcp) { NoDelay = true };
    try
    {
        socket.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.KeepAlive, true);
        socket.SetSocketOption(SocketOptionLevel.Tcp, SocketOptionName.TcpKeepAliveTime, 120);
        socket.SetSocketOption(SocketOptionLevel.Tcp, SocketOptionName.TcpKeepAliveInterval, 10);
        socket.SetSocketOption(SocketOptionLevel.Tcp, SocketOptionName.TcpKeepAliveRetryCount, 10);
        await socket.ConnectAsync(context.DnsEndPoint, token).ConfigureAwait(false);

        return new NetworkStream(socket, ownsSocket: true);
    }
    catch
    {
        socket.Dispose();
        throw;
    }
}
```

There are multiple problems with this:
1. The API is not ergonomic
2. SetSocketOption() is a legacy style of method signature. In .NET I would expect a simple TcpKeepAliveTime property
3. Dealing with integers instead of TimeSpans

We are forced to deal with a number of things that we shouldn't need to deal with such as...
1. Create SocketsHttpHandler
2. Create a callback
3. Having to create the Socket
4. Deciding the proper Socket constructor parameters
5. Setting NoDelay
6. Implement the try/catch to dispose the socket in case of error
7. Remembering the ConfigureAwait(false)
8. Creating a NetworkStream
9. Deciding the proper NetworkStream constructor parameters 

The Socket constructor parameters or whether to use a NetworkStream versus another type of stream are things that could very well change in .NET 7 or beyond and we will be left with outdated code because we were forced to write all that code that we didn't need.

### API Proposal

I'm proposing an extension method on IHttpClientBuilder that looks like this:
```csharp
public static IHttpClientBuilder ConfigureTcpKeepAlive(this IHttpClientBuilder builder, bool enabled, TimeSpan keepAliveTime, TimeSpan keepAliveInterval, int retryCount = 10)
```

This API lets the user do exactly what they want: setup the keep alive. It does not force the users to get into the networking weeds to work out how it is done.

### API Usage

```csharp
public static IHttpClientFactory CreateHttpClientFactory()
    => new ServiceCollection()
        .AddHttpClient("Test")
        .ConfigureTcpKeepAlive(true, TimeSpan.FromSeconds(120), TimeSpan.FromSeconds(10))
        .ConfigurePrimaryHttpMessageHandler(CreateHttpMessageHandler)
        .Services
        .BuildServiceProvider()
        .GetService<IHttpClientFactory>();
```

### Alternative Designs

Implement `ServicePointManager.SetTcpKeepAlive()` in .NET 6.

### Risks

Since this would be a wrapper that encapsulates all the complexity and doesn't change any existing APIs, I can't think of any risk.

**Comment by halter73** [comment]
If we think enabling TCP keep-alives are a common enough scenario for `HttpClient` that it deserves a more convenient API not involving `SocketsHttpHandler.ConnectCallback`, we should probably still add an API directly to `SocketsHttpHandler` and not just `IHttpClientBuilder`.

What about people who just want to new up an `HttpMessageHandler` themselves without involving DI? I imagine more people still new up their `HttpClient`'s directly than use `IHttpClientFactory`.

Whether we do one or both, we probably need to think about how the APIs compose with a custom `ConnectCallback`. Would custom `ConnectCallback`'s be expected to read these settings somehow and set the correct socket options? This kind of problem is why Kestrel exposes a [Create*Default*BoundListenSocket(EndPoint) method](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.transport.sockets.sockettransportoptions.createdefaultboundlistensocket?view=aspnetcore-6.0#microsoft-aspnetcore-server-kestrel-transport-sockets-sockettransportoptions-createdefaultboundlistensocket(system-net-endpoint)) method that someone customizing [CreateBoundListenSocket property](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.transport.sockets.sockettransportoptions.createboundlistensocket?view=aspnetcore-6.0#microsoft-aspnetcore-server-kestrel-transport-sockets-sockettransportoptions-createboundlistensocket) can call into before applying any of its additional customizations.

Also, if we do end up going with a new `IHttpClientBuilder` extension method, we should probably call it `ConfigureTcpKeepAlive` instead of `ConfigureKeepAlive` so these TCP keep-alive options cannot be conflated with options for something like HTTP/2 and HTTP/3 pings.

**Comment by wfurt** [comment]
I personally feel it should be enabled by default - as far as I can tell there is really no downside as it does nothing when there is traffic and overhead on idle connection is low and all handled by kernel. Than customization would become somewhat rare IMHO.

**Comment by antonfirsov** [comment]
@halter73 note that we already had a discussion on exposing it on `SocketsHttpHandler` in #61261, but decided not to, though we also kept it open to reconsider in the future.

>Would custom `ConnectCallback`'s be expected to read these settings somehow and set the correct socket options?

IMO this is the main concern. Currently we don't have any options exposed that a `ConnectCallback` implementation would need to forward to `Socket`, and `ConnectCallback` was not designed with this problem in mind.

> I personally feel it should be enabled by default 

We should also pick arbitrary values for `TcpKeepAliveTime`, `TcpKeepAliveInterval` and `TcpKeepAliveRetryCount` then. Do we think we know a configuration that is good for most users who encounter keepalive issues?

**Comment by JeffLeBert** [comment]
@antonfirsov in the case my company uses this, we use 2 minutes for the default. This is because the Azure load balancer defaults to 4 minutes (which is also the minimum) before it drops inactive connections. We figured half the minimum would be a good balance.

**Comment by halter73** [comment]
> I personally feel it should be enabled by default

Does any other HTTP client enable TCP keep alives by default? I've never noticed this in network traces myself if that's the case, but I guess it's not something I'm usually looking for.

It still seems very niche. Any purpose it would serve is usually made redundant by request timeouts, keep-alive timeouts or pings (for We sockets HTTP/2 and HTTP/3)?

What makes HTTP special? If there's no downside, why not make it default for all TCP sockets? The unnecessary traffic is at least a small downside even if it only happens for otherwise idle connections.

**Comment by halter73** [comment]
RFC 1122 also requires that application MUST default TCP keep-alives to be opted into. And even if it is opted into, the default interval MUST be no less than 2 hours. Has this RFC been replaced by anything else? It's interesting if Azure load balancer defaults to 4 minutes, but I think the bar is a little higher for a framework to configure this by default than for a service to configure it.

>             Implementors MAY include "keep-alives" in their TCP
>            implementations, although this practice is not universally
>            accepted.  If keep-alives are included, the application MUST
>            be able to turn them on or off for each TCP connection, and
>            they MUST default to off.

>            Keep-alive packets MUST only be sent when no data or
>            acknowledgement packets have been received for the
>            connection within an interval.  This interval MUST be
>            configurable and MUST default to no less than two hours.

https://www.rfc-editor.org/rfc/rfc1122#section-4.2.3.6

**Comment by Epic-Santiago** [comment]
Personally, I don't think enabling the keepalive by default is necessary.
The heart of the issues is that just because I need to set it, I shouldn't have to suddenly start managing how the socket is created. Those are two concerns that should have never been married. While there are many usability issues with the API as it exists, the most important issue is that as the consumer of the API, I'm being forced into taking charge of the Socket creation and I'm basically copy/pasting code from some doc. This will age poorly as subsequent releases of .NET will probably change how to best create this socket and I'll be left with my hardcoded values.

**Comment by stephentoub** [comment]
> I shouldn't have to suddenly start managing how the socket is created

FWIW, I disagree with this part.  There are lots of things someone can configure on a socket, or about how connections should be created in general, and all of those can't/shouldn't be lifted to be exposed on SocketsHttpHandler directly... at some point you have to fall back to the general hook that lets you configure whatever you want to configure: ConnectCallback. Now it might turn out that configuring keep alives is _so_ common that it's worth promoting.  I've not seen evidence of that, though.

**Comment by Epic-Santiago** [comment]
Yes, I just want to poke at the socket that the framework created. I think the extension method I proposed would be a good usability improvement. But letting us set something on the socket that the framework created instead of forcing us to take charge of the socket creation (again, by copy pasting code from a doc that is all but guaranteed to grow stale) would fix the most egregious problem. While most of the things I pointed out are usability problems, the socket creation I think forces us into writing bad code and that to me is more a bug than an enhancement request.

**Comment by ManickaP** [comment]
@Epic-Santiago we have opened a new issue to consider whether and how to make implementing `ConnectCallback` easier: https://github.com/dotnet/runtime/issues/78989.
Would something like that help you? If so, please share your insights there.

**Comment by Epic-Santiago** [comment]
@ManickaP, yes, I think this should help address some of the issues I shared here. I will follow that issue and contribute my thoughts. Thanks.

**Comment by ManickaP** [comment]
Triage: We'll never support `ServicePointManager` properties in `HttpClient`. We think that having the `ConnectCallback` to customize the socket is sufficient, but we want to make this more user-friendly (#78989). I think there's nothing more left to do in this issue, so I'm closing it. If I've missed something, feel free to re-open.
