### ISSUE TITLE
[wasm][debugger] Expand support of `DebuggerTypeProxy`

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#77768]
So far we support DebuggerTypeProxy for class and struct. Add tests to DebuggerTests.CustomViewTests.UsingDebuggerTypeProxy or similar to check if it works on assembly level. If it's failing - fix it.

WIP: https://github.com/dotnet/runtime/compare/main...ilonatommy:runtime:fix-77768?expand=1

**Comment by thaystg** [comment]
This is fixed by the new debugger.
