### ISSUE TITLE
Package System.Net.Http

### ISSUE THREAD

**Issue by joaodelgado13** [dotnet/runtime#77776]
Hi,

Noticed that this package was not updated since 2018 in the nuget repository: https://www.nuget.org/packages/System.Net.Http

I know that packages now are bundled in the .net core installation. But shouldn't it receive updates?

Kind regards

**Comment by p-brito** [comment]
I noticed this too, for example, the System.Net.Http.Json has all versions.

**Comment by karelz** [comment]
System.Net.Http package did not have any reason to be updated -- it redirects on both .NET Core and .NET Framework to the inbox versions which are part of the underlying .NET platform. It is basically no-op (which in the past had ambition to provide additional value).

Why do you look at the package and why do you feel it should have updates? Are you using it anywhere?

**Comment by joaodelgado13** [comment]
Basically, if you do a dotnet restore command it will return the latest version of the nuget repository, and in the end the version 6.0.0 is bundled when you are using .net6.0

It's a bit confusing to not see the correct version in the restore project, or why even pull a package version that won't be used

**Comment by joaodelgado13** [comment]
@karelz any update?

**Comment by karelz** [comment]
@joaodelgado13 I am not sure what I should update on? I don't quite understand your answer to my question. Can you please try to clarify it for me? Thanks!

**Comment by joaodelgado13** [comment]
Hi @karelz,

If you create a project in dotnet 6 with this dependency:

<ItemGroup>
    <PackageReference Include="NSubstitute" Version="4.3.0" />
  </ItemGroup>

and do dotnet restore command it will show System.HttpClient@4.3.0 but if you publish the application the System.HttpClient will be at version 6.0.0, although this version doesn't exist in nuget.org repository.

My question is why System.HttpClient.Json, for example, exists until version 6.0.0 in nuget.org and System.HttpClient does not.

**Comment by karelz** [comment]
Technically, there is not System.HttpClient version 6.0.0 -- I assume you mean System.Net.Http.dll.

If you use HttpClient class in your app, WITHOUT referencing System.Net.HttpClient nuget package, you will also get System.Net.Http.dll version 6.0.0. Adding the nuget package System.Net.HttpClient reference doesn't change anything. It is no-op. It just says "use what is in-box".

Hopefully that will explain what is happening and why.
The history how we landed here is complicated and requires reading of historic issues - you can start with #18280 https://github.com/dotnet/runtime/issues/20777#issuecomment-338418610 if you are interested.

**Comment by karelz** [comment]
Triage: Seems to be answered. Closing.
