### ISSUE TITLE
Expose `WebSocketMessageFlags` in `ClientWebSocket`

### ISSUE THREAD

**Issue by greenEkatherine** [dotnet/runtime#77783]
In #31088 compression support in WebSocket was introduced. There was added `WebSocketMessageFlags.DisableCompression` flag which is needed to turn off compression i.e. when sending data containing secrets -- it helps to avoid CRIME/BREACH attacks.

However, this flag was added only in `WebSocket` and not in `ClientWebSocket` which  is supposed to manage messages. We need to expose `DisableCompression` flag in `SendAsync` methods as well as it is done for `EndOfMessage` flag.

**Comment by stephentoub** [comment]
I've not quite followed the proposal.  ClientWebSocket derives from WebSocket, inheriting all the APIs added there, and its implementation wraps ManagedWebSocket that implements the compression.  What is the specific API that would be added to ClientWebSocket?

**Comment by greenEkatherine** [comment]
@stephentoub we should add `SendAsync` method that handles `DisableCompression` flag. Currently we handle only `EndOfMessage` flag in both ClientWebSocket https://github.com/dotnet/runtime/blob/64b3ee4d35f9ba6a0bf66a0c5b41d2c8873cd89f/src/libraries/System.Net.WebSockets.Client/src/System/Net/WebSockets/ClientWebSocket.cs#L145-L149 and parent WebSocket https://github.com/dotnet/runtime/blob/64b3ee4d35f9ba6a0bf66a0c5b41d2c8873cd89f/src/libraries/System.Net.WebSockets/src/System/Net/WebSockets/WebSocket.cs#L56-L64

**Comment by stephentoub** [comment]
Thanks. This isn't about missing API, then, it's a bug. ClientWebSocket should be overriding `public virtual ValueTask SendAsync(ReadOnlyMemory<byte> buffer, WebSocketMessageType messageType, WebSocketMessageFlags messageFlags, CancellationToken cancellationToken = default)` to forward it to the wrapped ManagedWebSocket's corresponding message.

**Comment by MihaZupan** [comment]
Triage: We should fix this in 8.0, looks like we're missing test coverage as well.

**Comment by CarnaViire** [comment]
Reopening for backport
