### ISSUE TITLE
WASM - Cannot import `dotnet.js` in an Angular app

### ISSUE THREAD

**Issue by sergiubologa** [dotnet/runtime#77782]
### Description

Hello! 👋 

I'm trying to create an Angular app that uses the generated WASM files. When I import the `dotnet.js` file and start the project I get the following warning and error:

```
dotnet.js:3144:108-117 - Warning: Critical dependency: the request of a dependency is an expression
dotnet.js:11908:45-61 - Error: Module not found: Error: Can't resolve 'module' in ...
```

It seems like this is an ES6 module and can't be imported into a project using webpack.

The import is made like this:

```ts
import { dotnet } from './dotnet';
```

The only way I can make it work is by loading it directly in the HTML file using the `<script type="module" src="dotnet.js"></script>`

Any idea how can I solve this?

### Reproduction Steps

- create a new Angular project (latest version)
- import the `dotnet.js` file in the main component
- try to start the app and see the console error

### Expected behavior

It should build correctly and start the app in the browser

### Actual behavior

The build doesn't pass and an error is thrown:
```
dotnet.js:3144:108-117 - Warning: Critical dependency: the request of a dependency is an expression
dotnet.js:11908:45-61 - Error: Module not found: Error: Can't resolve 'module' in ...
```

### Regression?

I don't think so

### Configuration

net 7 (7.0.100-rc.2.22477.23)
Windows/OSX
x64, ARM64

**Comment by pavelsavara** [comment]
It's rather webpack limitation, not dotnet limitation in my opinion.

There are few things you could try
- make it [external](https://webpack.js.org/configuration/externals/) in webpack config 
- annotate the import `await import(/* webpackIgnore: true */ './dotnet.js')`
- try to configure webpack to become ES6 friendlier. Last time I tried [here](https://github.com/dotnet/runtime/blob/main/src/mono/sample/wasm/browser-webpack/webpack.config.js)
