### ISSUE TITLE
Libraries Infrastructure and Tools work planned for .NET 8

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#77792]
Collecting the work in Infrastructure and Tools that we aspire to complete in .NET 8.

[TODO: Create sub issues]

- APICompat work
- GenAPI work / support
- Tool for docs migration: https://github.com/dotnet/runtime/issues/44969
- maintenance-packages repo
- VMR work for dotnet/runtime

**Comment by ViktorHofer** [comment]
Closing as we don't need the meta tracking issues anymore. We did make progress on all above items except the "maintenance-packages repo" one.
