### ISSUE TITLE
Update GeneratedRegex to support partial properties

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#77797]
Partial properties are destined for support in C# 13.  When that happens, we should utilize them in the regex generator (we wanted this experience from the get-go).

This will entail:
- Updating `GeneratedRegexAttribute` to target properties:
```diff
-[AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
+[AttributeUsage(AttributeTargets.Method | AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
 public sealed class GeneratedRegexAttribute : Attribute
```

- Updating the generator to support instance and static get-only properties, e.g. if a user writes:
```C#
[GeneratedRegex("...")]
private partial Regex MyProp1 { get; }

[GeneratedRegex("...")]
public static partial Regex MyProp2 { get; }
```
the generator emits:
```C#
private partial global::System.Text.RegularExpressions.Regex MyProp1 => global::System.Text.RegularExpressions.Generated.MyProp1_0.Instance;
public static partial global::System.Text.RegularExpressions.Regex MyProp2 => global::System.Text.RegularExpressions.Generated.MyProp2_0.Instance;
```

We will only support get-only auto props. Others will result in an error diagnostic.

**Comment by joperezr** [comment]
Calling this out since it wasn't mentioned above as the things this would entail, but we will obviously also want to make the required changes on the Analyzer and Code Fixer so that when this support is added our roslyn tools would help developers on these cases as well.

**Comment by stephentoub** [comment]
FYI @RikkiGibson, @333fred

**Comment by RikkiGibson** [comment]
dotnet/csharplang#6420

**Comment by teo-tsirpanis** [comment]
> whether or not our Roslyn Analyzer and Code Fixers should suggest using the static partial method or the properties instead

I think we should suggest the partial properties when we can; they are one parentheses pair easier to use than methods and the returned `Regex` is a cached singleton and matches the expectation that property accesses are cheap.

**Comment by ericstj** [comment]
Moved this out since partial properties are not available yet.

**Comment by bartonjs** [comment]
Looks good as proposed

```diff
-[AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
+[AttributeUsage(AttributeTargets.Method | AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
 public sealed class GeneratedRegexAttribute : Attribute
```
