### ISSUE TITLE
Collapse/remove projects under src/installer/tests/Assets/TestProjects

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/runtime#77807]
Many projects in src/installer/tests/Assets/TestProjects only have minor differences - multiple projects can become one with different behaviour based on command line arguments to reduce the cost of restoring/building the test assets (and including them in a helix payload when we get to that point)

Likely candidates: PortableApp*, RuntimeProperties, AppWith*, LightupApp

**Comment by am11** [comment]
@elinor-fung, are these operations relevant to host testing: https://github.com/dotnet/runtime/blob/21e9913582bccacb50a2ec6a136546c6d4afe0ae/src/installer/tests/Assets/TestProjects/StandaloneApp/Program.cs#L17-L18 If it is not possible that the assembly loading functionality could regress without breaking other (non-host) tests in the runtime repo (e.g. test_dependencies uses live host for libraries tests), we can clean up Newtonsoft dependency from TestProjects assets as well.

**Comment by elinor-fung** [comment]
For most cases, I think they are not relevant. I think they were mostly there to test basic dependency resolution, but also muddied with relying on the SDK/build. Aside from what you mentioned about coverage via the live host being used in libraries tests now, since those TestProjects assets were added @vitek-karas has done a lot of work to create more targeted component tests for that area.

There are a couple tests that intentionally do things to target moving around / configuring dependencies that use it, but I think they could/should be changed to do things differently.

**Comment by elinor-fung** [comment]
The tests been moved away from these projects to use pre-built test assets now. And it has gone from 40+ projects copied/built during test run to 18 pre-built test assets.
