### ISSUE TITLE
NetworkChange NetworkAddressChanged event throws NetworkInformationException on Android

### ISSUE THREAD

**Issue by chriskarlsson** [dotnet/runtime#77822]
### Description

NetworkInformationException is thrown when trying to subscribe to NetworkChange.NetworkAddressChanged on Android.

There is no indication in the source code that Android is UnsupportedOSPlatform but Android is not listed as supported in [Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/api/system.net.networkinformation.networkchange.networkaddresschanged?view=net-6.0).

### Reproduction Steps

Add the following to MainActivity of a clean Android or Maui application project:

```
NetworkChange.NetworkAddressChanged += (sender, args) =>
{
    Console.WriteLine($"Sender: {sender} args: {string.Join(", ", args.ToString())}");
};
```

### Expected behavior

Console output when network address changes.

### Actual behavior

NetworkInformationException is thrown with the quite cryptic exception message "Success".

### Regression?

This was working fine when the application ran on Mono. It also works fine on .Net6-ios and .Net6-mac.

### Configuration

Which version of .NET is the code running on? - Behavior seen on both .Net6-android with and without Maui
What OS and version, and what distro if applicable? - Android 12/API 31
What is the architecture (x64, x86, ARM, ARM64)? - ARM

**Comment by am11** [comment]
(aside from the NetworkAddressChanged event issue)

> NetworkInformationException is thrown with the quite cryptic exception message "Success".

If this exception is thrown from https://github.com/dotnet/runtime/blob/13733cdd969842de9c36235d730a604ce55ee729/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/NetworkAddressChange.Unix.cs#L172-L176 it shouldn't print "Success". @akoeplinger, looks like there is also something wrong in the error mapping? 🤔

**Comment by steveisok** [comment]
@simonrozsival, please take a look.

**Comment by akoeplinger** [comment]
@simonrozsival did you happen to find out whether we could support this?

**Comment by simonrozsival** [comment]
@akoeplinger I looked into it and I didn't find a good 1:1 replacement Android API. There are some ConnectivityManager APIs that seemed promissing but they don't behave the same way (for example [ConnectivityManager.registerNetworkCallback](https://developer.android.com/reference/android/net/ConnectivityManager#registerNetworkCallback(android.net.NetworkRequest,%20android.net.ConnectivityManager.NetworkCallback,%20android.os.Handler))). I will need to revisit this and look for some alternative ways of implementing it if it's even possible with the current Android restrictions.

**Comment by akoeplinger** [comment]
I wonder if we could start a timer/polling loop whenever someone registers the event that would continuously look for network changes

**Comment by simonrozsival** [comment]
We could do that. It would certainly work but wouldn't that be quite inefficient to do on a mobile device?

**Comment by simonrozsival** [comment]
I'm experimenting with `PeriodicTimer` to poll network information. I'm still not convinced that this is the optimal implementation but it's likely good enough. I need to do more testing before I submit the PR for full review. For the time being I opened a draft PR and any suggestions are welcome.

**Comment by akoeplinger** [comment]
With https://github.com/dotnet/runtime/pull/80548 being merged we should be done here right? I don't think it makes sense to backport this to 7.0

**Comment by simonrozsival** [comment]
I don't think we should backport the implementation. I think we can close this issue now.
