### ISSUE TITLE
[API Proposal]: Color.FromName(ROS name)

### ISSUE THREAD

**Issue by Shpendicus** [dotnet/runtime#77838]
### Background and motivation

Same as with StringBuilder, I do have methods which return slices to an existing buffer and would be super neat to have the option to have a factory-method in Color, which you can pass directly a ROS into to avoid extra allocations.

### API Proposal

```csharp

public static Color FromSpan(ROS name);

```

### API Usage

```csharp
ROS colName = GetKnownColorFromBuffer(someBuffer); //or whatever here

var color = Color.FromSpan(colName);

```

### Alternative Designs

Best as an extra overload.

### Risks

AFAIK none

**Comment by danmoseley** [comment]
Is this a hot path where an allocation would be a problem? Because I don't think we want to duplicate every existing method that takes a string.

**Comment by Shpendicus** [comment]
> 

Indeed it is, I have a textstyle enumerator who iterates over a big chunk of text, gathered from user input and returns a custom chunk type with some fields, and this enumerator runs roughly 60-144 FPS in render update loop, cause it has to look for input updates regarding the buffer.

**Comment by Shpendicus** [comment]
I should have indeed be clearer about my intentions and the direct need for that to have, sry..

**Comment by teo-tsirpanis** [comment]
You can do it like this:

```csharp
public static Color ParseColor(ReadOnlySpan<char> span) => Color.FromKnownColor(Enum.Parse<KnownColor>(span));
```

**Comment by Shpendicus** [comment]
> You can do it like this:
> 
> ```cs
> public static Color ParseColor(ReadOnlySpan<char> span) => Color.FromKnownColor(Enum.Parse<KnownColor>(span));
> ```

I think this is fine, thx man.
