### ISSUE TITLE
[API Proposal]: More Function-Overloads which takes ReadOnlySpan<char> instead of string

### ISSUE THREAD

**Issue by Shpendicus** [dotnet/runtime#77834]
### Background and motivation

Hello dear devs,

I was actually interessted in contributing to the .net repo in the regard of adding more function overloads which accept ROS/Span<T> of any sort, for instance the "Color" struct or in "StringBuilder", whereever possible without breaking something, and I wanted to sorta get green light in this endavor. 

Glad to hear from you in this regard!

Cheers

### API Proposal

-

### API Usage

-

### Alternative Designs

-

### Risks

-

**Comment by Shpendicus** [comment]
ALso i think it would be nice to allow a stringbuilder[range] for slices which return a ROS again. so u dont have to actually to build up a newstring with "builder.ToString()" when you wanna pass that slice onto other API (which if they take a ROS aswell is even better in terms of memory consumption)

**Comment by stephentoub** [comment]
> ALso i think it would be nice to allow a stringbuilder[range] for slices which return a ROS again

This assumes the storage behind a StringBuilder is contiguous.  It may not be.  StringBuilder is implemented as a linked list of chunks, so if your range crossed one of those chunk boundaries, producing a ReadOnlySpan would require non-trivial allocation and fixups to make the region contiguous.  We're not going to do that.

**Comment by Shpendicus** [comment]
> > ALso i think it would be nice to allow a stringbuilder[range] for slices which return a ROS again
> 
> This assumes the storage behind a StringBuilder is contiguous. It may not be. StringBuilder is implemented as a linked list of chunks, so if your range crossed one of those chunk boundaries, producing a ReadOnlySpan would require non-trivial allocation and fixups to make the region contiguous. We're not going to do that.

I forgot that potential non-contiguous nature, so i understand your view. But the rest of my post here is actually smth which could be done by the StringBuilder imho.

**Comment by Shpendicus** [comment]
> Can you please:
> 
>     1. Open individual issues for each method or related set of methods being proposed? Color and StringBuilder are not related and would warrant separate proposals.
> 
>     2. Please fully fill out the API proposal template, including the API signature being proposed, example usage, details on where/how/why it would be vaulable, etc.
> 
> 
> Thanks.

okay, i actually wanted to only say that there are still a decent portion of (whatever) functions which take string insteaf of ROS and i thought it a good idea to make contributions to those, but if you wish to have it more detailed i will do what you asked for.

**Comment by stephentoub** [comment]
Understood. But we're not blanketly adding new span-based overloads everywhere there's a string-based or array-based overload.  We did an initial pass adding the ones expected to be most useful, and then as there's been a demonstrated need, we've added additional ones. Thanks.

**Comment by Shpendicus** [comment]
Respected and thanks for all of your effort btw! THis goes out to all of the devs here. Really 😎  people here
