### ISSUE TITLE
[API Proposal]: JsonDocument.TryParse

### ISSUE THREAD

**Issue by paa-listas** [dotnet/runtime#77849]
Per @ahsonkhan's feedback, guidelines for `Try`-methods require representing one and only one failure mode when returning `false`, and otherwise throwing exceptions is perfectly acceptable. As such, it would not be possible to add such a method, at least not one that doesn't violate expectations as ruled out in the original post.

_Originally posted by @eiriktsarpalis in https://github.com/dotnet/runtime/issues/387#issuecomment-948850231_

We need a JDocument.TryParse(someJsonString)      Throwing exceptions is slow and not a good solution.

**Comment by krwq** [comment]
I'm not sure that idea is practical for our implementation, it seems we'd need to refactor essentially entire code-base to support this. Out of curiosity what's your scenario that you care that much of a perf for incorrect JSON scenarios?

**Comment by eiriktsarpalis** [comment]
Feedback from the original issue still holds: 

1. It is not the case that `Try-` methods cannot throw exceptions and,
2. A `false` result from a `Try-` method should represent one and only one failure mode.

As such adding a `TryParse` method would violate framework design guidelines. One alternative is adding a separate `bool IsValidJson` method but that would still require parsing the same JSON twice.

cc @bartonjs

**Comment by paa-listas** [comment]
I am writing code that looks like this because the Api providers sometimes responds with some JSON, and other times use another, and can add other JSON anytime:

<code>

            MemoryStream ms = new MemoryStream(/*bufferSize*/);
            Memory<byte> memory = new Memory<byte>(byteBuffer);
            do
            {
                ms.SetLength(0); // En cada iteracion va a cero
                // Recibo un mensaje completo, puedo leerlo en varias iteraciones si es muy grande.
                do
                {
                    vReceiveResult = await m_clientWebSocketOrderData.ReceiveAsync(memory, m_cancelToken);
                    ms.Write(memory.ToArray(), 0, vReceiveResult.Count);
                } while (vReceiveResult.EndOfMessage == false);

                // Si cerraron la conexion, salgo del bucle "infinito"
                if (vReceiveResult.MessageType == WebSocketMessageType.Close)
                {
                    Log.Information("Cerraron la conexion en la instancia {id}", m_MyId);
                    break;
                }
                else
                {
                    /// Traducimos el mensaje, que debe ser de tipo "WebSocketMessageType.Text" en formato de byte[],
                    /// a una cadena. Dicha cadena debe contener un JSON con una estructura de algun tipo de los que envia el
                    /// proveedor, pero puede agregar algun otro JSON con una estructura distinta cuando quiera!
                    string jsonResponse = System.Text.Encoding.UTF8.GetString(ms.ToArray());

                    // .NET no tiene un TryParse para JsonDocument, y lanza una excepcion que como es
                    // muy pesada capturar y se repita monton de veces, mejor no hacerlo.
                    // using (JsonDocument jDoc = JsonDocument.TryParse "...No existe ese metodo :(" (jsonResponse))
                    // JsonElement elem = jDoc.RootElement.GetProperty("status");

                    if (jsonResponse.StartsWith("{\"status\":\"ERROR\""))
                    {
                        // Algo mal enviamos y recibimos un error y no un informe de una orden
                        OrderDataErrorResponse orderDataError = null;
                        orderDataError = JsonSerializer.Deserialize<OrderDataErrorResponse>(jsonResponse);
                        if (m_callerCallBackError != null)
                        {
                            m_callerCallBackError(this, orderDataError);
                        }
                    }
                    else if (jsonResponse.StartsWith("{\"type\":\"or\""))
                    {
                        // Todo OK, recibimos una info sobre una orden parece
                        OrderDataResponse orderData = null;
                        orderData = JsonSerializer.Deserialize<OrderDataResponse>(jsonResponse);
                        if (m_callerCallBack != null)
                        {
                            m_callerCallBack(this, orderData);
                        }
                    }
                    else
                    {
                        Log.Error("Llego alguna estructura JSON que no habia tenido en cuenta.");
                    }
                }
            } while (m_cancelToken.IsCancellationRequested == false);

</code>


I have to use a serie of "if (jsonResponse.StartsWith("{\"status\":\"ERROR\""))....else if(jsonResponse.StartsWith("{\"type\":\"or\"")) etc.

We may need a bool IsValidJson<T>(string strJson, out JsonDocument jDoc) ?? I don't know, but i think that using a serie of if()...else if()....else if()... else can be improbed.

Thanks for being interested in the subject.
