### ISSUE TITLE
Windows Service Error 1053

### ISSUE THREAD

**Issue by Phylum123** [dotnet/runtime#77861]
### Description

I created a windows service, by using the worker project template and then referencing the extension.windowsservice Nuget package. I added UseWindowsService to the host creation. Without any changes I deployed the default service using SC.exe and it worked just fine. I then added some logic to the worker and updated the program.cs to load a few more things. The whole startup is around 800ms. I run the program in debug mode and it works as expected. However, when I try to use the new version as a target of SC, it installs but won't start due to error 1053. The weird part is the error comes up almost immediately, it is not waiting 30 seconds. Checking the event log I get two events - 7000, 7009. Event 7009 verifies the time out is set to 30 seconds (30,000ms). 

The second weird part is that if I just execute the exe, all is well and it runs as expected, except with a console window.

Is there any way to get a more meaningful message or something else I can try to figure out why it is not working as a windows service?

Below is the project file.
```
<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-CIIS.Pario2.DataBridge.HostedServiceTest-9B2416D7-E562-47A1-B37D-22D6F1BA0810</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="6.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CIIS.Pario2.Common.Service\CIIS.Pario2.Common.Service.csproj" />
    <ProjectReference Include="..\CIIS.Pario2.DataBridge.DomainServices\CIIS.Pario2.DataBridge.DomainServices.csproj" />
  </ItemGroup>
</Project>
```
### Reproduction Steps

See above

### Expected behavior

The program to function as a windows service.

### Actual behavior

Error 1053

**Comment by Phylum123** [comment]
Can anyone look at this?

**Comment by tarekgh** [comment]
We'll get into this when we are triaging it. And please provide a complete sample reproducing the issue we can look at.
