### ISSUE TITLE
ValueTaskSourceAsTask IAsyncStateMachineBox implementation?

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/runtime#77866]
I'm working on a project with high perf requirements. So far there is one scenario where being able to add multiple continuations might be required (*might*, with some re-engineering it may not be necessary). In this particular case I have to make a choice long before the decision whether it's required or not, forcing the rare case to be the norm.

Trying to implement this at the lowest cost I noticed there is a small gap in the BCL where there is no way to get a promise Task with just a single alloc, as a TaskCompletionSource is its own class as well. 

As a result there are three allocs, two for the tcs and task and one for the 'operation' instance that carries the tcs + other data.

Then I thought, well I can implement IValueTaskSource on the operation instead of using a tcs. Next we can construct a ValueTask from it and call AsTask() to get a task with two allocs. However when this task completes the underlying valuetask source it allocates a `QueueUserWorkItemCallbackDefaultContext`, bringing it right back to three allocs.

Even though conceptually it's a bit of an odd case it seems ValueTaskSourceAsTask could implement IAsyncStateMachineBox like the builder boxes do to avoid this alloc? (alternatively some way to get a promise Task with one alloc would also suffice)

Regardless of my specific use case it seems useful to have ValueTaskSourceAsTask be its own schedulable thing (either through IAsyncStateMachineBox or some other mechanism). As the threadpool item seems like an unnecessary alloc for the framework internals to make.

**Comment by benaadams** [comment]
You may want to implement [IThreadPoolWorkItem](https://learn.microsoft.com/en-us/dotnet/api/system.threading.ithreadpoolworkitem?view=net-6.0) instead? Then that object can be queued directly on the threadpool and expose its completion via `IValueTaskSource`

**Comment by NinoFloris** [comment]
That should teach me not to write out the horrible hack I'm using right now. It involves a custom ManualResetValueTaskSource that allows me to get at the continuation and instead of calling UQUWI it enqueues itself as a IThreadPoolWorkItem, handling the continuation it is holding. First problem is that this doesn't work in the race case, as there's already a sentinel set. Additionally this requires a lot of code that was neatly tucked away in a framework type (MRVTS). Additionally I don't want a million fields to be duplicated on this per operation object, bloating it unnecessarily.

Either way just implementing IThreadPoolWorkItem directly won't work as I want a ValueTask to give to consumers. That means internally a ValueTask now holds a [ValueTaskSourceAsTask](https://github.com/dotnet/runtime/blob/de27aa1584ed98e23f93136ce548fce3931184fd/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/ValueTask.cs#L232), however when that completes, when you have a normal ManualResetValueTaskSource backed IValueTaskSource it's just a normal action that has to be wrapped first.

ValueTaskSourceAsTask can't implement IThreadPoolWorkItem either because it'll be blocked by UQUWI checks as it's a derived Task type. IAsyncStateMachineBox seems the best option.

**Comment by benaadams** [comment]
Could return a regular Task rather than a ValueTask; if you are converting the ValueTask to a Task anyway?

**Comment by NinoFloris** [comment]
Even though that is sometimes a solution I don't want that to detract from the fact ValueTaskSourceAsTask allocates unduly today, IMO.

In our case however, the task is also often ready right away so Task isn't the right primitive here.

**Comment by NinoFloris** [comment]
I was able to remove the need for multiple continuations, for now. Doesn't take away much from the issue though.

Regading a single alloc TCS: how could I forget after authoring https://www.nuget.org/packages/Ply... 
AsyncTaskMethodBuilder can be used as a single alloc tcs. It's a bit weird to see it in normal code though.

The downside is you can only use it in cases where you don't mind continuations running synchronously, given you can't pass in any creation options. Not minding that may be the minority case though so I'm still hoping for a single alloc tcs.

**Comment by stephentoub** [comment]
> Even though that is sometimes a solution I don't want that to detract from the fact ValueTaskSourceAsTask allocates unduly today, IMO.

I implemented a solution to this:
https://github.com/dotnet/runtime/commit/bdea839abae0d2c1740145e005388a7e8b7527a8
but even in an extreme microbenchmark focused on putting this in the best light, it didn't really move the needle.  Given that, I don't think it's worth adding the complication or small additional cost for other cases.

Thanks for the suggestion.
