### ISSUE TITLE
ReadyToRun: The type initializer for 'System.Runtime.Serialization.Formatters.Binary.Converter' threw an exception.

### ISSUE THREAD

**Issue by tapika** [dotnet/runtime#77862]
### Description

git to clone (for now resides in develop, but this might change):

https://github.com/tapika/swupd/tree/ed2aaeb22f4c444fce4c58a7eda9da09e62f8264

Build ready2run image using command:

```
cakebuild --build true --r2r_targets choco --os win81 --r2r_build
```

or pick up pre-built image from here:

https://github.com/tapika/swupd/releases, see beta release.

Run elevated command prompt. Run command

```
choco install dotnetcore
```

Application exits with error:

```
The type initializer for 'System.Runtime.Serialization.Formatters.Binary.Converter' threw an exception.
```

If you try to debug given executable - you can see also inner exception (which might be right or wrong):

```
FileNotFoundException: Could not load file or assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
```

in project: `src\chocolatey.console\chocolatey.console.csproj`

There is configured not to trim `mscorlib`

```
<TrimmerRootAssembly Include="mscorlib" />
```
([See in issue 733](https://github.com/dotnet/runtime/issues/733)) 

Do theoretically assembly should not be trimmed away - but still it cannot be loaded ?

P.S. In master this command should work out of box, see also changes in develop versus master - last commit.

### Reproduction Steps

See description above

### Expected behavior

Successful run

### Actual behavior

Application fails due to exception

### Regression?

Regression - this worked in older build, but difficult to tell which.

**Comment by tapika** [comment]
@trylek ?

**Comment by tapika** [comment]
Problem on my side.

`cakebuild` was requesting via `global.json` too low level of version .net core 3.1 (`3.1.101`).

After applying [this bugfix](https://github.com/tapika/swupd/commit/8ee5358ca164ad126593d872f2fdf5d6ef39f826) problem disappered.

**Comment by trylek** [comment]
Great to hear you're unblocked now, please let us know if you hit any other issues!
