### ISSUE TITLE
PluginLoadContext and Ef DBContext -memory leak - not unloading

### ISSUE THREAD

**Issue by Seabizkit** [dotnet/runtime#77892]
### Description

I have a project with many moving pieces. I have run to a memory leak.
**in trying to identify so I have stripped my project to the bare minimum.**
The leak has to do with **_DBContext._**

everything is latest .net 6

############################
**Steps to re-produce**,  load plugin using AssemblyLoadContext in
the plugin should create IServerCollection, Register DBContext, load that from the services
noting else try unload the AssemblyLoadContext its does not unload
############################

please recreate then above and verify something similar I have provided a lot here as to what time doing, it has taken lot of time time trying to figure this out.

here is me doing the above but in a nut shell do the above and you will see it doesn't unload

basic project structure

interfaces
- Component.Facade **<-- interface for plugin**
- Component.database.config.Facade **<-- interface for database**

plugin
- Component.database.**Plugin**
--Component.database.config.Facade
--Component.database.config
--Component.Facade 

other 
- Component.Code <-- where PluginLoadContext is

database
- Component.database.config 
-- Component.database.config.Facade

test-  point it to the folder location of the plugin, Component.Facade is marked as private to the plugin so its all works its just not unloading... 

- Test.plugins
-- Component.Facade
-- Component.Code

plugin
```
public sealed class Plugin : IParadoxComponent
{
    public Guid IdentifferName => new Guid("C9BEB8BE-D031-4A30-B88B-7E9D3894D65E");
    public string Name => "Test plugin";
    public string ShortName => "Test";
    public string Author => "Paradox";
    public string Description => "trying to test if bug in DBcontext";
    public string ImageIcon => "na";
    public string ImageUrl => "";


    private Action<IServiceCollection, IConfiguration> SetupServices()
    {
        Action<IServiceCollection, IConfiguration> deligate = (services, config) =>
        {
            var conn = config.GetConnectionString("MsSqlParadoxImporter");
            services.AddDbContext<ParadoxCoreContext>(options =>
             options.UseSqlServer(conn)
            );
        };
        return deligate;
    }

    public async Task ExcuteAsync()
    {
        using (var serviceProvider = new Startup(SetupServices()))
        {
            using (var scope = serviceProvider.ServiceProvider.CreateScope())
            {
                var services = scope.ServiceProvider;
                using (var db = services.GetRequiredService<ParadoxCoreContext>())
                 {
                 }
            }
        }
    }
```

startup code inside of plugin project
```
public class Startup : IDisposable
    {
        private const string DefaultEnviroementName = "Development";
        IConfigurationRoot _configuration;
        ServiceProvider? _serviceProvider;

        public ServiceProvider ServiceProvider { get { return _serviceProvider; } }
        public Startup(Action<IServiceCollection, IConfiguration> deligate)
        {
            ////register Configuration
            /********************************/
            var environment = Environment.GetEnvironmentVariable("ASPNET_ENVIROMENT") ??
                            Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") ??
                            DefaultEnviroementName;


            string LocalPath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);

            var builder = new ConfigurationBuilder()
                .SetBasePath(LocalPath)
                .AddJsonFile($"appsettings.json", true, false)
                .AddJsonFile($"appsettings.{environment}.json", optional: true, reloadOnChange: false);

            _configuration = builder.Build();
            /********************************/

            var services = new ServiceCollection();
            deligate(services, _configuration);
            _serviceProvider = services.BuildServiceProvider();
        }

        public void Dispose()
        {
            if (_serviceProvider != null)
                _serviceProvider.Dispose();

            foreach (var provider in _configuration.Providers.OfType<JsonConfigurationProvider>())
            {
                if (provider.Source.FileProvider is PhysicalFileProvider pfp)
                {
                    pfp.Dispose();
                }
            }
        }
    }
```

PluginLoadContext 
```
 public class PluginLoadContext : AssemblyLoadContext
    {
        private AssemblyDependencyResolver _resolver;
        private string _path;
        public PluginLoadContext() : base(isCollectible: true)
        { }

        public PluginLoadContext(string pluginPath) : base(isCollectible: true)
        {
            _path = pluginPath;
            _resolver = new AssemblyDependencyResolver(pluginPath);
        }

        protected override Assembly Load(AssemblyName assemblyName)
        {
            if (_resolver != null)
            {
                string assemblyPath = _resolver.ResolveAssemblyToPath(assemblyName);
                if (assemblyPath != null)
                {
                    return LoadFromAssemblyPath(assemblyPath);
                }
            }
            return null;
        }

        protected override IntPtr LoadUnmanagedDll(string unmanagedDllName)
        {
            string libraryPath = _resolver.ResolveUnmanagedDllToPath(unmanagedDllName);
            if (libraryPath != null)
            {
                return LoadUnmanagedDllFromPath(libraryPath);
            }

            return IntPtr.Zero;
        }

        public IEnumerable<T> GetImplementations<T>()
        {
            var type = typeof(T);
            var assName = AssemblyName.GetAssemblyName(_path);
            var assembly = LoadFromAssemblyName(assName);
            var types = assembly.GetTypes().ToList();
            var other = new List<Type>();
            if (type.IsAbstract && !type.IsInterface)
            {
                other = types.Where(m => m.IsClass && !m.IsAbstract
                                        && m.IsSubclassOf(type)
                                ).ToList();
            }
            else
            {
                other = types.Where(t => type.IsAssignableFrom(t)).ToList();
            }
            return other
                .Select(t => Activator.CreateInstance(t))
                .Cast<T>();

        }

    }
```
test
```
  [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public async Task TestMethod1Async()
        {
            var directory = Directory.GetCurrentDirectory();
            var scrFolder = "src";
            var indexOfSrc = directory.IndexOf(scrFolder);
            var srcBaseDirectory = directory.Substring(0, indexOfSrc + scrFolder.Length);
            var pluginFolder = Path.Combine(srcBaseDirectory, "_Plugins");

            var plugins = Directory.GetDirectories(pluginFolder);

            var emailPlugin = plugins.Where(x => x.Contains("DatabasePlugin")).Single();
            //var emailPlugin = plugins.Where(x => x.Contains("EmailPlugin")).Single();

            for (int x = 0; x < 10000; x++)
            {
                var folderName = Path.GetFileName(emailPlugin);
                var fullpath = Path.Combine(emailPlugin, folderName + ".dll");

                var hostAlcWeakRef = await ExecuteAndUnload(fullpath);
            
                if (x % 10 ==0)
                {
                    // Poll and run GC until the AssemblyLoadContext is unloaded.
                    // You don't need to do that unless you want to know when the context
                    // got unloaded. You can just leave it to the regular GC.
                    for (int i = 0; hostAlcWeakRef.IsAlive && (i < 10); i++)
                    {
                        GC.Collect();
                        GC.WaitForPendingFinalizers();
                    }
                }
                Console.WriteLine($"Unload success: {!hostAlcWeakRef.IsAlive}");
            }

        }


        [MethodImpl(MethodImplOptions.NoInlining)]
        async Task<WeakReference>  ExecuteAndUnload(string assemblyPath)
        {
            // Create the unloadable HostAssemblyLoadContext
            var alc = new PluginLoadContext(assemblyPath);

            // Create a weak reference to the AssemblyLoadContext that will allow us to detect
            // when the unload completes.
            var alcWeakRef = new WeakReference(alc);

            // Load the plugin assembly into the HostAssemblyLoadContext.
            // NOTE: the assemblyPath must be an absolute path.
            //Assembly a = alc.LoadFromAssemblyPath(assemblyPath);

            // Get the plugin interface by calling the PluginClass.GetInterface method via reflection.
            var componentUI = alc.GetImplementations<BaseComponentUI>().Single();
            var plugin = alc.GetImplementations<IParadoxComponent>().Single();

            // Now we can call methods of the plugin using the interface
            await plugin.ExcuteAsync();
            
            // This initiates the unload of the HostAssemblyLoadContext. The actual unloading doesn't happen
            // right away, GC has to kick in later to collect all the stuff.
            alc.Unload();

            return alcWeakRef;
        }

    }
```

### Reproduction Steps

included

### Expected behavior

you should see the memory drop, it doesn't it just keeps increasing

### Actual behavior

memory is never free-ed

**Comment by John0King** [comment]
@Seabizkit   have u try  the `alc.EnterContextualReflection()` method like here does ? https://github.com/John0King/LazyMan.ModularLoader/blob/cb805ed3dbdbe6c01f3d1a4439d1f1ace5261a69/src/LazyMan.ModularLoader.AspNetCore/Extensions/StartupExtension.cs#L83-L86

the `EnterContextualReflection()`  can fix most issue related to  `Assembly.Load()`

The 'unload'  is really hard in ALC design ,  you must really carefull that all your type and dependencies do not intrduce hard reference in other ALC(default alc).

and note about the `Micorosft.Extensions.*`  packages, it can be load both by the default alc  and your  local  alc ,  and your local  alc may refernce to the default alc's assembly  if you not carefull about your assembly and dependencies.

**Comment by Seabizkit** [comment]
tried EnterContextualReflection() didn't have any effect

Memory is never free-ed
![image](https://user-images.githubusercontent.com/1920090/200127787-9cd88ac7-b2c5-4404-a831-4e7e76867548.png)

below are package referance:

data

- ParadoxData.Configuration
```
 <ItemGroup>
	<PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.8" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.8" />
	<PackageReference Include="Microsoft.Extensions.Configuration" Version="6.0.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="6.0.0" />
	<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="6.0.0" />
	<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="6.0.2" />
  </ItemGroup>
```

- ParadoxData.Configuration.Facade

```
none
```
plugin
- Paradox.Component.DatabasePlugin

```
<PackageReference Include="Microsoft.Extensions.Configuration" Version="6.0.0" />
<PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="6.0.0" />
<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="6.0.0" />
<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="6.0.0" />
<ProjectReference Include="..\..\Paradox.Component.Facade\Paradox.Component.Facade.csproj">
	<Private>false</Private>
	<ExcludeAssets>runtime</ExcludeAssets>
</ProjectReference>
<ProjectReference Include="..\..\..\Data\Paradox.Data.Configuration\ParadoxData.Configuration.csproj" />
<ProjectReference Include="..\..\..\Paradox.Data.Configuration.Facade\ParadoxData.Configuration.Facade.csproj" />
```

test
- Paradox.Plugin.Tests
```
<ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.3.2" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.2.10" />
    <PackageReference Include="MSTest.TestFramework" Version="2.2.10" />
    <PackageReference Include="coverlet.collector" Version="3.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
<ItemGroup>
    <ProjectReference Include="..\..\ComponentContainer\Paradox.Component.Facade\Paradox.Component.Facade.csproj" />
    <ProjectReference Include="..\..\ComponentContainer\Paradox.Component.Processor.Facade\Paradox.Component.Processor.Facade.csproj" />
  </ItemGroup>
```

**Comment by vitek-karas** [comment]
This is typically caused by a static cache which is not ALC aware and it stores references to `Type` or similar objects from the user assemblies. I don't know if `DbContext` has something like that, but I wouldn't be surprised if it did.

@roji would probably know more.

**Comment by John0King** [comment]
@vitek-karas    May I ask about the `Lazy<T>`  and the ALC unload feature ?

The `Lazy<T>` is load using the default ALC,  and the `T` is in user's ALC,  Does a   custome ALC  initialzie a static `Lazy<T>`  property/field  can cause the user's ALC can not be load ?

**Comment by vitek-karas** [comment]
The best way to think about the unloading is as if you're thinking about managed memory leaks. ALC's unload will happen only if all instances of the types defined in that assembly are freed (collected by GC) and also if any reflection references are freed (so nobody holds onto `System.Type` from that assembly).

The `Lazy<T>` is in no way special. If you have `Lazy<MyCat>` it doesn't matter that `Lazy<T>` comes from the default ALC, it will hold onto the reference of `MyCat` (from the other ALC) and as long as that reference lives the second ALC can't be unloaded. In that sense it's just like having a variable of type `MyCat` - the `Lazy<MyCat>` doesn't make it worse in any sense.

**Comment by John0King** [comment]
@vitek-karas   so in short answer is  if you plugin assembly have a static filed like below
```C#
public staitc readonly Lazy<MyCat> Cog = new Lazy<MyCat>(()=> new MyCat()) ;
```

then , you  ALC will never be unload  ,  right ?

**Comment by vitek-karas** [comment]
No - it will work just fine. The difference is that unloadable ALCs are not GC roots.
"GC root" is a location of a reference which never goes away. For example the default ALC is rooted by something in the runtime (runtime must always have the default ALC instance, so it keeps a refence to it - the root).
Through that all assemblies in the default ALC are also effectively rooted, since the ACL keeps references to them.
And through those all static fields in those assemblies are rooted as well (or rather their values are).

This is not true for unloadable ALC - there's nothing which would keep the unloadable ALC around forever - your code holds the reference to it when you create it via `new AssemblyLoadContext`, but if you release that reference, GC is free to collect it. And thus if there are no outside references to anything in that ALC, even the static fields in the assemblies in that ALC will get freed (or rather their values). (It's a bit more complicated than that, but the end result is basically this).

The problem is if some assembly in the default ALC stores a reference to the unloadable ALC is a static field. Then it becomes effectively rooted and GC will never collect it -> never be able to unload the ALC since there are live refences to something in it.

**Comment by Seabizkit** [comment]
@vitek-karas 

changing nothing but the .net version to 7.0 makes this a million times better. aka starts doing what I expect.

**Comment by vitek-karas** [comment]
@Seabizkit well - maybe somebody fixed something somewhere - I'm not aware of such change, but I'm definitely glad it works out. (It's highly unlikely we would backport any such fixed to 6 anyway)

**Comment by janvorli** [comment]
Maybe this is the fix: #58948

**Comment by Seabizkit** [comment]
@janvorli to me that is unclear as to what it was 'merged' into .6 or ,7, regardless the date is on Sep 10, 2021, so then it would of been fix in dot 6 if i had the latest... I tested my issue and was repeatable yesterday, **so then it cant be that.** to my understanding. glad its fixed but boy has this been a nightmare!

**Comment by roji** [comment]
It sounds like this issue no longer occurs in .NET 7.0... If you're still encountering issues, let me know and I can take a look at the EF side of things.

**Comment by Seabizkit** [comment]
my 2 cents  considering :
https://dotnet.microsoft.com/en-us/platform/support/policy

and the nature of the issue, i would of thought these types of things would defo be backported its not a feature and its not performance.

sorry I'm biased as there nothing worse than trying to rack your brain around something which simply is broken but you don't know.

Ill give it a week and then close this

**Comment by janvorli** [comment]
@Seabizkit I believe the fix should be ported.

**Comment by agocke** [comment]
I don't think this is worth backporting given the level of impact right now. We can re-evaluate based on user feedback.
