### ISSUE TITLE
Crash in ThrowHelper.ThrowJsonReaderException

### ISSUE THREAD

**Issue by RyanMTurner** [dotnet/runtime#77898]
### Description

We're using System.Text.Json in a production Xamarin.Forms app, for which we use AppCenter to track Crashes. We've received a number of SIGABRT signals pointing to ThrowHelper.ThrowJsonReaderException that I'd like to bring to your attention.

Stack Trace:
[StackTrace.txt](https://github.com/dotnet/runtime/files/9940147/StackTrace.txt)

### Reproduction Steps

The issue happens fairly rarely; our music app loads tons of content from our server that most people play through no problem. No one on my team has been able to reproduce the issue ourselves.

Some examples of the issues include:
`SIGABRT: '8' is an invalid end of a number. Expected a delimiter. LineNumber: 0 | BytePositionInLine: 721313.`
`SIGABRT: Expected end of string, but instead reached end of data. LineNumber: 0 | BytePositionInLine: 306748.` (happened with the same stack trace above except in `ConsumeString` instead of `ConsumeNumber`).

### Expected behavior

Consider the following deserialize wrapper function:
```csharp
private static readonly System.Text.Json.JsonSerializerOptions options = new System.Text.Json.JsonSerializerOptions() { IncludeFields = true };

protected ValueTask<T> DeserializeJsonAsync<T>(Stream data) where T : class
{
    try
    {
        if (data == null)
            return new ValueTask<T>(Task.FromResult<T>(null));
        return System.Text.Json.JsonSerializer.DeserializeAsync<T>(data, options);
    }
    catch (Exception ex)
    {
        //Error logging removed for brevity
        return new ValueTask<T>(Task.FromResult<T>(null));
    }
}
```

One would expect to catch a JsonException and for the application to continue.

### Actual behavior

Issues deserializing JSON occasionally result in `SIGABRT` and application closure rather than a JsonException.

### Configuration

Target framework: .NET Standard 2.0
Affected devices:
iPad12,1 - iOS 15.4.1
iPhone14,2 - iOS 15.6.1
iPhone XR - iOS 15.6.1
iPhone 11 Pro - iOS 15.6.1

**Comment by steveisok** [comment]
@RyanMTurner Is this crash happening on legacy xamarin or .NET 6?

**Comment by RyanMTurner** [comment]
@steveisok legacy xamarin

**Comment by krwq** [comment]
Is this reproing with .NET 7 package? We've done lots of stability fixes in .NET 7 timeline

**Comment by krwq** [comment]
@RyanMTurner please see the question above. Does that repro with .NET 7 System.Text.Json package? Is there any repro which will make this show up most of the time (i.e. loop/parallel loop)?

**Comment by RyanMTurner** [comment]
We are using .NET 7.3, System.Text.Json 6.0.4. I will update the package to 7.0.0 and let you know if we see any improvement.
