### ISSUE TITLE
[API Proposal]: adding explicit casting from int, float, double, byte, decimal to bool

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#77908]
### Background and motivation

I suggest adding explicit casting from int, float, double, byte, decimal to bool. Such an implicit casting algorithm, 0 is false, everything except 0 is true

### API Proposal

```csharp
int count = 0;
bool check = (bool)count;
```

### API Usage

```csharp
int index = 100;
while ((bool)index--)
{
    Console.WriteLine(index);
}
while (Convert.ToBoolean(index--))
{
    Console.WriteLine(index);
}
```

**Comment by tannergooding** [comment]
This is not something we're interested in doing.

The conversion is lossy and altogether less readable than `!= 0`. There are many subtleties that can go wrong and many edge cases where the proposed conversions don't necessarily make sense (for example, the handling of `NaN`, `Infinity`, or `NegativeZero`).

**Comment by Mr0N** [comment]
https://learn.microsoft.com/ru-ru/dotnet/api/system.convert?view=net-7.0 Why is there no Convert.ToInt128 here?

**Comment by tannergooding** [comment]
`Int128`/`UInt128` are new user-defined type, not a built-in runtime primitive. They do not have `TypeCode` values associated with them and cannot integrate with the rest of the functionality `Convert` was originally designed to support.

New code should utilize the `Generic Math` APIs, where relevant, instead.

**Comment by Mr0N** [comment]
> `Int128`/`UInt128` are new user-defined type, not a built-in runtime primitive. They do not have `TypeCode` values associated with them and cannot integrate with the rest of the functionality `Convert` was originally designed to support.
> 
> New code should utilize the `Generic Math` APIs, where relevant, instead.
Generic match is a cool thing) only if int128 is not a runtime type, will there be any differences) between the other types (for example, in multithreading), and for example when people will use generic match, they will not know which types will get to them
