### ISSUE TITLE
Rename Directory.CreateDirectory to Directory.Create to be consistent with File API

### ISSUE THREAD

**Issue by Aurumaker72** [dotnet/runtime#77919]
### Background and motivation

The System.IO.File API provides the following method for creating a file:

```cs
File.Create(path);
```

The System.IO.Directory API however provides this method:

```cs
Directory.CreateDirectory(path);
```

To be consistent with the File API (and Directory API itself, see `Directory.Delete`) and avoid redundancy, `Directory.CreateDirectory` should be renamed to `Directory.Create`

### API Proposal

```csharp
namespace System.IO;

public static partial class Directory
{
    public static DirectoryInfo Create(string path)
    {
        // ...
    }
}
```

### Risks
This API change breaks code relying on `Directory.CreateDirectory`, as the method has been renamed.

**Comment by teo-tsirpanis** [comment]
> This API change breaks code relying on Directory.CreateDirectory, as the method has been renamed.

Exactly for this reason we cannot change it. Naming mistakes unfortunately happen.

**Comment by Aurumaker72** [comment]
> > This API change breaks code relying on Directory.CreateDirectory, as the method has been renamed.
> 
> Exactly for this reason we cannot change it. Naming mistakes unfortunately happen.

Isn't that what the entire concept of obsoleting is for?

```cs
public DirectoryInfo Create(string path)
{
     ...
}

[Obsolete]
public DirectoryInfo CreateDirectory(string path) => Create(path);

```

**Comment by danmoseley** [comment]
> Isn't that what the entire concept of obsoleting is for?

Obsoleting is a way to designate API that isn't recommended. It doesn't prevent calling code breaking and it doesn't make it cheaper to fix the break so we would then have two documented API. A much stronger reason is needed to make a change like this.
