### ISSUE TITLE
There is no int 128

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#77912]
There is no int 128
https://github.com/dotnet/runtime/blob/bbcff6bc422da3d9b1904281a86014236ce50f2e/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs#L2257
https://learn.microsoft.com/en-us/dotnet/api/system.int128?view=net-7.0

**Comment by tannergooding** [comment]
`Int128`/`UInt128` are new "user-defined" types and are not runtime primitives. There is no TypeCode specifier for them and there is no atomicity for them.
