### ISSUE TITLE
Vector128.AndNot is broken

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#77942]
```csharp
static Vector128<byte> AndNot1(Vector128<byte> v1) => 
    Vector128.AndNot(v1, Vector128.Create((byte)63));

static Vector128<byte> AndNot2(Vector128<byte> v1) => 
    Sse2.AndNot(v1, Vector128.Create((byte)63));
```
Crossplatform helper seems to re-order arguments (AndNot is not commutative)
```asm
; Assembly listing for method C:AndNot1
       C5F9100515000000     vmovupd  xmm0, xmmword ptr [reloc @RWD00]
       C5F9DF02             vpandn   xmm0, xmm0, xmmword ptr [rdx]
       C5F91101             vmovupd  xmmword ptr [rcx], xmm0
       488BC1               mov      rax, rcx

; Assembly listing for method C:AndNot2
       C5F91002             vmovupd  xmm0, xmmword ptr [rdx]
       C5F9DF0511000000     vpandn   xmm0, xmm0, xmmword ptr [reloc @RWD00]
       C5F91101             vmovupd  xmmword ptr [rcx], xmm0
       488BC1               mov      rax, rcx
```
```csharp
        var a = Vector128.Create((byte)0xAB);
        Console.WriteLine(AndNot1(a));
        Console.WriteLine(AndNot2(a));
```
Output: (supposed to be the same)
```
<128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128> - not correct
<20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20>
```

**Comment by EgorBo** [comment]
Turns out it's not a bug, it's `Sse2.AndNot` doing NotAnd on xarch... so unfortunate

**Comment by gfoidl** [comment]
Maybe the xml-docs should have a hint here?
They are documented correctly https://github.com/dotnet/runtime/blob/3b0ef303e0969fa376569baa38a98c870a8f7561/src/libraries/System.Private.CoreLib/src/System/Runtime/Intrinsics/X86/Sse2.cs#L207-L211 but this sometimes bites me too (the xplat-intrinsics are more natural here IMO), but Sse2 follows just the plat-intrinsics.

So something like
```diff
        /// <summary>
        /// __m128i _mm_andnot_si128 (__m128i a,  __m128i b)
        ///   PANDN xmm, xmm/m128
+       /// Note: it is actually a NotAnd operation.
        /// </summary>
```

**Comment by stephentoub** [comment]
> Maybe the xml-docs should have a hint here

In general I think our docs for the intrinsics should be more descriptive, rather than just naming the corresponding instruction.

**Comment by tannergooding** [comment]
> In general I think our docs for the intrinsics should be more descriptive, rather than just naming the corresponding instruction.

This is blocked on getting permission from Intel and/or AMD to reproduce their docs in our docs.

cc. @terrajobst who was driving this from the PM side
