### ISSUE TITLE
[wasm] RuntimeError: memory access out of bounds - when configured with undefined `asset.name`

### ISSUE THREAD

**Issue by Kuinox** [dotnet/runtime#77946]
### Description

I'm trying to run a .NET program with mono wasm in a Web Worker.  

My first problem was that `dotnet.js` is now only distributed as a module, and [Firefox doesn't support module in a webworker yet](https://bugzilla.mozilla.org/show_bug.cgi?id=1247687).  

I worked around this by transpiling `dotnet.js` using a JS bundler, which I got the idea from [here](https://github.com/dotnet/runtime/issues/72990#issuecomment-1263219681).  

While `dotnet.js` has been transpiled, the `dotnet.wasm` come from [the runtime nuget package](https://www.nuget.org/packages/Microsoft.NETCore.App.Runtime.Mono.browser-wasm/7.0.0-rc.2.22472.3), and has not beed modified.

### Reproduction Steps

```js
console.log("Worker started.");
const dirUrl = removeLastPart(self.location.toString());
importScripts(new URL('dotnet.js', dirUrl));
console.log(self.dotnet.dotnet);
const assets = [
    {
        behavior: "dotnetwasm",
        hash: "sha256-vjazVGAHT+1Be7ZH5Amb8i9swFPmypF8KCz+cQGai9A=",
        resolvedUrl: "../runtime/7.0/dotnet.wasm"
    },
    {
        behavior: "assembly",
        resolvedUrl: "../runtime/7.0/System.Private.CoreLib.dll"
        }
    ]
self.dotnet.dotnet.moduleConfig.config = {
    assemblyRootFolder: "runtime/7.0/",
    disableDotnet6Compatibility: false,
    entryAssembly: "Draco.Compiler.Cli.dll",
    assets: assets,
    diagnosticTracing: true,
    enablePerfMeasure: true
};
self.dotnet.dotnet.moduleConfig.configSrc = null;
const wasm = await self.dotnet.default(self.dotnet.dotnet.moduleConfig);
```

### Expected behavior

No error, or clearer message if it's misuses.

### Actual behavior

```
Worker started.
worker.js:10 ao {moduleConfig: {…}}
dotnet.js:formatted:5253 MONO_WASM: mono_wasm_pre_init_essential
dotnet.js:formatted:5170 MONO_WASM: preInit
dotnet.js:formatted:5261 MONO_WASM: mono_wasm_pre_init_essential_async
dotnet.js:formatted:5340 MONO_WASM: instantiate_wasm_module
dotnet.js:formatted:2704 MONO_WASM: Attempting to download '../runtime/7.0/dotnet.wasm' for undefined
dotnet.js:formatted:5268 MONO_WASM: mono_wasm_pre_init_full
dotnet.js:formatted:2572 MONO_WASM: mono_download_assets
dotnet.js:formatted:2704 MONO_WASM: Attempting to download '../runtime/7.0/System.Private.CoreLib.dll' for undefined
dotnet.js:formatted:5346 MONO_WASM: instantiate_wasm_module done
dotnet.js:formatted:2845 MONO_WASM: instantiate_wasm_module streaming
dotnet.js:formatted:5195 MONO_WASM: preRunAsync
dotnet.js:formatted:5208 MONO_WASM: onRuntimeInitialized
dotnet.js:formatted:2795 MONO_WASM: Loaded:undefined as assembly size 3801752 from ../runtime/7.0/System.Private.CoreLib.dll
dotnet.js:formatted:2634 MONO_WASM: Error in mono_download_assets: RuntimeError: memory access out of bounds
```

### Regression?

Did not tested.

### Configuration

- mono-wasm
- lastest version of the nuget package as of now: https://www.nuget.org/packages/Microsoft.NETCore.App.Runtime.Mono.browser-wasm/7.0.0-rc.2.22472.3
- Happens both on chrome and firefox

### Other information

I tested against a debug build of mono-wasm, which is about one week old.
It output a better stacktrace:  
```
RuntimeError: memory access out of bounds
    at strcasecmp (http://localhost:5173/runtime/7.0/dotnet.wasm:wasm-function[17447]:0x2f168c)
    at mono_wasm_add_assembly (http://localhost:5173/runtime/7.0/dotnet.wasm:wasm-function[106]:0x8680)
    at c._mono_wasm_add_assembly (http://localhost:5173/_framework/dotnet.js:74:5552)
    at N (http://localhost:5173/_framework/dotnet.js:58:4372)
    at Object.mono_wasm_add_assembly (http://localhost:5173/_framework/dotnet.js:58:4624)
    at Ia (http://localhost:5173/_framework/dotnet.js:13:27395)
    at http://localhost:5173/_framework/dotnet.js:13:22547
    at async Promise.all (index 1)
```

**Comment by radical** [comment]
cc @pavelsavara

**Comment by pavelsavara** [comment]
The log message gives hint about the actual issue: Loaded:**undefined** as assembly

https://github.com/dotnet/runtime/blob/4ff7eca4e02f8e09d134e4fac0dd202d484df899/src/mono/wasm/runtime/assets.ts#L349

I guess you just need to set `name` for your assets.

**Comment by Kuinox** [comment]
Thank it was that!  
I did found it suspicious but I didn't thought an undefined would cause an issue in mono itself.  

Sadly I've hit another roadblock:  
```
dotnet.js:6 Error: [MONO] * Assertion at C:/Development/runtime/src/mono/mono/metadata/assembly.c:2712, condition `corlib' not met

    at Sr (dotnet.js:6:982)
    at Object.tr (dotnet.js:6:1309)
    at ks (dotnet.js:68:67294)
    at wasm_trace_logger (dotnet.wasm:0x8b7a)
    at eglib_log_adapter (dotnet.wasm:0x13e378)
    at monoeg_g_logstr (dotnet.wasm:0x2c1b64)
    at monoeg_g_logv_nofree (dotnet.wasm:0x2c1aaf)
    at monoeg_assertion_message (dotnet.wasm:0x2c1be5)
    at mono_assertion_message (dotnet.wasm:0x2c1c44)
    at mono_assembly_load_corlib (dotnet.wasm:0x45dea)
 ```
While I did add the corelib in the assets, as I can see  in a previous log: 
`MONO_WASM: Loaded:System.Private.CoreLib as assembly size 3801752 from ../runtime/7.0/System.Private.CoreLib.dll`

**Comment by pavelsavara** [comment]
Try to run the same in the main browser thread on chrome to see if this is difference in the environment or in your code.

I guess by now you know how to find the code which throws that 
https://github.com/dotnet/runtime/blob/5d1b7e77e054f74de05d6cd34de11c55ffbd125f/src/mono/mono/metadata/assembly.c#L2712

**Comment by Kuinox** [comment]
It also throws in the same way in the main browser thread.

> I guess by now you know how to find the code which throws that

Yes, I tried to understand why it doesn't work by having the wasm in step by step and the C code side by side, but after going through 1-2 layer of function call I can't quite follow.

I'll will redo my attempt from scratch by starting from a working example and iterate to what I want...

**Comment by pavelsavara** [comment]
This may help with troubleshooting (or equivalent in your startup sequence)
```
        .withEnvironmentVariable("MONO_LOG_LEVEL", "debug")
        .withEnvironmentVariable("MONO_LOG_MASK", "all")
```

**Comment by pavelsavara** [comment]
and this in project file
```
<WasmBuildNative>true</WasmBuildNative>
<WasmNativeStrip>false</WasmNativeStrip>
```

**Comment by pavelsavara** [comment]
This should assert that assembly names is string

**Comment by Elringus** [comment]
Sorry this is a bit off-topic, but just wanted to clarify if `browser-wasm` is designed to run in workers (ie, doesn't depend on `window` or other APIs not available for workers)? After reading https://devblogs.microsoft.com/dotnet/use-net-7-from-any-javascript-app-in-net-7/ and checking the samples I had an impression the intended use case is to run it on the main browser thread only. Is worker environment officially supported (and will be maintained) under the `browser-wasm` runtime?

**Comment by Kuinox** [comment]
I don't know if it's officially supported but I run DLLs in a webworker without any issue now.
