### ISSUE TITLE
[API Proposal]: Add 2 more constructors to ConcurrentDictionary class

### ISSUE THREAD

**Issue by Hermholtz** [dotnet/runtime#77948]
### Background and motivation

The `System.Collections.Generic.Dictionary<TKey,TValue>` type has the following constructor (among others) that has just one parameter, which allows to specify the initial dictionary capacity to help avoid reallocations and copying when the storage needs to grow:
```csharp
public Dictionary (int capacity);
``` 

For some reason, if you want to use `System.Collections.Concurrent.ConcurrentDictionary<TKey,TValue>` and set the initial capacity, you need to use a constructor with 2 parameters:
```csharp
public ConcurrentDictionary (int concurrencyLevel, int capacity);
```
There is no constructor that only accepts `int capacity`. I always must specify this arcane `concurrencyLevel` parameter. We, as the framework users, don't know the default value of this parameter, because it is not documented, and we surely can assume that it may change in the future. Besides, we should not to worry about properly determining a correct concurrency level, when we only want to set the capacity. If we're unfortunate enough to specify a constant value there, the program will have the concurrency set improperly when running on a different machine - e.g. may have too many locks on only couple of cores, or not enough locks on a powerful machine.

To fix the above and as an added benefit to make the API more consistent with `Dictionary<TKey,TValue>` I propose to add two more constructors as shown below.

### API Proposal

```csharp
namespace System.Collections.Concurrent;

public class ConcurrentDictionary<TKey,TValue>
{
    public ConcurrentDictionary (int capacity);
    public ConcurrentDictionary (int capacity, System.Collections.Generic.IEqualityComparer<TKey>? comparer);
}
```

### API Usage

```csharp
// I know that there will be more or less 1000 dictionary items and want to reduce reallocations/copying.
// According to the docs, "the capacity should not be divisible by a small prime number", hence a prime here.
var dict = new ConcurrentDictionary<int,MyClass>(1009);

// Use the dictionary as usual.
```

### Alternative Designs

Alternative is to use the existing constructors:
```csharp
public ConcurrentDictionary (int concurrencyLevel, int capacity);
public ConcurrentDictionary (int concurrencyLevel, int capacity, System.Collections.Generic.IEqualityComparer<TKey>? comparer);
```
and maintain the concurrency level at our side, perhaps providing there `Environment.ProcessorCount`. It is just extraneous and not clear.

### Risks

This addition does not create a breaking change and is a really simple modification. There's no added maintenance burden, as the implicit concurrency level value is already used in some constructors (such as the default one).

I assume that the constructors weren't implemented so far, because there are others taking just one `int` value, such as this:
```csharp
public ConcurrentDictionary (int concurrencyLevel, System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<TKey,TValue>> collection, System.Collections.Generic.IEqualityComparer<TKey>? comparer);
```
and the API designer may had thought that it might have been confusing to have the first parameter sometimes meaning concurrency level, and other times the capacity. This is unwarranted, and benefits far outweigh this risk.

**Comment by eiriktsarpalis** [comment]
> I assume that the constructors weren't implemented so far, because there are others taking just one `int` value, such as this:
>```csharp
>public ConcurrentDictionary (int concurrencyLevel, >System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<TKey,TValue>> collection, >System.Collections.Generic.IEqualityComparer<TKey>? comparer);
>```
> and the API designer may had thought that it might have been confusing to have the first parameter sometimes meaning concurrency level, and other times the capacity. This is unwarranted, and benefits far outweigh this risk.

I suspect you are right, and confusion about the meaning of the first integer parameter might be sufficient for this proposal to not be accepted. @bartonjs are there any FDG's we need to observe in cases like this?

**Comment by bartonjs** [comment]
> are there any FDG's we need to observe in cases like this?

The most specific/appropriate one is

> DO NOT have overloads with parameters at the same position and similar types, yet with different semantics.

Since `concurrencyLevel` is the "first int", there shouldn't be overloads that have `capacity` as the "first int", especially not as literally the first parameter.

**Comment by GSPP** [comment]
How about adding a documented default value (the usual suspect: `-1`) for `concurrencyLevel`?

**Comment by stephentoub** [comment]
> How about adding a documented default value (the usual suspect: -1) for concurrencyLevel?

This sounds like the right answer.
