### ISSUE TITLE
Handling preinstall pre-requivisites

### ISSUE THREAD

**Issue by tapika** [dotnet/runtime#77953]
Currently ReadyToRun requires some libraries to be preinstalled on windows - before readytorun executable can be actually used.

The list of what needs to be pre-installed is not so big - once you run windows in virtual machine:

(1) 

```
R2REXE.EXE - System Error
---------------------------
The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem. 
---------------------------
OK   
```

which in a turn requires 

```
Visual C++ Redistributable for Visual Studio 2015-2019.
```

After that it's still possible to get an error like this:

(2)

```
Failed to load the dll from [C:\Users\vagrant\AppData\Local\Temp\.net\r2rexe\yptd33ya.peh\hostfxr.dll], HRESULT: 0x80070057
The library hostfxr.dll was found, but loading it from C:\Users\vagrant\AppData\Local\Temp\.net\r2rexe\yptd33ya.peh\hostfxr.dll failed
  - Installing .NET Core prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306
```

In (2) link is quite obvious - so it gives some hints what you need to pre-install - that is (1) is mandatory for all windows versions, and (2) is mandatory only for windows 7.

I understand that readytorun is actually ready to run .exe and no additional installations are necessary.

As for (2) - I think this can be marked as windows 7 special "upgrade" requirement - if .dll cannot be loaded, then you're forced to update windows.

I haven't yet tested windows update - best approach could be that (1) and (2) would be included in windows update itself, and then ReadyToRun could work out of box with assumption that user has ran windows update.

How complex would it be to include at least (1) (But ideally (1) + (2)) into readytorun executable image ?

Within ticket

`ReadyToRun + PublishSingleFile=true: Possibility to specify compression codec and compression level`
https://github.com/dotnet/runtime/issues/61073

you've also mentioned about fully custom apphost - I'm thinking more about possibility of extending current apphost.
Would it be possible to add mechanism of linking native static library to current apphost.

Also being able to `make api-ms-*.dll` entries as delay loadable. Assumption is that if (1) is not installed, it would be installed
by extension library and loaded in place. (I'm also thinking on using [dllloader](https://github.com/tapika/dllloader) to just load bunch of vc2015-2019 .dll's in-place - but that could be my own solution using custom host linking approach)

So final target for this ticket could be:
A) ReadyToRun windows .exe can execute without anything pre-installed.
or 
B) Custom apphost offers a possibility to extend it so (A) can be reached by application developer.

**Comment by tapika** [comment]
FYI @trylek

**Comment by jkotas** [comment]
ReadyToRun is AOT compilation of IL code. It is not related to your question.

**Comment by tapika** [comment]
> I think you meant PublishSingleFile.

Yes, you're probably right.

**Comment by agocke** [comment]
Regarding

> The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer

That should only happen on an out-of-date Windows 7 install. Any updated OS should have the MSVC redistributable installed.

For

> The library hostfxr.dll was found, but loading it from

This means that you're using the "framework-dependent" version of the single-file bundle, but don't have a copy of .NET Core installed. You can avoid installing .NET Core by using a self-contained install, but it will be much larger.

**Comment by tapika** [comment]
> That should only happen on an out-of-date Windows 7 install. Any updated OS should have the MSVC redistributable installed.

That is true, tested on windows 8.1 - works out of box.

> > The library hostfxr.dll was found, but loading it from
> 
> This means that you're using the "framework-dependent" version of the single-file bundle, but don't have a copy of .NET Core installed. You can avoid installing .NET Core by using a self-contained install, but it will be much larger.

In windows 8.1 works ok - but does mean that .net core is installed in there ?

I think ticket can be closed, issue is applicable to windows only, and it's users can survive with manual install instructions.

**Comment by agocke** [comment]
My mistake, I think I also misread your error message -- the message isn't that hostfxr is missing from the machine install location, it's that it's missing from the extraction location (~/Temp/.net). That issue seems specific to .net core 3.1, since we changed the behavior in .NET 6 to not require extracting runtime files.

I believe that either moving to .NET 6, or being on a fully up-to-date windows 7 release (with all patches and service packs) should solve your problem. Feel free to comment and let me know if this comes up again.
