### ISSUE TITLE
[API Proposal]: MemoryExtensions.AsSpan(this string? text, Range range)

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#77955]
### Background and motivation

Some APIs return `Range` instances to specify subsets.  You can use such a `Range` with a string like `str[range]` to get the substring, but that allocates a string.  `MemoryExtensions` exposes `AsSpan` methods that take `Range`s, but only for `T[]` and `ArraySegment<T>`, not `string`.  It does have a `Range`-based `string` extension, but only `AsMemory`.

### API Proposal

```csharp
namespace System;

public static class MemoryExtensions
{
    public static ReadOnlySpan<char> AsSpan(this string? text, Range range);
}
```

### API Usage

```csharp
ReadOnlySpan<char> span = string.AsSpan(range);
```

**Comment by stephentoub** [comment]
(I have a memory of discussing this at some point, and deciding that `str.AsSpan()[range]` was sufficient, but I can't find that now, and if that was the decision, the presence of the array-based span methods and String-based memory method is strangely inconsistent.)

**Comment by Tornhoof** [comment]
Why is the string nullable in your proposal?

**Comment by stephentoub** [comment]
> Why is the string nullable in your proposal?

For consistency with the other such methods, where null is permitted in certain circumstances, e.g. https://github.com/dotnet/runtime/blob/6bae35120761e5929ee37b9fcb0c08645db1bb0a/src/libraries/System.Private.CoreLib/src/System/MemoryExtensions.cs#L137

**Comment by eerhardt** [comment]
There are some other minor inconsistencies with MemoryExtensions.

https://github.com/dotnet/runtime/blob/e1081df6da8ffbe667a7ea909a154c5b59e86351/src/libraries/System.Memory/ref/System.Memory.cs#L208-L220

* The Array and ArraySegment overloads also have `System.Index startIndex` overloads along with the `System.Range` overload. Should we add a System.Index overload for `string` as well?

https://github.com/dotnet/runtime/blob/e1081df6da8ffbe667a7ea909a154c5b59e86351/src/libraries/System.Memory/ref/System.Memory.cs#L195-L207

* The ArraySegment `AsMemory` methods don't have `Index` or `Range` overloads, like we have for `string` and `T[]`. Should we add them as well to make these 2 sets of methods be consistent?

**Comment by bartonjs** [comment]
Since there's already an AsMemory overload with the same shape, this seems like it's just properly squaring off the feature.

Since `AsSpan(string?, Index)` isn't present, but `AsSpan(T[], Index)` and `AsSpan(ArraySegment<T>, Index)` do, we've added that to further square this off.

```C#
namespace System;

public static partial class MemoryExtensions
{
    public static ReadOnlySpan<char> AsSpan(this string? text, Range range);
    public static ReadOnlySpan<char> AsSpan(this string? text, Index startIndex);
}
```
