### ISSUE TITLE
[wasm][debugger] `DebuggerRootHidden` elements cannot have identical names

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#77965]
In `DebuggerHidden` of Console App we can have two children of the same name (e.g. [0]): 
![image](https://user-images.githubusercontent.com/32700855/200256130-08a35008-9811-4f93-b791-662409ee0455.png)

When sending identical data from the proxy to IDE we are getting an error (or debugger connection dies - to be checked).
The problem gets solved when we modify the names, so that they would be unique in a single `JArray`. However, this way the behavior is not fully in line with coreclr's app debugging experience.

Try to fix it, so that names would not need to be edited.

**Comment by ilonatommy** [comment]
A sample repro code:
```
public class ClassThatContainsRootHiddenFields
{
    [DebuggerBrowsable(DebuggerBrowsableState.RootHidden)]
    public List<int> OnlyMyChildrenAreVisible1 = new List<int>() { 1, 2 };

    [DebuggerBrowsable(DebuggerBrowsableState.RootHidden)]
    public List<int> OnlyMyChildrenAreVisible2 = new List<int>() { 11, 22 };
}
```

When evaluating `ClassThatContainsRootHiddenFields` we should see 4 elements named "[0]", "[1]", "[0]", "[1]" of corresponding values from the lists: 1, 2, 11, 22. However, we cannot have two names that would be the same, so as a workaround we are returning names that would be unique: "OnlyMyChildrenAreVisible1[0]", "OnlyMyChildrenAreVisible1[1]", "OnlyMyChildrenAreVisible2[0]", "OnlyMyChildrenAreVisible2[1]". It's not 100% the same behavior as coreclr but it works. I am not sure if we are able to fix it easily.

**Comment by thaystg** [comment]
This is fixed by the new debugger.
