### ISSUE TITLE
[libraries-pgo] Assert failure: Reached the "unreachable" in getArrayOrStringLength

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#77968]
Work item: https://dev.azure.com/dnceng-public/public/_build/results?buildId=74655&view=ms.vss-test-web.build-test-results-tab&runId=1537616&resultId=194524&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab
Console log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-482d4a39acdd47cea7/System.Text.RegularExpressions.Tests/1/console.e2964816.log?helixlogtype=result

```scala
Assert failure(PID 16183 [0x00003f37], Thread: 16712 [0x4148]): Reached the "unreachable": FAILED: <unreachable>
    File: /__w/1/s/src/coreclr/vm/jitinterface.cpp Line: 1747
    Image: /datadisks/disk1/work/B76F0A0C/p/dotnet
```

This is inside `getArrayOrStringLength`, cc @EgorBo

**Comment by jakobbotsch** [comment]
There's also a win-x64 occurrence:
Work item: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-1d8c512ab7184e58a2/System.Net.Http.WinHttpHandler.Functional.Tests/1/console.db881519.log?helixlogtype=result
Console log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-1d8c512ab7184e58a2/System.Net.Http.WinHttpHandler.Functional.Tests/1/console.db881519.log?helixlogtype=result

**Comment by EgorBo** [comment]
Hm. that sounds like an assert from the code I added 🤔
