### ISSUE TITLE
OutOfMemoryException in container that didn't have enough memory to allocate an LOH segment

### ISSUE THREAD

**Issue by allan-ma** [dotnet/runtime#77961]
### Description

After upgrade .NET Core 3.1 to .NET 6, our service throw a lot of OutOfMemoryException

Part of the stacktrace of OutOfMemoryExcetion

```System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.\n   at System.GC.AllocateNewArray(IntPtr typeHandle, Int32 length, GC_ALLOC_FLAGS flags)\n   at System.GC.<AllocateUninitializedArray>g__AllocateNewUninitializedArray|66_0[T](Int32 length, Boolean pinned)\n   at System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1.Rent(Int32 minimumLength)\n   at Azure.Storage.Shared.PooledMemoryStream.BufferStreamPartitionInternal(Stream stream, Int64 minCount, Int64 maxCount, Int64 absolutePosition, ArrayPool`1 arrayPool, Nullable`1 maxArrayPoolRentalSize, Boolean async, CancellationToken cancellationToken)\n   at Azure.Storage.PartitionedUploader`2.GetBufferedPartitionInternal(Stream stream, Int64 minCount, Int64 maxCount, Int64 absolutePosition, Boolean async, CancellationToken cancellationToken)\n   at Azure.Storage.PartitionedUploader`2.GetPartitionsAsync(Stream stream, Nullable`1 streamLength, Int64 blockSize, GetNextStreamPartition getNextPartition, Boolean async, CancellationToken cancellationToken)+MoveNext()\n   at Azure.Storage.PartitionedUploader`2.GetPartitionsAsync(Stream stream, Nullable`1 streamLength, Int64 blockSize, GetNextStreamPartition getNextPartition, Boolean async, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()\n   at Azure.Storage.PartitionedUploader`2.UploadInParallelAsync(Stream content, Nullable`1 contentLength, Int64 blockSize, TServiceSpecificArgs args, IProgress`1 progressHandler, CancellationToken cancellationToken)\n   at Azure.Storage.PartitionedUploader`2.UploadInParallelAsync(Stream content, Nullable`1 contentLength, Int64 blockSize, TServiceSpecificArgs args, IProgress`1 progressHandler, CancellationToken cancellationToken)\n   at Azure.Storage.PartitionedUploader`2.UploadInternal(Stream content, TServiceSpecificArgs args, IProgress`1 progressHandler, Boolean async, CancellationToken cancellationToken)\n   at Azure.Storage.Blobs.Specialized.BlockBlobClient.UploadAsync(Stream content, BlobUploadOptions options, CancellationToken cancellationToken)\n ```

The reason of the OutOfMemoryExcetion is:

```
>analyzeoom
Managed OOM occurred after GC #249 (Requested to allocate 134217784 bytes)
Reason: Didn't have enough memory to allocate an LOH segment
```

Other Info:
```
> gcheapstat
Heap             Gen0         Gen1         Gen2          LOH          POH
Heap0          345408          168     14066176    408819400     10284808

Free space:                                                               Percentage
Heap0           12864           24        29416         6616           24 SOH:  0% LOH:  0% POH:  0%

Committed space:
Heap0        22887768     22887936     36954112    408952832     10293248

> eeheap -gc
Number of GC Heaps: 1
generation 0 starts at 0x00007FF6C0D692A8
generation 1 starts at 0x00007FF6C0D69200
generation 2 starts at 0x00007FF6BFFFF000
ephemeral segment allocation context: none
         segment             begin         allocated         committed    allocated size    committed size
00007FF6BFFFE000  00007FF6BFFFF000  00007FF6C0DBD7E8  00007FF6C233D000  0xdbe7e8(14411752)  0x233e000(36954112)
Large object heap starts at 0x00007FF6FFFFF000
         segment             begin         allocated         committed    allocated size    committed size
00007FF6FFFFE000  00007FF6FFFFF000  00007FF7185E06C8  00007FF718601000  0x185e16c8(408819400)  0x18602000(408952832)
Pinned object heap starts at 0x00007FF77FFFF000
00007FF77FFFE000  00007FF77FFFF000  00007FF7809CDF08  00007FF7809D0000  0x9cef08(10284808)  0x9d1000(10293248)
Total Allocated Size:              Size: 0x19d6edb8 (433515960) bytes.
Total Committed Size:              Size: 0x1b311000 (456200192) bytes.
------------------------------
GC Allocated Heap Size:    Size: 0x19d6edb8 (433515960) bytes.
GC Committed Heap Size:    Size: 0x1b311000 (456200192) bytes.

> dumpgcdata
concurrent GCs                : 0
compacting GCs                : 244
promoting GCs                 : 166
GCs that did demotion         : 4
card bundles                  : 244
elevation logic               : 0

[info per heap]
Interesting data points
           pre short: 2
          post short: 51
         merged pins: 0
      converted pins: 0
             pre pin: 3
            post pin: 50
    pre and post pin: 2
    pre short padded: 0
   post short padded: 0

Compacting reasons
[M]             low on ephemeral space: 0
[W]                 high fragmentation: 192
[M]             couldn't allocate gaps: 0
[M]          user specfied compact LOH: 48
[M]                 last GC before OOM: 0
[M]              induced compacting GC: 0
[W]     fragmented gen0 (ephemeral GC): 3
[W]    high memory load (ephemeral GC): 0
[M]          high memory load and frag: 0
[M]     very high memory load and frag: 0
[M]                         no gc mode: 0

Expansion mechanisms
    reused seg with normal fit: 0
      reused seg with best fit: 0
          expand promoting eph: 0
         expand with a new seg: 0
       no memory for a new seg: 0
        expand in next full GC: 0

Other mechanisms enabled
     using mark list: 194
            demotion: 4
```

### Reproduction Steps

It's hard to produce this issue

### Expected behavior

Will not throw the OutOfMemoryException

### Actual behavior

Our service throw OutOfMemoryException currently

### Configuration

.NET 6.0.10
Docker Base Image: mcr.microsoft.com/dotnet/aspnet:6.0-bullseye-slim-amd64
memory limit: 1.75Gi
run in Azure Kubernetes Services
the dump file: https://seismic-my.sharepoint.com/:u:/p/allanma/EVukCFm0za1Ijc2lyAvWiCwBSxQsFBwu9wgDRmoVh-o2pg?e=jaViN5

### Other information

Seems the fragmentation on Large Object Heap is high, but I'm not sure the reason, our service is normal in .NET Core 3.1

**Comment by mangod9** [comment]
thanks for reporting the issue. We will look at the dump. If possible a couple more dumps would be helpful to understand what might be going on. Also it appears that the issue is intermittent and takes a few hours to repro?

**Comment by allan-ma** [comment]
After redeploy the service, it will take a long time(>24 hours) to reproduce this issue

This dump aslo report OutOfMemoryException
https://seismic-my.sharepoint.com/:u:/p/allanma/EXR_p8OTuDZHtOFWxgXC4EYBxTVYhXmqz56q0MjO9kwdRg?e=7aSrg2
```
> analyzeoom
Managed OOM occurred after GC #2420 (Requested to allocate 4194360 bytes)
Reason: Didn't have enough memory to allocate an LOH segment
```

This dump didn't throw any exception when I upload a ~300MB file
https://seismic-my.sharepoint.com/:u:/p/allanma/ERyptfLjrkhGq6wlKdaHtsUB-8_2BhdbbVRBEQhM3Y3Xqg?e=pho1fc

**Comment by allan-ma** [comment]
@mangod9 did you find anything useful

**Comment by Maoni0** [comment]
I just took a look at this dump 
https://seismic-my.sharepoint.com/:u:/p/allanma/EXR_p8OTuDZHtOFWxgXC4EYBxTVYhXmqz56q0MjO9kwdRg?e=7aSrg2
your hard limit is not 1.75GiB. it's 537MiB -

```
0:000> dt libcoreclr!WKS::gc_heap::heap_hard_limit
=00007f8a`670db518 WKS::gc_heap::heap_hard_limit : 0x21999999
0:000> ? 0x21999999
Evaluate expression: 563714457 = 00000000`21999999
```
and your heap is already ~500mb 
```
0:000> !eeheap -gc
Number of GC Heaps: 1
generation 0 starts at 0x00007F8899407838
generation 1 starts at 0x00007F88993FF6D0
generation 2 starts at 0x00007F8897FFF000
ephemeral segment allocation context: none
         segment             begin         allocated         committed    allocated size    committed size
00007F8897FFE000  00007F8897FFF000  00007F8899695D30  00007F889A8A1000  0x1696d30(23686448)  0x28a2000(42606592)
Large object heap starts at 0x00007F88D7FFF000
         segment             begin         allocated         committed    allocated size    committed size
00007F88D7FFE000  00007F88D7FFF000  00007F88F3CA5D90  00007F88F3CA6000  0x1bca6d90(466251152)  0x1bca7000(466251776)
Pinned object heap starts at 0x00007F8957FFF000
00007F8957FFE000  00007F8957FFF000  00007F89585A1B78  00007F89585B0000  0x5a2b78(5909368)  0x5b1000(5967872)
Total Allocated Size:              Size: 0x1d8e0638 (495846968) bytes.
Total Committed Size:              Size: 0x1eafa000 (514826240) bytes.
```
so it's understandable why it's getting OOM.

I can see that the total physical memory is indeed about 1.75GiB. so something config-ed the memory limit of this process which made GC read the hard limit as 537MiB, either by setting the env var directly, or by some config in cgroups. @janvorli, do you know how this might happen?

**Comment by Maoni0** [comment]
or someone could have set the hard limit percentage config (GCHeapHardLimitPercent) to exactly 40% -
```
0:000> dt libcoreclr!WKS::gc_heap::total_physical_mem
=00007f8a`670db508 WKS::gc_heap::total_physical_mem : 0x70000000
```
563714457 / 1879048192 = 39.9999%.

**Comment by janvorli** [comment]
Looking at that dump, I can see the GCHeapHardLimitPercent was set to 30:
```
0:000> dt libcoreclr!GCConfig::s_GCHeapHardLimitPercent
=00007f8a`670d3178 GCConfig::s_GCHeapHardLimitPercent : 0n30
```
There don't seem to be any other GC config settings set.

**Comment by allan-ma** [comment]
Below is our docker file(I remove all the sensitive information), and I also check the kube file, didn't find any GCHeapHardLimitPercent OR GCHeapHardLimit or other related ENV

```
# Starting from MS's dotnet image that has all the SDKs installed,
# build and unit test the app
FROM mcr.microsoft.com/dotnet/sdk:6.0-bullseye-slim-amd64 AS build

# Restore dependencies
RUN mkdir -p /app
WORKDIR /app/

COPY src/XX.XXX.XXX/*.csproj ./XXX.XXX/XXX.XXX.XXX/
COPY src/NuGet.Config ./XXX.XXX/
COPY src/XXX.XXX.sln ./XXX.XXX/
.... other copy

WORKDIR /app/XXX.XXX
RUN dotnet restore XXXX/XXX.csproj --configfile NuGet.Config

# Build app
WORKDIR /app/
COPY src ./XXX.XXX
WORKDIR /app/XXX.XXX
RUN dotnet publish XXX.XXX.sln -c Release -o out

EXPOSE 80
# EXPOSE 443

# TODO Unit test

# Build the deployment container. Switch base images from 'sdk' to
# 'runtime'
FROM mcr.microsoft.com/dotnet/aspnet:6.0-bullseye-slim-amd64 AS runtime

ENV CORECLR_ENABLE_PROFILING=1 \
    CORECLR_PROFILER={36032161-FFC0-4B61-B559-F6C5D41BAE5A} \
    CORECLR_NEWRELIC_HOME=/usr/local/newrelic-netcore20-agent \
    CORECLR_PROFILER_PATH=/usr/local/newrelic-netcore20-agent/libNewRelicProfiler.so \
    NEW_RELIC_LICENSE_KEY=FIXME \
    NEW_RELIC_APP_NAME=XXX

RUN apt-get update && \
    apt-get install -y wget && \
    apt-get install -y libgdiplus && \
    wget https://download.newrelic.com/dot_net_agent/previous_releases/10.3.0/newrelic-dotnet-agent_10.3.0_arm64.deb -O  /tmp/newrelic-netcore20-agent_8.29.0.0_amd64.deb && \
    apt-get install -y /tmp/newrelic-netcore20-agent_8.29.0.0_amd64.deb && \
    apt-get purge -qy wget && \
    rm -rf /var/cache/apt/* 

# Copy New Relic Instrumentation xml
COPY --from=build /app/XXX/instrumentation.xml /usr/local/newrelic-netcore20-agent/extensions/

# Copy New Relic newrelic.config
COPY --from=build /app/XXX/newrelic.config /usr/local/newrelic-netcore20-agent/

# copy the compiled app from the 'build' stage
WORKDIR /app
COPY --from=build /app/XXX.XXX/out ./

ENTRYPOINT ["dotnet", "XXX.XXX.XXX.dll"]
```

**Comment by janvorli** [comment]
Besides the env vars, it can also be set as `System.GC.HeapHardLimitPercent` in the runtimeconfig.json file.

**Comment by allan-ma** [comment]
After run kubectl describe on my pod, there is an env: DOTNET_GCHeapHardLimitPercent: 0x1E, I'm not sure why, but it's not related to the .NET runtime, so close this issue

**Comment by allan-ma** [comment]
It seems that this issue related to the configuration in the below
```
<ServerGarbageCollection>false</ServerGarbageCollection>
```

After I remove this config and redeploy, there is no DOTNET_GCHeapHardLimitPercent env anymore.
Event I add back this configuration and redeploy again, there is also no DOTNET_GCHeapHardLimitPercent env.
