### ISSUE TITLE
[API Proposal]: Add Length and IsEmpty properties to System.BinaryData

### ISSUE THREAD

**Issue by 0xced** [dotnet/runtime#77970]
### Background and motivation

Getting the length of a `System.BinaryData` instance is something quite natural. Currently, the best way to get the length is by doing `data.ToMemory().Length` which is not very pleasant.

There's also a trap where one could do `data.ToArray().Length` or even  `data.ToStream().Length` and this would allocate!

Having a `Length` property solves both issues: code is more readable and ensures no allocation.

An `IsEmpty` property would also be welcome.

### API Proposal

```csharp
namespace System;

public class BinaryData
{
    public int Length { get; }
    public bool IsEmpty { get; }
}
```

### API Usage

```csharp
void ProcessData(BinaryData data, string outputFile)
{
    if (data.IsEmpty)
    {
        Console.WriteLine($"No data available to write to {outputFile}");
    }
    else
    {
        Console.WriteLine($"Writing {data.Length} bytes to {outputFile}");
        // ... actual implementation ...
    }
}
```

### Risks

There are no risks associated with this proposition. The implementations of those properties are trivial and would just call respectively `_bytes.Length` and `_bytes.IsEmpty`.

**Comment by 0xced** [comment]
Is there anything I should add to the proposal to initiate a discussion? Some months later I have worked with `BinaryData` again and struggled with this exact same issue again.

Ping @jeffhandley

**Comment by adamsitnik** [comment]
> Is there anything I should add to the proposal to initiate a discussion? S

Apologies for the delay. The proposal looks good to me, I've marked it as ready for review. Looking at https://apireview.net/backlog I estimate that it should get reviewed within next two weeks.

@0xced thank you!

**Comment by bartonjs** [comment]
Looks good as proposed.

We briefly discussed `Length` vs `Count`, and feel that `Length` is more appropriate here because it's representing a fixed size window of data, like Span/Memory/Array, vs a point-in-time number like List and the other collections.

```C#
namespace System;

public class BinaryData
{
    public int Length { get; }
    public bool IsEmpty { get; }
}
```

**Comment by 0xced** [comment]
A pull request addressing this issue is ready: #86721
