### ISSUE TITLE
Implementations of Double.ExpM1, Double.LogP1 & co are not correct for arguments close to 0

### ISSUE THREAD

**Issue by thomashilke** [dotnet/runtime#77979]
In addition to the usual elementary trigonometric and exponential functions, some languages offer special implementations which give better (and close to optimal) guarantees in term of precision around some critical parameter values. Typical examples are Log1p and Expm1, which are mathematically defined as:
 - $\mathrm{Expm1}(x) = \exp(x) - 1$,
 - $\mathrm{Log1p}(x) = \log(1 + x)$.
 
The purpose of `Log1p` is to evaluate the logarithm around 1, where $|x - 1| < \frac{1}{2}$ can be significantly smaller than the machine epsilon. Trying to naively evaluate `Math.Log(x + 1.0)` will inevitably lead to a [catastrophic cancellation](https://en.wikipedia.org/wiki/Catastrophic_cancellation) and loose all the bits of `x` which correspond to an absolute magnitude below or equal to `2^{-53}`. In the worst case, when $|x| < 10^{16}$, all the bits are lost when evaluating `1.0 + x`, and the relative error of the result returned by `Math.Log(1.0 + x)` is 100%.

Typical implementations of these functions rely on the usual `Exp` or `Log` implementation when `x > 0.5`, and on a ad-hoc implementation of the smaller values. Examples of implementations can be found in Boost:
- https://github.com/boostorg/math/blob/cb326912f508b8824ae7bfa65785f48d4fd5b5b0/include/boost/math/special_functions/expm1.hpp#L140
- https://github.com/boostorg/math/blob/cb326912f508b8824ae7bfa65785f48d4fd5b5b0/include/boost/math/special_functions/log1p.hpp#L113

and Visual Studio C++ also provide their implementation apparently, at least according to their documentation:
- https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/log1p-log1pf-log1pl2?view=msvc-170
- https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/expm1-expm1f-expm1l?view=msvc-170

They specifically mention that the precision is better when `x` is close to zero.

However, the current implementation of these function in `dotnet` naively call `Math.Exp(x) -1` and `Math.Log(x + 1)` as can be seen here:
- https://github.com/dotnet/runtime/blob/bfa4812aec806f09f1e2927939ba98118e5e5bf7/src/libraries/System.Private.CoreLib/src/System/Double.cs#L887
- https://github.com/dotnet/runtime/blob/bfa4812aec806f09f1e2927939ba98118e5e5bf7/src/libraries/System.Private.CoreLib/src/System/Double.cs#L623

This is at best useless, and at worse very misleading, as someone reaching for these functions will expect a very specific behavior around $x = 0$. These two functions are not the only one affected by the issue.

I also note that the naming of `LogP1` does now follow what is done in Visual C++ or Boost, which is confusing. The same happened with the nomenclature of `double.Epsilon`, which is, to my knowledge, universally defined as either `2^{-53}` or half that, except in `dotnet` where it is defined as `4.94065645841247E-324`. It would be great if `dotnet` could follow more closely what have been done in other languages, which are more referential at least in the numerical analysis domain, instead of reinventing new nomenclature that will make thing more confusing than necessary.

Anyway, I am really excited to see all this stuff coming to future version of `dotnet`! Keepup!

**Comment by tannergooding** [comment]
This is by design. While it would be desirable to expose correctly implementation functions in all scenarios, that is not feasible and we only guarantee that `LogP1`, `ExpM1`, and friends are at least equivalent to `Log(x + 1)` and `Exp(x) - 1`, respectively.

These functions may provide additional precision near zero for some scenarios, but it is ultimately dependent on the type and version of the library.

You can expect these to be updated to the AOCL LibM implementation sometime in .NET 8: https://github.com/amd/aocl-libm-ose/
