### ISSUE TITLE
[jitstress-random] Assertion failed '((lclNode->gtFlags & GTF_VAR_DEF) != 0) && (((lclNode->gtFlags & GTF_VAR_USEASG) != 0) == !isFullDef)'

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#77975]
Work item: https://dev.azure.com/dnceng-public/public/_build/results?buildId=74688&view=ms.vss-test-web.build-test-results-tab&runId=1538224&resultId=111112&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab
Console log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-143516ec64f649fb86/Methodical_others/1/console.20e9f117.log?helixlogtype=result

```scala
Assert failure(PID 14948 [0x00003a64], Thread: 14948 [0x3a64]): Assertion failed '((lclNode->gtFlags & GTF_VAR_DEF) != 0) && (((lclNode->gtFlags & GTF_VAR_USEASG) != 0) == !isFullDef)' in 'ILGEN_0x537f7b0:Method_0x323f83b5(double,byte,uint,short,ubyte,double,short,ushort,double,long,int,long,ushort,long,uint):float' during 'SSA: insert phis' (IL size 1860; hash 0xc5397ee1; FullOpts)

    File: /__w/1/s/src/coreclr/jit/ssabuilder.cpp Line: 758
    Image: /datadisks/disk1/work/A602097A/p/corerun
```

**Comment by jakobbotsch** [comment]
This assert was added in #76139 it looks like, cc @SingleAccretion

**Comment by SingleAccretion** [comment]
Yeah, I looked briefly at the dump, this is a case where the we introduce a shadow local of an actual type to substitute a small one and don't update the `USEASG` flag.

Should be straightforward enough to fix.
