### ISSUE TITLE
NRE in System.Diagnostics.Tracing.EventPipePayloadDecoder if Threading event keywords are enabled.

### ISSUE THREAD

**Issue by pengweiqhca** [dotnet/runtime#78006]
### Description

Like #65630, but I only have `Threading`.

### Reproduction Steps

Like #65630

### Expected behavior

Like #65630

### Actual behavior

Like #65630

### Regression?

Downgrade to net6.0.

### Configuration

.NET 7 RC2, Windows 11 x64

**Comment by tommcdon** [comment]
@davmason

**Comment by tommcdon** [comment]
Fixed via #85563
