### ISSUE TITLE
.NET 6 trimmed mode fails if the app uses obsolete code

### ISSUE THREAD

**Issue by alex-jitbit** [dotnet/runtime#78014]
### Description

If the application uses "obsolete" code (like has a class that inherits from `WebClient` for example, which is deprecated) it somehow references `System.ComponentModel` and trimmed publish throws error during runtime

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.ComponentModel.EventBasedAsync
```

This has been reported previously #63290

### Reproduction Steps

1. Create a console .NET app.
2. Use obsolete class `WebClient` in your code.
3. Publish the app "trimmed", doesn't matter `<TrimMode>link</TrimMode>` or `<TrimMode>copyused</TrimMode>`
4. Run the app
5. Enjoy the crash

### Expected behavior

Should run fine *like it did in .NET5!*

### Actual behavior

Crash

### Regression?

Worked fine in .NET 5

### Known Workarounds

Remove obsolete classes usage

**Comment by jkotas** [comment]
Did you see any trimming warnings when publishing the application? They should give you clues in where the problems are. We do not guarantee that the apps work after trimming if there are trimming warnings.

The reproduction steps are insufficient. I have tried that with a simple `WebClient` 
```csharp
using (WebClient client = new WebClient())
{
    client.DownloadData("https://www.bing.com/");
}
```
It works just fine when published trimmed.
