### ISSUE TITLE
adding a base record for exception

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#78024]
I suggest adding a base record for exception
Similar to this https://github.com/Mr0N/CustomExceptionRecords

**Comment by antomys** [comment]
Well, it doesn't make sense. Frankly speaking, you reinvented `System.Exception` class.

**Comment by Mr0N** [comment]
> Well, it doesn't make sense. Frankly speaking, you reinvented `System.Exception` class.

for record

**Comment by antomys** [comment]
Could you define, what is a major difference between `record` and `class`?

**Comment by stephentoub** [comment]
It sounds like what you're really asking for is the ability to declare a record that derives from Exception.  That's an issue for dotnet/csharplang, the ability to derive a record from a non-record.

**Comment by Mr0N** [comment]
> It sounds like what you're really asking for is the ability to declare a record that derives from Exception. That's an issue for dotnet/csharplang, the ability to derive a record from a non-record.

This is not a runtime problem, because I implemented it without changing the programming language.

**Comment by stephentoub** [comment]
> This is a runtime problem, because I implemented it without changing the programming language.

RecordException would need to derive from Exception. And if that were possible, you wouldn't need RecordException at all, as any record could derive from Exception directly.

"record" is a construct of the C# language. Augmenting it's design and capabilities are the domain of the C# language.

**Comment by antomys** [comment]
> It sounds like what you're really asking for is the ability to declare a record that derives from an Exception. That's an issue for `dotnet/csharplang`, the ability to derive a record from a non-record.

Oh, I see. Thanks for elaborating. So the main suggestion of this issue shortens to "Add ability to inherit a record from a non-record (here in issue: record from class)).  So, as I see it, this issue is not an issue, but a suggestion. Not sure that it's going to be useful, but anyway

**Comment by Mr0N** [comment]
> > This is a runtime problem, because I implemented it without changing the programming language.
> 
> RecordException would need to derive from Exception. And if that were possible, you wouldn't need RecordException at all, as any record could derive from Exception directly.
> 
> "record" is a construct of the C# language. Augmenting its design and capabilities are the domain of the C# language.



> > This is a runtime problem, because I implemented it without changing the programming language.
> 
> RecordException would need to derive from Exception. And if that were possible, you wouldn't need RecordException at all, as any record could derive from Exception directly.
> 
> "record" is a construct of the C# language. Augmenting its design and capabilities are the domain of the C# language.

Well,  change the logic of work "throw" and make a basic type for excluding records

**Comment by Mr0N** [comment]
![image](https://user-images.githubusercontent.com/61237140/200594658-c297e1a9-061a-4a2c-bcfc-4e26e9d86655.png)

**Comment by Mr0N** [comment]
> > It sounds like what you're really asking for is the ability to declare a record that derives from an Exception. That's an issue for `dotnet/csharplang`, the ability to derive a record from a non-record.
> 
> Oh, I see. Thanks for elaborating. So the main suggestion of this issue shortens to "Add ability to inherit a record from a non-record (here in issue: record from class)). So, as I see it, this issue is not an issue, but a suggestion. Not sure that it's going to be useful, but anyway

Yes, I do it at the level of il code, but in my example it will not be possible to do this in C# code.

**Comment by Mr0N** [comment]
> Reference

So my library changes the programming language :)
