### ISSUE TITLE
[jitstress] Assertion failed 'isContainable || supportsRegOptional' in 'JIT.HardwareIntrinsics.General.Program:AbsDouble()' during 'Generate code'

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#78023]
```
:\h\w\BD5F09D0\w\B7CA09CB\e>type C:\h\w\BD5F09D0\w\B7CA09CB\u\SetStressModes_jitstress2.cmd 
set DOTNET_TieredCompilation=0
set DOTNET_JitStress=2

  Starting:    JIT.HardwareIntrinsics.XUnitWrapper (parallel test collections = on, max threads = 4)
    JIT\HardwareIntrinsics\General\Vector128\Vector128_ro\Vector128_ro.cmd [FAIL]
      
      Assert failure(PID 964 [0x000003c4], Thread: 540 [0x021c]): Assertion failed 'isContainable || supportsRegOptional' in 'JIT.HardwareIntrinsics.General.Program:AbsDouble()' during 'Generate code' (IL size 74; hash 0xa20af912; FullOpts)
      
          File: D:\a\_work\1\s\src\coreclr\jit\hwintrinsiccodegenxarch.cpp Line: 61
          Image: C:\h\w\BD5F09D0\p\corerun.exe
```

Work item: https://dev.azure.com/dnceng-public/public/_build/results?buildId=76043&view=ms.vss-test-web.build-test-results-tab&runId=1574484&resultId=102263&paneView=debug
Console log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-76793-merge-bb14f9f0b05e4fd1ab/JIT.HardwareIntrinsics.General.Vector128/1/console.03aa098f.log?helixlogtype=result

cc @dotnet/jit-contrib @tannergooding

**Comment by JulieLeeMSFT** [comment]
@tannergooding, PTAL this blocking CI issue.

**Comment by tannergooding** [comment]
Not able to reproduce this currently.

**Comment by tannergooding** [comment]
Ah yeah. I see that now. Got confused because the machine is `windows.10.amd64.open`
