### ISSUE TITLE
Assembly resolution algorithm difference between .NET 6 and .NET 4.8

### ISSUE THREAD

**Issue by wilyoctopus** [dotnet/runtime#78037]
I have a `.NET Standard 2.0` assembly `lib.dll` which has `AssemblyVersion` of `1.2.0.1` (not strongly-named, i.e. without pub key and digital signature).
I also have a `.NET 4.8` and `.NET 6` console apps that reference and use this library.

Now, if I bluntly substitute this `lib.dll` with the `lib.dll` of a different version `1.0.0.0` (content is the same for both) in the folder from where it is picked up, then I observe a different behavior for `.NET 4.8` and `.NET 6` when trying to run the app:

.NET 4.8, `1.2.0.1` lib.dll is referenced, `1.0.0.0` is in the binaries: application executes without errors
.NET 4.8, `1.2.0.1` lib.dll is referenced, `1.2.0.1` is in the binaries: application executes without errors
.NET 4.8, `1.2.0.1` lib.dll is referenced, `1.2.0.5` is in the binaries: application executes without errors

.NET 6, `1.2.0.1` lib.dll is referenced, `1.0.0.0` is in the binaries: System.IO.FileNotFoundException: Could not load file or assembly 'lib, Version=1.2.0.1, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
.NET 6, `1.2.0.1` lib.dll is referenced, `1.2.0.1` is in the binaries: application executes without errors
.NET 6, `1.2.0.1` lib.dll is referenced, `1.2.0.5` is in the binaries: application executes without errors

Is there a page somewhere where I could read more about this change?
Is there something I could do to make `.NET 6` behavior similar to `.NET 4.8`?

**Comment by teo-tsirpanis** [comment]
@agocke, @vitek-karas, @VSadov

**Comment by vitek-karas** [comment]
In .NET Core/.NET 6+ the runtime will not allow loading assembly of a lower version than the requested version. And there are no workaround for that - this is a core behavior of the runtime.
It will allow using higher version to resolve the reference.

The only solution is to compile the app using the lowest version as the reference.

**Comment by wilyoctopus** [comment]
@vitek-karas, thank you!
