### ISSUE TITLE
[API Proposal]: Can exception not collect StackTrace?

### ISSUE THREAD

**Issue by zhouandke** [dotnet/runtime#78031]
### Background and motivation

In my asp.net core project, I throw exception to return bussiness error information, but runtime cost too much time to collect StackTrace.
Can we give exception a property like "NotCollectStack" to tell runtime not collect StackTrace?

### API Proposal

```csharp
throw new BussinessException() { NotCollectStack = false };
```

### API Usage

```csharp
throw new BussinessException() { NotCollectStack = false };
```

### Alternative Designs

Or like SuppressableStacktraceException in java

**Comment by gfoidl** [comment]
> throw exception to return bussiness error information

Why not return that "business error information" as normal object, i.e. not as Exception?

**Comment by jkotas** [comment]
> runtime cost too much time to collect StackTrace.

Do you have any data to support this?

**Comment by zhouandke** [comment]
> > throw exception to return bussiness error information
> 
> Why not return that "business error information" as normal object, i.e. not as Exception?

I used to use Result<T> as return type
```
    public class Result<T>
    {
        public int Code { get; set; }
        public T Data { get; set; }
        public string Message { get; set; }
    }
```
Every time I need to determine whether result.code is equal to 0, I think it's tedious.
Now In asp.net core, I throw the business exception directly,  then use middleware to catch the business exception, then return bussiness error to user.
This can reduce a lot of code.

**Comment by zhouandke** [comment]
> > runtime cost too much time to collect StackTrace.
> 
> Do you have any data to support this?

Thank you.
I used to test in Debug mode, stack trace has a big impact.
In Release mode, stack trace has a little impact in asp.net core 3.1.

I use exception to return bussiness error, is there any method to reduce exception cost?

RecursionCall 1 time with exception: 3346
RecursionCall 500 time with exception: 3343
RecursionCall 500 time: 0


```
        static void Main(string[] args)
        {
            var count = 100000;
            var sw = new System.Diagnostics.Stopwatch();
            sw.Start();
            for (int i = 0; i < count; i++)
            {
                try
                {
                    SomeMethodWithException(1);
                }
                catch { }
            }
            sw.Stop();
            Console.WriteLine("RecursionCall 1 time with exception: " + sw.ElapsedMilliseconds);

            sw.Restart();
            for (int i = 0; i < count; i++)
            {
                try
                {
                    SomeMethodWithException(500);
                }
                catch { }
            }
            sw.Stop();
            Console.WriteLine("RecursionCall 500 time with exception: " + sw.ElapsedMilliseconds);

            sw.Restart();
            for (int i = 0; i < count; i++)
            {
                try
                {
                    SomeMethod(500);
                }
                catch { }
            }
            sw.Stop();
            Console.WriteLine("RecursionCall 500 time: " + sw.ElapsedMilliseconds);
            Console.ReadLine();
        }

        private static void SomeMethodWithException(int n)
        {
            if (n <= 0)
            {
                throw new Exception();
            }
            SomeMethodWithException(n - 1);
        }

        private static string SomeMethod(int n)
        {
            if (n <= 0)
            {
                return SomeMethod(n - 1);

            }
            return "Error";
        }
```

**Comment by jkotas** [comment]
Note that methods like `SomeMethodWithException` in your example can be optimized by the JIT into a loop, so your test may not be actually measuring the deep recursive stacks that it is meant to measure.

Your benchmarks are not calling the `Exception.StackTrace` property that I thought your concern is about. If you called `Exception.StackTrace` as part of your test, it would get even slower. However, you are in full control on whether or not to call `Exception.StackTrace` already.

 The exception handling has to walk the stack to find the catch handler. It is not possible to skip the stack walking as part of the exception handling.

Exceptions in .NET are expensive, and it is a not a good idea to use them for control flow.
