### ISSUE TITLE
net7.0 `System.Text.Json.Utf8JsonWriter#WriteBase64String` requires `RefStructs` compiler feature VB.NET

### ISSUE THREAD

**Issue by campersau** [dotnet/runtime#78065]
### Description

With `net6.0` calling `System.Text.Json.Utf8JsonWriter#WriteBase64String("test", New Byte() {1, 2, 3})` worked in VB.NET but after upgrading to `net7.0` this now throws a compiler error:
```
error BC36954: Fehler bei der Überladungsauflösung, da keine zugreifbare "WriteBase64String" aufgerufen werden kann
```
The info window has more information:
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/4009570/200670570-1a6519e5-5849-41e0-a15d-1d4bd28a7fac.png">
```
"ReadOnlySpan(Of Byte)" requires the compiler function "RefStructs" which isn't supported by this version of the Visual Basic Compiler.
```

Why isn't this supported anymore? It worked fine with `net6.0`.

### Reproduction Steps

```vb
Imports System.IO
Imports System.Text
Imports System.Text.Json

Module Program
    Sub Main(args As String())
        Dim memoryStream As New MemoryStream()
        Using jsonWriter As New Utf8JsonWriter(memoryStream)
            jsonWriter.WriteStartObject()
            jsonWriter.WriteBase64String("test", New Byte() {1, 2, 3})
            jsonWriter.WriteEndObject()
        End Using
        Console.WriteLine(Encoding.UTF8.GetString(memoryStream.ToArray()))
    End Sub
End Module
```

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>ConsoleApp13</RootNamespace>
    <TargetFrameworks>net6.0;net7.0</TargetFrameworks>
    <OptionStrict>On</OptionStrict>
  </PropertyGroup>
</Project>
```

### Expected behavior

It should work/compile as before with `net6.0`.

### Actual behavior

It does not compile with `net7.0`.

### Regression?

Yes, it worked with `net6.0`.

### Known Workarounds

```vb
jsonWriter.WriteString("test", Convert.ToBase64String(New Byte() {1, 2, 3}))
```

**Comment by teo-tsirpanis** [comment]
The byte array you wrote gets implicitly converted to a `ReadOnlySpan<byte>` which is a ref struct and not supported in Visual Basic. If it were supported before it was by mistake.

**Comment by teo-tsirpanis** [comment]
For the latter case you can use `RandomNumberGenerator.Create().GetBytes(arr)`. `Create()` returns a cached instance.

**Comment by campersau** [comment]
Closing as it appears to be by design and looked like a mistake in `net6.0` even though it worked fine for us.
