### ISSUE TITLE
Implement T.MinValue and T.MaxValue for INumber<T> area-System.Numerics 

### ISSUE THREAD

**Issue by Aniobodo** [dotnet/runtime#78061]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Please add T.MinValue and T.MaxValue for INumber<T>.
For example, int should return -2147483648 and 2147483647 respectively.

**Comment by Aniobodo** [comment]
area-System.Numerics

**Comment by vcsjones** [comment]
There is a separate interface for this called [`IMinMaxValue<TSelf>`](https://learn.microsoft.com/en-us/dotnet/api/system.numerics.iminmaxvalue-1?view=net-7.0) that has a `MinValue` and `MaxValue` property.

**Comment by Aniobodo** [comment]
Thank you!
