### ISSUE TITLE
.net 7 cycles  Performance slow

### ISSUE THREAD

**Issue by quan0zhou** [dotnet/runtime#78089]
### Description
![image](https://user-images.githubusercontent.com/27860834/200751549-246aa425-e4a9-47a1-a60b-dbe45d07d023.png)
```c#
    public class BenchmarkSum
    {
        private JsonObject[] _jsonObjs;


        [GlobalSetup]
        public void Setup()
        {
            _jsonObjs = new JsonObject[100000];
        }

        [Benchmark]
        public void Sum()
        {
            for (int i = 0; i < 100000; i++)
            {
                _jsonObjs[i] = new JsonObject()
                {
                    ["aaa"] = 1,
                    ["bbbb"] = 2,
                    ["cccc"] = new JsonArray()
                    {
                        new JsonObject()
                        {
                            ["aaaa"] = "aaaaa",
                            ["ffffff"] = "ffffffffffffff"
                        }
                    }
                };
            }
        }
    }
```

**Comment by stephentoub** [comment]
@eiriktsarpalis, @krwq, here's an allocation trace with the repro but for only 1,000 iterations instead of 100,000 iterations.  On the left is .NET 6, on the right is .NET 7:
<img width="794" alt="image" src="https://user-images.githubusercontent.com/2642209/200905452-c805f5c0-a91f-4299-b0bc-83d078951c4a.png">
That's a lot of additional allocation.  Is this expected?

**Comment by eiriktsarpalis** [comment]
Superficially, this appears to only be creating DOM instances without performing any serializations, so I'm surprised that any `JsonSerializerOptions` instance are materialized. Would need to take a closer look.

**Comment by stephentoub** [comment]
@eiriktsarpalis, I assume the intent was for this to be static?!
https://github.com/dotnet/runtime/blob/a5f3676cc71e176084f0f7f1f6beeecd86fbeafc/src/libraries/System.Text.Json/src/System/Text/Json/Nodes/JsonNode.To.cs#L9
