### ISSUE TITLE
QuicListener AcceptConnectionAsync and OperationCanceledException

### ISSUE THREAD

**Issue by pepone** [dotnet/runtime#78096]
The QuicListener can throw  `OperationCanceledException` when the internal TLS handshake timeout expires, this is unexpected and not documented behavior.

See https://github.com/dotnet/runtime/blob/136657403c045ab99e0cb18ef2a39e0179e6b434/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicListener.PendingConnection.cs#L58

It would be better to wrap the OperationCanceled exception from the internal timeout in a QuicException with the ConnectionTimeout error code

You should consider fixing this along #75184

**Comment by ManickaP** [comment]
Triage: we should fix this, seems easy enough and should be addressed in 8.0.

**Comment by rzikm** [comment]
@ManickaP I see in the code that this scenario should throw `QuicException` with `QuicError.ConnectionTimeout`. I think we can close this issue now.

**Comment by ManickaP** [comment]
Depends where we decide to go with the exceptions. I left this open on purpose so we can discuss this.

In some cases, it looks we're deciding to go the way of different exception types, e.g. throwing `SocketException` for IP related errors. But here we're doing `QuicException` for a timeout. So I think that the exception type here is still something we should include in the whole "exception discussion".

**Comment by karelz** [comment]
@wfurt this should also be addressed by your exception changes, shouldn't it?

**Comment by ManickaP** [comment]
We're throwing `QuicException` with `QuicError.ConnectionTimeout` as Radek wrote in https://github.com/dotnet/runtime/issues/78096#issuecomment-1567195933

I'm calling this done.
