### ISSUE TITLE
System.Text.Json throws ArgumentNullException and not JsonException when deserializing with missing required property if exception resources are stripped

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#78099]
### Description

We're currently working on migrating all our JSON serialization from Newtonsoft.Json to System.Text.Json in the Microsoft Store (see also #77897, #78029), and we just hit another issue with trimming enabled that we think might be an actual bug in System.Text.Json. The issue is: whenever system resources are stripped (which is the default for us), trying to deserialize a JSON object that's missing a `[JsonRequired]` property causes the API to throw an `ArgumentNullException` instead of a `JsonException`. This of course then breaks callers that were only expecting a `JsonException`.

The issue is that the throw helper path in System.Text.Json doesn't take into account the fact that a resource might be missing or stripped away (in fact it's just ignoring a `null` warning), and then just passes it to `string.Format`, which then throws an `ArgumentNullException`). The code should likely just check if the retrieved resource is `null` (especially because the code retrieving it specifically does handle `MissingManifestResourceException`-s and returns `null` if that's the case), and simply format some fallback message if so. No changes for the normal case, and correct behavior in all other cases as well, win win 😄

### Reproduction Steps

Try to deserialize the following after having stripped exception message resources from corelib:

```csharp
_ = JsonSerializer.Deserialize("{}", MyJsonContext.Default.MyModel);

[JsonSerializable(typeof(MyModel))]
public partial class MyJsonContext : JsonSerializerContext
{
}

public class MyModel
{
    [JsonRequired]
    public string Name { get; set; }
}
```

### Expected behavior

This should throw a `JsonException`, as the `Name` property is missing.

### Actual behavior

This throws an `ArgumentNullException`.

Specifically, first a `MissingManifestResourceException` is thrown here:

![image](https://user-images.githubusercontent.com/10199417/200805661-2c8d2d22-a74d-4253-be23-c886f37e200f.png)

That'd be here:

https://github.com/dotnet/runtime/blob/264d7391ec9f6e698051db0621c5e090d0ae4710/src/libraries/System.Text.Json/src/System/Text/Json/ThrowHelper.Serialization.cs#L253

Which then tries to load the resource here:

https://github.com/dotnet/runtime/blob/264d7391ec9f6e698051db0621c5e090d0ae4710/src/libraries/Common/src/System/SR.cs#L26-L35

Now, this is handled already, great. The issue is that System.Text.Json then just suppresses the warning and calls `string.Format`:

![image](https://user-images.githubusercontent.com/10199417/200805707-4cb79170-7022-4830-acb9-852ea6b8f7f0.png)

Which finally throws the `ArgumentNullException` (understandably) here:

https://github.com/dotnet/runtime/blob/264d7391ec9f6e698051db0621c5e090d0ae4710/src/libraries/Common/src/System/SR.cs#L54

### Known Workarounds

Preserve the exception message resources, which wastes binary size.

This can easily be fixed in System.Text.Json with something like:

```csharp
if (resourceFormat is null)
{
    return $"{p1}";
}
```

This can easily be added to all these various formatting methods to handle these scenarios just fine. Note: these are already all throw paths, so there should be no concerns about any performance issues with adding one extra branch here. This will just make sure that the correct exception type is always thrown no matter what.

I'm happy to contribute a fix for this 🙂

cc. @eiriktsarpalis

### Configuration

- System.Text.Json 7.0.0
- .NET Native 6.2.14

**Comment by eiriktsarpalis** [comment]
I don't believe this is an issue specific to System.Text.Json. Assuming resource strings have been stripped from the application, I would think that any fallback should be handled by the resolution logic in the shared `SR.cs` file. We could either:

1. Update the nullability annotation for the `GetResourceString` method (which would trigger warnings in almost every library location that throws)
2. Return a placeholder string such as "Manifest resource string not found" or the empty string, assuming we can somehow detect if trimming has occurred for the particular key.
3. Keep current behavior?

cc @stephentoub @MichalStrehovsky

**Comment by Sergio0694** [comment]
> "Return a placeholder string such as "Manifest resource string not found" or the empty string"

We could also just return the name of the resource itself, which would provide some info more than an empty string. I do like this idea in general though, as it'd just be a very small fix in a single location and it would indirectly fix all callers 🙂

**Comment by Sergio0694** [comment]
Essentially we can just change this line and remove the null suppression:

https://github.com/dotnet/runtime/blob/264d7391ec9f6e698051db0621c5e090d0ae4710/src/libraries/Common/src/System/SR.cs#L37

And make it just be:

```csharp
return resourceString ?? resourceKey;
```

**Comment by stephentoub** [comment]
Isn't the intent that if resources are going to be stripped, UseSystemResourceKeys would also be set such that you always take this path:
https://github.com/dotnet/runtime/blob/264d7391ec9f6e698051db0621c5e090d0ae4710/src/libraries/Common/src/System/SR.cs#L18-L23
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Runtime/tests/System/UseResourceKeysTest.cs
https://github.com/dotnet/runtime/blob/6631b47896d1111fa984c8ceef3ae7e7bb47caea/src/mono/sample/wasm/Directory.Build.props#L27
?

**Comment by Sergio0694** [comment]
.NET Native is just nuking the resources without setting that (that code likely didn't even exist in the CoreRT runtime back then). The point here would be to ensure that runtimes that are using System.Text.Json through the OOB package (such as .NET Native, where both it and the OOB package for STJ are still supported) would still do the right thing. On that note though, let me actually try if just manually setting `System.Resources.UseSystemResourceKeys` in the `AppContext` switch works. If System.Text.Json is just reading that flag normally like any other one _maybe_ that willl do the trick. Be right back 😄

**Comment by eiriktsarpalis** [comment]
I think we can close this -- `UseSystemResourceKeys` is the [documented solution](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-7-0#trimming-framework-library-features) for trimming exception messages.

**Comment by eiriktsarpalis** [comment]
Should we reopen this issue to track a potential fix?
