### ISSUE TITLE
System.Management throw System.PlatformNotSupportedException: 'System.Management currently is only supported for Windows desktop applications.'

### ISSUE THREAD

**Issue by RachelXGanon** [dotnet/runtime#78104]
### Description

I'm using a condole app in .NET 5.0 app.
This the code:
 ```
class Program
    {
        static void Main(string[] args)
        {
			ManagementObjectSearcher windowsServicesSearcher = new ManagementObjectSearcher("root\\cimv2", "select * from Win32_Service");
			ManagementObjectCollection objectCollection = windowsServicesSearcher.Get();

			Console.WriteLine("There are {0} Windows services: ", objectCollection.Count);

			foreach (ManagementObject windowsService in objectCollection)
			{
				PropertyDataCollection serviceProperties = windowsService.Properties;
				foreach (PropertyData serviceProperty in serviceProperties)
				{
					if (serviceProperty.Value != null)
					{
						Console.WriteLine("Windows service property name: {0}", serviceProperty.Name);
						Console.WriteLine("Windows service property value: {0}", serviceProperty.Value);
					}
				}
				Console.WriteLine("---------------------------------------");
			}
			Console.ReadLine();
        }
```
Running the app by clicking on Start, I'm getting an error on the line:
`			ManagementObjectSearcher windowsServicesSearcher = new ManagementObjectSearcher("root\\cimv2", "select * from Win32_Service");
`
**System.PlatformNotSupportedException: 'System.Management currently is only supported for Windows desktop applications.'**

### Reproduction Steps

- Create .NET 5.0 console app
- Copy past the code above
- Run the app
- Use windows 10

### Expected behavior

Just to work, I guess..

### Actual behavior

Throw exception `System.PlatformNotSupportedException: 'System.Management currently is only supported for Windows desktop applications.'`

### Configuration

Run on Windows 10 platform,
VS 2019
.NET 5.0

**Comment by RachelXGanon** [comment]
@vcsjones - I appreciate your quick response.
I just succeed to resolve the issue by using `System.Management version 5.0.0` I used `7.0.0 `
Can it be that it should be with a match to the project target version?
And if so, why doesn't Microsoft warn about it?
Thanks anyway, since resolved, closing the issue.

**Comment by danmoseley** [comment]
@RachelXGanon Just want to make sure you saw that 5.0 is out of support. I recommend 7.0

**Comment by danmoseley** [comment]
RachelXGanon Just want to make sure you saw that 5.0 is out of support. I recommend 7.0
