### ISSUE TITLE
Eager load assemblies in Blazor for Roslyn compilation

### ISSUE THREAD

**Issue by Liam-Rougoor** [dotnet/runtime#78101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to compile code that is submitted in Blazor within the web client itself using Roslyn. I have seen a few tutorials on compiling code in blazor, targeting older versions of .Net Core. Roslyn requires references to assemblies to compile code succesfully. In the past, because assemblies in Blazor were eagerly loaded, they and their locations could be accessed at program startup. Since the introduction of lazy loading, this was no longer possible.

### Describe the solution you'd like

Would it be possible to eager load Blazor assemblies at startup with their Location property set? Or could I load assemblies in Roslyn in Blazor otherwise? I had found closed issue dotnet/aspnetcore#26805, but it hadn't proposed a(n alternative) solution. 

### Additional context
I've been trying to implement something like this, but the Location property is empty:
```
foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
                {
                    references.Add(
                        MetadataReference.CreateFromStream(
                            await this._http.GetStreamAsync("/_framework/_bin/" + assembly.Location)));
                }
```

**Comment by pavelsavara** [comment]
I could just offer unfounded speculation:

`Location` is file system location, I think. That would be pointing to emscripten's VFS on the web, right ? 
But, we are loading DLLs into memory as blob, rather than via VFS file location.
In other words, they do not exist on "file system" in the browser.

I guess binaries could be found in the Blazor's download cache.

**Comment by Liam-Rougoor** [comment]
So, one of @javiercn's suggestions provided a pretty easy solution: just adding `.dll` to the assembly name to get it from wwwroot was sufficient to create `MetadataReference`s.
```
var assemblies = AppDomain.CurrentDomain.GetAssemblies()
            .Select(a => a.FullName.Split(",")[0] + ".dll").ToArray();

        var metadataReferences = new List<MetadataReference>();
        foreach (var reference in assemblies)
        {
            var stream = await Http.GetStreamAsync($"_framework/{reference}");
            var metadataReference = MetadataReference.CreateFromStream(stream);
            metadataReferences.Add(metadataReference);
        }
```
However, I did run into the issue where `AppDomain.CurrentDomain.GetAssemblies()` only returns loaded assemblies, so not all assemblies are returned due to lazy loading. Is there a way to get _all_ assemblies, including the ones that haven't loaded yet?

**Comment by javiercn** [comment]
@Liam-Rougoor the only reliable way to do that if you are using blazor is to fetch `blazor.boot.json` with the caveheats mentioned above and get them from there. We do not offer APIs for it (on the blazor side) and the runtime folks can't really help you since lazy loading is a Blazor feature.

IMO, for what you are building I would avoid lazy loading altogether. It is not going to reap the benefits you expect, and it is going to give you headaches like this.

**Comment by Liam-Rougoor** [comment]
@javiercn I agree that lazy loading is not beneficial for my use case. That's why I was wondering if it was possible to not use lazy loading in Blazor. 

This is indeed no longer a runtime issue. If you have any more thoughts on avoiding lazy loading in Blazor, we could move the issue back to the aspnetcore repo. If lazy loading cannot be avoided using Blazor, then I'll just apply what I can with the tips presented by you guys.

**Comment by javiercn** [comment]
@Liam-Rougoor lazy loading is not enabled by default, you need to opt-in. Just do not support it in your app/tool and call it out to your users.

**Comment by Liam-Rougoor** [comment]
@javiercn Ah, it looks like I misunderstood how retrieving assemblies and Blazor's lazy loading works. I thought that lazy loading _was_ enabled by default, but I was mistaken😅. Instead of `AppDomain.CurrentDomain.GetAssemblies()`, I can find all referenced assemblies by looping through `assembly.GetReferencedAssemblies()` calls.

Everything seems to be working for me now. Thank you all for your troubles of helping me and have a great day! If you have nothing to add, feel free to close the issue.
