### ISSUE TITLE
Docker Container: running c# on linux arm32

### ISSUE THREAD

**Issue by Chrissi-99** [dotnet/runtime#78108]
Hello,

I have a problem and I can't get any further. I have an Edge Box with Docker installed. Now I want to run a C# application on this Edge Box. The Edge Box itself does not have an Internet connection, which is why I create the Docker image locally on the PC (AMD64 architecture) and then save it as a .tar file and then import it to the Edge Box via Portainer. However, when I run this image on the Edge Box, I get the error message:

"Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly '/Name.dll'. The System cannot find the file specified.

As already mentioned, the PC has an AMD64 architecture, the Edge Box an arm32 architecture. In addition to this, the OS is a Yocto based Linux system. 
So I create the image like this:

First we publish our dotnet program over cmd:

RUN dotnet publish -c Release -o out

after that we build the image as followed:

docker build --platform=linux/arm/v7 -t imagename .

I´ve tried it as a dotnet and as a dotnet Core application.

I wrote the Dockerfile as follows:

FROM mcr.microsoft.com/dotnet/runtime:6.0.0-focal-arm32v7

COPY out/ .

ENTRYPOINT ["dotnet", "Name.dll"]

I´ve tried many Base Images there.

Is it even possible to run a C# (.net / .net Core) application on an arm32 architecture?

I used many hours for this problem and I have no more idea how to solve it. Any ideas?

Thank You!

**Comment by bjornen77** [comment]
When taking a closer at your question I see that you are starting the application with the "dotnet" command. Then it should work without specifying the runtime identifier. The runtime identifier is only needed if you want to produce a platform specific executable etc. More info can be found here:

https://learn.microsoft.com/en-us/dotnet/core/deploying/

**Comment by Chrissi-99** [comment]
Hello,


I will try to publish the application for the arm32 architecture on Wednesday, hoping that it will work then.
But if I understood your second message correctly, this isn't the solution to solve this problem? 
What else can I do that I can Run this dotnet application on the Edge Box?

Any more ideas?

Thanks you! :)

**Comment by bjornen77** [comment]
Unfortunately, I have no arm32 device to test this at the moment, sorry. But please try the first approach where you publish specifically for arm32 and see if that works (it should). Then this is a solution to your problem. However, if I understand the documentation correctly, it should not be necessary to do this when you start the application with the dotnet command and publish the application according to your example, which is strange.

**Comment by Chrissi-99** [comment]
Hello,

we used the command: dotnet publish -r linux-arm --self-contained -c Release -o out
We tried to run it after on the Edge Box and we no more getting the Error Code: could not load dll.

So this Error Code seems to be fixed with this publish method.

But from now on we get the Error Code:
Failed to create CoreCLR, HRESULT: 0x80004005

So the program is still not running on the Edge Box.
Any ideas?

**Comment by bjornen77** [comment]
Sorry, I do not know. It could be many things. What is the Edge Box you are referring to? If you run uname -r and uname -m on the Edge box, what does it say? Is the Edge Box an ARMv7(armhf) or armel system?

**Comment by Chrissi-99** [comment]
Hi,

uname -r: 4.14.78-1.1.0+g952e7fb283fb
uname -m: armv7l

So the Edge Box is an Armv7 System.

**Comment by Chrissi-99** [comment]
cat/proc/cpuinfo didn´t work.
So I used the command "lscpu". Is it the same?

Architecture: armv7l
Byte Order: Little Endian
CPU(s): 2
On-line CPU list: 0,1
Threads per core: 1
Cores per socket: 2
Sockets: 1
Vendor ID: ARM
Model: 5
Model name: Cortex-A7
Stepping: r0p5
CPU max MHz: 1200
CPU min MHz: 792
BogoMIPS: 16
Flags: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm

**Comment by bjornen77** [comment]
It is the same I think. I just want to make sure the system is an armhf one.

If you go inside the /lib folder. Do you have files like 
arm-linux-gnueabihf and ld-linux-armhf.so.3 in there?

**Comment by bjornen77** [comment]
One suggestion could be to try a later version of the runtime. I see that you in in your docker file that you are using the 6.0.0 one. The latest is 6.0.11, so change your docker file to:
FROM mcr.microsoft.com/dotnet/runtime:6.0-focal-arm32v7

or

FROM mcr.microsoft.com/dotnet/runtime:6.0.11-focal-arm32v7

**Comment by bjornen77** [comment]
Yes, I mean on the Edge Box. Then it is probably in some other location as you are running a Yocto based Linux system. It is hard to know what might causing the issue, and I do not have any system at the moment to do some testing myself.

**Comment by michaldobrodenka** [comment]
@Chrissi-99 "Is it even possible to run a C# (.net / .net Core) application on an arm32 architecture?"
Yes, linux-arm is my primary platform. Do you have net7 SDK installed? it sometimes problematic, I've seen "Failed to create CoreCLR" during net7 testing. Even if you target net6, but have net7 sdk installed - it's problematic. I compile with net6 sdk in docker.

**Comment by Chrissi-99** [comment]
No I have dotnet 6 installed. I dont have net 7 installed.
I decided to write a new program in python now and I can run the program without any problems.

It´s sad that I dont know where my mistake is, running dotnet on the container.

But thanks you for your help ! :)

**Comment by ericstj** [comment]
So to answer the original question: 
> Is it even possible to run a C# (.net / .net Core) application on an arm32 architecture?

Yes, it is possible.  You can build and run on ARM32 using the CLI there, or build either a framework-dependent or self-contained application and run there.

Here are some docs:
https://learn.microsoft.com/en-us/dotnet/core/install/linux
https://learn.microsoft.com/en-us/dotnet/core/docker/build-container

As best I can tell from what was shared above it seems like a problem in transporting the application binaries to the docker file and executing the application.
