### ISSUE TITLE
SYSLIB1045 Use GeneratedRegexAttribute replaces verbatim string with regular string

### ISSUE THREAD

**Issue by MaceWindu** [dotnet/runtime#78113]
### Description

It is quite common to use verbatim strings to declare regex as it could contain a lot of escape sequences and with regular strings it looks like back-slach circus.

Currently `SYSLIB1045` refactoring replaces verbatim strings with regular strings.

### Reproduction Steps

```cs
private static readonly Regex _regex = new(@"[`~!@#\$%\^&*\(\)_\+\-={}\|\[\]\\:"";'<>\?,\./№ ]+");
```

### Expected behavior

```cs
[GeneratedRegex(@"[`~!@#\$%\^&*\(\)_\+\-={}\|\[\]\\:"";'<>\?,\./№ ]+")]
private static partial Regex MyRegex();
```

### Actual behavior

```cs
[GeneratedRegex("[`~!@#\\$%\\^&*\\(\\)_\\+\\-={}\\|\\[\\]\\\\:\";'<>\\?,\\./№ ]+")]
private static partial Regex MyRegex();
```

**Comment by stephentoub** [comment]
@joperezr, this is the same case you previously investigated, right?  What was the outcome?

**Comment by joperezr** [comment]
Yeah, I can't find the related issue where I wrote down the conclusions but essentially the main issue here is that the input to the code could also be _any_ type of a constant value, which means we have to extract the constant value of the string parameter and evaluate the constant value. Once we do that, we now only have the string value, but don't have the original syntax used to represent the string. Therefore, when we generate the attribute, we don't currently have a way of preserving which ever format was used originally as  all of that got lost at the time of evaluating what the constant value of original parameter was.

**Comment by stephentoub** [comment]
> Once we do that, we now only have the string value, but don't have the original syntax used to represent the string.

Why can't we store both?
