### ISSUE TITLE
MapBackgroundJob for Minimal APIs

### ISSUE THREAD

**Issue by julian-code** [dotnet/runtime#78137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

So minimal APIs have now introduced an excellent and functional way of designing APIs. However, you typically want some form of processing something in the background. Either ingest data where no `HttpContext` is present, such as through a message queue/service bus, or do some offloading from your API. Here we usually use `IHostedService` or `BackgroundService` abstractions which perfectly suit this purpose; however not that functional. The current status quo is the following:

```cs
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddHostedService<BackgroundJob>();

var app = builder.Build();

app.Run();

public class BackgroundJob : BackgroundService
{
    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        while (true)
        {
            Console.WriteLine("Hello from background");
            await Task.Delay(1000, stoppingToken);
        }
    }
}
```

### Describe the solution you'd like

I'm proposing the following
```cs
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddScoped<ScopedService>();
var app = builder.Build();

app.MapBackgroundJob(async (ScopedService service, CancellationToken stoppingToken) =>
{
    while (!stoppingToken.IsCancellationRequested)
    {
        Console.WriteLine("Hello from background");
        await Task.Delay(1000, stoppingToken);
    }
});

app.Run();
```

I did a very hacky solution. However, a lot of things don't work here. The handler isn't invoked asynchronously. We create a scope to use scoped services from DI.
```cs
public static class CreateBackgroundJobExtensions
{
    public static IApplicationBuilder MapBackgroundJob(this IApplicationBuilder applicationBuilder, Delegate handler)
    {
        _ = Task.Run(async () =>
        {
            while (true)
            {
                await using var scope = applicationBuilder.ApplicationServices.CreateAsyncScope();
                var parameters = handler.Method.GetParameters();
                var arguments = new object[parameters.Length];
                for (int i = 0; i < arguments.Length; i++)
                {
                    arguments[i] = scope.ServiceProvider.GetService(parameters[i].ParameterType);
                }
                
                handler.DynamicInvoke(arguments);
            }
        });
        return applicationBuilder;
    }
}
```

**Comment by halter73** [comment]
Straw man API proposal:

## Proposed API

```diff
// Microsoft.Extensions.Hosting.Abstractions.dll

namespace Microsoft.Extensions.DependencyInjection;

public static class ServiceCollectionHostedServiceExtensions
{
+    public static IServiceCollection AddHostedService(this IServiceCollection services, Delegate backgroundJob)
}
```

## Usage Examples



## Alternative Designs

Move back to the aspnetcore repo because a `Delegate` parameter is confusing/scary/complicated.

## Risks

While ASP.NET Core has used `Delegate`s like this for [minimal route handlers](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0#request-handling-1), this would be new for the runtime repo.

**Comment by julian-code** [comment]
@halter73, thanks for answering. Showcased it with the `MapBackgroundJob` to emphasize that this proposal should have the same feel as the `Map` methods.

I agree that the However, iterload would be better. It would probably be easier to find developers moving from MVC to minimal API.

**Comment by mitchdenny** [comment]
It also has the benefit that ```AddHostedService(...)``` is used outside of the context of ASP.NET as well so it gives a benefit to all kinds of apps.

**Comment by bradygaster** [comment]
> @bradygaster any thoughts?

It mirrors a request I made some time back on "minimal workers." Like the idea a lot.

**Comment by bradygaster** [comment]
Here's the "minimal workers" issue I'd created https://github.com/dotnet/runtime/issues/64874

**Comment by halter73** [comment]
Right! I can't believe I forgot. I commented over on #64874 updating it with the conversation we've had here.

I'm closing this as a dupe to try to keep this conversation mostly in one place. Thanks again @julian-code for demonstrating the desire for this kind of API and pushing this discussion forward.
