### ISSUE TITLE
[mono][release/7.0] build libs for android arm64 failed on ubuntu

### ISSUE THREAD

**Issue by gemSender** [dotnet/runtime#78141]
### Description

``build libs failed for android with command
`ANDROID_NDK_ROOT=/home/hange/android_tool/android-ndk-r23c ANDROID_SDK_ROOT=/home/hange/android_tool/android-sdk ./build.sh mono+libs -rf Mono -os Android -arch arm64 -c release`

### Reproduction Steps

just follow the doc

### Expected behavior

should successfully built

### Actual behavior

error info:

>   Stripping symbols from $<TARGET_FILE:System.IO.Compression.Native> into file $<TARGET_FILE:System.IO.Compression.Native>.dbg
  /usr/bin/objcopy: Unable to recognise the format of the input file `/home/hange/projects/dotnetruntime/artifacts/obj/native/net7.0-Android-Release-arm64/System.IO.Compression.Native/libSystem.IO.Compression.Native.so'
  System.IO.Compression.Native/CMakeFiles/System.IO.Compression.Native.dir/build.make:592: recipe for target 'System.IO.Compression.Native/libSystem.IO.Compression.Native.so' failed
  make[2]: *** [System.IO.Compression.Native/libSystem.IO.Compression.Native.so] Error 1
  make[2]: *** Deleting file 'System.IO.Compression.Native/libSystem.IO.Compression.Native.so'
  CMakeFiles/Makefile2:165: recipe for target 'System.IO.Compression.Native/CMakeFiles/System.IO.Compression.Native.dir/all' failed
  [ 54%] Building C object System.Security.Cryptography.Native.Android/CMakeFiles/System.Security.Cryptography.Native.Android.dir/pal_ecc_import_export.c.o
  Stripping symbols from $<TARGET_FILE:System.Native> into file $<TARGET_FILE:System.Native>.dbg
  make[1]: *** [System.IO.Compression.Native/CMakeFiles/System.IO.Compression.Native.dir/all] Error 2
  make[1]: *** Waiting for unfinished jobs....
  /usr/bin/objcopy: Unable to recognise the format of the input file `/home/hange/projects/dotnetruntime/artifacts/obj/native/net7.0-Android-Release-arm64/System.Native/libSystem.Native.so'
  System.Native/CMakeFiles/System.Native.dir/build.make:544: recipe for target 'System.Native/libSystem.Native.so' failed
  make[2]: *** [System.Native/libSystem.Native.so] Error 1
  make[2]: *** Deleting file 'System.Native/libSystem.Native.so'
  CMakeFiles/Makefile2:217: recipe for target 'System.Native/CMakeFiles/System.Native.dir/all' failed
  make[1]: *** [System.Native/CMakeFiles/System.Native.dir/all] Error 2
  [ 55%] Building C object System.Security.Cryptography.Native.Android/CMakeFiles/System.Security.Cryptography.Native.Android.dir/pal_eckey.c.o
  [ 55%] Building C object System.Security.Cryptography.Native.Android/CMakeFiles/System.Security.Cryptography.Native.Android.dir/pal_ecdh.c.o
  [ 56%] Building C object System.Security.Cryptography.Native.Android/CMakeFiles/System.Security.Cryptography.Native.Android.dir/pal_err.c.o
  [ 56%] Building C object System.Security.Cryptography.Native.Android/CMakeFiles/System.Security.Cryptography.Native.Android.dir/pal_cipher.c.o
  [ 57%] Building C object System.Security.Cryptography.Native.Android/CMakeFiles/System.Security.Cryptography.Native.Android.dir/pal_evp.c.o
  [ 58%] Building C object System.Security.Cryptography.Native.Android/CMakeFiles/System.Security.Cryptography.Native.Android.dir/pal_hmac.c.o
  [ 58%] Building C object System.Security.Cryptography.Native.Android/CMakeFiles/System.Security.Cryptography.Native.Android.dir/pal_jni.c.o
  [ 59%] Building C object System.Security.Cryptography.Native.Android/CMakeFiles/System.Security.Cryptography.Native.Android.dir/pal_lifetime.c.o
  [ 60%] Building C object System.Security.Cryptography.Native.Android/CMakeFiles/System.Security.Cryptography.Native.Android.dir/pal_memory.c.o
  [ 60%] Building C object System.Security.Cryptography.Native.Android/CMakeFiles/System.Security.Cryptography.Native.Android.dir/pal_misc.c.o
  [ 61%] Building C object System.Security.Cryptography.Native.Android/CMakeFiles/System.Security.Cryptography.Native.Android.dir/pal_rsa.c.o
  [ 61%] Building C object System.Security.Cryptography.Native.Android/CMakeFiles/System.Security.Cryptography.Native.Android.dir/pal_signature.c.o
  [ 62%] Building C object System.Security.Cryptography.Native.Android/CMakeFiles/System.Security.Cryptography.Native.Android.dir/pal_ssl.c.o
  [ 63%] Building C object System.Security.Cryptography.Native.Android/CMakeFiles/System.Security.Cryptography.Native.Android.dir/pal_sslstream.c.o
  [ 64%] Building C object System.Security.Cryptography.Native.Android/CMakeFiles/System.Security.Cryptography.Native.Android.dir/pal_x509chain.c.o
  [ 64%] Building C object System.Security.Cryptography.Native.Android/CMakeFiles/System.Security.Cryptography.Native.Android.dir/pal_x509.c.o
  [ 64%] Building C object System.Security.Cryptography.Native.Android/CMakeFiles/System.Security.Cryptography.Native.Android.dir/pal_x509store.c.o
  [ 65%] Building C object System.Security.Cryptography.Native.Android/CMakeFiles/System.Security.Cryptography.Native.Android.dir/home/hange/projects/dotnetruntime/artifacts/obj/_version.c.o
  [ 65%] Linking C shared library libSystem.Security.Cryptography.Native.Android.so
  Stripping symbols from $<TARGET_FILE:System.Security.Cryptography.Native.Android> into file $<TARGET_FILE:System.Security.Cryptography.Native.Android>.dbg
  /usr/bin/objcopy: Unable to recognise the format of the input file `/home/hange/projects/dotnetruntime/artifacts/obj/native/net7.0-Android-Release-arm64/System.Security.Cryptography.Native.Android/libSystem.Security.Cryptography.Native.Android.so'
  System.Security.Cryptography.Native.Android/CMakeFiles/System.Security.Cryptography.Native.Android.dir/build.make:432: recipe for target 'System.Security.Cryptography.Native.Android/libSystem.Security.Cryptography.Native.Android.so' failed
  make[2]: *** [System.Security.Cryptography.Native.Android/libSystem.Security.Cryptography.Native.Android.so] Error 1
  make[2]: *** Deleting file 'System.Security.Cryptography.Native.Android/libSystem.Security.Cryptography.Native.Android.so'
  CMakeFiles/Makefile2:269: recipe for target 'System.Security.Cryptography.Native.Android/CMakeFiles/System.Security.Cryptography.Native.Android.dir/all' failed
  make[1]: *** [System.Security.Cryptography.Native.Android/CMakeFiles/System.Security.Cryptography.Native.Android.dir/all] Error 2
  Makefile:135: recipe for target 'all' failed
  make: *** [all] Error 2
  ~/projects/dotnetruntime/src/native/libs
  Failed to build "native libraries component".
/home/hange/projects/dotnetruntime/src/native/libs/build-native.proj(42,5): error MSB3073: The command ""/home/hange/projects/dotnetruntime/src/native/libs/build-native.sh" arm64 Release outconfig net7.0-Android-Release-arm64 -os Android " exited with code 2.

Build FAILED.

/home/hange/projects/dotnetruntime/src/native/libs/build-native.proj(42,5): error MSB3073: The command ""/home/hange/projects/dotnetruntime/src/native/libs/build-native.sh" arm64 Release outconfig net7.0-Android-Release-arm64 -os Android " exited with code 2.
    0 Warning(s)
    1 Error(s)

**Comment by vcsjones** [comment]
Since the error is also occurring for `System.IO.Compression.Native` and `System.Native` in addition to `System.Security.Cryptopgraphy.Native.Android`, I don't believe this is specific to cryptography building.

**Comment by steveisok** [comment]
Weird. I have Ubuntu 18.04 local and release/7.0 Android builds fine for me.  

@gemSender, what version are you using?  Any other details to note?

**Comment by gemSender** [comment]
$ uname-a
Linux ubuntu 5.4.0-131-generic #147~18.04.1-Ubuntu SMP Sat Oct 15 13:10:18 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
@steveisok

**Comment by gemSender** [comment]
libmonosgen-2.0.so was successfully built

**Comment by steveisok** [comment]
I have the same version and the whole thing builds for me. Is there anything different about your setup?

**Comment by gemSender** [comment]
nothing else.
but i am wondering why the objcpy command in the system directory is called instead of the objcopy tool in the ndk directory
@steveisok 

it seems that objcopy tool in the ndk directory work correctly to shared library of android

**Comment by gemSender** [comment]
![}420P(9(A8B@C1FTA12L98T](https://user-images.githubusercontent.com/6006458/200999710-40ad1271-63a5-481e-bf94-167ae013c5bb.png)

**Comment by steveisok** [comment]
@akoeplinger @directhex any ideas?

**Comment by davidxuang** [comment]
This is causing problem when targeting `linux-arm64` as well. I’m using `mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-cross-arm64-staging` to build for `linux-x64` and `linux-arm64` side-by-side.

This is working
`dotnet publish -c Release -r linux-x64 -p:CppCompilerAndLinker=clang-9`
while this is not
`dotnet publish -c Release -r linux-arm64 -p:CppCompilerAndLinker=clang-9 -p:SysRoot=/crossrootfs/arm64`
with project properties
```xml
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DebugType>None</DebugType>
    <PublishAot>true</PublishAot>
    <StripSymbols>true</StripSymbols>
    <InvariantGlobalization>true</InvariantGlobalization>
    <IlcOptimizationPreference>Speed</IlcOptimizationPreference>
  </PropertyGroup>
```
and such error output
```
/usr/share/dotnet/sdk/7.0.100/Sdks/Microsoft.DotNet.ILCompiler/build/Microsoft.NETCore.Native.targets(358,5): error MSB3073: The command " [/__w/AotDemo/AotDemo/AotDemo.Commandline/AotDemo.Commandline.csproj]
/usr/share/dotnet/sdk/7.0.100/Sdks/Microsoft.DotNet.ILCompiler/build/Microsoft.NETCore.Native.targets(358,5): error MSB3073:         "objcopy" --only-keep-debug "bin/Release/net7.0/linux-arm64/native/AotDemo" "bin/Release/net7.0/linux-arm64/native/AotDemo.dbg" && [/__w/AotDemo/AotDemo/AotDemo.Commandline/AotDemo.Commandline.csproj]
/usr/share/dotnet/sdk/7.0.100/Sdks/Microsoft.DotNet.ILCompiler/build/Microsoft.NETCore.Native.targets(358,5): error MSB3073:         "objcopy" --strip-debug --strip-unneeded "bin/Release/net7.0/linux-arm64/native/AotDemo" && [/__w/AotDemo/AotDemo/AotDemo.Commandline/AotDemo.Commandline.csproj]
/usr/share/dotnet/sdk/7.0.100/Sdks/Microsoft.DotNet.ILCompiler/build/Microsoft.NETCore.Native.targets(358,5): error MSB3073:         "objcopy" --add-gnu-debuglink="bin/Release/net7.0/linux-arm64/native/AotDemo.dbg" "bin/Release/net7.0/linux-arm64/native/AotDemo"" exited with code 1. [/__w/AotDemo/AotDemo/AotDemo.Commandline/AotDemo.Commandline.csproj]
```

**Comment by akoeplinger** [comment]
@gemSender which cmake version are you using?

**Comment by directhex** [comment]
Can you attach a binlog? I want to see the decision making going into which objcopy binary is used

**Comment by gemSender** [comment]
3.20.1 @akoeplinger

**Comment by akoeplinger** [comment]
hmm I think I have vague memories of hitting issues with CMake 3.20. can you try installing the latest version and trying again, after deleting the `artifacts` directory?
