### ISSUE TITLE
LibraryImportGenerator, .NET 7: possible error in the 'Equals' method implementation

### ISSUE THREAD

**Issue by VasilievSerg** [dotnet/runtime#78145]
### Description

Code:
```cs
public bool Equals(IncrementalStubGenerationContext? other)
{
  return other is not null
               && StubEnvironment.AreCompilationSettingsEqual(Environment, other.Environment)
               && SignatureContext.Equals(other.SignatureContext)
               && ContainingSyntaxContext.Equals(other.ContainingSyntaxContext)
               && StubMethodSyntaxTemplate.Equals(other.StubMethodSyntaxTemplate)
               && LibraryImportData.Equals(other.LibraryImportData)
               && DiagnosticLocation.Equals(DiagnosticLocation)               // <=
               && ForwardedAttributes.SequenceEqual(other.ForwardedAttributes, (IEqualityComparer<AttributeSyntax>)SyntaxEquivalentComparer.Instance)
               && GeneratorFactoryKey.Equals(other.GeneratorFactoryKey)
               && Diagnostics.SequenceEqual(other.Diagnostics);
            }
```
[Link to the sources](https://github.com/dotnet/runtime/blob/d099f075e45d2aa6007a22b71b45a08758559f80/src/libraries/System.Runtime.InteropServices/gen/LibraryImportGenerator/LibraryImportGenerator.cs#L43).

Looks suspicious that `DiagnosticLocation` compares to itself. 

### Reproduction Steps

-

### Expected behavior

-

### Actual behavior

-

**Comment by AaronRobinsonMSFT** [comment]
@VasilievSerg Agreed, this does look odd. Care to submit a PR for adding the `other.`?

@jkoritzinsky Are we missing a test for this or is this one of those checks that doesn't matter often enough in practice?

**Comment by jkoritzinsky** [comment]
I fixed this in .NET 8 and found that we did have a test validating the behavior. Unfortunately, the test is wrong in .NET 7 and didn't catch it.

The fix and the updated test were part of https://github.com/dotnet/runtime/pull/76474/files#diff-e5ffd09434c9daa4ab5234b83ae383b344c4c20d15a93216b93d358226a10586

In particular, the updates to the `AppendingUnrelatedSource_DoesNotRegenerateSource` test capture the result of fixing this bug.

**Comment by jkoritzinsky** [comment]
Updating the milestone to .NET 7.0.X as this was already fixed in .NET 8.

**Comment by VasilievSerg** [comment]
I found two more similar places:

- JSImportGenerator.cs ([link](https://github.com/dotnet/runtime/blob/d099f075e45d2aa6007a22b71b45a08758559f80/src/libraries/System.Runtime.InteropServices.JavaScript/gen/JSImportGenerator/JSImportGenerator.cs#L42));
- JSExportGenerator.cs ([link](https://github.com/dotnet/runtime/blob/d099f075e45d2aa6007a22b71b45a08758559f80/src/libraries/System.Runtime.InteropServices.JavaScript/gen/JSImportGenerator/JSExportGenerator.cs#L37)).

**Comment by jkoritzinsky** [comment]
The fix for those was also included in #76474 for .NET 8. It might be worthwhile backporting these fixes to .NET 7 (or all of #76474, which I mentioned in that PR).

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky What is the fallout for this? How are customers impacted by this bug?

**Comment by AaronRobinsonMSFT** [comment]
This doesn't see to be actionable any longer. Closing.
