### ISSUE TITLE
Add a feature on Utf8JsonReader to skip validation when reading

### ISSUE THREAD

**Issue by alrz** [dotnet/runtime#78159]
### Background and motivation

There's a similar feature to skip validation on the writer.
```cs
sealed class MyConverter : JsonConverter<Model>
{
    public override void Write(Utf8JsonWriter writer, Model value, JsonSerializerOptions options)
        => writer.WriteRawValue(ToBytes(value), skipInputValidation: true); // invalid JSON
    public override Model? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        => FromBytes(reader.Value{Span, Sequece}); // internal ConsumeValue(byte) throws
}
```

### API Proposal

An option similar to `CommentHandling` to allow arbitrary byte streams.

**Comment by layomia** [comment]
Can you specify what validation you'd like to be able to skip? Some sample payloads would be great to see. What are `FromBytes` and `ConsumeValue` supposed to be doing? FWIW I'm not in favor of any such feature but it would be great to understand the ask here.

**Comment by alrz** [comment]
Was trying to implement a converter to write/read protobuf for IMessage types for a library that already work with S.T.J.
ConsumeValue is an internal method that cannot make sense of such byte stream and throws.
It would be convenient to be able to read back the data that's written using skipInputValidation=true.

**Comment by layomia** [comment]
IIUC you want a feature on `Utf8JsonReader` that skips structural validation when reading, analogous to writing with `Utf8JsonWriter.WriteRaw*` functionality.

**Comment by eiriktsarpalis** [comment]
Unlike comments, JSON values need to be validated for them to be skipped (because that's the only way the end position of the next value can be determined). This is currently achievable using the `Utf8JsonReader.Skip()` method.

Could you provide examples of input validation that you would like to see skipped and whether `Skip()` is able to handle these?

**Comment by alrz** [comment]
> Unlike comments, JSON values need to be validated for them to be skipped (because that's the only way the end position of the next value can be determined). This is currently achievable using the `Utf8JsonReader.Skip()` method.
> 
> Could you provide examples of input validation that you would like to see skipped and whether `Skip()` is able to handle these?

In my scenario I want to read the entire stream (the converter is defined on the root object).

**Comment by eiriktsarpalis** [comment]
> In my scenario I want to read the entire byte stream (the converter is defined on the root object).

Why use a converter (or even JsonSerializer) in the first place? Clearly you just need to offload the entire payload to a different parser.

**Comment by alrz** [comment]
> Was trying to implement a converter to write/read protobuf for IMessage types for a library that already work with S.T.J .. It would be convenient to be able to read back the data that's written using skipInputValidation=true.

That's what I stated in my previous comment to clarify. Perhaps that case is too niche to grant a feature but I like the symmetry of skipping validation in both reader and the writer.

**Comment by eiriktsarpalis** [comment]
I think the fact that that the scenario only works for root values precludes any possibility of this being included in `Utf8JsonReader`.
