### ISSUE TITLE
Using CmsSigner ComputeSignature i'm able to digitally sign a document but it's not valid for UE 2015/1506 directive 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#78166]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Using-CmsSigner-ComputeSignature-im-abl/10108302)._

---
Using CmsSigner ComputeSignature i'm able to digitally sign a document but it's not valid for UE 2015/1506 directive.
Step to reproduce this issue:
- digitally sign a document using ComputeSignature method of CmsSigner with a valid X509Certificate2
- visit this site: https://ec.europa.eu/digital-building-blocks/DSS/webapp-demo/validation using digitally signed document and source document and you could see "The signed attribute: 'signing-certificate' is absent"; note that all other attribute is correctly validated
I think it could be an issue on ComputeSignature method.
Enclosed you could find a detailed report ane here in our line of c# code;

```
        public void DoSign(X509Certificate2 cert)
        {
            try
            {
                ContentInfo content = new ContentInfo(File.ReadAllBytes(@"C:\Temp\ToSignTxt.txt"));
                SignedCms signedCms = new SignedCms(content, false);

                CmsSigner signer = new CmsSigner(SubjectIdentifierType.IssuerAndSerialNumber, cert);
                signer.DigestAlgorithm = new System.Security.Cryptography.Oid("SHA256"); //we have tried also System.Security.Cryptography.Oid("2.16.840.1.101.3.4.2.1");
                signer.SignedAttributes.Add(new Pkcs9SigningTime());

                signedCms.ComputeSignature(signer);
                byte[] signature = signedCms.Encode();
                System.IO.File.WriteAllBytes(@"C:\Temp\ToSignTxt.txt.p7m", signature);
                //The resulting signature will contain both the signature data as well as the original text.  When you use SignedCms to verify the signature on the other end:
            }

            catch (Exception ex)
            {
                //Logger.Write($"Errore {ex.Message}", "Application", 0, 0, System.Diagnostics.TraceEventType.Warning);
                MessageBox.Show($"Errore {ex.Message}", "Error During Digitally Sign Document", MessageBoxButtons.OK);
            }
        }
```

[DSS-Detailed-report.zip](https://aka.ms/dc/file?name=B72c279894d1e4e5c9e9cf57c6a109063637949358134411757_DSS-Detailed-report.zip&tid=72c279894d1e4e5c9e9cf57c6a109063637949358134411757)

---
#### Feedback Bot on 8/1/2022, 03:51 AM: 

(private comment, text removed)
#### Feedback Bot on 11/3/2022, 00:55 AM: 

(private comment, text removed)
#### Jeremy Barton [MSFT] on 11/9/2022, 01:44 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by bartonjs** [comment]
Replicating my statement from there to here:

UE 2015/1506 seems to be built on/around [CAdES](https://en.wikipedia.org/wiki/CAdES_(computing)), which is “SignedCms plus a bunch of other stuff”.

In this case, it seems to be complaining that you didn’t provide a value for the ESS signing-certificate attribute (or ESS signing-certificate-v2 attribute), which is required by CAdES-BES (per https://datatracker.ietf.org/doc/html/rfc5126#section-4.3.1).

We don’t have special support for CAdES documents built-in to .NET, you’ll have to add that as a signer attribute yourself (or find a CAdES-specialized library for .NET).
