### ISSUE TITLE
Using json source generators prevents the possibility to serialize anonymous objects in views

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#78164]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Using-json-source-generators-prevents-th/10156351)._

---
[severity:I'm unable to use this version] [regression] [worked-in:net 6.0]
In net6 we have source generators for api objects (defined in startup) and use standard serialization for generating javascript objects in views among which a lot of anonymous objects.
In .net 7 it is now required that all objects that are serialized or done by source generators. Although this can be done for fixed classes, it gives a problem for (dynamic) anonymous objects.

---
#### Feedback Bot on 9/25/2022, 10:27 PM: 

(private comment, text removed)

---
#### Rick Kauwen solved on 11/8/2022, 06:20 PM, 0 votes: 

<p>See <a target='_blank' href="https://learn.microsoft.com/en-us/dotnet/core/compatibility/serialization/7.0/reflection-fallback">https://learn.microsoft.com/en-us/dotnet/core/compatibility/serialization/7.0/reflection-fallback</a></p>

**Comment by davidfowl** [comment]
> In .net 7 it is now required that all objects that are serialized or done by source generators. Although this can be done for fixed classes, it gives a problem for (dynamic) anonymous objects.

Who said that?

**Comment by eiriktsarpalis** [comment]
Under the current source generator model, supported types need to be specified by name using the `JsonSerializableAttribute`. As such, it is not possible to opt them in for source generation. One workaround is replacing anonymous types with named equivalents (using C# records should minimize the amount of boilerplate required).
