### ISSUE TITLE
 Error 1053: The service did not respond to the start or control request in a timely fashion.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#78167]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/-Error-1053:-The-service-did-not-respond/10039971)._

---
[severity:It's more difficult to complete my work]
We have created a windows service using .Net C# language. 
We are able to install service on the UAT server but could not start the service. 

Service created by referring below link
https://www.c-sharpcorner.com/article/create-windows-services-in-c-sharp/

Getting following errors
![Error 1053.PNG](https://aka.ms/dc/image?name=Be74a533417444b7fb3236bcc79341839637879357765992687_Error_1053.PNG&tid=e74a533417444b7fb3236bcc79341839637879357765992687)

Below is the error from EventLog
![Error 1053 EventLog.PNG](https://aka.ms/dc/image?name=B6f6eb825cc05445483ba192d0f723c95637879358380873071_Error_1053_EventLog.PNG&tid=6f6eb825cc05445483ba192d0f723c95637879358380873071)

Please suggest solution.

---
#### Feedback Bot on 5/12/2022, 04:01 AM: 

(private comment, text removed)
#### Feedback Bot on 8/31/2022, 08:39 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ViktorHofer** [comment]
Prakash Mohite can you please share more information? The above images are broken.

**Comment by ericstj** [comment]
Adding a note for anyone else who might find this issue.  Error 1053 is ERROR_SERVICE_REQUEST_TIMEOUT.  This will happen if on start if the process starts and doesn't notify Service Control Manager that the service is started.  This will happen in a .NET service if the application does too much in it's main routine before calling [ServiceBase.Run](https://learn.microsoft.com/en-us/dotnet/api/system.serviceprocess.servicebase.run?view=dotnet-plat-ext-8.0) or if the application fails in it's main routine and never calls ServiceBase.Run.

Services should do little work in Main (or in their constructor) and instead move that work to be triggered by the call to ServiceBase.OnStart. See https://learn.microsoft.com/en-us/dotnet/api/system.serviceprocess.servicebase?view=dotnet-plat-ext-8.0
