### ISSUE TITLE
"Namespace" is not a supported Runtime Directive

### ISSUE THREAD

**Issue by ivanjx** [dotnet/runtime#78185]
### Description

i tried to exclude a namespace from native aot but i got the error as the title says. here is my `rd.xml`:
```
<Directives>
	<Application>
		<Namespace Name="mynamespace" Dynamic="Required All"></Namespace>
...
```

### Reproduction Steps

add a `Namespace` directive inside `rd.xml`

### Expected behavior

it works

### Actual behavior

`EXEC : error : "Namespace" is not a supported Runtime Directive.`

### Configuration

dotnet: 7.0.100
os: ubuntu 22.04 x64

**Comment by MichalStrehovsky** [comment]
The `Namespace` directive is not supported. The supported file format is described here: https://github.com/dotnet/runtime/blob/7db5a577938d83c76f0654635d6ffe1598358097/src/coreclr/nativeaot/docs/rd-xml-format.md

**Comment by ivanjx** [comment]
any reason why namespace isn't supported?

**Comment by MichalStrehovsky** [comment]
RD.XML is not a supported technology for PublishAot (there are no docs for it on docs.microsoft.com) and we don't plan to invest into it. The supported and documented trimming knobs are at https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-7-0.
