### ISSUE TITLE
Memory leak from linked cancellation token registrations

### ISSUE THREAD

**Issue by ogxd** [dotnet/runtime#78180]
### Description

# Context

We currently work on an ASP NET Core service that handles several thousands of request per seconds per instance. Internally, each request leads to several additional I/Os, with different response time requirements. In order to avoid unnecessarily waiting for an I/O completion when a request must be completed under a given time, we heavily rely on cancellation tokens and more specifically [CancellationTokenSource.CreateLinkedTokenSource](https://learn.microsoft.com/en-us/dotnet/api/system.threading.cancellationtokensource.createlinkedtokensource?view=net-6.0) to merge the different timeout policies. All good so far, this is probably quite a standard way to do this.   

A while ago, we noticed that our cancellation system was leading to a lot of thread contention (about 100k contention events / s according to ETW ContentionStart / Stop events).    
Fortunately, we saw [this 11 years old blog post](https://devblogs.microsoft.com/pfxteam/coalescing-cancellationtokens-from-timeouts/) from @stephentoub and by sharing the cancellation tokens the thread contention when down from 100k to something like 10 🎉

## The problem

Since we have been "pooling" cancellation tokens, despite the thread contention improvements, **we have noticed weird memory patterns** (some kind of memory leak). We've tried different implementations for pooling tokens, but the results were always the same, up to a point that we began questioning the framework itself.    

## The repro

It wasn't clear until we have made a simple repro. You can find it here: [cancellation-tokens-mem-leak-repro](https://github.com/ogxd/cancellation-tokens-mem-leak-repro).    
In this repro you can:
- Switch between not pooling token (`FrameworkTimeoutCancellationTokenProvider`) or pooling them (`CoalescingTimeoutCancellationTokenProvider`)
- Switch between using the framework way to merge 2 cancellation tokens (`FrameworkLinkedCancellationTokenProvider`) or 2 custom implementations (`CustomLinkedCancellationTokenProvider` and `CustomLinkedNoRegistrationCancellationTokenProvider`)

In short, the results are that whenever we pool tokens and keep a reference to cancellation token registrations, there is a memory leak.

Here are some graphs I've made using dotMemory:

### No pooling + Registrations = No leak (Reference)

![image](https://user-images.githubusercontent.com/12692438/201168123-f38d4950-7970-47b6-9eca-281e2ae7f5fe.png)
It's flat after a few seconds = no leak (verified by looking at GC survivors)

### Pooling + Registrations = Leak

(The results are the same, whether I use `FrameworkLinkedCancellationTokenProvider` or `CustomLinkedCancellationTokenProvider` so no need to show the results for both).
![image](https://user-images.githubusercontent.com/12692438/201168576-36bab107-248b-4f96-af66-f57b2a28231e.png)
Memory is growing over time: it's leaking.    
**So what's the leak?**    
![image](https://user-images.githubusercontent.com/12692438/201168943-ce7235f1-2255-41a8-8271-9553a03b9e14.png)
As you can see there are a lot of registrations and `Linked2CancellationTokenSource` surviving GC (it shouldn't)    
With dotMemory we can trace back the retention path for a single surviving `Linked2CancellationTokenSource` instance. It's very deep, so here is the beginning:
![image](https://user-images.githubusercontent.com/12692438/201169675-293c9b04-6559-42ed-918e-af1ff5c40694.png)
And here is the end (GC roots):
![image](https://user-images.githubusercontent.com/12692438/201169766-6aab5fcd-0256-4192-b6dd-5ca87ed7d734.png)

### Pooling + No registration = No leak ???
I have created `CustomLinkedNoRegistrationCancellationTokenProvider` which is similar to `Linked2CancellationTokenSource` BUT it doesn't keep a reference to registration. It turns out that doing so we can completely get rid of the leak. It feels weird to me however to not dispose an `IDisposable`, and this is why I would like to investigate this with you. This is probably more a workaround than a proper solution.    

Here is the memory profile anyway:
![image](https://user-images.githubusercontent.com/12692438/201170564-51911fa4-e6e3-42e0-b1a7-999f43d7c16b.png)
After a few seconds it's flat, which is a good sign. We can also look at GC survivors over 20 seconds:  
![image](https://user-images.githubusercontent.com/12692438/201170946-69d62f9b-ebd1-4492-b30c-8dbfd32d7c7e.png)
There are far less cancellation token sources surviving. Those remaining one are probably expected given how the repo is made.

### Reproduction Steps

https://github.com/ogxd/cancellation-tokens-mem-leak-repro

### Expected behavior

Expected behavior is no memory leak

### Actual behavior

It seems there is a memory leak.

### Regression?

I don't know

### Known Workarounds

The `CustomLinkedNoRegistrationCancellationTokenProvider` from the repro is a workaround, but it would be better to understand/fix the issue before relying on this in a production environment.

### Configuration

- Tested on MacOS, Windows and Ubuntu 20.
- Framework is SDK 6.0 and runtime 6.0

**Comment by MihaZupan** [comment]
If you run the repro longer, does the leak persist, or is it bounded at some point?

> It feels weird to me however to not dispose an IDisposable

Your repro isn't disposing anything though.

Regardless of what the exact cause of this issue is here, you may find https://github.com/microsoft/reverse-proxy/blob/main/src/ReverseProxy/Utilities/ActivityCancellationTokenSource.cs useful depending on exactly what you're doing with these cancellation tokens. This approach is practically allocation-free when timeouts aren't occurring.

**Comment by ogxd** [comment]
> If you run the repro longer, does the leak persist, or is it bounded at some point?
Yes, here I ran it for 8 minutes:
![image](https://user-images.githubusercontent.com/12692438/201186820-fdf04a50-cff9-42db-b16a-55cb9d21c218.png)
![image](https://user-images.githubusercontent.com/12692438/201186953-57518bfe-d926-4d66-bcae-816ec220a0cc.png)
![image](https://user-images.githubusercontent.com/12692438/201187112-8442df96-35eb-4406-8849-662a7d60621f.png)
Here is about the same duration with the workaround instead (not keeping a reference to registrations):
![image](https://user-images.githubusercontent.com/12692438/201188887-4e8d3380-fbd8-479a-8212-ed35f6c59b77.png)

> Your repro isn't disposing anything though.

I was expecting deconstructor to invoke `Dispose()` even if I don't explicitly call it
```csharp
public class LinkedCancellationTokenSource : CancellationTokenSource
{
    [...]

    protected override void Dispose(bool disposing)
    {
        reg1?.Dispose();
        reg2?.Dispose();
      
        base.Dispose(disposing);
    }

    ~LinkedCancellationTokenSource()
    {
        Dispose(true);
    }
}
```

**Comment by stephentoub** [comment]
> I was expecting deconstructor to invoke Dispose() even if I don't explicitly call it

That's the finalizer, which is only invoked when there are no more rooted references to this instance.  And those registrations have a reference back to this instance.  When you have:
```C#
CancellationTokenSource cts1 = ...;
CancellationTokenSource cts2 = CancellationTokenSource.CreateLinkedTokenSource(cts1.Token);
```
that's effectively storing a reference to cts2 into cts1 so that when cts1 has cancellation requested, that request will propagate to cts2.  Until you Dispose of cts2, cts1 is going to continue to hold that reference.  If you don't Dispose cts2, as long as cts1 is rooted, cts2 will also thus be rooted, and it will never have its finalizer called.

**Comment by ogxd** [comment]
Given what you said, I was thinking why not disposing the registrations (not the whole source) right after the cancellation occured?   
Like this:
```csharp
public class LinkedCancellationTokenSource : CancellationTokenSource
{
    private CancellationTokenRegistration? _registration1;
    private CancellationTokenRegistration? _registration2;
            
    public LinkedCancellationTokenSource(CancellationToken token1, CancellationToken token2)
    {
        if (token1.CanBeCanceled)
            _registration1 = token1.Register(CancelAndDisposeRegistrations);
                
        if (token2.CanBeCanceled)
            _registration2 = token2.Register(CancelAndDisposeRegistrations);
    }

    private void CancelAndDisposeRegistrations()
    {
        Cancel();
        _registration1?.Dispose();
        _registration2?.Dispose();
    }
}
```
It seems to work very well.
![image](https://user-images.githubusercontent.com/12692438/201193601-c39e9c77-1987-4117-b462-a36b49472e12.png)

Do you see any caveats in doing this?

**Comment by ogxd** [comment]
I played a little more with the repro and I think the reason for this "memory leak" is probably not a bug but the combination of these factors:
- Using Linked2CancellationTokenSource to create token registrations (from `CancellationTokenSource.CreateLinkedTokenSource`)
- Pooling the cancellation tokens (thus implying multiple registrations per token)
- Not disposing `Linked2CancellationTokenSource` 

By disposing the `Linked2CancellationTokenSource` I no longer have memory issues. We were missing this in our application.
```csharp
using var cts = CancellationTokenSource.CreateLinkedTokenSource(token1, token2);
await FooAsync(cts.Token);
```

Still I wonder if **the solution proposed above** (unregister in token cancel callback instead of unregistering in `Linked2CancellationTokenSource.Dispose`). It's always best to not forget to dispose, but time have shown that people tend to forget it at times (like we did, but [a search on GitHub](https://github.com/search?q=CreateLinkedTokenSource+extension%3A.cs&type=Code&ref=advsearch&l=&l=) shows that many forget it also and probably aren't aware that their code leak memory because of this).     
To avoid this easy issue, this solution could be a nice way to prevent this kind of unsafe symptom to happen in a non-unsafe context. What do you think?

**Comment by ogxd** [comment]
Here I come back with an answer to my own question 😀
The solution I proposed does seem to help **however** there is still a major issue from not disposing, even when using this. The issue is the case where the LinkedCancellationTokenSource isn't canceled yet but is out of scope. In this case, it is not disposed nor canceled, thus it will outlive the scope. This implies that despite addressing the main leak concern, it might live longer than it should and thus use more memory.

I still think this API is not very practical and can lead to memory safety issues. For now, I decided to leverage roslyn analyzers with [CA2000](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2000) to enforce disposal at build time. At least that's one less concern. 

Closing this issue.

**Comment by stephentoub** [comment]
> Still I wonder if the solution proposed above (unregister in token cancel callback instead of unregistering only in Linked2CancellationTokenSource.Dispose) isn't an nice usability/safety improvement.

We've avoided doing that in the past as it would require extra virtual method invocations somewhere along the Cancel path, whereas right now the only one that's involved is the one for Dispose.  But, technically I expect it could be done.
