### ISSUE TITLE
Use new IndexOfAnyValues throughout dotnet/runtime

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#78204]
Once https://github.com/dotnet/runtime/pull/78093 is merged, we'll want to use it in a variety of places where it'll provide benefits.

Some example possible use sites:

- https://github.com/dotnet/runtime/blob/8ddb0c4a0fc2b75ea77f8ef075ab8e41277ea442/src/libraries/Microsoft.Extensions.Configuration.UserSecrets/src/PathHelper.cs#L49
- https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/Internal/PathUtils.cs#L12-L29
- https://github.com/dotnet/runtime/blob/eeeeb7a75c338b0d994ccd7140d676a612990ebc/src/libraries/System.IO.Pipes/src/System/IO/Pipes/PipeStream.Unix.cs#L212
- https://github.com/dotnet/runtime/blob/8ddb0c4a0fc2b75ea77f8ef075ab8e41277ea442/src/libraries/System.Text.Json/src/System/Text/Json/Nodes/JsonObject.cs#L131

---

Already updated:
- https://github.com/dotnet/runtime/blob/8626da3cc62d940513141b7c58c3495a87bb2bba/src/coreclr/System.Private.CoreLib/src/System/TypeNameParser.cs#L279
- https://github.com/dotnet/runtime/blob/a41ac2c9457a91b1a2c3d5f06aad7fe1e249b658/src/libraries/System.Net.Primitives/src/System/Net/Cookie.cs#L241
- https://github.com/dotnet/runtime/blob/214ca6db481923aa49bac2d2b75b9aca4041b304/src/libraries/System.Private.Uri/src/System/DomainNameHelper.cs#L392-L393
- https://github.com/dotnet/runtime/blob/2f787345439a94935fca16dd2edd2a0351310695/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/X500NameEncoder.cs#L129-L130
- https://github.com/dotnet/runtime/blob/28f6daaaf825f167aa1808291cf56bf16234e48a/src/libraries/System.Private.Xml/src/System/Xml/XmlCharType.cs#L164-L177
- https://github.com/dotnet/runtime/blob/8918adf2e5255920aed3c61f9b92c2a51eec0fe3/src/libraries/System.Private.DataContractSerialization/src/System/Xml/XmlBaseWriter.cs#L757-L774
- https://github.com/dotnet/runtime/blob/8918adf2e5255920aed3c61f9b92c2a51eec0fe3/src/libraries/System.Private.DataContractSerialization/src/System/Xml/XmlBufferReader.cs#L768-L788
- https://github.com/dotnet/runtime/blob/8918adf2e5255920aed3c61f9b92c2a51eec0fe3/src/libraries/System.Private.DataContractSerialization/src/System/Xml/XmlConverter.cs#L1085-L1093
- https://github.com/dotnet/runtime/blob/8918adf2e5255920aed3c61f9b92c2a51eec0fe3/src/libraries/System.Net.Http/src/System/Net/Http/HttpRuleParser.cs#L88-L112
- https://github.com/dotnet/runtime/blob/4820105ba85531da5b388e7b2e98fdcdae9ced07/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexParser.cs#L150-L161

**Comment by adamsitnik** [comment]
@MihaZupan I can see that you have merged plenty of PRs related to this issue. Is it done now?

**Comment by MihaZupan** [comment]
My queries for interesting patterns that could be replaced are starting to dry up.
There's still a handful of places that can be updated, after that, I'll close this issue.

Still on my TODO to look at:
```
https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/Internal/PathUtils.cs
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Mail/src/System/Net/Mail/MailBnfHelper.cs
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.DataContractSerialization/src/System/Xml/XmlUTF8TextWriter.cs
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Globalization/CompareInfo.Icu.cs
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/MultipartContent.cs
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Data.Common/src/System/Data/Filter/ExpressionParser.cs
```
