### ISSUE TITLE
Use new IndexOfAnyValues in RegexCompiler and source generator

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#78203]
Once https://github.com/dotnet/runtime/pull/78093 is merged, we'll want to use it in the RegexCompiler and source generator.  This will require reworking the heuristics for when we consider sets viable for being used with IndexOf, updating the relevant data structures to pass along the relevant info, and updating the code emitters appropriately.

**Comment by MihaZupan** [comment]
I have some local experiments with this already. I'll take a crack at it and unassign myself if I fail miserably :)
