### ISSUE TITLE
mono runtime using 3rd Party library internal invoke native code lead app crash

### ISSUE THREAD

**Issue by jingliancui** [dotnet/runtime#78205]
### Description

please check this issue:
https://github.com/xamarin/xamarin-android/issues/7532

### Reproduction Steps

https://github.com/xamarin/xamarin-android/files/9944038/JPushMAUI.zip

1.Unzip the ziped file.
2.Using Android Studio run the app that placed on the native folder with debug mode.
3.Using Visual Studio run the app that placed on the SampleApp folder with debug mode.
4.Native app normal run after occur JPushInterface.init(this); which wrote on MainActivity.java
5.SampleApp crash after occur CN.Jpush.Android.Api.JPushInterface.Init(this); which wrote on MainActivity.cs

### Expected behavior

SampleApp run after occur CN.Jpush.Android.Api.JPushInterface.Init(this); which wrote on MainActivity.cs

### Actual behavior

SampleApp crash after occur CN.Jpush.Android.Api.JPushInterface.Init(this); which wrote on MainActivity.cs

### Known Workarounds

can not find any workarounds now.

### Other information

https://github.com/xamarin/xamarin-android/files/9953023/log.txt

**Comment by lambdageek** [comment]
Following up in https://github.com/xamarin/xamarin-android/issues/7532 it might be an issue with how XA calls `mono_runtime_invoke` on a thread that's not attached to the mono runtime.

**Comment by SamMonoRT** [comment]
Should be fixed via PR associated with https://github.com/xamarin/xamarin-android/issues/7532. Closing this issue.
