### ISSUE TITLE
Huge Breaking Issue in Net7 with MemberInfo equality

### ISSUE THREAD

**Issue by jogibear9988** [dotnet/runtime#78218]
### Description

If you compare 2 Memberinfos in Net7 from a Class and a Base they are equal in 7 but not in Previous Versions.
Cause of this my Database Mapping Framework did not work any more.
see issue: https://github.com/linq2db/linq2db/issues/3823

### Reproduction Steps

Try this code in Net6 it returns false, in 7 it returns true

    var i1 = typeof(a).GetProperty("c");
    var i2 = typeof(b).GetProperty("c");

    Console.WriteLine(i1 == i2);
    Console.ReadLine();

    class a
    {
        public string c { get; set; }
    }

    class b : a
    { }

### Expected behavior

Code should return false

### Actual behavior

returns tre

### Regression?

Yes

### Known Workarounds

None

**Comment by jogibear9988** [comment]
And if you do:

  Console.WriteLine(i1.ReflectedType == i2.ReflectedType);

this will return false... So memberinfos with different properties are handled as equal

**Comment by stephentoub** [comment]
cc: @buyaa-n, @jkotas

**Comment by jogibear9988** [comment]
Could be a huge problem with linq2db and fluent mapping. It depends on the correct behavior.

**Comment by jogibear9988** [comment]
And a question, will there be an Hotfix?

**Comment by jkotas** [comment]
Note that this reproduces only under debugger with hot-reload enabled. You can work around this by disabling hot-reload.

> Maybe a ReflectedType comparison is missing here: https://github.com/dotnet/runtime/blob/main/src/coreclr/System.Private.CoreLib/src/System/Reflection/RuntimePropertyInfo.cs#L59

ReflectedType comparison is missing in the Equals method. The CacheEquals method is fine.

**Comment by jogibear9988** [comment]
I've the issue also in VS when I disable Hotreload

**Comment by jogibear9988** [comment]
And also in release Mode.

**Comment by jogibear9988** [comment]
It don't appear to happen if you don't start from Visual Studio

**Comment by jogibear9988** [comment]
Now I understand why I don't saw this issue in my logfiles. I was looking why our App does not work in Net7 and thought this is the issue. But so it's not. It's only an issue while debugging. Now I need to look what's wrong without debugger...

**Comment by jogibear9988** [comment]
My fault, I deactivated here:
<img width="771" alt="image" src="https://user-images.githubusercontent.com/364896/201413643-b1b9ed5e-b0b7-4a03-8402-3474aa680a6a.png">
but you need to do here:
<img width="752" alt="image" src="https://user-images.githubusercontent.com/364896/201413694-0bca52b9-c7d7-4e86-a3d3-8beb16fe2abf.png">

**Comment by jogibear9988** [comment]
really? milestone 8.0.0?

**Comment by steveharter** [comment]
> really? milestone 8.0.0?

We always start with current (8.0 here) then backport.

**Comment by jogibear9988** [comment]
Can someone tell me, how I could disable hot reload? So I could still debug.

<img width="760" alt="image" src="https://user-images.githubusercontent.com/364896/201424097-e91f62a3-f758-4970-acac-23e236f70124.png">

the upper two switches don't seem to help, I still got the error.

**Comment by buyaa-n** [comment]
> We always start with current (8.0 here) then backport.

Tag @ericstj @jeffhandley for porting the fix to 7.0

**Comment by ericstj** [comment]
Seems reasonable to backport.  Regression from last release in a common scenario with non-trivial workaround.  Proceed with fix in main then open the backport pr and add template when ready.

**Comment by jogibear9988** [comment]
@jkotas 

> Note that this reproduces only under debugger with hot-reload enabled. You can work around this by disabling hot-reload.

can you tell me how to disable it when I start the app from within visual studio?

**Comment by jkotas** [comment]
I just checked - it is not possible to completely disable hot-reload when running under debugger. Parts of it are automatically enabled when debugger is attached. I am sorry that the workaround that I have suggested does not work.

**Comment by jogibear9988** [comment]
@jkotas 
maybe it should also be thought of? a way to disable hot reload?

**Comment by jkotas** [comment]
Yes, I agree: https://github.com/dotnet/runtime/issues/78540
