### ISSUE TITLE
ParamName of ArgumentNullException for new FileInfo is incorrect in .NET 7

### ISSUE THREAD

**Issue by vbreuss** [dotnet/runtime#78224]
### Description

The `ParamName` property of the `ArgumentNullException` thrown by the constructor `new System.IO.FileInfo(string)` changed from .NET 6 to .NET 7. Previously it was "fileName", now it changed to "originalPath", but the name of the string parameter did not change.

### Reproduction Steps

Using xUnit:

```csharp
	[Fact]
	public void ParamNameOfArgumentNullExceptionIsIncorrect()
	{
		var exception = Record.Exception(() => {
			_ = new FileInfo(null!);
		});
		
		var argumentNullException = Assert.IsType<ArgumentNullException>(exception);
		Assert.Equal("fileName", argumentNullException.ParamName);
	}
}
```

### Expected behavior

The ParamName should be the name of the provided parameter, which is "fileName" in [FileInfo(string)](https://github.com/dotnet/runtime/blob/v7.0.0/src/libraries/System.Private.CoreLib/src/System/IO/FileInfo.cs#L16)

### Actual behavior

The ParamName is set to "originalPath" as the parameter is named in the internal constructor.

### Regression?

Yes, it worked as expected until .NET 6.

### Known Workarounds

None

**Comment by Jozkee** [comment]
It was broken on https://github.com/dotnet/runtime/pull/65108.
@vbreuss would you like to send a PR to fix it?

**Comment by stephentoub** [comment]
I'm already fixing it :)
