### ISSUE TITLE
Access Violation assigning ref readonly field

### ISSUE THREAD

**Issue by deidian** [dotnet/runtime#78268]
### Description

Assigning a ref readonly field in a struct's constructor from a parameter being passed with in/ref modifiers causes an access violation that gets caught by the runtime and re-thrown as NullReferenceException when doing an implicit copy of the struct parameter.

### Reproduction Steps

The following console project can trigger it. Line `Struct = @struct;` will throw. Happens with both in and ref modifiers.

```cs
BigStruct bigStruct = default;
Test tst = new(123, ref bigStruct, 19232);
Console.WriteLine($"Value:{tst.ToString()}");

public readonly ref struct Test
{
    public readonly long Value;
    public readonly ref BigStruct Struct;
    public readonly nuint Value2;

    public Test(long value, ref BigStruct @struct, nuint value2)
    {
        Value = value;
        Struct = @struct;
        Value2 = value2;
    }

    public override string ToString() => $"{Value}//Struct//{Value2}";
}

public readonly struct BigStruct
{
    public readonly long Value;
    public readonly long Value2;
    public readonly long Value3;
    public readonly long Value4;
}
```

### Expected behavior

From a C# perspective 'NullReferenceException' shouldn't happen when doing the implicit copy.
There shouldn't be an implicit copy of the struct since it's immutable by definition (this is probably a Roslyn bug)

### Actual behavior

A NullReferenceException is thrown when doing an implicit copy of the struct.

### Configuration

.NET Version: 7.1.22.52112
Windows 11
Platform: x86 and x64

### Other information

This snippet is the IL generated for the constructor of test. From IL_0007 to IL_0013 it's the spurious implicit copy emitted by Roslyn.

```cil
IL_0000: ldarg.0
IL_0001: ldarg.1
IL_0002: stfld     int64 Test::Value
IL_0007: ldarg.0
IL_0008: ldfld     valuetype BigStruct& Test::Struct
IL_000D: ldarg.2
IL_000E: ldobj     BigStruct
IL_0013: stobj     BigStruct
IL_0018: ldarg.0
IL_0019: ldarg.3
IL_001A: stfld     native unsigned int Test::Value2
IL_001F: ret
```

And here a dissasembly of Test:.ctor

```as
; Assembly listing for method Test:.ctor(long,byref,ulong):this
; Emitting BLENDED_CODE for X64 CPU with AVX - Windows
; Tier-0 compilation
; MinOpts code
; rbp based frame
; partially interruptible

G_M000_IG01:                ;; offset=0000H
       55                   push     rbp
       C5F877               vzeroupper
       488BEC               mov      rbp, rsp
       48894D10             mov      bword ptr [rbp+10H], rcx
       48895518             mov      qword ptr [rbp+18H], rdx
       4C894520             mov      bword ptr [rbp+20H], r8
       4C894D28             mov      qword ptr [rbp+28H], r9

G_M000_IG02:                ;; offset=0017H
       488B4510             mov      rax, bword ptr [rbp+10H]
       488B5518             mov      rdx, qword ptr [rbp+18H]
       488910               mov      qword ptr [rax], rdx
       488B4510             mov      rax, bword ptr [rbp+10H]
       488B4008             mov      rax, bword ptr [rax+08H]
       488B5520             mov      rdx, bword ptr [rbp+20H]
       C5FE6F02             vmovdqu  ymm0, ymmword ptr[rdx]
       C5FE7F00             vmovdqu  ymmword ptr[rax], ymm0
       488B4510             mov      rax, bword ptr [rbp+10H]
       488B5528             mov      rdx, qword ptr [rbp+28H]
       48895010             mov      qword ptr [rax+10H], rdx

G_M000_IG03:                ;; offset=0042H
       C5F877               vzeroupper
       5D                   pop      rbp
       C3                   ret

; Total bytes of code 71
```

It's crashing because in the 2nd vmovdqu destination value is 0 crashing with Access Violation

**Comment by EgorBo** [comment]
Smaller repro:
```csharp
public readonly ref struct Test
{
    readonly ref long field;

    [MethodImpl(MethodImplOptions.NoInlining)]
    public Test(ref long s)
    {
        field = s;
    }
}
```
```
    .method public hidebysig specialname rtspecialname instance void .ctor (int64& s) cil managed noinlining 
    {
        .maxstack 8
        IL_0000: ldarg.0
        IL_0001: ldfld int64& Test::StructRefField
        IL_0006: ldarg.1
        IL_0007: ldind.i8
        IL_0008: stind.i8
        IL_0009: ret
    }
```
What it does here, basically, is - it tries to get value of `s` and save it to the location of `field` instead of what I suspect the author expects: saves reference to `s` to the field

**Comment by EgorBo** [comment]
@jaredpar should this be transferred to roslyn/csharplang to clarify the expected behavior (e.g. should it produce a warning or do we need an analyzer, etc)?

**Comment by stephentoub** [comment]
This, or at least a very close variation of it, was discussed in the C# language design.
https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-06-06.md#question-4-constructor-that-does-not-set-ref-field

**Comment by deidian** [comment]
@EgorBo yes, I was expecting that to happen since in a constructor it's a foregone conclusion that the ref field it's uninitialized and you aren't explicitly making room anywhere for a new copy. Or at least some error/warning flagging the potential non-sense if that was the case. 

Anyway, noted that I should always specify assign semantics when dealing with managed references.

**Comment by Joe4evr** [comment]
> Anyway, noted that I should always specify assign semantics when dealing with managed references.

Not like this is something that's ever changed. 🙃 

Honestly though, I'm surprised this doesn't produce a *compiler* error, something like `Cannot perform by-value assignment to a by-ref field`.

**Comment by JulieLeeMSFT** [comment]
Ping @jaredpar. 
> @jaredpar should this be transferred to roslyn/csharplang to clarify the expected behavior (e.g. should it produce a warning or do we need an analyzer, etc)?

**Comment by tannergooding** [comment]
> Honestly though, I'm surprised this doesn't produce a compiler error, something like Cannot perform by-value assignment to a by-ref storage location.

You've always been able to, that's how you mutate the contents of the `ref` :)

The compiler could probably warn that the `ref T field` has not been definitely assigned in the constructor.

------------

Also keep in mind with `ref` fields we have four possible refs:
* `ref T _field` - I can mutate the contents of the ref and change the address the reference points to
* `readonly ref T _field` - I can mutate the contents of the ref, but it always points to the same address
* `ref readonly T _field` - I cannot mutate the contents of the ref, but I can change the address the reference points to
* `readonly ref readonly T _field` - I cannot mutate the contents of the ref and it always points to the same address

**Comment by jaredpar** [comment]
> @jaredpar should this be transferred to roslyn/csharplang to clarify the expected behavior (e.g. should it produce a warning or do we need an analyzer, etc)?

As @stephentoub posted this was discussed in LDM and the decision was to not emit a diagnostic here.

**Comment by JulieLeeMSFT** [comment]
Closing as will not fix per LDM decision.

https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-06-06.md#question-4-constructor-that-does-not-set-ref-field

> As @stephentoub posted this was discussed in LDM and the decision was to not emit a diagnostic here.
