### ISSUE TITLE
Mono-flavored runtime never uses system libunwind

### ISSUE THREAD

**Issue by ayakael** [dotnet/runtime#78284]
### Description

Setting `--cmakeargs -DCLR_CMAKE_USE_SYSTEM_LIBUNWIND=TRUE` with coreclr-flavored runtime forces build to link to system libunwind. This switch doesn't seem to work for mono-flavored runtime, and no switch seems to exist in mono source code.

As reported in https://github.com/dotnet/source-build/issues/3020

/cc: @omajid 

### Reproduction Steps

Build mono-flavored runtime (via setting `p:PrimaryRuntimeFlavor=Mono`) and set `--cmakeargs -DCLR_CMAKE_USE_SYSTEM_LIBUNWIND=TRUE`

### Expected behavior

An `ldd` of `libcoreclr.so` should link to `libunwind.so`

### Actual behavior

There is no such link.

### Regression?

Never worked previously, confirmed with 6.0.111.

### Known Workarounds

No workarounds, other than using bundled libunwind.

### Configuration

.NET 7.0.100
Alpine Linux Edge
x64
Specific to mono-flavored runtime

**Comment by vargaz** [comment]
Mono doesn't use libunwind, neither the system nor the bundled one.

**Comment by ayakael** [comment]
Oh terrific! Good to know. @omajid We should then adjust `libunwind` test units on `regular-tests` accordingly to always skip on mono-flavored runtime. Beyond skipping certain RIDs, IDK if there's a mechanism for that.
