### ISSUE TITLE
Cross architecture CLRDEBUGINFO<host_os><host_arch> resource missing on windows coreclr

### ISSUE THREAD

**Issue by tommcdon** [dotnet/runtime#78282]
### Description

The Visual Studio debugger depends on the existence of the win32 resource `CLRDEBUGINFO<host_os><host_arch>` to support cross-platform/cross-architecture debugging.  This resource is missing on Windows ARM64 builds.

### Reproduction Steps

Attempt to debug a Windows ARM64 dump on X64 Visual Studio

### Expected behavior

Debug Managed, Debug Managed and Mix, and Debug Managed Memory should function as expected

### Actual behavior

When attempting to debug a .NET 6 or .NET 7 Windows ARM64 dump on X64 Visual Studio, the following error is displayed:

![image](https://user-images.githubusercontent.com/12520929/201500065-fd05726e-9fcb-4439-8851-ec56adffd89b.png)

### Regression?

No

### Known Workarounds

No known working in Visual Studio.  

### Configuration

Which version of .NET is the code running on? .NET 6/7
What OS and version, and what distro if applicable? Windows 
What is the architecture (x64, x86, ARM, ARM64)? ARM64 (app) and X64 (VS)
Do you know whether it is specific to that configuration? Yes
If you're using Blazor, which web browser(s) do you see this issue in? N/A

**Comment by mikem8361** [comment]
This cross-arch resource hasn't been needed until now for Windows arm64 support on Windows x64.  This will require two things:

1) Added the CLRDEBUGINFOWINDOWSARM64 resource to the Windows arm64 coreclr.dll
2) Generate the long-named DAC for arm64 on x64 (some like mscordaccore_amd64_arm64_8.0.1122.52304.dll
