### ISSUE TITLE
New custom attribute required to support C++ inline namespaces

### ISSUE THREAD

**Issue by tgani-msft** [dotnet/runtime#783]
Namespaces in .NET are not a first class concept in metadata but are implicit in type names. C++ inline namespaces are namespaces whose contents are implicitly available in the enclosing namespace. E.g.
```
namespace N {
  inline namespace I {
     ref class R {};
  }
}
```
The type `R` is simply name `N.I.R` in the metadata and upon import the C++ compiler does not know whether `I` is an inline namespace or not. To help the compiler import this correctly, an assembly-level custom attribute is emitted to the assembly for every inline namespace in the assembly. E.g., for the above we would emit

```
[CppInlineNamespace("N.I")];
```
To implement this, we need the attribute `System.Runtime.CompilerServices.CppInlineNamespaceAttribute` in System.Runtime.CompilerServices.VisualC.dll:

```C#
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Assembly, AllowMultiple=true)]
    public sealed class CppInlineNamespaceAttribute : Attribute
    {
        public CppInlineNamespaceAttribute(string dottedName);
    }
}
```

An explanation of how inline namespaces work is at https://foonathan.net/2018/11/inline-namespaces:

**Comment by terrajobst** [comment]
Is this only emitted for assemblies? Can this also be emitted for modules?

**Comment by tgani-msft** [comment]
In theory, yes, we could build a .netmodule though we don't officially support it.

An explanation of how inline namespaces work is at https://foonathan.net/2018/11/inline-namespaces/ 

We don't expect other compilers to do anything with this custom attribute, hence its location in VisualC.dll.

**Comment by terrajobst** [comment]
> An explanation of how inline namespaces work is at https://foonathan.net/2018/11/inline-namespaces/

Excellent, that helps!

**Comment by terrajobst** [comment]
* Looks good as proposed.
* @jkotas pointed out that you may no longer need it. If you don't, please close this issue. If you do, consider it approved.

```C#
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Assembly, AllowMultiple=true)]
    public sealed class CppInlineNamespaceAttribute : Attribute
    {
        public CppInlineNamespaceAttribute(string dottedName);
    }
}
```

**Comment by tgani** [comment]
We went with a different design based on @jkotas feedback. I'll close this issue.
