### ISSUE TITLE
JIT, SIMD Intrinsics: Recognize `~A & B` as `VectorXxx.AndNot(B, A)`

### ISSUE THREAD

**Issue by sunkin351** [dotnet/runtime#78303]
I love the new SIMD intrinsic surface area you guys have released with .NET 7, and would like to propose this improvement to JIT pattern recognition.

Although micro-benchmarks don't reveal any performance improvement on my CPU to use the `AndNot()` intrinsic over `~A & B`, it does to my knowledge result in 1 or more fewer instructions and thus benefits code size.

For reference, my CPU is a Ryzen 2700.

**Comment by SingleAccretion** [comment]
A good place for this reduction would be in morph, `fgOptimizeHWIntrinsic`.

**Comment by ErhanAtesoglu** [comment]
I'd be interested in this.  This is my first clrcore/jit issue but I think I already have the code done.

**Comment by EgorBo** [comment]
Closed by https://github.com/dotnet/runtime/pull/81993
