### ISSUE TITLE
String support in EnumerableTryGetNonEnumeratedCount and Enumerable.Count

### ISSUE THREAD

**Issue by NN---** [dotnet/runtime#78317]
### Description

System.String doesn't implement any collection interface: ICollection, IReadOnlyCollection, IReadOnlyList, IIListProvider.
This makes EnumerableTryGetNonEnumeratedCount and Enumerable.Count to work inefficienlty.

### Regression?

No

### Data

```cs
Enumerable.TryGetNonEnumeratedCount("abc", out var c);
Console.WriteLine(c); // 0

var count = Enumerable.Count("abc"); // Enumerates by character
```

**Comment by krwq** [comment]
I'd suggest to create a PR. You will need to add something similar to this but for string https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq/src/System/Linq/Count.cs#L23-L26

We can talk about this under the PR. There might be some perf investigation we'd ask you to do (we will point to any instructions if needed)

**Comment by NN---** [comment]
Hello @krwq,
Do you tend to add check for string type in LINQ methods or adding interface to string ?
Adding interface covers much more than optimizing a single method.

**Comment by eiriktsarpalis** [comment]
How common is it for strings to be used as Linq inputs? Adding an additional type check for string would incur a performance penalty for every input calling into that method. Have you considered just making that check yourself?
```C#
int count = -1;
if (source is string s) 
     count = s.Length;
else 
      source.TryGetNonEnumeratedCount(out count);
```

**Comment by stephentoub** [comment]
> How common is it for strings to be used as Linq inputs? Adding an additional type check for string would incur a performance penalty for every input calling into that method.

Yeah, enumerating the chars in strings via LINQ is not common enough to warrant negatively impacting every other use of this method.

**Comment by stephentoub** [comment]
(That said, it could be made to only add cost when T == char by guarding the string special-case with typeof(T) == typeof(char).)

**Comment by NN---** [comment]
Thanks for the answers and clarifications.

The issue has been created due to bad usage of Enumerable.Count for strings in our code base.
In addition I was trying to make a generic method validating empty sequence and found that it is not enough to implement for IReadOnlyCollection.

Btw, Java String class does implements CharSequence interface which is roughly equivalent to implementing IReadOnlyCollection<char>.

https://docs.oracle.com/javase/7/docs/api/java/lang/CharSequence.html
