### ISSUE TITLE
`Interop.CheckedAccess.cs` is unused

### ISSUE THREAD

**Issue by xtqqczze** [dotnet/runtime#78328]
[src/libraries/Common/src/Interop/Interop.CheckedAccess.cs](https://github.com/dotnet/runtime/blob/main/src/libraries/Common/src/Interop/Interop.CheckedAccess.cs)

**Comment by AaronRobinsonMSFT** [comment]
@stephentoub Any history on this file?

**Comment by xtqqczze** [comment]
Orphaned by https://github.com/dotnet/runtime/commit/02a9387410f7e621d27f190c95d5a522696f5e63#diff-55e380bb191bd077eccb78e9256e6953f0cd6a4ed6551da3a0c6303850f2021fL42

**Comment by AaronRobinsonMSFT** [comment]
@xtqqczze Thanks for doing the leg work on that. Care to submit a PR to remove the file?
