### ISSUE TITLE
[pgo] Assertion failed 'tree == stmt->GetRootNode()' during 'Optimize layout'

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#78322]
All the PGO pipelines are hitting this. Looks like a recent regression.

Example work item: https://dev.azure.com/dnceng-public/public/_build/results?buildId=81947&view=ms.vss-test-web.build-test-results-tab&runId=1709152&resultId=199727&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab

Log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-be5481c935334142b6/System.Text.RegularExpressions.Tests/1/console.638dc036.log?helixlogtype=result

```
Assert failure(PID 5888 [0x00001700], Thread: 4052 [0x0fd4]): Assertion failed 'tree == stmt->GetRootNode()' in 'System.Enum:TryParse[int](System.ReadOnlySpan`1[ushort],bool,bool,byref):bool' during 'Optimize layout' (IL size 514; hash 0xe1d7ebba; Tier1)

    File: D:\a\_work\1\s\src\coreclr\jit\fgdiagnostic.cpp Line: 3273
    Image: C:\h\w\A36D0914\p\dotnet.exe
```

cc @dotnet/jit-contrib

**Comment by JulieLeeMSFT** [comment]
@BruceForstall PTAL for an assert in Optimize Layout.

**Comment by BruceForstall** [comment]
Started failing on the 20221112.1 build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=81454&view=ms.vss-test-web.build-test-results-tab

**Comment by BruceForstall** [comment]
Looks like the regression is in this range: https://github.com/dotnet/runtime/compare/48908e57261f1a1c0b661d3bb1ba41a44c1cff26...5565135d21024ac2820e08d0a7aca3f2cb9d2b55

**Comment by BruceForstall** [comment]
This was exposed by https://github.com/dotnet/runtime/pull/77947
