### ISSUE TITLE
NativeAOT ignores PdbFile compiler option

### ISSUE THREAD

**Issue by dmex** [dotnet/runtime#78337]
Hello,

When compiling projects with `<PublishAot>true</PublishAot>` and `<PdbFile>abcd.pdb</PdbFile>` there are two invalid PDBs created in the directory and the wrong filename is added to the PE debug directory.

We use the PdbFile option to strip some of the directory path from the PDB filename. The option is documented here:
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/advanced#pdbfile

Duplicate PDBs (the first one is invalid):

![image](https://user-images.githubusercontent.com/1306177/201750907-49e893ec-6f6b-4161-9d55-ac8f72b619a3.png)

Adding <PublishAot>true</PublishAot> results in an incorrect filename in the PE debug directory:

![image](https://user-images.githubusercontent.com/1306177/201750484-9d9a7b3f-d045-4b0e-8bb7-fd6d2882defc.png)

Removing `<PublishAot>true</PublishAot>` results in the correct path:

![image](https://user-images.githubusercontent.com/1306177/201752916-03b3a1a1-4aaa-478b-bd43-6b8b73eefb1f.png)

### Reproduction Steps

1) Create project
2) Add `<PublishAot>true</PublishAot>` and `<PdbFile>abcd.pdb</PdbFile>`
3) Publish project

### Expected behavior

Value from PdbFile field in .csproj is used instead of the actual filename.

### Actual behavior

Real filename is used instead of the PdbFile option.

### Regression?

The PdbFile option works in all other versions of .NET except when using `<PublishAot>true</PublishAot>`

### Configuration

.NET 7.0 (x64)

**Comment by dmex** [comment]
`PublishAot` also ignores the alignment option:
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/advanced#filealignment

![image](https://user-images.githubusercontent.com/1306177/201763540-fa1ba72f-c813-4a9a-986d-7e5af7c264da.png)

`<PublishAot>true</PublishAot>` has the wrong FileAlignment:

![image](https://user-images.githubusercontent.com/1306177/201764075-ef260b33-ca44-4763-8844-c014151fc807.png)

`<PublishAot>false</PublishAot>` has the correct FileAlignment:

![image](https://user-images.githubusercontent.com/1306177/201763784-404d89a6-716b-478c-bc8d-b52b104b3190.png)

**Comment by jkotas** [comment]
These options are meant to control properties of managed binaries produced by C# compiler.

Controlling properties of the native binary produced by PublishAot is better done by passing extra arguments to the native linker, for example:
```
  <ItemGroup>
    <LinkerArg Include="/FILEALIGN:0x1000" />
  </ItemGroup>
```

**Comment by dmex** [comment]
> These options are meant to control properties of managed binaries

We've been some of these options for a few years. I couldn't find anything about compatibility with PublishAot and just assumed it uses the same properties.

> Controlling properties of the native binary produced by PublishAot is better done by passing extra arguments to the native linker

The LinkerArg option is exactly what we needed... thank you🥳

* `/PDBALTPATH:%_PDB%` correctly fixes the PdbFile name. 
* `/FILEALIGN:0x1000` correctly sets the file alignment. 

LinkerArg really needs to be documented. I tried using the same linker command line from our native C/C++ projects and everything works except for BREPRO. The deterministic hash incorrectly changes with each build when there are no source changes?

```
  <ItemGroup>
    <LinkerArg Include="/BREPRO /DEPENDENTLOADFLAG:0x800 /PDBALTPATH:%_PDB% /FILEALIGN:0x1000" />
  </ItemGroup>
```

**Comment by MichalStrehovsky** [comment]
Reproducible builds are tracked in https://github.com/dotnet/runtime/issues/73931#issuecomment-1214722679. Assuming you also specified `<Determinisitc>true</Deterministic>`, the output obj file should be the same. But then link.exe will mess it up. The VC++ doesn't yet have a switch that we can use (there's `/EXPERIMENTAL:DETERMINISTIC` but it didn't produce the same bits in my testing and the VC++ team said the work is not finished yet so I didn't poke into it more).

**Comment by dmex** [comment]
> it didn't produce the same bits in my testing

@MichalStrehovsky 

I'm not sure if it's the linker, IlCompiler or MSBuild messing up the deterministic build (or combination of all three). I've modified your ZeroSharp project and it's deterministic when compiled from the bat script. I'll update the other thread with the sample.

> Controlling properties of the native binary produced by PublishAot is better done by passing extra arguments to the native linker

@jkotas The LinkerArg flags resolved this issue so I'll close it. Thanks for the help :)
