### ISSUE TITLE
How to use the right certificate from a .NET Keystore for a .NET SSL application on linux

### ISSUE THREAD

**Issue by ramsubbaraoc** [dotnet/runtime#78369]
On Windows we have the concept of friendlyName(X509Certificate2.FriendlyName) and we could use that friendlyname to send the right one certificate for SSL Communication.

On Linux there is no concept of friendlyName for .NET API's and there could be multiple certificates in the keystore.Hence how do we send one right certificate during an SSL Communication?

**Comment by bartonjs** [comment]
The correct way is to just... know :smile:  Whether that be Thumbprint, a SHA-2-256-based thumbprint (`GetCertHash`), filtering by subject name/key usage/etc.

> BTW I'm wondering if we could add the FriendlyName to user stores since that is all custom anyway on Linux.

It... could... probably... be done with about 98% fidelity, but it's disproportionately expensive.

**Comment by ramsubbaraoc** [comment]
Thank you @wfurt @bartonjs

**Comment by rzikm** [comment]
Closing as answered
