### ISSUE TITLE
Idea for a convenient Replace

### ISSUE THREAD

**Issue by Zombach** [dotnet/runtime#78373]
I understand that this is just an concept. And my implementation leaves much to be desired. But I hope it will find a positive solution and will be finalized by specialists.
![image](https://user-images.githubusercontent.com/52016832/201875342-c6cc839e-6277-4a95-b027-350e28cf231b.png)
![image](https://user-images.githubusercontent.com/52016832/201875499-4b9e966a-7b2f-4cfa-abea-d166c1a0ff88.png)

**Comment by danmoseley** [comment]
Hi @Zombach . If you're proposing a new API please use the issue template for an API proposal.
