### ISSUE TITLE
[Analyzer] Make types declared in an executable internal

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#78388]
Various analyzers only pay attention to internal/private types and members, as changes to public API is visible.  For example, analyzers/fixers that find and remove dead code, or that recommend types without derivations be sealed.  Applications, rather than libraries, however, typically aren't referenced, and public types/members are likely mistakes, such that if the mistakes are corrected and the types/members have their visibility changed to internal/private, then other analyzers can start making recommendations for them.

The proposal is to add an analyzer/fixer that runs when a compilation's OutputKind is ConsoleApplication or WindowsApplication and that flags all public types, recommending they instead be made internal.

**Comment by bartonjs** [comment]
Looks good as proposed.

Given concerns with some of the templates (e.g. WinForms creating the skeleton for a new form type being default) we're recommending this analyzer be opt-in.  But we're probably easily convinced that it should be something else.

Category: Maintainability (?)
Visibility: None (off by default; might be nice if trimmer-style scenarios can flip it on by default)

**Comment by marek-safar** [comment]
> The proposal is to add an analyzer/fixer that runs when a compilation's OutputKind is ConsoleApplication or WindowsApplication and that flags all public types, recommending they instead be made internal.

Could the analyzer run when the output binary contains runnable entry-point?

**Comment by CollinAlpert** [comment]
Should this consider the OutputKind `WindowsRuntimeApplication` as well?

**Comment by KennethHoff** [comment]
I see a lot of the newly added analyzers are opt-in.

How do I as a developer enable them, and more importantly, find which ones to enable? I remember seeing a few good ones being added, so I worry that I'll forget about them and not benefit from them!

**Comment by CollinAlpert** [comment]
You can add an `.editorconfig` file to your solution and then select the severity of the rules you would like. For example:
`dotnet_diagnostic.CA1018.severity = warning`

[More information here](https://learn.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2022#set-rule-severity-in-an-editorconfig-file)

**Comment by cremor** [comment]
I assume it will also be enabled by setting `<AnalysisLevel>latest-all</AnalysisLevel>`?

**Comment by mavasani** [comment]
> I assume it will also be enabled by setting `<AnalysisLevel>latest-all</AnalysisLevel>`?

Indeed, that is correct.
