### ISSUE TITLE
Numerical < and == comparisons aren't fused into <=

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#78385]
Repro:
[SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8BiAOwFcAbS7YSmAAgBMBLXW+gWACgABABga8AjADoAcuXwwoLMLgDcPAQwDKAC2xQADgBlaogErlSGFtKXdlAZiEAmBgGEeAbx4MPDANoApFhgBxGFIZOQAKDABPbRgIADMwllMASmSAXXdPXlsRJAZgCAhKBgBZYQAeABUAPjDKhgA3bEpyGGSGAHd1GUZ6kAYASUl8YBkAITwYKuqGAF5qzM9PStEB3HEYAHNsMwaYMKaWtoZCQgYVtYAtGQgD5tbkyyXFoRzhPIKi0rtE00b747zF5LQ6tBjlBiCU7/I5zWaQp6eF6+fxBEKyMARaKxBJJDCpDLcJbZITvfKFYolazTOowh6dbqwc4MfpDKSjKATXBTGpoQaOCD4bRaNgQUgAeRiUB20FwVTQlTQn0oMyBRKWnlBjHK8JW1ygEERHheJNy5K+JRQvwwdMBC3VGtt4Ph/EsAF8gA)
```C#
#nullable disable
using System.Numerics;
using SharpLab.Runtime;

public class C
{
    [JitGeneric(typeof(int))]
    public static bool M1<T>(T value) where T : INumberBase<T> =>
        T.IsNegative(value) || T.IsZero(value);
    
    public static bool M2(int value) =>
        value < 0 || value == 0;
    
    [JitGeneric(typeof(int))]
    public static bool M3<T>(T value) where T : INumberBase<T>, IComparisonOperators<T,T,bool> =>
        value <= T.Zero;
    
    public static bool M4(int value) =>
        value <= 0;
}
```

Both M1 (generic) and M2 (non-generic) that do separate negative and zero checks produce:
```asm
    L0000: test ecx, ecx
    L0002: jl short L000c
    L0004: xor eax, eax
    L0006: test ecx, ecx
    L0008: sete al
    L000b: ret
    L000c: mov eax, 1
    L0011: ret
```
whereas both M3 (generic) and M4 (non-generic) that do combined negative and zero checks produce:
```asm
    L0000: xor eax, eax
    L0002: test ecx, ecx
    L0004: setle al
    L0007: ret
```
Similarly for `>=`.

The approved design of https://github.com/dotnet/runtime/pull/78222 was based on the idea that these would be the same, and thus the generic methods there could constrain T to just being `INumberBase<T>` and not require `IComparisonOperators<T,T,bool>` as well, but if it's going to remain producing worse code, we should reconsider.

cc: @EgorBo, @tannergooding

**Comment by EgorBo** [comment]
I have a branch that does this, it's just that I didn't see a lot of diffs from it and gave up, might give it a try again.
This might also be handled in optOptimizeBools. It looks similar to what we landed there recently by some community PR.

**Comment by EgorBo** [comment]
Similar to https://github.com/dotnet/runtime/issues/61940 in case if @drewnoakes is interested in extending that to this case

**Comment by drewnoakes** [comment]
Pinging @pedrobsaila who provided the implementation for that issue.

**Comment by EgorBo** [comment]
Ah, oops, pinged author of the issue instead of author of the PR 😄

**Comment by pedrobsaila** [comment]
Interested :) You can assign the issue to me
