### ISSUE TITLE
[API Proposal]: `OperatingSystem.IsWasi()`

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#78389]
### Background and motivation

Adding new RID for compiling Mono to [WebAssembly System Interface](https://wasi.dev/) platform.

Related discussion https://github.com/dotnet/runtime/issues/77780 and https://github.com/dotnet/runtime/pull/78376

### API Proposal

```diff
namespace System;

public sealed class OperatingSystem : ISerializable, ICloneable
{
+    public static bool IsWasi();
}
```

### API Usage

```csharp
if (OperatingSystem.IsWasi())
{
    throw new PlatformNotSupportedException();
}
```

### Alternative Designs

WASI is abreviation so it could be all upper case. 
```
public static bool IsWASI();
```

**Comment by teo-tsirpanis** [comment]
Is this ready for review? And it should be `IsWasi`; according to the guidelines acronyms are not capitalized.

**Comment by pavelsavara** [comment]
> Is this ready for review? And it should be `IsWasi`; according to the guidelines acronyms are not capitalized.

Okay, changed to `IsWasi`. It's ready.

**Comment by bartonjs** [comment]
Looks good as proposed.

Most of the other OperatingSystem.Is* methods have a -VersionAtLeast variant (with varying numbers of accepted integers), consider if WASI needs one (in the future).

```C#
namespace System;

public sealed partial class OperatingSystem : ISerializable, ICloneable
{
     public static bool IsWasi();
}
```
