### ISSUE TITLE
Probable wrong codegen or stack corruption in .NET 7.0.0 

### ISSUE THREAD

**Issue by ppekrol** [dotnet/runtime#78387]
### Description

We are in a process of migrating our codebase from latest .NET 6 to .NET 7.

During our initial tests we found an issue where we are getting a random value instead of expected 0 when reading from a pointer casted to a struct with explicit layout.

![image](https://user-images.githubusercontent.com/446555/201959846-96561f4d-76a9-4460-9a31-cb3d38773076.png)

If we access that in immediate window or evaluate that inline, we are getting expected value of 0. We think that somehow the generated code (even in Debug) is messing with the values.

### Reproduction Steps

1. Clone https://github.com/ppekrol/ravendb/tree/RavenDB-19531-repro
2. Put a brakepoint in JournalReader.ReadOneTransactionToDataFile method (line 129 - check the img from the description)
3. Start Tryouts project (in Debug)
4. The test that fails (one of many) is RavenDB_13291.CanMigrateTablesWithCounterWord (running it in the Tryouts)

### Expected behavior

`PageNumber` should be 0, we are doing `Memory.Set(0)` few lines above the code.

### Actual behavior

`PageNumber` is a random number

### Regression?

Yes, is working fine with latest .NET 6 (6.0.11)

### Known Workarounds

None

### Configuration

```
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  6.0.403 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

### Other information

I think it must be some codegen issue. No changes were made to that code, except of the migration to .NET 7. I've introduced variables in last `temp` commit https://github.com/ppekrol/ravendb/commit/038e526682343378adcac93e5214375f2a26b2be so it would be easier to show the problem to you. This branch `RavenDB-19531-repro` is based on https://github.com/ravendb/ravendb/tree/v5.4

**Comment by teo-tsirpanis** [comment]
The struct is explicit. https://github.com/ravendb/ravendb/blob/038e526682343378adcac93e5214375f2a26b2be/src/Voron/Impl/Journal/TransactionHeader.cs#L14-L28

**Comment by jakobbotsch** [comment]
I do see that `sizeof(TransactionHeaderPageInfo)` is 26 in .NET 6 but 32 in .NET 7. Would it explain the difference @ppekrol?

**Comment by jkotas** [comment]
The struct is explicit, but it is not blittable because of the `bool` field.

**Comment by jakobbotsch** [comment]
To sum up: to get consistent layout in all .NET versions for your code you need to make sure your structs are blittable (presumably by replacing `bool` fields with `byte` fields) and specify the packing explicitly.

**Comment by ppekrol** [comment]
I've added Pack = 1 and it solved the issue. Thank you for that! That is a huge breaking change in .NET 7 that I wasn't expecting :)

BTW, I had issues with `sizeof(TransactionHeaderPageInfo)` - couldn't understand how you are getting the 32, inside Immediate Window it is always 26, but after introduction of variable in code, it is 32. Very confusing. Not sure why is that.

What would be your recommendation regarding `bool` values? We are using them all over the place in similar fashion. Is it safe to use them with Pack or we should really consider moving to `byte` instead?

**Comment by redknightlois** [comment]
May I suggest that this case should have an analyzer built-in if not an outright compilation fail. We realized about this because around 25 tests out of 9103 were failing and would have crippling behavior for us as we are storing those structs to disk.

**Comment by jkotas** [comment]
> What would be your recommendation regarding bool values? 

I would recommend to either switching to `byte`, or enabling DisableRuntimeMarshalling for your assemblies that will make the structs with `bool` blittable and so you won't see differences between managed and unmanaged layouts like this one. There is a code analyzer and code fixer to help you with enabling DisableRuntimeMarshalling.

> inside Immediate Window it is always 26, but after introduction of variable in code, it is 32. Very confusing. Not sure why is that.

If you are still able to reproduce this, please report the issue using https://developercommunity.visualstudio.com
