### ISSUE TITLE
[Analyzer] Lift arrays of literals to static fields

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#78398]
We should consider adding an info-level analyzer that flags cases where arrays of literals are being allocated and recommend they instead be lifted to be stored in static readonly fields.  We'll need to experiment a bit to drive down false positive rates, e.g.
- Don't warn if the array is returned out of the method.
- Don't warn if the array is mutated by the method.
- Don't warn if the array is being stored / passed immediately as a `ReadOnlySpan<T>`.

Related:
https://github.com/dotnet/runtime/issues/33793

**Comment by steveberdy** [comment]
This definitely looks the same to me

**Comment by buyaa-n** [comment]
Yeah, doesn't see any difference, closing as duplicate
