### ISSUE TITLE
[API Proposal]: Random.Shuffle

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#78419]
### Background and motivation

In tests, in games, in simulations, it's common to want a shuffle operation (randomize the order), and it's non-trivial to do it well (or to remember how to do it well).

### API Proposal

```csharp
namespace System;

public class Random
{
    public void Shuffle<T>(Span<T> items);
}
```

### API Usage

```csharp
int[] items = ...;
Random.Shared.Shuffle(items);
```

**Comment by EgorBo** [comment]
Can it be a LINQ API?
I think I usually do `array.OrderBy(_ => random.Next())`

**Comment by hopperpl** [comment]
that is too slow for large sets... Durstenfeld is much better for very large sets

https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle

**Comment by vcsjones** [comment]
This got approved in https://github.com/dotnet/runtime/issues/73864.

**Comment by stephentoub** [comment]
> why `Random.Next.Shuffle(items);`? I would have expected eg `Random.Shared.Shuffle(items);`

Obviously a typo

**Comment by stephentoub** [comment]
> Can it be a LINQ API? I think I usually do array.OrderBy(_ => Random.Shared.Next())

Sounds like you have your LINQ API :)

If we were to separately add an IEnumerable-based API, I imagine it would just be implemented in terms of Random.Shuffle.

**Comment by vcsjones** [comment]
> stephentoub self-assigned this 5 minutes ago

@stephentoub not sure if saw, but I closed this since we approved that in the crypto API. Did you want to implement the `System.Random` portion of the API? Otherwise I am happy to do with along with the crypto one.

**Comment by stephentoub** [comment]
Thanks.  Go for it.
