### ISSUE TITLE
Debug symbols on Linux in Native AOT have lots of DWARF errors

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#78410]
Running `llmv-dwarfdump --verify` on symbols coming out of Native AOT on Linux produce hundreds or thousands of warnings and errors.

We should set up a test suite that runs dwarfdump on a test app and verifies at least the list of warnings/errors. Then, we can use that suite to drive down the issues to zero.

**Comment by filipnavara** [comment]
FWIW my branch in #77178 fares much better at this.

**Comment by agocke** [comment]
Yup, wouldn't be surprised -- I see a lot of problems here.

**Comment by MichalStrehovsky** [comment]
Duplicate of #72552?

**Comment by agocke** [comment]
Yes, closing as dup of #72552
