### ISSUE TITLE
VSMac Crash Reports Missing Frames

### ISSUE THREAD

**Issue by ryanching** [dotnet/runtime#78421]
VSMac crash reports are frequently missing frames. It seems to occur irrespective of exception type (we have hits on SigAbort, SigSegV, SigTerm, and SigBus). The issue should be diagnosable with diagnostic logging, but we need a way to enable diagnostic logging in the wild without negatively affecting performance of VSMac. I've attached an example SigAbort crash report with the missing frames issue. 

[CrashReport.txt](https://github.com/dotnet/runtime/files/10016136/CrashReport.txt)

**Comment by tommcdon** [comment]
@mikem8361

**Comment by mikem8361** [comment]
The problem seems to be fixed by the Ventura (13.x) fix in createdump.
