### ISSUE TITLE
[API Proposal]: Idea for a convenient Replace. area-system-runtime

### ISSUE THREAD

**Issue by Zombach** [dotnet/runtime#78423]
@dotnet/area-system-runtime
### Background and motivation

Idea for a convenient Replace. I understand that this is just an concept. And my implementation leaves much to be desired. But I hope it will find a positive solution and will be finalized by specialists. Improve both compactness and code readability.
Finally, it will be possible to change the character by index.

### API Proposal

```csharp
#My call string.Replace
public class String
{
    private string _value;

    public String() => _value = string.Empty;
    public String(string value) => _value = value;

    //Replace by index
    public string this[int index, char newChar]
    {
        get
        {
            if (index < 0 || index >= _value.Length) { throw new ArgumentOutOfRangeException("index"); }

            IEnumerable<char> chars = Array.Empty<char>();
            for (int i = 0; i < _value.Length; i++)
            {
                chars = chars.Append(i != index ? _value[i] : newChar);
            }

            return string.Concat(chars.Select(ch => ch));
        }
    }

    //Replace by char
    public string this[char oldChar, char newChar] => _value = _value.Replace(oldChar, newChar);
}
```
#Current call string.Replace
streing source = "Mu Text";
string value = source.Replace('u', 'y');

### API Usage

```csharp
// Replace by index
string source = "Mu message";
string value = source[1, 'y'];
//result value = "My message"

// Replace by char
string source2 = "Mu meccage";
string value2 = source2['c', 's'];
//result value2 = "My message"
```

### Alternative Designs

Move it to extensions System.String; But I think that this should be added inside the string class System.String

### Risks

Improvement needed. Since my skills are not enough to write at the same level as System.String.

**Comment by Zombach** [comment]
@dotnet/area-system-runtime

**Comment by dakersnar** [comment]
I don't think this is something we will be adding. 

If we were to expose this functionality, it would not be through an indexer, it would be through an API name like `ReplaceIndex` or something.

However, APIs additions on basic types (like string) have a high bar and have to add true value. Saving a few keystrokes is somewhat useful but it's low-impact and yet another thing customers have to learn. An example of the type of impact that would meet the bar for string would be saving customers from having to write an *algorithm*. Especially if it's logic they might need to implement frequently and which they're inclined to get wrong.

Given this, for now, I'm closing this proposal.
