### ISSUE TITLE
`Guid(ReadOnlySpan<Byte>)` could be optimized

### ISSUE THREAD

**Issue by xtqqczze** [dotnet/runtime#78440]
```csharp
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

Guid M0() => new Guid((ReadOnlySpan<byte>)new byte[]{0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10});
Guid M1() => Unsafe.ReadUnaligned<Guid>(ref MemoryMarshal.GetReference((ReadOnlySpan<byte>)new byte[]{0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10}));
```

```asm
M0()
    L0000: push rsi
    L0001: sub rsp, 0x40
    L0005: vzeroupper
    L0008: xor eax, eax
    L000a: mov [rsp+0x20], rax
    L000f: mov rsi, rdx
    L0012: mov rdx, 0x23dfaf408d8
    L001c: vxorps xmm0, xmm0, xmm0
    L0020: vmovupd [rsp+0x30], xmm0
    L0026: mov [rsp+0x20], rdx
    L002b: mov dword ptr [rsp+0x28], 0x10
    L0033: lea rdx, [rsp+0x20]
    L0038: lea rcx, [rsp+0x30]
    L003d: mov rax, 0x7ffce3d4d540
    L0047: call qword ptr [rax]
    L0049: vmovupd xmm0, [rsp+0x30]
    L004f: vmovupd [rsi], xmm0
    L0053: mov rax, rsi
    L0056: add rsp, 0x40
    L005a: pop rsi
    L005b: ret

M1()
    L0000: vzeroupper
    L0003: mov rax, 0x23dfaf408d8
    L000d: vmovupd xmm0, [rax]
    L0011: vmovupd [rdx], xmm0
    L0015: mov rax, rdx
    L0018: ret
```

[sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4a9Jq049+ggJI8ZEMfKhKV6mjQDiHXgBMGAWToAKAJQMAvAD4GLhgAdwZ7J3d3NhhsRwB5LkkAT1kxbC4AHmAkjBg/TyDQ7NyAbQBdAG86BDpyNAZqulJ6xoBmFpr0BpqAVg66JH6Adn6ADn6ATn7sfuB+sH7Hfph+gDMO8joAX08NanDnF3IvXwCAVS5cbFXBaNiL7EleAHMgxwyDv3dYVdcYfGgSRc2CguAAFo8WLYYBhojdYFwVJE7vFEik0plinkCiEGFjylUanVuk1+u0SV1Gn0SYMSSMSeMSVMSTMSXMSQsSUsSSsSetupsdrsaEA==)

**Comment by DaZombieKiller** [comment]
[Marking the constructor with AggressiveInlining seems to fix it](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCEBXAMy5il3YBLAHbYoATwDcNek1YAlDsIyD8MFgEllfCAAcAynwBugsDFzTajZi0XLV6gMIR8uwQBs+hqCbMWaNADiHIIAJgwAsnQAFACUDAC8AHwMwjAA7gzBYdHR8jDYoQDywu7i+rrYwgA8wOIYMEmxaZl1DQDaALoA3nQIdORoDH10pEMjAMzj/ejD/QCs03RISwDsSwAcSwCcS9hLwEtgS6FLMEtc0+R0AL6xltnhEeRxiSkAqsK42Ly2BaGfbDuQQAczSoWqjyS0VgXEiMHw0HEETEuAAFkCWIEYBh8rxYMIzLl8oUSmUKlVavVGs0Mgw2jAur1+oM5qMllM2bMRos2Ss2es2Vs2bs2fs2Yc2cc2ac2ec2Zc5tc7vcgiFQqRIqRXslUnTHtq8v8yeVKjUGU0WvTqUyRqyRmM2ZyRtyFkt+SNBSNhSNRSNxSNJSNpSNZSN5SNFX1larqDR2voMFAOGAMAAZbDiCAcDDRDNZnMAaREoRYhgAjhwYPYgbFOjRYIUIKVxAxcEmUxgsurSDRujQGIOGLooIIjNgGgxG6Fm2UGCIuwB9bCWIfD0fjyfT2et9HQJfAVdDkdjicwKf/HdttH7hiLsBHwcnzfn7ct62TxehR/r09by/vgyd4wD+z5nheTaAdSd5cKBG7gW+c5AYuIJwX+r4AUh0GLmiaEvhBM5QZ+gh4QhmGtshABWpH/pBWGfgA1pYA5Du0EQ4jeoQaK47jROxGCcdxujuEUugqM2AgAIIgiCsC4LgY4wFowLCCIIJ1ixg7EBM3ZhNqJLFC2FLmtSKTALEmkMP21BrmughwtEwAsGm1YggJDAAIQJAw5BIBZNm2YO1mBYFAlQBAmRWpJUAghwajKAAoggZhiYIzbRAARGw0FiFAmYMFw0C6eE+AcO29LnjACDYKmc6+R+5gMO4zYgiwGVDKIagQFwjmxLGIUMDcAQBYF9kMNEbCCBgzjCEYfANFAmi4GmU0YJ4CXCKEghVP5A3BQNQ4CYIuCJPCiISCi/AYu4fyFJCPbQuZP4DcQqzPUOQ1xiNtmLgxp3AO05DzJ072Dsup2TaIEgAAqjvgU2KQIBlaBgEykCtGBrTAG1bVUvWg3ewAQyIYjiLDqgI3NSP/CjvkY1jOPbcIjllsCRIoH1BP3sTUNk3DlPmLdXHKHTq3rZtTMs/obMwNEfn9SFX7/e0Gwg5Za6Lue3kA9savfRrcLa4DdB6wNKHK+Q5Cm4raIW6Q1uBYuggWxMDs/ZRFsoG7n03EAA).

**Comment by danmoseley** [comment]
Want to offer a PR for the latter?

**Comment by DaZombieKiller** [comment]
@danmoseley Sure! I've opened a PR for the change here: https://github.com/dotnet/runtime/pull/78446.
