### ISSUE TITLE
Des decryption result error on .net6,  It is normal in the  .netfx4.5 / .net5 environment

### ISSUE THREAD

**Issue by hkszlq** [dotnet/runtime#78445]
### Description

**The following code block gives inconsistent results when running under .netfx4.5 / .net5 and .net6**

var crypeTextBytes = Convert.FromBase64String("WIFk7WFebV270onYPjhzMQ==");
            using (var ms = new MemoryStream(crypeTextBytes))
            using (var tdesSer = new TripleDESCryptoServiceProvider() { Mode = CipherMode.ECB, Padding = PaddingMode.PKCS7 })
            using (var cs = new CryptoStream(ms, tdesSer.CreateDecryptor(Encoding.UTF8.GetBytes("123456789012345678901234"), null), CryptoStreamMode.Read))
            {
                var decrypeBytes = new byte[crypeTextBytes.Length];
                var bytesCount = cs.Read(decrypeBytes, 0, crypeTextBytes.Length);
                Console.WriteLine(Encoding.UTF8.GetString(decrypeBytes.Take(bytesCount).ToArray()));
            }

### Reproduction Steps

Choose a different runtime to run the following code

var crypeTextBytes = Convert.FromBase64String("WIFk7WFebV270onYPjhzMQ==");
            using (var ms = new MemoryStream(crypeTextBytes))
            using (var tdesSer = new TripleDESCryptoServiceProvider() { Mode = CipherMode.ECB, Padding = PaddingMode.PKCS7 })
            using (var cs = new CryptoStream(ms, tdesSer.CreateDecryptor(Encoding.UTF8.GetBytes("123456789012345678901234"), null), CryptoStreamMode.Read))
            {
                var decrypeBytes = new byte[crypeTextBytes.Length];
                var bytesCount = cs.Read(decrypeBytes, 0, crypeTextBytes.Length);
                Console.WriteLine(Encoding.UTF8.GetString(decrypeBytes.Take(bytesCount).ToArray()));
            }

### Expected behavior

 Console.WriteLine result should be:111111111111

### Actual behavior

11111111
net6 can only get 8 bit

### Regression?

.net5 and Fx4.5 is ok

### Configuration

.NET6
WINDOWS10,Linux
x64

**Comment by vcsjones** [comment]
This is a known behavioral change in .NET 6:

https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams

As noted in the document, `Read` is not guaranteed to read the number of requested bytes. The solution is to call `Read` until the desired number of bytes have been read, or, until there are no more bytes available to read from the stream (Read returns 0).

Your code should look something like this:

```C#
using System.Security.Cryptography;
using System.Text;

var crypeTextBytes = Convert.FromBase64String("WIFk7WFebV270onYPjhzMQ==");
using (var ms = new MemoryStream(crypeTextBytes))
using (var tdesSer = new TripleDESCryptoServiceProvider() { Mode = CipherMode.ECB, Padding = PaddingMode.PKCS7 })
using (var cs = new CryptoStream(ms, tdesSer.CreateDecryptor(Encoding.UTF8.GetBytes("123456789012345678901234"), null), CryptoStreamMode.Read))
{
    var decrypeBytes = new byte[crypeTextBytes.Length];
    int read;
    int total = 0;

    while ((read = cs.Read(decrypeBytes, total, crypeTextBytes.Length - total)) > 0)
    {
        total += read;
    }

    Console.WriteLine(Encoding.UTF8.GetString(decrypeBytes, 0, total));
}
```

That will produce the expected "111111111111".

Alternatively, for .NET 6+ you can use the new one-shot APIs that make this simpler and avoid the streams.

```C#
using System.Security.Cryptography;
using System.Text;

var crypeTextBytes = Convert.FromBase64String("WIFk7WFebV270onYPjhzMQ==");
using (var tdesSer = TripleDES.Create())
{
    tdesSer.Key = Encoding.UTF8.GetBytes("123456789012345678901234");
    byte[] result = tdesSer.DecryptEcb(crypeTextBytes, PaddingMode.PKCS7);
    string plaintext = Encoding.UTF8.GetString(result);
    Console.WriteLine(plaintext);
}
```

**Comment by hkszlq** [comment]
> Thank you very much. That's working normal after use your code 



> This is a known behavioral change in .NET 6:
> 
> https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams
> 
> As noted in the document, `Read` is not guaranteed to read the number of requested bytes. The solution is to call `Read` until the desired number of bytes have been read, or, until there are no more bytes available to read from the stream (Read returns 0).
> 
> Your code should look something like this:
> 
> ```cs
> using System.Security.Cryptography;
> using System.Text;
> 
> var crypeTextBytes = Convert.FromBase64String("WIFk7WFebV270onYPjhzMQ==");
> using (var ms = new MemoryStream(crypeTextBytes))
> using (var tdesSer = new TripleDESCryptoServiceProvider() { Mode = CipherMode.ECB, Padding = PaddingMode.PKCS7 })
> using (var cs = new CryptoStream(ms, tdesSer.CreateDecryptor(Encoding.UTF8.GetBytes("123456789012345678901234"), null), CryptoStreamMode.Read))
> {
>     var decrypeBytes = new byte[crypeTextBytes.Length];
>     int read;
>     int total = 0;
> 
>     while ((read = cs.Read(decrypeBytes, total, crypeTextBytes.Length - total)) > 0)
>     {
>         total += read;
>     }
> 
>     Console.WriteLine(Encoding.UTF8.GetString(decrypeBytes, 0, total));
> }
> ```
> 
> That will produce the expected "111111111111".
> 
> Alternatively, for .NET 6+ you can use the new one-shot APIs that make this simpler and avoid the streams.
> 
> ```cs
> using System.Security.Cryptography;
> using System.Text;
> 
> var crypeTextBytes = Convert.FromBase64String("WIFk7WFebV270onYPjhzMQ==");
> using (var tdesSer = TripleDES.Create())
> {
>     tdesSer.Key = Encoding.UTF8.GetBytes("123456789012345678901234");
>     byte[] result = tdesSer.DecryptEcb(crypeTextBytes, PaddingMode.PKCS7);
>     string plaintext = Encoding.UTF8.GetString(result);
>     Console.WriteLine(plaintext);
> }
> ```
