### ISSUE TITLE
AppDomain.CurrentDomain.GetAssemblies() and AssemblyLoadContexts being unloaded

### ISSUE THREAD

**Issue by simonferquel** [dotnet/runtime#78449]
### Description

AppDomain.CurrentDomain.GetAssemblies() does not filter out assemblies comming from AssemblyLoadContexts being unloaded.

We are working on various kinds of "code reload" scenarios, and in one of our experiments, we had an assembly loaded via a collectible AssemblyLoadContext that called AppDomain.CurrentDomain.GetAssemblies() on initialization to cache some type informations in a static field. We found out that when the ALC is unloaded and the assembly is reloaded in a new one, this initialization code would find duplicates of types. 
Further debugging showed that we were actually getting type informations for both current ALC, and the one we asked to Unload.

In our particular case, it lead to an ALC leak, as we were maintaining strong references to types coming from an unloading ALC in a static field.

### Reproduction Steps

- Create a collectible ALC
- Load an assembly within it (using any AssemblyLoadContext.Load* method)
- Call alc.Unload()
- Call AppDomain.CurrentDomain.GetAssemblies()

### Expected behavior

AppDomain.CurrentDomain.GetAssemblies() should filter out assemblies being unloaded, to avoid code paths that could lead to ALC leak.

### Actual behavior

If no GC happened between alc.Unload() and AppDomain.CurrentDomain.GetAssemblies(), GetAssemblies result will contain the assembly loaded in the unloaded ALC. Any usage of Activator.CreateInstance on a type from this assembly will correctly fail though, with an exception indicating its ALC is being unloaded.

### Regression?

Don't think so

### Known Workarounds

Workaround requires modifying the code being loaded to make it ALC aware. This is not feasible for us, as:
- We'll have cases where the loaded assembly will be built from user code outside our control
- The assembly being loaded is compiled for .net standard 2.1 to be able to load both with Mono and Core CLR.

### Configuration

- .Net 6 (should apply to .Net 7 as well)
- OS: Mac, Windows, Linux
- Arch: x64/arm64 - probably not os/architecture specific

**Comment by vitek-karas** [comment]
I understand the scenario and the concern, but there are other scenarios where such a change would be weird to say the least. It would be possible to have an instance of an object, which `Type` is from assembly which is not in the list returned by `AppDomain.CurrentDomain.GetAssemblies()`. That goes against what that API is supposed to do.

Especially `AppDomain` related code and assembly loading has changed enough from .NET Framework to .NET 6 that it's effectively impossible to guarantee compatibility of the exact same code on the two runtimes. The `AppDomain.GetAssemblies` is just one example (which is actually pretty close to the framework behavior) - there are other examples where the behavior is more noticeably different and if your plugin assembly uses one of those, it will likely break as well.

And finally, the unloading model in .NET 6 is cooperative - which means it assumes that the code which is being unloaded behaves reasonably. There are ways to make assemblies rooted forever - for example if the assembly registers its own handler for some global event (like `AppDomain.AssemblyResolve` for example) - then such assembly will never be unloaded.

**Comment by agocke** [comment]
Closing as not planned. As mentioned, assembly loading is fundamentally cooperative in .NET Core. If the code cannot be changed to be ALC-aware, unloading is not supported.
