### ISSUE TITLE
System.DirectoryServices.Protocols.LdapConnection has wrong argument check for anonymous authentication

### ISSUE THREAD

**Issue by GeertvanHorrik** [dotnet/runtime#78459]
### Description

When doing anonymous authentication, the service checks whether the user did not accidentally provide credentials anyway.

Correct check (line 79):

https://github.com/dotnet/runtime/blob/release/6.0/src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs#L79

Incorrect check (line 1037):

https://github.com/dotnet/runtime/blob/release/6.0/src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs#L1037

The last check on line 1037 is missing a `!` operator for the username check.

Maybe introduce `NetworkCredential.IsEmpty()` that can be re-used without issue and easily unit tested?

### Reproduction Steps

Try connecting to directory services with anonymous authentication.

### Expected behavior

Null / empty credentials should be accepted.

### Actual behavior

LdapConnection throws exception when binding.

### Configuration

.NET 6

**Comment by joperezr** [comment]
Great find @GeertvanHorrik! I wouldn't introduce an API just for these two uses, but if you think that is something worth pursuing, I would suggest opening a separate issue to track that. As for this specific bug, would you be willing to contribute a PR with the fix for this?

**Comment by GeertvanHorrik** [comment]
Thanks, I will try to create a PR. Need to read about the contribution guidelines first to see against what branch I should create the pull request against, but I think I can figure that out (it will be a fun learning experience).

**Comment by joperezr** [comment]
Awesome! [Here are our docs](https://github.com/dotnet/runtime/blob/main/CONTRIBUTING.md#contributing-changes) for how to contribute PRs as well as the suggested workflow for first-time contributors. That said, definitely feel free to reach out or ask any questions here if something is not mentioned or unclear over there.

**Comment by GeertvanHorrik** [comment]
Sorry for the delay, was caught up by end-of-year deadlines and holidays, but still planning to fix this. I got some issues getting this to build, but trying again now.

**Comment by buyaa-n** [comment]
Thank you @GeertvanHorrik, assigned to you

**Comment by GeertvanHorrik** [comment]
@buyaa-n / @joperezr I am having a bit of trouble getting the unit tests to run on my system. Could you please help me get started so I can finalize this issue / PR?

For more information about my request, see PR #80636

**Comment by buyaa-n** [comment]
Thank you @GeertvanHorrik for the fix, answered your question in the PR and merged it, closing!
