### ISSUE TITLE
[mono][debugger] MAUI Android crashing the app and the debugger

### ISSUE THREAD

**Issue by thaystg** [dotnet/runtime#78460]
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1633172

I was developing .NET MAUI App and used Android fro debugging. At some point debugger just stopped working and I startred to get this error message:

![image](https://user-images.githubusercontent.com/4503299/202182064-71367ae8-f26b-49b5-a112-8f8e74a9e2d7.png)

Found the cause. I was using a command, that accepts byte parameter, but XAML treates it as string, so the app just crashes and crash debugger as well. I thinks this still can be treated as bug because in such cases the debugger must not crash, but tell about exception in the code and gracefully close

**Comment by Ramttid** [comment]
Having the same error, very annoying

**Comment by thaystg** [comment]
Can you please provide a sample app where I can reproduce it?

**Comment by Ramttid** [comment]
I don't think this is only happens on a specific app, more like on (any) big app.
I fixed it (for now) by disabling XAML Hot Reload.

**Comment by thaystg** [comment]
I don't know how to reproduce it. I will close the issue.
