### ISSUE TITLE
Blazor C# Debugger doesn't hit C# breakpoint after calling async Javascript function

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#78475]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-C-Debugger-doesnt-hit-C-breakp/10186182)._

---
[severity:It's more difficult to complete my work]
I have a simple Blazor WASM app for which I have client debugging set up. It has been working fine for everything except calling async Javascript functions via JSRuntime.InvokeAsync(...). In the following screenshot, the first 2 breakpoints are hit, but the third is ignored. The code after the JS.InvokeAsync produces the expected results.

My Razor Page Setup:
![devenv_SUqmT5TsR0.png](https://aka.ms/dc/image?name=Bf97bc654deb6458d9080ad0a85cb5920638028386725225492_20221031-144433-devenv_SUqmT5TsR0.png&tid=f97bc654deb6458d9080ad0a85cb5920638028386725225492)

My Javascript:
![devenv_HlXXlz9eM2.png](https://aka.ms/dc/image?name=B9c15c08d662a4dddbacb728d87f36cf8638028397202953605_20221031-150159-devenv_HlXXlz9eM2.png&tid=9c15c08d662a4dddbacb728d87f36cf8638028397202953605)

I mostly use Chrome but have tested this on Microsoft Edge as well.

---
#### Eddy Fehr on 10/31/2022, 00:50 PM: 

(private comment, text removed)
#### Feedback Bot on 10/31/2022, 07:28 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Amplifier47** [comment]
These screenshots aren't working after vsfeedback moved the issue here, so I reposted them:
![devenv_HlXXlz9eM2](https://user-images.githubusercontent.com/83319963/202470608-6a6c1805-d15d-4c0d-b5e0-0bfe5fa82f59.png)
![devenv_SUqmT5TsR0](https://user-images.githubusercontent.com/83319963/202470612-b3c8c0a2-7d61-46b1-ae22-ea937c1bbce7.png)

**Comment by thaystg** [comment]
This is not very important, it's related to an specific Javascript function that refreshes the page.

**Comment by tommcdon** [comment]
Closing as low priority
