### ISSUE TITLE
[API Proposal]: Convert.TryFromHexString

### ISSUE THREAD

**Issue by Socolin** [dotnet/runtime#78472]
### Background and motivation

`Convert.FromHexString("not-hex");` is throwing a `System.FormatException` when input string is not a valid hex.

Like `Convert.TryFromBase64Chars()` `Convert.TryFromBase64String()` it would be nice to have `Convert.TryFromHexString();` when validating user input it's not great to be force to put a whole try/catch block arround for readability

```cs
byte[] myBytes;
try
{
	myBytes = Convert.FromHexString(inputString);
}
catch (FormatException ex)
{
	throw new InvalidXxx(ex);
}
``` 

I think It would be much nicer to do

```cs
if (!Convert.TryFromHexString(inputString, out var myBytes))
	throw new InvalidXxx(ex);
```

### API Proposal

```csharp
namespace System;

public class Convert
{
    public static bool TryFromHexString(string s, Span<byte> bytes, out int bytesWritten)
}
```

### API Usage

```cs
if (!Convert.TryFromHexString(inputString, out var myBytes))
	throw new InvalidXxx(ex);
```

### Alternative Designs

~`TryFromBase64String` returns a Span `bytes` instead with the number `bytesWritten`, so maybe it should be the same, but since the number of bytes are easy to guest with hex string (just divide string length by 2) I'm not sure it's useful~

```
public static bool TryFromHexString(string s, Span<byte> bytes, out int bytesWritten)
```

### Risks

I don't see any

**Comment by dakersnar** [comment]
This is a reasonable proposal. We would want to match existing patterns (the version called out in your Alternative Designs section), mostly because `Span<Byte>` doesn't need to be allocated. Can you update your proposal?

**Comment by Socolin** [comment]
> This is a reasonable proposal. We would want to match existing patterns (the version called out in your Alternative Designs section), mostly because `Span<Byte>` doesn't need to be allocated. Can you update your proposal?

I've updated my proposal

**Comment by terrajobst** [comment]
* We should align the shape with the existing `Try(From/To)Base64` API
    - If we accept a span to write to, we should accept a span as the source
    - For string, it makes sense to have a null-rejecting overload
* `TryFromHexString` *should* throw if destination is too small because `Try`-pattern are supposed to have a single failure mode
    - However, that's not what the existing `TryFromBase64` method does
    - Convenience wise, we believe it's worth to return `false` for both cases here

```C#
namespace System;

public partial class Convert
{
    public static bool TryFromHexString(string source, Span<byte> destination, out int bytesWritten);
    public static bool TryFromHexString(ReadOnlySpan<char> source, Span<byte> destination, out int bytesWritten);
    public static bool TryToHexString(ReadOnlySpan<byte> source, Span<char> destination, out int charsWritten);
}
```

**Comment by stephentoub** [comment]
> TryFromHexString should throw if destination is too small because Try-pattern are supposed to have a single failure mode However, that's not what the existing TryFromBase64 method does Convenience wise, we believe it's worth to return false for both cases here

Having a return value of false mean something other than "the destination buffer is too small" is a problem.  It means an algorithm like:
```C#
while (true)
{
    if (TryFromHexString(..., destination, ...) break;
    destination = new byte[destination.Length * 2];
}
```
will OOM if given invalid input.

**Comment by hrrrrustic** [comment]
What's the final decision here? Is one more API review meeting required?
I created a PR with no-throwing implementation, but changing it to throwing is easy

**Comment by terrajobst** [comment]
* `FromHexString`
    - We concluded we don't want the boolean because it either throws in unexpected ways or it collapses multiples errors which makes it non-trivial to recover.
    - We should use `OperationStatus` as the return value and drop the `Try` prefix
    - We should support incremental use by adding a consumed out parameter
* `ToHexString`
    - All bytes are valid, only error is destination is too small. Try-pattern is fine.

```C#
namespace System;

public partial class Convert
{
    public static OperationStatus FromHexString(string source, Span<byte> destination, out int charsConsumed, out int bytesWritten);
    public static OperationStatus FromHexString(ReadOnlySpan<char> source, Span<byte> destination, out int charsConsumed, out int bytesWritten);

    public static bool TryToHexString(ReadOnlySpan<byte> source, Span<char> destination, out int charsWritten);
}
```

**Comment by tannergooding** [comment]
This isn't going to make .NET 8. There is a pending PR, but its still in draft mode.

We'll be able to land it sometime after the repo opens for .NET 9 changes and the PR is no longer marked draft

**Comment by markusschaber** [comment]
Is there anything we can do to get the PR past "draft" status?

**Comment by tannergooding** [comment]
We're still locking down on .NET 8 cleanup and other issues.

The `main` branch is open for .NET 9 changes now and we should be getting to it "soon".

**Comment by markusschaber** [comment]
Thanks. I want it because of the possibility to provide a span as destination, this saves me a temporary array allocation and copying, at the non-cost of shorter code. :-)
