### ISSUE TITLE
.NET 7 extremely high memory usage

### ISSUE THREAD

**Issue by CyraxSputnik** [dotnet/runtime#78481]
Normally this PC only consumes this amount of RAM

![N](https://user-images.githubusercontent.com/43629243/202282217-06673bfa-8cfc-4861-8506-6c9aee258187.png)

This is after upgrading my app to .NET 7 and running it

![4](https://user-images.githubusercontent.com/43629243/202282598-010bda34-c75b-41fd-ab67-1d1af20079fd.png)

![10](https://user-images.githubusercontent.com/43629243/202282764-7e8b614b-991f-44fe-a35e-07ba76345162.png)

After going back to .NET 6 everything works normal

![11](https://user-images.githubusercontent.com/43629243/202282901-46c3a896-98f3-4e41-8ede-b42077a49c26.png)

**Comment by cap5lut** [comment]
Can you reproduce this on win10 or later?

**Comment by teo-tsirpanis** [comment]
.NET 7 does not support Windows 7 and 8.1. Unless the issue can reproduce on Windows 10+ it will be closed.

**Comment by HighPerfDotNet** [comment]
Just a suggestion in case Win 10 does not repro it, try it on Win Server 2012 R2 which is still supported and it's closer to Win 7/8.1 than Win 10.

**Comment by CyraxSputnik** [comment]
> Just a suggestion in case Win 10 does not repro it, try it on Win Server 2012 R2 which I believe is still supported (until end of 2023) and it's closer to Win 7/8.1 than Win 10.

I really tried, but in windows 11 everything works fine. We'll see with Windows Server. Thanks

**Comment by CyraxSputnik** [comment]
I tried again on Windows Server 2012, with a virtual machine, and unfortunately I couldn't reproduce it.

**Comment by teo-tsirpanis** [comment]
Thanks for the research, closing.
