### ISSUE TITLE
[API Proposal]: Random.NextTimeSpan

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#78488]
### Background and motivation

Random timespans are really useful for backoff algorithms.  An API should exist that can generate a timespan between two ranges.  If the generated timespan happens to be TimeOut.InfiniteTimeSpan, a new value should be selected.

### API Proposal

```csharp
namespace System

public class Random
{
    public TimeSpan NextTimeSpan(TimeSpan Min, TimeSpan Max);
    public TimeSpan NextTimeSpan(TimeSpan Max); // Generate a value between zero and max
}
```

### API Usage

```csharp

await Task.Delay(Random.NextTimeSpan(MaxDelay));

```

### Alternative Designs

An extension method on random that uses NextInt64 on ticks.

### Risks

This is a lesser use case than the currently implemented methods.

**Comment by omariom** [comment]
Why this?
```C#
Random.Shared.NextTimeSpan(TimeSpan.FromMinutes(0), TimeSpan.FromMinutes(5))
```
when we can already do this
```C#
TimeSpan.FromMinutes(Random.Shared.Next(0, 5))
```

**Comment by TonyValenti** [comment]
@omariom That's a good idea too!
