### ISSUE TITLE
Changed behaviour for PropertyInfo comparison between .net6 and .net7

### ISSUE THREAD

**Issue by alfattack** [dotnet/runtime#78487]
### Description

I wasn't able to find this change logged anywhere so apologies if I have missed something. 

Equality comparisons between `PropertyInfo` objects from classes which share properties of a base type produce different results in `.net6` versus `.net7`.

### Reproduction Steps

Given the classes:

``` C#
public class Vehicle
{
    public int Year { get; set; }
}

public class Car : Vehicle
{
}
```

I have observed different results when running the following on `.net6` versus `.net7`.

``` C#
var p1 = typeof(Car).GetProperty("Year");
var p2 = typeof(Vehicle).GetProperty("Year");

Console.WriteLine(p1 == p2);
Console.WriteLine(p1.Equals(p2));
Console.WriteLine(Equals(p1, p2));
```

### Expected behavior

In `.net6` this will output:

```
False
False
False
```

### Actual behavior

In `net7` this will output:

```
True
True
True
```

I would argue that this is preferrable, none the less it's still different.

**Comment by Wraith2** [comment]
Possibly related https://github.com/dotnet/runtime/issues/78218

**Comment by jkotas** [comment]
cc @buyaa-n

**Comment by alfattack** [comment]
I will also add that I'm observing different results in a .net7 test project. Here the result seems to be consistent with .net6.

``` C#
public class Vehicle
{
    public int Year { get; set; }
}

public class Car : Vehicle
{
}

public class Tests
{
    [Test]
    public void Test1()
    {
        var p1 = typeof(Car).GetProperty("Year") ?? throw new Exception();
        var p2 = typeof(Vehicle).GetProperty("Year") ?? throw new Exception();
        Assert.That(p1 != p2);
    }
}
```

@Wraith2  I missed this https://github.com/dotnet/runtime/issues/78218, I think they probably are the same issue.

**Comment by buyaa-n** [comment]
> I will also add that I'm observing different results in a .net7 test project

Right, that is because the bug introduced with hot reload related fix, therefore it is only happens in debug mode

> I think they probably are the same issue.

Yes, they are same and fixed, closing
