### ISSUE TITLE
Consolidate UTF8 character encoding implementations

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#78490]
We have two character encoding implementations for Utf8 <-> Utf16 <-> UCS4 in runtime; located at:

* `src/coreclr/pal/src/locale/{utf8,unicode}.cpp`
* `src/mono/mono/eglib/giconv.c`

The coreclr/pal implementation was ported from C# implementation in 2016: https://github.com/dotnet/coreclr/pull/3809. The C# implementation has diverged / improved since with spanified and intrinsified APIs so much that the similarities between the two are unrecognizable.

We can move eglib/giconv.c from mono to src/native/minipal, and create a neutral C header, so both coreclr pal and mono glib can rely on unified APIs. There are also some unused methods in these files (e.g. `g_utf8_to_ucs4_fast`) which can be cleaned up at the same time.

**Comment by jkotas** [comment]
Sounds good to me. Make sure that the shared implementation is at least as fast as the current one.

> UCS4

We should not need that.

**Comment by am11** [comment]
@jeffhandley, it is not related to System.Text.Encodings.Web. This is about consolidating native implementations of encoding used internally by coreclr and mono. Managed libraries don't consume these implementations.

**Comment by jeffhandley** [comment]
Ah; thanks, @am11.
