### ISSUE TITLE
Unable to break execution. The debugger is unable to stop this process as no CLR has been loaded for self contained and publish ready to run WPF app

### ISSUE THREAD

**Issue by okipol88** [dotnet/runtime#78507]
### Description

When trying to debug a published WPF app in .NET 6 I get a `Unable to break execution. The debugger is unable to stop this process as no CLR has been loaded.` message. This works fine when debugging (debug profile).

![image](https://user-images.githubusercontent.com/8424432/202497735-19fca99a-23d4-4cb4-bef1-548fafc46df7.png)

### Reproduction Steps

Create a WPF application with self contained and redy to run:

Deployment mode: self contained.
Produce single file.
Enable ReadyToRun compilation.

![image](https://user-images.githubusercontent.com/8424432/202495881-2e344040-f7d5-426f-9092-a854f8ee1ac8.png)

Run the application.
Attach to its process.
Break all.

Minimalistic example:
https://github.com/okipol88/WpfSelfContained

### Expected behavior

The app breaks its execution.

### Actual behavior

The app cannot break its execution.

### Configuration

.NET 7.0.1
VS 17.5 Preview (does not work from 17.3)
Windows 10 
x64

### Other information

No modules visible:
![image](https://user-images.githubusercontent.com/8424432/202497429-609c773b-4ad3-48c5-a78f-33c56a4fca7b.png)

Processes:
![image](https://user-images.githubusercontent.com/8424432/202497489-29f4e029-87ab-4436-ad64-6eb8d570333c.png)

Linked to:
https://github.com/dotnet/runtime/issues/76601
https://github.com/snoopwpf/snoopwpf/issues/378

**Comment by okipol88** [comment]
Hello @tommcdon,
Thank you for the reply.
I just posted the VS feedback item.

https://developercommunity.visualstudio.com/t/Unable-to-break-execution-The-debugger/10212489

**Comment by tommcdon** [comment]
Thank you @okipol88!  I'll go ahead and close this issue for now since this is a VS feedback item tracking the problem.  We will re-activate it if the issue turns out to be a bug in the runtime.
