### ISSUE TITLE
Unification of CoreCLR and Mono - AOT / NativeAOT

### ISSUE THREAD

**Issue by ChristianWeyer** [dotnet/runtime#78504]
> There should not be two different AOT stories:

AOT is tightly coupled with the core runtime. We have two core runtimes: CoreCLR and Mono, each comes with own variants of AOT.

Yes, we would love to have more unification between CoreCLR and Mono core runtimes, and we are actively working on it too.

_Originally posted by @jkotas in https://github.com/dotnet/runtime/issues/61231#issuecomment-964567292_

**Comment by ChristianWeyer** [comment]
Is there already an existing issue that covers the unification aspects? Especially wrt to AOT?

**Comment by danmoseley** [comment]
this seems like it should be labeled AOT -- those folks would be the best people to provide thoughts.

**Comment by teo-tsirpanis** [comment]
c.c. @MichalStrehovsky, @vargaz for thoughts.

**Comment by jkotas** [comment]
We have number of efforts, both small and large, to unify more of the runtime code. https://github.com/dotnet/runtime/issues/78498 opened earlier today is one of the many examples.

There is not much to say about some grand unification plan. It does not exist.

**Comment by MichalStrehovsky** [comment]
We unify where it makes sense. These unifications open new unification opportunities. It all started long time ago (there are pull requests as old as 2017, maybe older). There are no timelines or objectives - it's an ongoing process to improve engineering efficiency. Not sure it makes sense to keep a general issue like this open - we open issues (or just do the work) as we see opportunities.

**Comment by ChristianWeyer** [comment]
Thanks, gentlemen!
