### ISSUE TITLE
XmlSerializer serializes objects without removing whitespace between XML tags.

### ISSUE THREAD

**Issue by mdmg92** [dotnet/runtime#78511]
### Description

Since dotnet/runtime 6.0.11 XmlSerializer serializes objects without removing whitespace between XML tags.

We generate an XML document and then a external service generates a signature based on this XML.

The verifiyng part of the signature then validates the signatures and fails due to this whitespaces.

This behavior is not present on runtime 6.0.10.

### Reproduction Steps

Here is a console application I used to verify the behavior

Program.cs
```csharp
using System.Text;
using System.Xml.Serialization;

var doc = new Document
{
    FIToFICstmrCdtTrf = new FIToFICustomerCreditTransferV10
    {
        MsgId = "MsgId"
    }
};

using (var stringWriter = new Utf8StringWriter())
{
    var serializer = new XmlSerializer(doc.GetType());
    serializer.Serialize(stringWriter, doc);
    Console.WriteLine(stringWriter.ToString());
}

public partial class Document 
{

    private FIToFICustomerCreditTransferV10 fIToFICstmrCdtTrfField;

    /// <remarks/>
    public FIToFICustomerCreditTransferV10 FIToFICstmrCdtTrf {
        get {
            return this.fIToFICstmrCdtTrfField;
        }
        set {
            this.fIToFICstmrCdtTrfField = value;
        }
    }
}

public partial class FIToFICustomerCreditTransferV10
{
    private string msgIdField;

    public string MsgId {
        get {
            return this.msgIdField;
        }
        set {
            this.msgIdField = value;
        }
    }
}

class Utf8StringWriter : StringWriter
{
    public override Encoding Encoding => Encoding.UTF8;
}
```

Dockerfile used to test for 6.0.11 runtime
```dockerfile
FROM mcr.microsoft.com/dotnet/runtime:6.0.11-alpine3.16 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["ConsoleApp1.csproj", "ConsoleApp1/"]
RUN dotnet restore "ConsoleApp1/ConsoleApp1.csproj"
COPY [".", "ConsoleApp1/"]
WORKDIR "/src/ConsoleApp1"
RUN dotnet build "ConsoleApp1.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ConsoleApp1.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ConsoleApp1.dll"]
```

### Expected behavior

```xml
<?xml version="1.0" encoding="utf-8"?><Document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><FIToFICstmrCdtTrf><MsgId>MsgId</MsgId></FIToFICstmrCdtTrf></Document>
```

### Actual behavior

```xml
<?xml version="1.0" encoding="utf-8"?>
<Document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <FIToFICstmrCdtTrf>
     <MsgId>MsgId</MsgId>
   </FIToFICstmrCdtTrf>
</Document>
```

### Regression?

It worked on version 6.0.10

### Configuration

Dotnet version: 6.0.11
OS: Windows 10
Architecture: x64

**Comment by am11** [comment]
Prior to .NET 6, XmlWriter used to indent the elements and emit readable output. It was a breaking change and undesirable one (based on the consumer feedback) so it was reverted in https://github.com/dotnet/runtime/pull/73731. 

This should produce the expected result on all versions (except `6.0.0`..`6.0.10`):
```diff
+using System;
+using System.IO;
 using System.Text;
+using System.Xml;
 using System.Xml.Serialization;
 
 var doc = new Document
@@ -10,9 +13,10 @@ var doc = new Document
 };
 
 using (var stringWriter = new Utf8StringWriter())
+using (var xmlWriter = XmlWriter.Create(stringWriter, new XmlWriterSettings { Indent = false }))
 {
     var serializer = new XmlSerializer(doc.GetType());
-    serializer.Serialize(stringWriter, doc);
+    serializer.Serialize(xmlWriter, doc);
     Console.WriteLine(stringWriter.ToString());
 }
```

**Comment by mdmg92** [comment]
> Prior to .NET 6, XmlWriter used to indent the elements and emit readable output. It was a breaking change and undesirable one (based on the consumer feedback) so it was reverted in #73731.
> 
> This should produce the expected result on all versions (except `6.0.0`..`6.0.10`):
> 
> ```diff
> +using System;
> +using System.IO;
>  using System.Text;
> +using System.Xml;
>  using System.Xml.Serialization;
>  
>  var doc = new Document
> @@ -10,9 +13,10 @@ var doc = new Document
>  };
>  
>  using (var stringWriter = new Utf8StringWriter())
> +using (var xmlWriter = XmlWriter.Create(stringWriter, new XmlWriterSettings { Indent = false }))
>  {
>      var serializer = new XmlSerializer(doc.GetType());
> -    serializer.Serialize(stringWriter, doc);
> +    serializer.Serialize(xmlWriter, doc);
>      Console.WriteLine(stringWriter.ToString());
>  }
> ```

Thanks for the quick reply. I will try the code snippet you shared
