### ISSUE TITLE
bool does not implement IParsable<TSelf>

### ISSUE THREAD

**Issue by znakeeye** [dotnet/runtime#78523]
### Description

I'm writing a parser and this one is quite problematic. For the most basic type, a `boolean`, the new [IParsable&lt;TSelf&gt;](https://learn.microsoft.com/en-us/dotnet/api/system.iparsable-1?view=net-7.0) interface is not available. This makes no sense.

I realize that there is little need for a `bool.Parse(string, IFormatProvider?)` but since the second parameter may be `null`, it would be a no-brainer to implement. See [Boolean.cs(228)](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Boolean.cs#L228). Just add the interface, and these methods:

```c#
public static bool Parse(string value, IFormatProvider? _) => Parse(value);
public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? _, [MaybeNullWhen(false)] out TSelf result)
{
    return TryParse(s, out result);
}
```

### Reproduction Steps

Running `VS 17.5` targeting `.NET 7.0`, simply create a console app with the code below.

```c#
internal class Program
{
    static void Main(string[] args)
    {
        Cast<int>("123");   // OK
        Cast<bool>("true"); // CS0315
    }

    public static TSelf Cast<TSelf>(string s) where TSelf : IParsable<TSelf> => TSelf.Parse(s, null);
}
```

### Expected behavior

`Boolean` implements `IParsable<TSelf>`, just like all other primitive types.

### Actual behavior

`Boolean` does not implement `IParsable<TSelf>`.

### Regression?

No

### Known Workarounds

Wherever a method expects `IParsable<T>` you can duplicate that method to handle `bool` specifically. E.g.:

```c#
internal class Program
{
    static void Main(string[] args)
    {
        Cast<int>("123");
        CastBool("true"); // CS0315
    }

    public static TSelf Cast<TSelf>(string s) where TSelf : IParsable<TSelf> => TSelf.Parse(s, null);
    public static bool CastBool(string s) => bool.Parse(s);
}
```

### Configuration

.NET 7.0
Windows 11 (x64)

### Other information

https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Boolean.cs#L24

**Comment by svick** [comment]
This is a subset of https://github.com/dotnet/runtime/issues/67388.

**Comment by znakeeye** [comment]
> This is a subset of #67388.

Ah, really cool. I want to see that feature in .NET 7.01 😄 

I guess my suggestion could _theoretically_ break once #67388 is shipped. Though, I would still argue that my bug report is valid. Not having this interface for booleans is painful.

**Comment by teo-tsirpanis** [comment]
> I want to see that feature in .NET 7.0[.]1
Not going to happen. Servicing releases do not get new APIs.

**Comment by rickbrew** [comment]
Yeah I just found myself needing `bool` support for `IFormattable` and `IParsable<bool>`. It already has the methods, it just doesn't specify the interfaces 🤔

**Comment by znakeeye** [comment]
Can we expect this to be fixed in .NET 8?

**Comment by tannergooding** [comment]
Depends on what API review says for the API.

**Comment by tannergooding** [comment]
Will have a PR up covering this and #78842 shortly
