### ISSUE TITLE
System.Runtime.AttributeTargets - does not list Record

### ISSUE THREAD

**Issue by sujayvsarma** [dotnet/runtime#78552]
### Description

The Enum `AttributeTargets` in `System.Runtime`, ref below, does not list the `Record` type. 
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/AttributeTargets.cs

### Reproduction Steps

Ref Description

### Expected behavior

`Record` type is listed in the Enum.

### Actual behavior

`Record` type is not listed in the Enum.

### Regression?

No

### Known Workarounds

None

### Configuration

System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.11\ref\net6.0\System.Runtime.dll

**Comment by ShreyasJejurkar** [comment]
Not sure do we even need record entry there, as records are just classes under the hood. And also not having a record in the enum list, does not break anything, you can still apply attributes that are allowed for classes on record types. 
Please check below sample code. 

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATABgLABQ2AjIWQYRsQJwAUARIDwbgIPv0CUA3OQNoDCArgGcALhAC2AXUoBmAASxIUACayAysP5KYAO2G1OPAILDhUAJbB+wmAFVBAQwDmMWsdMWrMACr2oz4YIAdLwANvaCgmxSRHLYsgIi4m7mltayILLJHtaEAN7kAL5AA==

**Comment by ShreyasJejurkar** [comment]
Thanks, @sujayvsarma for closing. 

But I wanted to confirm with @stephentoub that we don't need a unique entry for records in the `AttributeTargets` enum and so is my understanding! 😊

**Comment by sujayvsarma** [comment]
I agreed with your assessment @ShreyasJejurkar and hence closed it. For my purposes, I am happy I can apply a `class` scoped attribute to a `record`, though I cannot see purists accept that as a solution and might still want a value added to that Enum. ;-)
