### ISSUE TITLE
gcc fails to arch-cross-compile on GNU/Linux in NativeAOT .NET 7

### ISSUE THREAD

**Issue by WhiteBlackGoose** [dotnet/runtime#78559]
### Description

Getting an error
```
gcc : error : unrecognized command-line option '--target=aarch64-linux-gnu'
```
When trying to compile my app for ARM64 while being on x86 64bit laptop

### Reproduction Steps

1. `dotnet new console -n frog && cd frog`
2. `dotnet publish -p:PublishAot=true -p:SelfContained=true -r linux-arm64`

### Expected behavior

Compiles

### Actual behavior

Doesn't compile:
```
$ dotnet publish -p:PublishAot=true -p:SelfContained=true -r linux-arm64
MSBuild version 17.4.0+18d5aef85 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  frog -> /home/goose/sandbox-1668781319/frog/bin/Debug/net7.0/linux-arm64/frog.dll
  Generating native code
gcc : error : unrecognized command-line option '--target=aarch64-linux-gnu' [/home/goose/sandbox-1668781319/frog/frog.csproj]
/home/goose/programs/dotnet-folder/sdk/7.0.100/Sdks/Microsoft.DotNet.ILCompiler/build/Microsoft.NETCore.Native.targets(346,5): error MSB3073: The command ""gcc" "obj/Debug/net7.0/linux-arm64/native/frog.o" -o "bin/Debug/net7.0/linux-arm64/native/frog" /home/goose/.nuget/packages/runtime.linux-arm64.microsoft.dotnet.ilcompiler/7.0.0/sdk/libbootstrapper.a /home/goose/.nuget/packages/runtime.linux-arm64.microsoft.dotnet.ilcompiler/7.0.0/sdk/libRuntime.WorkstationGC.a /home/goose/.nuget/packages/runtime.linux-arm64.microsoft.dotnet.ilcompiler/7.0.0/framework/libSystem.Native.a /home/goose/.nuget/packages/runtime.linux-arm64.microsoft.dotnet.ilcompiler/7.0.0/framework/libSystem.Globalization.Native.a /home/goose/.nuget/packages/runtime.linux-arm64.microsoft.dotnet.ilcompiler/7.0.0/framework/libSystem.IO.Compression.Native.a /home/goose/.nuget/packages/runtime.linux-arm64.microsoft.dotnet.ilcompiler/7.0.0/framework/libSystem.Net.Security.Native.a /home/goose/.nuget/packages/runtime.linux-arm64.microsoft.dotnet.ilcompiler/7.0.0/framework/libSystem.Security.Cryptography.Native.OpenSsl.a --target=aarch64-linux-gnu -g -Wl,-rpath,'$ORIGIN' -Wl,--build-id=sha1 -Wl,--as-needed -pthread -lstdc++ -ldl -lm -lz -lrt -pie -Wl,-z,relro -Wl,-z,now -Wl,--discard-all -Wl,--gc-sections" exited with code 1. [/home/goose/sandbox-1668781319/frog/frog.csproj]
```

### Configuration

1. 7.0.100
2. debian 12 sid bookworm
3. x86 64-bit
4. gcc (Debian 12.2.0-9) 12.2.0
5. aarch64-linux-gnu-gcc (Debian 12.2.0-9) 12.2.0
6. No clang installed

**Comment by am11** [comment]
We haven't tested cross-compilation with gcc, so this is unsupported. We can add support for it. However, there are few things to consider:

* clang has multi targets support (and hence `-target`/`--target` options are supported), but gcc only has one main target for which it was built for. We don't check the compiler flavor when setting this option (which is a bug).
* user will need to install target specific gcc toolchain to be able to use gcc for cross compilation.

You can install clang (or a docker image) for the cross-compilation in the meantime.

**Comment by am11** [comment]
Yup, those instructions apply only to clang, because this argument is not supported on gcc: https://github.com/dotnet/runtime/blob/0eabf7f3b086d4be386241b994dbf5a00c6486f2/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Unix.targets#L91

**Comment by WhiteBlackGoose** [comment]
I see.
While we're at it, is there anything for OS X that has to be referenced? (I see only windows and linux mentioned in the instruction)

**Comment by am11** [comment]
macOS is not supported in .NET 7. It is only available in the daily builds of .NET 8. We can update the document. Basically only cross-architecture is supported on OSX (not linux to osx). For example on M1 machine (osx-arm64), we can use:

```sh
$ dotnet8 publish -p:PublishAot=true --arch x64
```
to cross-compile x64 binary.

**Comment by am11** [comment]
> Without cross-compilation it works though 🤔

Yes, for osx-x64 but osx-arm64 is only supported in .NET 8.

**Comment by WhiteBlackGoose** [comment]
Got it. Any reason why btw? It requires additional work or something else?

**Comment by WhiteBlackGoose** [comment]
Also, is arch-cross-compilation only available in .NET 8?

**Comment by am11** [comment]
osx-arm64 support was implemented in https://github.com/dotnet/runtime/pull/75264 (merged three days before the 7.0 RC1 release), and number of fixes went in main branch after that. Normally  new platform support PRs are not backported, when there was no time spent on testing during the development cycle.

> Also, is arch-cross-compilation only available in .NET 8?

Yes, because for OSX we only support cross-architecture compilation (and not cross-OS compilation), so it was not necessary when only one architecture was supported.

**Comment by WhiteBlackGoose** [comment]
I mean, what about other OS? Is there arch-cross-compilation for linux on .NET 7?

**Comment by am11** [comment]
Yes. On linux, cross-compilation is supported with clang only. Normal compilation is supported with both clang and gcc.

**Comment by WhiteBlackGoose** [comment]
Thanks, is there any specific instruction or should work out of the box? (trying to get through an issue issue right now with it)

**Comment by agocke** [comment]
Instructions are here https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/compiling.md#cross-architecture-compilation. They do require a "sysroot" that contains the arm64 toolchain, esp. glibc. I did have some success getting this to work on Ubuntu by pulling in arm64 packages, but I haven't written anything up yet.

**Comment by agocke** [comment]
Closing as answered
