### ISSUE TITLE
[.NET 6] BufferFileStreamStrategy fills GC Finalizer Queue

### ISSUE THREAD

**Issue by sharpSteff** [dotnet/runtime#78553]
### Description

In .NET 6, `BufferedFileStreamStrategy` lacks `GC.SuppressFinalize(this)` call, which leads to memory and performance degradation under heavy usage of buffered file streams.

For .NET 7 this issue is already fixed with #64741 by adding the `GC.SuppressFinalize(this)` to `BufferedFileStreamStrategy`. However, we are stuck with .NET 6 and I want Information about if there is a workaround for .NET 6 or plans to fix this issue there.

### Reproduction Steps

Create and close a lot of `FileStream` instances with `DefaultBufferSize`. In the reported scenario, the application has heavy usage of loading bitmaps as file streams using the default buffer size, and this exercises the `BufferedFileStreamStrategy`.

### Expected behavior

Memory and performance degradation should not occur under heavy usage of buffered file streams (using `DefaultBufferSize`).

### Actual behavior

Using dotMemory, high numbers of finalizer-queued `BufferedFileStreamStrategy` instances are observed. These high numbers trigger the GC more often than in .NET Core 3.1. This leads to overall performance degradation (in both memory and execution time).

### Regression?

Yes, from .NET Core 3.1.

### Known Workarounds

Using non-buffered file streams, but that would come with different penalties.

**Comment by adamsitnik** [comment]
@jeffhandley @stephentoub The fixes (#64997 and #65899) have been merged 10 months ago and proven to be stable. The question is whether it meets the backport bar?

**Comment by jeffhandley** [comment]
@sharpSteff Could you provide a little more context for how you encountered this, and how it affected your system? That could help us make the case for backporting to .NET 6 in a servicing release. I presume the _expected behavior_ and the _actual behavior_ observed in your application tell a compelling story. Thanks!

**Comment by sharpSteff** [comment]
@jeffhandley Sure. We discovered a memory leak when using System.Drawing.Common on Linux. Our app relies in certain use-cases heavily on bitmaps. I migrated to SharpSkia and verified with Jetbrains dotMemory.(https://www.jetbrains.com/help/dotmemory/Working_with_dotMemory_Command-Line_Profiler.html).
This happened on .NET Core 3.1.

After migrating to .NET 6 later on, I rechecked the memory with dotMemory and discovered high numbers of finalizer-queued BufferedFileStreamStrategy as described in #64741. 

These high numbers triggered the GC more often than in .NET Core 3.1 which results into slightly worse overall performance (memory and execution time)

**Comment by jeffhandley** [comment]
Thank you, @sharpSteff. I've updated the issue description to capture this context. We'll review this for servicing.

**Comment by jeffhandley** [comment]
@adamsitnik -- Can you please prepare the `release/6.0` backport PR? Looking at #64997, the backport might require merging changes from a couple different PRs. (See previous backport PR: #65766). Our next window for servicing checkins is January 10th through 16th.

**Comment by sharpSteff** [comment]
@jeffhandley Thanks for your effort! Looking forward to this!

**Comment by adamsitnik** [comment]
@jeffhandley I've created the backport PR (https://github.com/dotnet/runtime/pull/80439), adopted it to 6.0 branch, verified the fixes, applied the label and sent an email to Tactics.

**Comment by adamsitnik** [comment]
Backport has been merged (#80439), the fix will be part of 6.0.14.
