### ISSUE TITLE
[Telemetry] Sockets telemetry like "bytes-sent" is using wrong CounterType

### ISSUE THREAD

**Issue by rgueldenpfennig** [dotnet/runtime#78568]
## Description

The [SocketTelemetry](https://github.com/dotnet/runtime/blob/v7.0.0/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketsTelemetry.cs) class is only using [PollingCounter](https://github.com/dotnet/runtime/blob/v7.0.0/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/PollingCounter.cs) types to define event types like `bytes-sent` and `bytes-received`.

The `PollingCounter` type defines those events as `Mean` in the `CounterType` field of the `CounterPayload`.

## Expected behavior
I assume those socket based events should be declared as `IncrementingPollingCounter`  so that the `CounterType` will be `Sum` instead of `Mean` because the values are increasing over time only.

It should be the same as like the GC or exception events defined in [RuntimeEventSource](https://github.com/dotnet/runtime/blob/v7.0.0/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/RuntimeEventSource.cs) for example.

## Impact
Frameworks that depend on consuming diagnostic events use the event payload to distinguish the type of the underlying counter.

For example the Prometheus based library [prometheus-net](https://github.com/prometheus-net/prometheus-net/issues/387) is currently defining the mentioned events from the Socket telemetry as gauges (because of counter type `Mean`) instead of counters.

**Comment by MihaZupan** [comment]
@dotnet/dotnet-diag can you take a look at this one?

While I understand observations about how Prometheus behaves here, I'm not sure we want to change anything in the runtime.
(To my knowledge) we expose things as `IncrementingPollingCounter` when we want tooling to display it as a rate of change, and `PollingCounter` when we just want the current value, which may also be strictly increasing.
For example, we expose both "total" and "per-second" metrics in our [Http instrumentation](https://github.com/dotnet/runtime/blob/de005e5ea950f852df5befac7c06ae2f717bfc29/src/libraries/System.Net.Http/src/System/Net/Http/HttpTelemetry.AnyOS.cs#L11-L15), even though either could be derived from the other one. E.g. `PollingCounter("requests-started")` and `IncrementingPollingCounter("requests-started-rate")`.

The linked `RuntimeEventSource` also exposes some always-increasing stats as a `PollingCounter`:  https://github.com/dotnet/runtime/blob/d099f075e45d2aa6007a22b71b45a08758559f80/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/RuntimeEventSource.cs#L47-L48
@noahfalk I see you asked these ones to not be `Incremental-` in the PR that added them (https://github.com/dotnet/runtime/pull/36489#discussion_r425657591), I take it we still stand by this, or have we changed our minds?

cc: @sandersaares

**Comment by rgueldenpfennig** [comment]
Thanks for your feedback.

> In the case of Prometheus I would expect people who want the rate of change can apply the [rate()](https://prometheus.io/docs/prometheus/latest/querying/functions/#rate) PromQL function to get it. Getting it by default may have been nicer, but I wouldn't break compat to fix it unless the pain runs much deeper than I realize.

The problem herein is that it is not possible to distinguish between `PollingCounter` and `IncrementingPollingCounter` to decide if a Prometheus "counter" or "gauge" should be created as the equivalent when `PollingCounter` and `IncrementingPollingCounter`  are mixed up between representing values that either increase endlessly or are flexible.

Imo the only difference to decide would be the `CounterType` property of the payload - if not mixed up originally.

Currently the prometheus-net library is making that decision [here](https://github.com/prometheus-net/prometheus-net/blob/master/Prometheus/EventCounterAdapter.cs#L112-L138) where either `Increment` or `Mean` indicate to create a counter or gauge.

The `rate()` function can only be applied to counters. Gauges are not supported for that afaik. At least I could not get it working. For that reason I opened both issues.

Maybe I am missing something. Would there be any other indications to make that decision properly? I would really appreciate the opinion of @sandersaares before I make too much noise here 😀

**Comment by noahfalk** [comment]
> The problem herein is that it is not possible to distinguish between PollingCounter and IncrementingPollingCounter to decide if a Prometheus "counter" or "gauge" should be created as the equivalent when PollingCounter and IncrementingPollingCounter are mixed up between representing values that either increase endlessly or are flexible

I am expecting that we'd map all PollingCounters to a Gauge in Prometheus, including these networking counters. I recognize that is not ideal in this instance, but I am not anticipating Prometheus to special case individual counters by name to map them differently. 

> The rate() function can only be applied to counters. Gauges are not supported for that afaik. At least I could not get it working. For that reason I opened both issues.

Ah I wasn't aware Prometheus restricted it. How about [delta()](https://prometheus.io/docs/prometheus/latest/querying/functions/#delta) or [deriv()](https://prometheus.io/docs/prometheus/latest/querying/functions/#deriv) instead? According to the docs these are intended for use with Gauges and seem like they accomplish a similar task as rate().

**Comment by rgueldenpfennig** [comment]
> Ah I wasn't aware Prometheus restricted it. How about [delta()](https://prometheus.io/docs/prometheus/latest/querying/functions/#delta) or [deriv()](https://prometheus.io/docs/prometheus/latest/querying/functions/#deriv) instead? According to the docs these are intended for use with Gauges and seem like they accomplish a similar task as rate().

More or less those functions can be used as a workaround accordingly on what you want to achieve. But it's no replacement for rate(), irate() or increase() which can be used on counters only.

**Comment by MihaZupan** [comment]
Triage: Closing this as we're unlikely to change the implementation in runtime per https://github.com/dotnet/runtime/issues/78568#issuecomment-1321248164, https://github.com/dotnet/runtime/issues/78568#issuecomment-1321883570
