### ISSUE TITLE
[API Proposal]: System.String.TryGetChar(int offset, out char letter)

### ISSUE THREAD

**Issue by sretz** [dotnet/runtime#78570]
### Background and motivation

To check if the string is long enough and get the char in one operation, instead of checking the length then getting the char.

### API Proposal

```csharp
namespace System;

public class String
{
    public bool TryGetChar(int offset, out char letter)
    {
       ...
    }
}
```

### API Usage

```csharp
string text = "Text"
if (text.TryGetChar(3, out var letter) && letter == 't')
{
}
```

**Comment by dakersnar** [comment]
See https://github.com/dotnet/runtime/issues/78571#issuecomment-1435248913
