### ISSUE TITLE
[API Proposal]: <T>[].TryGetOffset(int offset, out <T> value)

### ISSUE THREAD

**Issue by sretz** [dotnet/runtime#78571]
### Background and motivation

To check if the array is long enough and get the value in one operation, instead of checking the length then getting the value.

### API Proposal

```csharp
namespace System;

public class Array<T>
{
    public bool TryGetOffset(int offset, out T value)
    {
       ...
    }
}
```

### API Usage

```csharp
var text = "Text".ToArray();
if (text.TryGetOffset(3, out var letter) && letter == 't')
{
}
```

**Comment by reflectronic** [comment]
You can do this using C# 11 pattern matching: 
```cs
if (text is [_, _, _, 't'])
```

**Comment by Zintom** [comment]
> You can do this using C# 11 pattern matching: 
> ```cs
> if (text is [_, _, _, 't'])
> ```
> 

All due respect, but this pattern is ugly and barely readable. I think the intent of the OP's post was to have a concise but _readable_ method.

**Comment by vcsjones** [comment]
If we do this on `{ReadOnly}Span<T>` then we can combine this with your proposal #78570.

That said, what exactly are the use cases for this where you frequently need to try getting an element at a specific index that checking `(span.Length > index ...` becomes very repetitive?


An example using `Span<T>`:

```C#
using System.Security.Cryptography;

string text = "test";

if (text.AsSpan().TryGetOffset(3, out char resultChar) && resultChar == 't')
{
    Console.WriteLine("found the T");
}

byte[] data = new byte[] { 0xB, 0x0, 0x0, 0xC };


if (data.AsSpan().TryGetOffset(3, out byte resultByte) && resultByte == 0xC)
{
    Console.WriteLine("found the 0x0C");
}

static class MemoryExtensions
{
    public static bool TryGetOffset<T>(this Span<T> span, int index, out T value) =>
        TryGetOffset((ReadOnlySpan<T>)span, index, out value);

    public static bool TryGetOffset<T>(this ReadOnlySpan<T> span, int index, out T value)
    {
        if (span.Length > index)
        {
            value = span[index];
            return true;
        }
        else
        {
            value = default(T);
            return false;
        }
    }
}
```

**Comment by sretz** [comment]
My main intent is speed and second readability. In a lot of code I write, there checking the length of an array or string, not a span, and if the array or string is long enough get the value at the offset and do some logic based upon what was there. In my samples it would have been better to have had a switch instead of an ==. I believe it would be faster to have the runtime check the length and get the value then having the client code check and then get the value when you need to check the length for each get.

**Comment by svick** [comment]
@sretz 

> My main intent is speed

Looking the [the generated code](https://sharplab.io/#v2:C4LghgzgtgPgAgRgGwAI4CYUGECwAoAb3xRLWRQCMB7KgGxQFkAKAYwAswAnAbQF0VgAUwAewAJQoAvAD4BI4ADoAMoIB2Ac2BsU0ySgAsKAGRG5o7gGZ+kvQHJgtgNz4AvkA===) for `text.Length >= 4 && text[3] == 't'`, I don't see how adding this method could improve performance further.

**Comment by Zintom** [comment]
> ```cs
>public bool TryGetOffset(int offset, out T value)
> ```

Should be annotated with the `NotNullWhen` nullable static analysis attribute:
> ```cs
>public bool TryGetOffset(int offset, [NotNullWhen(true)] out T value)
> ```

**Comment by dakersnar** [comment]
We don't see this as a common enough pattern _outside_ of loops to be worth supporting. And if this API were to be used _inside_ of a loop, checking the bounds with every index would be really inefficient, as it is preferable to check the entire range once outside of the loop. Closing for now.
