### ISSUE TITLE
[Analyzer] Use IndexOfAnyValues instead of inlined or cached array

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#78587]
https://github.com/dotnet/runtime/issues/68328 is adding a new caching mechanism for IndexOfAny, such that instead of:
```C#
private static readonly char[] s_values = new[] { ... }
...
int index = span.IndexOfAny(s_values);
```
you can write:
```C#
private static readonly IndexOfAnyValues<char> s_values = IndexOfAnyValues.Create(new[] { ... }); 
...
int index = span.IndexOfAny(s_values);
```

We should consider an info-level performance analyzer that will flag cases like that above or where IndexOfAny is being called with an inline array (e.g. `IndexOfAny(new[] { ... })`) (or with a string constant containing the characters), and recommend switching to use IndexOfAnyValues, ideally with a fixer to automatically make the change.

**Comment by stephentoub** [comment]
cc: @MihaZupan, @marklio

**Comment by bartonjs** [comment]
The analyzer looks good as proposed.

Category: Performance
Severity: Info (which may get lowered based on the amount of noise in testing/development)

**Comment by MihaZupan** [comment]
Marking as 8.0 given we're backporting it in https://github.com/dotnet/roslyn-analyzers/pull/6924
