### ISSUE TITLE
[Analyzer] Recommend string.ToLower{Invariant}().Contains/IndexOf/StartsWith("lowercasestring") be replaced by case-insensitive comparison

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#78606]
There's a significant amount of code that's apparently trying to perform case-insensitive comparisons by first lower-casing and then comparing against a lowercased string, e.g.
https://grep.app/search?q=.ToLower%28%29.Contains&filter[lang][0]=C%23
https://grep.app/search?q=.ToLower%28%29.IndexOf&filter[lang][0]=C%23
https://grep.app/search?q=.ToLower%28%29.StartsWith&filter[lang][0]=C%23
Less but still many for ToUpper with upper-case, e.g.
https://grep.app/search?q=.ToUpper%28%29.Contains&filter[lang][0]=C%23
https://grep.app/search?q=.ToUpper%28%29.IndexOf&filter[lang][0]=C%23
https://grep.app/search?q=.ToUpper%28%29.StartsWith&filter[lang][0]=C%23
and with the Invariant variations, e.g.
https://grep.app/search?q=.ToLowerInvariant%28%29.Contains&filter[lang][0]=C%23

We should write an analyzer that flags these patterns and recommends comparisons using a `StringComparison` instead.

Such analyzers will help avoid the allocations caused by ToLower/ToUpper calls. 

[Performance rules Category](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/performance-warnings)
[Severity = suggestion](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-options#severity-level)

**Comment by MichalPetryka** [comment]
Should the invariant variants be also changed?

**Comment by tarekgh** [comment]
CC @Youssef1313

**Comment by carlossanlop** [comment]
I'll work on this.

**Question**: Should we always recommend the same `StringComparison` value (for example, `InvariantCultureIngoreCase`), or would it be variable depending on the context of the user's environment? If the answer is the latter, where can I read about the different conditions that would change the suggested `StringComparison` value? @tarekgh @stephentoub 

Adding a quick table for myself, for easier reference:

|Actual|Suggestion|
|-|-|
|`str.ToLower().Contains(substr)`|`Contains(substr, StringComparison.Something)`|
|`str.ToUpper().Contains(substr)`|`Contains(substr, StringComparison.Something)`|
|`str.ToLower().IndexOf(substr)`|`str.IndexOf(substr, StringComparison.Something)`|
|`str.ToUpper().IndexOf(substr)`|`str.IndexOf(substr, StringComparison.Something)`|
|`str.ToLower().StartsWith(substr)`|`str.StartsWith(substr, StringComparison.Something)`|
|`str.ToUpper().StartsWith(substr)`|`str.StartsWith(substr, StringComparison.Something)`|

**Comment by tarekgh** [comment]
@carlossanlop `ToLower()/ToUpper()` you need to use `StringComparison.CurrentCultureIgnoreCase`. For `ToLowerInvariant()/ToUpperInvariant()` need to use StringComparison.InvariantCultureIgnoreCase`

**Comment by carlossanlop** [comment]
Thank @tarekgh.

Another question: For the `ToLower/ToUpper` methods that take a `CultureInfo` argument, how does the passed culture translate to a `StringComparison`? Or should I ignore it and keep using the rules you mentioned in your previous reply, like this?:

`str.ToLower(System.Globalization.CultureInfo.CurrentCulture).StartsWith(substr);` => `str.StartsWith(substr, StringComparison.CurrentCultureIgnoreCase)` 

`str.ToLowerInvariant(System.Globalization.CultureInfo.CurrentCulture).Contains(substr);` => `str.Contains(substr, StringComparison.InvariantCultureIgnoreCase)`

The `Contains`/`StartsWith`/`IndexOf` methods don't seem to have an overload that takes a `CultureInfo` object, so I'm not sure if those should be flagged.

**Comment by tarekgh** [comment]
This analyzer approval did not include the ToUpper/ToLower overloads that takes culture info. But it is possible we can include these cases too. Can use `CultureInfo.CompareInfo.IsPrefix/IndexOf` and pass the option `CompareOptions.IgnoreCase`. 

On a separate note, there is a comment at https://github.com/dotnet/runtime/issues/78606#issuecomment-1324151916 containing instructions that we should carefully consider, in case you haven't already reviewed it.

CC @stephentoub

**Comment by carlossanlop** [comment]
> there is a comment at [#78606 (comment)](https://github.com/dotnet/runtime/issues/78606#issuecomment-1324151916) containing instructions that we should carefully consider

Yep. I included them in my table.

**Comment by tarekgh** [comment]
Usually, users who are doing something like `a.ToLower().CompareTo(b)` they always have `b` in the lowercase form to compare against. But I see this is not guaranteed. I am still seeing the diagnostics is useful, but we may not provide a fixer for this case.

**Comment by mavasani** [comment]
Should we consider also detecting simple patterns across statements, such as below?

```csharp
var loweredStr = str.ToLower();
if (loweredStr.Contains(anotherStr))
```

We would need to check that we have exactly one reference to the intermediate temporary variable.

If yes, we already added another analyzer which implements a simple heuristic for detecting above patterns: https://github.com/dotnet/roslyn-analyzers/blob/main/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/PreferStringContainsOverIndexOfAnalyzer.cs. If not for v1, but feel it may be a worthwhile enhancement, you may also consider filing a tracking issue for this enhancement.
