### ISSUE TITLE
[Analyzer] Using StartsWith instead of IndexOf == 0

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#78608]
We should write an analyzer that flags uses of IndexOf that's comparing the resulting index to 0, e.g.
https://grep.app/search?q=%5C.IndexOf%5C%28.%2A%3F%5C%29%20%3D%3D%200&regexp=true&case=true&filter[lang][0]=C%23
Such use would be much better off with StartsWith, as IndexOf will search the entire string vs StartsWith which will only compare at the beginning.

[Performance rules Category](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/performance-warnings)
[Severity = suggestion](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-options#severity-level)

**Comment by MichalPetryka** [comment]
Same with Contains and `IndexOf != -1`/`IndexOf > -1`/`IndexOf >= 0`.

**Comment by stephentoub** [comment]
> Same with Contains and IndexOf != -1/IndexOf > -1/IndexOf >= 0.

That already exists:
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2249

**Comment by tarekgh** [comment]
CC @Youssef1313

**Comment by bartonjs** [comment]
The analyzer/fixer should identify both `a.IndexOf(b) == 0` to `a.StartsWith(b)` and `a.IndexOf(b) != 0` to `!a.StartsWith(b)`.  And generally apply for the overloads that take comparison options.


Category:Performance
Severity:Suggestion
