### ISSUE TITLE
[Analyzer] string.ToLower() == otherString.ToLower()

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#78607]
The right way to compare two strings in a case-insensitive manner is via a StringComparer/Comparison that specifies case-insensitivity.  But there's are many cases where code is using ToLower() on each string and then comparing those for equality, e.g.

- https://grep.app/search?q=%5C.ToLower%5C%28%5C%29%20%3D%3D%20%5Cw%2B%5C.ToLower%5C%28%5C%29&regexp=true&case=true&filter[lang][0]=C%23
- https://grep.app/search?q=%5C.ToUpper%5C%28%5C%29%20%3D%3D%20%5Cw%2B%5C.ToUpper%5C%28&regexp=true&case=true&filter[lang][0]=C%23
- https://grep.app/search?q=%5C.ToLower%5C%28%5C%29%5C.Equals%5C%28%5Cw%2B%5C.ToLower%5C%28%5C%29&regexp=true&case=true&filter[lang][0]=C%23
- https://grep.app/search?q=%5C.ToUpper%5C%28%5C%29%5C.Equals%5C%28%5Cw%2B%5C.ToUpper%5C%28%5C%29&regexp=true&case=true&filter[lang][0]=C%23

We should write an analyzer that flags such uses and recommends fixing them to use Equals with the appropriate comparison.

This analyzer should cover `ToUpper` too even if the usage is low for that. 

Such analyzers will help avoid the allocations caused by ToLower/ToUpper calls.

[Performance rules Category](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/performance-warnings)
[Severity = suggestion](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-options#severity-level)

**Comment by MichalPetryka** [comment]
Should the invariant variants be also changed?

**Comment by stephentoub** [comment]
The intent is all variations of this that make sense. That includes ToLower/UpperInvariant.

**Comment by tarekgh** [comment]
CC @Youssef1313

**Comment by bartonjs** [comment]
We should identify any of the equality cases with a string-case transformation

* a.ToLower() == b.ToLower()
* a.ToLower() == b.ToLowerInvariant()
* a.ToLower() == b
* And all of the above in reverse order, `!=`, and `.Equals`; as well as the ToUpper versions.

And replace them with the equivalent call to `.Equals(b, StringComparison.IgnoreCase)`

This should be merged into the same diagnostic ID as #78606 (if possible).

**Comment by MichalPetryka** [comment]
`a.ToLower() == b` is not safe to replace since that'd be false when b contains any upper case chars.

**Comment by tarekgh** [comment]
> a.ToLower() == b is not safe to replace since that'd be false when b contains any upper case chars.

I think it will be safe to do it if `b` is literal string.

**Comment by carlossanlop** [comment]
I'll work on this one next. It is closely related to my other one that's almost done: https://github.com/dotnet/runtime/issues/78606

**Comment by carlossanlop** [comment]
@tarekgh - 

For this analyzer, should I continue using the same rules I used in my [previous PR](https://github.com/dotnet/roslyn-analyzers/pull/6662)?:

- `StringComparison.InvariantCultureIgnoreCase` for ToLowerInvariant/ToUpperInvariant
- `StringComparison.CurrentCultureIgnoreCase` for ToLower/ToUpper

I ask because Jeremy's approval comment mentioned a non-existent comparison:

> And replace them with the equivalent call to .Equals(b, StringComparison.IgnoreCase)

But there's also `OrdinalIgnoreCase`, so I'm unsure.

**Comment by tarekgh** [comment]
You will use `StringComparison.InvariantCultureIgnoreCase` and `StringComparison.CurrentCultureIgnoreCase` as you indicated. ToUpper/ToLower is always linguistic operation. We don't provide any API does ToUpper/ToLower for ordinal cases.

**Comment by carlossanlop** [comment]
I submitted a PR to fix this: https://github.com/dotnet/roslyn-analyzers/pull/6720

@tarekgh question: If I have this comparison:

```cs
a.ToLower() == a.ToLowerInvariant()`
```

Am I right to assume that the substitution should be this?:

```cs
a.Equals(b, StringComparison.CurrentCultureIgnorecase)
```

My assumption is that `CurrentCulture` takes precedence over `InvariantCulture`. Is this correct?

**Comment by tarekgh** [comment]
@carlossanlop in such case we shouldn't provide a fix but only diagnostic telling this is can be optimized by using string comparison with ignore casing feature. We cannot know the intention of the caller if want to have the current culture or invariant casing at that time.
