### ISSUE TITLE
Non-deterministic behavior of Type.IsAssignableTo

### ISSUE THREAD

**Issue by burkenyo** [dotnet/runtime#78619]
### Description

There seems to be an inherent inconsistency in how IsAssignableTo works with unconstructed generic types.

### Reproduction Steps

Run this example:
```cs
using System.Numerics;

// case 1
Console.WriteLine(typeof(int).IsAssignableTo(typeof(INumberBase<>)));

// case 2
Console.WriteLine(typeof(int).IsAssignableTo(typeof(INumberBase<int>)));

// case 3
Console.WriteLine(typeof(BigInteger).IsAssignableTo(typeof(INumberBase<>)));

// case 4
Console.WriteLine(typeof(BigInteger).IsAssignableTo(typeof(INumberBase<BigInteger>)));
```

### Expected behavior

All four cases should output `true`, or cases 1 and 3 should output `false`.

### Actual behavior

Only case 3 outputs `false`.

### Known Workarounds

use `Type.GetInterface`, e.g:
```cs
typeof(BigInteger).GetInterface(typeof(INumberBase<>).Name) is not null
```

### Configuration

runtime: Microsoft.AspNetCore.App 7.0.0
OS: macOS 12.6
architecture: ARM64

**Comment by jkotas** [comment]
Note that reordering the tests will give you different answer. 

Try the following:
```
using System.Numerics;

// case 2
Console.WriteLine(typeof(int).IsAssignableTo(typeof(INumberBase<int>)));

// case 1
Console.WriteLine(typeof(int).IsAssignableTo(typeof(INumberBase<>)));

// case 4
Console.WriteLine(typeof(BigInteger).IsAssignableTo(typeof(INumberBase<BigInteger>)));

// case 3
Console.WriteLine(typeof(BigInteger).IsAssignableTo(typeof(INumberBase<>)));
```
It is going to print
```
True
False
True
False
```

**Comment by jkotas** [comment]
This is type loader bug introduced by https://github.com/dotnet/runtime/pull/54588

**Comment by jkotas** [comment]
cc @davidwrighton @trylek @mangod9

**Comment by burkenyo** [comment]
HI @jkotas, what is the “correct” behavior in case such as `.IsAssignableTo(typeof(INumberBase<>))`?

**Comment by davidwrighton** [comment]
The correct behavior is that uninstantiated generics are not AssignableTo.
