### ISSUE TITLE
Dereferencing before `null` checks

### ISSUE THREAD

**Issue by VasilievSerg** [dotnet/runtime#78634]
I found several strange code fragments: in all these fragments, references are dereferenced before they are checked for `null`. 
I'm not sure that all these code fragments have errors, but they look suspicious.

**DocumentSchemaValidator.cs** ([link to the sources](https://github.com/dotnet/runtime/blob/d099f075e45d2aa6007a22b71b45a08758559f80/src/libraries/System.Private.Xml/src/System/Xml/Dom/DocumentSchemaValidator.cs#L421))
```csharp
XmlSchemaAttribute schemaAttribute = (_defaultAttributes[i] as XmlSchemaAttribute)!;
attrQName = schemaAttribute.QualifiedName; // <=
Debug.Assert(schemaAttribute != null);     // <=
```

**XmlSerializationWriterILGen.cs** ([link to the sources](https://github.com/dotnet/runtime/blob/d099f075e45d2aa6007a22b71b45a08758559f80/src/libraries/System.Private.Xml/src/System/Xml/Serialization/XmlSerializationWriterILGen.cs#L2579))
```csharp
LocalBuilder local = initValue.ILG.DeclareOrGetLocal(localType, variableName);  // <=
if (initValue != null)  // <=      
{
  initValue.Load(local.LocalType);
  initValue.ILG.Stloc(local);
}
```

**ExpressionBinder.cs** ([link to the sources](https://github.com/dotnet/runtime/blob/d099f075e45d2aa6007a22b71b45a08758559f80/src/libraries/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/Semantics/ExpressionBinder.cs#L798))
```csharp
private static RuntimeBinderException BadOperatorTypesError(Expr pOperand1, Expr pOperand2)
{
  // This is a hack, but we need to store the operation somewhere... the first argument's as
  // good a place as any.
  string strOp = pOperand1.ErrorString; // <=

  Debug.Assert(pOperand1 != null); // <=
  Debug.Assert(pOperand1.Type != null);
  ....
}
```

**PipeCompletionCallbacks.cs** ([link to the sources](https://github.com/dotnet/runtime/blob/d099f075e45d2aa6007a22b71b45a08758559f80/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/PipeCompletionCallbacks.cs#L20))
```csharp
public void Execute()
{
    var count = _callbacks.Count; // <=
    if (count == 0)
    {
      return;
    }

    List<Exception>? exceptions = null;

    if (_callbacks != null) // <=
            ....
}
```

**Infer.cs** ([link to the sources](https://github.com/dotnet/runtime/blob/d099f075e45d2aa6007a22b71b45a08758559f80/src/libraries/System.Private.Xml/src/System/Xml/Schema/Inference/Infer.cs#L324))
```csharp
if (childURI.Length == 0) // <=
{
    xs = parentSchema;
    add = false;
}
else if (childURI != null && !_schemaSet!.Contains(childURI))  // <=
```

**MgmtConfigurationRecord.cs** ([link to the sources](https://github.com/dotnet/runtime/blob/d099f075e45d2aa6007a22b71b45a08758559f80/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/MgmtConfigurationRecord.cs#L341))
```csharp
internal ConfigurationSection FindImmediateParentSection(ConfigurationSection section)
{
    ConfigurationSection result = null;

    string configKey = section.SectionInformation.SectionName;
    SectionRecord sectionRecord = GetSectionRecord(configKey, false);
    if (sectionRecord.HasLocationInputs)
    {
        SectionInput input = sectionRecord.LastLocationInput; // <=
        Debug.Assert(input.HasResult, "input.HasResult");  // <=
        result = (ConfigurationSection)input.Result;
    }
    else
    {
        if (sectionRecord.HasIndirectLocationInputs)
        {
            Debug.Assert(IsLocationConfig, "Indirect location inputs exist only in location config record");
            SectionInput input = sectionRecord.LastIndirectLocationInput;
            Debug.Assert(input != null);
            Debug.Assert(input.HasResult, "input.HasResult");
            result = (ConfigurationSection)input.Result;
         }
         ....
    ....
}
```

**Comment by stephentoub** [comment]
> MgmtConfigurationRecord.cs ([link to the sources](https://github.com/dotnet/runtime/blob/d099f075e45d2aa6007a22b71b45a08758559f80/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/MgmtConfigurationRecord.cs#L341))

What's the issue in this one?  I'm not seeing it.

**Comment by VasilievSerg** [comment]
> What's the issue in this one? I'm not seeing it.

I should have given a more detailed explanation. I'm sorry.

It looks like the both `LastLocationInput` and `LastIndirectLocationInput` properties may return `null`. 

```csharp
internal SectionInput LastLocationInput => HasLocationInputs ? LocationInputs[LocationInputs.Count - 1] : null;
```
[Link to the sources](https://github.com/dotnet/runtime/blob/d099f075e45d2aa6007a22b71b45a08758559f80/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/SectionRecord.cs#L110)

```csharp
internal SectionInput LastIndirectLocationInput
  => HasIndirectLocationInputs ? IndirectLocationInputs[IndirectLocationInputs.Count - 1] : null;
```

[Link to the sources](https://github.com/dotnet/runtime/blob/d099f075e45d2aa6007a22b71b45a08758559f80/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/SectionRecord.cs#L121)

The value of `LastIndirectLocationInput` is assigned to the `input` variable. After the assignment, `input` is checked for `null`. After this the `HasResult` property is also checked:
```csharp
SectionInput input = sectionRecord.LastIndirectLocationInput;
Debug.Assert(input != null);
Debug.Assert(input.HasResult, "input.HasResult");
```

The value of the `LastLocalInput` is assigned to the `input` variable. `input` is also checked for the result (`HasResult`), but 
 is not checked for the `null` value:
```csharp
SectionInput input = sectionRecord.LastLocationInput;
// Debug.Assert(input != null) ?
Debug.Assert(input.HasResult, "input.HasResult");
```

It looks a little bit suspicious.

**Comment by stephentoub** [comment]
I see, thanks, you're pointing out the lack of consistency around the assert. We could add one to the top block but I don't think it's worth the churn.
