### ISSUE TITLE
Native AOT always produced warning about including the NuGet package in .NET 8

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#78647]
I don't strictly think a warning is necessary, but if we feel one would be helpful I would add it to the targets file for the runtime pack and condition it on TFM. If a different TFM is used from the one in which the package is installed -- produce the warning.

**Comment by jkotas** [comment]
> I don't strictly think a warning is necessary

I would be ok with deleting the warning for .NET 8. We added the warning to help people transition from the explicit package references to just using what comes with the SDK. Now that most early adopters have transitioned, the warning is very useful.

**Comment by am11** [comment]
https://github.com/dotnet/sdk/issues/28823

**Comment by agocke** [comment]
Closed as dup of https://github.com/dotnet/sdk/issues/28823
