### ISSUE TITLE
TypeLoadException in System.Security.Cryptography.Xml v7.0.0.0 for EncryptedData in .NET 4.8 project referencing .NET Standard 2.0 library

### ISSUE THREAD

**Issue by mike-loux-planview** [dotnet/runtime#78652]
### Description

Upgraded System.Security.Cryptography.Xml v5.0.0 to v7.0.0 in a .NET 4.8 project, and now when I try to access the `EncryptedData` class, I get the following error:
```
System.TypeLoadException: Could not load type 'System.Security.Cryptography.Xml.EncryptedData' from assembly 'System.Security.Cryptography.Xml, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
```
[Issue_System.Security.Cryptography.Xml.zip](https://github.com/dotnet/runtime/files/10060096/Issue_System.Security.Cryptography.Xml.zip)

### Reproduction Steps

* Open Visual Studio 2022
* Create a .NET 4.8 console app.
* Add a .NET Standard 2.0 class library
* In the library:
  * Reference the `System.Security.Cryptography.Xml` NuGet package v7.0.0.0 (this also occurs in 6.0.0.1, FWIW).
  * Create a public class with a single method.
  * In the method, new up an instance of `EncryptedData`
* In the console app:
  * Ensure the `<RestoreProjectStyle>PackageReference</RestoreProjectStyle>` line is added to the .csproj file so you don't have to reference the NuGet package explicitly here.
  * Reference the class library, above.
  * In Main, new up an instance of the test class, above, and attempt to invoke the single method.

### Expected behavior

Should not throw. 

### Actual behavior

I get the error mentioned in the description, above.
![image](https://user-images.githubusercontent.com/62146387/203145607-d4f96d17-8702-43fb-95d0-470b33d89531.png)

### Regression?

This works fine when using System.Security.Encryption.Xml v6.0.1 or lower.  As soon as you update to v7.0.0, BLAM.  

### Known Workarounds

Use v6.0.1 for now.  The vulnerability appears to have been patched, but you don't get the v7.0.0 benefits (if there are any).  

### Configuration

* Console app is running on .NET 4.8
* Class library referencing the package is against .NET Standard 2.0
* Windows 10 Enterprise Version 21H2 (OS Build 19044.2251)
* Architecture is x64
* This has been reproduced on 2 separate machines running (roughly) the same configuration. 

### Other information

When looking at the .dll file using ILSpy or dotPeek, the EncryptedData class does not seem to be there at all.

**Comment by bartonjs** [comment]
I assume we didn't catch it because the tests directly include a reference to System.Security.dll:  https://github.com/dotnet/runtime/blob/8171bd0ed6622b686ddc31a5a763548d6a6516f4/src/libraries/System.Security.Cryptography.Xml/tests/System.Security.Cryptography.Xml.Tests.csproj#L74-L76

**Comment by mike-loux-planview** [comment]
Seriously cool watching someone else's CI/CD in action.  Thanks for jumping on this so quickly, folks!  
How long does it typically take for a new package (pre-release or otherwise) to drop?  
This is obviously **_not_** critical, as we have a workaround, but I'm insanely curious.

**Comment by bartonjs** [comment]
> How long does it typically take for a new package (pre-release or otherwise) to drop?

The daily builds from .NET 8 should already be available, but might yank your package graph forward in complicated ways (it also might not, I'm just offering it as a thing to watch out for): 
https://github.com/dotnet/runtime/blob/main/docs/project/dogfooding.md#obtaining-daily-builds-of-nuget-packages

The official package update from the v7 line should be on NuGet in January.  We usually publish on Patch Tuesday, or close to it, so January 10th or thereabouts.

**Comment by mike-loux-planview** [comment]
> > How long does it typically take for a new package (pre-release or otherwise) to drop?
> 
> The daily builds from .NET 8 should already be available, but might yank your package graph forward in complicated ways (it also might not, I'm just offering it as a thing to watch out for): https://github.com/dotnet/runtime/blob/main/docs/project/dogfooding.md#obtaining-daily-builds-of-nuget-packages
> 
> The official package update from the v7 line should be on NuGet in January. We usually publish on Patch Tuesday, or close to it, so January 10th or thereabouts.

Cool.  I subscribed to the NuGet release RSS feed for this package - easy peasy.  https://www.nuget.org/packages/System.Security.Cryptography.Xml/atom.xml

**Comment by ViktorHofer** [comment]
> We should do a root cause analysis as to why APICompat (Package Validation) didn't catch this. I would have expected it to flag the removed types compared to last release. cc @ViktorHofer @smasher164

Will take a look. My guess is that the type forwards weren't followed because of references not being available during baseline package validation.

**Comment by ericstj** [comment]
Seems like we should have a "no reference" mode for type forward checks that will still do its best to make sure that the type is exposed.  Sure we can't follow the forward to compare the type but we could make sure the forward (or type def) was present.

**Comment by ericstj** [comment]
In this case looks like APICompat did catch it.  I submitted a PR to remove the suppressions that we no longer need.
