### ISSUE TITLE
Central event fired when a debugging breakpoint is hit and process pauses

### ISSUE THREAD

**Issue by vcarlucci** [dotnet/runtime#78659]
**Problem**
We have an application with several time supervision. When we want to debug the code, the application process stops. In this situation we want to have to stop also our timers to prevent unvanted timing collisions, what today is not possible.

This means, we want to pause our stopwatch objects when a breakpoint hit is entered as long as the code is not continuing automatically (example F5, stop code debugging and proceed). This is just one usecase example, there are multiple scenarios of course.

**Solution**
Feature of additional system debugging events:
A system event that can be used and monitored when a debugger breakpoint is hit. Another event can be used to detect if the code is being processed.

Example integration in case of a customer timer class, accessing this new feature called here *//Debugger.Is...*:

`
### class TimeExample
    public Stopwatch _timer = new Stopwatch();
    public TimeExample()
    {
      // Searching for something like this:
      Debugger.IsBreakpointHit += StartWait; <- Idea, something like a .NET system "Debugger" object
      Debugger.IsContinuing += EndWait; (F5, line by line debugging ended) <- Idea, something like a .NET system "Debugger" object
    }

    public void Start()
    {
      _timer.Restart(); // resets the time
      _timer.Start();
    }      
    private void StartWait(object sender, EventArgs e)
    {
      _timer.Stop();
    }
    private void EndWait(object sender, EventArgs e)
    {
      _timer.Start();
    }
  `

**Additional content**
I have a stackoverflow already about this topic: 
[stackoverflow](https://stackoverflow.com/questions/64207537/c-sharp-is-there-a-way-to-pause-a-stopwatch-when-during-debug-mode-a-breakpoint)

**Comment by philipag** [comment]
+1 Because without this it is very difficult to debug code which is timing dependent, or even debug non-timing dependent code while timing dependent tasks are running in other threads.

**Comment by vcarlucci** [comment]
@philipag in a generalized solution yes, but with my code suggestion it would be possible to design specific timer classes and use them according the debugging needs to each part individually.

**Comment by philipag** [comment]
@vcarlucci I meant +1 for your solution.

**Comment by vcarlucci** [comment]
@philipag ah ok 🙂

**Comment by tommcdon** [comment]
Hello @vcarlucci! Visual Studio has the ability to run expressions evaluations known as 'function evaluations' from the debugger.  The examples of running code when a breakpoint is hit would need to run from the debugger via an expression evaluation because the debugger stops all thread execution when a breakpoint is hit.  I suggestion opening a Visual Studio feedback item to suggest the feature.

**Comment by vcarlucci** [comment]
Hello @tommcdon thank you for the answer. Can you please share the correct repo for a VS feature suggestion? I could only find the VS code repo, but no Visual Studio.

**Comment by tommcdon** [comment]
Hi @vcarlucci!  Please take a look at [Report a problem with the Visual Studio product or installer](https://learn.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) and let me know if you run into any problems.

**Comment by vcarlucci** [comment]
@tommcdon 👍 Thanks!
