### ISSUE TITLE
Generic math WriteLittleEndian is slow

### ISSUE THREAD

**Issue by xqrzd** [dotnet/runtime#78662]
I was looking to replace some encoding methods with generic math and noticed generic math was quite a bit slower. .NET 7.0.0

|            Method |      Mean |     Error |    StdDev |   Gen0 | Allocated |
|------------------ |----------:|----------:|----------:|-------:|----------:|
|   TestEncodeInt32 | 0.0254 ns | 0.0038 ns | 0.0035 ns |      - |         - |
| TestEncodeGeneric | 6.7771 ns | 0.0764 ns | 0.0714 ns | 0.0029 |      24 B |

```csharp
[MemoryDiagnoser]
public class Tester
{
    private readonly int _value = new Random().Next();
    private readonly byte[] _dest = new byte[4];

    [Benchmark]
    public void TestEncodeInt32()
    {
        EncodeInt32(_dest, _value);
    }

    [Benchmark]
    public void TestEncodeGeneric()
    {
        EncodeGeneric(_dest, _value);
    }

    private static void EncodeInt32(Span<byte> destination, int value) =>
        BinaryPrimitives.WriteInt32LittleEndian(destination, value);

    private static void EncodeGeneric<T>(Span<byte> destination, T value) where T : IBinaryInteger<T> =>
        value.WriteLittleEndian(destination);
}
```

**Comment by DaZombieKiller** [comment]
I believe this is a duplicate of https://github.com/dotnet/runtime/issues/77969

**Comment by hez2010** [comment]
Use `value.TryWriteLittleEndian(destination, out _);` instead as a workaround.

**Comment by xqrzd** [comment]
> I believe this is a duplicate of #77969

Yep, thanks!
