### ISSUE TITLE
corerun does not use CORE_ROOT on Linux

### ISSUE THREAD

**Issue by hadibrais** [dotnet/runtime#7867]
According to the [documentation](https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/UsingCoreRun.md), corerun is supposed to check whether CORE_ROOT is defined to get the directory in which libcoreclr.so and the other CLR libraries reside. Note that it supports the -c switch for the same purpose.

By going through the source code of the Windows and macOS corerun, it seems that the Windows host checks for CORE_ROOT but the macOS one doesn't.

**Comment by danmosemsft** [comment]
As far as I can see it is read in corerun.cpp for all platforms now.
