### ISSUE TITLE
[API Proposal]: Change Console Startup Messages

### ISSUE THREAD

**Issue by jeremy-morren** [dotnet/runtime#78689]
### Background and motivation

The default `ConsoleLifetime` (which is the default for hosting) produces log messages which don't make sense for production.   The code is at https://github.com/dotnet/runtime/blob/dd0ec9471dde6b6740ae6d9b504b64dec190b438/src/libraries/Microsoft.Extensions.Hosting/src/Internal/ConsoleLifetime.cs#L79 In particular, the `Ctrl+C` only makes sense in Development (it is rather pointless to have that appear in logs from a Kubernetes pod, for example).  The only control is the `ConsoleLifetimeOptions.SuppressStatusMessages` field, but that still does not allow any custom log messages.

In particular, I have found only the `Hosting Environment` message is useful in a container (unless debugging), however this would obviously vary with use case.  

### API Proposal

A better way would be to provide custom `OnApplicationStarted` and `OnApplicationStopping` callbacks that would allow custom log messages.

```csharp
public class ConsoleLifetimeOptions 
{
    public bool SupressStatusMessages { get; set; } = false;
    public Action<IHostEnvironment, ILogger>? OnApplicationStarted { get; set; } = null;
    public Action<IHostEnvironment, ILogger>? OnApplicationStopping { get; set; } = null;
}
```

### API Usage

Example: An kubernetes application is shown below, with messages that would be useful to plot, e.g. for Pod lifetime.

```csharp

var builder = WebApplication.CreateBuilder(args);

builder.Services.Configure<ConsoleLifetimeOptions>(options =>
{
    options.SuppressStatusMessages = true;

    //GetCommitVersion obviously not shown
    options.OnApplicationStarted = (env, logger) =>
    {
        logger.LogInformation("Application started.  Host environment: {Environment}. Pod: {Pod}. Commit: {Commit}",
            env.EnvironmentName, Environment.GetEnvironmentVariable("Hostname"), GetCommitVersion());
    };
    options.OnApplicationStopping = (env, logger) =>
    {
        logger.LogInformation("Application stopping.  Pod: {Pod}. Commit: {Commit}",
            Environment.GetEnvironmentVariable("Hostname"), GetCommitVersion());
    };
});

```

**Comment by steveharter** [comment]
Instead of a new API, could this be done with a combination of `Options.SuppressStatusMessages` and `ApplicationLifetime.ApplicationStarted.Register` like the current [implementation](https://github.com/dotnet/runtime/blob/dd0ec9471dde6b6740ae6d9b504b64dec190b438/src/libraries/Microsoft.Extensions.Hosting/src/Internal/ConsoleLifetime.cs#L55-L60)?

**Comment by jeremy-morren** [comment]
The main problem is surfacing `IHostEnvironment` (and friends), which is required to print the `Environment` message.

The only way of doing this is ATM to write your own implementation of the `ConsoleLifetime` class, which isn't that difficult.

**Comment by ericstj** [comment]
> The main problem is surfacing IHostEnvironment (and friends), which is required to print the Environment message.
> The only way of doing this is ATM to write your own implementation of the ConsoleLifetime class, which isn't that difficult.

I don't think you need to do that.  You could just grab the IHostEnvironment off the [WebApplication](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.webapplication.environment?view=aspnetcore-7.0) or [HostApplicationBuilder](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.hostapplicationbuilder.environment?view=dotnet-plat-ext-7.0), pull it from the service collection with [GetRequiredService](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.serviceproviderserviceextensions.getrequiredservice?view=dotnet-plat-ext-7.0), or create a component that has it injected through DI.

Here's a sample:
```C#
var builder = WebApplication.CreateBuilder(args);
builder.Services.Configure<ConsoleLifetimeOptions>(options => options.SuppressStatusMessages = true);
var app = builder.Build();

var applicationLifetime = app.Services.GetRequiredService<IHostApplicationLifetime>();
applicationLifetime.ApplicationStarted.Register(() => 
{
    app.Logger.LogInformation("Hosting environment: {EnvName}", app.Environment.EnvironmentName);
    app.Logger.LogInformation("Content root path: {ContentRoot}", app.Environment.ContentRootPath);
});

app.MapGet("/", () => "Hello World!");

app.Run();
```

**Comment by ericstj** [comment]
Closing as a solution was provided.
