### ISSUE TITLE
Feature suggestion - Obfuscator

### ISSUE THREAD

**Issue by himanshukodwani** [dotnet/runtime#78687]
It would be great to have an obfuscator supported and developed by dot net foundation or at least having a fork of open-source project like "ConfuserEx" overlooked by the foundation.

**Comment by EgorBo** [comment]
.net already has a nice obfuscator - NativeAOT 😄

**Comment by Symbai** [comment]
> NativeAOT

Which only works for console or library projects. No idea if that is what @himanshukodwani is looking for.

**Comment by himanshukodwani** [comment]
NativeAOT is not an obfuscator and shouldn't be used as an obfuscator. It has a purpose of creating non framework dependent assemblies and has got plenty of limitations.
ConfuserEX is doing the job for me right now, with few hacks I am able to make it work on dot net 6 too but what it is lacking is a sincere and caring community support.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by jkotas** [comment]
> obfuscator supported and developed by dot net foundation or at least having a fork of open-source project like "ConfuserEx" overlooked by the foundation.

.NET foundation does not develop or overlook development of projects that joined .NET Foundation. The development of projects that joined .NET Foundation is fully controlled by their original owners. If you believe that an open source project like ConfuserEx would benefit from joining .NET Foundation, the given project issues tracker is the best place to discuss it.

We have no plans to develop any dedicated obfuscator in dotnet/runtime.
