### ISSUE TITLE
JIT: RBO still introduces data races

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#78713]
The same example as #62048 without the `Volatile` still has the data race when run with `DOTNET_JitNoCSE=1`. According to #75790 that is not going to be allowed.

**Comment by SingleAccretion** [comment]
Also linking #75916.

**Comment by jakobbotsch** [comment]
See https://github.com/dotnet/runtime/pull/78714#issuecomment-1324347664 for an example that shows that counting uses is not enough to solve the problem, we probably need to disallow duplicating `GTF_GLOB_REF` trees entirely.

**Comment by JulieLeeMSFT** [comment]
@markples PTAL.

**Comment by JulieLeeMSFT** [comment]
@jakobbotsch, PTAL.
