### ISSUE TITLE
FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly test is failing in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#78718]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=91029&view=ms.vss-test-web.build-test-results-tab&runId=1918218&resultId=189964&paneView=debug

Configuration: `net7.0-Linux-Release-arm64-CoreCLR_checked-(Alpine.314.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm64v8` & `net7.0-Linux-Debug-arm64-CoreCLR_checked-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8`

```
Assert.Equal() Failure
↓ (pos 4)
Expected: FileÃName.bat
Actual:   File?�Name.bat
↑ (pos 4)
   at System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly() in /_/src/libraries/System.Net.Http/tests/UnitTests/Headers/ContentDispositionHeaderValueTest.cs:line 211
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
```

```json
{
  "ErrorMessage": "Expected: FileÃName.bat",
  "BuildRetry": false
}
```

cc @dotnet/ncl 

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[91636](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91636)|dotnet/runtime|[System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91636&view=ms.vss-test-web.build-test-results-tab&runId=1930274&resultId=189242)|dotnet/runtime#78736|
|[91625](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91625)|dotnet/runtime|[System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91625&view=ms.vss-test-web.build-test-results-tab&runId=1929578&resultId=189489)|dotnet/runtime#78741|
|[91517](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91517)|dotnet/runtime|[System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91517&view=ms.vss-test-web.build-test-results-tab&runId=1927280&resultId=189944)|dotnet/runtime#78738|
|[91507](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91507)|dotnet/runtime|[System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91507&view=ms.vss-test-web.build-test-results-tab&runId=1927162&resultId=194779)|dotnet/runtime#78736|
|[91483](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91483)|dotnet/runtime|[System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91483&view=ms.vss-test-web.build-test-results-tab&runId=1926680&resultId=189864)|dotnet/runtime#78580|
|[91457](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91457)|dotnet/runtime|[System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91457&view=ms.vss-test-web.build-test-results-tab&runId=1926420&resultId=189419)|dotnet/runtime#78733|
|[91365](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91365)|dotnet/runtime|[System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91365&view=ms.vss-test-web.build-test-results-tab&runId=1924916&resultId=182432)||
|[91336](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91336)|dotnet/runtime|[System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91336&view=ms.vss-test-web.build-test-results-tab&runId=1924068&resultId=189263)|dotnet/runtime#78728|
|[91307](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91307)|dotnet/runtime|[System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91307&view=ms.vss-test-web.build-test-results-tab&runId=1923730&resultId=189199)||
|[91215](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91215)|dotnet/runtime|[System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91215&view=ms.vss-test-web.build-test-results-tab&runId=1922022&resultId=194374)|dotnet/runtime#78572|
|[91201](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91201)|dotnet/runtime|[System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91201&view=ms.vss-test-web.build-test-results-tab&runId=1921642&resultId=189370)|dotnet/runtime#78709|
|[91155](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91155)|dotnet/runtime|[System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91155&view=ms.vss-test-web.build-test-results-tab&runId=1921038&resultId=189444)|dotnet/runtime#78720|
|[90632](https://dev.azure.com/dnceng-public/public/_build/results?buildId=90632)|dotnet/runtime|[System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=90632&view=ms.vss-test-web.build-test-results-tab&runId=1920776&resultId=189856)|dotnet/runtime#78685|
|[91127](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91127)|dotnet/runtime|[System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91127&view=ms.vss-test-web.build-test-results-tab&runId=1919904&resultId=189277)|dotnet/runtime#78714|
|[91029](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91029)|dotnet/runtime|[System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91029&view=ms.vss-test-web.build-test-results-tab&runId=1918218&resultId=189964)|dotnet/runtime#78703|
|[90647](https://dev.azure.com/dnceng-public/public/_build/results?buildId=90647)|dotnet/runtime|[System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=90647&view=ms.vss-test-web.build-test-results-tab&runId=1918158&resultId=189218)|dotnet/runtime#77996|
|[91022](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91022)|dotnet/runtime|[System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91022&view=ms.vss-test-web.build-test-results-tab&runId=1918042&resultId=189954)|dotnet/runtime#78580|
|[91010](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91010)|dotnet/runtime|[System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91010&view=ms.vss-test-web.build-test-results-tab&runId=1917990&resultId=189261)|dotnet/runtime#78700|
|[90970](https://dev.azure.com/dnceng-public/public/_build/results?buildId=90970)|dotnet/runtime|[System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=90970&view=ms.vss-test-web.build-test-results-tab&runId=1916944&resultId=189841)|dotnet/runtime#78702|
|[90927](https://dev.azure.com/dnceng-public/public/_build/results?buildId=90927)|dotnet/runtime|[System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=90927&view=ms.vss-test-web.build-test-results-tab&runId=1915938&resultId=195069)|dotnet/runtime#78698|
|[90857](https://dev.azure.com/dnceng-public/public/_build/results?buildId=90857)|dotnet/runtime|[System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=90857&view=ms.vss-test-web.build-test-results-tab&runId=1915298&resultId=189582)|dotnet/runtime#78557|
|[90830](https://dev.azure.com/dnceng-public/public/_build/results?buildId=90830)|dotnet/runtime|[System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=90830&view=ms.vss-test-web.build-test-results-tab&runId=1914264&resultId=189408)|dotnet/runtime#78020|
|[90801](https://dev.azure.com/dnceng-public/public/_build/results?buildId=90801)|dotnet/runtime|[System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=90801&view=ms.vss-test-web.build-test-results-tab&runId=1913512&resultId=189701)|dotnet/runtime#78678|
|[90662](https://dev.azure.com/dnceng-public/public/_build/results?buildId=90662)|dotnet/runtime|[System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=90662&view=ms.vss-test-web.build-test-results-tab&runId=1909942&resultId=188742)||
|[90652](https://dev.azure.com/dnceng-public/public/_build/results?buildId=90652)|dotnet/runtime|[System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=90652&view=ms.vss-test-web.build-test-results-tab&runId=1909438&resultId=195056)|dotnet/runtime#78688|
|[90641](https://dev.azure.com/dnceng-public/public/_build/results?buildId=90641)|dotnet/runtime|[System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=90641&view=ms.vss-test-web.build-test-results-tab&runId=1909182&resultId=189512)||
|[90620](https://dev.azure.com/dnceng-public/public/_build/results?buildId=90620)|dotnet/runtime|[System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=90620&view=ms.vss-test-web.build-test-results-tab&runId=1908802&resultId=189979)||
|[90558](https://dev.azure.com/dnceng-public/public/_build/results?buildId=90558)|dotnet/runtime|[System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=90558&view=ms.vss-test-web.build-test-results-tab&runId=1908022&resultId=189625)|dotnet/runtime#78680|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|28|28|28|

**Comment by EgorBo** [comment]
It's being investigated in https://github.com/dotnet/runtime/pull/78709

**Comment by MihaZupan** [comment]
For reference: https://github.com/dotnet/runtime/pull/78660#issuecomment-1323769901

#78660 changed how we do encoding here and now we're seeing failures on checked arm64 builds.
