### ISSUE TITLE
[NativeAOT] System.Numerics.Vectors test fails to compile with an assert.

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#78717]
To repro - just build tests with chk runtime config (like `build.cmd clr+libs+libs.tests -rc Checked -lc Release /p:TestNativeAot=true`)

A more direct repro is to just compile one test: `"C:\naot02\runtime\artifacts\bin\coreclr\windows.x64.Checked\ilc-published\\ilc" @"C:\naot02\runtime\artifacts\obj\System.Numerics.Vectors.Tests\Release\net7.0\native\System.Numerics.Vectors.Tests.ilc.rsp`

The command fails with:

```
ILC: C:\naot02\runtime\src\coreclr\jit\hwintrinsic.cpp:564
ILC: Assertion failed 'genActualType(arg->gtType) == genActualType(argType)' in 'System.Numerics.Vector:Load[ulong](ulong):System.Numerics.Vector`1[ulong]' during 'Importation' (IL size 7; hash 0xfe953b2c; FullOpts)
```

**Comment by EgorBo** [comment]
I'll take a look, I think jit-diff currently hit the same assert

**Comment by sodiqjonovich** [comment]
Why is this bug?

**Comment by EgorBo** [comment]
`build.cmd clr+libs+libs.tests -rc Checked -lc Release /p:TestNativeAot=true`

This command seems to take a lot of time, still building for me.. (and consumes a lot of space). Is it possible to generate rsp for a specific libs tests without it?

**Comment by jkotas** [comment]
You can omit `+libs.tests` and instead go to the specific libraries/.../test directory and run `dotnet build /t:Test /p:TestNativeAot=true` there.
