### ISSUE TITLE
Fatal error. Internal CLR error. (0x80131506) or unexpected NullReferenceException in XElement.Attribute(XName)

### ISSUE THREAD

**Issue by appel1** [dotnet/runtime#78759]
### Description

In one of our internal tools we started to get unexpected NullReferenceExceptions in XElement.Attribute(XName) after switching from .NET 6.0 to .NET 7.0. 

It downloads a lot of XML files in parallel and loads them into XDocuments which are then traversed. 

Don't know if it is relevant but it is configured to use server gc. 
`<ServerGarbageCollection>true</ServerGarbageCollection>`

Sometimes it happens after a few minutes, other times it can take an hour or more. And every now and then it can process all files without crashing. 

### Reproduction Steps

Don't have any sample that can reproduce this and the code and data it process is private. 

### Expected behavior

No crash.

### Actual behavior

Unexpected NullReferenceExceptions, access violations and segfaults. 

So far we've had unexpected errors like this:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Xml.Linq.XElement.Attribute(XName name)
```

![image](https://user-images.githubusercontent.com/973314/203519228-65bb7475-a87e-4c8b-814a-53528f629668.png)

The code basically does this over and over again with multiple calls running concurrently on different streams:
```
var doc = XDocument.Load(stream);
var root = doc.Root;
foreach (var element in root.Elements())
{
  var attr1 = (int?)element.Attribute("Something");
  var attr2 = (int)element.Attribute("Other");

  ...
}
```

Or the process dies with this error:
Fatal error. Internal CLR error. (0x80131506)

On Linux we've also seen that might be related:
```
[3715361.236396] .NET Server GC[193449]: segfault at 8 ip 00007fab9722505c sp 00007fab8effde30 error 6 in libcoreclr.so[7fab96de7000+4e1000]
[3715361.236415] Code: a2 94 0f 00 c3 66 0f 1f 84 00 00 00 00 00 55 48 89 e5 40 84 ff 74 18 66 48 8d 3d 87 36 0c 00 66 66 48 e8 b7 0e 0a 00 48 8b 00 <f0> 83 48 08 40 48 8b 05 98 36 0c 00 48 8b 38 48 85 ff 74 09 48 8b
[3733590.684493] .NET Server GC[215602]: segfault at 8 ip 00007f596cde705c sp 00007f5964ab5e30 error 6 in libcoreclr.so[7f596c9a9000+4e1000]
[3733590.684510] Code: a2 94 0f 00 c3 66 0f 1f 84 00 00 00 00 00 55 48 89 e5 40 84 ff 74 18 66 48 8d 3d 87 36 0c 00 66 66 48 e8 b7 0e 0a 00 48 8b 00 <f0> 83 48 08 40 48 8b 05 98 36 0c 00 48 8b 38 48 85 ff 74 09 48 8b
[3781114.466120] traps: .NET BGC[273180] general protection fault ip:7f2d92268bd3 sp:7eebc67fbb90 error:0 in libcoreclr.so[7f2d91fd1000+4e1000]
[3784441.425115] .NET Server GC[278359]: segfault at 8 ip 00007fa46043105c sp 00007fa458209e30 error 6 in libcoreclr.so[7fa45fff3000+4e1000]
[3784441.425151] Code: a2 94 0f 00 c3 66 0f 1f 84 00 00 00 00 00 55 48 89 e5 40 84 ff 74 18 66 48 8d 3d 87 36 0c 00 66 66 48 e8 b7 0e 0a 00 48 8b 00 <f0> 83 48 08 40 48 8b 05 98 36 0c 00 48 8b 38 48 85 ff 74 09 48 8b
```

### Regression?

This has never happened with .NET 6 that we've been using for this tool since February.

### Configuration

.NET 7.0

Windows 11
Debian GNU/Linux 11 (bullseye)

x64

**Comment by mangod9** [comment]
thanks for reporting this @appel1. Does it always fail with the same stack, or at different points? Given the symptoms it might be similar to https://github.com/dotnet/runtime/issues/78206. There is a private build available there if you would want to give that a try. 

Also Is there a dump you might be able to share privately to help diagnose/confirm whether its a similar issue? Thx!

**Comment by Maoni0** [comment]
if the private build doesn't fix your issue, or if it's hard to try a private build, could you please do the heap verification step? ie, set the COMPlus_HeapVerify env var to 1. this would allow us to get to the corruption sooner and help us see if the corruption is likely caused by the GC or not.

**Comment by appel1** [comment]
Hopefully I've managed to catch something meaningful here. 

With COMPlus_HeapVerify set the process was aborted and dmesg shows:
`[ 3981.920542] traps: .NET BGC[4221] general protection fault ip:7fc8c3045bd3 sp:7f86eeffcb90 error:0 in libcoreclr.so[7fc8c2dae000+4e1000]`

Second attempt with core dump enabled (`ulimit -c unlimited`):
```
[ 7340.960455] .NET Server GC[9201]: segfault at 8 ip 00007f7ff224705c sp 00007f7fea2b9e30 error 6 in libcoreclr.so[7f7ff1e09000+4e1000]
[ 7340.960480] Code: a2 94 0f 00 c3 66 0f 1f 84 00 00 00 00 00 55 48 89 e5 40 84 ff 74 18 66 48 8d 3d 87 36 0c 00 66 66 48 e8 b7 0e 0a 00 48 8b 00 <f0> 83 48 08 40 48 8b 05 98 36 0c 00 48 8b 38 48 85 ff 74 09 48 8b
```

How can I share the dump file privately? It's created on Debian and is 1.6GB gziped.

**Comment by appel1** [comment]
@mangod9  When we got NullReferenceException the stack was the same, but not the same data. Depends on how concurrent work is scheduled, I guess. 

It's a lot easier to reproduce this when running on Linux so if there's a build of the fixed clrgc for Linux I could try it.

**Comment by mangod9** [comment]
@PeterSolMS, can you please build a private for Linux? 

@appel1 , As for dumps if you could put on a secure share and send a link in email that would be helpful (my email should be in the profile).

**Comment by PeterSolMS** [comment]
@mangod9: I built a fixed libclrgc.so for Linux and put it on my OneDrive along with the Windows binaries:

https://1drv.ms/u/s!AuiLlxr1dM6apE-Ivxvkjr03oooA?e=zEenpo

**Comment by danmoseley** [comment]
One way to share dumps securely with us is to open a Visual Studio feedback ticket, and share the ID with us here. All attachments to such issues are securely stored. It's ok that it's not the reporting system for .NET Core.

**Comment by appel1** [comment]
Possibly doing something wrong but if I try to use the Linux libclrgc.so I get this error: 
`Failed to create CoreCLR, HRESULT: 0x80004005`

**Comment by mangod9** [comment]
can you please confirm whether you are running on Ubuntu or another distro -- also on x64 right?

**Comment by appel1** [comment]
I'm on Debian GNU/Linux 11 (bullseye), x64.

**Comment by mangod9** [comment]
Could you please check if running the application with `COMPlus_GCName=libclrgc.so` works for you without copying the private? @PeterSolMS, assume the private was built from the release/7.0 branch?

**Comment by appel1** [comment]
If I set COMPlus_GCName=libclrgc.so with the original libclrgc.so then the application can start.

**Comment by mangod9** [comment]
I have copied another private here: https://1drv.ms/u/s!AtaveiZOervriJhWyhQ7XH0ZqGBfXg?e=eyFQgU, if you want to try that out. Thx!

**Comment by appel1** [comment]
Looks promising but I'll do a couple of more runs just to be sure.

**Comment by appel1** [comment]
Got a couple of unexpected NullReferenceExceptions so far. Same code that has been running fine on .NET 6.0 for months. Heap verify is still enabled. 

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at MyClass.ValidateChildren(LoaderContext context) in C:\...\MyClass.cs:line 152
```

And line 152 is:
`base.ValidateChildren(context);`

Is there any way I can trigger a dump when a specific exception is raised on Linux? 

So far it hasn't happened when remote debugging.

**Comment by appel1** [comment]
Have done a couple of more runs that all completed without unexpected errors.
