### ISSUE TITLE
Resolve workaround for linker 1541 main assembly rooting behavior in AOT compiler

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#78752]
https://github.com/dotnet/runtime/blob/2ae7f5d42c817614839f3bf2e889981fdaa03631/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/UsageBasedMetadataManager.cs#L308-L314 has a workaround for rooting behavior of illink.

This behavior has been fixed in https://github.com/dotnet/linker/issues/1541.

We should remove the workaround in AOT compiler and make the two behaviors consistent.

Per @MichalStrehovsky this will require:
* Wait until the targets get propagated to the runtime repo because AFAIK the ILLink.targets we use to build tests are the one from the SDK used to build the repo. I think deleting the logic from the compiler would make us start rooting things.
* We will also need a change in the ILCompiler targets to ignore TrimmerRootAssembly with a non-default RootMode metadata. I didn’t even know such thing existed. We don’t need to be compatible with undocumented things (or we can if needed... it’s just more work and there’s huge value in keeping things simple for us and for customers).

**Comment by agocke** [comment]
Do we want an SDK test for this behavior, or is that overkill?
