### ISSUE TITLE
Should `IDictionary<K, V>` return something that implements `IReadOnlySet<K>`?

### ISSUE THREAD

**Issue by Ghostbird** [dotnet/runtime#78762]
> Finally... 👏👏
>
> May I suggest `Dictionary.KeyCollection` should also implement this?

_Originally posted by @nawfalhasan in https://github.com/dotnet/runtime/issues/32488#issuecomment-638006127_

I ran into such a situation today, I have a method that takes an `IReadOnlySet<string>` and I feed it from an `IDictionary<string>.Keys`. Which seems like a perfect match, but it doesn't work, because `IDictionary<string>.Keys` is an `ICollection<string>`. Even though logically it is a set.

**Comment by svick** [comment]
> May I suggest `Dictionary.KeyCollection` should also implement `IReadOnlySet<T>`?

That sounds reasonable.

> Should `IDictionary<K, V>.Keys` return something that implements `IReadOnlySet<K>`?

I don't think it can. Changing its return type from `ICollection<TKey>` to something else would be a breaking change. And changing `ICollection<T>` itself also doesn't seem reasonable.

Adding another (default implemented) property that returns `IReadOnlySet<K>` could work, but I'm not sure how good could that default implementation be.

**Comment by Ghostbird** [comment]
If the return type is changed to a covariant interface `IKeyCollection<K> implements ICollection<K>, IReadOnlySet<K>` is it a breaking change?
It won't break standard operations such as `is` and `as`, but I'm sure there are way more things that should be considered.

**Comment by svick** [comment]
> If the return type is changed to a covariant interface `IKeyCollection<K> implements ICollection<K>, IReadOnlySet<K>` is it a breaking change?

[Yes:](https://learn.microsoft.com/en-us/dotnet/core/compatibility/#members)

> ❌ DISALLOWED: Changing the type of a [...] return value

Specifically, consider a custom implementation of `IDictionary<K, V>`, which now returns some `ICollection<K>` from its `Keys`. That implementation would no longer be valid, which is why this would be a breaking change. (And why almost any change to an interface is a breaking change.)

**Comment by Ghostbird** [comment]
Ah, that makes perfect sense. I should've thought of it myself. Since this is clearly a breaking change that is not allowed for reasons of backwards compatibility, there doesn't seem to be a good way to solve this.

@nawfalhasan's original remark still stands, but I'd consider that a separate issue. Adding `IReadOnlySet<K>` to `KeyCollection<K>` while sensible, is relatively useless I think. I don't think I ever have knowledge of the specific `Dictionary<K,V>` implementation outside of the scope where it is created.

**Comment by nawfalhasan** [comment]
> I ran into such a situation today, I have a method that takes an IReadOnlySet<string> and I feed it from an IDictionary<string>.Keys.

Pretty much my scenario too. Also the fact that I cant use `IsSubsetOf`, `SetEquals` etc on `.Keys` is a bit annoying. All I am asking for is to have KeyCollection class to implement IReadOnlySet. 

I am not asking to change the return type. Of course it should have never been a mutable interface but those were designed well before IReadOnly counterparts and I guess that ship has sailed.
