### ISSUE TITLE
[Doc] Calling convention rules – Caller pop vs Callee pop?

### ISSUE THREAD

**Issue by xiangzhai** [dotnet/runtime#788]
Hi @davidwrighton

Thanks for your teaching about [Guide for porting .NET to a new processor architecture](https://github.com/dotnet/runtime/blob/master/docs/design/coreclr/botr/guide-for-porting.md)!

We are not clear about:

```
diff --git a/docs/design/coreclr/botr/guide-for-porting.md b/docs/design/coreclr/botr/guide-for-porting.md
index 9d5829e..f39d8df 100644
--- a/docs/design/coreclr/botr/guide-for-porting.md
+++ b/docs/design/coreclr/botr/guide-for-porting.md
@@ -155,7 +155,7 @@ Design issues
 These large architecture specific design issues will have substantial impact on
 both the JIT and VM.
 
-1.  Calling convention rules – Caller pop vs Callee pop, HFA arguments,
+1.  Calling convention rules – Caller push vs Callee pop, HFA arguments,
     structure argument passing rules, etc. CoreCLR is designed to utilize a
     broadly similar ABI to the OS api. Managed to managed calls typically have a
     small set of tweaks or extensions to the ABI for VM efficiency purposes, but it
```

> Architecture specific relocation information (to represent generation of relocations for use by load, store, jmp and call instructions) See https://docs.microsoft.com/en-us/windows/win32/debug/pe-format#coff-relocations-object-only for the sort of details that need to be defined.

Unimplemented `COFF Relocations` on MIPS64 yet.

> Crossgen/Crossgen2 - As the AOT compilers that produce machine specific logic from general purpose MSIL, these will be needed to improve startup performance.

Unimplemented.

> R2RDump - This allows diagnosing issues in pre-compiled code.

Unimplemented.

> coredistools - Necessary for GCStress (if determining instruction boundaries is non-trivial), as well as for SuperPMI asm diffs for JIT development.

`COMPlus_GCStress=1` failed to work at present.

> debug and diagnostics components - The managed debugger and profiler are beyond the scope of this document.

Unimplemented SOS. 

\cc @QiaoVanke

\cc @theaoqi

Thanks,
Leslie Zhai

**Comment by davidwrighton** [comment]
I'm not really sure what your question here is, but I'm assuming it has to do with the term callee pop vs caller pop.

In a caller pop calling convention, the caller is responsible for de-allocating space for the arguments of functions that it calls, but in callee pop the called function (the callee) is responsible for popping the arguments off of the stack. In .NET we use a callee pop abi for Windows X86, as that is the standard approach taken on that platform, but we use a caller pop abi on all other supported architecture and OS combinations.

In general a caller pop abi is more efficient unless the application makes heavy use of tail-calls as is common in some functional programming languages. In that situation, a callee pop abi is more efficient when the set of arguments passed to the function tail-called differ from the caller. For instance, I believe that GHC will generate functions with a callee pop abi when compiling Haskell code.

**Comment by xiangzhai** [comment]
Hi @davidwrighton 

Thanks for your kind response!

For example,

```
$ cat t.c
int foo(int a) {
  return a + 1;
}

void bar() {
  int a = foo(3);
  int b = a + 1;
}

$ gcc -O0 -mips64r2 -S -c t.c -o t.S
$ cat t.S
foo:
	.frame	$fp,32,$31		# vars= 16, regs= 1/0, args= 0, gp= 0
	.mask	0x40000000,-8
	.fmask	0x00000000,0
	.set	noreorder
	.set	nomacro
	daddiu	$sp,$sp,-32
	sd	$fp,24($sp)
	move	$fp,$sp
	move	$2,$4
	sll	$2,$2,0
	sw	$2,0($fp)
	lw	$2,0($fp)
	addiu	$2,$2,1
	move	$sp,$fp
	ld	$fp,24($sp)
	daddiu	$sp,$sp,32
	j	$31
	nop

	.set	macro
	.set	reorder
	.end	foo
	.size	foo, .-foo
	.align	2
	.globl	bar
	.set	nomips16
	.set	nomicromips
	.ent	bar
	.type	bar, @function
bar:
	.frame	$fp,48,$31		# vars= 16, regs= 3/0, args= 0, gp= 0
	.mask	0xd0000000,-8
	.fmask	0x00000000,0
	.set	noreorder
	.set	nomacro
	daddiu	$sp,$sp,-48
=>	sd	$31,40($sp)
=>	sd	$fp,32($sp)
=>	sd	$28,24($sp)
	move	$fp,$sp
	lui	$28,%hi(%neg(%gp_rel(bar)))
	daddu	$28,$28,$25
	daddiu	$28,$28,%lo(%neg(%gp_rel(bar)))
=>	li	$4,3			# 0x3
	ld	$2,%got_disp(foo)($28)
	move	$25,$2
	.reloc	1f,R_MIPS_JALR,foo
1:	jalr	$25
	nop

	sw	$2,0($fp)
	lw	$2,0($fp)
	addiu	$2,$2,1
	sw	$2,4($fp)
	move	$sp,$fp
	ld	$31,40($sp)
	ld	$fp,32($sp)
	ld	$28,24($sp)
	daddiu	$sp,$sp,48
	j	$31
	nop
```

That is my `Caller push`.

Thanks,
Leslie Zhai

**Comment by davidwrighton** [comment]
Ah, there is a misunderstanding here. The important detail between caller pop and callee pop has to do with adjusting the call stack. While this snippet indicates that the mips64r2 is a caller push abi, the important detail is where the $sp register is adjusted. (the daddiu $sp,$sp,-48 line and the daddiu $sp,$sp,48 line). In a caller pop architecture the stack pointer is adjusted on a per function basis, and in a callee pop architecture it is also adjusted on a per function *call*. In any case, it appears that mips also follows the common path of all supports architectures other than Windows X86.
