### ISSUE TITLE
[Mono][Android] App crashes with InvalidProgramException

### ISSUE THREAD

**Issue by simonrozsival** [dotnet/runtime#78833]
### Description

My code started crashing after pulling from `main`. There seems to be a some problem with the IL that's emitted by Mono on Android arm64.

### Reproduction Steps

Replace `src/mono/sample/Android/Program.cs` with the following code and run it using `make -C src/mono/sample/Android MONO_ARCH=arm64`:

```csharp
using System;
using System.Net.Http;

try
{
    using var handler = new SocketsHttpHandler();
    using var client = new HttpClient(handler);
    var response = await client.GetAsync("https://dot.net");
    Console.WriteLine(response);
    return 42;
}
catch (Exception ex)
{
    Console.WriteLine(ex);
    return 1;
}
```

### Expected behavior

The HTTP response is pritnted in logcat.

### Actual behavior

An exception is thrown:

```csharp
System.TypeInitializationException: The type initializer for 'System.Net.CookieContainer' threw an exception.
 ---> System.InvalidProgramException: Invalid IL code in (wrapper managed-to-native) Interop/Sys:GetDomainName (byte*,int): IL_0012: calli     0x00000003
   at Interop.Sys.GetDomainName()
   at System.Net.NetworkInformation.HostInformationPal.GetDomainName()
   at System.Net.NetworkInformation.HostInformation.get_DomainName()
   at System.Net.CookieContainer.CreateFqdnMyDomain()
   at System.Net.CookieContainer..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionSettings.CloneAndNormalize()
   at System.Net.Http.SocketsHttpHandler.SetupHandlerChain()
   at System.Net.Http.SocketsHttpHandler.SendAsync(HttpRequestMessage , CancellationToken )
   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage , CancellationToken )
   at System.Net.Http.HttpClient.<>n__0(HttpRequestMessage , CancellationToken )
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage , HttpCompletionOption , CancellationTokenSource , Boolean , CancellationTokenSource , CancellationToken )
   at Program.<Main>$(String[] )
```

### Configuration

- Current main (since [`3cfd6cffc495e4539bf6cdb5919922b8d8972e57`](https://github.com/dotnet/runtime/commit/3cfd6cffc495e4539bf6cdb5919922b8d8972e57))
- Android on arm64

### Other information

I've traced the problem to #75542. Basic hello world program works but when I try to make an HTTP request, the program crashes. The tests in CI seem to pass which is quite strange.

/cc @lambdageek @naricc

**Comment by lambdageek** [comment]
My hunch, without any evidence, is that mono and the marshaling component somehow ended up with two copies of some static var. And it's messing up marshaling. Possibly in some timing-related manner.

Either that or CI builds Android in some slightly different way than local builds

**Comment by simonrozsival** [comment]
Hmm, so I figured out that when I run the Android sample and I explicitly include the `marshal-ilgen` runtime component, it works as expected:

```
make -C src/mono/sample/Android MONO_ARCH=arm64 RUNTIME_COMPONENTS=marshal-ilgen
```

**Comment by lambdageek** [comment]
> Hmm, so I figured out that when I run the Android sample and I explicitly include the `marshal-ilgen` runtime component, it works as expected:
> 
> ```
> make -C src/mono/sample/Android MONO_ARCH=arm64 RUNTIME_COMPONENTS=marshal-ilgen
> ```

ok, in that case we should figure out:
1. Why `Interop/Sys:GetDomainName` needs non-legacy marshaling
2. Why the call to GetDomainName throws an unhelpful invalid IL error message instead of something coherent from the non-legacy marshaling.

/cc @naricc

**Comment by jandupej** [comment]
@simonrozsival Can you please verify that the issue still occurs?

**Comment by simonrozsival** [comment]
@jandupej I tested it on latest main and the Android app still crashes when I don't explicitly set `RUNTIME_COMPONENTS=marshal-ilgen`. The log output has changed:

```
06-15 20:01:34.857 16236 16259 D DOTNET  : ((null) error) * Assertion at /.../dotnet/runtime/src/mono/mono/metadata/method-builder-ilgen.c:577, condition `ctor' not met
06-15 20:01:34.857 16236 16259 E DOTNET  : Exit code: 1.
```

**Comment by jandupej** [comment]
The crashes are resolved with https://github.com/dotnet/runtime/pull/89564. Closing.
