### ISSUE TITLE
Strange behavior between Release and Debug builds [Random access violations and null exceptions]

### ISSUE THREAD

**Issue by redknightlois** [dotnet/runtime#78839]
### Description

First the disclaimer: Our code is not saint, it could totally be our fault, I just don't know where to look anymore. 

This piece of code works properly when code generated is in debug mode, but not when it is release. However, there is another interesting behavior. This error started appearing after implementing a new high performance SIMD sorting code based on the same algorithm used by the Garbage Collector. So the biggest difference is we are calling that routine. When either the caller assembly `Corax` or the assembly that host that code `Sparrow.Server` is emitting debug code the error does not show itself.

![image](https://user-images.githubusercontent.com/1045411/203844018-79e2bce1-38d0-408d-9b0b-f2fc4cb91ad5.png)
As you can see from the image, I test for `null` before the call to `.Fill()` and when I try to do the check again it triggers a null exception. Furthermore `match` is an `struct` so there is no option on it becoming null unless somehow the return pointer is wrong or something overwrites the stack. 

That counter measures how reliably the issue is triggered. The failure is totally unreliable sometimes it takes 1150 others 1270, and so on. 

### Reproduction Steps

1. Clone the repo: https://github.com/redknightlois/ravendb/tree/repro-release-mode-memoryissue
2. Execute in release mode: Voron.Benchmark
3. After 1200+ rounds the error happens at: https://github.com/redknightlois/ravendb/blob/repro-release-mode-memoryissue/src/Corax/Queries/SortingMatch/SortingMatch.cs#L244

### Expected behavior

No null exception. 

### Actual behavior

Null exception

### Known Workarounds

No

### Configuration

C# 11, .Net 7.0, SDK 7.0.100, 
Windows 10 , AMD x64

**Comment by MichalPetryka** [comment]
`Furthermore match is an struct so there is no option on it becoming null unless somehow the return pointer is wrong or something overwrites the stack.`

The ref to it could however somehow become null, could you check with `Unsafe.IsNullRef`?

**Comment by danmoseley** [comment]
Does it happen in 6.0?

**Comment by srwrr** [comment]
6037701726651810

سرور ریجای

در تاریخ پنجشنبه ۲۴ نوامبر ۲۰۲۲،‏ ۱۱:۴۷ ب.ظ Michał Petryka <
***@***.***> نوشت:

**Comment by ANahr** [comment]
If this only happens after switching to .Net 7 maybe another case of #78206?

**Comment by danmoseley** [comment]
Right, that's why it's interesting to know whether it happens on .NET 6

**Comment by jkotas** [comment]
This is not a duplicate #78206. If you set `DOTNET_TieredCompilation=0`, it will crash immediately in the first iteration and the GC did not run at all at that point.

@dotnet/jit-contrib This looks like a codegen optimization bug. Could you please take a look?

**Comment by redknightlois** [comment]
I cannot say for sure, because we transitioned the codebase a week or so ago. But I could try to incorporate that into the old codebase if you think it is worth it for analyzing the issue.

**Comment by jkotas** [comment]
A few more observations:
- The immediate reason for the crash is massive stack corruption - the whole stack is overwritten by random data.
- The bad codegen seems to be triggered by aggressive inlining. Commenting out all `MethodImplOptions.AggressiveInlining` in the repo makes the crash go away.

**Comment by redknightlois** [comment]
Removing the `MethodImplOptions.AggressiveInlining` and also `MethodImplOptions.AggressiveOptimization` does not work as a workaround. It does extend the time it takes to crash.

**Comment by EgorBo** [comment]
It looks like it's VXSort related, btw, we recently had to patch our version due to potential buffer overruns https://github.com/dotnet/runtime/pull/75364/files

**Comment by EgorBo** [comment]
When I run this benchmark under gcstress it asserts in `Main`, right after call `[Corax.Queries.SortingMatch:Fill(System.Span`1[long]):int:this]`

**Comment by jakobbotsch** [comment]
The stack corruption happens in the inlined version of this code:

https://github.com/redknightlois/ravendb/blob/6dfc989e2b2695ddb421d81421a4ac28fd1ca66c/src/Corax/VxSort/VectorizedSort.AVX2.long.generated.cs#L391-L392

I will look a bit further, but at first glance, this code looks somewhat dangerous (but maybe not):

https://github.com/redknightlois/ravendb/blob/6dfc989e2b2695ddb421d81421a4ac28fd1ca66c/src/Corax/VxSort/VectorizedSort.AVX2.generated.cs#L35-L45

What `_tempPtr` ends up pointing at after copies are done is not completely clear here, depending on how the constructor was called.

**Comment by redknightlois** [comment]
@jakobbotsch Yes, that's the part of when I said that it could totally be our fault :D ... For an explanation of what that is, those are the boundaries of the array to be sorted. 

I am checking with a colleague because we found one instance of the same issue without the VxSort but we are not completely sure it is not our fault too. If you want I can ask him to post a repro for it even though we haven't ruled out  yet if we are not something stupid on our end.

**Comment by redknightlois** [comment]
@jakobbotsch I misunderstood you. You mean the copy of the fixed part of the struct itself to a temporary pointer. Unless I am missing something we are dealing with a struct that is not going to be copied therefore it is safe. This is a method that is intended to be totally internal with very carefully crafted usage patterns because it is dangerous; your assessment is correct. You can look into HOW it is intended to be used here: https://github.com/redknightlois/ravendb/blob/6dfc989e2b2695ddb421d81421a4ac28fd1ca66c/src/Corax/VxSort/VectorizedSort.cs#L87

**Comment by EgorBo** [comment]
Two things I noticed yesterday that:
1) `[NoOptimization]` fixes the problem if put on top of https://github.com/redknightlois/ravendb/blob/6dfc989e2b2695ddb421d81421a4ac28fd1ca66c/src/Corax/VxSort/VectorizedSort.cs#L70
2) https://github.com/redknightlois/ravendb/blob/6dfc989e2b2695ddb421d81421a4ac28fd1ca66c/src/Corax/VxSort/VectorizedSort.cs#L106

Replacing int.MinValue/int.MaxValue with long.MinValue/long.MaxValue also help here but I've no idea if it's correct/expected.

**Comment by EgorBo** [comment]
Also, extending the size of that temp buffer also helps. Perhaps, that magic sequence of constants is not correct? `2 * (8 * 32) + 32 + 4 * 32`

**Comment by jakobbotsch** [comment]
> @jakobbotsch I misunderstood you. You mean the copy of the fixed part of the struct itself to a temporary pointer. Unless I am missing something we are dealing with a struct that is not going to be copied therefore it is safe.

This depends on how the constructor is called in the IL generated by Roslyn. If Roslyn generates `newobj` then there is going to be a temporary copy created. If Roslyn generates a direct call to the constructor passing the address of the local, then there is no copy. I am not sure if Roslyn is guaranteed to generate the latter for structs (this is what happens).

In any case, I was not implying there is no JIT bug, but the JIT bug may be due to optimizations that make wrong assumptions around some of this.

**Comment by EgorBo** [comment]
@redknightlois can you re-review 
`Int32Config.MaxPartitionTempSizeInElements`
and
`Int64Config.MaxPartitionTempSizeInElements`
and that
```
fixed int _temp[2 * (8 * 32) + 32 + 4 * 32];
```
that Jakob pointed to?
they all are the same value for int32 and int64 paths

**Comment by redknightlois** [comment]
@EgorBo nice catch, that is clearly a bug I will fix; but not relevant for this issue. 

This is from the reference implementation:
```
// We need this as a compile time constant
const ulong ALIGN = 32; // Alignment in bytes
const int V256_N = 256 / 8 / sizeof(int);
const int SLACK_PER_SIDE_IN_ELEMENTS = SLACK_PER_SIDE_IN_VECTORS * V256_N;

// How much initial room needs to be made
// during setup in full Vector256 units
const int SLACK_PER_SIDE_IN_VECTORS = 8; <--- this could be 4 for longs (definitely an issue, not in this case though because long should be 4)

// The formula goes like this:
// 2 x the number of slack elements on each side +
// 2 x amount of maximal bytes needed for alignment (32)
// 8 more elements since we write with 8-way stores from both ends of the temporary area
// and we must make sure to accidentaly over-write from left -> right or vice-versa right on that edge...
const int PARTITION_TMP_SIZE_IN_ELEMENTS = (int)(2 * SLACK_PER_SIDE_IN_ELEMENTS + 2 * ALIGN / sizeof(int) + V256_N);
```
So the formula goes like this:
```
2 * SLACK_PER_SIDE_IN_ELEMENTS + 2 * ALIGN / sizeof(T) + V256_N = 
2 * (SLACK_PER_SIDE_IN_VECTORS * V256_N) + 2 * ALIGN / sizeof(int) + V256_N = 
2 * (SLACK_PER_SIDE_IN_VECTORS * V256_N) + V256_N + 2 * ALIGN / sizeof(T) = 
V256_N * (2 * SLACK_PER_SIDE_IN_VECTORS + 1) + 2 * ALIGN / sizeof(T) = 
(256 / 8 / sizeof(T)) * (2 * SLACK_PER_SIDE_IN_VECTORS + 1) + 2 * ALIGN / sizeof(T) = 
(32 / sizeof(T)) * (2 * SLACK_PER_SIDE_IN_VECTORS + 1) + 2 * ALIGN / sizeof(T) = 
```
Now if we specialize for `int` we get something like this:
```
sizeof(T) = 4 [int]
(32 / 4) * (2 * 8 + 1) + 2 * (32 / 4) = 
8 * (16 + 1) + 2 * 8 = 
8 * 17 + 2 * 8 = 
152 -> in elements | 152 * 4  = 608 in bytes
```
And if we do that for `long` we get:
```
sizeof(T) = 4 [long]
(32 / 8) * (2 * 8 + 1) + 2 * (32 / 8) = 
4 * (2 * 8 + 1) + 2 * (32 / 8) = 
4 * 17 + 2 * 4 = 
76 -> in elements | 76 * 8 = 608 in bytes
```
But I just realized this:
```
_temp = 672 -> in elements | 672 * 4 [int] = 2688 bytes.
```
So it has more than enough room for almost any type mostly because I define it in `int`s instead of `bytes`.

**Comment by redknightlois** [comment]
> This depends on how the constructor is called in the IL generated by Roslyn. If Roslyn generates `newobj` then there is going to be a temporary copy created. If Roslyn generates a direct call to the constructor passing the address of the local, then there is no copy. I am not sure if Roslyn is guaranteed to generate the latter for structs (but this is what it does generate for this situation, so I believe it should be safe).

@jakobbotsch Interesting, I was under the impression that the latter was a guarantee... Who would be the right person to ask if that is a by-product of current implementation OR an specification guarantee?

**Comment by jakobbotsch** [comment]
> @jakobbotsch Interesting, I was under the impression that the latter was a guarantee... Who would be the right person to ask if that is a by-product of current implementation OR an specification guarantee?

I found some related issues:
https://github.com/dotnet/roslyn/issues/15715
https://github.com/dotnet/roslyn/issues/48688

From some quick skimming they both seem to suggest that actually a temporary copy should always be created.

**Comment by jakobbotsch** [comment]
The problem seems to disappear if I change the initialization to a more well-defined (from the C# side):
```diff
-                var sorter = new Avx2VectorizedSort(il, ir);
+                Avx2VectorizedSort.Init(il, ir, out Avx2VectorizedSort sorter);
```

**Comment by EgorBo** [comment]
I think the proper pattern is to just accept a pointer to a buffer in constructor. And then stackalloc it at the call-site.

In fact, 
```csharp
fixed (ptr = _field)
    return ptr;
```
pattern is never a good idea and perhaps we should throw a warning for it

**Comment by redknightlois** [comment]
> Replacing int.MinValue/int.MaxValue with long.MinValue/long.MaxValue also help here but I've no idea if it's correct/expected.https://github.com/redknightlois/ravendb/blob/6dfc989e2b2695ddb421d81421a4ac28fd1ca66c/src/Corax/VxSort/VectorizedSort.cs#L106
🤦‍♂️ <--- this is me right now... 

@EgorBo That is certainly a bug, how that kills the stack is beyond me though; worst case scenario in this particular case is that the data would get mangled and corrupted to the point of no-recognition. So if that changes the behavior of the code generated, we may have a lead (regardless of the unsafe usage pattern)

**Comment by jakobbotsch** [comment]
> The problem seems to disappear if I change the initialization to a more well-defined (from the C# side):

Actually this is not the case, I had forgotten to set `DOTNET_TieredCompilation=0`.

**Comment by jakobbotsch** [comment]
> So it has more than enough room for almost any type mostly because I define it in `int`s instead of `bytes`.

The code [here](https://github.com/redknightlois/ravendb/blob/6dfc989e2b2695ddb421d81421a4ac28fd1ca66c/src/Corax/VxSort/VectorizedSort.AVX2.long.generated.cs#L334) computes

`            var tmpStartRight = tmpStartLeft + PARTITION_TMP_SIZE_IN_ELEMENTS;`
where `tmpStartLeft` is a `long*`. So `tmpStartRight` ends up pointing outside `_temp`. If I change `_temp` to be an array of longs then the problem disappears.

**Comment by redknightlois** [comment]
And that is a BINGO!!! That could explain the mangled stack. You guys rock!! Sorry for making you chase a ghost. 

Give me a few hours to fix all these issues and extensively test everything, but I consider this closed.
