### ISSUE TITLE
ilconformance test for stind.ref doesn't test stind.ref

### ISSUE THREAD

**Issue by drcjt** [dotnet/runtime#78867]
The il conformance test for stind.ref doens't test the stind.ref il instruction.

Here's the test https://github.com/dotnet/runtime/blob/main/src/tests/JIT/IL_Conformance/Old/Conformance_Base/stind_ref.il

The il doesn't include the stind.ref instruction at all!

**Comment by JulieLeeMSFT** [comment]
@TIHan, PTAL.

**Comment by TIHan** [comment]
Will look into this.
