### ISSUE TITLE
[UWP] Cryptography.ProtectedData version 7.0 => System.PlatformNotSupportedException

### ISSUE THREAD

**Issue by jp-weber** [dotnet/runtime#78875]
### Description

If I install the current System.Security.Cryptography.ProtectedData version (7.0), I get following error message:
```
System.PlatformNotSupportedException: 'Windows Data Protection API (DPAPI) is not supported on this platform.'
````
With the previous version all runs well.

### Reproduction Steps

1. App with UWP target
2. Install System.Security.Cryptography.ProtectedData
3. Access the api => crash

### Expected behavior

No exception

### Actual behavior

See description

### Known Workarounds

Install System.Security.Cryptography.ProtectedData version 6.0

### Configuration

- Windows 10 19045.2311
- Visual Studio 2022 17.4.0
- UWP MinTarget 1809, Target 2004

**Comment by adamsitnik** [comment]
@ViktorHofer I am trying to understand why this has stopped working.  The `System.Security.Cryptography.ProtectedData.csproj` uses following settings:

```xml
<TargetFrameworks>$(NetCoreAppCurrent)-windows;$(NetCoreAppCurrent);$(NetCoreAppMinimum)-windows;$(NetCoreAppMinimum);netstandard2.0;$(NetFrameworkMinimum)</TargetFrameworks>

<GeneratePlatformNotSupportedAssemblyMessage Condition="'$(IsPartialFacadeAssembly)' != 'true' and '$(TargetPlatformIdentifier)' != 'windows'">SR.PlatformNotSupported_CryptographyProtectedData</GeneratePlatformNotSupportedAssemblyMessage>
``` 

Is UWP consuming the `netstandard2.0` package from all the above? Is it possible that after your changes from https://github.com/dotnet/runtime/pull/64500 the `TargetPlatformIdentifier` is not set to `windows` for UWP?

**Comment by ViktorHofer** [comment]
> @ViktorHofer I am trying to understand why this has stopped working. The System.Security.Cryptography.ProtectedData.csproj uses following settings:

UWP doesn't use .NETCoreApp target framework monikers like `netcoreapp3.1`, `net6.0`, `net7.0`. Instead, it uses the `uap10.0.xxxxx` target framework moniker. Therefore, the UWP client application picks the netstandard2.0 asset from the package which is a `PlatformNotSupportedException` throwing assembly as we intentionally don't provide a runtime agnostic implementation for System.Security.Cryptography.ProtectedData anymore.

@jp-weber is it possible for you to stay on the 6.0.x version of ProtectedData or retarget your app model to use .NET 6+ with WinUI?

**Comment by jp-weber** [comment]
@ViktorHofer 
Oh that is sad, currently I have a class library with targets NetStandard2.0 for UWP, and NET7.0 for all other. I would like to be able to use the current version under UWP. 

Due to the current status of WinUI3/WindowsAppSDK, an update to WinUI3 is not an option now and will only be possible in many years.

**Comment by vcsjones** [comment]
We could change this to be a runtime check on .NET Standard and remove the `GeneratePlatformNotSupportedAssemblyMessage`. @ViktorHofer @bartonjs does that seem like a viable path forward?

**Comment by ViktorHofer** [comment]
We discussed something similar offline. Could we do that for all tfms, not just netstandard2.0? Asking as PNSE assemblies increase the package size.

**Comment by ViktorHofer** [comment]
@jp-weber this just got fixed by @vcsjones in https://github.com/dotnet/runtime/pull/80158 and will be available as a preview nuget package when 8.0 Preview 1 releases.

**Comment by ViktorHofer** [comment]
Assuming that we don't want to backport the fix, let's close the issue.

**Comment by bartonjs** [comment]
We do want to backport the fix.

**Comment by vcsjones** [comment]
@bartonjs do we want to backport that PR as-is, or try making a more surgical change?

**Comment by bartonjs** [comment]
That's a good question.  I _assume_ that backporting the TFM reduction would be goodness, since it'll make the patched package smaller; and that NuGet has no real concept of SemVer, so there wouldn't be any weird affinitization for TFM split vs (mostly) unified in a patch package that wasn't already going to be an issue for major-version packages.

So I'd probably go for backporting it as-is.

**Comment by adamsitnik** [comment]
Both PRs got merged (https://github.com/dotnet/runtime/issues/78875, https://github.com/dotnet/runtime/pull/80196), closing.
