### ISSUE TITLE
[CoreRun] AppDomain.BaseDirectory returns the runtime host's directory

### ISSUE THREAD

**Issue by hadibrais** [dotnet/runtime#7887]
On the .NET Framework, the [AppDomainSetup.ApplicationBase](https://msdn.microsoft.com/en-us/library/system.appdomainsetup.applicationbase(v=vs.110).aspx) property returns the directory in which the main executable resides (the binary that contains the Main method). However, on .NET Core, apps require a host and so the runtime sets AppDomainSetup.ApplicationBase to the directory in which the host resides, which could be different from the one in which the main executable resides. This issue impacts [AppDomain.BaseDirectory ](https://msdn.microsoft.com/en-us/library/system.appdomain.basedirectory(v=vs.110).aspx)and [AppContext.BaseDirectory](https://msdn.microsoft.com/en-us/library/system.appcontext.basedirectory(v=vs.110).aspx) as well.

**Comment by joperezr** [comment]
From @jkotas response above it doesn't sound like this is a product issue, at least not with the shipping product so given the lack of activity here I'll go ahead and close this for now. Feel free to reopen if you think otherwise.
