### ISSUE TITLE
Binary DataContractSerializer serialization is broken in .NET 7 for floating point data types

### ISSUE THREAD

**Issue by IvanMaskaliou** [dotnet/runtime#78913]
### Description

When migrating to .NET 7 I have error when de-serializing object which was serialized using DataContractSerializer (using BinaryWriter). 

### Reproduction Steps

Just run the following code:

```csharp
using System.Runtime.Serialization;
using System.Xml;

namespace ConsoleApp2
{
    [DataContract]
    public class TestObject
    {
        [DataMember]
        public double MinDepth { get; set; }
    }

    internal class Program
    {
        static void Main(string[] args)
        {
            //create
            var instance = new TestObject { MinDepth = 100.8 };

            //serialize
            var serializer = new DataContractSerializer(typeof(TestObject));
            var stream = new MemoryStream();
            var writer = XmlDictionaryWriter.CreateBinaryWriter(stream);
            serializer.WriteObject(writer, instance);
            writer.Flush();

            //de-serialize
            stream.Position = 0;
            var reader = XmlDictionaryReader.CreateBinaryReader(stream, XmlDictionaryReaderQuotas.Max);
            var instance2 = serializer.ReadObject(reader) as TestObject;
        }
    }
}
```

### Expected behavior

instance2 is an instance of TestObject with MinDepth property value 100.8

### Actual behavior

Excpetion:
System.Runtime.Serialization.SerializationException: 'There was an error deserializing the object of type ConsoleApp2.TestObject. The input source is not correctly formatted.'

### Regression?

Worked correct in .NET 6 and earlier.

### Configuration

.NET 7 Windows 11 x64

### Other information

This code works fine for .NET 6 and earlier. In .NET 7, System.Runtime.Serialization.SerializationException exception is raised for property of double or float data type (works fine for decimal). Also works correct when property contain integer value (for example 100, value 100.8 raises exception). Does not depend on regional settings.

**Comment by K-Cully** [comment]
Note that this issue has also been observed when upgrading Service Fabric services that communicate through Service Fabric remoting. Service Fabric remoting uses  DataContractSerilizer, so this appears to have the same root cause detailed above.

**Comment by akoeplinger** [comment]
@HongGit @StephenMolloy

**Comment by mahpate** [comment]
We are observing same issue in SF remoting API's.
