### ISSUE TITLE
Feature request: Inline Breakpoint support in Visual Studio

### ISSUE THREAD

**Issue by jogibear9988** [dotnet/runtime#78932]
### Description

Don't know if feature requests are allowed here.

For example in Chrome you could set breakpoints "inline" if you have different scopes like a callback or something similar.
<img width="426" alt="image" src="https://user-images.githubusercontent.com/364896/204381060-fc56d8c1-244a-4165-9fb2-4e1b46b2ed3c.png">

If I'd like for example have this c# code:

       list.Where(x => { return x >2; }).ToList();

I could not set a breakpoint inside of the block of the where. Also it would be nice if I could set a breakpoint if it's a Expression instead of a block, but don't know if this would be possible. I know that it would not be possible on IQueryables cause the code would be in a Expression<T> (it also makes no sense there cause it will be converted to SQL or other code).

But for normal inline invocations it would be a huge addition if this would be possible.

### Reproduction Steps

feature request

### Expected behavior

feature request

### Actual behavior

feature request

**Comment by tommcdon** [comment]
Hello @jogibear9988!  Can you clarify which version of .NET you are using, project type, and application configuration (release or debug)?  Setting breakpoints inside of some types of expressions is supported in Visual Studio.  For example, I am able to set breakpoints inside of the Linq expression using Visual Studio with .NET 6+ (screenshot below).  Do you see a yellow exclamation point when setting the breakpoint or any other indication of a breakpoint binding issue?  

![image](https://user-images.githubusercontent.com/12520929/204383767-07c7701e-3db1-4f32-ac5f-f20934bf8087.png)

**Comment by jkotas** [comment]
To set the breakpoint on the return statement in your example, right click on the return statement and select Breakpoint / Insert Breakpoint from the context menu.

**Comment by jogibear9988** [comment]
Never knew this was possible, I'll try.
But a visual Indicator & switch like in Chrome & Edge would be really nice.

**Comment by tommcdon** [comment]
> But a visual Indicator & switch like in Chrome & Edge would be really nice.

That sounds like a great suggestion @jogibear9988!  A Visual Studio suggestion item can be created through [this link](https://developercommunity.visualstudio.com/VisualStudio/suggest) or inside of Visual Studio:

![image](https://user-images.githubusercontent.com/12520929/204396643-685821fe-35fe-4948-9fb1-21c4174dfd48.png)

**Comment by jogibear9988** [comment]
did suggest: https://developercommunity.visualstudio.com/t/Displayset-Inline-Breakpoints-like-in-G/10215438
Looking vor upvotes. :-)

**Comment by Suchiman** [comment]
@jogibear9988 another possibility is to just press F9 when your cursor is on the thing you want to break on.

**Comment by tommcdon** [comment]
Thanks all!  Since this is a Visual Studio feature request, I'll close this issue.
