### ISSUE TITLE
Assertion failed '!"Incompatible types for gtNewTempAssign"'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#78944]
win-x86 checked random jitstress

https://dev.azure.com/dnceng-public/public/_build/results?buildId=94457&view=ms.vss-test-web.build-test-results-tab&runId=1991328&paneView=debug&resultId=119215

Failures:

JIT\Directed\coverage\importer\byrefsubbyref1\byrefsubbyref1.cmd
JIT\Directed\coverage\importer\Desktop\byrefsubbyref1_il_r\byrefsubbyref1_il_r.cmd
JIT\Directed\coverage\importer\Desktop\byrefsubbyref1_il_d\byrefsubbyref1_il_d.cmd

```
    JIT\Directed\coverage\importer\Desktop\byrefsubbyref1_il_r\byrefsubbyref1_il_r.cmd [FAIL]
      
      Assert failure(PID 1364 [0x00000554], Thread: 7036 [0x1b7c]): Assertion failed '!"Incompatible types for gtNewTempAssign"' in 'a:byrefsubi4(byref,int):int' during 'Morph - Global' (IL size 10; hash 0x72f297d0; FullOpts)
      
          File: D:\a\_work\1\s\src\coreclr\jit\gentree.cpp Line: 15705
          Image: C:\h\w\B23E091A\p\corerun.exe
      
      
      Return code:      1
      Raw output file:      C:\h\w\B23E091A\w\A9E30972\uploads\Reports\JIT.Directed\coverage\importer\Desktop\byrefsubbyref1_il_r\byrefsubbyref1_il_r.output.txt
      Raw output:
      BEGIN EXECUTION
       "C:\h\w\B23E091A\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  byrefsubbyref1_il_r.dll 
      -4
                     [000002] -----+-----                         *  SUB       byref 
                     [000000] -----+-----                         +--*  LCL_VAR   byref  V00 arg0         
                     [000001] -----+-----                         \--*  LCL_VAR   int    V01 arg1         
      Expected: 100
      Actual: -1073740286
      END EXECUTION - FAILED
```

with:
```
set DOTNET_TieredCompilation=0
set DOTNET_JitStress=2b1
```

@dotnet/jit-contrib

**Comment by TIHan** [comment]
Will look into it.

**Comment by TIHan** [comment]
@jkotas @jkoritzinsky - This IL test has a situation where the JIT accepts a `byref -> native int` implicit conversion which I believe is illegal. I'm wondering what our plan is for handling it? Currently, the test causes an assert for x86 with env vars `JitStress=2b1` and `JitMinOpts=1`

I can resolve this issue by fixing the IL test with a `conv.u` in the meantime.

**Comment by EgorBo** [comment]
So from my understanding, it's not a valid IL but it works as is (well, apparently not with the jitstress)
if we start throwing InvalidProgramException for it we might brake some existing libraries.

This is exactly what happened with https://github.com/dotnet/runtime/pull/43386 - it stopped tolerating a similar pattern and it broke ninject https://github.com/dotnet/runtime/issues/67351 (and libraries which used it as a dependency)
