### ISSUE TITLE
Test failure: Interop\\COM\\ComWrappers\\WeakReference\\WeakReferenceTest\\WeakReferenceTest.cmd

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#78945]
Failed in win-x86 with random JitStress twice:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=94457&view=ms.vss-test-web.build-test-results-tab&runId=1991330&paneView=debug&resultId=105021

Related? https://github.com/dotnet/runtime/pull/78589

with:
```
set DOTNET_TieredCompilation=0
set DOTNET_JitStress=2f6
```

as well as with:
```
set DOTNET_TieredCompilation=0
set DOTNET_JitStress=3be
```

error:
```
    Interop\COM\ComWrappers\WeakReference\WeakReferenceTest\WeakReferenceTest.cmd [FAIL]
      
      Return code:      1
      Raw output file:      C:\h\w\B3570998\w\97580854\uploads\Reports\Interop.COM\ComWrappers\WeakReference\WeakReferenceTest\WeakReferenceTest.output.txt
      Raw output:
      BEGIN EXECUTION
       "C:\h\w\B3570998\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  WeakReferenceTest.dll 
      Running ValidateNonComWrappers...
      Running ValidateGlobalInstanceMarshalling...
        -- Validate weak reference creation
          -- Validate RCW recreation
          -- Validate release
        -- Validate target reset
          -- Validate RCW recreation
          -- Validate release
      Running ValidateGlobalInstanceTrackerSupport...
        -- Validate weak reference creation
          -- Validate RCW recreation
          -- Validate release
        -- Validate target reset
          -- Validate RCW recreation
          -- Validate release
      Validate weak reference with aggregation.
      Test Failure: Xunit.Sdk.NullException: Assert.Null() Failure
      Expected: (null)
      Actual:   DerivedObject { }
         at ComWrappersTests.Program.ValidateAggregatedWeakReference()
         at ComWrappersTests.Program.Main()
      Expected: 100
      Actual: 101
      END EXECUTION - FAILED
      FAILED
```

@VSadov @AaronRobinsonMSFT

**Comment by BruceForstall** [comment]
There are more cases with Linux/Mac arm64:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=94437&view=ms.vss-test-web.build-test-results-tab&runId=1991016&paneView=debug&resultId=100274

with JitStress=2, JitStressRegs=3

**Comment by VSadov** [comment]
The failures look different from https://github.com/dotnet/runtime/pull/78589 

I will take a look.

**Comment by VSadov** [comment]
What does JitStress do?   It will be helpful to know what makes the failures to show up.

**Comment by BruceForstall** [comment]
> What does JitStress do?

It changes the code generated by the JIT by changing various internal JIT heuristics, e.g., forcing a lot of inlining, or avoiding using certain registers to create additional register pressure. The "JitStress" or "JitStressRegs" number affects how these heuristics are altered.

**Comment by VSadov** [comment]
Hmm. Using or not using some registers might not make a difference for weak references, but too much or too little inlining may have effect on objects' lifetime. That could be a useful clue. Thanks!

**Comment by VSadov** [comment]
I was able to reproduce this locally.

**Comment by VSadov** [comment]
This is a result of aggressive inlining extending the life time of a local. It is a testcase issue. There is a simple fix. I will make a PR shortly.
