### ISSUE TITLE
dotnet EXE application doesn't work with shebang on Linux

### ISSUE THREAD

**Issue by daxian-dbw** [dotnet/runtime#78941]
### Description

When building a self-contained console application targeting .NET 7, the console application doesn't work with shebang in Linux.

However, when building the same console application targeting .NET 6, the produced console application works fine with shebang.

This causes powershell v7.3.0 to stop working with shebang on Linux. See https://github.com/PowerShell/PowerShell/issues/18510

### Build a simple self-contained console application targeting .NET 7

The console application is very simple:
```c#
using System;

namespace MyApp
{
    internal class Program
    {
        static void Main(string[] args)
        {
            for (int i = 0; i < args.Length; i++)
            {
                Console.WriteLine($"<Arg {i}>: {args[i]}");
            }
        }
    }
}
```

The .csproj file:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>

</Project>
```

Build a self-contained console application from the C# code, targeting .NET 7:
```
dotnet publish -r linux-x64 -c Release --self-contained
```

### Create the script file that uses shebang to run the console application

The content of the script file `dotnet7`:
```
#!/home/daxian/apps/1self/bin/Release/net7.0/linux-x64/publish/1self
$true
```

Then, run `chmod` to make the file an executable
```
chmod +x ./dotnet7
```

At last, run `dotnet7` in bash:
```
./dotnet7
```

### Expected behavior

The console application should run and print the arguments it receives.

When building against .NET 6, it works as expected, and here is the screenshot of the result:

![image](https://user-images.githubusercontent.com/127450/204409954-42382bb8-6195-4ac6-9e5e-557b88ae6eab.png)

### Actual behavior

When building against .NET 7, it stops working with the following error message:

```
bash:35> ./dotnet7
The application to execute does not exist: '/home/daxian/temp/1self.dll'.
```

![image](https://user-images.githubusercontent.com/127450/204410059-1ca57f6a-b7b9-45a4-b1ac-b85590c493ca.png)

### Regression?

Yes, it's a regression from .NET 6

### Known Workarounds

No known workaround so far.

### Configuration

> Which version of .NET is the code running on?

.NET 7 -- SDK version 7.0.100, 

> What OS and version, and what distro if applicable?

WSLv2 - Ubuntu 18.04

> What is the architecture (x64, x86, ARM, ARM64)?

I reproduced the issue on x64, but didn't try other architectures.

**Comment by am11** [comment]
> ```
> dotnet publish -r linux-x64 --self-contained
> ```
> ...
> ```
> #!/home/daxian/apps/1self/bin/Release/net7.0/linux-x64/publish/1self
> ```

Did you mean to use `/Debug/` on shebang line or pass `-c Release` to dotnet-publish?

**Comment by daxian-dbw** [comment]
@am11 Thanks for spotting that!
It was a typo, and I did specify `-c Release` to `dotnet publish`.
The typo was fixed in my repro steps.

**Comment by paradizelost** [comment]
Can confirm that this breaks pwsh 7.3.0 on linux hosts for me when using scripts with a #!/usr/bin/pwsh shebang as well

**Comment by am11** [comment]
> on Linux/macOS

BTW, this is a linux-only issue. macOS is not involved here. :)

How feasible it is for you to modify the shebang to prepend the process name with `env` (which is recommended)?

```diff
--- old
+++ new

- #!/home/daxian/apps/1self/bin/Release/net7.0/linux-x64/publish/1self
+ #!/usr/bin/env /home/daxian/apps/1self/bin/Release/net7.0/linux-x64/publish/1self
```

It does fix the issue.

If it is not a feasible solution, I'll send a PR to fallback to the old behavior where `namei` is set to the invoked interpreter rather than the script invoking it.

**Comment by vitek-karas** [comment]
@elinor-fung as FYI

@am11 could you please point me to where the change was made which broke this? (I'm just curious how it worked before and now), thanks a lot!

**Comment by am11** [comment]
@vitek-karas, added details in https://github.com/dotnet/runtime/pull/78958.

**Comment by daxian-dbw** [comment]
> BTW, this is a linux-only issue. macOS is not involved here. :)

Oh, I didn't verify on mac myself, but just saw macOS was mentioned in https://github.com/PowerShell/PowerShell/issues/18510. I've removed macOS from the issue description.

> How feasible it is for you to modify the shebang to prepend the process name with env (which is recommended)?

The `env` workaround was already posted in https://github.com/PowerShell/PowerShell/issues/18510#issuecomment-1310352015.
This regression affects PowerShell, and I don't think it's feasible to ask all affected powershell users to use `env` in the shebang. Also, as far as I know, you cannot specify extra parameters when using `#!/usr/bin/env pwsh`, right?

**Comment by paradizelost** [comment]
I agree that it is not feasible to ask people to update all of the scripts they have written to use the env. Also to me it introduces a security issue, i explicitly path my interpreter specifically because i don't want to rely on environment pathing to pick the right executable.

**Comment by am11** [comment]
>  I don't think it's feasible

OK, I was just confirming if on the off-chance it is something you control internally in powershell. I didn't read all comments in other thread.

> security issue

`#!/usr/bin/env bash` is sometimes recommended over `#!/bin/bash` (and AFAIK that's the only way for script to be portable across the Unix based OSes). It is hard to imagine that former has security vulnerabilities.

**Comment by iSazonov** [comment]
Will the fix be backported to 7.0?

**Comment by janvorli** [comment]
I believe we should backport it. I'll create the porting PR. Reopening this issue until the ported fix is merged.

**Comment by szymonos** [comment]
> Also, as far as I know, you cannot specify extra parameters when using #!/usr/bin/env pwsh, right?

@daxian-dbw, you can pass parameters when using `env`, I've posted solution in [PowerShell/PowerShell#18510](https://github.com/PowerShell/PowerShell/issues/18510#issuecomment-1312746133).

**Comment by daxian-dbw** [comment]
@janvorli Thanks for triggering the backporting (https://github.com/dotnet/runtime/pull/79057).
The powershell team needs to plan for a servicing release once the .NET 7.x release including that fix is out.
Do you know if the fix will be included in the January .NET release?

**Comment by daxian-dbw** [comment]
@janvorli Can you please make sure the fix will make to the .NET 7 servicing release for February? Thanks!

**Comment by janvorli** [comment]
@daxian-dbw I got the backport approved for the 7.0.3 release.

**Comment by daxian-dbw** [comment]
It's confirmed the original issue is [fixed](https://github.com/PowerShell/PowerShell/issues/18510#issuecomment-1444420158) with PowerShell v7.3.3, which targets .NET 7.0.3. So now, we can close this issue.
