### ISSUE TITLE
Null ignoring at SelectElements from System.Text.Json at JsonDocumentPathExtensions

### ISSUE THREAD

**Issue by Greenorine** [dotnet/runtime#78963]
### Description

I was trying to parse json with null fields via jsonpath, but got empty array. I checked source code of library methods and didn't find there any option where I can set null handling.

### Reproduction Steps

1. Use this json:
```csharp
const string featuresJson =
                @"{
                  ""files"": [
                    {
                      ""id"": ""90d1aeae-481b-4c82-821b-a034f9aa77cd"",
                      ""document_type"": null
                    }
                  ]
                }";
```           
2. Try to use json.SelectElements("$.files[*].document_type").Select(e => e.HasValue ? (object) e.Value : null);
3. It will return empty array.

### Expected behavior

We have option to include nulls in filter.

### Actual behavior

We can't set excepted behaviour.

**Comment by gregsdennis** [comment]
Related to https://github.com/dotnet/runtime/issues/68128

**Comment by Greenorine** [comment]
What is a possible work-around for SelectElements?

**Comment by eiriktsarpalis** [comment]
What are "SelectElements" and "JsonDocumentPathExtensions"? I don't believe System.Text.Json ships such a components.

**Comment by Greenorine** [comment]
Yep, my wrong. Excuse me. This is library about SelectElements: https://github.com/azambrano/JsonDocumentPath
