### ISSUE TITLE
Remove libraries folders that don't have src/*.cs files

### ISSUE THREAD

**Issue by Jozkee** [dotnet/runtime#78978]
Based on a conversation on https://github.com/dotnet/runtime/pull/78935/files#r1035029354.

It would be nice if we could remove folders that don't generate implementation assemblies because their types were moved to another assembly for unification.

If I browse through `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.0` I can see that there are assemblies that ship with dotnet and don't have a folder or a csproj in our src\libraries. e.g: System.IO.Compression.FileSystem.dll.

Is it possible to remove more folders from libraries in a similar way? 
In case is not possible, what makes System.IO.Compression.FileSystem.dll special?

In case of being possible we could be able to potentially remove all these folders (at least from the ones owned by my area pod):
* System.IO.FileSystem.Primitives
* System.IO.FileSystem
* System.IO.Pipes.AccessControl
* System.IO.UnmanagedMemoryStream
* System.IO
* System.Security.Cryptography.Algorithms
* System.Security.Cryptography.Cng
* System.Security.Cryptography.Csp
* System.Security.Cryptography.Encoding
* System.Security.Cryptography.OpenSsl
* System.Security.Cryptography.Primitives
* System.Security.Cryptography.X509Certificates

**Comment by vcsjones** [comment]
```
System.Security.Cryptography.Algorithms
System.Security.Cryptography.Cng
System.Security.Cryptography.Csp
System.Security.Cryptography.Encoding
System.Security.Cryptography.OpenSsl
System.Security.Cryptography.Primitives
System.Security.Cryptography.X509Certificates
```

All of these assemblies were collapsed in to `System.Security.Cryptography`. However, we need the `ref` assemblies for type forwarding to work. There is also the test consolidation work that is being tracked in #66338.

**Comment by Jozkee** [comment]
> However, we need the ref assemblies for type forwarding to work.

Yes, I'm asking if there's a better way to make type forwarding and why there's no ref project/source for System.IO.Compression.FileSystem.dll. 

If there's no other way, we are meant to keep forever folders of old assemblies whose types were shifted. That may not be a bad thing but it will keep piling-up over the time.

**Comment by ViktorHofer** [comment]
> If I browse through C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.0 I can see that there are assemblies that ship with dotnet and don't have a folder or a csproj in our src\libraries. e.g: System.IO.Compression.FileSystem.dll.

These assemblies are .NETFramework/.NETStandard shims and are still live built but hidden in a subdirectory under [src/libraries/shims](https://github.com/dotnet/runtime/tree/main/src/libraries/shims).

> Is it possible to remove more folders from libraries in a similar way?

We need to keep both the reference and the source assembly building as the ref is exposed in the targeting pack and the lib is part of the runtime pack / shared framework. Removing either one is a breaking change. In general, it would be possible to move these into a subdirectory to hide them but that would require infrastructure adjustments.

**Comment by ViktorHofer** [comment]
@Jozkee @bartonjs @adamsitnik is there anything else that you need from the libraries infrastructure team to make this change? Assuming there isn't any infrastructure work needed, should we break this down into smaller issues for the different area owners?

**Comment by ViktorHofer** [comment]
Let me reopen the issue as I had some time over the weekend to look into this further. The complete list of full facade assemblies (assemblies that only contain type forwards) is:

System.AppContext
System.Buffers
System.Data.DataSetExtensions
System.Diagnostics.Debug
System.Diagnostics.Tools
System.Dynamic.Runtime
System.Globalization
System.Globalization.Calendars
System.Globalization.Extensions
System.IO
System.IO.FileSystem
System.IO.FileSystem.Primitives
System.IO.UnmanagedMemoryStream
System.Reflection
System.Reflection.Extensions
System.Resources.Reader
System.Resources.ResourceManager
System.Runtime.CompilerServices.Unsafe
System.Runtime.Extensions
System.Runtime.Handles
System.Runtime.RuntimeInformation
System.Security.Cryptography.Algorithms
System.Security.Cryptography.Cng
System.Security.Cryptography.Csp
System.Security.Cryptography.Encoding
System.Security.Cryptography.OpenSsl
System.Security.Cryptography.X509Certificates
System.Security.Principal
System.Security.SecureString
System.Text.Encoding
System.Threading.Tasks
System.Threading.Tasks.Extensions
System.Threading.Timer
System.ValueTuple
System.Xml.XmlDocument

All of those should be moved into src/libraries/shims. Some of these typeforward to different assemblies between src and ref but for the ones that typeforward to the same assembly, we only need one assembly (means merging ref and src). I started working on this, here's my draft: https://github.com/dotnet/runtime/pull/89184
