### ISSUE TITLE
ServicePointManager and legacy APIs such as HttpWebRequest

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#78987]
`ServicePointManager` has several properties (mostly security related) which we take into account in legacy APIs, namely in `HttpWebRequest`, `SmtpConnection`, `FtpWebRequest`.
But there are others, which are no-op, leading to confusing behaviors when porting apps from Framework to Core, e.g. `SetTcpKeepAlive`, `Expect100Continue`, `UseNagleAlgorithm` etc.

There are 3 options what to do and we should decide on the course of action:
- Fill in support for these properties in above mentioned legacy APIs (only in them, this no about spreading this to `HttpClient`).
  This would make migration from Framework much easier and possible to do in several separate steps. 
- Another option is to distance ourselves from the legacy and obsolete the whole `ServicePointManager`.
- The last option is to do both, support in legacy APIs and obsoleting.

Related issues about obsoleting: https://github.com/dotnet/runtime/issues/62770 https://github.com/dotnet/runtime/issues/71836

cc @wfurt

**Comment by ManickaP** [comment]
Triage: we agreed this is a lower priority for now, putting to future.

**Comment by karelz** [comment]
Duplicate of #71836
