### ISSUE TITLE
Qustion: How does TryParse decide what to return when there are multiple matching values:

### ISSUE THREAD

**Issue by Korporal** [dotnet/runtime#78985]
Consider

```cs
public enum Words
{
   Houseboat,
   House = Houseboat,
   Barnacle,
   Barn = Barnacle
}
```
The elements `House` and `Houseboat` have the same value, 0 and `Barnacle` and `Barn` have the same value 1.

If I call a (caseless) `TryParse` with "barnacle" and "barn" I get the `enum` member `Barn` returned in each case. Is there anything I can do to get `Enum` member that actually matches the spelling? or is there any way to set it up so I can control which member spelling gets returned? (i.e. if I wanted 'Barnacle' returned in each case rather than 'Barn').

**Comment by MichalPetryka** [comment]
Enums exist only as a numeric value when the code is executing, there's no way to differentiate between two enum elements that have the same value at runtime.
