### ISSUE TITLE
CodeGen infrastructure work planned for .NET 8

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#79018]
This issue collects a set of CLR CodeGen (JIT) inner-loop infrastructure improvements we are planning for .NET 8.

(Related .NET 7 work was tracked with https://github.com/dotnet/runtime/issues/64832)

# Planned for .NET 8

## New SuperPMI-related features

- [ ] Enable NativeAOT collection and replay (Display in AzDo extension)
- [ ] https://github.com/dotnet/runtime/issues/47545
- [x] https://github.com/dotnet/runtime/issues/79015
- [ ] https://github.com/dotnet/runtime/issues/79017
- [x] https://github.com/dotnet/runtime/issues/47543
- [x] https://github.com/dotnet/runtime/issues/68179

## Test merging
- [x] https://github.com/dotnet/runtime/issues/71732
  - [x] [JIT/Regression(1312 tests)](https://github.com/dotnet/runtime/pull/83895)
  - [x] [JIT/jit64 (828 tests)](https://github.com/dotnet/runtime/pull/83151)
  - [x] JIT/CodeGenBringUpTests (641 tests)
  - [x] [JIT/Directed (541 tests)](https://github.com/dotnet/runtime/pull/83256)
  - [x] [JIT/IL_Conformance (378 tests)](https://github.com/dotnet/runtime/pull/80597)
  - [x] [baseservices/threading (231 tests)](https://github.com/dotnet/runtime/pull/83143)

In addition, there is a list of usability issues (also in https://github.com/dotnet/runtime/issues/71732).

## Bug fix level changes

- [x] https://github.com/dotnet/runtime/issues/75169
- [x] https://github.com/dotnet/runtime/issues/76421
- [ ] https://github.com/dotnet/runtime/issues/60947
- [x] https://github.com/dotnet/runtime/issues/80718

**Comment by JulieLeeMSFT** [comment]
We will move the remaining items to .NET 9.
