### ISSUE TITLE
superpmi: add real world benchmarks collection

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#79015]
We currently have a SuperPMI collection of the microbenchmarks from the dotnet/performance repo (https://github.com/dotnet/performance/tree/main/src/benchmarks/micro).

Recently, more "real world" benchmarks have been added, and the dotnet performance lab started running regular performance measurements of these (https://github.com/dotnet/performance/tree/main/src/benchmarks/real-world).

Add a new SuperPMI collection of these real-world benchmarks.

The proposal is to create a separate, new collection, instead of adding the real-world collection to the existing micro-benchmark collection. The reason is to make sure asm diffs changes in the real-world benchmarks are separately highlighted.

**Comment by kunalspathak** [comment]
Completed in https://github.com/dotnet/runtime/pull/87104
