### ISSUE TITLE
[API Proposal] Expose `System.String` static methods as string extensions

### ISSUE THREAD

**Issue by scarletquasar** [dotnet/runtime#79020]
### Background and motivation

Since I started to code in C#, I wonder why some "primitive" methods are static ones instead of being just extensions. The main one is `string.IsNullOrEmpty` (can also be `string.IsNullOrWhiteSpace`), I can see my coworkers making custom extensions to be able to use these methods directly from a string for example. Is there a concrete motivation to not have these extensions nowadays?

### API Proposal

Implementations like:

```csharp
public static bool IsNullOrEmpty(this string target)
{
    return string.IsNullOrEmpty(target);
}
```

```csharp
public static bool IsNullOrWhiteSpace(this string target)
{
    return string.IsNullOrWhiteSpace(target);
}
```

### API Usage

Extensions like:

```csharp
void doSomethingWhenValidString(string test)
{
    if(!test.IsNullOrWhiteSpace()) 
    {
        //do something...
    }
}
```

```csharp
void doSomethingWhenValidString(string test)
{
    if(!test.IsNullOrEmpty()) 
    {
        //do something...
    }
}
```

**Comment by TonyValenti** [comment]
Yes. I would love this. I've actually made a ton of extension methods that do exactly this.

**Comment by MSDN-WhiteKnight** [comment]
Extension methods are plagued by conflicts issue: https://github.com/dotnet/runtime/issues/78530 , https://github.com/morelinq/MoreLINQ/issues/351 When there are two extension methods with the same signature in current scope, C# compiler errors out and there's no sane way to resolve the conflict. Because of this, if such methods are added, preferably they should not be in System namespace as it's imported everywhere.

**Comment by victoriaquasar** [comment]
> Extension methods are plagued by conflicts issue: #78530 , [morelinq/MoreLINQ#351](https://github.com/morelinq/MoreLINQ/issues/351) When there are two extension methods with the same signature in current scope, C# compiler errors out and there's no sane way to resolve the conflict. Because of this, if such methods are added, preferably they should not be in System namespace as it's imported everywhere.

If preferred, these methods can be also added as instance methods

**Comment by strangeman375** [comment]
Adding this extensions will lead to incorrect usage, such as^
`if (str?.IsNullOrEmpty() ?? true)
{
    ...
 }
 `

**Comment by gfoidl** [comment]
> I wonder why some "primitive" methods are static ones instead of being just extensions. The main one is `string.IsNullOrEmpty`

History. `string.IsNullOrEmpty` is there since .NET Framework 2.0, and extension methods got added to C#  3 together with .NET Framework 3.5.

**Comment by jkotas** [comment]
`string.IsNullOrEmpty` cannot be an instance method. It would throw NullReferenceException instead of returning false when called on a null string instance.

**Comment by strangeman375** [comment]
>     Adding this extensions will lead to incorrect usage, such as: if (str?.IsNullOrEmpty() ?? true) { ... }
> 
> why is that an incorrect usage? Sorry I don't see it.

Dumbo coders will treat this extensions as instance methods and will do nullcheck before invoke them

**Comment by stephentoub** [comment]
Thanks for the suggestion. We're not going to add IsNullXx extension methods as they're inherently confusing given that they syntactically look like they're calling a method on an instance that could be null.

**Comment by tacosontitan** [comment]
> Thanks for the suggestion. We're not going to add IsNullXx extension methods as they're inherently confusing given that they syntactically look like they're calling a method on an instance that could be null.

Isn't it well-defined that extension methods can be invoked on `null` instances?

I can see the confusing part being the fact that you can't tell at a glance whether it's an instance or extension method, but developers should be validating for `null` before invoking either, 9 times out of 10 right?

<sub>Not trying to reopen, just trying to understand the decision.</sub>

**Comment by scarletquasar** [comment]
> Thanks for the suggestion. We're not going to add IsNullXx extension methods as they're inherently confusing given that they syntactically look like they're calling a method on an instance that could be null.

The IDE explicitly tells you that is an extension method, but ok.

**Comment by stephentoub** [comment]
> developers should be validating for null before invoking either, 9 times out of 10 right?

That's part of the point: validating for null before calling a method whose purpose is to validate for null is superfluous.
