### ISSUE TITLE
On Windows File.CreateSymbolicLink method does not create a working symlink in case the pathToTarget parameter is a relative path with forward slashes

### ISSUE THREAD

**Issue by Ev2geny** [dotnet/runtime#79031]
### Description

[File.CreateSymbolicLink ](https://learn.microsoft.com/en-us/dotnet/api/system.io.file.createsymboliclink?view=net-6.0 )method does not create a working symlink in case the **pathToTarget** parameter is a relative path with forward slashes. This makes the functionality of **File.CreateSymbolicLink** not self-consistent, as in 3 out of 4 cases it does correctly handle forward slashes. 

3 cases are: 

- **path** parameter absolute path, 
- **path** parameter relative path,  
- **pathToTarget** absolute path

And only **pathToTarget** relative path is not working correctly

### Reproduction Steps

This code shows the problem

```C#
using System;
using System.IO;

/*
 * Setup for test in the visual studio project directory bin\Debug\net6.0
 * 
 * C# Visual Studio Project Path\bin\Debug\net6.0\dir
 *                                                 |
 *                                                 |-- subdir
 *                                                      |
 *                                                      |-- file.txt
 *       
*/

class TestSymbolicLink
{
    public static void Main()
    {
        // This creates a working relative symlink
        File.CreateSymbolicLink(@"dir\relative_link_back_slash", @"subdir\file.txt");

        // This creates a working absolute symlink (change exact path for your case)
        File.CreateSymbolicLink("dir/absolute_link_forward_slash", "C:/_code/C#/symlink/bin/Debug/net6.0/dir/subdir/file.txt");

        // !!!!!!  This creates a relative symlink , but the symlink is not working 
        File.CreateSymbolicLink("dir/relative_link_forward_slash", "subdir/file.txt");
    }
}
```

### Expected behavior

The relative symlink with a target path with forward slashes shall be working

### Actual behavior

The relative symlink with a target path with forward slashes is not working

### Regression?

NO

### Known Workarounds

Make sure on Windows the **pathToTarget** parameter contains only back slashes as a path separator in case of a relative path. 

### Configuration

Windows 10
net6.0

### Other information

This is most likely caused by the Win32 API [CreateSymbolicLinkW ](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createsymboliclinkw), which .net is calling and even [present in the Windows mklink command.](https://github.com/python/cpython/issues/57911#issuecomment-1296356687)

See more description in the  
**Developer community issue**
https://developercommunity.visualstudio.com/t/CreateSymbolicLinkW-function-incorrectly/10208725

**Feedback hub issue:** (requires usage of the [Feedback Hub](https://learn.microsoft.com/en-us/windows-insider/feedback-hub/feedback-hub-app))
https://aka.ms/AAirrwf

Related issue for **Python** https://github.com/python/cpython/issues/57911:

**Comment by Jozkee** [comment]
IMO CreateSymbolicLinkW works fine, the problem is with Windows Explorer that is unable to understand a relative link target with forward slashes.

[`LinkTarget`](https://learn.microsoft.com/dotnet/api/system.io.filesysteminfo.linktarget) property retrieves said target properly and the `dir` utility in cmd is also able to show the target with forward slashes so I don't think we should go and introduce a fix that replaces slashes with backslashes before we hear from the Windows folks.

Since the VS Feedback ticket was closed, I'd suggest that you file a bug report to Windows as they suggested [here](https://developercommunity.visualstudio.com/t/CreateSymbolicLinkW-function-incorrectly/10208725#T-N10209183).
