### ISSUE TITLE
ILCompiler --make-repro-path improvements

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/runtime#79032]
When ILCompiler creates a repro package several options are handled incorrectly and stored in the `repro.rsp` file.
## Issues
1. Command line options: `--root`, `--conditionalroot`, `--trim` can accept assembly names or paths to assemblies as values.
If the latter is used, the `repro.rsp` file will have incorrect paths specified, since in general all paths should be converted to the relative ones (relative to the repro package). Currently, this does not happen for these options and can cause AOT compilation failures.
2. Command line options: `--conditionalroot`, `--trim` if not present in the original response file, will be emitted to the `repro.rsp` without a value, which is not acceptable by the compiler.
3. Command line options: `-o` (or `--out`) and `--exportsfile` are just copied over to the `repro.rsp`. These options can point to non-existing directories for the output files and will break the compiler.

## Suggestions
1. Use the same principle as with `-r` (or `--reference`) when a path to assembly is specified for `--root`, `--conditionalroot`, `--trim` options
2. Do not output options without a value
3. Create folders inside of the repro package for the output command-line options, and adjust their values with the relative paths 
    a) The created folders in repro package should be prefixed with `_in_` if they refer to an input option and `_out` if they refer to an output option

**Comment by MichalStrehovsky** [comment]
Thank you for opening this!

1. I looked at the code and it looks like if assembly name is passed to `--root` and co, we would throw and catch an exception while creating the copy of the file and skip rewriting the argument - which means we'll be fine. Would be good to validate this, but if it works like that, it removes my concern.
2. Yes, this looks like another difference in behavior with System.CommandLine.
3. We could flatten it like Vitek suggested (it's easier to delete the state as one is iterating on debugging), but maybe if we want it to be general purpose a separate directory for each would be better. If it's possible, I would only prefix the output ones and leave input ones as 0, 1, 2, 3. It looks "nicer" for tools that don't write output files and use this repro mechanism (like r2rdump).
