### ISSUE TITLE
Compiler error CS0121 With .NET 7 in BitConverter.GetBytes 

### ISSUE THREAD

**Issue by winxp2002** [dotnet/runtime#79034]
the code  on .NET 7 contains complier errors, I think the Compiler  override wrong method ,it work well on .NET 6 

`BitConverter.GetBytes((byte)value)`
` BitConverter.GetBytes((sbyte)value)`

The call is ambiguous between the following methods or properties: 'BitConverter.GetBytes(Half)' and 'BitConverter.GetBytes(short) '

**Comment by dakersnar** [comment]
This is technically a breaking change, although the use case doesn't seem particularly common. If the goal is to convert a byte into a byte array, this can be trivially done with `new byte[] { (byte)value }`. 

> If you think calling BitConverter.GetBytes with 1-byte types is useful and you would like it to work in some future version of .Net (it's very likely too late for .Net 7), you can [open an API suggestion in the dotnet/runtime repo](https://github.com/dotnet/runtime/issues/new/choose) for adding byte and sbyte overloads.

Seconded this point. I'm closing this for now, but feel free to open that proposal following our template.
