### ISSUE TITLE
Does MAUI not trust Android user-added root CAs?

### ISSUE THREAD

**Issue by Ghostbird** [dotnet/runtime#79041]
### Description

I'm porting a Xamarin Forms app to MAUI. Currently I'm stuck at the OIDC auto-discovery.
Any attempt to make an HTTP connection to the identity server immediately throws an exception with the message: _Trust anchor for certification path not found_

### Reproduction Steps

I run my Identity server using an API certificate signed by my company root CA
This certificate is imported as trusted root CA on my Android test device
I run my app, and make _any_ HTTP call to my identity server.

[Here](https://github.com/Ghostbird/maui-reproduction)'s a minimal reproduction scenario that includes all necessary set-up:
- Script to generate CA root and API certificate
- Minimal .NET 7.0 API with single get endpoint that returns "success" and runs with generated API certificate TLS by default
- Minimal .NET 7.0 MAUI Android app with a single button that triggers the error

### Expected behavior

Call succeeds using TLS

### Actual behavior

Call fails because: _Trust anchor for certification path not found._

### Regression?

Compared to Xamarin Forms: yes
Compared to earlier MAIU versions: I don't know

### Configuration

|                        |                                |
| ---------------------- | ------------------------------ |
| Description            | Debian GNU/Linux 11 (bullseye) |
| Release                | 11                             |
| Codename               | bullseye                       |
| Dotnet                 | dotnet 7.0.100                 |
| Android Debug Bridge   | version 1.0.41                 |
| SDK Version            | 33.0.3-8952118                 |
| Device Android Version | 12                             |
| Device Android API     | 32                             |

| Installed Workload Id | Manifest Version | Installation Source |
| --------------------- | ---------------- | ------------------- |
| maui-android          | 7.0.49/7.0.100   | SDK 7.0.100         |
| android               | 33.0.4/7.0.100   | SDK 7.0.100         |

### Other information

This set-up has always worked with Xamarin on both iOS and Android, and is also used for our web-app debugging on Window, MacOS and GNU/Linux, and as far as I understand TLS, _should_ work, because it in no way differs from how any website on the internet is trusted using TLS.

- `cacert.pem` custom root CA, imported as trusted root CA on all debug devices.
- `api.pfx` certificate used by Kestrel running .NET 7.0 web api in debug mode. Signed using the `cacert.pem`.
- The debug devices' DNS server points `debugger.conneqt.local` correctly to the machine running the authority.

The API certificate is in fact fully trusted by the OS and it extends that trust to supporting software, if I browse to that URI in Google Chrome, Samsung's browser or a [properly configured](https://android.stackexchange.com/a/245762) Firefox the certificate is validated and trusted.

- On the non-ported Xamarin Forms app the same code works, on the same device.
- This same MAUI app does _not_ throw the exception when I change the URI to our production identity server.

I saw a few other issues that raise this exception, but they all seem to involve using Android specific code, or bypassing TLS validation entirely. I didn't find only one that seemed to be applicable to my use case.

To be clear, I'm not looking for a way to get it working with a different mechanism, with some debug-only exception, or Android-only code. The current approach was explicitly chosen, because it should in no way differ how normal TLS website trust works, and therefore should work perfectly regardless of the platform used. I'm looking for what's going wrong, and what I can do to make _this_ work once again.

**Comment by simonrozsival** [comment]
If the certificate is installed system-wide, it should just work. I'll look into it.

**Comment by vcsjones** [comment]
With Android I believe you need to modify `<trust-anchors>` to trust user-added certificates starting in Android N. Your app needs to opt-in to user-added certificates. According to the [docs](https://developer.android.com/training/articles/security-config#TrustingAdditionalCas) you probably need something like this in your security manifest:

```xml
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>  
      <base-config>  
            <trust-anchors>  
                <certificates src="system" />  
                <certificates src="user" />  
           </trust-anchors>  
      </base-config>  
 </network-security-config>
```

I don't see `trust-anchors` anywhere in your sample application.

Further down in the documentation where it states "The default configuration for apps targeting Android 7.0 (API level 24) to Android 8.1 (API level 27) is as follows:" you can see that, by default, Android Apps only trust `system` certificates.

Note the definition of `system` and `user`:

> * "system" for the pre-installed system CA certificates
> * "user" for user-added CA certificates

"System" means pre-installed, so that does not cover things added by the user.

**Comment by Ghostbird** [comment]
Thank you so much. That seems very likely. I'll try it first thing tomorrow.
Is this a change from Xamarin Forms? Our latest Xamarin Forms build does not have this issue. It targets API 25+ and is built using API 32.

**Comment by Ghostbird** [comment]
Why did my browser suddenly close this issue?

Never mind, I've tried the solution, and updated the reproduction repo. It doesn't seem to solve the issue. Could you have another look and see if I have implemented it incorrectly? Thanks in advance.
