### ISSUE TITLE
CookieContainer doesnt work

### ISSUE THREAD

**Issue by planyazilim** [dotnet/runtime#79055]
### Description

While posting HttpClient with CookieContainer Code works on XamarinForms doesnt work on .Net Maui

### Steps to Reproduce
```c#
            var content = new MultipartFormDataContent();
            content.Add(new StringContent("myvalue1"), "myvalu1");
            content.Add(new StringContent("myvalue2"), "myvalue2");

            var cookieContainer = new CookieContainer();
            var handler = new HttpClientHandler() { CookieContainer = cookieContainer };
            var client = new HttpClient(handler);

            cookieContainer.Add(new Uri(myUri), new Cookie(myCookie));

            var response = await client.PostAsync("https://www.mylinkpage.com/AddPic/", content);
```

### Link to public reproduction project repository

none

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android

### Did you find any workaround?

No

### Relevant log output

```shell
No
```

**Comment by steveisok** [comment]
@planyazilim I'm assuming the URI in `myURI` matches what you're passing, correct? The default `AndroidMessageHandler` is using the request URI as the key:

https://github.com/xamarin/xamarin-android/blob/2a26c1e96fcd8f478b0e5e578754c35fa280f0e0/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs#L1023-L1025

/cc @simonrozsival

**Comment by planyazilim** [comment]
@steveisok yes uri is correct and no problem with xamarin forms. .net maui doesnt work.

**Comment by simonrozsival** [comment]
I couldn't replicate this issue with the code snippet. The cookies I add to the cookie container are correctly sent to the server (both using the native handler and the sockets handler).

@planyazilim could you create a runnable project that repros the issue and put it on github so I can use it to reproduce the issue?

**Comment by planyazilim** [comment]
@simonrozsival @steveisok @akoeplinger @jsuarezruiz @jonathanpeppers @MihaZupan

**Comment by planyazilim** [comment]
@simonrozsival @steveisok @akoeplinger @jsuarezruiz @jonathanpeppers @MihaZupan
@simonrozsival unfortunately returning results will not be meaningul if I put it on github.

I thought problem was with Cookiecontainer but I am not really sure I added the line below
"var cookies = cookieContainer.GetCookies(new Uri("https://www.mypage.com/"))" and cookie value is correct.

But I tested 100 times, same code working on Xamarin Forms, doesnt work on .Net 7 Maui.
if it is not a bug, what i may be missing i dont know.

            var content = new MultipartFormDataContent();
            string ilanno = "\"" + ilanno_deg.ToString() + "\"";

            content.Add(new StreamContent(stream), ilanno, "\"" + FileName + "\"");

            content.Add(new StringContent("bekle"), "bekle");
            content.Add(new StringContent("ilanno"), "ilanno");
            var cookieContainer = new CookieContainer();
            var handler = new HttpClientHandler() { CookieContainer = cookieContainer };
            var client = new HttpClient(handler);

            cookieContainer.Add(new Uri("https://www.mypage.com"), new Cookie("IelModule", ilkSayfa.uye.Cookie_Id));
            var response = await client.PostAsync("https://www.mypage.com/ara/Yukle", content);
            string CreateTicketResponse = response.Content.ReadAsStringAsync().Result;
            string StatusLabel = response.StatusCode.ToString();

            var cookies = cookieContainer.GetCookies(new Uri("https://www.mypage.com"));
            for (var i = 0; i < cookies.Count; i++)
            {
                string cookieValue = cookies[i].Value;
                string cookieDomain = cookies[i].Domain;
                string cookieName = cookies[i].Name;
            }

**Comment by simonrozsival** [comment]
@planyazilim could you please try running the following code? It will run against httpbin.com and that will take your server out of the equation.

```csharp
var url = new Uri("https://httpbin.org");
var cookieContainer = new CookieContainer();
cookieContainer.Add(url, new Cookie("clientcookie", "clientvalue"));

var handler = new HttpClientHandler { CookieContainer = cookieContainer };
var client = new HttpClient(handler);

var content = await client.GetStringAsync($"{url}/cookies/set/servercookie/servervalue");
Console.WriteLine(content);

Console.WriteLine("CookieContainer:");
var cookies = cookieContainer.GetCookies(url);
for (int i = 0; i < cookies.Count; i++)
{
    Console.WriteLine($"[{cookies[i].Domain}] {cookies[i].Name}: {cookies[i].Value}");
}
```

The output you should be getting in console is:

```
[DOTNET] {
[DOTNET]   "cookies": {
[DOTNET]     "clientcookie": "clientvalue", 
[DOTNET]     "servercookie": "servervalue"
[DOTNET]   }
[DOTNET] }
[DOTNET] CookieContainer:
[DOTNET] [httpbin.org] clientcookie: clientvalue
[DOTNET] [httpbin.org] servercookie: servervalue
```

**Comment by planyazilim** [comment]
@simonrozsival thank you fro your answer. I really appreciate. Your Code works well. This part works for me also
But I need to post MultipartFormDataContent with cookie. When I add the MultipartFormDataContent content lines. I should trigger  PostAsync then I get Status OK and 200 like it is successfull but at details Content gets **Android**.OS.NetworkOnMainThreadException** error. I started to think my problem may not be related  with cookie, but what may be i am really stuck. Same code wotks well with Xamarin Forms. But not with .Net 7 Maui App.

**Comment by simonrozsival** [comment]
@planyazilim Thanks for letting us know. Feel free to reach out if you run into any other problems.
