### ISSUE TITLE
[API Proposal]: Add [Generated] attribute to source-generated code 

### ISSUE THREAD

**Issue by dominoFire** [dotnet/runtime#79067]
### Background and motivation

Very similar to the [@Generated Java annotation](https://docs.oracle.com/javase/8/docs/api/javax/annotation/Generated.html), I think we need an attribute to decorate code that was computer-generated.

This will help in source review code to indicate readers that code was generated.

Also, you can use reflection to perform tasks in source-generated code, such as, avoid applying CodeAnalyzer rules to source-generated code, to avoid flags that users cannot solve.

### API Proposal

```csharp
namespace System.Collections.Generic;

[SourceGenerated]
public class MyFancyCollectionGenerated<T> : IEnumerable<T>
{
    [SourceGenerated]
    public void FancyGernerated(T item);
}
```

### API Usage

In a simple T4 template, you can just write

```csharp
WriteLine("[SourceGenerated]");
WriteLine("public class MyGeneratedClasss");
// ...
```

### Alternative Designs

Users who want this attribute can also add a very simple custom attribute in their codebases.

### Risks

- Old source-generated code will need to be regenerated with a new SDK version.
- The name should be chosen to avoid name-clashes with existing code.

**Comment by ufcpp** [comment]
![image](https://user-images.githubusercontent.com/3760955/204957977-81c49db8-68d6-421d-b527-052b0934bc76.png)

**Comment by stephentoub** [comment]
How would this differ from https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.compilergeneratedattribute?

**Comment by dominoFire** [comment]
At first sight, I thought [CompilerGenerated] was intended to use only inside .NET compiler stuff, not user, source-generated source code.

I didn't know aboud [GeneratedCode] attribute. If it's able to public consumption, that would be great.

**Comment by stephentoub** [comment]
> I didn't know aboud [GeneratedCode] attribute. If it's able to public consumption, that would be great.

Yes, it's public.
