### ISSUE TITLE
Want remove more boundary checks in loops

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#79075]
### Description

The compiler now removes the boundary check in the loop when accessing the current element.
In real code, we often access the previous or next element of an array. In doing so, we explicitly shift the boundary check, e.g. instead of `i=0` we make `i=1`, or instead of `i < array.Length` we make `i < array.Length-1`. Notice, we can make `i=33` and `i < array.Length-33`. The example below shows that the compiler isn't optimizing this kind of code today, even though it could.

### Configuration

```c#
using System;
public class C {
    public void M() {
        var h = new char[100];
        for (int j = h.Length - 2; j > 0; j--)
        {
            //Console.WriteLine(h[j]); // Ok, removed
            //Console.WriteLine(h[j+1]); // Ops!
            //Console.WriteLine(h[j-1]); // Ops!
        }

    }

    public void M2() {
        var h = new char[100];
        for (int i = 1; i < h.Length - 2; i++)
        {
            //Console.WriteLine(h[i]); // Ok, removed
            //Console.WriteLine(h[i+1]); // Ok, removed
            //Console.WriteLine(h[i-1]); // Ops!
        }
    }
}
```

### Regression?

No.

**Comment by gfoidl** [comment]
Similar https://github.com/dotnet/runtime/issues/9505, https://github.com/dotnet/runtime/issues/31638

**Comment by EgorBo** [comment]
Thanks, closing as a dup in favor of https://github.com/dotnet/runtime/issues/31638 that contains this case
