### ISSUE TITLE
[workloads] Add prerelease version to workload manifest location

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#79086]
We can avoid problems in the future by making sure prerelease workload manifests don't end up in the stable band directory and we should do this before net8-preview 1

**Comment by lewing** [comment]
@dsplaisted what do we need to do here?

**Comment by dsplaisted** [comment]
The version band is already included in the package ID, for example 7.0.100 in `Microsoft.NET.Workload.Mono.ToolChain.net6.Manifest-7.0.100`.  So you should update the package IDs to include the preview band, for example `Microsoft.NET.Workload.Mono.ToolChain.net8.Manifest-8.0.100-preview.1`.

Does that help?

**Comment by radical** [comment]
@dsplaisted ping

**Comment by steveisok** [comment]
@radical if I understand this correctly, I think the band in the sdk-manifest folder path should be 8.0.100. The manifest inside that folder will contain prerelease info in the name.

**Comment by dsplaisted** [comment]
> @radical if I understand this correctly, I think the band in the sdk-manifest folder path should be 8.0.100. The manifest inside that folder will contain prerelease info in the name.

This is not correct.  The folders under the `sdk-manifests` folder are the version bands, and may include the prerelease specifier.

> What is the expected behavior here? Does the workload resolver expect to find all the manifests in the same `sdk-manifest/8.0.100-dev`? Should the emscripten manifest be installed to the same band, somehow?

The resolver does not need all of the manifests to be in the same band.  If a workload is listed in `IncludedWorkloadManifests.txt`, then the resolver will first look for the manifest in the current band folder, but if it's not found there will fall back through the earlier version bands in the `sdk-manifests` folder.

> The task tries to now find the Emscripten manifest also, and builds up the package name using `SdkBandVersion=8.0.100-dev` - `Microsoft.NET.Workload.Emscripten.net7.Manifest-8.0.100-dev`. But that package doesn't exist, for obvious reasons.

Why doesn't the package exist?  Is Emscripten using different preview specifiers that runtime is?  If so you may have to have some way for the tests to have a way to find the Emscripten band to use.

**Comment by radical** [comment]
> > What is the expected behavior here? Does the workload resolver expect to find all the manifests in the same `sdk-manifest/8.0.100-dev`? Should the emscripten manifest be installed to the same band, somehow?
> 
> The resolver does not need all of the manifests to be in the same band. If a workload is listed in `IncludedWorkloadManifests.txt`, then the resolver will first look for the manifest in the current band folder, but if it's not found there will fall back through the earlier version bands in the `sdk-manifests` folder.

Ah, that sounds good!

> > The task tries to now find the Emscripten manifest also, and builds up the package name using `SdkBandVersion=8.0.100-dev` - `Microsoft.NET.Workload.Emscripten.net7.Manifest-8.0.100-dev`. But that package doesn't exist, for obvious reasons.
> 
> Why doesn't the package exist? Is Emscripten using different preview specifiers that runtime is? If so you may have to have some way for the tests to have a way to find the Emscripten band to use.

@steveisok @lewing I guess, we need to update emsdk to use an updated sdk band first.

**Comment by lewing** [comment]
> The version band is already included in the package ID, for example 7.0.100 in `Microsoft.NET.Workload.Mono.ToolChain.net6.Manifest-7.0.100`. So you should update the package IDs to include the preview band, for example `Microsoft.NET.Workload.Mono.ToolChain.net8.Manifest-8.0.100-preview.1`.
> 
> Does that help?

aren't we very short on characters here?

**Comment by lewing** [comment]
@dsplaisted is it the nupkg name that matters or the msi name?

**Comment by dsplaisted** [comment]
It's the nupkg name that matters.  I think the MSI name can be pretty much anything (though there may be some assumptions baked into the MSI generation tooling).

**Comment by lewing** [comment]
I think we can do the prerelease versioning on the nupkg without causing path problems in that case, so we are unblocked with making changes

**Comment by joeloff** [comment]
Yup, the package ID is what's primarily used when it generates the file names. Some level of uniqueness is required because the files end up in a flat container for the VS insertion (zip file) and on AzDo as a published artifact.
