### ISSUE TITLE
[QUERY] Issue Implementing High Performance Logger when switching to .net6.0 

### ISSUE THREAD

**Issue by jsquire** [dotnet/runtime#79087]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#32789](https://github.com/Azure/azure-sdk-for-net/issues/32789).

### Library name and version

Microsoft.Extensions.Logging

### Query/Question

Getting this error message when using the High Performance Logger (https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/loggermessage?view=aspnetcore-6.0): 

System.TypeInitializationException : The type initializer for 'Log' threw an exception.
---- System.ArgumentNullException : Value cannot be null. (Parameter 'format')

Even when the build is successful and the formatString is being passed in: 

private static readonly Action<ILogger, string, Exception> DebugLoggerMessage = LoggerMessage.Define<string>(
                LogLevel.Debug,
                Events.Started,
                "{Param1}");

I am unable to debug this line, but up until this line of code the lambda expression seem to be passing all necessary parameters in into the functions properly. 
Would like to get some help on whether someone has ran into this problem before or if anyone has any insight. 

Thanks

### Environment

net6.0

**Comment by tarekgh** [comment]
@eltonchan0128
Can you please provide a sample app to reproduce this issue? The provided information is not enough to help with.
