### ISSUE TITLE
Remove hardcoded TFM in wasm build files

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#79109]
The WasmAppNative.targets file hardcodes the TFM in two places:
- https://github.com/dotnet/runtime/blob/main/src/mono/wasm/build/WasmApp.Native.targets#L283
- https://github.com/dotnet/runtime/blob/41f57b7862dca221687a6cb638c35e33ee8e25db/src/mono/wasm/build/WasmApp.Native.targets#L555

This makes reving the TFM i.e., from net7.0 to net8.0 harder. Also, this component is shipping to customers and should use by the SDK provided values instead.

https://github.com/dotnet/runtime/blob/41f57b7862dca221687a6cb638c35e33ee8e25db/src/mono/wasm/build/WasmApp.targets#L223 uses the SDK provided `ResolvedRuntimePack` msbuild item. Even though that item itself doesn't offer a metadata that informs about the matching TFM, another item in the SDK should be available, i.e. `KnownRuntimePack` that includes the `TargetFramework` as metadata.

Noticed in https://github.com/dotnet/runtime/pull/78354/

cc @radical

**Comment by radical** [comment]
> Also, this component is shipping to customers and should use by the SDK provided values instead.
> https://github.com/dotnet/runtime/blob/41f57b7862dca221687a6cb638c35e33ee8e25db/src/mono/wasm/build/WasmApp.targets#L223
> 
> uses the SDK provided `ResolvedRuntimePack` msbuild item. Even though that item itself doesn't offer a metadata that informs about the matching TFM, another item in the SDK should be available, i.e. `KnownRuntimePack` that includes the `TargetFramework` as metadata.

How do I find the "matching" `KnownRuntimePack` item from the available `ResolvedRuntimePack`?
