### ISSUE TITLE
Different code execution on Mac/Windows

### ISSUE THREAD

**Issue by mkalinski93** [dotnet/runtime#79139]
### Description

I was tasked to create a CurrencyConverter for our company.
We download a .zip file from the ECB and parse two lines of csv into our datastore.

The problem is just one line of code which runs on our production environment extremely different.

```csharp
string[] lines = value.Split(Environment.NewLine).Take(2).ToArray();
```

We use macos for our development environment and the code returns exactly the first 2 lines of the splitted string.
When we run it on our Windows Server 2016 machine, it will return all values.

On mac it is absolutely working as expected. 
Please let me know if you need further information.

### Reproduction Steps

```csharp
string fetchUrl = "https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist.zip";

using HttpClient client = new HttpClient();
HttpResponseMessage response = await client.GetAsync(fetchUrl);

string value = string.Empty;
using ZipArchive zipFile = new ZipArchive(await response.Content.ReadAsStreamAsync(), ZipArchiveMode.Read);
using MemoryStream memoryStream = new MemoryStream();
foreach (ZipArchiveEntry zipArchiveEntry in zipFile.Entries) {
    await using Stream entryStream = zipArchiveEntry.Open();
    await entryStream.CopyToAsync(memoryStream);
}

value = Encoding.ASCII.GetString(memoryStream.ToArray());

//On windows, it return all values
string[] lines = value.Split(Environment.NewLine).Take(2).ToArray();
//On windows, this somehow runs into an OutOfRangeException for no reason?!?
string[] headers = lines[0].Split(",");
string[] exchanges = lines[1].Split(",");
List<CurrencyExchange> exchangeCollection = new List<CurrencyExchange>();

int length = headers.Skip(1).Count();
for (int i = 1; i < length; i++) {
    CurrencyExchange exchange = new CurrencyExchange(headers[i], exchanges[i]);
    exchangeCollection.Add(exchange);
}
```

### Expected behavior

string[] should contain 2 lines

### Actual behavior

string[] gets all lines and fails execution in the upcomming steps on windows

### Configuration

dotnet version mac: 6.0.401
dotnet version on Server: 6.0.2

macos: 13.0 (22A380)
Windows Server 2019: 10.0.17763 Build 17763

**Comment by MichalStrehovsky** [comment]
You're using [`Environment.NewLine`](https://learn.microsoft.com/en-us/dotnet/api/system.environment.newline?view=net-7.0) to split which has the documented difference between Windows and non-Windows.

Replace that with `"\n"` and it will work.

**Comment by mkalinski93** [comment]
That makes absolutely sense.
Thank you for your time.
