### ISSUE TITLE
Is it expected that the host.native subset fails on a fresh build (when the single file host isn't yet built)?

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#79144]
The NativeAOT libraries linker tests don't require the singlefilehost but the apphost but building the `host.native` fails if the single file host isn't yet built. Is that intentional? If the singlefilehost is a strong dependency to build `host.native` then we should update the Subset description to indicate that.

cc @agocke @sbomer 

```
C:\git\runtime2>build.cmd host.native -c Release
  Determining projects to restore...
  Tool 'coverlet.console' (version '3.1.2') was restored. Available commands: coverlet
  Tool 'dotnet-reportgenerator-globaltool' (version '5.0.2') was restored. Available commands: reportgenerator
  Tool 'microsoft.dotnet.xharness.cli' (version '1.0.0-prerelease.22566.1') was restored. Available commands: xharness
  Tool 'microsoft.visualstudio.slngen.tool' (version '8.5.17') was restored. Available commands: slngen
  Tool 'dotnet-format' (version '6.0.240501') was restored. Available commands: dotnet-format

  Restore was successful.
  All projects are up-to-date for restore.
  Determining projects to restore...
  All projects are up-to-date for restore.
  InjectResource -> C:\git\runtime2\artifacts\bin\coreclr\windows.x64.Release\InjectResource\InjectResource.dll
C:\git\runtime2\src\native\corehost\corehost.proj(48,5): error MSB3030: Could not copy the file "C:\git\runtime2\artifacts\bin\coreclr\windows.x64.Release\/corehost/si
nglefilehost.exe" because it was not found.
```

**Comment by jkoritzinsky** [comment]
The singlefilehost.exe file gets copied to the correct output directory and gets the (signed) DAC injected as a resource as part of the host.native build.

**Comment by ViktorHofer** [comment]
That explains the current state and what the project is responsible for. What I'm interested in knowing is, how can we build just the apphost (ie for the linker nativeaot tests) without requiring the singlefilehost and the runtime to be built?

**Comment by agocke** [comment]
I think that the single file host is now a requirement. I believe `host.native` also includes hostpolicy and hostfxr, and those are now built with the runtime, since the singlefilehost now builds directly with the runtime.

**Comment by jkoritzinsky** [comment]
The `hostpolicy` and `hostfxr` code is built twice, once as a static lib with the CoreCLR build for `singlefilehost`, and once in the `host.native` build for the shared libraries.

**Comment by ViktorHofer** [comment]
Bringing this up again. Can we change the host.native subset (or to be more precise, corehost.proj) so that we can just build the apphost without the singlefilehost? The NativeAOT libraries tests don't need any of the clr.runtime stuff, so not building that would be preferred.

Presumably, the NativeAOT libraries tests don't even need the apphost but that's currently a requirement in the SDK (when building SelfContained, the UseAppHost switch must be true).

**Comment by agocke** [comment]
> Can we change the host.native subset (or to be more precise, corehost.proj) so that we can just build the apphost without the singlefilehost?

If the current dependency is artificial then I’m supportive. 

> The NativeAOT libraries tests don't need any of the clr.runtime stuff

They’ll need the JIT. Not sure if there’s different subset for that.

**Comment by ViktorHofer** [comment]
Yes there is `clr.alljits` which nativeaot already uses: https://github.com/dotnet/runtime/blob/479d0133f3e07e8107da3877076801c5c31b600c/eng/Subsets.props#L59
