### ISSUE TITLE
[AndroidCrypto] Any TargetHost input is set as SNI hostname

### ISSUE THREAD

**Issue by simonrozsival** [dotnet/runtime#79143]
On Android, we put any `TargetHost` passed to a client `SslStream` into the SNI hostname:
- [`SafeDeleteSslContext:252`](https://github.com/dotnet/runtime/blob/09613f3ed6cb5ce62e955d2a1979115879d707bb/src/libraries/System.Net.Security/src/System/Net/Security/Pal.Android/SafeDeleteSslContext.cs#L252)
- [`pal_sslstream.c:500-540`](https://github.com/dotnet/runtime/blob/09613f3ed6cb5ce62e955d2a1979115879d707bb/src/native/libs/System.Security.Cryptography.Native.Android/pal_sslstream.c#L500-L540)

This is a problem when the hostname doesn't conform to the STD 3 ASCII rules (see [`SNIHostName` docs](https://developer.android.com/reference/javax/net/ssl/SNIHostName#SNIHostName(java.lang.String))). In this case, the code throws an exception and we can't establish communication with the server.

One particular case, that also shows in our functional tests, are IPv6 addresses. The colon symbol is not allowed and an exception is thrown. The Android crypto PAL tracking issue (#45741) also mentions underscores in hostnames.

The [RFC 6066](https://www.ietf.org/rfc/rfc6066.txt) that defines SNI states:

> Literal IPv4 and IPv6 addresses are not permitted in "HostName".

I think that our Android PAL shouldn't throw exceptions when `SNIHostName` rejects an IPv6 address and it should proceed with the handshake.

/cc @wfurt 
Ref https://github.com/dotnet/runtime/pull/77386#discussion_r1028354848

**Comment by wfurt** [comment]
The IPv6 LLA should be fixed by  #81631. It seems like the RFC forbids us to pass in IP literals. 
For weird names, it may perhaps be acceptable to either swallow the error and don't set the SNI or throw PNSE. 

Now there has been some chatter about allowing SslStream to connect to sites that do not conform to the spec.
`www-.volal.cz` is one the examples where .NET fails but some other tools are able to connect.

**Comment by steveisok** [comment]
@simonrozsival @wfurt is this still an issue?

**Comment by simonrozsival** [comment]
@steveisok I think the issue has been sufficiently resolved with #81631. There are still three tests that we currently skip and need re-enabling. I opened #89232 to re-enable those tests and I think we can close this issue once that PR is merged.
