### ISSUE TITLE
Base constructor not executed in Reflection.Emit

### ISSUE THREAD

**Issue by bdebaere** [dotnet/runtime#79142]
### Description

I have a small RuntimeTypeBuilder class (which has a lot more functionality but which I have reduced to the essentials for this issue below). When creating a runtime type which inherits from another class with `TypeBuilder.SetParent` I would expect the constructor of that inherited class to be executed. This doesn't seem to work however and I don't understand why. I have tried with non-abstract and other constructor accessors too. Am I missing something? Is `SetParent` not enough to enable .NET to execute the base class constructor?

![image](https://user-images.githubusercontent.com/1436449/205261766-040d6f50-97d7-4612-af3e-7c850450e61e.png)

I can even tell that in `TypeBuilder.DefineDefaultConstructorNoLock` the code to "generate the code to call the parent's default constructor" is being called.

![image](https://user-images.githubusercontent.com/1436449/205264009-28968a0b-db73-4ded-8b88-399946bd4780.png)

```
var runtimeTypeBuilder = new RuntimeTypeBuilder();
runtimeTypeBuilder.CreateRuntimeType("RuntimeClass");
runtimeTypeBuilder.SetBaseClass(typeof(Bar));
var type = runtimeTypeBuilder.GetRuntimeType();

var instance = Activator.CreateInstance(type);

Console.ReadLine();

public abstract class Bar
{
    public string Foo { get; set; }

    protected Bar()
    {
        this.Foo = "Something";
    }
}

public class RuntimeTypeBuilder
{
    private TypeBuilder typeBuilder;
    public Dictionary<string, PropertyBuilder> propertyBuilders;

    public RuntimeTypeBuilder()
    {
        this.propertyBuilders = new Dictionary<string, PropertyBuilder>();
    }

    public void CreateRuntimeType(string name)
    {
        var assemblyBuilder = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName(Guid.NewGuid().ToString()), AssemblyBuilderAccess.Run);
        var moduleBuilder = assemblyBuilder.DefineDynamicModule("MainModule");
        this.typeBuilder = moduleBuilder.DefineType(
            name,
            TypeAttributes.Public |
            TypeAttributes.Class |
            TypeAttributes.AutoClass |
            TypeAttributes.AnsiClass |
            TypeAttributes.BeforeFieldInit |
            TypeAttributes.AutoLayout,
            null);
        this.typeBuilder.DefineDefaultConstructor(MethodAttributes.Public | MethodAttributes.SpecialName | MethodAttributes.RTSpecialName);
    }

    public void SetBaseClass(Type type)
    {
        this.typeBuilder.SetParent(type);
    }

    public Type GetRuntimeType()
    {
        var typeInfo = this.typeBuilder.CreateTypeInfo();
        var type = typeInfo.AsType();
        return type;
    }
}
```

### Configuration

net6.0
Win10
x64

### Regression?

As far as I can tell the code produces the same result in every .NET version.

**Comment by steveharter** [comment]
The `DefineType()` overload has a `Type? parent` parameter that needs to be set.

**Comment by steveharter** [comment]
>  I don't understand the difference between TypeBuilder.SetParent(parent) and ModuleBuilder.DefineType(name, attributes, parent). Care to elaborate?

SetParent() will work as well, but needs to be called before `DefineDefaultConstructor()` so the generated code can call the base class's constructor.
