### ISSUE TITLE
SYSLIB1054 code fixer should not generate a code that try to access to LibraryImport.ThrowOnUnmappableChar

### ISSUE THREAD

**Issue by Tan90909090** [dotnet/runtime#79159]
**Version Used**: 
Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.4.2

**Steps to Reproduce**:

1. Write `<TargetFramework>net7.0</TargetFramework>` in csproj
2. Write a following code:
```cs
using System;
using System.Runtime.InteropServices;

class NativeMethods
{
    [DllImport("kernel32.dll", SetLastError = true, CharSet = CharSet.Ansi, BestFitMapping = false, ThrowOnUnmappableChar = true)]
    static extern IntPtr GetProcAddress(
        IntPtr hModule,
        [MarshalAs(UnmanagedType.LPStr)] string lpProcName);

    static void Main() { }
}
```

3.  Apply a quick-fix `Convert to 'LibraryImport'` at `GetProcAddress`

**Diagnostic Id**:
`SYSLIB1054 Mark the method 'GetProcAddress' with 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time`

**Expected Behavior**:
Code fixer generate a code that does not have an error.

**Actual Behavior**:
Code fixer generate a following code:
```cs
using System;
using System.Runtime.InteropServices;

partial class NativeMethods
{
    [LibraryImport("kernel32.dll", SetLastError = true, StringMarshalling = StringMarshalling.Custom, ThrowOnUnmappableChar = true, StringMarshallingCustomType = typeof(System.Runtime.InteropServices.Marshalling.AnsiStringMarshaller))]
    static partial IntPtr GetProcAddress(
        IntPtr hModule,
        [MarshalAs(UnmanagedType.LPStr)] string lpProcName);

    static void Main() { }
}
```
Because `LibraryImportAttribute` does not have `ThrowOnUnmappableChar` member so the above code has an error: `CS0246 The type or namespace name 'ThrowOnUnmappableChar' could not be found (are you missing a using directive or an assembly reference?)`

**Note**
  I realized that same issue happens to the following code because there is not `LibraryImportAttribute.BestFitMapping`:
```cs
    [DllImport("kernel32.dll", SetLastError = true, CharSet = CharSet.Ansi, BestFitMapping = true)]
    static extern IntPtr GetProcAddress(
        IntPtr hModule,
        [MarshalAs(UnmanagedType.LPStr)] string lpProcName);
```

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky I thought we stripped invalid field when converting attributes or indicated the fixer couldn't apply. Am I misremembering this? I think we either need to drop the unsupported field when converting or not flag it. @jtschuster Any chance you could quickly address this?

**Comment by Tan90909090** [comment]
Another related issue.
When I write a following code then there is a `SYSLIB1054`:
```cs
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

internal static partial class NativeMethods
{
    [DllImport("msvcrt.dll", CallingConvention=CallingConvention.Cdecl)]
    internal static extern int printf([MarshalAs(UnmanagedType.LPStr)] string s, __arglist);
}
```
If I apply a quick-fix `Convert to 'LibraryImport'` then I will get a following code:
```cs
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

internal static partial class NativeMethods
{
    [LibraryImport("msvcrt.dll")]
    [UnmanagedCallConv(CallConvs = new Type[] { typeof(CallConvCdecl) })]
    internal static partial int printf([MarshalAs(UnmanagedType.LPStr)] string s, __arglist);
}
```
The above code has an error:
```
Error CS8795 Partial method 'NativeMethods.printf(string, __arglist)' must have an implementation part because it has accessibility modifiers.
```
It seems that `LibraryImportGenerator` does not support `__arglist` currently.
