### ISSUE TITLE
.NET Framework golink now leads to nowhere

### ISSUE THREAD

**Issue by riverar** [dotnet/runtime#79203]
When attempting to run an app compiled for a version of .NET Framework that does not exist on Windows, the following error appears: 

> This application requires one of the following versions of the .NET Framework [...]
> Do you want to install this .NET Framework version now?

![image](https://user-images.githubusercontent.com/475132/205510218-b9c31391-5042-4192-a31d-5c61107c3dd4.png)

Clicking the Yes button this dialog attempts to open a _golink_, specifically `https://go.microsoft.com/fwlink/?prd=11324&pver=4.5&sbp=AppLaunch&plcid=0x409&o1=.NETFramework,Version=v4.8.1&processName=ConsoleApp25.exe&platform=0009&osver=6&isServer=0&shimver=4.0.30319.0`.

This now simply shows the Bing homepage.

![image](https://user-images.githubusercontent.com/475132/205510400-4a45fef1-074c-4437-8422-937205c65eb6.png)

**Comment by teo-tsirpanis** [comment]
Hello, issues of .NET Framework should be submitted in https://developercommunity.visualstudio.com/dotnet/report.

**Comment by riverar** [comment]
Thanks, for records, I just re-posted there https://developercommunity.visualstudio.com/t/NET-Framework-golink-now-leads-to-nowhe/10220656
