### ISSUE TITLE
Slow startup on Linux

### ISSUE THREAD

**Issue by epeshk** [dotnet/runtime#79206]
The startup time of the empty console application on Linux is too big. It is around 70 ms for .NET 7 on my machine, while for Windows it is 25ms. By empty I mean literally empty app, with empty `Main` method. This overhead present in non-empty apps too. Don't really know is it `dotnet` or just me.

NativeAOT reduces this overhead to 3 ms.

I also tested with `DOTNET_JitDisasmSummary` so, looks like it is not JIT-related problem.

#### Linux:
```bash
$ time ./bin/Release/net7.0/linux-x64/ConsoleApp1 

real  0m0,075s
user  0m0,026s
sys  0m0,026s

$ export DOTNET_JitDisasmSummary=1
$ time ./bin/Release/net7.0/linux-x64/ConsoleApp1 

   1: JIT compiled System.Runtime.CompilerServices.CastHelpers:StelemRef(System.Array,long,System.Object) [Tier1, IL size=88, code size=84]
   2: JIT compiled System.Runtime.CompilerServices.CastHelpers:LdelemaRef(System.Array,long,ulong) [Tier1, IL size=44, code size=40]
   3: JIT compiled System.SpanHelpers:IndexOfNullCharacter(byref) [Tier1, IL size=792, code size=384]
   4: JIT compiled Program:<Main>$(<unnamed>) [Tier0, IL size=1, code size=51]

real	0m0,064s
user	0m0,021s
sys	0m0,025s
```

#### Windows:
```ps
Measure-Command { .\ConsoleApp1.exe }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 25
Ticks             : 250565
TotalDays         : 2.90005787037037E-07
TotalHours        : 6.96013888888889E-06
TotalMinutes      : 0.000417608333333333
TotalSeconds      : 0.0250565
TotalMilliseconds : 25.0565
```

### Configuration

Ubuntu 22.04.1 LTS, non VM

### Regression?
Partially, this overhead is lower on .NET 6 – around 50 ms. But it is also way bigger than on Windows.

**Comment by hez2010** [comment]
What if you set the environment variable `DOTNET_EnableWriteXorExecute=0`?

**Comment by epeshk** [comment]
@hez2010, nothing changed

**Comment by JulieLeeMSFT** [comment]
@mangod9, PTAL.

**Comment by mangod9** [comment]
@epeshk, could you please clarify how you are measuring startup? Is the current measurement how long the entire "empty application" takes, so that could include startup+shutdown etc?
