### ISSUE TITLE
Is it static link only of mono aot on windows?

### ISSUE THREAD

**Issue by ifeuille** [dotnet/runtime#79214]
I find it generate static mono libraries only on windows with DISABLE_SHARED_LIBS=1.So what's the purpose for this？
@vargaz   area-Codegen-AOT-mono

**Comment by ifeuille** [comment]
area-Codegen-AOT-mono

**Comment by SamMonoRT** [comment]
@lateralusX @vargaz - this is about Mono AOT on windows. I moved all questions/discussion issues to 9.0, but please consider any relevant fixes (if any for backports).
