### ISSUE TITLE
Filehandle Blocks "Cut and Paste" allows "Copy and Paste"

### ISSUE THREAD

**Issue by Swiftpaws** [dotnet/runtime#79213]
### Description

The handle created here will disallow "Cut and Paste" over the file specified.
"Copy and Paste" works.

`File.OpenHandle(
        path,
        mode: FileMode.Open,
        access: FileAccess.Read,
        share: FileShare.Delete | FileShare.ReadWrite
        )`

### Reproduction Steps

* New console application
* Create two files: file1 file2
* Use the code above to create a handle for file1
* File.Move(file2, file1, true) will fail
* File.Copy(file2, file1,true) will NOT fail

Or: See Github Repo: [Link](https://github.com/Swiftpaws/FileHandle_blocks_cut_paste)

### Expected behavior

File.Move should overwrite the file

### Actual behavior

File.Move does not overwrite the file - Fails with an AccessException

### Regression?

No

### Known Workarounds

None

### Configuration

* Windows 10
* .Net 6

Possible bug/weird behavior in W32 ?

### Other information

Related stackoverflow: https://stackoverflow.com/questions/74610878/filehandle-prevents-file-move

**Comment by adamsitnik** [comment]
Hi @Swiftpaws 

I was able to reproduce the problem, thank you for a detailed report!

What `File.Move` does behind the scenes is calling `MoveFileExW`:

https://github.com/dotnet/runtime/blob/f0c4347ff0eb8852dd8c39a45f7d2c4da6cf0892/src/libraries/System.Private.CoreLib/src/System/IO/FileSystem.Windows.cs#L204-L206

And this sys-call is failing with error code equal `5`:

```cs
private const uint MOVEFILE_REPLACE_EXISTING = 0x01;
private const uint MOVEFILE_COPY_ALLOWED = 0x02;

if (!MoveFileEx(moveFilePath, handleFilePath, MOVEFILE_COPY_ALLOWED | MOVEFILE_REPLACE_EXISTING))
{
    int lastError = Marshal.GetLastWin32Error();
    Console.WriteLine(lastError);
}

[DllImport("kernel32.dll", SetLastError = true)]
static extern bool MoveFileEx(string lpExistingFileName, string lpNewFileName, uint flags);
```

Which according to [System Error Codes](https://learn.microsoft.com/windows/win32/debug/system-error-codes--0-499-) is `ERROR_ACCESS_DENIED`, which gets mapped to `UnauthorizedAccessException`. It's not `ERROR_SHARING_VIOLATION` (32) which we would expect in this case.

Unfortunately there is very little we can do:

1. Changing `UnauthorizedAccessException` to `IOException` (we don't have a dedicated exception for `ERROR_SHARING_VIOLATION`) would be considered a breaking change (user who added `catch (UnauthorizedAccessException)` could observe a different result of their app).
2. Replacing `File.Move(src, dest)` with `Delete(dest)`, `File.Create(dest)` and `File.Copy(src, dest)` would not be transactional (if one of the operations failed, we could not recover to the previous state).

I am afraid that the best I can do is to update the docs and add a clear statement that `File.Move(src, dest)` requires exclusive file access for `dest`.

**Comment by adamsitnik** [comment]
I've sent a PR with doc fix: https://github.com/dotnet/dotnet-api-docs/pull/8726
