### ISSUE TITLE
Rename `RdXmlFile` to `_DirectivesFile`

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#79210]
To make it 100% visible this is an unsupported internal option that may change or disappear one day without a breaking change warning or anything.

**Comment by wjk** [comment]
If you intend to make this API private, what are the supported alternatives?

**Comment by MichalStrehovsky** [comment]
> If you intend to make this API private, what are the supported alternatives?

It only was "public" in the experimental repos as an experiment and even there it was generating a warning for years: https://github.com/dotnet/runtimelab/pull/875. I don't think we would delete it anytime soon, but it's only meant for temporary workarounds. The real fix is the make the code AOT/trimming compatible and that's where all the guidelines are going to be. RdXmlFile didn't make it into docs.microsoft.com and the references to it were deleted from exception messages intentionally.

`RdXmlFile` started showing in various youtubes/blogs and it's very much undesirable. It was [never meant for public consumption](https://github.com/dotnet/corert/issues/5001). The format is really bad and the problem it's trying to fix is even worse.
