### ISSUE TITLE
Consider deleting enum support for bool as an underlying type from all runtimes

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#79224]
It's not expressible in C#, VB, or F#, effectively no one uses it, and it adds non-trivial complications to the implementations.

https://github.com/dotnet/runtime/pull/78580#discussion_r1038997410

**Comment by MichalPetryka** [comment]
This would require a change to the ECMA:
```
The
symbols of an enum are represented by an underlying integer type: one of { bool, char, int8,
unsigned int8, int16, unsigned int16, int32, unsigned int32, int64, unsigned int64, native int,
unsigned native int } 
```

**Comment by stephentoub** [comment]
> This would require a change to the ECMA

It wouldn't "require" it.  We'd be removing support for something that's effectively dead.  There are many places where the runtime differs from what the ECMA specification details:
https://github.com/dotnet/runtime/blob/main/docs/design/specs/Ecma-335-Augments.md
We would update this addendum.

Today technically there's support for other required types in that list, but the implementation isn't complete:
https://github.com/dotnet/runtime/blob/1fa5485a9a62bea0ca1cc58df3f2ebcb83c738b8/src/libraries/System.Private.CoreLib/src/System/Enum.cs#L12-L13
For example, today try getting the values for a float/double-backed enum, and you'll find they're all zeros.
