### ISSUE TITLE
Blazor WASM locale currency differs from Browser WASM

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#79235]
Report: https://github.com/dotnet/runtime/issues/45262#issuecomment-1337664949. Australian locale behaves differently - it does not work in any wasm of project kind that might imply missing data or corrupted file. 

For e.g. Czech locale, currency is displayed incorrectly in Blazor even though the same code in BrowserWasm works fine. It implies that the icudt file itself is all right. The difference between these two projects is the way we are loading the data: 
- `customStartup` handled by aspnetcore in blazor wasm
- standard startup, where runtime is loading the assets, including icu into the emcc memory as bytes.

Reproduction code:
```
<p role="status">@formattedMoney</p>
@code {
    private string formattedMoney;
    private void IncrementCount()
    {
        var cultureInfo = CultureInfo.GetCultureInfo("cs-CZ");
        decimal money = 125000.5m;
        formattedMoney = string.Format(cultureInfo, "{0:C}", money);
    }
}
```

Should get solved by introducing standard startup in Blazor.

**Comment by maraf** [comment]
I recently migrated my project (Blazor https://github.com/maraf/Money) to .NET 7 and formatting currency is ok there. I'm using [`.ToString("C", culture)` syntax there](https://github.com/maraf/Money/blob/e56e70f9f862b342f8225508168e659880c28769/src/Money.Blazor.Host/Services/CurrencyFormatter.cs#L86)

**Comment by ilonatommy** [comment]
> I recently migrated my project (Blazor https://github.com/maraf/Money) to .NET 7 and formatting currency is ok there. I'm using [`.ToString("C", culture)` syntax there](https://github.com/maraf/Money/blob/e56e70f9f862b342f8225508168e659880c28769/src/Money.Blazor.Host/Services/CurrencyFormatter.cs#L86). Tested CZK, EUR, USD


The difference between `Money` project and blank WASM I tried is using:
```
<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
```
@vpekarek, could you please let us know if you are having all globalization data option enabled in the Client app? If so, could you please share with us a minimal repro version? It looks like with this option + dotnet 7, CZK should work.

**Comment by vpekarek** [comment]
Hi @ilonatommy Thank you for reply. Yes, this works.
