### ISSUE TITLE
Object Header or Sync Block in BotR: Threading - Synchronization: Managed

### ISSUE THREAD

**Issue by Miljankg** [dotnet/runtime#79248]
Hi!

In the [Threading section](https://github.com/dotnet/runtime/blob/main/docs/design/coreclr/botr/threading.md) of the "Book of the Runtime", in the chapter "Synchronization: Managed", the last paragraph states:

> An object that is used as a condition variable (via Monitor.Wait and Monitor.Pulse) must always be inflated, as there is not enough room in the _sync block_ to hold the required state.

However, from reading the whole chapter, my understanding is that the objects are inflated when there is not enough space in the _object header_. Then the _sync block_ is added. If I am not mistaken, _sync block_ in the mentioned paragraph should be replaced with _object header_. 

Is this true, or did I misunderstand how the objects are inflated?

Thanks in advance.

**Comment by kouvel** [comment]
> Is this true, or did I misunderstand how the objects are inflated?

Yes, it should say "object header" instead.
