### ISSUE TITLE
Is there a way to tell SSLStreams to validate the remote certificate based on the certificate present in path rather than Windows keystore?

### ISSUE THREAD

**Issue by ramsubbaraoc** [dotnet/runtime#79266]
When using SSLStreams with AuthenticateAsClient, i think RemoteCertificateValidationCallback function checks if the public key of the server is present in the "Trusted Root Certification Authority" of Windows Keystore, if not present then the SSLPolicyErrors gets updated.

Now is there a way to say to SSLStreams that try to validate the Server certificate based on the public key present in a directory rather than Windows keystore.

**Comment by wfurt** [comment]
With 7.0 you can also set [SslClientAuthenticationOptions.CertificateChainPolicy](https://learn.microsoft.com/en-us/dotnet/api/system.net.security.sslclientauthenticationoptions.certificatechainpolicy?view=net-7.0#system-net-security-sslclientauthenticationoptions-certificatechainpolicy) and set `CustomTrustStore` to avoid getting into validation. 
Note that `CustomTrustStore` is collection replacing system trust e.g. it is not additive. 
You can look at example here: https://github.com/dotnet/runtime/blob/ecc1ca12aeb7935b7268e752a88c2fa16b875abc/src/libraries/System.Net.Security/tests/FunctionalTests/SslStreamNetworkStreamTest.cs#L757

Let me know if either one solution works for you @ramsubbaraoc

**Comment by ramsubbaraoc** [comment]
@Suchiman Thank you for your suggestion. I didn't want to do the validation myself because it could happen that i miss certain important aspects. Was checking if .NET could do the validation if provided a path instead of Windows Trusted Root authority.

@wfurt Thank you. I tried to set the following 
```
  clientAuthentication.CertificateChainPolicy = new X509ChainPolicy() { TrustMode = X509ChainTrustMode.CustomRootTrust,
                };
 clientAuthentication.CertificateChainPolicy.CustomTrustStore.Add(remoteCert);
```
And it seemed working. Have few questions, please can you answer them
1. Can the same code be used in production?
2. Are there any implications like the "is the validation same as what .NET does when the remote certificate is put in the trusted root authority? 
3. Should we be doing any additional validation when using "CustomTrustStore" ?

**Comment by rzikm** [comment]
By providing custom root trust, you are only changing which certs the client considers trusted, the rest of the validation process is unchanged.

As part of the validation process, the client verifies the certificate by building an `X509Chain` from the server certificate to any of the certificates in the root trust. You are only changing where such a chain can be rooted, the chain still needs to be considered valid by the default validation procedure (not expired, matches the expected hostname, has the right flags...).

It works the same for CA certificates. The only difference between Self-signed and other certs is that a self-signed cert is guaranteed to not be trusted by the default Root trust.

**Comment by ramsubbaraoc** [comment]
@rzikm Thank you

**Comment by rzikm** [comment]
Closing as answered
