### ISSUE TITLE
Different ShortDatePattern for the same CultureInfo on different Platforms

### ISSUE THREAD

**Issue by Timo-Weike** [dotnet/runtime#79275]
### Description

The value for `CultureInfo.GetCultureInfo("pl-PL").DateTimeFormat.ShortDatePattern` differs based on the platform/os version.

On my maschine with `Environment.Version == 6.0.11 and Environment.OSVersion == "Microsoft Windows NT 10.0.19044.0"` the value is `dd.MM.yyyy`. This was also the case while running tests in a AzureDevOps Agent with `Ubuntu 20.04.5`. However in an agent running on the new default `Ubuntu 22.04.1` the value for `CultureInfo.GetCultureInfo("pl-PL").DateTimeFormat.ShortDatePattern` is now `d.MM.yyyy`.

### Reproduction Steps

Run the test 
~~~ cs
[Fact]
public void Test()
{
    var dateTime = new DateTime(2022, 01, 02, 12, 34, 56);

    var plCulture = CultureInfo.GetCultureInfo("pl-PL");

    var dateTimeStr = dateTime.ToString(plCulture);

    var res = $"{dateTimeStr} with date format {plCulture.DateTimeFormat.ShortDatePattern}";

    res.Should().Be("02.01.2022 12:34:56 with date format dd.MM.yyyy ", $"Should work with runtime {Environment.Version} - {Environment.OSVersion}");
}
~~~
on the two different ubuntu images.

### Expected behavior

`ShortDatePattern` to have the same value on all platforms.

### Actual behavior

`ShortDatePattern` differes between `Ubuntu 20.04` and `Ubuntu 22.04` runtime.

**Comment by Timo-Weike** [comment]
@Clockwork-Muse thanks for the insight.

We have a extension method which extends the format of the given culture with the format markers for milliseconds
~~~ cs
public static string ToStringWithMilliseconds(this DateTime value, CultureInfo culture)
{
    // Append millisecond pattern to current culture's long time pattern
    var longTimePattern = culture.DateTimeFormat.LongTimePattern;
    longTimePattern = Regex.Replace(longTimePattern, "(:ss|:s)", "$1.fff");

    return $"{value.ToString(culture.DateTimeFormat.ShortDatePattern, culture)} {value.ToString(longTimePattern, culture)}";
}
~~~
that's why it came up in our tests.

Are the values for `ShortDatePattern` and `LongTimePattern` stable for the `CultureInfo.InvariantCulture`?

**Comment by tarekgh** [comment]
@Clockwork-Muse is correct. .NET picks the formats from the ICU library used on such platforms. Every change in the ICU version will be reflected on the .NET. 

> Are the values for ShortDatePattern and LongTimePattern stable for the CultureInfo.InvariantCulture?

Yes. Invariant culture never changes culture data in general. 

I am closing the issue. Feel free to send any questions if there is anything unclear here.

**Comment by Clockwork-Muse** [comment]
@Timo-Weike 
> We have a extension method which extends the format of the given culture with the format markers for milliseconds

Don't do this.  You're not guaranteed that any particular field is included, so you're not guaranteed that seconds will be included in the first place.

If you have an explicit requirement to include milliseconds, you should probably be using a (non-localized) custom time format to begin with, usually ISO.  Sometimes this also means date/time values should be in UTC, although that's a less-hard requirement.

As a side note, the given extension method is using Regex and not caching the results, which may consume a larger share of resources than expected...

**Comment by Timo-Weike** [comment]
We will review the use of the method and correct any wrong use of Cultures.

@Clockwork-Muse  and @tarekgh 
Thank you both for your time and help.
