### ISSUE TITLE
DateTime.Now from .NET 6 will return UTC time, not local time in Arm64 Docker Image

### ISSUE THREAD

**Issue by peter-kwb** [dotnet/runtime#79282]
### Description

Dear Sirs,
System.DateTime.Now does not show local time in Docker Container. Similar issue but with arm64 docker container: https://github.com/dotnet/runtime/issues/63194

We use following runtime image:
FROM mcr.microsoft.com/dotnet/aspnet:6.0-bullseye-slim-arm64v8 AS base

We mounted:
       - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
from host system.

Enter the container by docker exec -it /bin/bash
the commandline program date in container shows the correctly configured timezone from host system.

But if you do DateTime.now in the dotnet progamm, it shows utc, the wrong timezone

### Reproduction Steps

Create a docker container with:
FROM mcr.microsoft.com/dotnet/aspnet:6.0-bullseye-slim-arm64v8 AS base
...
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
....
all standard docker build steps

set a timezone in host system, check it with date command

docker run -v ...
       - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

docker exec -it mycontainer /bin/bash
root@container:/app date
Tue Dec  6 13:30:56 CET 2022

check output of application: DateTime.now and DateTime.UtcNow

### Expected behavior

DateTime.now should show the local time, the same as the date command in the docker container  and host since we mounted the timezone

### Actual behavior

DateTime.now is the same as DateTime.UtcNow and not the local time of the system/host/container

### Known Workarounds

See this issue for a fix
https://github.com/dotnet/runtime/issues/63194

### Configuration

Docker:
FROM mcr.microsoft.com/dotnet/aspnet:6.0-bullseye-slim-arm64v8 AS base
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

RaspiOS - Kernel: Linux 5.15.61-v8+ #1579 SMP PREEMPT Fri Aug 26 11:16:44 BST 2022 aarch64 GNU/Linux

Arm64

I have not tried other images or arm32

**Comment by Clockwork-Muse** [comment]
As I commented in that issue, it's generally poor practice to run a container in a specific timezone when you're running a server.  Rather, if some part of your application wants a localized timezone it's better to retrieve that from the entity/model when a request is made.

The timezone/culture of a server should never be relevant - instead, it should retrieve that data based on the entities being processed in the current request.

**Comment by peter-kwb** [comment]
Thanks for your reply.
So you say this is rather a wrong usage of DateTime.now and not a bug of c#/dotnet? So maybe you should change the documentation or add special notes: https://learn.microsoft.com/en-us/dotnet/api/system.datetime.now?view=net-7.0

But of course i could use another programming language.

**Comment by Clockwork-Muse** [comment]
... why do you care about the host's local time?  Why do you think you need that information?  Except under some very specific deployment scenarios, it's almost never relevant, and in most cases the host should likely be set to UTC anyways.

That is, after you've read this "local" time, what do you plan on doing with it?  Why shouldn't it be from some other explicit config or entity model, ie:
```cs
var businessTimeZone = TimeZoneInfo.FindSystemTimeZoneById(businessEntityModel.TimeZoneId);
var businessLocalTime = TimeZoneInfo.ConvertTime(DateTimeOffset.UtcNow, businessTimeZone);
```

**Comment by layomia** [comment]
This is a recurring report (https://github.com/dotnet/runtime/issues/63194, https://github.com/dotnet/runtime/issues/60469). We need to evaluate this in 8.0. cc @dotnet/area-system-datetime.

**Comment by Clockwork-Muse** [comment]
@layomia - Not quite:
 - #60469 was a runtime bug that was fixed.
 - This issue, #63194, and #62545 all stem from people trying to change the "local" timezone in the wrong way (with [some](https://github.com/dotnet/runtime/issues/62545#issuecomment-1107894186) [workarounds](https://github.com/dotnet/runtime/issues/62545#issuecomment-1115349195)).  In all of these cases, trying to get/use the local timezone is unusual/suspect behavior, and Utc should be preferred in the first place.

**Comment by tarekgh** [comment]
@Clockwork-Muse is correct, using `-v` to set the time zone on the container is wrong and shouldn't be used. The correct way would be as described in the comment https://github.com/dotnet/runtime/issues/62545#issuecomment-1115349195. The issue https://github.com/dotnet/runtime/issues/62545 has more detailed discussion about that which will be useful to look at.

**Comment by peter-kwb** [comment]
> ... why do you care about the host's local time? Why do you think you need that information? Except under some very specific deployment scenarios, it's almost never relevant, and in most cases the host should likely be set to UTC anyways.
> 
Our applications are servers and/or clients depending on their tasks. We develop IoT devices/services in the SmartHome context. For ease of deployment we work with containers and all timestamps we put are UTC, but we also need the local time at the location we configured. Our product is alwayse personalized and configured for a specific geografical location, a specific heating/cooling system,for specific local weather data. Our systems are installed by technicians which have to do several commissioning steps, one of which is to configure the local timezone.

> That is, after you've read this "local" time, what do you plan on doing with it? Why shouldn't it be from some other explicit config or entity model, ie:
> 
> ```cs
> var businessTimeZone = TimeZoneInfo.FindSystemTimeZoneById(businessEntityModel.TimeZoneId);
> var businessLocalTime = TimeZoneInfo.ConvertTime(DateTimeOffset.UtcNow, businessTimeZone);
> ```

this is correct, we could configure the time zone in some other context, like appsettings, file, db, service, .... the possibilities are near endless. 
but why not work with the obviouse choice but to use local time of the system? I didnt know this is wrong but ok, we all can learn.

**Comment by Clockwork-Muse** [comment]
>  I didnt know this is wrong but ok, we all can learn.

For a client device (ie, smart home speaker), using a "host" timezone is fine.
For anything server related, run it in UTC and have it read/use the "local" timezone when appropriate, and from the appropriate source.  Consider that someone may wish to run this server in the cloud, or have multiple locations.
