### ISSUE TITLE
[mono][perf] iOS and WASM disk size regressions on 06 Dec 2022

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#79285]
### Description

Change in Enum values https://github.com/dotnet/runtime/pull/78580 produced disk size regression in Mono iOS sample app and in Mono Blazorwasm.

Binary disk size (SOD) for Mono iOS sample has increased by 9.86%.
Framework disk size (SOD) for Mono AOT Blazorwasm sample has increased by 9.48%.

#### Details - Mono iOS sample app

Filename | Parent commit SOD in bytes (https://github.com/dotnet/runtime/commit/6e0c0461af18fd881554003951d8b23257d9e6a2) | Change commit SOD in bytes  (https://github.com/dotnet/runtime/commit/62f3eb2878c3e82631b91dd02ee4fb655d23a2b1)
---|-----|----
HelloiOS   |18998464 | 21078752
Info.plist   |     980 |      980
PkgInfo   |       8 |        8
Program.aotdata   |    4792 |     4792
Program.deps.json   |   11929 |    11929
Program.dll   |    6656 |     6656
Program.runtimeconfig.json   |    1064 |     1064
System.Console.aotdata   |   63344 |   138632
System.Console.dll   |   17920 |    17920
System.Private.CoreLib.aotdata   |  930368 |  1118880
System.Private.CoreLib.dll   | 1015808 |  1047552
icudt.dat   | 1859040 |  1859040

<img width="2002" alt="Screenshot 2022-12-13 at 11 39 04" src="https://user-images.githubusercontent.com/11523312/207295792-45ab6349-73c1-447c-a0d9-39011de52da2.png">

<hr>

#### Details - Mono WASM

Date | Diff | Change | Size increase (bytes) | Size increase (%)
--|--|--|--|--
06 Dec 2022 | https://github.com/dotnet/runtime/compare/b399eed41e575b5d03d0901e9d4776aa9a93b9a9...fcf0a09a47ee75bc33731b8c3358f6de78fbc211 | https://github.com/dotnet/runtime/commit/62f3eb2878c3e82631b91dd02ee4fb655d23a2b1 | 11042 |	0.51

<img width="2041" alt="Screenshot 2022-12-13 at 10 14 54" src="https://user-images.githubusercontent.com/11523312/207296316-8341bad9-a7ae-49e7-828b-70434bb0142b.png">

<hr>

#### Details - Mono AOT WASM

Date | Diff | Change | Size increase (bytes) | Size increase (%)
-|--|--|--|--
06 Dec 2022 | https://github.com/dotnet/runtime/compare/b399eed41e575b5d03d0901e9d4776aa9a93b9a9...fcf0a09a47ee75bc33731b8c3358f6de78fbc211 | https://github.com/dotnet/runtime/commit/62f3eb2878c3e82631b91dd02ee4fb655d23a2b1 | 414367 | 9.48

<img width="2039" alt="Screenshot 2022-12-13 at 11 42 43" src="https://user-images.githubusercontent.com/11523312/207296541-ff60b669-543e-4971-a488-c38d006a675e.png">

cc @SamMonoRT @lewing @radekdoulik 

#### iOS

OS: iOS/OSX
Architecture: arm64
.NET version: 7.0.100-rc.1.22431.12

#### WASM

OS: Ubuntu 18.04
Architecture: x64
.NET version: 7.0.100-rc.1.22431.12

**Comment by lewing** [comment]
wasm report is here https://github.com/dotnet/perf-autofiling-issues/issues/10461 at first glance it looks like the growth is primarily in System.Private.CoreLib and retained native code.

**Comment by stephentoub** [comment]
How does one determine what native code is being retained that wasn't before, and why it's being retained?

**Comment by kotlarmilos** [comment]
I don't think that we can analyze a dependency graph. I suggest to compare native symbols before and after the change. Moreover, we can check ILLinker logs for any trimming/linking actions made before and after the change.

Generics `TUnderlyingValue` could have impacted the size, especially with change mentioned in https://github.com/dotnet/runtime/issues/78851.

**Comment by stephentoub** [comment]
@jkotas, FYI

**Comment by ivanpovazan** [comment]
> How does one determine what native code is being retained that wasn't before, and why it's being retained?

@stephentoub, afaik currently there is no easy way to do this with Mono. We usually go through the changes and compare outputs as @kotlarmilos suggested. Regarding this, I have opened https://github.com/dotnet/runtime/issues/73159 as a .NET 8 idea which would help us answer such questions and improve the overall experience for detecting these kind of issues.

This being said, maybe we could utilize NativeAOT compiler's ILScanner mode, which we could run before and after a change in libraries' code, to dump the dependency graphs and track down what are all the new dependencies introduced by the change.

**Comment by eerhardt** [comment]
Maybe https://github.com/google/bloaty might help here? Not sure if it can be used on iOS, but I believe I've heard of people using it for WASM before.

**Comment by ivanpovazan** [comment]
> Maybe https://github.com/google/bloaty might help here? Not sure if it can be used on iOS, but I believe I've heard of people using it for WASM before.

I agree @eerhardt, I have used it along with a custom script to try to compare two separate binaries explained here:
https://github.com/dotnet/runtime/issues/56385#issuecomment-1156954458
If further explanation is needed on how to collect the measurements, I would gladly provide some more info.

**Comment by marek-safar** [comment]
I agree with @jkotas this looks like limitation/bug in Mono AOT engine.

/cc @vargaz to confirm

**Comment by MichalStrehovsky** [comment]
Seeing an 8% regression (for Hello World) in NativeAOT as well: #79437.

**Comment by vargaz** [comment]
Part of the increase seems to be caused by code like this:
```
            Type underlyingType = typeof(TEnum).GetEnumUnderlyingType();

                if (underlyingType == typeof(int)) return TryFormatPrimitiveDefault(rt, *(int*)&value, destination, out charsWritten);
                if (underlyingType == typeof(uint)) return TryFormatPrimitiveDefault(rt, *(uint*)&value, destination, out charsWritten);
```
Mono currently doesn't treat GetEnumUnderlyingType as an intrinsics. Even if that is implemented, it's not going to be smart enough to realize that 'underlyingType' points to typeof(int) at the if () location, so it can't optimize out the if () statements, forcing to to generate all the TryFormatPrimitiveDefault<T> instances.

**Comment by kotlarmilos** [comment]
Follow-up research on size improvements in Mono AOT compiler -- it seems that inflated instances in addition to gsharedvt created the regression with changes in Enum values.

Bloaty symbols diff before and after the change - https://gist.github.com/kotlarmilos/a5c7c0b3372f0e019a9e2016ce7805e5

It seems that single `TryParseByValueOrName` instance allocates about 14kb. If inflated instances are disabled for  `TryParseByValueOrName`, size improvement is about 300kb. If inflated instances are disabled for `System.Enum`, size improvement is about 1.6mb.

@vargaz Is it something that we might consider as an option if a speed isn't affected much, or is it not an option?

Bundles are attached for further comparison.

[before-enum-bundle.zip](https://github.com/dotnet/runtime/files/10883783/before-enum-bundle.zip)
[after-enum-bundle.zip](https://github.com/dotnet/runtime/files/10883789/after-enum-bundle.zip)

**Comment by kotlarmilos** [comment]
This approach seems to involve special handling for Enum, which may not be the best solution overall. Since this doesn't appear to be a reasonable fix / high effort, I will close the issue.
