### ISSUE TITLE
Logger name allocations from ILoggerFactory.CreateLogger<MyClass>()

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#79317]
### Description

As noticed in https://github.com/dotnet/aspnetcore/pull/45480, `CreateLogger<MyClass>()` allocates a StringBuilder + string for the logger name, even for simple cases. For example, `MyClass` is just getting `typeof(MyClass).FullName`.

https://github.com/dotnet/runtime/blob/c6d6b19da5427ae78eab241d2af596a3320a5e5b/src/libraries/Common/src/Extensions/TypeNameHelper/TypeNameHelper.cs#L81

Creating the logger name should avoid using a `StringBuilder` unless necessary. Usually `CreateLogger<T>` is used with a basic type (not nested, not generic, not array, etc). Most of the time `Type.FullName` can be used directly.

### Configuration

.NET 8 alpha

### Regression?

No

### Data

Allocations identified in https://github.com/dotnet/aspnetcore/pull/45480

**Comment by benaadams** [comment]
https://github.com/dotnet/runtime/pull/79325
