### ISSUE TITLE
TimeSpan - Microseconds and Nanoseconds

### ISSUE THREAD

**Issue by arung2207** [dotnet/runtime#79333]
TimeSpan should have Microsecond and Nanosecond properties instead of their plural versions on the line of similar properties in TimeOnly, DateTime, and DateTimeOffset

**Comment by krwq** [comment]
@arung2207 this ship already sailed - we can't rename it due to compat concerns and there doesn't seem much value in duplicating property

**Comment by arung2207** [comment]
@krwq You mean this is one of those inconsistencies that has to be lived with for ever! :(

> @arung2207 this ship already sailed - we can't rename it due to compat concerns and there doesn't seem much value in duplicating property

**Comment by krwq** [comment]
Yes, is there any particular thing you're missing? Perhaps you were searching for TotalMicroseconds?

**Comment by arung2207** [comment]
Its the consistency that seems off. Perhaps it should have been plurals in TimeOnly, DateTime, and DateTimeOffset also.

**Comment by tarekgh** [comment]
Closing the issue as we cannot change the shipped API names.
