### ISSUE TITLE
File.OpenHandle() limitations

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#79335]
We started to replace custom CreateFileW pinvokes with File.OpenHandle() in PowerShell repository and was blocked because of the API limitations.
Currently there are strong argument validations:
https://github.com/dotnet/runtime/blob/1a37caf773a3b857ccff49a31be3333d4fdc491f/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/FileStreamHelpers.cs#L62-L73

CreateFileW allows to use many flags for these parameters. Now they are blocked. In particular, we would like to have FILE_FLAG_POSIX_SEMANTICS, FILE_FLAG_OPEN_REPARSE_POINT, FILE_FLAG_BACKUP_SEMANTICS, FileAccess = 0 and so on.

What is the preferred way to solve this problem without using custom pinvoke?

Is it possible to remove these hard checks from the API so that we can use any flags with a simple cast?

The same question for another APIs like File.SetAttributes().

/cc @adamsitnik

**Comment by jkotas** [comment]
If you would like to have a full access to all Windows-specific OS flags, I think it is best to use PInvoke.

**Comment by iSazonov** [comment]
No doubt we will.
I would like to understand the meaning of this restriction. This API is already quite low-level in nature, and these parameters already have strict types, which excludes random errors. So it's unclear why we need to block values that could have been passed with cast.

**Comment by jkotas** [comment]
This is platform-neutral API. What would be do about the undefined flags on Linux if we were to allow them on Windows? How would we warn that the code is non-portable?

**Comment by iSazonov** [comment]
> This is platform-neutral API.

If I asked to add Windows specific values for example in FileAcces enum, it would violate this principle.
This can be compared to the Unsafe.* API. It's not for regular code, but it exists for low-level code nonetheless.
The API in the issue question uses _handle_. This is a low-level API and the hard constraints in it look unexpected.
And the area in the issue question is _pinvokes_ - it is non-portable area.

(I'm not pushing for the change, but I want to better understand the .Net team's position to avoid fruitless discussions in the future.)

**Comment by stephentoub** [comment]
> And the area in the issue question is pinvokes - it is non-portable area.

But this API is portable.  I believe you're asking to remove the validation and allow such bit patterns through.  But if that bit pattern doesn't throw when used on Windows, what does it do on Unix?  What if those same bits when cast to the underlying APIs on Linux mean something entirely different?  What if we want to expose additional options in the future that use those same bit patterns? Etc.

**Comment by stephentoub** [comment]
> And the parameters are of a strict type

Which is only meaningful if you validate it.  But if we allow (FileOptions)12345 through, then that becomes part of the API contract, everywhere.

**Comment by iSazonov** [comment]
And how is such the cast ((FileOptions)12345) more dangerous than any other? It must be very dangerous indeed if you forbid it, but not the other castes.

**Comment by stephentoub** [comment]
I don't know what other casts you're talking about.  But yes, it's dangerous to allow unvalidated input to be passed through portable APIs.

**Comment by adamsitnik** [comment]
> FILE_FLAG_POSIX_SEMANTICS, FILE_FLAG_OPEN_REPARSE_POINT, FILE_FLAG_BACKUP_SEMANTICS

We are always open for discussion about extending existing flags if they can be implemented on both Windows and Unix.

For `FILE_FLAG_BACKUP_SEMANTICS` you can follow #27086.

`FILE_FLAG_POSIX_SEMANTICS` - I would need to know how to enable case sensitivity for single file on macOS and whether this flag does something more. And whether it works on every Windows or just newer versions.

`FILE_FLAG_OPEN_REPARSE_POINT` - is my understanding correct that you want to open a link rather than the file it points to? May I ask what are you trying to achieve and what our existing symlink APIs are missing?

**Comment by stephentoub** [comment]
> I found Jeremy said triple "I'm also fine with removing the enum checks". 😸 It would help to make platform-specific pinvokes more graceful. But I don't insist.

We always reserve the right to get smarter and learn from the past.  We've seen a lot of issues in other areas of the stack where options were being passed through unvalidated then lead to complicated cross-platform behavioral problems that are difficult to diagnose and understand, e.g. in sockets.

**Comment by iSazonov** [comment]
> e.g. in sockets.

Great example! I guess they saved options in a field and then implicitly transferred to unassigned code. Yes, this is worth blocking in high level code.
Although I immediately want to have something like Unsafe.Cast for low level code. Although, eh, it is not for run time. Or not?... What if compiler will have (default) option to disable enum casts for regular code? This of course does not remove the checks in the public enum parameters, but it is similar to enable nullable story.

---

As side notice for the comment https://github.com/dotnet/runtime/blob/1a37caf773a3b857ccff49a31be3333d4fdc491f/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/FileStreamHelpers.cs#L80-L81
If such validations are used in many places it seems it makes sense to have something like `static bool Enum.IsValid(object value)`.
