### ISSUE TITLE
CultureInfo("nb-NO") not working correctly for iOS on .NET 7

### ISSUE THREAD

**Issue by espenrl** [dotnet/runtime#79347]
### Description

This is actually fixed, but I don't think it made it for the release of .NET 7. Please see #76596. Also reported at  https://github.com/dotnet/maui/issues/10441 and then https://github.com/xamarin/xamarin-macios/issues/16217

Will the fix be included in the upcoming patch release of .NET 7? I guess the fix should be backported to .NET 6 also.

This makes using MAUI apps in Norway a big problem.

### Reproduction Steps

Create a MAUI app and run on iOS.

### Expected behavior

```
var culture = CultureInfo.GetCultures(CultureTypes.AllCultures).SingleOrDefault(x => string.Equals(x.Name, "nb-NO", StringComparison.OrdinalIgnoreCase));
// should not be null
```

### Actual behavior

```
var culture = CultureInfo.GetCultures(CultureTypes.AllCultures).SingleOrDefault(x => string.Equals(x.Name, "nb-NO", StringComparison.OrdinalIgnoreCase));
// is null
```

**Comment by espenrl** [comment]
``` CSharp
var json = JsonSerializer.Serialize(new CultureInfo("nb-NO"), new JsonSerializerOptions()
            {
                ReferenceHandler = ReferenceHandler.IgnoreCycles
            });
```

[cultureinfo_nb_no_ios.json.txt](https://github.com/dotnet/runtime/files/10177858/cultureinfo_nb_no_ios.json.txt)
[cultureinfo_nb_no_windows.json.txt](https://github.com/dotnet/runtime/files/10177859/cultureinfo_nb_no_windows.json.txt)

**Comment by tarekgh** [comment]
@mkhamoyan @steveisok you need to decide if it is worth porting the fix to 7.0.

**Comment by steveisok** [comment]
Yes, I think it is worthy of a backport.

**Comment by espenrl** [comment]
Any news on this bugfix making it into .NET 7 @steveisok ?

**Comment by espenrl** [comment]
@steveisok you are absolutely correct. It works as expected in  .NET MAUI 7.0.59 Service Release 3. Closing the issue.
