### ISSUE TITLE
Question for Service Release of Net 7

### ISSUE THREAD

**Issue by jogibear9988** [dotnet/runtime#79359]
Is there a planed Release date for a first 7.0.101? I waiting for a fix for the Hot Reload error, and would be good to know when this is planed.

**Comment by teo-tsirpanis** [comment]
[.NET servicing updates](https://learn.microsoft.com/en-us/dotnet/core/releases-and-support#servicing-updates) get released each month on Patch Tuesday (the second Tuesday of the month). For December it will be December 13.
