### ISSUE TITLE
System.Tests.ArrayTests.CreateInstance test failing in NativeAOT

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#79403]
```
[FAIL] System.Tests.ArrayTests.CreateInstance(elementType: typeof(System.Int32*), repeatedValue: null)
Assert.Equal() Failure
Expected: 1
Actual:   2
   at System.Tests.ArrayTests.VerifyArray(Array array, Type elementType, Int32[] lengths, Int32[] lowerBounds) + 0x120
   at System.Tests.ArrayTests.VerifyArray(Array array, Type elementType, Int32[] lengths, Int32[] lowerBounds, Object repeatedValue) + 0x2c
   at System.Tests.ArrayTests.CreateInstance_Advanced(Type elementType, Int32[] lengths, Int32[] lowerBounds, Object repeatedValue) + 0xb4
   at System.Tests.ArrayTests.CreateInstance(Type elementType, Object repeatedValue) + 0x58
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=105778
Build error leg or test failing: System.Tests.ArrayTests.CreateInstance
Pull request: https://github.com/dotnet/runtime/pull/79378

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section).

```json
{
  "ErrorMessage": "[FAIL] System.Tests.ArrayTests.CreateInstance(elementType: typeof(System.Int32*), repeatedValue: null)",
  "BuildRetry": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[107031](https://dev.azure.com/dnceng-public/public/_build/results?buildId=107031)|dotnet/runtime|[System.Tests.ArrayTests.CreateInstance](https://dev.azure.com/dnceng-public/public/_build/results?buildId=107031&view=ms.vss-test-web.build-test-results-tab&runId=2285878&resultId=118701)|dotnet/runtime#79435|
|[106945](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106945)|dotnet/runtime|[System.Tests.ArrayTests.CreateInstance](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106945&view=ms.vss-test-web.build-test-results-tab&runId=2284432&resultId=116120)|dotnet/runtime#79381|
|[106894](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106894)|dotnet/runtime|[System.Tests.ArrayTests.CreateInstance](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106894&view=ms.vss-test-web.build-test-results-tab&runId=2283728&resultId=119372)|dotnet/runtime#79429|
|[106767](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106767)|dotnet/runtime|[System.Tests.ArrayTests.CreateInstance](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106767&view=ms.vss-test-web.build-test-results-tab&runId=2281858&resultId=123230)|dotnet/runtime#79021|
|[106587](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106587)|dotnet/runtime|[System.Tests.ArrayTests.CreateInstance](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106587&view=ms.vss-test-web.build-test-results-tab&runId=2281740&resultId=122369)|dotnet/runtime#79422|
|[106621](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106621)|dotnet/runtime|[System.Tests.ArrayTests.CreateInstance](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106621&view=ms.vss-test-web.build-test-results-tab&runId=2279772&resultId=116445)|dotnet/runtime#79423|
|[106549](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106549)|dotnet/runtime|[System.Tests.ArrayTests.CreateInstance](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106549&view=ms.vss-test-web.build-test-results-tab&runId=2279234&resultId=117405)|dotnet/runtime#78189|
|[106483](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106483)|dotnet/runtime|[System.Tests.ArrayTests.CreateInstance](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106483&view=ms.vss-test-web.build-test-results-tab&runId=2277934&resultId=121844)|dotnet/runtime#66551|
|[106451](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106451)|dotnet/runtime|[System.Tests.ArrayTests.CreateInstance](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106451&view=ms.vss-test-web.build-test-results-tab&runId=2275852&resultId=121591)|dotnet/runtime#79418|
|[106356](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106356)|dotnet/runtime|[System.Tests.ArrayTests.CreateInstance](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106356&view=ms.vss-test-web.build-test-results-tab&runId=2274230&resultId=121775)|dotnet/runtime#79385|
|[106319](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106319)|dotnet/runtime|[System.Tests.ArrayTests.CreateInstance](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106319&view=ms.vss-test-web.build-test-results-tab&runId=2274012&resultId=123665)|dotnet/runtime#79414|
|[106270](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106270)|dotnet/runtime|[System.Tests.ArrayTests.CreateInstance](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106270&view=ms.vss-test-web.build-test-results-tab&runId=2272490&resultId=118210)|dotnet/runtime#79382|
|[106116](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106116)|dotnet/runtime|[System.Tests.ArrayTests.CreateInstance](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106116&view=ms.vss-test-web.build-test-results-tab&runId=2270334&resultId=120533)|dotnet/runtime#77597|
|[105965](https://dev.azure.com/dnceng-public/public/_build/results?buildId=105965)|dotnet/runtime|[System.Tests.ArrayTests.CreateInstance](https://dev.azure.com/dnceng-public/public/_build/results?buildId=105965&view=ms.vss-test-web.build-test-results-tab&runId=2266120&resultId=120740)|dotnet/runtime#79400|
|[105954](https://dev.azure.com/dnceng-public/public/_build/results?buildId=105954)|dotnet/runtime|[System.Tests.ArrayTests.CreateInstance](https://dev.azure.com/dnceng-public/public/_build/results?buildId=105954&view=ms.vss-test-web.build-test-results-tab&runId=2265768&resultId=120670)|dotnet/runtime#79397|
|[105927](https://dev.azure.com/dnceng-public/public/_build/results?buildId=105927)|dotnet/runtime|[System.Tests.ArrayTests.CreateInstance](https://dev.azure.com/dnceng-public/public/_build/results?buildId=105927&view=ms.vss-test-web.build-test-results-tab&runId=2265532&resultId=120799)|dotnet/runtime#79386|
|[105651](https://dev.azure.com/dnceng-public/public/_build/results?buildId=105651)|dotnet/runtime|[System.Tests.ArrayTests.CreateInstance](https://dev.azure.com/dnceng-public/public/_build/results?buildId=105651&view=ms.vss-test-web.build-test-results-tab&runId=2261520&resultId=164651)||
|[105657](https://dev.azure.com/dnceng-public/public/_build/results?buildId=105657)|dotnet/runtime|[System.Tests.ArrayTests.CreateInstance](https://dev.azure.com/dnceng-public/public/_build/results?buildId=105657&view=ms.vss-test-web.build-test-results-tab&runId=2258938&resultId=123885)|dotnet/runtime#79384|
|[105653](https://dev.azure.com/dnceng-public/public/_build/results?buildId=105653)|dotnet/runtime|[System.Tests.ArrayTests.CreateInstance](https://dev.azure.com/dnceng-public/public/_build/results?buildId=105653&view=ms.vss-test-web.build-test-results-tab&runId=2258894&resultId=121241)|dotnet/runtime#79334|
|[105632](https://dev.azure.com/dnceng-public/public/_build/results?buildId=105632)|dotnet/runtime|[System.Tests.ArrayTests.CreateInstance](https://dev.azure.com/dnceng-public/public/_build/results?buildId=105632&view=ms.vss-test-web.build-test-results-tab&runId=2258876&resultId=122916)|dotnet/runtime#79349|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|20|20|20|

**Comment by jkotas** [comment]
@MichalStrehovsky Can this be a regression from your type loader cleanups?

**Comment by elachlan** [comment]
Can someone please reset the tests on the related PRs?

**Comment by MichalStrehovsky** [comment]
> Can someone please reset the tests on the related PRs?

I can re-trigger the test if really needed but we're generally fine merging with a failing test in the CI if the failure is understood and unlikely to be related to the PR. People with merge access know the rules.

**Comment by elachlan** [comment]
Thanks :)
