### ISSUE TITLE
[Android] Wrong exception HttpClient when SSL certificate is expired

### ISSUE THREAD

**Issue by rgroenewoudt** [dotnet/runtime#79442]
### Description

When doing a HTTP request with expired certificate, using HttpClient in .NET 7 Android app, the wrong exception type returned.
Expected: HttpRequestException. Returned: WebException.

Documentation of HttpClient.SendAsync indicates HttpRequestException or TaskCanceledException should be thrown.

### Reproduction Steps

```
var httpClient = new HttpClient();
try
{
	var request = new HttpRequestMessage(HttpMethod.Get, "https://expired.badssl.com/");
	var response = await httpClient.SendAsync(request);
}
catch(HttpRequestException ex)
{
	Console.WriteLine("SUCCESS HttpRequestMessage: " + ex);
}
catch(Exception ex)
{
	Console.WriteLine("FAIL " + ex);
}
```
in .NET 7 Android app using native HTTP handler.

No issues when using SocketsHttpHandler.

### Expected behavior

```
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
```

### Actual behavior

```
System.Net.WebException: Unacceptable certificate: CN=COMODO RSA Certification Authority, O=COMODO CA Limited, L=Salford, ST=Greater Manchester, C=GB
---> Javax.Net.Ssl.SSLHandshakeException: Unacceptable certificate: CN=COMODO RSA Certification Authority, O=COMODO CA Limited, L=Salford, ST=Greater Manchester, C=GB
```
[AndroidApp7.zip](https://github.com/dotnet/runtime/files/10193918/AndroidApp7.zip)

It would be nice if the returned exception matches SocketHttpHandler by returning HttpRequestException with inner AuthenticationException and then Javax.Net.Ssl.SSLHandshakeException as inner.

Note that WebClient returns the same exception and that should keep working.

### Regression?

Unknown, Classic Xamarin Android didn't have any guarantees.

### Known Workarounds

Simply use broader catch.

### Configuration

VS2022 17.4.2
Target: .NET 7 Android 33
Device: Android 13 emulator

**Comment by simonrozsival** [comment]
This should definitely be fixed and it should have the same behavior as SocketsHttpHandler.

The code that causes the WebException is here: https://github.com/xamarin/xamarin-android/blob/main/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs#L428-L436 so we should transfer this issue to `xamarin/xamarin-android` but I don't seem to have the permissions to do that. @steveisok could you transfer the issue please?

**Comment by steveisok** [comment]
> The code that causes the WebException is here: https://github.com/xamarin/xamarin-android/blob/main/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs#L428-L436 so we should transfer this issue to `xamarin/xamarin-android` but I don't seem to have the permissions to do that. @steveisok could you transfer the issue please?

As far as I know transfer works within runtime. I think this might have to be manually created.

**Comment by rgroenewoudt** [comment]
Created a new issue in Xamarin Android: https://github.com/xamarin/xamarin-android/issues/7629
