### ISSUE TITLE
HttpClient becomes very slow and cancel request after migrating to NET 7

### ISSUE THREAD

**Issue by tycho00** [dotnet/runtime#79443]
### Description
After migrating from NET 6 to NET 7. 

HttpClient GET requests are very slow and even cancel randomly cause default timeouts. The same GET/POST requests that were made before and took seconds in Net 6, are cancelled when migrating to Net 7. Occasionally some of them work and respond in seconds, but most of them end up cancelled.

### Configuration
.NET Runtime: 7.0.0
OS version: Ubuntu 20.04 LTS
Architecture: x64

### Regression?
Yes.

### Data
![net7_degradation](https://user-images.githubusercontent.com/35170958/206679739-d919affb-2651-4a11-81ef-a74c7212a83c.png)

### Analysis
The resources are images of users of social networks and GET are made to those resources, such as Google, Facebook or Twitter. Through curl on the server or from browser, they take milliseconds:

Get request to Google (< 1sec):
`curl https://lh3.googleusercontent.com/a/ALm5wu10gbhOd8sSWCgWf0vg2XT9ygzLp00-uOyw1vXj=s96-c`

Get request to Facebook (< 1sec):
`curl https://platform-lookaside.fbsbx.com/platform/profilepic/?sid=10165562301855386&height=50&width=50&ext=1672312126&hash=AeQpzxxt19hoO_t5fUI`

Traces in the server with HttpClient (Net 7):
![image](https://user-images.githubusercontent.com/35170958/206683270-e94fee74-5b45-47f5-a388-0df4c4301fff.png)

HttpClient to do this work:
```
public sealed class ImagesHttpClient : IImagesHttpClient
{
    private readonly HttpClient _httpClient;

    public ImagesHttpClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task<byte[]> DownloadImageFromUrl(string requestUri)
    {
        try
        {
            using (var result = await _httpClient.GetAsync(requestUri))
            {
                var response = await result.Content.ReadAsByteArrayAsync();

                return response;
            }
        }
        catch
        {
            return Array.Empty<byte>();
        }
    }
}
```

Setting in program/startup:
```
services.AddHttpClient<IImagesHttpClient, ImagesHttpClient>(options =>
  {
      options.DefaultRequestVersion = HttpVersion.Version11;
      options.DefaultVersionPolicy = HttpVersionPolicy.RequestVersionOrHigher;
      options.Timeout = TimeSpan.FromSeconds(10);
  });
```

**Comment by Seabizkit** [comment]
the code u showing ImagesHttpClient  and loginwithexternalProvider have quite different names are you sure you showing/test the correct code.

**Comment by CarnaViire** [comment]
@tycho00 can you please do a packet capture on a client via Wireshark and share with us?
Can you also collect traces for your process using that example https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/networking-telemetry#dotnet-trace?

**Comment by wfurt** [comment]
It may be also nice to isolate simpler unable repro. With the `HttpVersionPolicy.RequestVersionOrHigher` I'm wondering if there is attempt to upgrade to HTTP/3 e.g. Quick. You an try to lock it on HTTP/1.1 @tycho00

**Comment by jhudsoncedaron** [comment]
@wfurt : I'm wondering if I'm the only one who found HTTP/1.1 to be fast enough.
