### ISSUE TITLE
undefined reference to 'FreeLibraryAndExitThread'

### ISSUE THREAD

**Issue by nxbear** [dotnet/runtime#79440]
Hello.

I'm trying to use the FreeLibraryAndExitThread function for detaching a profiler from CLR.
(I'm working on dotnet/coreclr. v3.1 releases)

so I've build a coreclr and link my profiler with 'libcoreclrpal.a' library.

But when I try to build my profiler, linker outputs error like this

/usr/bin/ld: /tmp/MODProfiler-7b0549.o: in function `MODProfiler::InitializeForAttach(IUnknown*, void*, unsigned int)':
MODProfiler.cpp:(.text+0xf48): undefined reference to `FreeLibraryAndExitThread'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Is there any manual about how to link with coreclr static library for profiler?
I don't know what cause of this error.

this is my build.sh file

#!/bin/sh

[ -z "${CORECLR_PATH:-}" ] && CORECLR_PATH=~/coreclr
[ -z "${BuildOS:-}"      ] && BuildOS=Linux
[ -z "${BuildArch:-}"    ] && BuildArch=x64
[ -z "${BuildType:-}"    ] && BuildType=Debug
[ -z "${Output:-}"       ] && Output=CorProfiler.so

printf '  CORECLR_PATH : %s\n' "$CORECLR_PATH"
printf '  BuildOS      : %s\n' "$BuildOS"
printf '  BuildArch    : %s\n' "$BuildArch"
printf '  BuildType    : %s\n' "$BuildType"

printf '  Building %s ... ' "$Output"

CXX_FLAGS="$CXX_FLAGS --no-undefined -Wno-invalid-noreturn -fPIC -fms-extensions -DBIT64 -DPAL_STDCPP_COMPAT -DPLATFORM_UNIX -std=c++11"
INCLUDES="-I $CORECLR_PATH/src/pal/inc/rt -I $CORECLR_PATH/src/pal/prebuilt/inc -I $CORECLR_PATH/src/pal/inc -I $CORECLR_PATH/src/inc -I $CORECLR_PATH/bin/Product/$BuildOS.$BuildArch.$BuildType/inc"
LIBS="-lpthread -L $CORECLR_PATH/bin/Product/Linux.x64.Release/lib -lcoreclrpal"
SOURCE="ClassFactory.cpp MODProfiler.cpp dllmain.cpp Common.cpp ProfileManager.cpp FunctionMapper.cpp FunctionInfo.cpp Logger.cpp MetaDataUtil.cpp StringUtil.cpp ThreadManager.cpp CallstackInfo.cpp TreeNode.cpp sigparse.cpp SignatureParser.cpp Setting.cpp Environment.cpp"

clang++ -shared -o $Output $CXX_FLAGS $INCLUDES $LIBS $SOURCE $CORECLR_PATH/src/pal/prebuilt/idl/corprof_i.cpp

printf 'Done.\n'

**Comment by jkotas** [comment]
> Is there any manual about how to link with coreclr static library for profiler?

CoreCLR PAL APIs are implementation detail of .NET runtime. It would be best to avoid taking dependency on CoreCLR PAL in your profiler.  CoreCLR PAL is meant to just support the needs of .NET runtime only and we have been moving towards removing it.

**Comment by teo-tsirpanis** [comment]
BTW .NET Core 3.1 will go out of support in three days. You should update to .NET 6 or 7.

**Comment by davmason** [comment]
Hi @nxbear,

As Jan mentioned, linking against the PAL is an unsupported scenario. It is better to use cross platform APIs rather than rely on the PAL to emulate Windows APIs. We have some prior art at https://github.com/dotnet/samples/tree/main/core/profiling and https://github.com/dotnet/runtime/tree/main/src/tests/profiler/native that shows how you can build a profiler without relying on the PAL.

**Comment by nxbear** [comment]
Thank you for your answer. So, I have to implement it separately using APIs available on each platform, Linux and Windows. I will try to refer to the link you provided."

**Comment by jkotas** [comment]
> We have some prior art at https://github.com/dotnet/samples/tree/main/core/profiling and https://github.com/dotnet/runtime/tree/main/src/tests/profiler/native that shows how you can build a profiler without relying on the PAL.

These samples do rely on the CoreCLR PAL actually and do not build against the current dotnet/runtime repo:

https://github.com/dotnet/samples/blob/main/core/profiling/stacksampling/build.sh#L7
https://github.com/dotnet/samples/blob/main/core/profiling/stacksampling/src/profiler_pal.h#L9-L10

I have opened https://github.com/dotnet/runtime/issues/80280 on this.
