### ISSUE TITLE
Add support for compile time switches compatible for both JIT and NativeAOT

### ISSUE THREAD

**Issue by xoofx** [dotnet/runtime#79488]
Hello folks,

I need to support advanced debugging/tracing in one library that I'm developing that can only be active at "compile time" (JIT or AOT). But I would like to avoid the pain of compiling my library with different preprocessor directives and generating different NuGet packages.

I have tried to use `AppContext.TryGetSwitch` (I know it says "App" so it's not really compile time) but it doesn't seem to be inlined at compile time for both JIT and NativeAOT, and it's probably expected as the switch can be set at runtime via `AppContext.SetSwitch`.

I would like to propose a compile time boolean features, a bit like how [Rust is working with compile time "features"](https://www.worthe-it.co.za/blog/2018-11-18-compile-time-feature-flags-in-rust.html). Today it seems that we have some kind of support for builtin features via [`RuntimeFeature.IsSupported`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.runtimefeature.issupported). I would like to make it available also for user switchable features:

```c#
using System.Runtime.CompilerServices;
public static class Program {
    public static readobly bool HasMyFeature = RuntimeFeature.IsSupported("MyRunTimeFeature");

    public static int Main() {
        return HasMyFeature ? 1 : 0;
    }
}
```

The feature could be activated via a MSBuild property: for a JIT app, this property would be transfered to the `runtimeconfig.json` as we do for AppContext, otherwise it would be passed directly to the Ilc NativeAOT compiler.

```xml
  <ItemGroup>
    <RuntimeFeature Include="MyRunTimeFeature" Value="true" />
  </ItemGroup>
```

Thoughts?

I could make a PR for providing such support if it is accepted (please, please! 🙂 )

cc: @MichalStrehovsky

**Comment by MichalStrehovsky** [comment]
I think we already have the thing you need - feature switches - it's also possible to use outside the core framework: https://github.com/dotnet/runtime/blob/e31ddfdc4f574b26231233dc10c9a9c402f40590/docs/workflow/trimming/feature-switches.md?plain=1#L7

**Comment by xoofx** [comment]
> I think we already have the thing you need - feature switches - it's also possible to use outside the core framework:

D'oh! Indeed, seems exactly what I was looking for! 😅 

Though, one aspect that I'm not sure to understand from the link you provided: does it work at JIT time? It seems that it is relying on `AppContext.TryGetSwitch` or am I reading it wrong? (I just skimmed over very quickly)

**Comment by MichalStrehovsky** [comment]
Yep, the trimming is emulated by the appcontext at jit time without trimming/aot

**Comment by xoofx** [comment]
Ha, I missed the `Trim=true` that was the key!
Ok, so I think I got it working with NativeAOT, but I can't make it working with JIT. 

```c#
using System.Runtime.CompilerServices;

namespace TrySwitchApp
{
    internal class Program
    {
        private static bool IsFolks => AppContext.TryGetSwitch("TrySwitchApp.Program.IsFolks", out var x) && x;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void Main(string[] args)
        {
            if (IsFolks)
            {
                Console.WriteLine("Hello Folks!");
            }
            else
            {
                Console.WriteLine("Hello World!");
            }
        }
    }
}
```
The csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <RuntimeHostConfigurationOption Include="TrySwitchApp.Program.IsFolks" Value="false" Trim="true" />
  </ItemGroup>
</Project>
```

But when I run it with tiered compilation disable, I'm still getting the switch:

```
; Assembly listing for method TrySwitchApp.Program:Main(<unnamed>)
; Emitting BLENDED_CODE for X64 CPU with AVX - Windows
; optimized code
; rsp based frame
; partially interruptible
; No PGO data
; 0 inlinees with PGO data; 1 single block inlinees; 0 inlinees without PGO data

G_M000_IG01:                ;; offset=0000H
       4883EC28             sub      rsp, 40

G_M000_IG02:                ;; offset=0004H
       33C9                 xor      ecx, ecx
       894C2420             mov      dword ptr [rsp+20H], ecx
       48B9682000C725020000 mov      rcx, 0x225C7002068
       488B09               mov      rcx, gword ptr [rcx]
       488D542420           lea      rdx, [rsp+20H]
       FF159E8B0900         call     [System.AppContext:TryGetSwitch(System.String,byref):bool]
       8B4C2420             mov      ecx, dword ptr [rsp+20H]
       0FB6C9               movzx    rcx, cl
       22C8                 and      cl, al
       7419                 je       SHORT G_M000_IG05

G_M000_IG03:                ;; offset=002DH
       48B9702000C725020000 mov      rcx, 0x225C7002070
       488B09               mov      rcx, gword ptr [rcx]
       FF15D0181000         call     [System.Console:WriteLine(System.String)]
       90                   nop

G_M000_IG04:                ;; offset=0041H
       4883C428             add      rsp, 40
       C3                   ret

G_M000_IG05:                ;; offset=0046H
       48B9782000C725020000 mov      rcx, 0x225C7002078
       488B09               mov      rcx, gword ptr [rcx]
       FF15B7181000         call     [System.Console:WriteLine(System.String)]
       90                   nop

G_M000_IG06:                ;; offset=005AH
       4883C428             add      rsp, 40
       C3                   ret

; Total bytes of code 95

Hello World!
```

Do you see anything obvious that I'm missing?

**Comment by MichalStrehovsky** [comment]
You also need an extra ILLink.Substitutions.xml manifest file embedded in the assembly that defines the replacement that needs to happen (it's not a particularly elegant or user friendly solution, but it works)

**Comment by xoofx** [comment]
> You also need an extra ILLink.Substitutions.xml manifest file embedded in the assembly that defines the replacement that needs to happen (it's not a particularly elegant or user friendly solution, but it works)

Oh, I thought that was only for NativeAOT!

Hm, so I have added this `ILLink.Substitutions.xml`:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<linker>
  <assembly fullname="TrySwitchApp" feature="TrySwitchApp.Program.IsFolks" featurevalue="false">
    <type fullname="TrySwitchApp.Program.IsFolks">
      <method signature="System.Boolean get_IsFolks()" body="stub" value="false">
      </method>
    </type>
  </assembly>
</linker>
```

And then to the csproj:

```xml
  <ItemGroup>
    <None Remove="ILLink.Substitutions.xml" />
    <EmbeddedResource Include="ILLink.Substitutions.xml" />
  </ItemGroup>
```

But I'm still getting a switch at JIT time 🤔

**Comment by jkotas** [comment]
> when I run it with tiered compilation disable, I'm still getting the switch

To get it inlined as a constant by the JIT, you would need to cache the value in readonly static and make sure that the static constructor for readonly static is triggered before the method is compiled.

**Comment by xoofx** [comment]
> To get it inlined as a constant by the JIT, you would need to cache the value in readonly static and make sure that the static constructor for readonly static is triggered before the method is compiled.

Oh right, I got it working, thanks!
As I thought that specifying alone that a particular method should fold to a constant would be enough.

That's perfect, I'm super happy that I can use that!

**Comment by xoofx** [comment]
I think It was a bit difficult to get it working because I couldn't see any mention of this in the feature-switches docs and I haven't seen any clear example in the codebase that is really relying on this as-is (static readonly field + separate static method for ILLink substitution + accessing the static ctor before using it in places you want the optimization to happen)

**Comment by xoofx** [comment]
Version that is working for both JIT and AOT:

```c#
using System.Runtime.CompilerServices;

namespace TrySwitchApp
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(Program2.IsFolksCalculated);
            Main2();
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        static void Main2()
        {
            if (Program2.IsFolksCalculated)
            {
                Console.WriteLine("Hello Folks!");
            }
            else
            {
                Console.WriteLine("Hello World!");
            }
        }
    }

    internal class Program2
    {
        public static readonly bool IsFolksCalculated = IsFolks;
        public static bool IsFolks => AppContext.TryGetSwitch("TrySwitchApp.Program2.IsFolks", out var x) && x;
    }
}
```

csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ILLink.Substitutions.xml" />
    <EmbeddedResource Include="ILLink.Substitutions.xml" />
    <RuntimeHostConfigurationOption Include="TrySwitchApp.Program2.IsFolks" Value="false" Trim="true" />
  </ItemGroup>
</Project>
```

ILLink.Substitutions.xml:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<linker>
  <assembly fullname="TrySwitchApp" feature="TrySwitchApp.Program2.IsFolks" featurevalue="false">
    <type fullname="TrySwitchApp.Program2.IsFolks">
      <method signature="System.Boolean get_IsFolks()" body="stub" value="false">
      </method>
    </type>
  </assembly>
</linker>
```

**Comment by MichalStrehovsky** [comment]
> I think It was a bit difficult to get it working because I couldn't see any mention of this in the feature-switches docs and I haven't seen any clear example in the codebase that is really relying on this as-is

Yeah, we use it internally and it sort of works, but all of these experiences that require a sidecar XML file are really annoying. We still need something like https://github.com/dotnet/linker/pull/1723 to be able to really recommend this for public consumption. It works, and the substitutions formats are soft-documented, but it's far from ideal.

**Comment by xoofx** [comment]
> Yeah, we use it internally and it sort of works

And I'm curious where this pattern is actually used because while digging into many places in the dotnet/runtime repo where `AppContext.TryGetSwitch` is being used, I haven't seen yet a place where we are putting the result of the static method (that will get substituted) into a static readonly field.

**Comment by jkotas** [comment]
> I'm curious where this pattern is actually used 

For example, here: https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Private.CoreLib/src/System/Globalization/GlobalizationMode.cs#L15-L21

> I haven't seen yet a place where we are putting the result of the static method (that will get substituted) into a static readonly field.

The typical pattern is other way around to allow better trimming. Method that gets substituted returns a static readonly field.
