### ISSUE TITLE
NegotiateStream test deterministically fails locally on Windows 11

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#79481]
With a clean build of dotnet/runtime, just doing `dotnet build /t:test` in the System.Net.Security functional tests results in 13 failures for me locally.  All of them are variations of the NegotiateStream_StreamToStream_Authentication_EmptyCredentials_Fails test, e.g.
```
System.Net.Security.Tests.NegotiateStreamStreamToStreamTest_Async_Memory_NotEncrypted.NegotiateStream_StreamToStream_Authentication_EmptyCredentials_Fails [FAIL]
        System.AggregateException : One or more errors occurred. (Authentication failed, see inner exception.) (Authentication failed on the remote side (the stream might still be available for additional authentication attempts).
  )
        ---- System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.
        -------- System.ComponentModel.Win32Exception : No credentials are available in the security package
        ---- System.Security.Authentication.AuthenticationException : Authentication failed on the remote side (the stream might still be available for additional authentication attempts).
        -------- System.ComponentModel.Win32Exception : Unspecified error
        Stack Trace:
          D:\repos\runtime\src\libraries\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs(88,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
          D:\repos\runtime\src\libraries\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs(55,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
          D:\repos\runtime\src\libraries\System.Net.Security\tests\FunctionalTests\NegotiateStreamStreamToStreamTest.cs(213,0): at System.Net.Security.Tests.NegotiateStreamStreamToStreamTest.NegotiateStream_StreamToStream_Authenti
  cation_EmptyCredentials_Fails()
          --- End of stack trace from previous location ---
          ----- Inner Stack Trace #1 (System.Security.Authentication.AuthenticationException) -----
          D:\repos\runtime\src\libraries\System.Net.Security\src\System\Net\Security\NegotiateStream.cs(922,0): at System.Net.Security.NegotiateStream.SendAuthResetSignalAndThrowAsync[TIOAdapter](Byte[] message, Exception exceptio
  n, CancellationToken cancellationToken)
          D:\repos\runtime\src\libraries\System.Net.Security\src\System\Net\Security\NegotiateStream.cs(759,0): at System.Net.Security.NegotiateStream.SendBlobAsync[TIOAdapter](Byte[] message, CancellationToken cancellationToken)
          D:\repos\runtime\src\libraries\System.Net.Security\src\System\Net\Security\NegotiateStream.cs(899,0): at System.Net.Security.NegotiateStream.ReceiveBlobAsync[TIOAdapter](CancellationToken cancellationToken)
          D:\repos\runtime\src\libraries\System.Net.Security\src\System\Net\Security\NegotiateStream.cs(844,0): at System.Net.Security.NegotiateStream.SendBlobAsync[TIOAdapter](Byte[] message, CancellationToken cancellationToken)
          D:\repos\runtime\src\libraries\System.Net.Security\src\System\Net\Security\NegotiateStream.cs(708,0): at System.Net.Security.NegotiateStream.AuthenticateAsync[TIOAdapter](CancellationToken cancellationToken)
          D:\repos\runtime\src\libraries\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs(120,0): at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
          ----- Inner Stack Trace -----

          ----- Inner Stack Trace #2 (System.Security.Authentication.AuthenticationException) -----
          D:\repos\runtime\src\libraries\System.Net.Security\src\System\Net\Security\NegotiateStream.cs(958,0): at System.Net.Security.NegotiateStream.ThrowCredentialException(Int64 error)
          D:\repos\runtime\src\libraries\System.Net.Security\src\System\Net\Security\NegotiateStream.cs(872,0): at System.Net.Security.NegotiateStream.ReceiveBlobAsync[TIOAdapter](CancellationToken cancellationToken)
          D:\repos\runtime\src\libraries\System.Net.Security\src\System\Net\Security\NegotiateStream.cs(844,0): at System.Net.Security.NegotiateStream.SendBlobAsync[TIOAdapter](Byte[] message, CancellationToken cancellationToken)
          D:\repos\runtime\src\libraries\System.Net.Security\src\System\Net\Security\NegotiateStream.cs(899,0): at System.Net.Security.NegotiateStream.ReceiveBlobAsync[TIOAdapter](CancellationToken cancellationToken)
          D:\repos\runtime\src\libraries\System.Net.Security\src\System\Net\Security\NegotiateStream.cs(708,0): at System.Net.Security.NegotiateStream.AuthenticateAsync[TIOAdapter](CancellationToken cancellationToken)
          D:\repos\runtime\src\libraries\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs(120,0): at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
          ----- Inner Stack Trace -----
```

**Comment by filipnavara** [comment]
Out of curiosity, is the machine domain-joined? If yes, to regular domain controller or Azure AD? What is the exact Windows 11 build number?

**Comment by filipnavara** [comment]
Out of curiosity, is the machine domain-joined? If yes, to regular domain controller or Azure AD? What is the exact Windows 11 build number?

**Comment by stephentoub** [comment]
22H2 Build 22621.819

**Comment by filipnavara** [comment]
Thanks. I wanted to gather the info so I can try to reproduce it next week.

**Comment by filipnavara** [comment]
Not very useful, except as a data point: Windows 11 Build 22621.900, no domain join -> tests pass

I suppose that the Azure AD may influence the results.

**Comment by wfurt** [comment]
There may be more to it. _If_ this is corporate machine it may have extra restrictions - preventing weak options. The `NotEncrypted` makes me wonder...

**Comment by filipnavara** [comment]
> There may be more to it. _If_ this is corporate machine it may have extra restrictions - preventing weak options. The `NotEncrypted` makes me wonder...

That's the most likely explanation. Joining Azure AD didn't make a difference. Disabling NTLM through Group Policies makes the same test fail with slightly different error:

```
      System.Net.Security.Tests.NegotiateStreamStreamToStreamTest_Async_TestOverloadProtectionLevel.NegotiateStream_Str
  eamToStream_Authentication_EmptyCredentials_Fails [FAIL]
        System.AggregateException : One or more errors occurred. (Authentication failed on the remote side (the stream
  might still be available for additional authentication attempts).) (Authentication failed, see inner exception.)
        ---- System.Security.Authentication.AuthenticationException : Authentication failed on the remote side (the str
  eam might still be available for additional authentication attempts).
        -------- System.ComponentModel.Win32Exception : Unspecified error
        ---- System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.
        -------- System.ComponentModel.Win32Exception : The function requested is not supported
```

I didn't find a setting that would result in exactly the same error, but I can make it fail in the same code path.

**Comment by filipnavara** [comment]
Aside from blanket NTLM bans the closest thing I can think of is `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0` and the values of `NTLMMinClientSec`/`NTLMMinServerSec`.

**Comment by SteveSyfuhs** [comment]
Also check `LmCompatibilityLevels` https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-security-lan-manager-authentication-level

**Comment by Flir2023** [comment]
> > There may be more to it. _If_ this is corporate machine it may have extra restrictions - preventing weak options. The `NotEncrypted` makes me wonder...
> 
> That's the most likely explanation. Joining Azure AD didn't make a difference. Disabling NTLM through Group Policies makes the same test (same 13 tests, to be precise) fail with slightly different error:
> 
> ```
>       System.Net.Security.Tests.NegotiateStreamStreamToStreamTest_Async_TestOverloadProtectionLevel.NegotiateStream_Str
>   eamToStream_Authentication_EmptyCredentials_Fails [FAIL]
>         System.AggregateException : One or more errors occurred. (Authentication failed on the remote side (the stream
>   might still be available for additional authentication attempts).) (Authentication failed, see inner exception.)
>         ---- System.Security.Authentication.AuthenticationException : Authentication failed on the remote side (the str
>   eam might still be available for additional authentication attempts).
>         -------- System.ComponentModel.Win32Exception : Unspecified error
>         ---- System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.
>         -------- System.ComponentModel.Win32Exception : The function requested is not supported
> ```
> 
> I didn't find a setting that would result in exactly the same error, but I can make it fail in the same code path.

Hi, I disabled NTLM and got this error as you mentioned. Is there a solution to be able to diable NTLM and still 
Hi, I disabled NTLM and got this error as you mentioned. Is there a solution that allows NTLM to be disabled and still have it work?
NegotiateStream.AuthenticateAsClient() can also work through Kerberos.

**Comment by karelz** [comment]
@stephentoub is it still failing for you? We might need to have @wfurt to debug it with you.

**Comment by stephentoub** [comment]
> @stephentoub is it still failing for you? We might need to have @wfurt to debug it with you.

Just tried and the suite is passing.

I'll close this and will re-open if it starts happening again.
