### ISSUE TITLE
[NativeAOT] Crash with access violation instead of throwing System.NullReferenceException

### ISSUE THREAD

**Issue by tomcashman** [dotnet/runtime#79494]
Is there a ilc compiler flag to emit System.NullReferenceException code in NativeAOT?

We have some code that relies on System.NullReferenceException to be caught and handled but is currently crashing with an access violation.

The following is a simple example program that reproduces the issue.

```csharp
        public class TestObject
        {
            public void Method()
            {
                Console.WriteLine("Success");
            }
        }

        public static void NullTest(TestObject testObject)
        {
            testObject.Method();
        }

        static void Main(string[] args)
        {
            try
            {
                NullTest(null);
            }
            catch (System.NullReferenceException e)
            {
                Console.WriteLine("Caught exception");
            }
        }   
```

**Comment by MichalStrehovsky** [comment]
> The following is a simple example program that reproduces the issue.

On what platform? I just tried on Windows x64 and it catches it.

The compiler doesn't insert null checks to throw this - the runtime relies on the hardware exception raised by the CPU and converts that to a managed exception.

**Comment by tomcashman** [comment]
> The compiler doesn't insert null checks to throw this - the runtime relies on the hardware exception raised by the CPU and converts that to a managed exception.

Where does this conversion/handling happen in the code base?

Sorry I forgot to specify that we're encountering this on our NativeAOT console ports. They're Unix and Windows-based but perhaps the exception codes are different.

**Comment by jkotas** [comment]
The mapping happens here: https://github.com/dotnet/runtime/blob/b622489f6a188c96cf999c7f0efaf96bd7af791a/src/coreclr/nativeaot/Runtime/unix/HardwareExceptions.cpp#L507-L582

Are you able to depend on signals in your console ports?

**Comment by tomcashman** [comment]
Thanks for the responses and info.

Looks like we can't rely on signals or hardware exceptions on consoles. The hardware exceptions I wasn't previously aware of but looks like they're considered a game crash on most platforms. We'll just have to handle our scenario a different way on console platforms. Sorry to bother you 😄
