### ISSUE TITLE
MacOS 104 path length limit. Invalid length for use with domain sockets on this platform.  The length must be between 1 and 104

### ISSUE THREAD

**Issue by ep1kt3t0s** [dotnet/runtime#79503]
### Description

On MacOS (13.0.1, Apple Silicon) with dotnet 6.0.403 and 6.0.400 I got the below issue with paths being restricted to 104 characters.
I do think MacOS allows paths longer than 104, so I'm not sure where the 104 is coming.
I found this below code snippet that which I believe sets the 104 character limit but I could not run it on my dev environment.
`Interop.Sys.GetDomainSocketSizes(out s_nativePathOffset, out s_nativePathLength, out s_nativeAddressSize);`

But I am also using `Path.GetTempPath()` to get a work directory which produces a path like `/var/folders/7b/tkffkjy54676nvv44rpvv1l40000gn/T/`, which is quite long already.

The rest of the socket pipe, coming from using `ffmpeg` but I don't think related to it, creates a path of `CoreFxPipe_FFMpegCore_782288f0-1e42-4550-ab59-5a5161581e5b` and combination of these exceed 104 characters.

I do believe something might be wrong on MacOS with 104 character limit and might be better to check it out.

```
System.ArgumentOutOfRangeException: The path '/var/folders/7b/tkffkjy54676nvv44rpvv1l40000gn/T/CoreFxPipe_FFMpegCore_782288f0-1e42-4550-ab59-5a5161581e5b' is of an invalid length for use with domain sockets on this platform.  The length must be between 1 and 104 characters, inclusive. (Parameter 'path')
      Actual value was /var/folders/7b/tkffkjy54676nvv44rpvv1l40000gn/T/CoreFxPipe_FFMpegCore_782288f0-1e42-4550-ab59-5a5161581e5b.
         at System.Net.Sockets.UnixDomainSocketEndPoint..ctor(String path, String boundFileName)
         at System.Net.Sockets.UnixDomainSocketEndPoint..ctor(String path)
         at System.IO.Pipes.NamedPipeServerStream.SharedServer..ctor(String path, Int32 maxCount)
         at System.IO.Pipes.NamedPipeServerStream.SharedServer.Get(String path, Int32 maxCount)
         at System.IO.Pipes.NamedPipeServerStream.Create(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, HandleInheritability inheritability)
         at System.IO.Pipes.NamedPipeServerStream..ctor(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options)
```

### Reproduction Steps

Create a named pipe from a socket within the directory `Path.GetTempPath()`.

### Expected behavior

Should not error for 104 character limit on MacOS.

### Actual behavior

Errors for 104 character limit on MacOS.

**Comment by stephentoub** [comment]
https://man.openbsd.org/unix.4

"UNIX-domain addresses are variable-length filesystem pathnames of at most 104 characters."

We don't hardcode the length. It comes directly from the os:
https://github.com/dotnet/runtime/blob/3689fbec921418e496962dc0ee252bdc9eafa3de/src/native/libs/System.Native/pal_networking.c#L3093

**Comment by ep1kt3t0s** [comment]
Surprising the limit is only 104 characters. I actually did not hit this limit on Ubuntu but hitting it on MacOS.

**Comment by stephentoub** [comment]
On Linux the limit is typically 108 and the default temp path is usually much shorter.

**Comment by ep1kt3t0s** [comment]
Thank you for the clarification @stephentoub
