### ISSUE TITLE
.Net decimal vs SQL Server decimal

### ISSUE THREAD

**Issue by reader-man** [dotnet/runtime#7951]
Hi,
Thanks for the great .Net Core product/Tech.

SQL Server decimal size is very good for huge scientific numbers:
[](https://docs.microsoft.com/en-us/sql/t-sql/data-types/decimal-and-numeric-transact-sql)
it reaches 38 precision.

, but .Net/.Net Core does not match it:
[](https://msdn.microsoft.com/en-us/library/364x0z75.aspx)
it stops at 28 precision.

So, instead of going to non normal steps like string manipulation, it would be great to have the .net core decimal get bigger enough to hold the full precision and scale of the sql server decimal, or have decimal2 to be as sql server decimal precision.

Regards.

**Comment by tannergooding** [comment]
There hasn't been a response here in 3 years. Going to close.

Please feel free to reopen with more details if you have them 😄
