### ISSUE TITLE
Regression in Microsoft.Extensions.Options when IOptionsMonitor<T> created concurrently

### ISSUE THREAD

**Issue by petedishman** [dotnet/runtime#79529]
### Description

v7 has introduced a change in behaviour when the first creation of an `IOptionMonitor<T>` instance is done many times concurrently.

Given configuration code like this:  
```
                services.AddOptions<TestOptions>("testing")
                    .Configure<DummyService>((options, dummyService) =>
                    {
                        Console.WriteLine("Configuring TestOptions instance");
                    });
```

In dotnet 6 you could create multiple instances of `IOptionsMonitor<TestOptions>` concurrently on startup and the configuration callback would only be called once.

In dotnet 7, the same operation results in multiple calls to the configuration callback.

This was originally noticed as configuration of Microsoft.Identity.Web authentication stopped working correctly post upgrade to dotnet 7.

I raised a ticket there (https://github.com/AzureAD/microsoft-identity-web/issues/1995), but it was then narrowed down to be a Microsoft.Extensions.Options problem instead, so raising ticket here as @Tratcher suggested.

### Reproduction Steps

https://github.com/petedishman/OptionsTest contains a reproduction of this problem with two identical projects, except one is configured with the v6 versions of the libraries, and the other with v7.

The code sets up configuration as above, and then creates (concurrently) multiple instances of a service that take `IOptionsMonitor<TestOptions>` as a dependency.

When run against v6 libraries you get this output:
```
C:\build\examples\OptionsTest\OptionsTest6> dotnet run
Building...
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\build\examples\OptionsTest\OptionsTest6
Creating TestOptions instance
Creating TestOptions instance
Creating TestOptions instance
Creating TestOptions instance
Creating TestOptions instance
Configuring TestOptions instance
```

When run against v7, you get this:
```
C:\build\examples\OptionsTest\OptionsTest7> dotnet run
Building...
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\build\examples\OptionsTest\OptionsTest7
Creating TestOptions instance
Creating TestOptions instance
Creating TestOptions instance
Creating TestOptions instance
Creating TestOptions instance
Configuring TestOptions instance
Configuring TestOptions instance
Configuring TestOptions instance
Configuring TestOptions instance
Configuring TestOptions instance
```

After the initial concurrent access, subsequent calls to inject an `IOptionsMonitor<TestOptions>` instance correctly don't re-run the configuration callback.

### Expected behavior

The configuration callback should only be executed when multiple instances are requested concurrently

### Actual behavior

The configuration callback is called multiple times when initialised many times concurrently

### Regression?

Yes - regression since v6

https://github.com/dotnet/runtime/pull/66688 seems likely to be related/the cause

### Known Workarounds

Initialising the `IOptionsMonitor<T>` instance once manually before any possible concurrent access works around the problem.

### Configuration

Tested on .net 6 & 7 running on both windows & linux x64. Does not appear to be platform specific.

**Comment by tarekgh** [comment]
CC @madelson @eerhardt as there is a susception https://github.com/dotnet/runtime/pull/66688 could be the cause. I'll try to look later early next year :-)

**Comment by madelson** [comment]
@tarekgh I think I've identified the issue. See https://github.com/dotnet/runtime/pull/79639

**Comment by layomia** [comment]
Re-opening per https://github.com/dotnet/runtime/issues/79529#issuecomment-1358218038. @dotnet/area-extensions-options

**Comment by tarekgh** [comment]
@petedishman @tratacher could you please elaborate more about the exact problem that happened in the production? I know the callback will be called multiple times, but what exactly the side effect with that that break the production?

**Comment by Tratcher** [comment]
See https://github.com/AzureAD/microsoft-identity-web/issues/1995 where this caused the options instance to be mis-configured such that OIDC events are called multiple times for the same request. These events aren't expecting that and can fail.

**Comment by davidfowl** [comment]
Yes we should patch this one.

**Comment by tarekgh** [comment]
I'll start the patch process early next year when I am back. I already marked the issue with the 7.0 milestone. 

@petedishman is there a way to try the fix https://github.com/dotnet/runtime/pull/79639 in your environment to validate the fix?

**Comment by tarekgh** [comment]
This has been ported to the 7.0 servicing release branch though the PR https://github.com/dotnet/runtime/pull/80150.
