### ISSUE TITLE
Make ConfigurationBinder source generator feature-complete

### ISSUE THREAD

**Issue by layomia** [dotnet/runtime#79527]
Follow up work for the configuration binding source generator (https://github.com/dotnet/runtime/issues/44493, https://github.com/dotnet/runtime/pull/82179).

#### Preview 3

- [x] Support objects with parameterless ctors
- [x] Initial collection support (readonly collections were left out) 

#### Preview 4

- [x] https://github.com/dotnet/runtime/issues/83533
- [x] Add SDK prop (`EnableConfigurationBinderGenerator`) to serve as gesture to invoke generator (e.g. [EnableRequestDelegateGenerator flag](https://github.com/dotnet/sdk/pull/29982)) (as part of https://github.com/dotnet/sdk/issues/30872) and include generator in the ASP.NET Targeting Pack

#### Preview 5

- [x] Finish collection support (i.e readonly collections) - https://github.com/dotnet/runtime/pull/86285

#### Preview 6

- [x] Implement the right constructor invocation logic for classes, structs, record (+ init-only setters / required props) - https://github.com/dotnet/runtime/pull/86365
- [x] https://github.com/dotnet/runtime/issues/83600

#### Preview 7

- [x] Close on whether binding customization is needed: https://github.com/dotnet/runtime/issues/83599

#### RC 1

- [ ] https://github.com/dotnet/runtime/issues/83534
- [x] https://github.com/dotnet/runtime/issues/89322

#### Stretch / tbd / validation

- [ ] https://github.com/dotnet/performance/issues/2929
- [ ] Enable nullable annotations in generator project

<details>
<summary>FX DC feedback</summary>

There may be bad UX edge cases that need to be investigated, such as :

- The roslyn analyzers report an unused using-import from where the existing extension methods are (might be topically unlikely)
    - write the smallest possible source file that could invoke each hook and make sure that we don't have unused usings after source generator hooks the callsite.
- Concerns around callers using static invocation syntax instead of instance/extension syntax.
    - feature not a bug
    - make sure it triggers linker warning
    - have documentation on that linker warning that leads people to using the generator. 
- The generator might end up toggling itself on and off (by removing the calls to the existing methods)
    - have a discussion and review the triggering logic with folks from the compiler team
</details>

**Comment by jkotas** [comment]
Also, we should have this source generator documented at https://learn.microsoft.com/en-us/dotnet/core/extensions/configuration. Once the documentation is available, please update [this link](https://github.com/dotnet/docs/pull/36769/files#diff-52a827bf00d533c0782b508c3d107a393c70e30d5d98ee891d2f70ad2e7892e5R35) to point to it.

**Comment by layomia** [comment]
Closing. Tracking remaining 8.0 work in https://github.com/orgs/dotnet/projects/303/views/1.
