### ISSUE TITLE
Analyzer suggestion: Avoid unnecessary enum boxing

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/runtime#79548]
This analyzer will flag calls to `enumValue.GetHashCode()` and suggests either `(int)enumValue` or ((int)enumValue).GetHashCode()` to avoid boxing allocations.

See https://github.com/dotnet/roslyn/pull/65939 where this was causing a performance overhead.

**Comment by stephentoub** [comment]
The JIT in .NET Core already optimizes that:
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYRoG8aHunGBLAHYYGAWXIAKACLYAngHkAZgHUYMANYMAJgEoGAXgB8WgHQBxGBgASeABYsImmON0BuLj3oNBwkaSmzFFXUtXUMGcXFvXR0GMwtrXDsHJ1caGgBfIA=

**Comment by stephentoub** [comment]
My point was meant to be that I don't think we should have ship new analyzers telling developers to make their code more convoluted for things solved already by upgrading to a better runtime.

**Comment by Youssef1313** [comment]
I see the point, and I have no strong opinion here.

Looking through the history of https://github.com/dotnet/roslyn-analyzers/tree/main/src/NetAnalyzers/Core/Microsoft.NetFramework.Analyzers, I see that no analyzers specific to .NET Framework are newly written. Going to close this then.
