### ISSUE TITLE
Could not load file or assembly 'System.Net.Mail, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by ygoe** [dotnet/runtime#79545]
### Description

For an unknown reason, .NET 6.0 seems to be installed incomplete. When trying to use a System.Mime method, this exception is thrown:

Could not load file or assembly 'System.Net.Mail, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

That's outside the scope of my application. I have no code line numbers in my exception log, but I'm not using System.Net.Mail anywhere near the indicated method. Just Mime. Which at least includes the Mail namespace according to what I see when I go to the definition in Visual Studio (whereever I land there, it's probably the original .NET source code).

My application is installed by copying the published files for a framework-dependent build. It's running since .NET 2.1 was new, so quite some time. Never had this trouble. Building with VS 2022.

### Reproduction Steps

Maybe this? In an ASP.NET Core 6.0 application.

```cs
var cd = new System.Net.Mime.ContentDisposition
{
	FileName = $"Dashboard {dashboard.Name.MakeFileName()}.pdf",
	Inline = true
};
string cdStr = cd.ToString().Replace("\r", "").Replace("\n", " ");
Response.Headers.Add("Content-Disposition", cdStr);
```

### Expected behavior

No exception...

### Actual behavior

Exception see above...

### Regression?

Yes, it has worked in .NET 3.1. I assume that the .NET packages are missing an important file.

### Known Workarounds

None, the service is currently not available because of this bug.

### Configuration

Ubuntu 20.04 x64, installed through official packages

```
dotnet --info

global.json file:
  Not found

Host:
  Version:      6.0.11
  Architecture: x64
  Commit:       943474ca16

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.31 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.31 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by wfurt** [comment]
I could not reproduce running simplified console app @ygoe. 
Can you post full runable repro?
