### ISSUE TITLE
JsonSerializer no longer passes the CancellationToken to the AsyncEnumerable

### ISSUE THREAD

**Issue by Tratcher** [dotnet/runtime#79556]
### Description

This commit refactored the JsonSerializer:
https://github.com/dotnet/runtime/commit/3559d339d4989039be8c3cb37e115bdad2f76c93#diff-65021de09c4fb9b39607f1f3ed228e53cd04b483880f66b0ea56310f71a5e400L320

However, now state.CancellationToken doesn't get set anymore. This is failing tests in AspNetCore
https://dev.azure.com/dnceng-public/public/_build/results?buildId=109479&view=ms.vss-test-web.build-test-results-tab&runId=2337376&resultId=105425&paneView=debug

https://github.com/dotnet/runtime/blob/0e6013077eba9e9dc2923c87ff3079cc65d2576e/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfoOfT.WriteHelpers.cs#L117-L122

### Reproduction Steps

The test cancels the token as soon as the async enumeration starts, but the token is not passed through to the IAsyncEnumerable.
https://github.com/dotnet/aspnetcore/blob/6956f42a0a01ed4fb8fc2cb889c2535f8fe5f735/src/Http/Http.Extensions/test/HttpResponseJsonExtensionsTests.cs#L360-L369

### Expected behavior

The cancellation token should be passed through to the enumerator.

### Actual behavior

The cancellation token is not passed through to the enumerator.

### Regression?

Yes, 7 days ago.
https://github.com/dotnet/runtime/commit/3559d339d4989039be8c3cb37e115bdad2f76c93#r92837773

### Configuration

8.0.0-alpha.1.22611.2
https://github.com/dotnet/aspnetcore/pull/45475/files#diff-1ea18ff65faa2ae6fed570b83747086d0317f5e4bc325064f6c14319a9c4ff67R122

**Comment by eiriktsarpalis** [comment]
Our test coverage seems to have missed that because it relied on validating that the serialization operation throws TaskCanceledException:

https://github.com/dotnet/runtime/blob/fdd1f635234dc33f71e2e16d208fe5c08b4147e6/src/libraries/System.Text.Json/tests/Common/CollectionTests/CollectionTests.AsyncEnumerable.cs#L129-L141

Looking at your test, is it fair to assume that your destination stream is ignoring cancelled tokens?

**Comment by Tratcher** [comment]
The destination stream is MemoryStream, which should honor cancellation.

**Comment by eiriktsarpalis** [comment]
Even though the token is not passed to the converters, it is still being passed to the underlying stream so I would this line

https://github.com/dotnet/aspnetcore/blob/6956f42a0a01ed4fb8fc2cb889c2535f8fe5f735/src/Http/Http.Extensions/test/HttpResponseJsonExtensionsTests.cs#L350

to throw `TaskCanceledException`.
