### ISSUE TITLE
Failing tests in the Mono leg doesn't fail the CI

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#79579]
This leg looks all nice and green:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=109093&view=logs&jobId=f50bdeb8-70f9-5fe0-0c12-4bd43ab59b51&j=55625a83-07ac-525a-fb32-9d705da79581&t=ed547991-520a-5120-9a9a-8b7bdbddb033

But if you actually drill into the Helix console logs of one of the tests:

https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-79523-merge-afc22ef01dc2486a9f/System.IO.Pipes.Tests/1/console.ad2ab646.log?helixlogtype=result

There is a failure.

I'm disabling this particular test in #79578 so this is not going to repro soon.

**Comment by steveisok** [comment]
Weird, the test is being flagged as a failure in the "Tests" tab.  Wonder why it's showing green?

**Comment by steveisok** [comment]
Raised this on FR
