### ISSUE TITLE
[API Proposal]: Add Generic AddRange overloads to List and similar to improve performance

### ISSUE THREAD

**Issue by fitdev** [dotnet/runtime#79593]
### Background and motivation

Right now there is `void AddRange(IEnumerable<T> collection)` instance method on `List<T>`. This works great if `collection` is a reference type, i.e. a _class_ implementing `IEnumerable<T>` and already on the heap. However, if `collection` is a _struct_, then every such call requires boxing, which significantly decreases performance.

This may not seem like a big deal, since normally `AddRange` methods are not called often, however in my scenario, on several occasions I had to call it as often as `Add`. In particular I have a _struct_ `OneOrMore<T>` which, as the name suggests can have either one `T` or more `T`s. It is a convenience type which normally would contain just one item, but sometimes may contain 10s or even 100s, which is the reason it is used instead of say `T[]` (because most of the time there is just one item).

Back to the API proposal: If we pass such a struct into the current `AddRange` method, it will be boxed, kind of negating the benefit of using the struct as opposed to an array in the first place. That's where API proposal seems useful.

The example below is just for `List<T>` but ideally same / similar APIs should be employed with other collections as well where appropriate.

### API Proposal

```csharp
namespace System.Collections.Generic;

public class List<T> : IList<T>, IList, IReadOnlyList<T>
{
  public void AddRangeWithoutBoxing<TEnumerable>(TEnumerable items) where TEnumerable : IEnumerable<T> // <-- Note the generic type parameter constraint which allows us avoid boxing
  {
    this.AddRange(items);
  }
}
```

The method name `AddRangeWithoutBoxing` is just an example. Ideally some better name should be used.

### API Usage

```csharp
var l = new List<int>();
OneOrMore<int> structBasedEnumerable = new OneOrMore<int>(1, 2, 3); 
l.AddRangeWithoutBoxing(structBasedEnumerable);

public readonly struct OneOrMore<T> : IEnumerable<T> { ... }

```

### Alternative Designs

Instead of it being an instance method with `TEnumerable` generic type parameter, it could be an extension method with 2 generic type parameters - `T` and `TEnumerable`.

### Risks

Don't see any.

**Comment by DaZombieKiller** [comment]
With https://github.com/dotnet/runtime/issues/55217 you can do:
```cs
int start = list.Count;
CollectionsMarshal.SetCount(list, start + buffer.Count);
buffer.CopyTo(CollectionsMarshal.AsSpan(list).Slice(start));
```
Which you could implement as an instance method on a custom type derived from `List<T>`. An extension method would unfortunately not work as the compiler wouldn't be able to infer the generic parameters today.

**Comment by En3Tho** [comment]
I'm not sure how this will help you eliminating IEnumerator<T> allocation though. If allocations are no-go in your scenario then a specialized extension method can help you better than such an overload

**Comment by fitdev** [comment]
@En3Tho 

You are right here, but at least there is one allocation less (per each method call that is).

**Comment by DaZombieKiller** [comment]
> And as for type params in extension methods - it works perfectly fine today with the latest C# - both type parameters are inferred from the extension method (which is how I did it now).

You're correct, I was mistakenly thinking of the case where the `this` type is itself a generic parameter.

**Comment by En3Tho** [comment]
@fitdev IEnumerable`T contract strictly specifies that it returns IEnumerator`T, not T where T is an IEnumerator`U. So you will end up with enumerator allocation anyway. Even if it is a struct. Maybe PGO can elide an allocation in this case e.g. type check + direct call but I'm not sure.

**Comment by eiriktsarpalis** [comment]
We generally don't add new instance methods to popular generic types like `List<T>`, as that generally increases the static footprint for every .NET application, even the ones that don't use the new method. I don't see this use case as being particularly compelling, it could easily be defined as an extension method using either the list's indexer or as already mentioned the new `CollectionsMarshal` helpers. As far as enumerator allocations are concerned, it should be pointed out that the existing `InsertRange`/`AddRange` methods already optimize for inputs implementing `ICollection<T>`, so no further allocations should be observed in that case.
