### ISSUE TITLE
[mono][perf] WASM disk size regression on 21 Nov 2022

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#79599]
### Description

Disk size (SOD) regression detected in Mono Blazorwasm. 

#### Details - Mono

Date | Diff | Change | Size increase (bytes) | Size increase (%)
--|--|--|--|--
21 Nov 2022 | https://github.com/dotnet/runtime/compare/8171bd0ed6622b686ddc31a5a763548d6a6516f4...aa914518cae222ead75503e5c272299608a0a6c5 | https://github.com/dotnet/runtime/commit/aa914518cae222ead75503e5c272299608a0a6c5   |     15002 |	0.70

<img width="1977" alt="Screenshot 2022-12-13 at 10 14 11" src="https://user-images.githubusercontent.com/11523312/207292768-54f389f4-2427-43e4-964b-0af39ed7c563.png">

<hr>

#### Details - Mono AOT

Date | Diff | Change | Size increase (bytes) | Size increase (%)
-|--|--|--|--
21 Nov 2022 | https://github.com/dotnet/runtime/compare/8171bd0ed6622b686ddc31a5a763548d6a6516f4...dd0ec9471dde6b6740ae6d9b504b64dec190b438 |https://github.com/dotnet/runtime/commit/aa914518cae222ead75503e5c272299608a0a6c5  |     87278 |	2.20

<img width="2035" alt="Screenshot 2022-12-13 at 11 26 52" src="https://user-images.githubusercontent.com/11523312/207293248-c1713175-de23-4236-8254-cd03b39703e6.png">

### Configuration

OS: Ubuntu 18.04
Architecture: x64
.NET version: 7.0.100-rc.1.22431.12

**Comment by MihaZupan** [comment]
Is this issue tracking anything actionable?

**Comment by kotlarmilos** [comment]
We should check if there is anything we can do to mitigate the regression. I have moved the issue to .NET 9 due to low priority.
