### ISSUE TITLE
How to manage connections towards Apache when MaxKeepAliveRequests is not infinite?

### ISSUE THREAD

**Issue by JoakimJohesan** [dotnet/runtime#79610]
Hi, our .NET6 API's are integrating towards several SOAP services that use Apache Http Server. The Apache server is setup with a directive of MaxKeepAliveRequests set to 800, which is causing our .NET 6 APIs connections to suddenly drop whenever a connection exceeds the request limit. At the moment we simply retry the request, which works most of the time. However there are some requests that should not be retried because of poor idempotency control on the receiving end that may cause issues. 

Adjusting the limit on the Apache Http Service does not seem like an option due to fear of sticky connections that never drop limiting the posibility of changing underlying services and DNS changes.

My understanding of connection lifetimes on .NET and the connection pool is that it is mostly handled by the .NET code, and that connections can live for a long time.

I have tried without luck at finding a similar setting in .NETs [SocketsHttpHandler](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler?view=net-6.0), and was wondering if this maybe should be added, or if there is an easy workaround to make sure that a connection never exceeds a set amount of requests?

As I see it, we could maybe implement aggressive keep-alive timeout and connection pool settings to mitigate the issue, but we wish to implement a workaround that should not fail.

Would be happy to hear of any suggestions, and can provide more detailed information if needed. Thanks!

Relevant links:
- Apache documentation: https://httpd.apache.org/docs/2.4/mod/core.html#maxkeepaliverequests
- Related issue? https://github.com/dotnet/aspnetcore/issues/28428

Actual Apache settings:

```
# Timeout: The number of seconds before receives and sends time out.
Timeout 60

# KeepAlive: Whether or not to allow persistent connections (more than one request per connection). Set to "Off" to deactivate.
KeepAlive On

# MaxKeepAliveRequests: The maximum number of requests to allow during a persistent connection. Set to 0 to allow an unlimited amount. We recommend you leave this number high, for maximum performance.
MaxKeepAliveRequests 800

# KeepAliveTimeout: Number of seconds to wait for the next request from the same client on the same connection.
KeepAliveTimeout 15
```

**Comment by wfurt** [comment]
Can you try it with 7.0 to pick up https://github.com/dotnet/runtime/pull/73585
And what exact .NET version do you use? There were some fixes in 6.0.9 with https://github.com/dotnet/runtime/pull/73245

cc: @MihaZupan

**Comment by MihaZupan** [comment]
Would you be able to collect a network capture between the client and the server?

**Comment by JoakimJohesan** [comment]
We have captures, but I am quite wary of sharing them as they might contain sensitive data. I think a reproduction of the issue should be quite easy to create, but at the moment I cannot prioritize it. 

Will provide some screenshots of some captures, they might be helpful? 
Client side: (This will contain some noise, but communication should be clear enough)
![ClientCapture](https://user-images.githubusercontent.com/69187232/207824250-ae416a17-2019-4f3f-aad1-4f4b8c6ad713.png)
Lab reproduction of server side :
<img width="1272" alt="labCapture" src="https://user-images.githubusercontent.com/69187232/207824254-ae4f5f42-9116-4860-9411-7f08c14351ec.png">

**Comment by MihaZupan** [comment]
On the last successful server response, what did the headers look like - specifically the value of `Keep-Alive`?

**Comment by JoakimJohesan** [comment]
I have not actually fetched the headers for the last successfull response, but just took some from a regular response. I do not believe that they change.

```

```

**Comment by JoakimJohesan** [comment]
Can confirm that the server does not send any Connection or Keep-Alive headers before terminating the connection.

**Comment by MihaZupan** [comment]
Well, that's pretty horrible server behavior. It has two mechanisms it could use to inform us that a connection is no longer usable (`Keep-Alive` or `Connection: close`) and it does neither. This means there is no way for us to react well to that.

First of all, if you know the server's `KeepAliveTimeout`, you should set `SocketsHttpHandler.PooledConnectionIdleTimeout` to something lower (e.g. 1 second less).

To avoid hitting the `MaxKeepAliveRequests` limit, you have a few options:
1. Configure the server differently
    - If possible, configure the server to send a `Connection: close` or `Keep-Alive max=0` header
1. Avoid using `MaxKeepAliveRequests`
    - > Adjusting the limit on the Apache Http Service does not seem like an option due to fear of sticky connections that never drop limiting the posibility of changing underlying services and DNS changes
    - You can set `SocketsHttpHandler.PooledConnectionLifetime` instead to limit the amount of time a connection will be in use.
1. Stick a reverse proxy in front of Apache to better communicate things like when a connection will be closed
1. Disable connection re-use on the HttpClient
    - You can do so by not reusing the client, or by setting `PooledConnectionLifetime` to 0.
    - This will likely result in noticeable performance degradation
1. Set an aggressive `PooledConnectionLifetime`
    - E.g. if you know that the server has a limit of 1000 requests per connection and you know approximately what your latency is, you could change `PooledConnectionLifetime` to 5/10 seconds, which would make it unlikely for you to hit the limit.
1. Manually rotate HttpClient instances
    - There's no setting on HttpClient to tell it to "only use this connection for X requests", but you can emulate that by writing something horrible like [this](https://gist.github.com/MihaZupan/f141a6bf6f5152a2dcf887940922736c)

**Comment by MihaZupan** [comment]
Can you also share what the headers looked like for a request other than the last one?
It could be that apache sends `Connection: keep-alive` on all requests except the last but we ignore it.

**Comment by JoakimJohesan** [comment]
The only headers that are sent are the ones i posted above. I have contacted our supplier to see if they can change the server. Will try each point in your suggestions by turn if they refuse.

**Comment by MihaZupan** [comment]
As per https://github.com/dotnet/runtime/issues/79610#issuecomment-1369831996, I don't believe we can do something differently in HttpClient in this situation if the server doesn't use any of the mechanisms to warn us.
We're also unlikely to add a built-in option to limit the number of requests a connection can be used for as that is an odd way to limit the lifetime of a connection (total time / timeout-based approaches tend to behave more nicely).

Feel free to reopen this issue if you believe there's still something missing / something we can do to improve this situation.
