### ISSUE TITLE
[NativeAOT] SIGABRT Crash in System.Security.Cryptography.OpenSsl.Tests

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#79619]
Saw the failure in:
https://github.com/dotnet/runtime/pull/79519 and
https://github.com/dotnet/runtime/pull/79578 
https://github.com/dotnet/runtime/pull/79591  

The #79591 is a noop PR with no code changes.

https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-79591-merge-93e036f2375b4c6a89/System.Security.Cryptography.OpenSsl.Tests/1/console.644fc1d2.log?helixlogtype=result

```
Console log: 'System.Security.Cryptography.OpenSsl.Tests' from job 93e036f2-375b-4c6a-89fc-e74d1c387fdb workitem bbb0e44d-9920-4fe8-8aff-4747c271be55 (osx.1200.arm64.open) executed on machine dci-macm1-build-071.local running macOS-12.4
+ ./RunTests.sh --runtime-path /tmp/helix/working/AA1309B6/p
----- start Tue Dec 13 09:49:41 PST 2022 =============== To repro directly: =====================================================
pushd .
chmod +rwx System.Security.Cryptography.OpenSsl.Tests ^&^& ./System.Security.Cryptography.OpenSsl.Tests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -xml testResults.xml 
popd
===========================================================================================================
/private/tmp/helix/working/AA1309B6/w/B77E09B0/e /private/tmp/helix/working/AA1309B6/w/B77E09B0/e
Running assembly:System.Security.Cryptography.OpenSsl.Tests, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
No usable version of libssl was found
./RunTests.sh: line 168:  8794 Abort trap: 6           ./System.Security.Cryptography.OpenSsl.Tests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -xml testResults.xml $RSP_FILE
/private/tmp/helix/working/AA1309B6/w/B77E09B0/e
----- end Tue Dec 13 09:49:41 PST 2022 ----- exit code 134 ----------------------------------------------------------
exit code 134 means SIGABRT Abort. Managed or native assert, or runtime check such as heap corruption, caused call to abort(). Core dumped.
ulimit -c value: 0
+ export _commandExitCode=134
+ _commandExitCode=134
+ /usr/local/bin/python3 /tmp/helix/working/AA1309B6/p/reporter/run.py https://dev.azure.com/dnceng-public/ public 2363448 eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im9PdmN6NU1fN3AtSGpJS2xGWHo5M3VfVjBabyJ9.eyJuYW1laWQiOiJjNzczZjJjMi01MTIwLTQyMDctYWZlMi1hZmFmMzVhOGJjMGEiLCJzY3AiOiJhcHBfdG9rZW4iLCJhdWkiOiJmYTc2NmVlZS0yOWU0LTQxZWUtODU3ZS1iMDk4NWIxMWU5OWMiLCJzaWQiOiJmZmE0MmNlYy0zMGVkLTQxNTItOTUxMy1jMmNlYTg1ODc2ZTAiLCJCdWlsZElkIjoiY2JiMTgyNjEtYzQ4Zi00YWJiLTg2NTEtOGNkY2I1NDc0NjQ5OzExMDg4MSIsInBwaWQiOiJ2c3RmczovLy9CdWlsZC9CdWlsZC8xMTA4ODEiLCJvcmNoaWQiOiJkYWMzNjg1MC00YzYwLTQ0YjYtYmFjYi0wZTkxMDMwMmIwZTguYnVpbGQuYnVpbGRfb3N4X2FybTY0X3JlbGVhc2VfbmF0aXZlYW90X2xpYnMuX19kZWZhdWx0IiwicmVwb0lkcyI6IiIsImlzcyI6ImFwcC52c3Rva2VuLnZpc3VhbHN0dWRpby5jb20iLCJhdWQiOiJhcHAudnN0b2tlbi52aXN1YWxzdHVkaW8uY29tfHZzbzo2ZmNjOTJlNS03M2E3LTRmODgtOGQxMy1kOTA0NWI0NWZiMjciLCJuYmYiOjE2NzA5NDI2ODksImV4cCI6MTY3MDk2MTg4OX0.umAFGZgYtMvdHur2NenYbiWJ50taOIBQzmHmUbM5qtR9h0aVTrdiRb8zHDvZJancchWreA-e2w-k58KPpL9QNVSQLW8nFvKwsiGXGGIeAcqv8Ae_QUoAF8cf1tCsHPhC2tNdJuneBuSyYeZqE361GMFTFmND_nzunk_TqEgRYYP94RbK69MKJP9mB8t6ypD3quewXWiZLIgVRI_-Yy7PF0P3wIw8MTYa3mTOehMVyrZo7eMouB420DusNdOdEo8z0e7_5d4Mm-UPW4z-MtBQG-z2B5v6PpyUoxCN3lw2VAFYmRVLqEQvGsD7Oj3S9ShNh0RxkPrc9aR-u7DS2KtrCg
2022-12-13T17:49:41.797Z	INFO   	run.py	run(48)	main	Beginning reading of test results.
2022-12-13T17:49:41.798Z	INFO   	run.py	__init__(42)	read_results	Searching '/private/tmp/helix/working/AA1309B6/w/B77E09B0/e' for test results files
2022-12-13T17:49:41.798Z	INFO   	run.py	__init__(42)	read_results	Searching '/tmp/helix/working/AA1309B6/w/B77E09B0/uploads' for test results files
2022-12-13T17:49:41.798Z	WARNING	run.py	__init__(55)	read_results	No results file found in any of the following formats: xunit, junit, trx
2022-12-13T17:49:41.798Z	INFO   	run.py	packing_test_reporter(30)	report_results	Packing 0 test reports to '/tmp/helix/working/AA1309B6/w/B77E09B0/e/__test_report.json'
2022-12-13T17:49:41.799Z	INFO   	run.py	packing_test_reporter(33)	report_results	Packed 1424 bytes
+ /usr/local/bin/python3 /tmp/helix/working/AA1309B6/p/gen-debug-dump-docs.py -buildid 110881 -workitem System.Security.Cryptography.OpenSsl.Tests -jobid 93e036f2-375b-4c6a-89fc-e74d1c387fdb -outdir /tmp/helix/working/AA1309B6/w/B77E09B0/uploads -templatedir /tmp/helix/working/AA1309B6/p -dumpdir /cores -productver 8.0.0
Did not find dumps, skipping dump docs generation.
+ exit 134
['System.Security.Cryptography.OpenSsl.Tests' END OF WORK ITEM LOG: Command exited with 134]
```

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section).

```json
{
  "ErrorMessage": "No usable version of libssl was found",
  "BuildRetry": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[110530](https://dev.azure.com/dnceng-public/public/_build/results?buildId=110530)|dotnet/runtime|[System.Security.Cryptography.OpenSsl.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=110530&view=ms.vss-test-web.build-test-results-tab&runId=2364022&resultId=169889)|dotnet/runtime#79519|
|[110881](https://dev.azure.com/dnceng-public/public/_build/results?buildId=110881)|dotnet/runtime|[System.Security.Cryptography.OpenSsl.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=110881&view=ms.vss-test-web.build-test-results-tab&runId=2363448&resultId=169890)|dotnet/runtime#79591|
|[110537](https://dev.azure.com/dnceng-public/public/_build/results?buildId=110537)|dotnet/runtime|[System.Security.Cryptography.OpenSsl.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=110537&view=ms.vss-test-web.build-test-results-tab&runId=2353912&resultId=169889)||
|[110316](https://dev.azure.com/dnceng-public/public/_build/results?buildId=110316)|dotnet/runtime|[System.Security.Cryptography.OpenSsl.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=110316&view=ms.vss-test-web.build-test-results-tab&runId=2350144&resultId=169889)|dotnet/runtime#79578|
|[109880](https://dev.azure.com/dnceng-public/public/_build/results?buildId=109880)|dotnet/runtime|[System.Security.Cryptography.OpenSsl.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=109880&view=ms.vss-test-web.build-test-results-tab&runId=2346492&resultId=169888)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|5|

**Comment by vcsjones** [comment]
> No usable version of libssl was found

It seems like an infrastructure issue where some runs are using machines that don't have a proper version of OpenSSL on them.

This seems like a recurrence of https://github.com/dotnet/runtime/issues/73210 at first glance.

**Comment by vcsjones** [comment]
@MattGal since you helped us with the previous issue... is it possible we have another macOS machine in the pool that does not have OpenSSL?

**Comment by MattGal** [comment]
> @MattGal since you helped us with the previous issue... is it possible we have another macOS machine in the pool that does not have OpenSSL?

I'm taking a look and will let you know what I find.  Nothing interesting should have changed w/ the test macs recently.

**Comment by MattGal** [comment]
@VSadov checking it out there's definitely a pattern of this happening on osx.1200.amd64.open & osx.1200.arm64.open, I opened https://github.com/dotnet/arcade/issues/11943 and will try to figure out what broke today.

**Comment by MattGal** [comment]
@VSadov I'll put notes in the other issue, but the machines in that queue have not been reimaged or changed recently in any way, and the libraries we'd expect there from the previous issue are all there:
![image](https://user-images.githubusercontent.com/7862010/207441834-1530bc84-6cda-462a-a8fb-0469691a6dab.png)
Can you help clarify what version of OpenSSL is expected? (i.e. what broke?)

**Comment by VSadov** [comment]
I am not an expert in these tests or what OpenSSL does, I just did a test run and saw the failure and then I saw this failure in other runs. I think the environment expectations would not be different from a regular (not NativeAOT) case. 

It also, in theory, should use the same native PAL libraries, linked into the executable.
Infrastructure/install issue could be an easy explanation, but if it is not that, it is hard to tell what could be causing this.

**Comment by vcsjones** [comment]
@MattGal is there a `libssl1.1.dylib` as well, in the same directory?

**Comment by vcsjones** [comment]
Is it _only_ happening on NativeAOT runs? Are non-nativeAOT runs passing on these machines, or failing, too?

**Comment by VSadov** [comment]
As I look at https://github.com/dotnet/runtime/pull/79591 I see only NativeAOT and couple Mono legs having failures and Mono failures seem unrelated (somehting with System.Text.Json.Tests)

So I guess CoreCLR counterparts for these tests are passing. They could be running on different machine, but I do not know if that matters.

**Comment by filipnavara** [comment]
I am pretty sure these tests were not really running on NativeAOT until relatively recently. I fixed the OpenSSL native interop linkage somewhere along the macOS bring-up but I don't think these tests were enabled even after that, and they were definitely marked to be skipped at some point.

**Comment by MattGal** [comment]
@VSadov I think I found it. Specifically, it was fallout from https://github.com/dotnet/arcade/issues/11631 , "llvm-symbolizer not present in base queue".  

Addressing that made DDFUN run brew update, which moved them from having OpenSSL 1.1.1k to 1.1.1s without fixing those links.  While the links exist, they didn't actually go to the files they should.  

I've fixed this up on osx.1200.arm64.open and will keep an eye on it until the tests pass again.

**Comment by VSadov** [comment]
@MattGal - do we need to rerun failed test in https://github.com/dotnet/runtime/pull/79591, or you have other ways to check the fix?

**Comment by MattGal** [comment]
@VSadov I have my ways... I'll keep https://github.com/dotnet/arcade/issues/11943 open until I see it working either way.

**Comment by MattGal** [comment]
@VSadov I think it's fixed, feel free to reopen the linked arcade issue if(when) it comes back.

**Comment by jkotas** [comment]
No hits in last 7 days
