### ISSUE TITLE
Assertion failed 'dest->TypeGet() == src->TypeGet()' in 'Vector2_3_4Test:RunVector2Tests()'

### ISSUE THREAD

**Issue by BrianBohe** [dotnet/runtime#79626]
### Description

Hitting this assert on [runtime-coreclr jitstress-random](https://dev.azure.com/dnceng-public/public/_build?definitionId=159&_a=summary).

```
Interop/PInvoke/Vector2_3_4/Vector2_3_4/Vector2_3_4.sh [FAIL]
      
      Assert failure(PID 20030 [0x00004e3e], Thread: 238788 [0x3a4c4]): Assertion failed 'dest->TypeGet() == src->TypeGet()' in 'Vector2_3_4Test:RunVector2Tests()' during 'Morph - Global' (IL size 348; hash 0xcf5ce7a3; FullOpts)
      
          File: /Users/runner/work/1/s/src/coreclr/jit/importer.cpp Line: 936
          Image: /private/tmp/helix/working/9CCE08C8/p/corerun
      
      [createdump] Invalid process id: task_for_pid(20030) FAILED (os/kern) failure (5)
      [createdump] This failure may be because createdump or the application is not properly signed and entitled.
      [createdump] Failure took 0ms
      [createdump] waitpid() returned successfully (wstatus 0000ff00)
      /private/tmp/helix/working/9CCE08C8/w/B666097B/e/Interop/PInvoke/Vector2_3_4/Vector2_3_4/Vector2_3_4.sh: line 426: 20030 Abort trap: 6           (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
```
[Full log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-34661d032f254594a1/Interop/1/console.0865fbd3.log?helixlogtype=result)

### Reproduction Steps

Flags on logs:
DOTNET_TieredCompilation=0
DOTNET_DbgEnableMiniDump=1
DOTNET_DbgMiniDumpName=$HELIX_DUMP_FOLDER/coredump.%d.dmp
DOTNET_JitStress=1df

The command on log:
dotnet /tmp/helix/working/9CCE08C8/p/xunit/xunit.console.dll Interop/DllImportAttribute/Interop.DllImportAttribute.XUnitWrapper.dll Interop/FuncPtrAsDelegateParam/Interop.FuncPtrAsDelegateParam.XUnitWrapper.dll Interop/StructPacking/Interop.StructPacking.XUnitWrapper.dll Interop/PInvoke/Interop.PInvoke.XUnitWrapper.dll Interop/ICustomMarshaler/Interop.ICustomMarshaler.XUnitWrapper.dll Interop/UnmanagedCallConv/Interop.UnmanagedCallConv.XUnitWrapper.dll Interop/SimpleStruct/Interop.SimpleStruct.XUnitWrapper.dll Interop/RefCharArray/Interop.RefCharArray.XUnitWrapper.dll Interop/IDynamicInterfaceCastable/Interop.IDynamicInterfaceCastable.XUnitWrapper.dll Interop/SuppressGCTransition/Interop.SuppressGCTransition.XUnitWrapper.dll Interop/UnmanagedCallersOnlyBasic/Interop.UnmanagedCallersOnlyBasic.XUnitWrapper.dll Interop/ICastable/Interop.ICastable.XUnitWrapper.dll Interop/BestFitMapping/Interop.BestFitMapping.XUnitWrapper.dll Interop/StringMarshalling/Interop.StringMarshalling.XUnitWrapper.dll Interop/MonoAPI/Interop.MonoAPI.XUnitWrapper.dll Interop/DisabledRuntimeMarshalling/Interop.DisabledRuntimeMarshalling.XUnitWrapper.dll Interop/PrimitiveMarshalling/Interop.PrimitiveMarshalling.XUnitWrapper.dll Interop/MarshalAPI/Interop.MarshalAPI.XUnitWrapper.dll Interop/ArrayMarshalling/Interop.ArrayMarshalling.XUnitWrapper.dll Interop/NativeLibrary/Interop.NativeLibrary.XUnitWrapper.dll Interop/LayoutClass/Interop.LayoutClass.XUnitWrapper.dll Interop/COM/Interop.COM.XUnitWrapper.dll Interop/UnmanagedCallersOnly/Interop.UnmanagedCallersOnly.XUnitWrapper.dll Interop/StructMarshalling/Interop.StructMarshalling.XUnitWrapper.dll Interop/ObjectiveC/Interop.ObjectiveC.XUnitWrapper.dll -parallel collections -nocolor -noshadow -xml testResults.xml

### Expected behavior

To not assert

### Actual behavior

Assertion

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib -- random jitstress failure

**Comment by JulieLeeMSFT** [comment]
Assigned to @EgorBo for assert in Global Morph.
