### ISSUE TITLE
Unnecessary assertion "jit\importer.cpp"

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#79625]
In [Make System.Reflection.Emit public types abstract](https://github.com/dotnet/runtime/pull/78544) PR assertion failures found in [class attributes check](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-78544-merge-afe7a0e8af164ccf8c/System.Runtime.Tests/1/console.a7ebb10b.log?helixlogtype=result)
Log:
```log
Assert failure(PID 2368 [0x00000940], Thread: 1028 [0x0404]): Assertion failed '(info.compCompHnd->getClassAttribs(likelyCls) & (CORINFO_FLG_INTERFACE | CORINFO_FLG_ABSTRACT)) == 0' in 'System.Reflection.Emit.ILGenerator:Emit(System.Reflection.Emit.OpCode,System.String):this' during 'Importation' (IL size 47; hash 0x9d444ce1; Tier1)

    File: D:\a\_work\1\s\src\coreclr\jit\importer.cpp Line: 5847
    Image: C:\h\w\C57C0A0C\p\dotnet.exe
```
@jakobbotsch confirmed it is a JIT bug

**Comment by jakobbotsch** [comment]
cc @EgorBo, we should be robust to stale PGO data here. The PR is updating a class to be abstract and it hits this JIT assert when trying to use cast PGO data as a result. Can you take a look?
