### ISSUE TITLE
Should MemoryExtensions.Trim use IndexOfAnyExcept?

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#79621]
Haven't measured, however the internal methods `ClampStart` and `ClampEnd` serve similar purposes but don't have vectorised paths?

https://github.com/dotnet/runtime/blob/d8e1ec686e8336b8e17288a0f1d3ebac1ce082d5/src/libraries/System.Private.CoreLib/src/System/MemoryExtensions.Trim.cs#L129-L155 

Should thing be slower if usually not trimming or only trimming 1 element?

**Comment by stephentoub** [comment]
We've talked about trimming in the past, and the expectation is that in the vast majority case the number of things that gets trimmed is 0 or maybe 1, in which case the overhead of using the vectorized routine isn't worth it.  As such we've explicitly not used IndexOfAnyExcept in trimming routines.

**Comment by dakersnar** [comment]
Given Stephen's comments, I'm going to close this as not planned.
