### ISSUE TITLE
System.IO.Compression.ZipArchiveEntry Open method sometimes throws InvalidDataException in ZIP files over 4.2GB

### ISSUE THREAD

**Issue by damon-mythical** [dotnet/runtime#79628]
### Description

Opening a ZipArchiveEntry will sometimes throw the exception "System.IO.InvalidDataException: A local file header is corrupt," if the ZIP file is larger than 4.2GB. This seems to effect entries in large zip files that have an offset greater than the max value of uint32. 

### Reproduction Steps

1. Create a ZIP file that exceeds 4.2G and contains multiple entries.
2. Verify the last entry has the Zip64 Characteristic in 7-Zip.
3. Open the file using System.IO.Compresion.ZipFile.
4. Open the last entry.

Example:
```
var filePath = "<ZIP PATH>";
using var archive = System.IO.Compression.ZipFile.OpenRead(filePath);
using (var foo = archive.Entries[archive.Entries.Count - 1].Open()) 
{
  // Code to read the stream
}
```

### Expected behavior

A Stream representing the uncompressed data is returned.

### Actual behavior

The exception "System.IO.InvalidDataException: A local file header is corrupt." is thrown.

### Regression?

The same code works in .NET 6 and .NET 5.

### Configuration

.NET 7 
Windows 10.0.19045 Build 19045
x64

I do not know if the issue is specific to this configuration. A third party we work with was experiencing the same issue with a Team City runner.

### Other information

Stepping through the debugger it appears the _localHeaderOffset used in ZipBlocks.cs is being calculated differently in .NET 6 vs .NET 7 which is causing to .NET 7 to examine the wrong bytes when checking the header.

**Comment by smasher164** [comment]
@damon-mythical Is it possible for you to share the ZIP file with us? Do you know what tool created it?
