### ISSUE TITLE
Consider getting rid of DumpNativeResources task

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#79634]
This task extracts native resources from the input assembly and puts them into a res file. We then pass the res file to the linker.

Looks like linker then runs cvtres to convert it to an object file. We could just dump the resources into the object file the AOT compiler is generating and get rid of the step.

Motivated by a report of:

```
CVTRES : fatal error CVT1103: cannot read file [REDACTED.csproj]
LINK : fatal error LNK1123: failure during conversion to COFF: file invalid or corrupt [REDACTED.csproj]
C:\Program Files\dotnet\sdk\7.0.101\Sdks\Microsoft.DotNet.ILCompiler\build\Microsoft.NETCore.Native.targets(350,5): err
or MSB3073: The command ""C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\bin\Hostx6
4\x64\link.exe" @"obj\Release\net7.0\win-x64\native\link.rsp"" exited with code 1123. [REDACTED.csproj]
```

**Comment by jkotas** [comment]
> LNK1123: failure during conversion to COFF: file invalid or corrupt

https://github.com/dotnet/runtimelab/issues/1436
https://github.com/dotnet/runtime/issues/86493
