### ISSUE TITLE
Expired Helix queue windows.10.amd64.client21h1.open failing 6.0 CI run

### ISSUE THREAD

**Issue by CarnaViire** [dotnet/runtime#79646]
Observed in https://github.com/dotnet/runtime/pull/79549 (backport to release/6.0)

Libraries Build windows net48 x86 Release
Error log:
`SENDHELIXJOB(0,0): error : Helix queue windows.10.amd64.client21h1.open was set for estimated removal date of 2022-12-13. In most cases the queue will be removed permanently due to end-of-life; please contact dnceng for any questions or concerns, and we can help you decide how to proceed and discuss other options.`

Similar errors due to expired queues happened before in https://github.com/dotnet/runtime/issues/67048

**Comment by ViktorHofer** [comment]
Looks like we also use that queue in main: https://github.com/dotnet/runtime/blob/8e15d9f523209caf08db57897777b7beb0516c99/eng/pipelines/libraries/helix-queues-setup.yml#L180

@CarnaViire do you want to submit PRs targeting 6.0, 7.0 and main to fix that?

**Comment by CarnaViire** [comment]
@ViktorHofer it is stated there as the only machine for `net48` builds. Is there something it should be changed to?
Also, I wonder why I don't see similar failures in main and 7.0 CI 🤔 is `net48` only running for 6.0 branch?

(While I can attempt to submit the fix, I will be OOF starting this Friday, so I might not be the best person to do that)

**Comment by ViktorHofer** [comment]
That message also appears in main and release/7.0 but it was downgraded to not fail the build: https://dnceng-public.visualstudio.com/public/_build/results?buildId=111851&view=logs&j=4260d0c6-5941-59c0-51d5-62bf49c37870&t=691348e9-db6c-5b8a-8ed1-66f42a3b255d&l=46

@dotnet/dnceng to which Windows Client version should we upgrade to, away from `windows.10.amd64.client21h1.open`?

**Comment by MattGal** [comment]
> https://github.com/orgs/dotnet/teams/dnceng to which Windows Client version should we upgrade to, away from windows.10.amd64.client21h1.open?

There are now `windows.10.amd64.client.open` and `windows.10.amd64.client`, which should not expire til the end of life of Windows 10.

As a side note, to not break the build, I'd suggest setting "TreatWarningsAsErrors" as false in the "Send to Helix" stages of your build.  Due to no more rollouts this year, the queue won't actually be fully removed until around 1/11/2023 which would make addressing this less urgent.

Feel free to ping me directly on Teams for any questions.

**Comment by akoeplinger** [comment]
This was fixed by https://github.com/dotnet/runtime/pull/79665
