### ISSUE TITLE
[API Proposal]: FileSharingViolationException

### ISSUE THREAD

**Issue by zivkan** [dotnet/runtime#79643]
### Background and motivation

Apps that use file locking for cross process synchronization, or apps that use FileSystemWatcher, may try to open files and get `IOException` with exception message something like "The process cannot access the file '/home/zivkan/src/shareTest/test.file' because it is being used by another process.". When the file is locked, the app may want to retry after a delay.

However, `IOException` is also thrown in other scenarios, like device failures, and that's before we consider that some common exception types, like `FileNotFoundException` and `UnauthorizedAccessException`, extend `IOException` which makes `catch (IOException ioex)` catch a lot more than what's desired.

Trying to filter specifically on file share violation exceptions is impossible by parsing `exception.Message` since the message can be localized. I can't determine if `Exception.HResult` is guaranteed not to change (without breaking change notice) across different versions of .NET.  However, in any case `Exception.HResult` is different across different operating systems, which makes it difficult for app developers to write cross-platform code.

On Windows, [`Win32Marshal.GetExceptionForWin32Error`](https://github.com/dotnet/runtime/blob/6364f1569b719a2adddfb8aedb2e8ae2ce916722/src/libraries/Common/src/System/IO/Win32Marshal.cs#L25) already has a mapping of win32 errors to exception types, which is how `FileNotFoundException`, `UnauthorizedAccessException`, `PathTooLongException` get their specific exceptions, but there's a few that return a new `IOException`.

On Unix, it appears that [`Interop.IOErrors.GetExceptionForErrno`](https://github.com/dotnet/runtime/blob/6364f1569b719a2adddfb8aedb2e8ae2ce916722/src/libraries/Common/src/Interop/Unix/Interop.IOErrors.cs#L114) is the equivalent.

Basically, I think that "file is in use" exceptions are be treated as "common" and have easily catchable specific exception types, like file not found and permission exceptions.

### API Proposal

```csharp
namespace System.IO;

public class FileSharingViolationException : IOException
{
    public FileSharingViolationException(string message, int hResult)
      : base(message)
    {
      HResult = hResult;
    }
}
```

I don't care about the exact name. I chose `FileSharingViolationException` because the string that contains the exception message is `SR.IO_SharingViolation_File`, but I thought that `SharingViolationException` might sound a bit too generic, but maybe there are non-file scenarios where GetLastError() returns 20 on Windows, in which case dropping the `File` from the name probably makes a lot of sense.

### API Usage

```csharp
while (true)
{
    int retryCount = 0;
    try
    {
        // does not retry when file not found, permission error, disk/network failure, etc.
        return new FileStream(fileName, FileMode.Open, FileAccess.Read, FileShare.None);
    }
    catch (FileSharingViolationException ex) when (retryCount < 5)
    {
        // Something else has the file open, so we will retry up to 5 times
        retryCount++;
        Thread.Sleep(100 * retryCount);
    }
}
```

### Alternative Designs

Not exactly an alternate design, customers can currently implement something similar with

```cs
catch (IOException ex) when ( (Runtime.IsWindows() && ex.HResult == 0x80070020) || (ex.HResult == 11) )
```

However, the magic numbers `0x80070020` and `11` are non-trivial to find and feel arbitrary, needing "low level" operating system API knowledge to explain why those are the correct values. And I have no idea if this actually works for all operating systems, or just the ones I've tried so far (maybe BSD returns a different value? What's a less commonly used operating system that has community support, even if Microsoft doesn't directly support .NET on that platform?), or if it'll change in the future.

The point is that `catch (FileSharingViolationException)` is very clear and even inexperienced developers can be confident that it should work as expected. The IOException exception filter is not clear that it's actually correct (and honestly, I'm not sure that it is).

### Risks

Code that does something like `ex.GetType() == typeof(IOException)` will break, but hopefully almost everyone is using `catch (IOException)` instead, which will keep working. I'm not proposing to change the message or the HResult value, so existing exception filters should also keep working.

**Comment by Tornhoof** [comment]
You might want to read  #926, your proposal is a part of that.
