### ISSUE TITLE
[Convert.FromHexString] The input is not a valid hex string as it contains a non-hex character.

### ISSUE THREAD

**Issue by JKamsker** [dotnet/runtime#79649]
### Description

``Convert.FromHexString`` only supports input with the format of``abff``, but its also common to see values such as ``0xabff``.  It would be great if this would be caught.

### Reproduction Steps

Convert.FromHexString("0xff")

### Expected behavior

return ``byte[]{0xff}``

### Actual behavior

FormatException
--
The input is not a valid hex string as it contains a non-hex character.

### Known Workarounds

Checking the input yourself before passing it to the method.

### Configuration

.NET 7 / LinqPad

**Comment by dakersnar** [comment]
This is a reasonable suggestion, but it would likely need to be a brand-new API, as changing the behavior of the existing API would be a breaking change.
