### ISSUE TITLE
Backward binary compatibility

### ISSUE THREAD

**Issue by gulshan** [dotnet/runtime#79650]
Currently, to the best of my knowledge, recompilation is required to run a binary/assembly on a newer .NET runtime.

Will it be possible to compile an assembly targeting "some .NET version or later" (e.g. .NET6 or later) and keep running the binary on any future runtimes, unless there is an explicit breaking change?

**Comment by vitek-karas** [comment]
Yes - you can run .NET 6 app on .NET 7 runtime. It's disabled by default though.
This is called roll-forward policy. https://learn.microsoft.com/en-us/dotnet/core/versions/selection#framework-dependent-apps-roll-forward

In short, the default is to roll forward over minor version only - so 6.0 app can run on 6.1, but not on 7.0.
If you set roll forward to Major it will allow rolling forward over major versions as well - so that 6.0 app can run on 7.0 runtime.

**Comment by jkotas** [comment]
> unless there is an explicit breaking change

Note that every major .NET version comes with a number of breaking changes: https://learn.microsoft.com/en-us/dotnet/core/compatibility/. If you enable the roll forward policy, your app will be exposed and potentially broken by these breaking changes. We recommend running the app on the runtime that was tested on.  It is why we the roll-forward policy is disabled by default.

**Comment by rickbrew** [comment]
Paint.NET 5.0 running on .NET 7 is able to load and execute DLL plugins that were compiled all the way back in 2005 for .NET 2.0. There are some caveats -- mostly due to some documented breaking changes and functionality removed from Windows Forms -- but binary compatibility is 100%.

**Comment by gulshan** [comment]
As .NET core has matured enough, can this roll-forward policy be enabled by default for major versions also? This will decouple deployment and develop scenarios and simplify the deployment in the environments where developers do not have much control.

For example, we have a little winforms app, which is in maintenance mode. It is still targeting .NET framework. If we want to target .NET core runtimes, the install requirements get quite complicated for us and users to maintain. Making decision to put roll-forward policy manually seems another option. But I think company will rather keep targeting .NET framework.

Another point is, .NET Major versioning is not based on breaking changes, but on annual schedule. It is not easy to know if there are actual breaking changes in a new major version. Or if there will be breaking changes in a future major version. This also makes it difficult to decide on manual roll-forward policy.

**Comment by jkotas** [comment]
> If we want to target .NET core runtimes, the install requirements get quite complicated

Self-contained deployment is often used to side-step the complicated install requirements for client apps.

**Comment by gulshan** [comment]
>It is safe to assume that every .NET Core major version contains some breaking changes.

It seems the "Backward binary compatibility" is somewhat there but not guaranteed and cannot be relied upon. That's why this will be a somewhat new feature, I guess.

>It would force us to maintain bug-for-bug compatibility and stifle innovation.

I am not requesting to maintain bug-for-bug compatibility forever. But guaranteed backward binary compatibility for at least 5-6 years will be very helpful for the developers/users (at least a certain portion of them). And maintaining this binary compatibility will get increasingly easier with each .NET version releases, I guess.

**Comment by jkotas** [comment]
> But guaranteed backward binary compatibility for at least 5-6 years will be very helpful for the developers/users

[LTS releases](https://dotnet.microsoft.com/en-us/platform/support/policy) maintain guaranteed backward binary compatibility for 3 years today. You are basically asking to extend support for LTS releases to 5-6 years.

> And maintaining this binary compatibility will get increasingly easier with each .NET version releases, I guess.

That's not correct assumption for major versions. We do not believe that it is possible to add new interesting features and maintain guaranteed compatibility at the same time.

**Comment by Suchiman** [comment]
> The binary size of our current app targeting .NET framework is <1MB (it is indeed a small utility program). Self-contained deployments will take it to around 50 or 100MB I guess.

You might want to have a look at trimming and also NativeAOT (which does trimming as well implicitly), those could cut down the size significantly.
