### ISSUE TITLE
关于 HttpClient.PostAsync 使用JsonContent 时的问题

### ISSUE THREAD

**Issue by vrjure** [dotnet/runtime#79663]
最近在接入 Aria2 的jsonrpc
当我使用 JsonContent 时，返回` 500 (Internal Server Error)`，例如：
```c#
var content = JsonContent.Create(request, null, JsonOption.DefaultSerializer);
var result = await _client.PostAsync(_requestUri, content, cancellationToken);
```
奇怪的是,在Post之前读取content的内容后又会返回 `200`，例如：
```c#
var content = JsonContent.Create(request, null, JsonOption.DefaultSerializer);
await content.ReadAsStringAsync();
var result = await _client.PostAsync(_requestUri, content, cancellationToken);
```
我用Fiddler捕获了两次的内容， 失败的那次像是进行了编码：
500
![image](https://user-images.githubusercontent.com/24759389/207668917-2cc3df41-5c48-424b-859e-255efc919252.png)
200
![image](https://user-images.githubusercontent.com/24759389/207668384-b8159265-a6a6-4b94-99a0-b15e1aa1433a.png)

我不能理解！！！！

**Comment by wfurt** [comment]
It is not clear what your problem is @vrjure. However, the 500 error comes from server -> that typically means some code or resource problem there. It is possible you do not post correct info.

**Comment by vrjure** [comment]
Thank you.  it's aria2, a download tool. it provide JSON-RPC. Maybe it does not support chunk-encoded contents @MihaZupan 


> In the first example, we don't know what the length of the content is going to be upfront, so we use chunked encoding as we serialize the JSON on the fly.
> 
> In the second example, you buffered the whole content upfront, so we know the exact length. When we send it, we can just include the `Content-Length` header and copy the already-encoded data.
> 
> What server is this request going to? Is it possible that it does not support chunk-encoded contents?
