### ISSUE TITLE
PerformanceCounterCategory.ReadCategory is taking large memory allocation

### ISSUE THREAD

**Issue by oakcode** [dotnet/runtime#79660]
### Description

I am trying to create tool to read some of categories of performance counters but I faced one big problem where process memory constantly increasing.

This is my code:

```cs
private void CollectPerfCategories()
{
    perfCollectorTask = Task.Factory.StartNew(() =>
    {
        bool perfCatBrokenReported = false;

        PerformanceCounterCategory catThreads = new PerformanceCounterCategory(CAT_NET_CLR_LOCKS);
        PerformanceCounterCategory catProcess = new PerformanceCounterCategory(CAT_PROCESS);
        PerformanceCounterCategory catMemory = new PerformanceCounterCategory(CAT_NET_CLR_MEMORY);
        
        Stopwatch timer = new Stopwatch();

        while (isServiceActive)
        {
            timer.Restart();

            InstanceDataCollectionCollection categoryProcessData = null;
            try
            {
                categoryProcessData = catProcess.ReadCategory();
            }
            catch (Exception e)
            {
                    LOGGER.LogDebug("Error while reading Processes category of performance counters: " + e.Message + " | " + e.StackTrace);
            }
            
            InstanceDataCollectionCollection categoryThreadsData = null;
            try
            {
                categoryThreadsData = catThreads.ReadCategory();
            }
            catch (Exception e)
            {
                    LOGGER.LogDebug("Error while reading '.NET CLR LocksAndThreads' category of performance counters: " + e.Message + " | " + e.StackTrace);
            }

            InstanceDataCollectionCollection categoryClrData = null;
            try
            {
                categoryClrData = catMemory.ReadCategory();
            }
            catch (Exception e)
            {
                    LOGGER.LogDebug("Error while reading Memory category of performance counters: " + e.Message + " | " + e.StackTrace);
            }

            timer.Stop();
            int toSleep = 1000 - (timer.ElapsedMilliseconds >= 1000 ? 1000 : (int)timer.ElapsedMilliseconds);
            if (toSleep > 0)
                Thread.Sleep(toSleep);
        }
    },TaskCreationOptions.LongRunning);
}
```

### Configuration

It is .NET 4.5 running on Windows x64

### Regression?
No

### Data

How I can see almost complete memory is allocated by these to calls:
System.Diagnostics.CategorySample.ReadCategory()
System.Diagnostics.PerformanceCounterCategory.ReadCategory()
![image](https://user-images.githubusercontent.com/95284725/207663223-a7fa653e-70c0-4ef0-a3bf-18cde36aeddd.png)

### Analysis

I read many things about perf counters and memory allocations but still I do not know what is best practices.
Especially if we want to query data every second.

**Comment by ViktorHofer** [comment]
This is a .NET Framework issue, please report that to https://developercommunity.visualstudio.com/dotnet/report. We would be interested in knowing if this is still an issue on .NET 6+. Would you mind benchmarking your scenario on .NET 6/7/8?

**Comment by oakcode** [comment]
I need this for .NET Framework, I could not expect everybody has last version .NET installed.
Probably I can try to run it on .NET 6+ but only for testing purposes.

**Comment by carlossanlop** [comment]
@oakcode this repository does not ship the implementation of PerformanceCounter for .NET Framework. As mentioned, please file your request under https://developercommunity.visualstudio.com/dotnet/report .

If you notice this is an issue in .NET 5+, please feel free to open a new issue in this repo.
