### ISSUE TITLE
[API Proposal]: Add ability to safely get the managed object from a ComWrappers CCW

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/runtime#79674]
### Background and motivation

Using COM Interop it is a common pattern to cast incoming RCW's against internal instances. WinForms does this in a number of places. For example, we check incoming OLE control interfaces to see if they are our own hosting control and utilize fields/methods on the instance if it is.

Using `ComWrappers` this isn't possible to do safely without adding an additional interface to the outgoing CCW. It would be good to add functionality to `ComWrappers` to query for a wrapped managed object on any `IUnknown`.

Without a way for users to construct `ComWrappers` CCWs that we can attempt to unwrap when receiving from native methods they cannot enable trimming in their apps.

### API Proposal

```diff
namespace System.Runtime.InteropServices;

public abstract class ComWrappers
{
+    public static bool TryGetObject(void* unknown, out object? obj);
}
```

### API Usage

```csharp
public static MyCallbackApi(IUnknown* unknown)
{
   if (ComWrappers.TryGetObject(unknown, out object? myObject)
       && myObject is MyObject)
   {
        // Do stuff
   }
}
```

### Alternative Designs

We could potentially publish a new COM interface that we can have users implement in their `ComWrappers` CCWs that we can look for to know that it is ok to unwrap with `ComInterfaceDispatch.GetInstance`.

**Comment by JeremyKuhne** [comment]
cc: @lonitra, @AaronRobinsonMSFT, @jkoritzinsky, @LakshanF

**Comment by AaronRobinsonMSFT** [comment]
This should be done via your own `ComWrappers` implementation as opposed to relying upon it "magically" working. If we did this the API would need to throw if there wasn't a globally registered `ComWrappers` instance.

**Comment by AaronRobinsonMSFT** [comment]
> Using ComWrappers this isn't possible to do safely without adding an additional interface to the outgoing CCW. It would be good to add functionality to ComWrappers to query for a wrapped managed object on any IUnknown.

Which wrapper do you want? The `ComWrappers` mechanism is designed around a 1:N model - there are N potential CCWs, one for each `ComWrappers` implementation. It isn't possible to know which one is desired and would be incredibly expensive to create an API that permits this. Your implementation of `ComWrappers` should attempt to unwrap and if it can, it will, otherwise it is an native COM object and will be wrapped.

**Comment by AaronRobinsonMSFT** [comment]
Also see [`CreateObjectFlags.Unwrap`](https://learn.microsoft.com/dotnet/api/system.runtime.interopservices.createobjectflags), which will perform the unwrap for you instead of trying to inspect all this manually.

**Comment by AaronRobinsonMSFT** [comment]
Spoke to @JeremyKuhne offline. I get this scenario now. The implementation here is a going to be more complicated than https://github.com/dotnet/runtime/issues/79679, but is possible. In its simplest form, we can add a sentinel interface to the generated CCW and use that to return the associated `object` or perhaps the `GCHandle` that is embedded in the CCW.

**Comment by jkoritzinsky** [comment]
Another alternative implementation is to do the same sort of check we have the diagnostics layer do (it checks if the QueryInterface implementation for the `IUnknown*` is one of the runtime-implemented ones). That way we'd be consistent throughout the stack (since the OOP diagnostics can't QI for a sentinel interface)

**Comment by AaronRobinsonMSFT** [comment]
>That way we'd be consistent throughout the stack (since the OOP diagnostics can't QI for a sentinel interface)

The issue with this approach is that it breaks if user defined their own `IUnknown` methods. Having the diagnostic degrade is one thing but breaking core functionality is another. I'm not sure which is the best approach at the moment. My guess is we implement the QI first and see the performance cost.

**Comment by AaronRobinsonMSFT** [comment]
@JeremyKuhne Based on a private implementation here is what I would propose for the API along with details on use.

```csharp
/// <summary>
/// Given a COM object, determine if it is a ComWrappers created
/// unmanaged wrapper and if so, return the wrapped managed object.
/// </summary>
/// <param name="wrapperMaybe"></param>
/// <param name="instance"></param>
/// <returns>True if the wrapper was resolved to a managed object, otherwise false.</returns>
public static unsafe bool TryGetObject(void* wrapperMaybe, out object? instance);
```

**Comment by terrajobst** [comment]
Looks good as proposed.

```C#
namespace System.Runtime.InteropServices;

public abstract class ComWrappers
{
    public static bool TryGetObject(void* unknown, [NotNullWhen(true)] out object? obj);
}
```

**Comment by GSPP** [comment]
What's the significance of the returned bool? Is that not redundant with `obj != null`? If yes, is this just to enable the C# `out var` syntax? Seems drastic to add a strictly unneeded return value just for that.

**Comment by terrajobst** [comment]
The existing API on Marshal has "get or create"-semantics (which would never return null). I think the goal was to differentiate the semantics more strongly via API shape.
