### ISSUE TITLE
[API Proposal]: Support getting IUnknown for ComWrappers RCWs

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/runtime#79679]
### Background and motivation

For COM interop we expect to be able to cast RCWs to arbitrary `[ComImport]` interfaces. We use this and `Type.IsComObject` to implement `TypeDescriptor` functionality.

We can reimplement to support both legacy COM Interop and `ComWrapppers` if we have the ability to get `IUnknown*` for any `ComWrappers` generated RCWs.

Without this support we cannot enable trimming for WinForms without breaking critical features such as drag/drop/cut/paste and accessibility. This also prevents providing COM `ComWrappers` support with `TypeDescriptor` (which WinForms owns).

### API Proposal

```diff
namespace System.Runtime.InteropServices;

public abstract class ComWrappers
{
+    public static bool TryGetComInstance(object obj, out void* unknown);
}
```

### API Usage

```csharp
public static bool TryCreateComTypeDescriptor(object obj, out ComTypeDescriptor? descriptor)
{
    void* unknown;
    if (obj.GetType().IsCOMObject)
    {
        unknown = (void*)Marshal.GetIUnknownForObject(obj);
    }
    else
    {
        ComWrappers.TryGetComInstance(obj, out unknown);
    }

    return unknown is not null ? new ComTypeDescriptor(unknown) : null;
}
```

### Alternative Designs

One alternative (or addition) is to change all possible `Marshal` APIs that provide interface pointers to support `ComWrappers` RCWs:

``` C#
namespace System.Runtime.InteropServices;

// Existing interface pointer methods
public static class Marshal
{
    public static IntPtr GetComInterfaceForObject(object! o, Type! T);
    public static IntPtr GetComInterfaceForObject(object! o, Type! T, CustomQueryInterfaceMode mode);
    public static IntPtr GetComInterfaceForObject<T, TInterface>([DisallowNull] T o);
    public static IntPtr GetComInterfaceForObjectInContext(object o, Type t);
    public static IntPtr GetIDispatchForObject(object! o);
    public static IntPtr GetIDispatchForObjectInContext(object o);
    public static IntPtr GetIUnknownForObject(object! o);
    public static IntPtr GetIUnknownForObjectInContext(object o);
}
```

I don't know how plausible this is, but it would make writing consuming code much easier.

**Comment by JeremyKuhne** [comment]
cc: @lonitra, @AaronRobinsonMSFT, @jkoritzinsky, @LakshanF

related: #79674

**Comment by AaronRobinsonMSFT** [comment]
This is similar to my comment in https://github.com/dotnet/runtime/issues/79674. This would throw if there wasn't a globally registered `ComWrappers` instance. Which if there is one and it is known, this isn't an issue because one can call [`ComWrappers.GetOrCreateObjectForComInstance()`](https://learn.microsoft.com//dotnet/api/system.runtime.interopservices.comwrappers.getorcreateobjectforcominstance).

**Comment by JeremyKuhne** [comment]
> Which if there is one and it is known, this isn't an issue because one can call [ComWrappers.GetOrCreateObjectForComInstance()](https://learn.microsoft.com//dotnet/api/system.runtime.interopservices.comwrappers.getorcreateobjectforcominstance).

How does this help? `ComWrappers` RCWs implement specific interfaces, not arbitrary `[ComImport]` interfaces with matching guids. We'd presumably have to publish all interfaces we use as "interchange types". We only have a few defined interfaces in `ComTypes` and I don't believe `IUnknown` or `IDispatch` are defined anywhere. How would we publish these interfaces? With `HRESULT`s explicitly exposed or not? With "marshalling" or not?

For ActiveX Controls there are dozens of interfaces involved- and we allow providing [your own instance of the class](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.axhost.createinstancecore?view=windowsdesktop-7.0). In order for this to work (in the same way as before) we'd have to publish every interface we get off the root object and they would have to implement every single one of them. In this case I can't imagine that anyone is doing anything other than working with a wrapped `IUnknown`.

Beyond that there is a composition problem. We don't register our `ComWrappers` and I don't know that we ever could as users would not be able to register their own. How do we expose an RCW that either we created ourselves (with our non-registered `ComWrappers`) or the user provided for us (through `ComWrappers` or existing RCWs)?

Because we can't register our own `ComWrappers` I don't see how we can implement anything around COM interfaces without directly using COM pointers.

**Comment by AaronRobinsonMSFT** [comment]
Spoke to @JeremyKuhne offline. I get this scenario now. The implementation rather trivial since we already query for this information when constructing a `WeakReference`. The proposed alternative options aren't tenable due to semantic problems. The current semantics all guarantee they return a non-null value because the runtime would generate an CCW on the fly. The expectation here is the API will only return one if it exists, hence the "try" semantics.

**Comment by AaronRobinsonMSFT** [comment]
@JeremyKuhne Based on a private implementation here is what I would propose for the API along with details on use.

```csharp
/// <summary>
/// Given a managed object, determine if it is a ComWrappers created
/// managed wrapper and if so, return the wrapped unmanaged pointer.
/// </summary>
/// <param name="wrapperMaybe">A managed wrapper</param>
/// <param name="externalComObject">An unmanaged COM object</param>
/// <returns>True if the wrapper was resolved to an external COM object, otherwise false.</returns>
/// <remarks>
/// If a COM object is returned, the caller is expected to call Release() on the object.
/// This can be done through an API like Marshal.Release(). Since this API is required to interact
/// directly with the external COM object, QueryInterface(), it is important for the caller to
/// understand the COM object may have apartment affinity and therefore if the current thread is not
/// in the correct apartment or the COM object is not a proxy this call may fail.
/// </remarks>
public static unsafe bool TryGetComInstance(object wrapperMaybe, out void* externalComObject);
```

**Comment by JeremyKuhne** [comment]
@AaronRobinsonMSFT that looks good to me.

**Comment by terrajobst** [comment]
Looks good as proposed.

```C#
namespace System.Runtime.InteropServices;

public partial class ComWrappers
{
    public static bool TryGetComInstance(object? obj, out void* unknown);
}
```
