### ISSUE TITLE
Records class can not get property's CustomAttribute

### ISSUE THREAD

**Issue by startewho** [dotnet/runtime#79692]
### Description

When i used the reflection , the code like below:

### Reproduction Steps
```cs
var p = typeof(User).GetProperties().Where(p => p.GetCustomAttributes(typeof(FormatAttribute), false).FirstOrDefault() != null).FirstOrDefault();
var pdto = typeof(UserDto).GetProperties().Where(p => p.GetCustomAttributes(typeof(FormatAttribute), false).FirstOrDefault() != null).FirstOrDefault();

Console.WriteLine($"p:{p?.Name},pdto:{pdto?.Name}");


public record class User([Format] string Name);

public class FormatAttribute : Attribute
{
    public FormatAttribute()
    {

    }
}


public class UserDto
{
    [Format]
    public string Name { get; set; }
}
```
### Expected behavior

 Get the Name Property

### Actual behavior

Get Null

### Other information

Tryid .net6 .net7 .the same result

**Comment by davidfowl** [comment]
You're missing the property modifier on the attribute:

```
public record class User([property: Format] string Name);
```

You can compare the results [here]( https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoBBmABM3AYVwG9NcL88EAWXAWQAoBKU8ygX0y6zwCcApgGMA9nwAm+JLgCqAZwF9GAbQBiYyABcAuvhQAGXADkIYAcwDcmHLkGiJU2Qr5IVABz4i3izQE8QuOp8WroIBsam5lYYmNbSQVq4AQCCmpp8UMAArpoCpBxAA=)

**Comment by startewho** [comment]
> 
thanks for your help, it works .and I found the doc here:

> You may want to add attributes to any of these elements the compiler creates from the record definition. You can add a target to any attribute you apply to the positional record's properties. The following example applies the [System.Text.Json.Serialization.JsonPropertyNameAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonpropertynameattribute) to each property of the Person record. The property: target indicates that the attribute is applied to the compiler-generated property. Other values are field: to apply the attribute to the field, and param: to apply the attribute to the parameter.
[https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record](url)
