### ISSUE TITLE
[API Proposal]:  enum PARSE attribute 

### ISSUE THREAD

**Issue by aotto1968** [dotnet/runtime#79699]
### Background and motivation

I have the following enum:

```
  public enum LcErrorTypeE {
    NONE      = 0,
    FILE_IO   = 1,
    PARSE     = 2,
  }
```

this create the compile error:

```
Warning as Error: Identifier `cslcconfig.LcErrorTypeE.PARSE' differing only in case is not CLS-compliant
```

The problem is that `enum.Parse` (learn.microsoft.com/en-us/dotnet/api/system.enum.parse?view=net-6.0) is a known function.

and now the problem. *WHY* can mono(csharp) not differ between ATTRIBUTE and function?

The problem is that `enum LcErrorTypeE` is generated code and change of `PARSE` to something else ist not trivial.

### API Proposal

```
  public enum LcErrorTypeE {
    NONE      = 0,
    FILE_IO   = 1,
    PARSE     = 2,
  }
```

### API Usage

valid code
```
  public enum LcErrorTypeE {
    NONE      = 0,
    FILE_IO   = 1,
    PARSE     = 2,
  }
```

**Comment by teo-tsirpanis** [comment]
Here's how you can eliminate the warning:

```csharp
public enum LcErrorTypeE {
    NONE      = 0,
    FILE_IO   = 1,
    [CLSCompliant(false)]
    PARSE     = 2,
}
```

Do you have `[assembly:CLSCompliant(true)]` in your project (perhaps in an `AssemblyInfo` file)? I would recommend you to remove it, which would solve your problem as well. CLS compliance has lost its relevance these days, unless you specifically want to support a language other than C#, F# or Visual Basic.
