### ISSUE TITLE
missleading error net_io_invalidasyncresult

### ISSUE THREAD

**Issue by trivalik** [dotnet/runtime#79700]
### Description

The text of this error is "The IAsyncResult object was not returned from the corresponding asynchronous method on this class.", but in my opinion it should be "The IAsyncResult object was not returned from the corresponding asynchronous method on **instance of** this class.".

Additionally if you search https://github.com/dotnet/runtime/search?q=net_io_invalidasyncresult (github still not support search in commit) that
"src/libraries/System.Net.NameResolution", "src/libraries/System.Net.NetworkInformation" and "src/libraries/System.Net.Sockets" have a resx file for it, but not used.

If somebody confirms I would create a pull request for it (at least the text improvement).

### Reproduction Steps

Get the error in an async hell and be confused.

### Expected behavior

Error helps developer.

### Actual behavior

-

**Comment by wfurt** [comment]
any thoughts on the wording @stephentoub?

**Comment by MihaZupan** [comment]
Personally, I don't find the updated message any more helpful.
The added implication is that the method is an instance method and not a static one, but we don't have static ones anyway.

**Comment by antonfirsov** [comment]
Triage: should be easy to fix as long as someone finds the right wording. Contributions are welcome. Not critical for 8.0.
