### ISSUE TITLE
[Poison] Microsoft.DotNet.ILCompiler is consuming two PSB files

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/runtime#79712]
`Microsoft.DotNet.ILCompiler` is consuming PSB (previously source-built) versions of `System.Collections.Immutable.dll` and `System.Reflection.Metadata.dll`.

From poison report:
```
Microsoft.DotNet.ILCompiler/tools/netstandard/System.Collections.Immutable.dll
Microsoft.DotNet.ILCompiler/tools/netstandard/System.Reflection.Metadata.dll
```
 
These files ship with SDK and `Microsoft.DotNet.ILCompiler` nupkg.

Here's why this is happening.

`Microsoft.DotNet.ILCompiler` project builds, in CoreCLR part of the build: https://github.com/dotnet/runtime/blob/main/src/coreclr/tools/aot/ILCompiler.Build.Tasks/ILCompiler.Build.Tasks.csproj.

It restores those two binaries via package reference to `System.Reflection.Metadata` (which depends on `System.Collections.Immutable`).

This causes the usage of PSB, as we don't yet have the new binaries or `Microsoft.DotNet.ILCompiler` package. Binaries will get built later in Libraries part of the build, and packaged during Installer part of the build.

The proposed solution is to modify runtime project build order to build these 2 libraries first and update package version in ILCompiler project.

Alternatively, it would technically be possible, but not desirable, to instruct the packaging project, to pick new files: https://github.com/dotnet/runtime/blob/d8e1ec686e8336b8e17288a0f1d3ebac1ce082d5/src/installer/pkg/projects/Microsoft.DotNet.ILCompiler/Microsoft.DotNet.ILCompiler.pkgproj#L27

**Comment by ViktorHofer** [comment]
> @ViktorHofer @agocke, should this package reference also be pinned to the same version as in the HostModel project (i.e.6.0.0, in main)

No idea. @agocke would you know?

**Comment by MichalStrehovsky** [comment]
> > @ViktorHofer @agocke, should this package reference also be pinned to the same version as in the HostModel project (i.e.6.0.0, in main)
> 
> No idea. @agocke would you know?

These are build tasks - we have other build tasks that depend on S.R.Metadata. So the question of whether they need to be pinned depends on whether the desktop MSBuild has all the binding redirects to make this work with a live version.

Looking at my C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe.config, we don't bump the redirects very often. It's still 6.0 even in latest MSBuild. So I don't think we could build against or package the live bits here. I think it's the same restriction as Microsoft.NET.HostModel.csproj.

But these files are only needed for VS scenarios (I think), so we could just skip bunding these and still be fine (these libraries are inbox in netcoreapp). It will become a problem when source build becomes the product build that we ship.

**Comment by ViktorHofer** [comment]
> These are build tasks - we have other build tasks that depend on S.R.Metadata. So the question of whether they need to be pinned depends on whether the desktop MSBuild has all the binding redirects to make this work with a live version.
Looking at my C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe.config, we don't bump the redirects very often. It's still 6.0 even in latest MSBuild. So I don't think we could build against or package the live bits here. I think it's the same restriction as Microsoft.NET.HostModel.csproj.

cc @rainersigwald

**Comment by rainersigwald** [comment]
> So the question of whether they need to be pinned depends on whether the desktop MSBuild has all the binding redirects to make this work with a live version.
> 
> Looking at my C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe.config, we don't bump the redirects very often. It's still 6.0 even in latest MSBuild.

You should not expect that MSBuild will be able to update to bleeding-edge packages. There are two main reasons:

1. During the development cycle of .NET, most of the time "current" packages will actually be "future" packages, but in VS scenarios we will want to be on GA releases (for instance, for VS/MSBuild 17.5, we will not VS to depend on .NET 8.0-preview.1 packages).
2. Updating MSBuild's binding redirects is unfortunately fairly closely coupled with other Visual Studio components, so bumping versions is a long, annoying process.

I'm currently working with some folks on the "update to 7.0" iteration of that long, annoying process, and it's no good. We can't do it super frequently.

HOWEVER, for build tasks it should be perfectly fine to ship a newer version of the assemblies next to the task assembly and use that--as long as it has an AssemblyVersion outside the `0.0.0.0-{slightly stale public version}` range, the .NET Framework loader should happily pull it in side-by-side with the MSBuild/VS distributed one.

**Comment by agocke** [comment]
Rainer summed it up, but we should *never* use live bits of these packages as build task dependencies.

However, I'm not sure why we're copying the dependencies out of the Nuget package directory like that. Simple PackageReferences should work fine...

**Comment by NikolaMilosavljevic** [comment]
> Rainer summed it up, but we should _never_ use live bits of these packages as build task dependencies.
> 
> > HOWEVER, for build tasks it should be perfectly fine to ship a newer version of the assemblies next to the task assembly and use that--as long as it has an AssemblyVersion outside the 0.0.0.0-{slightly stale public version} range, the .NET Framework loader should happily pull it in side-by-side with the MSBuild/VS distributed one.
> 
> This doesn't seem like a good idea to me. The rest of the tasks in the product use "LKG" versions and I think we should stick with that.
> 
> However, I'm not sure why we're copying the dependencies out of the Nuget package directory like that. Simple PackageReferences should work fine...

Using LKG (static) version would be great and resolve the source build issue.
