### ISSUE TITLE
ICorProfilerInfo6::EnumNgenModuleMethodsInliningThisMethod may fail to report inlining sites in some cases

### ISSUE THREAD

**Issue by noahfalk** [dotnet/runtime#7972]
If ICorProfilerInfo6::EnumNgenModuleMethodsInliningThisMethod is called when:
a) The inlinersModuleId refers to a module compiled via NGen (not R2R, specifically NGEN only)
b) The inlineeModuleId refers to a module that has only loaded to a load level < DELIVER_EVENTS 

Then it will fail to report methods which did in fact inline the target method. It will also not set incompleteData = TRUE, so the profiler would incorrectly infer that inlining did not occur.

The profiler ModuleLoadFinished callback is invoked with load level POST_LOADLIBRARY for IL images (not NGEN images) which satisfies condition (b). It appears this is likely a pre-existing issue introduced when the API was first implemented in the 4.5(.1?) timeframe.

The issue occurs because decodedInlineeModule is incorrectly computed as NULL at: 
https://github.com/dotnet/coreclr/blob/master/src/vm/inlinetracking.cpp#L246
>	coreclr.dll!PersistentInlineTrackingMapNGen::GetInliners(Module * inlineeOwnerMod, unsigned int inlineeTkn, unsigned int inlinersSize, MethodInModule * inliners, int * incompleteData) Line 246	C++
 	coreclr.dll!Module::GetInliners(Module * inlineeOwnerMod, unsigned int inlineeTkn, unsigned int inlinersSize, MethodInModule * inliners, int * incompleteData) Line 204	C++
 	coreclr.dll!ProfToEEInterfaceImpl::EnumNgenModuleMethodsInliningThisMethod(unsigned __int64 inlinersModuleId, unsigned __int64 inlineeModuleId, unsigned int inlineeMethodId, int * incompleteData, ICorProfilerMethodEnum * * ppEnum) Line 9330	C++

The root cause is that IL modules become visible to the profiler at the POST_LOADLIBRARY load level, however the code path the inline tracker is using to resolve them doesn't correctly do so until the DELIVER_EVENTS level. At:
https://github.com/dotnet/coreclr/blob/master/src/vm/ceeload.cpp#L5439
>	coreclr.dll!Module::GetAssemblyIfLoaded(unsigned int kAssemblyRef, const char * szWinRtNamespace, const char * szWinRtClassName, IMDInternalImport * pMDImportOverride, int fDoNotUtilizeExtraChecks, ICLRPrivBinder * pBindingContextForLoadedAssembly) Line 5522	C++
 	coreclr.dll!ZapSig::DecodeModuleFromIndexesIfLoaded(Module * fromModule, unsigned long assemblyIndex, unsigned long moduleIndex) Line 705	C++
 	coreclr.dll!Module::GetModuleFromIndexIfLoaded(unsigned long ix) Line 10089	C++
 	coreclr.dll!PersistentInlineTrackingMapNGen::GetModuleByIndex(unsigned long index) Line 304	C++

we perform the IsLoaded() check which disregards the module we ideally would have returned.

Because NGEN images only become visible at the DELIVER_EVENTS load level the case of NGEN image A inlining IL from NGEN image B works as expected.

**Comment by davmason** [comment]
Closing since NGEN is no longer supported on coreclr
