### ISSUE TITLE
[API Proposal]: Implicit operators for Task<T>

### ISSUE THREAD

**Issue by Ali-YousefiTelori** [dotnet/runtime#79746]
### Background and motivation

Hi,
For now, We have to use Task.FromResult directly to convert a variable to Task<T> result without using async and await.
My suggestion will make an easy way to return Task<T> result.

example for now we have to do this way:

```csharp
        public Task<bool> GetResult()
        {
            return Task.FromResult(true);
        }
```

After this feature we can do this for all types :

```csharp
        public Task<bool> GetResult()
        {
            return true;
        }
```

The Task<T> can have implicit operators inside it's.
If you are ok, I can implement it.

### API Proposal

```csharp
    public class Task<T>
    {
        public static implicit operator Task<T>(T parameter)
        {
            return Task.FromResult(parameter);
        }
    }
```

### API Usage

```csharp
        public Task<bool> GetResultSample()
        {
            return true;
        }
```

### Risks

The dotnet compiler has to manage the methods ```async Task<T> GetResultSample() ``` and   ```Task<T> GetResultSample()  ``` to use implicit operators.

**Comment by gfoidl** [comment]
See https://github.com/dotnet/runtime/issues/15892

> an implicit conversion that allocates is considered fairly bad form. It makes it very difficult to spot potential performance problems

That still holds.
