### ISSUE TITLE
Inconsistent generation on a timestamp value using DateTimeOffset

### ISSUE THREAD

**Issue by jozif001** [dotnet/runtime#79743]
we are generating a Timestamp value using DateTimeOffset with maximum precision to define the processing order of records, we can't use incremental values because of the concurrency (two or more requests at the same time) issue, so we try to generate a Timestamp using the following code:
```
var processingOrder = DateTimeOffset.Now.ToString("yyMMddHHmmssFFFFFFF");
```
as you can see it uses the full seven most significant digits of the second's fraction.
We've done this procedure quite often and we've seen some cases where the generated values are not identical, and in some cases, it generates values lacking a digit.

examples:
```
221214184302839946      <= here
2212141142402360511
221214114240702689      <= here
2212141137434261509
2212141103431896048
```
is this normal behavior or is it a bug?
is there any other way we can use to generate a similar value more precisely and with a guaranteed result?

**Comment by svick** [comment]
[The `FFFFFFF` specifier works exactly as documented](https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#FFFFFFF_Specifier) (emphasis mine):

> The "FFFFFFF" custom format specifier represents the seven most significant digits of the seconds fraction; that is, it represents the ten millionths of a second in a date and time value. **Trailing zeros aren't displayed.**

What you're looking for is [the `fffffff` specifier](https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#fffffffSpecifier).

For example, consider the following code:

```c#
var now = DateTimeOffset.Parse("2022-12-16T11:42:50.1234");
Console.WriteLine(now.ToString("yyMMddHHmmssFFFFFFF"));
Console.WriteLine(now.ToString("yyMMddHHmmssfffffff"));
```

This prints:

```
2212161142501234
2212161142501234000
```

**Comment by gfoidl** [comment]
> we can't use incremental values because of the concurrency

`Interlocked.Increment` can be used iff within a single process. For distributes processes that won't work though.

> is there any other way we can use to generate a similar value more precisely and with a guaranteed result?

For coordinated approaches some Paxos-like algorithms, but that's cumbersome to implement.
Or un-coordinated approaches like [Snowflake](https://blog.twitter.com/engineering/en_us/a/2010/announcing-snowflake) from Twitter, which is implemented for .NET in https://github.com/RobThree/IdGen. See if the "roughly sorted" is enough for your use-case.
Or use a sequential GUID.
These are just a few alternatives to DTO, as there may be clashes depending on the workloud you have / expect to have.

**Comment by Clockwork-Muse** [comment]
Also - `DateTimeOffset.Now` should really be `DateTimeOffset.UtcNow`.  Especially if you're not appending the offset, so if that gets run distributed you might have multiple timezones (and hence incorrectly ordered stamps).
And if you're including (almost - you're leaving off the offset) all the date/time fields, you're probably better off just using the ISO format specifier (`o`/`O`).
