### ISSUE TITLE
issues of milestone 8.0.0 already fixed/present in 7.0.1

### ISSUE THREAD

**Issue by springy76** [dotnet/runtime#79752]
ex: https://github.com/dotnet/runtime/issues/76298

No mention in release notes - both issue 76298 and according merge request locked as resolved and limited conversation by some kind of bot - so fix was done weeeeeks before 7.0.0 got released.. Would have saved me from adding (and now removing) 1001+ files from source control.

**Comment by jeffhandley** [comment]
Hi @springy76; thanks for filing this. We're sorry for the inconvenience this caused you that it looked like this was a known issue but we had backported the fix to `release/7.0`. After a release branch is snapped, fixes generally go into the next version and then get considered for backporting, and that's indeed what happened here.

I'll discuss this situation with the team to look for opportunities to improve our documentation around known issues that get fixed like this one did.
