### ISSUE TITLE
`Environment.GetFolderPath(ApplicationData)` returns empty string on linux under root account

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#79757]
### Description

.NET returns an empty string for the `SpecialFolder.ApplicationData` location when running under the root account (via sudo, at least).

The `LocalApplicationData` location however is just fine. It returns a non-empty string for root and non-root accounts.

### Reproduction Steps

In a linux command prompt, under a Powershell prompt, run these commands:

```
PS /home/andrew/rustplayground/my-gtk-app> [environment]::getfolderpath([system.Environment+specialfolder]::applicationdata).length
20
PS /home/andrew/rustplayground/my-gtk-app> sudo pwsh
PowerShell 7.3.1
PS /home/andrew/rustplayground/my-gtk-app> [environment]::getfolderpath([system.Environment+specialfolder]::applicationdata).length
0
```

### Expected behavior

I expect `Environment.GetFolderPath(SpecialFolder.ApplicationData)` to return a non-empty string for root.

### Actual behavior

`Environment.GetFolderPath(SpecialFolder.ApplicationData)` returns an empty string for root.

### Regression?

Unknown.

### Configuration

Powershell running on .NET 7 on Ubuntu 22.10

**Comment by dakersnar** [comment]
Do you know if this behavior was different in .NET 6?

**Comment by danmoseley** [comment]
Is $HOME defined? What about $$XDG_CONFIG_HOME

**Comment by AArnott** [comment]
as root:
```
PS /home/andrew> gci env:/XDG*
PS /home/andrew> gci env:/HOME

Name                           Value
----                           -----
HOME                           /root
```

As a regular user:
```
PS /home/andrew> gci env:/XDG*

Name                           Value
----                           -----
XDG_DATA_DIRS                  /usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop

PS /home/andrew> gci env:/HOME

Name                           Value
----                           -----
HOME                           /home/andrew
```

**Comment by AArnott** [comment]
No idea if this worked differently with .NET 6.

**Comment by danmoseley** [comment]
What do you get for LocalApplicationData in both, and ApplicationData when not root?

**Comment by AArnott** [comment]
account | LocalApplicationData | ApplicationData
--|--|--
andrew | /home/andrew/.local/share | /home/andrew/.config 
root | /root/.local/share | (empty)

**Comment by danmoseley** [comment]
Hmm well looking at the code linked above it appears to be behaving as if XDG_CONFIG_HOME is defined but with an empty value.

**Comment by tmds** [comment]
> .NET returns an empty string for the SpecialFolder.ApplicationData location

The method returns an empty string when the directory doesn't exist. Try calling the overload that takes a `SpecialFolderOption` with `SpecialFolderOption.DoNotVerify`.

**Comment by AArnott** [comment]
Thanks. I'll use that.
