### ISSUE TITLE
Binding a dictionary mutates existing values instead of replacing

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#79770]
### Description

In .NET 6.0 binding to a dictionary would replace existing keys.  Now it mutates them.  It's unclear to me which is more correct, but this is breaking.

### Reproduction Steps

```C#
using Microsoft.Extensions.Configuration;

IConfiguration config = new ConfigurationBuilder()
    .AddInMemoryCollection()
    .Build();

config["Key:0"] = "NewValue";
var dict = new Dictionary<string, string[]>()
{ { "Key", new[] { "InitialValue" } } };

Console.WriteLine($"Initially: {String.Join(", ", dict["Key"])}");
config.Bind(dict);
Console.WriteLine($"Bind: {String.Join(", ", dict["Key"])}");
config.Bind(dict);
Console.WriteLine($"Bind again: {String.Join(", ", dict["Key"])}");
```
[dictRegression.zip](https://github.com/dotnet/runtime/files/10249076/dictRegression.zip)

### Expected behavior

The value in the dictionary should be replaced, with output like:
```
Initially: InitialValue
Bind: NewValue
Bind again: NewValue
```

### Actual behavior

The value is appended.
```
Initially: InitialValue
Bind: InitialValue, NewValue
Bind again: InitialValue, NewValue, NewValue
```

### Regression?

Yes.  This is a regression from 6.0.0 likely caused by https://github.com/dotnet/runtime/pull/63834.

**Comment by ericstj** [comment]
Thank you to @michasHL reported this.

CC @mapogolions for thoughts on how his change might have caused this.

It would seem this isn't unique to collections, but also applies to pocos.  I extended the example above with the following:
```c#
var dict2 = new Dictionary<string, MyPoco>()
{ { "Key", new() { A = "hello"} } };

config["Key:B"] = "world";
Console.WriteLine($"Initially: {dict2["Key"]}");
config.Bind(dict2);
Console.WriteLine($"Bind: {dict2["Key"]}");
config.Bind(dict2);
Console.WriteLine($"Bind again: {dict2["Key"]}");

class MyPoco
{
    public string A { get; set; }
    public string B { get; set; }

    public override string ToString() => $"A: {A} B: {B}";
}
```

On .NET 6.0 this produces:
```
Initially: A: hello B:
Bind: A:  B: world
Bind again: A:  B: world
```

Whereas on .NET 7.0 this produces:
```
Initially: A: hello B:
Bind: A: hello B: world
Bind again: A: hello B: world
```

Now lets consider what would happen if we use all POCOs and no collection.  This can serve as _precedent_ for what the right behavior should be, if we can think of a dictionary here as just another way to represent an object with properties.
```c#
var parent = new MyParentPoco()
{
    Key = new() { A = "hello"}
};
config["Key:B"] = "world";
Console.WriteLine($"Initially: {parent.Key}");
config.Bind(parent);
Console.WriteLine($"Bind: {parent.Key}");
config.Bind(parent);
Console.WriteLine($"Bind again: {parent.Key}");


class MyParentPoco
{
    public MyPoco Key { get; set;}
}

class MyPoco
{
    public string A { get; set; }
    public string B { get; set; }

    public override string ToString() => $"A: {A} B: {B}";
}
```

This has the exact same behavior on .NET 6.0 and .NET 7.0.
```
Initially: A: hello B:
Bind: A: hello B: world
Bind again: A: hello B: world
```

I can see how the new behavior for Dictionary might be more correct and consistent, since it matches how things work for POCOs.

**Comment by tarekgh** [comment]
@michasHL I agree with what @ericstj mentioned. The new behavior looks more correct to me too. We can consider documenting this breaking change. What do you think about that?

**Comment by michasHL** [comment]
Hello @tarekgh it's really hard for me to decide what is "more" correct over the other. 
Clearly the example @ericstj gave with the POCO seems to be behaving in line of my expectation with .NET 7 over .NET 6.

The use-case for us with the replace or append with an Array I would argue is not as clear-cut.
My team can go through our code-base to find issues with the bindings and that's actually already what we're doing.

I agree that documenting this change in behavior with the other breaking changes would be the next best thing to reverting the behavior altogether.

**Comment by tarekgh** [comment]
> The use-case for us with the replace or append with an Array I would argue is not as clear-cut.

We need to pick the closest correct behavior to be the default behavior. .NET 7.0 behavior looks more correct to me. So, will be good to review the use cases in your side and try to adapt the new behavior if possible. 

> My team can go through our code-base to find issues with the bindings and that's actually already what we're doing.

That is a good idea to do. 

> I agree that documenting this change in behavior with the other breaking changes would be the next best thing to reverting the behavior altogether.

Sounds documenting the breaking change will be the way to go then. I'll keep this issue open to track that. Thanks!

**Comment by tarekgh** [comment]
I have filed the breaking change issue https://github.com/dotnet/docs/issues/33685. I am closing this code as no more actions are needed here. Let's know if you have any question or ask we can help with.

**Comment by tarekgh** [comment]
https://github.com/dotnet/runtime/issues/118204
