### ISSUE TITLE
Performance regression - Allocation/WorkingSet on PlaintextPlatform

### ISSUE THREAD

**Issue by sebastienros** [dotnet/runtime#79774]
Allocations are increasing significantly on PlaintextPlatform, Windows only.
Minimal commits range: https://github.com/dotnet/runtime/compare/320f1e1...d47a24c

![image](https://user-images.githubusercontent.com/1165805/208203552-0a22fb2f-392d-41db-8dcf-7427a0725e7b.png)

![image](https://user-images.githubusercontent.com/1165805/208203587-7ade7c6e-0a2c-4ac7-b16c-cf845de84d35.png)

This type is the most allocating one after the regression shows up:

```
Name                                                                                               	Inc %	           Inc
 + System.Private.CoreLib.il!System.Threading.DeferredDisposableLifetime`1[System.__Canon].AddRef()	 82.8	   297,039,616
 |+ System.Private.CoreLib.il!ThreadPoolBoundHandle.AllocateNativeOverlapped                       	 82.8	   297,039,616
 | + System.Net.Sockets.il!SocketAsyncEventArgs.DoOperationReceiveSingleBuffer                     	 41.6	   149,219,392
 | + System.Net.Sockets.il!SocketAsyncEventArgs.DoOperationSendSingleBuffer                        	 39.2	   140,601,632
```

@stephentoub

**Comment by sebastienros** [comment]
Not just Plaintext Platform actually, but most benchmarks that didn't allocate enough to even trigger a GC. All Windows.

![image](https://user-images.githubusercontent.com/1165805/208204133-9693a342-1469-4545-8e40-98a24afa7723.png)

**Comment by MihaZupan** [comment]
Looks like we're boxing the struct here https://github.com/dotnet/runtime/blob/c6045adbf8f9092acc8c273946a3398f6309b80e/src/libraries/System.Private.CoreLib/src/System/Threading/DeferredDisposableLifetime.cs#L53
regressed in #79096
