### ISSUE TITLE
[API Proposal]: Provide optimized read-only collections for SortedSet and SortedDictionary

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/runtime#79781]
### Background and motivation

There are many scenarios where collections are initialized during startup, or during major state changes in the application, and are not mutated afterward. Taking advantage of this pattern can lead to substantial improvements in the overall access performance of the collections.

Additionally, the overwhelming majority of dictionaries and sets use strings and int as key types. Providing collections that are optimized for these types can also contribute to substantial performance gains relative to the canonical `SortedDictionary<,>` and `SortedSet<>` types.

The implementation will be as simple as the usual sorted array (all items are sorted by key) and no methods to modify items. It will be faster than SortedSet/SortedDictionary and consume less memory also.

In addition to the freezing functionality, the frozen dictionary API also provides the GetByRef method which makes it possible to get the ref to a value in a frozen dictionary, making dictionaries holding large value types efficient.

### API Proposal

```csharp
I provide API later when the motivation will be approved.
```
A few notes for discussion:
* **Ref-returning Members.** One of the design goals here is to enable all means of reading to be efficient; that includes when the values stored in a dictionary are large structs. Thus, as with ReadOnlySpan<T>, the indexer here returns a ref readonly T rather than just a T. There aren't safety concerns here as the underlying storage is immutable. For advanced usage, this also exposes a GetValueRefOrNullRef that mirrors the same method for SortedDictionary<,> we expose from CollectionsMarshal (but there, we put it on CollectionsMarshal because a growing dictionary can make the ref erroneous, and that's not a problem here).
* **Abstract base types.** As with types like Dictionary<,> and HashSet<>, these types are not meant to be extended arbitrarily. However, because they optimize for the exact set of inputs frozen into the collection, it's important to be able to customize the implementation based on the inputs. Thus, the collections are abstract, with a ToFrozenDictionary/Set factory that produces the right internally-derived implementation. Developers consuming the types only concern themselves with the FrozenDictionary<,>/FrozenSet<,> types and the associated extension methods, and the abstractness is just an implementation detail that's required to be public.

### API Usage

```csharp
var d = new SortedDictionary<string, int>(...);
var frozenD = d.Freeze();

var s = new SortedSet<string>(...);
var frozenS = s.Freeze();
```

**Comment by madelson** [comment]
> The implementation will be as simple as the usual sorted array

The `SortedList<TKey, TValue>` type is backed by a sorted array; could be worth checking out.

**Comment by layomia** [comment]
This looks like a fork of https://github.com/dotnet/runtime/issues/67209. Follow ups for the frozen collection feature set are being discussed here - https://github.com/dotnet/runtime/issues/77891. Please share your requirements in that issue.
