### ISSUE TITLE
[API Proposal]: Publicly expose `IPartition<TElement>`

### ISSUE THREAD

**Issue by neon-sunset** [dotnet/runtime#79791]
### Background and motivation

As of now, when taking advantage of LINQ, the developers are either limited to optimizations available to explicitly materialized collections like `ICollection<T>` and `IList<T>` or have to rely on `IEnumerable<T>` fallback that can't take advantage of implementation "traits" that are available to private enumerable implementations like, for example, `SelectListPartitionIterator<TSource, TResult>`.

It appears that `IPartition<TElement>` could be exposed to allow BCL's LINQ implementation to work with custom view-like and enumerator-like types that are not yet a fully materialized `ICollection<T>` but not an opaque unbound enumerable either.

### API Proposal

Includes `IListProvider` inherited members.
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq/src/System/Linq/IPartition.cs
```csharp
namespace System.Linq
{
    /// <summary>
    /// An iterator that supports random access and can produce a partial sequence of its items through an optimized path.
    /// </summary>
    public interface IPartition<TElement> : IIListProvider<TElement>
    {
        /// <summary>
        /// Creates a new partition that skips the specified number of elements from this sequence.
        /// </summary>
        /// <param name="count">The number of elements to skip.</param>
        /// <returns>An <see cref="IPartition{TElement}"/> with the first <paramref name="count"/> items removed.</returns>
        IPartition<TElement> Skip(int count);

        /// <summary>
        /// Creates a new partition that takes the specified number of elements from this sequence.
        /// </summary>
        /// <param name="count">The number of elements to take.</param>
        /// <returns>An <see cref="IPartition{TElement}"/> with only the first <paramref name="count"/> items.</returns>
        IPartition<TElement> Take(int count);

        /// <summary>
        /// Gets the item associated with a 0-based index in this sequence.
        /// </summary>
        /// <param name="index">The 0-based index to access.</param>
        /// <param name="found"><c>true</c> if the sequence contains an element at that index, <c>false</c> otherwise.</param>
        /// <returns>The element if <paramref name="found"/> is <c>true</c>, otherwise, the default value of <typeparamref name="TElement"/>.</returns>
        TElement? TryGetElementAt(int index, out bool found);

        /// <summary>
        /// Gets the first item in this sequence.
        /// </summary>
        /// <param name="found"><c>true</c> if the sequence contains an element, <c>false</c> otherwise.</param>
        /// <returns>The element if <paramref name="found"/> is <c>true</c>, otherwise, the default value of <typeparamref name="TElement"/>.</returns>
        TElement? TryGetFirst(out bool found);

        /// <summary>
        /// Gets the last item in this sequence.
        /// </summary>
        /// <param name="found"><c>true</c> if the sequence contains an element, <c>false</c> otherwise.</param>
        /// <returns>The element if <paramref name="found"/> is <c>true</c>, otherwise, the default value of <typeparamref name="TElement"/>.</returns>
        TElement? TryGetLast(out bool found);

        /// <summary>
        /// Produce an array of the sequence through an optimized path.
        /// </summary>
        /// <returns>The array.</returns>
        TElement[] ToArray();

        /// <summary>
        /// Produce a <see cref="List{TElement}"/> of the sequence through an optimized path.
        /// </summary>
        /// <returns>The <see cref="List{TElement}"/>.</returns>
        List<TElement> ToList();

        /// <summary>
        /// Returns the count of elements in the sequence.
        /// </summary>
        /// <param name="onlyIfCheap">If true then the count should only be calculated if doing
        /// so is quick (sure or likely to be constant time), otherwise -1 should be returned.</param>
        /// <returns>The number of elements.</returns>
        int GetCount(bool onlyIfCheap);
    }
}
```

### API Usage

```csharp
readonly struct SelectView<TSource, TElement, TList> : IPartition<TElement>
    where TList : IList<TSource>
{
    private readonly TList _source;
    private readonly Func<TSource, TElement> _selector;
    ...
    public TElement TryGetElementAt(int index, out bool found)
    {
        found = false;
        if (index >= 0 && index < _source.Count)
        {
            found = true;
            return _selector(_source[index]);
        }
        return default;
    }
    ...
}
```

The above is just an example scenario. The main purpose is to allow third-party collection and enumerable-like types to take the advantage of the "underlying-collection-aware" logic of the standard library beyond current limitations without having to reimplement `Select`, `Where`, and other enumerator types themselves.

### Alternative Designs

Privately implemented replacements for LINQ enumerator types that are tuned for particular non-standard (unmaterialized) collection types.

### Risks

- Making `IPartition<TElement>` public places restrictions on possible breaking changes available to BCL which may be undesirable for a part of standard library that is currently under review for the further improvement (the LINQ usage survey)
- Exposing additional methods will further complicate already wide API surface of LINQ-implementing types

**Comment by Sergio0694** [comment]
The proposed interface is extending `IIListProvider<TElement>`, but note that that interface isn't public either. Consider adjusting the proposal to either also propose making that public, or to adjust the API surface to work around it.

> **Note**: not commenting on the merits of this proposal, just pointing out an issue in the proposed API surface as of right now.

**Comment by eiriktsarpalis** [comment]
The internal enumerable implementations only implement `ISourceProvider`/`IPartition` in platforms that have speed optimizations enabled:

https://github.com/dotnet/runtime/blob/9fe3afee44401d52497ac6fbe03161d12183ab66/src/libraries/System.Linq/src/System.Linq.csproj#L8

https://github.com/dotnet/runtime/blob/9fe3afee44401d52497ac6fbe03161d12183ab66/src/libraries/System.Linq/src/System.Linq.csproj#L17-L38

As such these interfaces are platform-specific implementation details, making them public result in inconsistency for the built-in enumerables.
