### ISSUE TITLE
RegEx: Possible bug in Regex when matching words located right after an emoticon

### ISSUE THREAD

**Issue by miroslavp** [dotnet/runtime#79792]
Hi,
I wrote a simple code that matches words in a text. However it doesn't work as expected for words that are placed next to an emoticon. The regex captures the word with part of the emoticon. Here's the code

```csharp
using System.Text.RegularExpressions;

public class Program
{
    private static readonly Regex wordsRegEx = new Regex(@"\b[\w]*\b", RegexOptions.Compiled);

    public static string[] GetWords(string text)
    {
        MatchCollection matches = wordsRegEx.Matches(text);

        var words = from m in matches.Cast<Match>()
                    where !string.IsNullOrEmpty(m.Value)
                    select m.Value;

        return words.ToArray();
    }
    public static void Main()
    {
        var content = "Before emoticon❣️After emoticon";
        var words = GetWords(content);
    }

}
```
You can see in the Watch window that the word after the emoticon contains part of the emoticon as a first char

![watch](https://user-images.githubusercontent.com/1788594/208255658-0470d2f1-e8b8-4ee3-a4c8-dc667b70f96e.png)

Is this is an expected behavior or is it a bug?

**Comment by danmoseley** [comment]
Is the question, why is "HEAVY HEART EXCLAMATION MARK ORNAMENT" matching \w?

Or why it's showing up as 65039 instead of its actual code point 10083?

**Comment by stephentoub** [comment]
Your string "Before emoticon❣️After emoticon" contains the non-spacing mark `(char)0xFE0F` just after the emoji.  Regex treats individual System.Chars as their own entity, so it processes this non-spacing mark separately from the `(char)0x2763` that comes before it (the actual emoji).  And non-spacing marks are considered word characters (`\w`), which is why it's being included in the "After" word.

**Comment by miroslavp** [comment]
> > Is this is an expected behavior or is it a bug?
> 
> It's expected. Your string "Before emoticon❣️After emoticon" contains the non-spacing mark [`(char)0xFE0F`](https://codepoints.net/U+FE0F) just after the emoji. Regex treats individual System.Chars as their own entity, so it processes this non-spacing mark separately from the `(char)0x2763` that comes before it (the actual emoji). And non-spacing marks are considered word characters (`\w`), which is why it's being included in the "After" word.

Thank you for the explanation. I've read somewhere that [(char)0xFE0F](https://codepoints.net/U+FE0F) is used to make emojis look more graphical, but didn't know that it is also considered a word character. That makes sense now.
