### ISSUE TITLE
System.Text.Json: Add option to write trailing commas on serialization.

### ISSUE THREAD

**Issue by Drake53** [dotnet/runtime#79793]
### Background and motivation

Currently trailing commas are only supported on deserialization using JsonSerializerOptions.AllowTrailingCommas, it'd be nice if they can be supported on serialization as well.

One of the benefits of this feature would be improving diff views (for example with this library: https://github.com/mmanela/diffplex), since diffs look better when the JSON texts have trailing commas.

### API Proposal

```csharp
namespace System.Text.Json;

public class JsonSerializerOptions
{
    public bool WriteTrailingCommas { get; set; }
}
```

### API Usage

```csharp
var options = new JsonSerializerOptions
{
    WriteTrailingCommas = true,
    WriteIndented = true,
};

var oldText = JsonSerializer.Serialize(oldObject, options);
var newText = JsonSerializer.Serialize(newObject, options);

var diffView = new DiffViewer
{
    Dock = DockStyle.Fill,
    OldText = oldText,
    NewText = newText,
};
```

**Comment by fbrosseau** [comment]
Allowing to read non-standard extensions like commas (and probably much more often, comments) is very different from allowing to generate non-standard output.

Being able to read allows you to write a well-behaving application that happens to tolerate slightly invalid input (again, mostly comments) without having to reinvent systemtextjson, or without having to preprocess user input.

Being able to write would make dotnet generate objectively invalid output, which is probably not something you want as a framework.

**Comment by eiriktsarpalis** [comment]
Even though _writing_ invalid JSON is something we would never consider for STJ, it might be possible to include opt-in support for _reading_ certain forms of invalid JSON. This is tracked by https://github.com/dotnet/runtime/issues/32291.
