### ISSUE TITLE
Vector{128|256}.IsHardwareAccelerated return false when read via reflection

### ISSUE THREAD

**Issue by PJB3005** [dotnet/runtime#79795]
### Description

`Vector128.IsHardwareAccelerated` and similar always return false when read via reflection, even when the CPU supports it and reading the property directly via code *does* return true.

### Reproduction Steps

```cs
using System.Runtime.InteropServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;

Console.WriteLine($"{RuntimeInformation.RuntimeIdentifier} {RuntimeInformation.FrameworkDescription} {RuntimeInformation.OSDescription}");

// @formatter:off
Check(typeof(Vector128), "IsHardwareAccelerated", Vector128.IsHardwareAccelerated);
Check(typeof(Vector256), "IsHardwareAccelerated", Vector256.IsHardwareAccelerated);
Check(typeof(Avx),       "IsSupported",           Avx.IsSupported);
Check(typeof(Avx2),      "IsSupported",           Avx2.IsSupported);
// @formatter:on

void Check(Type type, string name, bool direct)
{
    var prop = type.GetProperties().First(x => x.Name == name);

    Console.WriteLine($"{type.Name}.{name} reflection: {prop.GetValue(null)}");
    Console.WriteLine($"{type.Name}.{name} direct:     {direct}");
}
```

### Expected behavior

`Vector128.IsHardwareAccelerated` and such should match value when read directly and when read via reflection.

```
win10-x64 .NET 7.0.1 Microsoft Windows 10.0.22000
Vector128.IsHardwareAccelerated reflection: True
Vector128.IsHardwareAccelerated direct:     True
Vector256.IsHardwareAccelerated reflection: True
Vector256.IsHardwareAccelerated direct:     True
Avx.IsSupported reflection: True
Avx.IsSupported direct:     True
Avx2.IsSupported reflection: True
Avx2.IsSupported direct:     True
```

### Actual behavior

They don't match, they're false when not read via reflection.

```
win10-x64 .NET 7.0.1 Microsoft Windows 10.0.22000
Vector128.IsHardwareAccelerated reflection: False
Vector128.IsHardwareAccelerated direct:     True
Vector256.IsHardwareAccelerated reflection: False
Vector256.IsHardwareAccelerated direct:     True
Avx.IsSupported reflection: True
Avx.IsSupported direct:     True
Avx2.IsSupported reflection: True
Avx2.IsSupported direct:     True
```

### Configuration

Version: .NET 7.0.1
OS: Windows 11 21H2 build 22000.1335
Architecture: x64
No idea if specific

**Comment by tannergooding** [comment]
This was resolved in .NET 8 https://github.com/dotnet/runtime/pull/69578.

CC. @jeffhandley, we didn't think it met the bar at the time (the fix went in mid September, just after the final snap) but it might meet the bar with more users hitting it.

**Comment by jeffhandley** [comment]
@PJB3005 Could you provide context for how you encountered this? That would help us understand how it affected you and whether or not we should backport the fix to .NET 7 in a servicing release. Thanks!

**Comment by PJB3005** [comment]
Was debugging why my code wasn't working and then as a sanity check tried to check this property from the debugger, resulting in it returning false. This got me *very* confused and I ended up having to ask in the C# discord (which then made me file this bug).

**Comment by dakersnar** [comment]
We've determined this is not worthy of backporting, but as mentioned, this is fixed in .NET 8. If there is evidence that we need to backport we will reconsider, so anyone can feel free to open a new issue if they believe the backport is needed.
