### ISSUE TITLE
[.NET 7.0 + WASM AOT] Assembly.GetName().Name crashes the app

### ISSUE THREAD

**Issue by DierkDroth** [dotnet/runtime#79814]
### Description

@vargaz I came across another WASM AOT crash where @jeromelaban pointed me here.

I'll copy the details of [my original report](https://github.com/unoplatform/uno/issues/10763) for your convenience ... and please believe me, for the whole weekend I (successfully) isolated the issue in my app and (unsuccessfully) tried to create a repo, but again failed ... so, again no repo :-(

I isolated an AOT crash where adding the line
`var o = GetType().Assembly.GetName().Name;`
... to my app's code crashes the app (screenshow and logs below).

Interestingly I have the line below right before the offending line above in my code and this itself does not cause any issues
```collection-which-is-not-empty.FirstOrDefault(o => o.Name == assembly.GetName().Name && o.Version == assembly.GetName().Version.ToString(3)) == null```

And it's getting even more weird: if I commented out the offending line, then the app would work as expected - of course. But if I 'commented' it out by
```
#if !HAS_UNO_WASM
var o = GetType().Assembly.GetName().Name;
#endif
```
... then the app still would crash?!? Really?!? Go figure...

Unfortunately I was unable to create a repo - although the issue itself is 100% reproducible by only adding the offending line above to my app. So, another WASM AOT mystery ... :-(

Would you have any idea idea what might be causing the issue?

[1671438561270.zip](https://github.com/unoplatform/uno/files/10257580/1671438561270.zip)

```
dotnet.js:1149 2022-12-19 08:27:21:693 (df574c21-3788-4807-9e52-2d6a793ca322) Common.Session.ConnectDbAsync: useLocalDb=False
dotnet.js:5 Error: [MONO] * Assertion at D:/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/mono/mono/mini/interp/interp.c:2557, condition `is_ok (error)' not met, function:init_jit_call_info, Attempting to JIT compile method '(wrapper other) void modreq(System.Runtime.CompilerServices.IsExternalInit) object:gsharedvt_out_sig (object&,intptr)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
 assembly:<unknown assembly> type:<unknown type> member:(null)

    at mono_wasm_stringify_as_error_with_stack (Latest/package_34f078c37648e985421d5e6a0dc211630a4e3da0/dotnet.js:5:620)
    at Object.mono_wasm_trace_logger (Latest/package_34f078c37648e985421d5e6a0dc211630a4e3da0/dotnet.js:5:985)
    at _mono_wasm_trace_logger (Latest/package_34f078c37648e985421d5e6a0dc211630a4e3da0/dotnet.js:5034:66)
    at wasm_trace_logger (Latest/package_34f078c37648e985421d5e6a0dc211630a4e3da0/dotnet.wasm)
    at eglib_log_adapter (Latest/package_34f078c37648e985421d5e6a0dc211630a4e3da0/dotnet.wasm)
    at monoeg_g_logv_nofree (Latest/package_34f078c37648e985421d5e6a0dc211630a4e3da0/dotnet.wasm)
    at monoeg_assertion_message (Latest/package_34f078c37648e985421d5e6a0dc211630a4e3da0/dotnet.wasm)
    at do_jit_call (Latest/package_34f078c37648e985421d5e6a0dc211630a4e3da0/dotnet.wasm)
    at interp_exec_method (Latest/package_34f078c37648e985421d5e6a0dc211630a4e3da0/dotnet.wasm)
    at interp_runtime_invoke (Latest/package_34f078c37648e985421d5e6a0dc211630a4e3da0/dotnet.wasm)
mono_wasm_trace_logger @ dotnet.js:5
```

### Reproduction Steps

Please see above

### Expected behavior

Please see above

### Actual behavior

Please see above

### Known Workarounds

None

**Comment by vargaz** [comment]
This is a testcase which is supposed to hit the relevant code path:
```
using System;

public class Test
{
    public string Prop
    {
        get { return "A"; }
        init { }
    }

    public static void Main () {
        try {
            throw new Exception ();
        } catch {
            var t = new Test () { Prop = "B" };
        }
    }
}
```

However, it doesn't cause a crash with dotnet/runtime HEAD.

**Comment by DierkDroth** [comment]
@vargaz thanks for looking into.

Curious: I don't see `Assembly.GetName().Name` in your sample - which is what makes my app crash.

What am I missing?

**Comment by vargaz** [comment]
The testcase should hit the code path inside the runtime which contains the failed assertion. Unfortunately, it doesn't reproduce the problem for me.

**Comment by DierkDroth** [comment]
@vargaz thanks again. 

Is there anything else I could try to isolate the issue (although every iteration will take ~1 hour due to the time needed to do the AOT build)?

**Comment by vargaz** [comment]
If you add the testcase code to the app, does it cause it to crash ?

**Comment by DierkDroth** [comment]
@vargaz thanks for getting back to me.

Please find below what I see when adding your coding above to my app and executing it like:
```
try
{ 
	Test.Main();
}
catch
{
	// does not make it here
}
```

Does this help?

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/26179242/210222277-44f2daa7-51f2-404a-a73e-7a4c8462d639.png">

**Comment by vargaz** [comment]
Does it also fail if you add the testcase to an empty uno app ?

**Comment by vargaz** [comment]
Also, can you try to get a verbose build log (/v:d argument to msbuild) ?

**Comment by DierkDroth** [comment]
@vargaz that's interesting: I can't compile a blank UNO template using your code snce there is conflict on static 'Main' function. Even if I stuffed your code in a different namespace would it not compile. @jeromelaban FYI
Not sure why it compiles file in my app...

So, I renamed 'Main' to 'Run'. However, the AOT compilation of a blank UNO project would **not** crash.

**Comment by DierkDroth** [comment]
@vargaz I attached build logs and a more detailed screenshot

[build.zip](https://github.com/dotnet/runtime/files/10334479/build.zip)

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/26179242/210305321-093783e3-c357-4935-95dc-cb2cee389502.png">
