### ISSUE TITLE
MVC Scaffolding and XmlTransforms -- Web.config

### ISSUE THREAD

**Issue by jamespack** [dotnet/runtime#79838]
I dont know if this is the appropriate place for this question. If not, please direct me to where I should direct my question.

Our project is using .Net framework 4.8 and utilizes XmlTransform build tasks to transform our web.config based on the current configuration. This week we started migrating to MVC5 and I noticed that when we add a MVC controller or View the web.config gets overwritten to our base template and seems to ignore the current config. I narrowed it down using procmon to either msbuild or devenv modifying the file but Ive searched hi and low on the web and cant find any good documentation or reference. Is this the expected behavior? Can we hook into the scaffolding somewhere to run our transform after the pieces are generated and added?

**Comment by jeffschwMSFT** [comment]
Please create an issue in https://developercommunity.visualstudio.com/home.  We track all our .NET Framework issues there.  Please link it here and I can help route it to the right team.

**Comment by jamespack** [comment]
Thanks @jeffschwMSFT 

https://developercommunity.visualstudio.com/t/MVC-Scaffolding-and-XMLTransforms----Web/10236295

**Comment by jeffschwMSFT** [comment]
Thanks, I have made sure that it is assigned to the right team.
