### ISSUE TITLE
LdapConnection Bind() takes longer on Windows 11

### ISSUE THREAD

**Issue by awdorrin** [dotnet/runtime#79836]
The following code takes ~1 second to bind on Windows 10, but ~44.6 seconds to bind on Windows 11.

```
        static bool AuthenticateUser(string domainName, string userName, string password)
        {
            try
            {
                DateTime start = DateTime.Now;
                NetworkCredential nc = new NetworkCredential(userName, password);
                LdapDirectoryIdentifier ldi = new LdapDirectoryIdentifier(domainName, 3269); //636
                LdapConnection ldapConnection = new LdapConnection(ldi, nc, AuthType.Basic);
                ldapConnection.Bind();
                Console.WriteLine("User {0} authenticated in {1}", userName, (DateTime.Now - start));
                return true;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return false;
            }
        }
```

I assume that the time is due to negotiating SSL layers, and timing out.
I can't find a way to force TLS1.2 (which worked for issues like this with other services)
If there were a way for force SslProtocol.Tls12, I assume this would resolve the issue.
(But guessing, because I haven't been able to test with Wireshark due to corporate permissions on my laptop...)

**Comment by steveharter** [comment]
We need to verify; TLS1.3 on Window 11 causing a potential regression.

**Comment by buyaa-n** [comment]
> I can't find a way to force TLS1.2 (which worked for issues like this with other services)
> If there were a way for force SslProtocol.Tls12, I assume this would resolve the issue. 

This doc might help: [Managing SSL/TLS Protocols and Cipher Suites for AD FS](https://learn.microsoft.com/en-US/windows-server/identity/ad-fs/operations/manage-ssl-protocols-in-ad-fs)

It has section like [Enable and Disable SSL 3.0](https://learn.microsoft.com/en-US/windows-server/identity/ad-fs/operations/manage-ssl-protocols-in-ad-fs#enable-and-disable-ssl-30) and [Enable and Disable TLS 1.2](https://learn.microsoft.com/en-US/windows-server/identity/ad-fs/operations/manage-ssl-protocols-in-ad-fs#enable-and-disable-tls-12)
