### ISSUE TITLE
[API Proposal]: `MemoryStream.GetString(Encoding? encoding)`

### ISSUE THREAD

**Issue by FranklinWhale** [dotnet/runtime#79830]
### Background and motivation

There are currently 3 [common](https://stackoverflow.com/questions/3542237/quick-way-to-get-the-contents-of-a-memorystream-as-an-ascii-string) [ways](https://stackoverflow.com/questions/78181/how-do-you-get-a-string-from-a-memorystream) to get a string from a `MemoryStream`:

1. `encoding.GetString(memoryStream.ToArray())`
2. `streamReader.ReadToEnd()`
3. `memoryStream.TryGetBuffer(out var buffer); encoding.GetString(buffer.Array!, buffer.Offset, buffer. Count);`

However, both 1 and 2 require extra allocations while 3 only works when the buffer is exposable.

By providing `MemoryStream.GetString(Encoding? encoding)`, `encoding.GetString` can be applied to the internal buffer without exposing it.

### API Proposal

```csharp
// inside System.IO.MemoryStream;

public string GetString(Encoding? encoding) =>
    (encoding ?? Encoding.Default).GetString(_buffer, _origin, _length - _origin);
```

### API Usage

```csharp
var stream = new MemoryStream();
// Something is written to the stream
var str = stream.GetString();
```

### Alternative Designs

An extension method like this:

```csharp
public static string GetString(this MemoryStream stream, Encoding? encoding)
{
    encoding ??= Encoding.Default;
    if (stream.TryGetBuffer(out var buffer))
    {
        return encoding.GetString(buffer.Array!, buffer.Offset, buffer.Count);
    }
    using var reader = new StreamReader(stream, encoding);
    return reader.ReadToEnd();
}
```

### Risks

I think the proposed API has no risk.

**Comment by Tornhoof** [comment]
Why Memory Stream? How often do you really work with a MemoryStream, outside of tests?
Usually the input streams are something else, like FileStream or HttpRequestStream. These streams would then require/prefer async methods.

**Comment by FranklinWhale** [comment]
I use `MemoryStream` with `Utf8JsonWriter` (https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/use-dom-utf8jsonreader-utf8jsonwriter?pivots=dotnet-7-0#use-utf8jsonwriter), but I think there are other cases where a `MemoryStream` may be storing characters in bytes.

**Comment by Tornhoof** [comment]
If you're using MS for that and are concerned about allocations, as this is one of the reasons you want a better api, you might want to look at RecyclableMemoryStream (https://www.nuget.org/packages/Microsoft.IO.RecyclableMemoryStream) or implement your own   IBufferWriter.
For the rare cases I need an temporary stream for such operations, I use that RecyclableMemoryStream and streamreader (your suggestion 2). For more performance critical code, I tend to have custom buffer writers.

**Comment by adamsitnik** [comment]
Hi @FranklinWhale

`MemoryStream` is a general purpose APIs. Some users might want to use the underlying byte buffer to decode a string, some to perform a binary deserialization, while others to do something completely different. That is why we provide methods like `MemoryStream.TryGetBuffer` so the users can do whatever they want. 

> while 3 only works when the buffer is exposable.

Buffer is exposable by default, user would need to create `MemoryStream` from a byte buffer and explicitly ask for it to not be exposed. This should be rare and moreover `TryGetBuffer` will just return `false` in such cases rather than throwing an exception, so you can gracefully handle it.

```cs
static string GetString(this MemoryStream memoryStream, Encoding encoding)
    => memoryStream.TryGetBuffer(out var buffer)
        ? encoding.GetString(buffer.Array!, buffer.Offset, buffer.Count) // hot path
        : encoding.GetString(memoryStream.ToArray()); // slow path, should be very rare, but could be optimized with ArrayPool
```

Having said that, I am going to close the issue. Thank you for your proposal!
