### ISSUE TITLE
Non-default property setter in class bound with appsettings.json, no longer loading in .NET 7

### ISSUE THREAD

**Issue by avinashtauro-arctechinfo** [dotnet/runtime#79848]
### Description

In .NET 7,  a property setter containing code is not called when injecting IOptions<T>. The value in appsettings in no longer loaded into the class object.

If the property setter has the default definition, it works as expected.

### Reproduction Steps

------------------------------------------------------------------------------------------
1. Add the following entry in appsettings.json
------------------------------------------------------------------------------------------
```json
"EmailNotificationSetting": {
    "EmailMessages": {
      "Test": {        
        "BodyLines": [
          "Dear Avinash,",
          "<br />",
          "Thank you for registering your request with us.",
          "<br />",
          "Your request is currently pending with your project leader for approval.",
          "<br />",
          "Please find attached documents for requisition details."
        ]
      }
    }
}
```
------------------------------------------------------------------------------------------
2. Add classes EmailMessageSetting.cs & EmailNotificationSetting.cs
------------------------------------------------------------------------------------------
```C#
public class EmailMessageSetting
{
    private List<string> _bodyLines;
    public List<string> BodyLines
    {
        get => _bodyLines ?? new List<string> {Body};
         set
        {
            _bodyLines = value;
            Body = string.Concat(value);
        }
    }

    public string Body { get; set; }
}

public class EmailNotificationSetting
{
    public Dictionary<string, EmailMessageSetting> EmailMessages { get; set; }
}
```

------------------------------------------------------------------------------------------
3. Inject this as below
```C#
services.Configure<EmailNotificationSetting>(configuration.GetSection(nameof(EmailNotificationSetting)));
```
------------------------------------------------------------------------------------------
4. Inject this class as below in any class
------------------------------------------------------------------------------------------
```C#
private readonly EmailNotificationSetting _mailNotificationSetting;

public EmailMessageService(IOptions<EmailNotificationSetting> emailNotificationSettingAccessor)
{
    _mailNotificationSetting = emailNotificationSettingAccessor.Value;

    var x = _mailNotificationSetting.Body;
    ...
}
```
------------------------------------------------------------------------------------------

### Expected behavior

Expected behavior => var x below should contain a string as below

Dear Avinash<br />Thank you for registering your request with us.<br />Your request is currently pending with your project // leader for approval.<br />Please find attached documents for requisition details.

### Actual behavior

Actual behavior => var x  is null

### Regression?

This works as expected in .NET 5 and .NET 6

### Known Workarounds

In .NET 7, If I change the property definition to below, the setter is called correctly.
public List<string> BodyLines { get; set; }

### Configuration

.NET 7
Windows 11 Pro (Version 10.0.22621 Build 22621)
x64

**Comment by avinashtauro-arctechinfo** [comment]
I am unable to edit the label. The correct area label would be **area-System.Configuration**

**Comment by tarekgh** [comment]
I confirmed this is a dup to https://github.com/dotnet/runtime/issues/79904. We are going to fix this issue in the next .NET 7.0 servicing release.
