### ISSUE TITLE
[6.0] .NET 4.8 queue removed

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#79858]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=111123
Build error leg or test failing: Libraries Build windows net48 x86 Release / Send to Helix
Pull requests:
  - #79620
  - #79549

## Error Message

```json
{
  "ErrorMessage": "Helix queue windows.10.amd64.client21h1.open was set for estimated removal date of 2022-12-13.",
  "BuildRetry": false
}
```

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[131741](https://dev.azure.com/dnceng-public/public/_build/results?buildId=131741)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/131741/logs/162)||
|[131742](https://dev.azure.com/dnceng-public/public/_build/results?buildId=131742)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/131742/logs/36)||
|[130236](https://dev.azure.com/dnceng-public/public/_build/results?buildId=130236)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/130236/logs/231)||
|[130234](https://dev.azure.com/dnceng-public/public/_build/results?buildId=130234)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/130234/logs/37)||
|[129718](https://dev.azure.com/dnceng-public/public/_build/results?buildId=129718)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/129718/logs/238)||
|[129717](https://dev.azure.com/dnceng-public/public/_build/results?buildId=129717)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/129717/logs/48)||
|[129417](https://dev.azure.com/dnceng-public/public/_build/results?buildId=129417)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/129417/logs/231)||
|[129415](https://dev.azure.com/dnceng-public/public/_build/results?buildId=129415)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/129415/logs/53)||
|[127972](https://dev.azure.com/dnceng-public/public/_build/results?buildId=127972)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/127972/logs/38)||
|[127971](https://dev.azure.com/dnceng-public/public/_build/results?buildId=127971)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/127971/logs/220)||
|[126228](https://dev.azure.com/dnceng-public/public/_build/results?buildId=126228)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/126228/logs/57)||
|[126227](https://dev.azure.com/dnceng-public/public/_build/results?buildId=126227)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/126227/logs/211)||
|[124558](https://dev.azure.com/dnceng-public/public/_build/results?buildId=124558)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/124558/logs/236)||
|[124553](https://dev.azure.com/dnceng-public/public/_build/results?buildId=124553)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/124553/logs/53)||
|[123908](https://dev.azure.com/dnceng-public/public/_build/results?buildId=123908)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/123908/logs/646)|dotnet/runtime#80152|
|[120353](https://dev.azure.com/dnceng-public/public/_build/results?buildId=120353)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/120353/logs/1340)|dotnet/runtime#79997|
|[123231](https://dev.azure.com/dnceng-public/public/_build/results?buildId=123231)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/123231/logs/436)|dotnet/runtime#80121|
|[123010](https://dev.azure.com/dnceng-public/public/_build/results?buildId=123010)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/123010/logs/47)||
|[123011](https://dev.azure.com/dnceng-public/public/_build/results?buildId=123011)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/123011/logs/216)||
|[122431](https://dev.azure.com/dnceng-public/public/_build/results?buildId=122431)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/122431/logs/238)||
|[122432](https://dev.azure.com/dnceng-public/public/_build/results?buildId=122432)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/122432/logs/34)||
|[122166](https://dev.azure.com/dnceng-public/public/_build/results?buildId=122166)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/122166/logs/50)||
|[122165](https://dev.azure.com/dnceng-public/public/_build/results?buildId=122165)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/122165/logs/197)||
|[121887](https://dev.azure.com/dnceng-public/public/_build/results?buildId=121887)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/121887/logs/216)||
|[121885](https://dev.azure.com/dnceng-public/public/_build/results?buildId=121885)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/121885/logs/40)||
|[121563](https://dev.azure.com/dnceng-public/public/_build/results?buildId=121563)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/121563/logs/214)||
|[121561](https://dev.azure.com/dnceng-public/public/_build/results?buildId=121561)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/121561/logs/53)||
|[121164](https://dev.azure.com/dnceng-public/public/_build/results?buildId=121164)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/121164/logs/203)||
|[121158](https://dev.azure.com/dnceng-public/public/_build/results?buildId=121158)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/121158/logs/40)||
|[121018](https://dev.azure.com/dnceng-public/public/_build/results?buildId=121018)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/121018/logs/505)|dotnet/runtime#80030|
|[120743](https://dev.azure.com/dnceng-public/public/_build/results?buildId=120743)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/120743/logs/217)||
|[120738](https://dev.azure.com/dnceng-public/public/_build/results?buildId=120738)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/120738/logs/53)||
|[120197](https://dev.azure.com/dnceng-public/public/_build/results?buildId=120197)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/120197/logs/233)||
|[120196](https://dev.azure.com/dnceng-public/public/_build/results?buildId=120196)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/120196/logs/43)||
|[119881](https://dev.azure.com/dnceng-public/public/_build/results?buildId=119881)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/119881/logs/209)||
|[119879](https://dev.azure.com/dnceng-public/public/_build/results?buildId=119879)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/119879/logs/37)||
|[119682](https://dev.azure.com/dnceng-public/public/_build/results?buildId=119682)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/119682/logs/193)||
|[119677](https://dev.azure.com/dnceng-public/public/_build/results?buildId=119677)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/119677/logs/38)||
|[119490](https://dev.azure.com/dnceng-public/public/_build/results?buildId=119490)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/119490/logs/222)||
|[119482](https://dev.azure.com/dnceng-public/public/_build/results?buildId=119482)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/119482/logs/37)||
|[119163](https://dev.azure.com/dnceng-public/public/_build/results?buildId=119163)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/119163/logs/208)||
|[119161](https://dev.azure.com/dnceng-public/public/_build/results?buildId=119161)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/119161/logs/41)||
|[118513](https://dev.azure.com/dnceng-public/public/_build/results?buildId=118513)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/118513/logs/42)||
|[118514](https://dev.azure.com/dnceng-public/public/_build/results?buildId=118514)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/118514/logs/201)||
|[117717](https://dev.azure.com/dnceng-public/public/_build/results?buildId=117717)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/117717/logs/166)||
|[117712](https://dev.azure.com/dnceng-public/public/_build/results?buildId=117712)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/117712/logs/36)||
|[110778](https://dev.azure.com/dnceng-public/public/_build/results?buildId=110778)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/110778/logs/1305)|dotnet/runtime#79549|
|[111123](https://dev.azure.com/dnceng-public/public/_build/results?buildId=111123)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/111123/logs/1282)|dotnet/runtime#79620|
|[117077](https://dev.azure.com/dnceng-public/public/_build/results?buildId=117077)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/117077/logs/560)|dotnet/runtime#79854|
|[116831](https://dev.azure.com/dnceng-public/public/_build/results?buildId=116831)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/116831/logs/38)||
|[116830](https://dev.azure.com/dnceng-public/public/_build/results?buildId=116830)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/116830/logs/204)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|12|51|

**Comment by akoeplinger** [comment]
Related issue: https://github.com/dotnet/runtime/issues/79646
There's a PR for 6.0 to update the queue name: https://github.com/dotnet/runtime/pull/79665

**Comment by akoeplinger** [comment]
This was fixed by https://github.com/dotnet/runtime/pull/79665
