### ISSUE TITLE
[macOS] cannot debug / stop at breakpoints when app sandbox is enabled

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#79852]
_From @tipa on Mon, 14 Nov 2022 22:18:23 GMT_

### Steps to Reproduce

1. Create new .NET macOS app (doesn't matter if .net6 or .net7)
2. Enable app sandbox in Entitlements.plist (see snippet below)
3. Create breakpoint somewhere in code
4. Start debugging

```
<key>com.apple.security.app-sandbox</key>
<true/>
```

### Expected Behavior
Code execution stops on breakpoints and developer can inspect variables etc
![Screenshot 2022-11-14 at 23 15 52](https://user-images.githubusercontent.com/2863198/201779511-2b15e504-3246-474f-8572-2715d6e099be.png)

### Actual Behavior
No breakpoint is hit, breakpoints show as inactive
![Screenshot 2022-11-14 at 23 14 49](https://user-images.githubusercontent.com/2863198/201779362-b8f3094d-b25d-42e4-a135-cab2f796881f.png)

### Comments
Debugging and hitting breakpoints worked without problems in legacy Xamarin, even when App Sandbox was enabled

### Environment
<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac
Version 17.4 (build 2406)
Installation UUID: 39a1422f-61e9-466b-9c35-a80fcd9a2d23

Runtime
.NET 6.0.9 (64-bit)
Architecture: Arm64

Roslyn (Language Service)
5.4.0-3.22461.4+8ab250290a4010c11a21521f78dbc87dbb7aac81

NuGet
Version: 6.3.1.1

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.100/Sdks
SDK Versions:
	7.0.100
	6.0.403
	6.0.402
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64)
SDK Versions:
	3.1.425
	3.1.424

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.0
	7.0.0-rc.2.22472.3
	6.0.11
	6.0.10

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	3.1.31
	3.1.30

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Not Installed

Microsoft Build of OpenJDK
Java SDK: Not Found

Eclipse Temurin JDK
Java SDK: Not Found

Android SDK Manager
Version: 17.4.0.54
Hash: 6eabb9e
Branch: remotes/origin/d17-4
Build date: 2022-11-02 23:47:26 UTC

Android Device Manager
Version: 0.0.0.1206
Hash: 886af39
Branch: 886af39
Build date: 2022-11-02 23:47:26 UTC

Apple Developer Tools
Xcode 14.1 (21534.1)
Build 14B47b

Xamarin.Mac
Version: 8.12.0.2 (Visual Studio Community)
Hash: 87f98a75e
Branch: d17-3
Build date: 2022-07-25 20:18:54-0400

Xamarin.iOS
Version: 16.0.0.72 (Visual Studio Community)
Hash: 6756a1146
Branch: release/6.0.4xx-xcode14
Build date: 2022-09-21 08:51:06-0400

Xamarin Designer
Version: 17.4.0.136
Hash: d49c9ff6d3
Branch: remotes/origin/d17-4
Build date: 2022-11-02 23:47:17 UTC

Build Information
Release ID: 1704002406
Git revision: dfb45c1152306f0d5f77334f9d026b0aadb7ec90
Build date: 2022-11-02 23:44:22+00
Build branch: release-17.4
Build lane: release-17.4

Operating System
Mac OS X 13.0.1
Darwin 22.1.0 Darwin Kernel Version 22.1.0
    Sun Oct  9 20:14:30 PDT 2022
    root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 arm64

```

</details>

### Example Project (If Possible)
[test.zip](https://github.com/xamarin/xamarin-macios/files/10007482/test.zip)

_Copied from original issue xamarin/xamarin-macios#16753_

**Comment by rolfbjarne** [comment]
_From @AlainRogister on Fri, 16 Dec 2022 12:08:05 GMT_

I have the same problem and the preview 15.2 doesn't resolve the problem

**Comment by rolfbjarne** [comment]
_From @rolfbjarne on Fri, 16 Dec 2022 14:19:33 GMT_

Does it work if you enable networking entitlements?

**Comment by rolfbjarne** [comment]
_From @AlainRogister on Fri, 16 Dec 2022 15:31:38 GMT_

This is my Entitlements. What key are you talking about exactly ?

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.inherit</key>
	<true/>
	<key>com.apple.security.files.bookmarks.app-scope</key>
	<true/>
	<key>com.apple.security.files.bookmarks.document-scope</key>
	<true/>
	<key>com.apple.security.smartcard</key>
	<true/>
	<key>com.apple.security.app-sandbox</key>
	<true/>
	<key>com.apple.security.network.server</key>
	<true/>
	<key>com.apple.security.network.client</key>
	<true/>
	<key>com.apple.security.print</key>
	<true/>
	<key>com.apple.security.personal-information.location</key>
	<true/>
	<key>com.apple.security.files.user-selected.read-write</key>
	<true/>
	<key>com.apple.security.files.downloads.read-write</key>
	<true/>
	<key>com.apple.security.personal-information.addressbook</key>
	<true/>
	<key>com.apple.developer.maps</key>
	<true/>
	<key>com.apple.security.device.camera</key>
	<true/>
	<key>com.apple.security.device.microphone</key>
	<true/>
</dict>
</plist>

**Comment by rolfbjarne** [comment]
_From @tipa on Fri, 16 Dec 2022 16:10:10 GMT_

@rolfbjarne are you able to reproduce the problem using the example project provided above?

**Comment by rolfbjarne** [comment]
_From @AlainRogister on Fri, 16 Dec 2022 16:19:16 GMT_

no, I tried with my project for which we had this bug.

To be able to debug, we had to set SandBox to False.

When set to true, impossible to debug.

I was hoping this would be fixed with the 15.2 preview but the problem is still there.

I specify that it is for NET 6 or 7 projects and that it is a macos application

**Comment by rolfbjarne** [comment]
_From @AlainRogister on Mon, 19 Dec 2022 13:39:06 GMT_

Do you have news for me ?

**Comment by rolfbjarne** [comment]
_From @AlainRogister on Mon, 19 Dec 2022 13:46:21 GMT_

I have the same problem with this application Test.

Impossible to debug

**Comment by rolfbjarne** [comment]
_From @rolfbjarne on Tue, 20 Dec 2022 14:44:06 GMT_

Yes, I can reproduce, even after enabling the networking entitlements (com.apple.security.network.client and com.apple.security.network.server).

This seems to be an issue between CoreCLR and the IDE, so I'm moving this to dotnet/runtime.

This might be related: https://github.com/dotnet/coreclr/pull/21068?

**Comment by AlainRogister** [comment]
Thank you Rolf ! I supposed that this correction will be in the 17.5 preview 3 ?

De : Rolf Bjarne Kvinge ***@***.***>
Date : mardi, 20 décembre 2022 à 15:44
À : dotnet/runtime ***@***.***>
Cc : AlainRogister ***@***.***>, Mention ***@***.***>
Objet : Re: [dotnet/runtime] [macOS] cannot debug / stop at breakpoints when app sandbox is enabled (Issue #79852)

From @rolfbjarne<https://github.com/rolfbjarne> on Tue, 20 Dec 2022 14:44:06 GMT

Yes, I can reproduce, even after enabling the networking entitlements (com.apple.security.network.client and com.apple.security.network.server).

This seems to be an issue between CoreCLR and the IDE, so I'm moving this to dotnet/runtime.

This might be related: dotnet/coreclr#21068<https://github.com/dotnet/coreclr/pull/21068>?

**Comment by hoyosjs** [comment]
cc: @mikem8361, @odhanson 

I wonder if VS/Xamarin is trying to use the correct API in the DBG shim that accounts for application group.

**Comment by odhanson** [comment]
> cc: @mikem8361, @odhanson
> 
> I wonder if VS/Xamarin is trying to use the correct API in the DBG shim that accounts for application group.

I wasn't aware .NET 6/7 changed the way they debug Xamarin apps.

We can verify if VS is now using dbgshim by doing the following:
1. Add the following application group
```
    <key>com.apple.security.application-groups</key>
    <array>
        <string>[App Group Id]</string>
    </array>
```
2. Create a file inside the application bundle's MacOS folder, named Foo.coreclr-debug-config.json. Where Foo is the name of the application. Inside the json file, add the following:
```
    {
        "applicationGroupId" : "[App Group Id]"
    }
```
You will need to replace the [App Group Id] with an application group id specific for your product.

This should allow the vs debugger to debug the sandboxed app.

**Comment by AlainRogister** [comment]
Hi,
I installed 17.5 build 1701 yesterday and I still have the problem.
Is it fixed and not put in this version ?
Alain


De : Rolf Bjarne Kvinge ***@***.***>
Date : mardi, 20 décembre 2022 à 15:44
À : dotnet/runtime ***@***.***>
Cc : AlainRogister ***@***.***>, Mention ***@***.***>
Objet : Re: [dotnet/runtime] [macOS] cannot debug / stop at breakpoints when app sandbox is enabled (Issue #79852)

From @rolfbjarne<https://github.com/rolfbjarne> on Tue, 20 Dec 2022 14:44:06 GMT

Yes, I can reproduce, even after enabling the networking entitlements (com.apple.security.network.client and com.apple.security.network.server).

This seems to be an issue between CoreCLR and the IDE, so I'm moving this to dotnet/runtime.

This might be related: dotnet/coreclr#21068<https://github.com/dotnet/coreclr/pull/21068>?

**Comment by mikem8361** [comment]
Did Oded suggestion work?  We are trying to determine if the problem is VS4Mac, dbgshim or just documentation for how to debug in a MacOS sandbox.

**Comment by AlainRogister** [comment]
Good morning,

thank you for looking at this problem because we have had this for 4 months and it is still not solved, but it seems to me to be a priority point. WE DON'T KNOW TO DEBUG when the application is sandboxed.

Obviously, if we pull the application from the Sandbox it works (fortunately if not impossible to work) but it is still very frustrating that such a problem is not yet solved.

THANKS

Alain

**Comment by odhanson** [comment]
@mikem8361 did you really mean to close this issue ?

Anyhow, my suggestion was just a manual workaround to verify if the issue is indeed what I think. I am not sure this is what people expect to do, as this feels like regressed functionality from what they had before.

**Comment by AlainRogister** [comment]
absolutely

**Comment by odhanson** [comment]
@AlainRogister 

Did you try my suggestion above?

1. Add the following application group
    <key>com.apple.security.application-groups</key>
    <array>
        <string>[App Group Id]</string>
    </array>
2. Create a file inside the application bundle's MacOS folder, named Foo.coreclr-debug-config.json. Where Foo is the name of the application. Inside the json file, add the following:
    {
        "applicationGroupId" : "[App Group Id]"
    }
* You will need to replace the [App Group Id] with an application group id specific for your product.

This should allow the vs debugger to debug the sandboxed app.

Let us know if this workaround unblocks you

**Comment by tommcdon** [comment]
@odhanson it seems that the debugging/sandbox issue is an app model issue and not a debugger issue.  Is that correct?  If yes should we transfer this over to Visual Studio and/or the SDK?

**Comment by odhanson** [comment]
I don't know. I have no clue how debugging worked before in Xamarin. So I cannot say what was regressed, I know that before, no one was using these APIs for sandbox debugging, other than our internal feature. So if this has changed, then support for this should be done at some level which needs some discussion.

**Comment by tipa** [comment]
The workaround posted above does not work for me. Even if it did, it would be highly impractical because:
- not all of my apps do have an app group id and I don't want to create one just to workaround Visual Studio problems
- the app bundle is located under the bin folder. I have to delete the obj/bin folders dozens of times every day because of other unfixed build issues related to MacOS apps

Building and debugging macOS apps really got painful in the last couple of months. Feels like more issues arise with every Visual Studio update

**Comment by AlainRogister** [comment]
it doesn't work for me either. I don't have an App Group for my app

I completely agree with TIPA, it's not a viable solution.

On the other hand, with preview 17.6 Preview 1, I know how to debug by setting SANDBOX to FALSE

**Comment by tipa** [comment]
It appears that it is only possible to debug when app-sandbox is disabled *and* this line is not present in the csproj:
`    <RuntimeIdentifiers>osx-x64;osx-arm64</RuntimeIdentifiers>
`
However, when removing it, my app is being built and run in "Intel" x86 mode...

**Comment by rolfbjarne** [comment]
You can try this to build for arm64:

> <RuntimeIdentifier>osx-arm64</RuntimeIdentifier>

**Comment by tipa** [comment]
I just noticed that this issue was moved to .NET 9 (as so many of the issues I've reported). I can't believe that this doesn't get higher priority, seems like no-one else is building macOS apps...? Debugging without sandbox is a pain, for a few reasons:
- need to constantly toggle the "sandboxed"  property in my Entitlements when switching from debugging and building an app for release
- my apps are using an SQLite database with the same name in their respective [HOME directory](https://developer.apple.com/documentation/foundation/1413045-nshomedirectory?language=objc). When "sandboxed" mode is off, that directory points to the user's home directory - so to the *same* file, that I have to delete every time I work on another app of mine
- Debugging permission requests (like for Photo library, microphone, calendar etc) is impossible, app crashes right away

**Comment by tommcdon** [comment]
Supporting both profiling and debugging in .NET Core will require work as described in https://github.com/dotnet/runtime/issues/94114#issuecomment-1784761813.  Closing this issue as we will track the work on #94114.
