### ISSUE TITLE
Access Violation in Interop+Sys.ChDir

### ISSUE THREAD

**Issue by HughPH** [dotnet/runtime#79864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

At first I thought this was a fork() issue, but the stack trace is very short:

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshalling.Utf8StringMarshaller+ManagedToUnmanagedIn.Free()
   at Interop+Sys.ChDir(System.String)
Aborted
```

I'm using Pty.Net (https://github.com/microsoft/vs-pty.net) and it fails with this exception when I try to run it in the .net 7.0 runtime. In .net 6.0 everything works fine.

### Expected Behavior

No exception thrown.

### Steps To Reproduce

The following code works fine in .net 6.0 and fails in .net 7.0

```
PtyOptions ptyOptions = new PtyOptions()
		                        {
			                        App = "/bin/bash",
			                        Cols = 80,
			                        Rows = 25,
			                        Cwd = Environment.CurrentDirectory,
		                        };

IPtyConnection connection = await PtyProvider.SpawnAsync(ptyOptions, CancellationToken.None);
```

### Exceptions (if any)

System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

### .NET Version

7.0.101

**Comment by HughPH** [comment]
I expect needs the area-Interop-coreclr label, belonging to @jeffschwMSFT @AaronRobinsonMSFT ?

**Comment by danmoseley** [comment]
I labeled interop, but it's not clear where the bug might be - it might be in the library, which is now somehow exposed.

Could you share a stand-alone repro, if the above is not one? Might be easiest to create a repo for the repro, with the project file too.

**Comment by HughPH** [comment]
> I labeled interop, but it's not clear where the bug might be - it might be in the library, which is now somehow exposed.
> 
> Could you share a stand-alone repro, if the above is not one? Might be easiest to create a repo for the repro, with the project file too.

I could branch vs-pty.net and create two projects, one that fails and one that does not. Would that be helpful?

**Comment by AaronRobinsonMSFT** [comment]
I am dubious the stack above is the full story. Looking at the implementation of the marshaller -- [`Utf8StringMarshaller+ManagedToUnmanagedIn`](https://github.com/dotnet/runtime/blob/8ac3832812f9bc37fba2a66ac8987ca66d381d85/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshalling/Utf8StringMarshaller.cs#L54) -- there doesn't seem to be anything obvious wrong. It is also odd that such a simple signature would find this kind of bug as this marshaller is used everywhere. It would be helpful to see the generated source for `ChDir` and determine the caller. The "Async" call and "fork" does add some interesting avenues for investigation.

@HughPH Is this a consistent repro? Can you also share the bitness and OS you are running on.

**Comment by danmoseley** [comment]
@am11 did you mean to thumbs down?

**Comment by jkotas** [comment]
It is not safe to run managed code in a forked process like this: https://github.com/microsoft/vs-pty.net/blob/9006ac03a8993a82ec82c1e732c79942bdf6ca89/src/Pty.Net/Linux/PtyProvider.cs#L55-L67 . 

We used to have a code like this in the early days of .NET Core. It caused reliability issues e.g. if some other thread triggers GC while the current forked thread is executing between fork and exec. The only way to solve these reliability issues was to move the fork+exec sequence to unmanaged code: https://github.com/dotnet/runtime/issues/14356 .

**Comment by am11** [comment]
@danmoseley, no I misclicked. Was trying to repro it locally but nuget is unable to restore https://www.nuget.org/packages/Pty.Net package with net7.0. Meanwhile saw Aaron comment explaining what's going on.

**Comment by HughPH** [comment]
I'm not using fork() to run managed code, to avoid any confusion.

I'm running Ubuntu 22.10 x64.

I'll see about repro when I get home, ~2-3hrs

**Comment by AaronRobinsonMSFT** [comment]
> I'm not using fork() to run managed code, to avoid any confusion.

Agreed, but that is what Pty.Net is doing, which is incorrect and can cause corruption/instability and should be avoided. The call to [`PtyProvider.SpawnAsync`](https://github.com/microsoft/vs-pty.net/blob/9006ac03a8993a82ec82c1e732c79942bdf6ca89/src/Pty.Net/PtyProvider.cs#L27-L57) calls [`PlatformServices.PtyProvider.StartTerminalAsync`](https://github.com/microsoft/vs-pty.net/blob/9006ac03a8993a82ec82c1e732c79942bdf6ca89/src/Pty.Net/Linux/PtyProvider.cs#L20-L74), which performs a `fork` call and results in the corruption. As @jkotas mentioned this can work if no GC occurs and moves memory. However, if one does occur this can cause corruption as is being observed. The Pty.Net library should be updated to follow the suggestion at https://github.com/dotnet/runtime/issues/79864#issuecomment-1362297208.

**Comment by HughPH** [comment]
@AaronRobinsonMSFT Thanks, I'll fork (the repo) & reproduce and then see if I can work the changes in to vs-pty.net. It might not be this side of xmas, though.

**Comment by AaronRobinsonMSFT** [comment]
Given the use of the `fork`/`exec` pattern in Pty.NET, I am going to close this. If this continues to repro, please tag this issue and we can reopen it.

**Comment by HughPH** [comment]
> Given the use of the `fork`/`exec` pattern in Pty.NET, I am going to close this. If this continues to repro, please tag this issue and we can reopen it.

I'll raise it against the Pty.NET repo, and send a PR if it doesn't get fixed before I get round to it.
