### ISSUE TITLE
Consider extending Linux core dumps format to include code sections

### ISSUE THREAD

**Issue by lt72** [dotnet/runtime#7986]
We need a way to pull core dumps off of machines and debug them standalone (without having to collect end-user binaries).  
Linux core dumps should be debuggable no matter what machine there were generated on. 
It is acceptable to use a symbol server for symbols, but OS and VM code of interest should may be included  in the dump itself, thus reducing the number and type of artifacts that a dev need to gather for a productive investigation.

**Comment by mikem8361** [comment]
The "--full" createdump option or setting COMPlus_DbgMiniDumpType=4 will create dumps with all the modules and state necessary.  As of 3.1 or greater full dumps are not the huge ones than 2.x produced.
