### ISSUE TITLE
Can StringInfo performance be improved?

### ISSUE THREAD

**Issue by hummy123** [dotnet/runtime#79873]
### Description

It is not a huge problem, but I have tried using StringInfo in my text buffer data structure (a Piece Table) as it is helpful for substring by text elements/grapheme clusters. However, I noticed that operations using StringInfo are about 10x slower (2.893 μs vs 24.922 μs in one example when using substring operations). 

That is likely not a huge issue, but I was wondering if performance can possibly be improved. 

I am not sure how the class is implemented, but I think a lookup table may help with faster substrings. The lookup table could be accessed by an array of <int, int> KeyValuePairs where the key is the visible character's position and the value is a pointer to the index where that character starts in the raw string.

Also, I was wondering about StringInfo concatenation which is unexpectedly slow (about 10x slower as well). I don't think the class itself supports concatenation so I concatenate the .String property on two StringInfo objects and convert the string result to another StringInfo object, which may be slow depending on how the class is initialised. 

For example, if the constructor traverses each character, counting each grapheme to produce the LengthInTextElements property, concatenation between two StringInfo objects can be much quicker as the LengthInTextElements property for both is already known and can just be added.

### Regression?

I don't think this is a regression. I have tested both .NET 6.0 and 7.0 where performance is about the same. The StringInfo class (from what I read) had a bug that means it didn't count TextElements properly prior to .NET 5.0, but I haven't been able to test .NET 5.0 where it was fixed.

### Data

(The `insertTimes` and `nearStart/Middle/EndOfTable` parameters below can likely be ignored as that's specific to my data structure.) 

Hardware:
```
BenchmarkDotNet=v0.13.2, OS=Windows 11 (10.0.22000.1335/21H2)
AMD Ryzen 3 5300U with Radeon Graphics, 1 CPU, 8 logical and 4 physical cores
.NET SDK=7.0.101
  [Host]     : .NET 6.0.12 (6.0.1222.56807), X64 RyuJIT AVX2 DEBUG
  Job-VVXMTS : .NET 6.0.12 (6.0.1222.56807), X64 RyuJIT AVX2

InvocationCount=1  UnrollFactor=1 
```

Insert operations with normal string:
```
|                      Method | insertTimes |     Mean |     Error |    StdDev |   Median | Allocated |
|---------------------------- |------------ |---------:|----------:|----------:|---------:|----------:|
|      **InsertIntoTableAtStart** |        **1000** | **2.682 μs** | **0.0625 μs** | **0.1656 μs** | **2.700 μs** |    **2632 B** |
|     InsertIntoTableAtMiddle |        1000 | 2.564 μs | 0.0840 μs | 0.2272 μs | 2.500 μs |    2728 B |
|        InsertIntoTableAtEnd |        1000 | 2.517 μs | 0.0494 μs | 0.1204 μs | 2.500 μs |    2632 B |

```

Insert operations with StringInfo:
```
|                      Method | insertTimes |      Mean |     Error |    StdDev |    Median | Allocated |
|---------------------------- |------------ |----------:|----------:|----------:|----------:|----------:|
|      **InsertIntoTableAtStart** |        **1000** | **24.933 μs** | **1.4922 μs** | **4.3053 μs** | **22.600 μs** |    **6728 B** |
|     InsertIntoTableAtMiddle |        1000 | 26.087 μs | 0.5468 μs | 1.5152 μs | 25.600 μs |    6824 B |
|        InsertIntoTableAtEnd |        1000 | 25.331 μs | 1.6657 μs | 4.8589 μs | 22.600 μs |    6728 B |
```

Substring operations with string:
```
|                      Method | insertTimes |     Mean |     Error |    StdDev |   Median | Allocated |
|---------------------------- |------------ |---------:|----------:|----------:|---------:|----------:|
|  GetSubstringAtStartOfTable |        1000 | 1.957 μs | 0.0965 μs | 0.2558 μs | 1.900 μs |     528 B |
| GetSubstringAtMiddleOfTable |        1000 | 2.600 μs | 0.1383 μs | 0.3764 μs | 2.500 μs |     600 B |
|    GetSubstringAtEndOfTable |        1000 | 2.893 μs | 0.3435 μs | 0.9799 μs | 2.400 μs |     592 B |
```

Substring operations with StringInfo:
```
|                      Method | insertTimes |      Mean |     Error |    StdDev |    Median | Allocated |
|---------------------------- |------------ |----------:|----------:|----------:|----------:|----------:|
|  GetSubstringAtStartOfTable |        1000 | 25.602 μs | 0.5092 μs | 1.1389 μs | 25.400 μs |    5032 B |
| GetSubstringAtMiddleOfTable |        1000 | 27.539 μs | 1.1485 μs | 3.2015 μs | 26.950 μs |    5104 B |
|    GetSubstringAtEndOfTable |        1000 | 24.922 μs | 1.0505 μs | 3.0140 μs | 24.000 μs |    4640 B |
```

### Code to reproduce

I was developing the data structure itself in F# and I think it's a good candidate for testing performance tweaks to the class as the data structure is all about manipulating (substring and concatenating) text.

Here is my repository: https://github.com/hummy123/Functional-Piece-Table/ .

My updated (much more comprehensive) benchmark code is not in all previous commits, but can be found at the following link: https://github.com/hummy123/Functional-Piece-Table/blob/main/PieceTableBenchmarks/InsertBenchmarks.fs .

However, it is worth commenting out everything except the `InsertIntoDocument` and `GetSubstring` benchmarks (in the `Main` EntryPoint at the bottom) as the other ones don't revolve around manipulating the string/StringInfo.

The commit where the string implementation can be tested is `4eeef5f` and the StringInfo implementation can be tested at commit ID `ed9b97c`.

(I can see after an edit looking [here](https://github.com/dotnet/runtime/blob/a9b3898ee4b568cba09236cc71a63faf3ec52eea/src/libraries/System.Private.CoreLib/src/System/Globalization/StringInfo.cs) that a lookup table is already in use, so no faster substrings that way. However, maybe concatenation is something to still consider.)

**Comment by teo-tsirpanis** [comment]
From a quick look your code has room for performance improvements. Instead of creating `StringInfo` objects, can you try using the `StringInfo.GetNextTextElementLength(ReadOnlySpan<char>)` static method? This will allow writing allocation-free code and since you target only .NET 6 you won't have any problem using it.

Also here are links to the commits for easier access:

* https://github.com/hummy123/Functional-Piece-Table/commit/4eeef5f7bde0ecd8aad244da4be2c8f7bfe4f6f8 - string
* https://github.com/hummy123/Functional-Piece-Table/commit/ed9b97c3bd54d0dccb2d5c0a4db934fc393f1648 - `StringInfo`

**Comment by hummy123** [comment]
Hi @teo-tsirpanis . Thanks for the time you took reviewing my code and the advice.

I thought about the problem a little more after posting this issue and came up with a solution giving me good performance in the usual case.

The two operations I needed were concatenation and substring, so I created a sum type/discriminated union that abstracts over both of these operations.

When the StringInfo object has a length equal to the original string, we know that there are no grapheme clusters so can use a normal string for fast operations and a StringInfo only if we need to handle clusters.

This solution works well for me since my text buffer stores text nodes with a length limit of 1024, so it's only in the nodes where clusters are that face a slowdown (a really nitpicky one to be honest) and I'm happy with that.

Here is my code for the type for reference: https://github.com/hummy123/Functional-Piece-Table/blob/main/src/UnicodeString.fs .

I think in OOP terms (if the idea is thought of is deemed worth implementing in the runtime), the abstraction would likely use an interface (forward the methods to work on a normal string if there are no clusters) rather than a discriminated union, but to be honest the performance difference is just a few microseconds and not likely impactful.

Happy for this issue to be closed.
