### ISSUE TITLE
Convert to GeneratedRegexAttribute fixer should preserve references to const string fields

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#79895]
Regex patterns typically contain plenty of backslashes. The fixer doubles them up. Consider
```c#
    private const string patt = @"\s*";
    private static Regex r1 = new Regex(patt);
```
run the fixer, you get
```c#
    [GeneratedRegex("\\s*")]
    private static partial Regex MyRegex();
```
it would have been clearer to use an @ string like this:
```c#
    [GeneratedRegex(@"\s*")]
    private static partial Regex MyRegex();
```
that might not seem a big deal, but now consider this output from running it on a particular regex in dotnet/msbuild
```c#
            [GeneratedRegex("((?<=@\\(\\s*[A-Za-z_][A-Za-z_0-9\\-]*\\s*->\\s*'[^']*)%\\(\\s* (?<ITEM_SPECIFICATION>(?<ITEM_TYPE>[A-Za-z_][A-Za-z_0-9\\-]*)\\s*\\.\\s*)? (?<NAME>[A-Za-z_][A-Za-z_0-9\\-]*) \\s*\\)(?![^']*'(\\s*,\\s*'[^']*')?\\s*\\))) | ((?<!@\\(\\s*[A-Za-z_][A-Za-z_0-9\\-]*\\s*->\\s*'[^']*)%\\(\\s* (?<ITEM_SPECIFICATION>(?<ITEM_TYPE>[A-Za-z_][A-Za-z_0-9\\-]*)\\s*\\.\\s*)? (?<NAME>[A-Za-z_][A-Za-z_0-9\\-]*) \\s*\\)(?=[^']*'(\\s*,\\s*'[^']*')?\\s*\\))) | ((?<!@\\(\\s*[A-Za-z_][A-Za-z_0-9\\-]*\\s*->\\s*'[^']*)%\\(\\s* (?<ITEM_SPECIFICATION>(?<ITEM_TYPE>[A-Za-z_][A-Za-z_0-9\\-]*)\\s*\\.\\s*)? (?<NAME>[A-Za-z_][A-Za-z_0-9\\-]*) \\s*\\)(?![^']*'(\\s*,\\s*'[^']*')?\\s*\\)))", RegexOptions.ExplicitCapture | RegexOptions.Compiled | RegexOptions.IgnorePatternWhitespace)]
            private static partial Regex MyRegex1();
```
which is considerably less easy to read than the below, which can also be pasted into a regex explainer site, eg.
```c#
            [GeneratedRegex(@"((?<=@\(\s*[A-Za-z_][A-Za-z_0-9\-]*\s*->\s*'[^']*)%\(\s* (?<ITEM_SPECIFICATION>(?<ITEM_TYPE>[A-Za-z_][A-Za-z_0-9\-]*)\s*\.\s*)? (?<NAME>[A-Za-z_][A-Za-z_0-9\-]*) \s*\)(?![^']*'(\s*,\s*'[^']*')?\s*\))) | ((?<!@\(\s*[A-Za-z_][A-Za-z_0-9\-]*\s*->\s*'[^']*)%\(\s* (?<ITEM_SPECIFICATION>(?<ITEM_TYPE>[A-Za-z_][A-Za-z_0-9\-]*)\s*\.\s*)? (?<NAME>[A-Za-z_][A-Za-z_0-9\-]*) \s*\)(?=[^']*'(\s*,\s*'[^']*')?\s*\))) | ((?<!@\(\s*[A-Za-z_][A-Za-z_0-9\-]*\s*->\s*'[^']*)%\(\s* (?<ITEM_SPECIFICATION>(?<ITEM_TYPE>[A-Za-z_][A-Za-z_0-9\-]*)\s*\.\s*)? (?<NAME>[A-Za-z_][A-Za-z_0-9\-]*) \s*\)(?![^']*'(\s*,\s*'[^']*')?\s*\)))", RegexOptions.ExplicitCapture | RegexOptions.Compiled | RegexOptions.IgnorePatternWhitespace)]
            private static partial Regex MyRegex1();
```
If Roslyn doesn't have a built-in way to translate, I imagine the fixer would replace all `\\` with `\` and put an `@` on the front.

**Comment by stephentoub** [comment]
This should have been fixed by https://github.com/dotnet/runtime/pull/78172. Was it not?

**Comment by danmoseley** [comment]
No, that only fixed the literal case --- `new Regex(@"\s*");`

The tests added in that change demonstrate that it does _not_ work for fields/locals -- note that the @ is lost here:

https://github.com/dotnet/runtime/blob/7853356ab6989eba20f8cb67abe174e2c0a401ac/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/UpgradeToGeneratedRegexAnalyzerTests.cs#L892

the code goes here
https://github.com/dotnet/runtime/blob/7853356ab6989eba20f8cb67abe174e2c0a401ac/src/libraries/System.Text.RegularExpressions/gen/UpgradeToGeneratedRegexCodeFixer.cs#L277-L284

and argument.Value is a LocalReferenceOperation or FieldReferenceOperation, which are not ILiteralOperation's, so the condition is not satisfied.

**Comment by stephentoub** [comment]
> No, that only fixed the literal case

Right. You're instead talking about a case where it's referring to the a const string defined separately? I think such a case should generate code that refers to the const if its in scope or else the fix shouldn't be offered. We shouldn't be duplicating the literal, regardless of slashes.

**Comment by danmoseley** [comment]
> I think such a case should generate code that refers to the exact same const if its in scope or else the fix shouldn't be offered.

That sounds good to me.
