### ISSUE TITLE
running "Convert to GeneratedRegexAttribute" fixer wants to fix all kinds of other things

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#79892]
I built the fixer from ca5bb9318a13c3710aed44067e93785133ddd7df (ie, dotnet/runtime today) and put it into `Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.1\analyzers\dotnet\cs` so that VS 2022 uses it.

I then cloned dotnet/msbuild, opened the solution in VS2022 17.4.3, built everything, then opened Expander.cs here
https://github.com/dotnet/msbuild/blob/main/src/Build/Evaluation/Expander.cs#L3018

I hit Ctrl-. and choose  "Convert to GeneratedRegexAttribute" and this is what I get -- it wants to adjust many unrelated things, as below.

I'm not sure what's governing this -- in the repo's editor config, for example I see `csharp_style_var_for_built_in_types = false:suggestion` but if anything that suggests it ought to prefer `String` to `string`? Besides the fact i don't want it to touch any of these things. Is this a VS bug?

![image](https://user-images.githubusercontent.com/6385855/209019612-88d7bfb2-34cd-46ba-bc8f-6ca922e393a6.png)

**Comment by danmoseley** [comment]
@CyrusNajmabadi do you see anything in https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.RegularExpressions/gen/UpgradeToGeneratedRegexCodeFixer.cs that would cause it to trigger this kind of "global cleanup of the class" rather than just the specific edit it intends?

**Comment by CyrusNajmabadi** [comment]
Don't add the simplifier annotation. Or, if you do, don't add it to something as big as the typedecl. 

I'm not in from of a computer, but there's likely more info I can add later.  But this is the cause and the thing to change right away.

**Comment by danmoseley** [comment]
Testing manually, that seems to fix it. (I wonder whether there is a reason it was put there.)

Not sure how to test it though, as the simplistic test below passes without the change - perhaps it needs an editorconfig or equivalent passed in somehow.
https://github.com/dotnet/runtime/compare/main...danmoseley:runtime:Simplifier?expand=1

**Comment by meziantou** [comment]
I think it has been copied from https://github.com/meziantou/Meziantou.Analyzer/blob/fbcf834a326e8fab69a24405b8d494bcd0d7a8ec/src/Meziantou.Analyzer/Rules/UseRegexSourceGeneratorFixer.cs#L88. There is no valid reason to add this annotation on the syntax node as it would impact all children. Note that this code is the result of a lot of attempts to get the expected result, so there may be some leftovers such as this one.

If I well remember what I was trying to do here, I was expecting modifiers to be sorted correctly. But I don't think this is useful as the `partial` keyword must be right before the `class`/`struct` keyword.
