### ISSUE TITLE
Daemon support for .NET Core

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#799]
Consider support analogous to what ServiceBase offers for Windows services. Either a library or sample. Need to understand how we could depend on Mono.Posix if we depend on it.

This is not committed for 2.1

**Comment by scalablecory** [comment]
ASP.NET Core has the `IHostedService` feature which partially satisfies this. CC @Pilchie

**Comment by Pilchie** [comment]
@scalablecory I'm not actually sure what beyond the systemd support for services this would track.  @danmosemsft - worth keeping, or close based on systemd support?

**Comment by KalleOlaviNiemitalo** [comment]
> In fact even OnPause() and OnResume() can be potentially implemented through SIGSTOP and SIGCONT.

SIGSTOP cannot be caught, so OnPause() would not be called. SIGTSTP is the more polite request, but I don't know whether systemd even has a pause concept. <https://www.freedesktop.org/software/systemd/man/systemd.kill.html>

**Comment by ericstj** [comment]
Closing per support in Microsoft.Extensions.Hosting.Systemd
