### ISSUE TITLE
How do I get a COM object in Runsimpersonated?

### ISSUE THREAD

**Issue by JeanRasin** [dotnet/runtime#79900]
How do I get a COM object in Runsimpersonated in NET 6.0?

```
WindowsIdentity.RunImpersonated(windowsIdentity.AccessToken, () =>
{
    Type? peepTypeFromId = Type.GetTypeFromProgID("Wppeep.Document", true);
});
```
Returns an error (0x800401F3 (CO_E_CLASSSTRING)). There is definitely data in the registry.

**Comment by AaronRobinsonMSFT** [comment]
> Returns an error (0x800401F3 (CO_E_CLASSSTRING)). There is definitely data in the registry.

I don't recall the all of the ProgID logic, but I though this was the "Unknown ProgID" error. Along with the CLSID, you also need to register the ProgID. It would be helpful if you could share your complete COM registration. Another question, is the COM server written in managed or unmanaged code?

Details on the COM specific side can be found at [Delegation and Impersonation](https://learn.microsoft.com/windows/win32/com/delegation-and-impersonation).

**Comment by JeanRasin** [comment]
The COM server is written in Microsoft C++. 
![image](https://user-images.githubusercontent.com/17027319/209545213-d0fb5a86-1620-475d-b03e-71bd7087406c.png)

**Comment by AaronRobinsonMSFT** [comment]
@JeanRasin Can you share the entire tree for the COM server entry? This can be converted into a text file by right clicking on the GUID node and selecting "Export".

**Comment by JeanRasin** [comment]
I tried doing test projects on .NET 5, .NET 6, .NET 7 on different machines. I also chose not my Peep program as a server, but regular Excel and the result is the same. It seems to me that the RunImpersonated method restricts the rights to work with the registry. Users with different rights also do not affect anything. Register entry [Peep.zip](https://github.com/dotnet/runtime/files/10305801/Peep.zip)

**Comment by elinor-fung** [comment]
Can you also check that you have a [ProgID key](https://learn.microsoft.com/windows/win32/com/-progid--key) for `Wppeep.Document`?

> I also chose not my Peep program as a server, but regular Excel and the result is the same. 

For Excel, what ProgID did you use and was it working without impersonation?

**Comment by JeanRasin** [comment]
I also substituted the keys. But if you make Windowsidentity.ruNimpersonated (Windowsidentity.acCesstoken, () => then everything works both with WPPEEP.Document and with excel.
![Screenshot_2](https://user-images.githubusercontent.com/17027319/214002307-78c08ded-2bdd-4f38-bcbc-50d93349ea48.png)
![Screenshot_3](https://user-images.githubusercontent.com/17027319/214002310-ca9a17b0-cbe2-489b-b46b-652fe53cf85f.png)
