### ISSUE TITLE
`MetricsEventSource` Not Publishing `UpDownCounter` For `dotnet-counters`/`dotnet-monitor`?

### ISSUE THREAD

**Issue by kkeirstead** [dotnet/runtime#79916]
The `dotnet monitor` tool is currently working on adding support for `System.Diagnostics.Metrics` (the `dotnet-counters` tool already supports this). Just from taking a look at https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs#L44, it looks like there isn't an event being published for `UpDownCounter` (e.g. UpDownCounterValuePublished) - does this need to be added so that `dotnet-counters` and `dotnet-monitor` can process those events?

**Comment by tarekgh** [comment]
CC @noahfalk
