### ISSUE TITLE
Way to increase x64 GC aggressiveness? (as per x86)

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#7991]
So I want to use x64 (including x64 server GC); but I'd like to turn up its recycle aggressiveness a little.

For example if I run the same server app as x64 it will hover around 1GB; whereas as x86 it will hover around 175MB (private working set). Actual active managed memory in both will be similar and an order of magnitude lower than x86. 

Having 1GB ambient use isn't greatly a problem as am running on a server with plenty of RAM. 

However, it makes it hard to determine correct multi-service loading/homing balance.

i.e. when working out where to re-home services across a cluster; the two major general coarse-grained metrics you'll use are the general behaviours around CPU use and RAM use; but with RAM use being much higher is can make estimating this harder and increasing service density more tricky.

I'm aware allowing more ambient RAM use means less frequent GCs; so it wouldn't apply to all services. Also I'm aware you can limit using [Job objects](https://blogs.msdn.microsoft.com/maoni/2016/05/23/job-support-in-the-gc/).

However, I'm looking for something more of an api or configuration setting like Threadpool min threads; but for memory; where below that threshold its happy to do as it does now and above it moves into a more aggressive reclamation mode. Kind of like Job object but without the hard stop and without the extra setup.

Don't have a formal proposal on what the right approach would be; as I'm not sure. Hoping others might...

/cc @Maoni0

**Comment by benaadams** [comment]
I think all this goodness is in .NET Core 3.1+ so closing

**Comment by JustArchi** [comment]
@benaadams What exactly can be used today in .NET Core 3.1+ for increasing x64 GC aggressiveness, if you don't mind answering?

The only settings I'm aware of are `COMPlus_GCLatencyLevel` and `COMPlus_gcTrimCommitOnLowMemory`.

**Comment by benaadams** [comment]
Much more now; are documented here https://docs.microsoft.com/en-us/dotnet/core/run-time-config/garbage-collector

**Comment by JustArchi** [comment]
Thank you a lot, I somehow missed that link. Cheers! 👍

**Comment by danstur** [comment]
@benaadams From reading the documentation I don't see anything similar to mono's `soft-heap-limit`, but only hard limits. 

Is there any way with 3.1 to allow the GC to use as much memory as it needs during exceptional circumstances, but afterwards when idling greatly reduce resource usage again?

**Comment by JustArchi** [comment]
@danstur `export COMPlus_GCLatencyLevel=0` is the best you can do in .NET Core, and I've configured it made a huge difference for me. You don't really need soft heap limit, if you want to artificially limit generations size then just specify hard limit instead, same deal.

This is my setup:

```
export COMPlus_GCHeapHardLimitPercent=75

export COMPlus_GCLatencyLevel=0
export COMPlus_gcTrimCommitOnLowMemory=1
```

**Comment by benaadams** [comment]
Can set up a lot of the GC settings via csproj https://docs.microsoft.com/en-us/dotnet/core/run-time-config/garbage-collector


Would "High memory percent" be what you are looking for as `soft-heap-limit`?

> ## High memory percent
> 
> Memory load is indicated by the percentage of physical memory in use. By default, when the physical memory load reaches 90%, garbage collection becomes more aggressive about doing full, compacting garbage collections to avoid paging. When memory load is below **90%**, GC favors background collections for full garbage collections, which have shorter pauses but don't reduce the total heap size by much. On machines with a significant amount of memory (80GB or more), the default load threshold is between 90% and 97%.
>
>
> The high memory load threshold can be adjusted by the `COMPlus_GCHighMemPercent` environment variable or `System.GC.HighMemoryPercent` JSON configuration setting. Consider adjusting the threshold if you want to control heap size. For example, for the dominant process on a machine with 64GB of memory, it's reasonable for GC to start reacting when there's 10% of memory available. But for smaller processes, for example, a process that only consumes 1GB of memory, GC can comfortably run with less than 10% of memory available. For these smaller processes, consider setting the threshold higher. On the other hand, if you want larger processes to have smaller heap sizes (even when there's plenty of physical memory available), lowering this threshold is an effective way for GC to react sooner to compact the heap down.

**Comment by Maoni0** [comment]
> Is there any way with 3.1 to allow the GC to use as much memory as it needs during exceptional circumstances, but afterwards when idling greatly reduce resource usage again?

the problem is how you decide what "idling" is? you know when your app is idling but this is not something that's expressed to the GC. GC can try to figure it out but that's purely based on guesses - we could use the amount of allocations, or (more expensively) check the CPU time, or the time we last did a full blocking collection. none of these are ideal because situation could suddenly change drastically. now, if you do know the process will be idling, this is one of the few cases that warrant inducing a GC yourself.

**Comment by danstur** [comment]
@Maoni0 Fair enough, it's definitely a hard problem to solve in general. 

Is there a way to get the GC to release memory back to the OS? Doing a full GC with a commit of 1.5GB when only a 150MB are in use doesn't release memory. I have to run `GC.Collect()` multiple times in a row to give memory back.

@benaadams That seems reasonable, but even with that setting I can't seem to get the process to hand back memory.

**Comment by Maoni0** [comment]
@danstur GC does release memory back to the OS naturally. this is described in [this section](https://github.com/Maoni0/mem-doc/blob/master/doc/.NETMemoryPerformanceAnalysis.md#physical-representation-of-the-gc-heap) of mem-doc. I'm not sure how counted the "150MB are in use", if you are counting it at the end of the GC [this section](https://github.com/Maoni0/mem-doc/blob/master/doc/.NETMemoryPerformanceAnalysis.md#special-handling-of-the-ephemeral-segment) would explain.
