### ISSUE TITLE
TripleDESCryptoServiceProvider Decrypt lost data

### ISSUE THREAD

**Issue by coolincy** [dotnet/runtime#79924]
### Description

Demo from https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.tripledescryptoserviceprovider?f1url=%3FappId%3DDev16IDEF1%26l%3DZH-CN%26k%3Dk(System.Security.Cryptography.TripleDESCryptoServiceProvider)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=net-7.0

The following code example creates a [TripleDESCryptoServiceProvider](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.tripledescryptoserviceprovider?view=net-7.0) object and uses it to encrypt and decrypt data in memory.

`using System;
using System.Security.Cryptography;
using System.Text;
using System.IO;

class TrippleDESCSPSample
{

    static void Main()
    {
        try
        {
            // Create a new TripleDESCryptoServiceProvider object
            // to generate a key and initialization vector (IV).
            TripleDESCryptoServiceProvider tDESalg = new TripleDESCryptoServiceProvider();

            // Create a string to encrypt.
            string sData = "Here is some data to encrypt.";

            // Encrypt the string to an in-memory buffer.
            byte[] Data = EncryptTextToMemory(sData, tDESalg.Key, tDESalg.IV);

            // Decrypt the buffer back to a string.
            string Final = DecryptTextFromMemory(Data, tDESalg.Key, tDESalg.IV);

            // Display the decrypted string to the console.
            Console.WriteLine(Final);
        }
        catch (Exception e)
        {
            Console.WriteLine(e.Message);
        }
    }

    public static byte[] EncryptTextToMemory(string Data,  byte[] Key, byte[] IV)
    {
        try
        {
            // Create a MemoryStream.
            MemoryStream mStream = new MemoryStream();

            // Create a CryptoStream using the MemoryStream
            // and the passed key and initialization vector (IV).
            CryptoStream cStream = new CryptoStream(mStream,
                new TripleDESCryptoServiceProvider().CreateEncryptor(Key, IV),
                CryptoStreamMode.Write);

            // Convert the passed string to a byte array.
            byte[] toEncrypt = new ASCIIEncoding().GetBytes(Data);

            // Write the byte array to the crypto stream and flush it.
            cStream.Write(toEncrypt, 0, toEncrypt.Length);
            cStream.FlushFinalBlock();

            // Get an array of bytes from the
            // MemoryStream that holds the
            // encrypted data.
            byte[] ret = mStream.ToArray();

            // Close the streams.
            cStream.Close();
            mStream.Close();

            // Return the encrypted buffer.
            return ret;
        }
        catch(CryptographicException e)
        {
            Console.WriteLine("A Cryptographic error occurred: {0}", e.Message);
            return null;
        }
    }

    public static string DecryptTextFromMemory(byte[] Data,  byte[] Key, byte[] IV)
    {
        try
        {
            // Create a new MemoryStream using the passed
            // array of encrypted data.
            MemoryStream msDecrypt = new MemoryStream(Data);

            // Create a CryptoStream using the MemoryStream
            // and the passed key and initialization vector (IV).
            CryptoStream csDecrypt = new CryptoStream(msDecrypt,
                new TripleDESCryptoServiceProvider().CreateDecryptor(Key, IV),
                CryptoStreamMode.Read);

            // Create buffer to hold the decrypted data.
            byte[] fromEncrypt = new byte[Data.Length];

            // Read the decrypted data out of the crypto stream
            // and place it into the temporary buffer.
            csDecrypt.Read(fromEncrypt, 0, fromEncrypt.Length);

            //Convert the buffer into a string and return it.
            return new ASCIIEncoding().GetString(fromEncrypt);
        }
        catch(CryptographicException e)
        {
            Console.WriteLine("A Cryptographic error occurred: {0}", e.Message);
            return null;
        }
    }
}`

The output is "Here is some data to enc"

### Reproduction Steps

Use demo codes from https://learn.microsoft.com/

### Expected behavior

Output must be "Here is some data to encrypt."

### Actual behavior

none

**Comment by svick** [comment]
The example code in the documentation is wrong, because `Read()` is not guaranteed to return everything in a single call.

If you're decrypting text, using a `StreamReader` is a better choice than directly reading bytes from the `Stream`.

Otherwise, you will need to call `Read()` in a loop, for example like this:

```c#
Span<byte> buffer = fromEncrypt;
while (!buffer.IsEmpty && csDecrypt.Read(buffer) is int bytesRead and > 0)
{
    buffer = buffer.Slice(bytesRead);
}
```

**Comment by vcsjones** [comment]
In addition to what @svick said, `TripleDESCryptoServiceProvider` is obsolete. You should prefer the factory method `TripleDES.Create`. The [documentation](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.tripledes.create?view=net-7.0) for the factory method shows correct usage.

Additionally, if you just want to encrypt and decrypt bytes, the streams can be entirely avoided with the new one-shot APIs, like [`EncryptCbc`](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.symmetricalgorithm.decryptcbc?view=net-7.0).

**Comment by coolincy** [comment]
> 

TripleDES.Create, same result

**Comment by coolincy** [comment]
> The example code in the documentation is wrong, because `Read()` is not guaranteed to return everything in a single call.
> 
> If you're decrypting text, using a `StreamReader` is a better choice than directly reading bytes from the `Stream`.
> 
> Otherwise, you will need to call `Read()` in a loop, for example like this:
> 
> ```cs
> Span<byte> buffer = fromEncrypt;
> while (!buffer.IsEmpty && csDecrypt.Read(buffer) is int bytesRead and > 0)
> {
>     buffer = buffer.Slice(bytesRead);
> }
> ```

It can fix this bug...
But with dotnet old version, the example code in the documentation is  is correct.

**Comment by svick** [comment]
> But with dotnet old version, the example code in the documentation is is correct.

I wouldn't say that it was correct, the documentation never promised that `Read()` will read everything in one go. But it was working, see [this article](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams) on what changed.
