### ISSUE TITLE
Unused struct fields sometimes improve the codegen

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#79928]
Given:

```c#
public struct T
{
    private double x;
    private byte y; // unused
    private int z; // unused

    public static double M(double v)
    {
        T t = new T { x = v };
        return t.x;
    }
}
```

codegen of `M` looks like:
```asm
T:M(double):double:
       ret  
```

after removing unused fields (`y` and `z`), it turns into:
```asm
T:M(double):double:
       push     rax
       movsd    qword ptr [rsp], xmm0
       add      rsp, 8
       ret
```

IOW, it needs at least one unused field (i.e. size of struct > 8) for this optimization to kick in.

**Comment by gfoidl** [comment]
> IOW, it needs at least one unused field (i.e. size of struct > 8) for this optimization to kick in.

Based on .NET 7 on my tests (out of curiosity): it looks like this optimization kicks in for primitive types, except floating point types (float, double). If a floating point type is present, then adding at least one non-FP-type it kicks in again.

**Comment by am11** [comment]
> then adding at least one non-FP-type it kicks in again.

It also gets optimized with two non-FP types: https://godbolt.org/z/KcY9P41Wz (daily build out of `main` branch)

**Comment by AndyAyersMS** [comment]
This is a known limitation of struct promotion -- it currently lacks a good model to decide whether promoting struct wrapped doubles and floats would be profitable. In cases like the above it is, but in cases where the struct wrapped double (or float) is primarily passed as an argument promotion can be inefficient.

cc @jakobbotsch who is looking into generalizing struct promotion.

https://github.com/dotnet/runtime/blob/e574fbe2393ea4021902decd12d21bbc2c5603b8/src/coreclr/jit/lclvars.cpp#L2118-L2134
