### ISSUE TITLE
Microsoft.Extensions.Hosting.WindowsServices version 7.0.0 not working in .NET 6

### ISSUE THREAD

**Issue by victorplanag** [dotnet/runtime#79929]
### Description

Debug is working correctly...
But when I publish the package and run the .exe as a Windows Service the next error is being displayed...

![image](https://user-images.githubusercontent.com/71526955/209308921-a98d0294-281a-4d11-a71c-67ab3a6e7656.png)

Please, update the package dependencies...

![image](https://user-images.githubusercontent.com/71526955/209307687-1a6be7d4-9b18-4892-8db2-a14b9a29dc65.png)

In version 6.0.1 the windows service is working properly.

### Reproduction Steps

Publish Windows Service with package Microsoft.Extensions.Hosting.WindowsServices version 7.0.0 in .NET 6

### Expected behavior

Working good

### Actual behavior

Error 1067

**Comment by buyaa-n** [comment]
> ### Reproduction Steps
>
> Publish Windows Service with package Microsoft.Extensions.Hosting.WindowsServices version 7.0.0 in .NET 6

@victorplanag I have published [a sample Windows Service](https://learn.microsoft.com/en-us/dotnet/core/extensions/windows-service) with package M`icrosoft.Extensions.Hosting.WindowsServices` version 7.0.0 in .NET 6 but was not able to repro. Please provide a sample repro or check the steps of [the sample Windows Service tutorial](https://learn.microsoft.com/en-us/dotnet/core/extensions/windows-service) and let us know what you did differently.

**Comment by ericstj** [comment]
This looks like the same problem from https://github.com/dotnet/runtime/issues/62579.

**Comment by victorplanag** [comment]
> > ### Reproduction Steps
> > Publish Windows Service with package Microsoft.Extensions.Hosting.WindowsServices version 7.0.0 in .NET 6
> 
> @victorplanag I have published [a sample Windows Service](https://learn.microsoft.com/en-us/dotnet/core/extensions/windows-service) with package M`icrosoft.Extensions.Hosting.WindowsServices` version 7.0.0 in .NET 6 but was not able to repro. Please provide a sample repro or check the steps of [the sample Windows Service tutorial](https://learn.microsoft.com/en-us/dotnet/core/extensions/windows-service) and let us know what you did differently.

Hi,

I leave here the dependency project file (**.csproj**) for a better analysis:

Corrupted dependencies:
```
<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Autofac.Extensions.DependencyInjection" Version="8.0.0" />
	<PackageReference Include="FluentEmail.Core" Version="3.0.2" />
	<PackageReference Include="FluentEmail.Smtp" Version="3.0.2" />
	<PackageReference Include="IdentityModel.AspNetCore" Version="4.3.0" />
	<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="7.0.0" />
	<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="7.0.0" />
    <PackageReference Include="ncrontab" Version="3.3.1" />
  </ItemGroup>
</Project>
```

vs

Fixed dependencies:
```
<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Autofac.Extensions.DependencyInjection" Version="8.0.0" />
	<PackageReference Include="FluentEmail.Core" Version="3.0.2" />
	<PackageReference Include="FluentEmail.Smtp" Version="3.0.2" />
	<PackageReference Include="IdentityModel.AspNetCore" Version="4.3.0" />
	<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.1" />
	<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="6.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="6.0.0" />
    <PackageReference Include="ncrontab" Version="3.3.1" />
  </ItemGroup>
</Project>
```

> This looks like the same problem from #62579.

Check this too. I hope you find the solution as soon as possible.

Regards.

**Comment by buyaa-n** [comment]
> > This looks like the same problem from https://github.com/dotnet/runtime/issues/62579.
> 
> Check this too. I hope you find the solution as soon as possible.

@victorplanag did you checked that issue yourself? Could you try out the workaround [mentioned there](https://github.com/dotnet/runtime/issues/62579#issuecomment-995320972) and let us know how that affects your problem? That would be more helpful, thanks!
