### ISSUE TITLE
[API Proposal] Add a IJsonSerializerOptionsFactory interface.

### ISSUE THREAD

**Issue by jackbond** [dotnet/runtime#79939]
### Background and motivation

net7.0 added the Default property to System.Text.Json.JsonSerializerOptions, which is less than ideal because it's both a static and can't be modified. Much preferable would be to have...

```
public interface IJsonSerializerOptionsFactory
{
    JsonSerializerOptions Create(string? name = default);
}
```

which essentially emulates the IHttpClientFactory interface.

### API Proposal

```
internal class JsonSerializerOptionsFactory : IJsonSerializerOptionsFactory
{
    public const string DefaultSerializerName = "Default";

    Dictionary<string, JsonSerializerOptions> SerializerOptions { get; }

    public JsonSerializerOptionsFactory(
        IOptions<JsonSerializerOptionsFactoryOptions> option)
    {
        if (option?.Value?.SerializerOptions == null)
        {
            throw new ArgumentNullException("SerializerOptions");
        }

        if (option.Value.SerializerOptions.ContainsKey(DefaultSerializerName))
        {
            // Essentially makes all the options readonly
            foreach (var serializer in option.Value.SerializerOptions)
            {
                JsonSerializer.Serialize(5, serializer.Value);
            }

            SerializerOptions = option.Value.SerializerOptions;
        }

        else
        {
            throw new ArgumentException($"A serializer named {DefaultSerializerName} was not provided.");
        }
    }

    public JsonSerializerOptions Create(string? name = default)
    {
        if(SerializerOptions.TryGetValue(name ?? "Default", out JsonSerializerOptions? options))
        {
            return options;
        }

        else
        {
            throw new ArgumentException($"JsonSerializerOptions named {name} not found.");
        }
    }
}

public static class ServiceCollectionExtensions
{
    public static void AddJsonSerializerOptionsFactory(
        this IServiceCollection services)
    {
        services.AddSingleton<IJsonSerializerOptionsFactory, JsonSerializerOptionsFactory>();
    }
}

public class JsonSerializerOptionsFactoryOptions
{
    public Dictionary<string, JsonSerializerOptions> SerializerOptions { get; }

    public JsonSerializerOptionsFactoryOptions()
    {
        JsonSerializerOptions serializer = new JsonSerializerOptions
        {
            NumberHandling = JsonNumberHandling.AllowReadingFromString,
            PropertyNameCaseInsensitive = true,
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        };

        serializer.Converters.Add(new MicrosoftSpatialGeoJsonConverter());

        SerializerOptions = new()
        {
            { "Default", serializer },
        };
    }
}
```

### API Usage

```
ServiceCollection services = new ServiceCollection();

services.AddJsonSerializerOptionsFactory();

ServiceProvider = services.BuildServiceProvider();  

IJsonSerializerOptionsFactory factory = ServiceProvider.GetService<IJsonSerializerOptionsFactory>();

JsonSerializerOptions options = factory.Create();

double latitude = 36.114647;
double longitude = -115.172813;

Foo foo = new Foo
{      
      MicrosoftPoint= GeographyPoint.Create(latitude, longitude),
};

string actual = JsonSerializer.Serialize(foo, options);

string expected = "{\"microsoftPoint\":{\"type\":\"Point\",\"coordinates\":[-115.172813,36.114647]}}";

Assert.AreEqual(expected, actual);
```

**Comment by layomia** [comment]
> which is less than ideal because it's both a static and can't be modified

Why is this less than ideal? Why would you want to modify a "default" object?

Is your concern related to dependency injection?

**Comment by eiriktsarpalis** [comment]
Related to #74492.

**Comment by jackbond** [comment]
Why is this less than ideal? Why would you want to modify a "default" object?

Because the default selections for the default object aren't suitable for my environment. In my shop, we use camel casing everywhere. Ideally, we'd have one instance of JsonSerializerOptions, including the one used by ASP.NET, that would be used by everything that calls JsonSerializer.Serialize. As it stands, I've implemented IJsonSerializerOptionsFactory and yes, it's injected during startup.

**Comment by layomia** [comment]
It seems like this concern should be tackled at the ASP.NET layer. cc @eerhardt @davidfowl.

**Comment by davidfowl** [comment]
I don't know what the name is for, or why we would need named options, or where those names would be specified. ASP.NET Core already has several ways to specify options for JSON in the DI container and I don't know what this would be for. 

I don't see the need for this.

**Comment by jackbond** [comment]
Imagine a large code base, where lots of classes are serializing objects to json. Should every one of them create their own instance of JsonSerializerOptions? The fact that you guys added JsonSerializerOptions.Default, seems to indicate that your users didn't want to be declaring new instances, and that'll work great for environments that JUST SO HAPPEN to be OK with the settings you've picked. Ironically, JsonSerializerOptions.Default doesn't work for the ASP.NET Core guys.

So what can I do, well I could declare my own static, pick the defaults that I like, and tell all my devs to use it. I could go that route, but in the DI / singleton world, I'd rather have something injectable, that's a bit more test friendly. So, I added IJsonSerializerOptionsFactory, so every time a developer needs to serialize something to json, they're not declaring a new instance of JsonSerializerOptions which may not even be properly configured for our environment.

I have great difficultly believing I'm going to be the only guy wanting a standardized way of getting an instance of JsonSerializerOptions.
