### ISSUE TITLE
Extend CA1310 to warn about Dictionary<string, T> and HashSet<string>

### ISSUE THREAD

**Issue by verdie-g** [dotnet/runtime#79932]
### Analyzer

**Diagnostic ID**: [CA1310](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1310)

### Describe the improvement

In my company we found out that culture-sensitive comparison was responsible for massive performance issues. Using ordinal string comparison on our biggest service decreased its CPU by 20%. That's why we would like to get rid of implicit culture-sensitive comparison. The `CA1310` rule is helping but it doesn't warn about `Dictionary<string, T>` and `HashSet<string>` that use culture-sensitive comparison by default.

### Describe suggestions on how to achieve the rule

When a `Dictionary<string, T>` or a `HashSet<string>` is instantiated with no `IEqualityComparer` like the following:
```csharp
Dictionary<string, T> d = new();
HashSet<string> h = new();
```
 a warning would be emitted to specify it explicitly.

**Comment by GSPP** [comment]
Do these collections really use culture-sensitive comparison? I thought not, and this seems to demonstrate that:

```
var hs = new HashSet<string>();
hs.Add("a");
hs.Add("A");
hs.Dump();
```

![image](https://user-images.githubusercontent.com/12032350/210630348-a3635383-efdf-4c2e-8018-86f3acd08ab5.png)

<hr>

```
string s1 = "\u00F6"; // ö
string s2 = "\u006F\u0308"; // ö

HashSet<string> hs = new HashSet<string>();

hs.Add(s1);
hs.Add(s2);

foreach (string s in hs)
    Console.WriteLine(s);
```

![image](https://user-images.githubusercontent.com/12032350/210631777-a8d5db54-5643-45e1-a2e2-2335fc9f6656.png)

Thanks, ChatGPT... 😄

**Comment by stephentoub** [comment]
> Do these collections really use culture-sensitive comparison?

No, they use `EqualityComparer<T>.Default` (or an equivalent), which will just use the `T`'s `IEquatable<T>` implementation, which has ordinal semantics, e.g. it's the same as if you explicitly used StringComparer.Ordinal.

**Comment by tarekgh** [comment]
Closing it per replies. @stephentoub gave example with HashSet and should apply to the Dictionary too. 

```C#
            CultureInfo.CurrentCulture = new CultureInfo("th-TH");
            Dictionary<string, string> d = new Dictionary<string, string>();
            d.Add("a", "a");
            d.Add("a-", "a-");
            Console.WriteLine(d.Count); // print 2
```

**Comment by verdie-g** [comment]
🤯 thanks!
