### ISSUE TITLE
NativeAOT cannot create generic type even if it is rooted using rd.xml

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtime#79930]
### Description

When attempt to run Blazor Hybrid + Winforms I ecounter following issue in the `Microsoft.JSInterop`

Location of the issue is here 
https://github.com/dotnet/aspnetcore/blob/95c74fef646a262909be462c9edda8d8ed4d5b24/src/JSInterop/Microsoft.JSInterop/src/Infrastructure/TaskGenericsUtil.cs#L31-L34

### Reproduction Steps

Program.cs
```csharp
// See https://aka.ms/new-console-template for more information
var task = Task.CompletedTask;
var result = System.Activator.CreateInstance(typeof(T<>).MakeGenericType(task.GetType().GetGenericArguments()[0]));
Console.WriteLine("Success!");

class T<TT>
{
}
```

rd.xml
```xml
<?xml version="1.0" encoding="utf-8" ?>
<Directives>
  <Application>
    <Assembly Name="testaot" Dynamic="Required All">
      <Type Name="T`1[[System.Threading.Tasks.VoidTaskResult,System.Private.CoreLib]]" Dynamic="Required All" />
    </Assembly>
    <Assembly Name="System.Private.CoreLib">
      <Type Name="System.Threading.Tasks.VoidTaskResult" Dynamic="Required All" />
    </Assembly>
  </Application>
</Directives>
```

### Expected behavior

Resulting program produce "Success!";

### Actual behavior

```
Unhandled Exception: System.NotSupportedException: 'T`1[]' is missing native code or metadata. This can happen for code that is not compatible with trimming or AOT. Inspect and fix trimming and AOT related warnings that were generated when the app was published. For more information see https://aka.ms/nativeaot-compatibility
   at System.Reflection.Runtime.General.TypeUnifier.WithVerifiedTypeHandle(RuntimeConstructedGenericTypeInfo, RuntimeTypeInfo[]) + 0x166
   at System.Reflection.Runtime.General.TypeUnifier.GetConstructedGenericTypeWithTypeHandle(RuntimeTypeInfo, RuntimeTypeInfo[]) + 0x3b
   at System.Reflection.Runtime.TypeInfos.RuntimeTypeInfo.MakeGenericType(Type[]) + 0x44c
   at Program.<Main>$(String[]) + 0xf2
   at testaot!<BaseAddress>+0x28d037
   at testaot!<BaseAddress>+0x28d0ca
```

### Regression?

No

### Known Workarounds

Did not exists probably

### Configuration

.NET 7.0.1

**Comment by kant2002** [comment]
Not sure, but type which is passed as parameter to `MakeGenericType` is actually `Boxed VoidTaskResult` and is ReflectionBlockedType

**Comment by MichalStrehovsky** [comment]
Try adding `<IlcArg Include="--nometadatablocking" />` to an ItemGroup

**Comment by kant2002** [comment]
That seems to be unblock me on that specific matter.


Пт, 23 дек. 2022 г. в 17:41, Michal Strehovský ***@***.***>:

**Comment by MichalStrehovsky** [comment]
Getting rid of reflection blocking is tracked in #72570 but currently it's by design that is not possible to reflect on implementation details.
