### ISSUE TITLE
Possible memory corruption issue in wasm

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#79943]
Hi @dotnet/mono-team, it looks like the changes introduced in 5236bb87b3f862a6a5d52e662ab5db792215954f are causing a number of tests to fail on wasm only. I've been able to narrow down the failures to a single unit test in fe3a6270757967cd1cd9000f2b49adf0ae85e082. The failure happens deterministically and only occurs on wasm targets. It appears to occur because the `JsonDocument._utf8Json` span is reported as empty, even though my changes in the second commit make this case impossible -- I suspect this could be caused by some kind of memory corruption.

_Originally posted by @eiriktsarpalis in https://github.com/dotnet/runtime/issues/79890#issuecomment-1364327634_

See https://github.com/dotnet/runtime/pull/79890/checks?check_run_id=10279234698 and https://dev.azure.com/dnceng-public/public/_build/results?buildId=119299&view=ms.vss-test-web.build-test-results-tab for more information.

**Comment by lewing** [comment]
should be fixed in https://github.com/dotnet/runtime/pull/80186
