### ISSUE TITLE
[API Proposal]: Add cartesian product/cross join methods to System.Linq

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#79944]
### Background and motivation

The cartesian product takes two or more enumerable sources and returns one enumerable of tuples enumerating all possible combinations. A common application is generating test data that combines data points from multiple sources.

### API Proposal

The cartesian product methods have signatures identical to those of `Zip` methods.

```csharp
namespace System.Linq;

public static class Enumerable
{
    public static IEnumerable<(TFirst First, TSecond Second)> Product<TFirst, TSecond>(
        this IEnumerable<TFirst> first, 
        IEnumerable<TSecond> second);

    public static IEnumerable<(TFirst First, TSecond Second, TThird Third)> Product<TFirst, TSecond, TThird>(
        this IEnumerable<TFirst> first,
        IEnumerable<TSecond> second,
        IEnumerable<TThird> third);

    public static IEnumerable<TResult> Product<TFirst, TSecond, TResult>(
         this IEnumerable<TFirst> first, 
         IEnumerable<TSecond> second, 
         Func<TFirst, TSecond, TResult> resultSelector);

    public static IEnumerable<TResult> Product<TFirst, TSecond, TThird, TResult>(
        this IEnumerable<TFirst> first,
        IEnumerable<TSecond> second,
        IEnumerable<TThird> third,
        Func<TFirst, TSecond, TThird, TResult> resultSelector);
}
```

### API Usage

Consider the following test data generation logic from System.Text.Json:

```C#
static IEnumerable<(TypeConfiguration typeConfig, string jsonInput)> GetTestData()
    => GetTypeConfigurations().Product(GetJsonInputs());

static IEnumerable<TestData> GetTypeConfigurations()
    => GetTypesAndAttributeAnnotations().Product(
            GetGlobalConfigurations(),
            GetContractConfigurations(),
            static (tc, globalConfig, contractOverride) => new TypeConfiguration(tc.type, globalConfig, tc.attributeAnnotation, contractOverride));

static IEnumerable<JsonUnmappedMemberHandling> GetGlobalConfigurations()
    => new[] { JsonUnmappedMemberHandling.Skip, JsonUnmappedMemberHandling.Disallow };

static IEnumerable<JsonUnmappedMemberHandling?> GetContractConfigurations()
    => new JsonUnmappedMemberHandling?[] { null, JsonUnmappedMemberHandling.Skip, JsonUnmappedMemberHandling.Disallow };

static IEnumerable<(Type type, JsonUnmappedMemberHandling? attributeAnnotation)> GetTypesAndAttributeAnnotations()
{
    yield return (typeof(PocoWithoutAnnotations), null);
    yield return (typeof(PocoWithSkipAnnotation), JsonUnmappedMemberHandling.Skip);
    yield return (typeof(PocoWithDisallowAnnotation), JsonUnmappedMemberHandling.Disallow);
}

private static IEnumerable<string> GetJsonInputs()
{
    yield return """{}""";
    yield return """{"Id": 42}""";
    yield return """{"UnmappedProperty" : null}""";
}
```

### Alternative Designs

* The proposed methods could be alternatively be named `Cartesian` or `CrossJoin`.
* Use nested `foreach` blocks in iterator methods, `SelectMany` or define your own extension methods.

**Comment by strangeman375** [comment]
I usually do it like this:
`private static IEnumerable<object[]> GetTestData()
{
    var integers = new[] { 1, 2, 3 };
    var strings = new[] { "4", "5", "6" };
    var doubles = new[] { 7.0, 8.0, 9.0 };

    return
        from i in integers
        from s in strings
        from d in doubles
        select new object[] { i, s, d };
}`

**Comment by stephentoub** [comment]
>> Use nested foreach blocks in iterator methods, SelectMany or define your own extension methods.

> I usually do it like this:

We do the same thing in a bunch of places in dotnet/runtime tests, e.g.
https://github.com/dotnet/runtime/blob/ecc1ca12aeb7935b7268e752a88c2fa16b875abc/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs#L1754-L1758

**Comment by scharnyw** [comment]
`SelectMany` (or from ... from ...) will do multiple enumerations on all the sequences except the first. In cases where this is a concern, `Join` is probably a better alternative:

    var result = from x in first
        join y in second on true equals true
        select (x, y);

Downside is it's less readable and awkward to handle >2 sequences.
