### ISSUE TITLE
IReadOnlySet<T> is not covariant

### ISSUE THREAD

**Issue by DjArt** [dotnet/runtime#79954]
### Description

Looks like mistake

### Reproduction Steps

```
internal interface IA<out T> : IReadOnlySet<T> { }
```

### Expected behavior

Successful implementation of interface

### Actual behavior

T is no covariance.

**Comment by teo-tsirpanis** [comment]
`IReadOnlySet<T>` cannot be covariant because its `Contains` method accepts a `T`.
