### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by okarpov** [dotnet/runtime#79955]
### Description

After some time of running dotnet application we get the error message in subject.

How to find out the root of the issue which causes this error
and where are the core dumped files saved?

Ubuntu Server 20.04

here is what i have found so far:

root@server: dmesg | grep segfault
[1157149.729375] .NET ThreadPool[2478560]: segfault at 6f1 ip 00007ffff7b639e0 sp 00007ffcfdff9ca0 error 4 in libc-2.31.so[7ffff7a82000+178000]

and this:

root@server:/var/crash# ls
_usr_share_dotnet_dotnet.0.crash

but how now understand what happened and where the crash was?

### Reproduction Steps

don't know yet

### Expected behavior

should run smoothly

### Actual behavior

Segmentation fault (core dumped)

### Configuration

.net 6.0

Ubuntu Server 20.04

**Comment by jeffschwMSFT** [comment]
@okarpov we will need a dump to investigate further.  Also, what exact version of .NET Core are you running and what architecture?

**Comment by danmoseley** [comment]
Also were there any changes to your app or environment just before this started happening?
