### ISSUE TITLE
[RyuJIT][LSRA] Take register encoding sizes into account

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/runtime#7996]
Consider preferring smaller encoding sizes for high ref count, and larger encoding sizes for small ref count.
(This issue was migrated from the desktop bug tracking system.)
category:cq
theme:register-allocator
skill-level:expert
cost:medium

**Comment by kunalspathak** [comment]
I do not think we will have time to do this in .NET 6.

**Comment by kunalspathak** [comment]
Fixed by https://github.com/dotnet/runtime/pull/88151

**Comment by kunalspathak** [comment]
Latest assembly code for the example in https://github.com/dotnet/runtime/issues/7996#issuecomment-361370169:

```
       call     CORINFO_HELP_NEWSFAST
       mov      dword ptr [rax+08H], esi
       mov      dword ptr [rax+0CH], edi
       mov      dword ptr [rax+10H], 4
       mov      dword ptr [rax+14H], 2
       mov      rcx, rbx
       mov      r8, rax
       mov      edx, 42
       mov      r9d, 2
```
