### ISSUE TITLE
Fatal error related to static abstract interface methods on structs.

### ISSUE THREAD

**Issue by HobbsCode** [dotnet/runtime#79968]
**Version Used**: 
VS 17.4.3
.NET 7.0.101

**Steps to Reproduce**:

The below program will compile successfully, but will crash at runtime saying "Fatal error." 
It appears that a combination of factors must be present to trigger the crash.

- The derived type must be a struct.
- The type hierarchy must be generic.
- The static abstract method declaration must be 'abstract' (not 'virtual').

```
DerivedClass.DoNothing();  // OK
DerivedStruct.DoNothing(); // Fatal Error.  (Comment out this line to make the program work.)

Console.WriteLine("Press any key...");
Console.ReadKey(true);

public interface IBase<T>
{
    public static abstract void DoWork(); // If this is 'virtual', then the program works.
}

public interface IDerived<T> : IBase<T>
{
    static void IBase<T>.DoWork() { }
}

public class DerivedClass : IDerived<DerivedClass>
{
    public static void DoNothing() { }
}

public struct DerivedStruct : IDerived<DerivedStruct>
{
    public static void DoNothing() { }
}

```

**Expected Behavior**:
Runs without error.

**Actual Behavior**:
Fatal error.

**Comment by mangod9** [comment]
this doesnt repro on .NET 8 preview 5. So its fixed in latest builds.
