### ISSUE TITLE
mscordbi.dll 4.700.22.55902 is missing from symbol servers.

### ISSUE THREAD

**Issue by yitzhakshsh** [dotnet/runtime#79996]
### Description

Hi,

similar to https://github.com/dotnet/runtime/issues/62939 and https://github.com/dotnet/runtime/issues/61775 and https://github.com/dotnet/runtime/issues/62962.
I'm unable to debug a linux core dump running 4.700.22.55902. 

![1](https://user-images.githubusercontent.com/121504401/209685036-5e62e43f-4976-44ca-b582-abb418df512a.png)

### Reproduction Steps

Try debugging a minidump from Linux running .NET 4.700.22.55902 in Visual Studio 2019/2022 -- open it and then try to start Managed Debugging.

### Expected behavior

The debugging works as usual.

### Actual behavior

The VS hangs with the message about mscordbi.dll not available (see Description above).

**Comment by tommcdon** [comment]
@hoyosjs

**Comment by hoyosjs** [comment]
It's available now.

**Comment by yitzhakshsh** [comment]
Thanks a lot!
