### ISSUE TITLE
SemaphoreSlim constructor parameter doc

### ISSUE THREAD

**Issue by pepone** [dotnet/runtime#79995]
https://github.com/dotnet/runtime/blob/c84d95d846b7cb4144904fde5f09855251c10a70/src/libraries/System.Private.CoreLib/src/System/Threading/SemaphoreSlim.cs#L146

Looking at this code, the doc should say `is less than or equal to zero`

**Comment by bjornen77** [comment]
I can try to put up a PR for this if wanted.

**Comment by danmoseley** [comment]
A PR would be great.

Looks like the actual docs are correct, I guess they are not yet generated from the code in this case:

https://learn.microsoft.com/en-us/dotnet/api/system.threading.semaphoreslim.-ctor?view=net-7.0#system-threading-semaphoreslim-ctor(system-int32-system-int32)

**Comment by bjornen77** [comment]
I changed the XML documentation to the same wording as the other docs mentioned above.
