### ISSUE TITLE
Execution of PublishSingleFile assembly crashes with "Failed to create CoreCLR, HRESULT: 0x80004005"

### ISSUE THREAD

**Issue by LinuxDoku** [dotnet/runtime#80017]
### Description

I can't execute dotnet 7 assemblies which are published with the `PublishSingleFile=true` flag for `win-x64` on my windows 10 x64 workstation.

- The flag `--self-contained` is not relevant - error occurs in both cases.
- It does not matter if I build/publish the assembly directly on this workstation or if I build it on my M1 macbook (with `-r win-x64`) and copy it over.
- The assembly itself works on other x64 windows machines - even if it was built on this "defective" workstation.
- The non `PublishSingleFile`-executable (in the `win-x64`, not in the `publish` directory) can be executed.

I have already repaired dotnet 7 with the installer and restarted this workstation. No luck so far.

### Reproduction Steps

```bash
dotnet new console -o ConsoleTest
cd ConsoleTest
dotnet publish -c Release -p:PublishSingleFile=true
.\bin\Release\net7.0\win-x64\publish\ConsoleTest.exe
```

### Expected behavior

The application should start, print "Hello, World!" and exit with success status code.

### Actual behavior

The application exits with an error:
```
Failed to create CoreCLR, HRESULT: 0x80004005
```

COREHOST_TRACE is attached: [trace.txt](https://github.com/dotnet/runtime/files/10314545/trace.txt)
last lines of this file:
```
[...]
Adding to native path: C:\Entwicklung\Test\dotnet7\ConsoleTest4\bin\Release\net7.0\win-x64\publish\
Property FX_DEPS_FILE = 
Property TRUSTED_PLATFORM_ASSEMBLIES = 
Property NATIVE_DLL_SEARCH_DIRECTORIES = C:\Entwicklung\Test\dotnet7\ConsoleTest4\bin\Release\net7.0\win-x64\publish\;
Property PLATFORM_RESOURCE_ROOTS = 
Property APP_CONTEXT_BASE_DIRECTORY = C:\Entwicklung\Test\dotnet7\ConsoleTest4\bin\Release\net7.0\win-x64\publish\
Property APP_CONTEXT_DEPS_FILES = 
Property PROBING_DIRECTORIES = 
Property RUNTIME_IDENTIFIER = win10-x64
Property System.Reflection.Metadata.MetadataUpdater.IsSupported = false
Property BUNDLE_PROBE = 0x7ff6ab5f5ab0
Property PINVOKE_OVERRIDE = 0x7ff6ab5f5cd0
Property HOSTPOLICY_EMBEDDED = true
CoreCLR path = '', CoreCLR dir = ''
Failed to create CoreCLR, HRESULT: 0x80004005
```

If required I can hand over a detailed procmon dump.

### Regression?

Changing `TargetFramework` from `net7.0` to `net6.0` fixes the problem (dotnet 6.0 sdk is also installed).

### Configuration

```
dotnet --info
.NET SDK:
 Version:   7.0.101
 Commit:    bb24aafa11

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.101\

Host:
  Version:      7.0.1
  Architecture: x64
  Commit:       97203d38ba

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]
  7.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]

Environment variables:
  Not set

global.json file:
  Not found
```

**Comment by vitek-karas** [comment]
@janvorli made some change in 8 to make runtime initialization failures easier to diagnose. Maybe if you could try to publish the app with latest .NET 8 nightly builds from https://github.com/dotnet/installer and then run it. It might show more information.

**Comment by LinuxDoku** [comment]
I installed the latest preview version of dotnet8 (`8.0.100-alpha.1.22622.3`) and tried it again. It still fails.

TargetFramework net7.0: [out-dotnet7.txt](https://github.com/dotnet/runtime/files/10332621/out-dotnet7.txt)
TargetFramework net8.0: [out-dotnet8.txt](https://github.com/dotnet/runtime/files/10332622/out-dotnet8.txt)

**Comment by vitek-karas** [comment]
@janvorli could you please take a look? I don't see any new output in the 8.0 log.

**Comment by janvorli** [comment]
@LinuxDoku was the project changed to target .NET 8 or have you just used the .NET 8 SDK?

**Comment by janvorli** [comment]
Ah, I can see from the log that it was.

**Comment by janvorli** [comment]
@vitek-karas I have missed the fact that besides the `src/native/corehost/hostpolicy/standalone/coreclr_resolver.cpp`, there is also `src/native/corehost/hostpolicy/static/coreclr_resolver.cpp` that needs to get the error logging callback added too. So for single exe host, we are not logging anything yet.

**Comment by vitek-karas** [comment]
@LinuxDoku Could you please try the latest 8.0 again - https://github.com/dotnet/runtime/pull/80104 should have fixed the problem with logging in 8.0 - so hopefully we will get more information now.

**Comment by mattleibow** [comment]
@janvorli just got this now on my machine with the execution of older things. I am on .net 7.0.101 and tried to run the powershell local tool 7.2.1:

```json
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "powershell": {
      "version": "7.2.1",
      "commands": [
        "pwsh"
      ]
    }
  }
}
```

```
> dotnet pwsh
Failed to create CoreCLR, HRESULT: 0x80004005
```

Normal dotnet commands work.

**Comment by mattleibow** [comment]
Seems that powershell was net6 and I did not have that installed... Installed net6 and it worked...

**Comment by LinuxDoku** [comment]
@vitek-karas after installing the latest dotnet8 nightly build (`8.0.100-alpha.1.23068.16`) I cannot reproduce this issue anymore. Then I have uninstalled dotnet8 - even now I can execute assemblies which were previously published with dotnet7. There is only one difference in the corehost_trace between two weeks ago and now when executing the .net 7 targeted single file assembly:

![image](https://user-images.githubusercontent.com/193365/213382433-af9ec900-7015-4c83-9038-a45af7480d8f.png)

`BUNDLE_PROBE` and `PINVOKE_OVERRIDE` have changed. Not sure if this is relevant?

**Comment by vitek-karas** [comment]
@LinuxDoku : `BUNDLE_PROBE` and `PINVOKE_OVERRIDE` are "stringified" pointers, so they will differ on each run basically.
What you describe seems to suggest that the install of 8 brought some necessary dependency which was missing before. But it's hard to tell exactly what that was. .NET 8 should have better error reporting in this case, but since it works it doesn't help.

@mattleibow : It is definitely expected that .NET 6 apps won't run by default without 6 runtime installed (you can force them to run on the later runtime via env. variable like `DOTNET_ROLLFORWARD=Major` for example). But the failure mode is weird - if it's missing the right runtime version I would expect it to fail with an error saying that, and not when it actually tried to launch the runtime (which means it decided to use it regardless of version somewhere).

/cc @elinor-fung

**Comment by LinuxDoku** [comment]
I close this issue as it seems to be fixed with .NET 8 - and so far it works for me.

**Comment by elinor-fung** [comment]
@mattleibow if it is not too much trouble for you to get back into the failure state, a [host trace](https://learn.microsoft.com/dotnet/core/tools/dotnet-environment-variables#corehost_trace) would be helpful to see how/why we are using the higher runtime version for 6.0 powershell.

**Comment by vitek-karas** [comment]
It seems Powershell has this in runtime config:
```json
    "rollForwardOnNoCandidateFx": 2,
```

So basically `RollForward=Major`.
