### ISSUE TITLE
Need to move off osx.1015.amd64.open queues

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#80029]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=120556
Build error leg or test failing: Libraries Test Run checked coreclr OSX x64 Debug / Send to Helix
Pull request: https://github.com/dotnet/runtime/pull/80005

At least release/6.0 it's the x64 test queue for all runtime tests
Also on main tvOS and iOS emulator tests run on these queues. 

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section).

```json
{
  "ErrorMessage": "Helix queue osx.1015.amd64.open is set for estimated removal date of",
  "BuildRetry": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by akoeplinger** [comment]
This was fixed in 6.0 by https://github.com/dotnet/runtime/pull/80030

**Comment by ViktorHofer** [comment]
Keeping open to track the 7.0 and main ports

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0
