### ISSUE TITLE
FileInfo.Createtime seem to be wrong (.Net 6 on Linux)

### ISSUE THREAD

**Issue by MrM40** [dotnet/runtime#80023]
### Description

This is the output form the stat command on Linux (ext4 filesystem):
![image](https://user-images.githubusercontent.com/16258063/209849804-41768416-38d8-490d-9c35-580d03fe3a36.png)

This is what I get from FileInfo:
![image](https://user-images.githubusercontent.com/16258063/209849829-ec989bde-a99a-48ab-83f5-dc6419df4790.png)

If CreateTime cannot be retrieved correctly, I would prefer an error or a `01/01/0001 00.00.00` date. 
This property is used in a backup-program to track file-changes so I'm happy I found this in time.

Found these related closed issues: [20489](https://github.com/dotnet/runtime/issues/20489) and [27956](https://github.com/dotnet/runtime/issues/27956)

### Reproduction Steps

 NA

### Expected behavior

NA

### Actual behavior

NA

**Comment by danmoseley** [comment]
In the issues you linked there was considerable discussion of the pros and cons of different approaches, including examining various existing libraries to see how they use it. To change this, we'd have to understand how that reasoning was flawed, and that changing it now would not been an unacceptable new break. Thoughts?

Linking PR also..
https://github.com/dotnet/corefx/pull/18343

**Comment by MrM40** [comment]
Wrong data is the worse of all options. It's a lot worse than no data!
So if birth/CreationTime is missing don't just replace with something else. Other options could be an error, null or `01/01/0001 00.00.00`, which is kind of bad too, but not as bad as a datetime that looks realistic as the current.
If stat can't retrieve birth time it return "-"

**Comment by danmoseley** [comment]
@MrM40 Do you appreciate the arguments made in the original discussion though? This allows some existing code to "just work" on Linux.

Leaving aside correctness, are you able to achieve your goals on Linux?

**Comment by MrM40** [comment]
Which argument in particular?

I see no gray-zone here, either it works or it doesn't, and it doesn't (FileInfo.CreationTime on Linux).
And just to repeat my self: not working is one thing, but present a wrong value is even worse.

But one can always execute an external native Linux tool like `stat` and serialize the result as a workaround.

**Comment by stephentoub** [comment]
As @danmoseley points out, we've discussed this at length multiple times, and the current approach is where we've landed.  I don't see any new evidence here to suggest changing direction.
