### ISSUE TITLE
PipeReader ReadAsync Do not cover all the case of completion of stream

### ISSUE THREAD

**Issue by abdollahkahne** [dotnet/runtime#80039]
https://github.com/dotnet/runtime/blob/fa7d049aad0261f8ed6c0584f1ccf2ad08aec23c/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/StreamPipeReader.cs#L343

As I understand from source code of `StreamPipeReader` which instantiated by static method `PipeReader.Create(stream),` the `IsCompleted` only return `true` when `ReadResult` (returned by `ReadAsync`) do return a buffere with `Lenght` equal to zero. I have an example which the source stream finished but reader do not return `ReadAsync` at al. It waits infinitely there and so my code waits too. Fortunately I can handle this situation by a pre-check before reading the pipe reader (`if (!stream.DataAvailable)`) but I think this better to be inherent to PipeReader itself (for example with `IsComplete` property). Another pre-check that I do in similar situation, is comparing returned buffer length with total buffer length which it is not possible in this special case. 
This issue only created for proposition and can be ignored.

**Comment by MihaZupan** [comment]
> I have an example which the source stream finished but reader do not return ReadAsync at al.

Can you share that example?

**Comment by abdollahkahne** [comment]
I think it depends on my machine which is Linux. The code is a sample which I get from a tutorial. Code created in this repo.
https://github.com/abdollahkahne/SocketSample.git

**Comment by adityamandaleeka** [comment]
Triage: a stalled stream is not a signal for completion. If this is useful to you in your specific scenario you can wrap it as you described, but in general this isn't something we would implement in the PipeReader code.
