### ISSUE TITLE
FromBase64Transform whitespace issue

### ISSUE THREAD

**Issue by appelgjo** [dotnet/runtime#80040]
This program gets a ``System.IndexOutOfRangeException`` in .NET Core 6, both on Windows and Linux:
```
using System.Security.Cryptography;
using System.Text;

string b64 =
    "TG9yZW0gaXBzdW0gZG9sb3Igc2l0IGFtZXQsIGNvbnNlY3RldHVyIGFkaXBpc2Np" +
    "\n" +
    "bmcgZWxpdC4K";
using Stream input = new MemoryStream(Encoding.ASCII.GetBytes(b64));
using ICryptoTransform decoder = new FromBase64Transform(FromBase64TransformMode.IgnoreWhiteSpaces);
using Stream decoding = new CryptoStream(input, decoder, CryptoStreamMode.Read);
using Stream output = Console.OpenStandardOutput();
decoding.CopyTo(output);
```
``"\r\n"`` instead of ``"\n"`` works fine.

Similar to https://github.com/dotnet/runtime/issues/46922 .

**Comment by gfoidl** [comment]
Sounds similar to https://github.com/dotnet/runtime/issues/76918

**Comment by appelgjo** [comment]
Duplicate of #76918

**Comment by appelgjo** [comment]
Closed.

**Comment by vcsjones** [comment]
Thanks for the issue report. Since a duplicate has been identified, I am going to close this one out in favor of the linked issue.
