### ISSUE TITLE
[wasm][debugger] Invoke static getter in valuetype not working

### ISSUE THREAD

**Issue by thaystg** [dotnet/runtime#80049]
For example: System.DateTime:get_DaysInMonth365 ()

**Comment by thaystg** [comment]
Invoke static getter in valuetype is working, added a test in this PR:
https://github.com/dotnet/runtime/pull/89399

Invoking this getter specifically "System.DateTime.DaysInMonth365" asserts in the runtime side. I'm not sure if this is important for .net8.0. I'll try to take a look.

**Comment by lewing** [comment]
@thaystg pleast retriage this

cc @tommcdon

**Comment by thaystg** [comment]
This is fixed by the new debugger.
