### ISSUE TITLE
Getting segfault error 4 in libcoreclr.so

### ISSUE THREAD

**Issue by MikeUgra** [dotnet/runtime#80047]
Hello there! I have dotnet core 3.1 app on CentOS 8.5, which is reading data from DB every 5 sec (tiny select with 2 linked small tables with max 50 rows in result). I'm using Dapper for querying data. App works fine with SQL Server, but when I try to do absolutely the same with PostgreSQL it throws:
segfault at 750000006c ip 00007efffeb87c0a sp 00007eff55445bd8 error 4 in libcoreclr.so[7efffea86000+2f0000].
Interesting fact is that throws the fault not when starting the app but after 5-7 successful queries. 

Sorry, English is not my native.

**Comment by danmoseley** [comment]
@MikeUgra 3.1 has just gone  out of support. Please update your app to 6.0 or 7.0 and try again. Let us know if you have trouble upgrading.

https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

if that fixes it, great. If not, do you have the ability to generate a stack trace at the point of failure, with GDB or LLDB?

if not, then did the system create a core dump? If not, run `sudo ulimit -c unlimited` and repro the crash again.

**Comment by MikeUgra** [comment]
Nothing has changed after ulimit -c unlimited
```
Dec 29 21:07:15 localhost.localdomain kernel: myapplication[7512]: segfault at 750000006c ip 00007f05ac89bc0a sp 00007f0598ce0108 error 4 in libcoreclr.so[7f05ac79a000+2f0000]
Dec 29 21:07:15 localhost.localdomain kernel: Code: cc bb 1c 00 66 44 0f 6f 0d d3 bb 1c 00 48 89 7c 24 90 66 66 66 66 66 2e 0f 1f 84 00 00 00 00 00 48 89 c8 48 8b 30 48 83 e6 fe <8b> 4e 04 83 3e 00 bd 00 00 00 00 79 0a 8b 50 08 0f b7 2e>
Dec 29 21:07:15 localhost.localdomain systemd[1]: Started Process Core Dump (PID 7558/UID 0).
Dec 29 21:07:15 localhost.localdomain systemd-coredump[7559]: Resource limits disable core dumping for process 7503 (myapplication).
Dec 29 21:07:15 localhost.localdomain systemd-coredump[7559]: Process 7503 (myapplication) of user 0 dumped core.
Dec 29 21:07:15 localhost.localdomain systemd[1]: systemd-coredump@3-7558-0.service: Succeeded.
Dec 29 21:07:15 localhost.localdomain systemd[1]: myapplication.service: Main process exited, code=killed, status=11/SEGV
```

**Comment by danmoseley** [comment]
What does 'ulimit -c' show ?

**Comment by danmoseley** [comment]
Are you using .NET 6.0 or 7.0? If not please update your app and re test.

**Comment by MikeUgra** [comment]
Updated to NET5, no segfault, many thanks!

**Comment by roji** [comment]
@MikeUgra great, but note that .NET 5 is out of support - it's highly recommended to upgrade to at least .NET 6.0.
