### ISSUE TITLE
[API Proposal]: Add System.IAction and System.IFunc default interfaces implicitly implemented by all Action and Func delegates

### ISSUE THREAD

**Issue by vhforte** [dotnet/runtime#80041]
### Background and motivation

It is hard to write unit tests when OOP principles are not followed. For example a method which accepts Action<T,...>.
I want to test the method below as a white box and check that the action passed as argument is called with specific arguments.
Example method:

```csharp
public class TestTarget
{
    public void Work(string arg, Action<string> action)
    {
        action(arg);
    }
}
```
My proposal is to have standard set of interfaces System.IAction<> and System.IFunc<> same as we have Action<> and Func<> delegates.
Every Action instance must implement the IAction interface by compiller. See proposed API and unit test below.

### API Proposal

Target class and method:
```csharp
public class TestTarget
{
    public void Work(string arg, IAction<string> action)
    {
        action.Act(arg)
        // or with syntax sugar:  action(arg);
    }
}
```

### API Usage

```csharp
using Moq;
using System;

public class MyTest
{
    [Fact]
    public void Test()
    {
        // Setup
        var target = new TestTarget();
        var mockedAction = new Mock<IAction<string>>(MockBehavior.Strict);
        mockedAction.Setup(action => action.Act("HELLO WORLD")).Verifiable();
       // or with syntax sugar:  mockedAction.Setup(action => action("HELLO WORLD")).Verifiable();

        // Act
        target.Work("HELLO WORLD", mockedAction.Object);

        // Verify
        mockedAction.Verify();
    }
}
```

### Alternative Designs

Alternatives are testing everything as blackbox with lots of code.
Or providing some fake implementation of Action with custom code to verify something using variables.

### Risks

Actions compiled in older .Net are not castable to IAction

**Comment by hez2010** [comment]
You can already mock the `Delegate.Invoke` without need of those interfaces:

```csharp
var mockAction = new Mock<Action<string>>();
mockAction.Setup(x => x("Hello World")).Verifiable();
```

**Comment by vhforte** [comment]
@hez2010 
Thank you. In this case, this proposal is not relevant.
