### ISSUE TITLE
Any plans of deprecation of RijndaelManaged class

### ISSUE THREAD

**Issue by janichirag11** [dotnet/runtime#80048]
Do we have any plans to deprecate the RijndaelManaged class? If yes, which version should we expect?

**Comment by danmoseley** [comment]
Off topic, but much appreciation for your triage work @teo-tsirpanis -- you're super industrious and it really helps make this repo better.

**Comment by janichirag11** [comment]
Thanks for the quick response.

May be I was not clear enough posting the question. I wanted to check when
these classes will be completely removed from the .net core library?

This means teams won't be able to compile the code at all.

Thanks in advance.

Regards,
Chirag Jani

**Comment by teo-tsirpanis** [comment]
Why remove them? It would break code for no reason.
