### ISSUE TITLE
Safety of Memory.Pin for Memory instances created with CreateFromPinnedArray

### ISSUE THREAD

**Issue by stephan-tolksdorf** [dotnet/runtime#80055]
If I read the [implementation](https://github.com/dotnet/runtime/blob/05671f8e4ac6ee921ca314a189912ddaee22b8f8/src/libraries/System.Private.CoreLib/src/System/Memory.cs#L411-L414) correctly, `System.Memory<T>.Pin()` does not allocate a `GCHandle` for a `Memory` instance that was created with `MemoryMarshal.CreateFromPinnedArray` from an array that was created with `GC.AllocateArray<T>(_, pinned:true)`. Isn't this rather unsafe because such an array is not necessarily kept alive when code is only using the handle (since the handle only contains an unmanaged pointer)?

**Comment by jkotas** [comment]
Yes, all APIs on `MemoryMarshal` are rather unsafe. 

The caller of this API has to guarantee that the array remains alive and pinned while the returned `Memory<T>` instance is still in use.

**Comment by stephan-tolksdorf** [comment]
The documentation for `CreateFromPinnedArray` remarks:

> This method should only be called on an array that is already pinned and that array should not be unpinned while the returned Memory<T> is still in use. Calling this method on an unpinned array could result in memory corruption.

That the caller is also responsible for ensuring that the array is kept alive to me seems like a subtle point, since one might expect the created `Memory<T>` to keep the array alive.

**Comment by davidfowl** [comment]
It's for scenarios like this:

https://github.com/dotnet/aspnetcore/blob/0467d031e798d596420dcf54a056bc6ab690e437/src/Shared/Buffers.MemoryPool/MemoryPoolBlock.cs#L17

We guarantee the array is pinned and rooted before calling `CreateFromPinnedArray`.  As @jkotas said, `MemoryMarshal` is for advanced/unsafe APIs.

**Comment by stephan-tolksdorf** [comment]
@davidfowl I'm worried about scenarios like the following, where a missing `Dispose` could lead to invalid memory accesses, as far as I understand:

```
// Library code

class MyClass : IDisposable {
    private IMemoryOwner<byte> _buffer;

    MyClass() {
        // Assigns _buffer an instance fetched and removed from a pool of pinned arrays
    }

    public void Write() {
        // Writes to _buffer memory.
    }

    public void Read() {
        using handle = _buffer.Memory.Pin();
        // Reads memory via handle.Pointer and doesn't use this afterwards.
    }

    void Dispose() {
        _buffer.dispose();
    }
}

// User code

void incautiousUserCode() {
    var x = new MyClass(); // User forgets to use using statement.
    x.Write();
    x.Read(); // GC might collect x and hence the buffer during execution of Read.
}
```

**Comment by zlatanov** [comment]
> ```cs
> x.Read(); // GC might collect x and hence the buffer during execution of Read.
> ```

I don't understand why the GC would collect the `x` instance, when there is code executing in its `Read` method, which is not static and thus has a `this` object reference inside of it?

**Comment by stephentoub** [comment]
> I don't understand why the GC would collect the x instance, when there is code executing in its Read method, which is not static and thus has a this object reference inside of it?

It's no different from a static method being passed an instance, e.g.
```C#
Foo(new Bar());
...
static void Foo(Bar b)
{
    b.Zoo();
    // it's valid to consider b unreachable here
}
```
With an instance method, the `this` is effectively just a parameter to the method.

**Comment by zlatanov** [comment]
> With an instance method, the `this` is effectively just a parameter to the method.

That makes sense to me if the method call is inlined. Does this also work in the non-inlined cases? Or is it more complicated and the answer is "it depends"?

Either way, you make a good point that I often times forget - that the object instance might be GC'ed while executing an instance method.

**Comment by jkotas** [comment]
Inlining does not change the guarantees. In the [example](https://github.com/dotnet/runtime/issues/80055#issuecomment-1369789233) that @stephentoub shared, `Bar` instance can be considered unreachable irrespective of whether `Foo` is inlined or not.

**Comment by jkotas** [comment]
> May be something like this would be more problematic

[This example](https://github.com/dotnet/runtime/issues/80055#issuecomment-1369553169) is not problematic. 
`memoryHandle` is full pinning memory handle in this example that will keep the array alive. `Memory<T>` does not know that the array is pinned by other means.

**Comment by stephentoub** [comment]
Closing as answered.
