### ISSUE TITLE
[API Proposal]: StringBuild.Substring

### ISSUE THREAD

**Issue by sretz** [dotnet/runtime#80061]
### Background and motivation

To create a new string from a portion of the StringBuilder.

### API Proposal

```csharp
namespace System.Collections.Generic;

public class StringBuilder
{
    public string Substring (int startIndex, int length);
}
```

### API Usage

```csharp
var builder = new StringBuilder("0123456789");
var sub = builder.Substring(1, 2);
```

**Comment by Clockwork-Muse** [comment]
Sample extension method (insufficient error checking):

```cs
public static string ToString(this StringBuilder sb, int start, int length) {
    var actual_length = Math.Min(sb.Length - start, length);
    return string.Create(actual_length, (sb, start), (span, t) => {
        var (sb, start) = t;
            sb.CopyTo(start, span, span.Length);
    });
}
```
(has the benefit of only allocating the destination string once, and probably avoiding intermediate allocations in the SB for some operations)

**Comment by stephentoub** [comment]
This already exists:
https://learn.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.tostring?view=net-7.0#system-text-stringbuilder-tostring(system-int32-system-int32)
