### ISSUE TITLE
PublishSingleFile=true + EventListener causes EventPipeEventDispatcher.DispatchEventsToEventListeners() to fully occupy a CPU core

### ISSUE THREAD

**Issue by sandersaares** [dotnet/runtime#80064]
### Description

I observe that there is a thread named ".NET Long Running Task" that is looping in `EventPipeEventDispatcher.DispatchEventsToEventListeners()`, constantly calling `EventPipeInternal.GetNextEvent()` and immediately looping again (without entering the `instanceData.ProviderID == m_RuntimeProviderID` block). This thread consumes an entire CPU core.

This only happens if PublishSingleFile=true in the csproj.

### Reproduction Steps

https://github.com/sandersaares/whatiswrongwithyourdog-single-exe-eventpipe

Just run it and you should see one CPU core immediately occupied.

### Expected behavior

No excessive CPU use from event dispatcher.

### Actual behavior

1 CPU core seems to be permanently used up by this event dispatcher loop.

### Known Workarounds

PublishSingleFile=false

### Configuration

.NET SDK:
 Version:   7.0.101
 Commit:    bb24aafa11

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.101\

Host:
  Version:      7.0.1
  Architecture: x64
  Commit:       97203d38ba

.NET SDKs installed:
  6.0.404 [C:\Program Files\dotnet\sdk]
  7.0.101 [C:\Program Files\dotnet\sdk]

**Comment by tommcdon** [comment]
@davmason

**Comment by tommcdon** [comment]
Hi @sandersaares!  This was fixed in 6.0.15 on https://github.com/dotnet/runtime/pull/81238 as well as 7.0.0 on https://github.com/dotnet/runtime/pull/74481.
