### ISSUE TITLE
Encoding.UTF8-Api has a low performance?

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/runtime#80067]
### Description
I 'm doing a network communication software, but found a problem in the sending scenario, I use UTF8Encoding for transcoding, and then use PipeWriter to write and send.  Why is the performance of the low-allocated API not the best?

### Configuration

.NET6.0
BenchmarkDotNet  0.13.1
System.IO.Pipelines 6.0.2

### Data

![11](https://user-images.githubusercontent.com/16236903/210061291-a8cb93bd-e20c-47eb-a1a5-12347c71c502.png)

```c#
        private readonly PipeWriter _writer;
        private static readonly Encoder Utf8Encoder;
        private static readonly Encoding Utf8Handler;

        [Benchmark]
        public void NormalAsyncWriter()
        {
            var data = $"A String";
            var datas = Utf8Handler.GetBytes(data);
            _writer.WriteAsync(datas).ConfigureAwait(false);
        }


        [Benchmark]
        public void NormalWriteWithSpanCopy()
        {
            var data = $"A String";
            var bytes = Utf8Handler.GetBytes(data);
            var span = _writer.GetSpan(bytes.Length);
            _writer.Advance(bytes.Length);
            bytes.CopyTo(span);
            _writer.FlushAsync().ConfigureAwait(false);
        }

        [Benchmark]
        public void NormalWriterByIBufferWriter()
        {
            var data = $"A String";
            Utf8Handler.GetBytes(data, _writer);
            _writer.FlushAsync().ConfigureAwait(false);
        }
```

And other result:
![28](https://user-images.githubusercontent.com/16236903/210061342-c55c0d2d-f090-4069-9408-39622438e2e1.png)

### Analysis
Does 'fixed' slow down performance?

**Comment by svick** [comment]
You're not measuring what you think you're measuring, since you never `await` the `async` operations.

**Comment by MihaZupan** [comment]
Looking at the [implementation](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Memory/src/System/Text/EncodingExtensions.cs) of the 
```c#
GetBytes(this Encoding encoding, ReadOnlySpan<char> chars, IBufferWriter<byte> writer)
```
extension, we are doing two passes over the input (`GetByteCount` + `GetBytes`).
For reasonably short inputs we should be able to just do `GetMaxByteCount` + `GetBytes`.

**Comment by NMSAzulX** [comment]
@svick @MihaZupan Thanks. I have changed my code. I increased the length of the string. The result was the expected result. But this test has some problem.

```c#

        const string data = @"A Stringasdsadsadasdsadasdasdasdasdasdasdasdasdasdasdasdasdasd";


        //WorkloadActual   1: 8388608 op, 822630800.00 ns, 98.0652 ns/op
        //exception: 
        /*
OutOfMemoryException!
BenchmarkDotNet continues to run additional iterations until desired accuracy level is achieved. It's possible only if the benchmark method doesn't have any side-effects.
If your benchmark allocates memory and keeps it alive, you are creating a memory leak.
You should redesign your benchmark and remove the side-effects. You can use `OperationsPerInvoke`, `IterationSetup` and `IterationCleanup` to do that.

System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.SpanHelpers.SequenceCompareTo(Char& first, Int32 firstLength, Char& second, Int32 secondLength)
   at System.String.Compare(String strA, Int32 indexA, String strB, Int32 indexB, Int32 length, StringComparison comparisonType)
   at System.Resources.ResourceManager.IsDefaultType(String asmTypeName, String typeName)
   at System.Resources.ManifestBasedResourceGroveler.CanUseDefaultResourceClasses(String readerTypeName, String resSetTypeName)
   at System.Resources.ManifestBasedResourceGroveler.CreateResourceSet(Stream store, Assembly assembly)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at System.SR.InternalGetResourceString(String key)
   at System.SR.GetResourceString(String resourceKey)
   at System.Reflection.TargetInvocationException..ctor(Exception inner)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)*/
        [Benchmark]
        public void WriteBytesWithoutCopy()
        {
            Utf8Encoding.GetBytes(data, _writer);
        }

        //WorkloadActual   1: 8388608 op, 944311400.00 ns, 112.5707 ns/op
        //exception:
        /*
 OutOfMemoryException!
BenchmarkDotNet continues to run additional iterations until desired accuracy level is achieved. It's possible only if the benchmark method doesn't have any side-effects.
If your benchmark allocates memory and keeps it alive, you are creating a memory leak.
You should redesign your benchmark and remove the side-effects. You can use `OperationsPerInvoke`, `IterationSetup` and `IterationCleanup` to do that.
         */
        [Benchmark]
        public void GetBytesAndCopyToSpan()
        {
            var bytes = Utf8Encoding.GetBytes(data);
            var span = _writer.GetSpan(bytes.Length);
            _writer.Advance(bytes.Length);
            bytes.CopyTo(span);
        }

        //WorkloadActual   1: 8388608 op, 975679200.00 ns, 116.3100 ns/op
        //exception:
        /*
 OutOfMemoryException!
BenchmarkDotNet continues to run additional iterations until desired accuracy level is achieved. It's possible only if the benchmark method doesn't have any side-effects.
If your benchmark allocates memory and keeps it alive, you are creating a memory leak.
You should redesign your benchmark and remove the side-effects. You can use `OperationsPerInvoke`, `IterationSetup` and `IterationCleanup` to do that.
         */
        [Benchmark]
        public void WriteBytesWithCopy()
        {
            var datas = Utf8Encoding.GetBytes(data);
            _writer.Write(datas);
        }
```

**Comment by MihaZupan** [comment]
Your benchmark has side effects (the writer keeps growing and growing). See https://github.com/dotnet/performance/blob/main/docs/microbenchmark-design-guidelines.md#no-side-effects.

**Comment by NMSAzulX** [comment]
> Your benchmark has side effects (the writer keeps growing and growing). See https://github.com/dotnet/performance/blob/main/docs/microbenchmark-design-guidelines.md#no-side-effects.

Thank you. I had recode buffer pool. It works! And got the result:

BenchmarkDotNet=v0.13.3, OS=Windows 10 (10.0.19045.2364)
Intel Core i7-6700HQ CPU 2.60GHz (Skylake), 1 CPU, 8 logical and 4 physical cores
.NET SDK=6.0.202
  [Host]     : .NET 6.0.4 (6.0.422.16404), X64 RyuJIT AVX2
  DefaultJob : .NET 6.0.4 (6.0.422.16404), X64 RyuJIT AVX2


|                Method |     Mean |    Error |   StdDev |      Min |      Max |   Median |   Gen0 |   Gen1 | Allocated |
|---------------------- |---------:|---------:|---------:|---------:|---------:|---------:|-------:|-------:|----------:|
| WriteBytesWithoutCopy | 78.19 ns | 0.772 ns | 0.722 ns | 77.08 ns | 79.18 ns | 78.15 ns | 0.0002 | 0.0001 |       2 B |
|    WriteBytesWithCopy | 99.12 ns | 0.532 ns | 0.497 ns | 98.43 ns | 99.89 ns | 99.05 ns | 0.0498 | 0.0006 |     162 B |

**Comment by NMSAzulX** [comment]
String length affects the performance of both methods. The longer the string, the faster the NoCopy method.

**Comment by tarekgh** [comment]
> String length affects the performance of both methods. The longer the string, the faster the NoCopy method.

Is it when the string is longer than 1M in length? Or are you saying this is general even with strings less than 1M in length? 

CC @GrabYourPitchforks

**Comment by NMSAzulX** [comment]
@tarekgh Emm..  The string is less than 1 m in length during the test.

**Comment by tarekgh** [comment]
`WriteBytesWithCopy` is calling `var datas = Utf8Encoding.GetBytes(data);` which will allocate the return buffer and then write it to the buffer. While `WriteBytesWithoutCopy` encode the data directly to the buffer. It will just need to calculate the size (through calling GetByteCount) before the encoding operation. So, the behavior you are seeing is expected.

**Comment by NMSAzulX** [comment]
@tarekgh  Thank you for your answer. 

I didn't make any constructive suggestions in this ISSUE, I will close it.
