### ISSUE TITLE
[API Proposal]: StringBuilder.IndexOf(string find, int start)

### ISSUE THREAD

**Issue by sretz** [dotnet/runtime#80060]
### Background and motivation

To be able to find a string in a StringBuilder without creating a new string.

### API Proposal

```csharp
namespace System;

public class StringBuilder
{
    public int IndexOf (string value, int startIndex);
}
```

### API Usage

```csharp
var builder = new StringBuilder("Text to Find");
var offset = builder.IndexOf("Find");
```

**Comment by danmoseley** [comment]
Could you say more about when you have needed this? Links to other code bases that are working around this would also help.

Philosophically it is not a goal for StringBuilder to have arbitrary features of String. It is designed to build up a char buffer efficiently and then be converted to a string. If you treat it as a kind of string you can hit perf traps and fixing those could compromise its core purpose. Searching is always going to be faster in a buffer that is known to be contiguous.

**Comment by sretz** [comment]
When processing a string of "{Name0:format}.{Name1:format}.{Name2:format}.{Name3:format}.{Name4:format}" as a format string.

**Comment by dakersnar** [comment]
@stephentoub after discussion, we think this seems reasonable given we already have this logic internally to implement Replace. Any objections to marking it ready for review?

**Comment by stephentoub** [comment]
Seems ok if there's a really good use case for it.

A few things to keep in mind, though:
- StringBuilder stores its data as a linked list of buffers, in reverse.  That means finding the element at the ith position can be an O(n) operation in the extreme, and so if you're using this method to repeatedly find the next occurrence, in the worst case it could be O(n^2).  Now in all liklihood it's nowhere near that expensive, and Replace as an implementation detail does suffer from that same thing today, but Replace could be implemented to avoid it, whereas that'd be hard via this API.
- string.IndexOf is culturally-sensitive, e.g. it behaves by default as if you used StringComparison.CurrentCulture.  I think it's ok for StringBuilder to differ; Replace already does, behaving like StringComparison.Ordinal.  But it's again just something to keep in mind.

Additionally, I don't fully understand the scenario or what:
"When processing a string of "{Name0:format}.{Name1:format}.{Name2:format}.{Name3:format}.{Name4:format}" as a format string."
means.  If the comment means that a normal composite format string is being parsed, it'd be helpful to understand why... this new API may not be the best answer for that.

**Comment by dakersnar** [comment]
Marked as "needs-author-action" to request some more details about use cases and elaboration on the specific example @sretz brought up.
