### ISSUE TITLE
`Microsoft.Extensions.FileSystemGlobbing.Matcher` matches glob pattern `/*/` against file path `/a/b`, but it shouldn't.

### ISSUE THREAD

**Issue by konrad-jamrozik** [dotnet/runtime#80076]
### Description

A glob pattern `/*/` should not match against `/a/b`. Some tools that confirm this:

- https://www.digitalocean.com/community/tools/glob?comments=true&glob=%2F%2A%2F&matches=false&tests=%2Fa%2Fb
- https://codepen.io/mrmlnc/pen/OXQjMe

However, it does match in case of `Microsoft.Extensions.FileSystemGlobbing.Matcher`. See reproduction steps below for details.

Relevant spec:
- https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.filesystemglobbing.matcher?view=dotnet-plat-ext-7.0
  Quote (emphasis mine):
  > Wildcards (*) in file and directory names that represent zero to many characters **not including directory separators characters**.
- https://man7.org/linux/man-pages/man7/glob.7.html

### Reproduction Steps

This test case should pass, but doesn't:

``` csharp
using System;
using System.Collections.Generic;
using Microsoft.Extensions.FileSystemGlobbing;
using NUnit.Framework;

namespace Repro;

[TestFixture]
public class ReproTests
{
    [Test]
    public void TestGlobBugRepro()
    {
        var globMatcher = new Matcher(StringComparison.Ordinal);
        globMatcher.AddInclude("/*/");

        var dir = new InMemoryDirectoryInfo(
            rootDir: "/", 
            files: new List<string> { "/a/b" });

        var patternMatchingResult = globMatcher.Execute(dir);
        Assert.That(patternMatchingResult.HasMatches, Is.False);
    }
}
```

`.csproj` file for the above:

``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>Nullable</WarningsAsErrors>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.1.0" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.2.1" />
    <PackageReference Include="NUnit.Analyzers" Version="3.3.0" />
    <PackageReference Include="coverlet.collector" Version="3.1.2" />
  </ItemGroup>
</Project>
```

### Expected behavior

Expected for a call to `Microsoft.Extensions.FileSystemGlobbing.Matcher.Execute` for glob pattern `/*/` and file path `/a/b` to return no matches.

### Actual behavior

A call to `Microsoft.Extensions.FileSystemGlobbing.Matcher.Execute` for glob pattern `/*/` and file path `/a/b` did return a match.

### Regression?

I don't know.

### Known Workarounds

None.

### Configuration

`.csproj` file from the repro:

``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>Nullable</WarningsAsErrors>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.1.0" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.2.1" />
    <PackageReference Include="NUnit.Analyzers" Version="3.3.0" />
    <PackageReference Include="coverlet.collector" Version="3.1.2" />
  </ItemGroup>
</Project>
```

**Comment by konrad-jamrozik** [comment]
Area label probably should be `area-Extensions-FileSystem`. FYI @jeffhandley

**Comment by kant2002** [comment]
Are you sure that this is not error in test infra because test was run on Windows? Line below convert `/` to `c:\`

https://github.com/dotnet/runtime/blob/3454d8c7fc1ee1a1a64f61b3b7df27d1b922b922/src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/InMemoryDirectoryInfo.cs#L53-L58

If I understand correctly this is same test using existing test infra, and it passed.

```csharp
[Fact]
public void TestGlobBugRepro2()
{
    var matcher = new Matcher();
    var scenario = new FileSystemGlobbingTestContext(@"/", matcher)
        .Include("/*/")
        .Files("a/b")
        .SubDirectory("a")
        .Execute();

    scenario.AssertExact();
}
```

**Comment by konrad-jamrozik** [comment]
> Are you sure that this is not error in test infra because test was run on Windows? Line below convert `/` to `c:\`
> 
> https://github.com/dotnet/runtime/blob/3454d8c7fc1ee1a1a64f61b3b7df27d1b922b922/src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/InMemoryDirectoryInfo.cs#L53-L58
> 
> If I understand correctly this is same test using existing test infra, and it passed.
> 
> ```cs
> [Fact]
> public void TestGlobBugRepro2()
> {
>     var matcher = new Matcher();
>     var scenario = new FileSystemGlobbingTestContext(@"/", matcher)
>         .Include("/*/")
>         .Files("a/b")
>         .SubDirectory("a")
>         .Execute();
> 
>     scenario.AssertExact();
> }
> ```

@kant2002, please note I am using the code I have shown in production, I am not using it as test harness. The only test-specific line is `Assert.That(patternMatchingResult.HasMatches, Is.False);`. The context is I was writing a parser for matching a path against entries in CODEOWNERS file. Hence I had to use `InMemoryDirectoryInfo` to coerce the matcher API to allow me to match one input path against just one GLOB pattern.

I wrote [50+ test cases](https://github.com/Azure/azure-sdk-tools/blob/6200ed435450eacd0816ce57fd1205071dc645f6/tools/code-owners-parser/Azure.Sdk.Tools.CodeOwnersParser.Tests/CodeOwnersFileTests.cs#L31-L114) and the matcher behaved correctly on all of them, except this one. So I would say this is an unexpected and surprising behavior, and should be fixed.

**Comment by Jozkee** [comment]
I understand that this doesn't align with other globbers but this is an intended behavior.

https://github.com/dotnet/runtime/blob/daa07f8e7ce28e5aba2d32ff586b261839adf91f/src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/Internal/Patterns/PatternBuilder.cs#L34-L38

if your pattern ends with a separator `/`, we will append a recursive wildcard `**` which means that it needs to match all entries within that directory.

I think the best solution for this case is to trim the `/` at the end.

**Comment by konrad-jamrozik** [comment]
@Jozkee thanks for the explanation. I think it would be worthwhile to mention this in the documentation, e.g. in these two places:

https://learn.microsoft.com/en-us/dotnet/core/extensions/file-globbing#pattern-formats
https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.filesystemglobbing.matcher?view=dotnet-plat-ext-7.0#remarks

It says:

<html>
<body>


`**/*` | All files in any subdirectory.
-- | --



</body>
</html>

I believe that it could also say:

<html>
<body>


`/` | All files in any subdirectory, i.e. equivalent to `/**`.
-- | --



</body>
</html>
