### ISSUE TITLE
Setting max worker threads of ThreadPool neither work nor fail

### ISSUE THREAD

**Issue by xiaomi7732** [dotnet/runtime#80072]
### Description

1. It is unclear what the max allowed values are - it would be helpful to clarify it [here](https://learn.microsoft.com/en-us/dotnet/api/system.threading.threadpool.setmaxthreads?view=net-7.0)
2. Assuming 32767 (default on my box), set a number greater than it, the settings won't change (remain 32767) and the API's returning `true` as a result.

Expectation:
1. Either, the API returns false - so that the client knows the new value is not in effect or allows the new value.

### Reproduction Steps

```csharp
ThreadPool.GetMaxThreads(out _, out int maxCompletionPortThreads);

if(ThreadPool.SetMaxThreads(40000, maxCompletionPortThreads)) // 40000 was made up, anything greater than the max.
{
    Console.WriteLine("Success set maximum.");
    ThreadPool.GetMaxThreads(out int maxWorkerNewValue, out _);
    Console.WriteLine("New value: {0}", maxWorkerNewValue);  // output: 32767
}
```

### Expected behavior

`SetMaxThreads` should return false since the value wasn't accepted.

### Actual behavior

It returns true.

### Regression?

N/A

### Known Workarounds

Check the actual value after setup, and verify they are equal.

### Configuration

Tried on .NET 6 / .NET 7, probably on all runtimes.

**Comment by theodorzoulias** [comment]
Related issue: Behaviour of ThreadPool.SetMaxThreads(-1, -1) #29265

**Comment by xiaomi7732** [comment]
Yes, it would be difficult for the user to set to max-possible. The problem is, leaving the API as is gives a false impression while reading the code.

For example, after reading these 3 lines, would we expect the actual max thread to be `32767`? Especially when the return values are all true.
```csharp
ThreadPool.SetMaxThreads(1000, 1000);
ThreadPool.SetMaxThreads(40000, 40000);
ThreadPool.SetMaxThreads(40000, 40000);
```

I understand the problem is then how does the user set it to max-allowed?

Two potential solutions come to mind:

1. Introduce a designated value, such as 0, to represent the maximum limit:

    ```csharp
    ThreadPool.SetMaxThreads(0, 0); //Configuring for maximum capacity
    ```

1. Offer an alternative method with clearer semantics:

    ```csharp
    ThreadPool.GetMaxAllowedThreads(out int maxAllowedWorkers, maxAllowedCompletionPortThreads); // Provides insights into the true limits
    ThreadPool.SetMaxThread(maxAllowedWorkers, maxAllowedCompletionPortThreads);
    ```

Both approaches would require appropriate documentation. However, they provide a transparent view of the actual settings.

Another potential (though disruptive) enhancement would involve returning the actual values as a tuple, rather than a single boolean. However, this could involve break changes that might not be feasible at this point.

**Comment by kouvel** [comment]
I agree the return value of `true` can be misleading in that case, though it can probably be resolved by clarifying in the docs. Returning `false` in those cases also feels awkward to me, and I guess would technically be a breaking change.

> Introduce a designated value, such as 0, to represent the maximum limit

Currently, the designated value can be thought of as `int.MaxValue`, as `SetMaxThreads(int.MaxValue, int.MaxValue)` would set the maximum thread counts to the highest values supported by the thread pool implementation. I don't see a significant benefit from exposing what the underlying limit actually is with a new property/method, and there is also a (perhaps roundabout) way to get the limit.
