### ISSUE TITLE
[browser][documentation] How-to add dotnet component into existing JavaScript application

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#80098]
Detailed how to document explaining https://github.com/maraf/dotnet-wasm-react and alternative strategies for embedding dotnet on wasm into existing non-blazor app.

- [ ] list of assets, directory they could be taken from -> `AppBundle`
- [ ] correct MIME type for each file type
- [ ] COOP HTTP headers
- [ ] list of public MSBuild flags
- [ ] few details about trimming and AOT
- [ ] hints about caching headers and cache busting
- [ ] few hints about (brotli) compression
- [ ] hints about invariant locales to reduce size
- [ ] what's good default value for initial memory size
- [ ] tutorial on how to marshal memory with `MemoryView`
- [ ] hints about bundling and if it's worth it
- [ ] link to dotnet.d.ts
- [ ] about source maps and debug symbols
- [ ] how to trim JSON serializer 
- [ ] Give hints about download size/speed/code maintanance tradeoffs.
- [ ] Jiterpreter
- [ ] few details about blazor.boot.json
- [ ] wwwroot, _framework, AppBundle

**Comment by pavelsavara** [comment]
@danroth27 if you have specific details you want us to include, please chime in

**Comment by pavelsavara** [comment]
- list of assets, directory they could be taken from -> `AppBundle`
- correct MIME type for each file type
- COOP HTTP headers
- list of public MSBuild flags in Net7
- few details about trimming and AOT
- hints about caching headers and cache busting
- few details about mono-config.js
- few hints about (brotli) compression
- hints about invariant locales to reduce size

**Comment by pavelsavara** [comment]
cc @guardrex

**Comment by guardrex** [comment]
@pavelsavara ... If it's for the ASP.NET Core doc set, I *guesstimate* that it either goes SxS with the React doc at ...

https://learn.microsoft.com/aspnet/core/client-side/spa/react

... or in the parent folder of the *Single Page Apps* node, which is the *Client-side development* node.

**Comment by pavelsavara** [comment]
@guardrex https://learn.microsoft.com/en-us/aspnet/core/client-side/dotnet-interop in the `client-side` could be possibly split into 2 pages. Take bits about embedding/deployment into new page and add the missing details ?

**Comment by guardrex** [comment]
You'll need to indicate what to split. It might be faster if you split it and create the new article, and then I'll perform an edit to the two topics on your PR.

**Comment by pavelsavara** [comment]
Sure, we will draft it and let you know. Thanks @guardrex

**Comment by pavelsavara** [comment]
by @ryanwinter
- Don't bundle the `dotnet.js`. It's really big anyway and there is a lot of things that need to align there
- Relating too 1, calling the module through dynamically import with `webpackIgnore: true` syntax will tell webpack to not bundle, there should be similar patterns for other packaging tools. Otherwise it might be simpler to tell the packager directly to not bundle. 
- There are many supplementary files (js, DLL's, json, etc) that need to be served, and your packager will need to handle these separately.

**Comment by vishnureddy17** [comment]
My feedback on documentation:

- A lot of relevant csproj properties are unclear:
    - OutputType has to be Exe
    - Various properties to reduce bundle size, and the tradeoffs of using them
- It'd be good to have documentation on the API surface exposed by `dotnet.js`, or at least make the type definitions easier to locate.
- Making an unminified version of `dotnet.js` available could be useful for users trying to troubleshoot and understand what is going on
- There are some Blazor docs that are useful to non-Blazor JS Interop users. It'd be clearer to people if the Blazor name was dropped from those docs.

**Comment by guardrex** [comment]
> There are some Blazor docs that are useful to non-Blazor JS Interop users. It'd be clearer to people if the Blazor name was dropped from those docs.

I don't think that will happen, as we're keeping our Blazor coverage focused on Blazor. However, you could indicate what parts you find useful for more coverage in the *Client-side development*/*SPA* node of the docs. I think that's a ***new issue*** tho and would be worked separately from this issue. @pavelsavara would need to confirm if I'm right about that.

**Comment by danroth27** [comment]
> There are some Blazor docs that are useful to non-Blazor JS Interop users. It'd be clearer to people if the Blazor name was dropped from those docs.

@vishnureddy17 Which Blazor docs specifically are you referring to?

**Comment by vishnureddy17** [comment]
> @vishnureddy17 Which Blazor docs specifically are you referring to?

One example is the table of type mappings in [this doc](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/import-export-interop?view=aspnetcore-7.0#call-javascript-from-net). I was referencing that table in the doc even though I wasn't using Blazor. There might be others as well.

**Comment by guardrex** [comment]
@vishnureddy17 ... The same table is in the non-Blazor version (for JS devs) of the doc at ...

https://learn.microsoft.com/en-us/aspnet/core/client-side/dotnet-interop?view=aspnetcore-7.0#javascript-interop-on-

There's an INCLUDE file on the repo, and that file is injected into both docs.

**Comment by pavelsavara** [comment]
Making JSON trimming friendly
```
[JsonSerializable(typeof(List<Item>))]
partial class ItemListSerializerContext : JsonSerializerContext { }

var json = JsonSerializer.Serialize(items, ItemListSerializerContext.Default.ListItem);

```

**Comment by pavelsavara** [comment]
Give hints about download size/speed/code maintanance tradeoffs.

"The Blazor wasm is running on Mono runtime, which has interpreter and and AOT options, but not JIT.
When you use wasm-tools workload, you could AOT compile your application together with the Mono runtime.
The runtime will be always part of the download. Usually it takes few MB with non trivial application."

**Comment by danroth27** [comment]
> but not JIT

Except on .NET 8 we now have the Jiterpreter! :rocket:
