### ISSUE TITLE
ArrayTypeMismatchException in nested arrays with function pointers (android)

### ISSUE THREAD

**Issue by oleg-st** [dotnet/runtime#80095]
### Description

The code below throws `System.ArrayTypeMismatchException` when run in Android emulator (MAUI project targeting Android).
It works fine in windows.

### Reproduction Steps

```csharp
unsafe class Program
{
    public static delegate* managed<int>[][] Functions = {
        new delegate* managed<int>[]
        {
            &Function,
        },
    };

    public static int Function() => 42;
}
```

### Expected behavior

No exception

### Actual behavior

System.ArrayTypeMismatchException: 'Attempted to access an element as a type incompatible with the array.'

### Configuration

Host:
  Version:      7.0.1
  Architecture: x64
  Commit:       97203d38ba

OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows

**Comment by fanyang-mono** [comment]
When I added the piece of code that @oleg-st mentioned above into the app that I created using `dotnet new maui`, the app crashed right after launching. I wasn't able to reproduce this exact error `System.ArrayTypeMismatchException`. @oleg-st Could you please provide the whole repro MAUI project?

**Comment by oleg-st** [comment]
[MauiApp1.zip](https://github.com/dotnet/runtime/files/10355339/MauiApp1.zip)
Running under Android Emulator : Pixel 5 - API 33 (Android 13.0 - API 33)

**Comment by mattleibow** [comment]
Managed to repro this in a plain Android app:


```cs
[Activity(Label = "@string/app_name", MainLauncher = true)]
public class MainActivity : Activity
{
    protected override void OnCreate(Bundle? savedInstanceState)
    {
        base.OnCreate(savedInstanceState);
        SetContentView(Resource.Layout.activity_main);

        // call the code
        var result = TestThings.Function();
        Console.WriteLine(result);
    }
}

unsafe class TestThings
{
    public static delegate* managed<int>[][] Functions = {
        new delegate* managed<int>[]
        {
            &Function,
        },
    };

    public static int Function() => 42;
}
```

I had to use a separate (non Java Object) class, otherwise the JNI process crashes in java so we lose the exception.

**Comment by fanyang-mono** [comment]
I was able to reproduce this issue with console app using interpreter

```
using System;

namespace HelloWorld
{
    unsafe class TestThings
    {
        public static delegate* managed<int>[][] Functions = {
            new delegate* managed<int>[]
            {
                &Function,
            },
        };

        public static int Function() => 42;
    }

    internal class Program
    {
        private static void Main(string[] args)
        {
            var result = TestThings.Function();
            Console.WriteLine(result);
        }
    }
}
```

**Comment by fanyang-mono** [comment]
The fix to this issue will be backported to .NET7.
