### ISSUE TITLE
Implement an async version of the blocking System.Console.ReadKey

### ISSUE THREAD

**Issue by rkeithhill** [dotnet/runtime#801]
In the PowerShell extension for Visual Studio Code, we have an async REPL loop where we'd love to be able to `await Console.ReadKeyAsync()` rather than blocking on `Console.ReadKey()`.   

The current implementation is problematic because we need cancellation support.  We have tried to work around the blocking ReadKey() call by using KeyAvailable() but there is a known issue with KeyAvailable() causing the characters to be echo'd to the screen on Linux which is not desirable when you're asking for a user's password.

**Comment by daveyostcom** [comment]
I don't see why this is not feasible. I imagine a dedicated thread that polls the device 20x a second and puts available keys into a [thread-safe queue](https://stackoverflow.com/a/21225922/1390116), to be read asynchronously by ReadKeyAsync().
