### ISSUE TITLE
Replace `Unsafe.NullRef<T>()` usage

### ISSUE THREAD

**Issue by xtqqczze** [dotnet/runtime#80107]
Use `ref *(T*)null`instead of `Unsafe.NullRef<T>()` to save 3 bytes of IL ([sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBLANgHwAEAGAAkIEYA6AJQFcA7DbAWxioGEIWAHPGKAGUBAN2xgYAZwDcAWABQCwgGZyAJlIdSAbwWl95VY0kBDAGYxSsM6WABPDJYCyxABQBKHXoM/CAdisYGwBVBlMLKgA5OlxcGiCAHntHAD4POXkfAF9vfRVSY3NLa1sHZwoPL0yfA39AmwAqV2SYBvcGGNwM7IUsoA)).

> Slightly smaller IL size (saves 3 bytes) an most importantly avoids a generic type instantiation. Could also potentially help the JIT in some niche cases, though it should handle `NullRef` well too given it's an intrinsic now. I'd also say conceptually it seems to me `ref *(T*)null` makes more sense in that the `Unsafe` APIs were all added as a workaround for things that could not be done at all in C#. Now that C# _can_ express this, there's no need to use the workaround API anymore. It's the same with `Unsafe.SizeOf<T>`: now that you can just do `sizeof(T)` everywhere, there's no need to ever use that either. Same thing for `Unsafe.As` in some context, now that you can have pointers to managed types 🙂
> 
> Like, if hypothetically speaking you could do everything you can do with `Unsafe` with just C#, you'd never use `Unsafe`, and for the same reason if C# had always been able to express all of it, `Unsafe` APIs would've never been added in the first place.

_Originally posted by @Sergio0694 in https://github.com/dotnet/runtime/pull/79589#discussion_r1052505754_

**Comment by tannergooding** [comment]
I’m not convinced this is better. It certainly results in smaller IL but it also comes at the cost of being harder to read/reason about in many ways, particularly due to the cast and indirections.

For optimized code we’re already able to see this is an intrinsic and so we can adjust the inlining profitability accordingly. We could likely adjust the IL cost as well if we believed it to have significant impact.

cc. @jkotas

**Comment by jkotas** [comment]
I agree with @tannergooding. The savings are very small, not worth the style and readability degradation.

(Also, this would be asymmetric with `Unsafe.IsNullRef`.)
