### ISSUE TITLE
Inconsistent Uri c'tor implementation  for Windows and Linux

### ISSUE THREAD

**Issue by jvmlet** [dotnet/runtime#80118]
### Description

`new Uri("/path")`  throws exception when running on Windows  
`new Uri("/path")`  creates `file://` Uri scheme  when running on Linux

### Reproduction Steps

Execute `new Uri("/path")` on `Windows` and on `Linux`

### Expected behavior

Consistent behavior 

### Actual behavior

`new Uri("/path")`  throws exception when running on Windows  
`new Uri("/path")`  creates `file://` Uri scheme  when running on Linux

### Configuration

net6.0

**Comment by vcsjones** [comment]
This is by design for Linux. `Uri` supports file paths, and `/path` is a valid file path.

See https://github.com/dotnet/runtime/issues/76816 for additional info.

**Comment by MihaZupan** [comment]
This is (unfortunately) by design. `Uri` supports parsing file paths to some extent, and `/path` is a valid absolute file path on Linux, but not on Windows.
See #76816 or #69308

Once https://github.com/dotnet/runtime/issues/59099#issuecomment-919412394 is implemented, you should be able to avoid this by doing
```c#
var options = new UriCreationOptions
{
    UriKind = Urikind.Absolute,
    AllowImplicitFilePaths = false
};

Uri.TryCreate("/path", options, out Uri uri)
```

**Comment by MihaZupan** [comment]
Ah, you're fast @vcsjones 😄

**Comment by afurer** [comment]
@vcsjones ,
> This is by design for Linux

is not compliant with statement  that  `dotnet` is  `OS` agnostic, unfortunately.

**Comment by afurer** [comment]
I understand that OS behaviors **ARE** different, just such `.net` statement  should have `stars` underneath.

**Comment by jvmlet** [comment]
Please make sure to have documentation warning on `Uri` constructor that describes this inconsistency and advises to use factory method.
Roslyn analyzer that catches direct Uri constructor invocation will help delevopers to not spending time investigating `.Net` by-design behaviors.
