### ISSUE TITLE
Two dimensional array with function pointers in .NET Framework (debug)

### ISSUE THREAD

**Issue by oleg-st** [dotnet/runtime#80112]
### Description

The code below throws `System.AccessViolationException` when run in .NET Framework (debug build).
Works fine in release build

### Reproduction Steps

```csharp
using System;

namespace TestFP;

public static unsafe class Program
{
    public static int Function() => 42;

    static void Main(string[] args)
    {
        var functions = new delegate* managed<int>[,] {
            {
                &Function,
            },
        };
        Console.WriteLine(functions[0, 0]());
    }
}
```

### Expected behavior

42

### Actual behavior

System.AccessViolationException

### Configuration

OS Name: Windows
OS Version: 10.0.19044
OS Platform: Windows

**Comment by vcsjones** [comment]
Generally, this repository is for issues for .NET Core and .NET. For issues with .NET Framework, issues should be filed at https://developercommunity.visualstudio.com/dotnet/report.

I will point out however that function pointers are a C# 9 feature, and .NET Framework only (officially) [supports up to C# 7.3](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version):

> C# 9 is supported only on .NET 5 and newer versions.

 It's known that some C# features don't work with .NET Framework.
