### ISSUE TITLE
Assertion failure: uint32_t GCEvent::Impl::Wait(uint32_t, bool): Assertion `(st != 110) || !m_state' failed

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#80166]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=123072
Build error leg or test failing: LibraryImportGenerator.Unit.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/79505

## Error Message

```json
{
  "ErrorMessage": "uint32_t GCEvent::Impl::Wait(uint32_t, bool): Assertion `(st != 110) || !m_state' failed",
  "BuildRetry": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[123072](https://dev.azure.com/dnceng-public/public/_build/results?buildId=123072)|dotnet/runtime|[LibraryImportGenerator.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=123072&view=ms.vss-test-web.build-test-results-tab&runId=2646424&resultId=195600)|dotnet/runtime#79505|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|1|

**Comment by janvorli** [comment]
The assert is incorrect, based on the `pthread_cond_timed_wait` doc (https://linux.die.net/man/3/pthread_cond_timedwait):
> #### Condition Wait Semantics
> It is important to note that when `pthread_cond_wait()` and `pthread_cond_timedwait()` return without error, the associated predicate may still be false. Similarly, **when `pthread_cond_timedwait()` returns with the timeout error, the associated predicate may be true due to an unavoidable race between the expiration of the timeout and the predicate state change.**

I have put in this assert when implementing the event stuff many years ago.

I will create a PR removing it.
