### ISSUE TITLE
Misleading error "Cannot delete an already deleted object"

### ISSUE THREAD

**Issue by ryanwilliams83** [dotnet/runtime#80167]
### Description

When I attempt to access the SamAccountName property of a deleted UserPrincipal instance.
The error message of "Cannot delete an already deleted object" is misleading.

Please consider changing it to "Cannot **access** an already deleted object"

[System.DirectoryServices.AccountManagement/src/Resources/Strings.resx](https://github.com/dotnet/runtime/blob/20744776437ab483b3e68d608996fdcf1b02420b/src/libraries/System.DirectoryServices.AccountManagement/src/Resources/Strings.resx#L153)

Helpful Search
https://github.com/dotnet/runtime/search?q=PrincipalDeleted&type=code

### Reproduction Steps

Call .Delete() on a UserPrincipal instance and then attempt to get the .SamAccountName property.

### Expected behavior

InvalidOperationException with different message

### Actual behavior

InvalidOperationException with misleading error message

**Comment by buyaa-n** [comment]
That message is used for many actions including `Delete`:
https://github.com/dotnet/runtime/blob/5da4a9e919dcee35f831ab69b6e475baaf798875/src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/Principal.cs#L444-L449
So probably we should pass the action (access/delete etc) to the `CheckDisposedOrDeleted(string action)` method and populated more meaningful message something like `$"Cannot {action} an already deleted object"`

**Comment by pedrobsaila** [comment]
@buyaa-n CheckDisposedOrDeleted is a protected method. If we add a parameter, we'll break compatibility with .net 6.0 and .net 7.0. Is it ok to do it ? if so I can work on it.

**Comment by buyaa-n** [comment]
Right thanks, did not notice that it was protected method of public abstract type, we cannot make such breaking change.

Apparently updating the message "Cannot delete an already deleted object" to "Cannot access an already deleted object" is better
