### ISSUE TITLE
(An error occurred while deserializing the Fields property of class divitiae_api.Models.Item: Cannot dynamically create an instance of type 'System.Text.Json.Nodes.JsonObject'. Reason: No parameterless constructor defined.)

### ISSUE THREAD

**Issue by Drojanx** [dotnet/runtime#80161]
I have this class in my project called Item:
````
        public class Item
        {
            [BsonId]
            public ObjectId Id { get; set; }
            public string AppId { get; set; }
            public JsonObject Fields { get; set; }

        }
````

And I've successfully POSTed a couple of items to my Mongo DB.

The problem occurs whenever I try to GET those items, the error I said in the title pops up:
````
(An error occurred while deserializing the Fields property of class divitiae_api.Models.Item: 
Cannot dynamically create an instance of type 'System.Text.Json.Nodes.JsonObject'. Reason: No parameterless constructor defined.)
````
What would be the best solution to this issue? I've tried defining a parameterless constructor, but it keeps on failing.

**Comment by eiriktsarpalis** [comment]
Judging by the attribute, your code is using System.Text.Json DOM types on the Newtonsoft.Json.Bson serializer. I wouldn't expect that combination to work out of the box, so I would recommend switching to Json.NET's own `JObject` type.
