### ISSUE TITLE
Clarification required on WinHttpHandler connection lease

### ISSUE THREAD

**Issue by cool-mist** [dotnet/runtime#80163]
When using WinHttpHandler, 

1. how long does a connection remain active? Is there a way to configure this? (something like a connection lease timeout)
2. When does dns resolution happen? Does it happen for each request using that connection? or is it fixed per connection?

**Comment by ManickaP** [comment]
@antonfirsov do you know answers to these questions?

**Comment by wfurt** [comment]
While we may try to answer the question, I feel this is implementation detail that is own by `WinHTTP` and it can vary among version and change in future without any warning.

**Comment by antonfirsov** [comment]
I emailed the WinHttp team to get an answer for this, will post a reply here when they come back to me.

I found a related https://github.com/dotnet/runtime/issues/23947#issuecomment-339167964 from the past stating that

> - Idle connections aren’t used after 1 minute of inactivity.
> - There is a periodic scavenger that runs every 2 minutes to remove/close these connections. They are also removed/closed when a request comes in and sees that they are past the idle timeout.

however this might have changed since then.

I wonder what is the context for this question. @cool-mist are you experiencing issues with DNS expiration?

**Comment by antonfirsov** [comment]
Answers:

> 1. How long does a connection remain active? Is there a way to configure this? (something like a connection lease timeout)

The connections are pooled per WinHttpHandler instance. The connection idle timeout is 1 minutes, and there is no way to configure it. As noted in https://github.com/dotnet/runtime/issues/80163#issuecomment-1400871318, this value is indeed an undocumented implementation detail that may change in the future.

> 2. When does dns resolution happen?

Whenever a new connection is established. There's no need to resolve DNS if an existing connection is being reused for a request.

Closing this as answered for now, but let us know if you have any follow-up questions!

**Comment by cool-mist** [comment]
Thanks @antonfirsov - I have seen these values configurable or documented for other http message handlers. So was curious how to do this here.

I have few other questions as well
1. What is the connection lease timeout? - is there a way we can specify how long a connection should remain active? The idle timeout behavior that you've noted above seems to imply that the connection will be closed ONLY when the connection is idle. What if the connection is not idle and there is a constant flow of requests?

2. What is the connection reuse behavior? What is the total number of distinct connections that will be opened by this handler to a target url before deciding to not open anymore? is there a way to configure it?

**Comment by antonfirsov** [comment]
> 1. What is the connection lease timeout? - is there a way we can specify how long a connection should remain active? The idle timeout behavior that you've noted above seems to imply that the connection will be closed ONLY when the connection is idle. What if the connection is not idle and there is a constant flow of requests?

This is a WinHttp implementation detail, so I don't know the answer for sure. To me the straightforward implementation logic (which we follow in .NET Core/5+ SocketsHttpHandler) would be that a connection only becomes idle if a request is completed and it's returned to the pool, meaning that the connection becomes available for other requests. If you do streaming that keeps a connection alive for a long time, it won't become idle and won't be scavenged.

> 2. What is the maximum connection pool size? Is there a way to configure it per url group? (or configure it at all?)

You are looking for [`WINHTTP_OPTION_MAX_CONNS_PER_SERVER`](https://learn.microsoft.com/en-us/windows/win32/winhttp/option-flags#winhttp_option_max_conns_per_server), which is exposed through [`WinHttpHandler.MaxConnectionsPerServer`](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.winhttphandler.maxconnectionsperserver?view=dotnet-plat-ext-7.0). Note that this counts connections per [`IdnHost`](https://learn.microsoft.com/en-us/dotnet/api/system.uri.idnhost?view=net-7.0), not per full URL path.

**Comment by cool-mist** [comment]
> This is a WinHttp implementation detail, so I don't know the answer for sure. To me the straightforward implementation logic (which we follow in .NET Core/5+ SocketsHttpHandler) would be that a connection only becomes idle if a request is completed and it's returned to the pool, meaning that the connection becomes available for other requests. If you do streaming that keeps a connection alive for a long time, it won't become idle and won't be scavenged.

Thanks. So this, along with the rotation logic in [DefaultHttpClientHandler](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Http/src/DefaultHttpClientFactory.cs) should fix both the socket exhaustion and stale DNS problems for WinHttpHandler.

> Note that this counts connections per [IdnHost](https://learn.microsoft.com/en-us/dotnet/api/system.uri.idnhost?view=net-7.0), not per full URL path.

Hmmm.. this sounds bad (unless I'm misunderstanding). Generally, it should be a combination of host/url + the auth scheme used to talk to the host. (which is what [ServicePoint ](https://referencesource.microsoft.com/#System/net/System/Net/HttpWebRequest.cs,5395) does for security reasons).

> This is a WinHttp implementation detail, so I don't know the answer for sure

Do you happen to know who can help here with the internal implementation details? The code does reside in this repository, so I presume, someone from this project group should know?
