### ISSUE TITLE
Possible QuicConnection leak

### ISSUE THREAD

**Issue by pepone** [dotnet/runtime#80172]
This method is called during the disposal of the listener.

https://github.com/dotnet/runtime/blob/88f75a83803a3b7fe59bcdb3eb748eefa4d35ddb/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicListener.PendingConnection.cs#L99

If the _finishHandshakeTask task has already been completed successfully the QuicConnection held by this task is never disposed of, and this is the only reference left to it.

**Comment by halter73** [comment]
There seems to be a similar issue any time `PendingConnection.FinishHandshakeAsync` gets canceled. While not ideal, hopefully the `MsQuicContextSafeHandle` at least cleans things up in either case, right?

**Comment by ManickaP** [comment]
Yep and yep, problem is the same with cancellation, and `MsQuicContextSafeHandle` cleans up eventually, after GC collects the main object.
