### ISSUE TITLE
release/6.0 does not build cleanly with LLVM 13 / Xcode 13.3

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#80208]
The issue described in https://github.com/dotnet/runtime/issues/66770 was fixed in `main` for .NET 7, but it was never back ported to `release/6.0`. Could we consider backporting https://github.com/dotnet/runtime/pull/67543 to `release/6.0`?

This prevents a clean build of the runtime using Xcode 13.3+ Developer Tools. You'll see errors like 

```
EXEC : error : ignoring unknown option: --minimize [/Users/vcsjones/Projects/runtime/src/libraries/Native/build-native.proj]
```

**Comment by ViktorHofer** [comment]
cc @lambdageek @hoyosjs @bartonjs

**Comment by ViktorHofer** [comment]
> Could we consider backporting https://github.com/dotnet/runtime/pull/67543 to release/6.0?

Just talked about this in our triage meeting. Feel free to send a backport @vcsjones.

cc @hoyosjs

**Comment by vcsjones** [comment]
Fixed by https://github.com/dotnet/runtime/pull/81042
