### ISSUE TITLE
[wasm] Review compiler options (again)

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#80217]
We're currently generating and processing full dwarf debug information for native and aot'd methods, then in a separate pass stripping that information in release mode (depending on several options) this can add substantial time and memory overhead.  We need to review the emscripten compiler options and optimize the default case better.  As part of the process we should review some of the properties we use and see if there is an easy way to surface some of them to the customer.
- [x] debug info
- [x] initial memory
- [ ]  TrimMode -> remove partial setting https://github.com/dotnet/runtime/pull/89110
- [x] Memory size

see https://github.com/dotnet/runtime/issues/79874 https://github.com/dotnet/runtime/pull/80103

**Comment by pavelsavara** [comment]
- explore `-Oz` vs `-O2` in dotnet.wasm of the runtime pack.
- figure out if `-fPIC` is a good thing for us
- figure out what makes the data section break into thousands of sections vs just two in AOT. Maybe [wasm-ld](https://github.com/llvm/llvm-project/blob/540e58af6692bf373d9be4f99d320b4b0f753e3b/lld/wasm/Writer.cpp#L1592) ?

**Comment by lewing** [comment]
to expand a bit:
1) the tests are exceptional in that they by design use most of the api surface and as a result are hard to AOT so we use special options to the compiler to stay inside container limits
2) our default settings generate and process dwarf info in the first linker pass and that info causes some really degenerate behavior in wasm-opt when it has to process all the relocations for all the symbols.  we really only use the name and possibly line information in the dwarf symbols, and we strip that information on publish so we should probably change our options to stop doing the expensive in time and space relocation processing
that patch fixes 1. for some of the tests (-01 skips wasm-opt in finalize)
there might be other cases we should tweak 
fixing 2. would fix the default case

**Comment by pavelsavara** [comment]
https://github.com/emscripten-core/emscripten/issues/15269#issuecomment-1012652696
