### ISSUE TITLE
Memory leak in blazor server application .net 7

### ISSUE THREAD

**Issue by alanma75** [dotnet/runtime#80258]
### Description

as planned .net 7 upgrade on our existing blazor projects, we noticed memory usage on performance test increased drastically, with dockerized container we can drive the application to OOM exception. 
reproduced and profiled locally, it shows the top locking objects are ConcurrentDictionary+Tables<JsonSerializerOptions, WeakReference<JsonSerializerOptions+CachingContext>>
https://github.com/dotnet/runtime/issues/76548 - this issue was already reported in November 2022. 

this is blocking us from upgrading an important application in production to .net 7. I have attached the sample project to demonstrate the OOM exception, with GCHeapHardLimit set to 1GB, 10+ webpage reload of blazor application will get OOM exception. 

### Reproduction Steps

Launch blazor server application attached, open http://localhost:5000 to load the sample application, refresh the page and observe the memory increasing with Generation2 stack and not be able to free after GC.

using the HeapHardLimit value in the sample (1GB), observe OOM exception in about 10 reloads

### Expected behavior

Memory properly GCed

### Actual behavior

OOM exception occurs

### Regression?

this is new in .net 7 with the C

### Known Workarounds

no workarounds

### Configuration

.net 7
it happens in all OS
[telerikgridhorscrollingapp.zip](https://github.com/dotnet/runtime/files/10355267/telerikgridhorscrollingapp.zip)

**Comment by alanma75** [comment]
![image](https://user-images.githubusercontent.com/13609471/210870098-9938c9fb-5caa-48a2-b1cb-82be655ac12e.png)

![image](https://user-images.githubusercontent.com/13609471/210870320-307233d5-e962-4e6a-8861-190b9da10c53.png)
from dotMemory profiling

**Comment by jeffhandley** [comment]
I was able to install the 30-day trial of the Telerik UI for Blazor and update the project to use `Telerik.UI.for.Blazor.Trial` version 3.7.0 to reproduce the issue. Note to @dotnet/area-system-text-json folks that I also tried the repro against a net8.0 build that incorporates #76607, and memory still climbs with each reload. Also note that the repro app produces other errors when (re)loading the page, but that does not interfere with the reported issue.

There's nothing in this repro app itself that uses System.Text.Json directly, which means the actual repro here is down in the Telerik layer's use of JSON serialization.

**Comment by alanma75** [comment]
![image](https://user-images.githubusercontent.com/13609471/211035619-40b81d45-ec5d-4e0e-af16-756b6aaf5885.png)
the main change in the fix is not having the ConcurrentDictionary with key JsonSerializerOptions, that hold a strong reference of each instance in blazor circuit (session). and the size of that JsonSerializerOptions can get big in our test. 

the new Array of weakReference will not have such issue, so under normal GC, the heap will be able to reduce, from my read of the code changes.

**Comment by eiriktsarpalis** [comment]
I haven't checked the repro yet, but this sounds somewhat different to the report in https://github.com/dotnet/runtime/issues/76548. The original issue reported increased memory consumption when the application remained idle, however the dangling cache entries would get immediately evicted on the first subsequent serialization operation. This case sounds like an unbounded memory leak, which is a problem of a whole new magnitude.

**Comment by jeffhandley** [comment]
I used the repro to capture memory dumps. I've shared them offline.

**Comment by eiriktsarpalis** [comment]
@jeffhandley @ericstj @SteveSandersonMS I think at this point we have enough evidence showing that this is impacting Blazor apps in a substantial way, and we should be backporting #76607 to .NET 7.

**Comment by jeffhandley** [comment]
OK; thanks, @eiriktsarpalis! With that evidence, I'm supportive of backporting #76607; do you have enough data to file an actionable issue against MemoryCache as well?

**Comment by eiriktsarpalis** [comment]
> do you have enough data to file an actionable issue against MemoryCache as well?

No. It may well be how `MemoryCache` is used. I would recommend filing an issue against Telerik support for that.

**Comment by alanma75** [comment]
sure, is this new in .net 7? if not I will check .net 6 as well, thanks

**Comment by eiriktsarpalis** [comment]
> sure, is this new in .net 7? 

If you're asking about the `JsonSerializerOptions` cache, then yes. I'm not sure where the `MemoryCache` usage comes from.

**Comment by alanma75** [comment]
I was asking about  MemoryCache, will check .net 6 on the usage, thanks

**Comment by eiriktsarpalis** [comment]
Backported to .NET 7 via https://github.com/dotnet/runtime/pull/80576
