### ISSUE TITLE
NativeAOT analysis doesn't warn when annotated item is accessed via ldtoken

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#80255]
`ldtoken` access is basically a reflection access to a given member. As such the analysis should look at its RUC and DAM annotations and produce a warning if there are any. Currently illink does this, but NativeAOT doesn't.

The correct way to fix this is to detect ldtoken in a method body and check if the target member has annotations. If so, add data flow analysis of the calling method to the graph. And then modify data flow analysis (MethodBodyScanner) to react to ldtoken and check for warnings.

**Comment by vitek-karas** [comment]
The implementation is somewhat challenging because the natural entry point would be `GetDependenciesDueToLdToken` but at the time this gets call, there's no information about the callsite (and can't be passed along as this goes through a node in the graph to get here).

The solution is probably to add a new API on metadata manager and call it directly from ILScanner/JitInterface where we have the information about the callsite. Similar to what happens for example for `GetDependenciesDueToAccess`. The question is if we want to change the existing `GetDependenciesDueToLdToken` or introduce a new API.

Note of fields: `ldtoken` on a field is even more complicated, because the JitInterface actually doesn't solve this itself, instead it goes through runtime helpers, so the code which figures out that it's a field and we need the dependency nodes for it is several layers detached from the point where we know about the callsite.

**Comment by MichalStrehovsky** [comment]
> The solution is probably to add a new API on metadata manager and call it directly from ILScanner/JitInterface where we have the information about the callsite. Similar to what happens for example for `GetDependenciesDueToAccess`. The question is if we want to change the existing `GetDependenciesDueToLdToken` or introduce a new API.

Can we just consider this access and call `GetDependenciesDueToAccess`? It feels like we would end up doing the same thing anyway.

> Note of fields: `ldtoken` on a field is even more complicated, because the JitInterface actually doesn't solve this itself, instead it goes through runtime helpers, so the code which figures out that it's a field and we need the dependency nodes for it is several layers detached from the point where we know about the callsite.

I think we can do methods and fields the same way. RyuJIT bypasses `resolveToken` for these (where we do the usual `GetDependenciesDueToAccess` and which is the reason why we miss this case), but it does call `embedGenericHandle` with `CORINFO_TOKENKIND_Ldtoken` and that should be what we need. Fixing up the scanner to do the same should be trivial because we process the `ldtoken` directly.

**Comment by jkotas** [comment]
>  RyuJIT bypasses resolveToken

RyuJIT calls `resolveToken` for all tokens in the IL stream, including all `ldtoken` tokens. `CORINFO_RESOLVED_TOKEN.tokenType` has the type of the callsite like `CORINFO_TOKENKIND_Ldtoken`.

**Comment by MichalStrehovsky** [comment]
> > RyuJIT bypasses resolveToken
> 
> RyuJIT calls `resolveToken` for all tokens in the IL stream, including all `ldtoken` tokens. `CORINFO_RESOLVED_TOKEN.tokenType` has the type of the callsite like `CORINFO_TOKENKIND_Ldtoken`.

Oh, I tried it and you're right.

I think the only problem is somewhere in the dataflow analysis. We do ask dataflow to take a look at the method with the ldtoken in GetDependenciesDueToAccess, but dataflow then fails to see the reference. It should apply the same way to fields.

**Comment by MichalStrehovsky** [comment]
@vitek-karas I think this was fixed.

I just tried:

```csharp
using System;
using System.Diagnostics.CodeAnalysis;
using System.Linq.Expressions;

class Program
{
    static void Main()
    {
        Expression<Action> e1 = () => MyMethod();
        e1.Compile()();

        Expression<Func<Type>> e2 = () => MyField;
        e2.Compile()();
    }

    [RequiresUnreferencedCode("")]
    static void MyMethod() { }

    [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)]
    static Type MyField;
}
```

And I see:

```
C:\git\runtime\src\coreclr\tools\aot\ILCompiler\repro\Program.cs(12): Trim analysis warning IL2026: Program.Main(): Using member 'Program.MyMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code.
C:\git\runtime\src\coreclr\tools\aot\ILCompiler\repro\Program.cs(15): Trim analysis warning IL2110: Program.Main(): Field 'Program.MyField' with 'DynamicallyAccessedMembersAttribute' is accessed via reflection. Trimmer can't guarantee availability of the requirements of the field.
```

I don't see any references to this issue number in the repo, so I'm going to close.
