### ISSUE TITLE
Icon/Image from Stream doesn't work for partial reads

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#80261]
Repro:
```C#
using System.Drawing;

byte[] ico;
using (var hc = new HttpClient())
{
    ico = await new HttpClient().GetByteArrayAsync(@"https://raw.githubusercontent.com/dotnet/runtime/main/src/native/corehost/dotnet/dotnet.ico");
}

var stream = new TrickleStream(ico);
new Icon(stream);

class TrickleStream : MemoryStream
{
    public TrickleStream(byte[] bytes) : base(bytes) { }

    public override int Read(byte[] buffer, int offset, int count) =>
        base.Read(buffer, offset, Math.Min(count, 1));
    public override int Read(Span<byte> buffer) =>
        base.Read(buffer.IsEmpty ? buffer : buffer.Slice(0, 1));
}
```

This should successfully load the data from the Stream into the icon, but instead it throws an exception.

All of these should be updated to not assume Stream.Read will return as much data as was requested.
https://github.com/dotnet/runtime/blob/1928cd2b65c04ebe6fe528d4ebb581e46f1fed47/src/libraries/System.Drawing.Common/src/System/Drawing/Icon.cs#L75
https://github.com/dotnet/runtime/blob/1928cd2b65c04ebe6fe528d4ebb581e46f1fed47/src/libraries/System.Drawing.Common/src/System/Drawing/Icon.cs#L113
https://github.com/dotnet/runtime/blob/1928cd2b65c04ebe6fe528d4ebb581e46f1fed47/src/libraries/System.Drawing.Common/src/System/Drawing/Icon.cs#L130
https://github.com/dotnet/runtime/blob/1928cd2b65c04ebe6fe528d4ebb581e46f1fed47/src/libraries/System.Drawing.Common/src/System/Drawing/Image.cs#L1057

cc: @eerhardt

**Comment by stephentoub** [comment]
Related:
https://github.com/dotnet/runtime/issues/69159

**Comment by ViktorHofer** [comment]
cc @JeremyKuhne
