### ISSUE TITLE
BitConverter.GetBytes is incompatible with INumber<T>

### ISSUE THREAD

**Issue by S1lver-Owl** [dotnet/runtime#80268]
### Describe the bug

When we have a Templated value using INumber, I need to convert that number into a byte array. When I use BitConverter.GetBytes(value), it does not understand what the type T is. The overload defaults to bool and throws the error `CS1503	Argument 1: cannot convert from 'T' to 'bool'`

### To Reproduce

```c#
bool WriteToCharacteristic<T>(T value)
	where T : INumber<T>
{
	byte[] sendValue = BitConverter.GetBytes(value);
	return sendValue.Length >= 2;
}
```

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

- `dotnet --info`
  - .NET SDK:
  Version:   7.0.100
  Commit:    e12b7af219
  \
  Runtime Environment:
   OS Name:     Windows
   OS Version:  10.0.19044
   OS Platform: Windows
   RID:         win10-x64
   Base Path:   C:\Program Files\dotnet\sdk\7.0.100\
  \
  Host:
    Version:      7.0.0
    Architecture: x64
    Commit:       d099f075e4
  \
  .NET SDKs installed:
    7.0.100 [C:\Program Files\dotnet\sdk]
  \
  .NET runtimes installed:
    Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  \
  Other architectures found:
    x86   [C:\Program Files (x86)\dotnet]
      registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]
  \
  Environment variables:
    Not set
  \
  global.json file:
    Not found
  \
  Learn more:
  https://aka.ms/dotnet/info
  \
  Download .NET:
    https://aka.ms/dotnet/download 
- Visual Studio Community 2022 17.4.1

**Comment by tannergooding** [comment]
> I was wondering if there was a way to implement both of these at the same time? Such that T could be either IBinaryInteger or IBinaryFloatingPointIeee754?

There is not. The intent is for the APIs on these two types to be used where possible for us in generic contexts.
