### ISSUE TITLE
Build breaks in profiling samples

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#80280]
The samples at https://github.com/dotnet/samples/tree/main/core/profiling/ have build breaks (observed on Linux, not sure about Windows).

The samples make fragile assumptions about dotnet/runtime repo directory structure and CoreCLR PAL that we do not make any compatibility guarantees for.

**Comment by jkotas** [comment]
Related #79440

**Comment by tommcdon** [comment]
@davmason
