### ISSUE TITLE
Linux: System.IO.Ports.SerialPort does not open with baudrate 111,865

### ISSUE THREAD

**Issue by DJSures** [dotnet/runtime#80288]
area-System.IO

### Description

We migrated a working console application from .Net 4.7.2 to .Net 7. The System.IO.Port.SerialPort gives an error with .Net 7 for the baud rate of 111,865. It works on Windows and macOS but does not work on Linux (x64, ARM64, ARM) anymore since the migration from .net 4.7.2 to .net 6. The error "Value does not fall within the expected range" is raised.

```
       var _sp = new SerialPort(
          "/dev/ttyS0",
          111865,
          0,
          8,
          StopBits.Two,
          Handshake.RequestToSend);
        _sp.Open();

```

### Reproduction Steps

Attempt to open the serial port with the following on Linux

```
       var _sp = new SerialPort(
          "/dev/ttyS0",
          111865,
          0,
          8,
          StopBits.Two,
          Handshake.RequestToSend);
        _sp.Open();

```

### Expected behavior

No error is thrown, and it works like all .Net Framework did (i.e. 4.7.2)

### Actual behavior

An exception is raised for "Value does not fall within the expected range"

### Regression?

.Net Framework 4.7.2

### Configuration

.net 7

Linux (ARM64, ARM, x64)

**Comment by DJSures** [comment]
area-System.IO

**Comment by janvorli** [comment]
@DJSures are you sure the hardware / its driver you are using supports that rate? It looks quite exotic, definitely out of the range of standard baud rates. If that's not the case, .NET cannot do much about it.

**Comment by DJSures** [comment]
Yes - I have a whole video on it (https://youtu.be/YypZW54wbmU) using a logic analyzer because I was curious at first if that baud would work across macOS, Linux and Windows. But it does because the FTDI hardware supports it. It's a USB to RS422 adapter for the NABU PC. I'm the developer of the Internet Adapter @ https://nabu.ca. The first version of the IA used Mono for a cross-platform GUI and, of course, that baud rate. Due to Mono not working on ARM64 macOS, we needed to compromise and release a CLI using Terminal.GUI. Summary is...

1) it worked with Mono on macOS and Linux
2) it still works with Windows (with .net 7) and also appears to work on macOS x86 (not ARM)
3) the baud is supported because the FTDI driver supports it (any microcontroller would keep it as well because it's just calculating the hardware uart timing based on clock frequency)
4) I copied Mono's SerialPort code from GitHub and added it to my project for fun to see if it would work on Linux. It does, but it won't work on macOS ARM because Mono libraries aren't supported. 

I haven't dug into it - but whatever Mono uses for SerialPort works successfully, whereas .Net 7 doesn't.

**Comment by danmoseley** [comment]
can you share the full stack? that would confirm it is coming from 
https://github.com/dotnet/runtime/blob/ef903fd300fc5115360fc27fc41207f232a5c87d/src/native/libs/System.IO.Ports.Native/pal_termios.c#L350

**Comment by janvorli** [comment]
@DJSures thank you for the details. @danmoseley my first guess is that there is some issue in the `SystemIoPortsNative_TermiosSetSpeed`. It seems that on Linux, we don't attempt to set non-standard rates. Based on what I've find by googling, it seems that `cfsetspeed` is only capable of setting the standard rates. On macOS, we actually try to use the `ioctl(fd, IOSSIOSPEED, ...)`, but it is possible that the `HAVE_IOSS_H` is not detected correctly. I have seen subtle problems with the cmake config in the past where things looked correct, but e.g. required adding some compiler option.

**Comment by janvorli** [comment]
Btw, I've found the following stackoverflow issue discussing setting non-standard rates: https://stackoverflow.com/questions/4968529/how-can-i-set-the-baud-rate-to-307-200-on-linux
Maybe we will need to add one of the fixes described there for Linux.

**Comment by janvorli** [comment]
I've verified that the `HAVE_IOSS_H` detection is correct, so the issue is not in that one.

**Comment by DJSures** [comment]
@janvorli, thanks for checking the IOS. The issue may be isolated to Linux based on your findings. I only have a macOS x86 to test with, which works.  The feedback on the macOS ARM is from a user who may not be providing the correct information if the ARM and x86 MAC libraries are based on the same codebase. We can then determine that this is isolated to Linux.

I will update my title accordingly not to confuse others.

**Comment by janvorli** [comment]
The arm64 and x64 code base for mac w.r.t. the serial port handling is the same.

**Comment by DJSures** [comment]
Is there anything else I can do to help you? In the meantime, I'm presenting a warning to Linux users and suggesting they change to 115,200 and cross their fingers. It's close and sometimes works, but improving their experience with the correct baud rate would be nice. So anything that I can do to help

**Comment by wfurt** [comment]
Do you have repro @janvorli or @krwq ? From the suggestions it seems like we do not try the `BOTHER` and we depend on `IOSSIOSPEED`.

**Comment by janvorli** [comment]
@wfurt the repro is in this issue at the beginning.

**Comment by wfurt** [comment]
And that fails for you @janvorli on Linux and works on Windows?

**Comment by janvorli** [comment]
I haven't tried that, I was just looking through our sources for a possible culprit.
