### ISSUE TITLE
string.IndexOf(string) gives incorrect result for some single-character args

### ISSUE THREAD

**Issue by IFYates** [dotnet/runtime#80298]
### Description

When using `string.IndexOf(string)` to find some characters (i.e., 0 to 31), the result is always the starting index (`0` if one wasn't supplied).

### Reproduction Steps

```csharp
var c = (char)1; // Seems to affect at least 0 -> 31
var str = "ABC" + c + "DEF";

// IndexOf(string)
Console.WriteLine("string> " + str.IndexOf($"{c}")); // Expect: 3, actual: 0
Console.WriteLine("string> " + str.IndexOf($"{c}", 2)); // Expect: 3, actual: 2
Console.WriteLine("string> " + str.IndexOf($"{c}", 4)); // Expect: -1, actual: 4

// IndexOf(char)
Console.WriteLine("char> " + str.IndexOf(c)); // 3
Console.WriteLine("char> " + str.IndexOf(c, 2)); // 3
Console.WriteLine("char> " + str.IndexOf(c, 4)); // -1
```

### Expected behavior

`IndexOf(string)` and `IndexOf(char)` should behave the same when `string` is a single-character.

### Actual behavior

`IndexOf(string)` always returns the starting index value (`0` if one wasn't supplied) when `string` is a certain character.

### Regression?

Anecdotally, I only found this because some previously working code started failing after a recent compilation. I haven't been able to track down any environment/project configuration or dependency that has changed since the last good build, and I was unable to make a working build until I changed all relevant `IndexOf(string)` usages to `IndexOf(char)`.

### Known Workarounds

If the length of the search string is 1, use `IndexOf(char)`.

Example:
```csharp
var str = "string-to-be-searched";
var val = "search-string";
var result = (val.Length == 1)
    ? str.IndexOf(val[0])
    : str.IndexOf(val);
```

### Configuration

Using dotnetfiddle, this appears to affect .NET Core 3.1 and .NET 5 through 7: https://dotnetfiddle.net/TCyeFP
.NET Framework 4.7.1 behaves as expected.

**Comment by vcsjones** [comment]
This is because `IndexOf(string)` is culture aware by default, whereas `IndexOf(char)` is ordinal by default. ICU probably treats those 0-31 characters as having zero weight.

If you want ordinal behavior, then specify `StringComparison.Ordinal`:


```C#
Console.WriteLine("string> " + str.IndexOf($"{c}", StringComparison.Ordinal));
Console.WriteLine("string> " + str.IndexOf($"{c}", 2, StringComparison.Ordinal));
Console.WriteLine("string> " + str.IndexOf($"{c}", 4, StringComparison.Ordinal));
```

Which prints:

> string> 3
> string> 3
> string> -1

See https://learn.microsoft.com/en-us/dotnet/core/compatibility/globalization/5.0/icu-globalization-api for additional details.

> Using dotnetfiddle, this appears to affect .NET Core 3.1 and .NET 5 through 7:

This affected all versions of .NET Core on Linux / macOS due to use of ICU, which I suspect is the OS that .NET Fiddle uses. This started affecting Windows in .NET 5 when it switched from NLS to ICU.

**Comment by IFYates** [comment]
Understood. Thanks.
That probably aligns with when we started building dependencies on Linux agents.
I'll feed back to those projects to update their code.
