### ISSUE TITLE
Build analysis failing with "/eng/pipelines/runtime-sanitized.yml (Line: 14, Col: 12): Unexpected value ''"

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#80290]
E.g. https://github.com/dotnet/runtime/pull/80228/checks?check_run_id=10472312277

cc @jkoritzinsky

**Comment by jkoritzinsky** [comment]
I'm working with @MattGal to fix the pipeline to not trigger on PRs without an explicit trigger.

**Comment by MattGal** [comment]
@jkoritzinsky it's entirely possible to set your triggers in YAML and thus not be subject to manual AzDO configuration stuff.

That said, I'll reach out on Teams and make any manual changes you'd like temporarily; the problem there is that will then override the YAML version of the same info.

**Comment by jkoritzinsky** [comment]
We've solved this over Teams. The AzDO UI has the option that is needed to hit the sweet spot of "This pipeline can run on PRs with the `/azp run` command but doesn't automatically run on any PR and must be explicitly requested".

We've set that option now, so this pipeline should stop running unless explicitly requested (which will only happen in the PR where I'm getting the pipeline working correctly)
