### ISSUE TITLE
Importing an ECC private key, from D value, without public key

### ISSUE THREAD

**Issue by wasabii** [dotnet/runtime#80305]
I have a need to use ECDiffieHellman.DeriveKeyMaterial(publicKey), where I only have the private key of my own, and public key of the other. Where the private key is given as a 32 byte big integer. I know the curve. I know the key size. I just don't know my own public key.

I can't find any formulation of the available public APIs on ECDiffieHellman, or it's friends (Cng, OpenSsl, directly) that let me generate an instance with only a private key on hand. I thought maybe I could use ECParameters, set D and curve, but not Q, and it would be okay. It's not. It fails to validate because the length of Q.X and Q.Y don't match D.

Is there anything exposed for this that I'm missing? Or is this a missing capability in .NET?

**Comment by vcsjones** [comment]
This works in .NET 5 and above. Support was added in https://github.com/dotnet/runtime/pull/33874 and https://github.com/dotnet/runtime/pull/34654.

```C#
using System;
using System.Security.Cryptography;

using ECDiffieHellman ecdh = ECDiffieHellman.Create(ECCurve.NamedCurves.nistP256);
ECParameters ecParams = ecdh.ExportParameters(true);


ECParameters dOnly = new ECParameters { D = ecParams.D, Curve = ecParams.Curve };
using ECDiffieHellman ecdhFromD = ECDiffieHellman.Create(dOnly);
using ECDiffieHellman otherParty = ECDiffieHellman.Create(ECCurve.NamedCurves.nistP256);

byte[] keyMaterial1 = otherParty.DeriveKeyMaterial(ecdhFromD.PublicKey);
byte[] keyMaterial2 = ecdhFromD.DeriveKeyMaterial(otherParty.PublicKey);

Console.WriteLine(Convert.ToHexString(keyMaterial1));
Console.WriteLine(Convert.ToHexString(keyMaterial2));
```

And the output will be some key agreement.

If you are running in to a scenario where it is not working, can you put together sample code to reproduce the issue, and what platform / exact operating system you are using?

**Comment by wasabii** [comment]
Gah. On core 3.1.

That's probably it.

Will verify and close. There any hack to get it working on 3.1?

**Comment by vcsjones** [comment]
> There any hack to get it working on 3.1?

Unfortunately I can't think of anything that would make that achievable using in-box components. I will also point out that .NET Core 3.1 [is out of support](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core) so the best way to achieve what you are looking for is to move to a supported version of .NET.

**Comment by wasabii** [comment]
Doesn't really matter when 90% of your users need 3.1 support.

**Comment by bartonjs** [comment]
If you only care about Windows, I believe you can just specify `Q.X = new byte[D.Length]`, and `Q.Y = Q.X` when you have a D value.  But I believe that gives some pretty garbage results on macOS and/or Linux.  (Test this if you want to try it)

Since the scenario works on supported versions, and we (by definition) don't support unsupported versions, there's not work for us to do here.

**Comment by vcsjones** [comment]
> But I believe that gives some pretty garbage results on macOS and/or Linux. (Test this if you want to try it)

It does not work on macOS or Linux. The errors are, respectively:

> OSStatus error -26275 - ECpriv failed to compute shared secret (err -1))

and

> EC_POINT_set_affine_coordinates:point is not on curve

**Comment by wasabii** [comment]
I'll be using that for Windows, but I do care about Linux in fact. Thanks.

I suspect I'm going to be going directly after OpenSSL at this point.

**Comment by wasabii** [comment]
So just so ya'll don't think I'm crazy, my project is IKVM. Huge numbers of our users are running 10+ year old software. Lots of big commercial stuff that needed access to old Java libraries. We have users still running NET 4.6, for instance.

And I'm trying to get it updated to a later JDK 8 version, which introduced EC support.
