### ISSUE TITLE
DateOnly.Parse throwing "not recognized as a valid DateOnly" for certain values on sv-FI on Linux only

### ISSUE THREAD

**Issue by perlun** [dotnet/runtime#80313]
### Description

The following program:

```c#
var date = DateOnly.Parse("31.01.2022", CultureInfo.GetCultureInfoByIetfLanguageTag("sv-FI"));
Console.WriteLine(date);
```

...runs correctly on Windows 10; it parses the date correctly and outputs `2022-01-31` (probably formatted using the current culture in the output).

### On Debian GNU/Linux (bookworm)

However, with the exact same code as above I get the following exception on Linux:

```
Unhandled exception. System.FormatException: String '31.01.2022' was not recognized as a valid DateOnly.
   at System.DateOnly.ThrowOnError(ParseFailureKind result, ReadOnlySpan`1 s)
   at System.DateOnly.Parse(String s, IFormatProvider provider, DateTimeStyles style)
```

### Reproduction Steps

See above.

### Expected behavior

A parsed `DateOnly` instance.

### Actual behavior

A `System.FormatException` is thrown.

### Regression?

Unknown.

### Known Workarounds

None.

### Configuration

.NET 6.0 has been used in the tests above; not yet tested/validated on .NET 7.

I initially thought this could have to do with missing locales, but I've reconfigured the locales on the machine in question to ensure `sv-FI` is enabled and the problem persists. Here is what it looks like right now:

```
$ egrep -v ^# /etc/locale.gen
en_US.UTF-8 UTF-8
sv_FI.UTF-8 UTF-8
sv_SE.UTF-8 UTF-8
```

### Other information

N/A

**Comment by tarekgh** [comment]
This is expected to fail. By the way, it fails on Windows 11 too.

`sv-FI` culture has `-` as date separator. So, parsing dates with `.` is expected to fail. Unicode standards define the `sv-FI` date format using `-` https://github.com/unicode-org/cldr/blob/ac66592c93d0cb26d0b8666d3978bcab1ec889fb/common/main/sv.xml#L2310.

It is possible Windows 10 had old culture data which using old date format which is using `.` as the date separator for `sv_FI` and make the parsing succeed there. 

If you still want to parse the dates with the old format which uses `.`, you can either use ParseExact.

```C#
            CultureInfo ci = new CultureInfo("sv-FI");
            var date = DateOnly.ParseExact("31.01.2022", "dd.MM.yyyy", ci);
```

or you override the short date pattern for this culture like:

```c#
            CultureInfo ci = new CultureInfo("sv-FI");
            ci.DateTimeFormat.ShortDatePattern = "dd.MM.yyyy";
            var date = DateOnly.Parse("31.01.2022", ci);
```

**Comment by perlun** [comment]
Thanks for the detailed answer, appreciated! 🙏 

I think that the `dd.mm.yyyy` format used in this example may be an (older?) Finnish date format in fact. 🤔 It's explicitly mentioned in e.g. this Oracle Solaris documentation (dated 2010): https://docs.oracle.com/cd/E19455-01/806-0169/overview-7/index.html

In fact... looking further from the link you posted, the `fi` CLDR file seems to suggest this `d.M.y` notation: https://github.com/unicode-org/cldr/blob/ac66592c93d0cb26d0b8666d3978bcab1ec889fb/common/main/fi.xml#L1590, so maybe one option for me would be to change to `fi-FI` for this use case instead. I'll give that a try. 👍 

(Thanks also for the other suggested workarounds; they might come in handy if the above fails. The data is coming from a 3rd party source so I cannot easily change it in this case.)
