### ISSUE TITLE
[API Proposal]: Casting INumber<T> to int and double  

### ISSUE THREAD

**Issue by Aniobodo** [dotnet/runtime#80318]
### Background and motivation

Since int and double are the default numeric types, all INumber<T> should be directly cast–able to int and double. 
Currently, the only way (I know) is to cast to object and then to int/double, which creates unnecessary object (heap allocation): (int)(object)INumber

### API Proposal

```csharp
namespace System.Numerics;

public class MyNumber : INumber<T>
{
    public static explicit operator Double(MyNumber n);
}

### API Usage

```csharp

double d = (double)MyNumber
```

**Comment by tannergooding** [comment]
You are meant to use `T.CreateChecked`, `T.CreateTruncating`, and `T.CreateSaturating`. So, given some `T x` and a constraint `where T : INumber<T>`, you can do `int.CreateTruncating(x)` to get an `int` from `x`.

This will, of course, truncate any bits and so `long.MaxValue` will return `-1`. If you want overflow to throw, you should use `int.CreateChecked(x)`. If you instead want it to saturate to int.MinValue/int.MaxValue, you should use `int.CreateSaturating(x)` (`long.MaxValue` would become `int.MaxValue` here).

For `double`, there is no concept of "overflow" or truncation. Instead, everything saturates and/or rounds to the nearest representable value.
