### ISSUE TITLE
[API Proposal]: Improvements on `Queue<T>` and `Stack<T>`

### ISSUE THREAD

**Issue by Rekkonnect** [dotnet/runtime#80327]
### Background and motivation

The queue and stack collections in the BCL provide very basic functionality, but are not tailored for offering bulk operations at the best speed possible. Enqueueing, dequeueing, pushing and popping multiple values is not possible without manually invoking the corresponding single-value methods multiple times while iterating the collection of values.

Furthermore, there is no interface abstraction for the following:
- queue or stack data structure operations (`IQueue<T>` and `IStack<T>`)
- tailed linear data structure (`ITailLinearCollection<T>` -- name could definitely be improved)

With the above abstractions, this opens the path for a `Deque` (#935)

### API Proposal

```csharp
namespace System.Collections.Generic;

// Deque would throw a NotSupportedException for Add, Peek, Remove, and their try equivalents
// Queue and Stack will implement the interface methods explicitly, forcing the user to use Enqueue, Pop, etc.
public interface IReadOnlyTailLinearCollection<T> : IEnumerable<T>, ICollection, IReadOnlyCollection<T>
{
    public T Peek();
    public bool TryPeek(out T peeked);
}

// The RemoveRange variants could return some type other than IEnumerable<T>
public interface ITailLinearCollection<T> : IReadOnlyTailLinearCollection<T>
{
    public void Add(T value);
    public void AddRange(IEnumerable<T> range);
    public void AddRange(Span<T> range);
    public T Remove();
    public IEnumerable<T> RemoveRange(int count);
    public bool TryRemove(out T removed);
}

public interface IQueue<T> : ITailLinearCollection<T>
{
    public void Enqueue(T value);
    public void EnqueueRange(IEnumerable<T> range);
    public void EnqueueRange(Span<T> range);
    public T Dequeue();
    public IEnumerable<T> DequeueRange(int count);
    public bool TryDequeue(out T removed);
}
public interface IStack<T> : ITailLinearCollection<T>
{
    public void Push(T value);
    public void PushRange(IEnumerable<T> range);
    public void PushRange(Span<T> range);
    public T Pop();
    public IEnumerable<T> PopRange(int count);
    public bool TryPop(out T removed);
}

public class Queue<T> : IQueue<T>
{
    // Implementations of the IQueue<T> interface
}
public class Stack<T> : IStack<T>
{
    // Implementations of the IStack<T> interface
}

public class Deque<T> : IQueue<T>, IStack<T>
{
    // Implementations of the two interfaces
    // As mentioned above, NotSupportedException thrown on Add, Peek, Remove, and their try equivalents

    public T PeekStart();
    public T PeekEnd();
    
    public bool TryPeekStart(out T peeked);
    public bool TryPeekEnd(out T peeked);
}
```

### API Usage

Here is an example of consuming the new API for `Queue<T>`
```csharp
var queue = new Queue<T>(new[] { 1, 2, 3, 4 });
Span<int> moreValues = stackalloc int[] { 5, 6, 7 };
queue.EnqueueRange(moreValues);

var dequeued = queue.DequeueRange(3).ToArray(); // { 1, 2, 3 }
// queue now contains { 4, 5, 6, 7 }
```

Here is an example of defining a linear structure that only contains elements once:
```csharp
public class QueueSet<T> : IQueue<T>, ISet<T>
{
    private readonly HashSet<T> set;
    private readonly IQueue<T> queue;

    void IQueue<T>.Enqueue(T value) => Enqueue(value);
    bool ISet<T>.Add(T value) => Enqueue(value);
    public bool Enqueue(T value)
    {
        if (!set.Add(item))
            return false;

        queue.Enqueue(item);
        return true;
    }

    // Similarly for EnqueueRange

    public bool Contains(T item) => set.Contains(item);

    // Trivial implementations of other operations
}
```

### Risks

The API design has to be carefully designed to provide a performant and healthy solution to the lack of abstractions and extensibility of data operations

**Comment by theodorzoulias** [comment]
```C#
public interface IQueue<T> : ITailLinearCollection<T>
{
    public IEnumerable<T> DequeueRange(int count);
```

What type of sequence would be returned by the `DequeueRange`? Deferred or materialized? If it's materialized, why not return a concrete type, like a `T[]`, so that it can be enumerated without allocating an `IEnumerator<T>`?

**Comment by Rekkonnect** [comment]
While you can easily and conveniently support most use cases, a materialized collection falls short in performance when you want to inject the dequeued elements in another collection, moving around the data twice.

A more general approach to that would be to additionally offer another method that accepts an `ICollection<T>` (maybe also support `ITailLinearCollection<T>`), and another for inserting into a span, and directly inserts the dequeued range into that collection. My only concern is that it excessively bloats the API.

I'd lean towards the materialized collection if I only had to pick one.

**Comment by theodorzoulias** [comment]
@Rekkonnect based on the API that you have proposed, you have to pick one. You can't return a collection that is both deferred and materialized. It's one or the other. Since you picked a materialized collection, you didn't answer my second question: why return an `IEnumerable<T>` sequence that is typically associated with deferred behavior (LINQ), and not a concrete type like a `T[]` that creates no confusion and can be enumerated without allocations?

**Comment by Rekkonnect** [comment]
I had a comment in the API design

```csharp
// The RemoveRange variants could return some type other than IEnumerable<T>
```

I intentionally avoided picking either, leaving it open for further discussion and research. The main purpose is to allow returning a range of dequeued/popped values in the same collection.

**Comment by theodorzoulias** [comment]
@Rekkonnect and isn't this a good place for having this discussion? As for the research, IMHO it's your responsibility to do it as the author of the proposal.

**Comment by Rekkonnect** [comment]
The API is *proposed* here, I have no authority. The API could be rejected, slightly refactored or accepted as-is. We're talking about a greatly-sized refactoring, so it would be effortless to think this through exhaustively by myself, especially when this is one of my first proposals. My job is to make a reasonably-designed initial movement, after which more people will engage and throw their own opinions on.

That being said, this is where the discussion takes place. I was feeling dirty with the choice of `IEnumerable<T>` as I was writing the proposal, which is why I left the comment for discussion. Moreover, I also mentioned how I could be happy with a more bloated design, but still afraid of the overkill in most scenarios. More experienced API designers could express their own opinions and approaches, helping mature the design and make it ready for review.

**Comment by theodorzoulias** [comment]
@Rekkonnect what bothers me mostly with the `IEnumerable<T>` return type, is that it contradicts the stated goal of the whole proposal, which is to offer bulk operations at the best speed possible. Allocating a buffer for storing the dequeued elements, and then on top of that allocating an enumerator for enumerating the buffer, will create more work for the garbage collector, which will most likely nullify all the performance gains of avoiding the single-value `Dequeue`.

**Comment by Rekkonnect** [comment]
That is correct, and as a result the returning type would best be `T[]` to my eye. Another alternative could be a `ReadOnlySpan<T>` but I fear many users might be thrown off by not knowing what that type does. The `ImmutableArray<T>` option is also viable but entirely kills the option of mutating the data, as it's effectively removed from the collection anyway.

**Comment by theodorzoulias** [comment]
@Rekkonnect if you return a `ReadOnlySpan<T>`, will you allocate it on the stack, or the heap, or conditionally based on how big is the `count`? Another option might be to let the user do the allocation, and pass a `Span<T>` to the `RemoveRange` by reference (I guess that this possible in C#11).

I don't think that the lack of familiarity with these types is a problem. The users how care about micro-optimizing the dequeuing of their queues, should be already well familiarized with these concepts. Honestly I think that the demand for this optimization feature is pretty rare.

**Comment by Rekkonnect** [comment]
The point is to give the average user to easily get access to an optimized solution, and the experienced user the ability to direct the removal results into a collection of their choice. Making an overload for `scoped ref Span<T>` is not bad in the sense that the experienced users will be taking advantage of it.

Rare as the demand for such optimizations may be, it's part of the structuring of a complete API that will serve to many users and will serve well. Due to the simplicity of those data structures, a user could go on and write their own implementation offering whatever optimizations they might come up with and need for their specific application. However, that would also force the user into implementing some standard interfaces that the BCL collections implement for the sake of being compatible with many APIs from the BCL. Additionally, there might come several tens or hundreds of unique user-implemented types all doing the same thing and using the same identifiers, which is not interfaced.

In the worst case of them all, these APIs could be refactored to fit into roles (from the roles and extensions proposal), when the time comes.

**Comment by eiriktsarpalis** [comment]
> Furthermore, there is no interface abstraction for the following:

See #48285. We generally don't expose collection abstractions unless the BCL contains a reasonable number of implementations that share the same feature set.

Regarding the performance improvements, I'm guessing they are primarily related to batch Pop/Dequeue operations? How common are these operations? Pop/Dequeue operations are fairly cheap, so I would be interested to see benchmarks showcasing any performance gains compared to sequencing multiple single-element operations.

**Comment by theodorzoulias** [comment]
@Abrynos my understanding is that associating a class with an interface (one-to-one) hinders the evolution of this class. For example the `PriorityQueue<TElement, TPriority>` will get a new method [`DequeueEnqueue`](https://github.com/dotnet/runtime/issues/75070) in .NET 8. Adding the same method in the hypothetical `IPriorityQueue<TElement, TPriority>` interface would be a breaking change, unless the `DequeueEnqueue` was added as a [default interface method](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/default-interface-methods) (DIM). But DIMs are avoided in the standard .NET libraries, because they are susceptible to ["shard diamonds"](https://github.com/dotnet/runtime/issues/2293#issuecomment-579524652) (ambiguous matches).
