### ISSUE TITLE
WebApplicationBuilder ILoggingBuilder does not enable logging by default

### ISSUE THREAD

**Issue by voltagex** [dotnet/runtime#80336]
### Description

Seems to be similar to #79798, but I have a repro with .NET 7 - either the Web API template needs to be changed or the documentation for logging needs to be clarified or both.

### Reproduction Steps

Modify the example ASP Net Core Web API template as follows:

```
using Microsoft.AspNetCore.Mvc;

namespace TestWebApp
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var builder = WebApplication.CreateBuilder(args);

            // Add services to the container.
            builder.Services.AddAuthorization();

            builder.Logging.ClearProviders();
            builder.Logging.AddConsole();
            builder.Logging.SetMinimumLevel(LogLevel.Trace);
            var app = builder.Build();

            // Configure the HTTP request pipeline.

            app.UseAuthorization();

            var summaries = new[]
            {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };

            app.MapGet("/weatherforecast", (HttpContext httpContext, [FromServices] ILogger<Program> logger) =>
            {
                logger.LogTrace("Trace event from /weatherforecast");
                Console.WriteLine($"ILogger enabled for trace? {logger.IsEnabled(LogLevel.Trace)}");
                var forecast = Enumerable.Range(1, 5).Select(index =>
                    new WeatherForecast
                    {
                        Date = DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
                        TemperatureC = Random.Shared.Next(-20, 55),
                        Summary = summaries[Random.Shared.Next(summaries.Length)]
                    })
                    .ToArray();
                return forecast;
            });

            app.Run();
        }
    }
}
```

(I am testing in Visual Studio 2022 17.4.3 so I hit F5 to run as standalone/Kestrel)

### Expected behavior

I would absolutely expect the following output:

```
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5206
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\git\TestWebApp

Trace event from /weatherforecast
ILogger enabled for trace? True

```

### Actual behavior

```
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5206
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\git\TestWebApp
ILogger enabled for trace? False

```

### Regression?

Unsure, but I haven't had this much trouble with ILogger before

### Configuration

Windows 10.0.19045.2364
NET 7.0.101
Visual Studio 17.3.4

**Comment by voltagex** [comment]
Note that 
```
app.MapGet("/weatherforecast", (HttpContext httpContext, [FromServices] ILoggerFactory loggerFactory) =>
            {
                var logger = loggerFactory.CreateLogger<Program>();
```

behaves the same - i.e. not enabled

**Comment by tarekgh** [comment]
@voltagex does your project include the file `appsettings.Development.json`? If so, try to change the `default` to `Trace` there.  Looks to me the logger settings are overridden by the values from the configuration.

```json
    "LogLevel": {
      "Default": "Trace",
      "Microsoft.AspNetCore": "Warning"
    }
```

**Comment by voltagex** [comment]
> @voltagex does your project include the file `appsettings.Development.json`? If so, try to change the `default` to `Trace` there. Looks to me the logger settings are overridden by the values from the configuration.
> 
> ```json
>     "LogLevel": {
>       "Default": "Trace",
>       "Microsoft.AspNetCore": "Warning"
>     }
> ```

How can you tell the settings are overridden? Shouldn’t values in code take preference over configuration?

**Comment by tarekgh** [comment]
@voltagex I was trying to provide a workaround to unblock you. I was not explaining the behavior.

**Comment by voltagex** [comment]
> @voltagex I was trying to provide a workaround to unblock you. I was not explaining the behavior. 

Thanks, understood.

**Comment by tarekgh** [comment]
I have confirmed the configuration taking a priority over the manually setting the logging min level. You may look at https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-7.0#default-log-level which clearly states the following:

```
The following code sets the default log level when the default log level is not set in configuration:
```

```C#
var builder = WebApplication.CreateBuilder();
builder.Logging.SetMinimumLevel(LogLevel.Warning);
```

So you need to set the value in the configuration or remove the default value from the configuration to adjust it.

By that, I am closing the issue. feel free to send any questions if you have any.
