### ISSUE TITLE
String concatenation - slight performance regression in .NET 7 (7.0.1) compared to .NET 6

### ISSUE THREAD

**Issue by davepcallan** [dotnet/runtime#80348]
Description
Slight regression for some string concatenation approaches.. string.join, string.concat, string.format etc. when concatenating a very small amount of strings. Regressions often around 10% but have seen up to 21% for string.join 

From 7.0
![image](https://user-images.githubusercontent.com/106764096/211219154-62c6e9b6-6d4a-4e01-be1b-8792426698c7.png)

Reproduction Steps
Gist is here -> https://gist.github.com/davepcallan/0e951cd6984f9ba75f9ed1c0962c6132

Expected behavior
Parity (or improvement) with .NET 6

Actual behavior
Slight regression of 10-20%

Regression?
Yes, 10-20%

Known Workarounds
No response

Configuration
No response

Other information
No response

**Comment by teo-tsirpanis** [comment]
Can you rerun your benchmarks with the environment variable `COMPLUS_GCName=clrgc.dll`?
