### ISSUE TITLE
Crash when running a csc compiled program in mono VM

### ISSUE THREAD

**Issue by Xinlong-Wu** [dotnet/runtime#80342]
I'm trying to add support for the RISC-V architecture to the Mono VM. but I got an error which block me for a long time. Can anyone help me to figure out where is the problem

I use `./build.sh --subset mono+Libs -C debug -p:RuntimeFlavor=mono` and `csc` to build the mono runtime and test program.
```C#
namespace HelloWorld
{
  class Program
  {
    static void Main()
    {
      return;
    }
  }
}
```

I use the cmmand `MONO_PATH=./artifacts/obj/mono/System.Private.CoreLib/x64/Debug ./artifacts/obj/mono/Linux.x64.Debug/out/bin/mono-sgen test/test_run.exe`.
it crash with a error: 
```
Process terminated.
Encountered infinite recursion while looking up resource 'Arg_DllNotFoundException' in System.Private.CoreLib. Verify the installation of .NET is complete and does not need repairing, and that the state of the process has not become corrupted.
```

https://github.com/dotnet/runtime/issues/74071

**Comment by am11** [comment]
For the port work, I'd use `dotnet` driver on mono desktop instead of sgen. That's the one used by testhost.

```sh
$ ./build.sh mono+libs+host
$ artifacts/bin/testhost/net7.0-Linux-Debug-x64/dotnet     test/test_run.exe
```

**Comment by Xinlong-Wu** [comment]
that is a great way, but how can I pass some parameter to mono vm?
cuz in some case, I need to specify which method to be compiled or Interpreted to compare their behaviors. or increase the log level to see what happened in it

**Comment by am11** [comment]
You can use an existing sample app after the build (`./build.sh mono+libs+host`):

```sh
# update src/mono/sample/HelloWorld/Program.cs as necessary, then
$ MONO_LOG_LEVEL=debug make run -C src/mono/sample/HelloWorld
```
from the repo root.

**Comment by Xinlong-Wu** [comment]
great I will try it

**Comment by am11** [comment]
BTW, `MONO_LOG_LEVEL=debug MONO_LOG_DEST=/tmp/mono-dump.log` etc. also work with `dotnet` under `testhost` directory:

```sh
$ cd ~/MyHelloWorld
$ dotnet build -c Release

$ cd runtime
$ rm -rf artifacts # start from clean state
$ ./build.sh mono+libs+host
$ MONO_LOG_LEVEL=debug MONO_LOG_DEST=/tmp/mono-dump.log \
    artifacts/bin/testhost/net7.0-Linux-Debug-x64/dotnet  ~/MyHelloWorld/bin/Release/net8.0/MyHelloWorld.dll
```

will write the debug logs in `/tmp/mono-dump.log`.

When we build `mono` without coreclr, the `libcoreclr.so` copied in `testhost` is actually the one with Mono runtime (filename is same for both runtimes for tooling purposes - https://github.com/dotnet/runtime/issues/34202). So if you are in doubt, you add this line in your test program:
```c#
Console.WriteLine($"IsMono: {Type.GetType("Mono.RuntimeStructs") is not null}");
```
rebuild and run with testhost. It should print `IsMono: True` when Mono VM is used and `False` when it is CoreCLR.

**Comment by Xinlong-Wu** [comment]
another quick question. How can I use set breakpoints in monoVM and debug it.

cuz it will make the problems/bug in JIT process be clear

when I run `gdb /home/wuxinlong/workspace/runtime/artifacts/bin/testhost/net8.0-Linux-Debug-riscv64/dotnet`, it report
```
Reading symbols from /home/wuxinlong/workspace/runtime/artifacts/bin/testhost/net8.0-Linux-Debug-riscv64/dotnet...
(No debugging symbols found in /home/wuxinlong/workspace/runtime/artifacts/bin/testhost/net8.0-Linux-Debug-riscv64/dotnet)
```
but I have use `-c Debug` to build the project already.

**Comment by am11** [comment]
(untested but) I think we do not copy dbg files in the testhost. You can copy them manually, something like:

```sh
# 1. find all ELF files in testhost dir
# 2. find `.gnu_debuglink` header in each ELF and parse the debug filename, then resolve the destination path for the debug filename
# 3. find debug filename under artifacts/bin and copy to destination

find ~/workspace/runtime/artifacts/bin/testhost -exec file "{}" \; | grep -i elf | \
  while IFS=: read file rest; do \
    dest="$(dirname "$file")/$(readelf --string-dump=.gnu_debuglink $file | sed -n '/]/{s/.* //;p;q}')"; key="$(basename "$dest")"; \
    find ~/workspace/runtime/artifacts/bin -name "$key" -exec cp "{}" "$dest" \;
  done
```
