### ISSUE TITLE
[API Proposal]: tweak IndexOfAnyValues<T> public API surface to drop dead paths

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#80340]
### Background and motivation

Disclaimer: the `IndexOfAnyValues<T>` API is functionally great. The current API surface though is, well, I don't really understand why it was structured the way it is, making the class not abstract and with a group of virtual methods that just always throw. I understand that it ultimately "doesn't matter", but like... Even still, why not just make that "correct"? 😄

This is from an ongoing conversation with @MihaZupan and other folks in the C# Discord, #lowlevel channel.

Happy to contribute this if the suggestion is accepted 🙂

### API Proposal

```diff
 namespace System.Buffers;

-public class IndexOfAnyValues<T> where T : IEquatable<T>?
+public abstract class IndexOfAnyValues<T> where T : IEquatable<T>?
 {
     private protected IndexOfAnyValues() { }
 
-    internal virtual T[] GetValues() => throw new UnreachableException();
+    internal abstract T[] GetValues();
 
-    internal virtual bool ContainsCore(T value) => throw new UnreachableException();
-    internal virtual int IndexOfAny(ReadOnlySpan<T> span) => throw new UnreachableException();
-    internal virtual int IndexOfAnyExcept(ReadOnlySpan<T> span) => throw new UnreachableException();
-    internal virtual int LastIndexOfAny(ReadOnlySpan<T> span) => throw new UnreachableException();
-    internal virtual int LastIndexOfAnyExcept(ReadOnlySpan<T> span) => throw new UnreachableException();
+    internal abstract bool ContainsCore(T value);
+    internal abstract int IndexOfAny(ReadOnlySpan<T> span);
+    internal abstract int IndexOfAnyExcept(ReadOnlySpan<T> span);
+    internal abstract int LastIndexOfAny(ReadOnlySpan<T> span);
+    internal abstract int LastIndexOfAnyExcept(ReadOnlySpan<T> span);
 }
```

### API Usage

Exact same use as before. No functional changes.

**Comment by stephentoub** [comment]
This was discussed in the recorded API review.

**Comment by Sergio0694** [comment]
I see. Fair enough, I'll close this then. Thank you! 🙂
