### ISSUE TITLE
Out of memory exception in JIT/Regression/JitBlue/DevDiv_255294 

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#8034]
Crossgen mode uses full optimizations and has quadratic algorithm it terms of memory to build and keep reachability sets for blocks.
CoreRun mode was fixed in dotnet/coreclr#11233.
So now CoreRun needs 300Mb (was 3 GB), CrossGen needs 3GB (was 6 GB). And 3GB is too much for x86.
category:throughput
theme:large-methods
skill-level:intermediate
cost:medium

**Comment by BruceForstall** [comment]
Closing this in favor of https://github.com/dotnet/runtime/issues/44341
