### ISSUE TITLE
Investigate Condition21.Test4 failure in TailcallVerifyWithPrefix

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/runtime#8036]
Condition21.Test4 in TailcallVerifyWithPrefix (in tests\src\JIT\opt\Tailcall) is currently failing and disabled. Here is the output of the test (checked x64):

        Executing Condition21.Test4 - Verifying helper frame location on the stack.
        The following shows a list of stack addresses of a local on the stack.
        You should see the same address three times before it decreases and repeats again.
        This happens because the call chain looks like this E->E->E->E->O->O->O->E->E->E->E->O->O->O
        where E is a method where tailcalls are not allowed (it's synchronized) and O is a
        method that gets tailcall'ed.
        0xb23b97d1f4
        0xb23b97d124
        0xb23b97d124
        0xb23b97cea4
        0xb23b97cdd4
        0xb23b97cdd4
        0xb23b97cb54
        0xb23b97ca84
        0xb23b97ca84
        0xb23b97c804
        0xb23b97c734
        0xb23b97c734
        0xb23b97c4b4
        0xb23b97c3e4
        0xb23b97c3e4
        0xb23b97c164
        0xb23b97c094
        0xb23b97c094
        0xb23b97be14
        0xb23b97bd44
        0xb23b97bd44
        0xb23b97bac4
        0xb23b97b9f4
        0xb23b97b9f4
        0xb23b97b774
        0xb23b97b6a4
        0xb23b97b6a4
        0xb23b97b424
        0xb23b97b354
        0xb23b97b354
        0xb23b97b0d4
        0xb23b97b004
        0xb23b97b004
        0xb23b97ad84
        0xb23b97acb4
        0xb23b97acb4
        0xb23b97aa34
        0xb23b97a964
        0xb23b97a964
        0xb23b97a6e4
        0xb23b97a614
        0xb23b97a614
        0xb23b97a394
        0xb23b97a2c4
        0xb23b97a2c4
        0xb23b97a044
        0xb23b979f74
        0xb23b979f74
        0xb23b979cf4
        0xb23b979c24
        0xb23b979c24
        0xb23b9799a4
        0xb23b9798d4
        0xb23b9798d4
        0xb23b979654
        0xb23b979584
        0xb23b979584
        0xb23b979304
        0xb23b979234
        0xb23b979234
        0xb23b978fb4
        0xb23b978ee4
        0xb23b978ee4
        0xb23b978c64
        0xb23b978b94
        0xb23b978b94
        0xb23b978914
        0xb23b978844
        0xb23b978844
        0xb23b9785c4
        0xb23b9784f4
        0xb23b9784f4
        0xb23b978274
        0xb23b9781a4
        0xb23b9781a4
        0xb23b977f24
        0xb23b977e54
        0xb23b977e54
        0xb23b977bd4
        0xb23b977b04
        0xb23b977b04
        0xb23b977884
        0xb23b9777b4
        0xb23b9777b4
        0xb23b977534
        Execution finished - Test FAILED

category:correctness
theme:testing
skill-level:intermediate
cost:small

**Comment by AndyAyersMS** [comment]
@jakobbotsch something to look into someday...

**Comment by jakobbotsch** [comment]
Closing for the same reason as https://github.com/dotnet/runtime/issues/8037#issuecomment-881947441.
