### ISSUE TITLE
.net462 httpClient does not seem to listen to cancellation token.

### ISSUE THREAD

**Issue by david-msft** [dotnet/runtime#80370]
Sample Code:        

```c#
    using (var httpClient = new HttpClient())  // system.net.http\4.3.4\
    using (var requestCts = new CancellationTokenSource())
    using (var response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, requestCts.Token))
    {
        // Start reading the response stream
        var responseContentReadTask = response.Content.ReadAsStringAsync();

        // Cancel the request and await the response
        requestCts.Cancel();

         Func<Task> testMethod = async () => await responseContentReadTask;
         requestCts.Cancel();        // This does not work - not cancelling the request.
         testMethod should be cancelled and throw but not in reality.
   }
```

**Comment by ManickaP** [comment]
The token is passed only to the `SendAsync` which has already ended by the time it gets canceled. You need to pass the token to `ReadAsStringAsync` if you want the response content reading to be cancel able.

**Comment by david-msft** [comment]
> The token is passed only to the `SendAsync` which has already ended by the time it gets canceled. You need to pass the token to `ReadAsStringAsync` if you want the response content reading to be cancel able.

I don't think so and ReadAsStringAsync does not support the Cancellation argument. There is an underlying logic in the HTTP client that is monitoring the request and should be able to catch the cancellation. I also tested the same logic with .net472, and it canceled as expected. I don't understand why .net462 would behave differently.

**Comment by karelz** [comment]
If 4.7.2 works fine, then it is good. You should be able to upgrade.
Higher versions have many bug fixes and some features on top of the old versions, that's why newer versions are better to be used. That's why they function better than older versions as they have more fixes.

BTW: We do not track .NET Framework bugs on GitHub. Although there is repo for regressions to be reported here: https://github.com/microsoft/dotnet

Given that it works in latest .NET Framework, closing the issue as resolved.

**Comment by david-msft** [comment]
> If 4.7.2 works fine, then it is good. You should be able to upgrade. Higher versions have many bug fixes and some features on top of the old versions, that's why newer versions are better to be used. That's why they function better than older versions as they have more fixes.
> 
> BTW: We do not track .NET Framework bugs on GitHub. Although there is repo for regressions to be reported here: https://github.com/microsoft/dotnet
> 
> Given that it works in latest .NET Framework, closing the issue as resolved.

The problem is We need .net462 version to work; we have a dependency on the version.
Ok, I will report it there.

**Comment by MihaZupan** [comment]
> If 4.7.2 works fine, then it is good. You should be able to upgrade.
Higher versions have many bug fixes and some features on top of the old versions

Notably though, this again differs from how .Net Core behaves.
The cancellation token supplied to SendAsync does not apply to the content in this case on Core as Mana described.
