### ISSUE TITLE
Console.WriteLine() skips newline if line length matches default console width

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#80373]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ConsoleWriteLine-skips-newline-if-lin/10220492)._

---
In a C# console app, if you call Console.Writeline() with a string length exactly the length of the default console windows (e.g. 120 characters), the newline character will not be printed.

The console will look fine at first, because the apparent "line break" is achieved only because of the wrap-around effects.  However, if you widen the window, you'll see there is actually no newline present.

Steps to reproduce:  Create a default C# console application, and add the following lines:

```
Console.WriteLine("123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890");
Console.WriteLine("Next line!");
```

Assuming a default console width of 120 characters, the output will look correct until you widen the console window.

---
#### Feedback Bot on 12/5/2022, 01:36 AM: 

(private comment, text removed)
#### Katya Sokolova [MSFT] on 1/4/2023, 03:23 PM: 

(private comment, text removed)
#### James Boer on 1/4/2023, 10:59 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jeffhandley** [comment]
I was curious and researched this a bit more. This behavior is expected on Windows and many terminals implement this same behavior. Some references I had found:
* https://superuser.com/questions/600677/in-linux-console-how-to-not-wrap-output
* https://stackoverflow.com/questions/66244924/windows-console-conhost-discards-newline-when-output-matches-witdth-of-the-win
* https://learn.microsoft.com/en-us/windows/console/getconsolemode#parameters -- see "ENABLE_WRAP_AT_EOL_OUTPUT"
