### ISSUE TITLE
Possible performance issue using Vector<Double> from stack allocated Span

### ISSUE THREAD

**Issue by atmoos** [dotnet/runtime#80385]
### Description
There may be a performance issue when using `Vector<Double>` that was initialized from a stack allocated `Span<Double>` and then using that vector for a computation such as `Vector.Sum` or `Vector.Dot`. These operations then seem to perform disproportionately slowly.

For a more detailed problem description please see my [symptom description benchmark](https://github.com/atmoos/VectorRegression/blob/master/SymptomDescription.cs) in a repo I created with three benchmark classes that illustrate the issue in greater detail. The minimal reproducible example is copy pasted further below.

### Configuration
I ran benchmarks on Windows and Linux, each on a different machine. All using .Net 7. I have not checked for previous .Net versions, though.

- OS: Windows 10 & Linux 6.1 arch linux with sway window manager
  - both x64 architecture with AVX2
  - `Vector<Double>.Count` = 4
- .Net 7.0

See below for the Benchmark.Net results of the minimal reproducible example.

### Regression?
I have not checked whether this is a regression in terms of _.Net versions_, nor if it's a regression in terms of the _generic type parameter_ of `Vector<T>`. (If I find time, I will check both scenarios).
It may be considered a regression of vector operations from **stack allocated data** versus **heap allocated data**.

### Data
I created a small repo that contains benchmarks that ought to illustrate the problem [here](https://github.com/atmoos/VectorRegression). I've copy pasted the most concise benchmark, i.e. the [minimal reproducible example](https://github.com/atmoos/VectorRegression/blob/master/DirectHeapVsStackComparison.cs) here for quick reference:

```csharp
[Benchmark(Baseline = true)]
public Double ExpectedStrictUpperBound()
{
    // Expect this to be a strict upper bound, due to heap allocated data.
    Span<Double> heapAllocatedData = new Double[Vector<Double>.Count];
    var vectorFromHeapData = new Vector<Double>(heapAllocatedData);
    return Vector.Sum(vectorFromHeapData);
}

[Benchmark] // Linux: ratio=1.15 | Windows: ratio=1.61
public Double ActualRuntime()
{
    // We'd expect the ratio to be strictly smaller than 1, but it's 1.15 (or 1.61).
    Span<Double> stackAllocatedData = stackalloc Double[Vector<Double>.Count];
    var vectorFromStackData = new Vector<Double>(stackAllocatedData);
    return Vector.Sum(vectorFromStackData);
}
```
We'd expect the `ExpectedStrictUpperBound` benchmark using heap allocated data to perform strictly _slower_ than the `ActualRuntime` benchmark that uses stack allocated data. However, unexpectedly, the version using stack allocated data performs notably slower, i.e. with ratios greater than one:

#### Windows 10 Results
```text
BenchmarkDotNet=v0.13.3, OS=Windows 10 (10.0.19044.2251/21H2/November2021Update)
Intel Core i7-10610U CPU 1.80GHz, 1 CPU, 8 logical and 4 physical cores
.NET SDK=7.0.101
  [Host]     : .NET 7.0.1 (7.0.122.56804), X64 RyuJIT AVX2
  DefaultJob : .NET 7.0.1 (7.0.122.56804), X64 RyuJIT AVX2
```

|                   Method |     Mean |     Error |    StdDev | Ratio | RatioSD |
|------------------------- |---------:|----------:|----------:|------:|--------:|
| ExpectedStrictUpperBound | 4.613 ns | 0.0563 ns | 0.0470 ns |  1.00 |    0.00 |
|            ActualRuntime | 7.415 ns | 0.1762 ns | 0.1809 ns |  1.61 |    0.05 |

#### Linux 6.1 Results
```text
BenchmarkDotNet=v0.13.3, OS=arch 
Intel Core i7-8565U CPU 1.80GHz (Whiskey Lake), 1 CPU, 8 logical and 4 physical cores
.NET SDK=7.0.101
  [Host]     : .NET 7.0.1 (7.0.122.61501), X64 RyuJIT AVX2
  DefaultJob : .NET 7.0.1 (7.0.122.61501), X64 RyuJIT AVX2
```
|                   Method |     Mean |     Error |    StdDev | Ratio |
|------------------------- |---------:|----------:|----------:|------:|
| ExpectedStrictUpperBound | 6.918 ns | 0.0518 ns | 0.0432 ns |  1.00 |
|            ActualRuntime | 7.966 ns | 0.0217 ns | 0.0203 ns |  1.15 |

### Analysis
I don't know where the issue might be. I do however know that three conditions must be met simultaneously for the performance impact to appear:
- Data from a stack allocated `Span<Double>`
- At least one `Vector<Double>` instance initialized from that span
- A vector operation on that vector, such as `Vector.Sum` or `Vector.Dot`
  - I'd expect the vector operations to perform equally fast regardless of whether the vector was initialized from stack or heap allocated data. 

Each of these operations on their own are fast and behave as "expected". (i.e. stack allocated span is faster than heap allocated span). However, in conjunction the variant using stack allocated data is unexpectedly slow.

For more details see my analysis [benchmark](https://github.com/atmoos/VectorRegression/blob/master/Analysis.cs) with more results.

**Comment by benaadams** [comment]
If you annotate the stackalloc method with `[SkipLocalsInit]` (project needs to allow unsafe blocks; namespace `System.Runtime.CompilerServices`)

```diff
G_M000_IG02:                ;; offset=001BH
+      852424               test     dword ptr [rsp], esp
-      4883C420             add      rsp, 32
-      6A00                 push     0
-      6A00                 push     0
-      6A00                 push     0
-      6A00                 push     0
       4883EC20             sub      rsp, 32
```
Then it drops four `push`es and an `add`; and puts in a `test`. May help

**Comment by tannergooding** [comment]
What Ben said is exactly right. `stackalloc` is an unsafe API and it results in more direct overhead in the form of zeroing and sometimes stack cookies.

`SkipLocalsInit` will help remove most of this overhead. However, there is still some other overhead due to the potential of buffer overrun/etc.

With .NET 8, we'll have `Vector.Load` and `Vector.LoadUnsafe` which can help a bit more, but what is best is likely going to depend on the more complete sample.

**Comment by tannergooding** [comment]
Going to close this as there isn't anything actionable on the library end.

The codegen side could do "more efficient" zeroing, but that's still going to have an overall relatively similar cost and the only fix is to opt out of that zeroing.
