### ISSUE TITLE
NativeAOT static linking produce too large files

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtime#80416]
When working on embedding Web API inside docker from scratch container, I publish fully statically linked EXE for WebApi, but it was 102 MB which is significantly more then I expect. It's just `dotnet new web` with minimal API. Same application with NativeAOT on Windows takes 16Mb.

I'm on Windows and it's currently hard for me tests sizes of the same setup on Linux without static linking. But either static linking did not trim something? or symbol stripping somehow does not strip something, or worst case Linux application somehow takes much more space and take dependencies.

I know that this specific setup is experimental at best, but size difference too big to ignore.

**Comment by neon-sunset** [comment]
IIRC, `PublishAot`  by default produces a binary together with its symbols. If `StripSymbols=true` MSBuild / .csproj property is specified, it supposedly emits them in a separate file alongside the binary which reduces the size.

Interestingly enough, on macOS further `strip`ing the binary reduces its size once more. I'm not sure what causes such behavior.

-- Example --
https://github.com/neon-sunset/http-bench | net8.0 SDK daily build | `osx-arm64` rid
`dotnet publish -c release -o publish --use-current-runtime` with `DebuggerSupport` property removed from .csproj:

`StripSymbols=false`: 38.6MB (still produces .dwarf file?)
`StripSymbols=true`: 26.4MB
`StripSymbols=true && strip binary`: 13MB

**Comment by kant2002** [comment]
Unfortunately, that does not help. When I publish linux-musl64 with `StripSymbols=true` and subsequenntly call strip on executable, final size does not change.

**Comment by MichalStrehovsky** [comment]
Are you statically linking all of libssl and icu? Can you try not including each of them to see how it changes the equation?

(Just libicuuc.so+libicudata.so is 28 MB on my machine, so the output of fully static linking on Linux is unlikely to be competitive with Windows.)

**Comment by kant2002** [comment]
Summary from repo where I do experiements

| Experiment | Size | ICU | OpenSSL | 
| ------------ | ----- | --- | ---------- |
| Console + Invariant globalization | 8.41 MB | No | No |
| Console + ICU | 51.4 MB | Yes | No |
| Console + Brotli + Deflate + Gzip | 11.8 MB  | No | No |
| HttpClient + OpenSSL | 39.6 MB | No | Yes |
| Web API | 102 MB | No | Yes |

All projects except usinng OpenSSL `<IlcDisableReflection>true</IlcDisableReflection>`.
All projects use `<InvariantGlobalization>true</InvariantGlobalization>` except `Console + ICU` obviously.
Let's pretend that 31Mb is OpenSSL + data and 8.5Mb is minimal code. Still around 60Mb somehow for WebAPI looks excessive.

**Comment by kant2002** [comment]
A bit more numbers, ICU data is 30.41 MB and actual code then 21.02 MB, SSL certs is 600Kb.

StripSymbols are always enabled https://github.com/kant2002/NativeAOTDocker/blob/main/WebApi/WebApi.csproj#L13

`Size`/`Size stripped`/manually calling `strip` seems to be do nothing

**Comment by am11** [comment]
> StripSymbols are always enabled https://github.com/kant2002/NativeAOTDocker/blob/main/WebApi/WebApi.csproj#L13

ok.

> `Size`/`Size stripped`/manually calling `strip` seems to be do nothing

You mean when you removed StripSymbols from your csproj, there was no difference in size?

**Comment by kant2002** [comment]
> You mean when you removed StripSymbols from your csproj, there was no difference in size?

yes. no difference. I add that setting in project just to give visibility that I try that way.

**Comment by am11** [comment]
That doesn't sound right. Try passing `--no-cache` to your `docker build` command.

**Comment by kant2002** [comment]
I did try `--no-cache` with same results.

**Comment by am11** [comment]
I added `RUN du -h out/WebApi` after this line: https://github.com/kant2002/NativeAOTDocker/blob/main/WebApi/Dockerfile#L17 and ran `docker build .` in WebApi directory and got `21.9M   out/WebApi`. Then I deleted `<StripSymbols>true` line from `WebApi.csproj` and reran `docker build .` and got `96.3M   out/WebApi`.

StripSymbols made 74.4 MB difference. How are you comparing it?

**Comment by am11** [comment]
You can delete the .dbg file after publish `RUN rm out/*.dbg`

**Comment by kant2002** [comment]
@am11 thank you! I'm again embarrased.

So what I do have now 

| Experiment | Size | ICU | OpenSSL | 
| ------------ | ----- | --- | ---------- |
| Console + Invariant globalization | 1.56 MB | No | No |
| Console + ICU | 35.9 MB | Yes | No |
| Console + Brotli + Deflate + Gzip | 2.56 MB  | No | No |
| HttpClient + OpenSSL | 10.5 MB | No | Yes |
| Web API | 23.6 MB | No | Yes |
