### ISSUE TITLE
Deduplication of symbols by using dedup/linkonce features

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#80419]
## Description

When Mono AOT compiler encounters a generic instance that is not handled by generic sharing, it will emit a code for the instance. If the same instance is encountered during compilation in multiple assemblies, the code will be emitted multiple times, increasing code size.

## Solutions

There are at least two possible solutions to this problem.

### Dedup by Mono AOT compiler

It compiles instances into a separate AOT image and consists of two phases. `Dedup-skip` flag is used when compiling assemblies, and it disables emitting code of dedup-able methods. `Dedup-include` flag is used when compiling dummy assembly where all assemblies are compiled together,  and it enables emitting code of dedup-able methods only. 

### Linkonce by LLVM

If two functions have the same name and they are marked linkonce, then the linker is allowed to throw away all copies except one.

## Experimental results

[List of methods](https://gist.github.com/kotlarmilos/97f9b0605feedd73c5e0bf6e22e0a8b6) In Mono iOS sample app that can be deduplicated. Estimated size reduction is 400kb. 
[Proposed change](https://github.com/dotnet/runtime/commit/fa422525bef96c71355b52e0fd04bc1486abd3da) for enabling deduplication in Mono iOS sample app. 

Deduplication of symbols is currently enabled in WASM.

**Comment by kotlarmilos** [comment]
Update: The dedup feature can be enabled in HelloiOS app in non-LLVM debug configuration. To enable it in release mode and with LLVM, the updated list of tasks need to be resolved.

Current implementation doesn't cover cases where both shared method and its inflated instances could be deduplicated. During the compilation, the shared method is emitted in corresponding AOT image while inflated instances are emitted in dedup AOT image. During the runtime, the shared method can't be retrieved as it was searched in the dedup AOT image.

Here is an example. During the compilation, the following list of inflated instances emitted in the dedup AOT image.
```
(wrapper runtime-invoke) object <Module>:runtime_invoke_byte__this___int (object,intptr,intptr,intptr)
(wrapper runtime-invoke) object <Module>:runtime_invoke_void__this___int_byte (object,intptr,intptr,intptr)
(wrapper runtime-invoke) object <Module>:runtime_invoke_int__this___int (object,intptr,intptr,intptr)
(wrapper runtime-invoke) object <Module>:runtime_invoke_void__this___int_int (object,intptr,intptr,intptr)
(wrapper runtime-invoke) object <Module>:runtime_invoke_int__this___int_int (object,intptr,intptr,intptr)
(wrapper runtime-invoke) object <Module>:runtime_invoke_void__this___int_int_int (object,intptr,intptr,intptr)
(wrapper runtime-invoke) object <Module>:runtime_invoke_uint16__this___int (object,intptr,intptr,intptr)
(wrapper runtime-invoke) object <Module>:runtime_invoke_void__this___int_uint16 (object,intptr,intptr,intptr)
(wrapper runtime-invoke) object <Module>:runtime_invoke_bool__this___int (object,intptr,intptr,intptr)
(wrapper runtime-invoke) object <Module>:runtime_invoke_void__this___int_byte (object,intptr,intptr,intptr)
(wrapper runtime-invoke) object <Module>:runtime_invoke_sbyte__this___int (object,intptr,intptr,intptr)
(wrapper runtime-invoke) object <Module>:runtime_invoke_void__this___int_sbyte (object,intptr,intptr,intptr)
(wrapper runtime-invoke) object <Module>:runtime_invoke_char__this___int (object,intptr,intptr,intptr)
(wrapper runtime-invoke) object <Module>:runtime_invoke_void__this___int_uint16 (object,intptr,intptr,intptr)
(wrapper runtime-invoke) object <Module>:runtime_invoke_int16__this___int (object,intptr,intptr,intptr)
(wrapper runtime-invoke) object <Module>:runtime_invoke_void__this___int_int16 (object,intptr,intptr,intptr)
(wrapper runtime-invoke) object <Module>:runtime_invoke_uint__this___int (object,intptr,intptr,intptr)
(wrapper runtime-invoke) object <Module>:runtime_invoke_void__this___int_uint (object,intptr,intptr,intptr)
(wrapper runtime-invoke) object <Module>:runtime_invoke_long__this___int (object,intptr,intptr,intptr)
(wrapper runtime-invoke) object <Module>:runtime_invoke_void__this___int_long (object,intptr,intptr,intptr)
(wrapper runtime-invoke) object <Module>:runtime_invoke_ulong__this___int (object,intptr,intptr,intptr)
(wrapper runtime-invoke) object <Module>:runtime_invoke_void__this___int_long (object,intptr,intptr,intptr)
(wrapper runtime-invoke) object <Module>:runtime_invoke_intptr__this___int (object,intptr,intptr,intptr)
(wrapper runtime-invoke) object <Module>:runtime_invoke_void__this___int_intptr (object,intptr,intptr,intptr)
(wrapper runtime-invoke) object <Module>:runtime_invoke_uintptr__this___int (object,intptr,intptr,intptr)
(wrapper runtime-invoke) object <Module>:runtime_invoke_void__this___int_intptr (object,intptr,intptr,intptr)
(wrapper runtime-invoke) object <Module>:runtime_invoke_single__this___int (object,intptr,intptr,intptr)
(wrapper runtime-invoke) object <Module>:runtime_invoke_void__this___int_single (object,intptr,intptr,intptr)
(wrapper runtime-invoke) object <Module>:runtime_invoke_double__this___int (object,intptr,intptr,intptr)
(wrapper runtime-invoke) object <Module>:runtime_invoke_void__this___int_double (object,intptr,intptr,intptr)
```
During the runtime, `(wrapper runtime-invoke) void object:runtime_invoke_dynamic (intptr,intptr,intptr,intptr)` was searched in the dedup AOT image as it is `RUNTIME_INVOKE_WRAPPER`, but not emitted in the dedup AOT image. It could be addressed by updating `mono_aot_get_method` method to handle such cases. Alternative approach could be adding a dedup flag in `MonoMethod` struct but it looks like inefficient approach.

Furthermore, In release configuration, during the runtime `mono_jit_cleanup` throws `Could not find method 'GetPinnableReference' due to a type load error: Type System.ReadOnlySpan'1[T] is not a ByRefLike type so ref field, '_reference'`. As it works without the dedup feature, it might happen due to inconsistent or missing data in the dedup AOT image. 

HelloiOS with LLVM enabled throws while executing method wrappers. During the debugging, the implementation was changed to emit all methods in corresponding AOT images and to have an empty dedup AOT image linked into a binary. The same error occurred, which could lead to having an issue with segments offset of AOT images in the binary. 

Further investigation is needed to narrow down the specific causes. /cc: @vargaz @lambdageek

**Comment by lambdageek** [comment]
> Furthermore, In release configuration, during the runtime mono_jit_cleanup throws Could not find method 'GetPinnableReference' due to a type load error: Type System.ReadOnlySpan'1[T] is not a ByRefLike type so ref field, '_reference'. As it works without the dedup feature, it might happen due to inconsistent or missing data in the dedup AOT image.

You might be able to fix this by adding `is_byreflike` to `MonoCachedClassInfo`.  Or we might need to fully load+init the ``ReadOnlySpan`1[T]`` class on some branch.

**Comment by vargaz** [comment]
is_byreflike is computed when the class is created i.e. in mono_class_create_from_typedef () so it should be set correctly.

**Comment by kotlarmilos** [comment]
> is_byreflike is computed when the class is created i.e. in mono_class_create_from_typedef () so it should be set correctly.

Let me check if for ``ReadOnlySpan`1[T]``.

> HelloiOS with LLVM enabled throws while executing method wrappers. During the debugging, the implementation was changed to emit all methods in corresponding AOT images and to have an empty dedup AOT image linked into a binary. [The same error occurred](https://gist.github.com/kotlarmilos/3ebf4d91f627a2e1963ff8a083a05b3d), which could lead to having an issue with segments offset of AOT images in the binary.

If LLVM is enabled the application throws in both release and debug configurations.  When using debug configuration, `NativeRuntimeEventSource` constructor throws when initializing its attribute `EventSource`, as `EventListener` is `NULL`.
https://github.com/dotnet/runtime/blob/8b2a92019b2bd24a7c069ef8dfc7d99c28f30d4b/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs#L1566

Similarly, when using release configuration, `InternalWait` throws as `default` is `NULL`.
https://github.com/dotnet/runtime/blob/8b2a92019b2bd24a7c069ef8dfc7d99c28f30d4b/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs#L140

In both cases, it fails when using default or global variable. The following direct call transformation is causing such issues with LLVM. @vargaz @lambdageek Any ideas why is it happening?

https://github.com/dotnet/runtime/blob/8b2a92019b2bd24a7c069ef8dfc7d99c28f30d4b/src/mono/mono/mini/aot-compiler.c#L6512-L6552

Overall, with proper retrieval of `is_byreflike` and disabled direct call transformation, dedup can be enabled in HelloiOS application. Next steps include testing the dedup in MAUI application and testing CI lanes. @ivanpovazan @SamMonoRT

**Comment by ivanpovazan** [comment]
@kotlarmilos nice progress! 
If I understand correctly, trying it out with MAUI is limited currently to Debug mode without LLVM, correct?

**Comment by kotlarmilos** [comment]
With proper code changes it works in all configurations. We have to find appropriate fix for `is_byreflike`. I can provide a WiP branch with patches and we can try it with a MAUI app.
