### ISSUE TITLE
SSL RemoteCertificateNameMismatch error in a chroot build environment

### ISSUE THREAD

**Issue by intelligide** [dotnet/runtime#80413]
### Description

I am creating a package for synology NAS with a c# program in it. In order to create this package, I need to use the build environment provided by Synology which is a minified linux environment using the `chroot` command.
This environment is special and quite limited. For example, root certificates are not available by default (it is possible to enable them with the `update-ca-trust` command). However, it is impossible to build a C# project using nuget dependencies, because an SSL exception with an error code is raised with urls of type "*.nuget.org".

The certificates are installed and detected after the `update-ca-trust` command. Curl works correctly and HTTPS requests in C# don't raise any exceptions (except for `nuget.org`). 
I tried to copy the root certificates from my host linux into the build environment, but the problem remains unsolved (HTTPS requests work, except for `nuget.org` urls).

The exception contains only `RemoteCertificateNameMismatch` as error code and not `UntrustedRoot` or `RemoteCertificateChainErrors`, which makes me speculate that this is not a problem in the installation of certificates.

PS: This error doesn't appear in my linux host, only in the chroot build environment.

### Reproduction Steps

- `mkdir SynologyPackageDev && cd SynologyPackageDev`
- `git clone https://github.com/SynologyOpenSource/pkgscripts-ng --branch DSM7.1`
- `sudo ./pkgscripts-ng/EnvDeploy -v 7.1 -p r1000`
  (this command may take some time, it will download and install a Synology build environment in the current folder)
- `sudo chroot build_env/ds.r1000-7.1/`
- `update-ca-trust`
  (certificates are not updated by default in the build environment, we have to update them manually to make them usable)
- `curl -L "https://dot.net/v1/dotnet-install.sh" -o dotnet-install.sh`
- `chmod +x dotnet-install.sh`
- `./dotnet-install.sh --version 7.0.101`
- `~/.dotnet/dotnet new console -o TestDotnetSSL`
- With vim, edit the `TestDotnetSSL/Program.cs`:
  ```cs
  using (HttpClient client = new HttpClient())
  {        
      using (HttpResponseMessage response = await client.GetAsync("https://api.nuget.org/v3/index.json"))
      {
          Console.WriteLine(await response.Content.ReadAsStringAsync());
      }
  }
  ```
  (Vim is the only command line editor available in the build environment. If you want to use a GUI editor, you have to edit the file located in  `build_env/ds.r1000-7.1/TestDotnetSSL/Program.cs` in root mode) 
- `~/.dotnet/dotnet run --project=TestDotnetSSL` (It should print the error)

(The project files are available here [TestDotnetSSL.tar.gz](https://github.com/dotnet/runtime/files/10378824/TestDotnetSSL.tar.gz))

### Expected behavior

No exception raised.

### Actual behavior

```
Unhandled exception. System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Program.<Main>$(String[] args) in /TestDotnetSSL/Program.cs:line 3
   at Program.<Main>(String[] args)
```

### Configuration

.NET Version: 7.0.101
OS: Linux Manjaro 5.15.85
Architecture: x86_64

**Comment by rzikm** [comment]
I find it interesting that `curl` is able to validate the cert but `dotnet` does not, since both use the same openssl lib (which is 1.0.2, quite old btw)

quick tests I tried:

openssl inside chroot
```
CHROOT@ds.r1000[/TestDotnetSSL]# openssl s_client -host api.nuget.org -port 443 -servername api.nuget.org

CONNECTED(00000003)
depth=1 C = US, O = Microsoft Corporation, CN = Microsoft Azure TLS Issuing CA 05
verify error:num=20:unable to get local issuer certificate
---
Certificate chain
 0 s:/C=US/ST=WA/L=Redmond/O=Microsoft Corporation/CN=*.nuget.org
   i:/C=US/O=Microsoft Corporation/CN=Microsoft Azure TLS Issuing CA 05
 1 s:/C=US/O=Microsoft Corporation/CN=Microsoft Azure TLS Issuing CA 05
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root G2
---
[...]
    Verify return code: 20 (unable to get local issuer certificate)
```

openssl outside chroot (v. 3.0.7):
```
❯  openssl s_client -host api.nuget.org -port 443 -servername api.nuget.org
CONNECTED(00000003)
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root G2
verify return:1
depth=1 C = US, O = Microsoft Corporation, CN = Microsoft Azure TLS Issuing CA 05
verify return:1
depth=0 C = US, ST = WA, L = Redmond, O = Microsoft Corporation, CN = *.nuget.org
verify return:1
---
[...]
```

However, when I download the cert to `cert.pem` and the intermediate to `intermediate.pem` and verify locally, it works as expected
```
# without intermediate cert
CHROOT@ds.r1000[/TestDotnetSSL]# openssl verify -verbose cert.pem 
cert.pem: C = US, ST = WA, L = Redmond, O = Microsoft Corporation, CN = *.nuget.org
error 20 at 0 depth lookup:unable to get local issuer certificate

# with intermediate cert
CHROOT@ds.r1000[/TestDotnetSSL]# openssl verify -verbose -untrusted intermediate.pem cert.pem 
cert.pem: OK
```

`tcpdump` captures don't show any significant difference between the two handshakes, so the catch must be somewhere around OpenSSL.

**Comment by rzikm** [comment]
@wfurt any ideas? I was there perhaps some bug in 1.0.2 we are hitting here?

**Comment by vcsjones** [comment]
@rzikm does passing `-check_ss_sig` change the behavior when using `openssl s_client`? .NET opts in to checking the self signed signature.

**Comment by wfurt** [comment]
Did you look at just the handshake @rzikm or everything? With intermediates missing, .NET _should_ try to fetch them from 'http://www.microsoft.com/pkiops/certs/Microsoft%20Azure%20TLS%20Issuing%20CA%2005%20-%20xsign.crt` (based on AIA extension) If you have repro you can simply try `X509Chain.Build` without any SSL to see if you can complete the chain.

**Comment by rzikm** [comment]
The certificates sent were the same in both scenarios

**Comment by wfurt** [comment]
My question was not about the handshake @rzikm but about the side HTTP channel fetching intermediates.

**Comment by rzikm** [comment]
I did not see any other significant network traffic on the original code sample, definitely no HTTP. Also, curl does not fetch certs from AIA.

Building the chain manually works (and it does not even need to download the intermediate it seems since I tcpdump captured no traffic)

<details>
<summary> Program + output </summary>

```csharp
using System.Security.Cryptography.X509Certificates;

using var clientCert = new X509Certificate2("/cert.pem");
System.Console.WriteLine(clientCert);

using var chain = X509Chain.Create();

System.Console.WriteLine($"Build result: {chain.Build(clientCert)}");

//Output chain element information.
Console.WriteLine("Chain Element Information");
Console.WriteLine("Number of chain elements: {0}", chain.ChainElements.Count);
Console.WriteLine("Chain elements synchronized? {0} {1}", chain.ChainElements.IsSynchronized, Environment.NewLine);

foreach (X509ChainElement element in chain.ChainElements)
{
    Console.WriteLine("Element issuer name: {0}", element.Certificate.Issuer);
    Console.WriteLine("Element certificate valid until: {0}", element.Certificate.NotAfter);
    Console.WriteLine("Element certificate is valid: {0}", element.Certificate.Verify());
    Console.WriteLine("Element error status length: {0}", element.ChainElementStatus.Length);
    Console.WriteLine("Element information: {0}", element.Information);
    Console.WriteLine("Number of element extensions: {0}{1}", element.Certificate.Extensions.Count, Environment.NewLine);

    if (chain.ChainStatus.Length > 1)
    {
        for (int index = 0; index < element.ChainElementStatus.Length; index++)
        {
            Console.WriteLine(element.ChainElementStatus[index].Status);
            Console.WriteLine(element.ChainElementStatus[index].StatusInformation);
        }
    }
}
```

```
[Subject]
  CN=*.nuget.org, O=Microsoft Corporation, L=Redmond, S=WA, C=US

[Issuer]
  CN=Microsoft Azure TLS Issuing CA 05, O=Microsoft Corporation, C=US

[Serial Number]
  33003968AD51CDD5F23C4F3A8D0000003968AD

[Not Before]
  04/27/2022 09:17:22

[Not After]
  04/22/2023 09:17:22

[Thumbprint]
  AFF8E461E4B34DD2269EC0F1F70E1B14D7A8D1BA

Build result: True
Chain Element Information
Number of chain elements: 3
Chain elements synchronized? False 

Element issuer name: CN=Microsoft Azure TLS Issuing CA 05, O=Microsoft Corporation, C=US
Element certificate valid until: 04/22/2023 09:17:22
Element certificate is valid: True
Element error status length: 0
Element information: 
Number of element extensions: 12

Element issuer name: CN=DigiCert Global Root G2, OU=www.digicert.com, O=DigiCert Inc, C=US
Element certificate valid until: 06/28/2024 07:59:59
Element certificate is valid: True
Element error status length: 0
Element information: 
Number of element extensions: 9

Element issuer name: CN=DigiCert Global Root G2, OU=www.digicert.com, O=DigiCert Inc, C=US
Element certificate valid until: 01/15/2038 20:00:00
Element certificate is valid: True
Element error status length: 0
Element information: 
Number of element extensions: 3
```
</details>

Here are the capture files

[captures.zip](https://github.com/dotnet/runtime/files/10400459/captures.zip)

**Comment by wfurt** [comment]
I did not figure out what is wrong but the OpenSSL is super old. However, I did found workaround that _maybe_ sufficient. 
I wanted to check with some somewhat known openssl. So I grabbed `openssl-libs` RPM from  http://mirror.centos.org/centos/7/os/x86_64/Packages/ and extracted to my subdirectory in chroot using `rpm2cpio openssl-libs-1.0.2k-19.el7.x86_64.rpm  | cpio -idmv`. (You will also need to do the same with  krb5-libs, libcom_err and libselinux) The base packages comes with links so you will also need 'ln -s libcrypto.so.1.0.2k libcrypto.so.1.0.0'  (and same for libssl)

now inside of chroot:
```
CHROOT@ds.r1000[/TestDotnetSSL]# export LD_LIBRARY_PATH=/TestDotnetSSL/openssl/lib64:/TestDotnetSSL/openssl/usr/lib64
CHROOT@ds.r1000[/TestDotnetSSL]# ldd /usr/bin/openssl
	linux-vdso.so.1 (0x00007ffc883bf000)
	libssl.so.1.0.0 => /TestDotnetSSL/openssl/usr/lib64/libssl.so.1.0.0 (0x00007f6ad1796000)
	libcrypto.so.1.0.0 => /TestDotnetSSL/openssl/usr/lib64/libcrypto.so.1.0.0 (0x00007f6ad1333000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f6ad0f90000)
	libgssapi_krb5.so.2 => /TestDotnetSSL/openssl/usr/lib64/libgssapi_krb5.so.2 (0x00007f6ad0d43000)
	libkrb5.so.3 => /TestDotnetSSL/openssl/usr/lib64/libkrb5.so.3 (0x00007f6ad0a5a000)
	libcom_err.so.2 => /TestDotnetSSL/openssl/usr/lib64/libcom_err.so.2 (0x00007f6ad0856000)
	libk5crypto.so.3 => /TestDotnetSSL/openssl/usr/lib64/libk5crypto.so.3 (0x00007f6ad0623000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f6ad041f000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f6ad0208000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6ad1a08000)
	libkrb5support.so.0 => /TestDotnetSSL/openssl/usr/lib64/libkrb5support.so.0 (0x00007f6acfff8000)
	libkeyutils.so.1 => /usr/lib/libkeyutils.so.1 (0x00007f6acfdf4000)
	libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007f6acfbdd000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f6acf9c0000)
	libselinux.so.1 => /TestDotnetSSL/openssl/usr/lib64/libselinux.so.1 (0x00007f6acf799000)
	libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007f6acf52a000)

CHROOT@ds.r1000[/TestDotnetSSL]# ~/.dotnet/dotnet run
{
  "version": "3.0.0",
  "resources": [
    {
....
```

.NET runs as it should using the alternative OpenSSL library. You can probably build it from sources if that is preferable  @intelligide. I hope it helps. With .NET 7 you can suppress name check (or do custom validation) in your app but it would not help you with NuGet. The workaround should allow you to build and run. I don't think it is practical for us to keep digging as this one-off on old unsupported OpenSSL version.
