### ISSUE TITLE
[API Proposal]: Provide a way to specify default JSON serialization for HttpClient

### ISSUE THREAD

**Issue by smarts** [dotnet/runtime#80415]
### Background and motivation

JSON serialization (via System.Text.Json) provides a convenient way to set default behaviors so that consumers of the API do not need to pass an options instance to each call.
On the other hand, `HttpClient` has no equivalent behavior for serializing and deserializing JSON, instead forcing the user to pass the aforementioned options instance to any call where custom serialization behavior is necessary.
It would be extremely convenient if there were some API that mirrors the functionality described above.

This is my first API proposal, so I apologize in advance if this proposal is somewhat rough.

### API Proposal

```csharp
public static class HttpClientDefaults
{
  public static JsonSerializerOptions JsonSerializerOptions
  {
    // same (or similar) implemenation as System.Text.Json.JsonSerializerOptions.Default
  }
}
```

### API Usage

Note: I'm excluding cancellation tokens for brevity

```csharp
// set default serializer options
HttpClientDefaults.JsonSerializerOptions.Converters.Add(…);

// no need to specify options elsewhere
var myUrl = new Uri("www.example.com/foo.json");
using var httpClient = new HttpClient();
var foo = await httpClient.GetFromJsonAsync<Foo>(myUrl);
var res = await httpClient.PostAsJsonAsync("www.example.org/api/myResources", new { name = "resource 1" });
var resource = await res.Content.ReadFromJsonAsync<MyResource>();
```

### Alternative Designs

Alternative locations for static instance:
I'm not sure if the preference would be to put this in its own class or have it live in `HttpClient` itself.

 Alternative implementations:
1. A static Boolean property that specifies whether or not to use the default options from System.Text.Json. (i.e., do not use a separate options instance for `HttpClient`)
1. Either the proposed API or an alternative configuration as instance data on `HttpClient` instead of static implementation.

### Risks

The static implementation is easy to use but doesn't work well in a scenario with many HttpClient instances with varying JSON needs. For example, it is common in enterprise software to integrate with several different HTTP [RESTful] APIs. However, sometimes each of these APIs each comes w/ its own unique quirks (e.g., using strings instead of numbers in JSON). If you are using dependency injection (i.e., `services.AddHttpClient(…)`) or even a scenario with self-managed long-lived client instances, it would be more flexible to configure the JSON serialization once (via a client configuration delegate if using AddHttpClient, or manually on each instance, and then never need to worry about it again for the lifetime of the application.

I looked at this purely from a developer experience perspective. I will let those with more expertise weigh in on the other implications (e.g., compiled code and performance).

**Comment by gregsdennis** [comment]
I'm not sure the STJ label applies to this.  It pertains more to `HttpClient` and ASP.Net.

**Comment by rjgotten** [comment]
If you're going to have a look at injecting configuration for (de)serialization; might as well also look at injecting the serializer implementation. ASP.NET Core model binding; API responses; and Razor view rendering all can receive implementation-specific injected classes allowing any compatible JSON serializer to be used. (Canonical example being Newtonsoft.Json aka Json.NET which for the longest time was the de facto standard serializer, before STJ took over.)

**Comment by MihaZupan** [comment]
> JSON serialization (via System.Text.Json) provides a convenient way to set default behaviors so that consumers of the API do not need to pass an options instance to each call.

Do you mean ASP.NET Core?

AFAIK `System.Text.Json` itself does not expose a mechanism to modify global defaults - #31094.
The same reason globally mutable options were rejected there likely applies to `HttpClient` usage too.

**Comment by eiriktsarpalis** [comment]
We should not be exposing global mutable configuration -- this true both for the STJ layer and the HttpClient layer.

**Comment by smarts** [comment]
> > JSON serialization (via System.Text.Json) provides a convenient way to set default behaviors so that consumers of the API do not need to pass an options instance to each call.
> 
> Do you mean ASP.NET Core?
> 
> AFAIK `System.Text.Json` itself does not expose a mechanism to modify global defaults - #31094. The same reason globally mutable options were rejected there likely applies to `HttpClient` usage too.

Maybe I'm confused, but what is `System.Text.Json.JsonSerializerOptions.Default`? Is that not a global default that is mutable?

**Comment by stephentoub** [comment]
> Is that not a global default that is mutable?

It's not mutable.

**Comment by smarts** [comment]
> I'm not sure the STJ label applies to this (that label is typically used for the STJ API and subsystem). It pertains more to `HttpClient` and ASP.Net.

I believe you're correct. I think whatever labels these issues saw `System.Text.Json` and mis-labeled this issue.

**Comment by smarts** [comment]
> We should not be exposing global mutable configuration -- this true both for the STJ layer and the HttpClient layer.

Was the proposal for global mutable configuration the reason for closing the issue? If not, then why? My second alternative was a proposal for an instance-specific implementation.

**Comment by smarts** [comment]
> We should not be exposing global mutable configuration -- this true both for the STJ layer and the HttpClient layer.

@eiriktsarpalis was the proposal for global mutable configuration the reason for closing the issue? If not, then why? My second alternative was a proposal for an instance-specific implementation.

**Comment by smarts** [comment]
> If you're going to have a look at injecting configuration for (de)serialization; might as well also look at injecting the serializer implementation. ASP.NET Core model binding; API responses; and Razor view rendering all can receive implementation-specific injected classes allowing any compatible JSON serializer to be used. (Canonical example being Newtonsoft.Json aka Json.NET which for the longest time was the de facto standard serializer, before STJ took over.)

@rjgotten that's expanding the scope of my request quite a bit. If the maintainers think it's worth it, then sure. But to be clear this definitely isn't what I'm asking for.

**Comment by eiriktsarpalis** [comment]
> > We should not be exposing global mutable configuration -- this true both for the STJ layer and the HttpClient layer.
> 
> @eiriktsarpalis was the proposal for global mutable configuration the reason for closing the issue? If not, then why? My second alternative was a proposal for an instance-specific implementation.

I believe the `System.Net.Http` library doesn't depend on `System.Text.Json` so it cannot (and arguably should not) encapsulate `JsonSerializerOptions` instances. The helper methods in `System.Net.Http.Json` are just extension methods over `HttpClient`, so they don't really augment the client with added state.

**Comment by smarts** [comment]
@eiriktsarpalis that makes sense. Do you have any recommendations? Re-implementing the extension methods which is problematic given that it means I either have to use different method names (which is confusing and/or less discoverable for engineers) or end up with ambiguous references. Using reflection to modify non-public default options instance makes me cringe as well.

**Comment by eiriktsarpalis** [comment]
Even if you did reimplement the extension methods, there's no way you could associate `HttpClient` with a specific `JsonSerializerOptions` instance (unless you used trickery such as ConditionalWeakTable). If you really needed to, you could try creating a new class that encapsulates both objects and surfaces methods as required.

**Comment by smarts** [comment]
@eiriktsarpalis the idea would be to let the extension methods use a specific `JsonSerializerOptions` instance, not the `HttpClient`. It doesn't solve the problem of needing many serialization strategies, but it does solve the problem of at least being able to control the default strategy.
