### ISSUE TITLE
HttpClient exceptions are always culture specific

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#80424]
### Description

I'm trying to get the exceptions messages of HttpClient in English but they are always in the current culture of Windows.

### Reproduction Steps

```C#
using System.Globalization;

internal class Program
{
    private static void Main(string[] args)
    {
        Go();
        Console.ReadKey();
    }
    async static void Go()
    {
        Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");
        Thread.CurrentThread.CurrentUICulture = new CultureInfo("en-US");
        CultureInfo.DefaultThreadCurrentCulture = new CultureInfo("en-US");
        CultureInfo.DefaultThreadCurrentUICulture = new CultureInfo("en-US");

        try
        {
            HttpResponseMessage webresponse = await new HttpClient().GetAsync("https://www.123blablablub.com");
        }
        catch (Exception e)
        {
            Console.WriteLine(e.Message);
        }
    }
}
```

### Expected behavior

`The specified host is unknown. (www.123blablablub.com:443)`

### Actual behavior

Depending on the language of Windows, for example Spanish it would be:
`El host especificado es desconocido. (www.123blablablub.com:443)`

### Configuration

.NET 6, Windows 11, 64bit, Console / Winforms or WPF project

**Comment by tarekgh** [comment]
This is a duplicate of https://github.com/dotnet/runtime/issues/40427

**Comment by Symbai** [comment]
> This is a duplicate of #40427

I dont think so. #40427 says I can set UI culture to English using CultureInfo.DefaultThreadCurrentUICulture etc. which I am doing in my example. It still doesn't work.

**Comment by tarekgh** [comment]
@Symbai what exception you are getting in the case you mentioned? Is it Win32Exception? If so, then it is same as #40427. Just start read it from the comment https://github.com/dotnet/runtime/issues/40427#issuecomment-1186302327

**Comment by Symbai** [comment]
Its HttpClient, so its System.Net.Http.HttpRequestException, not a Win32Exception.

**Comment by tarekgh** [comment]
Your code throws the following:

```
System.Net.Http.HttpRequestException: No such host is known. (www.123blablablub.com:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
```

So, it throws [System.Net.Sockets.SocketException](https://source.dot.net/#System.Net.Primitives/System/Net/SocketException.Unix.cs,8) which is extending `[Win32Exception](https://source.dot.net/System.Private.CoreLib/A.html#824f982cf95a6267)`.

It is same thing discussed in https://github.com/dotnet/runtime/issues/40427#issuecomment-1186302327. Basically, the message is coming from Windows OS and not from .NET. Windows cannot guarantee to carry English resources in all situations. 

There is some manual workaround here https://gist.github.com/ericstj/c72b90b0c12f86b7918850ee276fac3b which can help get the English message (if Windows has English resources). You can just pick SocketException.NativeErrorCode and call the extension method `ToString` from the work around using English culture.

**Comment by tarekgh** [comment]
>  I cannot even cast it to a Win32Exception

`HttpResponseMessage.InnerException` will have the `SocketException`. Just ensure to check `HttpResponseMessage.InnerException` is not null and is `SocketException`.

**Comment by Symbai** [comment]
The workaround expected a Win32Exception as parameter so I tried casting it which obviously didn't worked. Didn't know about SocketException and native code field. I had to modify the workaround, now it works. Closing as duplicate.
