### ISSUE TITLE
Q: Type 'IconBufferEventArgs' has a ComVisible(false) parent 'System.EventArgs' in its hierarchy, therefore QueryInterface calls for IDispatch or class interfaces are disallowed

### ISSUE THREAD

**Issue by nietras** [dotnet/runtime#80422]
We've been porting quite a few applications from .NET Framework to .NET 6. Many of these use third party libraries for devices. Devices we need to support for 10+ years. Those libraries often don't get updated past some point. Regardless, we have in most cases been able to get these libraries running on .NET 6 despite these targeting .NET 4, 3.5 or even 2.0. However, recently we hit a weird issue that I don't fully understand, so trying to wrap my head around this. 

In a mixed mode library (appears to be built with C++/CLI) targeting .NET Framework 2.0 everything works except one little thing. A managed event raised from native code. The code in question is basically:
```csharp
    public class IconBufferEventArgs : EventArgs
    {
        // Various properties
    }

    public delegate void IconBufferReceivedDelegate(object sender, IconBufferEventArgs args);

    interface IFrameGrabber    
    {
        event IconBufferReceivedDelegate IconBufferReceived;
    }
```
When `IconBufferReceived` is raised this fails with:
```
System.InvalidOperationException: Type 'IconBufferEventArgs' has a ComVisible(false) parent 'System.EventArgs' 
in its hierarchy, therefore QueryInterface calls for IDispatch or class interfaces are disallowed.
```
and `HResult -2146233079/0x80131509` with a call stack like:
```
at System.StubHelpers.InterfaceMarshaler.ConvertToNative(Object objSrc, IntPtr itfMT, IntPtr classMT, Int32 flags)
at XYZ.WrapperCallbackTranslator(IconBuffer* nativeIconBuffer, FrameGrabber* __unnamed001, Void* userdata, FrameGrabberStatus* nativeStatus)"
```
or in debug:
```
XYZ.dll!<Module>.Sick.Icon.WrapperCallbackTranslator(icon.IconBuffer* nativeIconBuffer, icon.FrameGrabber* __unnamed001, void* userdata, icon.FrameGrabberStatus* nativeStatus)
[Native to Managed Transition]
XYZ_51_x64.dll!00000000230dcf4b()
QtCore4_x64.dll!000000006721d415()
msvcr80.dll!000000006bfe37d7()
msvcr80.dll!000000006bfe3894()
kernel32.dll!00007ffe44b07614()
ntdll.dll!00007ffe44d626a1()
```

The exception and call stack indicate an issue with how `EventArgs` is defined e.g. no longer `ComVisible(true)` but `ComVisible(false)` and this being an issue for marshaling. And indeed if we run this in either .NET Fx 4.8 (everything works fine on .NET 4.8)  or .NET 6.0 we will get something like:
```
net4.8: IsComVisible IconBufferEventsArgs False EventArgs True
net6.0: IsComVisible IconBufferEventsArgs False EventArgs False
```

The only issue I have been able to find related to this is https://github.com/dotnet/runtime/issues/27974 (Seeing lots of InvalidOperationExceptions with Automation Peers), but this was closed as fixed by @jkotas in https://github.com/dotnet/coreclr/pull/21137 (Change System.Object to ClassInterface.None), but none of this touches upon `EventArgs`.

So my question is what is going on here? Why does this fail despite as far as I can tell no COM being involved directly? Why has the definition of `EventArgs` changed i.e. no longer `ComVisible(true)`? And could this not be marked as `ComVisible(true)`? If not, what's the issue with applying this to `EventArgs` when it has had that for years? (if it even helps).

Links:
EventArgs does not have `ComVisible(true)` set in 6.0 release:
https://github.com/dotnet/runtime/blob/release/6.0/src/libraries/System.Private.CoreLib/src/System/EventArgs.cs
https://github.com/dotnet/runtime/blob/fb3101268627d83e3b8200d31c8f9c0fd78540a9/src/libraries/System.Private.CoreLib/src/System/EventArgs.cs#L7-L9

`Delegate` however does so why not `EventArgs`?
https://github.com/dotnet/runtime/blob/release/6.0/src/coreclr/System.Private.CoreLib/src/System/Delegate.CoreCLR.cs
https://github.com/dotnet/runtime/blob/fb3101268627d83e3b8200d31c8f9c0fd78540a9/src/coreclr/System.Private.CoreLib/src/System/Delegate.CoreCLR.cs#L13-L15

**Comment by jkotas** [comment]
> Why does this fail despite as far as I can tell no COM being involved directly?

The call stack and error message that you have shared suggest that an object is being marshalled to IDispatch interface. It is as much COM as it can be.

> Why has the definition of EventArgs changed i.e. no longer ComVisible(true)?

In .NET Framework, most types in mscorlib.dll were marked as `ComVisible(true)`. It made difficult to evolve the BCL without breaking backward compatibility for COM for these types. It required introducing workarounds like https://github.com/microsoft/referencesource/blob/master/mscorlib/system/runtime/interopservices/iexception.cs .

In .NET Core, no BCL types are marked as `ComVisible(true)`, except very few exceptions like `Delegate`.

> And could this not be marked as ComVisible(true)?

Marking EventArgs as ComVisible would mean back to the .NET Framework situation that we do not want to be in. I do not think we want to do that.

**Comment by nietras** [comment]
> The call stack and error message that you have shared suggest that an object is being marshalled to IDispatch interface. It is as much COM as it can be.

Right, I guess `InterfaceMarshaler` is pretty telling here. My memory on COM is not great (thankfully 😅). 

> In .NET Core, no BCL types are marked as ComVisible(true), except very few exceptions like Delegate.
> Marking EventArgs as ComVisible would mean going back to the .NET Framework situation that we do not want to be in. I do not think we want to do that.

Even when `EventArgs` is basically a "marker" type without any members etc. and the likelihood of this changing being minimal? There is after all `ComVisible(true)` on `Delegate`. And I would think for the reason not to break a lot more things. That is, I would consider `EventArgs` similar to `Delegate` in this regard, since both used in interop.

Are they any tricks/hacks possible to try to fix this issue without having source code access?

What I find interesting here is that everything else in this 3rd party library works, so the issue appears isolated to `EventArgs` (perhaps native to managed transition?). Is that expected?

Given that I would (perhaps harshly) conclude that if this library hadn't inherited from `EventArgs` there wouldn't have been a problem and (once again) the guidance of inheriting from `EventArgs` shows it's problematic "face". And in this case it provides no value.

**Comment by jkotas** [comment]
> Are they any tricks/hacks possible to try to fix this issue without having source code access?

ildasm, patch the IL, ilasm

**Comment by nietras** [comment]
> Why does your library do with the interface? Does it actually use IDispatch?

It's not *my* library, it's a third party library and I have no idea if they use it, I don't think so given what works. Again my memory on COM details is fuzzy since it's been +10 years since I've been deep into the nitty gritty of it. From our side that is on .NET there is no usage reminiscent of COM at all. It's just plain C# interfaces, types etc.

> ildasm, patch the IL, ilasm

Well, I tried, but this does not work for **mixed-mode assemblies** does it? That is I can definitely `ildasm` but `ilasm` fails with:
```
error : Cannot compile native/unmanaged method
error : Local (embedded native) PInvoke method, the resulting PE file is unusable
```
is there a way to do that?

**Comment by nietras** [comment]
FYI in IL I believe the offending line inside `WrapperCallbackTranslator` is something like:
```msil
calli      unmanaged cdecl void modopt([mscorlib]System.Runtime.CompilerServices.CallConvCdecl)
(class [XXX.Interfaces]YYY.IconBufferEventArgs)
```

**Comment by jkotas** [comment]
There is no good way to modify mixed mode images.

**Comment by AaronRobinsonMSFT** [comment]
@nietras I don't believe there is anything for us to fix here as our removal of `ComVisible` on most types was intentional. Please let me know if I am mistaken and there is action on our side.
