### ISSUE TITLE
CryptoStream shouldn't flush when in read mode

### ISSUE THREAD

**Issue by theolivenbaum** [dotnet/runtime#80427]
### Description

When using a CryptoStream in read mode, the [Dispose method ](https://github.com/dotnet/runtime/blob/d4dbcc64f6f62ce023bb917d7c4fd0678004deeb/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/CryptoStream.cs#L744) and [DisposeAsync method](https://github.com/dotnet/runtime/blob/d4dbcc64f6f62ce023bb917d7c4fd0678004deeb/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/CryptoStream.cs#L784) might invoke Flush on the original stream, which is not expected as we're not writing to it.

### Reproduction Steps

```csharp
var source = new ReadOnlyStream(); //Any stream implementation that throws on Flush works here
var encryptor = //Create Encryptor - example: AES)
using var cs = new CryptoStream(source, encryptor, CryptoStreamMode.Read);
//Do something with the stream;
//Will throw on the call to Flush when the CryptoStream is disposed

```

### Expected behavior

No call to Flush on a read-only operation

### Actual behavior

CryptoStream Dispose method calls Flush regardless.

### Regression?

I think so - didn't observe the issue on NET60 (but not sure)

### Configuration

NET70

**Comment by vcsjones** [comment]
Duplicate of #25129

**Comment by theolivenbaum** [comment]
Understood! Will change how we use it then to reflect this behavior! Thanks @vcsjones
