### ISSUE TITLE
The CustomAttributeTypeNameParser is not able to translate generics correctly

### ISSUE THREAD

**Issue by tlakollo** [dotnet/runtime#80462]
### Description

The CustomAttributeTypeNameParser fails to translate generic types and generic methods names. Instead of getting something like Foo<T> will get Foo<!0>. Xml processing relies on the CustomAttributeTypeNameParser to understand the different Cecil formats and be able to take decisions based on that.

### Reproduction Steps

In a descriptor file add a method with a generic signature
`<method signature="System.Void PreservedMethod5(T)" />`
Then have a method declaration that is never used
`private void PreservedMethod5<T> (T arg) { }`

### Expected behavior

The PreservedMethod should be kept

### Actual behavior

The PreservedMethod is not kept

**Comment by MichalStrehovsky** [comment]
Which use of CustomAttributeTypeNameParser this is referring to? Do we call into it from any other place than:

https://github.com/dotnet/runtime/blob/7ac3cde6be0d10e0bb8d6e5fe0b95eeca549e2b8/src/coreclr/tools/Common/Compiler/ProcessLinkerXmlBase.cs#L195-L197

We already have an issue for this one - it's in the comment.

**Comment by tlakollo** [comment]
Yup, https://github.com/dotnet/runtime/issues/73083 will do
