### ISSUE TITLE
NativeAOT doesnt have a way to remove all occurences of an attribute

### ISSUE THREAD

**Issue by tlakollo** [dotnet/runtime#80466]
### Description

ILLink has the option of using a wildcard `*` when processing [LinkAttributes](https://github.com/dotnet/linker/blob/main/src/linker/Linker.Steps/LinkAttributesParser.cs#L450) xml files. This allows removing an attribute existing in System.Private.CoreLib from all input assemblies (including System.Private.CoreLib). The way ILLink does this is by using its context to remember which attribute needs to be removed. NativeAOT doesnt have access to this context that coul allow to remember which attribute needs to be removed from other assemblies, therefore NativeAOT currently does not support the `*` wildcard

### Reproduction Steps

System.Private.CoreLib actually declares a LinkAttributes xml file with this pattern https://github.com/dotnet/runtime/blob/main/src/mono/System.Private.CoreLib/src/ILLink/ILLink.LinkAttributes.xml#L10-L15

### Expected behavior

The attribute is removed from all the assemblies

### Actual behavior

The attribute is kept

**Comment by MichalStrehovsky** [comment]
We already track this in #77753.
