### ISSUE TITLE
StripSymbols doesn't seem to work on 7.0.102 arm64 Raspbian OS

### ISSUE THREAD

**Issue by maloo** [dotnet/runtime#80499]
### Description

See console output below. Setting StripSymbols doesn't strip symbols. Not sure if it is a general issue or just on this setup.

neptron@ntu999:~/test $ dotnet publish -r linux-arm64 -c Release -p:PublishAot=true -p:StripSymbols=true -o pub
MSBuild version 17.4.1+9a89d02ff for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  test -> /home/neptron/test/bin/Release/net7.0/linux-arm64/test.dll
  test -> /home/neptron/test/pub/
neptron@ntu999:~/test $ ls -la pub
total 12900
drwxr-xr-x 2 neptron neptron     4096 Jan 11 14:15 .
drwxr-xr-x 5 neptron neptron     4096 Jan 11 14:12 ..
-rwxr-xr-x 1 neptron neptron 13201120 Jan 11 14:12 test
neptron@ntu999:~/test $ strip pub/test
neptron@ntu999:~/test $ ls -la pub
total 3884
drwxr-xr-x 2 neptron neptron    4096 Jan 11 14:15 .
drwxr-xr-x 5 neptron neptron    4096 Jan 11 14:12 ..
-rwxr-xr-x 1 neptron neptron 3965200 Jan 11 14:15 test

### Reproduction Steps

create a new console app and publish as in description above.

UPDATE: you have to build once w/o StripSymbols first. Then next build as above.
dotnet publish -r linux-arm64 -c Release -p:PublishAot=true -o pub
dotnet publish -r linux-arm64 -c Release -p:PublishAot=true -p:StripSymbols=true -o pub

### Expected behavior

symbols should be stripped

### Actual behavior

symbols have to be manually stripped

### Known Workarounds

strip manually

### Configuration

see title

**Comment by maloo** [comment]
It seems like you have to remove bin/ obj/ and do a clean rebuild for StripSymbols to take effect. So I guess the bug is that StripSymbols doesn't work when already built once w/o it.

**Comment by am11** [comment]
> So I guess the bug is that StripSymbols doesn't work when already built once w/o it.

This behavior is not specific to `StripSymbols`. Property change does not force a rebuild on its own. Try e.g. `-p:Optimize=true` record the binary size, then `-p:Optimize=false` without deleting obj and bin dirs, the binary size won't change unless you delete the obj dir.

**Comment by maloo** [comment]
That kind of s**ks from a usability point of view. If I change a normal "Makefile" I get a rebuild triggered by deps changed. And since not even a "dotnet clean" in between helps here, it makes it even worse. Not sure why dotnet can't fix clean so you don't have to use git to clean ... what does clean even do since it doesn't clean the project dir from build output?

**Comment by am11** [comment]
> That kind of s**ks from a usability point of view.

Yes, and NativeAOT or not, this issue persists in .NET SDK, since 5.0. Ultimately this is the same issue with other application models https://github.com/dotnet/runtime/issues/62219#issuecomment-984249404; "changing properties between restore, build and publish step does not trigger the rebuild". So roughly it goes like: when we run `dotnet publish` (without --no-build flag), it forwards to msbuild to run the `Build` target, then msbuild skips the `Build` target because no source file was changed, then `Publish` target gets skipped because `Build` target was skipped. You can see exactly what is going on with `-v:diag > verbose-dump.log`.

Normally users have properties distilled in the csproj:

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <PublishAot>true</PublishAot>
    <Optimize>true</Optimize>
    <StripSymbols>true</StripSymbols>
  </PropertyGroup>

</Project>
```

and then your release build will always be optimized when you will execute `dotnet publish -c Release`

**Comment by maloo** [comment]
What are the defaults of Release? "-s" instead of "-o2" equivalent? I thought the whole point of that config was to optimize (and skip DEBUG define)?

I would lova a code first approach to building, basically make the build a compilable app instead of this hard to debug and use msbuild stuff. Like cake or build.rs.

**Comment by maloo** [comment]
btw, @am11 , do you know if there are any instructions to cross compile aot using docker buildx or other qemu solutions in WSL2? I need to build arm64 AOT target on x64 ...

**Comment by jkotas** [comment]
> do you know if there are any instructions to cross compile aot using docker 

The instructions are at https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/compiling.md#cross-architecture-compilation

**Comment by agocke** [comment]
Closing as dup of https://github.com/dotnet/runtime/issues/62219 (I agree this really sucks).
