### ISSUE TITLE
Documentation Comments for IMultiplyOperators`3 mention division.

### ISSUE THREAD

**Issue by otac0n** [dotnet/runtime#80521]
### Description

The return value of both the checked and unchecked operators of the IMultiplyOperators`3 interface are documented as:

> The product of \<paramref name="left" /> divided-by \<paramref name="right" />.

It should read

> The product of \<paramref name="left" /> multiplied-by \<paramref name="right" />.

### Reproduction Steps

None, this is a documentation issue.

### Expected behavior

The return value should be documented as:

> The product of \<paramref name="left" /> multiplied-by \<paramref name="right" />.

### Actual behavior

The return value of both the checked and unchecked operators of the IMultiplyOperators`3 interface are documented as:

> The product of \<paramref name="left" /> divided-by \<paramref name="right" />.

### Known Workarounds

None.

**Comment by tannergooding** [comment]
Marked this as up for grabs. Please feel free to submit a fix to both the XML comments in the runtime repo and to the corresponding docs page here: https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Numerics/IMultiplyOperators%603.xml

**Comment by IDisposable** [comment]
Also fixed NFloat.cs  (line 169) `operator *` comment

**Comment by IDisposable** [comment]
Added PRs for the source code fixed in [runtime source](https://github.com/dotnet/runtime/pull/83693) and in the [documentation](https://github.com/dotnet/dotnet-api-docs/pull/8915)

**Comment by IDisposable** [comment]
I noticed while scanning the documentation that there's a WHOLE lot of stuff missing the content that should have been automatically pulled from the source documentation but currently reads `To be added`. Is there a plan in place to sync this stuff up via an automated tool, or would there be value in cleaning some of that up by hand?

**Comment by IDisposable** [comment]
Warning, the documentation push flagged this as closed but the PR for the ///  comments has not yet been merged.
