### ISSUE TITLE
JsonSerializerOptions.GetTypeInfo throws when TypeInfoResolver is `null`

### ISSUE THREAD

**Issue by brunolins16** [dotnet/runtime#80529]
### Description

`JsonSerializerOptions.TypeInfoResolver` is documented as:

```log
A <see langword="null"/> setting is equivalent to using the reflection-based <see cref="[DefaultJsonTypeInfoResolver](https://source.dot.net/System.Text.Json/P/29c640504d3d4bbe.html#29c640504d3d4bbe)" />.
        /// The property will be populated automatically once used with one of the <see cref="[JsonSerializer](https://source.dot.net/System.Text.Json/P/2ca342a99419a245.html#2ca342a99419a245)"/> methods.
```

This behavior works correctly, however if instead try to obtain the `JsonTypeInfo` from the `JsonSerializerOptions` before calling the serializer it fails.

cc @davidfowl @eiriktsarpalis 

### Reproduction Steps

```c#
using System.Text.Json;

var options = new JsonSerializerOptions();
var typeinfo = options.GetTypeInfo(typeof(string));
```

### Expected behavior

When `JsonSerializerOptions.TypeInfoResolver` is null and a call to `JsonSerializerOptions.GetTypeInfo` happens it should behave similarly to a call to the `JsonSerializer` methods.

Probably in AOT-mode `DefaultJsonTypeInfoResolver` should not need to be set and throws at runtime might be ok.

### Actual behavior

```log
System.NotSupportedException
  HResult=0x80131515
  Message=Metadata for type 'System.String' was not provided by TypeInfoResolver of type '<null>'. If using source generation, ensure that all root types passed to the serializer have been indicated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_NoMetadataForType(Type type, IJsonTypeInfoResolver resolver) in /_/src/libraries/System.Text.Json/src/System/Text/Json/ThrowHelper.Serialization.cs:line 709
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Boolean resolveIfMutable) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 75
   at Program.<Main>$(String[] args) in C:\Users\brolivei\source\repos\WebApplication24\Program.cs:line 5
```

### Known Workarounds

Manually instantiate the `JsonSerializerOptions` with the `DefaultJsonTypeInfoResolver`

eg.:

```c#
var options = new JsonSerializerOptions() { TypeInfoResolver = new DefaultJsonTypeInfoResolver() } ;
```

### Configuration

.NET  7

**Comment by krwq** [comment]
We already have a solution for that in 8.0. Calling options.MakeReadOnly before GetTypeInfo. This has been added here https://github.com/dotnet/runtime/pull/74431

I think we should leave the issue open for now in case we want to re-iterate on the null in TypeInfoResolver/Combine.
Possibly we could consider adding some flag to control null behavior 🙄

**Comment by eiriktsarpalis** [comment]
> When JsonSerializerOptions.TypeInfoResolver is null and a call to JsonSerializerOptions.GetTypeInfo happens it should behave similarly to a call to the JsonSerializer methods.

The problem with the JsonSerializer methods is that they _have_ to be marked RequiresUnreferencedCode/RequiresDynamicCode precisely because they populate `TypeInfoResolver`. We decided to go with the throwing behaviour in `GetTypeInfo` here in order to make it work well with trimming/AOT scenaria.

**Comment by brunolins16** [comment]
> The problem with the JsonSerializer methods is that they _have_ to be marked RequiresUnreferencedCode/RequiresDynamicCode precisely because they populate `TypeInfoResolver`. We decided to go with the throwing behaviour in `GetTypeInfo` here in order to make it work well with trimming/AOT scenaria.

I got your point, however, in my opinion the `JsonSerializerOptions.GetTypeInfo` becomes useless when not using a source generator and confusing behavior because I cannot write a simple code, like this:

```c#
var options = new JsonSerializerOptions();
var typeinfo = options.GetTypeInfo(typeof(string));
var content = JsonSerializer.Serialize("value", typeinfo);
```

However, I can write something like this:

```c#
var options = new JsonSerializerOptions();
var content = JsonSerializer.Serialize("value", options);
```

**Comment by eiriktsarpalis** [comment]
Closing in favor of https://github.com/dotnet/runtime/issues/83279
