### ISSUE TITLE
Unity 2022.2.1f1 - System.Text.Json "no viable overloaded '='"

### ISSUE THREAD

**Issue by jakedowns** [dotnet/runtime#80525]
### Description

Attempting to use `System.Text.Json.6.0.6` in my `Unity 2022.2.1f1` project

the project compiles fine with the Mono scripting backend,
but, that is limited to 32-bit arm support.
I need 64-bit arm support for publishing to Google Play, so I need to use the **IL2CPP** backend

Unity 2022 introduced support for Full Generic Sharing:
https://blog.unity.com/technology/feature-preview-il2cpp-full-generic-sharing-in-unity-20221-beta

which solved a previous, runtime issue I was having with **System.Text.Json** trying to call an undefined generic method

but now, I'm getting a build-time error:

Full error here:
https://gist.github.com/jakedowns/4e1462e6b877d348539cc4d20fead3e5

### Reproduction Steps

Pull this Unity Project 
https://github.com/ryanhlewis/unity-youtube-explode/tree/sample-project

and open it in Unity 2022.2.1f1, targeting Android armv7 and arm64 (v8) with IL2CPP enabled

try to compile, see the error.

### Expected behavior

It should compile and run without error

### Actual behavior

It fails to build

### Known Workarounds

If I build for Mono + armv7 only, it works

### Configuration

the unity project player settings targets .NET Standard 2.1
I've also tried building while targeting .NET Framework (4.8)

neither builds, and both throw the same error

![image](https://user-images.githubusercontent.com/1683122/211937416-e64e3ead-2a1f-444b-b39f-948bcc43490e.png)

![image](https://user-images.githubusercontent.com/1683122/211938413-bd6319e9-d955-4479-b2c1-6130f927dffd.png)

**Comment by jakedowns** [comment]
> I couldn't figure out the best area label to add to this issue. If you have write-permissions please help me learn by adding exactly one [area label](https://github.com/dotnet/runtime/blob/master/docs/area-owners.md).

`area-System.Text.Json`

**Comment by MichalPetryka** [comment]
This should probably be reported to Unity instead, could you upload a zip of `Library\Bee\artifacts\Android\il2cppOutput\cpp` though so I can check what does IL2CPP exactly generate here?

**Comment by MichalPetryka** [comment]
[This](https://github.com/ryanhlewis/unity-youtube-explode/blob/sample-project/Assets/unity-youtube-explode-main/YoutubePlayer.cs#L148) is the line where Unity fails, the var has a different generic instantiation of the ValueTask than the method returns.

**Comment by jakedowns** [comment]
> [This](https://github.com/ryanhlewis/unity-youtube-explode/blob/sample-project/Assets/unity-youtube-explode-main/YoutubePlayer.cs#L148) is the line where Unity fails, the var has a different generic instantiation of the ValueTask than the method returns.

thank you so much for the feedback.
here is the cpp folder: https://www.dropbox.com/s/v2bwwhmqmvz4f1n/cpp.7z?dl=0

**Comment by jakedowns** [comment]
@MichalPetryka it seems like the issue persists even if i set an explicit type:

```
StreamManifest streamManifest = await youtube.Videos.Streams.GetManifestAsync(trimmedPath);
``` 

vs

```
var streamManifest = await youtube.Videos.Streams.GetManifestAsync(trimmedPath);
```

**Comment by MichalPetryka** [comment]
> @MichalPetryka it seems like the issue persists even if i set an explicit type:
> 
> ```
> StreamManifest streamManifest = await youtube.Videos.Streams.GetManifestAsync(trimmedPath);
> ```
> 
> vs
> 
> ```
> var streamManifest = await youtube.Videos.Streams.GetManifestAsync(trimmedPath);
> ```

It's because it's Unity that's generating the wrong type in IL2CPP, not you in your C# code.

**Comment by jakedowns** [comment]
> > @MichalPetryka it seems like the issue persists even if i set an explicit type:
> 
> > 
> 
> > ```
> 
> > StreamManifest streamManifest = await youtube.Videos.Streams.GetManifestAsync(trimmedPath);
> 
> > ```
> 
> > 
> 
> > vs
> 
> > 
> 
> > ```
> 
> > var streamManifest = await youtube.Videos.Streams.GetManifestAsync(trimmedPath);
> 
> > ```
> 
> 
> 
> It's because it's Unity that's generating the wrong type in IL2CPP, not you in your C# code.

i've pinged Josh Peterson (Lead of the .NET VM team at unity) https://twitter.com/jakedowns/status/1613682565386506241?s=46&t=S_JhvpFE4JJTpb9DhOu_5g

is there anything that could be done within this library in the meantime aside from replacing System.Text.Json as a dependency?

https://github.com/Tyrrrz/YoutubeExplode/blob/dc711851373da1b13e21ba7edf2a860bf3292ea5/YoutubeExplode/Videos/Streams/StreamManifest.cs

**Comment by jakedowns** [comment]
gonna switch to [Newtonsoft.Json-for-Unity](https://github.com/jilleJr/Newtonsoft.Json-for-Unity) for now
