### ISSUE TITLE
Static constructor on an interface is not invoked

### ISSUE THREAD

**Issue by zvrba** [dotnet/runtime#80538]
### Description

In Net7 (and possibly previous versions), it is possible to declare and  implement a static constructor on an interface. However, the constructor is never invoked.

### Reproduction Steps

Compile and run the following program. Set breakpoints on lines marked 1 and 2.

```
interface IComponent
{
    internal static readonly List<IComponent> Components = new();
}
interface IComponent<T> : IComponent where T : IComponent, new()
{
    static IComponent() {
        Components.Add(new T());                               ///////////////// 1
    }
}
class Component : IComponent<Component>
{
    static Component() {
        IComponent.Components.Add(null);               ///////////////// 2
    }
    public string F;
}

public static class Program
{
    public static void Main() {
        var z = new Component() { F = "asd" };
        var k = IComponent.Components.Count;
    }
}
```

### Expected behavior

That static constructor on line marked 1 is invoked when the first instance of the interface is created (i.e., when any class implementing it is created). Alternatively, that the compiler reports a compile error when a static ctor on an interface is defined.

### Actual behavior

Only class static ctor is executed, the interface static ctor is ignored.

**Comment by jkotas** [comment]
Referencing a method defined by an interface does not trigger interface static constructor.

The static constructors are triggered by accessing a static field or execution of a method implemented by the type. For example, the static constructor will be triggered in this example:

```csharp
((IComponent)new Component()).M();

class Component : IComponent
{
}

interface IComponent
{
    int M() => 1;

    static IComponent()
    {
        Console.WriteLine("IComponent constructor");
    }
}
```

**Comment by zvrba** [comment]
So to clarify: class static ctor is invoked upon on first `new()` of the class because class instance ctor is "implemented by the type"?

**Comment by jkotas** [comment]
The static constructor is triggered by code in the type. In my example, it is triggered by `int M() => 1;` .

If you change the example to:
```csharp
((IComponent)new Component()).M();

class Component : IComponent
{
    int IComponent.M() => 2;
}

interface IComponent
{
    int M() => 1;

    static IComponent()
    {
        Console.WriteLine("IComponent constructor");
    }
}
```
The IComponent static constructor is not going to be triggered anymore since no code in the type runs anymore.

**Comment by zvrba** [comment]
Ok, I think I get it now. Thanks for the explanation.
