### ISSUE TITLE
[API Proposal]: Support for Atomic "Interlocked" operations on arbitrary length structs

### ISSUE THREAD

**Issue by adam-dot-cohen** [dotnet/runtime#80535]
### Background and motivation

Atomic operations on arbitrary length structs are an extremely common.  Using `lock` yields suboptimal performance and results in repetitive bespoke implementations with a lighter weight alternatives such as 'SpinLock'.   The primary objectives of this proposal are to provide a utility that provides:

1. Atomic operations on value types of arbitrary length
2. Uses a light-weight locking mechanism
3. Abstracts away repetitive locking code

### API Proposal

```csharp
public sealed class Atomic<T> where T : unmanaged
{
	private AtomicSpinWait _wait = new();
	
	private Operation _operation;

	private T _value;

	public Atomic(T value)
	{
		_value = value;
		_operation = new Operation(this);
	}

	public T Value => _value;

	public void Op(Action<Operation> del)
	{
		_wait.Acquire();
		del(_operation);
		_wait.Release();
	}

	public sealed class Operation
	{
		private Atomic<T> _atomic;

		public Operation(Atomic<T> atomic) => _atomic = atomic;

		public T Value
		{
			get => _atomic._value;
			set => _atomic._value = value;
		}
		public void Update(T value)
			=> _atomic._value = value;

		public bool CompareExchange(T value, T compareand)
		{
			if (!_atomic.Equals(compareand))
			{
				_atomic._value = value;
				return true;
			}
			return false;
		}

		public T Exchange(T value)
		{
			var result = this.Value;

			_atomic._value = value;

			return result;
		}
	}

	[StructLayout(LayoutKind.Auto)]
	private struct AtomicSpinWait
	{
		private int _value;
		public AtomicSpinWait() => _value = 0;

		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public void Acquire()
		{
			for (var sw = new SpinWait(); Interlocked.CompareExchange(ref _value, 1, 0) == 1; sw.SpinOnce()) ;
		}

		public void Release() => _value = 0;
	}
}
```

### API Usage

**Struct Example**
```csharp
Guid key = Guid.NewGuid();
var atomic = new Atomic<Guid>();

atomic.Op(a =>
{
     //perform any atomic operation or use helper functions...
     if(a.CompareExchange(Guid.NewGuid(), key))
     {
          // store new key
     }
}

// IsEqual helper function works on any struct or enum...
var newGuid = new Guid.NewGuid();
atomic.Op(a => a.Value =  !a.IsEqual(newGuid) ? newGuid : a.Value );
```

**Enum Example**
```csharp
StateEnum state = StateEnum.Started;
var atomic = new Atomic<StateEnum>();

atomic.Op(a => 
{
     if(a.CompareExchange(State.Stopped, State.Started))
     {
          // stopping logic
    }
});
```

### Alternative Designs

Sample is purely for illustrative purposes.  I'm sure the MS brain trust come up a more technically sound implementation.

**Comment by danmoseley** [comment]
https://github.com/dotnet/runtime/issues/24694

Less related

https://github.com/dotnet/runtime/issues/17975

https://github.com/dotnet/runtime/issues/13048

**Comment by adam-dot-cohen** [comment]
#24694 has some similar themes in the conversation.  That said, I'm suggesting a need for something that doesn't have the 4-byte or 8-byte limitation (i.e. base32-bit / 64-bit architecture) of `Interlocked`.  Support for structs that require more than one mov instruction - Guid, decimal, etc.   Take the `Vector<int>` a 32-byte vector for instance...

```csharp

	Atomic<Vector<int>> inter = new();
	var vec0 = Vector<int>.Zero;
	var vec1 = Vector<int>.One;
	
	var result = inter.CompareExchange(ref vec0, vec1, vec0);
	
	Console.WriteLine(result);    //<0, 0, 0, 0, 0, 0, 0, 0>
	Console.WriteLine(vec0);     //<1, 1, 1, 1, 1, 1, 1, 1>
```

**Comment by adam-dot-cohen** [comment]
It probably goes without saying but I hacked this together quickly.  There really isn't a good reason for Atomic to be an open generic...

```csharp

	var inter = Atomic.Create();
	var vec0 = Vector<int>.Zero;
	var vec1 = Vector<int>.One;
	
	var result = inter.CompareExchange(ref vec0, vec1, vec0);
	
	Console.WriteLine(result);    //<0, 0, 0, 0, 0, 0, 0, 0>
	Console.WriteLine(vec0);     //<1, 1, 1, 1, 1, 1, 1, 1>
```

```csharp
[StructLayout(LayoutKind.Auto)]
public struct Atomic 
{
	private AtomicSpinWait _lock;
	public Atomic() => _lock = new();

	public static Atomic Create() => new();

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public T CompareExchange<T>(ref T current, T value, T compareand)
		where T : struct
	{
		_lock.Acquire();

		var result = current;

		var sizeOf = Unsafe.SizeOf<T>();

		if (MemoryMarshal.CreateReadOnlySpan(ref Unsafe.As<T, byte>(ref current), sizeOf).SequenceEqual(
			MemoryMarshal.CreateReadOnlySpan(ref Unsafe.As<T, byte>(ref compareand), sizeOf)))
			current = value;

		_lock.Release();

		return result;
	}

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public T Exchange<T>(ref T location, T value)
		where T : struct
	{
		_lock.Acquire();

		var result = location;

		location = value;

		_lock.Release();

		return result;
	}

	[StructLayout(LayoutKind.Auto)]
	private struct AtomicSpinWait
	{
		private volatile int _value;

		public AtomicSpinWait() => _value = 0;

		internal void Acquire()
		{
			for (var sw = new SpinWait(); CompareExchange(1, 0) == 1; sw.SpinOnce()) ;
		}

		internal void Release() => _value = 0;

		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		private int CompareExchange(int value, int comparand)
			=> Interlocked.CompareExchange(ref _value, value, comparand);
	}
}

**Comment by Tornhoof** [comment]
fwiw, you constraint should be ``unmanaged`` and you might want to assert somewhere with  RuntimeHelpers.IsReferenceOrContainsReferences<>(). (should be equivalent afaik)

**Comment by stephentoub** [comment]
I'm not clear on what this is really providing.  The `SpinLock` type already exists, and serves the same purpose as but a more robust implementation than the suggested AtomicSpinWait.  At that point, anyone that really wants this behavior just declares a SpinLock instead of an Atomic, and uses Wait/Release around their accesses.

**Comment by adam-dot-cohen** [comment]
Agreed on `SpinLock` (modified proposal).   To clarify, the objectives of the proposal is a utility that provides:

1. Atomic operations on value types of arbitrary length
2. Uses a light-weight locking mechanism
3. Abstracts away repetitive locking code

I updated 'Atomic' in the above proposal so it can be utilized across threads.  Also simplified the examples which I copied here as well for convenience...

**Struct Example**
```csharp
Guid key = Guid.NewGuid();
var atomic = new Atomic();

if(atomic.CompareExchange(ref key, Guid.NewGuid(), key) == key)
{
     // store new key
}
```

**Enum Example**
```csharp
StateEnum state = StateEnum.Started;
var atomic = new Atomic();

if(atomic.CompareExchange(ref state, state.Stopped, state.Started) == State.Started)
{
     // stopping logic
}
```

**Comment by stephentoub** [comment]
Can you share a real example?  The struct example, for example, is using locals (which unless they're being captured in a shared lambda) doesn't make sense for such synchronization primitives, and the CompareExchange using the same value for both the target of the ref, the old value, and the comparison value isn't something you'd typically find in bug-free code.

Overall, I'm not a big fan of providing helpers like that described.  Just providing CompareExchange and Exchange leaves a lot of missing functionality, e.g. just reading the value without replacing it, and without providing every such operation (you can see a few more in the proposal at https://github.com/dotnet/runtime/issues/17975), developers will end up operating on the value directly, which then can break any atomicity promised even by the exposed methods.  Direct use of a lock isn't particularly onerous, and unless significant value is provided by the wrappers, I think it's a net negative to expose such things.

**Comment by adam-dot-cohen** [comment]
Fair point re: developers working around the class.  I've modified the API proposal so `Atomic` acts as a holder that can be passed as a reference across threads, and forces changes to encapsulated value type to the `Atomic.Op(x=> )` lambda.  SEE BOTTOM of post for example usage - and keep in mind that `CompareExchange` is just a helper function, anything can be done to `Operation.Value` inside the lamda.  That said, the `IsEqual` function used by `CompareExchange` supports any value type.

Regarding `AtomicSpinWait` vs `SpinLock`, it dawned on me I was using `AtomicSpinWait` because it's roughly an order of magnitude faster than `SpinLock1 so I added back in for reference.  See benchmark project [here](https://github.com/adam-dot-cohen/Atomic).

|         Method |      Mean |     Error |    StdDev |   Gen0 | Allocated |
|--------------- |----------:|----------:|----------:|-------:|----------:|
|    Interlocked |  4.300 ns | 0.0015 ns | 0.0012 ns |      - |         - |
| AtomicSpinWait |  8.452 ns | 0.0729 ns | 0.0647 ns | 0.0018 |      24 B |
|       SpinLock | 74.869 ns | 0.0934 ns | 0.0828 ns | 0.0018 |      24 B |

**EXAMPLE**
The example uses `int` for simplicity.  Keep in mind that the class is really intended for variable length structs that aren't supported by `Interlocked`.  For example, a stock quote (Ask, AskSize, Bid, BidSize).
```csharp
public static class AtomicExample
{ 
	static Channel<int> _channel;
	static int iterations = 1_000_000;
	public static void Run()
	{
		var atomic = new Atomic<int>(0);
		_channel = Channel.CreateUnbounded<int>();
		
		var readTasks = Enumerable.Range(0, 3)
			.Select(x=> AsyncReader(atomic)).ToArray();
		
		AsyncWriter();
		
		Task.WaitAll(readTasks);
		
		Debug.Assert(atomic.Value == iterations);
	}

	public static void AsyncWriter()
	{
		Enumerable.Range(1, iterations).ToList().ForEach((e) => _channel.Writer.WriteAsync(e));
		_channel.Writer.Complete();
	}

	public static async Task AsyncReader(Atomic<int> atomic)
	{
		await foreach (var item in _channel.Reader.ReadAllAsync())
			atomic.Op(a =>
			{
				if (a.CompareExchange(a.Value++, a.Value))
				{
					// do something
				}
			});	
	}
}
```

**Comment by stephentoub** [comment]
> it dawned on me I was using AtomicSpinWait because it's roughly an order of magnitude faster than `SpinLock1 so I added back in for reference.

That's because by default it had diagnostics you haven't turned off. If you don't want those diagnostics, you need to use this ctor:
https://learn.microsoft.com/en-us/dotnet/api/system.threading.spinlock.-ctor?view=net-7.0#system-threading-spinlock-ctor(system-boolean)

> I've modified the API proposal so Atomic acts as a holder that can be passed as a reference across threads, and forces changes to encapsulated value type to the Atomic.Op(x=> ) lambda.

Which now requires an allocation to wrap the T, every operation involves a delegate dispatch, unless you complicate usage even more you now risk closures on every usage, you're copying around a potentially large T very frequently, the type continues to use an incorrect notion of equality, you're allocating a new Operation object for every single call,...

**Comment by adam-dot-cohen** [comment]
Apologies, not trying to get this perfect - but, I made changes to address some of your concerns.

Thanks for the pointer on diagnostics.  It's still 2x slower but significantly faster.

|         Method |      Mean |     Error |    StdDev |   Gen0 | Allocated |
|--------------- |----------:|----------:|----------:|-------:|----------:|
|    Interlocked |  4.302 ns | 0.0022 ns | 0.0018 ns |      - |         - |
| AtomicSpinWait |  8.426 ns | 0.0205 ns | 0.0171 ns | 0.0018 |      24 B |
|       SpinLock | 16.296 ns | 0.0467 ns | 0.0414 ns | 0.0018 |      24 B |

If you don't feel there's merit to the proposal - feel free to close it out.

**Comment by stephentoub** [comment]
> It's still 2x slower

Because the AtomicSpinWait you're using is buggy: its Exit method isn't using any synchronization, not even volatile, which will allow operations to move in and out of the lock's protection, in particular on architectures with weaker memory models, like arm. By default, SpinLock's Exit uses a full memory barrier... if you want to downgrade it to just a store release barrier, pass false to the Exit(bool) overload to improve performance at the expense of potentially allowing some operations after the lock to move into it. 

Writing lock-free synchronization primitives is hard.

**Comment by davidfowl** [comment]
> Writing lock-free synchronization primitives is hard.

Even Chatgpt gets them wrong 🥹
