### ISSUE TITLE
NET7 macOS: Impossible to symbolize managed addresses in AppCenter

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#80550]
_From @tipa on Thu, 12 Jan 2023 08:25:33 GMT_

In AppCenter, I am seeing crash reports for my .NET7 macOS app looking like this one:

![Screenshot 2023-01-12 at 09 13 30](https://user-images.githubusercontent.com/2863198/212013189-d632c72a-cb98-4632-9b9f-c09447ceb07e.png)

I have uploaded the .dSYM file for my app, but it's not enough to find out where the app crashed. I think AppCenter would also need the "libcoreclr.dSYM" file, but I cannot find it anywhere. Is there any possibility to create this file or is there another way to get more information out of the crash report?

My csproj looks something like this

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0-macos</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>MyApp</RootNamespace>
    <AssemblyName>MyApp</AssemblyName>
    <SupportedOSPlatformVersion>11.0</SupportedOSPlatformVersion>
    <RuntimeIdentifiers>osx-x64;osx-arm64</RuntimeIdentifiers>
    <EnableCodeSigning>true</EnableCodeSigning>
    <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
    <CodeSignProvision>Automatic</CodeSignProvision>
    <CodesignKey>Apple Development: ...</CodesignKey>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <TrimMode>link</TrimMode>
    <CodesignKey>Apple Distribution: ...</CodesignKey>
    <PackageSigningKey>3rd Party Mac Developer Installer: ...</PackageSigningKey>
    <EnablePackageSigning>true</EnablePackageSigning>
    <ArchiveOnBuild>true</ArchiveOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AppCenter.Crashes" Version="5.0.1" />
    <PackageReference Include="Microsoft.AppCenter.Analytics" Version="5.0.1" />
...
  </ItemGroup>
  <Import Project="..\MyApp\MyApp.projitems" Label="Shared" Condition="Exists('..\ MyApp\MyApp.projitems')" />
  <!-- https://github.com/xamarin/xamarin-macios/issues/16189 -->
  <Target Name="RemoveCreateDump" BeforeTargets="_ComputePublishLocation" AfterTargets="ComputeFilesToPublish">
    <ItemGroup>
      <_CreateDump Include="@(ResolvedFileToPublish)" Condition=" '%(ResolvedFileToPublish.Filename)' == 'createdump' And '%(ResolvedFileToPublish.Extension)' == '' And '%(ResolvedFileToPublish.AssetType)' == 'native'" PublishFolderType="Assembly" />
      <ResolvedFileToPublish Remove="@(_CreateDump)" />
    </ItemGroup>
  </Target>
</Project>
```

I was building the app using `dotnet publish -c Release`

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac
Version 17.4.2 (build 17)
Installation UUID: b4fb2e35-bce6-4233-8ede-13b9a37f2a2e

Runtime
.NET 6.0.12 (64-bit)
Architecture: Arm64

Roslyn (Language Service)
4.4.0-6.22578.12+3c6ab8e1715e5b080fb7bb77070810ab71e09387

NuGet
Version: 6.3.1.1

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.101/Sdks
SDK Versions:
	7.0.101
	7.0.100
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64)
SDK Versions:
	3.1.426
	3.1.425
	3.1.424

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.1
	7.0.0
	7.0.0-rc.2.22472.3
	6.0.11
	6.0.10

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	3.1.32
	3.1.31
	3.1.30

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 14.1 (21534.1)
Build 14B47b

Xamarin.Mac
Version: 9.0.0.28 (Visual Studio Community)
Hash: 6714e055b
Branch: xcode14.1
Build date: 2022-11-29 11:45:28-0500

Xamarin.iOS
Version: 16.1.1.28 (Visual Studio Community)
Hash: 6714e055b
Branch: xcode14.1
Build date: 2022-11-29 11:45:29-0500

Xamarin Designer
Version: 17.4.0.136
Hash: d49c9ff6d3
Branch: remotes/origin/d17-4
Build date: 2022-12-13 00:02:45 UTC

Xamarin.Android
Not Installed

Microsoft Build of OpenJDK
Java SDK: Not Found

Eclipse Temurin JDK
Java SDK: Not Found

Android SDK Manager
Version: 17.4.0.54
Hash: 6eabb9e
Branch: remotes/origin/d17-4
Build date: 2022-12-13 00:02:50 UTC

Android Device Manager
Version: 0.0.0.1206
Hash: 886af39
Branch: 886af39
Build date: 2022-12-13 00:02:50 UTC

Build Information
Release ID: 1704020017
Git revision: 7ef5413f2eec3351ce648085f619fc29fd8cb647
Build date: 2022-12-13 00:00:15+00
Build branch: release-17.4
Build lane: release-17.4

Operating System
Mac OS X 13.1.0
Darwin 22.2.0 Darwin Kernel Version 22.2.0
    Fri Nov 11 02:04:44 PST 2022
    root:xnu-8792.61.2~4/RELEASE_ARM64_T8103 arm64

```

</details>

_Copied from original issue xamarin/xamarin-macios#17195_

**Comment by akoeplinger** [comment]
You can install the `dotnet-symbol` global tool: https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-symbol

Then run `dotnet-symbol --symbols /path/to/libcoreclr.dylib` and the tool will download the symbol matching that file.

**Comment by tommcdon** [comment]
Hi @rolfbjarne!  Please let us know if [dotnet-symbols](https://learn.microsoft.com/dotnet/core/diagnostics/dotnet-symbol) does not resolve the issue.

**Comment by rolfbjarne** [comment]
@tipa does `dotnet-symbols` solve your issue?

**Comment by tipa** [comment]
@rolfbjarne  Yes, it helped getting the symbols and symbolicating the crash report - thanks!
Unfortunately, it didn't help finding the source of the crash as I found out that macOS apps aren't AOTed any more which makes stack traces less readable, but I've seen you're working on this for the .NET8 release.

**Comment by janvorli** [comment]
@tipa you can use LLDB and the SOS plugin to get full fidelity stack trace. See https://github.com/dotnet/diagnostics/blob/main/documentation/installing-sos-instructions.md for instructions on how to install it. The you can use the `clrstack` command to dump the managed code stack trace or `clrstack -f` to get stack trace with combined managed / native parts.

**Comment by tipa** [comment]
@janvorli Thanks. This sounds pretty technical and I am not sure if I understand it. I am not too familiar with some of this terminology.
So if I download and install the SOS extension, when running `dotnet publish -c Release` on my macOS project afterwards, there will be additional debugging information embedded in the app package, automatically?
Will I have to use `clrstack` (I don't seem to have it installed right now) to inspect the stack traces/dumps? Or will the stack trace automatically show up in AppCenter?
Does using this extension/plugin have any negative impact on either package size or app performance?

**Comment by hoyosjs** [comment]
@tipa dotnet-sos is a LLDB plugin - so it's a command line debugger extension. You'd need a coredump or attaching to a live process using the LLDB debugger to the app to be able to symbolize the managed frames. These don't bloat the app since they use the dump alongside with data in the process and the PDBs/dSYMs. However, I don't know if that's possible with App Center. What type of diagnostic artifacts do they give you?

**Comment by tipa** [comment]
@hoyosjs I'm afraid AppCenter doesn't provide a crash dump, only  the stack trace and some device info, see below:
[report-2517282598560009999-de3ea8ed-0c50-4b87-aa77-907e5fbff315.zip](https://github.com/dotnet/runtime/files/10446245/report-2517282598560009999-de3ea8ed-0c50-4b87-aa77-907e5fbff315.zip)

I can also get some ".xcrashpoint" reports from XCode if a user decides to upload the crash information. Can I get some information out of those files using SOS/clrstack?

My crash reports shot up significantly after migrating from "old" Xamarin.Mac to new .NET6 for macOS and I can't figure out what the source of it is.
