### ISSUE TITLE
Process.WaitForExit() deadlock when running multiple processes on linux with .net7

### ISSUE THREAD

**Issue by kirnosenko** [dotnet/runtime#80563]
### Description

Running multiple processes concurrently using System.Diagnostics.Process causes a deadlock on linux with .net7. I checked [this](https://github.com/dotnet/runtime/issues/51277), but I believe it is something else.

### Reproduction Steps

A simple example to reproduce deadlock is [here](https://github.com/kirnosenko/processdeadlock).

### Expected behavior

no deadlock

### Actual behavior

deadlock

### Configuration

.net7 on x64 alpine linux container

### Other information

I tested it in different environments:
.net6 + windows = fine
.net6 + linux = fine
.net7 + windows = fine
.net7 + linux = deadlock

**Comment by adamsitnik** [comment]
@tmds is there any chance you could take a look?

**Comment by tmds** [comment]
@kirnosenko you've only observed this issue in a container, right?

You can work around it by changing the entrypoint to something like:
```
ENTRYPOINT ["/bin/sh", "-c", "dotnet <your_assembly>.dll"]
```

https://github.com/dotnet/runtime/pull/79817 will fix this.

**Comment by kirnosenko** [comment]
@tmds yes I run it in container, unfortunately your suggestion makes no any difference, still has a deadlock.

**Comment by tmds** [comment]
> unfortunately your suggestion makes no any difference, still has a deadlock.

Ah, I thought it would be enough to make the .NET process have another pid than `1`, but that's not true.

If you add the `--init` flag to the `docker run` command (which adds an init process as pid 1), the deadlock disappears.

https://github.com/dotnet/runtime/pull/79817 fixes this issue.

**Comment by adamsitnik** [comment]
@tmds thank you for your help!
