### ISSUE TITLE
The app crashes under .NET7 in Docker with "Fatal error. The RW block to unmap was not found"

### ISSUE THREAD

**Issue by SergeiPavlov** [dotnet/runtime#80580]
### Description

When we switch to .NET7 from .NET6 we often see "Fatal error. The RW block to unmap was not found"

There are 2 places in dotnet code with this message:
https://github.com/dotnet/runtime/blob/main/src/coreclr/utilcode/executableallocator.cpp#L280
https://github.com/dotnet/runtime/blob/main/src/coreclr/utilcode/executableallocator.cpp#L845

Under .NET6 never seen such an error.
`DOTNET_EnableWriteXorExecute=0` setting helps to avoid it, but then `OutOfMemory` does appear, even when there is enough free memory for Heap and unmanaged needs.

### Reproduction Steps

.NET7 ASP NET app under Docker-in-Docker environment

### Expected behavior

No crash

### Actual behavior

Stack trace may be various. Example:
```
Fatal error. The RW block to unmap was not found
   at System.Reactive.Concurrency.DefaultScheduler.Schedule[[System.ValueTuple`2[[System.Reactive.Concurrency.LocalScheduler, System.Reactive, Version=5.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263],[System.Reactive.Disposables.SingleAssignmentDisposable, System.Reactive, Version=5.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.ValueTuple`2<System.Reactive.Concurrency.LocalScheduler,System.Reactive.Disposables.SingleAssignmentDisposable>, System.Func`3<System.Reactive.Concurrency.IScheduler,System.ValueTuple`2<System.Reactive.Concurrency.LocalScheduler,System.Reactive.Disposables.SingleAssignmentDisposable>,System.IDisposable>)
   at System.Reactive.Concurrency.DefaultScheduler.Schedule[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.ValueTuple`2<System.__Canon,System.__Canon>, System.TimeSpan, System.Func`3<System.Reactive.Concurrency.IScheduler,System.ValueTuple`2<System.__Canon,System.__Canon>,System.IDisposable>)
   at System.Reactive.Concurrency.LocalScheduler.ScheduleShortTermWork(WorkItem)
   at System.Reactive.Concurrency.LocalScheduler.EvaluateLongTermQueue()
   at System.Reactive.Concurrency.LocalScheduler.SystemClockChanged(System.Object, System.Reactive.PlatformServices.SystemClockChangedEventArgs)
   at System.Reactive.PlatformServices.SystemClock.OnSystemClockChanged(System.Object, System.Reactive.PlatformServices.SystemClockChangedEventArgs)
   at System.Reactive.PlatformServices.PeriodicTimerSystemClockMonitor.TimeChanged()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.TimerQueueTimer.Fire(Boolean)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
[createdump] Problem suspending threads: ptrace(ATTACH, 6) FAILED Operation not permitted (1)
[createdump] Failure took 0ms
```

### Regression?

On .NET6 it does work.

### Known Workarounds

`DOTNET_EnableWriteXorExecute=0` but it induces `OutOfMemory` exception more often

### Configuration
Based on image `mcr.microsoft.com/dotnet/aspnet:7.0.2-bullseye-slim-amd64`
We have limited .NET memory consumption by settings:
Docker-compose's
```
    mem_limit: 39g
    mem_reservation: 36g
```
Env var:
`DOTNET_GCHeapHardLimit: "3C0000000"`

_No response_

**Comment by jkotas** [comment]
cc @janvorli

**Comment by janvorli** [comment]
@SergeiPavlov would you be able to create a simple repro that you could share? We have not seen this issue ever before, so it seems there is something special going on in your case. I am referring to the "Fatal error. The RW block to unmap was not found" issue.

**Comment by SergeiPavlov** [comment]
> @SergeiPavlov would you be able to create a simple repro that you could share? We have not seen this issue ever before, so it seems there is something special going on in your case. I am referring to the "Fatal error. The RW block to unmap was not found" issue.

Unfortunately I cannot reproduce it on simple example. It crashes on huge app unit-testing process at relatively random time.
The first suspicion was "a deficite of RAM", but logging of `GCMemoryInfo` show no signs of memory stress condition: `HeapSizeBytes` & `Process.WorkingSet64` < 8G, while 32GB is reserved and ~16GB is allowed to .NET (DOTNET_GCHeapHardLimit)

**Comment by janvorli** [comment]
@SergeiPavlov ok, in that case, would it be possible to share a core dump at the failure? Or if that would not work for you, try to use a private build of libcoreclr.so with some extra logging that I would add?

**Comment by SergeiPavlov** [comment]
> try to use a private build of libcoreclr.so with some extra logging that I would add?

I'm ready to run tests with your `libcoreclr.so`

**Comment by janvorli** [comment]
Great, let me prepare it then. I will assume that you'll use the mcr.microsoft.com/dotnet/aspnet:7.0.2-bullseye-slim-amd64 image for the testing, as I need to build the libcoreclr.so from a specific state of the source tree that matches what's in the image.

**Comment by janvorli** [comment]
@SergeiPavlov you can get the testing libcoreclr.so here: https://1drv.ms/u/s!AkLV4wRkyHYhymkJZQ-qrTEFcxpI?e=GrlQyt
It is a drop-in replacement for the one in `mcr.microsoft.com/dotnet/aspnet:7.0.2-bullseye-slim-amd64`. You'll need to copy it over the one that's installed there.

Then you'll also need to set these env variables before running your app to enable the logging:
```
COMPlus_StressLogSize=2000000
COMPlus_TotalStressLogSize=1
COMPlus_StressLog=1
COMPlus_LogFacility=80
COMPlus_LogLevel=7
COMPlus_StressLogFilename=/path/to/log/file
```

The `/path/to/log/file` is a path to where the log file will be written. It will have size determined by the `COMPlus_TotalStressLogSize` (in GB). For now, it is set to 1GB, we'll see if that's enough or not.

After the process crashes, I'd need you to gzip the log file (it should compress well) and share it with me. I will then run a `StressLogAnalyzer` tool that's built in the runtime repo to view the events around the executable memory mapping. I have added events that log all mappings, unmappings and reservations. That should show us where we try to unmap something that was not mapped or already unmapped before.

**Comment by SergeiPavlov** [comment]
Thank you. I will try it.

**Comment by SergeiPavlov** [comment]
I have collected the log.
Extended TotalStressLogSize to 22GB.
The error is flaky. I see `Segmentation fault` more often than `The RW block to unmap was not found`.
So I think it is a side effect of memory corruption by some unmanaged or unsfafe code.

https://1drv.ms/u/s!Ajz6TT1A2pxyhClzkispqJBXgmOm?e=VlrIwt

**Comment by janvorli** [comment]
@SergeiPavlov it seems that the log was not produced using the testing `libcoreclr.so` or the `COMPlus_LogFacility=80` was not set. It doesn't contain any of the logging messages I've added. How did you replace the `libcoreclr.so`? If your application is not self contained, then you need to overwrite the `/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.2/libcoreclr.so`. If it is self contained, you'll need to overwrite the `libcoreclr.so` present in the subtree of your application.

**Comment by SergeiPavlov** [comment]
The app is not self contained.
I've check that `libcoreclr.so` is exactly yours:
```
root@vm:/app# docker exec -it 22bbcf3d3b14 /bin/bash
root@22bbcf3d3b14:/app# find /usr -name libcoreclr.so
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.2/libcoreclr.so
root@22bbcf3d3b14:/app# ls -la /usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.2/libcoreclr.so
-rw-r--r-- 1 root root 6983112 Jan 17 01:01 /usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.2/libcoreclr.so
root@22bbcf3d3b14:/app# env | grep COMPlus
COMPlus_LogLevel=7
COMPlus_StressLogFilename=/tmp/stress.log
COMPlus_LogFacility=80
COMPlus_TotalStressLogSize=8
COMPlus_StressLogSize=20000000
COMPlus_StressLog=1
root@22bbcf3d3b14:/app#
```

**Comment by SergeiPavlov** [comment]
For now I stuck on
`error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found`

```
# strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX_3.4
...
GLIBCXX_3.4.28
```

Apparently this `libcoreclr.so` was linked with newer `libstdc++.so.6` version, not available in Debian repo

**Comment by janvorli** [comment]
Ah, I am sorry, let me rebuild it on an older OS. I'll share a new version later today.

**Comment by janvorli** [comment]
@SergeiPavlov Here is a link to a build made on the same distro we use for our official builds - the CentOS 7:
https://1drv.ms/u/s!AkLV4wRkyHYhymppdSsOVuMzTgIL?e=a8Ywi8

**Comment by SergeiPavlov** [comment]
@janvorli https://1drv.ms/u/s!Ajz6TT1A2pxyhCuH-5NyhnPTqwA3?e=l6cnL4

**Comment by janvorli** [comment]
@SergeiPavlov thank you a lot for the log. It has revealed the problem right away. It is something that was already fixed in the main. I've made a mistake when checking the return value of a `mmap` to detect failed mapping. Instead of comparing it to `MAP_FAILED`, I've considered `NULL` to represent mapping error. The MAP_FAILED has a value of `FFFFFFFFFFFFFFFF` and we then try to handle it as if it was a real address. Depending on the timing, we either end up accessing that memory address, thus getting SIGSEGV or just storing it as a cached last mapping and trying to unmap it a bit later which leads to the fatal error.
Your problem happens due to a failure of `mmap` that is supposed to create writeable mapping for a piece of executable code. I guess the issue happens due to out of memory condition, but let me provide you with another updated libcoreclr.so that would dump the `errno` at the failure to make sure it is that one.
I'll share the updated libcoreclr.so in a minute.

**Comment by janvorli** [comment]
@SergeiPavlov here is the new version. I have also made it fail fast when the `MAP_FAILED` is detected at that point, so you should no longer see SIGSEGV coming from this place.
https://1drv.ms/u/s!AkLV4wRkyHYhymuU2RbA3FOQL3Wo?e=qjUVQo

**Comment by SergeiPavlov** [comment]
Wonderful! Thank you @janvorli for help!
Hoping this bugfix will appear in `.NET 7.0.3`.
BTW, mmap's `errno == ENOMEM` may have 3 causes:
* No memory is available.
* The process's maximum number of mappings would have been exceeded.
* The process's RLIMIT_DATA limit would have been exceeded

It would be good to distinguish these causes in error reporting.

I'm running the test to catch the error with the new libcoreclr.so...

**Comment by SergeiPavlov** [comment]
I confirm: there is new error message now: `Fatal error. Failed to create RW mapping for RX memory`
https://1drv.ms/u/s!Ajz6TT1A2pxyhC2MHmxevYeY_0iu?e=GA8xoL

**Comment by janvorli** [comment]
Thank you for the log, I'll take a look on Monday. The excessive number of mappings is strange. Now that we know the reason for the crash, it also explains why you were getting OOM with W^X disabled. I wonder what's causing that number of mappings in your app. Could it be some 3rd party native dependency of your app?

`RLIMIT_AS` being exceeded is yet another reason.

**Comment by SergeiPavlov** [comment]
I have created snapshot of `/proc/<pid>/maps` in the middle of tests and see that ~17000 of ~20000 records tagged as `/memfd:doublemapper (deleted)`:
```
7f8889950000-7f8889980000 rw-s 01f51000 00:01 4096                       /memfd:doublemapper (deleted)
7f8889980000-7f8889981000 r-xs 01f81000 00:01 4096                       /memfd:doublemapper (deleted)
7f8889981000-7f8889982000 rw-s 01f82000 00:01 4096                       /memfd:doublemapper (deleted)
7f8889982000-7f8889983000 r-xs 01f83000 00:01 4096                       /memfd:doublemapper (deleted)
7f8889983000-7f8889984000 rw-s 01f84000 00:01 4096                       /memfd:doublemapper (deleted)
```
looks as a resource leak.

**Comment by janvorli** [comment]
Regarding the number of mappings, can you please check also the case with W^X disabled? I would expect to see similar thing, but with anonymous mappings. The new thing compared to 6.0 is that code heaps for certain stubs are interleaving RW and RX pages. I think that in the old world, kernel would combine consecutive pages with the same protection into one large mapping and account that against the `vm.max_map_count`. 
However, the fact that we have so many mappings for those stub heaps means that really excessive number of these stubs are being created. Without looking at the code in those pages, I cannot tell which stubs are those, but there are three kinds of stubs that use this mechanism. Fixup precodes, stub precodes and call counting stubs. Simply said, the first two are used when managed coder calls to methods that were not jitted / located in precompiled code yet. The last one is used to optimize code dynamically by counting calls to methods to help figure out which ones to optimize.
On x64, the size of all of these stubs is 24 bytes. So e.g. 20000 records you are seeing correspond to 10000 pages of code which means 10000 * 4096 / 24 stubs, which is 1706666 stubs. So it seems really important to find out what's going on.
I would start with disabling the tiered jitting which would get rid of any call counting stubs. That can be done by setting the `COMPlus_TieredCompilation=0`. Then if you'd let your test run upto a similar point like before and check the number of mappings, we should see whether the numbers improved dramatically or only slightly. May I ask you to try to do this?

**Comment by SergeiPavlov** [comment]
Sure
Here are `/proc/self/maps` logs for cases: `DOTNET_EnableWriteXorExecute=0, COMPlus_TieredCompilation=0` and  `DOTNET_EnableWriteXorExecute=0, COMPlus_TieredCompilation=1` taken on 17th minute of testing process.
with filtered-out our assembly names.
https://1drv.ms/u/s!Ajz6TT1A2pxyhC4o8durNbLWKmtP?e=i5DDiy

The testing app uses ~1000 assemblies.  I see the testing process loads them on-demand, and number of mappings grows gradually.

In `COMPlus_TieredCompilation=0` case final number of mappings is 63K and the process complets successfully.
In default `COMPlus_TieredCompilation=1` case number of mappings is greater than 65K limit.

So we have average ~64 mappings per assembly, and obvious solution is to increase `vm.max_map_count` system limit.

**Comment by janvorli** [comment]
@SergeiPavlov thank you for the maps and for the .NET 6 details too. The growth might be just due to what I've mentioned before, the interleaving of the RW / RX pages. I'll investigate the maps to see if majority of the mappings can be attributed to these interleaved stub heaps. If that is the case, 64 mappings per assembly would mean around 5000 methods jitted per assembly (64 / 2 * 4096 / 24 - there are two mappings for one code page of the stub heap and each stub code is 24 bytes long). That sounds like a lot unless the assemblies use a lot of runtime generated code like LINQ or reflection emit or they are really huge.

**Comment by SergeiPavlov** [comment]
Tested on Windows:
```

**Comment by SergeiPavlov** [comment]
@janvorli 
Finally we discovered the root cause of mapping leak. There were thousands for dynamically created assemblies. Can be reproduced by code like this:
```
for (int i = 0; i < 100_000; i++) {
    var moduleBuilder = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("DynAssembly"), AssemblyBuilderAccess.Run).DefineDynamicModule("DynModule");
    var typeBuilder = moduleBuilder.DefineType($"DynBar", TypeAttributes.Public);
    typeBuilder.CreateType();
}
```

So we can close this issue.

**Comment by janvorli** [comment]
@SergeiPavlov thank you for the details, now it makes sense.
