### ISSUE TITLE
The documentation for using your build is out of date

### ISSUE THREAD

**Issue by OdeToCode** [dotnet/runtime#806]
The documents available to describe how to use a fresh build are outdated and still target a 3.0 preview. Specifically [Using Your Build](https://github.com/dotnet/runtime/blob/master/docs/workflow/testing/UsingYourBuild.md) and [Using Your Runtime Build with dotnet cli](https://github.com/dotnet/runtime/blob/master/docs/workflow/UsingDotNetCli.md).

**Comment by dhusemann** [comment]
Think some of the links will have to wait for CLI to finish its move to the SDK repo. ??

**Comment by jashook** [comment]
We have done a fair amount of documentation work since this issue was opened. If there are still problems please open a new issue.
