### ISSUE TITLE
Nested StreamWriter disposure

### ISSUE THREAD

**Issue by theCuriousOne** [dotnet/runtime#80606]
### Description

When StreamWriter is used as an input stream for GzipStream, and both are wrapped in a using statement then the disposing of the StreamWriter throws an Exception. I believe this happens because GzipStream disposes of the StreamWriter which was used to create it, and when the 'using' tries to expose the StreamWriter again it crashes because it has already been dispose.

### Reproduction Steps

```
using System.Xml;
using System.IO.Compression;

namespace GzipStreamDemo
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var sitemap = new XmlDocument();
            var xmlDeclaration = sitemap.CreateXmlDeclaration("1.0", "UTF-8", null);
            var root = sitemap.CreateElement("some_element");
            sitemap.AppendChild(root);
            sitemap.InsertBefore(xmlDeclaration, root);

            var filename = Path.ChangeExtension($"doc_name", ".xml.gz");
            try
            {
                //We shouldn't use the recomended using on the next line
                var streamwriter = new StreamWriter(Path.Combine("./", Path.ChangeExtension(filename, ".xml.gz")));
                using var gzipstream = new GZipStream(streamwriter.BaseStream, CompressionMode.Compress);
                sitemap.Save(gzipstream);
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
            Console.WriteLine("App finished");
        }
    }
}

```
### Expected behavior

I would expect either the inner dispose to be more fault tolerant, i.e. don't throw an exception if the stream is already exposed (I think this would be harder to achieve)  or at least mention it somewhere in the documentation (maybe I have missed it)

### Actual behavior

According to the [documentaion](https://learn.microsoft.com/en-us/dotnet/api/system.io.streamwriter?view=net-6.0#remarks) StreamWriter is recommended to be wrapped in using like:
using var streamwriter = new StreamWriter(Path.Combine("./", Path.ChangeExtension(filename, ".xml.gz")));
using var gzipstream = new GZipStream(streamwriter.BaseStream, CompressionMode.Compress);

But this causes an issue. 

### Known Workarounds

don't use the 'using' keyword twice

### Configuration

.NET 6 (but I suspect it might show on other versions as well)

**Comment by Tornhoof** [comment]
Why do you use StreamWriter for byte output? In the documentation link you provided it is stated it is for char output and not for byte output. What you are effectively doing is passing in the backing stream of the writer and let it be closed by your gzipstream.

Instead you should be using a Filestream.
```csharp
using var fileStream = File.OpenWrite(Path.Combine("./", Path.ChangeExtension(filename, ".xml.gz")));
using var gzipstream = new GZipStream(fileStream, CompressionMode.Compress);
sitemap.Save(gzipstream);
```

**Comment by stephentoub** [comment]
> When StreamWriter is used as an input stream for GzipStream, and both are wrapped in a using statement then the disposing of the StreamWriter throws an Exception.

To @Tornhoof's point, this is not what your repro shows. Your example is passing streamWriter.BaseStream, not streamWriter, to the GZipStream. You're basically erroneously disposing of resources owned by the StreamWriter out from under it while it's still using them, and the resulting behavior is expected.

**Comment by theCuriousOne** [comment]
Thank you @Tornhoof and @stephentoub for the clarifications. It was my mistake.
