### ISSUE TITLE
Interop Source Generator TFM check is very expensive

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#80621]
### Description

A customer VS slowdown has been traced back to the TFM check we do in the interop source generators. In particular, the `compilation.GetSpecialType(SpecialType.System_Object)` call is showing up as very expensive to do on every keystroke. There's [a bug open in Roslyn](https://github.com/dotnet/roslyn/issues/66410) for why code that call utilizes is so slow (from the same trace) as it shouldn't be this slow and there's some suspect algorithms, but we should consider changing how we do the TFM check to something cheaper, especially since the TFM check is only used in this repo as none of the interop source generators support downlevel usage and ship with the TFM.

### Configuration

Windows x64

### Regression?

The underlying issue in Roslyn looks to be a regression, but this is not a regression in the source-generator.

### Data
![MicrosoftTeams-image](https://user-images.githubusercontent.com/1571408/212394886-b030d783-cecb-4582-877d-bb8b351283ee.png)

### Analysis

The call to `compilation.GetSpecialType(SpecialType.System_Object)` in the `CreateStubEnvironment` method.

**Comment by jaredpar** [comment]
> but we should consider changing how we do the TFM check to something cheaper, especially since the TFM check is only used in this repo as none of the interop source generators support downlevel usage and ship with the TFM.

The compiler layer should not be attempting to infer target frameworks. At the compiler layer there is simply no such concept. Attempts to reverse engineer it can go wrong. 

If analyzer / generator needs target framework instead it should be fed through analyzer options.
