### ISSUE TITLE
JIT: Assertion failed '!"Missing flags on tree"' during 'Assertion prop' for recently added RuntimeHelpers.CreateSpan uses

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#80632]
libraries-jitstress jobs are failing with this assert, e.g. https://dev.azure.com/dnceng-public/public/_build/results?buildId=136796&view=ms.vss-test-web.build-test-results-tab&runId=2975122&resultId=191688&paneView=debug.

From bisection I think it is not exposed by a JIT change and we are hitting it now after #79461 (I bisected with an SPMI context, and even old JITs hit the assert).

Attached a win-x64 SPMI context that hits it on recent JIT commits (e.g. 3f5210dca709def1e1253916e4244c82b2177e9c).

[fail-39322.zip](https://github.com/dotnet/runtime/files/10415750/fail-39322.zip)

**Comment by SingleAccretion** [comment]
Probably #80622 will fix this by virtue of using a non-`CONST` handle for this data.

**Comment by jakobbotsch** [comment]
@EgorBo Can you double check with the attached SPMI context?

**Comment by EgorBo** [comment]
Just checked, the assert is gone with the patch. @jakobbotsch thanks for the SPMI context it saved an hour or two🙂
