### ISSUE TITLE
zsh comes up on macOS even though System.Diagnostics.ProcessStartInfo.CreateNoWindow is specified as true.

### ISSUE THREAD

**Issue by tatsuya-midorikawa** [dotnet/runtime#80649]
### Description

A window is created when `zsh` is started with `System.Diagnostics.Process.Start`, even though `System.Diagnostics.ProcessStartInfo.CreateNoWindow` is set to true.

### Reproduction Steps

The following code can be easily checked:
```fsharp
open System.Diagnostics
open System.Text

[<Literal>]
let private zsh' = "/System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal"

let exec () =
  use p = 
    ProcessStartInfo (zsh',
      UseShellExecute = false,
      RedirectStandardInput = true,
      RedirectStandardOutput = true,
      CreateNoWindow = true)
    |> System.Diagnostics.Process.Start

  let stdout = StringBuilder()    
  p.OutputDataReceived.Add (fun e -> if e.Data <> null then stdout.AppendLine(e.Data) |> ignore)
  p.BeginOutputReadLine()
  p.StandardInput.WriteLine "ls ./"
  p.StandardInput.WriteLine "exit"
  p.WaitForExit()
  stdout.ToString()
```
It is reproduced for both net6.0 and net7.0.

### Expected behavior

It is expected that no zsh window will be generated.

### Actual behavior

A zsh window shows.

### Regression?

No idea.

### Known Workarounds

Nothing.

### Configuration

- Which version of .NET is the code running on?
→ net6.0 / net7.0
- What OS and version, and what distro if applicable?
→ macOS Venture 13.1
- What is the architecture (x64, x86, ARM, ARM64)?
→ ARM64

**Comment by adamsitnik** [comment]
Hi @tatsuya-midorikawa 

Unfortunately there is no way for us to implement `CreateNoWindow` on Unix, so it's just ignored. Since it's already mentioned in the [docs](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.createnowindow?view=net-7.0#remarks):

> .NET Core does not support creating windows directly on Unix-like platforms, including macOS and Linux. This property is ignored on such platforms.

I am going to close the issue.
