### ISSUE TITLE
Alpine 3.17 images causes SSL Error "unsafe legacy renegotiation disabled"

### ISSUE THREAD

**Issue by dstj** [dotnet/runtime#80641]
After upgrading the `dotnet/runtime` and `dotnet/sdk` Docker images I'm using to the latest `6.0-alpine` (_i.e._ upgrading from `6.0-alpine3.16` to `6.0-alpine3.17`), I get the following SSL "unsafe legacy renegotiation disabled" error when trying to reach an endpoint that only accepts TLSv1.2 (I know this because disabling TLSv1.2 in Postman results in an error and disabling everything but TLSv1.2 succeeds)

```
"Exception": "System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:0A000152:SSL routines::unsafe legacy renegotiation disabled
```

My C# code only defines `ServicePointManager.SecurityProtocol = SecurityProtocolType.SystemDefault;` for SSL/TLS protocols, nothing else, and it works great with the Alpine 3.16 image. 

I read in the [changelog](https://alpinelinux.org/posts/Alpine-3.17.0-released.html) that Alpine 3.17 now uses OpenSSL 3.0, so I'm guessing that has something to do with it...

**Dockerfile**

My `Dockerfile` looks like this:

```
FROM mcr.microsoft.com/dotnet/runtime:6.0-alpine AS base-runtime
RUN apk update \
&& apk add gcompat curl icu-libs \
&& apk add libgdiplus --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ \
&& apk add msttcorefonts-installer fontconfig --no-cache \
&& update-ms-fonts \
&& fc-cache -f
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
RUN adduser -D svcuser

FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build-dotnet-0
WORKDIR /app
COPY myapp.csproj
RUN dotnet restore --runtime linux-musl-x64 --packages .nuget myapp.csproj

FROM build-dotnet-0 AS build-dotnet
ARG VERSION
COPY --from=build-dotnet-0 /app/.nuget /app/.nuget
WORKDIR /app
COPY . ./
RUN dotnet publish ./myapp.csproj --packages .nuget --configuration Release --runtime linux-musl-x64 --self-contained=true -p:UseAppHost=true -p:IsDockerBuild=true -p:PublishReadyToRun=true -p:PublishReadyToRunShowWarnings=true -p:Version=${VERSION} --output /app/publish

FROM base-runtime AS final
WORKDIR /app
COPY --from=build-dotnet --chown=svcuser /app/publish .
USER svcuser
```

**Comment by dstj** [comment]
Woops, this should have gone in the [dotnet/docker github](https://github.com/dotnet/dotnet-docker)  My bad. :/

**Comment by dstj** [comment]
Reposted as https://github.com/dotnet/dotnet-docker/issues/4332

**Comment by wfurt** [comment]
What site are you connecting to @dstj and is it asking for client certificates? In general, OpenSSL has some more strict security expectations. 

https://github.com/dotnet/runtime/pull/64531 may be relevant to you e.g. try it with 7.0.

**Comment by dstj** [comment]
Thanks @wfurt
(You replied in the dotnet/runtime github, not the dotnet/docker. Is it a runtime issue??)

Same problem happened on at least two APIs: a Cisco API (api.cisco.com) and the other was Autotask PSA API (webservices16.autotask.net).

> is it asking for client certificates?
In all honesty, I do not know ;) I only make calls with a standard `HttpClient`. Nothing fancy. Locally, from Windows, it works. Locally, from Docker Alpine 3.17, it doesn't. Locally, from Docker Alpine 3.16, it works.

Thanks for the link. I had searched for "unsafe legacy renegotiation disabled"  but it's not in the mentioned link so I hadn't found it. That does appear to be my issue.

**Comment by wfurt** [comment]
Well, I don't see how we would fix this via docker image. OpenSSL 3 brings changes but I cannot see us using the compat 1.1 as default.  As fas I can see there is really nothing wrong with the image that could be fixed via docker changes. 

You can also use 'openssl s_client` and you can try to connect the failing site to get more insight. 
And try the 7.0 images. There were more changes but the links would be my suspect.

**Comment by dstj** [comment]
@wfurt 

Ok, after like 4 hours, I finally managed to upgrade all my project to .NET 7 and EF Core 7... same exact OpenSSL error :(

As for `openssl s_client`, that command is new to me, but from my WSL Ubuntu running OpenSSL 1.1

```
$ openssl s_client -connect api.cisco.com:443

CONNECTED(00000003)
depth=2 C = US, O = IdenTrust, CN = IdenTrust Commercial Root CA 1
verify return:1
depth=1 C = US, O = IdenTrust, OU = HydrantID Trusted Certificate Service, CN = HydrantID Server CA O1
verify return:1
depth=0 CN = api.cisco.com, O = Cisco Systems Inc., L = San Jose, ST = California, C = US
verify return:1
---
Certificate chain
 0 s:CN = api.cisco.com, O = Cisco Systems Inc., L = San Jose, ST = California, C = US
   i:C = US, O = IdenTrust, OU = HydrantID Trusted Certificate Service, CN = HydrantID Server CA O1
 1 s:C = US, O = IdenTrust, OU = HydrantID Trusted Certificate Service, CN = HydrantID Server CA O1
   i:C = US, O = IdenTrust, CN = IdenTrust Commercial Root CA 1
 2 s:C = US, O = IdenTrust, CN = IdenTrust Commercial Root CA 1
   i:C = US, O = IdenTrust, CN = IdenTrust Commercial Root CA 1
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIICT... truncated ... DBuf
-----END CERTIFICATE-----
subject=CN = api.cisco.com, O = Cisco Systems Inc., L = San Jose, ST = California, C = US

issuer=C = US, O = IdenTrust, OU = HydrantID Trusted Certificate Service, CN = HydrantID Server CA O1

---
No client certificate CA names sent
---
SSL handshake has read 5345 bytes and written 623 bytes
Verification: OK
---
New, TLSv1.2, Cipher is AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : AES128-GCM-SHA256
    Session-ID: 998B9973CD9E608784A1D7DB3D9E3E961A4D23313D8DB4CCC2F20FC0EB7C53CA
    Session-ID-ctx:
    Master-Key: 03B962C30E08EE62ACBAD4D5F8560AE6C7F09DDF4A5CED53AC8DF2B67ADAAB251ACCF2B4A4FA8B801FE0D01AE863783E
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1673745807
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---

**Comment by rzikm** [comment]
> My C# code only defines ServicePointManager.SecurityProtocol = SecurityProtocolType.SystemDefault; for SSL/TLS protocols, nothing else, and it works great with the Alpine 3.16 image.

Just a side note, the `ServicePointManager` class does not affect SslStream/HttpClient anymore, it affects only legacy APIs like WebRequest. To change SSL/TLS settings used by `HttpClient`, you need to configure the `SslOptions` property on the underlying `SocketsHttpHandler`.

**Comment by mthalman** [comment]
> So it turns out it was more of a [`dotnet-docker`](https://github.com/dotnet/dotnet-docker) "issue." Or, at least, a migration action that should have been mentioned in a changelog.

I've updated the announcement at https://github.com/dotnet/dotnet-docker/discussions/4313 to call out the OpenSSL version change.

**Comment by wfurt** [comment]
I agree with @rzikm that we should not update the openssl.conf by default. The site does get "B" grade in https://www.ssllabs.com/ssltest/analyze.html?d=api.cisco.com as it does not support secure renegotiation. (and supports weak ciphers)
