### ISSUE TITLE
[API Proposal]: Add Random.GetItem(IReadOnlyList<T> choices)

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#80651]
### Background and motivation

As a convenience method to pick a random item from a list. As an example, where this pattern is used:

- [PowerOfTwoChoicesLoadBalancingPolicy](
https://github.com/microsoft/reverse-proxy/blob/b5192aacd311ae6072b78d7d1261ff59b872f2d3/src/ReverseProxy/LoadBalancing/PowerOfTwoChoicesLoadBalancingPolicy.cs#L33-L35)
- [RandomLoadBalancingPolicy](https://github.com/microsoft/reverse-proxy/blob/b5192aacd311ae6072b78d7d1261ff59b872f2d3/src/ReverseProxy/LoadBalancing/RandomLoadBalancingPolicy.cs)

We also just added [Random.GetItems](https://github.com/dotnet/runtime/pull/78598), so this would be a convenience method 
 `GetItem` that delegates the work to `GetItems`.
 
### API Proposal

```csharp
namespace System.Collections.Generic;

public class Random
{
    public T GetItem<T>(ReadOnlySpan<T> choices);
    public T GetItem<T>(IReadOnlyList<T> choices);
}
```

### API Usage

```csharp
string[] questions = GetQuestions();

var randomQuestion = Random.Shared.GetItem(questions);

Console.WriteLine(randomQuestion);
```

### Alternative Designs

Use Random.GetItems(choices, 1)?

```csharp
string[] questions = GetQuestions();

var randomQuestion = Random.Shared.GetItems(questions, 1)[0];

Console.WriteLine(randomQuestion);
```

### Risks

None

**Comment by N0D4N** [comment]
How about overload where consumer would be able to provide default value?
So it would follow the same pattern with LINQ's [FirstOrDefault](https://github.com/dotnet/runtime/blob/67743295d05777ce3701135afbbdb473d4fb4436/src/libraries/System.Linq/src/System/Linq/First.cs#L42) and `Nullable<T>` [GetValueOrDefault](https://github.com/dotnet/runtime/blob/67743295d05777ce3701135afbbdb473d4fb4436/src/libraries/System.Private.CoreLib/src/System/Nullable.cs#L54)

Something like this, not sure about best order of parameters `devaultValue` and `random`.
```cs
public TSource PickRandomlyOrDefault<TSource>(this IReadOnlyList<TSource> source, TSource defaultValue);
public TSource PickRandomlyOrDefault<TSource>(this IReadOnlyList<TSource> source, TSource defaultValue, Random random);
public TSource PickRandomlyOrDefault<TSource>(this ReadOnlySpan<TSource> source, TSource defaultValue);
public TSource PickRandomlyOrDefault<TSource>(this ReadOnlySpan<TSource> source, TSource defaultValue Random random);
```
Or it could potentially confuse consumers if source is `IReadOnlyList<Random>`?

**Comment by davidfowl** [comment]
I almost copied that but figured I'd see what people thought.

**Comment by svick** [comment]
I'm wondering whether this should really be an extension method on the collection, or whether this would be better as an another method on `Random`:

```c#
namespace System;

public class Random
{
    // Throws if source is empty
    public TSource Pick<TSource>(IReadOnlyList<TSource> source);
    public TSource Pick<TSource>(ReadOnlySpan<TSource> source);

    // Returns default if source is empty
    public TSource? PickOrDefault<TSource>(IReadOnlyList<TSource> source);
    public TSource? PickOrDefault<TSource>(ReadOnlySpan<TSource> source);
}
```

It does require you to get an instance of `Random`, but I don't see that as a bad thing, as I think it highlights the non-deterministic nature of the method better than a name and it's also consistent with existing ways to get random values.

Also, if the extension method approach is chosen, it should use optional parameters to simplify the API surface:

```c#
namespace System.Collections.Generic;

public static class RandomExtensions
{
    // Throws if source is empty
    public TSource PickRandomly<TSource>(this IReadOnlyList<TSource> source, Random? random = null);
    public TSource PickRandomly<TSource>(this ReadOnlySpan<TSource> source, Random? random = null);

    // Returns default if source is empty
    public TSource? PickRandomlyOrDefault<TSource>(this IReadOnlyList<TSource> source, Random? random = null);
    public TSource? PickRandomlyOrDefault<TSource>(this ReadOnlySpan<TSource> source, Random? random = null);
}
```

**Comment by mattzink** [comment]
Do we really need a shortcut for `source[Random.Shared.Next(source.Count)]` ?

**Comment by eiriktsarpalis** [comment]
I'm guessing the overloads not accepting `Random` default to `Random.Shared`? I tend to agree with @svick that this should be an instance/extension method on `Random` to make this more explicit. Picking should be the responsibility of the `Random` class and not be an extension method acting on collections.

**Comment by stephentoub** [comment]
> Picking should be the responsibility of the Random class and not be an extension method acting on collections.

I agree. _If_ we were to add such a method, given we just added a GetItems method that takes the choices and a count, I expect this would just be a GetItem method that just takes the choices. (I'm not convinced we should add these at all, given the one-liner, just adding what I think we should do if we add it. Also, if there's a need for non-span-defined choices, we should consider such overloads for GetItems, or if there's not, consider the type used for choices here.)

**Comment by davidfowl** [comment]
>  If we were to add such a method, given we just added a GetItems method that takes the choices and a count, I expect this would just be a GetItem method that just takes the choices.

Updated the API and made it nullable since we're not keen on adding the overloads.

> Also, if there's a need for non-span-defined choices, we should consider such overloads for GetItems, or if there's not, consider the type used for choices here.

I think we should add it to both.

**Comment by bartonjs** [comment]
Given that the proposed method is just `choices[random.Next(choices.Length)]`, plus the additional overhead of checking for `choices.Length == 0`, we aren't sure that the method has positive value.

If there were a strong/compelling use case, we might feel differently.

```C#
namespace System.Collections.Generic;

public partial class Random
{
    public T GetItem<T>(ReadOnlySpan<T> choices);
    public T GetItem<T>(IReadOnlyList<T> choices);
}
```
