### ISSUE TITLE
The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception

### ISSUE THREAD

**Issue by jsurana** [dotnet/runtime#80672]
Hi Team,

I have ASP.Net 4.7.2 window service which is processing NServiceBus messages. Currently it is deployed to On-Premise server. It has retry mechanism as well and working fine. Now I am going to containerizing it. While running into docker window container, it is doing same SQL operation using Entity framework Core and giving exception as mentioned below

The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception.: TypeInitializationException

Please find below screenshot for more details:

![image](https://user-images.githubusercontent.com/31936315/212561334-ddc5bb6b-faba-4383-904b-ad231440fa57.png)

I have below Nuget packages references:
Microsoft.data.sqlclient - 1.1.3
Microsoft.data.sqlclient.SNI - 1.1.1
Microsoft.EntityFrameworkCore.SqlServer - 3.1.21
NServiceBus.SqlServer - 4.1.2
System.Data.SqlClient - 4.7.0

I have checked and can see SNI.dll in both x86 and x64 in window container still getting this error.

I have read a lot of articles but did not get the fix. Can anyone help me to fix this?

**Comment by teo-tsirpanis** [comment]
Maybe is it a conflict between `System.Data.SqlClient` and `Microsoft.Data.SqlClient`? You should prefer the latter.

**Comment by jsurana** [comment]
> Maybe is it a conflict between `System.Data.SqlClient` and `Microsoft.Data.SqlClient`? You should prefer the latter.

@teo-tsirpanis I tried to uninstall System.Data.SqlClient but one another Nuget from my private Nuget feed depands on it. And NServiceBus.SqlServer.4.12 also depand on it so not able to uninstall

**Comment by Wraith2** [comment]
This is usually cause by one of two scenarios:
1) you're using a docker container which doesn't contain ICU libraries, see [my blog](https://blog.wraithware.org/2020/05/23/SqlClient-and-Globalization-Invariant-mode.html) for how to fix that.
2) you're trying to use windows compiled libraries on unix. You must compile specifically for a unix RID to have nuget restore the unix specific native dependencies.

**Comment by jsurana** [comment]
> This is usually cause by one of two scenarios:
> 
> 1. you're using a docker container which doesn't contain ICU libraries, see [my blog](https://blog.wraithware.org/2020/05/23/SqlClient-and-Globalization-Invariant-mode.html) for how to fix that.
> 2. you're trying to use windows compiled libraries on unix. You must compile specifically for a unix RID to have nuget restore the unix specific native dependencies.

@Wraith2 
Blog is more related to Linux and I am using windows container having ASP.Net framework 4.7.2 based application. Can you help me to validate and install in windows?
I am not using windows compiled libraries on Unix

**Comment by Wraith2** [comment]
Very unusual. Can you provide a minimal reproduction? This isn't a configuration I've seen in the past so I'm not sure what the causes might be, I'll need to debug it.

**Comment by jsurana** [comment]
@Wraith2  It might be something specific to my application. Can we please connect as giving Reproduction steps is little difficult for me and time taking also

**Comment by jsurana** [comment]
I am able to resolve the issue. I upgraded version of Microsoft.Data.SqlClient.SNI from 1.1.0 to 1.1.1. Thank you
