### ISSUE TITLE
Exception occurs during string interpolation

### ISSUE THREAD

**Issue by 9edc4e7c** [dotnet/runtime#80685]
### Description

try to execute following code
after execution c = "Object reference not set to an instance of an object."

try
{
    long a = 10;
    string b = $"test {a}.";
}
catch (Exception ex)
{
    string c = ex.Message;
}

### Configuration

dotnet 7.0.2
MacOS
x64

### Regression?

bug not reproduced on dotnet 6.0

### Other information

the bug not reproduced if specify a.ToString() in string interpolation

try
{
    long a = 10;
    string b = $"test {a.ToString()}.";
}
catch (Exception ex)
{
    string c = ex.Message;
}

**Comment by EgorBo** [comment]
@9edc4e7c can you share a complete repro? I cannot reproduce the problem with the just the snippet provided on macOS-x64 with 7.0.2

**Comment by EgorBo** [comment]
@9edc4e7c "debug" as in via IDE debug (VS for mac?) or `dotnet run -c Debug` (or just `dotnet run`) ?

**Comment by 9edc4e7c** [comment]
yes VSCode + Omnisharp

**Comment by stephentoub** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/78991

**Comment by tommcdon** [comment]
@hoyosjs
