### ISSUE TITLE
SemaphoreSlim.WaitAsync has very high contention cost in concurrent scenarios

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#8070]
As @CyrusNajmabadi reports in https://github.com/Microsoft/vs-threading/issues/109, `SemaphoreSlim.WaitAsync` is observed in an ETL trace to cost a great deal of CPU time due to lock contention. This is very unfortunate, especially since being an async method, we'd rather simply resume later if a lock isn't immediately available.

![image](https://cloud.githubusercontent.com/assets/3548/25977671/e2f35d2c-3671-11e7-96ae-1d0cc4fa8b01.png)

**Comment by stephentoub** [comment]
Since https://github.com/microsoft/vs-threading/issues/109 was closed as not having any complaints in years, I'm also going to close this.  Please re-open if there's still an observed problem here.  Thanks.
