### ISSUE TITLE
Regression: "The path must be absolute." on Debian Linux

### ISSUE THREAD

**Issue by kurtnelle** [dotnet/runtime#80710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Seems to be a regression of a long-standing issue: The fact that Linux does not have drive letters!!!!
https://github.com/dotnet/aspnetcore/issues/38175
 "Path.IsPathRooted" only works on Windows!
```c#
public PhysicalFileProvider(string root, ExclusionFilters filters)
        {
            if (!Path.IsPathRooted(root))
            {
                throw new ArgumentException("The path must be absolute.", nameof(root));
            }

            string fullRoot = Path.GetFullPath(root);
            // When we do matches in GetFullPath, we want to only match full directory names.
            Root = PathUtils.EnsureTrailingSlash(fullRoot);
            if (!Directory.Exists(Root))
            {
                throw new DirectoryNotFoundException(Root);
            }

            _filters = filters;
            _fileWatcherFactory = () => CreateFileWatcher();
        }
```
### Expected Behavior

On linux, it should ignore the fact that there is no drive letter.

**Comment by Jozkee** [comment]
>"Path.IsPathRooted" only works on Windows!

This isn't true. I just tested it on WSL Ubuntu.

@kurtnelle could you please verify if your issue is because you are on the same situation as https://github.com/dotnet/aspnetcore/issues/38175#issuecomment-991282119; otherwise, can you please elaborate why you think `Path.IsPathRooted` only works on Windows?

I will close this issue for now as is not actionable.

**Comment by kurtnelle** [comment]
After looking at the code in Github, I noticed that there is a Path.Windows.cs and a Path.Unix.cs
After getting the error in my application I looked into the source linked code to determine which version of those two files were being used in my application. It seems that it was the Path.Windows.cs that was being used. Try as I may I could not get the version with Path.Unix to appear in my application. This leads me to believe that all of the .net frameworks from 5.0 and up are using the wrong file for Unix based operating systems; but it's too much code for me to traverse through to figure out how the compilation works (I'll be at it for months).

**Comment by Jozkee** [comment]
> This leads me to believe that all of the .net frameworks from 5.0 and up are using the wrong file for Unix based operating systems

I don't think that's the case. I can see we build `Path.Windows.cs` on Windows only and `Path.Unix.cs` for Unix and a few other platforms.
https://github.com/dotnet/runtime/blob/7392fb7c4617ee831d160f0c61aaf43038a6aba8/src/libraries/System.Private.CoreLib/src/System.Private.CoreLib.Shared.projitems#L1991

If you want to get more familiar with how the whole .NET repo compiles, I encourage you to take a look at https://github.com/dotnet/runtime/blob/main/docs/workflow/README.md#getting-yourself-started.

In addition, I suggest you fiddle with a console application where you can demonstrate the behavior that you describe.

**Comment by kurtnelle** [comment]
If I make a project on Windows and compile it when it runs on Linux will it use the correct version of Path when running on Linux as opposed to Windows?
