### ISSUE TITLE
Bump ICU to version 72

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#80721]

**Comment by steveisok** [comment]
@directhex this doesn't have to be right away.  Sometime between now and the middle of Feb would be ok.

**Comment by directhex** [comment]
@steveisok to confirm, we fork from microsoft/icu.git and that repo is not on 72 (master branch is on 68, as is our fork). So I should sidestep the Microsoft repo & pull in ICU 72 direct from upstream?

**Comment by directhex** [comment]
Microsoft repo status at https://github.com/microsoft/icu/issues/120

**Comment by steveisok** [comment]
I think we should sidestep for now and align if/when they update.
