### ISSUE TITLE
[mono][perf] WASM disk size regression on 04 Jan 2023

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#80737]
### Description

Disk size (SOD) regression detected in Mono Blazorwasm. 

#### Details - Mono

Date | Diff | Size increase (bytes) | Size increase (%)
--|--|--|--
04 Jan 2023 | https://github.com/dotnet/runtime/compare/2975fa4ca577b46d651f9380fda8cc3b39f1550b...a2243718922e85370f137bdfa3e30a8eedebe954 |   65376 |	3.03

![Screenshot 2023-01-17 at 15 23 41](https://user-images.githubusercontent.com/11523312/212923937-4aa024ae-69b4-4cd1-9dba-3c13c9a6530c.png)

<hr>

#### Details - Mono AOT

Date | Diff | Size increase (bytes) | Size increase (%)
-|--|--|--
04 Jan 2023 | https://github.com/dotnet/runtime/compare/2975fa4ca577b46d651f9380fda8cc3b39f1550b...a2243718922e85370f137bdfa3e30a8eedebe954 |    459520  |	10.93

![Screenshot 2023-01-17 at 15 23 50](https://user-images.githubusercontent.com/11523312/212923962-ac312bc8-dc81-4a15-b416-40707d440317.png)

### Configuration

OS: Ubuntu 18.04
Architecture: x64
.NET version: 7.0.100-rc.1.22431.12

**Comment by radekdoulik** [comment]
this is probably result of net7 to net8 fix
