### ISSUE TITLE
ThreadPool consumes about 10 or up to 20 percent CPU when application is completely idle

### ISSUE THREAD

**Issue by linkaiyu** [dotnet/runtime#80746]
### Description

When a desktop application is completely idle, we observed about 5-10 % or sometimes up to 20% of CPU consumption (on windows machines) 

This is a problem for a financial company that distributes a .NET MAUI application to their users extensively. Their concern is that with the consumption of CPU when app is idle, they could be accused of data mining.

### Analysis

Looking at the .net source code, the threadpool is in the wait state but is looping and calculating and checking for wait period.

[runtime/LowLevelLifoSemaphore.cs at main · dotnet/runtime (github.com)](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Threading/LowLevelLifoSemaphore.cs)

@mikeparker104

**Comment by filipnavara** [comment]
The code in LowLevelLifoSemaphore may spin only for a few cycles. As seen in your profile the bulk of the time is spent in the "kernelbase!..." method below which is the actual Wait code which suspends the threads and doesn't consume any CPU cycles.

**Comment by linkaiyu** [comment]
@filipnavara , yes you are right that the code takes a few cycles as it waits for kernelbase. My analysis is a quick first stab as the issue. Not sure why the a few cycles takes up to 10 or up to 29% CPU. Here is what the Task Manager shows:
![image](https://user-images.githubusercontent.com/11820595/212975813-29c0e28a-1932-4305-ad3f-ccc272a70ca6.png)

**Comment by linkaiyu** [comment]
correction, it sometimes spike up to 20% CPU

**Comment by mangod9** [comment]
@kouvel @eduardo-vp as fyi. We will look into improving this in 8. Thx.

**Comment by AloisKraus** [comment]
@linkaiyu: Can you expand the full stack down to the deepest level? SpinWait calls Sleep at some point in time which is known to be intercepted by some AV solutions which can produce much higher CPU consumption than normally anticipated. 
See https://aloiskraus.wordpress.com/2022/12/11/war-story-how-antivirus-solutions-can-bring-a-server-down/ how such an issue can look like.

**Comment by linkaiyu** [comment]
Hi @AloisKraus , that is the deepest I can expand. I will share the perfview capture file with you in email

**Comment by linkaiyu** [comment]
@AloisKraus what is your MSFT alias?

**Comment by kouvel** [comment]
@linkaiyu, could you please share the trace with me too, at kouvel@microsoft.com?

**Comment by AloisKraus** [comment]
@linkaiyu: I am no MS employee. 
You need to remove all grouping patterns in this box:
![image](https://user-images.githubusercontent.com/101576413/213376744-feb4ee4d-0002-45fa-a131-f536a3c5e1a5.png)
then you can expand deeper and show potentially different modules in the kernel at play.

**Comment by linkaiyu** [comment]
Thanks everybody for jumping into this issue. After experimenting with the app I found that the app code is calling perfmon traces that has a background thread working. after commenting out all the perfmon related code, the CPU consumption goes down to less than 1% intermittently, which I assume is due to the occasional spinning of the threadpool.

**Comment by kouvel** [comment]
@linkaiyu, can this issue be closed now?

**Comment by linkaiyu** [comment]
Yes please
