### ISSUE TITLE
`IListProvider<T>.ToList()` implementations use `list.Add(element)` instead of direct array initialization.

### ISSUE THREAD

**Issue by neon-sunset** [dotnet/runtime#80760]
### Description

`IListProvider<T>.ToList()` implementations in `System.Linq` for iterators of known lengths use `list.Add(element)` to initialize the list over directly writing to its underlying array.

This is to not forget to update the implementations once any of the following is done: https://github.com/dotnet/runtime/issues/80311, https://github.com/dotnet/runtime/issues/55217 or https://github.com/dotnet/runtime/issues/80756.

### Configuration

All versions

### Regression?

No

### Analysis

Once we have an API for direct `List<T>` initialization (aside from `new List<T>(collection)`), it's a good idea to utilize it in BCL to reduce the overhead.

**Comment by eiriktsarpalis** [comment]
Which implementations do you specifically have in mind? I'm looking at the implementation of `Select` and it seems to be specializing for arrays and IList types:

https://github.com/dotnet/runtime/blob/47f171e0c5a50fcc80377cdd9e7047a7a23c62ba/src/libraries/System.Linq/src/System/Linq/Select.SpeedOpt.cs#L310-L320

If you could identify the implementations that could be optimized we might take a look at accepting a PR that improves things, provided it does not regress assembly size substantially.

**Comment by neon-sunset** [comment]
> If you could identify the implementations that could be optimized we might take a look at accepting a PR that improves things, provided it does not regress assembly size substantially.

As you noted, implementations do specialize `ToList()`. However, for example, `RangeIterator`'s `ToList()` is 2-3 times slower than it could be because of having to go through `list.Add(i)` call. Same applies to `SelectArrayIterator` and friends, albeit impact is less significant especially when `_selector` is not inlined with DynamicPGO.

Once BCL gets https://github.com/dotnet/runtime/issues/55217 (or any of the alternatives), the performance can be improved by removing such overhead. This issue tracks this optimization.

**Comment by eiriktsarpalis** [comment]
> However, for example, RangeIterator's ToList() is 2-3 times slower than it could be because of having to go through list.Add(i) call.

Can you clarify? Looks like it does presize the list:

https://github.com/dotnet/runtime/blob/ad9efe886e16b179f2ce8e93221386d420ffe10d/src/libraries/System.Linq/src/System/Linq/Range.SpeedOpt.cs#L30-L39

**Comment by stephentoub** [comment]
> Looks like it does presize the list:

It presizes the capacity, but not the count, and as such it still goes through the Add call to then fill in each member.  They're suggesting that instead of:
```C#
     for (int cur = _start; cur != _end; cur++) 
     { 
         list.Add(cur); 
     } 
```
which will incur a bounds check, a version increment, etc. on every Add, that we could instead do something like that:
```C#
CollectionsMarshal.SetCount(list, _end - _start);
Span<int> span = CollectionsMarshal.AsSpan(list);
for (int i = 0; i < span.Length; i++)
{
    span[i] = i + _start;
}
```

**Comment by eiriktsarpalis** [comment]
Sounds reasonable. These components are constrained to the `*.SpeedOpt.cs` files so I think we could afford to make that improvement there.

@neon-sunset would you be interested in contributing a PR?

**Comment by stephentoub** [comment]
It's not possible to do until SetCount is added, and PR #77794 was closed.  Do we have a plan for finishing that?

**Comment by eiriktsarpalis** [comment]
I think we do. Seems it was closed by the bot for inactivity.

**Comment by neon-sunset** [comment]
> would you be interested in contributing a PR?

Yes, thanks, this was the intention when creating this issue, to not miss it when it becomes possible.

**Comment by theodorzoulias** [comment]
[It is already possible](https://stackoverflow.com/questions/466946/how-to-initialize-a-listt-to-a-given-size-as-opposed-to-capacity/65766955#65766955 "How to initialize a List<T> to a given size (as opposed to capacity)?") to initialize a `List<T>` with `default(T)` values, by using a custom `ICollection<T>` that has a `CopyTo` implemented as a no-op. Not as ideal as the `CollectionsMarshal.SetCount`, but possible.

**Comment by brantburnett** [comment]
It appears that the blocker has been resolved, `CollectionsMarshal.SetCount` has been merged. Would anyone mind if I worked on this?

**Comment by stephentoub** [comment]
> It appears that the blocker has been resolved, `CollectionsMarshal.SetCount` has been merged. Would anyone mind if I worked on this?

You're welcome to if you find opportunity.  I think most of it has been done, however.
