### ISSUE TITLE
How to build CoreCLR on windows arm64ec using MSVC

### ISSUE THREAD

**Issue by YangYang129** [dotnet/runtime#80774]
### Description

We try MSVC to run `.\build.cmd -subset clr+libs -c release -arch x64` build on x64, it works. But we tried to build for target arm64ec and run `.\build.cmd -subset clr+libs -c release -arch ARM64EC`, display error:
```
F:\gitP\dotnet\runtime\eng\build.ps1 : Cannot validate argument on parameter 'arch'. The argument "ARM64EC" does not
belong to the set "x86,x64,arm,arm64,wasm" specified by the ValidateSet attribute. Supply an argument that is in the
set and then try the command again.
At line:1 char:76
+ ... tnet\runtime\eng\build.ps1' -subset clr+libs -c release -arch ARM64EC
+                                                                   ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [build.ps1], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,build.ps1
```

 How to build CoreCLR on windows arm64ec using MSVC? Thanks in advance.

### Reproduction Steps

1. Open VS2019 x64 tools command
2. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
3. git clone https://github.com/dotnet/runtime F:\gitP\dotnet\runtime
4. cd F:\gitP\dotnet\runtime
5. .\build.cmd -subset clr+libs -c release -arch ARM64EC

### Expected behavior

CoreCLR compiler fine on windows arm64ec using MSVC

### Actual behavior

```
F:\gitP\dotnet\runtime\eng\build.ps1 : Cannot validate argument on parameter 'arch'. The argument "ARM64EC" does not
belong to the set "x86,x64,arm,arm64,wasm" specified by the ValidateSet attribute. Supply an argument that is in the
set and then try the command again.
At line:1 char:76
+ ... tnet\runtime\eng\build.ps1' -subset clr+libs -c release -arch ARM64EC
+                                                                   ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [build.ps1], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,build.ps1
```

**Comment by teo-tsirpanis** [comment]
I don't think Visual Studio 2019 is supported.

**Comment by janvorli** [comment]
@YangYang129  We only support arm64 target arch
