### ISSUE TITLE
Distributed Transaction .Net 7 - Lost process

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#80776]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Distributed-Transaction-Net-7---Lost-pr/10230303)._

---
[severity:It's more difficult to complete my work]
Hello,
I using a distributed transaction in .net 7.
I have a problem when the transaction is disposed, the transaction is completeted and everything is commit on database but when the transaction is disposed I lost the process whitout error.
After debugging system dll, the last point I can access is the function "Commit" on the file "CommitableTransaction.cs".
On this function I lost the process on the method "_internalTransaction.State.BeginCommit(_internalTransaction, false, null, null);".

```
TransactionManager.ImplicitDistributedTransactions = true;
 using (var scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
 {
     using (var connection = new SqlConnection("data source=LOCALHOST;initial catalog=test;integrated security=SSPI;MultipleActiveResultSets=True;Encrypt=False;"))
     {
         await connection.OpenAsync();
    
         SqlCommand command = connection.CreateCommand();
         command.CommandType = CommandType.Text;
         command.CommandText = "UPDATE dbo._Dossier SET Solde -= 10 WHERE IdDossier = 9999";
    
         await command.ExecuteNonQueryAsync();
     }
     using (var connection = new SqlConnection("data source=LOCALHOST;initial catalog=test2;integrated security=SSPI;MultipleActiveResultSets=True;Encrypt=False;"))
     {
         await connection.OpenAsync();
    
         SqlCommand command = connection.CreateCommand();
         command.CommandType = CommandType.Text;
         command.CommandText = "UPDATE dbo._Dossier SET Solde -= 10 WHERE IdDossier = 9999";
    
         await command.ExecuteNonQueryAsync();
     }
     scope.Complete();
 }
```

---
#### Feedback Bot on 12/15/2022, 04:12 AM: 

(private comment, text removed)
#### Ilias Jeulin on 12/16/2022, 03:15 PM: 

(private comment, text removed)
#### Feedback Bot on 1/4/2023, 03:01 AM: 

(private comment, text removed)
#### Xiao Ou Lv [MSFT] on 1/4/2023, 09:54 AM: 

(private comment, text removed)
#### Ilias Jeulin on 1/4/2023, 11:34 AM: 

(private comment, text removed)
#### Xiao Ou Lv [MSFT] on 1/5/2023, 07:54 AM: 

(private comment, text removed)
#### Ilias Jeulin on 1/5/2023, 08:24 AM: 

(private comment, text removed)
#### Xiao Ou Lv [MSFT] on 1/6/2023, 07:42 AM: 

(private comment, text removed)
#### Ilias Jeulin on 1/6/2023, 08:00 AM: 

(private comment, text removed)
#### Xiao Ou Lv [MSFT] on 1/6/2023, 10:26 AM: 

(private comment, text removed)
#### Ilias Jeulin on 1/6/2023, 10:56 AM: 

(private comment, text removed)
#### Feedback Bot on 1/10/2023, 07:52 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by roji** [comment]
Can you please confirm whether you're using System.Data.SqlClient or Microsoft.Data.SqlClient, as well as the precise version?

**Comment by IliasJeulinL** [comment]
Hello,
I'm using Microsoft.Data.SqlClient.

**Comment by roji** [comment]
@IliasJeulinL I also need the precise version. If you're using anything less than the recently-released 5.1.0, please try that (there's a fix specifically for distributed transactions in that version).

If you're still encountering the bug, I'm going to need some sort of code repro - the code sample you've sent above does work for me.

**Comment by IliasJeulinL** [comment]
I used the version 4.0.0.
I update the Microsoft.Data.SqlClient version and it seem good.
I will test it further and confirm you that everything is fine.
Thank you very much

**Comment by IliasJeulinL** [comment]
Thank you
