### ISSUE TITLE
Assertion failed '!varTypeUsesFloatReg(targetType) || (emitTypeSize(targetType) == emitTypeSize(op1Type))'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#80773]
Failure in System.Numerics.Vectors.Tests in many variations of `runtime-coreclr libraries-jitstress` pipeline.

https://dev.azure.com/dnceng-public/public/_build/results?buildId=140597&view=ms.vss-test-web.build-test-results-tab&runId=3049944&resultId=199871&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

```
Assert failure(PID 4676 [0x00001244], Thread: 4260 [0x10a4]): Assertion failed '!varTypeUsesFloatReg(targetType) || (emitTypeSize(targetType) == emitTypeSize(op1Type))' in 'System.Numerics.Tests.Matrix3x2Tests:Matrix3x2EqualsNaNTest():this' during 'Generate code' (IL size 763; hash 0xd96aa0b9; FullOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\codegenxarch.cpp Line: 4927
    Image: C:\h\w\9E2F091C\p\dotnet.exe
```

@dotnet/jit-contrib

**Comment by JulieLeeMSFT** [comment]
Assigned to @TIHan for assert in Code Gen.
CC @dotnet/jit-contrib.

**Comment by tannergooding** [comment]
The first run I see this in is https://dev.azure.com/dnceng-public/public/_build/results?buildId=138109&view=results which corresponds to my PR https://github.com/dotnet/runtime/pull/80626

Notably I had run jitstress, but not the `libraries-jitstress` variant, just the `outerloop`, `isas-x86`, and `isas-x64`. I'm guessing there is some edge case that is only covered by libraries tests atm.

**Comment by TIHan** [comment]
I have a minimal repo so far:
```csharp
Matrix3x2 a = new Matrix3x2(float.NaN, 0, 0, 0, 0, 0);
Assert.False(a.Equals(new Matrix3x2()));
```
