### ISSUE TITLE
[wasm] Update emsdk to latest

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#80784]
The threading work requires an emscripten bump and our current build is fairly old

**Comment by lewing** [comment]
keep an eye out for https://github.com/emscripten-core/emscripten/pull/18191

**Comment by lewing** [comment]
@pavelsavara we should expose those values as msbuild properties and share them with the wasi build

**Comment by pavelsavara** [comment]
There is also this https://github.com/llvm/llvm-project/commit/1532be98f99384990544bd5289ba339bca61e15b for the main thread. I don't know if the emsdk bump already contains this LLVM update.

For the MT we will need `pthread_attr_getstack` on emscripten or something like that. 
WASI alternative doesn't exist yet afaik.

**Comment by radekdoulik** [comment]
The emscripten was updated for NET8 to version suitable for our MT support, currently we are at 3.1.34
