### ISSUE TITLE
IEnumerable<T>.All() should return false for empty collections

### ISSUE THREAD

**Issue by dmombach** [dotnet/runtime#80793]
### Description

IEnumerable<T>.All() returns true for empty collections; which can be misleading to developers.

Verifying all elements of a collection against a predicate should not return true if the collection is empty.
Returning true would tell developers that all of the collection elements are in conformity with the predicate; however, if there are no elements, returning true is misleading and can cause hard-to-find bugs.

Suggestion, changing the original extension method:

`        public static bool All<TSource>(this IEnumerable<TSource> source, Func<TSource, bool> predicate)
        {
            if (source == null)
            {
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.source);
            }

            if (predicate == null)
            {
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.predicate);
            }

            if (!source.Any())
            {
                return false;
            }

            foreach (TSource element in source)
            {
                if (!predicate(element))
                {
                    return false;
                }
            }

            return true;
        }`

### Reproduction Steps

`
var list = new List<DateTime>();

var test = list.All(i => i.Year == 2000);

// variable 'test' will be true, but the collection is empty, so no elements match the predicate!
`

### Expected behavior

IEnumerable<T>.All() should return false for empty collections:

`
var list = new List<DateTime>();

var test = list.All(i => i.Year == 2000);

// variable 'test' should be false because the collection is empty, so no elements match the predicate!
`

### Actual behavior

IEnumerable<T>.All() returns true for empty collections:

`
var list = new List<DateTime>();

var test = list.All(i => i.Year == 2000);

// variable 'test' is true, but the collection is empty thus no elements match the predicate!
`

### Known Workarounds

Verify if a collection is not empty before checking its elements with the IEnumerable<T>.All() extension method:

`
var list = new List<DateTime>();

var test = list.Any() && list.All(i => i.Year == 2000);

// variable 'test' will be false
`

**Comment by TheBuzzSaw** [comment]
I mean, first of all, this is definitely not going to change considering the current behavior has been out there for decades. Secondly, I am honestly shocked to see this even proposed. It is logically and mathematically correct that all elements of an empty set pass a predicate. If an empty collection is a special situation for your code, your code should handle that case.

**Comment by teo-tsirpanis** [comment]
I was going to say something similar but @TheBuzzSaw covered it better. I will close the issue since it would be a breaking change either way.

**Comment by TheBuzzSaw** [comment]
@dmombach Use this.

```csharp
static class Extensions
{
    public static bool AnyAndAll<T>(this IEnumerable<T> enumerable, Func<T, bool> predicate)
    {
        ArgumentNullException.ThrowIfNull(enumerable);
        ArgumentNullException.ThrowIfNull(predicate);

        using var enumerator = enumerable.GetEnumerator();

        if (!enumerator.MoveNext())
            return false;
        
        do
        {
            if (!predicate.Invoke(enumerator.Current))
                return false;
        }
        while (enumerator.MoveNext());
        
        return true;
    }
}
```
