### ISSUE TITLE
URI.TryCreate Does not correctly parse mailto protocol multiple to addresses

### ISSUE THREAD

**Issue by TheJoeFin** [dotnet/runtime#80799]
### Description
When building a `mailto` string and passing it to the `Uri.TryCreate` method. The method does not properly parse the `to` `sHeader` when there are multiple email addresses in the `to` area.

For example:
```
using System;
using System.Diagnostics;
					
public class Program
{
	public static void Main()
	{
		string uriString = @"mailto:user@example.com;user2@example.com;user3@example.com?subject=Message Title&body=Message Content";
		if (Uri.TryCreate(uriString, UriKind.Absolute, out var uri)) 
		{
			Debug.WriteLine("Success");
		}
		else
		{
			// this line is hit.
			Debug.WriteLine("Failure");
		}
	}
}
```

### Configuration
* Tested on .NET 6, but research leads me to believe this is more widespread.

### Other information
Using the `uriString` it works as expected in the following applications:
- Browser URL Bar
- Windows Run
- OneNote Link

**Comment by MihaZupan** [comment]
And what would you expect `Uri.UserInfo` or `Uri.Host` to return in such cases?

**Comment by TheJoeFin** [comment]
@MihaZupan, I'm not sure. I would assume whatever they return when there is a single email in the `to` field. 

The `mailto` protocol works fine when there is just one email in the `to` field, the issue only occurs where there are multiple.

**Comment by MihaZupan** [comment]
It's valid according to the [RFC](https://www.rfc-editor.org/rfc/rfc6068#section-2), but we're supporting only a limited version of the spec.

For example, the spec also notes
```
   Also note that it is syntactically valid to specify both <to> and an
   <hfname> whose value is "to".  That is,

   <mailto:addr1@an.example,addr2@an.example>

   is equivalent to

   <mailto:?to=addr1@an.example,addr2@an.example>
```
where `System.Uri` will fail to parse `mailto:addr1@an.example,addr2@an.example`, but succeed for `mailto:?to=addr1@an.example,addr2@an.example`.

For a Uri like `mailto:?to=addr1@an.example`, we'll also only populate the `Uri.Query` - `Uri.UserInfo` or `Uri.Host` will be empty.

---

@TheJoeFin If you don't care about getting any info from Uri's properties, would the fact that you can do
```
mailto:?to=user@example.com;user2@example.com;user3@example.com&subject=Message Title&body=Message Content
```
be a sufficient workaround?

**Comment by TheJoeFin** [comment]
@MihaZupan I use `Uri.TryCreate` in my app Text Grab (https://github.com/TheJoeFin/Text-Grab) to determine if a user has selected text which is a valid URI. If the URI is valid an additional `MenuItem` is added and when clicked Text Grab will `Process.Start...` the URI. Similar to when you select a URL in Edge/Chrome there is a right-click option to "Go to <URL>"

However, I found this bug when I was trying to build a `mailto:` within Text Grab for my personal use. So this work around would  help my situation personally, but for the app to function as expected the `Uri.TryCreate` will always return a false negative result in the scenario which prompted this issue.

**Comment by MihaZupan** [comment]
> So this work around would help my situation personally, but for the app to function as expected the Uri.TryCreate will always return a false negative result in the scenario which prompted this issue.

So in your case it resolves the issue fully, or would you still require changes from Uri to make things work?

Triage: This is the first time we've heard of someone trying to use Uri for a multi-address mailto. Given that we don't see a way to meaningfully support such inputs within the existing API shape (properties assume a single value), we're unlikely to make changes for this scenario.

**Comment by TheJoeFin** [comment]
@MihaZupan my app Text Grab relies upon the `Uri.TryCreate` to determine if a URI is valid. In the case I mentioned in this issue, users of Text Grab will get a false negative. It is not a major feature of the app, and I accept it will not work as expected.
