### ISSUE TITLE
JIT: `optInvertLoops` depends on bbNum ordering but doesn't guarantee it

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#80809]
While working on moving pred list building earlier I am seeing spurious diffs from `optInvertLoops`.

Looks like it expects blocks to have been renumbered but it doesn't check or try and renumber. Morph (which is a bit upstream) will often renumber so this only impacts a small set of methods.

https://github.com/dotnet/runtime/blob/e6bb67612ab8ad43415c851a1a1dfa6a9057af98/src/coreclr/jit/optimizer.cpp#L5145-L5152

**Comment by AndyAyersMS** [comment]
cc @BruceForstall 

I will fix this as a one-off. Seems like we might be on the verge of phases having checked preconditions or something...

**Comment by BruceForstall** [comment]
> Seems like we might be on the verge of phases having checked preconditions

That would be useful. I've found various places which depend on bbNum ordering when it's not clear they are properly ordered.
