### ISSUE TITLE
Matchad Prime clipboard bugs after NET 7.0 installation

### ISSUE THREAD

**Issue by cser** [dotnet/runtime#80815]
I reset the applications to the "factory settings" on windows 10 several times and after this PTC Matchad Express 7.0 30-day trial (uses NET 4.5, did not install anything specifically) worked correctly. As soon as I installed NET 7.0 (https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-7.0.102-windows-x64-installer ) and rebooted the computer - a bug appeared:
- create a text field (Ctl+T), enter the text;
- enter the formula (Ctrl+Shift+M);
- select the text (Ctrl+C);
- paste the text - it is inserted without a formula (but if you copy only the formula, then it's copied correctly).
The bug remains after NET 7.0 uninstalling. How can I uninstall it to recover Mathcad Prime correct working?

**Comment by cser** [comment]
Excuse me. I was wrong :confused:.

It's not .NET 7.0. I reset my win 10 again yesterday, nothing was installed except Mathcad Express 7.0. At first it works normally, And today the bug appeared again.

P.S. Do you know where to write to Microsoft, so as not to be ignored? I have already written to the windows 10 feedback center - no effect.

**Comment by danmoseley** [comment]
Hello, I'm unclear how you decided this is an OS bug not an app bug? 
Yes, feedback tool is how to report windows bugs (or support call if you have paid contract)

**Comment by cser** [comment]
@danmoseley:
I think so because:
- This is not a new Mathcad bug - it appeared without updating PTC Mathcad, it exists in versions 7 and 8 (and I have no doubt that versions 3, 4, 5, 6 are broken too).
- The error appeared in December 2022 not only for me (https://community.ptc.com/t5/Mathcad/Copy-Paste-issue-with-MathCAD-8-0/m-p/845725#M204261).
- Colleagues who did not install NET 7.0 has this bug too and they didn't complain about it two months ago.
- After resetting Windows 10 error is disapeared. Mathcad works correctly. But a day later (after 3 reboots), it breaks again.
If you are interested, this is journal after Windows 10 resetting: https://github.com/cser/images/blob/master/post_files/mathcad_error_win10stability.xml.

P.S. It's not mean, that PTC isn't blame for innormal clipboard using, but who feels better about it?

**Comment by jkotas** [comment]
Please report this bug to Mathcad, or via Windows feedback tool if you believe that it is Windows issue.

**Comment by cser** [comment]
@jkotas
The problem is solved! Microsoft published instructions to fix it. It was problem with December 2022 security updates for .NET Framework 4.8, 4.8.1.
https://support.microsoft.com/en-gb/topic/kb5022083-change-in-how-wpf-based-applications-render-xps-documents-a4ae4fa4-bc58-4c37-acdd-5eebc4e34556

**Comment by wstaelens** [comment]
@cser https://docs.winking.be/Tn/Article/285 also other updates besides the december 2022 could affect it.
