### ISSUE TITLE
NegotiateStream Wireshark decoder

### ISSUE THREAD

**Issue by SteveSyfuhs** [dotnet/runtime#80818]
Howdy folks. Not a bug -- more of a query. Windows team is working on our NTLM deprecation project and to simplify a lot of interop testing we're using a painfully simple `NegotiateStream`-over-socket test app. It works fine for our purposes, but we're having trouble reading the SPNego messages using Wireshark. Search yielded nothing interesting, so here we are.

How have folks analyzed NS packets with wireshark in the past? Is there a message structure that we can use to parse out messages we care about?

Sample code to highlight exactly how we're testing.

```csharp
internal class Program
{
    private const int port = 8282;

    static async Task Main(string[] args)
    {
        if (args.Length == 0)
        {
            Console.WriteLine("pick client or server");
            return;
        }

        while (true)
        {
            try
            {
                switch (args[0].ToLowerInvariant())
                {
                    case "client":
                        await ExecuteClient();
                        break;
                    case "server":
                        await ExecuteServer();
                        break;
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex}");

                Console.Write("Try again...");
                Console.Read();
            }
        }
    }

    private static async Task ExecuteServer()
    {
        var server = new TcpListener(IPAddress.Any, port);

        try
        {
            server.Start(1000);

            Console.WriteLine("Server started");

            while (true)
            {
                Console.WriteLine("Waiting to accept");

                using (var client = await server.AcceptTcpClientAsync())
                using (var nego = new NegotiateStream(client.GetStream()))
                {
                    Console.WriteLine("Accepted");
                    Console.WriteLine("Authenticating");

                    await nego.AuthenticateAsServerAsync();

                    Console.WriteLine("Authenticated");
                }
            }
        }
        finally
        {
            server.Stop();
        }
    }

    private static async Task ExecuteClient()
    {
        Console.WriteLine("Connecting");

        using (var client = new TcpClient("stsyfuhs-s1", port))
        using (var nego = new NegotiateStream(client.GetStream()))
        {
            Console.WriteLine("Authenticating");

            await nego.AuthenticateAsClientAsync(
                new NetworkCredential("mememe@meeeeee.com", "beans", "makingthisup.com"),
                "host/myserver"
            );

            Console.WriteLine("Authenticated");
        }
    }
}

```

**Comment by filipnavara** [comment]
It's not going to answer your question but there is [a specification](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-nns/93df08eb-a6c4-4dff-81c3-519cf7236df4) and numerous projects like NPgSql used to unwrap the messages in the past.

Then again, you may be better off just using the `NegotiateAuthentication` primitive in .NET 7 instead of `NegotiateStream`. It really trivial to wrap it into SASL exchange within some protocol that Wireshark understands, like SMTP. In fact, there are unit tests in this repository that do just that.

**Comment by BrennanConroy** [comment]
Maybe helpful?
Kestrel has a stream wrapper that logs bytes in a wireshark-esque format: https://github.com/dotnet/aspnetcore/blob/de8b5afeb180779c2c16f22cc2e392cb4cf59ed6/src/Servers/Kestrel/Core/src/Middleware/Internal/LoggingStream.cs#L150

**Comment by wfurt** [comment]
The problem is that `NegotiateStream` adds it's own headers that are .NET specific. The API @filipnavara mentioned was done in 7.0 and allows app to dump all the wrapping silliness: https://github.com/npgsql/npgsql/pull/4618

**Comment by ManickaP** [comment]
@SteveSyfuhs did the above comments answered your question? Or is there anything else?

**Comment by SteveSyfuhs** [comment]
Yup, this was helpful. Will likely work out something using the `NegotiateAuthentication` primitive and wrap it another protocol frame.
