### ISSUE TITLE
Light up `Span` with `Vector512` code paths.

### ISSUE THREAD

**Issue by anthonycanino** [dotnet/runtime#80824]
This task is for optimizing `Span` with `Vector512` code paths. We will likely target `Span.IndexOf` as a first potential `Vector512` code path for `Span`. This task will be updated with a list of methods in `Span` that we will likely target (and for each of its specialized implementations, e.g., `Char` and `Byte`).

**Comment by DeepakRajendrakumaran** [comment]
Have started work on this.

**Comment by BruceForstall** [comment]
@DeepakRajendrakumaran Does https://github.com/dotnet/runtime/pull/86655 complete this, or is there more you are working on?

**Comment by DeepakRajendrakumaran** [comment]
This has been completed and merged
