### ISSUE TITLE
Add opmask (k) registers to the register allocator

### ISSUE THREAD

**Issue by anthonycanino** [dotnet/runtime#80823]
This task will add the ability to specify opmask registers as LSRA constraints to the register allocator. This task has a dependency on https://github.com/dotnet/runtime/issues/80821.

**Comment by BruceForstall** [comment]
@tannergooding Is this complete with https://github.com/dotnet/runtime/pull/89059?

**Comment by tannergooding** [comment]
Yes it is. We're not allowing allocation of `k0` at the moment, because its a bit special; but there's nothing blocking it from being used outside setting the right preferencing for when its invalid
