### ISSUE TITLE
Add optimization for scalar/vector conversion of `uint32`/`uint64` to/from packed `float`/`double`

### ISSUE THREAD

**Issue by anthonycanino** [dotnet/runtime#80829]
`AVX512VL` adds a number of new scalar/packed conversion for unsigned 32-bit/64-bit integer types to float/double. These allow to replace less efficient conversions on xarch --- either multiple instructions or dedicated helper methods --- with single accelerated instructions.

**Comment by tannergooding** [comment]
This was completed in https://github.com/dotnet/runtime/pull/97529 and https://github.com/dotnet/runtime/pull/100993
