### ISSUE TITLE
Add EVEX encoding opmask (k) register masking to xarch emitter

### ISSUE THREAD

**Issue by anthonycanino** [dotnet/runtime#80821]
This task includes adjusting `instrDesc` to allow for an opmask register operand --- which will likely incur some additional refactorings --- and the xarch emitter to add the opmask register operand using EVEX form.

**Comment by tannergooding** [comment]
This was resolved in https://github.com/dotnet/runtime/pull/97675 and https://github.com/dotnet/runtime/pull/101886
