### ISSUE TITLE
Enable EVEX embedded broadcasting support in xarch emitter

### ISSUE THREAD

**Issue by anthonycanino** [dotnet/runtime#80825]
The purpose of this task is to extend the xarch emitter to allow the use of embedded broadcasting capability of EVEX for SIMD ops. Ideally, this task isolated the changes to enabling the embedded broadcasting in the xarch backend. It's currently open what needs to be redesigned to fold SIMD constants + SIMD ops into a single SIMD op with a broadcast. Will follow up with that investigation.

**Comment by BruceForstall** [comment]
@tannergooding @Ruihan-Yin Can we close this now that https://github.com/dotnet/runtime/pull/84821 is merged?

**Comment by tannergooding** [comment]
Yes. Closing
