### ISSUE TITLE
Category name should be deduced when injecting ILogger

### ISSUE THREAD

**Issue by vladinvancouver** [dotnet/runtime#80895]
The class receiving an ILogger injection needs to specify the category name for the logger. For example:

```
public AccountsController(ILogger<AccountsController> logger)
{
...
}

```
This is error prone when doing copy/paste. For example, inside the AccountsController, you can do the following which does not make sense:

```
public AccountsController(ILogger<PaymentsController> logger)
{
...
}
```

It would be great if the compiler could deduce the category name from the class name so that we can do the following:

```
public AccountsController(ILogger logger)
{
...
}
```

**Comment by davidfowl** [comment]
That isn't possible to implement today. The dependency injection system would need to support factories that could infer what the target type being injected into was.

This is really a dependency injection feature request.

**Comment by vladinvancouver** [comment]
Could you consider implementing this as a compiler feature? When the compiler see ILogger argument in a constructor, it converts it to ILogger<ClassName>. If I am not mistaken, there are lots of examples where the compiler does this kind of "magic". What do you think?

**Comment by davidfowl** [comment]
What would the compiler feature be?

**Comment by vladinvancouver** [comment]
I may not be using the correct terminology so please bare with me.

Let's say the user code is:

`public AccountsController(ILogger logger)`

The compiler transforms the code and then generates IL as through the user wrote:

`public AccountsController(ILogger<AccountsController> logger)`

Maybe this is done during the **lowering** process - I don't know. The end result is that the coder does not have to specify category name. The compiler generates the category name.

**Comment by davidfowl** [comment]
Right, that's not something that would be integrated into the compiler. C# knows nothing about the logger, and there's no way external code (source generators) can completely rewrite user code like this.

The best bet to making something like this work is a feature in DI that allows for something like this:

```C#
builder.Services.AddSingleton<ILogger>((IServiceProvider serviceProvider, Type targetType) =>
{
     return (ILogger)serviceProvider.GetService(typeof(Logger<>).MakeGenericType(targetType));
});
```
