### ISSUE TITLE
Directory.EnumerateFilesAsync API returning IAsyncEnumerable<string>

### ISSUE THREAD

**Issue by jnm2** [dotnet/runtime#809]
Due to the slowness of network calls, it became important for a desktop app to stream file results in before waiting for all of them.

Equally important was to respond to each MoveNextAsync/Current call on a threadpool thread since each call to FindFirstFileEx and FindNextFile are blocking on I/O. On a UI thread, this deteriorates the responsiveness. [Raymond Chen](https://devblogs.microsoft.com/oldnewthing/20131024-00/?p=2843) (and others I'm sure) will tell you not to do directory enumeration on a UI thread at all.

I looked for a .NET Core 3.1 API and didn't find one, so I wrote the simplest thing that worked:

```cs
public static async IAsyncEnumerable<string> EnumerateFilesAsync(
    string path,
    string searchPattern,
    SearchOption searchOption,
    [EnumeratorCancellation] CancellationToken cancellationToken)
{
    await TaskScheduler.Default.SwitchTo(cancellationToken);

    foreach (var file in Directory.EnumerateFiles(path, searchPattern, searchOption))
    {
        yield return file;

        await TaskScheduler.Default.SwitchTo(cancellationToken);
    }
}
```

###### `TaskScheduler.SwitchTo` is an [extension method](https://gist.github.com/jnm2/46a642d2c9f2794ece0b095ba3d96270) which I borrowed from [vs-threading](https://github.com/microsoft/vs-threading/blob/v16.4.33/src/Microsoft.VisualStudio.Threading/AwaitExtensions.cs) and augmented to handle cancellation. After https://github.com/dotnet/corefx/issues/15490 is implemented, that would probably be preferable.

</small>

I have two questions:

1. Could this implementation improved with access to .NET Core internals?

2. Should the burden of continuing from a `yield return` on a background thread belong to the `EnumerateFilesAsync` implementation, or should the caller know that MoveNextAsync will do blocking I/O and do its own marshaling? To make this easy, should there be an `asyncEnumerable.ConfigureMoveNext(continueOnSyncronizationContext: true)` wrapping extension method?

   E.g.

   ```cs
   // UI thread
   var filePaths = await Task.Run(() =>
   {
       // Task.Run ensures that EnumerateFilesAsync is not called from a UI thread and that the
       // synchronization context that ConfigureMoveNext captures will post work to the thread pool.
       return Directory.EnumerateFilesAsync(...).ConfigureMoveNext(true);
   });
   
   await foreach (var filePath in filePaths)
   {
       // List the file in the UI.
   }
   ```

**Comment by scalablecory** [comment]
There are many filesystem ops which are still blocking purely because OS has no async version of them.

I think this opens up a broader question of if we want to expose async APIs for many of these (possibly by a lot of fake async, which we currently avoid and also recommend users avoid)

**Comment by stephentoub** [comment]
> Could this implementation improved with access to .NET Core internals?

Not really.

> To make this easy, should there be an asyncEnumerable.ConfigureMoveNext(continueOnSyncronizationContext: true) wrapping extension method?

I don't think so.

I'd prefer to just see the caller be explicit about what they want, e.g.
```C#
using (var e = Directory.EnumerateFiles(...).GetEnumerator())
{
    while (await Task.Run(() => e.MoveNext())
    {
         Use(e.Current);
    }
}
```

Unless we had APIs on the various OSes to actually perform the directory walk using async I/O (and to my knowledge we don't), I wouldn't want such an EnumerateFilesAsync method exposed from the core libraries.

**Comment by jnm2** [comment]
That is very helpful. Thank you for the quick answer!

If a single OS begins supporting async directory enumeration I/O, would that be a good reason to open a new issue proposing the API?

**Comment by stephentoub** [comment]
> If any single OS begins supporting async directory enumeration I/O, would that be a good reason to open a new issue proposing the API? Or would it have to be particular OSes?

It's hard to speculate.  Ideally we only add functionality that can be properly implemented everywhere.  If it can only be implemented properly in one place and needs to be inefficiently emulated in others, then it would nee to be proven to be really important, so much so that it's worth the potential pit of failure to enable the important case.
