### ISSUE TITLE
NullReferenceException in LoggerFactory

### ISSUE THREAD

**Issue by qsdfplkj** [dotnet/runtime#80902]
This is a minimal reproducution that causes the NullReferenceException:

    new LoggerFactory(Enumerable.Empty<ILoggerProvider>(), (LoggerFilterOptions)null).CreateLogger("Test");

The exception is triggered when the CreateLogger is called but it is related to the LoggerFilterOptions being null.

I'm running in .NET 6 but the library seems to be the Microsoft.Extensions.Logging library is 7.0.0

**Comment by qsdfplkj** [comment]
I think it's caused by the depends injection on a azure function. But from the overloads on the constructors it's stange that there is no argument null exception from the constructor while the others have defaults for the options. It's more that it is really unexpected to get an exception Later on.

**Comment by tarekgh** [comment]
You should be getting a warning when compiling with nullability check enabled. 

```
warning CS8600: Converting null literal or possible null value to non-nullable type.
```

I think this should be good enough to catch such cases.

**Comment by qsdfplkj** [comment]
Yes I didn't notice but the nullable does not protect from setting up an invalid loggerfactory. Throwing an nullreferemceexception or using a default value does.

**Comment by tarekgh** [comment]
> does not protect from setting up an invalid loggerfactory

I am not sure what you are trying to protect against if you are eventually getting the exception anyway? What exactly is the scenario you want to protect against? I am trying to avoid any behavior here if there is no strong reason to do so.

**Comment by qsdfplkj** [comment]
After the constructor is done I have a loggerfactory on which I would assume would be able to safely call createlogger.

Use nullable reference types and checking the parameters are two different things. One stops you from creating the object the other helps you writing cleaner code.

**Comment by tarekgh** [comment]
@qsdfplkj I am not arguing check for null is not better. I am trying to understand the problem you are currently running into it. This code has been like that for a long time, and no-one complained before. 

Anyway, if you are interested, you may submit a PR.
