### ISSUE TITLE
Simply language tag, with only language code and without country or region code, are not recognized for currency symbol

### ISSUE THREAD

**Issue by RafBorrelli** [dotnet/runtime#80906]
### Description

If CultureInfo is missing of country code, the currency symbol is displayed as the generic symbol **¤**.

In blazor we can get the browser culture from the `Accept-Language` request HTTP header, using `BlazorWebAssemblyLoadAllGlobalizationData`. But int the `Accept-Language` header, the country code is optional, so, depending from user configuration, we can retrieve just "it" as language code, instead of "it-IT".

Example from Microsoft Edge:
`Accept-Language: it,it-IT;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6`

### Reproduction Steps

https://dotnetfiddle.net/lueNWv

```
CultureInfo.DefaultThreadCurrentCulture = new("it");
CultureInfo.DefaultThreadCurrentUICulture = new("it");
Console.WriteLine($"{number:C} \t CurrentCulture: {CultureInfo.CurrentCulture} (UI: {CultureInfo.CurrentUICulture})");	

CultureInfo.DefaultThreadCurrentCulture = new("it-IT");
CultureInfo.DefaultThreadCurrentUICulture = new("it-IT");
Console.WriteLine($"{number:C} \t CurrentCulture: {CultureInfo.CurrentCulture} (UI: {CultureInfo.CurrentUICulture})");	
```

### Expected behavior

```
1.999,69 €      CurrentCulture: it (UI: it)
1.999,69 €      CurrentCulture: it-IT (UI: it-IT)
```

### Actual behavior

```
1.999,69 ¤      CurrentCulture: it (UI: it)
1.999,69 €      CurrentCulture: it-IT (UI: it-IT)
```

### Configuration

- .net 7
- Microsoft Edge 109.0.1518.55 (64 bit)
- Windows 10 Pro 21H2 19044.2486 x64

**Comment by tarekgh** [comment]
This is intentional, all neutral cultures are not attached to specific regions and cannot have specific currency. If you take your example, `it`, there are 4 cultures which use the Italian languages:

```
it-CH: Italian (Switzerland) .... CHF
it-IT: Italian (Italy) .... €
it-SM: Italian (San Marino) .... €
it-VA: Italian (Vatican City) .... €
```

Note, not all these cultures use the `€` as a currency symbol. So, having `it` return `€` will be wrong. 

The framework provides the method `CultureInfo.CreateSpecificCulture` which can create a specific culture from a neutral culture. 

```C#
    Console.WriteLine(CultureInfo.CreateSpecificCulture("it").NumberFormat.CurrencySymbol); // print `€`
```
