### ISSUE TITLE
Enable AppleAppBuilder to bundle applications compiled with NativeAOT

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/runtime#80910]
## Description 
AppleAppBuilder build task currently only supports Mono as the default AOT compiler and runtime when creating application bundles. 

## Proposal 
Extend AppleAppBuilder to support NativeAOT, as a second AOT compiler and runtime, when creating iOS application bundles. 
This would enable building and running sample applications built with NativeAOT on iOS platforms, but also size and performance monitoring.

**Comment by am11** [comment]
It gets enabled when `TargetPlatformIdentifier` is set (not to be confused with `TargetFrameworkIdentifier` / TFI).

e.g. `<TargetFramework>net7.0-macos</TargetFramework>` is same as:

```xml
    <TargetFramework>net7.0</TargetFramework>
    <TargetPlatformIdentifier>macos</TargetPlatformIdentifier>
```

By setting TPI, .NET SDK imports `WorkloadManifestTargetsLocator`, which resolves `Microsoft.macos.Sdk.net7` SDK, which further resolves `Microsoft.NET.Runtime.MonoTargets.Sdk.net7` and then `Xamarin.Shared.Sdk` etc. Somewhere there in the SDK, we can check if `'$(PublishAot)' == 'true'` then e.g. skip importing `WorkloadManifestTargetsLocator` or something down the chain. There maybe some more changes required but that would be the starting point to ninja in the NativeAOT bits. 🥷

**Comment by ivanpovazan** [comment]
> It gets enabled when `TargetPlatformIdentifier` is set (not to be confused with `TargetFrameworkIdentifier` / TFI).
> 
> e.g. `<TargetFramework>net7.0-macos</TargetFramework>` is same as:
> 
> ```
>     <TargetFramework>net7.0</TargetFramework>
>     <TargetPlatformIdentifier>macos</TargetPlatformIdentifier>
> ```
> 
> By setting TPI, .NET SDK imports `WorkloadManifestTargetsLocator`, which resolves `Microsoft.macos.Sdk.net7` SDK, which further resolves `Microsoft.NET.Runtime.MonoTargets.Sdk.net7` and then `Xamarin.Shared.Sdk` etc. Somewhere there in the SDK, we can check if `'$(PublishAot)' == 'true'` then e.g. skip importing `WorkloadManifestTargetsLocator` or something down the chain. There maybe some more changes required but that would be the starting point to ninja in the NativeAOT bits. 🥷

^ @kotlarmilos I believe this would contribute to your SDK integration work
