### ISSUE TITLE
[API Proposal]: Dataflow SourceBlock<T>

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#80915]
### Background and motivation

It would be really nice if there was a dataflow block that would output a predetermined set of items.
It would essentially be the equivalent of a ```TransformMany<object?, TOutput>``` that is prepopulated with ```null```.

### API Proposal

```csharp
namespace System.Threading.Tasks.Dataflow;

public class SourceBlock<TOutput> : ISourceBlock<TOutput>
{
    public SourceBlock(params TOutput[] Source);
    public SourceBlock(IEnumerable<TOutput> Source);
    public SourceBlock(IAsyncEnumerable<TOutput> Source);
}
```

### API Usage

```csharp
// Fancy the value
var c = new MyFancyCollection<int>();
c.Fancy(42);

// Getting the values out
foreach (var v in c)
    Console.WriteLine(v);
```

### Alternative Designs

None

### Risks

None.

**Comment by stephentoub** [comment]
You can already do:
```C#
public static ISourceBlock<TOutput> CreateSourceBlock(params TOutput[] items)
{
    var block = new BufferBlock<TOutput>();
    foreach (TOutput item in items) block.Post(item);
    block.Complete();
    return block;
}
```
Why would a custom block be needed here?

**Comment by TonyValenti** [comment]
With your example, the buffer block is being populated at creation time.

In my use case, I'll have an AsyncEnumerable that will be doing a lazy pull of records from a database. (We don't want to load 10mil records into a buffer).

Conceptually, we also like the idea of having the values "pulled" out of the block itself instead of having a Task.Run that is responsible for pushing items into  a buffer block.

**Comment by stephentoub** [comment]
If you don't want to populate it all at construction, can't you do something like:
```C#
static ISourceBlock<TOutput> CreateSourceBlock<TOutput>(IAsyncEnumerable<TOutput> source)
{
    var tm = new TransformManyBlock<IAsyncEnumerable<TOutput>, TOutput>(ae => ae);
    tm.Post(source);
    tm.Complete();
    return tm;
}
```
?

> Conceptually, we also like the idea of having the values "pulled" out of the block itself instead of having a Task.Run that is responsible for pushing items into a buffer block.

That doesn't really fit with the notion of dataflow, where blocks push data to the next.  If a target isn't notified of another item being available, it won't pull one, and so if the next item is only retrieved when a target requests one, the whole thing will hang.

**Comment by TonyValenti** [comment]
This is a good idea. Thanks!
