### ISSUE TITLE
CodeDom - CodeTypeReference - Invalid VB output for List<int>[]

### ISSUE THREAD

**Issue by marius-bughiu** [dotnet/runtime#80921]
### Description

`CodeDomProvider` has incorrect `CodeTypeReference` output for `VisualBasic` for types like `List<int>[]` or `Dictionary<int, int>[]`. The unit test below tests a list of inputs and expected outputs.

### Reproduction Steps

```
public class CodeDomVbTests
{
    public static IEnumerable<object[]> TestCases() => new[]
        {
            new object [] { typeof(string),                 "String" },
            new object [] { typeof(bool),                   "Boolean" },
            new object [] { typeof(List<int>),              "System.Collections.Generic.List(Of Integer)" },
            new object [] { typeof(List<int>[]),            "System.Collections.Generic.List(Of Integer)()" },
            new object [] { typeof(Dictionary<int, int>),   "System.Collections.Generic.Dictionary(Of Integer, Integer)" },
            new object [] { typeof(Dictionary<int, int>[]), "System.Collections.Generic.Dictionary(Of Integer, Integer)()" },
        };

    [Theory]
    [MemberData(nameof(TestCases))]
    public void Should_Compile_Variable_Given_Definition(Type type, string expectedOutput)
    {
        var output = GetTypeReferemceExpression(type);

        Assert.Equal(expectedOutput, output);
    }

    private static string GetTypeReferemceExpression(Type type)
    {
        var codeDomProvider = CodeDomProvider.CreateProvider("VisualBasic");
        var typeReferenceExpression = new CodeTypeReferenceExpression(new CodeTypeReference(type));

        using var writer = new StringWriter();
        codeDomProvider.GenerateCodeFromExpression(typeReferenceExpression, writer, new CodeGeneratorOptions());

        var text = writer.GetStringBuilder().ToString();
        return text;
    }
}
```

### Expected behavior

I would expect the follwing:

| Input  | Output  | 
|---|---|
| List\<int>[]  | System.Collections.Generic.List(Of Integer)()  | 
|  Dictionary<int, int>[] | System.Collections.Generic.Dictionary(Of Integer, Integer)()  | 

### Actual behavior

It seems to ignore the fact that they are in fact arrays of lists and omits the `()` at the end.

| Input  | Output  | 
|---|---|
| List\<int>[]  | System.Collections.Generic.List(Of Integer) | 
|  Dictionary<int, int>[] | System.Collections.Generic.Dictionary(Of Integer, Integer)  | 

### Configuration

I've tested with `System.CodeDom` versions `6.0.0` and `7.0.0`, and it's reproducible with both.
It is also reproducible with the latest `main` at the time the ticket was created.

### Other information

The same works just fine if you use the `CSharp` provider.

**Comment by marius-bughiu** [comment]
I think the bot got the area wrong, it should be @dotnet/area-system-codedom

**Comment by marius-bughiu** [comment]
I was just now looking through the unit tests trying to understand the issue better (I am not very proficient with VB), and I noticed that there are two way to create an array of lists in VB:

`Dim arrayOfLists() As List(Of Integer)`

and

`Dim arrayOfLists As List(Of Integer)()`

What is the difference between the two?

**Comment by marius-bughiu** [comment]
After tinkering further with tests and the code, I figured `GetTypeOutput` outputs what I need.

That being said, I still think the output generated for `CodeTypeReferenceExpression` is incorrect.

**Comment by buyaa-n** [comment]
> `Dim arrayOfLists() As List(Of Integer)`
> 
> and
> 
> `Dim arrayOfLists As List(Of Integer)()`
> 
> What is the difference between the two?
> 
> LE: It seems like the code generator prefers the first:

I am not familiar with VB, though the docs suggest the firs, https://learn.microsoft.com/en-us/office/vba/language/concepts/getting-started/declaring-arrays, actually I did not find any doc that suggests the other option, so it doesn't look like a bug that needs a fix.
