### ISSUE TITLE
Memory leak in JsonSerializer.DeserializeAsyncEnumerable when constructors are used

### ISSUE THREAD

**Issue by MatElcome** [dotnet/runtime#80933]
### Description

The `JsonSerializer.DeserializeAsyncEnumerable<T>` method can be used to deserialize root-level JSON arrays in a streaming manner, as opposed to calling `JsonSerializer.DeserializeAsync<IAsyncEnumerable<T>>` which will materialize the complete array before returning. This allows us to process json files which are too large to hold in memory.

However, if the deserializer uses a parameterized constructor to create the object (instead of calling the parameterless constructor and property setters) then memory usage will climb until an `OutOfMemoryException` occurs.

### Reproduction Steps

[See here](https://github.com/MatElcome/JsonOomExample) for a full example project.

Firstly, add the following environment variables to limit the maximum heap size - in this case to 256MiB. (Otherwise the full system memory will be available, and a larger json file must be created to reproduce the issue).
```
DOTNET_gcServer=1
DOTNET_GCHeapHardLimit=10000000
```

Define the data model which you will be deserializing, providing a public parameterized constructor:
```cs
class TestModel
{
    public Guid Id { get; set; }
    public DateTimeOffset Date { get; set; }

    [JsonConstructor]
    public TestModel(Guid id, DateTimeOffset date)
    {
        this.Id = id;
        this.Date = date;
    }
}
```

Then create the .json file - it should be larger than the available heap size, eg. 300MiB in size:
```cs
using var stream = File.Create(jsonFilename);
var items = Enumerable.Range(0, 4_000_000)
                      .Select(c => new TestModel(Guid.Empty, DateTimeOffset.MinValue));
await JsonSerializer.SerializeAsync(stream, items);
```
```json
[
  {"Id":"00000000-0000-0000-0000-000000000000","Date":"0001-01-01T00:00:00+00:00"},
  {"Id":"00000000-0000-0000-0000-000000000000","Date":"0001-01-01T00:00:00+00:00"},
  ...
]
```

Then open the file and enumerate through the items:
```cs
using var stream = File.OpenRead(jsonFilename);
await foreach (var item in JsonSerializer.DeserializeAsyncEnumerable<TestModel>(stream))
{
    // Do something with item
}
```

### Expected behavior

The application should succesfully iterate through each item in the json file with roughly constant memory usage.

### Actual behavior

Memory usage will climb until it exceeds the hard GC limit, and then an `OutOfMemoryException` will be thrown.

### Configuration

.NET 7, Windows 11 Pro x64

Originally encountered on: .NET 7, linux docker image mcr.microsoft.com/dotnet/aspnet:7.0-bullseye-slim

### Other information

After taking a memory snapshot, the following classes seem to be involved:

`System.Text.Json.Arguments<Guid, DateTimeOffset, Object, Object>`
  - Count: 1,692,988
  - Size: 108,351,232 bytes
  - Inclusive Size: 108,351,232 bytes

`System.Text.Json.ArgumentState`
  - Count: 1,692,988
  - Size: 121,895,136 bytes
  - Inclusive Size: 230,246,368 bytes

So perhaps something to do with caching in `System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`

**Comment by eiriktsarpalis** [comment]
Hi @MatElcome, thanks for the detailed report. Could you share the path that is causing these objects to be rooted?

**Comment by MatElcome** [comment]
> Hi @MatElcome, thanks for the detailed report. Could you share the path that is causing these objects to be rooted?

Certainly - the paths to root are:
```
Arguments<Guid, DateTimeOffset, Object, Object>	0
		ArgumentState	1570134
			ReadStackFrame[]	1
				JsonSerializer+<CreateAsyncEnumerableDeserializer>d__75<JsonOomExample.TestModel> [Local Variable]	1
			ArgumentState[]	1570134
				List<ArgumentState>	1
					JsonSerializer+<CreateAsyncEnumerableDeserializer>d__75<JsonOomExample.TestModel> [Local Variable]	1
```

**Comment by MatElcome** [comment]
Some further information: when I set a breakpoint in the `TestModel` constructor and go up the call stack, I can see `System.Text.Json.ReadStack._ctorArgStateCache` is a `List<ArgumentState>` with over 1,000,000 items in it.

**Comment by eiriktsarpalis** [comment]
The issue appears to be a flaw in the implementation of the `_ctorArgStateCache` implementation:

https://github.com/dotnet/runtime/blob/a39435f8e709dfc8f876943092ac905f028f513f/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/ReadStack.cs#L391-L411

There is no mechanism for popping `ArgumentState` entries once deserialization of an object with a constructor has completed, so this list will accumulate _all_ constructor argument states encountered in the deserialized object graph. This impacts all deserialization modes, not just `DeserializeAsyncEnumerable` and the size of the array is bounded by the size of the deserialized object graph. This is not a recent regression, it appears to have been that way since constructor-based deserialization was introduced.

A targeted fix would involve storing `ArgumentState` on the `ReadStackFrame` struct instead of using this "cache" list.

**Comment by eiriktsarpalis** [comment]
@berkansasmaz Thank you for volunteering. If this is your first issue, it might be a bit too tricky to pull off. I would recommend this to folks already familiar with the STJ codebase.

**Comment by berkansasmaz** [comment]
Got it, thanks for the recommendation then it would be better for someone else to handle it.
