### ISSUE TITLE
Make big endian, little endian chosable in BitConverter

### ISSUE THREAD

**Issue by compunited** [dotnet/runtime#80982]
Data from IoT devices is sometimes big endian sometimes little endian

We Like to write the code with Bitconverter because it makes it more readable to application developer

byte[] buffer2byte = new byte[2];
Array.Copy(bytes, i, buffer2byte, 0, 2);
Array.Reverse(buffer2byte);
var distanceInMm = BitConverter.ToInt16(buffer2byte);

the idea would be to have a overloading with an enum ByteFormat.LittleEndian

in that case it could be just var distanceInMm = BitConverter.ToInt16(bytes,i, ByteFormat.BigEndian);

**Comment by teo-tsirpanis** [comment]
You can use the methods in the [`System.Buffers.Binary.BinaryPrimitives`](https://learn.microsoft.com/en-us/dotnet/api/system.buffers.binary.binaryprimitives) class, which have little and big endian editions.

**Comment by compunited** [comment]
> You can use the methods in the [`System.Buffers.Binary.BinaryPrimitives`](https://learn.microsoft.com/en-us/dotnet/api/system.buffers.binary.binaryprimitives) class, which have little and big endian editions.

The idea is good, but in that case i cannot choose the startindex

**Comment by teo-tsirpanis** [comment]
You can write `BinaryPrimitives.ReadUInt16LittleEndian(myArray.AsSpan(idx))`.

**Comment by vcsjones** [comment]
This has been proposed in the past (see #25655, #22839) and been closed with the recommended solution being @teo-tsirpanis's response.

**Comment by tannergooding** [comment]
Right. We already expose the relevant APIs they just aren't in `BitConverter` because they were exposed in a new type as part of .NET Standard because the .NET Framework implementation couldn't be updated.

The relevant fix is to use the `BinaryPrimitives` API.
