### ISSUE TITLE
in async static method is formatting by using $"{DateTime.Now}"  is throwing Null exception in System.Buffer.Memmove 

### ISSUE THREAD

**Issue by pajacz** [dotnet/runtime#80995]
### Description

In async static method is formatting by using $"{DateTime.Now}"  is throwing Null exception in System.Buffer.Memmove.

Using Rider with .NET 7.0.0 on MacOS.

### Reproduction Steps

```
// this works ok
var now = DateTime.Now.ToString("yyyyMMddHHmmss_ffffff");
var fileName = $"{requestName}_{now}.json";
// NOTE: this has been throwing an Null exception in System.Buffer.Memmove 
// var fileName = $"{requestName}_{DateTime.Now:yyyyMMddHHmmss_ffffff}.json";
```

Works fine in STA console app. 

Doesn't work if called from ASP.NET controller async method e.g.:
`public async Task<IActionResult> FoodAsync()`
Doesn't matter if called as async or not, throws the same exception. 

### Expected behavior

To not to throw that exception.

### Actual behavior

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Buffer.Memmove(Byte& dest, Byte& src, UIntPtr len)
   at System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted(String value)
   at FcrTech.SendX.Core.Utils.RequestLogger.StoreRequestAsync(String logsPath, String requestName, Object data) in .....cs:line 50

### Known Workarounds

Replace:
 `$"{DateTime.Now:yyyyMMddHHmmss_ffffff}"`
by:
`DateTime.Now.ToString("yyyyMMddHHmmss_ffffff") `

### Configuration

.NET 7.0.0
MacOS 13.1 (22C65)
x64

**Comment by KeterSCP** [comment]
Seems like a duplicate of https://github.com/dotnet/runtime/issues/78991

**Comment by pajacz** [comment]
yes, it's the same. thanks @KeterSCP

**Comment by Clockwork-Muse** [comment]
Unrelated - 
@pajacz - if you're using ASP.NET, that implies you're writing server code, where the usual recommendation is to set/run the server in UTC, and use the ISO format (`"o"`).
