### ISSUE TITLE
Native AOT - unable to generate MAP files

### ISSUE THREAD

**Issue by JOULTICOA** [dotnet/runtime#80992]
Need a way to generate MAP files for the Native binaries output from Native AOT / dotnet CLI pretty please

This is useful for various reasons, one of which is 3rd party software protection like VMprotect

**Comment by jkotas** [comment]
You can pass any additional options to native linker via your .csproj file. Adding this to your .csproj will do the trick:

```
<ItemGroup>
  <LinkerArg Include="/MAP" />
</ItemGroup>
```

https://learn.microsoft.com/en-us/cpp/build/reference/map-generate-mapfile

**Comment by am11** [comment]
For cross-platform support:

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PublishAot>true</PublishAot>
    <StripSymbols>true</StripSymbols>
    <_CrossReferences Condition="'$(UseCrossReferences)' == 'true'">,--cref</_CrossReferences>
  </PropertyGroup>

  <ItemGroup>
    <LinkerArg Condition="$([MSBuild]::IsOSPlatform('windows'))" Include="/MAP:$(TargetName).map" />
    <LinkerArg Condition="$([MSBuild]::IsOSPlatform('osx'))" Include="-Wl,-map,$(TargetName).map" />
    <LinkerArg Condition="!$([MSBuild]::IsOSPlatform('windows')) and !$([MSBuild]::IsOSPlatform('osx'))"
      Include="-Wl,-Map,$(TargetName).map$(_CrossReferences)" />
  </ItemGroup>

</Project>
```

`--cref` does not work on macOS.

**Comment by JOULTICOA** [comment]
Unfortunately I am getting an error in VMprotect that the MAP file timestamp does not match / is invalid compared to the EXE

Is this a Native AOT issue or a VMProtect issue?

I guess I should use something like CFF explorer to see where the timestamp is in the header?

**Comment by JOULTICOA** [comment]
> 

I have confirmed using CFF explorer that the time stamp in EXE file and the MAP file do not match / MAP file is wrong

Is this expected behavior?
<img width="741" alt="Mismatch" src="https://user-images.githubusercontent.com/74837290/213903542-e048e8eb-518a-4354-b490-495a41229920.png">

**Comment by jkotas** [comment]
Make sure that you are looking at the native AOT compiled .exe. There are multiple .exes under bin directory. Small ~150kB one that uses shared runtime. The native AOT compiled one is several MBs.

**Comment by JOULTICOA** [comment]
> Make sure that you are looking at the native AOT compiled .exe. There are multiple .exes under bin directory. Small ~150kB one that uses shared runtime. The native AOT compiled one is several MBs.

Yes I am looking at the Giant native one, and its MAP file in same folder

\bin\Release\net7.0-windows\win-x64\native

For now I just manually edit MAP file to match, just not sure if it is intended behavior or not

**Comment by jkotas** [comment]
I do not see different stamps. 

The difference between the two timestamps in your screenshot is 650 seconds. My guess is that you have done multiple builds and the binary and the map file are from different builds. Try deleting obj and bin directories and doing a fresh build.

**Comment by JOULTICOA** [comment]
> I do not see different timestamps.
> 
> The difference between the two timestamps in your screenshot is 650 seconds. My guess is that you have done multiple builds and the binary and the map file are from different builds. Try deleting obj and bin directories and doing a fresh build.

Thanks, deleting obj and bin worked.  after I did that, it started creating the map file in the root of project folder instead (which is what it should have been doing all along based on the argument).

It had gotten crusty somehow

**Comment by am11** [comment]
> it started creating the map file in the root of project folder

Updated the sample csproj above so it generates map file next to binary in the publish directory.

Default location is `bin/Release/{TFM}/{RuntimeIdentifier}/publish`, you can override it during publish.
e.g. `dotnet publish -o dist -c Release` will generate final binary and map file in `.\dist\` directory.
