### ISSUE TITLE
Enable building NativeAOT for Apple mobile platforms

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/runtime#81024]
## Description

dotnet/runtime currently does not support building NativeAOT subset (framework, SDK libraries and tools) for iOS platforms. Additionally, building an appropriate runtime NuGet package for these platforms is also unavailable. 

Enable building NativeAOT subset and creating matching runtime NuGet packages for the following set of platforms (target operating system and architecture combinations):
- iOS/tvOS (arm64)
- iOS/tvOS Simulator (x64, arm64)
- MacCatalyst (x64, arm64)

The feature should be conditionally included by introducing appropriate preprocessor directives

Remaining tasks:

- [x] Enable building the NativeAOT runtime - https://github.com/dotnet/runtime/pull/81780
- [x] #82389
- [x] #80911
- [x] Add runtime packs for the platforms - https://github.com/dotnet/runtime/pull/85047

**Comment by ivanpovazan** [comment]
@akoeplinger 
I was going through the tasks, listed in the issue description, and had a question regarding:
> [ ] Properly implement targeting these platforms rather than pretending to be macOS

Were you referring to this workaround (and what is brings along): https://github.com/dotnet/runtime/blob/8f19f4ebd511994be27a2e1f4c88424a26f91e7c/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs#L3066

**Comment by akoeplinger** [comment]
@ivanpovazan yes, and that also has corresponding implications on the native side. When I initially tried this I was getting asserts in the ILCompiler so we'll probably need a bit of help from the NativeAOT side.

**Comment by ivanpovazan** [comment]
The remaining task:
> - [ ] Properly implement targeting these platforms rather than pretending to be macOS

is tracked separately in the top-level tracking issue as it is identified as an improvement.

Closing this issue as all other tasks are completed.
