### ISSUE TITLE
System.IO.Ports.SerialPort 7 no longer throws TimeoutException but System.IO.IOException with message mentioning timeout

### ISSUE THREAD

**Issue by hugo-lyppens** [dotnet/runtime#81035]
### Description

System.IO.Ports.SerialPort 7 no longer throws TimeoutException but System.IO.IOException with message mentioning timeout.

This problem did not occur in .NET 6 version

### Reproduction Steps

read bytes from SerialPort and set timeout to 5 seconds

### Expected behavior

When reading from the serial port takes longer than the timeout, I expect an exception of type System.Timeout

### Actual behavior

System.IO.IOException with message containing  "timeout period expired"

### Regression?

yes it worked in version 6 of SerialPort.

### Known Workarounds

In addition to catching System.Timeout, also catch System.IO.IOException and check message containing  "timeout period expired"

**Comment by vcsjones** [comment]
This looks like a duplicate of https://github.com/dotnet/runtime/issues/80079.

**Comment by krwq** [comment]
It is in fact duplicate of #80079
