### ISSUE TITLE
[API Proposal]: Add timeout data to CancellationToken to retrieve the cancellation timeout passed to CTS.CancelAfter

### ISSUE THREAD

**Issue by mconnew** [dotnet/runtime#81045]
### Background and motivation

WCF throws exceptions on timeout, and as part of the timeout message thrown, we include the original timeout value that was used. The class which throws the timeout will be part of a composite operation up the call stack so the timeout isn't locally known. To work around this, we've created a custom CancelletionTokenSource (CTS) which returns the timeout via GetHashCode. CancellationToken.GetHashCode defers to CTS.GetHashCode so we recover this value from CancelletionToken.GetHashCode. We can't switch to/add CancellationToken on our public api's between channel layers as we can't depend on being able to recover the timeout.  
Knowing the original timeout is also needed for our backoff helper. When we can't connect to a named pipe, we wait a short time and retry, and keep doubling the timeout with each retry. We have code to do the final retry just before the timeout is due to fire. We couldn't use CancellationToken as we don't know the overall time out until after it's fired. As the timeout is passed in over public api, we can't use our timeout recovery trick.

### API Proposal

```csharp
namespace System.Threading;

public struct CancellationToken
{
    public TimeSpan? CancelAfterDuration { get; }
    public TimeSpan? CancellationDurationRemaining { get; }
}

public class CancellationTokenSource
{
    public TimeSpan? CancelAfterDuration { get; }
    public TimeSpan? CancellationDurationRemaining { get; }
}
```
I'm also proposing an API to know how much time is left.  This is helpful for scenarios such as when having a retry backoff algorithm when the method is part of a larger composite operation and the remaining time left could be significantly less than the original cancellation duration. I proposed nullable values from when using a non-cancellable token or a CTS which hasn't had CancelAfter called yet.

### API Usage

```csharp
public Task DoSomeThingAsync(CancellationToken cancellationToken)
{
    try
    {
        await DoSomeIOAsync(cancellationToken);
    }
    catch(OperationCancelledException oce}
    {
        TimeSpan timeout = oce.CancellationToken.CancelAfterDuration.HasValue ?
            oce.CancellationToken.CancelAfterDuration.Value : Timeout.InfiniteTimeSpan; // Or could use a default value
        throw new TimeoutException(SR.Format(SR.DoingSomethingTimeoutException, timeout);
    }
}
```

### Risks

A tiny increase in cost when calling CancelAfter(int timeout) as a TimeSpan will need to be created. Also DateTime.UtcNow will need to be called to store original set time so that remaining time can be calculated. I believe this will be negligible compared with the cost of registering a timer.

There will be some slightly confusing behavior when using a Linked cancellation token. You could calculate a reasonable value for CancellationDurationRemaining as you take the minimum value of all linked tokens, but that's only useful for some scenarios. You can't recover the original timeout. You could still get unusual behavior if one of linked tokens hasn't had a cancellation time set yet as that can be set later. This is no different than a CancellationTokenSource which can have CancelAfter called repeatedly. A consumer should expect that the value can be changed later. For example, the backoff retry example I gave would need to check the remaining time on each iteration to be correct.

**Comment by stephentoub** [comment]
Thanks for the suggestion.  We've considered such support multiple times in the past and declined to do so, e.g. https://github.com/dotnet/runtime/issues/59312.  All of the reasoning there still applies.  I'm going to close this as a duplicate.
