### ISSUE TITLE
[Proposal]: Add ZZZ date/time format specifier

### ISSUE THREAD

**Issue by IanKemp** [dotnet/runtime#81040]
[The `zzz` date/time format specifier always uses the colon character as the separator, instead of `DateTimeFormatInfo.TimeSeparator`.](https://github.com/dotnet/runtime/issues/31458) We cannot change this behaviour because it would break backwards compatibility, so instead I'm proposing to add a new [date/time format specifier](https://learn.microsoft.com/dotnet/standard/base-types/custom-date-and-time-format-strings) to cover this:

`ZZZ`: would function exactly the same as `zzz` does currently, but use `DateTimeFormatInfo.TimeSeparator` instead of colon

Example (taken from the linked issue):

```csharp
var dotSeparatedCulture = new CultureInfo(string.Empty)
{
    DateTimeFormat = { TimeSeparator = "." },
};
var result = DateTime.UtcNow.ToString("ZZZ", dotSeparatedCulture);
Assert.AreEqual("+00.00", result); // true
```

**Comment by tarekgh** [comment]
@IanKemp where you want to use this new format? Using the `:` in the UTC offset is a kind of standard separator. Changing that can produce some confusion.

**Comment by IanKemp** [comment]
> @IanKemp where you want to use this new format? Using the `:` in the UTC offset is a kind of standard separator. Changing that can produce some confusion.

The fact that every other format specifier respects `TimeSeparator` while `zzz` does not, strongly suggests that `zzz`'s behaviour is incorrect. This proposal allows for an opt-in to correct behaviour going forward, while not breaking existing applications.

**Comment by tarekgh** [comment]
> The fact that every other format specifier respects TimeSeparator while zzz does not, strongly suggests that zzz's behaviour is incorrect. 

I don't think there is anyone expect different separator for the UTC offset part. If we find a demand and real cases need that, we can consider the proposal. For now, I am closing the issue. Thanks, for your report.
