### ISSUE TITLE
[API Proposal]: CollectionsMarshal as extension method

### ISSUE THREAD

**Issue by Thaina** [dotnet/runtime#81067]
### Background and motivation

CollectionsMarshal class name is verbose and somehow hidden so much so forgettable. So I think it would be better if it just become easily accessible with the class it was responsible for directly

### API Proposal

```csharp
using System.Runtime.InteropServices;

namespace System.Collections.Generic

public static class CollectionsMarshalExt
{
    public Span AsSpan<T>(this in List<T> item) => CollectionsMarshal.AsSpan(item);
    public ref T GetValueRefOrNullRef<K,V>(this in Dictionary<K,V> item,in K key,out bool existed) => CollectionsMarshal.GetValueRefOrNullRef(item,key,out existed);
    public ref T GetValueRefOrAddDefault<K,V>(this in Dictionary<K,V> item,in K key,out bool existed) => CollectionsMarshal.GetValueRefOrAddDefault(item,key,out existed);
}
```

Also, is it possible to add `out bool existed` on `GetValueRefOrNullRef` too ?

### API Usage

```csharp
var dict = new Dictionary<string,int>();
public int? CalculateFromKey(string key)
{
    ref int i = dict.GetValueRefOrNullRef(key,out bool existed);
    if(!existed)
        return null;

    return i * i;
}
```

**Comment by Thaina** [comment]
Another thing I am curious if it already exist, do we have any functionality to iterate both key and value of dictionary by ref at the same time? If it not I would like to propose this functionality too

**Comment by davidfowl** [comment]
These methos aren't extension methods for a reason. So that they don't show up by default because they are advanced APIs that only need to be used in rare cases where performance is paramount.

**Comment by Thaina** [comment]
I see, thank you for your clarification

Still I would like to argue that performance should be default feature. Are there any reason these method are not safe to use in common use case?

**Comment by stephentoub** [comment]
> Are there any reason these method are not safe to use in common use case?

Yes, these are the reasons they're on a "Marshal" class, as they expose internal implementation details that make them unsafe in some fashion. For example, refs into a dictionary will point into logical garbage if the dictionary resizes after getting the ref.

**Comment by Thaina** [comment]
Thank you very much
