### ISSUE TITLE
Change the default package for the "Used By" section on GitHub

### ISSUE THREAD

**Issue by ldeluigi** [dotnet/runtime#81078]
#### The current selected default is Dynamic.
![image](https://user-images.githubusercontent.com/44567586/214281882-48c75cd8-d0e8-48c3-b269-3d424841f5f9.png)

#### Sugegsted Solution
I suggest Microsoft.CSharp or System.IO

### Reference
https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/exploring-the-dependencies-of-a-repository#changing-the-used-by-package

**Comment by stephentoub** [comment]
> The current selected default is Dynamic.

Why is that a problem?

**Comment by teo-tsirpanis** [comment]
> I suggest Microsoft.CSharp or System.IO

The problem is that these packages are outdated as well. In fact no package is required to install to use .NET and therefore would represent its popularity. The best solution would be to hide this "Used by" section but there isn't currently a way.

**Comment by ldeluigi** [comment]
> > I suggest Microsoft.CSharp or System.IO
> 
> The problem is that these packages are outdated as well. In fact no package is required to install to use .NET and therefore would represent its popularity. The best solution would be to hide this "Used by" section but there isn't currently a way.

Sure but at least they would be a hint of the popularity in the meantime that GitHub allows hiding it?

**Comment by teo-tsirpanis** [comment]
They would be a hit list of repositories to open PRs to remove them. 😛 These packages (especially the latter) should not be referenced by modern .NET; and even `Microsoft.CSharp` is intended for limited scenarios revolving around the `dynamic` keyword and on .NET Standard.

**Comment by ldeluigi** [comment]
The hit list is already there it would just be another link to it... but ok I see your point on the last statement... what do you suggest?

**Comment by stephentoub** [comment]
It's been changed.
