### ISSUE TITLE
PendingAmbientTransaction exception thrown even though it was completed before

### ISSUE THREAD

**Issue by jakubmartinik** [dotnet/runtime#81072]
### Description

When using transaction scope, sometimes I get an error that the transaction was not completed even though I called complete. 
Steps to reproduce:
1) Create transaction scope
2) Make changes in database
3) Send message to service bus
4) Complete transaction
5) Dispose transaction
6) Call any query in database

What happens is that when I make the last step, making a DB call,  Open method in RelationConnection class is called from which HandleAmbientTransactions method is called. In this method, there is a check if ambient transaction exists by checking if the item exists in the _ambientTransactions field. The transaction should have been removed when I called Complete on the transaction scope, there is a method HandleTransactionCompleted that should take care of it but this method is sometimes called later than the check for the ambient transaction and therefore the exception is thrown.

I created a small repo to reproduce the problem. 

https://github.com/jakubmartinik/TransactionScope/blob/main/ConsoleApp1/Program.cs

If there is a bit of delay between completing the transaction and calling the following query, the exception is not thrown.

https://github.com/jakubmartinik/TransactionScope/blob/delay/ConsoleApp1/Program.cs

Thank you in advance for taking a look at this issue.

**Comment by jakubmartinik** [comment]
Any progress?

**Comment by roji** [comment]
@jakubmartinik apologies for taking so long to answer, this slipped under my radar.

When using TransactionScope to manage distributed transactions, calling TransactionScope.Complete doesn't actually perform any commits; it merely signals completion to the transaction manager, which then asynchronously manages committing across the different resource managers. In other words, the 2-phase-commit mechanism is ultimately asynchronous, and the actual TransactionComplete event may be fired after an arbitrary delay ([note this comment](https://github.com/dotnet/efcore/blob/main/src/EFCore.Relational/Storage/RelationalConnection.cs#L850) in the RelationalConnection sources).

If you want your code to actually wait until the event is fired, you'll need to manage that yourself using synchronization, e.g. have your code wait on a SemaphoreSlim which gets released from a handler on the transaction's TransactionComplete event.

**Comment by SamMonoRT** [comment]
@jakubmartinik - Hope the above suggestion helped and you are unblocked. Closing this issue. Please re-open if necessary
