### ISSUE TITLE
JIT optimization: loop head alignment

### ISSUE THREAD

**Issue by JosephTremoulet** [dotnet/runtime#8108]
(I'm creating tracking issues for some optimizations that RyuJit doesn't perform, so we'll have a place to reference/note when we see the lack of them affecting particular benchmarks)

This one actually has an implementation plumbed through, but it's triggered only by the unsupported `COMPlus_JitAlignLoops` flag.  It should probably be enabled by default in at least some configurations/methods.

category:cq
theme:loop-opt
skill-level:expert
cost:medium

**Comment by kunalspathak** [comment]
This has been enabled for x86/x64 by https://github.com/dotnet/runtime/pull/44370.
