### ISSUE TITLE
System.Text.Json unable to deserialize an object that implement IEnumerable but is itself not a list

### ISSUE THREAD

**Issue by RyanGaudion** [dotnet/runtime#81084]
### Description

JsonSerializer.Deserialize is unable to deserialize a class that contains it's own properties will also implementing IEnumerable

### Reproduction Steps

Please see the test code here:

```
    public class UnitTest1
    {
        [Fact]
        public void Test1()
        {
            string validJson = @"
{
    ""List1"": [{""Test"": ""a""}],
    ""List2"": [{""Test"": ""a""}]
}";

            MyClass obj = JsonSerializer.Deserialize<MyClass>(validJson);

        }
    }
    class MyClass //: IEnumerable<TestClass>
    {
        public List<TestClass> List1 { get; set; } = new List<TestClass>();
        public List<TestClass> List2 { get; set; } = new List<TestClass>();

        public IEnumerator<TestClass> GetEnumerator()
        {
            return List1.Concat(List2).GetEnumerator();
        }
        //IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
    }

    class TestClass
    {
        public string Test { get; set; }
    }
```
This code passes, but when uncommenting out the 2 comments in MyClass - the tests then fail.

### Expected behavior

I expected adding an interface and method to an object to not effect it's ability to be deserialized

### Actual behavior

The deserialization fails with this error `System.Text.Json.JsonException : The JSON value could not be converted to MyClass. Path: $ | LineNumber: 1 | BytePositionInLine: 1.`

**Comment by krwq** [comment]
You'll need to implement CustomConverter for your type.

The reason this is not serializable is following:
- anything implementing IEnumerable will be by default serialized/deserialized as an array and not as object - currently there is no good workaround for that (#63791 or #77018 should fix that but it's not planned for near future)
- deserializer doesn't know how to add values to your collection (since you're implementing IEnumerable assumption is that it should deserialize from array and deserializer needs to add elements somehow)

**Comment by krwq** [comment]
Marking as `needs-author-action` because given current information we should close this issue as duplicate. Please close or add further details (bot will automatically close this issue if there is no response)

**Comment by RyanGaudion** [comment]
@krwq thank you for the reference to #63791. This looks like it'll resolve the issue. Is there any workaround to get an implementation like #63791 working with a custom converter? If so, what would this converter look like?

**Comment by krwq** [comment]
Implementation could look something like this (done very minimal testing on that, just showing idea):

```csharp
class MyClassConverter : JsonConverter<MyClass>
{
    public override MyClass? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        MyClass obj = new();

        while (reader.TokenType != JsonTokenType.EndObject)
        {
            if (reader.TokenType == JsonTokenType.PropertyName)
            {
                string? propertyName = reader.GetString();
                reader.Read();
                List<TestClass>? list = JsonSerializer.Deserialize<List<TestClass>>(ref reader, options);
                if (propertyName == nameof(MyClass.List1))
                {
                    obj.List1 = list;
                }
                else if (propertyName == nameof(MyClass.List2))
                {
                    obj.List2 = list;
                }
                else
                {
                    // we ignore unknown properties by default
                }
            }

            reader.Read();
        }

        return obj;
    }

    public override void Write(Utf8JsonWriter writer, MyClass value, JsonSerializerOptions options)
    {
        writer.WriteStartObject();
        writer.WritePropertyName(nameof(MyClass.List1));
        JsonSerializer.Serialize(writer, value.List1, options);
        writer.WritePropertyName(nameof(MyClass.List2));
        JsonSerializer.Serialize(writer, value.List2, options);
        writer.WriteEndObject();
    }
}
```
