### ISSUE TITLE
Getting MetadataType attributes through MemberInfo.GetCustomAttributes(true)

### ISSUE THREAD

**Issue by lokitech** [dotnet/runtime#81089]
### Description

So as seen here https://github.com/dotnet/runtime/pull/51772 @Xaeco made a commit to .net 6 that made possible to inherit MetadataType attributes with:

`TypeDescriptor.AddProviderTransparent( new AssociatedMetadataTypeTypeDescriptionProvider(typeof(MyClass), typeof(MyMetadataType)), typeof(MyClass));`

Which works perfectly fine. 

BUT the problem is when trying to access those attributes through MemberInfo.GetCustomAttributes(true), as it returns an empty list. 

Is there a way to access MetadataType attributes through reflection?

### Reproduction Steps

```
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Reflection;

public class Person
{
    public string Name { get; set; } = string.Empty;
}

public class PersonMetadata
{
    [Display(Name = "PersonName")]
    public string Name { get; set; } = string.Empty;
}

class Program
{
    static void Main(string[] args)
    {
        TypeDescriptor.AddProviderTransparent(
            new AssociatedMetadataTypeTypeDescriptionProvider(typeof(Person), typeof(PersonMetadata)),
            typeof(Person));

        var person = new Person();
        var type = typeof(Person);
        var member = type.GetMember("Name").FirstOrDefault();
        var attribute = member!.GetCustomAttribute(typeof(DisplayAttribute), true) as DisplayAttribute;
        Console.WriteLine($"Display Name = {attribute?.GetName()}");
    }
}
```

### Expected behavior

Display Name = PersonName

### Actual behavior

Display Name = 

### Configuration

.NET Core 6

**Comment by steveharter** [comment]
> Is there a way to access MetadataType attributes through reflection?

I don't think so -- closing issue; please re-open if you are aware of other TypeDescriptor cases that support the existing reflection methods.

You'll need to go through the TypeDescriptor like
`TypeDescriptor.GetProperties(typeof(Person)).Cast<PropertyDescriptor>().Select(p => p.Name).ToArray()`;
