### ISSUE TITLE
Strange behavior when type matching on arrays of enums

### ISSUE THREAD

**Issue by tkreindler** [dotnet/runtime#81102]
### Description

We have similar code to the following that needs to handle serializing arbitrary object types in our code:

<pre><code>string SerializeObject(object value)
{
    switch (value)
    {
        case System.Enum typed:
            return typed.ToString();

        case int typed:
            return typed.ToString();

        case System.Enum[] typed:
            return ArrayToString(typed.Select(x => x.ToString()));

        case int[] typed:
            return ArrayToString(typed.Select(x => x.ToString()));

        ... other types ...
    }
}</code></pre>

For int, int[], and any enum this code works as expected going to the correct corresponding statement.

For an array of enums however it's getting picked up as an int[] which leads to incorrect serialization behavior in this code. Is there any correct way to type match on an array of enums or is using reflection the only way?

### Reproduction Steps

Code above should reproduce.

### Expected behavior

An array of enums would get matched as such.

### Actual behavior

It's getting matched as an array of integers.

### Known Workarounds

Using reflection with Type.IsArray and Type.GetElementType().IsEnum.

### Configuration

-  .Net 6.0.400
- Windows 11 22H2
- x64
- Seems very unlikely to be specific to this configuration although I haven't tested in others.

**Comment by jkotas** [comment]
There is no way to match array of any (unboxed) enum. There is no type that can represent array of any (unboxed) enum. `Enum[]` represents array of boxed enums that is not assignable to an array of unboxed enums.
