### ISSUE TITLE
[API Proposal]:  add RegexParseError.EmptyCharacterClass

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#81110]
### Background and motivation

`Regex.IsMatch("foo", "[]")` produces `RegexParseException: Invalid pattern '[]' at offset 2. Unterminated [] set.`. 

This isn't, of course, accurate. The parser was just written such that both cases end up the same place and we missed that in https://github.com/dotnet/runtime/issues/372

We expose the type of parse error as an enum value on RegexParseException.Error. The message above corresponds to the value RegexParseError.UnterminatedBracket. To fix this to be an accurate message, we would need to extend that enum.

(I accept this is low priority, as it is correct that it's rejected, and it's obvious what the problem is.)

### API Proposal

```csharp
namespace System.Text.RegularExpressions;

    public enum RegexParseError
    {
           // existing entries
           EmptyCharacterClass = 32,
    }
```

### API Usage

purely internal -- we would tweak the parser to throw RegexParseException with an Error of RegexParseError.EmptyCharacterClass for this particular case.

### Alternative Designs

none

### Risks

none

**Comment by stephentoub** [comment]
> This isn't, of course, accurate.

It's a matter of perspective.  It actually is an unterminated set, as the `]` immediately after the `[` is interpreted as a member of the set.  For example, `[]123]` is a set containing four characters, `]`, `1`, `2`, and `3`.  So the parser is correctly reporting that it's parsed a set so far containing `]` and it then hits the end of the pattern without finding a set terminator.  According to regex101, other engines (PCRE, Java, go, Python) all behave similarly and report a similar error "Character class missing closing bracket".

**Comment by danmoseley** [comment]
Interesting. I didn't check other engines. This isn't worth pursuing I think
