### ISSUE TITLE
System.Text.Json.SourceGeneration.SourceGenerator failed to generate with custom array attribute value on property

### ISSUE THREAD

**Issue by sake402** [dotnet/runtime#81124]
### Description

Given as POCO class with custom atribute on it, the generator fails if any of the attribute value is an array

### Reproduction Steps

This works
```C#
 public class AAttribute : Attribute
    {
        public string[] Options { get; set; }
    }
    public class A
    {
        [A] //custom attribute with no value
        public int AB { get; set; }
    }

    [JsonSerializable(typeof(A))]
    internal partial class AJsonContext : JsonSerializerContext
    {
    }
```

But this fails with `` Generator 'JsonSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidOperationException' with message 'TypedConstant is an array. Use Values property.'``
```C#
 public class AAttribute : Attribute
    {
        public string[] Options { get; set; }
    }
    public class A
    {
        [A(Options = new[] {  "1" })] //custom attribute with an array value
        public int AB { get; set; }
    }

    [JsonSerializable(typeof(A))]
    internal partial class AJsonContext : JsonSerializerContext
    {
    }
```

Seems the exception is thrown from roslyn here
[https://github.com/dotnet/roslyn/blob/6acaa7b7c0efea8ea292ca26888c0346fbf8b0c1/src/Compilers/Core/Portable/Symbols/TypedConstant.cs#L99](https://github.com/dotnet/roslyn/blob/6acaa7b7c0efea8ea292ca26888c0346fbf8b0c1/src/Compilers/Core/Portable/Symbols/TypedConstant.cs#L99)

### Expected behavior

Should not even be trying to process an attribute that is not STJ defined. And if it has o should no throw exception on it.

### Actual behavior

Reading an array value attribute as Value causes exception

**Comment by krwq** [comment]
I think it's something we should consider fixing in 8.0 given we expect the usage of source-gen might be more common. @sake402 any chance you'd be interested in creating a fix?

**Comment by mb-to** [comment]
A common case for me is to use the Swashbuckle.AspNetCore.Annotations.SwaggerSchema which causes this issue.

**Comment by eiriktsarpalis** [comment]
This was fixed by https://github.com/dotnet/runtime/pull/86334 in .NET 8 Preview 5.
