### ISSUE TITLE
WASM build broken on main

### ISSUE THREAD

**Issue by kg** [dotnet/runtime#81136]
Some time after commit 98629a19442f33ed727701ff4728f3a98545de80, wasm builds on main broke for me with this error:

`
/home/kate/Projects/dotnet-runtime-wasm/src/mono/wasm/wasm.proj(95,5): error MSB4062: The "Microsoft.WebAssembly.Build.Tasks.RunWithEmSdkEnv" task could not be loaded from the assembly /home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/WasmAppBuilder/Debug/net8.0/WasmAppBuilder.dll. Index not found. (0x80131124) Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
`

This persists even if I delete `artifacts` and `.dotnet`.

**Comment by radical** [comment]
Did you hit this again?

**Comment by kg** [comment]
It's similar, but has a different pair of errors:
```
/home/kate/Projects/dotnet-runtime-wasm/src/mono/nuget/Microsoft.NET.Workload.Mono.Toolchain.net6.Manifest/Microsoft.NET.Workload.Mono.Toolchain.net6.Manifest.pkgproj(49,5): error MSB4062: The "GenerateFileFromTemplate" task could not be loaded from the assembly /home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/WorkloadBuildTasks/Debug/net8.0/WorkloadBuildTasks.dll. Culture is not supported. (Parameter 'name') /home/kate/Projects/dotnet-runtime-wasm/src/mono/nuget/Microsoft.NET.Workload.Mono.Toolchain.net6.Manifest/Microsoft.NET.Workload.Mono.Toolchain.net6.Manifest.pkgproj(49,5): error MSB4062: $ is an invalid culture identifier. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
```

**Comment by marek-safar** [comment]
@radical can this be closed now?
