### ISSUE TITLE
Verify `TarWriter.TarEntry(fileName, entryName)` behavior if user owner and device numbers cannot be retrieved

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#81144]
We fixed https://github.com/dotnet/runtime/pull/81070 which was an issue in `TarWriter.WriteEntry(string fileName, string entryName)`  where the method would crash if we attempted to add a file to an archive whose group owner name did not exist in the platform. This is the line that we fixed: [TarWriter.Unix.cs#L85](https://github.com/dotnet/runtime/blob/1bcd55a51ad8be98a07d2e407ff0e2d6e4d374ad/src/libraries/System.Formats.Tar/src/System/Formats/Tar/TarWriter.Unix.cs#L85)

Need to verify these two other locations:

- What if the user owner gets deleted from the system?: [TarWriter.Unix.cs#L76](https://github.com/dotnet/runtime/blob/1bcd55a51ad8be98a07d2e407ff0e2d6e4d374ad/src/libraries/System.Formats.Tar/src/System/Formats/Tar/TarWriter.Unix.cs#L76). I don't know if Unix systems would change the user owner of files if that user gets deleted. Need to test it.
  - **Edit**: The behavior is OK, I added tests to verify it: https://github.com/dotnet/runtime/pull/83126 and https://github.com/dotnet/runtime/pull/83267

- What if we have a problem retrieving device major and minor?: [TarWriter.Unix.cs#L58](https://github.com/dotnet/runtime/blob/1bcd55a51ad8be98a07d2e407ff0e2d6e4d374ad/src/libraries/System.Formats.Tar/src/System/Formats/Tar/TarWriter.Unix.cs#L58). This case is probably fine to let it crash. If we are trying to add a block device or a character device, and we cannot retrieve its two essential numbers (device minor and minor), then it's probably ok to continue crashing.

The other two places in that same method that are ok to crash if they fail is when we do the `lstat` and when we create the `FileStream` for a regular file.

cc @jeffhandley

**Comment by ViktorHofer** [comment]
According to the second point, if a crash occurs during retrieving the device major and minor then we can revisit issue.
