### ISSUE TITLE
NativeAOT and ILLink should fetch PDBs for inputs

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#81140]
When publishing, it doesn't look like NativeAOT or ILLink fetch PDBs for the input assemblies, but the output will not match up to the original PDBs (they need to be rewritten). We should write a utility to try to fetch the PDBs and run it during the build.

**Comment by vitek-karas** [comment]
This is basically a dupe of https://github.com/dotnet/sdk/issues/12962.

**Comment by agocke** [comment]
Agreed, closing as dup.
