### ISSUE TITLE
Kestrel process creating multiple threads.

### ISSUE THREAD

**Issue by satya-jugran** [dotnet/runtime#81149]
I have hosted an Asp.Net 6 Core web app on Linux and started as daemon service. It works fine.
However, when I see the thread information, it shows me 6 instances of same service threads (as shown in the screenshot below).

![image](https://user-images.githubusercontent.com/9986730/214353114-c0b15340-d770-4a94-bd6c-e87c8545cf1f.png)

I was expecting it to be a single threaded process only. 

Is this a Kestrel's behavior?
Is there any way I can configure it to be a single threaded process only?

Problem : We have a custom implementation of thread pooling so that we can configure how to configure concurrency based on our requirements. But because of this Kestrel's multithreaded behaviour, it is creating a thread pool starvation because now there are multiple thread pools of each WebApi instances.

**Comment by mangod9** [comment]
there are various components within the runtime which will create threads internally (like GC, finalizer) etc. Why is multiple threads a problem for you? Thx!
