### ISSUE TITLE
Platform Specifications Should Match Casing Among All Build Scripts

### ISSUE THREAD

**Issue by ivdiazsa** [dotnet/runtime#81141]
### Description

Recently, a conversation about making all platform ID's in build scripts lowercase was revived in PR #80164. However, the lack of uniformity can lead to unexpected and wrong behavior to unsuspecting developers passing flags directly to MSBuild when using other scripts, like for example `eng/common/build.sh`.

### Reproduction Steps

See this example:

1) Build CLR and Libs:

```bash
./build.sh -s clr+libs -c Release
```

2) Generate the test layout and build some tests:

```bash
./src/tests/build.sh -x64 -release -generatelayoutonly
./src/tests/build.sh -x64 -release -test:JIT/Methodical/Methodical_d2.csproj
```

3) Generate the Merged Payloads for Helix locally:

```bash

./eng/common/msbuild.sh src/tests/Common/helixpublishwitharcade.proj -maxcpucount -bl -p:TargetArchitecture=x64 -p:TargetOS=Linux -p:TargetOSSubgroup= -p:Configuration=Release
```

### Expected behavior

The Merged Payloads are generated in the same folder as the test builds.

### Actual behavior

After running the last command, checking in under `artifacts/tests/coreclr`, there will be two variants of the same results folder:
- Linux.x64.Release
- linux.x64.Release

The test builds will be under `linux` and the Merged Payloads will be under `Linux`. Consequently, the Merged Payloads will be empty since no tests were found under that path.

### Regression?

Yes, but according to the discussions in #80164 and other issues linked there, the lowercase behavior added in that PR is the one that the scripts ought to adopt.

### Known Workarounds

Pass `-p:TargetOS=linux` instead of `-p:TargetOS=Linux`.

### Other information

While this is not breaking by any means, at least for the time being, it can be very deceiving how many configuration options are case-insensitive (or are converted to a certain case behind curtains), and then suddenly one becomes case-sensitive. This confusion becomes more apparent when we consider the platform string is expected to be lower case, and all MSBuild properties are Pascal Case.

**Comment by ViktorHofer** [comment]
> Yes, but according to the discussions in https://github.com/dotnet/runtime/pull/80164 and other issues linked there, the lowercase behavior added in that PR is the one that the scripts ought to adopt.

I tried to cover all possible cases and scripts in that PR but based on the huge number of files using the TargetOS property, I might have missed a place. @ivdiazsa as you assigned yourself, I assume you will send a fix?

**Comment by ivdiazsa** [comment]
I don't currently have a fix ready but I assigned myself because I'm willing to work on it. However, if you or anyone else has a fix ready, feel free to submit it.
