### ISSUE TITLE
[Tracking] CoreCLR support for InlineArrayAttribute

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#81145]
This issue tracks the work for implementing CoreCLR support for `InlineArrayAttribute` #61135 and the related C# features such as `params ReadOnlySpan`, safe fixed size buffers, stackalloc of reference types, etc.

Required work:

- [x] Implement struct layout support for `InlineArrayAttribute` - https://github.com/dotnet/runtime/pull/82744
- [ ] Implement diagnostics support for structs with an `InlineArrayAttribute`
- [ ] #86572

**Comment by AaronRobinsonMSFT** [comment]
This follows from the Mono tracking issue https://github.com/dotnet/runtime/issues/80798

/cc @mangod9

**Comment by mangod9** [comment]
@VSadov assume this is ok to close?

**Comment by AaronRobinsonMSFT** [comment]
> @VSadov assume this is ok to close?

I don't think either of the two open check boxes are complete.

**Comment by mangod9** [comment]
@VSadov, is this on your radar to finish in 8?

**Comment by VSadov** [comment]
I was just looking at this. I do not think there are any showstoppers here. 

The marshaling part mentions that for 8.0 it could be just a documentation matter and later we can see if more is needed. 
The “implement diagnostics” is very vague. Should that be an issue on VS/debugger? Do we have diagnostics support for `Span<T>`, just as an example?

I think we can close this or move to 9.0 to follow up as we see more use of the feature and it becomes more clear what can be improved.

**Comment by mangod9** [comment]
Closing this based on the comment above. We can create new issues as required to track remaining work.
