### ISSUE TITLE
Inconsistent behavior in List<T> LastIndexOf(T, int, int) for an empty list.

### ISSUE THREAD

**Issue by csturm83** [dotnet/runtime#8117]
## Repro
```csharp
static void Main(string[] args)
{
    string[] arr = new string[] { };
    List<string> list = new List<string> { };
    Console.WriteLine(list.LastIndexOf("A", 0, 1));  // should throw here
    Console.WriteLine(Array.LastIndexOf(arr, "A", 0, 1));  // throws here
    Console.ReadLine();
}
```

## Expected
Both list.LastIndexOf(T, int, int) and Array.LastIndexOf(Array, T, int, int) throw an ArgumentOutOfRangeException for an invalid count parameter (similar to the IndexOf(T, int, int) overloads).

## Actual
list.LastIndexOf(T, int, int) returns -1.
Array.LastIndexOf(Array, T, int, int) throws ArgumentOutOfRangeException

Also exists in .NET Framework back to 2.0

**Comment by danmosemsft** [comment]
This should be an issue or PR in dotnet/docs if it's causing confusion.
