### ISSUE TITLE
NativeAOT: Dependency analysis support for generic method reflection

### ISSUE THREAD

**Issue by hez2010** [dotnet/runtime#81204]
I hope ILCompiler dependency analysis can take generic pattern into account so that we don't need `rd.xml` for this case any longer:

```csharp
// Here we have System.Array.IndexOf<System.Int32>(System.Int32[],System.Int32)
var method = typeof(Array).GetTypeInfo().GetMethod(nameof(Array.IndexOf), 1, BindingFlags.Public | BindingFlags.Static | BindingFlags.DeclaredOnly, null, CallingConventions.Any, new[] { Type.MakeGenericMethodParameter(0).MakeArrayType(), Type.MakeGenericMethodParameter(0) }, null)!.MakeGenericMethod(typeof(int));
var array = new int[] { 3, 2, 1, 0 };
Console.WriteLine(method.Invoke(null, new object?[] { array, 0 }));
```

Current behavior without a `rd.xml`:

```
Unhandled Exception: EETypeRva:0x00306AF8(System.Reflection.MissingRuntimeArtifactException): MakeGenericMethod() cannot create this generic method instantiation because no code was generated for it: 'System.Array.IndexOf<System.Int32>(System.Int32[],System.Int32)'.
```

**Comment by JamesNK** [comment]
Example of where this would be useful:

```csharp
internal static class ResultsOfTHelper
{
    [UnconditionalSuppressMessage("AOT", "IL3050", Justification = "MakeGenericType is safe because the target can be statically analyzed during compile.")]
    public static void PopulateMetadataIfTargetIsIEndpointMetadataProvider<TTarget>(MethodInfo method, EndpointBuilder builder)
    {
        if (typeof(IEndpointMetadataProvider).IsAssignableFrom(typeof(TTarget)))
        {
            var methodInfo = typeof(MetadataPopulator<>).MakeGenericType(typeof(TTarget)).GetMethod("PopulateMetadata")!;
            methodInfo.Invoke(null, new object[] { method, builder });
        }
    }

    internal static class MetadataPopulator<TTarget> where TTarget : IEndpointMetadataProvider
    {
        public static void PopulateMetadata(MethodInfo method, EndpointBuilder builder)
        {
            TTarget.PopulateMetadata(method, builder);
        }
    }
}
```

It currently fails when TTarget is a value type.

ASP.NET Core issue to use future improvement: https://github.com/dotnet/aspnetcore/issues/46267

**Comment by hez2010** [comment]
@MichalStrehovsky Even everything is statically known, we may still has to use MakeGenericType/MakeGenericMethod due to some generic constraints cannot be satisfied at the compile time but only at the runtime. 
The current C# lacks the ability of pattern matching on generic parameters (constraints), see https://github.com/dotnet/csharplang/discussions/6308.

**Comment by MichalStrehovsky** [comment]
Yup, that's why I brought this over from runtimelab. The linked discussion in the aspnetcore repo is about bridging constraints

**Comment by MichalStrehovsky** [comment]
We don't have a good spot to do this in the compiler. Dataflow analysis runs on top of uninstantiated IL so we can't do this there.

This would ideally be done in RyuJIT (intrinsic expansion of `typeof(Foo<>).MakeGenericType(typeof(T))` to `typeof(Foo<T>)`, provided constraints are met, etc). If we do it in RyuJIT, we also need to do it in IL Scanner.

Another closest spot where we could do this is the constant propagation (that rewrites IL) - this would be a single spot on the managed compiler side and it would not require RyuJIT work. However, we don't have facilities to easily do it here. The result would not be great.

I'm moving this to 9.0. This would be better done if we lay some foundational groundwork first.
