### ISSUE TITLE
[ARM32] Display wrong register number for double registers

### ISSUE THREAD

**Issue by hqueue** [dotnet/runtime#8121]
For ARM32, double register number is not shown correctly in JitDump, JitDisasm and etc.

- An example from coreclr unit test.
  ```
  $ COMPlus_JitDisasm=DblAdd COMPlus_JitDump=DblAdd  ./corerun 
  tests/JIT/CodeGenBringUpTests/DblAdd/DblAdd.exe
  ...(omitted)...
  IN0001: 000006  EE30 0B01      vadd    d0, d0, d2
  ...(omitted)...
  IN0001: 000006      vadd    d0, d0, d2
  ```
  However above instruction encoding `EE30 0B01` means `vadd d0, d0, d1`.

- Another example from recent PR for ryujit/arm32.
  I was confused with below example (https://github.com/dotnet/coreclr/pull/11643#issuecomment-301755496) in the PR.
  ```
  IN0074: 000180  EEB8 4BC4      vcvt.i2d d8, s8  
  ```
  This encoding `EEB8 4BC4` means `vcvt.i2d d4, s8`, i.e. single-float register number is correct, but double register number is incorrectly displayed.

Both LegacyJIT and RyuJIT have same problem.

category:implementation
theme:debug-dumps
skill-level:intermediate
cost:medium

**Comment by kunalspathak** [comment]
I can confirm the problem still exists. 

```asm
; Method getChars.MyXMLNodeWriter:DblAdd(double,double):double
G_M34776_IG01:              ;; offset=0000H
000000  E92D 4800      push    {r11,lr}
000004  46EB           mov     r11, sp
						;; size=6 bbWeight=1    PerfScore 2.00

G_M34776_IG02:              ;; offset=0006H
000006  EE30 0B01      vadd    d0, d0, d2
						;; size=4 bbWeight=1    PerfScore 1.00

G_M34776_IG03:              ;; offset=000AH
00000A  E8BD 8800      pop     {r11,pc}
						;; size=4 bbWeight=1    PerfScore 1.00
; Total bytes of code: 14
```
