### ISSUE TITLE
Perf summary : Microsoft.Extensions.Logging.Formatting.NoArguments

### ISSUE THREAD

**Issue by mayadav1** [dotnet/runtime#81230]
execution results :
Net8.0
|      Method |     Mean |    Error |   StdDev |   Median |      Min |      Max | Ratio | Allocated | Alloc Ratio |
|------------ |---------:|---------:|---------:|---------:|---------:|---------:|------:|----------:|------------:|
| NoArguments | 36.62 ns | 1.335 ns | 1.537 ns | 37.00 ns | 33.49 ns | 38.93 ns |  1.00 |         - |          NA |

Net6.0

|      Method |     Mean |    Error |   StdDev |   Median |      Min |      Max | Ratio | Allocated | Alloc Ratio |
|------------ |---------:|---------:|---------:|---------:|---------:|---------:|------:|----------:|------------:|
| NoArguments | 29.60 ns | 0.089 ns | 0.078 ns | 29.60 ns | 29.49 ns | 29.72 ns |  1.00 |         - |          NA |

#Regression diff ratio is 23.71%

Initially study shows that :
These functions inlined by net6.0 but net8.0 doesn’t inline them and the contribute 77.382ms out of 08s. Net6.0 execution time is 05.
Microsoft::Extensions::Logging::MessageLogger::get_MinLevel
Microsoft::Extensions::Logging::MessageLogger::get_Logger
Microsoft::Extensions::Logging::Logger::IsEnabled

#4 tried solution :
I tried to inline them using “[MethodImpl(MethodImplOptions.AggressiveInlining)]” but it works for methods 

Is there any way to inline class properties ? or them.

Used command:
py .\scripts\benchmarks_ci.py --architecture x64 -c Release -f net8.0 --filter "Microsoft.Extensions.Logging.Formatting.NoArguments"
py .\scripts\benchmarks_ci.py --architecture x64 -c Release -f net6.0 --filter "Microsoft.Extensions.Logging.Formatting.NoArguments"

Your suggestions and help will be appreciated.

**Comment by stephentoub** [comment]
I just tried locally and here's what I see:
```
dotnet run -c Release -f net6.0 -filter *Formatting.NoArguments --runtimes net6.0 net7.0 net8.0
```

|      Method |  Runtime |     Mean |    Error |   StdDev |   Median |      Min |      Max | Ratio |
|------------ |--------- |---------:|---------:|---------:|---------:|---------:|---------:|------:|
| NoArguments | .NET 6.0 | 32.53 ns | 1.090 ns | 1.255 ns | 32.10 ns | 31.14 ns | 35.37 ns |  1.00 |
| NoArguments | .NET 7.0 | 30.34 ns | 0.483 ns | 0.428 ns | 30.29 ns | 29.57 ns | 31.18 ns |  0.92 |
| NoArguments | .NET 8.0 | 29.22 ns | 0.489 ns | 0.382 ns | 29.23 ns | 28.67 ns | 29.78 ns |  0.88 |

**Comment by mayadav1** [comment]
I tried with following machine:
Machine Config:
AMD Ryzen 9 5900X 12-Core Processor 3.50 GHz
64-bit operating system, x64-based processor
16.0 GB (15.9 GB usable)
It is still reproducible. 
@stephentoub : Can you let me know your machine detail ? 
I debugged both the version of .net core(i.e. net6.0 and net8.0) and found inlining of below function is benefiting Net6.0.

        public bool IsEnabled(LogLevel level)
        {
            if (MinLevel != null && level < MinLevel)
            {
                return false;
            }

            if (Filter != null)
            {
                return Filter(ProviderTypeFullName, Category, level);
            }

            return true;
        }
It has lambda expression. I noticed with several benchmarks that net7.0 onward doesn't inline lambda expression every time.
Your advice will be appreciated.

**Comment by tarekgh** [comment]
I don't have `AMD Ryzen 9` machine to try. I tried on my machine, and I am seeing the same results as @stephentoub 

```
11th Gen Intel Core i7-11700 2.50GHz, 1 CPU, 16 logical and 8 physical cores

|      Method |  Runtime |     Mean |    Error |   StdDev |   Median |      Min |      Max | Ratio | RatioSD | Allocated | Alloc Ratio |
|------------ |--------- |---------:|---------:|---------:|---------:|---------:|---------:|------:|--------:|----------:|------------:|
| NoArguments | .NET 6.0 | 26.16 ns | 2.097 ns | 2.415 ns | 26.53 ns | 23.04 ns | 31.14 ns |  1.00 |    0.00 |         - |          NA |
| NoArguments | .NET 7.0 | 27.18 ns | 3.683 ns | 4.242 ns | 25.39 ns | 22.96 ns | 36.20 ns |  1.05 |    0.19 |         - |          NA |
| NoArguments | .NET 8.0 | 23.21 ns | 0.484 ns | 0.452 ns | 23.28 ns | 22.65 ns | 24.23 ns |  0.89 |    0.09 |         - |          NA |
```

Maybe sharing the jitted code from your machine can help comparing to the jitted code on Intel machines? 

CC @AndyAyersMS @EgorBo @mangod9 if they have any idea what the difference could be especially around inlining the properties.

**Comment by mayadav1** [comment]
Never mind, can't repro. I am correcting my numbers .

|      Method |  Runtime |     Mean |    Error |   StdDev |   Median |      Min |      Max | Ratio | Allocated | Alloc Ratio |
|------------ |--------- |---------:|---------:|---------:|---------:|---------:|---------:|------:|----------:|------------:|
| NoArguments | .NET 6.0 | 16.49 ns | 0.072 ns | 0.064 ns | 16.47 ns | 16.41 ns | 16.64 ns |  1.00 |         - |          NA |
| NoArguments | .NET 7.0 | 17.36 ns | 0.051 ns | 0.040 ns | 17.36 ns | 17.26 ns | 17.43 ns |  1.05 |         - |          NA |
| NoArguments | .NET 8.0 | 17.25 ns | 0.119 ns | 0.105 ns | 17.20 ns | 17.16 ns | 17.49 ns |  1.05 |         - |          NA |

**Comment by tarekgh** [comment]
Thanks @mayadav1
