### ISSUE TITLE
STJ should support deserializing/serializing nested polymorphism

### ISSUE THREAD

**Issue by angelobreuer** [dotnet/runtime#81279]
### Description

Some JSON protocols are implemented by having a property indicating the type of the payload (commonly named "operation code", or short "op"). Deserialization of such types works with the new polymorphism feature of System.Text.Json:

```cs
using System.Text.Json;
using System.Text.Json.Serialization;

var json = """
    {
        "op": "Start"
    }
    """;

var payload = JsonSerializer.Deserialize(json, ProtocolSerializerContext.Default.IPayload);

;

[JsonPolymorphic(TypeDiscriminatorPropertyName = "op")]
[JsonDerivedType(typeof(StartPayload), "Start")]
[JsonDerivedType(typeof(StopPayload), "Stop")]
interface IPayload
{
}

sealed record class StartPayload : IPayload;

sealed record class StopPayload : IPayload;

[JsonSerializable(typeof(IPayload))]
sealed partial class ProtocolSerializerContext : JsonSerializerContext
{
}
```

Some protocols also have messages where **the type of the payload depends on two properties of the JSON payload**, for example, here:

```json
{
    "op": "Event",
    "type": "Start"
}
```

Such a protocol would be implemented in STJ (probably) like this:

```cs
using System.Text.Json;
using System.Text.Json.Serialization;

var json = """
    {
        "op": "Event",
        "type" : "Start",
        "PropertyA": true
    }
    """;

// Deserialization of interface types is not supported. Type 'IEventPayload'. Path: $ | LineNumber: 2 | BytePositionInLine: 12."
var payload = JsonSerializer.Deserialize(json, ProtocolSerializerContext.Default.IPayload);

;

[JsonPolymorphic(TypeDiscriminatorPropertyName = "op", UnknownDerivedTypeHandling = JsonUnknownDerivedTypeHandling.FallBackToNearestAncestor)]
[JsonDerivedType(typeof(IEventPayload), "Event")]
[JsonDerivedType(typeof(CommandPayload), "Command")]
interface IPayload
{
}

sealed record class CommandPayload(string Name) : IPayload;

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(StartEventPayload), "Start")]
[JsonDerivedType(typeof(StopEventPayload), "Stop")]
interface IEventPayload : IPayload
{
    ulong ScopeId { get; }
}

sealed record class StartEventPayload(ulong ScopeId, bool PropertyA) : IEventPayload;

sealed record class StopEventPayload(ulong ScopeId, bool PropertyB) : IEventPayload;

[JsonSerializable(typeof(IPayload))]
[JsonSerializable(typeof(IEventPayload))]
sealed partial class ProtocolSerializerContext : JsonSerializerContext
{
}
```

### Reproduction Steps

Run the above code snippet.

### Expected behavior

STJ should properly deserialize types with nested JsonPolymorphism attribute.

### Actual behavior

STJ fails with the following exception message:

```js
System.NotSupportedException
  HResult=0x80131515
  Nachricht = Deserialization of interface types is not supported. Type 'IEventPayload'. Path: $ | LineNumber: 2 | BytePositionInLine: 12.
  Quelle = System.Text.Json
  Stapelüberwachung:
   bei System.Text.Json.ThrowHelper.ThrowNotSupportedException(ReadStack& state, Utf8JsonReader& reader, NotSupportedException ex)
   bei System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   bei System.Text.Json.Serialization.JsonConverter`1.OnTryReadAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state, Object& value)
   bei System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   bei System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   bei System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   bei System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   bei System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   bei System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonTypeInfo`1 jsonTypeInfo)
   bei Program.<Main>$(String[] args) in STJNestedPolymorphism\Program.cs: Zeile13

Innere Ausnahme 1:
NotSupportedException: Deserialization of interface types is not supported. Type 'IEventPayload'.
```

### Known Workarounds

One could use a different architecture, like writing an own JSON converter to deserialize such types.

### Configuration

.NET SDK:
 Version:   7.0.200-preview.22628.1
 Commit:    76bbaffad6

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.200-preview.22628.1\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  7.0.200-preview.22628.1 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

### Other information

Changing the types to proper classes does not work either. STJ complains about not finding a viable constructor.

**Comment by eiriktsarpalis** [comment]
I would say this is a feature way beyond the scope and design parameters of the built-in polymorphism implementation. I would recommend either writing a custom converter, or (assuming your protocol _must_ use both commands and events in the same channel) consider grouping your JSON objects by `op` type before ser/deserializing using either your command model or event model.
