### ISSUE TITLE
Generalize Arm64 ldr/str to ldp/stp optimization

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#81278]
https://github.com/dotnet/runtime/pull/77540 introduced a JIT peephole optimization to convert consecutive ldr/str instructions to ldp/stp. It was limited to avoiding this optimization when either of the two ldr/str represented lclvar, which requires more work to properly handle the GC effects.

See https://github.com/dotnet/runtime/pull/77540#pullrequestreview-1268515376 for more discussion.

This issue tracks generalizing the optimization to handle the lclvar cases.

Also, the optimization was restricted to not work in prologs or epilogs, to avoid affecting unwind codes. There are two potential improvements here:
1. Make sure the unwind codes work with the optimization.
2. Allow the optimization in the non-OS (not unwindable) part of the prolog/epilog.

**Comment by BruceForstall** [comment]
Regarding the lclvar case, `emitIns_S_S_R_R()` might be a place to look.

**Comment by kunalspathak** [comment]
https://github.com/dotnet/runtime/pull/85032 fixes the general code except prolog/epilog and unwind code. I will leave this issue open.

**Comment by kunalspathak** [comment]
Just to experiment, I tried to comment below lines and see lot of methods improved for benchmarks collection.

https://github.com/dotnet/runtime/blob/049acec07fb748b01f5300ec16eb3363ae337096/src/coreclr/jit/emitarm64.cpp#L16648-L16653

```
2,387 contexts with diffs (2,387 improvements, 0 regressions, 0 same size)
  -12,172 bytes

```
