### ISSUE TITLE
Use PoolingAsyncValueTaskMethodBuilder for System.Net.Http.HttpConnection async reads

### ISSUE THREAD

**Issue by theonm** [dotnet/runtime#81318]
### Description

The System.Net.Http.HttpConnection which is used for HTTP/1.0 and HTTP/1.1 is not reusing heap allocated value tasks meaning there are many more heap allocations which generates more work for the garbage collector.

This performance improvement has already been implemented for in System.Net.Http.Http2Connection which is used for HTTP/2.

**Comment by ManickaP** [comment]
Triage: based on the discussion in the linked PR, I'm putting this in the future. Firstly, there is an already PR for this. Secondly, we're waiting for some actual numbers proving this is worth pursuing so we might even decide not to do anything about it. So this is not a critical change for 8.0.

**Comment by epeshk** [comment]
I reproduced these allocations by reading HTTP1 request body from stream. Client and server should be on different machines (or VMs, e.g. WSL2). I used Windows for the client and Linux Ubuntu for the server.

Client:

```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Jobs;
using BenchmarkDotNet.Running;

BenchmarkRunner.Run<Benchmarks>();

[MemoryDiagnoser]
[SimpleJob(RuntimeMoniker.Net80)]
public class Benchmarks
{
  private string url = "http://ubuntu-01:5002";
  private byte[] buffer;
  private HttpClient client = new HttpClient(new SocketsHttpHandler());

  [Params(1024, 4*1024, 64*1024)]
  public int BufferSize { get; set; }

  [GlobalSetup]
  public void Setup() => buffer = new byte[BufferSize];

  [Benchmark]
  public async ValueTask ReadBodyBenchmark()
  {
    using var responseMessage = await client.GetAsync(
      url,
      HttpCompletionOption.ResponseHeadersRead);
    await using var stream = await responseMessage.Content.ReadAsStreamAsync();
    while (await stream.ReadAsync(buffer) != 0) ;
  }
}
```

Server:
```cs
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

var content = new byte[16 * 1024 * 1024];

Random.Shared.NextBytes(content);

app.MapGet("/", async context =>
{
  context.Response.ContentLength = content.Length;
  await context.Response.Body.WriteAsync(content);
});

app.Run();
```

Before:
```
|            Method | BufferSize |     Mean |   Error |  StdDev | Allocated |
|------------------ |----------- |---------:|--------:|--------:|----------:|
| ReadBodyBenchmark |       1024 | 147.2 ms | 0.08 ms | 0.07 ms | 575.84 KB |
| ReadBodyBenchmark |       4096 | 147.2 ms | 0.13 ms | 0.12 ms | 471.89 KB |
| ReadBodyBenchmark |      65536 | 147.3 ms | 0.12 ms | 0.10 ms |   85.6 KB |
```

After applying pooling:
```
|            Method | BufferSize |     Mean |   Error |  StdDev | Allocated |
|------------------ |----------- |---------:|--------:|--------:|----------:|
| ReadBodyBenchmark |       1024 | 147.1 ms | 0.08 ms | 0.07 ms |   2.72 KB |
| ReadBodyBenchmark |       4096 | 147.1 ms | 0.07 ms | 0.06 ms |   2.55 KB |
| ReadBodyBenchmark |      65536 | 147.1 ms | 0.06 ms | 0.06 ms |   2.53 KB |

```

Async objects for 'Before' case from dump:
```
00007ffd04bf7270      259        39368 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Int32, System.Private.CoreLib],[System.Net.Http.HttpConnection+<ReadAsync>d__102, System.Net.Http]]
00007ffd04bf76f0      259        45584 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Int32, System.Private.CoreLib],[System.Net.Http.HttpConnection+ContentLengthReadStream+<ReadAsync>d__3, System.Net.Http]]
```
So, 328 bytes per `.ReadAsync(...)` call.

I applied `[AsyncMethodBuilder(typeof(PoolingAsyncValueTaskMethodBuilder<>))]` to:
```
System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory<byte> buffer, CancellationToken cancellationToken)
System.Net.Http.HttpConnection.ReadAsync(Memory<byte> destination)
System.Net.Http.HttpConnection.ReadBufferedAsyncCore(Memory<byte> destination)
```

With changes proposed in https://github.com/dotnet/runtime/pull/81426 I didn't noticed any allocation reduction for this scenario (but PR may be useful for other scenarios, like WebSockets)

**Comment by theonm** [comment]
Hi @epeshk,

PR #81426 adds pooling to two of the methods you mentioned, so it looks like you also needed to add it to a method in the ContentLengthReadStream class to see any improvement in the scenario you were testing.

**Comment by theonm** [comment]
Hi @epeshk,

PR #81426 adds pooling to two of the methods you mentioned, so it looks like it is also needed on a method in the ContentLengthReadStream class to see an improvement for the provided scenario.
