### ISSUE TITLE
hex number format in .net 7 jit assembly

### ISSUE THREAD

**Issue by kasperk81** [dotnet/runtime#81329]
jitdisasm in .net 7 is printing h suffix for hex numbers. h suffix may be allowed by intel assembly spec and normal for microsoft assemblers, but clang/gcc don't support it. it's unfamiliar to users and their disassemblers (which don't print h suffix) and their assemblers (which don't recognize the h suffix). please replace `%02XH` with `0x%02x` or keep it readable decimal as it was before .net 7.

**Comment by kasperk81** [comment]
.net 6: using decimal recognized by masm, clang, gcc, nasm, ptx etc. and their users
```asm
.intel_syntax noprefix

x:
  mov    [rsp+16], rdi
  mov    rdi, [rsp+9]
```

.net 7: using hex with h suffix (instead of 0x prefix) recognized only by masm and its users
```asm
.intel_syntax noprefix

x:
  mov    [rsp+10H], rdi
  mov    rdi, [rsp+09H]
```

**Comment by EgorBo** [comment]
Overall JitDisam is not a real asm code, e.g. it contains pseudo instructions like `mov gword` 

cc @BruceForstall on hex formatting

**Comment by kunalspathak** [comment]
> Overall JitDisam is not a real asm code, e.g. it contains pseudo instructions like mov gword

Correct. This was changed in .NET 7 in https://github.com/dotnet/runtime/pull/73816 to ease the search of given address offset displayed in local variables table.

**Comment by kasperk81** [comment]
https://github.com/dotnet/runtime/pull/73816#issuecomment-1215594309
change to 0x format for readability

**Comment by kasperk81** [comment]
@BruceForstall feedback about reverting to well known 0x prefix was from the user when i enabled dotnet daily build on https://godbolt.org public website (https://github.com/compiler-explorer/compiler-workflows/commit/226373d04e312f09bb089e77e520f0a09e67c77b). this feedback echoes your comment: https://github.com/dotnet/runtime/pull/73816#issuecomment-1215594309. i think it should be changed

**Comment by kunalspathak** [comment]
Agree. I will revert the format of disassembly, and instead make changes in local variables table to make search easier.

**Comment by kunalspathak** [comment]
I was looking into this and the original change done in xarch was to make it consistent regardless of how much is the displacement. Prior to my change, it was showing a mixed of decimal and hexadecimal and some of them also included `H` as seen below.

https://github.com/dotnet/runtime/blob/c240ade7eac26ad2ee9cad05f6a6d595888ba0ee/src/coreclr/jit/emitxarch.cpp#L10311-L10326

**Comment by tannergooding** [comment]
There is no "official" format for x86 assembly and what exactly is supported can differ based on assembler.

That being said, most assemblers support `0x` while the support for `h` is definitely more variable. The majority of official samples from the Intel/AMD architecture manuals use `0x` as well.

**Comment by kunalspathak** [comment]
> That being said, most assemblers support `0x` (`MASM` is a notable exception) while the support for `h` is definitely more variable. The majority of official samples from the Intel/AMD architecture manuals use `0x` as well.

Thanks @tannergooding . A follow-up question, do they distinguish between displaying the address that is less than `1000`, the way we are doing? I am ok with using `0x` or `h` format as long as they are consistent for various address and not restrict it based on the actual address value.

**Comment by tannergooding** [comment]
There isn't really a standard there either and which is "better" depends on context.

If you're doing something like "field offsets" then decimal may be better. If you're doing arbitrary addresses or displacements, then hex may be better.

The same goes for practically any immediate value. For `shufps`, using hex for the immediate is almost always better even for small constants, as an example.

**Comment by kunalspathak** [comment]
@jakobbotsch  - can you please take a look?

**Comment by jakobbotsch** [comment]
@kunalspathak What is the work item here? To update the places in the xarch backend where we print hex numbers with "H" suffix to instead print with "0x" prefix?
