### ISSUE TITLE
Rewrite SpanHelpers.IndexOfNullByte/IndexOfNullCharacter to unmanaged pointers

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#81332]
1) It seems to be containing potential GC holes, see https://github.com/dotnet/runtime/pull/81327#discussion_r1089997416 for potential future uses.
2) Currently, this function is only used by `System.String`'s ctors accepting unmanaged pointers which then converted to managed ones.

It also will allow to avoid doing verbose Unsafe stuff like
```csharp
if (uValue == Unsafe.AddByteOffset(ref searchSpace, offset + 1))
```
and do
```csharp
if (uValue == searchSpace[offset + 1])
```
instead.

**Comment by teo-tsirpanis** [comment]
Fixed by #81347 ([GitHub does not recognize "Addresses"](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)).
