### ISSUE TITLE
[API Proposal]: `Unsafe.BitCast` for efficient type reinterpretation

### ISSUE THREAD

**Issue by MichalPetryka** [dotnet/runtime#81334]
### Background and motivation

Reinterpretation of types - especially value ones - is a common occurrence in high performance code.
Currently in C#, it is usually realized using the `Unsafe.As` API or with the `*(TTo*)&value` pattern. The JIT however has some issues with optimizing such code, due to the value being marked as address taken. Introducing a new API with a more descriptive name might be easier and cheaper than making the JIT recognize such pattern.

The name `BitCast` was inspired by the C++ `std::bit_cast` and LLVM `bitcast`.

Open questions:
1. Should the API have any generic constraints? Restricting it to `unmanaged` or `struct` types would make it safer to use but potentially less useful in generic contexts (for example with `Enum` constraint, since that by itself doesn't restrict it to such types).
2. What should the behaviour be for non matching size types? As I see it, there are two reasonable options:
a) make the API throw in such case - that's what the C++ and LLVM bitcasts do, not really useful but could be regarded as the expected behaviour.
b) make the API function as if a buffer of the larger size was created (and zero initialized), the `value` written into it and then the target type read from its beginning. This behaviour would allow the API to be utilized in the current code that reads a smaller type from the beginning of a larger one with `Unsafe.As` and could be used for extending stuff like Vectors.
3. Would `BitCast` or `Bitcast` be the preferred casing?

With different sizes being permitted the code would behave like this:
```C#
unsafe static TTo BitCast<TFrom, TTo>(TFrom value)
{
    if (sizeof(TFrom) >= sizeof(TTo))
        return *(TTo*)&value;
    TTo v = default;
    *(TFrom*)&v= value;
    return v;
}
```

With only same sizes being accepted it'd work like this:
```C#
unsafe static TTo BitCast<TFrom, TTo>(TFrom value)
{
    if (sizeof(TFrom) != sizeof(TTo))
        throw new NotSupportedException();
    return *(TTo*)&value;
}
```

### API Proposal

```csharp
namespace System.Runtime.CompilerServices;

public static class Unsafe
{
    public static TTo BitCast<TFrom, TTo>(TFrom value);
}
```

### API Usage

https://github.com/dotnet/runtime/blob/ae6a73f82ff572004d739083751026d0b82663f3/src/libraries/System.Private.CoreLib/src/System/SpanHelpers.T.cs#L39-L60

```csharp
// instead of non generic BitConverter APIs:
// Console.WriteLine(BitConverter.UInt32BitsToSingle(12345));
Console.WriteLine(Unsafe.BitCast<uint, float>(12345));
// prints 1.7299E-41

// bitcasting to a same sized type
Console.WriteLine(Unsafe.BitCast<Vector4, Vector128<float>>(new Vector4(1f, 2f, 3f, 4f)));
// prints <1, 2, 3, 4>

// bitcasting to a smaller type
Console.WriteLine(Unsafe.BitCast<Vector4, Vector2>(new Vector4(1f, 2f, 3f, 4f)));
// prints <1, 2>

// bitcasting to a bigger type
Console.WriteLine(Unsafe.BitCast<Vector2, Vector4>(new Vector2(1f, 2f)));
// prints <1, 2, 0, 0>
```

### Alternative Designs

Using `Unsafe.As` for same sized or smaller types, writing to a stack allocated, zero initialized, buffer of the destination type size and reading from it.

### Risks

Unsafely reinterpreting managed types if there are no generic constraints can lead to GC holes, unexpected behaviour on big endian platforms for non matching sizes can cause code to become platform specific.

**Comment by tannergooding** [comment]
It's worth noting that every example given is not really a "valid" scenario for this API.

For integer casts (same size or smaller), you're better off just casting.

For integer to floating-point casts, you're better off using `BitConverter.SingleToInt32Bits` or `SingleToUInt32Bits` or `Int64BitsToDouble`, etc...

For vector casts, you're better off doing `.AsVector128()`, `.AsVector4()`, `.AsVector3()`, `.GetLower()`, etc...

**Comment by tannergooding** [comment]
Noting that I'm not against such an API, it would be useful for other types of bitcasts such as two "Matrix4x4" definitions. It could also be used to simplify/centralize other currently intrinsic APIs to one callsite.

I just wanted to explicitly call out that all the others do have existing better APIs.

**Comment by tannergooding** [comment]
I do think that, as a `bitcast` API, it should only allow bitcasts

That is, it should throw if `sizeof(T)` and `sizeof(U)` do not match.

**Comment by jkotas** [comment]
> The JIT however has some issues with optimizing such code, due to the value being marked as address taken

What would it take to fix these issues in the JIT? We have done work in the JIT to cleanup unnecessary address-taken. Is there work left to do?

**Comment by tannergooding** [comment]
I believe there are still some import and other early cases before we've removed the "address taken" that are impacted.

This can impact early constant propagation, some inlining observations, and removal of dead branches before they impact any other phases (and therefore the JIT throughput).

**Comment by SingleAccretion** [comment]
Concretely, we are talking about this piece of code, part of the very early IL scan:

https://github.com/dotnet/runtime/blob/ae6a73f82ff572004d739083751026d0b82663f3/src/coreclr/jit/fgbasic.cpp#L2305-L2320

Before local morph determines the precise set of address-exposed locals, we have to assume `lvHasLdAddrOp == true` means the local can be arbitrarily mutated and its state globally visible.

Currently `impILConsumesAddr` only handles `ldfld`, it would take some TP measuring how expensive would it be to expand to other patterns as well as non-root methods.

**Comment by EgorBo** [comment]
Potential use-case (we discussed in the other issue):

![image](https://user-images.githubusercontent.com/523221/215346139-45f26d03-48e9-4e85-a3ed-67df6cef09d6.png)

This method is marked as AggressiveInling, but e.g. `IndexOf((byte)0)` will never propagate that `0` by value during inlining because IL prescan found that it is address taken. Thus, `IsKnownConstant` has no chance to work as desired and will always see a non-constant

**Comment by tannergooding** [comment]
@jkotas, any pushback against this API being exposed given the above?

If not, I'll mark this as `api-ready-for-review`.

**Comment by jkotas** [comment]
Looks fine to me.

**Comment by hamarb123** [comment]
Here's my 2 cents:

> What should the behaviour be for non matching size types?

I think bitcasting between different sizes could be useful.
But if we allow casting between different sizes, we should document how it works with endianness in the documentation so people will be able to look up what the behaviour is.

> Should the API have any generic constraints? Restricting it to `unmanaged` or `struct` types would make it safer to use but potentially less useful in generic contexts (for example with `Enum` constraint, since that by itself doesn't restrict it to such types).

I think we should avoid constraints on `Unsafe` APIs where it isn't necessary as the constraints bubble up uncontrollably currently, we should just document what it's expected to receive. And if it would provide correct behaviour between 2 structs with identical declarations, even though they have managed fields (depends on the implementation obviously as to whether this is the case), then it shouldn't have `unmanaged` on it imo.

> Would `BitCast` or `Bitcast` be the preferred casing?

I think `BitCast` looks a bit better, but both look fine to me.

**Comment by tannergooding** [comment]
> I think BitCast looks a bit better, but both look fine to me.

API review is going to spend at least a good bit of time debating this, is my expectation.

------------------------------

My point of view is...

From https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions#capitalizing-compound-words-and-common-terms

> Most compound terms are treated as single words for purposes of capitalization.
>
>❌ DO NOT capitalize each word in so-called closed-form compound words.
>
> These are compound words written as a single word, such as endpoint. For the purpose of casing guidelines, treat a closed-form compound word as a single word. Use a current dictionary to determine if a compound word is written in closed form.

Now the trouble with programing "terms" is that they are often "new enough" that they haven't been formalized in a dictionary yet. Hence, my belief is that it is up to API review to speculate if such a word will eventually being a "closed form" compound word or not.

If we look historically at both the general English language as well as more specifically at programming terms, we can see that people tend to normalize similar words to be compound over time.

Some examples specifically listed on the capitalization guidelines page include `endpoint`, `callback`, `gridline`, `hashtable`, and `metadata`. Some other considerations would be `website`.

Each of these words, when initially "introduced" would have started as two separate words and the usage of them evolved over time until they became a singular term and thus while `WebSite` is not "incorrect", the common place usage indicates that it is `Website` and `website`.

My belief is that there is enough evidence that points towards `bitcast` being the same and that even if these is some level of disagreement today, it will eventually normalize over time to be the singular.

There are some other examples of words doing the same such as `typecast` (as in typecasting an actor/actress) or `bedroom`.

Another point is how that word would be written down in documentation. Would you write:
* `Bitcasting is ...`
* `Bit casting is ...`

Or how about:
* `If we know the source of the bitcast ...`
* `If we know the source of the bit cast ...`

or even:
* `I think bitcasting between different ...`
* `I think bit casting between different ...`

Thus, I believe `Bitcast` and `bitcast` is correct, and that people will definitely preference `bitcast` over `bitCast` if using the name as a local, parameter, or private field, etc.

**Comment by hamarb123** [comment]
> Thus, I believe `Bitcast` and `bitcast` is correct, and that people will definitely preference `bitcast` over `bitCast` if using the name as a local, parameter, or private field, etc.

True, I hate the look of `bitCast`.

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System.Runtime.CompilerServices;

public static class Unsafe
{
    public static TTo BitCast<TFrom, TTo>(TFrom value);
}
```
