### ISSUE TITLE
[corehost] Return value of library_exists_in_dir is disregarded

### ISSUE THREAD

**Issue by TERESH1** [dotnet/runtime#81355]
### Discussed in https://github.com/dotnet/runtime/discussions/81315

<div type='discussions-op-text'>

<sup>Originally posted by **TERESH1** January 28, 2023</sup>
Why return value of function is not checked?
https://github.com/dotnet/runtime/blob/b6cd3003c05d9be521d6d1ffff9207255d177116/src/native/corehost/hostpolicy/deps_resolver.cpp#L832</div>

**Comment by elinor-fung** [comment]
`deps_resolver` itself treats being able to get the `coreclr` path as optional and the caller is responsible for checking and erroring out if appropriate.
https://github.com/dotnet/runtime/blob/d7a7e3484f8feaf3704482eaa18b6e45fe847c1c/src/native/corehost/hostpolicy/hostpolicy_context.cpp#L192-L201

This is functionally resulting in what it should, but there may be some refactoring - or at least comments - that can make the intent clearer.
