### ISSUE TITLE
Publish size regression on Linux

### ISSUE THREAD

**Issue by sebastienros** [dotnet/runtime#81374]
From 111MB to 284MB for a self-contained app. Only on Linux.

These files are the reason

![image](https://user-images.githubusercontent.com/1165805/215570571-2db265d9-a444-42e8-a1d7-041766561129.png)

Can be reproduced between versions `8.0.0-alpha.1.23076.9+007df05` and `8.0.0-alpha.1.23077.2+741fa51` which corresponds to this changeset https://github.com/dotnet/runtime/compare/007df05...741fa51e73e93f3e5752d0d1069a8c871ad302cc

**Comment by eerhardt** [comment]
cc @kunalspathak - https://github.com/dotnet/runtime/pull/77578 looks suspect.

**Comment by agocke** [comment]
Yup, that change almost certainly also affects the official build -- @kunalspathak can you revert your change? We can bring it back when we come up with a way to only include symbols in PR, or add a step to strip them before publishing.
