### ISSUE TITLE
Switch/check for NativeAOT and reflection-free mode.

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtime#81370]
Can we have some RuntimeFeature flag which can tell if reflection supported or not. Right now without reflection `serviceProvider.GetType().FullName` throws. I use that construct for better infomation diagnostics in tests, and would like to skip some reporting in reflection-free if possible. Or if `serviceProvider.GetType().FullName` can be made to magically work :)

**Comment by jkotas** [comment]
Type.FullName can return null. You can change the reflection free mode to do that instead of throwing.

> Can we have some RuntimeFeature flag which can tell if reflection supported

We do not plan to introduce APIs for the reflection-free mode as it exist today. See the discussion in https://github.com/dotnet/runtime/issues/67193

**Comment by teo-tsirpanis** [comment]
Duplicate of #61387.

**Comment by kant2002** [comment]
Thanks, I expect something like that, but returning null seems fine for me.
