### ISSUE TITLE
[Question] Will the dotnet runtime be updateable automatically via windows update?

### ISSUE THREAD

**Issue by glatzert** [dotnet/runtime#8137]
I tried to find Information on this Topic, but failed.

So will we be able to Auto-Update the dotnet runtime via WU or WSUS?

**Comment by ericstj** [comment]
@leecow @jamshedd can you please help answer this?

**Comment by leecow** [comment]
My answer above was definitely wrong. We currently do not release .NET Core updates via MU. Enabling that channel is something that's being considered but no firm decision yet. 

cc/ @nakarnam

**Comment by nakarnam** [comment]
This is being planned for the .NET 5 timeframe. We are tracking this in a separate [issue](https://github.com/dotnet/core/issues/5013).

**Comment by danmosemsft** [comment]
@nakarnam can we close this then?

**Comment by danmosemsft** [comment]
Duplicate of https://github.com/dotnet/core/issues/5013
