### ISSUE TITLE
It should not be possible to set Activity parent after activity is started

### ISSUE THREAD

**Issue by lmolkova** [dotnet/runtime#81371]
### Description

If `Activity` has started without parent, and then `SetParentId` is called, then Activity.ParentId is updated.
If `Activity` had a parent at start time, `SetParentId` does nothing (correctly).

In distributed tracing, spans (activities) that are in parent/child relationship should have the same trace-id. Setting parent after activity is started (trace-id is generated, sampling decision is done) is invalid.

### Reproduction Steps

```csharp
using System.Diagnostics;

var a = new Activity("foo").Start();
Console.WriteLine($" trace id - {a.TraceId}, parent id - {a.ParentId}");
a.SetParentId("00-6e76af18746bae4eadc3581338bbe8b1-2899ebfdbdce904b-00");
Console.WriteLine($" trace id - {a.TraceId}, parent id - {a.ParentId}");
```

### Expected behavior

`SetParentId` on started `Activity` should be ignored (write first chance exception). 

### Actual behavior

```
 trace id - 0bb55e0092537a03fe5a83fc6030677e, parent id -
 trace id - 0bb55e0092537a03fe5a83fc6030677e, parent id - 00-6e76af18746bae4eadc3581338bbe8b1-2899ebfdbdce904b-00
```

### Regression?

not a regression, the issue was there from day 1

**Comment by tarekgh** [comment]
Interesting, the issue https://github.com/dotnet/runtime/issues/63883 was claiming the opposite.

**Comment by noahfalk** [comment]
> Interesting, the issue https://github.com/dotnet/runtime/issues/63883 was claiming the opposite.

I suspect 63883 was observing this part of the behavior @lmolkova described above "If Activity had a parent at start time, SetParentId does nothing (correctly)." 

I can't rule out that it might trigger a compat issue in some app, but I certainly wouldn't expect this to be a common pattern. Given the behavior it enables clearly breaks the rules for TraceId I'd be in favor of fixing it. I think it would be reasonable to ignore the request, the same as we are already doing if a parent is present.

**Comment by lmolkova** [comment]
adding related activity from different trace can be done with links or delaying span start. 

my 2c on back-compat, any experience that sets parent after is broken anyway: 
- setting parent does not change trace-id, span-id, flags, anyway
- exporters would likely use `TraceId`,  `SpanId` and `ParentSpanId`, without ever knowing that `ParentSpanId` belongs to a different trace, which again creates a broken experience.

**Comment by tarekgh** [comment]
Sounds good, I'll create a PR to fix that.
