### ISSUE TITLE
GetTimeZoneIds empty on Android devices/emulators API 21-25

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#81373]
### Description

APIs depending on `GetTimeZoneIds`, such as `GetSystemTimeZones` -> `PopulateAllSystemTimeZones` -> `GetTimeZoneIds`, will have an incorrect empty set of `TimeZoneInfo`s.

### Reproduction Steps

```
foreach (var tz in TimeZoneInfo.GetSystemTimeZones())
{
    Console.WriteLine($"TimeZone: {tz.DisplayName}");
}
```
on an Android device/emulator running on API 21 leads to no time zones.

### Expected behavior

Non-empty set of time zones being written to the console.

### Actual behavior

No time zones being written to the console.

### Other information

Two pull requests are culpable for this behavior. https://github.com/dotnet/runtime/pull/54845 and https://github.com/dotnet/runtime/pull/64028

After porting over Mono's implementation to load time zone data in #54845, following the change to remove `zone.tab` on Android https://github.com/dotnet/runtime/issues/41867#issuecomment-687145243, there was an [issue](https://github.com/dotnet/runtime/issues/63693) where deprecated time zones were still inside the tzdata file alongside the updated/renamed time zone.
The solution at the time to determine what timezones were deprecated, A.K.A. "backwards", was to leverage the `tzlookup.xml`, and though it was [noted that it didn't exist on API 19 or 24](https://github.com/dotnet/runtime/issues/63693#issuecomment-1012323938), the fallback was missed in the implementation to remove backward timezones.

What happens is that the public `GetTimeZoneIds` grabs all time zones, and filters out "duplicates" based on the `_isBackwards` "property". That property is set to `TRUE` if it is not found in `tzlookup.xml`, which if there isn't that file in the first place, would lead to all timezones being marked as backwards, and thus none are returned in `GetTimeZoneIds`.

Options:

1) The easy fix to return a non-empty set would be to add a check if `tzlookup.xml` exists or if the `tzLookupIDs` is an empty set or not.
2) The more proper fix would be to figure out what ids are backwards without the `tzlookup.xml`, which might be retaining a copy of `tzlookup.xml` in runtime as suggested in https://github.com/dotnet/runtime/issues/63693#issuecomment-1012323938

**Comment by mdh1418** [comment]
@simonrozsival @steveisok

**Comment by akoeplinger** [comment]
I think we should at least do option 1 for 8.0 so we don't return an empty set in `GetTimeZoneIds`, having duplicated zones sounds better to me than none.

**Comment by mdh1418** [comment]
The Ids returned are no longer empty, though they contain duplicates as detailed in the other issue mentioned
