### ISSUE TITLE
OCSP revocation check does not work on Linux container

### ISSUE THREAD

**Issue by sokunna** [dotnet/runtime#81392]
### Description

We are running a .net 6 application on Kestrel inside a Linux docker container. The call the build the chain certificate fails with an error: "RevocationStatusUknown - unable to get certificate CRL". 
```				
				X509Chain x509Chain = new();
                x509Chain.ChainPolicy.RevocationFlag = X509RevocationFlag.EndCertificateOnly;
                x509Chain.ChainPolicy.RevocationMode = X509RevocationMode.Online;

				x509Chain.ChainPolicy.TrustMode = X509ChainTrustMode.CustomRootTrust;
				_ = x509Chain.ChainPolicy.CustomTrustStore.Add(rootCertificate);
				x509Chain.Build(clientCertificate);
```
The snippet of code returns true when run in a Windows environment but fails when running from a docker container. It seems to fail at this callstack where the DownloadOcspGet method returns a 404 Not Found. 

![image](https://user-images.githubusercontent.com/30151191/215615494-57546bd2-8ddb-4e0b-b7a8-506a0a115f23.png)

When using openssl from inside the docker terminal, it was able to process the chain certificate revocation just fine. 
Also tested in .net 7 -- same result.

### Reproduction Steps

1. Generate a client certficate with OCSP 
2. Export both root and client certificates
3. Use code snippet above
4. Run in a docker container

### Expected behavior

Chain.Build() should work from a Linux Docker environment.

### Actual behavior

Chain.Build() returns false with RevocationStatusUnknown - unable to get certificate CLR.

**Comment by bartonjs** [comment]
if memory serves, we only support OCSP via the GET method.  Are you using a responder that only supports POST?

**Comment by sokunna** [comment]
@bartonjs you are spot on. The responder is missing the POST support. Thanks for the help!
