### ISSUE TITLE
[Wasm][AOT] Using Array.Sort falls back to the interpreter

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/runtime#81403]
### Description

When running `Array.Sort` the AOT compiler falls back to the interpreter.

![image](https://user-images.githubusercontent.com/5839577/215634968-9366285a-f45f-4010-8bd7-4f96cef706aa.png)

Sample code :

```csharp
var length = 1000;
var arr = new Span<int>(new int[length]);
for (var i = 0; i < length; i++)
{
    arr[i] = (int)Random.Shared.Next();
}

var temp = new int[length];
for (var j = 0; j < 500; j++)
{
    arr.CopyTo(temp);
    Array.Sort(temp);
}
```

### Configuration

https://github.com/dotnet/runtime/tree/release/7.0

### Regression?

No, likely always was behaving this way.

**Comment by lewing** [comment]
what is your build configuration?

**Comment by lewing** [comment]
@radekdoulik can you check the current codegen

**Comment by jeromelaban** [comment]
I'm sorry I did not get to include the information, but if by configuration you mean AOT without profiling, that's what I'm using. I did not get a chance to validate it with the non-blazor workload, though.

**Comment by lewing** [comment]
@jeromelaban are you still able to reproduce this?

**Comment by lewing** [comment]
please reopen if you are still seeing this issue
