### ISSUE TITLE
NativeAOT Populate source link information in the final PDB

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#81415]
Currently the NativeAOT compiler uses the source PDBs to produce one final PDB for the app, but it doesn't propagate source link information to the final PDB. This makes debugging into anything but the app's code a degraded experience.

This issue tracks:
[ ] - Investigate if there's some mechanism for source-link on Linux and macOS
[ ] - Implement propagating source-link at least on Windows

Per @MichalStrehovsky:
I tried looking into that [3 years ago](https://github.com/MichalStrehovsky/corert/commit/84e53e3eec9ff24e666eb55792de95eb4b4e6585) and it didn’t look too complicated. We need to extract the source link information json from the individual compilands, combine the json, write out the json to a file and pass it to link.exe. At least on Windows.

**Comment by MichalStrehovsky** [comment]
> [@MichalStrehovsky](https://github.com/MichalStrehovsky) Can you take a look at this? Feedback has pushed this one up in priority.

Do you have any more details on the feedback - what platform is this? I think we can only support this on Windows out of the box. We'd likely need to build a native debugger plugin for Linux.
