### ISSUE TITLE
[bug] .net 6 & .net 7 cant deserialize dictionary & keyvaluepair

### ISSUE THREAD

**Issue by forReason** [dotnet/runtime#81449]
### Description
.net 6 cannot deserialize dictionary and keyvaluepair (perhaps with string key). the application will crash:
```
[Fact]
public void DeserializeKeyValuePair()
{
    string text = "{\"offer\": 12432515239}";
    KeyValuePair<string, long> test = JsonSerializer.Deserialize<KeyValuePair<string, long>>(text);
}
```

.Net 7 will not crash but the result will be an empty keyvaluepair. Dictionaries can be deserialized with .net 7.

### Configuration
* Which version of .NET is the code running on?
net 6 & .net 7
* What OS and version, and for Linux, what distro?
Windows 10, 22h2
* What is the architecture (x64, x86, ARM, ARM64)?
x64
* Do you know whether it is specific to that configuration?
unspecific

### Other information

the behaviour of .net 7 can be reproduced in .net 6 by installing the nuget package:
[System.Text.Json nuget](https://www.nuget.org/packages/System.Text.Json#supportedframeworks-body-tab)

that way, at least dictionaries can be deserialized.

**Comment by eiriktsarpalis** [comment]
Curious why you expect KeyValuePair to have the format you're describing. System.Text.Json does support roundtripping but it uses a different format:
```C#
var kvp = new KeyValuePair<string, long>("offer", 12432515239);
string json = JsonSerializer.Serialize(kvp);
Console.WriteLine(json); // {"Key":"offer","Value":12432515239}
JsonSerializer.Deserialize<KeyValuePair<string, long>>(json);
```
If you would like to use a different format I would recommend using a custom converter for KeyValuePair.
