### ISSUE TITLE
Resource message stripping not compatible with our event sources

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#81459]
In the framework we have a documented trimming optimization to strip exception messages ([`<UseSystemResourceKeys>true</UseSystemResourceKeys>`](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-7-0)).

What this actually does is that it gets rid of the `FxResources.*.SR` manifest resource unless the framework assembly opted out.

The problem is that there is one more spot that uses this resource that is not related to exception messages per se - all the places in libraries that specify `EventSourceAttribute.LocalizationResource`, for example:

https://github.com/dotnet/runtime/blob/00c60e41ac459b005338329cd9b5fd5d6652777c/src/libraries/System.Net.Mail/src/System/Net/Mail/NetEventSource.Mail.cs#L10

Stripping the resource results in the following failure mode when the resource is stripped:

```
[FAIL] System.Net.Mail.Tests.LoggingTest.EventSource_ExistsWithCorrectId
System.Resources.MissingManifestResourceException : Could not find the resource "FxResources.System.Net.Mail.SR.resources" among the resources "" embedded in the assembly "System.Net.Mail", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String) + 0x160
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo, Dictionary`2, Boolean, Boolean) + 0x1c4
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo, Boolean, Boolean) + 0x1bc
   at System.Resources.ResourceManager.GetString(String, CultureInfo) + 0x114
   at System.Diagnostics.Tracing.ManifestBuilder.WriteMessageAttrib(StringBuilder, String, String, String) + 0x70
   at System.Diagnostics.Tracing.ManifestBuilder.StartEvent(String, EventAttribute) + 0x138
   at System.Diagnostics.Tracing.EventSource.CreateManifestAndDescriptors(Type eventSourceType, String eventSourceDllName, EventSource source, EventManifestOptions flags) + 0xee4
   at System.Net.Mail.Tests.LoggingTest.EventSource_ExistsWithCorrectId() + 0x104
```

I don't actually understand which of the resources are relevant for this. Could we e.g. break them into a separate resource that doesn't get trimmed with the exception messages? Or can eventsource fall back to resource keys as well?

I found some old issue that predicted this failure mode: #15995

Cc @eerhardt @brianrob 

I ran into this in #81455 that actually tried to run tests with these resources stripped. We probably never ran tests with the officially supported trimming switch.

**Comment by brianrob** [comment]
If I recall correctly, this is a reference to a localized string that gets put into the ETW manifest so that event consumers can display the event data in context with a localized event string.  I anticipate that this isn't something we'd want to strip, since it will have implications that cascade further than just the app itself.

Adding @davmason and @noahfalk for their opinions.

**Comment by noahfalk** [comment]
@MichalStrehovsky - is the resource stripping just for framework code, or does it also extend to user authored code?

@brianrob @davmason  - do either of you know of any scenarios where localized resources for Framework authored EventSources are important? My first instinct is that we should only localize messages that have a decent chance of being observed by application users, but ETW events are almost exclusively viewed by app developers. I did a search and found only 9 localized event name strings in the runtime repo not including test code. 5 are for TPL events, the other 4 are copies of the 'OperationReturnedSomething'* event on the various Private.InternalDiagnostics.System.Net.Xyz EventSources. 

*yes that is the literal name of the event in the code :)

**Comment by eerhardt** [comment]
> is the resource stripping just for framework code, or does it also extend to user authored code?

It only occurs for the libraries in dotnet/runtime. User/library authored code is unaffected. See #38397 for how this works.

> any scenarios where localized resources for Framework authored EventSources are important?

I was under the understanding that we don't localize anything in the dotnet/runtime libraries. I'm not sure if there are plans to change that in the future though.

**Comment by brianrob** [comment]
> @brianrob @davmason - do either of you know of any scenarios where localized resources for Framework authored EventSources are important?

The most relevant scenario that I'm aware of is when these messages are sent to the EventLog or get pulled into apps themselves.  I would be careful about removing this functionality for apps - we could choose to do so for our events if we feel it's not important, but I don't think we should strip these for anyone outside of the framework.

**Comment by noahfalk** [comment]
> I would be careful about removing this functionality for apps - we could choose to do so for our events if we feel it's not important, but I don't think we should strip these for anyone outside of the framework.

Agreed, I was only exploring the idea of removing usage of the feature from Framework EventSources, not that we take the feature away from app code. Since the resource stripping is also only for Framework code that appears to match up nicely.

My suggestion if nobody has any objections is to remove the 'LocalizationResources = xxx' from each of the framework implemented EventSources, but the API and underlying support for this feature in EventSource would remain as-is. There are probably a small number of dangling string resources that could be removed at the same time. I think that would solve our trimming problem with minimal impact on anyone else.

**Comment by brianrob** [comment]
@noahfalk, that sounds good to me.  Agreed that it matches up nicely.  I agree that those events are likely to be more for developers and us than for actual users of an app.
