### ISSUE TITLE
ConfigurationSection not loading under latest assembly package

### ISSUE THREAD

**Issue by mwpowellhtx** [dotnet/runtime#81488]
### Description

Configuration section failing to load, does not cast to custom `ConfigurationSection`, much less parsing through to the verbs, managing the underlying `ConfigurationElementCollection`, so on and so forth.

### Reproduction Steps

Starting with basically boilerplate `ConfigurationElement`, `ConfigurationElementCollection`, `ConfigurationSection`, templates, extending into an `App.config`, which is:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />
  </startup>
  <configSections>
      <section name="My" type="My.Configuration.AuthorizationConfigurationSection, My.Configuration" />
  </configSections>
  <My>
      <elements>
          <add name="element0" type="alpha" token="..." />
          <add name="element1" type="bravo" token="..." tokenSecret="..." />
      </elements>
  </My>
</configuration>
```

In terms of `<configSections/>`, I am not concerned with strong naming, the weak naming should be sufficient, IIRC, AFAIK, to connect the dots.

### Expected behavior

In prior iterations I might do something like `config.Sections["My"]` and it would load the configured section, and not just that, but something like `(MyConfigurationSection)config.Sections["My"]`, then work with the section, collection, elements, etc.

### Actual behavior

Section is loading, to a point, but it is loading as a `System.Configuration.DefaultSection` and does not convert whatsoever to `MyConfigurationSection`. Inspecting under debugger, there is a `_rawXml` backing field that does appear to contain the correct text, but clearly, evidently, that is not being parsed, i.e. `'<My><elements><add name="element0" type="alpha" token="..." /><add name="element1" type="bravo" token="..." tokenSecret="..." /></elements></My>'`, whitespace snipped for brevity, but those characters are also present, so I know that it is at least finding the correct `App.config`.

### Regression?

 Not sure when, if any, the regression did occur. Don't care, necessarily, assuming there is a sensible migration path, see _Workarounds_.

### Known Workarounds

I'd be satisfied if the response was, migration into the new (?) `IConfiguration` paradigm. I am getting my feet damp exploring that as a possibly alternative migration path, anyway, it does show some promise, provided I can grock the nuanced inner workings. Pinning that, if there was something about the historical approach that I was missing, which I am unaware of, not knowing what I do not know, along these lines, why would that be broken in the latest packages?

### Configuration

Nuget packages are as follows:

```xml
<PackageReference Include="System.Configuration.ConfigurationManager" Version="7.0.0" />
```

### Other information

I think that about covers it. Would be happy to clarify best I can. Thank you.

**Comment by ericstj** [comment]
@mwpowellhtx your repro is missing the definition of `MyConfigurationSection`.  Could you share a project that shows this?  Ideally a repro that would work when using a previous version of the package, but fail with latest.

**Comment by mwpowellhtx** [comment]
Appreciate the response. I evaluated that and since went the `IConfiguration` route instead. Seems a bit simpler and easier to comprehend once you get the hang of it. Will close this one, since apparently, perhaps I was missing a section, but I don't think I was.

**Comment by ericstj** [comment]
I don't think you were missing anything in the config file, it's just that you didn't include the C# source that defines the `AuthorizationConfigurationSection` type.  To be certain that we're looking at the exact problem you're reporting it would help to have a self-contained repro that demonstrates the behavior.  Something we could pick up and build and debug to see exactly what you're seeing.  If you'd like to reopen the issue with that repro we can have a look.

**Comment by mwpowellhtx** [comment]
@ericstj And like I said, I am 99% sure I did include a section. Maybe the definition was incomplete, or was not correctly wired or something, I do not know. Anyway, for what it was, I've since migrated to the `IConfiguration` approach.
