### ISSUE TITLE
LINQ Select swallowing exceptions

### ISSUE THREAD

**Issue by mwpowellhtx** [dotnet/runtime#81499]
### Description

...or at least not emitting them. I'm not even sure where to file this issue, I think it is _LINQ_ related, doing an `Enumerable.Select` extention issue. Exception is apparently not emitting, failing unit tests.

### Reproduction Steps

I ran into this issue doing unit testing, peeled back the layers, and `xunit` is fine, so are my [fluent extensions}(https://nuget.org/packages/xunit.fluently.assert.exceptionally/). When exceptions are thrown, both framework and extensions see them appropriately.

```csharp
[Fact]
public void XunitDoesThrowsThrow()
{
    Action test = () => throw new MyException();
    // Okay
    var ex = Assert.Throws<MyException>(test);
    Assert.NotNull(ex);
}

[Fact]
public void ExceptionallyDoesThrowsThrow()
{
    Action test = () => throw new MyException();
   // Also okay
    var ex = test.AssertThrows<MyException>();
    ex.AssertNotNull();
}
```

However, when I bury that thrown exception deep within an action, switch case, tried both "conventional" switch form, as well as the switch expression, both are failing to emit the exception.

Isolating a switch statement in and of itself, in either form, also works as expected.

```csharp
[Fact]
public void SwitchCaseDoesThrowsThrow()
{
    Action test = () =>
    {
        var x = 1;
        switch (x)
        {
            case 2: break;
            case 3: break;
            default: throw new MyException();
        }
    };

   // Okay
    var ex = test.AssertThrows<MyException>();
    ex.AssertNotNull();
}
```

Airing on the side of _plain ole what I know_ versus _fancy new stylings_, but for giggles, tried also the `switch expression`, also which 'works'.

```charp
[Fact]
public void SwitchExpressionDoesThrowsThrow()
{
    Action test = () =>
    {
        var x = 1;
        var y = x switch
        {
            2 => 2,
            3 => 3,
            _ => throw new MyException()
        };
    };

   // Also okay
    var ex = test.AssertThrows<MyException>();
    ex.AssertNotNull();
}
```

Now for the crux, this definitely does not emit the exception I expect it probably should.

```csharp
[Fact]
public void LinqSelectDoesThrowsThrow()
{
    Action test = () =>
    {
        var x = new int[] { 2, 3, 1 };
        var y = x.Select(_ => _ switch
        {
            2 => 2,
            3 => 3,
            _ => throw new MyException()
        });
    };

    var ex = test.AssertThrows<MyException>();
    ex.AssertNotNull();
}
```

I am throwing `MyException` here, but I started with `ArgumentOutOfRangeException` and wondered LINQ might even be swallowing that, but it seems exceptions in general.

### Expected behavior

I'd half expect an exception to emit from the _LINQ Select_ pattern, but it does not appear to do so. The unit test report:

```
 ...AppsettingsTests.LinqSelectDoesThrowsThrow
   Source: AppsettingsTests.cs line 110
   Duration: 185 ms

  Message: 
Assert.Throws() Failure
Expected: typeof(...MyException)
Actual:   (No exception was thrown)

  Stack Trace: 
AppsettingsTests.LinqSelectDoesThrowsThrow() line 123
```

### Actual behavior

See enumerated progression of steps in _Steps_.

### Regression?

To be honest, I do not have a baseline against which to compare, did it work before? I'd half expect it did.

### Known Workarounds

It's kind of an issue, we cannot depend on exceptions emitting from that, do we need to fall back on cruder loop controls? Not impossible to do that approach, obviously, but shame tisk tisk cannot use the more abbreviated forms.

### Configuration

Targeting `net6.0`, `Enumerable.Select` _F12_ yields along the lines of the following.

![image](https://user-images.githubusercontent.com/1824187/216146514-9a7d2a28-1b35-488e-9d5d-56170c8da57b.png)

**Comment by En3Tho** [comment]
Your y never gets iterated so this behavior is by design. To iterate on it use foreach, .ToArray(), .Max e.t.c

**Comment by mwpowellhtx** [comment]
If it helps, elaborating a bit, I have the following debug inspection of the result after Select with deep thrown exception.

![image](https://user-images.githubusercontent.com/1824187/216148119-2ed8345f-e3a0-4bda-80b5-36034a5e2770.png)

And a bit deeper still on the _Results View_.

![image](https://user-images.githubusercontent.com/1824187/216147957-b8356903-3893-4fb5-8d35-36ea4ee3d2af.png)

Seems somewhat apparent an exception is there just waiting to emit, but yet it does not.

**Comment by mwpowellhtx** [comment]
@En3Tho Yes, I am aware, I am not interested in `y` per se, like I said in the subject, **_I want the exception_**, but this is not emitting. Are you saying select the evaluation needs a completion, such as `ToArray` or `ToList` to realize this? That sounds logical, just to clarify that aspect.

**Comment by mwpowellhtx** [comment]
Ah okay 💡 I am satisfied, that is the key.

**Comment by En3Tho** [comment]
Yes. Select and many other methods in Enumerable class give you back a lazy enumerator which has to be "materialized" somehow.

**Comment by mwpowellhtx** [comment]
Back of mind I knew that, of course, this was a bit of a peculiar scenario in which to be reminded. Thanks... 🍻
