### ISSUE TITLE
[API Proposal]: Add a "CustomData" property to JsonPropertyInfo.

### ISSUE THREAD

**Issue by CodeSetting** [dotnet/runtime#81502]
### Background and motivation

When developing a custom `JsonTypeInfoResolver`, it is sometimes advantageous to maintain additional information about properties in the returned information. Currently, the only way to do this is by creating a dictionary, keyed by the `JsonPropertyInfo` instance, to maintain that information. While this is not terrible, it could be better with one of several possible changes to the `JsonPropertyInfo` class.

For example, one use case could be to cache the value of the `DefaultValueAttribute` for a property. This might later be useful in the function referenced by the `JsonPropertyInfo.ShouldSerialize` property. I use this example only because it is the simplest to explain. My actual use case is more complex.

### API Proposal

The easiest solution is to simply add a "consumer data" property of type "object?" to the `JsonPropertyInfo` class.

```csharp
public object? CustomData { get; set; }
```

In fact, this same simple change would likely be beneficial for a number of the classes in the `JsonTypeInfo` model.

### API Usage

```csharp
public class MyTypeInfoResolver : DefaultJsonTypeInfoResolver
{
  public override JsonTypeInfo GetTypeInfo(Type type, JsonSerializerOptions options)
  {
    JsonTypeInfo info = base.GetTypeInfo(type, options);
    foreach(JsonPropertyInfo property in info.Properties)
      property.CustomData = FetchExtraDataINeedLater(property);
    return info;
 }
}
```

### Alternative Designs

An alternative solution might be to add a protected constructor that allows a new instance to be created based on the properties of a pre-existing instance. This would allow derivations of the class to be created that can maintain any information that is required.

```csharp
protected JsonPropertyInfo(JsonPropertyInfo other) { ... }
```

A final alternative, exposing an interface (`IJsonPropertyInfo`) throughout the API, would provide the greatest flexibility and benefit. Unfortunately, this would also be a breaking change and introduce a probably unacceptable level of risk.

### Risks

The addition of a "consumer data" property should not represent any significant risk. In fact, many other frameworks already employ similar techniques. For example, Windows Forms controls have a "Tag" property that serves a similar purpose.

**Comment by eiriktsarpalis** [comment]
Looking at your example, it is not clear to me how the custom data on the JsonPropertyInfo is meant to be consumed. You mentioned it could be used by `ShouldSerialize`, however you can already do this by capturing state in your lambda:
```C#
object data = FetchExtraDataINeedLater(property);
property.ShouldSerialize = (object, value) => ShouldSerializeHelper(object, value, data);
```

**Comment by eiriktsarpalis** [comment]
> However, for more complex use cases, where you're not simply saving a lambda expression, this is not always possible.

In that case, it is not clear to me at all how `CustomData` would get referenced after you set it. Are you sure that this proposal would actually solve your use case?

**Comment by CodeSetting** [comment]
> In that case, it is not clear to me at all how CustomData would get referenced after you set it.

In my specific case, I need the custom data later in a `IJsonTypeInfoResolver.Modifiers` action. This action takes a `JsonTypeInfo` instance as a parameter, which provides a reference to its `Properties` property, which is a collection that provides references to  the `JsonPropertyInfo` instances it contains, each of which would provide a reference to the proposed `CustomData` property. As I mentioned, my use case is complex :)

That said, `JsonTypeInfo` is a public class accessible to anyone who calls the public method `IJsonTypeInfoResolver.GetTypeInfo` method (either directly or indirectly), so I could imagine other use cases...just none that I need at the moment.

> Are you sure that this proposal would actually solve your use case?

Yes, I am or I wouldn't have suggested it :)

**Comment by CodeSetting** [comment]
That is not my requirement. While I still believe the proposal has merit, and it would definitely help me, and I suspect others, there seems to be resistance to adding a property.

I'll keep my short-term workaround of using a `JsonPropertyInfo` dictionary for custom data as a less-than-optimal, long-term solution.  Regrettably, I can't spend more time justifying this proposal.  I'm facing a deadline on a larger project for which this feature is a small part.

**Comment by eiriktsarpalis** [comment]
> While I still believe the proposal has merit, and it would definitely help me, and I suspect others, there seems to be resistance to adding a property.

In order for a proposal to be considered (and possibly "resisted" as you put it) we need to understand the problem it is attempting to solve. It might be that we agree that this is a useful feature, that it is not, or that there already exists functionality addressing the problem.

> Regrettably, I can't spend more time justifying this proposal. I'm facing a deadline on a larger project for which this feature is a small part.

That is unfortunate. Please keep in mind that any new features would target .NET 8 in the earliest, which is slated for release next November. So if you are looking for an immediate solution then an API proposal is probably not the most efficient approach, but we might be able to offer workaround should you provide us with a repro. With that said, I'm going to close the issue since it needs more info.

**Comment by CodeSetting** [comment]
>> and possibly "resisted" as you put it

It seems I have given unintentional offense. The word "resist" was not intended as a pejorative. Sometimes resistance is a good thing.  For example, I honestly would hope you would resist a bad suggestion :)

>> we need to understand the problem it is attempting to solve

The basic requirement remains simple, a need for custom data associated with an instance of the public class `JsonPropertyInfo`. Generally, the specific usage of "custom" data is understood to be exactly that: "custom" (aka black box) :)

There is ample precedent elsewhere in the .NET framework with many classes providing a similar "custom data" property.

You were initially concerned I might not be able to reference the data.  I appreciated the concern.  I explained exactly how I would reference it: in a custom modifier (see `IJsonTypeInfoResolver.Modifiers`), getting the instance of `JsonPropertyInfo` via `IJsonTypeInfo.Properties`.

You suggested an alternative implementation. I appreciated and considered it as well. I explained that it wouldn't work in my case. Unfortunately, without spending a significant amount of time, it's not easy for me to explain why. Also, explaining the exact nature of the custom data might place me in breach of a non-disclosure agreement.

>> That is unfortunate.

It is. I wish I could spend more time. However, I don't get to set my deadlines :)

>>  if you are looking for an immediate solution

I wasn't. As mentioned, I have a functioning solution (using the `JsonPropertInfo` dictionary). I was simply hoping to use a cleaner approach sometime in the indeterminate future.

>> I'm going to close the issue

OK. If you think that's for the best.

**Comment by eiriktsarpalis** [comment]
> The basic requirement remains simple, a need for custom data associated with an instance of the public class JsonPropertyInfo. Generally, the specific usage of "custom" data is understood to be exactly that: "custom" (aka black box) :)

> You suggested an alternative implementation. I appreciated and considered it as well. I explained that it wouldn't work in my case.

If the requirement is holding user data on an object that only your code would be accessing (and needn't be passed on somehow by the serializer) then `ConditionalWeakTable` should absolutely meet your needs. See [this article](https://www.stevejgordon.co.uk/accessing-state-in-system-text-json-custom-converters) which concerns itself with a similar problem for `JsonConverter` instances.
