### ISSUE TITLE
SslStream_NegotiateClientCertificateAsyncTls13_Succeeds fails on non-portable builds with OpenSSL 3.0

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#81546]
When I build the repo using:
```
./build.sh /p:NoPgoOptimize=true --portablebuild false --runtimeconfiguration Release --librariesConfiguration Debug --subset clr+libs+libs.tests 
```
`SslStream_NegotiateClientCertificateAsyncTls13_Succeeds` fails with:
```
Interop+Crypto+OpenSslCryptographicException : error:0A00010A:SSL routines::wrong ssl version
Stack Trace:
  /home/tmds/repos/runtime/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.IO.cs(211,0): at System.Net.Security.SslStream.RenegotiateAsync[TIOAdapter](CancellationToken cancellationToken)
  /home/tmds/repos/runtime/src/libraries/System.Net.Security/tests/FunctionalTests/SslStreamNetworkStreamTest.cs(554,0): at System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_NegotiateClientCertificateAsyncTls13_Succeeds(Boolean sendClientCertificate)
```
The test does **not** fail with the portable build on the same system.

It happens on RHEL9, Fedora 36, and Fedora 37, which have OpenSSL 3.0.
I have not seen it on RHEL8, which has OpenSSL 1.1.

The non-portable build links directly with OpenSSL, while the portable build goes through a shim.

@wfurt @vcsjones @bartonjs any idea what may be causing the difference?

cc @omajid

**Comment by bartonjs** [comment]
If something works in portable, but not in direct, then it's probably a bad `NEED_OPENSSL_something` precondition (or `FEATURE_DISTRO_AGNOSTIC_SSL` precondition, but that feels less likely).

https://github.com/dotnet/runtime/blob/d320fd90a2976b388169dd51b3732ad01bcb4266/src/native/libs/System.Security.Cryptography.Native/pal_ssl.c#L486-L509 seems suspicious.  That probably wants to be `#ifdef NEED_OPENSSL_1_1 || NEED_OPENSSL_3_0`.  But there might be others.

**Comment by wfurt** [comment]
That block would not run with OpenSSL 3, right? I think the intentions to avoid OpenSSL 1.0. 
e.g. the proposed change look good to me.

**Comment by tmds** [comment]
> seems suspicious. That probably wants to be #ifdef NEED_OPENSSL_1_1 || NEED_OPENSSL_3_0. But there might be others.

Yes, that's it, with another like it. Thanks!
