### ISSUE TITLE
[release/8.0-preview1] clang-9 causing build failures in linux arm64

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#81555]
Affecting the `release/8.0-preview1` internal rolling build. Example: https://dev.azure.com/dnceng/internal/_build/results?buildId=2102620&view=results

cc @mmitche @hoyosjs @jkoritzinsky @agocke

Affected queues:
    - `CoreCLR Product Build linux arm64 release` - https://dev.azure.com/dnceng/internal/_build/results?buildId=2102620&view=logs&j=f885dbec-8192-5917-c4f3-ae9a02ec6156&t=38bad756-fc6a-5edc-429b-a47524e1b030
    - `linux-arm64 release AllSubsets_Mono` - https://dev.azure.com/dnceng/internal/_build/results?buildId=2102620&view=logs&j=310dc301-e421-594f-7aee-252ab13d3239&t=008ea0ed-a691-5bf9-cc79-c6abd57b1aab
    - `linux-arm64 release AllSubsets_Mono_LLVMJIT LLVMJIT` - https://dev.azure.com/dnceng/internal/_build/results?buildId=2102620&view=logs&j=534f645c-cc65-50fc-aadd-4d0c6b9dd8f8&t=8d7e94c8-13dc-5af8-c54a-893e62f7e49d
    - `linux-arm64 release AllSubsets_Mono_LLVMAOT LLVMAOT` - https://dev.azure.com/dnceng/internal/_build/results?buildId=2102620&view=logs&j=32edc0c6-a0eb-5eaf-91ea-42a8a9c9d6ad&t=882c7357-d1f3-52e7-710c-1c032d7a9315
    - `Libraries Build linux arm64 Release` - https://dev.azure.com/dnceng/internal/_build/results?buildId=2102620&view=logs&j=a7185a84-0100-5e66-b360-01f256e68ff9&t=9042869a-47ff-55ee-f646-bdc9d047cbd3
    - `CoreCLR Product Build linux arm64 release PGO` - https://dev.azure.com/dnceng/internal/_build/results?buildId=2102620&view=logs&j=c2e749ed-3e2c-51d8-078b-193121b9b774&t=202ba399-972e-576e-a62d-2f502b3545dc
    - `linux-arm64 release CrossAOT_Mono crossaot` - https://dev.azure.com/dnceng/internal/_build/results?buildId=2102620&view=logs&j=143489d5-74d4-512f-2ac7-0f45bc6f28f4&t=8447cb88-0a79-55cb-e8f2-5f8cf1455fd8

```
CMake Error at /usr/share/cmake-3.25/Modules/CMakeTestCCompiler.cmake:70 (message):
  The C compiler

    "/usr/bin/clang-9"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /__w/1/s/artifacts/obj/coreclr/linux.arm64.Release/CMakeFiles/CMakeScratch/TryCompile-oItv5b
    
    Run Build Command(s):/usr/bin/make -f Makefile cmTC_1410a/fast && /usr/bin/make  -f CMakeFiles/cmTC_1410a.dir/build.make CMakeFiles/cmTC_1410a.dir/build
    make[1]: Entering directory '/__w/1/s/artifacts/obj/coreclr/linux.arm64.Release/CMakeFiles/CMakeScratch/TryCompile-oItv5b'
    Building C object CMakeFiles/cmTC_1410a.dir/testCCompiler.c.o
    /usr/bin/clang-9 --target=aarch64-linux-gnu --gcc-toolchain=/crossrootfs/usr --sysroot=/crossrootfs    -MD -MT CMakeFiles/cmTC_1410a.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_1410a.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_1410a.dir/testCCompiler.c.o -c /__w/1/s/artifacts/obj/coreclr/linux.arm64.Release/CMakeFiles/CMakeScratch/TryCompile-oItv5b/testCCompiler.c
    Linking C executable cmTC_1410a
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_1410a.dir/link.txt --verbose=1
    /usr/bin/clang-9 --target=aarch64-linux-gnu --gcc-toolchain=/crossrootfs/usr --sysroot=/crossrootfs -Wl,--rpath-link=/crossrootfs/lib/aarch64-linux-gnu -Wl,--rpath-link=/crossrootfs/usr/lib/aarch64-linux-gnu -Wl,--rpath-link=/crossrootfs/lib/aarch64-linux-gnu -Wl,--rpath-link=/crossrootfs/usr/lib/aarch64-linux-gnu -fuse-ld=lld  CMakeFiles/cmTC_1410a.dir/testCCompiler.c.o -o cmTC_1410a 
    ld.lld: error: cannot open crt1.o: No such file or directory
    ld.lld: error: cannot open crti.o: No such file or directory
    ld.lld: error: cannot open crtbegin.o: No such file or directory
    ld.lld: error: unable to find library -lgcc
    ld.lld: error: unable to find library -lgcc_s
    ld.lld: error: unable to find library -lc
    ld.lld: error: unable to find library -lgcc
    ld.lld: error: unable to find library -lgcc_s
    ld.lld: error: cannot open crtend.o: No such file or directory
    ld.lld: error: cannot open crtn.o: No such file or directory
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [CMakeFiles/cmTC_1410a.dir/build.make:100: cmTC_1410a] Error 1
    make[1]: Leaving directory '/__w/1/s/artifacts/obj/coreclr/linux.arm64.Release/CMakeFiles/CMakeScratch/TryCompile-oItv5b'
    make: *** [Makefile:127: cmTC_1410a/fast] Error 2

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:16 (project)

-- Configuring incomplete, errors occurred!
See also "/__w/1/s/artifacts/obj/coreclr/linux.arm64.Release/CMakeFiles/CMakeOutput.log".
See also "/__w/1/s/artifacts/obj/coreclr/linux.arm64.Release/CMakeFiles/CMakeError.log".
/__w/1/s
/__w/1/s/artifacts/obj/coreclr/linux.arm64.Release /__w/1/s
Executing make   runtime alljits paltests_install nativeaot spmi  -j 4
make: *** No rule to make target 'runtime'.  Stop.
```

I assume these two other failures caused by the above lack of artifacts generated:

  - `Installer Build and Test coreclr linux_arm64 Release` - https://dev.azure.com/dnceng/internal/_build/results?buildId=2102620&view=logs&j=465f3901-d6d9-523b-895c-4949f96bfbe0&t=4d9a4efa-1653-5a96-cd25-39e0ad3d0da6
  - `PGO Installer Build and Test coreclr linux_arm64 Release` - https://dev.azure.com/dnceng/internal/_build/results?buildId=2102620&view=logs&j=85085d93-92d8-5d35-0b38-0673aea2448d

```
Downloading artifacts for build: 2102620
##[error]Artifact CoreCLRProduct___linux_arm64_release not found for build 2102620. Please ensure you have published artifacts in any previous phases of the current build.
```

**Comment by hoyosjs** [comment]
This seems to be https://github.com/dotnet/arcade/issues/12395

**Comment by mmitche** [comment]
Thanks @hoyosjs. @carlossanlop can you port that?

**Comment by carlossanlop** [comment]
@mmitche sure I could do it, but I think it's covered by the arcade flow @hoyosjs just mentioned, right? https://github.com/dotnet/runtime/pull/81354

**Comment by mmitche** [comment]
That's under **eng/pipelines/common**/templates/pipeline-with-resources.yml not, **eng/common/**templates/pipeline-with-resources.yml. It's runtime specfiic info
