### ISSUE TITLE
Console app wont load if AspNetCore runtime is not installed

### ISSUE THREAD

**Issue by ocalvo** [dotnet/runtime#81554]
### Description

For an app that supports both runtimes: CoreNET and AspNetCore if the dotnet environment does not have the AspNetCore installed, the app will fail to load

### Reproduction Steps

1. Install dotnet and make sure that AspNetCore runtime is not installed.
`dotnet --list-runtimes'
```
Microsoft.NETCore.App 7.0.0 [C:\src\os1\tools\dotnet-runtime-latest-win-x64\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.1 [C:\src\os1\tools\dotnet-runtime-latest-win-x64\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.2 [C:\src\os1\tools\dotnet-runtime-latest-win-x64\shared\Microsoft.NETCore.App]
```
3. Create a new .NET Core console app in C#
4. Modify the runtime config file:
```
{
  "runtimeOptions": {
    "tfm": "net6.0",
    "frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "6.0.0"
      },
      {
        "name": "Microsoft.AspNetCore.App",
        "version": "6.0.0"
      }
    ]
  }
}
```
6. Execute `dotnet.exe --roll-forward LatestMajor MyConsoleApp.dll`

### Expected behavior

App will load and run as normal under the installed NETCore.App runtime.

### Actual behavior

App fails to load with this error:
```
You must install or update .NET to run this application.

App: C:\Users\ocalvo\source\repos\MyConsoleApp\MyConsoleApp\bin\Debug\net6.0\MyConsoleApp.dll
Architecture: x64
Framework: 'Microsoft.AspNetCore.App', version '6.0.0' (x64)
.NET location: C:\src\os1\tools\dotnet-runtime-latest-win-x64\

No frameworks were found.

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=6.0.0&arch=x64&rid=win10-x64
```

### Regression?

Unknown.

### Known Workarounds

Use this MSBuild code in `Directory.Build.Targets`

```
 <Target Name="__RemoveAspNetCoreApp" BeforeTargets="ResolveTargetingPackAssets" Condition="'@(FrameworkReference)' != ''" >
    <ItemGroup>
      <FrameworkReference Remove="Microsoft.AspNetCore.App" />
    </ItemGroup>
  </Target>
```

### Configuration

.NET 7
Windows 11 22661
x64
Not specific to this config.

**Comment by davidfowl** [comment]
What's the scenario here?

**Comment by ocalvo** [comment]
> What's the scenario here?

A highly secure build environment (e.g. Official Windows Build machines) require to minimize attack surface, so it was decided to not install runtimes that are not needed to run build tools.

**Comment by jkotas** [comment]
Why do your build tools depend on AspNetCore? 

If the app declares in runtime config that it depends on AspNetCore, it fails to start unless AspNetCore runtime is installed. I do not see anything wrong with that.

**Comment by ocalvo** [comment]
The app is a console app that is used in a restrictive build environment. So the AspNetCore runtime environment was removed (by design) to reduce attack surface. 
This started to happen after we took a dependency in some NuGet packages that also target ApsNetCore (that are also actually run inside and AspNet server)

**Comment by davidfowl** [comment]
The application has a dependency that pulls in ASP.NET Core.

**Comment by jkotas** [comment]
It means that you cannot afford to take this dependency for restricted build environments. 

Or you can use the (unreliable) hack above and hope that the dependency is not going to need something from ASP.NET.

**Comment by ocalvo** [comment]
Thanks @davidfowl , this clarifies the issue.
