### ISSUE TITLE
Fix GC/API/WeakReference/Finalize2 to be more robust

### ISSUE THREAD

**Issue by swgillespie** [dotnet/runtime#8158]
This test does `Collect`/`WaitForPendingFinalizers`/`Collect` [here](https://github.com/dotnet/coreclr/blob/master/tests/src/GC/API/WeakReference/Finalize2.cs#L139-L141) before asserting that all finalizers have run, which is not a safe assumption and prone to races between the main and finalizer threads. The fix is to do the collect/wfpf/collect calls in a loop while asserting that forward progress is being made, failing the test if not.

https://github.com/dotnet/coreclr/pull/11735#issuecomment-302595813 https://github.com/dotnet/coreclr/issues/4093#issuecomment-296853982

**Comment by davidwrighton** [comment]
Its been years, and we haven't seen reports of this failing. I'm going to close this.
