### ISSUE TITLE
IHttpClientFactory change HttpClientHandler credentials 

### ISSUE THREAD

**Issue by Val9000** [dotnet/runtime#81594]
Hello,

so what is my setup is:

- ip devices which use digest authentication. 
- to talk to each device I need to add set a handler the following:

`HttpClientHandler _handler = new HttpClientHandler()
        {
            Credentials = new NetworkCredential("root", "pass")
        }`
        
Now I heard to avoid some problems one, should use IHttpClientFactory, so we don't create new clients all the time.

Now the problem is... in program.cs I can only set the handler once... how can I change the credentials ? 

I've been googling and searching but I couldn't find a good solution.
I found this discussion: https://github.com/dotnet/extensions/issues/521 but unfortunately it didn't help me :( There is one "solution" by "[tsaluszewski] which too me doesn't seem like a solution because he is creating a new HttpClient everytime the credentials change....So I was like what is the point of using IHttpClientFactory? 

I would appreciate any help !!

**Comment by CarnaViire** [comment]
Hi @Val9000,

It is true that NetworkCredentials are tied to the handler itself, so in order to have different credentials (being automatically processed by HttpClient), you would need an HttpClientHandler/HttpClient per Credentials. That being said, if you are up to going a bit low-level and sending authentication headers manually, you can go around having only one HttpClient 😄

1. Automatic/NetworkCredentials way:
    - If your devices/credentials list is known in advance, you can have a named/typed client set up in HttpClientFactory per device/credentials
    - If you have to update credentials dynamically, then you can't use HttpClientFactory. But you can manage a pool of long-lived HttpClients yourself -- reusing the client as long as the credentials used are the same. You are advised to NOT recreate HttpClients *per request*, but creating a limited amount of long-lived HttpClients is perfectly fine (don't forget to set [PooledConnectionLifetime](https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/http/httpclient-guidelines#dns-behavior)).

2. Manual authentication way:
    - With that, you can reuse single HttpClient, as authentication is passed as headers, so if set manually, it can be changed per-request
    - However, you would need to process server's challenge manually. There's currently no publicly available API in .NET, but you can copy from sources how HttpClient does digest auth, or there potentially are Nuget packages which will do the processing for you
    - Here is an example of manual NTLM authentication, it is similar to digest auth in terms of: client sends request -> server replies 401 with challenge -> client processes challenge -> client sends request again with additional auth header https://github.com/wfurt/Ntlm/blob/d2bd5bb4e72e7044f1d20462d0f474b8d262a9e8/Program.cs#L28

Let me know if you need any help with either of these options.
