### ISSUE TITLE
Unable to sign StandardOptimizationData.mibc

### ISSUE THREAD

**Issue by mmitche** [dotnet/runtime#81601]
### Description

Failed to sign the `StandardOptimizationData.mibc` file.

### Reproduction Steps

See https://artprodcus3.artifacts.visualstudio.com/Ab55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy9wcm9qZWN0SWQvN2VhOTExNmUtOWZhYy00MDNkLWIyNTgtYjMxZmNmMWJiMjkzL2J1aWxkSWQvMjEwMzM0MS9hcnRpZmFjdE5hbWUvTG9ncy1QcmVwYXJlU2lnbmVkQXJ0aWZhY3Rz0/content?format=file&subPath=%2Fartifacts%2Ftmp%2FRelease%2FSigning%2FSign.2023.02.03.00.16.18.log in https://dev.azure.com/dnceng/internal/_build/results?buildId=2103341&view=results

### Expected behavior

File is signed.

### Actual behavior

```
37> 03.00.26.40 Failed to sign 'D:\a\_work\1\s\artifacts\tmp\Release\ContainerSigning\3569\tools\StandardOptimizationData.mibc' (OperationId: 928888e7-a763-4c8d-8a5b-f4ca651eea3b) because of  An exception occurred in the NEO Static Signer service.
exception: Sign operation failed for: "D:\Sign\928888e7-a763-4c8d-8a5b-f4ca651eea3b\ae1c6c19-5b76-4915-a99d-b41746d82867\StandardOptimizationData.mibc" For RequestId: 928888e7-a763-4c8d-8a5b-f4ca651eea3b. Command execution result from the tool: Done Adding Additional Store
Number of errors: 1
SignTool Error: This file format cannot be signed because it is not recognized.
SignTool Error: An error occurred while attempting to sign: D:\Sign\928888e7-a763-4c8d-8a5b-f4ca651eea3b\ae1c6c19-5b76-4915-a99d-b41746d82867\StandardOptimizationData.mibc
```

**Comment by mmitche** [comment]
Currently blocking preview1. I think we can probably just avoid signing this specific binary for p1.

**Comment by AndyAyersMS** [comment]
Fix in progress: https://github.com/dotnet/runtime/pull/81623
