### ISSUE TITLE
XmlSerializer: provide more details in error message "Compiling JScript/CSharp scripts is not supported"

### ISSUE THREAD

**Issue by WolfgangHG** [dotnet/runtime#81613]
### Description

Attached sample uses an approach to serialize a "System.Drawing.Color" object to XML that was suggested at [https://stackoverflow.com/questions/3280362/most-elegant-xml-serialization-of-color-structure/8638106](https://stackoverflow.com/questions/3280362/most-elegant-xml-serialization-of-color-structure/8638106) and which worked in .NET 4.8. 

This approach fails with .NET6 und 7. The goal of this ticket is not to complain about this behavior change, but about the really bad error message that is thrown: "Compiling JScript/CSharp scripts is not supported". There is no detail information, so in a larger class structure, you have no clue where to look. I found some other websites that talk about this error, but I did not find any issue to improve it. So I created this ticket.

### Reproduction Steps

Execute the sample with framework 4.8 to see that the suggested approach works. Execute it with .NET6 or 7 to see the error.

[XmlSerializerColor.zip](https://github.com/dotnet/runtime/files/10582680/XmlSerializerColor.zip)
(attached sample has a small bug in "XmlColor6.ReadXml": it should use "reader.ReadElementContentAsString" instead of "reader.ReadString". The workaround section already contains the fixed code)

A helper class "XmlColor" was defined:

``` 
  public class XmlColor48
  {
    private Color m_value = Color.Empty;

    //constructors...

    //some implicit conversion operators...

    [XmlText]
    public string Default
    {
      get
      {
        return this.m_value... //convert Color to string
      }
      set
      {
        this.m_value = ... //convert value to Color
      }
    }

  }
```

This was defined on a property of the class that is to be serialized:

```
    [XmlElement(Type = typeof(XmlColor48))]
    public Color Color
    {
      get; set;
    }
```` 

### Expected behavior

The error message should point to the piece of code that caused this failure.

### Actual behavior

A "something went wrong - search the needle in the hay stack" error is thrown.

### Known Workarounds

Implement interface "IXmlSerializable" instead (class "XmlColor6" in the sample):

```
  public class XmlColor6 : IXmlSerializable
  {
    private Color m_value = Color.Empty;

    //constructors...

    //some implicit conversion operators...

    public void WriteXml(XmlWriter writer)
    {
      string argb =... //convert Color to string
      writer.WriteString(argb);
    }

    public void ReadXml(XmlReader reader)
    {
      string argb = reader.ReadElementContentAsString();
      this.m_value = ... //convert string to Color
    }

    public XmlSchema GetSchema()
    {
      return (null);
    }
```

Use it this way:
```
    public XmlColor6 Color
    {
      get; set;
    }
```

**Comment by WolfgangHG** [comment]
After pulling and compiling the .NET8 runtime from Git and digging further in the code, I am confused: The error occurs in "System.Xml.Serialization.CodeGenerator.InternalConvert" (line 1237) - an "CodeGeneratorConversionException" is thrown, and it should have all information to create a meaningful exception like "could not convert from Color to XmlColor", but the exception is just caught in "System.Xml.Serialization.TempAssembly.ctor" (line 74). 
The catch block then sets a fallback flag, but there is no fallback besides throwing a "PlatformNotSupportedException":

```
            // We will make best effort to use RefEmit for assembly generation
            bool fallbackToCSharpAssemblyGeneration = false;

            if (!containsSoapMapping && !TempAssembly.UseLegacySerializerGeneration)
            {
                try
                {
                    _assembly = GenerateRefEmitAssembly(xmlMappings, types);
                }
                // Only catch and handle known failures with RefEmit
                catch (CodeGeneratorConversionException)
                {
                    fallbackToCSharpAssemblyGeneration = true;
                }
            }
            else
            {
                fallbackToCSharpAssemblyGeneration = true;
            }

            if (fallbackToCSharpAssemblyGeneration)
            {
                throw new PlatformNotSupportedException(SR.CompilingScriptsNotSupported);
            }
```

Why not rethrowing the "CodeGeneratorConversionException" instead of setting "fallbackToCSharpAssemblyGeneration" and adding a meaningful message to it? This would have helped me a lot in my sample.

After testing my sample with .NET 4.8 and all "break on exception" settings on, I see in the decompiled code that there was a real fallback instead of the "PlatformNotSupportedException" ("flag2" is the "fallbackToCSharpAssemblyGeneration" variable):
```
	if (flag2)
	{
		assembly = GenerateAssembly(xmlMappings, types, defaultNamespace, evidence, XmlSerializerCompilerParameters.Create(location), null, assemblies);
	}
````

This fallback actually worked and was removed in .NET6.

Also, why does "CodeGenerator.InternalConvert" decides that source "Color" and target "XmlColor" are not assignable in my sample? I have declared implicit operators, so an assignment should be possible. But this goes deep in "RuntimeType.IsAssignableFrom", where 15 years of C# practice are not enough ;-)

**Comment by krwq** [comment]
I suspect that didn't exist back when we ported the full framework code to .NET Core and we ended up throwing. I'll let serialization team handle that though.

**Comment by WolfgangHG** [comment]
Just to clarify: I don't request backporting the old serialization fallback (though in this case my initial code would have worked without modification). My main requirement is to rethrow the "CodeGeneratorConversionException" (which does currently not provide a meaningful message though it has all necessary information), instead of switching to a "PlatformNotSupportedException".

And maybe you could comment on my question why "RuntimeType.IsAssignableFrom" returns false though my sample declared the implicit operators. Shouldn't the xml deserialization be able to assign the XmlElement type to the property type through those implicit operators?

**Comment by WolfgangHG** [comment]
Thanks!

Could you comment on my question?

> ... why "RuntimeType.IsAssignableFrom" returns false though my sample declared the implicit operators. Shouldn't the xml deserialization be able to assign the XmlElement type to the property type through those implicit operators?

Modifying "RuntimeType.IsAssignableFrom" to check for implicit operators is probably a bit too much, but maybe this check could additionally be added in XmlSerializer. I don't know whether serialization would work afterwards or whether additional code would be necessary.
I could even try to do this modification myself...
