### ISSUE TITLE
PlatformNotSupportedException thrown by System.Drawing.Common on net7.0-windows10.0.22621.0

### ISSUE THREAD

**Issue by RaphMar2021** [dotnet/runtime#81639]
### Description

When the runtime is set to net7.0-windows10.0.22621 (.NET 7 but with Windows 10.0.22621.0 as target OS), System.Drawing.Common is throwing a PlatformNotSupportedException exception.

It's should be supported, the target OS is Windows 11 22H2.

### Reproduction Steps

1 : Create a console app on .NET 7
2 : Set the target OS to Windows & the target OS version to 10.0.22621 
Now it should look like this : 
![image](https://user-images.githubusercontent.com/81994075/216781997-37879f5c-e5d2-4541-aeb4-4f905cc65fd0.png)
3 : Install the System.Drawing.Common NuGet package
4 : Create a Graphics class (`var g = new Graphics();`)
5 : Run the console app and see the exception come.

### Expected behavior

It should work because the target OS is Windows.

### Actual behavior

It throws an PlatformNotSupportedException exception.

### Configuration

The code is running on .NET 7 (with Windows 11 22H2 set as target OS)

My OS is Windows 11 22H2 x64 (build 10.0.22621.1105, vanilla)

My PC is a ThinkPad T460

**Comment by ViktorHofer** [comment]
Hello @RaphMar2021. Thanks for reporting the issue. Can you please share a minimal repro for us to look into this further?

> System.Drawing.Common NuGet package

Which version of the package do you reference?

**Comment by RaphMar2021** [comment]
> Hello @RaphMar2021. Thanks for reporting the issue. Can you please share a minimal repro for us to look into this further?
> 
> > System.Drawing.Common NuGet package
> 
> Which version of the package do you reference?

The latest version of the NuGet Package

Here's a screenshot of my problem :
![image](https://user-images.githubusercontent.com/81994075/216787416-7c348119-fc35-412a-bd3e-7626994087b6.png)

**Comment by smasher164** [comment]
@RaphMar2021 Do you mind specifying the exact version you mean by latest?
Also, if you are able to, please provide a minimal repro.

Thanks

**Comment by ViktorHofer** [comment]
@RaphMar2021 we just talked about this issue in one of our triage meetings. In addition to what @smasher164 wrote above, here are a few observations:

Based on your call stack, it looks like you are interpreting and then loading assemblies on demand. Can you please share the assembly loading code block? We believe that your logic doesn't respect runtime specific assets from nuget packages, in this case System.Drawing.Common. Note that many packages in the ecosystem contain runtime specific assets, especially packages from dotnet/runtime. The dotnet host respects runtime specific assets and those are encoded in a deps.json file as runtimeTarget elements.

**Comment by RaphMar2021** [comment]
I didn't loaded System.Drawing.Common at runtime, it's in the referenced assemblies of Visual Studio

**Comment by carlossanlop** [comment]
Can you please share your assembly loading code? Please make sure it respects runtime-specific assemblies, especially if they come from nuget packages.
