### ISSUE TITLE
packages.microsoft.com apt update is veeerrryy slooow (1-2 sec per source)

### ISSUE THREAD

**Issue by maloo** [dotnet/runtime#81645]
Could someone take a look at the performance of packages.microsoft.com where dotnet ubuntu packages are hosted? When I do apt update (Ubuntu/WSL) the entire list of package sources are updated in less than one second, except for the MS sources. They take 1-2 seconds each. It is not critical, but I assume MS has the hosting resources to return a few lines of text so I guess something is wrong here. I'm located in Sweden if that helps. Maybe packages.ms isn't geo replicated?
Since apt update is a common operation it is quite annoying.

The slow sources (the ubuntu ones have some with bigger payload, and below ones take the same amount of time):
Get:24 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main armhf Packages [5598 B]
Get:25 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main all Packages [372 B]
Get:26 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main arm64 Packages [9401 B]
Get:27 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages [44.2 kB]

@richlander

**Comment by richlander** [comment]
Thanks for the report. I will pass it on.

**Comment by richlander** [comment]
Just tried now. I cannot repro. Everything seems fast. Try again?

**Comment by maloo** [comment]
Yes, seems faster now. Even started a new container and added the MS sources to get GET instead of HIT. But still looks much better now. Maybe some server maintenance ...
