### ISSUE TITLE
Trying to verify HttpClient.GetStreamAsync return type

### ISSUE THREAD

**Issue by mwpowellhtx** [dotnet/runtime#81659]
### Background and motivation

As subject states. Trying to verify that `responseTask.AssertIsType<Task<Stream>>()`, for instance, but getting some mangled plumbing type response.

### API Proposal

Sort of following up on the [_renaming_](11693) issue, but in general what else to expect.

### API Usage

My client wrapper is returning a simple `Task` depending on a configured `RequestMethod`, so I want to verify the returned type in this instance is in fact `Task<Stream>`.

### Alternative Designs

I do not have any great suggestions here except to suggest emitting an internal struct instance, even one that is casting somehow either implicitly, etc, does not bode well, especially when I want to verify the documented type `Task<Stream>`, because simply put, _"it ain't that"_. I'm not sure what else you do, but y'all are closer to the code than I am. For my usage, the `Task` is a means to an end, nothing more than that, to gain the `Task<T>.Result`.

### Risks

Unit test report as follows, along these lines. Obviously I don't care about any `System.Runtime.CompilerServices.AsyncTaskMethodBuilder`, I want the `Task`.

```
5)   My scenario() [05] (Scenario): Verify the request 
      Duration: 3.6 sec

      Message: 
Assert.IsType() Failure
Expected: System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.IO.Stream, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
        Actual:   System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.IO.Stream, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Net.Http.HttpClient+<GetStreamAsyncCore>d__51, System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]]

      Stack Trace: 
VolumeStreamApiTests.VerifyRequestAsync(ClientTwitterContextV2 context, Endpoint endpoint) line 96
<>c__DisplayClass11_0.<ConfigureScenario>b__4() line 122
<>c__DisplayClass4_0.<x>b__0(IStepContext c)
StepInvoker.<RunAsync>b__6_1()
<<Invoke>b__1>d.MoveNext()
--- End of stack trace from previous location ---
```

Stemming from the `Task<Stream> HttpClient.GetStreamAsync(requestUri)` call. If it is casting to Task<Stream> this should probably be done internally and not left to call side exposure. It's just sloppy IMO.

**Comment by mwpowellhtx** [comment]
Bit of a chagrin, modestly acceptable short-medium term workaround:

```csharp
var responseTask = context.RequestAsync(endpoint);
responseTask.GetType().BaseType.Equals(typeof(Task<Stream>));
```

This does seem to work, but direct type verification seems out of the question, at least under the present tense configuration.

**Comment by huoyaoyuan** [comment]
Please do not verify the detailed implementation type (return from `GetType()`). It's not part of the contract and may change at any time.

Could you share more code about the code you were verifying the type? For example how you use `RequestAsync` to get the return value.

**Comment by stephentoub** [comment]
Methods declared to return a type T are allowed to return a T or types derived from T; that's inherent to the design of the .NET type system, and it happens all over the place.  In this case, a method that is typed to return a `Task<Stream>` can return a type derived from `Task<Stream>`, which is what is happening here.  This also happens all over the place.  I'm not sure what exactly you're trying to verify with your asserts, but trying to validate that the return type is exactly a `Task<Stream>` rather than a `Task<Stream>` or something that derives from it is inherently flawed, as @huoyaoyuan points out; you're checking internal implementation details that can and do change.

**Comment by mwpowellhtx** [comment]
Indeed that's true that is accurate. Good point, thank you. As verified:

```csharp
var _is = responseTask is Task<Stream>; // true
```

**Comment by mwpowellhtx** [comment]
I am still a bit confused, how can a struct, which we have in this instance, be derived from a class, which the method signature is purported to be returning? This is now allowed, AFAIK, but the language definition, correct? In other words, for `responseTask is Task<Stream>` to be `true`, the return type would need to be derived from `Task<TResult>`, would it not? But isn't `System.Runtime.CompilerServices.AsyncTaskMethodBuilder<TResult>`a struct? Further, is not derived from anything, so hence me wondering, is there an implicit type conversion going on there.

**Comment by MihaZupan** [comment]
The builder is a struct, but `AsyncStateMachineBox` is a class that derives from `Task<TResult>`.

```
Actual:
AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[Stream],[HttpClient+<GetStreamAsyncCore>d__51]
```

https://github.com/dotnet/runtime/blob/f8daacff9d5ac3cad277fba8a97aefe72865ae45/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs#L273-L274

**Comment by mwpowellhtx** [comment]
Interesting. Thanks...
