### ISSUE TITLE
Support WindowStyle without UseShellExecute in ProcessStartInfo and Process implementation on Windows

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#81681]
In PowerShell repository we have to use pinvoke to support WindowStyle without UseShellExecute.

Today .Net supports WindowStyle only if UseShellExecute is true
https://github.com/dotnet/runtime/blob/58719ec90b3bbae527dd81685bf8670b993fe8f9/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Win32.cs#L23-L30

Current request is to add support for WindowStyle (on Windows) if UseShellExecute is false
https://github.com/dotnet/runtime/blob/58719ec90b3bbae527dd81685bf8670b993fe8f9/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Windows.cs#L427

It looks like a very simple implementation.
We would like confirmation soon from the .Net team that this can be implemented in .Net 8 so that we can avoid unnecessary work in the PowerShell repository.

**Comment by Jozkee** [comment]
Sounds like this is just setting wShowWindow on the [STARTUPINFO](https://learn.microsoft.com/windows/win32/api/processthreadsapi/ns-processthreadsapi-startupinfoa) structure we pass to CreateProcess, applying the same mapping we do on StartWithShellExecuteEx. If so, a PR would be very welcome.

Should it be invalid to allow ProcessStartInfo.WindowStyle with ProcessStartInfo.CreateNoWindow?

**Comment by iSazonov** [comment]
> Should it be invalid to allow ProcessStartInfo.WindowStyle with ProcessStartInfo.CreateNoWindow?

PowerShell throws in the case.

**Comment by Jozkee** [comment]
@iSazonov are you interested in working on this?

**Comment by iSazonov** [comment]
Maybe @jborean93 grab this. If no I will look a few weeks later.

**Comment by jborean93** [comment]
I can certainly try if I have time.

**Comment by jborean93** [comment]
I've opened a draft PR https://github.com/dotnet/runtime/pull/82662. I need to figure out how to build and run the tests so I can add some tests for this new addition. I'm unsure where the docs for https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.createnowindow?view=net-7.0#system-diagnostics-processstartinfo-createnowindow live to add an entry stating `CreateNoWindow` cannot be true if the `WindowStyle` is not `Normal`.

**Comment by iSazonov** [comment]
@jborean93 Docs for build and test https://github.com/dotnet/runtime/blob/main/docs/workflow/README.md

**Comment by adamsitnik** [comment]
> I need to figure out how to build and run the tests s

```cmd
# to build the whole repo
.\build.cmd -rc Release -subset clr+libs+libs.tests
# to rebuild the library
.\dotnet.cmd build .\src\libraries\System.Diagnostics.Process\System.Diagnostics.Process.sln
# to run the tests
.\dotnet.cmd build .\src\libraries\System.Diagnostics.Process\tests\System.Diagnostics.Process.Tests.csproj /t:Test
```

**Comment by jborean93** [comment]
Thanks for the guides, was able to add some tests. It seems like CI is failing with some problems with the `Http.Functional.Tests` which seem unrelated (it's also failing on the Linux side).

> 2023-03-02T05:18:29.5576910Z D:\a\_work\1\s\.packages\microsoft.dotnet.helix.sdk\8.0.0-beta.23123.2\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(90,5): error : Work item System.Net.Http.Functional.Tests in job bba582ab-b7c6-4367-ab20-af65211d971e has failed. [D:\a\_work\1\s\src\libraries\sendtohelixhelp.proj]

As for the behaviour of `CreateNoWindow` with `WindowStyle` being set I've had to remove the exception as there was code internally that was setting both and it would break anybody else that might be accidentally setting both currently. So for now the `WindowStyle` will set the entry in the STARTUPINFO structure at the same time as `CreateNoWindow`.
