### ISSUE TITLE
Mono HelloWorld is broken for AOT

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#81696]
Steps:
```bash
./build.sh Mono+Libs -c Release
cd src/mono/sample/HelloWorld
# enable AOT and change config to Release in the Makefle
make run
```
It will fail in msbuild complaining on extra arguments in MonoAotCompiler (PGO-related). cc @akoeplinger 

Also, it'd be nice to add an LLVM-AOT support to the sample please 🙂

**Comment by SamMonoRT** [comment]
@kotlarmilos - This should be working now, please close this issue after validation.

**Comment by kotlarmilos** [comment]
The Apple mobile sample is updated to work using a makefile. This one requires some minor changes.
