### ISSUE TITLE
JsonConverterAttribute not working with source-gen when converter is internal type

### ISSUE THREAD

**Issue by krwq** [dotnet/runtime#81703]
Manifestation and description of this issue is here: https://github.com/dotnet/runtime/issues/81702
Note: I opened two issues so that this is tracked by both areas

We should figure out what to do on the JSON side.

One of the options is to use Activator.CreateInstance somewhere but that seems a bit ugly and we should make sure we won't break trimmability with that.

**Comment by eerhardt** [comment]
> and we should make sure we won't break trimmability with that.

The trimmer and AOT compiler can recognize certain Reflection patterns and make sure the types, and their constructors, are preserved correctly. Basically something like:

`Activator.CreateInstance(Type.GetType("System.BinaryDataConverter, System.Memory.Data"))`

should be recognized by the trimmer, not produce a warning, and preserve the type and ctor when trimming.

cc @vitek-karas @sbomer
