### ISSUE TITLE
Trying to verify continuation task web response result

### ISSUE THREAD

**Issue by mwpowellhtx** [dotnet/runtime#81708]
### Description

Of internal type `System.Threading.Tasks.ContinuationTaskFromResultTask<System.IO.Stream>`. This is apparently internal, cannot reference the type for verification purposes.

### Reproduction Steps

Basically that, along lines of:

```csharp
responseTask.AssertIsAssignableFrom<Task<Stream>>(); // fails
```

But I cannot do this either:

```charp
responseTask.AssertIsAssignableFrom<ContinuationTaskFromResultTask<Stream>>(); // does not compile
```

### Expected behavior

I want to verify the responseTask I have is at least a `Task<Stream>` as expected. In this case, also happens to be a `ContinuationTaskFromResultTask<Stream>`.

### Actual behavior

Does not compile.

**Comment by MihaZupan** [comment]
The library you use for unit testing likely has a helper to check the inverse as well
```c#
foo.Should().BeAssignableTo<T>();
Assert.IsInstanceOf<T>(foo);
Assert.True(foo is T);
```

But the question from #81659 remains - why are you testing this at all?
If a signature is promising `Task<Stream>`, you don't have to unit test that the language isn't lying to you.

**Comment by mwpowellhtx** [comment]
Leaving aside the test framework, even if I do something simple like `responseTask is Task<Stream>` that yields `false` as well...

**Comment by stephentoub** [comment]
> Leaving aside the test framework, even if I do something simple like responseTask is Task<Stream> that yields false as well...

If you have:
```C#
Task<Stream> task = ...;
bool isTask = task is Task<Stream>;
Console.WriteLine(isTask);
```
the only way that'll print out false is if `task` is null.  If it prints out false and isTask isn't null, there's a massive type safety hole in the runtime, and that's not something you need to be testing for.

**Comment by mwpowellhtx** [comment]
It is possible I am trying to verify something that has not seen task activation yet, in which case it would not be `Task<Stream>` yet, either.

This is what I have:

![image](https://user-images.githubusercontent.com/1824187/217047816-b2883527-abd5-468d-a6ac-3c3db744c898.png)

And literally in my watch window.

![image](https://user-images.githubusercontent.com/1824187/217048077-40b501bc-3f9e-472c-a37f-592fcd29cfdf.png)

Which is being generated by:

![image](https://user-images.githubusercontent.com/1824187/217048396-38aa894a-4a3b-45c8-9572-c0922a0513d4.png)

That could be `Task<Stream>` (in this case) or a simple `Task`, AFAIK, depending on the request method.

`Client` is the `HttpClient`, making a web request.

**Comment by stephentoub** [comment]
Your `responseTask` there is typed as a `Task`, not `Task<Stream>`, so it's possible it could be both non-null and not a `Task<Stream>`.  I still don't understand what you're trying to validate, but regardless of what it is, you don't need access to the internal implementation detail types to do so.

> It is possible I am trying to verify something that has not seen task activation yet

What do you mean by this, and why is it important?

**Comment by mwpowellhtx** [comment]
@stephentoub See [post](https://github.com/dotnet/runtime/issues/81708#issuecomment-1419511832), I outlined the progression of the verification there.

**Comment by mwpowellhtx** [comment]
@stephentoub ...

>  I still don't understand what you're trying to validate...

I have an API context which may see a `Task<Stream>` or it may just be a `Task`, I do not know yet, in response to the `RequestMethod`. In this case the thing is a `Task<Stream>` but to the test scaffold, like I said, could simply be a `Task`, it does not know, but that needs to be verified and not assumed given contextual extensibility.

**Comment by stephentoub** [comment]
> but that needs to be verified

What _exactly_ needs to be verified and why?  You have a non-null `Task` that comes back.  What is it you then need to prove?  If `task is Task<Stream>` it is a `Task<Stream>` or something that derives from it.  If that's false, what is it you then need to prove?

**Comment by mwpowellhtx** [comment]
Like I said, the response could be either `Task<Stream>` or simply `Task`.

**Comment by stephentoub** [comment]
> Like I said, the response could be either Task<Stream> or simply Task.

And?  What is it you then need to prove?  Your original comments said "I want to verify the responseTask I have is at least a Task<Stream> as expected. In this case, also happens to be a ContinuationTaskFromResultTask<Stream>."  A `ContinuationTaskFromResultTask<Stream>` is both a `Task` and a `Task<Stream>`.  If your goal is to assert that the thing you have is a `Task<Stream>`, then assert that it `is Task<Stream>`.  If that fails, it's not a `Task<Stream>`.

**Comment by mwpowellhtx** [comment]
Oh so we're parsing words now...

One use case expects a `Task<Stream>`. That is all we would expect.

Another use case, completely different test class, might expect a `Task`. Would not be expected to be a Task<Stream> in that case.

And so on and so forth.

**Comment by stephentoub** [comment]
> Oh so we're parsing words now...

I was trying to understand what it was you were hoping for. That requires parsing words, yes. I'm not trying to be argumentative.

It's very common for implementations to return internal implementations/derivations of public abstractions. We're not going to make those internal implementations public just to be able to name them in asserts. I also would discourage folks from trying to pin down exactly what derivations are returned: implementations can and do change those over time, and doing so is considered to be non-breaking.

As there's nothing we're planning to act on here, I'm going to close it.

Thanks.
