### ISSUE TITLE
Provide custom marshaller for `USER_INFO_1`

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#81705]
In PR https://github.com/dotnet/runtime/pull/81480, the following P/Invoke was failing to compile when targeting .NET 8.

https://github.com/dotnet/runtime/blob/167112574ebfcfcddfc23267e1ba93eebdcdeaf1/src/libraries/Common/tests/TestUtilities/System/WindowsIdentityFixture.cs#L121-L122

The failure is because in the current dotnet/runtime official build this P/Invoke is only compiled to target .NET 6 and so the `LibraryImport` source generated degrades to a `DllImport`. We should provide a custom marshaller for the struct below

https://github.com/dotnet/runtime/blob/167112574ebfcfcddfc23267e1ba93eebdcdeaf1/src/libraries/Common/tests/TestUtilities/System/WindowsIdentityFixture.cs#L127-L138

This scenario could be made to "just work" with the following issue addressed: https://github.com/dotnet/runtime/issues/81656

**Comment by elinor-fung** [comment]
For anyone that might want to pick this up, here is an example of a struct with custom marshalling used in downlevel and current targets:
https://github.com/dotnet/runtime/blob/876a97d7d652b1c688e0b72e229bc38779609724/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/UnsafeNativeMethods.cs#L344-L348
