### ISSUE TITLE
BinaryData + JSON source gen produces compiler warnings

### ISSUE THREAD

**Issue by krwq** [dotnet/runtime#81702]
EDIT by @eiriktsarpalis to reflect more recent error modes

In https://github.com/dotnet/runtime/pull/73448 we've added internal converter for BinaryData but that's not working with JSON source-gen.

## Repro

```csharp
using System.Text.Json.Serialization;

[JsonSerializable(typeof(BinaryData))]
partial class MyContext : JsonSerializerContext { }
```

## Expected behavior:
Compiles and works when you serialize/deserialize

## Actual

```
warning SYSLIB1041: The 'JsonConverterAttribute' type 'System.BinaryDataConverter' specified on member 'System.BinaryData' is not a converter type or does not contain an accessible parameterless constructor.
```

## API Proposal

We should make the constructor of the already included custom converter public:

```diff
namespace System;

[JsonConverter(typeof(BinaryDataConverter))]
public partial class BinaryData { }

-internal sealed class BinaryDataConverter : JsonConverter<BinaryData> { }
+namespace System.Text.Json.Serialization;
+
+public sealed class BinaryDataConverter : JsonConverter<BinaryData> { }
```

**Comment by eiriktsarpalis** [comment]
In order to have the type supported in source gen the custom converter needs to be made public.

**Comment by layomia** [comment]
@eiriktsarpalis with https://github.com/dotnet/runtime/pull/87136 do we stop generating the converter logic?

**Comment by eiriktsarpalis** [comment]
That's right. It will no longer fail to compile but the custom converter won't be picked up.

**Comment by terrajobst** [comment]
* We should add Json somewhere in the name. It felt right to put before the converter.

```C#
namespace System.Text.Json.Serialization;

public sealed class BinaryDataJsonConverter : JsonConverter<BinaryData>
{
    // Overrides omitted
}
```
