### ISSUE TITLE
FileSystemWatcher Changed event fires only after right click on file.

### ISSUE THREAD

**Issue by xp-development** [dotnet/runtime#81717]
Hi, 

I try to watch a single file with the FileSystemWatcher. My current code:
```
_watcher = new FileSystemWatcher
  {
    Path = directoryName!,
    Filter = Path.GetFileName(_filePath)!,
    NotifyFilter = NotifyFilters.Attributes
                   | NotifyFilters.CreationTime
                   | NotifyFilters.FileName
                   | NotifyFilters.LastAccess
                   | NotifyFilters.LastWrite
                   | NotifyFilters.Security
                   | NotifyFilters.Size
  };
_watcher.Error += WatcherOnError;
_watcher.Changed += OnWatcherOnChanged;
_watcher.EnableRaisingEvents = true;
```

If I start my application the Changed event wasn't fired, but if I do a right click on the file in windows file explorer, the Changed event is fired. What is wrong? Why the event is not fired?

**Comment by danmoseley** [comment]
Sysinternals process monitor may show the difference in file system operations if any

**Comment by xp-development** [comment]
I trace the file and see that there is a Write File operation each second. XP.LogViewer.SampleLogging.exe writes every second a new log entry with log4net to the watched file. The FileSystemWatcher from XP.LogViewer.exe do not notify these changes until I do a right click in explorer. I think it's trigger by CreateFile or CloseFile operations from Explorer.exe. 

Why FileSystemWatcher Changed event is not raised for a Write operation?

![image](https://user-images.githubusercontent.com/9391891/217332510-b9322c80-2d18-4246-9a96-6e98aaf6a7f1.png)

**Comment by Jozkee** [comment]
@xp-development if you do the "logging" yourself with something like this:
```cs
```

**Comment by danmoseley** [comment]
I went to look at ReadDirectoryChangesW to see whether it describes certain kinds of file access that it doesn't reliably fire for, and I don't see mention of that. I did see

> ReadDirectoryChangesW fails with ERROR_NOTIFY_ENUM_DIR when the system was unable to record all the changes to the directory. In this case, you should compute the changes by enumerating the directory or subtree.

It looks like in the case of ERROR_NOTIFY_ENUM_DIR we call the Error delegate and quit (when we could in theory do what it says and continue). Probably not relevant, but is your WatcherOnError called?

**Comment by danmoseley** [comment]
cc @JeremyKuhne in case he knows of some kind of IO that ReadDirectoryChangesW won't reliably see.

**Comment by JeremyKuhne** [comment]
Without a full repro, there isn't enough information here to give an exact answer.

There could be more changes than the buffer could handle, for example (as @danmoseley points out). Additionally, not every file content change is going to get [reported](https://devblogs.microsoft.com/oldnewthing/20110812-00/?p=9913#:~:text=In%20other%20words%2C%20Read%C2%ADDirectory%C2%ADChangesW%20tells%20you%20when%20the,results%20from%20Read%C2%ADDirectory%C2%ADChangesW%20to%20update%20that%20collection%20incrementally.). I also don't know the exact heuristics for when the various file systems update the directory entries. I would presume there is some sort of [cadence](https://learn.microsoft.com/en-us/windows/win32/fileio/setting-and-getting-the-timestamp-of-a-file) for that, but I don't know for sure.

**Comment by danmoseley** [comment]
The link to the blog that Jeremy posted may be the clue. Do you see the timestamp changing on the file as log4net does its work? (use cmd.exe). 

>  if you write to a file via a memory-mapped view, that will not update the last-write time in the directory entry

another option is to use a [polling watcher](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.fileproviders.physicalfileprovider.usepollingfilewatcher?view=dotnet-plat-ext-7.0). if you're just concerned with this file, you could even do it yourself with a thread that checks every second or so.

**Comment by PeterHanson33** [comment]
I had a similar issue. I think it is a problem how log4net handle the file. I add a very simple sample application to reproduce.

https://github.com/PeterHanson33/FileWatchSample

**Comment by xp-development** [comment]
Sorry for my late response. I was ill. @PeterHanson33 has deployed a small app that described the problem very well.
@danmoseley I am using a polling watcher and it works fine.

Thanks to everybody for the great help!
