### ISSUE TITLE
Crash when deserializing certain types in Blazor Web Assembly projects when project is published

### ISSUE THREAD

**Issue by hypdeb** [dotnet/runtime#81746]
### Description

I have a type which implements some numerical operation interfaces. I'm obtaining a serialized version of this type in my Blazor Web Assembly front end, which I'm deserializing. This deserialization fails because of some missing method:
```
Error: System.TypeLoadException: Parent class vtable failed to initialize, due to: Could not load list of method overrides due to Method not found: !2 System.Numerics.IAdditionOperators`3.op_Addition(!0,!1) assembly:Repro.Wasm.dll type:AbstractType member:(null)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<<Main>$>d__0](:5432/<<Main>$>d__0& )
   at Program.<Main>$(:5432/String[] args)
    at qi (dotnet.7.0.2.2sr8yltp5e.js:5:80156)
    at Ji (dotnet.7.0.2.2sr8yltp5e.js:5:80040)
    at _Repro_Wasm__entrypoint (_Repro_Wasm__entrypoint:27:5)
    at dotnet.7.0.2.2sr8yltp5e.js:5:69011
    at Object.ji [as call_assembly_entry_point] (dotnet.7.0.2.2sr8yltp5e.js:5:69166)
    at Object.callEntryPoint (blazor.webassembly.js:1:46050)
    at Vt (blazor.webassembly.js:1:62248)
```

### Reproduction Steps

- Clone https://github.com/hypdeb/repros
- Navigate to `deserialize-with-abstract-static-methods` (ignore the name, it was based on my original assumptions for the cause of the issue)
- Run `docker build . -t repro-wasm`
- Run `docker run -p 5432:80 repro-wasm`
- Open your browser to `localhost:5432`
- Open dev tools and notice the exception above in the console

### Expected behavior

The exception obtained through the repro above does not occur.

### Actual behavior

The exception does occur.

### Other information

I've looked into the `_framework` folder of the published version of the app, and the `System.Numerics` dll is missing. It is present in the output of a simple build, which I think explains why it works if you simply run the app using `dotnet run`.

**Comment by marek-safar** [comment]
This sounds like trimming issue

/cc @vitek-karas

**Comment by hypdeb** [comment]
Indeed: I tried with `PublishTrimmed` false just now and it seems to work in the small reproduction repository I produced and it seems to be fixing the issue. Sadly it doesn't seem to work in my real application.

**Comment by vitek-karas** [comment]
@jtschuster could you please take a look - this is very likely in the same area as you worked before. Static interface method trimming.

**Comment by jtschuster** [comment]
It seems like the `IAdditionOperators.op_Addition` is expected to be removed because it's unused, and usually all overrides of a removed static abstract method would have their `.overrides` metadata stripped in `SweepStep.SweepOverrides()`. But because the definition of the overriding method is in a 'copy' assembly, it doesn't get swept and we have an entry in `.overrides` that points to a removed method. I'm working on a PR to mark the methods pointed to in the `.overrides` of marked methods in Copy and CopyUsed assemblies, then the trimmer will keep the `IAdditionOperators.op_Addition`.

**Comment by hypdeb** [comment]
@jtschuster I'm not too familiar with the versioning process. Will this be part of .NET 8 only or will it also make it to future versions of .NET 7 ?

**Comment by agocke** [comment]
I think we should backport this to .NET 7, so you will see this in a patch to 7.0 (ship time TBD)

**Comment by hypdeb** [comment]
Great news ! Thanks a lot !

**Comment by marek-safar** [comment]
@jtschuster please backport this change to linker repo
