### ISSUE TITLE
HttpClientFactoryServiceCollectionExtensions multiple implementations

### ISSUE THREAD

**Issue by DavidVollmers** [dotnet/runtime#81749]
I stumbled upon a really weird behavior when it comes to using the `HttpClientFactoryServiceCollectionExtensions` extension methods. 

I have an ASP.NET Core .NET 6.0 Web API project and a class library which is also .NET 6.0. Both host code which uses the `HttpClientFactoryServiceCollectionExtensions.AddHttpClient` extension method for the `IServiceCollection` interface.

While debugging I stumble upon two different implementations which are used in these projects. The ASP.NET Core project is using an implementation which internally calls `AddTypedClientCore` and the class library uses an implementation which internally calls `AddTypedClient`. This would not bother me if not for unit testsing where I mock the `IServiceCollection` interface. In one project testing works fine in the other it fails because the internal class `HttpClientMappingRegistry` is missing.

I would like to know what kind of black magic is done here and how I can cope with it.

**Comment by CarnaViire** [comment]
@DavidVollmers can you share a small runnable repro for that, please?

Did I understand you correctly, that when you add `Microsoft.Extensions.Http` NuGet package to your .NET 6 class library and use `AddHttpClient`, everything works as expected, but when you try to do the same `AddHttpClient` for ASP.NET Core 6.0 project, it fails?

Also, just curious, why would you need to mock `IServiceCollection`?

**Comment by DavidVollmers** [comment]
I am mocking the `IServiceCollection` so that I can make sure there is an implementation provided for each used interface when building the `IServiceProvider` in my application. So I don't get any null references or other exceptions when injection happens.

I will build an example Repository later this day and will inform you.

**Comment by DavidVollmers** [comment]
So I created an example setup which reproduces the described behaviour:
https://github.com/DavidVollmers/HttpClientFactoryServiceCollectionExtensions

While building this I also found the culprit: `Microsoft.AspNetCore.Http`
I believe it is an artifact in the project coming from older ASP.NET Core versions. I could savely remove the dependency without breaking anything so this problem is solved for me.

Still really weird that adding the package reference alters the internal implementation of something like `AddHttpClient`.

**Comment by DavidVollmers** [comment]
So I got confused by my own try to explain this. Further digging into this I now know that the issue is the difference between `Microsoft.Extensions.Http` versions. The version 6.0 uses `AddTypeClientCore` internally.

This doesn't change anything for this specific issue. But it also means it is impossible to test around `AddHttpClient` using a mock of `IServiceCollection` since the internal class `HttpClientMappingRegistry` is required in the `IServiceCollection` implementation.

In my opinion it is a bad design pattern to inject internal implementations into the service collection but this has nothing to do with the original issue described here.
