### ISSUE TITLE
OpenSslDirectoryBasedStoreProvider loads only *.pfx files

### ISSUE THREAD

**Issue by AlexPykavy** [dotnet/runtime#81759]
We're going to use directory based store to keep both private and public certificates (used for mutual TLS). But currently OpenSslDirectoryBasedStoreProvider [loads only files with .pfx extension](https://github.com/dotnet/runtime/blame/983c8f239a98812498d874ed36b7001bd764fdfe/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/OpenSslDirectoryBasedStoreProvider.cs#L21).

As an experiment, I've added a PEM certificate to the store directory `~/.dotnet/corefx/cryptography/x509stores/my` and changed it extension to `.pfx` and `OpenSslDirectoryBasedStoreProvider` successfully loaded it.

Does `OpenSslDirectoryBasedStoreProvider` support only `PFX` certificates and loading other things is just a backdoor?

**Comment by bartonjs** [comment]
Editing these directories manually is not supported.

Using the X509Store.Add method you can add certificates without associated private keys (or with).  The use of PFX is an implementation detail.
