### ISSUE TITLE
perf pipeline completely broken - ClientAuthenticationError while uploading results

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#81763]
[Broken build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2106697&view=results):

`<class 'azure.core.exceptions.ClientAuthenticationError'>: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.`
`AuthenticationErrorDetail:Signature did not match.`

Rest of the message can be seen in the logs.

cc @DrewScoggins @LoopedBard3

@steveisok even the mobile ones seem to be broken with this

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by cincuranet** [comment]
Fixed by https://github.com/dotnet/performance/issues/2886.
