### ISSUE TITLE
Segmentation fault when .NET starts JIT compilation of previous recorded methods triggered by `ProfileOptimization.StartProfile`

### ISSUE THREAD

**Issue by daxian-dbw** [dotnet/runtime#81799]
### Description

We PowerShell team got 2 reports about `Segmentation fault` when starting PowerShell by `pwsh -command` or `pwsh -file` on Redhat 7.9 and macOS M1 machine.

- https://github.com/PowerShell/PowerShell/issues/18958
- https://github.com/PowerShell/PowerShell/issues/18998

The stack trace for the report on macOS M1 machine is attached below.
The stack trace suggests the crash happened when .NET starts JIT compilation of the previous recorded methods, which is triggered by the [ProfileOptimization.StartProfile](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.profileoptimization.startprofile?view=net-7.0) call in PowerShell.

We asked the user to delete the profile data file and try launch `pwsh -c` or `pwsh -file` again, and the user reported back that it began to work after removing the profile data file: https://github.com/PowerShell/PowerShell/issues/18958#issuecomment-1416367110. So, it's confirmed that this is an issue with the .NET profile optimization.

![image](https://user-images.githubusercontent.com/103770981/213844837-3b1dfca9-3b65-49d3-9769-f9cd72fc2202.png)

### Reproduction Steps

The issue doesn't happen consistently. Even for the users who reported the issue, it was not consistent. They started with using PowerShell 7.3.1, which worked for a few days and then started to fail. Then they switched to PowerShell 7.3.0, which worked for a few days and started to fail again.

PowerShell 7.3.1 and PowerShell 7.3.0 are both on top of .NET 7.0.0

### Expected behavior

No segmentation fault.

### Actual behavior

Segmentation fault was reported.

### Regression?

It's a regression, given that we don't have the problem in PowerShell 7.2.x versions, which are on top of .NET 6.

### Known Workarounds

Deleting the profile data file, then `pwsh -c` and `pwsh -file` will start to work again.

### Configuration

> Which version of .NET is the code running on?
.NET 7.0.0

> What OS and version, and what distro if applicable?
Redhat 7.9 and macOS M1 machine

> What is the architecture (x64, x86, ARM, ARM64)?
For Redhat 7.9: Linux 3.10.0-1160.81.1.el7.x86_64
For macOS: ARM64

**Comment by daxian-dbw** [comment]
Any updates? We got another report of the issue in PowerShell repo, and this time it's on Ubuntu 22.04
> The error occurs once a day only on a specific machine user, who executes a lot of pwsh scripts. After a reboot powershell is working fine for approx. 24 hours. Then the issue occus again.

**Comment by AndyAyersMS** [comment]
@mangod9 seems like a runtime issue?

**Comment by mangod9** [comment]
@davidwrighton @kouvel. Does Powershell use multicore JIT functionality? @daxian-dbw, is there a dump available to look at?

**Comment by daxian-dbw** [comment]
> Does Powershell use multicore JIT functionality?

Yes, PowerShell calls `ProfileOptimization.SetProfileRoot/StartProfile` at the entry point.
We don't have a dump available. If you can provide steps to collect a dump in this particular case, I think @bobrozelle may be able to help with that when the issue happens again in their environment.

**Comment by kouvel** [comment]
The repro appears to be simple enough, if we have the right profile data file to cause the seg fault. When the seg fault is seen, and is reproducible with a simple pwsh command, could you please collect the profile data file and share it? I figure it may be reproducible elsewhere too with the same profile data file.

**Comment by AdminValida** [comment]
@mangod9 

As this is a production system our focus is to not have any segfaults :-)

But i ll try to reproduce the issue on the coming weekend. Maybe i can get both, a core dump and a "corrupted" profile file.

I'll keep you up to date

Regards

**Comment by mangod9** [comment]
yeah sounds good.

**Comment by AdminValida** [comment]
@mangod9 

I just reverted the permissions like described above and cache files are written now. I already got the first segfault but don't know where the dumps are, can you help me out here? I am on Ubuntu 22

Regards

**Comment by AdminValida** [comment]
I wasn't able to fully crash pwsh but some segfaults popped up:

` kernel: [187481.441049] pwsh[1565713]: segfault at 28 ip 00007f76eff09c30 sp 00007f76e8ffe8e0 error 4 in libcoreclr.so[7f76efdd7000+383000]`

Maybe i am able to test this again next weekend.

Regards

**Comment by Dmbob** [comment]
I was not able to acquire a crash or coredump, however, we have recently seen this issue occurring on a Redhat server running pwsh version 7.2.7. Removing the write permissions to the cache directory and deleting the cache files resolved the issue.

So this is also seems to be an issue for Powershell 7.2.x

**Comment by nitroed01** [comment]
Ran into this issue on AlmaLinux release 8.6, running Powershell 7.2.6. I upgraded to 7.3.6 and the issue went away for about a month, now the problem is back. This is also on a server running Nagios so pwsh is being called 100+ times per minute. I do have a copy of the corrupt StartupProfileData-NonInteractive file as I simply renamed it go get things working, if that would be of help.

**Comment by nitroed01** [comment]
Just emailed that profile data file. It does not seem to matter what is run, I'm running .ps1 files directly from bash that have a #!/usr/bin/pwsh in the first line. But even running a simple command fails: 
`pwsh -command Write-Output "ok"
Segmentation fault (core dumped)`

**Comment by kouvel** [comment]
Thanks for the data @nitroed01, I'm able to reproduce the issue. Not clear yet where the problems are, I'll investigate.

**Comment by rickbrew** [comment]
I believe I'm seeing this with Paint.NET.

Steps to repro:
1) Download and install Paint.NET v5.0.11, or use the portable version. Both available here: https://github.com/paintdotnet/release/releases/tag/v5.0.11 . That version of Paint.NET is using .NET 7.0.12

2) Place the two files in this ZIP into `%LOCALAPPDATA%\paint.net\Optimization`: 
[Startup.profiles.bad.zip](https://github.com/dotnet/runtime/files/13465430/Startup.profiles.bad.zip)
<img width="733" alt="image" src="https://github.com/dotnet/runtime/assets/10873410/d10a662e-56a6-48e0-a7ca-f30a781ad01e">


3) Try to start Paint.NET, either by double-clicking its icon or running `paintdotnet.exe` at the command-line

Expected: It works

Actual: App does not start, and you see errors in the event viewer like so:
![image](https://github.com/dotnet/runtime/assets/10873410/25ba5643-3381-4a89-88ee-e54c7a330ea4)

If this isn't the same issue then I can file a new issue for it, but this is causing misery for a non-trivial number of people who use my app 😢 In the short-term I can just disable the use of `ProfileOptimization` and release a hotfix for the app

**Comment by rickbrew** [comment]
This appears to be fixed? Should the issue be closed?

**Comment by mangod9** [comment]
yeah this could be closed I think @kg / @steveisok ?
