### ISSUE TITLE
Ignoring SSL certificate errors by using HttpClient does not work on linux-based systems (net6).

### ISSUE THREAD

**Issue by Evhen010693** [dotnet/runtime#81794]
### Description

Ignoring SSL certificate errors by using HttpClient does not work on linux-based systems (net6).

There is some need to ignore SSL certificate issues during http call. An usual approach with callback **ServerCertificateCustomValidationCallback** works only for windows system. The callback handler is not fired when trying to catch ssl errors within linux-based system like debian or ubunty. The code snippet below was used:

```c#
var handler = new HttpClientHandler
{
	ServerCertificateCustomValidationCallback = (request, cert, chain, errors) =>
	{
		Console.WriteLine("SSL error skipped");
		return true;
	}
};

HttpClient client = new HttpClient(handler);
using HttpResponseMessage response = await client.GetAsync("https://any_server_with_invalid_certificate");

```

### Configuration
.NET 6.0

Debian “bullseye”
Ubuntu 20.04.5 LTS (Focal]

**Comment by wfurt** [comment]
Could you share complete repro with particular site @Evhen010693 ? What you describing is unlikely generic problem as there are tests to cover such scenarios. (we use badssl.org for testing)

**Comment by Evhen010693** [comment]
> Could you share complete repro with particular site @Evhen010693 ? What you describing is unlikely generic problem as there are tests to cover such scenarios. (we use badssl.org for testing)

@wfurt you are right that it's unlikely generic problem, but some part is still unclear...

SSL issue is successfully ignored (as expected) once I try to use some bad ssl servers (like https://expired.badssl.com or https://self-signed.badssl.com) on **windows** and linux image like **aspnet:6.0-alpine**. At the same time it does not work on linux base image for my local exchange server (https://exchange.sandbox.local/ews/exchange.asmx)  that also has ssl issue:
![image](https://user-images.githubusercontent.com/29655797/217578803-cdcd1dbe-894c-4733-94c4-73199b70e211.png)

Sample project you can find here https://github.com/Evhen010693/SampleSSLApp

GREEN case (windows)

1. Run ConsoleApp1.exe in bin/Debug/net6.0 or run it via kestrel in VS
2. Actual result
![image](https://user-images.githubusercontent.com/29655797/217581219-947689d5-e174-4d88-8572-161768bd6376.png)
SSL issue was skipped - it's OK

RED case (aspnet:6.0-alpine)

1. Build docker image: docker build -t samplesslapp .
2. Run docker image: docker run samplesslapp
3. Actual result
![image](https://user-images.githubusercontent.com/29655797/217582257-bc0ed69b-d5cd-4963-897c-f42a56f3161b.png)
SSL issue was NOT skipped - it's NOT OK

So as you can see issue is reproducing only for specific server (with invalid ssl) and within linux-based container like alpine.

**Comment by wfurt** [comment]
Well, if there is validation error, you would see exception about the handshake, right @Evhen010693? The fact that you see nothing suggest that there is some issue with composing your docker. It may be worth of starting the docker with shell and building and running the app there. You can also run `tcpdump` or `Wireshark` to see  if there is any TLS handshake at all.

**Comment by Evhen010693** [comment]
> Well, if there is validation error, you would see exception about the handshake, right @Evhen010693? The fact that you see nothing suggest that there is some issue with composing your docker. It may be worth of starting the docker with shell and building and running the app there. You can also run `tcpdump` or `Wireshark` to see if there is any TLS handshake at all.

@wfurt right, there is no any exception within alpine container by some reason. When I tried to change image to mcr.microsoft.com/dotnet/aspnet:6.0 got the next exception 
`The SSL connection could not be established, see inner exception. Unable to read data from the transport connection: Connection reset by peer.`
![image](https://user-images.githubusercontent.com/29655797/217758681-4794f54a-f3f1-4788-bd3f-7bbd84334b87.png)

Anyway my target base image should be alpine. Will try to find out firstly why execution is blank (no ssl error skipping and no exceptions there). Thanks for advice and will get back to you.

**Comment by ManickaP** [comment]
Hi @Evhen010693, I'll close this issue for now as there's nothing actionable for us at the moment. Once you figure your problem out and it turns out that there really is an issue with .NET runtime, feel free to re-open or file another issue.
Thanks.
