### ISSUE TITLE
[Analyzer] BitConverter.ToString(bytes).Replace("-", "") to Convert.ToHexString

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#81796]
It seems that `BitConverter.ToString(bytes).Replace("-", "")` is a fairly popular pattern to convert a byte array into a hex string without dashes: [grep.app](https://grep.app/search?q=BitConverter.ToString%5C%28.%2B%5C%29.Replace%5C%28%22-%22%2C&regexp=true&filter[lang][0]=C%23) 

There were multiple issues/API proposals (with a lot of upvotes) around adding a special mode to avoid emitting those dashes (that's how `Convert.ToHexString` was born):

- https://github.com/dotnet/runtime/issues/14014
- https://github.com/dotnet/runtime/issues/24220
- https://github.com/dotnet/runtime/issues/17837

The analyzer is expected to replace
```csharp
string data = BitConverter.ToString(data).Replace("-", "");
```
with
```csharp
string data = Convert.ToHexString(data); // no unnecessary allocs, vectorized
```

**Comment by lewing** [comment]
ToLower seems pretty common too

**Comment by EgorBo** [comment]
![image](https://user-images.githubusercontent.com/523221/217393437-fdb4ecca-f890-4dbb-b2e1-0ae5c7f7e89f.png)

😕

**Comment by benaadams** [comment]
> ToLower seems pretty common too

Code for ToLower without dashes is in the runtime; just isn't an api exposed for it 😢

**Comment by bartonjs** [comment]
The analyzer seems like goodness.

Category: Performance
Severity: Info

**Comment by mpidash** [comment]
@EgorBo Is this analyzer up for grabs? If so, I would love to work on it 😄.

**Comment by EgorBo** [comment]
> @EgorBo Is this analyzer up for grabs? If so, I would love to work on it 😄.

Yes! Please feel free
