### ISSUE TITLE
There're two 'EnumCalendarInfoCallback' in System.Private.CoreLib that mono-llvm-PInvoke dont support ..

### ISSUE THREAD

**Issue by ifeuille** [dotnet/runtime#81813]
### Description

The two EnumCalendarInfoCallback
which cause the error:
```
error : Two callbacks with the same name 'EnumCalendarInfoCallback' are not supported.
```

### Reproduction Steps

Just see the code of PInvokeTableGenerator.cs
````
EmitNativeToInterp
    if (callbackNames.Contains (entry_name))
    {
        Error($"Two callbacks with the same name '{method_name}' are not supported.");
    }
````

### Expected behavior

No Error. Maybe need support multiple entries with same name?

### Actual behavior

The two 
- 1.
```[UnmanagedCallersOnly]
private unsafe static void EnumCalendarInfoCallback(char* calendarStringPtr, IntPtr context)
```
- 2.
```
[UnmanagedCallersOnly]
private unsafe static Interop.BOOL EnumCalendarInfoCallback(char* lpCalendarInfoString, uint calendar, IntPtr pReserved, void* lParam)
```
But PInvokeTableGenerator use '{module_symbol}_{class_name}_{method_name}' as key which cause the error:
```
error : Two callbacks with the same name 'EnumCalendarInfoCallback' are not supported.
```

### Known Workarounds

just test 

### Configuration

win10,x64

**Comment by ifeuille** [comment]
area: mono-llvm-aot

**Comment by SamMonoRT** [comment]
@matouskozak @radical - please add an update here regarding the investigations. It'll help determine priority of the fix.

**Comment by radical** [comment]
@matouskozak has been working on this.

**Comment by SamMonoRT** [comment]
Moving this to 9.0, will consider backporting a fix.

**Comment by matouskozak** [comment]
I'm struggling to reproduce this issue locally. @ifeuille Do you have a piece of reproducible code that triggers this error that you could share?

**Comment by radical** [comment]
@maraf did this get fixed with your task unification work?

**Comment by maraf** [comment]
> @maraf did this get fixed with your task unification work?

I don't think we did anything to support multiple callbacks. The code that does the check is still in place https://github.com/dotnet/runtime/blob/a39262bd2d8543e5e6636978d54a084669e1a8e5/src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs#L313-L317

Mentioned `EnumCalendarInfoCallback` callbacks come from `CalendarData.Icu.cs` (which is actually used on unix/wasm) and `CalendarData.Nls.cs` which is used only on Windows

**Comment by SamMonoRT** [comment]
Closing issue. Please re-open with minimal repro step with latest .NET8 RC1 builds.
