### ISSUE TITLE
Blazor wasm DateOnly.DayOfWeek not localized

### ISSUE THREAD

**Issue by TDroogers** [dotnet/runtime#81820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Configure localization in Blazor and set the language to Dutch (nl-NL)

Add the following code to a page `DateOnly.DayOfWeek`

The output will be in English `Tuesday`

Now use `DateOnly.ToString("dddd")`

The output will be in Dutch `Dinsdag`

### Expected Behavior

`DateOnly.DayOfWeek` and `DateOnly.ToString("dddd")` should have the same output, both in the localized language.

### Steps To Reproduce

See: Describe the bug

### .NET Version

7.0.102

**Comment by ilonatommy** [comment]
The behavior seems consistent across applications and does not apply to WASM only.
Console Application: 
![image](https://user-images.githubusercontent.com/32700855/217526930-e4031b0b-dcea-4721-9e55-25d4d857c1a5.png)

Blazor Server:
![image](https://user-images.githubusercontent.com/32700855/217527201-fe3c7174-15dd-4d24-afcb-b910b17765a5.png)

Blazor WASM:
![image](https://user-images.githubusercontent.com/32700855/217527595-1cdfb128-69ad-4b44-8ce9-d8f39a7af328.png)


WASM Browser:
![image](https://user-images.githubusercontent.com/32700855/217527932-e1c6c744-486c-45bd-8583-e50712957a61.png)

**Comment by ilonatommy** [comment]
@tarekgh, does it look like a bug to you?

**Comment by Clockwork-Muse** [comment]
> The members of the [DayOfWeek](https://learn.microsoft.com/en-us/dotnet/api/system.dayofweek?view=net-7.0) enumeration are not localized. To return the localized name of the day of the week, call the [DateTime.ToString(String)](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.tostring?view=net-7.0#system-datetime-tostring(system-string)) or the [DateTime.ToString(String, IFormatProvider)](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.tostring?view=net-7.0#system-datetime-tostring(system-string-system-iformatprovider)) method with either the "ddd" or "dddd" format strings. The former format string produces the abbreviated weekday name; the latter produces the full weekday name.

As designed.
