### ISSUE TITLE
JsonConverter<decimal> rounds number, even after overriding Write(...) method in custom converter

### ISSUE THREAD

**Issue by janrhansen** [dotnet/runtime#81825]
In our API we're exposing decimal values using the Swagger-toolchain. We're mapping decimals as

`options.MapType<decimal>(() => new OpenApiSchema { Type = "number", Format = "decimal" });`

hence the swagger.json exposes a `decimal?` value as

```
"amount": {
    "type": "number",
    "format": "decimal",
    "nullable": true
}
```

Using the default .net 6 System.Text.Json serialization of a decimal in our output-DTO object works for decimals with up to 17 digits (precision). 
Hence, a working example where the underlying SQL server column is Decimal(25,10): 
the value 1234567.0123456789 is output as 
`"amount" : 1234567.0123456789` 
Notice all 10 decimals are present.

Increasing the number of digits before the decimal separator, will make the output a rounded result. So, inserting 12345678.0123456789 (one extra '8' digit before the decimal separator) will output as 
`"amount": 12345678.01234568`
Notice the last part of the number is now rounded to 8 decimals, and 16 digits in total, whereas one might expect only one decimal less, as only one extra digit was introduced.

Also, utilizing the maximum number of digits available in this particular scenario, and setting the data to 111222333444555.0123456789 will yield the result 
`"amount": 111222333444555.02`
Notice that again the output reduced, this time to 17 digits.

Assuming that the default implementation of JsonConverter<decimal> was just restricted in some way, I went with a custom converter:

```
public class CustomDecimalConverter : JsonConverter<decimal>
{
    public override decimal Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        return reader.GetDecimal();
    }

    public override void Write(Utf8JsonWriter writer, decimal value, JsonSerializerOptions options)
    {
        writer.WriteRawValue(value.ToString(CultureInfo.CreateSpecificCulture("en-US"))); // yields "amount": 111222333444555.02,
    }
}

```
and decorated the property in the DTO class to use this converter:

```
    [JsonPropertyName("amount"), JsonConverter(typeof(CustomDecimalConverter))]
    public decimal? AmountIssued { get; set; }

```

Since I'm now providing the writer a string, which I **know** contains the correct value, with all digits, I expected the correct output:
`"amount": 111222333444555.0123456789`
but what I get is still
`"amount": 111222333444555.02`

so even calling `WriteRawValue(...)` does not bypass an internal process that seem to convert the string to a decimal and then output a rounded value.

If the default .net json serialization of a decimal is unable to actually serialize a .net decimal, and a custom conversion can't override the functionality, then how are one supposed to output a decimal with more than 17 digits as json? 

I would consider this a bug, but maybe I just don't understand what is actually going on here. So, is it a bug, or a known limitation of the functionality in the System.Text.Json namespace, possibly with a known workaround as well? 

I would rather not end up having to return the decimal values as strings:
"amount": "111222333444555.0123456789"
as I find this to be "incorrect" since numbers in json are usually represented without the quotation marks.

**Comment by layomia** [comment]
The underlying formatting for decimal with the serializer [is done by `Utf8Formatter`](https://github.com/dotnet/runtime/blob/38ca26b27b9e7a867e6ff69eec3cabbfb4e9e1cf/src/libraries/System.Text.Json/src/System/Text/Json/Writer/Utf8JsonWriter.WriteValues.Decimal.cs#L58). I believe this behavior is by-design but I'll transfer the issue to the right area to be sure. cc @tannergooding 

>  writer.WriteRawValue(value.ToString(CultureInfo.CreateSpecificCulture("en-US"))); // yields "amount": 111222333444555.02,

`WriteRawValue` writes the input passed to it as-is, so your issue here is still with lower leve APIs (`ToString()` in this case).

**Comment by tannergooding** [comment]
@layomia, this isn't an issue with the Utf8Formatter but rather something with System.Text.Json.

A repro showing that `Utf8Formatter` roundtrips values is here: https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmABgFgAoUgRmqLIAIjaA6AIRwDNuYoAzmwAqMBBgDc1avgEBDPtQDe1Jmpa0AnAApaekgYDMxlKYCsFtmVolDKM0gDsADk0BbAJRSqq9cACeGDAA2gC6TBA4GAAOUUwAvEx4MADuTAFBwSQWod6+agAmMGAAlm5yADZMBQlMejZGJuaW1rb2Tq5u3upMAKoY3M4AYtDlGEFQIlD+I1Bj2gVoEVGxGEuRGEwleJsZMAIA6lAl4zB4XtJUPdwlCDA12nsAVEzRG6u171Ee+UwqVz11KwdMk0qwyNptAJnh43itvhcAWoAL7UZFAA==

Rather, I'd expect that something else in the chain is treating this as a `double` somewhere, which is causing a loss of precision.

**Comment by tannergooding** [comment]
It's worth noting that Javascript's `number` type is explicitly:
> primitive value corresponding to a double-precision 64-bit binary format IEEE 754 value

Depending on the exact libraries/scenarios its used with, you may get extra precision and you may get truncation to `double` instead.

This is in contrast to JSON which simply defines a `number` format and not necessarily what the backing format is. Some languages try to be inline with Javascript and others (like .NET) may themselves allow an "extended precision".

**Comment by eiriktsarpalis** [comment]
I suspect something else might be going on, `WriteRawValue` will output the exact characters provided by the user (with some optional validation). I also can't reproduce your issue using a simple console app, either using the built-in converter or the custom converter that you shared:

```C#
decimal value = 111222333444555.0123456789M;
var poco = new MyPoco 
{ 
    AmountIssuedCustomConverter = value,
    AmountIssuedDefaultConverter = value,
};

Console.WriteLine(JsonSerializer.Serialize(value)); // 111222333444555.0123456789
Console.WriteLine(JsonSerializer.Serialize(poco)); // {"amount":111222333444555.0123456789,"AmountIssuedDefaultConverter":111222333444555.0123456789}

public class MyPoco 
{
    [JsonPropertyName("amount"), JsonConverter(typeof(CustomDecimalConverter))]
    public decimal? AmountIssuedCustomConverter { get; set; }
    public decimal? AmountIssuedDefaultConverter { get; set; }
}

public class CustomDecimalConverter : JsonConverter<decimal> 
{
    public override decimal Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) 
    {
        return reader.GetDecimal();
    }

    public override void Write(Utf8JsonWriter writer, decimal value, JsonSerializerOptions options) 
    {
        writer.WriteRawValue(value.ToString(CultureInfo.CreateSpecificCulture("en-US"))); // yields "amount": 111222333444555.02,
    }
}
```

Would it be possible to share a standalone reproduction of the problem?
