### ISSUE TITLE
[API Proposal]: Add span based apis for Array.CreateInstance/GetValue/SetValue

### ISSUE THREAD

**Issue by afxres** [dotnet/runtime#81826]
### Background and motivation

Avoid extra memory allocate during reflections/serialization

### API Proposal

```diff
Array.CreateInstance(Type, int[])
Array.CreateInstance(Type, int[], int[])
Array.GetValue(int[])
Array.SetValue(object, int[])
+ Array.CreateInstance(Type, Span<int>)
+ Array.CreateInstance(Type, Span<int>, Span<int>)
+ Array.GetValue(Span<int>)
+ Array.SetValue(object, Span<int>)
...
```

### API Usage

```csharp
var lengths = (stackalloc int[] { 1, 2 });
var lowerBounds = (stackalloc int[] { 3, 4 });
var array = Array.CreateInstance(typeof(int), lengths, lowerBounds);
// we can use 'MemoryMarshal.GetArrayDataReference' instead of 'GetValue/SetValue'
// but 'CreateInstance' still have to allocate extra memories
var reference = Unsafe.As<byte, int>(ref MemoryMarshal.GetArrayDataReference(array));
```

**Comment by tannergooding** [comment]
CC. @jkotas, @BruceForstall 

This seems like general goodness and helps make certain type of multi-dimensional array handling "better".

However, `Array` is special so I wanted to confirm that there aren't any concerns or considerations that might block such functionality from being exposed.

I imagine if it is, we may want `CreateInstance<T>(...)` to match the other Array proposal that Jan has open.

**Comment by jkotas** [comment]
> This seems like general goodness and helps make certain type of multi-dimensional array handling "better".

It makes it better, but it is not going to be by much. These APIs are still going to be slow APIs that do a lot of work even after this change.

> we may want CreateInstance<T>(...) to match the other Array proposal that Jan has open.

Do you mean https://github.com/dotnet/runtime/issues/76478? There is no `CreateInstance<T>` in that proposal. If you know `T`, you can just use `new T[...]`.

**Comment by tannergooding** [comment]
Yes, that's the one I was thinking of.

**Comment by tannergooding** [comment]
Going to close this based on the feedback above. We already have overloads that avoid allocating for the common cases of 1/2/3 lengths. For more lengths we may end up adding `params Span<T>` support as part of a more holistic effort when the language feature becomes available.
