### ISSUE TITLE
[API Proposal]: Initialization constructor for collections

### ISSUE THREAD

**Issue by NinjaCross** [dotnet/runtime#81834]
### Background and motivation

I hope this is not a duplicate (I searched, but I didn't find anything about the following), and in that case, mea culpa.

In my understanding, calling 
```cs
var list = new System.Collections.Generic.List<string>() { "First" };
```
is always equivalent to 
```cs
var list = new List<string>();
list.Add("First");
```

I often find myself (and AFAIK it's not very rare, I've seen it many, many times everywhere) to **create and return** or **create and pass as a parameter** a collection with just one element, or at least a "first" element, already known at the time of the creation of the collection, like this:

```cs
// ...do something...
return new System.Collections.Generic.List<string>() { "First" };
```
or this

```cs
// ...do something...
var list = new System.Collections.Generic.List<string>() { "First" };
InvokeMethod1(list);
```

Unless I'm mistaken, having the possibility to specify the "first" element of the list directly into the constructor would lead to a little performance improvement.

```cs
var list = new List<string>("First");
```

Of course in some scenarios this could lead to collisions in the parameters of existing constructors, so it could be added only to non-empty constructors of the existing collections.

### API Proposal

Add a constructor to collections so that adding a "first" element would be possibile in the same instruction that creates the list.
Of course, the proposal doesn't apply just to `List<T>`, but also to all other collections where this could be applied without introducing breaking changes or undesired side-effects

### API Usage

```cs
var list = new List<string>("First");
```

### Risks

In some scenarios, the new constructor would collide with the existing ones (i.e.  `List<int>`), so in many cases it could be added only to non-empty constructors of the existing collections as a last parameter.

**Comment by NinjaCross** [comment]
Sorry all for the multiple updates in the content of the proposal: I mistakenly pressed CTRL+Enter and the issues has been created before the description was completed.

**Comment by stephentoub** [comment]
I don't think this is common enough with enough of a performance benefit to warrant adding such a constructor.  Such a constructor would also be ambiguous, e.g. is `new List<int>(42)` creating a list with a capacity == 42 or is it adding the element 42 to the list.

It's possible we'll separately do something to optimize collection creation from a known set of elements in support of https://github.com/dotnet/csharplang/issues/5354, but that effort is being driven for now primarily in csharplang.

**Comment by NinjaCross** [comment]
> I don't think this is common enough with enough of a performance benefit to warrant adding such a constructor.

I agree it's not very common, but the proposal aims to "do better" in even uncommon scenarios.
We would have one less function call, and in (very) hot paths, that could count.
(Indeed in hot paths there are other considerations to do, I'm just reasoning from the "best performance" point of view).

> Such a constructor would also be ambiguous, e.g. is new `List<int>(42)` creating a list with a capacity == 42 or is it adding the element 42 to the list.

You are right, that's what I imagined too.
Infact in my proposal I suggested to add this as a new constructor having the new parameter (most probably) in the _last place_ (i.e. after the `capacity`, in the scenario of a `List<T>`).
The following would be a reasonable scenario, that IMHO would not cause collisions:

```csharp
// we know that the capacity will be at least 1, and given the described scenarios, it would most probably stay 1 forever
var intList = new List<int>(capacity: 1, value: 42); 
var stringList = new List<string>(capacity: 1, value: "First");
```

...or in short...

```csharp
// we know that the capacity will be at least 1, and for the described scenarios,
// it would most probably stay 1 forever.
// Anyway it's a good way to incentivize the use of "capacity", which is often ignored.
var intList = new List<int>(1,  42); 
var stringList = new List<string>(1, "First");
```

**Comment by stephentoub** [comment]
> We would have one less function call, and in (very) hot paths,

`List<T>.Add` is small and aggressively inlined. And any code path involving this ctor would be allocating both the list and the underlying array, which will dwarf any possible benefits, e.g. avoiding one bounds check. It would have to be a huge savings to warrant adding such a ctor for such an uncommon case that's already perfectly well handled by other means.

**Comment by eiriktsarpalis** [comment]
Closing as not planned.
