### ISSUE TITLE
Optimize `lsraRegOrder` and `buildPhysRegRecords` to skip non-AVX512 registers if AVX512 not available

### ISSUE THREAD

**Issue by anthonycanino** [dotnet/runtime#81847]
Per comment https://github.com/dotnet/runtime/pull/79544#discussion_r1099763413 : we can optimize this section of the code to only use/initialize the `AVX512` register records if `AVX512` is detected at runtime. See commit https://github.com/dotnet/runtime/pull/79544/commits/3c7acdbb2e11f297fa772941751e83467aaa3a1c for a rough idea of how to structure these changes.

**Comment by anthonycanino** [comment]
@JulieLeeMSFT please assign me, we are working on this internally.

**Comment by tannergooding** [comment]
This was partially covered by https://github.com/dotnet/runtime/pull/83862

**Comment by anthonycanino** [comment]
@tannergooding when I wrote this issue, this is the optimization I had in mind (fix some of the lsraRegOrder pertaining to the extra AVX512 registers).

Did you have something else in mind?

**Comment by tannergooding** [comment]
No, I had just interpreted the title as implying something additional. If everything intended to be covered was, then please feel free to close

**Comment by BruceForstall** [comment]
This is complete.
