### ISSUE TITLE
[release/6.0] The target framework 'net5.0' is out of support and will not receive security updates in the future

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#81850]
Already have a PR out to fix this but wanted to report it using the Known Issues feature so it gets auto tagged in PRs.
https://github.com/dotnet/runtime/pull/81848

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=163537
Build error leg or test failing: Libraries Build windows allConfigurations x64 Debug / Restore and Build Product
Pull request: https://github.com/dotnet/runtime/pull/81307

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "The target framework 'net5.0' is out of support and will not receive security updates in the future",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[163537](https://dev.azure.com/dnceng-public/public/_build/results?buildId=163537)|dotnet/runtime|Restore and Build Product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/163537/logs/1007)|dotnet/runtime#81307|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|1|

**Comment by ViktorHofer** [comment]
Fixed by https://github.com/dotnet/runtime/pull/81848
