### ISSUE TITLE
RegexGenerator sporadically failed to generate source in design time builds only

### ISSUE THREAD

**Issue by Suchiman** [dotnet/runtime#81891]
### Description

I often notice that my generated regexes stop working in VS.
While this does not affect builds (builds succeed without errors), it does fill up my error list with bogus errors 
![image](https://user-images.githubusercontent.com/7110884/217850326-153b6159-3eda-4b7e-bc26-2cfd8938120b.png)

### Reproduction Steps

Not sure, occurs after a random amount of time of using VS

### Expected behavior

Generated Code is always visible in VS

### Actual behavior

Source does not always get generated in VS

### Known Workarounds

Restart VS

### Configuration

.NET 7
Windows 10
Visual Studio 2022 17.5 Preview 6

**Comment by stephentoub** [comment]
Do you have the full stack trace for that CS8785 warning?  That appears to be coming from within Roslyn itself.
cc: @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
I believe this has been fixed. @jcouv @chsienki ?

**Comment by Suchiman** [comment]
> Do you have the full stack trace for that CS8785 warning

Unless i've missed something to reveal more, that was all the stack trace given when expanding the warning by clicking on the triangle to the left

**Comment by chsienki** [comment]
@CyrusNajmabadi no, we have a simple repro now, but still figuring out exactly what's causing it.

**Comment by stephentoub** [comment]
Is there a dotnet/roslyn issue we should resolve this as a dup of?

**Comment by chsienki** [comment]
https://github.com/dotnet/roslyn/issues/66451

**Comment by stephentoub** [comment]
Thanks
