### ISSUE TITLE
[Questions] How to know the latest installed dotnet sdk version on a non sdk style project file like .vcxproj

### ISSUE THREAD

**Issue by anchurcn** [dotnet/runtime#81899]
I want to include the nethost.h file in the dotnet distribution path.
If I get the latest dotnet sdk version, I can get Microsoft.NETCoreSdk.BundledVersion.props, and the info about navigating to nethost.h is define there.

**Comment by AR-May** [comment]
MSBuild team triage: Moving to runtime repo, because it seems like there should be some guidance how to do that.

**Comment by rainersigwald** [comment]
> A more question: Can msbuild get registry data easy? Must I implement a custom ITask? Thanks.

You can [access the registry via property](https://learn.microsoft.com/visualstudio/msbuild/msbuild-properties?view=vs-2022#registry-properties), but it tends to be fragile and we don't generally recommend it.

**Comment by vitek-karas** [comment]
> I want to include the nethost.h file in the dotnet distribution path.

Can you please explain in a bit more detail what does this mean?

/cc @elinor-fung

**Comment by anchurcn** [comment]
@vitek-karas I want to write a custom host (a slim dll between native windows app and managed assembly) to load managed library. I need to set an additional include path to find `nethost.h` where under "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Host.win-x86\6.0.13\runtimes\win-x86\native". I want to use a relative path rather than a hard-coded path in .vcxproj like "$(DotnetRoot)\packs\Microsoft.NETCore.App.Host.win-x86\$(InstanlledNewest6.x.xVersion)\runtimes\win-x86\native". 

![image](https://user-images.githubusercontent.com/42488109/218774474-fbd440ff-4cd1-49be-9892-64ebafe2e12d.png)
[Microsoft.NETCore.App.Host is installed with .NET SDK](https://learn.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting#create-a-host-using-nethosth-and-hostfxrh:~:text=the%20nethost%20header%20and%20library%20installed%20with%20the%20.NET%20SDK).

**Comment by anchurcn** [comment]
@vitek-karas Thank you, it's a nice solution.
