### ISSUE TITLE
[7.0] System.Net.Http.Json nuget issue in allconfigurations

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#81914]
After merging this backport PR: https://github.com/dotnet/runtime/pull/80553

I looked at the [public rolling builds for 7.0](https://github.com/dotnet/runtime/commits/release/7.0) and noticed a windows all-configurations failure related to the nuget package System.Net.Http.Json, which unfortunately did not show up in the PR CI.

- Rolling build run: https://github.com/dotnet/runtime/runs/11233952875
- Queue: `Libraries Build windows allConfigurations x64 Release`
- Failure:

```
artifacts\bin\testPackages\projects\System.Net.Http.Json\project.csproj(0,0): error NU1102: (NETCORE_ENGINEERING_TELEMETRY=Build) Unable to find package System.Text.Json with version (>= 7.0.2)
  - Found 1560 version(s) in dotnet7 [ Nearest version: 7.0.0-rtm.22511.4 ]
  - Found 98 version(s) in dotnet-public [ Nearest version: 7.0.1 ]
  - Found 1 version(s) in dotnet-eng [ Nearest version: 5.0.0-alpha.1.19618.1 ]
  - Found 1 version(s) in dotnet7-transport [ Nearest version: 7.0.0-rc.1.22426.10 ]
  - Found 0 version(s) in D:\a\_work\1\s\artifacts\packages\Release\
  - Found 0 version(s) in richnav
  - Found 0 version(s) in darc-pub-dotnet-emsdk-ba16583
  - Found 0 version(s) in dotnet-libraries
  - Found 0 version(s) in dotnet-tools
```

Looking at the System.Net.Http.Json.csproj change history, I see that the above PR was the first one to modify the project, so the OOB changes look right (version 1 bump): https://github.com/dotnet/runtime/commits/release/7.0/src/libraries/System.Net.Http.Json/src/System.Net.Http.Json.csproj

Since the error is complaining about System.Text.Json specifically, I checked its change history too, and the last time it was modified was in the branding PR from a couple days ago, which simply turned off the GeneratePackageOnBuild property, but the servicing version remains as 2: https://github.com/dotnet/runtime/commit/e35c90f01bb7a9a1b4d8cea5fd1b724d4baaa8f1 

I am not sure I understand the reason for the complaint. @ViktorHofer @ericstj any ideas?

```json
{
  "ErrorMessage": "Unable to find package System.Text.Json with version (>= 7.0.2)",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by carlossanlop** [comment]
I think I know what the problem is. The System.Text.Json nuget package was never pushed from the last release: https://www.nuget.org/packages/System.Text.Json#versions-body-tab

The last version available in nuget.org is 7.0.1. The error above is asking for 7.0.2.

@rbhanda @mmitche can one of you help push the 7.0.2. nuget package we generated in the February Release?

**Comment by MihaZupan** [comment]
My guess would be that the 7.0.2 version of System.Text.Json isn't on our engineering nuget feeds. I'll ping engineering.

**Comment by carlossanlop** [comment]
So we can't push it yet because GA day for the February Release is 2/14. We're discussing workarounds.

**Comment by lewing** [comment]
is this fixed then?

**Comment by ViktorHofer** [comment]
Yes this is already fixed. The package is on nuget.org and on our feeds.
