### ISSUE TITLE
is possible to use DispatchProxy without interface?

### ISSUE THREAD

**Issue by coader** [dotnet/runtime#81938]
as Castle.DynamicProxy can  pass class type to create proxy:
```
new ProxyGenerator().CreateClassProxy<TSource>(i)
```
TSouce could be class, not only interfqce

but DispatchProxy limit the generic type to be inteface
System.ArgumentException: The type 'xxxx' must be an interface, not a class. (Parameter 'T')

how can I use calss type, because thouse calss is already there can hard to refactor to interface

**Comment by buyaa-n** [comment]
As you noticed `DipatchProxy` only support proxying interfaces, unfortunately no class support. 

There is an API proposal asking for adding such support https://github.com/dotnet/runtime/issues/38873
