### ISSUE TITLE
SetBrowserRequestCredentials doesn't work in combination with headers

### ISSUE THREAD

**Issue by Matti-Koopa** [dotnet/runtime#81952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is a WebAssembly / Blazor Clientside Bug.
This bug happens, when when adding `DefaultRequestHeaders` to a `HttpClient` and setting `SetBrowserRequestCredentials` to include credentials (for like a CORS preflight request).
The credentials will not be sent when including custom headers or headers like `IfModifiedSince`.

Working code:
```
var client = _httpClientFactory.CreateClient();
var message = new HttpRequestMessage(HttpMethod.Get, new Uri("https://myweirdapi.example:4543/someaddress"));
message.SetBrowserRequestCredentials(BrowserRequestCredentials.Include);
var response = await client.SendAsync(message).ConfigureAwait(false);
```

Non-working code:
```
var client = _httpClientFactory.CreateClient();
client.DefaultRequestHeaders.IfModifiedSince = DateTime.UtcNow;
var message = new HttpRequestMessage(HttpMethod.Get, new Uri("https://myweirdapi.example:4543/someaddress"));
message.SetBrowserRequestCredentials(BrowserRequestCredentials.Include);
var response = await client.SendAsync(message).ConfigureAwait(false);
```

### Expected Behavior

It shouldn't matter what headers are set.

### .NET Version

7.0.102

### Anything else?

.NET 7.0, C# 11
Visual Studio 17.4.4
```
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.102\

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]
  6.0.402 [C:\Program Files\dotnet\sdk]
  7.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found
```

**Comment by Matti-Koopa** [comment]
This is not a server-side issue. I'm aware that CORS-preflight requests should not require credentials.
Sadly, I'm dealing with a reverse proxy that blocks preflight-requests to the target server with 500 when they do not contain a client certificate.
A browser can go around that non-standard behavior, by setting "credentials" to "include". This works fine as long as I don't set any extra headers. Like I described, it is disregarded as soon as I have added extra headers. The browser just doesn't send the credentials anymore.

**Comment by maraf** [comment]
Can you please validate that your code works without the proxy?
Does the browser print any error to the console or it just sends the requests without credentials?

> A browser can go around that non-standard behavior, by setting "credentials" to "include".

That is exactly what the `SetBrowserRequestCredentials(BrowserRequestCredentials.Include)` does under the hood. 

Since WebAssembly networking can only be relealized through javascript interop and we are using fetch. Can you test calling your API from javascript? What fetch options are needed? Just to be sure that what you are trying to accomplish is possible in the browser.
