### ISSUE TITLE
[API Proposal]: Clean up System.Text.Json chaos

### ISSUE THREAD

**Issue by ygoe** [dotnet/runtime#81968]
### Background and motivation

I don't understand how System.Text.Json is supposed to work. There is JsonDocument, JsonValue, JsonElement and JsonNode and none of them work together. The official documentation doesn't explain it either. It feels like a chaos of different non-interoperable concepts, grown in the wrong direction. I'd suggest removing it altogether and starting from a fresh base with a single consistent API like every other programming language has one.

### API Proposal

I have a JsonElement object that comes from a web API controller. It accepts any JSON value that I don't care about, it just needs to be passed on to another place. But I need to save it in a JSON file, load it again, and embed it into another JSON object. So using plain strings is not a good idea. It's impossible anyway, because a web API action cannot give me the raw JSON request body as a string. It always wants to interpret it in any way. And returning a string from an action will never result in a JSON object, always a JSON string.

### API Usage

JsonElement provides no methods or anything to construct new objects. JsonNode does, but it's unwilling to accept the JsonElement of type object that I have:

```
InvalidOperationException: The element cannot be an object or array.
   at System.Text.Json.Nodes.JsonValue.VerifyJsonElementIsNotArrayOrObject(JsonElement& element)
   at System.Text.Json.Nodes.JsonValue.Create(JsonElement value, Nullable`1 options)
```

### Alternative Designs

Using Json.NET maybe? I just had the impression that Microsoft didn't like it that much and wanted to do something on their own.

I'll try to convert JsonElement to a string and then parse it back as JsonNode, if that's possible at all. Or I'll ask my customer to change their API because C# can do everything well but unfortunately not JSON.

### Risks

Break everyone's code who had arranged with the existing API. But it'd allow everyone else to use it.

**Comment by stephentoub** [comment]
Thank you for the feedback.

> I'd suggest removing it altogether and starting from a fresh base with a single consistent API like every other programming language has one.

If there are specific improvements you'd hope to see made, we'd welcome you to open issues, e.g. bugs, missing APIs, concrete scenarios that are hard to achieve because of missing features.  However, we will not be removing System.Text.Json, and as that is the purpose of this issue, I'm going to close it.

Thank you.

**Comment by ygoe** [comment]
Unfortunately, I cannot do the work to design a usable JSON API. But it's a fact that the existing one causes me nothing but trouble and pain. And it's probably very inefficient when I need to serialize and deserialize to strings all the time. If .NET doesn't want to cover it, I'll have to find third-party solutions.

**Comment by Clockwork-Muse** [comment]
> It's impossible anyway, because a web API action cannot give me the raw JSON request body as a string. It always wants to interpret it in any way. And returning a string from an action will never result in a JSON object, always a JSON string.

This is obviously framework dependent, but assuming you're using ASP.NET Core you can do both of those things.

> JsonElement provides no methods or anything to construct new objects. JsonNode does, but it's unwilling to accept the JsonElement of type object that I have:

So don't use `JsonElement` at all, do everything with `JsonNode`.

**Comment by ArminShoeibi** [comment]
> Unfortunately, I cannot do the work to design a usable JSON API. But it's a fact that the existing one causes me nothing but trouble and pain. And it's probably very inefficient when I need to serialize and deserialize to strings all the time. If .NET doesn't want to cover it, I'll have to find third-party solutions.

Hello there,

I recommend that read the source code and find out, it is really enjoyable.

Kindly check these things:
https://devblogs.microsoft.com/dotnet/whats-next-for-system-text-json/#what-we-shipped-in-net-core-3-0
![image](https://user-images.githubusercontent.com/68565441/218194695-aaa5efea-289e-4fc3-bc86-148d70583875.png)



https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-4/#system-text-json-writable-dom-feature
![image](https://user-images.githubusercontent.com/68565441/218195062-fdeb6cd4-63b3-432e-8e44-18b79f3a6f07.png)


and the last:

https://source.dot.net/#System.Text.Json,namespaces
