### ISSUE TITLE
Crossgen2 asserts in JIT when compiling The JIT\Regression\JitBlue\Runtime_81739

### ISSUE THREAD

**Issue by janvorli** [dotnet/runtime#81963]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=167278
Build error leg or test failing: JIT\\Regression\\JitBlue\\Runtime_81739\\Runtime_81739\\Runtime_81739.cmd
Pull request: https://github.com/dotnet/runtime/pull/81956

## Error Message

" "dotnet" "C:\h\w\ACF5090A\p\crossgen2\crossgen2.dll" @"C:\h\w\ACF5090A\w\AA3A0904\e\JIT\Regression\JitBlue\Runtime_81739\Runtime_81739\Runtime_81739.dll.rsp"   -r:C:\h\w\ACF5090A\w\AA3A0904\e\JIT\Regression\JitBlue\Runtime_81739\Runtime_81739\IL-CG2\*.dll"
D:\a\_work\1\s\src\coreclr\jit\emitxarch.cpp:6034
Assertion failed 'isFloatReg(dstReg) && isFloatReg(srcReg)' in 'Runtime_81739:Main():int' during 'Generate code' (IL size 27; hash 0x0dd256ab; FullOpts)

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by JulieLeeMSFT** [comment]
@TIHan PTAL this blocking clean ci error in emitter.
CC @dotnet/jit-contrib.

**Comment by EgorBo** [comment]
#81721 ?

**Comment by TIHan** [comment]
Will look into it.

**Comment by TIHan** [comment]
@EgorBo - [#81721](https://github.com/dotnet/runtime/pull/81721) shouldn't have affected this. It looks like a hw intrinsic bug.

**Comment by jakobbotsch** [comment]
The test itself is new -- I added in #81787

**Comment by TIHan** [comment]
@jakobbotsch - This may be a struct promotion bug.

If I run crossgen2 without `--inputbubble`, I can see struct promotion occurs:

Left is without `--inputbubble`.
Right is with `--inputbubble`.
![image](https://user-images.githubusercontent.com/1278959/218202072-b40477cd-b164-4a19-b2c1-6830a1366044.png)

**Comment by jakobbotsch** [comment]
@TIHan Yes, likely something in codegen does not handle the promoted field correctly, or something upstream needed to DNER it.

**Comment by TIHan** [comment]
I have a fix in place, will probably need to run the R2R CI to double check.
