### ISSUE TITLE
Various System.Security.Cryptography libraries tests failing on the ES build machines

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#81967]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=166557
Build error leg or test failing: System.Security.Cryptography.Xml.Tests.DSAKeyValueTest.GetXml
Pull request: https://github.com/dotnet/runtime/pull/81925

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "BuildRetry": false,
  "ErrorPattern": "(No hay más extremos disponibles desde el asignador de extremos\.|Algoritmo especificado no es válido\.)",
  "ExcludeConsoleLog": false
}
```

**Comment by stephentoub** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/74838
