### ISSUE TITLE
IIdentity Nullable contract doesn't match expected

### ISSUE THREAD

**Issue by EdLichtman** [dotnet/runtime#81966]
### Description

The Name and AuthenticationType for IIdentity are both "String". They are not "String?"

However, when I try to use them, I'm required to use the Null forgiving operator or customize my own implementation. Since I don't know exactly how this package works under the hood, I don't know if I can put the null forgiving operator. This makes using it very verbose.

### Reproduction Steps

You can find the behavior here. Just copy that function into any class in DotNet Core or Standard, with <Nullable> in the csproj, and you'll see that it claims that the underlying entity is could result in a Null Exception.
https://github.com/EdLichtman/ApiVersioningDefectExample/blob/main/DefectExamples/NullableStringInIdentity.cs

### Expected behavior

I expect to be able to use these properties without having a bunch of null forgiveness, since the contract is a String.

### Actual behavior

I need to add a bunch of null forgiveness, whether it be with the forgiving operator or with String.IsNullOrWhitespace() usage.

### Known Workarounds

using the Null Forgiveness operator is an easier workaround but I feel less confident due to it not being my code, and knowing the compiler is telling me that there's a chance that this will blow up in my face. Therefore, the only other workaround is:

!String.IsNullOrWhitespace(identity.Name) ? identity.Name : String.Empty.

### Configuration

.net version: 7.0.102
---------------------------------------------------------------------------------------------
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19045.0 Microsoft Windows NT 10.0.19045.0
---------------------------------------------------------------------------------------------
Not specific to this configuration.

**Comment by stephentoub** [comment]
I'm not following the concern.  The Name and AuthenticationType properties are both defined as returning nullable strings:
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Runtime/ref/System.Runtime.cs#L11090-L11095
and some implementations do return null from these properties.  Can you elaborate on what doesn't match?

**Comment by EdLichtman** [comment]
interesting. @stephentoub the mscorlib contract is not nullable:
`namespace System.Security.Principal
{
    //
    // Summary:
    //     Defines the basic functionality of an identity object.
    [ComVisible(true)]
    [__DynamicallyInvokable]
    public interface IIdentity
    {
        //
        // Summary:
        //     Gets the name of the current user.
        //
        // Returns:
        //     The name of the user on whose behalf the code is running.
        [__DynamicallyInvokable]
        string Name
        {
            [__DynamicallyInvokable]
            get;
        }

        //
        // Summary:
        //     Gets the type of authentication used.
        //
        // Returns:
        //     The type of authentication used to identify the user.
        [__DynamicallyInvokable]
        string AuthenticationType
        {
            [__DynamicallyInvokable]
            get;
        }

        //
        // Summary:
        //     Gets a value that indicates whether the user has been authenticated.
        //
        // Returns:
        //     true if the user was authenticated; otherwise, false.
        [__DynamicallyInvokable]
        bool IsAuthenticated
        {
            [__DynamicallyInvokable]
            get;
        }
    }
}`

As is the Netstandard which resolves to the mscorlib on disc when I try to decompile it.

I suppose there is no issue, now that I see that it is indeed nullable. I suppose there's no way to modify the libraries that don't say nullable since they are on a framework prior to nullable objects?

**Comment by stephentoub** [comment]
> interesting. @stephentoub the mscorlib contract is not nullable:

mscorlib is part of .NET Framework, which has not been annotated for nullable reference types.  All types in .NET Framework and .NET Standard reference assemblies are not enabled for nullable reference types and are thus considered "oblivious" by the compiler.  There's no plan or good way to change that.

**Comment by EdLichtman** [comment]
Understood. ready to close.
