### ISSUE TITLE
System.Text.Json incorrectly serializes Half (float16) type

### ISSUE THREAD

**Issue by Davisjames0901** [dotnet/runtime#81970]
### Current Behavior
When using the System.Text.Json serializer Half type is serialized as an empty json object. 

### Expected Behavior
Half type should be serialized as a floating point value like the other floating point primitives in C#.

### Environment
**Tested SDK Versions:** 7.0.102 and 6.0.113
**Tested Operating Systems:** Fedora 37 and Windows 10
**CPU Architecture:** x64</br>
### Code Sample
```cs
var num = 1.01;
var float16 = System.Text.Json.JsonSerializer.Serialize((Half)num);
var float32 = System.Text.Json.JsonSerializer.Serialize((float)num);
var float64 = System.Text.Json.JsonSerializer.Serialize((double)num);

Console.WriteLine($"Half: {float16}");
Console.WriteLine($"float: {float32}");
Console.WriteLine($"double: {float64}");
```
### Output
```
Half: {}
float: 1.01
double: 1.01
```

**Comment by eiriktsarpalis** [comment]
Related to https://github.com/dotnet/runtime/issues/60780 and https://github.com/dotnet/runtime/issues/73500.

In the meantime, you might be able to find a reference implementation for a `Half` converter in our functional tests: https://github.com/dotnet/runtime/pull/74254.

**Comment by eiriktsarpalis** [comment]
Closing in favor of https://github.com/dotnet/runtime/issues/87994
