### ISSUE TITLE
Using 7.0.x packages for net6.0

### ISSUE THREAD

**Issue by WenningQiu** [dotnet/runtime#81971]
While enabling net7.0 target on my applications, I found that the 7.0.x packages also support .NET 6 so I just used the newer packages versions below for both net6.0 and net7.0 targets as below:

```
  <ItemGroup Condition=" '$(TargetFramework)' == 'net6.0' Or '$(TargetFramework)' == 'net7.0' ">
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="7.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Physical" Version="7.0.0" />
  </ItemGroup>
```
Applications compile cleanly in Visual Studio. However if I run publish command I would get the error below:
```
Assembly 'ACPxOrder.Api.Common' with identity 'ACPxOrder.Api.Common, Version=23.2.0.0, Culture=neutral, PublicKeyToken=15b1e4e352f38106' uses 'Microsoft.Extensions.Configuration.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.Extensions.Configuration.Abstractions' with identity 'Microsoft.Extensions.Configuration.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'    
```
So my questions are:

1. Is it acceptable to use 7.0.x versions for net6.0 applications?
2. Is publish behavior correct or should MSBuild/VS and publish command behave consistently?

**Comment by ViktorHofer** [comment]
> Is it acceptable to use 7.0.x versions for net6.0 applications?

See https://github.com/dotnet/runtime/issues/81740 for a detailed response. TL;DR: Yes, that's fully supported.

> Is publish behavior correct or should MSBuild/VS and publish command behave consistently?

`Assembly 'ACPxOrder.Api.Common' with identity 'ACPxOrder.Api.Common, Version=23.2.0.0, Culture=neutral, PublicKeyToken=15b1e4e352f38106' uses 'Microsoft.Extensions.Configuration.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.Extensions.Configuration.Abstractions' with identity 'Microsoft.Extensions.Configuration.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'`

That error indicates that you are referencing a Microsoft.Extensions.configuration.Abstractions/6.0.0.0 somewhere in your library (probably automatically via a NuGet package or by using AspNetCore) while also referencing a newer version of that library as a transitive package reference. Try to also add a `Microsoft.Extensions.Configuration.Abstractions` package reference with a 7.0.x version.

**Comment by WenningQiu** [comment]
The source might be from ASP.NET Core packages. Unlike most Microsoft packages that support multiple target frameworks. Microsoft.AspNetCore.* packages target single tfm.

```
<ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp3.1' ">
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="3.1.7" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="3.1.7" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net5.0' ">
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="5.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="5.0.3" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net6.0' ">
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="6.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="6.0.2" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net7.0' ">
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="7.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="7.0.2" />
  </ItemGroup>
```

**Comment by ericstj** [comment]
Correct, for ASP.NET packages you can only use those which support the framework you're targeting.

For packages from dotnet/runtime it's acceptable to use the newer packages on the older framework -- you'll get those packages app-local.  This is specifically how packages like `System.Text.Json` add API and make it available for `netstandard2.0`.  We couldn't do that if we didn't allow newer packages to be used on older frameworks.

You do have to be aware of support lifecycle - 7.0 will go out of support - at which point you should move to 8.0.

@WenningQiu - if you have further requests/questions for ASP.NET - please open an issue in that repository.
