### ISSUE TITLE
SocketsHttpHandler persistent request timeouts due to .NET 6 connection pooling behavior

### ISSUE THREAD

**Issue by markalward** [dotnet/runtime#81989]
### Description

We observed a sporadic issue in our service where requests to Azure Table Storage and Azure Blob Storage would start continuously timing out until the application was restarted. This was related to the `SocketsHttpHandler` connection pooling logic on .NET 6.

The trigger condition is a broken network connection between the client and server; the server stops sending packets to the client, with no RST or FIN to signal a connection close. This is fairly common, since load balancers and other network appliances can drop connections spuriously, breaking the flow of packets between a client and server.

Two issues then cause this one network blip to become a persistent failure:
1) `SocketsHttpHandler.ConnectTimeout` defaults to infinite, which allows a connection attempt to remain pending forever. On .NET 6, I don't think there is any timeout in `HttpConnectionPool.ConnectAsync()` when the default infinite timeout is used. The operating system TCP connect timeout might timeout the connection attempt in some cases, but in our scenario the connection is dropped in the middle of the TLS handshake while reading from the socket. There is no timeout for this read.
2) `HttpConnectionPool` tries to reuse this one pending connection for every new request that comes in. Rather than creating a new connection, each request waits for this one connection to become ready. Since the connection establishment will never complete (because of point 1),  every request times out waiting for the connection to become ready.

This failure persists for the lifetime of the app because the table client library we are using (https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table) makes use of a singleton `HttpClient`. After one of these "zombie" connection attempts enters the connection pool, all later requests through the same connection pool continuously time out.

I believe this is already fixed on .NET 7, and I'm not able to repro on .NET 7. I'm filing the issue because this is a fairly common scenario (interacting with Azure services) that is impacted by the .NET 6 connection pooling behavior, and there are likely many customers still on .NET 6.

### Reproduction Steps

This app causes `SocketsHttpHandler` to go into the bad state described above, where all requests try to reuse one infinitely pending connection:

https://github.com/markalward/DotNet/blob/main/ConnectTimeoutRepro/ConnectTimeoutRepro/Program.cs

Instead of an actual network drop, the server simulates the condition by not sending any data to the client so that the client remains blocked indefinitely on a socket read.

The output for the program is:

Client: Sending request
**Client: Creating new connection**
**Server: Accepted connection**
Client: Request timed out
Client: Sending request
Client: Request timed out
Client: Sending request
Client: Request timed out
...

The key point is that there is a single connection attempt at the beginning, and none of the subsequent requests trigger new connection attempts.

### Expected behavior

Requests should continue to succeed after a transient network drop.

### Actual behavior

A transient network drop can result in a persistent failure mode where all future requests to the same server timeout.

### Known Workarounds

- Set `SocketsHttpHandler.ConnectTimeout` to a non-default value, so that connections eventually time out.
- Discard and recreate the `HttpClient` object. This was the solution we used with the table storage library, though it required some hacks since the underlying `HttpClient` isn't exposed directly to the library user.

### Configuration

- .NET 6 (patch 6.0.13)
- Windows Server 2019
- x64
- Specific to .NET 6, no repro on .NET 7

**Comment by antonfirsov** [comment]
This is a known problem in .NET 6.0, we fixed it in #71785 for 7.0. That change is far from trivial, I don't think it's safe to backport it to 6.0.

> the table client library we are using (https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table)

That package is said to be deprecated. I wonder if the recommended replacement (Azure.Data.Tables) provides any ways to configure `SocketsHttpHandler` (for `ConnectTimeout`) without hacks?
