### ISSUE TITLE
JsonNull should not return true when compared to null using Equals (or ==)

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/runtime#820]
See https://github.com/dotnet/runtime/pull/528#discussion_r355094922 for details.

Currently the `==` operator on JsonNull always returns true. It should instead follow what other `JsonNode` types do and treat `null` differently.

This is about making sure JsonNull equality works as expected along with adding appropriate tests.

https://github.com/dotnet/runtime/blob/d8f744dbd3ee9f3189a46e1886b63dc1a9fd5efc/src/libraries/System.Text.Json/src/System/Text/Json/Node/JsonNull.cs#L41-L62

**Comment by henrikse55** [comment]
An existing test will fail if Equals return false when comparing against null.

https://github.com/dotnet/runtime/blob/71d7e6cd72e9d4154f595cc43adac4b66ca53e48/src/libraries/System.Text.Json/tests/JsonNullTests.cs#L47-L53

I wouldn't mind updating the test as well but I can't find anything in the docs stating whether modifying existing tests is allowed

**Comment by bartonjs** [comment]
@henrikse55 For a feature that already shipped, it's generally a bad idea.  This one is still in development, and we're correcting guidelines violations... so changing the tests is correct.
