### ISSUE TITLE
[RISC-V Port] runtime_invoke_virtual call the uncompiled function object:Finalize()

### ISSUE THREAD

**Issue by Xinlong-Wu** [dotnet/runtime#82010]
I am recently trying to port MonoVM for the RISC-V architecture, but I have encountered some problems in the process.
I've been stuck with this problem for a long time and had to come here for help

I am try to run the following code
```C#
namespace HelloWorld
{
  class Program
  {
    static void Main()
    {
      return;
    }
  }
}
```

The MonoVM calls GC after compiling the following method
```
System.OutOfMemoryException:.ctor (string)
 (wrapper runtime-invoke) <Module>:runtime_invoke_void__this___object (object,intptr,intptr,intptr)
System.SystemException:.ctor (string)
System.Exception:.ctor (string)
System.Exception:.cctor ()
(wrapper runtime-invoke) object:runtime_invoke_void (object,intptr,intptr,intptr)
(wrapper alloc) object:AllocSmall (intptr,intptr)
(wrapper managed-to-native) object:__icall_wrapper_mono_gc_alloc_obj
System.Exception:Init ()
System.Exception:set_HResult (int)
System.NullReferenceException:.ctor (string)
System.StackOverflowException:.ctor (string)
HelloWorld.Program:Main ()
HelloWorld.Program:.ctor ()
```

The Finalize Thread compile and call the function `runtime_invoke_virtual` in `mono/metadata/gc.c:mono_gc_run_finalize`.

**The problem is** the function `object:Finalize ()` are called by `runtime_invoke_virtual` without compile, so that it jump to a non-execuate area from `runtime_invoke_virtual` and then crashed. 

I would like to know what could be the reason why the method object:Finalize () is not compiled and how I should solve this problem?

**Comment by am11** [comment]
Hi, great progress! 👍
Can you call other library methods from `Main()` at this point in port? e.g. `System.Console.WriteLine("Hello World!");`

Does the full trace show something useful:
```sh
# catch all traces in `mono-trace.txt`
$ MONO_LOG_LEVEL=debug MONO_LOG_MASK=all MONO_ENV_OPTIONS="--trace=all" \
  COREHOST_TRACE=1 COREHOST_TRACE_VERBOSITY=4 \
    /path/dotnet /path/HelloWorld.dll 2>&1 | tee mono-trace.txt
```
(try comparing it with the output collected from e.g. linux-x64 system where it succeeds)

**Comment by HJLeee** [comment]
@Xinlong-Wu You might be interested in https://github.com/dotnet/runtime/issues/36748#issuecomment-1429055659

**Comment by am11** [comment]
@HJLeee that comment is for coreclr, this is about mono.

**Comment by HJLeee** [comment]
@am11 I was wondering if @Xinlong-Wu might be interested in .NET runtime on RISC-V in general. Sorry for missing intension.

**Comment by Xinlong-Wu** [comment]
I am verifying my implementation by comparing it with the X86 trace log. 
There are some differences in some of following traces.

x86 trace log:
```
[0x7fe3dae9f740: 0.23198 15] ENTER:c System.Text.Ascii:NarrowUtf16ToAscii (char*,byte*,uintptr)(0x7fe3d7b84144, 0x7ffef9b3e740, 0x1a)
[0x7fe3dae9f740: 0.23200 16] ENTER:c System.Diagnostics.Debug:Assert (bool)(1)
[0x7fe3dae9f740: 0.23200 17] ENTER:c System.Diagnostics.Debug:Assert (bool,string,string)(1, [STRING:0x7fe3d7b8c130:], [STRING:0x7fe3d7b8c130:])
[0x7fe3dae9f740: 0.23201 17] LEAVE:c System.Diagnostics.Debug:Assert (bool,string,string)(
[0x7fe3dae9f740: 0.23201 16] LEAVE:c System.Diagnostics.Debug:Assert (bool)(
[0x7fe3dae9f740: 0.23210 16] ENTER:c System.Text.Ascii:AllCharsInUInt64AreAscii (ulong)(0x0050004d004f0043)
[0x7fe3dae9f740: 0.23211 16] LEAVE:c System.Text.Ascii:AllCharsInUInt64AreAscii (ulong)(result=1
[0x7fe3dae9f740: 0.23241 16] ENTER:c System.Text.Ascii:NarrowFourUtf16CharsToAsciiAndWriteToBuffer (byte&,ulong)([BYREF:0x7ffef9b3e740])
...
```

RISC-V 64 trace log:
```
[0x4002bc8440: 0.45909 15] ENTER:c System.Text.Ascii:NarrowUtf16ToAscii (char*,byte*,uintptr)(0x4002cfc151, 0x40028129d0, 0x28129d0)
[0x4002bc8440: 0.45934 16] ENTER:c System.Diagnostics.Debug:Assert (bool)(1)
[0x4002bc8440: 0.45940 17] ENTER:c System.Diagnostics.Debug:Assert (bool,string,string)(1, [STRING:0x40061b0130:], [STRING:0x40061b0130:])
[0x4002bc8440: 0.45945 17] LEAVE:c System.Diagnostics.Debug:Assert (bool,string,string)(
[0x4002bc8440: 0.45949 16] LEAVE:c System.Diagnostics.Debug:Assert (bool)(
[0x4002bc8440: 0.45967 16] ENTER:c (wrapper managed-to-native) object:__icall_wrapper___emul_lmul (long,long)(0x0000000000000000, 0x0000000000000002)
[0x4002bc8440: 0.45980 16] LEAVE:c (wrapper managed-to-native) object:__icall_wrapper___emul_lmul (long,long)(lresult=0x               0
[0x4002bc8440: 0.45988 16] ENTER:c (wrapper managed-to-native) object:__icall_wrapper___emul_lmul (long,long)(0x0000000000000000, 0x0000000000000002)
[0x4002bc8440: 0.45994 16] LEAVE:c (wrapper managed-to-native) object:__icall_wrapper___emul_lmul (long,long)(lresult=0x               0
[0x4002bc8440: 0.45999 16] ENTER:c (wrapper managed-to-native) object:__icall_wrapper___emul_lmul (long,long)(0x0000000000000002, 0x0000000000000002)
[0x4002bc8440: 0.46003 16] LEAVE:c (wrapper managed-to-native) object:__icall_wrapper___emul_lmul (long,long)(lresult=0x               4
[0x4002bc8440: 0.46085 16] ENTER:c System.Text.Ascii:AllCharsInUInt32AreAscii (uint)(1869574015)
[0x4002bc8440: 0.46098 16] LEAVE:c System.Text.Ascii:AllCharsInUInt32AreAscii (uint)(result=0
...
```

The difference is that X86 calls `AllCharsInUInt64AreAscii` in the `NarrowUtf16ToAscii` function, while RISC-V calls `AllCharsInUInt32AreAscii`.

Reading the following source code located in `Ascii.Transcoding.cs`
```
if (IntPtr.Size >= 8)
{
    if (!AllCharsInUInt64AreAscii(utf16Data64Bits))
    ...
}
else
{
    if (!AllCharsInUInt32AreAscii(utf16Data32BitsHigh | utf16Data32BitsLow))
    ...
}
```

Then I compared the RISC-V64's log of the `method-to-ir` process, but I didn't find the the control flow to to compare whether `IntPtr.Size >= 8`. So I guess it might be optmised by some function due to `IntPtr.Size` is a const value.
And The `IntPtr.Size` in RISC-V64 is been configured as 4 ***incorrectlly***, so that it call `AllCharsInUInt32AreAscii` instead of `AllCharsInUInt64AreAscii`.

Thus, how can I fix the configuration of `IntPtr.Size` ?

**Comment by Xinlong-Wu** [comment]
I have compare the IL of method `System.Text.Ascii:NarrowUtf16ToAscii`
here it is,

X64:
```
converting (in B10: stack: 0) IL_0039: ldc.i4    8
converting (in B10: stack: 1) IL_003e: ldc.i4.8  
converting (in B10: stack: 2) IL_003f: clt       
converting (in B10: stack: 1) IL_0041: ldc.i4.0  
converting (in B10: stack: 2) IL_0042: ceq       
converting (in B10: stack: 1) IL_0044: stloc.s   7
converting (in B10: stack: 0) IL_0046: ldloc.s   7
converting (in B10: stack: 1) IL_0048: pop       
converting (in B10: stack: 0) IL_0049: nop       
converting (in B10: stack: 0) IL_004a: ldarg.0   
converting (in B10: stack: 1) IL_004b: call      0x2b0002d7
cmethod = ulong System.Runtime.CompilerServices.Unsafe:ReadUnaligned<ulong> (void*)
created temp 46 (R92) of type System.UInt64
```

RISC-V 64:
```
converting (in B10: stack: 0) IL_0038: nop       
converting (in B10: stack: 0) IL_0039: ldc.i4    4
converting (in B10: stack: 1) IL_003e: ldc.i4.8  
converting (in B10: stack: 2) IL_003f: clt       
converting (in B10: stack: 1) IL_0041: ldc.i4.0  
converting (in B10: stack: 2) IL_0042: ceq       
converting (in B10: stack: 1) IL_0044: stloc.s   7
converting (in B10: stack: 0) IL_0046: ldloc.s   7
converting (in B10: stack: 1) IL_0048: brfalse.s IL_004a
converting (in B11: stack: 0) IL_004a: nop       
converting (in B11: stack: 0) IL_004b: ldarg.0   
converting (in B11: stack: 1) IL_004c: call      0x2b000405
cmethod = uint System.Runtime.CompilerServices.Unsafe:ReadUnaligned<uint> (void*)
created temp 46 (R108) of type System.UInt32
```

please compare the `IL_0039 ~ IL_003e` between two Arch. I guess these IL are coresponding to the satement `if (IntPtr.Size >= 8)` in C#. My guess would probably be right.

It might means that the issue is happened at CSC instead of dotnet. How can I solve it by passing any parameters?

**Comment by am11** [comment]
It looks like your branch is behind the main: https://github.com/Xinlong-Wu/runtime/blob/riscv-jit-rv64/src/libraries/System.Private.CoreLib/src/System.Private.CoreLib.Shared.projitems#L22 doesn't have riscv64 condition which is present in upstream `main`: https://github.com/dotnet/runtime/blob/bee217ffbdd6b3ad60b0e1e17c6370f4bb618779/src/libraries/System.Private.CoreLib/src/System.Private.CoreLib.Shared.projitems#L22 based on that, we define a constant `TARGET_64BIT` https://github.com/dotnet/runtime/blob/bee217ffbdd6b3ad60b0e1e17c6370f4bb618779/src/libraries/System.Private.CoreLib/src/System.Private.CoreLib.Shared.projitems#L30 and set the size of IntPtr https://github.com/dotnet/runtime/blob/0b47a4dc519ada9c56d6f4d62865c2d96a56510c/src/libraries/System.Private.CoreLib/src/System/IntPtr.cs#L17 -> https://github.com/dotnet/runtime/blob/0b47a4dc519ada9c56d6f4d62865c2d96a56510c/src/libraries/System.Private.CoreLib/src/System/IntPtr.cs#L160

Please rebase your branch against upstream `main` branch:

```sh
$ git remote add dotnet https://github.com/dotnet/runtime && git fetch --all
$ git pull --rebase dotnet main
```

**Comment by Xinlong-Wu** [comment]
right, that make sense )

**Comment by Xinlong-Wu** [comment]
I think I have complete initial support Mono for RISC-V, I mean, it's almost ready to compile and run the simplest "Hello World" programs. 
But I don't know why it doesn't output anything, both on X64 and RISC-V64, so I think I seem to be having this problem.
https://github.com/dotnet/runtime/issues/61468

**Comment by Xinlong-Wu** [comment]
I think I'm almost complete with the initial RISC-V support for Mono, but I'm now running into a problem.

When I pass in Mono's `--compile-all` parameter via the environment variable `MONO_ENV_OPTIONS`, the program fails to output any characters to the command line, regardless of the architecture. Here is a example of X64.

C# source code:
```C#
using System;
namespace HelloWorld
{
  class Program
  {
    static void Main()
    {
      Console.WriteLine($"IsMono: {Type.GetType("Mono.RuntimeStructs") != null}");
      Console.WriteLine("Hello RISC-V");
      return;
    }
  }
}
```

then I run the command
```bash
mcs TestRun.cs
COMPlus_DebugWriteToStdErr=1 \
MONO_ENV_OPTIONS="--compile-all" \
../../../../artifacts/bin/testhost/net8.0-linux-Debug-x64/dotnet TestRun.exe
```

the command line dosen't output anything and exit. Is this the kind of expected behavior? 
I can create a new issue for it If necessary

**Comment by am11** [comment]
I haven't used `--compile-all` option, but it looks like it is the expected behavior:

https://github.com/dotnet/runtime/blob/52652185bf5331ecf651ad4c0c575da720cab3c1/src/mono/mono/tests/tailcall/readme.txt#L84-L87

> I think I'm almost complete with the initial RISC-V support for Mono

Great! Feel free to post PRs for review with initial implementation. Other issues can be sorted out in follow-up PRs.

**Comment by Xinlong-Wu** [comment]
Mono for RISC-V is able to output Hello World to the command line now, the code is available at the repo https://github.com/Xinlong-Wu/runtime/tree/Milestone_Hello_World.

![image](https://user-images.githubusercontent.com/43398706/226174102-95ef65c3-8633-44ba-b531-ce498d8ad4da.png)

I will close this issue
and, @am11 thank you for you help at this stage ;)
