### ISSUE TITLE
JIT\opt\ThrowHelper\NonVoidThrowHelper failing with NativeAOT

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#82030]
With optimizations on, it looks like we optimize

https://github.com/dotnet/runtime/blob/be84df7642f21702b0e7859f0c134e4d6cfc67eb/src/tests/JIT/opt/ThrowHelper/NonVoidThrowHelper.cs#L45-L49

Into `ret`. I guess we figured out the `is` is never true, but we forgot about the other effect of the call.

Cc @EgorBo

**Comment by EgorBo** [comment]
@MichalStrehovsky from what I see so far, the problem seems to be on ILC side

NAOT's `getClassAttribs` states that Program is `CORINFO_FLG_FINAL` despite the fact there is a subclass `ProgramSubclass`

**Comment by jakobbotsch** [comment]
@EgorBo but even so we shouldn't be discarding the side effects of `GetClass` (it throws an exception)

**Comment by EgorBo** [comment]
> @EgorBo but even so we shouldn't be discarding the side effects of `GetClass` (it throws an exception)

Right, I'm filing a PR to fix that too. But we somehow never hit it (it's not a new code)

**Comment by EgorBo** [comment]
The problem with NativeAOT is that we have code like this:
```
public unsafe class Program
public sealed class ProgramSubclass : Program
```
but `getClassAttribs` says `Program` is final too (both of them are sealed)

**Comment by MichalStrehovsky** [comment]
> Right, I'm filing a PR to fix that too. But we somehow never hit it (it's not a new code)

We don't run JIT tests in src/tests in the NativeAOT CI yet. Thousands of tiny tests is hard to test with NativeAOT. It's being worked on.

> The problem with NativeAOT is that we have code like this:

I agree this is nonsensical. But also is this a real problem for the JIT if `ProgramSubclass` is guaranteed to be never allocated? We could stop sealing the `Program` class in situations like this but then we'll need some other mechanism to tell the JIT that a derived class instance can never happen or we'd be leaving perf on the table.
