### ISSUE TITLE
OleDb connection hangs Net6 process, fine for Net472

### ISSUE THREAD

**Issue by RobSwDev** [dotnet/runtime#82040]
We're attempting to port some legacy code from NetFramework to Net6, and I've hit some issues with OleDb.
I've created a simple repro app: I simply connect to an Excel file, then close the connection.
On Net472, this works as expected.
On Net6, this works, but the process hangs when exiting, continually spinning the CPU (and also locking the Excel file)

Installed components
Microsoft Access database engine 2016: 16.0.5044.1000 (64 bit)
Microsoft 365 Apps for enterprise 16.0.15601.20456 (64 bit)
Dotnet sdk 6.0.404   [also installed: 5.0.415, 7.0.102]

I imagine its something to do with the versions of Office and the AccessDatabaseEngine I have installed:
I have the 2016 one: https://www.microsoft.com/en-US/download/details.aspx?id=54920
If I uninstall this, and install the 2010 one: https://www.microsoft.com/en-us/download/details.aspx?id=13255
Then the Net6 process no longer hangs on exit.

I attached a project that reproduces the issue. I first noticed it in tests, when "testhost.exe" was hanging around after test completion, locking files, and assumed it was an issue with the test framework. But the Console app does also hangs.

[ExcelAceOleDb.zip](https://github.com/dotnet/core/files/10661660/ExcelAceOleDb.zip)

**Comment by roji** [comment]
This sounds very similar to #76054, though that issue is about ACE/Access rather than Excel. Though the fact that this works in .NET Framework is indeed new, and does point to an issue on the .NET Core side.

**Comment by SamMonoRT** [comment]
@RobSwDev - does this still repro for you with newer releases of .NET and Office? Can we close this issue?

**Comment by RobSwDev** [comment]
It does seem to work now - I guess it can be closed.

**Comment by SamMonoRT** [comment]
Seems working now, Closing the issue.
