### ISSUE TITLE
Test failure baseservices\\multidimmarray\\rank1array\\rank1array.cmd

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#82078]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=170661&view=ms.vss-test-web.build-test-results-tab&runId=3421503&resultId=121330&paneView=debug

```
    baseservices\multidimmarray\rank1array\rank1array.cmd [FAIL]
      
      Assert failure(PID 3164 [0x00000c5c], Thread: 4416 [0x1140]): Assertion failed 'OperIs(GT_NOP, GT_CALL, GT_COMMA) || OperIsCompare() || OperIsLong() || OperIsHWIntrinsic() || IsCnsVec()' in '<Module>:Main():int' during 'Lowering nodeinfo' (IL size 242; hash 0x3beb8c24; Tier0)
      
          File: D:\a\_work\1\s\src\coreclr\jit\gentree.h Line: 1076
          Image: C:\h\w\A994099D\p\corerun.exe
      
      
      Return code:      1
      Raw output file:      C:\h\w\A994099D\w\B6A50958\uploads\Reports\baseservices.multidimmarray\rank1array\rank1array.output.txt
      Raw output:
      BEGIN EXECUTION
       "C:\h\w\A994099D\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  rank1array.dll 
      Expected: 100
      Actual: -1073740286
      END EXECUTION - FAILED
      FAILED
```

**Comment by BruceForstall** [comment]
This was caused by https://github.com/dotnet/runtime/pull/77357

@EgorBo @AndyAyersMS @jakobbotsch

**Comment by EgorBo** [comment]
Oops, thanks, didn't expect that change to cause troubles.

Will work on a revert for this revert. According to our TE benchmark that PR is responsble for some improvements e.g. the 3rd bounce here 

<img width="1375" alt="Screenshot 2023-02-14 at 20 34 33" src="https://user-images.githubusercontent.com/523221/218839576-ac09dd76-28e4-4c20-b390-43d060f3cef8.png">
