### ISSUE TITLE
Support marshalled delegates with NativeAOT on iOS platforms

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/runtime#82090]
NativeAOT supports marshalled delegates for platforms with hardened runtime by using a scheme of preallocated thunks which is available under the `FEATURE_FIXED_POOL_THUNKS` preprocessor directive. However, it seems the functions used by this scheme are implemented in assembler and are only supported on Windows:
https://github.com/dotnet/runtime/blob/8d3070f90c557b920b0e53489f617ec55b186eed/src/coreclr/nativeaot/Runtime/arm64/ThunkPoolThunks.asm#L4 

Even though marshalled delegates are considered as a legacy feature, they can still be used in the user's code and even framework libraries (e.g., Xamarin: https://github.com/xamarin/xamarin-macios/blob/main/src/ObjCRuntime/Blocks.cs#L122) which means they have to be supported in some way. 

As a final note, NativeAOT supports function pointers which are preferred over marshalled delegates, as they have better performance and smaller footprint at runtime. Xamarin codebase is in process of fully switching to function pointers: https://github.com/xamarin/xamarin-macios/issues/10470.

**Comment by ivanpovazan** [comment]
@filipnavara noted that there is also a third thunk allocation scheme which could serve the purpose: https://github.com/dotnet/runtime/pull/81780#issuecomment-1424952093
Would you be interested in taking over this issue?

**Comment by filipnavara** [comment]
I have a prototype ready, so I would be happy to take a stab at it once the iOS build support lands.

**Comment by ivanpovazan** [comment]
Awesome, thanks! Assigning the issue to you then.
