### ISSUE TITLE
Error while building linux clr on windows

### ISSUE THREAD

**Issue by leocb** [dotnet/runtime#82119]
First of all, I need to compile my own linux runtimes because of my company policy on third party software and distribution policies. I already tested our project with the pre-compiled docker runtime and it works flawlessly, we just can't use that for our production environment, hence my headache.

I'm running the following command on a powershell terminal with admin privileges:

`.\build.cmd -c release -lc release -rc release -a x64 -os linux -s clr+libs -v n`

if I try `-os windows` it compiles all the way, no problem.

This is the error I'm getting:

![image](https://user-images.githubusercontent.com/8310271/218834062-a96acf7a-d074-4334-a58c-5ac46f5cf63c.png)

Any suggestions to get this compiler to work? I'm trying on WSL2 ubuntu right now, but I ain't hopefull.

**Comment by leocb** [comment]
Too bad we can't cross-compile linux on windows, it would save o lot of setup time for future maintainers of our codebase.

I just finished compiling on linux (ubuntu 22 on WSL2). seem like it worked, even though I got this error twice: `bash : error : setlocale: LC_ALL: cannot change locale (en_US.UTF-8) [/home/lbottaro/git/dotnet.runtime/src/coreclr/crossgen-corelib.proj`, it said **Build succeeded.** in the end, sooo... ok?

I'll run some tests and check the performance.

**Comment by jasper-d** [comment]
To get rid of the setlocale error, you can do something like this (this works for Debian and probably Ubuntu too):
```
apt install locales -y --no-install-recommends
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen
```

Since you installed WSL anyway, I recommend building CLR inside a container because that gives you a clean build environment. Here is how I produce checked JIT builds:

```
FROM debian:bullseye-slim

RUN apt-get update &&  apt install -y cmake llvm lld clang build-essential \
python-is-python3 curl git lldb libicu-dev liblttng-ust-dev ca-certificates \
libssl-dev libnuma-dev libkrb5-dev zlib1g-dev ninja-build --no-install-recommends

RUN update-ca-certificates

RUN apt install locales -y --no-install-recommends
RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
RUN locale-gen

WORKDIR /src
RUN git clone --depth 100 --branch main https://github.com/dotnet/runtime . 
RUN git rev-parse HEAD
RUN ./build.sh clr.jit -rc Checked
RUN find ./artifacts -name libclrjit.so
```
You can then get the build artifacts using `docker cp` or `docker save`.

**Comment by jkotas** [comment]
> Afaik cross-compiling the native parts for Linux on Windows isn't supported.

Correct.

This is documented in https://github.com/dotnet/runtime/blob/main/docs/workflow/building/coreclr/cross-building.md "Only the combinations explained here are possible/supported.".
