### ISSUE TITLE
generation of RID graph no longer works

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#82125]
I was trying add new RID (ubuntu 23.04). I added entry to `runtimeGroups.props` in `Microsoft.NETCore.Platforms` and run `dotnet.sh pack  /p:UpdateRuntimeFiles=true` as usually. 
But no updates were made to `runtime.json` and `runtime.compatibility.json`
Release/6.0 branch still works but I experienced same issue with release/7.0.

**Comment by carlossanlop** [comment]
6.0 PR with changes that were successfully created with the generator: https://github.com/dotnet/runtime/pull/82120
7.0 PR with changes that couldn't get created with the generator: https://github.com/dotnet/runtime/pull/82123

**Comment by tmds** [comment]
With .NET 7, source-build for unknown distros manages to successfully update the graph and then use that graph in the build. The task for that (`GenerateRuntimeJson`) is similar to the one used here (`UpdateRuntimeJson`).

https://github.com/dotnet/runtime/blob/53bb518ea482a5960577b151c11cc1297e5dea6d/src/libraries/Microsoft.NETCore.Platforms/src/Microsoft.NETCore.Platforms.csproj#L60-L79

**Comment by ViktorHofer** [comment]
Here's yet another PR that successfully uses the infrastructure in main: https://github.com/dotnet/runtime/pull/82185. @wfurt please give it another try.

**Comment by wfurt** [comment]
What do you want me to try? Just run the pack command as documentation suggest?
https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.NETCore.Platforms/readme.md

**Comment by ViktorHofer** [comment]
I was looking for any console indication of why it doesn't work anymore but disregard as I just found the culprit: https://github.com/dotnet/runtime/pull/76068

**Comment by wfurt** [comment]
thanks for looking into it @ViktorHofer

**Comment by tmds** [comment]
The change was also backported to 6.0 with some differences: https://github.com/dotnet/runtime/pull/77510.
