### ISSUE TITLE
[NativeAOT] Update documentation when building native libraries with a custom native host 

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/runtime#82156]
[The documentation for building native libraries with NativeAOT](https://github.com/dotnet/samples/blob/main/core/nativeaot/NativeLibrary/README.md) should be updated with the description of recently added feature: compiling a managed program as a static library linked with a custom native host application: https://github.com/dotnet/runtime/pull/81873

/cc: @AustinWise @dotnet/ilc-contrib

**Comment by AustinWise** [comment]
The short version of how to build a static library that also includes the executable entry point.

Add this property to your project:

```xml
<PropertyGroup>
  <IlcArg>-splitinit</IlcArg>
</PropertyGroup>
```

This will generate a symbol for the managed main function. You can call it by writing the following C declaration:

```c
#if defined(_WIN32)
extern "C" int __managed__Main(int argc, wchar_t* argv[]);
#else
extern "C" int __managed__Main(int argc, char* argv[]);
#endif
```

Otherwise follow the instructions for linking the static libraries.

**Comment by MichalStrehovsky** [comment]
I wonder if we really need to document/support this outside Xamarin. The static library building experience is subpar and not something we suggest in general (need to worry about versions of C/C++ compiler and libc the runtime was built against and versions the user code is using). Dynamic libraries provide a better experience and most people should go with that.

Static libraries with custom main are a niche of a niche and it might be better to not overcomplicate the docs with that.

**Comment by agocke** [comment]
This seems like the kind of thing that could go in a runtime-repo doc file, but we wouldn't want to put in public documentation.

**Comment by ivanpovazan** [comment]
> I wonder if we really need to document/support this outside Xamarin. The static library building experience is subpar and not something we suggest in general (need to worry about versions of C/C++ compiler and libc the runtime was built against and versions the user code is using). Dynamic libraries provide a better experience and most people should go with that.
> 
> Static libraries with custom main are a niche of a niche and it might be better to not overcomplicate the docs with that.

I understand, I just wanted to avoid having this feature left undocumented. 
Especially because it is the integration point for both Xamarin and [AppleAppBuilder](https://github.com/dotnet/runtime/tree/main/src/tasks/AppleAppBuilder) and would be useful for developers working on the integration to have it documented somewhere.

Would https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/interop.md maybe be a better location or you would like to keep it private (internal) completely?

**Comment by AustinWise** [comment]
I made a sample for the `CustomNativeMain` property here:

https://github.com/AustinWise/SplitInit

I'll see about putting something in the [official interop docs](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/interop).

It looks like [Xamarin is using the `CustomNativeMain` property](https://github.com/xamarin/xamarin-macios/blob/net8.0/dotnet/targets/Xamarin.Shared.Sdk.props#L135-L136), so there is probably no need to document the `-splitinit` flag to ILC.exe.

**Comment by ivanpovazan** [comment]
Thank you for the provided sample.
I wonder if the sample and/or the description explaining the `CustomNativeMain` property could be added to: https://github.com/dotnet/samples/tree/main/core/nativeaot instead.

Regarding the public documentation, I am not sure what should be the right solution.
It is true that we integrated Xamarin builds with NativeAOT, as we knew (or discovered) what flags need to be passed to achieve this, and there is an open issue on simplifying that process: https://github.com/dotnet/runtime/issues/87187
Nevertheless, I think it would be useful to have (somewhere) a documentation explaining the integration process. Maybe the right place for such documentation is not dotnet/runtime, but rather Xamarin (and/or other app models) I am not sure. 

@MichalStrehovsky @jkotas what do you think?

**Comment by jkotas** [comment]
> I wonder if the sample and/or the description explaining the CustomNativeMain property could be added to: https://github.com/dotnet/samples/tree/main/core/nativeaot instead.

I agree with what Michal said in https://github.com/dotnet/runtime/issues/82156#issuecomment-1447424280 . I do not think it is worth it to complicate the mainstream documentation or samples with `CustomNativeMain` explanation.

> I think it would be useful to have (somewhere) a documentation explaining the integration process. Maybe the right place for such documentation is not dotnet/runtime, but rather Xamarin (and/or other app models) I am not sure.

Having document in Xamarin that explains how all parts are put together (including the static registrar, etc.) sounds reasonable to me.

**Comment by ivanpovazan** [comment]
> Having document in Xamarin that explains how all parts are put together (including the static registrar, etc.) sounds reasonable to me.

I am closing this issue in favour of: https://github.com/xamarin/xamarin-macios/issues/18585 which should track providing a public documentation regarding Xamarin+NativeAOT support. Please feel free to add more context there, if necessary, and review the changes once we get a PR for it.
