### ISSUE TITLE
build v7.0.3 tags hit error

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#82151]
we build mono flavor use below comand:
> build.cmd -pack -runtimeFlavor mono /p:Deterministic=true -os windows -arch x64 -c Release

hit the error:

```
dotnet\runtime\src\libraries\externals.csproj : error NU1603: externals depends on Microsoft.DiaSymReader.Native (>= 16.11.23-beta1.23063.1) but Microsoft.DiaSymReader.Native 16.11.23-beta1.23063.1 was not found. An approximate best match of Microsoft.DiaSymReader.Native 17.0.0-beta1.21524.1 was resolved. [F:\mydir\dotnet\runtime\Build.proj]

```

maybe it introduced by this pr https://github.com/dotnet/runtime/commit/8b3d9625d9967c5ba82a19e8c677ff6ee2dd8f7f

@mmitche @hoyosjs can you help me?

could not find the 16.11.23-beta1.23063.1 version on https://www.nuget.org/packages/Microsoft.DiaSymReader.Native/#versions-body-tab

**Comment by mmitche** [comment]
@hoyosjs I think we missed publishing a package.

**Comment by hoyosjs** [comment]
This should be fixed now.
