### ISSUE TITLE
[API Proposal]: File.ReadLines增加支持读写的打开方式，很多时候在打开的同时还有应用在写入，避免占用报错

### ISSUE THREAD

**Issue by liuzhaolei107** [dotnet/runtime#82152]
### Background and motivation

File.ReadLines增加支持读写的打开方式，很多时候在打开的同时还有应用在写入，避免占用报错

### API Proposal

```csharp
namespace System.Collections.Generic;

public class MyFancyCollection<T> : IEnumerable<T>
{
    public void Fancy(T item);
}
```

### API Usage

```csharp
// Fancy the value
var c = new MyFancyCollection<int>();
c.Fancy(42);

// Getting the values out
foreach (var v in c)
    Console.WriteLine(v);
```

**Comment by liuzhaolei107** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by stephentoub** [comment]
Running the title through a translator:
"[API Proposal]: File.ReadLines adds an opening method that supports reading and writing, and in many cases applications are writing at the same time as opening to avoid occupancy errors"
and the contents:
"File.ReadLinesAdd the opening mode that supports reading and writing, and in many cases, applications are writing at the same time as opening to avoid occupancy errors"

I'm not clear on what you're proposing.  Are you asking for an overload of File.ReadLines that takes additional parameters?

**Comment by liuzhaolei107** [comment]
希望在net6.0    System.IO.File下增加ReadLinesAsync异步方法

**Comment by dakersnar** [comment]
FYI for other collaborators, I just learned you can right click and hit "Translate to English" to automatically translate the entire page, at least on Edge. Neat 😄.

Can you clarify what exactly you are proposing? I recommend updating/editing the "API Proposal" and "API Usage" sections of the original post. It looks like they have not been updated from the template.

**Comment by Lightczx** [comment]
@stephentoub @dakersnar I beleive he is saying to Add some overload looks like
```c#
public static class File
{
    public static IEnumerable<string> ReadLines(string path, FileMode mode, FileAccess access, FileShare share);
    public static IEnumerable<string> ReadLines(string path, FileMode mode, FileAccess access, FileShare share, Encoding encoding)
}
```
Which will take `FileMode mode, FileAccess access, FileShare share` as parameters
While I think we can always use `FileStream` to achieve this.

**Comment by liuzhaolei107** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
