### ISSUE TITLE
Customize SNI separately in HttpClient

### ISSUE THREAD

**Issue by DarkCWK** [dotnet/runtime#82165]
Some places block some websites by detecting SNI
which can be bypassed by not sending SNI information.
But currently there doesn't seem to be a way to do this

**Comment by rzikm** [comment]
It should be possible, but it will take some work. You need to use [SocketsHttpHandler.ConnectCallback](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.connectcallback?view=net-7.0&viewFallbackFrom=netcore-2.2) to customize how connections are established. Inside the callback, construct the `SslStream` instance and authenticate with any `SslClientAuthenticationOptions` as you see fit and return it.

Note that ability to return `SslStream` from the callback was added in 7.0 only (https://github.com/dotnet/runtime/pull/63851).

**Comment by MihaZupan** [comment]
Related discussion in the YARP repo: #2036

There are a few variations on this issue that came up:
1. Not sending SNI at all
    - As Radek mentioned, it's not possible to avoid sending it completely from HttpClient's APIs directly, you have to go through the `ConnectCallback` and create the `SslStream` yourself.
2. Changing the value of SNI
    - The value HttpClient uses is the host specified in the Host header, otherwise the host from the request's Uri.
3. Send an SNI that's different than the host header
    - Because we use the value from the host header, it's not possible to send an SNI that's different without going through `ConnectCallback`.

**Comment by wfurt** [comment]
Since this is not common scenario and workarounds exist, I would assume this can be closed, right @DarkCWK?

**Comment by DarkCWK** [comment]
> Since this is not common scenario and workarounds exist, I would assume this can be closed, right @DarkCWK?

Yes, This has indeed solved the problem

> It should be possible, but it will take some work. You need to use [SocketsHttpHandler.ConnectCallback](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.connectcallback?view=net-7.0&viewFallbackFrom=netcore-2.2) to customize how connections are established. Inside the callback, construct the `SslStream` instance and authenticate with any `SslClientAuthenticationOptions` as you see fit and return it.
> 
> Note that ability to return `SslStream` from the callback was added in 7.0 only (#63851).

But I wonder if there is a solution for .net6.0?

**Comment by wfurt** [comment]
not easily. You _could_ lie to `HttpClient` and ask for `Http` instead of `Https` to prevent TLS handshake. And then you return negotiated `SslStream`. Since HttpClient has no clue it would not conflict with internal processing (solved with #63851)
I would need to be _VERY_ careful as you play tricks with internals.

**Comment by DarkCWK** [comment]
Thanks, maybe it's time to migrate to .net7.0.
