### ISSUE TITLE
HttpProtocolException is not reported properly on initial HTTP/2 settings handshake failure

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#82168]
There is an overlook in #71345. When the server doesn't initiate the connection with a proper SETTINGS preface, eg. responding by GOAWAY instead, the `InnerException` of the `HttpRequestException` being thrown must be a `ProtocolException` according to #70684.

Instead, we embed `ProtocolException` into further `IOException`-s  2 levels down in [`ProcessIncomingFramesAsync()`](https://github.com/dotnet/runtime/blob/0202b242169f8d5955e0411dc5e4f42a5d016c1b/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L503).

Repro:

```C#
[ConditionalFact(nameof(SupportsAlpn))]
public async Task Test()
{
    using Http2LoopbackServer server = Http2LoopbackServer.CreateServer();
    using HttpClient client = CreateHttpClient();
            
    Task<HttpResponseMessage> sendTask = client.GetAsync(server.Address);

    Http2LoopbackConnection connection = await server.AcceptConnectionAsync();
    await connection.ReadSettingsAsync();
    await connection.SendGoAway(0, ProtocolErrors.INTERNAL_ERROR);

    var ex = await Assert.ThrowsAsync<HttpRequestException>(() => sendTask);
    Assert.IsType<HttpProtocolException>(ex.InnerException); // Fails
}
```

**Comment by CarnaViire** [comment]
Triage: this looks like something straightforward to fix. We should fix it in 8.0.
