### ISSUE TITLE
JIT: RunOnGPUAttribute

### ISSUE THREAD

**Issue by Toxantron** [dotnet/runtime#8220]
This is just an idea and I hope it is not a duplicate, but as far as I understand the SIMD optimizations in `System.Numerics` only run on the CPU and are limited to predefined operations like `Add`, `Multiply` and some other common vector and matrix operations. dotnet/runtime#6556 proposes decoupling the CPU optimized APIs from the predefined methods, but still only considers the CPU as a target.

I thought of something like the example below. No the code does not make any sense, it could probably be rewritten to make use of `System.Numerics` and a lot of steps could be merged to improve big O behavior. I only chose it as a random example that probably does not exist in the `System.Numerics` API.

````cs
[RunOnGPU]
private static uint[] AwesomeFoo(uint a, uint[] bs, uint[] cs)
{
    var buffer = new uint[bs.Length, cs.Length + 1];
    Parallel.For(0, bs.Length, i => 
    {
         buffer[i, 0] = a * bs[i];
         Parallel.For(0, cs.Length, j => 
         {
             buffer[i,j] = bs[i] * cs[cs.Length - 1 - j] + a;
         });
    });
    var reduced = new uint[bs.Length];
    Parallel.For(0, bs.Length, i =>
    {
        var value = buffer[i];
        for (var j=0; j <= cs.Length; j++)
        {
             var index = (i + j) % bs.Length;
             value += buffer[index, j] * (1 + (-1 * j % 2));
        }
    });
    return reduced;
}
````

I am no expert in GPU computing nor the internals of the JIT, but as far as I understand it, we could offer specialized versions of the CoreCLR that make use of either NVIDIA, AMD or Adreno GPUs. When the JIT finds such a method it would check some requirements like datatypes, used APIs, etc. and decide wether it can be translated into GPU code or not. Using CUDA as an example it would than reserve GPU memory `cudaMalloc`, for the arguments, local variables and return values, use `cudaMemcpy` to copy the data and then translate the anonymous methods of `Parallel.For(..)` into cuda kernels, translate the code and after execution is complete copy back the result and release the reserved memory `cudaFree`. As on optimization the CoreCLR could reserve a dynamic amount of GPU memory similar to the way the GC does it with the normal RAM, but at least for CUDA I think there already is some sort of pooling.

Reasons to do this:
1. It would be an awesome feature.
2. It would enable a range of applications from automation and banking, to AI and gaming to develop entirly in C# and still benefit from latest gen hardware.
3. Using this internally could improve performance of current APIs by moving the code into GPU optimized private methods without any breaking changes.

Reasons not to do this:
1. This is probably insanely complicated.
2. Users need to pick the right CoreCLR for the GPU or detect and self-compile to get the full benefits.

category:proposal
theme:big-bets
skill-level:expert
cost:extra-large

**Comment by teo-tsirpanis** [comment]
Is that feature desirable or even _possible_ to implement at the runtime level? GPU programming is a quite opinionated field with various APIs like CUDA, OpenCL and DirectCompute. We would also need analyzers that enforce what is allowed and what is not in a method with `[RunOnGPU]` and lots of other stuff I can't think of.

I think that community projects powered by source generators such as @Sergio0694's [ComputeSharp](https://github.com/Sergio0694/ComputeSharp) are a much better way to approach this problem.

**Comment by jkotas** [comment]
Closing. Not actionable in this repo.
