### ISSUE TITLE
Net 7 Kestrel windows service hangs after a period of time

### ISSUE THREAD

**Issue by sccrgoalie1** [dotnet/runtime#82207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We just update our projects to .NET 7 from .NET 5 and are experiencing hangs where Kestrel quits responding.  It works for a day or so and then the windows service needs to be restarted.  This was not an issue on .NET5.  I gathered a memory dump to see if I can figure out what is causing it to hang.  Here are some screenshots.  This was gathered using ProcDump.

This API is installed at many unique locations and several have reported the same issue that they need to restart the service daily.  For some locations, we use Azure relay.  So far, the locations that go through the relay have not had any issues.

![image](https://user-images.githubusercontent.com/2366790/216437164-f9a61114-5598-466e-b063-f9d2aebc87f6.png)

![image](https://user-images.githubusercontent.com/2366790/216437211-fa7a841b-7659-47b5-9659-89370fde674f.png)

### Expected Behavior

The API should respond while running

### Steps To Reproduce

Let our project run for a day

### .NET Version

7.0.100

**Comment by kouvel** [comment]
Another thing to look into perhaps is why the IO completion with `ERROR_OPERATION_ABORTED` is not causing some kind of error to occur.
