### ISSUE TITLE
Why `System.Text.Json.JsonSerializer` serialize the wrapper properties by default?

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/runtime#82237]
Migrating from `Newtonsoft.Json` to `System.Text.Json` was such a pain, a whole bunch of inconsistent behaviour.

Such like this:

```cs
public class A {
    public int Property { get; set; }
    public int Wrapper { get => Property; set => Property = value; }
}
```
will be sterilized as:

```json
{
    "Property": 0,
	"Wrapper": 0
}
```

**Comment by eiriktsarpalis** [comment]
What is the behavior you're expecting in this case? From an IL perspective there is nothing distinguishing auto-properties from properties you implement explicitly. FWIW Json.NET also serializes both properties:
```C#
Console.WriteLine(JsonConvert.SerializeObject(new A())); // {"Property":0,"Wrapper":0}

public class A
{
    public int Property { get; set; }
    public int Wrapper { get => Property; set => Property = value; }
}
```
So I suspect you might have missed a `JsonIgnoreAttribute`.

**Comment by GF-Huang** [comment]
Sorry my mistake.
