### ISSUE TITLE
NativeAOT EventPipe library needs to work correctly when EventSource support is enabled

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#82231]
In `NativeAOT`, `EventPipe` library is not included by default in applications due to size considerations. This means that when applications enable [EventSource](https://github.com/dotnet/runtime/blob/main/docs/workflow/trimming/feature-switches.md) support, developers have a choice to include this library as shown in the table [here](https://github.com/dotnet/runtime/pull/80382#issue-1526169655). .NET applications do not have this option since EventPipe library is always included in .NET. 

There could be cases where developer might just want to get in-proc events and do not need to enable `EventPipe` library since they do not need these events sent out-proc (to listening clients like dotnet-trace) or want to keep their application size small while getting some event data. Currently in `NativeAOT`, the only option for `EventSource` support is also to include `EventPipe` library. This is due to existing code that is shared with `CoreCLR` do not distinguish between managed/native separation when EventSource support is enabled and calls the `EventPipe` [library](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs#L1561).

We need to do the following in NativeAOT

1. Pick the right default for `EventPipe` library support when `EventSource` support is enabled.
2. Fix the existing issue when `EventSource` is enabled and `EventPipe` is disabled. The work should also include the current code we have that assumes EventPipe can be disabled when `EventSource` is enabled. For example, removing methods in [DisabledEventPipeInternal.cpp](https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/Runtime/disabledeventpipeinternal.cpp)

**Comment by LakshanF** [comment]
We are not planning to separate `EventPipe` library support between managed and native code.

**Comment by agocke** [comment]
Closed as completed.
