### ISSUE TITLE
Enable TFM filtering for runtime's source-build

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/runtime#82298]
Created based on https://github.com/dotnet/runtime/issues/81468#issuecomment-1421061563

Based on the linked comment / discussion in the issue, TFM filtering should be enabled for runtime's source-build once other repositories have the filtering enabled and working as not to cause issue downstream.

The exact approach should be discussed once the work on the issue can start. At the moment of writing, there are two approaches:
  - utilize the existing `runtime`'s tooling for filtering out TFMs
  - utilize the newly introduced logic to Arcade infra

The source-build team would prefer the second approach due to other repos also utilizing it instead of introducing a special case for runtime that potentially could increase maintenance work down the line.

**Comment by ViktorHofer** [comment]
This is already implemented.
