### ISSUE TITLE
Strange boxing deopt

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/runtime#82291]
### Description

Given the following code, only the first function optimizes acceptably here. I'm not quite sure why it can't kick in for the other cases?

### Reproduction Steps

```cs
public class C {
    
    [SharpLab.Runtime.JitGeneric(typeof(int))]
    public bool GetValueOrNull<T>()
    {
        if (default(T) != null)
         return true;
         
       return false;
    }    
    
    [SharpLab.Runtime.JitGeneric(typeof(int))]
    public bool GetValueOrNullSlow<T>()
    {
        if (default(T) != null)
         return false;
         
       return false;
    }    

    
    [SharpLab.Runtime.JitGeneric(typeof(int))]
    public void GetValueOrNullSlow2<T>()
    {
        if (default(T) != null)
         return;
         
       return;
    }    
}
```

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4a9JuQCsG6poDMTUgyEMA3jQY2G12wG1ZAC2xQxAGWzB23PgJYAKV4MAHEYLhllAAoMAE8xGAgAM2jeHgBKDIBdextiY2AICEkGcIwANWxJDhgAeSgAOQ5JSQAeABUAPmiMvMt+2wZeZIZogBMYZOwWjGiOjIYAQgBeBi4WyT7qId3iAHYGDCha/V2hwfzD6clcGDPbAF8Lndt+p1d3Lx9OHn5BYJhCJRMCxBJJVLpDBZXKvfKFYqlcpVGr1JqbWSSCAAd06PW2QyscN2IzGk2ms3mi1W602BPOVwYNzuDwZlyY12qLP6zzeBmJ7xcbk83l8fwCgPCkSgMXiiRSaUyOX6BSYKDKMEq1VqDWarUxONIeN6/SJDOGowmUxmkjmC2Waw2rXpDIOrPO7LdPJejyAA

### Expected behavior

GetValueOrNullSlow and GetValueOrNullSlow2 are both optimized like GetValueOrNull

### Actual behavior

They don't

**Comment by benaadams** [comment]
Aside as workaround; replacing `default(T) != null` with `typeof(T).IsValueType` is optimised in all three cases

**Comment by vonzshik** [comment]
@benaadams that would be incorrect for nullable types (like `int?`).

**Comment by SingleAccretion** [comment]
The reason is that Roslyn (helpfully) optimizes the method itself:
```
IL_0000: ldloca.s 0
IL_0002: initobj !!T
IL_0008: ldloc.0
IL_0009: box !!T
IL_000e: pop
IL_000f: ldc.i4.0
IL_0010: ret
```
The Jit then doesn't drop the unused box.

The fix would be to simplify `BOX`es when importing `pop`s; it would also be good to share that code more generally for "importing unused values" (this handling exists for unused inlinee parameters, for example).
