### ISSUE TITLE
SafeHandle marshalling broken with Mono

### ISSUE THREAD

**Issue by uweigand** [dotnet/runtime#82308]
As of https://github.com/dotnet/runtime/pull/80715, many `System.Net.Sockets.Tests` test fail with the error:
```
System.Exception : Failed to create the 'shadow' (port blocker) socket in 16 attempts.
```

Looking at the behavior with strace shows the error is caused by failed attempts to bind to file descriptor 0 (which is of course not a socket):
```
[pid 774258] bind(0, {sa_family=AF_INET6, sin6_port=htons(44087), sin6_flowinfo=htonl(0), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_scope_id=0}, 28) = -1 ENOTSOCK (Socket operation on non-socket)
```

Investigating this closer shows that the bind call happens via a P/Invoke in the new test infrastructure:
https://github.com/dotnet/runtime/blob/65f5ad06c38fbd0a73583a46889419068534446a/src/libraries/Common/tests/System/Net/Sockets/SocketTestExtensions.cs#L205-L206

This seems to trigger marshalling code in Mono that accesses the `IntPtr` wrapped by the `SafeHandle`:
https://github.com/dotnet/runtime/blob/65f5ad06c38fbd0a73583a46889419068534446a/src/mono/mono/component/marshal-ilgen.c#L1919-L1923
using the data structure here:
https://github.com/dotnet/runtime/blob/65f5ad06c38fbd0a73583a46889419068534446a/src/mono/mono/metadata/class-internals.h#L670-L678

However, as of https://github.com/dotnet/runtime/pull/71991 the definition of the `SafeHandle` type on the managed side is:
https://github.com/dotnet/runtime/blob/65f5ad06c38fbd0a73583a46889419068534446a/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/SafeHandle.cs#L24-L35
Note when the library is built for the Debug configuration, the layout no longer matches - in the place Mono expects the `handle` field, we now have the `_ctorStackTrace` field.   As this is usually null, we get 0 as file descriptor ...

@stephentoub I see you updated the matching CoreCLR definition with https://github.com/dotnet/runtime/pull/71991, but not the Mono definition.   I guess this should be done there as well - however I'm not clear how to do this only for the Debug version of the library, this is something the Mono runtime doesn't currently appear to be doing ...

Also, I was quite confused why this problem only shows up in this one test, and not for all the "normal" places in the library where `SafeHandles` are marshalled to native code.  I now see this is using a different mechanism:
https://github.com/dotnet/runtime/blob/65f5ad06c38fbd0a73583a46889419068534446a/src/libraries/Common/src/Interop/Unix/System.Native/Interop.Bind.cs#L12-L13
which doesn't trigger the Mono marshalling code, but generates IL that uses calls to `System.Runtime.InteropServices.SafeHandle:DangerousGetHandle` instead of accessing the handle at a hard-coded offset.

CC @antonfirsov @vargaz @omajid @tmds

**Comment by stephentoub** [comment]
> Note when the library is built for the Debug configuration, the layout no longer matches - in the place Mono expects the handle field, we now have the _ctorStackTrace field. As this is usually null, we get 0 as file descriptor ...
@stephentoub I see you updated the matching CoreCLR definition with https://github.com/dotnet/runtime/pull/71991, but not the Mono definition. I guess this should be done there as well

That's definitely a miss on my part.  Though I'm also surprised nothing has failed until now, so maybe there's more going on.

Simplest fix is to just change the ifdef in SafeHandle.cs to make that additional debugging logic exclusive to coreclr.

**Comment by tmds** [comment]
We have a CI job that runs tests with `--runtimeconfiguration Release --librariesConfiguration Debug /p:PrimaryRuntimeFlavor=Mono` on `x64` where all these tests pass.

The problem doesn't sound architecture specific. I don't know why it doesn't show this issue. :thinking:

**Comment by stephentoub** [comment]
> We have a CI job that runs tests with --runtimeconfiguration Release

The additional code I added to SafeHandle is under DEBUG and is in corelib; it wouldn't affect a Release runtime.

**Comment by tmds** [comment]
Ah, I wrongly assumed `corelib` code was under `--librariesConfiguration Debug`.
