### ISSUE TITLE
Unnecessary boxing of value types in System.Text.Json.Nodes.JsonValue`1

### ISSUE THREAD

**Issue by tomupson** [dotnet/runtime#82349]
While looking into System.Text.Json.Nodes for a personal project, I happened to notice a number of unnecessary boxings when converting a JsonValue's held value to a generic T, where T is a value type, when the value is a JsonElement.

https://github.com/dotnet/runtime/blob/3f228d827d82d71b0c29e2c1533eca01db270cba/src/libraries/System.Text.Json/src/System/Text/Json/Nodes/JsonValueOfT.cs#L83-L136

These can be eliminated by making use of `Unsafe.As<TFrom, TTo>(ref TFrom source)` which will reinterpret the pointer as a T pointer, and is safe given the code already validates that the types are compatible

**Comment by stephentoub** [comment]
> unnecessary boxings

Note that this is a standard pattern recognized by the JIT.  It will elide the boxing in optimized code.

**Comment by tomupson** [comment]
> > unnecessary boxings
> 
> Note that this is a standard pattern recognized by the JIT. It will elide the boxing in optimized code.

Thanks Stephen, I was not aware. Is it worth "fixing" anyway or shall I close the issue?

**Comment by jkotas** [comment]
> Is it worth "fixing" anyway or shall I close the issue?

If both safe and unsafe variants result into same optimized code, we always prefer the safe variant. This is not worth "fixing".
