### ISSUE TITLE
LCIDToLocaleName may return wrong language tag for transient language identifiers

### ISSUE THREAD

**Issue by DJm00n** [dotnet/runtime#82367]
It turns out that the LCIDToLocaleName API, which is used inside CultureInfo, can return incorrect names for [transient language identifiers](https://learn.microsoft.com/globalization/locale/locale-names#the-deprecation-of-lcids):
- `0x2000` - LOCALE_TRANSIENT_KEYBOARD1
- `0x2400` - LOCALE_TRANSIENT_KEYBOARD2
- `0x2800` - LOCALE_TRANSIENT_KEYBOARD3
- `0x2C00` - LOCALE_TRANSIENT_KEYBOARD4

For example, it returns "nqo-GN" and "jv-Java-ID" instead of the language tags "nqo" and "jv-Java" (as seen in the Get-WinUserLanguageList PowerShell cmdlet). In this case, both languages mapped to the same transient language identifier.

Consider add parent culture check into [CultureData GetCultureData(int culture, bool bUseUserOverride)](https://github.com/dotnet/runtime/blob/3689fbec921418e496962dc0ee252bdc9eafa3de/src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs#L876-L888) to look at the parent language if it has the same language identifier as we requested and use parent in such cases:
```cs
if (IsCustomCultureId(retVal.LCID) && PInvoke.LocaleNameToLCID(retVal.ParentName, 0) == culture)
{
    retVal = GetCultureData(culture.ParentName, bUseUserOverride);
}
```

Found this but when testing https://github.com/dotnet/winforms/pull/8573

**Comment by tarekgh** [comment]
We are not investing in supporting LCID's anymore. It is obsolete and we are encouraging all users to move away from using LCID's. This is the same direction Windows is doing too.
