### ISSUE TITLE
Run low level EventPipe and container type native tests on CI.

### ISSUE THREAD

**Issue by lateralusX** [dotnet/runtime#82396]
https://github.com/dotnet/runtime/pull/78852 adds a set of new native container types, primarily used by EventPipe. EventPipe includes a set of low level native tests currently executed using eglibs test runner. The new native container types piggy backs on this and adds its test suites into the same native test runner. Currently these tests are only run local and only on Mono.

This issue is filed so we can decide how we should write low level native tests like this and how they can be run on CI for all runtimes using tested libraries (currently EventPipe and Containers). Current tests uses eglibs tests runner, so if we don't need more support than what it implements, we should move that test runner into src/native and use it for low level native tests like this. We also need to decide how to run this on CI, since tests produce a native binary that can be run and that reports success/failure we should probably add support that just runs these test binaries and make sure the output gets included on CI test reports.

**Comment by tommcdon** [comment]
After reviewing this issue, we have decided that we are unable to prioritize it.  Closing the issue for now until we discover that adding the low-level unit tests would be useful for catching regressions.
