### ISSUE TITLE
Missing version tag and can not backtrack

### ISSUE THREAD

**Issue by liesauer** [dotnet/runtime#824]
let's say i need the corehost `v2.1.0` or any `vx.y.z`'s source codes, i cannot back to any matching commit cause i don't have any related commit information.

**Comment by danmosemsft** [comment]
Hi @liesauer . There are git tags for each release - if not here, then in the repos this code recently came from: dotnet/core-setup, dotnet/corefx, dotnet/coreclr. 

Does that help?

**Comment by liesauer** [comment]
if a new release comes out, where will the new tag be in? here or original repo?2019年12月13日 12:02，Dan Moseley <notifications@github.com>写道：Hi @liesauer . There are git tags for each release - if not here, then in the repos this code recently came from: dotnet/core-setup, dotnet/corefx, dotnet/coreclr.
Does that help?

**Comment by danmosemsft** [comment]
@liesauer we will service 3.x and earlier from the old repos. So tags will go there. Eventually this repo will have tags like 5.0preview1 and onwards.

**Comment by danmosemsft** [comment]
I think this is answered.
