### ISSUE TITLE
Dynamically loaded DLL is missing symbols on Android and iOS

### ISSUE THREAD

**Issue by MaxwellDAssistek** [dotnet/runtime#82417]
### Description

When trying to dynamically load a DLL during runtime that has embedded symbols, it seems like symbols are not fully available. This only happens on Android and iOS. I have verified this does not happen on windows. This also happens when there is instead a separate pdb file next to the dll, rather than using embedded symbols.

When running with a debugger I am able to hit a breakpoint within that DLL, but Visual Studio ends up breaking on the last code before calling into the DLL. Looking at the call stack, while sitting on this breakpoint, it does have the proper code file and line number, but the Modules list claims that No symbols are loaded for that DLL.

![image](https://user-images.githubusercontent.com/61429558/220236349-6d32083f-6a67-452a-b144-5e45da8c520e.png)

I have also tracked this as a visual studio bug, but I am leaning towards this being a .NET runtime issue because of that Symbols not loaded message.
https://developercommunity.visualstudio.com/t/Hitting-breakpoint-in-dynamically-loaded/10269906

### Reproduction Steps

Start from this git repo and follow the setup instructions in the README.
https://github.com/MaxwellDAssistek/DynamicallyLoadedPagesRepro/tree/72feb21bfa7546b38cf1745ab51092b857718497

How it works:

1. Launch the app on android (or iOS)
2. Click the button called “Click me”
3. Observe that the new page is loaded from the dynamically loaded DLL.

To reproduce the issue:

1. Put a breakpoint in ModuleMain.cs in the MyModule project.
2. Launch the app on android (or iOS)
3. Click the button called “Click me”

### Expected behavior

It should highlight the location where the breakpoint was actually put and information about local variables should be available.

### Actual behavior

Observe that the breakpoint is hit, but the code that is highlighted is the line initMethod.Invoke(moduleInstance, null); in MainPage.xaml.cs rather than where the breakpoint actually is. Also notice that if you right click on the latest entry in the Call Stack and select Go To Module the MyModule.dll says that it has No symbols loaded.

### Configuration

Using latest .NET 7.
Reproduced the issue on Android (emulator and device) and iOS (tested on simulator only)
Does NOT happen on Windows.

**Comment by steveisok** [comment]
@thaystg is this something that should work as is?

**Comment by thaystg** [comment]
No, but I'm working on it, will have a PR soon.

**Comment by MaxwellDAssistek** [comment]
Will this fix be available in the next preview build?
