### ISSUE TITLE
enum_packedSlotLayout_NameHashMask is unused

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#82425]
I noticed that `MemberLoader::FindMethod` shows up in traces, namely [strcmp](https://github.com/dotnet/runtime/blob/463954dbc728470fb21a097188fc3dae91f6cbe4/src/coreclr/vm/memberload.cpp#L1135) inside it 

![image](https://user-images.githubusercontent.com/523221/220316519-8fee6dd7-1ac3-4d1a-9b27-c52ead6cc5fc.png)

It seems that logic in `FindMethod` implies MethodDesc might store a hash for method name inside `m_wSlotNumber` for faster name comparison but aparently it's never used since `enum_packedSlotLayout_NameHashMask` is never set. see [MethodDesc::MightHaveName](https://github.com/dotnet/runtime/blob/463954dbc728470fb21a097188fc3dae91f6cbe4/src/coreclr/vm/method.cpp#L387-L409)

Same for fields' names.

PS: I'm profiling first 2 seconds of Paint.NET start

cc @jkotas

**Comment by jkotas** [comment]
cc @AaronRobinsonMSFT 

The hashcode fast-path was an optimization done by fragile NGen that precomputed and stored the hashcodes at build-time.

It is not obvious whether this optimization worth it when the hashcodes are computed at runtime: We would spend time computing the hashcodes, hoping that these lookups happen often enough to offset the cost.
