### ISSUE TITLE
Support Half-precision floating-point numbers

### ISSUE THREAD

**Issue by vermorel** [dotnet/runtime#8243]
The CLR would greatly benefit from adding support the half-precision floating-point numbers.

The [Half-precision floating-point numbers](https://en.wikipedia.org/wiki/Half-precision_floating-point_format) are already extensively used in machine learning and image processing applications. Even if it the CLR is only meant for interacting with a native machine learning framework, the lack of a `System.Half` number means that those needs to be emulated, which is very inefficient; especially considering that both ARM and x64 have built-in support for half-precision floating point numbers.

Emulation can be done ala [C# Half](https://sourceforge.net/projects/csharp-half/) for example, but my own experiments hinted about 10x slower compared to native performance. Then, I wasn't even using dedicated SIMD, which are likely to add another 10x performance factor (bringing to 100x) between "emulated" and "native" on high-end processors.

**Comment by danmosemsft** [comment]
tracked by https://github.com/dotnet/runtime/issues/936
