### ISSUE TITLE
Add source gen support for `unspeakable types`

### ISSUE THREAD

**Issue by brunolins16** [dotnet/runtime#82457]
### Description

`Minimal APIs` uses the runtime type to call the serializer in most of the scenarios, that means once I have a compiler generated type (`unspeakable type`) returning from my API, this type will be used for serialization. 

While it works correctly when the `reflection-based resolver` is turned on, I could not find a way to add this compiler generated type to my source-generated `JsonSerializerContext`. Even if I try to specify the interface implemented by type, eg.: `IAsyncEnumerable` and still getting the following error:

`Metadata for type 'Program+<<<Main>$>g__Foo|0_5>d' was not provided by TypeInfoResolver of type 'MyContext'. If using source generation, ensure that all root types passed to the serializer have been indicated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically.`

### Reproduction Steps

```c#
var builder = WebApplication.CreateBuilder(args);
builder.Services.ConfigureHttpJsonOptions(options => options.SerializerOptions.TypeInfoResolver = MyContext.Default);
var app = builder.Build();

app.MapGet("/foo", Foo);
async IAsyncEnumerable<int> Foo()
{
    foreach (var i in Enumerable.Range(0, 10))
    {
        await Task.Delay(1000);
        yield return i;
    }
}

[JsonSerializable(typeof(IAsyncEnumerable<int>))]
internal partial class MyContext : JsonSerializerContext
{}
```

### Expected behavior

While is possible to have some additional logic on `ASP.NET Core` side, to check some sort of known types, the expected behavior is to have the metadata resolution be able to detect, as a fallback in the source generator context, if the requested type implements one of the interfaces registered in the context.

Eg.:

Current source-gen`ed context
```c#
    public override global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? GetTypeInfo(global::System.Type type)
    {
        if (type == typeof(global::System.Collections.Generic.IAsyncEnumerable<global::System.Int32>))
        {
            return this.IAsyncEnumerableInt32;
        }
        return null;
   }
```

Expected
```c#
    public override global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? GetTypeInfo(global::System.Type type)
    {
        if (type == typeof(global::System.Collections.Generic.IAsyncEnumerable<global::System.Int32>))
        {
            return this.IAsyncEnumerableInt32;
        }

        if (type.IsAssignableFrom(typeof(global::System.Collections.Generic.IAsyncEnumerable<global::System.Int32>)))
        {
            return this.IAsyncEnumerableInt32;
        }

        return null;
   }
```

### Actual behavior

```log
System.NotSupportedException: Metadata for type 'Program+<<<Main>$>g__Foo|0_5>d' was not provided by TypeInfoResolver of type 'MyContext'. If using source generation, ensure that all root types passed to the serializer have been indicated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically.
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_NoMetadataForType(Type type, IJsonTypeInfoResolver resolver)
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Boolean resolveIfMutable)
   at Microsoft.AspNetCore.Internal.ExecuteHandlerHelper.WriteJsonResponseAsync[T](HttpResponse response, T value, JsonSerializerOptions options, JsonTypeInfo`1 jsonTypeInfo)
   at lambda_method4(Closure, Object, HttpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by eiriktsarpalis** [comment]
For contrast, this is how the source generator produces metadata for IAsyncEnumerable's implementations that are visible to the source generator:
```C#
[JsonSerializable(typeof(MyAsyncEnumerable))]
public partial class MyContext : JsonSerializerContext
{
}

public class MyAsyncEnumerable : IAsyncEnumerable<int>
{
    IAsyncEnumerator<int> IAsyncEnumerable<int>.GetAsyncEnumerator(CancellationToken cancellationToken)
        => throw new NotImplementedException();
}
```
Produces
```C#
jsonTypeInfo = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateIAsyncEnumerableInfo<global::MyAsyncEnumerable, global::System.Int32>(options, info);
```
It's important to note that we wouldn't be able produce equivalent metadata for private implementations without resorting to `Type.MakeGenericType` calls, which are out of the question for NativeAOT scenaria. This is how the reflection converter factory works today:

https://github.com/dotnet/runtime/blob/cb8d49aaa4aa4f76e4cee0c2228651e1093188e9/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Collection/IAsyncEnumerableConverterFactory.cs#L28-L29

One possible solution is that we use [nearest ancestor](https://github.com/dotnet/runtime/blob/4cbe6f99d23e04c56a89251d49de1b0f14000427/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/PolymorphicTypeResolver.cs#L182-L229) resolution logic and fall back to the closest available supertype. This fallback should only happen in [serialization](https://github.com/dotnet/runtime/blob/cb8d49aaa4aa4f76e4cee0c2228651e1093188e9/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfoOfT.WriteHelpers.cs#L278-L285) as generally speaking it could only be supported in contravariant methods. We should never be returning the `JsonTypeInfo` of a supertype in any of the `GetTypeInfo` methods as that would violate the following invariant:
```C#
options.GetTypeInfo(typeof(T)) is JsonTypeInfo<T>
```
We also need to be careful about leaving out fallback to trivial supertypes such as `JsonTypeInfo<object>` as that would always just produce `{}` in JSON.

**Comment by krwq** [comment]
Why is ASP.NET looking at the runtime type when calling JSON? It should be using return type directly and then the metadata for unspeakable type wouldn't be needed... Am I missing something here?

**Comment by eiriktsarpalis** [comment]
> Why is ASP.NET looking at the runtime type when calling JSON? It should be using return type directly and then the metadata for unspeakable type wouldn't be needed... Am I missing something here?

Short answer is filters. They can return `object` so any static type information is lost

**Comment by eiriktsarpalis** [comment]
They could, although it would be replicating the logic that the PR is introducing. And, as mentioned in https://github.com/dotnet/runtime/pull/83631#issuecomment-1476100978 the issue is not specific to boxing, it also addresses the issue of private interface implementation support.

cc @eerhardt

**Comment by eiriktsarpalis** [comment]
And it's not just impacting ASP.NET obviously, we've had our own share of issues filed about this: https://github.com/dotnet/runtime/issues/79661

**Comment by eiriktsarpalis** [comment]
Reopening to track potential changes in the semantics of the feature (enabling via feature flags, etc.)
