### ISSUE TITLE
EnsureCapacity() on List<> increments the version

### ISSUE THREAD

**Issue by mikernet** [dotnet/runtime#82455]
### Description

Apparent oversight: Setting `Capacity` or calling `TrimExcess()` on `List<>` does not increment the version but calling `EnsureCapacity(int)` does.

### Reproduction Steps

```cs
var x = new List<int>();
var e = x.GetEnumerator();
x.EnsureCapacity(10);
e.MoveNext(); // collection modified exception due to version increment
```

### Expected behavior

Calling `EnsureCapacity` should not increment the version.

### Actual behavior

Calling `EnsureCapacity` increments the version.

**Comment by hez2010** [comment]
See https://github.com/dotnet/runtime/issues/81523
We may remove the check completely in the future.

**Comment by mikernet** [comment]
Yeah, I mentioned this in that discussion as well but wanted to create an issue to track this specifically in case a decision is made to keep the version checks.
