### ISSUE TITLE
Unroll SequenceEqual for u8 literals

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#82474]
```csharp
bool IsValue(ReadOnlySpan<byte> a) => a.SequenceEqual("value"u8);
```
```asm
; Method P:IsValue(System.ReadOnlySpan`1[ubyte]):bool:this
       sub      rsp, 40
       mov      r8, 0xD1FFAB1E ;; address of RVA field
       mov      rcx, bword ptr [rdx]
       mov      edx, dword ptr [rdx+08H]
       mov      bword ptr [rsp+20H], r8
       cmp      edx, 5
       jne      SHORT G_M29601_IG04
       mov      edx, 5
       mov      r8, rdx
       mov      rdx, bword ptr [rsp+20H]
       call     [System.SpanHelpers:SequenceEqual(byref,byref,ulong):bool]
       jmp      SHORT G_M29601_IG05
G_M29601_IG04:
       xor      eax, eax
       add      rsp, 40
       ret      
; Total bytes of code: 58

```

Should be unrolled similar to UTF-16:
```csharp
bool IsValue(ReadOnlySpan<char> a) => a.SequenceEqual("value");
```
```asm
; Method P:IsValue(System.ReadOnlySpan`1[ushort]):bool:this
       mov      rax, bword ptr [rdx]
       cmp      dword ptr [rdx+08H], 5
       jne      SHORT G_M10905_IG04
       mov      rdx, 0x75006C00610076
       xor      rdx, qword ptr [rax]
       mov      eax, dword ptr [rax+06H]
       xor      eax, 0x650075
       or       rax, rdx
       sete     al
       movzx    rax, al
       jmp      SHORT G_M10905_IG05
G_M10905_IG04:
       xor      eax, eax
G_M10905_IG05:
       ret      
; Total bytes of code: 44
```

### Motivation

To clean up various places like:
1) [JsonSerializer.Read.HandleMetadata.cs](https://github.com/dotnet/runtime/blob/cb8d49aaa4aa4f76e4cee0c2228651e1093188e9/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.HandleMetadata.cs#L236-L270)
2) aspnetcore's [HttpHeaders.Generated.cs](https://github.com/dotnet/aspnetcore/blob/f3836ae4b6d4ea9895745ac18af19331b4b58af5/src/Servers/Kestrel/Core/src/Internal/Http/HttpHeaders.Generated.cs#L7526-L7542)
3) ^ similar to that in runtime: [HeaderDescriptor.cs](https://github.com/dotnet/runtime/blob/cb8d49aaa4aa4f76e4cee0c2228651e1093188e9/src/libraries/System.Net.Http/src/System/Net/Http/Headers/HeaderDescriptor.cs#L183) - this currently picks a candidate and then does non-optimized comparison while it could do comparison against u8 literal in each case
4) Should optimize TE benchmarks as well e.g. here [BenchmarkApplication.cs](https://github.com/TechEmpower/FrameworkBenchmarks/blob/952b5243a07d8410ab9d727b0155be7d6da96399/frameworks/CSharp/aspnetcore/PlatformBenchmarks/BenchmarkApplication.cs#L62-L117)

### Work items

- [ ] SequenceEqual
- [ ] OrdinalIgnoreCase
- [ ] StartsWith

**Comment by stephentoub** [comment]
I thought we already did this :( Thanks for opening the issue. We don't do any such handling for bytes today, just chars?

**Comment by EgorBo** [comment]
> I thought we already did this :( Thanks for opening the issue. We don't do any such handling for bytes today, just chars?

Yep, chars only at the moment. RVA didn't fit well into that importer-level optimization, but I have a quick prototype to do this expansion later in ValueNumbering (or Early Prop). We also can then expand it to other patterns like `"false"u8.CopyTo(span)` 
https://github.com/dotnet/runtime/blob/d454374dd7ffb6830764a600324bc9088488291c/src/libraries/System.Private.CoreLib/src/System/Boolean.cs#L113-L115

**Comment by EgorBo** [comment]
Closed via https://github.com/dotnet/runtime/pull/83945

```csharp
bool IsValue(ReadOnlySpan<byte> a) => a.SequenceEqual("value"u8);
```
```asm
; Method Prog:IsValue(System.ReadOnlySpan`1[ubyte]):bool:this
G_M18139_IG01:
       sub      rsp, 40
						;; size=4 bbWeight=1 PerfScore 0.25

G_M18139_IG02:
       mov      rax, 0xD1FFAB1E      ; data for <PrivateImplementationDetails>:2AC3E771679DFE9EC82B8748F6F7718F3AD0E4EAAFABC9F68F4BC25187A5F230
       mov      rcx, bword ptr [rdx]
       mov      edx, dword ptr [rdx+08H]
       cmp      edx, 5
       jne      SHORT G_M18139_IG04
						;; size=21 bbWeight=1 PerfScore 5.50

G_M18139_IG03:
       mov      edx, dword ptr [rcx]
       mov      r8d, dword ptr [rax]
       mov      ecx, dword ptr [rcx+01H]
       mov      eax, dword ptr [rax+01H]
       xor      edx, r8d
       xor      eax, ecx
       or       eax, edx
       sete     al
       movzx    rax, al
       jmp      SHORT G_M18139_IG05
						;; size=26 bbWeight=0.50 PerfScore 6.00

G_M18139_IG04:
       xor      eax, eax
						;; size=2 bbWeight=0.50 PerfScore 0.12

G_M18139_IG05:
       add      rsp, 40
       ret      
						;; size=5 bbWeight=1 PerfScore 1.25
; Total bytes of code: 58
```

**Comment by gfoidl** [comment]
@EgorBo for `char` the [`xor` is done against two constants](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYQYG8aHuHgIIANgwCSuAGrYBAVxgAKAEoxsAEwDyAOwEBPAMoAHbOoA8YABbYoAPgbYAlAwC817ADodMAI4z1YGAFEvSVkAIgA3SRlg2wBuGgBfIA=), saving two memory loads. The JIT is able to do this when [written manually](https://github.com/dotnet/runtime/pull/83945#issuecomment-1484979336).

Is it possible to have this codegen here too? I.e. avoid the memory loads for the constant parts, and use only constant values.

**Comment by EgorBo** [comment]
> @EgorBo for `char` the [`xor` is done against two constants](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYQYG8aHuHgIIANgwCSuAGrYBAVxgAKAEoxsAEwDyAOwEBPAMoAHbOoA8YABbYoAPgbYAlAwC817ADodMAI4z1YGAFEvSVkAIgA3SRlg2wBuGgBfIA=), saving two memory loads. The JIT is able to do this when [written manually](https://github.com/dotnet/runtime/pull/83945#issuecomment-1484979336).
> 
> Is it possible to have this codegen here too? I.e. avoid the memory loads for the constant parts, and use only constant values.

A bit more complicated fix since I'll have to do that in an earlier phase. I just wanted to land a quick fix and see impact from it, so far not much
