### ISSUE TITLE
NativeAOT doesn't generate IL3000 and IL3001 - access to Assembly.Location property

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#82475]
The Single-File analyzer produces two warnings which are not triggered by `RequiresAssemblyFiles`, but are basically intrinsics:
- `IL3000` - basically just when accessing `Assembly.Location`
- `IL3001` - when accessing `Assembly.GetFiles` and several other methods

The NativeAOT compiler doesn't produce these warnings.

There also seem to be some issue with `RequiresAssemblyFiles` since the below program only produces analyzer warnings:
```C#
var a = typeof(object).Assembly.Location;   // IL3000
var b = typeof(object).Assembly.GetFiles();  // IL3001
```

But `Assembly.GetFiles` is annotated with `RequiresAssemblyFiles` attribute, so I would at least expect to get `IL3002` in this case (but ideally `IL3001`).

/cc @tlakollo

**Comment by MarcoRossignoli** [comment]
cc: @Evangelink

**Comment by MichalStrehovsky** [comment]
We should also enable the single file roslyn analyzer when publishaot is set in the project: filed #82503.
