### ISSUE TITLE
Configuration section Value discrepancy

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/runtime#82489]
### Description

When all you have in api helpers is IConfiguration (but it's actually a section) we sometimes want to get the value of the current section, either via GetSection("").Value or GetValue<T>(""); this does not work as expected today.

### Reproduction Steps

```cs
using System;
using Microsoft.Extensions.Configuration;

var json = """{"value": "here"}""";
var configuration = new ConfigurationBuilder().AddJsonStream(new System.IO.MemoryStream(System.Text.Encoding.UTF8.GetBytes(json))).Build();

Console.WriteLine(configuration.GetValue<string>("value") is null);
Console.WriteLine(configuration.GetSection("value").Value is null);
Console.WriteLine(configuration.GetSection("value").GetValue<string>("") is null);
Console.WriteLine(configuration.GetSection("value").GetSection("").Value is null);
```

### Expected behavior

I would expect it to be:
False
False
False
False

### Actual behavior

But instead this reads:

False
False
True
True

**Comment by tarekgh** [comment]
@NinoFloris could you elaborate more why you expect the following to return non-null values? 

```C#
configuration.GetSection("value").GetValue<string>("") 
configuration.GetSection("value").GetSection("").Value 
```

**Comment by NinoFloris** [comment]
Maybe I'm not understanding the semantics of asking GetSection/GetValue for an empty string key. Does that try to find a key "" instead? I assumed it would be a way to retrieve the head/current section. If so, is there some way to get the current section other than trying a type cast?

**Comment by tarekgh** [comment]
> Does that try to find a key "" instead? 

Yes. 

> is there some way to get the current section other than trying a type cast?

`configuration.GetSection("value")` is already returning `IConfigurationSection`.  So, you already have it. What exactly are you trying to do?

**Comment by tarekgh** [comment]
> Does that try to find a key "" instead? 

Yes. 

> is there some way to get the current section other than trying a type cast?

`configuration.GetSection("value")` is already returning `IConfigurationSection`.  So, you already have it. What exactly are you trying to do?

**Comment by NinoFloris** [comment]
The point is that I want helpers to be able to work over roots and sections so it's downcasted to IConfigurarion

**Comment by tarekgh** [comment]
Can you make this method parameter be `IConfiguration` and you can check inside `if (config :? IConfigurationSection)` to know if it is section or root?

**Comment by NinoFloris** [comment]
Sure, so the type cast it is :)

**Comment by tarekgh** [comment]
> Sure, so the type cast it is :)

Yes. I am closing the issue but feel free to respond if you have more questions.
