### ISSUE TITLE
Add possibility to add configuration files from anywhere

### ISSUE THREAD

**Issue by Kralizek** [dotnet/runtime#82485]
I'm not sure if this one should be an API proposal...

I'm creating a console application and I would like to be able to give my users the possibility to have overlapping configuration files  in the following locations:

- console installation location
- user home folder
- working directory

Currently, `AddJsonFile ` is limited to files within the application folder structure.

It would be cool if we could specify an absolute path and have the configuration system reading it.

At the moment, I'm reading the file myself and add its content to the configuration builder using `AddJsonStream`.

```csharp
internal static class ConfigurationBuilderExtensions
{
    public static IConfigurationBuilder AddAbsoluteJsonFile(this IConfigurationBuilder builder, FileInfo file)
    {
        if (file.Exists)
        {
            using var fs = new FileStream(file.FullName, FileMode.Open);

            builder.AddJsonStream(fs);
        }

        return builder;
    }
}
```

It would be cool if support for external files were to be added to the configuration system out of the box.

**Comment by tarekgh** [comment]
@Kralizek Thanks for your request. Unfortunately, we don't have any plan to support that in the near future because of other higher priority work. I am closing this request, but we'll watch if there will be any demand for this feature and we can consider.
