### ISSUE TITLE
[Memory consumption] Remove relocations for TypeHandle fields

### ISSUE THREAD

**Issue by ruben-ayrapetyan** [dotnet/runtime#8248]
Hello.

We are currently working on reducing memory consumption by reducing number of pages that contain relocated fields (i.e. fields that need fixup during load).

There are several places, in which `TypeHandle` fields are relocated:
 - in SECTION_Class (`ParamTypeDesc`-related)
 - in SECTION_ReadOnly (`MethodTable`-related)
 - ...

Fields other than `TypeHandle` are relatively simple to implement through `RelativePointer` or `RelativeFixupPointer`.

There is an issue with applying the technique to `TypeHandle`, which is related to `Instantiation` class (src/vm/typehandle.h).

The `Instantiation::GetRawArgs` provides raw access to `TypeHandle` fields through pointer to the fields. It is currently not aware of `RelativeFixupPointer`/`RelativePointer` representation.

Although the method is marked as `Unsafe ... Do not use unless absolutely necessary`, it is used in several places:
 - `TypeKey`
 - `CORINFO_SIG_INST`
 - fixup of `MethodDesc`
 - setup of `MethodTable`
 - `RuntimeTypeHandle::GetInstantiation`
 - `EECMHelperHashtableHelper::AllocateEntry` / `EECMHelperHashtableHelper::Hash`

All except the `EECMHelperHashtableHelper` seems to actually refer only the `TypeHandle` values, and the `EECMHelperHashtableHelper::Hash` uses the pointer values themselves for hashing.
Two set of relative pointers can be bitwise-equal and at the same time point to different values, so the hashing logic can be changed upon switching to relative pointers there. To leave the logic as is while changing to relative pointers, the `Hash` procedure should be updated, to handle pointer values one-by-one.

The comment to the `class Instantiation` is the following:
```
// Instantiation is representation of generic instantiation. 
// It is simple read-only array of TypeHandles. In NGen, the type handles
// may be encoded using indirections. That's one reason why it is convenient
// to have wrapper class that performs the decoding.
```

As I understand, the class is considered to be a wrapper for accessing type handles.
With exception of `GetRawArgs` it could be easily changed, by introducing a flag, which specifies absolute/relative format of pointers.

However, `GetRawArgs` also makes it to be a wrapper for the pointer values themselves.

Considering this, is it good idea to convert the `TypeHandle` fields to `RelativePointer<TypeHandle>`?

cc: @Dmitri-Botcharnikov @gbalykov

**Comment by jkotas** [comment]
The code for fragile ngen has been deleted.
