### ISSUE TITLE
ReplaceLineEndings is slower than Replace("\r\n")

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#82491]
```csharp
static readonly string Text = File.ReadAllText(@"C:\prj\runtime-main\THIRD-PARTY-NOTICES.TXT");

[Benchmark]
public string ReplaceLineEndings() => Text.ReplaceLineEndings();

[Benchmark]
public string Replace() => Text.Replace("\r\n", "");
```

Latest Main on Windows-x64, `THIRD-PARTY-NOTICES.TXT` file has ~1000 `\r\n`:
```
|             Method |      Mean |    Error |   StdDev |
|------------------- |----------:|---------:|---------:|
| ReplaceLineEndings | 140.40 us | 0.200 us | 0.187 us |
|            Replace |  32.20 us | 0.296 us | 0.277 us |
```
.NET 7.0 shows ever bigger difference.

cc @stephentoub @MihaZupan

**Comment by stephentoub** [comment]
> ReplaceLineEndings is slower than Replace("\r\n")

It's searching for more things.  Why wouldn't it be slower?

**Comment by EgorBo** [comment]
> > ReplaceLineEndings is slower than Replace("\r\n")
> 
> It's searching for more things. Why wouldn't it be slower?

Ah, oops, nvm 🙂 I misunderstood what ReplaceLineEndings does.

**Comment by MihaZupan** [comment]
As it's searching for 6 chars, it falls back to using the ProbabilisticMap instead of a vectorized IndexOf search.
I have a PR up that adds vectorization for it, but it would still be slower than just searching for CRLF.

**Comment by EgorBo** [comment]
https://grep.app/search?q=.Replace%28%22%5Cr%5Cn%22%2C%20%22%5Cn%22&words=true&filter[lang][0]=C%23 quite popular pattern - was just wondering if we can do anything to speed it up
