### ISSUE TITLE
Mono runtime fails to build cross-compilers for x86/x64 on arm/arm64

### ISSUE THREAD

**Issue by directhex** [dotnet/runtime#82495]
Splitting out the issues described in https://github.com/dotnet/runtime/issues/74175, especially the comments https://github.com/dotnet/runtime/issues/74175#issuecomment-1228860772 and https://github.com/dotnet/runtime/issues/74175#issuecomment-1220796119

As-is, we cannot build cross-compilers from arm64 to x64, so we cannot build cross-compilers for osx-arm64 to iOS, tvOS, Android, or Mac Catalyst. The same problem applies for Linux cross-compilers to Android. The build system is ready on the mono.proj etc side, it's problems with the Mono runtime itself.

**Comment by rdavisau** [comment]
In case it's useful, [unscientific testing](https://ryandavis.io/improving-dotnet-ios-release-build-times-on-apple-silicon/) on my M1 showed using arm64 binaries for `mono-aot-cross` and friends made the aot compile task 30%-35% faster across a variety of projects. 

![image](https://github.com/dotnet/runtime/assets/7392704/3077ddfe-ba28-4648-a144-881ad8e8e431)

**Comment by lambdageek** [comment]
After #74715 and #89027 I think this is our status now (updating the table from https://github.com/dotnet/runtime/issues/74175#issuecomment-1228860772):

| Build machine | Cross-compiler target | Executing machine | Status |
| --- | --- | --- | --- |
| linux-x64 | browser-wasm | linux-arm64 | ☑ 
| linux-x64 | android-x64 | linux-arm64 | ☑
| linux-x64 | android-arm64 | linux-arm64 | ⚠ Builds, disabled in #74175
| linux-x64 | android-x86 | linux-arm64 | ☑, ⚠ may need https://github.com/dotnet/runtime/issues/89039 for local builds 
| linux-x64 | android-arm | linux-arm64 | ⚠ Builds, disabled in #74175
| win-x64 | browser-wasm | win-arm64 | ☠ Does not build, removed from scope
| win-x64 | android-x64 | win-arm64 | ☠ Does not build, removed from scope
| win-x64 | android-arm64 | win-arm64 | ☠ Does not build, removed from scope
| win-x64 | android-x86 | win-arm64 | ☠ Does not build, removed from scope
| win-x64 | android-arm | win-arm64 | ☠ Does not build, removed from scope
| osx-x64 | browser-wasm | osx-arm64 | ☑
| osx-x64 | android-x64 | osx-arm64 | ☑
| osx-x64 | android-arm64 | osx-arm64 | ⚠ Builds, disabled in #74175
| osx-x64 | android-x86 | osx-arm64 | ☑
| osx-x64 | android-arm | osx-arm64 | ⚠ Builds, disabled in #74175
| osx-x64 | ios-arm64 | osx-arm64 | ⚠ Builds, disabled in #74175
| osx-x64 | iossimulator-arm64 | osx-arm64 | ⚠ Builds, disabled in #74175
| osx-x64 | iossimulator-x64 | osx-arm64 | ☑
| osx-x64 | iossimulator-x86 | osx-arm64 | ❌ Does not build - ❓ is this still supported
| osx-x64 | ios-arm | osx-arm64 | ⚠ Builds, disabled in PR - ❓ is this still supported
| osx-x64 | tvos-arm64 | osx-arm64 | ⚠ Builds, disabled in #74175
| osx-x64 | tvossimulator-arm64 | osx-arm64 | ⚠ Builds, disabled in #74175
| osx-x64 | tvossimulator-x64 | osx-arm64 | ☑
| osx-x64 | maccatalyst-arm64 | osx-arm64 | ⚠ Builds, disabled in #74175
| osx-x64 | maccatalyst-x64 | osx-arm64 | ☑

I'm not sure what "disabled in #74175 means"

**Comment by directhex** [comment]
Just meant "disabled in the PR I'm trying to get merged"

Do we still support any scenarios where iossimulator-x86 or ios-arm matter? IOS dropped support for 32-bit ARM with iOS 11 (2017). I can't easily determine when x86 support for the simulator was dropped, but I imagine it's the same thing if the whole-ass OS lost 32-bit support at once.

What's the minimum iOS version we support?

**Comment by steveisok** [comment]
@directhex No, we do not support x86 and arm on ios any longer. 

@akoeplinger what's the min iOS version we are targeting in .NET 8?

**Comment by directhex** [comment]
We should kill them for 8 then

**Comment by steveisok** [comment]
> We should kill them for 8 then

@akoeplinger did in https://github.com/dotnet/runtime/pull/81965

I also found iOS 11 is the min we support for .NET 8

**Comment by SamMonoRT** [comment]
Assigning to @directhex for accurate tracking. 
@steveisok @directhex - should we move this to 9.0, or is the remaining work essential to ship 8.0 release ?

**Comment by steveisok** [comment]
I think 9.0 is fine. There's really no time to test the win-arm64 cross compiler. That's the only one left in the bunch.

**Comment by directhex** [comment]
Yeah I have no confidence that we can get windows arm64 tested adequately in time for 8. There's an open PR for now
