### ISSUE TITLE
Unexpected `QuicStream.WriteAsync` exception

### ISSUE THREAD

**Issue by bentoi** [dotnet/runtime#82523]
### Description

`QuicStream.WriteAsync` can throw if the remote stream is disposed after reading the data. I don't expect `WriteAsync` to throw if the data is successfully sent.

### Reproduction Steps

Run the attached test case: [quicwriteexception.zip](https://github.com/dotnet/runtime/files/10814220/quicwriteexception.zip)

### Expected behavior

No exception.

### Actual behavior

`WriteAsync` raises `System.Net.Quic.QuicException: Stream aborted by peer (0)`.

### Configuration

DotNet 7.0.100

**Comment by CarnaViire** [comment]
Triage: I was able to reproduce it (though I had to wait for some time before that happened).
We need to fix it in 8.0.
Seems to be part of a group of issues around S.N.Quic's ResettableValueTaskSource (Cancellation, Reads/WritesClosed and disposal order/behavior).

**Comment by ManickaP** [comment]
I think this is similar to this test issue: https://github.com/dotnet/runtime/issues/81944
