### ISSUE TITLE
Garbage collector may crash when new byte[] and GC.AllocateUninitializedArray(n, true) is mixed extensively.

### ISSUE THREAD

**Issue by GhostTyper** [dotnet/runtime#82548]
### Description

When mixing calls to `new byte[n]` and `GC.AllocateUninitializedArray(n, true)` in multiple threads (parallel calls) the garbage collector may crash when running `GC.Collect()` or may corrupt memory.

### Reproduction Steps

I wrote a small demo which leads to the bug [here](https://github.com/GhostTyper/net6memory). You can either check out the demo and try it or work your way to the issue by this small example:

```csharp
private const int THREADS = 8;
private const int PER_RUN = 262144;

for (int thd = 0; thd < THREADS; thd++)
{
    int thdNo = thd;

    ThreadPool.QueueUserWorkItem(delegate
    {
        Random rng = new Random();

        mem[thdNo] = new List<Mem>();

        byte[] bts;

        while (true)
        {
            if (rng.Next(2) == 0)
                bts = GC.AllocateUninitializedArray<byte>(rng.Next(256), true);
            else
                bts = new byte[rng.Next(256)];

            rng.NextBytes(bts);

            mem[thdNo].Add(new Mem(bts));

            if (mem[thdNo].Count >= PER_RUN)
            {
                foreach (Mem sM in mem[thdNo])
                    if (sM.HasSizeChanged)
                        Console.WriteLine($"{sM.ErrorReport}                         ");

                mem[thdNo] = new List<Mem>();

                GC.Collect();
            }
        }
    });
}

struct Mem
{
    public readonly byte[] Bytes;
    public readonly int Length;

    public Mem(byte[] bytes)
    {
        Bytes = bytes;
        Length = Bytes.Length;
    }

    public bool HasSizeChanged => Bytes is null || Bytes.Length != Length;

    public string ErrorReport => $"Array size changed from {Length} to {(Bytes ?? new byte[0]).Length}.";
}
```

### Expected behavior

I expect the CLR to not crash and not corrupt memory.

### Actual behavior

Currently memory can be overwritten by control structures of the garbage collector (as it seems) which may lead to `byte[]` changing their `.Length` and sometimes content at the beginning.

Also it may result into `Fatal error. Internal CLR error. (0x80131506)` sometimes with or without the following stacktrace:
```text
Repeat 2 times:
--------------------------------
   at System.GC._Collect(Int32, Int32)
--------------------------------
   at MemoryTest.Program+<>c__DisplayClass5_0.<Main>b__0(System.Object)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

### Regression?

As I tracked this down this bug is in all .NET 6 and .NET 7 (and maybe .NET 5) implementations up to `6.0.14` and `7.0.3`.

### Known Workarounds

One could just use `new byte[]` and then pin it by `GCHandle`. However, sometimes this may not work because one may reserve the memory in a fire and forget style and then needs to extra handle the `GCHandle.Free()`.

### Configuration

We did see this issue on non server GC on Windows clients (Windows 10 and 11) and Windows Server and on debian 11.

### Other information

See the project [here](https://github.com/GhostTyper/net6memory) for a ready to run demo. It took us weeks because we tried to track down the issue in our own code.

**Comment by mangod9** [comment]
Thanks for reporting the issue @GhostTyper. Just wanted to confirm that you are able to repro this in 6.0 as well? If its only in 7, if could be related to this issue: https://github.com/dotnet/runtime/issues/79882

**Comment by GhostTyper** [comment]
Hey @mangod9, I released it to a Windows Server 2019 which only has .NET 6 installed and hereby confirm that it also has the mentioned issues:
```text
C:\Users\Administrator\Desktop\memtest>dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

C:\Users\Administrator\Desktop\memtest>MemoryTest.exe
This demo shows a bug in the memory management of .NET 6 when stressing
the garbage collector with a mixture of new byte[] and GC.Allocate-
UninitializedArray(..., true). We did test this on various hardware but
it may be that you can't reproduce the test results with your hardware.

There a two error patterns: (1) byte[] may be overwritten with others
or (2) the CLR (more seldom) may just die.

You will require RAM. Approx ~640 MB!

Array size changed from 255 to 126.
Array size changed from 201 to 29.
Array size changed from 86 to 20.
Array size changed from 62 to 9.
Fatal error. Internal CLR error. (0x80131506)
```

**Comment by mangod9** [comment]
ok, thanks. We will try to repro it locally.

**Comment by cshung** [comment]
@GhostTyper, can you please try to change the allocation size from `rng.Next(256)` to `512 + rng.Next(256)`, if that doesn't repro, it might indicate it is #76929.

**Comment by GhostTyper** [comment]
@cshung: When will it be fixed probably?

**Comment by cshung** [comment]
> @cshung: When will it be fixed probably?

It is not our priority right now, but if you have business justifications for why this is important you can let us know and we might prioritize it.

**Comment by GhostTyper** [comment]
> > @cshung: When will it be fixed probably?
> 
> It is not our priority right now, but if you have business justifications for why this is important you can let us know and we might prioritize it.

We have business justifications, however if it won't make it into the next release, we will find our way around this issue.

**Comment by cshung** [comment]
> We have business justifications, however if it won't make it into the next release, we will find our way around this issue.

Oh, if we are just talking about the next release, I am pretty sure this will make .NET 8.

**Comment by mangod9** [comment]
Just wanted to clarify where allocating the objects on POH is something you intend to do? Believe this bug wouldnt repro if not allocated on the pinned heap.

**Comment by GhostTyper** [comment]
@cshung: I thought more about 6.0.15 or 6.0.16.

@mangod9: Yes, we wanted to have pinned objects and we know that it wouldn't happen with just `new byte[]`.
