### ISSUE TITLE
No .webcil files after publish [Linux/x64 - static Blazor WASM]

### ISSUE THREAD

**Issue by JeepNL** [dotnet/runtime#82549]
When I locally (Windows 11) publish my static Blazor WASM project to upload to a Cloudflare Pages Linux/x64 environment, no `.webcil` files are published in the `wwwroot/_framework` directory.  The .dll, .dll.gz & dll.br files are published so the website (live at https://tusk.ninja) does work, but without the .webcil files.

**I've installed**
 * dotnet workload install wasm-tools
 * dotnet workload install wasm-experimental

**.csproj**
```
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <WasmEnableWebcil>true</WasmEnableWebcil>
    <BlazorEnableTimeZoneSupport>true</BlazorEnableTimeZoneSupport>
    <InvariantGlobalization>true</InvariantGlobalization>
    <BlazorWebAssemblyPreserveCollationData>false</BlazorWebAssemblyPreserveCollationData>
    <TrimmerRemoveSymbols>true</TrimmerRemoveSymbols>
    <DebuggerSupport>false</DebuggerSupport>
  </PropertyGroup>
```

**Build command line**
```
dotnet publish Client.Tusk.csproj --nologo --force -c Release --arch x64 --os linux --self-contained true -o C:\X\Repos\Tusk\_CloudflarePublish
```

**Comment by radical** [comment]
cc @lambdageek

**Comment by lambdageek** [comment]
Webcil is not supported with Blazor in .NET 8 Preview 1.  It will be enabled in Blazor in a future preview.

It only works with `dotnet new wasmbrowser` (Barebones .NET for webassembly) projects at this time

**Comment by JeepNL** [comment]
Ah, I thought `wasmbrowser` was the same as (a static) 'blazorwasm', but it's clearly not. My bad :)

Tried to install `wasmbrowser` with .NET 8 preview 1 command line, but it didn't work. This is just FYI (another issue?). Maybe/probably I'm doing something wrong (again).

**Search**
```
C:\X\Repos\_Test> dotnet new search wasmbrowser
Searching for the templates...
Matches from template source: NuGet.org
These templates matched your input: 'wasmbrowser'

Template Name            Short Name   Author     Language  Package                                      Downloads
-----------------------  -----------  ---------  --------  -------------------------------------------  ---------
WebAssembly Browser App  wasmbrowser  Microsoft  [C#]      Microsoft.NET.Runtime.WebAssembly.Templates
```

**Install**
```
C:\X\Repos\_Test>dotnet new install wasmbrowser
The following template packages will be installed:
   wasmbrowser

wasmbrowser could not be installed, the package does not exist.

For details on the exit code, refer to https://aka.ms/templating-exit-codes#103
```

If you want you can close this issue.

**Comment by JeepNL** [comment]
Yes, I did something wrong! Of course!

`dotnet new install Microsoft.NET.Runtime.WebAssembly.Templates` works.

Closing this 'issue'
