### ISSUE TITLE
[NativeAOT] cross-compiling to osx-arm64 from osx-x64 does not work

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#82542]
Reported by @lemonmojo in https://github.com/dotnet/runtime/issues/73678#issuecomment-1441488462:

I'm also running into the same error using .NET 8 Preview 1.

While cross-compiling to x64 from an M1 machine works fine for me, I can't get the reverse (cross-compiling to ARM64 from an Intel machine) to work.

I'm not using any packages in this project. In fact, the issue is very easy to reproduce:
```
dotnet new classlib -n "AOTTest"
cd AOTTest
dotnet publish -p "PublishAot=true" -r osx-x64
dotnet publish -p "PublishAot=true" -r osx-arm64
```

Publishing using `dotnet publish -r osx-x64` and `dotnet publish -r osx-arm64` works fine from an M1 machine.
While on an Intel machine only the x64 build works and the ARM64 one fails with the error message:

```
/Users/redacted/.nuget/packages/microsoft.dotnet.ilcompiler/8.0.0-preview.1.23110.8/build/Microsoft.NETCore.Native.Publish.targets(74,5): error : The PrivateSdkAssemblies ItemGroup is required for _ComputeAssembliesToCompileToNative [/Path/to/Project.csproj].
```

So here's what works and what doesn't work in my testing:
ARM64 -> x64: OK
ARM64 -> ARM64: OK
x64 -> x64: OK
x64 -> ARM64: Error

**Comment by jkotas** [comment]
@filipnavara Do you happen to know what the problem is?

**Comment by am11** [comment]
> While cross-compiling to x64 from an M1 machine works fine for me, I can't get the reverse (cross-compiling to ARM64 from an Intel machine) to work.

FWIW, the CI is cross-compiling for arm64 on osx-x64 machine.

**Comment by filipnavara** [comment]
It used to work, and this error is new to me. I'll try to reproduce it on my machine, but just in case that doesn't work, it would be useful to get a MSBuild binlog. It can be produced with a `/bl` switch on the `dotnet publish` command line, which will produce a `msbuild.binlog` file.

**Comment by kant2002** [comment]
I do have binlog from @lemonmojo and we troubleshoot that issue in #coreclr channel on dotnet evolution. 
Issue was that runtime package was not downloaded as part of restore(?) process.
We solve that by manually adding package `<PackageReference Include="runtime.osx-arm64.Microsoft.DotNet.ILCompiler" Version="8.0.0-preview.1.23110.8" />`. 
Discrepancies in differences quite possible was because `ARM64 -> x64: OK` was first attemp, and ARM64 machine has runtime package in the cache already.

**Comment by jkotas** [comment]
If you do not use explicit `Microsoft.DotNet.ILCompiler` package reference, it should just work.

The explicit `runtime.osx-arm64.Microsoft.DotNet.ILCompiler` package reference should be only needed if you use `Microsoft.DotNet.ILCompiler` package reference. This is documented in https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/compiling.md#cross-architecture-compilation.

**Comment by filipnavara** [comment]
It reproduces. The `RuntimePackagePath` property in `ImportRuntimeIlcPackageTarget` gets set to an empty value.

**Comment by kant2002** [comment]
I ask OP manually add this to download package in the cache. I think after this package in the Nuget cache issue will disappear.

**Comment by kant2002** [comment]
It obviosly still a bug, but I do not troubleshoot that far and I do not have Mac

**Comment by filipnavara** [comment]
The problem happens on this line:
https://github.com/dotnet/runtime/blob/f295ea1adf64cdd9d46674ff410da6fb5a538a00/src/coreclr/nativeaot/BuildIntegration/Microsoft.DotNet.ILCompiler.SingleEntry.targets#L51

`ResolvedTargetILCompilerPack` is set earlier:
<img width="435" alt="image" src="https://user-images.githubusercontent.com/1764393/221000429-5c68ee23-aa9e-46d1-8c67-ae9c1884e2d4.png">

It matches `RuntimeIlcPackageName = runtime.osx-arm64.Microsoft.DotNet.ILCompiler`.

However, there's no `PackageDirectory` property on the `ResolvedTargetILCompilerPack` item.

**Comment by kant2002** [comment]
It happens because RuntimeIlcPackageName   package not in the cache. Without that GetPackageDirectory cannot find path to package(it does not exists locally)

**Comment by filipnavara** [comment]
> It happens because RuntimeIlcPackageName package not in the cache. Without that GetPackageDirectory cannot find path to package(it does not exists locally)

Yep, I agree with the assessment. It doesn't restore the NuGet of the target runtime package. If it already exists though then the error doesn't happen.

Here's a proof:
```
filipnavara@Filips-MacBook-Air AOTTest % ~/.dotnet/dotnet publish -p "PublishAot=true" -r osx-arm64 
MSBuild version 17.6.0-preview-23108-10+51df47643 for .NET
  Determining projects to restore...
  Restored /Users/filipnavara/Projects/AOTTest/AOTTest.csproj (in 537 ms).
/Users/filipnavara/.dotnet/sdk/8.0.100-preview.1.23115.2/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(287,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/Users/filipnavara/Projects/AOTTest/AOTTest.csproj]
  AOTTest -> /Users/filipnavara/Projects/AOTTest/bin/Release/net8.0/osx-arm64/AOTTest.dll
  Generating native code
  AOTTest -> /Users/filipnavara/Projects/AOTTest/bin/Release/net8.0/osx-arm64/publish/
filipnavara@Filips-MacBook-Air AOTTest % rm -fr ~/.nuget
filipnavara@Filips-MacBook-Air AOTTest % ~/.dotnet/dotnet publish -p "PublishAot=true" -r osx-arm64 
MSBuild version 17.6.0-preview-23108-10+51df47643 for .NET
  Determining projects to restore...
  Restored /Users/filipnavara/Projects/AOTTest/AOTTest.csproj (in 1.88 sec).
/Users/filipnavara/.dotnet/sdk/8.0.100-preview.1.23115.2/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(287,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/Users/filipnavara/Projects/AOTTest/AOTTest.csproj]
  AOTTest -> /Users/filipnavara/Projects/AOTTest/bin/Release/net8.0/osx-arm64/AOTTest.dll
/Users/filipnavara/.nuget/packages/microsoft.dotnet.ilcompiler/8.0.0-preview.1.23110.8/build/Microsoft.NETCore.Native.Publish.targets(74,5): error : The PrivateSdkAssemblies ItemGroup is required for _ComputeAssembliesToCompileToNative [/Users/filipnavara/Projects/AOTTest/AOTTest.csproj]
```

**Comment by jkotas** [comment]
This code should be responsible for downloading both x64 and arm64 packages for cross-compilation:

https://github.com/dotnet/sdk/blob/main/src/Tasks/Microsoft.NET.Build.Tasks/ProcessFrameworkReferences.cs#L668-L684

**Comment by filipnavara** [comment]
> https://github.com/dotnet/sdk/blob/main/src/Tasks/Microsoft.NET.Build.Tasks/ProcessFrameworkReferences.cs#L668-L684

The output of the task has only the host targeting pack in the `_PackageToDownload` output despite the rest of the inputs and outputs being correct.

**Comment by filipnavara** [comment]
I suppose the fix would be placing this somewhere around [here](https://github.com/dotnet/sdk/blob/37d204c740a42b8580b5f94e69cd7b59d1841410/src/Tasks/Microsoft.NET.Build.Tasks/ProcessFrameworkReferences.cs#L683):

```
                if (EnableRuntimePackDownload)
                {
                    // We need to download the runtime pack
                    TaskItem runtimePackToDownload = new TaskItem(targetIlcPackName);
                    runtimePackToDownload.SetMetadata(MetadataKeys.Version, packVersion);
                    packagesToDownload.Add(runtimePackToDownload);
                }
```

**Comment by filipnavara** [comment]
I tested the fix with local build and it works, so I opened a PR.

**Comment by jkotas** [comment]
This specific cross-compilation scenario is fixed by https://github.com/dotnet/runtime/pull/82558. 

(If there are other cross-compilation scenarios to improve, we should open specific issues for them.)

**Comment by lemonmojo** [comment]
Thx @jkotas and @filipnavara! I'll test again when the next preview lands. Cheers
