### ISSUE TITLE
The current ManagedWebSocket.IsValidCloseStatus implementation may reject certain valid status codes when it shouldn't

### ISSUE THREAD

**Issue by chenxinyanc** [dotnet/runtime#82602]
I don't have a clean code snippet for this (suspected) bug but the current implementation of `IsValidCloseStatus` will reject WebSocket close status code [1014 "Bad Gateway"](https://www.iana.org/assignments/websocket/websocket.xhtml#close-code-number). Specifically, if remote-side initiates WS closure with status code 1014, `ManagedWebSocket` will immediately abort the connection.

Suppose we have client-side code as follows, and WS server closes WebSocket proactively after a while, with status code 1014
```c#
using var wsClient = new ClientWebSocket();
await wsClient.ConnectAsync(new Uri("..."), default);
var result = await wsClient.ReceiveAsync(Memory<byte>.Empty, default);
```

There will be an Exception thrown from client side, `wsClient` enters `Aborted` state, and server-side also observes the client-side has aborted connection instead of replying with a Close handshake message.
```log
System.Net.WebSockets.WebSocketException
An exception caused the WebSocket to enter the Aborted state. Please see the InnerException, if present, for more details.
   at System.Net.WebSockets.ManagedWebSocket.CloseWithReceiveErrorAndThrowAsync(WebSocketCloseStatus closeStatus, WebSocketError error, String errorMessage, Exception innerException)
   at System.Net.WebSockets.ManagedWebSocket.HandleReceivedCloseAsync(MessageHeader header, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at 
...
```

It seems that currently `ManagedWebSocket.IsValidCloseStatus` will reject all the WS close status code falling into the range of 1000-2999 but not within the (most of the) `WebSocketCloseStatus` enum values. This is too strict and not resilient to any possible future extensions.

I think the point is, as long as the WS close frame received from remote-side is valid, is it possible for `ManagedWebSocket` just to relay whatever status code received from remote side to the API consumer, and let them decide whether they'd like to abort the connection? I understand there are some status codes never intended to be sent (e.g., 1005 "Empty" or 1006 "Abnormal closure"), but that doesn't sound fit to me to reject all the other status codes in 1000-2999 because of this.

https://github.com/dotnet/runtime/blob/5415cd1e4e1359dd5fb5c6727bcdf8dcad457a71/src/libraries/System.Net.WebSockets/src/System/Net/WebSockets/ManagedWebSocket.cs#L1030-L1067

**Comment by IDisposable** [comment]
I'm pulling together a PR for this now

**Comment by IDisposable** [comment]
In building out the tests for this it becomes evident that **not** adding the three new acceptable close status codes to the `WebSocketCloseStatus` enum makes the testing break. It seems like it's just better not to play spooky magic with those three integer values since testing them gives errors.

**Comment by IDisposable** [comment]
PR up https://github.com/dotnet/runtime/pull/83712

**Comment by IDisposable** [comment]
PR https://github.com/dotnet/runtime/pull/83713

**Comment by IDisposable** [comment]
I'm reworking this now per the feedback on the PR
