### ISSUE TITLE
System.Security.Claims.Claim Value should support any data type

### ISSUE THREAD

**Issue by niemyjski** [dotnet/runtime#82613]
### Description

Currently you can only create a claim (https://github.com/dotnet/runtime/blob/main/src/libraries/System.Security.Claims/src/System/Security/Claims/Claim.cs) as with a string value. I'm sure there is a reason for this but it doesn't play nicely with jwt claim values as desribed in the RFC: https://www.rfc-editor.org/rfc/rfc7519#section-2

>   Claim Value
      The value portion of a claim representation.  A Claim Value can be
      any JSON value.

### Reproduction Steps

Try creating a claim with any array / object / number data.. You cannot:

`public Claim(string type, string value, string? valueType)`

### Expected behavior

I should be able to create a claim with any value (especially since I can specify a value type).

`public Claim(string type, object value, string? valueType)`

### Actual behavior

Only can create values as a string. I'm really not sure what happens if a claim comes through with a non string type what happens. I'm guessing this might go into https://github.com/dotnet/runtime/blob/main/src/libraries/System.Security.Claims/src/System/Security/Claims/Claim.cs#L30

**Comment by niemyjski** [comment]
I feel like there are other bug reports which might be related somewhat due to the data type (example: https://github.com/dotnet/runtime/issues/55732)

**Comment by Jozkee** [comment]
> I'm sure there is a reason for this 

As per the docs, it was intended to only support string.
https://learn.microsoft.com/en-us/dotnet/api/system.security.claims.claim?view=net-7.0#remarks

> The [Value](https://learn.microsoft.com/en-us/dotnet/api/system.security.claims.claim.value?view=net-7.0) property contains the value of the claim. In order to reduce dependencies and simplify administration, in WIF the value of a claim is represented only as a string. For more complex value types, it is recommended that you use standard XML schema types to indicate how the value is meant to be serialized into and deserialized from a string.

**Comment by Jozkee** [comment]
Can't you just serialize your value JSON and pass that as the `value` in the actor?

**Comment by niemyjski** [comment]
Sure, one could serialize it to json, but seems like opening this up to more than a single string would be ideal and more in common with real world usage?

**Comment by Jozkee** [comment]
As [this person pointed out](https://github.com/dotnet/runtime/issues/83128#issuecomment-1481839575):

> A Claim is orthogonal to any protocol or spec.
 

It is not up to the Claim to treat the value as if it needs to be JSON-serialized, I think that's the point of it just accepting string.

**Comment by niemyjski** [comment]
That's great but the RFC and real-world usage says otherwise. Makes interop with other systems outside of your control not that easy. I logged this because I hit this in real world trying to interact with a Java based system.

**Comment by Jozkee** [comment]
> That's great but the RFC and real-world usage says otherwise

which RFC? I assume you are referring to the JWT one you linked. Claims is not meant to be tied to only one RFC, as far as I see it.

> Makes interop with other systems outside of your control not that easy

Isn't this (in a simplified manner) what you have to do to support your scenario?

```cs
string jsonValue = JsonSerializer.Serialize(obj);
var yourClaim = new Claim(yourType, jsonValue, yourValueType);
```

cc @bartonjs
