### ISSUE TITLE
[API Proposal]: Rename IndexOfAnyValues

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#82622]
We introduced System.Buffers.IndexOfAnyValues in .NET 8 as a way to cache computation associated with preparing any number of values for being used in a search.  We expected to only use it with IndexOfAny, and maybe subsequently in a Contains, which if you squint is an IndexOf operation where you only pay attention to whether the result is negative.  However, we've since found places where we'd possibly benefit from exposing overloads of other operations that would take an IndexOfAnyValues, like Count, Replace, or Remove, and in those contexts, the IndexOfAnyValues name is... strange.

Other name possibilities:
- System.Buffers.SearchValues
- System.Buffers.FindValues
- ...

The type (`IndexOfAnyValues` and `IndexOfAnyValues<T>`) is brand new in .NET 8, so if we're going to change it, now is the time.

cc: @MihaZupan

**Comment by benaadams** [comment]
IndexesOfAnyValues 🤔😅

**Comment by dubiousconst282** [comment]
A more exotic option would be something like `BufferProbe` or `ValueProbe`.

I think having a more generic name would be better for future extensions like proposed in #75175.

**Comment by panost** [comment]
In my proposal #59649, I used the name Scanner

**Comment by terrajobst** [comment]
We'd prefer `SearchValues` as the type name.
