### ISSUE TITLE
[API Proposal]: System.Diagnostics.ActivitySource create/start root activity

### ISSUE THREAD

**Issue by CodeBlanch** [dotnet/runtime#82673]
### Background and motivation

Today we have ActivitySource.CreateActivity and ActivitySource.StartActivity APIs. If an ActivityContext is not supplied Activity.Current is automatically used as the parent. We have seen cases where users want to explicitly create an Activity without a parent. They are forced to do things like this...

```csharp
    Activity.Current = null;

    var newRoot = source.StartActivity("NewRoot");
```

Should we add something to help smooth this out?

/cc @martinjt @alanwest @cijothomas @utpilla @noahfalk @tarekgh 

### API Proposal

```csharp
namespace System.Diagnostics;

public class ActivitySource
{
    public Activity? CreateRootActivity(...)
    public Activity? StartRootActivity(...)
}
```

If we add this API it might be useful to supply a parameter which would automatically add the current parent context (if it exists) as a link.

```csharp
namespace System.Diagnostics;

public class ActivitySource
{
    public Activity? CreateRootActivity(..., bool linkToCurrentTrace = false, ...) {}
    public Activity? StartRootActivity(..., bool linkToCurrentTrace = false, ...) {}
}
```

### API Usage

```csharp
var newRoot = mySource.StartRootActivity(..., linkToCurrentTrace: true, ...)
```

**Comment by alanwest** [comment]
Related #65528

**Comment by tarekgh** [comment]
@CodeBlanch @alanwest could you please merge the two issues and have one proposal satisfy the asks if there are any differences? I am closing this one and feel free to update the linked one https://github.com/dotnet/runtime/issues/65528. Thanks!
