### ISSUE TITLE
hostfxr_initialize_for_runtime_config fails with error code 0x80008093

### ISSUE THREAD

**Issue by MansenC** [dotnet/runtime#82670]
Hi,

unfortunately I have found only one topic on this error code that lead me to nowhere.
My scenario is the following: I have a host application written in C++ that is going to have to interface heavily with C# code. The C# assembly has multiple entry points for requests made by my host application and may also call back into the C++ domain. Therefor, for starting the native host I used `hostfxr_initialize_for_runtime_config_fn` to get a hostfxr_handle.

Now, during testing where I use an installed framework everything works fine. The issue arises when I try to test my application on a clean VM with the C# code published using a self-contained net6.0 runtime. I use `LoadLibrary` to load the hostfxr dll into my process, get the address to `hostfxr_initialize_for_runtime_config`. Following that, a call is made to that address with the path to my runtime config (as follows), nullptr and a pointer to the returned handle. This call does return the error code `0x80008093` as mentioned. The only issue I found regarding this error mentioned that it most likely means 'bad configuration' and I really wish I didn't have to rely on that second hand guess. The configuration looks as follows:
```json
{
  "runtimeOptions": {
    "tfm": "net6.0",
    "includedFrameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "6.0.0"
      }
    ],
    "configProperties": {
      "System.Reflection.Metadata.MetadataUpdater.IsSupported": false
    }
  }
}
```
This configuration looks fine to me, so I have several options I'd like to get clarified. Am I:
A) doing something unsupported/wrong? (Are there any other causes that can trigger this error)
B) is there some way of doing what I want to achieve that I'm completely overlooking?

Thank you in advance

**Comment by vitek-karas** [comment]
`hostfxr_intialize_for_runtime_config` does not support self-contained components. There are two main reasons for this limitation:
* SDK currently doesn't have a way to publish a self-contained "component" (so something which is NOT an app). It is technically possible to publish a library project as self-contained but the produced output is wrong in many ways and this is not a supported scenario for the SDK. (There's also lot of questions to answer what does it even mean to produce a self-contained component)
* .NET supports only one runtime in any given process and having a self-contained component would mean that each component comes with its own runtime, so only one could ever be loaded.

The way to do what you want currently is to build the managed code as an app (as that is the only supported way to produce self-contained anything with the SDK). Use `hostfxr_initialize_for_dotnet_command_line` to load it. Then you can use the `hostfxr_get_runtime_delegate` to get the managed entry points, there's nothing forcing you to call `hostfxr_run_app`.

You might also want to consider NativeAOT as that has a direct support for building self-contained components with native exports.

**Comment by MansenC** [comment]
Thank you very much, works like a charm. For anyone stumbling across this issue, [here is a list of all error codes](https://github.com/dotnet/runtime/blob/main/docs/design/features/host-error-codes.md) one may stumble across their journey through .NET hosting land (since for some reason Google didn't even provide me with that document when I searched for the error codes)

**Comment by vitek-karas** [comment]
Sorry I didn't link that list myself - thanks!

For completeness - here's the design doc for the native hosting, contains most of the info above: https://github.com/dotnet/runtime/blob/main/docs/design/features/native-hosting.md
