### ISSUE TITLE
System.Net.MailAddress.TryCreate parses input with spaces into a valid email address

### ISSUE THREAD

**Issue by AachoLoya** [dotnet/runtime#82689]
### Description

https://learn.microsoft.com/en-us/dotnet/api/system.net.mail.mailaddress.trycreate?view=net-6.0

Spaces are Not allowed in email address. However, if you pass input with space in it e.g. "testing address@hotmail.com". This method succeeds and returns "address@hotmail.com" as output.

### Reproduction Steps

Pass any text with spaces and a valid email address E.g.
"testing address@hotmail.com"
"This is not a valid email@microsoft.com"
"This is also not a valid error@outlook.com email address"

### Expected behavior

All three of those inputs should cause TryCreate to return false

### Actual behavior

It returns true in all cases with output:
"address@hotmail.com"
"email@microsoft.com"
"error@outlook.com"

### Regression?

No Idea

### Known Workarounds

Currently manually checking input for spaces before calling this API.

### Configuration

Which version of .NET is the code running on?
.Net 6

What OS and version, and what distro if applicable?
Windows 10 22H2

What is the architecture (x64, x86, ARM, ARM64)?
x64

Do you know whether it is specific to that configuration?
Not sure

**Comment by CarnaViire** [comment]
Triage: this seems to be an easy fix. We are open for contributions. Not critical, so putting to Future

**Comment by heathbm** [comment]
Regarding text being in front of a valid email address. This comment: https://github.com/microsoft/referencesource/blob/51cf7850defa8a17d815b4700b67116e3fa283c2/System/net/System/Net/mail/MailAddressParser.cs#L224 mentions that `a comment, whitespace, an expected angle bracket, a quote for the display-name, or an expected comma` could be expected in front of the email address, separating it from the display name.

So, given "This is not a valid email@microsoft.com". We currently get:
- MailAddress.Address: "email@microsoft.com"
- MailAddress.DisplayName: "This is not a valid"

I would be happy to try to contribute a fix. However, I am a little unclear if the code comment is inaccurate (regarding whitespace), or if the current behavior is not an issue.

**Comment by CarnaViire** [comment]
Thanks for the info @heathbm!

Indeed, [RFC 5322](https://www.rfc-editor.org/rfc/rfc5322#section-3.4) states that mail address can have an optional display name before it -- and while the correct format would enclose display name in quotes and the actual address in angular brackets (`"John Doe" <johndoe@example.com>`), RFC mentions that there exist some legacy implementations which don't do that (neither `"..."` nor `<...>`).

I believe we are RFC-compliant, so I will close this issue.

P.S.: "This is also not a valid [error@outlook.com](mailto:error@outlook.com) email address" is not a valid address by RFC though -- but MailAddress does not accept such input.
