### ISSUE TITLE
Convert Georgian Year to solar year does not work on linux

### ISSUE THREAD

**Issue by mahdiyar021** [dotnet/runtime#82681]
### Description

hello
typically , i use .ToString(new CultureInfo("Fa-IR")) to Convert  Georgian Year to Solar Year on Datetime . this is work on my windows system but when i switch to linux server(cent os 8) the Output Remain Georgian Year .
I used Another class(PersianCalneder) for fix this issue and it works In correct way on linux,

### Reproduction Steps

// my code 
string secretariatDateTime =deceasedDocument.Corresponse.SecretariatDateTime.ToString(new CultureInfo("Fa-IR"));

### Expected behavior

string solarDateTime =DateTime.Pase("2014/08/16").ToString(new CultureInfo("Fa-IR"));
// output 1393/5/25 00:00:00

### Actual behavior

string solarDateTime =DateTime.Pase("2014/08/16").ToString(new CultureInfo("Fa-IR"));
// output 2014/08/16 00:00:00 (on linux)

### Configuration

dotnet version is 7.0.1
linux centos 8
x64

**Comment by tarekgh** [comment]
I quickly looked at Centos OS and I found the ICU there not setting the `PersianCalendar` as the default calendar to the `fa-IR`. So by default it uses the `GregorianCalendar` as teh default calendar there. You can work around this easily by manually setting the `PersianCalendar` as the default calendar in the created culture object. You can do the following:

```C#
        var ir = new CultureInfo("Fa-IR");
        ir.DateTimeFormat.Calendar = new PersianCalendar(); // This what will make it work.
        Console.WriteLine($"{ir.DateTimeFormat.Calendar}: {DateTime.Parse("2014/08/16").ToString(ir)}");
```

Side note, Centos 8 is not supporting OS any more https://learn.microsoft.com/en-us/dotnet/core/install/linux-centos#supported-distributions. But the issue you have reported still reproduces on Centos 7.
