### ISSUE TITLE
[wasi][mono] Support targeting wasi in AOT compiler

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#82691]
The wasm AOT compiler currently only has support for the wasm32-unknown-emscripten llvm tripple. We need to support wasm32-unknown-wasi as a target as well

**Comment by lewing** [comment]
Wasi aot is currently blocked on the lack of either c++ or wasm exception handling support in any of the wasi runtimes

**Comment by RReverser** [comment]
Re:blocker - could it do the same thing Blazor did with https://github.com/dotnet/runtime/pull/52883 and leave such methods interpreted?

**Comment by vargaz** [comment]
Thats possible, but too many perf critical methods in .net have clauses, and the transitioning in/out of the interpreter is also bad for performance.

**Comment by RReverser** [comment]
Sure, but it would be at least a working option for the interim since Emscripten's C++ exceptions rely on JS and none of WASI runtimes support WASM EH.

Despite the switching, I'm sure it would be still faster than fully non-AOT code.

**Comment by RReverser** [comment]
I was going to say that another option could be to rewrite either Wasm or IL, but I see that was already discussed before and the solution above is what Blazor settled on, so it would probably work here too with similar caveats.

**Comment by RReverser** [comment]
OTOH, as I now remember from discussion in NativeAOT-LLVM project, one other option is Node.js which supports both WASI and Wasm EH already.

Perhaps it would be possible to add Wasm EH support to Mono now, even if it can be only used with one runtime (Node.js) for now?

**Comment by vargaz** [comment]
So it looks like node can run wasm, probably EH as well, the problem is that wasi-sdk doesn't support c++ exception handling which mono needs to support wasm EH.

**Comment by RReverser** [comment]
There have been some updates since - have you seen https://github.com/dotnet/runtimelab/pull/2387 and related docs?

NativeAOT-LLVM went with the rewriting approach after all, and it looks quite promising - most promising probably, given the state of WASI SDK and engines for now.

I know impls differ quite a lot, but maybe it's possible to borrow some ideas.

**Comment by RReverser** [comment]
> So it looks like node can run wasm, probably EH as well, the problem is that wasi-sdk doesn't support c++ exception handling which mono needs to support wasm EH.

Oh, also - you could use Emscripten instead of WASI SDK. It supports both Wasm EH and WASI (via `-s PURE_WASI`) - a bit limited, but should be easy to shim any missing imports, so it allows to compile WASI programs with Wasm EH already.

**Comment by lewing** [comment]
We're looking into exception handling in AOT codegen that doesn't require wasm EH or emcc++ compiler style compiler support but any codegen that doesn't have runtime support is going to be extremely suboptimal.

**Comment by RReverser** [comment]
> but any exception codegen that doesn't have runtime support is going to be extremely suboptimal.

I imagine if will be still better than the JS-based Emscripten EH.

Either way, anything that prevents running the interpreter for majority of code would already be helpful. We are currently looking more closely at using NativeAOT-LLVM as an experimental option. 

For some scenarios we found codegen generated by if 2 orders of magnitude (~600x) faster than the default Mono interpreted output which makes a huge difference, especially for server side where WASI / pure Wasm is most commonly needed and where performance tends to be more critical. But it's a risky option as it's an experimental project and currently builds only on Windows, so having a regular AOT that gets even somewhere halfway would already be a safer and better option.

**Comment by lewing** [comment]
This is done at the base level, issues should be opened for problems.
