### ISSUE TITLE
Changing collection in CollectionChanged event results in exception

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#82699]
### Description

If you change the collection within `CollectionChanged` event of an `ObservableCollection` an exception is thrown: `Cannot change ObservableCollection during a CollectionChanged event`.

Which at first makes sense and is probably by design to avoid ending in a loop it simply block us from making SAFE changes to the collection which don't end in a loop. Consider the following pseudo code:

```C#
var collection = new ObservableCollection<int>() { 0, 1, 2, 3, 4}

collection.CollectionChanged += (e, s) => {
	if (s.Action == System.Collections.Specialized.NotifyCollectionChangedAction.Add) {		
		collection.Move(collection[1], 0);
	}
};
collection.Add(5);
```

This code is absolutely safe to execute. It doesn't end in a loop. But still an exception is thrown. One way around is to move the modification to another thread:

```C#
var collection = new ObservableCollection<int>() { 0, 1, 2, 3, 4}

collection.CollectionChanged += (e, s) => {
	if (s.Action == System.Collections.Specialized.NotifyCollectionChangedAction.Add) {		
		Bla();
	}
};
collection.Add(5);

async void Bla() {
	Application.Current.Dispatcher.Invoke(() => {	
		collection.Move(collection[1], 0);
	}, System.Windows.Threading.DispatcherPriority.Background);
}
```

I dont think changing it would be a breaking change because no existing real world code looks for, and handle, that specific exception. 
Instead of throwing an exception, a warning in VS analyzer might be better if possible. Otherwise just have trust in developers to not write silly looping code. 

An exception shouldn't be used as a warning like it is now. For example there are many scenarios where a developer could produce an infinite loop on using events, see https://github.com/dotnet/wpf/issues/7575#issuecomment-1445772847 but in none of them such an exception is thrown. For a good reason, just because you could write code which loops it doesn't mean you have to and there are scenarios where you don't do.

### Configuration

.NET 6

### Other information

Originally posted in WPF repo https://github.com/dotnet/wpf/issues/7575 but it has been said code is within .NET runtime.

**Comment by miloush** [comment]
I don't consider changing collection during the event safe. That event is informing any subscribers that the collection changed at a particular state of the collection. If you could change it on the way, handlers would get different state and the behavior would depend on the order they would be invoked. Furthermore, the parameters of `NotifyCollectionChangedEventArgs` become invalid after such change and any subsequent handlers would get useless arguments.

**Comment by Clockwork-Muse** [comment]
> One way around is to move the modification to another thread

`ObservableCollection<T>` isn't threadsafe, so that's (hopefully) going to explode in short order.

**Comment by Symbai** [comment]
> so that's (hopefully) going to explode in short order.

It's not.

> I don't consider changing collection during the event to be safe

I do. And it doesn't explain why other events don't have such a specific exception. I mean what you say can be applied to many events. So either all of them are should throw exceptions as well, or the exception on ObservableCollection should be removed.

**Comment by Clockwork-Muse** [comment]
> It's not.

... then you're courting disaster and some hard/impossible to diagnose bugs.  That you don't know you haven't hit it yet doesn't mean you won't (or haven't hit it and just not noticed)..

**Comment by Symbai** [comment]
So I'm not allowed to change collection within colllection changed event and you both say this is like it must be. Then tell me why am I allowed to change IsEnabled state within IsEnabledChanged event? Why am I allowed to change Size within SizeChanged event? Why am I allowed to change XY within XYChanged event? Why do they not throw any exceptions?

@eiriktsarpalis @Clockwork-Muse

**Comment by miloush** [comment]
@Symbai as suggested above, one difference is that the arguments to the event handlers you named will remain valid to all handlers regardless of your changes
