### ISSUE TITLE
TypeLoadException when instance of type "A" with a field(s) of type "GenericType<A>" 

### ISSUE THREAD

**Issue by BinToss** [dotnet/runtime#82701]
### Description

The use-case is primarily unmanaged, unmarshalled, no-COM, Windows interop across WOW64 boundaries.

```cs
internal struct UIntPtr64<T> where T : unmanaged
{
    public ulong Value;

    public static implicit operator UIntPtr64<T>(ulong v) => new() { Value = v };
    public static implicit operator ulong(UIntPtr64<T> v) => v.Value;

    public static explicit operator UIntPtr64(UIntPtr64<T> v) => v.Value;
}

internal readonly struct LIST_ENTRY64
{
    internal readonly UIntPtr64<LIST_ENTRY64> Flink;
    internal readonly UIntPtr64<LIST_ENTRY64> Blink;
}
```

If an instance of LIST_ENTRY64 (or a Type containing it) is created, the function or method that contains the instantiation will throw a System.TypeLoadException.

If this unhandled exception is intentional, a more informative exception type should be used and a code refactor suggestion via Roslyn rules would be appreciated.
If the exception is unexpected and it *should* work, then .NET SDK and/or Runtime will need to be investigated for a solution.
If the exception is unexpected and it should *not* have compiled, then .NET SDK and/or Roslyn will need to be investigated for a solution.

### Reproduction Steps

```cs

int main()
{
  
  void WriteDefaultListEntry()
  {
    var entry = default(LIST_ENTRY64);
    string outStr = $"\
Flink: {entry.Flink.Value}\n
Blink: {entry.Blink.Value}";
    Console.Out.WriteLine(outStr);
  }

  return 0;
}

internal struct UIntPtr64<T> where T : unmanaged
{
    public ulong Value;

    public static implicit operator UIntPtr64<T>(ulong v) => new() { Value = v };
    public static implicit operator ulong(UIntPtr64<T> v) => v.Value;

    public static explicit operator UIntPtr64(UIntPtr64<T> v) => v.Value;
}

internal readonly struct LIST_ENTRY64
{
    internal readonly UIntPtr64<LIST_ENTRY64> Flink;
    internal readonly UIntPtr64<LIST_ENTRY64> Blink;
}
```

### Expected behavior

Because the runtime allows fields of type `A*` inside a struct of type `A`, it is expected that one could emulate this behavior using generic types for situations in which pointers of a different bit-width are required.

### Actual behavior

When it is time for `WriteDefaultListEntry()` to begin, the runtime will throw the unhandled exception `System.TypeLoadException` with the message "Could not load type 'NewAssembly.LIST_ENTRY64' from assembly ''NewAssembly, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

### Configuration

|    | Version/Value
| -- | ---------
| .NET Runtime/AppHost | 6.0.14
| .NET SDK | 7.0.201
| Windows 11Pro | 22H2 (22621.1265)
| CPU arch | x64

**Comment by teo-tsirpanis** [comment]
Indeed.

**Comment by BinToss** [comment]
Ah, I see. This was a failure on my part to extensively search for related issues before opening a new one.
Thank you for linking that one!


Have a good day!
