### ISSUE TITLE
NET 7 new GC high lock contention

### ISSUE THREAD

**Issue by MichaelLogutov** [dotnet/runtime#82715]
### Description
In company we have a C# log parser that handles ~70k RPS of logs as json strings from kafka, parsing them, modifying and writing them in batches to elasticsearch (ELK). After upgrading to net 7 we saw considerable performance degradation in parsing and export code paths (we have metrics for each parrt of the log processing flow inside app).

### Regression?

After upgrading to net 7 I've tried running with different environment variables (like PGO and server GC) and also tried to remove them (meaning using defaults) - nothing helped until I've switched back to old GC using `COMPlus_GCName=libclrgc.so` - this led app to get back to the same performance it was in net 6.

### Analysis

I've collected traces from net 6 and various env configuration of net 7 and I saw considerable lock contention in net 7 with new GC.

For example, this is what "baseline" net 6 looks like with following envs
```
ENV DOTNET_gcServer=0
ENV DOTNET_GCHighMemPercent=4B
ENV DOTNET_TieredPGO=1
ENV DOTNET_ReadyToRun=0
ENV DOTNET_TC_QuickJitForLoops=1
```
![image](https://user-images.githubusercontent.com/405031/221615161-db6983d9-7f17-4bae-be02-9a51415bb1a7.png)

And this is net 7 with no additional environment variables set (log parsing and exporting with gzip compression was severely hindered):
![image](https://user-images.githubusercontent.com/405031/221615553-fbe0d4b5-c6fc-4a3f-80c4-b5bb5286aeba.png)

And this is net 7 switched to old GC (performance back as it was on net 6):
![image](https://user-images.githubusercontent.com/405031/221615689-0ed88c0e-85b5-4c7a-b244-cda89052d1e7.png)

I can provide all nettrace files if needed (or dotCover converted files which are a lot smaller).

**Comment by mangod9** [comment]
Hello @MichaelLogutov, please share the traces so we could take a look. Just confirming that you are running both scenarios with similar config (appears to be with WKS gc etc?). Thx

**Comment by MichaelLogutov** [comment]
Here they are: https://disk.yandex.ru/d/RXmhP6WypiwDtw
I've also explained configurations in readme file

**Comment by PeterSolMS** [comment]
@MichaelLogutov, thank you for the traces. I looked at them, but cannot figure out why the newer GC could somehow cause more lock contention. According to the traces, the GC pauses are smaller with the newer GC, albeit at lower overall throughput.

**Comment by MichaelLogutov** [comment]
@PeterSolMS Maybe you right - it's just saw high lock contention in trace overall statistics. It's not that it 200%, but it's noticeable and I didn't saw anything else. And because switching to old GC solved the performance problem I linked two those anomalies together.

**Comment by mangod9** [comment]
Adding @kouvel, since this doesnt look to be GC related. Might be something related to IO Completion changes in 7.

**Comment by kouvel** [comment]
> Might be something related to IO Completion changes in 7.

These look like traces on Unix, the IO completion changes in .NET 7 only affect Windows.

It looks like thread pool threads are spending most of their time waiting. There are a few stack frames missing to make that clear in the .NET 6 trace, but that is the most likely case. Traces taken with dotnet-trace include samples of threads that are blocked, so the inclusive times would include CPU time and blocked time, so it becomes difficult to tell where the CPU time is going. For on-CPU analysis, [perfcollect](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/trace-perfcollect-lttng) may be a better option to see where the extra CPU time is being spent, as it would only sample threads that are on the CPU, and the traces would also include native stack frames.

In the event stats I didn't see any significant contention or heavy burstiness in the thread pool.

I see that more time spent in `System.IO.Compression!Deflater.Deflate` in the .NET 7 defaults trace, which appears to spend most of its time in native code, I suspect that would be on-CPU time.

.NET 6 caller stack:

```
Name                                                        	Inc %	      Inc
 System.IO.Compression!Deflater.Deflate                     	  4.3	   38,778
+ System.IO.Compression!Deflater.ReadDeflateOutput          	  4.3	   38,778
 + System.IO.Compression!Deflater.GetDeflateOutput          	  3.3	   29,533
 |+ System.Text.Json!System.Text.Json.Utf8JsonWriter.Flush()	  3.2	   29,096
```

.NET 7 caller stack:

```
Name                                                          	Inc %	      Inc
 System.IO.Compression!Deflater.Deflate                       	 12.5	   55,482
+ System.IO.Compression!Deflater.ReadDeflateOutput            	 12.5	   55,482
 + System.IO.Compression!Deflater.GetDeflateOutput            	  9.5	   42,443
 |+ System.IO.Compression!DeflateStream.WriteDeflaterOutput   	  9.5	   42,443
 | + System.IO.Compression!DeflateStream.WriteCore            	  9.5	   42,443
 |  + System.Text.Json!System.Text.Json.Utf8JsonWriter.Flush()	  9.4	   41,734
```

Is it possible that the app was doing different work between these two traces?

**Comment by MichaelLogutov** [comment]
> Is it possible that the app was doing different work between these two traces?
Not likely. The code was processing logs from the same kafka topic at more than 40k RPS rate - each log is somewhat unique yes, but they are quite similar in their structure. And the sheer amount of them makes it quite representable from statistics standpoint. And it was very consistent - each time I've tried net 7 with different environment variables I see degradation (that is until switching to old GC). And each time after that I've rolled back net 6 and saw processing time back to normal every time. And I've waited couple of minutes before collecting perf traces.

**Comment by JohannesEH** [comment]
@MichaelLogutov did you ever figure out what happened, or did you just keep on .net 7? Have you tried the same on .net 8?

**Comment by MichaelLogutov** [comment]
I've switched to .net 8 and removed any environment variables - so far everything works fine.

**Comment by mangod9** [comment]
Ok good to know. Will close for now, please reopen if there is something to investigate. Thanks
