### ISSUE TITLE
Blazor WebAssembly suffers memory leaks from compiled lambda expressions

### ISSUE THREAD

**Issue by DouglasKSmith** [dotnet/runtime#82716]
### Description

We have a Blazor WebAssembly app whose memory keeps increasing until it hits the 2 GB limit, then silently crashes. We've narrowed down the main cause of the leak to [compiled lambda expressions](https://learn.microsoft.com/en-us/dotnet/api/system.linq.expressions.expression-1?view=net-6.0).

### Reproduction Steps

The following code may be used to reproduce the memory leak. It can be wired up as the event handler of a button on a page. When left running in the active tab (in the foreground), it leaks around 46 MB of memory a minute, causing the 2 GB limit to be reached (and the app to crash) in 47 minutes.

```csharp
private async Task RunMemoryLeakTestAsync()
{
    long total = 0;

    for (long i = 0; i < 2_000_000_000; i++)
    {
        Expression<Func<long, long>> expression = x => x + x;
        var func = expression.Compile();
        total += func(i);

        if (i % 1_000 == 0)
            await Task.Delay(millisecondsDelay: 100);  // keep app responsive and give GC time to run
    }
}
```

### Expected behavior

The online consensus appears to be that compiled lambda expressions [shouldn't cause memory leaks](https://stackoverflow.com/q/43041190/14207973) in .NET. (That answer was directed at .NET proper, not Blazor WebAssembly.)

### Actual behavior

Compiled lambda expressions cause a memory leak in Blazor WebAssembly. The app would consequently silently crash once the 2 GB limit is reached.

![image](https://user-images.githubusercontent.com/97787672/222121532-e5942353-7ae4-4fd2-a213-27c1e5a69398.png)

### Regression?

Compiled lambda expressions [don't cause memory leaks](https://stackoverflow.com/q/43041190/14207973) in .NET proper.

### Known Workarounds

The only workaround we have is to avoid using compiled lambda expressions in Blazor WebAssembly.

### Configuration

Blazor WebAssembly, compiled on .NET 6.0 using Release configuration.
Run in Google Chrome 110.0.5481.104 (64-bit) without debugging, on Windows 10.

### Other information

May be related to #62054. However, we've given our issue a quick test on .NET 7.0, and it still occurred.

**Comment by jtorjo** [comment]
I am really interested in this, but I don't really think it causes any leaks:

    private int RunGC() {
        var watch = Stopwatch.StartNew();
        GC.Collect();
        GC.WaitForPendingFinalizers();
        GC.Collect();
        return (int)watch.ElapsedMilliseconds;
    }
    private async void Page_Loaded(object sender, RoutedEventArgs e) {
        //await TestCreateSetPropertyAndDestroy();
        //Console.WriteLine("test ended");
        await Task.Delay(10000);
        long total = 0;
        var count = 500_000_000;

        RunGC();
        double gcMemoryMB = 0;
        gcMemoryMB = (double)GC.GetTotalMemory(false) / (1024d * 1024d);
        Console.WriteLine($"START mb={gcMemoryMB}");

        for (long i = 0; i < count; i++)
        {
            Expression<Func<long, long>> expression = x => x + x;
            var func = expression.Compile();
            total += func(i);
            if (total > 1_000_000_000)
                total = 0;

            if (i % 100_000 == 0) {
                var gcTime = RunGC();
                gcMemoryMB = (double)GC.GetTotalMemory(false) / (1024d * 1024d);
                Console.WriteLine($"i={i} mb={gcMemoryMB} time={gcTime}");
                await Task.Delay(millisecondsDelay: 100);  // keep app responsive and give GC time to run
            }
        }
        gcMemoryMB = (double)GC.GetTotalMemory(false) / (1024d * 1024d);
        Console.WriteLine($"END before gc mb={gcMemoryMB}");

        RunGC();
        gcMemoryMB = (double)GC.GetTotalMemory(false) / (1024d * 1024d);
        Console.WriteLine($"END mb={gcMemoryMB}");
        RunGC();
        RunGC();
        gcMemoryMB = (double)GC.GetTotalMemory(false) / (1024d * 1024d);
        Console.WriteLine($"END 2 mb={gcMemoryMB}");
    }

I've run this test in .net7 + webassembly -- manually calling the GC.Collect() will show you stuff is properly collected.
I' haven't tested .net6, but I'm almost certain it'll behave the same way.

**Comment by lewing** [comment]
We've made some fixes here for RC1 and believe it is resolved.  Please reopen if you are still seeing problems
