### ISSUE TITLE
[wasm] WBT: Update Skiasharp needed that's built with a newer emscripten

### ISSUE THREAD

**Issue by radekdoulik** [dotnet/runtime#82725]
The tests referencing SkiaSharp fail, because newer emscripten (like 3.1.30 we want to use) changed the `time_t` type size to 64 bits from previous 32 bits size.

We will disable these, until we can use SkiSharp built with newer emscripten.

**Comment by radical** [comment]
The latest they have is `3.1.12`, but we can open an issue to get a build for 3.1.30 too.

**Comment by mattleibow** [comment]
Thanks for the issue, SkiaSharp should now have the bits for emscripten 3.1.34. I have pushed them out to nuget and should appear soon: v2.88.4-preview.76

**Comment by radekdoulik** [comment]
This is fixed by https://github.com/dotnet/runtime/pull/87830
