### ISSUE TITLE
Implementation of Parallel.ForEachAsync for .NET Standard 2.0

### ISSUE THREAD

**Issue by ashutoshsuman99** [dotnet/runtime#82727]
I am trying to implement Parallel.ForEachAsync for .NET standard 2.0, but many of the features of Task and TaskCompletionSource being used in the implementation of Parallel.ForEachAsync of .NET 6.0 are not compatible with .NET standard 2.0. Since, the implementation is to be used in IO heavy operation using partitions doesn't fit the answer as DOP can be underutilized in this case and many other solutions don't have good cancellation/Loop break support. Therefore, I am looking for an implementation which is very close to the Parallel.ForEachAsync of .NET 6 and can also work in .NET standard 2.0. 

(We have to work with .NET standard as the class library in it is to be used for different types of runtimes like .NET framework and .NET core)

**Comment by stephentoub** [comment]
> but many of the features of Task and TaskCompletionSource being used in the implementation of Parallel.ForEachAsync of .NET 6.0 are not compatible with .NET standard 2.0

Which features?

- You can replace ArgumentNullException.ThrowIfNull with a normal argument null check
- You can use the generic TaskCompletionSource instead of the non-generic.
- You can reference the Microsoft.Bcl.AsyncInterfaces and System.Threading.Tasks.Extensions nuget packages to pull in types like IAsyncEnumerable and ValueTask
- You can use CancellationToken.Register instead of CancellationToken.UnsafeRegister
- You can use a different overload of ThreadPool.QueueUserWorkItem that doesn't care about IThreadPoolWorkItem and just delete that interface implementation

**Comment by ashutoshsuman99** [comment]
So the replacement suggested I have done the following:

1. Using Generic TaskCompletionSource: I have used `TaskCompletionSource<bool>` as we are returning Task at the end instead of Task<TResult> we don't have any particular use of TrySetResult function so adding bool values i.e. `TrySetResult(true)` was the easiest way.

2. For using a different overload od `ThreadPool.QueueUserWorkItem`, since in .NET standard we can only work with `QueueUserWorkItem(WaitCallback callBack, object state)` this, there I have done the following
```
_ = ThreadPool.QueueUserWorkItem((_) => Execute(), this);
```
Please correct me if I have misjudged anything here. Also, by default .NET Standard 2.0 uses C# 7.3 which doesn't support static asynchronous functions. So, what kind of effect will be switching from static async to a direct async function will have here?

**Comment by stephentoub** [comment]
> TrySetResult(true) was the easiest way.

Yup.

> _ = ThreadPool.QueueUserWorkItem((_) => Execute(), this);

This would be better as:
```C#
ThreadPool.QueueUserWorkItem(s => ((ForEachAsyncState<T>)s).Execute(), this);
```

> So, what kind of effect will be switching from static async to a direct async function will have here?

It will have zero impact on the resulting code. `static` when applied to lambdas only serves to have the compiler warn you if you try to close over instance state; it has no affect on code generation.  So by removing the static, you simply lose that checking, such that if you accidentally change the code to close over instance state, you'll be silently introducing additional allocation.

**Comment by theodorzoulias** [comment]
@ashutoshsuman99 I have posted [here](https://stackoverflow.com/questions/11564506/nesting-await-in-parallel-foreach/65251949#65251949 "Nesting await in Parallel.ForEach") a `Parallel_ForEachAsync<T>` implementation compatible with the .NET Framework, that replicates quite closely the behavior of the native [`Parallel.ForEachAsync`](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.parallel.foreachasync). It falls in the category "code found on the internet", so there are no tests and no guarantees. On the other hand adapting manually the .NET 7 [source code](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Threading.Tasks.Parallel/src/System/Threading/Tasks/Parallel.ForEachAsync.cs) to the .NET standard 2.0 specification, is not completely risk-free either.

**Comment by NN---** [comment]
You can use [CodeJam](https://www.nuget.org/packages/CodeJam) which has [ForEachAsync[(https://github.com/rsdn/CodeJam/blob/master/CodeJam.Main/Threading/TaskHelper.ForEachAsync.cs#L99).

**Comment by ashutoshsuman99** [comment]
Thanks @stephentoub for the clarification.
@NN--- and @theodorzoulias Thank you for your suggestion on other different approaches. Will take a look at those and then decide which one fits our case best. 

Closing this issue as my ask has been answered.

**Comment by Joe4evr** [comment]
> C# 7.3 which doesn't support static asynchronous functions

I'm still puzzled by this statement. If you're talking about regular `static` methods, there's nothing prohibiting them from being asynchronous.

**Comment by theodorzoulias** [comment]
@Joe4evr they probably mean the [static local functions](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/static-local-functions), that were introduced in C# 8.
