### ISSUE TITLE
Proxy authentication seems to not work with proxies that are not Fiddler

### ISSUE THREAD

**Issue by aCastrooo** [dotnet/runtime#82743]
### Description

It seems that proxy authentication is not working correctly when using different proxies. We tested using mitmproxy and Fiddler. Any request sent through Fiddler works as expected. Any request with mitmproxy does not. It works with Fiddler, not registered as a system proxy, using the environment variables explicitly, but doesn't with mitmproxy under the exact same conditions. This is also a problem on multiple platforms. This was corroborated by colleagues who were able to run the same repro steps on macos instead of Windows. From what it looks like, the client might be getting confused with how mitmproxy returns the 407 (by maybe keeping the connection open?). It is hard to say without being able to debug into dotnet. This is the Windows stack trace for a simple get call to http://www.bing.com/:

```
Unhandled exception. System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
---> System.TimeoutException: A task was canceled.
---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Program.<Main>$(String[] args) in C:\Users\acastronuovo\OneDrive - Microsoft\Documents\testCmdLine\HtpTest\Program.cs:line 1
   at Program.<Main>(String[] args)
```

 Succeeds with Fiddler:
![Screenshot_20230227_025433](https://user-images.githubusercontent.com/6385044/221708047-9b2f21fd-64ee-41a7-89f9-92015471d1bb.png)

Proxy environment vars set before running the console app:
```
PS C:\Users\acastronuovo\OneDrive - Microsoft\Documents\testCmdLine\HtpTest\bin\Debug\net7.0> gci env:* | sort-object name | findstr "proxy"
http_proxy                     http://any:any@127.0.0.1:9999
https_proxy                    http://any:any@127.0.0.1:9999
```

Also, apologies if this isn't the correct repo to open the issue in, I was digging through several other dotnet repos and this one seemed the most appropriate.

### Reproduction Steps

Create a .NET console app with a single line:     
`await new HttpClient().GetAsync("https://www.bing.com"); `

- build the dotnet project as normal
- Set http[s]_proxy=http://any:any@localhost:9999
- Start up the proxy on the correct port. For repro I was using proxy authentication user:pass set to "any:any".
- Run the built console app: `.\httpTest.exe` (or whatever you decide to call the project).

For mitmproxy: It will hang until it times out after the proxy returns the 407. 
For Fiddler: the proxy will send an initial 407, and then send the correct proxy auth headers, and return 200.

### Expected behavior

One of two behaviors should be expected:

1. The proxy sends a 407 back to the client and the client re-sends the request with the correct auth headers.
2. The client sends the proxy auth headers on the first attempt if the environment variables are explicitly set. 

### Actual behavior

Actual behavior hangs on 407, eventually timing out. Stack trace for Windows in the description. 

### Configuration

Running .net 7.0.103
Ran using Windows 11 x64 arch.
For mac, I am not sure what my colleague's set up was.

**Comment by wfurt** [comment]
can you get packet captures @aCastrooo? (or do you have public instance that can be used for testing?)

**Comment by aCastrooo** [comment]
I don't have a public instance or like, a special environment set up. Do you want me to attach the packets @wfurt?

**Comment by wfurt** [comment]
yes, that would be good start. It would be quite difficult to investigate without some insight. I know it is also tested with Squid so Fiddler is not the only one that works. 

Actually, can you also try to set the proxy to `127.0.0.1` instead of `loopback`?

**Comment by aCastrooo** [comment]
@wfurt I have my proxy is set to 127.0.0.1 explicitly, you can see it in the environment variables that I printed out. I should be able to get some more info for you this week, sorry about the delay.

**Comment by CarnaViire** [comment]
@aCastrooo can you please send us the packet capture and additional info?

**Comment by hackren** [comment]
Using a proxy with credentials, using wireshark to capture packets, it can be found that the first request does not carry the Proxy-Authorization header, and when the request returns 407, it will be requested again and carry Proxy-Authorization

There are some drawbacks to this, for example
1. Multiple negotiation requests affect speed
2. Most proxy servers work normally, but some proxy server programs do not accept secondary negotiation

I discovered this problem many years ago, unfortunately it has not been solved by net7, and I hope the team can improve this problem.

**Comment by hackren** [comment]
Setting HttpRequestMessage.Headers.ProxyAuthorization will work, but the Proxy-Authorization header will be carried to the target site

**Comment by wfurt** [comment]
This is not different to authentication to the server. Client will send credentials only when asked for to prevent leaking the credentials. And without the `407` you do not know what scheme to use and defaulting to `Basic` is bad option IMHO. Since that connection would typically be shared to many requests the overhead should be small. 

It seems like the lack of sending 407 or not accepting credentials after that is bug in the proxy.
