### ISSUE TITLE
Fatal error. Internal CLR error. (0x80131506) in .NET 7 during GC

### ISSUE THREAD

**Issue by Georgiks** [dotnet/runtime#82753]
### Description

We have an application that rarely crashes with CLR error, with stacktrace often ending to place where List or other collections needs to be resized (and memory allocated).
I managed to collect many crash dumps and most of them point to crash during GC. In the other cases the stacktrace shows it works with object that reports error during heap verification (`ValueTracker` class, will get to that).

I tried to collect as much information in similar manner as requested in this issue #78206.

After setting `DOTNET_HeapVerify` env var and reproducing the issue:
```(7acc.246c): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
coreclr!MethodTable::SanityCheck+0x4:
00007ff9`ecfa21d8 4c8b4128        mov     r8,qword ptr [rcx+28h] ds:00000000`00000028=????????????????
```

![image](https://user-images.githubusercontent.com/19236717/221740722-1517ea42-3eec-4631-9d10-51cca6bb09d6.png)

!VerifyHeap results:
```
5:119> !verifyheap
Object 0000021a25166c48: Bad member 0000021A254C97E8 at 0000021A25168368.

Last good object: 0000021A25166C30.
Object 0000021a24e26690: Bad member 0000021A254C97E8 at 0000021A24E27DB0.

Last good object: 0000021A24E26670.
5:119> !do 0000021a25166c48
Name:        System.Collections.Generic.Dictionary`2+Entry[[System.IntPtr, System.Private.CoreLib],[Keen.VRage.Library.Memory.ValueTracker+Record, VRage.Library]][]
MethodTable: 00007ff990e060c8
EEClass:     00007ff990e06030
Tracked Type: false
Size:        13816(0x35f8) bytes
Array:       Rank 1, Number of elements 431, Type VALUETYPE (Print Array)
Fields:
None
5:119> !do 0000021a24e26690
Name:        System.Collections.Generic.Dictionary`2+Entry[[System.IntPtr, System.Private.CoreLib],[Keen.VRage.Library.Memory.ValueTracker+Record, VRage.Library]][]
MethodTable: 00007ff990e060c8
EEClass:     00007ff990e06030
Tracked Type: false
Size:        6328(0x18b8) bytes
Array:       Rank 1, Number of elements 197, Type VALUETYPE (Print Array)
Fields:
None
```

The CLR errors are always connected to `ValueTracker`:
```cs
public class ValueTracker
{
    private readonly Dictionary<IntPtr, Record> _records = new();

    ...

    private readonly struct Record
    {
        public readonly Type ObjectType;
        public readonly string? DebugName;

        ...
    }
}
```
The IntPtr is obtained by `Marshal.AllocHGlobal(sizeof(int));` method before adding it to the Dictionary

I'm new to WinDbg tool, if there is more information I could provide, let me know.

### Reproduction Steps

Very hard, I have to run my application around 20 times before I can get the CLR error. What we have however is parallel environment, however every parallel task work with its own local data, no instances are shared between different tasks.

### Expected behavior

No CLR error

### Actual behavior

A CLR error occasionally occurs when running the application

### Regression?

Although in active development, this application has run several months on .NET 6 without any CLR errors, so it might be a regression after moving to .NET 7

### Configuration

Windows 10 64-bit
.NET 7.0.3 version

**Comment by Feralnex** [comment]
I can reproduce it easily when running code from [here](https://github.com/Feralnex/MemoryManagementTest) - I'm messing around with unmanaged memory. It occurs frequently (not 100% of the time)...

**Comment by SuRGeoNix** [comment]
I think I'm having same or similar issue after updating VS 17.5.4/.NET 7.0.5.
I got an System.ExecutionEngineException (in Unknown Module).
I got a [dump](https://drive.google.com/file/d/1bILR7Hwl86LCBOHDKoy4ndvESmWN246c/view?usp=share_link) (154mb zipped, 1gb unzipped) if that helps.

**Comment by mangod9** [comment]
Need more info to investigate further.

**Comment by Georgiks** [comment]
Closing the issue, turned out to be other issue related to unmanaged calls
