### ISSUE TITLE
Idle application dies of OOM on Ubuntu 22.04 on .NET 7.0.2+

### ISSUE THREAD

**Issue by gregolsky** [dotnet/runtime#82763]
### Description

We have a number of low-end instances running Ubuntu 22.04. They sport 2 vcpus and 0.5GB RAM.
The application has been recently updated to .NET 7.0.2 and started some peculiar behavior.

On completely *idle* servers the managed memory metric starts to increase until the application is killed by OOM reaper.

```
Feb 27 13:30:02 ip-10-10-88-118 kernel: Out of memory: Killed process 498 (Raven.Server) total-vm:274342356kB, anon-rss:265784kB, file-rss:0kB, shmem-rss:7672kB, UID:1001 pgtables:3108kB oom_score_adj:0
Feb 27 13:30:01 ip-10-10-88-118 systemd[1]: raven.service: A process of this unit has been killed by the OOM killer.
...
Feb 27 13:30:02 ip-10-10-88-118 systemd[1]: raven.service: Main process exited, code=killed, status=9/KILL
Feb 27 13:30:02 ip-10-10-88-118 systemd[1]: raven.service: Failed with result 'oom-kill'.
```

It was not the case before on .NET 7.0.0 or 7.0.1.

After it's killed most of the time the memory does not increase in such manner anymore, but application acts as normal and goes back to usual Managed memory usage. Some instances need to die at least twice  to go back to normal behavior.

We determined that the memory is kept in GC, which for some reason ceases to run. Not sure why?

We have an endpoint to force GC cleanup and after calling it had quite a lot of memory cleaned up (for such an instance) e.g.:
```
{
	"BeforeGC": "358.6 MBytes",
	"AfterGC": "45.24 MBytes",
	"Freed": "313.36 MBytes",
	"DurationInMs": 807,
	"PinnedObjectsCount": 5,
	"FinalizationPendingCount": 1121,
	"PauseTimePercentage": "0.08%"
}
```
Afterwards the application continues to work as normal

When attempting `dotnet-gcdump` it immediately clears the GC contents freeing up the memory, so there's no way for us to check what it's been holding.

### Configuration

Ubuntu 22.04
kernel 5.15.0-1030-aws
2 vcpus 
0.5GB RAM

### Regression?

Yes, since 7.0.2. We tried 7.0.3 as well - same thing.
Worked OK before that version.

### Data

![image](https://user-images.githubusercontent.com/1541805/221854823-8d7d219c-42e4-48c0-8b9e-2b18bf7c3308.png)
![image](https://user-images.githubusercontent.com/1541805/221854893-90af1992-ccb9-4be9-a10c-f33998765a11.png)

gcdump done:
![image](https://user-images.githubusercontent.com/1541805/221855411-986b2443-1148-4aea-a8e8-476a602de757.png)

**Comment by gregolsky** [comment]
No, we don't have traces at this point. I'll try to get some more info -
wanted to start a discussion here.

If we had explicit allocations it would not clear the mem when we force run
GC, would it?

Also why would using gcdump tool clear most of that GC held memory?

wt., 28 lut 2023, 18:00 użytkownik Manish Godse ***@***.***>
napisał:

**Comment by mangod9** [comment]
ok, thanks -- traces would be helpful to diagnose further.

**Comment by gregolsky** [comment]
@mangod9 We obtained some traces for over a minute, however I'm afraid they might contain some confidential information. Would it be possible to share them privately with you?

I know there's a bunch of exceptions being thrown around our cgroups support, however I doubt this would gather up in GC this way would it without being cleaned and then killing the service due to OOM? Is there any special handling as far as exceptions are concerned?

![image](https://user-images.githubusercontent.com/1541805/223141633-7c6418a9-daed-4f04-aed9-061caef5d2b0.png)
https://github.com/ravendb/ravendb/blob/v5.4/src/Sparrow.Server/Platform/Posix/KernelVirtualFileSystemUtils.cs#L28

I really wonder why would the GC not be triggered at all and why would it stop to act this way after 2-3 restarts of the service.

**Comment by mangod9** [comment]
you could send me a link to my email (should be in my profile). Would be helpful to also get a comparison trace with 7.0.1 so we can compare them side by side. 

Also for the exceptions you are noticing above, do they only happen in 7.0.2 or occur with 7.0.1 as well?

**Comment by gregolsky** [comment]
Ok I'll send traces later today to your email.

Exceptions are thrown in our code, not in .NET.
We got our own code that checks some stuff in cgroups virtual fs.

wt., 7 mar 2023, 06:32 użytkownik Manish Godse ***@***.***>
napisał:

**Comment by gregolsky** [comment]
@mangod9 I sent you an email with the traces.

**Comment by danmoseley** [comment]
If you want to send info with the maximum confidentiality you can create a Visual Studio feedback issue indicating it's just being used to pass info for this issue and then share the ID in the issue. That is fully protected and compliant.

**Comment by gregolsky** [comment]
Manish, did you have a chance to take a peek in the traces I sent?


śr., 8 mar 2023, 16:47 użytkownik Dan Moseley ***@***.***>
napisał:

**Comment by Maoni0** [comment]
I didn't see any updates on this issue internally (and Manish is out of office this week) so I just took a quick look. none of the 3 traces you collected showed any GC events so they are not useful for explaining why the heap is at the size it's at. 

I would recommend following instructions described [here](https://github.com/Maoni0/mem-doc/blob/master/doc/.NETMemoryPerformanceAnalysis.md#How-to-collect-top-level-GC-metrics) to collect a top level GC trace for before and after. that way you also don't need to worry about privacy issues because the top level GC traces do not contain PII. gc-verbose is rarely ever useful. we don't need cpu sample profiles at this point. so really you just need to collect a top level trace only. keep in mind 2 things -

+ the trace should contain enough history, ie, don't start collecting it after the heap is already larger than what you expected. start collecting before that so we can see how it got to that size. this is very lightweight so you just start collecting when the process starts and stop it when the heap size is larger than what you expected.

+ collect one for before and after so we can compare

if you could share those traces I'd be happy to take a look.

**Comment by mangod9** [comment]
hi @gregolsky, were you able to collect more traces as Maoni suggested above?
