### ISSUE TITLE
System NuGet packages not up to date?

### ISSUE THREAD

**Issue by drauch** [dotnet/runtime#82770]
Hi!

1) [System.ComponentModel.Annotations](https://www.nuget.org/packages/System.ComponentModel.Annotations/) is still on 5.x, it has a preview for 6.x, I updated to .NET 7 today and expected a non-preview 7.x version. Is this version missing or is this package not "version number synced" with .NET releases and the similarities in version number is superficial?

2) [System.IO.FileSystem.AccessControl](https://www.nuget.org/packages/System.IO.FileSystem.AccessControl) is still on 5.x too, it also has multiple previews for 6.x, I updated to .NET 7 today and expected a non-preview 7.x version. Is this version missing or is this package not "version number synced" with .NET releases and the similarities in version number is superficial?

Best regards,
D.R.

**Comment by vcsjones** [comment]
>  updated to .NET 7 today and expected a non-preview 7.x version.

If you are running .NET 7 then you can just remove the `<PackageReference />` to those packages. The APIs provided by those pages are part of the Runtime / SDK.

**Comment by drauch** [comment]
Ah, great to know, thanks!

**Comment by vcsjones** [comment]
Seems like this has been answered then. I'm going to close this, but please feel free to re-open if there are unaddressed issues or concerns.
