### ISSUE TITLE
Unexpected ToString call upon adding item to dictionary

### ISSUE THREAD

**Issue by mbvyd** [dotnet/runtime#82784]
### Description

There is a class which has a dictionary in one field and custom object (composition) with overriden `ToString` - in another field. During adding item to dictionary it seems `ToString` is called on custom object. Which seems unexpected behaviour.

### Reproduction Steps

Here [demonstration repo](https://github.com/mbvyd/ListClearDemo).
To reproduce apply [this commit](https://github.com/mbvyd/ListClearDemo/commit/dbb88d71b3b505186956db2908f4939daf1f0b7a), place breakpoint in `HtmlFileSlice.cs` on line 160, launch program and stepover on breakpoint. 

(Specifically "magic" occurs on line 174 which is a simple call `Add` to dictionary which is another field of class.)

### Expected behavior

Adding item to dictionary of another field should not result in custom object change.

### Actual behavior

Result - `Fragments` property of `_htmlProcessor` is cleared (count was 18 and then 0) which is behaviour of overriden `ToString` method of this custom type. 

### Known Workarounds

To prove it is indeed `ToString` call, here is [fix commit](https://github.com/mbvyd/ListClearDemo/commit/182a91342ec5688659e27586327408c78e20ab31) which makes overriden `ToString` "safe". 

And if avoid using ToString override - this [fix commit](https://github.com/mbvyd/ListClearDemo/commit/b1e7ed8b2bfad691cda76a42b90b32c5727ff99b) - problem also solved. 

### Other information

Demo includes several NuGet packages, and it can be some dependencies' problem, but nature of behaviour suggests it can be related to core components.

**Comment by vcsjones** [comment]
Are you sure it's not the debugger itself calling `ToString` to show a string representation of what is being added to the dictionary in some debug window, like the watch window? 

The Visual Studio Debugger will use `ToString` to get a string representation of objects for purposes of displaying the string in various windows and tooling.

**Comment by mbvyd** [comment]
Seems like it is indeed so (didn't know about that `ToString` calls). Without interruptions by debugger (breakpoints) i see in console that items count is printed out correctly. 
So it seems like useless report (sorry if so).

**Comment by vcsjones** [comment]
No worries. Thanks for taking the time to report and put together a repository to reproduce the issue.

Some thoughts:

1. Generally, `ToString` should be pure. That is, it doesn't have observable side-effects, and, given the same inputs, produce the same output. Various things like debuggers, loggers, etc. may use `ToString` to get a string representation of the current state of the object.
2. If you want to provide your own debugging behavior, you can use [`DebuggerDisplay`](https://learn.microsoft.com/en-us/visualstudio/debugger/using-the-debuggerdisplay-attribute?view=vs-2022) to customize how your objects look to a debugger. Keep in mind though, other things may still end up using `ToString`.

**Comment by mbvyd** [comment]
Thanks for valuable points. I doubted it is a good idea to override `ToString`, but proceeded :) Now i will definitely refuse to touch it without absolute necessity (if it is ever exists).
