### ISSUE TITLE
[NativeAOT] No variables or object inspection when debugging class library

### ISSUE THREAD

**Issue by Paril** [dotnet/runtime#82802]
It seems that if you have a native executable that loads a NativeAOT-built class library, when stepping into the C# code, there's no ability to view variables or inspect the C# side of things at all (not even parameters, etc); is this intentional, or is something set up incorrectly on my end? I did see some people say that they could view variables/inspect objects in other issues, but I'm not sure why that's not possible in this case.

**Comment by jkotas** [comment]
Could you please share more details about your environment:
- .NET runtime version
- Operating system
- Debugger

**Comment by vitek-karas** [comment]
Did the debugger find symbols for the NativeAOT-built library. The library behaves like native code, without symbols the debugger won't see pretty much anything.

/cc @LakshanF

**Comment by Paril** [comment]
This ended up being user error; I was using `dotnet publish` with `-c Release`, and apparently there's still the ability to step through stuff but no variable inspection.

**Comment by agocke** [comment]
This might be that DWARF information isn't as good as it could be. See https://github.com/dotnet/runtime/issues/72552

I'll start looking into Release codegen specifically. We might be able to do better than we are right now.
