### ISSUE TITLE
[wasm] System.Memory.Tests broken if SIMD is enabled

### ISSUE THREAD

**Issue by kg** [dotnet/runtime#82808]
Right now SIMD is disabled for HOST_BROWSER because the jiterp doesn't support it. If you turn it on it seems to break System.Memory.Tests, see this log:
https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-82773-merge-d904e60cf8534bb888/normal-System.Memory.Tests/1/console.55efc30d.log?helixlogtype=result
```
... etc ...
  fail: [FAIL] System.Buffers.Binary.Tests.ReverseEndiannessUnitTests.ReverseEndianness_Span_AllElementsReversed<Int16>(original: [-1426, 31290, -14834, -477, 28732, ...])
  info: Assert.Equal() Failure
  info:            ↓ (pos 0)
  info: Expected: [28410, 14970, 3782, 9214, 15472, ...]
  info: Actual:   [-1282, 31354, -14642, -257, 28796, ...]
  info:            ↑ (pos 0)
  info:    at System.Buffers.Binary.Tests.ReverseEndiannessUnitTests.ReverseEndianness_Span_AllElementsReversed[Int16](Int16[] original)
  info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, IntPtr* args)
  info:    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
  info: Finished:    System.Memory.Tests.dll
  info: 
  info: === TEST EXECUTION SUMMARY ===
  info: Total: 48920, Errors: 0, Failed: 56, Skipped: 0, Time: 117.80777s
```

This reproduces both with jiterp SIMD enabled (from my PR) and with jiterp SIMD disabled, and reproduces both when the jiterp uses v128 opcodes and when it doesn't.

**Comment by kg** [comment]
cc @BrzVlad

**Comment by radical** [comment]
This looks similar to https://github.com/dotnet/runtime/issues/82808 which I found on `main`.
