### ISSUE TITLE
Cannot instantiate nullable class with Activator. Is it a bug?

### ISSUE THREAD

**Issue by 3da** [dotnet/runtime#82835]
`
var t = Activator.CreateInstance(typeof(int?), 2)
`
The type of t is Int32, not Nullable < Int32 >

This looks strange. Isn't it?

**Comment by stephentoub** [comment]
`Activator.CreateInstance` returns `object`.  For value types, that means boxing the value type.  Boxing a `Nullable<T>` produces a boxed `T`, not a boxed `Nullable<T>`.  This isn't specific to `Activator.CreateInstance`... you'd see the same thing with just:
```C#
int? i = 2;
object o = i;
Console.WriteLine(o.GetType());
```
It's by design.

**Comment by 3da** [comment]
@stephentoub thank you. What's the best approach to convert T to Nullable<T> with reflection?

**Comment by teo-tsirpanis** [comment]
> convert T to Nullable < T > with reflection

If you want to pass a nullable value to a method/field/property via reflection, you can try and pass just the object of type `T`. I ran the following snippet:

```csharp
object value = 184;

var c = new C();

Console.WriteLine(c.X?.ToString() ?? "<null>"); // prints <null>

typeof(C).GetField("X")!.SetValue(c, value);

Console.WriteLine(c.X?.ToString() ?? "<null>"); // prints 184

class C { public int? X;}
```
