### ISSUE TITLE
Add CollectionsMarshal support for the `HashSet<T>` collection

### ISSUE THREAD

**Issue by theodorzoulias** [dotnet/runtime#82840]
### Background and motivation

The `Dictionary<TKey,TValue>` collection was improved in .NET 6, by introducing direct `ref` access to its values. This improvement made the collection more suitable for performance-critical applications, by reducing the number of times a key has to be hashed when adding/modifying values in the collection. For example the [`GetOrAdd`](https://github.com/dotnet/runtime/issues/15059) extension method can be implemented efficiently with a single hashing of the key. The same improvement could be made to the [`HashSet<T>`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.hashset-1) collection as well. A [`GetOrAdd`](https://github.com/dotnet/runtime/issues/21603) API has also been proposed for the `HashSet<T>`, but that proposal was closed with a mention about adding [`CollectionsMarshal`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.collectionsmarshal) support in the future. This proposal here is exactly about adding this support.

### API Proposal

```C#
namespace System.Runtime.InteropServices
{
    public static partial class CollectionsMarshal
    {
        public static ref T? GetValueRefOrAddDefault<T> (HashSet<T> hashSet, T item, out bool exists);
        public static ref T GetValueRefOrNullRef<T> (HashSet<T> hashSet, T item);
    }    
}
```

### API Usage

Below is a partial implementation of a concurrent `HashSet<T>` [with bounded capacity](https://stackoverflow.com/questions/27403530/thread-safe-collection-with-upper-bound "Thread safe Collection with upper bound"). The proposed API `GetValueRefOrAddDefault` is used when space is available in the collection, and the proposed API `GetValueRefOrNullRef` is used when the collection is full:

```C#
public partial class ConcurrentBoundedHashSet<T>
{
    private readonly HashSet<T> _set = new();
    private readonly int _boundedCapacity;

    /// <summary>
    /// Searches the set for a given value and returns the equal value it finds,
    /// otherwise adds the given value to the set if space is available,
    /// otherwise returns false.
    /// </summary>
    public bool TryGetOrAdd(T equalValue, out T? actualValue)
    {
        lock (_set)
        {
            if (_set.Count < _boundedCapacity)
            {
                ref T? valueRef = ref CollectionsMarshal.GetValueRefOrAddDefault(_set, equalValue,
                    out bool exists);
                if (!exists) valueRef = equalValue;
                actualValue = valueRef; return true;
            }
            else
            {
                ref T valueRef = ref CollectionsMarshal.GetValueRefOrNullRef(_set, equalValue);
                if (!Unsafe.IsNullRef(ref valueRef))
                {
                    actualValue = valueRef; return true;
                }
                else
                {
                    actualValue = default; return false;
                }
            }
        }
    }
}
```

### Risks

None that I can think of.

Labels: [**area-System.Collections**](https://github.com/dotnet/runtime/labels/area-System.Collections) / [**api-suggestion**](https://github.com/dotnet/runtime/labels/api-suggestion).

**Comment by eiriktsarpalis** [comment]
The CollectionMarshal methods for Dictionary provide `ref` access to the value of a given entry, not its key. In the case of HashSet you'd be necessarily permitting external modification of the key itself which has a number of problems:

1. What does `AddDefault` mean in `GetValueRefOrAddDefault`? If you're actually adding `default(T)` then that would not be equal to the `item` parameter and for reference types it would be `null` which is not supported.
2. Mutating the resultant `ref` would corrupt hashtable unless the value you're setting it with is equal to the original value.

**Comment by stephentoub** [comment]
I agree with @eiriktsarpalis; the proposed `GetValueRefOrAddDefault` doesn't seem viable. I could see us adding `GetValueRefOrNullRef` _if_ it were changed to return a `ref readonly`.

**Comment by theodorzoulias** [comment]
@eiriktsarpalis, @stephentoub you are both right. This was a poorly thought proposal.

On top of the above, in the "API Usage" example the `else` block can be trivially replaced with `return _set.TryGetValue(equalValue, out actualValue);`.

I am closing this one.
