### ISSUE TITLE
[API Proposal]: IPAddress should implement ISpanFormattable/Parsable<IPAddress>

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#82842]
### Background and motivation

IPAddress already provides TryFormat/TryParse methods.  It should implement the appropriate interfaces to go along with these.  Doing that for `IPAddress`, for example, means the `IPAddress`'s `TryFormat` will be used as part of string interpolation rather than its `ToString()` being used.

### API Proposal

```diff
namespace System.Net

public class IPAddress
+    : ISpanFormattable, ISpanParsable<IPAddress>
{
    // all of the interface members implemented explicitly
}
```

### API Usage

```C#
IPAddress address = ...;
string s = $"The address is {address}";
```

**Comment by stephentoub** [comment]
Implementation:
https://github.com/dotnet/runtime/compare/main...stephentoub:runtime:ipaddressinterfaces

**Comment by stephentoub** [comment]
cc: @antonfirsov

**Comment by antonfirsov** [comment]
@stephentoub thanks for pushing this! Since the implementation looks trivial, I think we should get this done before finishing #82779.

**Comment by bartonjs** [comment]
Looks good as proposed

```diff
namespace System.Net

public class IPAddress
+    : ISpanFormattable, ISpanParsable<IPAddress>
{
    // all of the interface members implemented explicitly
}
```
