### ISSUE TITLE
dotnet 7 System.Text.Json JsonSerializer.Serialize exception: is marked required but does not specify a setter.

### ISSUE THREAD

**Issue by kzhui125** [dotnet/runtime#82879]
### Description

using JsonSerializer.Serialize to Serialize object.

### Reproduction Steps

```cs
using System.Text.Json;
using System.Text.Json.Serialization;

TestDto t = new() { Items = new() };

string jsonString = JsonSerializer.Serialize(t);
Console.WriteLine(jsonString);

public class TestDto
{
    public string? Field1 { get; set; }
    [JsonIgnore]
    public required List<string> Items { get; set; }
}
```

### Expected behavior

no exception

### Actual behavior

exception throws

**Comment by eiriktsarpalis** [comment]
I believe this is by design. The `required` keyword is picked up by the serializer and has special meaning (equivalent to `JsonRequiredAttribute`). However "required" is the exact opposite to "ignore" so the two configurations are mutually exclusive. If the property needs to be ignored you should remove the `required` keyword. If the property is `required` for initialization then you should remove the `JsonIgnore` annotation.

**Comment by kzhui125** [comment]
```cs
using Newtonsoft.Json;

TestDto t = new() { Field1 = "Value1", Items = new() };
List<TestDto> ts = new() { t };

string json = JsonConvert.SerializeObject(t);
Console.WriteLine();

public class TestDto
{
    public required string Field1 { get; set; }

    [JsonIgnore]
    public required List<string> Items { get; set; }
}
```

when using Newtonsoft.Json it works

**Comment by kzhui125** [comment]
The property is required for object initialization (what the required keyword mean), but not required for json serialization.

They are two different things.

**Comment by eiriktsarpalis** [comment]
I would guess that's because Json.NET doesn't support `required` properties yet.

**Comment by eiriktsarpalis** [comment]
> The property is required for object initialization (what the required keyword mean), but not required for json serialization.
> 
> They are two different things.

They are not. Deserialization if anything does perform object initialization, albeit indirectly. You can always bypass required/init properties when using reflection (which is why you see this working in the case of Json.NET), however you can't do it in the case of source generators. STJ honors `required` properties both because it preserves invariants of the deserialized class and because it has to in the case of source generators.

**Comment by kzhui125** [comment]
Deserialization throws exception make sense. since deserialization will create object, and the required modifier should be respected.

But serialization is object to json. The object is already created(required modifier was also respected). Serialization throw exception make people confuse, since it doesn't create object, it only create string from concat object properties.

I meet this issue when I want to return dictionary as json to frontend, but I  don't want to return the original list (duplicate).

```cs
using System.Text.Json;
using System.Text.Json.Serialization;

SomeVm vm = new() { SomeDtos = new() };
foreach (var dto in vm.SomeDtos)
{
    dto.ItemsDict = dto.Items
        .ToDictionary(i => i.Key, i => i);
}

string jsonString = JsonSerializer.Serialize(vm);
Console.WriteLine(jsonString);


public class SomeVm
{
    public required List<SomeDto> SomeDtos { get; set; }
    public string? Field1 { get; set; }
}

public class SomeDto
{
    public string? Field1 { get; set; }

    [JsonIgnore]
    public required List<SomeItemDto> Items { get; set; }
    public Dictionary<string, SomeItemDto>? ItemsDict { get; set; }
}

public class SomeItemDto
{
    public required string Key { get; set; }
    public string? Value { get; set; }
}
```

Thanks for your help.

**Comment by eiriktsarpalis** [comment]
[JsonIgnoreAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonignoreattribute?view=net-7.0) is not specific to serialization -- it also controls deserialization. It's precisely this mode (disabling deserialization for a property marked required) that triggers the error you are seeing.

**Comment by eiriktsarpalis** [comment]
Does this work? https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/required-properties

**Comment by kzhui125** [comment]
The page talks about JsonSerializer.Deserialize will throw exception, but doesn’t mention JsonSerializer.Serialize

**Comment by eiriktsarpalis** [comment]
> The page talks about JsonSerializer.Deserialize will throw exception, but doesn’t mention JsonSerializer.Serialize

The error stems from validating the JSON contract for the type, which happens during both serialization and deserialization operations.

**Comment by kzhui125** [comment]
<img width="745" alt="image" src="https://user-images.githubusercontent.com/11925432/222501527-b85d1904-0b51-44ba-a3f0-4f4395a6985f.png">

maybe we should update the document, to make it clear.

**Comment by eiriktsarpalis** [comment]
> <img alt="image" width="745" src="https://user-images.githubusercontent.com/11925432/222501527-b85d1904-0b51-44ba-a3f0-4f4395a6985f.png">
> 
> maybe we should update the document, to make it clear.

That's not accurate. As mentioned the exception stems from contract _validation_ and is not part of the serialization contract for required properies. This should be evident from the stacktrace of the reproduction:

```
Unhandled exception. System.InvalidOperationException: JsonPropertyInfo 'Items' defined in type 'TestDto' is marked required but does not specify a setter.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonPropertyRequiredAndNotDeserializable(JsonPropertyInfo jsonPropertyInfo)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo.Configure()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.InitializePropertyCache()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureLocked|143_0()
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Boolean resolveIfMutable)
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
```

We might want to update the documentation for `JsonPriopertyInfo.IsRequired` to mention that it is not compatible with properties that don't have a setter or are ignoring their setter.
