### ISSUE TITLE
[API Proposal]: Add an overload of the StackTrace constructor to take in an array of frames

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/runtime#82871]
### Background and motivation

StackTrace already contains a constructor that accepts a single frame, accepting multiple frames would seem a logical continuation and allows for nice resolution of stack frames captured from an existing StackTrace object. 

Because `ToString(TraceFormat traceFormat, StringBuilder sb)` uses `_numOfFrames` rather than the virtual `FrameCount` when calling `GetFrame(int)`, it's unreliable (minus setting the field via reflection) to call `ToString()` on a class derived from `StackTrace` that would allow the specification of a specific set of frames (rather than one frame).

### API Proposal

```csharp
namespace System.Diagnostics;

public partial class StackTrace
{
    //Additional constructor
    public StackTrace(StackFrame[] frames)
    {
        _stackFrames = frames;
        _numOfFrames = frames.Length;
    }
}
```

### API Usage

```csharp
// Get a real stack trace
var realTrace = new StackTrace(true)
// Filter out frames that aren't of interest (things that could identify a customer, generated code, etc.)
var filteredFrames = FilterToDesiredFrames(realTrace.GetFrames());
// Construct a fake trace containing the desired frames
var fakeTrace = new StackTrace(filteredFrames);

// Using the prettification StackTrace applies to its frames
Console.WriteLine(fakeTrace);
```

**Comment by tommcdon** [comment]
@noahfalk

**Comment by noahfalk** [comment]
This seems fine to me. @tarekgh - for a simple change like this do we need someone to represent it in API review or can they just read it over?

**Comment by tarekgh** [comment]
It is better if someone represents it in the design review to answer any raised question from the reviewer. I can represent it if I'll be available. I'll not be available tomorrow so we may schedule this later next week. We can mark it as ready on Wednesday.

**Comment by tarekgh** [comment]
@noahfalk I marked this as ready for review. let's see when it will get scheduled.

**Comment by noahfalk** [comment]
> I can represent it if I'll be available

Thanks! Much appreciated :)

**Comment by bartonjs** [comment]
* We felt that IEnumerable was more flexible, allowing for callers to use Linq methods, etc, more easily.

```C#
namespace System.Diagnostics;

public partial class StackTrace
{
    //Additional constructor
    public StackTrace(IEnumerable<StackFrame> frames)
    {
        // Make a draining copy
    }
}
```

**Comment by tarekgh** [comment]
@noahfalk this approved. 

@mlorbetske do you want to resurrect the PR https://github.com/dotnet/runtime/pull/82872 and updated it according to the feedback?

**Comment by noahfalk** [comment]
Thanks @tarekgh!

**Comment by mlorbetske** [comment]
Can do, but might be a while before I'm able to get back to it.

**Comment by mlorbetske** [comment]
Sorry for the delay, recreated as #88542
