### ISSUE TITLE
Not able to serialize Geometry with System.Text.Json

### ISSUE THREAD

**Issue by mhosman** [dotnet/runtime#82870]
### Description

With GeoJSON4STJ, using System.Text.Json, and trying to serialize an object with Geometry attribute, I get:

".NET number values such as positive and negative infinity cannot be written as valid JSON. To make it work when using 'JsonSerializer', consider specifying 'JsonNumberHandling.AllowNamedFloatingPointLiterals' (see https://docs.microsoft.com/dotnet/api/system.text.json.serialization.jsonnumberhandling)."

I already added:

`options.JsonSerializerOptions.Converters.Add(new NetTopologySuite.IO.Converters.GeoJsonConverterFactory());`

And even:

`options.JsonSerializerOptions.NumberHandling = JsonNumberHandling.AllowNamedFloatingPointLiterals`

But is not working...

### Reproduction Steps

Try to serialize a Geometry object like this one:

`{POLYGON ((-56.1628036793649 -34.9146419359614, -56.1669231612679 -34.9151709047024, -56.1679692497985 -34.915428241992, -56.1733042972341 -34.9160286931848, -56.1753441683124 -34.9202746109245, -56.1747165156729 -34.9263643329828, -56.1699568172883 -34.9283798458885, -56.1651448129208 -34.9331396889133, -56.1623203760431 -34.9393142088626, -56.1573514585157 -34.9403432503296, -56.1550500671005 -34.9362270060086, -56.1529578924336 -34.9286800222015, -56.1432292765216 -34.9227620160856, -56.1403525336611 -34.9187735538318, -56.1404571408382 -34.9159000260728, -56.1371096632867 -34.9137555356797, -56.1339295512714 -34.913071691206, -56.1352467583123 -34.9098716521049, -56.1367002877222 -34.9058046017092, -56.1383719489081 -34.9013250083275, -56.1411009352232 -34.8977620313726, -56.1435280547161 -34.8950332624095, -56.1452181052468 -34.8923679909889, -56.146439649364 -34.8904309522975, -56.1475836134781 -34.8889814313825, -56.1475825302443 -34.888987456316, -56.1482544324268 -34.8892289925655, -56.1491925860663 -34.8895957594073, -56.1510216181927 -34.8902685180366, -56.1545751785472 -34.891067409282, -56.1570894541358 -34.8917635416443, -56.1588425276056 -34.8921229253218, -56.1598486703148 -34.8925273985235, -56.1625409945408 -34.893949173481, -56.1648117892893 -34.8948232318314, -56.1628036793649 -34.9146419359614))}`

### Expected behavior

The object gets serialized

### Actual behavior

I get error:

".NET number values such as positive and negative infinity cannot be written as valid JSON. To make it work when using 'JsonSerializer', consider specifying 'JsonNumberHandling.AllowNamedFloatingPointLiterals' (see https://docs.microsoft.com/dotnet/api/system.text.json.serialization.jsonnumberhandling)."

**Comment by eiriktsarpalis** [comment]
Could you please share a minimal reproduction showcasing the issue? Thanks.

https://github.com/dotnet/runtime/blob/main/CONTRIBUTING.md#writing-a-good-bug-report

**Comment by mhosman** [comment]
Closing since is related to https://github.com/dotnet/efcore/issues/28811
