### ISSUE TITLE
Test failure System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedWindowsPlatforms_IsSupportedIsTrue

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#82885]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=190304
Build error leg or test failing: System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedWindowsPlatforms_IsSupportedIsTrue
Pull request: https://github.com/dotnet/runtime/pull/82766

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedWindowsPlatforms_IsSupportedIsTrue",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

Failing configurations:
```
Failing Configurations (8)
net8.0-windows-Release-arm64-CoreCLR_checked-no_tiered_compilation-Windows.11.Arm64.Open
net8.0-windows-Release-arm64-CoreCLR_checked-tailcallstress-Windows.11.Arm64.Open
net8.0-windows-Release-arm64-CoreCLR_checked-jitstress1_tiered-Windows.11.Arm64.Open
net8.0-windows-Release-arm64-CoreCLR_checked-jitstress2-Windows.11.Arm64.Open
net8.0-windows-Release-arm64-CoreCLR_checked-jitstress1-Windows.11.Arm64.Open
net8.0-windows-Release-arm64-CoreCLR_checked-jitminopts-Windows.11.Arm64.Open
net8.0-windows-Release-arm64-CoreCLR_checked-zapdisable-Windows.11.Arm64.Open
net8.0-windows-Release-arm64-CoreCLR_checked-jitstress2_tiered-Windows.11.Arm64.Open
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by ManickaP** [comment]
Could the reason for this failure be that we switched to our internal feed from dotnet/msquic in #81742 but it doesn't build Windows arm 64 @wfurt?

**Comment by CarnaViire** [comment]
It was working 28.02 on main: [AzDO](https://dev.azure.com/dnceng-public/public/_build/results?buildId=189014&view=logs&j=f9affed7-8d82-5c58-eb09-b33088a0b629&t=841cba2d-9b8a-52d6-e2e0-be8034011045&l=223), [console log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-5d08fc851b8a4c7197/System.Net.Quic.Functional.Tests/1/console.64190a0d.log?helixlogtype=result)
It is not working 01.03 on main: [AzDO](https://dev.azure.com/dnceng-public/public/_build/results?buildId=190643&view=logs&j=f9affed7-8d82-5c58-eb09-b33088a0b629&t=841cba2d-9b8a-52d6-e2e0-be8034011045&l=233), [console log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-f69bc17f25aa420baf/System.Net.Quic.Functional.Tests/3/console.5c172097.log?helixlogtype=result)

**Comment by wfurt** [comment]
Probably outcome of  #81742 - missed by PR test coverage. We may choose to use official MsQuic for ARM to get some coverage for 2.1.x as well.

**Comment by CarnaViire** [comment]
Disabled in https://github.com/dotnet/runtime/pull/82902
