### ISSUE TITLE
[browser] don't publish native DLLs

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#82888]
## Problem
System.Diagnostics.Tracing.Tests.csproj has native dependencies such as `vcruntime140.dll`
We should not include them in the `AppBundle` folder and `mono-config.json` because 
- they are not possible to use on wasm anyway
- they create AV problems
- increase download size

The consequences are `Error: MONO_WASM: download 'http://127.0.0.1:40699/managed/vcruntime140_1.dll' for vcruntime140_1.dll failed 0 TypeError: Failed to fetch` see [log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-82049-merge-86cfe0b1dd5948ea89/WasmTestOnBrowser-System.Diagnostics.Tracing.Tests/1/console.643bf3f2.log?helixlogtype=result)

![image](https://user-images.githubusercontent.com/271576/222424476-cca87455-b701-4667-a17c-6f9fd8cb19bc.png)

## Possible solutions
A) `WasmAppBuilder` could skip non IL assemblies
B) `WasmAppBuilder` could fail build when non IL assemblies are added

**Comment by radical** [comment]
This is being included as a `@(None)`, so not meant for running this. The issue is known and will be resolved once we start using the publish output better, so it is part of that work.
