### ISSUE TITLE
Currency and Number formatting separators for en-BE CultureInfo is incorrect for Core

### ISSUE THREAD

**Issue by TCN-AlastairH** [dotnet/runtime#82898]
Hi,

As with the title it looks like the Currency and Number formatting values for the en-BE culture are swapped in .Net Core. Everything I can see (including looking at fr-BE and nl-BE) says that the Decimal Separator should be a comma and the group separator however it looks like since .Net Core 3.1 these are swapped. Previously .Net 4.7.2 had it set correctly.

It was causing me a bit of confusion as to why certain calculations were out until I spotted this.

You can see the values here: https://www.localeplanet.com/icu/en-BE/index.html

And a .Net Fiddle proving it here: https://dotnetfiddle.net/ejhVUp

Thanks,
Alastair

**Comment by danmoseley** [comment]
We moved from Windows OS tables to the industry standard ICU tables known as CLDR.
Do you see the same there?

https://unicode-org.github.io/cldr-staging/charts/latest/index.html

**Comment by TCN-AlastairH** [comment]
Hi Dan,

Thanks for the reply. You are correct that those CLDR tables show the settings as they are in Core. I'll close this for now, thanks.

-Alastair
