### ISSUE TITLE
Installing .NET Core on Ubuntu failing

### ISSUE THREAD

**Issue by drewswiredin** [dotnet/runtime#829]
```Get:8 https://packages.microsoft.com/ubuntu/19.10/prod eoan/main amd64 Packages [156 kB]
Err:8 https://packages.microsoft.com/ubuntu/19.10/prod eoan/main amd64 Packages
  File has unexpected size (3891 != 156065). Mirror sync in progress? [IP: 40.76.35.62 443]
  Hashes of expected file:
   - Filesize:156065 [weak]
   - SHA512:12e6dffcd247d1ff067acfa61a3c4eb6078c326c2858feb4f6f141a1d809e22292a78282414a5c103038ea80bb63cd734c7516782c9809c341335083d4e7611b
   - SHA256:c850f35f1979831ac75641978c397e51519fa22313598ec12bde5f52277044c0
   - SHA1:1f65f4a7388c22bcf7b7f30fb7bc337c60d94b2e [weak]
   - MD5Sum:4153a12e4a5629bfb14ed98f4c8ac234 [weak]
  Release file created at: Thu, 12 Dec 2019 19:59:19 +0000
```

**Comment by AustinSchoen** [comment]
I posted a similar problem here: https://github.com/microsoft/dotnet/issues/1152

**Comment by MichaelSimons** [comment]
This was also reported at dotnet/core#3988.

**Comment by danmosemsft** [comment]
@livarcocc  where should this one go?

**Comment by dagood** [comment]
An update on the problem: I've filed an internal ticket and emailed the repo admins. I'm going to use https://github.com/dotnet/core/issues/3988 for more followup as it happens.

---

> where should this one go?

*Some* issues about the Linux package repo have traditionally gone on the Core-Setup repo, which is probably why one was filed over here after the consolidation. I think we should find a better place for issues like this--issues about outages or release process issues that affect endpoints like the Microsoft Linux package repository or Download Center.

A lot of these have been tracked at dotnet/core recently, which seems fine to me. However, we should probably take a hard look at anywhere we point people at Core-Setup to report installer issues (like the announcement posts). @leecow

**Comment by danmosemsft** [comment]
Thanks, @dagood

**Comment by dagood** [comment]
Closing as resolved: this was fixed on Dec 10. (https://github.com/dotnet/core/issues/3995)
