### ISSUE TITLE
System.Text.Json: Ignore only (de)serialization

### ISSUE THREAD

**Issue by lus** [dotnet/runtime#82904]
Hello.

I currently have the need to only ignore **de**serialization of a value, but it should keep being serialized.
There were multiple issues already addressing this, such as #34404 or #30687, but they were all closed due to lack of need.
While I get that it seems like not much people need this feature, it looks like it is nearly impossible to achieve this behaviour with the current API, at least if it should not get too hacky.

If this is not planned to be implemented (which would be sad in my opinion), do you have any suggestions on how I could achieve this with the current API without producing too much of a mess?

**Comment by eiriktsarpalis** [comment]
In the meantime, we have an issue tracking `JsonIgnoreCondition` extensions specific to writing or reading: https://github.com/dotnet/runtime/issues/66490
