### ISSUE TITLE
[mono][aot] Remove method body for inlined methods

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#82907]
When a method is inlined, its implicit reference still exists in a `method_addresses` table  and native linker can't remove its body. For example, if `_HelloWorld_MyGen_Bar` is inlined and not called indirectly, then its method body is not needed during the runtime.
```
_mono_aot_HelloWorldmethod_addresses:
0000000000003938    bl    _HelloWorld_Program_Foo_string__
000000000000393c    bl    _HelloWorld_Program__ctor
0000000000003940    bl    _HelloWorld_MyGen_Bar
...
_HelloWorld_MyGen_Bar:
0000000000003970    adrp    x16, 5 ; 0x8000
0000000000003974    add    x16, x16, #0x2a8
0000000000003978    ldr    x16, [x16, #0xb8]
...
```

/cc: @ivanpovazan

**Comment by kotlarmilos** [comment]
@ivanpovazan According to your experiment, does the following code snipped in `emit_code` method populate `method_addresses` table?

https://github.com/dotnet/runtime/blob/e57bb02c569d6f5ac986395f0becfee289831df2/src/mono/mono/mini/aot-compiler.c#L10766-L10782

**Comment by ivanpovazan** [comment]
@kotlarmilos, yes here is the change from the experiment:

https://github.com/ivanpovazan/runtime/blob/38eabec1a6320287f754a2e05b19787664c55df5/src/mono/mono/mini/aot-compiler.c#L10782-L10787

**Comment by ivanpovazan** [comment]
> can_specialize depends on the linker adding annotations to methods, which needs to be implemented/fixed. @ivanpovazan Do you perhaps know what is the status of --explicit-reflection flag in the linker?

I have provided more details in the `Prerequisites` section in [my comment](https://github.com/dotnet/runtime/issues/82936#issuecomment-1479358878). The requirement `2.` is necessary to enable this optimization as well, so it can be treated as a common prerequisite. Afaik `--explicit-reflection` is a legacy feature which is currently unused.

**Comment by kotlarmilos** [comment]
Thanks! As you outlined, the idea is to estimate potential improvements (size savings and better performance) before proceeding with the concrete implementation.

**Comment by kotlarmilos** [comment]
Obsolete, lower priority compared to other tasks.
