### ISSUE TITLE
[API Proposal]: Allow custom converters to get their type's JsonTypeInfos

### ISSUE THREAD

**Issue by dragorosson** [dotnet/runtime#82922]
### Background and motivation

I apologize if this is a duplicate. I did a search on here but didn't find anything.

My general problem is that I'm trying to replicate "standard" `system.text.json`'s behavior in a custom converter. Basically, (de)serializing all the properties of the converter's type(s), respecting any attributes like `[JsonIgnore]` rather than need to implement the same logic that `system.text.json` already has. This would allow adding in custom augmentations while avoiding infinite recursion or having to leave out the original `JsonSerializerOptions` when calling `JsonSerializer.{De}Serialize` to get "standard" serialization behavior within a custom converter.

My specific problem is that I'm trying to get around https://github.com/dotnet/runtime/issues/72604, but I don't think this issue/proposal is strictly related to that.

### API Proposal

The proposal is to allow custom converters access to the `JsonTypeInfo` of the types they can convert.

Currently, if you try to get info for such a type, you will get back a `JsonTypeInfo` whose `Kind` is `None`. This appears to be intended, as explained in https://devblogs.microsoft.com/dotnet/system-text-json-in-dotnet-7/#metadata-kinds:
> None – type uses a converter not configurable by metadata; typically applies to primitive types, object, string or types using custom user-defined converters.

However, `JsonTypeInfo` seems like exactly the thing I'd want to use to make a converter mimic the built-in `system.text.json` behavior.

There are multiple (equivalent?) existing APIs to get `JsonTypeInfo`s:
- `JsonSerializerOptions.GetTypeInfo(Type type)`
- `DefaultJsonTypeInfoResolver.GetTypeInfo(Type type, JsonSerializerOptions options)`
- `IJsonTypeInfoResolver.GetTypeInfo(Type type, JsonSerializerOptions options)`

It's possible that no API signature change needs to be made, just the semantics so that they'll return a usable `JsonTypeInfo` instead of an empty one with `Kind == None`. An alternative would be to add another API that could return this `JsonTypeInfo` and leave the existing APIs unchanged (although I suppose this is not ideal because it would affect or be outside of metadata caching?).

### API Usage

For a fully working code example, including the workaround I had to do, see: https://github.com/dotnet/runtime/issues/72604#issuecomment-1440708052

A pseudocode example of using `JsonTypeInfo` within a custom converter:

```csharp
public override void Write(
    Utf8JsonWriter writer, T? value, JsonSerializerOptions options)
{
    writer.WriteStartObject();
    
    // (Some custom logic here specific to the converter, such as adding a type discriminator property)

    // Serialize the rest of the properties like normal
    JsonTypeInfo info = options.GetTypeInfo(value!.GetType()); // Right now this returns a `None` type info

    foreach (var p in info.Properties)
    {
        if (p.Get is null) continue;

        writer.WritePropertyName(p.Name);
        object? pVal = p.Get(value);
        JsonSerializer.Serialize(writer, pVal, options);
    }

    writer.WriteEndObject();
}
```

### Alternative Designs

My actual alternative is in the above section. I will briefly put the workaround I came up with in this section.

For the full code with workaround, see https://github.com/dotnet/runtime/issues/72604#issuecomment-1440708052

I can still get what I want done today, but in a way that seems more fragile to me. `GetTypeInfo` will work as desired on a `JsonSerializerOptions` with all the `JsonConverter`s taken out:

```csharp
JsonSerializerOptions optionsWithoutConverters = new(options);
optionsWithoutConverters.Converters.Clear();
JsonTypeInfo typeInfo = optionsWithoutConverters.GetTypeInfo(someType);
```

 I _think_ this doesn't have any negative consequences on the returned `JsonTypeInfo`. This isn't ideal because either I have to do this options cloning every read/write, or cache the result which will break if the original `JsonSerializationOptions` is cloned and has its configuration changed.

### Risks

I'm not very familiar with `system.text.json` internals 🤷 sorry!

**Comment by eiriktsarpalis** [comment]
> // Right now this returns a `None` type info

One important thing to understand about `JsonTypeInfo` configuration is that it controls how the _built-in_ converters are meant to serialize an object. Thus, the extent to which it can be configured depends on what converter is being used for the particular type. If the type uses the built-in object converter, its corresponding `JsonTypeInfo` reports `JsonTypeInfoKind.Object`, but if the type uses a custom converter (as in your case) then the corresponding `JsonTypeInfo` reports `JsonTypeInfoKind.None` because your converter implementation is the sole source of truth of how the type is meant to be serialized.

If you just need a quick way to get the _default_ metadata that STJ generates for a given type, just changing that line to
```C#
JsonTypeInfo info = JsonSerializerOptions.Default.GetTypeInfo(value!.GetType());
```
which should give you metadata independent of your custom converter.

**Comment by dragorosson** [comment]
> > // Right now this returns a `None` type info
> 
> One important thing to understand about `JsonTypeInfo` configuration is that it controls how the _built-in_ converters are meant to serialize an object. ...  your converter implementation is the sole source of truth of how the type is meant to be serialized.

I understand that's the intent of `JsonTypeInfo`. Just as modifying `JsonTypeInfo`s for built-in converters was found to be useful and enabled in .Net 7, being able to get a `JsonTypeInfo` as it would be resolved by the _same_ options passed into a custom converter would allow custom converters to be extended/modified as the built-in converters are. I think that many custom converters just need to modify what the built-in converters would normally do, not supply a completely different serialization or ignore any modifications the built-in converters would pick up.
 
> If you just need a quick way to get the _default_ metadata that STJ generates for a given type, just changing that line to
> 
> ```cs
> JsonTypeInfo info = JsonSerializerOptions.Default.GetTypeInfo(value!.GetType());
> ```

This misses out on a custom `TypeInfoResolver` or any `DefaultJsonTypeInfoResolver.Modifiers`.

If I do (from [here](https://devblogs.microsoft.com/dotnet/system-text-json-in-dotnet-7/#modifying-json-contracts)):
```
var options = new JsonSerializerOptions
{
    TypeInfoResolver = new DefaultJsonTypeInfoResolver
    {
        Modifiers = { UseUppercasePropertyNames }
    }
};
```
`JsonSerializerOptions.Default.GetTypeInfo` won't include the uppercase modifier, so a custom converter trying to match the built-in converters as much as possible won't be serializing property names correctly.

**Comment by eiriktsarpalis** [comment]
> If I do (from [here](https://devblogs.microsoft.com/dotnet/system-text-json-in-dotnet-7/#modifying-json-contracts)):
> 
> ```
> var options = new JsonSerializerOptions
> {
>     TypeInfoResolver = new DefaultJsonTypeInfoResolver
>     {
>         Modifiers = { UseUppercasePropertyNames }
>     }
> };
> ```
> 
> `JsonSerializerOptions.Default.GetTypeInfo` won't include the uppercase modifier, so a custom converter trying to match the built-in converters as much as possible won't be serializing property names correctly.

You can replace `JsonSerializerOptions.Default` with an options instance applying a modifier as shown to resolve the metadata you need. As long as that `options` instance doesn't specify a custom converter for the types you're interested in you should be ok.
