### ISSUE TITLE
[API Proposal]: ArgumentOutOfRangeException.ThrowIfNegativeOrGreaterThanOrEqual

### ISSUE THREAD

**Issue by xtqqczze** [dotnet/runtime#82930]
### Background and motivation

For the common case of validating an index to a span, array, string, etc.

Can be implemented in one branch as `(uint)value >= (uint)other` as opposed to two branches with the following:

```csharp
ArgumentOutOfRangeException.ThrowIfNegative(arrayIndex);
ArgumentOutOfRangeException.ThrowIfGreaterThan(arrayIndex, array.Length);
```

### API Proposal

```csharp
public class ArgumentOutOfRangeException : ArgumentException
{
  public static void ThrowIfNegativeOrGreaterThan<T>(T value, T other, [CallerArgumentExpression(nameof(value))] string? paramName = null)
    where T : INumberBase<T>
  public static void ThrowIfNegativeOrGreaterThanOrEqual<T>(T value, T other, [CallerArgumentExpression(nameof(value))] string? paramName = null)
    where T : INumberBase<T>
}
```

### API Usage

```csharp
  private T[] array
  public T this[int arrayIndex]
  {
    get
    {
      ArgumentOutOfRangeException.ThrowIfNegativeOrGreaterThanOrEqual(arrayIndex, array.Length);
      return array[arrayIndex];
    }
  }
```

### Alternatives

* The proposed API, but internal only.
* The JIT could be taught to recognize a range check and convert into a single branch.

**Comment by skyoxZ** [comment]
I think we don't need `INumberBase<T>`, `int` is enough. And the method name could be simplified to `ThrowIfNotWholeNumberLessThan`.

**Comment by stephentoub** [comment]
> Doing the same for a public API in the BCL is probably not possible, but taking a T[], Span<T>, and ReadOnlySpan<T> would be. We could then consider taking ICollection<T> to cover other cases, but I imagine the majority case would be covered by the first three.

Note that https://github.com/dotnet/runtime/issues/77749 proposes a `ThrowIfBufferTooSmall`, which I left some comments on in https://github.com/dotnet/runtime/issues/77749#issuecomment-1333201950.  I'd be concerned about taking an `ICollection<T>` that _could_ lead to interface dispatch (though hopefully it could be eliminated by the JIT in some cases) in an API that's intended to be super cheap.
