### ISSUE TITLE
Not sure, but it seems that timeBeginPeriod affects Task.Delay now? 

### ISSUE THREAD

**Issue by lhrbu** [dotnet/runtime#82944]
As list in document Task.Delay document [https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.delay?view=net-7.0](url) :"The system clock that is used is the same clock used by GetTickCount, which is not affected by changes made with timeBeginPeriod and timeEndPeriod.“ and I've tested years ago, timeBeginPeriod actually won't affect Task.Delay resolution. But things started to get interesting that I tested recently now on .net 7 that when you can timeBeginPeriod(1), Task.Delay can give a 1ms accuracy, WOW!!!. So is it true that the implementation has been modified?

**Comment by stephentoub** [comment]
@kouvel, this was a side effect of your portable timer changes, yes?

**Comment by kouvel** [comment]
Yea it's likely because .NET 7 uses the managed portable timer implementation. The managed implementation has been using `QueryUnbiasedInterruptTime`, which is affected by `timeBeginPeriod`, and the portable timer uses that to kick off timers as well. The previous native implementation used `GetTickCount` to kick off timers, which is not affected by `timeBeginPeriod`,

**Comment by lhrbu** [comment]
> 

wow, it's amazing, a high accuracy Task.Delay provides a much easier way to launch a cancellation token based cancellable timer task, thanks a lot for your effort

**Comment by danmoseley** [comment]
@lhrbu can you close now?

**Comment by lhrbu** [comment]
> @lhrbu can you close now?

As I test deeply, I've found another point, that if you aot publish your program, then timeBeginPeriod doesn't affect Task.Delay which is some kind of bug?

**Comment by kouvel** [comment]
NativeAOT uses the Windows thread pool, and it looks like the Windows thread pool's timers are not affected by `timeBeginPeriod`.

**Comment by mangod9** [comment]
Guessing the question has been answered, @lhrbu? Closing for now.
