### ISSUE TITLE
HttpResponseHeaders.Location can throw InvalidCastException

### ISSUE THREAD

**Issue by jskeet** [dotnet/runtime#82943]
### Description

I've only seen this issue second hand, via customers using the Google.Cloud.Storage.V1 library to upload storage objects to Google Cloud Storage. We have two customers with this issue, [reported here](https://github.com/googleapis/google-cloud-dotnet/issues/8552).

After fixing the library to report better exceptions, we've got this stack trace:

```text
Exception: Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 'System.Uri'.

StackTrace: at System.Net.Http.Headers.HttpResponseHeaders.get_Location() at
Google.Apis.Upload.ResumableUpload`1.InitiateSessionAsync(CancellationToken cancellationToken) at 
Google.Apis.Upload.ResumableUpload.UploadAsync(CancellationToken cancellationToken) at
Google.Apis.Upload.UploadProgress.ThrowOnFailure(IUploadProgress progress) at
Google.Cloud.Storage.V1.StorageClientImpl.UploadHelper.ExecuteAsync(CancellationToken cancellationToken)
```

I've spend the morning trying to reproduce this or at least understand how it's possible... and I've failed.

There are various ways that a `HeaderStoreItemInfo.ParsedValue` can end up containing a `List<object>` - but I can't see how it's possible for the `Location` header.

### Reproduction Steps

Unfortunately I'm unable to reproduce this.

Information we have about the environments in which it's been observed:

Customer 1:

- Docker Image: mcr.microsoft.com/dotnet/runtime:6.0-alpine
- Precise runtime version unknown

Customer 2:

- .NET runtime 6.0.10 self-contained app
- Running as a CLI via IIS on Windows Server 2019.

I will say that this "uploading a storage object" is the only scenario for which this has been reported. We begin a storage upload
with an [initialization request](https://github.com/googleapis/google-api-dotnet-client/blob/main/Src/Support/Google.Apis/Upload/ResumableUpload.cs#L1135), and we do expect a (single) Location header.

A sample request would look like this:

```text
POST https://storage.googleapis.com/upload/storage/v1/b/[redacted]/o?uploadType=resumable HTTP/1.1
Host: storage.googleapis.com
X-Upload-Content-Type: application/octet-stream
User-Agent: gcloud-dotnet/4.4.0 google-api-dotnet-client/1.60.0.0 (gzip)
x-goog-api-client: gl-dotnet/6.0.0 gccl/4.4.0 gax/4.3.1 gdcl/1.60.0.2742
Authorization: Bearer [redacted]
Accept-Encoding: gzip, deflate
Content-Type: application/json; charset=utf-8
Content-Length: 98

{"bucket":"[redacted]","contentType":"application/octet-stream","name":"issue-8552.txt"}
```

A sample response would look like this:

```text
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
X-GUploader-UploadID: [redacted]
Location: https://storage.googleapis.com/upload/storage/v1/b/[redacted]/o?uploadType=resumable&upload_id=[redacted]
Date: Fri, 03 Mar 2023 10:56:54 GMT
Vary: Origin
Vary: X-Origin
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Pragma: no-cache
Content-Length: 0
Server: UploadServer
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
```

### Expected behavior

If the response contains invalid headers (e.g. multiple locations), I'd expect any of:

- An exception or other failure when parsing the response
- Location to return null
- Location to return the first-parsed location (that's the behavior I see when trying to reproduce)

... but not an InvalidCastException

### Actual behavior

`System.InvalidCastException` trying to cast `List<object>` to `Uri`.

### Known Workarounds

We could potentially catch this and throw a different exception, but it's unlikely we could really proceed.

### Configuration

See Reproduction section.

### Other information

Currently baffled, but very happy to explore any ideas folks might have. I'm *hoping* this is something that a member of the .NET team has seen before. (I haven't found any duplicates, but it wouldn't be the first time I'd failed to find one...)

**Comment by jskeet** [comment]
The area-System.Net.Http is probably the most appropriate one. @dotnet/ncl

**Comment by stephentoub** [comment]
Is it possible the response headers were being accessed concurrently?

**Comment by stephentoub** [comment]
Thanks.

> that we have various HttpMessageHandler aspects going on

Could you point to the src for the handlers in the pipeline?

**Comment by jskeet** [comment]
- Definitely [`ConfigurableMessageHandler`](https://github.com/googleapis/google-api-dotnet-client/blob/main/Src/Support/Google.Apis.Core/Http/ConfigurableMessageHandler.cs)
- Possibly [`TwoWayDelegatingHandler`](https://github.com/googleapis/google-api-dotnet-client/blob/main/Src/Support/Google.Apis.Core/Http/TwoWayDelegatingHandler.cs)
- Probably [`StreamInterceptionHandler`](https://github.com/googleapis/google-api-dotnet-client/blob/main/Src/Support/Google.Apis.Core/Http/StreamInterceptionHandler.cs) somewhere in the chain
- Possibly [`GzipDeflateHandler`](https://github.com/googleapis/google-api-dotnet-client/blob/main/third_party/System.Net.Http/GzipDeflateHandler.cs)

Apologies that it's all so complex - in some scenarios we have to be able to hash content while before it's automatically decompressed. I wouldn't expect any active stream interception on *this* request, which should make the stream interceptor basically a no-op.

**Comment by stephentoub** [comment]
@MihaZupan, any ideas?

**Comment by MihaZupan** [comment]
Seeing this exception I'm immediately 99% sure it's due to concurrent access on the response header collection in .NET 6 (#61798).
But just because the stack trace shows that you hit the exception in your code path, it doesn't necessarily mean your code is doing anything wrong.

Since this is happening for response headers, a case we saw a few times were logging libraries (specifically NewRelic) injecting themselves into the response handling and reading headers on a different thread.
In the linked user report, I see they are using an old version of NewRelic:
```xml
<PackageReference Include="NewRelic.Agent.Api" Version="8.37.0" />
```
NewRelic [fixed](https://github.com/newrelic/newrelic-dotnet-agent/issues/803) their behavior in version `9.2.0`.

To avoid this issue, I would recommend that the user update NewRelic to a recent version, or move to .NET 7.

@lukas-iamd by chance are you also using NewRelic in your project (or as an agent on the machine running your .NET process)?

**Comment by jskeet** [comment]
@MihaZupan: Aha - that's precisely the sort of thing I hoped you'd be able to mention, and thank you (and @stephentoub) so much for your super-quick response. I'll ping "my" issue as well to check the usage of NewRelic.

**Comment by ManickaP** [comment]
I see the original issue was closed, I'm closing this as this seems to be resolved. Thanks.
