### ISSUE TITLE
.NET Logging causing significant slowdown in Unreal 5 build pipeline

### ISSUE THREAD

**Issue by joshberc** [dotnet/runtime#82951]
### Description

We are currently running a nightly build chain for an Unreal engine game. We noticed a significant slowdown in this pipeline after we introduced a new step that increases the number of logs being output to the terminal. A typical build went for ~1 hour to 5+ hours. After many debugging sessions we were able to trace the slowdown to an ILogger object from the Microsoft.Extensions.Logging library. It is instantiated as:
`ILogger _logger;`
The function in question is responsible for iterating over a buffer of logs to match with known events. We originally thought this was the cause, so we commented that out and left only the logging. We still didn't see a decrease in build time we commented out the logging line and saw our build fall below 1 hour again:
```
void ProcessData(bool bFlush)
		{
			_activeTimer.Start();
			int startLineCount = _buffer.Length;
			while (_buffer.Length > 0)
			{
				// Try to match an event
				List<LogEvent>? events = null;
                                /*
				if (Regex.IsMatch(_buffer[0]!, "<-- Suspend Log Parsing -->", RegexOptions.IgnoreCase))
				{
					_matchingEnabled--;
				}
				else if (Regex.IsMatch(_buffer[0]!, "<-- Resume Log Parsing -->", RegexOptions.IgnoreCase))
				{
					_matchingEnabled++;
				}
				else if (_matchingEnabled >= 0)
				{
					events = MatchEvent();
				}

				// Bail out if we need more data
				if (_buffer.Length < 1024 && !bFlush && _buffer.NeedMoreData)
				{
					break;
				}

				if (events != null)
				{
					foreach (Regex ignorePattern in IgnorePatterns)
					{
						if (ignorePattern.IsMatch(_buffer[0]!))
						{
							events = null;
							break;
						}
					}
				}
                                */

				// Report the error to the listeners
				if (events != null)
				{
					WriteEvents(events);
					_buffer.Advance(events.Count);
				}
				else
				{
					//This is the line that increased performance when commented out
                                       //_buffer[0]! refers to a List<string?>() within the buffer object.
					_logger.LogInformation(_buffer[0]!);
                                       //This iterates to the next line in the buffer object.
					_buffer.MoveNext();
				}
			}
			_linesParsed += startLineCount - _buffer.Length;
			_activeTimer.Stop();

			const double UpdateIntervalSeconds = 30.0;
			double elapsedSeconds = _timer.Elapsed.TotalSeconds;
			if (elapsedSeconds > UpdateIntervalSeconds)
			{
				const double WarnPct = 0.5;
				double activeSeconds = _activeTimer.Elapsed.TotalSeconds;
				double activePct = activeSeconds / elapsedSeconds;

				if (activePct > WarnPct)
				{
					_logger.LogInformation(KnownLogEvents.Systemic_LogParserBottleneck, "LogEventParser is taking a significant amount of CPU time: {Active:n1}s/{Total:n1}s ({Pct:n1}%). Processed {NumLines} lines in last {Interval} seconds ({NumLinesInBuffer} in buffer).", activeSeconds, elapsedSeconds, activePct * 100.0, _linesParsed, UpdateIntervalSeconds, _buffer.Length);
				}

				_activeTimer.Reset();
				_timer.Restart();
				_linesParsed = 0;
			}
		}
```

### Configuration
- .NET 6.0
- Windows 10 Professional 64-bit @ Latest
- AMD Ryzen Threadripper 5990X
- 256 GB RAM

### Regression?

- Tried with Microsoft.Extensions.Logging 6.0 & 7.0, roughly the same output with both. Marginally faster with version 7.

### Data

We have been using the built in speed measurement to gauge how long the cooks take. We noticed that we went from:
`LogEventParser is taking a significant amount of CPU time: 17.6s/30.9s (56.9%). Processed 477 lines in last 30 seconds (1 in buffer).`
->
`LogEventParser is taking a significant amount of CPU time: 30.9s/30.9s (100.0%). Processed 15 lines in last 30 seconds (0 in buffer).`

With logging disabled, the build goes through so quickly that this warning is never thrown since the function barely uses any compute time.

### Analysis
We have tried commenting out various sections, changing the method of logging. Originally, the log line was:
`_logger.Log(LogLevel.Information, KnownLogEvents.None, _buffer[0]!, null, (state, exception) => state);`
Even after changing it to LogInformation() we still saw the long builds. The only thing that consistently resolved the inflated build time was commenting out the logging all together.

**Comment by sharwell** [comment]
@joshberc Can you confirm that your console output verbosity is set to minimal (`/v:m`) and that you are collecting a binary log for the verbose data (`/bl`)?

**Comment by joshberc** [comment]
Turned out to be Console.WriteLine() blocking. Implemented solution here(https://stackoverflow.com/questions/3670057/does-console-writeline-block) and problem resolved!

**Comment by tarekgh** [comment]
@joshberc another thing, are you using the [Windows Terminal](https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701?hl=en-us&gl=us&rtc=1) on your machine or the legacy cmd console? I am asking because Windows Terminal is much faster.

**Comment by joshberc** [comment]
@tarekgh This was all being run via CMD. The Console.Writeline() fix managed to get us below previous build times however I will test it in the Windows Terminal out of curiosity :)
