### ISSUE TITLE
Useless GC.SuppressFinalize() calls

### ISSUE THREAD

**Issue by conqu1stador** [dotnet/runtime#82959]
There are some classes in dotnet/runtime that have a GC.SuppressFinalize() call in Dispose(), but no finalizer. 
Some examples:
- https://github.com/dotnet/runtime/blob/81e159e2116e5d41d8d6f298b0e38665207dfd50/src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/FindResult.cs#L48
- https://github.com/dotnet/runtime/blob/81e159e2116e5d41d8d6f298b0e38665207dfd50/src/libraries/System.Net.Http/src/System/Net/Http/HttpContent.cs#L679
- https://github.com/dotnet/runtime/blob/81e159e2116e5d41d8d6f298b0e38665207dfd50/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/HashAlgorithm.cs#L167

Is this a mistake or not? If so, should these calls be removed?

**Comment by conqu1stador** [comment]
If so, should these calls be deleted?

**Comment by sharwell** [comment]
> Is this a mistake or not?

If the type is publicly inheritable, a derived type could add a finalizer. The base type remains responsible for the call to `GC.SuppressFinalize()`.
