### ISSUE TITLE
[Blazor] WASM GC

### ISSUE THREAD

**Issue by daniel-p-tech** [dotnet/runtime#82974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Are you planning on taking advantage of the WASM GC implementation in .NET 8? How much is it going to reduce the initial size and load time (biggest pain points of this technology) of a minimal Blazor app? 

https://seb.deleuze.fr/the-huge-potential-of-kotlin-wasm/#the-upcoming-wasmgc-revolution
https://github.com/WebAssembly/proposals#phase-4---standardize-the-feature-wg 

### Describe the solution you'd like

Same as above.

**Comment by En3Tho** [comment]
this is being discussed https://github.com/WebAssembly/gc/issues/77

**Comment by lakani** [comment]
Looking forward to see this in dotnet 8

**Comment by pavelsavara** [comment]
https://github.com/WebAssembly/gc/issues/77 is the current state we are in. We will keep eye on wasm GC in the future.
