### ISSUE TITLE
[API Proposal]: Add TryRent to ArrayPool<T>

### ISSUE THREAD

**Issue by miroslavp** [dotnet/runtime#82995]
### Background and motivation

I would like to rent an array from `ArrayPool<T>`, but only if there is such already in the pool. I don't want the ArrayPool to add new instances to the pool if such is not present. There are parts in my code where I want to use this as an optimization without increasing the ArrayPool size. 

### API Proposal

```csharp

public bool TryRent(int minimumLength, out T[] array);

```

### API Usage

```csharp
var pool = ArrayPool<ulong>.Shared;
if (pool.TryRent(100, out var array)
{
   //do something with the array and return it
}
else
{
    //manually allocate one with new
}
```

### Alternative Designs

Alternative design would be something like this
```csharp
public T[] RentIfAvailable(int minimumLength);
```
where returned value would be `null` if array with suitable length is not available in the pool

**Comment by Clockwork-Muse** [comment]
> API Usage

... this is already what the pool does.  In the context of your larger usage, why would this be a net benefit?

**Comment by alexrp** [comment]
> ... this is already what the pool does.

The way I read the proposal, the issue is that with `Rent()`, you can't tell if the array was actually rented or freshly created. So if (for some reason) you don't want to return the array to the pool in the freshly allocated case, you can't really do that. I'm not sure *why* you would want to do that, though.

**Comment by Clockwork-Muse** [comment]
Sure, but if your code is doing that it's probably a smell in the "does two things" category.

**Comment by huoyaoyuan** [comment]
> I don't want the ArrayPool to add new instances to the pool if such is not present.

For the default ArrayPool implementation, it does not record "instances in the pool". It just reuses arrays you returned to it. It starts with the state that no arrays in it.

The implementation is also tolerant. Renting without returning is not a fatal error. The pool does not tracks the array and it will be collected by GC finally. Returning a non-rented array is also not fatal.

**Comment by miroslavp** [comment]
> It just reuses arrays you returned to it. It starts with the state that no arrays in it.

As I understand it, you have to **Rent** it first, **before** calling the **Return** method. And when you call Rent and there's no array in the pool with suitable length, it creates one. Isn't that what the ArrayPool<T> does?

> Renting without returning is not a fatal error. The pool does not tracks the array and it will be collected by GC finally. Returning a non-rented array is also not fatal.

According to the documentation:
 `Failure to return a rented buffer is not a fatal error. However, it may lead to decreased application performance, as the pool may need to create a new buffer to replace the lost one.`
 The thing is, **I don't want the pool to create a new buffer to replace the lost one**.
 
Let me give you an example. There are two places in my code that will heavily use `ulong[]`. One of it will use ArrayPool<T>.Rent to rent arrays with random length between 100_000 and 1_000_000 elements. The other will allocate arrays with length starting from 100_000 elements and gradually grow to length of **more than** 5_000_000 elements.

 I want the second part of the code to rent an array from the pool if only one is already rented and returned by the first part of the code. Otherwise it should create one with the `new` operator. That way, the second part by using TryRent(), will not put arrays larger than 1_000_000 elements into the pool and at the same time will take advantage of the arrays that are already returned to the pool by the first part of the code.

**Comment by miroslavp** [comment]
I just noticed that there's such API already planned for `ObjectPool<T>`https://github.com/dotnet/runtime/issues/49680

It would be nice if we have it for `ArrayPool<T>` as well

**Comment by Clockwork-Muse** [comment]
> Basically the first part should call Rent() and Return() and the second one should call only TryRent() (i.e. should not add new arrays to the pool)

Don't use the shared pool, [create your own pool](https://learn.microsoft.com/en-us/dotnet/api/system.buffers.arraypool-1.create?view=net-7.0#system-buffers-arraypool-1-create(system-int32-system-int32)):

```csharp
var limitedPool = ArrayPool.Create(/* max elements in rented array */ 1_000_000, /* max number of arrays */ 10);
```

You can "rent" an array larger than the pool has (will `new()` one up, nothing in the pool), then return it (which will drop it, since it's too large).

**Comment by Clockwork-Muse** [comment]
For that matter, you could create multiple pools:

```csharp
var smallPool = ArrayPoolCreate(5_000_000, 1);
```
... for the "rarely used" case, if you do end up using such an array multiple times.

**Comment by miroslavp** [comment]
@Clockwork-Muse 
Custom pool won't help me, because there is another problem that I think I didn't explain well which is:
The second part of the code allocates way more frequently than the first part (which allocates relatively small random lengths) and most of the time allocates larger array on every new request ("expands" an array) which I think is not suitable for `ArrayPool<T>` usage, because the `ArrayPool<T>` will need to allocate every time a new one on Rent(). This is the reason why I want TryRent(). I want it to rent an array if it is already available, otherwise I don't want it to fill the pool with thousands of new instances.

Correct me if I'm wrong, but if I have an empty pool and I Rent sequentially arrays with the following lengths (5,10,15,20,25,30,35....) it will always create new ones in the pool, right? That's the behavior I want to avoid.

**Comment by miroslavp** [comment]
Basically, my aim is to benefit from `TryRent()` by reusing arrays when possible and prevent overallocation of new arrays in the pool. Can't explain it simpler than that. It is kind of optimization.

**Comment by Joe4evr** [comment]
> Correct me if I'm wrong, but if I have an empty pool and I Rent sequentially arrays with the following lengths (5,10,15,20,25,30,35....) it will always create new ones in the pool, right? That's the behavior I want to avoid.

Not always. I'm relatively sure you always get the next power of 2, so asking for 10 will give you a size of 16, and if you return that before asking for 15, the 16-size one will be reused. Similarly, 20, 25, and 30 can all use the same 32-sized allocation, etc.

**Comment by miroslavp** [comment]
> > Correct me if I'm wrong, but if I have an empty pool and I Rent sequentially arrays with the following lengths (5,10,15,20,25,30,35....) it will always create new ones in the pool, right? That's the behavior I want to avoid.
> 
> Not always. I'm relatively sure you always get the next power of 2, so asking for 10 will give you a size of 16, and if you return that before asking for 15, the 16-size one will be reused. Similarly, 20, 25, and 30 can all use the same 32-sized allocation, etc.

Thanks! Based on your response I searched and found [this](https://segmentfault.com/a/1190000040611144/en) article which explains in details the internal implementation of `ArrayPool<T>`. The good thing is that the actual internal implementation addresses my biggest concerns.
Thank you @Joe4evr! Closing this issue ...

**Comment by Clockwork-Muse** [comment]
> Correct me if I'm wrong, but if I have an empty pool and I Rent sequentially arrays with the following lengths (5,10,15,20,25,30,35....) it will always create new ones in the pool, right? That's the behavior I want to avoid.

Even ignoring the power-of-two behavior (which is strictly speaking an implementation detail), the benefits of a pool will only be realized if your use case supports it.  If you only have one instance calling the second allocation path, you may as well use an `ArrayList`, or just use a pool capped at a lower size.  Suggesting a more tightly limited instance pool with support for larger sizes was based on the assumption you'd have multiple instances with similar/identical growth patterns
