### ISSUE TITLE
Optimize threadpool paths in CoreCLR used by ASP.NET

### ISSUE THREAD

**Issue by vancem** [dotnet/runtime#8299]
See  the profile 
```
\\clrmain\tools\PerfView.exe \\clrmain\public\PerfInvestigations\17-01-25.AspNet.TechEmpower\Data.05-30\json.wrk.Asp.2.0.sockets.CPU.1040K.18s.coreclr.perfView.xml.zip
```
You will see that 
```
module coreclr <<coreclr!Thread::intermediateThreadProc>>
```
uses 1351 msec (approximate 1-2% of the total CPU time in a Techempower benchmark).   There is just alot of 'goo' that is between the OS getting a callback on a socket and the managed code getting called.   

@stephentoub  @geoffkizer

**Comment by kouvel** [comment]
I think most of the overhead has been eliminated by now with several changes. One was to remove overhead from entering/exiting an AppDomain, there may have been others. A couple other changes moved to a mostly managed implementation of the thread pool, which avoids the frequent long call chain but there wasn't much overhead left there by then.
