### ISSUE TITLE
SourceGen build errors if JsonSerializableAttribute argument name 'type' is included

### ISSUE THREAD

**Issue by andrewdbond** [dotnet/runtime#82997]
### Description

In System.Text.Json:

```C#
[JsonSerializable(typeof(SerializedClass))]
```

builds successfully. However, if the argument *name* (`type:`) is added:

```C#
[JsonSerializable(type: typeof(SerializedClass))]
```

the build fails.

### Reproduction Steps

1. Run `dotnet new console`
2. Use the following code in Program.cs:

```C#
using System.Text.Json.Serialization;

Console.WriteLine("Hello, World!");

public class SerializedClass
{
}

[JsonSourceGenerationOptions]
[JsonSerializable(type: typeof(SerializedClass))]
internal partial class SourceGenerationContext : JsonSerializerContext
{
}
```

3. Run `dotnet build`

### Expected behavior

Build is successful.

### Actual behavior

The build fails with:

> CSC : warning CS8785: Generator 'JsonSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidOperationException' with message 'Sequence contains more than one element' [projectFolder\project.csproj]

> projectFolder\Program.cs(11,24): error CS0534: 'SourceGenerationContext' does not implement inherited abstract member 'JsonSerializerContext.GeneratedSerializerOptions.get' [projectFolder\project.csproj]

> projectFolder\Program.cs(11,24): error CS0534: 'SourceGenerationContext' does not implement inherited abstract member 'JsonSerializerContext.GetTypeInfo(Type)' [projectFolder\project.csproj]

### Known Workarounds

Remove the argument *name* (`type:`).

### Configuration

* .NET 7
* Windows 11, version 22H2
* Architecture: x64

**Comment by eiriktsarpalis** [comment]
I can reproduce in .NET 8.
