### ISSUE TITLE
.Net 4.8 fails with 7.0.1 ProtectedData's binding redirect.

### ISSUE THREAD

**Issue by tdhintz** [dotnet/runtime#83008]
### Description

.Net 4.8 windows service project fails to run after upgrading from system.security.cryptography.protecteddata 7.0.0 to 7.0.1 via NuGet if "Auto-generate binding redirects" is enabled on the project.  Fusion reports that the assembly is located but a redirect to 7.0.0.1 failed because the manifest doesn't match the requested version.

### Reproduction Steps

Create a .Net 4.8 project with "Auto-generate binding redirects" that uses ProtectedData and provision ProtectedData 7.0.1 from NuGet.  The following exception is thrown:

System.IO.FileLoadException: Could not load file or assembly 'System.Security.Cryptography.ProtectedData, Version=7.0.0.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'System.Security.Cryptography.ProtectedData, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

### Expected behavior

The assembly binding should succeed.

### Actual behavior

The following exception is thrown:

System.IO.FileLoadException: Could not load file or assembly 'System.Security.Cryptography.ProtectedData, Version=7.0.0.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'System.Security.Cryptography.ProtectedData, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

### Regression?

Reverting to the 7.0.0 NuGet works fine.

### Known Workarounds

Reverting to the 7.0.0 NuGet works fine, or don't use auto-generated binding redirects and manually set a binding redirect.

### Configuration

.Net 4.8, x64, Windows Server 2012 R2.

**Comment by ViktorHofer** [comment]
Hello @tdhintz. This might have been fixed recently with https://github.com/dotnet/runtime/commit/c8503d39053f9e0d94716a23c406b66f126ca259. Can you try this again with the [latest 8.0.0 Preview version of `System.Security.Cryptography.ProtectedData`](https://www.nuget.org/packages/System.Security.Cryptography.ProtectedData) and let us know? Thanks

**Comment by tdhintz** [comment]
Since the assembly has a whole new major number I assume 8.0 does not (yet) show the problem.  I'm not planning to try it.  7.0.1 remains broken.

**Comment by ViktorHofer** [comment]
> Since the assembly has a whole new major number I assume 8.0 does not (yet) show the problem. I'm not planning to try it. 7.0.1 remains broken.

ping @tdhintz as we want to understand and fix the broken scenario. Can you please share a full repro as I wasn't able to reproduce the issue myself.
