### ISSUE TITLE
Mutex constructor always outputs createdNew param as true on Ubuntu

### ISSUE THREAD

**Issue by LJN-hzleaper** [dotnet/runtime#83014]
### Description

Mutex constructor always outputs createdNew param as true on Ubuntu. 

### Reproduction Steps

Run two instances of following program at same time.
```
Mutex _mutex = new Mutex(true, "ConsoleNet_50698", out bool isNew);
_mutex.WaitOne();
Console.WriteLine("isNew:" + isNew);
Console.ReadKey();
_mutex.ReleaseMutex();
_mutex.Dispose();
```

### Expected behavior

One process output "isNew:True" and the other output "isNew:False".

### Actual behavior

Both output "isNew:True" on Ubuntu on arm64 and x64.

### Configuration

.NET 6.0.406
Ubuntu 20.04
Arm64 and x64

**Comment by janvorli** [comment]
@LJN-hzleaper the name of the Mutex you are creating indicates that its visibility is local to the current session. Have you launched the two processes e.g. from two different SSH sessions? If you want a Mutex that is global over multiple login sessions, you need to prefix it with `Global\`. See https://learn.microsoft.com/en-us/dotnet/api/system.threading.mutex.-ctor?view=net-7.0, the "Remarks" section.

**Comment by LJN-hzleaper** [comment]
@janvorli After adding prefix `Global\` my code works as expected. Thanks.
