### ISSUE TITLE
[API Proposal]: `Vector.Contains(scalar)`, `.IndexOf(scalar)` and `LastIndexOf(scalar)`

### ISSUE THREAD

**Issue by neon-sunset** [dotnet/runtime#83010]
### Background and motivation

Today, `ReadOnly/Span<T>` extensions offer a rich set of APIs suitable both for high level and low level processing - `Contains`, `IndexOf`, `IndexOfAny`, `LastIndexOf`, and etc. Using those, developers can be sure to get both good performance and usability.

However, if for some reason the desired behavior is not covered by the above (e.g. counting special characters in chunks with extra handling once found), it is necessary to write quite involved implementation by hand with `VectorXXX` APIs. Such implementation may either have to be a full vectorized loop or a workaround employing slicing and re-slicing spans to use existing span extensions which has its own drawbacks and overhead.

In general, cross-platform `VectorXXX` extensions in .NET 7 and `Span<T>` methods significantly reduce the effort required for fast processing of spans, but it seems there are still areas where additional QoL improvements can be offered.

Proposal specifically targets `Vector<T>` as a higher-level abstraction. There might be sense to add parity with `VectorXXX` despite most of its users not much benefiting since these can be written in a couple of lines - feedback on this is welcomed.

### API Proposal

```csharp
namespace System.Numerics;

public static partial class VectorExtensions
{
    public bool Contains<T>(this Vector<T> vector, T value);

    public int IndexOf<T>(this Vector<T> vector, T value);
    
    public int LastIndexOf<T>(this Vector<T> vector, T value);
}
```

### API Usage

```csharp
var span = GetSpanOf<int>();
var remainderLength = span.Length % Vector<int>.Count;
var vectorized = MemoryMarshal.Cast<int, Vector<int>>(span[..^remainderLength]);
var remainder = span[^remainderLength..];

foreach (var vector in vectorized)
{
    var index = vector.IndexOf(valueOfInterest);
    if (index >= 0)
    {
        // Do something with index
    }
    else if (vector.Contains(controlValue))
    {
        // Signal control value found
    }
}

foreach (var element in remainder)
{
    // Handle remainder
}
```

### Alternative Designs

N/A, providing implementation in user code or via third-party packages is possible.

### Risks

N/A

**Comment by tannergooding** [comment]
`Contains` is effectively already exposed as `EqualsAny`, there isn't any "real" benefit to also exposing the same thing as `Contains`.

`IndexOf` and `LastIndexOf` is one where the general concept today is `Compare, ExtractMostSignificantBits` and then you can check against `zero` to see "no match" or against an exact pattern to see "number of matches". You can use `LeadingZeroCount`, `TrailingZeroCount`, or `PopCount` to get the first/last index or total count from there.

With `VectorMask<T>` we should get "equivalent" functionality available to variable width vectors, such as `Vector<T>` and that should itself have a few helpers to simplify the three basic mask checks.

There might still be "some" benefit to exposing `IndexOf` and `LastIndexOf`, but in general they represent "more work" than you typically want for such APIs and it opens the doors to people asking for anything exposed on `Span<T>` to also be exposed on `Vector<T>`.

I'd, in general, prefer for `Span<T>` and `ROSpan<T>` to be the primary way users operate on arbitrary memory and with `Vector<T>` and `Vector64/128/256/512<T>` being the low-level primitives used to achieve that. Thus, you may have to be a bit more explicit in your handling when working with the lower level primitives.

**Comment by tannergooding** [comment]
Going to close this for the time being given the reasoning above.

`Contains` is already exposed via `EqualsAny`.

`IndexOf` and `LastIndexOf` will likely only be supported via the `VectorMask<T>` APIs. There is potential room for a more direct helper to be exposed, but in general this seems like something we can look at after `VectorMask<T>` has shipped if users find it problematic.
