### ISSUE TITLE
The default name of the configuration file is not uniform

### ISSUE THREAD

**Issue by kelilife** [dotnet/runtime#83022]
### Description

Whether you install the nuget package or manually add a configuration file or create a project or modify property values or whatever, you may trigger the generation of a configuration file. Especially for App.config files, their case is not uniform, and different programming languages may create different generated configuration files. This is extremely confusing and bad, and is ignored elsewhere, so I'm putting it here in the hope that it can be fixed.

In addition, I found that some of the new file templates are of the configuration file type, and the configuration file name should have lowercase initials. But the visual studio sample files violate this default rule.

### Reproduction Steps

There are no steps, it's a matter of normative confusion. Not so well expressed, I hope you can understand in place.

### Expected behavior

Generate case-sensitive file names inconsistently

### Actual behavior

Generate case-sensitive file names inconsistently

### Configuration

.NET Framework

**Comment by steveharter** [comment]
> Whether you install the nuget package or manually add a configuration file or create a project or modify property values or whatever

Please create separate issues for each of the cases you found (Nuget, etc) and try to assign the repo \ location as appropriate since this issue was automatically moved to the Configuration area which does not automatically create app.config files.
