### ISSUE TITLE
Fatal error. Internal CLR error. (0x80131506) in .NET 6

### ISSUE THREAD

**Issue by Feralnex** [dotnet/runtime#83027]
### Description

Running [this project](https://github.com/Feralnex/MemoryManagementTest) in .net 6 causes **Fatal error. Internal CLR error. (0x80131506)** (probably using unmanaged memory causes error during normal object memory allocation).

### Configuration

Windows 10 64-bit
.Net 6.0.403 version

### Regression?

Don't know about previous version, but in .net 7 it doesn't occur (on few attempts it didn't break)

### Other information

As far as I know the program breaks when allocating normal **Test** objects in the memory (first for loop).

**Comment by janvorli** [comment]
I think the issue is in the actual application. If I understand it correctly, it is creating reference objects out of the GC heap allocating their space using `Marshal.AllocHGlobal`. I don't think this is valid from our GC perspective. @PeterSolMS  / @Maoni0 please correct me if I am wrong.

**Comment by Feralnex** [comment]
Maybe it's not valid but it's weird that in version 7.0 it works just fine... I hope it's a bug because I would like to use it in version 6.0 if possible

**Comment by PeterSolMS** [comment]
I agree with @janvorli that the application is doing something invalid. It's allocating unmanaged memory, putting a managed object there, and tries to treat this fake managed object like a regular managed object. This confuses the GC - the fact that it crashes most of the time in 6.0 and doesn't crash in 7.0 is an accident. I don't believe it is a bug in either version. The garbage collector expects managed objects to reside on the managed heap.

**Comment by Feralnex** [comment]
So it doesn't concern You that in one version it works completely fine and breaks down in the other one?

**Comment by mangod9** [comment]
If you try hard enough it would AV in 6.0 as well. Just depends on specific conditions and allocation patterns.

**Comment by PeterSolMS** [comment]
Under 7.0 you would likely crash in a slightly more complicated scenario. One problematic case would be if your object in unmanaged memory actually points back at an object in the GC heap, and that object is removed or moved by the GC.

@Feralnex, Could you explain what you were trying to accomplish? Maybe we can suggest another solution.

**Comment by Feralnex** [comment]
GC.TryStartNoGCRegion under 6.0 version max value of totalSize parameter is 255648868 (above System.ArgumentOutOfRangeException is thrown) and under 7.0 version it takes even long.MaxValue... Why it takes long under 6.0 version in the first place when You can't even pass int.MaxValue?

**Comment by cshung** [comment]
`GC.TryStartNoGCRegion` is a preallocation-based solution. Basically, the GC asks the operating system for as much memory as you wish, and then the user application will use those. As long as the preallocated memory is not exhausted, the system will not be paused by the GC.

The difference between .NET 6 and .NET 7 is reflecting an implementation constraint in .NET 6 or below. In earlier versions, our data structure is restricted to having only one segment for ephemeral generations, so there is only so much we could prep the data structure for allocations. In .NET 7 we allow more than one region for Gen0, so we can use as much as your computer can do.

Eventually, the preallocated memory will be used up, and when that happens, we will do a blocking GC to clear all that up. That GC will be long because we have accumulated so much garbage to collect. 

Besides the NoGC region, you might also want to consider frozen segments, which allow you to put managed objects on unmanaged memory. The feature is currently private, but it is regularly [tested](https://github.com/dotnet/runtime/blob/main/src/tests/GC/API/Frozen/Frozen.cs) and consumed internally. The test also gives you the limitation to what you could do safely to those objects.

**Comment by Feralnex** [comment]
@cshung tested frozen segments and it breaks down almost the same way as my example. When You cross some threshold of new objects in the managed memory then an engine execution exception is thrown. For example try adding to [this](https://github.com/dotnet/runtime/blob/main/src/tests/GC/API/Frozen/Frozen.cs) code in the beginning of the main:

```cs
private static unsafe int Main()
        {
            Node[] firstArray = new Node[30000000];

            for (int index = 0; index < firstArray.Length; index++)
                firstArray[index] = new Node();

            IntPtr methodTable = typeof(Node).TypeHandle.Value;

[...]
```
and it wil break down under both versions (6.0 and 7.0) I think. At least my previous attempt worked under version 7.0, Yours doesn't work at all it seems...

**Comment by Feralnex** [comment]
Had some time to test more cases and even this short code snippet throws engine exception under 6.0 version

```cs
internal class Node
    {
        public Node next;
        public int number;
    }

    internal static class Program
    {
        private static unsafe void Main()
        {
            Node[] firstArray = new Node[30000000];
            IntPtr buffer = Marshal.AllocHGlobal(GetObjectSize(typeof(Node).TypeHandle.Value));
            Node node = Unsafe.AsRef<Node>(&buffer);

            for (int index = 0; index < firstArray.Length; index++)
                firstArray[index] = new Node();

            Marshal.FreeHGlobal(buffer);
        }

        private static unsafe short GetObjectSize(IntPtr methodTable)
        {
            IntPtr pointerToSize = methodTable + 4;
            return *((short*)pointerToSize);
        }
    }
```
Are You sure it's working as intended? I noticed that the engine exception is thrown when allocating more managed memory then some sort of threshold (unknown for me), when You specify smaller size for the array above (like 5000) everything works just fine. (Zero problems under 7.0 version)

**Comment by cshung** [comment]
You need to leave a pointer size at the very beginning of the buffer, see https://github.com/dotnet/runtime/blob/35f87ecf04416831c5675617b2bda4e2a031592f/src/tests/GC/API/Frozen/Frozen.cs#L92

The runtime expects every object to have that pointer-sized word so that it can use it for its purpose.

This code seems to work for me:

```c#
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

internal class Node
{
    public Node next;
    public int number;
}

internal static class Program
{
    private static unsafe void Main()
    {
        Node[] firstArray = new Node[30000000];

        short size = GetObjectSize(typeof(Node).TypeHandle.Value);
        IntPtr buffer = Marshal.AllocHGlobal(size + IntPtr.Size);
        IntPtr allocated = buffer + IntPtr.Size;
        Node node = Unsafe.AsRef<Node>(&allocated);

        for (int index = 0; index < firstArray.Length; index++)
            firstArray[index] = new Node();

        Marshal.FreeHGlobal(buffer);
    }

    private static unsafe short GetObjectSize(IntPtr methodTable)
    {
        IntPtr pointerToSize = methodTable + 4;
        return *((short*)pointerToSize);
    }
}
```

My test code seems to have a bug with the allocation of the second object, I should make sure every object has that `IntPtr.Size` before it. I will make a change there.

Note that this is still not correct code. You need to register that buffer with the GC as a frozen segment so that it knows it has to by-pass it where it should.

The allocation threshold and .NET 6/7 thing is mostly moot. The key is probably whether or not a GC happened. You can easily force a GC to happen using `GC.Collect()` and you will likely get the same behavior regardless of allocation/.NET version.

**Comment by Feralnex** [comment]
> @cshung tested frozen segments and it breaks down almost the same way as my example. When You cross some threshold of new objects in the managed memory then an engine execution exception is thrown. For example try adding to [this](https://github.com/dotnet/runtime/blob/main/src/tests/GC/API/Frozen/Frozen.cs) code in the beginning of the main:
> 
> ```cs
> private static unsafe int Main()
>         {
>             Node[] firstArray = new Node[30000000];
> 
>             for (int index = 0; index < firstArray.Length; index++)
>                 firstArray[index] = new Node();
> 
>             IntPtr methodTable = typeof(Node).TypeHandle.Value;
> 
> [...]
> ```
> 
> and it wil break down under both versions (6.0 and 7.0) I think. At least my previous attempt worked under version 7.0, Yours doesn't work at all it seems...

Still adding allocation in managed memory gives error in Your Frozen Segment example... Maybe it didn't break for You because You need to increase size for that array with managed objects?

**Comment by Feralnex** [comment]
> You need to leave a pointer size at the very beginning of the buffer, see
> 
> https://github.com/dotnet/runtime/blob/35f87ecf04416831c5675617b2bda4e2a031592f/src/tests/GC/API/Frozen/Frozen.cs#L92
> 
> The runtime expects every object to have that pointer-sized word so that it can use it for its purpose.
> 
> This code seems to work for me:
> 
> ```cs
> using System.Runtime.InteropServices;
> using System.Runtime.CompilerServices;
> 
> internal class Node
> {
>     public Node next;
>     public int number;
> }
> 
> internal static class Program
> {
>     private static unsafe void Main()
>     {
>         Node[] firstArray = new Node[30000000];
> 
>         short size = GetObjectSize(typeof(Node).TypeHandle.Value);
>         IntPtr buffer = Marshal.AllocHGlobal(size + IntPtr.Size);
>         IntPtr allocated = buffer + IntPtr.Size;
>         Node node = Unsafe.AsRef<Node>(&allocated);
> 
>         for (int index = 0; index < firstArray.Length; index++)
>             firstArray[index] = new Node();
> 
>         Marshal.FreeHGlobal(buffer);
>     }
> 
>     private static unsafe short GetObjectSize(IntPtr methodTable)
>     {
>         IntPtr pointerToSize = methodTable + 4;
>         return *((short*)pointerToSize);
>     }
> }
> ```
> 
> My test code seems to have a bug with the allocation of the second object, I should make sure every object has that `IntPtr.Size` before it. I will make a change there.
> 
> Note that this is still not correct code. You need to register that buffer with the GC as a frozen segment so that it knows it has to by-pass it where it should.
> 
> The allocation threshold and .NET 6/7 thing is mostly moot. The key is probably whether or not a GC happened. You can easily force a GC to happen using `GC.Collect()` and you will likely get the same behavior regardless of allocation/.NET version.

It's really weird, in release mode it works, but in debug mode it breaks...

**Comment by cshung** [comment]
> It's really weird, in release mode it works, but in debug mode it breaks...

To make debugging easier, the register allocator is explicitly instructed to extend the lifetime of all local variables to the whole method. In release mode, It is likely that `node` is stored on a register and then gets reused by some other values (such as the temp for storing `new Node()` and never reported to the GC as a live reference, while it is always reported as a live reference in debug mode, that might explain the difference.

See my blog entry [here](https://cshung.github.io/posts/false-memory-leak/) to learn more about variable lifetime and GC reporting.
 
Reporting frozen objects to the GC as live references should be supported. It is a bug if it doesn't.

**Comment by Feralnex** [comment]
@cshung So basically if You modify [this](https://github.com/dotnet/runtime/blob/main/src/tests/GC/API/Frozen/Frozen.cs) code by updating Allocate method

```cs
public IntPtr Allocate(IntPtr methodTable)
{
    if (_allocated == IntPtr.Zero)
    {
        throw new Exception("Segment already built");
    }
    int objectSize = GetObjectSize(methodTable);
    if ((_allocated + objectSize).CompareTo(_limit) > 0)
    {
        throw new Exception("OutOfCapacity");
    }

    IntPtr* pMethodTable = (IntPtr*)_allocated;
    *pMethodTable = methodTable;
    IntPtr result = _allocated + IntPtr.Size;
    _allocated = _allocated + objectSize + IntPtr.Size;
    return result;
}
```

and by adding instructions to the beggining od the main

```cs
private static unsafe int Main()
{
    Node[] firstArray = new Node[30000000]; //or bigger size if it is not breaking - should try running code couple of times

    for (int index = 0; index < firstArray.Length; index++)
        firstArray[index] = new Node();

    IntPtr methodTable = typeof(Node).TypeHandle.Value;

    [...]
```

and it throws engine errors then there should be a fix in the near future for it? Because it's literally how it is right now... If the changes that I've made to the Allocate method are wrong then let me know.

**Comment by cshung** [comment]
The crash is understood and https://github.com/dotnet/runtime/pull/83623 will fix it.

**Comment by Feralnex** [comment]
@cshung Thanks, can't wait for fix ^^
