### ISSUE TITLE
Issue HttpListenerRequestUriBuilder.GetPath throw ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by answergithub** [dotnet/runtime#83020]
### Description

> System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
>    at System.String.Substring(Int32 startIndex, Int32 length)
>    at System.Net.HttpListenerRequestUriBuilder.GetPath(String uriString)
>    at System.Net.HttpListenerRequestUriBuilder.BuildRequestUriUsingRawPath()
>    at System.Net.HttpListenerRequestUriBuilder.Build()
>    at System.Net.HttpListenerRequest.FinishInitialization()
>    at System.Net.HttpConnection.OnReadInternal(IAsyncResult ares)
>    at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Net.ContextAwareResult.Complete(IntPtr userToken)
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()

.Net Core 3.1.417, CentOS

### Reproduction Steps

> var httpListener = new HttpListener();
> httpListener.Prefixes.Add("http://*:8888/");
> HttpListenerContext context = null;
> while (true)
> {
> context = await this.httpListener.GetContextAsync();
> // handle context
> }

### Expected behavior

no exception thrown

### Actual behavior

exception thrown

**Comment by MihaZupan** [comment]
Are there specific requests you can reproduce this with?

Note that .Net Core 3.1 is out of support, can you reproduce this issue on .Net 7?

**Comment by answergithub** [comment]
I don't have specific requests to reproduce this bug. Those requests may come from something like network monitors, who randomly send requests to random ports.

Well I will consider upgrade to .Net 7 in the future

**Comment by MihaZupan** [comment]
The only known issue that would cause this is if the uri did not have a slash after the host - https://github.com/dotnet/runtime/issues/72748#issuecomment-1193409251. This was fixed in .Net 7.

If there are other cases where this may occur, we would need more information. Ideally a way to reproduce the issue, or a network capture when the problem occurs.

**Comment by answergithub** [comment]
Ok. I will upgrade to .Net 7 as soon as possible.
