### ISSUE TITLE
[browser] Fix encoding problem when publishing with AOT

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#83035]
Follow-up for https://github.com/dotnet/runtime/pull/82833. AOT case.

- Add AOT tests the same way as in the previous PR
- Fix `wasm-ld : error : /root/helix/work/workitem/e/wbt/pztditip.fs4/obj/Debug/net8.0/browser-wasm/wasm/for-publish/driver.o: undefined symbol: mono_aot_module_build_publish_Debug煉_info `

**Comment by maraf** [comment]
We need to update multiple places

- https://github.com/dotnet/runtime/blob/9fd3ece652fed473c9f2398363da6d7bca41a5d9/src/tasks/AotCompilerTask/MonoAOTCompiler.cs#L1027-L1028
- https://github.com/dotnet/runtime/blob/c0765d33251414ec276cbde2629f9b49b00059ab/src/mono/mono/mini/aot-compiler.c#L12121
- https://github.com/dotnet/runtime/blob/c0765d33251414ec276cbde2629f9b49b00059ab/src/mono/mono/mini/mini-llvm.c#L13624
