### ISSUE TITLE
Different behavior of string.StartsWith under Net481 and Net7.0

### ISSUE THREAD

**Issue by lellid** [dotnet/runtime#83049]
### Description

Under net481, the function string.StartsWith sometimes returns false, when it should return true. This is the case if the string contains Unicode characters.
This behavior is different from the behavior under net7.0.

### Reproduction Steps

Consider the following code:
```
const string firstPart = "ABC";
var s = firstPart + (char)0x1365;
foreach (StringComparison comparisonType in Enum.GetValues(typeof(StringComparison)))
{
    Console.WriteLine($"{comparisonType}: {s.StartsWith(firstPart, comparisonType)}");
}
```

### Expected behavior

The expected result would be `True` for all values of `StringComparison`.

### Actual behavior

The resulting output (net481) is:
```
CurrentCulture: False
CurrentCultureIgnoreCase: False
InvariantCulture: False
InvariantCultureIgnoreCase: False
Ordinal: True
OrdinalIgnoreCase: True
```

The resulting output (net7.0) is what I would expect:
```
CurrentCulture: True
CurrentCultureIgnoreCase: True
InvariantCulture: True
InvariantCultureIgnoreCase: True
Ordinal: True
OrdinalIgnoreCase: True
```

### Known Workarounds

Use StringComparison.Ordinal or StringComparison.OrdinalIgnoreCase to work around the problem.

### Configuration

Architecture: x64
Net Framework 4.8.1
Windows 10 Pro Build 19045, German UI culture

**Comment by EgorBo** [comment]
Starting from .NET 5.0 we switched to ICU (from NLS) on Windows, see https://learn.microsoft.com/en-us/dotnet/core/compatibility/globalization/5.0/icu-globalization-api

You can restore old behavior by adding:
```xml
<ItemGroup>
  <RuntimeHostConfigurationOption Include="System.Globalization.UseNls" Value="true" />
</ItemGroup>
```
to your csproj

**Comment by tarekgh** [comment]
@lellid this a bug in Windows collation tables. The .NET Framework is just calling Windows for string comparisons in general. In your case, the failures happen when doing linguistic comparisons (non-ordinal cases). Having the `Ethiopic Colon U+1365` affected the sort of weight of the previous letter `C`. Unfortunately, .NET Framework doesn't have control on the collation behavior. You may consider logging a bug to Windows through Windows Feedback Hub.
