### ISSUE TITLE
Unable to build .NET 7 MAUI projects with .NET 8 SDK and workloads

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/runtime#83045]
### Description

Install our latest .NET 8 Preview 2 builds:
* Download from: https://github.com/dotnet/installer
* Install MAUI:

```
sudo dotnet workload install maui --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json --source https://api.nuget.org/v3/index.json --source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-0d02a9fc/nuget/v3/index.json --source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-e013e98b/nuget/v3/index.json --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json --from-rollback-file https://gist.githubusercontent.com/rmarinho/f80804afceac1d5becebe6de295c3c2f/raw/0d2af48741eea8e3dc2a61ddc6876a145b57ca60/rollback.json --verbosity diag
```

* `dotnet new maui` to create a new project
* Add a `nuget.config` with additional sources:
```xml
    <add key="dotnet8" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json " />
    <add key="dotnet7" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json " />
```
* Edit the `.csproj` to make everything `net7.0`
* `dotnet build -bl`

Build fails with:

```
error NETSDK1178: The project depends on the following workload packs that do not exist in any of the workloads available in this installation: Microsoft.NETCore.App.Runtime.AOT.Cross.net7.ios-arm Microsoft.NETCore.App.Runtime.AOT.Cross.net7.ios-arm64 Microsoft.NETCore.App.Runtime.AOT.Cross.net7.iossimulator-arm64 Microsoft.NETCore.App.Runtime.AOT.Cross.net7.iossimulator-x64 Microsoft.NETCore.App.Runtime.AOT.Cross.net7.iossimulator-x86
error NETSDK1178: You may need to build the project on another operating system or architecture, or update the .NET SDK.
```

I believe the issue might be something with the Mono workload authoring. I can't find the mentioned pack:

```
ls /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.AOT.Cross.net7.iossimulator-x64
ls: /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.AOT.Cross.net7.iossimulator-x64: No such file or directory
```

### Reproduction Steps

I wrote those above.

### Expected behavior

You can build `net7.0` MAUI apps with a .NET 8 SDK.

### Actual behavior

Doing so results in errors about `Microsoft.NETCore.App.Runtime.AOT.Cross.net7` packs.

### Regression?

This works in .NET 7, you can build `net6.0-*` MAUI projects.

### Known Workarounds

Change all `net7.0` `$(TargetFramework)` to `net8.0` instead.

### Configuration

```
dotnet --version
8.0.100-preview.2.23153.6
```

**Comment by jonathanpeppers** [comment]
Oh wait, @rolfbjarne, I found:

```
cat /usr/local/share/dotnet/sdk-manifests/8.0.100-preview.2/microsoft.net.sdk.ios/WorkloadManifest.json
...
"extends": [
				"microsoft-net-runtime-ios",
				"microsoft-net-runtime-ios-net6",
			]
```

So maybe we are just missing `microsoft-net-runtime-ios-net7`?

**Comment by rolfbjarne** [comment]
> So maybe we are just missing `microsoft-net-runtime-ios-net7`?

Testing out this locally now.

**Comment by steveisok** [comment]
> > So maybe we are just missing `microsoft-net-runtime-ios-net7`?
> 
> Testing out this locally now.

if that doesn't work, @jonathanpeppers do you have the right darc feed with the stable net7 packages?

**Comment by rolfbjarne** [comment]
> > So maybe we are just missing `microsoft-net-runtime-ios-net7`?
> 
> Testing out this locally now.

Looks like this is it, I'll get the fix in preview 2.

@jonathanpeppers does net7.0-android already work?

**Comment by jonathanpeppers** [comment]
It appears Android works if I remove `net7.0-ios` and `net7.0-maccatalyst` from the project.

**Comment by steveisok** [comment]
OK, since this isn't a runtime issue, I think it's safe to close.

**Comment by rolfbjarne** [comment]
For reference this is our PR for preview 2: https://github.com/xamarin/xamarin-macios/pull/17725
