### ISSUE TITLE
src/mono/wasm/debugger/DebuggerTestSuite/TestHarnessProxy.cs(135,44): error CS8601: Possible null reference assignment.

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#83048]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=192960
Build error leg or test failing: Build / browser-wasm linux Release Mono_DebuggerTests_chrome / Build product
Pull request: https://github.com/dotnet/runtime/pull/82957

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by lewing** [comment]
this was fixed in https://github.com/dotnet/runtime/pull/82958
