### ISSUE TITLE
FileStream.SetLength doesn't return file pointer to original value on failure

### ISSUE THREAD

**Issue by azhmur** [dotnet/runtime#8307]
In case someone need reserve disk space before writing to file obvious strategy is following:

```csharp
  var fileStream = new FileStream();
  while (*)
  {
    try 
    {
       fileStream.SetLength();
       fileStream.Write();
    }
    catch ( out of space )
    {
    }
  }
```

But unfortunately on real out of disk space situation SetLength doesn't restore position, so on next interation succesfull SetLength restores incorrect position (EOF) and Write goes beyong supposed end of file.

I suppose to add try/finally statement for position restoration in SetLengthCore, to make this behaviour safer. I think moving position is uninteded and exists as work around for WinAPI incompleteness. I can make PR if this change is supposed to be approved.

https://github.com/dotnet/coreclr/blob/684784fdb929f2c7d0173a317cb6e3ac6dc29d1a/src/mscorlib/shared/System/IO/FileStream.Win32.cs#L444

PS Unix version seems to be calling unnecessary seeks. FTruncate doesn't need it. It seems like copy-pasting from Win32 version.
https://linux.die.net/man/2/truncate

**Comment by Jozkee** [comment]
Fixed by https://github.com/dotnet/runtime/pull/44170 (Windows) and https://github.com/dotnet/runtime/pull/44097 (Unix).
