### ISSUE TITLE
HostFxr loading assembly for each call to load_assembly_and_get_function_pointer 

### ISSUE THREAD

**Issue by ArthurVasseur** [dotnet/runtime#83071]
I am currently using the hdt_load_assembly_and_get_function_pointer delegate, as shown in this code snippet: (https://github.com/ConcertoEngine/ConcertoDotNet/blob/9fd1d1aaf4f6880079c53e229470aea40c9de37f/Src/HostFXR.cpp#L105)

This function returns an Assembly class, which is responsible for obtaining a function pointer from the assembly and calling that function, as shown here: (https://github.com/ConcertoEngine/ConcertoDotNet/blob/9fd1d1aaf4f6880079c53e229470aea40c9de37f/Include/Assembly.hpp#L44)

However, each call to load_assembly_and_get_function_pointer results in the assembly being loaded, which takes approximately 30 ms. This is a performance issue that needs to be addressed.

Is there a way to load the assembly only once and keep it in memory, so that we can provide this assembly to the function pointer and avoid loading the assembly every time?

I have already implemented a cache that stores the function pointer in a map<string, void*).

**Comment by vitek-karas** [comment]
As pointed out above the function will not load the assembly if it's already loaded (by it in previous invocation). So that should not be the root of the perf problems.

How did you measure the 30ms duration? Is it only the call to `load_assembly_and_get_function_pointer` or is it something else?
(On the first call, the duration can be heavily influenced by AV software if it decides to scan the assembly).

> I have a last question : do you know if there is a way to inherit from a c++ class in C#

No - the memory management models of the two environment don't match (C# classes must all be managed by GC, which is obviously not going to work with C++ and vice-versa).

Well to be precise, it is maybe possible with C++/CLI, but I would recommend to not use that technology if you don't have to (and definitely not for new code). For one, it only works on Windows.

**Comment by ArthurVasseur** [comment]
The measured time is for the first call of this function : 
```cpp
template<typename T>
T* GetFunctionPointerFromAssembly(const std::string& functionName)
{
	std::string dotnetType = _assemblyName + ".Lib, " + _assemblyName;
	std::wstring wdotnetType(dotnetType.begin(), dotnetType.end()); //TODO: cross platform support
	std::wstring wfunctionName(functionName.begin(), functionName.end()); //TODO: cross platform support
	T* functionPointer = nullptr;
	std::filesystem::path path = std::filesystem::current_path() / _assemblyPath;
	int rc = _load_assembly_and_get_function_pointer(
		reinterpret_cast<const char_t*>(path.wstring().c_str()),
		reinterpret_cast<const char_t*>(wdotnetType.c_str()),
		reinterpret_cast<const char_t*>(wfunctionName.c_str()),
		nullptr,
		nullptr,
		(void**)&functionPointer);
	if (rc != 0)
		throw std::runtime_error("Failed to load function pointer : '" + functionName + "', error code : " +
			std::to_string(rc));
	return functionPointer;
}

auto start = std::chrono::high_resolution_clock::now();
auto function = assembly.GetFunctionPointerFromAssembly<int(void*, int)>("Hello");
auto end = std::chrono::high_resolution_clock::now();
std::cout << "Time taken for execution: "  << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << " milliseconds" << std::endl;
```

The measured time time is around 20ms and 30ms

**Comment by vitek-karas** [comment]
It's really hard to comment on the expected duration for this operation - it's heavily dependent on the assembly in question, the hardware and so on. If this is a problem for you, you could try to profile it (probably with native profiling tools, as I would expect most of the time to be spent in native code for this) and see where it spends most of the time.

**Comment by ArthurVasseur** [comment]
Okay, thanks for you help ! For the moment it's not a real problem.
