### ISSUE TITLE
Why is Numerics missing most of the geometries?

### ISSUE THREAD

**Issue by Gavin-Williams** [dotnet/runtime#83083]
Numerics provides Plane, but you don't have any other geometries. Why?

Update: Just to expand on this question. Many packages implement their own math's libraries. When MS released Numerics, that went some way to provide a go-to solution for math's. I saw developers start saying things like 'next major release will see a switch to Numerics'. It's a core need, so it makes sense. But working with geometries is also a huge need. Without even getting into physics, we need geometric functions for intersection testing, ray-hitting, spacial-culling. It's so wide a need! And with the Plane type I can see that you started considering this, but just stopped? 

I'm not sure what you mean by including Plane type and no other types. Clearly the following types are almost universally needed..

* aabox
* box
* sphere
* ray
* frustum
* quad
* triangle

Just some explanation would be good. Is expanding on geometrics something you intend to do? Or did you mistakenly include Plane in Numerics? Should we request it be removed or should we request other types be added?

**Comment by tannergooding** [comment]
> Should we request it be removed or should we request other types be added?

The types were initially including some core concepts from XNA. Please feel free to open API suggestions for other types following the same general API shape, etc.
