### ISSUE TITLE
ILLink analyzer produces both IL3000 and IL3002 for AssemblyName.CodeBase method

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#83088]
The original intention for `IL3000` was to provide a better diagnostics for calls to `Assembly.Location`, `AssemblyName.CodeBase` and `AssemblyName.EscapedCodeBase`. Later on, `AssemblyName.CodeBase` and `AssemblyName.EscapedCodeBase` where annotated with `RequiresAssemblyFile` attribute.

This leads to the analyzer reporting both `IL3000` and `IL3002` warnings for accesses to these properties.

**Comment by agocke** [comment]
@jtschuster Could you look when you get a chance (after higher priority work).

**Comment by vitek-karas** [comment]
I'm like 50% there to have a fix for this. Sorry I didn't mention it here.
