### ISSUE TITLE
AV during System.Net.Http.Functional.Tests on windows x86

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#83098]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=195488
Build error leg or test failing: System.Net.Http.Functional.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/83068

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "exit code -1073741819",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```
Seems like failure is in the xunit host runtime?

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[196238](https://dev.azure.com/dnceng-public/public/_build/results?buildId=196238)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=196238&view=ms.vss-test-web.build-test-results-tab&runId=3707919&resultId=209602)|dotnet/runtime#83104|
|[195950](https://dev.azure.com/dnceng-public/public/_build/results?buildId=195950)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=195950&view=ms.vss-test-web.build-test-results-tab&runId=3704435&resultId=209606)|dotnet/runtime#82832|
|[195915](https://dev.azure.com/dnceng-public/public/_build/results?buildId=195915)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=195915&view=ms.vss-test-web.build-test-results-tab&runId=3704161&resultId=209606)|dotnet/runtime#83032|
|[195762](https://dev.azure.com/dnceng-public/public/_build/results?buildId=195762)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=195762&view=ms.vss-test-web.build-test-results-tab&runId=3702041&resultId=209606)|dotnet/runtime#82765|
|[195639](https://dev.azure.com/dnceng-public/public/_build/results?buildId=195639)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=195639&view=ms.vss-test-web.build-test-results-tab&runId=3701476&resultId=209606)|dotnet/runtime#82833|
|[195553](https://dev.azure.com/dnceng-public/public/_build/results?buildId=195553)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=195553&view=ms.vss-test-web.build-test-results-tab&runId=3699604&resultId=209602)|dotnet/runtime#82832|
|[195516](https://dev.azure.com/dnceng-public/public/_build/results?buildId=195516)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=195516&view=ms.vss-test-web.build-test-results-tab&runId=3699206&resultId=209606)|dotnet/runtime#82045|
|[195488](https://dev.azure.com/dnceng-public/public/_build/results?buildId=195488)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=195488&view=ms.vss-test-web.build-test-results-tab&runId=3699069&resultId=209602)|dotnet/runtime#83068|
|[195248](https://dev.azure.com/dnceng-public/public/_build/results?buildId=195248)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=195248&view=ms.vss-test-web.build-test-results-tab&runId=3696524&resultId=209773)|dotnet/runtime#82179|
|[195180](https://dev.azure.com/dnceng-public/public/_build/results?buildId=195180)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=195180&view=ms.vss-test-web.build-test-results-tab&runId=3696001&resultId=209606)|dotnet/runtime#82970|
|[195111](https://dev.azure.com/dnceng-public/public/_build/results?buildId=195111)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=195111&view=ms.vss-test-web.build-test-results-tab&runId=3695287&resultId=209602)|dotnet/runtime#82867|
|[194932](https://dev.azure.com/dnceng-public/public/_build/results?buildId=194932)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=194932&view=ms.vss-test-web.build-test-results-tab&runId=3693670&resultId=209581)||
|[194884](https://dev.azure.com/dnceng-public/public/_build/results?buildId=194884)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=194884&view=ms.vss-test-web.build-test-results-tab&runId=3693329&resultId=209584)|dotnet/runtime#83041|
|[194859](https://dev.azure.com/dnceng-public/public/_build/results?buildId=194859)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=194859&view=ms.vss-test-web.build-test-results-tab&runId=3693213&resultId=209584)|dotnet/runtime#82826|
|[194556](https://dev.azure.com/dnceng-public/public/_build/results?buildId=194556)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=194556&view=ms.vss-test-web.build-test-results-tab&runId=3690337&resultId=209580)|dotnet/runtime#82833|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|11|15|15|

**Comment by wfurt** [comment]
dup of #83110. closing this one as the other has more details.
