### ISSUE TITLE
[API Proposal]: ArrayPool based MemoryStream 

### ISSUE THREAD

**Issue by ladeak** [dotnet/runtime#83105]
### Background and motivation

`MemoryStream` currently uses a byte array for backing data. When the underlying array's capacity is not enough a new array is allocated and data is copied to the new array.

I would like to use MemoryStream on a hot path as a temporary storage. The size required for this temporary storage is not known upfront. I need a temporary storage due to limitations of 3rd party libraries for example:

```csharp
using var ms = MemoryStream();
ThirdPartySerializer.Serialze(ms, new object());
ms.Position = 0;
SomeOtherApi.Send(ms);
```

To avoid allocations, I would pool the MemoryStream objects. However, if I pool them, they hold onto the underlying byte array, and the size of the byte array may only ever grow.

Hence, I would like to propose a memory backed stream, which uses `ArrayPool<byte>.Shared` to rent the underlying storage while being used. It may also avoid additional copy when expanding the underlying array using a similar idea that is already used by `StringBuilder`. Such a construct may fit nicely with the existing `ReadOnlySequence<T>` API as well.

It might also provide a good option to bridge the API of types in `System.Buffers` and streaming APIs.

### API Proposal

```csharp
namespace System.IO;

public class ArrayBufferStream : Stream, IBufferWriter<byte>
{
    // Readable, Writable, Seekable stream
    // Might consider returning a `ReadOnlySequence<byte>`
}
```

### API Usage

```csharp
private ObjectPool<ArrayBufferStream<byte>> _pool = ObjectPool.Create<ArrayBufferStream<byte>>(new Policy());
// ...

var ms = _pool .Get();
try
{
    ThirdPartySerializer.Serialze(ms, new object());
    ms.Position = 0;
    SomeOtherApi.Send(ms);
}
finally
{
    _pool .Return(ms);
}
```
Usage should not differ from a regular stream.

### Alternative Designs

The reason I cannot use an ArrayPool directly:

- The `ThirdPartySerializer` might not support bare arrays.
- Cannot tell the required space upfront.

`System.IO.Pipelines.Pipe`:

- While the underlying implementation is similar to what I have on mind, the semantics of the API is too complex for this use-case.

**Comment by stephentoub** [comment]
Thanks.  This looks like a duplicate of https://github.com/dotnet/runtime/issues/22428.

**Comment by DaZombieKiller** [comment]
An implementation of this is available on the [`ArrayPoolBufferWriter<T>`](https://learn.microsoft.com/en-us/dotnet/api/communitytoolkit.highperformance.buffers.arraypoolbufferwriter-1) type from the .NET Community Toolkit, simply create an instance and use the [`AsStream`](https://learn.microsoft.com/en-us/dotnet/api/communitytoolkit.highperformance.arraypoolbufferwriterextensions.asstream) extension method:
```cs
using var writer = new ArrayPoolBufferWriter<byte>();
using var stream = writer.AsStream();
// ...
```

**Comment by ladeak** [comment]
@stephentoub  thanks for pointing to the duplicate. Although I explicitly searched for "ArrayPool MemoryStream", not sure how I missed it the existing issue.

Closing this now, if you feel there is a reason to keep it open, please re-open.
