### ISSUE TITLE
[wasm] Build - better integrate with `publish`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#83108]
- thus better consuming publish output, instead of using special items like `WasmExtraFilesToDeploy`
- And accordingly adjust the use of these items in wasi builds

**Comment by pavelsavara** [comment]
For context: 
For browser WasmFilesToIncludeInFileSystem is to VFS and WasmExtraFilesToDeploy is to web server.
For wasi VFS doesn't exist https://github.com/dotnet/runtime/issues/81418. And there is no web server.

**Comment by lewing** [comment]
@maraf feel free to update this with your current thinking or close it

**Comment by maraf** [comment]
Assigning back after offline discussion

**Comment by maraf** [comment]
I'm going to close this one as Wasm SDK is already using standard items (same as blazor) and the remaining bits for WasmAppBuilder tracked in other issues
