### ISSUE TITLE
System.Text.Json: The converter for derived type 'T' does not support metadata writes or reads.

### ISSUE THREAD

**Issue by jaliyaudagedara** [dotnet/runtime#83148]
### Describe the bug
Consider the below code example. Here I am trying to create a Converter, where when Serializing I need to exclude the `ActionIdentifier` from being serialized (can't use `[JsonIgnore]` attribute, because it's `required` property). But I am unable to create a Converter for polymorphic deserialization.

### To Reproduce
```csharp
[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(InitializeVariable), typeDiscriminator: nameof(InitializeVariable))]
public class WorkflowAction
{
    public required string ActionIdentifier { get; set; }
}

public class InitializeVariable : WorkflowAction { }

public class WorkflowActionJsonConverter : JsonConverter<WorkflowAction>
{
    public override WorkflowAction Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options)
    {
        // some code
    }

    public override void Write(
        Utf8JsonWriter writer,
        WorkflowAction objectToWrite,
        JsonSerializerOptions options)
    {
        // some code
    }
}

WorkflowAction initializeVariable = new InitializeVariable
{
    ActionIdentifier = "InitializeVariable_1"
};

var jsonSerializerOptions = new JsonSerializerOptions
{
    WriteIndented = true,
    PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    Converters =
    {
        new WorkflowActionJsonConverter()
    },
};

// Unhandled exception. System.NotSupportedException: The converter for derived type 'WorkflowAction' does not support metadata writes or reads.
string jsonString = JsonSerializer.Serialize(initializeVariable, jsonSerializerOptions);
```

### Stack Trace
 
> Unhandled exception. System.NotSupportedException: The converter for derived type 'WorkflowAction' does not support metadata writes or reads.
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_BaseConverterDoesNotSupportMetadata(Type derivedType)
   at System.Text.Json.Serialization.Metadata.PolymorphicTypeResolver..ctor(JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureLocked|143_0()
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Boolean resolveIfMutable)
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at Program.<Main>$(String[] args) in C:\Users\Jaliya\Desktop\ConsoleApp1\ConsoleApp1\Program.cs:line 56
   
### Workaround

Without using a converter, I was able to do something like below using the Contract Model.

```csharp
var jsonSerializerOptions = new JsonSerializerOptions
{
    WriteIndented = true,
    PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    TypeInfoResolver = new DefaultJsonTypeInfoResolver
    {
        Modifiers =
        {
            static typeInfo =>
            {
                foreach (JsonPropertyInfo propertyInfo in typeInfo.Properties)
                {
                    propertyInfo.ShouldSerialize = (parent, value) => propertyInfo switch
                    {
                        { Name: "actionIdentifier" }  => false,
                        _ => true
                    };
                }
            }
        }
    }
};

string jsonString = JsonSerializer.Serialize(initializeVariable, jsonSerializerOptions);
```

**Comment by eiriktsarpalis** [comment]
This is by design -- polymorphism attributes only work for types that make use of the built-in converters. Once you apply a custom converter these and any other STJ attributes will be ignored, since the converter is solely responsible for driving serialization.

**Comment by jaliyaudagedara** [comment]
Makes sense, thanks @eiriktsarpalis!
