### ISSUE TITLE
TraceSwitch can have inconsistent internal state 

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#83153]
### Description

`TraceSwitch` class is inherited from `Switch` class. `Switch` class has a property called `Value` which used to be a protected property in .NET 6.0 and became a public property in .NET 7.0. If the user creates `TraceSwitch` object and then call `Value` property. This operation will reflect also on the property `Level`. In other meaning, `Value` and `Level` must be in-sync. 
The problem is when the user set the `Level` property, this operation will not affect the `Value` property and the internal state of the object will have inconsistency. 

This problem is affecting users who use TraceSwitch with the configuration. You may look at the issue https://github.com/dotnet/runtime/issues/82998 for the details how this problem is affecting the configuration. 

### Reproduction Steps

```C#
            TraceSwitch ts = new TraceSwitch("Name", "Description");
            Console.WriteLine($"Level: {ts.Level}, Value: {ts.Value}"); // Level: Off, Value: 0

            ts.Value = "1"; // Error value
            Console.WriteLine($"Level: {ts.Level}, Value: {ts.Value}"); // Level: Error, Value: 1. Level is changed according to the Value

            ts.Level = TraceLevel.Info;
            Console.WriteLine($"Level: {ts.Level}, Value: {ts.Value}"); // Level: Info, Value: 1. Value didn't change :-(
```

### Expected behavior

When changing the `Level` it should get reflected on the `Value` and vice versa. 

### Actual behavior

When changing the `Level` it is not affecting the `Value` property.

### Regression?

After Exposing `Value` property in .NET 7.0 and not synchronizing the `Level` and `Value` values, this had a side effect on the configuration and causing a regression. The issue https://github.com/dotnet/runtime/issues/82998 has more details about this regression.

### Known Workarounds

For configuration regression, can set the `Value` and `Level` in the configuration. Look at the comment https://github.com/dotnet/runtime/issues/82998#issuecomment-1455341742 for more details.

### Configuration

.NET 7.0 on any OS with any architecture.

**Comment by ViktorHofer** [comment]
@tarekgh would you have time to help with this issue? I assume we want to backport a fix to .NET 7 as well.

**Comment by tarekgh** [comment]
@ViktorHofer I have submitted the PR https://github.com/dotnet/runtime/pull/89278 to fix this issue. I prefer to delay servicing this fix to .NET 7.0 till we find more reports or demand. 

CC @carlossanlop
