### ISSUE TITLE
Some hardware intrinsic ILLInk.Substitution entries may be unnecessary

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#83164]
As per https://github.com/dotnet/runtime/pull/83040#discussion_r1130168735, some of the ILLink.Substitution entries may be unnecessary since corelib already compiles in a different copy of the ISAs (`*.PlatformNotSupported.cs`) which return constant `false`.

We should double check that removing these are ok and make the files shorter if possible.

-- Noting the `Vector64/128/256/512` entries are needed since they do not return constant false and are instead recursive by default.

**Comment by jkotas** [comment]
> copy of the ISAs (*.PlatformNotSupported.cs) which return constant false.

These methods are marked with `[Intrinsic]` attribute. I believe that it is make AltJit work, among other things.

Linker does not look at bodies of methods marked `[Intrinsic]. The IL of these methods often does not match what the method actually does. The substitution is required to tell the linker what the method actually does.

**Comment by tannergooding** [comment]
Thanks for the info! Will close this as unnecessary then.
