### ISSUE TITLE
Nested classes in System.Runtime.Intrinsics are missing xml doc comments

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#83165]
The various `*.X64` and `*.Arm64` nested classes in the `System.Runtime.Intrinsics.*` namespace are missing XML doc comments and should be updated to have them.

**Comment by carlossanlop** [comment]
Let me check. These assemblies might be affected by the issue I'm trying to fix with https://github.com/dotnet/runtime/pull/82554

**Comment by michaelgsharp** [comment]
@carlossanlop did you ever end up checking?

**Comment by michaelgsharp** [comment]
Nevermind, I just did and it looks like they are still missing.

**Comment by carlossanlop** [comment]
Can you please remind me if this was a problem in the compiled xml intellisense files, or if is this a problem in the porting tool?

**Comment by michaelgsharp** [comment]
@tannergooding do you remember?

**Comment by carlossanlop** [comment]
> Nevermind, I just did and it looks like they are still missing.

What did you check here?

**Comment by michaelgsharp** [comment]
I just went to the docs repo and checked for the various `xml/ns-System.Runtime.Intrinsics.*.xml` files and they are still missing. Unless they won't have their own files, but even the main [xml/ns-System.Runtime.Intrinsics.xml](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/ns-System.Runtime.Intrinsics.xml) is missing info about them.

**Comment by tannergooding** [comment]
This was an issue in that they never had XML documents added in the first place.
