### ISSUE TITLE
SourceLink info missing from unmanaged CLR PDBs

### ISSUE THREAD

**Issue by pharring** [dotnet/runtime#83184]
### Description

I'm working on diagnostic tooling that uses SourceLink to locate sources in open source repositories.
While managed assemblies in the .NET runtime have SourceLink information, this appears to be missing from native (unmanaged) DLLs.
For example, coreclr.dll has no SourceLink information in its corresponding PDB, coreclr.pdb
I also checked clrjit.dll, hostpolicy.dll, hostfxr.dll, so I suspect it's all C++ (unmanaged) binaries.

### Reproduction Steps

Use https://github.com/pharring/SourceLinkCheck to build the SourceLinkCheck tool.
Run it on coreclr.pdb (downloaded from the public symbol servers)

I tried it on
.NET 6 (6,0,1423,7309 @Commit: 2a90daa2cc41ae8f11a2c1519cb8b235f609251a)
and
.NET 7 (7,0,323,6910 @Commit: 0a2bda10e81d901396c3cff95533529e3a93ad47)

Neither have SourceLink information. This breaks "go to source" for the native pieces of the CLR.

### Expected behavior

SourceLink information should be available for native CLR binaries.

### Actual behavior

No source link information found.

### Regression?

No.

### Known Workarounds

By convention, the Win32 file version happens to have the git commit ID in it. If you know your way around GitHub, I suppose you could compose a raw URI to the source. It seems a bit fragile, though.

### Configuration

Windows

**Comment by jkotas** [comment]
Did you verify that your tool works on unmanaged assemblies?

We do attach the source link .json to unmanaged assemblies here: https://github.com/dotnet/runtime/blob/340508f5c750d190090be93f0c731b1a8055a354/eng/native/configurecompiler.cmake#L82-L83

**Comment by jkotas** [comment]
This was implemented by .NET 7 change https://github.com/dotnet/runtime/pull/66677, so it is expected that it does not work for .NET 6.

**Comment by jkotas** [comment]
> .NET 7 (7,0,323,6910 @Commit: https://github.com/dotnet/runtime/commit/0a2bda10e81d901396c3cff95533529e3a93ad47)

I can see sourcelink blob in coreclr.pdb for this commit `{"documents":{"D:\\a\\_work\\1\\s\\*":"https://raw.githubusercontent.com/dotnet/runtime/0a2bda10e81d901396c3cff95533529e3a93ad47/*"}}`. windbg is able to find sources using this sourcelink info successfully.

**Comment by pharring** [comment]
Ah, thanks. Could be a bug in my checker tool. I thought I had it covered, but will re-check.

**Comment by pharring** [comment]
Yes, this is a deficiency in Microsoft.DiasymReader.Native which is used by my SourceLinkCheck tool.
https://github.com/pharring/SourceLinkCheck/issues/1
