### ISSUE TITLE
TimeZoneInfo.FindSystemTimeZoneById fails to find "Europe/Kyiv"

### ISSUE THREAD

**Issue by kikaragyozov** [dotnet/runtime#83188]
### Description

The timezone "Europe/Kiev" in August 2022 was changed to be "Europe/Kyiv". This change should long be present in .NET, but it doesn't seem that to be the case? Tested on .NET 7.

### Reproduction Steps

Writing `TimeZoneInfo.FindSystemTimeZoneById("Europe/Kyiv");` throws an exception.

### Expected behavior

No exception to be thrown.

### Actual behavior

An exception is thrown.

### Known Workarounds

Catch `"Europe/Kyiv"` and change it to the old name `"Europe/Kiev"`.

**Comment by huoyaoyuan** [comment]
.NET queries the OS/ICU library to provide such information. It is expected to see a delay of the sources.

**Comment by Clockwork-Muse** [comment]
Also, OS matters here, so we'd need that information for any potential troubleshooting.  Windows tends to lag more in this area than Linux.

**Comment by tarekgh** [comment]
@huoyaoyuan is correct about we depend on ICU in such cases for the Time Zone information. So, it is matter of time this get updated in ICU and reflected on the .NET automatically.
