### ISSUE TITLE
[API Proposal]: MemoryMarshal.CreateReadOnlySpan that takes `in` param

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#83191]
### Background and motivation

Currently `CreateReadOnlySpan` takes a `ref` so if a readonly field is passed it needs to first go via `Unsafe.AsRef(in` which seems an unnecessary friction of converting the type to non readonly.

### API Proposal

```csharp
namespace System.Runtime.InteropServices;

public static partial class MemoryMarshal
{
    public static ReadOnlySpan<T> CreateReadOnlySpan<T>(scoped in T reference, int length);
}
```

### API Usage

```csharp
// Fancy the value
readonly int _value;

MemoryMarshal.CreateReadOnlySpan(in _value, 1);
```

**Comment by stephentoub** [comment]
Yup, what @Sergio0694 said.  And even if we wanted to we couldn't add the proposed method; we can't overload based on ref vs in.

**Comment by tannergooding** [comment]
Closing this as inactionable at the moment. We can revisit if the language adds support for `ref readonly`
