### ISSUE TITLE
Directory.Delete() fails with "Could not find a part of the path" when deleting files from SMB share in Azure durable function

### ISSUE THREAD

**Issue by rhensing-code** [dotnet/runtime#83202]
We have a durable function with an Activity that simply deletes a directory and it is occasionally throwing this exception (I assure you the path exists):

[TriageWindowsMainDeleteAction] -  Could not find a part of the path 'C:\mounts\data\expanded\directory_to_delete'.

Stack Trace:
   at System.IO.FileSystem.GetFindData(String fullPath, Boolean isDirectory, Boolean ignoreAccessDenied, WIN32_FIND_DATA& findData)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at 
WindowsOrchestrator.WindowsMainActions.WindowsMainDeleteAction(IDurableActivityContext context, ILogger logger) in C:\Users\rhensing\source\repos\foo\WindowsMainActions.cs:line 92

We have an Azure files share mounted to a Windows azure function in a bring your own storage configuration using this command:
az webapp config storage-account add --name <Function App Name> --resource-group <Resource Group Name> --subscription <Subscription Id> --custom-id <Any string> --storage-type AzureFiles --account-name <Storage Account Name> --share-name data --access-key <Storage Access Key> --mount-path /mounts/data

I am extracting compressed files to a sub-folder in that 'data' share (mounted as c:\mounts\data to the app service plan host) and then simply doing a Directory.Delete(folder, true) on the path (i.e. 'C:\mounts\data\expanded\directory_to_delete').

The function app runs as an MSI with contributor role in the sub and has full permissions to delete the folder.
 
What we are seeing is that 90% of the time this works fine and the folder is removed but under load if I stress this code path by submitting multiple concurrent requests at a time to the root orchestrator a couple of the requests will fail and we'll get the exception above.

When the exception occurs the contents of the folder are removed but the top-level folder remains and is empty.  The only workaround we've found is to sleep 5 seconds and then try the same delete again at which point that top-level folder under the 'expanded' folder is finally removed.

We have a main orchestrator function that we call and this performs a fan-out to some activities that are awaited.  Once those activities are finished - the 'delete folder' activity is the final activity that is called like this:

await context.CallActivityAsync(nameof(WindowsMainActions.WindowsMainDeleteAction), functionsDto);

Inside of this activity it literally just does a Directory.Delete(folder,true) like this:
Directory.Delete(functionsDto.SourceFolder, true);

**Comment by rhensing-code** [comment]
Have not tried this from outside of .net yet.
Can I run process monitor a functions host?


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by danmoseley** [comment]
> Can I run process monitor a functions host?

You'd have to ask the functions team -- I don't know. It needs to run elevated on the machine, so perhaps not.

**Comment by Jozkee** [comment]
Replied offline:

I think it is near-impossible to tell for us, .NET, where the failing piece may be with only that information. 

This is using too much Azure jargon I'm not familiar with. From what I understand, you have an Azure file share mounted to an Azure function on which Directory.Delete(path) fails.

If you could somehow obtain a minimal consistent repro, I could gladly take a look.

Will close this issue for now.
