### ISSUE TITLE
[API Proposal]: System.Numerics Distance, Vector, Math Operations

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/runtime#83209]
### Backgound and motivation

[System.Numerics](https://learn.microsoft.com/en-us/dotnet/api/system.numerics?view=net-8.0) is a powerful library in .NET that provides support for mathematical operations on vectors, matrices, and complex numbers. Because these are [SIMD-enabled types](https://learn.microsoft.com/dotnet/standard/simd), operations on those types can be optimized. The library already contains a wide range of mathematical operations, but there are some common operations that are missing. In this proposal, we propose the addition of APIs to System.Numerics for the following operations: 

- Distance Metrics
	- **Cosine Similarity**
	- **Euclidean Distance**: An implementation is already in [System.Numerics](https://learn.microsoft.com/en-us/dotnet/api/system.numerics.vector2.distance?view=net-8.0#system-numerics-vector2-distance(system-numerics-vector2-system-numerics-vector2)) but limited to vectors of size 2-4
- Vector Operations
	- **Dot Product**: already in [System.Numerics](https://learn.microsoft.com/en-us/dotnet/api/system.numerics.vector.dot?view=net-8.0) but limited to vectors.
	- **Normalize (L2 / Euclidean Length)**
- Math Operations
	- **Softmax**
	- **Sigmoid**
	- **Tanh**: Already in [System.Math](https://learn.microsoft.com/en-us/dotnet/api/system.mathf.tanh?view=net-8.0) but only on scalars.
	- **Exponential**. Already in [System.Math](https://learn.microsoft.com/en-us/dotnet/api/system.mathf.exp?view=net-8.0) but only for scalars.

By providing a common optimized implementation for these operations, .NET library authors and developers can focus on high-level components of their application.

### API proposal

The following are the proposed APIs for the operations listed above. 

Additional details:

| Property | Value |
| --- | --- |
| Expected Vector Size | 1-8191|
| Precision | FP32, FP16, INT8 |

#### Cosine Similarity

Cosine similarity is a measure of similarity between two non-zero vectors of an inner product space. It is widely used in natural language processing and information retrieval. The proposed API will take two floating point collections as input and return the cosine similarity between them. 

```csharp
// Assembly System.Numerics.Vectors
namespace System.Numerics;

public static T CosineSimilarity<T>(ReadOnlySpan<T> vector1, ReadOnlySpan<T> vector2)
	
public static T CosineSimilarity<T>(T[] vector1, T[] vector2)
	
public static T CosineSimilarity<T>(Vector<T> vector1, Vector<T> vector2)
```

#### Euclidean Distance

Euclidean distance is a measure of distance between two points in a Euclidean space. It is widely used in mathematics, engineering, and machine learning. The proposed API will take two floating point collections as input and return the euclidean distance between the collections. 

```csharp
// Assembly System.Numerics.Vectors
namespace System.Numerics;

public static T EuclideanDistance<T>(ReadOnlySpan<T> vector1, ReadOnlySpan<T> vector2)
	
public static T EuclideanDistance<T>(T[] vector1, T[] vector2)
	
public static T EuclideanDistance<T>(Vector<T> vector1, Vector<T> vector2)
```

#### Dot Product

Dot product is a mathematical operation that takes two vectors and returns a scalar. It is widely used in linear algebra and machine learning. The proposed API will take two floating point collections as input and return the dot product of the vectors.

```csharp
// Assembly System.Numerics.Vectors
namespace System.Numerics;

public static T Dot<T>(ReadOnlySpan<T> vector1, ReadOnlySpan<T> vector2)

public static T Dot<T>(T[] vector1, T[] vector2)

public static T Dot<T>(Vector<T> vector1, Vector<T> vector2)
```

#### Normalize (L2 / Euclidean Length)

Normalize is a mathematical operation that takes a vector and returns a unit vector in the same direction. It is widely used in linear algebra and machine learning. The proposed API will take a vector as input and return the normalized vector. 

```csharp
// Assembly System.Numerics.Vectors
namespace System.Numerics;

public static ReadOnlySpan<T> Normalize<T>(ReadOnlySpan<T> vector)

public static T[] Normalize<T>(T[] vector)

public static Vector<T> Normalize<T>(Vector<T> vector)
```

#### Softmax

Softmax is a function that takes a collection of real numbers and returns a probability distribution. It is widely used in machine learning and deep learning. The proposed API will take a real number collection as input and return the softmax of the collection. 

```csharp
// Assembly System.Numerics.Vectors
namespace System.Numerics;

public static ReadOnlySpan<T> Softmax<T>(ReadOnlySpan<T> vector)

public static T[] Softmax<T>(T[] vector)

public static Vector<T> Softmax<T>(Vector<T> vector)
```

#### Sigmoid

Sigmoid is a function that takes a real number and returns a value between 0 and 1. It is widely used in machine learning and deep learning. The proposed API will take a real number collection as input and return the sigmoid of the number for each element in the collection. 

```csharp
// Assembly System.Numerics.Vectors
namespace System.Numerics;

public static ReadOnlySpan<T> Sigmoid<T>(ReadOnlySpan<T> vector)

public static T[] Sigmoid<T>(T[] vector)

public static Vector<T> Sigmoid<T>(Vector<T> vector)
```

#### Tanh

Tanh is a function that takes a real number and returns a value between -1 and 1. It is widely used in machine learning and deep learning as an activation function. The proposed API will take a real number collection as input and return the tanh for each element in the collection. 

```csharp
// Assembly System.Numerics.Vectors
namespace System.Numerics;

public static ReadOnlySpan<T> Tanh<T>(ReadOnlySpan<T> vector)

public static T[] Tanh<T>(T[] vector)

public static Vector<T> Tanh<T>(Vector<T> vector)
```

#### Exponential (Exp)

Exponential is a function that takes a real number and returns e raised to the power of the number. It is widely used in mathematics, engineering, and machine learning. The proposed API will take a real number collectionas input and return the exponential for each element in the collection. 

```csharp
// Assembly System.Numerics.Vectors
namespace System.Numerics;

public static ReadOnlySpan<T> Exp<T>(ReadOnlySpan<T> vector)

public static T[] Exp<T>(T[] vector)

public static Vector<T> Exp<T>(Vector<T> vector)
```

#### Cosine Similarity

```csharp
var input1 = new []{-0.4165,  0.1393,  1.1077}

var input2 = new [] {
	new [] {0.5073, -0.2416,  1.7139},
  new [] {-0.1245, -0.4960, -0.0715}
}

// Outputs
var output = 
	input2
		.Select(v => CosineSimilarity(input1,v))

// Outputs
// [0.7694, -0.1568]
```

#### Euclidean Distance

```csharp
var input1 = new []{-0.4165,  0.1393,  1.1077}

var input2 = new [] {
	new [] {0.5073, -0.2416,  1.7139},
  new [] {-0.1245, -0.4960, -0.0715}
}

// Outputs
var output = 
	input2
		.Select(v => Distance(input1,v))
// Outputs
// [1.1687, 1.3709]
```

#### Dot Product

```csharp
//1-D collection
var input1 = new [] {2,3};

//1-D collection
var input2 = new [] {2,1};

// Outputs
var output = 
	Dot(input1, input2)

// Outputs
// 7
```

#### Normalize

```csharp
var input = new [] {
	new [] {0.1146, -0.5104, -1.2457},
	new [] {0.3813, -0.6505, -0.1605}
}

// Outputs
var output = 
	input.Select(v => Normalize(v))

// Outputs
// [
//		[0.0849, -0.3778, -0.9220],
//		[0.4946, -0.8438, -0.2082],	
//	]
```

Related: 
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/SemanticKernel/AI/Embeddings/VectorOperations/NormalizeOperation.cs

#### Softmax

```csharp
var input = new [] {
	new [] {0.1146, -0.5104, -1.2457},
	new [] {0.3813, -0.6505, -0.1605}
}

// Outputs
var output = 
	input.Select(v => Softmax(v))

// Outputs
// [
//		[0.5581, 0.2987, 0.1432],
//		[0.5160, 0.1839, 0.3001],	
//	]
```

#### Sigmoid

```csharp
var input = new [] {
	new [] {0.1146, -0.5104, -1.2457},
	new [] {0.3813, -0.6505, -0.1605}
}

// Outputs
var output = 
	input.Select(v => Sigmoid(v))

// Outputs
// [
//		[0.5286, 0.3751, 0.2234],
//		[0.5942, 0.3429, 0.4600],	
//	]
```

#### Tanh

```csharp
var input = new [] {
	new [] {0.1146, -0.5104, -1.2457},
	new [] {0.3813, -0.6505, -0.1605}
}

// Outputs
var output = 
	input.Select(v => Tanh(v))

// Outputs
// [
//		[0.1141, -0.4703, -0.8471],
//		[0.3638, -0.5720, -0.1591],	
//	]
```

#### Exponential (Exp)

```csharp
var input = new [] {
	new [] {0.1146, -0.5104, -1.2457},
	new [] {0.3813, -0.6505, -0.1605}
}

// Outputs
var output = 
	input.Select(v => Tanh(v))

// Outputs
// [
//		[0.1141, -0.4703, -0.8471],
//		[0.3638, -0.5720, -0.1591],	
//	]
```

#### Semantic Search, Clustering, and Recommendations using Embeddings

Distance metrics are useful when performing search, clustering and recommendations because you want to surface related items. The following is an examples from Semantic Kernel using Cosine Similarity to find similar embeddings from an embedding collection. 

https://github.com/microsoft/semantic-kernel/blob/344bc54f329dd342bf9836913cdd96e25bbeb25f/samples/dotnet/kernel-syntax-examples/Example23_ReadOnlyMemoryStore.cs#L107-L138

```csharp
public IAsyncEnumerable<(MemoryRecord, double)> GetNearestMatchesAsync(string collectionName, Embedding<float> embedding, int limit,
	double minRelevanceScore = 0, bool withEmbeddings = false, CancellationToken cancel = default)
{
	// Note: with this simple implementation, the MemoryRecord will always contain the embedding.
	if (this._memoryRecords == null || !this._memoryRecords.Any())
	{
		return AsyncEnumerable.Empty<(MemoryRecord, double)>();
	}


	if (embedding.Count != this._vectorSize)
	{
		throw new Exception($"Embedding vector size {embedding.Count} does not match expected size of {this._vectorSize}");
	}


	EmbeddingReadOnlySpan<float> embeddingSpan = new(embedding.AsReadOnlySpan());


	TopNCollection<MemoryRecord> embeddings = new(limit);


	foreach (var item in this._memoryRecords)
	{
		EmbeddingReadOnlySpan<float> itemSpan = new(item.Embedding.AsReadOnlySpan());
		double similarity = embeddingSpan.CosineSimilarity(itemSpan);
		if (similarity >= minRelevanceScore)
		{
			embeddings.Add(new(item, similarity));
		}
	}


	embeddings.SortByScore();


	return embeddings.Select(x => (x.Value, x.Score.Value)).ToAsyncEnumerable();
}
```

See the following documents for more details:

- [Cosine Similarity](https://github.com/microsoft/semantic-kernel/blob/ed9f38f364ad04e27a11491e2eaa3829de4560d7/docs/COSINE_SIMILARITY.md)
- [Euclidean Distance](https://github.com/microsoft/semantic-kernel/blob/ed9f38f364ad04e27a11491e2eaa3829de4560d7/docs/EUCLIDEAN_DISTANCE.md)
- [Dot Product](https://github.com/microsoft/semantic-kernel/blob/ed9f38f364ad04e27a11491e2eaa3829de4560d7/docs/DOT_PRODUCT.md)
- [Embeddings](https://github.com/microsoft/semantic-kernel/blob/ed9f38f364ad04e27a11491e2eaa3829de4560d7/docs/EMBEDDINGS.md)

#### Normalize ML Model Outputs

Sometimes, the outputs from a machine learning model have to be post-processed. Some common post-processing operations include calculating the sigmoid or softmax 

```csharp
private float Sigmoid(float value)
{
    var k = (float)Math.Exp(value);
    return k / (1.0f + k);
}

private float[] Softmax(float[] values)
{
    var maxVal = values.Max();
    var exp = values.Select(v => Math.Exp(v - maxVal));
    var sumExp = exp.Sum();

    return exp.Select(v => (float)(v / sumExp)).ToArray();
}

private int GetOffset(int x, int y, int channel)
{
    // YOLO outputs a tensor that has a shape of 125x13x13, which 
    // WinML flattens into a 1D array.  To access a specific channel 
    // for a given (x,y) cell position, we need to calculate an offset
    // into the array
    return (channel * this.channelStride) + (y * COL_COUNT) + x;
}

private float GetConfidence(float[] modelOutput, int x, int y, int channel)
{
    return Sigmoid(modelOutput[GetOffset(x, y, channel + 4)]);
}

private CellDimensions MapBoundingBoxToCell(int x, int y, int box, BoundingBoxDimensions boxDimensions)
{
    return new CellDimensions
    {
        X = ((float)x + Sigmoid(boxDimensions.X)) * CELL_WIDTH,
        Y = ((float)y + Sigmoid(boxDimensions.Y)) * CELL_HEIGHT,
        Width = (float)Math.Exp(boxDimensions.Width) * CELL_WIDTH * anchors[box * 2],
        Height = (float)Math.Exp(boxDimensions.Height) * CELL_HEIGHT * anchors[box * 2 + 1],
    };
}

public float[] ExtractClasses(float[] modelOutput, int x, int y, int channel)
{
    float[] predictedClasses = new float[CLASS_COUNT];
    int predictedClassOffset = channel + BOX_INFO_FEATURE_COUNT;
    for (int predictedClass = 0; predictedClass < CLASS_COUNT; predictedClass++)
    {
        predictedClasses[predictedClass] = modelOutput[GetOffset(x, y, predictedClass + predictedClassOffset)];
    }
    return Softmax(predictedClasses);
}
```

In this case, the Sigmoid and Softmax functions are being used to:

1. Calculate the confidence that an object exists within the detected bounding boxes.
2. Get the probabilities for all of the potential classes and map that to each of the bounding boxes.

See the [ML.NET ONNX Object Detection tutorial](https://learn.microsoft.com/dotnet/machine-learning/tutorials/object-detection-onnx#create-helper-functions) for more details. 

### Alternative Designs

Today, several of these operations are available in libraries like ML.NET, TorchSharp, Semantic Kernel, and TensorFlow.NET. 

- ML.NET
	- [Softmax](https://github.com/dotnet/machinelearning/blob/db197154dcd924ae9a7e31074a835b86e34e33bb/src/Microsoft.ML.Core/Utilities/MathUtils.cs#L203)
	- [Cosine Similarity](https://github.com/dotnet/machinelearning/blob/db197154dcd924ae9a7e31074a835b86e34e33bb/src/Microsoft.ML.Core/Utilities/MathUtils.cs#L735)
	- [Sigmoid](https://github.com/dotnet/machinelearning/blob/db197154dcd924ae9a7e31074a835b86e34e33bb/src/Microsoft.ML.Core/Utilities/MathUtils.cs#L552)
	- [Tanh](https://github.com/dotnet/machinelearning/blob/db197154dcd924ae9a7e31074a835b86e34e33bb/src/Microsoft.ML.Core/Utilities/MathUtils.cs#L592)
	- [Exponential](https://github.com/dotnet/machinelearning/blob/db197154dcd924ae9a7e31074a835b86e34e33bb/src/Microsoft.ML.Core/Utilities/MathUtils.cs#L632)
- TorchSharp
	- [Softmax](https://github.com/dotnet/TorchSharp/blob/main/src/TorchSharp/NN/Activation/Softmax.cs)
	- [Cosine Similarity](https://github.com/dotnet/TorchSharp/blob/main/src/TorchSharp/NN/CosineSimilarity.cs)
	- [Sigmoid](https://github.com/dotnet/TorchSharp/blob/1b4eeaac1a6c484c2469f25401f6dc37ee2b8870/src/TorchSharp/Special.cs#L481)
	- [Tanh](https://github.com/dotnet/TorchSharp/blob/17a35cabef8b301dae1feff036367598ef0a6edd/src/TorchSharp/Tensor/torch.PointwiseOps.cs#L311)
	- [Exponential](https://github.com/dotnet/TorchSharp/blob/24dcf99ce3e8345544e2f83686476194638a2af4/src/TorchSharp/Distributions/Exponential.cs#L15)
- TensorFlow.NET
  - [Softmax](https://github.com/SciSharp/TensorFlow.NET/blob/f0e129e9a5d0565290dc04121479e321d3ab744f/src/TensorFlowNET.Keras/Activations.cs#L28)
  - [Cosine Similarity](https://github.com/SciSharp/TensorFlow.NET/blob/77eb6f5e71fbdd41cf2185093e9ef53583fe801a/src/TensorFlowNET.Keras/Metrics/CosineSimilarity.cs)
  - [Sigmoid](https://github.com/SciSharp/TensorFlow.NET/blob/f0e129e9a5d0565290dc04121479e321d3ab744f/src/TensorFlowNET.Keras/Activations.cs#L23)
  - [Tanh](https://github.com/SciSharp/TensorFlow.NET/blob/f0e129e9a5d0565290dc04121479e321d3ab744f/src/TensorFlowNET.Keras/Activations.cs#L33)
  - [Exponential](https://github.com/SciSharp/TensorFlow.NET/blob/8d7b85aa556344430ada57d335a26d81eba25c8a/src/TensorFlowNET.Core/APIs/tf.exp.cs#L21)
- Semantic Kernel
	- [Cosine Similarity](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/SemanticKernel/AI/Embeddings/VectorOperations/CosineSimilarityOperation.cs)
	- [DotProduct](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/SemanticKernel/AI/Embeddings/VectorOperations/DotProductOperation.cs)
	- [EuclideanLength (Normalization)](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/SemanticKernel/AI/Embeddings/VectorOperations/NormalizeOperation.cs)

These implementations have challenges. In the case of ML.NET, the methods live in an internal class that's not publicly exposed. In the case of TorchSharp and TensorFlow.NET, the size of the library is large and the benefit of consuming the library just for a few functions does not outweigh the downsides of taking on such a large dependency. 

The alternative is to implement your own as Semantic Kernel has done which although not hard, it's tedious and focused on functionality.

https://github.com/luisquintanilla/OAIDotnetZeroShotClassification/blob/7e37ba4fa3ff9d41387bbabe2cdd6de303135596/Program.cs#L45-L59

https://github.com/luisquintanilla/mlnet-workshop/issues/16#issuecomment-1374371524

### Open Questions

- How do we extend these operations to N-dimensional collections / matrices?
- For operations like `Exp` and `Tanh` which already exist in the .NET BCL, is there anything else that needs to be done here to support Vectors and other types of collections?
- For operations like `Dot` which already exist in `System.Numerics` is there anything else that needs to be done here to support other types of collections?

### Risks

- Should these operations be part of an out-of-band package?
- How would the implementation of these APIs be affected by down-level consumption?

**Comment by colombod** [comment]
what about one hot encoder ?

**Comment by colombod** [comment]
also assuming it can handle sequence of T and not jump straight into vectors

**Comment by luisquintanilla** [comment]
Additional operations to consider if not already available.

https://github.com/microsoft/semantic-kernel/tree/main/dotnet/src/SemanticKernel/AI/Embeddings/VectorOperations

**Comment by colombod** [comment]
> Additional operations to consider if not already available.
> 
> https://github.com/microsoft/semantic-kernel/tree/main/dotnet/src/SemanticKernel/AI/Embeddings/VectorOperations
> 
> * DotProduct
> * Euclidean Distance
> * Normalize (Euclidean Length)

makes total sense!

We start with those and the right dev and testing approach and will be very easy to expand. This is promising

**Comment by stephentoub** [comment]
@luisquintanilla, for all of the APIs your proposing, can you clarify on what types you're expecting these to live?  Are you envisioning some new static class of extensions?  Would these be on the existing MemoryExtensions?  Would anything here be on the generic math interfaces?  Are there constraints on the Ts involved here?  Etc.  Thanks.

**Comment by ericstj** [comment]
Are all of these operands single dimensional, or also 2-dim, n-dim?  If the latter, we'll need to also think about how we describe dimension information.  I doubt we'll want to use .NET multi-dimensional or jagged arrays (only) since those are not friendly to interop.  Samples above show 2-dim jagged arrays.

**Comment by stephentoub** [comment]
> Samples above show 2-dim jagged arrays.

Which in particular? Skimming again, the inputs I see are all single dim... where there's jagged, they're actually treated as collections of arrays, where the inputs to the functions are all single dim, eg
```C#
var input1 = new []{-0.4165,  0.1393,  1.1077}

var input2 = new [] {
	new [] {0.5073, -0.2416,  1.7139},
  new [] {-0.1245, -0.4960, -0.0715}
}

// Outputs
var output = input2.Select(v => CosineSimilarity(input1,v))

// Outputs
// [0.7694, -0.1568]
```

**Comment by colombod** [comment]
I am still pondering the support for double, if we had proper generic support this would have been easier

**Comment by ericstj** [comment]
> where the inputs to the functions are all single dim

I see - I missed that it was using linq over the rows and listing the output as an array instead of IEnumerable.  For single dim the specified inputs seem reasonable 👍.  I think @colombod mentioned it might be interesting to add some interface as an input.

**Comment by tannergooding** [comment]
Have opened https://github.com/dotnet/runtime/issues/89639 since the new design builds on this initial proposal and adjusts it to take into account the overall future direction desired here.

**Comment by tannergooding** [comment]
Closing as this was superseded by #89639
