### ISSUE TITLE
[API Proposal]: Add IReadOnlySet2 for speeeding up set operations

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/runtime#83229]
### Background and motivation

Origin: Enumerable.Except has a very hard time when the right side is much bigger than the left side.

Secondary Origin: We have our own implementation of `IDictionary` for reasons that don't need to be gotten into for now. I tried to add `IReadOnlySet<Tkey>` to `IDictionary.Keys` only to discover this doesn't work. On opening the implementation of `HashSet` I understood why. In `HashSet.IsSubsetOf`, `HashSet` does a downcast of its argument to another `HashSet`. If the downcast doesn't succeed, it does it the same bad way that Enumerable.Except does.

In both cases the problem is the same; the incoming set is copied. This defeats the purpose.

We also want to use `IReadOnlySet2<T>` as a flag type to say "must provide a fast Contains()" method. We currently use `ICollection<T>` and doc comments for this, and mistakes have gotten past a code reviewer.

Runtime classes to implement `IReadOnlySet2<T>`: `HashSet<T>`, `ImmutableSet<T>`, `FrozenSet<T>`, `Dictionary<Tkey, TValue>.KeyCollection`, `ImmutableDictionary<TKey, TValue>.Keys`, `FrozenDictionary<TKey, TValue>.Keys`

Trying to wrap the dictionary keys collections doesn't work because you can't get the comparer out of the dictionary. It has to be implemented in the base for it to work.

Change all internal invocations of `EqualityComparersAreEqual` to try downcast to IReadOnlySet2 and compare the equality comparers. This change does in fact back-propigate to change a lot of code in HashSet to downcast to the new interface instead. That's the point. If these changes aren't made (and the corresponding ones to ImmutibleSet and FrozenSet) there's no point doing this change.

Change Enumerable.ExceptIterator and Enumerable.IntersectIterator to try downcast and compare iterators and don't copy on a match. Adding an overload won't work. The idea is to pick up IDictionary.Keys.

### API Proposal

```csharp
namespace System.Collections.Generic;

public interface IReadOnlySet2<T> : IReadOnlySet<T>
{
    IEqualityComparer<T> EqualityComparer { get; }
}
```

### API Usage

```csharp
//
var classifications = new Dictionary<int, RecordClassification>();
foreach (var chunk in StreamRecords().Chunk(1000))
{
    var newclassifications = chunk.Select(GetRecordKey).ToHashSet().Except(classifications.Keys);
    if (newclassifications.Count > 0)
       foreach (var classification in Fetch<Classification>(newclassifications)
           classifications.Add(classification.Id, classification);
}
```

If you wrote this code now, it would run now; at terrible runtime.

### Alternative Designs

All alternative designs failed by either modifying `SortedSet` to assert that it provides an `O(1)` Contains or added an excessive number of downcasts to `System.Linq` methods.

An older version of this proposal had `IsProperSubsetOf` and `IsSubsetOf` as overloads of the methods on the base interface taking `IReadOnlySet2` as the argument. This appears to be unnecessary after all.

### Risks

Implementing `IReadOnlySet2` on `SortedSet` would be a mistake. The implementation detals assert that `IReadOnlySet.Contains` runs in O(1) time.

**Comment by eiriktsarpalis** [comment]
Adding a secondary interface every time we want extend the abstraction is not particularly a viable approach. One possible alternative would be to add an `EqualityComparer` property as a default interface member to `IReadOnlySet<T>` instead, however this approach itself suffers from both source and binary compatibility problems because it might introduce diamond ambiguity.

See also https://github.com/dotnet/runtime/issues/55106 for more details.

In the meantime, would it be possible to just downcast to the particular concrete set implementation your application is concerned with?

**Comment by stephentoub** [comment]
> One possible alternative would be to add an EqualityComparer property as a default interface member to IReadOnlySet<T> instead, however this approach itself suffers from both source and binary compatibility problems because it might introduce diamond ambiguity.

There's also no reasonable default implementation we could provide.  The only thing it could do, for example, would be to return `EqualityComparer<T>.Default`, but then if a concrete set didn't override this to provide the actual comparer, it'd potentially be returning the wrong answer, and consumers couldn't rely on it.

**Comment by eiriktsarpalis** [comment]
What about just null?

**Comment by stephentoub** [comment]
> What about just null? Not saying we should do that, but it certainly feels like a piece of metadata that implementations could provide optionally.

In the world of collections, a null comparer equates to the default comparer, e.g. if you pass null to a collection's `IEqualityComparer<T>` in the constructor, that's treated as equivalent to `EqualityComparer<T>.Default`.

**Comment by jhudsoncedaron** [comment]
@stephentoub : Adding downcasts cannot work because the offending code is in `System.Linq` and the downcast is a fanout downcast.

**Comment by eiriktsarpalis** [comment]
> You see, the problem is not trying to get my code to find the Comparer property. The problem is getting HashSet to recognize another implementation of IReadOnlySet.

But what comparer would it be using if the other implementation is a SortedSet?

**Comment by jhudsoncedaron** [comment]
@eiriktsarpalis : What is why I wrote SortedSet should not implement it, because the question doesn't make sense. Also, copying the collection is probably correct for SortedSet.

The target implementation is Dictionary.Keys. I can't even wrap it because there's no way to convince HashSet that the thing it's been passed is good enough unless it's exactly HashSet.
