### ISSUE TITLE
[release/7.0] Networking and Security tests fail on spanish servers: There are no more endpoints available in the endpoint mapper

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#83226]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=198600
Build error leg or test failing: System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_ServerCertificates_Http2_Test.UseCallback_SelfSignedCertificate_ExpectedPolicyErrors
Pull request: https://github.com/dotnet/runtime/pull/82807

## Error Message
```json
{
  "ErrorMessage": "No hay más extremos disponibles desde el asignador de extremos",
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[213628](https://dev.azure.com/dnceng-public/public/_build/results?buildId=213628)|dotnet/runtime|[System.Security.Cryptography.Dsa.Tests.DSAXml.FromToXml](https://dev.azure.com/dnceng-public/public/_build/results?buildId=213628&view=ms.vss-test-web.build-test-results-tab&runId=3969870&resultId=103415)||
|[213112](https://dev.azure.com/dnceng-public/public/_build/results?buildId=213112)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.DynamicChainTests.NameConstraintViolation_ExcludedTree_Dns](https://dev.azure.com/dnceng-public/public/_build/results?buildId=213112&view=ms.vss-test-web.build-test-results-tab&runId=3952542&resultId=171285)|dotnet/runtime#83742|
|[204142](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204142)|dotnet/runtime|[System.Security.Cryptography.Xml.Tests.SignedXml_Limits.TestReferenceLimits](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204142&view=ms.vss-test-web.build-test-results-tab&runId=3807826&resultId=162578)|dotnet/runtime#83405|
|[204115](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204115)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ClientCertificates_Test.Manual_CertificateOnlySentWhenValid_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204115&view=ms.vss-test-web.build-test-results-tab&runId=3807665&resultId=167321)|dotnet/runtime#83404|
|[199477](https://dev.azure.com/dnceng-public/public/_build/results?buildId=199477)|dotnet/runtime|[System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_NegotiateClientCertificateAsync_IncompleteIncomingTlsFrame_Throws](https://dev.azure.com/dnceng-public/public/_build/results?buildId=199477&view=ms.vss-test-web.build-test-results-tab&runId=3745224&resultId=183734)|dotnet/runtime#81283|
|[198640](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198640)|dotnet/runtime|[System.Security.Cryptography.Tests.DSACreateTests.CreateWithKeysize(keySizeInBits: 1024)](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198640&view=ms.vss-test-web.build-test-results-tab&runId=3736132&resultId=169544)||
|[198600](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198600)|dotnet/runtime|[System.Reflection.PortableExecutable.Tests.PEBuilderTests.Checksum](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198600&view=ms.vss-test-web.build-test-results-tab&runId=3735612&resultId=158148)|dotnet/runtime#82807|
|[197958](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197958)|dotnet/runtime|[System.Security.Cryptography.Pkcs.Tests.SignerInfoTests.AddCounterSignerToUnsortedAttributeSignature](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197958&view=ms.vss-test-web.build-test-results-tab&runId=3727962&resultId=163288)|dotnet/runtime#82277|
|[197933](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197933)|dotnet/runtime|[System.Security.Cryptography.Cng.Tests.ECDsaCngPkcs8Tests.NoPlaintextExportFailsPkcs8](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197933&view=ms.vss-test-web.build-test-results-tab&runId=3727841&resultId=163855)|dotnet/runtime#82246|
|[197927](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197927)|dotnet/runtime|[System.Security.Cryptography.Pkcs.Tests.Pkcs8PrivateKeyInfoTests.ReencryptAndImport](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197927&view=ms.vss-test-web.build-test-results-tab&runId=3727621&resultId=168514)|dotnet/runtime#82248|
|[196671](https://dev.azure.com/dnceng-public/public/_build/results?buildId=196671)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ServerCertificates_Test.UseCallback_SelfSignedCertificate_ExpectedPolicyErrors](https://dev.azure.com/dnceng-public/public/_build/results?buildId=196671&view=ms.vss-test-web.build-test-results-tab&runId=3714018&resultId=182114)|dotnet/runtime#83102|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|2|11|

**Comment by wfurt** [comment]
seems like dup of #74838. I'm wondering if we should change the 7.0 test queues as well or live with the failures @carlossanlop

**Comment by carlossanlop** [comment]
@wfurt can you please help backport the disabled tests that run in spanish? https://github.com/dotnet/runtime/pull/82578

**Comment by carlossanlop** [comment]
Here's an example of the heavy impact in 7.0 Security tests: https://dev.azure.com/dnceng-public/public/_build/results?buildId=204142&view=logs&j=457f7e88-dfa2-5bd9-f871-fdf124c2477d&t=bfe52dfb-2099-5c7f-ee52-70a1d81c544e&l=73

**Comment by carlossanlop** [comment]
Here's an example of 6.0 being impacted too (see the networking/security test failures): https://dev.azure.com/dnceng-public/public/_build/results?buildId=204115&view=logs&j=457f7e88-dfa2-5bd9-f871-fdf124c2477d&t=bfe52dfb-2099-5c7f-ee52-70a1d81c544e

**Comment by Jozkee** [comment]
@carlossanlop did https://github.com/dotnet/runtime/pull/82578 got backported?

**Comment by carlossanlop** [comment]
> did #82578 got backported?

Just did: https://github.com/dotnet/runtime/pull/83747 and https://github.com/dotnet/runtime/pull/83748.

**Comment by carlossanlop** [comment]
Backport PRs merged.
