### ISSUE TITLE
vsdbg-ui stepping over interpolated string line in async Task method throws a null reference exception

### ISSUE THREAD

**Issue by mrward** [dotnet/runtime#83232]
### Description

Original from https://developercommunity.visualstudio.com/t/mac-vs-debugger-using-net70-fails-to-st/10243752

Cannot step over an interpolated string line in an async method. Null reference exception is thrown.

### Reproduction Steps

dotnet new console -o TestInterpolatedString
Change Program.cs to:

```
using System;
using System.Threading.Tasks;

namespace test;

class Program
{
    static async Task Main()
    {
        int num1 = 5;
        Console.WriteLine($"{num1}");
        Console.ReadLine();

        await Task.CompletedTask;
    }
}
```

Open this code in VS Code or VS Mac.
Put a breakpoint on the Console.WriteLine statement.
Start the debugger
When the breakpoint hits try to step over the Console.WriteLine.

### Expected behavior

Can step over the line.

### Actual behavior

A null reference exception occurs.

![image](https://user-images.githubusercontent.com/372361/224160850-82298ac6-4224-4398-8be6-0f96a7c95528.png)

Debug protocol messages when the step over is attempted - https://gist.github.com/mrward/f0b334d2d7c83f6e637430ae2e56acc7

If you change the main method to be a void method then stepping over works OK.

### Configuration

dotnet --info
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.6
 OS Platform: Darwin
 RID:         osx.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

VS Code:

Version: 1.76.0
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:23:45.993Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No

vsdbg-ui: coreclr-debug-1-25-3

**Comment by tommcdon** [comment]
Duplicate to #78991
