### ISSUE TITLE
System.Net.Http.Functional.Tests crashing

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#83241]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=196238
Build error leg or test failing: System.Net.Http.Functional.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/83104

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "'System.Net.Http.Functional.Tests' END OF WORK ITEM LOG: Command exited with -1073741819",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by wfurt** [comment]
looks like dup of #83110
