### ISSUE TITLE
Unexpected performance dropoff for MathF.Exp in loops with high iteration counts

### ISSUE THREAD

**Issue by tgjones** [dotnet/runtime#83265]
### Description

I've been running some benchmarks on `Math.Exp` and `MathF.Exp`, and I noticed that `MathF.Exp` is unexpectedly slower than `Math.Exp` when executed in a loop, but only when the iteration count is above some threshold.

See the benchmarking results below - at lower iteration counts, `MathF.Exp` is faster than `Math.Exp`, as expected. But at higher iteration counts, the performance dropoff appears to be (a) quite significant and (b) non-linear in relation to the iteration count.

This is my benchmarking code:

``` csharp
using System;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Jobs;
using BenchmarkDotNet.Running;

namespace MathBenchmarks;

[SimpleJob(RuntimeMoniker.Net70)]
public class Program
{
    static void Main()
    {
        BenchmarkRunner.Run<Program>();
    }

    [Params(100000u, 500000u, 1000000u, 5000000u)]
    public uint Count;

    [Benchmark(Baseline = true)]
    public float MathExp()
    {
        float value = 0;
        float f = 0;
        for (ulong i = 0; i < Count; i++)
        {
            value += (float)Math.Exp(f);
            value += (float)Math.Exp(f + 0.01f);
            value += (float)Math.Exp(f + 0.02f);
            value += (float)Math.Exp(f + 0.03f);
            value += (float)Math.Exp(f + 0.04f);
            f += 0.0001f;
            if ((i & 0xFFFF) == 0)
            {
                value = 0;
            }
        }
        return value;
    }

    [Benchmark]
    public float MathFExp()
    {
        float value = 0;
        float f = 0;
        for (ulong i = 0; i < Count; i++)
        {
            value += MathF.Exp(f);
            value += MathF.Exp(f + 0.01f);
            value += MathF.Exp(f + 0.02f);
            value += MathF.Exp(f + 0.03f);
            value += MathF.Exp(f + 0.04f);
            f += 0.0001f;
            if ((i & 0xFFFF) == 0)
            {
                value = 0;
            }
        }
        return value;
    }
}
```

And the csproj:

``` xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.13.5" />
  </ItemGroup>

</Project>
```

### Regression?

I ran these benchmarks on .NET 5.0 and saw similar results, so at least it's not a regression from that version. I didn't test any further back than .NET 5.0.

### Data

``` ini

BenchmarkDotNet=v0.13.5, OS=Windows 11 (10.0.22621.1265/22H2/2022Update/SunValley2)
AMD Ryzen Threadripper PRO 3975WX 32-Cores, 1 CPU, 64 logical and 32 physical cores
.NET SDK=7.0.101
  [Host]   : .NET 7.0.1 (7.0.122.56804), X64 RyuJIT AVX2
  .NET 7.0 : .NET 7.0.1 (7.0.122.56804), X64 RyuJIT AVX2

Job=.NET 7.0  Runtime=.NET 7.0  

```
|   Method |   Count |         Mean |     Error |    StdDev |       Median | Ratio | RatioSD |
|--------- |-------- |-------------:|----------:|----------:|-------------:|------:|--------:|
|  **MathExp** |  **100000** |     **3.448 ms** | **0.0572 ms** | **0.0535 ms** |     **3.450 ms** |  **1.00** |    **0.00** |
| MathFExp |  100000 |     1.859 ms | 0.0370 ms | 0.1031 ms |     1.873 ms |  0.53 |    0.03 |
|          |         |              |           |           |              |       |         |
|  **MathExp** |  **500000** |    **16.856 ms** | **0.2952 ms** | **0.2761 ms** |    **16.626 ms** |  **1.00** |    **0.00** |
| MathFExp |  500000 |     9.198 ms | 0.1816 ms | 0.4454 ms |     9.205 ms |  0.55 |    0.02 |
|          |         |              |           |           |              |       |         |
|  **MathExp** | **1000000** |    **33.131 ms** | **0.0479 ms** | **0.0374 ms** |    **33.135 ms** |  **1.00** |    **0.00** |
| MathFExp | 1000000 |    50.053 ms | 0.9531 ms | 0.8915 ms |    50.152 ms |  1.51 |    0.03 |
|          |         |              |           |           |              |       |         |
|  **MathExp** | **5000000** |   **168.959 ms** | **2.4851 ms** | **2.3246 ms** |   **168.076 ms** |  **1.00** |    **0.00** |
| MathFExp | 5000000 | 1,329.982 ms | 3.5485 ms | 2.7704 ms | 1,330.040 ms |  7.85 |    0.11 |

### Analysis

I haven't dug further into it so I have no idea where the problem might lie. I'm happy to keep digging, but I'm creating this issue first just anyone can provide pointers towards likely culprits.

Here's a [SharpLab link](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYQYG8aHunGAzADYRsGBgFkRACwCiCAA4AKAK4BLAHajISjQEouPTtR7GGg4aIBu2AUpgMAvAwAMAbn0nTQkaYfO3Rj1NoBmUhNQBzBhVfVyiGAB4GLQ0XKIBqNL0Aj0NAkysbOzTHBTMRHQkMSQA6WUU+HX884wLbBmKQsowKqVr5UvbnaqdyBqbm7laikq6eqr76wadh0jH3Zqn2ma9uypq6gbShpzo17I3rNo7Snbn9/r4l4ZQzie5HjuWnb9HxiZVHgoFNEAGTOBAAMShEJ0DkcTiybw46yRm3hf2aAF8UTxsedjMQAOwMKYYvHGdb0TzmcRSCEHVQaJIQbTdda5QJdEmXOzonHvHY+Pn4nh8YKhCAROLouKJZIYVIqDKIwIciabDp7CELUqNBj8/I8ra0qrag4fY6jRoGlpGzV0nUWr6ra0ijwaxxax1PE6vN4ek2SM0PH0vV1Ij7w4Y/PgYvIAkLAhhgpyQ6Gw+zwlUTNVI7mFGJxwLk4sGon52xkmiYoA===) showing the assembly code for `MathExp` and `MathFExp`. At first glance I don't see anything obviously wrong. Here's the diff of the assembly code for the two methods:

<img width="747" alt="image" src="https://user-images.githubusercontent.com/102049/224361882-9566b308-95dd-46ae-a5c6-423cc8fa47de.png">

**Comment by tgjones** [comment]
@tannergooding thank you for the detailed reply - that makes a lot of sense!

For my purposes I'm happy to change my benchmarking code to make sure I stay on the fast path for `MathF.Exp`.

If you want to keep this issue open to track this as a potential future improvement then that's up to you, but from my point of view it can be closed. Given that (at least today) .NET calls into `exp` / `expf` it makes sense for .NET to match the performance characteristics of those underlying functions.

**Comment by tannergooding** [comment]
> For my purposes I'm happy to change my benchmarking code to make sure I stay on the fast path for MathF.Exp.

In general I'd expect for `MathF.Exp(x)` to remain faster provided `x <= 88` . I'd expect it to drop off quite a bit above that.

> If you want to keep this issue open to track this as a potential future improvement then that's up to you

I'll close this one, but will link it to https://github.com/dotnet/runtime/issues/9001 which tracks the more general idea of ensuring we have xplat and generally deterministic floating-point implementations. If we had that, then providing optimizations like this would then be possible.
