### ISSUE TITLE
[wasm] Review `FROZEN_CACHE` setting in the build targets

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#83281]
This whole does need to be reviewed again. If the workload is installed in non-user-writable location then how does the build behave? How does the `FROZEN_CACHE` setting affect things?

**Comment by lewing** [comment]
This is more important in the emsdk build when we make the cache package

**Comment by lambdageek** [comment]
This is causing breakages on lanes like this `runtime-wasm (Build browser-wasm linux Release LibraryTests_NodeJs)`:


```
cache(0,0): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Accessing the Emscripten cache at "/usr/local/emscripten/emsdk/upstream/emscripten/cache" (for "sysroot/lib/wasm32-emscripten/libsqlite3.a") is taking a long time, another process should be writing to it. If there are none and you suspect this process has deadlocked, try deleting the lock file "/usr/local/emscripten/emsdk/upstream/emscripten/cache/cache.lock" and try again. If this occurs deterministically, consider filing a bug.
```

**Comment by lambdageek** [comment]
the cache must be frozen.  If Emscripten is complaining about missing libraries, then we need to update the nuget pack to include them. not to unfreeze the cache

**Comment by lambdageek** [comment]
the `$(_EmBuilder) build MINIMAL` stuff from WasmApp.Native.targets should be done in emsdk, not in dotnet/runtime - all that stuff should end up in the Cache nuget

**Comment by radical** [comment]
`build MINIMAL` was removed from `WasmApp.Native.targets`. The only instance of `*FROZEN_CACHE` in our targets is:

https://github.com/dotnet/runtime/blob/81cb4b8f4769e44086380a677e77264be111aa75/src/mono/wasm/build/WasmApp.Native.targets#L274-L275

- Is `EM_FROZEN_CACHE` just the new name for `FROZEN_CACHE`?
- If the workload is installed in non-user-writable location then how does the build behave? How does the `EM_FROZEN_CACHE` setting affect things?

**Comment by lewing** [comment]
Ideally we'd only set FROZEN_CACHE when using the nuget and we would be using the emsdk nugets for to build icu and runtime

cc @directhex

**Comment by lewing** [comment]
cc @directhex

**Comment by lewing** [comment]
If there is work left to do here for net8 lets do it asap, otherwise close or update the issue with details

**Comment by directhex** [comment]
I don't really have the background on what FROZEN_CACHE does

**Comment by radekdoulik** [comment]
I think this is fully resolved. https://github.com/dotnet/runtime/pull/84356

**Comment by radekdoulik** [comment]
> `build MINIMAL` was removed from `WasmApp.Native.targets`. The only instance of `*FROZEN_CACHE` in our targets is:
> 
> https://github.com/dotnet/runtime/blob/81cb4b8f4769e44086380a677e77264be111aa75/src/mono/wasm/build/WasmApp.Native.targets#L274-L275
> 
>     * Is `EM_FROZEN_CACHE` just the new name for `FROZEN_CACHE`?
> 
>     * If the workload is installed in non-user-writable location then how does the build behave? How does the `EM_FROZEN_CACHE` setting affect things?

`EM_FROZEN_CACHE` env variable sets the `FROZEN_CACHE` for emscripten. That means that the emscripten doesn't try to expand the cache during build - the cache is part of our nuget.

One thing which we might consider is not setting the `FROZEN_CACHE` when `WasmCachePath` is overiden. This is currently undocumented property. We can document it and let user override it. That might improve build times in cases where user repeatedly builds native libs, OTOH the first build with overiden cache will result in long build to prime the new cache.

Possible long term improvement: enhance the emscripten to use multiple "cascaded" caches. Where it would be possible to use our nuget cache together with cache in different writable location.
