### ISSUE TITLE
Obsolete JsonSerializerOptions.AddContext

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#83280]
## Background & Motivation

The `JsonSerializerOptions.AddContext<TContext>()` method was introduced in .NET 6 as a means to associate `JsonSerializerOptions` instances with a given `JsonSerializerContext` type. This method was largely superseded in .NET 7 with the introduction of contract customization and the `JsonSerializerOptions.TypeInfoResolver` property.

We should obsolete `AddContext` for the following reasons:

1. Contrary to what the name suggests, it replaces user configuration instead of appending to it.
2. It can be confused with the new [`JsonSerializerOptions.TypeInfoResolverChain`](https://github.com/dotnet/runtime/issues/83095) when manipulating resolver chains.
3. The method only works with `JsonSerializerContext` type parameters, not with arbitrary `IJsonTypeInfoResolver` instances.
4. The method freezes the `JsonSerializerOptions` for further modification:
     ```C#
     JsonSerializerOptions options = new();
     options.AddContext<Context1>(); // success
     options.AddContext<Context2>(); // InvalidOperationException
     ```

## API Proposal

```C#
public class JsonSerializerOptions
{
     [Obsolete(/* SYLIB code TBD? */)]
     public void AddContext<TContext>() : where TContext : JsonSerializerContext { }
}
```

cc @eerhardt

**Comment by bartonjs** [comment]
Looks good as proposed.

Confirm with @terrajobst that System.Text.Json should use SYSLIB codes.
