### ISSUE TITLE
Using CryptoStream leaves copy of unencrypted data in shared array pool after it has been encrypted

### ISSUE THREAD

**Issue by dev991301** [dotnet/runtime#83295]
### Description

I did report this to MSRC but the report was closed saying "We determined that this behavior is considered to be by design. This behavior is due to how the GC and the runtime works. The CryptoStream is actually making a copy of the data internal which the developer doesn't control and cannot clear. The ArrayPool after clearing the original buffer actual returns the internal buffer CryptoStream copied the data into.". So they said it isn't a vulnerability but I still thought it was unexpected. I would have expected that once my data was encrypted using CryptoStream that my unencrypted data would not be available to rent via ArrayPool. 

### Reproduction Steps

```csharp
// Simulate getting the data from somewhere and let's say it gets the word "secret" encoded in UTF-8. 
var data = new byte []{ 0x73, 0x65, 0x63, 0x72, 0x65, 0x74 };

// Ensure we dispose of streams before we try to rent from the array pool.
using (var ms = new MemoryStream())
{
    using (var cs = new CryptoStream(ms, Aes.Create().CreateEncryptor(), CryptoStreamMode.Write))
    {
        cs.Write(data);
        cs.FlushFinalBlock();
    }
   // Do something with encrypted data in memory stream.
}
// Ensure my data is cleared from memory after being encrypted.
Array.Clear(data);

var rental = ArrayPool<byte>.Shared.Rent(data.Length);

// The line below outputs: Rented from the pool and got secret
Console.WriteLine($"Rented from the pool and got {Encoding.UTF8.GetString(rental)}");
```

### Expected behavior

Renting from the array pool after using CryptoStream would not return my unencrypted data.

### Actual behavior

Renting from the array pool after using CryptoStream returns my unencrypted data.

### Configuration

.NET 6
Windows 11
x64

**Comment by vcsjones** [comment]
This is actually coming from `Stream` base class:

https://github.com/dotnet/runtime/blob/0f1866ead5aef15d47983692bafb4ba20cd3aa98/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs#L922-L934

The `Write` ends up renting from the pool, converting it to an array, but `Write` doesn't clear what it rented.

One way to avoid this is to use the array overload: `cs.Write(data, 0, data.Length);`. It's only the span overload that rents from the pool. You'll get better performance with this call, too.

We should _probably_ override `public virtual void Write(ReadOnlySpan<byte> buffer)` in `CryptoStream`. If anything, it can do exactly what `Stream` does, except clear when returning to the pool.

@stephentoub I think you had some reservations previously about overriding `Write(ReadOnlySpan<byte> buffer)` in `CryptoStream`. I'm guessing that changing the base `Stream` to clear would be a deal-breaker performance wise. Does overriding this method seem like the appropriate fix here?

**Comment by stephentoub** [comment]
> I'm guessing that changing the base Stream to clear would be a deal-breaker performance

Yes

> Does overriding this method seem like the appropriate fix here?

If this is really a problem that needs fixing. You also would presumably care about other places ArrayPool is used with streams, only some of which are in CryptoStream's control, like CopyTo (which it can control for the outgoing direction by overriding it, but obviously not for other streams copying into it). And of course even if you do all that, the incoming data is still on the GC heap and could easily have left shadow copies.
