### ISSUE TITLE
[API Proposal]: Make common interface for Random

### ISSUE THREAD

**Issue by atomknack** [dotnet/runtime#83304]
### Background and motivation

We have multiple different generators:
System.Random;
System.Security.Cryptography;

So I propose to have common interface that could be use to interchange them and also use 3rd party random generators.

### API Proposal

```csharp

public partial interface IRandom
{
    int Next();
    int Next(int maxValue);
    int Next(int minValue, int maxValue);
    double NextDouble();
    void NextBytes(Span<byte> bytes);
    void GetItems<TItem>(ReadOnlySpan<TItem> choices, Span<TItem> destination);
    void Shuffle<TItem>(Span<TItem> values);
}
```

### API Usage

```csharp
IRandom c = new System.Random(70);
int x = c.Next();
Console.WriteLine(x);
```

### Alternative Designs

Currently not in Net, but also would be nice to have in interface abilities to Reset generator and Salt it.
void Reset();
void Salt(long salt);

### Risks

Conflicts with 3rd party libraries that already have interface with such name.

**Comment by stephentoub** [comment]
Thanks. Duplicate of https://github.com/dotnet/runtime/issues/82799, https://github.com/dotnet/runtime/issues/73567, and https://github.com/dotnet/runtime/issues/28229.
