### ISSUE TITLE
Dotnet muxer doesn't respect Windows symlinks

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#83314]
Scenario:

Install dotnet to a folder and create a symbolic link to dotnet.exe

Expected:

dotnet follows the symlink and resolves hostfxr etc as symlink-relative

Actual:

> A fatal error occurred. The folder [C:\Users\andy\AppData\Local\dnvm\host\fxr] does not exist

**Comment by elinor-fung** [comment]
Related (would likely be the same solution):
- https://github.com/dotnet/runtime/issues/3144

`pal::realpath` is probably what would need to change:
https://github.com/dotnet/runtime/blob/1936536dff9c37bf5fa9ff582ddf8a8082727af8/src/native/corehost/hostmisc/pal.windows.cpp#L727-L728
