### ISSUE TITLE
Do async state machines ever have Equals/GetHashCode called?

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#83323]
NativeAOT compiler generates extra bookkeeping to support calling Equals/GetHashCode on structs. We generate it for async state machines, because they're structs. Do we have to?

A quick hack to not generate it produces 0.6% size savings for BasicMinimalApi. But not sure if it's a correct optimization. We don't have a good way to figure out the wrong thing happened at runtime (we're likely going to take "are the bytes the same" and "hash of the bytes" code paths).

Cc @stephentoub @eerhardt

**Comment by stephentoub** [comment]
These shouldn't be needed (if they were, we'd also be generating strongly-typed IEquatable implementations to avoid boxing, and we're not.) We never put these into any kind of collection, compare them, etc.

**Comment by MichalStrehovsky** [comment]
Awesome, thanks! Opened #83369 to remove these!
