### ISSUE TITLE
jitstress-random-libraries: Assertion failed 'addr->TypeIs(TYP_BYREF)'

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#83333]
https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-2d2644c42b3f49d89f/System.Security.Cryptography.Tests/1/console.d4951751.log?helixlogtype=result

```
Assert failure(PID 2068 [0x00000814], Thread: 4464 [0x1170]): Assertion failed 'addr->TypeIs(TYP_BYREF)' in 'System.Formats.Asn1.NumericStringEncoding:.ctor():this' during 'Optimize layout' (IL size 12; hash 0x868f570d; FullOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\gentree.h Line: 6778
    Image: C:\h\w\A6AA08E9\p\dotnet.exe
```
something that was introduced recently, another similar assert in that pipeline is:

```

Assert failure(PID 5232 [0x00001470], Thread: 4976 [0x1370]): Assertion failed 'op1->gtEffectiveVal() == base' in 'System.Data.Tests.SqlTypes.SqlBinaryTest+<>c:<Properties>b__6_3():System.Object:this' during 'Assertion prop' (IL size 14; hash 0xa034b495; FullOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\gentree.cpp Line: 4420
    Image: C:\h\w\B5100964\p\dotnet.exe
```
https://dev.azure.com/dnceng-public/public/_build?definitionId=160&_a=summary

both are win-x86

**Comment by JulieLeeMSFT** [comment]
Failed again in net8.0-windows-Release-x86-CoreCLR_checked-jitstress_random_2-Windows.10.Amd64.Open
System.Data.Common.Tests Work Item
https://dev.azure.com/dnceng-public/public/_build/results?buildId=217448&view=ms.vss-test-web.build-test-results-tab&runId=4063112&paneView=debug&resultId=199083

```
Assert failure(PID 3900 [0x00000f3c], Thread: 4460 [0x116c]): Assertion failed 'op1->gtEffectiveVal() == base' in 'System.Data.Tests.SqlTypes.SqlBinaryTest+<>c:<Properties>b__6_3():System.Object:this' during 'Assertion prop' (IL size 14; hash 0xa034b495; FullOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\gentree.cpp Line: 4474
```

**Comment by EgorBo** [comment]
The problem here is in addressing mode detection logic for the following tree:

![image](https://user-images.githubusercontent.com/523221/229523986-2f0c1f31-e5fa-4ebe-a126-dec3dec89d72.png)

where baseAddr is effectively null
