### ISSUE TITLE
[mono][perf] Remaining AOT Linux x86-64 perf issues after RuntimeHelpers.CreateSpan<T>

### ISSUE THREAD

**Issue by jandupej** [dotnet/runtime#83330]
This issue tracks the performance issues that were not resolved or fully resolved by introducing `RuntimeHelpers.CreateSpan<T>` intrinsic to Mono. These were the original regression reports:
[https://github.com/dotnet/perf-autofiling-issues/issues/12060](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fperf-autofiling-issues%2Fissues%2F12060&data=05%7C01%7Cjandupej%40microsoft.com%7C05669f716c6e4a87ccf808db20c974f5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638139821872908984%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=a1Lyxd5S5EsZoW7IEvldHhnSclaqYoXB0UpoJklH1WE%3D&reserved=0)
[https://github.com/dotnet/perf-autofiling-issues/issues/12054](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fperf-autofiling-issues%2Fissues%2F12054&data=05%7C01%7Cjandupej%40microsoft.com%7C05669f716c6e4a87ccf808db20c974f5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638139821872908984%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WXUpHK7ooxpYlUMGtmWQ5Nl%2BwPECzo7Dbt4yeKW%2BiRk%3D&reserved=0)
[https://github.com/dotnet/perf-autofiling-issues/issues/11780](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fperf-autofiling-issues%2Fissues%2F11780&data=05%7C01%7Cjandupej%40microsoft.com%7C05669f716c6e4a87ccf808db20c974f5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638139821872908984%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=46hlxUtI20fceAhCex%2BWEJdrA0uFhJPUUpGc1adeD9Y%3D&reserved=0)

The following benchmarks were not improved:
- `System.Tests.Perf_Int32.TryParseSpan`
- `System.Tests.Perf_Char.ToUpper('A', en-US)`
- `System.Tests.Perf_String.Interpolation_MultipleArgs('A', "Foo")`
- `System.Collections.Tests.Perf_PriorityQueue<String, String>.Enumerate`
- `System.Collections.IterateForEach<String>.ImmutableArray`
- `System.Tests.Perf_Decimal.Mod`
- `IfStatements.AndArray`

The benchmark history from just before the regressions occurred to just after the fix can be found here [Ubuntu x64 AOT](https://pvscmdupload.blob.core.windows.net/parkertest/03_08_2023/report_Daily_ca%3Dx64_cb%3Drefs-heads-main_co%3DUbuntu1804_cr%3Ddotnetruntime_cc%3DCompilationMode%3Dtiered-LLVM%3Dfalse-MonoAOT%3Dtrue-MonoInterpreter%3Dfalse-RunKind%3Dmicro_mono_2023-03-08.html)

**Comment by kotlarmilos** [comment]
@jandupej Do we know why they regressed or investigation is needed?

**Comment by DrewScoggins** [comment]
Also the ToString methods in this issue are regressed still.

https://github.com/dotnet/perf-autofiling-issues/issues/12121

**Comment by matouskozak** [comment]
These regressions has been resolved during .NET 9 development timeframe. I confirmed by manually going thru some of the regressions that the measurement returned back to original values or improved.
