### ISSUE TITLE
IPv6 multicast, multicast group joins on not selected network adapter with .net SDK installed

### ISSUE THREAD

**Issue by Fredrik71** [dotnet/runtime#83336]
### Describe the bug
We have an application that should listen to messages sent to specific multicast group, this works if we are running it in a system without development environment, more specific .net SDK. The issue may not appear immediately, but after a while, it may be something that activates the issue.

It turns out that UdpClient.JoinMulticastGroup will join on another adapter than selected.

### To Reproduce
Run attached project on two separate systems with the receiver app on system with .net SDK installed, receiver app will print out a line for each multicast message received if it works, if the bug is reproduced it will stay silent.

### Further technical details

Working environment `dotnet --info`

```
global.json file:
  Not found

Host:
  Version:      6.0.14
  Architecture: x64
  Commit:       2a90daa2cc

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

Not working environment `dotnet --info`

```
.NET SDK:
 Version:   7.0.201
 Commit:    68f2d7e7a3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.201\

Host:
  Version:      7.0.3
  Architecture: x64
  Commit:       0a2bda10e8

.NET SDKs installed:
  7.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

- The IDE (VS / VS Code/ VS4Mac) VS 2022
[MulticastTester.zip](https://github.com/dotnet/sdk/files/10958859/MulticastTester.zip)

**Comment by antonfirsov** [comment]
> Run attached project on two separate systems with the receiver app on system with .net SDK installed

I doubt this is caused by the fact that the SDK is present on one of the systems. If you think so, have you tried uninstalling it, making sure you have the same runtime?

This is more likely a networking problem than an issue with .NET. We need to understand your networking configuration better to reason about this. Are your systems VM-s or physical machines? What are the OS-es? What are steps to create an equivalent configuration of networking devices and multicast groups to reproduce this?

**Comment by antonfirsov** [comment]
Triage: even this turns out to be a bug in .NET (which is very unlikely) it is not critical for 8.0.
