### ISSUE TITLE
Wrong error message formatting for IDX10653 (System.Security.Cryptography)

### ISSUE THREAD

**Issue by DavidVollmers** [dotnet/runtime#83347]
### Description

While testing my own code I ran into the following exception:
`IDX10653: The encryption algorithm 'System.String' requires a key size of at least 'System.Int32' bits. Key 'Microsoft.IdentityModel.Tokens.SymmetricSecurityKey', is of size: 'System.Int32'. 
(Parameter 'key')`

I understand that my symmetric key is too short (should it not be zero-padded automatically?) but the error message is the weird part. It seems to me that something went wrong in here and it doesn't use the values but rather the types when formatting the error message.

### Reproduction Steps

Here is an example project reproducing the behavior:
https://github.com/DavidVollmers/IDX10653/blob/main/Program.cs

### Expected behavior

The exception message should look like this:
`IDX10653: The encryption algorithm 'http://www.w3.org/2001/04/xmldsig-more#hmac-sha512' requires a key size of at least 128 bits. Key 'Microsoft.IdentityModel.Tokens.SymmetricSecurityKey', is of size: 32. (P
arameter 'key')`

### Actual behavior

The exception message looks like this:
`IDX10653: The encryption algorithm 'System.String' requires a key size of at least 'System.Int32' bits. Key 'Microsoft.IdentityModel.Tokens.SymmetricSecurityKey', is of size: 'System.Int32'. 
(Parameter 'key')`

### Configuration

- .NET 6.0
- Windows 10 Enterprise (11.‎03.‎2021, 19045.2604)
- x64

**Comment by stephentoub** [comment]
That library doesn't live in this repo.  It's defined here:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/4fddab7310da391246ef0d2a4b92e46d69bf3e1b/src/Microsoft.IdentityModel.Tokens/LogMessages.cs#L155

Can you open an issue there instead?

Thanks.

**Comment by DavidVollmers** [comment]
The repository/namespace/assembly distribution is some kind of security through obfuscation isn't it? 😕 

I copied the issue over to the recommended repository, thanks.
