### ISSUE TITLE
Native AOT classlib compiles with [DLLImport° as cheating dynamic library

### ISSUE THREAD

**Issue by DeafMan1983** [dotnet/runtime#83353]
Hello,

Woah I expected that I have written with [DLLImport()] in classlib project

But why does ldd not show if I added DLLImport as l(library-name) I will explain next line...

Example I write `Class1.cs`
```
using System.Runtime.InteropServices;
using System.Text;

namespace HelloFromString;
public class Class1
{
    [UnmanagedCallersOnly(EntryPoint = "write_line")]
    public static int WriteLine(IntPtr pString)
    {
        try
        {
            string str = Marshal.PtrToStringAnsi(pString);

            Console.WriteLine(str);
        }
        catch
        {
            return -1;
        }
        return 0;
    }

    [UnmanagedCallersOnly(EntryPoint = "hello_world")]
    private static void Hello()
    {
        Console.WriteLine("Hello World!");
    }

    [DllImport("libX11")]
    private static extern nint XOpenDisplay(nint display_name);

    [DllImport("libX11")]
    private static extern int XCloseDisplay(nint display);

    [DllImport("libX11")]
    private static extern int XDefaultScreen(nint display);

    [DllImport("libX11")]
    private static extern short XDisplayWidth(nint display, int scr_nbr);

    [DllImport("libX11")]
    private static extern short XDisplayHeight(nint display, int scr_nbr);

    [UnmanagedCallersOnly(EntryPoint = "custom_open")]
    public static nint Open(nint display_name)
    {
        return XOpenDisplay(display_name);
    }

    [UnmanagedCallersOnly(EntryPoint = "custom_close")]
    public static int Close(nint display)
    {
        return XCloseDisplay(display);
    }

    [UnmanagedCallersOnly(EntryPoint = "custom_default_screen")]
    public static int DefScr(nint display)
    {
        return XDefaultScreen(display);
    }

    [UnmanagedCallersOnly(EntryPoint = "custom_d_width")]
    public static short DWwidth(nint display, int scr_nbr)
    {
        return XDisplayWidth(display, scr_nbr);
    }

    [UnmanagedCallersOnly(EntryPoint = "custom_d_height")]
    public static short DHeight(nint display, int scr_nbr)
    {
        return XDisplayHeight(display, scr_nbr);
    }
}
```
I check native compiled `example.so` with ldd
what does it happen but native aot won't show when I already use `[DLLImport("libX11")]` as `-lX11` in clang / gcc line
Result:
```
ldd bin/Release/net7.0/linux-x64/native/example.so
	linux-vdso.so.1 (0x00007ffea7ee6000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fcec1c00000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fcec1f19000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fcec1800000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fcec241a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fcec23e2000)
```
That is unfair because dotnet cheats to load hidden dynamical libraries...
Where is libX11.so.6 from ldd when you have used DLLImport?

Please fix if native aot compilation will convert DLLImport into static library `*.a` then generates to clang's line `-l(library-name)` and include-path also.

And I try console project:
Result:
```
namespace Test;

using System.Runtime.InteropServices;

class Program
{
    [DllImport("example")]
    private static extern int write_line(IntPtr pString);
    
    [DllImport("example")]
    private static extern void hello_world();
    private static int WriteLine(string message)
    {
        return write_line(Marshal.StringToHGlobalAnsi(message));
    }

    [DllImport("example")]
    private static extern nint custom_open(nint display_name);

    [DllImport("example")]
    private static extern int custom_close(nint display);

    [DllImport("example")]
    private static extern int custom_default_screen(nint display);

    [DllImport("example")]
    private static extern short custom_d_width(nint display, int screen_number);

    [DllImport("example")]
    private static extern short custom_d_height(nint display, int screen_number);

    static void Main(string[] args)
    {
        int meshdl = WriteLine("From shared object");
        Console.WriteLine("Hello,", Convert.ToString(meshdl));
        hello_world();

        nint display = custom_open(nint.Zero);
        if (display == nint.Zero)
        {
            Console.WriteLine("Error");
            Environment.Exit(1);
        }

        Console.WriteLine("Initializing custom X11!");

        int screen_number = custom_default_screen(display);
        Console.WriteLine("Screen Number is {0}", screen_number);

        int d_width = custom_d_width(display, screen_number);
        int d_height = custom_d_height(display, screen_number);
        Console.WriteLine("\tScreen Width is {0}", d_width);
        Console.WriteLine("\tScreen Height is {0}", d_height);

        custom_close(display);
    }
}
```
And Terminal in VS Code output:
```
From shared object
Hello,
Hello World!
Initializing custom X11!
Screen Number is 0
        Screen Width is 1920
        Screen Height is 1080
```
Woah it works fine. But ldd doesn't know where is DLLImport's path-to-library? That is why I need to give suggestion generation of dotnet into static library name like `-lX11` from `libX11.a`

Example:
If you want SDL3 or GLFW3 into native aot via DLLImport and native aot compilation will change DLLImport to library-name like `clang ..... -lSDL3 ...`
then somebody checks with `ldd` then it will list in native aot compiled *.so file from classlib project.
```
ldd bin/Release/net7.0/linux-x64/native/example.so
	linux-vdso.so.1 (0x00007ffea7ee6000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fcec1c00000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fcec1f19000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fcec1800000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fcec241a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fcec23e2000)
	libSDL3.so => /lib/x86_64-linux-gnu/libSDL3.so
```
That is proof from generated path to lib-name. I hope you know about cheating is not allowed. And I want everyone is seriously. I know Dotnet is not cheater. That is why I find bug when native aot doesn't know while you write with `DLLImport` in classlib-project then native aot compiler should catch path if it find *.a "Hu that is valid or current a file of same shared libraries like Windows 10 has dll file and lib file.

I would like to imagine about our development if native aot process find path `User32.dll` then it knows -> where is User32.lib and it catches lib file from Windows SDK Installation's Path.

Do you think Dotnet native aot compilation can catch static library if somebody uses `DLLImport` and builds end-user application. And shows proof of ldd.

Is it realistically?

Thanks!

**Comment by jkotas** [comment]
.NET runtime loads shared libraries dynamically by default. Native AOT has the same default behavior.

If you would like the unmanaged shared library to be linked directly such that it shows up in ldd output, add it to `DirectPInvoke` item group in your project file, e.g. `<DirectPInvoke Include="libX11" />`.

This is documented in https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/interop.md#direct-pinvoke-calls

**Comment by DeafMan1983** [comment]
@jkotas thanks! That's great for direct invoke. That is weird bug. That's not question. It looks like cheating from hidden loading shared libraries who doesn't know to open important shared libraries like Ubuntu 22.04 forgot to install required deps when end user opens native aot compiled dotapps or checks ldd. They think dotnet cheats from forgotten invoking libraries. That's why dotnet made criminally. That's why we need support for improving generation of automatical directinvoke output after native aot compilation and end user will know when dotapp opens by user and throws errors and it says to need to install shared libraries. Thanks!

**Comment by jkotas** [comment]
Our principle is to avoid unnecessary behavior differences between standard .NET runtime and native AOT compiled binaries. .NET runtime loads shared libraries on demand and number of popular NuGet packages depend on this behavior. We are not going to change the default behavior. It would be a hard-to-justify breaking change.

**Comment by DeafMan1983** [comment]
Okay that's our decision of dotnet. Thanks for understanding! I will use manual with directinvoke.
