### ISSUE TITLE
JsonConfigurationFileParser.cs RootElement not support Array

### ISSUE THREAD

**Issue by zyz** [dotnet/runtime#83373]
### Description

https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Configuration.Json/src/JsonConfigurationFileParser.cs
Function: ParseStream
private Dictionary<string, string?> ParseStream(Stream input)
{
        var jsonDocumentOptions = new JsonDocumentOptions
        {
                CommentHandling = JsonCommentHandling.Skip,
                AllowTrailingCommas = true,
        };

        using (var reader = new StreamReader(input))
        using (JsonDocument doc = JsonDocument.Parse(reader.ReadToEnd(), jsonDocumentOptions))
        {
                if (doc.RootElement.ValueKind != JsonValueKind.Object)
                {
                        throw new FormatException(SR.Format(SR.Error_InvalidTopLevelJSONElement, doc.RootElement.ValueKind));
                }
                VisitObjectElement(doc.RootElement);
        }

        return _data;
}

if (doc.RootElement.ValueKind != JsonValueKind.Object)
Direct exclusion Array, RootElement not support Array

**How does the root element support array?**

private Dictionary<string, string?> ParseStream(Stream input)
 {
        var jsonDocumentOptions = new JsonDocumentOptions
        {
                CommentHandling = JsonCommentHandling.Skip,
                AllowTrailingCommas = true,
        };

        using (var reader = new StreamReader(input))
        using (JsonDocument doc = JsonDocument.Parse(reader.ReadToEnd(), jsonDocumentOptions))
        {
                if(doc.RootElement.ValueKind == JsonValueKind.Object)
                        VisitObjectElement(doc.RootElement);
                else if (doc.RootElement.ValueKind == JsonValueKind.Array)
                        VisitArrayElement(doc.RootElement);
                else
                {
                    throw new FormatException(SR.Format(SR.Error_InvalidTopLevelJSONElement, doc.RootElement.ValueKind));
                }
        }

        return _data;
}

### Reproduction Steps

Stream input is Array Stream [1,2,3] ;

### Expected behavior

no Exception

### Actual behavior

throw new FormatException(SR.Format(SR.Error_InvalidTopLevelJSONElement, doc.RootElement.ValueKind));

### Regression?

private Dictionary<string, string?> ParseStream(Stream input)
{
        var jsonDocumentOptions = new JsonDocumentOptions
        {
                CommentHandling = JsonCommentHandling.Skip,
                AllowTrailingCommas = true,
        };

        using (var reader = new StreamReader(input))
        using (JsonDocument doc = JsonDocument.Parse(reader.ReadToEnd(), jsonDocumentOptions))
        {
                if(doc.RootElement.ValueKind == JsonValueKind.Object)
                        VisitObjectElement(doc.RootElement);
                else if (doc.RootElement.ValueKind == JsonValueKind.Array)
                        VisitArrayElement(doc.RootElement);
                else
                {
                    throw new FormatException(SR.Format(SR.Error_InvalidTopLevelJSONElement, doc.RootElement.ValueKind));
                }
        }

        return _data;
}

**Comment by davidfowl** [comment]
What are you trying to accomplish?

**Comment by zyz** [comment]
var arrDic = JsonConfigurationParser.Parse("[1,2,3]");
RootElement support Array
Now RootElement not support Array

**Comment by zyz** [comment]
> What are you trying to accomplish?
var arrDic = JsonConfigurationParser.Parse("[1,2,3]");
throw new FormatException(SR.Format(SR.Error_InvalidTopLevelJSONElement, doc.RootElement.ValueKind));
RootElement support Array
Now RootElement not support Array

**Comment by davidfowl** [comment]
Why would the configuration file have a top level array instead of an object?

**Comment by davidfowl** [comment]
This isn't arbitrary JSON data though, this is configuration file parsing. The configuration format is a very specific transformation from JSON. Are you using this for something other than configuration?

**Comment by layomia** [comment]
This is by design.
