### ISSUE TITLE
[.NET 7]Integer auto-vectorization bug

### ISSUE THREAD

**Issue by koszeggy** [dotnet/runtime#83387]
### Description

The detailed description is [here](https://stackoverflow.com/q/75732627/5114784).

Summary: On some platforms `uint`/`int` vector initialization is wrong from ushort fields or arrays. `Vector<T>` and `Vector128<T>` are affected for sure, maybe others as well.

### Reproduction Steps

```cs
using System;
using System.Numerics;
using System.Runtime.Intrinsics;

(ushort A, ushort R, ushort G, ushort B) c = (32768, 65535, 32768, 16384);

Vector128<uint> v1 = Vector128.Create(c.R, c.G, c.B, 0u);
Console.WriteLine(v1);
v1 = v1 * c.A / Vector128.Create(0xFFFFu);
Console.WriteLine(v1);

Span<uint> span = stackalloc uint[Vector<uint>.Count];
span[0] = c.R;
span[1] = c.G;
span[2] = c.B;
Vector<uint> v2 = new Vector<uint>(span) * c.A / new Vector<uint>(0xFFFF);
Console.WriteLine(v2);

Console.WriteLine();
Console.WriteLine(Vector128.Create((int)c.A));
Console.WriteLine(Vector128.Create((int)32768));
Console.WriteLine(Vector128.Create((int)c.A, (int)c.A, (int)c.A, (int)c.A));
```

Please note that the results are correct in [SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMBGAWACgsAGAAizwDoA5VMAU2SgGMBnAbmLMpoCV0CKE2oBJGAhYx2bLsWIAKVOwAWAe2QJyAQTjkVGreX77Dm7QHEzai+QBCASnKtyAXnKKAzDgDsANgAOfX8AVlCvUP0fAODyPH8vQIAWR24iYgA1RlYETTwcQIAeVFgEAD5yADc8d3Js3PzC6gBhZEYIBEZFVmpTF2prAft9UlQ0njwATkUaiaIausWAKgGdcgB6epy85ALA1vbO7tIADwAxS/Px9KoZufTiAGUABwgYErLK9jeYOvYEBBWABrCAAGzB6lcpUkAG0GrtPpJyq11EIALrpH7vWGkdF1Xr8LG/WF4fEeXqWYk4nDk4bpBGaJEVao4OowRgAd22jWQzPKimxMGcq166y2HO5jL5MIqijOV3O8zusxw80mM2V00U0v2hw6XUUijKjjFji1M11zTaBu6xskjhiQXNt21VoONuORpNYv09oQpuoek8PqDftDOhdQA===) Release mode but are [incorrect](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8ACATAIwCwAUPgAwAE+xAdAHKpgCmyUAxgM4DcFanUYAldAijsGASRgJOMHt34UKAClQ8AFgHtkCGgEE4NTbv00RJs3oMBxa9ts0AQgEoaXGgF4aagMyEAOwAbAAcJiEArFH+USaBoRE0xCH+YQAsbgLkFABqbFwIesSEYQA8qLAIAHw0AG7EPjQFRSVlDADCyGwQCGxqXAxWngwOoy4mVKjZgsQAnGqNs+SNzWsAVKOGNAD0LYXFyKVhXT19A1QAHgBidzczOfSLyzkUAMoADhAwldV1PG+MGaPAQEC4AGsIAAbaE6LxVOQAbVaRz+chqXR04gAujlAT8kVQcc0hiJ8UCkcQSb4hnYKYTCDSJjlUXp0bUGoRmjA2AB3A5tZAcmpqAkwDxbIY7fa8gVs4WI2pqa73G4rZ5LQgrOaLDULNQKk5nXr9NRqapuaVufWLI0dbqmgYWuRuRLhG1PA3206Oi7my3SkwuhBWhjGPyB8PBqOGT1AA===) in Debug mode.

### Expected behavior

The expected output (works in SharpLab Release mode):
```
<65535, 32768, 16384, 0>
<32768, 16384, 8192, 0>
<32768, 16384, 8192, 0, 0, 0, 0, 0>

<32768, 32768, 32768, 32768>
<32768, 32768, 32768, 32768>
<32768, 32768, 32768, 32768>
```

### Actual behavior

Incorrect output (eg. in SharpLab Debug mode, .NET Fiddle or on my computer both in Release and Debug builds):
```
<65535, 32768, 16384, 0>
<32769, 49152, 57344, 0>
<32769, 49152, 57344, 0, 0, 0, 0, 0>

<-32768, -32768, -32768, -32768>
<32768, 32768, 32768, 32768>
<32768, 32768, 32768, 32768>
```

### Regression?

In .NET Fiddle the .NET 6 platform appears to be working; however, some of the used overloaded operators were not available in .NET 6 so I'm not sure what it actually executes.

### Known Workarounds

Vanilla operations, explicit usage of HW intrinsics, copying the `ushort` field into an `uint` first.

### Configuration

.NET 7.0.200
Intel i5-8300H
Windows 11 (Version 10.0.22621.1265)

**Comment by EgorBo** [comment]
Seems like a small-type related bug in HW intrinsics import (with opts)

**Comment by EgorBo** [comment]
the problematic tree is:
```
└──▌  HWINTRINSIC simd16 uint Create
   └──▌  LCL_FLD   ushort(AX) V00 loc0
```
it ends up as a broadcast that loads more than ushort data

**Comment by EgorBo** [comment]
cc @tannergooding - presumably it needs GT_CAST here

**Comment by EgorBo** [comment]
Minimal repro:
```csharp
class Prog
{
    [MethodImpl(MethodImplOptions.NoOptimization)]
    static void Main()
    {
        (ushort A, ushort R) c = (1, 3);
        Vector128<uint> v1 = Vector128.Create((uint)2);
        v1 = v1 * c.A;
        Console.WriteLine(v1.ToScalar());
    }
}
```

**Comment by tannergooding** [comment]
We discussed it a bit in discord with @jakobbotsch as well and this shouldn't need a cast.

Rather there is likely something in codegen that is checking the wrong size when considering the containment opportunities.

**Comment by BruceForstall** [comment]
@jakobbotsch Can you take a look at this? In particular, do we need it fixed for .NET 8?
