### ISSUE TITLE
IsolatedStorageFile GetUserStoreForApplication() returns wrong path on .NET for iOS

### ISSUE THREAD

**Issue by akrol95** [dotnet/runtime#83384]
### Description

I recently upgraded my application from old Xamarin to new .NET 7 for Android & iOS.
Unfortunately, after installing a new version of the app on real device I noticed I lost all the data stored using Akavache library.
After some investigation I noticed that the problem lies in the path that is returned from IsolatedStorageFile.GetUserStoreForApplication() (Akavache library uses it as a path for mobile projects).

So e.g using old Xamarin.iOS framework I get:
"{some-path-with-UDID}/data/Containers/Data/Application/{UDID}/Documents/.config/.isolated-storage"

and for .NET 7 for iOS I get:
"{some-path-with-UDID}/data/Containers/Data/Application/{UDID}/Documents/.isolated-storage/uygfypsp.kjn/qxiowk50.cd0/AppFiles/"

and that's the reason the app does not see previously stored data.

I see similiar problem described in https://github.com/dotnet/runtime/issues/74642, but it does not seem to be resolved to me.

### Reproduction Steps

1. Create plain .NET for iOS project from VS for Mac or any other IDE.
2. Run the project and check out the path from IsolatedStorageFile.GetUserStoreForApplication().
3. Create plain old Xamarin.iOS project.
4. Run the project and check out the path from IsolatedStorageFile.GetUserStoreForApplication(), and then compare it to path retrieved from when using .NET 7 for iOS.

### Expected behavior

IsolatedStorageFile.GetUserStoreForApplication() should be exact the same using Xamarin.iOS and .NET 7 for iOS.

### Actual behavior

Paths are different.

### Configuration

dotnet workload: ios 16.2.1024/7.0.100 SDK 7.0.200     
TargetFramework: net7.0-ios

**Comment by steveisok** [comment]
Should be fixed by https://github.com/dotnet/runtime/pull/83380

**Comment by mkhamoyan** [comment]
Fixed by https://github.com/dotnet/runtime/pull/83380
