### ISSUE TITLE
Revert unintentional nullability changes and fix inconsistencies in StringContent ctrs

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#83423]
This is a follow-up on https://github.com/dotnet/runtime/issues/81506#issuecomment-1419473937. We introduced some inconsistencies and unintentional nullability changes in `StringContent`'s constructors. Chronologically:
- #17036 proposed new constructors before the introduction of nullable references to C#
- #33268 changed all `mediaType` args to be nullable
- We approving the new constructors, the [comment with the fianal API suggestion](https://github.com/dotnet/runtime/issues/17036#issuecomment-849820882) did not takke into account the nullability changes implemented in #33268, falsely "recommending" that nullability should be "reverted". It also proposed the argument `MediaTypeHeaderValue mediaType` to be non-nullable, which is inconsistent with the then-existing API-s.
- #63231 implemented the proposal in this form, and also altered existing `mediaType` args to be non-nullable
  - On top of that, the new constructors taking `MediaTypeHeaderValue mediaType` don't do null-check on that arg, simply allowing the property to be set to null
https://github.com/dotnet/runtime/blob/58719ec90b3bbae527dd81685bf8670b993fe8f9/src/libraries/System.Net.Http/src/System/Net/Http/StringContent.cs#L59

#81722 provides a minimal fix, however, since this was an unintentional change, I suggest to revisit it for .NET 8.0, relaxing nullability for all `mediaType` declarations, explicitly setting `text/plain` when null is being passed. This should be fairly trivial to implement.

```diff
public class StringContent : ByteArrayContent
{
-   public StringContent(string content, MediaTypeHeaderValue  mediaType);
+   public StringContent(string content, MediaTypeHeaderValue? mediaType);
-   public StringContent(string content, Encoding? encoding, string  mediaType);
+   public StringContent(string content, Encoding? encoding, string? mediaType);
-   public StringContent(string content, Encoding? encoding, MediaTypeHeaderValue  mediaType);
+   public StringContent(string content, Encoding? encoding, MediaTypeHeaderValue? mediaType);
}
```

**Comment by bartonjs** [comment]
The changes look consistent with the code's treatment of those parameters.

```diff
public class StringContent : ByteArrayContent
{
-   public StringContent(string content, MediaTypeHeaderValue  mediaType);
+   public StringContent(string content, MediaTypeHeaderValue? mediaType);
-   public StringContent(string content, Encoding? encoding, string  mediaType);
+   public StringContent(string content, Encoding? encoding, string? mediaType);
-   public StringContent(string content, Encoding? encoding, MediaTypeHeaderValue  mediaType);
+   public StringContent(string content, Encoding? encoding, MediaTypeHeaderValue? mediaType);
}
```
