### ISSUE TITLE
.Net 7-iOS: Why is the interpreter needed in .Net7 but not in Xamarin.iOS?

### ISSUE THREAD

**Issue by joduss** [dotnet/runtime#83442]
When migrating our Xamarin.iOS to .NET 7 we encountered a problem with the line expression throwing an expression. A fix was enable the interpreter for the whole app with `<UseInterpreter>true</UseInterpreter>` but this comes with a big performance reduction (at least 50% slower). Another was to enable the interpreter only for the Linq expression assembly with `<MtouchInterpreter>-all,System.Linq.Expressions</MtouchInterpreter>`. In our app we still notice some performance reduction in. Moreover the app size increased a lot compared to Xamarin.iOS.

So, my question is, why do I need to enable the interpreter (that impact performances) in the .Net 7 project but not in the Xamarin.iOS project?

### Observations 

If we inspect the content of the compiled apps from the example projects, we see that the .Net7-ios app has a System.Linq.Expression.dll but the Xamarin.iOS does not. This is true for several other System.*.dll.
In the Xamarin.iOS, there is a System.dll much larger than in the .Net7 app. In both case, neither have .aotdata.arm64 file, so I suppose they use the interpreter. Is it possible that the Xamarin System.dll actually contains the Linq library? Similarly for other libraries which are now heir own assemblies in .Net 7?

### Example Projects

[Example-Projects.zip](https://github.com/dotnet/runtime/files/10977229/Reproduction.Projects.2.zip)

**Comment by steveisok** [comment]
@joduss you're encountering BCL differences between .NET and Xamarin.  The .NET version of System.Linq.Expressions is using `Delegate.CreateDelegate` in spots, which is something our AOT compiler does not support yet.  Once https://github.com/dotnet/runtime/issues/83329 lands and from what I know now, the problem with SLE should be resolved and you won't have to switch to interpreter mode.

**Comment by joduss** [comment]
Thank you for the explanation.
