### ISSUE TITLE
Where is the  `ServiceBase.CanHandleSessionChangeEvent` ?

### ISSUE THREAD

**Issue by DUWENINK** [dotnet/runtime#83450]
In NetCore ,we suggest use `BackgroundSerivice` instead of `ServiceBase(because it is netfx)`,but,but,but, if I want use the  `CanHandleSessionChangeEvent` property ,how can I get it in NetCore

**Comment by ViktorHofer** [comment]
Hello @DUWENINK. For browsing APIs there is this excellent website called https://apisof.net. For this specific API see https://apisof.net/catalog/e0c71f13-67fb-bc9e-b631-e595462ecdda?fx=net6.0

By looking at the "Packages" row, you will see that you need to reference the `System.ServiceProcess.ServiceController` nuget package to have the API available: https://www.nuget.org/packages/System.ServiceProcess.ServiceController/8.0.0-preview.4.23259.5

**Comment by DUWENINK** [comment]
thank you I see it , and I know how to solve the same question
