### ISSUE TITLE
x64 OSX installer test failed

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#83459]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=204699
Build error leg or test failing: Build / Installer Build and Test coreclr  osx_x64 Release / Build and Package
Pull request: https://github.com/dotnet/runtime/pull/83414

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "VSTest : error : Tests failed: /Users/runner/work/1/s/artifacts/TestResults/Release/HostActivation.Tests_net8.0_x64.html [net8.0|x64] ",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[243650](https://dev.azure.com/dnceng-public/public/_build/results?buildId=243650)|dotnet/runtime|Build and Package|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/243650/logs/2265)|dotnet/runtime#82045|
|[241763](https://dev.azure.com/dnceng-public/public/_build/results?buildId=241763)|dotnet/runtime|Build and Package|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/241763/logs/2275)|dotnet/runtime#82045|
|[232568](https://dev.azure.com/dnceng-public/public/_build/results?buildId=232568)|dotnet/runtime|Build and Package|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/232568/logs/1462)|dotnet/runtime#82973|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|3|

**Comment by agocke** [comment]
@AndyAyersMS Thanks for filing this!

**Comment by agocke** [comment]
It looks like the only two builds that are still around are from https://github.com/dotnet/runtime/pull/82045

The actual failure is:

> Command did not output with Expected Output. Expected: 'Hello World!

> .NET 8.0.0-ci
> '
> File Name: /Users/runner/work/1/s/artifacts/tests/Release/ha/xu3e00sq.qb2/StandaloneApp/bin/StandaloneApp
> Arguments:
> Exit Code: 0
> StdOut:
> Hello World!

> .NET 8.0.0-ci
> [no_gc_callback] Finalizer cannot found no_gc_callback related work

@AndyAyersMS are you sure this isn't an actual failure in that PR? Looks like it's making GC changes.

**Comment by agocke** [comment]
Never mind, I can see this was just retargeted, not filed now. :)

Ok, I think those two new failures are actual failures -- and the one failure from two weeks ago is likely flaky, but the build is gone so I can't see the results in order to diagnose the problem. We haven't seen the flaky failure again, so I'm going to close this out until it's actionable.
