### ISSUE TITLE
[API Proposal]: Support Asynchronous Signing in System.Security.Cryptography.X509Certificates.X509SignatureGenerator

### ISSUE THREAD

**Issue by AliKhalili** [dotnet/runtime#83476]
### Background and motivation

Currently, the `System.Security.Cryptography.X509Certificates.X509SignatureGenerator` class does not support asynchronous signing, but the Cloud Key Provider Clients(e.g. AWS KMS) have implemented the Sign method in an async manner. As a result, when implementing a custom signing algorithm that uses the KMS Client as the underlying method for actual signing, the current solution involves blocking the calling thread using the `GetResult()` method. This approach may lead to resource starvation and deadlock if the workload is high.

To enable non-blocking signing using the async library, we need to add support for asynchronous signing in the `System.Security.Cryptography.X509Certificates.X509SignatureGenerator` class.

### API Proposal

```csharp
namespace System.Collections.Generic;

public abstract class X509SignatureGenerator 
{
    public abstract Task<byte[]> SignDataAsync(byte[] data, HashAlgorithmName hashAlgorithm, CancellationToken cancellationToken);
    protected abstract Task<PublicKey> BuildPublicKeyAsync(CancellationToken cancellationToken);
}
```

### API Usage

```csharp
class CustomX509SignatureGenerator : X509SignatureGenerator 
{
    CustomClient client = new()
    public async override Task<byte[]> SignDataAsync(byte[] data, HashAlgorithmName hashAlgorithm, CancellationToken cancellationToken) 
    {
        var signature = await client.SignAsync(data);
        return signature;
    }
}
var req = new CertificateRequest(...);
var generator = new CustomX509SignatureGenerator();
var signature = req.CreateSigningRequest(generator);
```

**Comment by vcsjones** [comment]
A couple of thoughts.

We can't add `abstract` members. That is a breaking change. At minimum, they would need to be virtual and throw. But maybe it would be reasonable to have the async implementation call the sync if no one overrides it.

The larger problem is the viral nature of async. 

Looking at your example: `req.CreateSigningRequest(generator);`

This is a synchronous method. How is this going to call the signature generator's async implementation?

If we do sync over async - we still have the problem you expressed there's going to be a `GetAwaiter().GetResult()` in there somewhere. The responsibility is just now shifted in to `CertificateRequest` but the sync over async is still there.

To do async "right" we need `CertificateRequest` to have async versions of all its APIs to call the async signature generator. And anything that wants to use the async CertificateRequest now needs to be async too.

I (personally) don't think there should be an async version of all of these APIs. It would duplicate the API surface. We could do sync over async, but that's just hiding the problem.

So I'm not sure what value is left in the proposal.

**Comment by AliKhalili** [comment]
Hi @vcsjones 

You're right, proposing a new API might not be the best solution for this issue. 

I agree with your point that the viral nature of async can make things complicated, and simply doing sync over async may not solve the underlying problem. 

It seems like a better approach might be to express the issue clearly and try to come up with a more comprehensive solution that avoids adding unnecessary complexity. 

Have you considered looking into using a different design pattern or architecture that would better handle the async/sync problem? 
Perhaps there is an existing solution that could be adapted to this specific use case.

**Comment by jeffhandley** [comment]
> Have you considered looking into using a different design pattern or architecture that would better handle the async/sync problem?

[nodding] We have, most recently when we were trying to expand the Cryptography APIs into Blazor/WASM scenarios (see #40074). In that effort, we were faced with 1 platform providing async APIs while all others provide sync APIs; we wanted to bridge the gap, but it proved to be untenable and we backed the work out.

The generalized problem of sync vs. async, particularly in this problem space, is always in the back of our minds. At this time though, I'm going to close this issue as not planned.
