### ISSUE TITLE
CPU usage increases after upgrading to .NET 6

### ISSUE THREAD

**Issue by t-bzhan** [dotnet/runtime#83505]
### Description
Our ASP.NET Core service's CPU usage increases a lot after upgrading from .NET Core 3.1 to .NET 6.0.14, we collected a trace using dotnet-trace and found that our problem is pretty similar with https://github.com/dotnet/runtime/issues/62967. We tried to disable the usage of portable thread pool with setting `COMPlus_ThreadPool_UsePortableThreadPool=0`, the trick works in our test environment, we observed CPU usage decreased as expected under stressing test, however in production, we noticed that the problem persisted.

I compared the trace under ".NET 6" with ".NET Core 3.1" and found the increased CPU usage might be caused by `Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.Heartbeat.TimerLoop()` and `System.Diagnostics.Tracing.CounterGroup.PollForValues()`
![image](https://user-images.githubusercontent.com/61817681/225588977-c3b0ca7f-b243-4942-b16b-603239d71ef7.png)

![image](https://user-images.githubusercontent.com/61817681/225590983-d79d671a-bf88-49f8-8c77-629253a632cc.png)

Could anyone suggest what steps I need to take to resolve this?

I could not share the netrace file here as it contains production data but I could share it to MS internal members, feel free to drop me a message if a netrace file could help.

### Configuration

```
# dotnet --info
.NET SDK (reflecting any global.json):
Version:   6.0.406
Commit:    2988897946 Runtime Environment:
OS Name:     ubuntu
OS Version:  22.04
OS Platform: Linux
RID:         ubuntu.22.04-x64
Base Path:   /usr/share/dotnet/sdk/6.0.406/ 

global.json file:
  Not found
Host:
  Version:      6.0.14
  Architecture: x64
  Commit:       2a90daa2cc 

.NET SDKs installed:
  6.0.406 [/usr/share/dotnet/sdk] 

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

### Regression?
That looks like a regression, I did not observe similar CPU usage in .NET Core 3.1
![image](https://user-images.githubusercontent.com/61817681/225590269-e98345ef-89b9-4e54-82bc-80f9e52daaed.png)

### Data
CPU usage increased after we rollout new version which upgrade to .NET 6.

![image](https://user-images.githubusercontent.com/61817681/225594392-dbeaa4e5-f084-4e6f-b514-fc08c378c51b.png)

### Analysis

https://github.com/akkadotnet/akka.net/issues/5385#issuecomment-1311795534 mentioned that similar CPU regression could be fixed by upgrading the runtime version to 6.0.6, however our runtime version is 6.0.14 already.

For `Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.Heartbeat.TimerLoop()`'s CPU usage https://github.com/dotnet/aspnetcore/issues/47014 explained that the data is actually somewhat misleading, since it includes time that the thread was waiting as well.

**Comment by mangod9** [comment]
@kouvel to take a look. @t-bzhan, assume you see the same behavior on 7?

**Comment by En3Tho** [comment]
One more question: have you observers other metrics change? Like RPS for example or reduced latency? Maybe something else?

**Comment by t-bzhan** [comment]
> @kouvel to take a look. @t-bzhan, assume you see the same behavior on 7?

I did not test our service behavior on .NET 7 as our pipeline does not support it yet.

**Comment by t-bzhan** [comment]
> One more question: have you observers other metrics change? Like RPS for example or reduced latency? Maybe something else?

I noticed that the average response time increase around 10ms when the number of request counts remains the same level. 
![image](https://user-images.githubusercontent.com/61817681/226091438-2485dbab-a321-4ce3-8411-abb3dca46bf7.png)

I've also collected the dontnet perf counters in .NET 6, not sure whether that is helpful:
![image](https://user-images.githubusercontent.com/61817681/226091588-f0445c15-6a55-414d-a43a-a29441be8f1c.png)
![image](https://user-images.githubusercontent.com/61817681/226091631-e4b1dfe0-0b93-4cb5-89b8-a3b97bff7fe1.png)
![image](https://user-images.githubusercontent.com/61817681/226091880-dc48155c-507d-471f-90fe-72578489bd83.png)

I kind of feeling like the issue might be caused by threadpool, I checked the `Microsoft-Windows-DotNETRuntime/ThreadPoolWorkerThreadAdjustment/Adjustment` event with perfview, however I am not able to figure out whether that is abnormal or not:
![image](https://user-images.githubusercontent.com/61817681/226092335-8a184d82-3da0-4991-bc18-244641da90fc.png)

**Comment by kouvel** [comment]
Chatted offline, the times shown in the first two stacks are likely mostly blocked time and not CPU time, suggested using [perfcollect](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/trace-perfcollect-lttng) instead.

**Comment by t-bzhan** [comment]
That is related to https://github.com/dotnet/runtime/issues/84760, close it.
