### ISSUE TITLE
Can the CoreCLR library be unloaded from the memory process?

### ISSUE THREAD

**Issue by raffaeler** [dotnet/runtime#8350]
I host the CoreCLR by myself.
Since I wrapped the "LoadLibrary / FreeLibrary" "dlopen / dlclose" in a C++ class using the RAII paradigm, at the very end my app tries to unload the CLR and crashes.
This happens with both Windows specific API (mscoree) and with platform-neutral API (coreclr_initialize & Co).

If I comment out the coreclr unloading, everything works fine and the process closes normally.
What is the rationale behind the CoreCLR library? Can it be unloaded from the process or should I avoid unloading it?

**Comment by jkotas** [comment]
> CoreCLR create an extra set of file descriptors for the stdout/stderr pipes and keeps them open 

This issue is tracked by: https://github.com/dotnet/runtime/issues/25394
