### ISSUE TITLE
Net Framework 4.8: A lot of Async Pinned System.Threading.OverlappedData

### ISSUE THREAD

**Issue by lsoft** [dotnet/runtime#83500]
### Description

Hi!

We have a old Net Framework 4.8 server, which communicates with its clients via `Socket` + `SslStream`. We have notices that server spent a lot of % CPU time in GC (from 10% up to 70%).

So we had decided to get a dump and analyze it.

We found something strange:

```
!gchandles

... (a lot of lines like these:)
000000373c862210 AsyncPinned 0000003730678b78      112                  System.Threading.OverlappedData
000000373c862218 AsyncPinned 00000037323fad58      112                  System.Threading.OverlappedData
000000373c862220 AsyncPinned 0000003729041228      112                  System.Threading.OverlappedData
...

00007ffef588e710    26256      2940672 System.Threading.OverlappedData
...
Async Pinned Handles: 26256
```

```
!finalizequeue

...
00007ffef4c0d308     2331       428904 System.Net.Sockets.OverlappedAsyncResult
00007ffef4c40d30    26388       844416 System.Net.SafeNativeOverlapped
00007ffef4c41188    24741       989640 System.Net.SafeCloseSocket
00007ffef4c3e930    24741      3562704 System.Net.Sockets.Socket
00007ffef4c40a28    24735     12466440 System.Net.Sockets.Socket+Int32TaskSocketAsyncEventArgs
```

```
0:000> !gcroot 0000003737f34f60
HandleTable:
    0000003738bc6ab0 (async pinned handle)
    -> 0000003737f34f60 System.Threading.OverlappedData

Found 1 unique roots (run '!GCRoot -all' to see all roots).
```

We checked that all of these sockets are in shutdown state and do not hold a port actually (our code closed these sockets likely).

Our code runs against socket in `async` style like:

```C#
        public static async Task<int> ReadFullAsync(
            this Socket socket,
            ArraySegment<byte> buffer
            )
{
...
                var bytesRead = await socket.ReceiveAsync(
                    buffer1,
                    SocketFlags.None
                    ).ConfigureAwait(false);
...
```

After 1 hour after the restarting of the server we see:

```
Async Pinned Handles: 2237
```

and 2% CPU in GC.

so handles are leaking with the time...

Our hypothesis: a lot of async pinned `OverlappedData` objects makes us a high percent of CPU in GC. So leaking the handles is the root of our problem.

We are stuck about the reasons of these leaks, in our code we do not see anything strange. What is direction to dig in? I understand that Net Framework is something old, and the situation (probably) is tricky, so I would ask for any tips  how to resolve this. 

Also I'm able to ask a bit specific questions:

1. Swithing to modern .Net probably should fix the problem? (a lot of work for us)
2. As a backup: switching to sync `socket.Receive` probably should fix the problem? (a lot of work for us)

(something related https://github.com/dotnet/aspnetcore/issues/472  https://github.com/SignalR/SignalR/issues/3403 - all unresolved)

Thanks!

### Reproduction Steps

None.

### Expected behavior

CPU % in GC is low. No async pinned objects.

### Actual behavior

CPU % in GC is high. A lot of async pinned objects of `System.Threading.OverlappedData` type.

### Configuration

.Net Framework 4.8
x64 application
Windows Server 2012 R2 Standard

**Comment by jkotas** [comment]
> !finalizequeue

This is very long finalizer queue. You may want to check that the finalizer thread is not blocked and that it is able to keep up with the rate that your app is producing finalizable objects. Blocked or oversubscribed finalizer thread may explain the leaks that you have been seeing.

**Comment by jeffschwMSFT** [comment]
@lsoft we track .NET Framework issues via Visual Studio dev community.  Can you create an issue on https://developercommunity.visualstudio.com/home?  Please paste the link back to this issue and we can ensure it is routed to the right team.

**Comment by lsoft** [comment]
@jeffschwMSFT  got it, give me few days to do it, please.

@jkotas looks like I misinformed you because of I gave a truncated log. here is bigger part of the log (but I can't give complete log):

```
0:000> !finalizequeue
The version of SOS does not match the version of CLR you are debugging.  Please
load the matching version of SOS for the version of CLR you are debugging.
CLR Version: 4.8.4480.0
SOS Version: 4.8.4470.0
SyncBlocks to be cleaned up: 0
Free-Threaded Interfaces to be released: 0
MTA Interfaces to be released: 0
STA Interfaces to be released: 0
----------------------------------
generation 0 has 166 finalizable objects (0000003746334460->0000003746334990)
generation 1 has 45 finalizable objects (00000037463342f8->0000003746334460)
generation 2 has 187479 finalizable objects (00000037461c6040->00000037463342f8)
Ready for finalization 22 objects (0000003746334990->0000003746334a40)
Statistics for all finalizable objects (including all objects ready for finalization):

00007ffef4c175b0        1           24 System.WeakReference`1[[System.Net.AutoWebProxyScriptEngine, System]]
00007ffef58cce18        1           32 System.Security.Cryptography.SafeKeyHandle
00007ffef58cb2a8        1           32 System.Runtime.InteropServices.NativeBuffer+EmptySafeHandle

...

00007ffef4c0d308     2331       428904 System.Net.Sockets.OverlappedAsyncResult
00007ffef4c40d30    26388       844416 System.Net.SafeNativeOverlapped
00007ffef4c41188    24741       989640 System.Net.SafeCloseSocket
00007ffef4c3e930    24741      3562704 System.Net.Sockets.Socket
00007ffef5881530    69781      5024232 System.Reflection.Emit.DynamicResolver
00007ffef4c40a28    24735     12466440 System.Net.Sockets.Socket+Int32TaskSocketAsyncEventArgs

```

I'm working with windbg only few days, so I can interpret its data in a wrong way, but I think finalization queue is short: `Ready for finalization 22 objects` and I just have a large number of finalizable object in the heap: `generation 2 has 187479 finalizable objects`.

If I interpret this data correct, finalization queue is short, and high CPU % in GC need for another explanation. Is it possible to have high CPU % in GC because of large number of async pinned objects?

```
!gchandles

... (a lot of lines like these:)
000000373c862210 AsyncPinned 0000003730678b78      112                  System.Threading.OverlappedData
000000373c862218 AsyncPinned 00000037323fad58      112                  System.Threading.OverlappedData
000000373c862220 AsyncPinned 0000003729041228      112                  System.Threading.OverlappedData
...

00007ffef588e710    26256      2940672 System.Threading.OverlappedData
...
Async Pinned Handles: 26256
```

Sorry to bother you!

**Comment by lsoft** [comment]
For anyone, who find this topic later: we switched from

```C#
                var bytesRead = await socket.ReceiveAsync(
                    buffer1, //ArraySegment<byte>
                    socketFlags //SocketFlags.None
                    ).ConfigureAwait(false);
```

to

```C#
                var currentBytesActuallyRead = socket.Receive(
                    buffer, //byte[]
                    offset,
                    toRead,
                    socketFlags ////SocketFlags.None
                    );
```

and `OverlappedData` leaking has gone. This resolves the issue for us.
