### ISSUE TITLE
FileSystemWatcher monitors a shared AWS FSx

### ISSUE THREAD

**Issue by halimote** [dotnet/runtime#83501]
I have been using FileSytemWatcher in our C# application. In Production environment it monitors a shared network location with a AWS FSx which is a unique alphanumeric name across our aws network and it has two IP address but only one IP will be up and the other will be down. The IP of this shared location keeps switching between two IP ( I think its happening during patching or maintenance of the file server). Sometimes, FileSystemWatcher is not able to identify the changes to this shared location. When we restart the application, then it is able to monitor.
It seems that when we set the monitoring path for the FSW using a network host name (Not the IP directly), its resolving that host name to the underlying IP that is up and accessible and keeps monitoring that IP. When the IP of that host name is changed, FSW is not able to reset its monitoring path to the new IP. Below are the list of questions that I have.

1. Is there a way to identify what is the IP that FSW is monitoring? We assigned network hostname to FSW, but wanted to identify the IP that FSW watches?
2. Monitoring path is set for FSW and its running and if the monitoring IP becomes inaccessible in between, is there a way to identify that the monitoring IP is not accessible/unavailable?
3. Can we make FSW smart enough to keep monitoring the host name instead of resolving it to IP and watching? IF we can make it, then we do not worry about the IP change as FSW monitors the host name instead of IP.

Appreciate your help.

**Comment by jkotas** [comment]
FileSytemWatcher uses [`inotify`](https://linux.die.net/man/2/inotify_init1) Linux kernel APIs. Resolving of network name to IP happens in AWS FSx file system driver. FileSytemWatcher is not aware of it in any way.

AWS FSx support channels are better place to ask these question.

cc @normj

**Comment by jkotas** [comment]
> When assigned with network path, does FileSystemWatcher eventually monitors the IP of that network location?

FileSystemWatcher is not aware of whether the path is a network location or IP . It just calls Linux API to monitor a path. The request to monitor a path is routed by Linux kernel to the file system driver that the path is mapped to. The file system driver then actually talks to network, resolves network names to IPs, etc.

You are asking about how AWS FSx file system driver works. This repo is not the right place to ask about internal workings of AWS FSx file system driver.
