### ISSUE TITLE
Unable to load assemblies using SDK 7.0.202 but worked on SDK 7.0.201

### ISSUE THREAD

**Issue by reduckted** [dotnet/runtime#83526]
### Description

When compiled using .NET SDK 7.0.202, code that uses `Assembly.Load(AssemblyName)` fails to load assemblies that exists in the application directory.

Here's how you can reproduce the bug. 
1. Make sure you have .NET SDK 7.0.201 _and_ 7.0.202 installed.
2. Clone https://github.com/reduckted/LoadAssemblyBug
3. Open PowerShell and run `run.ps1`.

The application is quite simple. It finds all `.dll` files in the current working directory, gets the assembly name from each file, then uses `Assembly.Load()` to load that assembly.

Use the `run.ps1` script to reproduce the bug. It will first publish the application using SDK 7.0.201, then run the application. This will succeed and you will see it log the name of each assembly that it loads. Next it will publish the application using SDK 7.0.202, then run the application. This will fail for the vast majority of assemblies.

Here's a snippet of the output when using 7.0.201:
```
Loading assembly: LoadAssemblyBug, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Loading assembly: Microsoft.AspNetCore.Antiforgery, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Loading assembly: Microsoft.AspNetCore.Authentication.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Loading assembly: Microsoft.AspNetCore.Authentication.Cookies, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Loading assembly: Microsoft.AspNetCore.Authentication.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Loading assembly: Microsoft.AspNetCore.Authentication, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
```

And here's a snippet of the output when using 7.0.202:
```
Loading assembly: LoadAssemblyBug, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Loading assembly: Microsoft.AspNetCore.Antiforgery, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Could not load file or assembly 'Microsoft.AspNetCore.Antiforgery, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60, processorArchitecture=AMD64'. The system cannot find the file specified.
Loading assembly: Microsoft.AspNetCore.Authentication.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Could not load file or assembly 'Microsoft.AspNetCore.Authentication.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60, processorArchitecture=AMD64'. The system cannot find the file specified.
Loading assembly: Microsoft.AspNetCore.Authentication.Cookies, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Could not load file or assembly 'Microsoft.AspNetCore.Authentication.Cookies, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60, processorArchitecture=AMD64'. The system cannot find the file specified.
Loading assembly: Microsoft.AspNetCore.Authentication.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Could not load file or assembly 'Microsoft.AspNetCore.Authentication.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60, processorArchitecture=AMD64'. The system cannot find the file specified.
Loading assembly: Microsoft.AspNetCore.Authentication, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Could not load file or assembly 'Microsoft.AspNetCore.Authentication, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60, processorArchitecture=AMD64'. The system cannot find the file specified.
```
### Configuration

* .NET version: **.NET SDK 7.0.202, self-contained published application.**
* OS: **Windows 10**
* Architecture: **x64**

I've tried using `Microsoft.NET.Sdk.Web` and `Microsoft.NET.Sdk`, and both exhibit the same bug.

I have not tried using a different OS.

### Regression?

Yes. This works flawlessly when compiled with .NET SDK 7.0.201.

Related to dotnet/core#8285

**Comment by jkotas** [comment]
I think we should revert the change.

**Comment by agocke** [comment]
Sorry, which change would we revert? My understanding is that https://github.com/dotnet/runtime/pull/81101 was itself a fix for a regression. If we revert it that would presumably bring back the regression.

**Comment by VSadov** [comment]
> I think we should revert the change.

This was supposed to be a compat fix making behavior closer to what was a while ago.

Do we need to re-do the change (i.e. make the algorithm even closer to what native code used to do), or we want to just revert the change?

**Comment by VSadov** [comment]
The original bug was - https://github.com/dotnet/runtime/issues/77697
I do not recall that breaking any real scenarios, but it was an observable change, so we tried to get closer to the behavior of the native code (however ad-hock it could be).

I think reverting this change and "Won't Fix"-ing the scenario is a possible way forward, so I am wondering - which way do we want to go?

**Comment by jkotas** [comment]
> My understanding is that https://github.com/dotnet/runtime/pull/81101 was itself a fix for a regression

Yes, it was trying to fix a relatively minor regression in behavior of obsolete APIs.

> I think reverting this change and "Won't Fix"-ing the scenario is a possible way forward

Yes, I think it would be the best path forward. The problem with the obsolete ProcessArchitecture part of the assembly name is that it is apparently not handled consistently throughout the system. Trying to fix it is just going to introduce more problems than it is worth it.

**Comment by arkalyanms** [comment]
Is going back to 7.0.201 the right workaround at this point?

**Comment by VSadov** [comment]
> Is going back to 7.0.201 the right workaround at this point?

Also, if code change is an option, it may help to set the ProcessorArchitecture property to `ProcessorArchitecture.None` once the name is constructed.

**Comment by farnyser** [comment]
Show stopper for us, is there a workaround beside rollback ?

**Comment by ltrzesniewski** [comment]
We got this issue with an `AssemblyLoadContext`. Specifically, `AssemblyLoadContext.LoadFromAssemblyName` rejects an `AssemblyName` with a `ProcessorArchitecture` other than `None`.

Workaround to use at the start of `AssemblyLoadContext.Load`, in case it may help anyone:

```csharp
#pragma warning disable SYSLIB0037
assemblyName = (AssemblyName)assemblyName.Clone();
assemblyName.ProcessorArchitecture = ProcessorArchitecture.None;
#pragma warning restore SYSLIB0037
```

**Comment by reduckted** [comment]
When will this be fixed? It still occurs in SDK 7.0.203.

**Comment by vitek-karas** [comment]
@VSadov did we backport https://github.com/dotnet/runtime/pull/84028 (or are we going to?)

**Comment by janstrube** [comment]
In the last few weeks we have experienced twice an intermittent error in our ASP.NET Core MVC web site: 

FileNotFoundException(Could not load file or assembly 'System.Net.Mail, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.). 

The other time another system assembly could not be found. A restart of the application (IIS app pool) resolved the issue. The web site is published self containing. In both cases the assembly with the correct PublicKeyToken existed on the server.

We have never seens such issues with 7.0.3 and below. Could this be the same issue?

**Comment by agocke** [comment]
I believe the fix for this issue should appear in 7.0.6, which should ship in May.

**Comment by mrunks** [comment]
I just noticed this issue today but have had the problem with System.Net.Mail FileNotFoundException as well as the same exception for the following:

System.IO.FileNotFoundException: Could not load file or assembly ‘System.Diagnostics.TraceSource, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a’. The system cannot find the file specified.

The systems.diagnostics.Tracesource exception was triggered when executing an OrderBy the System.Linq.Dynamic.Core library.

**Comment by mrunks** [comment]
@reduckted I hope there is.  All of the problems that have occured for that apps I work on are with Self Contained publishing.  So if others are looking for a short term solution, Framework Dependent is an option.

**Comment by schh** [comment]
Another option is to put

`<RuntimeFrameworkVersion>7.0.3</RuntimeFrameworkVersion>`

In your project files

**Comment by reduckted** [comment]
Seems to be fixed in .NET SDK 7.0.304.

**Comment by vitek-karas** [comment]
Thanks for the confirmation @reduckted . Closing.
