### ISSUE TITLE
Perf regression: Max working set on ARM

### ISSUE THREAD

**Issue by sebastienros** [dotnet/runtime#83527]
![image](https://user-images.githubusercontent.com/1165805/222528583-4500023b-969d-4168-b89c-bf081589264c.png)

**Comment by mangod9** [comment]
I notice the reduction in working set, which is now lower than 7:

![image](https://user-images.githubusercontent.com/61718172/226405842-03b9a13b-e1b7-4d84-ae33-d00824b56775.png)
