### ISSUE TITLE
Address feedback from initial config binding generator PR

### ISSUE THREAD

**Issue by layomia** [dotnet/runtime#83531]
Address all feedback not resolved in PR https://github.com/dotnet/runtime/pull/82179.

**Comment by Tornhoof** [comment]
@eiriktsarpalis in https://github.com/dotnet/runtime/pull/82179#discussion_r1135534703 you wrote that "IncrementalValuesProvider also has a RegisterSourceOutput which can be triggered independently for each of its components without forcing recalculation of the others."

Do you have examples? I couldn't find an appropriate extension method.

**Comment by eiriktsarpalis** [comment]
@Tornhoof the more accurate statement would have been that `IncrementalGeneratorInitializationContext` has an overload that accepts `IncrementalValuesProvider`:

https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.incrementalgeneratorinitializationcontext.registersourceoutput?view=roslyn-dotnet-4.3.0#microsoft-codeanalysis-incrementalgeneratorinitializationcontext-registersourceoutput-1(microsoft-codeanalysis-incrementalvaluesprovider((-0))-system-action((microsoft-codeanalysis-sourceproductioncontext-0)))
