### ISSUE TITLE
Implement proper parsing of primitives in config binder generator

### ISSUE THREAD

**Issue by layomia** [dotnet/runtime#83533]
from @eerhardt in https://github.com/dotnet/runtime/pull/82179#discussion_r1131513910 (fyi @stephentoub)

> A couple things here:
> 
> Parsing:
> 
> 1. In order to be consistent with the reflection based behavior, we need to catch the int.Parse exception thrown here, and wrap it in a `InvalidOperationException` and add the configuration path of the invalid data. This allows devs to easily know where the invalid data exists from the exception message.
> 2. This should be `int.Parse(valueString, NumberStyles.Integer, NumberFormatInfo.InvariantInfo);`
> 
> See the following for how I did it when manually writing the bind code for Console Logging:
> 
> https://github.com/dotnet/runtime/blob/967250cc86b4c613015066b47b882e7424fdb590/src/libraries/Microsoft.Extensions.Logging.Console/src/ConsoleLoggerOptions.cs#L222-L239

**Comment by ericstj** [comment]
If we decide to directly use converters we should measure the size impact -- maybe directly referencing a converter is less expensive then GetCoverter (which I think @eerhardt said is huge), but it still looks pretty big.  Maybe we can just look to the converters for inspiration of which parse/tryparse signatures to call, then generate those?

**Comment by tarekgh** [comment]
I think the idea is not using the converters at all and just having the parse code embedded inside the generated code. no dependency and not calling type converter.

**Comment by eerhardt** [comment]
For built-in types like `int`, `bool`, and `enum`, I don't see a benefit pulling TypeConverter into the app. Using the parsing logic directly makes sense to me.

See also https://github.com/dotnet/runtime/issues/44493#issuecomment-1425969210 about TypeConverter extensibility being opt-in.

The one use of config binding in Console Logging shouldn't pull in TypeConverter at all. See https://github.com/dotnet/runtime/issues/81931 for why and numbers.

**Comment by layomia** [comment]
> I think the idea is not using the converters at all and just having the parse code embedded inside the generated code. no dependency and not calling type converter.

Yeah this is what I meant.

**Comment by eerhardt** [comment]
One option for the "opt in" model of `TypeConverters` is to respect the `TypeConverterAttribute` if either:

* Directly applied to the property
* Directly applied to the Type of the property

So, for example:

```C#
[TypeConverter(typeof(PointConverter))]
public struct Point
{
   public int X;
   public int Y;
}

public class CustomOptions
{
    public Point CurrentPoint { get; set }
}
```

or

```C#
public struct Point
{
   public int X;
   public int Y;
}

public class CustomOptions
{
    [TypeConverter(typeof(PointConverter))]
    public Point CurrentPoint { get; set }
}
```
See also:

* https://github.com/dotnet/runtime/issues/44493#issuecomment-1425503530
* https://github.com/dotnet/runtime/issues/36545

**Comment by layomia** [comment]
@eerhardt I opened https://github.com/dotnet/runtime/issues/83599 to discuss this.

**Comment by layomia** [comment]
@tarekgh @eerhardt I'm using the list of "intrinsic" types specified in the core `TypeConverter` assembly to determine which primitives need support - https://github.com/dotnet/runtime/blob/967250cc86b4c613015066b47b882e7424fdb590/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.cs#L162-L198

Are there any other strategies for picking these types that come to mind?

**Comment by tarekgh** [comment]
I think the collected list of primitive is good enough and we can watch if we get more cases we need to support.

**Comment by eerhardt** [comment]
Looking at:

https://github.com/dotnet/runtime/blob/bd6ed47fb8836556db3a0f792b4c432cf5a65d4e/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L838-L873

I think starting with those built-in Types makes a lot of sense, as those will be the types that can be converted out of the box with `TypeDescriptor.GetConverter(type)`. Note you will only need the Types that have a TypeConverter that `CanConvertFrom(typeof(string)) == true`.

1. Looks like `Nullable<>` should be tested to ensure it works correctly.
2. The last Type to consider would be `byte[]`, since it is built directly into ConfigurationBinder.

**Comment by layomia** [comment]
> Looks like Nullable<> should be tested to ensure it works correctly.
> The last Type to consider would be byte[], since it is built directly into ConfigurationBinder.

Yup we already have tests for these two; will just crosscheck that the implementation lines up with reflection in both cases.
