### ISSUE TITLE
System.Net.WebSockets.Client.Tests.InvokerCancelTest.ConnectAsync_Cancel_ThrowsCancellationException test fails

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#83560]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=205207
Build error leg or test failing: WasmTestOnBrowser-System.Net.WebSockets.Client.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/81997

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "failed: Error during WebSocket handshake: Response must not include",
  "BuildRetry": false,
  "ErrorPattern": "WebSocket connection to .+ failed: Connection closed before receiving a handshake response",
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by pavelsavara** [comment]
There are no hits and I'm exploring other timeouts here https://github.com/dotnet/runtime/issues/85304

Closing this one
