### ISSUE TITLE
read mem.stat.hierarchical_memory_limit when looking for the memory limit

### ISSUE THREAD

**Issue by Maoni0** [dotnet/runtime#83563]
AWS has scenarios that use this to set the memory limit, without setting the local cgroup's limits_in_bytes. for example, this issue https://github.com/dotnet/runtime/issues/82815 illustrates such a scenario in Fargate. we could check this value if mem.limits_in_bytes is not already set. 

CC-ing @janvorli.

**Comment by normj** [comment]
Any update on this feature getting implement for .NET 8?

**Comment by mangod9** [comment]
@normj, this hasnt been implemented yet. Can this wait till 9 or is something which is blocking a critical scenario ?

**Comment by normj** [comment]
My interest is with AWS Elastic Container Service (ECS). .NET doesn't understand the available memory by default in this service due to this issue. Last march I posted a [blog post](https://aws.amazon.com/blogs/developer/configuring-net-garbage-collection-for-amazon-ecs-and-aws-lambda/) that our customers can use to help .NET understand the correct memory space but I have concerns for our customers that don't see find this blog. So I would like to push for this to be in .NET 8.

**Comment by danilobreda** [comment]
@normj this was my case, I was having memory usage issues and I ended up coming to your blog post, it was resolved. But I believe that these sharp edges should be smoother in day-to-day development.

**Comment by mangod9** [comment]
Ok we will look into implementing this, and if not too risky add it to 8. Thx!

**Comment by normj** [comment]
@mangod9 If there are private/daily builds you would like me to test with on ECS let me know.

**Comment by janvorli** [comment]
I've looked at how to get this information in the past. The cgroups v1 has the hierarchical_memory_limit, but cgroups v2 doesn't have any equivalent of that, so we will need to walk and process the group hierarchy ourselves for v2. We would want to support both v1 and v2.

**Comment by mangod9** [comment]
if ECS supports v1 perhaps we can enable that support initially, and add v2 in 9?

**Comment by normj** [comment]
ECS updated to support for V2 last year https://github.com/aws/containers-roadmap/issues/1535. I admit I'm not an expert in this space and don't know exactly when ECS chooses to use V2 or V1.

**Comment by mangod9** [comment]
If v2 could be used we will need to move this to 9 since manually parsing the hierarchy could be risky at this point, since this is a fairly critical codepath.

**Comment by normj** [comment]
I'm on PTO and back in next week. Let me check with the ECS team to see when v2 is used versus v1.

**Comment by mangod9** [comment]
@janvorl, was this implemented as part of your work around memory limit improvements early in 9?

**Comment by janvorli** [comment]
@mangod9 it was implemented in #93611. I am closing this issue now.
