### ISSUE TITLE
Short time format is missing space under en_US on Fedora 38+

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#83571]
The short time format on Fedora 38 has replaced its breaking space by a 'NARROW NO-BREAK SPACE' (`U+202F`).

That space gets removed by:

 https://github.com/dotnet/runtime/blob/34c0472fe5a237f85c39bfc45e586ac0fd6e2f11/src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.Icu.cs#L225

Any character not explicitly recognized by this function (like `U+202F`) gets removed.

This function includes a specific case for a regular 'NO-BREAK SPACE' (`U+00A0`):

https://github.com/dotnet/runtime/blob/34c0472fe5a237f85c39bfc45e586ac0fd6e2f11/src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.Icu.cs#L261-L264

There are two ways to fix this:

- Instead of removing unknown characters, we pass characters (including these non-breaking spaces) as is.
- Or, we add `U+202F` so it also gets converted to a regular space.

I don't know why the current implementation opted for the second option for `U+00A0`.
I think it may be to have the same time format as on Windows under `en_US`.

I have a slight preference for the first option, because the second is overwriting part of the format information from icu. And, the second option would have prevented this issue from occurring.

What is the preferred option?

cc @omajid

**Comment by tmds** [comment]
cc @stephentoub

**Comment by stephentoub** [comment]
> I don't know why the current implementation opted for the second option for U+00A0.
I think it may be to have the same time format as on Windows under en_US.

@ellismg, do you remember?

> Instead of removing unknown characters, we pass characters (including these non-breaking spaces) as is.

What breaks if we do that?

**Comment by tmds** [comment]
> What breaks if we do that?

It affects formatting: non-breaking spaces don't break to the next line.

It breaks tests that expect the space to be used on Linux in the `en-US` time format, like on Windows.

I was wondering about something.

```cs
using System.Text;

foreach (string s in new string[] { "'\u202F'", "'\u00A0'" })
{
    Console.WriteLine(s);
    Console.WriteLine(AsciiRoundTrip(s));
}

static string AsciiRoundTrip(string s) =>
    Encoding.ASCII.GetString(Encoding.ASCII.GetBytes(s));
```

This prints:
```
' '
'?'
' '
'?'
```


It seems neither of these non-breaking spaces get converted to regular spaces when converting to ASCII.
If that's the intended behavior for the ASCII conversion(?), it seems desired to not include non-breaking spaces for ASCII compatibility.

**Comment by tmds** [comment]
Based on the above, I assume that, for `ASCII` conversion purposes, we want regular spaces in the time format.

**Comment by stephentoub** [comment]
> I would also prefer we use the format strings as they come from icu. That is the correct choice.

You're suggesting we have two completely different parsing / formatting code paths based on whether the format string came from a user or from ICU?  What about places where these format strings are returned to the user and need to be the .NET format?  I don't see how this is a viable or correct choice.  Have I totally misunderstood?

**Comment by tmds** [comment]
This function takes the format string that comes from icu, and translate it in to the equivalent .NET format string.

**Comment by stephentoub** [comment]
Right.  It sounded like you were saying you didn't want that done at all.  I probably misunderstood... what did you mean by "I would also prefer we use the format strings as they come from icu. That is the correct choice."

**Comment by stephentoub** [comment]
> The function (ConvertIcuTimeFormatString) is currently replacing the non-breaking spaces with regular spaces, and skipping unknown characters. It could pass them through.

Right, I understand.

Is that the extent of what you meant? That for anything not understood it should just be passed through, rather than not translating anything?  I understood your comment to mean you wished zero translation was being done.

**Comment by tarekgh** [comment]
>  we may want to add an additional case (mapping 'U+202F' to ' '), 

This is wrong. CLDR intentionally added 0+202f to prevent the formatted text from wrapping in the middle. We shouldn't change the space. IIRC we already read read 'U+202F' in the number formats too.

The change here is not only readying the format, but we also want to ensure parsing should handle that too.

**Comment by tmds** [comment]
@tarekgh we should also remove the existing case for `U+00A0` then?

**Comment by tarekgh** [comment]
CLDR is already changing the usage of `U+00A0` to `U+202F` so this is not going to be important whether we change it or not. The important thing here is we want to ensure the parsing is tolerant for all these space variations.

**Comment by tarekgh** [comment]
> Yeah, but that's ASCII. Format strings can have any number of non-ASCII characters (eg, the year/month/day symbols in Japanese), 

The case here is time format and not having any date formats.

**Comment by tmds** [comment]
With my question I actually meant to ask: it was not necessary to map `U+00A0` to a regular space?

**Comment by tarekgh** [comment]
> it was not necessary to map U+00A0 to a regular space?

It was helpful to avoid the parsing problem, but this was not correct to convert it to regular space. 

I see you have opened a PR which I think need some more work. Are you willing to help get the correct fix? 

Just for reference, ICU had a similar issue too. https://unicode-org.atlassian.net/browse/ICU-20067

**Comment by tarekgh** [comment]
Here we handle these spaces in the number parsing https://github.com/dotnet/runtime/blob/6ef9d10fd024a88130155997d5de182e472ff101/src/libraries/System.Private.CoreLib/src/System/Number.Parsing.cs#L2665

**Comment by Clockwork-Muse** [comment]
> The case here is time format and not having any date formats.

Okay, fine, you can also have non-ASCII hour/minute/second characters in Japanese too.

**Comment by tarekgh** [comment]
I don't think ICU has such formats, otherwise we would see it.

**Comment by Clockwork-Muse** [comment]
.... you appear to be right, they don't seem to be doing localized time formats (other than AM/PM markers, which would be substituted in the format string, so not the same thing).  I wonder why, when they have localized date formats.

**Comment by tmds** [comment]
> I see you have opened a PR which I think need some more work. Are you willing to help get the correct fix?

Yes, I will update the PR this week based on this discussion.
