### ISSUE TITLE
CreateFromEncryptedPem fails with valid PEM/KEY files

### ISSUE THREAD

**Issue by ridomin** [dotnet/runtime#83594]
### Description

Certificates created with [step cli](https://smallstep.com/cli/) (EC certs by default) cannot be loaded with `CreateFromEncryptedPem`, however the same PEM/KEY files can be used with `openssl` without any issues (eg. to convert the PEM/KEY to PFX).

```
Unhandled exception. System.Security.Cryptography.CryptographicException: The certificate contents do not contain a PEM with a CERTIFICATE label, or the content is malformed.
   at System.Security.Cryptography.X509Certificates.X509Certificate2.CreateFromPem(ReadOnlySpan`1 certPem)
   at System.Security.Cryptography.X509Certificates.X509Certificate2.CreateFromEncryptedPem(ReadOnlySpan`1 certPem, ReadOnlySpan`1 keyPem, ReadOnlySpan`1 password)
```

I have the same error when providing a non-encrypted key

```
System.Security.Cryptography.CryptographicException: The certificate contents do not contain a PEM with a CERTIFICATE label, or the content is malformed.
   at System.Security.Cryptography.X509Certificates.X509Certificate2.CreateFromPem(ReadOnlySpan`1 certPem)
   at System.Security.Cryptography.X509Certificates.X509Certificate2.CreateFromPem(ReadOnlySpan`1 certPem, ReadOnlySpan`1 keyPem)
```

### Reproduction Steps

1. Create a test certificate (self-signed to simplify the repro steps)

```bash
step certificate create test test.pem test.key --profile self-signed --subtle
```

2. Validate the PEM/KEY files are valid and can be used with `openssl`

``` bash
openssl pkcs12 -export -in test.pem -inkey test.key -out test.pfx
```

3. Load the PFX file

```cs
var pfx = new X509Certificate2("test.pfx", "pwd");
Console.WriteLine(pfx.Subject); // outputs CN=test
```

4. Load the PEM file

```cs
var cert = new X509Certificate2("test.pem");
Console.WriteLine(cert.Subject); // outputs CN=test
```

5. Load PEM with encrypted key

```cs
var ecert = X509Certificate2.CreateFromEncryptedPem("test.pem", "test.key", "1234"); // fails
```

6. Load PEM/KEY without password

```bash
openssl ec -in test.key -out test.key2
```

```cs
var ecert = X509Certificate2.CreateFromPem("test.pem", "test.key2"); //fails
```

### Expected behavior

the certificate is loaded from the pem/key files

### Actual behavior

System.Security.Cryptography.CryptographicException: The certificate contents do not contain a PEM with a CERTIFICATE label, or the content is malformed.

### Configuration

Tried with 
- dotnet 7.0.1 in WSL Ubuntu 20
- dotnet 7.0.4 in Windows 11

**Comment by vcsjones** [comment]
> var ecert = X509Certificate2.CreateFromPem("test.pem", "test.key2");

`X509Certificate2.CreateFromPem` expects the literal contents of a PEM. Not the paths. I think you are looking for [<code>X509Certificate2.CreateFromPem<strong><em>File</em></strong></code>](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate2.createfrompemfile?view=net-7.0) an `CreateFromEncryptedPemFile`.

**Comment by ridomin** [comment]
uups, my bad.

And thx for the quick reply !!
