### ISSUE TITLE
[API Proposal]: Add analyzer for Environment.SystemDirectory

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#83591]
### Background and motivation

`Environment.SystemDirectory` is a lot more efficient than `Environment.GetFolderPath(Environment.SpecialFolder.System)`. We should add an analyzer and fixer for this.

See 
* https://github.com/dotnet/runtime/pull/83564#pullrequestreview-1345143358
* https://github.com/dotnet/aspnetcore/issues/47269

**Category**: [Performance](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/performance-warnings)
**Severity = Info**

### API Proposal

N/A

### API Usage

```diff
- Environment.GetFolderPath(Environment.SpecialFolder.System)
+ Environment.SystemDirectory
```

**Comment by stephentoub** [comment]
Should we also make GetFolderPath just return Environment.SystemDirectory for this argument?

**Comment by tannergooding** [comment]
@eerhardt, do you think this is still needed with the fix Stephen provided?

**Comment by eerhardt** [comment]
It probably has little to no value after the fix. The only places it might be beneficial is older frameworks.
