### ISSUE TITLE
[API Proposal]: Adding ForEach method for IEnumerable<T>

### ISSUE THREAD

**Issue by dayo05** [dotnet/runtime#83601]
### Background and motivation

I suggest to add just simple extension method for IEnumerable<T> which just iterate all of members with execution of delegate.

In Rust, there are function `std::iter::for_each` [Reference](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.for_each)

And also in Kotlin, there are `Iterator<T>.forEach(operation: (T) -> Unit)` [Reference](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/for-each.html)

This style of foreach makes code more simple when I need to iterate very simple things.

Example:
```cs
// Previous
var iterator = GetEnumerable();
foreach(var x in iterator)
    Console.WriteLine(x);
```
```cs
// With new method
var iterator = GetEnumerable();
iterator.ForEach(Console.WriteLine);
```

Some IDE(eg. Jetbrains Rider) supports auto complete enumerable.foreach to foreach loop. This means this style of method is popular.

### API Proposal

```csharp
namespace System.Linq;

public static partial class Enumerable
{
    public static void ForEach<T>(this IEnumerable<T> source, Action<T> action) {
        foreach(var i in source)
            action(i);
    }
}
```

### API Usage

```csharp
GetMyFancyEnumerable().ForEach(MyFunction);

void MyFunction(Foo foo) {
  // Do something fancy here
}
```
```cs
GetMyFancyEnumerable().ForEach(Console.WriteLine);
```
```cs
GetMyFancyEnumerable().ForEach(x => x.Foo());
```

### Risks

This is method is just simple convertion of foreach loop and maybe able to make more layers which can cause performance issue?
I'm not good at low level part of dotnet so I have no idea about this.

**Comment by stephentoub** [comment]
Thanks.  This has been discussed several times before, e.g. https://github.com/dotnet/runtime/issues/27560, https://github.com/dotnet/runtime/issues/40409, https://learn.microsoft.com/en-us/archive/blogs/ericlippert/foreach-vs-foreach, https://github.com/dotnet/csharplang/issues/101, ...

**Comment by layomia** [comment]
The conclusion from previous discussions is that we aren't going to do this. The other two dotnet/runtime issues cited by @stephentoub are closed, so I'll close this one as well.
