### ISSUE TITLE
NativeAOT SetCreateObject on JsonTypeInfo<T> could be slimmed down

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/runtime#83608]
SetCreateObject on `JsonTypeInfo<T>` currently holds code to deal with the untyped/typed delegate and validation. This bloats every instantiation of `JsonTypeInfo<T>` while it should just do the bare minimum for the typed side to work. 

It seems trivial to move the validation and untyped setter logic into a new non virtual method on `JsonTypeInfo`, this would then call into the abstract SetCreateObject to just do the last bits for the typed delegate in `JsonTypeInfo<T>`. 

For specifically this path SetCreateObject would probably need to be changed to return its typed delegate as `Func<object>` (or Func (or null if it's not applicable) though it could also just overwrite _createObject.
https://github.com/dotnet/runtime/blob/46632f4f47026e0befee304504dfc4c9ead80596/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfoOfT.cs#L86-L90

**Comment by eiriktsarpalis** [comment]
It might help if you could share a PR that demonstrates the change. Thanks.

**Comment by krwq** [comment]
@NinoFloris please provide sample and potential saving (can be in terms of number of method i.e. or if you have numbers from mstat file - you can get mstat file using these instructions: https://github.com/dotnet/runtime/issues/78671#issuecomment-1370315695 and dump it using https://gist.github.com/eerhardt/9c56e6c60952adf8b463839e7670c7ce) then you can search for methods you think can be removed. Also make sure to show the sample app you run this on and show size in perspective of total.
