### ISSUE TITLE
Marshal.Copy throws SEHException on Arm64.

### ISSUE THREAD

**Issue by dunkleyr** [dotnet/runtime#83626]
### Description

When Marshal.Copy is used to copy over 16 bytes from IntPtr to a byte[], an SEHException is thrown (error code 0x80004005). This is seen on an ARM64 (ZynqMP) running 5.15.36 Kernel. This doesn't happen if I PInvoke into memcopy directly. It also only happens when we have an offset into the mapped region (not on a page boundary).

### Reproduction Steps

The following is example code used to create the error. It uses mmap to access /dev/mem to map a 4K section of device memory (0xA000_0000). It then attempts to read from that section into a buffer.

Setup:
`int fh = Libc.Open("/dev/mem", FileOpenFlags.O_RDWR | FileOpenFlags.O_SYNC);`
`IntPtr map = Libc.MMap(0, 4096, MemoryMappedProtections.PROT_READ | MemoryMappedProtections.PROT_WRITE, MemoryMappedFlags.MAP_SHARED, fh, 0xA000_0000);`
`byte[] dst = new byte[4096];`
`var handle = GCHandle.Alloc(dst, GCHandleType.Pinned);`

Broken Call:
`Marshal.Copy(map + 8, dst, 0, 128);`

Working Calls:
`Marshal.Copy(map, dst, 0, 128);`
`Marshal.Copy(map, dst, 8, 128);`
`Marshal.Copy(map, dst, 0, 16);`
`Marshal.Copy(map + 8, dst, 0, 16);`
`Marshal.Copy(map, dst, 8, 16);`
`Libc.MemCopy(handle.AddrOfPinnedObject(), map + 8, 128);`

### Expected behavior

No SEHException and the memory is successfully copied.

### Actual behavior

SEHException is thrown

### Regression?

We were running this code in .net 6.0 and it worked fine, but that was under an earlier version of the Linux Kernel 4.19. The problem happened when migrating to .net 7.0 on Kernel 5.15.

### Known Workarounds

If we only do 16 bytes at a time or don't offset into the memory mapped region, then it will work.

### Configuration

AspNetCore version 7.0.1
Architecture: arm64

Processor: Xilinx ZynqMP processor
Linux Kernel: 5.15.36

### Other information

The 16 byte limit matches the maximum single transfer of the device memory space (over AXI). That may just be coincidence because the above code works in C or calling PInvoking memcpy. I tried using Span<byte>.CopyTo similar to how Marshal.Copy is doing it under the hood. I was able to create the Span objects fine. The exception is thrown when doing the actual CopyTo.

**Comment by MichalPetryka** [comment]
Dotnet does not support accessing device memory on Arm64, since it can impose additional restrictions on access like no unaligned access which dotnet does not respect.

**Comment by dunkleyr** [comment]
This worked before and we have ensured the transfers are aligned. I understand, but the framework is obviously doing something erroneously besides just a memmove.

**Comment by MichalPetryka** [comment]
> This worked before and we have ensured the transfers are aligned. I understand, but the framework is obviously doing something erroneously besides just a memmove.

Something working before does not guarantee it always working. Accessing device memory is undefined behaviour in .NET and it's up to implementation what happens then. All runtime code assumes that the same rules (like for example unaligned access support) apply to all types of memory.
CC @jkotas

**Comment by dunkleyr** [comment]
In my opinion, the framework should be capable of doing what you can do in C. It is on the implementer to ensure the architecture specific limitations are adhered to. If a memcpy works in C, but a Marshal.Copy doesn't in C# then it is a detriment to using C#.

**Comment by jkotas** [comment]
We have this documented at https://github.com/dotnet/runtime/blob/main/docs/design/specs/Memory-model.md#unmanaged-memory-access

> the framework should be capable of doing what you can do in C

Passing device memory to arbitrary C runtime methods is undefined behavior as well. memcpy from C runtime is not guaranteed to work on device memory either.

You should be able to make this work in C# by writing your own device-safe memory copy that reads the memory one byte at a time using volatile read instruction:
```
static unsafe void DeviceMemoryCopy(IntPtr source, byte[] destination, int startIndex, int length)
{
    for (int i = 0; i < length; i++)
        destination[startIndex + i] = Volatile.Read(ref *(byte*)(source + i));
}
```

**Comment by dunkleyr** [comment]
"memcpy from C runtime is not guaranteed to work on device memory either"

I disagree with this statement. It may apply in the general case, but with caching turned off, and alignment ensured (by mmap setup) there shouldn't be any issue. I (and the Xilinx Community) have done this for years without issues. Can you point me to why you think this is the case?

One byte at a time is too slow. We can just PInvoke to memcpy to do this, but it would be nice if whatever broke the runtime would get fixed down the road.

**Comment by jkotas** [comment]
> Can you point me to why you think this is the case?

For example, the manual for arm C compiler says at https://developer.arm.com/documentation/ka004708/latest : "The C compiler and C/C++ library assumes Normal memory for pointers.".

> alignment ensured

The copy statement that is failing for you does not ensure sufficient alignment relative to the length of the buffer. The ensured alignment is 8-byte only, but the length of the buffer is 128-byte. If you ensured 128-byte alignment, it would likely work fine.

> One byte at a time is too slow. We can just PInvoke to memcpy to do this,

If memcpy on your system happens to work fine for this scenario, you can certainly PInvoke it. Alternatively, you can optimize the managed implementation to do more than one byte at a time as long as it follows device memory restrictions. It is going to be slower than the vectorized implementation of memcpy.

> it would be nice if whatever broke the runtime would get fixed down the road.

Fixing this would mean regressing copy memory performance for normal memory. It would be a bad tradeoff. It is not something we are going to do.

Copy methods did not reliably work in .NET 6 either. https://github.com/dotnet/runtime/issues/66082 is a report of similar problem on .NET 6. This is not a new problem introduced in .NET 7.

**Comment by dunkleyr** [comment]
> The copy statement that is failing for you does not ensure sufficient alignment relative to the length of the buffer.

I haven't seen anything in the Arm documentation or Linux that requires length of buffer alignment (inside of a single page). Arm Processor datasheets will often have the following:

> The operand of a single-register memory access instruction has an alignment boundary equal to its length. An operand’s address is misaligned if it is not a multiple of its width

The length refers to the register width (1, 2, 4 or 8), not the buffer width which is why we always align to 8 byte addresses (to ensure we are aligned). I ran some for loops with different alignments to see what works and it appears everything that is 16 byte (128 bit) aligned works. I then found this:

https://developer.arm.com/documentation/ka004805/1-0/?lang=en

I didn't realize you can do 128 bit moves. I am guessing somewhere down the stack we are doing 128 bit access (Arm optimizations maybe?) which is a good thing. We can update our code to be 16 byte aligned and that should fix it. It would be nice to have a Marshal.ReadInt128 now, but that is a different discussion. Thanks for your help @jkotas.

**Comment by jkotas** [comment]
> I didn't realize you can do 128 bit moves. 

Arm64 SVE2 extension allows reads or writes of up to 2048 bit (256 bytes) in a single instruction.
