### ISSUE TITLE
Deserializing references results in an exception in certain situations

### ISSUE THREAD

**Issue by jonathanbyrne** [dotnet/runtime#83634]
### Description

Deserializing references results in an exception in certain situations.  It seems to be limited to hierarchies that are at least three deep and you are trying to serialize a list of all members of the hierarchy.

### Reproduction Steps

Run this code:

```C#
using System.Text.Json.Serialization;
using System.Text.Json;

public class Team
{
    public IList<Team> Children { get; private set; } = new List<Team>();

    public string Name { get; set; }
}

public class Program
{
    static void Main()
    {
        var grandparentTeam = new Team { Name = "Grandparent Team" };
        var parentTeam = new Team { Name = "Parent Team" };
        grandparentTeam.Children.Add(parentTeam);
        var childTeam = new Team { Name = "Child Team" };
        parentTeam.Children.Add(childTeam);

        var teams = new List<Team> { childTeam, grandparentTeam, parentTeam };

        var jsonSerializerOptions = new JsonSerializerOptions
        {
            ReferenceHandler = ReferenceHandler.Preserve,
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
            WriteIndented = true
        };

        var serializedTeams = JsonSerializer.Serialize(teams, jsonSerializerOptions);
        Console.Out.WriteLine(serializedTeams);

        var deserializedTeams = JsonSerializer.Deserialize<IList<Team>>(serializedTeams, jsonSerializerOptions);

        Console.Out.WriteLine(deserializedTeams);
    }
}
```

### Expected behavior

It should successfully deserialize the object.

### Actual behavior

```
System.Text.Json.JsonException: 'Reference '6' was not found. Path: $.$values[2] | LineNumber: 34 | BytePositionInLine: 5.'
```

### Regression?

Unknown.

### Known Workarounds

- Making the setter on the child collection public resolves the error.  I originally thought that this may be a poorly documented requirement.  However, the next workaround convinced me it is a bug.
- Change the order of the list being serialized from `var teams = new List<Team> { childTeam, grandParentTeam, parentTeam };` to `var teams = new List<Team> { childTeam, parentTeam, grandParentTeam };`.

### Configuration

I doubt this is configuration specific but here are all the details:

**Operating System**
```
Edition	Windows 11 Pro
Version	22H2
Installed on	‎10/‎21/‎2022
OS build	22621.1265
Experience	Windows Feature Experience Pack 1000.22638.1000.0
```

**Dotnet**
```
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.102\

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  6.0.310 [C:\Program Files\dotnet\sdk]
  7.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Device Specifications**
```
Device name	DESKTOP-2N2UM3V
Processor	11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz   3.50 GHz
Installed RAM	64.0 GB (63.6 GB usable)
Device ID	0A8368C0-D0BD-42A8-81BB-E95DF49D44F2
Product ID	00355-60680-30537-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
```

**Comment by eiriktsarpalis** [comment]
> Making the setter on the child collection public resolves the error.

This provides a hint as to the underlying issue that is causing the behavior. If you run the same code with reference handling disabled, then you'll notice that the roundtripped values do not contain any children:

![image](https://user-images.githubusercontent.com/2813363/226103582-387f024e-ad6b-4148-876d-e9c192df3b26.png)

That's because deserialization with private setters is not supported, and the relevant JSON under that property gets skipped. As a result, there's no deserialized value corresponding to `"$ref" : "6"`  which causes the error you're seeing.

You can work around the issue either by making the setter public as you said, or you could try adding the `JsonInclude` attribute to the property with the private setter:

```C#
public class Team
{
    [JsonInclude]
    public IList<Team> Children { get; private set; } = new List<Team>();

    public string Name { get; set; }
}
```

Be warned that `JsonInclude` works using private reflection, as such it's not supported if you want to eventually port your application to source gen.

**Comment by jonathanbyrne** [comment]
@eiriktsarpalis, if this is functioning as designed, why does the behavior change depending on the order of the items in the array?  That should not have any impact on the ability to deserialize.

**Comment by eiriktsarpalis** [comment]
Because changing the order of the root-level list (whose deserialization does work because it's not hidden behind a private getter) means that there are no longer any dangling `$ref` objects in its elements.

**Comment by jonathanbyrne** [comment]
That still seems like a bug to me.  Even if the property list cannot be set, the code should function the same way regardless of the root list order.  I would expect the deserializer to always ignore properties it predictably cannot load.

**Comment by eiriktsarpalis** [comment]
How would it do that? If it cannot deserialize the `$id` node, then there is no value that the subsequent `$ref` node can bind to. Like I said, fundamentally the issue you are experiencing is that your model is not deserializable -- the fact that the reference handler fails is a symptom of that issue.
