### ISSUE TITLE
Http Client  "Cannot write more bytes to the buffer than the configured maximum buffer size: 2147483647."

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#83647]
### Description

![image](https://user-images.githubusercontent.com/61237140/226176209-8975206d-fa9b-411d-b64b-af5fc695974f.png)
![image](https://user-images.githubusercontent.com/61237140/226176229-10ab2ac5-25f7-4949-a68b-37ba81fcc58c.png)
HttpClient crashes when downloading more than 2 gigabytes of information
With this error
```
System.Net.Http.HttpRequestException: Cannot write more bytes to the buffer than the configured maximum buffer size: 2147483647.
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Program.<>c.<<<Main>$>b__0_0>d.MoveNext() in C:\Users\user\source\repos\Test\Test\Program.cs:line 29
```

### Reproduction Steps

https://github.com/Mr0N/example-http-client-buffer-error

```
   try
    {
        await Task.Delay(4000);
        using var client = new HttpClient();
        var read = await (await client.GetAsync("http://localhost:5256/File"))
            .Content
            .ReadAsStreamAsync();
        using var file = new FileStream(Path.GetTempFileName(), FileMode.Create,
            FileAccess.ReadWrite,
            FileShare.None, 4000,FileOptions.DeleteOnClose);
        read.CopyTo(file);
    }
    catch(Exception ex) {
        Console.WriteLine(ex.ToString());
    }
```

### Expected behavior

*

### Actual behavior

*

### Regression?

*

### Known Workarounds

*

### Configuration

*

### Other information

*

**Comment by stephentoub** [comment]
By default, HttpClient.GetAsync buffers the full response and you can't buffer more than int.MaxValue bytes. Pass HttCompletionOption.ResponseHeadersRead as the second parameter to GetAsync to not do such buffering, or use GetStreamAsync instead of GetAsync.

**Comment by Mr0N** [comment]
> By default, HttpClient.GetAsync buffers the full response, and you can't buffer more than int.MaxValue bytes. To not do such buffering, pass HttCompletionOption.ResponseHeadersRead as the second parameter to GetAsync , or use GetStreamAsync instead of GetAsync.

strange behavior, I did not expect that my "stream" would take up so much memory)

**Comment by Mr0N** [comment]
![image](https://user-images.githubusercontent.com/61237140/226185850-90753b67-0469-4495-b180-c45f796a8e86.png)
Length not working,will probably have to get the size of the stream from the headers

**Comment by stephentoub** [comment]
> will probably have to get the size of the stream from the headers

That might be available sometimes, but you can't count on it. In a chunked response, you don't know the length until all chunks have been received.

**Comment by Mr0N** [comment]
> > will probably have to get the size of the stream from the headers
> 
> That might be available sometimes, but you can't count on it. In a chunked response, you don't know the length until all chunks have been received.

Well, in fact, here the class behaves differently up to 2 gigabytes and from 2 gigabytes, it is not good to make the behavior of the class the same, as it is from 2 gigabytes.
Well, now it will probably be difficult to change something, because many programs will stop working.
