### ISSUE TITLE
MacOS - System.Net.Security - No usable version of libssl was found

### ISSUE THREAD

**Issue by SteeBono** [dotnet/runtime#83650]
I'm trying to debug the "System.Net.Security" library in .NET 6 from MacOS but it throws error "No usable version of libssl was found" when the Iterop class tries to load the dylib lib.

<img width="735" alt="Schermata 2023-03-19 alle 18 04 00" src="https://user-images.githubusercontent.com/11635557/226194483-67a671fb-0a2c-421d-9a2b-e087a905db46.png">

It's **NOT** a **BUG** because if I compile the System.Net.Security lib in release and I reference it in my project it works fine.
I'm probably missing some configuration.

I have currently tried the following in .bash_profile (one at time and all together):

> export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
> export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
> export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
> export DYLD_FALLBACK_LIBRARY_PATH="/usr/local/opt/openssl@1.1/lib"
> export DYLD_LIBRARY_PATH="/usr/local/opt/openssl@1.1/lib"
> export CLR_OPENSSL_VERSION_OVERRIDE="1.1" (tryed because I don't know the version of lib used by .NET6)

Lib filename:

> /usr/local/opt/openssl@1.1/lib
> -r--r--r-- 19 Mar 18:00 libssl.1.1.dylib

Openssl version:

> $ openssl version
> OpenSSL 1.1.1t  7 Feb 2023

Otool:

> otool -L /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib
> /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib:
>      /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
>      /usr/local/Cellar/openssl@1.1/1.1.1t/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
>      /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)

Configuration:
NET6 - runtime 6.0.14
OS Version: Mac OS X Monterey 12.6.3 (21G419)
Architecture: X86_64

**Comment by vcsjones** [comment]
.NET on macOS doesn't normally need OpenSSL for running - only for building. Only the Unix PAL uses OpenSSL at run time in System.Net.Security.

What is the call stack of your breakpoint?

**Comment by SteeBono** [comment]
Thanks to your comment I found the problem.

Visual Studio loaded the System.Net.Security (Unix) library when I started debugging.

I hadn't noticed the OSX specific source code because VS loads the Unix version by default.

To load the OSX version from Visual Studio I had to remove "$(NetCoreAppCurrent)-linux" value from "TargetFrameworks" element from the project file.

I had to improvise because I couldn't find documentation on the repository that explains how to debug a single library for a specific platform.

Can you give me some tips about that?

However you can close this issue, thanks for your time.
