### ISSUE TITLE
watchdog still seems to be killing test runs too early

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#83654]
See the following log:
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-67c9f916a1e44c3387/Methodical_r2.0.1/1/console.4c9464c0.log?helixlogtype=result

This is in the jit-cfg pipeline. It was green until the watchdog was enabled: https://dev.azure.com/dnceng-public/public/_build?definitionId=155

Note from the log that the first test seems to start running at 23:32:37 and it then seems to have been killed at 23:37:39. Yet the log says `+ export __TestTimeout=600000`, and the tests seem to be making good progress until that.

For comparison, here is a log from one of the green runs:
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-f9802d4a08bd49cba5/Methodical_r2.0.1/1/console.9d66d6d3.log?helixlogtype=result

**Comment by jakobbotsch** [comment]
cc @ivdiazsa

**Comment by ivdiazsa** [comment]
For some reason, this specific test seems to not be taking the fix I submitted last week. If you see the launch command, it still says `$CORE_ROOT/watchdog 300`, which was the original hardcoded 5-minute time limit. But that was changed with the fix. Are you sure this is taking the latest changes?

**Comment by ivdiazsa** [comment]
I've checked the pipeline and it doesn't seem to be the case in the more recent runs. Take this one from yesterday for example:
https://dev.azure.com/dnceng-public/public/_build/results?buildId=210229&view=results

Check this log for example: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-7c20b5106ff84bbfb0/HardwareIntrinsics_r.0.20/1/console.12c7caa5.log?helixlogtype=result

The test is actually timing out. The command is calling `$CORE_ROOT/watchdog 600000`, just as specified by `__TestTimeout`. And the test is being killed precisely after 10 minutes. Starts at 23:35 and is killed at 23:45.

So, this is a problem with the test that the watchdog is catching. Either there is a performance bug there, or that specific test needs to have its `__TestTimeout` value adjusted, wherever that is. The watcher only reads what was set to it beforehand.

**Comment by jakobbotsch** [comment]
I must have been looking at the wrong long. Here is comparison with a green run:
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-f9802d4a08bd49cba5/HardwareIntrinsics_r.16.20/1/console.cad79791.log?helixlogtype=result

So it actually takes 23 minutes for the HardwareIntrinsics_r runs to finish. So there must be a mismatch between how `__TestTimeout` is treated by the watchdog and by the rest of the infrastructure -- maybe `__TestTimeout` is for individual tests, not the whole work item? Should the watchdog use the work item timeout instead?

**Comment by ivdiazsa** [comment]
There is no mismatch between the watchdog and the environment variable, as the watchdog simply reads it.

> Should the watchdog use the work item timeout instead?

That could be it. Is this stored in another environment variable? Or if not, how can we know the value? So we can tell the watchdog to use it.

**Comment by jakobbotsch** [comment]
> There is no mismatch between the watchdog and the environment variable, as the watchdog simply reads it.

I mean a mismatch between how the watchdog treats `__TestTimeout` and how the rest of the test infrastructure treats it, since the green log shows that `__TestTimeout` was not failing the work item before. Some grepping in the repo shows e.g. comments like:

> Set __TestTimeout environment variable, which is the per-test timeout in milliseconds.

But these work items run many tests.

> That could be it. Is this stored in another environment variable? Or if not, how can we know the value? So we can tell the watchdog to use it.

It looks like there's some good information here:

https://github.com/dotnet/runtime/blob/4bd7819e55e0c6bf43cca2cb2988537cd10eddda/eng/pipelines/common/templates/runtimes/test-variables.yml#L9-L22

So probably this `timeoutPerTestCollectionInMinutes` is what you need to be using (well, maybe a bit smaller to give the watchdog time to its thing?). It is set to 120 minutes for `jit-cfg`, which corresponds to the 7200 seconds we see at the top of the log.

Looks like you might need to add a new environment variable to pass it along in helixpublishwitharcade.proj.

**Comment by ivdiazsa** [comment]
> > There is no mismatch between the watchdog and the environment variable, as the watchdog simply reads it.
> 
> I mean a mismatch between how the watchdog treats `__TestTimeout` and how the rest of the test infrastructure treats it, since the green log shows that `__TestTimeout` was not failing the work item before. Some grepping in the repo shows e.g. comments like:
> 
> > Set __TestTimeout environment variable, which is the per-test timeout in milliseconds.
> 
> But these work items run many tests.
> 
> > That could be it. Is this stored in another environment variable? Or if not, how can we know the value? So we can tell the watchdog to use it.
> 
> It looks like there's some good information here:
> 
> https://github.com/dotnet/runtime/blob/4bd7819e55e0c6bf43cca2cb2988537cd10eddda/eng/pipelines/common/templates/runtimes/test-variables.yml#L9-L22
> 
> So probably this `timeoutPerTestCollectionInMinutes` is what you need to be using (well, maybe a bit smaller to give the watchdog time to its thing?). It is set to 120 minutes for `jit-cfg`, which corresponds to the 7200 seconds we see at the top of the log.
> 
> Looks like you might need to add a new environment variable to pass it along in helixpublishwitharcade.proj.

Got it, thanks for the detailed explanation. I will work on and have the adjustment PR up soon.

**Comment by ivdiazsa** [comment]
Closing as per PR #83746 merged.
