### ISSUE TITLE
SocketsHttpHandler's PooledConnectionLifetime being Infinite on K8s

### ISSUE THREAD

**Issue by marcinjahn** [dotnet/runtime#83665]
The default value of the `PooledConnectionLifetime` property of `SocketsHttpHandler` (which is the default handler for `HttpClient`) is `Timeout.InfiniteTimeSpan`.

I think this value might be problematic in scenarios such as pod-to-pod communication in K8s when using factory-managed `HttpClient`. A pod usually communicates with other pods through a service. However, a service just resolves to an IP address of an actual target pod. Therefore, the source-pod that establishes communication with some target-pod, talks with that pod directly instead of going through some intermediate load-balancer. In cases where the communication between pods is frequent (less than 1 minute between requests by default - [PooledConnectionIdleTimeout](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.pooledconnectionidletimeout?view=net-8.0#system-net-http-socketshttphandler-pooledconnectionidletimeout)), the source pod will keep talking with the same pod of the target service, even though the target service could have many more replicas.

It might cause performance issue, which horizontal scaling of the target service does not resolve. The source pod will keep talking to the same target pod, which might be overwhelmed by the amount of requests being sent.

If the default value would stay the same, I think there should be some guidance on what setting would be appropriate for the case described above.

**Comment by ManickaP** [comment]
I'm not sure what the exact ask here is. Do you suggest we change the default value for everyone? Are you in a position where you cannot tweak the value yourself? What do you think the ideal value would be?

If you're after load balancing feature, you might be interested in [YARP](https://github.com/microsoft/reverse-proxy). cc @MihaZupan

**Comment by wfurt** [comment]
I think it is hard to make general recommendation. Certainly specifics to pods seems beyond scope of HttpClient. 
It feels like we should strive to document existing nobs and explain how that impact observed behavior. If the K8s needs something special user familiar with it should be bale to make right choices. 

I personality feel that `PooledConnectionLifetime` is only one part and in principal there is nothing wrong with long value .... if the connection is healthy and connection errors propagate properly. Reusing same connection/TLS is most efficient and cleanup may be done by the idle timeout e.g. when we keep around unused connection (that may become stale)

**Comment by marcinjahn** [comment]
Alright, thanks for your comments, I think the issue could be closed.
