### ISSUE TITLE
Confusing error message.

### ISSUE THREAD

**Issue by careri** [dotnet/runtime#83667]
Hi.

I think there is a mixup of the parameters going into the exception being thrown. The last argument should be `typeToConvert` instead of `converter.TypeToConvert`. At the moment the error says that the converter isn't compatible with the value it converts.
It should look like this:
```cs
          if (!converter.TypeToConvert.IsInSubtypeRelationshipWith(typeToConvert))
            {
                ThrowHelper.ThrowInvalidOperationException_SerializationConverterNotCompatible(converter.GetType(), typeToConvert);
            }
```

https://github.com/dotnet/runtime/blob/50fa756a2f1020bd21b8e72e5750d307e38d72e0/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/DefaultJsonTypeInfoResolver.Converters.cs#L159

**Comment by krwq** [comment]
@careri do you feel like sending a PR?

**Comment by careri** [comment]
@krwq what branches should I target?
