### ISSUE TITLE
Hierarchical ActivityID of ETW events becomes unrelated GUID when iterating over ETL files

### ISSUE THREAD

**Issue by xinyugu1998** [dotnet/runtime#83663]
Hi,

I'm trying to use PerfView to collect ETW events from an ASP .Net Core application, and I hope to link the System.Net.Http events from the same request by ActivityID.
In PerfView, I got hierarchical ActivityIDs like these:
<img width="1445" alt="image" src="https://user-images.githubusercontent.com/104054856/226293286-6e5ccc98-b495-4d8c-b4aa-8cec439cecad.png">
So I thought I could link the events with the same ActivityID prefix.

However, when I use another process to iterate over the collected ETL file, the ActivityIDs become GUIDs and I cannot find enough correlation among them.
Here are the ActivityIDs and RelatedActivityIDs I got when iterating:
```
Request/Start AID: 00002c1c-0000-0000-0000-0000ddb69d59
Request/Start RAID: 00000000-0000-0000-0000-000000000000

Activity2Start/Start AID: 00102c1c-0000-0000-0000-0000ddb6ad59
Activity2Start/Start RAID: 00002c1c-0000-0000-0000-0000ddb69d59

Resolution/Start AID: 00112c1c-0000-0000-0000-0000ddb6ae59
Resolution/Start RAID: 00102c1c-0000-0000-0000-0000ddb6ad59

RequestHeaders/Start AID: 00132c1c-0000-0000-0000-0000ddb6b059
RequestHeaders/Start RAID: 00000206-0001-0000-1473-0000ffdcd7b5

ResponseHeaders/Start AID: 00142c1c-0000-0000-0000-0000ddb6b159
ResponseHeaders/Start RAID: 00000222-0001-0000-1473-0000ffdcd7b5

ResponseContent/Start AID: 00202c1c-0000-0000-0000-0000ddb6bd59
ResponseContent/Start RAID: 00000209-0001-0000-1473-0000ffdcd7b5

Accept/Start AID: 0000241c-0000-0000-0000-0000ddce9d59
Accept/Start RAID: 00000071-0001-0000-1473-0000ffdcd7b5

Connect/Start AID: 00122c1c-0000-0000-0000-0000ddb6af59
Connect/Start RAID: 0000020b-0001-0000-1473-0000ffdcd7b5
```
The only correlation I can find is that Request/Start AID=Activity2Start/Start RAID, Activity2Start/Start AID=Resolution/Start RAID, and other events' RAID have the same suffix 0001-0000-1473-0000ffdcd7b5. But this is not enough to link all of them.

Could anyone give any advice? Thanks very much!

**Comment by tommcdon** [comment]
@brianrob @noahfalk is this a perfview/traceevent issue or a problem in the runtime?

**Comment by tarekgh** [comment]
CC @davmason

**Comment by noahfalk** [comment]
Is the issue that PerfView is unable to correlate the events correctly, or PerfView works but some other software you are writing is failing to reproduce what PerfView is doing?

In general to correlate events using ActivityIDs you need to look at all events in the stream. Its not clear from the set of events you called out above whether those Related Activity IDs are refering to events IDs on events you have yet to look at, or if the ID is entirely missing on any previous event. If it helps here is [a little information](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/eventsource-activity-ids) on how these IDs are intended to work.

**Comment by brianrob** [comment]
I should clarify that using the ActivityID / RelatedActivityID to correlate is something that you can do when you're consuming the events.  This isn't anything that would happen in the runtime - the runtime will already set the ActivityID and RelatedActivityID according to these rules.  If you want to correlate between these activities, you'll need to do the same with the ActivityID and RelatedActivityID when you're analyzing the events.
