### ISSUE TITLE
Arm64 macOS uses different sign character on ToString() on a LONG

### ISSUE THREAD

**Issue by JoakimJohesan** [dotnet/runtime#83671]
### Description

Hi, when trying to run an existing unit-test on my new machine MacOS Ventura 13.2.1 with an M2 Pro CPU. (ARM64) the tests failed. 

The test used ToString() on a LONG, and the output from ToString on macOS contained `U+2212 : MINUS SIGN` as the sign character instead of `U+002D : HYPHEN-MINUS {hyphen, dash; minus sign}` that is used on all other platforms.

macOs: `−`
Linux/Windows: `-`

Result running on MacOs:
```
$ dotnet test
  Determining projects to restore...
  All projects are up-to-date for restore.
  Tests -> /Users/johesan/git/Repro/Tests/bin/Debug/net7.0/Tests.dll
Test run for /Users/johesan/git/Repro/Tests/bin/Debug/net7.0/Tests.dll (.NETCoreApp,Version=v7.0)
Microsoft (R) Test Execution Command Line Tool Version 17.5.0 (arm64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed TestFailsOnMacOsArm64 [16 ms]
  Error Message:
     String lengths are both 11. Strings differ at index 0.
  Expected: "-1204555125"
  But was:  "−1204555125"
  -----------^

  Stack Trace:
     at Tests.Tests.TestFailsOnMacOsArm64() in /Users/johesan/git/Repro/Tests/UnitTest1.cs:line 12


Failed!  - Failed:     1, Passed:     1, Skipped:     0, Total:     2, Duration: 17 ms - Tests.dll (net7.0)
```

Result using dotnet/sdk docker image running locally:
```
$ docker run --rm -it -v "/Users/johesan/git/Repro:/repro" mcr.microsoft.com/dotnet/sdk 
$ dotnet test
  Determining projects to restore...
  Restored /repro/Tests/Tests.csproj (in 3.17 sec).
  Tests -> /repro/Tests/bin/Debug/net7.0/Tests.dll
Test run for /repro/Tests/bin/Debug/net7.0/Tests.dll (.NETCoreApp,Version=v7.0)
Microsoft (R) Test Execution Command Line Tool Version 17.5.0 (arm64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed TestPassOnMacOsArm64 [16 ms]
  Error Message:
     String lengths are both 11. Strings differ at index 0.
  Expected: "−1204555125"
  But was:  "-1204555125"
  -----------^

  Stack Trace:
     at Tests.Tests.TestPassOnMacOsArm64() in /repro/Tests/UnitTest1.cs:line 25


Failed!  - Failed:     1, Passed:     1, Skipped:     0, Total:     2, Duration: 20 ms - Tests.dll (net7.0)
```

### Reproduction Steps

Check reproduction project here: https://github.com/JoakimJohesan/ReproduceToStringIssue
```cs
namespace Tests;

public class Tests
{
    [Test]
    public void TestFailsOnMacOsArm64()
    {
        long value = -1204555125;
        var valueString = value.ToString();
        
        // U+002D HYPHEN-MINUS character (-)
        Assert.That(valueString, Is.EqualTo("-1204555125"));
    }
    
    [Test]
    public void TestPassOnMacOsArm64()
    {
        long value = -1204555125;
        var valueString = value.ToString();
        
        // U+2212 : MINUS SIGN
        Assert.That(valueString, Is.EqualTo("−1204555125"));
    }
}
```

### Expected behavior

Expected ToString on macOS to use the same sign character as all other platforms

### Actual behavior

ToString uses U+2212 : MINUS SIGN instead of U+002D : HYPHEN-MINUS {hyphen, dash; minus sign}

**Comment by Joe4evr** [comment]
> it was not expected that InvariantCulture had to be used as it's a very basic thing.

No, this is how .NET has behaved for two decades: If you want consistent strings everywhere, you have to specify a culture. It's also why you should enable the analyzers that tell you you should be using method overloads that explicitly take in a `CultureInfo`/`IFormatProvider` whenever they exist (CA1304 & CA1305) to avoid these kinds of surprises.

**Comment by tarekgh** [comment]
.NET uses the globalization data provided by the underlying the OS ICU library. Usually, CLDR/Unicode standard decides it. You cannot assume globalization data cannot change or get updated. As pointed out earlier, the only culture data guaranteed to not change is the Invariant data. NumberFormatInfo for any culture can give you the sign used by this culture and that what you need to use instead of assuming specific sign. by that I am closing this issue but feel free to send any question if you still have any. Thanks for your report.
