### ISSUE TITLE
[API Proposal]: Add Marshal.ReadInt128 and Marshal.WriteInt128 methods

### ISSUE THREAD

**Issue by dunkleyr** [dotnet/runtime#83684]
### Background and motivation

Now that we have Int128 support (#67151), it would be nice to have the ability to read and write those values directly from/to unmanaged memory similar to Marshal.ReadInt64 and Marshal.WriteInt64. Several Arm64 and x64 (SSE) processors support this already:

https://developer.arm.com/documentation/ka004805/1-0/?lang=en
https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/x64-instructions

The value added would be atomic access to 128-bit unmanaged values and faster 128-bit interop.

### API Proposal

```csharp
namespace System.Runtime.InteropServices;

public static partial class Marshal
{
    public static unsafe Int128 ReadInt128(IntPtr ptr, int ofs);

    public static Int128 ReadInt128(IntPtr ptr) => ReadInt128(ptr, 0);

    public static unsafe void WriteIn128(IntPtr ptr, int ofs, Int128 val);

    public static void WriteInt128(IntPtr ptr, Int128 val) => WriteInt128(ptr, 0, val);
}
```

### API Usage

```csharp
// Pulled from ReadInt64 Example.
// Allocate unmanaged memory. 
int elementSize = 16;
IntPtr unmanagedArray = Marshal.AllocHGlobal(10 * elementSize);

// Set the 10 elements of the C-style unmanagedArray
for (int i = 0; i < 10; i++)
{
    Marshal.WriteInt128(unmanagedArray, i * elementSize, ((Int128)(i + 1)));
}
Console.WriteLine("Unmanaged memory written.");

Console.WriteLine("Reading unmanaged memory:");
// Print the 10 elements of the C-style unmanagedArray
for (int i = 0; i < 10; i++)
{
    Console.WriteLine(Marshal.ReadInt128(unmanagedArray, i * elementSize));
}

Marshal.FreeHGlobal(unmanagedArray);

Console.WriteLine("Done. Press Enter to continue.");
Console.ReadLine();
```

### Alternative Designs

The above API uses Int128, but the Int64 versions use the long alias. If a similar alias is developed for Int128 (llong maybe?) then that alias should be used instead of Int128.

### Risks

This shouldn't affect any previous code, but the risk would be if a processor architecture doesn't support 128-bit access then what would the call do. The easiest would be to provide a NotImplementedException (or something similar). x64 and arm64 should be ok, but arm32 may not have an equivalent.

**Comment by AaronRobinsonMSFT** [comment]
This doesn't seem like a imminent need so I am moving to Future. Will monitor as we see community interest.

**Comment by tannergooding** [comment]
I don't see the benefit of such an API. Just utilize `Unsafe.ReadUnaligned` and `Unsafe.WriteUnaligned` which will do the right thing and do it more efficiently in general.

The modern/better approach to the sample code given would be:
```csharp
nuint elementCount = 10;
Int128* unmanagedArray = (Int128*)NativeMemory.Alloc(elementCount, (uint)sizeof(Int128));

// Set the 10 elements of the C-style unmanagedArray
for (nuint i = 0; i < elementCount; i++)
{
    Int128 value = (Int128)(i + 1);
    Unmanaged.WriteUnaligned((unmanagedArray + i), value);
}
Console.WriteLine("Unmanaged memory written.");

Console.WriteLine("Reading unmanaged memory:");
// Print the 10 elements of the C-style unmanagedArray
for (nuint i = 0; i < elementCount; i++)
{
    Int128 value = Unsafe.ReadUnaligned(unmanagedArray + i);
    Console.WriteLine(value);
}

NativeMemory.Free(unmanagedArray);

Console.WriteLine("Done. Press Enter to continue.");
Console.ReadLine();
```

There are many alternatives to this as well, including using `NativeMemory.AlignedAlloc` and `NativeMemory.AlignedFree` to guarantee higher alignment (such as `16-bytes`). Directly reading/writing the addresses such as `unmanagedArray[i] = (Int128)(i + 1);` and `Console.WriteLine(unmanagedArray[i])`, etc.

**Comment by MichalPetryka** [comment]
@tannergooding What is the proper alignment for Int128 in C#? 4, 8 or 16?

**Comment by jkotas** [comment]
> The value added would be atomic access to 128-bit unmanaged values and faster 128-bit interop.

The existing `Marshal.Read/Write` APIs do not guarantee atomic access. Also, the existing `Marshal.Read/Write` API have unnecessary overhead since their contracts requires to throw `AccessViolationException` instead of the standard `NullReferenceException`. 

`Unsafe.ReadUnaligned` and `Unsafe.WriteUnaligned` (and other options) are the recommended replacements as @tannergooding said.

**Comment by tannergooding** [comment]
> What is the proper alignment for Int128 in C#? 4, 8 or 16?

Depends on what exactly you're talking about.

It is defined as `2x UInt64` fields and so it will have the same GC alignment as a `System.UInt64`. Some 64-bit platforms require it to have a packing of 16-bytes, however and so it will have a default field offset that is a multiple of 16 on such platforms. Such platforms may expect or assume the struct has 16-byte alignment as well (much like `__m128` which corresponds to `Vector128<T>`).

**Comment by tannergooding** [comment]
> The current Marshal methods are great for us because we don't have to mark DLLs or code sections as unsafe

You should typically treat `Marshal` as if you had to write `unsafe`. It is itself "unsafe" and can often be more unsafe than actually using `unsafe` due to loss of type safety.

> It would be nice if Int128 had more support across the board (BitConverter, etc.) with what we have previously been able to do with Int64.

This support has generally been added in .NET 8 already. We will likewise be exposing other corresponding APIs as appropriate/needed. Marshal just happens to be one where there are better modern recommendations.

**Comment by dunkleyr** [comment]
Its policy driven. If a whole library is marked as unsafe, the whole library needs to be checked for unsafe regions so they can be scrutinized more. I understand Marshal has the same risks, but peer reviewing and runtime checking of IntPtr values is typically easier than allowing unsafe code in general (IMO).

> So is the plan to obsolete Marshal.ReadInt* methods down the road?

My whole point is to round out the existing API with Int128 support, but it sounds like you are saying the existing API shouldn't be used anyway.
