### ISSUE TITLE
System.Runtime|exception-count metric shows different values after migration from netcore3.1 to net6

### ISSUE THREAD

**Issue by mindyli1989** [dotnet/runtime#83690]
### Description
We are doing migration from netcore3.1 to net6. I noticed the geneva metric dashboards with using `System.Runtime|exception-count` metric started to doubled the exception amount after we migrated to net6.
![image](https://user-images.githubusercontent.com/128417937/226439569-34aca57f-ca24-4927-b8c3-dc4ac717c79a.png)

I have checked the logs and seems the logs amount in net6 is similar to what we had when using netcore3.1. In this case, it seems the `System.Runtime|exception-count` should remain the similar amount after we migrated to net6.
May I ask why the exception count values doubled after migration to net6 in the `System.Runtime|exception-count` metric? Thanks!

**Comment by jkotas** [comment]
> May I ask why the exception count values doubled after migration to net6 in the System.Runtime|exception-count metric?

It is not possible to answer this question without looking at the stacktraces for the exceptions being thrown. Could you please share the stacktraces of the exceptions being thrown?

The most likely explanation is that there is a new place where an exception is caught and rethrown in .NET 6.
