### ISSUE TITLE
Questions about JsonSerializer.Deserialize

### ISSUE THREAD

**Issue by Bunnui** [dotnet/runtime#83704]
I'm having a problem where I have a record base type (not abstract and interface) and I use `JsonPolymorphic`, putting `TypeDiscriminatorPropertyName = "type"`, and `IgnoreUnrecognizedTypeDiscriminators = true` when an unknown type is encountered, He will return the base type, but in fact it does not assign a value to the base type "type", is this a bug?

![image](https://user-images.githubusercontent.com/37466008/226499563-dda7d0dd-b71e-48bc-8544-913b64de15cd.png)
![image](https://user-images.githubusercontent.com/37466008/226499631-07eef3b0-7b0b-4ee9-9971-67ec331c689e.png)

Because the service program belongs to someone else's, I am worried that he will introduce unknown types, so I hope to accept it so that I can add new types so that I can better analyze the data.

Also, I wonder if at `JsonSerializer.Deserialize` can bind unresolved content data to custom properties like `JsonPolymorphic(TypeDiscriminatorPropertyName = "type")`, so that the data can be analyzed

**Comment by pinkfloydx33** [comment]
Last I can recall, you cannot have am _actual_ property for the discriminator field. There's definitely some older issues in this repo requesting that it be supported, so it's quite possible it's changed by now, but I don't remember seeing any updates just yet. 

Essentially what I'm saying is: remove the property. If you really want/need it, one solution is to make it an abstract property that you decorate with `JsonIgnore` and then require all sub types to override. We did something similar before deciding to remove it altogether.

**Comment by krwq** [comment]
it's currently not supported. My suggestion will be to directly implement static abstract member with the same type discriminators.

There is currently couple of parallel issues with treating metadata similar to properties:
- https://github.com/dotnet/runtime/issues/79482
- https://github.com/dotnet/runtime/issues/75269
- https://github.com/dotnet/runtime/issues/72170

possibly we should expose polymorphic metadata as regular JsonPropertyInfo to allow these scenarios to work.

**Comment by krwq** [comment]
In order to move this forward sooner it would be good if we created specific design proposal on how to modernize metadata handling (i.e. show them as JsonPropertyInfo, then perhaps trying to prototype that and seeing if that is sound plan). Once we have specific plan we all agree on we can consider that for vNext or we can leave it for volounteers to pick up.

**Comment by Bunnui** [comment]
> This is by design -- type discriminators are identifiers associated with particular derived types on the type level and not values that can be read from or written to object properties. Such a feature would not be polymorphism per se, rather, it is informing the contract of a serialized type dynamically based on contents of its values (and not its runtime type). As such, it is not in scope for the polymorphism feature.

Please don't use 'This is by design' as an excuse. It's flawed.
Instead of deserializing a primitive type without a value, at least when you encounter an unrecognized type discriminator, you should deserialize a primitive type and pass the identifier name associated with the discriminator. I think this is what the discriminator to do their job ` IgnoreUnrecognizedTypeDiscriminators = true ` I think ignoring the type of unrecognized discriminator is not necessary, really need is to specify the type of the unrecognized discriminator to assign a derived class. Otherwise wouldn't it be better to catch the exception directly? It ignores types it doesn't recognize, but it deserializes a blank type, so what's the point of this property?

Directly catching the exception, when the derived class has a property with other polymorphic types, then I can only analyze the whole original data, which is inconvenient, because he can't write the original type and original data.

Get the raw data: considering JSON parsing is using 'Utf8JsonReader', record the start position at the beginning of the object and the end position at the end of the object receiving record, then write this unrecognized data to the custom property (provided the property name is set)


Microsoft wants people to use 'System.Text.Json', but every time they ask a question, they use 'This is by design' as an excuse, instead of making changes to make 'System.Text.Json' easier to use. On the other hand, it makes it harder for developers to rewrite a lot of things themselves each time, and Enum custom names don't support custom Json names.

**Comment by eiriktsarpalis** [comment]
I'm sorry you feel that way, but as already mentioned, the type discriminator is designed to be a type-level mapping and does not bind to runtime values of properties (either in serialization or deserialization). As with any feature of such a nature, it is necessarily opinionated so it can't cater to every use case (similar to how the `ReferenceHandler.Preserve` doesn't bind reference metadata to properties). I would suggest writing your own custom converter that handles polymorphism in a way that satisfies your use case.
