### ISSUE TITLE
Inefficient codegen with struct consisting of 2 SIMD vectors.

### ISSUE THREAD

**Issue by MichalPetryka** [dotnet/runtime#83749]
### Description

CoreCLR emits inefficient codegen when working with structs consisting of 2 SIMD vectors, for example custom structs with 2xVector128 or Vector512 on platforms without AVX512.

If you compare the codegen for methods A and B in the reproduction, you can notice the JIT spilling the custom structs instead of promoting them in B. The goal here would be to have B emit the same codegen as A does.
If you look at Memmove there, you'll notice that the JIT does not spill them, but introduces a lot of redundant adds and leas in the codegen.

[Reproduction](https://gist.github.com/MichalPetryka/ce7052f1f57832aa307bf1037278624b)

### Configuration

Windows x64 .Net 8 preview 2

### Regression?

Probably not, checked just stack spilling and it occurs on .Net 7

**Comment by jakobbotsch** [comment]
The problem is here:
https://github.com/dotnet/runtime/blob/e43ddbf9dcf52d643a0714f0668b2ab978f0b386/src/coreclr/jit/lclvars.cpp#L2252-L2270

Since `B` uses no SIMD intrinsics the JIT assumes the fields of `Vector2x128` are not SIMD types and we end up skipping promotion due to that.
