### ISSUE TITLE
[wasm] wasm-experimental: dotnet publish with output directory doesn't put the AppBundle in the output directory

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#83760]
.NET 8 Preview 2

```console
$ dotnet new wasmbrowser
$ dotnet publish -c Release -o pub
...
```

What I expect:

The `pub` directory contains `index.html`, `dotnet.wasm`, etc.  The stuff that normally would end up in `bin/Release/net8.0/browser-wasm/AppBundle/`

What actually happens:

The `pub` directory contains `libmonosgen-2.0.a`, `pinvoke.c`, `runtime.es6.iffe.js`, etc...

**Comment by maraf** [comment]
This will be solved with taking over blazor sdk bits in https://github.com/dotnet/runtime/issues/70762

**Comment by lewing** [comment]
I believe this is fixed now

**Comment by maraf** [comment]
It will be fixed once we move our templates to WasmSDK. I'll close the issue, since there is no extra work needed
