### ISSUE TITLE
AddHttpClient configuration action is never called

### ISSUE THREAD

**Issue by francotiveron** [dotnet/runtime#83772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

F#
```
let host = 
    Host
        .CreateDefaultBuilder(args)
        .UseSerilog(Action<_,_,_>(
            fun (_: HostBuilderContext) (services: IServiceProvider) (loggerConfiguration: LoggerConfiguration) -> 
                loggerConfiguration.WriteTo.Console().ReadFrom.Services(services) |> ignore), false, false)
        .ConfigureServices(fun services -> 
            services
                .AddSingleton(policy)
                .AddTransient(typeof<YatpMaintenanceService>, serviceType) |> ignore
                        
            services
                .AddHttpClient(fun client -> client.BaseAddress <- Uri(apiHost))
                .AddTransientHttpErrorPolicy(fun builder -> builder.WaitAndRetryAsync(3, fun _ ->TimeSpan.FromSeconds(5))) |> ignore) 
        .Build()

```

```
let ``do`` (httpCLient: HttpClient) (): Task = task {
    let! rsp = httpCLient.PostAsync("/ensure-feed", null) 
    rsp.EnsureSuccessStatusCode() |> ignore }


type Service(policy: IsPolicy, httpClientFactory: IHttpClientFactory) = 
    inherit YatpMaintenanceService(policy)
    override __.Job = ``do`` (httpClientFactory.CreateClient())
```

### Expected Behavior

- Configuration action **_fun client -> client.BaseAddress <- Uri(apiHost)_** should be called when **_CreateClient_** is invoked
- **_httpClient.BaseAddress_** should be non null inside **_\`\`do\`\`_**

### .NET Version

7.0.202

### Anything else?

The call to AddTransientHttpErrorPolicy is also ineffective (no retry is carried out)

.NET SDK:
 Version:   7.0.202
 Commit:    6c74320bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.202\

Host:
  Version:      7.0.4
  Architecture: x64
  Commit:       0a396acafe

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]
  6.0.300-preview.22204.3 [C:\Program Files\dotnet\sdk]
  6.0.301 [C:\Program Files\dotnet\sdk]
  6.0.310 [C:\Program Files\dotnet\sdk]
  7.0.102 [C:\Program Files\dotnet\sdk]
  7.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by davidfowl** [comment]
What overload of AddHttpClient is this calling?:

```F#
AddHttpClient(fun client -> client.BaseAddress <- Uri(apiHost))
```

**Comment by francotiveron** [comment]
> 

![image](https://user-images.githubusercontent.com/8280970/227044268-be6a3fda-8634-4db0-9756-d6f4c11e7560.png)

**Comment by francotiveron** [comment]
> What overload of AddHttpClient is this calling?:
> 
> ```fsharp
> AddHttpClient(fun client -> client.BaseAddress <- Uri(apiHost))
> ```
![image](https://user-images.githubusercontent.com/8280970/227044451-db747962-850e-4802-ab6f-9849d4ad950a.png)

**Comment by halter73** [comment]
> Generic parameters: 
> 'TClient is unit
> 'TImplmentation is unit

Could that be the issue? You probably want to use a [named client](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-7.0#named-clients) which doesn't require any generic parameters to identify it.

**Comment by francotiveron** [comment]
I have tried

![image](https://user-images.githubusercontent.com/8280970/227046654-97947ab9-c7eb-4552-a09f-8fd48c01a5e7.png)
 and named clients too, no difference

**Comment by halter73** [comment]
I was suggesting [this overload](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.httpclientfactoryservicecollectionextensions.addhttpclient?view=dotnet-plat-ext-7.0#microsoft-extensions-dependencyinjection-httpclientfactoryservicecollectionextensions-addhttpclient(microsoft-extensions-dependencyinjection-iservicecollection-system-string-system-action((system-iserviceprovider-system-net-http-httpclient)))) that takes no generic parameters and takes a string as the first non-this parameter.

```fsharp
    .AddHttpClient("my-name", fun client -> client.BaseAddress <- Uri(apiHost))
//...
    override __.Job = ``do`` (httpClientFactory.CreateClient("my-name"))
```

**Comment by francotiveron** [comment]
> I was suggesting [this overload](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.httpclientfactoryservicecollectionextensions.addhttpclient?view=dotnet-plat-ext-7.0#microsoft-extensions-dependencyinjection-httpclientfactoryservicecollectionextensions-addhttpclient(microsoft-extensions-dependencyinjection-iservicecollection-system-string-system-action((system-iserviceprovider-system-net-http-httpclient)))) that takes no generic parameters and takes a string as the first non-this parameter.
> 
> ```fsharp
>     .AddHttpClient("my-name", fun sp client -> client.BaseAddress <- Uri(apiHost))
> //...
>     override __.Job = ``do`` (httpClientFactory.CreateClient("my-name"))
> ```

![image](https://user-images.githubusercontent.com/8280970/227051383-ce880940-b790-49b9-90a0-a35d9a36294e.png)

![image](https://user-images.githubusercontent.com/8280970/227051666-8f4629e1-e92a-4051-828c-dbfd36b188a9.png)

**Comment by halter73** [comment]
You're still selecting a generic overload ov `AddHttpClient` that expects a `Func<HttpClient, IServiceProvider, 'TImplementation>` where `'Timplementation` is `unit`. The non-generic overload expecting a `Action<IServiceProvider, HttpClient>` should work.

```fsharp
.AddHttpClient("my-name", Action<_,HttpClient>(fun _ client -> client.BaseAddress <- Uri(apiHost)))
```

**Comment by francotiveron** [comment]
Yes, this works, but would be good to understand why the others don't

![image](https://user-images.githubusercontent.com/8280970/227095037-be909c57-0a81-43f0-a9fd-1dabe907a645.png)

**Comment by francotiveron** [comment]
> I assume this is the same F# limitation as the one in here [#45035 (comment)](https://github.com/dotnet/runtime/issues/45035#issuecomment-733670334)

Yes, it does. thanks.
