### ISSUE TITLE
File.WriteAllText with Invalid File Name Chars in path writes 0 bytes and continues silently without exception

### ISSUE THREAD

**Issue by RonSijm** [dotnet/runtime#83778]
### Description

When using 

`await File.WriteAllTextAsync("C:\\temp\\File:Name.txt", "Content to be written");` or
`File.WriteAllText("C:\\temp\\File:Name.txt", "Content to be written");`

A file is created at: `C:\temp\File` - but the file is 0 bytes.

I noticed this when trying to write a file with a datatime in it.

### Reproduction Steps

    namespace FileWriteAllText_ZeroBytes
    {
        internal class Program
        {
            public static async Task Main(string[] args)
            {
                await File.WriteAllTextAsync("C:\\temp\\File:Name.txt", "Content to be written");
            }
        }
    }

### Expected behavior

Expected: an exception is thrown

### Actual behavior

The path is broken up at the invalid path character. For example:

`"C:\\temp\\File:Name.txt"` becomes `"C:\\temp\\File`

And then 0 bytes are written to that file.

This is confusing behavior, because half of the expected operation is performed (partially) - but no data written to the file. 

### Configuration

Windows11 x64 dotnet7

**Comment by stephentoub** [comment]
This is by design. That path is creating a file named "File" with an NTFS Alternate Data Stream named "Name.txt". That stream contains your data.

https://learn.microsoft.com/en-us/sysinternals/downloads/streams
