### ISSUE TITLE
Update MsQuic version in helix docker images

### ISSUE THREAD

**Issue by CarnaViire** [dotnet/runtime#83782]
Several helix docker images install a fixed MsQuic version, which is outdated by now.

We need to update the versions, and if possible, change to consuming the package from a package manager (even if it's a hack like in case of [Mariner 2.0](https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/68720f2fae2f9e5b7c3cd19c695b80f9fdbb51e8/src/cbl-mariner/2.0/helix/amd64/Dockerfile#L18-L25))

- [ ] OpenSUSE 15.2 x64 -- [currently has MsQuic 2.1.1](https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/1d2766c4bd1f68902cf4044f03d9f7040e922e48/src/opensuse/15.2/helix/amd64/Dockerfile#L43) -- in PR https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/828
- [ ] Debian 10 arm32 -- [currently has MsQuic 2.1.2](https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/25861af309ac7a423e6d1933c13a3ac798522c26/src/debian/10/helix/arm32v7/Dockerfile#L49-L53) -- in PR https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/828
- [ ] Debian 11 arm32 -- [currently has MsQuic 2.1.2](https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/25861af309ac7a423e6d1933c13a3ac798522c26/src/debian/11/helix/arm32v7/Dockerfile#L38-L42) -- in PR https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/828
- [ ] Ubuntu 18.04 arm64 -- [currently has MsQuic 2.1.1]() -- in PR https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/827

**Comment by wfurt** [comment]
note that this is not necessarily too bad. In practice we may see different versions in the field as well. But striving towards package manager will save us maintenance time. 
Ubuntu 18 will be EOS soon and Ubuntu 20 should work with auto updates. 
That still mean we need to rebuild the image to get latest upgrades.

**Comment by wfurt** [comment]
linked PRs are merged. I guess we can close this @CarnaViire?  (even if there is no runtime change)
