### ISSUE TITLE
[Memory consumption] Remove relocations for Readonly section

### ISSUE THREAD

**Issue by gbalykov** [dotnet/runtime#8379]
Hello.

We propose to reduce consumption of memory, which currently occurs due to applying relocations to Readonly section of ngen-ed images (for pointers related to MethodTable).

To achieve this, we propose to partially replace absolute pointers, which require allocations, with relative pointers and also to move structures, which contain the other part of absolute pointers, to separate section in ngen-ed image.

Next absolute pointers will be replaced with relative pointers
```
ModuleCtorInfo::ppMT
ModuleCtorInfo::ppHotGCStaticsMTs
ModuleCtorInfo::ppColdGCStaticsMTs
GenericsStaticsInfo::m_pFieldDescs
MethodTable::m_pLoaderModule
MethodTable::m_pEEClass
MethodTable::m_pCanonMT
MethodTable::m_pInterfaceMap

InterfaceInfo_t::m_pMethodTable
MethodTable::m_pPerInstInfo
MethodTable::m_pWriteableData
MethodTable::m_pParentMethodTable
MethodTable's vtable-1st-level-indirection
```

Next structures are moved to separate subsection of Readonly section in ngen-ed image
```
MethodTable's dictionary
MethodTable's vtable-2nd-level-indirection
```

On application, which is referenced in dotnet/runtime#7694 (comment), the following memory consumption changes occur for mappings of images (based on 5d2a54449d6b9d8fecb788e741654d7dbd992a87):

Rss: 8368 -> 8308 (0.7% improvement)
Private_Dirty: 3008 -> 2588 (14% improvement)
Private_Clean: 336 -> 348
Shared_Clean: 5024 -> 5372

We plan to open pull-request shortly.

cc: @Dmitri-Botcharnikov @ruben-ayrapetyan

**Comment by jkotas** [comment]
The code for fragile ngen has been deleted.
