### ISSUE TITLE
[API Proposal]: ToArray and ToList overloads with length argument

### ISSUE THREAD

**Issue by edokan** [dotnet/runtime#83807]
### Background and motivation

For most operations, ToArray and ToList use shortcuts to create correctly sized arrays to copy the contents of the source into. Still, when they cannot predict the size of the target array, they use different ways to create the underlying arrays.

Arrays use LargeArrayBuilder for the worst-case scenario in which it manages and grows an internal array each time it hits the capacity by doubling the array size and copying the interim array to the new one. The List class does a very similar thing in its constructor.

We can cut these array resizing operations by introducing an overload to ToArray and ToList and accepting the initial size of the target collections.

While this may only help with some cases, it can help with the ones where we, as programmers, already know the target size of the array, like when we do paging or record limiting.

Adding an argument named length may confuse some users (is it the number of items to copy), but I could not develop a better alternative.

### API Proposal

```csharp
using System.Collections.Generic;

namespace System.Linq;

public static partial class Enumerable
{
    public static TSource[] ToArray<TSource>(this IEnumerable<TSource> source);
    public static TSource[] ToArray<TSource>(this IEnumerable<TSource> source, int length);
}
```

### API Usage

```csharp

var pageSize = 100;
var pageIndex = 0;

var userList = dbLayer.Users
                      .OrderBy(u => u.Id)
                      .Skip(pageSize * pageIndex)
                      .Take(pageSize)
                      .ToArray(pageSize);
```

### Risks

Since this change is intended only for the initial size of the destination types, there should be no performance issue. There should be no breaking change other than the cases where `Enumerable.ToArray` is used as an argument with delegate type.

**Comment by eiriktsarpalis** [comment]
> My main concern is for the collections that do not implement such cases where the code has to use EnumerablePartition<T> or LargeArrayBuilder<T>. I believe they are in place because there are collections that do not support those interfaces.

If such cases cause measurable performance issues in your app, then LINQ is probably not the best set of APIs to use anyways.

**Comment by eiriktsarpalis** [comment]
I'm definitely not trying to attack or criticize you, I'm sorry if you feel I came across like that. I'm simply trying to understand your motivation for making the proposal, given that the original https://github.com/dotnet/runtime/issues/29620 was closed.

**Comment by edokan** [comment]
There are two comments in that thread relative to this issue:

 * https://github.com/dotnet/runtime/issues/29620#issuecomment-849406019 This one makes a benefit analysis based on the author's knowledge of the dotnet code base (I assume a lot) and their assumption of the use cases where they see little to no benefit from a similar suggestion. The author also suggests the original poster write a method for a specific case, then goes on to tirade about how people will perceive this as a cheap performance solution.

 * https://github.com/dotnet/runtime/issues/29620#issuecomment-956501584 And this one belongs to you (@eiriktsarpalis) where you think it is an opportunity to optimize ToDictionary, instead of implementing the proposed API.

My primary use case is extracting datasets from anywhere but databases where `IIListProvider` is not implemented. In most cases, I can estimate number of records that will return, or better yet, the data provider can provide the number of items in the dataset even before reading. Indeed, I can write a method like the one Lookup, and I have already done so.

My and other authors' suggestion is not strictly necessary, but it can improve for the better and does not even require any changes in the existing code in the wild.

On the other side, the "length" parameter was supposed to tell the initial size of the resulting array/list, just to drop numbers of the resize operations; it should have no side effect if not specified or the specified value is smaller than the size of the actual resultset.

One dataset I had had twenty years' worth of hourly data, which is supposed to quadruple when we switch to the 15-minute periods, assuming that I read from a stream with no seek, ToArray that uses LargearrayBuilder requires at least 16 reallocation/copy operations with ever-increasing number items to build a buffer of 262K array, and then another to build result array of 175K items.

Given that I represent a minority, I see your reluctance to add a change to one of the most used APIs in existence (GitHub alone contains 18M references to C# ToArray), it is still worth it, in my humble opinion.

I have a handful of useful functions that are so obvious people have been actually surprised that are not part of the Framework already. One example is ToArray(int), and another is IsNullOrEmpty for ICollection. I can write them, but I want everyone to enjoy them.

I hope this explanation is enough and clear because it hits the limits of my English.

**Comment by eiriktsarpalis** [comment]
There are many seemingly useful IEnumerable extension methods that could be considered for inclusion to Linq proper. However, more often than not, we err towards refraining from adding them for several reasons: intellisense bloat, assembly size concerns and the fact that it is often trivial for users to write their own extensions as per their requirements. 

While examining API proposals for Linq, we focus on functionality that is either difficult to replicate or provides high impact for a majority of Linq users. In terms of overloads for presizing destination buffers, it is a set of APIs that prioritizes performance and raises the following questions:

1. Why use LINQ if the code is in a critical hot path?
2. If presizing the destination buffer is a concern, should the user also contemplate buffer pooling?
3. What should be the course of action if the source enumerable surpasses the length provided by the user? Should the operation fail or should it quietly proceed with resizing the destination buffer?

All of the above makes me think that such overloads would not be suitable for inclusion to System.Linq.

**Comment by edokan** [comment]
Those are all valid concerns and thank you for the insights into the team's way of thinking. Let me try to address them.

1. Because it has already been there for some time, be it ancient code migrated from old projects or developed when performance was not the priority, as it is not most of the time. One other reason is that LINQ makes code more readable and approachable for newcomers because of its naming and easy-to-follow fluent structure.
2. This is a very valid suggestion and should be considered by every team, but it may prove very hard to utilize appropriately, according to my experience. It also reminds me of a paragraph (I'm unable to find for this comment) for a similar class, `StringBuilderPool`, where it is kept `internal` since it is easy to use in incorrect ways by the users.
3. In my proposal, it was the initial size of the Array/List, so it would work just like it had been working. Should users give a size smaller than their result, it would resize. The Intention here is to cut the number of reallocations and copy operations.

One can write an extension for this specific purpose that even utilizes `ArrayBuffer<>` and publish it as a NuGet package. We can use it, but how does it help with all the concerns you pointed like IntelliSense and assembly sizes? We would include yet another assembly to IntelliSense and our project to use only one function or a few if we are lucky.

I don't want to sound condescending or judgmental, but most of the NetCore group does not share your specific concerns, and they should since they are sound. Allocating memory according to the number of processors and giving no way to control it when using server GC is such a case where it made Kubernetes usage for processes that are heavy on the CPU power but light on the memory usage incredibly hard on both management and accounting.

**Comment by stephentoub** [comment]
> but most of the NetCore group does not share your specific concerns

I'm not sure who "NetCore group" is, but if you're referring to the .NET team at Microsoft on which @eiriktsarpalis works, many of us _do_ share his concerns.

There are practically an infinite number of possible extension methods one could write for `IEnumerable<T>`, and we include only the corest of the core on the `Enumerable` type.  For everything else, there are a myriad of libraries folks have created to include the extensions they believe to be most valuable, and thankfully many have published them on nuget for others to consume.  I'd encourage you to use one of them if it provides the additional extension you desire.

Beyond the previously cited concerns, there are also functional concerns.  With ToArray, for example, what if the specified number of items isn't exactly what's in the source?  You cite paging as an example, using Take, but Take only refers to a maximum; it's possible and even likely at the end of a paged data source for there to be fewer items. So should the API resize to be the actual number of items copied, or does such an API actually need another out parameter to indicate how many items were copied?  If the number of items ends up being more than what was specified, should the array grow, or should it be treated just as a hint?  Should we actually be considering a `CopyTo(Span<T>)` API instead? There are many possible variants someone could reasonably want here, and we're not in the business of supplying all of them.  The answer is possibly easier with a `ToList`, but there as well as cited in the other issues this duplicates, you can do `var list = new List<T>(capacity); list.AddRange(source);`.

This proposal has been considered multiple times in the issues cited as this being a duplicate of.  I'm not seeing new information that suggests it needs to be reconsidered at this time.  But thank you for your interest and arguments.

**Comment by edokan** [comment]
@stephentoub and @eiriktsarpalis, thank you for your consideration. You both listened to my arguments and decided against them, fair enough. I will close the issue.
