### ISSUE TITLE
net7: ValidationProblemDetails cannot be handled by JsonSerializerContext

### ISSUE THREAD

**Issue by oising** [dotnet/runtime#83815]
### Description

When attempting to add the new Json serializer context source generators to my NET 7 MVC project, and following the apparently breaking changes in https://github.com/dotnet/runtime/issues/77115, my Web Api attempted to return a `ValidationProblemDetails` and I received a runtime error of:

```text
System.NotSupportedException: Metadata for type 'Microsoft.AspNetCore.Mvc.ValidationProblemDetails' was not provided by TypeInfoResolver of type 'MyJsonSerializationContext'. If using source
generation, ensure that all root types passed to the serializer have been indicated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically.
```

So, I added `[JsonSerializable(typeof(Microsoft.AspNetCore.Mvc.ValidationProblemDetails))]` to the `JsonSerializerContext` and now I get the following at _compile_ time:

```
'ValidationProblemDetailsJsonConverter' is inaccessible due to its protection level.
```

### Reproduction Steps

- create a dotnet 7 webapi project
- return a custom type from a webapi method
- create a custom json serializer context for this custom type
- test return of the custom type (should be ok)
- introduce a runtime error in the return of the method, returning a ValidationProblemDetails

This will introduce the runtime error. Follow the instructions from the runtime, and you will receive the previously mentioned compile-time error  as the source generator cannot generate boilerplate for VPD.

### Expected behavior

`[JsonSerializable(typeof(Microsoft.AspNetCore.Mvc.ValidationProblemDetails))]` should work on the custom context.

### Actual behavior

`[JsonSerializable(typeof(Microsoft.AspNetCore.Mvc.ValidationProblemDetails))]` fails.

### Regression?

A likely regression implied via https://github.com/dotnet/runtime/issues/77115 but I cannot test here.

### Known Workarounds

No idea. 

```csharp
#if DOTNET6_0 || DOTNET8_0            
            options.JsonSerializerOptions.AddContext<MySerializationContext>();
#endif
```

:(

### Configuration

dotnet sdk 7.0.4

**Comment by eiriktsarpalis** [comment]
Addressed in https://github.com/dotnet/aspnetcore/issues/43236. Should be fixed in .NET 8 Preview-2

**Comment by oising** [comment]
> cc @eerhardt. The ASP.NET team is working to provide a solution specifically for that use case in .NET 8.
> 
> As a temporary workaround, you could try using configuring your JsonSerializerOptions to use reflection-based fallback:
> 
> ```cs
> options.TypeInfoResolver = JsonTypeInfoResolver.Combine(MySerializationContext.Default, new DefaultJsonTypeInfoResolver());
> ```

A minor correction to your workaround (for anyone else who finds this thread):

```csharp
options.**JsonSerializerOptions**.TypeInfoResolver = JsonTypeInfoResolver.Combine( ...
```
