### ISSUE TITLE
Make ParameterBuilder abstract

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#83831]
With [Abstract System.Reflection.Emit public types](https://github.com/dotnet/runtime/issues/78542) we have abstracted other `System.Reflection.Emit.XyzBuilder` types, `ParameterBuilder` type left out from this effort (probably because it lives in different ref file).

The type also needs to be abstracted same as others because:
 - Because of internal constructor could not create an instance of it outside of CoreLib. (The new `AsemblyBuilder` implementation will be added outside of CoreLib)
 - Even if we workaround the internal constructor we could not get `CustomAttributes` info set to the `ParameterBuilder` instance, same for the default value.

### Suggested API change:
```diff
namespace System.Reflection.Emit
{
-   public class ParameterBuilder
+   public abstract class ParameterBuilder
    {
-       internal ParameterBuilder() { }
+       protected ParameterBuilder() { }
        public virtual int Attributes { get { throw null; } }
        public bool IsIn { get { throw null; } }
        public bool IsOptional { get { throw null; } }
        public bool IsOut { get { throw null; } }
        public virtual string? Name { get { throw null; } }
        public virtual int Position { get { throw null; } }
        public virtual void SetConstant(object? defaultValue) { }
        public void SetCustomAttribute(ConstructorInfo con, byte[] binaryAttribute) { }
+       protected abstract void SetCustomAttributeCore(ConstructorInfo con, byte[] binaryAttribute);
        public void SetCustomAttribute(CustomAttributeBuilder customBuilder) { }
    }
}
```

**Comment by teo-tsirpanis** [comment]
How about we seize the opportunity and make `SetCustomAttributeCore` accept a `ReadOnlySpan<byte>`? No need to also expose it as a public method, this can happen as part of #63419.

**Comment by buyaa-n** [comment]
Internal implementation currently works with byte[], of course we could refactor that, I think that is better handled by https://github.com/dotnet/runtime/issues/63419 with all other types custom attributes handling (looks all of them handled similarly).

**Comment by terrajobst** [comment]
* The core method should be based on `ReadOnlySpan<byte>`
    - We should align the other ones we added this release

```diff
namespace System.Reflection.Emit;

-public class ParameterBuilder
+public abstract class ParameterBuilder
 {
-    internal ParameterBuilder();
+    protected ParameterBuilder();
     public virtual int Attributes { get; }
     public bool IsIn { get; }
     public bool IsOptional { get; }
     public bool IsOut { get; }
     public virtual string? Name { get; }
     public virtual int Position { get; }
     public virtual void SetConstant(object? defaultValue);
     public void SetCustomAttribute(ConstructorInfo con, byte[] binaryAttribute);
+    protected abstract void SetCustomAttributeCore(ConstructorInfo con, ReadOnlySpan<byte> binaryAttribute);
     public void SetCustomAttribute(CustomAttributeBuilder customBuilder);
 }
```
