### ISSUE TITLE
Support more formats in json TimeOnlyConverter

### ISSUE THREAD

**Issue by cdrfenix** [dotnet/runtime#83863]
Hi, i expected that **System.Text.Json.Serialization.Converters.TimeOnlyConverter** internally used "TimeOnly.Parse", since trying to parse "19:00" (without seconds) is valid input and one that is frequently used, the same as "7:00 PM" that is the output of TimeOnly.ToShortTimeString(). But neither of them works when trying to deserialize, i think TimeOnlyConverter needs to be a little more consistent with the formats supported by TimeOnly.

https://github.com/dotnet/runtime/blob/11ff382d63966d9ac7bbab1fb5f2425498cc01a8/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Value/TimeOnlyConverter.cs#L9

**Comment by svick** [comment]
I think that, at least by default, JSON should be treated as a strict, machine-readable format. It should not be treated as something that contains human-readable values and certainly not values that are culture-specific. So `TimeOnly.Parse(value)` would not be appropriate.

If you need different behavior for your specific use case, can't you write a custom converter?

**Comment by cdrfenix** [comment]
I didnt think about it when i writed this issue, i guess its made to follow the ISO 8601-1:2019 format as specified in this link.

https://learn.microsoft.com/en-us/dotnet/standard/datetime/system-text-json-support?pivots=dotnet-7-0

Ill need to create my own converters for TimeOnly, DateOnly and DateTime for specific culture.
