### ISSUE TITLE
Add VectorTableLookup/VectorTableLookupExtension support in mono

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#83891]
https://github.com/dotnet/runtime/issues/81599

Enable disabed tests in #80297

**Comment by kunalspathak** [comment]
@vargaz @fanyang-mono . Perhaps worth mentioning an entry in https://github.com/dotnet/runtime/issues/82859 as well.

**Comment by fanyang-mono** [comment]
The Mono intrinsics support was added via https://github.com/dotnet/runtime/pull/80297 and tests were enabled via https://github.com/dotnet/runtime/pull/84330. Closing this issue as all the work has been completed.
