### ISSUE TITLE
System.Diagnostics.Tests.EventLogMessagesTests crash

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#83915]
Access violation at
```
 # Call Site
00 wevtapi!Event::SetOwner
01 wevtapi!EventBatch::~EventBatch
02 wevtapi!EventBatch::`scalar deleting destructor'
03 wevtapi!EventBatch::ReleaseEvent
04 wevtapi!Event::HandleRelease
05 wevtapi!EvtClose
06 System_Diagnostics_EventLog_Tests!System_Diagnostics_EventLog_Microsoft_Win32_UnsafeNativeMethods___EvtClose_g____PInvoke_33_0
07 System_Diagnostics_EventLog_Tests!System_Diagnostics_EventLog_System_Diagnostics_Eventing_Reader_EventLogHandle__ReleaseHandle
08 System_Diagnostics_EventLog_Tests!S_P_CoreLib_System_Runtime_InteropServices_SafeHandle__InternalRelease
09 System_Diagnostics_EventLog_Tests!S_P_CoreLib_System_Runtime_InteropServices_SafeHandle__Finalize
0a System_Diagnostics_EventLog_Tests!S_P_CoreLib_System_Runtime___Finalizer__DrainQueue
0b System_Diagnostics_EventLog_Tests!S_P_CoreLib_System_Runtime___Finalizer__ProcessFinalizers
0c System_Diagnostics_EventLog_Tests!FinalizerStart
0d kernel32!BaseThreadInitThunk
0e ntdll!RtlUserThreadStart
```

Failed in #83881

Full log https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-83881-merge-6afb3e7c23b6419d8d/System.Diagnostics.EventLog.Tests/1/console.3869e255.log?helixlogtype=result

**Comment by danmoseley** [comment]
(windows.81.amd64.open.rt) executed on machine a000M4U running Windows-2012ServerR2-6.3.9600-SP0

**Comment by ViktorHofer** [comment]
@jkotas based on Dan's comment this was executed on Windows 8.1 which we don't support anymore (even though the underlying actual OS is Windows Server 2012 R2). Should we close this issue?

**Comment by jkotas** [comment]
The queue is called windows.81, but the actual OS running in that queue is Windows Server 2012: `(windows.81.amd64.open.rt) executed on machine a000M4U running Windows-2012ServerR2` Windows Server 2012 is still supported: https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md

This was one-off crash that we have not seen for months. I am ok with closing this issue.
