### ISSUE TITLE
[API Proposal]: Dictionary.TrySetValue

### ISSUE THREAD

**Issue by chr1st0scli** [dotnet/runtime#83920]
### Background and motivation

In accordance to the closed proposal  #14676 for adding a dictionary record without a duplicate lookup operation, I would find a similar method in IDictionary for updating a value very useful.

`bool TrySetValue(TKey key, TValue value);`

The whole point is not just ease of use and expressiveness, but also avoiding the double lookup operation. The goal is to update a value if the key is already there, but not add it or trigger an error if it is absent.

### API Proposal

```csharp
namespace System.Collections.Generic
{
    public interface IDictionary<TKey, TValue> : ICollection<KeyValuePair<TKey, TValue>>, IEnumerable<KeyValuePair<TKey, TValue>>, IEnumerable
    {	
        bool TrySetValue(TKey key, TValue value)
        {
            // This is a default interface method expressed in terms of IDictionary's existing
            // members, so that existing implementing concrete classes will not break.
            // But some core .NET classes like the Dictionary, will have to provide their own implementation
            // to avoid the double lookup demonstrated here.
            if (!ContainsKey(key))
                return false;

            this[key] = value;
            return true;
        }
    }
}
```

### API Usage

```csharp
var myDictionary = new Dictionary<string, int>();
// Add records to the dictionary...

if (!myDictionary.TrySetValue("a key", 0))
    return false; // or ignore or whatever...
```

### Risks

In my understanding the closed proposal #14676 has been implemented as the extension method TryAdd in CollectionExtensions, but I might be wrong. The essence of my request (avoiding the double lookup) might not be possible to be implemented as an extension method, because that would not have access to the internals of the Dictionary. So, if the request is realized, there might be a design discrepancy with the TryAdd extension method.

**Comment by theodorzoulias** [comment]
Check out [this](https://stackoverflow.com/questions/72837813/how-to-update-the-value-of-a-key-in-a-dictionary-but-only-if-the-key-already-ex/72837894#72837894 "How to update the value of a key in a dictionary, but only if the key already exists, without hashing the key twice?") StackOverflow answer. It shows how to implement this API, using tools that already exist.

**Comment by eiriktsarpalis** [comment]
`Dictionary` and `ConcurrentDictionary` have the [`TryAdd` method](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.tryadd?view=net-8.0). Doesn't this cover your use case?

If this is about extending IDictionary, adding new members to existing comes with [risk of breaking change](https://github.com/dotnet/runtime/issues/55106), so it's something we've not done so far.

**Comment by chr1st0scli** [comment]
> `Dictionary` and `ConcurrentDictionary` have the [`TryAdd` method](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.tryadd?view=net-8.0). Doesn't this cover your use case?
> 
> If this is about extending IDictionary, adding new members to existing comes with [risk of breaking change](https://github.com/dotnet/runtime/issues/55106), so it's something we've not done so far.

Hi.

No, TryAdd is quite different as I have described. 

As far as the breaking change, this is why I proposed the "new" C#8 feature of default interface method. But, yes, this is just an idea. 

Thank you.

**Comment by eiriktsarpalis** [comment]
Ah, I missed that you're proposing a method that only updates an entry provided that it already exists. As @theodorzoulias pointed out, you could solve this using one of the `CollectionsMarshal` methods.

> this is why I proposed the "new" C#8 feature of default interface method.

The risk of breaking change that the linked issue is describing is specifically about DIMs. Retroactively adding DIMs to shipped interfaces carry the risk of breaking downstream implementers.

**Comment by chr1st0scli** [comment]
> The risk of breaking change that the linked issue is describing is specifically about DIMs. Retroactively adding DIMs to shipped interfaces carry the risk of breaking downstream implementers.

Do you mean for example that an implementer might have already declared the exact same signature (declaration) as an extension method on that interface? Can you elaborate on that? I lost you a bit because other than that, I quote from the motivation section "_Default interface methods enable an API author to add methods to an interface in future versions without breaking source or binary compatibility with existing implementations of that interface._".
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/default-interface-methods

**Comment by eiriktsarpalis** [comment]
There exist corner cases where that statement does not hold. The issue I linked to contains a couple of reproductions that demonstrate this. That doesn't mean you can't use DIMs to achieve that goal in your code, however for very popular interfaces in the BCL there is a nonzero probability that somebody will be broken.
