### ISSUE TITLE
GetSystemTimeZones() returns incorrect StandardName etc.

### ISSUE THREAD

**Issue by montella1507** [dotnet/runtime#83924]
### Description

GetSystemTimeZones() returns incorrect StandardName etc. Atleast on MacOS.
For the instance:
`{(UTC+04:30) Afghanistan Time}
    BaseUtcOffset: {04:30:00}
    DaylightName: "GMT+04:30"
    DisplayName: "(UTC+04:30) Afghanistan Time"
    HasIanaId: true
    Id: "Asia/Kabul"
    StandardName: "Afghanistan Time"
    SupportsDaylightSavingTime: true
    _adjustmentRules: {System.TimeZoneInfo.AdjustmentRule[3]}
    _baseUtcOffset: {04:30:00}
    _daylightDisplayName: "GMT+04:30"
    _displayName: "(UTC+04:30) Afghanistan Time"
    _equivalentZones: null
    _id: "Asia/Kabul"
    _standardDisplayName: "Afghanistan Time"
    _supportsDaylightSavingTime: true
`

this should be "Afghanistan Standard Time" -  IANA Asia/Kabul

### Reproduction Steps

TimeZoneInfo.ClearCachedData();
TimeZoneInfo.GetSystemTimeZones()

### Expected behavior

Method should return correct information.

### Actual behavior

It returns incorrect data.

### Regression?

No.

### Configuration

MacOS M2 Air
Ventura 13.0.1

**Comment by montella1507** [comment]
Same for 50% of items.. Even the Europe/Prague is bad.

**Comment by tarekgh** [comment]
.NET don't carry the names, instead we pick the names from the underlying ICU library installed on the system (in this case is MacOS). 

https://github.com/dotnet/runtime/blob/3f5cb1805ea040e0869c1da8b8a7476a223ce4d2/src/native/libs/System.Globalization.Native/pal_timeZoneInfo.c#L77

Will be good logging issue to ICU as I am seeing using the name we returns 

https://github.com/unicode-org/icu/blob/2f8749a026f3ddc8cf54d4622480b7c543bb7fc0/icu4c/source/data/zone/en.txt#L59

**Comment by montella1507** [comment]
Hi, thanks for your response... 

Thanks god for IANA enums...
