### ISSUE TITLE
baseservices/threading/regressions/beta1/347011/347011.dll test failed

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#83929]
```
Assert.Equal() Failure
Expected: 100
Actual:   -5
```
https://dev.azure.com/dnceng-public/public/_build/results?buildId=217500&view=ms.vss-test-web.build-test-results-tab&runId=4064634&resultId=108726&paneView=debug

Looks like caused by https://github.com/dotnet/runtime/pull/83604 @tarekgh

**Comment by EgorBo** [comment]
I assume it was an intentional change to stop throwing ODE in `Timer.Change` as per https://github.com/dotnet/runtime/pull/83604#discussion_r1145599383
so presumably we only need to update this test?

**Comment by tarekgh** [comment]
> I assume it was an intentional change to stop throwing ODE in Timer.Change as per https://github.com/dotnet/runtime/pull/83604#discussion_r1145599383

Yes, this was an intentional change.
