### ISSUE TITLE
[Suggestion]: Replace usage of `ThrowHelper` methods for NullReference and OutOfRange Exceptions

### ISSUE THREAD

**Issue by jacobjmarks** [dotnet/runtime#83934]
# Context

Given the new(er) static helper methods for throwing common exception types introduced as part of [dotnet/runtime#48573](https://github.com/dotnet/runtime/issues/48573), I feel like the various `ThrowHelper` classes ([example](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq/src/System/Linq/ThrowHelper.cs)) used across the codebase &mdash; at least their [`ThrowArgumentNullException`](https://github.com/dotnet/runtime/blob/5d88ff404de77d78e07ad3de7fa2af270332da22/src/libraries/System.Linq/src/System/Linq/ThrowHelper.cs#L12) and [`ThrowArgumentOutOfRangeException`](https://github.com/dotnet/runtime/blob/5d88ff404de77d78e07ad3de7fa2af270332da22/src/libraries/System.Linq/src/System/Linq/ThrowHelper.cs#L15) methods &mdash; are somewhat obsolete and their usage could be replaced with the newer helper methods.

# Suggested Change

Replace occurrences of `ThrowHelper.ThrowArgumentNullException`

``` csharp
if (argument == null) // or `is null`
{
    ThrowHelper.ThrowArgumentNullException(ExceptionArgument.argument);
}
```

and `ThrowHelper.ThrowArgumentOutOfRangeException`

``` csharp
if (argument < 1) // example
{
    ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.argument);
}
```

With

``` csharp
ArgumentNullException.ThrowIfNull(argument);
```

and

``` csharp
ArgumentOutOfRangeException.ThrowIfLessThan(argument, 1); // or the respective appropriate method given the condition
```

respectively.

# Pros

- Less code to write and maintain; Removes:
  - `ThrowHelper.ThrowArgumentNullException(ExceptionArgument)`
  - `ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument)`
  - `ThrowHelper.GetArgumentString(ExceptionArgument)` ([example](https://github.com/dotnet/runtime/blob/5d88ff404de77d78e07ad3de7fa2af270332da22/src/libraries/System.Linq/src/System/Linq/ThrowHelper.cs#L32-L59))
  - `ThrowHelper.ExceptionArgument` enum ([example](https://github.com/dotnet/runtime/blob/5d88ff404de77d78e07ad3de7fa2af270332da22/src/libraries/System.Linq/src/System/Linq/ThrowHelper.cs#L62-L83))
- Much easier to throw exceptions for arguments which have not already been added to the respective `ExceptionArgument` enum.
  - No longer need to add the new argument name to the enum and the switch within the `GetArgumentString(ExceptionArgument)` method
- ~Reduced size of generated IL/asm code (inspected via `ildasm.exe`)~
  - Edit: Seems to be slightly worse under a Release build
- Better exception messages for `ArgumentOutOfRangeException` Exceptions

# Cons

- While it mightn't be enough to warrant arguments against the change, on paper it looks to perform slightly worse in certain cases (see below)
- Edit: Slight increase to IL/asm code for Release build (inspected via `ildasm.exe`)

# Benchmarks

<details>
<summary>See details</summary>

For completeness, transparency and consideration, I have run the following benchmarks to gauge the impact of the change.

I have tried to create as suitable benchmarks as possible.

<details>
<summary>View the benchmark code (122 lines)</summary>

``` csharp
[MemoryDiagnoser]
public class MyBenchmark
{
    // ArgumentNullException

    private const string? NonNullArgument = "";
    private const string? NullArgument = null;

    [Benchmark]
    public void ThrowHelper_ThrowArgumentNullException__Throws()
    {
        try
        {
            if (NullArgument == null)
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.argument);
        }
        catch { }
    }

    [Benchmark]
    public void ThrowHelper_ThrowArgumentNullException__DoesNotThrow()
    {
        try
        {
            if (NonNullArgument == null) { } // never true
        }
        catch { }
    }

    [Benchmark]
    public void ArgumentNullException_ThrowIfNull__Throws()
    {
        try
        {
            ArgumentNullException.ThrowIfNull(NullArgument);
        }
        catch { }
    }

    [Benchmark]
    public void ArgumentNullException_ThrowIfNull__DoesNotThrow()
    {
        try
        {
            ArgumentNullException.ThrowIfNull(NonNullArgument);
        }
        catch { }
    }

    // ArgumentOutOfRangeException

    private const int InRangeArgument = 0;
    private const int OutOfRangeArgument = -1;

    [Benchmark]
    public void ThrowHelper_ThrowArgumentOutOfRangeException__Throws()
    {
        try
        {
            if (OutOfRangeArgument < 0)
                ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.argument);
        }
        catch { }
    }

    [Benchmark]
    public void ThrowHelper_ThrowArgumentOutOfRangeException__DoesNotThrow()
    {
        try
        {
            if (InRangeArgument < 0) { } // never true
        }
        catch { }
    }

    [Benchmark]
    public void ArgumentOutOfRangeException_ThrowIfLessThan__Throws()
    {
        try
        {
            ArgumentOutOfRangeException.ThrowIfLessThan(OutOfRangeArgument, 0);
        }
        catch { }
    }

    [Benchmark]
    public void ArgumentOutOfRangeException_ThrowIfLessThan__DoesNotThrow()
    {
        try
        {
            ArgumentOutOfRangeException.ThrowIfLessThan(InRangeArgument, 0);
        }
        catch { }
    }
}

internal static class ThrowHelper
{
    [System.Diagnostics.CodeAnalysis.DoesNotReturn]
    internal static void ThrowArgumentNullException(ExceptionArgument argument)
        => throw new ArgumentNullException(GetArgumentString(argument));

    [System.Diagnostics.CodeAnalysis.DoesNotReturn]
    internal static void ThrowArgumentOutOfRangeException(ExceptionArgument argument)
        => throw new ArgumentOutOfRangeException(GetArgumentString(argument));

    private static string GetArgumentString(ExceptionArgument argument)
    {
        switch (argument)
        {
            case ExceptionArgument.argument: return nameof(ExceptionArgument.argument);
            default:
                System.Diagnostics.Debug.Fail("The ExceptionArgument value is not defined.");
                return string.Empty;
        }
    }
}

internal enum ExceptionArgument
{
    argument,
}
```

</details>

``` ini
BenchmarkDotNet=v0.13.5, OS=Windows 11 (10.0.22621.1413/22H2/2022Update/SunValley2)
AMD Ryzen 5 5600X, 1 CPU, 12 logical and 6 physical cores
.NET SDK=8.0.100-preview.2.23117.13
  [Host]     : .NET 8.0.0 (8.0.23.11601), X64 RyuJIT AVX2
  DefaultJob : .NET 8.0.0 (8.0.23.11601), X64 RyuJIT AVX2
```

**ArgumentNullException**

|                                                     Method |          Mean |      Error |     StdDev |   Gen0 | Allocated |
|----------------------------------------------------------- |--------------:|-----------:|-----------:|-------:|----------:|
|             ThrowHelper_ThrowArgumentNullException__Throws | 6,457.5011 ns | 41.8958 ns | 37.1396 ns | 0.0153 |     352 B |
|                  ArgumentNullException_ThrowIfNull__Throws | 6,592.7386 ns | 12.7112 ns | 10.6144 ns | 0.0153 |     352 B |
|       ThrowHelper_ThrowArgumentNullException__DoesNotThrow |     0.1129 ns |  0.0024 ns |  0.0019 ns |      - |         - |
|            ArgumentNullException_ThrowIfNull__DoesNotThrow |     0.1156 ns |  0.0080 ns |  0.0071 ns |      - |         - |

**ArgumentOutOfRangeException**

|                                                     Method |          Mean |      Error |     StdDev |   Gen0 | Allocated |
|----------------------------------------------------------- |--------------:|-----------:|-----------:|-------:|----------:|
|       ThrowHelper_ThrowArgumentOutOfRangeException__Throws | 6,405.1160 ns | 55.9590 ns | 52.3441 ns | 0.0153 |     360 B |
|        ArgumentOutOfRangeException_ThrowIfLessThan__Throws | 6,805.2519 ns | 52.0709 ns | 48.7072 ns | 0.0305 |     552 B |
| ThrowHelper_ThrowArgumentOutOfRangeException__DoesNotThrow |     0.1151 ns |  0.0047 ns |  0.0042 ns |      - |         - |
|  ArgumentOutOfRangeException_ThrowIfLessThan__DoesNotThrow |     0.2359 ns |  0.0053 ns |  0.0047 ns |      - |         - |

</details>

# Remarks

If discussions prove fruitful, I am more than happy to start submitting PRs with the relevant changes; I've got one for `System.Linq` [ready to go](https://github.com/dotnet/runtime/commit/ff80f281e2791ffb597f8f106d337a31173594e8).

**Comment by danmoseley** [comment]
This might not make sense in the hotter paths.

**Comment by jacobjmarks** [comment]
If we retain the conditional checks, and simply replace the `ThrowHelper` methods with simple `throw` statements\*, we see improved performance (_greater_ than that of the detriment observed when using the newer static methods):

> \* This does however cause `CA1510` analyser errors added as part of [dotnet/roslyn-analyzers#6293](https://github.com/dotnet/roslyn-analyzers/pull/6293)

i.e.

``` csharp
if (argument == null)
    ThrowHelper.ThrowArgumentNullException(ExceptionArgument.argument);

// vs

if (argument == null)
    throw new ArgumentNullException(nameof(argument));
```

|                                               Method |          Mean |      Error |     StdDev |   Gen0 | Allocated |
|----------------------------------------------------- |--------------:|-----------:|-----------:|-------:|----------:|
|       ThrowHelper_ThrowArgumentNullException__Throws | 6,418.5479 ns | 26.6016 ns | 24.8831 ns | 0.0153 |     352 B |
|                ThrowNewArgumentNullException__Throws | 5,653.9579 ns | 51.7546 ns | 48.4113 ns | 0.0076 |     232 B |
| ThrowHelper_ThrowArgumentOutOfRangeException__Throws | 6,412.4896 ns | 14.5111 ns | 12.8637 ns | 0.0153 |     360 B |
|          ThrowNewArgumentOutOfRangeException__Throws | 5,649.5179 ns | 21.1776 ns | 18.7734 ns | 0.0076 |     240 B |
|                                         DoesNotThrow |     0.1118 ns |  0.0006 ns |  0.0004 ns |      - |         - |

This approach, while not as nice as the newer static methods, retains the "short-circuit" nature of the existing conditional checks which are in place and performs better when an Exception does throw.

However, the following IL/asm code sizes were observed when switching a single statement in a method (`throw new` looks to cause a slight increase):

```
ThrowHelper: 143
ThrowIfNull: 135 (-8)
throw new:   145 (+2)
```

Speed vs Size 🤷

**Comment by jacobjmarks** [comment]
In addition, the new analysers added in [dotnet/roslyn-analyzers#6293](https://github.com/dotnet/roslyn-analyzers/pull/6293) state that "_Throw helpers_ [(refering to the newer static methods on the Exception classes, not the `ThrowHelper` classes)] _are simpler and more efficient than an if block constructing a new exception instance._"; However given the benchmarks I have run this doesn't seem to be the case?

**Comment by jkotas** [comment]
In general, we do not optimize for exception throwing speed. We are fine with exception to be slower.

We optimize for small code size and speed of non-throwing path.

**Comment by stephentoub** [comment]
> However given the benchmarks I have run this doesn't seem to be the case in terms of efficiency?

What benchmarks did you run? The numbers above suggest you're measuring a failure path, which as Jan says is not what we focus on (and even then the cited differences in the numbers look suspect). We care about the throughput on the success path, not on the throwing path where the actual exception mechanics outsize the other costs, and we care about the generated code size, in particular asm more than IL. For LINQ, for example, we utilize ThrowHelper to reduce asm size in these generic code paths where generic specialization can result in many copies of the highly used helpers.

**Comment by Clockwork-Muse** [comment]
> We are fine with exception to be slower.

Especially for these exceptions, which are intended to be non-recoverable (because the only thing you can do is have it be fixed by a programmer), and should end up crashing your program anyways.

**Comment by jacobjmarks** [comment]
Thanks for the clarifications folks; will close this off. Looks like the best solution is in place in terms of optimising for code size and non-failure path.

**Comment by jacobjmarks** [comment]
As an aside, what may be the best method of checking asm code size? I realise my current methods may be flawed.

**Comment by stephentoub** [comment]
> what may be the best method of checking asm code size?

If you're using benchmarkdotnet, you can use the [DisassemblyDiagnoser].

Otherwise, you can set the DOTNET_JitDisasm environment variable to have it dump out the assembly it generates (and size of that assembly).  Just keep in mind if you have tiering enabled (and it's enabled by default), you'll need to execute the relevant code enough to get the JIT to tier up the method so that it outputs the tier 1 code.
