### ISSUE TITLE
Quic exception in the guts of making an http request

### ISSUE THREAD

**Issue by jswigart** [dotnet/runtime#83932]
### Description

I have a game server that is using dotnet core 3.1, and I have recently begun building it for .net 7 to get away on a newer supported .net version. We are building this game server in self contained mode with a targeted runtime to make it completely self sufficient.

This server application is a console app, and one of the first things it does as part of starting up the server into the configured map is query mod.io for a template file to see if it needs to download the template file or whether the file hash matches the local file.

This fairly basic http query is failing seemingly within the code that is supposed to be checking whether QuicConnection IsSupported. Here is a callstack

```
BuildVerseServer.Server - DownloadTemplateFromModIO Exception
System.AggregateException: One or more errors occurred. (The type initializer for 'System.Net.Quic.MsQuicApi' threw an exception.)
 ---> System.TypeInitializationException: The type initializer for 'System.Net.Quic.MsQuicApi' threw an exception.
 ---> System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at System.Net.Quic.MsQuicApi.TryOpenMsQuic(QUIC_API_TABLE*& apiTable, Int32& openStatus)
   at System.Net.Quic.MsQuicApi..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Quic.QuicConnection.get_IsSupported()
   at System.Net.Http.HttpConnectionPool..ctor(HttpConnectionPoolManager poolManager, HttpConnectionKind kind, String host, Int32 port, String sslHostName, Uri proxyUri)
   at System.Net.Http.HttpConnectionPoolManager.SendAsyncCore(HttpRequestMessage request, Uri proxyUri, Boolean async, Boolean doRequestAuth, Boolean isProxyConnect, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPoolManager.SendAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Modio.Connection.Send[T](Request request) in C:\JenkinsHome\workspace\CreativerseStandalone\Server\Modio\Http\Connection.cs:line 41
   at Modio.SearchClient`1.ToPagedEnumerable()+MoveNext() in C:\JenkinsHome\workspace\CreativerseStandalone\Server\Modio\Clients\SearchClient.cs:line 90
   at Modio.SearchClient`1.ToPagedEnumerable()+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Modio.SearchClient`1.ToList() in C:\JenkinsHome\workspace\CreativerseStandalone\Server\Modio\Clients\SearchClient.cs:line 54
   at Modio.SearchClient`1.ToList() in C:\JenkinsHome\workspace\CreativerseStandalone\Server\Modio\Clients\SearchClient.cs:line 54
```

After some reading in several issues here on github. It seems that some of this Quic stuff or higher http versions that utilize it should be opt-in, and we aren't opting in, so I'm not sure why it is attempting to use/initialize Quic. In any case I thought it seemed suspect that the bowels of a completely optional component Quic could fail out of the entire attempt, rather than be caught and treated as non supported.

### Reproduction Steps

Reproduction is impractical to communicate, because this occurs in a highly specific circumstance of running the dedicated server app via steam on the steam deck handheld gaming device. What's more, is that this only occurs when running the server in this way. If we run the native linux version of the server via terminal on the steam deck, this issue does not occur. My guess is the presence of Quic support is being effected by the emulation layer that apps run on when launched via steam on the steam deck device.

### Expected behavior

I guess I would expect Quic support to report false and the app to continue without it, not fail with an exception all the way back up to user code.

### Actual behavior

Within the call context of System.Net.Quic.QuicConnection.get_IsSupported(), an uncaught exception causes the entire callstack to unwind back to user code and the http request to fail completely.

### Regression?

We are brand new at experimenting with running our game/server on the steam deck device. These issues are unique to running the application on top of the proton emulation layer, so while one may point to that as being the emulation layers problem, the nature of the failure to me suggests there is the possibility of a supposedly optional component(Quic) IsSupported function failing spectacularly and breaking the whole attempt.

### Known Workarounds

None

### Configuration

.net 7
steam OS

**Comment by jswigart** [comment]
Some more info, if I test with .net 6 I don't get this exception failure. So something appears to have changed between .net 6 and 7 that started using Quic, and the IsSupported check for Quic is bombing out the entire callstack rather than gracefully failing.

**Comment by rzikm** [comment]
>  ---> System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at System.Net.Quic.MsQuicApi.TryOpenMsQuic(QUIC_API_TABLE*& apiTable, Int32& openStatus)
   at System.Net.Quic.MsQuicApi..cctor()

This part is suspicious. Do you have `libmsquic` installed on your system? What is the version of the SteamOS you are using?

**Comment by jswigart** [comment]
libmsquic doesn't seem to be installed. isn't this an optional component?

we're also compiling self contained publish with target, with the expectation that it will bundle all it needs. gamers aren't always super tech savy, so we usually try to avoid making the game require manual package installation

<img width="673" alt="image" src="https://user-images.githubusercontent.com/4065267/227958974-53b45ceb-a174-4525-ab4f-92a533d44132.png">

![image](https://user-images.githubusercontent.com/4065267/227960569-1360f427-4eb5-448a-be27-5921160cb1ac.png)

**Comment by ManickaP** [comment]
Oh and what's in your self-contained bundle? By any chance, is there any file with msquic in its name?

**Comment by wfurt** [comment]
You can do 
`LD_DEBUG=libs ./myApp` 
That would show library loading and any bits not visible by the package manager.

**Comment by jswigart** [comment]
All 3 platforms are built from a windows jenkins build machine.

We are using nuke, but the actual build commands end up looking like this.

> "C:\Program Files\dotnet\dotnet.exe" publish ../Server/CreativerseServer.csproj --configuration Release --framework net6.0 --no-restore --output C:\JenkinsHome\workspace\CreativerseStandalone\Builds\Server\Steam\win-x64 --self-contained True --runtime win-x64
> "C:\Program Files\dotnet\dotnet.exe" publish ../Server/CreativerseServer.csproj --configuration Release --framework net6.0 --no-restore --output C:\JenkinsHome\workspace\CreativerseStandalone\Builds\Server\Steam\linux-x64 --self-contained True --runtime linux-x64
> "C:\Program Files\dotnet\dotnet.exe" publish ../Server/CreativerseServer.csproj --configuration Release --framework net6.0 --no-restore --output C:\JenkinsHome\workspace\CreativerseStandalone\Builds\Server\Steam\osx-x64 --self-contained True --runtime osx-x64

The only Quic file that ends in the self contained output is System.Net.Quic.dll, but here is a full dump of the files for the linux build

[linuxbuild.txt](https://github.com/dotnet/runtime/files/11081200/linuxbuild.txt)

**Comment by ManickaP** [comment]
You're commands show targeting net6.0 but the exception shows stack trace for .net 7.0 and newer. So is that a typo?

You should check for `msquic` not for `libmsquic` when looking for a package: https://aur.archlinux.org/packages/msquic. And apart from that, you can also try running `find /usr -name libmsquic*` or similar to check if the lib is not on the system via other means than package manager.

Also trying @wfurt suggestion with `LD_DEBUG` can lead to some clues.

**Comment by jswigart** [comment]
This issue is from .net 7 yes. We have rolled back our build to .net 6 which works better and doesn't have this issue. Seems that whatever it is, was introduced in 7. I pulled these command line logs after we downgraded.

I will get back to you when we have searched for those libraries as suggested. Thanks

**Comment by ManickaP** [comment]
I tested a simple .NET 7.0 program calling `HttpClient` on SteamOS VM and it runs without any issue  - `IsSupported` is false and client is able to retrieve a web page. There's no libmsquic on the system, it's a fresh VM from this image: https://store.steampowered.com/steamos/download?ver=steamdeck
