### ISSUE TITLE
Allow the timers created by TimeProvider to communicate if is resettable

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#83949]
This issue is to track address the [comment](https://github.com/dotnet/runtime/pull/83604#discussion_r1145601794)  on the [PR](https://github.com/dotnet/runtime/pull/83604).

TimeProvider allows creating a timer through the method [CreateTimer](https://github.com/dotnet/runtime/blob/922c75c837fc95092e1d9e433a087ac62082953d/src/libraries/Common/src/System/TimeProvider.cs#L137). The created timer can be used in various places like in `CancellationTokenSource` which support operations like [TryReset](https://github.com/dotnet/runtime/blob/922c75c837fc95092e1d9e433a087ac62082953d/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs#L471). Such operation is supported with the system timer only. This issue track looking at if we need to have such operations work with the custom timers too.

**Comment by tarekgh** [comment]
CC @stephentoub

**Comment by tarekgh** [comment]
https://github.com/dotnet/runtime/issues/36617

**Comment by stephentoub** [comment]
Right. We should double check, but I expect we could make this work if we add an `out bool idle` or something like that, which would be set to true iff both timeouts were infinite, the method returns true, _and_ the implementation guarantees that the timer will not fire unless subsequent changes are made, eg there's no pending work item already queued that will invoke the timer's callback.

**Comment by tarekgh** [comment]
We'll watch if we find there will be any demand to support this issue and then we can consider it. Maybe in the future we can expose `ITimer.MightHavePendingWork` and have the timers implement it properly which can be used to address this issue. Closing it for now.
