### ISSUE TITLE
Runtimes downloaded from Microsoft repos aren't detected by dotnet due to different installation directory

### ISSUE THREAD

**Issue by Kysawier** [dotnet/runtime#83950]
### Description

After following the installation instructions outlined in the Microsoft documentation (https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#register-the-microsoft-package-repository) for installing .NET/ASP.NET Core runtimes/SDKs on Linux Ubuntu, I noticed that .NET/ASP.NET Core runtimes for version 6 and 7 are installed in a different location. As a result, the dotnet application is unable to locate the .NET/ASP.NET Core 6 runtimes.

### Reproduction Steps

Following https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#register-the-microsoft-package-repository

### Expected behavior

dotnet-runtime-6.0 installed under /usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.13
and /usr/share/dotnet/shared/Microsoft.AspNetCore.App/6.0.13

### Actual behavior

dotnet-runtime-6.0 installed under /usr/lib/dotnet/shared/Microsoft.NETCore.App/6.0.13
and /usr/lib/dotnet/shared/Microsoft.AspNetCore.App/6.0.13

### Known Workarounds

Create symbolic links for the .NET and ASP.NET Core runtime 

```
sudo ln -s /usr/lib/dotnet/shared/Microsoft.NETCore.App/6.0.13/ /usr/share/dotnet/shared/Microsof
t.NETCore.App/6.0.13


sudo ln -s /usr/lib/dotnet/shared/Microsoft.AspNetCore.App/6.0.13/ /usr/share/dotnet/shared/Microsoft.AspNetCore.App/6.0.13
```

### Configuration

WSL2 Ubuntu 22.04.1 LTS

**Comment by NikolaMilosavljevic** [comment]
@Kysawier there are known issues with mixing packages from Microsoft and distro-specific repositories. Can you check if instructions outlined in the following issue are helpful? https://github.com/dotnet/core/issues/7699
