### ISSUE TITLE
Test merged baseservices/threading time out in gcstress

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#83961]
All recent gcstress runs have timeouts in the "threading" groups. For example:
https://dev.azure.com/dnceng-public/public/_build/results?buildId=217737&view=results

Likely these tests should be striped in the same manner as HardwareIntrinsics. cc @trylek

**Comment by JulieLeeMSFT** [comment]
Failing gcstress-extra pipeline as well: https://dev.azure.com/dnceng-public/public/_build?definitionId=113

**Comment by markples** [comment]
This does not appear to be a need for test striping, though it might get there when all tests are running.

baseservices\threading\regressions\30032\30032.cs behaves differently under merged groups, and I'm not sure why - even when it is the first test in the list.  Every time I've managed to break in with a debugger, it's sitting in WaitForPendingFinalizers (which the test calls), but the debugger is also having a lot of trouble doing anything when this test is running so I don't have a lot of information yet.

I will check if RequiresProcessIsolation in a merged group is sufficient to at least unblock things.

**Comment by trylek** [comment]
I recall that last year in my work on test merging I was hitting GC stress issues in tests that were somehow explicitly tampering with finalization. The working theory at that time was that this is possibly a bug in the GC stress implementation itself in the sense that by injecting the various extra GC calls into execution we can end up with a form of starvation where the finalization queue is getting filled in faster than it's pumped, causing exactly the type of hang you've described. IIRC the consensus at that time was to mark such tests as requiring out-of-proc execution because this behavior doesn't constitute an obvious product bug (in view of the fact that GC stress testing creates an artificial environment for the test) and is possibly hard to fix. I think this is one of the issue threads where we discussed this behavior:

https://github.com/dotnet/runtime/issues/68529

**Comment by markples** [comment]
This may be more widespread.  @BruceForstall proactively [ran gcstress after JIT\Regression](https://dev.azure.com/dnceng-public/public/_build/results?buildId=224309&view=ms.vss-test-web.build-test-results-tab&runId=4215414&resultId=302275&paneView=debug) and more groups failed.  Regression_1 and _2 both have some tests with WaitForPendingFinalizers in it, so I'm starting by marking them RequiresProcessIsolation.  Regression_4 does not, but it did run for 2 hours (of the 4) before getting stuck on a test.  The tests seem to slow down over time - I don't know if that's intrinsic to the tests or if GCStress degrades over time.  I will try striping there.

**Comment by markples** [comment]
Fixed #84193

**Comment by JulieLeeMSFT** [comment]
@markples, PTAL. There is still timeout in [gcstress0x3-gcstress0xc pipeline](https://dev.azure.com/dnceng-public/public/_build?definitionId=112&_a=summary)

Test: https://dev.azure.com/dnceng-public/public/_build/results?buildId=225615&view=ms.vss-test-web.build-test-results-tab&runId=4240042&resultId=122588&paneView=debug

tracing/eventpipe/enabledisable/enabledisable/enabledisable.sh

cmdLine:/root/helix/work/workitem/e/tracing/eventpipe/enabledisable/enabledisable/enabledisable.sh Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 4/2/2023 4:19:28 PM, end: 4/2/2023 5:19:28 PM)

Return code:      -100
Raw output file:      /root/helix/work/workitem/uploads/Reports/tracing.eventpipe/enabledisable/enabledisable/enabledisable.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false enabledisable.dll ''

cmdLine:/root/helix/work/workitem/e/tracing/eventpipe/enabledisable/enabledisable/enabledisable.sh Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 4/2/2023 4:19:28 PM, end: 4/2/2023 5:19:28 PM)
Printing stacktrace from '/home/helixbot/dotnetbuild/dumps/crashdump_4621.dmp.crashreport.json'
Test Harness Exitcode is : -100
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/e/tracing/eventpipe/enabledisable/enabledisable/enabledisable.sh
Expected: True
Actual:   False

**Comment by markples** [comment]
enabledisable isn't in baseservices/threading.  This failure is #83359
