### ISSUE TITLE
net7/net8 run on arm9 or arm11

### ISSUE THREAD

**Issue by cuican6** [dotnet/runtime#83975]
net7 or net8 can run with arm9 or arm11?

**Comment by hopperpl** [comment]
Both are about the very old ARM processors, pre-year 2000 and around early 2000. The ARM9 is ARMv4/v5 instruction set and the ARM11 is ARMv6, all 32-bit architectures.

Based on the lack of essential CPU features like division and (fast) multiplication and others, I would say both processors are not supported and will never be.

I may get corrected on this one, but net7/net8 are way too heavy for these small processors.

**Comment by alexrp** [comment]
I believe CoreCLR can kinda-sorta run on ARMv6, but there's going to be [some DIY around building](https://github.com/dotnet/runtime/issues/7764#issuecomment-1043468998). Mono definitely can.

*Technically* there's nothing preventing a port of CoreCLR or Mono to ARMv4-5. But it's not going to work out of the box, and I somewhat doubt that there's interest in taking patches for this in upstream .NET, considering [even ARMv6-7 is on the chopping block](https://github.com/dotnet/runtime/discussions/71042).

I will say that for Mono, the oldest ARM we've successfully run it on is ARMv5, and even that has been painful over the years. IIRC one of the pain points was missing instructions related to atomics and memory barriers. I would generally advise people to stay far away from anything older than ARMv7 if at all possible.
