### ISSUE TITLE
About. net6 executable files on window os

### ISSUE THREAD

**Issue by daodol** [dotnet/runtime#83977]
Hi, I am considering using C++to load the. net6 self contained executable file into memory and then execute it in memory. I looked at the PE structure of this executable file, but I don't know how to call it. The exported function address table contains CLRJitAttachState, DotNetRuntimeInfo, MetaDataGetDispenser, and g_ CLREngineMetrics.
I haven't found any relevant information, and I hope to get help.thanks

**Comment by daodol** [comment]
hello？

**Comment by vitek-karas** [comment]
Is the self-contained executable single-file or not?
If it's not a single file, then you should be able to use native hosting APIs to run the app. https://learn.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting
To run an app you would need to call `hostfxr_initialize_for_dotnet_command_line` and then `hostfxr_run_app` - these APIs are described here: https://github.com/dotnet/runtime/blob/main/docs/design/features/native-hosting.md

If it's a single-file application, then there's currently no hosting story for it. You could try to run the executable as any other native executable (find the native entry point address and so on), but there are no guarantees that it will work. The executable is not built specifically to support getting loaded into another process, it's designed to be started as a process on its own.

**Comment by daodol** [comment]
> Is the self-contained executable single-file or not? If it's not a single file, then you should be able to use native hosting APIs to run the app. https://learn.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting To run an app you would need to call `hostfxr_initialize_for_dotnet_command_line` and then `hostfxr_run_app` - these APIs are described here: https://github.com/dotnet/runtime/blob/main/docs/design/features/native-hosting.md
> 
> If it's a single-file application, then there's currently no hosting story for it. You could try to run the executable as any other native executable (find the native entry point address and so on), but there are no guarantees that it will work. The executable is not built specifically to support getting loaded into another process, it's designed to be started as a process on its own.
On the. NET platform, code is easily decompiled, even if code obfuscation tools are used. I want to use C++to run programs in memory, so that I can encrypt. NET programs through compression tools, making decompilation more difficult

**Comment by daodol** [comment]
> Is the self-contained executable single-file or not? If it's not a single file, then you should be able to use native hosting APIs to run the app. https://learn.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting To run an app you would need to call `hostfxr_initialize_for_dotnet_command_line` and then `hostfxr_run_app` - these APIs are described here: https://github.com/dotnet/runtime/blob/main/docs/design/features/native-hosting.md
> 
> If it's a single-file application, then there's currently no hosting story for it. You could try to run the executable as any other native executable (find the native entry point address and so on), but there are no guarantees that it will work. The executable is not built specifically to support getting loaded into another process, it's designed to be started as a process on its own.

On the. NET platform, code is easily decompiled, even if code obfuscation tools are used. I want to use C++to run programs in memory, so that I can encrypt. NET programs through compression tools, making decompilation more difficult

**Comment by Clockwork-Muse** [comment]
> On the. NET platform, code is easily decompiled, even if code obfuscation tools are used. I want to use C++to run programs in memory, so that I can encrypt. NET programs through compression tools, making decompilation more difficult

If your "attackers" are sufficiently motivated and experienced, this isn't even going to slow them down.  Assuming you decrypt the entire executable at once, the memory can just be trivially dumped at that point (and if you have the decryption key in the C++ binary, you don't even need to run it).  I would be not-at-all surprised if there were automated tools to do this.

Also: 
>  so that I can encrypt. NET programs through compression tools

If this isn't a typo, I'm not reassured...

**Comment by daodol** [comment]
> 



> > 在。NET平台，即使使用代码混淆工具，代码也很容易反编译。我想使用 C++ 在内存中运行程序，以便我可以加密。通过压缩工具的NET程序，使反编译更加困难
> 
> 如果你的“攻击者”有足够的动机和经验，这甚至不会减慢他们的速度。假设您一次解密了整个可执行文件，那么此时可以简单地转储内存（如果您在C++二进制文件中具有解密密钥，则甚至不需要运行它）。如果有自动化工具可以做到这一点，我一点也不会感到惊讶。
> 
> 也：
> 
> > 以便我可以加密。通过压缩工具的 NET 程序
> 
> 如果这不是错别字，我不放心...

Yes, this only increases the difficulty of decompiling the source code

> > On the. NET platform, code is easily decompiled, even if code obfuscation tools are used. I want to use C++to run programs in memory, so that I can encrypt. NET programs through compression tools, making decompilation more difficult
> 
> If your "attackers" are sufficiently motivated and experienced, this isn't even going to slow them down. Assuming you decrypt the entire executable at once, the memory can just be trivially dumped at that point (and if you have the decryption key in the C++ binary, you don't even need to run it). I would be not-at-all surprised if there were automated tools to do this.
> 
> Also:
> 
> > so that I can encrypt. NET programs through compression tools
> 
> If this isn't a typo, I'm not reassured...

Yes, this only increases the difficulty of decompiling the source code.This is enough, and it is more difficult than directly decompiling. net programs

**Comment by daodol** [comment]
> > On the. NET platform, code is easily decompiled, even if code obfuscation tools are used. I want to use C++to run programs in memory, so that I can encrypt. NET programs through compression tools, making decompilation more difficult
> 
> If your "attackers" are sufficiently motivated and experienced, this isn't even going to slow them down. Assuming you decrypt the entire executable at once, the memory can just be trivially dumped at that point (and if you have the decryption key in the C++ binary, you don't even need to run it). I would be not-at-all surprised if there were automated tools to do this.
> 
> Also:
> 
> > so that I can encrypt. NET programs through compression tools
> 
> If this isn't a typo, I'm not reassured...

Yes, this only increases the difficulty of decompiling the source code.This is enough, and it is more difficult than directly decompiling. net programs.

**Comment by daodol** [comment]
> > On the. NET platform, code is easily decompiled, even if code obfuscation tools are used. I want to use C++to run programs in memory, so that I can encrypt. NET programs through compression tools, making decompilation more difficult
> 
> If your "attackers" are sufficiently motivated and experienced, this isn't even going to slow them down. Assuming you decrypt the entire executable at once, the memory can just be trivially dumped at that point (and if you have the decryption key in the C++ binary, you don't even need to run it). I would be not-at-all surprised if there were automated tools to do this.
> 
> Also:
> 
> > so that I can encrypt. NET programs through compression tools
> 
> If this isn't a typo, I'm not reassured...

It is possible to partition and compress self contained. net executable files through encryption. Then the C++initiator reads different memory blocks and merges them into PE format for execution. You can even modify specific areas of the. NET executable file, load it into memory, and replace it

**Comment by vitek-karas** [comment]
Have you considered NativeAOT instead? It's still obviously easily reverse engineered (just like any other compiled code), but the final binary behaves more like compiled C++ than pure IL.

**Comment by agocke** [comment]
Closing this as [Native AOT](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/) is our story for compiling C# to native code. Single-file is not intended to support that scenario
