### ISSUE TITLE
Determine behavior for GeneratedComClass on a type with no GeneratedComInterface interfaces

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#84032]
Do we want to warn / bail if there are no interfaces with `GeneratedComInterface` on a `GeneratedComClass` type?

_Originally posted by @elinor-fung in https://github.com/dotnet/runtime/pull/83755#discussion_r1149754455_

**Comment by AaronRobinsonMSFT** [comment]
Since the primary focus for the COM source generator in .NET 8 is for our first party teams, we can go with the yes and then relax it in the future if needed.

**Comment by jkoritzinsky** [comment]
Completed with #87436
