### ISSUE TITLE
VersionConverter throws NullReferenceException if Version is null

### ISSUE THREAD

**Issue by osexpert** [dotnet/runtime#84037]
### Description

VersionConverter throws NullReferenceException if Version is null
Can easily be seen in the code why it crashes, there is not check for null:
dotnet/runtime/blob/main/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Value/VersionConverter.cs

Here is a converter that correctly checks for null:
dotnet/runtime/blob/main/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Value/ByteArrayConverter.cs

### Reproduction Steps

With System.Text.Json, try to serialize a class that contain a Version that is null.
It will crash with NullReferenceException in net6. But the code here looks like it still does not check for null.

### Expected behavior

It should not crash.

### Actual behavior

throws NullReferenceException

### Regression?

No, I don't think it has ever worked

### Known Workarounds

        public class FixedVersionConverter : JsonConverter<Version>
	{
		private readonly static JsonConverter<Version> s_defaultConverter =
			(JsonConverter<Version>)JsonSerializerOptions.Default.GetConverter(typeof(Version));

                public override Version Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
		{
			if (reader.TokenType == JsonTokenType.Null)
				return null;

			return s_defaultConverter.Read(ref reader, typeToConvert, options);
		}

		public override void Write(Utf8JsonWriter writer, Version value, JsonSerializerOptions options)
		{
			if (value == null)
				writer.WriteNullValue();
			else
				s_defaultConverter.Write(writer, value, options);
		}
	}

**Comment by osexpert** [comment]
But now I have second thoughts. I use https://github.com/arogozine/TupleAsJsonArray and wonder if this may have something to do with it...
The FixedVersionConverter does remove the crash, but maybe it should not have crashed to begin with. Even so, why do ByteArrayConverter handle null while VersionConverter (and UriConverter) does not. I am confused.

**Comment by osexpert** [comment]
Seems https://github.com/arogozine/TupleAsJsonArray uses converters directly and cause the problem:
This give NullReferenceException:
```
			JsonSerializerOptions options = new JsonSerializerOptions();
			JsonConverter<Version> jsonConverter = (JsonConverter<Version>)options.GetConverter(typeof(Version));
			Version v = null;
			jsonConverter.Write(new Utf8JsonWriter(new MemoryStream()), v, options);
```

This works:
```
			JsonSerializerOptions options = new JsonSerializerOptions();
			Version v = null;
			JsonSerializer.Serialize(new MemoryStream(), v, options);
```

So it seems the converters are not safe to use directly as they don't directly allow\handle null (except for the odd ByteArrayConverter). So I guess this is not a bug then...just a IMO very easy to use wrong design:-)

**Comment by eiriktsarpalis** [comment]
> So it seems the converters are not safe to use directly as they don't directly allow\handle null (except for the odd ByteArrayConverter). So I guess this is not a bug then...just a IMO very easy to use wrong design:-)

That's right, `null` values are typically controlled by the serializer and not the built-in converters, unless the [`HandleNull` ](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonconverter-1.handlenull?view=net-7.0) property has been overridden to return `true`.
