### ISSUE TITLE
`System.Action` assignable to `System.Action<>`

### ISSUE THREAD

**Issue by timcassell** [dotnet/runtime#84061]
I'm not sure if this is at all feasible, but it would be great if I could assign an `Action` to an `Action<T>`. It would essentially ignore the parameter that's passed to it when it's invoked. Today, doing this requires 2 allocations, 1 for the closure, and another for the new delegate, and adds an extra indirection cost to the invocation.

```cs
public static Action<T> Convert<T>(Action action)
{
    return _ => action(); // 2 allocations, plus an extra indirection!
}
```
Ideally, that could just be this:
```cs
public static Action<T> Convert<T>(Action action) => action;
```

This would be beneficial for the case of creating awaiters for async objects that you don't own.

```cs
public readonly struct AsyncOperationAwaiter : ICriticalNotifyCompletion
{
    private readonly UnityEngine.AsyncOperation _asyncOperation;

    public AsyncOperationAwaiter(UnityEngine.AsyncOperation asyncOperation) => _asyncOperation = asyncOperation;
    public bool IsCompleted => _asyncOperation.isDone;
    public AsyncOperationAwaiter GetAwaiter() => this;
    public void GetResult() { }
    public void UnsafeOnCompleted(Action continuation) => OnCompleted(continuation);

    public void OnCompleted(Action continuation)
    {
        // Would like to do this, but it is an illegal append. completed type is `Action<UnityEngine.AsyncOperation>`.
        // _asyncOperation.completed += continuation;

        // Forced to wrap the continuation in a new delegate.
        _asyncOperation.completed += _ => continuation();
    }
}

public static AsyncOperationAwaiter GetAwaiter(this UnityEngine.AsyncOperation asyncOperation)
    => new AsyncOperationAwaiter(asyncOperation);
```

If it's impossible to make directly assignable, perhaps the next best thing would be a function that could convert the delegate type to the target type using only a single allocation and no extra indirection. Is that possible?

**Comment by huoyaoyuan** [comment]
With delegate variance, `Action<object>` is assignable to `Action<T>` if `T` is a reference type, and there's no additional overhead.

**Comment by timcassell** [comment]
> With delegate variance, `Action<object>` is assignable to `Action<T>` if `T` is a reference type, and there's no additional overhead.

I'm talking about `Action`, not `Action<object>`.

**Comment by huoyaoyuan** [comment]
An `Action` will not be compatible with `Action<T>` without someone fulfills the incompatibility of native calling convention. If `T` is passed on stack and cleaned by callee, there must be additional code cleaning up the stack, which is similar to the manual `Convert` function.

**Comment by timcassell** [comment]
@DaZombieKiller That's pretty clever, I had no idea extensions as delegates were optimized that way!

**Comment by tannergooding** [comment]
The workaround given above is likely the best thing to do today.

Having some system that allows ignoring parameters would likely require changes to the language and/or runtime to make it work as expected and would need to be part of a broader design.
