### ISSUE TITLE
Running .NET 6 single file binary with enabled compression on Apple M1 chip causes app to be "killed"

### ISSUE THREAD

**Issue by daniilshipilin** [dotnet/runtime#84066]
### Description

Already discussed in [#79267](https://github.com/dotnet/runtime/issues/79267)
And solved in this .NET 7 branch PL [#80283](https://github.com/dotnet/runtime/pull/80283)

This problem persists in latest .NET 6 sdk (used 6.0.15 release). The fix made in main dotnet branch should also be backported for this LTS release.

### Reproduction Steps

Publish command:
`dotnet publish MyProject.csproj -c Release -r osx-arm64 -o publish`

MyProject.csproj contents:
`<Project Sdk="Microsoft.NET.Sdk">`
`    <PropertyGroup>`
`        <OutputType>Exe</OutputType>`
`        <TargetFramework>net6.0</TargetFramework>`
`        <LangVersion>latest</LangVersion>`
`        <RuntimeFrameworkVersion>6.0.15</RuntimeFrameworkVersion>`
`        <RuntimeIdentifiers>osx-arm64</RuntimeIdentifiers>`
`        <PublishSingleFile>true</PublishSingleFile>`
`        <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>`
`        <SelfContained>true</SelfContained>`
`    </PropertyGroup>`
`</Project>`

### Expected behavior

The compressed single file executable should work on latest MacOS v13.2.1.

### Actual behavior

App exits with `zsh: bus error` msg in console.

Some info extracted from MacOS troubleshoot log file (.ips):
`"exception" : {"codes":"0x0000000000000002, 0x00000001243053f0","rawCodes":[2,4902114288],"type":"EXC_BAD_ACCESS","signal":"SIGBUS","subtype":"KERN_PROTECTION_FAILURE at 0x00000001243053f0"},`

### Known Workarounds

Setting `EnableCompressionInSingleFile` option to false.

### Configuration

Mac Mini M1
ProductName: macOS
ProductVersion: 13.2.1
BuildVersion: 22D68

Darwin Mac-mini.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103 arm64

**Comment by daniilshipilin** [comment]
It's not codesigning related. I'm using local adhoc codesign method by
initiating manual command after each build: codesign -s - MyApp
The problem is gone after disabling compression.

**Comment by vitek-karas** [comment]
@vsadov could you please take a quick look (try to repro and where it fails if it does)?

**Comment by daniilshipilin** [comment]
Any updates on this one?

**Comment by VSadov** [comment]
It looks like it is the same issue as fixed in https://github.com/dotnet/runtime/pull/80283, just in 6.0. 

It would need a similar fix.  The code changed substantially between 6.0 and 7.0. There was a lot of cleanup in 7.0. The fix cannot be ported trivially. 
I will try reimplementing the same fix in the context of 6.0 and see if that fixes the issue.

**Comment by agocke** [comment]
As .NET 8 is out and .NET 6 is approaching end-of-life, I will close this as not planned for .NET 6, with the recommendation to use .NET 8 instead.
