### ISSUE TITLE
Add event log for `System.Threading.Tasks.Task.CancellationPromise` as is done in `DelayPromise`

### ISSUE THREAD

**Issue by cretz** [dotnet/runtime#84081]
### Description

https://github.com/dotnet/runtime/blob/dddf223348481d2e52e709c555f907adfae8a96d/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs#L5663-L5664 is present to let event log know when `Task.Delay` is called, but there is nothing for knowing when `Task.WaitAsync` (and friends) is called. An event log for `CancellationPromise` should be present the same way it is for `DelayPromise`.

The use case is to see to be able to see where timers are created in async code.

**Comment by stephentoub** [comment]
DelayPromise is kicking off its own asynchronous operation, which is why it's doing that logging. WaitAsync isn't; it's effectively just tacking on to an existing one.  Can you elaborate on why it would benefit from having such additional tracing and what you'd do with it?

**Comment by stephentoub** [comment]
> The use case is to see to be able to see where timers are created in async code.

Can you use the new TimeProvider for that?  It lets you hook CreateTimer, and there are overload of both Delay and WaitAsync that accept a TimeProvider.

**Comment by cretz** [comment]
I will definitely be leveraging the new time provider (I added my use case to https://github.com/dotnet/runtime/issues/36617#issuecomment-1489009132). But I figured for consistency/symmetry, one should be able to get an event log on `Task.Delay` or `Task.WaitAsync` instead of just the former.

**Comment by ericstj** [comment]
I think @stephentoub was mentioning that he actually saw Delay and WaitAsync differently so they might not necessarily need to be consistent.  FWIW I looked at the history of this event and it seems like it was added to serve as the async causality feature work -- probably that added only the events needed for that feature to work.

**Comment by cretz** [comment]
:+1: If it doesn't need to be consistent, no problem. Just a consistency hole I spotted when building my own tool that looks at these events.
