### ISSUE TITLE
[API Proposal]: Add API to detect Binary Format (MS-NRBF) header

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/runtime#84090]
### Background and motivation

With `BinaryFormatter` depreciation transitioning off of usages requires looking at incoming data to see if it is valid [Binary Format](https://learn.microsoft.com/openspecs/windows_protocols/ms-nrbf/75b9fe09-be15-475f-85b8-ae7b7558cfe5) data. Knowing that it is allows fallback logic to be implemented.

Knowing this also is potentially useful for other filtering of incoming binary streams.

We're seeing numerous places where we need this in the WinForms stack and expect that our customers will need the same.

### API Proposal

```csharp
namespace System.Runtime.Serialization.Formatters.Binary;

public sealed class BinaryFormatter : IFormatter
{
    public static bool HasValidBinaryFormatHeader(ReadOnlySpan<byte> data);
    public static bool HasValidBinaryFormatHeader(byte[] data);

    // Stream overload possible? Not all streams are seekable...
}
```

### API Usage

```csharp
void ProcessClipboardCsvData(ReadOnlySpan<byte> data)
{
    if (BinaryFormatter.HasValidBinaryFormatHeader(data))
    {
        // Handle legacy data
        return;
    }

    // Simple character stream, create string...
}
```

### Alternative Designs

Could potentially invert the logic as it is remotely possible to match a non binary formatted stream. E.g. `DoesNotHaveValid...`.

### Risks

No specific known risks.

**Comment by GrabYourPitchforks** [comment]
Seems reasonable to me. One issue with having a `Stream` overload is that, as you said, not all streams are seekable. So if we did want a Stream overload it would have to be something like:

```cs
if (!stream.CanSeek) { threw new Exception(/* ... */); }
long pos = stream.Position;
byte[] bytes = stream.Read17Bytes();
stream.Position = pos; // reset position
return HasValidHeader(bytes);
```

This isn't entirely unreasonable IMO, especially since most folks will probably just pass in a seekable `MemoryStream` or a `FileStream`.

**Comment by adamsitnik** [comment]
Fixed with https://github.com/dotnet/runtime/pull/103232

the new API is `NrbfDecoder.NrbfDecoder` there is one overload that accepts a byte array and another that accepts a `Stream`
