### ISSUE TITLE
Failure in System.Tests.TimeZoneInfoTests.Platform_TimeZoneNames(tzi: (UTC+03:30) Iran Standard Time 

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#84130]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=220373
Build error leg or test failing: System.Tests.TimeZoneInfoTests.Platform_TimeZoneNames
Pull request: https://github.com/dotnet/runtime/pull/83462

Maybe a change in ICU behavior?

```
;; System.Tests.TimeZoneInfoTests.Platform_TimeZoneNames(tzi: (UTC+03:30) Iran Standard Time 

Assert.Equal() Failure
↓ (pos 31)
Expected: ···: "(UTC+03:30) Iran Time", StandardName: Iran Standard Time",···
Actual:   ···: "(UTC+03:30) Iran Standard Time (Tehran)", StandardName: Ir···
↑ (pos 31)
```

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Actual:   ···: \"(UTC+03:30) Iran Standard Time (Tehran)\"",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[222638](https://dev.azure.com/dnceng-public/public/_build/results?buildId=222638)|dotnet/runtime|[System.Tests.TimeZoneInfoTests.Platform_TimeZoneNames](https://dev.azure.com/dnceng-public/public/_build/results?buildId=222638&view=ms.vss-test-web.build-test-results-tab&runId=4180580&resultId=191783)|dotnet/runtime#84123|
|[222146](https://dev.azure.com/dnceng-public/public/_build/results?buildId=222146)|dotnet/runtime|[System.Tests.TimeZoneInfoTests.Platform_TimeZoneNames](https://dev.azure.com/dnceng-public/public/_build/results?buildId=222146&view=ms.vss-test-web.build-test-results-tab&runId=4167658&resultId=190456)|dotnet/runtime#83829|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|2|2|2|

**Comment by AndyAyersMS** [comment]
Also seen in #84123

**Comment by tarekgh** [comment]
This should be fixed by https://github.com/dotnet/runtime/pull/84056

CC @carlosalberto
