### ISSUE TITLE
Подробное решение проблемы Запуск программы невозможен так как на компьютере отсутствует api-ms-win-crt-runtime-l1-1-0.dll описано тут [https://it-men.su/windows-error/api-ms-win-crt-runtime-l1-1-0.dll](https://it-men.su/windows-error/api-ms-win-crt-runtime-l1-1-0.dll)

### ISSUE THREAD

**Issue by veselov4nton** [dotnet/runtime#84131]
Подробное решение проблемы Запуск программы невозможен так как на компьютере отсутствует api-ms-win-crt-runtime-l1-1-0.dll описано тут [https://itmen.help/blog/api-ms-win-crt-runtime-l1-1-0.html](https://itmen.help/blog/api-ms-win-crt-runtime-l1-1-0.html)

_Originally posted by @veselov4nton in https://github.com/dotnet/runtime/issues/2917#issuecomment-597279367_

**Comment by NikolaMilosavljevic** [comment]
No replies from OP.
