### ISSUE TITLE
Unable to use hosting APIs to load managed assemblies from an ICorProfilerCallback implementation

### ISSUE THREAD

**Issue by jander-msft** [dotnet/runtime#84143]
## Problem

Anything that isn't the host doesn't seem to be able to use the hosting APIs in order to, for example, load a managed assembly and get a function pointer as a callback. The `hostfxr_handle` required by many of the hosting APIs is not accessible by anything other than the host itself. The removal of `GetCLRRuntimeHost` will cause a loss of this functionality if the hosting APIs (or some downstream layer) do not provide some way to access the handle.

## Background

The dotnet-monitor tool uses an ICorProfilerCallback implementation in order to augment the diagnostic capabilities of the runtime. We plan to use this profiler to also load a managed assembly into the process in the case where the profiler was loaded via attach. This requires some type of API to allow the profiler to load the managed assembly and get a function callback for some function within the assembly. This can currently be done by getting the `GetCLRRuntimeHost` function and invoking it to get the `ICLRRuntimeHost*` implementation.

However, #52688 expresses a desire to remove the `GetCLRRuntimeHost` function. The alternative seems to be to use the hosting APIs to perform similar functionality via [hostfxr_get_runtime_delegate](https://github.com/dotnet/runtime/blob/main/docs/design/features/native-hosting.md#getting-a-delegate-for-runtime-functionality).

The pitfall with this function and the related hosting API functions is that it assumes that the caller has access to a `hostfxr_handle` instance. However, it seems that only the host has access to this from calling one of the `hostfxr_initialize_for_*` methods. A ICorProfilerCallback implementation, or anything else loaded into the process, is not the one that initializes the runtime, so it doesn't have access to the handle instance. As noted it #83756, invoking `hostfxr_get_runtime_delegate` without a handle will return `InvalidArgFailure (0x80008081)`.

## Possible Solutions

1. Add some way of accessing "only" (or first?) `hostfxr_handle` for the dotnet application. I believe the vast majority of dotnet executables are running a single dotnet runtime; registering and providing the single (first?) loaded `hostfxr_handle` would be convenient for others in the application to use the hosting APIs.
2. (A more scoped solution) Add a new method to a `ICorProfilerInfo*` interface that allows getting the `hostfxr_handle` for the instance of the runtime that the `ICorProfilerCallback` is attached.

cc @dotnet/dotnet-monitor, @dotnet/dotnet-diag

**Comment by noahfalk** [comment]
@davmason

**Comment by vitek-karas** [comment]
I think it would make sense to allow calling `hostfxr_get_runtime_delegate` with `nullptr` context. Similar to `hostfxr_get_runtime_property_value` which already allows this.

The effect is that it finds the running runtime and acts on it. It will fail if there's no active runtime.

I don't think we need a way to get the handle for the running runtime - that would cause potential issues if another component got it and called close on it (or we would have to start to do ref counting). And we've already ran into this with the property values and solved it by allowing `NULL` - meaning "active".

We also don't want to allow just any action on the "active" context, since that would cause problems. For example we don't want `hostfxr_run_app` to be possible on `NULL` context.

@elinor-fung for ideas/opinions.

Note that I don't know what this will do with regard to the profiling APIs - not sure what is the interaction between assembly loading and profiling APIs and if it might cause reentrancy problems somewhere.

One possible issue (again don't know if it's actually real) - the hosting APIs assume that there's no way from inside `coreclr_initialize` will get back to the host before APIs (nothing will call hostfxr APIs). The host actively waits for the `coreclr_initialize` to return and until that happens the `NULL` context trick will not work (as the active context is still considered not fully initialized). So if the profiler callback happens during `coreclr_initialize` it would get errors from the hostfxr APIs.

This can be tried today - just call `hostfxr_get_runtime_property_value` with `NULL` context - if it works, then this idea should also work.

**Comment by elinor-fung** [comment]
> I think it would make sense to allow calling hostfxr_get_runtime_delegate with nullptr context. Similar to hostfxr_get_runtime_property_value which already allows this.
>
> I don't think we need a way to get the handle for the running runtime - that would cause potential issues if another component got it and called close on it (or we would have to start to do ref counting).

+1

> One possible issue (again don't know if it's actually real) - the hosting APIs assume that there's no way from inside coreclr_initialize will get back to the host before APIs (nothing will call hostfxr APIs). 

Definitely real. @jander-msft had tried out `hostfxr_get_runtime_property_value` during startup suspension and we crash because we try to take a lock recursively (but the original lock in non-recursive). We could avoid the crash, we'd then return an error about not being initialized. I don't know how much we could do here (aside from not crash so that it actually returns an error). The only action that could technically be valid at that point is getting a property value, since those were computed on the host side and doesn't depend on the runtime being initialized.

**Comment by jander-msft** [comment]
> > I think it would make sense to allow calling hostfxr_get_runtime_delegate with nullptr context. Similar to hostfxr_get_runtime_property_value which already allows this.
> > I don't think we need a way to get the handle for the running runtime - that would cause potential issues if another component got it and called close on it (or we would have to start to do ref counting).
> 
> +1
> 
> > One possible issue (again don't know if it's actually real) - the hosting APIs assume that there's no way from inside coreclr_initialize will get back to the host before APIs (nothing will call hostfxr APIs).
> 
> Definitely real. @jander-msft had tried out `hostfxr_get_runtime_property_value` during startup suspension and we crash because we try to take a lock recursively (but the original lock in non-recursive). We could avoid the crash, we'd then return an error about not being initialized. I don't know how much we could do here (aside from not crash so that it actually returns an error). The only action that could technically be valid at that point is getting a property value, since those were computed on the host side and doesn't depend on the runtime being initialized.

During `ICorProfilerCallback::Initialize`, it would be great if it return some error code rather than crashing. If we got #83756, then I don't think we need to interrogate the host for runtime property values so this may not be necessary. But from a correctness perspective, it probably shouldn't crash when invoked.

For loading the managed assembly, so long as we get #83756, we don't need to be able to do that during `ICorProfilerCballck::Initialize`; I don't think there's a scenario where we'd have someone use the .NET Monitor profiler at startup without having dotnet-monitor involved (which would have been able to use the solution from #83756 to set the startup hook). @wiktork do you see any scenario where we need to load managed assembly in/around `ICorProfilerCballck::Initialize` but there is no .NET Monitor process? This would be someone setting the profiler environment variables to load the .NET Monitor profiler without the .NET Monitor process existing and we want to have our startup hook loaded. I think in that hypothetical scenario, we'd have the person also set the .NET Monitor startup hook via the environment variable too.

I think if we got this issue resolved (by allowing `nullptr` to be passed for the `hostfxr_handle` parameter in `hostfxr_get_runtime_delegate`), I think this is sufficient for our attach scenario (.NET process is already running, profiler is loaded via attach).

**Comment by jander-msft** [comment]
I'm hoping that we can land this for .NET 8. Is there anything I can do to help it along or contribute here? If it's a matter of allowing the `nullptr` to be passed just as `hostfxr_get_runtime_property_value` allows for it today (barring the crashing issue), then I think this is probably something I can contribute myself.

> One possible issue (again don't know if it's actually real) - the hosting APIs assume that there's no way from inside coreclr_initialize will get back to the host before APIs (nothing will call hostfxr APIs). The host actively waits for the coreclr_initialize to return and until that happens the NULL context trick will not work (as the active context is still considered not fully initialized). So if the profiler callback happens during coreclr_initialize it would get errors from the hostfxr APIs.

I think it's fine if the APIs return an error code under this condition (rather than crash). I'm not expecting to realistically invoke any of the assembly loading APIs until after the runtime has finished initialization; I want to be able to use these on profiler attach, which is some arbitrary point during the managed execution of the process, not typically at the very beginning before initialization.

**Comment by elinor-fung** [comment]
If you are willing to contribute here, it would certainly be appreciated.

I think allowing `hostfxr_get_runtime_delegate` to take a `nullptr` handle would be like `hostfxr_get_runtime_property_value`. Adding [hosting tests](https://github.com/dotnet/runtime/blob/main/docs/workflow/testing/host/testing.md) is probably the more complicated part. To test the native hosting APIs, we build a [`nativehost` executable](https://github.com/dotnet/runtime/tree/main/src/native/corehost/test/nativehost) that takes different command line arguments to run different scenarios. It gets launched by [managed tests cases](https://github.com/dotnet/runtime/blob/main/src/installer/tests/HostActivation.Tests/NativeHosting/HostContext.cs) which check the output. This is an example of a case that runs an app and uses the hosting APIs to get a property from the active context.
https://github.com/dotnet/runtime/blob/7a57f6dd800e77508a4ba405e623059935c82f43/src/installer/tests/HostActivation.Tests/NativeHosting/HostContext.cs#L260-L262
https://github.com/dotnet/runtime/blob/7a57f6dd800e77508a4ba405e623059935c82f43/src/native/corehost/test/nativehost/host_context_test.cpp#L751-L755
https://github.com/dotnet/runtime/blob/7a57f6dd800e77508a4ba405e623059935c82f43/src/native/corehost/test/nativehost/host_context_test.cpp#L133-L134

For the crash, I suspect we should check that we are not mid-initialization (`g_context_initializing`) when trying to get the contract for an existing context and bail out with `HostInvalidState`:
https://github.com/dotnet/runtime/blob/7a57f6dd800e77508a4ba405e623059935c82f43/src/native/corehost/hostpolicy/hostpolicy.cpp#L760-L767

**Comment by jander-msft** [comment]
Thanks for the pointers! These were helpful for knowing where to get started.

After looking at the code a bit, it looks like the existing tests always pass the `hostfxr_handle` to `get_runtime_delegate`; my thinking is that I would add another parameter to `config_test`, `app`, and `mixed` in host_context_test.cpp that would indicate whether that handle should be passed into `inspect_modify_properties` and `get_runtime_delegate` functions and then updated the managed test to expand their matrix to pivot on this value. This would effectively get coverage on the `nullptr` usage of the `hostfxr_handle` parameter for the `hostfxr_get_runtime_delegate`, `hostfxr_get_runtime_property_value`, `hostfxr_get_runtime_properties` exports.

Does this sound reasonable?

**Comment by elinor-fung** [comment]
That seems reasonable. Testing using a null handle for getting properties in `inspect_modify_properties` should already be handled by the `check_properties::get_active/get_all_active` scenarios, so it might make sense to have the new parameter be specific to getting the runtime delegate.
