### ISSUE TITLE
about net8 aot and arm11 support

### ISSUE THREAD

**Issue by cuican6** [dotnet/runtime#84153]
hello,sir
    I am an iot developer;

    I wonder if net8 has plans to support arm9 arm11;

    I wonder if net8 plans to support linux-arm32 aot;

thank you

**Comment by jkotas** [comment]
> I wonder if net8 has plans to support arm9 arm11;

These are ARMv4/5 and ARMv6 instruction sets. We have no plans to officially support these old instruction sets in .NET runtime, the minimum is ARM v7. More discussion about this is in https://github.com/dotnet/runtime/issues/83975 .

> I wonder if net8 plans to support linux-arm32 aot;

We have no plans to add support for native AOT for linux-arm32 in .NET 8. We would still accept community contributions towards ARM32-Linux if these is interest (https://github.com/dotnet/runtime/issues/69739#issuecomment-1328372823).
