### ISSUE TITLE
BinClashes for Microsoft.Interop.SourceGeneration.dll

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#84157]
### Description

I opened a binlog and noticed this:
<img width="643" alt="image" src="https://user-images.githubusercontent.com/8918108/229008739-fb2a38be-07f3-4944-b8e8-44aa5fa81ac7.png">

That indicates the build is building both debug and release copies of Microsoft.Interop.SourceGeneration.dll.  We end up shipping whichever one builds last.

### Reproduction Steps

Build the product and examine binlog.

### Expected behavior

No binclashes

### Actual behavior

Binclashes for Microsoft.Interop.SourceGeneration.dll

**Comment by elinor-fung** [comment]
> Build the product and examine binlog.

@ericstj could you share what exactly you built and/or the binlog?

The source generation project gets used by both libraries and runtime (SPCL) build, so I'm wondering if this could be from building one of those in Debug and one of those in Release.

**Comment by ericstj** [comment]
This one was from an official build (note those paths are the ones used by our build machines).

My assumption was that it was due to some project stripping the `Configuration` property or somehow triggering a build that default it to a different configuration.

Let's see if I can find the binlog I downloaded.  Sorry I didn't include that in the orginal issue.

**Comment by ericstj** [comment]
I found the log, here's the command:
```
Command line arguments = "D:\a\_work\1\s\.dotnet\sdk\8.0.100-preview.1.23115.2\MSBuild.dll -maxcpucount -verbosity:m /m /nologo /clp:Summary /v:minimal /nr:False /p:ContinuousIntegrationBuild=True /warnaserror /p:TreatWarningsAsErrors=true D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23172.2\tools\Build.proj /bl:D:\a\_work\1\s\artifacts\log\Release\Build.binlog /p:Configuration=Release /p:RepoRoot=D:\a\_work\1\s\ /p:Restore=True /p:DeployDeps=False /p:Build=True /p:Rebuild=False /p:Deploy=False /p:Test=False /p:Pack=False /p:IntegrationTest=False /p:PerformanceTest=False /p:Sign=False /p:Publish=False /p:TargetArchitecture=x86 /p:subset=tools+libs+libs.tests /p:BuildTargetFramework=net48 /p:testscope=innerloop /p:ArchiveTests=true /logger:D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23172.2\tools\net8.0\Microsoft.DotNet.ArcadeLogging.dll"
```

I went ahead and checked the official builds to see if it reproduces there -- since that's where it matters most.  A repro in the official build might mean we're accidentally shipping debug generator. 

It appears to reproduce there too.  Here's a link to a log from the latest official build: https://dev.azure.com/dnceng/_apis/resources/Containers/13514893/Windows_NT_Libraries%20Build%20windows%20allConfigurations%20x64%20Release?itemPath=Windows_NT_Libraries%20Build%20windows%20allConfigurations%20x64%20Release%2FBuild.binlog

That seems to also have some other binclashes which I'll follow up on.

**Comment by elinor-fung** [comment]
Ah, thanks. Somehow completely that those are build machine paths.

> My assumption was that it was due to some project stripping the Configuration property or somehow triggering a build that default it to a different configuration.

Quick search through the evaluation phase for projects with Configuration=Debug:
```
AndroidAppBuilder.csproj
AppleAppBuilder.csproj
AssemblyStripper.csproj
Crossgen2Tasks.csproj
installer.tasks.csproj
LibraryBuilder.csproj
LibraryImportGenerator.csproj
Microsoft.Interop.SourceGeneration.csproj
Microsoft.NET.WebAssembly.Webcil.csproj
MonoAOTCompiler.csproj
MonoTargetsTasks.csproj
RepositoryValidation.proj
tasks.proj
TestExclusionListTasks.csproj
WasmAppBuilder.csproj
WasmBuildTasks.csproj
WorkloadBuildTasks.csproj
```

**Comment by elinor-fung** [comment]
Oh. We hard-code `Configuration=Debug` in tasks.proj
