### ISSUE TITLE
Multiple string concatenations in System.Net.Cookie class

### ISSUE THREAD

**Issue by tudoranghelina91** [dotnet/runtime#84167]
It seems that there are multiple string concatenations happening inside System.Net.Cookie

e.g. 
[Cookie.cs Line 724](https://github.com/dsisco11/runtime/blob/c861e47b42178c283688753994c8e11c2fc838bb/src/libraries/System.Net.Primitives/src/System/Net/Cookie.cs#L724)

and

[Cookie.cs Line 743](https://github.com/dsisco11/runtime/blob/c861e47b42178c283688753994c8e11c2fc838bb/src/libraries/System.Net.Primitives/src/System/Net/Cookie.cs#L743)

I have a suggestion for improving this a little bit by using a String Builder instead.
Let me know what you think, and if it's worth the effort, feel free to assign it to me if you wish.

**Comment by gfoidl** [comment]
Switch to latest main branch, then that's already optimized.

Note: https://github.com/dotnet/runtime/blob/ef6b6d581fbcdf65516d59c0597288755d46cb57/src/libraries/System.Net.Primitives/src/System/Net/Cookie.cs#L734 are constant strings, so no string concatenation happens (at runtime).

**Comment by antonfirsov** [comment]
@gfoidl good catch, I didn't bother to check :) @tudoranghelina91 do you see anything else worth optimizing, or can we close this?

**Comment by Joe4evr** [comment]
Importantly, the case of line 743 has the comment `// const strings` so use of concatination there doesn't matter since concatinating const strings will result in a single const string at compile-time.

Also, line 724 is `GetHashCode` so it's possible that one requires to be less complicated.

**Comment by tudoranghelina91** [comment]
@antonfirsov, all good. You may close the issue 😁. No action has been taken.

**Comment by danmoseley** [comment]
Thank you for the issue @tudoranghelina91 we would generally be interested if you see unnecessary allocations in other places in the libraries.

**Comment by tudoranghelina91** [comment]
> Thank you for the issue @tudoranghelina91 we would generally be interested if you see unnecessary allocations in other places in the libraries.

Hey @danmoseley, thanks. Will keep an open eye for this.
