### ISSUE TITLE
System.Linq.Expressions almost completely lacks support for ByRef values

### ISSUE THREAD

**Issue by atykhyy** [dotnet/runtime#84173]
With the advent of types such as `ReadOnlySpan<T>` many highly useful methods have been added to the runtime which return `ref` values. For example `ReadOnlySpan<T>`'s indexer returns a `ref T`. However, there is no unary expression in LINQ expressions that would allow one to use the return value of such methods. Worse, an expression invoking such a method cannot be used as a method argument even when types match exactly. When I tried to work around the lack of any dereference expression with a silly helper method to unwrap the `ref`, LINQ expressions complains that "Expression of type `System.Byte&` cannot be used for parameter of type `System.Byte` of method `Byte DerefByte(Byte ByRef)` (Parameter 'arg0')". The workaround is to create a static method wrapping the whole indexer, but this is hardly ideal.

```csharp
public static void Sink (byte b) {}
public static byte DerefByte (ref byte b) => b ;
public static byte GetByte (ReadOnlySpan<byte> span, int index) => span[index] ;
delegate void ProcessDelegate (ReadOnlySpan<byte> span) ;

void Compile ()
{
  var span  = Expression.Parameter (typeof (ReadOnlySpan<byte>)) ;
  var index = Expression.Constant  (1) ;
  var meth  = typeof (ReadOnlySpan<byte>).GetProperty ("Item").GetMethod ;
  // does not work:
  Expression.Lambda<ProcessDelegate> (
    Expression.Call (GetType (), nameof (Sink),
    Expression.Call (span, meth, index)),
    span).Compile () ;
  // does not work either:
  Expression.Lambda<ProcessDelegate> (
    Expression.Call (GetType (), nameof (Sink),
    Expression.Call (GetType (), nameof (DerefByte),
    Expression.Call (span, meth, index))),
    span).Compile () ;
  // only this works
  Expression.Lambda<ProcessDelegate> (
    Expression.Call (GetType (), nameof (Sink),
    Expression.Call (GetType (), nameof (GetByte), span, index)),
    span).Compile () ;
}
```

My specific use case is building a `Span`-based bytestream parser with LINQ expressions.

**Comment by cston** [comment]
@atykhyy, thanks for reporting this issue.

The `System.Linq.Expressions` library is effectively archived, and we are only taking changes that address significant bugs or regressions, or changes needed to continue shipping - see [README.md](https://github.com/dotnet/runtime/tree/main/src/libraries/System.Linq.Expressions/README.md).
