### ISSUE TITLE
GC.GetConfigurationVariables() not respecting "System.GC.HighMemoryPercent"

### ISSUE THREAD

**Issue by asrichesson** [dotnet/runtime#84198]
### Description

I'm trying to set the garbage collection properties in a runtimeconfig.template.json file, following the documentation in [Garbage collector config settings](https://learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector).
But not all my settings are being picked up, including `System.GC.HighMemoryPercent`. However, some properties like `System.GC.HeapHardLimit` *are* being picked up. 

I'm not sure whether my settings are invalid, the documentation is wrong, or the `GC.GetConfigurationVariables()` isn't returning the actual config values.

### Reproduction Steps

I have the following runtimeconfig.template.json file in a .net 7 console application. I have no related environment variables set.
```json
{
  "configProperties": {
    "System.GC.HighMemoryPercent": 75,
    "System.GC.LOHThreshold": 120000,
    "System.GC.Server": true,
    "System.GC.RetainVM": true,
    "System.GC.HeapHardLimit": 209715201,
    "System.GC.Concurrent": true,
    "System.GC.HeapCount": 9
  }
}
```
```csharp
var gcConfig = GC.GetConfigurationVariables();

foreach (var kvp in gcConfig)
{
    Console.WriteLine(kvp.Key + ":" + kvp.Value);
}
```
```text
ServerGC:True
ConcurrentGC:True
RetainVM:False
NoAffinitize:False
GCCpuGroup:False
GCLargePages:False
HeapCount:9
GCHeapAffinitizeMask:0
GCHeapAffinitizeRanges:
GCHighMemPercent:0
GCHeapHardLimit:209715201
GCHeapHardLimitPercent:0
GCHeapHardLimitSOH:0
GCHeapHardLimitLOH:0
GCHeapHardLimitPOH:0
GCHeapHardLimitSOHPercent:0
GCHeapHardLimitLOHPercent:0
GCHeapHardLimitPOHPercent:0
GCConserveMem:0
GCName:
```
[GCProgram.zip](https://github.com/dotnet/runtime/files/11128044/GCProgram.zip)

### Expected behavior

I should expect to see the following included in the program output.
```
GCHighMemPercent:75
```

### Actual behavior

```
GCHighMemPercent:0
```

### Known Workarounds

Setting the `DOTNET_GCHighMemPercent` env variable didn't seem to work either.

### Configuration

.net7, windows 11, x64

**Comment by mangod9** [comment]
@mrsharm can you take a look at this?

**Comment by mrsharm** [comment]
Yes, taking a look. I was able to repro. I will have a fix soon.

**Comment by asrichesson** [comment]
Looks like `System.GC.RetainVM` is also not being set.
