### ISSUE TITLE
PGO for Memmove unrolling

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#84192]
Poll size passed to Buffer.Memmove in Tier0 in order to optimize it in Tier1 for the most popular length at the given callsite. A simulated scenario:
```csharp
byte[] _src = new byte[50];
byte[] _dst = new byte[50];

[Benchmark]
public void CopyUnknownSize()
{
    _src.AsSpan().CopyTo(_dst);
}

[Benchmark]
public void CopyUnknownSize_PGO()
{
    // simulated PGO (Tier0 realized that we mostly do Memmove here for 50 elements)
    if (_src.Length == 50)
    {
        _src.AsSpan(0, 50).CopyTo(_dst); // unrolled for constant size via AVX
    }
    else
    {
        // fallback
        _src.AsSpan().CopyTo(_dst);
    }
}
```

|              Method |      Mean |
|-------------------- |----------:|
|     CopyUnknownSize | 1.6005 ns |
| CopyUnknownSize_PGO | **0.5583 ns** |

The actual difference should be bigger becuase my simulation does some additional overhead with `AsSpan(0, 50)`.
I think it's pretty straightforward to implement in JIT, the only part I'm not sure is the new PGO schema on vm side. cc @AndyAyersMS 

PS: As far I know, native compilers do this sort of optimizations for memset/memcpy with PGO

**Comment by AndyAyersMS** [comment]
> The actual difference should be bigger becuase my simulation does some additional overhead with `AsSpan(0, 50)`. I think it's pretty straightforward to implement in JIT, the only part I'm not sure is the new PGO schema on vm side. cc @AndyAyersMS
> 
> PS: As far I know, native compilers do this sort of optimizations for memset/memcpy with PGO

Yes, native compilers do this sort of "value profiling" for things like this, values of divisors, etc. One option is to introduce a new histogram type (length histogram). This might need a larger reservoir table.

But that might be too fine grained -- we could instead leverage knowledge of threshold values where our optimization approach changes, and leverage that aspect directly. For example say there are 3 length categories -- small, medium, and large, with count values of 8 and 128 or something. The jit could produce a table of 3 records for these three categories, and at runtime increment the proper category counter. With a bit of cleverness, we could keep these thresholds private to the jit and not need to have the jit and runtime agree.

**Comment by EgorBo** [comment]
NOTE: this needs context-sensitive profiling, e.g. Memmove is hidden under wrapper functions so if we inset probes in them we'll never get monomorphic values
