### ISSUE TITLE
How to get the byte pointer / a byte span to the data of an boxed object?

### ISSUE THREAD

**Issue by dn9090** [dotnet/runtime#84209]
### Background and Motivation

Due to performance reasons I'm mostly using value types in a big memory blob (native memory).
```CSharp
struct Position { public Vector3 value; }
struct Rotation { public Vector4 value; }
struct Velocity { public Vector3 value; }

struct TypeInfo { public int offsetInBuffer; public int count; public Type type; }

struct Physics {
  public TypeInfo[] infos;
  public byte* data;
}
```
I convert the values from a structure-of-arrays to a array-of-structures for the JSON serialization manually with the `Utf8JsonWriter` (unfortunately with boxing):
```CSharp
json.WriteStartObject();
for(int t = 0; t < infos.Length; ++t) {
  var value = JsonSerializer.Serialize(GetValueAtCurrentIndex(), options);
  json.WritePropertyName(infos[t].type.FullName);
  json.WriteRawValue(value);
}
json.WriteEndObject();
```
This works okayish.

### The Problem
The API's in `System.Text.Json` only provide `object` input and returns types like (for non generic types):
```CSharp
string Serialize (object? value, Type inputType, JsonSerializerContext context);
object? Deserialize (string json, Type returnType, JsonSerializerContext context);
```

The problem arises when I need to deserialize the JSON again. Because the serializer is missing a
```CSharp
ReadOnlySpan<byte> Deserialize (string json, Type returnType, JsonSerializerContext context);
```
API, it is impossible (correct me if I'm wrong) to unbox the `object` value to a `byte*` or `ReadOnlySpan<byte>` for writing the values in the memory blob. [A similar issue / proposal was closed](https://github.com/dotnet/runtime/issues/66934). So I have no other idea how to get to the byte data of the deserialized `object`.  `Unsafe.Unbox` requires a generic type that I do not have.
For an untyped `Array` there are the `MemoryMarshal.GetArrayDataReference` functions. But I can't find anything similar for objects.
Is there a solution / other API for this?

**Comment by EgorBo** [comment]
Will `JsonDocument` or even `Utf8JsonReader` work for you then?

**Comment by dn9090** [comment]
> Will `JsonDocument` or even `Utf8JsonReader` work for you then?

Only for serialization (with boxing which is not great). I tried a workaround for deserialization with
```CSharp
var handle = GCHandle.Alloc(value, GCHandleType.Pinned);
var slice = new Span<byte>(handle.AddrOfPinnedObject(), sizeInBytes);
```
but it did not work (everything is 0). Unfortunately other JSON libraries have the same limitations (with `object`).

**Comment by dn9090** [comment]
After a bit of trial and error, I came up with two solutions. The first solution is the (hopefully) safe variant, in which a GCHandle is allocated and the address of the handle gets converted to the byte pointer:
```CSharp
var handle = GCHandle.Alloc(value, GCHandleType.Pinned);
var result   = new Span<byte>(handle.AddrOfPinnedObject(), GetSize(type));
// ...
handle.Free();
```
The second variant I stole from the AOT runtime and looks very shaky to me, but has less overhead because no GCHandle has to be allocated:
```CSharp
[StructLayout(LayoutKind.Sequential)]
internal class RawData {
	public byte Data;
}

var ptr = Unsafe.AsPointer(ref GetRawData(value));
var result   = new Span<byte>(ptr, GetSize(type));
```
@zgabi maybe it will solve your problem as well.

**Comment by jkotas** [comment]
```csharp
[StructLayout(LayoutKind.Sequential)]
internal class RawData {
	public byte Data;
}

internal static ref byte GetRawData(object obj) {
  return ref Unsafe.As<RawData>(obj).Data;
}

var ptr = Unsafe.AsPointer(ref GetRawData(value));
var result = new Span<byte>(ptr, GetSize(type));
```

@dn9090 This code fragment is not correct. If you depend on it in your application, you are going to see intermittent crashes and data corruptions, often in unrelated part of your program. The remarks section in documentation of the `Unsafe.AsPointer` API talks about it: https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.unsafe.aspointer?view=net-8.0#remarks .

You may have seen similarly looking code in dotnet/runtime repo. It is not a good idea to copy a low-level code from this repo without detailed understanding what it does and why it works. Some parts of this repo use non-portable implementation strategies that won't generally work well outside this repo.

**Comment by dn9090** [comment]
@jkotas Thank you. Does the first variant work (with the GCHandle)? Otherwise, I do not know how to solve the unboxing problem.

**Comment by zgabi** [comment]
@dn9090: Could you please share your GetSize method?

**Comment by dn9090** [comment]
> @dn9090: Could you please share your GetSize method?

Sure, it's also a workaround because `Unsafe.SizeOf` is requires a generic type too:
```
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static int SizeOf(Type type) {
  // Workaround because Unsafe.SizeOf does not accept a type object and
  // Marshal.SizeOf gives back the wrong size (and does not work with generic types).
  var method = typeof(Unsafe).GetMethod(nameof(Unsafe.SizeOf)).MakeGenericMethod(type);
  return (int)method.Invoke(null, null);
}
```
This is expensive so I cache the result for every type ([here is my actual implementation](https://github.com/dn9090/Checs/blob/main/src/Checs/Types/TypeUtility.cs).

**Comment by zgabi** [comment]
Or maybe  even better:

```
    interface IWrapper
    {
        public Span<byte> GetData(object value);
    }

    struct Wrapper<T> : IWrapper where T : unmanaged
    {
        public T Value;

        public Span<byte> GetData(object obj)
        {
            Value = (T)obj;
            return MemoryMarshal.AsBytes(MemoryMarshal.CreateSpan(ref Value, 1));
        }
    }

    private static IWrapper GetValueWrapper(Type type)
    {
        var wrapperType = typeof(Wrapper<>).MakeGenericType(type);
        var instance = (IWrapper)Activator.CreateInstance(wrapperType);
        return instance;
    }

```

use:
```
        var obj = DateTime.Now;
        var type = obj.GetType();

        var cachedWrapper = GetValueWrapper(type);

        var bytes = cachedWrapper.GetData(obj).ToArray();

```

**Comment by dn9090** [comment]
The problem is that the object gets boxed two times in your case.
First you have the boxed object and then you box it a second time by passing the object in the wrapper and casting it again to an `IWrapper` interface. The advantage of the `GCHandle.Alloc` is that I get direct access to the boxed byte values. If the implementation has remained that way, GCHandle will not allocate anything if the cache behind it is large enough.

**Comment by zgabi** [comment]
I don't understadn your comment. The cached wrapper is already an IWrapper.. if you use that (boxed) object, no other boxing occurs.

```
using System.Runtime.InteropServices;

namespace ConsoleApp4;

internal class Program
{
    static unsafe void Main(string[] args)
    {
        var obj = (object)DateTime.Now;
        var type = obj.GetType();

        var cachedWrapper = GetValueWrapper(type);

        long totalBytes = 0;
        for (int i = 0; i < 1000000; i++)
        {
            var bytes = cachedWrapper.GetData(obj);
            totalBytes += bytes.Length;
        }

        Console.WriteLine(totalBytes);
        Console.ReadLine();
    }

    private static IWrapper GetValueWrapper(Type type)
    {
        var wrapperType = typeof(Wrapper<>).MakeGenericType(type);
        var instance = (IWrapper)Activator.CreateInstance(wrapperType);
        return instance;
    }
}

interface IWrapper
{
    public Span<byte> GetData(object value);
}

struct Wrapper<T> : IWrapper where T : unmanaged
{
    public T Value;

    public Span<byte> GetData(object obj)
    {
        Value = (T)obj;
        return MemoryMarshal.AsBytes(MemoryMarshal.CreateSpan(ref Value, 1));
    }
}
```

Result:
![image](https://user-images.githubusercontent.com/3104253/229628111-c5755c88-b844-4e81-b441-3999ef7122ab.png)

Of course the wrapper is boxed, since it is a stuct, but you can use a class instead :)

**Comment by dn9090** [comment]
> I don't understadn your comment. The cached wrapper is already an IWrapper.. if you use that (boxed) object, no other boxing occurs.

My comment was referring to the line:
```
var instance = (IWrapper)Activator.CreateInstance(wrapperType);
```
where the struct gets boxed to the interface. But I agree, if you cache it and store it as a class (which I want to avoid), you can avoid the second boxing.

Having just looked again at the wonky upper solution, I wonder if the following might work after all (without `Unsafe.AsPointer` this time)?:
```CSharp
[StructLayout(LayoutKind.Sequential)]
internal class RawData {
	public byte Data;
}

var data = Unsafe.As<RawData>(value);
var result = MemoryMarshal.CreateSpan(ref data.Data, GetSize(value));
```
This avoids the wrapper / GCHandle completely and is not using pointers (which should avoid the GC problem).
