### ISSUE TITLE
LoggerMessageAttribute extension to support Exception messages

### ISSUE THREAD

**Issue by Simonl9l** [dotnet/runtime#84233]
As an example : It seems that a general use case it to raise an exception and in the handler log an error. One tends to generate (custom) exceptions with custom parameterized strings.

Whilst the LoggerMessageAttribute is exceptionally good (and getting better) with the Logging Message part and support taking an exception as a parameter, and soon @ support too.

However, given the general case above, this is of limited value if one just regurgitates the exception string.

Is there a way, proposal or enhancement approach such that one can hook an exception into the Loggin Message code generation?

**Comment by tarekgh** [comment]
Why can't you use the template message to format the exception the way you like? 

```C#
    [LoggerMessage(EventId = 0, Level = LogLevel.Critical, Message = "{exceptionType}:  `{message}`\nExceptionSatck: {exceptionSatck}")]    
	public static partial void LogException(ILogger logger, string exceptionType, string exceptionMessage. string exceptionSatck);
```
Then when having any exception object `e`, you can do something like:
```C#
LogException(logger, e.GetType().ToString(), e.Message. e.StackTrace);
```

**Comment by tarekgh** [comment]
@Simonl9l thanks for the reply. To ensure I fully understand your proposal here, what happens when you call `LogError(e)`? can you explain in more detail what you expect the source gen will do?

**Comment by tarekgh** [comment]
> LogError(e) is the invocation of a LoggerMessage! per

I know that this was not my question. Sorry if I was not clear.

I am asking how you want LoggerMessage to handle this? The method `LogError` takes the exception `e` and having the attribute including `ExceptionMessage = MyError`.  `MyError` is defined as `static exception MyError(int parameter);`.  Could you write the exact code you expect to be generated from `LogError`?
