### ISSUE TITLE
System.Configuration.TypeUtil.GetImplicitType 

### ISSUE THREAD

**Issue by Turhan8** [dotnet/runtime#84244]
### Description

When application does not load correct app.config I am able to use the correct config by
`AppDomain.CurrentDomain.SetData("APP_CONFIG_FILE", path);`
However, if you have a custom configSection in the app.config which is defined in your assembly, the type is not found due to 
line 52 in `System.Configuration.TypeUtil.GetImplicitType `
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/TypeUtil.cs

typeString.IndexOf(',') will fail because this is how we specify the assembly. This check should be removed.

### Reproduction Steps

I have had this issue when upgrading my excel-dna application from .net framework 4.7.2 to .NET6.
If ConfigurationManager had worked, this upgrade would have been with almost no code change.

### Expected behavior

When config used by ConfigurationManager is changed with this
`AppDomain.CurrentDomain.SetData("APP_CONFIG_FILE", path);`
We want custom configSection types to load correctly.

### Actual behavior

Currently we get an exception that says something like "Could not find the assembly that contains the type"

### Known Workarounds

I could not find a work around. I guess if I can tell the AppDomain that it is not the machine.config, it may work. Can you think of a workaround?

**Comment by buyaa-n** [comment]
> typeString.IndexOf(',') will fail because this is how we specify the assembly. This check should be removed.

@Turhan8 do not understand why/how the type name you are searching got a comma in it. It would be very helpful if you could provide a sample app for repro.

**Comment by buyaa-n** [comment]
v
Apparently by design
