### ISSUE TITLE
Incorrect comparison of cyrillic words [net6]

### ISSUE THREAD

**Issue by maa** [dotnet/runtime#84251]
Tactics would like to hold on this backport pending evidence of wider impact. Noted that the customer reporting this has a workaround.

_Originally posted by @danmoseley in https://github.com/dotnet/runtime/issues/71158#issuecomment-1164688562_

Due to this bug comparison of words with cyrillic letter 'ё' is not working properly.

**Comment by maa** [comment]
> @maa
> 
> > Due to this bug comparison of words with cyrillic letter 'ё' is not working properly.
> 
> What you are mentioning here is different than the issue listed in the #71158. How did you conclude that? Could you share a sample code to demonstrate the problem?

Why do you think that it is different problem? Ordinal ignore case comparison do not working properly for cyrillic words in net6.

Example: `StringComparer.OrdinalIgnoreCase.Compare("ёлка", "ясень")`
netcore3.1 (NLS): -1
net5 (ICU): -46
net6 (ICU): +2
net7 (ICU): -46

Obviously, net6 runtime returns incorrect (positive) result.

**Comment by tarekgh** [comment]
> Why do you think that it is different problem? Ordinal ignore case comparison do not working properly for cyrillic words in net6.

Because the issue title/description did not mention ordinal comparisons at all. 

Considering your code sample, it is the same issue. The question now, can't you use .NET 7.0?

**Comment by lsoft** [comment]
@tarekgh 

> The question now, can't you use .NET 7.0?

net6 is LTS release, I guess it would be correct to backport the fix from net7 to net6. :)

**Comment by tarekgh** [comment]
> net6 is LTS release, I guess it would be correct to backport the fix from net7 to net6. :)

We backport if we see demand on that. That is what I am trying to figure out that. How many users are running into this issue and can't upgrade to .NET 7.0.

**Comment by lsoft** [comment]
@tarekgh 

> the risk of the product stability.

I understand that there is a risk for product stability, but I also see the huge impact of basic algorithms like sorting users by their lastname. Such bugs may be a strong blocker to migrate to net6.

>  and can't upgrade to .NET 7.0

there are a lot of projects that cannot migrate to non-LTS releases.

> if we see demand on that

My voice is here :) Please consider to backport this to net6.


Thank you! 👍

**Comment by maa** [comment]
> The question now, can't you use .NET 7.0?
Nope. 

> How many users are running into this issue and can't upgrade to .NET 7.0.
I guess that many users facing this bug but just have not noticed the problem yet.

> My voice is here :) Please consider to backport this to net6.
👍

**Comment by vonzshik** [comment]
+1 for backporting to .NET 6. While I can't confirm that we've encountered it yet, we're not able to upgrade to .NET 7 due to `System.Drawing.Common` being unusable on linux.

**Comment by tarekgh** [comment]
I have ported the fix to 6.0 servicing release through the PR https://github.com/dotnet/runtime/pull/84386. The fix should be included in the next servicing release.
