### ISSUE TITLE
Type.IsValueType returns true for type parameter constrained to Enum

### ISSUE THREAD

**Issue by svick** [dotnet/runtime#84256]
### Description

The `Type.IsValueType` property returns `true` for type parameters constrained to `Enum`. That's technically incorrect, because the reference type `Enum` also satisfies that constraint.

I don't know if this is something that should be fixed, or just documented as a quirk of the implementation.

### Reproduction Steps

[Run the following code:](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUKgBgAJVMA6AGQEsoBHAbjz1IE4AKYATwAcBTAewBmbUgHYAlGQDivYAFlZAC35w2AIjlrxAQmmyZUXmCoBjAIJgA5hAC2vKMADObSQGUalgDa8XZAJKOAGoAhp4QvAAqPLzijPiY7Fx8QmwAolC2kgEhYZHRsXhyADzptgB8LnF43MFgwFShJOgkmKJ4AN54RN0kAMwtAGwkACxExREV4kQA7opGvEQRRCBEpTZdPZ24PTstidEpEVlBoeFRfAXbPQC+eNdAA==)

```c#
using System;
using System.Linq;

Console.WriteLine(typeof(Program).GetMethod("M")!.GetGenericArguments().Single().IsValueType);
Console.WriteLine(typeof(Enum).IsValueType);
M<Enum>();

partial class Program
{
    public static void M<T>() where T : Enum
    {
        Console.WriteLine(typeof(T).IsValueType);
    }
}
```

### Expected behavior

The type parameter is not considered a value type and so the program prints:

```
False
False
False
```

### Actual behavior

The program prints:

```
True
False
False
```

### Configuration

Core CLR 7.0.222.60605

**Comment by steveharter** [comment]
Since `<T>` can either be a specific enum or `System.Enum`, the existing semantics are fine. They are also consistent with `ParameterType`:
```cs

Console.WriteLine("M unbound:" + typeof(Program).GetMethod("M")!.GetGenericArguments().Single().IsValueType);
Console.WriteLine("Arg unbound to System.Enum:" + typeof(Program).GetMethod("M")!.GetParameters()[0].ParameterType.IsValueType);
Console.WriteLine("M bound to System.Enum:" + typeof(Program).GetMethod("M")!.MakeGenericMethod(new Type[] { typeof(Enum) }).GetGenericArguments().Single().IsValueType);
Console.WriteLine("Arg bound to System.Enum:" + typeof(Program).GetMethod("M")!.MakeGenericMethod(new Type[] { typeof(Enum) }).GetParameters()[0].ParameterType.IsValueType);
Console.WriteLine("M bound to specific enum:" + typeof(Program).GetMethod("M")!.MakeGenericMethod(new Type[] { typeof(MYENUM) }).GetGenericArguments().Single().IsValueType);
Console.WriteLine("Arg bound to specific enum:" + typeof(Program).GetMethod("M")!.MakeGenericMethod(new Type[] { typeof(MYENUM) }).GetParameters()[0].ParameterType.IsValueType);

partial class Program
{
    public static void M<T>(T t) where T : Enum
    {
        Console.WriteLine(typeof(T).IsValueType);
    }
}

public enum MYENUM { }
```
output:
```
M unbound:True
Arg unbound to System.Enum:True
M bound to System.Enum:False
Arg bound to System.Enum:False
M bound to specific enum:True
Arg bound to specific enum:True
```

Also note that even `ValueType` is similar to `Enum`: a specific type will return `false` but the general type will return `true`. E.g. 
`typeof(ValueType).IsValueType` will return `false`.

We could doc this, but seems like a very edge case; if you feel this should be doc'd, please re-open this and I'll move it to the docs repo.
