### ISSUE TITLE
[API Proposal]: Paraller For and Paraller Foreach

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#84266]
### Background and motivation

I suggest adding or replacing Parallel Foreach and Parallel in the runtime so that it works according to this principle
https://github.com/Mr0N/example12345/blob/master/example12345/Program.cs

### API Proposal

```csharp
using System;

class MyParaller
{
    public void Foreach<TObj>(IEnumerable<TObj> enumerable, Action<TObj?> func, int countTask)
    {
        var query = Slice(enumerable, countTask);
        var ls = new List<Task>(countTask);
        foreach (var iCollection in query)
        {
            var task = Task.Run(() =>
            {
                foreach (var item in iCollection)
                {
                    func.Invoke(item);
                }
            });
            ls.Add(task);
        }
        Task.WaitAll(ls.ToArray());
        // enumerable.Chunk
    }
    private IEnumerable<IEnumerable<TObj>> Slice<TObj>(IEnumerable<TObj> en, int count)
    {
        var enumerator = en.GetEnumerator();
        for (int i = 0; i < count; i++)
        {
            yield return GetPart(enumerator);
        }

    }
    private IEnumerable<TObj> GetPart<TObj>(IEnumerator<TObj> en)
    {
        while (true)
        {
            lock (objLock)
            {
                if (!en.MoveNext())
                    break;
            }
            yield return en.Current;
        }
    }
    static object objLock = new object();
}
```

### API Usage

```csharp
new MyParaller().Foreach<int>(Enumerable.Range(0, 1000), a =>
{
    Console.WriteLine($"items:{a}  thread:{Thread.CurrentThread.ManagedThreadId}");
    for (int i = 0; i < int.MaxValue; i++)
    {

    }
}, 5);
```

**Comment by stephentoub** [comment]
> I suggest adding or replacing Parallel Foreach and Parallel in the runtime so that it works according to this principle

First, we're not going to "replace" the existing Parallel.ForEach.  What's there is there.  If there's something important missing, we can of course consider adding something.

Second, what "principle"?  You shared a code snippet, but it's not clear to me what difference there you're suggesting is important.  Are you trying to impact how it chunks items to be handled?  There's already a detailed system for partitioning via the Partitioner type and friends.  What doesn't that support that you need it to support?

**Comment by Mr0N** [comment]
> > I suggest adding or replacing Parallel Foreach and Parallel in the runtime so that it works according to this principle
> 
> First, we're not going to "replace" the existing Parallel.ForEach. What's there is there. If there's something important missing, we can of course consider adding something.
> 
> Second, what "principle"? You shared a code snippet, but it's not clear to me what difference there you're suggesting is important. Are you trying to impact how it chunks items to be handled? There's already a detailed system for partitioning via the Partitioner type and friends. What doesn't that support that you need it to support?



> > I suggest adding or replacing Parallel Foreach and Parallel in the runtime so that it works according to this principle
> 
> First, we're not going to "replace" the existing Parallel.ForEach. What's there is there. If there's something important missing, we can of course consider adding something.
> 
> Second, what "principle"? You shared a code snippet, but it's not clear to me what difference there you're suggesting is important. Are you trying to impact how it chunks items to be handled? There's already a detailed system for partitioning via the Partitioner type and friends. What doesn't that support that you need it to support?

The problem with Parallel.ForEach is probably that new tasks are being created at each iteration, which prevents the creation of resources for a single thread (task), and makes it work less efficiently in terms of speed.

**Comment by stephentoub** [comment]
> The problem with Parallel.ForEach is probably that new tasks are being created at each iteration

They're not.  Multiple tasks might be used, and tasks might be replaced in order to allow the thread pool to use the underlying thread for something else, but tasks can definitely process multiple iterations.

> which prevents the creation of resources for a single thread (task)

Overloads of these APIs exist to have iteration-local state that flows from delegate invocation to delegate invocation on the same thread.  You supply a delegate that initializes the value, that value is passed into the iteration delegate, and then there's an aggregation delegate that's invoked at the end, e.g.
https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.parallel.foreach?view=net-8.0#system-threading-tasks-parallel-foreach-2(system-collections-concurrent-partitioner((-0))-system-threading-tasks-paralleloptions-system-func((-1))-system-func((-0-system-threading-tasks-parallelloopstate-1-1))-system-action((-1)))

**Comment by Mr0N** [comment]
> > The problem with Parallel.ForEach is probably that new tasks are being created at each iteration
> 
> They're not. Multiple tasks might be used, and tasks might be replaced in order to allow the thread pool to use the underlying thread for something else, but tasks can definitely process multiple iterations.
> 
> > which prevents the creation of resources for a single thread (task)
> 
> Overloads of these APIs exist to have iteration-local state that flows from delegate invocation to delegate invocation on the same thread. You supply a delegate that initializes the value, that value is passed into the iteration delegate, and then there's an aggregation delegate that's invoked at the end, e.g. https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.parallel.foreach?view=net-8.0#system-threading-tasks-parallel-foreach-2(system-collections-concurrent-partitioner((-0))-system-threading-tasks-paralleloptions-system-func((-1))-system-func((-0-system-threading-tasks-parallelloopstate-1-1))-system-action((-1)))

Well, I don't know, but I think it's necessary to use the number of tasks per the number of threads specified in Parallel, as shown in the example. Whenever I've used Parallel, I've noticed a decrease in the speed of the program and an increase in the CPU load. Anyway), I've shared an example that could be implemented someday.)

**Comment by stephentoub** [comment]
What concretely are you proposing?

**Comment by stephentoub** [comment]
You want the body delegate to be passed an array of a few items rather than an individual item? You can just pass in src.Chunk(count) rather than src.

**Comment by Mr0N** [comment]
> You want the body delegate to be passed an array of a few items rather than an individual item? You can just pass in src.Chunk(count) rather than src.

Yes, it's just unclear what's in IEnumerable, it could contain IQueryable.

**Comment by stephentoub** [comment]
> Yes, it's just unclear what's in IEnumerable, it could contain IQueryable.

Every IQueryable is an IEnumerable, and Parallel.ForEach only processes enumerables... if you pass in a queryable, it'll be reified as an enumerable and processed.

**Comment by gfoidl** [comment]
> Yes, but if there are a couple of terabytes in the database, the program will not work.

I didn't follow along with this issue, but this sounds like Parallel.For/Each isn't the right thing to use. Producer/Consumer (i.e. [Channels](https://devblogs.microsoft.com/dotnet/an-introduction-to-system-threading-channels/)) may be a better fit for such things.

**Comment by stephentoub** [comment]
Your pseudo examples are all based on IEnumerable.  Are you actually asking for an IQueryable based set of APIs?  I don't see us adding anything like that.

**Comment by Mr0N** [comment]
> Your pseudo examples are all based on IEnumerable. Are you actually asking for an IQueryable based set of APIs? I don't see us adding anything like that.

I don't like the performance of Paraller.Foreach.

**Comment by stephentoub** [comment]
> I don't like the performance of Paraller.Foreach.

I still don't know what it is concretely you're proposing.  There are lots of solutions already available.  If you want the data chunked you can use Enumerable.Chunk or the equivalent.  If you want to control how the partitioning happens more dynamically you can use Partitioner.  If you want to manage task-local state you can use the initialize/finally delegates on overloads to ForEach.  If you want to manage TLS yourself you can use your own ThreadLocal.  Etc.

I'm going to close this now.  If you'd like to share more details about exactly what you'd hope to see improved, please feel free to re-open and do so.  Thanks.
