### ISSUE TITLE
WebAssembly way to run either AOT or JIT at runtime

### ISSUE THREAD

**Issue by andivlad-talentia** [dotnet/runtime#84288]
Hi,

The AOT compilation for Blazor WASM will actually ship both AOT and JIT. While the size of the downloaded application isn't a problem for us, the memory usage maybe sometimes (it will consume as expected 2x memory), is there a way to force the browser to run (or load?) the JIT code only somehow in certain scenarios?

**Comment by maraf** [comment]
Not all the code is AOT compiled and under some circumstances the when AOT code is running, it needs to fall back to interpreter and needs the IL code. We currently don't have a way to optimize this.

**Comment by andivlad-talentia** [comment]
That's understandable, my question is can we/could we force only non (full) AOT code in certain scenario/switch? 

Throwing a wild idea (which i'm sure overly simplifies things), have something like:
dotnet.aot.wasm
dotnet.wasm

And if there's a certain configuration in Blazor.start not load the AOT as an entry point ?

**Comment by maraf** [comment]
It should be doable. Blazor has an API that lets you choose how assets are downloaded https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-7.0#load-boot-resources.

So if you build the app twice, than you can manually create a layout that should let you decide on runtime which version gets downloaded.

Does it make sense? It that what you looked for?
