### ISSUE TITLE
OperatingSystem.IsLinux() returns false when running as exe on WSL2 ubuntu

### ISSUE THREAD

**Issue by zwcloud** [dotnet/runtime#84283]
### Description

`OperatingSystem.IsLinux()` unexpectedly returns false on WSL2 Ubuntu when running a console app as exe.

### Reproduction Steps

csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <PublishTrimmed>false</PublishTrimmed>
    <PublishReadyToRun>false</PublishReadyToRun>
    <PublishSingleFile>false</PublishSingleFile>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>
```

Program.cs
```cs
Console.WriteLine("OperatingSystem.IsLinux():" + OperatingSystem.IsLinux());
Console.WriteLine("OperatingSystem.IsWindows():" + OperatingSystem.IsWindows());
```

Then build and publish
```
dotnet publish -c Release
```
Published files are in `Z:\1_experiment\WSLOperatingSystemCheckDemo\bin\Release\net7.0\publish\` on my computer.
On WSL2, the path is `/mnt/z/1_experiment/WSLOperatingSystemCheckDemo/bin/Release/net7.0/publish/`.

Then run the app in two ways:
1. directly execute exe
```
/mnt/z/1_experiment/WSLOperatingSystemCheckDemo/bin/Release/net7.0/publish/WSLOperatingSystemCheckDemo.exe
```
result is unexpected:
```
OperatingSystem.IsLinux():False
OperatingSystem.IsWindows():True
```
2. run with dotnet and dll
```
dotnet /mnt/z/1_experiment/WSLOperatingSystemCheckDemo/bin/Release/net7.0/publish/WSLOperatingSystemCheckDemo.dll
```
result is correct
```
OperatingSystem.IsLinux():True
OperatingSystem.IsWindows():False
```

Screenshot of WSL2 running results:
![image](https://user-images.githubusercontent.com/6965758/229695807-828086ef-ee1c-4334-90af-9edeb4e1dfca.png)

### Expected behavior

`OperatingSystem.IsLinux()` should always return true when runing on WSL2

### Actual behavior

![image](https://user-images.githubusercontent.com/6965758/229694176-6ca58679-dad7-4eca-a354-96d0e98caf3f.png)

### Configuration

WSL2:
$ uname -a
Linux DESKTOP-B1234K 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
$ dotnet --list-runtimes
Microsoft.NETCore.App 6.0.15 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Windows(which build and publish the console app):
Win10 22H2 19045.2788
PS Z:\> dotnet --list-sdks
7.0.100 [C:\Program Files\dotnet\sdk]
7.0.104 [C:\Program Files\dotnet\sdk]
7.0.202 [C:\Program Files\dotnet\sdk]

**Comment by zwcloud** [comment]
Also tried `RuntimeInformation.IsOSPlatform(OSPlatform.Linux)`, the behavior is identical and incorrect.

**Comment by hez2010** [comment]
It is expected because you are running .exe file in WSL, which will be handled by Windows, not Linux.
