### ISSUE TITLE
Can not access GlobalSystemMediaTransportControlsSessionManager in Windows 11 while running as service

### ISSUE THREAD

**Issue by Seraksab** [dotnet/runtime#84293]
### Description

Accessing the `GlobalSystemMediaTransportControlsSessionManager` from a .NET application in Windows 11 results in an error when running in a service.

### Reproduction Steps

Program.cs:
```
using Windows.Media.Control;

try
{
  var sm = await GlobalSystemMediaTransportControlsSessionManager.RequestAsync();
  var mediaProps = await sm.GetCurrentSession().TryGetMediaPropertiesAsync();
  File.AppendAllText("C:/dev/winrttest/log.txt", $"{mediaProps?.Title}\n");
}
catch (Exception e)
{
  File.AppendAllText("C:/dev/winrttest/log.txt", $"{e.Message}\n{e.StackTrace}\n");
}
```

.csproj:
```
<Project Sdk="Microsoft.NET.Sdk">    
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net7.0-windows10.0.22000.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
</Project>
```

Publish and register as service:
```
dotnet publish .\winrttest\ -c Debug -r win-x64 -f net7.0-windows10.0.22000.0 -o C:/dev/winrttest --no-self-contained
.\sc.exe create testservice binpath="C:/dev/winrttest/winrttest.exe"
```

### Expected behavior

The title of the current media session should be written to the `log.txt` file

### Actual behavior

The following error is logged instead:
```
The specified service does not exist as an installed service. (0x80070424)
   at Program.<Main>$(String[] args) in C:\dev\winrttest\Program.cs:line 5
```

### Regression?

This only occurs while running in a service in Windows 11. 
Manually starting the published `winrttest.exe` from console works fine. Running as a service works fine in Windows 10 as well.

### Configuration

Tested on both .NET 6 and .NET 7 for win-x64

**Comment by ericstj** [comment]
Looks like this is feedback for Windows owners of the `GlobalSystemMediaTransportControlsSessionManager` API.   I'll see if I can find out how to report that issue.

**Comment by ericstj** [comment]
You don't actually need to run as a service.  Running as `SYSTEM` is good enough to repro and easier to debug.  You can use `psexec -sid` to launch the debugger under `SYSTEM` and this repros with simple console app.

Here's some interesting debug-spew during the failure:
```
onecore\com\combase\dcomrem\resolver.cxx(2211)\combase.dll!00007FFF6C700D20: (caller: 00007FFF6C786FE2) ReturnHr(1) tid(7484) 80070424 The specified service does not exist as an installed service.
onecore\com\combase\dcomrem\resolver.cxx(2414)\combase.dll!00007FFF6C78700A: (caller: 00007FFF6C6EB9F8) ReturnHr(2) tid(7484) 80070424 The specified service does not exist as an installed service.
avcore\playto\globalsmtcsessionmanager\lib\smtcsessionmanager.cpp(42)\Windows.Media.MediaControl.dll!00007FFF3E4A7C48: (caller: 00007FFF3E4A0A4E) ReturnHr(1) tid(7484) 80070424 The specified service does not exist as an installed service.
```

I think you'll need to follow up with the WinRT API owners on this.  I'd recommend finding a channel for engagement here: https://developer.microsoft.com/en-us/windows/support/?tabs=Contact-us

**Comment by Seraksab** [comment]
Just in case someone else runs into the same problem and finds this issue:

Turns out this issue is due to a change in Windows 11. 
Universal Windows Platform (UWP) APIs are no longer supported when running in a non-interactive session (so as a service or as SYSTEM).

https://learn.microsoft.com/en-us/answers/questions/1263190/can-not-access-globalsystemmediatransportcontrolss
