### ISSUE TITLE
Improvement for library tests summary 

### ISSUE THREAD

**Issue by LeVladIonescu** [dotnet/runtime#84294]
### Problem
Currently, passed tests are not shown in the summary. It would make it clearer if a field regarding passed tests is shown.

#### Current test summary
=== TEST EXECUTION SUMMARY ===
     System.Runtime.Serialization.Json.Tests  Total: 171, Errors: 0, Failed: 0, Skipped: 0, Time: 0.777s

#### Proposal
=== TEST EXECUTION SUMMARY ===
     System.Runtime.Serialization.Json.Tests  Total: 171, Passed: 171, Errors: 0, Failed: 0, Skipped: 0, Time: 0.777s

**Comment by stephentoub** [comment]
This comes directly from xunit:
https://github.com/xunit/xunit/blob/1892224c60f8499b42ee1d8a521d65995ef32aea/src/xunit.runner.utility/Reporters/DefaultRunnerReporterMessageHandler.cs#L339-L369
I don't think this is actionable in this repo.

**Comment by kotlarmilos** [comment]
Thanks @stephentoub! 

@LeVladIonescu I suggest transferring the issue to https://github.com/xunit/xunit and closing this one.
