### ISSUE TITLE
WASI app always tries to load icudt.dat from disk

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/runtime#84310]
### Description

A default app created using the `wasiconsole` template from the new `wasi-experimental` workload can only run with disk access. Without disk access, it fails with:

```
Failed to load ./icudt.dat
```

This appears to be the case regardless of setting `<InvariantGlobalization>true</InvariantGlobalization>` in the csproj.

The drawback of this is that it prevents single-file deployment or running in any environment that doesn't allow access to arbitrary files on disk.

### Reproduction Steps

* `dotnet new wasiconsole`
* `dotnet build /p:WasmSingleFileBundle=true`
* `wasmtime bin\Debug\net8.0\wasi-wasm\AppBundle\MyApp.wasm`

### Expected behavior

The `icudt.dat` file:

 * Should not be required at all if `InvariantGlobalization` is true on build
 * Should be bundled into the `.wasm` file otherwise

... so in both cases, a default "hello world" app should be able to run without disk access.

### Actual behavior

`Failed to load ./icudt.dat`

**Comment by pavelsavara** [comment]
cc @ilonatommy @mkhamoyan

**Comment by mkhamoyan** [comment]
> cc @ilonatommy @mkhamoyan

As per discussion here @radical implemented it, but looks like it was not merged yet. If I'm not mistaken implementation is under this PR https://github.com/dotnet/runtime/pull/83496

**Comment by radical** [comment]
> > cc @ilonatommy @mkhamoyan
> 
> As per discussion [here](https://github.com/dotnet/runtime/issues/82895) @radical implemented it, but looks like it was not merged yet. If I'm not mistaken implementation is under this PR #83496

Yep. I should be able to revive this in the next couple of weeks.

**Comment by pavelsavara** [comment]
I stolen pieces of @radical's code and split smaller PR https://github.com/dotnet/runtime/pull/85049
