### ISSUE TITLE
Arm64: Use VectorTableLookup/VectorTableLookupExtension APIs in libraries

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#84328]
https://github.com/dotnet/runtime/pull/80297 added support for Arm64's `VectorTableLookup` and `VectorTableLookupExtension` APIs. We should start using them in libraries methods.

**Comment by a74nh** [comment]
Looking through the libraries the current uses of shuffle/vectortablelookup can be improved:


System.Private.CoreLib/src/System/IndexOfAnyValues/ProbabilisticMap.cs
- Two consecutive shuffles can be combined into a vectorlookup2.

System.Private.CoreLib/src/System/IndexOfAnyValues/IndexOfAnyAsciiSearcher.cs
- Can combine shuffles, but only the instances where there are two bitmaps in a single function.

System.Private.CoreLib/src/System/Buffers/Text/Utf8Formatter/Utf8Formatter.Guid.cs
- Should be able to turn vector z into a single vectorlookup2.
 
System.Private.CoreLib/src/System/Buffers/Binary/BinaryPrimitives.ReverseEndianness.cs
System.Private.CoreLib/src/System/SpanHelpers.Byte.cs
System.Private.CoreLib/src/System/SpanHelpers.cs
Common/src/System/HexConverter.cs
System.IO.Hashing/src/System/IO/Hashing/XxHashShared.cs
- Technically out of scope of this issue, but these are all using hardcoded index values, so can switch from shuffle to shuffleunsafe.
 
EncodeToUtf8.cs
DecodeFromUtf8.cs
- Once LD4 and ST3 available, then they can be rewritten to use to vectortablelookup2.
 
There may be additional things, but these were the obvious ones.

**Comment by MihaZupan** [comment]
> System.Private.CoreLib/src/System/IndexOfAnyValues/IndexOfAnyAsciiSearcher.cs
> - Can combine shuffles, but only the instances where there are two bitmaps in a single function.

Do you mean
https://github.com/dotnet/runtime/blob/4ebecb0f69015544c09832558467135afa048fa3/src/libraries/System.Private.CoreLib/src/System/IndexOfAnyValues/IndexOfAnyAsciiSearcher.cs#L912-L920
?
Which operations would you combine here?

**Comment by kunalspathak** [comment]
@JulieLeeMSFT - FYI.

**Comment by a74nh** [comment]
> Do you mean
> 
> https://github.com/dotnet/runtime/blob/4ebecb0f69015544c09832558467135afa048fa3/src/libraries/System.Private.CoreLib/src/System/IndexOfAnyValues/IndexOfAnyAsciiSearcher.cs#L912-L920
> 
> 
> ?
> Which operations would you combine here?

Unless there's something I'm missing, bitsets can be created just via:
Vector128<byte> bitsets =  AdvSimd.VectorTableLookup2(bitmapLookup0, bitmapLookup1, lowNibbles);

**Comment by SwapnilGaikwad** [comment]
> System.Private.CoreLib/src/System/Buffers/Binary/BinaryPrimitives.ReverseEndianness.cs 
> System.Private.CoreLib/src/System/SpanHelpers.Byte.cs
> System.Private.CoreLib/src/System/SpanHelpers.cs
> Common/src/System/HexConverter.cs
> System.IO.Hashing/src/System/IO/Hashing/XxHashShared.cs
> 
>     * Technically out of scope of this issue, but these are all using hardcoded index values, so can switch from shuffle to shuffleunsafe.

For these cases, changing from `Shuffle` to `ShuffleUnsafe` would not give any performance improvements.
When the indices are hardcoded, they get optimised during the importation phase and avoid the bounds check logic. Therefore, we get the same JIT-ed assembly sequence.

Even when the indices are out of the bounds of the vector, if the positions vector is hard-coded then the overhead of bounds-check is avoided with the shuffle.
In the following example, the index for the first position is `25` so with `Vector128.Shuffle` we expect value `0` in `dest[0]` but with `Ssse3.Shuffle` we expect value `src[9]` (25%16=9).

`Vector128.Shuffle(sourceVec, Vector128.Create((byte)25, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0));`

Instead of getting a bounds check, after the importation phase, we see an updated index `FF` for the first position that would set value `0` in `dest[0]`.
With `Vector128.ShuffleUnsafe` we get index `19` instead.

```
; Assembly listing for method System.Text.Tests.ShuffleUnsafeTest:ReverseWithShuffle(byref,ulong)
; Emitting BLENDED_CODE for X64 CPU with AVX512 - Unix
; optimized code
; rsp based frame
; partially interruptible
; No PGO data
; Final local variable assignments
;
;  V00 arg0         [V00,T00] (  4,  4   )   byref  ->  rdi         single-def
;* V01 arg1         [V01    ] (  0,  0   )    long  ->  zero-ref    single-def
;# V02 OutArgs      [V02    ] (  1,  1   )  struct ( 0) [rsp+00H]   do-not-enreg[XS] addr-exposed "OutgoingArgSpace"
;  V03 tmp1         [V03,T01] (  2,  4   )  simd16  ->  mm0         "Spilling op1 side effects for HWIntrinsic"
;
; Lcl frame size = 0

G_M46485_IG01:  ;; offset=0000H
       vzeroupper
                        ;; size=3 bbWeight=1 PerfScore 1.00
G_M46485_IG02:  ;; offset=0003H
       vmovups  xmm0, xmmword ptr [rdi]
       vpshufb  xmm0, xmm0, xmmword ptr [reloc @RWD00]
       vmovups  xmmword ptr [rdi], xmm0
                        ;; size=17 bbWeight=1 PerfScore 8.00
G_M46485_IG03:  ;; offset=0014H
       ret
                        ;; size=1 bbWeight=1 PerfScore 1.00
RWD00   dq  08090A0B0C0D0EFFh, 0001020304050607h


```



<details>
<summary>Assembly for `Vector128.ShuffleUnsafe(sourceVec, Vector128.Create((byte)25, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0));`.</summary>

```
; Assembly listing for method System.Text.Tests.ShuffleUnsafeTest:ReverseWithShuffleUnsafe(byref,ulong)
; Emitting BLENDED_CODE for X64 CPU with AVX512 - Unix
; optimized code
; rsp based frame
; partially interruptible
; No PGO data
; 0 inlinees with PGO data; 0 single block inlinees; 1 inlinees without PGO data
; Final local variable assignments
;
;  V00 arg0         [V00,T00] (  4,  4   )   byref  ->  rdi         single-def
;* V01 arg1         [V01    ] (  0,  0   )    long  ->  zero-ref    single-def
;# V02 OutArgs      [V02    ] (  1,  1   )  struct ( 0) [rsp+00H]   do-not-enreg[XS] addr-exposed "OutgoingArgSpace"
;  V03 tmp1         [V03,T01] (  2,  4   )  simd16  ->  mm0         "Spilling op1 side effects for HWIntrinsic"
;* V04 tmp2         [V04    ] (  0,  0   )  simd16  ->  zero-ref    "Inlining Arg"
;
; Lcl frame size = 0

G_M34751_IG01:  ;; offset=0000H
       vzeroupper
                        ;; size=3 bbWeight=1 PerfScore 1.00
G_M34751_IG02:  ;; offset=0003H
       vmovups  xmm0, xmmword ptr [rdi]
       vpshufb  xmm0, xmm0, xmmword ptr [reloc @RWD00]
       vmovups  xmmword ptr [rdi], xmm0
                        ;; size=17 bbWeight=1 PerfScore 8.00
G_M34751_IG03:  ;; offset=0014H
       ret
                        ;; size=1 bbWeight=1 PerfScore 1.00
RWD00   dq  08090A0B0C0D0E19h, 0001020304050607h


; Total bytes of code 21, prolog size 3, PerfScore 12.10, instruction count 5, allocated bytes for code 21 (MethodHash=64be7840) for method System.Text.Tests.ShuffleUnsafeTest:ReverseWithShuffleUnsafe(byref,ulong)
; ============================================================
```
</details>

**Comment by kunalspathak** [comment]
This was completed in https://github.com/dotnet/runtime/pull/87126. If there are more instances in BCL that can benefit from VectorTableLookup, we can have a separate issue for them.
