### ISSUE TITLE
Wasm.Build.Tests.Blazor.MiscTests.DefaultTemplate_AOT_InProjectFile Test failed

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#84368]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=228059
Build error leg or test failing: Wasm.Build.Tests.Blazor.MiscTests.DefaultTemplate_AOT_InProjectFile
Pull request: https://github.com/dotnet/runtime/pull/84271

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Microsoft.JSInterop.WebAssembly.dll.bc",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by lewing** [comment]
The installer pr has landed so this should go away once a new installer is publihed to the feed

**Comment by maraf** [comment]
It already passed on https://dev.azure.com/dnceng-public/public/_build/results?buildId=234179&view=results
