### ISSUE TITLE
[NativeAOT] Optimize the access pattern to threadstatics.

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#84373]
Prior to implementing JIT inlining of threadstatic access, it makes sense to simplify the access pattern. 

There could be some opportunities. For example we may not need per-module indirection.
Re: https://github.com/dotnet/runtime/pull/82973#issuecomment-1497682112

**Comment by VSadov** [comment]
According to @MichalStrehovsky multimodule scenario is not something that is commonly used, but it is functional and it may make sense to not break it, if possible.

**Comment by jkotas** [comment]
The multimodule scenario leaves performance on the table in general. It is ok to use a slow helper for it if we want to keep it working.

We should focus on optimizing the thread-static access pattern for the single module case with assumption that the JIT can help by inlining it. How far do you think it makes to push it? Should we push it to be as efficient as thread statics in C where possible (non-GC non-generic statics)?

**Comment by VSadov** [comment]
> Should we push it to be as efficient as thread statics in C where possible (non-GC non-generic statics)?

C threadstatic can be very efficient. Here is the access to the current thread in the native code:

```c
    Thread * pThread = ThreadStore::GetCurrentThread();
00007FF7BAB06FD2  mov         edx,dword ptr [_tls_index (07FF7BACB2B48h)]  
00007FF7BAB06FD8  mov         rax,qword ptr gs:[58h]  
00007FF7BAB06FE1  mov         ebx,10h  
00007FF7BAB06FE6  add         rbx,qword ptr [rax+rdx*8]  
```

This is basically getting native thread static `tls_CurrentThread`. There is nothing dynamic about `tls_CurrentThread`, apart from threads being created/destroyed dynamically. Indirection off `gs` handles that. 
(on other platforms it will be `x18`, `TPIDR_EL0` or similar)

I think we can have this for unmanaged threadstatics only if we emit unmanaged threadstatics in the same way as C and let the C runtime manage them. It would be attractive for threadstatics such as managed thread ID.
I have no idea if that is feasible. This is beyond my understanding how things are described in the obj files and presented to the native linker.

Managed and dynamic threadstatics will need something similar to what we have now, but I think we can reduce number of indirections. If the above is too hard or fragile, then unmanaged stuff could be on the same plan as managed.

**Comment by VSadov** [comment]
in a first approximation I'd have two slots on the native thread instance:
- one "static" slot for a combo instance that covers nondynamic module0 threadstatics. Not sure if it needs to be lazy. Perhaps we can just set it up right away on thread attach.
JIT would inline the access to this. There is nothing to check or call, if we allocate the store eagerly. 
It will be the sequence like in C++ with one additional indirection to get the `ref` to the per-type store. 

- and another "dynamic" slot that would be on the same plan as it is now - to handle multiple modules and dynamic types. It can be as lazy as what we have now. Access to it may not be inlined by the JIT

The tricky part about "combo" instance is that `GetThreadStaticBaseForType` would need to be changed to return `ref` to the per-type store. 
The location could be computed from `typeTlsIndex` as we know per-type store sizes, but it would be more efficient for the non-dynamic case to operate in terms of something like `typeTlsOffset`.

**Comment by VSadov** [comment]
CC: @kunalspathak

**Comment by VSadov** [comment]
> There is nothing to check or call, if we allocate the store eagerly.

Actually, code does not know statically if it is in module0, so we will need one check. Either for the module number==0 or whether there are multiple modules.

**Comment by jkotas** [comment]
The compiler knows whether it is emitting multi-module code (`--multifile` switch).

**Comment by VSadov** [comment]
> The compiler knows whether it is emitting multi-module code (--multifile switch).

That is good! Then we can tell the jit to just call the helper.

**Comment by VSadov** [comment]
Note that we have two helpers:
- GetThreadStaticBaseForType   (C#) 
- RhpGetThreadStaticBaseForType  (asm)  - only called in nongeneric case.

The reason we have `RhpGetThreadStaticBaseForType` is really just to do INLINE_GETTHREAD, so we do not need to make yet another call to fetch the native TLS. 

My plan is to simplify the storage how we can, which should result in simpler asm helper for the fast path.

As the next step @kunalspathak will teach JIT to just inline that piece of asm, so that `RhpGetThreadStaticBaseForType` no longer needed.

**Comment by VSadov** [comment]
An initial implementation of simpler access to threadstatics - https://github.com/dotnet/runtime/pull/84566

It separates the fast "inlineable" case from multimodule/dynamic case and preinitializes the storage, so that the asm helper does not need to check for anything or call anything.

It does not yet introduce a "combo" instance. It looks like that could require some changes in how JIT deals with threadstatics - i.e. the helper would return a `ref`, not an `object`. 
Not sure yet how disruptive such change could be.
