### ISSUE TITLE
dynamic with RuntimeBinder.RuntimeBinderException

### ISSUE THREAD

**Issue by guangzhengli** [dotnet/runtime#84406]
### Description

.netframework or .net core get dynamic object from .netstandard2.0 method return dynamic object throw RuntimeBinder.RuntimeBinderException.

### Reproduction Steps

The way to reproduce this issue is to use .NET Framework to call a method in .NET Standard 2.0 that returns an object of dynamic type, which cannot be properly resolved by the .NET Framework.

code in .netstandard2.0 project:

```csharp
public static class StandardClass
    {
        public static dynamic Get()
        {
            return new { prop1 = "hello", prop2 = 12 };
        }
    }
```

code in .netframework project:

```csharp
internal class Program
    {
        public static void Main(string[] args)
        {
            try
            {
                var test = StandardClass.Get();
                var props = test.GetType().GetProperties();
                var prop1 = test.prop1;
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }
    }
```

At this point, the code will throw an exception and the exception message is:

```csharp
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'object' does not contain a definition for 'prop1'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
```

But if we move the StandardClass Get() method to .netframework Program, the dynamic object can be resolved normally. 

### Expected behavior

no error.

### Actual behavior

Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'object' does not contain a definition for 'prop1'

### Regression?

.NET Framework / .NET Core

**Comment by huoyaoyuan** [comment]
Could you clarify on which combination of platforms (.NET Standard/.NET Framework/.NET Core) this issue reproduces in a table?

**Comment by guangzhengli** [comment]
StandardClass.cs in the .NET Standard project, Program.cs can use .NET Framework or .NET Core project

**Comment by hippieZhou** [comment]
Because the anonymous type is generated as `internal` level, so the binder doesn't really "know" about it's props. we can 

- use `ExpandoObject` as return type
- or add `InternalsVisibleTo` property in `*.csproj` as follows:

```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>default</LangVersion>
    </PropertyGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="ConsoleApp1" />
    </ItemGroup>
</Project>
```

the reference is here：[C# ‘dynamic’ cannot access properties from anonymous types declared in another assembly](https://stackoverflow.com/questions/2630370/c-sharp-dynamic-cannot-access-properties-from-anonymous-types-declared-in-anot)

**Comment by guangzhengli** [comment]
Thanks. Best wishes!
