### ISSUE TITLE
[ppc64le] Common.Tests and more tests are failing for missing opcode 'rcompare' on Power.

### ISSUE THREAD

**Issue by vikasgupta8** [dotnet/runtime#84401]
### Description

The Common.Tests and more tests are failing in [CI pipeline](https://dev.azure.com/dnceng-public/public/_build/results?buildId=226542&view=logs&j=afa9e9c9-0835-5e87-9576-859a0f7dc04f&t=06e5c6f9-c6d6-516b-3325-4576fe8baba2) with below error.

`Opcode 'rcompare' missing from machine description file.`

**Detail:**

```
Console log: 'Common.Tests' from job eeb16027-4beb-4fd6-90c3-c27927786054 workitem 3bb2a0bd-4359-40c1-a4a4-5b0a495474d9 (ubuntu.2004.ppc64le.experimental.open) executed on machine dotnet-2 running Linux-5.4.0-146-generic-ppc64le-with-glibc2.29
+ ./RunTests.sh --runtime-path /home/helixbot/work/B37C091D/p
----- start Mon 03 Apr 2023 07:23:20 PM UTC =============== To repro directly: =====================================================
pushd .
/home/helixbot/work/B37C091D/p/dotnet exec --runtimeconfig Common.Tests.runtimeconfig.json --depsfile Common.Tests.deps.json xunit.console.dll Common.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
~/work/B37C091D/w/AE690932/e ~/work/B37C091D/w/AE690932/e
Opcode 'rcompare' missing from machine description file.

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x7da4716ba2a8 - Unknown
	0x7da47166884c - Unknown
	0x7da4716b9768 - Unknown
	0x7da4721804c8 - Unknown
	0x7da471aed168 - Unknown
	0x7da471ac4850 - Unknown
```

### Reproduction Steps

Run the runtime testcases.

### Expected behavior

All the tests should pass without any failure or crash.

### Actual behavior

Tests are failing with crash due to missing opcode 'rcompare'.

**Comment by Sapana-Khemkar** [comment]
@vargaz  We have noticed that these tests are failing after https://github.com/dotnet/runtime/pull/82005 is merged.
I can see opcode rcompare is not implemented for power. I am trying to understand why your changes triggered. Can you please help me understanding this.

**Comment by vikasgupta8** [comment]
Hi @vargaz , I could see [pipeline build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=231207&view=logs&j=afa9e9c9-0835-5e87-9576-859a0f7dc04f&t=2878655b-c85f-5fae-0348-e7dcf636ea1a) is failing with below error after reverting part of https://github.com/dotnet/runtime/pull/82005

```
[ 83%] Building C object mono/mini/CMakeFiles/monosgen-objects.dir/seq-points.c.o

/__w/1/s/src/mono/mono/mini/mini.c:3141:13: error: use of undeclared identifier 'llvm'

g_assert (!llvm);

^
```

I could see the change `assert(!llvm)` was not there earlier. Could you please check.




```
#ifdef MONO_ARCH_FLOAT32_SUPPORTED
	/* Force float32 mode on platforms where its supported */
	opts |= MONO_OPT_FLOAT32;
#else
	opts &= ~MONO_OPT_FLOAT32;
	**g_assert (!llvm);**
#endif
```

**Comment by vargaz** [comment]
Should be fixed now.

**Comment by vikasgupta8** [comment]
llvm issue is fixed in https://github.com/dotnet/runtime/pull/84473/files
