### ISSUE TITLE
CctorForWrite failing with NativeAOT

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#84400]
This:

https://github.com/dotnet/runtime/blob/e45e5db94b3c7847d5d11cb20c8e2768dc92c040/src/tests/Loader/classloader/TypeInitialization/CctorsWithSideEffects/CctorForWrite.cs#L22-L25

Gets generated as:

```
13:     public static int Main()
    14:     {
00007FF635E301F0 55                   push        rbp  
00007FF635E301F1 56                   push        rsi  
00007FF635E301F2 48 83 EC 28          sub         rsp,28h  
00007FF635E301F6 48 8D 6C 24 30       lea         rbp,[rsp+30h]  
    15:         try
    16:         {
    17:             ClassWithCctor.StaticField = Call();
00007FF635E301FB E8 3A 0E E4 FF       call        __GetNonGCStaticBase_repro_ClassWithCctor (07FF635C7103Ah)  
00007FF635E30200 48 8B F0             mov         rsi,rax  
00007FF635E30203 E8 B8 FF FF FF       call        repro_CCC__Call (07FF635E301C0h)  
00007FF635E30208 89 06                mov         dword ptr [rsi],eax  
    22:         }
    
```

Notice we grab the cctor base before the call, hitting exactly what the test is testing we shouldn't be doing.

Not sure what effect #83911 is going to have on this, but it's failing right now. I'm surprised we're not seeing it in ReadyToRun testing because this is a ReadyToRun pattern. (We're not seeing this in NativeAOT testing because we're still in the process of standing up these tests in regular testing.)

Cc @markples

**Comment by markples** [comment]
R2R issue for this is #84007

**Comment by MichalStrehovsky** [comment]
> R2R issue for this is #84007

Oh, I did see the test was introduced in a PR from January but I thought we would have dealt with a possible R2R issue in the 3 months since then. I didn't realize the January PR only merged last week. It's probably a dupe of the R2R issue.
