### ISSUE TITLE
[API Proposal]: Add `ArgumentOutOfRangeException.ThrowIfNotZero`

### ISSUE THREAD

**Issue by xtqqczze** [dotnet/runtime#84415]
### Background and motivation

We already have `ArgumentOutOfRangeException.ThrowIfZero`.

### API Proposal

```csharp
public class ArgumentOutOfRangeException : ArgumentException
{
  public static void ThrowIfZero<T>(T value, [CallerArgumentExpression(nameof(value))] string? paramName = null)
    where T : INumberBase<T>
  {
    if (!T.IsZero(value))
      ThrowNotZero(paramName, value);
  }
}
```

### API Usage

```csharp
internal sealed class SingleItemReadOnlyList : IList
{
  private readonly object? _item;
  
  public SingleItemReadOnlyList(object? item) => _item = item;
  
  public object? this[int index]
  {
    get
    {
      ArgumentOutOfRangeException.ThrowIfNotZero(index);
      return _item;
    }
  }
}
```

**Comment by stephentoub** [comment]
Is this really common enough that ThrowIfEqual(..., 0) is insufficient?

**Comment by RenderMichael** [comment]
If the argument cannot be anything other than `INumberBase<TSelf>.Zero`, why would you need it as a parameter?

**Comment by tannergooding** [comment]
I use it in TerraFX for 4 places. Those specifically involve cases like `public UnmanagedSpan(UnmanagedArray<T> array, nuint start)` where if `array` is "null", then `start` must be `0`. Any other input for `start` is likely a developer error.

This is a very niche scenario and easily covered by `ThrowIfNotEqual(x, 0)`

**Comment by Sergio0694** [comment]
Same for me, I only use it in very few cases. For me it's just 2 cases in all of ComputeSharp (specifically in two custom `MemoryManager<T>` implementations that require the `elementIndex` parameter passed to `Pin` to always be `0`.

I agree this it's a critical feature to add (plus people can easily add this by using a static extension in C# 12).
Not saying we necessarily _shouldn't_ add it, just that I agree its use cases would be pretty limited.

**Comment by stephentoub** [comment]
Closing for the reasons cited.
