### ISSUE TITLE
[API Proposal]: Add StructuredLoggingFormat to StringSyntaxAttribute

### ISSUE THREAD

**Issue by ristogod** [dotnet/runtime#84423]
When I use a `Microsoft.Extensions.Logging.ILogger` instance in my code, I get tooling support that recognizes the format for the message, that normally looks like this:

``` csharp
_logger.LogError("Account {AccountId} has received an invalid value of {Value}", accountId, value);
```

The tooling recognizes the pattern of the message appropriately.

Our business framework has our own `ILogger` implementations that wrap `Microsoft.Extensions.Logging.ILogger`. We would like the same tooling support on our Log methods.

This was attempted:

``` csharp
void LogError([StringSyntax(StringSyntaxAttribute.CompositeFormat)] string message, params object?[] args);
```

However, the tooling does not recognize that in the same way as it does for `Microsoft.Extensions.Logging.ILogger` formatting. Instead it suggests that `{0}` and `{1}` should be used instead.

I suggest the addition of a `StringSyntax.StructuredLoggingFormat` value be added, so the tooling can implement around this.

**Comment by tarekgh** [comment]
What tooling is used here and how is it going to handle `StringSyntax.StructuredLoggingFormat`?
