### ISSUE TITLE
[NETSDKE2E] With .NET 8.0 Preview4, debugging does not work normally on Mac X64

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/runtime#84466]
### Description

With .NET 8.0 Preview4, debugging does not work normally on Mac X64

### Reproduction Steps

1.VSCode: Install version 1.77.1:https://code.visualstudio.com/download
2.Install C# extension 1.25.5 : https://github.com/OmniSharp/omnisharp-vscode/releases/
3.Install SDK:.NET 8.0.100-preview.4.23205.4 (runtime- 8.0.0-preview.4.23181.2):[GitHub - dotnet/installer: .NET SDK Installer](https://github.com/dotnet/installer)
4.Create a new project via CLI (For example: Console).
5.Open the project in VSCode and hit F5.

dotnet --info:
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/99376012/230523811-70db4bab-65b3-4076-b05b-c663145fe24b.png)

### Expected behavior

Debugging works fine and see "Hello,World!"
![MicrosoftTeams-image3](https://user-images.githubusercontent.com/99376012/230522907-6416aff3-a106-415a-ab81-0956d652bed9.png)

### Actual behavior

Debugging could not be finished normally, could not see "Hello, World!"
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/99376012/230521777-ea13b1a7-6e19-42a0-9601-04e1655753dd.png)

### Regression?

Yes. This issue is not repro with .NET 8 Preview3, Preview2

### Configuration

Version: .NET 8.0.100-preview.4.23205.4 (runtime- 8.0.0-preview.4.23181.2)
OS: Big Sur(11.7.5), Ventura(13.3)
Architecture: Mac X64
This issue is only repro on Mac X64, not repro on Mac M1 and Windows.

### Other information

-->The OmniSharp Log:
[OmniSharpLog.txt](https://github.com/dotnet/runtime/files/11175425/OmniSharpLog.txt)

**Comment by ChenhuiYuan01** [comment]
Also reported on Linux
![image](https://user-images.githubusercontent.com/92560562/230565650-69741131-f219-417b-9234-1eb84c7500f7.png)

**Comment by jeffschwMSFT** [comment]
@tommcdon can you take a look?
