### ISSUE TITLE
[mono][tests] Hybrid.WASM.Tests SIGSEGV failure on iOS

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#84477]
The issue has been encountered on two separate PRs.
 - https://github.com/dotnet/runtime/pull/84304
 - https://github.com/dotnet/runtime/pull/79169

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=231297
Build error leg or test failing: Hybrid.WASM.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/79169

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "(NETCORE_ENGINEERING_TELEMETRY=Test) Work item Hybrid.WASM.Tests in job",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[234114](https://dev.azure.com/dnceng-public/public/_build/results?buildId=234114)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/234114/logs/700)|dotnet/runtime#84552|
|[233539](https://dev.azure.com/dnceng-public/public/_build/results?buildId=233539)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/233539/logs/828)|dotnet/runtime#84552|
|[233540](https://dev.azure.com/dnceng-public/public/_build/results?buildId=233540)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/233540/logs/946)||
|[233505](https://dev.azure.com/dnceng-public/public/_build/results?buildId=233505)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/233505/logs/1799)|dotnet/runtime#84148|
|[233492](https://dev.azure.com/dnceng-public/public/_build/results?buildId=233492)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/233492/logs/1158)|dotnet/runtime#82773|
|[233240](https://dev.azure.com/dnceng-public/public/_build/results?buildId=233240)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/233240/logs/2047)|dotnet/runtime#84148|
|[233074](https://dev.azure.com/dnceng-public/public/_build/results?buildId=233074)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/233074/logs/923)||
|[233000](https://dev.azure.com/dnceng-public/public/_build/results?buildId=233000)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/233000/logs/1502)|dotnet/runtime#82973|
|[232973](https://dev.azure.com/dnceng-public/public/_build/results?buildId=232973)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/232973/logs/864)|dotnet/runtime#84552|
|[232933](https://dev.azure.com/dnceng-public/public/_build/results?buildId=232933)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/232933/logs/909)||
|[232836](https://dev.azure.com/dnceng-public/public/_build/results?buildId=232836)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/232836/logs/1459)|dotnet/runtime#82973|
|[232774](https://dev.azure.com/dnceng-public/public/_build/results?buildId=232774)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/232774/logs/636)|dotnet/runtime#84318|
|[232731](https://dev.azure.com/dnceng-public/public/_build/results?buildId=232731)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/232731/logs/913)||
|[232568](https://dev.azure.com/dnceng-public/public/_build/results?buildId=232568)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/232568/logs/1526)|dotnet/runtime#82973|
|[232561](https://dev.azure.com/dnceng-public/public/_build/results?buildId=232561)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/232561/logs/911)||
|[232430](https://dev.azure.com/dnceng-public/public/_build/results?buildId=232430)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/232430/logs/43)|dotnet/runtime#79169|
|[232429](https://dev.azure.com/dnceng-public/public/_build/results?buildId=232429)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/232429/logs/47)|dotnet/runtime#79169|
|[232401](https://dev.azure.com/dnceng-public/public/_build/results?buildId=232401)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/232401/logs/917)||
|[232375](https://dev.azure.com/dnceng-public/public/_build/results?buildId=232375)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/232375/logs/553)|dotnet/runtime#83151|
|[232270](https://dev.azure.com/dnceng-public/public/_build/results?buildId=232270)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/232270/logs/2166)|dotnet/runtime#84148|
|[231952](https://dev.azure.com/dnceng-public/public/_build/results?buildId=231952)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/231952/logs/922)||
|[231848](https://dev.azure.com/dnceng-public/public/_build/results?buildId=231848)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/231848/logs/1174)|dotnet/runtime#82773|
|[231601](https://dev.azure.com/dnceng-public/public/_build/results?buildId=231601)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/231601/logs/553)|dotnet/runtime#83151|
|[231490](https://dev.azure.com/dnceng-public/public/_build/results?buildId=231490)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/231490/logs/552)|dotnet/runtime#84330|
|[231297](https://dev.azure.com/dnceng-public/public/_build/results?buildId=231297)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/231297/logs/46)|dotnet/runtime#79169|
|[231259](https://dev.azure.com/dnceng-public/public/_build/results?buildId=231259)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/231259/logs/914)||
|[231230](https://dev.azure.com/dnceng-public/public/_build/results?buildId=231230)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/231230/logs/553)|dotnet/runtime#83151|
|[230666](https://dev.azure.com/dnceng-public/public/_build/results?buildId=230666)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/230666/logs/1158)||
|[230845](https://dev.azure.com/dnceng-public/public/_build/results?buildId=230845)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/230845/logs/1495)|dotnet/runtime#84453|
|[230873](https://dev.azure.com/dnceng-public/public/_build/results?buildId=230873)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/230873/logs/1159)|dotnet/runtime#82773|
|[230424](https://dev.azure.com/dnceng-public/public/_build/results?buildId=230424)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/230424/logs/42)||
|[230266](https://dev.azure.com/dnceng-public/public/_build/results?buildId=230266)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/230266/logs/42)|dotnet/runtime#79169|
|[230264](https://dev.azure.com/dnceng-public/public/_build/results?buildId=230264)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/230264/logs/52)|dotnet/runtime#79169|
|[229837](https://dev.azure.com/dnceng-public/public/_build/results?buildId=229837)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/229837/logs/41)|dotnet/runtime#79169|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|6|34|34|

**Comment by kotlarmilos** [comment]
Interpreter on iOS and tvOS simulators can't find `GlobalizationNative_GetLocaleInfoStringNative` because it is conditionally emitted.

https://github.com/dotnet/runtime/blob/a7f3df9b14d896cda708e2d22f35165737646769/src/native/libs/System.Globalization.Native/pal_locale.m#L33-L52

@ilonatommy @mkhamoyan are there simulator specific targets that could be used? If not, the test could be disabled on the simulators.

**Comment by mkhamoyan** [comment]
> Interpreter on iOS and tvOS simulators can't find `GlobalizationNative_GetLocaleInfoStringNative` because it is conditionally emitted.
> 
> https://github.com/dotnet/runtime/blob/a7f3df9b14d896cda708e2d22f35165737646769/src/native/libs/System.Globalization.Native/pal_locale.m#L33-L52
> 
> @ilonatommy @mkhamoyan are there simulator specific targets that could be used? If not, the test could be disabled on the simulators.

Looks like during wasm tests it also tries to run on ios/tvos platforms. @ilonatommy  We need to run this tests only for wasm/wasi platforms https://github.com/dotnet/runtime/blob/main/src/libraries/System.Globalization/tests/Hybrid/Hybrid.WASM.Tests.csproj , like is done for hybrid ios tests https://github.com/dotnet/runtime/blob/main/src/libraries/System.Globalization/tests/Hybrid/Hybrid.IOS.Tests.csproj
