### ISSUE TITLE
Increased memory consumption after upgrading to .NET 7

### ISSUE THREAD

**Issue by mihaimyh** [dotnet/runtime#84497]
After upgrading my applications to the latest .NET version (7.0.202), I have noticed a significant increase in memory consumption on Linux (RHEL7). Both my apps upgraded to .NET7 are self-contained.

Applying the fix described at https://github.com/dotnet/runtime/issues/79633#issuecomment-1469200172 (setting `DOTNET_GCName=libclrgc.so`) solved my problem and the memory consumption got reduced to the .NET 6 levels.

 Please guide on how to collect traces from RHEL from both my applications I've upgraded.

**Comment by mangod9** [comment]
Could you please try the latest servicing release (7.0.4), and check if that makes things better? 7.0.3 has the fix for #79633.

**Comment by mihaimyh** [comment]
@mangod9 SDK 7.0.202 doesn't included 7.0.4 runtime?

**Comment by mangod9** [comment]
Oh sorry misread that as the runtime version. Yeah SDK 7.0.202 should be the latest. To investigate your issue if you have a standalone repro which shows the working set difference that would be great. Else if you could please collect GC only traces with default and the DOTNET_GCName config, that would help with investigating further. Thx!
