### ISSUE TITLE
[NativeAOT] Mach-O shared library has a hard-coded identification name under LC_ID_DYLIB

### ISSUE THREAD

**Issue by markgomez** [dotnet/runtime#84500]
I'm playing around with NativeAOT in the latest preview (8.0.0-preview.2.23128.3) on Apple silicon and I'm able to successfully call into an AOT compiled .NET library from another C library. An issue arises when I want to have a different run-time search path.

If I use the `-o` flag to change the publish path...

```bash
$ dotnet publish foo -p:NativeLib=shared -r osx-arm64 -c Release -o $HOME/.local/myapp
```

The `.dylib` file ends up in the correct location, but running the app (I'm building a console type app) will result in an error that looks something like this...

```bash
dyld[87366]: Library not loaded: 'bin/Release/net8.0/osx-arm64/native/foo.dylib'
  Referenced from: '/Users/me/projects/myapp/build/config-clang-debug/bin/mylib.dylib'
  Reason: tried: 'bin/Release/net8.0/osx-arm64/native/foo.dylib' (no such file), '/usr/local/lib/foo.dylib' (no such file), '/usr/lib/foo.dylib' (no such file)
```

Inspecting the binary shows a hard-coded default path (despite providing a custom one)...

```bash
$ otool -l $HOME/.local/myapp/foo.dylib
```
```bash
# ...

Load command 4
          cmd LC_ID_DYLIB
      cmdsize 80
         name bin/Release/net8.0/osx-arm64/native/foo.dylib (offset 24)
   time stamp 1 Wed Dec 31 16:00:01 1969
      current version 0.0.0
compatibility version 0.0.0

# ...
```

I incorrectly assumed it would match the value passed to the `-o` parameter. I can manually change the name via `install_name_tool` before linking it to my other C files (or use the `/usr/**/lib` directories), but wanted to know if there are other options that I could try, e.g., property flags that I'm not aware of for enabling the use of `@rpath`, `@executable_path`, etc. (`-p:NativeLib` was the only one mentioned in the [native library sample](https://github.com/dotnet/samples/tree/main/core/nativeaot/NativeLibrary)).

**Comment by agocke** [comment]
Looks like we would need to set RPATH when linking. I'll have to look into if and how we would do that (i.e., what we would set, exactly).

In the meantime, I think you can use `install_name_tool` to change the path.

**Comment by markgomez** [comment]
> In the meantime, I think you can use `install_name_tool` to change the path.

I ended up doing just that via CMake and it works well enough for me:
```cmake
if(CMAKE_SYSTEM_NAME STREQUAL Darwin)
    execute_process(
        COMMAND install_name_tool
        -id "@loader_path/foo.dylib"
        "${lib_output_dir}/foo.dylib"
    )
endif()
```

In any case, this is all super exciting stuff. Great work on NativeAOT!

**Comment by MichalStrehovsky** [comment]
We unconditionally set rpath to this:

https://github.com/dotnet/runtime/blob/1487522704c23df9b7aef2a48874c38a1345bfaa/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Unix.targets#L48

Maybe we shouldn't set it when making a shared library? Or use `@loader_path`?

**Comment by markgomez** [comment]
Thanks for pointing that line out. In my case, I think `@executable_path` still would've broken my installation because another library (not an executable) is the loader:

```bash
relocatable_parent/
│
├── bin/
│   └── myapp (loads `mylib.dylib` via its LC_ID_DYLIB)
│
└── lib/
    ├── mylib.dylib (LC_ID_DYLIB=@loader_path/../lib/mylib.dylib;
    │                and loads `nativeaot.dylib` via its LC_ID_DYLIB)
    │
    └── nativeaot.dylib (LC_ID_DYLIB=@loader_path/nativeaot.dylib)  # changed via `install_name_tool` 
```

Does `@executable_path` in that `.targets` file get substituted with something else in another build step? After the build artifacts are created in my situation, `otool` shows `bin/Release/net8.0/osx-arm64/native/nativeaot.dylib` for `LC_ID_DYLIB` (not `@executable_path/nativeaot.dylib`).

**Comment by am11** [comment]
> After the build artifacts are created in my situation, otool shows `bin/Release/net8.0/osx-arm64/native/nativeaot.dylib` for `LC_ID_DYLIB` (not `@executable_path/nativeaot.dylib`).

@markgomez, do you see this problem with the daily build? It seems to be getting `@executable_path` on M1:

```sh
$ dotnet --version
8.0.100-rc.1.23404.2

$ dotnet new classlib -n nativeaot
$ dotnet publish -c Release --ucr -p:PublishAot=true -p:NativeLib=Shared -o $HOME/.local/myapp nativeaot

$ otool -l ~/.local/myapp/nativeaot.dylib | grep -B1 -A2 'LC_RPATH'
Load command 23
          cmd LC_RPATH
      cmdsize 32
         path @executable_path (offset 12)

# same thing reported by objdump
$ objdump --macho --rpaths ~/.local/myapp/nativeaot.dylib 
/Users/am11/.local/myapp/nativeaot.dylib:
@executable_path
```

**Comment by markgomez** [comment]
@am11, thanks for the heads-up. I wasn't able to verify that for myself as the following issues occur when trying to run the daily build (I'm still on macOS Monterey):

Using the `.pkg` installer...
```
“dotnet-sdk-8.0.100-rc.1.23409.2-osx-arm64.pkg” cannot be opened because it is from an unidentified developer.

macOS cannot verify that this app is free from malware.
```

Using the `.tar.gz` archive...
```
“libhostfxr.dylib” can’t be opened because Apple cannot check it for malicious software.

This software needs to be updated. Contact the developer for more information.
```

But it generating `@executable_path` now instead of a hard-coded path sounds good! It would mean the `.dylib` would have to be in the same directory as the executable, however. In my use case, it needs to be relocatable (i.e., I'd still need to use `otool` to change the path to use `@loader_path`. The `install_name_tool` approach has been working pretty well so far on 8.0.100-preview.6.23330.14 in my C++ (via CMake) and Rust (via build.rs) projects.

**Comment by agocke** [comment]
Sounds like there are no more issues -- I'll close this as resolved and we can reopen later if there are more issues.
