### ISSUE TITLE
[API Proposal]: File.AppendAllBytes

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#84532]
### Background and motivation

The File class has all methods for bytes which also exist for text except of appending data. Not only that it fits into the api surface by filling this gap is also saves us writing more than one line of code.

### API Proposal

```diff
namespace System.IO;

public class File
{
+    public static void AppendAllBytes(string path, ReadOnlySpan<byte> data);
+    public static Task AppendAllBytesAsync(string path, ReadOnlyMemory<byte> data, CancellationToken cancellationToken = default);
     public static void AppendAllText(string path, string? contents);
     public static Task AppendAllTextAsync(string path, string? contents, CancellationToken cancellationToken = default);
}
```

### API Usage

```csharp

byte[] data = File.ReadAllBytes("C:\\1.bin");

File.AppendAllBytes("C:\\2.bin", data);


```

**Comment by Symbai** [comment]
> The `data` argument should be of type `ReadOnlySpan<byte>` instead of `byte[]?`?

`WriteAllBytes` [uses byte[]](https://github.com/dotnet/runtime/blob/210a7a9feec64b7fac5147656cddb199ec90cf75/src/libraries/System.Private.CoreLib/src/System/IO/File.cs#L683) instead of span, thats why I used it here as well but yeah sure it can be a span.

**Comment by adamsitnik** [comment]
Few comments from my side:

- Why the API should allow for `null`s? What is the point of appending nothing to a file? Creating it? If so, we have dedicated API for that.
- We need an async overload too.
- The mentioned APIs were introduced before `Span` and `Memory`, the new methods should accepts `ReadOnlySpan` and `ReadOnlyMemory` to accept both arrays and other types of inputs.


```diff
namespace System.IO;

public class File
{
+    public static void AppendAllBytes(string path, ReadOnlySpan<byte> data);
+    public static Task AppendAllBytes(string path, ReadOnlyMemory<byte> data, CancellationToken cancellationToken = default);
}
```

Having said that, I am going to update the proposal and make it as ready for review.

**Comment by Symbai** [comment]
> * Why the API should allow for `null`s? What is the point of appending nothing to a file?

The WriteAllText allows a nullable string. I dont know whats the point of it either or if this is a bug in VS decompile but this is how it showed up and I only followed this choice. Dont mind if you change it.

**Comment by stephentoub** [comment]
> Why the API should allow for nulls? What is the point of appending nothing to a file? Creating it? If so, we have dedicated API for that.

There's value in being consistent with the existing APIs here.  If someone is using WriteAllText with something that ends up being null and they decide to switch to appending rather than overriding, it'd be nice if that didn't then entail having to handle the arguments differently.

> The mentioned APIs were introduced before Span and Memory, the new methods should accepts ReadOnlySpan and ReadOnlyMemory to accept both arrays and other types of inputs.

Do we want `ReadOnly{Span/Memory}<byte>` overloads then for the existing ones?  What about `ReadOnlySpan<char>` for the ones currently only accepting strings?

**Comment by adamsitnik** [comment]
> Do we want ReadOnly{Span/Memory}<byte> overloads then for the existing ones? What about ReadOnlySpan<char> for the ones currently only accepting strings?

I would not mind adding them, but I would prefer to see an actual need first (otherwise we should do it for all existing APIs that accept only arrays).

**Comment by bartonjs** [comment]
Because nothing else in this type uses span/memory, we are only comfortable adding it at this time as `byte[]`.

We don't disagree with adding span/memory overloads to this type, but it should be done holistically and not only for append bytes.

We also renamed `data` to `bytes` for consistency with the naming in WriteAllBytes.

```C#
namespace System.IO;

public partial class File
{
    public static void AppendAllBytes(string path, byte[] bytes);
    public static Task AppendAllBytesAsync(string path, byte[] bytes, CancellationToken cancellationToken = default);
}
```

**Comment by adamsitnik** [comment]
Here are some tips for contributor who want to take this issue:

- before you start working on it, please let me know so I can assign you and nobody else is going to work on it at the same time and duplicate the effort
- [here](https://github.com/dotnet/runtime/blob/main/docs/workflow/README.md) you can find our workflow instructions, the first step is to install everything required to build the product
- to build the clr, libs and tests you need to build following subsets:
```cmd
.\build.cmd -c Release -subset clr+libs+libs.tests
```
- the `File` type is included in corelib, not in `System.IO.dll`: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/IO/File.cs
- its tests are in `System.IO.FileSystem`: https://github.com/dotnet/runtime/tree/main/src/libraries/System.IO.FileSystem/tests/File
- the test projects can access only the public classes and methods that were added to the ref assembly: https://github.com/dotnet/runtime/blob/104752ae2874cc6a1d4ff709f0dfaae0c7e06931/src/libraries/System.Runtime/ref/System.Runtime.cs#L9544
- To rebuild only the corelib (where File class is) and run the tests you can run following command:
```cmd
.\build.cmd -c Release -subset clr.corelib+clr.nativecorelib+libs.PreTest && .\dotnet.cmd build -c Release .\src\libraries\System.IO.FileSystem\System.IO.FileSystem.sln && .\dotnet.cmd build -c Release .\src\libraries\System.IO.FileSystem\tests\System.IO.FileSystem.Tests.csproj /t:Test
```

**Comment by AlexRadch** [comment]
@adamsitnik can you assign this issue to me?

**Comment by MojtabaTajik** [comment]
@adamsitnik Can I work on this API implementation?

**Comment by adamsitnik** [comment]
> @adamsitnik can you assign this issue to me?

@AlexRadch please excuse me, for some reason I've missed the notification. Since you still have some actionable PRs opened (example: https://github.com/dotnet/runtime/pull/88009#pullrequestreview-1532521684), I am going to assign @MojtabaTajik. I hope you don't mind.

**Comment by adamsitnik** [comment]
> @adamsitnik @stephentoub Can I work on this API implementation?

@MojtabaTajik I've assigned you, please let me know if you need some help.

**Comment by MojtabaTajik** [comment]
The PR is ready for merge. 
@adamsitnik Could you please review it, or should I mention someone else for this?

https://github.com/dotnet/runtime/pull/90364/checks?check_run_id=15816349468

**Comment by tcortega** [comment]
Hi @adamsitnik and @MojtabaTajik,

I noticed this PR has been quiet since August 19th. If it's okay, I'd like to help out or take it on.

**Comment by MojtabaTajik** [comment]
Hey @tcortega 

I was on vacation, but I hope to get it done this week.

**Comment by MojtabaTajik** [comment]
> Hi @adamsitnik and @MojtabaTajik,
> 
> 
> 
> I noticed this PR has been quiet since August 19th. If it's okay, I'd like to help out or take it on.

Hey @tcortega

I was on vacation, but I hope to get it done this week.
