### ISSUE TITLE
[API Proposal]: System.Memory's Encoding.GetChars with consumed bytes

### ISSUE THREAD

**Issue by ladeak** [dotnet/runtime#84541]
### Background and motivation

Current method [GetChars](https://source.dot.net/#System.Memory/System/Text/EncodingExtensions.cs,add13478b9478ab4) extension method on using `ReadOnlySequence<byte>` and `Span<char>`:

`public static int GetChars(this Encoding encoding, in ReadOnlySequence<byte> bytes, Span<char> chars)`

should have an overload that also returns the bytes consumed from the `ReadOnlySequence<byte>`.
So, if someone has a longer sequence and prefers to decode the byte sequence in multiple operations with a reasonably smaller buffer char array used as the backing for `Span<char>`, can do it in an easier way.

Today one would need to use the written Span to calculate with GetBytesCount the number of bytes consumed.

### API Proposal

in System.Memory.dll:

```csharp
namespace System.Text;

public static class EncodingExtensions
{
    /// <summary>
    /// Decodes the specified <see cref="ReadOnlySequence{Byte}"/> to <see langword="char"/>s using the specified <see cref="Encoding"/>
    /// and outputs the result to <paramref name="chars"/>.
    /// </summary>
    /// <param name="encoding">The <see cref="Encoding"/> which represents how the data in <paramref name="bytes"/> is encoded.</param>
    /// <param name="bytes">The <see cref="ReadOnlySequence{Byte}"/> to decode to characters.</param>
    /// <param name="chars">The destination buffer to which the decoded characters will be written.</param>
    /// <param name="consumed">The number of bytes consumed from <paramref name="bytes"/>.</param>
    /// <returns>The number of chars written to <paramref name="chars"/>.</returns>
    /// <exception cref="ArgumentException">Thrown if <paramref name="chars"/> is not large enough to contain the encoded form of <paramref name="bytes"/>.</exception>
    /// <exception cref="DecoderFallbackException">Thrown if <paramref name="bytes"/> contains data that cannot be decoded and <paramref name="encoding"/> is configured
    /// to throw an exception when such data is seen.</exception>
    public static int GetChars(this Encoding encoding, in ReadOnlySequence<byte> bytes, Span<char> chars, out int consumed);
}
```

### API Usage

```csharp
void Sample(ReadOnlySequence<byte> input)
{
    var temp = new char[4096];
    int charCount = int.MaxValue;
    while (charCount > 0 && input.Length > 0)
    {
        var buffer = temp.AsSpan();
        charCount = Encoding.UTF8.GetChars(input, buffer, out var consumedBytes);
        buffer = buffer.Slice(0, charCount);
        // Process buffer...
        input = input.Slice(consumedBytes);
    }
}
```

### Alternative Designs

1. Method could have `void` return type and both consumed bytes and written chars would be `out` parameters.
2. Method with `ref ReadOnlySequence<byte>` input, and GetChars could do the slicing.

**Comment by stephentoub** [comment]
> Today one would need to use the written Span to calculate with GetBytesCount the number of bytes consumed.

The existing method will throw if the destination isn't large enough. I think you're actually asking for a non-throwing variant, possibly employing OperationStatus.

**Comment by ladeak** [comment]
Yes, that would be a the case. Especially, because it is not that trivial to handle higher code points where a single character encoded on multiple bytes might be separated into different ReadOnlySequenceSegments.

**Comment by stephentoub** [comment]
> I wonder now if a ReadOnlySequence to Stream could be a good alternative.

The Convert APIs already do effectively want you want if you're ok with the target being an IBufferWriter.

> Yes, that would be the case.

In which case just having it be an overload isn't going to be appropriate, as the only difference being an out parameter subtly changing exception semantics is something we avoid.  That's why I mention it.

**Comment by ladeak** [comment]
That is exactly what I ended up doing, but I wondered if it should/could be simpler. I have spent a few hours converging to `IBufferWriter`.

```csharp
Encoding.UTF8.GetChars(payload, new MyBufferWriter());
```

**Comment by ladeak** [comment]
I understand your concern regarding the original proposal. In the meantime, I solved my problem with `IBufferWriter`, but I think what I have done could be significantly simpler.

I also understand there are open issues regarding `ReadOnlySegment<T>` and `Stream` permeability.

@stephentoub  Do you see value in keeping this proposal open while updating it to address your concern, or shall we close it? If so please feel free to close it otherwise I am happy to iterate the API proposal.

**Comment by stephentoub** [comment]
Either's fine. Thanks.
