### ISSUE TITLE
Access violation occurring during JIT compilation of Vector2 constructor

### ISSUE THREAD

**Issue by CEO-Chair** [dotnet/runtime#84546]
### Description

JIT compiler crashes when compiling a specific line with the Vector2 constructor with intrinsics. This only seems to occur in exceedingly large functions (in my case, anywhere from 7,000 to 25,000 lines)

### Reproduction Steps

Not feasible to give full context due to the absurd size of the method.
I've narrowed it down to this specific line: `Vector2 vector278 = new Vector2(this.ai[1], this.ai[2]);`
`ai` is just a small array of floats with a length of 4

### Expected behavior

The method preparation/JIT compilation succeeds.

### Actual behavior

Throws a `System.AccessViolationException`

### Regression?

The same exception occurs in .NET 7.0 and .NET 6.0

### Known Workarounds

Creating local variables to store the contents of `ai[1]` and `ai[2]` prepares successfully. 
`float ai1 = this.ai[1];
float ai2 = this.ai[2];
Vector2 vector278 = new Vector2(ai1, ai2);`

### Configuration

Occurs on .NET 7.0 (7.0.202, x64, Windows 10) and.NET 6.0 (6.0.400, x64, Windows 10)
Occurs in only debug mode builds

### Other information

With the native debugger, I have narrowed down the exact line in the JIT compilation process that causes the access violation

![image](https://user-images.githubusercontent.com/87276335/230781697-83e38f4e-11bb-4c60-882e-85ba72d6757d.png)
`op1->AsOp()->gtOp1` is null

**Comment by tannergooding** [comment]
CC. @SingleAccretion, this needs to be doing `op1->Op(1)` instead, correct?

**Comment by SingleAccretion** [comment]
I think `op1 = ADDR(op1->AsOp()->gtOp1 = LCL_VAR)` is expected here. 

Notable: this should be fixed in .NET 8 as the code in question has been deleted.

**Comment by CEO-Chair** [comment]
After a bit of tomfoolery, I managed to squeeze a reproduction down to about 1400 lines. Here's a sharplab containing the code to reproduce: https://sharplab.io/#gist:c59beaf9976701aa1e93659f170bd461
(The file is a bit large, search "Heres the line that fails JIT" to find the specific line)

**Comment by CEO-Chair** [comment]
> @CEO-Chair, thanks for reporting this issue. 
> What is your business impact due to this issue? Since there is a workaround and it occurs only in Debug mode, I am leaning towards to push it to Future because we will not have time to fix this in .NET 8.

I haven't experienced much impact from it; it was only a minor inconvenience to work around. It only happened in a few cases in my codebase, so it really was trivial.

**Comment by TIHan** [comment]
The AV does not reproduce in latest .NET 8, closing. Thank you for reporting @CEO-Chair .
