### ISSUE TITLE
Can't apply a [JsonConstructor] attribute on a record class with more than one constructor

### ISSUE THREAD

**Issue by zxopink** [dotnet/runtime#84544]
### Description

my record:

```cs
public record class TargetScreen(PointF[] Locations) : Attack
{
    public TargetScreen(Point[] locations, Size size) 
    : this(locations.Select(p => new PointF(p.X / size.Width, p.Y / size.Height)).ToArray())
    { /*Empty*/ }

    public bool IsEmpty => Locations.Length == 0;
    public static readonly TargetScreen Empty = new TargetScreen(Array.Empty<PointF>());
}
 ```

I want to serialize the record using JsonSerializer but it throws an exception: 
`Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported`

I want to add a `[JsonConstructor]` attribute to the `TargetScreen(PointF[] Locations)` but it won't allow me to put an attribute on it

### Reproduction Steps

Copy the class and deserialize it:
```cs
using System.Drawing;
using System.Text.Json;

TargetScreen target = new(new PointF[] { new(1f, 2f), new(3f, 4f) });
string json = JsonSerializer.Serialize(target);
Console.WriteLine(json);

TargetScreen back = JsonSerializer.Deserialize<TargetScreen>(json);
Console.WriteLine(back);
```

### Expected behavior

I expected to put a `[JsonConstructor]` attribute on the record and make the record's main constructor the json constructor.

### Actual behavior

Gives an error:
`Attribute 'JsonConstructor' is not valid on this declaration type. It is only valid on 'constructor' declarations.`

### Known Workarounds

switch to a normal class or play around with the constructors

### Configuration

Visual Studio 2022, .NET 6, C# 9

**Comment by eiriktsarpalis** [comment]
This is a constraint of C# language itself, and is tracked by the following issue: https://github.com/dotnet/csharplang/issues/7047
