### ISSUE TITLE
TestCurrentValueDoesNotAllocateOnceValueIsCached test failing in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#84551]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=232800
Build error leg or test failing: Microsoft.Extensions.Options.Tests.OptionsMonitorTest.TestCurrentValueDoesNotAllocateOnceValueIsCached
Pull request: https://github.com/dotnet/runtime/pull/84487

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "TestCurrentValueDoesNotAllocateOnceValueIsCached", 
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

```
Exception Message
Assert.Equal() Failure
Expected: 0
Actual:   336
CallStack
   at Microsoft.Extensions.Options.Tests.OptionsMonitorTest.TestCurrentValueDoesNotAllocateOnceValueIsCached()
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, IntPtr* args)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[233142](https://dev.azure.com/dnceng-public/public/_build/results?buildId=233142)|dotnet/runtime|[Microsoft.Extensions.Options.Tests.OptionsMonitorTest.TestCurrentValueDoesNotAllocateOnceValueIsCached](https://dev.azure.com/dnceng-public/public/_build/results?buildId=233142&view=ms.vss-test-web.build-test-results-tab&runId=4432148&resultId=111147)|dotnet/runtime#84553|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|1|1|

**Comment by tarekgh** [comment]
@stephentoub is there a direct link to the failure? The link in the description does not show the failure.

**Comment by stephentoub** [comment]
I copied it to the bottom of the description.

**Comment by tarekgh** [comment]
We already have active issue https://github.com/dotnet/runtime/issues/67611 for `iOS` and `tvOS`. 

> I copied it to the bottom of the description.

I am not seeing it.

**Comment by vcsjones** [comment]
@tarekgh https://dev.azure.com/dnceng-public/public/_build/results?buildId=232800&view=ms.vss-test-web.build-test-results-tab&runId=4425584&paneView=debug&resultId=100559

It failed on Browser.

**Comment by tarekgh** [comment]
@lewing could you have a look? this failing test is disabled for `iOS` and `tvOS` and now is failing on the browser. Should this be disabled on the browser? 

CC @steveisok

**Comment by lewing** [comment]
I haven't seen this fail on wasm before but I'm fine with disabling it if this keeps happening

**Comment by jkotas** [comment]
This should be disabled on Mono instead of individual architectures.
