### ISSUE TITLE
ImmutableArray cast to IList does not conform to other collection's usage

### ISSUE THREAD

**Issue by star-thoughts** [dotnet/runtime#84565]
### Description

When casting an ImmutableArray to an IList, calls to IndexOf do not act as they do in other collections.  Other collections return -1 for items that are not found, regardless of their type.  ImmutableArray cast to IList then IndexOf is called will throw a NullReferenceException or InvalidCastException depending on the parameter passed in.
I originally found this when I noticed a Binding in WPF throwing an exception when bound to an ImmutableArray.  WPF was assuming that IndexOf on IList would always return -1 for a non-match.

### Reproduction Steps

Assuming the following Enum:
`enum States
{
    A,
    B
}`

The following code will show the problem:

    static void Main(string[] args)
    {
        List<States> list = new List<States>(new[] { States.A, States.B });
        TestList(list);

        States[] array = new[] { States.A, States.B };
        TestList(list);

        ImmutableArray<States> imm = ImmutableArray.Create(new[] { States.A, States.B });
        TestList(imm);
    }

    private static void TestList(IList list)
    {
        list.IndexOf(States.A);
        list.IndexOf(null);
        list.IndexOf(new object());
    }

TestList on ImmutableArray throws a NullReferenceException when ilist.IndexOf(null) is called.  If that line is commented out, it will throw an InvalidCastException when ilist.IndexOf(new object()) is called.

### Expected behavior

I would expect IList.IndexOf to return -1 and not throw one of those exceptions regardless of the implementing type.

### Actual behavior

A NullReferenceException or an InvalidCastException are thrown, depending on whether null is passed as a parameter, or an invalid type is passed as a parameter.

### Configuration

Version:  7.0
OS:  Windows 10
Arch:  X64
I doubt it is unique to this OS or machine architecture.

### Other information

This may be because at https://github.com/dotnet/runtime/blob/a7f3df9b14d896cda708e2d22f35165737646769/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray_1.cs#L1211 the passed in parameter is directly cast to the type in the collection.

**Comment by eiriktsarpalis** [comment]
Looking at the [other `IList` implementations](https://grep.app/search?q=IndexOf%28%28T%29&filter[repo][0]=dotnet/runtime) in the repo, it seems like the common pattern is to include an [`IsCompatibleObject` check](https://github.com/dotnet/runtime/blob/19ff97834663497ff6fd5207f6f64bbe2af93cba/src/libraries/System.Private.CoreLib/src/System/Collections/ObjectModel/ReadOnlyCollection.cs#L191-L196) in all the methods accepting `object?` arguments.

The only exceptions that I noticed are [`ImmutableArray<T>`](https://github.com/dotnet/runtime/blob/19ff97834663497ff6fd5207f6f64bbe2af93cba/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray_1.cs#L1186-L1212) and [`ImmutableSortedSet<T>`](https://github.com/dotnet/runtime/blob/19ff97834663497ff6fd5207f6f64bbe2af93cba/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableSortedSet_1.cs#L850-L865). It would make sense to update the implementatins for consistency. Would you be interested in contributing a PR?

**Comment by star-thoughts** [comment]
I should be able to do this.  Though I'm not familiar with XUnit or how to work with forks on Github.  So there will be a learning curve slowing me down.

**Comment by MihaZupan** [comment]
Looking just at runtime, just at `IList.IndexOf`, there are a bunch of other places with the same issue, with many other methods following the same pattern:

https://github.com/dotnet/runtime/blob/7526a4c6a0a095670f1135d983a349b4e867f2e2/src/libraries/System.CodeDom/src/System/CodeDom/CodeNamespaceImportCollection.cs#L95
https://github.com/dotnet/runtime/blob/7526a4c6a0a095670f1135d983a349b4e867f2e2/src/libraries/System.Collections.Specialized/src/System/Collections/Specialized/StringCollection.cs#L209-L211
https://github.com/dotnet/runtime/blob/7526a4c6a0a095670f1135d983a349b4e867f2e2/src/libraries/System.Private.Xml/src/System/Xml/Xsl/ListBase.cs#L165-L167
https://github.com/dotnet/runtime/blob/7526a4c6a0a095670f1135d983a349b4e867f2e2/src/libraries/System.DirectoryServices/src/System/DirectoryServices/SchemaNameCollection.cs#L208
https://github.com/dotnet/runtime/blob/7526a4c6a0a095670f1135d983a349b4e867f2e2/src/libraries/System.Diagnostics.TraceSource/src/System/Diagnostics/TraceListeners.cs#L267-L269
https://github.com/dotnet/runtime/blob/7526a4c6a0a095670f1135d983a349b4e867f2e2/src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/ValueCollection.cs#L55-L60
https://github.com/dotnet/runtime/blob/7526a4c6a0a095670f1135d983a349b4e867f2e2/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/EventDescriptorCollection.cs#L401
https://github.com/dotnet/runtime/blob/7526a4c6a0a095670f1135d983a349b4e867f2e2/src/libraries/System.Private.Xml/src/System/Xml/Xsl/Runtime/XmlQuerySequence.cs#L282-L284
https://github.com/dotnet/runtime/blob/7526a4c6a0a095670f1135d983a349b4e867f2e2/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/PropertyDescriptorCollection.cs#L553

**Comment by star-thoughts** [comment]
Would you like me to include all of the ones you listed here in this as well?  I can try to get that in.

If so, should I close my current PR, make the other fixes and re-open it?  Or let this PR merge and create a new one?
