### ISSUE TITLE
Unnecessary sign-extension for `(nuint)span.Length`

### ISSUE THREAD

**Issue by xtqqczze** [dotnet/runtime#84564]
> @EgorBo In theory, the length in `(nuint)span.Length` should be recognized as never negative, and the sign-extension elided, but doesn't appear to be the case (at least in R2R), see https://csharp.godbolt.org/z/14oW68fqz.

_Originally posted by @xtqqczze in https://github.com/dotnet/runtime/issues/84524#issuecomment-1500999983_

```csharp
static nuint Span0(ReadOnlySpan<byte> span) => (nuint)span.Length;
static nuint Span1(ReadOnlySpan<byte> span) => (uint)span.Length;
```

```asm
// crossgen2 8.0.0-preview.4.23208.99+07f00dc2f624946c54dbf85fea79c600a690f634

C:Span0(System.ReadOnlySpan`1[ubyte]):ulong:
; Emitting BLENDED_CODE for X64 CPU with AVX - Windows
						;; size=0 bbWeight=1 PerfScore 0.00
       movsxd   rax, dword ptr [rcx+08H]
						;; size=4 bbWeight=1 PerfScore 4.00
       ret      
						;; size=1 bbWeight=1 PerfScore 1.00

C:Span1(System.ReadOnlySpan`1[ubyte]):ulong:
; Emitting BLENDED_CODE for X64 CPU with AVX - Windows
						;; size=0 bbWeight=1 PerfScore 0.00
       mov      eax, dword ptr [rcx+08H]
						;; size=3 bbWeight=1 PerfScore 2.00
       ret      
						;; size=1 bbWeight=1 PerfScore 1.00
```

**Comment by EgorBo** [comment]
Should be a simple fix since Span.Length can be recognized via `IsNeverNegative`. We just need to mark such `GT_CAST` as `GTF_UNSIGNED` if it's target is `IsNeverNegative` and we're upcasting

**Comment by SingleAccretion** [comment]
We already do:

https://github.com/dotnet/runtime/blob/00dbf84e3df92c050cf256ef93dff09ff5aa2934/src/coreclr/jit/morph.cpp#L10190-L10194

The snippets in the issue are cases of an un-promoted span, which should be rare in practice.
