### ISSUE TITLE
[wasm] Make runtime errors from simd and exception handling failures easy to understand

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#84574]
Now that we are enabling post MVP Wasm rutime features we should make sure that any runtime errors are clear and guide the developer on how to resolve the issue.  Additionally we should consider adding messages during the build explaining that these features are enabled and that they impact compatibility.

Features which could be detected
- wasm SIMD - old Safari
- wasm EH
- Threads/SharedArrayBuffer/WebWorker - Coop headers, old FireFox without ES6 workers
- BigInt64Array - old Safari
- CSP - http headers
- WebSocket on NodeJS

**Comment by kg** [comment]
On the client side, one option we have is to leverage jiterp's feature detection and run it on any failure to load dotnet.wasm, so we can use that information to choose an appropriate error message. The question still arises of how to message that load failure to the user, though, and that would require some decisions to happen at the Blazor level I think.

**Comment by pavelsavara** [comment]
Once we have small loader module which would be loaded before the main emscripten script, we could use it to detect which features are available and choose the correct build flavor to load. See https://github.com/dotnet/runtime/issues/85045

**Comment by pavelsavara** [comment]
Should we take dependency on https://github.com/GoogleChromeLabs/wasm-feature-detect and bundle it into the loader module ?

**Comment by pavelsavara** [comment]
```
    import { simd } from "https://unpkg.com/wasm-feature-detect@1.5.1/dist/esm/index.js";
    console.log("simd: "+ await simd());
```

only 764 bytes!

**Comment by lewing** [comment]
https://github.com/dotnet/runtime/issues/89028 is an example
