### ISSUE TITLE
Hot Reload Fails on Microsoft Subsystem for Android & Android Emulators for .razor pages

### ISSUE THREAD

**Issue by Envitec** [dotnet/runtime#84572]
### Description

I have an hybrid MAUI App with .razor pages and Maui Xaml pages. 

Hot reload fails on Android Emulators and Microsoft Subsystem for Android with following error:

* Assertion at /__w/1/s/src/mono/mono/component/hot_reload.c:1101, condition `success' not met
[libc] Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 9142 (.NET ThreadPool), pid 9004 (pp.xxxxxxxx.org)

However it works for MAUI target on Windows Syste,

### Steps to Reproduce

1. Make changes to .razor page on any of the html elements
2. Save page
3. Application terminates with error * Assertion at /__w/1/s/src/mono/mono/component/hot_reload.c:1101, condition `success' not met [libc] Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 9142 (.NET ThreadPool), pid 9004 (pp.swadhyay.org)
4. Set Target as Windows Machine and repeat steps above. Hot Reload works as expected.

### Link to public reproduction project repository

NA

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Android, Windows

### Affected platform versions

Android 13

### Did you find any workaround?

Unfortunately no.

### Relevant log output

```shell
[pp.xxxxxxxx.org] * Assertion at /__w/1/s/src/mono/mono/component/hot_reload.c:1101, condition `success' not met
[libc] Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 9142 (.NET ThreadPool), pid 9004 (pp.xxxxxxxx.org)
```

**Comment by lambdageek** [comment]
There's no assert on [line 1101 in net6.0](https://github.com/dotnet/runtime/blob/3e109839ddb415401a51574eb1e30455766ff57c/src/mono/mono/component/hot_reload.c#L1101).  As Peppers noted, there's an assert on 1101 in 7.0.  So some of the info in this issue is not accurate.

Also "Make changes to .razor page on any of the html elements" is not sufficient to diagnose the issue.  Is it a static html element or a Razor component?  Is the static html element inside the body of a razor component?  A repo with some sample code and the suggested change would be helpful

**Comment by Envitec** [comment]
This is a razor component and issue was noticed on VS 2022 preview - Version 17.6.0 preview 2. 
This project has dependency on other projects that use .Net 7. One of them is a gRPC client and other manages Sqlite DB.

I am trying to get pieces out in a separate project to reproduce this.

Thanks

**Comment by lambdageek** [comment]
Thanks @Envitec ! Anything you could provide us to try and repro the issue would be amazing.

In particular any hints about what sorts of changes you're making in the .razor files will be helpful.  the hot reload support for mobile in .NET 7 is limited largely to changes to C# method bodies - a lot of razor changes compile to more complex C# changes under the hood, so this could be one of those scenarios.  In .NET 8 we have improved the set of supported edits on mobile, but it's possible you're encountering something unanticipated.

**Comment by Envitec** [comment]
Ok. So this is interesting. After 3 days of grueling search, I think found the root cause of this issue. It is connected to this issue  [AndroidMessageHandler doesn't use ClientCertificates](https://github.com/dotnet/runtime/issues/73960)

I have added this line in my **.csproj** to fix the issue I am facing with gRPC calls.
**< UseNativeHttpHandler > false < /UseNativeHttpHandler >**

However, this setting causes the exceptions during Hot Reload when I change .razor pages. If I need Hot Reload to work, I have to remove this setting in **.csproj** and use native Http handler but then the **gRPC** calls fails as the **HttpClientHandler** **ClientCertificate** property is null.

This is reproducible consistently. Hope this helps.

Thanks
Rajesh
