### ISSUE TITLE
[Breaking change] Changing EventSource OnEventCommand to be consistent

### ISSUE THREAD

**Issue by davmason** [dotnet/runtime#84586]
PR #82970 was a fix for issue #61353, it included a minor breaking change in that we make the callback for `EventSource.OnEventCommand` after we mark all events as disabled.

**Previous behavior**
Prior to this change, we would issue the `EventSource.OnEventCommand` callback for a `EventCommand.Disable` prior to setting `m_eventSourceEnabled=false`. This means that `IsEnabled` would return true in the `OnEventCommand` callback for a user `EventSource`, even if the command would lead to the `EventSource` being disabled.

The callback happens after we turn off the ability to dispatch events though, so even if an `EventSource` tries to fire an event it will not be written. Also, for `EventCommand.Enable` we issue a consistent view - `IsEnabled` accurately reports the state of the world, and the `EventSource` can write events from the `OnEventCommand` callback. This change makes the `EventCommand.Disable` behavior match the `Enable` behavior.

**New behavior**
The change makes the callbacks consistent, now we will mark the `EventSource` as disabled before the callback.

@PriyaPurkayastha - We have multiple first party requests to backport this fix to 6.0 and 7.0, I would appreciate guidance on how to proceed with the backports. Is documentation sufficient?

**Comment by davmason** [comment]
CC @dotnet-diagnostics @jeffschwMSFT

**Comment by davmason** [comment]
Actually CC @dotnet/dotnet-diag (typo the first time)

**Comment by tommcdon** [comment]
Breaking change doc issues created:

* https://github.com/dotnet/docs/issues/35313
* https://github.com/dotnet/docs/issues/35314

**Comment by davmason** [comment]
Closing this since we have the breaking change doc bugs created
