### ISSUE TITLE
ETL for Tiered Compilation Settings not showing the TieredPGO flag?

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#84607]
I am trying to write up a note on how end users can verify TieredPGO is properly enabled. One mechanism is to trigger the TieredCompilation/Settings event, via something like the following:

```
dotnet-trace collect --providers Microsoft-Windows-DotNETRuntime:0x1000000000:4 -- bin\Release\net8.0\pgo-etw.exe
```
where in my test app the exe runtimeconfig has:
```
      "System.Runtime.TieredPGO": true
```
However I never see the TieredPGO flag bit set in the event flags. I can tell that TieredPGO is enabled via jit disassembly. So not sure yet why this bit is not making it to the ETL.

<img width="875" alt="image" src="https://user-images.githubusercontent.com/10121823/231036887-9e098ff8-99da-4061-bf72-36de8e870d4c.png">

Also it would be good to document the `0x1000000000` keyword.

**Comment by AndyAyersMS** [comment]
FYI @mangod9 

I will do some digging but somebody on your team might be able to figure this out faster. Also there is no user-friendly name for the tiered compilation events and they do not seem to be documented.

**Comment by mangod9** [comment]
@kouvel and @eduardo-vp .. Believe there was a tracing issue which was recently fixed around this?

**Comment by kouvel** [comment]
The issue seems to be that the TC Settings event is sent before the EEConfig value for tiered PGO is initialized:

Event is sent here:
https://github.com/dotnet/runtime/blob/58e585085c86e68dcf89bee49f43d0cda9cd180f/src/coreclr/vm/eeconfig.cpp#L774-L777

Then, the EEConfig value for tiered PGO is initialized:
https://github.com/dotnet/runtime/blob/58e585085c86e68dcf89bee49f43d0cda9cd180f/src/coreclr/vm/eeconfig.cpp#L781-L793

**Comment by kouvel** [comment]
The `TieredCompilationRundown/SettingsDCStart` event seems to show the correct flags when tiered PGO is enabled

**Comment by kouvel** [comment]
> Also there is no user-friendly name for the tiered compilation events and they do not seem to be documented.

They aren't currently documented. Can you clarify what you mean by "user-friendly name for the tiered compilation events"?

**Comment by AndyAyersMS** [comment]
> Can you clarify what you mean by "user-friendly name for the tiered compilation events"?

I'm probably just confused, I thought somewhere you could specify keywords by name instead of hex values.

**Comment by kouvel** [comment]
Ah ok, I think the PerfView `-ClrEvents` switch allows specifying keywords by name and Contention is one of them.

**Comment by kouvel** [comment]
I put up a PR the fix the issue (https://github.com/dotnet/runtime/pull/86827), and filed a separate issue for documenting the TC events (https://github.com/dotnet/runtime/issues/86826)
