### ISSUE TITLE
httpclient.PostAsJsonAsync ignores jsonpropertyname attr if it starts with an @ on serialization

### ISSUE THREAD

**Issue by SireMartin** [dotnet/runtime#84612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I got the impression that HttpClient.PostAsJsonAsync ignores JsonPropertyNameAttribute if it starts with an @ on serialization
If i use the JsonSerializer.Serialize(), the serialization seems OK

Example using this object for serialization:
public class Agv
{
    [JsonPropertyName("@timestamp")]
    public DateTimeOffset Timestamp {get;set;}
}

Using JsonSerializer.Serialize(agv), the object gets serialzed correct :
"{\"@timestamp\":\"2023-04-07T12:47:23.654374+00:00\"}"

Using await _httpClient.PostAsJsonAsync($"{iterMsg.PartitionKey}/_doc?{iterMsg.ReplyTo}", agv);
Pipedream shows me te following output:

Timestamp:
2023-04-07T12:47:23.654374+00:00

### Expected Behavior

httpclient should serialize the same way as JsonSerializer.Serialize()

### .NET Version

6

**Comment by mitchdenny** [comment]
@SireMartin I've moved this into the runtime repo since it isn't ASP.NET specific (from what I can see).

**Comment by MihaZupan** [comment]
> await _httpClient.PostAsJsonAsync($"{iterMsg.PartitionKey}/_doc?{iterMsg.ReplyTo}", agv) ignores the JsonPropertyNameAttr
await _httpClient.PostAsync($"{iterMsg.PartitionKey}/_doc?{iterMsg.ReplyTo}", JsonContent.Create(agv)) does not ignore the JsonPropertyNameAttr

How are you determining this? Have you looked at what's being sent on the network?
I don't see why you'd see different behavior between the two, they're effectively the same.

`PostAsJsonAsync` is a very thin wrapper to create the content. Here's the whole implementation:
https://github.com/dotnet/runtime/blob/476bce3456006245bdade1fc38a1a300b10f91e8/src/libraries/System.Net.Http.Json/src/System/Net/Http/Json/HttpClientJsonExtensions.Post.cs#L36-L37

---

If you run the following code, you will see that the server received the same data in both cases:

```c#
var agv = new Agv { Timestamp = DateTime.UtcNow };

using var client = new HttpClient();

using var response1 = await client.PostAsJsonAsync("https://httpbin.org/post", agv);
using var response2 = await client.PostAsync("https://httpbin.org/post", JsonContent.Create(agv));

Console.WriteLine(await response1.Content.ReadAsStringAsync());
Console.WriteLine(await response2.Content.ReadAsStringAsync());

public class Agv
{
    [JsonPropertyName("@timestamp")]
    public DateTimeOffset Timestamp { get; set; }
}
```

**Comment by abouroubi** [comment]
> > await _httpClient.PostAsJsonAsync($"{iterMsg.PartitionKey}/_doc?{iterMsg.ReplyTo}", agv) ignores the JsonPropertyNameAttr
> > await _httpClient.PostAsync($"{iterMsg.PartitionKey}/_doc?{iterMsg.ReplyTo}", JsonContent.Create(agv)) does not ignore the JsonPropertyNameAttr
> 
> How are you determining this? Have you looked at what's being sent on the network? I don't see why you'd see different behavior between the two, they're effectively the same.
> 
> `PostAsJsonAsync` is a very thin wrapper to create the content. Here's the whole implementation:
> 
> https://github.com/dotnet/runtime/blob/476bce3456006245bdade1fc38a1a300b10f91e8/src/libraries/System.Net.Http.Json/src/System/Net/Http/Json/HttpClientJsonExtensions.Post.cs#L36-L37
> 
> If you run the following code, you will see that the server received the same data in both cases:
> 
> ```cs
> var agv = new Agv { Timestamp = DateTime.UtcNow };
> 
> using var client = new HttpClient();
> 
> using var response1 = await client.PostAsJsonAsync("https://httpbin.org/post", agv);
> using var response2 = await client.PostAsync("https://httpbin.org/post", JsonContent.Create(agv));
> 
> Console.WriteLine(await response1.Content.ReadAsStringAsync());
> Console.WriteLine(await response2.Content.ReadAsStringAsync());
> 
> public class Agv
> {
>     [JsonPropertyName("@timestamp")]
>     public DateTimeOffset Timestamp { get; set; }
> }
> ```

Just to add my two cents, I'm having the same issue with this code:
```csharp
public partial class LoginDTO
{
    [JsonPropertyName("name")]
    public string Name { get; set; }

    [JsonPropertyName("password")]
    public string Password { get; set; }
}

public async Task Login()
{
        var loginData = new LoginDTO
        {
            Name = "username",
            Password = "password"
        };

        JsonContent content = JsonContent.Create(loginData);
        var loginResult = await _client.PostAsync("/login", content);

        var loginResult2 = await _client.PostAsJsonAsync("/login", loginData);
}
```

In the first call, my login server receives:
```json
{"name": "username", "password": "password"}
```

Second call I receive:
```json
{"Name": "username", "Password": "password"}
```

**Comment by abouroubi** [comment]
I'm using it in an Azure Functions project, and the client is injected using:
```csharp
builder.Services.AddHttpClient<LoginService>();
```

I don't know if this way of instantiating changes something or not.

**Comment by SireMartin** [comment]
@mitchdenny I post the http call to pipedream.com to evaluate the resulting serialized data.
In my case this also occurs in an Azure Function (same as for @abouroubi) !!
I wrote a console application in dotnet6 and there I cannot reproduce this problem.

**Comment by mitchdenny** [comment]
I think what we need here @SireMartin or @abouroubi is a stand-alone repro in a public GitHub repro with exactly the code you are using to product this behavior. Then we can make sure we are on the same page.

**Comment by abouroubi** [comment]
Here it is:
https://github.com/abouroubi/json-functions-issue

**Comment by MihaZupan** [comment]
@abouroubi thanks, what are the steps to reproduce the issue with your project?
What's the expected result and what are you seeing instead?

**Comment by abouroubi** [comment]
Run the project, and you will see that when I use ‘PostAsJson’ the body sent have json property names as PascalCase and they are supposed to be camelCase.

**Comment by MihaZupan** [comment]
Okay, I see the issue now, thanks for the repro.

There are a number of helpers exposed in the `System.Net.Http.Json` namespace that help with sending/receiving json bodies. These include helpers like `JsonContent` or `PostAsJsonAsync` that encode your object using `System.Text.Json`.

The issue is that your call to `_client.PostAsJsonAsync` **is not** using the same set of helpers as `JsonContent.Create`.
The project is referencing `Microsoft.NET.Sdk.Functions`, which depends on `Microsoft.Azure.WebJobs.Extensions.Http`, which depends on `Microsoft.AspNet.WebApi.Client`, which includes a similar set of extensions (e.g. `PostAsJsonAsync`), but those extensions use `Newtonsoft.Json` instead of `System.Text.Json`.

Your calls to `PostAsJsonAsync` are binding to that extension method which is using `Newtonsoft.Json`, instead of the one in `System.Net.Http.Json` (try checking "Go To Definition" in VS).
That is, your calls are going to `HttpClientExtensions.PostAsJsonAsync` (coming from the NuGet package), and not `HttpClientJsonExtensions.PostAsJsonAsync`.
When you instead use `JsonContent.Create(myObj)` or `JsonSerializer.Serialize`, you are using `System.Text.Json` serialization.

---

@mathewc does `Microsoft.Azure.WebJobs.Extensions.Http` have to target `Microsoft.AspNet.WebApi.Client` on newer TFMs? As far as I can tell [the latter is specific to legacy ASP.NET](https://github.com/aspnet/AspNetWebStack).
The fact that the package is being pulled in by the SDK leads to confusing behavior (this issue) where some calls are binding to legacy extension methods with different behavior.

**Comment by abouroubi** [comment]
I understand better now.

It's kind weird that Azure Functions forces us to use their extension when calling outside services ...

**Comment by MihaZupan** [comment]
Triage: There is nothing we can do in the runtime to change the behavior here.
From our perspective, `PostAsJsonAsync` behaves exactly the same as `JsonContent`.

The fact that these legacy extensions are "hijacking" calls to the new ones is very unfortunate. Filing an issue in https://github.com/Azure/azure-webjobs-sdk-extensions may be the best next step to see if this is something that can be improved.

**Comment by mathewc** [comment]
@MihaZupan - it looks like the `Microsoft.AspNet.WebApi.Client` reference got pulled in about 5 years ago in [this](https://github.com/Azure/azure-webjobs-sdk-extensions/commit/32142a5d521e55ae0cfdfa69bfc5dd1a2784030f) commit. @fabiocav might have more insight but it looks like this is a transitive dependency coming from `Microsoft.AspNetCore.Mvc.WebApiCompatShim` which this extension also references.
