### ISSUE TITLE
System.ValueTuple - compatibility issue between net 4.8 and net standard 2.0

### ISSUE THREAD

**Issue by martin-stepanek-swi** [dotnet/runtime#84618]
### Description

There's a specific scenario where in my opinion incorrect assembly is loaded.

Basically mix of GAC, nuget package, binding redirect, net 4.8 and net standard 2.0 projects results in:

_Unhandled Exception: System.TypeLoadException: Method 'get_KeyParametersWithResolver' in type 'ValueTupleIssueDemo.DemoClass' from assembly 'ValueTupleIssueDemo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation. at ValueTupleIssueDemo.Program.Main(String[] args)_

## Steps to reproduce the issue

1. Have System.ValueTuple netstandard1.0 dll in GAC
(can be taken from  https://www.nuget.org/packages/System.ValueTuple/4.5.0)
2. Create console app targeting net48 (have auto generated binding redirects ON for the console app project.)
3. Add nuget package *Microsoft.Extensions.Configuration.Json* v. 3.1.22  (version is not relevant, can be newer as well)
4. Have class with property using System.ValueTuple like this:

```
internal class DemoClass
    {
        public IEnumerable<(string Name, Func<string, object> Resolver)> KeyParametersWithResolver { get; }

        public DemoClass()
        {
            KeyParametersWithResolver = new (string Name, Func<string, object> Resolver)[]
           {
                ("key", key => key)
           };
        }
    }
```

5. Instantiate this class from Main in Program.cs

```
 DemoClass demoClass = new DemoClass();
```

Until now, program should be running just fine.

6. Add ClassLibrary project targeting netstandard2.0 and reference it from console app project.
7. Add abstract class including abstract property

```
 public abstract class BaseDemoClass
    {
        public abstract IEnumerable<(string Name, Func<string, object> Resolver)> KeyParametersWithResolver { get; }
    }
```

8. As soon as you implement this abstract class in DemoClass like this:

```
  internal class DemoClass : BaseDemoClass
    {
        public override IEnumerable<(string Name, Func<string, object> Resolver)> KeyParametersWithResolver { get; }

        public DemoClass()
        {
            KeyParametersWithResolver = new (string Name, Func<string, object> Resolver)[]
           {
                ("key", key => key)
           };
        }
    }
```

You'll get:
*Unhandled Exception: System.TypeLoadException: Method 'get_KeyParametersWithResolver' in type 'ValueTupleIssueDemo.DemoClass' from assembly 'ValueTupleIssueDemo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at ValueTupleIssueDemo.Program.Main(String[] args)*

### Expected behavior

ValueTuple is loaded correctly (from mscorlib or net 4.7 dll with redirect to mscorlib)

### Actual behavior

System.ValueTuple is loaded from GAC and program ends up with 

_Unhandled Exception: System.TypeLoadException: Method 'get_KeyParametersWithResolver' in type 'ValueTupleIssueDemo.DemoClass' from assembly 'ValueTupleIssueDemo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation. at ValueTupleIssueDemo.Program.Main(String[] args)_

### Known Workarounds

1. Delete generated binding redireciton

```
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.ValueTuple" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
      </dependentAssembly>
    </assemblyBinding>
```
2. Replace System.ValueTuple in GAC with net47 version, or remove it from GAC completely.
3. Use Tuple instead of ValueTuple.

### Configuration

.NET: net 4.8 + net standard 2.0 as target projects
OS: Tried with Windows 10 21H2 and Windows Server 2019 1809, also Windows Server 2016 all with .net framework 4.8 installed.

### Other information

System.ValueTuple is from NET 4.7 part of mscorlib, up to that point package was needed. Here partial issue is that *Microsoft.Extensions.Configuration.Json* has dependency on *System.Text.Json*
which then refers to *System.ValueTuple*, assembly redirection is then generated automatically

```
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.ValueTuple" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
      </dependentAssembly>
    </assemblyBinding>
```
net47 and netstandard1.0 dll for System.ValueTuple have same signature that is token, culture, version etc. Only difference is that net47 version has forwarder
to mscorlib, while netstandard1.0 one has implementation of ValueTuple in it. 

Because of the same signature and order of assembly binding, the dll from GAC is loaded.
**IMPORTANT** : but that is **ONLY IN CASE** where we implement class from net standard 2.0, without it the mscorlib is used directly.

Public repo with reproduced issue (you need to add System.ValueTuple in GAC yourself, see readme) :
https://github.com/martin-stepanek-swi/SystemValueTupleIssue

**Comment by tannergooding** [comment]
CC. @ericstj, could you provide input/insight into this scenario? It seems like types are failing to unify here.

**Comment by ericstj** [comment]
I cannot reproduce this on a clean machine.

This part of the repro is _invalid_:
> Have System.ValueTuple netstandard1.0 dll in GAC
(can be taken from https://www.nuget.org/packages/System.ValueTuple/4.5.0)

It sounds to me like someone installed an OOB copy of System.ValueTuple in the GAC and installed a version that didn't match the framework that was installed on the machine.  That same package provided a *better/correct* asset for this machine which should have been used.

The assemblies must have the same identity for multi-targeting to work.  We rely on asset selection to determine the "correct" one for the framework being targeted.  Here the "correct" one is from the `net47` folder in the package.

Removing the bindingRedirect makes things work because .NETFramework's unification table will force the version to the one inbox.  `bindingRedirects` will override the unification table, however, so that's why you're able to force a different version than is inbox.

Probably we can report a bug here against MSBuild - it should not be generating bindingRedirects when the assembly is part of the framework.  It should recognize that the a newer version is in the framework and not emit a bindingRedirect nor allow an app-local copy.  FWIW the `dotnet cli` does this correctly, but the VS-installed MSBuild seems to produce the wrong result cc @rainersigwald @dsplaisted.

**Comment by jeffhandley** [comment]
@PranavSenthilnathan For this issue, if it can still be reproduced using the VS-installed MSBuild as @ericstj described, please file an issue against [dotnet/msbuild](https://github.com/dotnet/msbuild) to capture the scenario with an accurate title and a minimal repro if feasible.
