### ISSUE TITLE
Task.WhenAll(IEnumerable) causes results to disappear in specific scenario

### ISSUE THREAD

**Issue by alexandrehtrb** [dotnet/runtime#84626]
### Description

Hello,

I was using `Task.WhenAll(IEnumerable<Task<X>> tasks)` in a specific scenario and it caused the results to disappear.

### Reproduction Steps

Console sample below:

```cs
int[] entries = new[] { 1, 2, 3, 4 };

int[] results = (await DoAllInParallelAsync(entries, WaitAndDoubleAsync)).ToArray();

Console.WriteLine("Entries: " + string.Join(',', entries));
Console.WriteLine("Results: " + string.Join(',', results));

static async Task<int> WaitAndDoubleAsync(int i)
{
    await Task.Delay(200);
    return i * 2;
}

static async Task<IEnumerable<Y>> DoAllInParallelAsync<X,Y>(X[] entries, Func<X, Task<Y>> entryToTaskMapper)
{
    // It works if .ToArray() is appended at the end, 
    // or simply return await Task.WhenAll(tasks);
    var tasks = entries.Select(entryToTaskMapper);

    await Task.WhenAll(tasks);

    return tasks.Where(t => t.IsCompleted && t.Result != null)
               .Select(t => t.Result);
}
```

### Expected behavior

```
Entries: 1,2,3,4
Results: 2,4,6,8
```

### Actual behavior

```
Entries: 1,2,3,4
Results:
```

### Known Workarounds

Described in comments on the code

### Configuration

Happens in both .NET 6 and 7, both on Debug and Release

**Comment by stephentoub** [comment]
Every time you enumerate your `tasks`, it's going to re-evaluate the `Select(entryToTaskMapper)`.  Your code enumerating `tasks` after the `WhenAll` is thus operating on a completely different set of tasks.
