### ISSUE TITLE
Why copy twice at List<T>.InsertRange in .NET Framework

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/runtime#84624]
.NET Framework:
```C#
T[] array = new T[count];
collection2.CopyTo(array, 0);
array.CopyTo(_items, index);
```

Why not:
collection2.CopyTo(this._items, index);

**Comment by stephentoub** [comment]
> Why copy twice at List<T>.InsertRange in .NET Framework

Most likely it was a defense against handing the list's internal array directly to external code.

> Why not: collection2.CopyTo(this._items, index);

That's what .NET Core does:
https://github.com/dotnet/runtime/blob/19ff97834663497ff6fd5207f6f64bbe2af93cba/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/List.cs#L805
Such changes are not backported back to .NET Framework (and this repo is for .NET Core).

Thanks.
