### ISSUE TITLE
[wasm] Set -sMAXIMUM_MEMORY to 256 MiB by default

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#84638]
Mobile Safari (on ios 16.4 and probably earlier) doesn't like Emscripten's default `MAXIMUM_MEMORY` of 2 GiB:

```js
wasmMemory=new WebAssembly.Memory({"initial":INITIAL_MEMORY/65536,"maximum":2147483648/65536,"shared":true})
```

We get a rejected promise during startup with `RangeError: out of memory` with the default maximum memory size.

As a workaround I can add this in my .csproj, but we should set a good default:

```xml
        <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
            <!-- 256 MiB -->
            <EmccFlags>-sMAXIMUM_MEMORY=268435456</EmccFlags>
        </PropertyGroup>
```

Note: we should double-check that 256 is a good default for Blazor

Note2: demo https://lambdageek.dev/dotnet-wasm-raytracer/net8/

<img width="661" alt="Screenshot 2023-04-11 at 13 01 05" src="https://user-images.githubusercontent.com/480437/231237377-b09ae0f8-3357-49cd-84a9-58ff632f9afb.png">

**Comment by lewing** [comment]
Interesting, we definitely need to think about what a good default for this is.

**Comment by maraf** [comment]
I think it's too late to change defaults and would prefer to start with in early .NET 9

**Comment by pavelsavara** [comment]
I can't find `new WebAssembly.Memory` statement in the dotnet.native.js anymore.

I can see Memory section in wa-info
```
Reading section:    Memory size:            7 count: 1
  memory: 0 limits: 256, 32768 has max: True
```

**Comment by lambdageek** [comment]
@maraf Can we think about adding an msbuild property for .net8 to set the maximum in a nice way instead of relying on `EmccFlags`. That way we don't change the default, but people who are interested in supporting iOS can set a maximum that it can use.

**Comment by maraf** [comment]
> I can't find `new WebAssembly.Memory` statement in the dotnet.native.js anymore.

The `new WebAssembly.Memory` is there only in MT version. when wasm memory is marked as import

**Comment by pavelsavara** [comment]
Are we saying that setting max heap lower will make GC run earlier, and the browser would not have to allocate more than he can  (on limited device) ? 

Or we actually need to set initial memory ?

**Comment by pavelsavara** [comment]
Also if this is only about Mono GC pressure I think we could have other means how to set it lower, without needing to make it compile time constant. 

@radekdoulik I remember that you somehow detect available memory for GC purpose ?

**Comment by lambdageek** [comment]
I'm not sure what this has to do with Mono. Mobile Safari refuses to create the wasm memory instance if the maximum is more than 256MiB. Doesn't matter how Mono will use it. This happens much earlier

**Comment by ilonatommy** [comment]
Wasn't https://github.com/dotnet/runtime/pull/91256 a fix for this? Do we need to keep the discussion open?

**Comment by lambdageek** [comment]
> Wasn't #91256 a fix for this? Do we need to keep the discussion open?

#91256 made it easier for app authors to set the maximum initial memory.  But we didn't change the default.

Maybe we don't need to change the default? Maybe we can just add something to the docs?  or write something to the console if we detect mobile safari and the runtime fails to start?

**Comment by mkhamoyan** [comment]
Error message was added by https://github.com/dotnet/runtime/pull/104963
