### ISSUE TITLE
SPMI diff failure for SqlSingleTest

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#84631]
### Error Blob

```json
{
  "ErrorMessage": "Assertion failed 'type != TYP_VOID' in 'System.Data.Tests.SqlTypes.SqlSingleTest:Lessers():this' during 'Expand static init'",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by EgorBo** [comment]
the assert is fired in `gtSplitTree`

**Comment by EgorBo** [comment]
![image](https://user-images.githubusercontent.com/523221/231212276-ef67b27c-1410-4ae9-a173-b0064221b0a5.png)

@jakobbotsch does it ring a bell to you why `gtSplitTree` fail here on void COMMA while splitting this tree on the helper call point?

**Comment by EgorBo** [comment]
> Where do we create that comma?

@SingleAccretion said it's dead store removal?

**Comment by BruceForstall** [comment]
How did this regress, given that JIT PRs run replay/asmdiffs pipelines before checkin?

**Comment by BruceForstall** [comment]
But spmi collection process would filter out any failures, so if #83911 introduced the failure but also changed the GUID, I would expect the new collection to hit the assertion during collection, but the collection "clean" process to remove the failing MCs from the resultant MCH.

**Comment by jakobbotsch** [comment]
Good point. On a closer look the issue actually was introduced with my change in the splitter in #83388 (itself a fix for a different issue I hit as part of that PR)... The last test runs in that PR were from Friday, so before the new collection.

**Comment by tannergooding** [comment]
So this was the result of a couple different passing PRs conflicting post merge?

**Comment by jakobbotsch** [comment]
Yes, essentially. Well, the bug was in my PR, but apparently stress did not manage to expose it until the extra cases seen with #83911.
