### ISSUE TITLE
Reflection regression - Type.GetType does not skip leading `.`

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/runtime#84644]
### Description

`Type.GetType` does not find the type when type name starts with `.` (dot)..

### Reproduction Steps

```
class MyType
{
    static void Main() => Console.WriteLine(Type.GetType(".MyType"));
}
```

### Expected behavior

Type is found

### Actual behavior

Type is not found

### Regression?

Yes, this used to work on SDK 8.0.100-preview.4.23171.22

### Configuration

SDK 8.0.100-preview.4.23210.1
macOS-11.6.7
x64

**Comment by EgorBo** [comment]
hm.. I can't repro no matter what I do - I tried the exact SDK version + played with R2R/TC modes - it still prints "Success!" on run for me

**Comment by EgorBo** [comment]
Also tried to run it in a loop (via bash) and with various stress modes - still no luck reproing

**Comment by AndriySvyryd** [comment]
I have only been able to repro this on Helix machines via `dotnet run`.

[Here's an updated repro](https://github.com/dotnet/runtime/files/11214690/ReflectionOSX.zip) that builds the target assembly at runtime.

**Comment by AndriySvyryd** [comment]
We also set `COMPlus_EnableWriteXorExecute=0` before running this (it's a workaround for a different issue we've hit)

**Comment by EgorBo** [comment]
Doesn't look to be https://github.com/dotnet/runtime/pull/83911 as it still reproduces on Main when I disable that phase. Also reproduces in Debug mode + R2R=0 + JitMinOpts=1 so highly unlikely a JIT issue, still looking

**Comment by AndriySvyryd** [comment]
Updating Microsoft.CodeAnalysis.CSharp from 4.2.0 to 4.5.0 resolves this issue. So, it can be closed as far as we are concerned.

**Comment by EgorBo** [comment]
I was bisecting it on locally built runtime and the regression or whatever it was is between [20..25] of march, bisecting

**Comment by EgorBo** [comment]
so far looks like #83484, I'll check before-after in a moment to make sure

**Comment by EgorBo** [comment]
Yes, it's https://github.com/dotnet/runtime/pull/83484 cc @jkotas 

Steps for https://github.com/dotnet/runtime/files/11214690/ReflectionOSX.zip
```bash
# I was doing this using 8.0.100-preview.4.23210.1 SDK 
dotnet publish -c Release -r osx-x64 
```
then I was just executing output binary using corerun from Checked folder 
```
~/prj/runtime/artifacts/bin/coreclr/osx.x64.Checked/corerun \
bin/Release/net8.0/osx-x64/publish/ReflectionOSX.dll
```

**Comment by jkotas** [comment]
@EgorBo Thank you for taking a look!

The problem is in `Type.GetType` API and it affects all platforms (it is not OSX specific). I have updated the description. `assembly.GetType(".GlobalNamespaceContextModel")` is the statement in the repro that triggered the issue.

The issue is that `Type.GetType` implementation had a quirk that made it ignore leading `.` in the type name. The new managed type name parser is missing this quirk.
