### ISSUE TITLE
System.Reflection.NullabilityInfoContext does not correctly determine nullability of members in constructed generics

### ISSUE THREAD

**Issue by webczat** [dotnet/runtime#84647]
I have a type like this:
```cs
public class C<T>
{
    public T Property { get; set; }
}
```

This class is generic and accepts any type, so includes both nullable and non nullable reference types.
When I'd create instances of `C<string>` and `C<string?>` and try to use the property, compiler correctly does null analysis.
However, if I do
```cs
var nc = new NullabilityInfoContext();
var nullability = nc.Create(typeof(C<string>).GetProperty("Property"));
```
Then both it's `ReadState` and `WriteState` members will say `Nullable` instead of `NotNull`.

I encountered this problem by writing some tests related to json serialization and handling nullable reference types. I have a test dto which is generic so that I can test different combinations of nullable and not nullable types and behaviors after my contract customizations are applied.
However it seems that my STJ customizations which utilize NullableInfoContext don't work when the test type is a constructed generic. Which is really unfortunate.

**Comment by buyaa-n** [comment]
This is by design, there is no way to get nullability info from `typeof(C<string>)` or `typeof(C<string?>)`
