### ISSUE TITLE
[API Proposal]: Add StringMarshalling property to GeneratedComInterfaceAttribute

### ISSUE THREAD

**Issue by jtschuster** [dotnet/runtime#84662]
### Background and motivation

GeneratedComInterface does not support string marshalling with a StringMarshalling enum. To match the functionality of LibraryImport, GeneratedComInterface should also allow specifying a StringMarshalling value and an accompanying StringMarshallingCustomType. This would apply for all methods in the interface, as well as methods on interfaces that inherit from it if the inheriting interfaces do not specify their own StringMarshalling.

### API Proposal

```csharp
namespace System.Runtime.InteropServices.Marshalling;

[AttributeUsage(AttributeTargets.Interface)]
public class GeneratedComInterfaceAttribute : Attribute
{
    public StringMarshalling StringMarshalling { get; set; }
    public Type? StringMarshallingCustomType { get; set; }
}
```

### API Usage

Example from crossgen2:
```csharp
    [GeneratedComInterface(StringMarshalling = StringMarshalling.Utf16)]
    [Guid("B029E51B-4C55-4fe2-B993-9F7BC1F10DB4")]
    internal partial interface ISymNGenWriter2 : ISymNGenWriter
    {
        void OpenModW(
                      string wszModule,
                      string wszObjFile,
                      out UIntPtr ppmod);

        void CloseMod(UIntPtr pmod);

        void ModAddSymbols(UIntPtr pmod, [MarshalAs(UnmanagedType.LPArray)] byte[] pbSym, int cb);

        void ModAddSecContribEx(
            UIntPtr pmod,
            ushort isect,
            int off,
            int cb,
            uint dwCharacteristics,
            uint dwDataCrc,
            uint dwRelocCrc);

        void QueryPDBNameExW(
            [MarshalUsing(CountElementName = nameof(cchMax))]
            char[] pdb,
            IntPtr cchMax);
    }
```

### Alternative Designs

We could do a per-method string marshalling attribute, or continue using per-parameter MarshalAs / MarshaUsing attributes.

### Risks

The ComInterfaceGenerator is new, so there aren't risks of regressions or breaking changes. No other risks come to mind.

## Steps
- [x] Generate string marshalling based on the `StringMarshalling` field on the `GeneratedComInterfaceAttribute` https://github.com/dotnet/runtime/pull/86404
- [x] Ensure MarshalAs and MarshalUsing on the parameter/return overrides the interface-wide StringMarshalling https://github.com/dotnet/runtime/pull/86963
- [x] Warn if inherited interfaces don't have the same `StringMarshalling` and `StringMarshallingCustomType` as the base interface. https://github.com/dotnet/runtime/pull/86467
- [ ] ~Warn if the `StringMarshallingCustomType` is less visible than the interface.~ Warn if StringMarshallingCustomType is less visible than 'internal' https://github.com/dotnet/runtime/pull/87065

**Comment by jkoritzinsky** [comment]
Also, I'm unsure if we want to propagate the setting across inheritance boundaries. While it's likely correct, it goes more towards the "spooky-action-at-a-distance" model that we've been trying to actively avoid with source-generated interop. Also, in the past we've discussed introducing an assembly-level attribute to specify the string marshalling rules, which would then conflict with the inheritance-based model if the base type was in a different assembly.

I'd be interested to hear from the rest of the team as well as I might be in the minority here.

**Comment by jtschuster** [comment]
Those are good points, and I think also it could be confusing if we generate shadowing methods for the base interfaces. Maybe it would be best to force StringMarshalling to be the same as the base interface? And if anyone needs different string marshalling than the base, they can use MarshalUsing/MarshalAs.

**Comment by AaronRobinsonMSFT** [comment]
> > While it's likely correct, it goes more towards the "spooky-action-at-a-distance" model that we've been trying to actively avoid with source-generated interop

> Maybe it would be best to force StringMarshalling to be the same as the base interface?

Agreed, and we can easily detect that in the analyzer and force propagation of the setting throughout the heirarchy. The gist is specify it once, it must be specified, and match, for everything below. Anything above should be "okay" because we require it if strings are involved so we should be set. It is sane and matches our expectations for being explicit about string encoding.

**Comment by bartonjs** [comment]
Looks good as proposed

```C#
namespace System.Runtime.InteropServices.Marshalling;

[AttributeUsage(AttributeTargets.Interface)]
public partial class GeneratedComInterfaceAttribute : Attribute
{
    public StringMarshalling StringMarshalling { get; set; }
    public Type StringMarshallingCustomType { get; set; }
}
```

**Comment by AaronRobinsonMSFT** [comment]
[like]  Aaron Robinson reacted to your message:
________________________________

**Comment by AaronRobinsonMSFT** [comment]
[0]     Aaron Robinson reacted to your message:
________________________________
