### ISSUE TITLE
Why is the performance of HttpClient low?

### ISSUE THREAD

**Issue by simpleway2016** [dotnet/runtime#84672]
Here is my test code, accessing a locally running web api program one thousand times took about 31 seconds.
and if i use a socket for access, it only takes 0.3 seconds.

```c#
            var httpclient = new HttpClient();
            var ret = await httpclient.GetAsync("http://127.0.0.1:5005/main/test?name=Jack");

            Stopwatch sw = new Stopwatch();
            sw.Start();
            for (int i = 0; i < 1000; i++)
            {
                ret = await httpclient.GetAsync("http://127.0.0.1:5005/main/test?name=Jack");
            }
            sw.Stop();
            var ms = sw.ElapsedMilliseconds;
```

**Comment by hez2010** [comment]
HttpClient will fetch the whole response message and parse it into headers and body. 

You may want to parallelize your access:

```csharp
var httpclient = new HttpClient();
var ret = await httpclient.GetAsync("http://127.0.0.1:5005/main/test?name=Jack");

Stopwatch sw = new Stopwatch();
sw.Start();
var rets = await Task.WhenAll(Enumerable.Repeat(httpclient.GetAsync("http://127.0.0.1:5005/main/test?name=Jack"), 1000));
sw.Stop();
var ms = sw.ElapsedMilliseconds;
```

**Comment by benaadams** [comment]
Also call `Dispose()` on the returned `HttpResponseMessage`

**Comment by benaadams** [comment]
You need to `.Dispose()` the returned `HttpResponseMessage` to release the request resources which you can do with a `using` statement
```csharp
using System.Diagnostics;

var httpclient = new HttpClient();
Stopwatch sw = new Stopwatch();
sw.Start();
for (int i = 0; i < 1000; i++)
{
    using var ret = await httpclient.GetAsync("http://127.0.0.1:5005/main/test?name=Jack");
}
sw.Stop();
var ms = sw.ElapsedMilliseconds;
```

**Comment by simpleway2016** [comment]
> You need to `.Dispose()` the returned `HttpResponseMessage` to release the request resources which you can do with a `using` statement
> 
> ```cs
> var httpclient = new HttpClient();
> Stopwatch sw = new Stopwatch();
> sw.Start();
> for (int i = 0; i < 1000; i++)
> {
>     using var ret = await httpclient.GetAsync("http://127.0.0.1:5005/main/test?name=Jack");
> }
> sw.Stop();
> var ms = sw.ElapsedMilliseconds;
> ```

Adding dispose does not necessarily speed up the next request of httpclient.

**Comment by ManickaP** [comment]
> when i use a socket to initiate the request, it only takes 1ms.

Do you also get all the data from the server and parse them in your socket tests? Could you share your socket test code so we can see we're comparing similar work being done?

**Comment by antonfirsov** [comment]
@simpleway2016 what is your platform? Can you also share the response from `http://127.0.0.1:5005/main/test?name=Jack`?

**Comment by simpleway2016** [comment]
> @simpleway2016 what is your platform? Can you also share the response from `http://127.0.0.1:5005/main/test?name=Jack`?

Here is my webapi code:

``` cs
        [HttpGet]
        public Task<string> Test(string name)
        {
            return Task.FromResult( "Hello " + name + DateTime.Now.ToString("HH:mm:ss"));
        }
```

**Comment by antonfirsov** [comment]
I cannot reproduce this; for me `HttpClient` is faster for the same scenario. Something weird must be going on in your environment. Do you have any firewalls, proxies configured? Can you share packet captures? (eg. with Wireshark)

**Comment by simpleway2016** [comment]
> I cannot reproduce this; for me `HttpClient` is faster for the same scenario. Something weird must be going on in your environment. Do you have any firewalls, proxies configured? Can you share packet captures? (eg. with Wireshark)

How long does it take for you to request 1000 times using httpclient?

**Comment by simpleway2016** [comment]
> > I cannot reproduce this; for me `HttpClient` is faster for the same scenario. Something weird must be going on in your environment. Do you have any firewalls, proxies configured? Can you share packet captures? (eg. with Wireshark)
> 
> How long does it take for you to request 1000 times using httpclient?  
The webapi must be confirmed to be running in release mode, otherwise using socket requests will also be very slow.

**Comment by antonfirsov** [comment]
> How long does it take for you to request 1000 times using httpclient?

~150ms. I was running everything in release.

**Comment by simpleway2016** [comment]
> > How long does it take for you to request 1000 times using httpclient?
> 
> ~150ms. I was running everything in release.

I have also noticed my problem. The httpclient must be running in release mode to be fast
