### ISSUE TITLE
[API Proposal]: Add Support for ToBase In BigInteger Parsing

### ISSUE THREAD

**Issue by j0nimost** [dotnet/runtime#84684]
### Background and motivation

Given a string, the current implementation of `BigInteger.Parse` and `BigInteger.TryParse` lacks support for ToBase i.e.; 2, 8, 10, 16

### API Proposal

```csharp
// Add Support For String and/or ReadOnlySpan<char>

public static BigInteger Parse(string value, int tobase);
public static BigInteger Parse(ReadOnlySpan<char> value, int tobase);


public static bool TryParse(string value, int tobase, out BigInteger result);
public static bool TryParse(ReadOnlySpan<char> value, int tobase, out BigInteger result);
```

### API Usage

```csharp

// Given a couple of strings; assumption: large strings
string binary = "101010101100";
string hex = "0x34";

ReadOnlySpan<char> binarySpan = binary.AsSpan();
ReadOnlySpan<char> hexSpan = hex.AsSpan();

BigInteger bigIntA = BigInteger.Parse(binary, 2);
BigInteger bigIntA2 = BigInteger.Parse(binarySpan, 2);

_ = BigInteger.TryParse(hex, 16, out BigInteger bigIntOut)
_ = BigInteger.TryParse(hexSpan, 16, out BigInteger bigIntOut2)

// etc.
```

**Comment by tannergooding** [comment]
`Parse` APIs explicitly do not take a `base` parameter. You are expected to call the overloads that take a `System.Globalization.NumberStyles` instead (such as [Parse(string, NumberStyles)](https://learn.microsoft.com/en-us/dotnet/api/system.numerics.biginteger.parse?view=net-7.0#system-numerics-biginteger-parse(system-string-system-globalization-numberstyles))) and pass in the relevant styles.

For `hexadecimal`, this would be `NumberStyles.HexNumber`.
For `binary`, this will be `NumberStyles.BinaryNumber` once we finish implementing https://github.com/dotnet/runtime/issues/83619
