### ISSUE TITLE
[Fuzzlyn] Arm64 failure for negation, cast, bitwise-and

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#84693]
# 1 reduced examples are available
```csharp
// Generated by Fuzzlyn v1.5 on 2023-04-12 13:58:51
// Run on Arm64 MacOS
// Seed: 15653303803842509097
// Reduced from 14.3 KiB to 0.3 KiB in 00:00:10
// Debug: Outputs 255
// Release: Outputs -1
public class Program
{
    public static short s_2;
    public static void Main()
    {
        sbyte vr5 = (sbyte)M8(1);
    }

    public static uint M8(byte arg0)
    {
        s_2 = 1;
        arg0 = (byte)(-s_2);
        var vr1 = arg0 & arg0;
        System.Console.WriteLine(vr1);
        return 0;
    }
}
```

**Comment by TIHan** [comment]
Reproduces on Windows ARM64 as well. Will look into it.

**Comment by TIHan** [comment]
Still looking into the issue. Reproduces even with disabling these optimizations individually and in combination:

- https://github.com/dotnet/runtime/pull/77874
- https://github.com/dotnet/runtime/pull/79630
- https://github.com/dotnet/runtime/pull/82276

Does not reproduce on XARCH.

**Comment by TIHan** [comment]
Disabling the optimization, `fgOptimizeCastOnAssignment`, fixes the issue though I don't think its the cause. I think we are not handling NormalizeOnLoad variables correctly on ARM64.
