### ISSUE TITLE
Include ADO azure-feed:// URI for daily build feeds in dogfooding docs

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#84699]
I'd like to add the preview feed for .NET 8 daily builds as an upstream to our internal ADO feed, so I can more easily try out preview packages without having to just add the feed manually to a configuration file or .csproj file in every single branch where I want to try new stuff. In order to configure the feed though, I need the ADO feed URI in this format:

```
azure-feed://organization/optionalProject/feed@view
```

The [dogfooding docs](https://github.com/dotnet/runtime/blob/main/docs/project/dogfooding.md) only mention the full URL to the public feed, and there isn't an clear/easy way to get the right URI in that ADO format. Would it be possible to list URIs in that format as well, so folks using internal ADO feeds can easily add them?

For reference, this is the public nightly feed for the [Windows Community Toolkit](https://github.com/CommunityToolkit/WindowsCommunityToolkit) (and the .NET Community Toolkit):

```
https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-MainLatest/nuget/v3/index.json
```

And this is the corresponding ADO feed URI for this feed:

```
azure-feed://dotnet/CommunityToolkit-MainLatest@Local
```

Thank you! 🙂

---

> "why can't you use the regular NuGet URL?"

Good question, but I don't have an answer to that. Eg. in our case we've been explicitly told we should use that ADO feed URI format, which is the same one that all of our other additional upstream feeds are also using, for our internal ADO feed.

**Comment by ViktorHofer** [comment]
cc @mmitche

**Comment by mmitche** [comment]
I think this sounds reasonable. It should probably be called out that this is ADO-specific info, typically only useful for Microsoft.

**Comment by mmitche** [comment]
azure-feed://dnceng/public/dotnet8@Local

If you know the NuGet feed URl the azure-feed version is just a combination of the org, project and feed path parameters.

**Comment by ViktorHofer** [comment]
@Sergio0694 do you want to submit the PR that adds the URI to the dogfooding doc?

**Comment by Sergio0694** [comment]
Yup, I can do that! 🙂
Feel free to assign this to me (don't have triage permissions in this repo).
