### ISSUE TITLE
Cmdline arguments are not parsed correctly using System.Environment.CommandLine

### ISSUE THREAD

**Issue by MrM40** [dotnet/runtime#84723]
### Description

**Test1:**
Specified cmdline args with double-quotes: 
`appl.exe -param1 --param2="Hello  World"`

Return by System.Environment.CommandLine:
`"app.exe" -param1 "--param2=Hello  World"` _(the third double-quote is wrongly located infront of `--param2`)_

Expected return:
`"app.exe" -param1 --param2="Hello  World"` 
<br>

**Test2:**
Specified cmdline args with single-quotes: 
`appl.exe -param1 --param2='Hello  World'` _(note **two** whitespaces)_

Return by System.Environment.CommandLine:
`"app.exe" -param1 --param2='Hello World'` _(only **one** whitespace)_

Expected return:
`"app.exe" -param1 --param2='Hello  World'` _(with **two** whitespaces)_
<br>

Could it be possible to keep the argument-string untouched when using `System.Environment.CommandLine` so you can build your own arg-parser?

### Reproduction Steps

..

### Expected behavior

..

### Actual behavior

..

### Known Workarounds

haven't found one :-(

### Configuration

TargetFramework: net6.0
Platforms: x64
RuntimeIdentifiers: win-x64

.NET SDK (reflecting any global.json):
 Version:   6.0.402
 Commit:    6862418796

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64

**Comment by jkotas** [comment]
Related / duplicate https://github.com/dotnet/runtime/issues/11305

**Comment by MrM40** [comment]
@jkotas: These two cases doesn't seem to have anything in common beside `System.Environment.CommandLine`, the issues are completely different. At least remove "duplicate" from your statement, but I would prefer "Another `CommandLine` issue #11305"

**Comment by jkotas** [comment]
The fix for both this issue and https://github.com/dotnet/runtime/issues/11305 would be exactly the same.

**Comment by MrM40** [comment]
"issues" and "solutions" are two different things. You first statement can only be read as referring to issues. 
If you talk about solutions then correct it to "Same solution as #11305" or something similar. This issues are NOT the same.

I know it's nit-picking but things take longer time to solve if communication is not exact.
Please correct and we can delete these noisy last comments.

**Comment by jkotas** [comment]
> I wonder if this issue has been introduces in one of the later runtime versions, 

This issue is present in all .NET Core / .NET 5+ versions. 

> strange if I'm the first to notice after so many years.

IIRC, somebody asked about it before. There is a simple work around:
```
static unsafe string GetRawCommandLine()
{
    return new string(GetCommandLineW());

    [System.Runtime.InteropServices.DllImport("kernel32")]
    static extern char* GetCommandLineW();
}
```
