### ISSUE TITLE
Debugger.IsAttached doesn't work

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#84736]
This expects the .NET Native debugger to flip a private field. Instead we should query the OS (`IsDebuggerPresent` on Windows and ??? on Linux/mac).

https://github.com/dotnet/runtime/blob/887c043eb94be364188e2b23a87efa214ea57f1e/src/coreclr/nativeaot/System.Private.CoreLib/src/System/Diagnostics/Debugger.cs#L41-L44

**Comment by jkotas** [comment]
`Debugger.IsAttached` returns whether proper managed debugger is attached. Attaching unmanaged debuggers (windbg, VS native debugger, etc.) does not make this property return true in regular CoreCLR. I am not sure whether it is a good idea to make this property track unmanaged debuggers in native AOT. It has a good chance to break as many things as it fixes.
