### ISSUE TITLE
Official build failure trying to sign Microsoft.NET.Sdk.WebAssembly.Pack

### ISSUE THREAD

**Issue by sbomer** [dotnet/runtime#84742]
Official builds started failing after https://github.com/dotnet/runtime/pull/84082. Link to build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2156574&view=logs&j=4d50a8bf-a143-51c7-5cc8-defff437e23b&t=24058bbf-eb7e-5a58-7620-a06c45604c2a

The publish stage step `Download Intermediate Artifacts` says it downloaded the package:

```
Downloaded IntermediateArtifacts/MonoRuntimePacks/Shipping/Microsoft.NET.Sdk.WebAssembly.Pack.8.0.0-preview.4.23212.5.nupkg to D:\a\_work\1\s\artifacts\PackageDownload\IntermediateArtifacts\MonoRuntimePacks\Shipping\Microsoft.NET.Sdk.WebAssembly.Pack.8.0.0-preview.4.23212.5.nupkg
```

But the next step `Prepare artifacts and upload to build` fails:

```
D:\a\_work\1\s\src\installer\prepare-artifacts.proj(146,5): error : Item to sign 'Microsoft.NET.Sdk.WebAssembly.Pack.8.0.0-preview.4.23212.5.nupkg' was not found in the artifacts
##[error]src\installer\prepare-artifacts.proj(146,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Item to sign 'Microsoft.NET.Sdk.WebAssembly.Pack.8.0.0-preview.4.23212.5.nupkg' was not found in the artifacts
D:\a\_work\1\s\src\installer\prepare-artifacts.proj(146,5): error : Item to sign 'Microsoft.NET.Sdk.WebAssembly.Pack.8.0.0-preview.4.23212.5.symbols.nupkg' was not found in the artifacts
##[error]src\installer\prepare-artifacts.proj(146,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Item to sign 'Microsoft.NET.Sdk.WebAssembly.Pack.8.0.0-preview.4.23212.5.symbols.nupkg' was not found in the artifacts
  Writing build manifest file 'D:\a\_work\1\s\artifacts\log\Release\AssetManifest/Manifest.xml'...
```

The failure comes from arcade here:
https://github.com/dotnet/arcade/blob/5ec6af6931967583ebedeeccc85c25769de902bc/src/Microsoft.DotNet.Build.Tasks.Feed/src/SigningInformationModelFactory.cs#L54-L60

I believe the `PushToAzureDevOpsArtifacts` invocation here:
https://github.com/dotnet/runtime/blob/887c043eb94be364188e2b23a87efa214ea57f1e/src/installer/prepare-artifacts.proj#L146-L163

includes the new package in `ItemsToSign` (which gets populated from the `PackageDownload` directory mentioned earlier), but not in `ItemsToPush`, and this is what causes the failure. I think the fix would be to add the new package to `NupkgToPublishFile` somewhere in this logic (I'm assuming the package should get published):

https://github.com/dotnet/runtime/blob/887c043eb94be364188e2b23a87efa214ea57f1e/src/installer/prepare-artifacts.proj#L188-L259

@maraf @ViktorHofer

**Comment by lewing** [comment]
We can revert this to unblock if needed

**Comment by lewing** [comment]
@joeloff any thoughts on this one?

**Comment by lewing** [comment]
opened https://github.com/dotnet/runtime/pull/84743 while we look into this

**Comment by maraf** [comment]
This seems like the right pattern  https://github.com/dotnet/runtime/blob/0ac097f594f62b7a13ca9bd3354a9fb94566878a/src/installer/prepare-artifacts.proj#L248-L253

I' curious, I ran the official build for the PR branch yesterday, and it passed. Does this build run something more?

**Comment by maraf** [comment]
Can I somehow validate that https://github.com/dotnet/runtime/pull/84754 really fixes the issue?

**Comment by radical** [comment]
Is this package meant to be downloaded by users? Or is it a transport package for getting some files to the `sdk` repo?

**Comment by maraf** [comment]
@radical It's lind of a transport package used by SDK

**Comment by maraf** [comment]
Found that the validation by `ItemsToSignPostBuild` is turned on by `PostBuildSign=true`, can I set it for my build?

**Comment by radical** [comment]
Naming it like the other transport packages should help at least partially. See https://github.com/dotnet/runtime/blob/1311b8aaf2bd03c2e6c64bd8fdc00c44120b7e7f/src/installer/prepare-artifacts.proj#L255-L257

**Comment by ViktorHofer** [comment]
Yes, if the package is a transport package please name it accordingly, i.e.: https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Internal.Runtime.AspNetCore.Transport/src/Microsoft.Internal.Runtime.AspNetCore.Transport.proj

But is the package really a transport package? Transport package means that the customer will never download it to their machine.

**Comment by maraf** [comment]
> But is the package really a transport package? Transport package means that the customer will never see the package in their local package cache. We use transport packages to transport assets from one repository to the other without every leaking that implementation detail to the customer.

No, that is not the case. The package is similar to `Microsoft.NET.ILLink.Tasks`. 
It's registered here as the "Known*" https://github.com/dotnet/installer/blob/cb3333646b29a90f1777a28bafab779379a79b89/src/redist/targets/GenerateBundledVersions.targets#L409-L411 and used by the SDK
