### ISSUE TITLE
Publishing for linux-arm64 on Linux x64 with NativeAot and StripSymbols uses objcopy instead of aarch64-linux-gnu-objcopy

### ISSUE THREAD

**Issue by JinShil** [dotnet/runtime#84769]
### Describe the bug
The following output shows the problem:
```
dotnet publish -c Release -r linux-arm64 -p:PublishAot=true -p:StripSymbols=true
MSBuild version 17.5.1+f6fdcf537 for .NET
  Generating native code
  objcopy: Unable to recognise the format of the input file `{projectPath}'
/usr/share/dotnet/sdk/7.0.203/Sdks/Microsoft.DotNet.ILCompiler/build/Microsoft.NETCore.Native.targets(358,5): error MSB3073: The command "
/usr/share/dotnet/sdk/7.0.203/Sdks/Microsoft.DotNet.ILCompiler/build/Microsoft.NETCore.Native.targets(358,5): error MSB3073:         "objcopy" --only-keep-debug "{executable_path}" "{executable_path}.dbg" && 
/usr/share/dotnet/sdk/7.0.203/Sdks/Microsoft.DotNet.ILCompiler/build/Microsoft.NETCore.Native.targets(358,5): error MSB3073:         "objcopy" --strip-debug --strip-unneeded "{executable_path}" &&
/usr/share/dotnet/sdk/7.0.203/Sdks/Microsoft.DotNet.ILCompiler/build/Microsoft.NETCore.Native.targets(358,5): error MSB3073:         "objcopy" --add-gnu-debuglink="{executable_path}.dbg" "{executable_path}"" exited with code 1.
```

### To Reproduce

1. Walk over to a Linux x64 computer
2. Create a new .NET console project using .NET 7 SDK
3. Run the above `dotnet publish` command in an attempt to publish it for Linux ARM64
4. Notice that it fails because it is trying to use `objcopy` instead of `aarch64-linux-gnu-objcopy` to strip the symbols

### Further technical details
```
.NET SDK:
 Version:   7.0.203
 Commit:    5b005c19f5

Runtime Environment:
 OS Name:     debian
 OS Version:  11
 OS Platform: Linux
 RID:         debian.11-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.203/

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  6.0.408 [/usr/share/dotnet/sdk]
  7.0.203 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.16 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.16 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by am11** [comment]
The solution is to either set `<ObjCopyName>aarch64-linux-gnu-objcopy` property, or install `llvm-objcopy`, which supports multiple architectures.

**Comment by JinShil** [comment]
> The solution is to either set `<ObjCopyName>aarch64-linux-gnu-objcopy` property, or install `llvm-objcopy`, which supports multiple architectures.

I argue that is a workaround, not a solution.  The build system should be able to determine what tools the system has and make the correct choice. If a supported tool is not available then it should display an error saying so with information about which tools need to be installed.  It should never use the wrong tool.

**Comment by MichalStrehovsky** [comment]
This is the general "crossbuild is difficult to setup" bucket. We now document one way to set it up as part of official docs here: https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/cross-compile#linux. It's unlikely we'd do more tool introspection because it would just be a bugfarm.
