### ISSUE TITLE
[wasm] Provisioning issue - could not find a chrome snapshot folder

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#84774]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=237130
Build error leg or test failing: Build / browser-wasm windows Release LibraryTests / Build product
Pull request: https://github.com/dotnet/runtime/pull/84714

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Could not find a chrome snapshot folder under https://storage.googleapis.com/chromium-browser-snapshots/Win_x64",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

**Comment by lewing** [comment]
we rolled back to an older chrome for the time being
