### ISSUE TITLE
jitformat failing on linux x64

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#84780]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=237232
Build error leg or test failing: Build / Formatting linux x64 / Run jitformat.py
Pull request: https://github.com/dotnet/runtime/pull/84741

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "syntax error near unexpected token",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[238577](https://dev.azure.com/dnceng-public/public/_build/results?buildId=238577)|dotnet/runtime|Run jitformat.py|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/238577/logs/195)|dotnet/runtime#84605|
|[238556](https://dev.azure.com/dnceng-public/public/_build/results?buildId=238556)|dotnet/runtime|Run jitformat.py|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/238556/logs/319)||
|[238510](https://dev.azure.com/dnceng-public/public/_build/results?buildId=238510)|dotnet/runtime|Run jitformat.py|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/238510/logs/223)|dotnet/runtime#84716|
|[238380](https://dev.azure.com/dnceng-public/public/_build/results?buildId=238380)|dotnet/runtime|Run jitformat.py|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/238380/logs/162)||
|[237357](https://dev.azure.com/dnceng-public/public/_build/results?buildId=237357)|dotnet/runtime|Run jitformat.py|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/237357/logs/1571)|dotnet/runtime#84605|
|[238326](https://dev.azure.com/dnceng-public/public/_build/results?buildId=238326)|dotnet/runtime|Run jitformat.py|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/238326/logs/115)|dotnet/runtime#84734|
|[238210](https://dev.azure.com/dnceng-public/public/_build/results?buildId=238210)|dotnet/runtime|Run jitformat.py|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/238210/logs/203)|dotnet/runtime#84772|
|[238204](https://dev.azure.com/dnceng-public/public/_build/results?buildId=238204)|dotnet/runtime|Run jitformat.py|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/238204/logs/213)|dotnet/runtime#84772|
|[237232](https://dev.azure.com/dnceng-public/public/_build/results?buildId=237232)|dotnet/runtime|Run jitformat.py|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/237232/logs/1571)|dotnet/runtime#84741|
|[238043](https://dev.azure.com/dnceng-public/public/_build/results?buildId=238043)|dotnet/runtime|Run jitformat.py|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/238043/logs/199)|dotnet/runtime#84661|
|[237909](https://dev.azure.com/dnceng-public/public/_build/results?buildId=237909)|dotnet/runtime|Run jitformat.py|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/237909/logs/1571)|dotnet/runtime#84765|
|[237995](https://dev.azure.com/dnceng-public/public/_build/results?buildId=237995)|dotnet/runtime|Run jitformat.py|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/237995/logs/166)|dotnet/runtime#84772|
|[237866](https://dev.azure.com/dnceng-public/public/_build/results?buildId=237866)|dotnet/runtime|Run jitformat.py|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/237866/logs/181)|dotnet/runtime#84661|
|[237804](https://dev.azure.com/dnceng-public/public/_build/results?buildId=237804)|dotnet/runtime|Run jitformat.py|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/237804/logs/195)|dotnet/runtime#84748|
|[237792](https://dev.azure.com/dnceng-public/public/_build/results?buildId=237792)|dotnet/runtime|Run jitformat.py|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/237792/logs/180)||
|[237775](https://dev.azure.com/dnceng-public/public/_build/results?buildId=237775)|dotnet/runtime|Run jitformat.py|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/237775/logs/154)|dotnet/runtime#84275|
|[237744](https://dev.azure.com/dnceng-public/public/_build/results?buildId=237744)|dotnet/runtime|Run jitformat.py|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/237744/logs/279)||
|[237666](https://dev.azure.com/dnceng-public/public/_build/results?buildId=237666)|dotnet/runtime|Run jitformat.py|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/237666/logs/209)|dotnet/runtime#84731|
|[237598](https://dev.azure.com/dnceng-public/public/_build/results?buildId=237598)|dotnet/runtime|Run jitformat.py|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/237598/logs/246)|dotnet/runtime#84275|
|[237469](https://dev.azure.com/dnceng-public/public/_build/results?buildId=237469)|dotnet/runtime|Run jitformat.py|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/237469/logs/180)|dotnet/runtime#84748|
|[237373](https://dev.azure.com/dnceng-public/public/_build/results?buildId=237373)|dotnet/runtime|Run jitformat.py|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/237373/logs/172)|dotnet/runtime#84661|
|[237337](https://dev.azure.com/dnceng-public/public/_build/results?buildId=237337)|dotnet/runtime|Run jitformat.py|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/237337/logs/213)|dotnet/runtime#84716|
|[237422](https://dev.azure.com/dnceng-public/public/_build/results?buildId=237422)|dotnet/runtime|Run jitformat.py|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/237422/logs/160)||
|[237416](https://dev.azure.com/dnceng-public/public/_build/results?buildId=237416)|dotnet/runtime|Run jitformat.py|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/237416/logs/132)|dotnet/runtime#83151|
|[237107](https://dev.azure.com/dnceng-public/public/_build/results?buildId=237107)|dotnet/runtime|Run jitformat.py|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/237107/logs/216)|dotnet/runtime#84275|
|[237112](https://dev.azure.com/dnceng-public/public/_build/results?buildId=237112)|dotnet/runtime|Run jitformat.py|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/237112/logs/120)|dotnet/runtime#84275|
|[237002](https://dev.azure.com/dnceng-public/public/_build/results?buildId=237002)|dotnet/runtime|Run jitformat.py|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/237002/logs/190)|dotnet/runtime#84731|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|2|27|27|

**Comment by kunalspathak** [comment]
It seems that we are not able to download the clang tools although the code in the script that verifies the url seems correct. I have sent out https://github.com/dotnet/jitutils/pull/368 to log the download url links.

**Comment by BruceForstall** [comment]
Looks like making available the clang-format/clang-tidy wasn't good enough. Now on linux-x64 we have:

```
Can't find compile_commands.json file. Running configure.
Running: /__w/1/s/src/coreclr/build-runtime.sh x64 Checked configureonly -cmakeargs -DCMAKE_EXPORT_COMPILE_COMMANDS=1
Unhandled exception. System.IO.FileNotFoundException: Could not find file '/__w/1/s/artifacts/obj/coreclr/linux.x64.Checked/compile_commands.json'.
File name: '/__w/1/s/artifacts/obj/coreclr/linux.x64.Checked/compile_commands.json'
   at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at ManagedCodeGen.jitformat.Main(String[] args) in /tmp/tmpe86afm5e/jitutils/src/jit-format/jit-format.cs:line 502
```

So maybe the "configureonly" build is failing?

@jkoritzinsky ideas?

**Comment by BruceForstall** [comment]
Test PR:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=238765&view=logs&jobId=32acbff2-0723-5398-e8b4-f0caab88bd5c&j=32acbff2-0723-5398-e8b4-f0caab88bd5c&t=336ebb8d-7afa-5e0a-21cd-ad905aa5f221

**Comment by BruceForstall** [comment]
Looks like the Docker container is `build.ubuntu.1804.amd64.open`

**Comment by BruceForstall** [comment]
This looks like the same issue as https://github.com/dotnet/runtime/issues/84822: the Docker container used to build changed from centos to mariner

@sbomer @jkoritzinsky @steveisok PTAL

**Comment by BruceForstall** [comment]
This is due to https://github.com/dotnet/runtime/pull/84148

**Comment by BruceForstall** [comment]
I verified the fix with test PR https://github.com/dotnet/runtime/pull/84862
