### ISSUE TITLE
[API Proposal]: Make RegexRunner.CharInClass public instead of protected

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#84783]
### Background and motivation

The RegexRunner class is the public extensibility point via which source-generated regexes plug in (and via which the older CompileToAssembly compiled regexes plugged in).  RegexRunner has a "CharInClass" method that's used by the customized implementations to check whether a character is in a given character class (stored in a particular string representation of that character class).  This method is currently protected.  But the source generator emits some helpers that want access to this method, which forces it to create a type derived from RegexRunner just to expose that member:
```C#
        internal class Base : RegexRunner
        {
            internal static new bool CharInClass(char ch, string charClass) => RegexRunner.CharInClass(ch, charClass);
        }
```
We can instead just make the member public.

### API Proposal

```diff
namespace System.Text.RegularExpressions;

public abstract class RegexRunner
{
-    protected static bool CharInClass(char ch, string charClass);
+    public    static bool CharInClass(char ch, string charClass);
}
```

### API Usage

n/a

**Comment by bartonjs** [comment]
Looks good as proposed, though there was a recommendation to EditorBrowsable-Never the member (or the type, for that matter).

```diff
namespace System.Text.RegularExpressions;

public abstract class RegexRunner
{
-    protected static bool CharInClass(char ch, string charClass);
+    public    static bool CharInClass(char ch, string charClass);
}
```
