### ISSUE TITLE
 Assertion failed 'likelihood >= 0.0' during 'Profile incorporation'

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#84798]
Failed in [libraries-pgo pipeline](https://dev.azure.com/dnceng-public/public/_build?definitionId=145&_a=summary)

https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-84772-merge-ca986f3aaa67420399/System.Collections.Tests/1/console.b3c01543.log?helixlogtype=result

cc @AndyAyersMS

**Comment by AndyAyersMS** [comment]
Hopefully just an issue with subtraction not clamping to zero. I see similar things in the coreclr-pgo runs:
```
Assertion failed 'likelihood <= 1.0' in 'System.Threading.ThreadPoolWorkQueue:Dispatch():bool' during 'Profile incorporation' (IL size 435; hash 0xae85da53; Tier1)
```
