### ISSUE TITLE
Plugin method is ignored without exception if method signature changed

### ISSUE THREAD

**Issue by 2mik** [dotnet/runtime#84836]
### Description

My application uses plugins. Plugin is a separate assembly (dll) that is loaded dynamically on the application start.
Let's say an old plugin version has a method: MyClass.MyMethod(T1 arg1, T2 arg2)
Later a new plugin version has some changes in the same method: MyClass.MyMethod(T1 arg1)
because my plugin's API, supported by the app, changed.

If I put old plugin DLL for the new version of the application, the application tries to call MyClass.MyMethod(T1 arg1) but the plugin implements MyClass.MyMethod(T1 arg1, T2 arg2). Unfortunately, the method call simply ignored without any exception. It's very hard to diagnose. In classic .NET Framework, method not found exception thrown in such case.

### Reproduction Steps

The issue occurs in a quite big application. It would be nice to get some thoughts from the .NET team to clarify how .NET should work in the described situation, and how can I check it deeper on my environment.

### Expected behavior

Exception is called when method not found.

### Actual behavior

Method call is ignored.

### Configuration

.NET6
Windows and Linux, any.
x64
It's not specific to the configuration.

**Comment by jkotas** [comment]
There are no changes between .NET Framework and current .NET in this area. Calling a method that does not exist should produce `MissingMethodException` in both.

Could you please try to create a repro that demonstrates the problem?

**Comment by 2mik** [comment]
The example project is attached: [PluginTest.zip](https://github.com/dotnet/runtime/files/11248986/PluginTest.zip)

**Step 1**
In the classes PluginBase and PluginChild uncomment
`public virtual void DoSomething(int arg1, int arg2)`
and
`public override void DoSomething(int arg1, int arg2)`

and comment
`public virtual void DoSomething(int arg1)`
`public override void DoSomething(int arg1)`

Build the solution and copy results to Folder1.

**Step 2**
In the classes PluginBase and PluginChild comment
`public virtual void DoSomething(int arg1, int arg2)`
and
`public override void DoSomething(int arg1, int arg2)`

and uncomment
`public virtual void DoSomething(int arg1)`
`public override void DoSomething(int arg1)`

Build the solution and copy results to Folder2.

**Step 3**
Inside Folder1:
Copy MyPlugin.dll to the same folder where MainApp.exe is located. Run MainApp.exe
You will get
> MainApp started
> PluginChild.DoSomething arg1=1, arg2=2

Copy MyPlugin.dll from the Folder2 to the Folder1, Run MainApp.exe
> MainApp started
> PluginBase.DoSomething arg1=3

Instead of MissingMethodException the application calls the base method. It does not look as expected.

**Comment by vitek-karas** [comment]
I think the problem here is that:
* The base class has body for the virtual method
* The derived class declares basically a new method (different signature)
* The runtime doesn't see the new method as an override of the base virtual method (different signature)

I would expect the .NET Framework to behave the same in this case.

I would also expect to get an exception if the base class method is abstract (no body) - then the runtime should fail to load the plugin type because it's missing a required override.

Also - if the plugins have their own dependencies and possibly version collisions, the behavior of .NET 6 is different from .NET Framework. You may need to implement load contexts to make that work: https://learn.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support

**Comment by 2mik** [comment]
Thank you for the explanation.
I tested with abstract instead of virtual and got
> System.TypeLoadException: Method 'DoSomething' in type 'MyPlugin.PluginChild' from assembly 'MyPlugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
If the existing behavior with virtual/override method is correct, please close the issue.

**Comment by jkotas** [comment]
Yes, the current behavior with virtual/override method is expected. There is no behavior change between .NET Framework and .NET Core.
