### ISSUE TITLE
[wasm] Assertion failure -- condition 'aname != NULL' not met

### ISSUE THREAD

**Issue by JamieMagee** [dotnet/runtime#84859]
### Description

A default app created using the `wasiconsole` template from the new `wasi-experimental` workload fails to run when loaded from Node.js

### Reproduction Steps

1. `dotnet new wasiconsole`
2. Create `index.mjs` in `bin\Debug\net8.0\wasi-wasm\AppBundle\`. This is taken from [the example in Node.js documentation](https://nodejs.org/docs/latest-v19.x/api/wasi.html)

<details>
<summary>`index.mjs`</summary>

```js
import { readFile } from 'node:fs/promises';
import { WASI } from 'node:wasi';
import { argv, env } from 'node:process';

const wasi = new WASI({
    version: 'preview1',
    args: argv,
    env,
    preopens: {
        '/': './'
    },
});

const importObject = { wasi_snapshot_preview1: wasi.wasiImport };

const wasm = await WebAssembly.compile(
    await readFile(new URL('./dotnet.wasm', import.meta.url)),
);
const instance = await WebAssembly.instantiate(wasm, importObject);

wasi.start(instance);
```

</details>

3. `node --experimental-wasi-unstable-preview1 .\index.mjs`

### Expected behavior

`Hello, Wasi Console!`

### Actual behavior

```sh
(node:36476) ExperimentalWarning: WASI is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[MONO] error: * Assertion at /__w/1/s/src/mono/mono/metadata/appdomain.c:759, condition `aname != NULL' not met
```

### Configuration

.NET 8.0.100-preview.4.23213.27 on Windows 11 x64
Node.js v19.9.0

**Comment by radical** [comment]
For this default case the first argument needs to be the name of the main assembly.

**Comment by JamieMagee** [comment]
Thanks for the tip. I managed to get it working with this change to the args

```diff
const wasi = new WASI({
    version: 'preview1',
+   args: [argv, 'dotnet-wasi'],
-   args: argv
    env,
    preopens: {
        '/': './'
    },
});
```

Where `dotnet-wasi` is the name of my project.

```shell
$ node --experimental-wasi-unstable-preview1 --no-warnings .\index.mjs
Hello, Wasi Console!

```
