### ISSUE TITLE
Upgrading from .NET 7.0.103 -> .NET 7.0.203 breaks code generators

### ISSUE THREAD

**Issue by flabbet** [dotnet/runtime#84882]
### Description

PixiEditor has incremental source generators, after upgrading .NET to 7.0.203 along with Visual Studio 17.5, compilation is no longer possible due to tons of very weird errors. Code generator project is on .NET Standard 2.0
![image](https://user-images.githubusercontent.com/25402427/232200076-85be9d4c-f001-46ec-92ac-8905ed8bbf32.png)

IntelliSense seems to be getting crazy about them too. 

### Reproduction Steps

1. Clone https://github.com/PixiEditor/PixiEditor
2. Try running in Visual Studio 17.5 with .NET 7.0.203

### Expected behavior

Code generators compile correctly, since they did in previous .NET 7 version.

### Actual behavior

Compiler throws a lot of errors, which seems to be totally invalid looking at produced C# code.

### Known Workarounds

Downgrade to .NET 7.0.103

### Configuration

.NET 7.0.203
Windows 11 Pro 10.0.22621
x64
It's not specific to my configuration

**Comment by thomhurst** [comment]
typeof just expects a type, but it's also being passed in a variable name?

`typeof(object property)`
Should be 
`typeof(object)`

**Comment by Tornhoof** [comment]
You're using ``ToDisplayString`` to format Parameters, this ist not a correct use for this API, ``ToDisplayString`` is for human Output.
See https://github.com/dotnet/roslyn/issues/56573#issuecomment-1222453623 for Details.

**Comment by Equbuxu** [comment]
> You're using `ToDisplayString` to format Parameters, this ist not a correct use for this API, `ToDisplayString` is for human Output. See [dotnet/roslyn#56573 (comment)](https://github.com/dotnet/roslyn/issues/56573#issuecomment-1222453623) for Details.

It indeed is the reason our code no longer compiles, the returned value of `ParameterSymbol.ToDisplayString` seems to have changed from being just `<type>` to `<type> <parameter name>`. Thank you all for help
