### ISSUE TITLE
Annotate Task.IsFaulted with MemberNotNullWhen(true, nameof(Exception))

### ISSUE THREAD

**Issue by Bip901** [dotnet/runtime#84884]
### Description

According to the documentation on [Task.IsFaulted](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.isfaulted), when it returns true, [exception](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.exception) is guaranteed to be non-null.

However, the `IsFaulted` property is not marked with [`MemberNotNullWhen(true, nameof(Exception))`](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.membernotnullwhenattribute).

### Reproduction Steps

The following code generates warning CS8597 (Thrown value may be null):

```
Task task = Task.Delay(1000);
if (task.IsFaulted)
{
    throw task.Exception;
    //    ^~~~~~~~~~~~~~  Thrown value may be null
}
```

### Expected behavior

The compiler is aware that `Exception` is not null.

### Actual behavior

The compiler believes that `Exception` may be null.

**Comment by stephentoub** [comment]
It is in .NET 8:
https://github.com/dotnet/runtime/blob/004927625242eaacb357c53b7a3547e9e67a9398/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs#L1525-L1526
