### ISSUE TITLE
ILogger Transform and Enrichment (Including Redaction prototyping)

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#84902]
This issue tracking the work for adding Enrichment support with the logging.

**Comment by tarekgh** [comment]
CC @noahfalk 

@dpk83 I logged this issue to track the work. Feel free to add any needed details.

**Comment by joperezr** [comment]
@tarekgh @noahfalk I assume we have to adjust the milestone for this issue to push out from 8.0 as we are now planning on doing this in the dotnet/extensions layer for now?

**Comment by joperezr** [comment]
Adjusting milestone to mark it as post-GA.
