### ISSUE TITLE
[API Proposal]: Add GetElapsedTime(long) 

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#84945]
### Background and motivation

We've added a useful feature called `TimeProvider.GetElapsedTime(long startingTimestamp, long endingTimestamp)`. However, we've identified another frequently used scenario where users want to calculate the elapsed time from the starting timestamp to the current timestamp. To achieve this, users must currently call:

```C#
timeProvider.GetElapsedTime(startingTimestamp, timeProvider.GetTimestamp());
```

To simplify this process, we propose introducing an overload for GetElapsedTime that allows users to simply call `timeProvider.GetElapsedTime(startingTimestamp)` without having to manually call GetTimestamp() each time they want to calculate the elapsed time.

Also, will be consistent with [Stopwatch.GetElapsedTime(system-int64)](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.stopwatch.getelapsedtime?view=net-7.0#system-diagnostics-stopwatch-getelapsedtime(system-int64))

### API Proposal

```csharp
namespace System
{
    public abstract class TimeProvider
    {
	    /// <summary>
	    /// Gets the elapsed time since the <paramref name="startingTimestamp"/> value retrieved using <see cref="GetTimestamp"/>.
	    /// </summary>
        public TimeSpan GetElapsedTime(long startingTimestamp)
    }
}
```

### API Usage

```csharp

long startingTimestamp = timeProvider.GetTimeStamp();

// .... do some work here

TimeSpan timeProvider.GetElapsedTime(startingTimestamp);

```

**Comment by tarekgh** [comment]
CC @sebastienros @stephentoub

**Comment by bartonjs** [comment]
Looks good as proposed

```C#
namespace System
{
    public partial class TimeProvider
    {
	    /// <summary>
	    /// Gets the elapsed time since the <paramref name="startingTimestamp"/> value retrieved using <see cref="GetTimestamp"/>.
	    /// </summary>
        public TimeSpan GetElapsedTime(long startingTimestamp)
    }
}
```
