### ISSUE TITLE
Missed optimization with `Math.Abs`; Branches generated on x86

### ISSUE THREAD

**Issue by colejohnson66** [dotnet/runtime#84986]
### Description

Given the following C# code:

```cs
using System;
public class C {
    public int M(int input) {
        return Math.Abs(input);
    }
}
```

The JIT generates the following assembly:

```asm
C.M(Int32)
    L0000: push ebp
    L0001: mov ebp, esp
    L0003: test edx, edx
    L0005: jl short L000b
    L0007: mov eax, edx
    L0009: pop ebp
    L000a: ret
    L000b: neg edx
    L000d: jns short L0007
    L000f: call dword ptr [0xaca7330]
    L0015: int3
```

### Configuration

* SharpLab output above: Core CLR 7.0.222.60605 on x86
* Benchmarks below: .NET 7.0.4 (7.0.423.11508), X64 RyuJIT AVX2

### Data

The relevant logic begins with `L0003` and `L0005` where we test for negative values. Negatives branch to `L000b` to be negated, before doing *another* conditional jump on the sign bit (that will always occur) to `L0007` in order to return the value. If the value was already positive, we fall through the conditional jump at `L0005` to `L0007` where we return as normal.

These branches are relatively horrible on modern processors. Especially considering "absolute valuing" a number can be done with branchless code. According to [a StackOverflow question](https://stackoverflow.com/questions/2639173/x86-assembly-abs-implementation), there's many methods to do so. I don't have the knowledge to test implementations of these in the runtime (such as [one that uses `cmov`](https://stackoverflow.com/a/11927940/1350209)), but I made a benchmark of ones I *could* implement. Namely, the [two from this answer](https://stackoverflow.com/a/14194764/1350209) (the libc implementation and one from Hacker's Delight).

### Analysis

To test both positive and negative values, I made a benchmark that contains two tests of each method - one for a positive value and one for a negative.

```cs
public class Benchmark
{
    private int Positive;
    private int Negative;

    [GlobalSetup]
    public void Setup()
    {
        Positive = Math.Abs(Random.Shared.Next());
        Negative = -Positive;
    }

    [Benchmark]
    public int MathAbsPositive() =>
        Math.Abs(Positive);

    [Benchmark]
    public int MathAbsNegative() =>
        Math.Abs(Negative);

    [Benchmark]
    public int HackersDelightPositive()
    {
        int x = Positive;
        return ((x >> 30) | 1) * x;
    }

    [Benchmark]
    public int HackersDelightNegative()
    {
        int x = Negative;
        return ((x >> 30) | 1) * x;
    }

    [Benchmark]
    public int CLibPositive()
    {
        int x = Positive;
        int y = x >> 31;
        return (x ^ y) - y;
    }

    [Benchmark]
    public int CLibNegative()
    {
        int x = Negative;
        int y = x >> 31;
        return (x ^ y) - y;
    }
}
```

|                 Method |      Mean |     Error |    StdDev |    Median |
|----------------------- |----------:|----------:|----------:|----------:|
|        MathAbsPositive | 0.0082 ns | 0.0136 ns | 0.0120 ns | 0.0014 ns |
|        MathAbsNegative | 0.6585 ns | 0.0520 ns | 0.0510 ns | 0.6736 ns |
| HackersDelightPositive | 0.0104 ns | 0.0125 ns | 0.0111 ns | 0.0079 ns |
| HackersDelightNegative | 0.0077 ns | 0.0086 ns | 0.0071 ns | 0.0074 ns |
|           CLibPositive | 0.0141 ns | 0.0191 ns | 0.0170 ns | 0.0084 ns |
|           CLibNegative | 0.0063 ns | 0.0102 ns | 0.0105 ns | 0.0000 ns |

**Comment by tfenise** [comment]
`Math.Abs` throws `OverflowException` if called with `Math.Abs(int.MinValue)`. Your alternative implementations do not have this behaviour.

**Comment by colejohnson66** [comment]
Good point. I changed the benchmark to add `if (x is int.MinValue) throw new OverflowException();` and get these results:

|                 Method |      Mean |     Error |    StdDev |    Median |
|----------------------- |----------:|----------:|----------:|----------:|
|        MathAbsPositive | 0.0071 ns | 0.0153 ns | 0.0150 ns | 0.0000 ns |
|        MathAbsNegative | 0.7150 ns | 0.0472 ns | 0.0525 ns | 0.7252 ns |
| HackersDelightPositive | 0.0544 ns | 0.0118 ns | 0.0104 ns | 0.0546 ns |
| HackersDelightNegative | 0.1509 ns | 0.0411 ns | 0.0520 ns | 0.1565 ns |
|           CLibPositive | 0.0537 ns | 0.0127 ns | 0.0118 ns | 0.0513 ns |
|           CLibNegative | 0.0719 ns | 0.0237 ns | 0.0210 ns | 0.0684 ns |
