### ISSUE TITLE
JSSignatureContext.cs may include incorrect use of Math.Abs

### ISSUE THREAD

**Issue by tfenise** [dotnet/runtime#84996]
https://github.com/dotnet/runtime/blob/790b14bc1c1dfeacaff248622b1b0f19ddd5acab/src/libraries/System.Runtime.InteropServices.JavaScript/gen/JSImportGenerator/JSSignatureContext.cs#L49-L58

The last line does not seem correct. If `(int)hash == int.MinValue`, `Math.Abs` would throw, which I suppose is not the intended behaviour for a hash function. I would suggest simply `int typesHash = (int)hash & int.MaxValue;`, or if the hash code is required to be persistent across versions, `int typesHash = (int)hash == int.MinValue ? int.MaxValue : Math.Abs((int)hash)`.

**Comment by EgorBo** [comment]
It should've used `HashCode.Combine` but I'm not familiar with what this API does and if the changed hash code impl is a breaking change or not

**Comment by pavelsavara** [comment]
It doesn't have to be consistent across versions. This just prevents conflict in the names on the same assembly, type and method name.

**Comment by MichalStrehovsky** [comment]
The fix was reverted in #110599
