### ISSUE TITLE
System.PlatformNotSupportedException: Algorithm 'RC2' is not supported on this platform.

### ISSUE THREAD

**Issue by SepuWeb** [dotnet/runtime#85019]
### Description

I'm trying to convert my Xamarin App into new .NET MAUI.

This works in Xamarin:

string path = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData) + "/cert_with_key.pfx";
byte[] rawData= File.ReadAllBytes(path);
X509Certificate2 cert = new X509Certificate2(rawData, privKeyPSW); ----->this throw the following error

{System.Security.Cryptography.CryptographicException: The certificate data cannot be read with the provided password, the password may be incorrect.
 ---> System.PlatformNotSupportedException: Algorithm 'RC2' is not supported on this platform.

### Steps to Reproduce

1. Create a File > New .NET MAUI App
2. Create a pfx file with this name cert_with_key.pfx in application folder with a password
3. And use the code in the description
4. Excute on Android Device

### Link to public reproduction project repository

no

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android from 10 

### Did you find any workaround?

No

### Relevant log output

```shell
{System.Security.Cryptography.CryptographicException: The certificate data cannot be read with the provided password, the password may be incorrect.
 ---> System.PlatformNotSupportedException: Algorithm 'RC2' is not supported on this platform.
   at System.Security.Cryptography.PasswordBasedEncryption.CreateRC2()
   at System.Security.Cryptography.PasswordBasedEncryption.Decrypt(AlgorithmIdentifierAsn& algorithmIdentifier, ReadOnlySpan`1 password, ReadOnlySpan`1 passwordBytes, ReadOnlySpan`1 encryptedData, Span`1 destination)
   at System.Security.Cryptography.X509Certificates.UnixPkcs12Reader.DecryptSafeContents(ReadOnlySpan`1 password, ContentInfoAsn& safeContentsAsn)
   at System.Security.Cryptography.X509Certificates.UnixPkcs12Reader.DecryptAndProcessSafeContents(ReadOnlySpan`1 password, CertBagAsn[]& certBags, AttributeAsn[][]& certBagAttrs, Int32& certBagIdx, SafeBagAsn[]& keyBags, Int32& keyBagIdx)
   at System.Security.Cryptography.X509Certificates.UnixPkcs12Reader.Decrypt(ReadOnlySpan`1 password, ReadOnlyMemory`1 authSafeContents)
   at System.Security.Cryptography.X509Certificates.UnixPkcs12Reader.VerifyAndDecrypt(ReadOnlySpan`1 password, ReadOnlyMemory`1 authSafeContents)
   at System.Security.Cryptography.X509Certificates.UnixPkcs12Reader.Decrypt(SafePasswordHandle password, Boolean ephemeralSpecified)
   --- End of inner exception stack trace ---
   at System.Security.Cryptography.X509Certificates.UnixPkcs12Reader.Decrypt(SafePasswordHandle password, Boolean ephemeralSpecified)
   at System.Security.Cryptography.X509Certificates.AndroidCertificatePal.ReadPkcs12(ReadOnlySpan`1 rawData, SafePasswordHandle password, Boolean ephemeralSpecified)
   at System.Security.Cryptography.X509Certificates.AndroidCertificatePal.FromBlob(ReadOnlySpan`1 rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.CertificatePal.FromBlob(ReadOnlySpan`1 rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, String password)
```

**Comment by steveisok** [comment]
According to https://github.com/dotnet/runtime/issues/45741, RC2 is not supported in .NET.  Originally, I had thought it was an underlying Android API problem, but https://developer.android.com/reference/javax/crypto/spec/RC2ParameterSpec made me think otherwise. 

Tagging @simonrozsival for awareness.

**Comment by jkoritzinsky** [comment]
RC2 isn't listed on the supported ciphers on Android's documentation https://developer.android.com/reference/javax/crypto/Cipher

I think it used to support RC2 and the support was removed.

**Comment by SepuWeb** [comment]
Ok, but I don't use RC2, I use that function: new X509Certificate2(rawData, privKeyPSW); 

and the cert_with_key.pfx was created using RSA using this code:

`X509Name name = new X509Name("CN=" + CN);

            AsymmetricCipherKeyPair ackp = await Task.Run(() =>
            {
                try
                {
                  
                    RsaKeyPairGenerator rkpg = new RsaKeyPairGenerator();
                    var random = new SecureRandom();
                    var gen = new KeyGenerationParameters(random, 2048);
                    rkpg.Init(gen);
                    return rkpg.GenerateKeyPair();
                }
                catch (Exception ex)
                {
                    Debug.WriteLine(ex.ToString());
                    return null;
                }
            });

            //PKCS #10 Certificate Signing Request
            Pkcs10CertificationRequest csr = new Pkcs10CertificationRequest("SHA256WITHRSA", name, ackp.Public, null, ackp.Private);

            //Convert BouncyCastle CSR to .PEM file.
            StringBuilder CSRPem = new StringBuilder();
            PemWriter CSRPemWriter = new PemWriter(new StringWriter(CSRPem));
            CSRPemWriter.WriteObject(csr);
            CSRPemWriter.Writer.Flush();

            //Convert BouncyCastle Private Key to .PEM file.
            StringBuilder PrivateKeyPem = new StringBuilder();
            PemWriter PrivateKeyPemWriter = new PemWriter(new StringWriter(PrivateKeyPem));
            PrivateKeyPemWriter.WriteObject(ackp.Private);
            CSRPemWriter.Writer.Flush();

            File.WriteAllText(cert_with_key_path, PrivateKeyPem.ToString());`

**Comment by bartonjs** [comment]
The code you shared looks like it would have created two PEM files, something else was involved in making the PFX (perhaps an `openssl pkcs12` command?)

**Comment by SepuWeb** [comment]
Thanks @bartonjs, no, nothing else, if you look I use a Pkcs10CertificationRequest.

**Comment by bartonjs** [comment]
PKCS#10 is certificate requests.  PFX is PKCS#12.  They're not really related (just produced by the same standards group).

Your code sample for what went wrong is loading `cert_with_key.pfx`; which does seem to be a real PFX (based on the callstack).  Your snippet saying how you created `cert_with_key.pfx` doesn't actually create that file.  (A cert+key PEM, or CSR+key PEM would not end up in `UnixPkcs12Reader.Decrypt`)

**Comment by SepuWeb** [comment]
My fault, I got confused.
In the resources I have a .pfx file that I set up as MAUI Asset. 
Before running the function written in the first post I run this:

` private async Task SaveCertToDiskAsync()
        {
var resName = "certificate.pfx";
var fileToSave = "cert_with_key.pfx";
 using var stream = await FileSystem.OpenAppPackageFileAsync(resName);
            byte[] arrByte = ReadFully(stream);

            File.WriteAllBytes(fileToSave, arrByte);
        }

 private byte[] ReadFully(Stream input)
        {
            byte[] buffer = new byte[16 * 1024];
            using (MemoryStream ms = new MemoryStream())
            {
                int read;
                while ((read = input.Read(buffer, 0, buffer.Length)) > 0)
                {
                    ms.Write(buffer, 0, read);
                }
                return ms.ToArray();
            }
        }`

**Comment by JairJr** [comment]
I have the same problem during a migration to MAUI, during the authentication a client certificate that was created using RC2 ciphers thats is dynamic and i don't have any workarround for moment. I use a built-in certificate that i upgrade the ciphers via powershell import/export. on Xamarin its works fine too.

**Comment by SepuWeb** [comment]
Thank you @JairJr, do you use some plugin like BouncyCastle? or Portable Bouncy Castle?

**Comment by steveisok** [comment]
> Thank you @JairJr, do you use some plugin like BouncyCastle? or Portable Bouncy Castle?

Might be worth a try.

It seems that's the reason RC2 is no longer working with the Android API's. Looks like they had a bouncy castle dependency and dropped it completely. 

Since there's nothing we can do on our side, I'm going to close this issue.

**Comment by JairJr** [comment]
> Thank you @JairJr, do you use some plugin like BouncyCastle? or Portable Bouncy Castle?

I upgaded the certificate on powershell just with pfx import and export
