### ISSUE TITLE
Methods that take a function pointer can't be reflection invoked

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#85028]
This works in .NET 7 but throws in .NET 8.

```csharp
unsafe class Program
{
    static void Main()
    {
        typeof(Program).GetMethod("Fnptr").Invoke(null, new object[] { IntPtr.Zero });
    }

    public static void Fnptr(delegate*<void> d) { }
}
```

I can't find a place in the design doc (#282) where this would be conscious choice. There's a discussion of a potential `System.Reflection.FunctionPointer` that would work similar to `System.Reflection.Pointer` but that is orthogonal - `System.Reflection.Pointer` and a boxed `IntPtr`/`UIntPtr` can be used interchangeably as far as reflection is concerned.

To add to the confusion, if the method _returns_ a `delegate*`, we do allow reflection invoking it and the result will be a boxed `IntPtr`. Similarly, if the method takes a `delegate*` as an out parameter, we will box it as `IntPtr`.

There's a similar issue with `FieldInfo.SetValue` for a `delegate*`-typed field where we do allow `IntPtr` (but confusingly don't allow `UIntPtr`).

This inconsistency seems jarring.

**Comment by MichalStrehovsky** [comment]
A thing this also implies is that introducing `System.Reflection.FunctionPointer` will likely necessitate a breaking change if we want to be consistent with normal pointers - the places in reflection that _return_ pointers return a `S.R.Pointer`, not a boxed `IntPtr`. We currently return a boxed `IntPtr`.

So the question is also whether we want to be done with function pointer breaking changes in .NET 8, or postpone this one further. .NET 8 feels like a good opportunity since we're making a breaking change around this anyway.

**Comment by steveharter** [comment]
> and a boxed IntPtr/UIntPtr can be used interchangeably as far as reflection is concerned.

In v7 core, only IntPtr can be used.

**Comment by steveharter** [comment]
> To add to the confusion, if the method returns a delegate*, we do allow reflection invoking it and the result will be a boxed IntPtr. Similarly, if the method takes a delegate* as an out parameter, we will box it as IntPtr.

> A thing this also implies is that introducing System.Reflection.FunctionPointer will likely necessitate a breaking change if we want to be consistent with normal pointers - the places in reflection that return pointers return a S.R.Pointer, not a boxed IntPtr. We currently return a boxed IntPtr.

The lack of support for System.Pointer was called out in the design: https://github.com/dotnet/designs/pull/282/files#diff-aa1be871163360183955101af051dd78199829d1cdb52d20b398651bd3240d88R503

Although supporting Pointer would be consistent, it also introduces a significant perf hit since it is a reference type (why was that, btw?). I think adding a System.FunctionPointer value type would be better, but overkill IMO.

**Comment by steveharter** [comment]
Closing as fixed from https://github.com/dotnet/runtime/pull/90270.

We could create a v9 issue to support `System.Pointer` or some other mechanism for a function pointer return value based on feedback \ priority.
