### ISSUE TITLE
[System.Text.Json] JsonSerializer.Deserialize hangs forever deserializing when Newtonsoft.Json's JsonConvert.DeserializeObject does not

### ISSUE THREAD

**Issue by QuantumToasted** [dotnet/runtime#85033]
### Description

I am trying to deserialize the following input JSON via `JsonSerializer.Deserialize<LfsBatchTransferRequest>(json)`:
(See **Reproduction Steps** for the class/record hierarchy)
```json
{
    "operation": "download",
    "transfers": [ "basic" ],
    "objects": [
        {
            "oid": "ee58b157beb74e3b4dc0ec25556ed376ced3bfe4412094834902b0267c5d1a27",
            "size": 62409
        }
    ]
}
```

Upon calling this method, execution never completes, and memory usage begins rising extremely quickly - Almost 1GB of memory every 5 seconds!!!

Deserializing via Newtonsoft.Json's `JsonConvert.DeserializeObject<LfsBatchTransferRequest>(json)` completes immediately, successfully, and with no hassle.

### Reproduction Steps

Disclaimer: All objects being deserialized to are `record`s. If this is the cause, please let me know, and I will revise my code to see if the issue persists with classes instead.

```cs
public enum LfsOperation
{
    [EnumMember(Value = "upload")]
    Upload,
    [EnumMember(Value = "download")]
    Download
}

public record LfsTransfer(string Type)
{
    public static LfsTransfer Basic => new("basic");

    public static implicit operator string(LfsTransfer transfer)
        => transfer.Type;

    public static implicit operator LfsTransfer(string s)
        => new(s);
}

public record LfsRequestObjectRef(
    [property: JsonPropertyName("name")] 
        string Name);

public record LfsRequestObject(
    [property: JsonPropertyName("oid")] 
        string Hash, 
    [property: JsonPropertyName("size")] 
        long Size);
    
public record LfsBatchTransferRequest(
    [property: JsonPropertyName("operation"), JsonConverter(typeof(JsonStringEnumConverter))] 
        LfsOperation Operation,
    [property: JsonPropertyName("objects")] 
        ICollection<LfsRequestObject> Objects,
        ICollection<LfsTransfer>? Transfers = null,
    [property: JsonPropertyName("ref"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] 
        LfsRequestObjectRef? Ref = null,
        string? HashAlgorithm = null)
{
    public static class HashAlgorithms
    {
        public const string SHA256 = "sha256";
    }
    
    [JsonPropertyName("transfers"), JsonConverter(typeof(LfsTransferCollectionJsonConverter))]
    public ICollection<LfsTransfer> Transfers { get; init; } = Transfers ?? new[] { LfsTransfer.Basic };

    [JsonPropertyName("hash_algo")]
    public string HashAlgorithm { get; init; } = HashAlgorithm ?? HashAlgorithms.SHA256;
}

public class LfsTransferCollectionJsonConverter : JsonConverter<ICollection<LfsTransfer>>
{
    public override ICollection<LfsTransfer> Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var transfers = new List<LfsTransfer>();
        
        if (reader.TokenType != JsonTokenType.StartArray || !reader.Read())
            throw new JsonException("Invalid array start, or failed to read array start.");

        while (reader.TokenType != JsonTokenType.EndArray)
        {
            transfers.Add(JsonSerializer.Deserialize<string>(ref reader, options)!);
        }

        return transfers;
    }

    public override void Write(Utf8JsonWriter writer, ICollection<LfsTransfer> value, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        
        foreach (var transfer in value)
        {
            writer.WriteStringValue(transfer.Type);
        }
        
        writer.WriteEndArray();
    }
}
```

### Expected behavior

Deserialization should complete succesfully, or throw an exception if there is an issue with the JSON or the types I am deserializing to.

### Actual behavior

Trying to deserialize the JSON using the code above causes execution to never complete and hang, and memory usage begins rising extremely quickly.

### Regression?

Not known - I have just started using System.Text.Json to see if I can effectively replace Newtonsoft.Json entirely in my project.

### Known Workarounds

Using Newtonsoft.Json.

### Configuration

.NET 7, this is an ASP.NET Web API project utilizing Minimal APIs.

### Other information

I am aware that STJ is not generally intended to be a drop-in replacement for Newtonsoft.Json when it comes to certain things, and I am still learning what works out of the box and what needs "guidance" for converting existing models to support STJ - but this seems quite strange given the circumstances.

**Comment by Tornhoof** [comment]
Did you actually debug your repro code?
Your custom Converter never calls reader.Read() in your while loop, i.e. your list will simply add the same string an infinite times.
Try something like this
```csharp
            public override ICollection<LfsTransfer> Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
            {
                var transfers = new List<LfsTransfer>();

                if (reader.TokenType != JsonTokenType.StartArray)
                    throw new JsonException("Invalid array start");


                while (reader.Read() && reader.TokenType != JsonTokenType.EndArray)
                {
                    transfers.Add(JsonSerializer.Deserialize<string>(ref reader, options)!);
                }

                return transfers;
            }
```
having said that, instead of calling ``Deserialize`` in your while loop, you can simply use ``reader.GetString()``

**Comment by QuantumToasted** [comment]
My apologies, I never properly debugged the deserialization because I truly had no reason to believe the JsonConverter was at fault here. I must've missed adding the `reader.Read()` to the while loop. Fixing the code as you described resolved the issue immediately.
