### ISSUE TITLE
System.Net.Http.Enterprise.Tests build failing in CI

### ISSUE THREAD

**Issue by rzikm** [dotnet/runtime#85035]
Likely caused by https://github.com/dotnet/runtime/pull/84148

[Build fails with](https://dev.azure.com/dnceng-public/public/_build/results?buildId=243440&view=logs&j=03b95830-93c2-599b-7e4d-1efb940adc28&t=9abf97cd-b4a3-5a26-6cf2-d05ce865f2ef&l=3907)
```
##[error]clang(0,0): error : (NETCORE_ENGINEERING_TELEMETRY=Build) invalid linker name in argument '-fuse-ld=lld'
```

Docker image used: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04

**Comment by jkotas** [comment]
https://github.com/dotnet/runtime/pull/84795
