### ISSUE TITLE
System.Text.RegularExpressions.Tests segmentation fault

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#85046]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=243484
Build error leg or test failing: System.Text.RegularExpressions.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/85006

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "BuildRetry": false,
  "ErrorPattern": "Segmentation fault.*System.Text.RegularExpressions.Tests",
  "ExcludeConsoleLog": false
}
```
----
```
/private/tmp/helix/working/A7ED0907/w/A48708BB/e /private/tmp/helix/working/A7ED0907/w/A48708BB/e
  Discovering: System.Text.RegularExpressions.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Text.RegularExpressions.Tests (found 329 of 357 test cases)
  Starting:    System.Text.RegularExpressions.Tests (parallel test collections = on, max threads = 6)
./RunTests.sh: line 168: 33008 Segmentation fault: 11  "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.Text.RegularExpressions.Tests.runtimeconfig.json --depsfile System.Text.RegularExpressions.Tests.deps.json xunit.console.dll System.Text.RegularExpressions.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
/private/tmp/helix/working/A7ED0907/w/A48708BB/e
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by stephentoub** [comment]
Looks like there's no dump or further information?

**Comment by steveharter** [comment]
Closing; no new hits since it was created 3.5 months ago.

Re-open if this occurs again; ideally with additional info.
