### ISSUE TITLE
[browser][MT] Keep track of additional JS keepalive sources for worker threads

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#85052]
In https://github.com/dotnet/runtime/pull/84492 we added `WebWorkerEventLoop.HasUnsettledInteropPromises` that will be used by https://github.com/dotnet/runtime/pull/84494 to keep a threadpool worker thread alive in the JS event loop as long as some promise exists that is needed by a `JSImport`ed `Task` in C#.

There could be, however, other reasons why a threadpool worker thread may need to stay alive:  if the JS code has used `setTimeout` with a callback that depends on a JS proxy of a C# function or object, for example.  These additional scenarios can be somewhat covered by creating promises that the C# code could `await`, but we should also have more robust tracking in our interop layer.

**Comment by pavelsavara** [comment]
I think we will solve this by not allowing JS interop from managed thread pool. Eventually by dispatching the JS calls to original web worker or UI thread. And possibly by explicit API for creating `WebWorker` which could have JS interop, such worker would have keep alive right by design.
