### ISSUE TITLE
Assertion failed 'IsBaselineSimdIsaSupportedDebugOnly()'  during 'Lowering nodeinfo' 

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#85059]
Repros on windows/x64:

```
Environment:
set COMPlus_JitAggressiveInlining=1
set COMPlus_TieredCompilation=0
set COMPlus_EnableHWIntrinsic=0
```

Repro: https://gist.github.com/kunalspathak/ba3555754d6c6b830d9d6e5e54211b3a

**Comment by tannergooding** [comment]
What commit was this tested against? @EgorBo got a fix in, I believe yesterday, for the memcmp issue.

**Comment by kunalspathak** [comment]
This was tested on weekend. But I just verified on main and doesn't seem to repro, so it could be Egor's fix.
