### ISSUE TITLE
GeneratedConfigurationBinder type is generated with no content

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#85057]
### Description

I noticed that when using `Microsoft.Extensions.Configuration.Binder.SourceGeneration` and having no types that would trigger it, it still adds the `GeneratedConfigurationBinder` to my assembly.

### Reproduction Steps

File -> new project.
Add reference to Microsoft.Extensions.Configuration.Binder 8.0.0-*
Enable the generator with property.
Examine compiled assembly.

### Expected behavior

No GeneratedConfigurationBinder type

### Actual behavior

GeneratedConfigurationBinder type exists

### Known Workarounds

Disable the generator.

**Comment by layomia** [comment]
[Fixed](https://github.com/dotnet/runtime/blob/5a24757eab72279dcc28f2359ef5771b279efc59/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/SourceGenerationTests/ConfigurationBindingGeneratorTests.Baselines.cs#L509).
