### ISSUE TITLE
CipherMode.CFB does not Encrypt without changing FeedbackSize (DES)

### ISSUE THREAD

**Issue by xairaven** [dotnet/runtime#85079]
### Background and motivation

I'm not very into cryptography, but I had to try to work with DES and encryption modes. I noticed that CFB mode is not working - I have an exception: 
```
System.Security.Cryptography.CryptographicException: The specified feedback size '64' for CipherMode 'CFB' is not supported.
```
My code:
```csharp
using (var cipher = DES.Create())
        {
            cipher.Mode = CipherMode.CFB;
           

            var encryptor = cipher.CreateEncryptor();
            ...
```
Saw the same issue, but with AES and TripleDES here: #43234 
After the fix (?), this exception does not occur with AES and TripleDES with same mode (CFB).

Fixed it with:
```csharp
FeedbackSize = 8;
```
Is it problem or not? If yes, then my suggestion is to change the default value of FeedbackSize for DES to 8.

Exception invokes here:
```
   at System.Security.Cryptography.DesImplementation.ValidateCFBFeedbackSize(Int32 feedback)
   at System.Security.Cryptography.DesImplementation.CreateTransform(Byte[] rgbKey, Byte[] rgbIV, Boolean encrypting)
```
```csharp
private static void ValidateCFBFeedbackSize(int feedback)
        {
            // only 8bits feedback is available on all platforms
            if (feedback != 8)
            {
                throw new CryptographicException(string.Format(SR.Cryptography_CipherModeFeedbackNotSupported, feedback, CipherMode.CFB));
            }
        }
```

I did a test console app to reproduce this on .NET 7.

### API Proposal

To set default FeedbackSize to 8 bytes (?)

### API Usage

No extra line needed:

```csharp
cipher.FeedbackSize = 8;
```

**Comment by vcsjones** [comment]
I think we can reasonably change the default to 8 for `DESImplementation`. In fact, that's what `DESCryptoServiceProvider` defaults to [for .NET Framework][1], so would actually improve the situation for the defaults when `DES.Create()` is used.

Also it's the only value that works, so that further justifies it.


[1]: https://referencesource.microsoft.com/#mscorlib/system/security/cryptography/descryptoserviceprovider.cs,25
