### ISSUE TITLE
System.Security.Cryptography.Tests CertTests.RaceDisposeAndKeyAccess failing

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#85073]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=235406
Build error leg or test failing: System.Security.Cryptography.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/81059

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "at Interop.Crypto.EvpPKeyDuplicate",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```
```log
Process terminated. Assertion failed.
   at Interop.Crypto.EvpPKeyDuplicate(SafeEvpPKeyHandle currentKey, EvpAlgorithmId algorithmId) in /_/src/libraries/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.EvpPkey.cs:line 25
   at System.Security.Cryptography.RSAOpenSsl..ctor(SafeEvpPKeyHandle pkeyHandle) in /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/RSAOpenSsl.cs:line 76
   at System.Security.Cryptography.X509Certificates.OpenSslX509CertificateReader.GetRSAPrivateKey() in /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/OpenSslX509CertificateReader.cs:line 556
   at System.Security.Cryptography.X509Certificates.CertificateExtensionsCommon.GetPrivateKey[T](X509Certificate2 certificate, Predicate`1 matchesConstraints) in /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/CertificateExtensionsCommon.cs:line 61
   at System.Security.Cryptography.X509Certificates.RSACertificateExtensions.GetRSAPrivateKey(X509Certificate2 certificate) in /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/RSACertificateExtensions.cs:line 27
   at System.Security.Cryptography.X509Certificates.Tests.CertTests.<>c.<RaceDisposeAndKeyAccess>b__4_1(Object cert) in /_/src/libraries/System.Security.Cryptography/tests/X509Certificates/CertTests.cs:line 54
./RunTests.sh: line 168:    24 Aborted                 (core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.Security.Cryptography.Tests.runtimeconfig.json --depsfile System.Security.Cryptography.Tests.deps.json xunit.console.dll System.Security.Cryptography.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
/root/helix/work/workitem/e
----- end Wed 12 Apr 2023 12:33:49 AM UTC ----- exit code 134 ----------------------------------------------------------
exit code 134 means SIGABRT Abort. Managed or native assert, or runtime check such as heap corruption, caused call to abort(). Core dumped.
ulimit -c value: unlimited
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[277117](https://dev.azure.com/dnceng-public/public/_build/results?buildId=277117)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=277117&view=ms.vss-test-web.build-test-results-tab&runId=5495770&resultId=194702)|dotnet/runtime#86400|
|[272007](https://dev.azure.com/dnceng-public/public/_build/results?buildId=272007)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=272007&view=ms.vss-test-web.build-test-results-tab&runId=5372370&resultId=198760)|dotnet/runtime#85551|
|[269809](https://dev.azure.com/dnceng-public/public/_build/results?buildId=269809)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=269809&view=ms.vss-test-web.build-test-results-tab&runId=5320260&resultId=198753)|dotnet/runtime#86076|
|[269059](https://dev.azure.com/dnceng-public/public/_build/results?buildId=269059)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=269059&view=ms.vss-test-web.build-test-results-tab&runId=5305666&resultId=198701)|dotnet/runtime#86007|
|[268930](https://dev.azure.com/dnceng-public/public/_build/results?buildId=268930)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=268930&view=ms.vss-test-web.build-test-results-tab&runId=5302624&resultId=198689)|dotnet/runtime#85913|
|[255939](https://dev.azure.com/dnceng-public/public/_build/results?buildId=255939)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=255939&view=ms.vss-test-web.build-test-results-tab&runId=4990044&resultId=198656)|dotnet/runtime#84494|
|[251855](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251855)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251855&view=ms.vss-test-web.build-test-results-tab&runId=4885922&resultId=194542)|dotnet/runtime#85343|
|[248075](https://dev.azure.com/dnceng-public/public/_build/results?buildId=248075)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=248075&view=ms.vss-test-web.build-test-results-tab&runId=4788282&resultId=199053)|dotnet/runtime#85000|
|[246147](https://dev.azure.com/dnceng-public/public/_build/results?buildId=246147)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=246147&view=ms.vss-test-web.build-test-results-tab&runId=4749162&resultId=199044)|dotnet/runtime#85111|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|9|

**Comment by vcsjones** [comment]
Hm. Looks like a real race condition, but no idea why it just started failing. The test has been there for a while.

I'll take a look.
