### ISSUE TITLE
Unable to load Analyzer assembly .../Microsoft.CodeAnalysis.Analyzers.dll : Not a valid assembly

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#85082]
```
  Restored /__w/1/s/src/coreclr/tools/SuperFileCheck/SuperFileCheck.csproj (in 5.22 sec).
  Restored /__w/1/s/src/coreclr/tools/dotnet-pgo/dotnet-pgo.csproj (in 8.42 sec).
  Restored /__w/1/s/src/coreclr/tools/aot/crossgen2/crossgen2.csproj (in 5.66 sec).
CSC : error CS8034: Unable to load Analyzer assembly /__w/1/s/.packages/microsoft.codeanalysis.analyzers/3.3.3/analyzers/dotnet/cs/Microsoft.CodeAnalysis.Analyzers.dll : Not a valid assembly: /__w/1/s/.packages/microsoft.codeanalysis.analyzers/3.3.3/analyzers/dotnet/cs/Microsoft.CodeAnalysis.Analyzers.dll [/__w/1/s/src/libraries/System.Private.CoreLib/gen/System.Private.CoreLib.Generators.csproj]
##[error]CSC(0,0): error CS8034: (NETCORE_ENGINEERING_TELEMETRY=Build) Unable to load Analyzer assembly /__w/1/s/.packages/microsoft.codeanalysis.analyzers/3.3.3/analyzers/dotnet/cs/Microsoft.CodeAnalysis.Analyzers.dll : Not a valid assembly: /__w/1/s/.packages/microsoft.codeanalysis.analyzers/3.3.3/analyzers/dotnet/cs/Microsoft.CodeAnalysis.Analyzers.dll
CSC : error CS8032: An instance of analyzer Microsoft.CodeAnalysis.CSharp.Analyzers.CSharpImmutableObjectMethodAnalyzer cannot be created from /__w/1/s/.packages/microsoft.codeanalysis.analyzers/3.3.3/analyzers/dotnet/cs/Microsoft.CodeAnalysis.CSharp.Analyzers.dll : Exception has been thrown by the target of an invocation.. [/__w/1/s/src/libraries/System.Private.CoreLib/gen/System.Private.CoreLib.Generators.csproj]
##[error]CSC(0,0): error CS8032: (NETCORE_ENGINEERING_TELEMETRY=Build) An instance of analyzer Microsoft.CodeAnalysis.CSharp.Analyzers.CSharpImmutableObjectMethodAnalyzer cannot be created from /__w/1/s/.packages/microsoft.codeanalysis.analyzers/3.3.3/analyzers/dotnet/cs/Microsoft.CodeAnalysis.CSharp.Analyzers.dll : Exception has been thrown by the target of an invocation..
CSC : error CS8032: An instance of analyzer Microsoft.CodeAnalysis.CSharp.Analyzers.CSharpUpgradeMSBuildWorkspaceAnalyzer cannot be created from /__w/1/s/.packages/microsoft.codeanalysis.analyzers/3.3.3/analyzers/dotnet/cs/Microsoft.CodeAnalysis.CSharp.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis.Analyzers, Version=3.3.5.2003, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/__w/1/s/src/libraries/System.Private.CoreLib/gen/System.Private.CoreLib.Generators.csproj]
##[error]CSC(0,0): error CS8032: (NETCORE_ENGINEERING_TELEMETRY=Build) An instance of analyzer Microsoft.CodeAnalysis.CSharp.Analyzers.CSharpUpgradeMSBuildWorkspaceAnalyzer cannot be created from /__w/1/s/.packages/microsoft.codeanalysis.analyzers/3.3.3/analyzers/dotnet/cs/Microsoft.CodeAnalysis.CSharp.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis.Analyzers, Version=3.3.5.2003, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified..
CSC : error CS8032: An instance of analyzer Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpDiagnosticAnalyzerApiUsageAnalyzer cannot be created from /__w/1/s/.packages/microsoft.codeanalysis.analyzers/3.3.3/analyzers/dotnet/cs/Microsoft.CodeAnalysis.CSharp.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis.Analyzers, Version=3.3.5.2003, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/__w/1/s/src/libraries/System.Private.CoreLib/gen/System.Private.CoreLib.Generators.csproj]
##[error]CSC(0,0): error CS8032: (NETCORE_ENGINEERING_TELEMETRY=Build) An instance of analyzer Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpDiagnosticAnalyzerApiUsageAnalyzer cannot be created from /__w/1/s/.packages/microsoft.codeanalysis.analyzers/3.3.3/analyzers/dotnet/cs/Microsoft.CodeAnalysis.CSharp.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis.Analyzers, Version=3.3.5.2003, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified..
CSC : error CS8032: An instance of analyzer Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpDiagnosticAnalyzerFieldsAnalyzer cannot be created from /__w/1/s/.packages/microsoft.codeanalysis.analyzers/3.3.3/analyzers/dotnet/cs/Microsoft.CodeAnalysis.CSharp.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis.Analyzers, Version=3.3.5.2003, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/__w/1/s/src/libraries/System.Private.CoreLib/gen/System.Private.CoreLib.Generators.csproj]
##[error]CSC(0,0): error CS8032: (NETCORE_ENGINEERING_TELEMETRY=Build) An instance of analyzer Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpDiagnosticAnalyzerFieldsAnalyzer cannot be created from /__w/1/s/.packages/microsoft.codeanalysis.analyzers/3.3.3/analyzers/dotnet/cs/Microsoft.CodeAnalysis.CSharp.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis.Analyzers, Version=3.3.5.2003, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified..
CSC : error CS8032: An instance of analyzer Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpRegisterActionAnalyzer cannot be created from /__w/1/s/.packages/microsoft.codeanalysis.analyzers/3.3.3/analyzers/dotnet/cs/Microsoft.CodeAnalysis.CSharp.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis.Analyzers, Version=3.3.5.2003, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/__w/1/s/src/libraries/System.Private.CoreLib/gen/System.Private.CoreLib.Generators.csproj]
##[error]CSC(0,0): error CS8032: (NETCORE_ENGINEERING_TELEMETRY=Build) An instance of analyzer Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpRegisterActionAnalyzer cannot be created from /__w/1/s/.packages/microsoft.codeanalysis.analyzers/3.3.3/analyzers/dotnet/cs/Microsoft.CodeAnalysis.CSharp.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis.Analyzers, Version=3.3.5.2003, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified..
CSC : error CS8032: An instance of analyzer Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpReportDiagnosticAnalyzer cannot be created from /__w/1/s/.packages/microsoft.codeanalysis.analyzers/3.3.3/analyzers/dotnet/cs/Microsoft.CodeAnalysis.CSharp.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis.Analyzers, Version=3.3.5.2003, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/__w/1/s/src/libraries/System.Private.CoreLib/gen/System.Private.CoreLib.Generators.csproj]
##[error]CSC(0,0): error CS8032: (NETCORE_ENGINEERING_TELEMETRY=Build) An instance of analyzer Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpReportDiagnosticAnalyzer cannot be created from /__w/1/s/.packages/microsoft.codeanalysis.analyzers/3.3.3/analyzers/dotnet/cs/Microsoft.CodeAnalysis.CSharp.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis.Analyzers, Version=3.3.5.2003, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified..
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=244978
Build error leg or test failing: Build / CoreCLR  Product Build linux_musl arm64 release / Build managed product components and packages
Pull request: https://github.com/dotnet/runtime/pull/85036

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "BuildRetry": false,
  "ErrorPattern": "An instance of analyzer Microsoft\\.CodeAnalysis\\.CSharp\\..* cannot be created from",
  "ExcludeConsoleLog": false
}
```

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[381868](https://dev.azure.com/dnceng-public/public/_build/results?buildId=381868)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/381868/logs/1009)|dotnet/runtime#90912|
|[381040](https://dev.azure.com/dnceng-public/public/_build/results?buildId=381040)|dotnet/runtime|Build managed test components|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/381040/logs/846)|dotnet/runtime#90814|
|[380937](https://dev.azure.com/dnceng-public/public/_build/results?buildId=380937)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/380937/logs/1019)||
|[379994](https://dev.azure.com/dnceng-public/public/_build/results?buildId=379994)|dotnet/runtime|Build managed test components|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/379994/logs/96)||
|[377230](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377230)|dotnet/runtime|Build managed test components|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/377230/logs/77)||
|[375016](https://dev.azure.com/dnceng-public/public/_build/results?buildId=375016)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/375016/logs/313)||
|[374758](https://dev.azure.com/dnceng-public/public/_build/results?buildId=374758)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/374758/logs/1092)|dotnet/runtime#90620|
|[374599](https://dev.azure.com/dnceng-public/public/_build/results?buildId=374599)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/374599/logs/889)||
|[372068](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372068)|dotnet/runtime|Build managed test components|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/372068/logs/996)||
|[370598](https://dev.azure.com/dnceng-public/public/_build/results?buildId=370598)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/370598/logs/539)|dotnet/runtime#90360|
|[369321](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369321)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/369321/logs/967)|dotnet/runtime#90273|
|[369189](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369189)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/369189/logs/418)|dotnet/runtime#90290|
|[367837](https://dev.azure.com/dnceng-public/public/_build/results?buildId=367837)|dotnet/runtime|Build managed test components|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/367837/logs/99)||
|[367215](https://dev.azure.com/dnceng-public/public/_build/results?buildId=367215)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/367215/logs/340)|dotnet/runtime#90132|
|[367201](https://dev.azure.com/dnceng-public/public/_build/results?buildId=367201)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/367201/logs/1001)|dotnet/runtime#88926|
|[366557](https://dev.azure.com/dnceng-public/public/_build/results?buildId=366557)|dotnet/runtime|Build managed test components|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/366557/logs/765)|dotnet/runtime#90146|
|[366123](https://dev.azure.com/dnceng-public/public/_build/results?buildId=366123)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/366123/logs/648)|dotnet/runtime#90116|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|17|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=322870
**Error message validated:** `An instance of analyzer Microsoft\.CodeAnalysis\.CSharp\..* cannot be created from`
**Result validation: :x:** Known issue did not match with the provided build.
**Validation performed at:** 6/28/2023 9:15:11 PM UTC

**Comment by MichalStrehovsky** [comment]
I think this is the same issue that @lewing and I saw in https://github.com/dotnet/runtime/pull/84422#issuecomment-1502632712 last week. I just reran the build and it was gone. I can't tell for sure if that's the PR where this problem was introduced. But looks like this is real because I ran into it again, in a different part of the build.

**Comment by jaredpar** [comment]
This behavior goes back to at least 4/8. 

https://runfo.azurewebsites.net/view/build/?number=232555

**Comment by radical** [comment]
This was hit with runtime tests [build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=277389&view=results) for wasm - [log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/277314/logs/1360).

**Comment by carlossanlop** [comment]
As indicated in https://github.com/dotnet/runtime/issues/84995, this is happening in the `release/8.0` branch, so I set the milestone to 8.0.0.

**Comment by jaredpar** [comment]
@carlossanlop can you link to a recent failure

**Comment by agocke** [comment]
Looks like we've fixed this one
