### ISSUE TITLE
[NativeAOT] System.NotSupportedException: DelegateMarshalling_MissingInteropData in Marshal.StructureToPtr 

### ISSUE THREAD

**Issue by AhmedZero** [dotnet/runtime#85086]
### Description

there is a problem with `Marshal.StructureToPtr` if I define a managed delegate to `struct`, despite adding the assembly to the `RD.xml` file in NativeAOT.

### Reproduction Steps

MpvOpenglInitParams.cs
```C#
namespace AZVideoDRM.FFI.LibMpv;
public delegate nint MpvGetProcAddressCallback(nint ctx, string name);
[StructLayout(LayoutKind.Sequential)]
public struct MpvOpenglInitParams
{
    /**
         * This retrieves OpenGL function pointers, and will use them in subsequent
         * operation.
         * Usually, you can simply call the GL context APIs from this callback (e.g.
         * glXGetProcAddressARB or wglGetProcAddress), but some APIs do not always
         * return pointers for all standard functions (even if present); in this
         * case you have to compensate by looking up these functions yourself when
         * libmpv wants to resolve them through this callback.
         * libmpv will not normally attempt to resolve GL functions on its own, nor
         * does it link to GL libraries directly.
         */
    public MpvGetProcAddressCallback MpvGetProcAddress;

    /**
         * Value passed as ctx parameter to get_proc_address().
         */
    public nint GetProcAddressCtx;
}
```
Program.cs
```
            MpvOpenglInitParams openglPara = new();        
            var data = Marshal.AllocHGlobal(Marshal.SizeOf<MpvOpenglInitParams>());
            Marshal.StructureToPtr(openglPara, data, true);
            Marshal.FreeHGlobal(data);

```

rd.xml
```xml
<Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
	<Application>
		<Assembly Name="AZVideoDRM" Dynamic="Required All" />
	</Application>
</Directives>

```

### Expected behavior

works without any problems

### Actual behavior

```
System.NotSupportedException: DelegateMarshalling_MissingInteropData, AZVideoDRM.MPV.MpvGetProcAddressCallback
   at Internal.Runtime.CompilerHelpers.RuntimeInteropData.GetDelegateMarshallingStub(RuntimeTypeHandle, Boolean) + 0x85
   at System.Runtime.InteropServices.PInvokeMarshal.AllocateThunk(Delegate) + 0x6a
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValueLocked(TKey, ConditionalWeakTable`2.CreateValueCallback) + 0x26
   at System.Runtime.InteropServices.PInvokeMarshal.GetFunctionPointerForDelegate(Delegate) + 0xf0
   at AZVideoDRM!<BaseAddress>+0xbadcd9
   at System.Runtime.InteropServices.Marshal.StructureToPtr(Object, IntPtr, Boolean) + 0xec
   at AZVideoDRM.MPV.RenderContextCreate(Dictionary`2 parameters) + 0x23c
   at AZVideoDRM.Controls.OpenGlControl.OnOpenGlInit(GlInterface gl) + 0x149
```

### Configuration

I test in .NET 7 and .NET 8
Windows 11 X64

**Comment by hez2010** [comment]
See https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/rd-xml-format.md

You need to keep delegate marshalling data manually for your delegate type.

**Comment by MichalStrehovsky** [comment]
You should be seeing following warning from both the Roslyn analyzer and at publish time:

https://github.com/dotnet/runtime/blob/66ba9d5a66dd44762b780ca06dca1902c07b92aa/src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.NativeAot.cs#L139

Please follow the instructions in the warning. RD.XML is unsupported.

**Comment by jkotas** [comment]
There is no warning generated (`Marshal.StructureToPtr` is recognized as intrinsic by the toolchain) and the AOT compiled binary works fine for me.

My repro steps:
1. `dotnet new console`
2. Replace `Program.cs` with
```
using System.Runtime.InteropServices;

MpvOpenglInitParams openglPara = new();        
var data = Marshal.AllocHGlobal(Marshal.SizeOf<MpvOpenglInitParams>());
Marshal.StructureToPtr(openglPara, data, true);
Marshal.FreeHGlobal(data);

Console.WriteLine("Done!");

public delegate nint MpvGetProcAddressCallback(nint ctx, string name);

[StructLayout(LayoutKind.Sequential)]
public struct MpvOpenglInitParams
{
    public MpvGetProcAddressCallback MpvGetProcAddress;
    public nint GetProcAddressCtx;
}
```
3. Run `dotnet publish -c Release -r win-x64`
4. Run the .exe

@AhmedZero Could you please share the exact repro steps?

**Comment by MichalStrehovsky** [comment]
> There is no warning generated (Marshal.StructureToPtr is recognized as intrinsic by the toolchain)

Ah - saw `at System.Runtime.InteropServices.Marshal.StructureToPtr(Object, IntPtr, Boolean) + 0xec` on the stack but didn't realize it might have been inlined from the generic one that the compiler does recognize. Sorry for the confusion.

**Comment by AhmedZero** [comment]
I found something strange, that exception randomly occurred. when I close the program and open it again, maybe occurred or not.

**Comment by AhmedZero** [comment]
I'm sorry, my mistake the problem only in .NET 7, it worked in The latest preview .Net 8.
