### ISSUE TITLE
String.Compare Always ignore case

### ISSUE THREAD

**Issue by Im-Kevin** [dotnet/runtime#85094]
### Description

I have found that the 'ignoreCase' of 'String. Compare' uses' StringComparison. CurrentCulture ', which can lead to cases being ignored in certain situations

### Reproduction Steps

String.Compare("C", "b", true)
return 1
String.Compare("C", "b", false)
return 1 

### Expected behavior

String.Compare("C", "b", false)
The correct one should be -1 
Because the ASCII of C is 67, while the ASCII of b is 98

### Actual behavior

Even if you choose not to ignore case now, you will still use the method of ignoring case

### Configuration

I found this issue on the traditional Chinese system
.net 6
Windows 11 x64

**Comment by huoyaoyuan** [comment]
If you need to compare the ASCII value, please use `string.CompareOrdinal` or `StringComparison.Ordinal`.

The `string.Compare` method correctly passes the ignoreCase option to underlying culture. However, it seems to only affect the case of `==`:

```
> string.Compare("C", "c", false, new System.Globalization.CultureInfo("en-US"))
1
> string.Compare("C", "C", false, new System.Globalization.CultureInfo("en-US"))
0
```

**Comment by tarekgh** [comment]
@huoyaoyuan is mostly correct. When comparing string linguistically, the underlying collation engine (like ICU in our case), generate a sorting key which always have `b < c` regardless of the casing of the letters. If you are interested, you can play with that in the tool https://icu4c-demos.unicode.org/icu-bin/collation.html.

If you want to get your desired result, you need to `StringComparison.Ordinal` or `StringComparison.OrdinalIgnoreCase`.

**Comment by Im-Kevin** [comment]
This parameter design is a bit bad, ignoreCase = false will be somewhat different from what the field actually does

**Comment by Im-Kevin** [comment]
An ordinary person understands that ignoreCase = false should be equal to not ignoring case, but various complicated factors have to be considered here
