### ISSUE TITLE
.NET Core application running in docker gets OOMKilled if swapping is disabled

### ISSUE THREAD

**Issue by devKlausS** [dotnet/runtime#851]
We are running .NET Core applications inside docker containers on a kubernetes cluster. Docker containers get OOMKilled because GC is not executed.

To test this we created a test program which allocates arrays in a loop. These arrays should get deleted by the GC. The program is executed in a docker container with 100Mb memory limit. Kubernetes is not involved in the tests.

When running the test with **swap enabled** everything works as expected and the GC gets triggered when the total memory reaches 100Mb. The test never gets killed.

When running the test with **swap disabled** the test gets OOMKilled when the total memory reaches 100Mb. We have tested this behaviour with ServerGC=true|false and with .NET Core 2.0 and 2.1

Enabling swap is not an option cause it's neither recommended nor supported by Kubernetes.

# Code
you can find out test program here: https://github.com/devKlausS/dotnet_mem_allocator
      
    var rand = new Random();
    List<byte[]> m_arrays = new List<byte[]>();
    
    int iLoop = 0;
    while (true)
    {
        var array = new byte[iAllocBytes];
        var value = (byte)rand.Next();
        Parallel.ForEach(array, (item) =>
        {
            item = value;
        });
        rand.NextBytes(array);
    
        if(!bFree)
            m_arrays.Add(array);
    
        if(iCollect > 0 && iLoop % iCollect == 0)
        {
            Console.WriteLine("run GC");
            GC.Collect();
        }
    
        Console.Write("AllocatedBytesForCurrentThread: " + GC.GetAllocatedBytesForCurrentThread() / 1000000 + "Mb " +
            "TotalMemory: " + GC.GetTotalMemory(bForceFullCollection) / 1000000 + "Mb ");
    
        for(int i = 0; i < GC.MaxGeneration; i++)
        {
            Console.Write("CollectionCount("+i+"): " + GC.CollectionCount(i) + " ");
        }
    
        Console.WriteLine("");
    
        Thread.Sleep(iSleepMs);
        iLoop++;
    }
# Docker images 

### ServerGC=false alloc/free .NET CORE 2.0
    docker run -ti -m 100M schaefferlinkbit/dotnet_mem_allocator:1.0.3895_20_client_GC /alloc_mb=20 /free=false
### ServerGC=true alloc/free .NET CORE 2.0
    docker run -ti -m 100M schaefferlinkbit/dotnet_mem_allocator:1.0.3895_20_server_GC /alloc_mb=20
### ServerGC=false alloc/free .NET CORE 2.1
    docker run -ti -m 100M schaefferlinkbit/dotnet_mem_allocator:1.0.3895_21_client_GC /alloc_mb=20 /free=false
### ServerGC=true alloc/free .NET CORE 2.1
    docker run -ti -m 100M schaefferlinkbit/dotnet_mem_allocator:1.0.3895_21_server_GC /alloc_mb=20

# cgroup limits
After reading multiple issues according to .NET Core GC and docker limits we started to dig into the cgroup limits. We compiled https://github.com/dotnet/coreclr/blob/master/src/gc/unix/cgroup.cpp and executed the program inside the docker container. As shown in the following screenshot the the path of the memory.limit_in_bytes file is pointing to the directory of the host machine and the file open operation fails.
![screenshot from 2018-05-18 11-27-29](https://user-images.githubusercontent.com/13675575/40230729-f77807ba-5a98-11e8-9740-7da4217a4777.png)
The next screenshot shows the volume mounts of the container. The host machine path is mounted to /sys/fs/memory inside the container. When reading memory.limit_in_bytes we see ~300MB (we pass -m 300M to the docker container)
![screenshot from 2018-05-18 11-27-40](https://user-images.githubusercontent.com/13675575/40230855-64052d4a-5a99-11e8-854f-c5751ab2f56b.png)

It seems like CLR is not able to read the physical memory limits from cgroup and therefore the GC is not triggered correctly. As a result the process is killed because of OOM. We guess that CLR is triggering GC when it has to do swapping and this is the reason why our process is not killed when swapping is enabled.

**Comment by richlander** [comment]
Same question as https://github.com/dotnet/runtime/issues/852#issuecomment-565743896 ... is this issue still a problem with 3.x.

Info on 3.x for containers: https://devblogs.microsoft.com/dotnet/using-net-and-docker-together-dockercon-2019-update/

**Comment by effyteva** [comment]
We face the same issue. Switching from .NET core 2.2 to 3.1 made it even worse for our application.
Are there any recommendations for temporary solutions?
Waiting for .NET core 5.0 (November 2020) isn't a great solution...

**Comment by Gladskih** [comment]
[Related ](https://github.com/dotnet/runtime/issues/9261#issuecomment-585819030)

**Comment by vladshestel** [comment]
The issue is still relevant for netcore `3.1.0-bionic` image. May be my scenario will be useful for someone or it brings any new information to the runtime team.

We facing the problem while migrating an asp.net application with high memory pressure between two sets of servers. We use docker swarm mode to orchestrate services and cgroups for a memory limits. Exact same image was used to start a container on both servers sets and it fails with out-of-memory on a new ones.

The servers were configured with ansible scripts, so they use the exact same configs, docker engine version and both has disabled swapping. Only differences between the old servers and the new servers were an OS version and different environment type.
We have VMware virtual machines with `Ubuntu 16.04.5` on old nodes and bare metal machines with `Ubuntu 18.04.4` on a new nodes.

So, attempt to run a container with memory limit leads to `out-of-memory` error message.

Attempt to run a container without memory limit leads to a "half-dead-working" application with really high memory consumption (4x above normal), without ability to process requests (with connection refused).

One of my hypothesis was about different ubuntu versions. To validate it I deployed stage copy of production node (with Ubuntu 18.04.4 on a virtualized machine) and made the application with production setup run. The run was successful. 

So maybe problem with GC is somehow relevant to a system run mode?

**Temp solution, that make it work:** explicit use of `Workstation GC` mode solve the issue.
```xml
<PropertyGroup>
    <ServerGarbageCollection>false</ServerGarbageCollection>
</PropertyGroup>
```

**Comment by vladshestel** [comment]
Whoa, hope this could be helpful for some researchers.

After further investigations I've noticed that there is big difference between my servers in amount of available logical CPUs count (80 vs 16). After some googling I came across this topic [dotnet/runtime#622](https://github.com/dotnet/runtime/issues/622) that leads me to an experiments with CPU/GC/Threads settings.

I was using [`--cpus` constraint](https://docs.docker.com/compose/compose-file/#resources) in stack file; explicitly set [`System.GC.Concurrent=true`](https://docs.microsoft.com/en-us/dotnet/core/run-time-config/garbage-collector#systemgcconcurrentcomplus_gcconcurrent), [`System.GC.HeapCount=8`](https://docs.microsoft.com/en-us/dotnet/core/run-time-config/garbage-collector#systemgcheapcountcomplus_gcheapcount), [`System.GC.NoAffinitize=true`](https://docs.microsoft.com/en-us/dotnet/core/run-time-config/garbage-collector#systemgcnoaffinitizecomplus_gcnoaffinitize), [`System.Threading.ThreadPool.MaxThreads=16`](https://docs.microsoft.com/en-us/dotnet/core/run-time-config/threading#maximum-threads) in `runtimeconfig.template.json` file; update image to a [`3.1.301-bionic` sdk](https://hub.docker.com/_/microsoft-dotnet-core-sdk) and [`3.1.5-bionic` asp.net runtime](https://hub.docker.com/_/microsoft-dotnet-core-aspnet/) — I made all this things in a various combinations and all of this had no effect. Application just hangs until gets OOMKilled.

The only thing that make it work with Server GC is `--cpuset-cpus` constraint. Of course, explicit setting of available processors is not an option for a docker swarm mode. But I was experimenting with available cpus to find any regularity. And here I got a few interesting facts.

What is interesting, previously I have mirgated 3 other backend services to a new servers cluster and they all go well with a default settings. Their memory limit is set to `600 Mb` but in fact they need about `400 Mb` to run. Things go wrong only with memory-consuming applications (I have two of those), it requires `3 Gb` to build in-memory structures and runs with a `6 Gb` constraint.

It keeps working in any range between `[1, 35]` available cpus and gets hanging when cpus count is `36`. `¯\_(ツ)_/¯`

Of course, it's relevant only for my particular workload, but may be someone could see any relations.

**Comment by pnagori02** [comment]
Hi, is there a plan to fix this sooner ? We are also hitting this problem

**Comment by janvorli** [comment]
I have finally tested this with .NET 6 preview 6. We have made some changes to how we detect memory load on Linux recently, so I wanted to give this a try. It seems that both the client and server cases now behave correctly:
```
server GC: false
allocated bytes: 20000000
sleep ms: 1000
free: True
force full collection: False
run GC every: 0
AllocatedBytesForCurrentThread: 20Mb TotalMemory: 20Mb CollectionCount(0): 0 CollectionCount(1): 0
AllocatedBytesForCurrentThread: 40Mb TotalMemory: 40Mb CollectionCount(0): 1 CollectionCount(1): 1
AllocatedBytesForCurrentThread: 60Mb TotalMemory: 60Mb CollectionCount(0): 1 CollectionCount(1): 1
AllocatedBytesForCurrentThread: 80Mb TotalMemory: 40Mb CollectionCount(0): 2 CollectionCount(1): 2
AllocatedBytesForCurrentThread: 100Mb TotalMemory: 60Mb CollectionCount(0): 2 CollectionCount(1): 2
AllocatedBytesForCurrentThread: 120Mb TotalMemory: 40Mb CollectionCount(0): 3 CollectionCount(1): 3
AllocatedBytesForCurrentThread: 140Mb TotalMemory: 40Mb CollectionCount(0): 4 CollectionCount(1): 4
AllocatedBytesForCurrentThread: 160Mb TotalMemory: 60Mb CollectionCount(0): 4 CollectionCount(1): 4
AllocatedBytesForCurrentThread: 180Mb TotalMemory: 40Mb CollectionCount(0): 5 CollectionCount(1): 5
AllocatedBytesForCurrentThread: 200Mb TotalMemory: 60Mb CollectionCount(0): 5 CollectionCount(1): 5
AllocatedBytesForCurrentThread: 220Mb TotalMemory: 40Mb CollectionCount(0): 6 CollectionCount(1): 6
AllocatedBytesForCurrentThread: 240Mb TotalMemory: 40Mb CollectionCount(0): 7 CollectionCount(1): 7
AllocatedBytesForCurrentThread: 260Mb TotalMemory: 60Mb CollectionCount(0): 7 CollectionCount(1): 7
AllocatedBytesForCurrentThread: 280Mb TotalMemory: 40Mb CollectionCount(0): 8 CollectionCount(1): 8
AllocatedBytesForCurrentThread: 300Mb TotalMemory: 60Mb CollectionCount(0): 8 CollectionCount(1): 8
AllocatedBytesForCurrentThread: 320Mb TotalMemory: 40Mb CollectionCount(0): 9 CollectionCount(1): 9
AllocatedBytesForCurrentThread: 340Mb TotalMemory: 40Mb CollectionCount(0): 10 CollectionCount(1): 10
AllocatedBytesForCurrentThread: 360Mb TotalMemory: 60Mb CollectionCount(0): 10 CollectionCount(1): 10
AllocatedBytesForCurrentThread: 380Mb TotalMemory: 40Mb CollectionCount(0): 11 CollectionCount(1): 11
AllocatedBytesForCurrentThread: 400Mb TotalMemory: 60Mb CollectionCount(0): 11 CollectionCount(1): 11
AllocatedBytesForCurrentThread: 420Mb TotalMemory: 40Mb CollectionCount(0): 12 CollectionCount(1): 12
AllocatedBytesForCurrentThread: 440Mb TotalMemory: 40Mb CollectionCount(0): 13 CollectionCount(1): 13
AllocatedBytesForCurrentThread: 460Mb TotalMemory: 60Mb CollectionCount(0): 13 CollectionCount(1): 13
```
The total memory keeps oscillating between 40 and 60 Mb even if I let it run for a long time.

Server GC version behaves the same way:
```
server GC: true
allocated bytes: 20000000
sleep ms: 1000
free: True
force full collection: False
run GC every: 0
AllocatedBytesForCurrentThread: 20Mb TotalMemory: 20Mb CollectionCount(0): 0 CollectionCount(1): 0
AllocatedBytesForCurrentThread: 40Mb TotalMemory: 40Mb CollectionCount(0): 0 CollectionCount(1): 0
AllocatedBytesForCurrentThread: 60Mb TotalMemory: 60Mb CollectionCount(0): 0 CollectionCount(1): 0
AllocatedBytesForCurrentThread: 80Mb TotalMemory: 40Mb CollectionCount(0): 1 CollectionCount(1): 1
AllocatedBytesForCurrentThread: 100Mb TotalMemory: 60Mb CollectionCount(0): 1 CollectionCount(1): 1
AllocatedBytesForCurrentThread: 120Mb TotalMemory: 40Mb CollectionCount(0): 2 CollectionCount(1): 2
AllocatedBytesForCurrentThread: 140Mb TotalMemory: 60Mb CollectionCount(0): 2 CollectionCount(1): 2
AllocatedBytesForCurrentThread: 160Mb TotalMemory: 40Mb CollectionCount(0): 3 CollectionCount(1): 3
AllocatedBytesForCurrentThread: 180Mb TotalMemory: 60Mb CollectionCount(0): 3 CollectionCount(1): 3
AllocatedBytesForCurrentThread: 200Mb TotalMemory: 40Mb CollectionCount(0): 4 CollectionCount(1): 4
AllocatedBytesForCurrentThread: 220Mb TotalMemory: 60Mb CollectionCount(0): 4 CollectionCount(1): 4
AllocatedBytesForCurrentThread: 240Mb TotalMemory: 40Mb CollectionCount(0): 5 CollectionCount(1): 5
AllocatedBytesForCurrentThread: 260Mb TotalMemory: 60Mb CollectionCount(0): 5 CollectionCount(1): 5
AllocatedBytesForCurrentThread: 280Mb TotalMemory: 40Mb CollectionCount(0): 6 CollectionCount(1): 6
AllocatedBytesForCurrentThread: 300Mb TotalMemory: 60Mb CollectionCount(0): 6 CollectionCount(1): 6
AllocatedBytesForCurrentThread: 320Mb TotalMemory: 40Mb CollectionCount(0): 7 CollectionCount(1): 7
AllocatedBytesForCurrentThread: 340Mb TotalMemory: 60Mb CollectionCount(0): 7 CollectionCount(1): 7
AllocatedBytesForCurrentThread: 360Mb TotalMemory: 40Mb CollectionCount(0): 8 CollectionCount(1): 8
AllocatedBytesForCurrentThread: 380Mb TotalMemory: 60Mb CollectionCount(0): 8 CollectionCount(1): 8
AllocatedBytesForCurrentThread: 400Mb TotalMemory: 40Mb CollectionCount(0): 9 CollectionCount(1): 9
AllocatedBytesForCurrentThread: 420Mb TotalMemory: 60Mb CollectionCount(0): 9 CollectionCount(1): 9
AllocatedBytesForCurrentThread: 440Mb TotalMemory: 40Mb CollectionCount(0): 10 CollectionCount(1): 10
AllocatedBytesForCurrentThread: 460Mb TotalMemory: 60Mb CollectionCount(0): 10 CollectionCount(1): 10
```

**Comment by janvorli** [comment]
@devKlausS these were tested with swap disabled. Do the result look good to you so that we can close this issue?
