### ISSUE TITLE
Missing overrides in LoggingHttpMessageHandler and LoggingScopeHttpMessageHandler

### ISSUE THREAD

**Issue by mphelt** [dotnet/runtime#85104]
### Background and motivation

Both [LoggingHttpMessageHandler](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Http/src/Logging/LoggingHttpMessageHandler.cs) and [LoggingScopeHttpMessageHandler](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Http/src/Logging/LoggingScopeHttpMessageHandler.cs) have implementations of:
`protected async override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request!!, CancellationToken cancellationToken)`
but they are missing implementations of:
`protected internal override HttpResponseMessage Send(HttpRequestMessage request, CancellationToken cancellationToken)`
It would be great to see these implementations introduced, as otherwise custom implementation of:
- `IHttpMessageHandlerBuilderFilter`,
- `HttpHeadersLogValue`,
- `LoggingHttpMessageHandler`
- `LoggingScopeHttpMessageHandler`

is needed.
I know that synchronous usage is not expected most of the times, but we've spent quite some time figuring out why we can't turn on those logs in our legacy app migrated to .NET 6 when we tried to figure out how it works.
### Risks

_No_ response

**Comment by MihaZupan** [comment]
Providing implementations for sync paths makes sense. In this case, it doesn't only affect performance, but also the functionality of such handlers.
@mphelt would you be interested in contributing the change?

**Comment by mphelt** [comment]
Sure, please find https://github.com/dotnet/runtime/pull/85143.
I didn't create copy of all tests that use SendAsync, but only the basic ones to check if it works - I hope that's enough.
