### ISSUE TITLE
Porting NativeAOT exception handling implementation to CoreCLR

### ISSUE THREAD

**Issue by janvorli** [dotnet/runtime#85119]
This issue tracks porting of the NativeAOT exception handling implementation to CoreCLR. The primary goal is to significantly improve exception handling performance. The work is based on the recent experiment described in #77568.

The work will be initially done supporting win-x64. Platform specific changes will be made after this scenario fully works.

* [x] Implement native runtime helpers for stack walking, exception clause enumeration and funclet invocation
* [x] Make necessary modifications to the managed `exceptionhandling.cs` reflecting differences in the stack walker and runtime helper invocations
* [x] Modify exception throwing JIT helpers to invoke the managed exception handling code
* [x] Ensure that basic single software / hardware exception throwing / catching including finally and exception filters work. 
* [x] Enable building stack traces in the exceptions
* [x] Enable collided exception support (rethrow / throwing a new exception from catch / finally)
* [x] Enable proper tracking of exception stack unwinding during GC stack walks so that unwound frames are correctly skipped and no stale references are reported.
* [x] Enable support for exceptions crossing boundary between managed code and runtime native code, for example in reflection invoke code etc.
* [x] Enable support for exception propagation over pinvokes / reverse pinvokes if feasible.
* [x] Enable ETW events generation for the exception handling stuff similar to what CoreCLR emits.
* [x] Enable Watson support for Windows
* [x] Ensure that the debugging tools work properly with the new exception handling mechanism
* [x] Fill in gaps in architecture / target support, verify that the new exception handling works correctly on Unix and non-x64 architectures too_
* [x] Measure final performance using the methodology from the exception handling experiment

**Comment by mangod9** [comment]
Closing since new EH has been enabled since preview3.
