### ISSUE TITLE
NullReferenceException in async code between System.Security.Cryptography HashProviderCng.AppendHashData and  BCrypt.BCryptHashData(...)

### ISSUE THREAD

**Issue by MAOliver** [dotnet/runtime#85115]
### Description

I'm getting an exception when using MD5 compute hash in some .net 7.0.202 code. 

Exception:
```
    System.NullReferenceException : Object reference not set to an instance of an object.

  Stack Trace: 
    BCrypt.BCryptHashData(SafeBCryptHashHandle hHash, ReadOnlySpan`1 pbInput, Int32 cbInput, Int32 dwFlags)
    HashProviderCng.AppendHashData(ReadOnlySpan`1 source)
    HashProvider.AppendHashData(Byte[] data, Int32 offset, Int32 count)
    HashAlgorithm.ComputeHash(Byte[] buffer)
    UnitTest1.Hash(String input) line 86
    UnitTest1.TestMethod2(SomeTestObject sto) line 75
    UnitTest1.HigherLevelTestMethod(SomeTestObject sto) line 52
    <<Test1>b__8>d.MoveNext() line 35
    --- End of stack trace from previous location ---
    UnitTest1.Test1() line 35
    --- End of stack trace from previous location ---
```

### Reproduction Steps

    public class UnitTest1
    {
        private Random _random;
        private HashAlgorithm hashAlgorithm;

        public UnitTest1()
        {
            _random = new Random();
          //  Barrel.ApplicationId = "Test.MonkeyCache.HashNull";
            hashAlgorithm = MD5.Create();
        }

        [Fact]
        public async Task Test1()
        {
            var id = 1;
            var faker = new Faker<SomeTestObject>()
                .StrictMode(true)
                .RuleFor(o => o.id, f => id++)
                .RuleFor(o => o.name, (f, u) => f.Name.FirstName())
                .RuleFor(o => o.description, (f,u)=>f.Commerce.ProductName())
                .RuleFor(o => o.guid, f => Guid.NewGuid());
            var objs = faker.GenerateBetween(30, 100).ToArray();
            var results = await Task.WhenAll(objs.Select(async x => await HigherLevelTestMethod(x)));

            Assert.True(results.Any());
        }

        public async Task<SomeTestObject> HigherLevelTestMethod(SomeTestObject sto)
        {
            int id = 1;
            var faker = new Faker<SomeTestObject>()
            .StrictMode(true)
                .RuleFor(o => o.id, f => id++)
                .RuleFor(o => o.name, (f, u) => f.Name.FirstName())
                .RuleFor(o => o.description, (f, u) => f.Commerce.ProductName())
                .RuleFor(o => o.guid, f => Guid.NewGuid());
            var objs = faker.GenerateBetween(50, 100).ToArray();
            var otherKey = await TestMethod2(sto);
            var keyResult = await TestMethod(sto);
            var otherResults = await Task.WhenAll(objs.Select(obj => TestMethod2(obj)));
            var otherResults2 = await Task.WhenAll(objs.Select(obj => TestMethod(obj)));

            await Task.Delay(_random.Next(25));

            return otherResults[_random.Next(0, otherResults.Length-1)];
        }

        public async Task<SomeTestObject> TestMethod(SomeTestObject sto)
        {
            var key = $"{sto.name}-{sto.description}-{sto.guid}";

            Hash(key);
            await Task.Delay(5);

            return sto;
        }

        public async Task<SomeTestObject> TestMethod2(SomeTestObject sto)
        {
            var key = $"{sto.name}-{sto.description}";

            Hash(key);
            await Task.Delay(5);

            return sto;
        }

        string Hash(string input)
        {
            var data = hashAlgorithm.ComputeHash(Encoding.Default.GetBytes(input));
            return BitConverter.ToString(data);
        }
    }

    public class SomeTestObject
    {
        public int id;
        public string name;
        public string description;
        public Guid guid;
    }

### Expected behavior

Hash should calculate accurate regardless of use of async tasks or not.

### Actual behavior

Exception is thrown -- looks like a race condition?

### Regression?

Unknown

### Known Workarounds

Unwinding the Task.WhenAll and reducing the level of asynchronous task execution reduces the likelihood that this occurs (but slows down the production code I'm using).

### Configuration

dotnet 7.0.202

Processor	Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz   2.40 GHz
Installed RAM	32.0 GB (31.6 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	Touch support with 10 touch points

Edition	Windows 10 Enterprise
Version	21H2
Installed on	‎10/‎15/‎2021
OS build	19044.2728
Experience	Windows Feature Experience Pack 120.2212.4190.0

Read that the Cng crypto providers are specific to windows, so this may be platform specific.

**Comment by vcsjones** [comment]
Hash algorithm instances are not thread safe. You are using an instance of `MD5` from multiple threads.

> dotnet 7.0.202

You should use the static `MD5.HashData` method. The static method is safe to call from multiple threads.

Something like this:

```C#
string Hash(string input)
{
    var data = MD5.HashData(Encoding.Default.GetBytes(input));
    return BitConverter.ToString(data);
}
```

**Comment by MAOliver** [comment]
I was using another library that was using an instance of the hashalgorithm and I was having this issue. I isolated it to just this code. I'll reopen the issue over there.

Thanks again.
