### ISSUE TITLE
[Android][Net6/7] TimeZoneInfo StandardName/DaylightName does not displays abbreviations anymore

### ISSUE THREAD

**Issue by takla21** [dotnet/runtime#85126]
### Description

Since `net6.0-android`, `StandardName` & `DaylightName` does not return abbreviations. Instead it returns the full name.

### Reproduction Steps

I've made a small uno project containing both a Xamarin version & net6/7 version that checks all `TimeZoneInfo` and display `TimeZoneInfo.Local` info to the page.

- Download this sample [TimeZoneSample.zip](https://github.com/dotnet/runtime/files/11290930/TimeZoneSample.zip)
- Open it on visual studio 2022
- Go to the NET folder
- Deploy on android (you can also change net version in the csproj)
- Look for logs in the console

Alternatively, you could simply add those logs on any net6/7 or xamarin app

```cs
var timeZones = TimeZoneInfo.GetSystemTimeZones();
foreach (var tz in timeZones)
{ 
    Console.WriteLine($"timezone {tz}= StandardName: {tz.StandardName}, DaylightName: {tz.DaylightName}");
}
```

### Expected behavior

Console logs: [logs_expected.txt](https://github.com/dotnet/runtime/files/11290957/logs_expected.txt)

Here's the result on my android xamarin sample app provided above
![Screenshot_20230420-182805](https://user-images.githubusercontent.com/17461593/233500662-63c7893a-2735-4c34-8a82-c1c268c30337.jpg)

### Actual behavior

With the loggin in the expected section, I have this on my android net6/7 project [logs_actual.txt](https://github.com/dotnet/runtime/files/11290964/logs_actual.txt)

Here's the result on my net6/7 android sample provided above
![Screenshot_20230420-182813](https://user-images.githubusercontent.com/17461593/233500536-948e8474-5ad9-4218-ad80-99c67a436c8e.jpg)

### Regression?

I'm not 100% sure the specific .NET version, but on xamarin it's not an issue. 

### Known Workarounds

N/A

### Configuration

- `net6.0-android`, `net7.0-android`
- Tested on Android 11

### Other information

On `net6.0-ios`, it's still displaying abbreviations for `StandardName` & `DaylightName`.

**Comment by takla21** [comment]
Any news on it @steveisok @mdh1418 ?

**Comment by steveisok** [comment]
> Any news on it @steveisok @mdh1418 ?

Nothing yet, but it is on @mdh1418's list to investigate.

**Comment by mdh1418** [comment]
Hi @takla21, I believe the change in behavior is expected. The .NET 6 effort included a unification that affected the base class libraries, so now the Android implementation follows .NET libraries implementation in lieu of the [mono/mono BCL implementation](https://github.com/mono/mono/blob/2020-02/mcs/class/corlib/System/TimeZoneInfo.cs) that is seen in Classic Xamarin.Android. I believe you might be able to see the abbreviations for the `StandardName` and `DaylightName` properties if you use [`GlobalizationMode.Invariant`](https://github.com/dotnet/runtime/blob/main/docs/workflow/trimming/feature-switches.md).

Is there a particular reason you need to have abbreviations for these properties? As the documentation (showing the specific .NET 6 docs) for [`TimeZoneInfo.StandardName`](https://learn.microsoft.com/en-us/dotnet/api/system.timezoneinfo.standardname?view=net-6.0#system-timezoneinfo-standardname) and [`TimeZoneInfo.DaylightName`](https://learn.microsoft.com/en-us/dotnet/api/system.timezoneinfo.daylightname?view=net-6.0) exemplify a full name and do not mention providing abbreviations, I believe any desire to have abbreviations instead in a non `GlobalizationMode.Invariant` environment will be an API proposal instead.

**Comment by takla21** [comment]
Hi @mdh1418, so essentially, we need to display the timezone on our app. In our case, it's easier to fit the abbreviation rather than its full name.

Fortunately, we've worked around it by using another library, https://www.nuget.org/packages/TimeZoneNames, to get the abbreviation. So, if you're saying that it's supposed to behave that way on net6, I guess we can close it. Although, if I recall correctly, on iOS, it still displays the timezone as abbreviated. Does this mean that there should be a bug on iOS instead?

**Comment by mdh1418** [comment]
It might indeed be a bug on iOS as we use our own version of ICU to grab information, so the appropriate data to get the full name for StandardName and DaylightName might have been filtered out. I'll have to investigate that. Thanks for pointing it out!

**Comment by mdh1418** [comment]
Closing this issue as it is Android specific, will create an iOS issue after confirming the bug.
