### ISSUE TITLE
NativeAOT ComWrappers: support IReferenceTrackerHost

### ISSUE THREAD

**Issue by AustinWise** [dotnet/runtime#85137]
Currently NativeAOT's ComWrapper managed object wrapper supports being created with the [`CreateComInterfaceFlags.TrackerSupport`](https://learn.microsoft.com/dotnet/api/system.runtime.interopservices.createcominterfaceflags) flag. This causes the wrapper to implement [`IReferenceTrackerTarget`](https://learn.microsoft.com/windows/win32/api/windows.ui.xaml.hosting.referencetracker/nn-windows-ui-xaml-hosting-referencetracker-ireferencetrackertarget).

What is missing is an implementation of [`IReferenceTrackerHost`](https://learn.microsoft.com/windows/win32/api/windows.ui.xaml.hosting.referencetracker/nn-windows-ui-xaml-hosting-referencetracker-ireferencetrackerhost). Supporting `IReferenceTrackerHost` would enable tighter integreation between the .NET garbage collector and the unmanaged runtime. When implementing this, inspiration can be taken from [CoreCLR's implementation](https://github.com/dotnet/runtime/blob/main/src/coreclr/interop/trackerobjectmanager.cpp).

This tracking issue captures some of the conversation from #85087

**Comment by jkoritzinsky** [comment]
Marking for 8.0 as we have a lot of time to try to get it in and as “help-wanted” in case the community wants to lead the implementation.

**Comment by kant2002** [comment]
I think there should be some explanation what IReferenceTrackerHost do. Right now it’s a bit of black box.
