### ISSUE TITLE
[Proposal] Allow a Brotli compression level between Fastest and Optimal

### ISSUE THREAD

**Issue by SvenViking** [dotnet/runtime#85138]
# Summary

Allow the System.IO.Compression.Brotli compression level to be set to a level or levels in-between the "Fastest" and "Optimal" settings, whether by allowing an explicit compression level to be passed to a BrotliStream or BrotliEncoder via an enum or integer value (outside of .NET, Brotli supports compression levels between 0 and 11), or by adding a new member to the CompressionLevel enum. 

# Motivation

The [.NET Blog article introducing support for Brotli compression](https://devblogs.microsoft.com/dotnet/introducing-support-for-brotli-compression/) explains that:

- At the Fastest setting, Brotli compression ratios and times are not much better than GZip at its Fastest setting.
- At the Optimal setting, Brotli compression ratios are good, but it is exceedingly slow, with compression times *orders of magnitude higher* than GZip at its Optimal setting.
- At medium compression levels such as Level 5, Brotli compression ratios are greatly improved for minimal time penalties, essentially providing the best of both worlds with both higher ratios and faster speeds than GZip's Optimal setting.

However, as far as I have been able to find, there is no way to use the suggested Compression Level 5 or any other level between the Fastest and Optimal settings via .NET's Brotli implementation. This would seem to be far from optimal for many use cases.

**Comment by SvenViking** [comment]
Thanks for moving this to the appropriate area.

**Comment by stephentoub** [comment]
> However, as far as I have been able to find, there is no way to use the suggested Compression Level 5 or any other level between the Fastest and Optimal settings via .NET's Brotli implementation. This would seem to be far from optimal for many use cases.

This was changed in .NET 7.  Optimal is now quality level 4.

See https://devblogs.microsoft.com/dotnet/performance_improvements_in_net_7/#compression for discussion.

> or BrotliEncoder

The encoder's public `public BrotliEncoder(int quality, int window)` ctor lets you choose any level you want.

**Comment by SvenViking** [comment]
Thanks! I was using it in .NET Standard so didn't notice the change, but I also missed the BrotliEncoder option somehow. Definitely makes sense for me for Optimal not to be set to something that isn't a thousandfold slower.
