### ISSUE TITLE
Managed type system casting logic doesn't handle all array variance

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#85146]
Compile following with optimizations on:

```csharp
class Program
{
    static void Main()
    {
        object source = new Enum0[] { Enum0.First, Enum0.Second, Enum0.Third };
        Console.WriteLine(source is IEnumerable<Enum1>);
    }

    enum Enum0 { First, Second, Third }
    enum Enum1 { }
}
```

Expected: prints true
Observed: prints false

This is because the CanCastTo logic within the managed type system doesn't think these are castable. RyuJIT hardcodes this to false in codegen.

**Comment by Fabi** [comment]
Just a thing to clarify: The `is` keyword actually returns true as soon as an implicit conversion is possible? I thought it only returns true on exact type matches :D

**Comment by MichalStrehovsky** [comment]
It returns true if a cast can succeed.

You can do `((IEnumerable<Enum1>)source).GetType()` and you'll get `Enum0[]`. There's no conversion involved, just a type check.

**Comment by Fabi** [comment]
> It returns true if a cast can succeed.
> 
> You can do `((IEnumerable<Enum1>)source).GetType()` and you'll get `Enum0[]`. There's no conversion involved, just a type check.

That's good to know, thank you. I always expected it to only return true on exact type matches
