### ISSUE TITLE
Where is corerun ?

### ISSUE THREAD

**Issue by micli** [dotnet/runtime#8514]
At the .NET Core debugging instruction markdown file 
https://github.com/dotnet/coreclr/blob/master/Documentation/building/debugging-instructions.md
mentioned that:
Start lldb (the version the plugin was built with, currently 3.6): `lldb-3.6 corerun HelloWorld.exe linux`

But I cannot find corerun from official installation package.
If I compiled manually, I can find some corerun locations like this:
`corerun:[micl@centos7dotnet dotnet]$ find -name corerun
./coreclr/src/coreclr/hosts/corerun
./coreclr/bin/Product/Linux.x64.Debug/corerun
./coreclr/bin/obj/Linux.x64.Debug/src/coreclr/hosts/unixcorerun/corerun
./corefx/packages/runtime.linux-x64.microsoft.netcore.testhost/2.1.0-preview1-25409-01/runtimes/linux-x64/native/corerun
./corefx/bin/runtime/netcoreapp-Linux-Debug-x64/corerun
./corefx/bin/testhost/netcoreapp-Linux-Debug-x64/shared/Microsoft.NETCore.App/9.9.9/corerun
./corefx/bin/Unix.AnyCPU.Debug/runtime/netcoreapp/corerun`

If I want to launch process from LLDB, how can I do ？ Thanks!

**Comment by danmosemsft** [comment]
Out of date now I think.
