### ISSUE TITLE
Dotnet publish command creates publish folder locally but not in the Azure pipelines. 

### ISSUE THREAD

**Issue by vinayakmsft** [dotnet/runtime#85147]
I tried a dotnet publish command to generate a publish folder. Following is the configuration of the task in pipeline:

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/CoveragePublisher.Console.csproj'
    arguments: '-c Release -f net7.0 -r win-x64'
    
    
But on using the CopyFiles task it shows "No Soure Folder" found Error. Following is the configuration of CopyFiles task in the pipeline :

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/src/CoveragePublisher.Console/bin/Release/net7.0/win-x64/publish/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
    
 Error message- [error]Error: Not found SourceFolder: D:\a\1\s\src\CoveragePublisher.Console\bin\Debug\net7.0\win-x64\publish\
 
 
 Please help me in resolving this issue. And let me know what is needed to be done so that the CopyFiles task works correctly?

**Comment by vitek-karas** [comment]
In the task definition for CopyFiles you have a path to `Release`, but then the error says `Debug`. Based on the publish command line it needs to look for `Release`. Not sure why, but the `Debug` path is expected to exist when publishing `Release`.

**Comment by elinor-fung** [comment]
@vinayakmsft can you confirm that the error message you posed (with `Debug` in the path) is from the same CopyFiles task you posted (with `Release` in the path)? As Vitek pointed out, that discrepancy is really weird - and if that is happening, I'd recommend opening an issue in https://github.com/microsoft/azure-pipelines-tasks.
