### ISSUE TITLE
Deserialising null to JsonNode in nested structures fails in System.Text.Json

### ISSUE THREAD

**Issue by adj123** [dotnet/runtime#85172]
`JsonSerializer.Deserialize<JsonNode>("null")` returns null
`JsonSerializer.Deserialize<List<JsonNode>>("[null]")` throws
`JsonSerializer.Deserialize<Dictionary<string, JsonNode>>("{ \"Foo\": null }")` throws

Assuming this isn't intentional? Reproducible in .Net 6 & 7.

**Comment by eiriktsarpalis** [comment]
I can reproduce, looks like the `JsonNode` converters do not handle `JsonTokenType.Null` on deserialization, hitting this case:

https://github.com/dotnet/runtime/blob/b1497d3b33b3d44a5a1a6f9ca6c0b29addc6fe06/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Node/JsonNodeConverter.cs#L64-L66

@adj123 would you be interested in contributing a fix?

**Comment by eiriktsarpalis** [comment]
Tagging @steveharter in case the current behavior baked into the converters is intentional.

**Comment by adj123** [comment]
Sure I can do. I'll wait to hear confirmation the behaviour should be changed first.
