### ISSUE TITLE
F1 on our source generator errors goes nowhere because we don't set a HelpUri

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#85181]
I got this
![image](https://user-images.githubusercontent.com/6385855/233733776-f9553850-f54c-4c05-9821-b79bab3efa32.png)

clicked on the SYSLIB1052 code, which is hyperlinked, and got an Oops page:

https://learn.microsoft.com/en-us/visualstudio/ide/not-in-toc/default?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(keywords_removed)%26rd%3Dtrue&view=vs-2022

Not sure if it's just this code.

**Comment by teo-tsirpanis** [comment]
BTW clicking many newer compiler error codes also leads to a generic error page like this.

**Comment by danmoseley** [comment]
@buyaa-n how do we handle ensuring that the SYSLIBxxx codes go someplace?

**Comment by danmoseley** [comment]
should ours all pass [HelpLinkUri](https://github.com/dotnet/roslyn/blob/74f99e6cad8d288ff406f6faefd26faad7144442/src/Compilers/Core/Portable/Diagnostic/DiagnosticDescriptor.cs#L38) or should there be useful default behavior somewhere?

**Comment by buyaa-n** [comment]
> how do we handle ensuring that the SYSLIBxxx codes go someplace?

I don't know how SYSLIBxxx links works, seems it should open https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib1050-1069, tagging @gewarren who created that page

**Comment by gewarren** [comment]
None of the SYSLIB warning links seem to work, even the ones that have a dedicated page (I tried SYSLIB0011 for BinaryFormatter.Serialize). I think this is how the code analysis rules hook up to learn.microsoft.com: https://github.com/dotnet/roslyn-analyzers/blob/2420507acd5863bfe30a7dd97993c9362527045b/src/Utilities/Compiler/DiagnosticDescriptorHelper.cs#L36. @mavasani might be able to suggest a solution for the SYSLIB warnings?

**Comment by mavasani** [comment]
> should ours all pass [HelpLinkUri](https://github.com/dotnet/roslyn/blob/74f99e6cad8d288ff406f6faefd26faad7144442/src/Compilers/Core/Portable/Diagnostic/DiagnosticDescriptor.cs#L38) or should there be useful default behavior somewhere?

You should write a DiagnosticDescription creation helper in your repo that builds up the help link based on the diagnostic ID and adds it to the descriptor. We do so in both Roslyn and Roslyn-analyzers repo.

**Comment by AaronRobinsonMSFT** [comment]
> You should write a DiagnosticDescriptor creation helper in your repo that builds up the help link based on the diagnostic ID and adds it to the descriptor. 

Seems like this is a general analyzer issue for the repo and no specific to interop.

**Comment by danmoseley** [comment]
The DiagnosticDescriptorHelper would need to have a mapping table in order to produce URL's like

https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib1040-1049
https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib1050-1069
https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib1070-1089

a few URL's are missing, #86023

**Comment by gewarren** [comment]
> The DiagnosticDescriptorHelper would need to have a mapping table in order to produce URL's like

We can do the mapping on the docs side through the redirection file, e.g. 

```
{
    "source_path_from_root": "/docs/fundamentals/syslib-diagnostics/syslib1055.md",
    "redirect_url": "/dotnet/fundamentals/syslib-diagnostics/syslib1050-1069"
}
```

**Comment by danmoseley** [comment]
> > The DiagnosticDescriptorHelper would need to have a mapping table in order to produce URL's like
> 
> We can do the mapping on the docs side through the redirection file, e.g.

Ah, I think that would be much better. So the helper should basically just set HelpUri to `https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/<CODE>.md` for each code.

**Comment by danmoseley** [comment]
cc @captainsafia as it appears that the RDG is also missing HelpLinkUri eg

https://github.com/danmoseley/aspnetcore/blob/d6d85eda7ed5b7a9c72ef9f36166f8ec9f850fd2/src/Http/Http.Extensions/gen/DiagnosticDescriptors.cs#L10

I can open an issue if there's not already a task tracking that.

for reference, aspnetcore's list is at https://github.com/dotnet/aspnetcore/blob/main/docs/list-of-diagnostics.md

**Comment by captainsafia** [comment]
> I can open an issue if there's not already a task tracking that.

Yep, let's file an issue for this.

We currently have the HelpLink uri configured the analyzers/codefixers in the targeting pack but not the generator.

**Comment by ericstj** [comment]
The fix for this should add a DiagnosticDescriptorHelper class [like the one shared](https://github.com/dotnet/roslyn-analyzers/blob/2420507acd5863bfe30a7dd97993c9362527045b/src/Utilities/Compiler/DiagnosticDescriptorHelper.cs#L36) by @gewarren (thanks!) with a create method taking relevant constructor parameters, it should create the `helpLink` as 
```c#
string helpLink = $"https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/{id.ToLowerInvariant()}.md";
```
Then create the DiagnosticDescriptor.  Looks like we have a few different sources in the repo -- some may not be syslib. 
https://github.com/search?q=repo%3Adotnet%2Fruntime%20DiagnosticDescriptor%20&type=code

@layomia -- maybe you can try this out while you're working on the ConfigurationBinder generator to find a pattern that works well, then apply it across the other generators?

**Comment by danmoseley** [comment]
Note that despite the title it's not just generators of course, anywhere a DiagnosticDescriptor is created, eg [analyzer diagnostics.](https://github.com/dotnet/runtime/blob/3747edb1812106f0b88a42b724c3e44b69dc79c4/src/libraries/System.Text.RegularExpressions/gen/DiagnosticDescriptors.cs#L58)
