### ISSUE TITLE
[API Proposal]: Add ForeachAsync in Enumerable

### ISSUE THREAD

**Issue by Alerinos** [dotnet/runtime#85199]
### Background and motivation

Many times when creating code it would be nice to have a lambda that would allow foreach to be used in a list.

### API Proposal

```csharp
public static async Task ForEachAsync<T>(this IEnumerable<T> items, Func<T, Task> func)
        {
            if (items == null)
            {
                return;
            }

            foreach (var item in items) await func(item);
        }
```

### API Usage

```csharp
            await articlesDto.ForEachAsync(async x =>
            {
                var user = await User.GetAsync(x.AuthorId);
                x.AuthorName = user.Name;
            });
```

**Comment by stephentoub** [comment]
You can just write an await foreach loop. I don't see us adding this for many of the same reasons a ForEach method hasn't been added. Plus, you can use Parallel.ForEachAsync with a max limit of 1 of you really want that.

**Comment by Alerinos** [comment]
The usual ForEach integration already exists. I think I messed up the repository.
```cs
        public void ForEach(Action<T> action)
        {
            if (action == null)
            {
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.action);
            }

            int version = _version;

            for (int i = 0; i < _size; i++)
            {
                if (version != _version)
                {
                    break;
                }
                action(_items[i]);
            }

            if (version != _version)
                ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion();
        }
```
https://github.com/microsoft/referencesource/blob/51cf7850defa8a17d815b4700b67116e3fa283c2/mscorlib/system/collections/generic/list.cs#L545

**Comment by stephentoub** [comment]
> The usual ForEach integration already exists.

That's on `List<T>`, not an extension on `IEnumerable<T>`.
