### ISSUE TITLE
Improve SOS so that it displays profiler modified IL for functions

### ISSUE THREAD

**Issue by noahfalk** [dotnet/runtime#8520]
When jitting fails we'd like to know whether the JIT was operating on the original IL or profiler modified IL. We should identify one or more commands to change/modify (!DumpMD is probably one) to expose this information. In the runtime this info can be found in Module->m_debuggerSpecificData.m_pTemporaryILBlobTable
BaseDomain->m_rejitMgr->m_table (which is in progress of being refactored to CodeVersionManager)

We should also expose some basic information about whether or not a profiler is attached and what configuration flags it has set up. This info can be found in:
g_profControlBlock

**Comment by iskiselev** [comment]
@mmayr-at, have you published anywhere your WinDbg extension to view profiler-generated IL?

**Comment by davmason** [comment]
This was implemented in https://github.com/dotnet/diagnostics/pull/437, and will work starting with coreclr 3.0
