### ISSUE TITLE
Unable to get exception's filename and line number in mono.

### ISSUE THREAD

**Issue by CeSun** [dotnet/runtime#85223]
I integrated .net7(mono) into UE, and then loaded the plugin.

The dll of my plug-in is not loaded directly through mono's c++ api (because mono has deleted the multi-domain support), I first load a Util.dll (c#), and then load it by calling the static function in Util.dll Other plugin dlls:

Code :
```c#
 public static class AssemblyUtil
    {
        static AssemblyLoadContext? ALC;

        public static void Initialize()
        {
            ALC ??= new AssemblyLoadContext("MonoCSharp", true);
        }

        public static void Deinitialize()
        {
            if (ALC != null)
            {
                ALC.Unload();

                ALC = null;
            }
        }

        public static Assembly? Load(string InPath)
        {

            var pdbFile = InPath.Substring(0, InPath.Length - 4) + ".pdb";
            using var LibraryFileSR = new StreamReader(InPath);
            if (File.Exists(pdbFile))
            {
                Console.WriteLine($@"Find the pdb file ""{pdbFile}"" of the ""{InPath}"" file");
                using var SymbolFileSR = new StreamReader(pdbFile);
                return ALC?.LoadFromStream(LibraryFileSR.BaseStream, SymbolFileSR.BaseStream);

            }
            else
            {
                Console.WriteLine($@"No pdb file found for ""{InPath}"" file");
                return ALC?.LoadFromStream(LibraryFileSR.BaseStream);
            }

        }
    }
```

I'm running into a problem right now where I can't use StackTrace to get the source file path and line number when an exception is thrown in a dll in c#.

```c#
  public static string GetTraceback()
        {
            var Traceback = new StringBuilder();

            var Trace = new StackTrace(true);

            var Frames = Trace.GetFrames();

            foreach (var Frame in Frames)
            {
                Traceback.Append(String.Format("at {0}.{1} in {2}:{3}\r\n",
                    Frame.GetMethod().DeclaringType.FullName,
                    Frame.GetMethod().Name,
                    Frame.GetFileName(),
                    Frame.GetFileLineNumber()));
            }

            return Traceback.ToString();
        }
```

**Comment by lateralusX** [comment]
In order for Mono to be able to map source/line info in stack traces, you will need to enable runtime debug support. If you embed the Mono runtime using the C API, you also need to configure the debugger support needed in order to load, parse and use symbol data at runtime. The same logic is enabled in `driver.c, mono_main` by supplying the `--debug` argument.

The function call enabling debug symbol support in runtime is the following:

`mono_debug_init (MONO_DEBUG_FORMAT_MONO);`

make sure that gets called before calling `mono_jit_init` in the embedding code.

**Comment by CeSun** [comment]
Added mono_debug_init (MONO_DEBUG_FORMAT_MONO).
