### ISSUE TITLE
 PATH=~/cmake/bin:$PATH ./build.sh clr+libs  -c Release  failed

### ISSUE THREAD

**Issue by monstercatss** [dotnet/runtime#85236]
i can build debug but fail build release runtime

**Detail**
[ 85%] Building CXX object src/jit/standalone/CMakeFiles/clrjit.dir/__/alloc.cpp.o
  [ 89%] Built target protononjit
  Scanning dependencies of target mscordaccore_module_index_header
  [ 89%] Generating mscordaccore module index file -> /home/magus/zmx/runtime/artifacts/obj/coreclr/Linux.x64.Release/src/inc/dacmoduleindex.h
  [ 94%] Built target cee_crossgen
  g++-9: error: unrecognized command line option ‘-fprofile-instr-use=/home/magus/.nuget/packages/optimization.linux-x64.pgo.coreclr/99.99.99-master-20200806.6/data/clrjit.profdata’
  make[2]: *** [src/jit/standalone/CMakeFiles/clrjit.dir/build.make:63: src/jit/standalone/CMakeFiles/clrjit.dir/__/alloc.cpp.o] Error 1
  make[1]: *** [CMakeFiles/Makefile2:2435: src/jit/standalone/CMakeFiles/clrjit.dir/all] Error 2
  make[1]: *** Waiting for unfinished jobs....
  [ 94%] Built target mscordaccore_module_index_header
  Scanning dependencies of target mscordbi
  [ 94%] Building CXX object src/dlls/mscordbi/CMakeFiles/mscordbi.dir/mscordbi.cpp.o
  [ 94%] Building ASM object src/dlls/mscordbi/CMakeFiles/mscordbi.dir/__/mscordac/palredefines.S.o
  [ 94%] Building C object src/dlls/mscordbi/CMakeFiles/mscordbi.dir/__/__/__/version.c.o
  Scanning dependencies of target coreclr_static
  [ 94%] Building CXX object src/dlls/mscoree/coreclr/CMakeFiles/coreclr_static.dir/__/mscoree.cpp.o
  [ 94%] Building CXX object src/dlls/mscoree/coreclr/CMakeFiles/coreclr_static.dir/__/unixinterface.cpp.o
  [ 94%] Linking CXX shared library libmscordbi.so
  [ 94%] Linking CXX static library libcoreclr_static.a
  Stripping symbols from $<TARGET_FILE:mscordbi> into file $<TARGET_FILE:mscordbi>.dbg
  [ 94%] Built target mscordbi
  [ 94%] Built target coreclr_static
  make: *** [Makefile:130: all] Error 2
  Failed to build "CoreCLR component".
/home/magus/zmx/runtime/src/coreclr/runtime.proj(32,5): error MSB3073: The command ""/home/magus/zmx/runtime/src/coreclr/build-runtime.sh" -x64 -release -os Linux" exited with code 2.

Build FAILED.

/home/magus/zmx/runtime/src/coreclr/runtime.proj(32,5): error MSB3073: The command ""/home/magus/zmx/runtime/src/coreclr/build-runtime.sh" -x64 -release -os Linux" exited with code 2.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:02:17.57

**Comment by am11** [comment]
Sounds like you are using clang for C and g++ for C++. Can you show the line that starts with `Commencing build of "install" target in "CoreCLR component"` and few lines after that?

They should either match:
```
-- The C compiler identification is GNU X.Y.Z
-- The CXX compiler identification is GNU X.Y.Z
```
or:
```
-- The C compiler identification is Clang X.Y.Z
-- The CXX compiler identification is Clang X.Y.Z
```
without mixing llvm and gnu toolchains.

**Comment by monstercatss** [comment]
suceessful build  using 

> .src/coreclr/build-runtime.sh -skipmanaged -gcc -release

btw Can i see HIR  and LIR in release when gdb corerun，no JitDump



Commencing CoreCLR Repo build
__DistroRid: linux-x64
__RuntimeId: linux-x64
Setting up directories for build
Checking prerequisites...
Commencing build of "CoreCLR component" for Linux.x64.Release in /home/magus/runtime/artifacts/obj/coreclr/Linux.x64.Release
Invoking "/home/magus/runtime/eng/native/gen-buildsys.sh" "/home/magus/runtime/src/coreclr" "/home/magus/runtime/src/coreclr" "/home/magus/runtime/artifacts/obj/coreclr/Linux.x64.Release" x64 gcc "" "" Release ""  -DCLR_ENG_NATIVE_DIR="/home/magus/runtime/eng/native" -DCLR_CMAKE_PGO_INSTRUMENT=0 -DCLR_CMAKE_OPTDATA_PATH= -DCLR_CMAKE_PGO_OPTIMIZE=1 -DCLR_REPO_ROOT_DIR="/home/magus/runtime" 
~/runtime/artifacts/obj/coreclr/Linux.x64.Release ~/runtime/src/coreclr
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/gcc-9
-- Check for working C compiler: /usr/bin/gcc-9 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-9
-- Check for working CXX compiler: /usr/bin/g++-9 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Detected Linux x86_64
-- Performing Test COMPILER_SUPPORTS_F_STACK_PROTECTOR_STRONG
-- Performing Test COMPILER_SUPPORTS_F_STACK_PROTECTOR_STRONG - Success
-- Performing Test COMPILER_SUPPORTS_W_CLASS_MEMACCESS
-- Performing Test COMPILER_SUPPORTS_W_CLASS_MEMACCESS - Success
-- Performing Test COMPILER_SUPPORTS_F_ALIGNED_NEW
-- Performing Test COMPILER_SUPPORTS_F_ALIGNED_NEW - Success
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/gcc-9
....
[ 85%] Built target cee_crossgen
[ 85%] Built target crossgen
[ 99%] Built target cee_wks_core
[100%] Built target coreclr_static
[100%] Built target coreclr
[100%] Built target coreclr_module_index_header
[100%] Built target runtimeinfo
Install the project...
-- Install configuration: "RELEASE"
Repo successfully built.
Product binaries are available at /home/magus/runtime/artifacts/bin/coreclr/Linux.x64.Release
