### ISSUE TITLE
System.Security.Principal.Windows nuget package has latest version 6.0.0-preview.5.21301.5 (last updated 15.06.2021)

### ISSUE THREAD

**Issue by bairog** [dotnet/runtime#85237]
Hello. 
[System.Security.Principal.Windows](https://www.nuget.org/packages/System.Security.Principal.Windows/6.0.0-preview.5.21301.5) nuget package has latest version **6.0.0-preview.5.21301.5** (it is not updated since **15.06.2021**). And this package is not marked as depreceated. 
What is recommended for applications targeting latest .NET vesions (**.NET 7** for example) - use latest stable version (**5.0.0** that is dated **9.11.2020**) or what?

**Comment by huoyaoyuan** [comment]
The package is now in box and you don't need to install anything. See #54365:

> These packages will no longer be updated because their implementation is now part of the .NET 6 platform:
>
> - Microsoft.Win32.Registry
> - System.ComponentModel.Annotations
> - System.IO.FileSystem.AccessControl
> - System.IO.Pipes.AccessControl
> - System.Security.AccessControl
> - System.Security.Cryptography.Cng
> - System.Security.Cryptography.OpenSsl
> - System.Security.Principal.Windows
