### ISSUE TITLE
outerloop-nightly is broken because "native test components" is unavailable

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#85263]
It seems that we skip to upload the "native test components" because of which all the test jobs in `outerloop-nightly` fails because it tries to download those artifacts but doesn't find it. The conditions to skip uploading seems legitimate, so not sure if we should skip downloading them as well with the same conditions check.

https://github.com/dotnet/runtime/blob/c3a2bce1396441511e4a97f174e4d43c7648624f/eng/pipelines/coreclr/templates/build-job.yml#L294-L305

[runtime pipeline](https://dev.azure.com/dnceng-public/public/_build/results?buildId=250191&view=logs&j=39a07da7-60a1-56aa-621d-b74991bb2f3d&t=e2ea621e-9d75-513b-a9e1-ba7aec44bd94)

<img width="885" alt="image" src="https://user-images.githubusercontent.com/12488060/234072287-2422a691-aa34-4b52-be9b-2620a876f286.png">

vs.

[outerloop-nightly pipeline](https://dev.azure.com/dnceng-public/public/_build/results?buildId=249028&view=logs&j=128f4634-3e62-52f1-6764-cb4c2b8330d4)

<img width="640" alt="image" src="https://user-images.githubusercontent.com/12488060/234072351-b72f1a62-8bb4-4894-aca1-e012e6edccbd.png">

and the download job for `native test components` keep failing.

<img width="1536" alt="image" src="https://user-images.githubusercontent.com/12488060/234072607-4591bffc-6a9f-4785-8e47-90740e878e6a.png">

**Comment by kunalspathak** [comment]
@agocke @hoyosjs @jkoritzinsky

**Comment by kunalspathak** [comment]
> In particular, I believe that in our Monday backlog sync-ups JeffSchw looks at the latter so if the intent was to improve outerloop coverage by implementing some checked vs. release build variations, it would seem logical to me to add them to the existing outerloop run instead of creating a new one.

Agree.

**Comment by trylek** [comment]
I have looked at the GitHub history and it looks like the <code>coreclr-release-outerloop-nightly</code> pipeline was either created or ported as part of our repo merging in early 2020. I must admit I have no detailed memory of the pipeline despite the fact that I apparently contributed to it by one or two fixes. While I believe it should be possible to fix the pipeline by adding the <code>testGroup</code> <code>jobParameter</code> when calling <code>build-coreclr-and-libraries-job</code>, longer term I would find it preferable to fold this pipeline into the <code>runtime-coreclr outerloop</code> pipeline provided the various infra stakeholders agree (unless there's some crucial counterargument I'm missing right now).

**Comment by trylek** [comment]
I have triggered an experimental run with my proposed fix for the pipeline:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=250522&view=logs&j=af986455-df3a-5ed6-b067-9144b6c8d0c6

It's only just started but I do see the "Zip / publish native test components" steps in the CoreCLR build jobs. I can send it out for PR if the test finishes fine; we can then have a secondary discussion regarding its potential consolidation with the other outerloop pipeline.

**Comment by trylek** [comment]
OK, so it's far from green (I haven't found any previous green run of the pipeline) but at least it's now actually sending the tests to Helix and just a handful of them is failing, a few test execution jobs have passed. I'm going to go ahead and publish the PR now as a general goodness, I think that some of the test failures are really interesting in terms of test coverage, we may have been missing some of them previously due to using checked builds in the <code>runtime-coreclr outerloop</code> pipeline.

**Comment by kunalspathak** [comment]
> OK, so it's far from green

@TIHan FYI. Please consider checking the unique failures and open issues as appropriate.
