### ISSUE TITLE
[Documentation] Request update on the documentation of IL2026

### ISSUE THREAD

**Issue by Yun-Ting** [dotnet/runtime#85274]
Related to: 
https://github.com/open-telemetry/opentelemetry-dotnet/pull/4428
https://github.com/open-telemetry/opentelemetry-dotnet/pull/4392

On suppressing the warnings for https://github.com/open-telemetry/opentelemetry-dotnet/blob/ef0c9217087bfca0d6fe9206ccde343eb4e5738c/src/OpenTelemetry/Internal/OpenTelemetrySdkEventSource.cs#L203

Regarding the below documentation:
https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-warnings/il2026

When enabling trimming analysis, the message specifies:
"... EventSource will serialize the whole object graph. Trimmer will not safely handle this case because properties may be trimmed. This can be suppressed if the object is a primitive type"

I checked with @eerhardt that IL2026 could be suppressed in this case: https://github.com/open-telemetry/opentelemetry-dotnet/blob/10eb79cdddbe400608fcdf2dd8ccf91d5a36f262/src/OpenTelemetry/Internal/OpenTelemetrySdkEventSource.cs#L203

because the definition of primitive type here is different from the definition of `system.type.isprimitive`.

The definition of the primitive type here means:
https://github.com/dotnet/runtime/blob/ab2b80d06dd4d997df5ffa72a3c4a99cb36ccbff/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/TraceLogging/Statics.cs#L484-L574

I'd like to request an update on the IL2026 documentation to provide the definition/exhaustive list of primitive type where the warning could be safely suppressed.

@agocke , @LakshanF

**Comment by tommcdon** [comment]
@noahfalk @davmason

**Comment by agocke** [comment]
My PR (https://github.com/dotnet/runtime/pull/83751) will make this obsolete as the warning will go away entirely, assuming you are using one of the trim-compatible input types.

**Comment by tommcdon** [comment]
Closing via https://github.com/dotnet/runtime/pull/83751
