### ISSUE TITLE
[TestFailure] System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes

### ISSUE THREAD

**Issue by rzikm** [dotnet/runtime#85290]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=250208
Build error leg or test failing: System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes
Pull request: https://github.com/dotnet/runtime/pull/84976

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

configuration: net48-windows-Release-x86-Windows.10.Amd64.Client.Open

```json
{
  "ErrorMessage": "Assert.Equal() Failure\r\n                        \u2193 (pos 14)\r\nExpected: 175308643975310.8\r\nActual:   175308643975311\r\n                        \u2191 (pos 14)",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

```
Assert.Equal() Failure
                        ↓ (pos 14)
Expected: 175308643975310.8
Actual:   175308643975311
                        ↑ (pos 14)
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[273616](https://dev.azure.com/dnceng-public/public/_build/results?buildId=273616)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=273616&view=ms.vss-test-web.build-test-results-tab&runId=5409236&resultId=100379)||
|[273626](https://dev.azure.com/dnceng-public/public/_build/results?buildId=273626)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=273626&view=ms.vss-test-web.build-test-results-tab&runId=5409216&resultId=100377)||
|[273613](https://dev.azure.com/dnceng-public/public/_build/results?buildId=273613)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=273613&view=ms.vss-test-web.build-test-results-tab&runId=5409214&resultId=100452)||
|[273607](https://dev.azure.com/dnceng-public/public/_build/results?buildId=273607)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=273607&view=ms.vss-test-web.build-test-results-tab&runId=5409174&resultId=100452)||
|[273197](https://dev.azure.com/dnceng-public/public/_build/results?buildId=273197)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=273197&view=ms.vss-test-web.build-test-results-tab&runId=5398228&resultId=100452)||
|[273209](https://dev.azure.com/dnceng-public/public/_build/results?buildId=273209)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=273209&view=ms.vss-test-web.build-test-results-tab&runId=5398218&resultId=100452)||
|[273192](https://dev.azure.com/dnceng-public/public/_build/results?buildId=273192)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=273192&view=ms.vss-test-web.build-test-results-tab&runId=5398208&resultId=100415)||
|[273191](https://dev.azure.com/dnceng-public/public/_build/results?buildId=273191)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=273191&view=ms.vss-test-web.build-test-results-tab&runId=5398194&resultId=100452)||
|[272720](https://dev.azure.com/dnceng-public/public/_build/results?buildId=272720)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=272720&view=ms.vss-test-web.build-test-results-tab&runId=5384756&resultId=100379)||
|[272715](https://dev.azure.com/dnceng-public/public/_build/results?buildId=272715)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=272715&view=ms.vss-test-web.build-test-results-tab&runId=5384760&resultId=100452)||
|[272725](https://dev.azure.com/dnceng-public/public/_build/results?buildId=272725)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=272725&view=ms.vss-test-web.build-test-results-tab&runId=5384742&resultId=100452)||
|[272713](https://dev.azure.com/dnceng-public/public/_build/results?buildId=272713)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=272713&view=ms.vss-test-web.build-test-results-tab&runId=5384734&resultId=100452)||
|[271601](https://dev.azure.com/dnceng-public/public/_build/results?buildId=271601)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=271601&view=ms.vss-test-web.build-test-results-tab&runId=5361566&resultId=100379)||
|[271580](https://dev.azure.com/dnceng-public/public/_build/results?buildId=271580)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=271580&view=ms.vss-test-web.build-test-results-tab&runId=5361618&resultId=100452)||
|[271596](https://dev.azure.com/dnceng-public/public/_build/results?buildId=271596)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=271596&view=ms.vss-test-web.build-test-results-tab&runId=5361590&resultId=100452)||
|[271578](https://dev.azure.com/dnceng-public/public/_build/results?buildId=271578)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=271578&view=ms.vss-test-web.build-test-results-tab&runId=5361538&resultId=100452)||
|[270262](https://dev.azure.com/dnceng-public/public/_build/results?buildId=270262)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=270262&view=ms.vss-test-web.build-test-results-tab&runId=5329300&resultId=100415)||
|[270268](https://dev.azure.com/dnceng-public/public/_build/results?buildId=270268)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=270268&view=ms.vss-test-web.build-test-results-tab&runId=5329232&resultId=100452)||
|[270266](https://dev.azure.com/dnceng-public/public/_build/results?buildId=270266)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=270266&view=ms.vss-test-web.build-test-results-tab&runId=5329258&resultId=100452)||
|[270253](https://dev.azure.com/dnceng-public/public/_build/results?buildId=270253)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=270253&view=ms.vss-test-web.build-test-results-tab&runId=5329218&resultId=100415)||
|[268810](https://dev.azure.com/dnceng-public/public/_build/results?buildId=268810)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=268810&view=ms.vss-test-web.build-test-results-tab&runId=5297148&resultId=100452)||
|[268804](https://dev.azure.com/dnceng-public/public/_build/results?buildId=268804)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=268804&view=ms.vss-test-web.build-test-results-tab&runId=5297094&resultId=100415)||
|[268788](https://dev.azure.com/dnceng-public/public/_build/results?buildId=268788)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=268788&view=ms.vss-test-web.build-test-results-tab&runId=5297066&resultId=100452)||
|[268799](https://dev.azure.com/dnceng-public/public/_build/results?buildId=268799)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=268799&view=ms.vss-test-web.build-test-results-tab&runId=5297080&resultId=100452)||
|[267083](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267083)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267083&view=ms.vss-test-web.build-test-results-tab&runId=5260208&resultId=100452)||
|[267087](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267087)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267087&view=ms.vss-test-web.build-test-results-tab&runId=5260174&resultId=100415)||
|[267078](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267078)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267078&view=ms.vss-test-web.build-test-results-tab&runId=5260144&resultId=100452)||
|[267096](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267096)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267096&view=ms.vss-test-web.build-test-results-tab&runId=5260162&resultId=100415)||
|[265601](https://dev.azure.com/dnceng-public/public/_build/results?buildId=265601)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=265601&view=ms.vss-test-web.build-test-results-tab&runId=5227852&resultId=100379)||
|[265613](https://dev.azure.com/dnceng-public/public/_build/results?buildId=265613)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=265613&view=ms.vss-test-web.build-test-results-tab&runId=5227858&resultId=100452)||
|[265599](https://dev.azure.com/dnceng-public/public/_build/results?buildId=265599)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=265599&view=ms.vss-test-web.build-test-results-tab&runId=5227806&resultId=100452)||
|[265597](https://dev.azure.com/dnceng-public/public/_build/results?buildId=265597)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=265597&view=ms.vss-test-web.build-test-results-tab&runId=5227810&resultId=100415)||
|[265076](https://dev.azure.com/dnceng-public/public/_build/results?buildId=265076)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=265076&view=ms.vss-test-web.build-test-results-tab&runId=5214258&resultId=100379)||
|[265074](https://dev.azure.com/dnceng-public/public/_build/results?buildId=265074)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=265074&view=ms.vss-test-web.build-test-results-tab&runId=5214228&resultId=100452)||
|[265069](https://dev.azure.com/dnceng-public/public/_build/results?buildId=265069)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=265069&view=ms.vss-test-web.build-test-results-tab&runId=5214222&resultId=100415)||
|[265067](https://dev.azure.com/dnceng-public/public/_build/results?buildId=265067)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=265067&view=ms.vss-test-web.build-test-results-tab&runId=5214220&resultId=100452)||
|[264525](https://dev.azure.com/dnceng-public/public/_build/results?buildId=264525)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=264525&view=ms.vss-test-web.build-test-results-tab&runId=5202460&resultId=100452)||
|[264520](https://dev.azure.com/dnceng-public/public/_build/results?buildId=264520)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=264520&view=ms.vss-test-web.build-test-results-tab&runId=5202476&resultId=100415)||
|[264529](https://dev.azure.com/dnceng-public/public/_build/results?buildId=264529)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=264529&view=ms.vss-test-web.build-test-results-tab&runId=5202480&resultId=100452)||
|[264521](https://dev.azure.com/dnceng-public/public/_build/results?buildId=264521)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=264521&view=ms.vss-test-web.build-test-results-tab&runId=5202472&resultId=100452)||
|[263425](https://dev.azure.com/dnceng-public/public/_build/results?buildId=263425)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=263425&view=ms.vss-test-web.build-test-results-tab&runId=5176568&resultId=100452)||
|[263426](https://dev.azure.com/dnceng-public/public/_build/results?buildId=263426)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=263426&view=ms.vss-test-web.build-test-results-tab&runId=5176522&resultId=100415)||
|[263424](https://dev.azure.com/dnceng-public/public/_build/results?buildId=263424)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=263424&view=ms.vss-test-web.build-test-results-tab&runId=5176548&resultId=100452)||
|[263420](https://dev.azure.com/dnceng-public/public/_build/results?buildId=263420)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=263420&view=ms.vss-test-web.build-test-results-tab&runId=5176518&resultId=100415)||
|[262068](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262068)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262068&view=ms.vss-test-web.build-test-results-tab&runId=5141844&resultId=100452)||
|[262067](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262067)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262067&view=ms.vss-test-web.build-test-results-tab&runId=5141780&resultId=100415)||
|[262058](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262058)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262058&view=ms.vss-test-web.build-test-results-tab&runId=5141770&resultId=100452)||
|[262051](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262051)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262051&view=ms.vss-test-web.build-test-results-tab&runId=5141784&resultId=100452)||
|[260630](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260630)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260630&view=ms.vss-test-web.build-test-results-tab&runId=5105910&resultId=100415)||
|[260624](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260624)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260624&view=ms.vss-test-web.build-test-results-tab&runId=5105882&resultId=100415)||
|[260634](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260634)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260634&view=ms.vss-test-web.build-test-results-tab&runId=5105942&resultId=100452)||
|[260633](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260633)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260633&view=ms.vss-test-web.build-test-results-tab&runId=5105912&resultId=100452)||
|[259071](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259071)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259071&view=ms.vss-test-web.build-test-results-tab&runId=5064154&resultId=100452)||
|[259058](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259058)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259058&view=ms.vss-test-web.build-test-results-tab&runId=5064104&resultId=100415)||
|[259070](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259070)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259070&view=ms.vss-test-web.build-test-results-tab&runId=5064218&resultId=100452)||
|[259051](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259051)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259051&view=ms.vss-test-web.build-test-results-tab&runId=5064138&resultId=100452)||
|[257915](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257915)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257915&view=ms.vss-test-web.build-test-results-tab&runId=5036158&resultId=100415)||
|[257900](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257900)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257900&view=ms.vss-test-web.build-test-results-tab&runId=5036152&resultId=100452)||
|[257897](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257897)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257897&view=ms.vss-test-web.build-test-results-tab&runId=5036136&resultId=100415)||
|[257903](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257903)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257903&view=ms.vss-test-web.build-test-results-tab&runId=5036150&resultId=100211)||
|[257408](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257408)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257408&view=ms.vss-test-web.build-test-results-tab&runId=5024532&resultId=100452)||
|[257389](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257389)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257389&view=ms.vss-test-web.build-test-results-tab&runId=5024506&resultId=100452)||
|[257403](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257403)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257403&view=ms.vss-test-web.build-test-results-tab&runId=5024522&resultId=100415)||
|[257399](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257399)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257399&view=ms.vss-test-web.build-test-results-tab&runId=5024518&resultId=100415)||
|[257044](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257044)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257044&view=ms.vss-test-web.build-test-results-tab&runId=5013552&resultId=100452)||
|[257045](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257045)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257045&view=ms.vss-test-web.build-test-results-tab&runId=5013536&resultId=100452)||
|[257040](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257040)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257040&view=ms.vss-test-web.build-test-results-tab&runId=5013532&resultId=100415)||
|[257024](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257024)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257024&view=ms.vss-test-web.build-test-results-tab&runId=5013524&resultId=100415)||
|[255861](https://dev.azure.com/dnceng-public/public/_build/results?buildId=255861)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=255861&view=ms.vss-test-web.build-test-results-tab&runId=4987100&resultId=100415)||
|[255854](https://dev.azure.com/dnceng-public/public/_build/results?buildId=255854)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=255854&view=ms.vss-test-web.build-test-results-tab&runId=4987046&resultId=100452)||
|[255846](https://dev.azure.com/dnceng-public/public/_build/results?buildId=255846)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=255846&view=ms.vss-test-web.build-test-results-tab&runId=4987016&resultId=100415)||
|[255856](https://dev.azure.com/dnceng-public/public/_build/results?buildId=255856)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=255856&view=ms.vss-test-web.build-test-results-tab&runId=4987038&resultId=100452)||
|[254410](https://dev.azure.com/dnceng-public/public/_build/results?buildId=254410)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=254410&view=ms.vss-test-web.build-test-results-tab&runId=4948032&resultId=100452)||
|[254406](https://dev.azure.com/dnceng-public/public/_build/results?buildId=254406)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=254406&view=ms.vss-test-web.build-test-results-tab&runId=4948002&resultId=100452)||
|[254400](https://dev.azure.com/dnceng-public/public/_build/results?buildId=254400)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=254400&view=ms.vss-test-web.build-test-results-tab&runId=4947994&resultId=100452)||
|[254395](https://dev.azure.com/dnceng-public/public/_build/results?buildId=254395)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=254395&view=ms.vss-test-web.build-test-results-tab&runId=4947932&resultId=100452)||
|[253026](https://dev.azure.com/dnceng-public/public/_build/results?buildId=253026)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=253026&view=ms.vss-test-web.build-test-results-tab&runId=4913368&resultId=100452)||
|[253024](https://dev.azure.com/dnceng-public/public/_build/results?buildId=253024)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=253024&view=ms.vss-test-web.build-test-results-tab&runId=4913192&resultId=100415)||
|[253030](https://dev.azure.com/dnceng-public/public/_build/results?buildId=253030)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=253030&view=ms.vss-test-web.build-test-results-tab&runId=4913180&resultId=100452)||
|[253014](https://dev.azure.com/dnceng-public/public/_build/results?buildId=253014)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=253014&view=ms.vss-test-web.build-test-results-tab&runId=4913252&resultId=100452)||
|[251307](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251307)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251307&view=ms.vss-test-web.build-test-results-tab&runId=4870580&resultId=100452)||
|[251291](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251291)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251291&view=ms.vss-test-web.build-test-results-tab&runId=4870554&resultId=100452)||
|[250208](https://dev.azure.com/dnceng-public/public/_build/results?buildId=250208)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=250208&view=ms.vss-test-web.build-test-results-tab&runId=4844796&resultId=100200)|dotnet/runtime#84976|
|[249837](https://dev.azure.com/dnceng-public/public/_build/results?buildId=249837)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=249837&view=ms.vss-test-web.build-test-results-tab&runId=4833400&resultId=100422)||
|[249824](https://dev.azure.com/dnceng-public/public/_build/results?buildId=249824)|dotnet/runtime|[System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesAllDataTypes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=249824&view=ms.vss-test-web.build-test-results-tab&runId=4833340&resultId=100459)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|4|28|85|

**Comment by tommcdon** [comment]
@tarekgh

**Comment by tarekgh** [comment]
@noahfalk will be the best to look at this one if possible.

**Comment by tarekgh** [comment]
https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/#making-the-formatter-ieee-754-2008-compliant

**Comment by tarekgh** [comment]
The failure is on `net48-windows-Release-x86-Windows` and not on net core. The link I pasted shows the divergence in the floating point since net core 3.0. So, I expect we can run into differences when running on NETFX. I don't know why this started to show up though but I don't expect any change done in the NETFX can cause this failure.

**Comment by noahfalk** [comment]
ah! I missed that net48 entirely, thanks!
