### ISSUE TITLE
*.comhost.dll support arm64x

### ISSUE THREAD

**Issue by fuxuejun** [dotnet/runtime#85291]
I have a com server project and have set EnableComHosting to true. RuntimeIdentifiers is win-x64, win-x86, win-arm64.
It work's fine in windowx x86 or windows x64, but not work in windows 11 arm.
The x86/x64 process works well on window 11 arm. but the arm64 process is not work.
I found [https://learn.microsoft.com/zh-cn/windows/arm/arm64x-build](url)  arm64x support x64 and arm64 process, but the default *.comhost.dll is not work.

**Comment by vitek-karas** [comment]
Could you please provide more information about "it doesn't work"?

/cc @elinor-fung

**Comment by vitek-karas** [comment]
What target framework do you use? I just tried building the [COMServer sample](https://github.com/dotnet/samples/tree/main/core/extensions/COMServerDemo) for `win-arm64` and that does produce a `COMServer.comhost.dll`. This is targeting `net7.0`.

**Comment by fuxuejun** [comment]
I use .net 8.0.0-preview.3.23178.1, and I build win-x86, win-x64, win-arm64.

dotnet publish PangIME.csproj -c RELEASE -o x64 -r win-x64
dotnet publish PangIME.csproj -c RELEASE -o x86 -r win-x86
dotnet publish PangIME.csproj -c RELEASE -o arm64 -r win-arm64

x64 pc can load x64/pangime.comhost.dll and x86/pangime.comhost.dll.
arm64 pc can only load  x64/pangime.comhost.dll and x86/pangime.comhost.dll, arm64 process can't load arm64/pangime.comhost.dll

**Comment by fuxuejun** [comment]
TargetFramework is net8-windows.

Com client can not find arm64/foo.comhost.dll, because regedit is not save the com register infomation, but regsvr32 report success.

**Comment by elinor-fung** [comment]
> Com client can not find arm64/foo.comhost.dll

What is the error / hresult that the client gets when it fails to activate the COM server?

> not save the com register infomation, but regsvr32 report success.

That is definitely odd. Could you enable host tracing when running regsvr32 for the arm64 comhost?
- Set `COREHOST_TRACE=1` and `COREHOST_TRACEFILE=<path_to_file>` environment variables per https://learn.microsoft.com/dotnet/core/tools/dotnet-environment-variables#corehost_trace
- Run `regsvr32 ...`

If you are willing to capture [Procmon](https://learn.microsoft.com/sysinternals/downloads/procmon) logs of running regsvr32 and then of running the arm64 COM client, that would also be helpful.

Note that the trace file and logs can contain things like local paths, so only share it if you're okay with the information it contains.

> if the foo.comhost.dll support arm64x

I just want to point out that the .NET runtime does not support arm64x - it is only arm64.
