### ISSUE TITLE
Assembly Version of System.DirectoryServices.Protocols 7.0.0 is 4.0.0.0 (and maybe a problem for finding the assembly during runtime?)

### ISSUE THREAD

**Issue by rominator1983** [dotnet/runtime#85296]
### Description

Package System.DirectoryServices.Protocols 7.0.0 has assemblies with assembly version 4.0.0.0.
This is not intuitive as it is a lower assembly version than before (6.0.0.1 in package 6.0.1)
I did not check the previews on [nuget.org](https://www.nuget.org/packages/System.DirectoryServices.Protocols/6.0.1)

I expected the assembly (there are several in there) version to be 7.0.0.0.

I am not sure if that is causing an issue described in https://stackoverflow.com/questions/75619100/system-io-filenotfoundexception-could-not-load-file-or-assembly/76098560#76098560 (I wrote the only answer on that. There are some findings on google so it seems to hit some people when using 7.0.0). Not quite sure what's going on here.

### Reproduction Steps

`dotnet add package System.DirectoryServices.Protocols`

### Expected behavior

Assembly version should be 7.0.0.0

### Actual behavior

`dotnet add package System.DirectoryServices.Protocols` leads to assembly version 4.0.0.0

### Known Workarounds

Use previous package version 6.0.1

### Other information

https://stackoverflow.com/questions/75619100/system-io-filenotfoundexception-could-not-load-file-or-assembly/76098560#76098560

**Comment by rominator1983** [comment]
Should I report the dependency loading issue at the [dotnet sdk](https://github.com/dotnet/sdk) ?

**Comment by vcsjones** [comment]
This version should be 4.0.0.0 for the assembly version. There is some background on "why" from @ericstj at https://github.com/dotnet/runtime/issues/84031#issuecomment-1487359031:

> The reason that DirectoryServices.Protocols remains at 4.0.0.0 is because it has the same name as the .NETFramework assembly, and exposes a netstandard2.0 assembly. For that to work it must keep the netstandard2.0 assembly <= 4.0.0.0 so that the package does not try to replace the .NETFramework assembly.

> In this case the bug seems to be that the 6.0.1 package version of System.DirectoryServices.Protocols accidentally shipped assembly version 6.0.0.1 then the newer package version 7.0.0 shipped the lower assembly version.

**Comment by rominator1983** [comment]
Thanks for the quick and profound answer @ericstj 
I will close the issue once everything is working fine on our side of things.

**Comment by steveharter** [comment]
> Thanks for the quick and profound answers @ericstj and @vcsjones
I will close the issue once everything is working fine on our side of things.

Closing as assumed fixed.
