### ISSUE TITLE
Broken build on Arch Linux

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#85315]
I assume this will be problem for any rolling distro, not just Arch Linux. `VERSION_ID` is optional in `/etc/os-release`: https://www.freedesktop.org/software/systemd/man/os-release.html#VERSION_ID. And together with `set -u` in `build.sh`: 
https://github.com/dotnet/runtime/blob/19d545c62c3eea1836e8c3830eb654e2a022cac7/eng/build.sh#L3
results in:
```
/home/manicka/repositories/runtime.2/eng/native/init-distro-rid.sh: line 28: VERSION_ID: unbound variable
```

@tmds @ViktorHofer I suspect #82832 PR broke it.

I can workaround it locally with removing `set -u`, but I'm not sure if that's what you'd prefer as a solution.

**Comment by ViktorHofer** [comment]
@tmds can you please take a look?

cc @akoeplinger and @am11 just FYI
