### ISSUE TITLE
cannot build native oat in visual studio code

### ISSUE THREAD

**Issue by NCLnclNCL** [dotnet/runtime#85325]
### Description

I installed Desktop Development
ment for C++ in visual studio 2017 but I still get the same error when I build

### Reproduction Steps

dotnet publish -r win-x64 -c Release

### Expected behavior

success

### Actual behavior

C:\Program Files\dotnet\sdk\7.0.203\Sdks\Microsoft.DotNet.ILCompiler\build\Microsoft.NETCore.Native.Windows.targets(116,5): error : Platform link 
er not found. To fix this problem, download and install Visual Studio 2022 from http://visualstudio.com. Make sure to install the Desktop Develop 
ment for C++ workload. For ARM64 development also install C++ ARM64 build tools.

### Configuration

.net 7
window 10
x64
visual studio code

**Comment by vitek-karas** [comment]
Could you please follow the build requirements as described here: https://github.com/dotnet/runtime/blob/main/docs/workflow/requirements/windows-requirements.md

**Comment by jkotas** [comment]
> Could you please follow the build requirements as described here: https://github.com/dotnet/runtime/blob/main/docs/workflow/requirements/windows-requirements.md

There are pre-requisites for building dotnet/runtime. Pre-requisites for PublishAot are documented at: 
https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/#prerequisites .

> C++ in visual studio 2017 

Native AOT requires Visual Studio 2022 tools. We have no plans to support older Visual Studio versions.
