### ISSUE TITLE
Wasm SDK Multitargeting conventions for net8.0-browser

### ISSUE THREAD

**Issue by javiercn** [dotnet/runtime#85333]
We need to teach the SDK about net8.0-browser and add appropriate conventions similar to the ones that maui has as described [here](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/single-project?view=net-maui-7.0#platform-specific-code)

https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/configure-multi-targeting?view=net-maui-7.0

Tasks:

- [x] Check TPI and add `TargetPlatformSupported=true` property and `SdkSupportedTargetPlatformVersion=1.0` itemgroup to `Microsoft.NET.Workload.Mono.Toolchain.Current.Manifest/WorkloadManifest.targets.in` - https://github.com/dotnet/runtime/pull/87866
- [x] Fix [platform analyzer](https://github.com/dotnet/roslyn-analyzers) so it doesn't complain about version 1.0 for browser, https://github.com/dotnet/roslyn-analyzers/pull/6707

**Comment by lewing** [comment]
cc @steveisok

**Comment by akoeplinger** [comment]
This is done.
