### ISSUE TITLE
DataView does not unescape sort strings

### ISSUE THREAD

**Issue by miloush** [dotnet/runtime#85367]
### Description

Citing Remarks for [`DataTable.Select`](https://docs.microsoft.com/en-us/dotnet/api/system.data.datatable.select):

> The Sort argument also uses the same rules for creating class's [Expression](https://learn.microsoft.com/en-us/dotnet/api/system.data.datacolumn.expression?view=net-7.0) strings.

and the referenced expression syntax:

> If the column name is enclosed in square brackets then any `]` and `\` characters (but not any other characters) in it must be escaped by prepending them with the backslash (`\`) character. If the column name is enclosed in grave accent characters then it must not contain any grave accent characters in it.

However, `DataTable.ParseSortString` simply does not do that:

https://github.com/dotnet/runtime/blob/455150f3c0768760030f7dc5aceea05aa3aac6c1/src/libraries/System.Data.Common/src/System/Data/DataTable.cs#L3700-L3705

1) completely inappropriately splits the string by comma first
2) does not unencode column names enclosed by `[` `]`
3) does not support column names enclosed by `` ` ``

### Reproduction Steps

```C#
DataTable dt = new DataTable();
dt.Columns.Add("ahoj,test");
dt.DefaultView.Sort = @"[ahoj,test]";
```

### Expected behavior

The sort string is accepted as per documentation.

### Actual behavior

System.ArgumentException: ' [ahoj isn't a valid Sort string entry.'

### Regression?

Repros in .NET Framework

### Configuration

8.0.0-preview.3.23174.8
25346.1001.amd64fre.rs_prerelease.230415-1347

**Comment by Wraith2** [comment]
I think we could probably use he name parsing code from Microsoft.Data.Sqlclient to deal with this.

**Comment by roji** [comment]
I agree that the behavior here is far from satisfactory. However, this is a very old component that is no longer being actively developed, and the priority here is stability and maintaining backwards compatibility. And unfortunately, any change in the logic of the expression parsing is likely to be breaking to a lot of existing users.

So at this point I'm closing this issue despite the problems with this API. I generally recommend considering moving off of DataAdapter/DataTable and related types.

**Comment by miloush** [comment]
The cases brought up are currently throwing and the expectation is to make them not throwing and fulfill the documented behavior. Do you have any example how that would break a backwards compatibility?

> I generally recommend considering moving off of DataAdapter/DataTable and related types.

What do you recommend moving to instead?

**Comment by roji** [comment]
> Do you have any example how that would break a backwards compatibility?

I'd have to think about it some more, but this is typically a case where we'd avoid doing a change unless it's very necessary and very safe. This code has been like this for decades at this point, and hasn't been actively developed for many years.

> What do you recommend moving to instead?

That depends on what exactly you're looking for... Dapper or EF are good options for data access in .NET, and there are quite a few others out there.
