### ISSUE TITLE
adopting cgroup2 in coreclr

### ISSUE THREAD

**Issue by Maoni0** [dotnet/runtime#854]
from [corefx 39673](https://github.com/dotnet/corefx/issues/39673), cgroup2 is out. @janvorli would you please take a look at cgroup2 and see if it's a simple matter of adopting it (eg, read the same values just from different places kind of thing) or does it mean we'll need to handle new scenarios enabled by cgroup2 and/or does it make us change anything we are currently doing?

**Comment by omajid** [comment]
FWIW, this should have been fixed by https://github.com/dotnet/runtime/pull/34334 (aside from any new features, like Pressure Stall Information, like mentioned above).

**Comment by Maoni0** [comment]
thank you very much for your contribution, @omajid :+1:

**Comment by omajid** [comment]
I am interested in investigating Pressure Stall Information. Any pointers on how I can get started and where the interesting hook-points for hooking that into coreclr might be?

**Comment by Maoni0** [comment]
there was already [an attempt](https://github.com/dotnet/runtime/pull/958) by @lpereira but he didn't have time to finish. please feel free to take a look at that.

**Comment by mangod9** [comment]
Since cgroupv2 support is now enabled, perhaps we should create a separate issue for Pressure Stall Information and close this?

**Comment by mangod9** [comment]
Closing since cgroup2 support is now enabled.
