### ISSUE TITLE
Can we have better doc on inner loop workflow for testing runtime changes in a BlazorWasm app?

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#85413]
I found the process to test these with a BlazorWasm app to be somewhat cumbersome and error-prone. I didn't find and doc on this, such as at https://github.com/dotnet/runtime/blob/main/src/mono/wasm/build/README.md. 

I do not make changes specifically for BlazorWasm or Mono interpreter often, so here's my primitive and brute-force workflow for getting library and runtime changes so I can test those within a Blazor app, which I'm sure is not ideal:
1) Make runtime and\or library changes (e.g. in `C:\git\runtime`)
2) Copy those changes to the current package location. If copied locally into the WASM app location bin staging area, these seem to get overridden during publish.
    - e.g. for runtime changes: `copy C:\git\runtime\artifacts\bin\microsoft.netcore.app.runtime.browser-wasm\Release\runtimes\browser-wasm\native\System.Private.CoreLib.dll C:\Users\<YOURNAME>\.nuget\packages\microsoft.netcore.app.runtime.mono.browser-wasm\8.0.0-preview.3.23174.8\runtimes\browser-wasm\native\`.
    - This is super fragile and assumes my local build is compatible with the referenced version in the app's .csproj's `PackageReference`.
    - Some alternatives, partially explored, is to either add a `<Reference Include>` to the .csproj to point to a local copy of `System.Private.CoreLib.dll`, for example, which would override the package version, or publish my local build and do some nuget package redirection. Not sure what devs that work in this area do.
3) In the BlazorWasm app folder, delete the build artifacts so that publish will update the staging area: `del /q /s obj\Release\net8.0 && del /q /s bin\Release\net8.0`
4) Publish: `dotnet publish -c release`
5) Change directory to `wwwroot` (it appears the active directory must be `wwwroot`): `cd bin\Release\net8.0\publish\wwwroot\`
6) Run: `dotnet serve`

**Comment by steveisok** [comment]
@lewing I think having a runtime pack location override would be helpful here.

**Comment by maraf** [comment]
You can override the location where blazor searches for runtime pack using

```xml
<Target Name="UpdateRuntimePack" AfterTargets="ResolveFrameworkReferences">
	<ItemGroup>
		<ResolvedRuntimePack PackageDirectory="C:\git\runtime\artifacts\bin\microsoft.netcore.app.runtime.browser-wasm\Debug" Condition="'%(ResolvedRuntimePack.FrameworkName)' == 'Microsoft.NETCore.App'" />
	</ItemGroup>
</Target>
```

**Comment by steveharter** [comment]
> And using dotnet run -c Release should eliminate steps 3-6 or do you explicitly need to run publish?

For my case, I need to publish in order to verify trimming.

**Comment by maraf** [comment]
> For my case, I need to publish in order to verify trimming.

Ook. Than `dotnet serve` has the `-d` option, eg `dotnet serve -d:.\bin\Release\net8.0\publish\wwwroot`
