### ISSUE TITLE
JIT: Assertion failed '(refPosition->refType == RefTypeUpperVectorRestore) || (genCountBits(candidates) == 1)' during 'LSRA build intervals'

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#85426]
libraries-jitstress is hitting this in a few jobs, for example https://dev.azure.com/dnceng-public/public/_build/results?buildId=252833&view=ms.vss-test-web.build-test-results-tab&runId=4908054&resultId=177607&paneView=debug

```scala
Assert failure(PID 28 [0x0000001c], Thread: 396 [0x018c]): Assertion failed '(refPosition->refType == RefTypeUpperVectorRestore) || (genCountBits(candidates) == 1)' in 'System.Buffers.ProbabilisticMap:IndexOfAnyVectorized(byref,byref,int,System.ReadOnlySpan`1[ushort]):int' during 'LSRA build intervals' (IL size 203; hash 0x36e94114; Tier1)

    File: /__w/1/s/src/coreclr/jit/lsra.cpp Line: 12346
    Image: /root/helix/work/correlation/dotnet
```

I was able to get a partial jitdump (it hit segfault after printing this) which I've attached.

[out.txt](https://github.com/dotnet/runtime/files/11337830/out.txt)

**Comment by BruceForstall** [comment]
New assert related to arm64 consecutive registers support.

**Comment by kunalspathak** [comment]
I will take a look.
