### ISSUE TITLE
Strange permissions issue when calling dylib function from C#

### ISSUE THREAD

**Issue by CamJN** [dotnet/runtime#85428]
### Description

I have a library I've written (libgetargv) which gets the arguments of other processes on macOS. It is written in C due to the backing API being a C API. I have written wrappers for this library in Swift, Rust, Ruby, Node, Python, and Java (which I only mention to indicate I have done this many times and know what I'm doing in general). I am now working on adding a wrapper for C#/dotnet.

In my unit tests I call the function to get the args of the test process itself so that I know that 1) the process exists, and 2) that I have permission to see the args (on macOS you can only see the args of pids running as the same user unless you call the function as root).

Unlike in every other language I've written wrappers for, I get a permission denied error, despite the process looking at itself. (that is, if the target PID exists, I can tell I'm not just getting a permission error all the time because for PIDs that don't exist I get a proper process-not-found error).

I also tested calling the function using a pid that I tested separately using a tool in another language and which I could see i had permission to look at, that also resulted in a permission denied error in C#/dotnet.

### Reproduction Steps

It could be difficult to provide a reproduction project, and it would have to run on macOS because it's a macOS-only API that the library uses. I'll see what I can come up with.

### Expected behavior

No weird permission problems unique to dotnet.

### Actual behavior

Weird permission problems unique to dotnet.

### Regression?

unknown

### Known Workarounds

none

### Configuration

`dotnet --version`:`7.0.100`
`sw_vers`:
```
ProductName:		macOS
ProductVersion:		13.3.1
BuildVersion:		22E261
```
`machine`: `x86_64h`
unknown if it is specific to this configuration
I do not use blazor

**Comment by jkotas** [comment]
Could you please share the steps to reproduce the issue?

**Comment by CamJN** [comment]
To reproduce you will need the macOS CLT installed, and the dotnet cli tool

```
git clone https://github.com/getargv/getargv.cs
git clone https://github.com/CamJN/stub-getargv
cd stub-getargv
make
make install # might need sudo depending on permissions of /usr/local dir
cd ../getargv.cs
dotnet build
dotnet test
```

**Comment by CamJN** [comment]
Sorry I missed a bit of needed demo code before it should be working now.

You will need the macOS CLT and dotnet cli tool installed.

```
git clone https://github.com/getargv/getargv.cs
git clone https://github.com/CamJN/stub-getargv
cd stub-getargv
make
make install # make need sudo depending on your /usr/local dir's permissions
cd ../getargv.cs
dotnet test
```

**Comment by CamJN** [comment]
Hmm not a permission problem after all, the pid is 0 when passed to the function, yet I set it in the struct before calling the function in the test, oh well more than likely a problem on my end.
