### ISSUE TITLE
Component governance failing on musl legs of servicing branches

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#85492]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=253921
Build error leg or test failing: CoreCLR  Product Build Linux_musl x64 checked / Component Detection (auto-injected by policy)
Pull request: https://github.com/dotnet/runtime/pull/85425

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "globalThis is not defined",
  "BuildRetry": false,
  "ExcludeConsoleLog": true
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by hoyosjs** [comment]
@mmitche @dkurepa didn't we stop componentGovernance on public?

**Comment by mmitche** [comment]
@wtgodbe's changes just got checked in to arcade. That may be why we we're still seeing this. Btw I think this may fixed now on CG's side.

**Comment by wtgodbe** [comment]
This should be fixed once https://github.com/dotnet/arcade/pull/13274 flows through here

**Comment by wtgodbe** [comment]
Oh, sorry, this is servicing - needs https://github.com/dotnet/arcade/pull/13282

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by agocke** [comment]
We managed to skip this.
