### ISSUE TITLE
JIT does not promote Span<T> in R2R code

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#85511]
Outside the SPC version bubble crossgen2 returns `CORINFO_FLG_DONT_DIG_FIELDS` despite the fact that `Span<T>/ReadOnlySpan<T>` are not versionable. This means the JIT does not promote spans in R2R code.
Talked a bit with @davidwrighton and it might be problematic to let JIT ask questions about the fields even for non-versionable types -- so we may need to special case `Span<T>`/`ReadOnlySpan<T>` in some way. Or we can introduce more specific JIT-EE helper for the purpose of promotion so that crossgen2 can make a more fine grained decision of what dependencies the JIT is allowed to make.

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib

**Comment by jkotas** [comment]
> it might be problematic to let JIT ask questions about the fields even for non-versionable types

Why would it be problematic?

**Comment by jakobbotsch** [comment]
> Why would it be problematic?

@davidwrighton can probably answer better what his concerns were.

I've looked and I don't think it would be problematic for the questions we ask as part of promotion in the JIT. I suppose the problematic case would be if the JIT causes crossgen2 to suddenly need to encode some fixup referring to fields outside the version bubble, but the closest we get is with `getClassSize` and that knows not to emit the fixups for non-versionable cases (provided fields of non-versionable types are going to be non-versionable -- which I imagine is a precondition).

**Comment by davidwrighton** [comment]
`getFieldOffset` also needs to emit fixups in the general sense, but as you note, that isn't necessary for `NonVersionable` structures. My biggest concern about something like this is that its easy for the contract we define here to get lost, and then in 5 years somebody adds a call to the jit interface that isn't safe under some truly obscure condition, and we don't find the issue out until a customer scenario breaks.

According to @jakobbotsch in an offline conversation, the jit really just needs to have the struct broken down into primitives, and I feel that we could fairly easily have the VM side of the world do that, and in crossgen2 determining if its safe/not safe to do so would be pretty trivial. I'm imagining an api that would return a table like the following

|FieldOrdinal|FieldPrimitiveType|FieldOffset|
|----|---|---|
|0|CORINFO_TYPE_INT|0|
|1|CORINFO_TYPE_BOOL|4|
|2|CORINFO_TYPE_CLASS|8|

And would have some flag which would indicate that no, it couldn't translate to the specified type.
