### ISSUE TITLE
Children of a custom Layout control are not displayed in Design view

### ISSUE THREAD

**Issue by dafo** [dotnet/runtime#85515]
### Description

I have an issue that looks like a regression (I reproduce it in .NET Framework 4.8.1), however I was not able to confirm in what version the behavior has changed.
I have a custom Layout control (Dialog window) which inherits from System.Web.UI.WebControls.WebControl. I use the Dialog control in an application where I place a standard TextBox and a standard Button components inside its’ ContentPane’s template. When I run the application in the browser the standard ASP.NET components are displayed correctly inside the Dialog’s content. However, when I open the Design View inside VS 2019 or 2022 – no TextBox or Button is displayed inside the Dialog. In previous versions the content was displayed correctly. 

This is how the attributes for my custom Dialog Window control look like:
```
[ParseChildren(true)]
[PersistChildren(false)]
[Designer("Infragistics.Web.UI.Design.DialogWindowDesigner," + AssemblyVersion.DesignerAssemblyName)]
[ToolboxData("<{0}:WebDialogWindow runat=\"server\" Width=\"400px\" Height=\"300px\" ></{0}:WebDialogWindow>
System.Drawing.ToolboxBitmap(typeof(Infragistics.Web.UI.LayoutControls.WebDialogWindow), "WebDialogWindow.png"
UltraLicense("WebDialogWindow")]
public class WebDialogWindow : LayoutControl
```

I have ‘GetDesignTimeHtml’ method overridden like that:

```
public override string GetDesignTimeHtml(System.Web.UI.Design.DesignerRegionCollection regions)
{
  if (...)
	  ...
  else if (...)
	  ...
  else
  {
	  if (this._dialogWindow.Header.MinimizeBox.Visible)
		  regions.Add(new DesignerRegion(this, "MinButton", false));
	  if (this._dialogWindow.Header.CloseBox.Visible)
		  regions.Add(new DesignerRegion(this, "CloseButton", false));
	  if (this._dialogWindow.ContentPane.HasContentOrUserUrl() == DefaultableBoolean.NotSet)
		  regions.Add(new EditableDesignerRegion(this, "Content", false));
  }
  return base.GetDesignTimeHtml();
}
```
And the call to `base.GetDesignTimeHtml()` is what returns the HTML without the content (Button and TextBox). 
I was not able to find if anything was changed in the last versions that would affect this behavior, so I would appreciate any help on the scenario. I am attaching an example application that reproduces the issue.
[sample.zip](https://github.com/dotnet/runtime/files/11352977/sample.zip)

### Reproduction Steps

1. Run the attached sample in VS 2022
2. Open Default.aspx
3. Navigate to the Design view (or Split view)

### Expected behavior

 `<asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>` and `<asp:Button ID="Button1" runat="server" Text="Button" />` should be displayed inside the Dialog Window control

### Actual behavior

Both Button and TextBox are not displayed inside the Dialog Window

### Regression?

Yes. This is also confirmed by our end user. However, I was not able to confirm the exact version the behavior changed.

### Known Workarounds

N/A

### Configuration

.NET Framework 4.8.1
x64
I am not sure if it is specific to that configuration.

**Comment by jkotas** [comment]
@dafo We track .NET Framework issues via Visual Studio dev community. Can you please create an issue on https://developercommunity.visualstudio.com/home instead?
