### ISSUE TITLE
[mono][llvm] Linux-arm64 llvmfullaot build fails with missing libclang-9.so.1

### ISSUE THREAD

**Issue by jandupej** [dotnet/runtime#85529]
Build fails with `Libclang '/usr/lib/llvm-9/lib/libclang-9.so.1' doesn't exist.` It's on an extra platform, so removing `blocking-clean-ci`

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=255903
Build error leg or test failing: Build / linux-arm64 Release AllSubsets_Mono_LLVMFullAot_RuntimeTests llvmfullaot / Build Mono LLVM AOT cross compiler
Pull request: https://github.com/dotnet/runtime/pull/85458

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Libclang '/usr/lib/llvm-9/lib/libclang-9.so.1' doesn't exist.",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[270179](https://dev.azure.com/dnceng-public/public/_build/results?buildId=270179)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/270179/logs/848)|dotnet/runtime#86050|
|[270139](https://dev.azure.com/dnceng-public/public/_build/results?buildId=270139)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/270139/logs/788)||
|[269658](https://dev.azure.com/dnceng-public/public/_build/results?buildId=269658)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/269658/logs/758)||
|[269142](https://dev.azure.com/dnceng-public/public/_build/results?buildId=269142)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/269142/logs/560)|dotnet/runtime#86050|
|[268718](https://dev.azure.com/dnceng-public/public/_build/results?buildId=268718)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/268718/logs/746)||
|[268078](https://dev.azure.com/dnceng-public/public/_build/results?buildId=268078)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/268078/logs/686)||
|[267827](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267827)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267827/logs/622)||
|[267715](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267715)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267715/logs/479)|dotnet/runtime#85908|
|[267007](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267007)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267007/logs/770)||
|[266742](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266742)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266742/logs/635)||
|[266495](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266495)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266495/logs/593)||
|[265629](https://dev.azure.com/dnceng-public/public/_build/results?buildId=265629)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/265629/logs/716)|dotnet/runtime#85908|
|[266409](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266409)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266409/logs/713)||
|[265427](https://dev.azure.com/dnceng-public/public/_build/results?buildId=265427)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/265427/logs/666)|dotnet/runtime#85810|
|[265291](https://dev.azure.com/dnceng-public/public/_build/results?buildId=265291)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/265291/logs/768)||
|[265057](https://dev.azure.com/dnceng-public/public/_build/results?buildId=265057)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/265057/logs/800)||
|[264846](https://dev.azure.com/dnceng-public/public/_build/results?buildId=264846)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/264846/logs/775)||
|[264752](https://dev.azure.com/dnceng-public/public/_build/results?buildId=264752)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/264752/logs/532)|dotnet/runtime#85852|
|[264751](https://dev.azure.com/dnceng-public/public/_build/results?buildId=264751)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/264751/logs/527)|dotnet/runtime#85851|
|[264750](https://dev.azure.com/dnceng-public/public/_build/results?buildId=264750)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/264750/logs/525)|dotnet/runtime#85850|
|[264740](https://dev.azure.com/dnceng-public/public/_build/results?buildId=264740)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/264740/logs/535)|dotnet/runtime#85847|
|[264749](https://dev.azure.com/dnceng-public/public/_build/results?buildId=264749)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/264749/logs/534)|dotnet/runtime#85849|
|[264500](https://dev.azure.com/dnceng-public/public/_build/results?buildId=264500)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/264500/logs/788)||
|[264235](https://dev.azure.com/dnceng-public/public/_build/results?buildId=264235)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/264235/logs/662)|dotnet/runtime#85692|
|[264051](https://dev.azure.com/dnceng-public/public/_build/results?buildId=264051)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/264051/logs/770)||
|[263902](https://dev.azure.com/dnceng-public/public/_build/results?buildId=263902)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/263902/logs/525)|dotnet/runtime#85185|
|[263342](https://dev.azure.com/dnceng-public/public/_build/results?buildId=263342)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/263342/logs/753)||
|[262840](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262840)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/262840/logs/768)||
|[261788](https://dev.azure.com/dnceng-public/public/_build/results?buildId=261788)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/261788/logs/1009)|dotnet/runtime#84566|
|[261990](https://dev.azure.com/dnceng-public/public/_build/results?buildId=261990)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/261990/logs/766)||
|[261437](https://dev.azure.com/dnceng-public/public/_build/results?buildId=261437)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/261437/logs/732)||
|[258928](https://dev.azure.com/dnceng-public/public/_build/results?buildId=258928)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/258928/logs/1305)|dotnet/runtime#84566|
|[261188](https://dev.azure.com/dnceng-public/public/_build/results?buildId=261188)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/261188/logs/647)|dotnet/runtime#85692|
|[260534](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260534)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/260534/logs/725)||
|[259956](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259956)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/259956/logs/703)||
|[258971](https://dev.azure.com/dnceng-public/public/_build/results?buildId=258971)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/258971/logs/733)||
|[258590](https://dev.azure.com/dnceng-public/public/_build/results?buildId=258590)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/258590/logs/737)||
|[258289](https://dev.azure.com/dnceng-public/public/_build/results?buildId=258289)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/258289/logs/574)|dotnet/runtime#85601|
|[257874](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257874)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/257874/logs/764)||
|[257815](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257815)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/257815/logs/675)|dotnet/runtime#85504|
|[257694](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257694)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/257694/logs/753)||
|[257380](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257380)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/257380/logs/777)||
|[257197](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257197)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/257197/logs/779)||
|[257000](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257000)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/257000/logs/775)||
|[256625](https://dev.azure.com/dnceng-public/public/_build/results?buildId=256625)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/256625/logs/778)||
|[256353](https://dev.azure.com/dnceng-public/public/_build/results?buildId=256353)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/256353/logs/679)||
|[255903](https://dev.azure.com/dnceng-public/public/_build/results?buildId=255903)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/255903/logs/526)|dotnet/runtime#85458|
|[255744](https://dev.azure.com/dnceng-public/public/_build/results?buildId=255744)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/255744/logs/734)||
|[255582](https://dev.azure.com/dnceng-public/public/_build/results?buildId=255582)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/255582/logs/613)||
|[255331](https://dev.azure.com/dnceng-public/public/_build/results?buildId=255331)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/255331/logs/589)||
|[255110](https://dev.azure.com/dnceng-public/public/_build/results?buildId=255110)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/255110/logs/681)||
|[254950](https://dev.azure.com/dnceng-public/public/_build/results?buildId=254950)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/254950/logs/616)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|3|28|52|

**Comment by steveisok** [comment]
@directhex please take a look.

**Comment by filipnavara** [comment]
I think the particular cbl-mariner image doesn't use the version suffix for `clang` but that should be easy enough to verify by checking the docker image.
