### ISSUE TITLE
`new FileStream(fd,..., isAsync:true)` doesn't appear to be supported on Unix

### ISSUE THREAD

**Issue by wasabii** [dotnet/runtime#85560]
I don't appear to have any way to create a new FileStream from a raw int FD on Linux with async set to true. It's easy enough for me to call open() with O_ASYNC. The next step would be to create a SafeFileHandle, and then hand it to the ctor of FileStream. However, SafeFileHandle's Unix implementation seems to have no way to tell it the underlying FD is async. The Windows version calls into ntdll to actually detect whether the FD is async. The Unix version doesn't have any such call, and only sets IsAsync when it is responsible for calling open().

However, new FileStream(sfh,,,true) validates that IsAsync on the SafeFileHandle is true.

**Comment by Gnbrkm41** [comment]
It appears that you can query the flags set on a given file descriptor using `fcntl` function in `F_GETFL` mode, could we perhaps return the actual value instead of storing whether the file descriptor was opened with one?

**Comment by adamsitnik** [comment]
Hi @wasabii 

`O_ASYNC` does nothing for regular files on Linux. `FileStream` uses plain `read` and `write` sys-calls for pipes and sockets (no epoll), so there would be no gain from using it for these two file types as well.

From https://man7.org/linux/man-pages/man2/open.2.html

> This feature is available only for terminals, pseudoterminals, sockets, and (since Linux 2.6) pipes and FIFOs.

If you are using sockets please use [Socket](https://learn.microsoft.com/en-us/dotnet/api/system.net.sockets.socket?view=net-8.0#asynchronous-mode) type that provides full async support on Linux (via epoll).

In the future we might implement `io_uring` support for `FileStream`. Please follow https://github.com/dotnet/runtime/issues/51985 for updates.

**Comment by wasabii** [comment]
@adamsitnik 

At the OS level that might all be true, however, and I might be not completely accurate here anymore, because I'd have to fire up my tests again, it's been awhile.... I found that FileStream.ReadAsync/WriteAsync and similar methods were unusable unless FileStream thought it was talking to an async handle. They threw.

So, even though FileStream.ReadAsync would technically function on Unix by doing synchronous operations: it refused to do so unless it thought it was opened for async operations. And the only way to create a new FileStream that thought it was capable of doing so, from a FD, was to pass it a SafeFileHandle marked for isAsync.

Ignore O_ASYNC, as I suppose that was somewhat of a red herring for my purposes here. I need a FileStream that is capable of having ReadAsync called on it. And I need to initialize that FileStream from a FD. And there is no option to create a FileStream with isAsync: true, if the SafeFileHandle.IsAsync is false.

**Comment by adamsitnik** [comment]
> FileStream.ReadAsync/WriteAsync and similar methods were unusable unless FileStream thought it was talking to an async handle. They threw.

These methods should always work no matter how you create the `FileStream`.

@wasabii Which .NET version are you using? Could you please provide a repro?
