### ISSUE TITLE
 System.IO.Ports.SerialPort  receive 0x1A   lead to exception

### ISSUE THREAD

**Issue by lee8871** [dotnet/runtime#85567]
### Description

```c#
public System.IO.Ports.SerialPort sp;
int rev = sp.Read(buffer, offset, count);
```
If receiving data is 0x1A. It throw an exception;

### Reproduction Steps

```c#
public System.IO.Ports.SerialPort sp;		
public SerialPortDp() {
	sp = new System.IO.Ports.SerialPort();
	sp.ReadBufferSize = 4096;
	sp.WriteBufferSize = 4096;
	sp.ReadTimeout = 0;
	sp.WriteTimeout = -1;
	sp.DataReceived += Sp_DataReceived;
	sp.ErrorReceived += Sp_ErrorReceived;

}
public override int Read(byte[] buffer, int offset, int count) {
	if (sp.IsOpen==false) {
		return 0;
	}
	sp.BaseStream.ReadTimeout = 0;
	int rev = sp.Read(buffer, offset, count);//throw exception
	countRead(rev);
	return rev;
}	
```

### Expected behavior

It worked well if receiving other byte.

### Actual behavior

System.TimeoutException
  HResult=0x80131505
  Message=The operation has timed out.
  Source=System.IO.Ports
  StackTrace:
   在 System.IO.Ports.SerialStream.Read(Byte[] array, Int32 offset, Int32 count, Int32 timeout)
   在 System.IO.Ports.SerialPort.Read(Byte[] buffer, Int32 offset, Int32 count)
   在 Sl.Duplex.SerialPortDp.Read(Byte[] buffer, Int32 offset, Int32 count) 在 D:\L\Cs\ChholConfig\Duplex\SerialPortDp.cs 中: 第 103 行
   在 Sl.Forms.StreamUI.receiveData(IDuplex p) 在 D:\L\Cs\ChholConfig\CmdTextBox\StreamUI.cs 中: 第 57 行
   在 Sl.Duplex.SerialPortDp.Sp_DataReceived(Object sender, SerialDataReceivedEventArgs e) 在 D:\L\Cs\ChholConfig\Duplex\SerialPortDp.cs 中: 第 95 行
   在 System.IO.Ports.SerialPort.CatchReceivedEvents(Object src, SerialDataReceivedEventArgs e)
   在 System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   在 System.Threading.ThreadPoolWorkQueue.Dispatch()
   在 System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   在 System.Threading.Thread.StartCallback()

**Comment by lee8871** [comment]
I have tried 8.0.0-preview.3.23174.8 and 7.0.0
Under net6.0-windows

**Comment by krwq** [comment]
@lee8871 have you tried setting SerialPort.NewLine with `"\0xa"`? I'm suspecting you have it currently set to `"\0xc\0xa"` which is causing the timeouts since it's not finding `0xc`...
