### ISSUE TITLE
iOS/tvOS simulators ran out of trampolines of type 1

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#85582]
## Build Information
Error log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-85384-merge-d429926282c4447486/System.Text.Json.Tests.Attempt.3/1/console.36f02c66.log?helixlogtype=result
Build error leg or test failing: runtime-ioslikesimulator (Build tvossimulator-x64 Release AllSubsets_Mono)
Pull request: https://github.com/dotnet/runtime/pull/85384

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Ran out of trampolines of type 1 in",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[257450](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257450)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257450&view=ms.vss-test-web.build-test-results-tab&runId=5026378&resultId=185480)|dotnet/runtime#85384|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|1|

**Comment by steveisok** [comment]
@kotlarmilos this has happened from time to time and to remedy, we would bump the defaults in https://github.com/dotnet/runtime/blob/da0aa0cb6944dd49d6c1d1859c4530fe7e38b76f/src/mono/msbuild/apple/build/AppleBuild.targets#L139-L144.  I can't remember what type 1 maps to off the top of my head.
