### ISSUE TITLE
Typo in SafeHandle.cs - Reported by Visual Studio's spell checker

### ISSUE THREAD

**Issue by echoix** [dotnet/runtime#85593]
This is a small isuue that didn't correspond to the bug issue template.
Using the Visual Studio's spell checker marks a warning on other files, including the one implementing `SafeHandle`s. 

In the comments of the `private void InternalRelease(bool disposeOrFinalizeOperation)` method, there is a typo where the word **`providng`** is unkown, and should probably be **`providing`**
https://github.com/dotnet/runtime/blob/80cd72e931db38bbcbd90067cb6d9b8cbf340e7a/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/SafeHandle.cs#LL259C24-L259C24

https://github.com/dotnet/runtime/blob/80cd72e931db38bbcbd90067cb6d9b8cbf340e7a/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/SafeHandle.cs#L259

```diff
             // If we get here we successfully decremented the ref count. Additionally we
             // may have decremented it to zero and set the handle state as closed. In
-            // this case (providng we own the handle) we will call the ReleaseHandle
+            // this case (providing we own the handle) we will call the ReleaseHandle
             // method on the SafeHandle subclass.
             if (performRelease)
             {
                 // Save last error from P/Invoke in case the implementation of ReleaseHandle
                 // trashes it (important because this ReleaseHandle could occur implicitly
                 // as part of unmarshaling another P/Invoke).
                 int lastError = Marshal.GetLastPInvokeError();
                 ReleaseHandle();
                 Marshal.SetLastPInvokeError(lastError);
             }
```

Since the typo is present in the `main` branch and the `release/8.0-preview4`, would a PR be accepted to suggest this change?

**Comment by jkoritzinsky** [comment]
We'd be willing to accept a typo fix for the `main` branch, but not for the Preview 4 branch. The preview branches only get limited changes as we prepare for release.
