### ISSUE TITLE
Blazor WASM using 'en' culture instead of 'en-GB' when using Accept-Language header

### ISSUE THREAD

**Issue by ADringer** [dotnet/runtime#85598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,

I'm using Blazor WASM and have followed the documentation for globalisation using the Accept-Language header at [here](https://learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-7.0&pivots=webassembly#dynamically-set-the-culture-from-the-accept-language-header).

The accept-language header being passed in is `en-GB,en;q=0.9` but when formatting a date it comes out in the American format, not GB format. When getting the current culture it's returning 'en' instead of 'en-GB'.

I have included `<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>` in the client project.

Is en-GB a supported culture OTB?

### Expected Behavior

Blazor WASM app should use en-gb culture as it's the first in the accept-language list.

### .NET Version

7.0.5

**Comment by ilonatommy** [comment]
@ADringer, could you please give us the minimal repro? My attempt to reproduce using the doc + net 7.0.5 resulted in 100% correct behavior. It would be easier if we saw your code. 
![image](https://user-images.githubusercontent.com/32700855/235615985-bee71ce5-eee0-4e0f-93e8-cfd1d8384e79.png)
In the meantime, I am pusing the working version, in case you find it helpful: https://github.com/ilonatommy/Blazor_Issue85598
