### ISSUE TITLE
Blazor - Ternary operator crashes

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/runtime#85597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The commented code below fails 100% of the time.  It is replaced with the expanded `if` statements in subsequent lines.

There is no error message.  The debugger simply stops working.  The method does not finish executing. IDK where it resumes since the debugger just stops.

        
        public void DimensionsChanged(Tuple<List<Dimension<T>>, Dimension<T>, DropZone> args)
        {
            List<Dimension<T>> axisDimensions = null;
            Dimension<T> dim = args.Item2;
            DropZone dropZone = args.Item3;
            List<Dimension<T>> enabledDimensions = Dimensions.Where(x => x.IsEnabled).ToList();

            //if (dropZone == DropZone.Hidden)
            //    axisDimensions = dim.IsRow ?  RowDimensions : ColumnDimensions;
            //else
            //    axisDimensions = dropZone == DropZone.Rows ? RowDimensions : ColumnDimensions;

            if (dropZone == DropZone.Hidden)
            {
                if (dim.IsRow)
                    axisDimensions = RowDimensions;
                else
                    axisDimensions = ColumnDimensions;
            }
            else
            {
                axisDimensions = args.Item1;
            }

            if (dropZone != DropZone.Hidden) 
            {
                bool isRows = dropZone == DropZone.Rows;
                List<Dimension<T>> crossAxisDimensions = null;
                //crossAxisDimensions = isRows ? ColumnDimensions : RowDimensions;

                if (isRows)
                    crossAxisDimensions = ColumnDimensions;
                else
                    crossAxisDimensions = RowDimensions;

### Expected Behavior

Ternary operator should work like a simple `if` statement.

### Steps To Reproduce

Clone [this repo](https://github.com/leaderanalytics?tab=repositories) and [this one](https://github.com/leaderanalytics/LeaderPivot.Blazor).  In the demo project remove the reference to the nuget and and add a reference to the project in the second repo.  Uncomment code as shown above in `LeaderPivot.razor.cs`.  Run the project and drag the blue buttons.

### .NET Version

7.0.203

**Comment by lambdageek** [comment]
@sam-wheat the first link in your issue just goes to a list of repositories.  I assume you meant this one: https://github.com/leaderanalytics/LeaderPivot.BlazorDemo

**Comment by sam-wheat** [comment]
@lambdageek Yes that is correct.

**Comment by lambdageek** [comment]
@sam-wheat I don't understand the repro directions. The ternary code and the pair of `if/else` statements below it don't do the same thing.  Do you want me to rebuild the code like this:

```csharp
        if (dropZone == DropZone.Hidden)
            axisDimensions = dim.IsRow ?  RowDimensions : ColumnDimensions;
        else
            axisDimensions = dropZone == DropZone.Rows ? RowDimensions : ColumnDimensions;

        //if (dropZone == DropZone.Hidden)
        //{
        //    if (dim.IsRow)
        //        axisDimensions = RowDimensions;
        //    else
        //        axisDimensions = ColumnDimensions;
        //}
        //else
        //{
        //    axisDimensions = args.Item1;
        //}
```

or do I need to also comment out the second `if/else`.  Would it be possible for you to fork the LeaderPivot.Blazor repo and make a branch with the code that causes the crash?


Also, does the code only crash when running with the debugger? what if you just launch the demo server without debugging and start dragging the buttons around?

**Comment by sam-wheat** [comment]
@lambdageek  The code you show should demo the problem.  I may have changed it after commenting.  Running without debugging will demo the problem also.

**Comment by lambdageek** [comment]
@sam-wheat I can't repro the issue with .NET 7.0.203

When I make the change as I showed above, and then run the demo with `dotnet run`, and then drag the `Country` button on top of `Year`, the table adds a country column and everything appears to work.

Maybe I'm missing something in order to trigger the issue?

What do you see in the browser's dev tools console?

**Comment by sam-wheat** [comment]
I can't reproduce it now either.  I spent several hours debugging this and during that time I reproduced it every single time.  In fact I could not get my original code to work at all - that is why I committed the change.

A couple things worth noting:

For some reason my breakpoints stopped being visible to VS when using Firefox.  I tried all the usual things - change port, delete bin/obj/.vs/browser history/Ctrl+F5, etc.  I tried changing the browser to Chrome and it did not work either.  Changed the browser to Edge and it works.  I still can no longer use Firefox I have no idea what changed or why.

In the screencap note that attempting to watch `isRows` variable throws an error in VS watch window. isRows is assigned a value and is in scope.  Refreshing the watch window does not work.  I noticed this when I first started debugging the ternary issue.  This screencap was saved today.


The only errors I see in dev tools console occur on startup but do not appear to affect program operation or debugging:

> Failed to load resource: net::ERR_CONNECTION_REFUSED
> Failed to load resource: net::ERR_CONNECTION_REFUSED
![Capture](https://user-images.githubusercontent.com/16885210/235555152-f9464b79-9b79-4f94-a461-ceae8581ef02.PNG)

**Comment by lambdageek** [comment]
@thaystg  Are these issues known?  ^^^.  

1. firefox and chrome debugging not working with a hosted blazorwasm app (edge works)
2. `isRows` variable does not exist in the current context

**Comment by thaystg** [comment]
1) Debugging on Firefox is not supported by VS. To debug on Firefox you need to use Firefox DevTools.
2) There is a chrome version that the debugger was not working, can you please update it or send me the version that you are using?
3) `isRows` is correctly shown if you look at "Locals Tab"?

**Comment by sam-wheat** [comment]
@thaystg  

Hi, I've been using Firefox for months without problem,

![Capture](https://user-images.githubusercontent.com/16885210/235797261-08ee34bf-ab58-4f24-9d2b-1f4b95f305cc.PNG)

`isRows` shows up in Locals Tab however it appears to be obscured by an object that is internal to VS.  



![Capture](https://user-images.githubusercontent.com/16885210/235800194-0a4cc696-1b40-4f6d-9286-d068c0b91506.PNG)


Firefox is v 112.0.2.  It's been working fine up till now.

**Comment by thaystg** [comment]
Oh wait, this is on the server side of the project, right?

**Comment by sam-wheat** [comment]
No - repo is [here](https://github.com/leaderanalytics/LeaderPivot.BlazorDemo).

**Comment by thaystg** [comment]
@joj any idea how he can debug "javascript" files using firefox?
@sam-wheat can you share with me the content of this file after you startup your debug session: C:\Users\[USER_NAME]\AppData\Local\Temp\visualstudio-js-debugger.txt

**Comment by sam-wheat** [comment]
Per your request

[visualstudio-js-debugger.txt](https://github.com/dotnet/runtime/files/11378890/visualstudio-js-debugger.txt)

**Comment by thaystg** [comment]
Did you debug on firefox and then send me the file? I can see that is debugging on Edge, am I wrong?

`{"tag":"dap.receive","timestamp":1683066149969,"metadata":{"connectionId":0,"message":{"type":"request","command":"launch","arguments":{"webRoot":"C:\\Git\\LeaderPivot.BlazorDemo\\LeaderPivot.BlazorDemo.Server","rootPath":"C:\\Git\\LeaderPivot.BlazorDemo\\LeaderPivot.BlazorDemo.Server","__workspaceFolder":"C:\\Git\\LeaderPivot.BlazorDemo\\LeaderPivot.BlazorDemo.Server","runtimeExecutable":"C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe","runtimeArgs":[],"sourceMaps":true,"url":"https://localhost:7205/","trace":{"logFile":"C:\\Users\\sam\\AppData\\Local\\Temp\\visualstudio-js-debugger.txt"},"launchUnelevated":false,"projectGuid":"4a13558e-ee75-4c0b-86e5-7e3788d57940","userDataDir":"C:\\Users\\sam\\AppData\\Local\\Microsoft\\VisualStudio\\17.0_3e5f8e7c\\WebTools\\90107F59_58C3691C","breakOnLoad":true,"pathMapping":{"/_content/LeaderAnalytics.LeaderPivot.Blazor":"C:\\Git\\LeaderPivot.Blazor\\LeaderPivot.Blazor\\wwwroot\\"},"smartStep":true,"continueOnAttach":false,"skipFiles":[],"showAsyncStacks":true,"timeout":60000,"inspectUri":"{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}","__webAssemblyDebugServerPath":"C:\\Users\\sam\\.nuget\\packages\\microsoft.aspnetcore.components.webassembly.devserver\\7.0.5\\Tools\\BlazorDebugProxy\\BrowserDebugHost.dll","__startWebAssemblyDebugServer":false,"cleanUp":"wholeBrowser","name":"Launch the JavaScript PWA Debugger from Visual Studio","type":"pwa-msedge","request":"launch","continueOnDisconnect":true},"seq":2}},"level":0}
`

"runtimeExecutable":"C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"

**Comment by sam-wheat** [comment]
When I tried to debug with Firefox it did not create the file.  
I renamed the file, then started a debugging session with FF set as the browser.  A new file was not created so I sent that one.
Is there something else I can try to create the file?

**Comment by sam-wheat** [comment]
Chrome is working again.  My computer must have been having a bad day.

[visualstudio-js-debugger.txt](https://github.com/dotnet/runtime/files/11378929/visualstudio-js-debugger.txt)

I tried again with FF - the file is not created.

**Comment by joj** [comment]
I've heard of people debugging with Firefox but that's not something we support in the Javascript debugger and to be honest, I don't know how they get it to work with C# either. I understand Firefox does have a compatibility later for V8 debugging, but again, I don't know how that works. I'm not recognizing that browser selection dialog, either. Where is that coming from?

**Comment by sam-wheat** [comment]
I don't recall having to do anything special to make it work.  I used to use Brave browser and that worked well also.

![image](https://user-images.githubusercontent.com/16885210/235822289-f9c593ed-64b9-4b56-8871-2b83f67e9a22.png)

**Comment by thaystg** [comment]
By worked well do you mean pausing on breakpoints on razor.cs files right?

**Comment by sam-wheat** [comment]
Yes

**Comment by lewing** [comment]
this appears to be resolved
