### ISSUE TITLE
OSX build error: Removing global symbols from a final linked no longer supported

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#85600]
Failures in libraries tests in `/azp run runtime-extra-platforms` run:

`/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip(0,0): error : (NETCORE_ENGINEERING_TELEMETRY=Build) removing global symbols from a final linked no longer supported.  Use -exported_symbols_list at link time when building: /Users/runner/work/1/s/artifacts/bin/ComInterfaceGenerator.Tests/Release/net8.0/native/ComInterfaceGenerator.Tests`
 
Log: https://dev.azure.com/dnceng-public/public/_build/results?buildId=257857&view=logs&jobId=1b7517dc-3493-5614-db19-9039ca700e8e&j=d44cf75c-a475-5ab8-9e3a-15ab166e7134&t=40b10810-f350-5b11-df15-9a9e3c3e48e8

**Comment by jkotas** [comment]
@ivanpovazan This seems to be introduced or related to https://github.com/dotnet/runtime/pull/85293 . Could you please take a look?

**Comment by jkotas** [comment]
Testing revert in https://github.com/dotnet/runtime/pull/85601

**Comment by lambdageek** [comment]
FYI @SamMonoRT @kotlarmilos

**Comment by jkotas** [comment]
> Testing revert in https://github.com/dotnet/runtime/pull/85601

I have confirmed that this was introduced by https://github.com/dotnet/runtime/pull/https://github.com/dotnet/runtime/pull/85293 . I think we should revert the change unless this is fixed soon.

**Comment by SamMonoRT** [comment]
> > Testing revert in #85601
> 
> I have confirmed that this was introduced by #85293 . I think we should revert the change unless this is fixed soon.

@ivanpovazan is out, and I'm out sick as well. Please merge the revert PR to get CI green again. We can work on right fix once he is back later next week.
