### ISSUE TITLE
Question: Does System.IO.Hashing.XxHash3 uses the fastest instruction set by default if available?

### ISSUE THREAD

**Issue by jerrywoo96** [dotnet/runtime#85614]
Hi,

https://github.com/Cyan4973/xxHash/wiki/Performance-comparison

Looking at the performance table for XxHash3, SSE, AVX2 and AVX512 can be used to calculate file hashes. Does it automatically use the fastest instruction set by default if the hardware supports it? And fallback to using the next fastest instruction set if the fastest instruction set is not supported? 

Thanks.

**Comment by stephentoub** [comment]
It doesn't currently support AVX512. Other than that, yes.
