### ISSUE TITLE
Assertion failed '!"Unknown operator for loop increment"' during 'Optimize Valnum CSEs'

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#85631]
Repro: https://gist.github.com/kunalspathak/0bb5980bc49f625bcd7e2e02c17e1e98

```
Environment:

set COMPlus_JitOptRepeat=*
set COMPlus_JitAggressiveInlining=1
set COMPlus_JitNoMemoryBarriers=1
set COMPlus_TailCallLoopOpt=0
set COMPlus_JitEnableNoWayAssert=1
set COMPlus_TC_OnStackReplacement=1
set COMPlus_AltJitName=clrjit_universal_arm64_x64.dll
set COMPlus_AltJit=TryRunSingle

Out of memory.
Assert failure(PID 9428 [0x000024d4], Thread: 19772 [0x4d3c]): Assertion failed '!"Unknown operator for loop increment"' in 'System.Number+Grisu3:TryRunSingle(float,int,byref):bool' during 'Optimize Valnum CSEs' (IL size 174; hash 0xf28546e5; Tier1)
    File: E:\git\runtime\src\coreclr\jit\compiler.hpp Line: 3209
    Image: e:\git\runtime\artifacts\tests\coreclr\windows.x64.Checked\tests\Core_Root\CoreRun.exe
```

**Comment by jakobbotsch** [comment]
Going to put this in future given the non-standard environment variables. IMO if we want to make JitOptRepeat work we should start out with making it run with our test suite.

**Comment by kunalspathak** [comment]
> Going to put this in future given the non-standard environment variables

I agree. I think I will take this out from Antigen (which I thought I did once).

**Comment by kunalspathak** [comment]
> think I will take this out from Antigen (which I thought I did once).

Done. https://github.com/kunalspathak/Antigen/commit/0d70a3854950d9436599bbfdc81b2b763bfc6508

**Comment by BruceForstall** [comment]
This doesn't repro for me. Possibly fixed by https://github.com/dotnet/runtime/pull/94250 and related.
