### ISSUE TITLE
[API Proposal]: Enumerable.Chunk (Array)

### ISSUE THREAD

**Issue by NetDefender** [dotnet/runtime#85653]
### Background and motivation

When calling external APIs that return a full, non-paginated result set, using the **Chunk** method in that result is very useful for processing it in pieces.
So when calling the **Chunk** method on a materialized or full array, using Array.Copy improves performance over GetEnumerator() and manual setting the elements in the target array.

The same could be done to other collection types like **List&lt;T&gt;**(reading the underlying _items field).

### API Proposal

```csharp
namespace System.Linq;

public static partial class Enumerable
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static IEnumerable<TSource[]> Chunk<TSource>(this TSource[] array, int size)
    {
        ArgumentNullException.ThrowIfNull(array);
        ArgumentOutOfRangeException.ThrowIfLessThan(size, 1);
        return ArrayChunkIterator(array, size);
    }

    private static IEnumerable<TSource[]> ArrayChunkIterator<TSource>(TSource[] array, int size)
    {
        for (int start = 0; start < array.Length; start += size)
        {
            int end = start + size;
            if (end >= array.Length)
            {
                end = array.Length;
            }
            TSource[] chunk = new TSource[end - start];
            Array.Copy(array, start, chunk, 0, chunk.Length);
            yield return chunk;
        }
    }

    public static IEnumerable<TSource[]> Chunk<TSource>(this IEnumerable<TSource> source, int size)
    {
        ArgumentNullException.ThrowIfNull(source);
        ArgumentOutOfRangeException.ThrowIfLessThan(size, 1);
        if (source is TSource[] array)
        {
            return ArrayChunkIterator(array, size);
        }
        ...
    }
}



```

Performance results:

``` ini

BenchmarkDotNet=v0.13.5, OS=Windows 10 (10.0.19044.2846/21H2/November2021Update)
AMD Ryzen 7 1700, 1 CPU, 16 logical and 8 physical cores
.NET SDK=8.0.100-preview.3.23178.7
  [Host]     : .NET 8.0.0 (8.0.23.17408), X64 RyuJIT AVX2
  DefaultJob : .NET 8.0.0 (8.0.23.17408), X64 RyuJIT AVX2


```
|     Method | ARRAY_SIZE | CHUNK_SIZE |      Mean |     Error |    StdDev | Ratio |    Gen0 | Allocated | Alloc Ratio |
|----------- |----------- |----------- |----------:|----------:|----------:|------:|--------:|----------:|------------:|
|  Default Chunk |      10000 |         57 | 62.117 μs | 0.6543 μs | 0.6120 μs |  1.00 | 10.8643 |  44.55 KB |        1.00 |
| Array Chunk Overload |      10000 |         57 |  5.519 μs | 0.1078 μs | 0.1107 μs |  0.09 | 10.7574 |  43.94 KB |        0.99 |

### API Usage

```csharp
using System.Net.Http;
using System.Net.Http.Json;

public record class Signal(int Id, decimal Price, ...);

HttpClient client = new HttpClient();
Signal[] dailySignals = await client.GetFromJsonAsync<Signal[]>("/api/daily/signals");

foreach (Signal[] signals in dailySignals.Chunk(10))
{
    BatchSave(signals);
}
```

### Alternative Designs

Actual implementation of chunk supports Arrays and List&lt;T&gt; but is not optimal.

### Risks

If someone is using the **Chunk** method over an array, the new overload will take place and will improve performance without having to touch anything

**Comment by NetDefender** [comment]
> The implementation, yours and the original one, still creates output arrays for the yield. 

Yes, It is an extension to the current api.

If one doesn't want to create an array, one could complement it with another method that returns an Enumerable from Memory, but I think this should be thought more deeply.
Something like this:

```csharp
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static IEnumerable<ReadOnlyMemory<TSource>> MemoryChunk<TSource>(this TSource[] array, int size)
    {
        ArgumentNullException.ThrowIfNull(array);
        ArgumentOutOfRangeException.ThrowIfLessThan(size, 1);
        return MemoryChunkIterator(array, size);
    }

    private static IEnumerable<ReadOnlyMemory<TSource>> MemoryChunkIterator<TSource>(TSource[] array, int size)
    {
        ReadOnlyMemory<TSource> memory = array;
        for (int start = 0; start < array.Length; start += size)
        {
            int end = start + size;
            if (end >= array.Length)
            {
                end = array.Length;
            }
            yield return memory[start..end];
        }
    } 
```



>Do you think, that the overhead of the Enumerator, shows up in any Benchmark?

Thanks, I'll clarify in the initial API statement what I meant about GetEnumerator().

Out of curiosity I have done a Benchmark to see if i can see any difference in using IEnumerable&lt;T&gt;.GetEnumerator() and its about x10 slower than the for loop and allocates more memory.

```csharp
    [Benchmark]
    public int ArrayIteration()
    {
        int result = 0;
        for (int i = 0; i < _elementsArray.Length; i++)
        {
            result = _elementsArray[i];
        }
        return result;
    }

    [Benchmark(Baseline = true)]
    public int EnumeratorIteration()
    {
        int result = 0;
        using IEnumerator<int> enuma = ((IEnumerable<int>)_elementsArray).GetEnumerator();
        while (enuma.MoveNext())
        {
            result = enuma.Current;
        }
        return result;
    }
```

``` ini

BenchmarkDotNet=v0.13.5, OS=Windows 10 (10.0.19044.2846/21H2/November2021Update)
AMD Ryzen 7 1700, 1 CPU, 16 logical and 8 physical cores
.NET SDK=8.0.100-preview.3.23178.7
  [Host]     : .NET 8.0.0 (8.0.23.17408), X64 RyuJIT AVX2
  DefaultJob : .NET 8.0.0 (8.0.23.17408), X64 RyuJIT AVX2


```
|              Method | ARRAY_SIZE | CHUNK_SIZE |      Mean |     Error |    StdDev | Ratio | Allocated | Alloc Ratio |
|-------------------- |----------- |----------- |----------:|----------:|----------:|------:|----------:|------------:|
|      ArrayIteration |      10000 |         57 |  4.641 μs | 0.0510 μs | 0.0477 μs |  0.10 |         - |        0.00 |
| EnumeratorIteration |      10000 |         57 | 45.334 μs | 0.4599 μs | 0.3840 μs |  1.00 |      32 B |        1.00 |

**Comment by viceroypenguin** [comment]
@NetDefender You can check out `.Batch()` in [SuperLinq](/viceroypenguin/SuperLinq) (see code [here](https://github.com/viceroypenguin/SuperLinq/blob/master/Source/SuperLinq/Batch.Buffered.cs) and [here](https://github.com/viceroypenguin/SuperLinq/blob/master/Source/SuperLinq/Batch.Buffered.cs)). It doesn't do the `Array.Copy`, but it does have several similar performance enhancements.

**Comment by stephentoub** [comment]
As @eiriktsarpalis stated, we're not going to add array-based overloads. We'd accept a PR that special-cased array and list if an appropriate case can be made that the extra code and checks are worthwhile, eg real examples where Chunk is being used on a path where the improved throughput matters. Thanks.
