### ISSUE TITLE
Reload configuration not work for named options add with BindConfiguration extension method.

### ISSUE THREAD

**Issue by McMlok** [dotnet/runtime#85665]
### Description

Hello,

I want to reload a JSON configuration from a file after the file changed. I'm using the IOptionsMonitor and  the OnChnage event is fired but when I'm using named options OnChnage is always fired for DefaultOptionName (""). I register the options class to DI container with BindConfiguration extension method. If I use Bind extension method it works.

### Reproduction Steps

I made a [repro ](https://github.com/McMlok/NamedOptionsReloadTest)with working and not working code how to add options to the container.

working code
```csharp
services.AddOptions<ConsoleHostOptions>("Test").Bind(hostContext.Configuration.GetSection("Config:Test"));
```

not working code

```csharp
services.AddOptions<ConsoleHostOptions>("Test").BindConfiguration("Config:Test");
```

### Expected behavior

When a change in an underlying file occurred OnChnage event is fired for named options with the correct options class and the correct name.

### Actual behavior

When a change occurred the change event is fired but for the CurrentValue option class with "" value in arg2 event parameter (option name).

### Known Workarounds

Manually register IOptionsChangeTokenSource<> with correct name

```csharp
services.AddSingleton<IOptionsChangeTokenSource<ConsoleHostOptions>>(new ConfigurationChangeTokenSource<ConsoleHostOptions>("Test", hostContext.Configuration));
```

### Configuration

tested on .NET 6 (6.0.408), .NET 7 (7.0.203) on Windows 10 x64 22H2

**Comment by pinkfloydx33** [comment]
I can confirm this behavior as well. I meant to report the issue a few weeks ago but forgot all about it. Happens on NET7 with latest 7.0.x bits

**Comment by McMlok** [comment]
The problem is in [OptionsBuilderConfigurationExtensions](https://github.com/dotnet/runtime/blob/32a16d039dca69cae153a8e6905f697b8035c39d/src/libraries/Microsoft.Extensions.Options.ConfigurationExtensions/src/OptionsBuilderConfigurationExtensions.cs#L81)

It registers a ConfigurationChangeTokenSource without respecting the option name.
```csharp
optionsBuilder.Services.AddSingleton<IOptionsChangeTokenSource<TOptions>, ConfigurationChangeTokenSource<TOptions>>();
```

I suggest it should be something like

```csharp
services.AddSingleton<IOptionsChangeTokenSource<ConsoleHostOptions>, ConfigurationChangeTokenSource<TOptions>>(
  sp =>
      {
        return new ConfigurationChangeTokenSource<TOptions>(optionsBuilder.Name, sp.GetRequiredService<IConfiguration>());
});
```

I did in my project extension to register correct IOptionsChangeTokenSource, it results in multiple fired events about change but I can live with it.

```csharp
public static class OptionsBuilderExtensions
{
  public static OptionsBuilder<TOptions> RegisterChangeTokenSource<TOptions>(this OptionsBuilder<TOptions> optionsBuilder)
    where TOptions : class
  {
    optionsBuilder.Services.AddSingleton<IOptionsChangeTokenSource<TOptions>, ConfigurationChangeTokenSource<TOptions>>(
      sp =>
      {
        return new ConfigurationChangeTokenSource<TOptions>(optionsBuilder.Name, sp.GetRequiredService<IConfiguration>());
      });
    return optionsBuilder;
  }
}
```

**Comment by Le-Merle** [comment]
The source of the issue is [this PR discussion](https://github.com/dotnet/runtime/pull/46740#discussion_r619083463), where it looks like the original implementation worked, but the loss of support for named options went unnoticed in the reworked version.

In our case, we have `IValidateOptions` setup and the options is only ever configured with the name, leading to an empty option being generated which fails validation and throws an exception whenever someone updates the configuration. This is annoying since we're using Azure App Configuration, so anyone updating a flag in the Feature Manager triggers the issue.
