### ISSUE TITLE
[wasi] Cleanly delineate runtime, and application arguments

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#85674]
Based on @pavelsavara's suggestion - https://github.com/dotnet/runtime/pull/85617#discussion_r1182595694 

Something like `dotnet run <host args> -- <mono args> -- <application args>` where ` -- ` is the separator.

**Comment by pavelsavara** [comment]
Perhaps there should be pass-thru argument like `--host:xxx=yyy` and `--runtime:aaa=bbb` before application ` -- ` ? As an alternative to multiple ` -- `.

**Comment by lewing** [comment]
What is left here?

**Comment by radical** [comment]
Closing as duplicate of https://github.com/dotnet/runtime/issues/88760 .
