### ISSUE TITLE
Failed to load libcoreclr.so on Raspberry Pi Zero 2W when running C# program using .NET Core Debugger (vsdbg)

### ISSUE THREAD

**Issue by aardrasystems** [dotnet/runtime#85680]
I am trying to set up my Raspberry Pi Zero 2W to run C# programs, following the instructions provided in the guide "Create RaspberryPi dotNET Core C# IoT Applications" on GitHub.

I have used Windows Subsystem for Linux (WSL) to create a project in Visual Studio Code, and I have followed the example to create the launch and task files. However, when I try to start the debugger, I receive the following error message:

    Starting: "/usr/bin/ssh" djosh@raspberrypi "~/vsdbg/vsdbg --interpreter=vscode"
    ------------------------------------------------------------------- You may only use the Microsoft .NET Core Debugger (vsdbg) with Visual Studio Code, Visual Studio or Visual Studio for Mac software to help you develop and test your applications. -------------------------------------------------------------------
    Failed to load /home/djosh/dotnet.core.iot.csharp/libcoreclr.so, error: /home/djosh/dotnet.core.iot.csharp/libcoreclr.so: wrong ELF class: ELFCLASS32
    The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
    The program '[11552] dotnet.core.iot.csharp' has exited with code 1 (0x1)'

I am seeking help to resolve this issue so that I can successfully run C# programs on my Raspberry Pi Zero 2W. Despite running on the 64-bit PI OS, I suspect that the ELF Class32 is causing the problem.

I have attempted to troubleshoot this issue on my own, but being new to C# programming, I am unsure how to proceed. Could someone please provide me with guidance on how to resolve this issue and get C# running on my Raspberry Pi Zero 2W? The tutorial that I am following can be found at the following link: https://github.com/gloveboxes/Create-RaspberryPi-dotNET-Core-C-Sharp-IoT-Applications.

**Comment by hoyosjs** [comment]
@aardrasystems when debugging, are you selecting ARM64ReleasePublish? from this dropdown:

<img width="264" alt="image" src="https://user-images.githubusercontent.com/19413848/235789547-17e175ba-b26e-4406-b104-42248bcbf6e2.png">

**Comment by aardrasystems** [comment]
@hoyosjs Yes I am,can it be anything related to ARM used on Pi 2W zero even if the OS is 64-bit.

**Comment by hoyosjs** [comment]
What happens if you SSH into the pi and run `~/vsdbg/vsdbg --interpreter=vscode` as well as `file ~/vsdbg/vsdbg`? What bitness are you trying to run?

**Comment by janvorli** [comment]
Can you also please run
```
file /home/djosh/dotnet.core.iot.csharp/libcoreclr.so
```
and share the output? It would detect and dump details on the shared library binary format.

**Comment by aardrasystems** [comment]
> What happens if you SSH into the pi and run `~/vsdbg/vsdbg --interpreter=vscode` as well as `file ~/vsdbg/vsdbg`? What bitness are you trying to run?

When I type file` ~/vsdbg/vsdbg` I get the following output:

```
djosh@raspberrypi:~ $ file ~/vsdbg/vsdbg
/home/djosh/vsdbg/vsdbg: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=6f277326f6d5184f0773feea917d8f3ff2f61c14, with debug_info, not stripped
```

When I type` ~/vsdbg/vsdbg --interpreter=vscode` Nothing happens, it is as if the debugger is waiting for somthing

**Comment by aardrasystems** [comment]
> Can you also please run
> 
> ```
> file /home/djosh/dotnet.core.iot.csharp/libcoreclr.so
> ```
> 
> and share the output? It would detect and dump details on the shared library binary format.

@janvorli 

I get the following output:


```
djosh@raspberrypi:~ $ file /home/djosh/dotnet.core.iot.csharp/libcoreclr.so
/home/djosh/dotnet.core.iot.csharp/libcoreclr.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=5dd8b43f95dce7160d8d20c736bac25d53bee22e, stripped
```

**Comment by aardrasystems** [comment]
@janvorli Do you mean the installed debugger is ARM and not arm64? So I need to uninstall the debugger and install the ARM64 version?

**Comment by janvorli** [comment]
No, I mean that the native part of the .NET runtime (libcoreclr.so) is arm32.

**Comment by aardrasystems** [comment]
@janvorli  So, What must I do to correct this?

**Comment by janvorli** [comment]
I wonder if the problem could be related to the fact that both the arm and arm64 publish in the instructions use `./bin/linux-arm/publish` directory. I would try to modify the paths to use `linux-arm64` instead of `linux-arm`. It is there at four places below.

```json
        {
            "label": "ARM64DebugPublish",
            "command": "sh",
            "type": "shell",
            "problemMatcher": "$msCompile",
            "args": [
                "-c",
                "\"dotnet publish -r linux-arm64 --self-contained -c Debug -o ./bin/linux-arm/publish ./${workspaceFolderBasename}.csproj && rsync -rvuz ./bin/linux-arm/publish/ user@host:~/${workspaceFolderBasename}\"",
            ]
        },
        {
            "label": "ARM64ReleasePublish",
            "command": "sh",
            "type": "shell",
            "problemMatcher": "$msCompile",
            "args": [
                "-c",
                "\"dotnet publish -r linux-arm64 --self-contained -c Release -o ./bin/linux-arm/publish ./${workspaceFolderBasename}.csproj && rsync -rvuz ./bin/linux-arm/publish/ user@host:~/${workspaceFolderBasename}\"",
            ]
        }
```

**Comment by aardrasystems** [comment]
@janvorli but when we invoke dubgger we choose from the list, and I am selecting arm64 version

**Comment by aardrasystems** [comment]
> I wonder if the problem could be related to the fact that both the arm and arm64 publish in the instructions use `./bin/linux-arm/publish` directory. I would try to modify the paths to use `linux-arm64` instead of `linux-arm`. It is there at four places below.
> 
> ```json
>         {
>             "label": "ARM64DebugPublish",
>             "command": "sh",
>             "type": "shell",
>             "problemMatcher": "$msCompile",
>             "args": [
>                 "-c",
>                 "\"dotnet publish -r linux-arm64 --self-contained -c Debug -o ./bin/linux-arm/publish ./${workspaceFolderBasename}.csproj && rsync -rvuz ./bin/linux-arm/publish/ user@host:~/${workspaceFolderBasename}\"",
>             ]
>         },
>         {
>             "label": "ARM64ReleasePublish",
>             "command": "sh",
>             "type": "shell",
>             "problemMatcher": "$msCompile",
>             "args": [
>                 "-c",
>                 "\"dotnet publish -r linux-arm64 --self-contained -c Release -o ./bin/linux-arm/publish ./${workspaceFolderBasename}.csproj && rsync -rvuz ./bin/linux-arm/publish/ user@host:~/${workspaceFolderBasename}\"",
>             ]
>         }
> ```

I will give this a try

**Comment by hoyosjs** [comment]
@aardrasystems can you change this to:

```json
{
            "label": "ARM64DebugPublish",
            "command": "sh",
            "type": "shell",
            "problemMatcher": "$msCompile",
            "args": [
                "-c",
                "\"dotnet publish -r linux-arm64 --self-contained -c Debug -o ./bin/linux-arm64/publish ./${workspaceFolderBasename}.csproj && rsync -rvuz ./bin/linux-arm64/publish/ user@host:~/${workspaceFolderBasename}\"",
            ]
        },
        {
            "label": "ARM64ReleasePublish",
            "command": "sh",
            "type": "shell",
            "problemMatcher": "$msCompile",
            "args": [
                "-c",
                "\"dotnet publish -r linux-arm64 --self-contained -c Release -o ./bin/linux-arm64/publish ./${workspaceFolderBasename}.csproj && rsync -rvuz ./bin/linux-arm64/publish/ user@host:~/${workspaceFolderBasename}\"",
            ]
        }
```

I doubt it, but maybe the incremental part of the build might be conflicting and not rebuilding.

**Comment by aardrasystems** [comment]
I am now getting the following error:

```
Starting: "/usr/bin/ssh" djosh@raspberrypi "~/vsdbg/vsdbg --interpreter=vscode"
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
Failed to load /home/djosh/dotnet.core.iot.csharp/libcoreclr.so, error: /home/djosh/dotnet.core.iot.csharp/libcoreclr.so: wrong ELF class: ELFCLASS32
The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[86732] dotnet.core.iot.csharp' has exited with code 1 (0x1).
```

**Comment by aardrasystems** [comment]
Sorry, I got it working. I deleted the generated folder on Pi and it seems to be working now.
