### ISSUE TITLE
JIT: inefficient multidimensional array access vis Jit32 (and in general)

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#8569]
RyuJit fails to optimize multidimensional array indices and misses some cases that Jit32 is able to optimize. In the following code example,
```C#
class M
{
    public static int Example(int[,] a, int b)
    {
        int r = 0;
        for (int i = 0; i < a.GetLength(1); i++)
        {
            r += a[b, i] + a[b, i];
        }
        return r;
    }

    public static int Main()
    {
        int[,] a = new int[10,10];
        a[3,3] = 3;
        a[3,7] = 7;
        int r = Example(a, 3);
        return r == 20 ? 100 : 0;
    }
}
```
Jit32 is able to CSE the addressing done in the `a[b,i]` references in `Example` (though it does not CSE the array fetch itself). RyuJit does not CSE anything in the loop.

Neither jit recognizes `a.GetLength` as being a loop invariant, or that the initial bounds check `r[b, ]` is likewise a loop invariant, or inline and decompose `GetLength` despite inlining the very similar bounds check and element addressing logic. Neither jit is able to optimize away the bounds checks in `Main` where the array size and indices are known.

category:cq
theme:md-arrays
skill-level:expert
cost:large

**Comment by BruceForstall** [comment]
This is addressed in https://github.com/dotnet/runtime/pull/70271. There are follow-up items there to continue to improve MD array performance.
