### ISSUE TITLE
Perf is not working for JITed code in DotNet (Mono Runtime)

### ISSUE THREAD

**Issue by shivanirmishra** [dotnet/runtime#85706]
During the profiling analysis of DotNet benchmarks, it was observed that the perf report is not working for annotating the symbols. A deeper analysis showed that there is an environmental variable that can help to create a .map file and a .dump file in /tmp/ folder.
So, we followed the steps below:

```
MONO_ENV_OPTIONS="--jitmap --jitdump" perf record
perf inject -j -i perf.data -o perf.jit.data
perf report -i perf.jit.data
```
Then we observed that we are able to read the .map file, but the .dump file is not working.
Linux perf tools will expect symbols for code executed from unknown memory regions at /tmp/perf-.map.
So it will read that file to do symbol resolution and show the data. And due to this, we are able to see the functions in the profile but not the annotations inside that.

Mono is responsible for creating a mmap entry in perf.data file which actually lets perf know about the .dump file but we don’t see any mmap call with the .dump file so that means the mmap call of mono is not working as expected.

> We are getting the below error after getting into any JITed function after the perf report:
> objdump: /tmp/perf-337604.map: File format not recognized

**Comment by lambdageek** [comment]
This is the same issue as https://github.com/dotnet/performance/issues/2988, right @shivanirmishra ?

**Comment by fanyang-mono** [comment]
Closing this issue, as the related issue has been fixed. Refer to https://github.com/dotnet/runtime/pull/85107#issuecomment-1623116339
