### ISSUE TITLE
MAUI Blazor App fails on load for adhoc release 

### ISSUE THREAD

**Issue by GreatIdeaz** [dotnet/runtime#85722]
So I have a MAUI Blazor build that runs fine on iOS device in DEVELOPMENT.

I successfully went through the steps here (https://learn.microsoft.com/en-us/dotnet/maui/ios/deployment/publish-ad-hoc?view=net-maui-7.0&tabs=vsmac) to create an ad-hoc release and pushed it to the MS App Center for distribution.

I downloaded it onto the same device I was successfully using for development. I deleted the DEVELOPMENT version of the app before I downloaded the ad hoc release version for testing.

The ad-hoc release version of application installed without flagging any errors.

When starting the application it begins to load the MAUI Blazor application. I see the loading animation start. It never get past zero percent and I see the error bar at the bottom with the Reload link.

I'm using the latest stable VS for MAC to build, test and deploy.

**Comment by GreatIdeaz** [comment]
Interestingly, if you follow all of the instructions except that you chose the DEBUG instead of RELEASE on the step Publish the App, then the application will open correctly when distributed to the device and it is a smaller download (20Mb instead of 30Mb)

Looks like the issue is somewhere in the Release build process? Possibly the LLVM linker?

Anybody else seeing this issue or have a better work around?

**Comment by lewing** [comment]
@marek-safar I'm not sure this is wasm related?

**Comment by kotlarmilos** [comment]
@GreatIdeaz Thank you for reporting the issue. Could you please provide a failure log (if available) to help identify whether the issue is related to Mono or Xamarin?

/cc: @jonathanpeppers @SamMonoRT

**Comment by jonathanpeppers** [comment]
[`adb logcat`](https://docs.microsoft.com/xamarin/android/deploy-test/debugging/android-debug-log) output would say what the problem is.

Also turn on additional logging:
```
# enable Mono logging
adb shell setprop debug.mono.log default,assembly,mono_log_level=debug,mono_log_mask=all
# clear the log
adb logcat -c
# cause the crash, launch the app, etc.
# save the log
adb logcat -d > log.txt
```
Share `log.txt` here.
