### ISSUE TITLE
PipeReader.CopyToAsync(Stream) sometimes does a zero length write

### ISSUE THREAD

**Issue by Tratcher** [dotnet/runtime#85733]
### Description

PipeReader.CopyToAsync(Stream) copies data from the pipe into the given Stream. However, under some circumstances it will call Stream.WriteAsync with a zero length buffer. This can be a problem if the Stream is only expecting a certain amount of data before automatically closing, such as an HTTP Content-Length response (HttpSys server), causing an ObjectDisposedException.

### Reproduction Steps

```c#
using System.Buffers;
using System.IO.Pipelines;

var pipe = new Pipe();
// await pipe.Writer.WriteAsync(new byte[100]); // Optional

var copyTask = pipe.Reader.CopyToAsync(new FakeStream());

pipe.Writer.Write(Array.Empty<byte>());
pipe.Writer.Complete();
await copyTask;

class FakeStream : Stream
{
    public override bool CanRead => false;

    public override bool CanSeek => false;

    public override bool CanWrite => true;

    public override long Length => throw new NotImplementedException();

    public override long Position { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }

    public override void Flush() { }

    public override int Read(byte[] buffer, int offset, int count) => throw new NotImplementedException();

    public override long Seek(long offset, SeekOrigin origin) => throw new NotImplementedException();

    public override void SetLength(long value) => throw new NotImplementedException();

    public override void Write(byte[] buffer, int offset, int count) => throw new NotImplementedException();

    public override ValueTask WriteAsync(ReadOnlyMemory<byte> buffer, CancellationToken cancellationToken = default)
    {
        Console.WriteLine("Writing: " + buffer.Length);
        return default;
    }
}
```

### Expected behavior

Stream.WriteAsync should not be called if the buffer length is 0.

### Actual behavior

Stream.WriteAsync may be called with a buffer length of 0.

### Configuration

.NET 6, 7.

### Other information

https://github.com/dotnet/runtime/blob/8d35268c39cbc21c595265c51260518316032497/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/PipeReader.cs#L249-L251

TryGet is returning true with a zero length buffer.

**Comment by stephentoub** [comment]
> This can be a problem if the Stream is only expecting a certain amount of data before automatically closing

I'm not following this part.  Why would calling it with 0 bytes be a problem for this?

**Comment by Tratcher** [comment]
A Content-Length response marks the stream as disposed after sending the expected number of bytes. Future writes fail with ODE.

**Comment by mgravell** [comment]
I'm happy to submit fixes for both; presumably the pipe scenario here is "the pipe is has been fully drained when it is marked complete, so the final "completed" read is empty"
