### ISSUE TITLE
Publishing NativeAOT fails on Windows if $env:VSINSTALLDIR doesn't have a trailing slash

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#85737]
### Description

When the `VSINSTALLDIR` environment variable is set without a trailing slash, `PublishAot=true` no longer works on Windows.

### Reproduction Steps

In a fresh powershell command prompt:

1. `dotnet new console --aot`
2. `$env:VSINSTALLDIR=$(. "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -prerelease -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -version "[16,18)" -property installationPath)`
3. `dotnet publish`

### Expected behavior

Publish should succeed.

### Actual behavior

```
MSBuild version 17.7.0-preview-23251-02+59879b095 for .NET
  Determining projects to restore...
  Restored C:\DotNetTest\TestTrailingSlash\TestTrailingSlash.csproj (in 235 ms).
C:\dotnet\sdk\8.0.100-preview.5.23253.1\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(287,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [C:\DotNetTest\TestTrailingSlash\TestTrailingSlash.csproj]
  TestTrailingSlash -> C:\DotNetTest\TestTrailingSlash\bin\Release\net8.0\win-x64\TestTrailingSlash.dll
  INFO: Could not find files for the given pattern(s).
C:\Users\eerhardt\.nuget\packages\microsoft.dotnet.ilcompiler\8.0.0-preview.5.23252.2\build\Microsoft.NETCore.Native.Windows.targets(122,5): error : Platform linker not found. To fix this problem, download and install Visual Studio 2022 from http://visualstudio.com. Make sure to install the Desktop Development for C++ workload. For ARM64 development also install C++ ARM64 build tools. [C:\DotNetTest\TestTrailingSlash\TestTrailingSlash.csproj]
```

### Regression?

No

### Known Workarounds

Ensure a trailing slash is set on `$env:VSINSTALLDIR` before publishing.

### Configuration

.NET 8. Windows x64. 

### Other information

When `$env:VSINSTALLDIR` doesn't have a trailing slash, it appears that `vcvarsall.bat` isn't setting all the `$PATH` variables that NativeAOT needs. See the code here:

https://github.com/dotnet/runtime/blob/caaab8a30583b6936f1f33b1e1046fab5b7da83c/src/coreclr/nativeaot/BuildIntegration/findvcvarsall.bat#L37-L42

cc @agocke @MichalStrehovsky

**Comment by agocke** [comment]
> When $env:VSINSTALLDIR doesn't have a trailing slash, it appears that vcvarsall.bat isn't setting all the $PATH variables that NativeAOT needs. See the code here:

Not quite sure what this means, that code looks like we're just calling `where link`. Does this mean that `where` depends on the trailing slash?

**Comment by eerhardt** [comment]
> Does this mean that where depends on the trailing slash?

It doesn't. It means that the path to VS's C++ tooling isn't getting added to the `$env:PATH` after calling `vcvarsall.bat`. That's why `where` can't find `link`.

**Comment by jkotas** [comment]
There are many ways you can confuse `vcvarsall.bat` by setting env variables that it operates on. Missing slash in `VSINSTALLDIR` is just a tip of iceberg.

BTW: We have IlcUseEnvironmentalTools property that you can set to suppress our detection using vcvarsall and take over the responsibility for setting the build environment (ie making sure that a good link.exe is available on the path). It can be used in build environments like razzle where the build toolchain comes as part of the enlistment.

**Comment by jkotas** [comment]
Fixed by https://github.com/dotnet/arcade/pull/13406

**Comment by eerhardt** [comment]
> Fixed by [dotnet/arcade#13406](https://github.com/dotnet/arcade/pull/13406)

Do we want to do something in the product in case customers do the repro steps themselves in their own build scripts (i.e. not using arcade)?

**Comment by eerhardt** [comment]
You could imagine both `vswhere` and `vsvarsall.bat` getting fixed here.

1. `vswhere` should return the installationPath with a trailing slash.
2. `vsvarsall.bat` should still work even if `$env:VSINSTALLDIR` doesn't have a trailing slash

**Comment by jkotas** [comment]
I do not think we want to be in business of compensating for incorrectly set native toolchain environment variables. 

If we believe that vcvarsall.bat script should be more robust and tolerate some cases of incorrectly set environment variables, we should open a suggestion for VS.

**Comment by eerhardt** [comment]
>  we should open a suggestion for VS.

Done. https://developercommunity.visualstudio.com/t/vcvarsallbat-should-handle-VSINSTALLDIR/10353703
