### ISSUE TITLE
.NET 6 Environment.OSVersion returns compatibility mode version

### ISSUE THREAD

**Issue by natan-abolafya** [dotnet/runtime#85758]
### Description

According to https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/5.0/environment-osversion-returns-correct-version it should return the correct operating system version but it doesn't.
It's strange though since I tried all versions. Am I missing a detail?

### Reproduction Steps

Create a new dotnet 6 project with only this piece of code
```
Console.WriteLine(Environment.OSVersion);
``` 

If I run it directly, I get this on my Windows 10 
```
Microsoft Windows NT 10.0.19045.0
```

I go to `ConsoleApp1\bin\Debug\net6.0\` on explorer and change the exe to this
![image](https://user-images.githubusercontent.com/64091305/236160228-4ccb5b0d-b554-45df-b1d8-9d362bbfd380.png)

I run it again:
```
Microsoft Windows NT 6.2.9200.0
```

### Expected behavior

I should get
```
Microsoft Windows NT 10.0.19045.0
```

### Actual behavior

```
Microsoft Windows NT 6.2.9200.0
```

### Regression?

Tried
```
<TargetFramework>net5.0-windows</TargetFramework>
<TargetFramework>net5.0</TargetFramework>
<TargetFramework>net6.0-windows</TargetFramework>
<TargetFramework>net6.0</TargetFramework>
<TargetFramework>net7.0-windows</TargetFramework>
<TargetFramework>net7.0</TargetFramework>
```
Same result.

### Configuration

```
dotnet --version
7.0.203
```

Windows 10 19045 x64.

**Comment by natan-abolafya** [comment]
yeah, I understand the logic and wouldn't have created this issue if this information was not on microsoft's website. https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/5.0/environment-osversion-returns-correct-version

> In previous .NET versions, [Environment.OSVersion](https://learn.microsoft.com/en-us/dotnet/api/system.environment.osversion#system-environment-osversion) returns an OS version that may be incorrect when an application runs under Windows compatibility mode. For more information, see [GetVersionExA function remarks](https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getversionexa#remarks). On macOS, [Environment.OSVersion](https://learn.microsoft.com/en-us/dotnet/api/system.environment.osversion#system-environment-osversion) returns the underlying Darwin kernel version.

> Starting in .NET 5, [Environment.OSVersion](https://learn.microsoft.com/en-us/dotnet/api/system.environment.osversion#system-environment-osversion) returns the actual version of the operating system for Windows and macOS.

**Comment by jkotas** [comment]
Windows has multiple different compatibility modes. The .NET 5 change applied to manifest-based compatibility shims only. It does not apply to the compatibility modes that can be selected via the compat dialog that you have used. Ultimately, we cannot guarantee that we return the actual OS version in all cases. The underlying OS can always choose to lie to the application.

We should fix the docs.

**Comment by MichalPetryka** [comment]
You can try checking the file version of system executables like `cmd.exe` as a workaround.

**Comment by jkotas** [comment]
> You can try checking the file version of system executables like cmd.exe as a workaround.

Until Windows introduces a compatibility shim for that, it is quite possible they have one already. 

There is no point in going to great lengths to try to circumvent compatibility shims. Compatibility shims can always win if they choose to. It is better to fix the app so that the compatibility shims do not kick in for it.

**Comment by natan-abolafya** [comment]
We used to use the equivalent of `(Get-WmiObject Win32_OperatingSystem).Version` in the past but we like to avoid using wmi if possible. We started using `Environment.OSVersion` because we saw that article. I guess we weren't aware of the multiple compatibility shims :).

**Comment by MSDN-WhiteKnight** [comment]
>You can try checking the file version of system executables like cmd.exe as a workaround.

People already ran into issues when trying to do this: https://github.com/dotnet/runtime/issues/79077 Using WMI is probably better, because administrator-oriented API should not lie to consumers, otherwise admins will be unable to determine whether systems they control update OS correctly.
