### ISSUE TITLE
[wasm] Wasm.Build.Tests - blazor run tests failing

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#85769]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=261558
Build error leg or test failing: Wasm.Build.Tests.Blazor.BuildPublishTests.BlazorBuildRunTest
Pull request: https://github.com/dotnet/runtime/pull/85723

```
        [error] crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
              Unhandled exception rendering component: Could not load type of field 'Microsoft.AspNetCore.Components.Routing.TemplateParser:_invalidParameterNameCharacters' (0) due to: Could not resolve type with token 0100008c from typeref (expected class 'System.Buffers.IndexOfAnyValues`1' in assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a') assembly:System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:System.Buffers.IndexOfAnyValues`1 member:(null)
        System.TypeLoadException: Could not load type of field 'Microsoft.AspNetCore.Components.Routing.TemplateParser:_invalidParameterNameCharacters' (0) due to: Could not resolve type with token 0100008c from typeref (expected class 'System.Buffers.IndexOfAnyValues`1' in assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a') assembly:System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:System.Buffers.IndexOfAnyValues`1 member:(null)
           at Microsoft.AspNetCore.Components.RouteTableFactory.Create(Dictionary`2 templatesByHandler)
           at Microsoft.AspNetCore.Components.RouteTableFactory.Create(List`1 componentTypes)
           at Microsoft.AspNetCore.Components.RouteTableFactory.Create(RouteKey routeKey)
           at Microsoft.AspNetCore.Components.Routing.Router.RefreshRouteTable()
           at Microsoft.AspNetCore.Components.Routing.Router.Refresh(Boolean isNavigationIntercepted)
           at Microsoft.AspNetCore.Components.Routing.Router.RunOnNavigateAsync(String path, Boolean isNavigationIntercepted)
           at Microsoft.AspNetCore.Components.Routing.Router.<>c__DisplayClass67_0.<RunOnNavigateAsync>b__1(RenderTreeBuilder builder)
           at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
        [] info: Microsoft.Hosting.Lifetime[0]
        []       Application is shutting down...
```

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Unhandled exception rendering component: Could not load type of field 'Microsoft.AspNetCore.Components.Routing.TemplateParser:_invalidParameterNameCharacters'",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[262351](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262351)|dotnet/runtime|[Workloads-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262351&view=ms.vss-test-web.build-test-results-tab&runId=5171536&resultId=100101)|dotnet/runtime#85705|
|[262579](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262579)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262579&view=ms.vss-test-web.build-test-results-tab&runId=5160036&resultId=100101)|dotnet/runtime#85738|
|[262524](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262524)|dotnet/runtime|[Workloads-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262524&view=ms.vss-test-web.build-test-results-tab&runId=5155492&resultId=100101)|dotnet/runtime#85787|
|[262499](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262499)|dotnet/runtime|[Workloads-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262499&view=ms.vss-test-web.build-test-results-tab&runId=5154874&resultId=100101)|dotnet/runtime#85741|
|[262441](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262441)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262441&view=ms.vss-test-web.build-test-results-tab&runId=5153912&resultId=100101)|dotnet/runtime#85668|
|[262409](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262409)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262409&view=ms.vss-test-web.build-test-results-tab&runId=5152930&resultId=100101)|dotnet/runtime#85558|
|[262247](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262247)|dotnet/runtime|[Workloads-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262247&view=ms.vss-test-web.build-test-results-tab&runId=5148936&resultId=100101)|dotnet/runtime#85771|
|[262232](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262232)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262232&view=ms.vss-test-web.build-test-results-tab&runId=5148878&resultId=100101)|dotnet/runtime#85770|
|[262213](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262213)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262213&view=ms.vss-test-web.build-test-results-tab&runId=5148524&resultId=100101)|dotnet/runtime#85643|
|[262163](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262163)|dotnet/runtime|[Workloads-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262163&view=ms.vss-test-web.build-test-results-tab&runId=5145754&resultId=100101)|dotnet/runtime#85766|
|[262089](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262089)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262089&view=ms.vss-test-web.build-test-results-tab&runId=5143432&resultId=100101)|dotnet/runtime#85528|
|[262082](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262082)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262082&view=ms.vss-test-web.build-test-results-tab&runId=5142944&resultId=100101)|dotnet/runtime#85445|
|[262045](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262045)|dotnet/runtime|[Workloads-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=262045&view=ms.vss-test-web.build-test-results-tab&runId=5142480&resultId=100101)|dotnet/runtime#85520|
|[261937](https://dev.azure.com/dnceng-public/public/_build/results?buildId=261937)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=261937&view=ms.vss-test-web.build-test-results-tab&runId=5138178&resultId=100101)||
|[261558](https://dev.azure.com/dnceng-public/public/_build/results?buildId=261558)|dotnet/runtime|[Workloads-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=261558&view=ms.vss-test-web.build-test-results-tab&runId=5137492&resultId=100101)|dotnet/runtime#85723|
|[261899](https://dev.azure.com/dnceng-public/public/_build/results?buildId=261899)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=261899&view=ms.vss-test-web.build-test-results-tab&runId=5136100&resultId=100101)|dotnet/runtime#85254|
|[261758](https://dev.azure.com/dnceng-public/public/_build/results?buildId=261758)|dotnet/runtime|[Workloads-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=261758&view=ms.vss-test-web.build-test-results-tab&runId=5132274&resultId=100087)|dotnet/runtime#85498|
|[261643](https://dev.azure.com/dnceng-public/public/_build/results?buildId=261643)|dotnet/runtime|[Workloads-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=261643&view=ms.vss-test-web.build-test-results-tab&runId=5131174&resultId=100101)|dotnet/runtime#85741|
|[261591](https://dev.azure.com/dnceng-public/public/_build/results?buildId=261591)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=261591&view=ms.vss-test-web.build-test-results-tab&runId=5129660&resultId=100101)|dotnet/runtime#84867|
|[261546](https://dev.azure.com/dnceng-public/public/_build/results?buildId=261546)|dotnet/runtime|[Workloads-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=261546&view=ms.vss-test-web.build-test-results-tab&runId=5128866&resultId=100101)|dotnet/runtime#74623|
|[261541](https://dev.azure.com/dnceng-public/public/_build/results?buildId=261541)|dotnet/runtime|[Workloads-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=261541&view=ms.vss-test-web.build-test-results-tab&runId=5128040&resultId=100107)|dotnet/runtime#74623|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|21|

**Comment by lewing** [comment]
blocked on https://github.com/dotnet/aspnetcore/pull/48014

**Comment by radical** [comment]
This was fixed by https://github.com/dotnet/runtime/pull/86268 but didn't get closed.

**Comment by simeyla** [comment]
For anyone seeing this message after updating to the June 2023 preview of .NET 8 (preview 5) you just need to update your project's packages.
