### ISSUE TITLE
[browser] do native build when preserving native symbols

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#85778]
WasmStripNative==false should turn on WasmBuildNative. The default runtime is stripped, you must do a native build to preserve symbols

**Comment by radical** [comment]
A `debug` build has `WasmNativeStrip=false`, which would trigger relinking. Without the change suggested here though, it wouldn't, and thus not really have any effect at all.

Maybe for `debug` *build* 1. don't set `WasmNativeStrip=false`; 2. emit a message suggesting that to get symbols the user should set `WasmNativeStrip=false`?
