### ISSUE TITLE
Test failure ConsoleEncoding.TestEncoding

### ISSUE THREAD

**Issue by CarnaViire** [dotnet/runtime#85772]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=262105
Build error leg or test failing: ConsoleEncoding.TestEncoding
Pull request: https://github.com/dotnet/runtime/pull/85143

ConsoleEncoding.TestEncoding(inputString: \"This string has invalid surrogates \\xd800\\xd800\\xd\"...)
[console log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-85143-merge-4459c320b0ab437bb3/System.Console.Tests/1/console.9a8553af.log?helixlogtype=result)

Failing Configuration
`net8.0-linux-Debug-x64-Mono_release-Ubuntu.1804.Amd64.Open`

Exception Message
```
Assert.Equal() Failure
                          ↓ (pos 50)
Expected: [..., 191, 189, 239, 191, 189]
Actual:   [..., 191, 189, 0, 0, 0]
                          ↑ (pos 50)
```

Stack Trace
```
   at ConsoleEncoding.TestEncoding(String inputString) in /_/src/libraries/System.Console/tests/ConsoleEncoding.cs:line 58
   at System.Object.InvokeStub_ConsoleEncoding.TestEncoding(Object , Object , IntPtr* )
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 55
```

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "ConsoleEncoding.TestEncoding(inputString: \"This string has invalid surrogates \\xd800\\xd800\\xd\"...) [FAIL]",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by adamsitnik** [comment]
So far it happened only once and on Mono, I've removed `blocking-clean-ci` and moved it to Future.

**Comment by adamsitnik** [comment]
> 1-Month Count: 0

No repros since may, closing.
