### ISSUE TITLE
[WASM] Blazor Application crashes after 15 minutes

### ISSUE THREAD

**Issue by JustSxm** [dotnet/runtime#85774]
### Description

 Blazor Application crashes after around 15 minutes from an error caused by mono.  I would love to attempt to debug it and be more helpful, but the error doesn't tell us anything obvious.

### Reproduction Steps

We build the application with docker. 

```
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["Project", "Project"]
RUN dotnet restore "Project/Project.csproj"
COPY . .
WORKDIR "/src/Project"
RUN dotnet build "Project.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "BusinessOne.Polling.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Project.dll"]
```

With these properties in the Server
```
<WasmNativeStrip>false</WasmNativeStrip>
<PublishTrimmed>false</PublishTrimmed>
```

### Expected behavior

Does not crash. 

### Actual behavior

Crashes

### Known Workarounds

This does not happen when in debug on our side. Including debugging with docker. It only happens when it is build in release, published in the docker file and deployed.

### Configuration

Which version of .NET is the code running on? 
Dotnet 7

What OS and version, and what distro if applicable? 
Windows 10 (for debug), Linux (for release & publish)

What is the architecture (x64, x86, ARM, ARM64)? 
x64

Do you know whether it is specific to that configuration?
No

If you're using Blazor, which web browser(s) do you see this issue in?
Chrome

### Other information

I attached the Console logs of the webassembly application.
[console (2).log](https://github.com/dotnet/runtime/files/11398786/console.2.log)

**Comment by JustSxm** [comment]
> AOT

Yes

**Comment by JustSxm** [comment]
After further investigation, seems that it's a third party package that cause this error. Should I close the ticket?

**Comment by vargaz** [comment]
The application should not crash like that unless it contains some native/unsafe code which corrupts memory etc.
