### ISSUE TITLE
Support System.Text.Json on .NET Framework 4.6.1

### ISSUE THREAD

**Issue by Cyberneticocst** [dotnet/runtime#85793]
### Description

System.Text.Json is necessary, please, that they give it compatibility with net framework 4.6.1 so that it does not have a problem with windows 10 2015

### Reproduction Steps

System.Text.Json is necessary, please, that they give it compatibility with net framework 4.6.1 so that it does not have a problem with windows 10 2015

### Expected behavior

System.Text.Json is necessary, please, that they give it compatibility with net framework 4.6.1 so that it does not have a problem with windows 10 2015

### Actual behavior

System.Text.Json is necessary, please, that they give it compatibility with net framework 4.6.1 so that it does not have a problem with windows 10 2015

### Regression?

System.Text.Json is necessary, please, that they give it compatibility with net framework 4.6.1 so that it does not have a problem with windows 10 2015

### Known Workarounds

System.Text.Json is necessary, please, that they give it compatibility with net framework 4.6.1 so that it does not have a problem with windows 10 2015

### Configuration

System.Text.Json is necessary, please, that they give it compatibility with net framework 4.6.1 so that it does not have a problem with windows 10 2015

### Other information

System.Text.Json is necessary, please, that they give it compatibility with net framework 4.6.1 so that it does not have a problem with windows 10 2015

**Comment by danmoseley** [comment]
@Cyberneticocst what is holding you on 4.6.1?

**Comment by stephentoub** [comment]
Note that .NET Framework 4.6.1 is out of support.  Support for it ended in April 2022.

**Comment by huoyaoyuan** [comment]
Windows 10 1507 is still in LTSB support until 2025. According to [documentation](https://learn.microsoft.com/en-us/dotnet/framework/install/on-windows-10#net-framework-462), it supports .NET Framework 4.6.2, which is still in support.
