### ISSUE TITLE
ComInterfaceGenerator generates cleanup stage for stateless marshalled parameters when it shouldn't

### ISSUE THREAD

**Issue by jtschuster** [dotnet/runtime#85795]
Parameters marshalled by stateless marshallers are being freed in too many scenarios. They should only be freed in unmanaged to managed ref scenarios (on the pointer that was passed in, not the value that is returned at the end of the method. In and Out parameters should not be cleaned up. Stateful marshallers can have free called on them as they can know which MarshalMode they are in and decide to actually free the underlying memory or not.

**Comment by jkoritzinsky** [comment]
For stateful marshallers specifically, they may also be tracking additional state for an unmanaged->managed in/out/ref scenario that needs to be freed in addition to/instead of the unmanaged value.
