### ISSUE TITLE
The working directory log message on app startup

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#85809]
### Description

https://github.com/dotnet/runtime/pull/82445 added a new log message when an app starts (last line):

```
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Development\source\Benchmarks\src\BenchmarksApps\Grpc\BasicGrpc
info: Microsoft.Hosting.Lifetime[0]
      Current working directory is /. If Content root path is not set explicitly, then working directory is used by default.
```

This is a very prominent place for logging. Every ASP.NET Core app displays this log message by default when it starts. Exact thought needs to be put into what is logged here and it seems like it needs more work.

* Weird casing. Why is "Content" capitalized in "If Content root ..."? It looks like a typo.
* The log message is inconsistent with the other logging written during startup
* Also, the meaning of the working directory value in logging is unclear. What does `/` mean? Should this be a full path?
* Is information the right log level? Should this be displayed by default? The default ASP.NET Core log level is `Information`. If this is only useful for debugging then perhaps the `Debug` log level would be better. That reduces logs written on app start.
* Needs unit tests

### Reproduction Steps

Start an app with hosting, e.g. an aspnetcore app, with console logging. The log is written to the console:

### Expected behavior

Log message is consistent with other logs on startup. Working directory value is easy to understand.

### Actual behavior

```
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Development\source\Benchmarks\src\BenchmarksApps\Grpc\BasicGrpc
info: Microsoft.Hosting.Lifetime[0]
      Current working directory is /. If Content root path is not set explicitly, then working directory is used by default.
```

Hosting environment and content root path logs have the format `Name: value`. I would expect the current working directory to be the same, e.g. `Working directory: XXX`.

Also, this log seems the wrong place to add extra detail like `If Content root path is not set explicitly, then working directory is used by default.`. This logging is visible by default in every ASP.NET Core app that starts up. Only the most important detail should be logged here. I don't think that sentence meets the bar.

**Comment by JamesNK** [comment]
cc @DamianEdwards @davidfowl

**Comment by davidfowl** [comment]
I think we should revert this. It's unclear why this is useful information to show all of the time.

cc @steveharter @ericstj

**Comment by ericstj** [comment]
Let's have another look at this, @steveharter.  CC @pedrobsaila

**Comment by steveharter** [comment]
The commit was reverted and the original [issue ](https://github.com/dotnet/runtime/issues/78789)was reopened.
