### ISSUE TITLE
IlcGenerateMstatFile doesn't work on MachO architectures (macOS, iOS)

### ISSUE THREAD

**Issue by filipnavara** [dotnet/runtime#85814]
Error reported from LLVM ObjWriter: `EXEC : LLVM error : unable to evaluate offset to undefined symbol ''`

**Comment by filipnavara** [comment]
I tried to reproduce it with latest Debug build to get a stack trace but the error didn't happen. It did happen with the ILCompiler from 8.0.0-preview.4.23225.9 NuGet package on the same inputs (same .rsp file).

**Comment by MichalStrehovsky** [comment]
This was fixed in #85626.

The objwriter messages are red herring. We tell object writer to wrap things up in a finally but it doesn't make sense to wrap up if there was an exception.
