### ISSUE TITLE
Mono incorrectly throws a TypeLoadException for a recursive type definition

### ISSUE THREAD

**Issue by joshpeterson** [dotnet/runtime#85821]
### Description

Given the following code:

```csharp
var test = new Node<int>();
Console.WriteLine(test);

public class Node<T>
{
  public Node<T>[][] Children;
  public T Data;
}
```
Mono will throw a `TypeLoadException` exception, which is not expected:
```
Unhandled Exception:
System.TypeLoadException: Recursive type definition detected .Node`1
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Recursive type definition detected .Node`1
```
CoreCLR does not throw a similar exception.

### Reproduction Steps

1. Create a new console app with the code above.
2. In the .csproj file, add the following content to run the console app with Mono:

```        
<SelfContained>true</SelfContained>
<UseMonoRuntime>true</UseMonoRuntime>
<RuntimeIdentifier>osx-x64</RuntimeIdentifier>
```
(Note that I'm using macOS x64, but the behavior is not specific to platform or architecture.)

3. Run the built console app, the exception will occur, which is not expected.

### Expected behavior

The output is:

```
Node`1[System.Int32]
```
 and no exception occurs.

### Actual behavior

Mono will throw a `TypeLoadException` exception, which is not expected:
```
Unhandled Exception:
System.TypeLoadException: Recursive type definition detected .Node`1
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Recursive type definition detected .Node`1
```

### Regression?

This has not worked in Mono. I also see the same behavior with Mono 6.12.0 from the mono/mono repository.

### Known Workarounds

I don't have any known worarounds.

### Configuration

I'm using .NET version 7.0.202 on macOS x64.

### Other information

This bug was originally reported to Unity here: https://issuetracker.unity3d.com/issues/typeloadexception-is-thrown-when-using-recursive-types-in-monobehaviour-inherited-classes

**Comment by lambdageek** [comment]
We've fixed a number of cases similar to this one.  In principle this ought to work: it's not a struct, the generic parameter doesn't get used in a parent class or an interface, etc.

I'll take an initial look

**Comment by lambdageek** [comment]
Repros with .NET8 previews.

It's not because of the toplevel statements, AFAICT.  Same problem if I make a normal class with a Main.

It does seem to be related to `Node<T>[][]`. If I change it to `Node<T>[]`, the exception goes away.

I think probably the constructor for arrays is too aggressive in initializing the element type.  if we know it's a reference type, we shouldn't need to expand it too much.

But on the other hand, initializing `Node<T>[]` works - so we must understand at least some types of recursion in this case.

Maybe it's something about array interface methods.  I'll have to try a runtime with tracing enabled.

**Comment by lambdageek** [comment]
we're probably hitting something added in 2005.  If the code is overly-pessimistic, it's an easy fix.  If it turns out the initialization is necessary, we are probably looking at a very hard bug (probably will need loader levels ala https://github.com/mono/mono/issues/7856)

**Comment by joshpeterson** [comment]
I wanted to follow up on this. @lambdageek: Did the draft PR provide a viable solution?

**Comment by joshpeterson** [comment]
@lambdagee: Did you have a chance to step through the initialization code in the debugger?

**Comment by lambdageek** [comment]
@joshpeterson hey, sorry it took a while. yea I'm not pretty confident I understand what the difference was between `Node[] Children` and `Node[][] Children`.  I updated the PR with some notes.

**Comment by lambdageek** [comment]
oops. Edited the previosu comment.  I meant to say "I'm **now** pretty confident".  The PR is good.

**Comment by joshpeterson** [comment]
> @joshpeterson hey, sorry it took a while. yea I'm now pretty confident I understand what the difference was between `Node[] Children` and `Node[][] Children`. I updated the PR with some notes.

Thank you! I'll watch that PR and sync it back to our fork of Mono when it lands.
