### ISSUE TITLE
Q: How to build a Metric-based SystemRuntimeMetrics.cs in System.Private.CoreLib that has a dependency on System.Diagnostics.Metrics?

### ISSUE THREAD

**Issue by omajid** [dotnet/runtime#85827]
As part of https://github.com/dotnet/runtime/issues/85372, I am trying to prototype a class that uses [`System.Diagnostics.Metrics`](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.metrics?view=net-8.0). 

Basing the layout on the existing `src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/RuntimeEventSource.cs` file, I have placed this at `src/libraries/System.Private.CoreLib/src/System/Diagnostics/Metrics/SystemRuntimeMetrics.cs`.

The class looks like this:

```csharp
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Diagnostics.CodeAnalysis;
using System.Diagnostics.Metrics;
using System.Threading;

namespace System.Diagnostics.Metrics
{
    /// <summary>
    /// SystemRuntimeMetrics contains meters for measurements in the managed runtime.
    /// </summary>
    internal sealed partial class SystemRuntimeMetrics
    {
        private static SystemRuntimeMetrics? s_SystemRuntimeMetrics;

        internal const string MeterName = "System.Runtime";

        private ObservableUpDownCounter<uint>? _assemblyCounter;
    }
}
```

I plugged it into the build system like this:

```
diff --git a/src/libraries/System.Private.CoreLib/src/System.Private.CoreLib.Shared.projitems b/src/libraries/System.Private.CoreLib/src/System.Private.CoreLib.Shared.projitems
index f4cec1a72c6..a81af6f9e7d 100644
--- a/src/libraries/System.Private.CoreLib/src/System.Private.CoreLib.Shared.projitems
+++ b/src/libraries/System.Private.CoreLib/src/System.Private.CoreLib.Shared.projitems
@@ -1413,6 +1413,7 @@
     <Compile Include="$(CommonPath)Interop\Windows\Advapi32\Interop.EVENT_INFO_CLASS.cs">
       <Link>Common\Interop\Windows\Advapi32\Interop.EVENT_INFO_CLASS.cs</Link>
     </Compile>
+    <Compile Include="$(MSBuildThisFileDirectory)System\Diagnostics\Metrics\SystemRuntimeMetrics.cs" Condition="'$(FeaturePerfTracing)' == 'true'" />
     <Compile Include="$(MSBuildThisFileDirectory)System\Diagnostics\Tracing\ActivityTracker.cs" />
     <Compile Include="$(MSBuildThisFileDirectory)System\Diagnostics\Tracing\DiagnosticCounter.cs" />
     <Compile Include="$(MSBuildThisFileDirectory)System\Diagnostics\Tracing\CounterGroup.cs" />
```

Build trying to build it leads to errors like this:

```
src/libraries/System.Private.CoreLib/src/System/Diagnostics/Metrics/SystemRuntimeMetrics.cs(19,17): error CS0246: The type or namespace name 'ObservableUpDownCounter<>' could not be found (are you missing a using directive or an assembly reference?) [src/coreclr/System.Private.CoreLib/System.Private.CoreLib.csproj]
```

How should I take a dependency on the `System.Diagnostics.Metrics` namespace?

**Comment by jkotas** [comment]
> How should I take a dependency on the System.Diagnostics.Metrics namespace?

I do not think this should be in CoreLib. The runtime metrics provider should in System.Diagnostics.DiagnosticSource (or in a new assembly) and call public runtime APIs to access the metrics. If we are still missing some public APIs for this, we should add them.

cc @noahfalk @tarekgh

**Comment by tarekgh** [comment]
@jkotas is correct. The runtime needs to expose whatever APIs to retrieve the needed metrics data. The counters will be exposed from the Microsoft.Extensions.* or DiagnosticSource library. 

@omajid I am going to close this issue and we can open any issues for any missing runtime metrics data.

**Comment by omajid** [comment]
Thanks!
