### ISSUE TITLE
[API Proposal]: File.DeleteAsync(path)

### ISSUE THREAD

**Issue by thomhurst** [dotnet/runtime#85834]
### Background and motivation

There is no option to delete files asynchronously, without workarounds such as wrapping a synchronous delete in a new task.

Since files are on the disk, this operation is I/O, so could benefit from being asynchronous, especially for tools that might be calling this multiple times concurrently.

E.g. A tool to clean up junk or temporary files

It'd be good to have this implemented in the core library, for better performance than the workarounds, and of course not needing to work around any limitations in the core library.

### API Proposal

```csharp
await File.DeleteAsync(path)
```

### API Usage

```csharp
await File.DeleteAsync(path)
```

### Risks

N/A

**Comment by Tornhoof** [comment]
Atleast on Windows there is no async File delete api, as far as i know. For ReadFile etc. there is. See e.g
https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-deletefile
and
https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-readfileex

So, atleast on Windows, it would be equally "Fake" as you wrapping it in tasks.

**Comment by huoyaoyuan** [comment]
See #63153 #67587 #74848

**Comment by thomhurst** [comment]
Seems crazy that after all these years that major OS's don't have this, especially as disk is all I/O which gains the biggest benefit from doing things asynchronously??

**Comment by huoyaoyuan** [comment]
The only API I know that has async filesystem operations is WinRT storage API, which is also known to be slow.

**Comment by stephentoub** [comment]
Thanks for the proposal. As noted on the other issue, we don't add async APIs if the only way we could implement then is by queuing the synchronous work. And the main OSes .NET targets don't provide asynchronous file deletion APIs.
