### ISSUE TITLE
how to hotload  dotnet assembly in coreclr?

### ISSUE THREAD

**Issue by 1982889949** [dotnet/runtime#85862]
My project uses two languages C++and c #. C # and C++interoperability uses .Net CoreCLR to host managed code in C++. Now the project needs to implement the DLL function of dynamically loading C #. So that C++code can compile and generate C# DLLs during runtime, that is, dynamically load them. Now, it is necessary to stop the C++code running before compiling C # code and generating DLLs. In large projects, this can consume development time. I saw a method to add the environment variable "DOTNET_MODIFIABLE_ASSEMBLIES" in C++CORECLR, but  couldn't provide detailed guidance and didn't quite understand it.Is there a good solution and how to implement hot update DLL operations? Does CoreCLR have its own way to support dynamic loading? How to achieve it? thank you！

**Comment by huoyaoyuan** [comment]
You can use `AssemblyLoadContext` and set it as collectible, then load assembly into it. Then you can unload the ALC and create a new one with new assembly.

**Comment by 1982889949** [comment]
> 

I used the method you mentioned, but it is a bit difficult to implement. My C # project is relatively large, and multiple assemblies depend on each other. It takes a lot of time and costs a lot to change. I want to see if you have a better method. Try not to change the C # side, and change the C++coreclr managed code side, which costs the least.Thank you very much for your suggestion！

**Comment by huoyaoyuan** [comment]
I don't believe there is a way to patch already loaded assemblies without debugging techniques like Hot Reload, which also has many limitations.

**Comment by agocke** [comment]
Closing as question was answered
