### ISSUE TITLE
Polymorphism on System.Text.Json source generation with different assemblies

### ISSUE THREAD

**Issue by isadorasophia** [dotnet/runtime#85884]
### Description

I am trying to figure out how to leverage polymorphism with System.Text.Json source generation when the base class has been declared in a different assembly. My app targets **.NET 7** and I am compiling the project with:
```csproj
<PublishTrimmed>true</PublishTrimmed>
<PublishAot>true</PublishAot>
```

### Reproduction Steps

Consider the interface declared in **a.dll**:
```csharp
public interface IComponent { }
```

and the inherited type declared in **b.dll**:
```csharp
public readonly struct Component : IComponent { }
```

### Expected behavior

I expect some source generator for the inherited type, e.g.

```csharp
[JsonDerivedTypeFrom(typeof(IComponent), "Component")]
public readonly struct Component : IComponent { }
```

### Actual behavior

Right now, I need to do the following to generate the source accordingly:

```csharp
[JsonDerivedType(typeof(Component), "Component")]
public interface IComponent { }

[JsonSerializable(typeof(IComponent))]
public partial class SourceGenerationContext : JsonSerializerContext
{
}
```

However, this is not practical if **IComponent** has been declared on another assembly (a.dll), as b.dll already depends on a.dll and I would just create a cyclic reference. I currently need to rely on reflection to actually serialize this.

If I don't use JsonDerivedType, the following exception occurs while deserializing it:
`System.NotSupportedException: Deserialization of interface types is not supported. `
Which is odd considering that it is supported under that attribute.

### Regression?

No.

### Known Workarounds

I can write a JsonConverter and use reflection to serialize this type. I guess I also need to adjust rd.xml to do it correctly on native AOT.

### Configuration

I am running on .NET 7 in Windows x64 and targeting native AOT.

**Comment by isadorasophia** [comment]
I saw other duplicate issues on this, apparently it is by design. I was able to workaround by using a custom JsonConverter and redirecting the payload according to its metadata. I manually generate a list of derived types my JsonConverter.

I will keep that around if there are any updates on decisions to support this (or any .NET 8 work that might make these tweaking converters easier).

**Comment by pinkfloydx33** [comment]
Couldn't you achieve all of this with the existing [contract model](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/polymorphism?source=recommendations&pivots=dotnet-7-0#configure-polymorphism-with-the-contract-model), rather than in a converter?

**Comment by isadorasophia** [comment]
@pinkfloydx33 thanks for the link! it was a bit odd, I tried implementing my own info resolver:

```csharp
// [JsonSerializable(typeof(IComponent))] I think I don't need this?
[JsonSerializable(typeof(Position))]
public partial class SourceGenerationContext : JsonSerializerContext
{
    static SourceGenerationContext()
    {
        s_defaultOptions.TypeInfoResolver = new ComponentTypeResolver();
    }
}

public class ComponentTypeResolver : DefaultJsonTypeInfoResolver
{
    public override JsonTypeInfo GetTypeInfo(Type type, JsonSerializerOptions options)
    {
        JsonTypeInfo jsonTypeInfo = base.GetTypeInfo(type, options);

        Type basePointType = typeof(IComponent);
        if (jsonTypeInfo.Type == basePointType)
        {
            jsonTypeInfo.PolymorphismOptions = new JsonPolymorphismOptions
            {
                IgnoreUnrecognizedTypeDiscriminators = true,
                UnknownDerivedTypeHandling = JsonUnknownDerivedTypeHandling.FailSerialization,
                DerivedTypes =
                {
                    new JsonDerivedType(typeof(Position), nameof(Position))
                }
            };
        }

        return jsonTypeInfo;
    }
}
```

but when I ran:
```csharp
Position testPosition = new(30, 30);
string jsonString = JsonSerializer.Serialize(testPosition, typeof(IComponent), SourceGenerationContext.Default);
Console.WriteLine(jsonString);
```

I get:
**System.NotSupportedException: 'Deserialization of interface types is not supported. Type 'Engine.IComponent'. Path: $ | LineNumber: 1 | BytePositionInLine: 1.'**

JsonConverter has been working fine for the line above though. Maybe I missed something?

**Comment by eiriktsarpalis** [comment]
> However, this is not practical if IComponent has been declared on another assembly (a.dll), as b.dll already depends on a.dll and I would just create a cyclic reference. I currently need to rely on reflection to actually serialize this.

In such cases, I generally recommend moving your `JsonSerializerContext` to a third assembly that references all assemblies containing your DTOs (e.g. in your application assembly if practical). If you can afford the refactoring cost, you might consider simply collocating all your DTOs in a single project, which would make them easier to control and evolve.

**Comment by eiriktsarpalis** [comment]
@isadorasophia does the above answer your question? Thanks!

**Comment by isadorasophia** [comment]
@eiriktsarpalis Sorry that it took a while to get back to this! Thanks for the suggestions 🙂 It's not really practical for me to keep this in a third assembly (it's a game engine and the intent is to keep the metadata in place). I'm okay relying on converters/resolvers/reflection whenever source generator is not enough (I'll also need it to handle private fields, probably).

Do you mean something like this?

```csharp
SourceGenerationContext context = new(new JsonSerializerOptions() { WriteIndented = true, IncludeFields = true, IgnoreReadOnlyProperties = false, TypeInfoResolver = new ComponentTypeResolver() });

string jsonString = JsonSerializer.Serialize(testPosition, typeof(IComponent), context);
```

I still see the same exception and `ComponentTypeResolver` is never reached. I was able to use both syntaxes when adding a custom JsonConverter, though.

**Comment by BreyerW** [comment]
This is something i will also run into sooner or later. I hope multi-assembly story can be improved in future. I dont think this is seriously blocking for me but it will leave bad taste if i will have to resort to reflection and/or fairly complex custom resolver in otherwise reflection-free and relatively straightforward serialization codebase

**Comment by eiriktsarpalis** [comment]
@isadorasophia Here's how you could get this working using source generators:
```C#
using ClassLibrary1;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;

var options = new JsonSerializerOptions
{
    TypeInfoResolver = SourceGenerationContext.Default.WithModifier(
        static typeInfo =>
        {
            if (typeInfo.Type == typeof(IComponent))
            {
                typeInfo.PolymorphismOptions = new()
                { 
                    DerivedTypes =
                    {
                        new JsonDerivedType(typeof(Component), nameof(Component))
                    }
                };
            }
        })
};

IComponent component = new Component();
Console.WriteLine(JsonSerializer.Serialize(component, options));

public readonly struct Component : IComponent { }

[JsonSerializable(typeof(IComponent))]
[JsonSerializable(typeof(Component))]
public partial class SourceGenerationContext : JsonSerializerContext
{
}

public static class ResolverExtensions
{
    public static IJsonTypeInfoResolver WithModifier(this IJsonTypeInfoResolver resolver, Action<JsonTypeInfo> modifier)
        => new ModifierResolver(resolver, modifier);

    private sealed class ModifierResolver : IJsonTypeInfoResolver
    {
        private readonly IJsonTypeInfoResolver _source;
        private readonly Action<JsonTypeInfo> _modifier;

        public ModifierResolver(IJsonTypeInfoResolver source, Action<JsonTypeInfo> modifier)
        {
            _source = source;
            _modifier = modifier;
        }

        public JsonTypeInfo? GetTypeInfo(Type type, JsonSerializerOptions options)
        {
            JsonTypeInfo? typeInfo = _source.GetTypeInfo(type, options);
            if (typeInfo != null)
            {
                _modifier(typeInfo);
            }

            return typeInfo;
        }
    }
}
```
