### ISSUE TITLE
[NativeAOT] Missed devirtualization opportunities due to Unsafe.As

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#85906]
In the below program we miss a devirtualization opportunity in `Method` due to the `Unsafe.As`.

`IFace` has a single implementor but RyuJIT doesn't even ask for it.

```csharp
using System;
using System.Runtime.CompilerServices;

interface IFace
{
    void Frob();
}

class Program : IFace
{
    public static IFace s_inst = new Program();

    public object inst;

    public Program() => inst = s_inst;

    public void Frob() { }

    [MethodImpl(MethodImplOptions.NoInlining)]
    public void Method() => Unsafe.As<IFace>(inst).Frob();

    static void Main()
    {
        new Program().Method();
    }
}
```

I noticed this in the pattern from here as I was looking why interface dispatch is so hot (2.7% of samples spent in `RhpInterfaceDispatch1` **alone**) in BasicMinimalApis:

https://github.com/dotnet/runtime/blob/05a3d360d6079db3cb64636fcdf99f832a58c1d2/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/ValueTask.cs#L719

Cc @EgorBo

**Comment by EgorBo** [comment]
Dup of https://github.com/dotnet/runtime/issues/84377

Currently `Unsafe.As` is just a no-op for JIT,
