### ISSUE TITLE
`Double.NegativeZero` is actually `+0.0`

### ISSUE THREAD

**Issue by andanteyk** [dotnet/runtime#85914]
### Description

`Double.NegativeZero` is actually `+0.0` (non-negative).

### Reproduction Steps

```cs
using System;

Console.WriteLine($"{BitConverter.DoubleToUInt64Bits(double.NegativeZero):x16}");
Console.WriteLine($"{BitConverter.DoubleToUInt64Bits(-0.0):x16}");
```

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoaosgTgAoASAIgG8AhASwwGEIeAG4woGUQDoAIhBzAANjAAqEAKoBJPBlQ8MAZ0YATWQpgSAcjADmAQwzcRALVEQAlCARkkAX1auA3LQMLBy6AsKi4lDSJooqGlo6vAZwAAwSqe6ePn6BVEA=

### Expected behavior

```
8000000000000000
8000000000000000
```

### Actual behavior

```
0000000000000000
8000000000000000
```

### Known Workarounds

`-0.0` (literal) is correctly recognized as -0.0 (0x80000000_00000000 in binary).

### Configuration

This issue was reproduced in the following environment:
* .NET 8.0.0-preview.3.23174.8
* .NET 7.0.4

OS: Windows 11, 22H2 (x64)

**Comment by Xiera-Services** [comment]
claim

**Comment by skyoxZ** [comment]
`float.NegativeZero` is defined as `-0f`, witch is correct.

**Comment by tannergooding** [comment]
We should be explicit and ensure it is `-0.0f` to help avoid any potential ambiguity/etc

**Comment by skyoxZ** [comment]
I think a number ended with `f` is definitely a float, while it would be nice to have a test case of `BitConverter.SingleToUInt32Bits(float.NegativeZero)`.

**Comment by tannergooding** [comment]
We have such tests the issue is that the reference assembly is out of sync with the implementation assembly and running tests against the reference assembly isn’t as trivial

**Comment by Xiera-Services** [comment]
> We have such tests the issue is that the reference assembly is out of sync with the implementation assembly and running tests against the reference assembly isn’t as trivial

May I ask what do you mean with 'isn't as trivial'? In my mind I wanted to create a simple test against it as well, but I take it that you mean it won't be that easy?

**Comment by tannergooding** [comment]
Not all of the test projects compile against the `ref assembly` and so adding a new explicit test to `src\libraries\System.Runtime\tests\System\DoubleTests.cs` may or may not reproduce the issue. If it does, that's great. If not then I'll need to provide more in depth guidance on how to get the test actually doing the right things.

The fix here is simple, just make the two line changes in `src\libraries\System.Runtime\ref\System.Runtime.cs` to explicitly use `-0.0` and `-0.0f` for consistency.

The real "fix", which would avoid future issues, is a bit more complex and involves touching code in https://github.com/dotnet/arcade. More specifically you'd need to special case `-0` in https://github.com/dotnet/arcade/blob/main/src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Attributes.cs#L270-L293

**Comment by skyoxZ** [comment]
I can confirm that adding a test in `DoubleTests.cs` can reproduce the issue and the test succeeds after building `src/libraries/System.Runtime/ref/System.Runtime.csproj` with the fix.
