### ISSUE TITLE
[High Memory] Consumed approximately 300MB of additional memory with latest runtime docker image 6.0.16

### ISSUE THREAD

**Issue by Richeir** [dotnet/runtime#85924]
Hey Team,

I recently updated a service **without changing the code,** **only rebuilding the image**. I used the latest version of the ASP.NET Core Runtime image (**6.0.16**, whereas before it was **6.0.6**). I then discovered through monitoring that the **memory usage had increased by about 300 MB**.

Have you encountered this issue?

Below is a screenshot of the monitoring:

![image](https://user-images.githubusercontent.com/1574948/236878362-71e1e64f-3e82-4823-adfa-977e5f6b854d.png)

**Comment by mangod9** [comment]
Hello @Richeir, are you able to repro this for a simple asp.net app, or is the increase specific to your scenario? Thx.

**Comment by Richeir** [comment]
> 

Hey @mangod9 , thank you for your reply

I'm afraid I can't do it because this is the working project code, and my environment may not be suitable for testing a simple ASP. NET project.

Perhaps you can tell me, have you ever encountered the same situation?

**Comment by mangod9** [comment]
We havent heard of any broad issues around working set increase in 6.0.x. Perhaps you could try to narrow down which release after 6.0.6 you notice the increase and that might help narrow down the set of changes to help with investigating. 

Also if its possible to share a dump and/or GC traces (for both 6.0.6 and 6.0.16) then it might help narrow it down too. Thx!

**Comment by Richeir** [comment]
@mangod9 Thanks!

I believe that if it is a widespread issue of sudden memory consumption, it should be quickly identified and resolved.

Thank you for your confirmation. I will provide feedback on these issues to my colleagues.

This issue has been resolved. 

Thank you for your enthusiasm!

**Comment by mangod9** [comment]
Hi @Richeir, by resolved do you mean it was fixed by some code change on your side?

**Comment by Richeir** [comment]
Hi @mangod9, I closed this issue only because I confirmed that it is not a problem with the. NET runtime.

We are still trying to find the root cause.
