### ISSUE TITLE
Readonly access of JsonObject with dynamic is not working

### ISSUE THREAD

**Issue by MatrixRonny** [dotnet/runtime#85943]
### Description

I have failed to use dynamic with System.Text.Json in .NET 6.

This issue [https://github.com/dotnet/runtime/issues/53195](https://github.com/dotnet/runtime/issues/53195) states that: 
Currently `JsonObject` supports C# "dynamic" which primarily means an instance of JsonObject can get\set a property value without having to use a string for the property name.

Also, there is an example in that post that I have copy pasted and throws an exception.

### Reproduction Steps

Example 1:
```
using System.Text.Json.Nodes;
const string Json = "{\"MyNumber\":42, \"MyArray\":[10,11]}";
dynamic obj = JsonNode.Parse(Json);
int number = (int)obj.MyNumber;
```

Example 2:
```
using System.Text.Json;
const string Json = "{\"MyNumber\":42, \"MyArray\":[10,11]}";
dynamic obj = JsonSerializer.Deserialize<JsonObject>(Json);
int number = (int)obj.MyNumber;
```

### Expected behavior

I was expected the code to run successfully and return the value found in the JSON string.

### Actual behavior

In both cases, I receive the following exception:
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'System.Text.Json.Nodes.JsonObject' does not contain a definition for 'MyNumber'

### Regression?

No, it is the first time I am testing such code.

### Known Workarounds

This works fine with Json.NET library. Also, there are all sorts of work arounds in this SO post: [https://stackoverflow.com/questions/3142495/deserialize-json-into-c-sharp-dynamic-object]( https://stackoverflow.com/questions/3142495/deserialize-json-into-c-sharp-dynamic-object)

### Configuration

.NET 6
Windows 10 Pro
x64
It is not a configuration issue
Not using Blazor

### Other information

I have tried `JsonSerializer.Deserialize<ExpandoObject>` and noticed with Visual Studio that data is properly populated in the `ExpandoObject`. The same is true on the `JsonObject`, but I don't know how dynamic is expected to work there. Also, it is possible to use the non-dynamic version to access deserialized JSON data.

**Comment by hez2010** [comment]
It is expected because dynamic support has been removed from System.Text.Json, see https://github.com/dotnet/runtime/pull/55430

**Comment by MatrixRonny** [comment]
Thanks for clarifying. I think that's all there is to this issue. Maybe add this information at the end of the post describing use of dynamic with JsonNode.
