### ISSUE TITLE
Could not find chrome snapshot folder for Linux_x64

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#85949]
### Error Blob

```json
{
  "ErrorMessage": " Could not find a chrome snapshot folder under https://storage.googleapis.com/chromium-browser-snapshots",
  "BuildRetry": false,
  "ExcludeConsoleLog": true
}
```

### Reproduction Steps

Looks like all browser_wasm legs on Linux are failing. For example: https://github.com/dotnet/runtime/pull/85941

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[267679](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267679)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267679/logs/2541)|dotnet/runtime#85858|
|[268023](https://dev.azure.com/dnceng-public/public/_build/results?buildId=268023)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/268023/logs/1372)|dotnet/runtime#85833|
|[268017](https://dev.azure.com/dnceng-public/public/_build/results?buildId=268017)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/268017/logs/1344)|dotnet/runtime#86014|
|[266583](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266583)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266583/logs/1994)|dotnet/runtime#85923|
|[266551](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266551)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266551/logs/1496)|dotnet/runtime#85950|
|[268001](https://dev.azure.com/dnceng-public/public/_build/results?buildId=268001)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/268001/logs/375)|dotnet/runtime#86015|
|[266577](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266577)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266577/logs/1496)|dotnet/runtime#85952|
|[267984](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267984)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267984/logs/831)|dotnet/runtime#85932|
|[267955](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267955)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267955/logs/842)|dotnet/runtime#85918|
|[267966](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267966)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267966/logs/1535)||
|[267900](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267900)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267900/logs/885)|dotnet/runtime#84132|
|[266915](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266915)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266915/logs/2535)|dotnet/runtime#85962|
|[267839](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267839)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267839/logs/643)|dotnet/runtime#86010|
|[267785](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267785)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267785/logs/808)|dotnet/runtime#85117|
|[267807](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267807)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267807/logs/1306)|dotnet/runtime#84864|
|[267802](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267802)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267802/logs/1204)|dotnet/runtime#86007|
|[267769](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267769)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267769/logs/831)|dotnet/runtime#86002|
|[267709](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267709)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267709/logs/1002)|dotnet/runtime#85908|
|[267657](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267657)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267657/logs/1525)|dotnet/runtime#84100|
|[267635](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267635)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267635/logs/1420)|dotnet/runtime#85995|
|[267598](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267598)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267598/logs/1469)|dotnet/runtime#84676|
|[267515](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267515)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267515/logs/658)|dotnet/runtime#85843|
|[267487](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267487)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267487/logs/940)|dotnet/runtime#85796|
|[267421](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267421)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267421/logs/1815)|dotnet/runtime#85978|
|[267420](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267420)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267420/logs/1506)|dotnet/runtime#85833|
|[267351](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267351)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267351/logs/894)|dotnet/runtime#85966|
|[267254](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267254)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267254/logs/1537)|dotnet/runtime#85317|
|[267230](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267230)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267230/logs/1572)|dotnet/runtime#85913|
|[267219](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267219)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267219/logs/1455)|dotnet/runtime#85563|
|[267198](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267198)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267198/logs/1556)|dotnet/runtime#80331|
|[267194](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267194)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267194/logs/1609)|dotnet/runtime#85972|
|[267151](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267151)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267151/logs/846)|dotnet/runtime#85969|
|[267120](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267120)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267120/logs/1532)|dotnet/runtime#85968|
|[267063](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267063)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267063/logs/105)|dotnet/runtime#85730|
|[267059](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267059)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267059/logs/1720)|dotnet/runtime#85730|
|[266769](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266769)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266769/logs/2532)|dotnet/runtime#85938|
|[267024](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267024)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267024/logs/904)|dotnet/runtime#85966|
|[267007](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267007)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267007/logs/566)||
|[266996](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266996)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266996/logs/1521)|dotnet/runtime#85963|
|[266985](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266985)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266985/logs/1678)|dotnet/runtime#85965|
|[266975](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266975)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266975/logs/1761)||
|[266968](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266968)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266968/logs/1096)|dotnet/runtime#85964|
|[266957](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266957)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266957/logs/795)|dotnet/runtime#85301|
|[266952](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266952)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266952/logs/1057)|dotnet/runtime#85528|
|[266948](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266948)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266948/logs/905)|dotnet/runtime#85649|
|[266548](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266548)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266548/logs/2540)|dotnet/runtime#85947|
|[266815](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266815)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266815/logs/1435)|dotnet/runtime#85858|
|[266790](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266790)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266790/logs/1495)|dotnet/runtime#85833|
|[266760](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266760)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266760/logs/1571)|dotnet/runtime#85913|
|[266643](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266643)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266643/logs/1357)|dotnet/runtime#84864|
|[266635](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266635)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266635/logs/1395)|dotnet/runtime#74623|
|[266590](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266590)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266590/logs/580)|dotnet/runtime#85843|
|[266566](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266566)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266566/logs/1072)|dotnet/runtime#85424|
|[266545](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266545)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266545/logs/1433)|dotnet/runtime#85947|
|[266464](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266464)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266464/logs/1399)|dotnet/runtime#85880|
|[266460](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266460)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266460/logs/840)|dotnet/runtime#85941|
|[266421](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266421)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266421/logs/1462)|dotnet/runtime#85938|
|[265623](https://dev.azure.com/dnceng-public/public/_build/results?buildId=265623)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/265623/logs/1374)|dotnet/runtime#85908|
|[266382](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266382)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266382/logs/1423)|dotnet/runtime#85926|
|[266409](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266409)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266409/logs/524)||
|[266368](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266368)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266368/logs/997)|dotnet/runtime#85920|
|[266359](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266359)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266359/logs/1391)|dotnet/runtime#82045|
|[266337](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266337)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266337/logs/1409)|dotnet/runtime#85833|
|[266321](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266321)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/266321/logs/810)|dotnet/runtime#85846|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|21|64|64|

**Comment by lewing** [comment]
This happens sometimes when upstream chrome doesn't produce builds for all platforms, we're looking at options to avoid this causing issues in CI.

**Comment by radical** [comment]
Fixed by https://github.com/dotnet/runtime/pull/86012 .
