### ISSUE TITLE
[android] Mono AOT compiler fails in main/.NET 8 Preview 5

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/runtime#85940]
### Description

I don't get a great error message, but Release Android builds fail with:
```
[UnnamedProject.dll] Exit code: 134
...
/Users/runner/work/1/s/xamarin-android/bin/Release/dotnet/packs/Microsoft.Android.Sdk.Darwin/34.0.0-ci.darc-main-b58cf04b-4873-4f6e-844d-888e4a56e859.282/targets/Microsoft.Android.Sdk.Aot.targets(109,5): Precompiling failed for /Users/runner/work/1/a/TestRelease/05-08_13.21.40/temp/BuildAot AndÜmläüts_armeabiv7aarm64v8ax86x8664_True_False/obj/Release/android-x86/linked/UnnamedProject.dll with exit code 134.
Mono Ahead of Time compiler - compiling assembly /Users/runner/work/1/a/TestRelease/05-08_13.21.40/temp/BuildAot AndÜmläüts_armeabiv7aarm64v8ax86x8664_True_False/obj/Release/android-x86/linked/UnnamedProject.dll
AOTID 4E821B6F-731B-5E01-65C2-A7B17F9F4CC0
opcode 940 load_gotaddr [/Users/runner/work/1/a/TestRelease/05-08_13.21.40/temp/BuildAot AndÜmläüts_armeabiv7aarm64v8ax86x8664_True_False/UnnamedProject.csproj]
```

Log: [build.zip](https://github.com/dotnet/runtime/files/11425280/build.zip)

### Reproduction Steps

Likely just:
* `dotnet new android`
* `dotnet build -c Release`
But I pull logs from failing integration tests.

### Expected behavior

AOT compiler succeeds

### Actual behavior

AOT compiler fails

### Regression?

Yes

### Known Workarounds

Set `RunAOTCompilation=false`, but customers rely on this feature for fast startup times.

### Configuration

This was discovered in code flow:
* https://github.com/xamarin/xamarin-android/pull/8018
* https://github.com/dotnet/runtime/compare/9a7db5556f...bc9dad2351

**Comment by vargaz** [comment]
https://github.com/dotnet/runtime/pull/85950

**Comment by jonathanpeppers** [comment]
@vargaz thanks, this appears to be working now.

I'll be able to merge this one shortly: https://github.com/xamarin/xamarin-android/pull/8018
