### ISSUE TITLE
How to set DateTimeFormat.ShortTimePattern by Environment variables

### ISSUE THREAD

**Issue by SpringHgui** [dotnet/runtime#85973]
# my Code
```c#
static void Main(string[] args)
{
    CultureInfo culture = CultureInfo.CurrentCulture;

    Console.WriteLine($"{culture.Name} {culture.DateTimeFormat.ShortTimePattern}");
    Console.WriteLine("Now: " + DateTime.Now.ToString());
    Console.ReadLine();
}

```

# run on windows

![image](https://github.com/dotnet/runtime/assets/22363718/4ea9f50d-99fb-4a06-877c-c8b41c77e098)

# run on linux by docker
Dockerfile
```dockerfile
FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["ConsoleApp2/ConsoleApp2.csproj", "ConsoleApp2/"]
RUN dotnet restore "ConsoleApp2/ConsoleApp2.csproj"
COPY . .
WORKDIR "/src/ConsoleApp2"
RUN dotnet build "ConsoleApp2.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ConsoleApp2.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final

ENV TZ=Asia/Shanghai
ENV LANG=zh_CN.UTF-8

WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ConsoleApp2.dll"]
```
- result:
![image](https://github.com/dotnet/runtime/assets/22363718/85273225-42b0-4e0e-8ecd-9a3b58be51d7)

# I want

this line print same format，by set Environment variables，
```
Console.WriteLine("Now: " + DateTime.Now.ToString());
```

thanks~~~

**Comment by Clockwork-Muse** [comment]
Your application shouldn't be overriding the built-in culture formats (or almost never).

If you need a specific format for data interchange with an API, you should be using the `InvariantCulture` and explicitly using the ISO/Roundtrip format (the `O`/`o` [format specifier](https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings)).

If this is user-facing data, the formats should be a user-specified format, which may not be what you expect (there are a number of ways to override formats as appropriate).

Perhaps you can give more details as to what you feel you need to accomplish?

**Comment by huoyaoyuan** [comment]
Programmatically construct and set a `CultureInfo` instance would be the best approach. The globalization settings aren't read from environment variables.

**Comment by SpringHgui** [comment]
thanks
