### ISSUE TITLE
Wasm perf runs are completely broken due to recent changes

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#86001]
This has been broken since May 8, like https://dev.azure.com/dnceng/internal/_build/results?buildId=2176141&view=results .

```
+ python3 -m pip install --user -U pip
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  from cryptography.utils import int_from_bytes
Requirement already satisfied: pip in /home/helixbot/.local/lib/python3.6/site-packages (21.3.1)
/home/helixbot/work/910D07D6/p/scripts/266ab3989f774d4394cd56c66eb23ada/execute.sh: 6: /home/helixbot/work/910D07D6/p/scripts/266ab3989f774d4394cd56c66eb23ada/execute.sh: cannot open 2: No such file
+ pip3 install urllib3
```

This seems to be broken since https://github.com/dotnet/runtime/pull/85915 .
cc @LoopedBard3 @kotlarmilos @lewing 

### Known Issue Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "BuildRetry": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by LoopedBard3** [comment]
That latest update b92c1d2 seems to have fixed the prereq install issues. Waiting for the run to finish to see if there are any downstream issues.

**Comment by LoopedBard3** [comment]
Added tracking specific for the iOS scenarios to this issue: https://github.com/dotnet/performance/issues/3010. This should allow us to close this issue if there are no more broken WASM runs that I am missing, the main ones appear to be fixed.

**Comment by kotlarmilos** [comment]
@radical I suggest we close this issue as the issue has been fixed.
