### ISSUE TITLE
Inconsistent date and time patterns

### ISSUE THREAD

**Issue by h15ter** [dotnet/runtime#86017]
### Description

Hi Guys,

I'm migrating an old netfx app to netcore, and I'm running the following simple test code for dates (in both Framework 4.7.2 and .NET 6.0):
```
var cultures = new[]
{
    "en-US",
    "de-DE",
    "ar-AR",
    "ru-RU"
};

var date = new DateTime(2022, 12, 23, 2, 35, 0);

foreach (var culture in cultures)
{
    var cultureInfo = new CultureInfo(culture, false);
    var dateTimeFormat = cultureInfo.DateTimeFormat;
    Console.WriteLine("  {0}     {1}    {2}", 
        culture, 
        dateTimeFormat.FullDateTimePattern, 
        date.ToString("F", cultureInfo));
}
```
Apparently formats for Arabic and Russian are not the same on Windows and Linux, so my first idea was that I have to tweak regional settings.
But then I executed the same code on two Win2019 and Win10 machines with the same default datetime regional settings, and I still see the difference. In fact, netfx version gives the same consistent result, but netcore version doesn't. See attached screenshots for details.
How do I make date and time patterns consistent?

![win10_netcore](https://github.com/dotnet/runtime/assets/5887224/33ab2b61-62fa-43d4-931b-a793330c9005)
![win2019_netcore](https://github.com/dotnet/runtime/assets/5887224/c1b7c981-e586-4cb7-a99f-b0b4a626842f)
![win10_netfx](https://github.com/dotnet/runtime/assets/5887224/1467ff9e-6908-4efd-a96d-d752c35b9c54)
![win2019_netfx](https://github.com/dotnet/runtime/assets/5887224/5bfd1dbb-cd67-48ce-8423-48058eaf569e)

Thanks!

### Reproduction Steps

Run the following code on different OS (win2019, win10, linux):
```
var cultures = new[]
{
    "en-US",
    "de-DE",
    "ar-AR",
    "ru-RU"
};

var date = new DateTime(2022, 12, 23, 2, 35, 0);

foreach (var culture in cultures)
{
    var cultureInfo = new CultureInfo(culture, false);
    var dateTimeFormat = cultureInfo.DateTimeFormat;
    Console.WriteLine("  {0}     {1}    {2}", 
        culture, 
        dateTimeFormat.FullDateTimePattern, 
        date.ToString("F", cultureInfo));
}
```

### Expected behavior

The following properties should return the same values on different OS (or should adhere regional date setting at least):
`CultureInfo.DateTimeFormat.LongDatePattern`
`CultureInfo.DateTimeFormat.LongTimePattern`
`CultureInfo.DateTimeFormat.FullDateTimePattern`

### Actual behavior

Date and time patterns are different on two different Windows machines using default regional date/time settings, also different on Linux.

### Regression?

Yes
.NET Framework 4.7.2 -> .NET 6.0

### Known Workarounds

workaround is welcome :)

### Configuration

Windows2019, Windows10, Ubuntu
.NET Framework 4.7.2, .NET 6.0

**Comment by Clockwork-Muse** [comment]
This is because recent versions of .NET Core [use the ICU](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#icu-on-windows).  That article gives some workarounds.

The better question is, _why_ are you trying to ensure consistent formats?  Normally you should simply use the formats given to you from the OS, especially because on consumer machines they are various ways to present/use customized formats that they would prefer.

**Comment by tarekgh** [comment]
@h15ter I am closing this issue but feel free to send any question if you still have any.

**Comment by h15ter** [comment]
> This is because recent versions of .NET Core [use the ICU](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#icu-on-windows). That article gives some workarounds.

Thanks!

> The better question is, _why_ are you trying to ensure consistent formats? Normally you should simply use the formats given to you from the OS, especially because on consumer machines they are various ways to present/use customized formats that they would prefer.

I don't really get your point about  "simply use formats given from the OS" - my OS clearly has the desired settings, the problem is that netcore ignores them and uses something totally different.

![win10_settings](https://github.com/dotnet/runtime/assets/5887224/8b48616e-5529-45cb-8c12-b7d56ab3ecbb)
![win10_netcore](https://github.com/dotnet/runtime/assets/5887224/8861bab8-29ba-427f-8483-b941307b36d3)

**Comment by tarekgh** [comment]
> my OS clearly has the desired settings, the problem is that netcore ignores them and uses something totally different.

This is not true. This happen because you are passing `false` for the user overrides in the call 

```C#
 var cultureInfo = new CultureInfo(culture, false);
 ```

pass `true instead and this should pick your user settings.

**Comment by h15ter** [comment]
@tarekgh 
> This is not true. This happen because you are passing `false` for the user overrides in the call
> pass `true` instead and this should pick your user settings.

No, that doesn't work. 
Maybe if I had some explicit overrides, that would work. But I don't have any overrides - I use the default datetime settings for the locale, as they are provided by OS (you can see them on the screenshot), and they are not respected, no matter if I pass `false` or `true` as the second parameter.

![Capture](https://github.com/dotnet/runtime/assets/5887224/d697f22e-41bb-4649-a509-dfd1ce044a09)

**Comment by Clockwork-Muse** [comment]
> I don't really get your point about "simply use formats given from the OS" - my OS clearly has the desired settings, the problem is that netcore ignores them and uses something totally different.

Sorry, I guess I'm a little too used to some of the other culture-related questions we get.
That said:

> The following properties should return the same values on different OS

This will never be guaranteed.  Setting aside what you're experiencing here, different OSs will have different versions of the ICU library/datafiles (they update multiple times a year), which means they're going to report different formats.  Windows, currently, tends to lag ICU updates more than most Linux distros (which may not have it installed in some cases - docker containers especially).

> No, that doesn't work.

... maybe it needs to be your current culture?
Or, since that appears to be the old Control Panel region window, maybe that only displays the NLS data, and not the ICU data?  (Dunno, just spitballing here).

**Comment by h15ter** [comment]
> This will never be guaranteed. Setting aside what you're experiencing here, different OSs will have different versions of the ICU library/datafiles (they update multiple times a year), which means they're going to report different formats. Windows, currently, tends to lag ICU updates more than most Linux distros (which may not have it installed in some cases - docker containers especially).

From a user perspective, netcore i11n should report either formats configured in OS, or some consistent defaults, otherwise the whole thing makes little sense. As you can see from my screenshots above, neither is the case: two windows versions (not even linux yet!), same locale settings => different results. Please don't tell me that's "as designed" :)
 
> ... maybe it needs to be your current culture? 

This doesn't sound right, but I also tried that - doesn't work.

> Or, since that appears to be the old Control Panel region window, maybe that only displays the NLS data, and not the ICU data? 

New date format dialog in win10 reports the same settings as the old one.

![Capture](https://github.com/dotnet/runtime/assets/5887224/9525e422-1004-429a-82b8-41c0ba263a40)

**Comment by tarekgh** [comment]
> Maybe if I had some explicit overrides, that would work. But I don't have any overrides - I use the default datetime settings for the locale, as they are provided by OS (you can see them on the screenshot), and they are not respected, no matter if I pass false or true as the second parameter.

You are mixing 2 issues here. First, when running .NET Framework, the globalization data is picked from NLS. It happened there that the culture data is same as the user overrides you have in the settings. This is why either using `true` or `false` for the user overrides you don't notice any change. 
If you are running on .NET 6, the globalization data comes from ICU which is possible to be different than NLS data. This means, if using `false` for the user overrides you'll get the data from ICU. If you use `true` you will pick the user overrides from the settings. I hope this clarifies the behavior.

**Comment by tarekgh** [comment]
@h15ter I tried teh following on my machine and I am seeing it work as expected:

```C#
            Console.WriteLine($"`{CultureInfo.CurrentCulture}` ");
            CultureInfo ci = new CultureInfo("ru-RU", true);
            Console.WriteLine($"With User Overrides: `{ci.DateTimeFormat.ShortDatePattern}` `{ci.DateTimeFormat.ShortTimePattern}`  `{ci.DateTimeFormat.LongDatePattern}`  `{ci.DateTimeFormat.LongTimePattern}` ");

            ci = new CultureInfo("ru-RU", false);
            Console.WriteLine($"Without User Overrides: `{ci.DateTimeFormat.ShortDatePattern}` `{ci.DateTimeFormat.ShortTimePattern}`  `{ci.DateTimeFormat.LongDatePattern}`  `{ci.DateTimeFormat.LongTimePattern}` ");
```

producing 

```
`ru-RU`
With User Overrides: `dd.MM.yyyy` `H:mm`  `d MMMM yyyy 'г.'`  `H:mm:ss` 
Without User Overrides: `dd.MM.yyyy` `HH:mm`  `dddd, d MMMM yyyy 'г'.`  `HH:mm:ss`
```

![image](https://github.com/dotnet/runtime/assets/10833894/97589229-f999-4017-abb2-c9317d11d191)

**Comment by Clockwork-Muse** [comment]
> But if you mean to set the culture as the current culture of the OS - that, surprisingly, works.

Yes, that's what I meant.

> But that's not the solution obviously (not for multi-user/multi-culture apps), so I'm even more convinced now that's a bug.

If you want a more controlled ICU experience for a server/set of servers, you'd want to install an app-local ICU.  That's assuming your server actually needs to deal with culture, which isn't necessarily a given.
For client computers, it's immaterial (since the settings for their local culture will be used).
