### ISSUE TITLE
PreserializedResourceWriterTests.TestResourceManagerIsSafeForConcurrentAccessAndEnumeration test failure

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#86013]
```
  Discovering: System.Resources.Extensions.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Resources.Extensions.Tests (found 26 test cases)
  Starting:    System.Resources.Extensions.Tests (parallel test collections = on, max threads = 2)
    System.Resources.Extensions.Tests.PreserializedResourceWriterTests.TestResourceManagerIsSafeForConcurrentAccessAndEnumeration(useEnumeratorEntry: False) [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/System.Resources.Extensions/tests/BinaryResourceWriterUnitTest.cs(531,0): at System.Resources.Extensions.Tests.PreserializedResourceWriterTests.TestResourceManagerIsSafeForConcurrentAccessAndEnumeration(Boolean useEnumeratorEntry)
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs(59,0): at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
  Finished:    System.Resources.Extensions.Tests
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=266915
Build error leg or test failing: System.Resources.Extensions.Tests.PreserializedResourceWriterTests.TestResourceManagerIsSafeForConcurrentAccessAndEnumeration
Pull request: https://github.com/dotnet/runtime/pull/85962

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "System.Resources.Extensions.Tests.PreserializedResourceWriterTests.TestResourceManagerIsSafeForConcurrentAccessAndEnumeration",
  "BuildRetry": true,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[270335](https://dev.azure.com/dnceng-public/public/_build/results?buildId=270335)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/270335/logs/2442)|dotnet/runtime#86091|

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[284189](https://dev.azure.com/dnceng-public/public/_build/results?buildId=284189)|dotnet/runtime|[System.Resources.Extensions.Tests.PreserializedResourceWriterTests.TestResourceManagerIsSafeForConcurrentAccessAndEnumeration](https://dev.azure.com/dnceng-public/public/_build/results?buildId=284189&view=ms.vss-test-web.build-test-results-tab&runId=5657046&resultId=171475)|dotnet/runtime#86674|
|[282666](https://dev.azure.com/dnceng-public/public/_build/results?buildId=282666)|dotnet/runtime|[System.Resources.Extensions.Tests.PreserializedResourceWriterTests.TestResourceManagerIsSafeForConcurrentAccessAndEnumeration](https://dev.azure.com/dnceng-public/public/_build/results?buildId=282666&view=ms.vss-test-web.build-test-results-tab&runId=5623736&resultId=180051)|dotnet/runtime#86567|
|[282482](https://dev.azure.com/dnceng-public/public/_build/results?buildId=282482)|dotnet/runtime|[System.Resources.Extensions.Tests.PreserializedResourceWriterTests.TestResourceManagerIsSafeForConcurrentAccessAndEnumeration](https://dev.azure.com/dnceng-public/public/_build/results?buildId=282482&view=ms.vss-test-web.build-test-results-tab&runId=5619288&resultId=168736)||
|[276887](https://dev.azure.com/dnceng-public/public/_build/results?buildId=276887)|dotnet/runtime|[System.Resources.Extensions.Tests.PreserializedResourceWriterTests.TestResourceManagerIsSafeForConcurrentAccessAndEnumeration](https://dev.azure.com/dnceng-public/public/_build/results?buildId=276887&view=ms.vss-test-web.build-test-results-tab&runId=5490872&resultId=175853)|dotnet/runtime#86151|
|[276622](https://dev.azure.com/dnceng-public/public/_build/results?buildId=276622)|dotnet/runtime|[System.Resources.Extensions.Tests.PreserializedResourceWriterTests.TestResourceManagerIsSafeForConcurrentAccessAndEnumeration](https://dev.azure.com/dnceng-public/public/_build/results?buildId=276622&view=ms.vss-test-web.build-test-results-tab&runId=5481744&resultId=180825)|dotnet/runtime#85965|
|[274034](https://dev.azure.com/dnceng-public/public/_build/results?buildId=274034)|dotnet/runtime|[System.Resources.Extensions.Tests.PreserializedResourceWriterTests.TestResourceManagerIsSafeForConcurrentAccessAndEnumeration](https://dev.azure.com/dnceng-public/public/_build/results?buildId=274034&view=ms.vss-test-web.build-test-results-tab&runId=5419910&resultId=176198)|dotnet/runtime#86252|
|[272903](https://dev.azure.com/dnceng-public/public/_build/results?buildId=272903)|dotnet/runtime|[System.Resources.Extensions.Tests.PreserializedResourceWriterTests.TestResourceManagerIsSafeForConcurrentAccessAndEnumeration](https://dev.azure.com/dnceng-public/public/_build/results?buildId=272903&view=ms.vss-test-web.build-test-results-tab&runId=5390704&resultId=182553)|dotnet/runtime#86210|
|[270987](https://dev.azure.com/dnceng-public/public/_build/results?buildId=270987)|dotnet/runtime|[System.Resources.Extensions.Tests.PreserializedResourceWriterTests.TestResourceManagerIsSafeForConcurrentAccessAndEnumeration](https://dev.azure.com/dnceng-public/public/_build/results?buildId=270987&view=ms.vss-test-web.build-test-results-tab&runId=5345500&resultId=114494)|dotnet/runtime#84384|
|[270027](https://dev.azure.com/dnceng-public/public/_build/results?buildId=270027)|dotnet/runtime|[System.Resources.Extensions.Tests.PreserializedResourceWriterTests.TestResourceManagerIsSafeForConcurrentAccessAndEnumeration](https://dev.azure.com/dnceng-public/public/_build/results?buildId=270027&view=ms.vss-test-web.build-test-results-tab&runId=5323996&resultId=179850)|dotnet/runtime#86074|
|[269251](https://dev.azure.com/dnceng-public/public/_build/results?buildId=269251)|dotnet/runtime|[System.Resources.Extensions.Tests.PreserializedResourceWriterTests.TestResourceManagerIsSafeForConcurrentAccessAndEnumeration](https://dev.azure.com/dnceng-public/public/_build/results?buildId=269251&view=ms.vss-test-web.build-test-results-tab&runId=5310246&resultId=172916)|dotnet/runtime#85843|
|[268707](https://dev.azure.com/dnceng-public/public/_build/results?buildId=268707)|dotnet/runtime|[System.Resources.Extensions.Tests.PreserializedResourceWriterTests.TestResourceManagerIsSafeForConcurrentAccessAndEnumeration](https://dev.azure.com/dnceng-public/public/_build/results?buildId=268707&view=ms.vss-test-web.build-test-results-tab&runId=5294538&resultId=114486)|dotnet/runtime#85317|
|[266915](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266915)|dotnet/runtime|[System.Resources.Extensions.Tests.PreserializedResourceWriterTests.TestResourceManagerIsSafeForConcurrentAccessAndEnumeration](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266915&view=ms.vss-test-web.build-test-results-tab&runId=5255108&resultId=167911)|dotnet/runtime#85962|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|3|13|

**Comment by buyaa-n** [comment]
Related to https://github.com/dotnet/runtime/pull/75054 CC: @madelson the test still fails occasionally

**Comment by madelson** [comment]
@buyaa-n I assume we're hitting timeouts/contention? Do you think it would help to use `TaskCreationOptions.LongRunning` when creating the threads [here](https://github.com/dotnet/runtime/blob/27d000943852c85ab0756e85c69aed370ae254d6/src/libraries/System.Resources.Extensions/tests/BinaryResourceWriterUnitTest.cs#L529)?

We could also increase the timeout even more than what it currently is.

**Comment by buyaa-n** [comment]
> I assume we're hitting timeouts/contention? 

Yes

> Do you think it would help to use TaskCreationOptions.LongRunning when creating the threads [here](https://github.com/dotnet/runtime/blob/27d000943852c85ab0756e85c69aed370ae254d6/src/libraries/System.Resources.Extensions/tests/BinaryResourceWriterUnitTest.cs#L529)?

That was actually suggested [previously](https://github.com/dotnet/runtime/pull/75054#discussion_r1044541614) and apparently you applied the suggestion only to `ResourceManagerTests.cs` https://github.com/dotnet/runtime/blob/ce689d9189d549e249f4bb5e3d9aeef322464bfb/src/libraries/System.Resources.ResourceManager/tests/ResourceManagerTests.cs#L262-L266
Please apply the suggestion to this test too, thanks!
