### ISSUE TITLE
System.Text.Json deserialisation does not respect "required" keyword when used in base class

### ISSUE THREAD

**Issue by stedaho** [dotnet/runtime#86031]
### Description

When I use System.Text.Json to deserialise to a class which derives from a base class using `required` keyword in a property, the keyword has no effect.

### Reproduction Steps

Code snippet showing the unexpected behavior (case 1) and also a working example (case 2):
```csharp
using System;
using System.Text.Json;

public class Program
{
	public static void Main()
	{
		// Problematic test case
		Console.WriteLine("Case 1: Derived class");
		try
		{
			var obj = JsonSerializer.Deserialize("{}", typeof(DerivedTestClass));
			Console.WriteLine("obj: " + obj.ToString());
		}
		catch (JsonException e)
		{
			// Is not been thrown
			Console.WriteLine(e.Message);
		}

		// Second test case for reference
		Console.WriteLine("\nCase 2: Base class");
		try
		{
			var obj = JsonSerializer.Deserialize("{}", typeof(TestClass));
			Console.WriteLine("obj: " + obj.ToString());
		}
		catch (JsonException e)
		{
			// Is thrown as expected
			Console.WriteLine(e.Message);
		}
	}

	private class TestClass
	{
		public required string StringValue { get; set; }
		public required int IntegerValue { get; set; }
	}

	private class DerivedTestClass : TestClass
	{
		public override string ToString()
		{
			return $"StringValue: '{StringValue}', IntegerValue: '{IntegerValue}'";
		}
	}
}
```

### Expected behavior

`JsonSerializer.Deserialize` should throw a `JsonException` for the required (and not set) properties.

### Actual behavior

The deserialised class is instantiated with default values for the properties.

### Regression?

Not applicable, new feature in .NET 7

### Known Workarounds

The example works as expected when I used the `[JsonRequired]` attribute instead of the `required` keyword.

### Configuration

.NET 7.0.5
Also on local machine (windows, x64) and in .NET Fiddle: https://dotnetfiddle.net/ffvMGn

**Comment by eiriktsarpalis** [comment]
I should add that the issue only impacts the reflection serializer, it works as expected if you try the same repro in the source generator.
