### ISSUE TITLE
[API Proposal]: 

### ISSUE THREAD

**Issue by Artromskiy** [dotnet/runtime#86067]
### Background and motivation

Graphic APIs often use various data sets that need to be processed before use. For example, in open gl for batching, several vertex arrays and several index arrays from different models are combined. Initially, indexes are tied to each model and unite them into triangles. Accordingly, each model has a certain set (1,2,3,2,3,4). After combining the models into one buffer, each such array of indices must be offset by n from the previous one in order to draw the corresponding vertices. That is, several arrays (1,2,3,2,3,4),(1,2,3,2,3,4),(1,2,3,2,3,4) will turn into one (1 ,2,3,2,3,4, 5,6,7,6,7,8, 9,10,11,10,11,12) I would like to do such operations without iterating over the array, for example, using Vector<T> It has methods like Add(Vector<T> left, Vector<T> rigth) but there's no methods with semantics (Vector<T> left, T right).

### API Proposal

```csharp
namespace System.Collections.Generic;

    public static unsafe partial class Vector
{
    public void Add(Vector<T> left, T right);
}
```

### API Usage

```csharp

private void GenerateIndices(List<Mesh> meshes, Span<uint> indices)
{
            uint indexOffset = 0;

            // Enumerating meshes
            for (int i = 0; i < meshes.Count; i++)
            {
                var mesh = meshes[i];
               // Creating Vector of current indices of mesh
                Vector<uint> indicesVec = new Vector<uint>(mesh.indices.Span);

                // Adding offset based on how many vertices already added by previos meshes
                indicesVec = Vector.Add(indicesVec, indexOffset);

               // Setting indices with offset
                indicesVec.CopyTo(indices);

                // Adding offset of this mesh
                indexOffset += (uint)mesh.VerticesLength;
            }
}
```

**Comment by tannergooding** [comment]
You would do: `Vector vIndexOffset = new Vector(indexOffset);` outside the loop and then in the loop do `Vector.Add(indicesVec, vIndexOffset);` (or `indicesVec + vIndexOffset`).

Platforms don't typically provide acceleration for `vector + scalar` and so we don't provide it and encourage users to write the better pattern themselves directly.

The same code would also work for `Vector128<T>`, `Vector256<T>`, or `Vector512<T>`.
