### ISSUE TITLE
Support HttpClientHandler.Proxy on iOS

### ISSUE THREAD

**Issue by ChristopherStephan** [dotnet/runtime#86061]
### Description

A `System.PlatformNotSupportedException` is thrown on iOS when setting the `Proxy` property on a `HttpClientHandler`:

```
var proxy = new WebProxy("http://proxyserver:80/", true);
HttpClientHandler handler = new HttpClientHandler() { Proxy = proxy };
```

Are there any plans supporting the `Proxy` property for the `HttpClientHandler`? With Xamarin this worked for us. Maybe this request relates to https://github.com/xamarin/xamarin-macios/issues/14632 and https://github.com/dotnet/maui/issues/2028.

### Public API Changes

`new HttpClientHandler() { Proxy = proxy };` does not throw 

### Intended Use-Case

I want to use a proxy.

**Comment by rolfbjarne** [comment]
> Maybe this request relates to [xamarin/xamarin-macios#14632](https://github.com/xamarin/xamarin-macios/issues/14632) and #2028.

Yes, this is really a duplicate of https://github.com/xamarin/xamarin-macios/issues/14632.
