### ISSUE TITLE
Extent of reflection-related impact around function pointers?

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#86063]
https://learn.microsoft.com/en-us/dotnet/core/compatibility/reflection/8.0/function-pointer-reflection calls out that:

> a function pointer type is now a [System.Type](https://learn.microsoft.com/en-us/dotnet/api/system.type) instance with new capabilities such as [Type.IsFunctionPointer](https://learn.microsoft.com/en-us/dotnet/api/system.type.isfunctionpointer#system-type-isfunctionpointer). Previously, the [System.Type](https://learn.microsoft.com/en-us/dotnet/api/system.type) instance returned was the [IntPtr](https://learn.microsoft.com/en-us/dotnet/api/system.intptr) type.

But it also states:

> A function pointer instance, which is a physical address to a function, continues to be represented as an [IntPtr](https://learn.microsoft.com/en-us/dotnet/api/system.intptr); only the reflection type has changed.

Based on that, I would assume I should still be able to pass an IntPtr instance to a method that accepts a function pointer, but that doesn't work.  Consider this repro:
```C#
using System.Reflection;

internal class Program
{
    static unsafe void Main()
    {
        MethodInfo m = typeof(Program).GetMethod("Foo")!;
        m.Invoke(null, new object[] { IntPtr.Zero });
    }

    public static unsafe void Foo(delegate* managed<Program> ptr) { }
}
```
That runs to completion on .NET 7.  On .NET 8, it fails with:
```
Unhandled exception. System.ArgumentException: Object of type 'System.IntPtr' cannot be converted to type 'Program()'.
   at System.RuntimeType.CheckValue(Object& value, ParameterCopyBackAction& copyBack, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Span`1 copyOfParameters, IntPtr* byrefParameters, Span`1 shouldCopyBack, ReadOnlySpan`1 parameters, RuntimeType[] sigTypes, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Program.Main()
```
Is that expected?  If it is expected, we might just want to flesh out the breaking change docs a bit more.

This came up while investigating an application using Newtonsoft.Json v13.0.1, which breaks due to the overall function-pointer-related reflection changes.  Changes in Newtonsoft.Json in 13.0.3 resolve those breaks.

**Comment by EgorBo** [comment]
Isn't that an intentional breaking change? https://learn.microsoft.com/en-us/dotnet/core/compatibility/reflection/8.0/function-pointer-reflection

**Comment by MichalStrehovsky** [comment]
Dup of #85028?

**Comment by stephentoub** [comment]
Yup, looks like it, just with different context.
