### ISSUE TITLE
Official build fails due to missing windows_arm job

### ISSUE THREAD

**Issue by sbomer** [dotnet/runtime#86073]
Official builds have started failing with:

```
workloadsbuild depends on unknown job installer__coreclr__windows_arm_Release_.
```

See for example https://dev.azure.com/dnceng/internal/_build/results?buildId=2178029&view=results. I believe caused by https://github.com/dotnet/runtime/pull/85947. @BruceForstall

Probably we need to at least remove the arm dependencies from
https://github.com/dotnet/runtime/blob/11e22cebdf2e76795be088d12830eed767367d51/eng/pipelines/runtime-official.yml#L527 and
https://github.com/dotnet/runtime/blob/11e22cebdf2e76795be088d12830eed767367d51/eng/pipelines/mono/templates/workloads-build.yml#L75

**Comment by BruceForstall** [comment]
Looks like the official build is failing in the `Build crossdac publishing` step:

```
D:\a\_work\1\s\.packages\microsoft.dotnet.build.tasks.packaging\8.0.0-beta.23259.5\build\Packaging.targets(1264,5): error : Error when creating nuget lib package from D:\a\_work\1\s\artifacts\packages\Release\specs\runtime.linux-musl-arm.Microsoft.CrossOsDiag.Private.CoreCLR.nuspec. NuGet.Packaging.Core.PackagingException: File not found: 'D:\a\_work\1\s\artifacts\CoreCLRCrossDacArtifacts\CoreCLRCrossDacArtifacts\linux_musl.arm.Release\x86\mscordaccore.pdb'. [D:\a\_work\1\s\src\coreclr\.nuget\Microsoft.CrossOsDiag.Private.CoreCLR\Microsoft.CrossOsDiag.Private.CoreCLR.pkgproj]
D:\a\_work\1\s\.packages\microsoft.dotnet.build.tasks.packaging\8.0.0-beta.23259.5\build\Packaging.targets(1264,5): error :    at NuGet.Packaging.PackageBuilder.AddFiles(String basePath, String source, String destination, String exclude) [D:\a\_work\1\s\src\coreclr\.nuget\Microsoft.CrossOsDiag.Private.CoreCLR\Microsoft.CrossOsDiag.Private.CoreCLR.pkgproj]
D:\a\_work\1\s\.packages\microsoft.dotnet.build.tasks.packaging\8.0.0-beta.23259.5\build\Packaging.targets(1264,5): error :    at NuGet.Packaging.PackageBuilder.PopulateFiles(String basePath, IEnumerable`1 files) [D:\a\_work\1\s\src\coreclr\.nuget\Microsoft.CrossOsDiag.Private.CoreCLR\Microsoft.CrossOsDiag.Private.CoreCLR.pkgproj]
D:\a\_work\1\s\.packages\microsoft.dotnet.build.tasks.packaging\8.0.0-beta.23259.5\build\Packaging.targets(1264,5): error :    at Microsoft.DotNet.Build.Tasks.Packaging.NuGetPack.Pack(String nuspecPath, String nupkgPath, Manifest manifest, Boolean packSymbols) in /_/src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetPack.cs:line 261 [D:\a\_work\1\s\src\coreclr\.nuget\Microsoft.CrossOsDiag.Private.CoreCLR\Microsoft.CrossOsDiag.Private.CoreCLR.pkgproj]
D:\a\_work\1\s\.packages\microsoft.dotnet.build.tasks.packaging\8.0.0-beta.23259.5\build\Packaging.targets(1264,5): error : Error when creating nuget lib package from D:\a\_work\1\s\artifacts\packages\Release\specs\runtime.linux-arm.Microsoft.CrossOsDiag.Private.CoreCLR.nuspec. NuGet.Packaging.Core.PackagingException: File not found: 'D:\a\_work\1\s\artifacts\CoreCLRCrossDacArtifacts\CoreCLRCrossDacArtifacts\linux.arm.Release\x86\mscordaccore.pdb'. [D:\a\_work\1\s\src\coreclr\.nuget\Microsoft.CrossOsDiag.Private.CoreCLR\Microsoft.CrossOsDiag.Private.CoreCLR.pkgproj]
D:\a\_work\1\s\.packages\microsoft.dotnet.build.tasks.packaging\8.0.0-beta.23259.5\build\Packaging.targets(1264,5): error :    at NuGet.Packaging.PackageBuilder.AddFiles(String basePath, String source, String destination, String exclude) [D:\a\_work\1\s\src\coreclr\.nuget\Microsoft.CrossOsDiag.Private.CoreCLR\Microsoft.CrossOsDiag.Private.CoreCLR.pkgproj]
D:\a\_work\1\s\.packages\microsoft.dotnet.build.tasks.packaging\8.0.0-beta.23259.5\build\Packaging.targets(1264,5): error :    at NuGet.Packaging.PackageBuilder.PopulateFiles(String basePath, IEnumerable`1 files) [D:\a\_work\1\s\src\coreclr\.nuget\Microsoft.CrossOsDiag.Private.CoreCLR\Microsoft.CrossOsDiag.Private.CoreCLR.pkgproj]
D:\a\_work\1\s\.packages\microsoft.dotnet.build.tasks.packaging\8.0.0-beta.23259.5\build\Packaging.targets(1264,5): error :    at Microsoft.DotNet.Build.Tasks.Packaging.NuGetPack.Pack(String nuspecPath, String nupkgPath, Manifest manifest, Boolean packSymbols) in /_/src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetPack.cs:line 261 [D:\a\_work\1\s\src\coreclr\.nuget\Microsoft.CrossOsDiag.Private.CoreCLR\Microsoft.CrossOsDiag.Private.CoreCLR.pkgproj]
##[error].packages\microsoft.dotnet.build.tasks.packaging\8.0.0-beta.23259.5\build\Packaging.targets(1264,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Error when creating nuget lib package from D:\a\_work\1\s\artifacts\packages\Release\specs\runtime.linux-musl-arm.Microsoft.CrossOsDiag.Private.CoreCLR.nuspec. NuGet.Packaging.Core.PackagingException: File not found: 'D:\a\_work\1\s\artifacts\CoreCLRCrossDacArtifacts\CoreCLRCrossDacArtifacts\linux_musl.arm.Release\x86\mscordaccore.pdb'.
```

@sbomer @jkotas @jkoritzinsky Anyone know how this works? @jkotas Maybe the linux-arm cross-dac build was inadvertently removed?

**Comment by BruceForstall** [comment]
@noahfalk @tommcdon @mikem8361 Is the linux arm crossdac owned by you? We've been removing Windows arm (builds and code) and it appears linux-arm crossdac builds were a casualty. How do we bring it back without bringing back Windows arm builds?

**Comment by mikem8361** [comment]
@hoyosjs would know how.

**Comment by hoyosjs** [comment]
The linux crossbuild was done from the arm leg as the crosscomponents built the x86 -> arm DAC and DBI. Maybe we could fold that into the x86 leg (Do we have a windows jit targetting linux-arm? Is it built there?).

**Comment by BruceForstall** [comment]
> (Do we have a windows jit targetting linux-arm? Is it built there?)

The win-x86 build creates clrjit_universal_arm_x86.dll, which is a JIT that runs on win-x86 and targets any arm32 OS.

The win-x64 build creates clrjit_universal_arm_x64.dll, which is a JIT that runs on win-x64 and targets any arm32 OS.

**Comment by hoyosjs** [comment]
We don't support win-arm targeting linux-arm, so folding the arm crossdac to the linux build is completely OK to me.

**Comment by BruceForstall** [comment]
Where and how is that build done? What needs to change?

**Comment by ericstj** [comment]
@hoyosjs is the expert, but it might be here:
https://github.com/dotnet/runtime/blob/3bd383212013439c27097339031e48091ac74a3a/eng/pipelines/coreclr/templates/crossdac-build.yml#L11-L15

Looks like that's invoked once for the same archType as the outer build.  Maybe we need to add an additional call for whatever arch we want to use to add the arm build to?

**Comment by BruceForstall** [comment]
I'm inclined to revert https://github.com/dotnet/runtime/pull/85947, https://github.com/dotnet/runtime/pull/86074, https://github.com/dotnet/runtime/pull/86065 to fix the build.

My goal was to stop running tests in the CI on win-arm; I don't want to spend time pulling all the threads to completely remove win-arm support across all repos.

**Comment by jkotas** [comment]
#86138 should fix the official build

**Comment by BruceForstall** [comment]
Hopefully there aren't upstream repos (installer? sdk?) that still expect to consume win-arm bits from runtime.

**Comment by jkotas** [comment]
We got a green official build an hour ago

**Comment by ericstj** [comment]
> Hopefully there aren't upstream repos (installer? sdk?) that still expect to consume win-arm bits from runtime.

That's probably a good thing to check before bringing this change back.  You can also trigger an official build for this change by pushing it to AzDo and scheduling there.
