### ISSUE TITLE
[API Proposal]: Add body content to HttpRequestException

### ISSUE THREAD

**Issue by StephenCleary** [dotnet/runtime#86095]
### Background and motivation

The existing HttpClient / HttpRequestException API does not provide a pit of success when API calls fail. `System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).` isn't terribly useful since it throws away all the details of the error, usually present in the body of the response. This applies to all failing status codes.

This is particularly impactful for developers learning a new API, as well as developers "testing the waters" of C# - API calls are something they're often familiar with, yet the first attempt often has some mistake in it. Experienced developers are also regularly frustrated by this because they have to add more boilerplate logging code *after* the call failed with a useless log message and then wait for it to fail again.

Minimum request: if the body content is a textual MIME type, include it (truncated if necessary) in `HttpRequestException.Message`.

Stretch goal: also handle binary information, adding a member to `HttpRequestException` to access the body content as bytes (buffered in memory, so this would also need to be truncated).

### API Proposal

(No API change; just a behavior change)

The default `HttpRequestException.Message` would include the content as a string, if possible.

### API Usage

```c#
catch (HttpRequestException ex)
{
  logger.LogError(ex, "Call failed"); // ex.Message now includes body as string
}
```

**Comment by stephentoub** [comment]
The body content could be massive, could include sensitive details, etc... anyone logging the message today could be in for an undesirable surprise.  The body might also not even be available anymore, e.g. if the HttpRequestMessage's Content used a stream.

**Comment by MihaZupan** [comment]
I don't think the exception message is the right place for such information, but something like HttpClientFactory's logging could be expanded to something closer to [ASP.NET's Http logging](https://learn.microsoft.com/aspnet/core/fundamentals/http-logging/). That model includes opt-ins for logging request/response bodies with truncation, headers, ...

**Comment by CarnaViire** [comment]
> something like HttpClientFactory's logging could be expanded

😄
Linking to https://github.com/dotnet/runtime/issues/77312 just in case

**Comment by ManickaP** [comment]
Including content as a text in the exception has many drawbacks as stated above, there are also ways to get to the content in case of non-success status code and lastly we have tracking issue to improve `HttpClientFactory` logging. I'm closing this as there are many drawbacks to this proposal.
If you feel the offered workarounds aren't sufficient, feel free to re-open and/or continue the discussion. Thanks.

**Comment by StephenCleary** [comment]
I understand the difficulties involved in implementing this. I just think this would make .NET a better runtime for new adopters.

Currently, every production-ready .NET client has to use something like Refit or Azure.Core or their own custom solution to do this. Note that both of those popular solutions provide this out-of-the-box.

It just seems odd (and honestly, embarrassing) to say "yeah, you actually need to build a whole system of your own around HttpClient, and you know all those super-convenient methods like GetStringAsync? Well, you can't actually use them; they're only for demos and docs, not real projects".

I'm not saying this issue should be re-opened; but I am saying that there's a definite place for something like a higher-level `HttpClient` to exist in the .NET runtime itself.
