### ISSUE TITLE
Happy Eyeballs support in Socket.ConnectAsync

### ISSUE THREAD

**Issue by scalablecory** [dotnet/runtime#861]
This proposal adds APIs needed to implement RFC 8305 "Happy Eyeballs" in `Socket.ConnectAsync`. This depends on #939.

The simplified description of Happy Eyeballs is that it makes A and AAAA DNS requests in parallel, and then goes back and forth between A and AAAA beginning parallel `Connect()` at a set interval until it has a connection. This trades more overhead for improved latency of the root `ConnectAsync` call.

See https://github.com/dotnet/runtime/issues/26177#issuecomment-540141586 where we decided to explore this as a general `Socket` feature rather than only `SocketsHttpClient`.

(API has cancellation support added where there previously hasn't been, to avoid needing to add yet more APIs later. See related #921)

```c#
class System.Net.Sockets.Socket
{
    public static bool ConnectAsync (SocketType socketType, ProtocolType protocolType, SocketAsyncEventArgs e, ConnectAlgorithm connectAlgorithm);
}

enum System.Net.Sockets.ConnectAlgorithm
{
    // use existing behavior.
    Default,

    // use a Happy Eyeballs-like algorithm to connect.
    Parallel = 1
}
```

#26177 would be implemented using this, but is not blocked by it.

**Comment by GrabYourPitchforks** [comment]
Feedback:

 * Take the new parameter and move it to the end of the parameter list of the new overload.
 * Remove `[Flags]` from the enum. We can add it later if necessary as long as we only have 1 legal value on the enum right now.
 * Rename the zero value to _Default_.
 * Consider renaming the enum to `ConnectionAlgorithm`.

**Comment by scalablecory** [comment]
Closing for mega-issue #33418.

**Comment by paulomorgado** [comment]
@GrabYourPitchforks,

From https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/enum:

> ✔️ DO name flag enums with plural nouns or noun phrases and simple enums with singular nouns or noun phrases.

So, adding or removing the [Flags] attribute has implications on the enum name.
