### ISSUE TITLE
Question about instruction groups

### ISSUE THREAD

**Issue by alpencolt** [dotnet/runtime#86117]
I've been investigated disasm for RISC-V and found strange thing:
```assembly
  2CA43023  sd           a0, 704(fp)
  2CB43423  sd           a1, 712(fp)
  2B043503  ld           a0, 688(fp)
  2B843583  ld           a1, 696(fp)
  2C043603  ld           a2, 704(fp)
						;; size=236 bbWeight=1 PerfScore 0.00
G_M24870_IG67:  ;; offset=35C8H
  2C843683  ld           a3, 712(fp)
  01F00713  addi         a4, zero, 31
  00B71713  slli         a4, a4, 11
  40B70713  addi         a4, a4, 1035
  00B71713  slli         a4, a4, 11
  4FE70713  addi         a4, a4, 1278
  00B71713  slli         a4, a4, 11
  60070713  addi         a4, a4, 1536
  00073703  ld           a4, 0(a4)
  000700E7  jalr         ra, 0(a4)		// System.Decimal:op_Modulus(System.Decimal,System.Decimal):System.Decimal
```

There we can see preparation for calling `op_Modulus(Decimal, Decimal)`, argumens passed in registers `a0-a3` and method address in `a4`. There is no other logic, just preparation for method invocation and invocation itself, but we can see that's the code split to different instruction groups. 
Does the instruction group similar to basic block? Looks there is bug if it's so.

cc @jakobbotsch @jkotas @BruceForstall 
@wscho77 @HJLeee @JongHeonChoi @t-mustafin @clamp03 @gbalykov

**Comment by SingleAccretion** [comment]
Instruction groups represent a collection of instructions. While the most common cause of groups being "broken up" is labels and thus control flow, there are many other possibilities, e. g. "overflow" - an instruction group has a maximum number of instructions it can house, or stress, or no-GC regions, etc.

**Comment by BruceForstall** [comment]
Instruction groups should display if they are "extension" (or "overflow") groups. Also, in some dumps, instruction groups will display a list of all the basic blocks that contributed code to them. I presume the Risc-V implementation preserves all this behavior, but I haven't checked.

**Comment by alpencolt** [comment]
It's definitely not caused by control flow, since there is no branches, but might be caused by overflow. Dump implementation in RISC-V is minimalistic and may show not all information.
Thank you for information, I will investigate.
