### ISSUE TITLE
Parallel.ForEachAsync loop counter

### ISSUE THREAD

**Issue by khteh** [dotnet/runtime#86135]
### Description
I need async and I need a loop counter which is used for async API calls which needs a sequence # for correlation. How to achieve this? https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.parallel.foreachasync?view=net-7.0
### Configuration

* Which version of .NET is the code running on? 7.0.105
* What OS and version, and for Linux, what distro? Ubuntu 23.04
* What is the architecture (x64, x86, ARM, ARM64)? x64
* Do you know whether it is specific to that configuration? No
* If you're using Blazor, which web browser(s) do you see this issue in?

**Comment by hez2010** [comment]
You can simply call `Select` to embed index data before passing your sequence to `Parallel.ForEachAsync`. For example:

```csharp
await Parallel.ForEachAsync(
    seq.Select((x, i) => (Value: x, Index: i)),
    async (x, token) => {
        await Task.Delay(100);
        Console.WriteLine($"#{x.Index}: {x.Value}");
   }
);
```
