### ISSUE TITLE
When reflecting abstruct proterty in interface, "BadImageFormatException: Bad IL format" will be thrown.

### ISSUE THREAD

**Issue by kkle1994** [dotnet/runtime#86141]
### Description

When reflecting abstruct proterty in interface, "BadImageFormatException: Bad IL format" will be thrown.
Interface code:
```Csharp
    public interface ITool
    {
        /// <summary>
        /// Whether this tool need P4 Connection.
        /// </summary>
        public abstract static bool IsP4Tool { get; }

        /// <summary>
        /// Whether this tool need to use Jira API.
        /// </summary>
        public abstract static bool IsJiraTool { get; }
    }
```

Reflect code
```Csharp
        /// <summary>
        /// Create instance of this type of tool, and preserve it into ToolInstances
        /// </summary>
        /// <param name="type"></param>
        public static void InstantiateTool(Type type)
        {
            var instance = type.GetConstructor(new Type[0]).Invoke(new object[0]);
            ToolManager.Instance.ToolInstances.Add(instance);

            var needInitP4method = type.GetInterface(nameof(ITool)).GetProperty(nameof(ITool.IsP4Tool), BindingFlags.Static | BindingFlags.Public);

            bool needInitP4 = (bool)(needInitP4method.GetGetMethod().Invoke(null, null));
            if (needInitP4)
            {
                InitP4Setting();
            }

            var needInitJiramethod = type.GetInterface(nameof(ITool)).GetProperty(nameof(ITool.IsJiraTool), BindingFlags.Static | BindingFlags.Public);
            bool needInitJira = (bool)needInitJiramethod.GetValue(null);
            if (needInitJira)
            {
                InitJiraSetting();
            }

        }
```

Exception detail:
```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   在 System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   在 System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   在 Drafter.Operators.ToolManager.InstantiateTool(Type type) 在 C:\p4v\yihang.gong_O1PCCB07302161_4483\Dev\Tool\Drafter\Drafter\Operators\ToolManager.cs 中: 第 64 行
   在 Drafter.ToolsForm.treeViewTools_NodeMouseDoubleClick(Object sender, TreeNodeMouseClickEventArgs e) 在 C:\p4v\yihang.gong_O1PCCB07302161_4483\Dev\Tool\Drafter\Drafter\ToolsForm.cs 中: 第 106 行
   在 System.Windows.Forms.TreeView.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

  此异常最初是在此调用堆栈中引发的: 

内部异常(Inner Exception) 1:
BadImageFormatException: Bad IL format.

```

### Configuration

.Net 7.0.5
Windows 10 x64

### Regression?

Abstruct static property is not supported before.

### Other information

Nope

**Comment by huoyaoyuan** [comment]
Invoking static virtual method via interface reflection is not supported. See https://github.com/dotnet/runtime/issues/50129#issuecomment-806236997 :

> There shall be no way to use reflection Invoke to perform a constrained invoke. If a customer truly needs to do that, the customer may use the interface map acquired through Type.GetInterfaceMap()

I'd suggest you to make the `InstantiateTool` method generic, and invoking it with instantiation is much easier.

**Comment by kkle1994** [comment]
> Invoking static virtual method via interface reflection is not supported. See [#50129 (comment)](https://github.com/dotnet/runtime/issues/50129#issuecomment-806236997) :
> 
> > There shall be no way to use reflection Invoke to perform a constrained invoke. If a customer truly needs to do that, the customer may use the interface map acquired through Type.GetInterfaceMap()
> 
> I'd suggest you to make the `InstantiateTool` method generic, and invoking it with instantiation is much easier.

Bad news, okay got that thanks. I see there is a .net-8 acitivity, so is this issue fixed in .net 8? (or well be fixed?)

**Comment by huoyaoyuan** [comment]
> Bad news, okay got that thanks. I see there is a .net-8 acitivity, so is this issue fixed in .net 8? (or will be fixed?)

Which activity do you refer to? Unless there is a planning that claims support, I don't any sort of support will be brought.

We should throw a better exception here though.
