### ISSUE TITLE
System.Net.Http.HttpRequestException: An HTTP/2 connection could not be established because the server did not complete the HTTP/2 handshake

### ISSUE THREAD

**Issue by okarpov** [dotnet/runtime#86142]
How to get know what may cause this issue and how it can be negotiated/resolved with HttpClient?

System.Net.Http.HttpRequestException: An HTTP/2 connection could not be established because the server did not complete the HTTP/2 handshake

**Comment by wfurt** [comment]
Get packet captures @okarpov. That should show some clues.
