### ISSUE TITLE
ProfToEEInterfaceImpl::DoStackSnapshot can only be called from the same thread on non Windows platforms

### ISSUE THREAD

**Issue by davmason** [dotnet/runtime#8615]
On Windows `ProfToEEInterfaceImpl::DoStackSnapshot` returns E_NOTIMPL for non Windows platforms. Looking through the code, this is because `Thread::SuspendThread` is disabled for the PAL.

This is a breaking change for the profiler APIs and we should investigate what it would take to bring it back to full functionality.

**Comment by davmason** [comment]
This is by design, since there is no safe thread suspension API like on windows. Closing.

**Comment by k15tfu** [comment]
@davmason Hi! I thought that you already emulate it on Linux (using UNIX signals), and use native API on macOS (thread_suspend). Why they can't be used by users before calling DoStackSnapshot()? What kind of limitations prevent us from having it?

**Comment by davmason** [comment]
In the runtime we don't do suspension of threads on a native level. I.e. we don't stop the thread exactly where it is. We do managed thread suspension for GCs, but that isn't freezing the thread. There are many things involved in managed thread suspension, it often involves letting the thread run a little bit to get to a safe spot.

As far as the profiler is concerned on linux and mac, you can either call DoStackSnapshot  on your own thread or after calling ICorProfilerInfo10::SuspendRuntime. Those are the only supported ways currently and anything further will require feature work.

**Comment by davmason** [comment]
#13171 tracks future work
