### ISSUE TITLE
[wasm] blazor perf builds failing

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#86165]
Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2179001&view=results with sdk `8.0.100-preview.5.23261.16`, commit - https://github.com/dotnet/runtime/commit/3bd383212013439c27097339031e48091ac74a3a .

```
$ pushd "/home/helixbot/work/ADA909AA/p/performance/src/scenarios/blazorpizza"
$ dotnet restore /home/helixbot/work/ADA909AA/p/performance/src/scenarios/blazorpizza/app/BlazingPizza.sln --packages /home/helixbot/work/ADA909AA/w/B94B0A4F/u/artifacts/packages /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1
/home/helixbot/work/ADA909AA/p/dotnet/sdk/8.0.100-preview.5.23261.16/Containers/build/Microsoft.NET.Build.Containers.targets(14,5):
  error MSB4184: The expression "[MSBuild]::VersionGreaterThanOrEquals('', 8.0)" cannot be evaluated. Version string was not in a correct format. [/home/helixbot/work/ADA909AA/p/performance/src/scenarios/blazorpizza/app/BlazingPizza.Client/BlazingPizza.Client.csproj]
/home/helixbot/work/ADA909AA/p/dotnet/sdk/8.0.100-preview.5.23261.16/NuGet.targets(398,5):
  error MSB4181: The "MSBuild" task returned false but did not log an error. [/home/helixbot/work/ADA909AA/p/performance/src/scenarios/blazorpizza/app/BlazingPizza.sln]
```

Started with sdk `8.0.100-preview.5.23261.2`, https://github.com/dotnet/runtime/commit/1ed120651c8a9e49cc4bb95cb3e6936e3f768e0e, and [build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2178329&view=results).

### Known Issue Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "BuildRetry": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by lewing** [comment]
@baronfel this looks like your change

**Comment by baronfel** [comment]
Yep, we've got a PR in SDK addressing it already. I'll check on the status.

**Comment by lewing** [comment]
@baronfel thanks, it's blocking out perf runs so there will be a gap in the data while it is broken

**Comment by baronfel** [comment]
@lewing the PR just merged in SDK, so is should start rolling through codeflow now.

**Comment by radical** [comment]
@baronfel That fix is needed for `main` also. Our perf runs are still broken with `8.0.100-preview.5.23264.2`.

**Comment by radical** [comment]
Now blocked on https://github.com/dotnet/installer/pull/16391 .

**Comment by radical** [comment]
All the relevant PRs have merged. And the error is no longer being hit.

**Comment by radical** [comment]
@baronfel thank you for the help!

**Comment by baronfel** [comment]
Apologies for the problem in the first place :)
