### ISSUE TITLE
[CoreCLR] Implement support for `UnsafeAccessorAttribute`

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#86161]
Implement https://github.com/dotnet/runtime/issues/81741 for CoreCLR.

- [x] Add `UnsafeAccessorAttribute` as a well-known attribute to the runtime https://github.com/dotnet/runtime/pull/86932
  We will need to extract a named string-value property from the custom attribute - duplicate work item with mono.
- [x] Non-generic scenarios https://github.com/dotnet/runtime/pull/86932
- [x] Validate generated code can be inlined https://github.com/dotnet/runtime/pull/86932
- [x] Add runtime testing https://github.com/dotnet/runtime/pull/86932
- [x] Update Trimmer to respect `UnsafeAccessorAttribute`
- [x] Validate Diagnostic scenarios

See Mono work item - https://github.com/dotnet/runtime/issues/86040
See NativeAOT work item - https://github.com/dotnet/runtime/issues/86438

**Comment by vitek-karas** [comment]
@AaronRobinsonMSFT do you want us to create a separate issue for NativeAOT support, or do you want to track that here as well?

Similar for crossgen - not sure if it needs to do anything, but at the very least it needs testing.

**Comment by AaronRobinsonMSFT** [comment]
> do you want us to create a separate issue for NativeAOT support, or do you want to track that here as well?

Possibly? I haven't thought too much about the needs in NativeAOT. My assumption is the compiler should be able to peer through at codegen time and emit the code. However, I support the stub needs to be generated. Hmmm yeah, a new issue is probably helpful for tracking at least.

**Comment by MichalStrehovsky** [comment]
NativeAOT work is probably the same as crossgen work if we want this for crossgen. Some thought for crossgen is needed because R2R only guarantees same versionability as the source IL and accessing privates goes beyond what we consider binary breaks for IL.

**Comment by MichalStrehovsky** [comment]
Oh I take that back, it's likely not possible in crossgen now because crossgen doesn't (AFAIK) have a way to manufacture new tokens and we'd likely need new ones for this

**Comment by jkotas** [comment]
Open a new tracking issue for the generics support and close this one as completed?

**Comment by AaronRobinsonMSFT** [comment]
> Open a new tracking issue for the generics support and close this one as completed?

Yep, that was the plan. Someone is pushing on this earlier than anticipated ;-)
