### ISSUE TITLE
ICorProfilerCallback.AssemblyUnloadStarted is never called

### ISSUE THREAD

**Issue by kevingosse** [dotnet/runtime#86178]
### Description

When loading an assembly into an AssemblyLoadContext, the methods AssemblyLoadStarted/AssemblyLoadFinished on ICorProfilerCallback are called as expected. However, when unloading the ALC, AssemblyUnloadStarted is not called (as far as I can tell).

I made extra sure with a debugger that the module was properly unloaded, yet the event is not raised. 

I scanned through the code and the event is supposed to be raised by `Assembly::StartUnload` but it doesn't seem to be called anywhere. Same thing for `Module::StartUnload`.

> 

### Reproduction Steps

- Write an application that properly unloads an ALC
- Attach a profiler

### Expected behavior

`ICorProfilerCallback::AssemblyUnloadStarted` should be called.

### Actual behavior

`ICorProfilerCallback::AssemblyUnloadStarted` aren't called.

**Comment by teo-tsirpanis** [comment]
c.c. @davmason

**Comment by kevingosse** [comment]
I'm guessing it should happen somewhere around there: https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/loaderallocator.cpp#L524

The ETW event is raised and the debugger is notified, but no love for the profiler.

**Comment by tommcdon** [comment]
Adding @davmason @janvorli for thoughts

**Comment by kevingosse** [comment]
I edited the issue: I initially thought that both `AssemblyUnloadStarted` and `AssemblyUnloadFinished` were missing, but I wasn't testing properly. Only `AssemblyUnloadStarted` is missing.

**Comment by janvorli** [comment]
I have looked through our sources and I have found that we don't have any call to the `Assembly::StartUnload` that would raise the event. I've found that the call was removed in early 5.0 by #204, but at that time, it was already not being called. I'll look into reenabling it.
