### ISSUE TITLE
[mono][hotreload] Adding a new field didn't work

### ISSUE THREAD

**Issue by thaystg** [dotnet/runtime#86172]
Program.cs:
```
public class EntryPoint
{
	public static void Main(string[] args)
	{
		try
		{
			AddProperty1.Main2(); // line 7
			Console.Write("\f");
		}
		catch (Exception e)
		{
			Console.WriteLine(e);
			throw;
		}
	}
}
```
OtherClass.cs
```
public class AddProperty1
{
	public static void Main2()
	{
	}
}
```
Add a breakpoint on line 7 of Program.cs.
Run the program, once it's paused, go to OtherClass.cs and replace the content to:

```
public class AddProperty1
{
	private static int A { get; set; }
	public static void Main2()
	{
		A = 11;
		System.Console.WriteLine(A);
	}
}
```

Mono runtime crashes:
![image](https://github.com/dotnet/runtime/assets/4503299/45199520-7e28-4e72-97fc-24f535917da2)

`field->type is NULL`

**Comment by lambdageek** [comment]
ah ok, easy fix.  we already check if a field is from a hot reload update in `compute_class_bitmap`. but we do it too late
