### ISSUE TITLE
SPMI: Ensure native linux hosted asmdiffs work

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#86181]
Currently asmdiffs doesn't work on Linux. Quoting @BruceForstall for why:

> It's because we need jit-analyze and git. In particular, we need git on the Helix machine so it can be used for git diff by jit-analyze. For Windows, we download a "portable git" package to the correlation payload. Building jit-analyze for Linux wouldn't be hard, but would require a few tweaks.

**Comment by kunalspathak** [comment]
As mentioned in https://github.com/dotnet/runtime/pull/86021#discussion_r1192795274, we already should have ability to run asmdiffs locally on linux.
