### ISSUE TITLE
Consider exposing Socket(SafeSocketHandle fd) constructor

### ISSUE THREAD

**Issue by dmirmilshteyn** [dotnet/runtime#862]
--- 
EDIT: Revised proposal by @stephentoub on 4/3/2020:
```C#
public Socket(SafeSocketHandle handle);
```
---

`System.Net.Sockets.Socket` currently does not expose any mechanism to instantiate a socket from an existing file descriptor/handle. This proposal aims to expose this functionality to improve interop with external applications that manage socket connections.

# Rationale and Usage

Currently, a socket must be both created and managed by the user application. While this is desired behaviour in most cases, there is no mechanism to take an existing socket handle/file descriptor and make use of it within the user application. If one wanted to use a socket that was created by an external application, the only option (outside of reflection hacks) is to reimplement the calls to the underlying platform sockets with P/Invoke - largely removing the benefits that the managed socket classes provide.

More specifically, this improves interop with existing applications that manage socket connections, such as systemd and the socket activation feature. In this scenario, systemd creates an unmanaged socket to listen for connections. Once a connection is established, a .NET application is launched and a file descriptor that references the unmanaged socked is passed to it through environment variables. Without the ability to create a managed socket from a file descriptor, the connection will need to be reset and then reestablished using the managed APIs - rather than cleanly being passed through and maintained. 

# Proposed API

```c#
namespace System.Net.Sockets
{
    // Previously implemented socket class
    public partial class Socket : System.IDisposable
    {
        // Existing constructors
        public Socket(System.Net.Sockets.AddressFamily addressFamily, System.Net.Sockets.SocketType socketType, System.Net.Sockets.ProtocolType protocolType) { }
        public Socket(System.Net.Sockets.SocketInformation socketInformation) { }
        public Socket(System.Net.Sockets.SocketType socketType, System.Net.Sockets.ProtocolType protocolType) { }   
        private Socket(SafeCloseSocket fd) { }

        // Additional existing members omitted

        // Proposed member
        public Socket(IntPtr fileDescriptor, AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType) { }
    }
}
```

# Details

* Adding this rather than exposing the existing Socket(SafeCloseSocket fd) constructor will keep the rest of the socket PAL internal, as there's currently public no way (as far as I can tell) to create an instance of SafeCloseSocket from a IntPtr.
* This will align with user expectations coming from other languages, such as Python, which has a similar method to create a socket from a file descriptor (see [socket.fromfd(fd, family, type[, proto])](https://docs.python.org/2/library/socket.html#socket.fromfd)).
* Platforms that don't support wrapping unmanaged sockets (or that don't expose them, such as UWP?) will throw PlatformNotSupportedException.

**Comment by scalablecory** [comment]
We have two internal partners asking for this. CC @samsp-msft

**Comment by wfurt** [comment]
`SO_DOMAIN` and  `SO_PROTOCOL` is not POSIX but it does exist and work on FreeBSD. Windows have `SO_PROTOCOL_INFO`. With that we should be able to reconstruct following properties:
```
AddressFamily
Blocking
Connected
IsBound
LocalEndPoint
ProtocolType
RemoteEndPoint
SocketType
```

That leaves macOS. When socket is bound or connected we can get AddressFamily from the address. Also `getsockopt(fd, IPPROTO_IP, *)` fails with `EINVAL` on PF_INET6 socket. It should take up to 3 probes to determine there families e.g. `InterNetwork`, `InterNetwork6` and `Unix` .

I did also some testing with using unsupported socket type on Linux e.g. `Netlink`. So far everything works with exception of Bind() and custom EndPoint. OS `bind()` still works  and it can be used as workaround.

**Comment by stephentoub** [comment]
> With that we should be able to reconstruct following properties

Thanks for the notes!

Mostly. I actually have this implemented locally and wired up with #34158 (which was what I actually wanted to solve). However, we can't fully reconstruct everything you listed.  Blocking, for example.  I don't know of any way to query that on Windows.  And on Unix, we can query it, but that tells us the actual state of the file descriptor's nonblocking setting, whereas in the managed layer we maintain some shadow state to keep Socket.Blocking behaving the way the developer set it but be able to use non-blocking under the covers as part of the async implementation.

Even with some minor hiccups / inconsistencies, I think this is still worthwhile.  The majority use case for this is taking a file descriptor / handle that didn't come from a managed Socket, and without this ctor, there's no good way to achieve it, and with the ctor, the cited inconsistencies should be at worst minor annoyances.

**Comment by wfurt** [comment]
For the Blocking, the special handling would apply only with async, right? So for the newly created socket it should be OK to reflect OS Blocking IMHO since no Async was done so far. This could possibly create issue if somebody used Handle from existing socket thinking it is Blocking but it is not under the cover e.g. the issue is with sending, not creating Socket from handle. 

For Windows, I'm wondering if we could always set it as blocking and document that or if it would be better to live with possible inconsistency. In some way caller should know and structure the code accordingly. 
   
The easy way to fix if somebody hits is to set it explicitly after creation, right? If we see use case for creating `Socket` from existing `Socket` maybe we can add support for duplication/clone. 

In either case, since access exist outside if the `Socket`, OS handle can be closed and that can also create surprises. Perhaps it would be worth of adding note about good practices.

**Comment by stephentoub** [comment]
> For the Blocking, the special handling would apply only with async, right?

Correct.

> For Windows, I'm wondering if we could always set it as blocking

That's what I currently do.  I don't see a better alternative.

> The easy way to fix if somebody hits is to set it explicitly after creation, right?

Yes

**Comment by stephentoub** [comment]
@wfurt, here's my branch, btw:
https://github.com/stephentoub/runtime/commit/ffa06e16ae273bc7b27768938c3f9922438de05f
