### ISSUE TITLE
error when build native aot with selenium dotnet 7

### ISSUE THREAD

**Issue by NCLnclNCL** [dotnet/runtime#86202]
### Description

error when i run it 

### Reproduction Steps

build native aot

### Expected behavior

running succesfully

### Actual behavior

error 
Unhandled Exception: System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Reflection.Assembly.GetCallingAssembly() + 0x5b
   at OpenQA.Selenium.Internal.ResourceUtilities.get_AssemblyVersion() + 0x40
   at OpenQA.Selenium.Remote.HttpCommandExecutor..ctor(Uri, TimeSpan, Boolean) + 0xbc
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor..ctor(DriverService, TimeSpan, Boolean) + 0x4d
   at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService, ChromiumOptions, TimeSpan) + 0x44
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService, ChromeOptions) + 0x26

### Known Workarounds

no

### Configuration

.net 7
win 10
x64

**Comment by am11** [comment]
NativeAOT does not support GetCallingAssembly. Either its support will be added as part of https://github.com/dotnet/runtime/issues/69919 or this API will be obsoleted altogether in favor of Roslyn feature: https://github.com/dotnet/csharplang/issues/4984.

**Comment by NCLnclNCL** [comment]
> NativeAOT không hỗ trợ GetCallingAssembly. Hỗ trợ của nó sẽ được thêm vào như một phần của #69919 hoặc API này sẽ bị lỗi thời hoàn toàn để ủng hộ tính năng Roslyn: [dotnet/csharplang#4984](https://github.com/dotnet/csharplang/issues/4984) .

I don't know how to actually use that function

**Comment by am11** [comment]
Selenium is calling `GetCallingAssembly` here: https://github.com/SeleniumHQ/selenium/blob/632df3ecab85f7ca6ce268573997a63983c47797/dotnet/src/webdriver/Internal/ResourceUtilities.cs#L46

**Comment by NCLnclNCL** [comment]
> Selenium is calling `GetCallingAssembly` here: https://github.com/SeleniumHQ/selenium/blob/632df3ecab85f7ca6ce268573997a63983c47797/dotnet/src/webdriver/Internal/ResourceUtilities.cs#L46

How to fix sir, do i need to fix selenium source?

**Comment by am11** [comment]
> do i need to fix selenium source?

Yes, making Selenium NativeAOT compatible is the way to go.

**Comment by NCLnclNCL** [comment]
> > do i need to fix selenium source?
> 
> Yes, making Selenium NativeAOT compatible is the way to go.

How to making bro,do you can help me

**Comment by am11** [comment]
You can create an issue at https://github.com/SeleniumHQ/selenium/issues for NativeAOT compatibility or reply to this closed issue https://github.com/SeleniumHQ/selenium/issues/8549 with your steps to repro. Someone in their community might be able to help.

The version of bazel they are using (rules_dotnet) doesn't support .NET 7 and I'm not familiar with bazel enough to know how to upgrade its rules. It was giving me `"key net7.0 not found in dictionary"` when I updated `TargetFramework` to net7.0 in webdriver's csrpoj file and built.

**Comment by MichalStrehovsky** [comment]
I've submitted a PR to Selenium as https://github.com/SeleniumHQ/selenium/pull/12038 but it looks like it's going to require a CLA signature and I'm not going to authorize a random github app to access my github account to do that. If the PR doesn't go through because they'll insist on the CLA on a de minims change that is not even copyrightable, @NCLnclNCL feel free to submit the same change yourself. I don't care about Selenium, I just wanted to fix this bug.

Going to close this as external/dup of https://github.com/dotnet/runtime/issues/69919.

**Comment by am11** [comment]
@MichalStrehovsky, there are other places using PNSE-throwing APIs. Their build requires bazel in pre-build step to generate code needed by the main build. Without building it locally, it isn't worth pursuing.

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky, there are other places using PNSE-throwing APIs. Their build requires bazel in pre-build step to generate code needed by the main build. Without building it locally, it isn't worth pursuing.

Ah, thanks! I'll just close the PR then. This one looked "obviously wrong" enough that I gave it a go but don't really want to spend time on it.

**Comment by NCLnclNCL** [comment]
> > @MichalStrehovsky, there are other places using PNSE-throwing APIs. Their build requires bazel in pre-build step to generate code needed by the main build. Without building it locally, it isn't worth pursuing.
> 
> Ah, thanks! I'll just close the PR then. This one looked "obviously wrong" enough that I gave it a go but don't really want to spend time on it.

You still yet help me

**Comment by NCLnclNCL** [comment]
Help me

**Comment by MichalStrehovsky** [comment]
@NCLnclNCL you need to raise this with Selenium. Assembly.GetCallingAssembly is not supported with NativeAOT and we have no plans to add it.

**Comment by Perksey** [comment]
It looks like Selenium fixed this 3 weeks ago: https://github.com/SeleniumHQ/selenium/pull/12045
