### ISSUE TITLE
[API Proposal]: AsSpan for Vector128<T>, Vector256<T>m 

### ISSUE THREAD

**Issue by DaanV2** [dotnet/runtime#86204]
### Background and motivation

I was busy writing some code where I had to go over an array of bytes.
I decided to implement `Vector128<Byte>` for faster manipulation of the entire data set.

But for a piece of code, I still need to loop over the contents, Now is that pretty easy as `Vector128<Byte>` does support this.
However, I have already written the code for ReadOnlySpan<Byte>, and in theory, vectors could support this, but atm this doesn't work.

A benefit of this, is that any written code in the .Net libraries written for Spans suddenly becomes more easily accessible for Vectors

So here is my proposal for the feature to get a AsSpan for vectors

### API Proposal

```csharp
class Vector128<Byte> {
   public Span<T> AsSpan();

// OR

   public ReadOnlySpan<T> AsSpan();
}
```

### API Usage

```csharp
// Fancy the value
var vec = Vector128.Create(someByeData);

Print(vec.AsSpan())

void Print(ReadOnlySpan<Byte> data) {
  foreach (var d in data)
      Console.WriteLine(d);
}
```

### Risks

Vector128 as pretty optimized and do some memory trick to make them work as they do.

With `span` it could possible lead to some problems?  but just `ReadOnlySpan` make it safer?

**Comment by EgorBo** [comment]
> But for a piece of code, I still need to loop over the contents,

That sounds like you're using Vectors in an non-SIMD fashion, for example see how we iterate matches from a comparison of two vectors:
```
uint mask = cmpAnd.ExtractMostSignificantBits();
do
{
    int bitPos = BitOperations.TrailingZeroCount(mask);
    mask = BitOperations.ResetLowestSetBit(mask);
} while (mask != 0);
```
Do you have some more realistic example you need AsSpan for?

**Comment by DaanV2** [comment]
> That sounds like you're using Vectors in an non-SIMD fashion

Yes, because I have all the SIMD things I could do

> Do you have some more realistic examples you need AsSpan for?

Im converting the contents of the vector to a string representation. which causes 1 byte to be split over characters.

**Comment by EgorBo** [comment]
> Im converting the contents of the vector to a string representation. which causes 1 byte to be split over characters.

Do you mean UTF8 -> UTF16? Sounds like a job for `Vector128.Widen`

**Comment by EgorBo** [comment]
If you still need a Span you can do something like
```csharp
Span<int> span = stackalloc int[4];
myVector.StoreUnsafe(ref MemoryMarshal.GetReference(span));
```

> data out of the vector in a way that isn't supported.

If you show us a complete use-case we might suggest you a way to still use SIMD for it

**Comment by DaanV2** [comment]
Guess ill write just an extension method, don't get why there is such as resistance on it

**Comment by EgorBo** [comment]
I'm not against this idea completely, but API proposals need a strong motivation to be considered (with real world examples), they're not meant to save 1 line of code for an edge case. Also, as was noted previously, the existence of such an API might motivate people to work with vectors in a non-SIMD fashion.

**Comment by DaanV2** [comment]
I don't know a good real-world example, as I was just busy, and I found it weird that Vectors supported going to span.

Span is everywhere nowadays in the std library. 

An example I could think of was `Stream`. They support many different spans in their method, but I would need to find a way to put a Vector into my stream directly. Unless you use the code, you just wrote. I had no idea you could do it that way. But what I did know was that a lot supports Span and ReadOnlySpan, so it just seemed weird to me that such a fast and good objects didn't support this

> ```cs
> Span<int> span = stackalloc int[4];
> myVector.StoreUnsafe(ref MemoryMarshal.GetReference(span));
> ```

**Comment by EgorBo** [comment]
> I don't know a good real-world example, as I was just busy, and I found it weird that Vectors supported going to span.
> 
> Span is everywhere nowadays in the std library.
> 
> An example I could think of was `Stream`. They support many different spans in their method, but I would need to find a way to put a Vector into my stream directly. Unless you use the code, you just wrote.
> 
> > ```cs
> > Span<int> span = stackalloc int[4];
> > myVector.StoreUnsafe(ref MemoryMarshal.GetReference(span));
> > ```
> 
> I had no idea you could do it that way. But what I did know was that a lot supports Span and ReadOnlySpan, so it just seemed weird to me that such fast and good objects didn't support this.
> 
> Event allot of input methods of vectors use Span, but nothing that goes out

It turns out we already discussed a similar proposal - https://github.com/dotnet/runtime/issues/24596#issuecomment-355715647

**Comment by DaanV2** [comment]
> It turns out we already discussed a similar proposal - https://github.com/dotnet/runtime/issues/24596#issuecomment-355715647

Not sure if this counts, but that proposal is for an extension class, which wouldn't work with spans.
You would have to bake in the method to get it to work.

**Comment by tannergooding** [comment]
`Vector128` already has several APIs that support reading from and writing to spans.

These new proposed APIs would not lead to correct usage of the types in the typical case and would encourage patterns that actively hurt the perf/throughput of the code in question instead.
