### ISSUE TITLE
IOS Push Notification Sending Failed with SSL Connection Error

### ISSUE THREAD

**Issue by Sujit2444** [dotnet/runtime#86214]
```
IOS Push Notification Sending Failed. The SSL connection could not be established, see inner exception.  Stack Trace:     at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at servicewithtopself.Notification.SendIOSNotification(String deviceToken, String apnsId, Int32 notificationId, String title, String category, String message, String tags) in E:\Work\Source\App_ApplePushNotifyService\Main\App_ApplePushNotifyService\Notification.cs:line 218
```

I encountered an issue while trying to send an iOS push notification. The error message indicates that the SSL connection could not be established, with an inner exception.I also chceked my APNs certificate valid till september 2023. I am looking for guidance on how to resolve this error and establish a successful connection for push notifications. Any assistance or suggestions would be greatly appreciated.

**I attached my code snippet. 
![Capture4](https://github.com/dotnet/runtime/assets/129045794/1afcc858-a2ee-4d03-9475-485f47bd5f5b)

**Comment by vcsjones** [comment]
Can you help us by providing a little more information?

> see inner exception

What is the inner exception?

> App_ApplePushNotifyService\Main\App_ApplePushNotifyService\Notification.cs:line 218

Can you share sample code that reproduces the issue?

Based on your path in your exception, I assume you are running on Windows. Can you tell us what version of Windows you are using?

**Comment by wfurt** [comment]
Wireshark packet capture may be also useful.

**Comment by Sujit2444** [comment]
> Can you help us by providing a little more information?
> 
> > see inner exception
> 
> What is the inner exception?
> 
> > App_ApplePushNotifyService\Main\App_ApplePushNotifyService\Notification.cs:line 218
> 
> Can you share sample code that reproduces the issue?
> 
> Based on your path in your exception, I assume you are running on Windows. Can you tell us what version of Windows you are using?

**Comment by Sujit2444** [comment]
> Tagging subscribers to this area: @dotnet/ncl, @bartonjs, @vcsjones See info in [area-owners.md](https://github.com/dotnet/runtime/blob/main/docs/area-owners.md) if you want to be subscribed.
> 
> Issue Details



> Can you help us by providing a little more information?
> 
> > see inner exception
> 
> What is the inner exception?
> 
> > App_ApplePushNotifyService\Main\App_ApplePushNotifyService\Notification.cs:line 218
> 
> Can you share sample code that reproduces the issue?
> 
> Based on your path in your exception, I assume you are running on Windows. Can you tell us what version of Windows you are using?

please check the code snippet I attached!

**Comment by steveisok** [comment]
@Sujit2444 it would help us understand what's wrong better if you included a sample project. That way we can see if you're using the native handler or sockets http handler among other things.

**Comment by steveisok** [comment]
/cc @simonrozsival 

This might need transferred to the xam ios repo depending on the handler type used.

**Comment by simonrozsival** [comment]
@steveisok @karelz this issue is tagged with `os-ios` but I don't see any other indication that this code actually runs on an iOS device. Isn't this a server-side service that's trying to send a push notification to an iOS device? Can you please clarify on which platform you got this exception, @Sujit2444?
