### ISSUE TITLE
[BUG] .NET acts weirdly on wrapped native libraries

### ISSUE THREAD

**Issue by aymen157** [dotnet/runtime#86224]
### Description

using any SDL wrapper on a .NET app (eg. console application + SDL-cs) causes the flag "SDL_WINDOW_ALLOW_HIGHDPI" to not work. Manually P/invoking SetProcessDpiAwareness Enables high dpi. So i suppose this has to do with the way .NET boilerplate code is interacting with the OS ?

(Tested on windows 10 x64 .Net 6) (This is not a SDL bug. other wrappers work perfectly such as Rust wrapper, native C++/C works properly)

Example is attached.

[highdpi_bug repository](https://github.com/aymen157/high_dpi_bug_sdl_dotnet/tree/main/highdpi_bug)

(The used wrapper [SDL2-CS](https://github.com/flibitijibibo/SDL2-CS). but other wrappers have same problem aswell)

### Reproduction Steps

Any native lib that deals with DPI is inconsistent on .NET

### Expected behavior

DPI to be working after settings that flag.

### Actual behavior

DPI not changing. Possibly due to bug in how .NET boilerplate works.

**Comment by huoyaoyuan** [comment]
Testing with the `Veldrid.SDL2` wrapper. Setting AllowHighDpi in SDL call has no effect, but adding `<dpiAware>` in win32 manifest has effect, even with `AllowHighDpi` not set, in term of window size.
This may be related to how Windows deals with the executable.

**Comment by aymen157** [comment]
im pretty sure it's related to the native code in the runtime. for instance, languages that doesn't add boilerplate such as cpp doesn't have this problem.
im not sure if its windows only or not as it requires what is triggering this bug. i've dug but not too deep and couldn't understand how

**Comment by aymen157** [comment]
This Issue seems to be windows related and not .Net related as windows does weird stuff with DPI to only certain applications.
For anyone curious / further reading about this : https://github.com/libsdl-org/SDL/issues/4908
