### ISSUE TITLE
System.Security.AccessControl relies on deprecated package System.Security.Principal.Windows

### ISSUE THREAD

**Issue by SimonCropp** [dotnet/runtime#86236]
https://www.nuget.org/packages/System.Security.AccessControl/6.0.0 relies on https://www.nuget.org/packages/System.Security.Principal.Windows/ which is deprecated.

So should  System.Security.AccessControl be deprecated as well?

**Comment by ericstj** [comment]
The 6.0.0 packages will be marked deprecated when 6.0 goes out of support.  What's the user experience 

Both of these packages are facades, so they aren't particularly interesting for .NETFramework projects.  Their only real remaining purpose is for folks writing .NETStandard 2.0 libraries where they provide a reference, which is replaced by the facade when targeting .NETFramework and replaced with inbox assembly when targeting .NET5+.

AFAIK we don't have a way to mark these as deprecated for one framework and not another.  Options available are the following:
1. Leave as deprecated.  The messaging that the tooling gives is close enough to what we'd like to say.
2. Unmark as deprecated, but don't do anything to bring the packages back to a branch where they can build -- given they're only reference assemblies and facades we'll likely never need to service them.
3. Unmark as deprecated and move them to https://github.com/dotnet/maintenance-packages removing the .NETCore implementation and replacing with a placeholder.

@terrajobst @ViktorHofer can you weigh in on this?

**Comment by ViktorHofer** [comment]
In my opinion, packages that are still needed to target and/or run on our minimum supported target frameworks should not be deprecated. The currently minimum supported TFMs are: netstandard2.0, net462 and net6.0. Regarding .NET Standard support, runtimes besides .NET Framework and .NETCoreApp are still in support, i.e. UWP, Unity and Xamarin.

Below is the list of packages that are needed for .NET Framework and/or .NET Standard support. We should make sure to not deprecate the latest stable version of any of the packages below and un-deprecate the five ones that already got marked as deprecated:

| Package | Latest stable version deprecated |
| --- | :---: |
| Microsoft.Bcl.AsyncInterfaces | |
| Microsoft.Bcl.Cryptography | |
| Microsoft.Bcl.HashCode | |
| Microsoft.CSharp | |
| Microsoft.Diagnostics.Tracing.EventSource.Redist | |
| Microsoft.IO.Redist | |
| Microsoft.Win32.Registry | x |
| System.Buffers | |
| System.Data.DataSetExtensions | |
| System.Memory | |
| System.Net.WebSockets.WebSocketProtocol | x |
| System.Numerics.Vectors | |
| System.Reflection.DispatchProxy | |
| System.Reflection.Emit | |
| System.Reflection.Emit.ILGeneration | |
| System.Reflection.Emit.Lightweight | |
| System.Reflection.TypeExtensions	| |
| System.Runtime.CompilerServices.Unsafe | |
| System.Runtime.InteropServices.RuntimeInformation	| |
| System.Security.AccessControl | |
| System.Security.Cryptography.Algorithms | |
| System.Security.Cryptography.Cng | x |
| System.Security.Cryptography.OpenSsl | x |
| System.Security.Principal.Windows | x |
| System.Threading.Tasks.Extensions | |
| System.ValueTuple | |

cc @leecow

**Comment by ViktorHofer** [comment]
We just reverted the deprecation of the five packages from the list above. Feel free to open a new issue when you see packages incorrectly being marked as deprecated again.

**Comment by SimonCropp** [comment]
thanks peoples
