### ISSUE TITLE
[8.0.100-preview.5.23264.1] Apps that using BinaryFormatter will get System.NotSupportedException Exception

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/runtime#86308]
### Description

In dotnet-sdk-8.0.100-preview.5.23264.1, fail to launch 3 apps in our lab with System.NotSupportedException: 'BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.'

### Reproduction Steps

1. Launch Flow.Launcher.exe

### Expected behavior

App launches successful.

### Actual behavior

App launches failed with following error:
```System.NotSupportedException: 'BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.'```

### Regression?

Yes

**Verify Scenarios:**
1. Windows10 21h2 x64 + dotnet-sdk-8.0.100-preview.5.23264.1: Fail
2. Windows10 21h2 x64 + dotnet-sdk-8.0.100-preview.4.23259.1: Pass
3. Windows10 21h2 x64 + dotnet-sdk-7.0.300: Pass

### Known Workarounds
Set it in your application's project file to reenable BinaryFormatter functionality ```<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>```

### Configuration

**Application Name:** Flow.Launcher (WPF/WinForm), Forum(ASPNETCore), SCM2020(WPF), JexusManager (WinForm), NotatnikMechanika(WinForm/WPF), Estoque(WinForm), ReoGrid(WPF), ConicSectionPlayground(WinForm), paintnetcore(WinForm/WPF), PortProxyGUI(WinForm), NetTopologySuite(UnitTest)
**OS**: Windows 10 21H2
**CPU:** X64
**.NET Build Number**: dotnet-sdk-8.0.100-preview.5.23264.1
**Github source link**:  https://github.com/Flow-Launcher/Flow.Launcher
**Also Can check app or app source at** : https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1819238

### Other information

**Minimal Repro Steps:**  (demo: [WpfApp1.zip](https://github.com/dotnet/runtime/files/11504371/WpfApp1.zip))

1.Create a default WPF project.
2. Install NLog.Web.AspNetCore nuget package into the project.
3. Add following code in MainWindow.xaml.cs file:
```
#pragma warning disable SYSLIB0011
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();

            Hashtable addresses = new Hashtable();
            addresses.Add("Jeff", "2222123 Main Street, Redmond, WA 98052");
            addresses.Add("Fred", "987 Pine Road, Phila., PA 19116");
            addresses.Add("Mary", "PO Box 112233, Palo Alto, CA 94301");

            FileStream fs = new FileStream("DataFile.dat", FileMode.Create);
            BinaryFormatter formatter = new BinaryFormatter();
            formatter.Serialize(fs, addresses);
            fs.Close();
        }
    }
```
4. Build the project.
5. Change the runtime.config file to run against with 8.0.100-preview.5.23264.1:
```
{
  "runtimeOptions": {
    "tfm": "net7.0",
    "frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "8.0.0-preview.5.23260.3"
      },
      {
        "name": "Microsoft.WindowsDesktop.App",
        "version": "8.0.0-preview.5.23261.7"
      },
      {
        "name": "Microsoft.AspNetCore.App",
        "version": "8.0.0-preview.5.23262.1"
      }
    ]
  }
}
```
7. Launch the app.

**Excepted Result:**
App launch succesful.

**Actual Result:**
App launch failed with NotSupportedException.

**Findings:**

1. We found this breaking change issue doc: [[Breaking change]: BinaryFormatter disabled across almost all project types by default · Issue #34891 · dotnet/docs (github.com)](https://github.com/dotnet/docs/issues/34891) 
According to this sentence "In .NET 8 Preview 4, these methods will throw NotSupportedException at runtime across all project types except WinForms and WPF. ", the NotSupportedException will be thrown at runtime except WinForms and WPF. This app is mixed of WPF and Winform, and refer a asp.net core related component (Nuget Package: NLog.Web.AspNetCore). From 8.0.100-preview.5.23264.1, the app gets NotSupportedException at runtime. 

2. We created a console app to use BinaryFormatter to Serialize/Deserialize FileStream and suppressed the error with "#pragma warning disable SYSLIB0011", but it doesn't throw NotSupportedException at runtime on 8.0.100-preview.5.23264.1. (Demo app attached: [BinaryFormatterDemo.zip](https://github.com/dotnet/runtime/files/11504381/BinaryFormatterDemo.zip)). According to the breaking change doc, it should throw the exception.

3. If we create a asp.net core app that using BinaryFormatter, it will throw NotSupportedException when running against with 8.0.100-preview.5.23264.1.
4. On 8.0.100-preview.5.23264.1, If a WPF/WinForm app refers a asp.net core related component (for example: NLog.Web.AspNetCore nuget package), it will throw this NotSupportedException even the app doesn't use it. (Demo attached: WpfApp1.zip)
5. Starting from dotnet-sdk-8.0.100-preview.5.23273.2, almost all project types including Console, Winform and WPF apps, failed with NotSupportedException without using asp.netcore related component. (Demo attached: 
[DefaultWinFormsApp.zip](https://github.com/dotnet/runtime/files/11552876/DefaultWinFormsApp.zip))

@dotnet-actwx-bot @dotnet/compat

**Comment by stephentoub** [comment]
cc:@GrabYourPitchforks

**Comment by Junjun-zhao** [comment]
Updated more findings and the additional 2 affected apps in our lab.

**Comment by Junjun-zhao** [comment]
As @GrabYourPitchforks  is OOF,  adding @jeffhandley,  Could you help check and triage this issue?  Thanks.

**Comment by jeffhandley** [comment]
Generally speaking, these errors are expected. Some of the detailed notes about when you do and don't see exceptions are confusing me though--perhaps because I'm not sure if you're including `<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>` in your application configuration. Using pragmas to suppress the compiler warnings won't change the runtime behavior, but setting that config setting will.

Ultimately these applications, like all others using BinaryFormatter features, will need to be modified to not use that feature set and instead serialize/deserialize the data in different ways.

We won't be able to look at this more closely until next week. But if you need to get temporarily unblocked, I recommend ensuring that config setting is in place for the apps.

**Comment by Junjun-zhao** [comment]
Thank you for your information @jeffhandley.   That's ok. We are updating these apps by setting the config setting to unblock them.

> Some of the detailed notes about when you do and don't see exceptions are confusing me though--perhaps because I'm not sure if you're including ```<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>``` in your application configuration.

No, we did not set it in the application configuration.  It should be an issue with build 8.0.100-preview.5.23264.1. Starting from latest build dotnet-sdk-8.0.100-preview.5.23273.2, it will throw the exception.

**Comment by jeffhandley** [comment]
It sounds like everything is behaving as expected then, with the exception being thrown when the config setting is not set. I'm not sure which build number would have had the breaking change first; does that detail need to be determined?

Once the apps are all patched to be working with the config switch set, that should get you through the rest of .NET 8. However, in .NET 9, we will continue the journey of deprecating BinaryFormatter by removing these compat switches. EAch app affected will need to be modified to avoid usage of BinaryFormatter.

https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md#net-9-nov-2024

Let me know if there's anything else needed on this at this time. Thanks!
