### ISSUE TITLE
CI build failure: Bash exited with code '1' failure - Could NOT find ZLIB

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/runtime#86324]
Seen when running `runtime-extra-platforms` on  `linux-arm64 Release AllSubsets_Mono_LLVMFullAot_RuntimeTests llvmfullaot`

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=274202
Build error leg or test failing: Build / linux-arm64 Release AllSubsets_Mono_LLVMFullAot_RuntimeTests llvmfullaot / Build Mono LLVM AOT cross compiler
Pull request: https://github.com/dotnet/runtime/pull/86266

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[353096](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353096)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/353096/logs/931)||
|[353048](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353048)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/353048/logs/664)|dotnet/runtime#89467|
|[352690](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352690)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/352690/logs/965)|dotnet/runtime#89431|
|[2230039](https://dev.azure.com/dnceng/internal/_build/results?buildId=2230039)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2230039/logs/116)||
|[2229927](https://dev.azure.com/dnceng/internal/_build/results?buildId=2229927)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2229927/logs/121)||
|[352326](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352326)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/352326/logs/949)||
|[2229668](https://dev.azure.com/dnceng/internal/_build/results?buildId=2229668)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2229668/logs/111)||
|[2229580](https://dev.azure.com/dnceng/internal/_build/results?buildId=2229580)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2229580/logs/47)||
|[2229437](https://dev.azure.com/dnceng/internal/_build/results?buildId=2229437)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2229437/logs/104)||
|[351937](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351937)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/351937/logs/823)||
|[351866](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351866)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/351866/logs/940)||
|[351758](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351758)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/351758/logs/681)|dotnet/runtime#89223|
|[351723](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351723)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/351723/logs/813)||
|[2229082](https://dev.azure.com/dnceng/internal/_build/results?buildId=2229082)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2229082/logs/111)||
|[351065](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351065)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/351065/logs/931)||
|[351063](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351063)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/351063/logs/548)|dotnet/runtime#89421|
|[351019](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351019)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/351019/logs/33)||
|[2228885](https://dev.azure.com/dnceng/internal/_build/results?buildId=2228885)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2228885/logs/113)||
|[2228802](https://dev.azure.com/dnceng/internal/_build/results?buildId=2228802)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2228802/logs/47)||
|[2228665](https://dev.azure.com/dnceng/internal/_build/results?buildId=2228665)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2228665/logs/91)||
|[350495](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350495)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/350495/logs/944)||
|[350271](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350271)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/350271/logs/840)||
|[2228258](https://dev.azure.com/dnceng/internal/_build/results?buildId=2228258)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2228258/logs/98)||
|[349510](https://dev.azure.com/dnceng-public/public/_build/results?buildId=349510)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/349510/logs/913)||
|[349464](https://dev.azure.com/dnceng-public/public/_build/results?buildId=349464)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/349464/logs/35)||
|[2227956](https://dev.azure.com/dnceng/internal/_build/results?buildId=2227956)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2227956/logs/99)||
|[2227939](https://dev.azure.com/dnceng/internal/_build/results?buildId=2227939)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2227939/logs/47)||
|[349328](https://dev.azure.com/dnceng-public/public/_build/results?buildId=349328)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/349328/logs/928)||
|[2227837](https://dev.azure.com/dnceng/internal/_build/results?buildId=2227837)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2227837/logs/97)||
|[349156](https://dev.azure.com/dnceng-public/public/_build/results?buildId=349156)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/349156/logs/933)||
|[2227737](https://dev.azure.com/dnceng/internal/_build/results?buildId=2227737)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2227737/logs/105)||
|[349144](https://dev.azure.com/dnceng-public/public/_build/results?buildId=349144)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/349144/logs/31)||
|[2227669](https://dev.azure.com/dnceng/internal/_build/results?buildId=2227669)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2227669/logs/54)||
|[2227649](https://dev.azure.com/dnceng/internal/_build/results?buildId=2227649)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2227649/logs/97)||
|[349045](https://dev.azure.com/dnceng-public/public/_build/results?buildId=349045)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/349045/logs/965)||
|[2227542](https://dev.azure.com/dnceng/internal/_build/results?buildId=2227542)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2227542/logs/113)||
|[348654](https://dev.azure.com/dnceng-public/public/_build/results?buildId=348654)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/348654/logs/937)||
|[2227439](https://dev.azure.com/dnceng/internal/_build/results?buildId=2227439)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2227439/logs/97)||
|[348644](https://dev.azure.com/dnceng-public/public/_build/results?buildId=348644)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/348644/logs/37)||
|[2227366](https://dev.azure.com/dnceng/internal/_build/results?buildId=2227366)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2227366/logs/47)||
|[2227269](https://dev.azure.com/dnceng/internal/_build/results?buildId=2227269)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2227269/logs/117)||
|[348291](https://dev.azure.com/dnceng-public/public/_build/results?buildId=348291)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/348291/logs/902)||
|[347426](https://dev.azure.com/dnceng-public/public/_build/results?buildId=347426)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/347426/logs/986)||
|[347390](https://dev.azure.com/dnceng-public/public/_build/results?buildId=347390)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/347390/logs/37)||
|[2226549](https://dev.azure.com/dnceng/internal/_build/results?buildId=2226549)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2226549/logs/47)||
|[2226537](https://dev.azure.com/dnceng/internal/_build/results?buildId=2226537)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2226537/logs/85)||
|[346915](https://dev.azure.com/dnceng-public/public/_build/results?buildId=346915)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/346915/logs/918)||
|[346860](https://dev.azure.com/dnceng-public/public/_build/results?buildId=346860)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/346860/logs/847)||
|[2226244](https://dev.azure.com/dnceng/internal/_build/results?buildId=2226244)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2226244/logs/100)||
|[346479](https://dev.azure.com/dnceng-public/public/_build/results?buildId=346479)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/346479/logs/814)||
|[346114](https://dev.azure.com/dnceng-public/public/_build/results?buildId=346114)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/346114/logs/964)||
|[346085](https://dev.azure.com/dnceng-public/public/_build/results?buildId=346085)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/346085/logs/37)||
|[2225817](https://dev.azure.com/dnceng/internal/_build/results?buildId=2225817)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2225817/logs/94)||
|[2225791](https://dev.azure.com/dnceng/internal/_build/results?buildId=2225791)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2225791/logs/47)||
|[345752](https://dev.azure.com/dnceng-public/public/_build/results?buildId=345752)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/345752/logs/705)||
|[345634](https://dev.azure.com/dnceng-public/public/_build/results?buildId=345634)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/345634/logs/771)||
|[345419](https://dev.azure.com/dnceng-public/public/_build/results?buildId=345419)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/345419/logs/679)||
|[2225456](https://dev.azure.com/dnceng/internal/_build/results?buildId=2225456)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2225456/logs/113)||
|[344997](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344997)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344997/logs/856)||
|[344698](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344698)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344698/logs/914)||
|[344678](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344678)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344678/logs/37)||
|[344129](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344129)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344129/logs/777)||
|[343954](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343954)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/343954/logs/667)|dotnet/runtime#88723|
|[343204](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343204)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/343204/logs/933)||
|[343172](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343172)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/343172/logs/37)||
|[2224068](https://dev.azure.com/dnceng/internal/_build/results?buildId=2224068)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2224068/logs/47)||
|[2224038](https://dev.azure.com/dnceng/internal/_build/results?buildId=2224038)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2224038/logs/105)||
|[342556](https://dev.azure.com/dnceng-public/public/_build/results?buildId=342556)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/342556/logs/886)||
|[2223560](https://dev.azure.com/dnceng/internal/_build/results?buildId=2223560)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2223560/logs/114)||
|[2223513](https://dev.azure.com/dnceng/internal/_build/results?buildId=2223513)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2223513/logs/133)||
|[2223490](https://dev.azure.com/dnceng/internal/_build/results?buildId=2223490)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2223490/logs/111)||
|[2223435](https://dev.azure.com/dnceng/internal/_build/results?buildId=2223435)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2223435/logs/101)||
|[341622](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341622)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/341622/logs/905)||
|[2223279](https://dev.azure.com/dnceng/internal/_build/results?buildId=2223279)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2223279/logs/132)||
|[2223226](https://dev.azure.com/dnceng/internal/_build/results?buildId=2223226)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2223226/logs/101)||
|[341572](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341572)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/341572/logs/37)||
|[2223186](https://dev.azure.com/dnceng/internal/_build/results?buildId=2223186)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2223186/logs/116)||
|[2223134](https://dev.azure.com/dnceng/internal/_build/results?buildId=2223134)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2223134/logs/142)||
|[2223121](https://dev.azure.com/dnceng/internal/_build/results?buildId=2223121)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2223121/logs/118)||
|[2223110](https://dev.azure.com/dnceng/internal/_build/results?buildId=2223110)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2223110/logs/52)||
|[2223079](https://dev.azure.com/dnceng/internal/_build/results?buildId=2223079)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2223079/logs/108)||
|[2223049](https://dev.azure.com/dnceng/internal/_build/results?buildId=2223049)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2223049/logs/133)||
|[2223043](https://dev.azure.com/dnceng/internal/_build/results?buildId=2223043)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2223043/logs/148)||
|[341305](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341305)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/341305/logs/930)||
|[2223025](https://dev.azure.com/dnceng/internal/_build/results?buildId=2223025)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2223025/logs/133)||
|[2223012](https://dev.azure.com/dnceng/internal/_build/results?buildId=2223012)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2223012/logs/133)||
|[2222998](https://dev.azure.com/dnceng/internal/_build/results?buildId=2222998)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2222998/logs/107)||
|[2222960](https://dev.azure.com/dnceng/internal/_build/results?buildId=2222960)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2222960/logs/118)||
|[2222944](https://dev.azure.com/dnceng/internal/_build/results?buildId=2222944)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2222944/logs/133)||
|[2222915](https://dev.azure.com/dnceng/internal/_build/results?buildId=2222915)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2222915/logs/114)||
|[2222903](https://dev.azure.com/dnceng/internal/_build/results?buildId=2222903)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2222903/logs/143)||
|[341090](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341090)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/341090/logs/907)||
|[341070](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341070)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/341070/logs/37)||
|[2222835](https://dev.azure.com/dnceng/internal/_build/results?buildId=2222835)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2222835/logs/73)||
|[340960](https://dev.azure.com/dnceng-public/public/_build/results?buildId=340960)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/340960/logs/939)||
|[2222775](https://dev.azure.com/dnceng/internal/_build/results?buildId=2222775)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2222775/logs/127)||
|[2222765](https://dev.azure.com/dnceng/internal/_build/results?buildId=2222765)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2222765/logs/115)||
|[340683](https://dev.azure.com/dnceng-public/public/_build/results?buildId=340683)|dotnet/runtime|Build Mono LLVM AOT cross compiler|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/340683/logs/898)||
|[340670](https://dev.azure.com/dnceng-public/public/_build/results?buildId=340670)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/340670/logs/31)||
|[2222634](https://dev.azure.com/dnceng/internal/_build/results?buildId=2222634)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2222634/logs/110)||
Displaying 100 of 119 results
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|119|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=323893
**Error message validated:** `Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 6/28/2023 9:28:40 PM UTC

**Comment by directhex** [comment]
Nothing to do with ZLIB, that's just CMake lying to you. The true build error here is `clang-16: error: unable to execute command: Executable "ld" doesn't exist!`, because we aren't passing a value for `-fuse-ld=lld` via LDFLAGS because we aren't passing a value for `-DCMAKE_TOOLCHAIN_FILE=` in this specific scenario. Read on for the full analysis.

Once upon a time, we had two code paths in mono.proj - `Target Name="BuildMonoRuntime"` which compiled a runtime against `$(TargetOS)-$(TargetArchitecture)`, and `Target Name="BuildMonoCross"` which compiled a cross-compiler (runtime) against `$(HostOS)-$(BuildArchitecture)` with the codegen targeting `$(TargetOS)-$(TargetArchitecture)`.

So, for example, build for `android-arm` on an x64 Mac and you'd get `BuildMonoRuntime` generating an `android-arm` `libmonosgen.so` and `BuildMonoCross` generating an `osx-x64` `mono-aot-cross`. Strict 1:1 mapping (i.e. no consistent way to produce multiple cross-compilers for the same target, or any cross-compiler for a different target than the host)

In 2021 I wrote a new build system, intended to allow a many:many relationship, and part of that was changing `BuildMonoCross` to deal with the difference between "generate code for RID" and "compile code for RID". I kept the old method working, in order to not break anyone's workflow, but it became deprecated & basically abandoned, other than for these LLVM AOT lanes.

Fast forward to recently, when we started building everything possible with CBL-Mariner. One of the changes forced by Mariner is treating all compiles as cross-compiles - instead of "compile for the host which is always x64 or cross-compile for the OS in /crossrootfs", all architectures are cross-compiles. This is great! However, it runs into a problem with the legacy-BuildMonoCross lanes like this one, because we cannot `BuildMonoRuntime` using an `arm64` crossrootfs and `BuildMonoCross` using an `x64` crossrootfs - we have no Docker images containing both crossroots at once.

This is the patch to enable cross-compiler mode for legacy `BuildMonoCross`:

```
diff --git a/src/mono/mono.proj b/src/mono/mono.proj
index de64d7d3440..c187b348c1a 100644
--- a/src/mono/mono.proj
+++ b/src/mono/mono.proj
@@ -665,6 +665,12 @@
   <!-- Build AOT cross compiler (if available) -->
   <Target Name="BuildMonoCross" Condition="'$(BuildMonoAOTCrossCompiler)' == 'true'" DependsOnTargets="BuildMonoRuntime">
 
+    <!-- Legacy cross-compiler mode (build cross compiler for host CPU/OS) -->
+    <PropertyGroup Condition="'$(RealTargetOS)' == '' and '$(RealTargetArchitecture)' == ''">
+      <RealTargetOS>$(HostOS)</RealTargetOS>
+      <RealTargetArchitecture>$(BuildArchitecture)</RealTargetArchitecture>
+    </PropertyGroup>
+
     <!-- iOS/tvOS specific options -->
     <PropertyGroup Condition="'$(TargetstvOS)' == 'true' or '$(TargetsiOS)' == 'true'">
       <!-- FIXME: Disable for simulator -->
```

But it won't work. Therefore we have three choices:

1. Don't use Mariner for this lane, revert to whatever we were using before
2. Create a new multi-targeting Mariner docker image, and use that (passing an overridden crossrootfs property where needed to the appropriate targets, since we assume we use the same property throughout)
3. Split this job in two - an offset generation job using an arm64 crossrootfs, and the AOT compiler job using an x64 crossrootfs (this is basically the model for official builds, where we generate offsets in `eng/pipelines/mono/templates/generate-offsets.yml` and consume them in `eng/pipelines/common/global-build-job.yml` using `/p:MonoCrossAOTTargetOS=OSNAMEFROMMONOAOTCROSSDOTPROJ /p:SkipMonoCrossJitConfigure=true /p:BuildMonoAOTCrossCompilerOnly=true`

**Comment by kotlarmilos** [comment]
Thanks for the explanation. It sounds to me that the 3rd option is aligned with the official builds and may be a path we want to consider. If that makes sense, I can try to split this job into offset generation and the AOT compilation.

**Comment by SamMonoRT** [comment]
@directhex @kotlarmilos @steveisok - Milos reminded me of this while checking on another PR We need to move forward with this, given a lack of desktop full aot llvm lane. Two things we should do asap - 1. Disable this lane (even in extra-platforms) prior to RC1 cutoff. 2. Work on option 3 suggested above for 9.0 (essentially at the earliest once RC1 is out of the way next week). For this we will need some help understanding the cross-compiler/official build. 

Moving this to 9.0, but we need to disable the lane prior to rc1 cutoff for cleaner CI.

**Comment by steveisok** [comment]
> Moving this to 9.0, but we need to disable the lane prior to rc1 cutoff for cleaner CI to remove the blocking green ci tag

@directhex can you please do this before Monday's cutoff?
