### ISSUE TITLE
[API Proposal]: Implement IDirectoryContents on PhysicalDirectoryInfo at MS.Extensions.FileProviders.Physical

### ISSUE THREAD

**Issue by vpenades** [dotnet/runtime#86354]
### Background and motivation

`Microsoft.Extensions.FileProviders.Abstractions` provides a basic set of interfaces that allow accessing the file system.

The default implementation, `Microsoft.Extensions.FileProviders.Physical` , wraps `FileInfo` and `DirectoryInfo` , and the context is initialized using a `PhysicalFileProvider`, which, as I understand it, might be used at the directory root, or any directory that can be considered the "local root"

The problem:

`PhysicalFileProvider` implements `IDirectoryContents`  which gives the list of `IFileInfo` items contained in the root directory, which are represented by both _files_ and _directories_ , the latter being implemented by a `PhysicalDirectoryInfo` , which implements `IFileInfo`, but does not implement `IDirectoryContents` , and as a consequence of this, it's not possible to traverse the file system tree beyond the 1st directory level provided by `PhysicalFileProvider`

### API Proposal

```csharp
namespace Microsoft.Extensions.FileProviders.Physical
{
    public class PhysicalDirectoryInfo : IFileInfo, IDirectoryContents  
    {
        // IDirectoryContents implementation
    }
```

### API Usage

```csharp
class Utils
{
    public static void RecursivelyTraverseTree(IDirectoryContents contents)
    {
        foreach (var entry in contents)
        {
            if (entry.IsDirectory)
            {
                if (entry is IDirectoryContents childContents)
                {
                    RecursivelyTraverseTree(childContents);
                }                
            }
        }           
    }
}
```

### Alternative Designs

Alternatively, PhysicalDirectoryInfo could implement `IFileProvider `instead of `IDirectoryContents ` because the latter can be retrieved from the former.

Anyway, I am open to proposals to know how to traverse a file system tree based on IFileInfo abstractions, without taking assumptions about the underlaying implementation.

**Comment by Jozkee** [comment]
As a workaround, you could just create a PhysicalDirectoryContents using PhysicalDirectoryInfo.PhysicalPath, no?

**Comment by vpenades** [comment]
> As a workaround, you could just create a PhysicalDirectoryContents using PhysicalDirectoryInfo.PhysicalPath, no?

No, the point of using the interfaces is to have an abstraction layer that does not implicitly assume there's a physical path. In fact I want to create virtualized file systems, or file system from within archives, where PhysicalPath would throw an exception.

**Comment by bartonjs** [comment]
Looks good as proposed

```diff
namespace Microsoft.Extensions.FileProviders.Physical
{
    public partial class PhysicalDirectoryInfo : IFileInfo
+       , IDirectoryContents  
    {
        // IDirectoryContents implementation
    }
