### ISSUE TITLE
.Net 6 System.Process.Start cannot launch a self contained .net core 2.2 web app

### ISSUE THREAD

**Issue by Craig-TSS** [dotnet/runtime#86368]
### Description

I have an application (asp.net core web app, ie console app) which we use for launching other applications in Windows. Our current launcher system is built on .net core 2.2 and has been working well for many years now. I've been working on upgrading it to .net 6 for obvious reasons, however I cant for the life of me get the launching to work correctly in .net 6. It seems the behavior of Process.Start has changed. 

Whenever I attempt to run the app from the launcher, it fails with
Application: ServerToLaunch.exe
CoreCLR Version: 4.6.28207.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Reflection.Assembly.GetType(String name, Boolean throwOnError)
   at System.StartupHookProvider.CallStartupHook(String assemblyPath)
   at System.StartupHookProvider.ProcessStartupHooks()

The app being run is a published (self contained, x86) net core 2.2 app. The file referenced exists at its location and working directory appears to be getting set correctly.

### Reproduction Steps

[WebLauncherIssue.zip](https://github.com/dotnet/runtime/files/11494069/WebLauncherIssue.zip)

- Load the attached solution
- Build the solution
- Right click the "ServerToLaunch" project and choose publish. Select the x86 profile and publish it.
- Start Debugging the "WebLauncherIssue" project
- It will load the default controller. Change the url path to launch/x86, eg http://localhost:5085/launch/x86 to trigger a launch attempt of the published app. You will see the cmd prompt appear and show the error reported.
- Stop the debugging session
- Start debugging the "WebLauncherNetCore2" project instead and do the same thing, you will see this launches the published app correctly. The launcher code in this project is identical, its just in .net core 2.2 instead of .net 6

### Expected behavior

The .net core 2.2 console application should launch correctly

### Actual behavior

The application fails with exception code 0xe0434352
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

### Regression?

This worked fine in .net core 2.2

### Configuration

I am running on Windows 11 x64

### Other information

I need the process to be launched separately from the launcher (ie not a child process), so I set UseShellExecute = true
If i take the exact parameters/working dir used by the launcher and do them in a command prompt instead, it works fine. I also tried creating a batch file that explicitly changes directory then runs the app and having the launcher try to run that bat file instead, but same result. I have also tried launching a x64 version of the self contained app but that also made no difference. I have tried using a 3rd party process wrapper CliWrap as well, but that has the same problem in .net 6.

Interestingly .net 6 Process.Start is able to launch Windows Forms apps (both .net framework 4.6.1 and .net 6) just fine. I have also tested launching another self contained x86 .net 6 web (console) app and that also works fine. It seems like the issue might be specific to launching .net core 2.2 apps. 

I need to be able to get this function to work correctly in .Net 6 for the migration to .Net 6 to be feasible for this project. .Net 7 is not an option due to the lack of Windows 7 support, unfortunately in my industry there are still a lot of custom Windows 7 SP1 machines out there.

Any help resolving this would be much appreciated.

**Comment by Craig-TSS** [comment]
I have also run some additional tests and have found the following. Launch code is identical, just different target frameworks.
Launcher (.NetCore 2.2)
- CAN launch .net core 2.2 console app (published -> self contained)
- CAN launch .net 6 console app (published -> self contained)
- CAN launch .net framework 4.6.1 app
- CAN launch .net 6 win forms apps

Launcher (Net 6)
- **FAILS** to launch .net core 2.2 console app (published -> self contained)
- CAN launch .net 6 console app (published -> self contained)
- CAN launch .net framework 4.6.1 app
- CAN launch .net 6 win forms apps

**Comment by Craig-TSS** [comment]
I am just running the published (self contained) exe directly and don't explicitly set any environment variables. 

There is a link to a sample project reproducing the issue above in the Reproduction Steps section of the OP. You can see exactly what code I am using to run it in there.

**Comment by Craig-TSS** [comment]
So it does look like it is related to Visual Studio, running the launcher with or without the debugger attached always fails to launch the .net core 2.2 app, however if i instead publish the launcher as a self contained exe and run it from the command line instead, then it is actually able to successfully launch the .net core 2.2 app.

So is there a way to get it to work while running from VS as well?

**Comment by jkotas** [comment]
> So is there a way to get it to work while running from VS?

Try disabling hot reload (Debug / Options / Hot reload).

What is your Visual Studio version? IIRC, this issue is fixed in VS2022.

**Comment by feiyun0112** [comment]
you need remove some Environment Variables when run in VS

```
private void Launch(string target)
        {
            FileInfo fi = new FileInfo(target);

            ProcessStartInfo startInfo = new ProcessStartInfo(fi.FullName);
            foreach(string key in startInfo.EnvironmentVariables.Keys)
            {
                if (key.StartsWith("DOTNET_"))
                {
                    Console.WriteLine($"{key}={startInfo.EnvironmentVariables[key]}");
                    startInfo.EnvironmentVariables.Remove(key);
                }
            }
            
            startInfo.Arguments = "";
            startInfo.WorkingDirectory = fi.DirectoryName;
            
            startInfo.UseShellExecute = false;
            startInfo.RedirectStandardOutput = true;

            // execute the process
            var process = new Process();

            process.StartInfo = startInfo;
            process.EnableRaisingEvents = true;
            
            process.Start();
 
        }
```

**Comment by Craig-TSS** [comment]
Thanks @feiyun0112 that has resolved the issue when running from VS.
