### ISSUE TITLE
[API Proposal]: Expose options to only generate one direction for generated COM interfaces

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#86360]
### Background and motivation

Currently, users must provide support in custom marshallers for `[GeneratedComInterface]` APIs for both managed-to-unmanaged and unmanaged-to-managed. Many COM interfaces are meant to be consumed from managed code either by calling into a COM component implemented elsewhere or implementing a COM component that will be called from non-.NET code. This proposal adds members on the `[GeneratedComInterface]` attribute to support turning off either the managed->unmanaged or the unmanaged->managed direction of code-gen.

### API Proposal

```diff
namespace System.Runtime.InteropServices.Marshalling;

+ [Flags]
+public enum ComInterfaceOptions
+ {
+     ManagedObjectWrapper = 0x1,
+     ComObjectWrapper = 0x2,
+ }

[AttributeUsage(AttributeTargets.Interface)]
public sealed class GeneratedComInterfaceAttribute
{
+    public ComInterfaceOptions Options { get; } = ComInterfaceOptions.ManagedObjectWrapper | ComInterfaceOptions.ComObjectWrapper;
}
```

### API Usage

```csharp
[GeneratedComInterface(Options = ComInterfaceOptions.ManagedObjectWrapper)]
[Guid("e7ba7579-49ec-4d6a-905b-87fb4e476e36")]
interface IFoo
{
     void Bar();
}
```

### Alternative Designs

- Continue to require developers to handle marshallers going in both directions.
- Use two `bool` properties instead of an enum.

**Comment by Sergio0694** [comment]
Love this 😄

Just out of curiosity, would there be any benefits other than binary size reduction from turning off either marshalling side, or would it be just for that? Not that it'd be a bad thing, just wondering if disabling either of those properties would also being any wins for perf or other things 🙂

**Comment by jkoritzinsky** [comment]
No it’s really just to generate less code. There’s no other improvements this would provide.

**Comment by AaronRobinsonMSFT** [comment]
I'm fine with two `bool` values, but is there any argument for an `enum`?

**Comment by jtschuster** [comment]
I generally would prefer enums, my only thought is to avoid "ManagedToUnmanaged" and "UnmanagedToManaged" enum values. We usually mean that in the caller to callee, but with COM object, a runtime object pass from Managed to Unmanaged is called from Unmanaged to Managed, so that could be confusing IMO.

**Comment by jkoritzinsky** [comment]
I've updated the proposal to use an enum. Let me know what you think of the naming/shape!

**Comment by Sergio0694** [comment]
I like it! Nit: I feel the "Generated" prefix on the enum isn't strictly necessary, and removing it might make the type potentially more general, which might or might not be potentially useful in other scenarios in the future? Other than that LGTM 😄

**Comment by bartonjs** [comment]
namespace System.Runtime.InteropServices.Marshalling;

```C#
[Flags]
public enum ComInterfaceOptions
{
     None = 0,
     ManagedObjectWrapper = 0x1,
     ComObjectWrapper = 0x2,
}

[AttributeUsage(AttributeTargets.Interface)]
public sealed partial class GeneratedComInterfaceAttribute
{
    public ComInterfaceOptions Options { get; set; } = ComInterfaceOptions.ManagedObjectWrapper | ComInterfaceOptions.ComObjectWrapper;
}
```

**Comment by jkoritzinsky** [comment]
It looks like for attributes, we usually just do `get; set;`, so the setter is correct.
