### ISSUE TITLE
Blazor WASM Hosted app fails to run when Nuget Packages upgraded to 8.0.0-preview-4.23260.4

### ISSUE THREAD

**Issue by GraemeWellington** [dotnet/runtime#86364]
### Description

Creating a new Blazor WASM Hosted app in version `8.0.0-preview-3.23177.8` works ok
Upgrading the Nuget Packages for Server/Client to version `8.0.0-preview-4.23260.4` fails to run
```
Console error: Reason: TypeError: r.withStartupOptions is not a function
at Wt (blazor.webassembly.js:1:54519)
(anonymous) @ blazor.webassembl
```
### Reproduction Steps

Open Microsoft Visual Studio Community 2022 (64-bit) - Preview : Version 17.7.0 Preview 1.0
Create new project
Blazor WASM Hosted - this creates a project with .Net8 version: `8.0.0-preview-3.23177.8`
Run the application - works ok
Upgrade Nuget Packages for Server / Client to 8.0.0-preview-4.23260.4
Run the application - fails to run {stops loading)
```
Console Error: Reason: TypeError: r.withStartupOptions is not a function
    at Wt (blazor.webassembly.js:1:54519)
(anonymous) @ blazor.webassembl
```
### Expected behavior

Application should run as for previous version

### Actual behavior

Application fails at loading state

**Comment by radical** [comment]
cc @maraf @pavelsavara

**Comment by lambdageek** [comment]
@GraemeWellington Are you just upgrading the nuget references without installing the .NET 8 Preview 4 SDK?

**Comment by GraemeWellington** [comment]
Hi Aleksey

In my haste I neglected to install the .Net 8 Preview 4 SDK.

This now installed and problem solved.

Thank for your assistance.

***@***.***
