### ISSUE TITLE
[wasm][debugger] KeepNativeSymbols=true breaks SteppingTests.SkipWasmFunctionsAccordinglyJustMyCode

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#86387]
If you build a runtime with `-p:KeepNativeSymbols=true` and then run the debugger testsuite, `SteppingTests.SkipWasmFunctionsAccordinglyJustMyCode` will fail.

Note that we don't ship `KeepNativeSymbols`, so this is purely something that is a papercut when working on dotnet/runtime itself.

Repro steps:
```
./build.sh --os browser -c Debug -bl -nr:false -p:KeepNativeSymbols=true
```

then

```
make -C src/mono/wasm run-debugger-tests CONFIG=Debug TEST_FILTER='~SteppingTests.SkipWasmFunctionsAccordinglyJustMyCode'
```

**Comment by lambdageek** [comment]
This is probably related to given how we look for stack frames in `MonoProxy.SendCallStack`:

https://github.com/dotnet/runtime/blob/7692f981f825bb9aec8d6eba7e12054c6dcdfaee/src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs#L1119-L1133

With `KeepNativeSymbols` it's possible that some of those `wasm-function` symbols will have real names instead

**Comment by pavelsavara** [comment]
cc @thaystg

**Comment by thaystg** [comment]
This test is expected to not work in debug runtime builds, only in release.
