### ISSUE TITLE
[wasm] Unable to get the value for a local when debugging a Blazor app

### ISSUE THREAD

**Issue by dkboon01** [dotnet/runtime#86395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Using Visual Studio 2022 , .net 7 in a blazor wasm application.   Are there any improvements coming in .net 8 for the debugger in Blazor WASM?  For instance being able to see the value in the settlementdate variable in the attached print screen.  It says busy  below and when busy goes away you still can't see the value.   The only way to get the value is to do Console.WriteLine statements which is not very productive.  I would think the debugger in Blazor WASM would be a high priority so that more developers would use blazor.    Troubleshooting code is where we spend a majority of time as developers and this is frustrating when you can't see the value when debugging. 
![Screenshot 2023-05-17 101032](https://github.com/dotnet/aspnetcore/assets/11353230/040a3531-d10e-41e7-8a3c-065cc9b70fc1)

### Describe the solution you'd like

I want the ability to see variables in the blazor wasm debugger watch window

**Comment by thaystg** [comment]
@dkboon01 what is the type of the variable settlementdate? Can you share with me a small code to reproduce it?
Also, can you see the value of settlementdate in the locals window?

**Comment by dkboon01** [comment]
I'm trying to get the code where the problem still exist but I'm not giving the entire solution.  The solution is quite large.  When I try it in a very small project and a very small record layout, it is working.  I will try over the weekend to separate out the existing (problem code) into a smaller solution to see if the problem still exists. Currently, this piece of code is in a huge solution all in blazor wasm. I'm wondering if it is a memory issue where just alot of rows of data, the list has too many columns or if our solution is so large that the debugger is just having a problem with size.

**Comment by lewing** [comment]
@ilonatommy can you try to reproduce this?

**Comment by ilonatommy** [comment]
> I will try over the weekend to separate out the existing (problem code) into a smaller solution to see if the problem still exists.

@dkboon01, did you succeed? It would be helpful to have a repro. Could you share the VS logs when it fails (from "C:\Users\USER\AppData\Local\Temp\visualstudio-js-debugger.txt")?
