### ISSUE TITLE
HTTPClient throw many System.IO.IOException in .NET6 & .NET7

### ISSUE THREAD

**Issue by howing0345** [dotnet/runtime#86422]
### Description

Recently when I am debugging program in .NET 6, I found that it throw tons of System.IO.IOException after the program started.
![image](https://github.com/dotnet/runtime/assets/133934648/ee266106-1846-437c-9570-94f7dda3b345)

This doesn't appear before. I create a new .NET 6 console project and do a simple get request to Google, after 75 second it will throw the System.IO.IOException, but I try the same code in .NET 5 and it would not throw any exception. In .NET 7 this issue is still appear. I found another computer and install Visual Studio to test the code, the exception will not throw in the Visual Studio, but if I using the dnSpy to debug the program it appear again.
![image](https://github.com/dotnet/runtime/assets/133934648/4cc820f9-e475-4db3-92ef-113c3a1dc459)

Look like due to the HTTPClient issue, when I am using Google.Cloud.PubSub.V1 library, it throw massive System.Threading.Tasks.TaskCanceledException & Grpc.Core.RpcException.
![image](https://github.com/dotnet/runtime/assets/133934648/0425cc0f-4800-495b-ae35-c8410f63b9f3)

I read some article and found a similar case: https://www.reddit.com/r/AskProgramming/comments/soy6sq/systemioioexception_that_doesnothing/

After trying `Client.DefaultRequestHeaders.ConnectionClose = true;`, it can solve the problem, but I think this is cure the symptoms, not the disease. Because I don't need to do this in .NET 5, and it is very trouble to config the HTTPClient in Grpc.Net.Client which used by Google.Cloud.PubSub.V1 library.

### Reproduction Steps

```c#
namespace Net6_Test;
class Program
{
    internal static HttpClient Client;
    static void Main(string[] args)
    {
        Client = new();
        _ = GetGoogle();
        Console.WriteLine("Test");
        Console.ReadKey();
    }
    static async Task GetGoogle()
    {
        var response = await Client.GetAsync("https://www.google.com");
        Console.WriteLine(response);
        Console.WriteLine(await response.Content.ReadAsStringAsync());
    }
}
```

### Expected behavior

No exception will throw after sending the request.

### Actual behavior

Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..

![image](https://github.com/dotnet/runtime/assets/133934648/f2277576-fcdc-41c3-986c-f6996f1448aa)
![image](https://github.com/dotnet/runtime/assets/133934648/5920d076-9505-49e5-8279-7b78fe5827e0)
![image](https://github.com/dotnet/runtime/assets/133934648/7f65a894-8dc4-4ac6-9834-82ba798fa071)
![image](https://github.com/dotnet/runtime/assets/133934648/7463d66f-b0c7-469f-a05b-ef2ea8a66236)
![image](https://github.com/dotnet/runtime/assets/133934648/2f74ebdd-b275-46cc-817e-6856ee623fca)
![image](https://github.com/dotnet/runtime/assets/133934648/40f46464-7bfb-4aa0-aac7-ad45342c79ac)

Google.Cloud.PubSub.V1& Grpc.Net.Client Exception
Exception thrown: 'Grpc.Core.RpcException' in Grpc.Net.Client.dll
Status(StatusCode="Unavailable", Detail="The service was unable to fulfill your request. Please try again. [code=8a75]")
![image](https://github.com/dotnet/runtime/assets/133934648/cd7941da-a305-4383-8c64-acce9b29dac2)

### Regression?

In .NET 5 it is normal

### Known Workarounds

`Client.DefaultRequestHeaders.ConnectionClose = true;`

### Configuration

.NET SDK 6.0.408
Desktop Runtime - 6.0.16
Windows 10 22H2

### Other information

.

**Comment by wfurt** [comment]
this looks like possibly environmental issue - especially if you cannot always reproduce one separate computer. You should probably take packet captures with Wireshark and compare what is going on the network layer. The IO  exception is likely result of some external events.

**Comment by howing0345** [comment]
> this looks like possibly environmental issue - especially if you cannot always reproduce one separate computer. You should probably take packet captures with Wireshark and compare what is going on the network layer. The IO exception is likely result of some external events.

Not sure is the environmental issue, I have some remote computer which run the same program at different location and ISP, and all of them throw the error when debug by dnSpy.

**Comment by howing0345** [comment]
Hi @wfurt, I just capture the packet by Microsoft Network Monitor, hope these photo help.

NET 5
![Net5 Netmon](https://github.com/dotnet/runtime/assets/133934648/4197f618-b8d4-4792-8721-40a225921ed7)

NET6
![Net6 Netmon](https://github.com/dotnet/runtime/assets/133934648/c3a10c83-7fb0-4e96-ba56-f88485984cb6)

**Comment by howing0345** [comment]
After discussing in Facebook group, look like it is due to the change of `System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)` method
In .NET 5, it look like this:
![image](https://github.com/dotnet/runtime/assets/133934648/bb5d6b13-1a14-49b6-8026-dd323d109478)

But in .NET 6, it becomes this:
![image](https://github.com/dotnet/runtime/assets/133934648/5c56d605-4c6e-455e-ab13-cf7b18d00fcf)

It also thorw exception if `SocketError.ConnectionAborted`.

**Comment by MihaZupan** [comment]
Seeing the exception multiple times in the debugger may just mean that you're looking at the async stack unwinding and rethrowing exceptions before it reaches the actual calling code, not a meaningful behavioral difference.

Are you seeing any observable differences in behavior between versions (ignoring the debugger exception view)?

**Comment by howing0345** [comment]
No if I not debugging it. But look like this will cause error when using Google Cloud Pub/Sub library when debugging.

**Comment by karelz** [comment]
@howing0345 do you get the same problem when you don't catch first-chance exceptions?
Perhaps the failure is time sensitive under debugger when you manually resume exceptions.

Either way, it does not seem to be very actionable for us to act on. If you have a small repro (ideally without Google library / gRPC), then perhaps it might be actionable.

**Comment by karelz** [comment]
No response for 3 week, closing. Feel free to reopen when there is more info available to make it actionable. Thanks!
