### ISSUE TITLE
[NativeAOT] Implement support for `UnsafeAccessorAttribute`

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#86438]
Implement https://github.com/dotnet/runtime/issues/81741 for NativeAOT.

- [x] Implement the stub generation for the extern methods - https://github.com/dotnet/runtime/pull/86932
- [x] Add tests - or make sure we can run the tests added in CoreCLR using NativeAOT - https://github.com/dotnet/runtime/pull/86932
- [x] There's probably no need for direct trimming work - so just make sure that the trimming tests added for illink also run on NativeAOT

See https://github.com/dotnet/runtime/issues/86161 for CoreCLR support

**Comment by AaronRobinsonMSFT** [comment]
@vitek-karas Can we close this now?

**Comment by vitek-karas** [comment]
Yes - this is done I think.
