### ISSUE TITLE
Convert not grace handling boundary values of integer types when converting from floating point representations

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/runtime#86439]
### Description

`Convert.ToInt32` and `Convert.ToInt64` are not grace handling values close (or equal to) `MaxValue`/`MinValue` of the respective types (`OverflowException` is thrown).

This is given by the fact that IEEE 754 implementations need to represent those values utilizing exponent, hence losing precision and conversion back to integer type can overflow.

This diverges from the documented behavior:
https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System/Convert.xml#L11740-L11741

So it would be good to either explicitly document this, or adjust `Convert` to handle the boundary values (as suggested in the workaround section)

### Reproduction Steps

```csharp
Convert.ToInt32((float) int.MaxValue);
Convert.ToInt64((double) long.MaxValue);
```

Due to the loss of precision (as exponent need to be used) - it's not a problem only for the exact boundaries, but a close range to them:

```
Convert.ToInt32((float)(int.MaxValue - 10));
Convert.ToInt64((double)(long.MaxValue - 100));
```

### Expected behavior

Convert works for the supported range of the target type. IAW, this code should never throw

```csharp
bool TryConvertToLong(double value, out long result)
{
  if(value > long.MaxValue || value < long.MinValue)
  {
     result = 0;
     return false;
  }

  result = Convert.ToIn64(value);
  return true;
}
```

### Actual behavior

The above code throws `OverflowException` for values close to long boundaries. e.g. `TryConvertToLong((double) long.MaxValue)`

### Regression?

No

### Known Workarounds

Explicitly handle the bounderies (similarly as is done in [CreateTruncating/CreateSaturating](https://github.com/dotnet/runtime/blob/1ffe321285f2f16ea2eff5f623ef14a0b1b48249/src/libraries/System.Private.CoreLib/src/System/Int64.cs#L1070-L1075)):

```csharp
bool TryConvertToLong(double value, out long result)
{
  if(value > long.MaxValue || value < long.MinValue)
  {
     result = 0;
     return false;
  }

  result = (value  >= long.MaxValue) ? long.MaxValue : (value <= long.MinValue) ? long.MinValue : (long)value;
  return true;
}
```

**Comment by tannergooding** [comment]
This is expected and correct behavior.

`double` can only accurately represent integral values up to `2^53` and `float` only up to `2^24`. Values above this range will lose precision and round to their nearest representable result.

Thus, `int.MaxValue` cannot be represented as a `float` and `long.MaxValue` cannot be represented as a `double`, instead they round to the nearest representable value which happens to be `2147483648` (`int.MaxValue + 1`) and `9223372036854775808` (`long.MaxValue + 1`).

These rounded values are outside the range of `int`/`long`, respectively and so must throw. There is likewise no way to differentiate between a value that was actually `2147483648` and one that was rounded (either up or down) to `2147483648`, so there is no special handling that could be added to handle this scenario either.

The delta between `2147483648` and the next smallest representable value for `float` is `128` (that is the next smallest representable value is `2147483520`) and so all numbers greater than or equal to `2147483584` will round up, making `2147483583` the largest `int` that won't cause overflow when converted to `float` and then back to `int` (it will still cause a loss of precision and return `2147483520`).

The delta for `double` at this range is `1024` and similar rules apply.

**Comment by JanKrivanek** [comment]
While strictly technically true that `(double) long.MaxValue > long.MaxValue` (as LHS rounds to `long.MaxValue + 1`), so strictly technically the `Convert` specification is right, however evaluation of such equation leads to same rounding of RHS, and hence confusing results when trying to guard the boundaries:

```
bool TryConvertToLong(double value, out long result)
{
  if(value > long.MaxValue || value < long.MinValue)
  {
     result = 0;
     return false;
  }

  // This still can throw, as above equation cannot filter out rounded-up values close to the MaxValue
  result = Convert.ToIn64(value);
  return true;
}
```

That being said - should [the `Convert` documentation](https://learn.microsoft.com/en-us/dotnet/api/system.convert.toint64?view=net-7.0#system-convert-toint64(system-double)) mention this caveat?

**Comment by JanKrivanek** [comment]
Btw. why the [`Convert.ToInt32(double value)`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Convert.cs#L1059-L1082) explicitly handles the representability differences as opposed to [`Convert.ToInt64(double value)`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Convert.cs#L1308-L1311)?

Should we apply similar approach in the latter, to make sure it sticks to it's definition?

**Comment by JanKrivanek** [comment]
Thank you @tannergooding for the details!
