### ISSUE TITLE
Add a `JsonTypeInfoResolver.WithModifier` extension method

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#86440]
### Background and motivation

When contract customization was launched in .NET 7, we included a `Modifiers` property in the `DefaultJsonTypeInfoResolver` class which let users introduce tweaks to the reflection-based contract:

```C#
var options = new JsonSerializerOptions
{
    TypeInfoResolver = new DefaultJsonTypeInfoResolver
    {
        Modifiers = 
        {
           static typeInfo =>
           {
                foreach (JsonPropertyInfo prop in typeInfo.Properties)
                {
                    prop.Name = prop.PropertyType.Name.ToUpperInvariant();
                }
           }
        }
    }
};
```

This particular pattern is not exclusive to reflection-based serialization, but can be applied to the `IJsonTypeInfoResolver` abstraction in the general case. At this point however, we have no baked-in API that lets users do this easily.

### API Proposal

```diff
namespace System.Text.Json.Serialization.Metadata;

public static class JsonTypeInfoResolver
{
    public static IJsonTypeInfoResolver Combine(params IJsonTypeInfoResolver?[] resolvers);
+   public static IJsonTypeInfoResolver WithAddedModifier(this IJsonTypeInfoResolver resolver, Action<JsonTypeInfo> modifier);
}
```

### API Usage

Users can now specify modifiers on top of source generated metadata:
```C#
var options = new JsonSerializerOptions
{
    TypeInfoResolver = SourceGenerationContext.Default
        .WithModifier(
            static typeInfo =>
            {
                foreach (JsonPropertyInfo prop in typeInfo.Properties)
                {
                    prop.Name = prop.PropertyType.Name.ToUpperInvariant();
                }
            })
};
```

### Alternative Designs

The method could be made to accept a param array of modifiers:
```diff
namespace System.Text.Json.Serialization.Metadata;

public static class JsonTypeInfoResolver
{
    public static IJsonTypeInfoResolver Combine(params IJsonTypeInfoResolver?[] resolvers);
+   public static IJsonTypeInfoResolver WithModifiers(this IJsonTypeInfoResolver resolver, params Action<JsonTypeInfo>[] modifiers);
}
```
But I figured it might be preferable if multiple callbacks are chained using fluent-style chaining:
```C#
resolver.WithModifier(modifier1).WithModifier(modifier2);
```

**Comment by bartonjs** [comment]
This came up in API Review, and we were unclear what the semantics of the method should be.

If it's creating a clone and then appending the new modifier, then we think a name like `WithExtraModifier`/`WithAdditionalModifier`/etc is appropriate.  If it's clearing and assigning only the one, then a different name would be better.

The alternative proposal (params `WithModifiers`) definitely suggests full replacement.

**Comment by eiriktsarpalis** [comment]
Renamed the proposed method to `WithAddedModifier`.

**Comment by terrajobst** [comment]
* Looks good as proposed
* 
```C#
namespace System.Text.Json.Serialization.Metadata;

public static partial class JsonTypeInfoResolver
{
    public static IJsonTypeInfoResolver WithAddedModifier(this IJsonTypeInfoResolver resolver, Action<JsonTypeInfo> modifier);
}
```
