### ISSUE TITLE
Feature request: treat Memory/ReadOnlyMemory<T> as T[] in System.Text.Json

### ISSUE THREAD

**Issue by sandersaares** [dotnet/runtime#86442]
EDIT: see https://github.com/dotnet/runtime/issues/86442#issuecomment-1605362904 for API proposal.

<details><summary>Original Proposal</summary>
<p>

I would like System.Text.Json to serialize/deserialize `Memory/ReadOnlyMemory<T>` using the same logic as it uses for `T[]`.

This implies:

* `Memory<byte>` should be base64-encoded just like `byte[]` is
* `Memory<FooBar>` should be serialized as appropriate for the type `FooBar`, same as `FooBar[]` would.

The main motivation is that I have an array from `ArrayPool<T>.Shared`, which can have space for more items than I actually need. To serialize only a segment of the array, I would like to use `Memory<T>` to identify only use "used" part of the array.

</p>
</details>

**Comment by eiriktsarpalis** [comment]
Also related to https://github.com/dotnet/runtime/issues/73500, https://github.com/dotnet/runtime/issues/81970 and https://github.com/dotnet/runtime/issues/60780. One concern that has prevented us from adding built-in support for more types is trimmed application size, although this has become less of an issue for apps that only source generators.

**Comment by eiriktsarpalis** [comment]
Provisional API proposal:
```C#
namespace System.Text.Json.Serialization.Metadata

public partial class JsonMetadataServices
{
    // Similar to byte[] serializes as Base64 strings
    public static JsonConverter<Memory<byte>> MemoryByteConverter { get; }
    public static JsonConverter<ReadOnlyMemory<byte>> ReadOnlyMemoryByteConverter { get; }

    // Other element types serialize as JSON arrays
    public static JsonTypeInfo<Memory<TElement>> CreateMemoryInfo<TElement>(JsonSerializerOptions options, JsonCollectionInfoValues<Memory<TElement>> collectionInfo);
    public static JsonTypeInfo<ReadOnlyMemory<TElement>> CreateReadOnlyMemoryInfo<TElement>(JsonSerializerOptions options, JsonCollectionInfoValues<ReadOnlyMemory<TElement>> collectionInfo);
}
```

**Comment by bartonjs** [comment]
Looks good as proposed

```C#
namespace System.Text.Json.Serialization.Metadata;

public partial class JsonMetadataServices
{
    // Similar to byte[] serializes as Base64 strings
    public static JsonConverter<Memory<byte>> MemoryByteConverter { get; }
    public static JsonConverter<ReadOnlyMemory<byte>> ReadOnlyMemoryByteConverter { get; }

    // Other element types serialize as JSON arrays
    public static JsonTypeInfo<Memory<TElement>> CreateMemoryInfo<TElement>(JsonSerializerOptions options, JsonCollectionInfoValues<Memory<TElement>> collectionInfo);
    public static JsonTypeInfo<ReadOnlyMemory<TElement>> CreateReadOnlyMemoryInfo<TElement>(JsonSerializerOptions options, JsonCollectionInfoValues<ReadOnlyMemory<TElement>> collectionInfo);
}
```
