### ISSUE TITLE
[API Proposal]: Add async version of ThreadStart and ParameterizedThreadStart callback

### ISSUE THREAD

**Issue by wsy** [dotnet/runtime#86454]
### Background and motivation

Nowadays, many library offers only async APIs.  (e.g. `HttpClient` class only offers `GetAsync` API)
If I want to start a new thread, and I want to use HttpClient in that thread, I have to use async APIs in a non-async context.
Either I add `Wait()` calls after each async API invoke, or I write another async callback and call it from Thread's non-async callback with one single `Wait()` call.

Example1: I have to add `Wait()` calls after each async API invoke
```csharp
void ThreadCallback()
{
    CallSomeAsyncMethods().Wait();
    CallSomeAsyncMethods().Wait();
    CallSomeAsyncMethods().Wait();
}
```

Example2: I must wrap another layer of my callback
```csharp
void ThreadCallback()
{
    MyThreadCallback().Wait();
}
async Task MyThreadCallback()
{
    await CallSomeAsyncMethods();
    await CallSomeAsyncMethods();
    await CallSomeAsyncMethods();
}
```

### API Proposal

```csharp
namespace System.Threading;

// Introduct two new callback types
public delegate Task ThreadStartAsync();
public delegate Task ParameterizedThreadStartAsync(object? obj);

public sealed partial class Thread : CriticalFinalizerObject
{
    // Introduce four new constructors
    public Thread(ThreadStartAsync start) { /*Other code omitted*/ }
    public Thread(ThreadStartAsync start, int maxStackSize)
    public Thread(ParameterizedThreadStartAsync start) { /*Other code omitted*/ }
    public Thread(ParameterizedThreadStartAsync start, int maxStackSize)

    private sealed class StartHelper
    {
        // Alter RunWorker method to handle async callbacks
        private void RunWorker()
        {
            // Other code omitted

            if (start is ThreadStartAsync threadStartAsync)
            {
                threadStartAsync().Wait();
            }
            else if (start is ThreadStart threadStart)
            {
                threadStart();
            }
            else if (start is ParameterizedThreadStartAsync parameterizedThreadStartAsync)
            {
                object? startArg = _startArg;
                _startArg = null;
                parameterizedThreadStartAsync(startArg).Wait();
            }
            else
            {
                ParameterizedThreadStart parameterizedThreadStart = (ParameterizedThreadStart)start;

                object? startArg = _startArg;
                _startArg = null;

                parameterizedThreadStart(startArg);
            }

            // Other code omitted
        }

        // Other code omitted
    }

    // Other code omitted
}
```

### API Usage

```csharp
public class MyDemoClass
{
    private const string HeartbeatUrl = "https://example.com";
    static async Task SendHeartbeatSignal(object? state)
    {
        CancellationToken cancellationToken = CancellationToken.None;
        if (state != null && state is CancellationToken _cancellationToken)
        {
            cancellationToken = _cancellationToken;
        }
        HttpClient httpClient = new();
        while (!cancellationToken.IsCancellationRequested)
        {
            await httpClient.GetAsync(HeartbeatUrl, cancellationToken);
        }
    }

    private Thread heartbeatThread = new(SendHeartbeatSignal);
    private CancellationTokenSource cancellationTokenSource = new();
    public void Initialize()
    {
        heartbeatThread.Start(cancellationTokenSource.Token);
        // Other code omitted
    }

    // Other code omitted
}
```

**Comment by stephentoub** [comment]
To make sure I understand the proposal, the whole thing is to be able to write:
```C#
private Thread heartbeatThread = new(SendHeartbeatSignal);
```
instead of:
```C#
private Thread heartbeatThread = new(() => SendHeartbeatSignal().Wait());
```
?

**Comment by wsy** [comment]
Yes. I think this is similar to 

```csharp
static void Main(string[] args)
```
and
```caharp
static async Task Main(string[] args)
```

Without the async version of entry point, developers would have to write this:
```csharp
static void Main(string[] args) => MyMain(args).Wait();
static async Task MyMain(string[] args) {}
```

**Comment by stephentoub** [comment]
Thanks. I don't think this is something we'd want to do.  First, we try hard not to introduce APIs that are sync-over-async, where the only thing the API serves to do is invoke something asynchronous and then block waiting on it.  In the case of `async Main` you point out, that thread effectively needs to be blocked anyway to prevent the app from going away, and it's also a super common case.   Second, I think the API itself is misleading, as it seems to suggest that the async method is going to be run on that thread, but in reality the only part that'll be run on that thread is the synchronous part up until the first await that yields; after that, the thread will just be sitting there blocked waiting for other threads to finish the processing of the method.

**Comment by huoyaoyuan** [comment]
> Second, I think the API itself is misleading, as it seems to suggest that the async method is going to be run on that thread, but in reality the only part that'll be run on that thread is the synchronous part up until the first await that yields; after that, the thread will just be sitting there blocked waiting for other threads to finish the processing of the method.

It's also worthy to note that, before creating threads, why not using `Task.Run`? It has been a wide mistake to not leverage the thread pool.

**Comment by wsy** [comment]
> we try hard not to introduce APIs that are sync-over-async
OK. I now understand. My proposal is indeed the case of 'sync-over-async'. We should avoid this. And we should close this proposal.

Thanks for your explaination.

> in reality the only part that'll be run on that thread is the synchronous part up until the first await that yields
By the way, this is new knowledge to me. Thanks.

**Comment by wsy** [comment]
> before creating threads, why not using `Task.Run`?
@huoyaoyuan Of course it's always preferable to utilize ThreadPool for short term tasks. However, we do sometimes have the need to create a Thread for some dedicated long-running task. And that task sometimes will have to call some async APIs.
