### ISSUE TITLE
[wasm] Upgrade VMs to Ubuntu 22.04

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#86480]
https://github.com/dotnet/runtime/pull/86194 upgrades all the non-wasm VMs to Ubuntu 22.04 .

What is needed on wasm side to do the same?

https://github.com/dotnet/runtime/blob/29d485c14f1ce5a7358cbed3dd97df725a5bec6d/eng/pipelines/libraries/helix-queues-setup.yml#L182-L192

## dotnet-runtime-perf pipeline
- [x] Update perf pipeline too (thanks to @cincuranet)
- [ ] Update node, and jsvu in all these places (*WIP*)

## runtime pipeline
- [ ] Helix: main wasm queue is still on 18.04
- [ ] Helix: queue used for firefox debugger tests is still on 18.04
- [ ] What is needed for upgrading the build machines we use?
- [ ] Update node, and jsvu in all these places

cc @radekdoulik @maraf

**Comment by lewing** [comment]
what is the status of this one?

**Comment by radical** [comment]
> what is the status of this one?

The perf pipeline machines have been moved to 22.04, and the issues hit with that are being fixed now.
For `runtime`, the work is pending.
