### ISSUE TITLE
[AOT] LINK : fatal error LNK1123: Failed during conversion to COFF: Invalid or corrupted file

### ISSUE THREAD

**Issue by qssq1** [dotnet/runtime#86493]
![image](https://github.com/dotnet/runtimelab/assets/14260426/f5911d84-0f54-4384-a793-a30cc2bc2caa)

I TRY uninstall 7.0.5 but 7.0.302 for visual studio cannot to uninstall or replase  7.0.202 for visual studio

C:\Program Files\dotnet\sdk\7.0.302\Sdks\Microsoft.DotNet.ILCompiler\build\Microsoft.NETCore.Native.targets(350,5): err
or MSB3073: 命令“"D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64\link.
exe" @"obj\YTLSX_R\net7.0\win-x64\native\link.rsp"”已退出，代码为 1123。 [D:\dev\company_project\WEB_webapi\webapi_mes\webap
i_mes.csproj]

![image](https://github.com/dotnet/runtimelab/assets/14260426/42b14282-2619-48a6-9cc5-b571c1842b88)
Because there was a problem with the code running after AOT was compiled, I deleted many .net 7.0  version folders on the computer and uninstalled it, resulting in this problem that cannot be fixed regardless of whether it is reinstalled or not.

**Comment by jkotas** [comment]
> error LNK1123: Failed during conversion to COFF: Invalid or corrupted file

Try deleting your obj and bin directories, and doing a clean build. It is what we have helped to resolve this error in https://github.com/dotnet/runtimelab/issues/1436#issuecomment-903947363

A better solution is tracked by https://github.com/dotnet/runtime/issues/79634 .

> I deleted many .net 7.0 version folders on the computer and uninstalled it

Manually deleting the .NET 7.0 version folders under `C:\Program Files\dotnet` corrupts the installation. Repairing the installation using Visual Studio Setup may help in this case.
