### ISSUE TITLE
InternalGetCustomAttributes, dictionary is not needed

### ISSUE THREAD

**Issue by ninedan** [dotnet/runtime#86507]
### Description

In Attribute.InternalGetCustomAttributes implementation, a dictionary is allocated with 11 elements as default capacity, populated, but it seems the dictionary is never used.

The dictionary types is allocated, passed to CopyToAttributeList twice:

![image](https://github.com/dotnet/runtime/assets/19536938/d0caf0fb-7021-49ec-938b-220d3a4486eb)

Inside CopyToAttributeList, it puts first attribute of a type into the dictionary:
![image](https://github.com/dotnet/runtime/assets/19536938/b6e31015-1fa7-48ef-992c-c8569ef9baf4)

But the dictionary is never used otherwise. So it's safe to totally removed it.

**Comment by stephentoub** [comment]
> But the dictionary is never used otherwise. So it's safe to totally removed it.

It's passed to AddAttributesToList as well:
https://github.com/dotnet/runtime/blob/89678442a8625fd53501ec6b9fd60f7d47dc9ae9/src/coreclr/System.Private.CoreLib/src/System/Attribute.CoreCLR.cs#L43
where it's both queried and updated:
https://github.com/dotnet/runtime/blob/89678442a8625fd53501ec6b9fd60f7d47dc9ae9/src/coreclr/System.Private.CoreLib/src/System/Attribute.CoreCLR.cs#L403-L414

Have I misunderstood?  If there's actually an unused dictionary here, we'd certainly want to delete it, but I'm not seeing it.

**Comment by ninedan** [comment]
You're right, my bad.

**Comment by stephentoub** [comment]
Thanks, anyway.

**Comment by ninedan** [comment]
The dictionary has too much capacity. In most cases, there should be only a single type, so it should be possible to remove the dictionary.
