### ISSUE TITLE
CI failure in JitBlue/GitHub_85129/GitHub_85129.cs: CS0260: -Missing partial modifier on declaration of type 'Program'; another partial declaration of this type exists

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#86514]
### Error Blob

```json
{
  "ErrorMessage": "",
  "BuildRetry": false,
  "ErrorPattern": "GitHub_85129\.cs\(\d+,\d+\)\: error CS0260\: Missing partial modifier on declaration of type \'Program\'; another partial declaration of this type exists",
  "ExcludeConsoleLog": true
}
```

### Reproduction Steps

- PR: https://github.com/dotnet/runtime/pull/86453
- Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=279134&view=results
- Job: https://dev.azure.com/dnceng-public/public/_build/results?buildId=279134&view=logs&j=190ad6c8-5950-568c-cadd-f2dfb7d5a79f&t=bede7c9a-a35a-5c60-69ce-a4ea87514b0b
- Job name: `Build Browser wasm Linux Release AllSubsets_Mono_RuntimeTests` 
- Step name: `Build Tests`
- Error message:
```
##[error]src/tests/JIT/Regression/JitBlue/GitHub_85129/GitHub_85129.cs(11,14): error CS0260: Missing partial modifier on declaration of type 'Program'; another partial declaration of this type exists [/__w/1/s/src/tests/JIT/Regression/JitBlue/GitHub_85129/GitHub_85129.csproj]
```

### Known Issue Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "BuildRetry": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by tannergooding** [comment]
This was just a bug in the PR: https://github.com/dotnet/runtime/pull/86453

Test infrastructure changed a bit between .NET 7 and .NET 8, so I had to tweak some things.
