### ISSUE TITLE
System.Text.Json Desrialization to an IParsable<T>

### ISSUE THREAD

**Issue by SDP190** [dotnet/runtime#86529]
Can we make Json deserialization to make use of `IParsable` types, so for example if a Json property has a string value, but the converting-to type is not a string but is a complex type which implements `IParsable<T>`, then the de-serialization process should automatically call `IParsable.Parse()` to try and create an instance of that type.

We may want to restrict it to only allow parsing of value types (structs) ?

Or we may want to have a special attribute on top of IParsable type properties to define whether deserialization can use IParsable.Parse for that specific property or not, something like:
`[JsonAllowIParsableDeserialization]` 
if the attribute is applied we can adhere to it, if not we may have a default decision whether yes or not to use `IParsable<T>.Parse`  (which itself might in turn depend if its a value type or object).
 
Besides above mentioned attribute, we may want to have an general option in the `SerializationOptions` passed to the Deserialize method.

Is this already the behavior of Json deserialization now?, as far as I have searched its not documented anywhere.

**Comment by eiriktsarpalis** [comment]
Related to https://github.com/dotnet/runtime/issues/84305. Given the nature of STJ supporting the UTF-8 variants of the parser/formatter interfaces probably makes more sense.
