### ISSUE TITLE
[API Proposal]: `GC.IgnoreTransitionSuppression(void*)`

### ISSUE THREAD

**Issue by DaZombieKiller** [dotnet/runtime#86525]
### Background and motivation

Today, if a `DllImport` or function pointer invocation makes use of `SuppressGCTransition`, very bad things can happen if the function has been detoured and no longer satisfies the requirements of `SuppressGCTransition`.

While function detouring is an unsafe and largely unsupported scenario, I feel that it would be worthwhile to offer an API to disable the effects of `SuppressGCTransition` for a given code address.

Essentially, `GC.IgnoreTransitionSuppression` would be given the address of a function, and the runtime would ignore `SuppressGCTransition` for any `DllImport`s or function pointer invocations using that address.

### API Proposal

```csharp
namespace System;

public static partial class GC
{
    public static unsafe void IgnoreTransitionSuppression(void* address);
}
```

### API Usage

```csharp
var module  = GetModuleHandle("KERNEL32.DLL");
var pointer = NativeLibrary.GetExport(module, "SomeAPIThatHasADllImportMarkedWithSuppressGCTransition");
GC.IgnoreTransitionSuppression((void*)pointer);
// Unmanaged hooks can now be installed on that address without fear of transition issues
```

### Alternative Designs

A runtime configuration option to globally disable `SuppressGCTransition` could be offered.

**Comment by EgorBo** [comment]
I'm not sure I fully understand, when a pinvoke has `SuppressGCTransition` we build the codegen accordingly by just invoking the direct target (with a gc safepoint) - how do we safely/immidiately revert that?
I think if there is a chance a function with `SuppressGCTransition` may mis-behave, the attribute should not be used at all

**Comment by AaronRobinsonMSFT** [comment]
@DaZombieKiller I agree with @EgorBo. Also, I can't think of any existing mechanism that can be used to disable a properly applied attribute or feature in the runtime. I would also assume that any detouring of a function that has the `SuppressGCTransition` likely violates the requirements of [`SuppressGCTransition`](https://learn.microsoft.com/dotnet/api/system.runtime.interopservices.suppressgctransitionattribute#remarks).

It might be helpful to explain how you got here and the scenario where this caused a problem.

**Comment by DaZombieKiller** [comment]
> I'm not sure I fully understand, when a pinvoke has `SuppressGCTransition` we build the codegen accordingly by just invoking the direct target (with a gc safepoint) - how do we safely/immidiately revert that?

The method would likely need to be dirtied in some way to force it to be re-jitted, including anything that the invoke was inlined into. Probably a non-trivial amount of work.

> It might be helpful to explain how you got here and the scenario where this caused a problem.

In my own scenario, I'm not currently detouring any APIs that are marked with `SuppressGCTransition`. I have however seen issues arise before from users doing this (https://github.com/dotnet/runtime/issues/79971) and opened this issue with the intention of determining if there may be a way to handle the situation if I'm unfortunate enough to find myself in it later.

There was a lengthy discussion on this in the C# Discord server with myself, @SingleAccretion, @tannergooding and @Sewer56. The conclusion that was ultimately reached was that an API like this is unlikely to make it into the runtime due to the inherently unsupported nature of combining detours with managed code in the same application, and the various edge cases that this API would still not solve even if it were added.

For example: if you have detoured a method that is invoked with `SuppressGCTransition`, that method will not necessarily be the one that is directly invoked from managed code. It could be indirectly invoked by another method that is also marked with `SuppressGCTransition`, placing you in the same situation as if you hadn't used this API at all.

As a result, I'm no longer convinced that this API would solve the problem to a degree that makes it worth adding to the runtime, and the fact that it would most likely be a non-trivial implementation for an extremely niche use case only makes it even less likely to happen.
