### ISSUE TITLE
[main] Installer HostActivation/HostModel.ComHost Tests failing in coreclr x86/x64 windows/osx

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#86520]
### Error Blob

Important: There is a couple of similar issues open for [6.0](https://github.com/dotnet/runtime/issues/81851) and for [7.0](https://github.com/dotnet/runtime/issues/86518), but please confirm they have the same root cause before marking this one as duplicate of the other ones.

```json
{
  "ErrorMessage": "",
  "BuildRetry": false,
  "ErrorPattern": "Microsoft\\.NET\\.HostModel\\.ComHost\\.Tests_net8\\.0_x(86|64)\\.html",
  "ExcludeConsoleLog": true
}
```

### Reproduction Steps

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=275370&view=results

## x64 windows
- Job link: https://dev.azure.com/dnceng-public/public/_build/results?buildId=275370&view=logs&j=c08f4d29-06c1-5e3b-b94b-1702412980f1&t=f529fb3d-1463-5ee2-5dfd-063237ddec28
- Job name: `Installer Build and Test coreclr windows_x64 Release`
- Step name: `Build`
- Output:
```
VSTest : error : Tests failed:
D:\a\_work\1\s\artifacts\TestResults\Release\HostActivation.Tests_net8.0_x64.html [net8.0|x64] [D:\a\_work\1\s\src\installer\tests\HostActivation.Tests\HostActivation.Tests.csproj]

VSTest : error : Tests failed:
D:\a\_work\1\s\artifacts\TestResults\Release\Microsoft.NET.HostModel.ComHost.Tests_net8.0_x64.html [net8.0|x64] [D:\a\_work\1\s\src\installer\tests\Microsoft.NET.HostModel.Tests\Microsoft.NET.HostModel.ComHost.Tests\Microsoft.NET.HostModel.ComHost.Tests.csproj]
```

## x86 windows
- Job link: https://dev.azure.com/dnceng-public/public/_build/results?buildId=275370&view=logs&j=956d6d25-bf2f-5b4e-edc4-1a96f4d34516&t=d78281ea-2e35-55df-d4b3-210f2370f831
- Job name: `Installer Build and Test coreclr windows_x86 Debug`
- Step name: `Build`
- Output:
```
VSTest : error : Tests failed:
D:\a\_work\1\s\artifacts\TestResults\Debug\HostActivation.Tests_net8.0_x86.html [net8.0|x86] [D:\a\_work\1\s\src\installer\tests\HostActivation.Tests\HostActivation.Tests.csproj]

VSTest : error : Tests failed:
D:\a\_work\1\s\artifacts\TestResults\Debug\Microsoft.NET.HostModel.ComHost.Tests_net8.0_x86.html [net8.0|x86] [D:\a\_work\1\s\src\installer\tests\Microsoft.NET.HostModel.Tests\Microsoft.NET.HostModel.ComHost.Tests\Microsoft.NET.HostModel.ComHost.Tests.csproj]
```

## x64 osx:

- Job: https://dev.azure.com/dnceng-public/public/_build/results?buildId=275370&view=logs&j=4e067266-f659-5f19-62f1-c3e5aa254bc7&t=05407611-1902-5f81-107b-208c27ccf706
- Job name: `Installer Build and Test coreclr osx_x64 Release`
- Step name: `Build and Package`
- Output:
```
VSTest : error : Tests failed:
/Users/runner/work/1/s/artifacts/TestResults/Release/HostActivation.Tests_net8.0_x64.html [net8.0|x64] [/Users/runner/work/1/s/src/installer/tests/HostActivation.Tests/HostActivation.Tests.csproj]

VSTest : error : Tests failed:
/Users/runner/work/1/s/artifacts/TestResults/Release/Microsoft.NET.HostModel.ComHost.Tests_net8.0_x64.html [net8.0|x64] [/Users/runner/work/1/s/src/installer/tests/Microsoft.NET.HostModel.Tests/Microsoft.NET.HostModel.ComHost.Tests/Microsoft.NET.HostModel.ComHost.Tests.csproj]
```

### Known Issue Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "BuildRetry": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by vitek-karas** [comment]
The failure is: `System.TypeLoadException : Could not load type 'System.Buffers.SearchValues`1' from assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.`

So again the problem with a mismatch between the live build and the SDK.

The same problem is hit in https://github.com/dotnet/runtime/pull/85913. 

@elinor-fung  solved that one, so she probably knows what to do here as well.

**Comment by elinor-fung** [comment]
@carlossanlop are you seeing this in the actual main branch? The linked failures are from https://github.com/dotnet/runtime/pull/85913 PR build itself before I updated the branch to resolve them.

**Comment by carlossanlop** [comment]
I saw these issues in an internal build. I didn't check if these were showing up in public, I assumed they were. But I'm confident these are happening in main since the error text mentions "8.0".

**Comment by elinor-fung** [comment]
@carlossanlop could you point me at any other builds you saw with the `TypeLoadException` failure in host tests? I haven't managed to find other occurrences.

**Comment by elinor-fung** [comment]
We don't seem to more hits of the same error here and no specific builds to investigate, so I'm gong to close this one.
