### ISSUE TITLE
Microsoft.Extensions.Configuration.Binder.Tests.ConfigurationBinderTests.BindCanReadStaticProperty failing intermittently

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#86532]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=280353
Build error leg or test failing: Microsoft.Extensions.Configuration.Binder.Tests.ConfigurationBinderTests.BindCanReadStaticProperty
Pull request: https://github.com/dotnet/runtime/pull/86519

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Expected: other stuff",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": true
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[436679](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436679)|dotnet/runtime|[Microsoft.Extensions.Configuration.Binder.Tests.ConfigurationBinderTests.BindCanReadStaticProperty](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436679&view=ms.vss-test-web.build-test-results-tab&runId=9707206&resultId=103476)||
|[431376](https://dev.azure.com/dnceng-public/public/_build/results?buildId=431376)|dotnet/runtime|[Microsoft.Extensions.Configuration.Binder.Tests.ConfigurationBinderTests.BindCanReadStaticProperty](https://dev.azure.com/dnceng-public/public/_build/results?buildId=431376&view=ms.vss-test-web.build-test-results-tab&runId=9539474&resultId=113305)||
|[430806](https://dev.azure.com/dnceng-public/public/_build/results?buildId=430806)|dotnet/runtime|[Microsoft.Extensions.Configuration.Binder.Tests.ConfigurationBinderTests.BindCanReadStaticProperty](https://dev.azure.com/dnceng-public/public/_build/results?buildId=430806&view=ms.vss-test-web.build-test-results-tab&runId=9525290&resultId=104530)|dotnet/runtime#93066|
|[429943](https://dev.azure.com/dnceng-public/public/_build/results?buildId=429943)|dotnet/runtime|[Microsoft.Extensions.Configuration.Binder.Tests.ConfigurationBinderTests.BindCanReadStaticProperty](https://dev.azure.com/dnceng-public/public/_build/results?buildId=429943&view=ms.vss-test-web.build-test-results-tab&runId=9503114&resultId=100624)|dotnet/runtime#92057|
|[425385](https://dev.azure.com/dnceng-public/public/_build/results?buildId=425385)|dotnet/runtime|[Microsoft.Extensions.Configuration.Binder.Tests.ConfigurationBinderTests.BindCanReadStaticProperty](https://dev.azure.com/dnceng-public/public/_build/results?buildId=425385&view=ms.vss-test-web.build-test-results-tab&runId=9360832&resultId=102709)||
|[418980](https://dev.azure.com/dnceng-public/public/_build/results?buildId=418980)|dotnet/runtime|[Microsoft.Extensions.Configuration.Binder.Tests.ConfigurationBinderTests.BindCanReadStaticProperty](https://dev.azure.com/dnceng-public/public/_build/results?buildId=418980&view=ms.vss-test-web.build-test-results-tab&runId=9192752&resultId=100603)||
|[417649](https://dev.azure.com/dnceng-public/public/_build/results?buildId=417649)|dotnet/runtime|[Microsoft.Extensions.Configuration.Binder.Tests.ConfigurationBinderTests.BindCanReadStaticProperty](https://dev.azure.com/dnceng-public/public/_build/results?buildId=417649&view=ms.vss-test-web.build-test-results-tab&runId=9151172&resultId=114738)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|7|

 ### Known issue validation
**Build: :mag_right:** 
**Result validation: :warning:** Validation could not be done without an Azure DevOps build URL on the issue. Please add it to the "**Build: :mag_right:**" line.
**Validation performed at:** 6/28/2023 10:04:11 PM UTC

**Comment by tarekgh** [comment]
The failing test is https://github.com/dotnet/runtime/blob/1ec5ff876baf614275dcdc1d6ba435e94d78e4b1/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/Common/ConfigurationBinderTests.cs#L692.

The failure is https://dev.azure.com/dnceng-public/public/_build/results?buildId=280353&view=ms.vss-test-web.build-test-results-tab&runId=5559962&resultId=100636&paneView=debug

```
Assert.Equal() Failure
↓ (pos 0)
Expected: other stuff
Actual:   stuff
↑ (pos 0)


 at Microsoft.Extensions.Configuration.Binder.Tests.ConfigurationBinderTests.BindCanReadStaticProperty() in /_/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/Common/ConfigurationBinderTests.cs:line 705
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
```

This is a very weird issue as it looks like the string somehow gets trimmed from the beginning. No idea how this can happen.

**Comment by steveharter** [comment]
This is likely due to `ComplexOptions.StaticProperty` being a static property and shared with other tests that could be running at the same time, including another test that sets it to "stuff".

**Comment by jkotas** [comment]
This was just hit in #93766 that included the attempted fix.

Log https://helix.dot.net/api/2019-06-17/jobs/2a5ba216-8f70-4231-a125-ae077ebca6fa/workitems/Microsoft.Extensions.Configuration.Binder.Tests/console
