### ISSUE TITLE
Can't build runtime on Ubuntu 20.04 (LTS) due to native PGO format

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#86531]
I followed the [official steps](https://github.com/dotnet/runtime/blob/main/docs/workflow/requirements/linux-requirements.md) to configure my Ubuntu 20.04 and when I try to build the runtime it fails with
```
  error: Could not read profile /home/egorbo/.nuget/packages/optimization.linux-x64.pgo.coreclr/1.0.0-
prerelease.23260.3/data/coreclr.profdata: Unsupported instrumentation profile format version
  1 error generated.
```
(and builds fine with `/p:NoPgoOptimize=true`)

Is it expected? My `clang --version` is `10.0.0-4ubuntu` did we bump minimal requirement to 16?

@sbomer (cc @directhex who might be familiar with it too)
Also, cc @sebastienros in case if he hit a similar build issue for TE. The problem that we noticed a serios regression in TE instrumented-tiers benchmark which might be affected by Native PGO (or lack of it) 

PS: I use `ubuntu 20.04` because it uses the correct libc for TE benchmarks, I believe I can't update to 22

cc @AndyAyersMS

**Comment by EgorBo** [comment]
We believe that broken native PGO is responsible for these huge regression in TE:

![image](https://github.com/dotnet/runtime/assets/523221/1258db12-6bb0-4ec5-8536-f1fd1a93ff66)

**Comment by sebastienros** [comment]
@kunalspathak probably what I mentioned earlier for Ampere machines.

**Comment by EgorBo** [comment]
Thanks! Yes, let's close it, thanks for the clarification.
