### ISSUE TITLE
Set Browsable property value at runtime by reflection

### ISSUE THREAD

**Issue by GMCadiom** [dotnet/runtime#86544]
[Based on Mr @teo-tsirpanis 's suggestion I have opened this issue](https://github.com/dotnet/runtime/pull/86542#issuecomment-1556004485)

I have an issue with changing BrowsableAttribute.Browsable value at runtime

in **framework 4.8** was using this code and was working stable

```
PropertyDescriptor descriptor = TypeDescriptor.GetProperties(modelName)[propertyName];
BrowsableAttribute attribute = (BrowsableAttribute)descriptor.Attributes[typeof(BrowsableAttribute)];
FieldInfo fieldToChange = attribute.GetType().GetField("browsable", BindingFlags.NonPublic | BindingFlags.Instance);
fieldToChange?.SetValue(attribute, value);
```

and now in **.net core 6** using this code

```
PropertyDescriptor descriptor = TypeDescriptor.GetProperties(modelName)[propertyName];
BrowsableAttribute attribute = (BrowsableAttribute)descriptor.Attributes[typeof(BrowsableAttribute)];
PropertyInfo propertyToChange = attribute.GetType().GetProperty("Browsable");
propertyToChange?.SetValue(attribute, value);

```
It throws this exception
`System.ArgumentException: 'Property set method not found.'`

in **framework 4.8** was their ability to change **Browsable** property value
so I made this [PL#86542](https://github.com/dotnet/runtime/pull/86542)

**Comment by GMCadiom** [comment]
> Tagging subscribers to this area: @dotnet/area-system-componentmodel See info in [area-owners.md](https://github.com/dotnet/runtime/blob/main/docs/area-owners.md) if you want to be subscribed.
> 
> Issue Details

@dotnet/area-system-componentmodel

**Comment by jkotas** [comment]
[.NET Framework design guidelines](https://www.amazon.com/Framework-Design-Guidelines-Conventions-Addison-Wesley/dp/0135896460) says:

DO provide get-only properties for required arguments.
DO provide settable properties for optional arguments.

Browsable is require argument. It should not have settable property according to the design guidelines.

**Comment by stephentoub** [comment]
> in framework 4.8 was using this code and was working stable

Note as well, even if it happened to work, private reflection to set a private field of the core libraries is not supported.

**Comment by GMCadiom** [comment]
@jkotas 
@stephentoub 
Thanks for contributing

So is there any work around to change the value of Browsable property at runtime

Or even add the BrowsableAttribute to specific property on class with (true, false) value based on condition same at runtime

**Comment by jkotas** [comment]
What are you trying to achieve by changing the value of Browsable property at runtime? Can you allocate a new `BrowsableAttribute` instance that has the `Browsable` property set correctly instead?

If you would like to replicate what you have done on .NET Framework, you can find the current name of the field that backs the Browsable property and set that using the private reflection. Repeating again, private reflection on the core libraries is not supported. It may happen to work this release and break again next release.

**Comment by GMCadiom** [comment]
> What are you trying to achieve by changing the value of Browsable property at runtime? Can you allocate a new `BrowsableAttribute` instance that has the `Browsable` property set correctly instead?
> 
> If you would like to replicate what you have done on .NET Framework, you can find the current name of the field that backs the Browsable property and set that using the private reflection. Repeating again, private reflection on the core libraries is not supported. It may happen to work this release and break again next release.

What I'm trying to achieve is that there is a list filled to BindingSource.Database which I want to show some columns based on a boolean condition.

I was just using my code :
```
PropertyDescriptor descriptor = TypeDescriptor.GetProperties(modelName)[propertyName];
BrowsableAttribute attribute = (BrowsableAttribute)descriptor.Attributes[typeof(BrowsableAttribute)];
FieldInfo fieldToChange = attribute.GetType().GetField("browsable", BindingFlags.NonPublic | BindingFlags.Instance);
fieldToChange?.SetValue(attribute, value);
```
and set the `value` as the condition result.
