### ISSUE TITLE
ConfigurationBindingGenerator Fails with ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by chrisoverzero** [dotnet/runtime#86557]
### Description

When configuration binding generation is enabled by means of `<EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>`, no source code is generated. Instead, the generator throws an `ArgumentOutOfRangeException` and fails with this message:

```
CSC : warning CS8785: Generator 'ConfigurationBindingGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of 
type 'ArgumentOutOfRangeException' with message 'repeatCount ('-4') must be a non-negative value. (Parameter 'repeatCount') [/app/repro/repro.csproj]
```

### Reproduction Steps

Given the following project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.0-preview.4.23259.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0-preview.4.23259.5" />
  </ItemGroup>

</Project>
```

…and the following Program.cs:

```c#
using Microsoft.Extensions.Configuration;

var c = new ConfigurationBuilder().Build();
var x = c.GetSection("Anything").Get<TimeSpan?>();
Console.WriteLine(x.GetValueOrDefault());
```

…run `dotnet build` via public 8.0 Preview 4 or daily 8.0 Preview 5.

This repro was generated from the `dotnet new console` command. The method `Bind` can be substituted with the same result. 8.0 Preview 5 versions of "Microsoft.Extensions.Configuration.Binder" and "Microsoft.Extensions.Hosting" can be substituted with the same result.

(Interestingly, source generation isn't even _attempted_ unless "Microsoft.Extensions.Hosting" is present. This was also the case in 8.0 Preview 3. Is that meant to be so? I couldn't find it documented. If not, I can file another issue.)

### Expected behavior

A file is generated which contains configuration binding code.

### Actual behavior

Compilation fails with the following error:

```
CSC : warning CS8785: Generator 'ConfigurationBindingGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of 
type 'ArgumentOutOfRangeException' with message 'repeatCount ('-4') must be a non-negative value. (Parameter 'repeatCount') [/app/repro/repro.csproj]
```

### Regression?

This was not present in 8.0 Preview 3.

### Configuration

.NET Version: This has been tried with "8.0.100-preview.4.23260.5" and "8.0.100-preview.5.23269.37" versions of the SDK.

OS and version: macOS 13.3.1 (a) and Ubuntu 18.04.6 LTS. The latter via `mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-cross-arm64-20220427171722-6e40d49`. (~Though I see that the cross-compilation instructions have changed since I last checked. I'll make sure to try to recreate with `mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-2.0-cross-arm64`.~ _Same on "CBL-Mariner 2.0.20230426"._)

Architecture: x64. I don't believe it is specific to that configuration.

Blazor: :x:

### Other information

I think this has something to do with indentation determination. The only `repeatCount` it seems that it could plausibly be is the one in `StringBuilder`'s `AppendChar`.

**Comment by tarekgh** [comment]
@chrisoverzero could you please try referencing the following package and let's know if this makes any difference? 

```
dotnet add package Microsoft.Net.Compilers.Toolset --version 4.7.0-1.final
```

**Comment by chrisoverzero** [comment]
> could you please try referencing the following package […]

Sure thing:

```diff
     <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0-preview.4.23259.5" />
+    <PackageReference Include="Microsoft.Net.Compilers.Toolset" Version="4.7.0-1.final" />
   </ItemGroup>
```

But no difference.

```
root [ /app/repro ]# ~/.dotnet/dotnet build
MSBuild version 17.7.0-preview-23267-02+fe79798bd for .NET
  Determining projects to restore...
  Restored /app/repro/repro.csproj (in 238 ms).
/root/.dotnet/sdk/8.0.100-preview.5.23269.37/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(314,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/app/repro/repro.csproj]
CSC : warning CS8785: Generator 'ConfigurationBindingSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentOutOfRangeException' with message 'repeatCount ('-4') must be a non-negative value. (Parameter 'repeatCount') [/app/repro/repro.csproj]
  repro -> /app/repro/bin/Release/net8.0/repro.dll

Build succeeded.

CSC : warning CS8785: Generator 'ConfigurationBindingSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentOutOfRangeException' with message 'repeatCount ('-4') must be a non-negative value. (Parameter 'repeatCount') [/app/repro/repro.csproj]
    1 Warning(s)
    0 Error(s)
```

**Comment by tarekgh** [comment]
Thanks @chrisoverzero.

@layomia could you please have a look?

**Comment by layomia** [comment]
This has been fixed. Please report any further issues with this.

**Comment by chrisoverzero** [comment]
I _eagerly_ await the daily build. Thanks so much.

**Comment by chrisoverzero** [comment]
@layomia Is this meant to be available in Preview 6? I am getting the same error on the same reproduction.

**Comment by layomia** [comment]
@chrisoverzero can you pls try the latest build of the generator? https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet8/NuGet/Microsoft.Extensions.Configuration.Binder/versions

**Comment by chrisoverzero** [comment]
With these dependencies:

```xml
<PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0-rc.1.23370.5" />
<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.0-rc.1.23374.2" />
```

…and compiler version `8.0.100-preview.6.23330.14`, I get this error:

```
CSC : warning CS8785: Generator 'ConfigurationBindingGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidCastException' with message 'Unable to cast object of type 'Microsoft.Extensions.Configuration.Binder.SourceGeneration.NullableSpec' to type 'Microsoft.Extensions.Configuration.Binder.SourceGeneration.ObjectSpec'.' [/Users/cosborn/Developer/repro/repro.csproj]
```

**Comment by tarekgh** [comment]
@layomia I am reopening the issue as it looks, we still have some issue with this scenario.
