### ISSUE TITLE
JIT\Methodical\eh\finallyexec\nestedfinallycall_d failing with optimizations on

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#86561]
NativeAOT controls optimizations at the entrypoint assembly level so after test merging, we started running some tests with optimizations that on CoreCLR we never execute with optimizations.

RyuJIT seems to be to be stripping a bunch of finally blocks in nestedfinallycall_d.

The test is getting checked in as disabled in NativeAOT in #86429

**Comment by AndyAyersMS** [comment]
Can you describe how to repro?

**Comment by MichalStrehovsky** [comment]
I think you can just add Optimize=true to the project file.

**Comment by MichalStrehovsky** [comment]
(or whatever is the ILasm equivalent to put the magic attribute that allows optimizing in RyuJIT)

**Comment by AndyAyersMS** [comment]
There is already a variant of this we run with JIT optimization enabled (nestedfinallycall_r). And the opt flag to ILASM just seems to use short encodings for var nums and branches; the JIT produces the same code and same EH table either way, and both versions run without failing with the coreclr runtime.

So presumably this only fails under NAOT for some yet to be determined reason -- I can probably figure out repro instructions for that, but I'd rather just start from whatever it was you were running when you saw things fail.

**Comment by MichalStrehovsky** [comment]
I definitely had a repro where adding/removing `-O` made the difference between working and not working, but it doesn't repro for me anymore. Let's close this, I didn't want to file an issue in the first place.

**Comment by jkotas** [comment]
If the test is not failing, we should delete the exclusion from issues.targets
