### ISSUE TITLE
Support x86 for NativeAOT

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtime#86573]
I know that x86 is legacy right now, but come across person who what to write anti-cheat for x86 game using NativeAOT.
I know that's fringe case, and I prefer to have better case asking for support me on this journey.

So my question would be following: If I put some efforts into this, would this be a burden for core team?

**Comment by NCLnclNCL** [comment]
> I cannot have enough time for this, so nobody working on the matter right now from what I know. I would suggest you try different route then NativeAOT for x86

i think you can refer to .net native x86 at uwp

**Comment by lowleveldesign** [comment]
> Any suggestions @kant2002 ?

@ThaDaVos , if you're OK with loading .NET runtime libs into the target process, you could try the approach from the [core hosting sample](https://github.com/dotnet/samples/tree/main/core/hosting). I used it in my [windbg extension template](https://github.com/lowleveldesign/windbg-ext-template).

**Comment by ThaDaVos** [comment]
I am currently using a modified version of DNNE (https://github.com/AaronRobinsonMSFT/DNNE) to get it to work, it compiles a Native library which loads the runtime and my library - still sad it's not included in NativeOAT, but it's understandable after the explanations I've found

**Comment by joeamnesiac** [comment]
> I am currently using a modified version of DNNE (https://github.com/AaronRobinsonMSFT/DNNE) to get it to work, it compiles a Native library which loads the runtime and my library - still sad it's not included in NativeOAT, but it's understandable after the explanations I've found

What did you have to change? Is there a **branch** or a **clone** with the changes needed?

**Comment by ThaDaVos** [comment]
@joeamnesiac - you can just use the normal DNNE version if you want a Native x86 library - my modified version contains some extra stuff for working with Clarion (automatic generation of some files)

**Comment by NCLnclNCL** [comment]
> Why do we need x86 for Linux and Windows? I thought Windows won't drop 32 bit support. What is about win-x86?

i think window x64 will support 32 bit over wow64 forever until 128 bit comes out, linux x86 hasn't been supported for a long time

**Comment by filipnavara** [comment]
Initial support has landed with https://github.com/dotnet/runtime/pull/99372. There are still bugs that need to be solved. I expect to setup some test infrastructure in the coming days and file issues for specific failures.

**Comment by filipnavara** [comment]
Current list of known outstanding issues / tasks:
- [ ] https://github.com/dotnet/runtime/issues/99687 (PR: https://github.com/dotnet/runtime/pull/99718)
- [ ] Incorrect recognition of HW intrinsics (PR: https://github.com/dotnet/runtime/pull/99894)
- [ ] Enable tests (PR: https://github.com/dotnet/runtime/pull/99688)
- [ ] Add win-x86 to the list of supported platforms in SDK: https://github.com/dotnet/installer/blob/e22bf5e53db01d3e9b961270b9cbf761fabefcbf/src/redist/targets/GenerateBundledVersions.targets#L377-L381
- [ ] Add win-x86 packages into official builds: https://github.com/dotnet/runtime/blob/8b04e76468af5905f739506e97039170b7554671/eng/pipelines/runtime-official.yml#L322

**Comment by ThaDaVos** [comment]
> Initial support has landed with #99372. There are still bugs that need to be solved. I expect to setup some test infrastructure in the coming days and file issues for specific failures.

I guess that's in Dotnet 9? Or hasn't it be published yet? Would love to help by trying it out

**Comment by MichalStrehovsky** [comment]
A public preview with the support hasn't shipped yet, but if you get the latest installer bits from https://github.com/dotnet/installer?tab=readme-ov-file#installers-and-binaries, you can try it out. In the linked page, make sure to choose "Zip" or "Installer" from the column marked "main (9.0.x Runtime)". Make sure to read the instructions about nuget.config. Without that, you'll get restore errors.

**Comment by nahakyuu** [comment]
> A public preview with the support hasn't shipped yet, but if you get the latest installer bits from https://github.com/dotnet/installer?tab=readme-ov-file#installers-and-binaries, you can try it out. In the linked page, make sure to choose "Zip" or "Installer" from the column marked "main (9.0.x Runtime)". Make sure to read the instructions about nuget.config. Without that, you'll get restore errors.


I followed the above and still got the NETSDK1203 error
```
> dotnet --version
9.0.100-preview.5.24230.22
```
```
NativeLibrary.csproj
<PackageReference Include="Microsoft.DotNet.ILCompiler; runtime.win-x86.Microsoft.DotNet.ILCompiler" Version="9.0.0-preview.4.24251.3" />
```

**Comment by MichalStrehovsky** [comment]
Is the project targeting net9.0? Also how did you end up with the ProjectReference to ILCompiler? You shouldn't need any. This should only require PublishAot=true in the project file.

**Comment by nahakyuu** [comment]
> Is the project targeting net9.0? Also how did you end up with the ProjectReference to ILCompiler? You shouldn't need any. This should only require PublishAot=true in the project file.

@MichalStrehovsky  I updated my original comment，The code used refers to this [link](https://github.com/dotnet/samples/blob/main/core/nativeaot/NativeLibrary/README.md), update `TargetFramework` to `net9.0`

**Comment by NCLnclNCL** [comment]
> > Is the project targeting net9.0? Also how did you end up with the ProjectReference to ILCompiler? You shouldn't need any. This should only require PublishAot=true in the project file.
> 
> @MichalStrehovsky I updated my original comment，The code used refers to this [link](https://github.com/dotnet/samples/blob/main/core/nativeaot/NativeLibrary/README.md) and [link2](https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/compiling.md), update `TargetFramework` to `net9.0`

There's something wrong with the new version, I'm using the old version so it's okay

**Comment by nahakyuu** [comment]
> > > Is the project targeting net9.0? Also how did you end up with the ProjectReference to ILCompiler? You shouldn't need any. This should only require PublishAot=true in the project file.
> > 
> > 
> > @MichalStrehovsky I updated my original comment，The code used refers to this [link](https://github.com/dotnet/samples/blob/main/core/nativeaot/NativeLibrary/README.md) and [link2](https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/compiling.md), update `TargetFramework` to `net9.0`
> 
> There's something wrong with the new version, I'm using the old version so it's okay
old version is ? I failed using **9.0.100-preview.3.24204.13**

**Comment by NCLnclNCL** [comment]
> Is the project targeting net9.0? Also how did you end up with the ProjectReference to ILCompiler? You shouldn't need any. This should only require PublishAot=true in the project file.

The latest version of dotnet, I can't build winform native aot, the build file is only 1 mb in size.

**Comment by MichalStrehovsky** [comment]
> > Is the project targeting net9.0? Also how did you end up with the ProjectReference to ILCompiler? You shouldn't need any. This should only require PublishAot=true in the project file.
> 
> @MichalStrehovsky I updated my original comment，The code used refers to this [link](https://github.com/dotnet/samples/blob/main/core/nativeaot/NativeLibrary/README.md) and [link2](https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/compiling.md), update `TargetFramework` to `net9.0`

Delete the PackageReference. It should not be needed and it will only make things worse.

**Comment by MichalStrehovsky** [comment]
> > Is the project targeting net9.0? Also how did you end up with the ProjectReference to ILCompiler? You shouldn't need any. This should only require PublishAot=true in the project file.
> 
> The latest version of dotnet, I can't run winform native aot though build successly, the build file is only 1 mb in size.

It doesn't repro with:

```
D:\wftest>dotnet --info
.NET SDK:
 Version:           9.0.100-preview.4.24222.10
 Commit:            118dfc281e
 Workload version:  9.0.100-manifests.fb4db8ea
 MSBuild version:   17.11.0-preview-24218-01+195e9289b
```

My steps:

```
dotnet new winforms -o wftest
cd wftest
dotnet publish --arch x86 -p:_SuppressWinFormsTrimError=true -p:PublishAot=true
```

The output is a 21 MB exe and works.

**Comment by NCLnclNCL** [comment]
> > > Is the project targeting net9.0? Also how did you end up with the ProjectReference to ILCompiler? You shouldn't need any. This should only require PublishAot=true in the project file.
> > 
> > 
> > The latest version of dotnet, I can't run winform native aot though build successly, the build file is only 1 mb in size.
> 
> It doesn't repro with:
> 
> ```
> D:\wftest>dotnet --info
> .NET SDK:
>  Version:           9.0.100-preview.4.24222.10
>  Commit:            118dfc281e
>  Workload version:  9.0.100-manifests.fb4db8ea
>  MSBuild version:   17.11.0-preview-24218-01+195e9289b
> ```
> 
> My steps:
> 
> ```
> dotnet new winforms -o wftest
> cd wftest
> dotnet publish --arch x86 -p:_SuppressWinFormsTrimError=true -p:PublishAot=true
> ```
> 
> The output is a 21 MB exe and works.

Newest is dotnet 9 preview 5

**Comment by nomi-san** [comment]
Any new?
The latest dotnet 9 SDK `preview-5` should work with win-x86 target but it raises error when compiling classlib due to missing some nuget dependencies that are only available in `preview-3` 🤔

**Comment by MichalStrehovsky** [comment]
> Any news? The latest dotnet 9 SDK `preview-5` should work with `win-x86` target but it raises error when compiling classlib due to missing some nuget dependencies that are only available in `preview-3` 🤔

What's the error? Did you do the "Make sure to read the instructions about nuget.config. Without that, you'll get restore errors." part of my comment?

**Comment by nomi-san** [comment]
> Make sure to read the instructions about nuget.config.

Thank you, now it works like a charm. Is there planned a date of publishing preview-5 prerelease?

**Comment by MichalStrehovsky** [comment]
> Is there planned a date of publishing preview-5 prerelease?

Sometime in June based on past preview dates. I think Preview 4 will have this usable as well and that one should come out soon.

**Comment by smoogipoo** [comment]
Is this enabled in the latest previews? Would really like to test it (not a production app so it's no biggie if not): https://github.com/smoogipoo/osu-native-diffcalc/actions/runs/9474207360/job/26103336336

```
Run dotnet publish -c Release -r win-x86 -f net9.0 --self-contained Sources/osu.Game.Native.Desktop/osu.Game.Native.Desktop.csproj
  Determining projects to restore...

Error: C:\Program Files\dotnet\sdk\9.0.100-preview.5.24307.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1203: Ahead-of-time compilation is not supported for the target runtime identifier 'win-x86'. [D:\a\osu-native-diffcalc\osu-native-diffcalc\Sources\osu.Game.Native.Desktop\osu.Game.Native.Desktop.csproj]
```

**Comment by NCLnclNCL** [comment]
> Is this enabled in the latest previews? Would really like to test it (not a production app so it's no biggie if not): https://github.com/smoogipoo/osu-native-diffcalc/actions/runs/9474346123/job/26103751949
> 
> ```
> Run dotnet publish -c Release -r win-x86 -f net9.0 --self-contained Sources/osu.Game.Native.Desktop/osu.Game.Native.Desktop.csproj
>   Determining projects to restore...
> 
> Error: C:\Program Files\dotnet\sdk\9.0.100-preview.5.24307.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1203: Ahead-of-time compilation is not supported for the target runtime identifier 'win-x86'. [D:\a\osu-native-diffcalc\osu-native-diffcalc\Sources\osu.Game.Native.Desktop\osu.Game.Native.Desktop.csproj]
> ```

![image](https://github.com/dotnet/runtime/assets/126905141/be1edfb8-4d20-4494-88b8-cc51233c643a)
add win-x86 to ILcompiler with path dotnet-sdk-9.0.100-preview.5.24267.1-win-x64\sdk\9.0.100-preview.5.24267.1

**Comment by MichalStrehovsky** [comment]
> Is this enabled in the latest previews? Would really like to test it (not a production app so it's no biggie if not): https://github.com/smoogipoo/osu-native-diffcalc/actions/runs/9474346123/job/26103751949
> 
> ```
> Run dotnet publish -c Release -r win-x86 -f net9.0 --self-contained Sources/osu.Game.Native.Desktop/osu.Game.Native.Desktop.csproj
>   Determining projects to restore...
> 
> Error: C:\Program Files\dotnet\sdk\9.0.100-preview.5.24307.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1203: Ahead-of-time compilation is not supported for the target runtime identifier 'win-x86'. [D:\a\osu-native-diffcalc\osu-native-diffcalc\Sources\osu.Game.Native.Desktop\osu.Game.Native.Desktop.csproj]
> ```

Thanks for bringing this up. This is actually a recent regression. We lost the following line when dotnet/installer repo got folded into dotnet/sdk repo: https://github.com/dotnet/installer/blob/main/src/redist/targets/GenerateBundledVersions.targets#L380

(I'm starting an email thread with the people involved in the repo migration to make sure they investigate if this was the only thing we lost in the migration.)

Fix in https://github.com/dotnet/sdk/pull/41537. It will be in Preview 6 :(
