### ISSUE TITLE
GetILFunctionBody fails in dotnet 7 for dynamic methods with CORPROF_E_DATAINCOMPLETE

### ISSUE THREAD

**Issue by AllenBiton** [dotnet/runtime#86577]
dotnet 7 removed the feature to GetILFunctionBody of dynamic methods.
This is needed for code coverage for example and faking and more.
Please bring this feature back or give us a workaround to do this so we dynamically change the code with unmanaged API.

**Comment by davmason** [comment]
Hi @AllenBiton, thanks for filing this issue. Would you be able to test a private runtime to see if it fixes your issue? I can provide you with binaries or link to a github repository where you can build them yourself.

This commit should fix your issue https://github.com/davmason/runtime/commit/930b0cbc5f69b6e8b528850eb376e28eb3987642

**Comment by davmason** [comment]
To update this thread, @AllenBiton and I are chatting privately and he is testing a private build to see if it fixes the issue
