### ISSUE TITLE
[Tracking] Decide if the tags order matter when creating meter or instrument

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#86614]
As we began caching the instruments or meters that are created, we aim to avoid creating new objects if the creation parameters (such as name, unit, tags) match any of the cached objects. The issue at hand is whether we should consider the comparison of tags to be order sensitive or not. This is a decision we need to make.

**Comment by JamesNK** [comment]
From other thread:

> What I'm getting at is that if you specify meter options with the same name and two tags in different `MeterFactory.Create` calls:
> * Create(Name = "Test", Tags = "A=1, B=2")
> * Create(Name = "Test", Tags = "B=2, A=1")
>  
> The result is two different meters. Do exporters, e.g. Prometheus, care about tag order?
> 
> I don't know if it's important or not, I just want to make sure a metrics expert has thought about it.

**Comment by tarekgh** [comment]
This is addressed by https://github.com/dotnet/runtime/pull/86740
