### ISSUE TITLE
`double.Parse` with `NumberStyles.Currency` Fails to Parse Strings with Non-Breaking Spaces

### ISSUE THREAD

**Issue by Megasware128** [dotnet/runtime#86641]
### Description

When attempting to parse a string containing a certain type of whitespace (character 160, or non-breaking space) using `double.Parse` with `NumberStyles.Currency`, an exception is thrown. This happens even though the Unicode standard considers character 160 to be a whitespace character.

### Reproduction Steps

Here is a minimal code snippet to reproduce the issue:

```csharp
string price = "€ 0,24932"; // contains a non-breaking space (character 160)
double.Parse(price, NumberStyles.Currency, new CultureInfo("nl-NL"));
```
This will throw a FormatException.

### Expected behavior

`double.Parse` with `NumberStyles.Currency` should be able to correctly parse strings containing any type of whitespace, including non-breaking spaces.

### Actual behavior

`double.Parse` throws a `FormatException` when attempting to parse a string containing a non-breaking space.

### Regression?

It's unclear if this behavior is a regression or if it has always been present in .NET.

### Known Workarounds

A workaround for this issue is to replace all whitespace characters with a regular space before parsing. Here is an example:

```csharp
private static double ParsePrice(string price)
{
    Span<char> chars = stackalloc char[price.Length];

    // Replace non-standard whitespace with regular whitespace
    for (var i = 0; i < price.Length; i++)
    {
        var c = price[i];

        chars[i] = char.IsWhiteSpace(c) ? ' ' : c;
    }

    return double.Parse(chars, NumberStyles.Currency, new CultureInfo("nl-NL"));
}
```

### Configuration

The issue was encountered on a local development machine running Windows 11 x64, using .NET 7 with isolated Azure Functions. It is however not necessarily tied to this specific configuration and is expected to occur in other environments as well.

### Other information

The issue seems to stem from [the `IsWhite` method in the `System/Number.Parsing.cs` file](https://github.com/dotnet/runtime/blob/026f5e0609f8b292c45eee3411eb3e0d41d845a8/src/libraries/System.Private.CoreLib/src/System/Number.Parsing.cs#L1267), which only considers a limited number of characters as whitespace.

It's important to note that this behavior is different from the `char.IsWhiteSpace` method available in .NET. `char.IsWhiteSpace` correctly recognizes character 160 as a whitespace character, but the `IsWhite` method used by `double.Parse` does not.

**Comment by tannergooding** [comment]
This is expected behavior and is covered by https://learn.microsoft.com/en-us/dotnet/api/system.globalization.numberstyles?view=net-7.0

> | Field | Bit | Description |
> | -- | -- | -- |
> | AllowLeadingWhite | 1 | Indicates that leading white-space characters can be present in the parsed string. Valid white-space characters have the Unicode values U+0009, U+000A, U+000B, U+000C, U+000D, and U+0020. Note that this is a subset of the characters for which the IsWhiteSpace(Char) method returns true. |
> | AllowTrailingWhite | 2 | Indicates that trailing white-space characters can be present in the parsed string. Valid white-space characters have the Unicode values U+0009, U+000A, U+000B, U+000C, U+000D, and U+0020. Note that this is a subset of the characters for which the IsWhiteSpace(Char) method returns true. |

You should feel free to open an API proposal suggesting this functionality be changed. I expect the easiest way would be to request a new `NumberStyles` flag named something like `AllowLeadingUnicodeWhitespace` or similar. API review can then discuss the merits of taking a behavioral change to `AllowLeadingWhite` vs introducing a new option.

It would need weigh-in from a few others before being marked "ready-for-review". CC. @tarekgh, @stephentoub, @GrabYourPitchforks
