### ISSUE TITLE
Mono EventPipe code in ep_rt_temp_path_get has an off by 1 issue

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#86640]
In the [code ](https://github.com/dotnet/runtime/blob/main/src/mono/mono/eventpipe/ep-rt-mono.h#L1099-L1101), if the buffer is just long enough to hold the temp directory, adding the G_DIR_SEPARATOR character will go past the buffer

cc @elinor-fung

**Comment by lateralusX** [comment]
https://github.com/dotnet/runtime/blob/main/src/mono/mono/eventpipe/ep-rt-mono.h#L1096-L1102C3

should be:

```
if (result <= 0 || GINT32_TO_UINT32(result) >= buffer_len)
    ep_raise_error ();

if (buffer [result - 1] != G_DIR_SEPARATOR) {
    if (GINT32_TO_UINT32(result) >= buffer_len - 1)
        ep_raise_error ();
    buffer [result++] = G_DIR_SEPARATOR;
    buffer [result] = '\0';
}

```
