### ISSUE TITLE
ConfigurationBindingGenerator does not work unless Microsoft.Extensions.DependencyInjection.Abstractions is referenced

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#86653]
### Description

Reported in https://github.com/dotnet/runtime/issues/86557

When creating an app that only references Microsoft.Extensions.Configuration.Binder, the source generator for configuration will not run unless Microsoft.Extensions.Hosting is also referenced.

This appears to be due to a check for `IServiceCollection` here:
https://github.com/dotnet/runtime/blob/8f19f4ebd511994be27a2e1f4c88424a26f91e7c/src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Parser.cs#L45-L48

The binder can be used without DI, so we shouldn't require this type definition to be present.

### Reproduction Steps

Project:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.0-preview.5.23273.2" />
    <!-- <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0-preview.5.23273.2" /> -->
  </ItemGroup>

</Project>
```

Nuget.Config:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="dotnet8" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

Source code:
```c#
var c = new ConfigurationBuilder().Build();
var x = c.GetSection("Anything").Get<TimeSpan?>((_) =>  {} );
Console.WriteLine(x.GetValueOrDefault());
```

Repro project: [testConfig.zip](https://github.com/dotnet/runtime/files/11547534/testConfig.zip) (remove DI.Abstractions reference to repro)

### Expected behavior

Build succeeds and uses generator.

### Actual behavior

Generator is not triggered, uncomment `Microsoft.Extensions.DependencyInjection.Abstractions` to make generator run.

**Comment by ericstj** [comment]
Thank you @chrisoverzero for the original report.

**Comment by layomia** [comment]
This was fixed in https://github.com/dotnet/runtime/pull/87733. I believe I added a dedicated test but somehow it was dropped. Will re-add one then close this issue.
