### ISSUE TITLE
Wasm.Build.Tests timeouts while waiting for the web server

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#86658]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=282580
Build error leg or test failing: Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations
Pull request: https://github.com/dotnet/runtime/pull/86415

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "System.Exception : Timed out waiting for the web server url",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[282580](https://dev.azure.com/dnceng-public/public/_build/results?buildId=282580)|dotnet/runtime|[Workloads-Wasm.Build.Tests.WasmTemplateTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=282580&view=ms.vss-test-web.build-test-results-tab&runId=5621478&resultId=100101)|dotnet/runtime#86415|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|1|

**Comment by radical** [comment]
Removed `blocking-clean-ci` because this seems to be a one-off, and hasn't been seen since.

**Comment by radical** [comment]
> Removed `blocking-clean-ci` because this seems to be a one-off, and hasn't been seen since.

Closing this. It can be reopened if it is hit again.
