### ISSUE TITLE
Microsoft.Extensions.DependencyInjection NuGet Package Missing README File

### ISSUE THREAD

**Issue by mckennabarlow** [dotnet/runtime#86663]
As one of the top most installed NuGet packages, your Microsoft.Extensions.DependencyInjection package is extremely important to the developer ecosystem. The NuGet team has noticed that your package on NuGet.org is missing a README file.

Please take a moment to add a README file to your package repository.
Our customer research indicates that one of the top problems that package consumers face is insufficient package documentation such as README files. Adding a README file to your package will help users quickly understand what the package is and what it does. Since your README will be the first impression for users when they view your package on NuGet.org, it is crucial for authors to write and include high-quality READMEs for their packages.

There is no specific format or structure to a good README – instead it’s about effectively communicating the purpose and functionality of your package to potential users. If you are unsure of where to start, check out our [blog post](https://devblogs.microsoft.com/nuget/write-a-high-quality-readme-for-nuget-packages/) for some README best practices and a template file.
If you are new to NuGet README, learn more about [how to add a README to your NuGet Package](https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/).

Your feedback is very important to us. If you experience any issue using READMEs or have ideas for improvements – please feel free to contact us by replying to this issue.

**Comment by MSDN-WhiteKnight** [comment]
There's already an issue for adding missing readmes for several NuGet packages: <https://github.com/dotnet/runtime/issues/59630>. Should i close that big issue in favour of specific issues for each package? Or the opposite, specific issues should be closed as duplicates of the big one?

>There is no specific format or structure to a good README

But note that runtime repository has guidelines for package readme: https://github.com/MSDN-WhiteKnight/runtime/blob/main/docs/coding-guidelines/libraries-packaging.md#package-readme

**Comment by ericstj** [comment]
Closing this in favor of https://github.com/dotnet/runtime/issues/59630.  This particular library will be addressed with https://github.com/dotnet/runtime/pull/91210 which will be merged for 8.0 RC2
