### ISSUE TITLE
X509Certificate2 Issuer is empty on Linux in netcoreapp3.1

### ISSUE THREAD

**Issue by yonineitor** [dotnet/runtime#86679]
Similiar to https://github.com/dotnet/runtime/issues/29693, but using netcoreapp3.1.

I'm seeing an empty Issuer parsing certificates that are providers by a thyrd party

The following code results is success on Windows, but an empty Issueron Linux:

`
 X509Certificate2 cert = new X509Certificate2(csdBlob, csdPassword, X509KeyStorageFlags.MachineKeySet);
      System.Console.WriteLine("Issuer", cert.Issuer);
`

When i check on linux or wsl the _oppenssl document.pfx -issuer_ it works Issuer ok

**Comment by vcsjones** [comment]
Thanks for taking the time to open an issue. A couple of things.

First, .NET Core 3.1 is [out of support](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core) and is not receiving fixes. Does this issue reproduce for you with .NET 6 or .NET 7?

If it does reproduce on a supported .NET version, are you able to share the certificate? We would only need the public portion of the certificate, not the private key.

**Comment by yonineitor** [comment]
Yes, i tried with .NET 6 & 7 same result
I cant share the certificate :(
I tried change the flag X509KeyStorageFlags.Exported and same result

Fails on WSL Ubuntu 20.04 and linux versions.


The cert.Subject works ok

**Comment by vcsjones** [comment]
> If I wrote a tool to extract the contents of the issuer from the certificate

Actually, it is probably just as simple as:

```C#
using System.Security.Cryptography.X509Certificates;

X509Certificate2 cert; // get your cert
Console.WriteLine(Convert.ToBase64String(cert.IssuerName.RawData));
```

If you are able to share the output of that, I think that would give us enough information to understand the underlying issue. If it errors or produces no output, then we'll have to extract the issuer some other way.

**Comment by yonineitor** [comment]
Issuer information has sensivity information where i work.

When i print the code:
`
Console.WriteLine(Convert.ToBase64String(cert.IssuerName.RawData));  // bytes[436]
`
Return the value "MIIBsDE6MDgGA1UEAwwxQS5DLiBkZWwgU2Vydmlja................24gQ2VudHJhbCBkZSBTZXJ2aWNpb3MgVHJpYnV0YXJpb3MgYWwgQ29udHJpYnV5ZW50ZQ=="

Note: the Issuer value use some accents and address with comma like: street 1, int 10

**Comment by yonineitor** [comment]
When i debug in windows the output in the cert.Issuer looks 
![image](https://github.com/dotnet/runtime/assets/4680382/1d315feb-419d-4dca-a19f-ec6344473ba1)

Could it be something from the decoding?

**Comment by bartonjs** [comment]
I'm guessing that the L or S values there claim to be an IA5String, but contain non-IA5 data.  But, without the full value of the IssuerName encoding being shared this isn't really possible to answer.  (You can't `...` away the middle)

**Comment by vcsjones** [comment]
I would agree with @bartonjs that it's likely you have an AttributeValue that declares it is a particular type of string that contains invalid encoding.

You can try something like this to get better error diagnostics.

This will try to print the most minimal diagnostic information about decoding the Issuer. If it can't decode something, it will print what could not be decoded in its original binary form.

If this does not help us narrow down the cause, then I would agree with Jeremy that there is not enough information to understand the cause of the issue.

```C#
using System.Formats.Asn1;
using System.Security.Cryptography.X509Certificates;

X509Certificate2 cert; // YourCert
DiagnoseDN(cert.IssuerName);

static void DiagnoseDN(X500DistinguishedName dn)
{
    ReadOnlyMemory<byte> dnBytes = dn.RawData;
    AsnReader reader = new AsnReader(
        dnBytes,
        AsnEncodingRules.DER,
        new AsnReaderOptions { SkipSetSortOrderVerification = true});

    Console.WriteLine("Started reading distinguished name.");

    Console.WriteLine("Started reading RDNSequence");
    AsnReader rdnSequence = reader.ReadSequence();
    reader.ThrowIfNotEmpty();

    Console.WriteLine("Started iterating RDNSequence");
    while (rdnSequence.HasData)
    {
        Console.WriteLine("Started reading RelativeDistinguishedName");
        AsnReader rdn = rdnSequence.ReadSetOf(true);

        Console.WriteLine("Started reading AttributeTypeAndValue");
        AsnReader attributeTypeAndValueReader = rdn.ReadSequence();

        Console.WriteLine("Started reading AttributeType");
        string attributeType = attributeTypeAndValueReader.ReadObjectIdentifier();
        Console.WriteLine($"AttributeType is {attributeType}");
        Console.WriteLine("Finished reading AttributeType");

        Console.WriteLine("Started reading AttributeValue");
        Asn1Tag attributeValueTag = attributeTypeAndValueReader.PeekTag();
        Console.WriteLine($"Tag is {attributeValueTag}");

        // Peek the value as raw bytes incase it's an invalid DirectoryString.
        ReadOnlyMemory<byte> attributeValue = attributeTypeAndValueReader.PeekEncodedValue();

        try
        {
            string str = attributeTypeAndValueReader.ReadCharacterString((UniversalTagNumber)attributeValueTag.TagValue);
            Console.WriteLine("The AttributeValue is " + str);
        }
        catch (Exception e)
        {
            Console.WriteLine(@$"ERROR: the component with OID {attributeType} has a tag of {attributeValueTag} that could not be decoded. " +
            $"The raw content is \"{Convert.ToHexString(attributeValue.Span)}\". The error is {e.GetType().FullName}: {e.Message}");
        }

        Console.WriteLine("Finished reading AttributeValue");

        Console.WriteLine("Finished reading RelativeDistinguishedName");
    }

    Console.WriteLine("Finished iterating RDNSequence");
    Console.WriteLine("Finished reading distinguished name.");
}
```

**Comment by yonineitor** [comment]
@bartonjs @vcsjones 
Thank you very much for your help.
The API provider generated the certificates wrong, They will be created again.

The error is validated when using the DiagnoseDn function:

ERROR: the component with OID 1.2.840.113549.1.9.2 has a tag of PrintableString that could not be decoded. The raw content is "134E726573706F6E7361626C653A2041646D696E69737472616369C3B36E2043656E7472616C20646520536572766963696F732054726962757 46172696F7320616C20436F6E747269627579656E7465". The error is System.Formats.Asn1.AsnContentException: The ASN.1 value is invalid.
