### ISSUE TITLE
DefaultMeterFactory.Create and MeterOptions.Scope

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#86684]
### Description

A meter factory sets the scope of the meter it creates to itself:

https://github.com/dotnet/runtime/blob/ce689d9189d549e249f4bb5e3d9aeef322464bfb/src/libraries/Microsoft.Extensions.Diagnostics/src/Metrics/DefaultMeterFactory.cs#L50-L51

However, a scope can be provided on `MeterOptions.Scope`, which passed to `Create`.

`Create` should probably throw an error if a scope is specified. Otherwise there could be confusion about why the specified scope value wasn't used.

### Reproduction Steps

```cs
object myCoolScope = new object();
IMeterFactory f = CreateFactory();
Meter meter = f.Create(new MeterOptions("Name") { Scope = myCoolScope });

Debug.Assert(meter.Scope == myCoolScope); // Fails?!?!
```

### Expected behavior

Throw an error.

### Actual behavior

The scope provided by the user is ignored, and the meter scope is set to the factory.

**Comment by JamesNK** [comment]
cc @tarekgh @noahfalk

**Comment by tarekgh** [comment]
Thanks @JamesNK. I'll take care with that.

**Comment by tarekgh** [comment]
This is addressed by https://github.com/dotnet/runtime/pull/86740
