### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'System.Security.Cryptography, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3 a' or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by jagadeswar-devarasetti-dsw** [dotnet/runtime#86693]
Hi !!

i am working on .Net and python ,

so my task is to communicate or call c# functions in python using pythonnet library of clr package 

i had created c# script along with functions and also able build sucessfully and run the code , got ouput as well..

but while i calling from python using pythonnet library 

i am getting this error :

Traceback (most recent call last):
  File ".\test.py", line 13, in <module>
    print(obj2.DecryptData(EncryptedText,Encryptionkey))
System.IO.FileNotFoundException: Could not load file or assembly 'System.Security.Cryptography, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3
a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Security.Cryptography, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Test2.Program.DecryptData(String EncryptedText, String Encryptionkey)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

dotnet details:
C:\Users\jjaga>dotnet --info
.NET SDK:
 Version:   7.0.302
 Commit:    990cf98a27

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.302\

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  7.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

can anyone please help what might be the solution

**Comment by vitek-karas** [comment]
Based on the error the .NET code is running on .NET Framework, not on .NET 6 (or .NET 7). If you're able to get some code to run, you can validate this by for example printing out the location of `typeof(object).Assembly.Location`.

**Comment by jagadeswar-devarasetti-dsw** [comment]
thanks @vitek-karas for replying

i am little bit new to this .net framework 

i calling through python 

here is my reference code:

import clr 
import sys
clr.AddReference("/Desktop/c#/bin/Debug/net7.0/c#") # this is c# dll file 
#from Test import calci
from Test2 import Program

#obj = calci()
obj2 = Program()
#print(obj.add(1,2))
Encryptionkey = "key"
EncryptedText = "text to be encrypted"

print(obj2.DecryptData(EncryptedText,Encryptionkey))

so it problem in my python code or should i use in c# script 

here is my c# script below:


using System;
using System.IO;
using System.Security.Cryptography;
using System.Text;

namespace Test2{
public class Program
{
 public static string EncryptData(string textData, string encryptionKey)
 {
using (RijndaelManaged aesEncryption = new RijndaelManaged())
{
    aesEncryption.Mode = CipherMode.CBC;
    aesEncryption.Padding = PaddingMode.PKCS7;
    aesEncryption.KeySize = 128;
    aesEncryption.BlockSize = 128;

    byte[] passBytes = Encoding.UTF8.GetBytes(encryptionKey);
    byte[] encryptionKeyBytes = new byte[16];
    int len = passBytes.Length;
    if (len > encryptionKeyBytes.Length)
    {
    len = encryptionKeyBytes.Length;
    }
    Array.Copy(passBytes, encryptionKeyBytes, len);
    aesEncryption.Key = encryptionKeyBytes;
    aesEncryption.IV = encryptionKeyBytes;

    ICryptoTransform objTransform = aesEncryption.CreateEncryptor();
    byte[] textDataBytes = Encoding.UTF8.GetBytes(textData);
    byte[] encryptedBytes = objTransform.TransformFinalBlock(textDataBytes, 0, textDataBytes.Length);
    return Convert.ToBase64String(encryptedBytes);
 }
}


 public string DecryptData(string EncryptedText, string Encryptionkey)
{

RijndaelManaged aesEncryption = new RijndaelManaged();
aesEncryption.Mode = CipherMode.CBC;
aesEncryption.Padding = PaddingMode.PKCS7;
aesEncryption.KeySize = 0x80;
aesEncryption.BlockSize = 0x80;
 byte[] encryptedTextByte = Convert.FromBase64String(EncryptedText);
byte[] passBytes = Encoding.UTF8.GetBytes(Encryptionkey);
byte[] EncryptionkeyBytes = new byte[0x10];
int len = passBytes.Length;
if (len > EncryptionkeyBytes.Length)
{
len = EncryptionkeyBytes.Length;
 }
 Array.Copy(passBytes, EncryptionkeyBytes, len);
 aesEncryption.Key = EncryptionkeyBytes;
aesEncryption.IV = EncryptionkeyBytes;
byte[] TextByte = aesEncryption.CreateDecryptor().TransformFinalBlock(encryptedTextByte, 0, encryptedTextByte.Length);
return Encoding.UTF8.GetString(TextByte);  //it will return readable string
}
static void Main()
{

    Program program = new Program();
 
 }
}
}


so please help me with your valuable suggestions

**Comment by jagadeswar-devarasetti-dsw** [comment]
> Based on the error the .NET code is running on .NET Framework, not on .NET 6 (or .NET 7). If you're able to get some code to run, you can validate this by for example printing out the location of `typeof(object).Assembly.Location`.

location i got this :



C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.5\System.Private.CoreLib.dll

**Comment by vitek-karas** [comment]
That's weird - since that means it runs .NET 7.
Do you get a callstack from the error somewhere? You might try to attach a debugger and try to catch the exception as it happens as well.

**Comment by jkotas** [comment]
pythonnet uses .NET Framework by default. You need to explicitly tell pythonnet that you want to use .NET Core. Details are at https://pypi.org/project/pythonnet/ .

Either set `PYTHONNET_RUNTIME=coreclr` environment variable, or add this before `import clr` to your python file:
```
from pythonnet import load
load("coreclr")
```

**Comment by jagadeswar-devarasetti-dsw** [comment]
Thanks @jkotas able to run successfully
Thanks @vitek-karas for your support
