### ISSUE TITLE
QUIC Listener ConnectionOptionsCallback ALPN Narrowing Down Failure with Wrong Error Code

### ISSUE THREAD

**Issue by liveans** [dotnet/runtime#86701]
This is a tracking issue for `msquic` next release to activate `Listener_AlpnNarrowingDown_Failure` test inside of `QuicListenerTests`.

**Description:**
While we're narrowing down ALPN negotiation list with `ConnectionOptionsCallback`, Quic is renegotiating ALPN with the Client.
```c#
                ApplicationProtocols = new List<SslApplicationProtocol>()
                {
                    new SslApplicationProtocol("foo"),
                    new SslApplicationProtocol("bar"),
                    new SslApplicationProtocol("test"),
                },
                ConnectionOptionsCallback = (_, _, _) =>
                {
                    // Narrowing down alpn list to more specific.
                    var options = CreateQuicServerOptions();
                    options.ServerAuthenticationOptions.ApplicationProtocols = new()
                    {
                        new SslApplicationProtocol("bar"),
                        new SslApplicationProtocol("test"),
                    };
                    return ValueTask.FromResult(options);
                }
```

In that case, if Quic can't find any matching ALPN between the client and server, the connection is failing with `QUIC_STATUS_INTERNAL_ERROR` instead of `QUIC_STATUS_ALPN_NEG_FAILURE`.

This is coming from `msquic` and has already been fixed in both the `main` and `release/2.2` branches. (https://github.com/microsoft/msquic/pull/3647 and https://github.com/microsoft/msquic/pull/3649)

**Comment by liveans** [comment]
msquic v2.2.2 has been released, which includes these changes. https://github.com/microsoft/msquic/releases/tag/v2.2.2 We need to update our pipeline msquic package versions and I will enable the test on  https://github.com/dotnet/runtime/pull/86659 this PR.

**Comment by wfurt** [comment]
docker images are easy and Dobian should be already done. RH Stream 8 will be triggered when https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/895 is merged. 

For actual Helix machines it may take several more weeks. AFAIK they are on auto-updated and updated on most Wednesdays.
