### ISSUE TITLE
NativeAOT produces very large `__LINKEDIT` segment on macOS

### ISSUE THREAD

**Issue by nxtn-staged** [dotnet/runtime#86707]
### Description

NativeAOT on macOS typically produces binaries about twice the size with large, almost zero-filled `__LINKEDIT` segments. Is this expected？

### Reproduction Steps

```
dotnet new console --aot --output Test.Console
cat > ./Test.Console/Program.cs << EOF
using var client = new HttpClient();
Console.WriteLine(await client.GetStringAsync("https://example.com"));
EOF
dotnet publish ./Test.Console/Test.Console.csproj
ls -lh ./artifacts/publish/Test.Console/release
```

### Expected behavior

**win-x64**

```
5.0M Test.Console.exe
 22M Test.Console.pdb
```

**linux-x64**

```
6.6M Test.Console
 19M Test.Console.dbg
```

### Actual behavior

**osx-x64**

```
 11M Test.Console
 24M Test.Console.dwarf
```

```
% bloaty ./artifacts/publish/Test.Console/release/Test.Console
    FILE SIZE        VM SIZE    
 --------------  -------------- 
  37.9%  4.11Mi  34.1%  4.11Mi    [__LINKEDIT]
  26.4%  2.87Mi  23.8%  2.87Mi    __TEXT,__managedcode
  13.3%  1.45Mi  12.0%  1.45Mi    __TEXT,__const
   0.0%       0   9.2%  1.11Mi    __DATA,hydrated
   8.5%   938Ki   7.6%   938Ki    __TEXT,__eh_frame
   5.1%   563Ki   4.6%   563Ki    __TEXT,__text
   4.1%   459Ki   3.7%   459Ki    __DATA,.dotnet_eh_table
   2.7%   297Ki   2.4%   297Ki    __TEXT,__unwind_info
   0.8%  88.5Ki   0.7%  88.5Ki    __DATA,__data
   0.0%       0   0.5%  61.2Ki    __DATA,__bss
   0.4%  39.5Ki   0.3%  39.5Ki    __TEXT,__cstring
   0.3%  30.1Ki   0.2%  30.1Ki    Function Start Addresses
   0.0%       0   0.2%  29.4Ki    __DATA,__common
   0.1%  11.9Ki   0.1%  14.0Ki    [__DATA]
   0.1%  10.3Ki   0.1%  10.7Ki    [14 Others]
   0.1%  10.3Ki   0.1%  10.3Ki    __TEXT,__unbox
   0.1%  9.00Ki   0.1%  9.00Ki    [__DATA_CONST]
   0.1%  6.76Ki   0.1%  6.76Ki    String Table
   0.1%  6.62Ki   0.1%  6.62Ki    Symbol Table
   0.0%  3.39Ki   0.0%  3.39Ki    __DATA_CONST,__got
   0.0%  3.38Ki   0.0%  3.27Ki    [Mach-O Headers]
 100.0%  10.8Mi 100.0%  12.0Mi    TOTAL
```

**osx-arm64**

```
 11M Test.Console
 24M Test.Console.dwarf
```

```
% bloaty ./artifacts/publish/Test.Console/release/Test.Console
    FILE SIZE        VM SIZE    
 --------------  -------------- 
  36.5%  4.06Mi  33.0%  4.07Mi    [__LINKEDIT]
  28.6%  3.19Mi  25.8%  3.19Mi    __TEXT,__managedcode
  12.8%  1.42Mi  11.5%  1.42Mi    __TEXT,__const
   0.0%       0   9.0%  1.11Mi    __DATA,hydrated
   8.3%   941Ki   7.4%   941Ki    __TEXT,__eh_frame
   4.6%   520Ki   4.1%   520Ki    __TEXT,__text
   4.0%   451Ki   3.6%   451Ki    __DATA,.dotnet_eh_table
   2.6%   293Ki   2.3%   293Ki    __TEXT,__unwind_info
   0.8%  88.5Ki   0.7%  88.5Ki    Code Signature
   0.8%  88.5Ki   0.7%  88.5Ki    __DATA,__data
   0.0%       0   0.5%  61.1Ki    __DATA,__bss
   0.3%  39.7Ki   0.3%  39.7Ki    __TEXT,__cstring
   0.3%  31.5Ki   0.2%  31.5Ki    Function Start Addresses
   0.0%       0   0.2%  29.2Ki    __DATA,__common
   0.2%  19.0Ki   0.2%  19.1Ki    [14 Others]
   0.1%  9.29Ki   0.1%  9.39Ki    [__TEXT]
   0.1%  8.19Ki   0.1%  8.19Ki    [__DATA_CONST]
   0.0%  4.08Ki   0.1%  7.05Ki    [__DATA]
   0.1%  6.88Ki   0.1%  6.88Ki    __TEXT,__unbox
   0.1%  6.71Ki   0.1%  6.71Ki    String Table
   0.1%  6.58Ki   0.1%  6.58Ki    Symbol Table
 100.0%  11.1Mi 100.0%  12.3Mi    TOTAL
```

### Configuration

**win-x64**

```
> dotnet --info
.NET SDK:
 Version:   8.0.100-preview.4.23260.5
 Commit:    2268e7b15c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
```

**linux-x64**

```
$ dotnet --info
.NET SDK:
 Version:   8.0.100-preview.4.23260.5
 Commit:    2268e7b15c

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
```

**osx-x64**

```
% dotnet --info
.NET SDK:
 Version:   8.0.100-preview.4.23260.5
 Commit:    2268e7b15c

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.4
 OS Platform: Darwin
 RID:         osx.13-x64
```

**osx-arm64**

```
% dotnet --info
.NET SDK:
 Version:   8.0.100-preview.4.23260.5
 Commit:    2268e7b15c

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.4
 OS Platform: Darwin
 RID:         osx.13-arm64
```

**Comment by jkotas** [comment]
@filipnavara Do you have any insights about where the large `__LINKEDIT` section is coming from?

**Comment by filipnavara** [comment]
> @filipnavara Do you have any insights about where the large `__LINKEDIT` section is coming from?

Unfortunately not. I'd use XMachOViewer to figure out which link edit block is taking the space. I can look at it in more detail next week after I get back from vacation...

**Comment by MichalStrehovsky** [comment]
@ivanpovazan started looking at it this week - in a MAUI app he sent me this segment was 20 MB and I was puzzled what it was when looking at it with a hex editor. A third of the MAUI executable was zeros.

**Comment by ivanpovazan** [comment]
we've noticed a similar (but much much smaller) behaviour with MAUI iOS template app built with MonoAOT, where the section is around 200kb also zeroed out: https://gist.github.com/ivanpovazan/97ec573836caca3f8347b8eafa2cad14 
we are currently looking into this

**Comment by MichalStrehovsky** [comment]
Stripping can be disabled with `<StripSymbols>false<StripSymbols>`, deleting obj/bin and rebuilding. Various comments in ld64 seems to indicate that this is indeed where symbol table was: https://github.com/apple-oss-distributions/ld64/blob/59a99ab60399c5e6c49e6945a9e1049c42b71135/src/ld/parsers/macho_dylib_file.cpp#L371-L372

**Comment by MichalStrehovsky** [comment]
We're likely not invoking the strip tool correctly. I cannot imagine symbol stripping would work like this by design on Apple platforms that really care about size. Is there a way to see how stripping happens on a normal obj-c/swift/c++ Xcode project?

**Comment by filipnavara** [comment]
There's also the reserved room for code signature at the end of the file/__LINKEDIT section. It should not be this big though.

**Comment by filipnavara** [comment]
> We're likely not invoking the strip tool correctly.

I think the strip tool is rarely used on Apple platforms. You just tell the linker/compiler to strip it. One of the reasons is that the linker produces ad-hoc code signatures nowadays, and any further modification has to account for the code signature. It is hard to rewrite the signature, but it's even harder to reallocate the space for the signature (you need to change size of __LINKEDIT section, which has descriptor at the beginning of file, but also calculate the size of the signature at the same time, which needs to know the sizes of all headers and sections).

**Comment by jkotas** [comment]
> You just tell the linker/compiler to strip it.

Strip it and save it into a separate file? (ie make it work just like it works with Windows linkers and .pdbs) What is the command line option for that?

**Comment by ivanpovazan** [comment]
After some investigation, there is something wrong with the way we are doing native linking, not stripping. 

Regarding the large sections being zeroed out, I am mainly referring to the: `__LINKEDIT Export Info` section, which seems to include all exported symbols if we do not strip symbols. 

To explain it further, if I do the following with what @nxtn-staged provided as a repro:
- Add an empty `exports.txt` file: `touch Test.Console/exports.txt`
- Publish the project via: `dotnet publish ./Test.Console/Test.Console.csproj -p:ExportsFile=exports.txt`

The size of the app comes down to: 7356576

The flag above will force passing to the native linker `-exported_symbols_list "exports.txt"` which seems to affect what ends up in `__LINKEDIT Export Info`. Stipping the symbols afterwards seems to work just fine.

Additionally, applying the same approach to the MAUI iOS with NativeAOT issue, shaves the 20MB of zeroes from the binary.

**Comment by filipnavara** [comment]
> Strip it and save it into a separate file?

For future reference: That doesn't quite apply to Mach-O. In Apple world the debug symbols are not propagated to the final executable. Instead the executable has an assigned GUID and there's a map that points to the original .o files which have DWARF symbols. `dsymutil` can then be used to collect the the symbols and create a symbol file "bundle" which you can distribute or transfer to another machine (similarly to .pdb files). Lastly, the dSYM bundle can be located anywhere since Spotlight indexes the files and the global search index is also used by `lldb`.

**Comment by filipnavara** [comment]
@ivanpovazan That kinda rings a bell. We output some obnoxious amount of symbols in the Mach-O .o files in the ILCompiler output because the Apple linker is both buggy and picky. It basically needs to find function boundaries and match them with the DWARF exception info. Unlike ELF there are no explicit function symbols with size. It also notoriously misinterprets symbol+offset relocations in context of the debug symbols, which - once again - means outputting extra symbols (for methods with try/catch and try/finally blocks).

**Comment by agocke** [comment]
> > Strip it and save it into a separate file?
> 
> For future reference: That doesn't quite apply to Mach-O. In Apple world the debug symbols are not propagated to the final executable. Instead the executable has an assigned GUID and there's a map that points to the original .o files which have DWARF symbols. `dsymutil` can then be used to collect the the symbols and create a symbol file "bundle" which you can distribute or transfer to another machine (similarly to .pdb files). Lastly, the dSYM bundle can be located anywhere since Spotlight indexes the files and the global search index is also used by `lldb`.

Doing some reading, I don't quite understand what the MacOS standard is, but I agree that it sounds like Mac is different from Linux and it's expected for linkers/Mach-O tools to split debug symbols ahead of time.

Separately, it looks like our default is to produce a "flat" file, which is at best seems not-preferred and potentially not-supported, instead of a dSYM bundle, which is the preferred one. I think this is because the runtime build wants to upload a single symbol file, and dSYMs are actually directories. We may need to do some fiddling with the infra to get runtime to produce whatever it needs, but produce dSYMs for customers

**Comment by ivanpovazan** [comment]
Here is another resource explaining the issue and confirms similar approach I gave above with empty `exports.txt` file: https://github.com/qyang-nj/llios/blob/main/exported_symbol/README.md#strip
