### ISSUE TITLE
Frozen Collection Follow-up: Items/Keys/Values properties

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/runtime#86719]
Spawned from: #77891 - Frozen collection follow-ups

The current design has Items/Keys/Values properties that return ImmutableArray<>. This is to enable access to the data as a ReadOnlySpan<>, indexibility, via refs, and with very fast enumeration. This does, however, place a requirement on implementations that they either store the keys/values/items separately and in contiguous memory or that implementations maintain a second copy of the data that does so. If we'd be willing to give up on the ReadOnlySpan<> and indexing capabilities, these types should instead be changed to some FrozenEnumerable<>-like type that would allow different implementations to vary how the data was stored.

**Comment by adamsitnik** [comment]
Thanks to all of the recent performance improvements ([Frozen collection construction performance · Issue #87964 · dotnet/runtime (github.com)](https://github.com/dotnet/runtime/issues/87964#issuecomment-1604355892)), we were able to remove `optimizeForReading` overloads and the `WrappedDictionaryFrozenDictionary` type which was maintaining a separate copy of key and value arrays to implement the abstract methods of `FrozenDictionary`. So, with all the existing implementations the design choice is correct.

Speaking of the future ones, both `TKey` and `TValue` have no generic constraints, so they can be anything, including types with references. Which means that we cannot use unmanaged memory for storing all keys and values. It’s possible to implement a dedicated version for selected primitive types and use unmanaged memory, but this would require handling the lifecycle of the unmanaged memory, which can be troublesome and should not be encouraged. So, I would say that managed arrays are our only choice.

Then, the most important aspect of frozen dictionaries is to get value for given key as fast as possible. This includes getting a hash code for given key and iterating over all keys with the same hash code until we find equal key. To achieve the best performance in such a code path, we need to store keys and values separately.

In my opinion the current design is optimal from both performance point of view, and user experience (keys and values are exposed as Immutable Arrays so they can be used for LINQ but those who need the best perf can get a readonly span out of it and do whatever they need).

Having said that, I am going to close the issue as done.
