### ISSUE TITLE
[API Proposal]: Create an AsnReader from an AsnReader

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#86723]
### Background and motivation

The `AsnReader` is great for forward-only reading, but sometimes you want to use it, but not consume it; or you want to be able to put it back to how it was before you read through it.

It would be nice if there was a way to copy a reader with its current state. The Peek methods don't work particularly well for this scenario, since that only gives you the data for the next encoded value, not any trailing data.

I would propose a constructor on AsnReader that takes an AsnReader, and duplicates the state.

### API Proposal

```csharp
namespace System.Formats.Asn1;

public partial class AsnReader
{
    public AsnReader(AsnReader reader);
}
```

### API Usage

```csharp
public void ProcessData(AsnReader reader) {
    AsnReader clone = new AsnReader(reader);

    while (clone.HasData) {
        ReadOnlyMemory<byte> value = clone.ReadEncodedValue();
        // Do something with the value
    }

    // The reader parameter has not been advanced
}
```

### Alternative Designs

This could be a `Copy` or `Clone` instance method, but my preference leans toward a new constructor.

**Comment by adamsitnik** [comment]
Creating a copy of a `class` to have a state that we can go back to seems a little bit unintuitive for me. As Jeremy wrote, we often do it for `struct`s, but for reference types I would expect to see sth like:

```cs
public class AsnReader
{
    public int Position { get; set; }
}
```

But this would require non trivial changes to the type itself (it's based on slicing as far as I can see). 

So the proposal LGTM ;)

**Comment by vcsjones** [comment]
> public int Position { get; set; }

One reason I like the current design, and not a position, is a `Position` would allow you to drop in to arbitrary locations = and since a SEQUENCE is also a an AsnReader, you might end up doing a lot of book keeping on the position.

Consider this ASN.1, in BER: `3005090380000A0101010101`

This is a SEQUENCE that contains a REAL with trailing data.

If I start reading it at Position 1, now all of the sudden it becomes an ASN.1 NULL (a weird one, but valid in BER).

The current design really doesn't let you do that, which I think is a good characteristic.

**Comment by adamsitnik** [comment]
> The current design really doesn't let you do that, which I think is a good characteristic.

👍

**Comment by terrajobst** [comment]
* Seems like a typed `Clone()` is easier to use

```C#
namespace System.Formats.Asn1;

public partial class AsnReader
{
    public AsnReader Clone();
}
```
