### ISSUE TITLE
NativeAOT stripped symbol files aren't loaded automatically in MacOS+lldb

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#86734]
Using the default (`StripSymbols` property is set to true) and publishing a `NativeAOT` application doesn't use the standalone `dwarf `symbol file. This was validated with `lldb`. 

Setting `StripSymbols` explicitly to false works with lldb correctly loading the symbols.

Possibly related to #86707 in some way.

**Comment by filipnavara** [comment]
I discussed this with @akoeplinger some time ago in a different context. The flat .dwarf files are unsupported and have to be loaded manually in `lldb`. The only format that is supported automatically is the dSYM bundle.

The final executable is assigned an UUID that can be printed with `xcrun dwarfdump --uuid <path-to-exe>`. You can then run `mdfind "com_apple_xcode_dsym_uuids == <uuid>` to locate the debug symbols. If it returns something it will work in `lldb`. The dSYM bundles are automatically indexed by Spotlight, so they don't even need to be next to the original executable.

**Comment by agocke** [comment]
Fixed by https://github.com/dotnet/runtime/pull/89358
