### ISSUE TITLE
ComInterfaceGenerator uses Diagnostic in incremental pipeline, which do not compare as equal in Roslyn

### ISSUE THREAD

**Issue by jtschuster** [dotnet/runtime#86736]
Diagnostics won't be incremental in the generator pipeline: https://github.com/dotnet/roslyn/issues/68291

Workaround is to create a DiagnosticTemplate record with all the information required to report the diagnostic, then build the diagnostic right before reporting it.

**Comment by jkoritzinsky** [comment]
We should fix this for LibraryImport at the same time.

**Comment by jtschuster** [comment]
fixed in https://github.com/dotnet/runtime/pull/86908
