### ISSUE TITLE
IsAssignableFrom returns false when cross different AssemblyLoadContexts

### ISSUE THREAD

**Issue by liesauer** [dotnet/runtime#86756]
### Description

`crossType` is exact the same type loaded from the same dll, but different `AssemblyLoadContext`.

`crossType.IsAssignableFrom(typeof(TestLib2))` returns `false`, does this is expected? for me, this should return `true`.

```csharp
using System;
using System.IO;
using System.Runtime.Loader;

namespace CrossALCType
{
    internal class Program
    {
        static void Main(string[] args)
        {
            if (typeof(TestLib).IsAssignableFrom(typeof(TestLib2)))
            {
                Console.WriteLine("same alc: yes");
            }
            else
            {
                Console.WriteLine("same alc: no");
            }

            var myContext = new AssemblyLoadContext("MyContext");

            var path = Path.GetDirectoryName(typeof(Program).Assembly.Location);

            var assembly = myContext.LoadFromAssemblyPath(path + "/TestLib.dll");

            var crossType = assembly.GetType("CrossALCType.TestLib");

            if (crossType.IsAssignableFrom(typeof(TestLib2)))
            {
                Console.WriteLine("cross alc: yes");
            }
            else
            {
                Console.WriteLine("cross alc: no");
            }

            Console.Write("");
        }
    }

    class TestLib2 : TestLib
    {
    }
}
```

`TestLib`

```csharp

using System;

namespace CrossALCType
{
    public class TestLib
    {
    }
}
```

### Reproduction Steps

[demo.zip](https://github.com/dotnet/runtime/files/11564602/demo.zip)

### Expected behavior

return `true`

### Actual behavior

return `false`

**Comment by jkotas** [comment]
> does this is expected? 

Yes, it is expected. The loading same .dll into two different assembly load contexts creates two unrelated set of type instances. It is documented at https://learn.microsoft.com/en-us/dotnet/core/dependency-loading/understanding-assemblyloadcontext#type-conversion-issues
 
If you would like to share some types between the two assembly load contexts, you may want to load the .dll with the shared types into the default assembly load context. Check the documentation at https://learn.microsoft.com/en-us/dotnet/core/dependency-loading/understanding-assemblyloadcontext#shared-dependencies and the plugin sample at https://learn.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support
