### ISSUE TITLE
[NativeAOT] How to export functions for executables?

### ISSUE THREAD

**Issue by LegendaryB** [dotnet/runtime#86788]
I found this Pull request which was merged in main: https://github.com/dotnet/runtime/pull/78738
Can somebody guide me how I would be able to export functions from my Console Application? I guess I just need to specify something in the csproj file but did not find any documentation regarding that. Anybody able to help?`

Kind Regards

**Comment by huoyaoyuan** [comment]
https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/interop#native-exports

**Comment by LegendaryB** [comment]
> https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/interop#native-exports

Thank you but I already read that. My method is decorated with the attribute and also the EntryPoint is not null

**Comment by Symbai** [comment]
There are a few limitations, if you have read that far:

https://github.com/dotnet/samples/blob/main/core/nativeaot/NativeLibrary/README.md#exporting-methods

Otherwise provide example code

**Comment by jkotas** [comment]
> I found this Pull request which was merged in main: #78738

You have to be on a .NET 8 preview build and you need to specify `<IlcExportUnmanagedEntrypoints>true</IlcExportUnmanagedEntrypoints>` property in your .csproj file.

Just curious - why do you need to export functions from the application?

**Comment by LegendaryB** [comment]
> > I found this Pull request which was merged in main: #78738
> 
> You have to be on a .NET 8 preview build and you need to specify `<IlcExportUnmanagedEntrypoints>true</IlcExportUnmanagedEntrypoints>` property in your .csproj file.
> 
> Just curious - why do you need to export functions from the application?

Thank you!
Was trying exactly that and was wondering why it did not work. Will try it out later when I have the time to get a .NET 8 preview build. 

I just wanted to play around with PE injection
