### ISSUE TITLE
LibraryImportGenerator should generate code using "global::"

### ISSUE THREAD

**Issue by Lightczx** [dotnet/runtime#86786]
### Description

When I have a extern method placed in a namespace contains `System`
(For example: when using it with CsWin32, we have a namespace called `Windows.Win32.System`)
The LibraryImport will place the generated code in the same namespace, thus it can't find:
```
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Interop.LibraryImportGenerator", "7.0.8.17405")]
[System.Runtime.CompilerServices.SkipLocalsInitAttribute]
```
and report several CS0234
Because there is no `Windows.Win32.System.CodeDom` and `Windows.Win32.System.Runtime`

**Comment by AaronRobinsonMSFT** [comment]
This should be an easy fix. Thanks @Lightczx for reporting it.
