### ISSUE TITLE
Provide Minimal JSON Escaping Implementation

### ISSUE THREAD

**Issue by davidmatson** [dotnet/runtime#86800]
There is no out-of-the-box implementation that does only the escaping required by the JSON RFC. See #86463 for mor details.

**Comment by eiriktsarpalis** [comment]
I've reopened #42847 to keep track of the original conversation, feel free to contribute to the conversation there.

**Comment by davidmatson** [comment]
I think the scope of #42847 is a bit different, as fixing that issue doesn't mean this one gets resolved. For example, supporting unescaped emoji doesn't necessarily mean doing the same for other non-BMP languages, private use characters, newly-defined Unicode code points, etc.

Can this issue be re-opened to keep track of the scope in its title?

**Comment by eiriktsarpalis** [comment]
I understand that, but I would recommend contributing to https://github.com/dotnet/runtime/issues/42847 towards defining a good proposal that suits your and other folks' usecases. Keeping $n$ open issues with minute variations of the same problem statement does not make it easy for maintainers to keep track of the backlog.

**Comment by eiriktsarpalis** [comment]
Done.

**Comment by davidmatson** [comment]
Thanks, @eiriktsarpalis!
