### ISSUE TITLE
Provide a runtime package through the store

### ISSUE THREAD

**Issue by TravisEz13** [dotnet/runtime#86808]
### Summary

Provide a runtime package through the store so that other store packages can be FDD

### Background

PowerShell should move to Framework Dependent Deployments, so that .NET runtime issues are automatically serviced and to reduce the package size of PowerShell.  Deploying via the store and MSIX seems like where we are encouraged to move this to for Windows.  So, we need the .NET Runtime to support this scenario.

**Comment by reflectronic** [comment]
See also: https://github.com/dotnet/runtime/issues/51574, https://github.com/dotnet/installer/issues/7725

**Comment by jkotas** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/51574
