### ISSUE TITLE
[browser][wasm-mt] Regression with asset loading, improper URL resolution for WebWorker file

### ISSUE THREAD

**Issue by IsaMorphic** [dotnet/runtime#86819]
### Description

Please see my comment on the commit containing the breaking change:
https://github.com/dotnet/runtime/commit/c6e435b135dab4254baee6e3d3d00672626a8838#r115203570

### Reproduction Steps

Use the latest successful build of dotnet installer and runtime with any Blazor project. Enable `WasmEnableThreads`.

### Expected behavior

Loading of runtime should complete successfully. 

### Actual behavior

`GET https://localhost:44370/dotnet.native.worker.8.0.0-preview.5.23272.14.hma21u2o3j.js 404`

### Regression?

I have linked the breaking change above.

### Known Workarounds

Manually moving the WebWorker script to the directory above `_framework`

**Comment by IsaMorphic** [comment]
@pavelsavara

**Comment by pavelsavara** [comment]
cc @maraf
