### ISSUE TITLE
GZipStream produces different results on Windows and Ubuntu

### ISSUE THREAD

**Issue by nth-commit** [dotnet/runtime#86824]
### Description

A string compressed via GZipStream on Windows does not produce the same result as if it were compressed on Ubuntu/Mac.

### Reproduction Steps

I've pushed up a repo with the minimal reproduction: https://github.com/nth-commit/GZipStreamRepro/blob/main/UnitTest1.cs

This action runs the tests on Windows/Ubuntu/Mac, and fails on the latter 2 (I produced the encodings on a Windows machine): https://github.com/nth-commit/GZipStreamRepro/actions/runs/5095988113

### Expected behavior

The encodings are the same. I can take a string encoded on Ubuntu and decode it on Windows.

### Actual behavior

The encodings are different.

### Regression?

I think this has been an issue for a while. Definitely on .NET 7, and I believe since at least .NET Standard 1.0.

### Known Workarounds

None.

### Configuration

.NET 7.0

**Comment by stephentoub** [comment]
> The encodings are the same.

This is not a guarantee. Different versions of zlib on different operating systems may compress differently.

>  I can take a string encoded on Ubuntu and decode it on Windows.

This should always work. Do you have an example where it doesn't?

**Comment by nth-commit** [comment]
Oh, interesting! Makes sense.

Yes, I have an example. The GitHub action run I linked shows my test passing on Windows but failing on Linux.

Ubuntu version:

>2023-05-27T00:26:36.5087231Z Ubuntu
2023-05-27T00:26:36.5087541Z 22.04.2
2023-05-27T00:26:36.5088086Z LTS

Windows version:

**Comment by stephentoub** [comment]
Yes. There are many different ways the same input data may be compressed, all of which result in valid gzip data.  All of them can be decompressed using any gzip implementation.

**Comment by nth-commit** [comment]
TIL. Thank you!

I'll close this.

**Comment by stephentoub** [comment]
Thanks.
