### ISSUE TITLE
string.Join with first element null status

### ISSUE THREAD

**Issue by miloush** [dotnet/runtime#86823]
Reference issue: https://github.com/dotnet/runtime/issues/5681 PR: https://github.com/dotnet/coreclr/pull/8114

What a debugging nightmare having this behave differently in net6.0 and net48 targets indeed!

@stephentoub said:

> As long as we port the fix back to desktop (under a quirk I guess, in particular since the behavior is documented) and fix the documentation, I'm ok with it.

It seems to me this breaking change has been sneaked in without fulfilling the stated conditions. https://learn.microsoft.com/en-us/dotnet/api/system.string.join?view=net-8.0#system-string-join(system-string-system-object()) still contains the remark and note for .NET 8.0 Preview 4 that empty string should be returned which it isn't, and targetting net481 still does return empty string. Has it been poretd back to desktop? If a quirk setting is available, it should be mentioned in the .NET Framework documentation as well.

**Comment by huoyaoyuan** [comment]
This should be a bug-to-bug compatibility for .NET Framework. It won't be fixed on .NET Framework, since all applications depends on this bug will be infected.

**Comment by miloush** [comment]
None of the issues mentions reversing the decision to backport the "fix". Either way the documentation should be fixed.

**Comment by stephentoub** [comment]
That discussion is from the earliest days of .NET Core, before we decided we were effectively not backporting anything.

**Comment by tannergooding** [comment]
As per the above, it was determined .NET Framework isn't getting new features like this.
