### ISSUE TITLE
could not able to install .net in rhel9 manually using "dotnet-sdk-6.0-6.0.116-2.el9.x86_64.rpm" file

### ISSUE THREAD

**Issue by jagadeswar-devarasetti-dsw** [dotnet/runtime#86831]
Hi 

i am having rhel9.1 server , i need to install dotnet in the server , 

I dont have access to internet in my server or my server did now whitelisted those so i cannot able to install .net using this command :
-> sudo dnf install dotnet-sdk-6.0

Repository packages-microsoft-com-prod is listed more than once in the configuration
Extra Packages for Enterprise Linux 9 - x86_64                                         0.0  B/s |   0  B     01:52
Errors during downloading metadata for repository 'epel':
  - Curl error (28): Timeout was reached for https://ftp.yz.yamagata-u.ac.jp/pub/linux/fedora-projects/epel/9/Everything/x86_64/repodata/repomd.xml [Failed to connect to ftp.yz.yamagata-u.ac.jp port 443: Connection timed out]
Error: Failed to download metadata for repo 'epel': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

so , i tried to download rpm file of dotnet "dotnet-sdk-6.0-6.0.116-2.el9.x86_64.rpm" 

and trying to install using below command but could able to install it . 

[root@VBKYGGHJ user_admin]# dnf install dotnet-sdk-6.0-6.0.116-2.el9.x86_64.rpm
Repository packages-microsoft-com-prod is listed more than once in the configuration
Extra Packages for Enterprise Linux 9 - x86_64                                         0.0  B/s |   0  B     01:52
Errors during downloading metadata for repository 'epel':
  - Curl error (28): Timeout was reached for https://ftp.yz.yamagata-u.ac.jp/pub/linux/fedora-projects/epel/9/Everything/x86_64/repodata/repomd.xml [Failed to connect to ftp.yz.yamagata-u.ac.jp port 443: Connection timed out]
Error: Failed to download metadata for repo 'epel': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

so i dont have access to internet or sites, how can i install .net manually in RHEL 9.1 using rpm files

please help me with your valuable suggestions

@jkotas @vitek-karas

**Comment by jkotas** [comment]
https://access.redhat.com/documentation/en-us/net/6.0/html/getting_started_with_.net_on_rhel_9/installing-dotnet_getting-started-with-dotnet-on-rhel-9 are the official supported steps for installing .NET 7 on rhel9.

@tmds Is manual install from rpm packages supported on rhel?

**Comment by jagadeswar-devarasetti-dsw** [comment]
Thanks @jkotas , 

I had tried to download tar.gz file from official
https://dotnet.microsoft.com/en-us/download/dotnet/6.0 site .

And ther extracted , export and set the path , and then sucessful able to run the dotnet in rhel9, without using internet access..

**Comment by tmds** [comment]
fyi, the offline install of the rpm didn't work because.NET is spilt over several packages. To install it offline, you need to download also the .NET runtime package and all other dependencies of the SDK package, and pass those files together to the install command.
