### ISSUE TITLE
[API Proposal]: ArgumentException.ThrowIfNullOrEmpty / ThrowIfNull / ThrowIfNullOrWhiteSpace with custom message

### ISSUE THREAD

**Issue by wcontayon** [dotnet/runtime#86833]
### Background and motivation

Sometimes, we may also need to provide a custom message for exception to better explain why we raise that exception.
I'm currently working on a PR [ArgumentException.ThrowIfNullOrWhitespace in AspNetCore](https://github.com/dotnet/aspnetcore/pull/48414) to use these classes. 
But we've found that we sometimes need to set a custom error message like this code below

https://github.com/dotnet/aspnetcore/blob/2a709351416d0ad85011805787dbdeaecb251b8f/src/Hosting/Hosting/src/Internal/HostingEnvironmentExtensions.cs#L70-L73

### API Proposal

```csharp
namespace System;

public class ArgumentException : SystemException
{
    public static void ThrowIfNullOrEmpty(string? argument, string? message = null, [CallerArgumentExpression(nameof(argument))] string? paramName = null)
    {
        ArgumentNullException.ThrowIfNull(argument, message, paramName);
        if (argument.Count == 0)
        {
            throw new ArgumentException(string.IsNullOrEmpty(message) : "value cannot be null or empty ..." : message, paramName);  
        }
    }

public static void ThrowIfNull(object? argument, string? message = null, [CallerArgumentExpression(nameof(argument))] string? paramName = null);

public static void ThrowIfNullOrWhiteSpace(string? argument, string? message = null, [CallerArgumentExpression(nameof(argument))] string? paramName = null);
}
```

### API Usage

```csharp
// Throw the exception with a custom message
var contentRootPath = string.Empty;
ArgumentException.ThrowIfNullOrEmpty(contentRootPath, "A valid non-empty content root must be provided ...", nameof(contentRootPath));
```

### Alternative Designs

N/C

### Risks

I dont think so as it well be an overload, no risk of regression 🙂

**Comment by stephentoub** [comment]
The more you put at the call site, the more work ends up being done even in the success case. It ends up being a pit of failure if folks do anything other than a constant to populate that message.

**Comment by wcontayon** [comment]
> The more you put at the call site, the more work ends up being done even in the success case. It ends up being a pit of failure if folks do anything other than a constant to populate that message, and in my experience, most of the cases where a custom message is supplied involve some kind of formatting, accessing of resource strings, etc

Understand the point.
However, I think it'll be useful to customize the message. `ArgumentException.ThrowIfNull` is a useful helper to reduce line and repeated code (null test, etc.), enable the option will best fit with cases where the message is not generic.

**Comment by danmoseley** [comment]
@wcontayon I don't think we'll do this. In the rare case where you need a custom message, you can do it the regular way. We can always take another look based on future feedback.
For the example you linked in aspnet, the parameter name does give a clue, which seems fine.
I'll close based on comments above. Thanks for suggesting though.
