### ISSUE TITLE
The thread "Tiered Compilation Woker" load my extra assembly.

### ISSUE THREAD

**Issue by hmisaki** [dotnet/runtime#86858]
The project platform is .Net Core 6.0. In my case, I have an app and two DLLs, `MrUi.dll` and `Mr.dll`. The  `MrUi.dll` will be loaded first, and the `MrUi.dll`  register the callback to AppDomain to watch the load `Mr.dll` assembly event. See code: 
```
Initialize(){ 
    AppDomain domain = AppDomain.CurrentDomain; 
    domain.AssemblyLoad += new AssemblyLoadEventHandler(domain_AssemblyLoad); 
} 
void domain_AssemblyLoad(object sender, AssemblyLoadEventArgs args) 
{ 
    AssemblyName aName = args.LoadedAssembly.GetName(); 
    if (string.Compare(aName.Name, "Mr", true) == 0) 
    { 
        ...do something... 
    } 
} 
```
 
In the usual case, we will load the `Mr.dll` in the main thread, but in some cases, the `Mr.dll` will be loaded by the Tiered Compilation Woker, which causes a Bug; some resources can't be accessed in this thread; refer to the stack screenshot: 
![image](https://github.com/dotnet/runtime/assets/23306796/3302b63b-484b-4e96-ad66-ab72a5149958)

Why can the Tiered Compilation Woker load my DLL?

**Comment by MichalStrehovsky** [comment]
The runtime can recompile your app to native code to generate better performing code. This compilation happens on a background thread. It looks like inlining triggered a new assembly to be loaded, so the callback was called on this compilation thread.

If your app is sensitive to which thread can handle the callback, you'll have to build your own mechanism to trigger the processing on the expected thread (e.g. post to a queue that is processed on the expected thread).

You can work around by disabling tiered compilation, but you'll not get the best possible performance: https://learn.microsoft.com/en-us/dotnet/core/runtime-config/compilation#tiered-compilation

**Comment by panxn** [comment]
Hi @MichalStrehovsky we can't disable tiered compilation, performance is important. We have many code depend on such behavior: do initialization work (thread-sensitive) in handler of [AssemblyLoad](https://learn.microsoft.com/en-us/dotnet/api/system.appdomain.assemblyload?view=net-7.0) before executing any code of the assembly.
Can I understand that this way is no longer safe in .NET6? Is there any way to prevent tiered compilation from loading assembly in its thread?

**Comment by MichalStrehovsky** [comment]
IIRC this callback will be called on whatever thread that first loads the assembly so if it wasn't hit before .NET 6 one could also attribute that to luck. There are many things that can trigger an assembly load.

**Comment by panxn** [comment]
Thank you! At least it works well in .NET framework age for many years, it sounds it's no longer reliable in .NET6.

**Comment by ShreyasJejurkar** [comment]
@MichalStrehovsky asking out of curiosity, can't we disable tiered compilation for that specific method or class via some attribute that way, so that the tiered compilation thread won't go inside that method to execute those things?

**Comment by vitek-karas** [comment]
I don't know if there's a way to disable tiered compilation per method, but I think that's just a workaround. The runtime doesn't make any guarantees from which thread the assembly resolution event handlers will be called, just like it doesn't make any guarantees that they won't be called simultaneously for the same input, or repeatedly for the same input. The assembly resolution handlers need to be thread safe and idempotent (same input gives same output).

I would strongly suggest against relying on any specific threading behavior with regard to this event handler, even if it happens to work, there's no guarantee it won't change in the future.

**Comment by jkotas** [comment]
> Can I understand that this way is no longer safe in .NET6? 

This was not safe even in .NET Framework. For example, you can hit this situation with finalizer thread in .NET Framework.

**Comment by panxn** [comment]
Could you please suggest a way to archive my goal `Do initialization work before executing any code in the assembly`? I hope it's under control, won't be accidentally triggered by Tiered Compilation or even Background JIT. I just tried [Module Initializers](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/module-initializers), it's still triggered by Tiered Compilation.

**Comment by panxn** [comment]
Hi @vitek-karas Thanks for your information.

I want to explain more about my problem. I usually write C++, what I expect is something like `DllMain` in C++ DLL. We can control/expect when and where a DLL gets loaded then `DllMain` gets called. It could happen in any thread as long as it's under control. The key point is programmers can control it. In .NET6, it becomes unpredictable because of Tiered Compilation or Background JIT(or maybe others).

I can't manually load assembly from main, we have many assemblies, this way hurts performance, assemblies should be loaded only if necessary.

Anyway I can understand .NET is different from native DLL, what I expect does not exist, we will investigate more to find a practical solution or just turn off Tiered Compilation. Thanks!
