### ISSUE TITLE
[8.0.100-preview.5.23276.4] After setting SocketsHttpHandler.AllowAutoRedirect property as false, the HttpResponseMessage.StatusCode changed from "Redirect" to "Found"

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/runtime#86857]
### Description

**When run the clashN with the latest .NET 8 Preview5 runtime, After setting SocketsHttpHandler.AllowAutoRedirect property as false, the HttpResponseMessage.StatusCode changed from "Redirect" to "Found"**
**GitHub Site**: https://github.com/2dust/clashN
**Or App Location checking at**: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1826703

### Reproduction Steps

**Minimal Repro steps (demo attached)**:
[ResponseCodeIssue.zip](https://github.com/dotnet/runtime/files/11590722/ResponseCodeIssue.zip)

**The machine only has 8.0.100-preview.5.23276.4 installed and set DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX environment variable as 2.**

1. Create a default console application.

2. Add following code in Program.cs file:

```
SocketsHttpHandler webRequestHandler = new SocketsHttpHandler
{
    AllowAutoRedirect = false,
};
HttpClient client = new HttpClient(webRequestHandler);
HttpResponseMessage response = await client.GetAsync("https://github.com/2dust/clashN/releases/latest");
Console.WriteLine(response.StatusCode.ToString());
```

3. Build the console app. 

4. Update the app's runtime.config file:
```
{
  "runtimeOptions": {
    "tfm": "net7.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "8.0.0-preview.5.23275.10"
    }
  }
}
```
5. Launch the app.

### Expected behavior

The console app will output "Redirect".

### Actual behavior

The console app outputs "Found".

### Regression?

Yes
**Verify Scenarios:**
1. Windows10 21h2 x64 + dotnet-sdk-8.0.100-preview.5.23269.37: Pass
2. Windows10 21h2 x64 + dotnet-sdk-8.0.100-preview.5.23273.2: Fail
3. Windows10 21h2 x64 + dotnet-sdk-8.0.100-preview.5.23276.4: Fail
4. Windows10 21h2 x64 + dotnet-sdk-6.0.117: Pass

### Configuration

Application Name: clashN 
OS: Windows10 21h2
CPU: x64

### Other information

**Findings:**
After setting SocketsHttpHandler.AllowAutoRedirect property as false, the response's StatusCode is changed from "Redirect" to "Found". If we set SocketsHttpHandler.AllowAutoRedirect property as true, the response's StatusCode is "OK" on both .NET 7 and .NET 8 Preview.5.23276.4

@dotnet-actwx-bot @dotnet/compat

**Comment by MihaZupan** [comment]
See "Notes to callers" section of [`Enum.ToString()`)](https://learn.microsoft.com/dotnet/api/system.enum.tostring#system-enum-tostring) docs:
> If multiple enumeration members have the same underlying value and you attempt to retrieve the string representation of an enumeration member's name based on its underlying value, your code should not make any assumptions about which name the method will return.

In this case `HttpStatusCode.Found` and `HttpStatusCode.Redirect` both share the value `302`. Which one `ToString()` will return is not guaranteed to be stable.

My guess is that #85841 changed the internal representation of the enum enough to cause the change.

**Comment by Junjun-zhao** [comment]
Thank you @MihaZupan for looking into this issue. We are in the validation of .NET 8 Preview 5.  Could you help confirm whether this issue is a blocker for .NET 8 Preview 5?

**Comment by Junjun-zhao** [comment]
Got it. Thank you @stephentoub . We will update the app owner about it.
