### ISSUE TITLE
PredefinedCulturesOnly=false not respected in new CultureInfo(int)

### ISSUE THREAD

**Issue by OwnageIsMagic** [dotnet/runtime#86878]
### Description

This creates issue for WinForms
https://github.com/dotnet/winforms/issues/9191#issuecomment-1567383463

see
https://github.com/dotnet/runtime/blob/182591af3ea67a09bca7e0516b950dafce71d5a6/src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs#L860-L872
and
https://github.com/dotnet/runtime/blob/182591af3ea67a09bca7e0516b950dafce71d5a6/src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs#L670-L682

### Reproduction Steps

`dotnet build /p:InvariantGlobalization=true /p:PredefinedCulturesOnly=false && dotnet run --no-build`
```c#
_ = new CultureInfo(1100);
```

### Expected behavior

Return Invariant culture.

### Actual behavior

Exception.

**Comment by tarekgh** [comment]
Why would you enable the invariant globalization mode for a WinForm app? I believe this is not the suitable environment for running WinForm apps for several reasons. Additionally, we generally discourage the use of LCID (Locale Identifier) as it is considered obsolete, and we try to avoid investing in outdated technologies. The appropriate course of action in this case is to disable the invariant mode for your WinForm apps.

**Comment by OwnageIsMagic** [comment]
I'm developing tool to convert data from one well defined format to another, and doesn't have any plans on localization. `InvariantGlobaliztion` helps me to ensure that I don't accidentally depend on current culture of my dev environment and saves me from scanning WinForms and other dependencies repos in case it does somewhere sets `CurrentCulture/CurrentUICulture/DefaultThreadCurrentCulture/DefaultThreadCurrentUICulture` or any other global property I'm not aware of.

Usage of this constructor is tied to what we get from `WM_INPUTLANGCHANGE` Win32 message.

Fix is trivial and will bring in consistency between constructor overloads.

```diff
      if (GlobalizationMode.Invariant)
      {
+          if (!GlobalizationMode.PredefinedCulturesOnly)
+          {
+               return Invariant;
+          }
          // LCID is not supported in the InvariantMode
          throw new CultureNotFoundException(nameof(culture), culture, SR.Argument_CultureNotSupportedInInvariantMode);
      }
```

**Comment by tarekgh** [comment]
@OwnageIsMagic thanks for the info. in your tool, who is creating the culture using the LCID? Is it your tool or WinFoms? If it is your tool, then you can just avoid creating the culture in the first place and use Invariant Culture. If it is WinForms, then you have something seriously wrong trying to use WinFomrs and expect it will handle the cultural operation correctly while you are enabling Invariant Globalization mode. 

> Fix is trivial

This is not the point; the point is we need to refrain users from using LCIDs in general. Helping fixing cases to support LCIDs will make it worse to obsolete such APIs moving forward.

**Comment by OwnageIsMagic** [comment]
@tarekgh the culture is created in WinForms as part of creating `EventArgs` for handling system broadcast message, it's not used internally, but it's a part of public api.
Issue can be worked around on WinForms side, but exception message links to this property as [documented](https://learn.microsoft.com/en-us/dotnet/core/runtime-config/globalization#predefined-cultures) workaround.
> the point is

In invariant mode LCID is actually unused and ignored, so I don't think that can be considered as support.

**Comment by tarekgh** [comment]
@OwnageIsMagic are you interested to submit a PR?
