### ISSUE TITLE
Fix AddMetrics extension method namespace

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#86885]
**edited by @tarekgh adding the proposal section**
### Description

MetricsServiceExtensions has the namespace `Microsoft.Extensions.Diagnostics.Metrics`.That isn't the standard namespace for extensions methods on `IServiceCollection`. The standard namespace is `Microsoft.Extensions.DependencyInjection`.

https://github.com/dotnet/runtime/blob/8154757175ead0854b9cf914bff87e03d352a4ce/src/libraries/Microsoft.Extensions.Diagnostics/src/Metrics/MetricsServiceExtensions.cs

For example, `Microsoft.Extensions.Http` correctly has `Microsoft.Extensions.DependencyInjection`: https://github.com/dotnet/runtime/blob/8154757175ead0854b9cf914bff87e03d352a4ce/src/libraries/Microsoft.Extensions.Http/src/DependencyInjection/HttpClientFactoryServiceCollectionExtensions.cs

## Proposal
```diff

- namespace Microsoft.Extensions.Diagnostics.Metrics
+ namespace Microsoft.Extensions.DependencyInjection
{
    public static class MetricsServiceExtensions
    {
        public static IServiceCollection AddMetrics(this IServiceCollection services)
    }
}
```

### Reproduction Steps

In an ASP.NET Core app, try to configure metrics with `AddMetrics(config)` extension method.

### Expected behavior

`AddMetrics` automatically shows up in intellisense like other `AddXXX` methods that are in the `Microsoft.Extensions.DependencyInjection` namespace. That namespace is automatically added in ASP.NET Core apps.

### Actual behavior

Not automatically visible with intellisense and `Microsoft.Extensions.Diagnostics.Metrics` needs to be added.

**Comment by JamesNK** [comment]
cc @tarekgh @noahfalk

**Comment by tarekgh** [comment]
> That isn't the standard namespace for extensions methods on IServiceCollection. The standard namespace is Microsoft.Extensions.DependencyInjection.

I don't think this is the case. We have other cases where we define the IServiceCollection extension methods in other namespaces. 

https://github.com/dotnet/runtime/blob/7d50edd1f85300dc0bbcd5df8f00a05c56c103c8/src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetimeHostBuilderExtensions.cs#L75

> Not automatically visible with intellisense and Microsoft.Extensions.Diagnostics.Metrics needs to be added.

I am wonder who is going to register the metrics APIs and not going to use the other APIs which require `icrosoft.Extensions.Diagnostics.Metrics` namespace anyway.

**Comment by JamesNK** [comment]
IMO APIs that aren't in this namespace are a mistake. It's the standard.

HttpClientFactory:
https://github.com/dotnet/runtime/blob/8154757175ead0854b9cf914bff87e03d352a4ce/src/libraries/Microsoft.Extensions.Http/src/DependencyInjection/HttpClientFactoryServiceCollectionExtensions.cs#L11

Logging: https://github.com/dotnet/runtime/blob/4d709cd12269fcbb3d0fccfb2515541944475954/src/libraries/Microsoft.Extensions.Logging/src/LoggingServiceCollectionExtensions.cs#L9

Options:
https://github.com/dotnet/runtime/blob/4d709cd12269fcbb3d0fccfb2515541944475954/src/libraries/Microsoft.Extensions.Options/src/OptionsServiceCollectionExtensions.cs#L10

Hosting:
https://github.com/dotnet/runtime/blob/4d709cd12269fcbb3d0fccfb2515541944475954/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/ServiceCollectionHostedServiceExtensions.cs#L9

**Comment by noahfalk** [comment]
I hadn't noticed that pattern before, but implicitly it does seem to be recognized in our public documentation https://learn.microsoft.com/en-us/dotnet/core/extensions/options-library-authors

"DO NOT use the Microsoft.Extensions.DependencyInjection namespace for non-official Microsoft packages" 

To me that implies official Microsoft packages do use this namespace as their pattern. The examples from James support that view. Unless we had a strong reason not to do it I would follow suit. I am a little surprised this didn't get flagged during BCL design review because it seems like the kind of naming consistency rule they would care about, but perhaps it was just missed.
