### ISSUE TITLE
StringBuilder and exception in stringinterpolation causes partial string to be written to builder

### ISSUE THREAD

**Issue by mathiasgormjensen** [dotnet/runtime#86897]
When executing something like this code, I would expect only line #1 and information about the exception to be present in the stringbuilder. But to my surprise line #2 has been partially added.
```
Func<string> someMethod = () => throw new Exception("Hello!");
StringBuilder builder = new StringBuilder();
try
{
	builder.AppendLine("Line #1: Before");
	builder.AppendLine($"Line #2: Value: {someMethod()}"); // expecting this entire line to fail
	builder.AppendLine("Line #3: After");
}
catch (Exception ex)
{
	// at this point we would expect the builder to contain only line #1 (because an exception occurred while appending line #2), but surprisingly it contains line #1 and "Line #2: Value: " and does not end with a newline
	builder.AppendLine($"Error: {ex.Message}");
}
```
The expected result is something like this:
```
Line #1: Before
Error: Hello!
```

The actual result is something like this:
```
Line #1: Before
Line #2: Value: Error: Hello!
```

This behavior seems to be specific to StringBuilder and I haven't noticed anywhere else where this happens.
Is this behavior intentional or a bug?

(BTW we can obviously easily work around the issue by adding ToString() at the end of the interpolation)

**Comment by stephentoub** [comment]
> Is this behavior intentional or a bug?

It is intentional.  There's no partial buffering being applied.  It's appending as it goes, and if you get an exception from one piece, all previously written pieces will remain.  This:
```C#
builder.AppendLine($"Line #2: Value: {someMethod()}"); // expecting this entire line to fail
```
will behave equivalently to:
```C#
builder.Append("Line #2: Value: ").Append(someMethod()).AppendLine();
```

**Comment by mathiasgormjensen** [comment]
The thing that bothers me is that this is not how StringBuilder works in .NET Framework and also not how similar classes such as Console works.
Is this behavior going to be used on other classes to, or will it remain StringBuilder-specifix?

**Comment by stephentoub** [comment]
It's how interpolated string handlers work.  It's not StringBuilder-specific.

**Comment by vcsjones** [comment]
> Is this behavior going to be used on other classes to, or will it remain StringBuilder-specific?

It can likely be observed any place that a `*InterpolatedStringHandler` is used. For example, this behavior can be reproduced with `Utf8`:

```C#
using System.Text;
using System.Text.Unicode;

Span<byte> buffer = stackalloc byte[200];
buffer.Fill(0x20);

static string ThrowPotato() => throw new Exception("Potato!");

try {
    Utf8.TryWrite(buffer, $"Hello {ThrowPotato()}", out _);
}
catch {
}

Console.WriteLine(Encoding.UTF8.GetString(buffer));
```

This will print "Hello" (and a bunch of whitespace) to the console.

**Comment by teo-tsirpanis** [comment]
See https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/stringbuilder-append-evaluation-order for more details about this breaking change. You can write `builder.AppendLine((string)$"Line #2: Value: {someMethod()}");` to revert to the previous behavior.

**Comment by Clockwork-Muse** [comment]
... Frankly, at the point you get an exception _while_ mutating an object's internal state, **ALL BETS ARE OFF**.  You should consider yourself to have **NO** guarantees about the actual state of the object.  You're lucky it's not actually corrupted to the point of crashing your application.

(As an aside, in this example you're also comingling normal output and error output, which seems problematic...)

**Comment by mathiasgormjensen** [comment]
> plied. It's appending as it goes, and if you get an exception from one piece, all previously written pieces will remain. This:

Thanks @teo-tsirpanis for the link which clearly indicates that Microsoft are aware of this and that it is intentional :)

**Comment by mathiasgormjensen** [comment]
@Clockwork-Muse, FYI the purpose of the sample was just to make it easy to reproduce and easy to see what the problem was. 

I'm curious would you also say "_all bets are off_" and "_no guarantees_", if the code looked like this:
`string value = "Line #2: Value: {someMethod()}";`
I assume you would never expect that to crash your application, right? :)

**Comment by mathiasgormjensen** [comment]
> It can likely be observed any place that a `*InterpolatedStringHandler` is used.

Thanks @vcsjones , I will keep my eyes open for InterpolatedStringHandler overloads :)

**Comment by Clockwork-Muse** [comment]
> I assume you would never expect that to crash your application, right? :)

Yes and no (there's any number of reasons such a call could or should crash my application).  But that's not the relevant problem.

The actual problem here is that you're mutating an object, and then using it after catching an exception that (potentially) occurred during a method call into it - the actual problem is the `builder.AppendLine(...)` call, not the creation of the interpolated string.  At that point, you don't have any guarantee what the internal state of the `builder` object is, which could be anything, including irrecoverably corrupted.

**Comment by mathiasgormjensen** [comment]
> The actual problem here is that you're mutating an object, and then using it after catching an exception that (potentially) occurred during a method call into it - the actual problem is the `builder.AppendLine(...)` call, not the creation of the interpolated string. At that point, you don't have any guarantee what the internal state of the `builder` object is, which could be anything, including irrecoverably corrupted.

OK, I get what you mean now. Writing to the builder as part of the catch was just for demonstration-purposes. I could just have well just have pointed out that the builder contained a partial string.

But you definitely have an point on the internal state of the builder. I don't think it's a problem with StringBuilder, but other implementations that takes an interpolated string as input and processes it piece by piece, may certainly enter a corrupt state if an exception occurs.

**Comment by Clockwork-Muse** [comment]
> I could just have well just have pointed out that the builder contained a partial string.

Yes.... but that's (recoverable, although that's not necessarily guaranteed) corrupted state.  It's _expected_ that it may not look like what you wanted.
