### ISSUE TITLE
[ComRegisterFunction]/[ComUnregisterFunction] decorated public static methods do not run during regsvr32 registration

### ISSUE THREAD

**Issue by rwasef1830** [dotnet/runtime#869]
Hello,
I have discovered that contrary to documentation in .NET Core, [ComRegisterFunction] and [ComUnregisterFunction] are not called by the COM registration system if they are not in a public class decorated by `[ComVisible(true)]` and a `[Guid(...)]` in the immediate assembly being registered.

See repo for a playground project:
https://github.com/rwasef1830/netcore31comregistrationbugs

In the playground project, building and attempting to register the comhost dll will cause the message box from the registration function inside the immediate main assembly to be called. The other one is ignored entirely, even if the main one is removed entirely.

2nd behavior: If you make the class containing the register/unregister functions non-public or removed the COM exposure attributes (ComVisible, Guid), the functions will get ignored entirely.

This is a breaking behavior from .NET Framework and contrary to advice that the registration functions should be internal. In addition regasm called com registration functions even in dependent assemblies, even if the enclosing classes were non-public and non-com-exposed.

Hope that clarifies it.

Migrated from https://github.com/dotnet/core-sdk/issues/5852
@AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
Appears to be a logical flaw when trying to discover the entry points.

https://github.com/dotnet/runtime/blob/be71bafdbe138fbf4c3f3e46b20679034e5826be/src/coreclr/src/System.Private.CoreLib/src/Internal/Runtime/InteropServices/ComActivator.cs#L145

It is unclear if loading of dependent assemblies is something I was not aware of.

**Comment by AaronRobinsonMSFT** [comment]
@rwasef1830 Really appreciate the reporting of this issue.

>This is a breaking behavior from .NET Framework and contrary to advice that the registration functions should be internal.

Agreed as a breaking change if the callbacks are defined on other types, but functions with the attribute can still be marked `internal` on the class in question so that guidance is still possible to adhere to. Enumerating all types in the assembly is definitely possible and something I will bring back since it is following the guidance and many people probably depend on that.

The dependent assembly loading I am still TBD on. I would like to know how many customers are impacted before bringing that back.

**Comment by jozefizso** [comment]
Support for COM registration functions defined in .NET code and executed by the comhost would be great.

We use them in MS Office Add-ins to automatically register the addin in the Office application. Eg:

https://github.com/NetOfficeFw/NetOffice/blob/releases/netoffice_v1.7.4/Examples/Word/C%23/IExtensibility%20COMAddin%20Examples/ClassicUI/Addin.cs#L97

**Comment by elinor-fung** [comment]
@jozefizso there is existing support for managed COM registration functions called by the comhost (added for #12627). However, they will currently only be called if they are directly on the type that is being registered. Are you hitting issues where registration functions directly on the type being registered are not called?

I believe the missing piece here is that the runtime does not walk up the base types of the class being registered to look for registration functions. 

From what I see, even in Framework, types had to be `ComVisible` to be registered. And registration functions on types in dependent assemblies would not be called unless the main assembly has a type that derives from the type in the dependent assemblies with those functions.

@rwasef1830 it sounds like you were seeing types in dependent assemblies being registered in Framework - do you have an example of that?

One thing to note is that there is a difference around how `ComVisible` is handled in Framework versus Core.
- In Framework, if there is no `ComVisible` attribute on the type or the assembly, the type will be registered.
- In Core, `ComVisible` and `Guid` attributes must explicitly be set on the type. Only types with those attributes set will be registered via the comhost.

**Comment by rwasef1830** [comment]
@elinor-fung old versions of https://github.com/dsafa/CSDeskBand that were targeting .NET Framework there was a com registration function in the nuget dll and it was called by regasm.

**Comment by elinor-fung** [comment]
Thanks! From the doc and samples on there, the expectation is that a consumer would create a class that inherits from the `CSDeskBandWin` or `CSDeskBandWpf` classes that are in the libraries in the NuGet package. Their registration functions would have been called based on the inheritance hierarchy, so updating the .NET Core runtime to properly look at the base types of the class being registered should cover that scenario.

**Comment by rwasef1830** [comment]
Seems you're right: https://github.com/dsafa/CSDeskBand/blob/76ffdf1be0a549410ed6688673fd982633cbcf8b/CSDeskBand.Wpf/CSDeskBandWpf.cs#L168

**Comment by jozefizso** [comment]
I added the **[ComRegisterFunction]** to my sample addin which is using .NET Core 3.1

https://github.com/NetOfficeFw/NetOffice/blob/dev/netoffice_v1.8/Examples/Word/C%23/NetCore%20Addin%20Examples/01%20Simple/WordAddin.cs#L59

When I call `regsvr32 /i SimpleNetCoreAddin.comhost.dll` I get the error:

```
---------------------------
RegSvr32
---------------------------
The module "SimpleNetCoreAddin.comhost.dll" was loaded but the entry-point DllInstall was not found.

Make sure that "SimpleNetCoreAddin.comhost.dll" is a valid DLL or OCX file and then try again.
---------------------------
OK   
---------------------------
```

![image](https://user-images.githubusercontent.com/287778/78063817-18198800-7391-11ea-9f0b-a363ca333c24.png)

**Comment by elinor-fung** [comment]
Ah, the comhost currently does not implement or support `DllInstall`. Since you are specifying the `/i` flag for `regsvr32`, it is trying to run both `DllInstall` and `DllRegisterServer`. Just running `regsvr32 SimpleNetCoreAddin.comhost.dll` should work and run the function attributed with `ComRegisterFunction`.

The optional install semantics of `regsvr32` aren't implemented since that isn't something that has ever been supported in .NET (Framework) and we don't have a mechanism for propagating any install commands to user code.

Are you relying on the install step (instead of just registering) for something?

**Comment by jozefizso** [comment]
I'm just used to call `regsvr32` with `/i` switch.

Yes, it works without the **/i** switch.
