### ISSUE TITLE
[browser][mt] Running any Thread for longer than 5000 ms crashes runtime (Blazor)

### ISSUE THREAD

**Issue by IsaMorphic** [dotnet/runtime#86903]
### Description

Spawning any long-running Task or Thread from the main thread for longer than 5000 ms kills application and runtime when using Blazor. 
![Screenshot 2023-05-29 182353](https://github.com/dotnet/runtime/assets/24303611/8562e465-5e17-4cdf-b357-78a9b3517a8b)

### Reproduction Steps

1. Create empty Blazor app and use current `main` build of runtime in project file
2. Use Task.Run, Thread.Start or async/await anywhere in the app with a long-running task (importantly, NOT Task.Yield or Task.Delay)
3. Observe the error and runtime crash. 

### Expected behavior

I should be able to start a task from anywhere on the main thread using Task.Run in a Blazor app and not have the runtime crash after 5000ms

### Actual behavior

Runtime crashes with error (screenshot above)

### Regression?

This previously worked perfectly on the official release build of .NET 8 Preview 4. 

### Known Workarounds

None

**Comment by IsaMorphic** [comment]
Most likely this change is the cause of the issue: #86278

**Comment by lambdageek** [comment]
@IsaMorphic Can you say a bit more about what's in the body of the long-running task?  Is it compute-intensive?  doing a synchronous call to JS that takes longer than 5 seconds? calling some native wasm code (like C code)?

In principle if the long-running task is just a compute loop in C# it should be trying to safepoint at backward branches in the loops... unless we're failing to emit the safepointing opcodes for some reason...

**Comment by IsaMorphic** [comment]
@lambdageek Of course. It is definitely a compute intensive task in .NET land. No interop is happening inside of it.

**Comment by pavelsavara** [comment]
This is GC trying to suspend a thread. Probably UI thread is unbalanced on GC state.

**Comment by pavelsavara** [comment]
@lambdageek is there way how to test safepoint with unit test ?

**Comment by lambdageek** [comment]
> @lambdageek is there way how to test safepoint with unit test ? 

Start a GC

**Comment by pavelsavara** [comment]
Create tight for loop and make sure it runs longer than `MONO_SLEEP_ABORT_LIMIT`. 
And start GC on the other thread, right ?
Could we do better ?

**Comment by IsaMorphic** [comment]
Any updates on this investigation / fix? I'm eagerly awaiting the moment that this bug is squashed, as I am building an app that heavily relies on this functionality!

**Comment by pavelsavara** [comment]
@IsaMorphic is it still possible to replicate with the latest build ?

You can try it with nightly build https://aka.ms/dotnet/9.0.1xx/daily/dotnet-sdk-win-x64.zip
