### ISSUE TITLE
TypeLoadException thrown from MetadataLoadContext should expose TypeName

### ISSUE THREAD

**Issue by IS4Code** [dotnet/runtime#86923]
### Description

When an instance of `TypeLoadException` is thrown from the custom reflection items formed by `MetadataLoadContext`, its `TypeName` property is an empty string (`""`). It would be expected for this property to work in a similar way as when the exception is thrown from normal assembly loading, as is shown in the [examples](https://learn.microsoft.com/en-us/dotnet/api/system.typeloadexception.typename?view=net-7.0#examples) for this property. Such a thing would be useful in situations where only the type name is required (for example when loading attributes on a member and comparing them by name) and so it does not matter that the full `Type` instance could not be provided, if the name was passed through `TypeLoadException.TypeName`.

### Reproduction Steps

```cs
var context = new MetadataLoadContext(new PathAssemblyResolver(new[] { typeof(object).Assembly.Location }), typeof(object).Assembly.GetName().FullName);
try{
    context.CoreAssembly.GetType("NonExistentType", true);
}catch(TypeLoadException tle)
{
    Console.WriteLine(tle.TypeName);
}
```

### Expected behavior

`NonExistentType` should be written, akin to the example for the property.

### Actual behavior

The code writes an empty line.

### Regression?

Seems to have been this way as early as 4.6.

### Known Workarounds

The name could be parsed from the exception message, but that is not optimal.

### Configuration

Version 8.0.0-preview.4.23259.5 of `System.Reflection.MetadataLoadContext`; .NET 7.0.

### Other information

The issue is probably somewhere [here](https://github.com/dotnet/runtime/blob/f2f3b092cbeb46eb5c50eebc1b29a7c7107c3482/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/Modules/Ecma/EcmaModule.GetTypeCore.cs#L62), where only the message is given to `TypeLoadException`.

**Comment by steveharter** [comment]
Closing; [the `TypeName` property](https://github.com/dotnet/runtime/blob/00874d6fdec31ec8ffec4d05b18eb849f1d4f1a0/src/libraries/System.Private.CoreLib/src/System/TypeLoadException.cs#L41) doesn't work unless the private constructor is called, or the `SerializationInfo` "TypeLoadClassName" is populated like shown above.

**Comment by IS4Code** [comment]
@steveharter I am sorry, I do not really understand how is this being completed. Will the `EcmaModule` class be fixed so that it throws the exception containing the information?
