### ISSUE TITLE
[8.0.100-preview.5.23276.4] Custom extended ToDictionary<TKey, TValue>() method conflicts with the one in System.Linq.Enumerable

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/runtime#86936]
### Description

In .NET 8.0.100-preview.5.23276.4, ToDictionary() extension method has parameterless definition, this conflicts with ToDictionary() custom extension method defined in paint.netcore app. It is caused by the app retarget to .NET 8.0 failed.

### Reproduction Steps

**Minimal Repro sample:**  Minimal repro sample [ConfilictIssueDemo.zip](https://github.com/dotnet/runtime/files/11610051/ConfilictIssueDemo.zip)

1. Create a default .net7.0 Console app named ConfilictIssueDemo
2. Add a CustomClass.cs with following code:
```
internal static class CustomClass
    {
        internal static Dictionary<TKey, TValue> ToDictionary<TKey, TValue>(this IEnumerable<(TKey, TValue)> items)
        where TKey : notnull
        {
            return new Dictionary<TKey, TValue>();
        }
    }
```
4. Add following code to Program.cs file:
```
using ConfilictIssueDemo; //if we remove this line, issue not repro, call custom extension method
internal class Program
{
    private static void Main(string[] args)
    {
        Dictionary<string, string> dict = new Dictionary<string, string>();
        dict.Add("aaa", "bbb");
        dict.Add("ccc", "ddd");
        var result = dict.Select(kvp => (kvp.Key, typeof(string).MakeGenericType(kvp.Value.GetType()))).ToDictionary();
    }
}
```
6. Build the project, it will build successfully.
7. Retarget the project to .NET 8:
```
 <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
```
9. Build the project.

### Expected behavior

Build successful.

### Actual behavior

Build failed with errors:
```
Error CS0121 The call is ambiguous between the following methods or properties: 'System.Linq.Enumerable.ToDictionary<TKey, TValue>(System.Collections.Generic.IEnumerable<(TKey Key, TValue Value)>)' and 'ConfilictIssueDemo.CustomClass.ToDictionary<TKey, TValue>(System.Collections.Generic.IEnumerable<(TKey, TValue)>)'

```

![image](https://github.com/dotnet/runtime/assets/83067197/7ebf2a5d-a956-4b79-aaa9-756fbcf98961)

### Regression?

Yes.

Verify Scenarios:
1).Windows 10 21H2 AMD64 + dotnet-sdk-8.0.100-preview.5.23276.4 + app (default 7.0): Pass
2). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.100-preview.5.23276.4 + app (retarget 8.0): Fail
3). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.100-preview.3.23178.7 + app (retarget 8.0): Pass

### Configuration

**Application Name**: paint.netcore
**OS**: Windows10 21h2
**CPU:** x64
**Application Source Location checking at:** https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1828268

### Other information

**Findings:**
1.If we change the ToDictionary method name to any other name in CustomClass.cs file, such as "ToCustomDictionary", the CS0121 error will go.
2. In .Net8, ToDictionary() extension method has parameterless definition, this conflicts with ToDictionary() custom extension method shown above. Following commits should be related to this change: [Add ToDictionary() overloads for KeyValuePair and ValueTuple kv. (#85… · dotnet/runtime@95c83fc · GitHub](https://github.com/dotnet/runtime/commit/95c83fc389cb1cf9618636da94106070eceda884)

@dotnet-actwx-bot @dotnet/compat

**Comment by Junjun-zhao** [comment]
This issue is found in the validation of .NET 8 Preview 5, could you help check and confirm whether this issue is a blocker for .NET 8 Preview 5?   Please help move to a right team if this is not correct.  Thanks.

**Comment by eiriktsarpalis** [comment]
Generally speaking, any new extension method that we ship risks conflicting with pre-existing user-defined extension methods which is a potential source breaking change. This has never prevented us from shipping new extension methods, so the recommendation here is to update the code to use the newly added extension method or rename the user-defined extension method.

cc @terrajobst @bartonjs

**Comment by Junjun-zhao** [comment]
@eiriktsarpalis  Thank you for your update. Is there a breaking change document for this change?

**Comment by stephentoub** [comment]
> Is there a breaking change document for this change?

No, we don't consider adding new methods to be breaking changes; we wouldn't be able to evolve any type if we were unable to add new methods to it.
