### ISSUE TITLE
is there any way to that vs 2022 exists using vswhere although i dont install it

### ISSUE THREAD

**Issue by NCLnclNCL** [dotnet/runtime#86947]
i think vswhere check it in regedit, i need vs2022 to build native aot but i only need c++, i can copy them exactly the folders needed to compile native aot, but if i uninstall vs2022 i cant compile  can be translated

**Comment by Clockwork-Muse** [comment]
If you don't want the full editor (for whatever reason), check if the [build tools](https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2022) will suffice.

**Comment by MichalStrehovsky** [comment]
The only supported route is if you have VS properly installed.

You can specify `<IlcUseEnvironmentalTools>true</IlcUseEnvironmentalTools>` to avoid running VSWhere but you need to ensure link.exe and all the other requirements are on PATH and in the environment variables. This configuration is unsupported.

**Comment by NCLnclNCL** [comment]
> 

i build 1 other where to return path of vs2022
