### ISSUE TITLE
DotNetBuildFromSource fail to compile src/libraries/shims/System.Data/ref/System.Data.csproj

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#86946]
Our internal CI builds have been failing since mid May (d0740fc967d8b3a9b215a24ca0a007a9602a9fa9 working, d7a30ba1f1c9ccce26a6a223898b7b9aba186a3a failing).

The build error is:
```
/Microsoft.Common.CurrentVersion.targets(2353,5): error MSB3106: Assembly strong name "/home/tester/.nuget/packages/system.data.sqlclient/4.8.5/ref/net6.0/System.Data.SqlClient.dll" is either a path which could not be found or it is a full assembly name which is badly formed. If it is a full assembly name it may contain characters that need to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quote("), Apostrophe('), Backslash(\). [/home/tester/runtime/src/libraries/shims/System.Data/ref/System.Data.csproj]
```
I've extracted the `System.Data.SqlClient 4.8.5` package from nuget.org. There is no `ref/net6.0` present.

I can reproduce the failure locally when running the build with (`DotNetBuildFromSource`).

@ViktorHofer this probably regressed by https://github.com/dotnet/runtime/pull/84782.

cc @omajid

**Comment by ViktorHofer** [comment]
@MichaelSimons can you please help here? Based on this report, when doing a source build without using Arcade powered source build, the SBRP package isn't picked up. Is that correct?

**Comment by MichaelSimons** [comment]
> @MichaelSimons can you please help here? Based on this report, when doing a source build without using Arcade powered source build, the SBRP package isn't picked up. Is that correct?

That is correct.  ARPOW pulls in the intermediates into the local package cache prior to the build so that they get used instead of pulling packages from other nuget feeds in scope.

**Comment by tmds** [comment]
I find it useful to be able to build this repo with a source-build configuration, and without going through Arcade.

> If yes, is there a way to differentiate between the two modes via an msbuild property?

Yes, we can use `ArcadeBuildFromSource` for this.

**Comment by tmds** [comment]
> I find it useful to be able to build this repo with a source-build configuration, and without going through Arcade.

To make more clear what I mean:

```
./build.sh  clr+libs+libs.tests -rc release -lc debug --test
```

When you add `/p:DotNetBuildFromSource=true` to this command, it will do what you expect.

If you add `--sb` to use ARPOW, it builds what source-build needs. That is different from the specified subset, and no tests are built or run.
