### ISSUE TITLE
[wasm] WBT: Blazor tests failing to find `dotnet.native*js`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#86959]
[Rolling build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=290839&view=results), and [log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-dc209a0a22354b9a81/Workloads-Wasm.Build.Tests.Blazor.MiscTests/1/console.6596521f.log?helixlogtype=result):

```
Wasm.Build.Tests.Blazor.MiscTests.NativeBuild_WithDeployOnBuild_UsedByVS(config: "Debug", nativeRelink: True) [FAIL]
  Could not find blazor's dotnet*js in /root/helix/work/workitem/e/wbt/blz_deploy_on_build_Debug_True_3qgnfzb3.rrw/bin/Debug/net8.0/publish/wwwroot/_framework
```

Also noticed the output path in the build log was different:
```
   []   blz_deploy_on_build_Debug_True_3qgnfzb3.rrw -> /root/helix/work/workitem/e/wbt/blz_deploy_on_build_Debug_True_3qgnfzb3.rrw/obj/Debug/net8.0/browser-wasm/PubTmp/Out/
```

cc @maraf @pavelsavara

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step).

```json
{
  "ErrorPattern": "Could not find blazor's dotnet\*js .*_framework",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[291252](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291252)|dotnet/runtime|[Wasm.Build.Tests.Blazor.MiscTests.NativeBuild_WithDeployOnBuild_UsedByVS](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291252&view=ms.vss-test-web.build-test-results-tab&runId=5835310&resultId=100067)|dotnet/runtime#86501|
|[291200](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291200)|dotnet/runtime|[Wasm.Build.Tests.Blazor.MiscTests.NativeBuild_WithDeployOnBuild_UsedByVS](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291200&view=ms.vss-test-web.build-test-results-tab&runId=5833984&resultId=100068)|dotnet/runtime#86722|
|[291150](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291150)|dotnet/runtime|[Wasm.Build.Tests.Blazor.MiscTests.NativeBuild_WithDeployOnBuild_UsedByVS](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291150&view=ms.vss-test-web.build-test-results-tab&runId=5832838&resultId=100067)|dotnet/runtime#86892|
|[291098](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291098)|dotnet/runtime|[Wasm.Build.Tests.Blazor.MiscTests.NativeBuild_WithDeployOnBuild_UsedByVS](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291098&view=ms.vss-test-web.build-test-results-tab&runId=5831760&resultId=100068)|dotnet/runtime#86954|
|[291071](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291071)|dotnet/runtime|[Wasm.Build.Tests.Blazor.MiscTests.NativeBuild_WithDeployOnBuild_UsedByVS](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291071&view=ms.vss-test-web.build-test-results-tab&runId=5830740&resultId=100067)|dotnet/runtime#86652|
|[291031](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291031)|dotnet/runtime|[Wasm.Build.Tests.Blazor.MiscTests.NativeBuild_WithDeployOnBuild_UsedByVS](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291031&view=ms.vss-test-web.build-test-results-tab&runId=5829826&resultId=100067)|dotnet/runtime#86951|
|[291026](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291026)|dotnet/runtime|[Wasm.Build.Tests.Blazor.MiscTests.NativeBuild_WithDeployOnBuild_UsedByVS](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291026&view=ms.vss-test-web.build-test-results-tab&runId=5829550&resultId=100067)|dotnet/runtime#86698|
|[291010](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291010)|dotnet/runtime|[Wasm.Build.Tests.Blazor.MiscTests.NativeBuild_WithDeployOnBuild_UsedByVS](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291010&view=ms.vss-test-web.build-test-results-tab&runId=5829002&resultId=100068)|dotnet/runtime#86048|
|[290889](https://dev.azure.com/dnceng-public/public/_build/results?buildId=290889)|dotnet/runtime|[Wasm.Build.Tests.Blazor.MiscTests.NativeBuild_WithDeployOnBuild_UsedByVS](https://dev.azure.com/dnceng-public/public/_build/results?buildId=290889&view=ms.vss-test-web.build-test-results-tab&runId=5824836&resultId=100067)|dotnet/runtime#86941|
|[290839](https://dev.azure.com/dnceng-public/public/_build/results?buildId=290839)|dotnet/runtime|[Wasm.Build.Tests.Blazor.MiscTests.NativeBuild_WithDeployOnBuild_UsedByVS](https://dev.azure.com/dnceng-public/public/_build/results?buildId=290839&view=ms.vss-test-web.build-test-results-tab&runId=5822692&resultId=100067)||
|[290763](https://dev.azure.com/dnceng-public/public/_build/results?buildId=290763)|dotnet/runtime|[Wasm.Build.Tests.Blazor.MiscTests.NativeBuild_WithDeployOnBuild_UsedByVS](https://dev.azure.com/dnceng-public/public/_build/results?buildId=290763&view=ms.vss-test-web.build-test-results-tab&runId=5820494&resultId=100067)|dotnet/runtime#85558|
|[290681](https://dev.azure.com/dnceng-public/public/_build/results?buildId=290681)|dotnet/runtime|[Wasm.Build.Tests.Blazor.MiscTests.NativeBuild_WithDeployOnBuild_UsedByVS](https://dev.azure.com/dnceng-public/public/_build/results?buildId=290681&view=ms.vss-test-web.build-test-results-tab&runId=5818862&resultId=100068)|dotnet/runtime#86928|
|[290651](https://dev.azure.com/dnceng-public/public/_build/results?buildId=290651)|dotnet/runtime|[Wasm.Build.Tests.Blazor.MiscTests.NativeBuild_WithDeployOnBuild_UsedByVS](https://dev.azure.com/dnceng-public/public/_build/results?buildId=290651&view=ms.vss-test-web.build-test-results-tab&runId=5818030&resultId=100068)|dotnet/runtime#84512|
|[290451](https://dev.azure.com/dnceng-public/public/_build/results?buildId=290451)|dotnet/runtime|[Wasm.Build.Tests.Blazor.MiscTests.NativeBuild_WithDeployOnBuild_UsedByVS](https://dev.azure.com/dnceng-public/public/_build/results?buildId=290451&view=ms.vss-test-web.build-test-results-tab&runId=5813446&resultId=100067)|dotnet/runtime#86928|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|14|14|

**Comment by radical** [comment]
This is due to https://github.com/dotnet/sdk/pull/31829 - change in fingerprinting, and the test is expecting a fingerprint.

**Comment by hoyosjs** [comment]
@radical, what's the error string here? to unblock current PRs

**Comment by radical** [comment]
> @radical, what's the error string here? to unblock current PRs

`Could not find blazor's dotnet*js .*_framework` - I have updated the known-build-error json too.
