### ISSUE TITLE
[RyuJIT] Integer Promotion Elimination on GT_CAST

### ISSUE THREAD

**Issue by fiigii** [dotnet/runtime#8695]
According to VTune characterization, [TryGetAsciiString](https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Kestrel.Core/Internal/Infrastructure/StringUtilities.cs#L8) is one of the hot functions in the TechEmpower-Plaintext scenario.  

This function reads ASCII characters (byte) and converts them to `char`.
```csharp
public static unsafe bool TryGetAsciiString(byte* input, char* output, int count)
{
    var i = 0;
    sbyte* signedInput = (sbyte*)input;

    bool isValid = true;
    while (i < count - 11)
    {
        ......
        *(output) = (char)*(signedInput);
        ......
    }
    ......
    return isValid;
}
```
The statement ` *(output) = (char)*(signedInput);` will be compiled to IL:
```
IL_000b: ldarg.1
IL_000c: ldloc.1
IL_000d: ldind.i1
IL_000e: conv.u2
IL_000f: stind.i2
```
Then compiled by RyuJIT to:
```asm
movsx r11, byte ptr [rcx]    ;; ldind.i1                                                                                                                            
movzx r11d, r11w             ;; conv.u2                                                                                                                
mov word ptr [rdx], r11w     ;; stind.i2                                                                                                                             
```
As we can see, `movzx r11d, r11w` is useless in this case because the intermediate result (char) has been properly promoted by previous operations (guaranteed by IL semantics) and the following usage operation is a truncation. So this kind of integer promotion could be safely removed.

I will look into providing an optimization.

category:cq
theme:basic-cq
skill-level:intermediate
cost:medium

**Comment by TIHan** [comment]
Closing as the JIT currently does not emit the unnecessary `movzx` anymore:
```
TryGetAsciiString(Byte*, Char*, Int32)
    add r8d, 0xfffffff5
    test r8d, r8d
    jle short L0012
    movsx rax, byte ptr [rcx]
    mov [rdx], ax
    jmp short L0009
    mov eax, 1
    ret
```
