### ISSUE TITLE
Frequent WebSocket Compression Segfault

### ISSUE THREAD

**Issue by QuinnDamerell** [dotnet/runtime#86960]
### Description

I run a service that heavily uses WebSockets, with anywhere from 3-8k concurrent WebSockets connections per server. These are long-lived connections; most are from 12 hours to a few days. I enabled websocket compression because size and latency is essential for my application, but I have been getting a super frequent crash due to it.

I'm running Ubuntu server 22.04 with the most up-to-date MS package repo versions of dotnet 7.0, aspnet, etc. My service uses the WebSocket class directly; I'm not using any middleware for handling the streams. I have around eight server running, and I see about 1-3 crashes per server per day due to this bug. 

Please let me know if I can provide any more helpful debugging information. I'm able to attach lldb and wait for a segfault, so I can gather any other info needed.

### Reproduction Steps

Set up an aspnet server that accepts websockets and enable web socket compression. Run the server as normal, allowing messages to be sent on the WebSocket and sockets to come and go. Eventually, the dotnet process will segfault, with this stack:

```
OS Thread Id: 0x4242a (212)
        Child SP               IP Call Site
00007F2BDD7F9038 00007f2c4d07f401 [InlinedCallFrame: 00007f2bdd7f9038] Interop+ZLib.Deflate(ZStream*, FlushCode)
00007F2BDD7F9038 00007f6c8109b576 [InlinedCallFrame: 00007f2bdd7f9038] Interop+ZLib.Deflate(ZStream*, FlushCode)
00007F2BDD7F9030 00007F6C8109B576 System.Net.WebSockets.Compression.WebSocketDeflater.Deflate(ZLibStreamHandle, FlushCode)
00007F2BDD7F90C0 00007F6C810F4458 System.Net.WebSockets.Compression.WebSocketDeflater.UnsafeFlush(System.Span`1<Byte>, Boolean ByRef)
00007F2BDD7F90F0 00007F6C810F4268 System.Net.WebSockets.Compression.WebSocketDeflater.DeflatePrivate(System.ReadOnlySpan`1<Byte>, System.Span`1<Byte>, Boolean, Int32 ByRef, Int32 ByRef, Boolean ByRef)
00007F2BDD7F9140 00007F6C810F4012 System.Net.WebSockets.Compression.WebSocketDeflater.Deflate(System.ReadOnlySpan`1<Byte>, Boolean)
00007F2BDD7F91C0 00007F6C80BCBD17 System.Net.WebSockets.ManagedWebSocket.WriteFrameToSendBuffer(MessageOpcode, Boolean, Boolean, System.ReadOnlySpan`1<Byte>)
00007F2BDD7F9210 00007F6C80BCB3C8 System.Net.WebSockets.ManagedWebSocket+<SendFrameFallbackAsync>d__58.MoveNext()
00007F2BDD7F9310 00007F6C80BCB0C7 System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.Net.WebSockets.ManagedWebSocket+<SendFrameFallbackAsync>d__58, System.Net.WebSockets]](<SendFrameFallbackAsync>d__58 ByRef)
00007F2BDD7F9350 00007F6C80BCAFE4 System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync(MessageOpcode, Boolean, Boolean, System.ReadOnlyMemory`1<Byte>, System.Threading.Tasks.Task, System.Threading.CancellationToken)
00007F2BDD7F9400 00007F6C80BCAB52 System.Net.WebSockets.ManagedWebSocket.SendAsync(System.ReadOnlyMemory`1<Byte>, System.Net.WebSockets.WebSocketMessageType, System.Net.WebSockets.WebSocketMessageFlags, System.Threading.CancellationToken)
...
<service specific code that's writing to the websocket>
```

### Expected behavior

The dotnet process shouldn't crash; at a minimum, it should throw a managed exception.

### Actual behavior

After some time of my service running, the process segfaults with the stack above.

### Regression?

This has been happening for a while, I'm not sure when it started, but it's been at least a few months.

### Known Workarounds

None. :(

### Configuration

Latest dotnet and aspnet packages from the Microsoft package repo for Ubunut Jammy. I also have the most up-to-date system packages.

dotnet sdk 7.0.302
dotnet runtime 7.0.5
aspnet 7.0.5
Ubuntu 22.04.2 LTS (Jammy Jellyfish), x64.

**Comment by CarnaViire** [comment]
Thanks a lot for the report @QuinnDamerell!
Does the issue only show under the load?
Do you own only server side, or client side as well? The crash is happening exclusively upon _writing_ to a buffer?
Would it be possible for you to create an isolated repro?

**Comment by QuinnDamerell** [comment]
@CarnaViire, thanks for the questions. My WS impl only acts as the server for my connections, so for my service, this only happens for the server side of the WS connection. I'm unsure if the error only occurs under load due to the nature of the crash. It happens on more used servers, but that could be because the code is used more. It is hard to say if the crash is more likely when the server is more in use, which follows a daily cycle pattern.

I was trying to make an isolate repo, but I couldn't get it happening. Since my service handles ~100 websocket connects/disconnected an hour with thousands of messages, it's not super likely to crash, but it does crash around 2-3 times a day.

Sorry, that's not very helpful; let me know if there's anything else I can get you that would be more helpful.

**Comment by zlatanov** [comment]
@QuinnDamerell did the errors started occurring as soon as you started using compression or sometimes later? 

A few other things that might help narrow the issue down are:
1. Are you using custom window bits? If yes, which?
2. Are you disabling context takeover or is it enabled as it is by default?
3. How big are the messages being sent?
4. Are you sending the messages as multiple frames?

**Comment by QuinnDamerell** [comment]
@zlatanov yeah, the errors only happen when compression is enabled. I have had it enabled for a while.

To your other questions:

1. I don't think so, I'm not setting anything like that on the WebSocket object.
2. I don't set the context takeover either, so I assume it's at the default value.
3. The messages can be quite large. I multiplex many things over the WS, including file transfers. The files can be upwards of 2GB, so I try to chunk the messages to be quite large for throughput. The system can send single WebSocket messages upwards of 500KB.
4. I assume the large messages are getting broken up internally by the WS, so I think yes?

Let me know if I can help with anything else!

**Comment by QuinnDamerell** [comment]
Here's the code snippet I use for websocket accept.

var ws = await m_context.WebSockets.AcceptWebSocketAsync(new WebSocketAcceptContext() { DangerousEnableCompression = true });

**Comment by zlatanov** [comment]
@QuinnDamerell Sorry for the confusion, I meant whether you've had compression enabled for longer time and only recently started getting errors. Or did the errors start as soon as you've enabled it?

**Comment by zlatanov** [comment]
Also, internally the websocket doesn't partition messages. If you give it a buffer of 2GB it will try and send it as a single message. I guess, when you say that you mutliplex files, you are buffering yourself and you're using a certain buffer size? If so, can you let me know what it is.

**Comment by QuinnDamerell** [comment]
@zlatanov no problem. I have had compression enabled for a long time and have seen this crash. So it's been a long time, and I think I have seen this crash for about as long as it's been enabled.

That's interesting about the message size. I'm serializing HTTP calls to the WebSocket and multiplexing possibly multiple calls at once. My max buffer size for a single websocket send is 500 kilobytes, but often messages are smaller. For the file transfers, I buffer up to 500kb reading from the HTTP body and then send it down the websocket.

**Comment by zlatanov** [comment]
If you don't have any sensitive data, would you mind getting a memory dump when the segfault occurs? If you can't share it, I can try to guide you for what exactly we're looking for so you can inspect the memory dump yourself.

Also, would it be possible for you to try and disable context takeover to see if the error would stop occurring? To do this, you should do the following:

```c#
var ws = await m_context.WebSockets.AcceptWebSocketAsync(new WebSocketAcceptContext() 
{ 
    DangerousEnableCompression = true,
    DisableServerContextTakeover = true
});
```

**Comment by QuinnDamerell** [comment]
Sure, I can try to capture a dump for you. I don’t have luck getting system coredumps, is there a way from lldb to dump when it segfaults?

I will also try disabling the server take over and see what happens.

**Comment by zlatanov** [comment]
You don't need lldb for this. You can enable core dumps and the operating system will do this for you. For this to happen though, you need to make sure the maximum allowed file size for core dumps is big enough or unrestricted. You can check the current limit like this:

```bash
ulimit -c
```

If the core file size limit is set to 0, core dumps are disabled. Enable them with:

```bash
ulimit -c unlimited
```

I think by default dumps are saved in the directory of the running process. However, it depends on `/proc/sys/kernel/core_pattern`. You can check it, to see if something is set there and where it is.

**Comment by wfurt** [comment]
make sure you also set `coredump_filter`
https://github.com/dotnet/diagnostics/blob/main/documentation/FAQ.md
Without it the dump may not have al the details.

**Comment by QuinnDamerell** [comment]
@zlatanov I don't know what I'm doing wrong, but I never get core dumps to work for some reason. I have tried all kinds of stuff, and I never get them in the path I set. But I will try again to see if I can get them working. If I get a crash dump, is there a good way to send it to you?

It seems that `DisableServerContextTakeover  = True` might have improved things, but I'm still getting 2-3 crashes a day on my more busy servers.

**Comment by zlatanov** [comment]
> @zlatanov I don't know what I'm doing wrong, but I never get core dumps to work for some reason. I have tried all kinds of stuff, and I never get them in the path I set. But I will try again to see if I can get them working. If I get a crash dump, is there a good way to send it to you?
> 
> It seems that `DisableServerContextTakeover = True` might have improved things, but I'm still getting 2-3 crashes a day on my more busy servers.

I've followed you on twitter. DM me and we can take this conversation there. If you do not wish to use twitter for this, I can send you a message through your website?

**Comment by CarnaViire** [comment]
Triage: this is something we need to investigate and fix in 8.0.

Thanks a lot for helping out @zlatanov! It would be awesome if you could also keep us in the loop. I'll drop you an email @QuinnDamerell @zlatanov so we could chat offline.

**Comment by zlatanov** [comment]
I've received privately another dump (thanks Sarah) and although it didn't contain enough information about the `System.Net.WebSockets` assembly for some reason, I was able to dump the memory layouts for objects near the faulting instruction.

I think I found the culprit and it isn't the deflate. This is the memory layout for the WebSocketDeflator which is causing the segfault:
```
7f7347307bd0 System.Net.WebSockets!Unknown (MethodTable: 7fb327387778)
============ 40 bytes
00007f73`47307bd0  78 77 38 27 b3 7f 00 00-00 00 00 00 00 00 00 00  xw8'............
00007f73`47307be0  a0 a8 52 41 73 7f 00 00-f4 ff ff ff 01 00 00 00  ..RAs...........
00007f73`47307bf0  01 00 00 00 00 00 00 00   
```

The `f4 ff ff ff` indicates that it has been created with window bits = 12. The value before it is a pointer to the buffer we're using internally to compress the data to `7f734152a8a0` and is 1MB, but this at the moment is irrelevant. The interesting part is that there seems to be missing the pointer which should point to the current zlib stream. This can only happen if the compression has already been completed and we're not persisting the stream or the deflator has been disposed.

We know, since the data pointer is not zeroes, that the object is doing a compression at the moment. This leaves only the possibility that the stream got disposed in the middle of a compression operation.

And indeed, this can happen if the WebSocket is disposed while there is an inflight Send operation (the deflator will be corrupted) or an inflight Receive operation (the inflator will be corrupted then).

https://github.com/dotnet/runtime/blob/2e764d6eb092fc8f05c42e6f137347c3eab45fd0/src/libraries/System.Net.WebSockets/src/System/Net/WebSockets/ManagedWebSocket.cs#L208-L224

We aren't locking the StateUpdateLock when inflating/deflating data and since Dispose() or Abort() can be and are allowed to be called concurrently, we need to take measures.

@CarnaViire @stephentoub please let me know what you think, and I will submit a PR to address the issue.

**Comment by sossee2** [comment]
I'm not sure if this is the same issue but we are getting a System.AccessViolationException when using compression on the client side. 

* The issue is rare but does cause a crash which is a big problem for us. In the last 7 days since turning on compression it has happened twice in production despite the application having ~200 connections per instance and ~20 instances currently running. 
* Call Stack 1:
```
CoreCLR Version: 7.0.423.11508
.NET Version: 7.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at Interop+ZLib.Inflate(ZStream*, FlushCode)
   at Interop+ZLib.Inflate(ZStream*, FlushCode)
   at System.Net.WebSockets.Compression.WebSocketInflater.Inflate(ZLibStreamHandle, System.Span`1<Byte>, FlushCode)
   at System.Net.WebSockets.Compression.WebSocketInflater.Inflate(System.Span`1<Byte>, Int32 ByRef)
   at System.Net.WebSockets.ManagedWebSocket+<ReceiveAsyncPrivate>d__63`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)

``` 
* Call stack 2
```
CoreCLR Version: 7.0.423.11508
.NET Version: 7.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at Interop+ZLib.InflateEnd(ZStream*)
   at Interop+ZLib.InflateEnd(ZStream*)
   at System.IO.Compression.ZLibNative+ZLibStreamHandle.InflateEnd()
   at System.IO.Compression.ZLibNative+ZLibStreamHandle.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalRelease(Boolean)
   at System.Net.WebSockets.ManagedWebSocket.DisposeCore()
   at System.Net.WebSockets.ManagedWebSocket.Dispose()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)

``` 
* I have a minidump from windows but would need a way to securely share it. 
* We are running on 64 bit windows 2022

**Comment by zlatanov** [comment]
@sossee2 I am 100% sure it is the same issue. Given that you have access violation with different callstacks and one of them originates from Dispose only confirms it.

I will prepare a PR today, however it's up to the .NET runtime team to decide whether it will be ported back to .NET 7. There really isn't a workaround for it.

**Comment by CarnaViire** [comment]
Thanks a lot for catching this @zlatanov!

**Comment by QuinnDamerell** [comment]
Great! Sorry, I haven't been able to help; I have been slammed. If you make a change that might fix the crash, I'm happy to test a private build!

**Comment by QuinnDamerell** [comment]
Amazing! When will this be in the official SDK? dotnet 8 or will it make it into dotnet 7? @CarnaViire

**Comment by CarnaViire** [comment]
It will definitely be in .NET 8 (and I believe even starting from Preview7 already?), however, while we might backport it to .NET 7, we decided to postpone it until there would be more reports.

**Comment by QuinnDamerell** [comment]
Wonderful, I will make a note to re-enable compression when I upgrade to dotnet 8!
