### ISSUE TITLE
ConfigurationBuilder is not parsing boolean params without an explicit declaration 

### ISSUE THREAD

**Issue by pollau** [dotnet/runtime#86977]
### Describe the bug

Once a ConfigurationBuilder is created with the command line 
```
IConfigurationRoot config = new ConfigurationBuilder()
                    .AddCommandLine(args)
                    .Build();
```

The boolean params such as `--my-feature` are not loaded to the configuration. The [`Command-line configuration provider`](https://learn.microsoft.com/en-us/dotnet/core/extensions/configuration-providers#command-line-configuration-provider) is working with key value pair and do not detect the boolean param unless the value is specified `--my-feature=true` 
The System.CommandLine parser (and I guess all CLI parsers) is considering that the value for `--my-feature` is true as long as the param is set in the CLI. 

### To Reproduce

```
IConfigurationRoot config = new ConfigurationBuilder()
    .AddCommandLine(new string[] { "--my-feature" })
    .Build();

var value = config.GetValue(typeof(bool), "my-feature");
Console.WriteLine($"Config value: {value}"); //Config value: 

IConfigurationRoot explicitConfig = new ConfigurationBuilder()
    .AddCommandLine(new string[] { "--my-feature=true" })
    .Build();

var explicitValue = explicitConfig.GetValue(typeof(bool), "my-feature");
Console.WriteLine($"Explicit config value: {explicitValue}"); //Explicit config value: true
```

**Comment by tarekgh** [comment]
The current configuration is not designed to have the default Boolean value. The configuration always assumes you need to provide key-value pairs to make it work. 
https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.commandlineconfigurationextensions.addcommandline?view=dotnet-plat-ext-7.0

It is trivial to work around this by providing value. This is something we can consider in the future if we see a demand for this feature. Thanks for your report.
