### ISSUE TITLE
maybe create WASM module export from `[UnmanagedCallersOnly]`

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#86985]
UnmanagedCallersOnly symbols could create exports in  the wasm module.  Particularly if they are not resolved statically in the rest of the build.

**Comment by jkotas** [comment]
cc @yowl

**Comment by lewing** [comment]
Support was added for this in https://github.com/dotnet/runtime/pull/94615 but there is an interpreter bug that complicates calling the export.
