### ISSUE TITLE
Explicit static interface implementation compiles but program crashes with "Fatal error" with .NET 7

### ISSUE THREAD

**Issue by frankbuckley** [dotnet/runtime#86993]
### Description

Explicit static interface implementation compiles but program crashes with "Fatal error"

### Reproduction Steps

```c#
using System;
using System.Numerics;

Console.WriteLine(new Int32Value(1));

public interface IValue<TSelf, T> : IModulusOperators<TSelf, TSelf, int>
    where T : struct
    where TSelf : IValue<TSelf, T>
{
    static int IModulusOperators<TSelf, TSelf, int>.operator %(TSelf left, TSelf right) => 0;
}

public readonly record struct Int32Value(int Value) : IValue<Int32Value, int>;
```

### Expected behavior

Program executes successfully, printing "Int32Value { Value = 1 }"

### Actual behavior

Crashes with "Fatal error"

### Regression?

Fails on 7.0.5 - does not compile with previous versions.

Does **not** fail on 8.0.0-preview.4.23259.5

### Known Workarounds

No known workaround

### Configuration

Tested 7.0.5 and 8.0.0-preview.4.23259.5 on win10-x64 (10.0.22631)

### Other information

Could be duplicate/related to #85159 and #79603.

Thanks @bradwilson for [pointing out this was not an Xunit issue](https://github.com/xunit/visualstudio.xunit/issues/376#issuecomment-1570706106).

This code crashes Xunit on test discovery.

It would seem it is fixed in 8.0 but it would be nice if the fix could be backported as the bug severely limits the usefulness of static interface implementations in supported platform versions.

**Comment by mangod9** [comment]
hi @frankbuckley, since this doesnt repro on 8 previews, are you wondering whether the fix would be ported to 7?

**Comment by frankbuckley** [comment]
Hi @mangod9 - that was my request, but we've moved this project to 8 previews so it is no longer an issue for us.
