### ISSUE TITLE
GlobalInstanceTrackerSupportTests_TargetUnix failing

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#86990]
We don't run the Windows version of this test due to the Windows version being attributed as `IsManagedCOMClient`. So Linux only.

```
        BEGIN EXECUTION
        /home/michals/runtime/src/tests/Common/scripts/nativeaottest.sh /home/michals/runtime/artifacts/tests/coreclr/linux.x64.Checked/Interop/COM/ComWrappers/GlobalInstance/GlobalInstanceTrackerSupportTests_TargetUnix/ GlobalInstanceTrackerSupportTests_TargetUnix.dll ''
        Running ValidateRegisterForTrackerSupport...
        Running ValidateNotifyEndOfReferenceTrackingOnThread...
        Test Failure: Xunit.Sdk.EqualException: Assert.Equal() Failure
        Expected: -1
        Actual:   0
           at Xunit.Assert.Equal[T](T, T, IEqualityComparer`1) + 0x177
           at ComWrappersTests.GlobalInstance.Program.Main() + 0x90
        Expected: 100
        Actual: 101
        END EXECUTION - FAILED
```

**Comment by MichalStrehovsky** [comment]
@jkoritzinsky @AaronRobinsonMSFT how much of ComWrappers support in NAOT are we comfortable with not working in .NET 8? Wondering if we should push this to 9.0 since we probably shipped like this in 7.0. I assume CsWinRT would be the main customer for this but I don't know if they have any more plans for this in 8.0 timeframe.

**Comment by AaronRobinsonMSFT** [comment]
@MichalStrehovsky @manodasanW and other in the CsWinRT world are taking one last effort on this area. They are trying to have something by mid-next week. After that I agree we can push this off to .NET 9.

/cc @Sergio0694

**Comment by AaronRobinsonMSFT** [comment]
With https://github.com/dotnet/runtime/pull/90283, this seems to work, yay. Thanks @manodasanW!
