### ISSUE TITLE
Build method of ConfigurationBuilder taking too much time while initializing pods under kubernetes

### ISSUE THREAD

**Issue by otwinservices** [dotnet/runtime#87018]
I am calling Build method of ConfigurationBuilder to initialize & build globalSettings of application for IHostBuilder but we have found that it is taking too much time to build. This is happening only when we are deploying application under pods in kubernetes cluster.

I suspect either it is something to do with kestrel hosting or somehow this build is taking time. It is random and sometimes taking more than 15 or 30 minutes to get the build done. Due to this my pod readiness is failing and ultimately leading unavailability of application for long time.

This is working fine when we are deploying this under windows operating system iis.

**Comment by tarekgh** [comment]
@otwinservices 
Agree this seems a hosting/environment issue if it occurs randomly. But this is not actionable till we get some perf traces to look at. Is it possible you can collect the perf traces when the issue occurs and share it?

**Comment by otwinservices** [comment]
public IConfigurationRoot Build()
        {
            var providers = new List<IConfigurationProvider>();
            foreach (IConfigurationSource source in Sources)
            {
                IConfigurationProvider provider = source.Build(this);
                providers.Add(provider);
            }
            return new ConfigurationRoot(providers);
        }

Above is taking time. Problem is we have tested same application in multiple EKS and happening in few EKS only, rest at all places it is working properly.

**Comment by tarekgh** [comment]
@otwinservices this issue is not actionable to us till we get either a solid repro or a perf dump we can investigate. We cannot speculate the providers used there and the environment that causes the problem. Please try to provide more information to make this issue actionable. Thanks!

**Comment by otwinservices** [comment]
Give me sometime, i will try to get performance dump from linux

**Comment by davidfowl** [comment]
@otwinservices What makes you think it's that code? Are you profiling? Are you using keyvault or another external configuration provider?

**Comment by tmds** [comment]
Does your base image have `DOTNET_USE_POLLING_FILE_WATCHER` set?
If not, does setting it make a difference?
(see https://github.com/dotnet/runtime/issues/68322)

**Comment by otwinservices** [comment]
Thanks @tmds, it works. I have gone through the post and got the issue understanding. Thanks a lot for your help.

**Comment by tmds** [comment]
@otwinservices happy to hear that fixed the issue.

Are you using one of the Microsoft provided .NET base images?
