### ISSUE TITLE
TagList.GetEnumerator() allocates

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#87022]
There was an overlook in #56940. `TagList.GetEnumerator()` returns an `IEnumerator<KeyValuePair<string, object?>>` instead of `TagList.Enumerator` which leads to boxing:

https://github.com/dotnet/runtime/blob/125b216c3918c76c6dbdf45d47212ea91623e5a2/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/TagList.cs#L407

There is no way to fix this without introducing a breaking change. I'm opening the issue, so we have awareness. As a workaround, we can recommend using `for` loops instead of `foreach` loops in code that iterates over `TagList`.

**Comment by stephentoub** [comment]
Do we know how this slipped through api review and coding and pr review and all the way to shipping?

**Comment by HypsyNZ** [comment]
> Do we know how this slipped through api review and coding and pr review and all the way to shipping?

Because you care about your circle jerk more than quality?

**Comment by tommcdon** [comment]
@tarekgh please take a look

**Comment by tarekgh** [comment]
> Do we know how this slipped through api review and coding and pr review and all the way to shipping?

This was slipped in the implementation (my mistake) and not in the design review. Unfortunately, this will be a breaking change if we want to fix it. I already talked offline with @antonfirsov and he was going to use `for` instead of `foreach` to avoid the allocation. 

 @stephentoub do you have any suggestion can fix this without a breaking change?

**Comment by stephentoub** [comment]
> This was slipped in the implementation (my mistake) and not in the design review

FWIW, it shows up in the API proposal as well:
https://github.com/dotnet/runtime/issues/56936
```C#
public  readonly IEnumerator< KeyValuePair<string, object?>> GetEnumerator() { throw null; }
```
so we all missed it apparently.

> do you have any suggestion can fix this without a breaking change?

Nope.  It's a binary breaking change to fix it.  We don't really have any recourse right now.

**Comment by cakescience** [comment]
> FWIW, it shows up in the API proposal as well:

Yes but not in the approved API https://github.com/dotnet/runtime/issues/56936#issuecomment-898594175. Any chance to fix this issue for .NET 8 even if it's a binary breaking change or it is not possible/acceptable?
