### ISSUE TITLE
dotnet 7.0.4 (iOS): NullReferenceException in Socket-related code (originating from Http2Connection disposal)

### ISSUE THREAD

**Issue by knocte** [dotnet/runtime#87031]
### Describe the bug
The problem seems to be a crash caused by an unhandled NullReferenceException that seems to originate in the .NET BCL itself (not in our code), as demonstraded by the stacktrace.

### To Reproduce

I'm sorry that I cannot provide proper steps to reproduce, because I actually was not the one running into this crash myself. However, given that I got a full report about the crash in my Sentry account, and the stacktrace looks very clear (in the sense that it looks clear enough for the bug to be easily fixed), so I thought I should file the bug.

### Exceptions (if any)
```
System.NullReferenceException: Object reference not set to an instance of an object
  ?, in int Dictionary<Error, SocketError>.Initialize(int)
  ?, in new Dictionary<Error, SocketError>(int, IEqualityComparer<Error>) x 2
  ?, in static SocketErrorPal()
System.TypeInitializationException: TypeInitialization_Type, System.Net.Sockets.SocketErrorPal
  ?, in SocketError SocketErrorPal.GetSocketErrorForNativeError(Error)
  ?, in SocketError SocketPal.GetSocketErrorForErrorCode(Error)
  ?, in SocketError SafeSocketHandle.DoCloseHandle(bool)
  ?, in bool SafeSocketHandle.CloseHandle(bool, bool)
  ?, in void SafeSocketHandle.CloseAsIs(bool)
  ?, in void Socket.Dispose(bool) x 2
  ?, in void Socket.Close(int)
  ?, in void NetworkStream.Dispose(bool)
  ?, in void Stream.Close()
  ?, in void Stream.Dispose()
  ?, in void Http2Connection.FinalTeardown()
  ?, in void Http2Connection.Dispose()
  ?, in void <>c.<CleanCacheAndDisposeIfUnused>b__120_3(?)+(HttpConnectionBase) => { }
  ?, in void List<HttpConnectionBase>.ForEach(Action<HttpConnectionBase>)
  ?, in void <>c.<CleanCacheAndDisposeIfUnused>b__120_0(?)+(object) => { }
  ?, in void Task.ExecuteWithThreadLocal(ref Task, Thread)
```

### Further technical details
- .NET 7.0.4

Here's the screenshot of the crash-info in our Sentry account:
<img width="1424" alt="Screenshot 2023-05-04 at 12 38 42 PM" src="https://user-images.githubusercontent.com/331303/236113663-95fac072-8202-4ccb-8daa-d89f0789a87f.png">

**Comment by karelz** [comment]
@vitek-karas can you please help with triage?

**Comment by vitek-karas** [comment]
@simonrozsival could you please take a quick look if this is something we should address? (and if it's even actionable)

**Comment by simonrozsival** [comment]
I don't see anything we could do just based on this report. The `Dictionary.Initialize` method is straightforward and it's not clear what went wrong and how to reproduce the issue.

@knocte has this exception happened just this once or has it been happening frequently?

**Comment by knocte** [comment]
I think we can close this because I haven't seen it again. Plus, I remember at the time I surfed into the Base Class Libraries to find where exactly a NRE could happen, and didn't find any place, so I assume it was a runtime issue.
