### ISSUE TITLE
[API Proposal]: `JsonConverterAttribute<T>`

### ISSUE THREAD

**Issue by just-ero** [dotnet/runtime#87047]
### Background and motivation

Today, we are able to specify a `JsonConverterAttribute` on types, properties, and fields. This attribute must be used in the following way:
```cs
class MyConverter : JsonConverter<MyClass> { /* */ }

[JsonConverter(typeof(MyConverter))]
class MyClass { }
```
With the addition of generic attributes in .NET 7 / C# 11, this should no longer be necessary.

### API Proposal

```cs
namespace System.Text.Json.Serialization;

[AttributeUsage(AttributeTargets.Class | AttributeTargets.Interface | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Property | AttributeTargets.Field, AllowMultiple = false)]
public class JsonConverterAttribute<TConverter> : JsonAttribute
    where TConverter : JsonConverter
{ }
```

### API Usage

```cs
class MyConverter : JsonConverter<MyClass> { /* */ }

[JsonConverter<MyConverter>]
class MyClass { }
```

### Risks

Perhaps this could raise some ambiguity issues between the non-generic `JsonConverterAttribute` and this new generic definition?

**Comment by eiriktsarpalis** [comment]
I believe this has been requested in the past (but couldn't find the relevant issue). We don't think this adds a lot of value since:

1. It doesn't provide many benefits from a type safety perspective, since it can't guarantee that the converter type matches the annotated members.
2. Generic attributes are not supported by all .NET languages.
3. A generic attribute can be defined trivially in user code.

Not closing the issue, since we might eventually decide to add it.

**Comment by huoyaoyuan** [comment]
There is still some difference between generic attribute and types in attribute. For example:

```csharp
[GenericAttribute<G<>>] // not allowed, only generic instantiates are supported
[Attribyte(typeof(G<>))] // allowed!
```

I'm not sure whether the following usage is supported by STJ, but it's a valid pattern:
```csharp
[JsonConverter(XConverter<>)] // we have no access to the generic argument of X here
class X<T>
{
}
```

**Comment by Sergio0694** [comment]
I agree that it doesn't add much benefit here. Especially if you're using the source generators, where the generated code will already generate the actual constructor calls to the annotated converter type, so it's not like you'd be getting any performance benefit either. And any additional warning, like if you used a converter type that is incompatible or invalid (say, an open generic type), the source generator can detect it anyway and emit a diagnostic as well. I mean I understand the appeal of leveraging the type system for this kind of things (eg. making open generic types an error right at the language level), but this seems like it would really not add much gain, and it would instead add another attribute type which increases cognitive load for users 🤔

**Comment by Khitiara** [comment]
> I believe this has been requested in the past (but couldn't find the relevant issue). We don't think this adds a lot of value since:
The relevant past issue is [72936](https://github.com/dotnet/runtime/issues/72936) fyi

**Comment by eiriktsarpalis** [comment]
Thanks, I think we can close this one then.
