### ISSUE TITLE
[mono][dbg] EvaluateConstantValueUsingRuntimeEvaluate test crash on Chrome

### ISSUE THREAD

**Issue by jandupej** [dotnet/runtime#87053]
Example log: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-86035-merge-267c39529af64ea9a4/chrome-DebuggerTests.EvaluateOnCallFrame2Tests/1/console.2eb806f3.log?helixlogtype=result

```
OpenSession crashing. proxy state: RunLoopExitState { reason = Exception, exception = System.IO.IOException: Process for /root/helix/work/correlation/chrome-linux/chrome unexpectedly exited with 127 during startup.
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=293517
Build error leg or test failing: chrome-DebuggerTests.EvaluateOnCallFrame2Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/86035

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step).

```json
{
  "ErrorMessage": "/root/helix/work/correlation/chrome-linux/chrome unexpectedly exited with 127 during startup",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[333866](https://dev.azure.com/dnceng-public/public/_build/results?buildId=333866)|dotnet/runtime|[chrome-DebuggerTests.CallFunctionOnTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=333866&view=ms.vss-test-web.build-test-results-tab&runId=6913792&resultId=100297)|dotnet/runtime#88387|
|[333453](https://dev.azure.com/dnceng-public/public/_build/results?buildId=333453)|dotnet/runtime|[chrome-DebuggerTests.CallFunctionOnTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=333453&view=ms.vss-test-web.build-test-results-tab&runId=6902826&resultId=100297)|dotnet/runtime#88594|
|[332849](https://dev.azure.com/dnceng-public/public/_build/results?buildId=332849)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=332849&view=ms.vss-test-web.build-test-results-tab&runId=6884034&resultId=100296)||
|[332270](https://dev.azure.com/dnceng-public/public/_build/results?buildId=332270)|dotnet/runtime|[chrome-DebuggerTests.DelegateTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=332270&view=ms.vss-test-web.build-test-results-tab&runId=6866194&resultId=100297)|dotnet/runtime#88245|
|[329880](https://dev.azure.com/dnceng-public/public/_build/results?buildId=329880)|dotnet/runtime|[chrome-DebuggerTests.BreakpointTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=329880&view=ms.vss-test-web.build-test-results-tab&runId=6805726&resultId=100270)|dotnet/runtime#88436|
|[329278](https://dev.azure.com/dnceng-public/public/_build/results?buildId=329278)|dotnet/runtime|[chrome-DebuggerTests.SetVariableValueTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=329278&view=ms.vss-test-web.build-test-results-tab&runId=6791642&resultId=100295)|dotnet/runtime#88397|
|[328418](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328418)|dotnet/runtime|[chrome-DebuggerTests.AssignmentTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328418&view=ms.vss-test-web.build-test-results-tab&runId=6786768&resultId=100298)|dotnet/runtime#88346|
|[328839](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328839)|dotnet/runtime|[chrome-DebuggerTests.CustomViewTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328839&view=ms.vss-test-web.build-test-results-tab&runId=6781558&resultId=100309)|dotnet/runtime#88373|
|[328360](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328360)|dotnet/runtime|[chrome-DebuggerTests.GetPropertiesTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328360&view=ms.vss-test-web.build-test-results-tab&runId=6770880&resultId=100298)|dotnet/runtime#88322|
|[328288](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328288)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrame2Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328288&view=ms.vss-test-web.build-test-results-tab&runId=6769488&resultId=100309)|dotnet/runtime#88075|
|[327950](https://dev.azure.com/dnceng-public/public/_build/results?buildId=327950)|dotnet/runtime|[chrome-DebuggerTests.SetVariableValueTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=327950&view=ms.vss-test-web.build-test-results-tab&runId=6759798&resultId=100298)||
|[327245](https://dev.azure.com/dnceng-public/public/_build/results?buildId=327245)|dotnet/runtime|[chrome-DebuggerTests.AsyncTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=327245&view=ms.vss-test-web.build-test-results-tab&runId=6738454&resultId=100298)|dotnet/runtime#88052|
|[325362](https://dev.azure.com/dnceng-public/public/_build/results?buildId=325362)|dotnet/runtime|[chrome-DebuggerTests.PointerTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=325362&view=ms.vss-test-web.build-test-results-tab&runId=6689640&resultId=100298)|dotnet/runtime#88006|
|[325309](https://dev.azure.com/dnceng-public/public/_build/results?buildId=325309)|dotnet/runtime|[chrome-DebuggerTests.GetPropertiesTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=325309&view=ms.vss-test-web.build-test-results-tab&runId=6688628&resultId=100298)|dotnet/runtime#88201|
|[323566](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323566)|dotnet/runtime|[chrome-DebuggerTests.HotReloadTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323566&view=ms.vss-test-web.build-test-results-tab&runId=6647770&resultId=100270)|dotnet/runtime#88125|
|[323413](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323413)|dotnet/runtime|[chrome-DebuggerTests.BreakpointTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323413&view=ms.vss-test-web.build-test-results-tab&runId=6642596&resultId=100277)|dotnet/runtime#88052|
|[322878](https://dev.azure.com/dnceng-public/public/_build/results?buildId=322878)|dotnet/runtime|[chrome-DebuggerTests.SetVariableValueTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=322878&view=ms.vss-test-web.build-test-results-tab&runId=6629560&resultId=100298)|dotnet/runtime#88075|
|[322756](https://dev.azure.com/dnceng-public/public/_build/results?buildId=322756)|dotnet/runtime|[chrome-DebuggerTests.PointerTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=322756&view=ms.vss-test-web.build-test-results-tab&runId=6626386&resultId=100298)|dotnet/runtime#86255|
|[318419](https://dev.azure.com/dnceng-public/public/_build/results?buildId=318419)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=318419&view=ms.vss-test-web.build-test-results-tab&runId=6607450&resultId=100279)|dotnet/runtime#86255|
|[321475](https://dev.azure.com/dnceng-public/public/_build/results?buildId=321475)|dotnet/runtime|[chrome-DebuggerTests.CallFunctionOnTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=321475&view=ms.vss-test-web.build-test-results-tab&runId=6594208&resultId=100298)|dotnet/runtime#87774|
|[321080](https://dev.azure.com/dnceng-public/public/_build/results?buildId=321080)|dotnet/runtime|[chrome-DebuggerTests.SteppingTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=321080&view=ms.vss-test-web.build-test-results-tab&runId=6585814&resultId=100320)|dotnet/runtime#87774|
|[321041](https://dev.azure.com/dnceng-public/public/_build/results?buildId=321041)|dotnet/runtime|[chrome-DebuggerTests.SteppingTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=321041&view=ms.vss-test-web.build-test-results-tab&runId=6584944&resultId=100318)|dotnet/runtime#87284|
|[320852](https://dev.azure.com/dnceng-public/public/_build/results?buildId=320852)|dotnet/runtime|[chrome-DebuggerTests.SteppingTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=320852&view=ms.vss-test-web.build-test-results-tab&runId=6582280&resultId=100298)|dotnet/runtime#86982|
|[320189](https://dev.azure.com/dnceng-public/public/_build/results?buildId=320189)|dotnet/runtime|[chrome-DebuggerTests.CallFunctionOnTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=320189&view=ms.vss-test-web.build-test-results-tab&runId=6564500&resultId=100298)|dotnet/runtime#88006|
|[317553](https://dev.azure.com/dnceng-public/public/_build/results?buildId=317553)|dotnet/runtime|[chrome-DebuggerTests.CallFunctionOnTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=317553&view=ms.vss-test-web.build-test-results-tab&runId=6509108&resultId=100298)||
|[317194](https://dev.azure.com/dnceng-public/public/_build/results?buildId=317194)|dotnet/runtime|[chrome-DebuggerTests.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=317194&view=ms.vss-test-web.build-test-results-tab&runId=6501002&resultId=100294)||
|[317013](https://dev.azure.com/dnceng-public/public/_build/results?buildId=317013)|dotnet/runtime|[chrome-DebuggerTests.SetNextIpTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=317013&view=ms.vss-test-web.build-test-results-tab&runId=6498384&resultId=100298)|dotnet/runtime#87522|
|[316113](https://dev.azure.com/dnceng-public/public/_build/results?buildId=316113)|dotnet/runtime|[chrome-DebuggerTests.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=316113&view=ms.vss-test-web.build-test-results-tab&runId=6479004&resultId=100298)|dotnet/runtime#87672|
|[314362](https://dev.azure.com/dnceng-public/public/_build/results?buildId=314362)|dotnet/runtime|[chrome-DebuggerTests.SteppingTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=314362&view=ms.vss-test-web.build-test-results-tab&runId=6437728&resultId=100298)|dotnet/runtime#85558|
|[314090](https://dev.azure.com/dnceng-public/public/_build/results?buildId=314090)|dotnet/runtime|[chrome-DebuggerTests.GetPropertiesTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=314090&view=ms.vss-test-web.build-test-results-tab&runId=6430716&resultId=100298)|dotnet/runtime#86911|
|[313210](https://dev.azure.com/dnceng-public/public/_build/results?buildId=313210)|dotnet/runtime|[chrome-DebuggerTests.SetVariableValueTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=313210&view=ms.vss-test-web.build-test-results-tab&runId=6408974&resultId=100298)|dotnet/runtime#87190|
|[313143](https://dev.azure.com/dnceng-public/public/_build/results?buildId=313143)|dotnet/runtime|[chrome-DebuggerTests.BreakpointTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=313143&view=ms.vss-test-web.build-test-results-tab&runId=6406878&resultId=100285)|dotnet/runtime#87044|
|[313047](https://dev.azure.com/dnceng-public/public/_build/results?buildId=313047)|dotnet/runtime|[DebuggerTests.EvaluateOnCallFrameTests.DebuggerTests.EvaluateOnCallFrameTests.EvaluateTypeInstanceMembers](https://dev.azure.com/dnceng-public/public/_build/results?buildId=313047&view=ms.vss-test-web.build-test-results-tab&runId=6404750&resultId=100250)|dotnet/runtime#87190|
|[313035](https://dev.azure.com/dnceng-public/public/_build/results?buildId=313035)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrame2Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=313035&view=ms.vss-test-web.build-test-results-tab&runId=6404264&resultId=100298)|dotnet/runtime#87583|
|[312288](https://dev.azure.com/dnceng-public/public/_build/results?buildId=312288)|dotnet/runtime|[chrome-DebuggerTests.GetPropertiesTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=312288&view=ms.vss-test-web.build-test-results-tab&runId=6381012&resultId=100298)|dotnet/runtime#87522|
|[312143](https://dev.azure.com/dnceng-public/public/_build/results?buildId=312143)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=312143&view=ms.vss-test-web.build-test-results-tab&runId=6377400&resultId=100298)|dotnet/runtime#87765|
|[311155](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311155)|dotnet/runtime|[chrome-DebuggerTests.HotReloadTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311155&view=ms.vss-test-web.build-test-results-tab&runId=6347046&resultId=100298)|dotnet/runtime#87522|
|[310742](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310742)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310742&view=ms.vss-test-web.build-test-results-tab&runId=6335172&resultId=100298)|dotnet/runtime#87700|
|[310467](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310467)|dotnet/runtime|[chrome-DebuggerTests.AssignmentTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310467&view=ms.vss-test-web.build-test-results-tab&runId=6326272&resultId=100298)|dotnet/runtime#87700|
|[310374](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310374)|dotnet/runtime|[chrome-DebuggerTests.GetPropertiesTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310374&view=ms.vss-test-web.build-test-results-tab&runId=6325020&resultId=100298)|dotnet/runtime#87659|
|[310139](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310139)|dotnet/runtime|[chrome-DebuggerTests.ArrayTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310139&view=ms.vss-test-web.build-test-results-tab&runId=6320670&resultId=100298)|dotnet/runtime#87522|
|[310117](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310117)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310117&view=ms.vss-test-web.build-test-results-tab&runId=6318988&resultId=100298)|dotnet/runtime#87190|
|[309051](https://dev.azure.com/dnceng-public/public/_build/results?buildId=309051)|dotnet/runtime|[chrome-DebuggerTests.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=309051&view=ms.vss-test-web.build-test-results-tab&runId=6288958&resultId=100298)|dotnet/runtime#85796|
|[308955](https://dev.azure.com/dnceng-public/public/_build/results?buildId=308955)|dotnet/runtime|[chrome-DebuggerTests.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=308955&view=ms.vss-test-web.build-test-results-tab&runId=6287194&resultId=100298)|dotnet/runtime#87634|
|[308358](https://dev.azure.com/dnceng-public/public/_build/results?buildId=308358)|dotnet/runtime|[chrome-DebuggerTests.SteppingTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=308358&view=ms.vss-test-web.build-test-results-tab&runId=6275376&resultId=100298)|dotnet/runtime#87607|
|[307377](https://dev.azure.com/dnceng-public/public/_build/results?buildId=307377)|dotnet/runtime|[chrome-DebuggerTests.CallFunctionOnTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=307377&view=ms.vss-test-web.build-test-results-tab&runId=6254308&resultId=100298)|dotnet/runtime#87285|
|[306922](https://dev.azure.com/dnceng-public/public/_build/results?buildId=306922)|dotnet/runtime|[chrome-DebuggerTests.SteppingTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=306922&view=ms.vss-test-web.build-test-results-tab&runId=6244540&resultId=100298)|dotnet/runtime#87522|
|[306725](https://dev.azure.com/dnceng-public/public/_build/results?buildId=306725)|dotnet/runtime|[chrome-DebuggerTests.CallFunctionOnTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=306725&view=ms.vss-test-web.build-test-results-tab&runId=6238240&resultId=100285)|dotnet/runtime#87549|
|[306673](https://dev.azure.com/dnceng-public/public/_build/results?buildId=306673)|dotnet/runtime|[chrome-DebuggerTests.GetPropertiesTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=306673&view=ms.vss-test-web.build-test-results-tab&runId=6237292&resultId=100298)|dotnet/runtime#87170|
|[305194](https://dev.azure.com/dnceng-public/public/_build/results?buildId=305194)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrame2Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=305194&view=ms.vss-test-web.build-test-results-tab&runId=6200832&resultId=100298)|dotnet/runtime#86255|
|[304960](https://dev.azure.com/dnceng-public/public/_build/results?buildId=304960)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrame2Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=304960&view=ms.vss-test-web.build-test-results-tab&runId=6194008&resultId=100298)|dotnet/runtime#87405|
|[304881](https://dev.azure.com/dnceng-public/public/_build/results?buildId=304881)|dotnet/runtime|[chrome-DebuggerTests.AssignmentTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=304881&view=ms.vss-test-web.build-test-results-tab&runId=6191800&resultId=100298)||
|[304822](https://dev.azure.com/dnceng-public/public/_build/results?buildId=304822)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=304822&view=ms.vss-test-web.build-test-results-tab&runId=6190154&resultId=100298)|dotnet/runtime#87405|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|2|8|53|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=323566
**Error message validated:** `/root/helix/work/correlation/chrome-linux/chrome unexpectedly exited with 127 during startup`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 6/28/2023 9:11:18 PM UTC

**Comment by pavelsavara** [comment]
Related https://github.com/dotnet/runtime/pull/86968

**Comment by radical** [comment]
Hm looks like the helix retry stuff didn't quite work.
