### ISSUE TITLE
Consider preserving some types for DiagnosticSource to work with dotnet-monitor in NativeAOT

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#87064]
Dotnet-monitor has a [list](https://github.com/dotnet/diagnostics/blob/main/src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/HttpRequestSourceConfiguration.cs) of key-value pairs that the tool relies on for diagnostic scenarios. For `NativeAOT`, we did some [work](https://github.com/dotnet/runtime/pull/76109) in `DiagnosticSource `to make the tooling experience better, by giving information on missing types rather than crash. 

If we can preserve these core list for asp.net, dotnet-monitor users will have a better experience with `DiagnosticsSource`.

cc @wiktork, @eerhardt

**Comment by eerhardt** [comment]
@LakshanF - specifically which properties don't work today?

We do already have a bunch of the properties in your list above marked as `[DynamicDependency]`. See:

https://github.com/dotnet/runtime/blob/7febca6802545d8c96e386187d536bc100d40337/src/libraries/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs#L217C1-L222

https://github.com/dotnet/runtime/blob/7febca6802545d8c96e386187d536bc100d40337/src/libraries/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs#L250-L257

and in ASP.NET:

https://github.com/dotnet/aspnetcore/blob/d919168952ac4da33be8532c6980547a783a7389/src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs#L441-L457

Note that there was a bug in AOT in this area - https://github.com/dotnet/runtime/issues/75994. But that has been fixed. So this should work. It would be good to document exactly which properties aren't working and we can get them added.

**Comment by tommcdon** [comment]
@LakshanF please update the issue with current status and remaining work for .NET 8

**Comment by LakshanF** [comment]
@eerhardt, Is the first part in dotnet monitor [Diagnostic string](https://github.com/dotnet/diagnostics/blob/main/src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/HttpRequestSourceConfiguration.cs#L22), map to [this](https://github.com/dotnet/aspnetcore/blob/main/src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs#L484) method? If so, I can see that the WriteDiagnosticEvent<T>'s T annotation in there will preserve all public properties of `HttpContext`. The `DynamicDependency `seems to preserve the properties of `HttpRequest `(one level deeper to preserve the properties of a property in `HttpContext`). I assume the key value pairs of the dotnet-monitor (example, `;ActivityParentId=*Activity.ParentId`), is tied with preserving all on types like `QueryString`, `HostString`, PathString. 

Can you explain how the key-value preservation work please?

**Comment by eerhardt** [comment]
> Is the first part in dotnet monitor [Diagnostic string](https://github.com/dotnet/diagnostics/blob/main/src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/HttpRequestSourceConfiguration.cs#L22), map to [this](https://github.com/dotnet/aspnetcore/blob/main/src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs#L484) method?

Yes. Notice that "[this](https://github.com/dotnet/aspnetcore/blob/main/src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs#L484) method" has a comment on it pointing directly to the same "[Diagnotic string](https://github.com/dotnet/diagnostics/blob/7cc6fbef613cdfe5ff64393120d59d7a15e98bd6/src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/HttpRequestSourceConfiguration.cs#L20-L33)".

> Can you explain how the key-value preservation work please?

Here is a pretty good comment on how the FilterAndPayloadSpecs work:

https://github.com/dotnet/runtime/blob/d1fc57ea18ee90aee8690697caed2b9f162409eb/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource.cs#L47-L79

Also see
