### ISSUE TITLE
False Positive CS8604 for Nullable<T>.ToString()

### ISSUE THREAD

**Issue by realbart** [dotnet/runtime#87070]
This code should not produce a CS8604 warning:

```
        int? value = 1;
        if (value is not null)
        {
            string stringValue = value.ToString();
        }
```

It's true that Nullable<int>.ToString() returns a nullable string, but it has only a null value if HasValue is false.

**Comment by stephentoub** [comment]
> It's true that Nullable.ToString() returns a nullable string, but it has only a null value if HasValue is false.

This is not the case.  Even if the nullable has a value, the ToString of the value it contains could return null.  The base `object.ToString` method returns null.  That particular case is discussed here: https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/api-guidelines/nullability.md#virtualabstract-methods-and-interfaces.

**Comment by realbart** [comment]
I still leave the suggestion to at least do this for system types (numbers) because their behavior is known and I believe this is the vast majority of uses for Nullable.

Also: In a nullable context this code fails on the line ```public override string ToString() => null;```

```
Foo? x = new Foo();
Console.WriteLine(x.HasValue);
Console.WriteLine(x.ToString() == null);

struct Foo
{
    public override string ToString() => null;
}
```

**Comment by stephentoub** [comment]
> Also: The line public override string ToString() => null; DOES yield a CS8603

That's because you declared it's return type as `object` but you're returning null. If you change it to `object?`, it won't warn.

**Comment by stephentoub** [comment]
> I still leave the suggestion to at least do this for system types (numbers) because their behavior is known and I believe this is the vast majority of uses for Nullable.

We have no way to describe that in the definition of Nullable. That would be a request for the language (dotnet/csharp) or compiler (dotnet/roslyn).
