### ISSUE TITLE
Question: Thread safety of X509Certificate2 class

### ISSUE THREAD

**Issue by knightmeister** [dotnet/runtime#87085]
Hi, firstly, forgive me if this is the wrong repository.

The [docs page for X509Certificate2](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate2?view=net-7.0#remarks) makes no mention of thread safety. 

I'm using Kestrel to host a multitennant app which I'm getting ready to launch. I use `ServerCertificateSelector` to select the appropriate X509 cert based on the hostname.

I cache the X509 certs for the first request to a given domain. This cert is then returned whenever that domain name is seen. There seems to be no problem with this approach from our testing but want to make sure this is considered OK because it's difficult to make that assessment from the documentation.

**Comment by teo-tsirpanis** [comment]
`X509Certificate`s are immutable and [their mutating members have been obsoleted](https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0026), so I wouldn't worry if I were you. But I am not 100% certain.

**Comment by vcsjones** [comment]
There is, technically, one point of mutability: `Dispose()`. The behavior of `X509Cerificate{2} ` is undefined if it is being read while another thread disposes of it. As long as you take care to not dispose of it while it's in use, I believe it will be fine to read from it from multiple threads. I suspect a considerable amount of code has been written to depend on the multi-thread readability of the certificate.

**Comment by knightmeister** [comment]
@vcsjones appreciate the clarification. Thanks for your help.
