### ISSUE TITLE
Interop Generators don't warn when CountElementName for parameter array is an out parameter

### ISSUE THREAD

**Issue by jtschuster** [dotnet/runtime#87081]
In the example below, the widths and length parameter will be used for marshalling the array, but they are not guaranteed to be set before the method is called. This would lead to a zero length array being marshalled.
```C#
        [LibraryImport("Doesn't Exist")]
        public static partial void Method(
                [MarshalUsing(CountElementName = nameof(length)),
                MarshalUsing(ElementIndirectionDepth = 1, CountElementName = nameof(widths))]
                int[][] array,
                [MarshalUsing(CountElementName = nameof(length))]
                out int[] widths,
                out int length);
```

The behavior of the generators should be the following:
<table>  
  <tr>
    <td />
    <th colspan = 9>Array parameter refKind / attribute</th>
  </tr>
  <tr>
    <th rowspan=9>Length(s) parameter refKind / attribute</th>
  </tr>
  <tr>
    <td/>
    <th>(nothing)</th>
    <th>ref</th>
    <th>in</th>
    <th>out</th>
    <th>[In, Out]</th>
    <th>[In]</th>
    <th>[Out]</th>
  </tr>
  <tr>
    <th>(nothing)</th>
    <td>Ok</td>
    <td>Ok</td>
    <td>Ok</td>
    <td>Ok</td>
    <td>Ok</td>
    <td>Ok</td>
    <td>Ok</td>
  </tr>
  <tr>
    <th>ref</th>
    <td>Ok</td>
    <td>Ok</td>
    <td>Ok</td>
    <td>Ok</td>
    <td>Ok</td>
    <td>Ok</td>
    <td>Ok</td>
  </tr>
  <tr>
    <th>in</th>
    <td>Ok</td>
    <td>Ok</td>
    <td>Ok</td>
    <td>Ok</td>
    <td>Ok</td>
    <td>Ok</td>
    <td>Ok</td>
  </tr>
  <tr>
    <th>out</th>
    <td>Warn</td>
    <td>Warn</td>
    <td>Warn</td>
    <td>Ok</td>
    <td>Warn</td>
    <td>Warn</td>
    <td>Ok</td>
  </tr>
  <tr>
    <th>[In, Out]</th>
    <td>Ok</td>
    <td>Ok</td>
    <td>Ok</td>
    <td>Ok</td>
    <td>Ok</td>
    <td>Ok</td>
    <td>Ok</td>
  </tr>
  <tr>
    <th>[In]</th>
    <td>Ok</td>
    <td>Ok</td>
    <td>Ok</td>
    <td>Ok</td>
    <td>Ok</td>
    <td>Ok</td>
    <td>Ok</td>
  </tr>
  <tr>
    <th>[Out]</th>
    <td>Warn</td>
    <td>Warn</td>
    <td>Warn</td>
    <td>Ok</td>
    <td>Warn</td>
    <td>Warn</td>
    <td>Ok</td>
  </tr>
</table>

**Comment by jtschuster** [comment]
cc: @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
> cc: @AaronRobinsonMSFT, does this matrix look right?

@jtschuster I'm not sure I understand how to use the matrix.

I assume the Y axis is relative to the argument with the `CountElementName` and the X axis is for the parameter that `CountElementName` refers to. If so, then the Y-`ref` is wrong for the X-`out` because the Y has in/out semantics and the length being used only has `out`.

Below is what I am describing above. This should warn because `array` will be marshalled "in" and "out", but its length is only `out`.

```csharp
   [LibraryImport("Doesn't Exist")]
      public static partial void Method(
              [MarshalUsing(CountElementName = nameof(length))]
              ref int[] array,
              out int length);
```

**Comment by jtschuster** [comment]
> I assume the Y axis is relative to the argument with the `CountElementName` and the X axis is for the parameter that `CountElementName` refers to. If so, then the Y-`ref` is wrong for the X-`out` because the Y has in/out semantics and the length being used only has `out`.

It's meant to be the other way around, which I think covers the scenario you're talking about. I've updated the table to use "Array parameter" and "Length(s) parameter" if that's clearer

**Comment by AaronRobinsonMSFT** [comment]
> > I assume the Y axis is relative to the argument with the `CountElementName` and the X axis is for the parameter that `CountElementName` refers to. If so, then the Y-`ref` is wrong for the X-`out` because the Y has in/out semantics and the length being used only has `out`.
> 
> It's meant to be the other way around, which I think covers the scenario you're talking about. I've updated the table to use "Array parameter" and "Length(s) parameter" if that's clearer

Ah. Thanks. This looks correct then.

**Comment by AaronRobinsonMSFT** [comment]
@jtschuster Are we deferring this to .NET 9?

**Comment by jtschuster** [comment]
@AaronRobinsonMSFT I think this could be a stretch goal for 8, but we could push it to 9 for tracking.
