### ISSUE TITLE
tools.ps1 should ensure sdk.txt is always created if createSdkLocationFile is true

### ISSUE THREAD

**Issue by cshung** [dotnet/runtime#871]
I think I have spotted a bug in the `dotnet.cmd`/`tools.ps1` interaction:

Here is the relevant content of [dotnet.cmd](https://github.com/dotnet/runtime/blob/master/dotnet.cmd):

https://github.com/dotnet/runtime/blob/496c2a628aef7ebf1fd5b92775d6eb1d19d996d3/dotnet.cmd#L3-L10

Apparently, `dotnet.cmd` assumes `tools.ps1` will ensure `sdk.txt` exists after `InitializeDotNetCli $true $true` is ran. Now let's look into the relevant code in `tools.ps1`.

https://github.com/dotnet/runtime/blob/496c2a628aef7ebf1fd5b92775d6eb1d19d996d3/eng/common/tools.ps1#L132-L165

If we didn't get a chance to reach the comparison on line 150 (e.g. we entered the branch of line 135), then we will not create the `sdk.txt`. If `sdk.txt` was never created (e.g. a clean clone), then the build would fail with a file not found error.

This is not just theoretical, this could actually happen if `dotnet.cmd` is invoked inside the build process (e.g. when `build.cmd` of `coreclr` trying to publish `crossgen2`). 

https://github.com/dotnet/runtime/blob/496c2a628aef7ebf1fd5b92775d6eb1d19d996d3/src/coreclr/build.cmd#L659

In that case, the `DOTNET_INSTALL_DIR` environment variable is already set somewhere upstream, therefore the script actually enters line 135 and never creates the `sdk.txt` file, leading to downstream failures.

IMHO, we should fix `tools.ps1` so that it ensures `sdk.txt` is created under all conditions.

**Comment by ViktorHofer** [comment]
Submitted a PR to fix this https://github.com/dotnet/arcade/pull/4546

**Comment by ViktorHofer** [comment]
Thanks for reporting @cshung
