### ISSUE TITLE
JIT still emitting helper calls for `typeof`

### ISSUE THREAD

**Issue by ShreyasJejurkar** [dotnet/runtime#87109]
This PR https://github.com/dotnet/runtime/pull/75573 was supposed to avoid helper for type info calls but looks like it's not working as intended, or maybe I am missing something! 

I just tried the same code sample against the main branch using CE (link here https://godbolt.org/z/beTeKEf95), I can see the JIT is still emitting the helper call and not getting the address of them. 

I printed the runtime version as well so that we are sure we are running against the latest main branch version which is .NET `8.0.0-preview.6.23304.99`

Quick reference screenshot 
![image](https://github.com/dotnet/runtime/assets/17148381/0d0e776a-4c4e-4831-a646-ee60c38f6dbd)

cc @EgorBo

**Comment by EgorBo** [comment]
Godbolt uses crossgen to obtain codegen and we don't use frozen objects for R2R (although, we do for NativeAOT).
The good news that if your R2R'd code is hot enough, it will be re-jitted with JIT and will benefit from the frozen objects ;-)

**Comment by EgorBo** [comment]
If you want to check it by yourself, download the most recent public preview of .NET 8 and run this:
```csharp
using System;
using System.Runtime.CompilerServices;

public class Prog
{
    static void Main(string[] args)
    {
        Foo();
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static Type Foo() => typeof(int);
}
```
with 
```
$env:DOTNET_JitDisasm="Foo"
dotnet run -c Release
```

**Comment by ShreyasJejurkar** [comment]
Thanks, @EgorBo for the reply. I was pretty sure I am missing something because of this I am not getting that behavior. 

> The good news that if your R2R'd code is hot enough, it will be re-jitted with JIT and will benefit from the frozen objects ;-)

I guess I can't simulate this online, so I won't see this unless I try it on my machine! 

Or is there any way we can tell CLR the method name so that it would consider that method as hot and it will rejit that method with more optimized codegen!? I guess not (at least I am not aware of)

**Comment by ShreyasJejurkar** [comment]
Yes, it does on local. Thanks, @EgorBo 

![image](https://github.com/dotnet/runtime/assets/17148381/e957fd8a-3273-4ded-ae83-371b908758b8)


btw not sure if are you seeing this, but `dotnet run` has gone pretty slow, roughly it takes 7 seconds to run a hello world! 
Yeah its another issue, nothing related to this, so I will close this!
