### ISSUE TITLE
.Net 6 performance of CreateSpecificCulture significantly slower than .net framework and .net core 3.1

### ISSUE THREAD

**Issue by Craig-TSS** [dotnet/runtime#87110]
### Description
Calling CreateCultureInfo (eg System.Globalization.CultureInfo.CreateSpecificCulture("en-US");) is substantially slower on .Net 6 than it was on .NetCore 3.1 or .Net Framework 4.7.2

Simple example attached using BenchmarkDotNet

### Configuration
Windows 10 Pro 22H2 (x64)

```
|                  Method |              Runtime |          Mean 
|------------------------ |--------------------- |--------------:
|       TestCreateCulture |             .NET 6.0           | 167,747.86 ns 
|       TestCreateCulture |        .NET Core 3.1       |   1,066.97 ns 
|       TestCreateCulture | .NET Framework 4.7.2 |   1,496.37 ns 
|                         |                      |               
| TestCachedCopyOfCulture |             .NET 6.0           |      48.98 ns 
| TestCachedCopyOfCulture |        .NET Core 3.1       |      56.83 ns 
| TestCachedCopyOfCulture | .NET Framework 4.7.2 |     100.20 ns 
|                         |                      |               
|    TestInvariantCulture |             .NET 6.0          |      44.28 ns 
|    TestInvariantCulture |        .NET Core 3.1      |      55.14 ns 
|    TestInvariantCulture | .NET Framework 4.7.2 |      96.39 ns 

```

Sample benchmark attached
[CreateCulturePerformanceIssueNet6.zip](https://github.com/dotnet/runtime/files/11645670/CreateCulturePerformanceIssueNet6.zip)

**Comment by tarekgh** [comment]
Since .NET 5.0 we switched to use ICU. The first culture creation has a cost for normalizing the names before calling ICU. Alos, if you are comparing with .NET 3.1, we are using ICU there too which I believe these numbers will be different when running on Linux/MacOS. 

But it is clear after caching the culture, we are faster than the other versions of the framework.

**Comment by HypsyNZ** [comment]
The represents an un-usable regression.

Tell yourself whatever you want microsoft fan boy.

**Comment by Craig-TSS** [comment]
I personally am only interested in the Windows performance of this. So your saying we now have to cache the culture ourselves in our apps (as per the TestCachedCopyOfCulture benchmark)? 
TBH I would have expected the framework itself to cache the cultures it has created (especially given the large drop in performance since it was changed) so subsequent calls to create that culture just return the already cached version and significantly improve the performance for everybody, rather than relying on every developer that uses it to cache it themselves, especially when they have never had to do it previously.

**Comment by tarekgh** [comment]
The returned culture from `CreateSpecificCulture` is not a read-only objects. So, we cannot return a cached version of the culture. Even if we cache it, we'll have to clone it before returning it to you which still  will have some cost too. 

My question is why you are using `CreateSpecificCulture`? can you call `CultureInfo.GetCultureInfo` instead? `GetCultureInfo` will return you a cached read-only object. If you can talk more about your scenario, I may be able to advise what is the best you can do here.

**Comment by Craig-TSS** [comment]
Thanks for the clarification, yes I can call GetCultureInfo instead, that seems a more suitable call to be making anyway, for whatever reason I missed the existence of that function and have been using the create one instead not realising the implications.
