### ISSUE TITLE
System.Text.Json's default enum converter handles key serialization inconsistently

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#87129]
Consider the following example:
```C#
var dictionary = new Dictionary<MyEnum, MyEnum> { [MyEnum.A] = MyEnum.A };
Console.WriteLine(JsonSerializer.Serialize(dictionary)); // {"A":0}, should have been {"0":0}

// For contract, here's the behavior using the JsonStringEnumConverter:
var options = new JsonSerializerOptions { Converters = { new JsonStringEnumConverter() } };
Console.WriteLine(JsonSerializer.Serialize(dictionary, options)); // {"A":"A"}

public enum MyEnum { A };
```

When fixing this, we try to make the converter tolerate the current format, since doing otherwise could break users that are trying to read JSON created from previous versions of the serializer.

**Comment by layomia** [comment]
I believe it's by-design for the non-string-key serialization feature to format supported types to their string representations by default. For enums, that would apply if the key value maps to a valid literal for the type, like the example above.

**Comment by eiriktsarpalis** [comment]
Ah, fair enough then.
