### ISSUE TITLE
Localization cultures (en-AU) not installing under Alpine 3.17

### ISSUE THREAD

**Issue by danielbecroft** [dotnet/runtime#87128]
There appear to be issues with globalization cultures no longer being installed correctly under Alpine 3.17 containers (specifically, `en-AU`).

### Steps to Reproduce

I've got a simple program:
```c#
using System.Globalization;

Console.WriteLine($"CultureInfo.CurrentCulture = {CultureInfo.CurrentCulture}");
Console.WriteLine($"DateTime.Today = {DateTime.Today}");

foreach (var format in new string[] { "dd-MMM-yyyy", "dd-MMMM-yyyy" })
{
    Console.WriteLine($"format = {format} ==> {DateTime.Today.ToString(format)}");
}
```

When running in an Alpine container, I get the following results:
```
Using docker image sha256:2cd4e548f635f30dd562027a0a75d7407036eb0f7ddbf9e02d379f7bca6446b4 for mcr.microsoft.com/dotnet/sdk:7.0-alpine with digest mcr.microsoft.com/dotnet/sdk@sha256:f116f997b2cad177074276bb36c46829251dd14d421ea011867f3aee5c03bd19 ...
$ apk add --no-cache icu-libs icu-data-full
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/x86_64/APKINDEX.tar.gz
OK: 55 MiB in 34 packages
$ dotnet run
CultureInfo.CurrentCulture = en-AU
DateTime.Today = 1/6/2023 12:00:00am
format = dd-MMM-yyyy ==> 01-June-2023
format = dd-MMMM-yyyy ==> 01-June-2023
```

I'm also setting these variables for the container:
```
DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "false"
LC_ALL: en_AU.UTF-8
LANG: en_AU.UTF-8
```

But they don't appear to be making a difference. What's strange is the functionality was working a couple of weeks ago on the same code, and the same base image. I can see from the issue history there was an [issue](https://github.com/dotnet/dotnet-docker/issues/3844) where a different package was required for 3.16, but from what I can see, this is installed by default (and I'm installing it again).

I've tried 6.0, and alpine 3.15/3.16 as well, with the same results.

**Comment by tarekgh** [comment]
This is a duplicate of the https://github.com/dotnet/runtime/issues/86643 and this behavior is by design by the CLDR (Unicode Standard). Please read the comments on https://github.com/dotnet/runtime/issues/86643 to learn more about that.

**Comment by danielbecroft** [comment]
Thanks @tarekgh .  I've read the comments on that issue and agree that it's due to the underlying definitions by ICU. But, what I can't work out, is why the same ICU version is giving different results. For example, I've run through the various combinations of Alpine versions, for both 6.0.301 and 6.0.302, and I can't' find a correlation to an ICU upgrade.

| Image | ICU version | Output | Result |
| --- | --- | --- | --- |
| 6.0.301-alpine-3.14 | 67.1 | `Jun` | PASS | 
| 6.0.301-alpine-3.15 | 69.1 | `June` | FAIL | 
| 6.0.301-alpine-3.16 | 71.1 | `Jun` | PASS | 
| 6.0.302-alpine-3.15 | 69.1 | `June` | FAIL | 
| 6.0.302-alpine-3.16 | 71.1 | `June` | FAIL | 

The builds on 6.0.301 is the weird one. If it was purely an ICU version bump, then I'd expect all images using the same ICU version to operate the same, but that isn't the case.

**Comment by tarekgh** [comment]
> But, what I can't work out, is why the same ICU version is giving different results. 

Is it possible in some images you have multiple ICU versions installed in same image? You may try to use the code like https://github.com/dotnet/runtime/blob/e96321db982c3add192381f6ea4ff0a999ee1410/src/libraries/Common/tests/TestUtilities/System/PlatformDetection.cs#L390 which give the ICU version used at the runtime and run it on `6.0.301-alpine-3.16` and `6.0.302-alpine-3.16`

**Comment by danielbecroft** [comment]
Thanks @tarekgh , I've run the referenced method on both versions, and they match the version numbers above across all the image tags. I sourced the original version using `find / -name "*icu*"`, and taking the version off the filenames in the `/usr/lib` directory. 

* `6.0.301-alpine3.16`
```
ICUVersion() = 71.1.0.0
```

* `6.0.302-alpine3.16`
```
ICUVersion() = 71.1.0.0
```

**Comment by tarekgh** [comment]
Interesting. 

were you setting the default locale to en_AU on both images and also using CutureInfo.CurrentCulture to validate the setting? When I get some time, I can try to look at these images and figure out the difference.

**Comment by Clockwork-Muse** [comment]
Irrespective of the merits of tracking the differences down... 

@danielbecroft - As I mentioned in the original issue, why do you care what the output looks like?

**Comment by tarekgh** [comment]
@danielbecroft I looked at the two docker images `6.0.301-alpine3.16` and `6.0.302-alpine3.16`. Although the same version of the ICU is installed there but looks two different sets of ICU data `icudt71l.dat` are there. 

```
/usr/share/icu/71.1 # ls -la


 2678944 May 15  2022 icudt71l.dat <-- trimmed data which work incorrectly ... Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec,  
30418768 May 15  2022 icudt71l.dat <-- complete data which work correctly  ... Jan, Feb, Mar, Apr, May, June, July, Aug, Sept, Oct, Nov, Dec, 
```

This means `6.0.301-alpine-3.16` installed ICU version with trimmed data. 

Will be good to answer @Clockwork-Muse question too.

**Comment by danielbecroft** [comment]
Thanks @Clockwork-Muse . The issue is not so much what the output looks like for us, but more for parsing of dates. We get numerous sources of data as text, where the dates are formatted as `01-Jan-2023`, etc. We have historically just done:

```c#
DateTime.ParseExact(input, "dd-MMM-yyyy")
// or 
DateTime.TryParseExact(input, "dd-MMM-yyyy", CultureInfo.CurrentCulture, DateTimeStyles.AssumeLocal, out DateTime date)
```

to parse the date, and this has worked for years. It's frustrating that just by bumping to a later security patch of a docker image, this functionality now no longer works for the `eu-AU` culture, especially due to something outside of our control. 

We now have to balance staying on the older image (with the security vulnerabilities it has), v changing and testing our application, and communicating with developers that they can use the `DateTime` library to parse/format strings, unless they need the `MMM` qualifier, then we have to do it ourselves.

The only reason we stumbled across this, was that we had a flaw in our unit tests, where we used `DateTime.Today`, and when it clicked over to June, the tests started to fail, so we will now rectify that. 

I understand that it's outside of the .NET ecosystem (except for the strange versioning issues above), but for us, this is still a breaking change deployed in a security release.

**Comment by Clockwork-Muse** [comment]
> The issue is not so much what the output looks like for us, but more for parsing of dates.

_Why_ are you parsing dates this way?

 - If this is for an API or data interchange, you **should not** be parsing dates that look like this, but rather using the invariant culture and either the round-trip (`O`/`o`) or the "universal sortable" (`u`) format specifier - essentially, the standard ISO format.
 - If this is for user-facing input, _preferably_ you should avoid text input in favor of a UI element like a calendar selection window.  Quite apart from any culture problems (even if the data hadn't changed here, people might abbreviate anything wrong - or use numbers, or any number of other things), it helps with validating cases like leap years.  For those rare cases requiring textual input, an abbreviated month name seems strange (in preference for the full month name).
 - If you're doing something like full-document parsing..... good luck.  Your problems are way worse, because you have no guarantees about format in the first place, never mind non-standardized abbreviations.

**Comment by danielbecroft** [comment]
`yyyy-MM-dd` is the way forward, but there are numerous providers that we interact with that provide data in the form of CSV files, and the dates are formatted as `dd-MMM-yyyy`, and we aren't going to be alone in that situation. We have no control over how they provide their data, and they're the sort of industries where changes to that format would take years. 

As I said, we'll have to change our code and adjust it, but a breaking change like this in a security release is concerning. Who knows what other breaking changes are going to get introduced in other security releases.

**Comment by Clockwork-Muse** [comment]
> We have no control over how they provide their data, and they're the sort of industries where changes to that format would take years.

I mean you can always ask (or check and see if they already provide a separate field).... And you should at least bring up that if they're using culture data, they could break their partners' data intake.

but in the meantime, the better way forward is to **not** use an OS-provided culture, but a custom created one in your application.  Because your application doesn't really care about the actual culture per se, but rather a notional version you and the other business have agreed on.

> but a breaking change like this in a security release is concerning

This isn't considered a breaking change, because it's been standard practice for multiple decades that you don't use culture-specific formats for interchange, for exactly this reason.  And even more serious silent ones.

**Comment by danielbecroft** [comment]
This discussion isn't going anywhere. @tarekgh has helpfully identified where the problem is, and why we get different results across the different images. I've raised bugs on the ICU mailing lists and Jira to get the culture information corrected, as it is wrong.

Thanks for your time.
