### ISSUE TITLE
Using AssemblyLoadContext for isolation, respecting transitive dependencies

### ISSUE THREAD

**Issue by plioi** [dotnet/runtime#8714]
I'm porting a test framework to .NET Core, so I need to avoid relying on AppDomains for netcoreapp test assemblies. I've attempted to use a custom AssemblyLoadContext to accomplish the same thing, but it's not clear how to have a custom AssemblyLoadContext that can successfully load dependencies like nuget packages now that such assemblies don't literally appear in a project's build output folder.

Background
-------

Historically, like NUnit and xUnit, I've used an AppDomain to address assembly loading. The running executable is a console application living in some nuget-controlled folder, while the test assembly and its dependencies live in the test assembly's own build output folder. The primary AppDomain for the console application finds the runner's own dependencies right beside the exe, of course, and a secondary AppDomain is created with the ApplicationBase path set to the test assembly's folder (ie ...bin/Debug/MyProject.Tests/). This essentially tricks the test assembly into thinking it's the running application, as far as assembly loading goes.

First Attempt at a Custom AssemblyLoadContext
-------

For a netcoreapp test assembly, we don't have AppDomains. It appears this is one of the things AssemblyLoadContext is intended to solve:

* https://blogs.msdn.microsoft.com/dotnet/2016/02/10/porting-to-net-core/ specifically calls out AssemblyLoadContext as the recommended alternative to AppDomains for resolving assemblies dynamically.
* @gkhanna79's helpful documentation at https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/assemblyloadcontext.md says these provide the "Ability to load assemblies explicitly in a context isolated from that of the application."
* @jkotas's examples in the comments at https://blogs.msdn.microsoft.com/dotnet/2016/05/27/making-it-easier-to-port-to-net-core/ got me far enough for basic scenarios to work:

```csharp
    class TestAssemblyLoadContext : AssemblyLoadContext
    {
        readonly string testAssemblyDirectory;

        public TestAssemblyLoadContext(string testAssemblyDirectory)
        {
            this.testAssemblyDirectory = testAssemblyDirectory;
        }

        protected override Assembly Load(AssemblyName assemblyName)
        {
            return LoadFromFolderOrDefault(assemblyName);
        }

        Assembly LoadFromFolderOrDefault(AssemblyName assemblyName)
        {
            try
            {
                var path = Path.Combine(testAssemblyDirectory, assemblyName.Name);

                if (File.Exists(path + ".dll"))
                    return LoadFromAssemblyPath(path + ".dll");

                if (File.Exists(path + ".exe"))
                    return LoadFromAssemblyPath(path + ".exe");

                //TODO: Probably missing something here. What if it's
               //             a transitive nuget dependency, not literally in the
               //             test project's build output folder?

                return null;
            }
            catch (Exception ex)
            {
                  Console.WriteLine(ex);
            }

            return null;
        }
    }
```

Not too surprisingly, this would only help to load assemblies that literally appear beside the test assembly. Transitive nuget dependencies would only be implied by the runtimeconfig.json, deps.json, and runtimeconfig.dev.json files in that folder.

I had been hoping that the inherited behavior from AssemblyLoadContext would provide some assistance for traversing such dependencies and finding their location on disk, so that my TODO above could find them.

xUnit's Solution
--------------

Earlier, the xUnit team ran into a similar challenge, as discussed here: https://github.com/dotnet/core-setup/issues/1926

Instead of making a custom AssemblyLoadContext, their solution instead involves 2 parts:
* kicking off their console runner with "dotnet exec..." so that they can specify the test assembly's own json files as the `--depsfile` and `--runtimeconfig` as seen here: https://github.com/xunit/xunit/blob/091f2055c91357d0ac2322348f00e7f4ed7cc31c/src/dotnet-xunit/Program.cs#L388 That appears to solve loading of the test assembly, its physically-present dependencies in the same folder, and likely their transitive dependencies too.
* Since that alone would likely break their console runner from loading its *own* dependencies, they attach a handler to AssemblyLoadContext.Default.Resolving to load assemblies that live beside the console runner itself: https://github.com/xunit/xunit/blob/091f2055c91357d0ac2322348f00e7f4ed7cc31c/src/xunit.console/Utility/NetCoreAssemblyHelper.cs

Request for Guidance
-------------------

I've attempted both approaches unsuccessfully, so this is a request for guidance.

With my custom AssemblyLoadContext above, I achieve the desired isolation you'd want in a test framework (it'd be awful if my own reference to Newtonsoft.Json for instance interfered with that of a test project!), but I fail to load transitive dependencies.

When I instead try to use `dotnet exec` and AssemblyLoadContext.Default.Resolving, my app crashes without even entering Main due to a failure to load its own dependency sitting right beside Main's assembly. I'm not sure why that's happening for me but not for xUnit. Even if I could get around that, I think this leaves the door wide open for mistakes at runtime when the test framework's own dependencies are a different version than those of the test assembly.

What's the right way to achieve AppDomain-like isolation, for a test assembly and its dependencies? VSTest must have had to encounter and resolve the same challenge for `dotnet test`, but I haven't been able to find it in their implementation.

**Comment by moh-hassan** [comment]
This custom [ALC ](https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support#load-plugins) can load  transitive dependencies  

The ALC use the  `AssemblyDependencyResolver` to resolve the dependencies.

I tested it with a complex plugin scenario that reference a class library and external OLEDB nuget package and it's working fine. Also it's working in [dotnet samples](https://github.com/dotnet/samples/tree/master/core/extensions/AppWithPlugin).

**Comment by plioi** [comment]
I think this can be closed now that it's easy to implement an AssemblyLoadContext in combination with AssemblyDependencyResolver, and since there's some clear documentation on the ins-and-outs: https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support
