### ISSUE TITLE
[API Proposal]: Uri : ISpanFormattable

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#87151]
### Background and motivation

Uri.ToString() is a common source of allocation, especially in logging code.  We can avoid some such allocation by enabling Uri to play nicely with string interpolation by implementing ISpanFormattable that enables it to write directly into a destination buffer.

### API Proposal

```diff
namespace System;

public class Uri : ISerializable,
+    ISpanFormattable
{
+    bool TryFormat(Span<char> destination, out int charsWritten);
}
```

### API Usage

```csharp
StringBuilder sb = ...;
sb.Append($"Url: {url}");
```

### Alternative Designs

- We could also implement `IUtf8SpanFormattable` to support directly writing out UTF8 bytes.

**Comment by bartonjs** [comment]
Looks good as proposed.  We additionally feel that it's worthwhile to approve the IUtf8SpanFormattable addition (even if it gets implemented later)

```
namespace System;

public class Uri : ISerializable,
+    ISpanFormattable
+    , IUtf8SpanFormattable
{
+    public bool TryFormat(Span<char> destination, out int charsWritten);
+    public bool TryFormat(Span<byte> utf8Destination, out int bytesWritten);
+    // Explicitly implement the formattable interfaces to hide unsupported parameters.
}
```
