### ISSUE TITLE
[mono][tvos] Failing Vector64/128 tests

### ISSUE THREAD

**Issue by jandupej** [dotnet/runtime#87164]
There are test failures that do with extracting a single item from a `Vector64` or `Vector128` of multiple types. This seems to occur only on tvos (extra-platforms). See https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-87058-merge-76c973399c7b4da993/System.Runtime.Intrinsics.Tests.Attempt.2/1/net.dot.System.Runtime.Intrinsics.Tests.log?helixlogtype=result

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=293814
Build error leg or test failing: System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.GetOne*
Pull request: https://github.com/dotnet/runtime/pull/87058

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step).

```json
{
  "ErrorMessage": "System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.GetOne",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[333189](https://dev.azure.com/dnceng-public/public/_build/results?buildId=333189)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.Intrinsics.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=333189&view=ms.vss-test-web.build-test-results-tab&runId=6895062&resultId=185558)|dotnet/runtime#88559|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|1|

**Comment by SamMonoRT** [comment]
The hit count is 1 over the last month. @steveisok - should we remove the blocking-clean-ci label ?

**Comment by steveisok** [comment]
Yes, should we even keep the issue open?

**Comment by SamMonoRT** [comment]
Closing issue. @jandupej if you see these failures again, please re-open with recent build logs.
