### ISSUE TITLE
Open terminal/bash/console/cmd on macOS/linux using ProcessStartInfo and RedirectStandardOutput/Error

### ISSUE THREAD

**Issue by muhamedkarajic** [dotnet/runtime#87172]
### Description

I'm trying to open a Terminal (CMD) and execute some commands while monitoring the outputs of those commands. However I can't seem to find a way to do that on macOS. 

Maybe what I'm missing is a /C like in CMD but I could not find any info about it online. 
`/C -Carries out the command specified by string and then terminates.`

On some forums people write use ScriptEditor, however that won't work for my workflow cause I want to monitor the responses and based on it execute futher commands.

### Reproduction Steps

```csharp
var workingDirectory = "PLACE_HODLER";
var processStartInfo = new ProcessStartInfo("/System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal", "ls")
{
    RedirectStandardOutput = true,
    RedirectStandardError = true,
    UseShellExecute = false,
    WorkingDirectory = workingDirectory,
    CreateNoWindow = true
};
```

### Expected behavior

Should open a terminal and list the files inside of it.

### Actual behavior

Opens the terminal and dose not do anything.

**Comment by muhamedkarajic** [comment]
For anyone who might encounter the same issues, there is a way to solve it using the bash in macOS.

E.g.
```csharp
var command = "npm i --save";
var result = await Cli
    .Wrap("/bin/bash")
    .WithArguments($"-c \"{command}")
    .WithWorkingDirectory(dir)
    .WithStandardOutputPipe(PipeTarget.ToDelegate(Console.WriteLine))
    .WithStandardErrorPipe(PipeTarget.ToDelegate(Console.WriteLine))
    .ExecuteBufferedAsync();
```

What did not work for me was:

```csharp
var command = "npm i --save";
var processStartInfo = new ProcessStartInfo()
{
    FileName = "/bin/bash",
    CreateNoWindow = false,
    Arguments = $"-c \"{command}",
    UseShellExecute = false,
    RedirectStandardOutput = true,
    RedirectStandardError = true
};
```

**Comment by IvanJosipovic** [comment]
Thank you for this issue, I'm facing the same problem and couldn't figure out the reason.
My project is using .Net 8 Preview 5
Basic process calls stopped working in Linux, https://github.com/IvanJosipovic/KubernetesCRDModelGen/blob/ab2bdedba2cad36fe57d94a4836b5333fb95ce11/src/KubernetesCRDModelGen.Sync/HelmClient.cs

**Comment by Jozkee** [comment]
> What did not work:
> ```csharp
> var command = "npm i --save";
> var processStartInfo = new ProcessStartInfo()
> {
>     FileName = "/bin/bash",
>     CreateNoWindow = false,
>     Arguments = $"-c \"{command}",
>     UseShellExecute = false,
>     RedirectStandardOutput = true,
>     RedirectStandardError = true
> };
> ```
> 

This does work but your snippet is incomplete. You need to start the process and read StandardOutput and/or StandardError.
```cs
var command = "npm i --save";
var processStartInfo = new ProcessStartInfo()
{
    FileName = "/bin/bash",
    CreateNoWindow = false,
    Arguments = $"-c \"{command}",
    UseShellExecute = false,
    RedirectStandardOutput = true,
    RedirectStandardError = true
};

var p = Process.Start(processStartInfo);

string s = p!.StandardOutput.ReadToEnd();
Console.WriteLine(s);

s = p!.StandardError.ReadToEnd();
Console.WriteLine(s); // prints "/bin/bash: npm: command not found" for me.

p.WaitForExit();
```
