### ISSUE TITLE
Field defined with profiling API contains out of thin air values

### ISSUE THREAD

**Issue by ori-saporta83** [dotnet/runtime#87213]
### Description

Using the dotnet profiling API to [define a new field](https://learn.microsoft.com/en-us/dotnet/framework/unmanaged-api/metadata/imetadataemit-definefield-method), we add a ulong field without assigning any values to it.
We sample the contents of the field during the execution of an SslStream and see that it receives values that no code we know of assigned to it.
At this point, we have noticed this phenomenon only when adding fields to generated async state machine inner classes of the SslStream class. 
Important notes:
1. This happens regardless of the field name.
2. Also occurs if we do assign any value to the field, which gets overwritten at some point during the SslStream run.

### Reproduction Steps

The full project reproducing the issue [dotnet-profiler-test.zip](https://github.com/dotnet/runtime/files/11677041/dotnet-profiler-test.zip), is based on the [ELTProfiler sample ](https://github.com/microsoft/clr-samples/tree/master/ProfilingAPI/ELTProfiler) with a test program that reproduces the issue is attached.

To reproduce the issue using the test project
1. Open the solution
2. Build all projects
3. Edit TestApp\Properties\launchSettings.json, set CORECLR_PROFILER_PATH to the path of the ClrProfiler.dll built
4. Run TestApp

Some information on how the profiler and test programs work
1. Initialize a profiler
```cpp
HRESULT STDMETHODCALLTYPE CorProfiler::Initialize(IUnknown* pICorProfilerInfoUnk)
{
	HRESULT queryInterfaceResult = pICorProfilerInfoUnk->QueryInterface(__uuidof(ICorProfilerInfo8), reinterpret_cast<void**>(&this->corProfilerInfo));

	if (FAILED(queryInterfaceResult))
	{
		return E_FAIL;
	}

	DWORD eventMask = COR_PRF_MONITOR_MODULE_LOADS;

	auto hr = this->corProfilerInfo->SetEventMask(eventMask);
	if (hr != S_OK)
	{
		printf("ERROR: Profiler SetEventMask failed (HRESULT: %d)", hr);
	}

	return S_OK;
}
```
2. When the relevant module loads, add a field the profiling API, like so:
```cpp
	mdTypeDef sslTkn;
	mdi->FindTypeDefByName(tname, NULL, &sslTkn);
	mdTypeDef asmTkn;
	mdi->FindTypeDefByName(asmName, sslTkn, &asmTkn);

	IMetaDataEmit2* mde;
	mdi->QueryInterface(IID_IMetaDataEmit2, (void**)&mde);

	// Create the field type signature blob
	ULONG fieldTypeBlobSize;
	COR_SIGNATURE fieldTypeBlob[] = { IMAGE_CEE_CS_CALLCONV_FIELD, ELEMENT_TYPE_U8 };

	// Define the field in the specified class
	mdFieldDef idFldTkn = 0;
	uint64_t zero = 0;
	mde->DefineField(asmTkn, fieldName, fdPublic, fieldTypeBlob, sizeof(fieldTypeBlob), ELEMENT_TYPE_U8, &zero, 4, &idFldTkn);
```
3. Instrument a specific method, sampling the contents of the field when it is called, like so:
```cpp
	mdMethodDef mnTkn;
	mdi->FindMethod(asmTkn, L"MoveNext", nullptr, 0, &mnTkn);
	ILRewriter rewriter(corProfilerInfo, nullptr, moduleId, mnTkn);
	rewriter.Import();

	auto pos = rewriter.GetILList()->m_pNext;
	ILInstr* pNewInstr = rewriter.NewILInstr();
	pNewInstr->m_opcode = CEE_LDARG_0;
	rewriter.InsertBefore(pos, pNewInstr); // stack: this

	pNewInstr = rewriter.NewILInstr();
	pNewInstr->m_opcode = CEE_LDFLD;
	pNewInstr->m_Arg32 = idFldTkn;
	rewriter.InsertBefore(pos, pNewInstr); // stack: __vf_id

	pNewInstr = rewriter.NewILInstr();
	pNewInstr->m_opcode = CEE_LDC_I4;
	pNewInstr->m_Arg32 = type;
	rewriter.InsertBefore(pos, pNewInstr); // stack: __vf_id, type

	pNewInstr = rewriter.NewILInstr();
	pNewInstr->m_opcode = CEE_LDC_I8;
	pNewInstr->m_Arg64 = reinterpret_cast<intptr_t>((void*)MoveNextEnter);
	rewriter.InsertBefore(pos, pNewInstr); // stack: __vf_id, type, MoveNextEnter

	pNewInstr = rewriter.NewILInstr();
	pNewInstr->m_opcode = CEE_CALLI;
	pNewInstr->m_Arg32 = sigTkn;
	rewriter.InsertBefore(pos, pNewInstr); // stack: 

	std::vector<uint8_t> modifiedIL;
	rewriter.Export(modifiedIL);
	rewriter.SetILFunctionBody(modifiedIL);
```
4. Log the value on "MoveNextEnter" like so:
```cpp
static void STDMETHODCALLTYPE MoveNextEnter(uint64_t sm, uint8_t type)
{
	printf("MoveNextEnter SM=%llx type=%d\n", sm, type);
}
```
5. Run the test program calling GetStringAsync from an https address with the profiler attached, like so:
```csharp
namespace TestApp
{
    internal class Program
    {
        static void Main(string[] args)
        {
            for (int i = 0; i < 10; i++)
            {
                Console.WriteLine("start {0}", i);
                GetHttpSite().Wait();
            }
            Console.WriteLine("done");
        }

        private static async Task<string> GetHttpSite()
        {
            HttpClient client = new HttpClient();
            return await client.GetStringAsync("https://www.microsoft.com");
        }
    }
}
```

### Expected behavior

Field value should always be zero

### Actual behavior

The field gets seemingly random values of 0xffffffff and 1. 
We also instrumented a "control" method and for it the field as constantly at 0, as expected.
see the sample results here, where the "type" field indicates which method is instrumented (0 - SslStream, 1 - control method)
```
MoveNextEnter SM=0 type=1
MoveNextEnter SM=ffffffff type=0
MoveNextEnter SM=1 type=0
MoveNextEnter SM=0 type=1
```

### Regression?

This happened in all dotnet and dotnet-core versions we have tested. 
We did not encounter the phenomenon on any .Net Framework versions.

### Known Workarounds

It seems that adding an additional field of the exact same signature causes only the last field added to contain the unexpected data.

### Configuration

.Net version - This sample runs on dotnet 6, but was also tested on dotnet-core 3.X.
OSs - 
1. Edition	Windows 11 Pro
Version	22H2
OS build	22621.1702
Experience	Windows Feature Experience Pack 1000.22641.1000.0
2. Windows Server 2019 Datacenter
Version 1809
OS build 17763.4252 

Architecture - x64

We do not know if it is limited to this configuration, we expect it is not.

**Comment by tommcdon** [comment]
@davmason please take a look

**Comment by davmason** [comment]
Hi @ori-saporta83,

I took a look at your repro project, when I debug it I can see that the 0xFFFFFFFF you're seeing is being read out of a stack address that never gets set by the MoveNext function, i.e. it is stale data from some previous function that just happens to be on the stack. I don't have an explanation right now, I will have to spend some more time investigating.

**Comment by davmason** [comment]
@AndyAyersMS do you know if the jit has any special assumptions about the compiler generated async state machines? We have a customer reporting that fields added to an async state machine do not behave as expected. I have investigated a bit and not seen anything obvious, just wanted to check before digging in deeper.

**Comment by jkotas** [comment]
JIT has no special handling for async state machines.

The dotnet/runtime assemblies are compiled with `SkipLocalsInit` optimization. This optimization means that stack variables have to be always initialized explicitly, the JIT is not going to zero initialize them with zeros by default. The problem is that the new field added by the instrumentation is not initialized explicitly. It explains why it has random uninitialized value.

**Comment by ori-saporta83** [comment]
That explanation is not consistent with our observations. 
Regarding the initialization, first, we used the constant value to initialize the field to zero. 
Second, we have used this API on hundreds of other classes and consistently got 0 on all others. 
Even more importantly, this does not explain why the value changes occasionally, like you can see in the provided logs, from ffffffff to 1.
Moreover, our actual use case does involve setting the value at some point, but it still gets subsequently overridden when retrieving it later on. 
These additional use cases were not included in the provided test project for the sake of brevity.

**Comment by jkotas** [comment]
> Regarding the initialization, first, we used the constant value to initialize the field to zero.

The provided test project does not have any such initialization. The `pValue` argument of `DefineField` method applies to static fields only. It has no effect on instance fields.

There is a second problem in the provided test project: The instrumentation is producing invalid IL. The `<ReadAsyncInternal>d__188`1` type is generic. Instance fields of generic types have to be accessed using FieldRef token. The FieldRef token is necessary to provide generic instantiation details. The provided test project is accessing the field using FieldDef token that does not contain generic instantiation details. It results in a completely unrelated field to be fetched.

**Comment by ori-saporta83** [comment]
I will revise the test project accordingly and provide an updated sample ASAP.

**Comment by ori-saporta83** [comment]
Using a member ref on the type spec seemed to resolve the issue.
Thank you very much for your assistance.
