### ISSUE TITLE
Apt dependency `libnuma1` missing for Ubuntu 22.04 + amd64

### ISSUE THREAD

**Issue by externl** [dotnet/runtime#87225]
### Description

Hi, sorry if this is the wrong repository to report this issue.

We recently encountered this issue when we upgraded our CI Docker container to use Ubuntu 22.04. We noticed that [`QuicConnection.IsSupported`](https://learn.microsoft.com/en-us/dotnet/api/system.net.quic.quicconnection.issupported?view=net-7.0#system-net-quic-quicconnection-issupported) was suddenly returning `false` when it was previously working on Ubuntu 20.04. 

After some digging it was narrowed down to a missing dependency `liblttng-ust1`. It is listed on the [Install the .NET SDK or the .NET Runtime on Ubuntu](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#dependencies) page as required and that "When you install with a package manager, these libraries are installed for you."

It appears that it is not he case for this particular dependency. Minimal Ubuntu installs (like from Docker) do not include this out of the box, but regular sever installs do (e.g. installing from the ISO).

Adding the MS apt repository and installing `dotnet` does not bring in this dependency. 

This also affects the official MS container `mcr.microsoft.com/dotnet/sdk:7.0`

As far as I can tell this affects `amd64`, but not `arm64`. Uninstalling `liblttng-ust1` in an arm64 container will also uninstall `dotnet`. This doesn't seem to be the case for `amd64`

### Reproduction Steps

Clone https://github.com/externl/quic-test on an `amd64` machine with Docker installed. 

By default it only a few packages are installed. Just enough to enable the ms repo and install `dotnet-sdk-7.0`. It does not include `liblttng-ust1`. 

```
docker build -t quic-test .
docker run --rm quic-test
```

You'll see `QIC is not supported :(`

Now update `Dockerfile` and uncomment the line that installs `liblttng-ust1`. The the above commands again and you'll see `QIC is supported :)`

You should also be able to reproduce this by uninstalling `liblttng-ust1` and then installing `dotnet-sdk-7.0` from the MS apt repostiroy. 

### Expected behavior

`liblttng-ust1` should be a dependency when installing `dotnet` from the apt repo

### Actual behavior

It does not get installed.

**Comment by jkoritzinsky** [comment]
Right now, the Microsoft build of .NET does not explicitly require libttng-ust packages to be installed. The support for LTTNG lights up when the packages are available.

When using the build of .NET that Ubuntu provides in the default repositories for Ubuntu, the dependency should be present on the package metadata (and cause it to auto-install).

@hoyosjs this is related to what we were discussing offline last week.

**Comment by externl** [comment]
> The support for LTTNG lights up when the packages are available.

Unfortunately [System.Net.Quic](https://learn.microsoft.com/en-us/dotnet/api/system.net.quic?view=net-7.0) seems to rely on this being installed, and it's not so obvious why it doesn't work when it's not installed.

The MS documentation doesn't mention anywhere that this is an optional dependency.

**Comment by jkotas** [comment]
If msquic package depends on liblttng, it should declare it as a dependency. This should be transfered to https://github.com/microsoft/msquic

**Comment by jkotas** [comment]
cc @wfurt Is there a known issue with msquic dependency on lttng?

**Comment by externl** [comment]
> If msquic package depends on liblttng, it should declare it as a dependency. This should be transfered to https://github.com/microsoft/msquic

The dotnet documentation should also be updated to indicate that ` libttng-ust` is not a required dependency and it not installed automatically.

**Comment by wfurt** [comment]
AFAIK letting was soft dependency. We only encountered problem with `libnuma` and the fix was submitted to msquic but not related. 
@nibanks would know.

cc: @CarnaViire @ManickaP

**Comment by wfurt** [comment]
this should be fixed by new MsQuic 2.2.2 package.
