### ISSUE TITLE
Handle dotnet/extensions scenarios for HttpClient logging

### ISSUE THREAD

**Issue by noahfalk** [dotnet/runtime#87247]
dotnet/extensions introduces new logging middleware for HttpClient that is different than the default logging. Ideally we want an experience that composes or upgrades, not two implementations that differ along a variety of axes.

We expect the best way to get there is to be able to selectively disable the built-in logging and then adjust dotnet/extensions' API and behavior so that users feel like they have opted into more features (as opposed to different features). This issue tracks:
- [ ] - Being able to disable default logging (https://github.com/dotnet/runtime/issues/85840)
- [ ] - Designing changes to the dotnet/extensions APIs.

cc @geeknoid @dpk83 @JamesNK

**Comment by CarnaViire** [comment]
@noahfalk should we close this as a dupe of https://github.com/dotnet/runtime/issues/77312?

**Comment by noahfalk** [comment]
Yeah, thats fine 👍
