### ISSUE TITLE
Handle dotnet/extensions scenarios in HttpClient metrics middleware

### ISSUE THREAD

**Issue by noahfalk** [dotnet/runtime#87245]
We recently added metrics middleware support to HttpClient, and dotnet/extensions also introduced alternative middleware. Ideally we handle that in a way that feels like customization or composition, not just picking between multiple alternative implementations that differ along multiple dimensions.

The important things dotnet/extensions wants to support:
- Enriching the metrics with additional custom tags
- Changing the metric name and tag names to support alternate naming schemas

cc @geeknoid @dpk83 @JamesNK @antonfirsov

**Comment by JamesNK** [comment]
Document that integrates new metrics APIs with dotnet/extensions is written and has ongoing internal review. Any changes that come from discussion can be logged as new issues.
