### ISSUE TITLE
The ETW event generated by EventSource.SendManifest is lost at receiver due to size limit when extended data is appended

### ISSUE THREAD

**Issue by ms-hujia** [dotnet/runtime#87255]
### Description

For [EventSource.SendManifest](https://github.com/dotnet/runtime/blob/90b416a511564b109d6e9f4534f2de86cab7dd0c/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs#L2796), the current `ManifestEnvelope.MaxChunkSize` used is `0xFF00`. In extended data is requested at receiver (e.g., ContainerId), the ETW event will exceed the ETW limit (0xFFFF), which causes the event lost and all events from the ETW provider unable to be analyzed. 

### Reproduction Steps

At sender, using an `EventSource` which has hundreds of events so its manifest will be larger than 64K. Emit an event in container.

At receiver, using `TraceEventSession` with `EnableSourceContainerTracking` set.

### Expected behavior

PerfView can analyze the .etl file correctly.

### Actual behavior

PerfView report events lost and cannot analyze the event correctly. Event name and message are missing.

### Known Workarounds

At receiver, don't set  `EnableSourceContainerTracking`.

**Comment by tommcdon** [comment]
@ms-hujia, thanks for filling this issue!  

> For [EventSource.SendManifest](https://github.com/dotnet/runtime/blob/90b416a511564b109d6e9f4534f2de86cab7dd0c/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs#L2796), the current `ManifestEnvelope.MaxChunkSize` used is `0xFF00`. In extended data is requested at receiver (e.g., ContainerId), the ETW event will exceed the ETW limit (0xFFFF), which causes the event lost and all events from the ETW provider unable to be analyzed.

Adding @brianrob @davmason for thoughts.   I am curious why the ETW manifest isn't being sliced into multiple chunks.

> At receiver, using TraceEventSession with EnableSourceContainerTracking set.
@ms-hujia do you have a requirement to enable `EnableSourceContainerTracking`?

**Comment by brianrob** [comment]
The manifest should be sliced into chunks, but it sounds like the math to determine event size is including the extended data, which in this case includes the container ID and might just be pushing the chunk over the edge.  A quick way to confirm this is to reduce the max chunk size and try again.  If things work, then we know that we just need to reduce the size to account for the container ID and anything else that might be added as extended data.
