### ISSUE TITLE
[mono] Tests failing with `Failed to find compatible device: arm64-v8a`

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/runtime#87267]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=298055

Build error leg:
- linux_bionic-arm64 Release AllSubsets_Mono

Tests failing: 
- Microsoft.Bcl.AsyncInterfaces.Tests.WorkItemExecution
- Microsoft.Extensions.DependencyInjection.ExternalContainers.Tests.WorkItemExecution
- System.Diagnostics.DiagnosticSource.Switches.Tests.WorkItemExecution
- System.IO.Pipes.Tests.WorkItemExecution
- System.Linq.Queryable.Tests.WorkItemExecution

Pull request: https://github.com/dotnet/runtime/pull/86652

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step).

```json
{
  "ErrorMessage": "crit: Failed to find compatible device: arm64-v8a",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[476263](https://dev.azure.com/dnceng-public/public/_build/results?buildId=476263)|dotnet/runtime|[Microsoft.VisualBasic.Core.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=476263&view=ms.vss-test-web.build-test-results-tab&runId=10890316&resultId=160574)||
|[476004](https://dev.azure.com/dnceng-public/public/_build/results?buildId=476004)|dotnet/runtime|[Microsoft.XmlSerializer.Generator.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=476004&view=ms.vss-test-web.build-test-results-tab&runId=10882472&resultId=181478)||
|[472380](https://dev.azure.com/dnceng-public/public/_build/results?buildId=472380)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=472380&view=ms.vss-test-web.build-test-results-tab&runId=10880034&resultId=163472)|dotnet/runtime#94844|
|[475900](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475900)|dotnet/runtime|[Microsoft.Extensions.FileProviders.Composite.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475900&view=ms.vss-test-web.build-test-results-tab&runId=10879730&resultId=175798)||
|[475292](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475292)|dotnet/runtime|[Microsoft.Extensions.Configuration.Binder.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475292&view=ms.vss-test-web.build-test-results-tab&runId=10865856&resultId=164946)||
|[475327](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475327)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475327&view=ms.vss-test-web.build-test-results-tab&runId=10863756&resultId=169329)||
|[475076](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475076)|dotnet/runtime|[Microsoft.Extensions.Configuration.Binder.SourceGeneration.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475076&view=ms.vss-test-web.build-test-results-tab&runId=10853240&resultId=172049)||
|[474832](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474832)|dotnet/runtime|[System.Composition.AttributeModel.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474832&view=ms.vss-test-web.build-test-results-tab&runId=10846722&resultId=169310)||
|[471584](https://dev.azure.com/dnceng-public/public/_build/results?buildId=471584)|dotnet/runtime|[System.Threading.ThreadPool.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=471584&view=ms.vss-test-web.build-test-results-tab&runId=10748570&resultId=181234)||
|[471508](https://dev.azure.com/dnceng-public/public/_build/results?buildId=471508)|dotnet/runtime|[System.Text.RegularExpressions.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=471508&view=ms.vss-test-web.build-test-results-tab&runId=10746802&resultId=166430)||
|[471393](https://dev.azure.com/dnceng-public/public/_build/results?buildId=471393)|dotnet/runtime|[System.Xml.RW.CustomReader.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=471393&view=ms.vss-test-web.build-test-results-tab&runId=10742302&resultId=179742)||
|[471313](https://dev.azure.com/dnceng-public/public/_build/results?buildId=471313)|dotnet/runtime|[System.Threading.RateLimiting.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=471313&view=ms.vss-test-web.build-test-results-tab&runId=10740338&resultId=171982)||
|[470965](https://dev.azure.com/dnceng-public/public/_build/results?buildId=470965)|dotnet/runtime|[System.Threading.RateLimiting.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=470965&view=ms.vss-test-web.build-test-results-tab&runId=10730420&resultId=168625)|dotnet/runtime#93220|
|[470621](https://dev.azure.com/dnceng-public/public/_build/results?buildId=470621)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=470621&view=ms.vss-test-web.build-test-results-tab&runId=10720144&resultId=153506)||
|[470544](https://dev.azure.com/dnceng-public/public/_build/results?buildId=470544)|dotnet/runtime|[System.Security.Cryptography.Xml.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=470544&view=ms.vss-test-web.build-test-results-tab&runId=10716060&resultId=159994)||
|[470317](https://dev.azure.com/dnceng-public/public/_build/results?buildId=470317)|dotnet/runtime|[System.Security.Cryptography.Xml.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=470317&view=ms.vss-test-web.build-test-results-tab&runId=10708000&resultId=181139)||
|[470325](https://dev.azure.com/dnceng-public/public/_build/results?buildId=470325)|dotnet/runtime|[System.Xml.Linq.Axes.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=470325&view=ms.vss-test-web.build-test-results-tab&runId=10707880&resultId=180933)||
|[469832](https://dev.azure.com/dnceng-public/public/_build/results?buildId=469832)|dotnet/runtime|[System.Runtime.Serialization.Json.ReflectionOnly.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=469832&view=ms.vss-test-web.build-test-results-tab&runId=10694254&resultId=170281)||
|[469799](https://dev.azure.com/dnceng-public/public/_build/results?buildId=469799)|dotnet/runtime|[System.Threading.Tasks.Dataflow.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=469799&view=ms.vss-test-web.build-test-results-tab&runId=10692230&resultId=161495)||
|[469455](https://dev.azure.com/dnceng-public/public/_build/results?buildId=469455)|dotnet/runtime|[System.Threading.Tasks.Dataflow.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=469455&view=ms.vss-test-web.build-test-results-tab&runId=10682740&resultId=167034)||
|[469234](https://dev.azure.com/dnceng-public/public/_build/results?buildId=469234)|dotnet/runtime|[System.Threading.RateLimiting.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=469234&view=ms.vss-test-web.build-test-results-tab&runId=10675984&resultId=153272)||
|[468967](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468967)|dotnet/runtime|[System.Xml.RW.SubtreeReader.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468967&view=ms.vss-test-web.build-test-results-tab&runId=10668558&resultId=181390)||
|[468943](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468943)|dotnet/runtime|[System.Security.Cryptography.ProtectedData.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468943&view=ms.vss-test-web.build-test-results-tab&runId=10667976&resultId=164192)||
|[468844](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468844)|dotnet/runtime|[System.Xml.Linq.Misc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468844&view=ms.vss-test-web.build-test-results-tab&runId=10665346&resultId=180872)||
|[468831](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468831)|dotnet/runtime|[System.Threading.Tasks.Extensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468831&view=ms.vss-test-web.build-test-results-tab&runId=10664926&resultId=182516)||
|[468599](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468599)|dotnet/runtime|[System.Threading.Tasks.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468599&view=ms.vss-test-web.build-test-results-tab&runId=10657568&resultId=182269)||
|[468590](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468590)|dotnet/runtime|[System.Xml.RW.NameTable.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468590&view=ms.vss-test-web.build-test-results-tab&runId=10657414&resultId=180648)||
|[468420](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468420)|dotnet/runtime|[System.Threading.Channels.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468420&view=ms.vss-test-web.build-test-results-tab&runId=10652824&resultId=168209)||
|[468095](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468095)|dotnet/runtime|[System.Xml.RW.CustomReader.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468095&view=ms.vss-test-web.build-test-results-tab&runId=10643244&resultId=181400)||
|[467978](https://dev.azure.com/dnceng-public/public/_build/results?buildId=467978)|dotnet/runtime|[System.ValueTuple.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=467978&view=ms.vss-test-web.build-test-results-tab&runId=10639388&resultId=181875)||
|[467759](https://dev.azure.com/dnceng-public/public/_build/results?buildId=467759)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=467759&view=ms.vss-test-web.build-test-results-tab&runId=10632750&resultId=166720)|dotnet/runtime#94602|
|[467535](https://dev.azure.com/dnceng-public/public/_build/results?buildId=467535)|dotnet/runtime|[System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=467535&view=ms.vss-test-web.build-test-results-tab&runId=10627732&resultId=174918)||
|[467341](https://dev.azure.com/dnceng-public/public/_build/results?buildId=467341)|dotnet/runtime|[System.Threading.Channels.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=467341&view=ms.vss-test-web.build-test-results-tab&runId=10619616&resultId=172811)||
|[467123](https://dev.azure.com/dnceng-public/public/_build/results?buildId=467123)|dotnet/runtime|[System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=467123&view=ms.vss-test-web.build-test-results-tab&runId=10612784&resultId=175809)||
|[466947](https://dev.azure.com/dnceng-public/public/_build/results?buildId=466947)|dotnet/runtime|[System.Web.HttpUtility.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=466947&view=ms.vss-test-web.build-test-results-tab&runId=10609058&resultId=182798)||
|[466956](https://dev.azure.com/dnceng-public/public/_build/results?buildId=466956)|dotnet/runtime|[System.Threading.RateLimiting.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=466956&view=ms.vss-test-web.build-test-results-tab&runId=10606486&resultId=172640)||
|[466670](https://dev.azure.com/dnceng-public/public/_build/results?buildId=466670)|dotnet/runtime|[System.Threading.Tasks.Parallel.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=466670&view=ms.vss-test-web.build-test-results-tab&runId=10598334&resultId=175652)||
|[466386](https://dev.azure.com/dnceng-public/public/_build/results?buildId=466386)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=466386&view=ms.vss-test-web.build-test-results-tab&runId=10590892&resultId=170719)||
|[466152](https://dev.azure.com/dnceng-public/public/_build/results?buildId=466152)|dotnet/runtime|[System.Threading.Tasks.Parallel.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=466152&view=ms.vss-test-web.build-test-results-tab&runId=10590490&resultId=182745)||
|[462819](https://dev.azure.com/dnceng-public/public/_build/results?buildId=462819)|dotnet/runtime|[Microsoft.Extensions.Http.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=462819&view=ms.vss-test-web.build-test-results-tab&runId=10480386&resultId=182748)||
|[462611](https://dev.azure.com/dnceng-public/public/_build/results?buildId=462611)|dotnet/runtime|[System.CodeDom.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=462611&view=ms.vss-test-web.build-test-results-tab&runId=10470788&resultId=180049)||
|[462515](https://dev.azure.com/dnceng-public/public/_build/results?buildId=462515)|dotnet/runtime|[System.CodeDom.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=462515&view=ms.vss-test-web.build-test-results-tab&runId=10466298&resultId=161286)||
|[462059](https://dev.azure.com/dnceng-public/public/_build/results?buildId=462059)|dotnet/runtime|[Microsoft.Bcl.AsyncInterfaces.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=462059&view=ms.vss-test-web.build-test-results-tab&runId=10451298&resultId=181881)||
|[461730](https://dev.azure.com/dnceng-public/public/_build/results?buildId=461730)|dotnet/runtime|[Microsoft.Extensions.FileProviders.Composite.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=461730&view=ms.vss-test-web.build-test-results-tab&runId=10440656&resultId=162745)||
|[458877](https://dev.azure.com/dnceng-public/public/_build/results?buildId=458877)|dotnet/runtime|[Microsoft.XmlSerializer.Generator.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=458877&view=ms.vss-test-web.build-test-results-tab&runId=10347782&resultId=164928)||
|[458245](https://dev.azure.com/dnceng-public/public/_build/results?buildId=458245)|dotnet/runtime|[System.Diagnostics.Contracts.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=458245&view=ms.vss-test-web.build-test-results-tab&runId=10327060&resultId=153512)||
|[457943](https://dev.azure.com/dnceng-public/public/_build/results?buildId=457943)|dotnet/runtime|[Microsoft.Extensions.Configuration.EnvironmentVariables.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=457943&view=ms.vss-test-web.build-test-results-tab&runId=10315956&resultId=173469)||
|[457916](https://dev.azure.com/dnceng-public/public/_build/results?buildId=457916)|dotnet/runtime|[Microsoft.Extensions.Configuration.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=457916&view=ms.vss-test-web.build-test-results-tab&runId=10314856&resultId=177521)|dotnet/runtime#94274|
|[457319](https://dev.azure.com/dnceng-public/public/_build/results?buildId=457319)|dotnet/runtime|[System.ComponentModel.EventBasedAsync.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=457319&view=ms.vss-test-web.build-test-results-tab&runId=10299284&resultId=175496)||
|[456975](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456975)|dotnet/runtime|[Microsoft.Extensions.FileProviders.Composite.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456975&view=ms.vss-test-web.build-test-results-tab&runId=10288198&resultId=164370)||
|[456789](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456789)|dotnet/runtime|[System.AppContext.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456789&view=ms.vss-test-web.build-test-results-tab&runId=10283378&resultId=181462)||
|[456721](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456721)|dotnet/runtime|[System.Buffers.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456721&view=ms.vss-test-web.build-test-results-tab&runId=10281522&resultId=172356)|dotnet/runtime#94038|
|[456534](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456534)|dotnet/runtime|[Microsoft.Extensions.Options.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456534&view=ms.vss-test-web.build-test-results-tab&runId=10275222&resultId=182764)||
|[456177](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456177)|dotnet/runtime|[System.Threading.Tasks.Extensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456177&view=ms.vss-test-web.build-test-results-tab&runId=10265536&resultId=157866)||
|[455954](https://dev.azure.com/dnceng-public/public/_build/results?buildId=455954)|dotnet/runtime|[System.Threading.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=455954&view=ms.vss-test-web.build-test-results-tab&runId=10257024&resultId=182179)||
|[455930](https://dev.azure.com/dnceng-public/public/_build/results?buildId=455930)|dotnet/runtime|[System.Threading.Tasks.Parallel.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=455930&view=ms.vss-test-web.build-test-results-tab&runId=10256658&resultId=176831)||
|[455771](https://dev.azure.com/dnceng-public/public/_build/results?buildId=455771)|dotnet/runtime|[System.Runtime.Serialization.Schema.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=455771&view=ms.vss-test-web.build-test-results-tab&runId=10251710&resultId=158624)||
|[455739](https://dev.azure.com/dnceng-public/public/_build/results?buildId=455739)|dotnet/runtime|[System.Threading.Tasks.Parallel.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=455739&view=ms.vss-test-web.build-test-results-tab&runId=10250338&resultId=182138)||
|[455556](https://dev.azure.com/dnceng-public/public/_build/results?buildId=455556)|dotnet/runtime|[System.Threading.RateLimiting.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=455556&view=ms.vss-test-web.build-test-results-tab&runId=10243322&resultId=181926)||
|[455375](https://dev.azure.com/dnceng-public/public/_build/results?buildId=455375)|dotnet/runtime|[System.Text.Encoding.Extensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=455375&view=ms.vss-test-web.build-test-results-tab&runId=10238468&resultId=166629)|dotnet/runtime#94038|
|[454951](https://dev.azure.com/dnceng-public/public/_build/results?buildId=454951)|dotnet/runtime|[System.Threading.Overlapped.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=454951&view=ms.vss-test-web.build-test-results-tab&runId=10225250&resultId=167974)||
|[454774](https://dev.azure.com/dnceng-public/public/_build/results?buildId=454774)|dotnet/runtime|[System.Threading.RateLimiting.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=454774&view=ms.vss-test-web.build-test-results-tab&runId=10218588&resultId=172608)||
|[454509](https://dev.azure.com/dnceng-public/public/_build/results?buildId=454509)|dotnet/runtime|[System.Threading.Channels.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=454509&view=ms.vss-test-web.build-test-results-tab&runId=10211306&resultId=169701)||
|[454434](https://dev.azure.com/dnceng-public/public/_build/results?buildId=454434)|dotnet/runtime|[System.Threading.Tasks.Extensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=454434&view=ms.vss-test-web.build-test-results-tab&runId=10207118&resultId=176669)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|8|64|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=323893
**Error message validated:** `crit: Failed to find compatible device: arm64-v8a`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 6/28/2023 9:22:27 PM UTC

**Comment by jakobbotsch** [comment]
@ivanpovazan I think this log statement is from

**Comment by jakobbotsch** [comment]
I don't think there is an issue related to that log statement and I don't think it causes the work items to fail. So you should look for other failures in the logs. E.g. in
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-86652-merge-1c9c9cfd4ebd4ec7b3/System.IO.Pipes.Tests/1/console.5b1e5bba.log?helixlogtype=result
(for the System.IO.Pipelines failure in net8.0-linux-Release-arm64-Mono_Release_LinuxBionic-Windows.10.Amd64.Android.Open), the log ends with "ERROR: The process "corerun.exe" not found.", but the actual failure is above that:
```scala
[02:00:43] info: An error occurred running System.IO.Pipes.Tests.sh
[02:00:43] dbug: Exit code: 1
                 Std out:
                   Discovering: System.IO.Pipes.Tests (method display = ClassAndMethod, method display options = None)
                   Discovered:  System.IO.Pipes.Tests (found 107 of 538 test cases)
                   Starting:    System.IO.Pipes.Tests (parallel test collections = on, max threads = 8)
                       System.UnauthorizedAccessException : Access to the path '/data/local/tmp/CoreFxPipe_g2n3xo52.px0' is denied.
                       Stack Trace:
                         /_/src/libraries/System.IO.Pipes/src/System/IO/Pipes/NamedPipeServerStream.Unix.cs(336,0): at System.IO.Pipes.NamedPipeServerStream.SharedServer..ctor(String path, Int32 maxCount, Boolean isFirstPipeInstance)
                         /_/src/libraries/System.IO.Pipes/src/System/IO/Pipes/NamedPipeServerStream.Unix.cs(279,0): at System.IO.Pipes.NamedPipeServerStream.SharedServer.Get(String path, Int32 maxCount, PipeOptions pipeOptions)
                         /_/src/libraries/System.IO.Pipes/src/System/IO/Pipes/NamedPipeServerStream.Unix.cs(43,0): at System.IO.Pipes.NamedPipeServerStream.Create(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, HandleInheritability inheritability)
                         /_/src/libraries/System.IO.Pipes/src/System/IO/Pipes/NamedPipeServerStream.cs(82,0): at System.IO.Pipes.NamedPipeServerStream..ctor(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, HandleInheritability inheritability)
                         /_/src/libraries/System.IO.Pipes/src/System/IO/Pipes/NamedPipeServerStream.cs(39,0): at System.IO.Pipes.NamedPipeServerStream..ctor(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options)
                         /_/src/libraries/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.CreateServer.cs(263,0): at System.IO.Pipes.Tests.NamedPipeTest_CreateServer.PipeOptions_FirstPipeInstanceWithSameNameReuse_Throws_UnauthorizedAccessException()
                         /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodInvoker.Mono.cs(30,0): at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, IntPtr* args)
                         /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs(59,0): at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
                   Finished:    System.IO.Pipes.Tests
                 === TEST EXECUTION SUMMARY ===
                    System.IO.Pipes.Tests  Total: 150, Errors: 0, Failed: 1, Skipped: 0, Time: 2.364s
                 
                 
                 Std err:
                     System.IO.Pipes.Tests.NamedPipeTest_CreateServer.PipeOptions_FirstPipeInstanceWithSameNameReuse_Throws_UnauthorizedAccessException [FAIL]
```

So for example you could use `System.IO.Pipes.Tests.NamedPipeTest_CreateServer.PipeOptions_FirstPipeInstanceWithSameNameReuse_Throws_UnauthorizedAccessException [FAIL]` as the error message in the known error template. Using "ERROR: The process \"corerun.exe\" not found",` is causing tons of unrelated PRs to be linked to this issue.

**Comment by ivanpovazan** [comment]
Thank you very much for the detailed explanation, and sorry for the confusion.

This issue seems to be related to a missing device on `linux_bionic-arm64 Release AllSubsets_Mono`, while on the `linux_bionic-x64 Release AllSubsets_Mono` (note the difference in architecture) there is the failing test @jakobbotsch noted above:
> System.IO.Pipes.Tests.NamedPipeTest_CreateServer.PipeOptions_FirstPipeInstanceWithSameNameReuse_Throws_UnauthorizedAccessException [FAIL]

I will create a separate tracking issue as these don't seem to be related.
