### ISSUE TITLE
System.Net.Requests.Tests, System.Net.Security.Tests failing with `Segmentation fault` on Debian 10

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/runtime#87268]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=298055

Build error legs: 
- linux-x64 Release NativeAOT_Checked_Libs_SizeOpt
- linux-x64 Release NativeAOT_Checked_Libs_SpeedOpt

Tests failing: 
- System.Net.Requests.Tests
- System.Net.Security.Tests

Pull request: https://github.com/dotnet/runtime/pull/86652

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "25 Segmentation fault      (core dumped) ./System.Net.Requests.Tests",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[299406](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299406)|dotnet/runtime|Build and Package|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/299406/logs/1405)|dotnet/runtime#87148|
|[299407](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299407)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/299407/logs/100)|dotnet/runtime#87148|

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[299800](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299800)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299800&view=ms.vss-test-web.build-test-results-tab&runId=6072986&resultId=151952)||
|[299568](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299568)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299568&view=ms.vss-test-web.build-test-results-tab&runId=6067676&resultId=120379)||
|[299541](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299541)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299541&view=ms.vss-test-web.build-test-results-tab&runId=6067296&resultId=120379)|dotnet/runtime#87261|
|[299567](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299567)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299567&view=ms.vss-test-web.build-test-results-tab&runId=6067322&resultId=141808)||
|[299732](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299732)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299732&view=ms.vss-test-web.build-test-results-tab&runId=6070732&resultId=104399)||
|[299728](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299728)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299728&view=ms.vss-test-web.build-test-results-tab&runId=6070516&resultId=104399)||
|[299741](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299741)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299741&view=ms.vss-test-web.build-test-results-tab&runId=6070444&resultId=104420)||
|[299742](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299742)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299742&view=ms.vss-test-web.build-test-results-tab&runId=6070452&resultId=104420)||
|[299731](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299731)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299731&view=ms.vss-test-web.build-test-results-tab&runId=6070342&resultId=104437)||
|[299730](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299730)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299730&view=ms.vss-test-web.build-test-results-tab&runId=6070408&resultId=104435)||
|[299729](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299729)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299729&view=ms.vss-test-web.build-test-results-tab&runId=6070354&resultId=104437)||
|[299727](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299727)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299727&view=ms.vss-test-web.build-test-results-tab&runId=6070308&resultId=104435)||
|[299720](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299720)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299720&view=ms.vss-test-web.build-test-results-tab&runId=6070240&resultId=104437)||
|[299718](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299718)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299718&view=ms.vss-test-web.build-test-results-tab&runId=6070208&resultId=104437)||
|[299592](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299592)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299592&view=ms.vss-test-web.build-test-results-tab&runId=6066924&resultId=202040)|dotnet/runtime#86843|
|[298109](https://dev.azure.com/dnceng-public/public/_build/results?buildId=298109)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=298109&view=ms.vss-test-web.build-test-results-tab&runId=6066868&resultId=201995)|dotnet/runtime#86578|
|[299527](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299527)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299527&view=ms.vss-test-web.build-test-results-tab&runId=6066078&resultId=202040)|dotnet/runtime#86546|
|[297387](https://dev.azure.com/dnceng-public/public/_build/results?buildId=297387)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=297387&view=ms.vss-test-web.build-test-results-tab&runId=6065528&resultId=201995)|dotnet/runtime#87189|
|[299514](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299514)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299514&view=ms.vss-test-web.build-test-results-tab&runId=6065450&resultId=201140)||
|[299429](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299429)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299429&view=ms.vss-test-web.build-test-results-tab&runId=6063740&resultId=112511)||
|[299427](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299427)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299427&view=ms.vss-test-web.build-test-results-tab&runId=6064236&resultId=120377)||
|[299396](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299396)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299396&view=ms.vss-test-web.build-test-results-tab&runId=6063458&resultId=120378)||
|[298623](https://dev.azure.com/dnceng-public/public/_build/results?buildId=298623)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=298623&view=ms.vss-test-web.build-test-results-tab&runId=6064178&resultId=202036)|dotnet/runtime#86759|
|[299397](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299397)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299397&view=ms.vss-test-web.build-test-results-tab&runId=6063462&resultId=120380)||
|[299365](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299365)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299365&view=ms.vss-test-web.build-test-results-tab&runId=6062334&resultId=202040)|dotnet/runtime#87204|
|[299242](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299242)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299242&view=ms.vss-test-web.build-test-results-tab&runId=6060996&resultId=120378)||
|[298991](https://dev.azure.com/dnceng-public/public/_build/results?buildId=298991)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=298991&view=ms.vss-test-web.build-test-results-tab&runId=6061914&resultId=202036)|dotnet/runtime#87209|
|[299244](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299244)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299244&view=ms.vss-test-web.build-test-results-tab&runId=6060246&resultId=202100)|dotnet/runtime#87099|
|[299225](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299225)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299225&view=ms.vss-test-web.build-test-results-tab&runId=6059828&resultId=202040)|dotnet/runtime#87198|
|[299206](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299206)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299206&view=ms.vss-test-web.build-test-results-tab&runId=6059590&resultId=202042)|dotnet/runtime#87065|
|[299181](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299181)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299181&view=ms.vss-test-web.build-test-results-tab&runId=6058654&resultId=202040)|dotnet/runtime#87237|
|[298055](https://dev.azure.com/dnceng-public/public/_build/results?buildId=298055)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=298055&view=ms.vss-test-web.build-test-results-tab&runId=6059452&resultId=136329)|dotnet/runtime#86652|
|[299037](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299037)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299037&view=ms.vss-test-web.build-test-results-tab&runId=6054452&resultId=148740)||
|[298966](https://dev.azure.com/dnceng-public/public/_build/results?buildId=298966)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=298966&view=ms.vss-test-web.build-test-results-tab&runId=6052732&resultId=198698)|dotnet/runtime#87233|
|[298965](https://dev.azure.com/dnceng-public/public/_build/results?buildId=298965)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=298965&view=ms.vss-test-web.build-test-results-tab&runId=6052528&resultId=203604)|dotnet/runtime#87232|
|[298677](https://dev.azure.com/dnceng-public/public/_build/results?buildId=298677)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=298677&view=ms.vss-test-web.build-test-results-tab&runId=6050144&resultId=118410)||
|[298811](https://dev.azure.com/dnceng-public/public/_build/results?buildId=298811)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=298811&view=ms.vss-test-web.build-test-results-tab&runId=6048832&resultId=203600)||
|[298918](https://dev.azure.com/dnceng-public/public/_build/results?buildId=298918)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=298918&view=ms.vss-test-web.build-test-results-tab&runId=6051326&resultId=182514)|dotnet/runtime#87230|
|[298816](https://dev.azure.com/dnceng-public/public/_build/results?buildId=298816)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=298816&view=ms.vss-test-web.build-test-results-tab&runId=6050204&resultId=141832)||
|[298414](https://dev.azure.com/dnceng-public/public/_build/results?buildId=298414)|dotnet/runtime|[ComInterfaceGenerator.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=298414&view=ms.vss-test-web.build-test-results-tab&runId=6039316&resultId=207294)|dotnet/runtime#87125|
|[297910](https://dev.azure.com/dnceng-public/public/_build/results?buildId=297910)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=297910&view=ms.vss-test-web.build-test-results-tab&runId=6023020&resultId=118410)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|35|43|43|

**Comment by ivanpovazan** [comment]
Updated the search term to use `ErrorPattern` instead, as the initial `"ErrorMessage": "Segmentation fault"` was too broad

**Comment by jkotas** [comment]
> https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=298055

System.Net.Quic.Functional.Tests is known issue #87275.

System.Net.Requests.Tests is crashing is crashing in libcrypto.so.1.1 initialization on Debian 10. I do not think it has anything to do with the size/speed opt configs, we just happened to hit this problem in these configs first.

Unfortunately, it is not possible to get accurate stacktrace to debug this further since Debian does not publish symbols for security updates (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=894081). 

We do not support Debian 10 for .NET 8 according to https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md#linux . We should "fix this" by deleting Debian 10 test runs for .NET 8.

```
#0  0x000000000008bb56 in ?? ()                                                                                                                                                                                             #1  0x00007f8f8aea1cb0 in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1                                                                                                                                             #2  0x00007f8f8ae30017 in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1                                                                                                                                             #3  0x00007f8f88d18f48 in ?? () from /usr/lib/x86_64-linux-gnu/libssl.so.1.1                                                                                                                                                #4  0x00007fd02726e34a in call_init (l=0x563d7fe57920, argc=argc@entry=9, argv=argv@entry=0x7fffd8bbf948, env=env@entry=0x7fffd8bbf998) at dl-init.c:58                                                                     #5  0x00007fd02726e486 in call_init (env=0x7fffd8bbf998, argv=0x7fffd8bbf948, argc=9, l=<optimized out>) at dl-init.c:30                                                                                                    #6  _dl_init (main_map=main_map@entry=0x7f8f7800a270, argc=9, argv=0x7fffd8bbf948, env=0x7fffd8bbf998) at dl-init.c:119                                                                                                     #7  0x00007fd0272722e3 in dl_open_worker (a=a@entry=0x7f8f895a3d80) at dl-open.c:517                                                                                                                                        #8  0x00007fd026ffa8cf in __GI__dl_catch_exception (exception=exception@entry=0x7f8f895a3d60, operate=operate@entry=0x7fd027271f70 <dl_open_worker>, args=args@entry=0x7f8f895a3d80) at dl-error-skeleton.c:196             #9  0x00007fd027271bca in _dl_open (file=0x563d7d7efebb "libssl.so.1.1", mode=-2147483647, caller_dlopen=0x563d7dc62c5c, nsid=<optimized out>, argc=9, argv=0x7fffd8bbf948, env=0x7fffd8bbf998) at dl-open.c:599            #10 0x00007fd027253256 in dlopen_doit (a=a@entry=0x7f8f895a3fa0) at dlopen.c:66                                                                                                                                             #11 0x00007fd026ffa8cf in __GI__dl_catch_exception (exception=exception@entry=0x7f8f895a3f40, operate=operate@entry=0x7fd027253200 <dlopen_doit>, args=args@entry=0x7f8f895a3fa0) at dl-error-skeleton.c:196                #12 0x00007fd026ffa95f in __GI__dl_catch_error (objname=objname@entry=0x7f8f78009170, errstring=errstring@entry=0x7f8f78009178, mallocedp=mallocedp@entry=0x7f8f78009168,                                                       operate=operate@entry=0x7fd027253200 <dlopen_doit>, args=args@entry=0x7f8f895a3fa0) at dl-error-skeleton.c:215                                                                                                          #13 0x00007fd027253995 in _dlerror_run (operate=operate@entry=0x7fd027253200 <dlopen_doit>, args=args@entry=0x7f8f895a3fa0) at dlerror.c:170                                                                                #14 0x00007fd0272532e6 in __dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:87                                                                                                                              #15 0x0000563d7dc62c5c in ?? ()                                                                                                                                                                                             #16 0x00007fd027095997 in __pthread_once_slow (once_control=0x563d7e618b68, init_routine=0x563d7dc62b80) at pthread_once.c:116                                                                                              #17 0x0000563d7dc62d99 in InitializeOpenSSLShim ()                                                                                                                                                                          #18 0x0000563d7dc5bd8f in ?? ()                                                                                                                                                                                             #19 0x00007fd027095997 in __pthread_once_slow (once_control=0x563d7e618b2c, init_routine=0x563d7dc5bd80) at pthread_once.c:116                                                                                              #20 0x0000563d7dc5bd77 in CryptoNative_EnsureOpenSslInitialized ()                                                                                                                                                          #21 0x0000563d7df5a4df in TestUtilities_Interop_CryptoInitializer__EnsureOpenSslInitialized ()                                                                                                                              #22 0x0000563d7df5a469 in TestUtilities_Interop_CryptoInitializer___cctor ()                                                                                                                                                #23 0x0000563d7dee317e in S_P_CoreLib_System_Runtime_CompilerServices_ClassConstructorRunner__EnsureClassConstructorRun ()                                                                                                  #24 0x0000563d7dee309d in S_P_CoreLib_System_Runtime_CompilerServices_ClassConstructorRunner__CheckStaticClassConstructionReturnNonGCStaticBase ()                                                                          #25 0x0000563d7df5a3a9 in TestUtilities_Interop_OpenSsl___cctor ()   
```
