### ISSUE TITLE
string.Format throws FormatException on Mac Catalyst/ARM64

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#87277]
### Description

Calling string.Format with a string of at least 8 character triggers a FormatException.

### Reproduction Steps

Repro:

1. Create a Mac Catalyst project, make sure TargetFramework=net8.0-maccatalyst
2. Add this to Main:

```cs
String.Format ("12345678");
```

3. Build with .NET 8 (8.0.100-preview.6.23280.13 or later) for ARM64:

```
dotnet build /p:RuntimeIdentifier=maccatalyst-arm64
```

Complete project file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-maccatalyst</TargetFramework>
		<OutputType>Exe</OutputType>
		<ApplicationId>StringFormatCrash</ApplicationId>
	</PropertyGroup>
</Project>c
```

and source code:

```cs
using System;
using Foundation;
String.Format ("12345678");
GC.KeepAlive (typeof (NSObject)); // prevent linking away the platform assembly
```

### Expected behavior

No exception.

### Actual behavior

A FormatException occurs:

```
(lldb) bt
* thread #1, name = 'tid_103', queue = 'com.apple.main-thread', stop reason = breakpoint 3.1
  * frame #0: 0x000000010473fac0 MySimpleApp`System_ThrowHelper_ThrowFormatInvalidString_int_System_ExceptionResource
    frame #1: 0x00000001047e4558 MySimpleApp`System_Text_ValueStringBuilder_AppendFormatHelper_System_IFormatProvider_string_System_ReadOnlySpan_1_object + 4040
    frame #2: 0x0000000104623a64 MySimpleApp`string_FormatHelper_System_IFormatProvider_string_System_ReadOnlySpan_1_object + 340
    frame #3: 0x00000001046235d4 MySimpleApp`string_Format_string_object__ + 212
    frame #4: 0x000000010234e8dc MySimpleApp`Program__Main__string__ + 172
    frame #5: 0x0000000104e7ee88 MySimpleApp`wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 296
    frame #6: 0x000000010efc903c libmonosgen-2.0.dylib`mono_jit_runtime_invoke + 1360
    frame #7: 0x000000010f1cad88 libmonosgen-2.0.dylib`mono_runtime_invoke_checked + 148
    frame #8: 0x000000010f1d315c libmonosgen-2.0.dylib`do_exec_main_checked + 104
    frame #9: 0x000000010f01d114 libmonosgen-2.0.dylib`mono_jit_exec + 364
    frame #10: 0x000000010e5c429c libxamarin-dotnet-debug.dylib`xamarin_main(argc=1, argv=0x000000016fdff138, launch_mode=XamarinLaunchModeApp) at monotouch-main.m:490:8
    frame #11: 0x0000000106668118 MySimpleApp`main(argc=1, argv=0x000000016fdff138) at main.arm64.mm:408:11
    frame #12: 0x00000001a8bf3f28 dyld`start + 2236
```

note that the app eventually crashes, so I got the exception in lldb (full terminal output without lldb: https://gist.github.com/rolfbjarne/99e5a6fc9d92d065e6ea58fd448e48d6)

### Regression?

Yes.

This started happening on our first bump from maestro here: https://github.com/xamarin/xamarin-macios/pull/18385

That's this bump: Microsoft.Dotnet.Sdk.Internal: [from 8.0.100-preview.6.23279.5 to 8.0.100-preview.6.23280.13](https://github.com/dotnet/installer/compare/2de0392d49...5127103b0b)

Which is this range of commits in dotnet/runtime: https://github.com/dotnet/runtime/compare/8163d1643afe2c029c1783b5f92548e6dc6828ff...bf7fb2ecbf69deb6a73bb8bbca1e56e7beec8d8a

### Known Workarounds

Be less verbose, passing 7 characters to string.Format works fine:

```cs
String.Format ("1234567");
```

### Other information

Enabling the linker also makes the app work.

Crashing app bundle: https://www.dropbox.com/s/sxy1i36vmntz4rq/MySimpleApp.zip?dl=0

**Comment by rolfbjarne** [comment]
CC @steveisok

**Comment by steveisok** [comment]
@kotlarmilos @vargaz could any of your changes in the commit range in the description have had an impact?

**Comment by vargaz** [comment]
What configuration is this using ? Is llvm enabled ? Is there a verbose build log somewhere ?

**Comment by rolfbjarne** [comment]
binlog: [build.binlog.zip](https://github.com/dotnet/runtime/files/11725238/build.binlog.zip)

**Comment by rolfbjarne** [comment]
> Is llvm enabled

No, LLVM is not enabled. In fact, enabling LLVM makes the crash go away.

**Comment by danmoseley** [comment]
This reminded me of https://github.com/dotnet/runtime/issues/78991 but that's x64 amongst other differences.

**Comment by vargaz** [comment]
Looks like this is caused by:
https://github.com/dotnet/runtime/commit/8d2c3658303e086fc3dccad4956002913d6ab64e
The problem happens when a generic method has a Vector<T> argument, and the callee uses generic sharing. The vector types used in generic shared methods, i.e. Vector<T_INT> are not treated as SIMD, so the caller passes the argument in a SIMD reg, but the caller expects it to be in a pair of normal registers.
@fanyang-mono
