### ISSUE TITLE
[mono] System.IO.Pipes.Tests test fails on `linux_bionic-x64 Release AllSubsets_Mono`

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/runtime#87279]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=298055

Build error leg:
- linux_bionic-x64 Release AllSubsets_Mono

Test failing: 
- System.IO.Pipes.Tests.NamedPipeTest_CreateServer.PipeOptions_FirstPipeInstanceWithSameNameReuse_Throws_UnauthorizedAccessException

Pull request: https://github.com/dotnet/runtime/pull/86652

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step).

```json
{
  "ErrorMessage": "System.IO.Pipes.Tests.NamedPipeTest_CreateServer.PipeOptions_FirstPipeInstanceWithSameNameReuse_Throws_UnauthorizedAccessException [FAIL]",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by kotlarmilos** [comment]
May be related to https://github.com/dotnet/runtime/issues/77469.

**Comment by akoeplinger** [comment]
This specific test was disabled as it hits issues with SELinux in https://github.com/dotnet/runtime/commit/4475c57b6b5da8bceb075dd6a5db6b622708c165
