### ISSUE TITLE
Work item tests crash on OSX x64 Debug

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#87287]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=300158
Build error leg or test failing: System.IO.FileSystem.Watcher.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/86974

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step).

```json
{
  "ErrorMessage": "END OF WORK ITEM LOG: Command exited with 127",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[475355](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475355)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475355&view=ms.vss-test-web.build-test-results-tab&runId=10866742&resultId=100100)||
|[474849](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474849)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474849&view=ms.vss-test-web.build-test-results-tab&runId=10848330&resultId=100100)||
|[474532](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474532)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474532&view=ms.vss-test-web.build-test-results-tab&runId=10836526&resultId=100100)||
|[473727](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473727)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473727&view=ms.vss-test-web.build-test-results-tab&runId=10815196&resultId=100100)||
|[473597](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473597)|dotnet/runtime|[System.IO.FileSystem.Manual.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473597&view=ms.vss-test-web.build-test-results-tab&runId=10810772&resultId=100098)||
|[473431](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473431)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473431&view=ms.vss-test-web.build-test-results-tab&runId=10804140&resultId=100100)||
|[473397](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473397)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473397&view=ms.vss-test-web.build-test-results-tab&runId=10803204&resultId=100100)||
|[472898](https://dev.azure.com/dnceng-public/public/_build/results?buildId=472898)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=472898&view=ms.vss-test-web.build-test-results-tab&runId=10790004&resultId=100100)||
|[472852](https://dev.azure.com/dnceng-public/public/_build/results?buildId=472852)|dotnet/runtime|[System.IO.Compression.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=472852&view=ms.vss-test-web.build-test-results-tab&runId=10788912&resultId=100094)||
|[472282](https://dev.azure.com/dnceng-public/public/_build/results?buildId=472282)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=472282&view=ms.vss-test-web.build-test-results-tab&runId=10770292&resultId=100100)||
|[471895](https://dev.azure.com/dnceng-public/public/_build/results?buildId=471895)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=471895&view=ms.vss-test-web.build-test-results-tab&runId=10760744&resultId=100100)||
|[471740](https://dev.azure.com/dnceng-public/public/_build/results?buildId=471740)|dotnet/runtime|[System.IO.Compression.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=471740&view=ms.vss-test-web.build-test-results-tab&runId=10756288&resultId=100094)||
|[471580](https://dev.azure.com/dnceng-public/public/_build/results?buildId=471580)|dotnet/runtime|[System.IO.FileSystem.Manual.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=471580&view=ms.vss-test-web.build-test-results-tab&runId=10750602&resultId=100098)||
|[471389](https://dev.azure.com/dnceng-public/public/_build/results?buildId=471389)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=471389&view=ms.vss-test-web.build-test-results-tab&runId=10745366&resultId=100100)||
|[470637](https://dev.azure.com/dnceng-public/public/_build/results?buildId=470637)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=470637&view=ms.vss-test-web.build-test-results-tab&runId=10721870&resultId=100100)||
|[470321](https://dev.azure.com/dnceng-public/public/_build/results?buildId=470321)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=470321&view=ms.vss-test-web.build-test-results-tab&runId=10708956&resultId=100100)||
|[469012](https://dev.azure.com/dnceng-public/public/_build/results?buildId=469012)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=469012&view=ms.vss-test-web.build-test-results-tab&runId=10671756&resultId=100100)||
|[468964](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468964)|dotnet/runtime|[System.IO.FileSystem.Primitives.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468964&view=ms.vss-test-web.build-test-results-tab&runId=10669870&resultId=100099)||
|[468841](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468841)|dotnet/runtime|[System.IO.FileSystem.Manual.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468841&view=ms.vss-test-web.build-test-results-tab&runId=10666032&resultId=100098)||
|[468587](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468587)|dotnet/runtime|[System.IO.FileSystem.Primitives.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468587&view=ms.vss-test-web.build-test-results-tab&runId=10660266&resultId=100099)||
|[468089](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468089)|dotnet/runtime|[System.IO.FileSystem.Primitives.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468089&view=ms.vss-test-web.build-test-results-tab&runId=10645496&resultId=100099)||
|[467619](https://dev.azure.com/dnceng-public/public/_build/results?buildId=467619)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=467619&view=ms.vss-test-web.build-test-results-tab&runId=10629988&resultId=100100)||
|[467146](https://dev.azure.com/dnceng-public/public/_build/results?buildId=467146)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=467146&view=ms.vss-test-web.build-test-results-tab&runId=10614346&resultId=100100)||
|[466691](https://dev.azure.com/dnceng-public/public/_build/results?buildId=466691)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=466691&view=ms.vss-test-web.build-test-results-tab&runId=10599850&resultId=100100)||
|[465768](https://dev.azure.com/dnceng-public/public/_build/results?buildId=465768)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=465768&view=ms.vss-test-web.build-test-results-tab&runId=10577590&resultId=100100)||
|[465695](https://dev.azure.com/dnceng-public/public/_build/results?buildId=465695)|dotnet/runtime|[System.IO.FileSystem.Primitives.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=465695&view=ms.vss-test-web.build-test-results-tab&runId=10574638&resultId=100099)||
|[465642](https://dev.azure.com/dnceng-public/public/_build/results?buildId=465642)|dotnet/runtime|[XUnitLogChecker.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=465642&view=ms.vss-test-web.build-test-results-tab&runId=10572886&resultId=201149)|dotnet/runtime#93906|
|[465587](https://dev.azure.com/dnceng-public/public/_build/results?buildId=465587)|dotnet/runtime|[XUnitLogChecker.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=465587&view=ms.vss-test-web.build-test-results-tab&runId=10571056&resultId=209792)|dotnet/runtime#93906|
|[465447](https://dev.azure.com/dnceng-public/public/_build/results?buildId=465447)|dotnet/runtime|[XUnitLogChecker.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=465447&view=ms.vss-test-web.build-test-results-tab&runId=10566808&resultId=209792)|dotnet/runtime#93906|
|[465319](https://dev.azure.com/dnceng-public/public/_build/results?buildId=465319)|dotnet/runtime|[System.IO.FileSystem.Primitives.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=465319&view=ms.vss-test-web.build-test-results-tab&runId=10564506&resultId=100099)||
|[465327](https://dev.azure.com/dnceng-public/public/_build/results?buildId=465327)|dotnet/runtime|[System.IO.FileSystem.Primitives.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=465327&view=ms.vss-test-web.build-test-results-tab&runId=10564164&resultId=100099)||
|[464592](https://dev.azure.com/dnceng-public/public/_build/results?buildId=464592)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=464592&view=ms.vss-test-web.build-test-results-tab&runId=10540616&resultId=100100)||
|[463142](https://dev.azure.com/dnceng-public/public/_build/results?buildId=463142)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=463142&view=ms.vss-test-web.build-test-results-tab&runId=10492704&resultId=100100)||
|[462608](https://dev.azure.com/dnceng-public/public/_build/results?buildId=462608)|dotnet/runtime|[System.IO.FileSystem.Manual.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=462608&view=ms.vss-test-web.build-test-results-tab&runId=10475760&resultId=100098)||
|[461771](https://dev.azure.com/dnceng-public/public/_build/results?buildId=461771)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=461771&view=ms.vss-test-web.build-test-results-tab&runId=10444614&resultId=100100)||
|[460596](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460596)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460596&view=ms.vss-test-web.build-test-results-tab&runId=10406878&resultId=100100)||
|[460238](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460238)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460238&view=ms.vss-test-web.build-test-results-tab&runId=10394458&resultId=100100)||
|[459941](https://dev.azure.com/dnceng-public/public/_build/results?buildId=459941)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=459941&view=ms.vss-test-web.build-test-results-tab&runId=10385134&resultId=100100)||
|[459223](https://dev.azure.com/dnceng-public/public/_build/results?buildId=459223)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=459223&view=ms.vss-test-web.build-test-results-tab&runId=10361544&resultId=100100)||
|[458289](https://dev.azure.com/dnceng-public/public/_build/results?buildId=458289)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=458289&view=ms.vss-test-web.build-test-results-tab&runId=10329738&resultId=100100)||
|[457386](https://dev.azure.com/dnceng-public/public/_build/results?buildId=457386)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=457386&view=ms.vss-test-web.build-test-results-tab&runId=10302566&resultId=100100)||
|[456786](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456786)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456786&view=ms.vss-test-web.build-test-results-tab&runId=10284924&resultId=100100)||
|[456243](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456243)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456243&view=ms.vss-test-web.build-test-results-tab&runId=10269134&resultId=100100)||
|[456245](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456245)|dotnet/runtime|[System.IO.FileSystem.Manual.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456245&view=ms.vss-test-web.build-test-results-tab&runId=10269052&resultId=100098)||
|[455009](https://dev.azure.com/dnceng-public/public/_build/results?buildId=455009)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=455009&view=ms.vss-test-web.build-test-results-tab&runId=10229458&resultId=100100)||
|[454543](https://dev.azure.com/dnceng-public/public/_build/results?buildId=454543)|dotnet/runtime|[System.IO.FileSystem.Manual.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=454543&view=ms.vss-test-web.build-test-results-tab&runId=10211412&resultId=100098)||
|[454533](https://dev.azure.com/dnceng-public/public/_build/results?buildId=454533)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=454533&view=ms.vss-test-web.build-test-results-tab&runId=10211452&resultId=100100)||
|[454134](https://dev.azure.com/dnceng-public/public/_build/results?buildId=454134)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=454134&view=ms.vss-test-web.build-test-results-tab&runId=10196572&resultId=100100)||
|[452981](https://dev.azure.com/dnceng-public/public/_build/results?buildId=452981)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=452981&view=ms.vss-test-web.build-test-results-tab&runId=10165632&resultId=100100)||
|[451747](https://dev.azure.com/dnceng-public/public/_build/results?buildId=451747)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=451747&view=ms.vss-test-web.build-test-results-tab&runId=10132244&resultId=100100)||
|[450630](https://dev.azure.com/dnceng-public/public/_build/results?buildId=450630)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=450630&view=ms.vss-test-web.build-test-results-tab&runId=10103546&resultId=100100)||
|[449186](https://dev.azure.com/dnceng-public/public/_build/results?buildId=449186)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=449186&view=ms.vss-test-web.build-test-results-tab&runId=10068126&resultId=100100)||
|[447511](https://dev.azure.com/dnceng-public/public/_build/results?buildId=447511)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=447511&view=ms.vss-test-web.build-test-results-tab&runId=10020484&resultId=100100)||
|[446965](https://dev.azure.com/dnceng-public/public/_build/results?buildId=446965)|dotnet/runtime|[System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=446965&view=ms.vss-test-web.build-test-results-tab&runId=10003866&resultId=100100)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|21|54|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=323604
**Error message validated:** `Work item System.IO.FileSystem.Watcher.Tests in job`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 6/28/2023 9:26:54 PM UTC

**Comment by Jozkee** [comment]
The logs not only show FileSystem.Watcher.Tests. I think this is a broader issue.

https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/334444/logs/123

e.g:
```
2023-07-11T00:12:22.4993970Z /Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.23313.4/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(90,5): error : Work item Common.Tests in job 9199670f-aa4c-4e8e-8150-b650ad0bb59f has failed. [/Users/runner/work/1/s/src/libraries/sendtohelixhelp.proj]
2023-07-11T00:12:22.4995970Z /Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.23313.4/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(90,5): error : Failure log: https://helix.dot.net/api/2019-06-17/jobs/9199670f-aa4c-4e8e-8150-b650ad0bb59f/workitems/Common.Tests/console [/Users/runner/work/1/s/src/libraries/sendtohelixhelp.proj]
2023-07-11T00:12:22.5108980Z ##[error].packages/microsoft.dotnet.helix.sdk/7.0.0-beta.23313.4/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(90,5): error : (NETCORE_ENGINEERING_TELEMETRY=Test) Work item Common.Tests in job 9199670f-aa4c-4e8e-8150-b650ad0bb59f has failed.
Failure log: https://helix.dot.net/api/2019-06-17/jobs/9199670f-aa4c-4e8e-8150-b650ad0bb59f/workitems/Common.Tests/console
2023-07-11T00:12:22.5122420Z /Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.23313.4/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(90,5): error : Work item IcuAppLocal.Tests in job 9199670f-aa4c-4e8e-8150-b650ad0bb59f has failed. [/Users/runner/work/1/s/src/libraries/sendtohelixhelp.proj]
2023-07-11T00:12:22.5126220Z /Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.23313.4/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(90,5): error : Failure log: https://helix.dot.net/api/2019-06-17/jobs/9199670f-aa4c-4e8e-8150-b650ad0bb59f/workitems/IcuAppLocal.Tests/console [/Users/runner/work/1/s/src/libraries/sendtohelixhelp.proj]
```

**Comment by carlossanlop** [comment]
Yea, doesn't seem to be a FileSystemWatcher-only issue. The jobs are getting unexpectedly killed, according to the console log outputs. Example:

- Log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-70-staging-9199670faa4c4e8e81/Microsoft.Bcl.AsyncInterfaces.Tests/1/console.7114ae01.log?helixlogtype=result
Output: 
```
2023-07-11T00:05:26.562Z	INFO   	run.py	run(48)	main	Beginning reading of test results.
2023-07-11T00:05:26.563Z	INFO   	run.py	__init__(42)	read_results	Searching '/private/tmp/helix/working/A8D4097B/w/9393087D/e' for test results files
2023-07-11T00:05:26.563Z	INFO   	run.py	__init__(42)	read_results	Searching '/tmp/helix/working/A8D4097B/w/9393087D/uploads' for test results files
2023-07-11T00:05:26.563Z	WARNING	run.py	__init__(55)	read_results	No results file found in any of the following formats: xunit, junit, trx
2023-07-11T00:05:26.563Z	INFO   	run.py	packing_test_reporter(30)	report_results	Packing 0 test reports to '/tmp/helix/working/A8D4097B/w/9393087D/e/__test_report.json'
2023-07-11T00:05:26.564Z	INFO   	run.py	packing_test_reporter(33)	report_results	Packed 1523 bytes
+ exit 127
['Microsoft.Bcl.AsyncInterfaces.Tests' END OF WORK ITEM LOG: Command exited with 127]
``

**Comment by akoeplinger** [comment]
A couple observations from looking through a couple results:
1. Only happens on the 7.0 branches
2. Only happens on runtime-libraries-coreclr outerloop-osx
3. The test doesn't get killed, instead it fails because `dotnet` couldn't be found: 
>./RunTests.sh: line 168: /tmp/helix/working/B2D409A4/p/dotnet: No such file or directory

**Comment by akoeplinger** [comment]
The 7.0 branch is missing this fix: https://github.com/dotnet/runtime/pull/79652

**Comment by akoeplinger** [comment]
Fixed by https://github.com/dotnet/runtime/pull/95011
