### ISSUE TITLE
Outerloop crossgen 2 failures: The file is not a ReadyToRun image

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#87299]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=299541
Build error leg or test failing: JIT.opt.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/87261

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step).

```json
{
  "ErrorMessage": "Error: System.BadImageFormatException: The file is not a ReadyToRun image",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[318594](https://dev.azure.com/dnceng-public/public/_build/results?buildId=318594)|dotnet/runtime|[JIT/Regression/JitBlue/DevDiv_255294/DevDiv_255294/DevDiv_255294.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=318594&view=ms.vss-test-web.build-test-results-tab&runId=6531036&resultId=116183)||
|[317390](https://dev.azure.com/dnceng-public/public/_build/results?buildId=317390)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=317390&view=ms.vss-test-web.build-test-results-tab&runId=6508476&resultId=117708)||
|[315024](https://dev.azure.com/dnceng-public/public/_build/results?buildId=315024)|dotnet/runtime|[JIT/Regression/JitBlue/DevDiv_255294/DevDiv_255294/DevDiv_255294.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=315024&view=ms.vss-test-web.build-test-results-tab&runId=6455530&resultId=116754)||
|[314400](https://dev.azure.com/dnceng-public/public/_build/results?buildId=314400)|dotnet/runtime|[JIT/Regression/JitBlue/DevDiv_255294/DevDiv_255294/DevDiv_255294.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=314400&view=ms.vss-test-web.build-test-results-tab&runId=6439534&resultId=158782)||
|[313103](https://dev.azure.com/dnceng-public/public/_build/results?buildId=313103)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=313103&view=ms.vss-test-web.build-test-results-tab&runId=6408080&resultId=118713)||
|[311865](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311865)|dotnet/runtime|[Regressions/coreclr/GitHub_54719/test54719/test54719.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311865&view=ms.vss-test-web.build-test-results-tab&runId=6373838&resultId=118613)||
|[311711](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311711)|dotnet/runtime|[Regressions/coreclr/GitHub_45037/test45037/test45037.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311711&view=ms.vss-test-web.build-test-results-tab&runId=6367088&resultId=118586)||
|[311712](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311712)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311712&view=ms.vss-test-web.build-test-results-tab&runId=6366592&resultId=120588)||
|[311597](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311597)|dotnet/runtime|[Regressions/coreclr/GitHub_54719/test54719/test54719.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311597&view=ms.vss-test-web.build-test-results-tab&runId=6363342&resultId=120491)||
|[311578](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311578)|dotnet/runtime|[Regressions/coreclr/GitHub_45037/test45037/test45037.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311578&view=ms.vss-test-web.build-test-results-tab&runId=6361720&resultId=118613)||
|[311497](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311497)|dotnet/runtime|[Regressions/coreclr/GitHub_54719/test54719/test54719.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311497&view=ms.vss-test-web.build-test-results-tab&runId=6357126&resultId=118614)||
|[311363](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311363)|dotnet/runtime|[Regressions/coreclr/GitHub_45037/test45037/test45037.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311363&view=ms.vss-test-web.build-test-results-tab&runId=6354250&resultId=118614)||
|[311319](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311319)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311319&view=ms.vss-test-web.build-test-results-tab&runId=6352736&resultId=120588)||
|[311318](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311318)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311318&view=ms.vss-test-web.build-test-results-tab&runId=6352718&resultId=120588)||
|[311307](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311307)|dotnet/runtime|[Regressions/coreclr/GitHub_45037/test45037/test45037.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311307&view=ms.vss-test-web.build-test-results-tab&runId=6352308&resultId=119557)||
|[311305](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311305)|dotnet/runtime|[Regressions/coreclr/GitHub_54719/test54719/test54719.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311305&view=ms.vss-test-web.build-test-results-tab&runId=6352220&resultId=118614)||
|[311190](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311190)|dotnet/runtime|[Regressions/coreclr/GitHub_45037/test45037/test45037.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311190&view=ms.vss-test-web.build-test-results-tab&runId=6349072&resultId=118614)||
|[310909](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310909)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310909&view=ms.vss-test-web.build-test-results-tab&runId=6339320&resultId=120587)||
|[310908](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310908)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310908&view=ms.vss-test-web.build-test-results-tab&runId=6339296&resultId=120587)||
|[310889](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310889)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310889&view=ms.vss-test-web.build-test-results-tab&runId=6338976&resultId=120588)|dotnet/runtime#87241|
|[310769](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310769)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310769&view=ms.vss-test-web.build-test-results-tab&runId=6337076&resultId=120588)|dotnet/runtime#87241|
|[310510](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310510)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310510&view=ms.vss-test-web.build-test-results-tab&runId=6331858&resultId=118711)|dotnet/runtime#87588|
|[310478](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310478)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310478&view=ms.vss-test-web.build-test-results-tab&runId=6331110&resultId=118711)||
|[309817](https://dev.azure.com/dnceng-public/public/_build/results?buildId=309817)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=309817&view=ms.vss-test-web.build-test-results-tab&runId=6313432&resultId=118711)||
|[309621](https://dev.azure.com/dnceng-public/public/_build/results?buildId=309621)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=309621&view=ms.vss-test-web.build-test-results-tab&runId=6306842&resultId=120587)||
|[309622](https://dev.azure.com/dnceng-public/public/_build/results?buildId=309622)|dotnet/runtime|[Regressions/coreclr/GitHub_54719/test54719/test54719.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=309622&view=ms.vss-test-web.build-test-results-tab&runId=6306998&resultId=118588)||
|[309581](https://dev.azure.com/dnceng-public/public/_build/results?buildId=309581)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=309581&view=ms.vss-test-web.build-test-results-tab&runId=6304848&resultId=120679)|dotnet/runtime#87421|
|[309485](https://dev.azure.com/dnceng-public/public/_build/results?buildId=309485)|dotnet/runtime|[Regressions/coreclr/GitHub_54719/test54719/test54719.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=309485&view=ms.vss-test-web.build-test-results-tab&runId=6302738&resultId=118613)||
|[309277](https://dev.azure.com/dnceng-public/public/_build/results?buildId=309277)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=309277&view=ms.vss-test-web.build-test-results-tab&runId=6300498&resultId=118711)|dotnet/runtime#87438|
|[308896](https://dev.azure.com/dnceng-public/public/_build/results?buildId=308896)|dotnet/runtime|[Regressions/coreclr/GitHub_54719/test54719/test54719.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=308896&view=ms.vss-test-web.build-test-results-tab&runId=6288506&resultId=118612)||
|[308149](https://dev.azure.com/dnceng-public/public/_build/results?buildId=308149)|dotnet/runtime|[Regressions/coreclr/GitHub_54719/test54719/test54719.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=308149&view=ms.vss-test-web.build-test-results-tab&runId=6272888&resultId=118612)||
|[308007](https://dev.azure.com/dnceng-public/public/_build/results?buildId=308007)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=308007&view=ms.vss-test-web.build-test-results-tab&runId=6267634&resultId=120586)||
|[308008](https://dev.azure.com/dnceng-public/public/_build/results?buildId=308008)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=308008&view=ms.vss-test-web.build-test-results-tab&runId=6267666&resultId=120586)||
|[307831](https://dev.azure.com/dnceng-public/public/_build/results?buildId=307831)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=307831&view=ms.vss-test-web.build-test-results-tab&runId=6265328&resultId=118710)||
|[307293](https://dev.azure.com/dnceng-public/public/_build/results?buildId=307293)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=307293&view=ms.vss-test-web.build-test-results-tab&runId=6255794&resultId=118710)||
|[306663](https://dev.azure.com/dnceng-public/public/_build/results?buildId=306663)|dotnet/runtime|[Regressions/coreclr/GitHub_45037/test45037/test45037.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=306663&view=ms.vss-test-web.build-test-results-tab&runId=6239340&resultId=118612)||
|[306672](https://dev.azure.com/dnceng-public/public/_build/results?buildId=306672)|dotnet/runtime|[Regressions/coreclr/GitHub_54719/test54719/test54719.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=306672&view=ms.vss-test-web.build-test-results-tab&runId=6239496&resultId=118605)|dotnet/runtime#87536|
|[306512](https://dev.azure.com/dnceng-public/public/_build/results?buildId=306512)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=306512&view=ms.vss-test-web.build-test-results-tab&runId=6234168&resultId=120586)||
|[306513](https://dev.azure.com/dnceng-public/public/_build/results?buildId=306513)|dotnet/runtime|[Regressions/coreclr/GitHub_45037/test45037/test45037.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=306513&view=ms.vss-test-web.build-test-results-tab&runId=6234406&resultId=120489)||
|[306358](https://dev.azure.com/dnceng-public/public/_build/results?buildId=306358)|dotnet/runtime|[Regressions/coreclr/GitHub_45037/test45037/test45037.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=306358&view=ms.vss-test-web.build-test-results-tab&runId=6232348&resultId=118611)||
|[305654](https://dev.azure.com/dnceng-public/public/_build/results?buildId=305654)|dotnet/runtime|[HardwareIntrinsics_X86_Avx_ro.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=305654&view=ms.vss-test-web.build-test-results-tab&runId=6213232&resultId=120124)||
|[303328](https://dev.azure.com/dnceng-public/public/_build/results?buildId=303328)|dotnet/runtime|[TypeGeneratorTests1000-1099.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=303328&view=ms.vss-test-web.build-test-results-tab&runId=6155782&resultId=120573)||
|[303173](https://dev.azure.com/dnceng-public/public/_build/results?buildId=303173)|dotnet/runtime|[Regression_2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=303173&view=ms.vss-test-web.build-test-results-tab&runId=6149538&resultId=120300)||
|[303167](https://dev.azure.com/dnceng-public/public/_build/results?buildId=303167)|dotnet/runtime|[jit64_4.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=303167&view=ms.vss-test-web.build-test-results-tab&runId=6149238&resultId=120330)||
|[302824](https://dev.azure.com/dnceng-public/public/_build/results?buildId=302824)|dotnet/runtime|[JIT/Regression/JitBlue/DevDiv_255294/DevDiv_255294/DevDiv_255294.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=302824&view=ms.vss-test-web.build-test-results-tab&runId=6140148&resultId=115103)||
|[300944](https://dev.azure.com/dnceng-public/public/_build/results?buildId=300944)|dotnet/runtime|[JIT/Regression/JitBlue/DevDiv_255294/DevDiv_255294/DevDiv_255294.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=300944&view=ms.vss-test-web.build-test-results-tab&runId=6097042&resultId=115986)||
|[299568](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299568)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299568&view=ms.vss-test-web.build-test-results-tab&runId=6067676&resultId=120379)||
|[299541](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299541)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299541&view=ms.vss-test-web.build-test-results-tab&runId=6067296&resultId=120379)|dotnet/runtime#87261|
|[299429](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299429)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299429&view=ms.vss-test-web.build-test-results-tab&runId=6063740&resultId=112511)||
|[299427](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299427)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299427&view=ms.vss-test-web.build-test-results-tab&runId=6064236&resultId=120377)||
|[299396](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299396)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299396&view=ms.vss-test-web.build-test-results-tab&runId=6063458&resultId=120378)||
|[299397](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299397)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299397&view=ms.vss-test-web.build-test-results-tab&runId=6063462&resultId=120380)||
|[299242](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299242)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299242&view=ms.vss-test-web.build-test-results-tab&runId=6060996&resultId=120378)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|5|53|

**Comment by hoyosjs** [comment]
Related: https://github.com/dotnet/runtime/issues/86399

**Comment by jakobbotsch** [comment]
This, #87305 and #87258 are likely all the same issue and were fixed by #87263. cc @EgorBo

**Comment by mangod9** [comment]
Is this ok to close? Havent seen hits in the last few days?

**Comment by hoyosjs** [comment]
SGTM
