### ISSUE TITLE
Rejit test failures in outerloop - unexpected counts

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#87300]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=299541
Build error leg or test failing: profiler/rejit/rejit/rejit.sh
Pull request: https://github.com/dotnet/runtime/pull/87261

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "rejit count=\\d+ expected rejit count=\\d+",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by AndyAyersMS** [comment]
This may be the problem @tommcdon was asking me about the other day -- with Dynamic PGO enabled, frequently called methods,may now be jitted 3 times (Tier0, Tier0+instr, Tier1).

**Comment by tommcdon** [comment]
Zero failures in the last month, closing
