### ISSUE TITLE
WindowsServiceLifetime.ServiceName is empty in NET6

### ISSUE THREAD

**Issue by Igor-ZA** [dotnet/runtime#87309]
### Description

"In .NET 6, the WindowsServiceLifetime.ServiceName returns an empty string, while this works in .NET 7."

### Reproduction Steps

nugets:

Microsoft.Extensions.Hosting Version=6.0.1
Microsoft.Extensions.Hosting.WindowsServices Version=6.0.1
Serilog.Sinks.File Version=5.0.0

using Microsoft.Extensions.Hosting.WindowsServices;
using Serilog;
using System.Runtime.InteropServices;

var logPath = "C:\\App\\Logs";

Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Debug()
    .WriteTo.File(Path.Combine(logPath, "log-.txt"),
        outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message:lj}{NewLine}{Exception}",
        rollingInterval: RollingInterval.Day)
    .CreateLogger();

var host = Host.CreateDefaultBuilder(args)
    .UseWindowsService()
    .ConfigureServices(services =>
    {
        services.AddHostedService<Worker>();
    })
    .Build();

await host.RunAsync();

class Worker : BackgroundService
{
    private readonly IHostLifetime _hostLifetime;

    public Worker(IHostLifetime hostLifetime)
    {
        _hostLifetime = hostLifetime;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        while (!stoppingToken.IsCancellationRequested)
        {
            Log.Information($"ServiceName: **{GetServiceName()}**");
            await Task.Delay(5000, stoppingToken);
        }
    }

    private string GetServiceName()
    {
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows) &&
            _hostLifetime is WindowsServiceLifetime windowsServiceLifetime)
        {
            return windowsServiceLifetime.ServiceName;
        }

        return "TEST";
    }
}

If I update it, it works:
Microsoft.Extensions.Hosting Version=7.0.1
Microsoft.Extensions.Hosting.WindowsServices Version=7.0.0

### Expected behavior

WindowsServiceLifetime.ServiName returns the name of the windows service

### Actual behavior

NET6: WindowsServiceLifetime.ServiName  is empty
NET7: it works

**Comment by feiyun0112** [comment]
This is because .NET7 add code to get the ServiceName  before the service start

[https://github.com/dotnet/runtime/blob/main/src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceBase.cs#LL867C26-L867C39](https://github.com/dotnet/runtime/blob/main/src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceBase.cs#LL867C26-L867C39)

you can get ServiceName like this in .NET6

```
private string GetServiceName()
{
    if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
    {
        int processId = Process.GetCurrentProcess().Id;
        ManagementObjectSearcher searcher = new ManagementObjectSearcher(
            "SELECT * FROM Win32_Service where ProcessId = " + processId);
        ManagementObjectCollection collection = searcher.Get();
        var serviceName = (string)collection.Cast<ManagementBaseObject>().First()["Name"];

        return serviceName;
    }

    return "TEST";
}
```

**Comment by Igor-ZA** [comment]
> This is because .NET7 add code to get the ServiceName before the service start
> 
> https://github.com/dotnet/runtime/blob/main/src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceBase.cs#LL867C26-L867C39
> 
> you can get ServiceName like this in .NET6
> 
> ```
> private string GetServiceName()
> {
>     if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
>     {
>         int processId = Process.GetCurrentProcess().Id;
>         ManagementObjectSearcher searcher = new ManagementObjectSearcher(
>             "SELECT * FROM Win32_Service where ProcessId = " + processId);
>         ManagementObjectCollection collection = searcher.Get();
>         var serviceName = (string)collection.Cast<ManagementBaseObject>().First()["Name"];
> 
>         return serviceName;
>     }
> 
>     return "TEST";
> }
> ```
Thank you, this works, but I think it's an bug in .NET 6.

**Comment by steveharter** [comment]
Closing as won't port\service to 6.0 since there is a workaround above.

Re-open or comment here if a port\service request is needed.
