### ISSUE TITLE
fgReplacePred will attempt to remove Preds that do not exist.

### ISSUE THREAD

**Issue by jashook** [dotnet/runtime#8732]
The current behavior is to not insert the newPred.

category:correctness
theme:flowgraph
skill-level:intermediate
cost:medium

**Comment by AndyAyersMS** [comment]
The underlying issue (pred lists not remaining sorted) is fixed, see https://github.com/dotnet/runtime/pull/46351.

Seems like we could now easily add an assert and figure out if we're ever asking `fgReplacePred` to do something nonsensical.

**Comment by AndyAyersMS** [comment]
> Seems like we could now easily add an assert and figure out if we're ever asking `fgReplacePred` to do something nonsensical.

And so we should!

**Comment by AndyAyersMS** [comment]
`fgReplacePred` has been rewritten to operate on a flow edge, so the issue raised here is no longer possible.

See https://github.com/dotnet/runtime/pull/98563
