### ISSUE TITLE
Porting X509Certificate2.MatchesHostname to Net6

### ISSUE THREAD

**Issue by JRahnama** [dotnet/runtime#87341]
Currently at SqlClient team we have an internal implementation to validate Server Certificate by calling `RemoteCertificateValidationCallback `delegate. The newly added APIs in net 7 and greater makes it a lot easier to verify the certificate and its SAN names, however in Net 6 it gets more complicated as there is no easy way of checking/accessing multiple SANs from a certificate.

Is it possible to port `X509Certificate2.MatchesHostname` to net6 by any chance?

**Comment by bartonjs** [comment]
No, new public API can never be added to previous versions.
