### ISSUE TITLE
Generate error message when createdump is missing or does not have executable permissions

### ISSUE THREAD

**Issue by tommcdon** [dotnet/runtime#87352]
The .NET runtime can be configured to write crashdump files to the local file system on unhandled exceptions (for example setting the `DOTNET_DbgEnableMiniDump=1` environment variable per https://github.com/dotnet/runtime/blob/main/docs/design/coreclr/botr/xplat-minidump-generation.md#configurationpolicy).  The implementation launches `createdump` which is an executable binary that ships in the `<dotnet_install_root>/shared/Microsoft.NETCore.App/<version>` folder. 

We have had user reports that dumps are mysteriously not collected even when the environment variable was set.  When diagnosing the root cause we often find the problem is caused by the "execute" flag on `createdump` is missing.  

In the event that `createdump` fails to launch, we should output a useful error message that details the reason why a crash dump was not collected.

**Comment by tommcdon** [comment]
@hoyosjs @mikem8361

**Comment by mikem8361** [comment]
We already display a message in this case: https://github.com/dotnet/runtime/blob/eb650227be048a1a89d18484de18dd5aeda7caf7/src/coreclr/pal/src/thread/process.cpp#L2240

**Comment by mikem8361** [comment]
Maybe the problem is that this error message goes to the app's stderr which if it is a service or in the background, it won't be seen.

**Comment by tommcdon** [comment]
Closing since this is already fixed in .net 7+
