### ISSUE TITLE
[API Proposal]: Make LargeArrayBuilder public

### ISSUE THREAD

**Issue by xrem** [dotnet/runtime#87361]
### Background and motivation

I've found out that using [LargeArrayBuilder](https://github.com/dotnet/runtime/blob/main/src/libraries/Common/src/System/Collections/Generic/LargeArrayBuilder.SpeedOpt.cs) is much more effective then just calling `.ToArray()`. So, it would be nice to have ability to use it via publiс API ([without fancy reflections](https://gist.github.com/xrem/d96268a6755b08b232dfa7f3ead3c93d#file-managedlargearraybuilder-cs-L17))

See benchmarks & discussion:
https://github.com/dotnet/efcore/issues/31040

See also:
https://github.com/dotnet/runtime/issues/20045
https://github.com/dotnet/runtime/issues/37852

### API Proposal

```csharp
namespace System.Collections.Generic;

public struct LargeArrayBuilder<T>
{
    public void Add(T item);
    public void AddRange(IEnumerable<T> items);
    public void CopyTo(T[] array, int arrayIndex, int count);
    public CopyPosition CopyTo(CopyPosition position, T[] array, int arrayIndex, int count);
    public T[] GetBuffer(int index);
    public T[] ToArray();
    public bool TryMove(out T[] array);
}
```

### API Usage

```csharp

public int[] Foo() {
    var arrayBuilder = new LargeArrayBuilder<int>();
    foreach (var i in Enumerable.Range(0, 100)) 
    {
        arrayBuilder.Add(i);
    }
    return arrayBuilder.ToArray();
}
```

### Risks

I don't see risks such as breaking changes, performance regressions since it was internal struct.

**Comment by DaZombieKiller** [comment]
For the most part, you can use [ArrayBufferWriter](https://learn.microsoft.com/en-us/dotnet/api/system.buffers.arraybufferwriter-1) (or [ArrayPoolBufferWriter](https://learn.microsoft.com/en-us/dotnet/api/communitytoolkit.highperformance.buffers.arraypoolbufferwriter-1) from the toolkit) for this purpose today. You can retrieve the current `T[]` from an `ArrayBufferWriter<T>` by using `MemoryMarshal.TryGetArray` on `writer.WrittenMemory`. The toolkit's `ArrayPoolBufferWriter<T>` exposes a `DangerousGetArray` method.

With this in mind, it might be better to just expose `TryMoveToArray`, `MoveToArray` and `DrainToArray` (mimicking the APIs on `ImmutableArray<T>.Builder`) on `ArrayBufferWriter`, and expose a new `IBufferWriter<T>` extension method for handling `IEnumerable<T>`:
```diff
namespace System.Buffers;

public sealed class ArrayBufferWriter<T> : IBufferWriter<T>
{
+    public T[] MoveToArray();
+    public T[] DrainToArray();
+    public bool TryMoveToArray([NotNullWhen(true)] out T[]? array);
}

public static class BuffersExtensions
{
+    public static void Write<T>(this IBufferWriter<T> writer, IEnumerable<T> items);
}
```

**Comment by stephentoub** [comment]
> I've found out that using [LargeArrayBuilder](https://github.com/dotnet/runtime/blob/main/src/libraries/Common/src/System/Collections/Generic/LargeArrayBuilder.SpeedOpt.cs) is much more effective then just calling .ToArray()

I don't understand this statement.  LINQ's `ToArray` today is implemented to just do effectively what's in your "API usage" example:
https://github.com/dotnet/runtime/blob/362678a6c7d45f9a49c4aaa946701f791c56b484/src/libraries/Common/src/System/Collections/Generic/EnumerableHelpers.Linq.cs#L83-L85
Can you elaborate?

`LargeArrayBuilder` can be more efficient for larger inputs, but it can be a net negative for smaller inputs, and it's a significant amount of code to carry around for every generic specialization.  We've contemplated actually just ripping it out entirely. I don't currently see us going the other direction and wanting to expose it publicly.

**Comment by xrem** [comment]
I'll review comments, do benchmarks and return with new reasons to make that struct public 🙂
