### ISSUE TITLE
Example of building and testing libraries doesn't work

### ISSUE THREAD

**Issue by skyoxZ** [dotnet/runtime#87367]
https://github.com/dotnet/runtime/blob/66def3a7024d8c860c047a9b1681085c591d46ca/docs/workflow/building/libraries/README.md?plain=1#L40-L48

There are two problems:

1. AFAIK `command1 && command2` runs sequentially but `command1 & command2` runs simultaneously. So the last line would not work as expected.

2. `System.Text.RegularExpressions` is uncommon that there's not a xxx.csproj in directory `tests`:

    https://github.com/dotnet/runtime/tree/66def3a7024d8c860c047a9b1681085c591d46ca/src/libraries/System.Text.RegularExpressions/tests

**Comment by danmoseley** [comment]
In cmd.exe, `&&` and `&` both cause commands to run sequentially. The difference is that `&&` tests that the command before it succeeded (compare `||` tests that it failed) whereas `&` does not.

Yes, the regex tests were split. Feel free to offer a PR fixing the example.

**Comment by danmoseley** [comment]
Oops, I missed that this is Unix, not Windows. Good point - do you want to fix?

**Comment by skyoxZ** [comment]
Yeah I'm glad to take it. Should we still use `RegularExpressions` for the example or change to another library?

**Comment by stephentoub** [comment]
> Maybe pick one that has the more typical test project location.

It's common to have a single test project, in which case there's a csproj in the tests folder, and it's common to have multiple projects, in which case there isn't.

**Comment by skyoxZ** [comment]
I notice my PR is not reviewed for 10 days and this issue was marked `needs-author-action` but I don't know why. Did I miss something?
