### ISSUE TITLE
Address non-standard printf formatting in printf

### ISSUE THREAD

**Issue by swgillespie** [dotnet/runtime#8737]
The `dprintf` logging mechanism in the GC uses some non-standard formatting sequences that may not work as expected with a non-windows CRT. We should settle on standard formatting sequences so that we can use this mechanism on non-Windows platforms.

The standalone GC build currently builds with `-Wno-format` in order to silence the warnings raised about these non-standard formatting sequences.

cc @Maoni0

**Comment by jkotas** [comment]
cc @AaronRobinsonMSFT The non-standard printf formatting strings is one of the things that we will need to address to get rid of the Win32 PAL.
