### ISSUE TITLE
[API Proposal]: add overloads with SocketAddress to Socket's SendTo and ReceiveFrom

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#87397]
### Background and motivation

This is subset from #30797. There is long discussion about how to make sending and receiving UDP more efficient. Current overloads allocate a lot for each packet and that kills performance and it puts lot of pressure on GC. Garbage collection has  significant impact on scenarios that are sensitive to timing - like multiplayer Unity games.  

### API Proposal

```csharp
namespace System.Net.Sockets;

public class Socket
{
+  public int ReceiveFrom(Span<byte> buffer, SocketFlags socketFlags, SocketAddress socketAddress);
+  public ValueTask<int> ReceiveFromAsync(Memory<byte> buffer, SocketFlags socketFlags, SocketAddress socketAddress, CancellationToken cancellationToken = default);

+. public int SendTo(ReadOnlySpan<byte> buffer, SocketFlags socketFlags, SocketAddress socketAddress);
+. public ValueTask<int> SendToAsync(ReadOnlyMemory<byte> buffer, SocketFlags socketFlags, SocketAddress socketAddress, CancellationToken cancellationToken = default);
}
```

Instead of allocating and returning EndPoint, we can reuse `SocketAddress` and we would update it in place. Ideally using API proposed in https://github.com/dotnet/runtime/issues/86872 but in worst case the `SocketAddress` is already writable and we can play some internal tricks. 

### API Usage

example of simple server that would process request - inspired by DNS server linked in #30797

```csharp
  SocketAddress sa = new SocketAddress(AddressFamily.InterNetworkV6);
  while (doWork)
  {
      int receivedLength = s.ReceiveFrom(buffer, SocketFlags.None, sa);
      response = processRequest(buffer.Slice(0, receivedLength);
      s.SendTo(response, SocketFlags.None, sa);
  }
```

The async version would be basically same with addition of `CancellationToken`. Unlike `ReceiveFromAsync ` that used `EndPoint` and returns `SocketReceiveFromResult` we would return `ValueTask<int>` just like the synchronous version and we would update `socketAddress` in-place.

### Risks

This is low-level API intended for experienced users. While there is nothing particularly dangerous one should be very careful about life cycle of the `socketAddress` as it can be overwritten on subsequent use.

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System.Net.Sockets;

public partial class Socket
{
    public int ReceiveFrom(Span<byte> buffer, SocketFlags socketFlags, SocketAddress socketAddress);
    public ValueTask<int> ReceiveFromAsync(Memory<byte> buffer, SocketFlags socketFlags, SocketAddress socketAddress, CancellationToken cancellationToken = default);

    public int SendTo(ReadOnlySpan<byte> buffer, SocketFlags socketFlags, SocketAddress socketAddress);
    public ValueTask<int> SendToAsync(ReadOnlyMemory<byte> buffer, SocketFlags socketFlags, SocketAddress socketAddress, CancellationToken cancellationToken = default);
}
```

**Comment by fredrikhr** [comment]
Thinking about the ergonomics of receiving the `SocketAddress` I think the following proposal could make `ReceiveFrom` viable:

This basically adds `ref` for the `SocketAddress` parameter.

```C#
namespace System.Net.Sockets;

public partial class Socket
{
    public int ReceiveFrom(Span<byte> buffer, SocketFlags socketFlags, ref SocketAddress socketAddress);
    public ValueTask<int> ReceiveFromAsync(Memory<byte> buffer, SocketFlags socketFlags, ref SocketAddress socketAddress, CancellationToken cancellationToken = default);
}
```

**Comment by antonfirsov** [comment]
This has been considered, the problem is that `ref` doesn't play well with `async`.

**Comment by fredrikhr** [comment]
@antonfirsov can you elaborate on that? I just prototyped this in SharpLab https://sharplab.io/#gist:14ff035d0a0dec97365a6d992b47dfd9. What am I missing?

**Comment by antonfirsov** [comment]
`ReceiveFromAsync` would be only able to only mutate it on it's synchronous path. If you mark the method `async`, the compiler will complain. As a rule of thumb, async methods never take `ref`.

**Comment by fredrikhr** [comment]
Thanks for indulging in my ignorance. Makes perfect sense now! I am excited to see Levi's idea that he started to propose during API review.

**Comment by stephentoub** [comment]
> We don't like ReceiveFrom because it mutates the socket address

Why is it a problem to mutate the SocketAddress? The whole point of this was to mutate it, thereby providing a way of achieving am allocstion-free receive path.  We have other methods that mutate arguments... why can't this one?

**Comment by dersia** [comment]
> > We don't like ReceiveFrom because it mutates the socket address
> 
> Why is it a problem to mutate the SocketAddress? The whole point of this was to mutate it, thereby providing a way of achieving an allocation-free receive path. We have other methods that mutate arguments... why can't this one?
> 
> SocketAddress is just a strongly-typed buffer. Mutating buffers in read/receive methods is how things work.

during the meeting it came up that users might assume that ReceiveFrom would receive an address with the parameter and not expect for it to mutate. I general the problem wasn't that it is mutating, but that the name was misleading and therefor it was excluded for now.

at least that is what I understood from the meeting.

**Comment by stephentoub** [comment]
Thanks. To me that's an issue for documentation: the overload may write into the supplied buffers, both for the data received and for the address from which it was received.

I'd really like for these overloads to be in .NET 8.  @bartonjs, @terrajobst, can we revisit this at the beginning of the next API review?

**Comment by terrajobst** [comment]
* let's change the name of the parameter `socketAddress` to `receivedAddress` to make it clear that it will be mutated.

```C#
namespace System.Net.Sockets;

public partial class Socket
{
    public int ReceiveFrom(Span<byte> buffer, SocketFlags socketFlags, SocketAddress receivedAddress);
    public ValueTask<int> ReceiveFromAsync(Memory<byte> buffer, SocketFlags socketFlags, SocketAddress receivedAddress, CancellationToken cancellationToken = default);

    // Approved already
    // public int SendTo(ReadOnlySpan<byte> buffer, SocketFlags socketFlags, SocketAddress socketAddress);
    // public ValueTask<int> SendToAsync(ReadOnlyMemory<byte> buffer, SocketFlags socketFlags, SocketAddress socketAddress, CancellationToken cancellationToken = default);
}
```
