### ISSUE TITLE
`RequestReJITWithInliners` doesn't always trigger a rejit without `COR_PRF_MONITOR_JIT_COMPILATION` enabled

### ISSUE THREAD

**Issue by schmittjoseph** [dotnet/runtime#87418]
### Description

When requesting that methods be rejitted using a main profiler and `ICorProfilerInfo10::RequestReJITWithInliners`, it appears that it will sometimes, and seemingly random, not actually trigger a rejit - the `ICorProfilerCallback4::GetReJITParameters` callback is never invoked for the requested methods.  This doesn't consistently happen, and happens independently of the set of methods rejit is being requested for.

I've found that by enabling `COR_PRF_MONITOR::COR_PRF_MONITOR_JIT_COMPILATION` in the profiler's event mask, this issue goes away even with the corresponding callbacks being no-ops.

### Reproduction Steps

The only consistent repro we have for this is in our CI pipelines on MacOS so it's difficult to share an easy way to repro locally. Let me know if there's additional information you'd like to see and I can update our CI to gather it.

### Expected behavior

`ICorProfilerCallback4::GetReJITParameters` is called the next time the requested managed method is called.

### Actual behavior

`ICorProfilerCallback4::GetReJITParameters` is sometimes never called even after the requested managed method is called multiple times over an extended period of time. 

### Known Workarounds

Enable `COR_PRF_MONITOR::COR_PRF_MONITOR_JIT_COMPILATION` in the profiler's event mask.

### Configuration

Versions: Tested and observed in net6.0, net7.0, and net8.0

OS: This appears to be independent of the OS, but we can consistently repro it on MacOS in our pipelines (Windows rarely repros it for us).

### Other information

I don't have any evidence that this is the cause and it might be unrelated, but the only significant difference I've found in the runtime caused by setting `COR_PRF_MONITOR_JIT_COMPILATION` is that multicore jit gets disabled: https://github.com/dotnet/runtime/blob/84a3d0e37e8f22b0b55f8bf932cb788b2bdd728f/src/coreclr/vm/profilinghelper.cpp#L1290-L1294

It's also worth noting that the runtime's tests for `RequestReJITWithInliners` always has `COR_PRF_MONITOR_JIT_COMPILATION` enabled:  https://github.com/dotnet/runtime/blob/84a3d0e37e8f22b0b55f8bf932cb788b2bdd728f/src/tests/profiler/native/rejitprofiler/rejitprofiler.cpp#L74-L76

**Comment by tommcdon** [comment]
@davmason  would you mind taking a look?

**Comment by davmason** [comment]
Hi @schmittjoseph,

Thanks for reaching out. Reading through your description the only explanation I can think of is that your method somehow gets inlined with a race condition between RequestReJITWithInliners and something else triggering a jit.

This will be very difficult to diagnose without a repro. Are you able to capture a memory dump from the test when it fails in automation?

**Comment by tommcdon** [comment]
After careful consideration, we do not plan to action this particular item in this release. We will continue to evaluate it for future releases. Ideally, we would like to fix every issue and implement every idea people submit. Realistically, we cannot address every item.
