### ISSUE TITLE
[iOS] Vector128 and Vector64 GetOne* test failures 

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#87412]
On CI, it appears all of the GetOne (GetOneByte, GetOneIntPr, GetOneInt32, etc) tests are failing for Vector128 and Vector64.  

https://dev.azure.com/dnceng-public/public/_build/results?buildId=303329&view=ms.vss-test-web.build-test-results-tab

For example:

Vector64.GetOneByte

```
Expected: <1, 0, 0, 0, 0, 0, 0, 0>
Actual:   <3, 122, 0, 0, 0, 0, 0, 0>
```

Vector128.GetOneInt32

```
Expected: <1, 0, 31235, 0>
Actual:   <31235, 0, 0, 0>
```

## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=303329&view=ms.vss-test-web.build-test-results-tab
Leg Name: https://dev.azure.com/dnceng-public/public/_build?definitionId=154&_a=summary

## Error Message

```json 
{ 
    "ErrorMessage": "Expected: <1, 0, 0, 0, 0, 0, 0, 0>",
    "BuildRetry": false,
    "ErrorPattern": "",
    "ExcludeConsoleLog": false
} 
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=303329
**Result validation: :white_check_mark:** Known issue matched with the provided build.

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[303329](https://dev.azure.com/dnceng-public/public/_build/results?buildId=303329)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.GetOneByte](https://dev.azure.com/dnceng-public/public/_build/results?buildId=303329&view=ms.vss-test-web.build-test-results-tab&runId=6155090&resultId=112235)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|1|

**Comment by kotlarmilos** [comment]
The issue is not occurring in the latest runs. Let's check if it is still happening.
