### ISSUE TITLE
[wasm][AOT] Vector256ByteShiftLeftTest - Cannot select: 0x55ee6da14cd0: v16i8

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#87423]
AOT compilation of `System_Runtime_Intrinsics_Tests_System_Runtime_Intrinsics_Tests_Vectors_Vector256Tests_Vector256ByteShiftLeftTest`

[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-86759-merge-37fcd92fd68e4ff583/normal-System.Runtime.Intrinsics.Tests/1/console.9bab6002.log?helixlogtype=result)

```
error : clang -cc1 version 17.0.0 based upon LLVM 17.0.0git default target x86_64-unknown-linux-gnu 
[/root/helix/work/workitem/e/publish/ProxyProjectForAOTOnHelix.proj]
/root/helix/work/correlation/build/wasm/WasmApp.Native.targets(358,5): 
error : fatal error: error in backend: Cannot select: 0x558f096a8c60: v16i8 = BUILD_VECTOR 
Constant:i32<-240>, Constant:i32<-240>, Constant:i32<-240>, 
Constant:i32<-240>, Constant:i32<-240>, Constant:i32<-240>, 
Constant:i32<-240>, Constant:i32<-240>, Constant:i32<0>, 
Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, 
Constant:i32<0>, Constant:i32<0>, Constant:i32<0> 
[/root/helix/work/workitem/e/publish/ProxyProjectForAOTOnHelix.proj]

In function: System_Runtime_Intrinsics_Tests_System_Runtime_Intrinsics_Tests_Vectors_Vector256Tests_Vector256ByteShiftLeftTest [/root/helix/work/workitem/e/publish/ProxyProjectForAOTOnHelix.proj]
```
AOT compilation of `System_Runtime_Intrinsics_Tests_System_Runtime_Intrinsics_Tests_Vectors_Vector256Tests_Vector256ByteShiftLeftTest`

[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-86759-merge-37fcd92fd68e4ff583/normal-System.Runtime.Intrinsics.Tests/1/console.9bab6002.log?helixlogtype=result)

```
error : clang -cc1 version 17.0.0 based upon LLVM 17.0.0git default target x86_64-unknown-linux-gnu 
[/root/helix/work/workitem/e/publish/ProxyProjectForAOTOnHelix.proj]
/root/helix/work/correlation/build/wasm/WasmApp.Native.targets(358,5): 
error : fatal error: error in backend: Cannot select: 0x558f096a8c60: v16i8 = BUILD_VECTOR 
Constant:i32<-240>, Constant:i32<-240>, Constant:i32<-240>, 
Constant:i32<-240>, Constant:i32<-240>, Constant:i32<-240>, 
Constant:i32<-240>, Constant:i32<-240>, Constant:i32<0>, 
Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, 
Constant:i32<0>, Constant:i32<0>, Constant:i32<0> 
[/root/helix/work/workitem/e/publish/ProxyProjectForAOTOnHelix.proj]

In function: System_Runtime_Intrinsics_Tests_System_Runtime_Intrinsics_Tests_Vectors_Vector256Tests_Vector256ByteShiftLeftTest [/root/helix/work/workitem/e/publish/ProxyProjectForAOTOnHelix.proj]
```

## note
To reproduce this locally you would need to add `-p:BuildAOTTestsOnHelix=true` to the command line, because the optimization flags used for helix are different. For local runs we use `-O2`, vs for helix `-Oz -Wl,-O0 -Wl,--lto-O0`.

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by lewing** [comment]
@radekdoulik please update the status here
