### ISSUE TITLE
[wasm] Perf pipeline completely broken

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#87434]
`Zip Browser Wasm Artifacts` step failing with:

```
##[error]Error: Unable to locate executable file: 'zip'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
##[error]Unable to locate executable file: 'zip'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

Changes since last working build: 15d77612...22492751 which includes https://github.com/dotnet/runtime/pull/86806 .

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by radical** [comment]
fyi @SamMonoRT

**Comment by LoopedBard3** [comment]
It seems that this is likely related to https://github.com/dotnet/runtime/pull/86806. At the very least, the container that is now being used is the clb-mariner-2.0-webassembly container, where it was ubuntu-18.04-webassembly-net8 before. It also looks like the mariner container does not contain zip by default. I am not sure if these images are supposed to include the zip tool but it appears that they do not.

**Comment by lewing** [comment]
cc @jkoritzinsky

**Comment by LoopedBard3** [comment]
Another option may be to just install the zip tool before the task that needs zip.
