### ISSUE TITLE
Failure in checked/release asm diffs pipeline

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#87432]
In the `coreclr_tests` spmi collection, we're seeing a bunch of:

```
ISSUE: <ASSERT> #303569 D:\a\_work\1\s\src\coreclr\jit\compiler.h (8722) - Assertion failed '(JitConfig.EnableHWIntrinsic() == 0) || (JitConfig.EnableSSE() == 0)' in 'System.Diagnostics.Tracing.RuntimeEventSource:.ctor():this' during 'Importation' (IL size 55; hash 0xd472ed50; FullOpts)
```

https://dev.azure.com/dnceng-public/public/_build/results?buildId=302887&view=results

This doesn't happen when doing a spmi replay of either Checked or Release compilers alone. Note that checked/release diffs uses the superpmi.py option `--diff_with_release`, which in turn passes `-ignoreStoredConfig` to superpmi.exe. Note the comment in superpmi.py:

```
# If one of the JITs is Release, ignore all the stored configuration variables.
# This isn't necessary if both are Release builds (and, in fact, it can clear variables
# that both Release compilers can interpret). However, we rarely or never compare
# two Release compilers, so this is safest.
flags += [ "-ignoreStoredConfig" ]
```

This appears to be a regression from https://github.com/dotnet/runtime/pull/85551.

Maybe will be fixed by https://github.com/dotnet/runtime/pull/87420?

**Comment by BruceForstall** [comment]
I kicked off https://dev.azure.com/dnceng-public/public/_build/results?buildId=305674&view=results to see if #87420 fixes it

**Comment by tannergooding** [comment]
#87420 won't fix this as the asserts weren't removed.

This assert should probably just be removed. There are a few cases where `Vector<T>` can be unsupported even without HWIntrinsics being disabled.

**Comment by tannergooding** [comment]
Kicked off https://dev.azure.com/dnceng-public/public/_build/results?buildId=307685&view=results
