### ISSUE TITLE
[API Proposal]: Stopwatch.ToString()

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#87449]
### Background and motivation

When logging the time passed in a Stopwatch, some may write `Stopwatch.ToString()`. This is a mistake as it always returns the string `System.Diagnostics.Stopwatch`. 

We should make it return a reasonable default representation of the elapsed time. That would satisfy the principle of least surprise, as well as be a little more compact when writing a little test program and dumping the time. 

### API Proposal

```csharp
namespace System.Diagnostics;

public partial class Stopwatch
{
    public override string ToString() => Elapsed.ToString();
}
```

### API Usage

The scenario here is probably a simple test app, since otherwise you'd care more about formatting.

```csharp
var sw = Stopwatch.StartNew();
// do something 
Console.WriteLine(sw.ToString());
```

### Alternative Designs

It could choose a different format, but `TimeSpan.ToString()` (which uses format 'c') is already the default on TimeSpan and consistent across locales. Also, it's what's used in the DebuggerDisplay, which is `$"{Elapsed} (IsRunning = {_isRunning})"`.

### Risks

Someone depending on ToString() returning the hard coded type name for some diagnostic purpose. Without hard data that that is common, this seems an acceptable risk.

**Comment by bartonjs** [comment]
Looks good as proposed

```C#
namespace System.Diagnostics;

public partial class Stopwatch
{
    public override string ToString() => Elapsed.ToString();
}
```

**Comment by ericmutta** [comment]
@danmoseley thanks for this! Please assign it to me and I will take a stab at it 👍 

PS: my plan of action is to fork the **dotnet/runtime** repo, clone the forked repo to my machine, do the work, push commits to my fork, then do a pull request...hopefully that's the right workflow for such changes.

**Comment by danmoseley** [comment]
Assigned. Yep, that's the workflow. 

You can look at 
https://github.com/dotnet/runtime/blob/main/docs/workflow/README.md

BTW, if you're relatively new to contributing here, we'd certainly be glad to get any tweaks to the contribution docs that you think would have helped you.

**Comment by ericmutta** [comment]
Thanks @danmoseley - I am reviewing the workflow docs, they are easy to read and so far, so good 👍 

PS: just submitted a small fix for [a broken link in those docs](https://github.com/dotnet/runtime/pull/87681).

**Comment by ericmutta** [comment]
@danmoseley I have finished reading all the workflow docs, they are really handy. I have also located the [Stopwatch.cs](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Stopwatch.cs) file where I believe the one-liner should be added. However, I have looked everywhere for the tests for the `Stopwatch` class but can't find them - could you please point me in the right direction?

**Comment by danmoseley** [comment]
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Runtime.Extensions/tests/System/Diagnostics/Stopwatch.cs

**Comment by danmoseley** [comment]
meanwhile, @ericmutta you can definitely run tests on the command line. that's what I do (but I'm a bit prehistoric). just following https://github.com/dotnet/runtime/blob/c94760e6b93a70ad0ce732366ecbbfc54c84fc44/docs/workflow/building/libraries/README.md#quick-start

the test for this should be super easy and not need debugging in VS. we should have a good VS workflow documented though.

**Comment by ericmutta** [comment]
> @danmoseley: the test for this should be super easy and not need debugging in VS.

As a new contributor, the interesting thing here is that VS helps me get the peace of mind that comes with being able to **directly execute the JUST the code I have changed**. This is a massive repo, if you do a command line build/test, there's a tonne of output and I found myself wondering "did it work? did it touch the code WRITTEN BY ME?". Thankfully, the tests for this did work in VS and I could just add a breakpoint, run it and SEE IT STOP ON MY CODE...which is nice 😄
