### ISSUE TITLE
SerializationGuard bloats the binary size on NAOT

### ISSUE THREAD

**Issue by aromaa** [dotnet/runtime#87470]
Currently when calling `Process.Start` it brings the whole reflection stack with it even when the `Switch.System.Runtime.Serialization.SerializationGuard.AllowProcessCreation` is specified. This adds about 1MB to the final binary size.

The `SerializationGuard` seems to use reflection internally to retrieve the switch [here](https://github.com/dotnet/runtime/blob/6df68007176331b572d1aef3bbc8b22e272b1a40/src/libraries/Common/src/System/Runtime/Serialization/SerializationGuard.cs#L20) which ends up rooting the reflection stack. It would be nice if the whole reflection guard concept would be possible to trim away on NAOT.

**Comment by aromaa** [comment]
Related #44369. Noticed it after I changed the title to be more general last minute. I'm more concerned about the `Process.Start` myself so this might be more actionable as a subset?

**Comment by danmoseley** [comment]
Cc @GrabYourPitchforks

**Comment by stephentoub** [comment]
> > It would be nice if the whole reflection guard concept would be possible to trim away on NAOT.
> 
> Can we at least introduce a feature switch to allow people who do not want to pay for the serialization guard overheads to opt-out of it?

I'd be in favor of deleting it entirely, especially with BinaryFormatter disabled by default in most workloads and scheduled for extinction. Short of that, a feature switch in the meantime makes sense. Could we not just use the existing one for BinaryFormatter to also guard the guard?

**Comment by MichalStrehovsky** [comment]
Per https://github.com/dotnet/runtime/issues/44369#issuecomment-724225762 this is also used in deserialization of DataTable so it's not BinaryFormatter only.

Looks like users can configure DataSet/DataTable deserialization to be a binaryformatter-like security nightmare. I wonder whether that mode should also be obsoleted together with BinaryFormatter.
