### ISSUE TITLE
[wasm][7.0-staging] `System.Runtime.Intrinsics`, and `System.Runtime` tests with AOT timing out on windows

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#87482]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=304251
Build error leg or test failing: Build Browser wasm windows Release LibraryTests_AOT
Pull request: https://github.com/dotnet/runtime/pull/87427

## Error Message

[EXECUTION TIMED OUT]

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "WasmTestOnBrowser-.*-System.Runtime.* END OF WORK ITEM LOG: Command timed out, and was killed",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by radical** [comment]
```
...
  [39/39] xunit.runner.utility.netcoreapp10.dll -> xunit.runner.utility.netcoreapp10.dll.bc

...
[EXECUTION TIMED OUT]
Exit Code:-3Executor timed out after 3600 seconds and was killed

['WasmTestOnBrowser-simd-System.Runtime.Intrinsics.Tests' END OF WORK ITEM LOG: Command timed out, and was killed]
```

The last thing the log shows is the AOT build step, and the job runs for over an hour. So, something got stuck/deadlocked. I'm re-running this on the original PR.

**Comment by lewing** [comment]
Not likely to be serviced at all
