### ISSUE TITLE
Cannot debug Blazor .net 8 WASM app

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/runtime#87491]
### Description

Using VS Version 17.7.0 Preview 1.0 I can create a Blazor WASM app that uses 

```
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.0-preview.4.23260.4" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.0-preview.4.23260.4" PrivateAssets="all" />
```

But when I upgrade to `8.0.0-preview.5.23302.2` I now get the following error when I try to run.

```
---------------------------
Microsoft Visual Studio
---------------------------
Process with an Id of 22448 is not running.
---------------------------
OK   
---------------------------
```

### Reproduction Steps

1. Install VS Version 17.7.0 Preview 1.0
2. New Blazor WASM app
3. Run it to confirm it works
4. Update NuGet packages to version `8.0.0-preview.5.23302.2`
5. Run

### Expected behavior

It should debug

### Actual behavior

It shows an error dialog box.

### Regression?

Works fine with 8.0.0-preview.5.23302.2

### Other information

.NET SDK:
 Version:   8.0.100-preview.4.23260.5
 Commit:    2268e7b15c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.4.23260.5\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-preview.4.23259.5
  Architecture: x64
  Commit:       84a3d0e37e

.NET SDKs installed:
  6.0.408 [C:\Program Files\dotnet\sdk]
  7.0.302 [C:\Program Files\dotnet\sdk]
  7.0.400-preview.23225.8 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.4.23260.5 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.4.23260.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.4.23259.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.4.23260.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by timheuer** [comment]
Waiting to hear if installing the NET 8 Preview 5 SDK fixes this -- @mrpmorris hadn't yet done that step

**Comment by mrpmorris** [comment]
This was the problem. I saw the package updates before I was aware there was a new installation available.

Sorry for the bother, and thank you!
