### ISSUE TITLE
How to perform ntlm authentication when using alpine as base image?

### ISSUE THREAD

**Issue by smartaquarius10** [dotnet/runtime#87568]
Hello,

We have followed the steps [suggested here](https://github.com/mikeTWC1984/gssntlm) but, nothing is working. We are trying to run the application in Azure AKS. Any suggestions please

**Code**
```
               var cred= new CredentialCache();
                cred.Add(new Uri("url"), "NTLM", new NetworkCredential("user", "pwd", "***.com"));

                var hwd= new HttpClientHandler() { Credentials = credentialsCache, PreAuthenticate = true };
                
                hwd.ClientCertificateOptions = ClientCertificateOption.Manual;
                hwd.ServerCertificateCustomValidationCallback =
                    (httpRequestMessage, cert, cetChain, policyErrors) => true;
                hwd.UseDefaultCredentials = false;

                var client = new FlurlClient(new HttpClient(hwd) { Timeout = new TimeSpan(0, 0, 30) };);
                 var response = await request
                    .AllowHttpStatus(HttpStatusCode.NotFound)
                    .WithHeader("Accept", "application/json")
                    .WithClient(client)
                    .WithHeader("Content-Type", "application/json; charset=utf-8")
                    .GetAsync();
```

**Exception**

```
Flurl.Http.FlurlHttpException: Call failed. NTLM authentication is not possible with default credentials on this platform: 
System.PlatformNotSupportedException: NTLM authentication is not possible with default credentials on this platform. at
```
**POD base image**
```

NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.16.3
PRETTY_NAME="Alpine Linux v3.16"
```
**dotnet version:- 6.0.14**

**Comment by mthalman** [comment]
[Triage] Moved to runtime repo since this isn't a Docker-specific question. This is strictly runtime-related and its interop with Alpine.

**Comment by wfurt** [comment]
The steps in link are conceptually right @smartaquarius10. .NET uses authentication layer from OS (e.g. GSSAPI) and it ls limited by OS capabilities. The sequence modifies alpine to add support for NTLM to GSSAPI. 

You can possibly build and run something from https://github.com/davidsh/NetworkingTests/tree/master/gssapitests to see if the mechanism was added correctly. 

now, the exception is about default credentials. You only added NTLM to CredentialCache. Are you sure that server is not sending `Negotiate` scheme? Either get packet captures or simply add the `Negotiate` as well. 

For .NET 7.0 you can possibly use [NegotiateAuthentication](https://learn.microsoft.com/en-us/dotnet/api/system.net.security.negotiateauthentication?view=net-7.0) directly but that is not available in 6.

**Comment by smartaquarius10** [comment]
@wfurt I used this docker file.. Everything build but after that this error started coming 

`GSSAPI operation failed with error - No credentials were supplied, or the credentials were unavailable or inaccessible (kdc reply did not match expectations).`

**Comment by wfurt** [comment]
1. Check if the container GSSAPI supports NTLM - using the tools I posted. 
2. Figure out if the authentication is doing pure NTLM or if this is on Negotiate path (that can do NTLM as well)

**Comment by wfurt** [comment]
you can always isolate the repro and run specific container on your local machine. And then you can capture outside of the container. For HTTPS you can use something like https://github.com/wfurt/PcapStream

You can also enable HTTP tracing as we are mostly after header exchange. 

It will be be difficult yo help you without answer to both questions.

**Comment by smartaquarius10** [comment]
@wfurt I have the curl command for that as well.. Can I use these tools with curl command

**Comment by smartaquarius10** [comment]
@wfurt I have checked in google chrome developer tools.. This is coming in response headers
![image](https://github.com/dotnet/runtime/assets/7824529/dcb50f8d-2878-40e0-9695-c6094795599d)

**Comment by wfurt** [comment]
right. so the code fragment you originally posted will not work as "NTLM" does not match "Negotiate". Did you add the `Negotiate` mechanism as I suggested?

**Comment by smartaquarius10** [comment]
Should we add this negotiate along with building gssntlm package inside alpine

**Comment by smartaquarius10** [comment]
@wfurt After banging my head with this alpine I have finally shifted to the base image of debian type flavour. I need to complete this migration otherwise there will be a big money loss. 

However, by any chance can u suggest the lightest debian type base image for .net app. I have used bullseye slim and tried self contained .net app with `publishtrim=true `still its 374 mb of file. Any suggestions to decrease the size. 

I have also asked this question [here](https://github.com/dotnet/dotnet-docker/discussions/4678)

**Comment by wfurt** [comment]
this is more question for Linux distribution people. There will be some unfixable difference IMHO e.g. glibc vs musl-libc. You can probably make list of packages and start removing the one you do not need. Package manager should tell you if you cut something you need. 

long term, best solution may be contributing gss-ntlm package to Alpine.

**Comment by smartaquarius10** [comment]
@wfurt Definitely.. GSS-ntlm has to be in alpine..
