### ISSUE TITLE
FrameworkList.xml generated in libraries build for live ref pack does not include source generators

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#87582]
The FrameworkList.xml file that's generated for the ref pack that the build outputs to `MicrosoftNetCoreAppRefPackDir` does not include any of our analyzer or generator assemblies. As a result, any tests that depend on this ref pack don't reference ref-pack generators by default.

This is particularly difficult for our trimming tests, which have their project files generated and would need modification to the generation script to support this.

Also, solving this would help make our "out-of-band" projects even closer to a "not in dotnet/runtime" project by removing the requirements for them to have project references to in-box generators.

**Comment by ViktorHofer** [comment]
Yes, we noticed that a while ago in https://github.com/dotnet/runtime/pull/74897 and I submitted https://github.com/dotnet/runtime/pull/75093 to fix that but hadn't had time to finish the PR.

**Comment by jkoritzinsky** [comment]
Another way to fix it other than #75093 would be to produce the ref-pack that we test with from the Microsoft.NETCore.App.Ref.sfxproj project. That would require a few changes to how we track "is this project in-box" (ie NetCoreAppLibrary.props) though as I found through some simple prototyping.

**Comment by ViktorHofer** [comment]
That's the ideal, yes but I see that as a ideal middle / long-term goal. Short term, fine-tuning the fake ref pack orchestration and making it analyzer aware should be sufficient.
