### ISSUE TITLE
[RyuJIT][LSRA] Restructure LinearScan::isAssigned to improve efficiency

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/runtime#8758]
`bool LinearScan::isAssigned(RegRecord* regRec ARM_ARG(RegisterType newRegType))` calls `bool LinearScan::isAssigned(RegRecord* regRec, LsraLocation lastLocation ARM_ARG(RegisterType newRegType))` with `lastLocation` set to `MaxLocation`. This doesn't make it easy for the C++ compiler to optimize away the check in this case.

category:throughput
theme:register-allocator
skill-level:intermediate
cost:medium

**Comment by kunalspathak** [comment]
We do not take `lastLocation` into account anymore.
