### ISSUE TITLE
JsonSerializer should support field as well as properties

### ISSUE THREAD

**Issue by YohDeadfall** [dotnet/runtime#876]
_Updated by @layomia:  I'm pasting the API approved in https://github.com/dotnet/runtime/issues/34558. Please see that issue for review notes and further discussion._

```C#
namespace System.Text.Json
{
    public partial class JsonSerializerOptions
    {
        public bool IgnoreReadOnlyFields { get; set; }
        public bool IncludeFields { get; set; }
    }
}
namespace System.Text.Json.Serialization
{
    [AttributeUsage(AttributeTargets.Property |
                    Attributes.Field, AllowMultiple = false)]
    public sealed class JsonIncludeAttribute : JsonAttribute
    {
        public JsonIncludeAttribute();
    }
}
```

<details>
<summary>
Original proposal (click to view)
</summary>

There is no way to serialize and deserialize fields using `JsonSerializer`. 

While public fields are [generally not recommended](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/fields), they are used in .NET itself (see value tuples) and by users.

This feature was scoped out of v1 (3.x) due to lack of time, as we prioritized supporting simple POCOs with public properties.

We elected to have an opt-in model for field support because it would be a breaking change to support them by default, and also because public fields are generally not recommended. Other serializers, including `Newtonsoft.Json`, `Utf8Json`, and `Jil`, support this feature by default.
</details>

**Comment by marcuslindblom** [comment]
Any progress here or what is the prefered workaround for this issue?

**Comment by YohDeadfall** [comment]
Previously it was blocked by the team due to optimizations. Recently pinged @ahsonkhanon this, but have received no answer.

Anyway I'm going to move the PR to dotnet/runtime in a few days.

**Comment by marcuslindblom** [comment]
@YohDeadfall does this address named tuple serialization as well? I use Newtonsoft Json for now but it serialize this `(string Landscape, string Portrait) Images;` as `Item1` and `Item2`.

**Comment by YohDeadfall** [comment]
Don't think that named tuples worth support because names available only in very limited number of cases and in most of them it won't work well. Names provided by `TupleElementNamesAttribute` and, as you know, attributes cannot be applied to variables. Therefore, names can be serialized when a value tuple is a part of another object, but this probably means a bad design.

**Comment by marcuslindblom** [comment]
@YohDeadfall Ok, I see. Do I understand you correct if I could use `TupleElementAttribute` if I have a model like this?

```c#
public class Home {
    public string Heading { get;set; }
    public ArtDirection ArtDirection { get;set; }
  }

  public class ArtDirection {
    public string Alt { get; set; }
    public (string Landscape, string Portrait, string Fallback) Images { get; set; }
  }
```

**Comment by YohDeadfall** [comment]
Yes, it is only one possible way to get names of tuple members, but in other cases it isn't possible (when you pass a tuple directly to the serializer). Therefore, supporting `TupleElementNamesAttribute` would cause different behavior in different cases and misunderstanding by users. The final decision on this should be made by Microsoft team.

It's better to have a class/struct for that kind of scenario.

/cc @ahsonkhan @steveharter @layomia

**Comment by ahsonkhan** [comment]
From @newpost in https://github.com/dotnet/runtime/issues/1519

> ```cs
> [ApiController]
>     [Route("[controller]")]
>     public class DefaultController : ControllerBase
>     {
>         [HttpGet]
>         public ValueTuple<int, int, int> Index()
>         {
>             return new ValueTuple<int,int,int>(1,2,3);
>         }
>     }
> ```
> 
> actual output: {}.
> expected output:{"item1":1,"item2":2,"item3":3}

**Comment by ahsonkhan** [comment]
I mention a workaround for `ValueTuples` (up to 3) based on custom converters if folks need it.
https://github.com/dotnet/runtime/issues/1519#issuecomment-572751931

**Comment by ahsonkhan** [comment]
From @Greypuma in https://github.com/dotnet/runtime/issues/32294

> I was trying to serialize an object into json. I get an empty string. below is the code i used.
> using System.Linq;
> using System.Text;
> using System.Threading.Tasks;
> using System.Text.Json;
> using System.Text.Json.Serialization;
> using Newtonsoft.Json;
> 
> namespace test
> {
> public class AdbEmulator
> {
> //needs to be public otherwise wont work
> public string name;
> internal string attached;
> 
> ```
> }
> public class AndroidJson
> {
>     public AndroidJson()
>     {
>         AddData();
>     }
>     public void AddData()
>     {
>         AdbEmulator adb1 = new AdbEmulator() { name = "emulator-5554", attached = "ll" };
>         emulators.Add(adb1);
>         string jsonAdb = System.Text.Json.JsonSerializer.Serialize<AdbEmulator>(adb1);
>         string newtonjson = Newtonsoft.Json.JsonConvert.SerializeObject(adb1);
>     }
> }
> ```
> 
> Program.cs
> static void Main(string[] args)
> { AndroidJson aj = new AndroidJson(); }
> 
> Output
> jsonAdb = {}
> newtonjson ={"name":"emulator-5554"}
> 
> I'm not sure why newtonsoft works and the microsoft one does not.
> i'v'e tried the code in an dotnet core 3.1 project and windows application ( including the nuget package for that project).

**Comment by JVimes** [comment]
@YohDeadfall, it looks like you have a [pull request for this](https://github.com/dotnet/corefx/pull/39254) in the old repo. Should that be moved here, like maryamariyan [suggested](https://github.com/dotnet/corefx/pull/39254#issuecomment-550501731)?

**Comment by YohDeadfall** [comment]
Already did this by #2192, but since field addition is a breaking change there should be an API review. Will write all things @layomia requested tomorrow or on Saturday.

**Comment by YohDeadfall** [comment]
@layomia @karelz updated the first message to list problems which block the PR.

**Comment by rafaelbenavent** [comment]
Any update on this?

**Comment by layomia** [comment]
From @leung85 in https://github.com/dotnet/runtime/issues/34001:

> core version 3.1.102
> 
> ```
>  public class TestDict
>     {
>         public Dictionary<string, string> Test = new Dictionary<string, string>(){
>             { "09:00", "In"},
>             { "18:00", "Out"}
>         };
>     }
> 
>  var option = new JsonSerializerOptions();
>             option.WriteIndented = true;
>             string configJson = System.Text.Json.JsonSerializer.Serialize(new TestDict(), option);
> ```
> 
> the configJson return `{}`,
> But it can be serialized if just use Dictionary<string, string> directly.

**Comment by layomia** [comment]
@YohDeadfall, are you still interested in implementing this feature? API approved in https://github.com/dotnet/runtime/issues/34558:

```C#
namespace System.Text.Json
{
    public partial class JsonSerializerOptions
    {
        public bool IgnoreReadOnlyFields { get; set; }
        public bool IncludeFields { get; set; }
    }
}
namespace System.Text.Json.Serialization
{
    [AttributeUsage(AttributeTargets.Property |
                    Attributes.Field, AllowMultiple = false)]
    public sealed class JsonIncludeAttribute : JsonAttribute
    {
        public JsonIncludeAttribute();
    }
}
```

**Comment by YohDeadfall** [comment]
Will take a look and implement. Probably will resurrect the closed PR with the requested API above.

**Comment by mnns** [comment]
Spent a lot of time understanding why I don't see the fields in my output. Anyway, using 3.1, still don't see this option. Any news? thanks

**Comment by YohDeadfall** [comment]
It should be .NET 5 feature.

**Comment by layomia** [comment]
@YohDeadfall, can you take another look soon? Field support is one of the [top priorities for System.Text.Json in 5.0](https://github.com/dotnet/runtime/projects/25#column-8165016), and we'd like to get the feature in a preview for folks to try.

**Comment by YohDeadfall** [comment]
Planned to reopen the PR on this weekend. Working on this won't be problematic, but the snake case naming policy will since there is a stuck discussion.

**Comment by layomia** [comment]
> Planned to reopen the PR on this weekend.

Sounds good 👍 

> but the snake case naming policy will since there is a stuck discussion.

We should address snake case separately from this issue - https://github.com/dotnet/runtime/issues/782#issuecomment-629435686.

**Comment by YohDeadfall** [comment]
While it isn't too late, there are a few `Ignore` properties in `JsonSerializerOptions`. Should `IncludeFields` be renamed to `IgnoreFields` with the default value `true` for consistency?

**Comment by layomia** [comment]
> Should IncludeFields be renamed to IgnoreFields with the default value true for consistency?

This was considered, but we chose `IncludeFields` so that the default value would be `false` for consistency with other options (where CLR default is used).

**Comment by jessicah** [comment]
Could we have the JsonInclude also apply at the struct level?

**Comment by YohDeadfall** [comment]
What did you mean? It's not working for structs or something else?
