### ISSUE TITLE
System.Threading.RateLimiting is missing XML documentation for public API

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#87604]
See https://github.com/dotnet/runtime/pull/84917 for more context.

`System.Threading.RateLimiting` is a new library which contains public API that isn't yet documented. Public API is displayed on docs.microsoft.com and in Intellisense via tooling. We should document the API and then remove the `NoWarn=1591` from the project file.

@BrennanConroy

**Comment by BrennanConroy** [comment]
Oh is it just one class missing a comment?
https://github.com/dotnet/runtime/blob/32cf743c8daa42da56b4a1ca938a1020be139cc0/src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/ReplenishingRateLimiter.cs#L6

**Comment by ViktorHofer** [comment]
I don't have the build available anymore that showed the ones that were missing. IIRC it's just a handful of APIs. After https://github.com/dotnet/runtime/pull/84917 is merged, you can repro the failures by removing the `NoWarn` from the project file and doing a `dotnet build`.
