### ISSUE TITLE
[NativeAOT] Properly implement targeting iOS-like platforms rather than pretending to be macOS

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/runtime#87610]
## Description

Initial support for targeting iOS-like platforms with NativeAOT introduced with: https://github.com/dotnet/runtime/pull/81476 uses a workaround in JIT interface: https://github.com/dotnet/runtime/blob/8f19f4ebd511994be27a2e1f4c88424a26f91e7c/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs#L3066 
hardwiring the compilation as if the target platform is macOS which also brings along corresponding implications on the native side.

**Comment by MichalStrehovsky** [comment]
What problem is this causing? If there are ABI differences (that this bit controls in the JIT), I'd expect we wouldn't be able to run a MAUI app.

**Comment by jkotas** [comment]
Is this issue just about renaming macOS to OSXLike in the JIT and JIT/EE interface?

**Comment by filipnavara** [comment]
Does the flag control the ABI only, or can it have effect on something like the minimum expected architecture baseline? (which is different between M1 ARM and Axx ARM).

**Comment by MichalStrehovsky** [comment]
Instruction sets are configured here; the JIT doesn't decide this:

https://github.com/dotnet/runtime/blob/e141ce4821bd63ebe2ebe8780ebd844f0f467238/src/coreclr/tools/Common/InstructionSetHelpers.cs#L26-L34

**Comment by akoeplinger** [comment]
> Is this issue just about renaming macOS to OSXLike in the JIT and JIT/EE interface?

That is an option, but when I initially did the iOS changes for NativeAOT I tried to add a new platform CORINFO_IOS etc but then hit some issues with the consistency checks here: https://github.com/dotnet/runtime/blob/0570583829c7656778c2b0e8f20570627d6ecde1/src/coreclr/jit/compiler.cpp#L5852-L5855

Back then I didn't have time to investigate further so we went with pretending to target macOS for iOS.

**Comment by MichalStrehovsky** [comment]
> Back then I didn't have time to investigate further so we went with pretending to target macOS for iOS.

The question is if there's anything different for iOS that we would need a new value to distinguish it in RyuJIT. We distinguish it as TargetOS in the C# part of the compiler, but only because there's one spot in the LLVM object writer that puts this into the object file (99.9% of the compiler doesn't see it as a different OS). Is there a part of RyuJIT that needs to know?

**Comment by akoeplinger** [comment]
As far as I can see the JIT would be fine with a generic "Apple" value, except for the compatibility checks. E.g. this one:
https://github.com/dotnet/runtime/blob/0570583829c7656778c2b0e8f20570627d6ecde1/src/coreclr/jit/compiler.cpp#L5874-L5876

I assume we also use the Unix jit variant for iOS x64 (Simulator) today so presumably it works fine.

If you think that we don't need this distinction in the JIT I can send a PR to rename OSX -> Apple.

**Comment by MichalStrehovsky** [comment]
> As far as I can see the JIT would be fine with a generic "Apple" value, except for the compatibility checks. E.g. this one:

That compatibility check also uses `TargetOS::IsMacOSX` above which is currently broken #87794 without anything noticing - I don't know what this actually does.

> If you think that we don't need this distinction in the JIT I can send a PR to rename OSX -> Apple.

If we're only discussing renaming this within the JIT, this is now fully a JIT issue, so I'm moving this to that area and leaving the call on the JIT team.

**Comment by JulieLeeMSFT** [comment]
cc @dotnet/jit-contrib. @jakobbotsch please take a look.

**Comment by jakobbotsch** [comment]
> If you think that we don't need this distinction in the JIT I can send a PR to rename OSX -> Apple.

Indeed I don't think we need the distinction. Feel free to submit a PR to rename the value. I'm going to move the issue to future since this is just a cosmetic change.
