### ISSUE TITLE
Minimizing size of Dotnet WebAssembly Browser app

### ISSUE THREAD

**Issue by sps014** [dotnet/runtime#87617]
Hello, I have Dotnet WebAssembly Browser app. The size of default dotnet.native.wasm with .Net 8 preview 5 is 2.8 MB.

On other hand In blazor WebAssembly app we can have PublishTrimmed and TrimMode to reduce the size to 300-400 KB. These 2 properties do not have effect on Web Assembly Browser app. Trimming doesn't takes place. Also Is there way to trim timezone and other data.

Is there any way to allow trimming to get smaller dotnet wasm in Web assembly browser application? Is there any roadmap for it similar to blazor size reduction tasks?

Thanks

**Comment by lewing** [comment]
Are you publishing the app?  Is PublishTrimmed set to true?

**Comment by sps014** [comment]
> Are you publishing the app?  Is PublishTrimmed set to true?

Yes , I used these flags in csproj.
These flags seems to have no effect when publishing.

**Comment by maraf** [comment]
We are on a journey to unify behavior between Blazor and WebAssembly Browser app. Roadmap for this work is in https://github.com/dotnet/runtime/issues/70762. 

I'll check the `PublishTrimmed` and `TrimMode` flags. 

Timezone trimming is currently not possible due to change how it's delivered and we are working on enabling it again https://github.com/dotnet/runtime/pull/87284

**Comment by maraf** [comment]
Both `PublishTrimmed` and `TrimMode` are set by default publishing both the WebAssembly app and Blazor app. 

I got the same size for `dotnet.native.wasm` in both apps on .NET 8 preview 5 (~ 2.6MB). You can disable globalization with `InvariantGlobalization=true` (~ 1.3 MB). Finally you can save some KB with `EventSourceSupport=false` and `UseSystemResourceKeys=true`. More info at https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options#trimming-framework-library-features

The timezone data has ~ 300KB which is not trimmable at the moment.

**Comment by sps014** [comment]
@maraf Thanks for this valuable information.

**Comment by maraf** [comment]
I'm happy to help! I'm going to close this issue, feel free to reopen it or open a new one if you have further questions.
