### ISSUE TITLE
List<T>.Enumerator is still boxed

### ISSUE THREAD

**Issue by RichardD2** [dotnet/runtime#87616]
### Description

When iterating over a `List<T>` with a `foreach` loop, the code uses the `List<T>.Enumerator` struct directly, which avoids allocating an object on the heap, and avoids all virtual method calls. 

At least, that's what it should do.

Unfortunately, `IDisposable` ruins things. Rather than directly call the `Dispose` method on the struct, the struct is cast to `IDisposable` first. That means the enumerator will be boxed, and the `Dispose` call will be a virtual method call.

It seems the magic "duck typing" for `IEnumerable<T>` isn't applied to `IDisposable`.

### Example:

```csharp
public void M(List<int> source)
{
    foreach (int value in source)
    {
        Console.WriteLine(value);
    }
}
```

#### Expected compilation results:

```csharp
public void M(List<int> source)
{
    List<int>.Enumerator enumerator = source.GetEnumerator();
    try
    {
        while (enumerator.MoveNext())
        {
            int value = enumerator.Current;
            Console.WriteLine(value);
        }
    }
    finally
    {
        enumerator.Dispose();
    }
}
```

#### Actual compilation results:

```csharp
public void M(List<int> source)
{
    List<int>.Enumerator enumerator = source.GetEnumerator();
    try
    {
        while (enumerator.MoveNext())
        {
            int value = enumerator.Current;
            Console.WriteLine(value);
        }
    }
    finally
    {
        ((IDisposable)enumerator).Dispose();
    }
}
```

[SharpLab](https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoBAGABAlAFgG5NMEBmfJXAYV0wG9NdX8qFDcBZACgBkoAZwAuAHlgiAfLiEB7AK4AnAMYBTAJQMMbXMx262AMzlK1EFQAtcvSbgBuEADYK1uWLMWrNLQ631+fgQAnLyOLpqkBn4Avr6scdHaupT4XAByvAQUEjDSnsrqGvF6JbomZhbWtnkOzq7uMAXexUm6AYEpKKHhrhpRnYm6iTFAA)

**Comment by stephentoub** [comment]
> Unfortunately, IDisposable ruins things. Rather than directly call the Dispose method on the struct, the struct is cast to IDisposable first. That means the enumerator will be boxed, and the Dispose call will be a virtual method call.

This isn't the case.  If you look at the emitted IL, you'll see this:
```
            IL_0020: ldloca.s 0
            IL_0022: constrained. valuetype [System.Collections]System.Collections.Generic.List`1/Enumerator<int32>
            IL_0028: callvirt instance void [System.Runtime]System.IDisposable::Dispose()
            IL_002d: endfinally
```
There's no boxing there.  A constrained call is being made to Dispose.

**Comment by RichardD2** [comment]
Aha! I hadn't seen that instruction before. That makes sense. Thanks for replying. :)
