### ISSUE TITLE
Can not build System.Runtime solution inside VS. The type or namespace name 'SearchValues<>' could not be found

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/runtime#87624]
### Description

Some `System.Runtime` tests FAIL on my computer when I run them from root folder `build -subset clr+libs+libs.tests -test -rc Release`. All libraries compiled without any error, but some `System.Runtime` tests FAIL on my computer.
When I try to debug tests inside VS, I can not build `System.Runtime.sln` solution inside Visual Studio and run tests inside Visual Studio.

### Reproduction Steps

Open `System.Runtime.sln` inside Visual Studio and try to build it.

### Expected behavior

Success build.

### Actual behavior

Compilation error at https://github.com/dotnet/runtime/blob/4302b80fa089ace2d6fd404af99efddd1f121871/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexParser.cs#LL2080C22-L2080C22 line.

```cs
        private static readonly SearchValues<char> s_metachars =
            SearchValues.Create("\t\n\f\r #$()*+.?[\\^{|");
```

|Severity	|Code	|Description	|Project	|File	|Line	|Suppression |State|
|-----|-----|-----|-----|-----|-----|-----|-----|
|Error	|CS0246	|The type or namespace name 'SearchValues<>' could not be found (are you missing a using directive or an assembly reference?)	|System.Text.RegularExpressions.Generator (net8.0)	|C:\AProj\runtime\src\libraries\System.Text.RegularExpressions\src\System\Text\RegularExpressions\RegexParser.cs	|2080	|Active| |

### Regression?

Windows 10, last VS, last sources from the `main` branch, and so on...

### Known Workarounds

Change line to
```cs
        private static readonly IndexOfAnyValues<char> s_metachars =
            IndexOfAnyValues.Create("\t\n\f\r #$()*+.?[\\^{|");
```

### Configuration

Windows 10, last VS, last sources from the `main` branch, and so on...

**Comment by ViktorHofer** [comment]
cc @stephentoub for the Regex source generator

**Comment by stephentoub** [comment]
`IndexOfAnyValues<>` was renamed to `SearchValues<>`.  The regex source generator spits out use of `SearchValues<>` because that's what it's now called.  If you're getting compilation errors saying that can't be found, you must be building against an older runtime that still uses the old name.
