### ISSUE TITLE
[API Proposal]: Interface for Exceptions that have child/aggregate Exceptions

### ISSUE THREAD

**Issue by DigitlWorld** [dotnet/runtime#87625]
### Background and motivation

The team I'm working with recently came across an unhandled `ReflectionTypeLoadException` in an area where we weren't expecting it. We have diagnostic logging in our product that logs any exceptions, including unhandled. However, upon looking at the log, we encountered this message:

> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

In order to further debug this issue, we now have to go in and add specific logging for `ReflectionTypeLoadException` to iterate over the `LoaderExceptions` property. 

Our generic logging solution knows to iterate `InnerException` and `InnerExceptions` (for `AggregateException`), however, `ReflectionTypeLoadException` does not adhere to the AggregateException pattern, and as such, proper generic logging requires knowing how to log this type _specifically_.

I would like to see a potential interface added to the runtime that better abstracts the "inner exceptions" concepts in a way that allows for generic logging and traversal of exception data.

### API Proposal

```csharp
namespace System;

public interface IAggregateException<out T> where T : Exception
{
    // This collection should aggregate any "sub" exceptions that implementing Exception
    // type contains, even if the implementing type is not a AggregateException.
    IEnumerable<T> InnerExceptions { get; }
}
```

### API Usage

```csharp
namespace System;

public class AggregateException : Exception, IAggregateException<Exception>
{
    // ...
}
```

```csharp
namespace System.Reflection;

public class ReflectionTypeLoadException : SystemException, IAggregateException<Exception>
{
    // ... 

    public IEnumerable<Exception> InnerExceptions 
    {
        get
        {
            foreach( var exception in LoaderExceptions )
            {
                yield return exception;
            }
        }
    }
}
```
```csharp
// Example generic logging logic
public static void LogException( Exception exception )
{
    // Do logging stuff here...
    if( exception is IAggregateException<Exception> aggregateException )
    {
        foreach( var innerException in aggregateException.InnerExceptions )
        {
            LogException( innerException );
        }
    }
}
```

### Alternative Designs

I prefer the explicitness of having a dedicated `IAggregateException` interface, however I could see an argument for that being too verbose/specific and simply having exception types that have inner exception implement `IEnumerable<Exception>` and making that part of the runtime/API guidelines.

### Risks

Potentially low risk, as this adds an API footprint without potentially breaking/changing existing APIs.

Requires updating any existing system exceptions to implement this interface if they don't directly inherit from AggregateException.

**Comment by svick** [comment]
```c#
public interface IAggregateException<out T> where T : IException
```

There is no `IException` interface and I don't see much reason to introduce it. In fact, is there even a reason for this to be generic?

**Comment by danmoseley** [comment]
Can your logging simply do ToString()?

**Comment by DigitlWorld** [comment]
> ```cs
> public interface IAggregateException<out T> where T : IException
> ```
> 
> There is no `IException` interface and I don't see much reason to introduce it. In fact, is there even a reason for this to be generic?

I apologize. Force of habit. 😄 I intended that to just be `Exception`. Exception unambiguously serves as the base type for all exceptions, so there is not a reason to add an interface for it.

**Comment by DigitlWorld** [comment]
> Can your logging simply do ToString()?

Sure, however if my system, or another system wanted to do something more specific, or wanted more control over how it logged an exception beyond the offering of each exception's `ToString()` implementation, we're back here. Maybe some logging system simply wants to output messages and not stack traces at a certain log detail level, or wants to separate the logging of child exceptions into another log. 

While I am proposing this as a result of a specific scenario my team ran into, it's less about solving my specific problem. To me, this is about establishing an architectural pattern in the runtime/ecosystem that expresses "this exception has child/inner exceptions" unambiguously. Today, `AggregateException` is not sufficient because it is required in the ancestry of a given type, and sometimes (like in this case) the exception's base type may need/want to be something different. To me, this is exactly a case for some sort of interface to describe this cross-cutting concern.

**Comment by davidfowl** [comment]
How many exceptions would implement this? How would the consumer go about using this generic interface? Can you show an example from your scenario?

**Comment by DigitlWorld** [comment]
> How many exceptions would implement this? How would the consumer go about using this generic interface? Can you show an example from your scenario?

I would need to do analysis over the various Exception implementations in the Runtime to see if any besides `AggregateException` and `ReflectionTypeLoadException` have "child" exceptions, but my expectation would be that any exception implementation that has "child" exceptions would implement this interface, or for the alternative design, at a minimum implement `IEnumerable<Exception>`.

Use cases are wide, and I can't bring specific code to this, however my example usage in the original submission lays out an example (3rd code block under the `API Usage` section above).

**Comment by davidfowl** [comment]
```
if( exception is IAggregateException<Exception> aggregateException )
    {
        foreach( var innerException in aggregateException.InnerExceptions )
        {
            LogException( innerException );
        }
    }
```

Why is IAggregateException generic?

**Comment by DigitlWorld** [comment]
> ```
> if( exception is IAggregateException<Exception> aggregateException )
>     {
>         foreach( var innerException in aggregateException.InnerExceptions )
>         {
>             LogException( innerException );
>         }
>     }
> ```
> 
> Why is IAggregateException generic and what would T be other than exception? This forces your code to also be generic with the same constraint (making it viral).

Not hard set on it. It was just a fairly quick proposal. Generic/constraint was intended to allow the implementer to be more specific if they only aggregate specific types/subclasses of exceptions. I'm open to dropping the new interface conceptually, per my alternative above, in favor of just having these types of exceptions implement `IEnumerable<Exception>` if that's a lighter-weight path.

My only real goal here is to establish a pattern in the runtime/ecosystem that always communicates, unambiguously, "this exception has child exceptions, and here's where to get them". Only provided proposed concepts both, because the proposal form requires it, and because I know it will help illustrate what I'm getting at. 😄

**Comment by tannergooding** [comment]
This API would be fairly niche and difficult to consume properly, it would only work on newer versions of .NET and only for the built-in interfaces intially.

Given the primary issue is with `ReflectionTypeLoadException` and such aggregate exceptions are rare, it seems like it'd be overall better and easier to special-case this one other type.

I'm happy to hear additional feedback or to have further discussion on the design/shape, I just don't think its something where the benefit justifies the cost and complexity at the moment.
