### ISSUE TITLE
Remove traceparent header from http requests

### ISSUE THREAD

**Issue by SleepyF0X** [dotnet/runtime#87635]
https://github.com/dotnet/runtime/blob/fe866e6485e1ba4423e879c9d00a6c0edeecea4f/src/libraries/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs#LL139C13-L142C14

I wanna to remove traceparent header from http request, but only for one HttpClient in my project. Can do it? Now i see that traceparent header added here by OpenTelemetry

**Comment by stephentoub** [comment]
If you set your SocketsHttpHandler's ActivityHeaderPropagator property to `DistributedContextPropagator.CreateNoOutputPropagator()`, it shouldn't add those headers.

**Comment by ManickaP** [comment]
Stephen;s comment answers the question, so I'm closing this. @SleepyF0X feel free to re-open if you hit any more problems.
