### ISSUE TITLE
Things needing System.Net.Security.Native may not work on Bionic

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#87665]
https://github.com/dotnet/runtime/pull/87595#discussion_r1231110751

We're not building System.Net.Security.Native when targeting Bionic, but it also looks like the managed part is not configured in a way that would avoid calling into this library.

Cc @directhex

**Comment by wfurt** [comment]
Is this primarily about TLS? NegotiateStream will be probably partially fixed by  #86948.

**Comment by filipnavara** [comment]
There's no GSSAPI on linux-bionic. We should get it to the same plan as Android (managed NTLM).

**Comment by filipnavara** [comment]
Actually, this is a bit tricky since there's no linux-bionic TFM, so we cannot easily make a special version of System.Net.Security assembly. My current plan is to consolidate all the "offending" code into that single assembly (prerequisities: #86948, #86956). Then we can decide what to do next. One option is to disable the GSSAPI (/System.Net.Security.Native) code paths at runtime. In fact, I wanted to offer an option to use the managed NTLM on macOS, so this would be very similar change.

**Comment by wfurt** [comment]
May also help with https://github.com/dotnet/runtime/issues/87568. GSSAPI exist for Kerberos but not for NTLM. Maybe handle legacy NTLM in managed code and leave Negotiate to GSSAPI...?

**Comment by filipnavara** [comment]
> Maybe handle legacy NTLM in managed code and leave Negotiate to GSSAPI...?

There are the multiple possible combinations:
1) Use GSSAPI for NTLM, Kerberos, and Negotiate
2) Use managed NTLM and Negotiate, no Kerberos
3) Use GSSAPI for Kerberos, managed for NTLM and Negotiate (wrapping both the Kerberos and NTLM)
4) Use GSSAPI for Kerberos and Negotiate, managed NTLM only when asked specifically for NTLM

Today we use option 1) on all platforms except Android and tvOS, which are on option 2).

I'd like to add an implementation of 3) with a configuration switch, and fallback to 2) if GSSAPI is not available. I don't have a use case for option 4) but it would be generally easier to implement than option 3) if there's a strong desire or preference.

**Comment by wfurt** [comment]
Can we get 3) working? I was thinking originally about 4) as it would be simple split. And NTLM would work only for legacy.

**Comment by filipnavara** [comment]
> Can we get 3) working?

I think we can. I may have even done that in one the stale branches last year...

**Comment by filipnavara** [comment]
We likely still need to fix the P/Invokes in tests but product-wise this should be fixed.

**Comment by MichalStrehovsky** [comment]
@steveisok the relevant tests are still disabled on Mono-Bionic (they got disabled without a tracking issue, which is how this got missed in the first place). Do you want to keep this open to track reenabling?

https://github.com/dotnet/runtime/blob/31bcc752fed783227eba08ece7e07a690aa12d11/src/libraries/tests.proj#L156

**Comment by filipnavara** [comment]
Are there any instruction on how to run the NativeAOT tests on Linux Bionic? I found the scripts for the Mono legs but not NativeAOT.

**Comment by MichalStrehovsky** [comment]
> Are there any instruction on how to run the NativeAOT tests on Linux Bionic? I found the scripts for the Mono legs but not NativeAOT.

I don't think anyone ever ran these on NativeAOT. This issue tracks the Mono test exclusion that has been there since the beginning. The problem was found during NativeAOT bringup, but not because we tried to execute the test. We don't have budget to set up regular NativeAOT testing in 8.0 since this is all experimental there.

**Comment by wfurt** [comment]
would this be mostly fixed by #95274?

**Comment by rzikm** [comment]
Should be. I added some tests which explicitly enable NTLM tests on bionic tfm
