### ISSUE TITLE
Microsoft.Extensions.DependencyInjection.Specification.Tests is missing API documentation

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#87709]
See https://github.com/dotnet/runtime/pull/84917 for more context.

The compiler generated XML file for Microsoft.Extensions.DependencyInjection.Specification.Tests is shipping to customers via the nuget package and is missing public API documentation. The above linked PR disables the compiler error CS1591 until all the API is documented.

When working on this, remove the NoWarn=1591 setting from the project file.

**Comment by steveharter** [comment]
Is this worth it? Documenting the test types and individual tests? We could make the test methods non-public to avoid documenting each test.

**Comment by ViktorHofer** [comment]
It's probably not a priority. I don't know if we can make the test methods non-public. I thought those are the "public API" that other DI libraries test against.

**Comment by steveharter** [comment]
I believe a `[Fact]` test method can be private but the class must be public.

These are the tests that other DI implementations can use to test against, however the tests are self-describing and unless there is a real benefit to creating the doc and maintaining it, I suggest closing this issue.

**Comment by ViktorHofer** [comment]
Before closing, consider updating this comment here: https://github.com/dotnet/runtime/blob/45acd380b37c9ee883070a70a2ef2cb7eca77683/src/libraries/Microsoft.Extensions.DependencyInjection.Specification.Tests/src/Microsoft.Extensions.DependencyInjection.Specification.Tests.csproj#L12-L13

**Comment by steveharter** [comment]
Just the comment needs to be updated - something like "Tests do not need to be documented."
