### ISSUE TITLE
R2R known test failure

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#87716]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=310510&view=results
Build error leg or test failing: Regressions\\coreclr\\GitHub_54719\\test54719\\test54719.cmd
Pull request: https://github.com/dotnet/runtime/pull/87588

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "at Internal.TypeSystem.CastingHelper.CanCastToInternal",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

https://github.com/dotnet/runtime/issues/87663

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[311865](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311865)|dotnet/runtime|[Regressions/coreclr/GitHub_54719/test54719/test54719.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311865&view=ms.vss-test-web.build-test-results-tab&runId=6373838&resultId=118613)||
|[311712](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311712)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311712&view=ms.vss-test-web.build-test-results-tab&runId=6365040&resultId=120196)||
|[311746](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311746)|dotnet/runtime|[Regressions/coreclr/GitHub_54719/test54719/test54719.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311746&view=ms.vss-test-web.build-test-results-tab&runId=6367388&resultId=101121)||
|[311711](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311711)|dotnet/runtime|[Regressions/coreclr/GitHub_45037/test45037/test45037.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311711&view=ms.vss-test-web.build-test-results-tab&runId=6367088&resultId=118586)||
|[311597](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311597)|dotnet/runtime|[Regressions/coreclr/GitHub_54719/test54719/test54719.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311597&view=ms.vss-test-web.build-test-results-tab&runId=6363342&resultId=120491)||
|[311578](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311578)|dotnet/runtime|[Regressions/coreclr/GitHub_45037/test45037/test45037.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311578&view=ms.vss-test-web.build-test-results-tab&runId=6361720&resultId=118613)||
|[311497](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311497)|dotnet/runtime|[Regressions/coreclr/GitHub_54719/test54719/test54719.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311497&view=ms.vss-test-web.build-test-results-tab&runId=6357126&resultId=118614)||
|[311363](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311363)|dotnet/runtime|[Regressions/coreclr/GitHub_45037/test45037/test45037.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311363&view=ms.vss-test-web.build-test-results-tab&runId=6354250&resultId=118614)||
|[311324](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311324)|dotnet/runtime|[Regressions/coreclr/GitHub_54719/test54719/test54719.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311324&view=ms.vss-test-web.build-test-results-tab&runId=6353056&resultId=101875)||
|[311319](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311319)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311319&view=ms.vss-test-web.build-test-results-tab&runId=6352772&resultId=120196)||
|[311318](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311318)|dotnet/runtime|[Regressions/coreclr/GitHub_45037/test45037/test45037.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311318&view=ms.vss-test-web.build-test-results-tab&runId=6352906&resultId=118602)||
|[311307](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311307)|dotnet/runtime|[Regressions/coreclr/GitHub_54719/test54719/test54719.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311307&view=ms.vss-test-web.build-test-results-tab&runId=6352330&resultId=119533)||
|[311305](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311305)|dotnet/runtime|[Regressions/coreclr/GitHub_54719/test54719/test54719.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311305&view=ms.vss-test-web.build-test-results-tab&runId=6352220&resultId=118614)||
|[311190](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311190)|dotnet/runtime|[Regressions/coreclr/GitHub_45037/test45037/test45037.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311190&view=ms.vss-test-web.build-test-results-tab&runId=6349072&resultId=118614)||
|[310909](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310909)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310909&view=ms.vss-test-web.build-test-results-tab&runId=6339384&resultId=120195)||
|[310908](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310908)|dotnet/runtime|[Regressions/coreclr/GitHub_54719/test54719/test54719.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310908&view=ms.vss-test-web.build-test-results-tab&runId=6339480&resultId=102085)||
|[310889](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310889)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310889&view=ms.vss-test-web.build-test-results-tab&runId=6338976&resultId=120588)|dotnet/runtime#87241|
|[310769](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310769)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310769&view=ms.vss-test-web.build-test-results-tab&runId=6337076&resultId=120588)|dotnet/runtime#87241|
|[310510](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310510)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=310510&view=ms.vss-test-web.build-test-results-tab&runId=6330596&resultId=120195)|dotnet/runtime#87588|
|[309817](https://dev.azure.com/dnceng-public/public/_build/results?buildId=309817)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=309817&view=ms.vss-test-web.build-test-results-tab&runId=6312222&resultId=120295)||
|[309621](https://dev.azure.com/dnceng-public/public/_build/results?buildId=309621)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=309621&view=ms.vss-test-web.build-test-results-tab&runId=6306372&resultId=120195)||
|[309581](https://dev.azure.com/dnceng-public/public/_build/results?buildId=309581)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=309581&view=ms.vss-test-web.build-test-results-tab&runId=6305320&resultId=120195)|dotnet/runtime#87421|
|[309485](https://dev.azure.com/dnceng-public/public/_build/results?buildId=309485)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=309485&view=ms.vss-test-web.build-test-results-tab&runId=6302480&resultId=120195)||
|[309277](https://dev.azure.com/dnceng-public/public/_build/results?buildId=309277)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=309277&view=ms.vss-test-web.build-test-results-tab&runId=6300498&resultId=118711)|dotnet/runtime#87438|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|6|24|24|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=310510
**Result validation: :white_check_mark:** Known issue matched with the provided build.

**Comment by EgorBo** [comment]
I guess it could be https://github.com/dotnet/runtime/pull/85743 cc @davidwrighton

**Comment by davidwrighton** [comment]
Thank you for bringing this to my attention, I'mll take a look today
