### ISSUE TITLE
System.Numerics.Tensors is missing API documentation

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#87710]
See https://github.com/dotnet/runtime/pull/84917 for more context.

The compiler generated XML file for System.Numerics.Tensors is shipping to customers via the nuget package and is missing public API documentation. The above linked PR disables the compiler error CS1591 until all the API is documented.

When working on this, remove the NoWarn=1591 setting from the project file.

**Comment by tannergooding** [comment]
This is a prototype feature that has never properly shipped. It is likely to change fairly significantly before it does ship and until we start working on it again, documentation isn't necessary or a priority on it.
