### ISSUE TITLE
.net8 prev 5 unassociated AOT processes crash when the debugger starts on the system.

### ISSUE THREAD

**Issue by xljiulang** [dotnet/runtime#87739]
### Description

eventpipeinternal.cpp

已在 Lotus.exe 中执行断点指令(__debugbreak()语句或类似调用)。

>	Lotus.exe!RhEventPipeInternal_WaitForSessionSignal(unsigned __int64 sessionID, int timeoutMs) 行 41	C++
 	Lotus.exe!S_P_CoreLib_System_Diagnostics_Tracing_EventPipeInternal__EventActivityIdControl() 行 114	未知
 	Lotus.exe!S_P_CoreLib_System_Runtime_CompilerServices_TaskAwaiter___c___OutputWaitEtwEvents_b__12_0() 行 295	未知
 	Lotus.exe!S_P_CoreLib_System_Threading_Tasks_AwaitTaskContinuation__System_Threading_IThreadPoolWorkItem_Execute() 行 647	未知
 	Lotus.exe!S_P_CoreLib_System_Threading_ThreadPoolWorkQueue__Dispatch() 行 924	未知
 	Lotus.exe!S_P_CoreLib_System_Threading_ThreadPool__DispatchCallback() 行 376	未知

### Reproduction Steps

1. Run a aot process
2. Debug some process
3. aot process crash

### Expected behavior

aot process will not crash

### Actual behavior

aot process will crash

**Comment by vitek-karas** [comment]
@LakshanF this is very likely something about event pipe - starting VS debugger turns on event collection system wide (although that should be ETW, so maybe it's something about the runtime event source).
