### ISSUE TITLE
how dotnet find windows kits paths

### ISSUE THREAD

**Issue by NCLnclNCL** [dotnet/runtime#87743]
i solved without installing visual studio2022 i can still build native aot, but i have problem with window kits, i want to ask dotnet how to find its path(eg like this C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0), I tried registry but it doesn't seem to work, can someone tell me, how dotnet find out 10.0.22621.0

**Comment by jkotas** [comment]
> how dotnet find out 10.0.22621.0

We setup up C++ build environment by running `vcvarsall.bat` that is part of Visual Studio, and then capture value of the `LIB` environment variable in this build environment.

https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/BuildIntegration/findvcvarsall.bat#L37-L48
