### ISSUE TITLE
Add DebuggerDisplay to System.Diagnostics.Metrics's Meter and Instruments

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#87758]
Meter = Meter.Name (maybe also a count of instruments?)
Instruments = Instrument.Name (maybe also its meter name? And Enabled?). DebuggerDisplay attribute is inherited so the attribute can be added once to the base class.

`DebuggerDisplayAttribute` docs: https://learn.microsoft.com/en-us/visualstudio/debugger/using-the-debuggerdisplay-attribute?view=vs-2022

It could be tagged as help wanted.

**Comment by tommcdon** [comment]
@tarekgh @noahfalk

**Comment by tarekgh** [comment]
This is a reasonable ask.
