### ISSUE TITLE
JsonElement deserialization dispose behavior

### ISSUE THREAD

**Issue by eknkc** [dotnet/runtime#87751]
Deserializing a `JsonElement` in this fashion creates a `JsonElement` without an accessible `JsonDocument`

```csharp
JsonSerializer.Deserialize<JsonElement>("{}");
```

So I asssume it is safe to use and pass around as it is not possible to access the parent `JsonDocument` and dispose it. However it looks like these two create slightly different parents:

```csharp
var direct = JsonSerializer.Deserialize<JsonElement>("{}");

using (var doc = JsonSerializer.Deserialize<JsonDocument>("{}"))
    cloned = doc.RootElement.Clone();
```

<img width="563" alt="CleanShot 2023-06-19 at 00 40 24@2x" src="https://github.com/dotnet/runtime/assets/1248453/c6a3bb6c-b75a-499b-9291-f1a51737f188">

When it is `cloned` from the `RootElement` of a `JsonDocument`, the parent has `IsDisposable` to false. However when it is deserialized in `direct` fashion, `IsDisposable` is true. This made me believe that the `direct` method has a parent that actually needed to be disposed at some point.

Is that the case? Is it safe to directly deserialize `JsonElement` instances and keep them around? Looks like neither has shared buffer allocations but I wanted to make sure if this is not an issue.

Thanks.

**Comment by eiriktsarpalis** [comment]
I believe this is an issue with the internal `ParseUnrented` implementation
