### ISSUE TITLE
.net8 preview4 AOT windows service process, log component always writes to ETW

### ISSUE THREAD

**Issue by xljiulang** [dotnet/runtime#87769]
### Description

```
 var builder = WebApplication.CreateSlimBuilder(args);

 builder.Logging.ClearProviders();
 if (ServiceUtil.IsWindowsService() == false)
 {
     builder.Logging.AddConsole();
 }
```
If the above code is installed and run as a windows service after AOT, the log will always be written to ETW, but the JIT compilation behaves correctly.

### Reproduction Steps

1. clear all loger providers.
2. build as AOT
3. install and run as windows service

### Expected behavior

Logs are not written to ETW

### Actual behavior

Logs allway written to ETW

**Comment by tommcdon** [comment]
@LakshanF do we plan on doing the work in Native AOT to support ETW?

**Comment by tommcdon** [comment]
@LakshanF would you mind taking a look?

**Comment by LakshanF** [comment]
Taking a look

**Comment by xljiulang** [comment]
@LakshanF
Sorry, I found out that this is the default logging behavior of the UseWindowsService() extension, which always calls logging.AddEventLog() when a windows service is eligible.
