### ISSUE TITLE
Please backport fix for #84994 (via PR #85001) to .NET 7

### ISSUE THREAD

**Issue by rickbrew** [dotnet/runtime#87791]
@stephentoub fixed #84994  via #85001 and this looks like it landed for .NET 8.

At first I only had 1 stray crash report for this, but I'm starting to get more crash reports, and my app (Paint.NET) is using .NET 7.

Could this be backported / cherry-picked into .NET 7?

**Comment by teo-tsirpanis** [comment]
Fixed in #88153, don't know why it was not closed automatically.
