### ISSUE TITLE
Consider adding option in csproj for software and fixed point number types

### ISSUE THREAD

**Issue by Shadowblitz16** [dotnet/runtime#87793]
It's really useful in networking to have cross platform deterministic data types 
Instead of needing to send data over the network we can just send inputs and rely on the fact that our output will always be the same.

consider adding..
```
<FloatingType>software</FloatingType>
```
and
```
<FloatingType>softwarefixed</FloatingType>
```

To csproj and dotnet.

This would automatically make half, float, double, decimal use fixed or software based implimentation
The default would be...
```
<FloatingType>hardware</FloatingType>
```

**Comment by danmoseley** [comment]
Overall issue
https://github.com/dotnet/runtime/issues/61885

Other issues come up eg
Https://github.com/dotnet/runtime/issues/42747
