### ISSUE TITLE
OSX/x64: TargetOS::IsMacOS returns false in jit codebase 

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#87794]
`TargetOS::IsMacOS` returns `false` when used on osx/x64. I had to use it in https://github.com/dotnet/runtime/pull/87082, but since it was always return `false`, had to use a workaround https://github.com/dotnet/runtime/pull/87082/commits/d3cdf77dec4006522a25b3adc93a1f7e2bfa331f.

**Comment by davidwrighton** [comment]
Fixed with #87940
