### ISSUE TITLE
[API Proposal]: Make `System.IO.Pipelines.Pipe.Length` from `internal` to `public`

### ISSUE THREAD

**Issue by dameng324** [dotnet/runtime#87808]
### Background and motivation

I use `System.IO.Pipelines.Pipe` to process network datas, I send data to pipe and use another task to read pipe and send data to socket in case to not block the send thread.

but when in low bandwide environment there is so many data in the pipe to send to socket, I should know how much bytes is waiting for send to socket.

I read the source of `System.IO.Pipelines.Pipe` and found `Length` property is what I want, but it is `internal`, I can't use it directly in my code, the solution is refection but more performance cost, or build my own `System.IO.Pipelines.Pipe` but not so elegant.

So, I suggest make the `Length` property public, and I can know how many data is not processed in my pipe.

### API Proposal

```csharp
namespace System.IO.Pipelines
{
    public sealed partial class Pipe
    {
        // other code
        public long Length => _unconsumedBytes;
        // other code
    }
}
```

### API Usage

```csharp
// create a pipe
var pipe =  new Pipe();
//get the length of pipe
Console.WriteLine(pipe.Length);
```

**Comment by davidfowl** [comment]
Can you show how you plan to use it? Also can you show what you are doing to day to work around it? (a full example would be appreciated).

**Comment by dameng324** [comment]
Sure, Here is an example:
```cs
    internal class TcpStreamSender
    {
        Pipe sendPipe = new Pipe(new PipeOptions(pauseWriterThreshold: 0));//do not block the writer FlushAsync method
        readonly NetworkStream _stream;
        CancellationTokenSource _runningCancellationTokenSource = new CancellationTokenSource();

        public TcpClient TcpClient { get; }

        public TcpStreamSender(TcpClient client)
        {
            TcpClient = client;
            var stream = client.GetStream();
            Task.Run(ReadSendPipeAsync);
        }

        /// <summary>
        /// 不需要调用Close的异常
        /// </summary>
        /// <param name="e"></param>
        /// <returns></returns>
        private bool IsIgnorableException(Exception e)
        {
            if(e is ObjectDisposedException || e is NullReferenceException || e is OperationCanceledException)
                return true;

            if(e.InnerException != null)
                return IsIgnorableException(e.InnerException);

            return false;
        }
        //Read the datas in pipe and send them to network stream
        private async void ReadSendPipeAsync()
        {
            Debug.Assert(_stream is not null);
            PipeReader reader = sendPipe.Reader;
            var cts = _runningCancellationTokenSource;
            while(!cts.IsCancellationRequested)
            {
                ReadResult result;
                try
                {
                    result = await reader.ReadAsync(cts.Token).ConfigureAwait(false);
                }
                catch(Exception e)
                {
                    if(!IsIgnorableException(e) && cts.IsCancellationRequested == false)
                    {
                        CloseInternal($"Failed to read from the send pipe:{e.Message}");
                    }
                    break;
                }

                var buffer = result.Buffer;

                if(result.IsCanceled)
                {
                    if(cts.IsCancellationRequested == false)
                    {
                        CloseInternal($"channel canceled");
                    }
                    break;
                }

                var completed = result.IsCompleted;
                try
                {
                    if(buffer.Length > 0)
                    {
                        if(buffer.IsSingleSegment)
                        {
                            await _stream.WriteAsync(buffer.First, cts.Token);
                        }
                        else
                        {
                            foreach(var memory in buffer)
                            {
                                await _stream.WriteAsync(memory, cts.Token);
                            }
                        }
                        //if bandwidth is limited, this function will be slow, and cannot read data from pipe.
                        await _stream.FlushAsync();

                        if(completed)
                        {
                            break;
                        }
                    }
                }
                catch(Exception e)
                {
                    if(cts.IsCancellationRequested == false)
                    {
                        // close the connection if get a protocol error
                        CloseInternal($"Protocol error:{e.Message}");
                    }
                    break;
                }
                finally
                {
                    reader.AdvanceTo(buffer.End);
                }
            }
            await reader.CompleteAsync();
        }
        private void CloseInternal(string reason)
        {
            if(_runningCancellationTokenSource?.IsCancellationRequested == false)
            {
                try
                {
                    _runningCancellationTokenSource?.Cancel();
                }
                catch(Exception)
                {
                }
            }
            if(TcpClient.Connected)
            {
                TcpClient.Close();
            }
        }

        const long MaxPipeCachedData = 4 * 1024 * 1024;//4MB
        public async Task SendDataAsync(byte[] data)
        {
            //disconnect the client when send pipe has too many data to send;
            if(sendPipe.Length > MaxPipeCachedData)
            {
                CloseInternal($"there is to much data in the pipe");
            }
            await sendPipe.Writer.WriteAsync(data);
            await sendPipe.Writer.FlushAsync();
        }

        public delegate long GetPipeLengthDelegate(Pipe pipe);
        public static GetPipeLengthDelegate GetPipeLengthFunc =
            typeof(Pipe).GetProperty("Length", System.Reflection.BindingFlags.NonPublic| System.Reflection.BindingFlags.Instance)!
            .GetMethod!
            .CreateDelegate<GetPipeLengthDelegate>();
        /// <summary>
        /// Get the pipe.Length by reflection.
        /// </summary>
        /// <param name="pipe"></param>
        /// <returns></returns>
        public static long GetPipeLength(this Pipe pipe)
        {
            return GetPipeLengthFunc(pipe);
        }
    }

```

Let me make a brief description:
1. I use SendDataAsync to send data to pipe.
2. I use Task.Run to read data from pipe, and send data to NetworkStream.
3. When there is too many data to send, and the network is poor, so `NetworkStream.FlushAsync` will be slow, the pipe.Length will be bigger and bigger and my memory usage will be uncontroled.
4. So I decide to watch the pipe.Length is big or not, if pipe.Length is bigger than my threshold, I can disconnect the client to avoid this memory problem.
5. But I cannot fetch pip.Length because it is internal not public, so I have to use reflection to fetch this value, I do not want this way, because it is not performance well and not friendly to nativeAOT.
6. So I will use reflection now,but will fix my code when `Length` is public.

Is my description clear?

**Comment by Clockwork-Muse** [comment]
> `e is NullReferenceException`

`NullReferenceException`s should not be ignored - they represent a bug in your code.  

> //disconnect the client when send pipe has too many data to send;

... this seems really unfriendly to do.  Ideally, you should be putting some form of backpressure on your caller (and rejecting the submit, or at least only a partial update), or otherwise throttling the send instead.

> `Pipe sendPipe = new Pipe(new PipeOptions(pauseWriterThreshold: 0));//do not block the writer FlushAsync method`

Actually putting a limit here would allow you to help throttle (because of blocking the flush).

There's also [`PipeWriter.UnflushedBytes`](https://learn.microsoft.com/en-us/dotnet/api/system.io.pipelines.pipewriter.unflushedbytes?view=dotnet-plat-ext-7.0), which would tell you if there were any outstanding bytes.  Would that suffice for you?

Also, is there something specific and additional you're doing, or would just a simple call to [`PipeWriter.CopyFromAsync(...)`](https://learn.microsoft.com/en-us/dotnet/api/system.io.pipelines.pipewriter.copyfromasync?view=dotnet-plat-ext-7.0#system-io-pipelines-pipewriter-copyfromasync(system-io-stream-system-threading-cancellationtoken)) be enough, which would do most of this work for you?

**Comment by dameng324** [comment]
> NullReferenceExceptions should not be ignored   

Yes, you are right, I will check the code and fix this. thank you.

> this seems really unfriendly to do.  

I have to explain that my datas are very latency sensitive like realtime stock market datas, so if the send speed is slower than receive speed, many datas will be cached in my memory, which lead to uncontrolable memory issue and latency issue. I can't send the data out, and can't skip these data too, so the only way of the server is disconnect the low speed client connection.

> Actually putting a limit here would allow you to help throttle (because of blocking the flush).

I do not want to block send thread, because there is so many client to send. I will never wait for a send operation complete then send to another client. The last client's latency will be very high. Maybe you will say every client should send In seperated Thread/Task, but It will cause same memory problem, only difference is the sending queue cached the sending data instead of pipe.


> There's also [PipeWriter.UnflushedBytes](https://learn.microsoft.com/en-us/dotnet/api/system.io.pipelines.pipewriter.unflushedbytes?view=dotnet-plat-ext-7.0), which would tell you if there were any outstanding bytes. Would that suffice for you?

I known this UnflushedBytes property, this is not what I want. this property is how many data has not been flushed, not how many data has not been read. I will flush the data  immediately when I writen a data array to decrese the latency as much as possable. so this property will always be 0,when I want send my data.

I think the `Pipe.Length` will be useful for user to known the pipe consume state. I want to use this to decide whether should I continue write to the pipe.

**Comment by Clockwork-Muse** [comment]
> I can't send the data out, and can't skip these data too, so the only way of the server is disconnect the low speed client connection

.... but you _are_ (effectively) skipping this data for "slow" clients.  Who are likely going to be getting partial messages from this.  While exactly how much time a 4MB buffer represents is going to depend on your throughput, that's potentially a **very** narrow window of time, likely on the order of seconds, which means that even trivial network disruptions that would normally be recoverable are just going to be dropped.

This is one of those areas where one of the existing pub/sub libraries/frameworks/message queues is likely to serve you in much better stead, as writing a performant and robust implementation is a non-trivial exercise.

> I will never wait for a send operation complete then send to another client.

You don't show a multi-client version, but considering that your clients are presumably on the other end of the TCP connection you are blocking on that send, just not on the intermediate pipe.

> I have to explain that my datas are very latency sensitive like realtime stock market datas

For stock market data specifically, every implementation I've heard mentioned has been in C/C++.  Really heavily tuned C/C++, because they _really_ want the speed.

**Comment by dameng324** [comment]
Thanks for your turning to C/C++ sugguestion, but when bandwidth is limited, C/C++ does not slove the problem.

> While exactly how much time a 4MB buffer represents is going to depend on your throughput, that's potentially a very narrow window of time, likely on the order of seconds, which means that even trivial network disruptions that would normally be recoverable are just going to be dropped.

You are right, 4MB maybe is too small, but I can change this buffer size to a reasonable value. 

Considering the my business, disconnect the slow client is acceptable, uncontroled server side memory usage is not acceptable.

I think we should back to the orginal problem, I just want to known how many bytes in the pipe which not been read. Does this not worth to consider make this change?

**Comment by dameng324** [comment]
The message queue does not solve the uncontrolable memory usage problem, when there is slow client , message queue will use more and more memory as well.

If I have a business level heart beat, slow client will cause heart beat timeout when large data arrive as well, which will lead to disconnect connection. So I think disconnect the client should be a acceptable way.

**Comment by Clockwork-Muse** [comment]
What I was getting at more with the suggestion to use an existing message-queue framework is that part of the implication in your question is that you have a 4MB pipe for each connection.  If you're sending the exact same thing to each client (or mostly), that's not necessary - you can share the data another way and have each connection handle where it is in a (potentially _much_ larger) buffer.  A good message-queue framework would do this type of work for you.  Too, any good framework would allow you to configure limits, so you could prevent unconstrained memory growth anyways.

> If I have a business level heart beat, slow client will cause heart beat timeout when large data arrive as well, which will lead to disconnect connection.

If the client is behaving that poorly they have larger problems.  Especially because that would be "slow client process", not "slow connection to client", which are distinct and separate problems.

> I think we should back to the orginal problem, I just want to known how many bytes in the pipe which not been read. Does this not worth to consider make this change?

Perhaps (although keep in mind that any such value would be stale the moment you read it).  More what I was getting at is that what you're asking for doesn't necessarily solve your _actual_ problem(s), as opposed to solving for your implemented solution.

**Comment by davidfowl** [comment]
I'm struggling with 2 things:

> I do not want to block send thread, because there is so many client to send. I will never wait for a send operation complete then send to another client. The last client's latency will be very high. Maybe you will say every client should send In seperated Thread/Task, but It will cause same memory problem, only difference is the sending queue cached the sending data instead of pipe.

Each client should send in a separate task, not a separate thread. If you want to limit the memory, then limit the number of concurrent connections.

I don't fully understand why you turned off the backpressure feature (pauseWriterThreshold) to then ask for what seems like the same feature but implemented in your own code. Instead of awaiting the flush, you could potentially do something like this:

```C#
public async Task SendDataAsync(byte[] data)
{
    await sendPipe.Writer.Write(data);
    var flushTask = sendPipe.Writer.FlushAsync();
    if (!flushTask.IsCompleted) 
    {
       // Back pressure, the consumer hasn't kept up
       CloseInternal($"there is to much data in the pipe");
    }
   await flushTask;
}
```

Maybe you want a TryWrite that would do a similar thing and return if the data can fit.

**Comment by dameng324** [comment]
@Clockwork-Muse 

> any good framework would allow you to configure limits, so you could prevent unconstrained memory growth anyways.

As you said, any good framework can configure limits, but how can I implement this limit without the `Pipe.Length` ? How do I know how many bytes has not been sent in pipe?

4MB is just an example value. I can use it as a config.

> If the client is behaving that poorly they have larger problems. Especially because that would be "slow client process", not "slow connection to client", which are distinct and separate problems.

The server side should not care so much about the client side, If client side has their problem, server side close their connection should be a acceptable way to avoid server side issue. What I care about is whatever the client side behavior, they should not cause server side issue, such like unlimited memory usage ,which is what I really care about.

> Perhaps (although keep in mind that any such value would be stale the moment you read it). More what I was getting at is that what you're asking for doesn't necessarily solve your actual problem(s), as opposed to solving for your implemented solution.

I dont understand why you think what I am asking does not solve my problem. My problem is I cannot limit the server side memory usage, disconnect the connection is a reasonable way to solve that.

**Comment by dameng324** [comment]
@davidfowl 

You really know what I want, and your answer seems solving my problem. Thank you.

Now I will explain your confusings.
> Each client should send in a separate task, not a separate thread. If you want to limit the memory, then limit the number of concurrent connections.

You are right, each client should send in a separate task not thread. But when I broadcast a message to my clients, an usual way is use a foreach loop. which call `await SendDataAsync`  syncly. Maybe I should turn to `Parallel` to fix it? What's your suggestion?

> I don't fully understand why you turned off the backpressure feature (pauseWriterThreshold) to then ask for what seems like the same feature but implemented in your own code.

That's my mistake. I use the default pipe options at first, but I found that when I turned off it, It will never block the `FlushAsync` call, so never block the `SendDataAsync` method. My broadcast foreach loop will executed more somoothly. I will fix it as your suggestion.

> var flushTask = sendPipe.Writer.FlushAsync();
    if (!flushTask.IsCompleted) 
    {
       // Back pressure, the consumer hasn't kept up
       CloseInternal($"there is to much data in the pipe");
    }

The return value of FlushAsync is a ValueTask. When will it complete syncly and when asyncly? 
Can I suppose that it must be reaching the limit of `pauseWriterThreshold` when FlushTask is not completed syncly?

> Maybe you want a TryWrite/TryFlush that would do a similar thing and return if the data can fit.

Yes, this can solve my problem as well, and more strightforward than `ValueTask.IsCompleted`. Will dotnet team add it?

**Comment by davidfowl** [comment]
> Can I suppose that it must be reaching the limit of pauseWriterThreshold when FlushTask is not completed syncly?

Yes, this is how the system works.

There's a document on how backpressure works here https://learn.microsoft.com/en-us/dotnet/standard/io/pipelines#backpressure-and-flow-control


> Yes, this can solve my problem as well, and more strightforward than ValueTask.IsCompleted. Will dotnet team add it?

Maybe, we don't just add things. They need to be discussed and designed and then an API needs to be approved. Right now this is just a discussion to understand exactly what and why you are asking for a new API (which I'm not sure you need).

**Comment by dameng324** [comment]
Learned a lot. Thank you, @davidfowl. The backpressure mechanism seems to help me solve the problem.
