### ISSUE TITLE
why i add dotnet to path but application with --no-self-contained cannot run

### ISSUE THREAD

**Issue by NCLnclNCL** [dotnet/runtime#87819]
i use dotnet's portable, i added the environment variable, it seems those apps target C:\Program Files (x86)\dotnet or C:\Program Files\dotnet not the environment

**Comment by davidfowl** [comment]
Very little information, not enough to help you resolve the problem.

**Comment by tmds** [comment]
You also need to set `DOTNET_ROOT` envvar to the directory that holds the `dotnet` executable.
This is used to search for the shared frameworks.

**Comment by agocke** [comment]
Closing as answered.
