### ISSUE TITLE
[Test Failure] 'System.Net.Sockets.Tests.SendReceive_SpanSyncForceNonBlocking.SendRecv_Stream_TCP_MultipleConcurrentReceives'

### ISSUE THREAD

**Issue by rzikm** [dotnet/runtime#87815]
https://[helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-01d941239f0045aaaa/System.Net.Sockets.Tests/1/console.ac2d96f4.log?helixlogtype=result](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-01d941239f0045aaaa/System.Net.Sockets.Tests/1/console.ac2d96f4.log?helixlogtype=result)

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=309925&view=results

## Error Message

```json
{
  "ErrorMessage": "System.Net.Sockets.Tests.SendReceive_SpanSyncForceNonBlocking.SendRecv_Stream_TCP_MultipleConcurrentReceives",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

 ### Known issue validation
**Build: :mag_right:** 
**Result validation: :warning:** Validation could not be done without an Azure DevOps build URL on the issue. Please add it to the "**Build: :mag_right:**" line.
**Validation performed at:** 10/19/2023 3:32:20 PM UTC

### Known Issue Error Message

**Comment by karelz** [comment]
Does not seem to happen very often. I would suggest Future mileston.

**Comment by karelz** [comment]
Moved to Future due to low frequency - FYI @antonfirsov @wfurt

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by rzikm** [comment]
No recent hits, not actionable at this moment, closing until issue resurfaces.
