### ISSUE TITLE
[ProfilerAPI] Different reserved region sizes reported for frozen segment

### ISSUE THREAD

**Issue by ww898** [dotnet/runtime#87834]
### Description

I see different region reserved sizes for the same frozen segment reported by `GetGenerationBounds` (`type=soh2` in log) and `GetNonGCHeapBounds` (`type=foh` in log) calls:
```
0000449C 1 0000027202149FE0 GG::Heaps c=7
	#0 type=poh  base=0000027280000028 size=0000000000003FF0 reservedSize=0000000001FFFFD8 objectSizeAlignment=8
	#1 type=loh  base=0000027282C00028 size=0000000000050820 reservedSize=0000000001FFFFD8 objectSizeAlignment=8
	#2 type=soh2 base=0000027202170008 size=0000000000007020 reservedSize=00000000003FFFF8 objectSizeAlignment=8 // <=== here
	#3 type=soh2 base=0000027282800028 size=00000000000151B8 reservedSize=00000000003FFFD8 objectSizeAlignment=8
	#4 type=soh1 base=0000027282000028 size=0000000000000000 reservedSize=00000000003FFFD8 objectSizeAlignment=8
	#5 type=soh0 base=0000027284C00028 size=000000000010B0A0 reservedSize=00000000003FFFD8 objectSizeAlignment=8
	#6 type=foh  base=0000027202170008 size=0000000000007020 reservedSize=0000000000400000 objectSizeAlignment=8 // <=== here
```

### Reproduction Steps

Application to reproduce the issue:
```
Console.WriteLine("Hello, World!");
Console.ReadLine();
```

### Expected behavior

`base=0000027202170008 size=0000000000007020 reservedSize=00000000003FFFF8`

### Actual behavior

`base=0000027202170008 size=0000000000007020 reservedSize=0000000000400000`

### Configuration

.NET 8.0-preview.5
Windows 10 Pro 22H2 x64

**Comment by ww898** [comment]
The bug is here https://github.com/dotnet/runtime/blob/19a088e3a12317bdd1d24b33b70c8e92de6330d4/src/coreclr/vm/proftoeeinterfaceimpl.cpp#L7692

We should subtract `sizeof(ObjHeader)` in this line

**Comment by cshung** [comment]
This work-in-progress PR https://github.com/dotnet/runtime/pull/85727 will fix it.

**Comment by ww898** [comment]
@EgorBo Could you please take a look?
