### ISSUE TITLE
Assertion failed 'unreached' in 'System.Runtime.InteropServices.Tests.NFloatTests_GenericMath:MaxMagnitudeTest()'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#87837]
runtime-coreclr libraries-jitstress-random
net8.0-linux-Release-arm-CoreCLR_checked-jitstress_random_2-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
System.Runtime.InteropServices.Tests Work Item

https://dev.azure.com/dnceng-public/public/_build/results?buildId=314259&view=ms.vss-test-web.build-test-results-tab&runId=6433322&paneView=debug&resultId=198352

```
DOTNET_EnableCrashReport=1
DOTNET_TieredCompilation=0
DOTNET_JitStress=f6
DOTNET_DbgMiniDumpName=/home/helixbot/dotnetbuild/dumps/coredump.%d.dmp
DOTNET_DbgEnableMiniDump=1
+ ./RunTests.sh --runtime-path /root/helix/work/correlation
----- start Tue Jun 20 19:36:07 UTC 2023 =============== To repro directly: =====================================================
pushd .
/root/helix/work/correlation/dotnet exec --runtimeconfig System.Runtime.InteropServices.Tests.runtimeconfig.json --depsfile System.Runtime.InteropServices.Tests.deps.json xunit.console.dll System.Runtime.InteropServices.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
/root/helix/work/workitem/e /root/helix/work/workitem/e
  Discovering: System.Runtime.InteropServices.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Runtime.InteropServices.Tests (found 895 of 913 test cases)
  Starting:    System.Runtime.InteropServices.Tests (parallel test collections = on, max threads = 2)
...
Assert failure(PID 28 [0x0000001c], Thread: 42 [0x002a]): Assertion failed 'unreached' in 'System.Runtime.InteropServices.Tests.NFloatTests_GenericMath:MaxMagnitudeTest()' during 'Do value numbering' (IL size 391; hash 0xb559fe7c; FullOpts)

    File: /__w/1/s/src/coreclr/jit/valuenum.cpp Line: 8475
    Image: /root/helix/work/correlation/dotnet
```

Looks like https://github.com/dotnet/runtime/pull/87641 missed the `float` argument type cases in VN?

@tannergooding PTAL

```json
{
  "ErrorMessage": "",
  "BuildRetry": false,
  "ErrorPattern": "Assertion failed 'unreached' in 'System.Runtime.InteropServices.Tests.NFloatTests_GenericMath:.*' during 'Do value numbering'",
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=313357
**Result validation: :white_check_mark:** Known issue matched with the provided build.

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[315893](https://dev.azure.com/dnceng-public/public/_build/results?buildId=315893)|dotnet/runtime|[System.Runtime.InteropServices.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=315893&view=ms.vss-test-web.build-test-results-tab&runId=6473348&resultId=198498)|dotnet/runtime#87869|
|[314956](https://dev.azure.com/dnceng-public/public/_build/results?buildId=314956)|dotnet/runtime|[System.Runtime.InteropServices.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=314956&view=ms.vss-test-web.build-test-results-tab&runId=6452108&resultId=198497)|dotnet/runtime#87810|
|[314899](https://dev.azure.com/dnceng-public/public/_build/results?buildId=314899)|dotnet/runtime|[System.Runtime.InteropServices.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=314899&view=ms.vss-test-web.build-test-results-tab&runId=6450228&resultId=198497)||
|[314384](https://dev.azure.com/dnceng-public/public/_build/results?buildId=314384)|dotnet/runtime|[System.Runtime.InteropServices.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=314384&view=ms.vss-test-web.build-test-results-tab&runId=6437402&resultId=198371)|dotnet/runtime#87810|
|[313357](https://dev.azure.com/dnceng-public/public/_build/results?buildId=313357)|dotnet/runtime|[System.Runtime.InteropServices.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=313357&view=ms.vss-test-web.build-test-results-tab&runId=6435228&resultId=211815)|dotnet/runtime#87790|
|[314259](https://dev.azure.com/dnceng-public/public/_build/results?buildId=314259)|dotnet/runtime|[System.Runtime.InteropServices.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=314259&view=ms.vss-test-web.build-test-results-tab&runId=6433322&resultId=198352)||
|[314215](https://dev.azure.com/dnceng-public/public/_build/results?buildId=314215)|dotnet/runtime|[System.Runtime.InteropServices.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=314215&view=ms.vss-test-web.build-test-results-tab&runId=6433230&resultId=196873)|dotnet/runtime#87810|
|[313536](https://dev.azure.com/dnceng-public/public/_build/results?buildId=313536)|dotnet/runtime|[System.Runtime.InteropServices.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=313536&view=ms.vss-test-web.build-test-results-tab&runId=6418186&resultId=198350)|dotnet/runtime#87809|
|[313336](https://dev.azure.com/dnceng-public/public/_build/results?buildId=313336)|dotnet/runtime|[System.Runtime.InteropServices.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=313336&view=ms.vss-test-web.build-test-results-tab&runId=6412190&resultId=198350)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|3|9|9|

**Comment by jakobbotsch** [comment]
This fails in libraries-jitstress too, I added a known error for this
