### ISSUE TITLE
Follow up on TarEntry feedback from PR #87534

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#87835]
Got some feedback on my PR that ports a servicing fix: https://github.com/dotnet/runtime/pull/87534
Will address separately.

**Comment by tmds** [comment]
I've included the suggestions I made to for `TarEntry.cs` in https://github.com/dotnet/runtime/pull/87534 to https://github.com/dotnet/runtime/pull/85378.

**Comment by carlossanlop** [comment]
> I've included the suggestions I made to for `TarEntry.cs` in #87534 to #85378.

@tmds thank you so much, I missed this message. Do you mean we can close this now?
