### ISSUE TITLE
jit-diff produces random diffs on Linux due to relocs

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#87842]
"Random" diff example @MihaZupan shared: https://www.diffchecker.com/DH246Mx2/ 

My guess that it happens because on Linux we have a chance that we won't be able to reserve the memory for the loader heap near the coreclr while on Windows it is sort of guaranteed. 

We should probably just disable relocs for jit-diff on non-windows.

cc @dotnet/jit-contrib

**Comment by EgorBo** [comment]
Should be a simple change:
1) Add a new env var (available in Release) to clrconfigvalues
2) Set `g_fAllowRel32` to false if that variable is set.

**Comment by jakobbotsch** [comment]
If we have a consistent repro of this failing to reserve space it would be good to figure out why it fails.

cc @janvorli

**Comment by EgorBo** [comment]
> If we have a consistent repro of this failing to reserve space it would be good to figure out why it fails.
> 
> cc @janvorli

Last time we discussed this it was pretty much 50/50 chance on arm64 Linux/macOS to reserve the space

**Comment by jakobbotsch** [comment]
Did we understand why it was not reliable? What was being mapped such that we couldn't reserve the space? The space is reserved very early during startup, when not much should be mapped into memory. Also, this is x64. It's hard for me to believe we don't have a large chunk of memory available somewhere in the +- 2 GiB range.

**Comment by EgorBo** [comment]
> Did we understand why it was not reliable? What was being mapped such that we couldn't reserve the space? The space is reserved very early during startup, when not much should be mapped into memory. Also, this is x64. It's hard for me to believe we don't have a large chunk of memory available somewhere in the +- 2 GiB range.

No, `ReserveVirtualMemory` just may return nullptr, perhaps some OS security features are involved - no idea.

**Comment by janvorli** [comment]
> It's hard for me to believe we don't have a large chunk of memory available somewhere in the +- 2 GiB range.

It can theoretically happen due to ASLR or due to SELinux that has mode that always ignores address passed as a hint to mmap.
