### ISSUE TITLE
Follow up items for Options validation source generator

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#87844]
This issue is tracking the follow up tasks we need to do options source gen.

- [x] Source gen optimizations listed in the comments 
    - https://github.com/dotnet/runtime/pull/87587#pullrequestreview-1481881917
    - https://github.com/dotnet/runtime/pull/87587#pullrequestreview-1482967441
    - https://github.com/dotnet/runtime/pull/87587#pullrequestreview-1482973873
- [x] https://github.com/dotnet/runtime/pull/90275
    -  ValidateObjectMembersAttribute
    - ValidateEnumeratedItemsAttribute

https://github.com/dotnet/runtime/issues/85475

**Comment by xakep139** [comment]
@tarekgh I created two issues: #88152 and 88150, not sure that these should be considered as follow-up items for this one
