### ISSUE TITLE
Generate UUID-5 in FIPS-140-3 mode using SHA-1\MD-5 (RFC-4122)

### ISSUE THREAD

**Issue by krishnan-unni** [dotnet/runtime#87884]
### Description

According to RFC-4122 (https://www.rfc-editor.org/rfc/rfc4122#section-4.3), it is recommended to use SHA-1 or MD-5 for hashing if we need to generate a UUID-5 (name based).

As per the US government FIPS-140-3, it is not allowed to use SHA-1 for security-related cryptographic purposes but for non-security purposes.

Now, it works fine, but if we turn on the FIPS mode in Windows, the SHA-1\MD-5 functions won't be available, and it will result in an InvalidOperationException.

What is the alternative to this? Is there a FIPS compliant module that we can target to both `net48 `and `net6.0-windows`

### Reproduction Steps

The below code would work when FIPS is turned OFF, but it throws an InvalidOperationException when FIPS is turned ON.
```
using System;
using System.Security.Cryptography;

public class Program
{
    public static void Main()
    {
        try
        {
            using (SHA1Managed sha1 = new SHA1Managed())
            {
                byte[] data = System.Text.Encoding.ASCII.GetBytes("test data");
                byte[] hashData = sha1.ComputeHash(data);
                string hash = Convert.ToBase64String(hashData);
                Console.WriteLine(hash);
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.Message);
        }
    }
}
```

### Expected behavior

If SHA-1 doesn't work, we need an alternative for UUID-5 generation adhering to RFC-4122.

### Actual behavior

SHA-1 has a blanket ban when FIPS is ON even if it is for simple UUID 5 generation.

**Comment by bartonjs** [comment]
.NET doesn't enforce FIPS algorithms.  Are you, perhaps, using Red Hat Enterprise Linux and the system cryptography policy is banning the use of SHA-1?  If so, you'll have to configure the RHEL crypto policy.

**Comment by krishnan-unni** [comment]
@bartonjs Let me correct that initial statement. Found out that I had set it to 4.8, but it was targeting 4.7.2 since it was getting overridden at the project level.

Here is a screenshot while using MD5 in 4.7.2. I don't get this error in 4.8.
![image](https://github.com/dotnet/runtime/assets/14880339/2cfcc6b5-ad2a-4e80-8884-bcc5d0a9ecfb)

The issue is with MD5 (not SHA-1) and .Net 4.7.2 (not 4.8). 
Based on what I see here: https://learn.microsoft.com/en-us/windows/security/threat-protection/fips-140-validation
Windows currently is validated only for FIPS-140-2 (not 140-3). That is why SHA1 is not throwing errors like MD5 (like you stated above). 

So the question is:
- Is there a timeline or plan for Windows validating to enforce FIPS 140-3?
- If we turn on FIPS, is there an alternative rather than updating the application to 4.8 to continue using SHA1\MD5 for UUID generation (or other non-security related) purposes?

And yes, I agree, we should almost always use SHA1. The posted code was for producing the issue as part of the security validation test.

**Comment by Jozkee** [comment]
> Is there a timeline or plan for Windows validating to enforce FIPS 140-3?

This may be related https://learn.microsoft.com/en-us/azure/compliance/offerings/offering-fips-140-2.

> If we turn on FIPS, is there an alternative rather than updating the application to 4.8 to continue using SHA1\MD5 for UUID generation (or other non-security related) purposes?

I think the alternative was mentioned on https://learn.microsoft.com/en-us/dotnet/framework/migration-guide/retargeting/4.7.2-4.8#suggestion.

> If your application targets .NET Framework 4.7.2 or earlier, you can also opt in to this change by adding the following AppContextSwitchOverrides configuration setting to the <runtime> section of your application configuration file:
> 
> ```xml
> <runtime>
>   <AppContextSwitchOverrides value="Switch.System.Security.Cryptography.UseLegacyFipsThrow=false" />
> </runtime>
> ```
