### ISSUE TITLE
`UnsafeAccessor` works on non-static methods

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#87881]
```C#
    class InstanceAccessors
    {
        public InstanceAccessors() { }

        [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
        public extern InstanceAccessors UnsafeNonStaticAccessorForConstructor();
    }

   void Test()
   {
       (new InstanceAccessors()).InstanceAccessors(); // Works
   }
```

Per the proposal https://github.com/dotnet/runtime/issues/81741, the attribute should only be effective on static methods. It's also not clear what it means on instance methods.

@AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
> the attribute should only be effective on static methods

Yep. I will add a run-time check for CoreCLR and a compile time check in NativeAOT.

/cc @fanyang-mono @jkotas
