### ISSUE TITLE
RuntimeEnvironment.GetSystemVersion returns wrong version

### ISSUE THREAD

**Issue by luchunminglu** [dotnet/runtime#87908]
### Description

I write code in dotnet7, but RuntimeEnvironment.GetSystemVersion() returns v4.0.30319

### Reproduction Steps

public static void Main(string[] args)
        {
            Console.WriteLine(RuntimeEnvironment.GetSystemVersion());
}

### Expected behavior

7.0.7

### Actual behavior

v4.0.30319

**Comment by huoyaoyuan** [comment]
`RuntimeEnvironment.GetSystemVersion()` returns the "runtime version" attribute of corelib image:

https://github.com/dotnet/runtime/blob/2e764d6eb092fc8f05c42e6f137347c3eab45fd0/src/libraries/System.Runtime.InteropServices/src/System/Runtime/InteropServices/RuntimeEnvironment.cs#L37

The "runtime version" is actually an indicator of .NET Framework in-place replacement, not product releases. For example, for .NET Framework 2.0-3.5 it's v2.0.50727, and for 4.X it's always v4.0.30319.

You can use `RuntimeInformation.FrameworkDescription` to get a better version string. `Environment.Version` also returns the version in expected value now.

We should probably obsolete the entire `RuntimeEnvironment` type since it's not providing meaningful information in .NET core.

**Comment by joshudson** [comment]
I would argue that for most processes, `null` is the correct return, because for .NET Core processes, the framework CLR is not loaded (check DLL list). If you load the framework CLR via a P/Invoke to a mixed-mode DLL, expect something wild to happen.

**Comment by AaronRobinsonMSFT** [comment]
@richlander I recall you working on the version confusion in a previous release. Do you have any insight into this API and how you would expect it documented? The current implementation is below.

https://github.com/dotnet/runtime/blob/84873e6c4e38b87185ad64beb95c6b76ec7f8d60/src/libraries/System.Runtime.InteropServices/src/System/Runtime/InteropServices/RuntimeEnvironment.cs#L37

**Comment by jkotas** [comment]
I think we should make this API to return meaningful version, ie return `v8.0.0` in  .NET 8.

**Comment by AaronRobinsonMSFT** [comment]
Will do. If we start returning `v8.0.0`, does that mean we need to update the doc in any meaningful way?

**Comment by stephentoub** [comment]
I agree with Jan.  Unless we discover something that doing so would massively break, it'd be good to have this return something "correct" for the .NET being used.

**Comment by AaronRobinsonMSFT** [comment]
I'm following the work/goals done in https://github.com/dotnet/runtime/issues/28788, fair?

**Comment by AaronRobinsonMSFT** [comment]
That means we have two options:

```
Environment.Version: 8.0.0
RuntimeInformation.FrameworkDescription: .NET 8.0.0
```

I think `Environment.Version` is the one people are expecting, but I can also understand the latter.

**Comment by AaronRobinsonMSFT** [comment]
Since the existing returns `"v4.0.30319"`, another option is to do the following to keep the general format consistent.

```csharp
public static string GetSystemVersion() => "v" + Environment.Version;
```

**Comment by richlander** [comment]
I'm not sure. I can see why that might be good, but we're already breaking the API. Why not go all the way and return the pure numeric values.

**Comment by richlander** [comment]
Ya. Also, there is already an API w/o the `v` so this is the one with the `v`.

**Comment by richlander** [comment]
Thanks @AaronRobinsonMSFT. You are now part of the "simplifying .NET versioning" v-team. I'll make sure to include you in our upcoming meetings.

**Comment by AaronRobinsonMSFT** [comment]
😨

**Comment by stephentoub** [comment]
> You are now part of the "simplifying .NET versioning" v-team

Here, @richlander, I've fixed it for you:
You are now ~part of~ the "simplifying .NET versioning" v-team

**Comment by richlander** [comment]
I VERY MUCH stand corrected @stephentoub.

Well played.

**Comment by ericstj** [comment]
This is one of those good breaking changes, but let's drop a note in the breaking change docs around it.

**Comment by richlander** [comment]
BCN: https://github.com/dotnet/docs/issues/36525
