### ISSUE TITLE
[API Proposal] ConfigureHttpClientDefaults for HttpClientFactory

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#87914]
<details>
<summary>Original issue by @JamesNK</summary>

### Background and motivation

`HttpClientFactory` in Microsoft.Extensions.Http allows a developer to centrally configure and instatiate HTTP clients with DI:

```csharp
services
    .AddHttpClient("consoto", c => c.BaseAddress = new Uri("https://consoto.com/"))
    .AddHttpMessageHandler<MyAuthHandler>();

services
    .AddHttpClient("github", c => c.BaseAddress = new Uri("https://github.com/"))
    .AddHttpMessageHandler<MyAuthHandler>();
```

Two named clients are defined in the example above. Unfortunately, there isn't a way to apply the default settings for all clients. Both need `AddHttpMessageHandler<MyAuthHandler>()`.

This issue proposes an `AddHttpClientDefaults` method that can be used to specify configuration that is applied to all clients.

### API Proposal

```diff
namespace Microsoft.Extensions.DependencyInjection;

public static class HttpClientFactoryServiceCollectionExtensions
{
+   public static IHttpClientBuilder AddHttpClientDefaults(this IServiceCollection services);
}
```

### API Usage

`AddHttpClientDefaults` returns an `IHttpClientBuilder`. This is the same type returned by `services.AddHttpClient(...)`. That means all the extension methods for `IHttpClientBuilder` automatically work with `AddHttpClientDefaults`.

```csharp
services.AddHttpClientDefaults()
    .AddHttpMessageHandler<MyAuthHandler>();

// Clients automatically have the handler specified as a default.
services.AddHttpClient("consoto", c => c.BaseAddress = new Uri("https://consoto.com/"));
services.AddHttpClient("github", c => c.BaseAddress = new Uri("https://github.com/"));
```

The default configuration is run on a client before client-specific configuration:

```csharp
services.AddHttpClientDefaults()
    .ConfigureHttpClient(c => c.BaseAddress = new Uri("https://consoto.com/"));

// Client a base address of https://consoto.com
services.AddHttpClient("consoto");

// Client has a base address of https://github.com/ (overrides default)
services.AddHttpClient("github", c => c.BaseAddress = new Uri("https://github.com/"));
```

Default configuration can be added to multiple times, and its order compared to `AddHttpClient` doesn't matter:

```csharp
services.AddHttpClientDefaults()
    .ConfigureHttpClient(c => c.BaseAddress = new Uri("https://consoto.com/"));

// Client a base address of https://consoto.com and has MyAuthHandler
services.AddHttpClient("consoto");

services.AddHttpClientDefaults()
    .AddHttpMessageHandler<MyAuthHandler>();
```

### Alternative Designs

We want `AddHttpClientDefaults` that returns an `IHttpClientBuilder` so existing extension methods automatically work with it.

We want to _**avoid**_ the situation that we are seeing where people are adding two extension methods: one to add configuration to a builder, and another to apply configuration to all builders.

Example of what we don't want:

```csharp
// Add handler to one client
services.AddHttpClient("myclient").AddMyCustomerLogging();

// Add handler to all clients
services.AddMyCustomerLoggingToAllClients();
```

</details>

--------------------

### Background and motivation

`HttpClientFactory` in Microsoft.Extensions.Http allows a developer to configure and create HttpClient instances with DI.

Consider an example where two named clients are defined, and they all need MyAuthHandler in their message handlers chain. 

```csharp
services
    .AddHttpClient("consoto", c => c.BaseAddress = new Uri("https://consoto.com/"))
    .AddHttpMessageHandler<MyAuthHandler>();

services
    .AddHttpClient("github", c => c.BaseAddress = new Uri("https://github.com/"))
    .AddHttpMessageHandler<MyAuthHandler>();
```

Unfortunately, there isn't a way to apply the default settings for all clients. All need `AddHttpMessageHandler<MyAuthHandler>()`.

This issue proposes an `ConfigureHttpClientDefaults` method that can be used to specify configuration that is applied to all clients.

### API Proposal

```c#
// existing
public static class HttpClientFactoryServiceCollectionExtensions
{
    // new
    public static IServiceCollection ConfigureHttpClientDefaults(
        this IServiceCollection services, Action<IHttpClientBuilder> configure) {}
}

// existing
public static class HttpClientBuilderExtensions
{
    // new
    public static IHttpClientBuilder ConfigurePrimaryHttpMessageHandler(
        this IHttpClientBuilder builder,
        Action<HttpMessageHandler, IServiceProvider> configureHandler) {}

    public static IHttpClientBuilder ConfigureAdditionalHttpMessageHandlers(
        this IHttpClientBuilder builder,
        Action<IList<DelegatingHandler>, IServiceProvider> configureAdditionalHandlers) {}


    // existing (+2 overloads)
    // public static IHttpClientBuilder ConfigurePrimaryHttpMessageHandler(this IHttpClientBuilder builder, Func<HttpMessageHandler> configureHandler) {}

    // existing (+2 overloads)
    // public static IHttpClientBuilder AddHttpMessageHandler(this IHttpClientBuilder builder, Func<DelegatingHandler> configureHandler) {}

    // existing -- to be deprecated in the future
    // public static IHttpClientBuilder ConfigureHttpMessageHandlerBuilder(this IHttpClientBuilder builder, Action<HttpMessageHandlerBuilder> configureBuilder) {}
}
```

#### 1. Basic usage and extension methods

`ConfigureHttpClientDefaults` accepts an action over `IHttpClientBuilder`. This is the same type returned by `services.AddHttpClient(...)`. That means all the extension methods for `IHttpClientBuilder` automatically work with `AddHttpClientDefaults`.

```csharp
services.ConfigureHttpClientDefaults(b =>
    b.AddHttpMessageHandler<MyAuthHandler>());

// Clients automatically have the handler specified as a default.
services.AddHttpClient("consoto", c => c.BaseAddress = new Uri("https://consoto.com/"));
services.AddHttpClient("github", c => c.BaseAddress = new Uri("https://github.com/"));
```

#### 2. Order of applying

The default configuration is run on a client before client-specific configuration:

```csharp
services.ConfigureHttpClientDefaults(b =>
    b.ConfigureHttpClient(c => c.BaseAddress = new Uri("https://consoto.com/")));

// Client a base address of https://consoto.com
services.AddHttpClient("consoto");

// Client has a base address of https://github.com/ (overrides default)
services.AddHttpClient("github", c => c.BaseAddress = new Uri("https://github.com/"));
```

Default configuration can be added to multiple times, between each other it will be applied one-by-one in order of registration; and its place in the registration compared to `AddHttpClient` doesn't matter:

```csharp
services.ConfigureHttpClientDefaults(b =>
    b.ConfigureHttpClient(c => c.BaseAddress = new Uri("https://consoto.com/")));

// Client a base address of https://consoto.com and has MyAuthHandler
services.AddHttpClient("consoto");

services.AddHttpClientDefaults()
    .AddHttpMessageHandler<MyAuthHandler>();
```

#### 3. Subsequent per-name reconfiguration

Setting additional properties in a primary handler:

```c#
services.ConfigureHttpClientDefaults(b =>
    b.ConfigurePrimaryHandler(() => new SocketsHttpHandler() { UseCookies = false }));

// will have SocketsHttpHandler with UseCookies = false and MaxConnectionsPerServer = 1
services.AddHttpClient("bar")
    .ConfigurePrimaryHandler((handler, _) => ((SocketsHttpHandler)handler).MaxConnectionsPerServer = 1);
```

Inserting in a specific position or removing from an additional handlers list:

```c#
services.ConfigureHttpClientDefaults(b =>
    b.AddHttpMessageHandler<MyAuthHandler>());

// will have MyLoggingHandler as a top-most wrapper handler, and MyAuthHandler
services.AddHttpClient("baz")
    .ConfigureAdditionalHttpMessageHandlers((handlerList, _) => handlerList.Insert(0, new MyLoggingHandler());

// will NOT have MyAuthHandler
services.AddHttpClient("qux")
    .ConfigureAdditionalHttpMessageHandlers((handlerList, _) =>
        handlerList.Remove(handlerList.SingleOrDefault(h => h.GetType() == typeof(MyAuthHandler))));
```

#### 4. Subsequent per-name reconfiguration -- order of applying

Between each other, the order of `ConfigurePrimaryHandler` and `ConfigureAdditionalHttpMessageHandlers` and other per-name configuration methods is the same as if it was implemented via `ConfigureHttpMessageHandlerBuilder` -- in order of registration, and if a subsequent write overwrites e.g. a primary handler instance, the last one "wins".

```c#
// Primary handler will already be a SocketsHttpHandler instance because it was set in ConfigureHttpClientDefaults
// below, which runs first, so it is safe to cast
services.AddHttpClient("bar")
    .ConfigurePrimaryHandler((handler, _) => ((SocketsHttpHandler)handler).MaxConnectionsPerServer = 1);

// But the second call overwrites primary handler, so the final result will NOT have MaxConnectionsPerServer  set
services.AddHttpClient("bar")
    .ConfigurePrimaryHandler(() => new SocketsHttpHandler() { UseCookies = false }));

services.ConfigureHttpClientDefaults(b =>
    b.ConfigurePrimaryHandler(() => new SocketsHttpHandler()));
```

**Comment by CarnaViire** [comment]
We had a discussion with @stephentoub yesterday about the API shape and we came up with a potentially more easy-to-undersand API:

```c#
public static IServiceCollection ConfigureHttpClientDefaults(this IServiceCollection services, Action<IHttpClientBuilder> configure) {}
```

One of the main points was that `AddHttpClientDefaults()` itself is a "no-op" which doesn't bring any value if the builder is not subsequently configured. The API proposed requires a configuration method to be passed.
This API also mitigates the issue we've discussed on our call @JamesNK

I strongly believe we need 2 additional APIs to be able to conveniently modify default configuration per-name:

```c#
public static IHttpClientBuilder ConfigurePrimaryHttpMessageHandler(this IHttpClientBuilder builder, Action<HttpMessageHandler, IServiceProvider> configureHandler) {}
public static IHttpClientBuilder ConfigureAdditionalHttpMessageHandlers(this IHttpClientBuilder builder, Action<IList<DelegatingHandler>, IServiceProvider> configureAdditionalHandlers) {}
```

While this _can_ be achieved through `ConfigureHttpMessageHandlerBuilder`, I would strongly advise _against_ it.

I'd like to avoid encouraging users to use the API that forbids optimizations and that we are planning to eventually deprecate (as it prevents us from improvements and/or fixes like https://github.com/dotnet/runtime/issues/35987 and https://github.com/dotnet/runtime/issues/47091 that require separation of PrimaryHandler creation from additional handlers creation) -- and currently there's no other way.

Usages:

```c#
services.ConfigureHttpClientDefaults(b =>
    b.AddHttpMessageHandler<MyAuthHandler>()
        .ConfigurePrimaryHandler(() => new SocketsHttpHandler() { UseCookies = false }));

// will have MyAuthHandler and SocketsHttpHandler with UseCookies = false
services.AddHttpClient("foo");

// will have MyAuthHandler and SocketsHttpHandler with UseCookies = false and MaxConnectionsPerServer = 1
services.AddHttpClient("bar")
    .ConfigurePrimaryHandler((handler, _) => handler.MaxConnectionsPerServer = 1);

// will have MyLoggingHandler as a top-most wrapper handler, MyAuthHandler, and SocketsHttpHandler
// with UseCookies = false
services.AddHttpClient("baz")
    .ConfigureAdditionalHttpMessageHandlers((handlerList, _) => handlerList.Insert(0, new MyLoggingHandler());

// will have SocketsHttpHandler with UseCookies = false and will not have MyAuthHandler
services.AddHttpClient("qux")
    .ConfigureAdditionalHttpMessageHandlers((handlerList, _) =>
        handlerList.Remove(handlerList.SingleOrDefault(h => h.GetType() == typeof(MyAuthHandler))));
```

**Comment by JamesNK** [comment]
> We had a discussion with @stephentoub yesterday about the API shape and we came up with a potentially more easy-to-undersand API:
> 
> ```cs
> public static IServiceCollection ConfigureHttpClientDefaults(this IServiceCollection services, Action<IHttpClientBuilder> configure) {}
> ```
> 
> One of the main points was that `AddHttpClientDefaults()` itself is a "no-op" which doesn't bring any value if the builder is not subsequently configured. The API proposed requires a configuration method to be passed. This API also mitigates the issue we've discussed on our call @JamesNK

Good point that `AddHttpClientDefaults()` doesn't do anything by itself. However, it's worth mentioning that `AddHttpClient("name")` doesn't do anything either. It just returns a builder with the name, and that's it:

https://github.com/dotnet/runtime/blob/3195fbbd82fdb7f132d6698591ba6489ad6dd8cf/src/libraries/Microsoft.Extensions.Http/src/DependencyInjection/HttpClientFactoryServiceCollectionExtensions.cs#L78-L86

I like how `AddHttpClientDefaults()` is so similar to `AddHttpClient(...)`. But, I don't have a strong objection to `ConfigureHttpClientDefaults`. It solves the chaining issue.

> I strongly believe we need 2 additional APIs to be able to conveniently modify default configuration per-name:

Do they need to be done right now as part of this issue? As far as I can tell they don't block the customer scenarios in this issue, and they aren't blocked from being done in the future.

Off topic, I noticed a problem in one of your sample usages:

> ```cs
> // will have MyAuthHandler and SocketsHttpHandler with UseCookies = false and MaxConnectionsPerServer = 1
> services.AddHttpClient("bar")
>     .ConfigurePrimaryHandler((handler, _) => handler.MaxConnectionsPerServer = 1);
> ```

In the proposed API, this example is missing a cast from `HttpMessageHandler` to `SocketsHttpHandler`:

```cs
// will have MyAuthHandler and SocketsHttpHandler with UseCookies = false and MaxConnectionsPerServer = 1
services.AddHttpClient("bar")
    .ConfigurePrimaryHandler((handler, _) => ((SocketsHttpHandler)handler).MaxConnectionsPerServer = 1);
```

**Comment by CarnaViire** [comment]
> Good point that AddHttpClientDefaults() doesn't do anything by itself. However, it's worth mentioning that AddHttpClient("name") doesn't do anything either. It just returns a builder with the name, and that's it

Good point, even though that's not strictly true, it will add all the HttpClientFactory infra the first time it's called... so you can use the factory to create (unconfigured/default) clients right away. And while `AddHttpClientDefaults` would also all the infra, it wouldn't bring any more value than an empty AddHttpClient call... Though, I liked the similarity as well. I suggest bringing both options to the API review and decide there.

**Comment by stephentoub** [comment]
The concept of a parameterless method adding a new named client makes sense. The concept of a parameterless method adding defaults does not; it suggests without doing it there aren't defaults, which is both confusing and incorrect.

**Comment by JamesNK** [comment]
**Updating to use ConfigureHttpClientDefaults:** [`a13c14a` (#87953)](https://github.com/dotnet/runtime/pull/87953/commits/a13c14a968eeab38e86825a7f77d562e64a718dd)

Simple change. Feels good to use.

**Add extra configure methods for additional handlers and primary handler:** [`ec57e0a` (#87953)](https://github.com/dotnet/runtime/pull/87953/commits/ec57e0aa970a89ebb876677ff8d5ee356b932ed8)

I implemented these by using the existing `HttpMessageHandlerBuilderActions`. That means the order the configuration runs in depends on when it is called.

What happens if someone does:

```cs
services.AddHttpClient("bar")
    .ConfigurePrimaryHandler((handler, _) => ((SocketsHttpHandler)handler).MaxConnectionsPerServer = 1);

services.AddHttpClient("bar")
        .ConfigurePrimaryHandler(() => new SocketsHttpHandler() { UseCookies = false }));
```

Exact thought needs to be put into when these methods run.

Another example:

```cs
services.AddHttpClient("bar")
    .AddHttpMessageHandler(() => Mock.Of<DelegatingHandler>())
    .ConfigureAdditionalHttpMessageHandlers((additionalHandlers, _) =>
    {
        additionalHandlers.Clear();
    });
```

The code above doesn't result in no additional handlers. It results in two additional handlers because after the delegate added by `ConfigureAdditionalHttpMessageHandlers` runs and clears the collection, configuration the logging filter adds afterward then adds two logging handlers.

**Comment by JamesNK** [comment]
I think the intent is these configuration methods is they run after `HttpMessageHandlerBuilderActions`. Won't extra APIs be needed on `HttpClientFactoryOptions`?

```diff
public class HttpClientFactoryOptions
{
+   public IList<Action<HttpMessageHandler>> PrimaryMessageHandlerActions { get; }

+   public IList<Action<IList<HttpMessageHandler>> AdditionalHttpMessageHandlerActions { get; }
}
```

**Comment by CarnaViire** [comment]
Thanks @JamesNK!

> That means the order the configuration runs in depends on when it is called.

That was exactly the intent, and it aligns with how usually in DI registrations the last one "wins". So in the first example, the second ConfigurePrimaryHandler overwrites the previous handler, and that's expected. 

> Exact thought needs to be put into when these methods run.

The idea is that they are run in the same time they would previously run when people used ConfigureHttpMessageHandlerBuilder and allow for simple transition with the similar and expected functionality. Basically, implementation via HttpMessageHandlerBuilderActions is a baseline, and it further can be optimized by splitting into two collections PrimaryMessageHandlerActions and  AdditionalHttpMessageHandlerActions, etc.

> I think the intent is these configuration methods is they run after HttpMessageHandlerBuilderActions.

The final goal is that there would be no HttpMessageHandlerBuilderActions, so both collections PrimaryMessageHandlerActions and  AdditionalHttpMessageHandlerActions could be run independently (but still depending on the order of registration within each group).

As soon as anything is added to HttpMessageHandlerBuilderActions, everything would need to fall back to single HttpMessageHandlerBuilderActions collection to retain order.

> Won't extra APIs be needed on HttpClientFactoryOptions?

It's nice to have, but I believe it still can be done with them being internal.

> Someone might expect the code above to result in no additional handlers for the client. Actually the client still has two additional handlers. After the delegate added by ConfigureAdditionalHttpMessageHandlers runs and clears the collection, configuration by the logging filter adds two logging handlers.

I would consider logging to be something a bit separate from other additional handlers, and with separate configuration to be discussed in https://github.com/dotnet/runtime/issues/85840.

Also, the same would happen if you clear the collection via ConfigureHttpMessageHandlerBuilder so I would vote for them to have similar behavior.

**Comment by JamesNK** [comment]
>>I think the intent is these configuration methods is they run after HttpMessageHandlerBuilderActions.
>
> The final goal is that there would be no HttpMessageHandlerBuilderActions, so both collections PrimaryMessageHandlerActions and AdditionalHttpMessageHandlerActions could be run independently (but still depending on the order of registration within each group).
>
>As soon as anything is added to HttpMessageHandlerBuilderActions, everything would need to fall back to single HttpMessageHandlerBuilderActions collection to retain order.

I know you want people to stop using the build `HttpMessageHandlerBuilderActions`. I mentioned the builder actions as a shortcut for the extension methods that configure it internally: `ConfigurePrimaryHttpMessageHandler`, `AddHttpMessageHandler`.

Source:
https://github.com/dotnet/runtime/blob/cf50b7d86a1456e9aad09ddeafd5ff8701f9afdc/src/libraries/Microsoft.Extensions.Http/src/DependencyInjection/HttpClientBuilderExtensions.cs#L63-L221

If the new methods aren't intended to run last then I guess what they're currently doing is fine.

**Comment by CarnaViire** [comment]
>  I mentioned the builder actions as a shortcut for the extension methods that configure it internally

I know. What I meant is something like [the following](https://github.com/CarnaViire/runtime/blob/2a1c16983852944dd4bc53c8b8d4f0741d29bd3c/src/libraries/Microsoft.Extensions.Http/src/HttpClientFactoryOptions.cs#L85-L101) that could be called instead of `options.HttpMessageHandlerBuilderActions.Add(...` in the methods above

```c#
internal void AddPrimaryHandlerAction(Action<IPrimaryHandlerBuilder> action, bool disregardPreviousActions)
{
    if (_primaryHandlerActions != null) // HttpMessageHandlerBuilderActions is empty, collections are separated
    {
        if (disregardPreviousActions)
        {
            _primaryHandlerActions.Clear();
        }
        _primaryHandlerActions.Add(action);
    }
    else
    {
        // can't optimize in case of a unified collection
        HttpMessageHandlerBuilderActions.Add(action);
    }
}
```

Or you meant access to that functionality from the user side as well?

**Comment by JamesNK** [comment]
I'm going to leave any more changes until after the API is approved.

It's important to be clear about the configuration's order with `ConfigurePrimaryHttpMessageHandler` and `ConfigureAdditionalHttpMessageHandlers`. What are the scenarios these methods will be used in? Have example code of things configured in different and unexpected orders and what you expect the result to be.

This is a subtle but important detail. Right now there isn't information any information about the order of configuration for these methods.

**Comment by JamesNK** [comment]
@CarnaViire What's the status here? I'm going on leave in less than a week and there are outstanding questions. When will they be answered? When will this go to API review?

**Comment by CarnaViire** [comment]
> What's the status here?

I'm preparing the description for the API review, together with https://github.com/dotnet/runtime/issues/84075 and https://github.com/dotnet/runtime/issues/77312

> When will this go to API review?

We don't have a date yet, but I've let Immo know, as I'd like to go over all HttpClientFactory APIs in one session

> you'll need to represent this

That's what I intended to do, yes

> there are outstanding questions. When will they be answered?

What exact questions are not answered? I might be missing something, but I believe I've commented on the expected behavior previously here https://github.com/dotnet/runtime/issues/87914#issuecomment-1611325307 (expected = exactly how it would behave if it was done by ConfigureAdditionalHttpMessageHandlers instead), and some examples were here https://github.com/dotnet/runtime/issues/87914#issuecomment-1604483290 and I will add some more for the API review.

**Comment by JamesNK** [comment]
Thanks, I wasn’t sure if the order question was answered.

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace Microsoft.Extensions.DependencyInjection;

public static partial class HttpClientFactoryServiceCollectionExtensions
{
    public static IServiceCollection ConfigureHttpClientDefaults(
        this IServiceCollection services,
        Action<IHttpClientBuilder> configure);
}

public static partial class HttpClientBuilderExtensions
{
    // Existing:
    //
    // public static IHttpClientBuilder ConfigurePrimaryHttpMessageHandler(
    //    this IHttpClientBuilder builder,
    //    Func<HttpMessageHandler> configureHandler);
    //
    // public static IHttpClientBuilder AddHttpMessageHandler(
    //    this IHttpClientBuilder builder,
    //    Func<DelegatingHandler> configureHandler);
    //
    // Existing but to be deprecated in the future:
    //
    // public static IHttpClientBuilder ConfigureHttpMessageHandlerBuilder(
    //    this IHttpClientBuilder builder,
    //    Action<HttpMessageHandlerBuilder> configureBuilder);

    // new
    public static IHttpClientBuilder ConfigurePrimaryHttpMessageHandler(
        this IHttpClientBuilder builder,
        Action<HttpMessageHandler, IServiceProvider> configureHandler);

    public static IHttpClientBuilder ConfigureAdditionalHttpMessageHandlers(
        this IHttpClientBuilder builder,
        Action<IList<DelegatingHandler>, IServiceProvider> configureAdditionalHandlers);
}
```
