### ISSUE TITLE
link option for PIE executable

### ISSUE THREAD

**Issue by chunseoklee** [dotnet/runtime#8791]
I have built the latest coreclr (commit 637bfeffb0fd0378ff6d04d7bb845938b77bdade) and found that it does not produce PIE executables for corerun, crossgen, ildasm, ilasdm. 
```
twoflower@js2-desktop ~/d/c/b/P/Linux.x64.Release> hardening-check crossgen
crossgen:
 Position Independent Executable: no, normal executable!
 Stack protected: yes
 Fortify Source functions: no, only unprotected functions found!
 Read-only relocations: yes
 Immediate binding: no, not found!
```
But, compilation option `-fPIE` is introduced on commit 891b2aa2b1c65ff157a840c3462fa6d007f2dac9.
Am I missing something(flag) or we need a patch to enable PIE executable ?

**Comment by jkotas** [comment]
Fixed by #685
