### ISSUE TITLE
[ComInterfaceGenerator] Custom enum return type in base interface unrecognized when processing derived interface

### ISSUE THREAD

**Issue by lordmilko** [dotnet/runtime#87915]
### Description

The ComInterfaceGenerator throws an error when attempting to parse a derived interface whose base interface contains an unqualified custom enum type as the return type of a method.

For example, attempting to compile the following code

```c#
public enum HRESULT
{
}

[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
[Guid("4BBA36C0-20BB-4DFF-9241-71992D498B39")]
[GeneratedComInterface]
public partial interface Base
{
    // Base will generate its wrapper successfully, but Derived will complain Base.M1's HRESULT type is unknown
    HRESULT M1();
}

[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
[Guid("8BCFEC21-589D-45BC-908C-E038252F3453")]
[GeneratedComInterface]
public partial interface Derived : Base
{
    HRESULT M2();
}
```
generates the following errors

```
error CS0246: The type or namespace name 'HRESULT' could not be found (are you missing a using directive or an assembly reference?)
error CS0539: 'InterfaceImplementation.M1()' in explicit interface declaration is not found among members of the interface that can be implemented
```

* If `Derived` is modified to not derive from `Base` the application successfully compiles
* Changing the return type of `M1` to a runtime type like `int` successfully compiles
* Fully qualifying the return type of `M1` (e.g. `ConsoleApp1.HRESULT M1()`) also successfully compiles
* Specifying an argument of type `HRESULT` to `M1` with return type `void` successfully compiles - the issue only occurs when our custom type is used as a return type

This behavior occurs regardless of whether `PreserveSigAttribute` is specified

### Reproduction Steps

```c#
public enum HRESULT
{
}

[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
[Guid("4BBA36C0-20BB-4DFF-9241-71992D498B39")]
[GeneratedComInterface]
public partial interface Base
{
    HRESULT M1();
}

[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
[Guid("8BCFEC21-589D-45BC-908C-E038252F3453")]
[GeneratedComInterface]
public partial interface Derived : Base
{
    HRESULT M2();
}
```

### Expected behavior

Custom return types are properly recognized without needing to fully qualify their namespaces

### Actual behavior

```
error CS0246: The type or namespace name 'HRESULT' could not be found (are you missing a using directive or an assembly reference?)
error CS0539: 'InterfaceImplementation.M1()' in explicit interface declaration is not found among members of the interface that can be implemented
```

**Comment by AaronRobinsonMSFT** [comment]
@lordmilko We'll close this for now as I agree with @jkoritzinsky. Please let us know if this wasn't addressed in the next preview.
