### ISSUE TITLE
Optimize allocations of a capturing lambda in `GetRuntimeNativeAssets`

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/runtime#87911]
![image](https://github.com/dotnet/runtime/assets/31348972/d37be1e8-3d68-4318-906b-db9b1a3d8b22)

![image](https://github.com/dotnet/runtime/assets/31348972/4bc5fe95-acdd-4f59-a6c1-5690b891bd02)

---

Also

![image](https://github.com/dotnet/runtime/assets/31348972/04bb630b-e5cb-4f99-801d-56b83655c57f)

This seems related to this lambda:

https://github.com/dotnet/runtime/blob/ce953d023f20964303cf761bf6e2e72d70bdf3d9/src/libraries/Microsoft.Extensions.DependencyModel/src/DependencyContextExtensions.cs#L35

**Comment by vitek-karas** [comment]
What scenario requires you to call this code so many time for this to become a problem?
(I'm not questioning that this is a problem, I'm just surprised it's used that often)
