### ISSUE TITLE
.Net application aborts at startup with "Failed to create CoreCLR, HRESULT: 0x80004005" on windows server - when upgrade .Net5 to .Net 6

### ISSUE THREAD

**Issue by NargesMousavi** [dotnet/runtime#87937]
### Steps to reproduce
I' v decided to upgrade a project from .net5 to .net6. After upgrade when I publish and then deploy through CI/CD server that contains .net6 runtime, the production server that installed windows server couldn't run the project and aborts at startup with "Failed to create CoreCLR, HRESULT: 0x80004005".
But when I publish on my pc that contains .net6 runtime too, then copy to the same machine(windows server), application runs without any error.
I read these issues [https://github.com/dotnet/runtime/issues/3168](url) , [https://github.com/dotnet/runtime/issues/70758](url) but I couldn't find useful guide.

**Comment by NargesMousavi** [comment]
my ci/cd server is GitLab and in next step I want to reinstall .NET runtime on ci/cd server maybe this could fix problem and I can publish through CI/CD server too.

**Comment by NargesMousavi** [comment]
I also enabled tracing by setting COREHOST_TRACE=1 env. variable then run the project and got the same error, no more information.

**Comment by vitek-karas** [comment]
Just want to make sure I understand the symptoms:
* If you build the app locally (on your dev machine) for .NET 6 and copy it to the production server, it runs just fine
* If you build the app in CI/CD and copy to the production server, it fails
Right?

Do you publish the application as self-contained?
Can you get the copy of the app produced by CI/CD and try to run it locally on your dev machine?

Since some .NET 6 app can run on the server this is likely not anything to do with the server itself. It's more likely a problem with the app. For example, you can get this error is it's a self-contained application and there's no `System.Private.CoreLib.dll` in it.

**Comment by NargesMousavi** [comment]
- yes, I have exactly the problem you described.
- yes, I publish the project as self-contained in both my local dev machine and in GitLab server using this command `dotnet publish -c Release -r win-x64 `
At the first I also care about exciting `System.Private.CoreLib.dll` and there is in it.
I copy the app produced by CI/CD and try to run it locally on my dev machine, then it fails with the same error `Failed to create CoreCLR, HRESULT: 0x80004005` . 
@vitek-karas

**Comment by NargesMousavi** [comment]
I  think installed .NET runtime on GitLab server is not  .NET6, because in produced app by  CI/CD `coreclr.dll` assembly version is 5.
I 'll verify this now.

**Comment by NargesMousavi** [comment]
I checked .NET version on ci/cd server. .net6 runtime was instilled on this server , also other versions were installed as below shot:
[https://drive.google.com/file/d/1FxnPqbxgDeW704XVbGV6S2Clgm7XLVdn/view?usp=sharing](url)
I'm going to verify why publish a .NET6 application as self-contained on this ci/cd server results an `coreclr.dll `assembly version  5.

**Comment by vitek-karas** [comment]
Note that the version of the SDK on the CI/CD doesn't necessarily affect the version of .NET used when publishing a self-contained app. It is perfectly valid to use .NET 6 SDK to publish a .NET 5 self-contained app. The .NET version used by the app is determined by its `TargetFramework` which is set in the `app.csproj`.

**Comment by elinor-fung** [comment]
@NargesMousavi were you able to check that your app is set up to build for .NET 6 and take a look at why you ended up with a .NET 5 `coreclr`?
