### ISSUE TITLE
[NativeAOT] HardwareIntrinsics\X64Avx512 test fails on machines with no avx512 (on Windows only)

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#87931]
My main machine has a relatively new CPU (Ryzen 5950X), but there is no AVX512 support. 
I suspect the situation of not having AVX512 is common

On Linux the test .proj checks if AVX512 is present and does not enable the test if not. - i.e. on the same machine in WSL environment the test does not run.  

On Windows the test runs and fails all the time and it becomes a nuisance. Like when one need to run the tests in a loop to a failure the test must be disabled/deleted, but later reverted.

If it is at all possible to make the test conditional in a similar way as on Linux, it needs to be done.
Or perhaps make the test opt-in with some flag and set that flag in CI.

**Comment by MichalStrehovsky** [comment]
Cc @tannergooding 

I don't see a way to do this with WMI. Looks like we could p/invoke into [IsProcessorFeaturePresent](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-isprocessorfeaturepresent) with [PowerShell](https://www.leeholmes.com/powershell-pinvoke-walkthrough/), but that only lets us query for AVX512f and not the full set of extensions the test expects. I don't have other ideas.

**Comment by VSadov** [comment]
I guess “make the test opt-in with some flag and set that flag in CI.” is the only other option.  
With the state of AVX512 adoption perhaps the test must be opt-in for a few months or years?

**Comment by tannergooding** [comment]
@MichalStrehovsky, `IsProcessorFeaturePresent` should be sufficient. The ISAs required are supported by all AVX512 capable hardware except for Knight's Landing, which is very unlikely to be hit.

Alternatively, we should be able to check for the NAOT exit message saying the hardware is unsupported or roll our own small program that queries CPUID and reports true/false if the required ISAs aren't present.

**Comment by MichalStrehovsky** [comment]
The runtimelab CI is also running into this (reported by @yowl over discord):
https://dev.azure.com/dnceng-public/public/_build/results?buildId=319797&view=logs&j=882c4811-6d19-5cba-ad52-4ad8914abd7d&t=5f7b77ae-d2f0-519c-d681-a88dc27ee52f
