### ISSUE TITLE
String.IndexOf("'") returns incorrect value in Thai culture

### ISSUE THREAD

**Issue by Epic-Santiago** [dotnet/runtime#87939]
### Description

`String.IndexOf("'")` always returns zero. Tested the following cases:
- String is empty
- String has a single quote in a position greater than zero
- String has no single quotes

`String.IndexOf('\'')` works correctly.

### Reproduction Steps

```c#
System.Threading.Thread.CurrentThread.CurrentCulture = System.Globalization.CultureInfo.GetCultureInfo("th-TH");
System.Diagnostics.Debug.Assert("".IndexOf('\'') == "".IndexOf("'"));
```

### Expected behavior

The return value of `String.IndexOf("'")` should match that of `String.IndexOf('\'')`. It should return the correct position of the single quote within the string.

### Actual behavior

Always returns zero regardless of the input.

### Regression?

Yes. It works on .NET Framework and on .NET 6 with the old NLS behaviour:
```xml
<ItemGroup>
  <RuntimeHostConfigurationOption Include="System.Globalization.UseNls" Value="true" />
</ItemGroup>
```

### Known Workarounds

Use the `System.Globalization.UseNls` switch or use Ordinal like so:
```c#
String.IndexOf("'", System.StringComparison.Ordinal);
```

### Configuration

- .NET 6
- Windows 10
- x64
- I don't believe it is specific to this configuration other than .NET 6 (this likely worked prior to .NET 5 and the switch from NLS to ICU)
- Not a browser issue

**Comment by tarekgh** [comment]
please have a look at https://github.com/dotnet/runtime/issues/59120#issuecomment-923209271.

**Comment by Epic-Santiago** [comment]
Thanks for pointing me to that other issue. I understand the explanation given though I find it surprising. I don't understand why `IndexOf(string)` returns a different value from `IndexOf(char)`. It seems to be implied that the char overload is ordinal but that does not seem to be the case. Both the `string` and `char` overloads can take a `StringComparison` parameter and I see no reason why they would behave inconsistently when the parameter is not provided. Even taking into account the explanation from the  other issue, this still seems like a bug.

**Comment by Epic-Santiago** [comment]
Thinking about his further, it seems that if the character is ignored in Thai then the returned index should be -1, not 0? On an empty string, zero is an invalid index and therefore `IndexOf` is returning an impossible index.

**Comment by tarekgh** [comment]
> On an empty string, zero is an invalid index and therefore IndexOf is returning an impossible index.

We are having this behavior for the app compatibility reason. It is tricky too if returning `-1` because this means `'` is not part or the empty string but at the same time the empty string equal to `'`. 

> I don't understand why IndexOf(string) returns a different value from IndexOf(char)

The reason is mentioned in the link I pasted before. The overload that takes string is performed as linguistic operation, but the one take character is performed as ordinal.  We have the issue https://github.com/dotnet/runtime/issues/43956 tracking make the experience better. 

> Even taking into account the explanation from the other issue, this still seems like a bug.

It is not a bug; it is how the APIs are exposed and the default behavior for every API. This is why we are tracking to make this better https://github.com/dotnet/runtime/issues/43956.
