### ISSUE TITLE
Failure to create an XmlSerializer throws an unhelpful exception

### ISSUE THREAD

**Issue by mconnew** [dotnet/runtime#87944]
### Description

If an XmlSerializer can't be generated for some reason (eg attributes for a particular type but the property isn't compatible), then a fallback code path is run. On .NET Framework this would do code gen and compile the code generated XmlSerializer. This functionality doesn't exist in .NET and instead it throws a PNSE. This hides the original problem and makes it hard to understand what the real problem is.

This is the exception with message that is thrown:
```
System.PlatformNotSupportedException: Compiling JScript/CSharp scripts is not supported
```

Original issue opened in the WCF repo: https://github.com/dotnet/wcf/issues/2219

### Reproduction Steps

Try to create an XmlSerializer for a type which isn't possible.

### Expected behavior

Throw a meaningful exception

### Actual behavior

A generic PlatformNotSupportedException with an unhelpful exception message.

**Comment by StephenMolloy** [comment]
Fixed by #88804.
