### ISSUE TITLE
Decoder ran into invalid data

### ISSUE THREAD

**Issue by okarpov** [dotnet/runtime#87965]
### Description

HttpClient sends request to ASP.NET Core Kestrel and gets this exception

```
System.InvalidOperationException: Decoder ran into invalid data.
    at System.IO.Compression.BrotliStream.TryDecompress(Span`1 destination, Int32& bytesWritten)
    at System.IO.Compression.BrotliStream.<ReadAsync>g__Core|24_0(Memory`1 buffer, CancellationToken cancellationToken)
    at System.IO.Stream.<CopyToAsync>g__Core|27_0(Stream source, Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
    at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
```

### Reproduction Steps

HttpClient sends request to ASP.NET Core Kestrel

### Expected behavior

should work fine

### Actual behavior

exception

### Configuration

Ubuntu 20.04 LTS (GNU/Linux 5.4.0-29-generic x86_64)

Host:
  Version:      7.0.7
  Architecture: x64
  Commit:       5b20af47d9

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by CarnaViire** [comment]
Can you provide a minimal runnable repro please @okarpov? Without it, this is not actionable for us.

**Comment by wfurt** [comment]
Do you know what headers and compression is used by the server? Obviously if there is some mismatch this is going to fail.

**Comment by okarpov** [comment]
ASP.NET Kestrel has just these two lines:
```
app.UseRequestDecompression();
app.UseResponseCompression();
```

**Comment by wfurt** [comment]
That is not interesting. You will need to look at the wire - to see what headers are exchanged and what compression is negotiated. And possibly verify that the response actually _is_ Brotli compression.
