### ISSUE TITLE
The regular expression does not return a greedy result.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#87976]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/The-regular-expression-does-not-return-a/10285927)._

---
[severity:It's more difficult to complete my work]
I am trying to use a regular expression to matches the content as following
[test.txt](https://aka.ms/dc/file?name=Bab5cb9c7a65e416cb440eb40bd3fa10f638125916829179439_test.txt&tid=ab5cb9c7a65e416cb440eb40bd3fa10f638125916829179439)
The regular expression I used it:
[regularexpression.txt](https://aka.ms/dc/file?name=B28185c1811cb4e6ea76cec767cdd9cc0638125917614483865_regularexpression.txt&tid=28185c1811cb4e6ea76cec767cdd9cc0638125917614483865)
And the result is not correct. The last star(*) will always return a non-greedy result. If I change * to +, it will match one time. But even that, the result is also not greedy. Because it could match 2 times.

---
#### Tracy Wang [MSFT] on 2/22/2023, 00:56 AM: 

(private comment, text removed)
#### 李寒松 on 2/22/2023, 09:03 PM: 

(private comment, text removed)
#### Feedback Bot on 2/23/2023, 00:19 AM: 

(private comment, text removed)
#### Feedback Bot on 6/1/2023, 07:20 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CarnaViire** [comment]
Repro from the user:

```pwsh
$Content=@"
0 Entries of failure 0 (SMI-33)

130 Entries of failure 1 (SMI-2073)

Detected some error explain 1

 in afile.c:184
Detected some error explain 2

 in bfile.c:251
5 Entries of test function 02 (SMI-2073)

Detected some error explain 1

 in afile.c:184
Detected some error explain 2

 in bfile.c:251
 
"@
$RegularExpression1="(?m)(?<EntriesNumber>[0-9]+) Entries of (?<SMICaseName>[\S ]+)\((?<SMICaseNumber>SMI-[0-9]+)\)(\r|\n|\r\n)(\r|\n|\r\n)((?<Description>([\S ]+(\r|\n|\r\n))+)(\r|\n|\r\n) in (?<FileName>[\S]+)\:(?<LineNumber>[0-9]+)(\r|\n|\r\n))*"
$RegularExpression2="(?m)(?<EntriesNumber>[0-9]+) Entries of (?<SMICaseName>[\S ]+)\((?<SMICaseNumber>SMI-[0-9]+)\)(\r|\n|\r\n)(\r|\n|\r\n)((?<Description>([\S ]+(\r|\n|\r\n))+)(\r|\n|\r\n) in (?<FileName>[\S]+)\:(?<LineNumber>[0-9]+)(\r|\n|\r\n))+"
$RegularExpression3="(?m)(?<EntriesNumber>[0-9]+) Entries of (?<SMICaseName>[\S ]+)\((?<SMICaseNumber>SMI-[0-9]+)\)(\r|\n|\r\n)(\r|\n|\r\n)((?<Description>([\S ]+(\r|\n|\r\n))+)(\r|\n|\r\n) in (?<FileName>[\S]+)\:(?<LineNumber>[0-9]+)(\r|\n|\r\n)){2}"
$RegexMatchRes1=[System.Text.RegularExpressions.Regex]::Matches($Content,$RegularExpression1)
$RegexMatchRes2=[System.Text.RegularExpressions.Regex]::Matches($Content,$RegularExpression2)
$RegexMatchRes3=[System.Text.RegularExpressions.Regex]::Matches($Content,$RegularExpression3)

Write-Host 'Powershell Version Info'
$PSVersionTable|Format-Table|Out-String|Write-Host
Write-Host "Regular Expression Version Info"
Write-Host ([System.Text.RegularExpressions.Regex].AssemblyQualifiedName)
Write-Host 'Match Result for Regex1 for Group LineNumber Matches' -ForegroundColor Green
$RegexMatchRes1|Foreach-Object{$_.Groups['LineNumber'].Success}
Write-Host 'Match Result for Regex2 for Group LineNumber Matches' -ForegroundColor Green
$RegexMatchRes2|Foreach-Object{$_.Groups['LineNumber'].Success}
Write-Host 'Match Result for Regex3 for Group LineNumber Matches' -ForegroundColor Green
$RegexMatchRes3|Foreach-Object{$_.Groups['LineNumber'].Success}
```

**Comment by stephentoub** [comment]
The expression is behaving correctly.  Note that the second and third matches aren't actually beginning at the same place as the first.  The first expression with the * matches at the line:
```
0 Entries of failure 0 (SMI-33)
```
whereas the second and third match at the line:
```
130 Entries of failure 1 (SMI-2073)
```
The first expression with a `*` is able to find a match with zero occurrences of that last expression earlier in the input, and so that's what it returns.  It successfully matches everything up until that last unbounded loop, finds zero occurrences of that loop, and completes the match.
