### ISSUE TITLE
Make libmsquic load failures actionable

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#87970]
When user tries to use HTTP/3 or Quic APIs and they fail to load libmsquic (esp. on Linux), we should provide steps to troubleshoot.
1. If the problem was insufficient libmsquic version, say so in exception text.
2. If the problem was general loading failure, give user link to our troubleshooting guide, which we can edit over time, incl. instructions which tools to use to troubleshoot.

It might require exposing new API from Quic APIs. Or we could use it as text of PlatformNotSupportedException we throw from there.
Customer of the API is HttpClient and also any other (external) Quic API user, incl. Kestrel.

**Comment by ManickaP** [comment]
Bullet 1. should be addressed in https://github.com/dotnet/runtime/pull/89112, the rest can be punted to 9.0

**Comment by ManickaP** [comment]
Point 1. addressed, punting to 9.0
