### ISSUE TITLE
Missing timezone version 6.0.18

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#87973]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Missing-timezone-version-6018/10393129)._

---
[severity:I'm unable to use this version]
TimeZoneInfo.GetSystemTimeZones() is missing "Europe/Copenhagen" in .NET 6.0.18. 
Worked fine in earlier versions.

This line will fail in version 6.0.18
var timeZoneInfo = TimeZoneInfo.GetSystemTimeZones().Where(t =t x.Id == "Europe/Copenhagen");
Use Where(t =t.Id.StartsWith("Europe/C") and verify, that Copenhagen is missing.

There is a workaround, though:
var timeZoneTry2 = TimeZoneInfo.FindSystemTimeZoneById("Europe/Copenhagen");

---
#### Feedback Bot on 6/16/2023, 03:40 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CarnaViire** [comment]
Might be related to https://github.com/dotnet/runtime/issues/75275

**Comment by Clockwork-Muse** [comment]
As a side note, timezones can be superseded, split, combined, or a host of any number of things.  It's unlikely that ICU guarantees timezone ids be guaranteed in perpetuity.  There usually is some form of "aliasing" available, but I don't know how that plays out in all situations, or how we handle it.

And that's before things like the user customizing the data.

**Comment by tarekgh** [comment]
I ran the following code on Ubuntu using .NET 6.0 and it work fine. it prints `Time zone: Europe/Copenhagen`

```C#
            var timeZoneInfo = TimeZoneInfo.GetSystemTimeZones().Where(t => t.Id == "Europe/Copenhagen").FirstOrDefault();
            if (timeZoneInfo is not null)
            {
                Console.WriteLine($"Time zone: {timeZoneInfo.Id}");
            }
```

Most likely you are running on Windows. When run on Windows, the returned Ids there will not be IANA Ids and instead will be Windows Ids. `Romance Standard Time` is the Windows Id which is equivalent to `Europe/Copenhagen`.
