### ISSUE TITLE
why  Conserve memory dont have in runtimeconfig.json

### ISSUE THREAD

**Issue by NCLnclNCL** [dotnet/runtime#88013]
https://learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector#heap-limit
i see Conserve memory is in runtimeconfig,json
I don't like setting it via environment variable

**Comment by cshung** [comment]
It is available in `runtimeconfig.json` as `System.GC.ConserveMemory`. It is just the docs that are not up to date.
