### ISSUE TITLE
[API Proposal]: Add IEnumerable<T>.ToReadOnlyList() and ToReadOnlyCollection() extension methods

### ISSUE THREAD

**Issue by dombrovsky** [dotnet/runtime#88018]
### Background and motivation

For more straightforward creation of read-only collections from IEnumerable<T> and IAsyncEnumerable<T>.
So it is possible instead of doing `Array.AsReadOnly(source.ToArray())` do `source.ToReadOnlyCollection()`.

### API Proposal

```csharp
namespace System.Linq;

public static class Enumerable
{
    public static IReadOnlyCollection<TSource> ToReadOnlyCollection<TSource>(this IEnumerable<TSource> source);

    public static IReadOnlyList<TSource> ToReadOnlyList<TSource>(this IEnumerable<TSource> source);
}

public static class AsyncEnumerable
{
      public static ValueTask<IReadOnlyCollection<TSource>> ToReadOnlyCollectionAsync<TSource>(
            this IAsyncEnumerable<TSource> source,
            CancellationToken cancellationToken = default(CancellationToken));

      public static ValueTask<IReadOnlyList<TSource>> ToReadOnlyListAsync<TSource>(
            this IAsyncEnumerable<TSource> source,
            CancellationToken cancellationToken = default(CancellationToken));
}
```

### API Usage

```csharp
IReadOnlyCollection<int> collection = Enumerable.Range(0, 10).ToReadOnlyCollection();
```

### Alternative Designs

Use ToImmutableArray() from System.Collections.Immutable.
In this case would be nice to have one for IAsyncEnumerable:
```csharp
public static ValueTask<ImmutableArray<TSource>> ToImmutableArrayAsync<TSource>(
            this IAsyncEnumerable<TSource> source,
            CancellationToken cancellationToken = default(CancellationToken));
```

**Comment by dombrovsky** [comment]
Thanks for quick reply @eiriktsarpalis. I missed [AsReadOnly ](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.collectionextensions.asreadonly?view=net-7.0#system-collections-generic-collectionextensions-asreadonly-1(system-collections-generic-ilist((-0))))extension method has been added in .net7.

Being able to write `source.ToArray().AsReadOnly()` resolves the problem this proposal tried to address: to not have to write `Array.AsReadOnly(source.ToArray())`, which was not an extension method: https://learn.microsoft.com/en-us/dotnet/api/system.array.asreadonly?view=net-7.0.
Also I must admit `AsReadOnly(IList)` extension method is a better design than proposed `ToReadOnlyCollection(IEnumerable)`/`ToReadOnlyList(IEnumerable)`.
I believe this issue can be closed.

**Comment by dombrovsky** [comment]
Does same motivation as for `System.Linq.Async` apply to `System.Collections.Immutable` library?
Would it make sense to add `IAsyncEnumerable `extensions to `System.Collections.Immutable`?

**Comment by eiriktsarpalis** [comment]
I don't think so, they are separate namespaces.
