### ISSUE TITLE
`double.IsPow2` reports incorrectly for subnormal numbers

### ISSUE THREAD

**Issue by hamarb123** [dotnet/runtime#88023]
### Description

`double.IsPow2` should return `true` for for all doubles which are a power of 2, and false otherwise. It doesn't appear to work correctly for subnormal numbers.

### Reproduction Steps

Execute the following:
```csharp
double.IsPow2(double.Epsilon * 64 * 64 * 64 * 64 * 64 * 64 * 64 * 64 * 16); //not subnormal, = 2^-1022
double.IsPow2(double.Epsilon * 64 * 64 * 64 * 64 * 64 * 64 * 64 * 64 * 8); //is subnormal, = 2^-1023
double.IsPow2(double.Epsilon); //is subnormal, = 2^-1074
```

### Expected behavior

```csharp
double.IsPow2(double.Epsilon * 64 * 64 * 64 * 64 * 64 * 64 * 64 * 64 * 16); //true
double.IsPow2(double.Epsilon * 64 * 64 * 64 * 64 * 64 * 64 * 64 * 64 * 8); //true
double.IsPow2(double.Epsilon); //true
```

### Actual behavior

```csharp
double.IsPow2(double.Epsilon * 64 * 64 * 64 * 64 * 64 * 64 * 64 * 64 * 16); //true
double.IsPow2(double.Epsilon * 64 * 64 * 64 * 64 * 64 * 64 * 64 * 64 * 8); //false
double.IsPow2(double.Epsilon); //false
```

### Configuration

Reproduces on:
.NET 8.0.0-preview.5.23280.8, 7.0.5.
Windows 10 Pro 10.0.19045.3086 x64
No, it probably isn't specific to this configuration.

### Other information

The simplest correct check I can think of for this would be: check the negative bit is not set, check the exponent is not the max exponent (can be combined with previous check), if the exponent is not zero: check the mantissa is 0, if the exponent is zero: check the PopCount is 1.

It seems to also reproduce with `float` and `Half`, I only checked `T.IsPow2(T.Epsilon)`, but these should both return `true` also.

**Comment by danmoseley** [comment]
Good catch @hamarb123
