### ISSUE TITLE
[mono][ios] System.Formats.Tar.Tests are failing with System.ArgumentException

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#88049]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=320749&view=results
Build error leg or test failing: iossimulator-x64 Release AllSubsets_Mono
Pull request: https://github.com/dotnet/runtime/pull/88042

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "System.ArgumentException : The field 'Name' exceeds the maximum allowed length for this format",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=320749
**Result validation: :white_check_mark:** Known issue matched with the provided build.

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[495924](https://dev.azure.com/dnceng-public/public/_build/results?buildId=495924)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=495924&view=ms.vss-test-web.build-test-results-tab&runId=11525258&resultId=193999)||
|[492182](https://dev.azure.com/dnceng-public/public/_build/results?buildId=492182)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=492182&view=ms.vss-test-web.build-test-results-tab&runId=11405750&resultId=197088)|dotnet/runtime#95757|
|[491743](https://dev.azure.com/dnceng-public/public/_build/results?buildId=491743)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=491743&view=ms.vss-test-web.build-test-results-tab&runId=11394302&resultId=188283)|dotnet/runtime#95733|
|[489669](https://dev.azure.com/dnceng-public/public/_build/results?buildId=489669)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=489669&view=ms.vss-test-web.build-test-results-tab&runId=11329496&resultId=188314)||
|[484466](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484466)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484466&view=ms.vss-test-web.build-test-results-tab&runId=11158040&resultId=193999)||
|[478851](https://dev.azure.com/dnceng-public/public/_build/results?buildId=478851)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=478851&view=ms.vss-test-web.build-test-results-tab&runId=10977342&resultId=188283)||
|[478790](https://dev.azure.com/dnceng-public/public/_build/results?buildId=478790)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=478790&view=ms.vss-test-web.build-test-results-tab&runId=10975372&resultId=188283)||
|[478779](https://dev.azure.com/dnceng-public/public/_build/results?buildId=478779)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=478779&view=ms.vss-test-web.build-test-results-tab&runId=10974920&resultId=193968)||
|[477633](https://dev.azure.com/dnceng-public/public/_build/results?buildId=477633)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=477633&view=ms.vss-test-web.build-test-results-tab&runId=10938242&resultId=188283)||
|[477305](https://dev.azure.com/dnceng-public/public/_build/results?buildId=477305)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=477305&view=ms.vss-test-web.build-test-results-tab&runId=10935262&resultId=188314)||
|[476004](https://dev.azure.com/dnceng-public/public/_build/results?buildId=476004)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=476004&view=ms.vss-test-web.build-test-results-tab&runId=10887160&resultId=188314)||
|[473580](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473580)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473580&view=ms.vss-test-web.build-test-results-tab&runId=10809918&resultId=188314)||
|[473434](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473434)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473434&view=ms.vss-test-web.build-test-results-tab&runId=10805344&resultId=188314)||
|[473400](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473400)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473400&view=ms.vss-test-web.build-test-results-tab&runId=10804424&resultId=193999)||
|[472901](https://dev.azure.com/dnceng-public/public/_build/results?buildId=472901)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=472901&view=ms.vss-test-web.build-test-results-tab&runId=10789702&resultId=193968)||
|[472857](https://dev.azure.com/dnceng-public/public/_build/results?buildId=472857)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=472857&view=ms.vss-test-web.build-test-results-tab&runId=10788566&resultId=193999)||
|[471800](https://dev.azure.com/dnceng-public/public/_build/results?buildId=471800)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=471800&view=ms.vss-test-web.build-test-results-tab&runId=10758540&resultId=193999)||
|[471653](https://dev.azure.com/dnceng-public/public/_build/results?buildId=471653)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=471653&view=ms.vss-test-web.build-test-results-tab&runId=10752850&resultId=193968)||
|[471584](https://dev.azure.com/dnceng-public/public/_build/results?buildId=471584)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=471584&view=ms.vss-test-web.build-test-results-tab&runId=10750902&resultId=188283)||
|[471393](https://dev.azure.com/dnceng-public/public/_build/results?buildId=471393)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=471393&view=ms.vss-test-web.build-test-results-tab&runId=10746324&resultId=188283)||
|[470325](https://dev.azure.com/dnceng-public/public/_build/results?buildId=470325)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=470325&view=ms.vss-test-web.build-test-results-tab&runId=10709206&resultId=193968)||
|[468967](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468967)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468967&view=ms.vss-test-web.build-test-results-tab&runId=10670648&resultId=193999)||
|[468844](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468844)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468844&view=ms.vss-test-web.build-test-results-tab&runId=10666372&resultId=188283)||
|[468590](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468590)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468590&view=ms.vss-test-web.build-test-results-tab&runId=10660982&resultId=188314)||
|[468095](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468095)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468095&view=ms.vss-test-web.build-test-results-tab&runId=10646500&resultId=193999)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|3|25|

**Comment by kotlarmilos** [comment]
@carlossanlop It seems that the regression was introduced in https://github.com/dotnet/runtime/pull/87534. The issue appears to be specific to the ios and tvos simulators.

**Comment by steveisok** [comment]
> Hi - The Path length used for V7 should stay as is, it's what the spec indicates and it should be respected.
> 
> The test could be modified so that the temporary path directory is created with a much shorter path. Would that work?

Yes, definitely.

**Comment by carlossanlop** [comment]
@kotlarmilos @steveisok the folder used to store files needs to have a shorter path for the test to work (the failure is expected for this tar format). Can you please change it to a shorter directory for this platform?
