### ISSUE TITLE
Blazor Wasm debugging with a proxy

### ISSUE THREAD

**Issue by MattDowningShell** [dotnet/runtime#88051]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Not sure where/how to get an answer from this.  WASM Hosted debugs successfully on my personal computer.  However working in an enterprise environment that uses a proxy there is a problem.  I created a vanilla Blazor WASM Hosted project using the VS template.  
launchSettings.json has the
"inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
lines

When I F5 for debug I get (I have used square brackets to replace sensitive values):

 Content root path: [MY PATH]\repos\BlazorWasmVanilla\BlazorWasmVanilla\Server\
got exception System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server
 ---> System.Net.Http.HttpRequestException: The proxy tunnel request to proxy 'http://[ENTERPRISE_PROXY].com/' failed with status code '403'."
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, HttpRequestHeaders headers, CancellationToken cancellationToken)
   
The only thing (and I don't know that it is a thing) is that the proxy in my machine's Environment Variable has port 80 specified (the :80 suffix) which I don't see in the error message.

What can resolve this debugging issue?

### Expected Behavior

Create Blazor WASM hosted project using standard template.
Press F5, run in debug mode

### Steps To Reproduce

Within an enterprise using a proxy
Create Blazor WASM hosted project using standard template.
Press F5, run in debug mode

### Exceptions (if any)

info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:7086
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5007
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\...\repos\BlazorWasmVanilla\BlazorWasmVanilla\Server\
got exception System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server
 ---> System.Net.Http.HttpRequestException: The proxy tunnel request to proxy 'http://[...].com/' failed with status code '403'."
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, HttpRequestHeaders headers, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.Run(Uri browserUri, WebSocket ideSocket)
   at Microsoft.WebAssembly.Diagnostics.DebugExtensions.<>c__DisplayClass2_0.<<UseDebugProxy>g__ConnectProxy|5>d.MoveNext()

C:\Users\[...]\repos\BlazorWasmVanilla\BlazorWasmVanilla\Server\bin\Debug\net6.0\BlazorWasmVanilla.Server.exe (process 35192) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.

### .NET Version

Tried with .Net 6 and .Net 7

**Comment by MattDowningShell** [comment]
> This is somewhat uncommon situation and its related to the proxy settings of your environment. I don't think this is a scenario that we support. @thaystg what do you think?

I can understand that.  
But as the error thrown is a 403 authentication error, it is reasonable to ask about configuration of the required connection to allow for an authenticated proxy.  That is not specific to one organisation, it is general to organisations with an authenticated proxy.

launchSettings has "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}", 

And I have been studying the guidance here:
https://learn.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-5.0&tabs=visual-studio#debug-in-the-browser

I have added the "NO_PROXY": "localhost" to the launchSettings.json settings for each profile, which that page doesn't explain very well but there is a good example here:
https://learn.microsoft.com/en-us/answers/questions/488198/urgent-help-with-blazor-wasm-hosted-environment-is

The question is why the framework is still trying to go via the proxy?

**Comment by lewing** [comment]
> > This is somewhat uncommon situation and its related to the proxy settings of your environment. I don't think this is a scenario that we support. @thaystg what do you think?
> 
> I can understand that. But as the error thrown is a 403 authentication error, it is reasonable to ask about configuration of the required connection to allow for an authenticated proxy. That is not specific to one organisation, it is general to organisations with an authenticated proxy.
> 
> launchSettings has "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
> 
> And I have been studying the guidance here: https://learn.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-5.0&tabs=visual-studio#debug-in-the-browser
> 
> I have added the "NO_PROXY": "localhost" to the launchSettings.json settings for each profile, which that page doesn't explain very well but there is a good example here: https://learn.microsoft.com/en-us/answers/questions/488198/urgent-help-with-blazor-wasm-hosted-environment-is
> 
> The question is why the framework is still trying to go via the proxy?

That endpoint does a redirect to a separate service so my guess is that it the launch settings aren't applying there.  @thaystg have any ideas?

**Comment by lewing** [comment]
see also https://github.com/dotnet/runtime/issues/88391

**Comment by thaystg** [comment]
Hey, I was able to reproduce the error.
Can't you configure on windows to don't use proxy for localhost address? This was enough for me.
![image](https://github.com/dotnet/runtime/assets/4503299/045ae553-a134-4d7a-b347-5b2f3636b4a6)

**Comment by MattDowningShell** [comment]
> Hey, I was able to reproduce the error. Can't you configure on windows to don't use proxy for local addresses? This was enough for me. ![image](https://user-images.githubusercontent.com/4503299/253105665-045ae553-a134-4d7a-b347-5b2f3636b4a6.png)

Thanks for the suggestion, but the proxy is not established by that "Use proxy server" panel (it is "off" for me, making that "don't use" box unavailable.

And an app instance of the ASP.Net Core-hosted React template (with its FetchData etc) operates fine.   I can put a break point on FetchData, debug the app, navigate to the page it in the client, and the FetchData break point is hit as expected.
So my machine happily knows not to go via the proxy for localhost.  Blazor Server debugs fine, client chats to localhost server.  Blazor WASM is doing something different & can't.

**Comment by MattDowningShell** [comment]
Really appreciate you working on a fix for this @thaystg !

**Comment by MattDowningShell** [comment]
Hi, I can see https://github.com/dotnet/runtime/pull/88884 is complete.  Do we know when the fix will be included in a release?

**Comment by MattDowningShell** [comment]
> This is fixed on .net8 rc1. Yes, I think this will also work on Blazor United.

Great on the rc1, thanks.

**Comment by MattDowningShell** [comment]
Hi @thaystg just one more question on the Blazor United front - is there a way to check for sure that this is fixed or not an issue for Blazor United?  I'm not sure how to do that, but  as someone who is trying to decide between WASM and BU for migration of a Blazor Server-Hosted project it would be a shame if it was a problem for BU.

**Comment by thaystg** [comment]
Hi, Matt. The same infrastructure is used to debug in both scenarios. It should work. I suggest you to test when RC1 is shipped. But you should not have any issue with that. Thanks.

**Comment by MattDowningShell** [comment]
Ok, thanks for the reply.
