### ISSUE TITLE
Enable Finalizer event in NativeAOT

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#88056]
The finalizer thread in `NativeAOT` is in [managed code](https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/Runtime.Base/src/System/Runtime/__Finalizer.cs#L50-L65) and should fire events similar to the `CoreCLR` native [implementation](https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/finalizerthread.cpp#L91).

The managed code in NativeAOT for this is in the base class library, as opposed to the CoreLib implementation for [exception event](https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/System.Private.CoreLib/src/System/Exception.NativeAot.cs#L139-L152) and require investigation on the `RuntimeImport` support to enable the event.

**Comment by MichalStrehovsky** [comment]
If we need to fire an event at the beginning/end, the implementation being in managed doesn't matter:

https://github.com/dotnet/runtime/blob/6d6fbe065e26c03177c49ace22dd45d5a0ae2551/src/coreclr/nativeaot/Runtime.Base/src/System/Runtime/__Finalizer.cs#L30-L37

RhpWaitForFinalizerRequest and RhpSignalFinalizationComplete are in native and we can call into eventpipe easily from there. We can add a parameter to RhpSignalFinalizationComplete with the number of finalized objects.
