### ISSUE TITLE
[mono][ios] Unknown format in import in System.Security.Cryptography.Tests

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#88050]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=320749&view=results
Build error leg or test failing: iossimulator-x64 Release AllSubsets_Mono
Pull request: https://github.com/dotnet/runtime/pull/88042

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Interop+AppleCrypto+AppleCommonCryptoCryptographicException : Unknown format in import",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=320749
**Result validation: :white_check_mark:** Known issue matched with the provided build.

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[325432](https://dev.azure.com/dnceng-public/public/_build/results?buildId=325432)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=325432&view=ms.vss-test-web.build-test-results-tab&runId=6693096&resultId=193828)||
|[324452](https://dev.azure.com/dnceng-public/public/_build/results?buildId=324452)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=324452&view=ms.vss-test-web.build-test-results-tab&runId=6670824&resultId=193410)|dotnet/runtime#88167|
|[324371](https://dev.azure.com/dnceng-public/public/_build/results?buildId=324371)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=324371&view=ms.vss-test-web.build-test-results-tab&runId=6668604&resultId=193410)||
|[323893](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323893)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323893&view=ms.vss-test-web.build-test-results-tab&runId=6657996&resultId=193373)|dotnet/runtime#88113|
|[323521](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323521)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323521&view=ms.vss-test-web.build-test-results-tab&runId=6648200&resultId=193371)||
|[322934](https://dev.azure.com/dnceng-public/public/_build/results?buildId=322934)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2.Import_BlobHasMoreThanOnePfx_LoadsOnlyOne](https://dev.azure.com/dnceng-public/public/_build/results?buildId=322934&view=ms.vss-test-web.build-test-results-tab&runId=6634534&resultId=168163)||
|[322681](https://dev.azure.com/dnceng-public/public/_build/results?buildId=322681)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=322681&view=ms.vss-test-web.build-test-results-tab&runId=6628760&resultId=193373)|dotnet/runtime#87260|
|[322518](https://dev.azure.com/dnceng-public/public/_build/results?buildId=322518)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=322518&view=ms.vss-test-web.build-test-results-tab&runId=6623814&resultId=193373)|dotnet/runtime#88094|
|[321994](https://dev.azure.com/dnceng-public/public/_build/results?buildId=321994)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=321994&view=ms.vss-test-web.build-test-results-tab&runId=6610714&resultId=193373)||
|[321687](https://dev.azure.com/dnceng-public/public/_build/results?buildId=321687)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=321687&view=ms.vss-test-web.build-test-results-tab&runId=6602456&resultId=193828)||
|[321510](https://dev.azure.com/dnceng-public/public/_build/results?buildId=321510)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=321510&view=ms.vss-test-web.build-test-results-tab&runId=6599782&resultId=193828)||
|[321392](https://dev.azure.com/dnceng-public/public/_build/results?buildId=321392)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=321392&view=ms.vss-test-web.build-test-results-tab&runId=6594820&resultId=193373)||
|[320749](https://dev.azure.com/dnceng-public/public/_build/results?buildId=320749)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2Collection.Import_BlobHasMoreThanOnePfx_LoadsOnlyOne](https://dev.azure.com/dnceng-public/public/_build/results?buildId=320749&view=ms.vss-test-web.build-test-results-tab&runId=6583430&resultId=187768)|dotnet/runtime#88042|
|[320642](https://dev.azure.com/dnceng-public/public/_build/results?buildId=320642)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=320642&view=ms.vss-test-web.build-test-results-tab&runId=6581770&resultId=193803)|dotnet/runtime#88036|
|[320422](https://dev.azure.com/dnceng-public/public/_build/results?buildId=320422)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=320422&view=ms.vss-test-web.build-test-results-tab&runId=6574344&resultId=193803)||
|[320144](https://dev.azure.com/dnceng-public/public/_build/results?buildId=320144)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=320144&view=ms.vss-test-web.build-test-results-tab&runId=6564330&resultId=193803)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|5|16|

**Comment by Jozkee** [comment]
This suggests to me that there could be an iOS specific bug in the `Slice` logic we just added in https://github.com/dotnet/runtime/pull/87514:

https://github.com/Jozkee/runtime/blob/51fda4a55af41cf1913084992d39329680175840/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/X509Certificate.cs#L716-L718

**Comment by akoeplinger** [comment]
@Jozkee that change got backported to 7.0 right?

**Comment by Jozkee** [comment]
@akoeplinger yes, and to 6.0 as well.

**Comment by akoeplinger** [comment]
Could be, I'll try to repro it locally and see if reverting the change fixes it.

**Comment by akoeplinger** [comment]
@Jozkee I confirmed that the test failures don't happen with https://github.com/dotnet/runtime/pull/87514 reverted.

**Comment by akoeplinger** [comment]
Given it only fails `Import_BlobHasMoreThanOnePfx_LoadsOnlyOne` I wonder if this is just using some algorithm that isn't supported by iOS.

**Comment by akoeplinger** [comment]
I added more logging and it fails only when trying to import the `twoPfxes` item, I assume this is getting rejected by the `SecCertificateCreateWithData` API which we only use on iOS/tvOS/MacCatalyst. I think we can disable the test.

**Comment by vcsjones** [comment]
That's a little odd that iOS is failing two PFXes. A quick glance shows it should work.

The PKCS12 iOS PAL uses `ApplePkcs12Reader`.

https://github.com/dotnet/runtime/blob/eba3c11ed72f4cb461d3442c0048a1b7a299c081/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/AppleCertificatePal.Pkcs12.iOS.cs#L12-L17

That uses the base class (`UnixPkcs12Reader`) ParsePkcs12.

https://github.com/dotnet/runtime/blob/eba3c11ed72f4cb461d3442c0048a1b7a299c081/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/ApplePkcs12Reader.iOS.cs#L11-L15

Which specifically says it handles trailing data:

https://github.com/dotnet/runtime/blob/eba3c11ed72f4cb461d3442c0048a1b7a299c081/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/UnixPkcs12Reader.cs#L33-L42

I think we should disable it with an [ActiveIssue] back to this issue so we can better understand why it doesn't appear to be working when, at first glance, it should.
