### ISSUE TITLE
Trying to get DOTNET_gcServer to work

### ISSUE THREAD

**Issue by youn123** [dotnet/runtime#88065]
### Description

I am trying to turn on server GC for msbuild, which significantly reduces msbuild static graph load time for our project builds. Turning it on through msbuild.exe.config increases processor utility and reduces the load time as expected, where as trying to turn it on through the environment variable https://learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector does not.

### Reproduction Steps

Ideally on machine with >32 GB memory:
1. Open Visual Studio developer command prompt
2. Try building a project w/ large number of dependencies (hundreds of projects) with static graph

```
msbuild /t:restore a.csproj
msbuild /graph a.csproj
```

Note the printed static graph load time. Try the same with server GC environment variable:

```
SET DOTNET_gcServer=1
msbuild /graph a.csproj
```

### Expected behavior

Would expect static graph load time to be cut down by at least half, since this is what we see when we turn it on through msbuild.exe.config

### Actual behavior

Static graph load time remain about the same.

### Other information

I am reproducing this behavior on a Microsoft internal project. Can reach out to me on Teams for more details.

**Comment by teo-tsirpanis** [comment]
The `msbuild` command runs MSBuild on .NET Framework. To run MSBuild on modern .NET where the switch would have effect, use `dotnet msbuild` instead.

**Comment by youn123** [comment]
Thank you for the reply, that explains the problem.
