### ISSUE TITLE
hi, quesion about coreclr interpreter

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#88078]
I found coreclr has interpreter implemented at : https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/interpreter.cpp 

what is this used for? what is different from mono/interp?

**Comment by huoyaoyuan** [comment]
https://github.com/dotnet/runtime/blob/e5ddc6c9b7e481d36d6350960868188d7b275ef7/docs/design/coreclr/botr/guide-for-porting.md#L41-L50

It implements some basic feature, and can be used for initial bring up of new platform.

**Comment by srxqds** [comment]
ok, thank you for reply
