### ISSUE TITLE
ServiceController's API got wrong service status

### ISSUE THREAD

**Issue by mingtong** [dotnet/runtime#88105]
My env is Windows 11/.net 6 sdk/VS 2022.
I am trying to start my service if found the service is stopped. 
What I manually to make the service to stop is stop the service and delete a critical file(a DLL file), so then the service cannot be started. 
And then code will be go into the if statement. but after I call start() and WaitForStatus(ServiceControllerStatus.Running), the status got running. and if I change the call to WaitForStatus(ServiceControllerStatus.Stopped), it got stopped.
And the timeout never wait for 5 sec or 30 sec.
This is weird.
Do I call this API in a incorrect way?

To short the description, I just put the code here for you to reproduce.
`
static void Main(string[] args)
        {
            Console.WriteLine("Hello, World!");

            ServiceController serviceController = null;
            try
            {
                serviceController = new("service name");

                serviceController.Refresh();

                // here value is Stopped
                if (serviceController.Status == ServiceControllerStatus.Stopped)
                {
                    serviceController.Start();
                    serviceController.Refresh();
                    serviceController.WaitForStatus(ServiceControllerStatus.Running, TimeSpan.FromSeconds(5));
                    serviceController.Refresh();
                    var s = serviceController.Status;// here value is Running
                }
            }
            catch (Exception ex)
            {
            }
        }
`

**Comment by ViktorHofer** [comment]
@mingtong please elaborate on your question, as as we aren't sure what you're asking for. The sample code looks correct. Aside from that, deleting an assembly might cause unexpected behavior (i.e. it could still be in memory).

**Comment by danmoseley** [comment]
Can you reproduce this with the "sc" roll in Windows?
