### ISSUE TITLE
SYSLIB1045 Use GeneratedRegexAttribute replaces verbatim string with regular string

### ISSUE THREAD

**Issue by pawchen** [dotnet/runtime#88122]
### Description

Similar to #78113, but I found it on different methods: `Regex.Match`, `Regex.Matches`, `Regex.Replace`. Is it a regression or my version too low? I'm targeting .NET 7 with .NET SDK 7.0.304.

![image](https://github.com/dotnet/runtime/assets/159110/41c12c6c-f9cd-4bec-975b-e2f7da652023)

### Reproduction Steps

```C#
Regex.Match(href, @"pageId=(\d+)")
```

### Expected behavior

GeneratedRegex uses the same string style at the original place.

### Actual behavior

Regular string is generated.

### Configuration

VS 17.6.4
project targets .NET 7
.NET SDK 7.0.304

**Comment by stephentoub** [comment]
> Is it a regression or my version too low? I'm targeting .NET 7 with .NET SDK 7.0.304.

This was fixed for .NET 8 in https://github.com/dotnet/runtime/pull/78172.  The change was not backported to .NET 7.
