### ISSUE TITLE
Please add the pattern to the summary of GeneratedRegex partial method

### ISSUE THREAD

**Issue by pawchen** [dotnet/runtime#88121]
### Description

Currently only lengthy explanation is available. I would like to see the original pattern on mouse hover, it is much clearer for me, especially for patterns that contain several capture groups, `(?<...>)` is very easy to spot compared to bullet points.

![image](https://github.com/dotnet/runtime/assets/159110/f0a9d770-f462-487d-abbe-2734807e3293)

### Reproduction Steps

```C#
[GeneratedRegex(@"Origin (?<version>(?<num>\d+[a-z]?|\d+\.\d+(?:.\d)?)(?<sr> SR\d)?) (?<type>.*)")]
private static partial Regex GetOriginVersionPattern();
```

### Expected behavior

The pattern used to generate the partial method should be included in the xml document summary.

### Actual behavior

Only verbose explanations are given.

### Known Workarounds

Not use the GeneratedRegex feature.

### Configuration

VS 17.6.4
project targets .NET 7
.NET SDK 7.0.304

**Comment by stephentoub** [comment]
https://github.com/dotnet/runtime/pull/88175
