### ISSUE TITLE
debugger-agent not able to evaluate / resolve type with provided expression (mono)

### ISSUE THREAD

**Issue by AlexeiNaabal** [dotnet/runtime#88123]
We use VisualStudio as a debug frontend, repo [debugger-lib](https://github.com/mono/debugger-libs) as debug engine.  
While we debugging our mono project, we found that some frame commands return response with false status, 
more specifically, some evaluate request, especially when debugging lambda / linq codes. 
Take below as example:
```c#
struct SomeStruct
{
    //...
}
List<SomeStruct> list = new List<SomeStruct>();
// add content to list
// ...
foreach(var item in list)     // code line where breakpoint set
{
    // access item.{field_or_prop_or_func_member}
}
```
We noticed that when breakpoint hit, and step-in or hover over the "item" in the foreach scope, the VisualStudio sends evaluate request to mono debug engine implementation, trying to evaluate expression "item", or "item.*" when inside the loop, these expression seems very vague, and the mono debug engine is not able to resolve the type of it.  
The typical debug process log is as below:
```
[DebugAdapter] --> C (evaluate-12): {"type":"request","command":"evaluate","arguments":{"context":"hover","expression":"item","frameId":1001,"noSideEffects":true,"timeout":5000},"seq":12}
[DebugAdapter] <--   R (evaluate-12) [68645 ms]: {"type":"response","request_seq":12,"success":false,"command":"evaluate","message":"Evaluate request failed (not available).","body":{"error":{"id":3014,"format":"Evaluate request failed ({_reason}).","variables":{"_reason":"not available"},"showUser":true,"sendTelemetry":false}},"seq":19}

```
We looked into the implementation of mono's debug agent, it seems without namespace, or full type name, it is unlikely to get such expression type resolved.  

Does this a evaluation limitation, or we missed some configuration? (or should we ask in debug-adapter-host / visual studio instead? )

**Comment by thaystg** [comment]
@AlexeiNaabal can you help me to reproduce?
I created a Maui app to try to reproduce and I don't see any failure:
![image](https://github.com/dotnet/runtime/assets/4503299/8c393809-36d3-4249-9e3d-439ab6ba17ea)

I hover over the "item" and was able to see the value of each item.
Can you share more details of your scenario, or share an app that reproduces the issue?

Thanks.

**Comment by thaystg** [comment]
I will close this issue as I don't know how to reproduce. Please reopen it when you can give me more details.
