### ISSUE TITLE
System.Text.Json

### ISSUE THREAD

**Issue by unikgyd** [dotnet/runtime#88143]
### Description

when i try to serialize a generic class with serilizer.serialize() method, it returns "{}". i also tried such an operation with newtownsoft.json, but that was ok. i wonder whether it's a bug or how to solve it.

### Reproduction Steps

use serilizer.serialize() to serialize a generic class

### Expected behavior

normal json

### Actual behavior

only "{}"

**Comment by eiriktsarpalis** [comment]
We would need a reproduction to be able to help you. Does the class only contain fields or internal/private members perhaps?

**Comment by unikgyd** [comment]
> We would need a reproduction to be able to help you. Does the class only contain fields or internal/private members perhaps?

No, they are all public, and I tried to do serialization with newtownsoft.json, it was normal. the sample should be: serializer.serialize(new someClass<string>{
    message="bla bla"
});

**Comment by KeterSCP** [comment]
@unikgyd can you show how does the `someClass` look like?

**Comment by unikgyd** [comment]
public class TestMessageStructure<T>
    {
        [JsonPropertyName("action")]
        public string action = string.Empty;
        [JsonPropertyName("params")]
        public T? @params;
        [JsonPropertyName("echo")]
        public string echo=string.Empty;
    }

**Comment by danmoseley** [comment]
Can you please share a repro that can be compiled on its own with no other dependencies and no code that's not necessary.

**Comment by unikgyd** [comment]
> Can you please share a repro that can be compiled on its own with no other dependencies and no code that's not necessary.

@[unikgyd/Sample](https://github.com/unikgyd/Sample)

**Comment by gregsdennis** [comment]
Field serialization is disabled by default.  You'll need to enable it.

See https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.includefields?view=net-7.0#system-text-json-jsonserializeroptions-includefields

Otherwise change your fields to properties, and it should work.

**Comment by unikgyd** [comment]
thank you
