### ISSUE TITLE
[browser][blazor] Unexpected files in publish folder

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#88142]
- `nuget.config` from the directory of the `.csproj` 
- `dotnet.native.wasm` from runtime pack 
appear in the `bin\Release\net8.0\publish\` output folder after `dotnet publish` with AOT rebuild.

binlog attached

![image](https://github.com/dotnet/runtime/assets/271576/5188d5b2-34ec-483e-a7a3-c103a214e175)

[msbuild.binlog.zip](https://github.com/dotnet/runtime/files/11895822/msbuild.binlog.zip)

cc @maraf @radical

**Comment by radical** [comment]
`nuget.config` is very odd!

**Comment by maraf** [comment]
The `dotnet.native.wasm` comes from runtime pack and should have been replaced (and moved wwwroot) by AOTed version.
