### ISSUE TITLE
R2R Test CpuId_R2R_Avx fails locally

### ISSUE THREAD

**Issue by jasper-d** [dotnet/runtime#88156]
### Description

Running CpuId_R2R_Avx test fails locally (Ryzen 4750U) when testing Vector512 HW acceleration which this model does not have.

### Reproduction Steps

```powershell
git checkout 19d2e90b # commit is not related, it's just an arbirtrary recent revision
.\build.cmd clr+libs -rc Checked -lc Release
.\src\tests\build.cmd Checked test D:\runtime\src\tests\readytorun\HardwareIntrinsics\X86\CpuId_R2R_Avx.csproj
$env:CORE_ROOT="$PWD\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root"
.\artifacts\tests\coreclr\windows.x64.Checked\readytorun\HardwareIntrinsics\X86\CpuId_R2R_Avx\CpuId_R2R_Avx.cmd
```

### Expected behavior

Test does not fail.

### Actual behavior

Test fails with

> System.Runtime.Intrinsics.Vector512.IsHardwareAccelerated returned false but the hardware and runtime returned true
> Expected: 100
> Actual: 0

### Regression?

Probably not. I believe the test was added after I ran tests the last time.

### Known Workarounds

Disabling AVX512 manually before running the test:
```powershell
$env:DOTNET_EnableAVX512F=0
```

### Configuration

.NET 19d2e90b 
Windows 10
AMD Ryzen 7 PRO 4750U with Radeon Graphics
AMD64 Family 23 Model 96 Stepping 1, AuthenticAMD

cpuid:
```
0x00000000 0x00: eax=0x0000000d ebx=0x68747541 ecx=0x444d4163 edx=0x69746e65
0x00000001 0x00: eax=0x00860f01 ebx=0x06100800 ecx=0xfed83203 edx=0x178bfbff
...
0x00000007 0x00: eax=0x00000000 ebx=0x219c01a9 ecx=0x00400004 edx=0x00000000
...
```

### Other information

It passes with the following change to the test, but I'm not sure if that's the right fix.

https://github.com/dotnet/runtime/blob/257c3c1dfd004a7afebeecd5ca538e1ea831f50a/src/tests/readytorun/HardwareIntrinsics/X86/CpuId.cs#L213
```diff
- bool isAvx512HierarchyDisabled = isHierarchyDisabled;
+ bool isAvx512HierarchyDisabled = isHierarchyDisabled || !Avx512F.IsSupported;
```

There is also the special handling of certain Intel models which could possibly be extended.

**Comment by jasper-d** [comment]
Reproduces on more recent Ryzens too, e.g. 

```
AMD Ryzen 7 PRO 6850U
CPU Family: 25
Stepping: 1
Model: 68

CPU:
   0x00000000 0x00: eax=0x00000010 ebx=0x68747541 ecx=0x444d4163 edx=0x69746e65
   0x00000001 0x00: eax=0x00a40f41 ebx=0x04100800 ecx=0x7ef8320b edx=0x178bfbff
   0x00000002 0x00: eax=0x00000000 ebx=0x00000000 ecx=0x00000000 edx=0x00000000
   0x00000003 0x00: eax=0x00000000 ebx=0x00000000 ecx=0x00000000 edx=0x00000000
   0x00000004 0x00: eax=0x00000000 ebx=0x00000000 ecx=0x00000000 edx=0x00000000
   0x00000005 0x00: eax=0x00000040 ebx=0x00000040 ecx=0x00000003 edx=0x00000011
   0x00000006 0x00: eax=0x00000004 ebx=0x00000000 ecx=0x00000001 edx=0x00000000
   0x00000007 0x00: eax=0x00000000 ebx=0x219c97a9 ecx=0x0040069c edx=0x00000010
```

cc: @tannergooding I believe this is your area of expertise.

**Comment by tannergooding** [comment]
Some fixes have gone in around this area. I'm working on getting one of my older boxes running so I can test locally myself, but if someone has the availability it would be beneficial to confirm whether the issue is still surfacing for the latest commit from main.

**Comment by jasper-d** [comment]
It still reproduces for me running 2e7f0dc040 on Ryzen 4750U.
