### ISSUE TITLE
ReadOnlySpan<char> has its char values replaced (or dereferenced) by terminating char "\0" after constructing string for a 2nd time

### ISSUE THREAD

**Issue by milen-denev** [dotnet/runtime#88158]
### Description

I am trying to combine 2 Span<char> and then print them out (by doing `new string(_charSpan)`). After trying to print it out for a second time all the values of the `ReadOnlySpan<char> _charSpan` are equal to `\0` (terminating character). It might be my fault, but I have no way to clarify it.

Another weird behavior is that if I don't add a breakpoint to the debugger, I get a weird looking message like `??Q??Q??Q?????Q??Qd day!` instead of `Hello World! What a great day!`. But if I add a breakpoint right before the `_charSpan = MemoryMarshal.CreateReadOnlySpan<char>(ref MemoryMarshal.GetReference(_tempSpan), _tempSpan.Length);` is called, wait, and then click Continue (F5) it's printed out just fine.

### Reproduction Steps

The code behind

``` csharp

public ref struct StackString
{
    private ReadOnlySpan<char> _charSpan;
    private Span<char> _tempSpan;

    public StackString(ReadOnlySpan<char> charSpan)
    {
        _charSpan = charSpan;
    }

    public void AddString(ReadOnlySpan<char> stringValue)
    {
        unsafe
        {
            _tempSpan = stackalloc char[stringValue.Length + _charSpan.Length];
            _charSpan.CopyTo(_tempSpan);
            var slice = _tempSpan.Slice(_charSpan.Length);
            stringValue.CopyTo(slice);
            _charSpan = MemoryMarshal.CreateReadOnlySpan<char>(ref MemoryMarshal.GetReference(_tempSpan), _tempSpan.Length);
        }
    }

    public override string ToString() => new string(_charSpan);
}

```

``` csharp

public class Program
{
    public static void Main()
    {
        var stackString = new StackString("Hello World!".AsSpan());

        stackString.AddString(" What a great day!".AsSpan());

        Console.WriteLine(stackString.ToString());
        Console.WriteLine(stackString.ToString()); //Here the values in the _charSpan are equal to '\0'

        Console.ReadKey();
    }
}

```

### Expected behavior

I am expecting to print out whatever comes out of `AddString()` as many times as neccessary.

### Actual behavior

After the first time calling `new string(_charSpan))` the chars within the `ReadOnlySpan<char>` are equal (or dereferenced) to `\0`.

### Configuration

- .NET 7.0.8
- Windows 11 Pro 22H2 Build 22621.1928
- x64
- I don't think so
- N/A

**Comment by stephentoub** [comment]
I assume the reason you added `unsafe` into AddString is because you were getting an error CS8353, and adding unsafe allowed it to compile with a warning CS9081?  That was a legitimate error.  You've created your `_tempSpan` via a stackalloc, which means it's using stack memory from the current stack frame.  You're then storing a reference to that memory into _charSpan, which survives the method call; when the method call returns, that stack frame goes away, and the span is now pointing off into memory that will get overwritten the next time something happens on the stack, like another method call.  The CS8353 error was preventing you from doing this:
```
error CS8353	A result of a stackalloc expression of type 'Span<char>' cannot be used in this context because it may be exposed outside of the containing method
```
Adding unsafe downgraded it to a warning, but it's still trying to tell you there's a bug here:
```
warning CS9081: A result of a stackalloc expression of type 'Span<char>' in this context may be exposed outside of the containing method
```

**Comment by milen-denev** [comment]
Ok I did resolve the error / warning by doing the following:

``` csharp
    public void AddString(ReadOnlySpan<char> stringValue)
    {
        Span<char> tempSpan = stackalloc char[stringValue.Length + _charSpan.Length];
        _charSpan.CopyTo(tempSpan);
        var slice = tempSpan.Slice(_charSpan.Length);
        stringValue.CopyTo(slice);
        _charSpan = MemoryMarshal.CreateReadOnlySpan<char>(ref MemoryMarshal.GetReference(tempSpan), tempSpan.Length);       
    }
```
I am still having trouble though. The string let's say gets corrupted after anything else happens.

You are saying "survives the method call; when the method call returns, that stack frame goes away, and the span is now pointing off into memory that will get overwritten the next time something happens on the stack.". Does this mean that I cannot store data the way I am trying too?

(I am trying to create some sort of stack allocated `string `/ `char[]`, manipulate it and then things are done allocate them to the heap via `new string()`)

**Comment by stephentoub** [comment]
> Ok I did resolve the error / warning by doing the following

The error went away but the core problem still persists: you're stackalloc'ing tempSpan and then using MemoryMarshal.CreateReadOnlySpan to store the same stack-based span to be used after the method. The compiler can't see it, but it's just as unsafe.

You can't stackalloc and store the result for use after the method. That is broken regardless of whether the compiler errors or not. MemoryMarshal is itself "unsafe".

**Comment by milen-denev** [comment]
Ok thank you very much for the help. Always finding something new to learn.
