### ISSUE TITLE
DOTNET_DiagnosticPorts doesn't work for the runtime with listen mode

### ISSUE THREAD

**Issue by tri-bao** [dotnet/runtime#88177]
dotnet core runtime 6.0.19, in linux platform
```
DOTNET_DiagnosticPorts=/home/baoho/main-app.socket,listen,nosuspend dotnet MyApp.dll
```
But no socket file was created. I also tried `listen,suspend` but the app didn't suspend. Looks like the runtime completely ignores `listen` mode.
It seems to me the runtime only works with mode `connect` because when I tried `connect,suspend` the app startup paused.

What I wanted to achieve is to have my app create a diagnostic unix domain socket in a shared folder (mounted from a kubernetes volume) and listen to it. So that, whenever we want to diagnostic the app, we will spin up a different container and use a dotnet tool to connect to that socket file.

I follow this document [https://learn.microsoft.com/en-us/dotnet/core/diagnostics/diagnostic-port](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/diagnostic-port) It says
> This article applies to: ✔️ .NET Core 3.1 and later versions

I understand that it also applies to .NET core 6

> In each communication channel between a diagnostic tool and the .NET runtime, one side needs to be the listener and wait for the other side to connect. The runtime can be configured to act in either role for each port

I understand that I can have the runtime (my app site) create the socket file and listen to incoming connection from any dotnet tool.

However, no matter what I tried, no socket file was created when I run my application.
This issue looks similar to the issue [#66263](https://github.com/dotnet/runtime/issues/66263) but I'm not sure what is the conclusion of it

**Comment by hoyosjs** [comment]
This is https://github.com/dotnet/diagnostics/issues/3809 - the docs incorrectly claim the runtime supports more than one listen port.
