### ISSUE TITLE
[API Proposal]: Make AddBinaryFormattedResource obsolete

### ISSUE THREAD

**Issue by gewarren** [dotnet/runtime#88217]
### Background and motivation

Most of the remaining legacy serialization APIs were obsoleted in https://github.com/dotnet/runtime/pull/84383. I'm proposing that we obsolete the [System.Resources.Extensions.PreserializedResourceWriter.AddBinaryFormattedResource method](https://github.com/dotnet/runtime/blob/3e87528325b09f884b0a09a8c4ef79393abfd0db/src/libraries/System.Resources.Extensions/src/System/Resources/Extensions/PreserializedResourceWriter.cs#L155) as well. I ran this by Levi and some others in an email:

From: Rainer Sigwald
Sent: Monday, June 26, 2023 7:09 AM
Subject: RE: AddBinaryFormattedResource method
 
Yeah, I’d be totally fine with obsoleting it but we will need it to keep working indefinitely. It’ll be an important scenario for a long time to support targeting .NET Framework apps from `dotnet build`. 
 
From: Eric St. John 
Sent: Friday, June 23, 2023 5:17 PM
Subject: RE: AddBinaryFormattedResource method

As you mention, it doesn’t itself use BinaryFormatter.  It’s just writing resource data to a .resources format that will be treated as binary formatted data when that .resources file is eventually loaded.

We could obsolete it, the only person using it right now is MSBuild and they’ll just suppress that obsoletion because they need to continue to support writing those resources – warnings need to go upstream where users choose this format.
 
Adding the obsoletion here would discourage others from using it, imagining it as some kind of “safe” backdoor to getting binary-formatted resources loaded.  I’m OK with us making it obsolete – but we can’t remove it.

### API Proposal

```csharp
[Obsolete ...]
public void AddBinaryFormattedResource(string name, byte[] value, string? typeName = null)
```

### API Usage

N/A

**Comment by steveharter** [comment]
@rainersigwald is this OK to do in v8 - does `dotnet build` need to be updated to adjust to any compiler warning\error?

**Comment by terrajobst** [comment]
* Makes sense as proposed

```C#
namespace System.Resources.Extensions;

public partial class PreserializedResourceWriter
{
     [Obsolete(...)]
     public void AddBinaryFormattedResource(string name, byte[] value, string? typeName = null);
}
```
