### ISSUE TITLE
Test failure System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#88224]
**Failed in:** [runtime-coreclr libraries-jitstress 20230629.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=324820&view=ms.vss-test-web.build-test-results-tab&runId=6676136&resultId=100332&paneView=debug)

**Failed tests:**
```
net8.0-windows-Release-arm64-CoreCLR_checked-jitstress1_tiered-Windows.11.Arm64.Open
    - System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages
net8.0-windows-Release-arm64-CoreCLR_checked-tailcallstress-Windows.11.Arm64.Open
    - System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages
net8.0-windows-Release-arm64-CoreCLR_checked-jitstress2_tiered-Windows.11.Arm64.Open
    - System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages
net8.0-windows-Release-arm64-CoreCLR_checked-no_tiered_compilation-Windows.11.Arm64.Open
    - System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages
net8.0-windows-Release-arm64-CoreCLR_checked-zapdisable-Windows.11.Arm64.Open
    - System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages
net8.0-windows-Release-arm64-CoreCLR_checked-jitstress2-Windows.11.Arm64.Open
    - System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages
net8.0-windows-Release-arm64-CoreCLR_checked-jitstress1-Windows.11.Arm64.Open
    - System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages
net8.0-windows-Release-arm64-CoreCLR_checked-jitminopts-Windows.11.Arm64.Open
    - System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages
```

**Error message:**
```
Assert.Equal() Failure
                                 ↓ (pos 42)
Expected: ···c9-a094-de53168c96d0
Actual:   ···c9-a094-de53168c96d0\0
                                 ↑ (pos 42)
```

**Stack trace:**
```
   at System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages() in /_/src/libraries/System.Diagnostics.EventLog/tests/EventLogMessagesTests.cs:line 80
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
```

```json
{
  "ErrorMessage": "CanReadAndWriteMessages",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": true
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=324820
**Error message validated:** `CanReadAndWriteMessages`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 7/4/2023 1:24:41 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[356430](https://dev.azure.com/dnceng-public/public/_build/results?buildId=356430)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=356430&view=ms.vss-test-web.build-test-results-tab&runId=7498566&resultId=106505)||
|[354230](https://dev.azure.com/dnceng-public/public/_build/results?buildId=354230)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=354230&view=ms.vss-test-web.build-test-results-tab&runId=7445156&resultId=118640)||
|[353408](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353408)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353408&view=ms.vss-test-web.build-test-results-tab&runId=7428134&resultId=116896)||
|[342975](https://dev.azure.com/dnceng-public/public/_build/results?buildId=342975)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=342975&view=ms.vss-test-web.build-test-results-tab&runId=7166320&resultId=112593)||
|[342104](https://dev.azure.com/dnceng-public/public/_build/results?buildId=342104)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=342104&view=ms.vss-test-web.build-test-results-tab&runId=7143512&resultId=113899)||
|[341300](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341300)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341300&view=ms.vss-test-web.build-test-results-tab&runId=7140176&resultId=122576)|dotnet/runtime#88854|
|[339891](https://dev.azure.com/dnceng-public/public/_build/results?buildId=339891)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=339891&view=ms.vss-test-web.build-test-results-tab&runId=7087114&resultId=111835)||
|[339787](https://dev.azure.com/dnceng-public/public/_build/results?buildId=339787)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=339787&view=ms.vss-test-web.build-test-results-tab&runId=7084502&resultId=114121)|dotnet/runtime#88854|
|[338978](https://dev.azure.com/dnceng-public/public/_build/results?buildId=338978)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=338978&view=ms.vss-test-web.build-test-results-tab&runId=7059558&resultId=104392)||
|[338961](https://dev.azure.com/dnceng-public/public/_build/results?buildId=338961)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=338961&view=ms.vss-test-web.build-test-results-tab&runId=7058738&resultId=119679)||
|[337931](https://dev.azure.com/dnceng-public/public/_build/results?buildId=337931)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=337931&view=ms.vss-test-web.build-test-results-tab&runId=7028432&resultId=115807)||
|[336908](https://dev.azure.com/dnceng-public/public/_build/results?buildId=336908)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=336908&view=ms.vss-test-web.build-test-results-tab&runId=7003368&resultId=110247)||
|[336356](https://dev.azure.com/dnceng-public/public/_build/results?buildId=336356)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=336356&view=ms.vss-test-web.build-test-results-tab&runId=6987038&resultId=113362)||
|[334957](https://dev.azure.com/dnceng-public/public/_build/results?buildId=334957)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=334957&view=ms.vss-test-web.build-test-results-tab&runId=6946190&resultId=117269)||
|[334721](https://dev.azure.com/dnceng-public/public/_build/results?buildId=334721)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=334721&view=ms.vss-test-web.build-test-results-tab&runId=6938778&resultId=108971)||
|[334256](https://dev.azure.com/dnceng-public/public/_build/results?buildId=334256)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=334256&view=ms.vss-test-web.build-test-results-tab&runId=6925248&resultId=116349)||
|[334061](https://dev.azure.com/dnceng-public/public/_build/results?buildId=334061)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=334061&view=ms.vss-test-web.build-test-results-tab&runId=6919722&resultId=122545)||
|[331369](https://dev.azure.com/dnceng-public/public/_build/results?buildId=331369)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=331369&view=ms.vss-test-web.build-test-results-tab&runId=6845132&resultId=113972)||
|[331172](https://dev.azure.com/dnceng-public/public/_build/results?buildId=331172)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=331172&view=ms.vss-test-web.build-test-results-tab&runId=6839282&resultId=115405)||
|[330937](https://dev.azure.com/dnceng-public/public/_build/results?buildId=330937)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=330937&view=ms.vss-test-web.build-test-results-tab&runId=6834372&resultId=115706)||
|[330588](https://dev.azure.com/dnceng-public/public/_build/results?buildId=330588)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=330588&view=ms.vss-test-web.build-test-results-tab&runId=6825908&resultId=124510)||
|[330527](https://dev.azure.com/dnceng-public/public/_build/results?buildId=330527)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=330527&view=ms.vss-test-web.build-test-results-tab&runId=6824202&resultId=126625)||
|[330480](https://dev.azure.com/dnceng-public/public/_build/results?buildId=330480)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=330480&view=ms.vss-test-web.build-test-results-tab&runId=6822938&resultId=102636)||
|[330387](https://dev.azure.com/dnceng-public/public/_build/results?buildId=330387)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=330387&view=ms.vss-test-web.build-test-results-tab&runId=6820494&resultId=118445)||
|[329962](https://dev.azure.com/dnceng-public/public/_build/results?buildId=329962)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=329962&view=ms.vss-test-web.build-test-results-tab&runId=6809118&resultId=116988)||
|[329717](https://dev.azure.com/dnceng-public/public/_build/results?buildId=329717)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=329717&view=ms.vss-test-web.build-test-results-tab&runId=6801914&resultId=108177)|dotnet/runtime#88345|
|[329704](https://dev.azure.com/dnceng-public/public/_build/results?buildId=329704)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=329704&view=ms.vss-test-web.build-test-results-tab&runId=6801664&resultId=111701)|dotnet/runtime#84122|
|[329472](https://dev.azure.com/dnceng-public/public/_build/results?buildId=329472)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=329472&view=ms.vss-test-web.build-test-results-tab&runId=6796044&resultId=121694)||
|[329439](https://dev.azure.com/dnceng-public/public/_build/results?buildId=329439)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=329439&view=ms.vss-test-web.build-test-results-tab&runId=6795426&resultId=110062)||
|[329361](https://dev.azure.com/dnceng-public/public/_build/results?buildId=329361)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=329361&view=ms.vss-test-web.build-test-results-tab&runId=6794004&resultId=125799)|dotnet/runtime#88345|
|[329210](https://dev.azure.com/dnceng-public/public/_build/results?buildId=329210)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=329210&view=ms.vss-test-web.build-test-results-tab&runId=6790692&resultId=125796)||
|[329047](https://dev.azure.com/dnceng-public/public/_build/results?buildId=329047)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=329047&view=ms.vss-test-web.build-test-results-tab&runId=6786584&resultId=105194)|dotnet/runtime#88380|
|[328828](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328828)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328828&view=ms.vss-test-web.build-test-results-tab&runId=6781820&resultId=124683)|dotnet/runtime#88322|
|[328822](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328822)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328822&view=ms.vss-test-web.build-test-results-tab&runId=6781600&resultId=120896)||
|[328776](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328776)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328776&view=ms.vss-test-web.build-test-results-tab&runId=6780596&resultId=106740)||
|[328678](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328678)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328678&view=ms.vss-test-web.build-test-results-tab&runId=6777954&resultId=121186)|dotnet/runtime#88345|
|[328529](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328529)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328529&view=ms.vss-test-web.build-test-results-tab&runId=6775008&resultId=120693)||
|[328483](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328483)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328483&view=ms.vss-test-web.build-test-results-tab&runId=6773916&resultId=115543)|dotnet/runtime#88354|
|[328443](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328443)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328443&view=ms.vss-test-web.build-test-results-tab&runId=6772896&resultId=110428)|dotnet/runtime#88322|
|[328406](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328406)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328406&view=ms.vss-test-web.build-test-results-tab&runId=6772118&resultId=125993)|dotnet/runtime#88345|
|[328385](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328385)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328385&view=ms.vss-test-web.build-test-results-tab&runId=6771704&resultId=125812)|dotnet/runtime#88342|
|[328094](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328094)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328094&view=ms.vss-test-web.build-test-results-tab&runId=6764392&resultId=122993)|dotnet/runtime#88322|
|[327993](https://dev.azure.com/dnceng-public/public/_build/results?buildId=327993)|dotnet/runtime|[System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=327993&view=ms.vss-test-web.build-test-results-tab&runId=6761948&resultId=118952)|dotnet/runtime#88184|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|3|43|

**Comment by BruceForstall** [comment]
I'm not able to repro this locally. Maybe we should wait until another run or two verifies that it continues to fail.

**Comment by BruceForstall** [comment]
Well, a separate PR run still failed with these, so these failures look repeatable.

**Comment by BruceForstall** [comment]
@stephentoub Is #87906 possibly related? It's the only recent change I found with "Event" in the title.
@noahfalk @davmason Any idea what might have changed here?

**Comment by stephentoub** [comment]
> Is https://github.com/dotnet/runtime/pull/87906 possibly related?

Anything's possible, but this seems very unlikely.  It just replaced one singleton instance with another and shouldn't be anywhere near to code that impacts whether something has an extra null terminator.

**Comment by davmason** [comment]
I am not aware of any changes here. I merged #86850 last night, but it looks like it was merged after this started failing so wouldn't be the issue. Other than that I don't know of any recent changes

**Comment by jakobbotsch** [comment]
This fails consistently in runtime-extra-platforms too: https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E7+definition%3Aruntime-extra-platforms+name%3ASystem.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages

So doesn't seem like a jitstress issue. Given that it fails in jitminopts, it's also very unlikely to be a JIT issue., so will move this out.

**Comment by jakobbotsch** [comment]
The failure appears to only be on Windows 11. I've disabled it there in #88472.
