### ISSUE TITLE
Missing CI test coverage for Vector512

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#88233]
The following test passed CI without any errors in #88166:
```c#
[Fact]
[MethodImpl(MethodImplOptions.AggressiveOptimization)]
public static void SanityCheckAO()
{
    if (Vector512.IsHardwareAccelerated && Avx512BW.IsSupported)
        throw new Exception("Yay?");
}
```

Dumping the CpuId, it looks like all processors in CI that report `Avx512BW.IsSupported == true` also report `isGenuineIntel=True familyID=6 extendedModelID=5 model=5`.

https://github.com/dotnet/runtime/blob/ddf47f088cbb52193230f3e1a131c6a71f80bd44/src/coreclr/vm/codeman.cpp#L1882-L1892

With #86655, those no longer report `Vector512.IsHardwareAccelerated`, therefore we have no CI coverage of such code paths?

**Comment by tannergooding** [comment]
We should add an outerloop leg to the AVX-512 run that sets `DOTNET_PreferredVectorBitWidth=512`

We are getting some stress coverage still, just randomly based on `compStressCompile(STRESS_GENERIC_VARN, 20)` and noting this only impacts `Vector512.IsHardwareAccelerated` lightup. It doesn't impact direct usage or validation of the `System.Runtime.Intrinsics.X86` code paths.
