### ISSUE TITLE
[API Proposal]: Allow DoesConsoleSupportAnsi to be overridden on Windows by environment variable

### ISSUE THREAD

**Issue by hach-que** [dotnet/runtime#88236]
### Background and motivation

At the moment, [DoesConsoleSupportAnsi](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Logging.Console/src/ConsoleLoggerProvider.cs#L69) returns true in the following scenarios:

- If the platform is not Windows, or
- If the platform is Windows, but the kernel indicates that the process is connected to a terminal

However in my case is that I have log output that I *specifically know* will reach something that can parse ANSI color codes - in this case it's a CI server which is running a command with standard output redirected to a file, and then parsing the ANSI colors in the resulting log file.

The problem is that DoesConsoleSupportAnsi causes the IConsole implementation to be `AnsiParsingLogConsole`, which strips out ANSI color codes regardless - you can't even use `ColorBehavior = LoggerColorBehavior.Enabled` of the formatter to bypass this. `IConsole` also doesn't come from dependency injection, so I can't override it that way either.

### API Proposal

It would be ideal if I could set, e.g. `DOTNET_FORCE_COLOR=true` or something of that nature as an environment variable, which would force `AnsiLogConsole` to be used even on Windows.

### API Usage

```
set DOTNET_FORCE_COLOR=true
dotnet run ...
```

**Comment by hach-que** [comment]
It looks like there's already an `DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION` environment variable which is meant to turn ANSI color codes on, but it's not currently respected by `DoesConsoleSupportAnsi`: https://github.com/dotnet/runtime/blob/main/src/libraries/Common/src/System/Console/ConsoleUtils.cs#L38-L42

**Comment by adamsitnik** [comment]
> It looks like there's already an `DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION` environment variable which is meant to turn ANSI color codes on, but it's not currently respected by `DoesConsoleSupportAnsi`: 

If that is the case, then we should most likely update `DoesConsoleSupportAnsi` to respect this env var.

@hach-que would you like to send a PR with a fix?

**Comment by hach-que** [comment]
@adamsitnik Sent through a quick fix (I think). As mentioned, I just did it from the GitHub web interface since I don't have a development environment up and running for building code in the `runtime` repository (and given the nature of it I'm assuming it's more complicated than just opening it up in Visual Studio).

**Comment by adamsitnik** [comment]
@hach-que sounds good to me, thank you!

**Comment by tarekgh** [comment]
@adamsitnik does `DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION` documented somewhere? or we need to document it?
