### ISSUE TITLE
can't dotnet run x86 at x64 on net8 

### ISSUE THREAD

**Issue by NCLnclNCL** [dotnet/runtime#88283]
### Description

I use dotnet run -a x86
however it returns error, if i use dotnet build -a x86 it can build successfully
if i target to net7 or net6, it tool cannot run with same errors

### Reproduction Steps

dotnet run -a x86 and target net 8 preview5

### Expected behavior

run successfully

### Actual behavior

return errors Failed to load the dll from [D:\dotnet-sdk-8.0.100-preview.5.23303.2-win-x64\host\fxr\8.0.0-preview.5.23280.8\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from D:\dotnet-sdk-8.0.100-preview.5.23303.2-win-x64\host\fxr\8.0.0-preview.5.23280.8\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306

### Configuration

net8 preview5
window 10 2009
x64

**Comment by hez2010** [comment]
It seems that you are trying to run your program with x86 architecture while you only have x64 dotnet runtime installed.

**Comment by elinor-fung** [comment]
@NCLnclNCL as @hez2010 pointed out, you'll need the x86 version of .NET installed. Can you install the x86 version of .NET and try again?

We do have an open issue around trying to detect the architecture mismatch case for better error messaging:
- https://github.com/dotnet/runtime/issues/3745

**Comment by vitek-karas** [comment]
In this case it seems to be exaggerated by the fact that the SDK is running from a private install, so there's very likely `DOTNET_ROOT` set to point to the x64 install. To make this work in a private install, you would need to install x86 runtime into another location and set `DOTNET_ROOT_X86` to point to that location. Then `dotnet run -a x86` should work even when running it from the x64 SDK.

Note that if you were using globally installed SDK/Runtime there's no need to set any env. variable as the location of the runtime for each architecture is written in registry and the app will find it from there. That's probably why it works just fine for .NET 6/7 as you're likely using the global install in that case.

**Comment by agocke** [comment]
Closed as dup of https://github.com/dotnet/runtime/issues/3745
