### ISSUE TITLE
I'm trying out how the `QuicListener` API to see how suitable it is, but so far I've been unable to even get it past the hello world stage.

### ISSUE THREAD

**Issue by ayende** [dotnet/runtime#88298]
I'm trying out how the `QuicListener` API to see how suitable it is, but so far I've been unable to even get it past the hello world stage.

Here is my code:

```c#
using System.Security.Cryptography.X509Certificates;
using System.Security.Cryptography;
using System.Net.Quic;
using System.Net;
using System.Text;
using System.Net.Security;

var cert = CreateSelfSignedCertificate();

var listener = await QuicListener.ListenAsync(new QuicListenerOptions
{
    ApplicationProtocols = new List<SslApplicationProtocol>
    {
        new SslApplicationProtocol("test")
    },
    ListenEndPoint = IPEndPoint.Parse("127.0.0.1:19999"),
    ConnectionOptionsCallback = (con, hello, token) => ValueTask.FromResult(new QuicServerConnectionOptions
    {
        DefaultStreamErrorCode = 123456,
        DefaultCloseErrorCode = 654321,
        ServerAuthenticationOptions = new SslServerAuthenticationOptions
        {
            ServerCertificate = cert,
            ClientCertificateRequired = false,
            RemoteCertificateValidationCallback = (sender, chain, certificate, errors) => true
        },
    }),
});


_ = Task.Run(async () =>
{
    var con = await listener.AcceptConnectionAsync();
    var stream = await con.AcceptInboundStreamAsync();
    var reader = new StreamReader(stream);
    while (true)
    {
        var data = await reader.ReadLineAsync();
        Console.WriteLine(data);
        await stream.WriteAsync(Encoding.UTF8.GetBytes("World"));
    }
});

try
{

    var value = await QuicConnection.ConnectAsync(new QuicClientConnectionOptions
    {
        RemoteEndPoint = IPEndPoint.Parse("127.0.0.1:19999"),
        DefaultCloseErrorCode = 789,
        DefaultStreamErrorCode = 987,
        ClientAuthenticationOptions = new SslClientAuthenticationOptions
        {
            ClientCertificates = new X509CertificateCollection { cert },
            ApplicationProtocols = new List<SslApplicationProtocol>
        {
            new SslApplicationProtocol("test")
        },
            TargetHost = "localhost",
            RemoteCertificateValidationCallback = (sender, chain, certificate, errors) => true
        }
    });
    var st = await value.OpenOutboundStreamAsync(QuicStreamType.Bidirectional);
    await st.WriteAsync(Encoding.UTF8.GetBytes("hello"));
    using var reader = new StreamReader(st);
    Console.WriteLine(await reader.ReadLineAsync());
}
catch (Exception e)
{
    Console.WriteLine(e);
}


X509Certificate2 CreateSelfSignedCertificate()
{
    var ecdsa = ECDsa.Create();
    var certificateRequest = new CertificateRequest("CN=localhost", ecdsa, HashAlgorithmName.SHA256);
    certificateRequest.CertificateExtensions.Add(
        new X509BasicConstraintsExtension(
            certificateAuthority: false,
            hasPathLengthConstraint: false,
            pathLengthConstraint: 0,
            critical: true
        )
    );
    certificateRequest.CertificateExtensions.Add(
        new X509KeyUsageExtension(
            keyUsages:
                X509KeyUsageFlags.DigitalSignature | X509KeyUsageFlags.KeyEncipherment |
                X509KeyUsageFlags.CrlSign | X509KeyUsageFlags.KeyCertSign,
            critical: false
        )
    );
    certificateRequest.CertificateExtensions.Add(
        new X509EnhancedKeyUsageExtension(
            new OidCollection {
                    new Oid("1.3.6.1.5.5.7.3.2"), // TLS Client auth
                    new Oid("1.3.6.1.5.5.7.3.1")  // TLS Server auth
            },
            false));

    certificateRequest.CertificateExtensions.Add(
        new X509SubjectKeyIdentifierExtension(
            key: certificateRequest.PublicKey,
            critical: false
        )
    );

    var sanBuilder = new SubjectAlternativeNameBuilder();
    sanBuilder.AddDnsName("localhost");
    certificateRequest.CertificateExtensions.Add(sanBuilder.Build());

    return certificateRequest.CreateSelfSigned(DateTimeOffset.Now.AddDays(-1), DateTimeOffset.Now.AddYears(5));
}
```

When I'm trying to run that, I'm getting this error:

```
System.Security.Authentication.AuthenticationException: Authentication failed. ConfigurationLoadCredential failed: QUIC_STATUS_CERT_NO_CERT
   at System.Net.Quic.ThrowHelper.ThrowIfMsQuicError(Int32 status, String message)
   at System.Net.Quic.MsQuicConfiguration.Create(QuicConnectionOptions options, QUIC_CREDENTIAL_FLAGS flags, X509Certificate certificate, X509Certificate[] intermediates, List`1 alpnProtocols, CipherSuitesPolicy cipherSuitesPolicy, EncryptionPolicy encryptionPolicy)
```

I'm passing the certificate, obviously, but I believe that this is related to (unstated) requirements in the certificate.
I found that this is likely the command to generate an appropriate certificate:

https://github.com/microsoft/msquic/blob/3e89ddcf94210edd2fe21b7c15310922de55142f/src/tools/sample/sample.c#L26

Using that (with):

```c#
X509Store certStore = new X509Store(StoreName.My, StoreLocation.CurrentUser);
certStore.Open(OpenFlags.ReadOnly);
X509Certificate2Collection certCollection = certStore.Certificates.Find(
                           X509FindType.FindByThumbprint, "8B9F76CD64DBB6FFBD76C57FCC208677213A427E",
                           false);

var cert = certCollection[0];
```

Gives a different error:

```
System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'UserCanceled'.
   at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data)
   at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent)
   at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
```

At this point, I'm not sure what is going on and looking at the Quic tests, it looks like I'm doing the right thing.

_Originally posted by @ayende in https://github.com/dotnet/runtime/discussions/82762_

**Comment by ManickaP** [comment]
You need to also specify ALPN for server connection options, e.g:
```c#
ConnectionOptionsCallback = (con, hello, token) => ValueTask.FromResult(new QuicServerConnectionOptions
{
    DefaultStreamErrorCode = 123456,
    DefaultCloseErrorCode = 654321,
    ServerAuthenticationOptions = new SslServerAuthenticationOptions
    {
        // This
        ApplicationProtocols = new List<SslApplicationProtocol>
        {
            new SslApplicationProtocol("test")
        },
        ServerCertificate = cert,
        ClientCertificateRequired = false,
        RemoteCertificateValidationCallback = (sender, chain, certificate, errors) => true
    },
})
```

You get "UserCanceled" error because your callback told QUIC that it doesn't accept `test` ALPN as it didn't specify any. We could consider adding the same list from Listener as default in case user doesn't provide anything, thoughts on this @wfurt?

Few more things with your sample:
- if you're doing `ReadLine` you also need to send the new line, otherwise you're stuck on that line
- you need to properly dispose all the QUIC objects, they all implement `DisposeAsync`: listener, connections and streams.

Hope this helps.

**Comment by ayende** [comment]
I'm afraid that this doesn't really help.
My full code is [here](https://gist.github.com/ayende/9d7bca0ca165206d54a345de1872b980), with your recommend changes.
I'm now getting a different error: 

```
System.Security.Authentication.AuthenticationException: Authentication failed. ConfigurationLoadCredential failed: QUIC_STATUS_CERT_NO_CERT
```

However, if I remove the `ClientCertificates = new X509CertificateCollection { cert },` line from the `QuicClientConnectionOptions`, I'll get:

```
System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'UserCanceled'.
```

No idea what is going on, since the code goes into MsQuic and native code.

**Comment by ManickaP** [comment]
First of all, you don't need client cert unless your app needs it, cert is mandatory only for server.
And you're test program runs for me and prints (I'm on Linux, works on .NET 8 preview as well as .NET 7):
```
Called!
hello
```
Then it gets stuck on the `ReadLine` of "World".

So what is your environment: dotnet version, OS, if on Linux which version of libmsquic you have?

**Comment by ayende** [comment]
My intention is to use client cert for authentication, so I would like to have it working.
At any rate, that doesn't work on either option.

I'm running this on `Microsoft Windows NT 10.0.22621.0` using `dotnet 7.0.305`

With a client certificate:

```
System.Security.Authentication.AuthenticationException: Authentication failed. ConfigurationLoadCredential failed: QUIC_STATUS_CERT_NO_CERT
   at System.Net.Quic.ThrowHelper.ThrowIfMsQuicError(Int32 status, String message)
   at System.Net.Quic.MsQuicConfiguration.Create(QuicConnectionOptions options, QUIC_CREDENTIAL_FLAGS flags, X509Certificate certificate, X509Certificate[] intermediates, List`1 alpnProtocols, CipherSuitesPolicy cipherSuitesPolicy, EncryptionPolicy encryptionPolicy)
   at System.Net.Quic.MsQuicConfiguration.Create(QuicClientConnectionOptions options)
   at System.Net.Quic.QuicConnection.FinishConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken)
   at System.Net.Quic.QuicConnection.ConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken)
   at System.Net.Quic.QuicConnection.ConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\Users\Oren\source\repos\RightStuff\RightStuff\Program.cs:line 70

```

Without:

```
System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'UserCanceled'.
   at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data)
   at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent)
   at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
--- End of stack trace from previous location ---
   at System.Net.Quic.ValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Quic.QuicConnection.FinishConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken)
   at System.Net.Quic.QuicConnection.ConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken)
   at System.Net.Quic.QuicConnection.ConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\Users\Oren\source\repos\RightStuff\RightStuff\Program.cs:line 70
```

**Comment by ManickaP** [comment]
I can repro it on Windows, looks like the SChannel backend doesn't like the server cert. @wfurt, @rzikm any ideas?

**Comment by wfurt** [comment]
It may be worth of trying the cert with `SslStream`. If there is something unusual with the cert I would expect to bubble up as well. And yes the `user cancelled` is misleading IMHO, that generally means handshake failed.  

Last part may be ephemeral keys on Windows. It may be worth of trying
https://github.com/dotnet/runtime/blob/0a47ab064b53fa6dcd5a749be6563c3de1a04d7c/src/libraries/System.Net.Security/tests/FunctionalTests/TestHelper.cs#L211-L216

We updated `SslStream` to provide some more meaningful error But that probably does not cover `Quic`

**Comment by rzikm** [comment]
I believe client certs are not supported on Windows 10 SChannel for TLS 1.3 (what QUIC uses).

In order to support that, you would have to use MsQuic build which uses OpenSSL backend (there is such build even for Windows, and it might become the recommended option for the future by MsQuic folks).

**Comment by rzikm** [comment]
See also

https://github.com/dotnet/runtime/blob/2deebf04c5a238682163c08aed4e2c57aa7f3efd/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs#L193-L199

**Comment by rzikm** [comment]
I tried and it seems that there is something wrong with the certificate, when I use the same cert we use in unit tests for the code, it works fine (on Win 11), but the repro code does not work even if I add the exportable flag as wfurt suggested.

**Comment by ayende** [comment]
I tried using:

```
var clientCert = new X509Certificate2(cert.Export(X509ContentType.Pfx), (string?)null, X509KeyStorageFlags.Exportable);
```

And this gives me:
```
System.Net.Quic.QuicException: An internal error has occurred. ConfigurationLoadCredential failed: Unknown (0x80090304)
   at System.Net.Quic.ThrowHelper.ThrowIfMsQuicError(Int32 status, String message)
   at System.Net.Quic.MsQuicConfiguration.Create(QuicConnectionOptions options, QUIC_CREDENTIAL_FLAGS flags, X509Certificate certificate, X509Certificate[] intermediates, List`1 alpnProtocols, CipherSuitesPolicy cipherSuitesPolicy, EncryptionPolicy encryptionPolicy)
   at System.Net.Quic.MsQuicConfiguration.Create(QuicClientConnectionOptions options)
   at System.Net.Quic.QuicConnection.FinishConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken)
   at System.Net.Quic.QuicConnection.ConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken)
   at System.Net.Quic.QuicConnection.ConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\Users\ayende\source\repos\ConsoleApp49\Program.cs:line 71
```


How can I force it to use MsQuic with OpenSSL?

**Comment by rzikm** [comment]
> How can I force it to use MsQuic with OpenSSL?

I think the easiest way is probably to build the app as self-contained and replace MsQuic.dll with the other version (see https://github.com/microsoft/msquic for releases). A more drastic approach would be overwriting MsQuic.dll in .NET installation in (see `dotnet --info` for location). However, note that using dotnet with OpenSSL-based MsQuic is not officially supported (we don't test this combination in CI) so there may be bugs.

**Comment by ayende** [comment]
Okay, I can confirm that manually updating `MsQuic` dll from `msquic_windows_x64_Release_openssl.zip` worked for the test scenario.
That isn't ideal, of course. I'm currently just testing things, however, and can live without the client cert support.
What I don't understand is why I cannot use the standard server only model here.

I'm still getting `UserCancelled` when I'm trying this on Windows.

**Comment by wfurt** [comment]
I think 22621 is Win 11 - even if it reports as 10. The check you posted @rzikm is `20348OrLower` e.g. it _should_ work IMHO on version [ayende](https://github.com/ayende) has. It would be _nice_ to figure out what that particular certificate does not work - and update troubleshooting guide.

**Comment by ayende** [comment]
Note that I also tried that with a Let's Encrypt certificate, so I'm pretty sure that the certificate itself is healthy and correct.

**Comment by ayende** [comment]
Any updates on this?

**Comment by ManickaP** [comment]
@ayende Have you tried that certificate with `SslStream` on that Windows set up? `SslStream` also uses SChannel as backend, so if it doesn't work, it's general cert + SChannel problem, not QUIC one.

**Comment by ayende** [comment]
Yes, I have.
I'm making extensive use of `SslStream` and I have tried that exact scenario (and many similar ones) with that with no issue.

**Comment by wfurt** [comment]
I'll give it try and I can run it on my Win 11 machine where client certificate tests are passing.

**Comment by wfurt** [comment]
I did little bit digging and here is what I found. 
I used you posted code @ayende and the generated certificate fails for SslStream as well - as expected:
```
System.Security.Authentication.AuthenticationException
  HResult=0x80131501
  Message=Authentication failed because the platform does not support ephemeral keys.
  Source=System.Net.Security
  StackTrace:
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslAuthenticationOptions sslAuthenticationOptions, Boolean newCredentialsRequested) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs:line 242
   at System.Net.Security.SslStream.AcquireCredentialsHandle(SslAuthenticationOptions sslAuthenticationOptions, Boolean newCredentialsRequested) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Protocol.cs:line 712
```

SslStream gives better exception in 8.0 and the export I suggested is unfortunately correct and needed. 
And then the handshake was failing as you described. After some digging, I found that it fails because of ECDSA but works with RSA. If you change the generation to 
```diff
- var ecdsa = ECDsa.Create();
+ var rsa = RSA.Create();
+ var certificateRequest = new CertificateRequest("CN=localhost", rsa, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);
```
then the code prints `hello` as expected on my Win 11 box so it seems like platform algorithm difference.
@nibanks may have some more insight. The 0x80090304 maps to SEC_E_INTERNAL_ERROR and that is certainly strange. 

I would suggest to close this there is not much we can do about it at .NET layer. 
If anything, I would suggest to open issue in msquic repo.

**Comment by ManickaP** [comment]
Closing based on @wfurt  recommendation. The same problem is with `SslStream`, this is not QUIC problem.

**Comment by wfurt** [comment]
I'm wondering if we should throw better exception. Perhaps PNSP would be more appropriate. @nibanks Is there some good way how to tell if MsQuic supports DSA certificates (or whatever) on given platform. The observed behavior is on particularly pleasant.
