### ISSUE TITLE
Vector<T> Can't Read Data Properly.

### ISSUE THREAD

**Issue by kingsznhone** [dotnet/runtime#88291]
### Description

I'm trying to use SIMD feature on .NET 6.
My CPU support AVX2.
In my understanding, a `Vector<T>` can hold 4 _double_  or 8 _float_ .
Then I  initialize a new vector from an array.
Weird thing happend.
With `Vector<double>.Count==4`
new vector only have values on index0 and index 1 (See Reproduction Steps)

### Reproduction Steps

```
double[] array_double = new double[]{ 0.1, 0.2, 0.3, 0.4 };
int vectorDoubleSize = Vector<double>.Count; //4
var vdouble = new Vector<double>(array_double, 0);
//vdouble = {0.1, 0.2, 0, 0}

float[] array_float = new float[] { 0.1f, 0.2f, 0.3f, 0.4f,0.5f,0.6f,0.7f,0.8f };
int vectorSingleSize = Vector<float>.Count; //8
var vfloat = new Vector<float>(array_float, 0);
//vfloat = {0.1, 0.2, 0.3, 0.4, 0, 0, 0, 0}
```

### Expected behavior

vdouble == {0.1, 0.2, 0.3, 0.4}
vfloat == {0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8}

### Actual behavior

vdouble == {0.1, 0.2, 0, 0}
vfloat == {0.1, 0.2, 0.3, 0.4, 0, 0, 0, 0}

### Known Workarounds

None

### Configuration

.NET 6  Windows 10 x64

**Comment by EgorBo** [comment]
I assume it only happens when debugger is attached? If it must be a dup of https://github.com/dotnet/runtime/issues/7626

**Comment by kingsznhone** [comment]
> I assume it only happens when debugger is attached? If so - it must be a dup of #7626 (or #9688) and presumably fixed in .NET 8

I think you are right. happens when debugger is attached Thanks for reply.
