### ISSUE TITLE
DateTime Comparison fails with different DateTimeKind

### ISSUE THREAD

**Issue by AdamRadicsTalison** [dotnet/runtime#88309]
### Description

When comparing UTC vs local time, it seems the offset is not applied before comparison.

### Reproduction Steps

I am in the UTC+8 time zone.

// 9.20am
DateTime laterUTC = new DateTime(2023, 06, 26, 01, 20, 00, DateTimeKind.Utc);

// 08:50am
DateTime earlierLocal = new DateTime(2023, 06, 26, 08, 50, 00, DateTimeKind.Local);

laterUTC.ToString("O").Dump();
earlierLocal.ToString("O").Dump();

($"Later UTC < Earlier Local: {(laterUTC < earlierLocal)}").Dump();

($"Later UTC < Earlier UTC: {(laterUTC < earlierLocal.ToUniversalTime())}").Dump();

($"Later Local < Earlier Local: {(laterUTC.ToLocalTime() < earlierLocal)}").Dump();

### Expected behavior

2023-06-26T01:20:00.0000000Z
2023-06-26T08:50:00.0000000+08:00
Later UTC < Earlier Local: False
Later UTC < Earlier UTC: False
Later Local < Earlier Local: False

### Actual behavior

2023-06-26T01:20:00.0000000Z
2023-06-26T08:50:00.0000000+08:00
Later UTC < Earlier Local: True
Later UTC < Earlier UTC: False
Later Local < Earlier Local: False

### Known Workarounds

Convert kind before comparison.

**Comment by huoyaoyuan** [comment]
I'll recommend using `DateTimeOffset` everywhere to get consistent result. Personally I ban the usage of `DateTime` at all.

**Comment by Clockwork-Muse** [comment]
[From the documentation](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.compare?view=net-7.0#remarks):
> To determine the relationship of t1 to t2, the [Compare](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.compare?view=net-7.0) method compares the [Ticks](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.ticks?view=net-7.0) property of t1 and t2 but ignores their [Kind](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.kind?view=net-7.0) property. Before comparing [DateTime](https://learn.microsoft.com/en-us/dotnet/api/system.datetime?view=net-7.0) objects, ensure that the objects represent times in the same time zone.

So: by design.

The reason for this is that `DateTimeKind` was introduced _after_ `DateTime`, and changing the behavior here would have been a **massive** breaking change.

**Comment by tarekgh** [comment]
@Clockwork-Muse is correct. Also, it will not be reliable to allow this comparison because it wouldn't make sense when having Unspecified Kind. Or even local Kind can be serialized to another machine which has different zone. @huoyaoyuan suggestion is good which try use DateTimeOffset in your case.

**Comment by Clockwork-Muse** [comment]
(Note that this is part of why I revile `DateTimeKind`, because it makes it extremely difficult to work with `DateTime` at all)
