### ISSUE TITLE
crossgen/ilc --help weird indentation 

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#88304]
It seems that `--help` prints commands with descriptions with a huge padding between them (presumably, aligned by the longest command):

![image](https://github.com/dotnet/runtime/assets/523221/d1d3b488-3b02-4909-b881-c56742f91954)

If the console window is not wide enough to fit it it's displayed like this:
![image](https://github.com/dotnet/runtime/assets/523221/79257e94-fea2-4147-9181-a6a824bd5212)

**Comment by EgorBo** [comment]
So presumably it happens because of `--targetos <FreeBSD|iOS|iOSSimulator|Linux|MacCatalyst|NetBSD|OSX|SunOS|tvOS|tvOSSimulator|Unknown|WebAssembly|Windows>`

**Comment by EgorBo** [comment]
.NET 7.0 crossgen:

![image](https://github.com/dotnet/runtime/assets/523221/a383418c-e332-414a-9652-142eea2f4ad6)

**Comment by jkotas** [comment]
cc @am11 @adamsitnik

**Comment by jkotas** [comment]
Reopening to fix ilc too: https://github.com/dotnet/runtime/pull/88324#discussion_r1250975409
