### ISSUE TITLE
The JIT is trying to compile all instantiations for Vector`1 once Span is used

### ISSUE THREAD

**Issue by hez2010** [dotnet/runtime#88312]
See https://godbolt.org/z/3xGTYovTP

The compiler is trying to instantiate all primitive types for Vector`1 once Span is used which leads to huge size regression. This is also leading compiler-explorer failed due to timeout.

Either switch to net7.0 or remove the Span usage in the code can resolve this issue.

**Comment by EgorBo** [comment]
@hez2010 I guess it's an expected behaviour with https://github.com/compiler-explorer/compiler-explorer/blob/271d5ff788862cd4a30a6e68cd29a43b83d15a54/lib/compilers/dotnet.ts#L325

**Comment by JulieLeeMSFT** [comment]
Hi @hez2010, does this answer your question? If so, I will close this issue.

> @hez2010 I guess it's an expected behaviour with https://github.com/compiler-explorer/compiler-explorer/blob/271d5ff788862cd4a30a6e68cd29a43b83d15a54/lib/compilers/dotnet.ts#L325

**Comment by hez2010** [comment]
Yes. Feel free to close it.
