### ISSUE TITLE
`impImportCnsTreeFromBuffer` can create incorrectly typed `TYP_DOUBLE` trees

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#88315]
This code:
https://github.com/dotnet/runtime/blob/f25bc7b5b859935192e4eddc5b71efe71a60a4de/src/coreclr/jit/importer.cpp#L3695-L3699
creates a `TYP_DOUBLE` node instead of a `TYP_FLOAT` node.

**Comment by EgorBo** [comment]
@jakobbotsch I thought you fixed it?

**Comment by jakobbotsch** [comment]
> @jakobbotsch I thought you fixed it?

I ended up not landing #87548 that had that fix and fixed the underlying problem in a different way
