### ISSUE TITLE
DateTimeOffset.ParseExact unable to parse day 1 year 1

### ISSUE THREAD

**Issue by Sigval** [dotnet/runtime#88335]
### Description

DateTimeOffset.ParseExact unable to parse day 1 year 1

### Configuration

// this is ok
var d1 = DateTimeOffset.ParseExact("0001-01-02", "yyyy-MM-dd", null, System.Globalization.DateTimeStyles.None);
// this fails
var d2 = DateTimeOffset.ParseExact("0001-01-01", "yyyy-MM-dd", null, System.Globalization.DateTimeStyles.None);
// this is ok
DateTimeOffset dateTimeOffset = DateTimeOffset.ParseExact("0001-01-01T00:00:00+00:00", "yyyy-MM-ddTHH:mm:sszzz", null);
// this fails
DateTimeOffset dateTimeOffset = DateTimeOffset.ParseExact("0001-01-01T00:00:00+01:00", "yyyy-MM-ddTHH:mm:sszzz", null);

### Regression?

N/A

### Other information

we experiance this when using nswag, when using dateOnly backend, nswag tries to parse dataOnly to dateTimeOffest and fails when the dateOnly variable is set to DateOnly,MinValue

presumably due to dateTimeOffset.ParseExact using default offset which differs from 0 and thereby fails if for example set to +1
resulting in legal year timeframe out of boundery 1 to 9999

DateTimeOffset.ParseExact should maybe instead use default offset 0 when no offset is provided, or alternativly assure that any offset would never cause year to go below day 1 year 1.

**Comment by tarekgh** [comment]
The behavior is documented in the remark section of https://learn.microsoft.com/en-us/dotnet/api/system.datetimeoffset.parseexact?view=net-7.0#system-datetimeoffset-parseexact(system-string-system-string()-system-iformatprovider-system-globalization-datetimestyles). It is clearly states:

```
If styles includes [AssumeLocal](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.datetimestyles?view=net-7.0#system-globalization-datetimestyles-assumelocal), the offset of the local time zone is assigned to the [DateTimeOffset](https://learn.microsoft.com/en-us/dotnet/api/system.datetimeoffset?view=net-7.0) object. If styles includes [AssumeUniversal](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.datetimestyles?view=net-7.0#system-globalization-datetimestyles-assumeuniversal), the Coordinated Universal Time (UTC) offset, or +00:00, is assigned to the [DateTimeOffset](https://learn.microsoft.com/en-us/dotnet/api/system.datetimeoffset?view=net-7.0) object. If neither value is specified, the offset of the local time zone is used.
```

As suggested before, you can use `DateTimeStyles.AssumeUniversal`.
