### ISSUE TITLE
Build break in Mono Android extra-platforms

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#88344]
PR: https://github.com/dotnet/runtime/pull/88342

Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=328385

Log: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/328385/logs/223

```
2023-07-03T16:59:17.6848371Z   CMake Error at /usr/share/cmake-3.21/Modules/CMakeTestCXXCompiler.cmake:62 (message):
2023-07-03T16:59:17.6856690Z     The C++ compiler
2023-07-03T16:59:17.6856932Z   
2023-07-03T16:59:17.6857259Z       "/usr/bin/c++"
2023-07-03T16:59:17.6857646Z   
2023-07-03T16:59:17.6857894Z     is not able to compile a simple test program.
2023-07-03T16:59:17.6858043Z   
2023-07-03T16:59:17.6858208Z     It fails with the following output:
2023-07-03T16:59:17.6858340Z   
2023-07-03T16:59:17.6858549Z       Change Dir: /__w/1/s/artifacts/obj/mono/android.arm64.Release/cross/CMakeFiles/CMakeTmp
2023-07-03T16:59:17.6858948Z       
2023-07-03T16:59:17.6859436Z       Run Build Command(s):/usr/bin/make -f Makefile cmTC_e98b0/fast && /usr/bin/make  -f CMakeFiles/cmTC_e98b0.dir/build.make CMakeFiles/cmTC_e98b0.dir/build
2023-07-03T16:59:17.6859987Z       make[1]: Entering directory '/__w/1/s/artifacts/obj/mono/android.arm64.Release/cross/CMakeFiles/CMakeTmp'
2023-07-03T16:59:17.6860286Z       Building CXX object CMakeFiles/cmTC_e98b0.dir/testCXXCompiler.cxx.o
2023-07-03T16:59:17.6861105Z       /usr/bin/c++   -I/__w/1/s/artifacts/obj/mono/android.arm64.Release/llvm//x64/include/c++/v1 -L/__w/1/s/artifacts/obj/mono/android.arm64.Release/llvm//x64/lib -stdlib=libc++  -o CMakeFiles/cmTC_e98b0.dir/testCXXCompiler.cxx.o -c /__w/1/s/artifacts/obj/mono/android.arm64.Release/cross/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
2023-07-03T16:59:17.6862084Z       c++: error: unrecognized command-line option ‘-stdlib=libc++’
2023-07-03T16:59:17.6862397Z       make[1]: *** [CMakeFiles/cmTC_e98b0.dir/build.make:78: CMakeFiles/cmTC_e98b0.dir/testCXXCompiler.cxx.o] Error 1
2023-07-03T16:59:17.6862993Z       make[1]: Leaving directory '/__w/1/s/artifacts/obj/mono/android.arm64.Release/cross/CMakeFiles/CMakeTmp'
2023-07-03T16:59:17.6863231Z       make: *** [Makefile:127: cmTC_e98b0/fast] Error 2
```

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "is not able to compile a simple test program",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=328385
**Error message validated:** `is not able to compile a simple test program`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 7/5/2023 8:25:13 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[333900](https://dev.azure.com/dnceng-public/public/_build/results?buildId=333900)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/333900/logs/277)|dotnet/runtime#88539|
|[333418](https://dev.azure.com/dnceng-public/public/_build/results?buildId=333418)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/333418/logs/8)||
|[333413](https://dev.azure.com/dnceng-public/public/_build/results?buildId=333413)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/333413/logs/277)||
|[2217531](https://dev.azure.com/dnceng/internal/_build/results?buildId=2217531)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2217531/logs/135)||
|[2217469](https://dev.azure.com/dnceng/internal/_build/results?buildId=2217469)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2217469/logs/128)||
|[333175](https://dev.azure.com/dnceng-public/public/_build/results?buildId=333175)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/333175/logs/367)||
|[333176](https://dev.azure.com/dnceng-public/public/_build/results?buildId=333176)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/333176/logs/8)||
|[2217350](https://dev.azure.com/dnceng/internal/_build/results?buildId=2217350)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2217350/logs/183)||
|[333001](https://dev.azure.com/dnceng-public/public/_build/results?buildId=333001)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/333001/logs/367)||
|[332997](https://dev.azure.com/dnceng-public/public/_build/results?buildId=332997)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/332997/logs/8)||
|[332951](https://dev.azure.com/dnceng-public/public/_build/results?buildId=332951)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/332951/logs/260)|dotnet/runtime#88548|
|[2217160](https://dev.azure.com/dnceng/internal/_build/results?buildId=2217160)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2217160/logs/244)||
|[332861](https://dev.azure.com/dnceng-public/public/_build/results?buildId=332861)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/332861/logs/368)||
|[332859](https://dev.azure.com/dnceng-public/public/_build/results?buildId=332859)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/332859/logs/8)||
|[2217069](https://dev.azure.com/dnceng/internal/_build/results?buildId=2217069)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2217069/logs/131)||
|[2216979](https://dev.azure.com/dnceng/internal/_build/results?buildId=2216979)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2216979/logs/123)||
|[332633](https://dev.azure.com/dnceng-public/public/_build/results?buildId=332633)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/332633/logs/8)||
|[332635](https://dev.azure.com/dnceng-public/public/_build/results?buildId=332635)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/332635/logs/298)||
|[2216940](https://dev.azure.com/dnceng/internal/_build/results?buildId=2216940)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2216940/logs/133)||
|[2216878](https://dev.azure.com/dnceng/internal/_build/results?buildId=2216878)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2216878/logs/184)||
|[332434](https://dev.azure.com/dnceng-public/public/_build/results?buildId=332434)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/332434/logs/297)||
|[332431](https://dev.azure.com/dnceng-public/public/_build/results?buildId=332431)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/332431/logs/8)||
|[2216705](https://dev.azure.com/dnceng/internal/_build/results?buildId=2216705)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2216705/logs/184)||
|[332212](https://dev.azure.com/dnceng-public/public/_build/results?buildId=332212)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/332212/logs/304)|dotnet/runtime#88530|
|[332206](https://dev.azure.com/dnceng-public/public/_build/results?buildId=332206)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/332206/logs/234)|dotnet/runtime#88529|
|[2216413](https://dev.azure.com/dnceng/internal/_build/results?buildId=2216413)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2216413/logs/153)||
|[331700](https://dev.azure.com/dnceng-public/public/_build/results?buildId=331700)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/331700/logs/293)||
|[331699](https://dev.azure.com/dnceng-public/public/_build/results?buildId=331699)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/331699/logs/8)||
|[2216266](https://dev.azure.com/dnceng/internal/_build/results?buildId=2216266)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2216266/logs/132)||
|[2216141](https://dev.azure.com/dnceng/internal/_build/results?buildId=2216141)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2216141/logs/177)||
|[331212](https://dev.azure.com/dnceng-public/public/_build/results?buildId=331212)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/331212/logs/302)||
|[331211](https://dev.azure.com/dnceng-public/public/_build/results?buildId=331211)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/331211/logs/8)||
|[2215927](https://dev.azure.com/dnceng/internal/_build/results?buildId=2215927)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2215927/logs/148)||
|[330527](https://dev.azure.com/dnceng-public/public/_build/results?buildId=330527)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/330527/logs/284)||
|[330525](https://dev.azure.com/dnceng-public/public/_build/results?buildId=330525)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/330525/logs/8)||
|[2215460](https://dev.azure.com/dnceng/internal/_build/results?buildId=2215460)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2215460/logs/137)||
|[2215301](https://dev.azure.com/dnceng/internal/_build/results?buildId=2215301)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2215301/logs/168)||
|[2214924](https://dev.azure.com/dnceng/internal/_build/results?buildId=2214924)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2214924/logs/132)||
|[329962](https://dev.azure.com/dnceng-public/public/_build/results?buildId=329962)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/329962/logs/292)||
|[329959](https://dev.azure.com/dnceng-public/public/_build/results?buildId=329959)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/329959/logs/8)||
|[329893](https://dev.azure.com/dnceng-public/public/_build/results?buildId=329893)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/329893/logs/222)|dotnet/runtime#88436|
|[2214747](https://dev.azure.com/dnceng/internal/_build/results?buildId=2214747)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2214747/logs/153)||
|[2214660](https://dev.azure.com/dnceng/internal/_build/results?buildId=2214660)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2214660/logs/157)||
|[329472](https://dev.azure.com/dnceng-public/public/_build/results?buildId=329472)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/329472/logs/303)||
|[329470](https://dev.azure.com/dnceng-public/public/_build/results?buildId=329470)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/329470/logs/8)||
|[2214570](https://dev.azure.com/dnceng/internal/_build/results?buildId=2214570)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2214570/logs/154)||
|[2214469](https://dev.azure.com/dnceng/internal/_build/results?buildId=2214469)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2214469/logs/129)||
|[329210](https://dev.azure.com/dnceng-public/public/_build/results?buildId=329210)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/329210/logs/311)||
|[329209](https://dev.azure.com/dnceng-public/public/_build/results?buildId=329209)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/329209/logs/8)||
|[2214383](https://dev.azure.com/dnceng/internal/_build/results?buildId=2214383)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2214383/logs/156)||
|[2214311](https://dev.azure.com/dnceng/internal/_build/results?buildId=2214311)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2214311/logs/159)||
|[2214184](https://dev.azure.com/dnceng/internal/_build/results?buildId=2214184)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2214184/logs/159)||
|[328828](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328828)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/328828/logs/277)|dotnet/runtime#88322|
|[328823](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328823)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/328823/logs/8)||
|[328822](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328822)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/328822/logs/305)||
|[2214097](https://dev.azure.com/dnceng/internal/_build/results?buildId=2214097)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2214097/logs/159)||
|[328688](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328688)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/328688/logs/239)|dotnet/runtime#88360|
|[2214014](https://dev.azure.com/dnceng/internal/_build/results?buildId=2214014)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2214014/logs/120)||
|[328529](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328529)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/328529/logs/341)||
|[328528](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328528)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/328528/logs/8)||
|[328443](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328443)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/328443/logs/281)|dotnet/runtime#88322|
|[2213884](https://dev.azure.com/dnceng/internal/_build/results?buildId=2213884)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2213884/logs/149)||
|[328385](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328385)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/328385/logs/294)|dotnet/runtime#88342|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|7|59|63|

**Comment by jkotas** [comment]
Introduced by #87190

cc @directhex

**Comment by directhex** [comment]
Gonna copy-paste my explainer on this issue from Discord:

> 1. Mariner has a model of "base OS is a minimal host for clang, all actual compilation is cross compiled against a base OS in a folder in /crossrootfs.
> 2. All non-desktop targets have a model of "build target runtime, and build a cross-compiler for the current running host, and use that cross-compiler to build the BCL and friends for the runtime pack... throw away the cross-compiler at the end (and build those in a separate job for distribution to users)
> 3. Our Android builds currently only work by accident, because they build the android runtime using android sdk then a non-cross-compiled cross-compiler against the host OS (using gcc and /usr/lib instead of clang and /crossrootfs/x64). There is no crossrootfs in the android image. The entire BuildMonoCross target is doing everything exactly wrong.

This should be easily fixed by adding `/p:BuildMonoAOTCrossCompiler=false` to the job, it helped with the same failure on runtime-official.
