### ISSUE TITLE
Console.CursorTop causes invalid Console.ReadKey input

### ISSUE THREAD

**Issue by waf** [dotnet/runtime#88343]
### Description

Calling `Console.CursorTop` when reading `Console.ReadKey` in a loop can cause `Console.ReadKey` to read an invalid character (�).

Simply removing the call to `Console.CursorTop` (with no other changes) solves the issue. There's no multithreading going on here, but it does require calling `Console.ReadKey` repeatedly in a loop.

It does not happen on Windows, but it does happen on Linux as well as WSL2 in Windows Terminal.

### Reproduction Steps

Reproduction steps:

1. Run the below program (it's a valid top-level program for .NET 7).
2. Put about 100 or 200 unicode characters on your clipboard (e.g. the character '❌' a bunch of times) and then paste it several times.
    - See the screen recording below as an example.

**Program showing the problem:**

```csharp
// the following is valid top-level statement program.

Console.WriteLine("Started. Press Ctrl-C to exit.");
Console.Write("> ");
ReadLine();

static void ReadLine()
{
    foreach (var key in ReadForever())
    {
        // comment out the following line to avoid the garbled characters.
        _ = Console.CursorTop;

        Console.Write(key);
    }
}

static IEnumerable<string> ReadForever()
{
    while (true)
    {
        var key = Console.ReadKey(true);

        if (!Console.KeyAvailable)
        {
            yield return key.KeyChar.ToString();
            continue;
        }

        // If the user pastes text, we see it as a bunch of key presses. We don't want to send
        // them all individually, as it will trigger unnecessary processing. Instead, batch
        // them up to send as single "pasted text" block.
        var keys = new List<ConsoleKeyInfo> { key };
        do
        {
            keys.Add(Console.ReadKey(true));
        } while (Console.KeyAvailable);

        yield return string.Join("", keys.Select(k => k.KeyChar));
    }
}
```

**Screen Recording of reproduction steps**

[!Screen Recording of reproduction steps](https://github.com/dotnet/runtime/assets/97195/272704e6-ef65-48c1-8bb0-fbf0ebaec9dc)

### Expected behavior

Should be able to call `Console.CursorTop` without affecting `Console.ReadKey`.

### Actual behavior

`Console.CursorTop` interferes with `Console.ReadKey`.

### Configuration

I have reports of users that are running Linux natively on their machines running into this issue. I have reproduced it with the following WSL2 configuration:

- WSL2 with Ubuntu: Linux 5.15.90.1-microsoft-standard-WSL2 x86_64
- .NET 7.0.305 (I also tried this with the latest .NET 8 pre-release)
- Windows Terminal 1.17.11461.0

### Other information

From debugging, it's an input issue, not an output issue. The char being read from Console.ReadKey has the unicode replacement character:

![image](https://github.com/dotnet/runtime/assets/97195/833127d8-c5ff-46c1-bada-717eb881d67d)

**Comment by adamsitnik** [comment]
Hi @waf 

Thank you for a very detailed bug report.

To get the current cursor position we write a terminal-specific escape sequence to standard output and then read the terminal response from standard input:

https://github.com/dotnet/runtime/blob/e5be81a39b1337c0b066e97b702b5ac5518c4831/src/libraries/System.Console/src/System/ConsolePal.Unix.cs#L488-L521

There must be something specific to copy-pasting that we are missing (most likely the paste is filling the standard input with more than one character, we emit the sequence, the response gets added after pasted unread content, the reader does not account for that and we are in trouble).

I doubt we are going to have free cycles to fix it for .NET 8, so for now I can mark it as "help needed" and hope that we can get some help from outside.

**Comment by waf** [comment]
Thanks for the explanation and pointing out that section of the code. Just a bit of additional info, it's also reproducible by holding down a keyboard key, but it depends on the computer's key repeat speed so the repro steps are a bit more involved.

For example, if a user holds down their `ä` key or any other key representing a non-ASCII character they can also trigger this.

**Comment by tmds** [comment]
@adamsitnik I can take a look at this.
