### ISSUE TITLE
[wasm] AOT: segfault in mono-aot-cross for `System.Collections.Tests`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#88358]
`mono-aot-cross` segaulting when AOT'ing `System.Collections.Tests` on [windows](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-e75caed90dca4be1be/WasmTestOnBrowser-System.Collections.Tests/1/console.bcafbf2f.log?helixlogtype=result), and [linux](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-f64a1598354a4e32a8/normal-System.Collections.Tests/1/console.a59a1b37.log?helixlogtype=result).

`Precompiling failed for /root/helix/work/workitem/e/wasm_build/obj/wasm/for-build/aot-in/System.Collections.Tests.dll with exit code 139`
`Precompiling failed for /root/helix/work/workitem/e/wasm_build/obj/wasm/for-build/aot-in/aot-instances.dll with exit code 139`
```
mono-aot-cross[20259]: segfault at 0 ip 00005560e14c15b2 sp 00007ffde3dbc028 error 4 in mono-aot-cross[5560e0de4000+9c0000] [ 1197.076060] Code: 0f 1f 84 00 00 00 00 00 e9 6b d5 10 00 66 66 2e 0f 1f 84 00 00 00 00 00 0f b6 47 08 48 85 ff 74 0d 83 f8 0f 75 08 48 8b 7f 10 <48> 8b 07 c3 48 85 ff 74 03 83 f8 11 48 83 c7 18 48 8b 07 c3 66 2e [ 1211.785100]
mono-aot-cross[20306]: segfault at 0 ip 000055ec647445b2 sp 00007ffff7c528d8 error 4 in mono-aot-cross[55ec64067000+9c0000] [ 1211.785111] Code: 0f 1f 84 00 00 00 00 00 e9 6b d5 10 00 66 66 2e 0f 1f 84 00 00 00 00 00 0f b6 47 08 48 85 ff 74 0d 83 f8 0f 75 08 48 8b 7f 10 <48> 8b 07 c3 48 85 ff 74 03 83 f8 11 48 83 c7 18 48 8b 07 c3 66 2e
```

Changes since last passing run: f25bc7b5...80090662 which includes the LLVM upgrade https://github.com/dotnet/runtime/pull/87190 .

cc @vargaz @directhex 

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by directhex** [comment]
Waiting on an LLVM update which might help

**Comment by directhex** [comment]
Testing LLVM update in https://github.com/dotnet/runtime/pull/88345

**Comment by vargaz** [comment]
https://github.com/dotnet/runtime/pull/88397

**Comment by vargaz** [comment]
Should be fixed.
