### ISSUE TITLE
Once HttpClient.DefaultProxy is accessed, it will not be updated again.

### ISSUE THREAD

**Issue by simpleway2016** [dotnet/runtime#88409]
### Description

When the system proxy changes, HttpClient.DefaultProxy still retrieves the old proxy.

### Reproduction Steps

When running the program and accessing HttpClient.DefaultProxy, if the system proxy is modified afterwards, the program will still retrieve the old proxy when accessing HttpClient.DefaultProxy again.

### Expected behavior

nothing

### Actual behavior

  nothing

**Comment by karelz** [comment]
This is a known limitation - covered in #46910

**Comment by karelz** [comment]
Duplicate of #46910
