### ISSUE TITLE
Minor documentation error for `IFloatingPoint<TSelf>.Round(TSelf, int, MidpointRounding)`

### ISSUE THREAD

**Issue by hamarb123** [dotnet/runtime#88401]
The following documentation comment is incorrect:

https://github.com/dotnet/runtime/blob/51d351706ef51770b305c46664828886e97d634b/src/libraries/System.Private.CoreLib/src/System/Numerics/IFloatingPoint.cs#L41

It should be:
```diff
-/// <summary>Rounds a value to a specified number of fractional-digits using the default rounding mode (<see cref="MidpointRounding.ToEven" />).</summary>
+/// <summary>Rounds a value to a specified number of fractional-digits using the specified rounding mode.</summary>
```

I noticed this in VS.

**Comment by danmoseley** [comment]
thanks. do you want to offer a PR? note, it would also be to this as I don't believe these are generated from sources here yet.
https://github.com/dotnet/dotnet-api-docs/blob/cbfe8950f80429d965b9ad1848f55cb952532f16/xml/System.Numerics/IFloatingPoint%601.xml#L343

**Comment by danmoseley** [comment]
cool. to be clear -- PR for code here, and for docs. Eventually one will be built from the other, but right now for historical reasons only part is.

**Comment by hamarb123** [comment]
PRs:
https://github.com/dotnet/runtime/pull/88458
https://github.com/dotnet/dotnet-api-docs/pull/9122
