### ISSUE TITLE
System.Array.Copy() getting slow in background on Windows 11

### ISSUE THREAD

**Issue by stanley76726** [dotnet/runtime#88407]
The "background" term represents the running program is NOT on top. There is no issue while the program is running in foreground.

This issue only occurs on Windows 11 (Windows 10 works fine in both foreground and background).

It can be reproduced by following C# code:

```
using System;
using System.Diagnostics;

namespace ArrayCopyIssue
{
    internal class Program
    {
        const int Width = 16384;
        const int Height = 1024;
        const int Bpp = 12;
        const int Size = Width * Height;
        const int DataSize = Size * ((Bpp + 7) / 8);

        static void Main(string[] args)
        {
            int threshold;
            if (args.Length == 0 || !int.TryParse(args[0], out threshold))
                threshold = 50;

            bool cancelled = false;
            Console.CancelKeyPress += (s, e) => cancelled = true;

            var rawData = new byte[DataSize];
            var data16 = new ushort[Size];
            var outData = new int[Size];

            var watch = new Stopwatch();
            while (!cancelled)
            {
                Buffer.BlockCopy(rawData, 0, data16, 0, rawData.Length);
                watch.Restart();
                Array.Copy(data16, 0, outData, 0, outData.Length);
                watch.Stop();
                if (watch.ElapsedMilliseconds < threshold)
                    Log($"Consumer: Array.Copy() takes {watch.ElapsedMilliseconds}ms.");
                else
                    Error($"Consumer: Array.Copy() takes {watch.ElapsedMilliseconds}ms.");
            }
        }

        static void Log(string log)
        {
            Console.ForegroundColor = ConsoleColor.White;
            Console.WriteLine(log);
        }

        static void Error(string error)
        {
            Console.ForegroundColor = ConsoleColor.DarkRed;
            Console.WriteLine(error);
        }
    }
}
```

I've tested several PCs and all of them have the same issue on Win11. See my test results for details:

| PC | CPU | OS | .NET | Time in Foreground | Time in Background |
| :---: | :---: | :---: | :---: | --- | ---|
| A | Intel i9-12900 2.40GHz | Win11 x64 21H2 | 4.8 | 40ms | **50-70ms** |
| | | | 6.0 | 25ms | **40-60ms** |
| B | Intel i5-3470 3.20GHz | Win10 x64 21H1 | 4.8 | 120-125ms | 120-125ms |
| | | | 6.0 | 85-90ms | 85-90ms |
| C | Intel i3-12100 3.30GHz | Win10 x64 22H2 | 4.8 | 40-45ms | 40-45ms |
| D | Intel i5-13100 3.40GHz | Win11 x64 22H2 | 4.8 | 40-45ms | **50-70ms** |
| | | | 6.0 | 20-30ms | **30-45ms** |
| E | Intel i5-10500 3.10GHz | Win10 x64 21H2 | 4.8 | 55-65ms | 55-65ms |
| | | Win11 21H2 | 4.8 | 60ms | **70-100ms** |
| F | Intel i5-11500 2.70GHz | Win10 x64 22H2 | 4.8 | 55-60ms | 55-60ms |
| | | Win11 21H2 | 4.8 | 55-65ms | **75-120ms** |

**Comment by MichalPetryka** [comment]
What's the CPU being used here? If it's an Intel 12th or 13th gen CP, it's likely that OS reschedules the thread to an efficiency core.

**Comment by Clockwork-Muse** [comment]
I'm not sure it even has to be a recent-gen CPU, since the OS could reschedule anyways.

**Comment by MichalStrehovsky** [comment]
Would be worth checking if changing this setting resolves this. Client version of Windows by design prioritize the processes users are interacting with. Normally this only affects things like thread priority, but who knows what power management policies et al do with this:

![image](https://github.com/dotnet/runtime/assets/13110571/0a4dd5cb-59f0-454b-a6ad-68af1f232b66)

**Comment by stanley76726** [comment]
@MichalStrehovsky @Clockwork-Muse 
Edited my test results to add CPU info and to update OS version. Intel CPUs of 9th, 10th, 11th, and 13th Gens have the same issue on Win11.
I also tested the performance options as Michal suggested. Unfortunately the issue still exists in both Programs/Background services settings.

@danmoseley 
What I've tried to run at higher priority but failed:
- Run as Administrator
- Run the loop in a long-running task using `Task.Factory.StartNew(() => { }, cancelToken, TaskCreationOptions.LongRunning, TaskScheduler.Default)` (I expect the task to run at a dedicated core)

My "running in background" means minimized and to launch Edge browser to read some news on the homepage for about one minute 😄 .
Initially I found the issue in my UI application and it was running as 32-bit. To narrow down the scope, I wrote the test program but running as 64-bit (I didn't run the test program as 32-bit again).

**Update**
My current workaround is to use for-loop instead of Array.Copy() since the former is almost 2x faster than latter:
```
#if false
Array.Copy(data16, 0, outData, 0, outData.Length);
#else
for (int i = 0; i < outData.Length; i++)
    outData[i] = data16[i];
#endif
```
It also becomes my another question: Why for-loop can be faster than Array.Copy() if the source type and destination type are different?
And I also found it using for-loop getting slow in background.

**Comment by reflectronic** [comment]
Windows 11 has a new "foreground boost" feature that is much more aggressive in prioritizing the foreground application (e.g. see [SetAdditionalForegroundBoostProcesses](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setadditionalforegroundboostprocesses)). If this doesn't reproduce on Windows 10 then this is probably the cause.

**Comment by MichalPetryka** [comment]
> My current workaround is to use for-loop instead of Array.Copy() since the former is almost 2x faster than latter:

Does this reproduce on all machines too? I think that the only case where a scalar loop would be faster would be running on an efficiency core, since those don't have real AVX support.

**Comment by Clockwork-Muse** [comment]
> (I expect the task to run at a dedicated core)

This isn't guaranteed.  Whatever scheduler is in use _may_ use that to assign a thread from outside the pool, but there's no requirement to do so.  Also, note that all threads the C# process uses are still only going to get slices of time from the OS, not a completely dedicated thread.

> My "running in background" means minimized and to launch Edge browser to read some news on the homepage for about one minute 😄 .

.... do you really need `Array.Copy(...)` for this?  As opposed to just reading from whatever returned span.

**Comment by stanley76726** [comment]
> > (I expect the task to run at a dedicated core)
> 
> This isn't guaranteed. Whatever scheduler is in use _may_ use that to assign a thread from outside the pool, but there's no requirement to do so. Also, note that all threads the C# process uses are still only going to get slices of time from the OS, not a completely dedicated thread.

I really mean that I expect it could, but I know it can't. It's just to reply to what I've tried to run at higher priority.

> 
> > My "running in background" means minimized and to launch Edge browser to read some news on the homepage for about one minute 😄 .
> 
> .... do you really need `Array.Copy(...)` for this? As opposed to just reading from whatever returned span.

Yes, I need it for my real application.

**Comment by tannergooding** [comment]
This isn't something .NET really has any control over. The operating system scheduler for many different platforms do similar things where processes that have focus get more CPU time than those without.

It would be undesirable for .NET to implicitly go against the platform defaults for such systems.
