### ISSUE TITLE
[API Proposal]: ConcurrentQueue.TryDequeue with condition

### ISSUE THREAD

**Issue by wmjordan** [dotnet/runtime#88412]
### Background and motivation

Items are enqueued into a `ConcurrentQueue`.
The consumer will periodically check the queue's first item and see whether a condition is met. If its met, the item is dequeued, otherwise no item will be dequeued.

External condition might change (for instance, time elapses).
Internal condition might change (for instance, a counter within an enqueued item increments).
Thus there may be a _Check and Dequeue_ pattern for the `ConcurrentQueue`.

The _Check and Dequeue_ pattern should be atomic.

### API Proposal

```csharp
namespace System.Collections.Concurrent;

public class ConcurrentQueue<T>
{
    public bool TryDequeue(Func<T, bool> condition, out T item);
}
```

### API Usage

```csharp
// insert value
var c = new ConcurrentQueue<(int, DateTime)>();
c.Enqueue((42, DateTime.Now));
var deadline = DateTime.Now.AddSeconds(-1);

// Getting the value out if it is expired
while (c.TryDequeue(i => i.Item2 < deadline, out var expiredItem) == false) {
    Thread.Sleep(100);
    deadline = DateTime.Now.AddSeconds(-1);
}
Console.WriteLine(expiredItem.Item1 + " is expired");
```

**Comment by wmjordan** [comment]
The original API Usage example code had a dead-loop. I just fixed it.

**Comment by eiriktsarpalis** [comment]
Looking at your motivating example, it seems a bit odd that you'd want to block the entire queue based on a property of its head element. Perhaps using a priority queue keyed on the `DateTime` would make more sense instead?

Secondly, it seems it should be possible to express the proposed method via an extension using the `TryPeek` and `Dequeue` methods and locking on the queue. I'm not an expert of `ConcurrentQueue` but a quick look at the `Dequeue` implementation suggests to me that a baked-in implementation would need to do something similar (e.g. by having competing threads spin while the user delegate is running).

**Comment by wmjordan** [comment]
Yes, you are right.

Using`SpinWait` or `lock` protected `TryPeak` and `TryDequeue` should be sufficient.
