### ISSUE TITLE
Cannot modify the static field of dependent module on dynamically-loaded library using hostfxr(DNNE)

### ISSUE THREAD

**Issue by dayo05** [dotnet/runtime#88427]
### Description

I'm using [DNNE](https://github.com/AaronRobinsonMSFT/DNNE) which uses hostfxr internally to embed CLR in my program. 

I have two project in the solution: just simply use libraryA, libraryB here.

I initialize CLR and load libraryA with DNNE using `UnmanagedCallersOnly` Attribute. Then I load libraryB which depends on libraryA dynamically using `Assembly.LoadFrom`. Then, I execute the code inside libraryB with reflection.

### Reproduction Steps

This is the code I used to for embed CLR:
```cpp
#include <ConsoleApp1NE.h>

int main(int argv, char** args) {
    CallUnmanaged();
    return 0;
}
```

This is the code of libraryA:
```cs
using System.Reflection;
using System.Runtime.InteropServices;
using ConsoleApp1;


X.CallInternal();
return;

public class X {
    [UnmanagedCallersOnly]
    public static void CallUnmanaged() {
        CallInternal();
    }


    public static void CallInternal() {
        Console.WriteLine(Variable.a);
        Variable.a++;
        Console.WriteLine(Variable.a);
        var asm = Assembly.LoadFrom("/Users/dayo/JIC/ConsoleApp1/ClassLibrary1/bin/Release/net6.0/ClassLibrary1.dll");
        asm.GetType("ClassLibrary1.Entry").GetMethod("Exec").Invoke(null, null);
        Console.WriteLine(Variable.a);

        asm.GetType("ClassLibrary1.Entry").GetMethod("Exec").Invoke(null, null);
        asm.GetType("ClassLibrary1.Entry").GetMethod("Exec").Invoke(null, null);
    }
}
```
```cs
namespace ConsoleApp1; 

public class Variable {
    public static int a = 1;
    public static void Print() => Console.WriteLine(a++);
}
```
And this is libraryB
```cs
using ConsoleApp1;

namespace ClassLibrary1;

public class Entry {
    public static void Exec() {
        Variable.a++;
        Console.WriteLine("a: " + Variable.a);
    }
}
```

The output are almostly different with those two cases.
Using hostfxr:

### Expected behavior

If I don't use hostfxr; just execute the library, I got this output which I expected
```
1
2
a: 3
3
a: 4
a: 5
```

### Actual behavior

If I use hostfxr, I got this output:
```
1
2
a: 2
2
a: 3
a: 4
```

### Configuration

I'm using mac os with M1 pro chips and .NET 6 on JB Rider

**Comment by jkotas** [comment]
You are likely ending up with multiple copies of libraryA loaded in different assembly load contexts. Here is how you can verify it:

Call `AppDomain.CurrentDomain.GetAssemblies()` at the end of your test and check that there is only one instance of libraryA loaded. If there are multiple instance of libraryA loaded, it would explain what you are seeing.

`Assembly.LoadFrom` tends to cause problems like this one. It is best to avoid this API.

cc @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
The solution here is to manually manage the depedencies through `AssemblyLoadContext`s (ALCs). There are many ways to handle this though. I recommend [familiarizing yourself with ALCs](https://learn.microsoft.com/dotnet/core/dependency-loading/understanding-assemblyloadcontext) and pushing all dependencies into the same ALC if isolation isn't the highest priority.

We have recently address some of this ALC confusion in C++/CLI and COM. @elinor-fung has been working on a general solution.

**Comment by dayo05** [comment]
> The solution here is to manually manage the depedencies through `AssemblyLoadContext`s (ALCs). There are many ways to handle this though. I recommend [familiarizing yourself with ALCs](https://learn.microsoft.com/dotnet/core/dependency-loading/understanding-assemblyloadcontext) and pushing all dependencies into the same ALC if isolation isn't the highest priority.
> 
> We have recently addressed some of this ALC confusion in C++/CLI and COM. @elinor-fung has been working on a general solution.

Thanks for some references.

By that, I can solve my issue with 
```cs
var alc = AssemblyLoadContext.All.First(x => x.Assemblies.Any(x => x == typeof(MainEntryAttribute).Assembly));
```
To get current ALC, load new assembly with that ALC.

But this might be little bit complex part to understand... so I hope the general solution gonna implement to CLR soon :D
