### ISSUE TITLE
Missing CI validation for RHEL 7.2 Release

### ISSUE THREAD

**Issue by dpodder** [dotnet/runtime#8843]
Linux official Release builds are currently produced on Red Hat Enterprise Linux 7.2, but we don't have this configuration in CI validation. We just recently recovered from a build break that slipped in on that platform due to the lack of validation.

We should enable RHEL 7.2 Release to be automatically triggered in CI, so that we can validate the Linux release build config. This should be done such that if the official build platform for Linux changes, the matching CI job gets updated to match as well.

**Comment by MattGal** [comment]
I'm going to close this out.  We have regular testing now on a "best effort" latest Rhel 7 setup, which is currently 7.9, and this runs on most PRs and in inner/outerloop scenarios every day.
