### ISSUE TITLE
MSB4018 The "ConvertDllsToWebCil" task failed unexpectedly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#88442]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MSB4018-The-ConvertDllsToWebCil-task-f/10404423)._

---
I have Visual Studio Version 17.7.0 Preview 2.0 installed on my Windows 11 Laptop Machine. I am working on a Blazor Webassembly project with latest Net Core 8.0 (preview 5). Its second time i am facing Version ~MSB4018 The "ConvertDllsToWebCil" task failed unexpectedly~ Error. First it gets very slow in compiling and loading web page and finally it gets this error. Its impossible to resolve the error until I will uninstall Visual Studio and Install it again which takes longer. Please advise some solution or if its a bug then remove it as soon as possible. 
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "ConvertDllsToWebCil" task failed unexpectedly.
System.IO.IOException: The file exists.

at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
   at Microsoft.NET.Sdk.WebAssembly.ConvertDllsToWebCil.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder. <ExecuteInstantiatedTask>d__26.MoveNext()	RumuzSmartCateringAdmin	C:\Users\HP\.nuget\packages\microsoft.net.sdk.webassembly.pack\8.0.0-preview.5.23280.8\build\Microsoft.NET.Sdk.WebAssembly.Browser.targets	221
```
---
#### Feedback Bot on 6/29/2023, 06:23 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by danmoseley** [comment]
Are there 65,536 files named like tmpXXXX.tmp in the temp folder...

**Comment by danmoseley** [comment]
Probably fixed by https://github.com/dotnet/runtime/pull/86972

**Comment by radical** [comment]
@lambdageek what would be a good way to circumvent this for the user? Clear their temp dir?

**Comment by lambdageek** [comment]
Yea, just delete the temp files

**Comment by radical** [comment]
Closing this as fixed by https://github.com/dotnet/runtime/pull/86972 . And the fix should be available in preview6.
