### ISSUE TITLE
DoStackSnapshot behaves differently on Windows x86 and x64 WRT stack unwinding

### ISSUE THREAD

**Issue by urisimchoni** [dotnet/runtime#88463]
In a .Net profiler, if I call DoStackSnapshot from the context of a ExceptionUnwindFunctionLeave event, I get different result depending on whether the application (and profiler) is 32-bits or 64-bits.

Suppose I have the following:

```
void Func0()
{
  try
  {
    Func1();
  }
  catch(Exception e)
  {
  }
}

void Func1()
{
  return Func2();
}

void Func2()
{
  throw new NotImplementedException();
}
```

(let's assume inlining is disabled, and no tail calls are hapenning, e.g. by setting COMPlus_TailCallOpt=0)

Suppose I want to get a stack snapshot from the context of ExceptionUnwindFunctionLeave of Func1. Preparing for DoStackSnapshot(), I do native stack walking to find the top managed frame and thtat returns the context of Func2(). Then I call DoStackSnapshot().

In 64-bit mode, the first callback from DoStackSnapshot gives me the FunctionID of Func1 (meaning that it somehow taking the unwinding into account and giving me the "logical" top-of-stack).

In 32-bit mode, the first callback gives me Func2().

This happens on Windows, both Framework and .Net 6.

Is this something to be expected?

**Comment by tommcdon** [comment]
@davmason

**Comment by davmason** [comment]
Hi @urisimchoni,

I was trying to reproduce this and see Func2 for both x86 and x64. With the following test program I made a sample profiler that has a `DebugBreak()` inside `ExceptionUnwindFunctionLeaveHelper`
```
internal class Program
{
    static void Main(string[] args)
    {
        TestExceptions testExceptions = new TestExceptions();
        testExceptions.Func0();
    }
}

internal class TestExceptions
{
    [MethodImpl(MethodImplOptions.NoInlining)]
    public void Func0()
    {
        try
        {
            Func1();
        }
        catch (Exception e)
        {
            Console.WriteLine(e.ToString());
        }
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    public void Func1()
    {
        Func2();
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    public void Func2()
    {
        throw new NotImplementedException();
    }
}
```


I see the following stack with Func2 at frame 1A

```
1:003> k
 # ChildEBP RetAddr      
00 (Inline) --------     KERNELBASE!DebugBreak [minkernel\kernelbase\debug.c @ 143] 
01 0317d8b4 6f29294c     KERNELBASE!wil::details::DebugBreak+0x2 [onecore\internal\sdk\inc\wil\opensource\wil\result_macros.h @ 1836] 
02 0317d8b4 690316c1     CorProfiler!CorProfiler::ExceptionUnwindFunctionLeave+0xc [D:\git\ProfilerRepro\src\CorProfiler.cpp @ 85] 
03 0317d8e4 68f3105b     coreclr!EEToProfInterfaceImpl::ExceptionUnwindFunctionLeave+0x71 [D:\a\_work\1\s\src\coreclr\vm\eetoprofinterfaceimpl.cpp @ 4729] 
04 0317d8ec 68f2d70a     coreclr!ExceptionUnwindFunctionLeaveHelper+0xb [D:\a\_work\1\s\src\coreclr\inc\profilepriv.inl @ 1166] 
05 0317d900 68ef7881     coreclr!ProfControlBlock::DoProfilerCallbackHelper<int (__stdcall*)(ProfilerInfo *),long (__stdcall*)(EEToProfInterfaceImpl *)>+0x2a [D:\a\_work\1\s\src\coreclr\inc\profilepriv.h @ 284] 
06 (Inline) --------     coreclr!ProfControlBlock::DoOneProfilerIteration+0x3a [D:\a\_work\1\s\src\coreclr\inc\profilepriv.h @ 199] 
07 (Inline) --------     coreclr!ProfControlBlock::IterateProfilers+0x3a [D:\a\_work\1\s\src\coreclr\inc\profilepriv.h @ 207] 
08 (Inline) --------     coreclr!ProfControlBlock::DoProfilerCallback+0x3e [D:\a\_work\1\s\src\coreclr\inc\profilepriv.h @ 295] 
09 (Inline) --------     coreclr!ProfControlBlock::ExceptionUnwindFunctionLeave+0x3e [D:\a\_work\1\s\src\coreclr\inc\profilepriv.inl @ 1172] 
0a 0317d950 68ef6648     coreclr!EEToProfilerExceptionInterfaceWrapper::ExceptionUnwindFunctionLeave+0x74 [D:\a\_work\1\s\src\coreclr\vm\eetoprofinterfacewrapper.inl @ 151] 
0b 0317da18 68e8410b     coreclr!COMPlusUnwindCallback+0x628 [D:\a\_work\1\s\src\coreclr\vm\i386\excepx86.cpp @ 2875] 
0c (Inline) --------     coreclr!Thread::MakeStackwalkerCallback+0x108 [D:\a\_work\1\s\src\coreclr\vm\stackwalk.cpp @ 834] 
0d 0317dcdc 68e1eb1b     coreclr!Thread::StackWalkFramesEx+0x19c [D:\a\_work\1\s\src\coreclr\vm\stackwalk.cpp @ 914] 
0e 0317e010 68ea83db     coreclr!Thread::StackWalkFrames+0x8a [D:\a\_work\1\s\src\coreclr\vm\stackwalk.cpp @ 998] 
0f 0317e038 68ea837e     coreclr!UnwindFrames+0x3b [D:\a\_work\1\s\src\coreclr\vm\excep.cpp @ 2140] 
10 0317e14c 68ea8277     coreclr!COMPlusAfterUnwind+0xbd [D:\a\_work\1\s\src\coreclr\vm\i386\excepx86.cpp @ 474] 
11 0317e2c0 68ea7ebe     coreclr!CPFH_RealFirstPassHandler+0x3a0 [D:\a\_work\1\s\src\coreclr\vm\i386\excepx86.cpp @ 1244] 
12 (Inline) --------     coreclr!CPFH_FirstPassHandler+0xc6 [D:\a\_work\1\s\src\coreclr\vm\i386\excepx86.cpp @ 1353] 
13 0317e304 77ad8872     coreclr!COMPlusFrameHandler+0x13e [D:\a\_work\1\s\src\coreclr\vm\i386\excepx86.cpp @ 1748] 
14 0317e328 77ad8844     ntdll!ExecuteHandler2+0x26 [minkernel\ntos\rtl\i386\xcptmisc.asm @ 230] 
15 0317e3f0 77ab87b6     ntdll!ExecuteHandler+0x24 [minkernel\ntos\rtl\i386\xcptmisc.asm @ 190] 
16 0317ef68 75eb8a22     ntdll!KiUserExceptionDispatcher+0x26 [minkernel\ntos\rtl\i386\userdisp.asm @ 604] 
17 0317ef68 68ef5d54     KERNELBASE!RaiseException+0x62 [minkernel\kernelbase\xcpt.c @ 937] 
18 0317f014 68ef5bf6     coreclr!RaiseTheExceptionInternalOnly+0x146 [D:\a\_work\1\s\src\coreclr\vm\excep.cpp @ 2807] 
19 0317f0ac 08d272ca     coreclr!IL_Throw+0x86 [D:\a\_work\1\s\src\coreclr\vm\jithelpers.cpp @ 4119] 
1a 0317f0bc 08d27276     sampleapp!TestExceptions.Func2+0x3a
1b 0317f0c8 08d2720f     sampleapp!TestExceptions.Func1+0x1e [D:\git\ProfilerRepro\sampleapp\Program.cs @ 38] 
1c 0317f0f4 08d26f75     sampleapp!TestExceptions.Func0+0x2f [D:\git\ProfilerRepro\sampleapp\Program.cs @ 27] 
1d 0317f108 68f1c29f     sampleapp!Program.Main+0x45 [D:\git\ProfilerRepro\sampleapp\Program.cs @ 16] 
```

Is it possible your stackwalking is accidentally walking past the first managed frame in x86?

**Comment by urisimchoni** [comment]
Sorry for taking so long to respond, and I really appreciate the effort you put into this so far.

I think I may have failed to describe my issue, so I made a reproducer project that can be built with both x86 and x64, and you can see the results are different. The project is at https://gitlab.com/urisimchoni/stackwalkexception

The sample profiler is doing a stack snapshot at ExceptionUnwindFunctionLeave, and the sample code is pretty much the same as discussed above.

When running the x64 build, we get the following output:

```
7fff3ed996b8 -> TestCase.Program.Main
Hello, X64!
7fff3ed996d0 -> TestCase.Program.Func0
7fff3ed996e8 -> TestCase.Program.Func1
7fff3ed99700 -> TestCase.Program.Func2
ExceptionUnwindFunctionEnter 7fff3ed99700
ExceptionUnwindFunctionLeave 7fff3ed99700, 7fff3ed996e8, 7fff3ed996d0, 7fff3ed996b8, 0
ExceptionUnwindFunctionEnter 7fff3ed996e8
ExceptionUnwindFunctionLeave 7fff3ed996e8, 7fff3ed996d0, 7fff3ed996b8, 0
ExceptionUnwindFunctionEnter 7fff3ed996d0
```

...and when running the X86 build I get the following:

```
541ee6c -> TestCase.Program.Main
Hello, X86!
541ee7c -> TestCase.Program.Func0
541ee8c -> TestCase.Program.Func1
541ee9c -> TestCase.Program.Func2
ExceptionUnwindFunctionEnter 541ee9c
ExceptionUnwindFunctionLeave 541ee9c, 541ee8c, 541ee7c, 541ee6c, 0
ExceptionUnwindFunctionEnter 541ee8c
ExceptionUnwindFunctionLeave 541ee9c, 541ee8c, 541ee7c, 541ee6c, 0
ExceptionUnwindFunctionEnter 541ee7c
```

So what we can see is that whilst the x64 is presenting a stack snapshot that is consistent with the state of the exception handling, the x86 build shows the same stack throughout the exception handling (which is probably the "physical view" of the stack - you can't both do exception handling and pop the stack at the same time, I imagine the runtime is first doing all the exception handling and then is popping the stack).

What I've discovered in the meantime is that if I take a snapshot at ELT events during exception handling (that is, while running finally blocks), then I get the "logically correct" stack, and then as I move to another frame I get the "physical" stack again in the UnwindFunctionLeave event.

I hope this explains things better,
Uri.

**Comment by davmason** [comment]
Thanks for the further details @urisimchoni. It will be a little while longer before I am able to take another look, I do not know the answer off the top of my head and it will take some time to dig in. Thank you for your patience.

**Comment by tommcdon** [comment]
After careful consideration, we do not plan to action this particular item in this release. We will continue to evaluate it for future releases. Ideally, we would like to fix every issue and implement every idea people submit. Realistically, we cannot address every item.
