### ISSUE TITLE
MemoryMappedFile is slow on Linux, shm_open not used

### ISSUE THREAD

**Issue by AudriusButkevicius** [dotnet/runtime#88489]
### Description

Not sure if it belongs in this repo, but it's not clear who is responsible for the Linux artefacts in dotnetcli.azureedge.net so feel free to move.

cc @dotnet/area-infrastructure-libraries

Stable .NET runtime shipped in official Microsoft provided docker images, for both Debian and Ubuntu, is compiled without `HAVE_SHM_OPEN_THAT_WORKS_WELL_ENOUGH_WITH_MMAP`.

See: https://github.com/dotnet/runtime/blob/a2c19cd005a1130ba7f921e0264287cfbfa8513c/src/native/libs/System.Native/pal_io.c#L371-L393
which disables the use of shm_open.

This can be verified via objdump:
```
root@home ~/ # docker run -it --rm --entrypoint /bin/bash mcr.microsoft.com/dotnet/runtime:latest
root@98bb14a5b84c:/# ( apt -y update; apt -y install binutils ) &>/dev/null
root@98bb14a5b84c:/# objdump --disassemble=SystemNative_ShmOpen /usr/share/dotnet/shared/Microsoft.NETCore.App/*/libSystem.Native.so
<snip>
000000000000c7d0 <SystemNative_ShmOpen>:
    c7d0:       55                      push   %rbp
    c7d1:       48 89 e5                mov    %rsp,%rbp
    c7d4:       e8 57 8a 00 00          callq  15230 <__errno_location@plt>
    c7d9:       c7 00 5f 00 00 00       movl   $0x5f,(%rax)
    c7df:       48 c7 c0 ff ff ff ff    mov    $0xffffffffffffffff,%rax
    c7e6:       5d                      pop    %rbp
    c7e7:       c3                      retq
```
As you can see, it sets the errno to 95 and returns -1.

You can also verify the same issue in releases available in:
```
https://dotnetcli.azureedge.net/dotnet/Runtime/<version>/dotnet-runtime-<version>-linux-x64.tar.gz
```
which [seems to be what is being used to provide the runtime when building the images](https://github.com/dotnet/dotnet-docker/blob/5517616ffd9d5f163c89eb42cad27294ad1aaf8f/src/runtime/7.0/jammy/amd64/Dockerfile), and presumably are also used by CLI tooling to download runtimes.
 
We found this as apart of migrating some applications from Windows to Linux and observing very large performance regressions for applications that use MemoryMappedFile constructs, which we use to pass large amounts of data (gigabytes) between processes.

### Configuration

* Which version of .NET is the code running on?
tested on latest stable (7.0.8) + few versions of 6

* What OS version, and what distro if applicable?
Debian Bullseye, Ubuntu Jammy and Ubuntu Focal

* What is the architecture (x64, x86, ARM, ARM64)?
x64

Please note that this seems to be working on 8.0-preview images, but it's not clear if it's intentional fix or just a side-effect of how the previews are built

**Comment by hoyosjs** [comment]
This is expected - our portable builds have to work in all our supported platform. Notably, CentOS 7 fails the `HAVE_SHM_OPEN_THAT_WORKS_WELL_ENOUGH_WITH_MMAP`. Now that we dropped support on .NET 8, our build enabled the scenario.

**Comment by AudriusButkevicius** [comment]
Understood, feel free to close and lets wait for November.
