### ISSUE TITLE
Optimize `VectorXX` equality checks in JIT

### ISSUE THREAD

**Issue by anthonycanino** [dotnet/runtime#88490]
Currently, .NET libs prefer the following pattern to optimally check if the bitwise and between two vectors is equal to 0, which relies on an explicit `Avx` intrinsic (and requires the code to technically check first where the hardware supports `Avx`).

```C#
public static bool HasAllAscii0(Vector256<byte> v)
{
  return Avx.TestZ(Vector256.Create((byte)0x80), v);
}
```

which gives

```asm
vmovups  ymm0, ymmword ptr [reloc @RWD00]
vptest   ymm0, ymmword ptr [rcx]
sete     al
movzx    rax, al
```

whereas performing the similar check in a pure xplat manner

```C#
[MethodImpl(MethodImplOptions.NoInlining)]
public static bool HasAllAscii2(Vector256<byte> v)
{
  return (Vector256.Create((byte)0x80) & v) == Vector256<byte>.Zero;
}
```

gives

```asm
vmovups  ymm0, ymmword ptr [rcx]
vpand    ymm0, ymm0, ymmword ptr [reloc @RWD00]
vptest   ymm0, ymm0
sete     al
movzx    rax, al
```

The latter could be optimized to the former by the JIT, and would help reduce explicit intrinsic checks where the JIT can likely detect the pattern under the hood and optimize for the specific platform.

**Comment by EgorBo** [comment]
Related: https://github.com/dotnet/runtime/issues/87792

**Comment by Ruihan-Yin** [comment]
Hi @tannergooding, I suppose this optimization has been covered by your previous kmask PR, (see https://github.com/dotnet/runtime/blob/90df613abf7cd8e16e277b618c8ca96c3b7eaeaf/src/coreclr/jit/lowerxarch.cpp#L1735)

Can we close this issue as completed?

**Comment by Ruihan-Yin** [comment]
Hi @anthonycanino @tannergooding, seeing the results in the [link](https://godbolt.org/z/1Tozf6P1v), I think it is safe to close this issue as completed.

**Comment by xtqqczze** [comment]
Fixed by https://github.com/dotnet/runtime/pull/89059.
