### ISSUE TITLE
System.Reflection on NET Self Contained app fails with TypeLoadException (net fx based assembly)

### ISSUE THREAD

**Issue by wzm199309** [dotnet/runtime#88496]
### Description

After migrating to NET self-contained application, app's self-reflection call failed silently and one of its sub-call to assembly (net fx based)  failed with TypeLoadException.

### Reproduction Steps

code and function defined in assembly:

```
assembly name: Microsoft.WindowsAzure.xxx.xxx.EventSource.dll

namespace Microsoft.xxx.Tracing{
   public class EventSource : IDisposable
  {
        [SuppressMessage("Microsoft.Concurrency", "CA8001", Justification = "This does not need to be correct when racing with other threads")]
        public bool IsEnabled()
        {
            return m_eventSourceEnabled;
        }
   }
}
```

in the system reflection call on NET Self-contained app:
`       Type type1 = this.eventSourceDll.GetType(" Microsoft.xxx.Tracing.EventSource", throwOnError: true, ignoreCase: true);`

### Expected behavior

type get returned successfully

### Actual behavior

TypeLoadException raised:

System.TypeLoadException: Could not load type 'EventSource' from assembly 'Microsoft.WindowsAzure.xxx.xxx.EventSource, Version=2.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at System.Reflection.RuntimeAssembly.GetType(QCallAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive, ObjectHandleOnStack assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at Microsoft.SqlServer.Management.SqlIaaSHandlerData.KustoLogger.TryWriteLog(LogSource source, IaaSHandlerEventType eventType, LogLevel logLevel, String message)

### Known Workarounds

N/A

**Comment by teo-tsirpanis** [comment]
Can you open the compiled executable with [ILSpy](https://github.com/icsharpcode/ILSpy) to check if the type actually exists in the assembly? I suspect your app got trimmed and the `EventSource` type got removed. Were you getting warnings when you published the app?

**Comment by wzm199309** [comment]
its there, but for some reason the function just wont work, I know for self-contained app its system reflection might not load all required modules so sometimes issue can happen, should we load all references in this to make it work ?
![image](https://github.com/dotnet/runtime/assets/40444440/6bed6eb2-4079-4da4-a256-cf30a665ed80)



![image](https://github.com/dotnet/runtime/assets/40444440/674a7267-050d-4d7b-8502-5f479e8ded92)

**Comment by jkotas** [comment]
> should we load all references in this to make it work ?

It should not be required.

Could you please share exact repro steps for the problem? It is likely something else that you are doing that leads to this problem.

**Comment by wudragonfly** [comment]
Hi @jkotas This is Longfei. I'm working with @wzm199309 on the same project.
I have a more detailed repro for the issue. Here it goes.

From our self-contained .NET 6 application, we're calling a function `A.dll` via reflection.
```cs
public void FunctionToBeInvokedViaReflection(...)
{
// do something
}
```
In this function, it has referenced another struct `EventMetada`, and this is how it is defined:
```cs
internal struct EventMetadata
{
    public System.Diagnostics.Eventing.EventDescriptor Descriptor;
    // some other properties
}
```
This `System.Diagnostics.Eventing.EventDescriptor` belongs to `System.Core.dll`, which is part of the .NET framework runtime.

If we invoke the function `FunctionToBeInvokedViaReflection` directly from our self-contained .NET 6 extension, We'll get a `TypeLoadException` like this:

```cs
Exception: System.TypeLoadException
   at Package.A.FunctionToBeInvokedViaReflection(...)
``` 

Most likely it could not find the `EventDescriptor` type.

We tried to:
- copy this `System.Core.dll` in the same folder as `A.dll`
  - we still got `TypeLoadException` 
- copy this `System.Core.dll` to the same folder as our self-contained application
  - we still got `TypeLoadException` 
- Load this `System.Core.dll` using `Assembly.LoadFrom` in our self-contained application (the same way how we load `A.dll`)
  - we got a different `FileLoadException` as below:
```cs
System.IO.FileLoadException: 0x80131621
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Program.<Main>$(String[] args)
```
We are looking for any suggestions on how can we make this `System.Core.dll` and its type discoverable to our application.

**Comment by wzm199309** [comment]
Hi @jkotas we have a further investigation and find out clues why it fails, is there any way we can load all these dependencies into NET？

**Comment by jkotas** [comment]
> copy this System.Core.dll

System.Core.dll is part of .NET Core/.NET 5. You should not be copying System.Core.dll around. Copying System.Core.dll from .NET Framework into .NET Core app is unsupported and it is not going to work.

**Comment by wudragonfly** [comment]
Hi @jkotas Thanks for your reply. In such case, do you know if there is any workaround for our self-contained .NET 6 application to invoke `A.dll` via reflection?

**Comment by teo-tsirpanis** [comment]
`System.Diagnostics.Eventing.EventDescriptor` does not exist on .NET 6. Your app must migrate away from it.

**Comment by reflectronic** [comment]
The direct replacement for `EventProvider` is [EventSource](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/eventsource). But, if you do not want to rewrite this code, the implementation of `EventProvider` is simple enough that you could just paste it directly from the .NET Reference Source https://github.com/microsoft/referencesource/tree/master/System.Core/System/Diagnostics/Eventing.

Would it make sense to bring these APIs forward for .NET Framework porting? (previously discussed in https://github.com/dotnet/runtime/issues/30335)

**Comment by jkotas** [comment]
> Would it make sense to bring these APIs forward for .NET Framework porting? (previously discussed in https://github.com/dotnet/runtime/issues/30335)

The area owners decided that it is not worth it to port these APIs in #30335.

In general, we are done with bulk porting APIs from .NET Framework. Any new APIs (including suggestions for including old .NET Framework APIs) go through the regular API review process.
