### ISSUE TITLE
Is there a faster way than using Encoding.Unicode.GetChars(byte[])?

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#885]
Is there a faster way for getting unicode chars out of a byte array using Encoding.Unicode.GetChars? Unfortunately the Char struct is Utf16 otherwise we could use MemoryMarshal.Cast:

```
var span = bytes.AsSpan();
var chars = MemoryMarshal.Cast<byte, char>(span);
```

I assume the .NET does not have a primitive structure of unicode character yet (unlike the upcoming Utf8 struct)? What else could I use then?

**Comment by mikedn** [comment]
> Unfortunately the Char struct is Utf16

What do you mean by "Char struct is Utf16"?

> otherwise we could use MemoryMarshal.Cast:

Well, it the byte array really contains UTF16LE characters then you likely could do that.

It's not really clear what you want to achieve.

**Comment by Symbai** [comment]
> 
> 
> It's not really clear what you want to achieve.

Converting a byte array into an array of unicode characters using Encoding.Unicode.GetChars. But that allocates memory and costs too much performance. I was asking if anyone knows a faster way which may even allocate less memory.

**Comment by stephentoub** [comment]
There is an overload of GetChars that takes the destination span to write into; also one for pointers. Those overloads don't allocate.

**Comment by Symbai** [comment]
Nice, thank you.
