### ISSUE TITLE
[Design] .NET metrics naming standard

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#88515]
What should instruments and tags be named?

Options:
1. Follow event counters naming standard
2. Follow OTel semantic conventions naming standard

Needs to be decided before .NET 8 ships.

**Comment by gfoidl** [comment]
> Follow OTel semantic conventions naming standard

👍🏻 

When there's a standard, that's used across platforms, this one should be followed.
E.g. in a micro-service scenario environment where heterogenous technologies are used, it would be great to have one standard for metrics (OTel) which allows for easier creation and interpretion of dashboards, etc.

**Comment by noahfalk** [comment]
We are on a path that the new names would be based around OpenTelemetry semantic conventions and trying to nail down the details of what the names would be. Lots of discussion is happening right now over in https://github.com/lmolkova/semantic-conventions/pull/1. Feedback is welcome! (but the cutoff to get anything into RC1 is coming up quick)

**Comment by antonfirsov** [comment]
@tarekgh given that all the key points affecting 8.0 dotnet/runtime metrics have been decided in the discussions https://github.com/lmolkova/semantic-conventions/pull/1 and the metrics renaming PRs have been merged, I think this can be closed.

**Comment by tarekgh** [comment]
@noahfalk @JamesNK is there anything pending here?

**Comment by JamesNK** [comment]
This is done in dotnet/runtime. The counters in aspnetcore still have open PRs with renaming.

**Comment by tarekgh** [comment]
Ok, closing this one then. Will be good if you can link the PRs to this issue.
