### ISSUE TITLE
Run the ilc .sln project ILCompiler, and the object file it generates is garbled

### ISSUE THREAD

**Issue by tangyanzhi** [dotnet/runtime#88513]
### Description

I ran the ILCompiler project, generated the repro.obj file, opened repro.obj with Notepad and saw garbled characters, how to solve this problem?

repro.obj path is：...\artifacts\bin\repro\x64\Debug

![image](https://github.com/dotnet/runtime/assets/29683262/af7100ac-d0ee-4c5a-8c1a-37dfd3dab16c)

### Reproduction Steps

As shown above

### Expected behavior

I want to open repro.obj to see what's inside

### Actual behavior

I want to open repro.obj to see what's inside, but it's garbled

### Configuration

```
E:\Visual Studio Project\ConsoleApp9\ConsoleApp3>dotnet --info
.NET SDK:
 Version:   8.0.100-preview.5.23303.2
 Commit:    3fe444af72

 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.5.23303.2\

.NET workloads installed:

Host:
  Version:      8.0.0-preview.5.23280.8
  Architecture: x64
  Commit:       bc78804f5d

.NET SDKs installed:
  7.0.100 [C:\Program Files\dotnet\sdk]
  7.0.304 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.5.23303.2 [C:\Program Files\dotnet\sdk]
```

**Comment by MichalStrehovsky** [comment]
`.obj` file format is a binary file format, similar to `.exe`. One doesn't use Notepad to inspect either of those. You can e.g. use `dumpbin /all repro.obj` to look at the contents. Docs for dumpbin are here: https://learn.microsoft.com/en-us/cpp/build/reference/dumpbin-command-line?view=msvc-170. There are other tools that can open this too, searching the internet helps.

**Comment by tangyanzhi** [comment]
> `.obj` file format is a binary file format, similar to `.exe`. One doesn't use Notepad to inspect either of those. You can e.g. use `dumpbin /all repro.obj` to look at the contents. Docs for dumpbin are here: https://learn.microsoft.com/en-us/cpp/build/reference/dumpbin-command-line?view=msvc-170. There are other tools that can open this too, searching the internet helps.

Use .Net7, i can open this repro.obj file with Notepad, why not now?

**Comment by tangyanzhi** [comment]
> > > `.obj` file format is a binary file format, similar to `.exe`. One doesn't use Notepad to inspect either of those. You can e.g. use `dumpbin /all repro.obj` to look at the contents. Docs for dumpbin are here: https://learn.microsoft.com/en-us/cpp/build/reference/dumpbin-command-line?view=msvc-170. There are other tools that can open this too, searching the internet helps.
> > 
> > 
> > Use .Net7, i can open this repro.obj file with Notepad, why not now?
> 
> Can you post a screenshot of what you see?

yes ,A few previous images can be found

![image](https://github.com/dotnet/runtime/assets/29683262/1bc7499c-db81-45a7-85b9-0854054eb1d5)

![image](https://github.com/dotnet/runtime/assets/29683262/10fa182a-f925-4739-ab7b-ecf882e3a2da)

![image](https://github.com/dotnet/runtime/assets/29683262/2de302b8-7684-43f5-aaae-729ab834ee85)

**Comment by MichalStrehovsky** [comment]
> yes ,A few previous images can be found

This is not contents of the obj file opened in Notepad. This is a disassembly. Whatever produced the disassembly for the .NET 7 object file should be able to produce it for .NET 8 as well, but I don't know what you used on 7.

**Comment by tangyanzhi** [comment]
> > yes ,A few previous images can be found
> 
> This is not contents of the obj file opened in Notepad. This is a disassembly. Whatever produced the disassembly for the .NET 7 object file should be able to produce it for .NET 8 as well, but I don't know what you used on 7.

This is Notepad

Inside obj are assembly code and other debugging symbols for linking purposes.
I remember opening it with Notepad before, but now I don't know why it doesn't work.

**Comment by tangyanzhi** [comment]
> > yes ,A few previous images can be found
> 
> This is not contents of the obj file opened in Notepad. This is a disassembly. Whatever produced the disassembly for the .NET 7 object file should be able to produce it for .NET 8 as well, but I don't know what you used on 7.

Sorry, I remember, at that time I exported repro.obj to notepad via dumpbin, so the screenshot is notepad, but not obj files cannot be opened directly with notepad.

Thank you for your answer
