### ISSUE TITLE
HttpWebRequest.MaximumResponseHeadersLength Property doesn't support -1 contrary to the docs

### ISSUE THREAD

**Issue by anupamsr** [dotnet/runtime#88524]
### Description

This issue is same as https://github.com/dotnet/runtime/issues/27296 .

The doc at https://learn.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest.maximumresponseheaderslength says:

![image](https://github.com/dotnet/runtime/assets/301019/88dd31ab-b898-4076-96a6-ad74be990e18)

The setter is fine (as linked at https://github.com/dotnet/corefx/blob/72119235e294e711871cf453f2ffc66ba17ff23b/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs#L166 in previous bug report).

The problem shows when actually using the request: https://github.com/dotnet/runtime/blob/24d7f5a58ac4bcee1ec5197427068e437f19552f/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs#L488C32-L488C32

Using the example in the docs:
![image](https://github.com/dotnet/runtime/assets/301019/9d94edb7-416f-4c17-a580-a4b382b54029)

### Reproduction Steps

Change MaximumResponseHeadersLength  to -1

### Expected behavior

It should allow for unlimited response header length

### Actual behavior

It throws exception

### Regression?

Yes, since .NET Framework supports -1

### Known Workarounds

No idea

**Comment by ManickaP** [comment]
In .NET Framework, `WebRequest` had it's own HTTP implementation. In .NET Core +, it delegates to `HttpClient`, which by default uses `SocketsHttpHandler`.  `MaxResponseHeadersLength` of both `WinHttpHandler` as well as `SocketsHttpHandler` require positive value.

The best course of action for you is to juts stop using `-1`. Either leave it to the default 64kB, or set it up to int32.MaxValue if you really need "unlimited" response headers.

Also, `WebRequest` is deprecated and not maintained. It exists only for compat reasons. We highly recommend migrating to `HttpClient`.


Triage: We could make the `WebRequest.MaximumResponseHeadersLength` setter as strict as `SocketsHttpHandler.MaxResponseHeadersLength` , however that would introduce behavioral difference between framework and core. We also have other illogical behaviors in other compat-only classes (`ServicePoint` etc.), so I'm inclined to close this without any action.

**Comment by anupamsr** [comment]
I would still propose to fix the documentation so that this behavioral difference is pointed out.

**Comment by kunalspathak** [comment]
@karelz

**Comment by ManickaP** [comment]
> I would still propose to fix the documentation so that this behavioral difference is pointed out.

Feel free to update the docs, we'd appreciate it! They are here: https://github.com/dotnet/dotnet-api-docs/blob/049dcaabd31db9ea06d9854d64813d6e4b5cb1e9/xml/System.Net/HttpWebRequest.xml#L2455

**Comment by anupamsr** [comment]
Please review https://github.com/dotnet/dotnet-api-docs/pull/9137

**Comment by anupamsr** [comment]
SInce docs changes are merged, closing this issue.
