### ISSUE TITLE
Integrating .NET 8 WebAssembly project into the Angular app

### ISSUE THREAD

**Issue by socreative** [dotnet/runtime#88545]
Is there a nice way to incorporate the dotnet JS runtime into an existing angular project? 

I manage to do that with .NET 7 files but it was tricky still. When imported dotnet.js assumes it's run in a node environment so it tried loading fetching all files from the config .JSON using file system paths. I ended up messing about with the source code to rewrite the filesystem paths to URLs and it worked, but that seems like a dirty hack. 

With .NET 8 there are more that just dotnet.js files - I can see it's trying to dynamically import **dotnet.runtime.js** and **dotnet.native.js** - that is where Webpack is having issues with importing these.

**Comment by radical** [comment]
cc @pavelsavara @maraf

**Comment by pavelsavara** [comment]
hi @socreative, we are aware of it, we collect use cases here https://github.com/dotnet/runtime/issues/86162

I will close this issue as duplicate.

**Comment by pavelsavara** [comment]
I fixed webpack sample we have https://github.com/dotnet/runtime/pull/88907
It will pack only `dotnet.js` and load rest of it as separate files in parallel, which is likely faster than large bundle.

True single file solution would take more effort in linked issue.

**Comment by socreative** [comment]
Thanks. An npm package to replace dotnet.js would be an ideal scenario so it could be intergrated with front-end or node apps.
