### ISSUE TITLE
Exception quality of life improvements

### ISSUE THREAD

**Issue by strich** [dotnet/runtime#886]
Although I believe C# ranks fairly highly in actionable exception reporting, I do find that there is a lot of low hanging fruit that could measurably improve the quality of life for developers.

As an example, let's take one of the most famous of exceptions (**NullReferenceException**) and the first line of it's stacktrace:

> **NullReferenceException**: Object reference not set to an instance of an object
> Game.Model.Systems.Tiles.MapGen.SomeMethod(WallController wallPrefab, GameObject floorPrefab, Tile[,] tiles, MeshRenderer[,] floorMRs) (at Tiles/TileMapSystem.cs:235)

It's pretty clear where to look, but there are at least 4 variables I need to manually check for. In a perfect world I've written against defensive coding practices and I would have clear custom errors for each unassigned variable, but that's rarely the case. 

As a developer I now need to parse the code offline to find where I made the mistake or attach a debugger to inspect it live. This takes a couple of minutes to perform.

On the other hand, if the error was more like:

> **NullReferenceException**: **WallController** reference not set to an instance of an **WallController**
> Game.Model.Systems.Tiles.MapGen.SomeMethod(WallController wallPrefab, GameObject floorPrefab, Tile[,] tiles, MeshRenderer[,] floorMRs) (at Tiles/TileMapSystem.cs:235)

This would drastically decrease the time to root cause on average. I may not need to do any debugging. I imagine that on average, even this little bit of extra information would help a developer big such bugs orders of magnitude quicker.

AFAIK the runtime has this information available at the time. I might be interested in creating a pull request with the change, however for such a core area of .NET I currently have really no idea of the requirements. 

I'm also wondering if there is a key reason why work hasn't been put into this area of .NET?

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/coreclr/issues/25. It isn't an easy problem, unfortunately.
