### ISSUE TITLE
[wasm] Perf benchmark failures - `System.Text.Json` serializer related failures

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#88610]
Failing for AOT, and interpereter.

Benchmark: `Json_ToStream<Location>.SystemTextJson_Reflection`:

```
console.info: Initializing dotnet version 8.0.0-ci commit hash 36481bfd079093fe7d29ef024b1fb801e6c787fe
...
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotSupportedException: JsonTypeInfo metadata for type 'MicroBenchmarks.Serializers.Location' was not provided by TypeInfoResolver of type '[]'. If using source generation, ensure that all root types passed to the serializer have been annotated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically.
   at BenchmarkDotNet.Autogenerated.Runnable_7.Run(IHost host, String benchmarkName)
   at System.Reflection.MethodInvoker.Invoke(Object , IntPtr* , BindingFlags )
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object , IntPtr* , BindingFlags )
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args)
// AfterAll
test-main.js exiting dba61141-3925-4bba-8dea-e01f32679898.dll --benchmarkName with result -1
MONO_WASM: {"name":"ExitStatus","message":"Program terminated with exit(-1)","status":-1}
console.info: WASM EXIT -1
```

Benchmark `ColdStartSerialization<SimpleStructWithProperties>.NewCustomizedOptions`:
```
console.info: Initializing dotnet version 8.0.0-ci commit hash 36481bfd079093fe7d29ef024b1fb801e6c787fe
...
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: JsonSerializerOptions instance must specify a TypeInfoResolver setting before being marked as read-only.
   at System.Text.Json.Serialization.Tests.ColdStartSerialization`1[[MicroBenchmarks.Serializers.SimpleStructWithProperties, MicroBenchmarks, Version=42.42.42.42, Culture=neutral, PublicKeyToken=null]].Setup()
   at BenchmarkDotNet.Autogenerated.Runnable_142.Run(IHost host, String benchmarkName)
   at System.Reflection.MethodInvoker.Invoke(Object , IntPtr* , BindingFlags )
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object , IntPtr* , BindingFlags )
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args)
// AfterAll
test-main.js exiting dba61141-3925-4bba-8dea-e01f32679898.dll --benchmarkName with result -1
MONO_WASM: {"name":"ExitStatus","message":"Program terminated with exit(-1)","status":-1}
console.info: WASM EXIT -1
```

Changes 60799cc5...53a10ea1 (`[20230707.3](https://dev.azure.com/dnceng/internal/_build/results?buildId=2216705)` to https://dev.azure.com/dnceng/internal/_build/results?buildId=2217531&view=results). The pipeline had other failures earlier, so the starting hash could be a little off.

Sdk version changed from `8.0.100-preview.7.23357.5` to `8.0.100-preview.7.23359.2`.
.. which corresponds to https://github.com/dotnet/sdk/compare/f8336e3e35fd4b96d2b83214408b18be69f16eed...cfa4244f6d240c28bfa36f0d3103708dcb9fc3cc

`dotnet/performance` commit used for both was https://github.com/dotnet/performance/commit/a719dec8f44205f38538fde192e86b7c3a3c29b4

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by radical** [comment]
@eiriktsarpalis Any idea what might be wrong here?

**Comment by eiriktsarpalis** [comment]
Seems related to https://github.com/dotnet/runtime/pull/88480. These benchmarks target the reflection serializer and thus should never be running in trimmed applications or AOT. Were they even working in AOT before the feature switch got turned on?

**Comment by lewing** [comment]
opened https://github.com/dotnet/runtime/pull/88612

**Comment by radical** [comment]
`ColdStartSerialization` - this one seems to have been around since April, and I haven't seen it fail before this.

**Comment by lewing** [comment]
yeah I was reading across too many failures apologies for the noise
