### ISSUE TITLE
Json source generator does not produce a valid diagnostic for JsonConverterAttribute subtype with no constructor parameters

### ISSUE THREAD

**Issue by Khitiara** [dotnet/runtime#88638]
### Description

If using a subtype of `JsonConverterAttribute` which overrides the `CreateConverter` method but has no constructor parameters, [JsonSourceGenerator.Parser.cs#L1234](https://github.com/dotnet/runtime/blob/ec08e25eb78777f7047b9beafb4a5ce06ffdb58c/src/libraries/System.Text.Json/gen/JsonSourceGenerator.Parser.cs#L1234) produces an `IndexOutOfRangeException` instead of failing with an error diagnostic, which leads to errors involving unimplemented abstracts rather than expected information on the actual source of the error.

### Reproduction Steps

```cs
public class MyJsonConverterAttribute : JsonConverterAttribute {
    public override JsonConverter? CreateConverter(Type typeToConvert) => null; // actual converter logic would go here
}

public class MyType {
    [MyJsonConverter]
    public int Foo { get; init; }
}

[JsonSerializable(typeof(MyType))]
public partial class MyJsonContext : JsonSerializerContext;
```

### Expected behavior

An error diagnostic on the attribute usage.

### Actual behavior

Several unimplemented abstract method errors on the context class declaration and no generated code.

### Known Workarounds

Using a `JsonConverterFactory` implementation with the default `JsonConverterAttribute` sidesteps the issue neatly while also just working rather than being a compiler error, but with [third party libraries](https://github.com/nodatime/nodatime.serialization/blob/main/src/NodaTime.Serialization.SystemTextJson/NodaTimeDefaultConverterAttribute.cs) that may not be easy or possible.

### Configuration

.net 8 preview; I do not believe it to be specific to that configuration.

### Other information

Related issue: [nodatime.serialization#97](https://github.com/nodatime/nodatime.serialization/issues/97)

**Comment by eiriktsarpalis** [comment]
Ah yes, the `JsonConverterAttribute.CreateConverter` method was never supported by the source generator. I think it would make sense to at least handle that case gracefully and emit a diagnostic.

**Comment by Khitiara** [comment]
Plus, `JsonConverterFactory` covers most if not all of the bases youd want `JsonConverterAttribute.CreateConverter` for anyway
