### ISSUE TITLE
Inconsistent Result | [.Net Framework vs .Net Core] | Comparer<DateTime>.Default.Compare(DateTime.UtcNow, DateTime.UtcNow)

### ISSUE THREAD

**Issue by raziahmadansari** [dotnet/runtime#88654]
### Description

I have recently migrated the code base from .Net Framework to .Net Core as a result I came across an issue wherein I was passing predicate to LINQ query which compares the date and if the date is null then it fallbacks to DateTime.UtcNow.

```c#
using System;
using System.Collections.Generic;
using System.Linq;

public class Program
{
public static void Main()
{
var list = new List() { new Structure(new DateTime(2024,7,1)), new Structure(new DateTime(2023,7,1)), new Structure(new DateTime(2022,7,1)) };
var preProcessedList = list.OrderByDescending(o => o.ProcessedFrom ?? DateTime.UtcNow);
foreach (var structure in preProcessedList)
{
Console.WriteLine(structure.EffectiveFrom);
}
}
}

public class Structure {
public DateTime? ProcessedFrom { get; set; }
public DateTime EffectiveFrom { get; set; }
public Structure(DateTime effectiveFrom){
this.EffectiveFrom = effectiveFrom;
}
}
```

The same code reproduces different result in .Net FrameWork and .Net Core

Result in .Net Framework
![image](https://github.com/dotnet/runtime/assets/48851944/9b216019-17e9-4d46-9890-34ec60d2b38d)

Result in .Net Core
![image](https://github.com/dotnet/runtime/assets/48851944/d0106d70-43bd-4ec3-b304-2fd8d2acd276)

When I looked in the LINQ OrderByDescending source code, found that it is using the Default Comparator of type T, which in this case becomes Comparator<DateTime>.Default

Which internally uses Ticks for comparison and in .Net Framework those Ticks are getting cached but not in .Net Core as a result it is reproducing different result in both the environments.

[Sample - .Net Framework]
![image](https://github.com/dotnet/runtime/assets/48851944/2bf9ff73-1178-43f4-8769-a2a9709574f1)

[Sample - .Net Core]
![image](https://github.com/dotnet/runtime/assets/48851944/cb69dc04-c895-46c0-b61c-d398fc71f12d)

From the attached images, we can see that in case of
.Net Framework - it is giving 0
where in case of
.Net Core - it is giving -1

And also the values against Ticks are different in .Net Core.

-------------------------------------------------------------------------------------------------------------------------------------------

Just as a HOT-FIX
If you write it like this in .Net Core it'll give the same result.
![image](https://github.com/dotnet/runtime/assets/48851944/c3fb3610-07f1-453f-87d4-d82e8e096815)

Ticks for both the dates will become same as a result it'll produce the same result as of .Net Framwork.

### Reproduction Steps

Just compare the DateTime.UtcNow in both _.Net Framwork_ as well as in _.Net Core_.

### Expected behavior

In .Net Core while using DateTime.UtcNow in LINQ queries or inside any loop it should be consistent.

### Actual behavior

In .Net 6 the value of **DateTime.UtcNow** is different at each iteration while using it inside of a LINQ query whereas, in .Net Framework it is consistent across all the values.

**Comment by paulbartrum** [comment]
@raziahmadansari Why do you expect that DateTime.UtcNow is consistent in LINQ queries or inside a loop? As far as I can tell, it is documented just to return the current time. Which -- logically -- should always increase (but as the docs for UtcNow explain, may not happen due to precision limitations with the system timer). It seems to me that both the .NET framework and .NET core versions of UtcNow are working as documented, and that it's your assumption that UtcNow won't change which is the error. If you need UtcNow not to change, then just assign it to a local variable and then read from the local variable inside the loop/LINQ query.

**Comment by raziahmadansari** [comment]
Hi @paulbartrum , I completely understand your point and had the same thing in my mind as well
but I'm still not sure why the same LINQ query is behaving in different manner.

If you check in .Net Framework it is generating different output than .Net 6.

In -- Hot Fix -- , I've done the same thing, stored the value in local variable and used it.

**Comment by Clockwork-Muse** [comment]
> // DateTime.UtcNow accuracy on .NET Framework is ~16ms, this method
            // uses combination of Stopwatch and DateTime to calculate accurate UtcNow.

Looks like it did, though?  Or were you thinking of something else?

<hr /> 
As an aside, `OrderByDescending(...)` feels wrong here, as the most recently processed items will be processed again first.  If you have any sort of limitation on the items being processed, that will mean anything older eventually gets "stuck" not processing.  You could prevent that, and solve your issue here, by using a regular ascending sort and using `DateTime.Min` instead of the current time.

**Comment by danmoseley** [comment]
@raziahmadansari fwiw you can add \```c# above an \``` below the code to colorize it. I edited your top post.

**Comment by danmoseley** [comment]
I agree with @paulbartrum here this is simply because the time is more accurate in .NET Core. You should store the time outside of the loop (the Linq is a loop underneath)

**Comment by danmoseley** [comment]
incidentally @raziahmadansari just curious if you want to share more about your porting project. is this a large app, and what kind, have you hit any other issues, and do you have any perf comparison yet.

**Comment by paulbartrum** [comment]
> > // DateTime.UtcNow accuracy on .NET Framework is ~16ms, this method
> > // uses combination of Stopwatch and DateTime to calculate accurate UtcNow.
> 
> Looks like it did, though? Or were you thinking of something else?

I realised that the method the comment I linked to is referring to is actually `System.Diagnostics.Activity.GetUtcNow()`, not `DateTime.UtcNow`.

**Comment by raziahmadansari** [comment]
Hi @paulbartrum , I was doing some threshold testing and it turns out that every time you call `DateTime.UtcNow`, it gets evaluated on each call.

What I personally thought of is that when we pass any `predicate`, the values inside it gets stored as cache but it's not happening like that and with the previous comment that you've added explaining that it is calling a method - `System.Diagnostics.Activity.GetUtcNow()`.

> Now, it's more clear that a method is being called over time, so the values are getting changed.

Thanks @paulbartrum , @danmoseley  and @Clockwork-Muse for taking out time and providing such insightful informations.
