### ISSUE TITLE
[interp] inlining a wrapper with a MINT_LDSTR_TOKEN instruction aborts

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#88694]
If the runtime creates a wrapper whose entire body is just `mono_mb_emit_exception_full(mb, "System", "NotImplementedException", "some case in this wrapper is unimplemented")` then the interpreter will emit an `MINT_LDSTR_TOKEN` instruction for the `const char* msg` argument.

If this wrapper is then inlined into its caller, we end up here: 

https://github.com/dotnet/runtime/blob/eabea90040d359e9552e2821d6f7ab3e249a9a4d/src/mono/mono/mini/interp/interp.c#L5580-L5587

Normally, if the wrapper is not inlined `MonoMethod *method = frame->imethod->method` will be the wrapper, and we end up in the `method->wrapper_type != MONO_WRAPPER_NONE` case.

But if the wrapper is inlined we end up in the `else g_assert_not_reached()` case and crash.

Found in an early iteration of https://github.com/dotnet/runtime/pull/88626

**Comment by lambdageek** [comment]
Actually it might not have anythign to do with inlining.

It has to do with the fact that `imethod->method` is always the wrapped method, not the wrapper

https://github.com/dotnet/runtime/blob/14e8b829e56398e3a12a42ed59c0f82c785ea71d/src/mono/mono/mini/interp/transform.c#L11404-L11419

Here even if we do `method = nm` we haven't modified `imethod->method`. so even if we replaced some method by a wrapper, at execution time in `interp.c` we're not going to see that.

so if any of those wrappers used `MINT_LDSTR_TOKEN` they would have the same problem.

**Comment by BrzVlad** [comment]
I'm pretty sure, in general, for wrapper methods `imethod->method` points to a wrapper `MonoMethod`. What exactly is the repro for this issue ?
