### ISSUE TITLE
[mono][tests] Microsoft.Gen.OptionsValidation is failing on iOS platforms

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#88720]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=335352
Build error leg or test failing: Microsoft.Gen.OptionsValidation.Unit.Test.EmitterTests.ProduceDiagnosticFromOtherAssemblyTest
Pull request: https://github.com/dotnet/runtime/pull/88655

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "System.PlatformNotSupportedException : RemoteExecutor is not supported on this platform.",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=335352
**Error message validated:** `System.PlatformNotSupportedException : RemoteExecutor is not supported on this platform.`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 7/12/2023 8:47:12 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[334799](https://dev.azure.com/dnceng-public/public/_build/results?buildId=334799)|dotnet/runtime|[Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=334799&view=ms.vss-test-web.build-test-results-tab&runId=6988412&resultId=194381)|dotnet/runtime#88611|
|[335920](https://dev.azure.com/dnceng-public/public/_build/results?buildId=335920)|dotnet/runtime|[Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=335920&view=ms.vss-test-web.build-test-results-tab&runId=6979654&resultId=194384)||
|[335676](https://dev.azure.com/dnceng-public/public/_build/results?buildId=335676)|dotnet/runtime|[Microsoft.Gen.OptionsValidation.Unit.Test.EmitterTests.ProduceDiagnosticFromOtherAssemblyTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=335676&view=ms.vss-test-web.build-test-results-tab&runId=6970056&resultId=113914)|dotnet/runtime#88687|
|[335352](https://dev.azure.com/dnceng-public/public/_build/results?buildId=335352)|dotnet/runtime|[Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=335352&view=ms.vss-test-web.build-test-results-tab&runId=6958242&resultId=194381)|dotnet/runtime#88655|
|[335350](https://dev.azure.com/dnceng-public/public/_build/results?buildId=335350)|dotnet/runtime|[Microsoft.Gen.OptionsValidation.Unit.Test.EmitterTests.ProduceDiagnosticFromOtherAssemblyTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=335350&view=ms.vss-test-web.build-test-results-tab&runId=6955708&resultId=105318)|dotnet/runtime#88655|
|[335349](https://dev.azure.com/dnceng-public/public/_build/results?buildId=335349)|dotnet/runtime|[Microsoft.Gen.OptionsValidation.Unit.Test.EmitterTests.ProduceDiagnosticFromOtherAssemblyTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=335349&view=ms.vss-test-web.build-test-results-tab&runId=6955700&resultId=130997)|dotnet/runtime#88655|
|[335161](https://dev.azure.com/dnceng-public/public/_build/results?buildId=335161)|dotnet/runtime|[Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=335161&view=ms.vss-test-web.build-test-results-tab&runId=6954374&resultId=194381)|dotnet/runtime#88167|
|[335062](https://dev.azure.com/dnceng-public/public/_build/results?buildId=335062)|dotnet/runtime|[Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=335062&view=ms.vss-test-web.build-test-results-tab&runId=6952766&resultId=194381)|dotnet/runtime#88655|
|[335060](https://dev.azure.com/dnceng-public/public/_build/results?buildId=335060)|dotnet/runtime|[Microsoft.Gen.OptionsValidation.Unit.Test.EmitterTests.ProduceDiagnosticFromOtherAssemblyTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=335060&view=ms.vss-test-web.build-test-results-tab&runId=6948278&resultId=103053)|dotnet/runtime#88655|
|[335059](https://dev.azure.com/dnceng-public/public/_build/results?buildId=335059)|dotnet/runtime|[Microsoft.Gen.OptionsValidation.Unit.Test.EmitterTests.ProduceDiagnosticFromOtherAssemblyTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=335059&view=ms.vss-test-web.build-test-results-tab&runId=6948258&resultId=122644)|dotnet/runtime#88655|
|[334907](https://dev.azure.com/dnceng-public/public/_build/results?buildId=334907)|dotnet/runtime|[Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=334907&view=ms.vss-test-web.build-test-results-tab&runId=6944894&resultId=194381)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|4|11|11|

**Comment by kotlarmilos** [comment]
Should be fixed by https://github.com/dotnet/runtime/pull/88613.

**Comment by tarekgh** [comment]
Close this and watch if we see it again after the fix. Thanks @kotlarmilos for your follow up.
