### ISSUE TITLE
DateTime comparison with different Kind

### ISSUE THREAD

**Issue by ddrenkovski** [dotnet/runtime#88729]
### Description

I have been debugging an efcore about Entity property not being updated and it lead me to the System.Runtime DateTime class the == operator.
The comparison does not takes into account the Kind property of DateTime and not sure if that should be the case. IMHO local time and utc time should not be evaluate as the same even though the non TimeZone representation is equal.

### Reproduction Steps

Since I was debugging/[testing ](https://github.com/dotnet/efcore/blob/f3723a5ecc90d397b1ecdf0a42774b6bd8293298/test/EFCore.Tests/ChangeTracking/MemberEntryTest.cs#L72)the efcore I created a test to confirm my suspicious:

    [ConditionalFact]
    public void Can_get_and_set_current_value_property_date_time()
    {
        using var context = new FreezerContext();
        var entity = new Chunky();
        var today = DateTime.Now;
        context.Add(entity);
        var property = context.Entry(entity).Member("Birthday");
        Assert.Equal(DateTime.MinValue, property.CurrentValue);
        property.CurrentValue = today;
        Assert.Equal(today, property.CurrentValue);
        var utcToday = DateTime.SpecifyKind(today, DateTimeKind.Utc);

        //We assign a DateTime with different Kind
        //but efcore sees it as not modified value since the == operator of DateTime returns true for both today and utcToday
        property.CurrentValue = utcToday;   

        Assert.StrictEqual(utcToday, property.CurrentValue);
        Assert.Equal(utcToday.Kind, ((DateTime)property.CurrentValue).Kind); 
    } 

### Expected behavior

Assert.Equal(utcToday.Kind, ((DateTime)property.CurrentValue).Kind);  // this should be equal after property.CurrentValue = utcToday;

### Actual behavior

Assert.Equal(utcToday.Kind, ((DateTime)property.CurrentValue).Kind);  // this is not equal since it considers that DateTime.UtcNow and DateTime.Now are equal

### Known Workarounds

Override the `operator ==` method could be a possibility, but the impact might be huge
 public static bool operator ==(DateTime d1, DateTime d2) => ((d1._dateData ^ d2._dateData) << 2) == 0;

### Configuration

.Net 7 and .Net EFCore 7

**Comment by huoyaoyuan** [comment]
See also https://github.com/dotnet/runtime/issues/88309#issuecomment-1618598446.

**Comment by ddrenkovski** [comment]
Thank you @huoyaoyuan for pointing it out (didn't found that issue previously)

So it is by design comparison between DateTime, Will ask the EF Team if this is also considered as "by design" from their end, because DateTime is translated from DB values and those can be with or without timezones.

**Comment by Clockwork-Muse** [comment]
@ddrenkovski - If your database has an _offset_ (which is a distinct thing from a timezone), you should be using `DateTimeOffset`.

There are a couple of databases that (allegedly) support a zoned-type, but due to a couple of implementation reasons they're usually best avoided.
