### ISSUE TITLE
Use Python scripts to auto-generate native provider source code

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#88739]
Both `Mono `and `CoreCLR` runtimes use a [python script](https://github.com/dotnet/runtime/blob/main/src/coreclr/scripts/genEventing.py) to generate the source code for native providers (`dotnetruntime.cpp, dotnetruntimeprivate.cpp, dotnetruntimerundown.cpp, dotnetruntimestress.cpp, eventpipehelpers.cpp`) and header files (`clretwallmain.h, clreventpipewriteevents.h, clrxplatevents.h, etmdummy.h, ClrEtwAll.h`). 

NativeAOT currently only supports `Microsoft-Windows-DotnetRuntime` (`dotnetruntime.cpp`) and also only some basic runtime events. But it should move to the auto generation via python code and use an '`allowed-list`', similar to Mono, to include the events that are supported. This approach will avoid unintentional mistakes in code when writing the code manually, align with the pattern that the other 2 runtime follow, and more importantly, allow an easy mechanism to support new runtime events when they are added.

**Comment by MichalStrehovsky** [comment]
@LakshanF was this fixed in #92508?

**Comment by LakshanF** [comment]
Yep, this was done
