### ISSUE TITLE
Visual Studio 2022 v17.6.5 can not build dotnet 6.0.20, but v17.6.4 is OK.

### ISSUE THREAD

**Issue by sonyps5201314** [dotnet/runtime#88732]
### Description

F:\runtime-6.0.20\src\libraries\Common\src\Roslyn\GetBestTypeByMetadataName.cs(39,72): error CS0246: 未能找到类型或命名空间名“Compilation”(是否缺少 using 指令或程序集引用?) [F:\runtime-6.0.20\src\libraries\System.Text.Json\gen\System.Text.Json.SourceGeneration.Roslyn4.0.csproj]
F:\runtime-6.0.20\src\libraries\Common\src\Roslyn\GetBestTypeByMetadataName.cs(39,23): error CS0246: 未能找到类型或命名空间名“INamedTypeSymbol”(是否缺少 using 指令或程序集引用?) [F:\runtime-6.0.20\src\libraries\System.Text.Json\gen\System.Text.Json.SourceGeneration.Roslyn4.0.csproj]

### Reproduction Steps

@call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -no_logo
build.cmd -arch x64 -configuration Release

### Expected behavior

build ok

### Actual behavior

build faill.

**Comment by huoyaoyuan** [comment]
It looks like nuget restoring issue. Is there any nuget related output available?

**Comment by ViktorHofer** [comment]
This isn't actionable with the shared information. Can you please share the full build log if it happens again?

**Comment by sonyps5201314** [comment]
> This isn't actionable with the shared information. Can you please share the full build log if it happens again?

[full_build_log.txt](https://github.com/dotnet/runtime/files/12034539/full_build_log.txt)

**Comment by ViktorHofer** [comment]
Hmm I don't see anything obvious, nor do I see a restore error. Seems to be related to `System.Text.Json.SourceGeneration.Roslyn4.0.csproj` only so I'm moving this to the System.Text.Json area.

**Comment by eiriktsarpalis** [comment]
These appear to be logs building the runtime repo.

> System.Text.Json\gen\Reflection\FieldInfoWrapper.cs(15,33): error CS0246: The type or namespace name 'IFieldSymbol' could not be found (are you missing a using directive or an assembly reference?) [F:\runtime-6.0.20\src\libraries\System.Text.Json\gen

 These types were removed a while back in https://github.com/dotnet/runtime/pull/86334, which suggests to me that your local clone is using an older commit or contains local state. Running `git clean -fdx` before checking out the latest main might help.

**Comment by sonyps5201314** [comment]
> 这些似乎是构建运行时存储库的日志。
> 
> > System.Text.Json\gen\Reflection\FieldInfoWrapper.cs(15,33)：错误 CS0246：找不到类型或命名空间名称“IFieldSymbol”（您是否缺少 using 指令或程序集引用？）[F: \runtime-6.0.20\src\libraries\System.Text.Json\gen
> 
> 这些类型不久前在#86334中被删除，这表明您的本地克隆正在使用较旧的提交或包含本地状态。`git clean -fdx`在检查最新的 main 之前运行可能会有所帮助。

but I build is v6.0.20

**Comment by sonyps5201314** [comment]
> These appear to be logs building the runtime repo.
> 
> > System.Text.Json\gen\Reflection\FieldInfoWrapper.cs(15,33): error CS0246: The type or namespace name 'IFieldSymbol' could not be found (are you missing a using directive or an assembly reference?) [F:\runtime-6.0.20\src\libraries\System.Text.Json\gen
> 
> These types were removed a while back in #86334, which suggests to me that your local clone is using an older commit or contains local state. Running `git clean -fdx` before checking out the latest main might help.

but I build is v6.0.20

**Comment by eiriktsarpalis** [comment]
What is the commit hash you are trying to build? I'm pretty sure this is a local state issue with your machine, as anything else would probably have surfaced in our own CI builds. Try cleaning state from your local clone and local NuGet cache or try to reproduce on a different machine.

**Comment by sonyps5201314** [comment]
> What is the commit hash you are trying to build? I'm pretty sure this is a local state issue with your machine, as anything else would probably have surfaced in our own CI builds. Try cleaning state from your local clone and local NuGet cache or try to reproduce on a different machine.

Thanks, I have solve this problem by clean local NuGet cache.
