### ISSUE TITLE
[7.0] Globalization IcuAppLocalTests .TestIcuAppLocal test failure

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#88742]
### Error Blob

```json
{
  "ErrorMessage": "Failed to load app-local ICU",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Reproduction Steps

I only found this failure in a `mono` runtime config.

- PR: https://github.com/dotnet/runtime/pull/88652
- Queue: `Build windows x64 Release AllSubsets_Mono`
- Run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=336356&view=logs&j=585f1246-0618-5d47-ff3e-08c83309e2d2&t=5e10daf8-cc46-5bd4-2ab7-d28eafd857b5
- Log file: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-heads-release-70-2691c26cd50842a981/IcuAppLocal.Tests/1/console.99dad9bb.log?helixlogtype=result
- Callstack:
```
C:\h\w\9E650856\w\AF0A095B\e>"C:\h\w\9E650856\p\dotnet.exe" exec --runtimeconfig IcuAppLocal.Tests.runtimeconfig.json --depsfile IcuAppLocal.Tests.deps.json xunit.console.dll IcuAppLocal.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: IcuAppLocal.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  IcuAppLocal.Tests (found 1 test case)
  Starting:    IcuAppLocal.Tests (parallel test collections = on, max threads = 2)
Process terminated.
Failed to load app-local ICU: icuuc68.2.0.9.dll
    System.Globalization.Tests.IcuAppLocalTests.TestIcuAppLocal [FAIL]
      Exit code was -1073740791 but it should have been 42
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(239,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing)
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(57,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose()
        /_/src/libraries/System.Globalization/tests/IcuAppLocal/IcuAppLocal.cs(32,0): at System.Globalization.Tests.IcuAppLocalTests.TestIcuAppLocal()
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodInvoker.Mono.cs(33,0): at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
  Finished:    IcuAppLocal.Tests
=== TEST EXECUTION SUMMARY ===
   IcuAppLocal.Tests  Total: 1, Errors: 0, Failed: 1, Skipped: 0, Time: 7.563s
----- end Wed 07/12/2023  3:56:03.52 ----- exit code 1 ----------------------------------------------------------
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=336356
**Error message validated:** `Failed to load app-local ICU`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 7/12/2023 11:54:50 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[681837](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681837)|dotnet/runtime|[System.Globalization.Tests.IcuAppLocalTests.TestIcuAppLocal](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681837&view=ms.vss-test-web.build-test-results-tab&runId=16919780&resultId=103732)||
|[679420](https://dev.azure.com/dnceng-public/public/_build/results?buildId=679420)|dotnet/runtime|[System.Globalization.Tests.IcuAppLocalTests.TestIcuAppLocal](https://dev.azure.com/dnceng-public/public/_build/results?buildId=679420&view=ms.vss-test-web.build-test-results-tab&runId=16845856&resultId=100262)||
|[678355](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678355)|dotnet/runtime|[System.Globalization.Tests.IcuAppLocalTests.TestIcuAppLocal](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678355&view=ms.vss-test-web.build-test-results-tab&runId=16814594&resultId=100968)||
|[659984](https://dev.azure.com/dnceng-public/public/_build/results?buildId=659984)|dotnet/runtime|[System.Globalization.Tests.IcuAppLocalTests.TestIcuAppLocal](https://dev.azure.com/dnceng-public/public/_build/results?buildId=659984&view=ms.vss-test-web.build-test-results-tab&runId=16353386&resultId=103006)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|4|

**Comment by carlossanlop** [comment]
I'm having trouble getting the Known Build Error feature to capture the hits. But I linked the run and log file where I found the hit. Tagging @tarekgh since there was a recent globalization servicing change and it might be related to this failure.

**Comment by tarekgh** [comment]
@carlossanlop I'll look. Do you have a pointer to the linked failures that are not mentioned here? I just want to see if all failures are on `Windows-2012ServerR2-6.3.9600-SP0`

**Comment by carlossanlop** [comment]
According to the run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=336356&view=logs&j=585f1246-0618-5d47-ff3e-08c83309e2d2&t=5e10daf8-cc46-5bd4-2ab7-d28eafd857b5

These are the queues being used: `Windows.81.Amd64.Open+Windows.Amd64.Server2022.Open+Windows.11.Amd64.Client.Open`

**Comment by tarekgh** [comment]
@marek-safar could you get someone from Mono side to look at as this is a mono specific issue.

**Comment by tarekgh** [comment]
The Mono runtime failed to load the ICU native library. https://github.com/dotnet/runtime/blob/6166de40e07aaca44fe54e12546a667744630ecb/src/libraries/System.Private.CoreLib/src/System/Globalization/GlobalizationMode.Windows.cs#L45. So far, I am seeing it on Windows only with Mono runtime.

**Comment by carlossanlop** [comment]
New hit:

- PR: https://github.com/dotnet/runtime/pull/91916
- Queue: `Build windows x64 Release AllSubsets_Mono`
- Run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=404317&view=logs&j=bcc8d23b-52ae-5620-d7b1-d70522f650cc&t=d5d3d6c5-17db-557f-2299-a43d76756801&l=89
- Log: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-heads-release-70-8c26673f45f64addab/IcuAppLocal.Tests/1/console.529ef56b.log?helixlogtype=result
- Output:
```
===========================================================================================================

C:\h\w\B00D09D5\w\A667089E\e>"C:\h\w\B00D09D5\p\dotnet.exe" exec --runtimeconfig IcuAppLocal.Tests.runtimeconfig.json --depsfile IcuAppLocal.Tests.deps.json xunit.console.dll IcuAppLocal.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: IcuAppLocal.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  IcuAppLocal.Tests (found 1 test case)
  Starting:    IcuAppLocal.Tests (parallel test collections = on, max threads = 2)
Process terminated.
Failed to load app-local ICU: icuuc68.2.0.9.dll
    System.Globalization.Tests.IcuAppLocalTests.TestIcuAppLocal [FAIL]
      Exit code was -1073740791 but it should have been 42
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(239,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing)
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(57,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose()
        /_/src/libraries/System.Globalization/tests/IcuAppLocal/IcuAppLocal.cs(32,0): at System.Globalization.Tests.IcuAppLocalTests.TestIcuAppLocal()
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodInvoker.Mono.cs(33,0): at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
  Finished:    IcuAppLocal.Tests
=== TEST EXECUTION SUMMARY ===
   IcuAppLocal.Tests  Total: 1, Errors: 0, Failed: 1, Skipped: 0, Time: 29.869s
----- end Tue 09/19/2023 18:21:30.71 ----- exit code 1 ----------------------------------------------------------
2023-09-19T18:21:31.336Z	INFO   	run.py	run(48)	main	Beginning reading of test results.
2023-09-19T18:21:31.336Z	INFO   	run.py	__init__(42)	read_results	Searching 'C:\h\w\B00D09D5\w\A667089E\e' for test results files
2023-09-19T18:21:31.336Z	INFO   	run.py	__init__(48)	read_results	Found results file C:\h\w\B00D09D5\w\A667089E\e\testResults.xml with format xunit
2023-09-19T18:21:31.336Z	INFO   	run.py	__init__(42)	read_results	Searching 'C:\h\w\B00D09D5\w\A667089E\uploads' for test results files
2023-09-19T18:21:31.336Z	INFO   	run.py	packing_test_reporter(30)	report_results	Packing 1 test reports to 'C:\h\w\B00D09D5\w\A667089E\e\__test_report.json'
2023-09-19T18:21:31.336Z	INFO   	run.py	packing_test_reporter(33)	report_results	Packed 2641 bytes
['IcuAppLocal.Tests' END OF WORK ITEM LOG: Command exited with 0]
```

**Comment by vitek-karas** [comment]
@steveisok - this is on Windows which is weird. Not sure who "owns" this.  Also it's 7.0, so maybe we should close it if it's nowhere else.

**Comment by akoeplinger** [comment]
Build Analysis says this only happened on release/7.0 which isn't a thing anymore, closing.
