### ISSUE TITLE
[7.0] [Android] Test failure in X509Certificates.Tests.PfxTests - Algorithm 'RC2' is not supported on this platform

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#88747]
### Error Blob

```json
{
  "ErrorMessage": "Algorithm 'RC2' is not supported on this platform",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Reproduction Steps

- PR: The change containing all the internal->public commits: https://github.com/dotnet/runtime/pull/88652
- Queues: All android queues.
- Android artifacts: https://dev.azure.com/dnceng-public/public/_build/results?buildId=336356&view=ms.vss-test-web.build-test-results-tab&runId=6986794&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab&resultId=185211
- Log file: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-heads-release-70-a2ed2dda2c9a46af89/System.Security.Cryptography.X509Certificates.Tests/1/adb-logcat-net.dot.System.Security.Cryptography.X509Certificates.Tests-net.dot.MonoRunner.log?helixlogtype=result
- Callstack:
```
07-12 04:41:05.016 11331 11351 I DOTNET  : Failed tests:
07-12 04:41:05.037 11331 11351 I DOTNET  : 1) 	[FAIL] System.Security.Cryptography.X509Certificates.Tests.PfxTests.TestIterationCounter   Test name: System.Security.Cryptography.X509Certificates.Tests.PfxTests.TestIterationCounter(name: "Pkcs12MacosKeychainCreated", usesPbes2: False, blob: [48, 130, 9, 182, 2, ...], iterationCount: 4097)   Test case: System.Security.Cryptography.X509Certificates.Tests.PfxTests.TestIterationCounter
07-12 04:41:05.037 11331 11351 I DOTNET  :    Assembly:  [System.Security.Cryptography.X509Certificates.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]
07-12 04:41:05.037 11331 11351 I DOTNET  :    Exception messages: System.Exception : There's an error on certificate Pkcs12MacosKeychainCreated, see inner exception for details
07-12 04:41:05.037 11331 11351 I DOTNET  : ---- System.PlatformNotSupportedException : Algorithm 'RC2' is not supported on this platform.   Exception stack traces:    at System.Security.Cryptography.X509Certificates.Tests.PfxTests.TestIterationCounter(String name, Boolean usesPbes2, Byte[] blob, Int32 iterationCount) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/PfxTests.cs:line 487
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
07-12 04:41:05.037 11331 11351 I DOTNET  : ----- Inner Stack Trace -----
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.PasswordBasedEncryption.CreateRC2()
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.PasswordBasedEncryption.Decrypt(AlgorithmIdentifierAsn& algorithmIdentifier, ReadOnlySpan`1 password, ReadOnlySpan`1 passwordBytes, ReadOnlySpan`1 encryptedData, Span`1 destination)
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.Asn1.Pkcs12.PfxAsn.DecryptContentInfo(ContentInfoAsn contentInfo, UInt32& iterations)
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.Asn1.Pkcs12.PfxAsn.CountTotalIterations()
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.X509Certificates.X509Certificate.GetIterationCount(ReadOnlySpan`1 pkcs12)
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.X509Certificates.Tests.PfxTests.TestIterationCounter(String name, Boolean usesPbes2, Byte[] blob, Int32 iterationCount) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/PfxTests.cs:line 482
07-12 04:41:05.037 11331 11351 I DOTNET  :    Execution time: 0.0396158
07-12 04:41:05.037 11331 11351 I DOTNET  : 2) 	[FAIL] System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2.Import_IterationCounLimitNotExceeded_Succeeds   Test name: System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2.Import_IterationCounLimitNotExceeded_Succeeds(name: "Pkcs12MacosKeychainCreated", usesPbes2: False, blob: [48, 130, 9, 182, 2, ...], iterationCount: 4097)   Test case: System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2.Import_IterationCounLimitNotExceeded_Succeeds
07-12 04:41:05.037 11331 11351 I DOTNET  :    Assembly:  [System.Security.Cryptography.X509Certificates.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]
07-12 04:41:05.037 11331 11351 I DOTNET  :    Exception messages: System.Security.Cryptography.CryptographicException : PKCS12 (PFX) without a supplied password has exceeded maximum allowed iterations. See https://go.microsoft.com/fwlink/?linkid=2233907 for more information.
07-12 04:41:05.037 11331 11351 I DOTNET  : ---- System.PlatformNotSupportedException : Algorithm 'RC2' is not supported on this platform.   Exception stack traces:    at System.Security.Cryptography.X509Certificates.X509Certificate.EnforceIterationCountLimit(ReadOnlySpan`1 pkcs12, Boolean readingFromFile, Boolean passwordProvided)
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.X509Certificates.AndroidCertificatePal.FromBlob(ReadOnlySpan`1 rawData, SafePasswordHandle password, Boolean readingFromFile, X509KeyStorageFlags keyStorageFlags)
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.X509Certificates.AndroidCertificatePal.FromBlob(ReadOnlySpan`1 rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.X509Certificates.CertificatePal.FromBlob(ReadOnlySpan`1 rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(ReadOnlySpan`1 data)
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] data)
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData)
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2.Import(Byte[] blob) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/PfxIterationCountTests.X509Certificate2.cs:line 9
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests.Import_IterationCounLimitNotExceeded_Succeeds(String name, Boolean usesPbes2, Byte[] blob, Int64 iterationCount) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/PfxIterationCountTests.cs:line 34
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
07-12 04:41:05.037 11331 11351 I DOTNET  : ----- Inner Stack Trace -----
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.PasswordBasedEncryption.CreateRC2()
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.PasswordBasedEncryption.Decrypt(AlgorithmIdentifierAsn& algorithmIdentifier, ReadOnlySpan`1 password, ReadOnlySpan`1 passwordBytes, ReadOnlySpan`1 encryptedData, Span`1 destination)
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.Asn1.Pkcs12.PfxAsn.DecryptContentInfo(ContentInfoAsn contentInfo, UInt32& iterations)
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.Asn1.Pkcs12.PfxAsn.CountTotalIterations()
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.X509Certificates.X509Certificate.GetIterationCount(ReadOnlySpan`1 pkcs12)
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.X509Certificates.X509Certificate.EnforceIterationCountLimit(ReadOnlySpan`1 pkcs12, Boolean readingFromFile, Boolean passwordProvided)
07-12 04:41:05.037 11331 11351 I DOTNET  :    Execution time: 0.0029499
07-12 04:41:05.037 11331 11351 I DOTNET  : 3) 	[FAIL] System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2Collection.Import_IterationCounLimitNotExceeded_Succeeds   Test name: System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2Collection.Import_IterationCounLimitNotExceeded_Succeeds(name: "Pkcs12MacosKeychainCreated", usesPbes2: False, blob: [48, 130, 9, 182, 2, ...], iterationCount: 4097)   Test case: System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2Collection.Import_IterationCounLimitNotExceeded_Succeeds
07-12 04:41:05.037 11331 11351 I DOTNET  :    Assembly:  [System.Security.Cryptography.X509Certificates.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]
07-12 04:41:05.037 11331 11351 I DOTNET  :    Exception messages: System.Security.Cryptography.CryptographicException : PKCS12 (PFX) without a supplied password has exceeded maximum allowed iterations. See https://go.microsoft.com/fwlink/?linkid=2233907 for more information.
07-12 04:41:05.037 11331 11351 I DOTNET  : ---- System.PlatformNotSupportedException : Algorithm 'RC2' is not supported on this platform.   Exception stack traces:    at System.Security.Cryptography.X509Certificates.X509Certificate.EnforceIterationCountLimit(ReadOnlySpan`1 pkcs12, Boolean readingFromFile, Boolean passwordProvided)
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.X509Certificates.StorePal.FromBlob(ReadOnlySpan`1 rawData, SafePasswordHandle password, Boolean readingFromFile, X509KeyStorageFlags keyStorageFlags)
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.X509Certificates.StorePal.FromBlob(ReadOnlySpan`1 rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Import(ReadOnlySpan`1 rawData)
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Import(Byte[] rawData)
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2Collection.Import(Byte[] blob) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/PfxIterationCountTests.X509Certificate2Collection.cs:line 11
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests.Import_IterationCounLimitNotExceeded_Succeeds(String name, Boolean usesPbes2, Byte[] blob, Int64 iterationCount) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/PfxIterationCountTests.cs:line 34
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
07-12 04:41:05.037 11331 11351 I DOTNET  : ----- Inner Stack Trace -----
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.PasswordBasedEncryption.CreateRC2()
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.PasswordBasedEncryption.Decrypt(AlgorithmIdentifierAsn& algorithmIdentifier, ReadOnlySpan`1 password, ReadOnlySpan`1 passwordBytes, ReadOnlySpan`1 encryptedData, Span`1 destination)
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.Asn1.Pkcs12.PfxAsn.DecryptContentInfo(ContentInfoAsn contentInfo, UInt32& iterations)
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.Asn1.Pkcs12.PfxAsn.CountTotalIterations()
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.X509Certificates.X509Certificate.GetIterationCount(ReadOnlySpan`1 pkcs12)
07-12 04:41:05.037 11331 11351 I DOTNET  :    at System.Security.Cryptography.X509Certificates.X509Certificate.EnforceIterationCountLimit(ReadOnlySpan`1 pkcs12, Boolean readingFromFile, Boolean passwordProvided)
07-12 04:41:05.037 11331 11351 I DOTNET  :    Execution time: 0.0006872
07-12 04:41:05.038 11331 11351 I DOTNET  : 4) 	[FAIL] System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate.Import_IterationCounLimitNotExceeded_Succeeds   Test name: System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate.Import_IterationCounLimitNotExceeded_Succeeds(name: "Pkcs12MacosKeychainCreated", usesPbes2: False, blob: [48, 130, 9, 182, 2, ...], iterationCount: 4097)   Test case: System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate.Import_IterationCounLimitNotExceeded_Succeeds
07-12 04:41:05.038 11331 11351 I DOTNET  :    Assembly:  [System.Security.Cryptography.X509Certificates.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]
07-12 04:41:05.038 11331 11351 I DOTNET  :    Exception messages: System.Security.Cryptography.CryptographicException : PKCS12 (PFX) without a supplied password has exceeded maximum allowed iterations. See https://go.microsoft.com/fwlink/?linkid=2233907 for more information.
07-12 04:41:05.038 11331 11351 I DOTNET  : ---- System.PlatformNotSupportedException : Algorithm 'RC2' is not supported on this platform.   Exception stack traces:    at System.Security.Cryptography.X509Certificates.X509Certificate.EnforceIterationCountLimit(ReadOnlySpan`1 pkcs12, Boolean readingFromFile, Boolean passwordProvided)
07-12 04:41:05.038 11331 11351 I DOTNET  :    at System.Security.Cryptography.X509Certificates.AndroidCertificatePal.FromBlob(ReadOnlySpan`1 rawData, SafePasswordHandle password, Boolean readingFromFile, X509KeyStorageFlags keyStorageFlags)
07-12 04:41:05.038 11331 11351 I DOTNET  :    at System.Security.Cryptography.X509Certificates.AndroidCertificatePal.FromBlob(ReadOnlySpan`1 rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
07-12 04:41:05.038 11331 11351 I DOTNET  :    at System.Security.Cryptography.X509Certificates.CertificatePal.FromBlob(ReadOnlySpan`1 rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
07-12 04:41:05.038 11331 11351 I DOTNET  :    at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(ReadOnlySpan`1 data)
07-12 04:41:05.038 11331 11351 I DOTNET  :    at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] data)
07-12 04:41:05.038 11331 11351 I DOTNET  :    at System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate.Import(Byte[] blob) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/PfxIterationCountTests.X509Certificate.cs:line 9
07-12 04:41:05.038 11331 11351 I DOTNET  :    at System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests.Import_IterationCounLimitNotExceeded_Succeeds(String name, Boolean usesPbes2, Byte[] blob, Int64 iterationCount) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/PfxIterationCountTests.cs:line 34
07-12 04:41:05.038 11331 11351 I DOTNET  :    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
07-12 04:41:05.038 11331 11351 I DOTNET  : ----- Inner Stack Trace -----
07-12 04:41:05.038 11331 11351 I DOTNET  :    at System.Security.Cryptography.PasswordBasedEncryption.CreateRC2()
07-12 04:41:05.038 11331 11351 I DOTNET  :    at System.Security.Cryptography.PasswordBasedEncryption.Decrypt(AlgorithmIdentifierAsn& algorithmIdentifier, ReadOnlySpan`1 password, ReadOnlySpan`1 passwordBytes, ReadOnlySpan`1 encryptedData, Span`1 destination)
07-12 04:41:05.038 11331 11351 I DOTNET  :    at System.Security.Cryptography.Asn1.Pkcs12.PfxAsn.DecryptContentInfo(ContentInfoAsn contentInfo, UInt32& iterations)
07-12 04:41:05.038 11331 11351 I DOTNET  :    at System.Security.Cryptography.Asn1.Pkcs12.PfxAsn.CountTotalIterations()
07-12 04:41:05.038 11331 11351 I DOTNET  :    at System.Security.Cryptography.X509Certificates.X509Certificate.GetIterationCount(ReadOnlySpan`1 pkcs12)
07-12 04:41:05.038 11331 11351 I DOTNET  :    at System.Security.Cryptography.X509Certificates.X509Certificate.EnforceIterationCountLimit(ReadOnlySpan`1 pkcs12, Boolean readingFromFile, Boolean passwordProvided)
07-12 04:41:05.038 11331 11351 I DOTNET  :    Execution time: 0.0007288
07-12 04:41:05.044 11331 11351 D DOTNET  : assembly_preload_hook: System.Xml.ReaderWriter  /data/user/0/net.dot.System.Security.Cryptography.X509Certificates.Tests/files
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=336356
**Error message validated:** `Algorithm 'RC2' is not supported on this platform`
**Result validation: :x:** Known issue did not match with the provided build.
**Validation performed at:** 7/12/2023 4:33:41 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[338475](https://dev.azure.com/dnceng-public/public/_build/results?buildId=338475)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2Collection.ExportedPfxWithNullPassword_DecryptReturnsValidPaddingWithEmptyPassword](https://dev.azure.com/dnceng-public/public/_build/results?buildId=338475&view=ms.vss-test-web.build-test-results-tab&runId=7046244&resultId=181267)|dotnet/runtime#87319|
|[338204](https://dev.azure.com/dnceng-public/public/_build/results?buildId=338204)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2Collection.ExportedPfxWithNullPassword_DecryptReturnsValidPaddingWithEmptyPassword](https://dev.azure.com/dnceng-public/public/_build/results?buildId=338204&view=ms.vss-test-web.build-test-results-tab&runId=7037736&resultId=186445)||
|[338111](https://dev.azure.com/dnceng-public/public/_build/results?buildId=338111)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2Collection.ExportedPfxWithNullPassword_DecryptReturnsValidPaddingWithEmptyPassword](https://dev.azure.com/dnceng-public/public/_build/results?buildId=338111&view=ms.vss-test-web.build-test-results-tab&runId=7034874&resultId=178753)|dotnet/runtime#88811|
|[338000](https://dev.azure.com/dnceng-public/public/_build/results?buildId=338000)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2Collection.ExportedPfxWithNullPassword_DecryptReturnsValidPaddingWithEmptyPassword](https://dev.azure.com/dnceng-public/public/_build/results?buildId=338000&view=ms.vss-test-web.build-test-results-tab&runId=7031142&resultId=185387)|dotnet/runtime#87319|
|[337945](https://dev.azure.com/dnceng-public/public/_build/results?buildId=337945)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2Collection.ExportedPfxWithNullPassword_DecryptReturnsValidPaddingWithEmptyPassword](https://dev.azure.com/dnceng-public/public/_build/results?buildId=337945&view=ms.vss-test-web.build-test-results-tab&runId=7028480&resultId=178821)|dotnet/runtime#87319|
|[337765](https://dev.azure.com/dnceng-public/public/_build/results?buildId=337765)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2Collection.ExportedPfxWithNullPassword_DecryptReturnsValidPaddingWithEmptyPassword](https://dev.azure.com/dnceng-public/public/_build/results?buildId=337765&view=ms.vss-test-web.build-test-results-tab&runId=7023140&resultId=181575)|dotnet/runtime#88787|
|[337634](https://dev.azure.com/dnceng-public/public/_build/results?buildId=337634)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2Collection.ExportedPfxWithNullPassword_DecryptReturnsValidPaddingWithEmptyPassword](https://dev.azure.com/dnceng-public/public/_build/results?buildId=337634&view=ms.vss-test-web.build-test-results-tab&runId=7019556&resultId=181591)||
|[337208](https://dev.azure.com/dnceng-public/public/_build/results?buildId=337208)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2Collection.ExportedPfxWithNullPassword_DecryptReturnsValidPaddingWithEmptyPassword](https://dev.azure.com/dnceng-public/public/_build/results?buildId=337208&view=ms.vss-test-web.build-test-results-tab&runId=7009792&resultId=186430)|dotnet/runtime#88722|
|[337182](https://dev.azure.com/dnceng-public/public/_build/results?buildId=337182)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2Collection.ExportedPfxWithNullPassword_DecryptReturnsValidPaddingWithEmptyPassword](https://dev.azure.com/dnceng-public/public/_build/results?buildId=337182&view=ms.vss-test-web.build-test-results-tab&runId=7008052&resultId=180191)|dotnet/runtime#87319|
|[336543](https://dev.azure.com/dnceng-public/public/_build/results?buildId=336543)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2Collection.ExportedPfxWithNullPassword_DecryptReturnsValidPaddingWithEmptyPassword](https://dev.azure.com/dnceng-public/public/_build/results?buildId=336543&view=ms.vss-test-web.build-test-results-tab&runId=6993026&resultId=181554)|dotnet/runtime#88633|
|[336542](https://dev.azure.com/dnceng-public/public/_build/results?buildId=336542)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2Collection.ExportedPfxWithNullPassword_DecryptReturnsValidPaddingWithEmptyPassword](https://dev.azure.com/dnceng-public/public/_build/results?buildId=336542&view=ms.vss-test-web.build-test-results-tab&runId=6993036&resultId=178732)||
|[336405](https://dev.azure.com/dnceng-public/public/_build/results?buildId=336405)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2Collection.ExportedPfxWithNullPassword_DecryptReturnsValidPaddingWithEmptyPassword](https://dev.azure.com/dnceng-public/public/_build/results?buildId=336405&view=ms.vss-test-web.build-test-results-tab&runId=6988144&resultId=181195)|dotnet/runtime#88714|
|[334799](https://dev.azure.com/dnceng-public/public/_build/results?buildId=334799)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2Collection.ExportedPfxWithNullPassword_DecryptReturnsValidPaddingWithEmptyPassword](https://dev.azure.com/dnceng-public/public/_build/results?buildId=334799&view=ms.vss-test-web.build-test-results-tab&runId=6987752&resultId=181190)|dotnet/runtime#88611|
|[336279](https://dev.azure.com/dnceng-public/public/_build/results?buildId=336279)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2Collection.ExportedPfxWithNullPassword_DecryptReturnsValidPaddingWithEmptyPassword](https://dev.azure.com/dnceng-public/public/_build/results?buildId=336279&view=ms.vss-test-web.build-test-results-tab&runId=6985278&resultId=180137)|dotnet/runtime#87319|
|[335920](https://dev.azure.com/dnceng-public/public/_build/results?buildId=335920)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2Collection.ExportedPfxWithNullPassword_DecryptReturnsValidPaddingWithEmptyPassword](https://dev.azure.com/dnceng-public/public/_build/results?buildId=335920&view=ms.vss-test-web.build-test-results-tab&runId=6971388&resultId=186733)||
|[335676](https://dev.azure.com/dnceng-public/public/_build/results?buildId=335676)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2Collection.ExportedPfxWithNullPassword_DecryptReturnsValidPaddingWithEmptyPassword](https://dev.azure.com/dnceng-public/public/_build/results?buildId=335676&view=ms.vss-test-web.build-test-results-tab&runId=6965402&resultId=180133)|dotnet/runtime#88687|
|[335349](https://dev.azure.com/dnceng-public/public/_build/results?buildId=335349)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2Collection.ExportedPfxWithNullPassword_DecryptReturnsValidPaddingWithEmptyPassword](https://dev.azure.com/dnceng-public/public/_build/results?buildId=335349&view=ms.vss-test-web.build-test-results-tab&runId=6955700&resultId=181517)|dotnet/runtime#88655|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|17|17|

**Comment by vcsjones** [comment]
These tests should probably be marked as conditional with:

```C#
[ConditionalFact(typeof(PlatformSupport), nameof(PlatformSupport.IsRC2Supported))]
```
