### ISSUE TITLE
System.Text.Json.JsonProperty allocated a string in WriteTo()

### ISSUE THREAD

**Issue by mwadams** [dotnet/runtime#88767]
### Description

System.Text.Json.JsonProperty.WriteTo() uses the Name property to write name and value.

This realises the property name as a string, causing an allocation.

https://github.com/dotnet/runtime/blob/0a50fefb4f1eef9e6a2ddafc06d1acd6d189c9a2/src/libraries/System.Text.Json/src/System/Text/Json/Document/JsonProperty.cs#L120

It would be preferable to write the property name using the underlying JsonElement and avoid the allocation.

**Comment by eiriktsarpalis** [comment]
Thanks for reporting this. Would you be interested in contributing a PR that fixes the issue?

**Comment by karakasa** [comment]
i would try to implement a fix.
