### ISSUE TITLE
Conflict in Property Serialization with System.Text.Json When Hiding Base Interface Properties in Child Interface

### ISSUE THREAD

**Issue by AhsanJoyia** [dotnet/runtime#88774]
### Description

When running a newly created minimal WebAPI in 8.0.100-preview.6.23330.14, an InvalidOperationException occurs during property serialization with the System.Text.Json library. 

**Error Details**
An InvalidOperationException is thrown with the following message:
"The JSON property name for 'LearningProject.ResultWrappers.IResultWrapper1[WeatherForecast[]].payload' collides with another property." The exception occurs in the System.Text.Json library, specifically in the ThrowInvalidOperationException_SerializerPropertyNameConflict` method.

### Reproduction Steps

Create a new minimal WebAPI project.
Modify the WeatherForecastController to return WeatherForecast data wrapped in a ResultWrapper.
Build and run the WebAPI project.
Make a request to the WeatherForecast endpoint.
Observe the InvalidOperationException during property serialization

Here is the Code:
```C#
namespace LearningProject 
{
    public class WeatherForecast
    {
        public static IResultWrapper<WeatherForecastInfo[]> ReturnResult(string[] summaries)
        {
            var result = Enumerable.Range(1, 5).Select(index =>
                    new WeatherForecastInfo
                    (
                        DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
                        Random.Shared.Next(-20, 55),
                        summaries[Random.Shared.Next(summaries.Length)]
                    ))
                    .ToArray();
            return ResultWrapper.Success(result);
        }
    }
    public interface IResultWrapper
    {
        object? Payload { get; set; }
        object? Errors { get; set; }
    }
    public interface IResultWrapper<T> : IResultWrapper
    {
        new T? Payload { get; set; }
        new T? Errors { get; set; }
    }
    public class Success<T> : IResultWrapper<T>
    {

        public Success(T? payload = default)
        {
            Payload = payload;
        }

        public T? Payload { get; set; }
        public T? Errors { get; set; }

        object? IResultWrapper.Payload { get; set; }
        object? IResultWrapper.Errors { get; set; }
    }

    public static class ResultWrapper
    {
        public static IResultWrapper<TPayload> Success<TPayload>(TPayload? payload)
        {
            return new Success<TPayload>(payload);
        }
        public static IResultWrapper Success<TPayload>(object? payload)
        {
            return new Success<object>(payload);
        }
    }
}
```

### Expected behavior

The System.Text.Json library should handle serialization correctly when hiding base interface properties in the child interface, as it did in .NET 7.

### Actual behavior

In 8.0.100-preview.6.23330.14, the System.Text.Json library not handling serialization correctly when hiding base interface properties in the child interface.

### Configuration

**Development Environment**

**Operating System**
Windows 11

**.NET Runtime Version**
8.0.100-preview.6.23330.14

**API**
Minimal API

**Browser**
Microsoft Edge

**Comment by eiriktsarpalis** [comment]
This is caused by the recently added support for [interface hierarchies](https://github.com/dotnet/runtime/pull/78788) (until .NET 7 properties of base interfaces were being ignored). Minimal reproduction:

```C#
using System.Text.Json;

IDerived value = new DerivedImpl();
Console.WriteLine(JsonSerializer.Serialize(value));

public interface IBase
{
    object? Value { get; set; }
}

public interface IDerived : IBase
{
    new int Value { get; set; }
}

public class DerivedImpl : IDerived
{
    object? IBase.Value { get; set; } = 0;
    public int Value { get; set; } = 1;
}
```

This is caused by the conflict resolution algorithm being too conservative for the case of interfaces due to the possibility of diamonds:

https://github.com/dotnet/runtime/blob/b9c99648783d0c28afdee394a93516c0bd228165/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs#L1389-L1398

Even though this is by design, I think we could relax the check to avoid this particular regression.

**Comment by eiriktsarpalis** [comment]
@AhsanJoyia in the meantime, you can work around the issue by applying the `[JsonIgnore]` attribute on the properties of the base interface.

**Comment by AhsanJoyia** [comment]
@eiriktsarpalis Thank you sincerely for your invaluable assistance! I genuinely appreciate your efforts in guiding me towards understanding the cause of this issue. Yes, I had already applied the [JsonIgnore] attribute before raising this matter on GitHub.
