### ISSUE TITLE
NativeAOT EventPipe require multi byte to wide char support

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#88785]
EventPipe [ep_rt_utf8_to_utf16le_string](https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/Runtime/eventpipe/ep-rt-aot.h#L1380) and [ep_rt_utf16_to_utf8_string](https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/Runtime/eventpipe/ep-rt-aot.h#L1448) implementation currently only supports ASCII conversions. These need to support multi-byte conversions.

This recent [work ](https://github.com/dotnet/runtime/pull/85558/)looks promising in terms of leveraging common code for this purpose

**Comment by am11** [comment]
I think it is possible to make EP directly call `minipal_convert_utf8_to_utf16` and `minipal_convert_utf16_to_utf8` APIs without duplicating the calling code for each runtimes. Currently, EP for both both coreclr and mono end up calling exactly the same minipal APIs via different wrappers; PAL or giconv.

**Comment by am11** [comment]
I think it is possible to make EP directly call `minipal_convert_utf8_to_utf16` and `minipal_convert_utf16_to_utf8` APIs without duplicating the calling code for each runtimes. Currently, EP for both coreclr and mono end up calling exactly the same minipal APIs via different wrappers; PAL or giconv.
