### ISSUE TITLE
PublishAot should respect DebugSymbols/DebugType

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#88780]
In trying to make a minimally sized NativeAOT app in a Linux Docker container, the developer typically doesn't want the native symbols in their app folder. These symbols can really bloat the size of their container.

In trying to accomplish this, one way I thought to do it was to set either:

* `/p:DebugSymbols=false`
* `/p:DebugType=none`

However, neither of these properties seem to affect the published output. In both cases I get a `.dbg` file, bloating my container.

We should respect one or both of these properties in PublishAot so container developers can easily opt out of debug symbols in their published apps.

cc @richlander @DamianEdwards

**Comment by MichalStrehovsky** [comment]
Try `/p:NativeDebugSymbols=false`. We don't officially support/document it because doing this means you can't even get a stack in a debugger and the experience is _much_ worse than just not having managed symbols.

**Comment by am11** [comment]
I have a `RUN rm output/*.dbg` line in my builder container. It is possible to conditionally copy the dbg file with something more explicit like `CopyNativeSymbolsToOutput=false`.

**Comment by eerhardt** [comment]
> Try `/p:NativeDebugSymbols=false`. We don't officially support/document it because doing this means you can't even get a stack in a debugger and the experience is _much_ worse than just not having managed symbols.

Hmm, that doesn't appear to work on Linux. I've set:

```xml
    <PublishAot>true</PublishAot>
    <DebugSymbols>false</DebugSymbols>
    <NativeDebugSymbols>false</NativeDebugSymbols>
    <DebugType>none</DebugType>
```

in my .csproj, rebuild my docker container, and the .dbg file is still there.

However, on Windows the above settings will cause the .pdb file to no longer be emitted to the publish folder.

**Comment by am11** [comment]
StripSymbols and NativeDebugSymbols are not the same things https://github.com/dotnet/runtime/pull/70233#issuecomment-1146954090. Former generates the symbols and strips to a separate file (which we can control), and latter does not generate the debug symbols.

**Comment by MichalStrehovsky** [comment]
> in my .csproj, rebuild my docker container, and the .dbg file is still there.

Is the size of the dbg file still the same? We do condition this in the linux linker: https://github.com/dotnet/runtime/blob/6bcc188bcef478be5efff61f54f7a61bb487dfa0/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Unix.targets#L114

But as @am11 said, we'll probably still run objcopy to create the dbg file but it probably won't have anything. Maybe we shouldn't run it.

**Comment by eerhardt** [comment]
I can verify tomorrow when I’m at my desktop, but the .dbg file was still 2x the size of my executable.

**Comment by am11** [comment]
Size of .dbg for `dotnet new api --aot` template app on Alpine arm64:

* Without `NativeDebugSymbols=false`: 28.8M 
* With `NativeDebugSymbols=false`: 16.0M

executable size remained the same (10.2M).

I think a separate property like `CopyNativeSymbolsToPublishDir=false` would be better to keep their meaning separate, so user can optionally upload the dbg to their production environment when diagnostics are needed; without rebuilding the app with `NativeDebugSymbols=true`.

**Comment by eerhardt** [comment]
> I think a separate property 

I think we might have too many properties already. `DebugSymbols` and `DebugType` is confusing by themselves. Add to it `NativeDebugSymbols` as well makes it worse.

> so user can optionally upload the dbg to their production environment when diagnostics are needed

See https://github.com/dotnet/sdk/issues/33476 for more ideas about this.

**Comment by am11** [comment]
`NativeDebugSymbols` controls whether or not we should build with debug symbols (`cc -g`). To reverse this decision, we have to rebuild/republish the app.

`StripSymbols` controls whether or not we should strip the symbols. On Linux, we additionally execute a command to create the .dbg file. We can reverse it with `eu-unstrip`  tool to join the files. On macOS, the .dwarf file is always created by the stripping tool.

I agree with @MichalStrehovsky that we should definitely infer `StripSymbols=false` when `NativeDebugSymbols=false` is specified (this is a bug in the existing .targets). However, I was suggesting we should also allow "skip copying debug file to publish directory" for `StripSymbols=true` and `NativeDebugSymbols=true` by means of a separate property, as symbols file can be pulled on-demand for debugging the published app (which, IMO, is a useful ability to keep).

**Comment by MichalStrehovsky** [comment]
> I think we might have too many properties already. DebugSymbols and DebugType is confusing by themselves. Add to it NativeDebugSymbols as well makes it worse.

I looked again and we default NativeDebugSymbols to whatever DebugSymbols/DebugType say:

https://github.com/dotnet/runtime/blob/9fc8cb91709986421e14b43e27d143812494a1d8/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets#L25

So this should be fine.

> I agree with @MichalStrehovsky that we should definitely infer `StripSymbols=false` when `NativeDebugSymbols=false` is specified (this is a bug in the existing .targets). However, I was suggesting we should also allow "skip copying debug file to publish directory" for `StripSymbols=true` and `NativeDebugSymbols=true` by means of a separate property, as symbols file can be pulled on-demand for debugging the published app (which, IMO, is a useful ability to keep).

Would it make sense to still strip, but don't put them into dbg file? If I understand it correctly, StripSymbols will strip both the debug information and other symbols. We put them into a separate file for debuggability of the output. But if the user doesn't want debuggability of the output (they specified `NativeDebugSymbols=false`) we could just drop it all on the floor. (Basically, I want to avoid `NativeDebugSymbols=true` growing the size of the output, which I assume would happen if we make it imply StripSymbols=false.)

**Comment by am11** [comment]
When `NativeDebugSymbols=false`, we want to build without `cc -g`, strip the binary (disregarding `StripSymbols` prop value, false or true alike) without creating the symbols file.  Otherwise, respect the properties. Is this correct?

(we _may_ need to actually delete the symbols file on macOS, as part of app publishing but that's just a tiny implementation detail 😅)

**Comment by MichalStrehovsky** [comment]
> When `NativeDebugSymbols=false`, we want to build without `cc -g`, strip the binary (disregarding `StripSymbols` prop value, false or true alike) without creating the symbols file. Otherwise, respect the properties. Is this correct?
> 
> (we _may_ need to actually delete the symbols file on macOS, as part of app publishing but that's just a tiny implementation detail 😅)

I think that should work as I would expect, yes.
