### ISSUE TITLE
SslStream now does zero byte read of InnerStream which breaks WCF

### ISSUE THREAD

**Issue by mconnew** [dotnet/runtime#88792]
### Description

The change made in #87563 causes SslStream to execute a read of zero bytes on the InnerStream. This breaks the semantics of the Stream class. When calling any of the variants of Read on a Stream, the return value is overloaded in meaning. If it's non-zero it returns how many bytes were actually read. But if it returns a 0, that indicates you've reached the end of the Stream. In the case of a Stream representing a network connection, this means the connection was closed.  

Streams can be wrapped in layers, just like SslStream wraps an inner stream. If you have an intermediate Stream between SslStream and the actual network stream, if it were to pass through the zero byte read, the code which interprets the return value wouldn't be able to know whether the inner stream was closed or not and would interpret zero bytes returned as the connection was closed.  

WCF has multiple utility Stream implementations which wrap the connection Stream for various reasons. One example is a Stream which counts the bytes received and fails the request if too many bytes have been sent. Each of these utility streams, as well as our actual networking Stream (we don't just use the built in ones as we need to toggle nagle on and off for performance reasons) do argument validation and throw an exception if you pass a zero length input into their Read methods.

### Reproduction Steps

```c#
public class MyStream : Stream
{
    private bool _eof;
    private Stream _innerStream;

    public MyStream(Stream innerStream)
    {
        _innerStream = innerStream;
    }

    public override int Read(byte[] buffer, int offset, int count)
    {
        ThrowIfEof();
        int bytesRead = innerStream.Read(buffer, offset, count);
        if (bytesRead == 0) _eof = true;
        return bytesRead;
    }

    private void ThrowIfEof()
    {
        if (_eof) throw new ObjectDisposedException();
    }
}
```

If you used a stream similar to the code above (with the rest of the methods implemented), it wouldn't work with SslStream as the zero byte read would cause the Read to consider the inner stream to have reached EOF and any subsequent calls will throw ODE.

### Expected behavior

SslStream only calls Read with a buffer which is at least 1 byte long.

### Actual behavior

SslStream calls Read with an empty buffer.

### Regression?

This issue only appeared in a recent preview release of .NET 8

### Known Workarounds

Add complicated logic to all wrapping Stream implementations where it only considers 0 bytes read to mean you've reached the end of the Stream when a non-zero length buffer has been passed in. This adds extra conditions and branching code in lots of places through our code base.

### Other information

This is the specific line of code that WCF hit, but there might be other places this happens.
https://github.com/dotnet/runtime/blob/d59af2cf097acb100ad6a9cba652be34be6f4a2e/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.IO.cs#L708

**Comment by mconnew** [comment]
Marked as blocking as this breaks the existing WCF Client packages.

**Comment by MihaZupan** [comment]
Reads on streams with length=0 buffers are valid. If your stream implementations are throwing for such inputs, then that validation is too strict.

Correct stream implementations either:
a) Check for EOF by checking both `count == 0 && bytesRead == 0` (this is the preferred option)
b) Check for `count == 0` at the start and immediately return back 0, effectively disabling zero-byte reads

**Comment by mconnew** [comment]
@MihaZupan, that's not what the documentation for Stream.Read says. From the remarks of the [documentation for Stream.Read(Span\<Byte\>)](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.read?view=net-7.0#system-io-stream-read(system-span((system-byte)))):

> The implementation will block until at least one byte of data can be read, in the event that no data is available. [Read](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.read?view=net-7.0) returns 0 only when there is no more data in the stream and no more is expected (such as a closed socket or end of file).

The Async variants behave the same as the sync variants except instead of blocking, they return an uncompleted Task/ValueTask, and they can be cancelled using a CancellationToken. But the semantics for writing/reading are the same. If you want proof of this, take a look at this code:
https://github.com/dotnet/runtime/blob/d59af2cf097acb100ad6a9cba652be34be6f4a2e/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs#L246

When you derive from Stream but *don't* override BeginRead/EndRead or ReadAsync, the default implementations just wrap a call to the synchronous Read method. All the APM and Async methods are virtual, only the sync methods are abstract. This means the async variants have the same semantics as the synchronous API because they fall back to it when there isn't an explicit async version. In addition, [this overload of ReadAsync](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.readasync?view=net-7.0#system-io-stream-readasync(system-byte()-system-int32-system-int32)) does state in its documentation that a value of 0 indicates you reached the end of the stream.  

For the implementation to block (or go async) until at least one byte of data can be read, the only way for this to happen is if a non-zero length buffer is passed in. A Stream following the documented behavior has no way to return from/complete a Read call when a 0 length buffer has been passed in unless it reaches the end of the stream.   

The documentation states that returning a zero means there is no more data in the stream. When SslStream makes a read call with a zero length buffer, the only value that can be returned is zero. The documentation says this is to be interpreted as there's no more data in the stream and no more is expected. This means SslStream should behave consistent with the inner streams socket having been closed as that's what the inner stream indicated. The inner stream may have been closed, and it just informed SslStream of this fact. But instead of interpreting it this way, it's going to make another call. This doesn't make sense according to the documentation as the inner stream just informed SslStream that there's no more data.

**Comment by MihaZupan** [comment]
In this case, it looks like the documentation is wrong/misleading.
It should be updated to indicate that
- empty buffers / count=0 are valid inputs
- a 0 return value indicates an EOF only if the provided buffer was not empty

As for what are the actual expectations of `Stream` (at least for everything in the networking stack):
- If you give us an empty buffer, we will try to block/wait until data is actually available. For most stream implementations this means passing the input buffer directly down to the inner stream. That is, if you call `ReadAsync(Memory<byte>.Empty)` on `SslStream`, `NetworkStream` or any `HttpContent` stream, the call will not return until data is available or we've hit EOF.
- Readers (e.g. HttpClient/SslStream) may issue zero-byte reads to other streams. The expectation is  that those streams will either
  - block until data is actually available and then return 0. To see if we hit an EOF, the reader will issue another read with a non-empty buffer
  - return 0 right away before doing anything else. This means that the reader will follow up with a non-zero read immediately.

Using zero-byte reads is not unique to SslStream. For example, HttpClient, Kestrel, YARP, and gRPC will all issue zero-byte reads on transport streams.

**Comment by mconnew** [comment]
In-box streams supporting an undocumented zero byte read mechanism to wait until data is available doesn't make it valid to make a zero byte read to a 3rd party Stream. Especially when the existing documentation implies this isn't a valid thing to do.  

It's like with network specs, best practice is you are forgiving in what you accept, but strict in what you send to others. When applied to documented API's which can be implemented in-box and by 3rd parties, you should only pass arguments which strictly adhere to the documented behavior to external implementations, and accept where possible arguments which you can do something sensible with.  

The runtime should only call documented API's that 3rd parties can implement strictly according to the documentation and shouldn't rely on undocumented behavior.  

I took a good look at the code and I believe it's not necessary to do a zero byte read in this case. The implementation in SslStream can easily be modified to still get what you want (defer allocating buffers) without doing a zero byte read. The current implementation will actually unnecessarily allocate larger buffers sometimes. The zero byte read is done when you don't know the frame size yet. The frame header which contains the size only needs 5 bytes. You could have an instance `byte[5]` which you use in place of the zero byte read to read the frame header. From that you can calculate the frame size and allocate the amount of buffer that you need to read the entire frame.  

To hit the code path which does the zero byte read you have to not have read the frame header yet, which means you're going to go with a guess instead. That guess is 64KB + 64 bytes. You make sure the size of the buffer is at least this size. At least with WCF Service side it's not uncommon for incoming messages to only be 100-200 bytes in size. The current code is going to significantly over allocate memory usage for WCF in many cases. This isn't theoretical either, CoreWCF has some tests using the WCF client which is hitting this issue, which means it intends to allocate a large buffer unnecessarily.  

I understand the scenario you are optimizing for is if you have 5000 clients connected, you don't want to maintain a read buffer for every single connection when they aren't actively sending data. By deferring getting a buffer from the pool until there's data to read, the total number of concurrent buffers you need will be equal to the number of concurrent connections actively receiving inside a Read call. As it's written, most buffers will be just over 64KB big. With my suggestion, you can reduce that significantly. Typically with HTTP (what I presume you are generally optimizing for), the HTTP headers are only a few KB big. There's massive over allocation happening in the typical case. Fixing that will also remove the zero byte read, a win-win.

**Comment by MihaZupan** [comment]
> when the existing documentation implies this isn't a valid thing to do

Which is why the documentation should be updated.

Is there something blocking you/WCF from fixing the stream implementations to play nice with this mechanism?
The minimal changes in question here are
```diff
-if (bytesRead == 0)
+if (bytesRead == 0 && buffer.Length == 0)
```

---

> That guess is 64KB + 64 bytes. You make sure the size of the buffer is at least this size. At least with WCF Service side it's not uncommon for incoming messages to only be 100-200 bytes in size. The current code is going to significantly over allocate memory usage for WCF in many cases.

These buffers are pooled.
Because of the zero-byte read we also know that data is very likely already available, so there is a good chance they'll be returned to the pool quickly.
This means that renting more memory in such cases is often effectively free.

> This isn't theoretical either, CoreWCF has some tests using the WCF client which is hitting this issue

If there is actually an issue here contrary to my previous paragraph, we would need more info to investigate what is actually happening.

> As it's written, most buffers will be just over 64KB big. With my suggestion, you can reduce that significantly. Typically with HTTP (what I presume you are generally optimizing for), the HTTP headers are only a few KB big. There's massive over allocation happening in the typical case.

What if [there are many small frames](https://github.com/dotnet/runtime/issues/49000)? Your suggestion means doing two read calls per frame. It also means that anything that called `SslStream` would only be reading one frame per read call.
If we instead rent a larger buffer ahead of time, we can grab a bunch of those frames in a single read, and when someone calls read on SslStream, we can return multiple frames at the same time.

---

Zero-byte reads have other advantages over small-buffer reads, such as giving you the [ability to avoid async state machine allocations completely in some types of wrapper streams](https://github.com/dotnet/runtime/pull/79386#discussion_r1043985899).

Depending on the platform, reading > 0 bytes may also involve pinning the buffer, leading to increased GC fragmentation.

**Comment by wfurt** [comment]
I'm not sure I fully understand your argumentation @mconnew but I generally agree with @MihaZupan. Zero bytes reads should be legal and supportive streams should block until data are available and non supportive streams should just return immediately - without assuming 0 is EOF. We discussed the with @stephentoub and he can probably provide more complete and accurate argument.

**Comment by davidfowl** [comment]
Zero byte reads are legal and we updated all of the streams in the box to make sure they work. e.g
- https://github.com/dotnet/aspnetcore/issues/41305
- https://github.com/dotnet/aspnetcore/issues/41287

**Comment by mconnew** [comment]
The current documentation  for Stream doesn't allow for zero byte reads as it explicitly says it only returns when at least one byte has been read or you hit the end of the stream. Zero byte read optimizations are counter to documented behavior.  

Changing the expectation that all existing Stream implementations must support zero byte reads without any change in documentation, or stating as such in any breaking changes documentation doesn't seem like the best approach for the extended eco system. 

And as I stated, in this particular case, as the intention was to improve memory consumption, an even more memory efficient implementation would actually eliminate the zero byte read.

**Comment by MihaZupan** [comment]
I agree that the expectation could have been documented and communicated better, but [it's not a new one, and not limited to `SslStream`](https://github.com/dotnet/runtime/issues/88792#issuecomment-1633350813).

Re: the rest, have you missed this reply: https://github.com/dotnet/runtime/issues/88792#issuecomment-1633436373?

**Comment by bencyoung-Fignum** [comment]
To be fair to @mconnew it's not that it was "badly documented" before, it was explicitly and positively documented that the behaviour he expected was the correct one. While it may be a sensible change there's no doubt it's a significant breaking change and will potentially break lots of other third party implementation which you can have no knowledge of at all? Now they'll have to synchronise changes to WCF to go in before the .NET changes and ensure all consumers update which is no guarantee

Perhaps you can use 0 byte reads when the inner stream is of a known inbox type only...

**Comment by mconnew** [comment]
@MihaZupan, this isn't a case of updating the documentation to refine the description of expected behavior. This is changing the documentation to state the behavior is now incompatible with what the prior documentation stated.  

I haven't got around to it yet, but I have on my todo list filing an issue against SslStream which is the opposite of #49000. SslStream greedily reading from the incoming connection is the wrong thing to do. It's an invalid assumptions that data following the current Tls frame is another Tls frame. There's nothing in the TLS spec which says that a connection secured with TLS must always be secured with it. CoreWCF/WCF explicitly requires the ability to revert a connection back to an unsecured state and greedily reading the stream breaks CoreWCF. I've had to implement TLS header parsing and byte counting to prevent SslStream from being able to read greedily. It shouldn't presume that data subsequently available on the connection will be TLS data unless a consumer attempts to read from SslStream. NegotiateStream doesn't greedily read from the connection, and this is the correct behavior. I think adding a property to turn on greedy reading is a reasonable solution, but having it on by default is making assumptions which aren't valid to make. 

I know issue #49000 is a different issue, but it is related. Fundamentally SslStream shouldn't be greedily reading from the connection data after the current frame as it might not be data intended for SslStream, and with WCF it sometimes isn't. This is related to the code here as this is where it's greedily reading from the inner stream and uses an oversized buffer to do so. It's this use of an oversized buffer which leads to the need to do a zero byte read.  

If you're worried about a 5 byte buffer causing GC fragmentation, then use a special pool like the PinnableBufferCache that exists on .NET Framework which is intended to provide GEN2 allocated buffers which won't cause fragmentation.

**Comment by MihaZupan** [comment]
> SslStream greedily reading from the incoming connection is the wrong thing to do. ... but having it on by default is making assumptions which aren't valid to make.

I disagree.
This sounds like a very niche scenario. Even if it were to make it into SslStream as an option, it wouldn't be the default.

**Comment by mconnew** [comment]
It's a fact that there's no guarantee that the data following a TLS frame is another TLS frame, as evidenced by the concrete example of WCF. What part of my statement do you disagree with? Are you saying that despite this, that it should consume data it maybe shouldn't consume anyway?

Nuget daily download numbers for the [WCF Client NetTcp](https://www.nuget.org/packages/System.ServiceModel.NetTcp) package is 34.9K. The daily download numbers for the [Grpc .NET Client](https://www.nuget.org/packages/Grpc.Net.Client) package is 61.K. They are the same order of magnitude in daily download numbers so NetTcp is definitely not a niche scenario.

**Comment by wfurt** [comment]
If there is other framing beyond TLS it would be responsibility of the caller to deal with it IMHO. There is example for SqlClient where TLS is segmented to SQL frames. The zero byte read serves only one purpose -> determining if some data are ready for processing and if internal resources should be allocated.

**Comment by mconnew** [comment]
I agree. WCF's case isn't wrapping frames around TLS, it's simply choosing not to use TLS on the connection any more. The problem is SslStream consumes the data outside of a TlsFrame. Anyway, that's a separate issue which I have an annoying and expensive work around for. I mentioned it as the intention with the zero byte read is to reduce memory consumption, and the best way to reduce memory consumption is to not allocate a buffer to read more than the size of the frame, and doing that solves both of my issues. But my immediate problem is the zero byte read breaks WCF. Only our most recent package version targets net6.0 and above, our previous packages, which are still in support, they target netstandard2.0. This change means we would need to go back and do a servicing release for prior releases too as they all will run on .net 8.

**Comment by wfurt** [comment]
similar changes in Read behavior were documented as breaking change for 6.0....
https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams

**Comment by stephentoub** [comment]
It's simply the case that the documentation is misleading, in that it's written referring to the case where there's a non-0 `count` requested.  The docs don't discuss the behavior when a 0 `count` is requested (but we should update the docs to do so).  This is obvious when you consider statements in the docs like "[Read](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.read) returns 0 only when there is no more data in the stream and no more is expected (such as a closed socket or end of file)"... that's obviously erroneous if `count` == 0 (which is a valid value), in which case it _has_ to return 0.

As has been stated, it has always been the case that there are two valid implementations for count==0:
1. Return immediately with 0, regardless of whether it's EOF
2. Wait for data to be available or EOF, then return 0

and we've long had streams that do one of those... we even have streams that can end up doing either behavior given the situation.  That goes all the way back to .NET Framework 1.0.  Streams following one of these two behaviors is not new.  In .NET Framework, for example, DeflateStream implements (1), PipeStream implements (2), and FileStream implements either (1) or (2) depending on what kind of file it's backed by.

**Comment by mconnew** [comment]
It's not difficult work as we can easily implement option 1 and just modify the validation logic everywhere that's needed. It's just a non-trivial amount of work as we need have multiple stream implementations and need to patch multiple versions as we used to target netstandard2.0.  
Implementing option 2 is a quite a bit more work. As this was hit in our client implementation, the perf cost of maintaining a pending read with a real buffer isn't something I would worry about as you generally don't have a lot of client instances in a process. I don't know if we have a problem in CoreWCF yet as we get a client exception really early.

**Comment by MihaZupan** [comment]
> It's just a non-trivial amount of work as we need have multiple stream implementations

If you don't care about an extra small allocation, you could update just the places where you create an `SslStream` instead, if it's easier.

```diff
-new SslStream(myStream);
+new SslStream(new BlockZeroByteReadsStream(myStream));
```

```c#
internal sealed class BlockZeroByteReadsStream : DelegatingStream
{
    public BlockZeroByteReadsStream(Stream stream) : base(stream) { }
    
    public override Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
    {
        if (count == 0) return Task.FromResult(0);
        return base.ReadAsync(buffer, offset, count, cancellationToken);
    }

    public override ValueTask<int> ReadAsync(Memory<byte> buffer, CancellationToken cancellationToken = default)
    {
        if (buffer.IsEmpty) return ValueTask.FromResult(0);
        return base.ReadAsync(buffer, cancellationToken);
    }

    public override int Read(byte[] buffer, int offset, int count)
    {
        if (count == 0) return 0;
        return base.Read(buffer, offset, count);
    }

    public override int Read(Span<byte> buffer)
    {
        if (buffer.IsEmpty) return 0;
        return base.Read(buffer);
    }
}
```
