### ISSUE TITLE
Does ServicePointManager still work in .NET 7 for HttpClient calls or is it "dead code"?

### ISSUE THREAD

**Issue by drauch** [dotnet/runtime#88814]
The docs of `ServicePointManager` tell us that:

> We don't recommend that you use the ServicePointManager class for new development. Instead, use the [System.Net.Http.HttpClient](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-7.0) class.

I don't understand this, HttpClient is not a replacement for ServicePointManager, they're orthogonal? If we use HttpClient in our Application do global ServicePointManager settings (in particular `SetTcpKeepAlive` or `DefaultConnectionLimit`) have effect or do we need to find replacements?

I'm asking in particular because the docs page is a bit confusing to me, and because the SetTcpKeepAlive way-to-go in .NET 7 is much more complicated and if we could postpone the switch it would be nice.

Best regards,
D.R.

**Comment by rzikm** [comment]
There is existing issue for obsoleting it: https://github.com/dotnet/runtime/issues/71836

**Comment by karelz** [comment]
Also, to certain level it works with HttpWebRequest for compat reasons with .NET Framework

**Comment by drauch** [comment]
Thank you - closing the issue.

**Comment by karelz** [comment]
You should be able to use [SocketsHttpHandler.SslOptions](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.ssloptions?view=net-7.0) - property [EnabledSslProtocols](https://learn.microsoft.com/en-us/dotnet/api/system.net.security.sslclientauthenticationoptions.enabledsslprotocols?view=net-7.0#system-net-security-sslclientauthenticationoptions-enabledsslprotocols) to achieve the same thing per HttpClient

**Comment by wfurt** [comment]
Or more generic [HttpClientHandler.SslProtocols](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.sslprotocols?view=net-6.0). And than you pass either handler to HttpClient constructor. If you use legacy HttpWebRequest the `ServicePointManager.SecurityProtocol` should still work.

**Comment by vats-ashish** [comment]
> You should be able to use [SocketsHttpHandler.SslOptions](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.ssloptions?view=net-7.0) - property [EnabledSslProtocols](https://learn.microsoft.com/en-us/dotnet/api/system.net.security.sslclientauthenticationoptions.enabledsslprotocols?view=net-7.0#system-net-security-sslclientauthenticationoptions-enabledsslprotocols) to achieve the same thing per HttpClient

Thank you Karelz! but even if I use EnabledSslProtocols I will be still hardcoding the security protocol right?
can't we keep it generic?

how can we keep it enabled for all..? will that be safe?

**Comment by karelz** [comment]
@vats-ashish I don't quite understand what exactly you need. Can you perhaps restate and clarify what you want and why?

If you want secure defaults, don't change anything. The right thing will happen - latest TLS supported, etc. Nothing insecure will be allowed by the OS.

If you have reason to override defaults (which is not recommended), then the above is what you can do.

**Comment by vats-ashish** [comment]
so in my legacy code (framework 4.5), we have this hardcoded while creating new HttpClient:
`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;`

now we have migrated to .Net 6 and using HttpClient, how it should be taken care now?

should we remove it completely?
or should we handle it in a different way so we can always have secure defaults?

**Comment by karelz** [comment]
Even for legacy code, it is not recommended to set it to Tls12 (as a result you will not get even safer TLS 1.3 when available) -- see https://learn.microsoft.com/en-us/dotnet/framework/network-programming/tls
Retargeting to 4.7+ is strongly recommended (you already run on it anyway).

.NET Core has secure defaults, so the highest version will be negotiated (TLS 1.3 or 1.2). You don't need to set anything.

**Comment by vats-ashish** [comment]
thank you for the information.
