### ISSUE TITLE
[7.0] Can't exec into pod anymore (exit code 138 - SIGBUS) - increased memory with net7.0

### ISSUE THREAD

**Issue by koepalex** [dotnet/runtime#88824]
### Description

We have an dotnet application that we recently updated to net7 (we couldn't update before because of the ARM build issue in containers). Our application is running as kubernetes pod with the main application and a sidecar communicating via memory mapped files and POSIX signals.

The behavior we observed on this high level, that remote debugging or exec into the pod (starting new shell) wasn't possible anymore. The reason is that linux sends SIGBUS signal to the starting application, running `apt update` or starting a shell failed while running preinstalled small tools (ls, ps aux) seem to work (for short time). 

As part of that investigation we found that the virtual memory was higher than with .net6.0 and it looks like the host OS memory is fully consumed:
<img width="735" alt="image" src="https://github.com/dotnet/runtime/assets/5366648/557aca15-e572-41cd-ae15-02938359a6e5">

### Reproduction Steps

* Using dotnet base image: mcr.microsoft.com/dotnet/runtime:7.0-bullseye-slim 
* Using 5 memory mapped files (size 1MB each)
* Having 56+ threads in total (shared by application and sidecar) 

### Expected behavior

Virtual memory of each process/thread should be in net6 range. 

### Actual behavior

Virtual memory of the process and threads is shown as 262MB each, which increases the virtual memory to handle.

```bash
root@opc-ua-connector-d47755954-7rgk4:/app# ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
65535          1  0.0  0.0    972     4 ?        Ss   14:54   0:00 /pause
root           7  4.3  0.8 275201556 131692 ?      Ssl  14:54   0:04 dotnet OpcUa.Connector.dll
root          20  3.6  0.5 275201556 86156 ?     Ssl  14:54   0:03 dotnet Apollo.ModuleConnectorSidecar.dll
root         442  0.0  0.0   2480   516 pts/0    Ss   14:56   0:00 sh -c clear; (bash || ash || sh)
root         450  0.0  0.0   2480    84 pts/0    S    14:56   0:00 sh -c clear; (bash || ash || sh)
root         451  0.0  0.0   4028  3408 pts/0    S    14:56   0:00 bash
root         453  0.0  0.0   6756  2952 pts/0    R+   14:56   0:00 ps aux
```

### Regression?

yes, worked with net6.0, found related bugs that are closed already:
* https://github.com/dotnet/runtime/issues/79633
* https://github.com/dotnet/runtime/issues/84497

We opend the bug, as the problem still occurs with latest service release 7.0.9.

### Known Workarounds

Restoring net6 behavior by setting `DOTNET_GCName="libclrgc.so"`

```bash
root@opc-ua-connector-566d8b46db-wf5dt:/app# ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
65535          1  0.0  0.0    972     4 ?        Ss   15:19   0:00 /pause
root           7  0.8  0.4 4114844 80308 ?       Ssl  15:19   0:02 dotnet OpcUa.Connector.dll
root          29  2.2  0.5 4867424 88652 ?       Ssl  15:19   0:05 dotnet Apollo.ModuleConnectorSidecar.dll
root         137  0.0  0.0   2480   520 pts/0    Ss   15:23   0:00 sh -c clear; (bash || ash || sh)
root         144  0.0  0.0   2480    88 pts/0    S    15:23   0:00 sh -c clear; (bash || ash || sh)
root         145  0.0  0.0   4028  3424 pts/0    S    15:23   0:00 bash
root         480  0.0  0.0   6756  2952 pts/0    R+   15:23   0:00 ps aux
```

### Configuration

* NET 7.0.9 runtime
* OS: Linux Debian Buster 
* Architecture: x64
* Kubernetes distribution:
  * AKS 
  * minikube

### Other information

If I exec into container befor the application "gets active" (spawns the threads to work with), I am able to connect but will get kicked because the started shell exits with code `190` or `188.` 

> command terminated with exit code 190

_Note:_ I don't understand fully why linux send SIGBUS to the newly created program like bash, even if the virtual memory is high... but maybe this is a cgroup limitation or the fact that multiple instances of our application running in the same cluster consuming to much virtual memory in total. If someone could explain this, that would be great.

**Comment by mangod9** [comment]
Hello @koepalex, thanks for reporting the issue. By virtual memory do you mean the reserved memory? Starting 7 the GC does reserve (not allocate) 256gb address space so that it has a continuous block available to allocate. Theoretically, that shouldnt be causing any issues since that much memory is not physically consumed. 

Do your containers run with any memory restrictions?

**Comment by koepalex** [comment]
Hello @mangod9, sorry for being unspecific yes the memory shown is reserved memory.
There is no memory request or limit defined for the pods. We are runnign a AKS cluster with 5 nodes (and each 16GB Ram), hosting 10-15 instances of our application + sidecar.

**Comment by mangod9** [comment]
would be interesting to check if things work better if you add some reasonable memory limits on the container, that should limit the reservation size. Still not quite sure why the high reservation size would cause the container to not allow `exec`

**Comment by mangod9** [comment]
would be interesting to try with a memory limit to check if that makes things work better.

**Comment by koepalex** [comment]
Found it, the issue was another process writing different POSIX signals to pid `-1` which sends to all processes. 
Linux processes that receive POSIX signals they don't expect terminate with return code  + Posixsignal. And as apt, the shell or htop were long running it was just a matter of time that they killed.

 That tools like ps or htop show the reserved memory instead of the commited memory were guiding me in the wrong direction, it was pure coincidence that it looked better with restoring the net GC behavior.
