### ISSUE TITLE
Confusion between Avx.IsSupported and Vector256.IsHardwareAccelerated

### ISSUE THREAD

**Issue by PavielKraskouski** [dotnet/runtime#88828]
My old laptop has an `Intel Core i7-2670QM` processor. This is a `Sandy Bridge` processor that supports `AVX`. As far as I know, processors with `AVX` have `256 bit` registers that hold `8` floating point numbers. In the picture below, you can see that the processor supports `AVX` as well as `Vector256<float>`, which is expected. But I can't understand why `Vector.IsHardwareAccelerated` is `false` and the size of `Vector<float>` is `4` and not `8`.

![Info](https://github.com/dotnet/runtime/assets/9061796/8537d9ff-7278-46a5-ad0c-9c3ef00f2f41)

**Comment by EgorBo** [comment]
> Thanks for the reply! Do I understand correctly that if I call the `Vector256.Abs` method, this operation will not be hardware accelerated on my processor because `AVX2` is needed to find the absolute value?

It seems that `Vector256.Abs` is not optimized for AVX1-only hardware, but e.g. if you need to perform Abs for `Vector256<float>` you can do `Avx.AndNot(Vector256.Create(-0.0f), vec)` or just call `Avx.Abs` if your vector is of integer type (small ints)

**Comment by PavielKraskouski** [comment]
Thanks for your help, it all made sense to me! We can close this issue.
