### ISSUE TITLE
Using SocketsHttpHandler over HttpClientHandler

### ISSUE THREAD

**Issue by drauch** [dotnet/runtime#88834]
Unfortunately, the only way to get TCP KeepAlive enabled is by switching `HttpClient`'s `HttpClientHandler` to `SocketsHttpHandler` (at least, according to the [docs](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.connectcallback?view=net-7.0#examples)).

What does this switch entail for us besides being able to enable TCP KeepAlive? I.e., why would I want to use one over the other? Which features do we lose?

I've looked a bit into the code myself and it looks like most of the code in `HttpClientHandler` exists to switch between `SocketsHttpHandler` for "normal" use cases and `BrowserHttpHandler` for "browser" use cases. There are subtle differences though, especially in regards to client certificate authentication. What exactly are the differences?

Is it better to still use `HttpClientHandler` and enable TCP KeepAlive by accessing the underlying handler (which is a `SocketsHttpHandler`) via Reflection? Is it maybe possible to make the underlying handler available via a property in the future? It really feels awkward for us to enable TCP KeepAlive by switching out one of the core classes in the HttpClient area.

Best regards,
D.R.

**Comment by MihaZupan** [comment]
Unless you are running in the Browser/on Mobile, HttpClientHandler is SocketsHttpHandler, you don't lose anything by creating it directly.

And on Browser/Mobile, I don't believe you have the option to set TCP KeepAlive anyway.

**Comment by karelz** [comment]
> Is it better to still use `HttpClientHandler` and enable TCP KeepAlive by accessing the underlying handler (which is a `SocketsHttpHandler`) via Reflection?

Reflection should NEVER be used in general (of course, every rule has an exception -- but exceptions are rare, VERY rare).
Using Reflection makes one dependent on internal implementation details and it can stop working with any new release or even servicing update. Which is typically very undesirable. There is no guarantee from .NET team about what could happen or that it would work.

Anyway, answered above, closing.
