### ISSUE TITLE
[Test Failure] System.Net.Security.Tests.CertificateValidationClientServer.CertificateValidationClientServer_EndToEnd_Ok on Windows AoT

### ISSUE THREAD

**Issue by rzikm** [dotnet/runtime#88832]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=332434
Build error leg or test failing: System.Net.Security.Tests.CertificateValidationClientServer.CertificateValidationClientServer_EndToEnd_Ok
Pull request:

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step).

```json
{
  "ErrorMessage": "System.Net.Security.Tests.CertificateValidationClientServer.CertificateValidationClientServer_EndToEnd_Ok(clientCertSource: CertificateContext)",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[701919](https://dev.azure.com/dnceng-public/public/_build/results?buildId=701919)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationClientServer.CertificateValidationClientServer_EndToEnd_Ok](https://dev.azure.com/dnceng-public/public/_build/results?buildId=701919&view=ms.vss-test-web.build-test-results-tab&runId=17475694&resultId=163121)|dotnet/runtime#103161|
|[699212](https://dev.azure.com/dnceng-public/public/_build/results?buildId=699212)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationClientServer.CertificateValidationClientServer_EndToEnd_Ok](https://dev.azure.com/dnceng-public/public/_build/results?buildId=699212&view=ms.vss-test-web.build-test-results-tab&runId=17398980&resultId=168141)|dotnet/runtime#103037|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|2|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=332434
**Error message validated:** `System.Net.Security.Tests.CertificateValidationClientServer.CertificateValidationClientServer_EndToEnd_Ok(clientCertSource: CertificateContext)`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 7/13/2023 2:17:22 PM UTC

**Comment by karelz** [comment]
Triage: Looks like unpleasant investigation will be needed. It is not super-common and affecting only AOT for now. Moving to 9.0.

**Comment by wfurt** [comment]
Do we have any info left what was failing @rzikm? I don't see it failing now and it does not seems to be disabled. It does not seems like we can do much at the moment. Perhaps close and re-open if we see more failures?

**Comment by rzikm** [comment]
It is still failing, see https://[helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-1ac9acfc4068453ca0/System.Net.Security.Tests/3/console.33101fec.log?helixlogtype=result](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-1ac9acfc4068453ca0/System.Net.Security.Tests/3/console.33101fec.log?helixlogtype=result)

The failing check in question is `sslClientStream.IsMutuallyAuthenticated`

**Comment by wfurt** [comment]
ok. It seems to be running on Windows 8. I think we should try to reproduce it. I don't see why AOT would matter in this case...

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as this has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by rzikm** [comment]
Looking at CI db, this failure stopped happening about 2 weeks ago. There are other failures of this test on non-windows platforms but they are a different problem than reported in this issue. Closing now until the issue resurfaces.
