### ISSUE TITLE
Path for ICU_DAT_FILE_PATH when targeting iOS inside an XCTest bundle

### ISSUE THREAD

**Issue by lemonmojo** [dotnet/runtime#88835]
### Description

As [commented here](https://github.com/xamarin/xamarin-macios/issues/18471#issuecomment-1634287195) the recently [introduced change](https://github.com/dotnet/runtime/pull/87813) to relatively locate the icudt.dat file inside an app bundle works fine.

However, when a NativeAOT'd library is included and called from an XCTest bundle, `-[NSBundle mainBundle]` returns a path inside Xcode instead of the test bundle:

```swift
let mainPath = Bundle.main.bundlePath
// /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Xcode/Agents

let testPath = Bundle(for: SomeTypeInTheTestBundle.self).bundlePath
// ~/Library/Developer/Xcode/DerivedData/TestBundle/Build/Products/Variant-ASan/Debug-iphonesimulator/TestBundle.xctest
```

Of course this causes the load to fail because the icudt.dat will never be in Xcode's app bundle.
If the XCTest project is however set up to copy this file to it's bundle resources folder, it would be there waiting to be consumed by the .NET runtime but currently fails because the logic of locating it just targets the main bundle.

**Comment by akoeplinger** [comment]
hmm not right now, we have the ICU_DAT_FILE_PATH app context key but NativeAOT compiles that into the app "hardcoded" during the build time.

we could probably add an environment variable override.

**Comment by lemonmojo** [comment]
@akoeplinger I can confirm that using `AppContext` to set the file path at runtime does indeed work.

I think it's still a good idea to change the loading code in the runtime to use `-[NSBundle bundleForClass:]` and provide a way to overwrite the path using an env var in case the bundle is structured in another way.

**Comment by lemonmojo** [comment]
@akoeplinger Any chance that the switch to `-[NSBundle bundleForClass:]` will make it into .NET 8?

**Comment by akoeplinger** [comment]
Actually, can you try setting `ICU_DAT_FILE_PATH` as an environment variable? it looks like AppContext will read from the environment if it's not set already.

**Comment by akoeplinger** [comment]
For XCTest we could probably look at `XCTestBundlePath` to find the bundle path but we'd hit the same issue when we're embedded inside a .framework.

Alternatively we could make the build pass in the bundle identifier via AppContext and then use `+[NSBundle bundleWithIdentifier]` (see the perf optimizations Flutter had to do with that approach: https://github.com/flutter/engine/pull/39975)

I wonder if the easiest solution is embedding the icudt.dat file itself somehow.

**Comment by lemonmojo** [comment]
@akoeplinger Sorry for the delay. I just tried setting the `ICU_DAT_FILE_PATH` as an environment variable instead of writing it to AppContext but that didn't work unfortunately.

At least for my case, just looking at `XCTestBundlePath` won't do the trick as I use nested frameworks and the ICU file could be deep inside the framework tree.

I'm not sure I understand your second suggestion regarding passing in the bundle identifier. Could you please elaborate?

Is embedding the icudt.dat file a viable option at that level? If so, that would absolutely be the easiest approach from a .NET user's perspective. To be honest, I didn't even know what that file is and why it's required until I hit some issues because I wasn't embedding it. So yeah, if you can make that work I'd be awesome.

**Comment by akoeplinger** [comment]
.NET 9 uses "hybrid globalization" on iOS which doesn't rely on bundling ICU with the app anymore so this should no longer be needed.
