### ISSUE TITLE
[NativeAOT] Add appropriate telemetry flags to track use of NativeAOT on iOS-like platforms

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/runtime#88844]
@steveisok please add more context if necessary, thank you!

**Comment by steveisok** [comment]
Our current state is that we would only get telemetry numbers for NativeAOT during dotnet publish.  That is not something iOS does by default.  

https://github.com/dotnet/sdk/blob/676d07949d868756967172ceaa7494bb2317cd15/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets#L91-L95
