### ISSUE TITLE
Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBinderTests.GetCanReadStaticProperty failed

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#88843]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=337818
Build error leg or test failing: Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBinderTests.GetCanReadStaticProperty
Pull request: https://github.com/dotnet/runtime/pull/88679

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "ConfigurationBinderTests.cs(752,0)",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": true
}
```

 ### Known issue validation
**Build: :mag_right:** 
**Result validation: :warning:** Provided build not found. Provide a valid build in the "**Build: :mag_right:**" line.
**Validation performed at:** 8/22/2023 7:50:05 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by ericstj** [comment]
Since this is a static property I wonder if concurrently executing tests might be setting the value to different things.

**Comment by mikelle-rogers** [comment]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=371425
Build error leg or test failing: Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBinderTests.GetCanReadStaticProperty
Pull request: https://github.com/dotnet/runtime/pull/90049

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).



```json
{
  "ErrorMessage": "Expected: stuff",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": true
}

**Comment by tarekgh** [comment]
We fixed the test a while ago. Closing this and we can reconsider opening it if it still hits.
