### ISSUE TITLE
[CoreCLR] UnsafeAccessorAttribute: Missing static modifier check for field

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#88858]
CoreCLR missed the check for when UnsafeAccessorKind is set to Field, the corresponding field shouldn't be static and vice/versa.

A new testcase was added in #88626 and it failed on CoreCLR.

Re-enable test: Verify_InvalidTargetUnsafeAccessor upon fixing this issue.

**Comment by AaronRobinsonMSFT** [comment]
I believe this is an issue in the newly added test. See  https://github.com/dotnet/runtime/pull/88626/files#r1262953624

**Comment by AaronRobinsonMSFT** [comment]
Closing based on https://github.com/dotnet/runtime/pull/88626#issuecomment-1634810706
