### ISSUE TITLE
Blazor Virtualize Component Memory Leak when Scrolling

### ISSUE THREAD

**Issue by robertjak** [dotnet/runtime#88850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

During fast scrolling with Virtualize Component memory consumption on the server increases significantly and it is not released by garbage collector automatically. 

### Expected Behavior

Scrolling fast upwards and downwards should not significantly increase memory consumption on the server.

### Steps To Reproduce

A sample project to reproduce the bug:
https://github.com/robertjak/VirtualizeTest

1. run the project (Index page) in release mode without debugger
2. quickly scroll up and down in the table dragging the scrollbox (thumb) with mouse for a minute
3. memory increases, on my computer from initial 29 MB to over 100 MB for the process

### Workaround

Calling  the following function inside of the Virtualize's ChildContent:
@{
    GC.Collect(2, GCCollectionMode.Aggressive | GCCollectionMode.Forced, blocking: true, compacting: true);
}
### .NET Version

7.0.203

**Comment by SamMonoRT** [comment]
@robertjak - Closing this issue due to lack of input. Please re-open with a minimal repro as mentioned above.
