### ISSUE TITLE
InlineArrayInvalid needs to be converted to il

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#88861]
In https://github.com/dotnet/runtime/pull/88188 roslyn started emitting errors for the invalid definitions and the test build was disabled.  The test should be coverted to il and reenabled.

**Comment by mangod9** [comment]
@VSadov, assume you plan on enabling this in 8?

**Comment by VSadov** [comment]
> @VSadov, assume you plan on enabling this in 8?

yes, I will also need to make the case with readonly element field illegal (as recently discussed), which will need a new test or two.
