### ISSUE TITLE
[RyuJIT] Audit places that set lvAddrExposed to true

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/runtime#8888]
Some of the places that set lvAddrExposed to true look questionable. For example, the comment explaining setting why lvAddrExposed is set here isn't clear:

https://github.com/dotnet/coreclr/blob/8a338880b527a86ccd33c29b1aa7baccd3f4b998/src/jit/morph.cpp#L9502

Setting lvAddrExposed on fewer structs may help get more struct fields promoted.

category:cq
theme:jit-coding-style
skill-level:expert
cost:small

**Comment by BruceForstall** [comment]
Closing
