### ISSUE TITLE
Document NativeAOT diagnostics for the .NET8 release

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#88905]
We need to set the right expectations for diagnostic support in `NativeAOT `for users in .NET8. `NativeAOT `applications are significantly different from a .NET application and the diagnostic experience, at least in .NET8, will be different to what users typically expect from a .NET application. 

We are planning to make the differences narrower in future releases based on user feedback, but its critical that users see very clearly in our documentation the current support. Towards that end, the following places should have `NativeAOT `diagnostic support clearly visible to our users.
 - Official NativeAOT application documentation pages
 - Dotnet-* tools
 - Logging technology like `OpenTel`
 - `EventPipe `support
 - .NET Debugging support

**Comment by agocke** [comment]
I believe this is done.
