### ISSUE TITLE
Ensure createdump works with NativeAOT applications

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#88904]
Tracking issue for some work needed on CreateDump to work in NativeAOT,
- [x] Not to load the DAC
- [x] Remove dependencies on PAL/DAC functions
- [x] Createdump on a NativeAOT app crash when env variables are set

**Comment by mikem8361** [comment]
This PR address the first 2 items: https://github.com/dotnet/runtime/pull/88802
