### ISSUE TITLE
Building iOS in release mode still attaches `--debug` flag to Mono AOT compiler

### ISSUE THREAD

**Issue by frenzibyte** [dotnet/runtime#88940]
### Description

When building a normal `net6.0-ios` project with AOT/LLVM compiler in release mode, either via my IDE (JetBrains Rider), or using `dotnet` CLI, I always notice the following in the output:

![CleanShot 2023-07-15 at 06 25 48](https://github.com/dotnet/runtime/assets/22781491/f0282472-cc3c-432a-9abd-8bd10f7af39a)

```
         Tool /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.AOT.osx-x64.Cross.ios-arm64/6.0.19/Sdk/../tools/mono-aot-cross execution started with arguments: --aot=mtriple=arm64-ios,data-outfile=obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Xml.XDocument.aotdata,static,asmonly,direct-icalls,full,readonly-value=ObjCRuntime.Runtime.Arch=i4/0,nodebug,dwarfdebug,direct-pinvoke,llvm-path=/usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.AOT.osx-x64.Cross.ios-arm64/6.0.19/Sdk/../tools,outfile=obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Xml.XDocument.dll.s,llvm-outfile=obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Xml.XDocument.dll.llvm.o --aot= --debug --llvm -O=gsharedvt /Users/salman/Projects/MetalSandbox/iOSApplication/obj/Release/net6.0-ios/ios-arm64/linked/System.Xml.XDocument.dll
```

There's a debugging flag attached in every instance of `mono-aot-cross`, and I would like to confirm whether that's intended, and whether there's a way to avoid having it.

### Reproduction Steps

1. Install latest .NET iOS workload (`16.4.8525-net8-p5/8.0.100-preview.5` at the time of opening this issue)
2. Create new "iOS Application" project (`dotnet new ios`)
3. Build project with release configuration and `ios-arm64` runtime to enable AOT/LLVM compilers (`dotnet run -p iOSTemplate.csproj -c:Release -r:ios-arm64 -v normal`)

### Expected behavior

Project compiles without attaching `--debug` flag in `mono-aot-cross` instances.

### Actual behavior

Project compiles with `--debug` flags attached in `mono-aot-cross` instances, e.g.:

![CleanShot 2023-07-15 at 06 40 21](https://github.com/dotnet/runtime/assets/22781491/bd1a981a-f859-4ef1-9f9a-db22a79bc0db)

```
         Tool /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.AOT.osx-x64.Cross.ios-arm64/8.0.0-preview.5.23280.8/Sdk/../tools/mono-aot-cross execution started with arguments: --aot=mtriple=arm64-ios,data-outfile=obj/Release/net8.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Runtime.InteropServices.aotdata,static,asmonly,dedup-skip,direct-icalls,full,readonly-value=ObjCRuntime.Runtime.Arch=i4/0,nodebug,dwarfdebug,direct-pinvoke,llvm-path=/usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.AOT.osx-x64.Cross.ios-arm64/8.0.0-preview.5.23280.8/Sdk/../tools,outfile=obj/Release/net8.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Runtime.InteropServices.dll.s,llvm-outfile=obj/Release/net8.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Runtime.InteropServices.dll.llvm.o --debug --llvm -O=gsharedvt /Users/salman/Projects/Attempt/obj/Release/net8.0-ios/ios-arm64/linked/System.Runtime.InteropServices.dll
```

### Regression?

N/A

### Known Workarounds

N/A

### Configuration

```
[I] ╭─salman at Salmans-MBP in /Users/salman/Projects/Attempt
╰─λ dotnet --info                                                                             0 (0.008s)
.NET SDK:
 Version:   8.0.100-preview.5.23303.2
 Commit:    3fe444af72

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.3
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.100-preview.5.23303.2/

.NET workloads installed:
 [ios]
   Installation Source: SDK 8.0.100-preview.5
   Manifest Version:    16.4.8525-net8-p5/8.0.100-preview.5
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100-preview.5/microsoft.net.sdk.ios/WorkloadManifest.json
   Install Type:        FileBased
 [maccatalyst]
   Installation Source: SDK 8.0.100-preview.5
   Manifest Version:    16.4.8525-net8-p5/8.0.100-preview.5
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100-preview.5/microsoft.net.sdk.maccatalyst/WorkloadManifest.json
   Install Type:        FileBased
 [wasm-tools-net6]
   Installation Source: SDK 8.0.100-preview.5
   Manifest Version:    8.0.0-preview.5.23280.8/8.0.100-preview.5
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100-preview.5/microsoft.net.workload.mono.toolchain.net6/WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.0-preview.5.23280.8
  Architecture: arm64
  Commit:       bc78804f5d

.NET SDKs installed:
  6.0.406 [/usr/local/share/dotnet/sdk]
  7.0.201 [/usr/local/share/dotnet/sdk]
  8.0.100-preview.5.23303.2 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.5.23302.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.5.23280.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

Probably not specific to my configuration.

**Comment by radical** [comment]
cc @rolfbjarne @steveisok

**Comment by lateralusX** [comment]
--debug flag is passed to cross-compiler and shouldn't have any impact on optimization levels of generated code, there are other arguments passed to --aot argument in order to change optimization levels, generate sequence point for soft debugging etc. The --debug flag mainly makes sure runtime can/will load ppdb info for loaded assemblies in order to get better stacktraces etc (like IL to source line mappings), but if not dwarfdebug aot option is selected nothing of that should find its way into the aot image.

So --debug passed to cross-compiler should not have impact on the generated code, and as long as additional debugging parameters are enabled, it should mainly instructs cross-compiler to load ppdb files for compiled assemblies, if they are available. I guess it is always passed to make the handling of other arguments simpler, since if you pass other aot compiler arguments that depends on --debug, and that argument has not been passed to cross-compiler, then cross-compiler will fail, so instead of having the aot compiler task explicitly know what sub arguments that needs --debug, and since the impact of always passing it looks small, it will always pass it.

I agree that it looks a little wired to always pass it to cross-compiler, but what matters is the generated code, and that should not be affected, unless you pass additional debug commands in the --aot argument.
