### ISSUE TITLE
Consider replacing `Dictionary` with `ConcurrentDictionary` in `DefaultMeterFactory`

### ISSUE THREAD

**Issue by cakescience** [dotnet/runtime#88955]
### Description

Currently, `DefaultMeterFactory` uses a `Dictionary` to cache meters. A explicit lock is used to ensure thread safety and prevent race conditions.

https://github.com/dotnet/runtime/blob/b898a540f75d78ca55ee33288a4fd62b1ab69fa2/src/libraries/Microsoft.Extensions.Diagnostics/src/Metrics/DefaultMeterFactory.cs#L13
https://github.com/dotnet/runtime/blob/b898a540f75d78ca55ee33288a4fd62b1ab69fa2/src/libraries/Microsoft.Extensions.Diagnostics/src/Metrics/DefaultMeterFactory.cs#L32

### Proposal

By using a `ConcurrentDictionary`, we can ensure thread-safe access to the dictionary without the need for explicit locks. `ConcurrentDictionary` is designed to handle concurrent access efficiently. This can potentially improve performance in scenarios with high concurrent access.

**Comment by cakescience** [comment]
cc @tarekgh

**Comment by antonfirsov** [comment]
HttpClient/SocketsHttpHandler executes one `IMeterFactory.Create()` call per handler initialization. @cakescience do you have a scenario proving that these calls may be frequent enough so this change is worth it?

**Comment by tarekgh** [comment]
@cakescience as @antonfirsov mentioned, what is your scenario you have a perf problem with. Note the lock is not just for accessing the dictionary but also the value lists too. Using the lock is simplifying the code here too.
