### ISSUE TITLE
[API Proposal]: Ship IPNetwork downlevel for netstandard2.0

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#88965]
See https://github.com/dotnet/runtime/issues/79946#issuecomment-1448984670

We need decision from API review group - @stephentoub any thoughts when it might be decided?

**Comment by stephentoub** [comment]
> We need decision from API review group - @stephentoub any thoughts when it might be decided?

What specific decision are you waiting on?  The previous issue wasn't tagged to have it in any review queue.

If the question is whether to ship the type downlevel, I'd suggest defaulting to "no".

If the question is that you've already decided we need to and you're asking about package name, what is the proposed name?

**Comment by karelz** [comment]
Triage: If it is internal only in dotnet/extensions, then we do not need a downlevel package.
If it is public, then we should remove it from dotnet/extensions - if there are customers depending on it, we would ship it downlevel.

**Comment by terrajobst** [comment]
@GrabYourPitchforks mentioned he received partner requests and will follow up with @antonfirsov to see if those got lost somewhere in mail.

**Comment by karelz** [comment]
Triage: We didn't see strong signal that it is needed. Closing
If it impacts a few customers, they can have a copy in their code for downlevel.

If there is more customer demand in future, we can reconsider.
