### ISSUE TITLE
Improve ArraySegment debugging

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#88961]
ArraySegment could be improved with debugger display and debugger type proxy.

Current state:

![image](https://github.com/dotnet/runtime/assets/303201/9cdc2f27-0509-4f52-af6f-40e39ffa28ad)

See Span debugging support for ideas of improvement.

**Comment by tannergooding** [comment]
This is a small improvement that doesn't impact public API surface. Please feel free to provide it anytime after `main` opens up for .NET 9 changes
