### ISSUE TITLE
Https_MultipleRequests_TlsResumed test is unreliable

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#88979]
https://github.com/dotnet/runtime/blob/4ebb3eaf8039bbb399466bed3ae6dfcd05812eef/src/libraries/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs#L4298

This new test is failing for me locally on the majority of runs (succeeds once every ~5 runs).

```
---- Assert.True() Failure
Expected: True
Actual:   False
```
here:
https://github.com/dotnet/runtime/blob/4ebb3eaf8039bbb399466bed3ae6dfcd05812eef/src/libraries/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs#L4329

Doesn't affect CI as it's under an `#if DEBUG`.

cc: @wfurt

**Comment by karelz** [comment]
Triage: It is impacting dev loop, we should disable the test or fix it in 8.0.

**Comment by wfurt** [comment]
what is your base os @MihaZupan? AFAIK we do some debug runs in CI as well.

**Comment by MihaZupan** [comment]
It's Win11 enterprise, 10.0.22621
