### ISSUE TITLE
[NativeAOT] Tests failing due to TypeInfoResolver not providing JsonTypeInfo metadata for a type

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/runtime#88982]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=341298

Observed in `runtime-extra-platforms` pipeline

Build error legs:
- net8.0-windows-Release-x64-NativeAOT_Release-(Windows.Nano.1809.Amd64.Open)
- net8.0-windows-Release-x64-NativeAOT_Release-Windows.11.Amd64.Client.Open
- net8.0-windows-Release-x64-NativeAOT_Release-Windows.Amd64.Server2022.Open
- net8.0-windows-Release-x64-NativeAOT_Release-Windows.81.Amd64.Open
- net8.0-linux-Release-arm64-NativeAOT_Release-(Debian.11.Arm64.Open)
- net8.0-linux-Release-arm64-NativeAOT_Release-(Ubuntu.1804.Arm64.Open)

 Tests failing: 
- `System.Net.Http.Json.Functional.Tests.*`
- `System.Text.Json.SourceGeneration.Tests.*`

Pull request: https://github.com/dotnet/runtime/pull/88723

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "System.NotSupportedException : JsonTypeInfo metadata for type",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=341298
**Error message validated:** `System.NotSupportedException : JsonTypeInfo metadata for type`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 7/17/2023 7:42:58 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[343204](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343204)|dotnet/runtime|[System.Text.Json.SourceGeneration.Tests.UnsupportedTypesTests_Metadata.DeserializeUnsupportedType<Nullable<IntPtr>>(wrapper: 123)](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343204&view=ms.vss-test-web.build-test-results-tab&runId=7172226&resultId=174044)||
|[342556](https://dev.azure.com/dnceng-public/public/_build/results?buildId=342556)|dotnet/runtime|[System.Text.Json.SourceGeneration.Tests.RequiredKeywordTests_SourceGen.ClassWithRequiredKeywordAndSmallParametrizedCtorFailsDeserialization](https://dev.azure.com/dnceng-public/public/_build/results?buildId=342556&view=ms.vss-test-web.build-test-results-tab&runId=7160242&resultId=174014)||
|[342345](https://dev.azure.com/dnceng-public/public/_build/results?buildId=342345)|dotnet/runtime|[System.Text.Json.SourceGeneration.Tests.ReferenceHandlerTests_IgnoreCycles_Default_AsyncStream.IgnoreCycles_DoesNotSupportPreserveSemantics](https://dev.azure.com/dnceng-public/public/_build/results?buildId=342345&view=ms.vss-test-web.build-test-results-tab&runId=7154722&resultId=173758)|dotnet/runtime#88974|
|[341622](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341622)|dotnet/runtime|[System.Text.Json.SourceGeneration.Tests.ReferenceHandlerTests_IgnoreCycles_Default_String.IgnoreCycles_DoesNotSupportPreserveSemantics_Polymorphic](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341622&view=ms.vss-test-web.build-test-results-tab&runId=7134832&resultId=173247)||
|[341305](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341305)|dotnet/runtime|[System.Text.Json.SourceGeneration.Tests.ReferenceHandlerTests_IgnoreCycles_Default_AsyncStream.IgnoreCycles_DoesNotSupportPreserveSemantics](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341305&view=ms.vss-test-web.build-test-results-tab&runId=7124124&resultId=172427)||
|[341298](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341298)|dotnet/runtime|[System.Text.Json.SourceGeneration.Tests.ReferenceHandlerTests_IgnoreCycles_Default_String.IgnoreCycles_DoesNotSupportPreserveSemantics_Polymorphic](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341298&view=ms.vss-test-web.build-test-results-tab&runId=7124632&resultId=174325)|dotnet/runtime#88723|
|[341220](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341220)|dotnet/runtime|[System.Text.Json.SourceGeneration.Tests.ReferenceHandlerTests_IgnoreCycles_Default_String.IgnoreCycles_DoesNotSupportPreserveSemantics_Polymorphic](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341220&view=ms.vss-test-web.build-test-results-tab&runId=7122062&resultId=174240)|dotnet/runtime#87847|
|[341209](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341209)|dotnet/runtime|[System.Text.Json.SourceGeneration.Tests.ReferenceHandlerTests_IgnoreCycles_Metadata_AsyncStream.IgnoreCycles_DoesNotSupportPreserveSemantics](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341209&view=ms.vss-test-web.build-test-results-tab&runId=7120762&resultId=173922)|dotnet/runtime#88163|
|[341090](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341090)|dotnet/runtime|[System.Text.Json.SourceGeneration.Tests.RequiredKeywordTests_SourceGen.ClassWithRequiredKeywordAndLargeParametrizedCtorFailsDeserialization](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341090&view=ms.vss-test-web.build-test-results-tab&runId=7118640&resultId=174022)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|3|9|9|

**Comment by am11** [comment]
@eiriktsarpalis, this is still showing up in [the latest run](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-4b388418d74b44c19d/System.Memory.Data.Tests/1/console.4f2b0434.log?helixlogtype=result) of `runtime-extra-platforms`:

```
[FAIL] System.Tests.BinaryDataTests.IsBinaryDataMemberPropertySerialized
System.NotSupportedException : JsonTypeInfo metadata for type 'System.Tests.BinaryDataTests+TestModelWithBinaryDataProperty' was not provided by TypeInfoResolver of type '[]'. If using source generation, ensure that all root types passed to the serializer have been annotated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically.
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_NoMetadataForType(Type, IJsonTypeInfoResolver) + 0x65
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type, Boolean, Nullable`1, Boolean, Boolean) + 0xa5
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoForRootType(Type, Boolean) + 0x62
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions) + 0x25
   at System.Tests.BinaryDataTests.IsBinaryDataMemberPropertySerialized() + 0x110
   at System.Memory.Data.Tests!<BaseAddress>+0x3bcc34
   at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0xb3
[FAIL] System.Tests.BinaryDataTests.IsBinaryDataMemberPropertyDeserialized
System.NotSupportedException : JsonTypeInfo metadata for type 'System.Tests.BinaryDataTests+TestModelWithBinaryDataProperty' was not provided by TypeInfoResolver of type '[]'. If using source generation, ensure that all root types passed to the serializer have been annotated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically.
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_NoMetadataForType(Type, IJsonTypeInfoResolver) + 0x65
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type, Boolean, Nullable`1, Boolean, Boolean) + 0xa5
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoForRootType(Type, Boolean) + 0x62
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions) + 0x25
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String, JsonSerializerOptions) + 0x28
   at System.Tests.BinaryDataTests.IsBinaryDataMemberPropertyDeserialized() + 0xee
   at System.Memory.Data.Tests!<BaseAddress>+0x3bcc34
   at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0xb3
```

(can use `/azp run runtime-extra-platforms` in PR to start it on-demand)

**Comment by eiriktsarpalis** [comment]
I'm guessing that test project also has a dependency on reflection STJ cc @dotnet/area-system-memory
