### ISSUE TITLE
CI: `runtime-ioslike-mono`, and `runtime-ioslike-coreclr` pipelines are broken due to setup issues

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#88996]
The new pipelines are failing at the `Send to helix` step.
[Log](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341731&view=logs&j=7f49df26-8126-5de3-bf2f-6ac6bde01830&t=c62b6a8c-bf71-5057-7f45-9c355fe0b802):

```
.packages/microsoft.dotnet.helix.sdk/8.0.0-beta.23364.2/tools/azure-pipelines/AzurePipelines.MultiQueue.targets(16,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) A call to an Azure DevOps api returned 401, which may indicate a bad 'System.AccessToken' value.

Please Check the 'Make secrets available to builds of forks' in the pipeline pull request validation trigger settings.
We have evaluated the security considerations of this setting and have determined that it is fine to use for our public PR validation builds.
```

cc @kotlarmilos @steveisok 

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by steveisok** [comment]
@kotlarmilos can you revert the PR that introduced these pipelines?
