### ISSUE TITLE
Multiple IL2049 warnings when publishing with NativeAOT and _AggressiveAttributeTrimming

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#88994]
### Description

I tried using `_AggressiveAttributeTrimming` to check the size diffs, and noticed a whole bunch of warnings:

> resource ILLink.LinkAttributes.xml in System.Private.CoreLib(377,8): warning IL2049: System.Private.CoreLib: The internal attribute name 'RemoveAttributeInstances' being used in the xml is not supported by ILLink, check the spelling and the supported internal attributes. [C:\Users\sergiopedri\git\ComputeSharp\samples\ComputeSharp.SwapChain.Cli\ComputeSharp.SwapChain.Cli.csproj]

### Reproduction Steps

- Checkout to https://github.com/Sergio0694/ComputeSharp/tree/dev/_AggressiveAttributeTrimming-warn
- Build the CLI sample with these steps:
```powershell
$env:COMPUTESHARP_SWAPCHAIN_CLI_PUBLISH_AOT='true';
dotnet publish samples\ComputeSharp.SwapChain.Cli\ComputeSharp.SwapChain.Cli.csproj -c Release -f net8.0 -r win-x64
```

### Expected behavior

Should build with no warnings.

### Actual behavior

When `_AggressiveAttributeTrimming` is set, you get a whole bunch of warnings.

### Configuration

- 8.0.100-preview.7.23364.32

**Comment by MichalStrehovsky** [comment]
It's generating a warning because an obscure/useless corner case of the attribute trimming XML format is not implemented. Can be fixed by just not generating the warning (it's unlikely the obscure corner case is worth the effort to implement).

Since `_AggressiveAttributeTrimming` (or the XML format) is not documented, moving this to Future, pending result of #88805.

**Comment by rolfbjarne** [comment]
This affects NativeAOT when targeting Apple platforms (net8.0-macos/maccatalyst/ios/tvos):

```
	resource ILLink.LinkAttributes.xml in System.Private.CoreLib(335): warning IL2049: System.Private.CoreLib: The internal attribute name 'RemoveAttributeInstances' being used in the xml is not supported by ILLink, check the spelling and the supported internal attributes.
	resource ILLink.LinkAttributes.xml in System.Private.CoreLib(342): warning IL2049: System.Private.CoreLib: The internal attribute name 'RemoveAttributeInstances' being used in the xml is not supported by ILLink, check the spelling and the supported internal attributes.
	resource ILLink.LinkAttributes.xml in System.Private.CoreLib(349): warning IL2049: System.Private.CoreLib: The internal attribute name 'RemoveAttributeInstances' being used in the xml is not supported by ILLink, check the spelling and the supported internal attributes.
	resource ILLink.LinkAttributes.xml in System.Private.CoreLib(356): warning IL2049: System.Private.CoreLib: The internal attribute name 'RemoveAttributeInstances' being used in the xml is not supported by ILLink, check the spelling and the supported internal attributes.
	resource ILLink.LinkAttributes.xml in System.Private.CoreLib(363): warning IL2049: System.Private.CoreLib: The internal attribute name 'RemoveAttributeInstances' being used in the xml is not supported by ILLink, check the spelling and the supported internal attributes.
	resource ILLink.LinkAttributes.xml in System.Private.CoreLib(370): warning IL2049: System.Private.CoreLib: The internal attribute name 'RemoveAttributeInstances' being used in the xml is not supported by ILLink, check the spelling and the supported internal attributes.
```

**Comment by MichalStrehovsky** [comment]
> This affects NativeAOT when targeting Apple platforms (net8.0-macos/maccatalyst/ios/tvos):

Does this show up in customer scenarios? (Would we want this for 8.0?)

**Comment by ivanpovazan** [comment]
> > This affects NativeAOT when targeting Apple platforms (net8.0-macos/maccatalyst/ios/tvos):
> 
> Does this show up in customer scenarios? (Would we want this for 8.0?)

Sorry for the late reply. Yes these show up in template apps, I have posted examples of warnings here: 
https://github.com/xamarin/xamarin-macios/issues/18571#issuecomment-1649439551
We would like to have `dotnet new ios` app have 0 warnings for .NET8.

PS I see you have already opened a PR for this, thanks!
