### ISSUE TITLE
ECDiffieHellmanOpenSsl throws PlatformNotSupported on macOS

### ISSUE THREAD

**Issue by mvoss84** [dotnet/runtime#89006]
### Description

The constructor of ECDiffieHellmanOpenSsl throws a PlatformNotSupportedException on macOS, though it doesn't seem to be flagged as a platform-specific class and its documentation says it is for interop needs. Neither the default OpenSsl nor the latest installed by Homebrew seem to make a difference.

### Reproduction Steps

`if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
{
    ECDiffieHellmanOpenSsl ecdh = new();
}`

Specifying a particular curve also doesn't seem to make a difference.

### Expected behavior

Ideally the class would work on as many platforms as possible; it's for interop use, after all, but if there are some which can't be supported, it would be good to give them the attribute for the platforms they do support, so consumers know they have to work around it.

### Actual behavior

There is no warning about supported platforms on the code and running it throws

System.PlatformNotSupportedException: Algorithm 'ECDiffieHellmanOpenSsl' is not supported on this platform.
    at System.Security.Cryptography.ECDiffieHellmanOpenSsl.ThrowIfNotSupported()
    at System.Security.Cryptography.ECDiffieHellmanOpenSsl..ctor(Int32 keySize)
    at System.Security.Cryptography.ECDiffieHellmanOpenSsl..ctor()

### Configuration

macOS Monterey x64; uncertain if it's specific to platform. Happens on both .NET 6 and 7; unsure if it's a regression.

**Comment by vcsjones** [comment]
`ECDiffieHellmanOpenSsl` is supported on macOS - the problem is macOS does not come with a recent version of OpenSSL. .NET requires a supported version of OpenSSL.

For example, with Homebrew, if I do:

```
brew install openssl@3
```

That will install OpenSSL - but it won't put the libraries in a place that are on the OS dylib loading path. You can either create links to libcrypto and libssl in a searchable location, or us an environment variable to set where to load the library:


```
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:"$(brew --prefix)/opt/openssl@3/lib"
```

After that, using `ECDiffieHellmanOpenSsl` will work on macOS.


------

In general, unless you need OpenSSL specific capabilities (like working with EVP PKEY handles) you should use `ECDiffieHellman ecdh = ECDiffieHellman.Create();`

This will return a platform agnostic implementation. On Linux it will use OpenSSL, on macOS it will use CommonCrypto, and for Windows it will use CNG. This is preferred because it will "just work".

**Comment by mvoss84** [comment]
I've re-run the Homebrew install and environment variable commands to make sure I've got it right and am seeing the same error. Would it be possible to get more-specific errors in this class to help people trying to use it identify what the problem is? PlatformNotSupported leaves me with little direction for followup.

<hr/>

ECDiffieHellman.Create() does seem to just work, as suggested; I don't think this necessarily solves the problem I have in hand because I'm trying to call code from another library that's using ECDiffieHellmanOpenSsl everywhere but Windows, and I'd have to confirm with the owners of it that changing it would meet all of their needs, though this reply implies that the documentation on ECDiffieHellmanOpenSsl is could use an update. Taken from this article...
https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.ecdiffiehellmanopenssl?view=net-7.0

> This class should only be used directly when doing platform interop with the system OpenSSL library. When platform interop is not needed, you should use the [ECDiffieHellman.Create](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.ecdiffiehellman.create?view=net-7.0) factory methods instead of a specific derived implementation.

... but it sounds from this reply that the conditions under which we'd prefer ECDiffieHellmanOpenSsl are narrower. I suspect that the code I'm trying to call into was attempting to follow that advice when they wrote their part.

**Comment by vcsjones** [comment]
> and am seeing the same error.

The general gist is that you need libcrypto.dylib and libssl.so for this class to function. On linux these are there by default, and include a supported version. For macOS, you can use Homebrew, or any other means, to make sure the libraries are in a path that macOS will look for them.

If you are still seeing errors, then make sure your brew-installed OpenSSL matches the same architecture as your .NET application.

> ECDiffieHellmanOpenSsl everywhere but Windows

That means the library will only work in places where OpenSSL is available. It’s optionally available on macOS, but it isn’t the preferred way to use ECDH. ECDiffieHellman.Create is the only way to get a cross-platform implementation. Using the ECDHOpenSsl class will also not work on Android or iOS, whereas ECDiffieHellman.Create will. ECDiffieHellmanOpenSsl primary benefit is that it has two constructors that take either an EC_KEY or an EVP_PKEY. 

> Would it be possible to get more-specific errors in this class to help people trying to use it identify what the problem is?

The most reasonable thing I think we could do in this situation is change the exception text to something that explicitly indicates no usable version of OpenSSL was found on the system.

> implies that the documentation on ECDiffieHellmanOpenSsl is could use an update.

that paragraph is more or less explicitly saying “Don’t use this unless you explicitly need OpenSSL or OpenSSL features. Use ECDiffieHellman.Create instead for a cross platform implementation.”

What improvements to the documentation that you linked to could we make to help make the situation more clear?

**Comment by mvoss84** [comment]
I don't understand what's meant for matching architecture? Is there some documentation that I ought to be reading about compatibility between .NET apps and OpenSSL to determine whether I'm building an app that can use OpenSSL?

<hr/>

As a suggestion for better error text, compare to trying to DllImport and having a library name wrong: the error includes what it was looking for and where it looked. While that doesn't give me a correct answer on its own, as DllImport doesn't know what it doesn't know (or surely it'd find out and then run the command); if that's not possible, saying that there's no usable OpenSSL would be a much stronger hint than PlatformNotSupported -- "No usable OpenSSL" suggests to a user to look at environment variables, versions, architecture, etc, particularly if there's a case where ECDiffiehellmanOpenSsl did find something but can't run it, even if it doesn't know why, "I found X. I can't use X. I don't know why I can't use X" is still fairly-specific direction. It at least would've lead me to investigating OpenSSL instead of reporting a bug here. The PlatformNotSupported that's thrown now suggests that it can't work here and changing configuration is fruitless. I only bothered trying environment variables and versions of OpenSSL before creating this issue because the documentation for ECDiffieHellmanOpenSsl explicitly says it's for interop uses.

<hr/>

I'm not certain that the paragraph in ECDiffieHellmanOpenSsl's article does more or less say "Don't use this unless you explicitly need OpenSSL features." -- I think that specific sentence would've been a good deal clearer. The specific direction of "When platform interop is not needed, you should use ECDiffieHellman.Create" implies that ECDiffieHellman.Create does not interop, but it seems that it does. A more accurate second sentence, based on this conversation, would be "When OpenSSL is not needed, you should use ECDiffieHellman.Create".

**Comment by vcsjones** [comment]
> I don't understand what's meant for matching architecture?

If you have a Mac / OpenSSL installation that is installing ARM64 because you are on Apple Silicon, but you are trying to run a .NET app as x64. Or if your homebrew installation is installing x64 libraries but your .NET application is ARM64.

If the environment variables are not working for you - which can be admittedly a bit finicky with processes, you can instead link them in to /usr/local/lib:

Assuming you installed openssl@3:

```shell
sudo ln -s $(brew --prefix)/opt/openssl@3/lib/libcrypt.3.dylib /usr/local/lib/libcrypto.3.dylib
sudo ln -s $(brew --prefix)/opt/openssl@3/lib/libssl.3.dylib /usr/local/lib/libssl.3.dylib
```

> I'm not certain that the paragraph in ECDiffieHellmanOpenSsl's article does more or less say "Don't use this unless you explicitly need OpenSSL features."

Thanks - I opened an issue in the documentation repository to try and clear this up. I'll work with the docs folks to see how we can more clearly, and consistently, word this.

> As a suggestion for better error text

Gotcha - I think this is something that can be improved. I'll take a stab at this.

**Comment by vcsjones** [comment]
> I think this is something that can be improved. 

The exception message has been changed to "OpenSSL is required for algorithm 'ECDiffieHellmanOpenSsl' but could not be found or loaded."

**Comment by vcsjones** [comment]
I think we can close this issue out now.

We have an issue tracking documentation changes at https://github.com/dotnet/dotnet-api-docs/issues/9146

We have improved the exception text in https://github.com/dotnet/runtime/pull/89046

To re-summarize: using `ECDiffieHellmanOpenSsl` specifically means "use OpenSSL", which macOS does not come with a suitable version of OpenSSL to use. It is recommended to use `ECDiffieHellman.Create()` to create a platform agnostic instance of `ECDiffieHellman`.

Please feel free to re-open this issue if you feel there are parts still unaddressed or not tracked by new issues.
