### ISSUE TITLE
CoreBindingHelper for configuration binding source generator should be marked as [GeneratedCode]

### ISSUE THREAD

**Issue by martincostello** [dotnet/runtime#89007]
### Description

When enabling the [Configuration binding source generator improvements](https://devblogs.microsoft.com/dotnet/announcing-dotnet-8-preview-6/#configuration-binding-source-generator-improvements) in an application which requires a minimum level of code coverage, code emitted by the generator counts towards the application's own coverage metrics.

If the code emitted for the `CoreBindingHelper` class was annotated with `[GeneratedCode]` then it would be easy to exclude from coverage metrics in the consuming application without having to know the internal implementation details (e.g. to exclude a class named `Microsoft.Extensions.Configuration.Binder.SourceGeneration.CoreBindingHelper`).

### Reproduction Steps

Inspect the emitted code for an application using the configuration binding source generator in a tool such as ILSpy. The type is not annotated with `[GeneratedCode]`.

### Expected behavior

The types emitted by the source generator into the user's assembly as marked as `[GeneratedCode]` so they can be easily excluded.

### Actual behavior

The generated types are not annotated as such.

### Regression?

No.

### Known Workarounds

Exclude the `Microsoft.Extensions.Configuration.Binder.SourceGeneration.CoreBindingHelper` type from code coverage metrics, such as using `Exclude` for coverlet.

### Configuration

.NET SDK 8.0.100-preview.6.23330.14

**Comment by layomia** [comment]
This was fixed for preview 7 in https://github.com/dotnet/runtime/pull/88338, see [example](https://github.com/dotnet/runtime/blob/9ffdb53540ce286438a769b3e1950c4d99b630f0/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/SourceGenerationTests/Baselines/OptionsBuilder/Bind_T.generated.txt#L61).
