### ISSUE TITLE
Configuration binding source generator fails to compile with CS8600 when using nullable reference types

### ISSUE THREAD

**Issue by martincostello** [dotnet/runtime#89019]
### Description

When enabling the configuration binding source generator for a project where nullable types are used, compilation fails with an CS8600 error.

```
Project\src\Project\Microsoft.Extensions.Configuration.Binder.SourceGeneration\Microsoft.Extensions.Configuration.Binder.SourceGeneration.ConfigurationBindingGenerator\GeneratedConfigurationBinder.g.cs(1070,53): error CS8600: Converting null literal or possible null value to non-nullable type. [Project\src\Project\Project.csproj]
```

### Reproduction Steps

1. Clone and checkout any of the following commits:
    * https://github.com/martincostello/alexa-london-travel-site/commit/43bd5a9ea0aa53c1e8e30f467f2d86d00c349402
    * https://github.com/martincostello/api/commit/356d8cbe6ffa3e2c114b79f89d5ae70e72302c3d
    * https://github.com/martincostello/website/commit/e0a98c7900557075c09666fb8ce43d9e571570f8
1. Run `build.ps1`

### Expected behavior

The applications compile and the tests pass.

### Actual behavior

The applications fail to compile with CS8600 errors.

### Regression?

No.

### Known Workarounds

None.

### Configuration

.NET SDK 8.0.100-preview.6.23330.14

**Comment by ericstj** [comment]
Probably you can workaround with NoWarn in the project file (temporarily).
```xml
<NoWarn>$(NoWarn);CS8600</NoWarn>
```
