### ISSUE TITLE
Configuration binding source generator throws ArgumentOutOfRangeException on macOS and Linux

### ISSUE THREAD

**Issue by martincostello** [dotnet/runtime#89014]
### Description

When using the Configuration binding source generator to compile and test an application on Linux, macOS and Windows the application fails to compile on Linux and macOS.

Exactly what is causing this I don't know, but I can reproduce it with three different repositories.

Logs for one such example can be found [here](https://github.com/martincostello/apple-fitness-workout-mapper/actions/runs/5576750181).

My own computer runs Windows, so I didn't find this issue until I pushed my local changes which were working to GitHub and the CI ran.

### Reproduction Steps

1. Clone and checkout any of the following commits:
    * https://github.com/martincostello/apple-fitness-workout-mapper/pull/726/commits/0910c24adce43dc6b95343c5bacd4201196d4963
    * https://github.com/martincostello/costellobot/commit/7389254d86a25b6a69cb664b131be8c011f92e0e
    * https://github.com/martincostello/dependabot-helper/commit/43085922094d7901002168f19cdd7234a2530e37
1. Run `build.ps1`.

### Expected behavior

The applications compile and the tests pass.

### Actual behavior

The application fails to compile on macOS and Linux with the following exception:

```
CSC : error CS8785: Generator 'ConfigurationBindingGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentOutOfRangeException' with message 'Specified argument was out of the range of valid values. (Parameter 'value')'
```

### Regression?

No.

### Known Workarounds

None.

### Configuration

.NET SDK 8.0.100-preview.6.23330.14

**Comment by vcsjones** [comment]
Could be related to https://github.com/dotnet/runtime/issues/88918

**Comment by layomia** [comment]
Can you try the suggestion here https://github.com/dotnet/runtime/issues/88918#issuecomment-1638659030?

**Comment by martincostello** [comment]
> Can you try the suggestion here [#88918 (comment)](https://github.com/dotnet/runtime/issues/88918#issuecomment-1638659030)?

[Still fails](https://github.com/martincostello/apple-fitness-workout-mapper/actions/runs/5585785134/jobs/10208965663?pr=841#step:4:80), but a slightly different error message:

```
CSC : error CS8785: Generator 'ConfigurationBindingGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentOutOfRangeException' with message 'repeatCount ('-4') must be a non-negative value. (Parameter 'repeatCount') [/home/runner/work/apple-fitness-workout-mapper/apple-fitness-workout-mapper/src/AppleFitnessWorkoutMapper/AppleFitnessWorkoutMapper.csproj]
```
