### ISSUE TITLE
[HttpClientFactory] ILoggerFactory dependency issue

### ISSUE THREAD

**Issue by CodeBlanch** [dotnet/runtime#89032]
Original post: https://github.com/dotnet/runtime/issues/77312#issuecomment-1625715837

## Description

I've run into (essentially) a circular reference issue because [DefaultHttpClientFactory takes a depedency on ILoggerFactory via ctor injection](https://github.com/dotnet/runtime/blob/fa40ecf7d36bf4e31d7ae968807c1c529bac66d6/src/libraries/Microsoft.Extensions.Http/src/DefaultHttpClientFactory.cs#L64).

OpenTelemetry has implemented an ILoggerProvider which may use HttpClient to export logs to different backends. We use IHttpClientFactory to allow users to control/customize the HttpClient instance. During construction of ILoggerFactory this provider is created which tries to access IHttpClientFactory which again tries to acces ILoggerFactory.

`ILoggerFactory -> OpenTelemetryLoggerProvider -> LogExporter -> IHttpClientFactory -> ILoggerFactory`

Ideally `DefaultHttpClientFactory` would not depend on `ILoggerFactory` so that it may be used in logging scenarios.

/cc @CarnaViire @noahfalk

**Comment by karelz** [comment]
Triage: Looks nasty without a workaround.
We should ask the providers to create HttpClient without public logging and we need to switch internal logging to EventSource instead of ILogger.
