### ISSUE TITLE
other than mscv in window, is there any way to compile nativeaot

### ISSUE THREAD

**Issue by NCLnclNCL** [dotnet/runtime#89069]
it seems nativeaot on windows now requires mscv

**Comment by huoyaoyuan** [comment]
If I've understood correctly, the linker of msvc is used, which is the only native linker on Windows. Rust also uses the linker.

**Comment by MichalStrehovsky** [comment]
Yes, we need link.exe, the C runtime, and the Windows SDK (things like kernel32.lib, etc.). It has always been like that and cannot be worked around (especially the C runtime part).
