### ISSUE TITLE
Revisit HttpRequestException.HttpRequestError type

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#89080]
We just merged a new API adding an `HttpRequestError` property to `HttpRequestException`.
```C#
public HttpRequestException(string? message, Exception? inner = null, HttpStatusCode? statusCode = null, HttpRequestError? httpRequestError = null);
public HttpRequestError? HttpRequestError { get; }
```
There is controversy over HttpRequestError, in particular that it's a `Nullable<HttpRequestError>` when HttpRequestError.Unknown also exists.  There are then two different ways to communicate that a meaningful HttpRequestError value could not be provided.

I propose the above be changed to instead be:
```C#
public HttpRequestException(HttpRequestError httpRequestError, string? message = null, Exception? inner = null, HttpStatusCode? statusCode = null);
public HttpRequestError HttpRequestError { get; }
```
- HttpRequestError parameter to the ctor is moved to be first
- message is given a nullable default value
- HttpRequestError property is made non-nullable

**Comment by terrajobst** [comment]
This makes sense to me. Let's talk about it later but this seems like an easy change.

**Comment by terrajobst** [comment]
* Makes sense as proposed

```diff
 namespace System.Net.Http;
 
 public class HttpRequestException : Exception
 {
     // Previously approved
-    public HttpRequestException(string? message, Exception? inner = null, HttpStatusCode? statusCode = null, HttpRequestError? httpRequestError = null);
-    public HttpRequestError? HttpRequestError { get; }

     // Newly approved
+    public HttpRequestException(HttpRequestError httpRequestError, string? message = null, Exception? inner = null, HttpStatusCode? statusCode = null);
+    public HttpRequestError HttpRequestError { get; }
 }
```
