### ISSUE TITLE
[Test Failure] System.Net.Sockets.Tests.SocketAsyncEventArgsTest.Finalizer_InvokedWhenNoLongerReferenced

### ISSUE THREAD

**Issue by rzikm** [dotnet/runtime#89089]
Failures seem to be concentrated on ARM runs on Mono

## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=334889
Build error leg or test failing: System.Net.Sockets.Tests.SocketAsyncEventArgsTest.Finalizer_InvokedWhenNoLongerReferenced
Pull request:

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step).

```json
{
  "ErrorMessage": "System.Net.Sockets.Tests.SocketAsyncEventArgsTest.Finalizer_InvokedWhenNoLongerReferenced(afterAsyncOperation: True) [FAIL]",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=334889
**Error message validated:** `System.Net.Sockets.Tests.SocketAsyncEventArgsTest.Finalizer_InvokedWhenNoLongerReferenced(afterAsyncOperation: True) [FAIL]`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 7/18/2023 3:30:04 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[351019](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351019)|dotnet/runtime|[System.Net.Sockets.Tests.SocketAsyncEventArgsTest.Finalizer_InvokedWhenNoLongerReferenced](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351019&view=ms.vss-test-web.build-test-results-tab&runId=7368550&resultId=103792)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|1|

**Comment by karelz** [comment]
@rzikm is it only on Mono and arm? If yes, can you please add those labels?
If it happens on more platforms and arm/Mono is just majority, then we should leave it as it is.

**Comment by fanyang-mono** [comment]
This seems to be a hiccup to me. It only happened once in the past month. Closing it now.
