### ISSUE TITLE
Detect name resolution errors in QuicConnection.ConnectAsync

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#89095]
*Edit:* see https://github.com/dotnet/runtime/issues/89095#issuecomment-1662978563.

----
https://github.com/dotnet/runtime/pull/88974/files#r1265843373 needs a follow-up:
https://github.com/antonfirsov/runtime/blob/b54e8c72cb63de3549ae4bff268d88daa628404c/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs#L146

**Comment by ManickaP** [comment]
Seems like dupe of https://github.com/dotnet/runtime/issues/82404

**Comment by antonfirsov** [comment]
Sorry, I forgot about that one. In case we want a simple fix for the `HttpRequestError` problem, I wonder if we can get rid of the `host.Equals(options.ClientAuthenticationOptions.TargetHost)` [special-casing](https://github.com/dotnet/runtime/blob/1ceed18aaa69f4bb72fd275cfa564816e25f3373/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs#L272-L273), always resolving the name & setting a `QUIC_PARAM_CONN_REMOTE_ADDRESS` to the first address? Or do we expect problematic side-effects from doing so? If we are unwilling to do such a change for 8.0, let's close this issue as a dupe of #82404.

**Comment by antonfirsov** [comment]
Tentatively re-assigned myself. Will bring it up in todays meeting, and file a PR if we have consensus. (If no, let's close it as a dupe.)

**Comment by wfurt** [comment]
I think that should be ok. It is more work but we do it anyway and it possibly opens avenue to deal better with names that remove to multiple addresses.
