### ISSUE TITLE
[HttpRequestError] Detect NameResolutionError more reliably

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#89096]
Follow up on https://github.com/dotnet/runtime/pull/88974/files#r1265749282:

https://github.com/antonfirsov/runtime/blob/b54e8c72cb63de3549ae4bff268d88daa628404c/src/libraries/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs#L4372-L4374

**Comment by antonfirsov** [comment]
When a SocketException is thrown by `Socket.ConnectAsync(DnsEndPoint)`, there is no reliable way to decide if it was coming `Dns.GetHostAddressesAsync()` or from the actual connect operation that follows the name resolution. `getaddrinfo` may return `EAI_AGIAN` on both [Linux ](https://man7.org/linux/man-pages/man3/getaddrinfo.3.html#RETURN_VALUE) and [Windows](https://learn.microsoft.com/en-us/windows/win32/api/ws2tcpip/nf-ws2tcpip-getaddrinfo#return-value), which is mapped to `SocketError.TryAgain`, and it may or may not be a temporary issue (eg. timeout). On CI we see `EAI_AGAIN`/`TryAgain` [being returned](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-89260-merge-d32f771393e5421d8b/System.Net.Http.Functional.Tests/3/console.a2e7eeba.log?helixlogtype=result) for invalid hosts on some Ubuntu images. It would be interesting to know why, but I think we can assume this can happen in any environment, and we should map these SocketExceptions to `HttpRequestError.NameResolutionError` in a reliable manner.

I see two ways to deal with this:
1. Define a way to reliably distinguish `SocketException` coming from `Dns.*` calls. Either store a field in `Exception.Data` (which costs 2x allocations, but we probably don't care on an exception path anyways), or define a new public `NameResolutionException : SocketException` subtype.
2. Since TCP `connect()` should not return `EAGAIN`/`WSATRY_AGAIN` according to the docs ([Linux](https://man7.org/linux/man-pages/man2/connect.2.html#ERRORS), [Windows](https://learn.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2)) and my limited research, we can decide to map all cases of `SocketError.TryAgain` to `HttpRequestError.NameResolutionError`. @wfurt @tmds any thoughts?

**Comment by antonfirsov** [comment]
The Linux man page of connect + EAGAIN actually says:
> For nonblocking UNIX domain sockets, the socket is nonblocking, and the connection cannot be completed immediately.  For other socket families, there are insufficient entries in the routing cache.

I'm not sure how common is the case with *"insufficient entries in the routing cache"*, but my gut feel is that it's much less likely than getting EAGAIN from `getaddrinfo`, which means that even if it's imperfect to classify all `TryAgain` errors as DNS errors because of some very rare edge-cases, it could be much better than the behavior we have now, where we falsely classify DNS errors as connection errors in known cases on our CI.

**Comment by wfurt** [comment]
We should check it but lack if Kernel resources should be rare and when that happen the system is in much bigger troubles IMHO. In future, we may add separate code for NameResolution failures IMHO but in mean time I feel mapping that into HttpRequestError should be fine. We should verify the completeness as there could at least two types of failures: The resolver asked but did not get answer on time. And then it asked and there was authoritative answer that given host does not exist.

**Comment by antonfirsov** [comment]
> We should verify the completeness as there could at least two types of failures

I'm not sure I follow what do you mean by this. I'm suggesting to map both `SocketError.HostNotFound` and `SocketError.TryAgain` to `HttpRequestError.NameResolutionError`. If someone is interested which of these two cases caused the `HttpRequestException`, they can observe the inner `SocketException`.

Are you suggesting there might be other cases we are missing?

**Comment by wfurt** [comment]
that should be fine. That generally covers two cases I had in mind.
