### ISSUE TITLE
[Test Failure] Long running test: SslStreamMemoryConformanceTests.ReadWrite_Success_Large

### ISSUE THREAD

**Issue by rzikm** [dotnet/runtime#89092]
https://[helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-b55530f4919e4a4398/System.Net.Security.Tests/1/console.66ad7591.log?helixlogtype=result](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-b55530f4919e4a4398/System.Net.Security.Tests/1/console.66ad7591.log?helixlogtype=result)

We should at least check the test if more timeouts are needed to convert it to regular test failure.

## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=338272
Build error leg or test failing: System.Net.Security.Tests.SslStreamMemoryConformanceTests.ReadWrite_Success_Large
Pull request:

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step).

```json
{
  "ErrorMessage": "[Long Running Test] 'System.Net.Security.Tests.SslStreamMemoryConformanceTests.ReadWrite_Success_Large'",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=338272
**Error message validated:** `[Long Running Test] 'System.Net.Security.Tests.SslStreamMemoryConformanceTests.ReadWrite_Success_Large'`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 7/18/2023 3:34:19 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[412786](https://dev.azure.com/dnceng-public/public/_build/results?buildId=412786)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=412786&view=ms.vss-test-web.build-test-results-tab&runId=9004814&resultId=104316)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|1|

**Comment by karelz** [comment]
Triage: Rare occurrence. We should check if we can add some timeouts to the test to make it easier to analyze.
Moving to 9.0.
