### ISSUE TITLE
[API Proposal]: Expose DefaultJsonTypeInfoResolver.RootDefaultInstance

### ISSUE THREAD

**Issue by cakescience** [dotnet/runtime#89113]
### Background and motivation

Today, when using the JSON source generator, if a type is not declared in the `TypeInfoResolver` used, a `NotSupportedException` is thrown like:
```
System.NotSupportedException: 'JsonTypeInfo metadata for type 'Todo[]' was not provided by TypeInfoResolver of type '[AppJsonSerializerContext]'. If using source generation, ensure that all root types passed to the serializer have been annotated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically.'
```
To have a fallback to the reflection-based JSON contract resolver, it is necessary (as far as I know and understand) to use the `DefaultJsonTypeInfoResolver`.

For example:

```c#
JsonSerializerOptions jsonSerializerOptions = new JsonSerializerOptions
{
    TypeInfoResolverChain = { AppJsonSerializerContext.Default, new DefaultJsonTypeInfoResolver() }
};

Todo[] todos = new Todo[] { new Todo("Todo1"), new Todo("Todo2") };
string json = JsonSerializer.Serialize<Todo[]>(todos, jsonSerializerOptions);

// Todo[] is not declared in this context
[JsonSerializable(typeof(Todo))]
internal partial class AppJsonSerializerContext : JsonSerializerContext
{
}
```

To use `DefaultJsonTypeInfoResolver` today, it is necessary to instantiate it manually, while this class holds a default instance which is a singleton. If this singleton is exposed, it would not be necessary to create a new instance each time.

### API Proposal

```diff
namespace System.Text.Json.Serialization.Metadata;

public partial class DefaultJsonTypeInfoResolver : IJsonTypeInfoResolver, IBuiltInJsonTypeInfoResolver
{
-    internal static DefaultJsonTypeInfoResolver RootDefaultInstance()
+    public static DefaultJsonTypeInfoResolver RootDefaultInstance()
}
```

### API Usage

```csharp
JsonSerializerOptions jsonSerializerOptions = new JsonSerializerOptions
{
    TypeInfoResolverChain = { AppJsonSerializerContext.Default, DefaultJsonTypeInfoResolver.RootDefaultInstance() }
};
```

### Alternative Designs

I am not sure if we should expose the method `RootDefaultInstance()` or `s_defaultInstance`

https://github.com/dotnet/runtime/blob/21f07e17b0874a898c660afc07261c70a2cb867d/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/DefaultJsonTypeInfoResolver.cs#L131

### Risks

To be quite honest, I'm not confident about this proposal and don't know if it's a good idea. I am open to any feedback or corrections.

**Comment by eiriktsarpalis** [comment]
Creating a new `JsonSerializerOptions` for serialization is a super expensive operation, whereas creating a new resolver instance is cheap (it only costs one allocation). As such, I don't think there would be huge value in exposing the singleton (if anything adding was probably overkill in the first place).
