### ISSUE TITLE
Dotnet 7 can not work with openssl 1.1.1f

### ISSUE THREAD

**Issue by Samcoder2000** [dotnet/runtime#89126]
### Description

Here's the one-line summary of our findings:
When running an application in .NET 7 with FIPS enforced using openssl 1.1.1f, it shows ERR_SSL_PROTOCOL_ERROR.

Host machine:
Built on Ubuntu Pro 18.04, running kernel 4.15.0-2043-gcp-fips

Working configurations:
- OpenSSL 1.1.1-1ubuntu2.fips.2.1~18.04.23 (Ubuntu Pro 18.04 fips-updates latest version) with our .NET 7 application shows no issue.
- Building the application in .NET 6 shows no SSL issue with any FIPS OpenSSL package. The application can work with openssl 1.1.1 and 1.1.1f.

Broken configuration:
- Upgrading OpenSSL and dependencies to 1.1.1f-1ubuntu2.fips.19 (Ubuntu Pro 20.04 fips-updates latest version) causes an SSL error when connecting to our .NET 7 application.  

Here's the curl output when the application is in the broken state:

curl -vvv https://***.com
*  Trying 34.*.*.*:443...
* TCP_NODELAY set
* Connected to ***.com (34.*.*.*) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
 CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS alert, no application protocol (632):
* error:14094460:SSL routines:ssl3_read_bytes:reason(1120)
* Closing connection 0
curl: (35) error:14094460:SSL routines:ssl3_read_bytes:reason(1120)

Attempting to connect to the webserver using a Chromium-based browser shows "ERR_SSL_PROTOCOL_ERROR"

Do you have any insights that how can we solve this issue? Thanks. 

### Reproduction Steps

1. Use ubuntu pro 18.04.
2. Upgrade openssl to 1.1.1f from 1.1.1
3. Build the application with dotnet 7

### Expected behavior

No ssl protocol error.

### Actual behavior

Showing ssl protocol error.

**Comment by wfurt** [comment]
What is the exception and did you look what is going on on the wire? It seems like the curl also fails - or do I get it wrong?

**Comment by Samcoder2000** [comment]
> 

That is not the exception, our code doesn't get any exception. I am not sure I understand it correctly: it seems like to me that Dotnet uses the openssl trying to establish the connection but fails. Dotnet handles it by itself, our code doesn't get involved. Yes, curl fails as well.

**Comment by karelz** [comment]
Triage: If it needs a change in .NET, we will likely have to backport it to 7.0 and 6.0.
Therefore, we should investigate earlier rather than later.

**Comment by Samcoder2000** [comment]
@karelz Thanks. I attached the code of our project which got this error.
Pls let me know if you need more information. Thanks.

[simplewebserver.zip](https://github.com/dotnet/runtime/files/12112568/simplewebserver.zip)

**Comment by wfurt** [comment]
where is the certificate? Is it possible it uses weak or unsupported crypto? (blocked by the FIPS version) 
You can look at openssl.conf and possibly fiddle with the security levels.

**Comment by Samcoder2000** [comment]
Sorry, we are not able to share the certificate due to the security. 

The certificate and the setting of openssl should be good. If I change the my simple app to use Dotnet 6 and leave everything unchanged(same openssl 1.1.1f, openssl.cnf and certificate ) then there is no this "ERR_SSL_PROTOCOL_ERROR" error.

**Comment by wfurt** [comment]
right, but that can still be because FIPS limits some ciphers. We can try to reproduce and go from there.

**Comment by wfurt** [comment]
BTW you don't need to share your production certificate - just something structurally similar that can reproduce the problem. The easier it is for us to reproduce the more likely it gets look at.

**Comment by Samcoder2000** [comment]
Okey, let me try to get a similar certificate and will share here. Thanks.

**Comment by Samcoder2000** [comment]
I tested this attached certificate, I got the same error. Pls let me know if you need more information from me. Thanks.
[certificate.zip](https://github.com/dotnet/runtime/files/12134575/certificate.zip)

**Comment by wfurt** [comment]
I cannot reproduce it @Samcoder2000. I got 18.04 container. I enabled the Pro, did all updates and everything was fine. (tested externally with curl) 

So I updated to 20.04, got `OpenSSL 1.1.1f` and everything keeps working. 
You can probably do packet capture with Wireshark (or tcpdump)

**Comment by Samcoder2000** [comment]
@wfurt Thanks for working on this case. I have some questions: 
1: when you reproduce this issue, did you enable the strict FIPS enforcement? Within a container is more complicated, but on the Ubuntu Pro host you can run this command:
`sudo ua enable fips-updates --assume-yes`

2: Have you update the openssl to 1.1.1f when using 18.04 pro?

Thanks again.

**Comment by wfurt** [comment]
yes.
```
root@c320ab739873:/#  ua enable fips-updates --assume-yes
One moment, checking your subscription first
FIPS Updates is already enabled.

root@c320ab739873:/# openssl version -a
OpenSSL 1.1.1f  31 Mar 2020
built on: Mon Jun 12 13:22:06 2023 UTC
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(int) blowfish(ptr)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -fdebug-prefix-map=/build/openssl-6iH9fG/openssl-1.1.1f=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_TLS_SECURITY_LEVEL=2 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-1.1"
Seeding source: os-specific
```

As I mentioned above, I did not get  1.1.1f update using 18.04 baseline. So my container is 20.04 with FIPS + OpenSSL 1.1.1f.

**Comment by Samcoder2000** [comment]
@wfurt Thanks for sharing the information. 

I have a question: does your server enable the strict FIPS enforcement when you run your container? Can you pls try running this command:
`echo 'content' > /tmp/test & openssl md5 /tmp/test;
`
in your container? If FIPS is enforced, it will immediately fail with an error stating that MD5 is not allowed by FIPS.



By the way, I have attached a simple container which is using Ubuntu 22.04 with openssl 3.0 and FIPS enabled.  you can run this command to create the container image: 
`./simplewebserver.sh build
`
and if you run this container on any server(with FIPS or without FIPS enforcement), you will get this:
![image](https://github.com/dotnet/runtime/assets/22242969/006f1b6a-b396-457f-8a41-8a104c4357cb)
We see this issue when using openssl 3.0 before(both dotnet 6 and dotnet 7), however we don't want to confuse you with the openssl 1.1.1f issue. So we didn't bring it up. Hope this can help your troubleshooting.
[simplewebservercontainer.zip](https://github.com/dotnet/runtime/files/12234053/simplewebservercontainer.zip)

**Comment by wfurt** [comment]
what is your client? Did you do the packet capture to look at the TLS handshake?

**Comment by Samcoder2000** [comment]
The client is Chrome. This is the curl info:
```
:~/SimpleWebServer$ curl https://127.0.0.1:10001 -v
*   Trying 127.0.0.1:10001...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 10001 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS alert, protocol version (582):
* error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
* Closing connection 0
curl: (35) error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
```

I am working on capturing the packet, however I will need our security team to review the data before I can share it with you.

**Comment by Samcoder2000** [comment]
@wfurt @karelz I have my data reviewed by our security team, I should be able to share it. Do you mind giving me an email address that I can send my file link to? Thanks.

**Comment by wfurt** [comment]
just use my GH address @Samcoder2000

**Comment by Samcoder2000** [comment]
@wfurt Thank you. I have sent the file to you.

**Comment by Monochromics** [comment]
@Samcoder2000 Hello!

I think I may have found the issue. Is there a particular reason you're installing+fips`ifying` openssl from upstream, rather than using the debs provided by Canonical? I grabbed your archives above for testing, and when I dropped the upstream installs, everything seemed to work as expected on .net7. I'm assuming there are some missing sauce/configs that are creating the issue.

I also confirmed that porting the debs over and using the Canonical provided fips openssl releases, it still worked. There are 2 main methods to accomplish there here[1] and here[2], depending on if you want to leverage BUILDKIT and attach directly at build time. 

[1] https://ubuntu.com/blog/building-and-running-fips-containers-on-ubuntu18-04
[2] https://github.com/canonical/ubuntu-pro-client/blob/docs-devel/docs/howtoguides/enable_in_dockerfile.md

Cheers

**Comment by Samcoder2000** [comment]
Hi @Monochromics, 
Thank you for helping with this case. Yeah, we need the FIPS module to be installed when config the docker image. 

BTW you mean you can reproduce the issue? and you removed the FIPS module then the issue was gone?

**Comment by Monochromics** [comment]
@Samcoder2000 Yes, with your jammy repro container (as well as when bumping it down to focal) I can reproduce. The issue goes away when removing the upstream openssl fips install RUN. It also still works when using Canonical's fips compliant openssl version inside of the containers (tested with method 2 mentioned in the above comment to install at build time).

I didn't test against .net6 since 7 was already working. I'm far from a .net expert, but looking at the changelog from 6->7 it does appear there were some crypto changes. This probably created an incompatibility with the raw upstream packages that Canonical addressed at openssl-fips build time.

**Comment by Samcoder2000** [comment]
@Monochromics we would like to use openssl 3.0 so we will try your second method with ubuntu 22.04 pro to see if it works. Thank you very much.

**Comment by wfurt** [comment]
did you make any progress @Samcoder2000? I don't think we would be able to help without getting good repro.

**Comment by Samcoder2000** [comment]
@wfurt  We found a workaround to only use tls 1.2 for ssl connections. We are still trying to see if we can use the ubuntu pro to create a docker image to run our application.

**Comment by karelz** [comment]
Triage: We couldn't reproduce it, likely network appliance problem. There is workaround to downgrade TLS version. Closing.
