### ISSUE TITLE
Test build fails with "libSystem.IO.Ports.Native.so.dbg' to be packed was not found on disk."

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#89146]
***Note: this build break causes all "coreclr Pri0 runtime tests..." to be skipped***

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=344136
Build error leg or test failing: Build / coreclr Common Pri0 Test Build AnyOS AnyCPU checked / Build coreclr/libs components needed by test build
Pull request: https://github.com/dotnet/runtime/pull/87656

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "NuGet\\.Build\\.Tasks\\.Pack\\.targets.+libSystem\\.IO\\.Ports\\.Native\\.so\\.dbg' to be packed was not found on disk",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=344136
**Error message validated:** `NuGet\.Build\.Tasks\.Pack\.targets.+libSystem\.IO\.Ports\.Native\.so\.dbg' to be packed was not found on disk`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 7/18/2023 11:38:21 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[344790](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344790)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344790/logs/13)||
|[344778](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344778)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344778/logs/62)||
|[344043](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344043)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344043/logs/2477)|dotnet/runtime#89036|
|[344743](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344743)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344743/logs/609)|dotnet/runtime#89174|
|[344719](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344719)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344719/logs/636)|dotnet/runtime#88986|
|[344591](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344591)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344591/logs/2625)|dotnet/runtime#89162|
|[344695](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344695)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344695/logs/257)||
|[344527](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344527)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344527/logs/2346)|dotnet/runtime#89130|
|[344683](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344683)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344683/logs/757)||
|[344680](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344680)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344680/logs/84)||
|[344662](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344662)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344662/logs/115)||
|[344661](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344661)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344661/logs/61)||
|[344656](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344656)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344656/logs/451)|dotnet/runtime#89088|
|[344651](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344651)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344651/logs/289)|dotnet/runtime#88878|
|[344632](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344632)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344632/logs/96)||
|[344633](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344633)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344633/logs/75)||
|[344627](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344627)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344627/logs/285)|dotnet/runtime#89159|
|[344631](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344631)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344631/logs/135)||
|[344604](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344604)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344604/logs/298)|dotnet/runtime#85694|
|[344602](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344602)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344602/logs/83)||
|[344601](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344601)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344601/logs/137)||
|[344595](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344595)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344595/logs/330)|dotnet/runtime#89059|
|[344600](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344600)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344600/logs/30)|dotnet/runtime#89059|
|[344559](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344559)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344559/logs/784)|dotnet/runtime#89156|
|[344560](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344560)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344560/logs/786)|dotnet/runtime#89156|
|[344557](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344557)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344557/logs/94)||
|[344550](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344550)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344550/logs/800)|dotnet/runtime#89147|
|[344534](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344534)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344534/logs/302)|dotnet/runtime#89159|
|[344454](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344454)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344454/logs/774)|dotnet/runtime#89156|
|[344444](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344444)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344444/logs/664)|dotnet/runtime#89153|
|[344442](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344442)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344442/logs/249)||
|[344437](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344437)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344437/logs/706)|dotnet/runtime#89152|
|[344427](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344427)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344427/logs/618)|dotnet/runtime#89155|
|[344421](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344421)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344421/logs/610)|dotnet/runtime#89154|
|[344254](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344254)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344254/logs/1360)|dotnet/runtime#89142|
|[344398](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344398)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344398/logs/640)|dotnet/runtime#89151|
|[344340](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344340)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344340/logs/388)|dotnet/runtime#87438|
|[344330](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344330)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344330/logs/421)|dotnet/runtime#89061|
|[344321](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344321)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344321/logs/671)|dotnet/runtime#89147|
|[344317](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344317)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344317/logs/332)|dotnet/runtime#89123|
|[344313](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344313)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344313/logs/469)|dotnet/runtime#89145|
|[344296](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344296)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344296/logs/711)|dotnet/runtime#89102|
|[344290](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344290)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344290/logs/387)|dotnet/runtime#87847|
|[344284](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344284)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344284/logs/624)|dotnet/runtime#89144|
|[344268](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344268)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344268/logs/667)|dotnet/runtime#89130|
|[344261](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344261)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344261/logs/711)|dotnet/runtime#85328|
|[344239](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344239)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344239/logs/664)|dotnet/runtime#86089|
|[344207](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344207)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344207/logs/277)|dotnet/runtime#89129|
|[344182](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344182)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344182/logs/301)|dotnet/runtime#89135|
|[344136](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344136)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344136/logs/325)|dotnet/runtime#87656|
|[344129](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344129)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344129/logs/284)||
|[344112](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344112)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344112/logs/385)|dotnet/runtime#85734|
|[344099](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344099)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344099/logs/302)|dotnet/runtime#89064|
|[344092](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344092)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344092/logs/332)|dotnet/runtime#89116|
|[344056](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344056)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344056/logs/270)|dotnet/runtime#89123|
|[344049](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344049)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344049/logs/698)||
|[344020](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344020)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344020/logs/477)|dotnet/runtime#89121|
|[344014](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344014)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344014/logs/398)|dotnet/runtime#89061|
|[343994](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343994)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/343994/logs/364)|dotnet/runtime#87438|
|[343982](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343982)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/343982/logs/706)|dotnet/runtime#85328|
|[343993](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343993)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/343993/logs/237)|dotnet/runtime#87438|
|[343954](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343954)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/343954/logs/255)|dotnet/runtime#88723|
|[343938](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343938)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/343938/logs/287)|dotnet/runtime#88941|
|[343935](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343935)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/343935/logs/504)|dotnet/runtime#88723|
|[343925](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343925)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/343925/logs/337)|dotnet/runtime#84542|
|[343905](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343905)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/343905/logs/391)|dotnet/runtime#89011|
|[343871](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343871)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/343871/logs/643)|dotnet/runtime#89115|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|67|67|67|

**Comment by JulieLeeMSFT** [comment]
Removed Known Build Error label because it is skipping all the coreclr Pri0 tests from other PRs.

**Comment by jakobbotsch** [comment]
@ViktorHofer Could this be caused by #89115? From the table that seems to be the first pipeline run with this failure, but it's quite hard to determine when it was introduced.

**Comment by ViktorHofer** [comment]
Yes that's on me. Will send another PR.
