### ISSUE TITLE
OpenSSL provider support 

### ISSUE THREAD

**Issue by krwq** [dotnet/runtime#89167]
In https://github.com/dotnet/runtime/pull/88656 we've added ENGINE support but we've left out providers pending more investigation on issues discovered during implementation. This API was already approved last year but asking for re-approval given time which passed.
Original issue: https://github.com/dotnet/runtime/issues/55356 

### Background

ENGINE and providers are plug-in systems for OpenSSL which allow to make custom implementation of some crypto algorithms. That enables scenarios such as using TPM keys.

ENGINE is an old (now deprecated) plug-in system which was the only FIPS approved plugin system until recently. Providers is new plug-in system allowing a bit more flexibility to developers (but also harder to implement).

### Proposal

```csharp
namespace System.Security.Cryptography
{
    public partial class SafeEvpPKeyHandle
    {
        // existing OpenSSL ENGINE APIs (only plugin model for OSSL 1.1, deprectated (but present) in 3.0+)
        // public static SafeEvpPKeyHandle OpenPrivateKeyFromEngine(string engineName, string keyId) => throw null;
        // public static SafeEvpPKeyHandle OpenPublicKeyFromEngine(string engineName, string keyId) => throw null;

        // OpenSSL Providers (new plugin model for OSSL 3.0+)
        public static SafeEvpPKeyHandle OpenKeyFromProvider(string providerName, string keyUri) => throw null;
    }
}
```

### Usage Example

```csharp
byte[] data = ...;

// For TPM settings refer to provider documentation you're using, i.e. https://github.com/tpm2-software/tpm2-openssl/tree/master
// specific values are just example
using (SafeEvpPKeyHandle priKeyHandle = SafeEvpPKeyHandle.OpenKeyFromProvider("tpm2", "handle:0x81000007"))
using (ECDsa ecdsaPri = new ECDsaOpenSsl(priKeyHandle))
{
    byte[] signature = ecdsaPri.SignData(data, HashAlgorithmName.SHA256);
    // do stuff with signature
    // note: tpm2 does not allow Verify operations, public key needs to be exported and re-imported into new instance
}
```

### Security considerations

Those APIs are not meant to be used with untrusted inputs. Allowing untrusted inputs may potentially allow attacker to use TPM or other private keys in an unintended way. Some providers i.e. "default" allow reading files from arbitrary paths (in order to read the key) which makes it further dangerous to use with untrusted inputs. Additionally providerName may load libraries into the process which adds additional risk (depending on OSSL_PROVIDER_set_default_search_path setting this may or may not be a big issue).

(considerations also apply to already added ENGINE APIs)

**Comment by vcsjones** [comment]
I'm not sure that a new API shape is needed; or that the suggestion here is the right approach. For all other crypto primitives in .NET, the object itself maintains all related handles to keep things working so that two things with two independent lifetimes need to be managed.

Using the example above:


```C#
OpenSslProvider provider = new("some_pkcs11_module");
SafeEvpPKeyHandle foo = provider.OpenRSAPrivateKey("my key uri");
provider.Dispose();
RSA rsa = new RSAOpenSsl(foo); // What happens here?
```

Trying to make that work sensibly, even just making sure we throw a managed exception instead of a SIGSEGV, I think would be difficult. 

I think it probably makes sense to have the provider lifetime managed by the `SafeEvpPKeyHandle`. We have similar concepts already

1. NCrypt has parent handles:
         https://github.com/dotnet/runtime/blob/d051a846e333c3c350db328ba3c6206a99ef2097/src/libraries/System.Security.Cryptography/src/Microsoft/Win32/SafeHandles/NCryptSafeHandles.cs#L75-L75

    We use this to keep a CERT_CONTEXT alive when getting a key off of the certificate. 

    https://github.com/dotnet/runtime/blob/d051a846e333c3c350db328ba3c6206a99ef2097/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/CertificatePal.Windows.PrivateKey.cs#L260

2. macOS does not require you to manage a keychain lifetime separately from the key itself.

I view the way we could solve this with `OSSL_LIB_CTX*` similarly: A `SafeEvpPKeyHandle` could keep a related handle / parent handle so that developers do not have independent object lifetimes to manage.

**Comment by krwq** [comment]
Note: I've updated proposal to look as it was before.

**Comment by krwq** [comment]
per offline discussion with @bartonjs it's already approved so it doesn't need to be re-approved. PR should point to the old issue which approved it

**Comment by terrajobst** [comment]
(marking as api-approved for clarity)
