### ISSUE TITLE
[API Proposal]: HttpMethod.From(string)

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#89161]
### Background and motivation

HttpMethod provides a constructor (`string method = ...; ... = new HttpMethod(method);`), but the 99.999% case is that one of the static properties on HttpMethod suffices, and folks end up writing their own mapping tables to use those singletons.  We can just provide that mapping once.

### API Proposal

```diff
namespace System.Net.Http;

public class HttpMethod
{
// Case insensitive - to match our logic in Networking stack
+   public static HttpMethod From(ReadOnlySpan<char> method);
// Alternative names: Parse / Get / Create

//   public static HttpMethod From(string method); ... OPTIONAL, Networking team thinks it is NOT necessary

/*
        method switch
        {
            "GET" => s_getMethod,
            "PUT" => s_putMethod,
            "POST" => s_postMethod,
            "DELETE" => s_deleteMethod,
            "HEAD" => s_headMethod,
            "OPTIONS" => s_optionsMethod,
            "TRACE" => s_traceMethod,
            "PATCH" => s_patchMethod,
            "CONNECT" => s_connectMethod,
            _ => new HttpMethod(method);
        };
*/
} 
```

### API Usage

```csharp
string methodName = ...;
HttpMethod method = HttpMethod.From(methodName);
```

**Comment by ShreyasJejurkar** [comment]
I can take this one for implementation once it's approved! 🙌

**Comment by KeterSCP** [comment]
Have you thought about naming it `Parse`?

Yeah, I know that there is not much parsing involved, but still it seems to be more consistent with other APIs

**Comment by karelz** [comment]
Triage: Makes sense, top post updated with discussion results.

**Comment by bartonjs** [comment]
* We think that the method should be `Parse` instead of `From`.
* It's probably reasonable for the method to do case normalization and maybe trimming ("get " -> "GET")
* It's mildly unfortunate for the 0.01% case when it hits the unknown case that it could be string -> ROS-char -> new allocated string, but since it's expected to be 0.01%, it's fine.

```C#
namespace System.Net.Http;

public class HttpMethod
{
    public static HttpMethod Parse(ReadOnlySpan<char> method);
}
```

**Comment by MihaZupan** [comment]
> and maybe trimming

If you give us garbage we could just let the constructor throw and have the caller fix their substring/slice 🤷‍♂️ Don't care too much about it though.

**Comment by Neme12** [comment]
Maybe it should implement `IParsable` as well if it has a `Parse` method? That just seems like general goodness so that serialization frameworks would automatically be able to deserialize this type.
