### ISSUE TITLE
How can I use system.web as a configuration section in a asp.net net472 app that uses System.Configuration.ConfigurationManager

### ISSUE THREAD

**Issue by dschwartzni** [dotnet/runtime#89169]
I am migrating a large .net framework application to net6.  The strategy I am using is to migrate libraries to netstandard2.0 while keeping the net472 runtime until the application is ready to migrate completely.

As part of the process, I need to upgrade from System.Configuration (only net472) to System.Configuration.ConfigurationManager (netstandard2.0) version 6.0.0.  However, when I update all references in my code, my ASP.net web service running returns this error:

    Unrecognized configuration section system.web

Some details:

 1. ASP.Net application is running on IIS
 2. IIS is using some of the settings in the system.web section of the configuration
 3. ASP.Net application is running on the netframework 4.7.2 (not netcore/net6)
 4. If I include System.Configuration as well, then it fails on a DLL mismatch.  If I don't, I get this error

How can I get my application to retrieve the configuration and not fail on this error?

**Comment by ericstj** [comment]
The `System.Configuration.ConfigurationManager` package does not provide any implementation for a `net472` application, instead it type-forwards the implementation in System.Configuration.  Can you double check that you are referencing the `System.Configuration.ConfigurationManager` package in the `net472` app and not accidentally using the netstandard implementation of Configuration which doesn't support all the features present in the .NETFramework version?  

If you still face issues, please share a repro application.

**Comment by dschwartzni** [comment]
@ericstj 
So, I should add back System.Configuration to the application?

If so, when I do that, I get compile errors that the class has a conflict between System.Configuration.ConfigurationManager and System.Configuration

How should I handle that?

**Comment by ericstj** [comment]
> So, I should add back System.Configuration to the application?

> If so, when I do that, I get compile errors that the class has a conflict between System.Configuration.ConfigurationManager and System.Configuration

That's actually a symptom that you're referencing the *wrong* `System.Configuration.ConfigurationManager` in your application.  The `System.Configuration.ConfigurationManager.dll` that's specific to `net472` does not define any types so you should not see an error.

You need to make sure your application references both the `System.Configuration.ConfigurationManager` package and the `System.Configuration` assembly (note the latter should be added automatically when referencing the `System.Configuration.ConfigurationManager` package.  The package will provide the following assembly which typeforwards all types to `System.Configuration`:
```
system.configuration.configurationmanager\6.0.1\lib\net461\System.Configuration.ConfigurationManager.dll
```

**Comment by dschwartzni** [comment]
> > So, I should add back System.Configuration to the application?
> 
> > If so, when I do that, I get compile errors that the class has a conflict between System.Configuration.ConfigurationManager and System.Configuration
> 
> That's actually a symptom that you're referencing the _wrong_ `System.Configuration.ConfigurationManager` in your application. The `System.Configuration.ConfigurationManager.dll` that's specific to `net472` does not define any types so you should not see an error.
> 
> You need to make sure your application references both the `System.Configuration.ConfigurationManager` package and the `System.Configuration` assembly (note the latter should be added automatically when referencing the `System.Configuration.ConfigurationManager` package. The package will provide the following assembly which typeforwards all types to `System.Configuration`:
> 
> ```
> system.configuration.configurationmanager\6.0.1\lib\net461\System.Configuration.ConfigurationManager.dll
> ```

Switching the System.Configuration.ConfigurationManager to the net472 one in the application bin folder solved the issue
