### ISSUE TITLE
[mono][tests] SocketException : Can't assign requested address [::]:0

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#89180]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=344698
Build error leg or test failing: iossimulator-x64 Release AllSubsets_Mono
Pull request: https://github.com/dotnet/runtime/pull/87916

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "System.Net.Sockets.SocketException : Can't assign requested address",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```
```
[FAIL] System.Net.Sockets.Tests.ConnectSync.Connect_DatagramSockets_DontThrowConnectedException_OnSecondAttempt   Test name: System.Net.Sockets.Tests.ConnectSync.Connect_DatagramSockets_DontThrowConnectedException_OnSecondAttempt(listenAt: ::1, secondConnection: ::)   Test case: System.Net.Sockets.Tests.ConnectSync.Connect_DatagramSockets_DontThrowConnectedException_OnSecondAttempt
   Assembly:  [System.Net.Sockets.Tests, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]
2023-07-19 04:15:23.846 Df System.Net.Sockets.Tests[81773:e4132]    Exception messages: System.Net.Sockets.SocketException : Can't assign requested address [::]:0   Exception stack traces:    at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
2023-07-19 04:15:23.847 Df System.Net.Sockets.Tests[81773:e4132]    at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Tests.SocketHelperArraySync.<>c__DisplayClass3_0.<ConnectAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__281_0(Object obj)
2023-07-19 04:15:23.848 Df System.Net.Sockets.Tests[81773:e4132]    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
```
/cc: @liveans 

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=344698
**Error message validated:** `System.Net.Sockets.SocketException : Can't assign requested address`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 7/19/2023 12:48:05 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[344698](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344698)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344698&view=ms.vss-test-web.build-test-results-tab&runId=7207360&resultId=194741)||
|[344603](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344603)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344603&view=ms.vss-test-web.build-test-results-tab&runId=7203854&resultId=194735)|dotnet/runtime#85694|
|[344129](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344129)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344129&view=ms.vss-test-web.build-test-results-tab&runId=7194170&resultId=194718)||
|[343954](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343954)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343954&view=ms.vss-test-web.build-test-results-tab&runId=7190862&resultId=194687)|dotnet/runtime#88723|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|4|4|4|

**Comment by ivanpovazan** [comment]
Dup of: https://github.com/dotnet/runtime/issues/89166 
Feel free to adjust it (or this issue).
