### ISSUE TITLE
NU5129 warning for System.Resources.Extensions package

### ISSUE THREAD

**Issue by mthalman** [dotnet/runtime#89208]
When building the runtime repo with the latest build of the .NET 8 Preview 7 SDK, the following warning  occurs:

```
/vmr/.dotnet/sdk/8.0.100-preview.7.23369.1/Sdks/NuGet.Build.Tasks.Pack/buildCrossTargeting/NuGet.Build.Tasks.Pack.targets(221,5): warning NU5129: - At least one .targets file was found in 'buildTransitive/', but 'buildTransitive/System.Resources.Extensions.targets' was not. [/vmr/src/runtime/artifacts/source-build/self/src/src/libraries/System.Resources.Extensions/src/System.Resources.Extensions.csproj]
/vmr/.dotnet/sdk/8.0.100-preview.7.23369.1/Sdks/NuGet.Build.Tasks.Pack/buildCrossTargeting/NuGet.Build.Tasks.Pack.targets(221,5): warning NU5129:  [/vmr/src/runtime/artifacts/source-build/self/src/src/libraries/System.Resources.Extensions/src/System.Resources.Extensions.csproj]
```

**Comment by ericstj** [comment]
I couldn't reproduce. I was using 8.0.100-preview.7.23369.9 SDK.  Here's the content of that package, I don't see what it would be complaining about.  If it's complaining about `_._` that'd be a bug, since that's a special file to create an empty directory.
```
buildTransitive\net461\System.Resources.Extensions.targets
buildTransitive\net462\System.Resources.Extensions.targets
buildTransitive\net6.0\_._
buildTransitive\netcoreapp2.0\System.Resources.Extensions.targets
```

Can you share a binlog?

**Comment by mthalman** [comment]
Ok, it's actually a warning and does not fail the build. I misinterpreted what I was seeing since some another error was mixed in there. Binlog is too big to attach. But you can access it with this [internal link](https://artprodcus3.artifacts.visualstudio.com/Ab55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy9wcm9qZWN0SWQvN2VhOTExNmUtOWZhYy00MDNkLWIyNTgtYjMxZmNmMWJiMjkzL2J1aWxkSWQvMjIyNTE1Ni9hcnRpZmFjdE5hbWUvQ2VudE9TU3RyZWFtOF9PbmxpbmVfQ3VycmVudFNvdXJjZUJ1aWx0U2RrX3g2NF9CdWlsZExvZ3NfQXR0ZW1wdDE1/content?format=file&subPath=%2Fsrc%2Fruntime%2Fartifacts%2Fsource-build%2Fself%2Fsrc%2Fartifacts%2Fsourcebuild.binlog). As I mentioned, there's an unrelated error showing up in there so change the search filter to `$warning` to see the issue.

**Comment by ericstj** [comment]
Looks to me like this is the cause:
<img width="600" alt="image" src="https://github.com/dotnet/runtime/assets/8918108/6202431b-1f79-4836-a044-5a5716356285">

It's coming from here:
https://github.com/dotnet/runtime/blob/bd471dc6f18baacb12bf32370f93676f38daff63/src/libraries/System.Resources.Extensions/src/System.Resources.Extensions.csproj#L71-L72

And the reason seems to be that source build unsets this property.
https://github.com/dotnet/runtime/blob/643087b28c42f1ea0fbb645ba9f7cbcb2f334060/Directory.Build.props#L110-L111

Probably we can just put a condition on this.
