### ISSUE TITLE
Stream.Read - document 0-byte reads

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#89233]
`Stream` does not have 0-byte reads documented clearly, which is causing confusion - see #88792

Affected APIs:
- [Stream.Read](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.read)
- [Stream.ReadAsync](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.readasync)

**Comment by svick** [comment]
I think this is a duplicate of https://github.com/dotnet/dotnet-api-docs/issues/9155.
