### ISSUE TITLE
Move tests from full facade assemblies into type forward destination

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#89230]
https://github.com/dotnet/runtime/pull/89184 moved full façade assemblies into src/libraries/shims but left the tests in their original location. This issue tracks moving the tests and their test projects into the type forward destination (in most cases System.Runtime/tests/):

- [x] System.AppContext
- [x] System.Buffers
- [x] System.Data.DataSetExtensions
- [x] System.Diagnostics.Debug
- [x] System.Diagnostics.Tools
- [x] System.Dynamic.Runtime
- [x] System.Globalization
- [x] System.Globalization.Calendars
- [x] System.Globalization.Extensions
- [x] System.IO
- [x] System.IO.FileSystem
- [x] System.IO.FileSystem.Primitives
- [x] System.IO.UnmanagedMemoryStream
- [x] System.Reflection
- [x] System.Resources.Reader
- [x] System.Resources.ResourceManager
- [x] System.Runtime.CompilerServices.Unsafe
- [x] System.Runtime.Extensions
- [x] System.Runtime.Handles
- [x] System.Runtime.InteropServices.RuntimeInformation
- [x] System.Security.SecureString
- [x] System.Text.Encoding
- [x] System.Threading.Tasks
- [x] System.Threading.Tasks.Extensions
- [x] System.Threading.Timer
- [x] System.ValueTuple

**Comment by ericstj** [comment]
Is there an easy version of this that just moves the projects into subdirectories in System.Runtime\tests but doesn't do any project refactoring?

**Comment by ViktorHofer** [comment]
What do you mean by project refactoring? I would hope that moving the test sources doesn't need any major msbuild work.

**Comment by ericstj** [comment]
I meant we could simply move the project files as is - giving a test folder with the same name as the test project - rather than trying to combine the sources with the existing System.Runtime.Tests.csproj.

**Comment by MichalStrehovsky** [comment]
WASM is running into some implementation limitations in System.Text.Json test because they're too huge (#87078). If most of these are going to and up in System.Runtime.Tests, we might run into same impl limitations (I'm not clear what they are - just pointing to an issue that has them, with people that might understand more).

**Comment by ViktorHofer** [comment]
Oh I see. I should have clarified in the top post. I think it would be best to move the tests as is, including their project files and not attempt to merge the test sources into the existing test projects.

Libraries' tests.proj disables test projects based on configurations (mobile vs NativeAOT vs wasm, ...). If one of these test projects is already disabled and we would now merge the test source code into an existing test project, those tests would need to be disabled inside the assembly.
