### ISSUE TITLE
[perf] System.Numerics.** performance regressions in Mono AOT x64 microbenchmarks from Preview 5 to Preview 7

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#89246]
## Description

The following performance regressions occurred between the Preview 4 snapshot (May 2nd, 2023) and Preview 7 snapshot (July 19th, 2023).

The configuration used for the benchmarks is Mono AOT with LLVM on x64 ubuntu 18.04.

Name | Baseline Value | Compare Value | % Difference
-|-|-|-
System.Numerics.Tests.Perf_VectorOf\<UInt64>.DotBenchmark | 2.94 | 3.22 | 9.52
System.Numerics.Tests.Perf_VectorOf\<UInt32>.GreaterThanAnyBenchmark | 5.65 | 6.12 | 8.32
System.Numerics.Tests.Perf_VectorOf\<UInt32>.ExclusiveOrOperatorBenchmark | 2.82 | 3.16 | 12.06
System.Numerics.Tests.Perf_VectorOf\<UInt32>.DotBenchmark | 4.8 | 5.09 | 6.04
System.Numerics.Tests.Perf_VectorOf\<UInt16>.ExclusiveOrOperatorBenchmark | 2.82 | 3.11 | 10.28
System.Numerics.Tests.Perf_VectorOf\<UInt16>.EqualsBenchmark | 0.92 | 1.31 | 42.39
System.Numerics.Tests.Perf_VectorOf\<Single>.MultiplyOperatorBenchmark | 2.83 | 3.07 | 8.48
System.Numerics.Tests.Perf_VectorOf\<Single>.LessThanBenchmark | 19.45 | 20.7 | 6.43
System.Numerics.Tests.Perf_VectorOf\<SByte>.SubtractionOperatorBenchmark | 2.79 | 3.04 | 8.96
System.Numerics.Tests.Perf_VectorOf\<SByte>.LessThanOrEqualAllBenchmark | 24.49 | 30.85 | 25.97
System.Numerics.Tests.Perf_VectorOf\<SByte>.GreaterThanOrEqualAllBenchmark | 2.11 | 2.5 | 18.48
System.Numerics.Tests.Perf_VectorOf\<Int32>.EqualsBenchmark | 0.81 | 0.95 | 17.28
System.Numerics.Tests.Perf_VectorOf\<Int16>.InequalityOperatorBenchmark | 0.44 | 0.51 | 15.91
System.Numerics.Tests.Perf_VectorOf\<Int16>.BitwiseOrBenchmark | 2.88 | 3.57 | 23.96
System.Numerics.Tests.Perf_VectorOf\<Double>.SubtractBenchmark | 2.92 | 3.17 | 8.56
System.Numerics.Tests.Perf_VectorOf\<Double>.EqualityOperatorBenchmark | 0.36 | 0.38 | 5.56
System.Numerics.Tests.Perf_VectorOf\<Byte>.MaxBenchmark | 41.53 | 43.74 | 5.32
System.Numerics.Tests.Perf_VectorOf\<Byte>.EqualsStaticBenchmark | 31.84 | 41.26 | 29.59
System.Numerics.Tests.Perf_Vector3.ReflectBenchmark | 39.45 | 43.89 | 11.25
System.Numerics.Tests.Perf_Vector3.NegateOperatorBenchmark | 9.78 | 11.96 | 22.29
System.Numerics.Tests.Perf_Vector3.MaxBenchmark | 13.26 | 14.97 | 12.9
System.Numerics.Tests.Perf_Vector3.DivideByVector3Benchmark | 10.94 | 13.04 | 19.2
System.Numerics.Tests.Perf_Vector3.DivideByScalarBenchmark | 16.46 | 18.01 | 9.42
System.Numerics.Tests.Perf_Vector3.AddFunctionBenchmark | 10.57 | 12.28 | 16.18
System.Numerics.Tests.Perf_Vector2.DistanceBenchmark | 10.59 | 12.71 | 20.02
System.Numerics.Tests.Perf_Matrix4x4.CreateLookAtBenchmark | 154.37 | 164.32 | 6.45
System.Numerics.Tests.Perf_Matrix3x2.CreateRotationWithCenterBenchmark | 61.26 | 64.36 | 5.06
System.Numerics.Tests.Perf_BigInteger.ToByteArray(numberString: 123) | 30.31 | 32.27 | 6.47
System.Numerics.Tests.Constructor.ConstructorBenchmark_Int32 | 22.42 | 23.59 | 5.22

**Comment by kotlarmilos** [comment]
@tannergooding We are trying to narrow down changes between May 2nd, 2023 and July 19th, 2023 that may have caused the regressions. If you are aware of any changes that might have potentially caused these regressions, please let us know.

/cc: @fanyang-mono @vargaz

**Comment by fanyang-mono** [comment]
I took a look the history of `System.Numerics.Tests.Perf_VectorOf<UInt64>.DotBenchmark`. And here is the result
![Screenshot 2023-07-20 at 11 23 18 AM](https://github.com/dotnet/runtime/assets/52458914/67ab40eb-51d0-4c52-998e-13440db3a672)
I don't believe that there is any real regression. On the contrary, there is an improvement on May 11th. However, Zoltan's change to intrinsify Vector128 on Amd64 only went in on June 13th (https://github.com/dotnet/runtime/pull/86546). If I remember correctly, May 11th is the date when Mono AOT runs were actually not running Mono but CoreCLR. Before moving forward with more "performance regression" investigation, I would suggest to confirm the data that being collected are correct and reliable.

**Comment by kotlarmilos** [comment]
Hey @fanyang-mono, thanks for checking out. The reported improvements are false positives since we are missing performance results during Preview 5 - Preview 7 timeframe. We fixed the Mono AOT performance jobs just before the Preview 7 snapshot and got the results back. The reported microbenchmarks have regressed more than 5% (on x64 arch), but in the most of the cases look like noise.

System.Numerics.Tests.Perf_VectorOf<UInt16>.EqualsBenchmark regressed 42.39%.
![newplot (3)](https://github.com/dotnet/runtime/assets/11523312/b02f48c8-0ae6-4c0c-96f9-d495dcde9a39)

System.Numerics.Tests.Perf_VectorOf<Byte>.EqualsStaticBenchmark regressed 29.59%.
![newplot (4)](https://github.com/dotnet/runtime/assets/11523312/e9736c39-977d-4ce4-a7ae-54878e4a601a)

System.Numerics.Tests.Perf_VectorOf<SByte>.LessThanOrEqualAllBenchmark  regressed 25.97%.
![newplot (5)](https://github.com/dotnet/runtime/assets/11523312/a7c78200-8d6a-4cb8-9730-593fb67777df)

I think it is safe to close this issue.

**Comment by fanyang-mono** [comment]
@kotlarmilos I am curious what made you conclude that System.Numerics.Tests.Perf_VectorOf.EqualsBenchmark regressed 42.39% and System.Numerics.Tests.Perf_VectorOf.LessThanOrEqualAllBenchmark regressed 25.97%? As you could see in the graph, the results fluctuate.

I inspected the result of `System.Numerics.Tests.Perf_VectorOf.EqualsBenchmark`. Before May 11 (the date it started to collect results of CoreCLR), the result range was between about 0.99 - 1.37. After July 17th, the result range was between about 0.92 - 1.3. I don't believe there was any regression being introduced. Same conclusion for `System.Numerics.Tests.Perf_VectorOf.LessThanOrEqualAllBenchmark`.

**Comment by fanyang-mono** [comment]
Since the results fluctuate so much, one suggestion for gathering report is to get the average of a couple data points (say 3 days of results).

**Comment by kotlarmilos** [comment]
They were initially marked as regressions since only two points were compared. As you suggested, moving average would help here. These are false positives, thus closing this issue.

@fanyang-mono thank you for the assistance!
