### ISSUE TITLE
[perf] System.Security.Cryptography.** performance regressions in Mono AOT x64 microbenchmarks from Preview 5 to Preview 7

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#89244]
## Description

The following performance regressions occurred between the Preview 4 snapshot (May 2nd, 2023) and Preview 7 snapshot (July 19th, 2023).

The configuration used for the benchmarks is Mono AOT with LLVM on x64 ubuntu 18.04.

Name | Baseline Value | Compare Value | % Difference
-|-|-|-
System.Security.Cryptography.Primitives.Tests.Performance.Perf_FixedTimeEquals.FixedTimeEquals_256Bit_VersusZero | 50.04 | 60.86 | 21.62
System.Security.Cryptography.Primitives.Tests.Performance.Perf_FixedTimeEquals.FixedTimeEquals_256Bit_AllBitsDifferent | 50.51 | 60.75 | 20.27

**Comment by kotlarmilos** [comment]
@LeVladIonescu Please try to narrow them down.

**Comment by LeVladIonescu** [comment]
![sec cr fixeq](https://github.com/dotnet/runtime/assets/114913836/73dc9dae-ff0b-4c97-96c6-bcbde2825092)
Not a real regression, chart showing noise for those.
