### ISSUE TITLE
[perf] System.Runtime.Intrinsics.** performance regressions in Mono AOT x64 microbenchmarks from Preview 5 to Preview 7

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#89245]
## Description

The following performance regressions occurred between the Preview 5 snapshot (May 2nd, 2023) and Preview 7 snapshot (July 19th, 2023).

The configuration used for the benchmarks is Mono AOT with LLVM on x64 ubuntu 18.04.

Name | Baseline Value | Compare Value | % Difference
-|-|-|-
System.Runtime.Intrinsics.Tests.Perf_Vector128Of\<UInt64>.DivideBenchmark | 18.89 | 20.22 | 7.04
System.Runtime.Intrinsics.Tests.Perf_Vector128Of\<SByte>.GetHashCodeBenchmark | 98.32 | 105.83 | 7.64

**Comment by kotlarmilos** [comment]
@vargaz @fanyang-mono There are a number of Vector128 improvements in https://github.com/dotnet/runtime/issues/89238 and I assume we can close this issue.

**Comment by fanyang-mono** [comment]
I don't understand your last comment, I searched in https://github.com/dotnet/runtime/issues/89238. And these two microbenchmarks also showed as regressions. How that could help close this issue?

**Comment by kotlarmilos** [comment]
I was thinking it is a tradeoff :) But if not, we should mitigate it.

**Comment by fanyang-mono** [comment]
There are two things here:
1. These Vector128 microbenchmarks are quite independent from each other. Even though most of them got improved, the regressed ones still worth looking into.
2. Like I mentioned in #89246, we should collect results with average of a couple data points. These looks like false positive to me. The performance of these two microbenchmarks didn't change.

**Comment by kotlarmilos** [comment]
Thanks for the info. Here are the last 10 runs with the baseline before the regression, and the targets after the recovery.

System.Runtime.Intrinsics.Tests.Perf_Vector128Of<UInt64>.DivideBenchmark
Run | Baseline | Target
-|-|-
1 | 18,78173253			| 18,79884798
2 |18,76230461			| 18,62760552
3 |18,76230461			| 18,69527468
4 |18,79260984			| 19,9226462
5 |19,01008983			| 18,65647022
6 |19,12448913			| 18,83510237
7 |18,85043033			| 20,09960835
8 |18,7581046			| 20,14199486
9 |18,73615193			| 20,15739381
10 |18,74319966			| 20,15808063
avg |18,83214171			| 19,40930246

System.Runtime.Intrinsics.Tests.Perf_Vector128Of<SByte>.GetHashCodeBenchmark
Run | Baseline | Target
-|-|-
1 | 97,80791568			| 105,8302407
2 | 97,87356477			| 103,1638385
3 | 98,30399123			| 104,7245511
4 | 98,89306389			| 104,3972979
5 | 98,09571083			| 96,46227839
6 | 97,78725048			| 104,6662993
7 | 97,79220034			| 103,1119935
8 | 102,149487			| 104,1949933
9 | 102,0973694			| 104,143184
10 | 102,3439054			| 104,327521
avg | 99,3144459			| 103,5022198

In both cases it looks like noise, thus closing this issues.
