### ISSUE TITLE
HttpClient changes the case of x-request-id when it is added to the DefaultRequestHeaders collection

### ISSUE THREAD

**Issue by conradakunga** [dotnet/runtime#89256]
### Description

If you add the header **x-request-id** to the `DefaultRequestHeaders `collection of a `HttpClient`, the case is changed from **x-request-id** to **X-Request-ID**

### Reproduction Steps

```c#
var client = new System.Net.Http.HttpClient();
client.DefaultRequestHeaders.Add("x-request-id", "foo");
Console.WriteLine(client.DefaultRequestHeaders);
```

### Expected behavior

It should print 

**x-request-id**

Exactly as passed

### Actual behavior

It prints

**X-Request-ID**

With the casing changed

### Regression?

It works correctly on .NET Framework, and returns precisely what was passed

### Known Workarounds

There are none as far as I can tell - it does not seem possible to access the underlying collection of headers and modify them directly.

### Configuration

Operating System: Windows 10 Pro 64-bit (10.0, Build 19045) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
Processor: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 CPUs), ~2.4GHz

.NET SDK:
 Version:   7.0.306
 Commit:    f500069cb7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.306\

I can reproduce this issue on .NET 8 beta, and .NET 6

### Other information

From reading the code, the issue appears to be that optimizations have been done to speed up the logic around adding headers, the rationale being that headers should be case-insensitive, as an industry standard.

The problem with this assumption is the code might be interfacing with legacy systems or systems that are controlled by third parties which are unwilling or unable to update their systems, which is precisely my predicament

**Comment by MihaZupan** [comment]
> the rationale being that headers should be case-insensitive, as an industry standard.

Exactly, the HTTP standards define header names as case-insensitive. While we don't always enforce every detail from such specifications, header name case-insensitivity seems to be something that almost all implementations got right.

HttpClient has optimizations internally to recognize some well-known names, and for those the casing may change.

> legacy systems or systems that are controlled by third parties which are unwilling or unable to update their systems, which is precisely my predicament

If you are able to use HTTP/2 or HTTP/3, header names will always be transmitted in lower-case.

With HTTP/1.1, the only way to override HttpClient's behavior of normalizing these names is to abuse the format of the protocol by smuggling an extra header inside another one
```c#
Headers.TryAddWithoutValidation("dummy-key", "dummyValue\nx-request-id: foo");
```

**Comment by conradakunga** [comment]
Thank you for your timely response.

I wrote a small program to test your brilliant solution:

```
var client = new HttpClient();
client.DefaultRequestHeaders.TryAddWithoutValidation("dummy", "dummy\nx-request-id: foo");
await client.GetAsync("http://localhost:5168");
```


I then wrote a simple minimal Web API app to parse and print the headers

```
app.MapGet("/", (HttpRequest req) =>
{
    var counter = 1;
    foreach (var header in req.Headers)
    {
        logger.LogInformation("{Counter} - {Key}:{Value}", counter++, header.Key, header.Value);
    }
});
```

The output was as follows:

> info: Program[0]
>       1 - Host:localhost:5168
> info: Program[0]
>       2 - dummy:dummy
> info: Program[0]
>       3 - x-request-id:foo

In other words, it appears to work perfectly.

I expect it to work in production and will confirm as much.

Of interest:
1. I have tested it with .NET 8 preview and .NET 7 and it works on both
2. It does **NOT** work at all for .NET 6 - the header is silently rejected

**Comment by MihaZupan** [comment]
> It does NOT work at all for .NET 6 - the header is silently rejected

Can you try adding it to the `HttpRequestMessage.Headers` instead of `DefaultRequestHeaders`?

(Request ID feels like an odd thing to add to `DefaultRequestHeaders`)

**Comment by conradakunga** [comment]
I updated the code to try your suggestion as follows:

```c#
var client = new HttpClient();
HttpRequestMessage msg = new(HttpMethod.Get, "http://localhost:5168");
msg.Headers.TryAddWithoutValidation("dummy", "dummy\nx-request-id: foo");
Console.WriteLine(msg.Headers);
```

My findings are the same:
1. Works for .NET 7 and .NET 8 preview - the headers are added
2. Does not add the headers for .NET 7

**Comment by MihaZupan** [comment]
I believe it should work on .NET 6 too as well as long as you don't access the headers collection with validation (the `Console.WriteLine(msg.Headers)` in your previous edit would end up silently removing that header).

**Comment by MihaZupan** [comment]
Triage: We're unlikely to change behavior here unless we get a lot of feedback that this is impacting real uses (I don't remember seeing other issues that would talk about the **name** case sensitivity). This is also no longer a concern once you start using HTTP/2 or HTTP/3 as the servers will always receive the lowercase form. A workaround for HTTP/1.X (albeit an ugly one) exists. Closing.

**Comment by conradakunga** [comment]
> I believe it should work on .NET 6 too as well as long as you don't access the headers collection with validation (the `Console.WriteLine(msg.Headers)` in your previous edit would end up silently removing that header -- it won't do so anymore on .NET 7+).

You're right, if I remove that line it correctly submits the headers on .NET 6.

A nasty surprise though - simply accessing the headers should not remove them 😮

Thanks for the assistance!
