### ISSUE TITLE
[perf] System.Globalization.** performance regressions in Mono AOT x64 microbenchmarks from Preview 5 to Preview 7

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#89250]
## Description

The following performance regressions occurred between the Preview 4 snapshot (May 2nd, 2023) and Preview 7 snapshot (July 19th, 2023).

The configuration used for the benchmarks is Mono AOT with LLVM on x64 ubuntu 18.04.

Name | Baseline Value | Compare Value | % Difference
-|-|-|-
System.Globalization.Tests.StringSearch.LastIndexOf_Word_NotFound(Options: (en-US, Ordinal, False)) | 232.74 | 522.51 | 124.5

**Comment by kotlarmilos** [comment]
@mkhamoyan @ilonatommy We are trying to narrow down changes between May 2nd, 2023 and July 19th, 2023 that may have caused the regressions. If you are aware of any changes that might have potentially caused these regressions, please let us know.

**Comment by mkhamoyan** [comment]
This can be related to HybridGlobalization changes but what is surprising for me that platform is x64 ubuntu.
HybridGlobalization mode is supported on iOS/tvOS/MacCatalyst/Browser platforms. Can you give more details related to calculations?

**Comment by kotlarmilos** [comment]
Sorry for the late reply. Your changes shouldn't affected the microbenchmark since the `HybridGlobalization` is not enabled yet. It looks like span regression https://github.com/dotnet/runtime/issues/89247#issuecomment-1644142104.

**Comment by steveisok** [comment]
Since this is about .net 8 previews, there's not much action we can take. Closing
