### ISSUE TITLE
Configuration binding source generator doesn't handle generics correctly

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#89273]
When trying to use the configuration binder source generator with an expression that uses a closed-generic type, I'm getting a warning saying it isn't supported.

However, since the expression is a closed-generic type, the type is able to be understood. In this case, the type is `OidcProviderOptions`.

We have this case in ASP.NET Auth. Specifically the Blazor WASM project templates use this exact pattern.

https://github.com/dotnet/aspnetcore/blob/24bbfb6d8398684091cc970bd342df185c8f9421/src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Program.cs#L15C1-L21

### Repro steps

`dotnet build` the following app.

```C#
using Microsoft.Extensions.Configuration;

var config = new ConfigurationBuilder().Build();

AddOidcAuthentication(options =>
{
    config.Bind("Local", options.ProviderOptions);  // warning HERE
});

static void AddOidcAuthentication(Action<RemoteAuthenticationOptions<OidcProviderOptions>> configure)
{
    configure(new());
}

public class RemoteAuthenticationOptions<TRemoteAuthenticationProviderOptions> where TRemoteAuthenticationProviderOptions : new()
{
    public TRemoteAuthenticationProviderOptions ProviderOptions { get; } = new TRemoteAuthenticationProviderOptions();
}

public class OidcProviderOptions
{
    public string? Authority { get; set; }
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0-preview.7.23370.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.0-preview.7.23370.3" />
  </ItemGroup>

</Project>
```

### Expected results

The above app should build successfully with no warnings or errors.

### Actual results

```
Program.cs(7,5): warning SYSLIB1104: Binding logic was not generated for a binder call. Unsupported input patterns include generic calls and passing boxed objects.
```

**Comment by layomia** [comment]
Thanks, I'll take a look. I think I fixed something similar in https://github.com/dotnet/runtime/commit/e4e0810cf1812d7ed46c457f37c864404170ec8a#diff-c941b7a8491ae8b0d73a97808f886062a388c3d59da08b281d56eb0c2afbc2c5R126.

**Comment by layomia** [comment]
> We have this case in ASP.NET Auth. Specifically the Blazor WASM project templates use this exact pattern.

@eerhardt per our offline discussion, there's a workaround for the templates (go back to disabling the generator for now) and we don't need a fix for this in Preview 7. We'll make a fix in RC.
