### ISSUE TITLE
Add optimization for scalar conversion of `float`/`double` to `ulong`.

### ISSUE THREAD

**Issue by anthonycanino** [dotnet/runtime#89279]
AVX512VL adds a number of new scalar conversion for unsigned 32-bit/64-bit integer types to float/double. This issue is meant to address some cases that were not implemented in a previous PR https://github.com/dotnet/runtime/pull/84384, notably

- `double` to `ulong`
- `float` to `ulong`

**Comment by BruceForstall** [comment]
@anthonycanino @khushal1996 @DeepakRajendrakumaran Is this issue resolved with the merge of https://github.com/dotnet/runtime/pull/97529?

**Comment by tannergooding** [comment]
This was completed in https://github.com/dotnet/runtime/pull/97529 and https://github.com/dotnet/runtime/pull/100993
