### ISSUE TITLE
Inconsistent DebuggerDisplay formatting

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#89283]
There isn't a consistent format for displaying name/values in `DebuggerDisplayAttribute`.

The most popular is equals, comma-separated, with spaces, e.g. [`IsCancellationRequested = {IsCancellationRequested}`](https://github.com/dotnet/runtime/blob/a4a8e8e712eff30c9223ebdeeeb4c80fb798e972/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationToken.cs#L29). This format is used most often and on the most commonly used types such as `CancellationToken`, `List<T>`, `Dictionary<TKey, TValue>`.

However, also used in equals, comma-separated, without spaces, e.g. [`Name={Name}`](https://github.com/dotnet/runtime/blob/a4a8e8e712eff30c9223ebdeeeb4c80fb798e972/src/libraries/System.Text.Json/gen/Model/TypeRef.cs#L12)
Colons are sometimes used, e.g. [`Count: {Segments.Length}`](https://github.com/dotnet/runtime/blob/a4a8e8e712eff30c9223ebdeeeb4c80fb798e972/src/libraries/System.Memory/src/System/Buffers/ReadOnlySequenceDebugView.cs#L42)

I think we should make DebuggerDisplay attributes consistent and I think the format should be the most popular one: equals, comma-separated, with spaces. e.g.

* `[DebuggerDisplay("IsCancellationRequested = {IsCancellationRequested}")]`
* `[DebuggerDisplay("First = {First}, Second = {Second}")]`

Tasks for this issue:

* Audit and update `[DebuggerDisplay]` text directly, e.g. `[DebuggerDisplay("Count: {Count}")]`
* Audit and update `[DebuggerDisplay]` debug property/method bound to the attribute, e.g. for `[DebuggerDisplay("{DebuggerToString()}")]` the changes will happen in the `DebuggerToString()` method.
* **Don't** update public `ToString()` without prior discussion. It has a runtime impact so any changes need to be thought through.

Note: Some debugger display attributes don't display name/value data. This issue doesn't cover them.

**Comment by tannergooding** [comment]
C# records follow the general premise outlined above. They do the [following](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record):
```
<record type name> { <property name> = <value>, <property name> = <value>, ...}
```

The one downside to this is that `,` can sometimes get confused with other separators or number display in some cultures.

**Comment by whosenbocus** [comment]
I can look into this issue.

Can this be assigned to me please?

**Comment by JamesNK** [comment]
Done

**Comment by danmoseley** [comment]
@whosenbocus I suggest to start with one relatively small PR for this rather than a huge one. That way any discussion can happen before you do lots of work.

**Comment by whosenbocus** [comment]
Draft PR Created #89370 

This only consists changes for Task 1 - Space and equal for name/value.

Still need to look into "changes will happen in the DebuggerToString() method", but want to get feedback on these changes first.

**Comment by JamesNK** [comment]
If it’s ready for review then don’t mark it as draft. Additional changes to debug methods can be in another PR.

**Comment by whosenbocus** [comment]
Noted.

Applied your suggestion to the PR and marked it for review.

Let me know your thought and if we can complete it. I will then proceed with the other Task.

**Comment by whosenbocus** [comment]
#89370

**Comment by whosenbocus** [comment]
@JamesNK, PR is now merged.

Anything outstanding for this issue or can we close it?

**Comment by JamesNK** [comment]
Close it. Thanks for improving this!
