### ISSUE TITLE
createdump is not being signed 

### ISSUE THREAD

**Issue by tussock** [dotnet/runtime#89285]
### Description

I have upgraded a Xam.Mac app to .Net for Mac. In the process, I also upgraded to .Net 7 and C# 11. I’m trying to upload it to the app store. This worked under Xam.Mac, but does not work now.

The problem is that there is a new application automatically added to the Application bundle - createdump - which does not get signed properly.

I see that this has been raised before (e.g. https://github.com/dotnet/runtime/issues/83613), but those are all closed without actually saying how to work around the issue.

How to reproduce:

build the app with release build

1. Select “Archive For Publishing”.
2. The select “Sign and Distribute”.
3. Select “App Store”, then the signing identity, provisioning profile and installer signing identity.
4. This seems to work, and I can save the build.
5. I then switch to the Transporter app and attempt to upload (by dragging and dropping the package). I get the following error:

`Invalid Code Signing. The executable MYAPP.pkg/Payload/MYAPP.app/Contents/MonoBundle/createdump' must be signed with the certificate that is contained in the provisioning profile.
`
I understand from the following links:

> https://github.com/xamarin/xamarin-macios/issues/14155
> https://github.com/xamarin/xamarin-macios/issues/13417

that createdump was added recently as a troubleshooting utility, and needs to be signed manually. But I cannot find any documentation on how one is supposed to sign this app that gets added to my package.

The second link suggests a workaround by attempting to code sign “createdump” using configuration in the csproj file, but that does not work. I get an error:

`The "Codesign" task was not given a value for the required parameter "StampFile", nor was there a "CodesignStampFile" metadata on the resource /Users/paul/Dev/MYAPP/MYAPP.Mac/bin/Release/net7.0-macos13.0/MYAPP.Mac.app/Contents/MonoBundle/createdump.`

THIS error has apparently been fixed back in 2022: https://github.com/xamarin/xamarin-macios/issues/14126, but that doesn’t work (or isn’t relevant). There is no other documentation on what StampFile should be.

VSMac Version: 17.6 (build 1575)
MacOS Version: 13.4.1 (latest)

### Reproduction Steps

1. Select “Archive For Publishing”.
2. The select “Sign and Distribute”.
3. Select “App Store”, then the signing identity, provisioning profile and installer signing identity.
4. This seems to work, and I can save the build.
5. I then switch to the Transporter app and attempt to upload (by dragging and dropping the package). I get the following error:

`Invalid Code Signing. The executable MYAPP.pkg/Payload/MYAPP.app/Contents/MonoBundle/createdump' must be signed with the certificate that is contained in the provisioning profile.
`

### Expected behavior

Either:

- VSMac will automatically sign createdump (since VS is adding it to my app), OR
- Instructions will be provided as to HOW to sign createdump manually so that the app can be delivered to the app store.

Right now, my app cannot be uploaded to the app store.

### Actual behavior

createdump is not being signed.

### Known Workarounds

None known.

**Comment by tussock** [comment]
Forgot to mention:

```
<TargetFramework>net7.0-macos</TargetFramework>
<SupportedOSPlatformVersion>10.14</SupportedOSPlatformVersion>
<RuntimeIdentifiers>osx-x64</RuntimeIdentifiers>
```

And here is the workaround I mention in the bug report that does not work:
```
    <!-- Workaround for https://github.com/xamarin/xamarin-macios/issues/13417 -->
  <PropertyGroup>
    <CodesignDependsOn>CodeSignCreateDump;$(CodesignDependsOn)</CodesignDependsOn>
  </PropertyGroup>
  <Target Name="CodeSignCreateDump" Condition="'$(_CodeSigningKey)' != ''">
    <Codesign Condition="'$(IsMacEnabled)' == 'true'" SessionId="$(BuildSessionId)" ToolExe="$(CodesignExe)" ToolPath="$(CodesignPath)" CodesignAllocate="$(_CodesignAllocate)" DisableTimestamp="$(_CodesignDisableTimestamp)" Keychain="$(CodesignKeychain)" Resources="$(AppBundleDir)\Contents\MonoBundle\createdump" SigningKey="$(_CodeSigningKey)" ExtraArgs="$(CodesignExtraArgs)" UseHardenedRuntime="$(UseHardenedRuntime)" StampFile="" UseSecureTimestamp="$(UseHardenedRuntime)" />
  </Target>
    <!-- Workaround for https://github.com/xamarin/xamarin-macios/issues/13417 -->
```

**Comment by marek-safar** [comment]
I think this issue should move to https://github.com/xamarin/xamarin-macios

@dalexsoto @rolfbjarne

**Comment by tussock** [comment]
> I think this issue should move to https://github.com/xamarin/xamarin-macios

I think you are right, my apologies for the error.
Can I move it? Or do I need to create a new one?

**Comment by steveisok** [comment]
Closing in favor of https://github.com/xamarin/xamarin-macios/issues/18578
