### ISSUE TITLE
[AOT]  System.NotSupportedException: The type 'System.Collections.Generic.List`1[System.String]' is not supported

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#89288]
### Description

Serializing a list of string works fine but trying to deserialize the same json back to a list of string fails with  `System.NotSupportedException: The type 'System.Collections.Generic.List 1[System.String]' is not supported`

### Reproduction Steps

    internal class Program
    {
        static List<string> Strings = new();

        [RequiresUnreferencedCode("Calls System.Text.Json.JsonSerializer.Deserialize<TValue>(ReadOnlySpan<Byte>, JsonSerializerOptions)")]
        [RequiresDynamicCode("Calls System.Text.Json.JsonSerializer.Deserialize<TValue>(ReadOnlySpan<Byte>, JsonSerializerOptions)")]
        static void Main(string[] args)
        {
            Strings.Add("aaa");
            Strings.Add("bbbb");

            string json = JsonSerializer.Serialize(Strings);

            List<string>? NewStrings = JsonSerializer.Deserialize<List<string>>(json);

            Console.WriteLine("Done");
            Console.ReadKey();
        }
    }

### Expected behavior

No exception

### Actual behavior

```
Unhandled Exception: System.NotSupportedException: The type 'System.Collections.Generic.List`1[System.String]' is not supported. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
 ---> System.NotSupportedException: The type 'System.Collections.Generic.List`1[System.String]' is not supported.
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_SerializationNotSupported(Type) + 0x3a
   at System.Text.Json.Serialization.Converters.ListOfTConverter`2.CreateCollection(Utf8JsonReader&, ReadStack&, JsonSerializerOptions) + 0x61
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack&, TCollection&) + 0xa4
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack&, T&, Boolean&) + 0x224
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader&, JsonSerializerOptions, ReadStack&) + 0x167
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(ReadStack&, Utf8JsonReader&, NotSupportedException) + 0x33a
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader&, JsonSerializerOptions, ReadStack&) + 0x36b
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1, JsonTypeInfo`1, Nullable`1) + 0xfe
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1, JsonTypeInfo`1) + 0x108
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String, JsonSerializerOptions) + 0x4c
```

### Known Workarounds

Publishing NOT using AOT works fine

### Configuration

```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
```

```
.NET SDK:
 Version:   8.0.100-preview.6.23330.14
 Commit:    ba97796b8f

 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.6.23330.14\

Host:
  Version:      8.0.0-preview.6.23329.7
  Architecture: x64
  Commit:       5340be2ccc
```

**Comment by eiriktsarpalis** [comment]
Using reflection-based serialization in AOT can result in unexpected failures like the one you're experiencing, hence the warnings being issues be the relevant APIs. When publishing to Native AOT the recommendation is to always use the [source generated serializer APIs](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation) instead.

**Comment by Symbai** [comment]
I am serializing a list of strings, I don't use a custom class. How can I use the "source generated serializer" for that? The examples in your link are only for custom classes.

**Comment by eiriktsarpalis** [comment]
You just need to replace the type declarations in the `JsonSerializerContext` with the types that you need to serialize. In your case:
```C#
using System.Text.Json;
using System.Text.Json.Serialization;

internal partial class Program
{
    static List<string> Strings = new();

    static void Main(string[] args)
    {
        Strings.Add("aaa");
        Strings.Add("bbbb");

        string json = JsonSerializer.Serialize(Strings);

        List<string>? NewStrings = JsonSerializer.Deserialize(json, MyContext.Default.ListString);

        Console.WriteLine("Done");
        Console.ReadKey();
    }

    [JsonSerializable(typeof(List<string>))]
    internal partial class MyContext : JsonSerializerContext
    { }
}
```
