### ISSUE TITLE
Possible issue with BinaryReader.ReadString()

### ISSUE THREAD

**Issue by CharlesPublic** [dotnet/runtime#893]
Hi, i'm creating a web service and i'm using BinaryReader / BinaryWriter to serialize some data.
(System.IO.BinaryReader)

I've noticed that the 
- BinaryReader.ReadString()

 function allocates a StringBuilder capacity with the value from the start of the string bytes:  

- StringBuilderCache.Acquire(Read7BitEncodedInt());

This might be a problem for my service because some malicious data with a value of 
int.MaxValue as the first 4 bytes of the string would allocate a 2 GB Buffer when trying to deserialize the data.

I'm not sure if this is an issue you want to address, just want to mention it.
It's also a little clunky to fix myself as there's no build in function to Read a 7 Bit encoded int and the BinaryReader doesn't allow peeking much.

Cheers

**Comment by CharlesPublic** [comment]
Here is my Test:

    public class TestBugBinaryReader
    {
        public static void Test()
        {
            var ms = new MemoryStream();

            // generate a fake length
            var fakeLength = To7BitEncodedInt(int.MaxValue / 10 * 2);

            var writer = new BinaryWriter(ms);
            writer.Write(fakeLength);
            // add 200 random bytes
            writer.Write(AntEncrypt.GenerateRandomBytes(200));

            ms.Position = 0;
            var reader = new BinaryReader(ms);

            // our data is just 205 bytes long
            // 18 mb allocated
            var memBefore = Process.GetCurrentProcess().PrivateMemorySize64;
            try
            {
                reader.ReadString();
            }
            catch (Exception ex)
            {
                // 800 mb allocated
                var memAfter = Process.GetCurrentProcess().PrivateMemorySize64;
            }
        }


        static byte[] To7BitEncodedInt(int value)
        {
            uint num;
            var bytes = new List<byte>();

            for (num = (uint)value; num >= 128; num >>= 7)
            {
                bytes.Add((byte)(num | 0x80));
            }
            bytes.Add((byte)num);

            return bytes.ToArray();
        }

        static byte[] GenerateRandomBytes(int n)
        {
            var randomBytes = new byte[n];
            using (var rngCsp = new RNGCryptoServiceProvider())
                rngCsp.GetBytes(randomBytes);

            return randomBytes;
        }
    }

**Comment by Gnbrkm41** [comment]
I'm not sure if there's much to be done here; it's doing what it's supposed to do, even if it's with possibly crafted data to cause problem. There's no way to tell because who knows if the string is very long for legitimate reason?

Perhaps you could introduce a length limit of some sort in your service and validate the string length before you read? Take this to read a 7-bit encoded int: https://github.com/dotnet/runtime/blob/57df20206691c6123b6e2d392b661cb3541fc24a/src/libraries/System.Private.CoreLib/src/System/IO/BinaryReader.cs#L587-L609

and use `BinaryReader.BaseStream.Position` or `BinaryReader.BaseStream.Seek` to seek back then call `ReadString`.

**Comment by CharlesPublic** [comment]
@Gnbrkm41 thanks i might just do that.

i think this issue might still be a problem if you look at where ReadString() is also used in the .NET Framework...
- ASP.NET: read and initialize Security.Claims
- HttpStaticObjectsCollection deserialize
- SessionState
- Reading Authentications tickets, this is for cookies i think

**Comment by Gnbrkm41** [comment]
> BinaryFormatter

It's already known to be dangerous anyway: https://github.com/dotnet/corefx/issues/38760 🙂 Can't tell about the rest though.

**Comment by JeremyKuhne** [comment]
Triage: It would be worth considering adding an overload that allows you to cap the size of the string you want to read. The current API won't overflow the string, but an `int.MaxValue` string is quite large. :) @CharlesPublic is making such a proposal something you're interested in?

**Comment by GrabYourPitchforks** [comment]
Resolved in https://github.com/dotnet/runtime/pull/36348.
