### ISSUE TITLE
ComInterfaceGenerator Docs should be very clear about how return values / HResult on the managed method translates to the native signature

### ISSUE THREAD

**Issue by jtschuster** [dotnet/runtime#89314]
It can be very confusing that a return value in managed becomes an out parameter in native and a new `int` return value is added. Our documentation and announcements should be very clear about how these translate, and when to use `[PreserveSig]`.

**Comment by jtschuster** [comment]
> @jtschuster Jackson Schuster FTE I assume [dotnet/docs#36833](https://github.com/dotnet/docs/pull/36833) will handle this issue?

Yes, the preserve-sig.md page should take care of this.

**Comment by MatejKafka** [comment]
I have a related question:

In #35855, the first example (`result GetValue();`) illustrates that if the generated `out` pointer parameter for the return value is `NULL`, the method correctly runs, the return value is ignored and `S_OK` is returned. Is this documented somewhere? If not, is this behavior defined, or should I not rely on it and instead use `[PreserveSig]` and marshal manually?

**Comment by jtschuster** [comment]
@MatejKafka #35855 is related to built-in COM and that behavior is still the same (inconsistent behavior depending on how you define the method). The COM generator should throw a null reference exception in the marshalling code and return `E_POINTER` for all cases.

> Is this documented somewhere? If not, is this behavior defined, or should I not rely on it and instead use [PreserveSig] and marshal manually?
I don't think it's documented anywhere besides the issue linked, and it isn't defined behavior. If you're using built-in COM and want to handle a null parameter, I would recommend [PreserveSig] and convert `out` parameters to pointers and marshal manually. It's worth noting, though, that passing null (or any invalid pointer) for a parameter defined in COM IDL as `[out]` is invalid use and isn't strictly required to be handled by the called method.

**Comment by MatejKafka** [comment]
@jtschuster My question is, is the inconsistent behavior for the built-in COM defined, or is it just an implementation detail that may change in future version of .NET?

**Comment by jtschuster** [comment]
@MatejKafka It's an implementation detail that may change.
