### ISSUE TITLE
Use Roslyn interceptors feature in config binder generator

### ISSUE THREAD

**Issue by layomia** [dotnet/runtime#89322]
ref: @captainsafia's work on the request delegate source generator - https://github.com/dotnet/aspnetcore/pull/48817.

cc @tarekgh @eerhardt @ericstj.

**Comment by layomia** [comment]
Can take this opportunity to fix https://github.com/dotnet/runtime/issues/86363.

**Comment by layomia** [comment]
@tarekgh @ericstj @eiriktsarpalis looks like the interceptors feature [requires `<Features>$(Features);InterceptorsPreview</Features>`](https://github.com/dotnet/aspnetcore/pull/48817/files#r1256032359) in consuming projects. While the feature is in preview, it seems we should update the SDK to set it if `EnableConfigurationBindingGenerator` is set. Otherwise users would need to set two properties to use the generator.

The Web SDK already sets the feature property when binding & RDG generates are enabled, so the concern is about regular SDK scenarios.

**Comment by tarekgh** [comment]
@layomia does the interceptor feature will be released the same way? I mean users have to opt-in to get it. Or this is temporary for preview and will change when it get released?

**Comment by ericstj** [comment]
We can do the same thing as RDG here.  Just add us to this condition:
https://github.com/dotnet/sdk/blob/b3b5a2800d4de997572068332bf222e2e8f808d5/src/WebSdk/ProjectSystem/Targets/Microsoft.NET.Sdk.Web.ProjectSystem.targets#L62-L65

We could do the same in our nuget package targets:
https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Configuration.Binder/src/buildTransitive/Microsoft.Extensions.Configuration.Binder.targets

Might be good to have a safeguard in the generator just in case someone manages to invoke it without setting that property.  I suspect RDG needs the same as well (eg Web class library that get's referenced by a normal app or class library).
