### ISSUE TITLE
Empty .pfx certificates causes apps to crash after a while

### ISSUE THREAD

**Issue by alek5ey** [dotnet/runtime#89345]
### Description

Faced periodic application crashes with OutOfMemoryException, "Too many open files" and freezes after some time of work. The application in a loop makes many requests to different websites.
Using the `lsof` utility, I found a huge number of open certificate files from `~/.dotnet/corefx/cryptography/x509stores/ca/*.pfx` and their number gradually increased until the application crashed.
As it turned out, the certificate files were broken (with zero size), where they came from - I don't know.

### Reproduction Steps

1. Create an empty pfx file (the more there are, the faster the application crashes)
`cat /dev/null > ~/.dotnet/corefx/cryptography/x509stores/ca/1C58A3A8518E8759BF075B76B750D4F2DF264FCD.1.pfx`

2. Code (important that HttpClient is recreated)
```
Console.WriteLine(Environment.ProcessId);
while (true)
{
    try
    {
        using var httpClient = new HttpClient();
        var response = await httpClient.GetAsync("https://www.microsoft.com/");
        Console.WriteLine(response.StatusCode);
    }
    catch (Exception e)
    {
        Console.WriteLine(e);
    }
    finally
    {
        Thread.Sleep(5_000);
    }
}
```

4. Approximately every 30 seconds, a hung pfx file will begin to appear in the output of lsof
`lsof -p PID`

### Expected behavior

Incorrect files do not hang open and close immediately

### Actual behavior

Listing open files before application crashes
![lsof output](https://github.com/dotnet/runtime/assets/37906869/41c89cc7-65ec-4a60-b2bb-8978846d0839)

### Known Workarounds

Delete all empty pfx files manually

### Configuration

.NET 7.0.109
Ubuntu 22.04
x64

### Other information

The file descriptor may not properly close empty files.
The frequency of opening new pfx files may be determined by:
https://github.com/dotnet/runtime/blob/2d1e28432105391f5e0d5a4573f7858fa9d798a7/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/OpenSslCachedDirectoryStoreProvider.cs#L37-L81

**Comment by vcsjones** [comment]
Hm. This looks like something is not quite working correctly with storing AIA fetched certificates. There are two problems here:

1. These files should not be empty, so something is failing to write them.
2. When there is a failure, these should be properly cleaned up, file handles closed, etc.

I'll take a look.

**Comment by vcsjones** [comment]
I can reproduce it - if there is a "bad" PFX in the ca store, it keeps a handle to it open.

<img width="1336" alt="image" src="https://github.com/dotnet/runtime/assets/361677/4f7e45dc-4aa8-41a6-afdb-658ea6ca70a2">

This reproduces in .NET 6, so it isn't a recent regression.

@alek5ey the contents of this directory indicate that something is not quite working correctly here.. there should rarely if ever be .1, .2, .3 etc of certificates. Are all of them empty?

If you completely remove `~/.dotnet/corefx/cryptography/x509stores/ca` does your system continue to create .1 and .2 PFX files?

**Comment by alek5ey** [comment]
@vcsjones, I don't know where these empty files came from, but there were a lot of them and the application crashed about every hour
![Certs list](https://github.com/dotnet/runtime/assets/37906869/31c33733-e2bc-4bb5-8f2e-6cbe737db462)

After discovering the problem, I deleted the "bad" files and the application stabilized and no more empty files were created

**Comment by vcsjones** [comment]
I can see in a trace that we open the directory, then open the file, close the directory, but never close the file.

```
openat(AT_FDCWD, "/home/vcsjones/.dotnet/corefx/cryptography/x509stores/ca", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 60
openat(AT_FDCWD, "/home/vcsjones/.dotnet/corefx/cryptography/x509stores/ca/1C58A3A8518E8759BF075B76B750D4F2DF264FCD.1.pfx", O_RDONLY) = 66
read(66, "", 4096)                      = 0
close(60)                               = 0
```

I suspect the problem is here:

https://github.com/dotnet/runtime/blob/ae4d6987824188f6d051b77a89cd5c297cd70b79/src/native/libs/System.Security.Cryptography.Native/pal_x509.c#L515

We only `fclose` the file if `d2i_PKCS12_fp` returns non-null. But for an empty file, `d2i_PKCS12_fp` returns NULL. So the file handle is never closed.

**Comment by vcsjones** [comment]
The above does not explain _how_ you got these empty files, but it does explain why the presence of these empty files causes file handles to remain open indefinitely.

**Comment by wfurt** [comment]
is this specific to `X509Store` or would this also be problem for reading "normal" pfx @vcsjones ?

**Comment by vcsjones** [comment]
@wfurt It's specific to X509Store. As @alek5ey points out though, since we refresh the store with a timer, every time the timer elapses, we create another file handle.
