### ISSUE TITLE
Building iOS projects with AOT & LLVM enabled consumes all CPU cores and makes system unusable

### ISSUE THREAD

**Issue by frenzibyte** [dotnet/runtime#89356]
### Description

When enabling AOT compilation & LLVM compiler on an iOS project, building it spawns a lot of `mono-aot-cross`/`opt`/`llt` processes that consumes too much of my CPU to the point where my entire machine becomes unusable until it finishes building. This has been annoying me a lot during my experience with .NET iOS.

My suspicion is that this has something to do with the fact that the AOT cross compiler runs on Rosetta right now, but that's about all I can gather.

### Reproduction Steps

1. Check out https://github.com/ppy/osu-framework (picked because AOT'ing the iOS projects there spends enough time to notice the effects of the compiler on the system).
2. Build `SampleGame.iOS` (e.g. `dotnet build SampleGame.iOS -c Release -r ios-arm64 -v n`)

### Expected behavior

Project builds without making the system unusable.

### Actual behavior

Project builds while each instance of `mono-aot-cross`/`opt`/`llc` has too much CPU usage (see https://share.cleanshot.com/vsqbW1jX).

### Configuration

```
[I] ╭─salman at Salmans-MBP in /Users/salman/Projects/osu-framework (master ⚑477)
╰─λ dotnet --info                                                                             1 (0.111s)
.NET SDK (reflecting any global.json):
 Version:   6.0.406
 Commit:    2988897946

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.3
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.406/

Host:
  Version:      8.0.0-preview.6.23329.7
  Architecture: arm64
  Commit:       5340be2ccc

.NET SDKs installed:
  6.0.406 [/usr/local/share/dotnet/sdk]
  7.0.201 [/usr/local/share/dotnet/sdk]
  8.0.100-preview.5.23303.2 [/usr/local/share/dotnet/sdk]
  8.0.100-preview.6.23330.14 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.5.23302.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.6.23329.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.5.23280.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.6.23329.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  /Users/salman/Projects/osu-framework/global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

Not sure whether it's specific to the configuration, maybe specific to M1/M2 machines.

**Comment by huoyaoyuan** [comment]
Building CLR also utilizes all CPU cores. MSBuild in Visual Studio provides a feature to lower the priority of compiler processes, but I didn't find such option for ninja.

**Comment by frenzibyte** [comment]
Worthy of mention, building much bigger projects such as `osu.iOS` in https://github.com/ppy/osu leads to extreme memory usage as well:

![image](https://github.com/dotnet/runtime/assets/22781491/d2b076bb-bb96-4bd7-8b04-6f998f5de76e)

**Comment by MichalPetryka** [comment]
I'd say that the behaviour here is kind of expected, LLVM is a resource heavy compiler and in general, it's the OSes responsibility to prevent software from making it unstable.

**Comment by steveisok** [comment]
@akoeplinger as @MichalPetryka said, I think this is expected behavior. Want to confirm with you first before closing.

**Comment by SamMonoRT** [comment]
From comments above, this seems like expected behavior. Closing the issue.
