### ISSUE TITLE
How should I debug the corehost .sln？

### ISSUE THREAD

**Issue by tangyanzhi** [dotnet/runtime#89354]
### Description

I want to debug corehost.sln, but I don't know how to debug it, such as parameter settings, command line, etc., is there a document to refer to?

When I debug the corehost .sln, some functions are inlined, some variables are optimized, how can I see these functions and variables?

ALSO #ifndef DEBUG doesn't work anymore, isn't it enabled by default? How do you make it work?

When Hostfxr .dll run to coreclr .dll, a lot of things are not visible

### Reproduction Steps

I want to debug corehost.sln, but I don't know how to debug it, such as parameter settings, command line, etc., is there a document to refer to?

### Expected behavior

I want to debug corehost.sln,

### Actual behavior

but I don't know how to debug it, such as parameter settings, command line, etc., is there a document to refer to?

### Configuration

```
C:\Users\Administrator>dotnet --info
.NET SDK:
 Version:   8.0.100-preview.5.23303.2
 Commit:    3fe444af72

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.5.23303.2\
```

**Comment by vitek-karas** [comment]
The tests for `corehost` and `hostfxr` and `hostpolicy` (and other related functionality) are described in https://github.com/dotnet/runtime/blob/main/docs/workflow/testing/host/testing.md.

If you want to debug an app with your custom build of hosting components you can follow this: https://github.com/dotnet/runtime/blob/main/docs/workflow/testing/host/using-apphost.md
(I would start with the "local .NET root" at the bottom of that page for a simple debugging, unless you need specific behaviors around apphost or single-file and such).

**Comment by tangyanzhi** [comment]
> The tests for and and (and other related functionality) are described in https://github.com/dotnet/runtime/blob/main/docs/workflow/testing/host/testing.md.`corehost``hostfxr``hostpolicy`
> 
> If you want to debug an app with your custom build of hosting components you can follow this: https://github.com/dotnet/runtime/blob/main/docs/workflow/testing/host/using-apphost.md (I would start with the "local .NET root" at the bottom of that page for a simple debugging, unless you need specific behaviors around apphost or single-file and such).

Yes, it can debug the corehost .sln.
But the data inside the #ifdef _DEBUG doesn't show it. When debugging coreclr .sln, it can be displayed, such as MethodDesc:

For example:MethodDesc

coreclr.sln:
![image](https://github.com/dotnet/runtime/assets/29683262/0e8b680b-5d98-4b6e-90bf-f2b41c274437)

corehost.sln
![image](https://github.com/dotnet/runtime/assets/29683262/23a9ed4d-9cec-44b7-92ff-4d2d94c9fa18)



How can I debug the corehost .sln, also display the data in #ifdef _DEBUG


I set up the #define _DEBUG, but it doesn't

**Comment by vitek-karas** [comment]
If you want to debug both the host and the runtime in debug builds then please change the build to:
```
.\build.cmd -s clr+libs -c Debug
.\build.cmd -s host+packs.product -runtimeConfiguration Debug -librariesConfiguration Debug
```

Similarly for the other commands - specify `-runtimeConfiguration Debug`. Using the `testhost` created by the libraries tests is probably the simplest way to then run basically any console app with the locally built host/runtime (debug). Running a debugger with that should give you full debug support across the host and runtime (and libraries).

**Comment by tangyanzhi** [comment]
> If you want to debug both the host and the runtime in debug builds then please change the build to:
> 
> ```
> .\build.cmd -s clr+libs -c Debug
> .\build.cmd -s host+packs.product -runtimeConfiguration Debug -librariesConfiguration Debug
> ```
> 
> Similarly for the other commands - specify `-runtimeConfiguration Debug`. Using the `testhost` created by the libraries tests is probably the simplest way to then run basically any console app with the locally built host/runtime (debug). Running a debugger with that should give you full debug support across the host and runtime (and libraries).


I already have debug versions of host and the runtime.

However, debugging host cannot display the member variables in the #ifndef _DEBUG.

My approach was to open the corehost .sln and set the INSTALL project bit startup entry. In the INSTALL right-click -> Configuration Properties -> Debug-" command enter the exe path generated by the console, and then F5 debug.

Is there anything wrong with this, please? Why can't it be displayed

**Comment by vitek-karas** [comment]
Code under `#ifndef _DEBUG` should only be used on Release builds, so if you're using Debug builds it won't be there. Could you please point me to the member you're looking for?

You can debug the executable pretty much any way, if everything is built locally the debugger should find the right symbols for everything. The only important part is to set the debugger type to Native, if you somehow manage to make it Managed it will obviously not work for the native code in the host.
