### ISSUE TITLE
PeriodicTimer.WaitForNextTickAsync lack <exception> comment

### ISSUE THREAD

**Issue by kzhui125** [dotnet/runtime#89366]
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Threading/PeriodicTimer.cs#L134

The method will throw System.OperationCanceledException.

But I don't see `<exception>` tag in comment.

**Comment by teo-tsirpanis** [comment]
Isn't it implied that methods accepting a `CancellationToken` throw `OperationCanceledException` if they get canceled? [`Stream.ReadAsync` is also not documented to throw OCE.](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.readasync)

**Comment by stephentoub** [comment]
In general, methods have documented what they synchronously throw, not what exceptions might be stored into the Tasks they return.

**Comment by kzhui125** [comment]
Thanks.
