### ISSUE TITLE
Native AOT - interop - statically linking / calling .lib while producing single EXE

### ISSUE THREAD

**Issue by JOULTICOA** [dotnet/runtime#89361]
I have followed the information here:  https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/interop
to edit project XML

I need help with example c# code or documentation for calling Unmanaged method from c# when STATICALLY linking to a .a / .lib with Native AOT.

Native AOT opens the totally brand new possibility of Statically Linking to .a / .lib and calling the unmanaged methods while still having a single, self-contained native EXE as the final output.

In my case, I want to statically link and call some OpenSSL methods from my Unmanaged c# code.

In my case, OpenSSL was cross-compiled on Linux using MinGW-w64 and GCC targeting Windows.  mingw/gcc produced .a file, which per stackoverflow answers are the same as .lib files for the pure C language (C++ is different story)  see here:  https://stackoverflow.com/questions/25637110/how-to-generate-lib-files-with-mingw-toolchain

What would the c# look like for this?  I know I'm NOT doing System.Runtime.InteropServices [DllImport("libcrypto.dll")]

so what am I doing?

If anyone has some examples, or some blog post on how to do STATICALLY LINKED .a / .lib using Native AOT interop, that produces single self contained EXE, that would be amazing

**Comment by JOULTICOA** [comment]
@MichalStrehovsky please have mercy if I put this wrong place thank you

**Comment by agocke** [comment]
I think you want this: https://github.com/dotnet/runtime/blob/fa9f94d01bb0a4103058f7ceae27fe42613f2cf1/src/coreclr/nativeaot/docs/compiling.md?plain=1#L101

**Comment by jkotas** [comment]
> What would the c# look like for this? I know I'm NOT doing System.Runtime.InteropServices [DllImport("libcrypto.dll")]

It can be `[DllImport("libcrypto.dll")]`, or more modern `[LibraryImport("libcrypto.dll")]` that enables marshalling code produced by source generators).

Also, you should have `<DirectPInvoke Include="libcrypto.dll" />` in your .csproj to enable the static linking against libcrypto.dll.

The only thing that matters for static linking is that the name used by `DllImport` matches the name in the `DirectPInvoke` directive. The actual name does not matter. For example, `[DllImport("mylibcrypto")]` and `<DirectPInvoke Include="mylibcrypto" />` would work too.

**Comment by jkotas** [comment]
> I think you want this: https://github.com/dotnet/runtime/blob/fa9f94d01bb0a4103058f7ceae27fe42613f2cf1/src/coreclr/nativeaot/docs/compiling.md?plain=1#L101

These instructions are for statically linking openssl used by the runtime libraries on Linux. I believe @JOULTICOA wants to statically link openssl on Windows and use it from the app code.

**Comment by agocke** [comment]
Ah, I missed the windows part. Aren't the symbols for the mingw libc different from ucrt? Will linking the mingw openssl against ucrt work?

**Comment by JOULTICOA** [comment]
Thank you so much for looking, yes, final target Windows x64, with single self contain Native EXE output.  We want use OpenSSL specifically for a variety of reasons, and already using many c# libraries successfully with Native AOT compile down to single EXE, so it makes sense stay c# for main app

> I think you want this:
> 
> https://github.com/dotnet/runtime/blob/fa9f94d01bb0a4103058f7ceae27fe42613f2cf1/src/coreclr/nativeaot/docs/compiling.md?plain=1#L101

Interesting note about Linux / Unix only, I guess I do not 100% have knowledge to understand how OpenSSL is different from any other .a / .lib  pure C application.  Obviously every application is YMMV situation to some extent

Is what I am doing possible with mingw LIB and Native AOT and OpenSSL down to single native EXE?

**Comment by jkotas** [comment]
>  Aren't the symbols for the mingw libc different from ucrt? Will linking the mingw openssl against ucrt work?

It depends on how the cross-compilation was configured exactly. I think it can work, but there is a lot of room for problems.

> Is what I am doing possible with mingw LIB and Native AOT and OpenSSL down to single native EXE?

It should be possible to statically link openssl into your app on Windows. However, I would not use cross-compilation using mingw to avoid the kind problems that @agocke pointed out. You will likely save you a lot of troubles by compiling openssl on Windows, using Visual Studio C++ compiler.

**Comment by JOULTICOA** [comment]
> > Aren't the symbols for the mingw libc different from ucrt? Will linking the mingw openssl against ucrt work?
> 
> It depends on how the cross-compilation was configured exactly. I think it can work, but there is a lot of room for problems.
> 
> > Is what I am doing possible with mingw LIB and Native AOT and OpenSSL down to single native EXE?
> 
> It should be possible to statically link openssl into your app on Windows. However, I would not use cross-compilation using mingw to avoid the kind problems that @agocke pointed out. You will likely save yourself from a lot of troubles by compiling openssl on Windows, using Visual Studio C++ compiler.

Ok thank you so much, 2 more last question

1.) Is this a common enough usage scenario that it be some kind of feature request, or should I wait a while until maybe it get added to StaticOpenSslLinking feature in a few years?  Maybe I totally misunderstand what this feature is

2.) What does the c# look like for calling a native method from c# when statically linking with Native AOT without a Wrapper?  I've only ever used wrapper and importing DLL before

**Comment by jkotas** [comment]
>  Is this a common enough usage scenario that it be some kind of feature request, or should I wait a while until maybe it get added to StaticOpenSslLinking feature in a few years?

`StaticOpenSslLinking` is only for internal use of OpenSSL by .NET runtime and only on Linux. .NET runtime does not use OpenSSL on Windows and we are not planning to change that. If you want to use OpenSSL on Windows, you are on your own.

> What does the c# look like for calling a native method from c# when statically linking with Native AOT without a Wrapper?

The C# for dynamic linking vs. static linking looks exactly same. For example:
``
[DllImport("libcrypto")]
internal static extern IntPtr EVP_CIPHER_CTX_new();
```
The static linking is enabled by `DirectPInvoke` directive in .csproj file. The C# does not change when you enable static linking.

**Comment by JOULTICOA** [comment]
> > Is this a common enough usage scenario that it be some kind of feature request, or should I wait a while until maybe it get added to StaticOpenSslLinking feature in a few years?
> 
> `StaticOpenSslLinking` is only for internal use of OpenSSL by .NET runtime and only on Linux. .NET runtime does not use OpenSSL on Windows and we are not planning to change that. If you want to use OpenSSL on Windows, you are on your own.
> 
> > What does the c# look like for calling a native method from c# when statically linking with Native AOT without a Wrapper?
> 
> The C# for dynamic linking vs. static linking looks exactly same. For example:
> 
> ```
> [DllImport("libcrypto")]
> internal static extern IntPtr EVP_CIPHER_CTX_new();
> ```
> 
> The static linking is enabled by `DirectPInvoke` directive in .csproj file. The C# does not change when you enable static linking.

Wow OK had no idea it was the same.  Thanks for all the help!
