### ISSUE TITLE
X500DistinguishedName string representation and dotted-decimal attributes

### ISSUE THREAD

**Issue by markm77** [dotnet/runtime#89386]
Hi there,

This may be a API enhancement request or simply a request for advice.

I am using UK Open Banking which requires the DN string for an MTLS transport certificate to be supplied when registering with a bank (see "tls_client_auth_subject_dn" in https://openbankinguk.github.io/dcr-docs-pub/v3.3/dynamic-client-registration.html).

I would like to get this from X500DistinguishedName using e.g. the Name/Decode/Format members but at the moment there are a few issues with this (using .NET 7).

Currently I get the following using X500DistinguishedName.Name from the transport certificate (latest .NET 7):
CN=X1, OID.2.5.4.97=X2, O=X3, C=GB

What I actually want to get is either of (depending on bank convention which differs between banks):
CN=X1,organizationIdentifier=X2,O=X3,C=GB
CN=X1,2.5.4.97=#X4,O=X3,C=GB
where #X4 is a hex value corresponding to dotted-decimal AttributeValue X2 (as specified by https://datatracker.ietf.org/doc/html/rfc4514#section-2.4).

These are the two formats currently accepted by UK banks from my testing (I maintain a client library for UK Open Banking: https://github.com/finlabsuk/open-banking-connector).

These formats have two minor differences (removal of spaces and (re-)naming for dotted-decimal attribute) and one major difference (return hex value for dotted-decimal attribute) from the current X500DistinguishedName.Name string.

I'm just wondering if you could consider adding e.g. flags to support generation of these formats. And in the meantime could you possibly advise the best way to perform BER encoding to get #X4 from X2 (as per https://datatracker.ietf.org/doc/html/rfc4514#section-2.4)?

Many thanks for any help.

BR,
Mark

**Comment by vcsjones** [comment]
There are a number of changes coming in this area that may improve the compatibility that you are looking for, depending on the platform you are using. #88197 and #88037.

Are you using Windows or non-Windows for the behavior you are observing?

If you are using Windows, then I don't think we would expect to see many changes here any time soon. .NET asks CryptoAPI "Please give me the string representation for this X.500 name". .NET's goal is to match Windows behavior on non-Windows. If Windows has the incorrect behavior for you, then I don't think any upcoming changes work improve that.

> And in the meantime could you possibly advise the best way to perform BER encoding to get #X4 from X2 (as per https://datatracker.ietf.org/doc/html/rfc4514#section-2.4)?

The best but fairly complicated way to do this is to read the ASN.1 of the distinguished name yourself using `System.Formats.Asn1` and build the distinguished name yourself. Or, perhaps a library is able to format these as you need (though no such recommendation comes to mind).

**Comment by markm77** [comment]
Hi @vcsjones ,

Thanks very much for the reply and help. I've been using Windows for testing this. In my software currently DN strings are hand-crafted and supplied via configuration so was looking to use the X500DistinguishedName class to auto-generate them in code from transport certificates.

Given your comments, I still think this is a good idea but some extra steps will be required.

Since only one attribute requires adjustment ("OID.2.5.4.97"), perhaps I can use X500DistinguishedName.EnumerateRelativeDistinguishedNames and your new X500DistinguishedNameBuilder to break down and re-construct the DN with adjusted attribute. And then strip out the unwanted delimiting spaces from the DN string as a final step.

As for BER encoding to get the hex AttributeValue when required, thanks for your suggestion. I guess I can read the ASN.1 as you suggest or perhaps perform the BER encoding myself. I also just found https://learn.microsoft.com/en-us/dotnet/api/system.directoryservices.protocols.berconverter.encode?view=dotnet-plat-ext-7.0 which might do the job. I'll do some experiments with different methods.

Please feel free to add any further comments but I'll close this for now.

BR,
Mark

**Comment by markm77** [comment]
Just to note, I did test this on Linux (WSL Ubuntu 22.04) and there X500DistinguishedName.Name gives:
CN=X1, organizationIdentifier=X2, O=X3, C=GB

This (apart from spaces) matches one of the desired formats and uses "organizationIdentifier" instead of "OID.2.5.4.97" (as used on Windows) which seems more correct as matches output of `openssl x509 -in ./cert.pem -noout -subject` (OpenSSL 3.0.2) which is:
subject=C = GB, O = X3, organizationIdentifier = X2, CN = X1

So I prefer the output on Linux but seems this will in future be changed to align with Windows.

**Comment by markm77** [comment]
After reviewing this and the code I wrote, it seems a quick win that would get rid of ugly OS (Windows/Linux) switches in my code would be for the following issue to be addressed: #89434. Hope that is possible!

BR,
Mark
