### ISSUE TITLE
[mono] The bitcast test fails with exit code 104 on apple mobile platforms

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#89385]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=349474
Build error leg or test failing: JIT_Intrinsics.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/89296

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Application has finished with exit code 104 but 100 was expected",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```
The BitCast test fails with exit code 104 on the apple mobile platforms. I will try to get more details locally.

/cc: @EgorBo

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=349474
**Error message validated:** `Application has finished with exit code 104 but 100 was expected`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 7/24/2023 1:23:25 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[353900](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353900)|dotnet/runtime|[JIT_Intrinsics.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353900&view=ms.vss-test-web.build-test-results-tab&runId=7440104&resultId=100032)|dotnet/runtime#89555|
|[349967](https://dev.azure.com/dnceng-public/public/_build/results?buildId=349967)|dotnet/runtime|[JIT_Intrinsics.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=349967&view=ms.vss-test-web.build-test-results-tab&runId=7347912&resultId=100045)|dotnet/runtime#88167|
|[349510](https://dev.azure.com/dnceng-public/public/_build/results?buildId=349510)|dotnet/runtime|[JIT_Intrinsics.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=349510&view=ms.vss-test-web.build-test-results-tab&runId=7335044&resultId=100045)||
|[349474](https://dev.azure.com/dnceng-public/public/_build/results?buildId=349474)|dotnet/runtime|[JIT_Intrinsics.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=349474&view=ms.vss-test-web.build-test-results-tab&runId=7333800&resultId=100045)|dotnet/runtime#89296|
|[349328](https://dev.azure.com/dnceng-public/public/_build/results?buildId=349328)|dotnet/runtime|[JIT_Intrinsics.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=349328&view=ms.vss-test-web.build-test-results-tab&runId=7327794&resultId=100045)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|5|5|

**Comment by EgorBo** [comment]
cc @MichalPetryka

Perhaps, it's already fixed with https://github.com/dotnet/runtime/pull/89364 (if that was the issue)

**Comment by MichalPetryka** [comment]
Looks like the 4 tests for [implicit floating point casting](https://github.com/dotnet/runtime/blob/main/src/tests/JIT/Intrinsics/BitCast.il#L116) fail on Mono and instead of casting just reinterpret the bits.
Such implicit conversion of `float32 <-> float64` is legal in IL as per the ECMA so this looks like a Mono runtime bug.

**Comment by kotlarmilos** [comment]
I didn't manage to reproduce it locally with `Console.WriteLine(Unsafe.BitCast<float, int>(1f))`.
```
IL_006b: ldc.r4 1
IL_0070: call !!1 [System.Runtime]System.Runtime.CompilerServices.Unsafe::BitCast<float32, int32>(!!0)
```

However, with implicit conversion it fails.
```
IL_00bc:  ldc.r8 1.
IL_00c5:  call !!1 [System.Runtime]System.Runtime.CompilerServices.Unsafe::BitCast<float32,int32>(!!0)
```
