### ISSUE TITLE
[mono][ios] MarshalingPInvokeScanner fails with PE image does not have metadata

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#89429]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=350013
Build error leg or test failing: baseservices_compilerservices.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/89392

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "System.InvalidOperationException: PE image does not have metadata.",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

The apple mobile runtime tests are failing with `System.InvalidOperationException: PE image does not have metadata`. The tests use JustInterp AOT mode and have the following configuration.
```
<PropertyGroup Condition="'$(UseRuntimeComponents)' == 'true'">
  <RuntimeComponents>diagnostics_tracing;marshal-ilgen</RuntimeComponents>
  <DiagnosticPorts>127.0.0.1:9000,nosuspend,listen</DiagnosticPorts>
</PropertyGroup>
```
/cc: @jandupej 

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=350013
**Error message validated:** `System.InvalidOperationException: PE image does not have metadata.`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 7/25/2023 10:29:00 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[355013](https://dev.azure.com/dnceng-public/public/_build/results?buildId=355013)|dotnet/runtime|[System.Diagnostics.FileVersionInfo.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=355013&view=ms.vss-test-web.build-test-results-tab&runId=7465516&resultId=159955)|dotnet/runtime#89301|
|[355014](https://dev.azure.com/dnceng-public/public/_build/results?buildId=355014)|dotnet/runtime|[tracing_eventpipe.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=355014&view=ms.vss-test-web.build-test-results-tab&runId=7466334&resultId=100020)|dotnet/runtime#89301|
|[354241](https://dev.azure.com/dnceng-public/public/_build/results?buildId=354241)|dotnet/runtime|[System.Diagnostics.FileVersionInfo.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=354241&view=ms.vss-test-web.build-test-results-tab&runId=7455700&resultId=159955)|dotnet/runtime#89223|
|[354674](https://dev.azure.com/dnceng-public/public/_build/results?buildId=354674)|dotnet/runtime|[Loader_classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=354674&view=ms.vss-test-web.build-test-results-tab&runId=7458124&resultId=100012)|dotnet/runtime#89521|
|[354414](https://dev.azure.com/dnceng-public/public/_build/results?buildId=354414)|dotnet/runtime|[baseservices_TieredCompilation.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=354414&view=ms.vss-test-web.build-test-results-tab&runId=7451184&resultId=100014)||
|[353999](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353999)|dotnet/runtime|[tracing_eventpipe.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353999&view=ms.vss-test-web.build-test-results-tab&runId=7441562&resultId=100020)|dotnet/runtime#89569|
|[353907](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353907)|dotnet/runtime|[tracing_eventpipe.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353907&view=ms.vss-test-web.build-test-results-tab&runId=7439956&resultId=100023)|dotnet/runtime#88167|
|[353569](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353569)|dotnet/runtime|[tracing_eventpipe.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353569&view=ms.vss-test-web.build-test-results-tab&runId=7440588&resultId=100020)|dotnet/runtime#89548|
|[353633](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353633)|dotnet/runtime|[tracing_eventpipe.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353633&view=ms.vss-test-web.build-test-results-tab&runId=7433834&resultId=100020)||
|[353576](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353576)|dotnet/runtime|[tracing_eventpipe.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353576&view=ms.vss-test-web.build-test-results-tab&runId=7431712&resultId=100023)|dotnet/runtime#89508|
|[353281](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353281)|dotnet/runtime|[tracing_eventpipe.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353281&view=ms.vss-test-web.build-test-results-tab&runId=7425576&resultId=100020)|dotnet/runtime#89223|
|[353096](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353096)|dotnet/runtime|[tracing_eventpipe.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353096&view=ms.vss-test-web.build-test-results-tab&runId=7420848&resultId=100023)||
|[353048](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353048)|dotnet/runtime|[tracing_eventpipe.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353048&view=ms.vss-test-web.build-test-results-tab&runId=7419178&resultId=100023)|dotnet/runtime#89467|
|[352690](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352690)|dotnet/runtime|[tracing_eventpipe.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352690&view=ms.vss-test-web.build-test-results-tab&runId=7419208&resultId=100023)|dotnet/runtime#89431|
|[352607](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352607)|dotnet/runtime|[tracing_eventpipe.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352607&view=ms.vss-test-web.build-test-results-tab&runId=7409506&resultId=100020)|dotnet/runtime#89499|
|[352584](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352584)|dotnet/runtime|[tracing_eventpipe.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352584&view=ms.vss-test-web.build-test-results-tab&runId=7408888&resultId=100020)|dotnet/runtime#89301|
|[352503](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352503)|dotnet/runtime|[System.Diagnostics.FileVersionInfo.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352503&view=ms.vss-test-web.build-test-results-tab&runId=7405516&resultId=159936)|dotnet/runtime#89428|
|[352553](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352553)|dotnet/runtime|[reflection_StaticInterfaceMembers.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352553&view=ms.vss-test-web.build-test-results-tab&runId=7408024&resultId=100017)|dotnet/runtime#89498|
|[352326](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352326)|dotnet/runtime|[CoreMangLib_system.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352326&view=ms.vss-test-web.build-test-results-tab&runId=7400778&resultId=100001)||
|[352310](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352310)|dotnet/runtime|[tracing_eventpipe.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352310&view=ms.vss-test-web.build-test-results-tab&runId=7400382&resultId=100020)|dotnet/runtime#89301|
|[351866](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351866)|dotnet/runtime|[tracing_eventlistener.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351866&view=ms.vss-test-web.build-test-results-tab&runId=7389626&resultId=100019)||
|[351758](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351758)|dotnet/runtime|[Exceptions_UnwindFpBleedTest.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351758&view=ms.vss-test-web.build-test-results-tab&runId=7387564&resultId=100002)|dotnet/runtime#89223|
|[350013](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350013)|dotnet/runtime|[tracing_eventpipe.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350013&view=ms.vss-test-web.build-test-results-tab&runId=7372294&resultId=100023)|dotnet/runtime#89392|
|[351016](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351016)|dotnet/runtime|[tracing_eventpipe.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351016&view=ms.vss-test-web.build-test-results-tab&runId=7369694&resultId=100023)|dotnet/runtime#89296|
|[351065](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351065)|dotnet/runtime|[reflection_regression.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351065&view=ms.vss-test-web.build-test-results-tab&runId=7370488&resultId=100018)||
|[350917](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350917)|dotnet/runtime|[Exceptions_UnwindFpBleedTest.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350917&view=ms.vss-test-web.build-test-results-tab&runId=7367658&resultId=100002)|dotnet/runtime#89308|
|[350495](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350495)|dotnet/runtime|[baseservices_TieredCompilation.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350495&view=ms.vss-test-web.build-test-results-tab&runId=7358674&resultId=100011)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|8|27|27|

**Comment by jandupej** [comment]
@kotlarmilos The fix to the rest of MarshallingPInvokeScanner errors is now merged. Can you pls verify that this solves the issue?

**Comment by kotlarmilos** [comment]
The issue has been fixed, thank you!
