### ISSUE TITLE
RyuJIT: fgDebugCheckBBlist (or similar) should check loop annotations

### ISSUE THREAD

**Issue by JosephTremoulet** [dotnet/runtime#8944]
Follow up to @briansull's https://github.com/dotnet/coreclr/pull/13957#issuecomment-329322217 : when we walk the block list to check invariants, we could/should make sure that:
 - each block's `bbNatLoopNum` matches the index of the first loop in the table whose top/bottom blocks' numbers bracket it
 - walking the lpParent links in the loop table from that innermost loop, all ancestors also have top/bottom blocks whose numbers bracket the current block's number

This would have given us an assertion failure during compilation of dotnet/runtime#8916 rather than silent bad codegen.

category:correctness
theme:flowgraph
skill-level:intermediate
cost:small

**Comment by AndyAyersMS** [comment]
We are doing pretty careful checking these days:
* https://github.com/dotnet/runtime/pull/48060
* https://github.com/dotnet/runtime/pull/64126
* https://github.com/dotnet/runtime/pull/71184

I think we can consider this done.
