### ISSUE TITLE
[Mono] Windows static library runtime build exports MONO_API functions.

### ISSUE THREAD

**Issue by lateralusX** [dotnet/runtime#89444]
### Description

This PR changed our cmake logic, https://github.com/dotnet/runtime/pull/82182, doing object libraries instead of adding source files when build shared and static versions of runtime. Since there will only be one set of object files used in shared and static version of Mono runtime on Windows, it will create issues with MONO_API exported functions. In the past, we build different set of object files to include in static and shared version of runtime library, meaning we only set `__declspec(dllexport)` when building the source files included in shared library, and not setting it when building the source file included in static library. If that is not done that way, all code that will link with the static version of the library will end up exporting all the functions decorated with MONO_API, including binaries like mono-sgen.exe.

### Reproduction Steps

Do Mono runtime build and run dumpbin.exe /Exports mono-sgen.exe.

### Expected behavior

dumpbin.exe /Exports mono-sgen.exe shouldn't list any exported symbols.

### Actual behavior

dumpbin.exe /Exports mono-sgen.exe list all symbols decorated with MONO_API.

### Regression?

Yes, in previous releases we handled the exported functions correctly on Windows for shared and static libraries.

**Comment by lambdageek** [comment]
I think we should build two sets of object files

**Comment by lateralusX** [comment]
> I think we should build two sets of object files

Agree, the double set will only be a Windows thing, so other platforms should not be affected.
