### ISSUE TITLE
[Test Failure] Long Running Test: System.Net.Sockets.Tests.SendReceive_Sync.SendRecv_Stream_TCP_LargeMultiBufferSends

### ISSUE THREAD

**Issue by liveans** [dotnet/runtime#89440]
[Helix log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-bbff7190076a40c1a3/System.Net.Sockets.Tests/1/console.daf17e4a.log?helixlogtype=result)
Let's see if we need to add any timeout.

## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=349185
Build error leg or test failing: System.Net.Sockets.Tests.SendReceive_Sync.SendRecv_Stream_TCP_LargeMultiBufferSends
Pull request:

## Error Blob

```json
{
  "ErrorMessage": "[Long Running Test] 'System.Net.Sockets.Tests.SendReceive_Sync.SendRecv_Stream_TCP_LargeMultiBufferSends'",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=349185
**Error message validated:** `[Long Running Test] 'System.Net.Sockets.Tests.SendReceive_Sync.SendRecv_Stream_TCP_LargeMultiBufferSends'`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 7/25/2023 3:14:08 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by karelz** [comment]
Looks pretty rare, moving to Future.

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by liveans** [comment]
No hit in last 6 months, we can re-open again if this appears in CI
