### ISSUE TITLE
[libs][iOS] TimeZoneInfo StandardName/DisplayName display abbreviations instead of full name

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#89466]
### Description

As mentioned in https://github.com/dotnet/runtime/issues/85126#issuecomment-1648183786, `StandardName` and `DisplayName` return abbreviations instead of the full name that other platforms return. This is likely due to iOS using its own version of ICU, and the data there not being complete enough to return the full name. As a result, it is likely that the backup values https://github.com/dotnet/runtime/blob/764f77412ef4ec1a7e5dc521608247487a66cd7e/src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.Unix.cs#L244 and https://github.com/dotnet/runtime/blob/764f77412ef4ec1a7e5dc521608247487a66cd7e/src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.Unix.cs#L258 are being used instead.

### Reproduction Steps

Run the iOS sample `src/mono/sample/iOS` with 
```
Console.WriteLine("StandardName: {TimeZoneInfo.Local.StandardName}");
Console.WriteLine("DaylightName: {TimeZoneInfo.Local.DaylightName}");
```

### Expected behavior

Should see full names and not abbreviations, and since I'm based on East coast of North America,
Eastern Standard Time
Easter Daylight Time

### Actual behavior

I'm based on East coast of North America, so
EST
EDT

**Comment by tarekgh** [comment]
@steveisok could you please triage as it is iOS?

**Comment by steveisok** [comment]
I think this is something we can tweak in the ICU filter for iOS.

**Comment by mdh1418** [comment]
After Meri's work in https://github.com/dotnet/runtime/pull/91458, the DisplayName/StandardName/DaylightName TimeZoneInfo properties are no longer abbreviations when HybridGlobalization is enabled. When HybridGlobalization is not enabled, default values (abbreviated form) will be used similar to Invariant globalization mode.
