### ISSUE TITLE
[API Proposal]: Add CloseAsync to Stream

### ISSUE THREAD

**Issue by dersia** [dotnet/runtime#89479]
### Background and motivation

While working on #88244 I found a few possible Bugs in `StreamWriter`'s async disposable behavior.

Please also see my comments on https://github.com/dotnet/runtime/issues/88244#issuecomment-1647543667

the Major issue that I see, is that StreamWriter is calling `Close()` on the underlying Stream, which if not overriden will call `Dispose(true)` on the Stream. In any case, DisposeAsync is not called on the underlying Stream and therefor everything happens sync.

This would also mean, that the implementation of `DisposeAsync()` on Stream needs to be updated, because it just calls `Dispose()` which calls `Close()` which again calls `Dispose(true)`. 

### API Proposal

I propose to add the following API:

```cs
namespace System.IO;

public abstract class Stream: MarshalByRefObject, IDisposable, IAsyncDisposable 
{
    public virtual Task CloseAsync(CancellationToken cancellationToken);
}
```

### API Usage

This would than be used like this in StreamWriter

```cs
namespace System.IO;

public class StreamWriter : TextWriter
{
    //omitted code of IAsyncDisposable calling CloseStreamFromDisposeAsync(bool disposing)
    private async ValueTask CloseStreamFromDispose(bool disposing)
    {
        try
        {
            if (_closable && !_disposed)
            {
                if (disposing)
                {
                    await _stream.CloseAsync();
                }
            }
        }
        finally
        {
            _disposed = true;
            _charLen = 0;
            await base.DisposeAsync(disposing);
        }
    }
}
```

### Alternative Designs

Alternatively it stays as is and calls to sync `Dispose()`

### Risks

Based on implementation of Streams this might have an impact, but I don't see a bis impact since in the abstract type `CloseAsync()` can jsut call `Close()`

**Comment by teo-tsirpanis** [comment]
The `Close` method was introduced in .NET Framework 1.0 and superseded by the `Dispose` method in .NET Framework 2.0. You should just call `DisposeAsync` instead of adding a `CloseAsync` method.

**Comment by stephentoub** [comment]
Yes, `Close` was a mistake we can't undo.  It should have been removed prior to .NET Framework 1.0 shipping, but that ship sailed over two decades again.  We're not going to double-down on the mistake, though.

Thanks.
