### ISSUE TITLE
HasNativeCodeReJitAware

### ISSUE THREAD

**Issue by mikelle-rogers** [dotnet/runtime#89475]
Check uses of EEDebugInterface::GetFunctionAddress and see if we should return nondefault code addresses.
HasNativeCodeReJitAware is only checking if the active or default versions have native code. It's possible that a non-active, non-default version has code even if both the active and default versions do not. 
Delete HasNativeCodeReJitAware and move its functionality to GetFunctionAddress.

**Comment by tommcdon** [comment]
Closing via #90049
