### ISSUE TITLE
[browser] single file JavaScript and custom loader

### ISSUE THREAD

**Issue by Elringus** [dotnet/runtime#89510]
### Description

I'm attempting to run `browser-wasm` with a minimal custom config under .NET 8:

```js
import { dotnet } from './dotnet.js'

const config = {
    "mainAssemblyName": "Test.dll",
    "assemblyRootFolder": "managed",
    "assets": [
	    {
	      "behavior": "dotnetwasm",
	      "name": "dotnet.native.wasm",
	    },
	    {
	      "behavior": "js-module-native",
	      "name": "dotnet.native.js",
	    },
	    {
	      "behavior": "js-module-dotnet",
	      "name": "dotnet.js",
	    },
	    {
	      "behavior": "js-module-runtime",
	      "name": "dotnet.runtime.js",
	    },
	    {
	      "behavior": "assembly",
	      "name": "System.Console.wasm",
	    },
	    {
	      "behavior": "assembly",
	      "name": "System.Linq.wasm",
	    },
	    {
	      "behavior": "assembly",
	      "name": "System.Private.CoreLib.wasm",
	    },
	    {
	      "behavior": "assembly",
	      "name": "Test.wasm",
	    }
    ]
};
const runtime = await dotnet.withConfig(config).create();
```
But getting nullref here: https://github.com/dotnet/runtime/blob/v8.0.0-preview.6.23329.7/src/mono/wasm/runtime/loader/assets.ts#L145C28

It worked in .NET 7 fine before.

### Reproduction Steps

Publish `browser-wasm` and try running it with a custom config under "AppBundle" dir.

### Expected behavior

No errors.

### Actual behavior

Error in mono_download_assets: TypeError: pendingDownloadInternal is null

### Regression?

Yes, it worked in .NET 7.

### Known Workarounds

None.

### Configuration

.NET v8.0.0-preview.6.23329.7
Windows 10
Local http server under AppBundle dir with `serve` under powershell.

**Comment by radical** [comment]
cc @maraf @pavelsavara

**Comment by pavelsavara** [comment]
I guess we could add WBT with this as a test app

**Comment by Elringus** [comment]
@pavelsavara Hey, Any idea when to expect this to land in .NET SDK distribution? I've tried the recent preview 7, but looks like it's not there yet.

**Comment by Elringus** [comment]
@pavelsavara Thanks, I've checked but it still doesn't work for my use case.

Here is the setup I'm trying to use:

```js
const config = {
    mainAssemblyName: "Test.dll",
    assets: [
        {
            name: "dotnet.native.js",
            buffer: await fetchBin("dotnet.native.js"),
            behavior: "js-module-native"
        },
        {
            name: "dotnet.runtime.js",
            buffer: await fetchBin("dotnet.runtime.js"),
            behavior: "js-module-runtime"
        },
        {
            name: "dotnet.native.wasm",
            buffer: await fetchBin("dotnet.native.wasm"),
            behavior: "dotnetwasm"
        },
        {
            name: "System.Private.CoreLib.wasm",
            buffer: await fetchBin("System.Private.CoreLib.wasm"),
            behavior: "assembly"
        },
        {
            name: "System.Runtime.InteropServices.JavaScript.wasm",
            buffer: await fetchBin("System.Runtime.InteropServices.JavaScript.wasm"),
            behavior: "assembly"
        },
        {
            name: "System.Console.wasm",
            buffer: await fetchBin("System.Console.wasm"),
            behavior: "assembly"
        },
        {
            name: "Test.wasm",
            buffer: await fetchBin("Test.wasm"),
            behavior: "assembly"
        }
    ]
 };

const runtime = await dotnet.withConfig(config).create();
```

I can't use `resources` as there seem to be no option to provide buffer to them. But even with the above setup I get following errors:

```
Loading failed for the module with source “http://localhost:3000/dotnet.runtime.js”. localhost:3000:5:42
MONO_WASM: error loading dynamically imported module: http://localhost:3000/dotnet.runtime.js
Error in mono_download_assets: TypeError: error loading dynamically imported module: http://localhost:3000/dotnet.runtime.js assets.ts:254:22
Loading failed for the module with source “http://localhost:3000/dotnet.native.js”. localhost:3000:5:42
```

— looks like even though I provide buffers for `dotnet.native.js` and `dotnet.runtime.js` they are ignored and `dotnet.js` attempts to fetch them on its own.

Here is the repro: https://github.com/Elringus/JSInteropTest

**Comment by pavelsavara** [comment]
JavaScript modules are imported with dynamic `await import("./someURL.js")`
do you have any suggestion how to import them from buffer ?

Also what happens about CSP/COOP/CORS in such case ? Because such module would not have origin right.

And finally, why this is useful ?

**Comment by Elringus** [comment]
It's required in cases when we need to bundle the whole stuff into single js file. In .NET 6 there was a single dotnet.js, which allowed me to build web extensions for VS Code. I have no idea if it's possible to import from buffer like that; is it really required to split the JS like this, though? Requiring dynamic import of external JS files like that disables usage scenarios where that's not allowed by the env.

**Comment by pavelsavara** [comment]
Yeah, we have https://github.com/dotnet/runtime/issues/86162 for that.

**Comment by pavelsavara** [comment]
We could have `asset.exports`  (similar to `asset.buffer`) in which you could give us the whatever our JS modules export. How you instantiate those JS modules would be your problem. Would that help ?

**Comment by Elringus** [comment]
> We could have `asset.exports` (similar to `asset.buffer`) in which you could give us the whatever our JS modules export. How you instantiate those JS modules would be your problem. Would that help ?

If you could also make  `dotnet.js`, `runtime.js` and `native.js` something like following (runtime.js is currently very close to this):
```js
var moduleInterface = { .... }
export default moduleInterface;
```

— that would work. I'll then remove `export default moduleInterface` line and pass `moduleInterface` to `asset.exports` via a build post-process step, eg:

```js
// injected from dotnet.native.js with export line stripped
var nativeModule = { ... };
// injected from dotnet.runtime.js with export line stripped
var runtimeModule = { ... };
// injected from dotnet.js with export line stripped
var dotnet = { ... };

const assets = [
        {
            name: "dotnet.native.js",
            exporsts: nativeModule,
            behavior: "js-module-native"
        },
        {
            name: "dotnet.runtime.js",
            exports: runtimeModule,
            behavior: "js-module-runtime"
        },
        {
            name: "dotnet.native.wasm",
            buffer: await fetchBin("dotnet.native.wasm"),
            behavior: "dotnetwasm"
        }
]

const runtime = await dotnet.withConfig({ assets }).create();
```

**Comment by pavelsavara** [comment]
I'm not sure we will make it for Net8, but I'm thinking about how this could be done.

**Comment by Elringus** [comment]
@pavelsavara Just adding `asset.exports` would help greatly, actually. It looks like it's possible to run node scripts via msbuild (https://github.com/dotnet/runtime/blob/main/src/mono/wasm/wasm.proj#L575), so maybe instead of direct patching I would be able to use rollup to make the JS modules write their exports to a variable.

If it's something you can consider public PR for, I'd love to try contributing.

**Comment by pavelsavara** [comment]
The Net8 deadline for new features is on Monday and I'm ooo next week. I will sketch quick PR now.

**Comment by pavelsavara** [comment]
> If it's something you can consider public PR for, I'd love to try contributing.

@Elringus you could choose something to contribute for Net9, [here are our issues](https://github.com/dotnet/runtime/issues?q=is%3Aopen+is%3Aissue+sort%3Aupdated-desc+label%3Aarch-wasm+milestone%3A9.0.0) or let's propose some topic which makes sense for your project.

Ping me on [discord](https://aka.ms/dotnet-discord) I can help you get started after 20th Sep or our team in `#webassembly` room

**Comment by Elringus** [comment]
Will do, thanks!
