### ISSUE TITLE
Maybe convert Parallel.ForEachAsync to ValueTask instead of Task

### ISSUE THREAD

**Issue by MartinDemberger** [dotnet/runtime#89552]
### Description

In one of my performance tests which use a lot of `Parallel.ForEachAsync` I had the case that the memory footprint exploded and no work was done anymore.
I found that a lot of Task.ContingentProperties and Task<Object> are in memory.

### Analysis

Maybe if you change `Parallel.ForEach` and `Paralle.ForEachAsync` to ValueTask instead of Task this may be a little less memory consuming.

**Comment by huoyaoyuan** [comment]
Changing method return type is an unacceptable breaking change, unfortunately.

**Comment by huoyaoyuan** [comment]
Note that `ForAsync` and `ForeachAsync` already accepts `ValueTask` for each item, which is used much more.

**Comment by MartinDemberger** [comment]
Thank you very much for the explanation.
