### ISSUE TITLE
[Android][Test] Failed to install mobile app

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#89567]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=353048
Build error leg or test failing: 
Pull request: https://github.com/dotnet/runtime/pull/89467

## Error Message
```
System.AggregateException : One or more errors occurred. (Failed to install mobile app.
      Expected: True
      Actual:   False) (The following constructor parameters did not have matching fixture data: _Global globalVar)
      ---- Failed to install mobile app.
      Expected: True
      Actual:   False
      ---- The following constructor parameters did not have matching fixture data: _Global globalVar
      Stack Trace:
        
        ----- Inner Stack Trace #1 (Xunit.Sdk.TrueException) -----
           at Interop_NativeLibrary._Global..ctor()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
        ----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```
Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Failed to install mobile app",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=353048
**Error message validated:** `Failed to install mobile app`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 7/27/2023 2:36:55 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[362691](https://dev.azure.com/dnceng-public/public/_build/results?buildId=362691)|dotnet/runtime|[Interop.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=362691&view=ms.vss-test-web.build-test-results-tab&runId=7663954&resultId=100283)||
|[362596](https://dev.azure.com/dnceng-public/public/_build/results?buildId=362596)|dotnet/runtime|[baseservices.threading.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=362596&view=ms.vss-test-web.build-test-results-tab&runId=7661270&resultId=102677)|dotnet/runtime#89003|
|[362306](https://dev.azure.com/dnceng-public/public/_build/results?buildId=362306)|dotnet/runtime|[nativeaot.SmokeTests.UnitTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=362306&view=ms.vss-test-web.build-test-results-tab&runId=7654220&resultId=100002)|dotnet/runtime#89932|
|[361849](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361849)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361849&view=ms.vss-test-web.build-test-results-tab&runId=7643478&resultId=100282)||
|[361403](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361403)|dotnet/runtime|[baseservices.invalid_operations.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361403&view=ms.vss-test-web.build-test-results-tab&runId=7630662&resultId=100285)|dotnet/runtime#88724|
|[361283](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361283)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361283&view=ms.vss-test-web.build-test-results-tab&runId=7628118&resultId=100285)||
|[361259](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361259)|dotnet/runtime|[JIT/Methodical/ldtoken/_il_dbgtypes/_il_dbgtypes.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361259&view=ms.vss-test-web.build-test-results-tab&runId=7627226&resultId=100704)||
|[360331](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360331)|dotnet/runtime|[nativeaot.SmokeTests.UnitTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360331&view=ms.vss-test-web.build-test-results-tab&runId=7603256&resultId=100002)||
|[360148](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360148)|dotnet/runtime|[JIT.Regression.CLR-x86-JIT.V1-M09-M11.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360148&view=ms.vss-test-web.build-test-results-tab&runId=7598400&resultId=102675)|dotnet/runtime#89814|
|[360125](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360125)|dotnet/runtime|[Loader.classloader.generics.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360125&view=ms.vss-test-web.build-test-results-tab&runId=7598064&resultId=102955)||
|[360127](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360127)|dotnet/runtime|[JIT/Methodical/eh/basics/emptyfinally_d/emptyfinally_d.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360127&view=ms.vss-test-web.build-test-results-tab&runId=7598198&resultId=100982)||
|[360116](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360116)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360116&view=ms.vss-test-web.build-test-results-tab&runId=7597884&resultId=100285)|dotnet/runtime#89829|
|[359818](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359818)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359818&view=ms.vss-test-web.build-test-results-tab&runId=7591324&resultId=100282)|dotnet/runtime#89809|
|[359734](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359734)|dotnet/runtime|[JIT/Methodical/ldtoken/_il_dbgtypes/_il_dbgtypes.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359734&view=ms.vss-test-web.build-test-results-tab&runId=7586490&resultId=100320)||
|[359654](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359654)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359654&view=ms.vss-test-web.build-test-results-tab&runId=7583894&resultId=100285)||
|[359522](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359522)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359522&view=ms.vss-test-web.build-test-results-tab&runId=7581222&resultId=102677)|dotnet/runtime#89805|
|[359526](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359526)|dotnet/runtime|[JIT/Methodical/Arrays/huge/_il_relhuge_b/_il_relhuge_b.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359526&view=ms.vss-test-web.build-test-results-tab&runId=7581240&resultId=101027)|dotnet/runtime#89009|
|[359427](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359427)|dotnet/runtime|[JIT.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359427&view=ms.vss-test-web.build-test-results-tab&runId=7578952&resultId=100285)|dotnet/runtime#89260|
|[358612](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358612)|dotnet/runtime|[JIT.PGO.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358612&view=ms.vss-test-web.build-test-results-tab&runId=7555142&resultId=100285)||
|[358004](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358004)|dotnet/runtime|[JIT.Math.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358004&view=ms.vss-test-web.build-test-results-tab&runId=7538084&resultId=100282)||
|[357141](https://dev.azure.com/dnceng-public/public/_build/results?buildId=357141)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=357141&view=ms.vss-test-web.build-test-results-tab&runId=7517494&resultId=100285)||
|[357075](https://dev.azure.com/dnceng-public/public/_build/results?buildId=357075)|dotnet/runtime|[baseservices.mono.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=357075&view=ms.vss-test-web.build-test-results-tab&runId=7515188&resultId=100285)|dotnet/runtime#89696|
|[356877](https://dev.azure.com/dnceng-public/public/_build/results?buildId=356877)|dotnet/runtime|[baseservices.mono.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=356877&view=ms.vss-test-web.build-test-results-tab&runId=7509512&resultId=100285)||
|[356421](https://dev.azure.com/dnceng-public/public/_build/results?buildId=356421)|dotnet/runtime|[baseservices/threading/coverage/OSThreadId/osthreadid/osthreadid.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=356421&view=ms.vss-test-web.build-test-results-tab&runId=7498452&resultId=100187)||
|[356351](https://dev.azure.com/dnceng-public/public/_build/results?buildId=356351)|dotnet/runtime|[JIT.Math.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=356351&view=ms.vss-test-web.build-test-results-tab&runId=7497240&resultId=100285)|dotnet/runtime#89638|
|[356170](https://dev.azure.com/dnceng-public/public/_build/results?buildId=356170)|dotnet/runtime|[JIT.Math.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=356170&view=ms.vss-test-web.build-test-results-tab&runId=7491922&resultId=100282)||
|[355235](https://dev.azure.com/dnceng-public/public/_build/results?buildId=355235)|dotnet/runtime|[baseservices.threading.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=355235&view=ms.vss-test-web.build-test-results-tab&runId=7471368&resultId=102677)|dotnet/runtime#89009|
|[355027](https://dev.azure.com/dnceng-public/public/_build/results?buildId=355027)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=355027&view=ms.vss-test-web.build-test-results-tab&runId=7465578&resultId=102677)|dotnet/runtime#89619|
|[355019](https://dev.azure.com/dnceng-public/public/_build/results?buildId=355019)|dotnet/runtime|[JIT.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=355019&view=ms.vss-test-web.build-test-results-tab&runId=7465810&resultId=100285)||
|[354674](https://dev.azure.com/dnceng-public/public/_build/results?buildId=354674)|dotnet/runtime|[baseservices.invalid_operations.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=354674&view=ms.vss-test-web.build-test-results-tab&runId=7456050&resultId=100282)|dotnet/runtime#89521|
|[354230](https://dev.azure.com/dnceng-public/public/_build/results?buildId=354230)|dotnet/runtime|[JIT.IL_Conformance.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=354230&view=ms.vss-test-web.build-test-results-tab&runId=7445288&resultId=102890)||
|[354241](https://dev.azure.com/dnceng-public/public/_build/results?buildId=354241)|dotnet/runtime|[nativeaot.SmokeTests.UnitTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=354241&view=ms.vss-test-web.build-test-results-tab&runId=7445466&resultId=100002)|dotnet/runtime#89223|
|[353999](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353999)|dotnet/runtime|[baseservices.invalid_operations.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353999&view=ms.vss-test-web.build-test-results-tab&runId=7440914&resultId=100282)|dotnet/runtime#89569|
|[353048](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353048)|dotnet/runtime|[baseservices.invalid_operations.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353048&view=ms.vss-test-web.build-test-results-tab&runId=7418034&resultId=100285)|dotnet/runtime#89467|
|[352553](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352553)|dotnet/runtime|[baseservices.mono.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352553&view=ms.vss-test-web.build-test-results-tab&runId=7406830&resultId=100282)|dotnet/runtime#89498|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|3|26|35|

**Comment by fanyang-mono** [comment]
cc: @premun Are you aware of any known issue which could call the Android app failing to be installed?

**Comment by SamMonoRT** [comment]
@lambdageek - I'm seeing some logs failures indicating there were some warnings (I guess now treated as errors after https://github.com/dotnet/runtime/pull/89197/files ?) I'm not sure if these are related to the change though - https://dev.azure.com/dnceng-public/public/_build/results?buildId=353048&view=logs&j=11fc76eb-f2d5-5967-e9b4-f54329587f75&t=5d22afdd-fd55-5fd8-7ab1-37ebf23474bd


/__w/1/s/src/mono/msbuild/android/build/AndroidBuild.targets(259,5): error MSB4018: Scanning dependencies of target System.Threading.Channels.dll [/__w/1/s/src/tests/FunctionalTests/Android/Device_Emulator/AOT/Android.Device_Emulator.Aot.Test.csproj]
/__w/1/s/src/mono/msbuild/android/build/AndroidBuild.targets(259,5): error MSB4018: [ 65%] Building ASM object CMakeFiles/System.Threading.Channels.dll.dir/__w/1/s/artifacts/obj/Android.Device_Emulator.Aot.Test/Release/net8.0/android-arm64/mobile/System.Threading.Channels.dll.s.o [/__w/1/s/src/tests/FunctionalTests/Android/Device_Emulator/AOT/Android.Device_Emulator.Aot.Test.csproj]
/__w/1/s/src/mono/msbuild/android/build/AndroidBuild.targets(259,5): error MSB4018: clang: warning: argument unused during compilation: '-D FORCE_AOT=1' [-Wunused-command-line-argument] [/__w/1/s/src/tests/FunctionalTests/Android/Device_Emulator/AOT/Android.Device_Emulator.Aot.Test.csproj]
/__w/1/s/src/mono/msbuild/android/build/AndroidBuild.targets(259,5): error MSB4018: clang: warning: argument unused during compilation: '-D STATIC_AOT=1' [-Wunused-command-line-argument] [/__w/1/s/src/tests/FunctionalTests/Android/Device_Emulator/AOT/Android.Device_Emulator.Aot.Test.csproj]
/__w/1/s/src/mono/msbuild/android/build/AndroidBuild.targets(259,5): error MSB4018: clang: warning: argument unused during compilation: '-D ANDROID' [-Wunused-command-line-argument] [/__w/1/s/src/tests/FunctionalTests/Android/Device_Emulator/AOT/Android.Device_Emulator.Aot.Test.csproj]
/__w/1/s/src/mono/msbuild/android/build/AndroidBuild.targets(259,5): error MSB4018: clang: warning: argument unused during compilation: '-fdata-sections' [-Wunused-command-line-argument] [/__w/1/s/src/tests/FunctionalTests/Android/Device_Emulator/AOT/Android.Device_Emulator.Aot.Test.csproj]
/__w/1/s/src/mono/msbuild/android/build/AndroidBuild.targets(259,5): error MSB4018: clang: warning: argument unused during compilation: '-ffunction-sections' [-Wunused-command-line-argument] [/__w/1/s/src/tests/FunctionalTests/Android/Device_Emulator/AOT/Android.Device_Emulator.Aot.Test.csproj]
/__w/1/s/src/mono/msbuild/android/build/AndroidBuild.targets(259,5): error MSB4018: clang: warning: argument unused during compilation: '-funwind-tables' [-Wunused-command-line-argument] [/__w/1/s/src/tests/FunctionalTests/Android/Device_Emulator/AOT/Android.Device_Emulator.Aot.Test.csproj]
/__w/1/s/src/mono/msbuild/android/build/AndroidBuild.targets(259,5): error MSB4018: clang: warning: argument unused during compilation: '-fstack-protector-strong' [-Wunused-command-line-argument] [/__w/1/s/src/tests/FunctionalTests/Android/Device_Emulator/AOT/Android.Device_Emulator.Aot.Test.csproj]
/__w/1/s/src/mono/msbuild/android/build/AndroidBuild.targets(259,5): error MSB4018: clang: warning: argument unused during compilation: '-D _FORTIFY_SOURCE=2' [-Wunused-command-line-argument] [/__w/1/s/src/tests/FunctionalTests/Android/Device_Emulator/AOT/Android.Device_Emulator.Aot.Test.csproj]

**Comment by lambdageek** [comment]
@SamMonoRT Not all warnings are treated as errors - only the missing prototype warnings are treated as errors.  However the compiler now emits more warnings (`-Wall` is new from #89197, also).  So those other ones are harmless.

Also @akoeplinger fixes the `register_aot_modules` error which I guess is what is making the builds fail https://github.com/dotnet/runtime/pull/89922

**Comment by akoeplinger** [comment]
Yes I think that specific error should be fixed now. Let's close this.
