### ISSUE TITLE
[browser] Suport for OutputType Library

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#89577]
currently WASM projects need to be `<OutputType>Exe</OutputType>`

use case: nuget library with component for Blazor, including `[JSImport]`

**Comment by pavelsavara** [comment]
For the "wasm application without main" what would be the use-case ?
Could we have blazor component with wasm functionality as nuget and then add that to non-wasm blazor project and expect it to work ?

Could we have dotnet wasm wrapped as react component and somehow flow it thru asp.net core in a way which would initialize the dotnet.js ?

I feel that the answer is probably not with nuget.

Could the same thing be achieved with npm package and node/webpack ecosystem ? Possibly yes.

**Comment by maraf** [comment]
If it's not the "wasm application without main" case, we can close the issue
