### ISSUE TITLE
ComInterfaceGenerator should warn on PreserveSig methods that return a struct named HResult

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#89603]
Unlike built-in COM, source generated COM is using the `MemberFunction` calling convention. This calling convention is correct for COM, but will cause failures for any code that blindly converts their COM interfaces that also happen to use an HResult struct. We should detect this case and warn the user that they need to define a custom marshaller for their HResult type.

**Comment by AaronRobinsonMSFT** [comment]
> We should detect this case and warn the user that they need to define a custom marshaller for their HResult type.

I'm not overly thrilled with the following suggestion, but since this pattern is so pervasive perhaps we should have a pre-canned marshaller for this and just apply it?

**Comment by jkoritzinsky** [comment]
We could have a predefined marshaller that users could apply, but I'd rather not auto-apply it just to any struct named `HResult`. I'd rather the user have to manually apply it. We could provide a code-fix to enable it.
