### ISSUE TITLE
[API Proposal]: Java-like throws keyword in method signature

### ISSUE THREAD

**Issue by HarryRobertson** [dotnet/runtime#89622]
### Background and motivation

Null and Exceptions are similar in that they can both function as hidden return types. With nullable reference types we got a powerful tool in the fight against bugs. If the warnings are treated as errors, it's now almost impossible to get a NullReferenceException.

Another source of bugs is unhandled exceptions, and these too would benefit from compiler-enforced handling. Including information about what _can_ be thrown as an optional feature, generating warnigns when these exceptions are not handled or bubbled up, and allowing developers to upgrade these warnings to errors would eliminate a whole class of bugs in dotnet.

### API Proposal

```csharp
namespace System.Collections.Generic;

public class MyFancyCollection<T> : IEnumerable<T>
{
    public void Fancy(T item) throws OutOfRangeException;
}
```

### API Usage

```csharp
void MethodCallingFancy(MyFancyCollection<int> fancyCollection)
{
    try
    {
        c.Fancy(42);
    }
    catch(OutOfRangeException)
    {
        // handle without throwing...
    }

    // Getting the values out
    foreach (var v in c)
        Console.WriteLine(v);
}
```
OR
```csharp
void MethodCallingFancy(MyFancyCollection<int> fancyCollection) throws OutOfRangeException
{
    c.Fancy(42);

    // Getting the values out
    foreach (var v in c)
        Console.WriteLine(v);
}
```

### Alternative Designs

There could be better ways to do this - for example as a discriminated union return type, although this may be less clear in its purpose.

### Risks

This would be a breaking change so would need to be opt-in following the same approach as nullable reference types.

**Comment by pinkfloydx33** [comment]
This sounds like checked exceptions, which would be a _language_ feature and [unlikely to ever happen](https://github.com/dotnet/csharplang/discussions/429#discussioncomment-68080).
