### ISSUE TITLE
[API Proposal]: Create vectors of lower dimension from vectors of higher dimension

### ISSUE THREAD

**Issue by PavielKraskouski** [dotnet/runtime#89647]
### Background and motivation

Current API provides methods to create vectors of higher dimension from vectors of lower dimensions. For example, we can create `Vector4` from `Vector3` and `W` or from `Vector2`, `Z` and `W`. I propose to add new constructors and methods to existing vector structures to go from higher to lower dimensions. This can be used when projecting three-dimensional vertices onto the plane to go from three dimensions to two, or when converting from four-dimensional homogeneous coordinates to three-dimensional coordinates.

### API Proposal

```csharp
namespace System.Numerics;

public struct Vector2
{
    public Vector2(Vector3 value) : this(value.X, value.Y)
    {
    }

    public Vector2(Vector4 value) : this(value.X, value.Y)
    {
    }
}

public struct Vector3
{
    public Vector3(Vector4 value) : this(value.X, value.Y, value.Z)
    {
    }

    public Vector2 ToVector2() => new Vector2(X, Y);
}

public struct Vector4
{
    public Vector2 ToVector2() => new Vector2(X, Y);
    public Vector3 ToVector3() => new Vector2(X, Y, Z);
}
```

### API Usage

```csharp
Vector4 v1 = new(1, 2, 3, 4);
Vector4 v2 = new(5, 6, 7, 8);
Vector2 v1v2 = (v2 - v1).ToVector2();
// Vector2 v1v2 = new(v2 - v1);
```

**Comment by EgorBo** [comment]
Related: https://github.com/dotnet/runtime/issues/86220

**Comment by tannergooding** [comment]
This was resolved and we now have `.AsVector2()` and `.AsVector3()` APIs
