### ISSUE TITLE
ETW::GCLog::ForceGCForDiagnostics uses AttachCurrentThread

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#89649]
As [this ](https://github.com/dotnet/runtime/pull/89516#discussion_r1275444979)comment observes, `ThreadStore::AttachCurrentThread()` is disallowed in GC Server scenarios. Filing this issue to track if this needs to be changed.

**Comment by jkotas** [comment]
ForceGCForDiagnostics should be only called on the event pipe threads. It should not be called on server GC threads or some other threads not owned by event pipe.

It should be fine for ForceGCForDiagnostics to attach the thread to runtime. CoreCLR version of the method does that too.

I think this issue can be closed.
