### ISSUE TITLE
NativeAOT publishing with MSBuild doesn't work with .NET 8 SDK

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#89659]
### Description

I'm trying to build my [ComputeSharp WASDK Win32 CLI sample](https://github.com/Sergio0694/ComputeSharp/tree/main/samples/ComputeSharp.SwapChain.D2D1.Cli) with NativeAOT using the preview .NET 8 SDK (especially because .NET 7 builds fail at runtime due to https://github.com/dotnet/runtime/issues/84908), but I'm unable to actually get a publish build to be created correctly. I'm oing exactly the same steps I did previously, but it seems when I use the .NET 8 SDK, I just get a normal CoreCLR publish build? 🤔

### Baseline (.NET 7)

- Checkout https://github.com/Sergio0694/ComputeSharp/commit/70f80003eb95a6f93bee28adb492c6822dce7420
- Open a VS Developer PowerShell prompt (need MSBuild)
- Go to folder and publish:
```powershell
cd samples\ComputeSharp.SwapChain.D2D1;
msbuild ComputeSharp.SwapChain.D2D1.csproj -t:restore,publish /p:Configuration=Release /p:Platform=x64 /p:RuntimeIdentifier=win10-x64;
```

Verify that the publish folder has the expected NativeAOT .exe file.
Of course, it'll crash at startup after the first frame, due to https://github.com/dotnet/runtime/issues/84908.

### Regression (.NET 8)

- Checkout https://github.com/Sergio0694/ComputeSharp/commit/773f8c49f81e5298ed49db5b8ffc17bd6933f83d
- Open a VS Preview Developer PowerShell prompt (need MSBuild and the .NET 8 Preview SDK)
- Go to folder and publish:
```powershell
cd samples\ComputeSharp.SwapChain.D2D1.Cli;
msbuild ComputeSharp.SwapChain.D2D1.Cli.csproj -t:restore,publish /p:Configuration=Release /p:Platform=x64 /p:RuntimeIdentifier=win10-x64
```

Observe how the publish folder actually has a lot of random stuff from what seems to be a normal publish build.
In fact, trying to open shows it's not even self-contained, as it's presumably using the default settings:

![](https://github.com/dotnet/runtime/assets/10199417/311630b2-7b43-4d58-99ef-f23043da3cae)

### Expected behavior

I would expect a NativeAOT publish build to be created, just like on .NET 7.

### Actual behavior

I end up getting a normal publish build with default settings, and not a NativeAOT one.

### Regression?

Yes (works on .NET 7).

### Configuration

- .NET 7.0.306
- .NET 8.0.100-preview.7.23364.32
- Windows 11 Enterprise 22621.1992

**Comment by am11** [comment]
> msbuild ComputeSharp.SwapChain.D2D1.csproj -t:restore,publish /p:Configuration=Release /p:Platform=x64 /p:RuntimeIdentifier=win10-x64;

Does it work with the top-level `-restore` option?

```
msbuild ComputeSharp.SwapChain.D2D1.csproj -restore -t:publish /p:Configuration=Release /p:Platform=x64 /p:RuntimeIdentifier=win10-x64;
```

**Comment by Sergio0694** [comment]
Alright I fixed it, there were a few problems:
- `-t:restore,publish` doesn't work with the .NET 8 SDK, had to use `/restore -t:publish`, same as @am11 suggested (fixed in https://github.com/Sergio0694/ComputeSharp/pull/545). Not sure why it worked with the .NET 7 SDK.
- The .NET 8 SDK changed from needing `win10-x64` as RID to `win-x64`, and WASDK wasn't updated for that yet. @jkoritzinsky said he'd let the team now. In the meantime, I could work around it by adding `/p:RuntimeIdentifiers=win-x64`.
- Had to also leave `/p:RuntimeIdentifier=win10-x64` otherwise the building wouldn't copy the native .dll from Win2D to the output directory.

For this last part, @MichalStrehovsky is this something that should be handled by the SDK, by WASDK, or is this something we should fix on Win2D's end? Not sure where to report that or whether that's something we can fix ourselves 😄

**Comment by NCLnclNCL** [comment]
Dont use net8 preview 7, you cannot build with it

**Comment by AaronRobinsonMSFT** [comment]
> The .NET 8 SDK changed from needing win10-x64 as RID to win-x64, and WASDK wasn't updated for that yet.

Is this something all SDKs will need to respond to? I believe this was the RID update work. Are there other SDK teams we should contact?

/cc @elinor-fung

**Comment by jkoritzinsky** [comment]
So I was a little wrong on the SDK part of the rid problem. The actual problem was that the WinAppSDK sets the RuntimeIdentifiers property to include Windows-ARM RIDs, which aren't supported.

The fact that the package puts files into the win10-* rid folders is a problem as the breaking change with the RID graph will affect packages like that.

**Comment by Sergio0694** [comment]
Oh... What would the correct way to handle that on Win2D's side then, should we just update our two packages to use `win-` folders and update our targets? Would this mean that this would then only work for .NET 8+, but not work anymore for anyone on .NET 7 or below? And would this be transparent to C++ consumers, I suppose? 🤔

**Comment by jkoritzinsky** [comment]
> Oh... What would the correct way to handle that on Win2D's side then, should we just update our two packages to use `win-` folders and update our targets? Would this mean that this would then only work for .NET 8+, but not work anymore for anyone on .NET 7 or below? And would this be transparent to C++ consumers, I suppose? 🤔

Unless you need to use separate APIs for each Windows version, just use the win- folders and it’ll still work downlevel.

**Comment by Sergio0694** [comment]
Perfect. Yeah no, we ship the same .winmd/.dll for all versions of Windows, so we can then just fix the folders then 👍
Thank you! 😄

Should I close this issue? I assume the issue with WASDK is tracked separately?

**Comment by jkoritzinsky** [comment]
I haven’t had a chance to file an issue on WASDK, so let’s leave this open until I do that.

**Comment by jkoritzinsky** [comment]
Opened https://github.com/microsoft/WindowsAppSDK/issues/3783.
