### ISSUE TITLE
ETW need a mechanism to get an activity_id

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#89657]
NativeAOT is using the activity_id support from [EventPipe](https://github.com/dotnet/runtime/blob/main/src/native/eventpipe/ep-thread.h#L30) library, similar to the mono runtime, as [this ](https://github.com/dotnet/runtime/pull/89516#discussion_r1275374247)discussion shows. However, `CoreCLR` tracks the [activity_id ](https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/threads.h#L4307)in thread, which can be used by both `EventPipe` and `ETW`. `NativeAOT `need to provide support to get an `activity_id `for ETW as well.

**Comment by jkotas** [comment]
Where does ETW read thread activity ID in CoreCLR? I am not able to see it.

**Comment by LakshanF** [comment]
You are right, its only used in [EventPipe](https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/eventing/eventpipe/ep-rt-coreclr.h#L1763) and through [managed code](https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/eventpipeinternal.cpp#L158). ETW doesn't need this. Thanks!
