### ISSUE TITLE
HttpListener.Getcontext() not working on linux.

### ISSUE THREAD

**Issue by apilatosba** [dotnet/runtime#89671]
### Description

```csharp
using System.Net;
using System.Text;

namespace github_issue_report {
   internal class Program {
      static async Task Main(string[] args) {
         for (; ; ) {
            using HttpListener httpListener = new HttpListener();
            httpListener.Prefixes.Add($"http://+:80/");
            httpListener.Start();

            await Console.Out.WriteLineAsync("111");
            var context = await httpListener.GetContextAsync();
            await Console.Out.WriteLineAsync("222");

            var request = context.Request;
            var response = context.Response;

            byte[] buffer = Encoding.UTF8.GetBytes("hello");
            response.ContentLength64 = buffer.Length;
            var output = response.OutputStream;
            output.Write(buffer, 0, buffer.Length);

            output.Close();
            httpListener.Stop();
         }
      }
   }
}
```
When I run this program on windows it works fine. But when i run it on manjaro (all packages are up to date) it never accepts an incoming connection ie. program outputs 111 to console but never 222.  
I can ping machine and it responds back so there is no issues with firewall settings. I actually have an equivalent program that uses Socket instead of HttpListener. And socket program works, both on windows and on manjaro.
```csharp
using System.Net;
using System.Text;
using System.Net.Sockets;

namespace github_issue_report {
   internal class Program {
      static async Task Main(string[] args) {
         for (; ; ) {
            using Socket listener = new Socket(
               AddressFamily.InterNetworkV6,
               SocketType.Stream,
               ProtocolType.Tcp);


            listener.Bind(new IPEndPoint(IPAddress.IPv6Any, 80));
            listener.Listen();

            using Socket socket = listener.Accept();
            listener.Close();

            byte[] buffer = new byte[2048];

            // Receive
            for (; ; ) {
               if (socket.Available == 0) break;
               int bytesReceived = socket.Receive(buffer);
            }

            // Send
            string response = "hello";
            for (int bytesSent = 0; bytesSent < response.Length;
               bytesSent += socket.Send(Encoding.ASCII.GetBytes(response)))
               ;

            socket.Close();
         }
      }
   }
}
```
I am using IPv6. 
Also I ran the program on debian and results are same with manjaro's.
You need to run the program as admin on windows or as root user on linux.
I am kind of new to programming and this is my first time reporting an issue, so forgive me if I am missing something very simple.

### Reproduction Steps

Run the first piece of code in the description on manjaro or on debian, and try to connect.

### Expected behavior

Expected behaviour is I think HttpListener.GetContext() should be responsive on linux as well.

### Actual behavior

Actual behaviour is, HttpListener.GetContext() is not responsive on linux.

### Known Workarounds

Not using HttpListener on linux but using sockets. Or using another http server library.

### Configuration

version of .NET is .NET6.
relevant OSes are manjaro, debian11.6.0 and windows10.

**Comment by apilatosba** [comment]
After posting that I realised and found where the problem is. On windows everything perfect with no issues but on linux
```csharp
httpListener.Prefixes.Add($"http://+:80/");
```
this piece of code is the problem. You can't use "+" or "*" as it is said in the documentation page. In documentation page it says you can listen for all incoming requests on a port by using "+" or "*". But it seems like it is wrong. I used my domain name instead of "+" and it worked.

**Comment by wfurt** [comment]
I'm glad you figure it out. Note that if you use port bigger than 1024 you will not need root or admin privilege. Running everything privileged is possible security risk.

**Comment by apilatosba** [comment]
Yeah, I figured out what the bug is. Isn't it need to be fixed or something? Or at least, put something to documentation page about it maybe, so other devs know it doesn't work.
