### ISSUE TITLE
Provide a way to delete symbols with native AOT

### ISSUE THREAD

**Issue by richlander** [dotnet/runtime#89686]
The production of symbols is challenging for container users, since glob-based copying is common. For Dockerfiles, that requires the use of a separate `RUN rm` command. For SDK container builds, there is no convenient solution since the copying is done with the SDK implementation.

Ideally, symbols would be opt-in for release builds. Small size is one of the dominant value props of native AOT and we expect containers to be a dominant deployment model.

Here's a good comparison. The first image is built with `docker build` with a manual Dockerfile instruction to remove symbols. The second image is build using `dotnet publish`.

```bash
$ docker images | grep release
releasesapi                         latest               ac28888af2c1   About a minute ago   28.3MB
maplesugar.azurecr.io/releasesapi   latest               0b10fe76d5b4   18 hours ago         73.1MB
```

**Comment by MichalStrehovsky** [comment]
You can set `<CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>` if you don't want symbols copied to publish output. We still produce them so the user can archive them someplace else if they want, but they will not be part of the publish output.

#88780 tracks not generating them at all in the first place. That already works on Windows, needs a bit of .targets work on Linux due to symbol handling being different with stripping and all. Note in that case there's no symbols, so no dump debugging either (or only for adventurous people).

I think the first property will address your use case.

**Comment by richlander** [comment]
Thanks for that. I tried it and don't see a difference.

```bash
rich@vancouver:~/git/dotnet-docker/samples/releasesapi-aot$ cat *.csproj
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
<CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
</PropertyGroup>
</Project>

rich@vancouver:~/git/dotnet-docker/samples/releasesapi-aot$ docker run --rm -it -v $(pwd):/source -v /home/rich/.docker:/root/.docker -w /source mcr.microsoft.com/dotnet/aot-sdk:latest dotnet publish /p:PublishProfile=DefaultContainer /p:ContainerBaseImage=mcr.microsoft.com/dotnet/runtime-deps:8.0-preview-jammy-chiseled /p:ContainerRegistry=maplesugar.azurecr.io
MSBuild version 17.7.0+5785ed5c2 for .NET
  Determining projects to restore...
  Restored /source/releasesapi.csproj (in 4.27 sec).
/usr/share/dotnet/sdk/8.0.100-preview.6.23330.14/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(314,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/source/releasesapi.csproj]
  releasesapi -> /source/bin/Release/net8.0/linux-x64/releasesapi.dll
  releasesapi -> /source/bin/Release/net8.0/linux-x64/publish/
  Building image 'releasesapi' with tags latest on top of base image mcr.microsoft.com/dotnet/runtime-deps:8.0-preview-jammy-chiseled
  Uploading layer sha256:a253d5a1e257f9f936b736e65aea1c3a06188f403be94a81eb0ebf4159ed7445 to maplesugar.azurecr.io
  Uploading layer sha256:7c0e4d4597c7e15d78b35aa8fbc5203ec06c27a73e835838659a2cfa2b6fbe4f to maplesugar.azurecr.io
  Layer sha256:a253d5a1e257f9f936b736e65aea1c3a06188f403be94a81eb0ebf4159ed7445 already existed
  Finished uploading layer sha256:7c0e4d4597c7e15d78b35aa8fbc5203ec06c27a73e835838659a2cfa2b6fbe4f to maplesugar.azurecr.io
  Uploading config to registry at blob sha256:dab813e708e13fc0b3f0b3a0fb447180566b1d60435eeb80a36f77f09ad33158
  Uploaded config to registry
  Uploading manifest to registry maplesugar.azurecr.io as blob sha256:7ee799ff58651a627c1e18b2bee9892917132f47fb59bb46897d9344862d1f3a
  Uploaded manifest to maplesugar.azurecr.io
  Uploading tag latest to maplesugar.azurecr.io
  Uploaded tag latest to maplesugar.azurecr.io
  Pushed image 'maplesugar.azurecr.io/releasesapi:latest' to registry 'maplesugar.azurecr.io'
rich@vancouver:~/git/dotnet-docker/samples/releasesapi-aot$ docker pull maplesugar.azurecr.io/releasesapi:latest
latest: Pulling from releasesapi
a253d5a1e257: Already exists 
7c0e4d4597c7: Pull complete 
Digest: sha256:7ee799ff58651a627c1e18b2bee9892917132f47fb59bb46897d9344862d1f3a
Status: Downloaded newer image for maplesugar.azurecr.io/releasesapi:latest
maplesugar.azurecr.io/releasesapi:latest
rich@vancouver:~/git/dotnet-docker/samples/releasesapi-aot$ docker images maplesugar.azurecr.io/releasesapi:latest
REPOSITORY                          TAG       IMAGE ID       CREATED          SIZE
maplesugar.azurecr.io/releasesapi   latest    dab813e708e1   27 seconds ago   73.1MB
rich@vancouver:~/git/dotnet-docker/samples/releasesapi-aot$ docker build -t app -f Dockerfile.ubuntu .
rich@vancouver:~/git/dotnet-docker/samples/releasesapi-aot$ docker images app
REPOSITORY   TAG       IMAGE ID       CREATED         SIZE
app          latest    f524590fa593   7 seconds ago   28.3MB
```

**Comment by am11** [comment]
`CopyOutputSymbolsToPublishDirectory=false` support in NativeAOT is relatively new (merged 2 weeks ago). e.g. with 8.0.100-rc.1.23378.5 (daily build), the publish directory do not have a symbols file on my machine.

Having a symbols file for a rainy day under non-publish directory (`bin/Release/{Framework}/{RID/}native`) directory (even with `CopyOutputSymbolsToPublishDirectory=false`), when someone really wants to debug their app in production, is good to have, IMHO. e.g. folks can upload it to their company's symbols store, then pull it with [`dotnet symbol --server-path <http server path>`](https://github.com/dotnet/symstore/blob/main/src/dotnet-symbol/Program.cs#L85) when needed. Therefore, I personally hope that we skip implementing support for https://github.com/dotnet/runtime/issues/88780. :)

**Comment by richlander** [comment]
Looks good! I validated the experience with RC1.

The use case / suggestion from @am11 makes sense to me.
