### ISSUE TITLE
Unhandled exception. System.TypeLoadException with struct

### ISSUE THREAD

**Issue by kzhui125** [dotnet/runtime#89690]
with dotnet 7.0.304, the following code works:

```cs
TestStruct2 t2 = default;
Console.WriteLine(t2.Test.Run(t2));

Console.WriteLine("Hello, World!");

public struct TestStruct2
{
    public TestStruct1<TestStruct2, string> Test => new();
}

public struct TestStruct1<RT, A> where RT : struct
{
    public string Run(RT rt) => typeof(RT).ToString();
}
```

But with the following code, I get `Unhandled exception. System.TypeLoadException: Could not load type 'TestStruct2' from assembly 'TestConsole, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.`

```cs
TestStruct2 t2 = new() { Test = new() };
Console.WriteLine(t2.Test.Run(t2));

Console.WriteLine("Hello, World!");

public struct TestStruct2
{
    public TestStruct1<TestStruct2, string> Test { get; init; }
}

public struct TestStruct1<RT, A> where RT : struct
{
    public string Run(RT rt) => typeof(RT).ToString();
}
```

I want to pass TestStruct1 instance to TestStruct2, instead of use `=> new();` inside TestStruct1.

How can I achieve this, is this a runtime bug?

Thanks,

see also https://github.com/dotnet/aspnetcore/issues/49736

**Comment by ufcpp** [comment]
https://github.com/dotnet/runtime/issues/6924#issuecomment-547078135 ?

**Comment by kzhui125** [comment]
@ufcpp Thanks, looks like the same issue.

I have tested the code in dotnet `8.0.100-preview.6.23330.14`, it seems fiexd in dotnet 8.

Anyone knows if there is a workaround in dotnet7? To pass a TestStruct1 instance to TestStruct2...

Thanks,

**Comment by kzhui125** [comment]
In my application use case, I only need inject a singleton TestStruct1 to inject to TestStruct2.

So I have found a workaround:

```cs
TestStruct2Globals.SetTest(new());

TestStruct2 t2 = default;
Console.WriteLine(t2.GlobalTest.Run(t2));

Console.WriteLine("Hello, World!");

public static class TestStruct2Globals
{
    public static void SetTest(TestStruct1<TestStruct2, string> test) => Test = test; // only be called once
    public static TestStruct1<TestStruct2, string> Test { get; private set; }
}

public struct TestStruct2
{
    public TestStruct1<TestStruct2, string> GlobalTest => TestStruct2Globals.Test;
}

public struct TestStruct1<RT, A> where RT : struct
{
    public string Run(RT rt) => typeof(RT).ToString();
}
```

Thanks,
