### ISSUE TITLE
area-ILVerification and area-Tools-ILVerification

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#89693]
These two label exist and seem to have duplicate purposes. Should they be consolidated?

It seems like the former was recently introduced whereas the latter has existed for some time.

**Comment by jkotas** [comment]
`area-ILVerification` was renamed to `area-Tools-ILVerification` in https://github.com/dotnet/runtime/pull/81958/files#diff-c05c405016080fb559ebcdb8844d3e12114169e55e77788fe200ec62b45afb78L439. 

The labelling bot seems uses the old name (see https://github.com/dotnet/runtime/issues/89691). Do we need to refresh the labeling bot data?
