### ISSUE TITLE
ManualResetEventSlim.Set() should throw ObjectDisposedException

### ISSUE THREAD

**Issue by ericmutta** [dotnet/runtime#89692]
I was writing some tests to confirm that if you dispose a `ManualResetEventSlim` object then try to use any of its members, you get an `ObjectDisposedException`. This seems to be true for the `Wait()`, `Reset()` and `WaitHandle` members, but is not the case for the `Set()` and `IsSet` members as the following xUnit test shows:

```csharp
  [Fact]
  public static void Test() {
    // create an event and dispose it immediately.
    var mre = new ManualResetEventSlim(initialState: false);
    mre.Dispose();

    // the following assertions work as expected.
    Assert.Throws<ObjectDisposedException>(() => mre.Wait());
    Assert.Throws<ObjectDisposedException>(() => mre.Reset());
    Assert.Throws<ObjectDisposedException>(() => mre.WaitHandle);

    // but the following assertions fail...what gives?
    Assert.Throws<ObjectDisposedException>(() => mre.Set());
    Assert.Throws<ObjectDisposedException>(() => mre.IsSet);
  }
``` 

I can see [we have tests](https://github.com/dotnet/runtime/blob/bd83e17052d3c09022bad1d91dca860ca6b27ab9/src/libraries/System.Threading/tests/ManualResetEventSlimTests.cs#L100C16-L100C16) which confirm that an `ObjectDisposedException` is thrown for the  `Wait()`, `Reset()` and `WaitHandle` members, but there is no equivalent check for the `Set()` and `IsSet` members.

**Is there a technical reason for allowing the `Set()` method and the `IsSet` property to be used on a disposed `ManualResetEventSlim` object without throwing an exception like we do for the other members?**

CC: @stephentoub, @danmoseley

**Comment by ericmutta** [comment]
Incidentally, the non-slim version, i.e. `ManualResetEvent` DOES throw as expected, when you call `Set()` on a disposed object. This can be confirmed using this test which runs successfully:

```csharp
  [Fact]
  public static void Test() {
    // create an event and dispose it immediately.
    var mre = new ManualResetEvent(initialState: false);
    mre.Dispose();

    // ManualResetEvent.Set() does throw as expected.
    Assert.Throws<ObjectDisposedException>(() => mre.Set());
  }
```

This difference between `ManualResetEvent` and `ManualResetEventSlim` leads me to think we may have a bug here.

**Comment by danmoseley** [comment]
Is it the same on .NET Framework?

**Comment by ericmutta** [comment]
@danmoseley  I have only tested on .NET 7, but looking at the git blame for those tests I linked to, it seems they were touched 8 years ago, so its likely this was inhrited from the .NET Framework but I would have to test to be sure when I get back to the office tomorrow 👍

**Comment by stephentoub** [comment]
I've no doubt it was done purposefully, but it was over a decade ago and I don't remove what the reasoning was.

I don't think it's worth adding checks and throws at this point.

**Comment by ericmutta** [comment]
Closing as per the feedback from @stephentoub (it is not super important for my use case for the exception to be thrown) 👍
