### ISSUE TITLE
Configuration model binding skips entire objects when enum binding fails

### ISSUE THREAD

**Issue by thedmi** [dotnet/runtime#89715]
### Description

Behavior of configuration model binding with `ConfigurationBinder.Bind(this IConfiguration configuration, object? instance)` prohibits use of enums in config models if they are nested in the object structure. Specifically, entire list elements are skipped if an unknown enum literal is tried somewhere in that list element.

The observed behavior makes using enums in config binding problematic, unless provided configuration is guaranteed to be valid and only contain known enum literals. This is often not the case, as configuration is provided "from the outside" and must be validated first.

### Reproduction Steps

The following code snippet contains two unit tests. The first shows that the code works when a valid enum literal `Value2` is provided. The second test fails with an empty list, even though the list in the provided JSON was **not** empty, it just contained an undefined enum literal.

```csharp
using Microsoft.Extensions.Configuration;

namespace ConfigBindingRepro;

public class Tests
{
    [Test]
    public void Config_binding_with_known_enum_literal_works()
    {
        var json = """
            {
                "SomeList": [ 
                    { "StringProp": "some", "EnumProp": "Value2" } 
                ]
            }
            """u8;
        
        var config = LoadConfig(json);

        Assert.That(config.SomeList.Count, Is.EqualTo(1));
        Assert.That(config.SomeList[0], Is.EqualTo(new ListItem { StringProp = "some", EnumProp = TheEnum.Value2 }));
    }
    
    [Test]
    public void Config_binding_with_unknown_enum_literal_binds_null()
    {
        var json = """
            {
                "SomeList": [ 
                    { "StringProp": "some", "EnumProp": "Unknown" } 
                ]
            }
            """u8;
        
        var config = LoadConfig(json);

        Assert.That(config.SomeList.Count, Is.EqualTo(1));
        Assert.That(config.SomeList[0], Is.EqualTo(new ListItem { StringProp = "some", EnumProp = null }));
    }

    private static Config LoadConfig(ReadOnlySpan<byte> json)
    {
        var builder = new ConfigurationBuilder();

        using var memoryStream = new MemoryStream(json.ToArray());
        
        builder.AddJsonStream(memoryStream);

        var configRoot = builder.Build();
        var config = new Config();
        configRoot.Bind(config);
        
        return config;
    }

    public record Config
    {
        public List<ListItem> SomeList { get; init; }
    }

    public record ListItem
    {
        public string? StringProp { get; init; }
        
        public TheEnum? EnumProp { get; init; }
    }

    public enum TheEnum
    {
        Value1,
        Value2
    }
}
```

Used nuget packages:

- Microsoft.Extensions.Configuration Version="7.0.0"
- Microsoft.Extensions.Configuration.Binder Version="7.0.4"
- Microsoft.Extensions.Configuration.Json" Version="7.0.0"

### Expected behavior

- The nullable enum property should be initialized with null when trying to bind an unknown enum literal.
- Containing objects should not be affected by failed enum binding (the list should have 1 element in the provided example).

### Actual behavior

Failed enum model binding aborts model binding for whole containing object trees.

### Regression?

Same problem on .NET 7.0.1

### Known Workarounds

Bind enum value as string and then convert manually. But that kind of defeats the idea of model binding :-)

### Configuration

- .NET SDK 7.0.306 /  .NET Runtime 7.0.9
- Windows 10
- x64

**Comment by tarekgh** [comment]
The configuration is not intended to be used in this manner. Simply overlooking incorrect values within the configuration is not the appropriate approach. Instead, it is advisable to enable error handling, which would prompt the system to raise errors when encountered with wrong values. Subsequently, the ideal course of action would be to address these errors by modifying the configuration to ensure proper binding.

```C#
    configRoot.Bind(config, o => o.ErrorOnUnknownConfiguration = true);
```

and then should get the exception like 

```
Unhandled exception. System.InvalidOperationException: 'ErrorOnUnknownConfiguration' was set and binding has failed. The likely cause is an invalid configuration value.
 ---> System.InvalidOperationException: Failed to convert configuration value at 'SomeList:0:EnumProp' to type 'NetCoreApp.Program+TheEnumeration'.
 ---> System.FormatException: Unknown is not a valid value for TheEnumeration.
 ---> System.ArgumentException: Requested value 'Unknown' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.TryConvertValue(Type type, String value, String path, Object& result, Exception& error)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, BindingPoint bindingPoint, IConfiguration config, BinderOptions options, Boolean isParentCollection)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperties(Object instance, IConfiguration configuration, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, BindingPoint bindingPoint, IConfiguration config, BinderOptions options, Boolean isParentCollection)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindCollection(Object collection, Type collectionType, IConfiguration config, BinderOptions options)
```

**Comment by thedmi** [comment]
> Simply overlooking incorrect values within the configuration is not the appropriate approach.

I fully agree, but that is exactly what the current implementation does, and even more blatantly than in my suggested alternative.

I find the current behavior **very** surprising and cannot see a case where one would want to drop whole object hierarchies because of failed enum parsing. Granted, enabling `ErrorOnUnknownConfiguration` avoids that, but then the discussion should probably be about why that isn't the default.

**Comment by tarekgh** [comment]
> but then the discussion should probably be about why that isn't the default.

Because we care a lot about application compatibility. changing the default behavior is a big breaking change which we should avoid.
