### ISSUE TITLE
[AOT][Blazor][Net8] String.ToLower performance issue

### ISSUE THREAD

**Issue by arivoir** [dotnet/runtime#89735]
Executing the method String.ToLower is taking too much time in a WASM Blazor application using Net8

![image](https://github.com/dotnet/runtime/assets/17496741/413db56a-3efd-4e56-be13-68e83a0400b1)

And the string is not longer than 3 characters.

**Comment by SamMonoRT** [comment]
cc @radekdoulik @vargaz

**Comment by lewing** [comment]
Please include the version of .NET you are using

**Comment by kg** [comment]
If you could provide a test application or more info on the scenario that would be useful too. Are you calling ToLower in your own code? It looks like from the stack trace it's happening inside of Blazor. We have some measurements specifically for ToLower/ToUpper in our benchmark suite that haven't shown this anomaly so we definitely want to figure out what's happening.

**Comment by lewing** [comment]
Do you see the same problem without the profiler enabled?

**Comment by arivoir** [comment]
I'm seeing this problem disappear when compiling the application in "Release" configuration.

![image](https://github.com/dotnet/runtime/assets/17496741/7629070c-df2c-4748-abc5-d0eaea199ad5)

The 58ms now are 0.59ms

Dotnet 8.0.100-preview.6.23330.14
