### ISSUE TITLE
Configuration-binding source generator: Binding logic was not generated for a binder call

### ISSUE THREAD

**Issue by eduherminio** [dotnet/runtime#89732]
### Description

I'm trying to use the new configuration-binding source generator in my console application, but it's not working for my use case and I'm not sure why.
I'm getting: `warning SYSLIB1104: Binding logic was not generated for a binder call. Unsupported input patterns include generic calls and passing boxed objects.`

-----

Context: this same code, if compiled with `/p:PublishTrimmed=true` stops working as expected and reading the values from the configuration files/env variables.
That's why I'm looking to move to the source generator asap.
Any workaround until it works properly is also welcome, of course 😊

### Reproduction Steps

Given:

```csharp
public static class Configuration
{
    public static GeneralSettings GeneralSettings { get; set; } = new GeneralSettings();
}

public sealed class GeneralSettings
{
    public bool DisableLogging { get; set; } = false;
}
```

This bind call isn't behaving as expected:
```csharp
var environmentName = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") ?? "Production";
var config = new ConfigurationBuilder()
    .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
    .AddJsonFile($"appsettings.{environmentName}.json", optional: true, reloadOnChange: true)
    .AddEnvironmentVariables()
    .Build();

config.GetRequiredSection(nameof(GeneralSettings)).Bind(Configuration.GeneralSettings); // <-----------------
```

### Expected behavior

Source generator is used

### Actual behavior

Source generator isn't used and warning is triggered, therefore can't trim the app properly and load the configuration from file/env variable.

### Configuration

```log
.NET SDK:
 Version:   8.0.100-preview.6.23330.14
 Commit:    ba97796b8f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
```

### Other information

Same error as in https://github.com/dotnet/runtime/issues/89273, but no generics involved here.

**Comment by layomia** [comment]
Thanks. Related to https://github.com/dotnet/runtime/pull/89537 & https://github.com/dotnet/runtime/issues/89273. Will fix in that PR if I can repro with latest bits.

**Comment by eduherminio** [comment]
Thanks to you for the quick answer, a real project to reproduce it is [lynx-chess/Lynx](https://github.com/lynx-chess/Lynx/tree/net-8), `net-8` branch.

**Comment by eduherminio** [comment]
@layomia Did it make the cut for `preview-7`?
