### ISSUE TITLE
Comparers don't work for messy generic corner cases

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#89767]
Compile the repro below with/without optimizations.

Without optimizations, this prints:

```
Here
False
True
```

That's good.

With optimizations, this prints:

```
Here
False
Here
False
```

That's not so good.

```csharp
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
{
    MyStruct<object, object> s1 = default;
    MyStruct<object, object> s2 = default;
    Console.WriteLine(Equals(s1, s2));
}

{
    MyStruct<object, string> s1 = default;
    MyStruct<object, string> s2 = default;
    Console.WriteLine(Equals(s1, s2));
}

[MethodImpl(MethodImplOptions.NoInlining)]
static bool Equals<T>(T x, T y)
{
    return EqualityComparer<T>.Default.Equals(x, y);
}

struct MyStruct<T, U> : IEquatable<MyStruct<U, U>>
{
    public bool Equals(MyStruct<U, U> other)
    {
        Console.WriteLine("Here");
        return false;
    }
}
```

**Comment by MichalStrehovsky** [comment]
(To be clear, this issue is not for Native AOT, it's broken for JIT scenarios. It's also broken on Native AOT but I'm going to wait until there's a defined behavior for this, defined by the JIT side.)

**Comment by jakobbotsch** [comment]
What is the non-NAOT repro case? This one doesn't seem to repro without NativeAOT for me.

**Comment by jakobbotsch** [comment]
(Seems like it was failing just recently until #88006. Also https://github.com/dotnet/runtime/pull/88006#issuecomment-1622324118 looks related.)

**Comment by JulieLeeMSFT** [comment]
@EgorBo PTAL. CC @jkotas.

**Comment by jkotas** [comment]
This is a bug in native AOT implementation of JIT/EE interface. I will take a look.

**Comment by MichalStrehovsky** [comment]
I would have sworn I tested it with the latest installer build but probably fell into the trap of having something else on PATH. Sorry for the noise.
