### ISSUE TITLE
Breaking change in WebAssembly loadBootResource

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/runtime#89766]
The change in PR #89435 (merged a few days ago) appears not to be back-compatible and is probably causing the SDK ingestion https://github.com/dotnet/aspnetcore/pull/49704 to fail.

Specifically, when calling the application's `loadBootResource` callback, it now passes different values for the `type` parameter, and imposes new rules that are stricter than we had in the past. Existing applications' `loadBootResource` implementations may not support these new types/rules.

As a concrete example, see the Blazor docs at https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-7.0. This page contains the following code sample:

```html
<script src="_framework/blazor.webassembly.js" autostart="false"></script>
<script>
  Blazor.start({
    loadBootResource: function (type, name, defaultUri, integrity) {
      if (type == 'dotnetjs') {
        return null;
      } else {
        return fetch(defaultUri, {
          cache: 'no-cache',
          integrity: integrity,
          headers: { 'Custom-Header': 'Custom Value' }
        });
      }
    }
  });
</script>
```

This works with 7.0, but will break after PR #89435 because the runtime now supplies the new type name `js-module-runtime`, which is not a documented type. The logic above will perform a `fetch` request for the resource, since the only documented type that can't be fetched is `dotnetjs`. Then the runtime will reject the value, giving the exception message *For a js-module-runtime resource, custom loaders must supply a URI string*. This is one of the build failures at https://github.com/dotnet/aspnetcore/runs/15504558324

### Proposed resolution

For any resource type that you don't accept a `Promise<Response>` value, use the type name `dotnetjs` for back-compat. Avoid adding new type names that impose stricter rules than existed before.

cc @pavelsavara @maraf @lewing

**Comment by SteveSandersonMS** [comment]
Note, this isn't necessarily the *only* build-breaking problem introduced in this SDK update. There are also possibly some different failures, since some other tests instead fail with:

`dotnet.js 2:917 "MONO_WASM: Failed to resolve module specifier 'WasmMinimal/_framework/dotnet.runtime.8.0.0-rc.1.23379.8.j5ye6ne55d.js'\nTypeError: Failed to resolve module specifier 'WasmMinimal/_framework/dotnet.runtime.8.0.0-rc.1.23379.8.j5ye6ne55d.js' [Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/356713/logs/13)`

**Comment by SteveSandersonMS** [comment]
Actually that indicates there's also a second breaking change. The logic in `run.ts`'s `importModules` looks wrong because it assumes the URL formats will be compliant with ES dynamic import, but that's not true in general.

For example: 

* `import('https://some/full/url.js')` is legal
* `import('./a/b/url.js')` is legal
* `import('/a/b/url.js')` is legal
* `import('a/b/url.js')` is **not** legal and will cause the *Failed to resolve module specifier* error

That is, URLs must be absolute or rooted with `/` or relative to `.`.

### Proposed resolution

Resolve all URLs into absolute ones using the same technique that Blazor used in .NET 7:

https://github.com/dotnet/aspnetcore/blob/c64d745c863088e6bb6390984b7fe93782e686c3/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L173-L174

```ts
  const absoluteSrc = (new URL(src, document.baseURI)).toString();
  return await import(/* webpackIgnore: true */ absoluteSrc);
```

**Comment by pavelsavara** [comment]
> For any resource type that you don't accept a `Promise<Response>` value, use the type name `dotnetjs` for back-compat. Avoid adding new type names that impose stricter rules than existed before.

We are calling that `loadBootResource` extension point in order to allow the 3rd party to customize the location of javascript files. But now there are more JS files than before and so we could not use same `dotnetjs` to distinguish them.

The enforcement that it will return non-null is a bug, I will fix it.

**Comment by pavelsavara** [comment]
> To fix the unqualified case, we have to make assumption about script directory, in which case the `document.baseURI` doesn't match normal `import` behavior.

It seems we already have this behavior for some time. I will implement it consistently with document.baseURI and document it.

**Comment by SteveSandersonMS** [comment]
> But now there are more JS files than before and so we could not use same dotnetjs to distinguish them.
> Edit: we are also sending the name.
> The enforcement that it will return non-null is a bug, I will fix it.

I'm not certain exactly what you're saying you'll fix here, but there are existing implementations of the `loadBootResource` callback out in the wild (such as the one in our docs, shown above) which we need not to break.

**Comment by pavelsavara** [comment]
> I'm not certain exactly what you're saying you'll fix here, but there are existing implementations of the `loadBootResource` callback out in the wild (such as the one in our docs, shown above) which we need not to break.

I will return back to mapping asset types for `loadBootResource` as before with `dotnetjs` `WebAssemblyBootResourceType`.
I will also add new last parameter `behavior?: AssetBehaviors` to `loadBootResource` signature. In JavaScript this is not breaking change and it will allow implementers to differentiate JS modules.
