### ISSUE TITLE
[API Proposal]: System.IO.MatchType.Regex

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#89760]
### Background and motivation

We often run into the situation where we want to get a list of files having more than one file extension. Currently it's only possible to get a list of ALL files and then pick the files ourselves. Often this looks like:

```C#
var textFiles = new DirectoryInfo("...").EnumerateFiles("*.*").Where(f => f.Extension == ".txt" || f.Extension == ".log" || f.Extension == ".json");
```

This has a lot of unnecessary allocations and with many files this can become very slow. Ideally we would have more control over the file enumeration itself. There are multiple ways for implementing and I'm open for a better suggestion but my idea is that we have an existing enum of `MatchType` which specifies the way of how the search pattern is read and regex not only allows looking for multiple extensions but also gives more room for other scenarios.

### API Proposal

```csharp
namespace System.IO;

public enum MatchType
{
    Simple,
    Win32,
    Regex
}
```

### API Usage

```csharp
var textFiles = new DirectoryInfo("...").EnumerateFiles("^.*\.(txt|log|json)$", new EnumerationOptions { MatchType = MatchType.Regex});
```

**Comment by JanTamis** [comment]
You can use this api: https://learn.microsoft.com/en-us/dotnet/api/system.io.enumeration.filesystemenumerable-1?view=net-7.0
