### ISSUE TITLE
[Test Failure] System.Net.Security.Tests.CertificateValidationRemoteServer.DefaultConnect_EndToEnd_Ok(host: "www.microsoft.com")

### ISSUE THREAD

**Issue by rzikm** [dotnet/runtime#89779]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=352466
Build error leg or test failing: System.Net.Security.Tests.CertificateValidationRemoteServer.DefaultConnect_EndToEnd_Ok
Pull request: https://github.com/dotnet/runtime/pull/89452

Console: https://[helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-8f1f0a9c4e7648d3b9/System.Net.Security.Tests/3/console.d6731305.log?helixlogtype=result](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-8f1f0a9c4e7648d3b9/System.Net.Security.Tests/3/console.d6731305.log?helixlogtype=result)

Occurs on Win 7 and Win 8.1 runs. Does not repro on Win 11.

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=352466
**Error message validated:** `Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 8/1/2023 1:53:23 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[359012](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359012)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.DefaultConnect_EndToEnd_Ok](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359012&view=ms.vss-test-web.build-test-results-tab&runId=7564684&resultId=103197)|dotnet/runtime#89742|
|[358709](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358709)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.DefaultConnect_EndToEnd_Ok](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358709&view=ms.vss-test-web.build-test-results-tab&runId=7557186&resultId=103060)||
|[358708](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358708)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.DefaultConnect_EndToEnd_Ok](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358708&view=ms.vss-test-web.build-test-results-tab&runId=7556904&resultId=104202)||
|[358702](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358702)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.DefaultConnect_EndToEnd_Ok](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358702&view=ms.vss-test-web.build-test-results-tab&runId=7556808&resultId=104232)||
|[358686](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358686)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.DefaultConnect_EndToEnd_Ok](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358686&view=ms.vss-test-web.build-test-results-tab&runId=7556988&resultId=102819)||
|[358705](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358705)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.DefaultConnect_EndToEnd_Ok](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358705&view=ms.vss-test-web.build-test-results-tab&runId=7556758&resultId=104229)||
|[358693](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358693)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.DefaultConnect_EndToEnd_Ok](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358693&view=ms.vss-test-web.build-test-results-tab&runId=7556960&resultId=102793)||
|[358679](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358679)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.DefaultConnect_EndToEnd_Ok](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358679&view=ms.vss-test-web.build-test-results-tab&runId=7556718&resultId=104398)||
|[358694](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358694)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.DefaultConnect_EndToEnd_Ok](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358694&view=ms.vss-test-web.build-test-results-tab&runId=7557066&resultId=103423)||
|[358692](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358692)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.DefaultConnect_EndToEnd_Ok](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358692&view=ms.vss-test-web.build-test-results-tab&runId=7556686&resultId=104215)||
|[358689](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358689)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.DefaultConnect_EndToEnd_Ok](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358689&view=ms.vss-test-web.build-test-results-tab&runId=7556654&resultId=104431)||
|[358690](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358690)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.DefaultConnect_EndToEnd_Ok](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358690&view=ms.vss-test-web.build-test-results-tab&runId=7556890&resultId=103138)||
|[358684](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358684)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.DefaultConnect_EndToEnd_Ok](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358684&view=ms.vss-test-web.build-test-results-tab&runId=7556666&resultId=104503)||
|[358677](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358677)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.DefaultConnect_EndToEnd_Ok](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358677&view=ms.vss-test-web.build-test-results-tab&runId=7556620&resultId=104545)||
|[356202](https://dev.azure.com/dnceng-public/public/_build/results?buildId=356202)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.DefaultConnect_EndToEnd_Ok](https://dev.azure.com/dnceng-public/public/_build/results?buildId=356202&view=ms.vss-test-web.build-test-results-tab&runId=7493196&resultId=103198)||
|[352466](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352466)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.DefaultConnect_EndToEnd_Ok](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352466&view=ms.vss-test-web.build-test-results-tab&runId=7403932&resultId=103217)|dotnet/runtime#89452|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|14|16|16|

**Comment by vcsjones** [comment]
Seems like microsoft.com changed to use a very modern cipher suite configuration that Windows 7 and 8.1 do not support.
