### ISSUE TITLE
FPE (Formet preservation encryption) FF1/FF3 supports in .Net

### ISSUE THREAD

**Issue by jiten87** [dotnet/runtime#89818]
Not sure about the right forum to ask this query like Is there any plan to support FPE FF1/FF3 in any upcoming releases

**Comment by jeffhandley** [comment]
From what I can tell, FF1/FF3 have not progressed the last few years and there isn't a clear path toward availability in Windows CNG or OpenSSL. Some resources I referenced:
* openssl/openssl/issues/5131 (shows OpenSSL is holding on this)
* https://www.nist.gov/news-events/news/2019/02/methods-format-preserving-encryption-nist-requests-public-comments-draft (this seems to be the last activity on the topic)
* https://github.com/0NG/Format-Preserving-Encryption

I'm assessing this as unlikely to move forward and therefore closing the issue. If Windows CNG and/or OpenSSL do ever provide support, a new https://github.com/dotnet/runtime/labels/api-suggestion issue can be submitted.
