### ISSUE TITLE
Native AOT libraries for iOS and Android

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#89817]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Native-AOT-libraries-for-iOS-and-Android/10419270)._

---
[severity:It's more difficult to complete my work]
We have some .NET libraries that we want use with native iOS and Android apps. Is it possible to publish a native AOT library in .NET 8 for use on those platforms? If not, is there a plan to support native libraries on mobile platforms, and what are limitation of doing so?

---
#### Feedback Bot on 7/19/2023, 06:45 PM: 

(private comment, text removed)
#### Roi Chen [MSFT] on 7/19/2023, 11:38 PM: 

(private comment, text removed)
#### Feedback Bot on 7/20/2023, 08:11 PM: 

(private comment, text removed)

**Comment by MichalStrehovsky** [comment]
Yes, it is possible - see this document for instructions on Android: https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/android-bionic.md

For iOS it's possible with workarounds. The end-to-end experience is tracked in #88737.

Please file issues or comment on the other issue if there's problems with this.
