### ISSUE TITLE
MSB6006: "csc.dll" exited with code 143

### ISSUE THREAD

**Issue by vpapidokha** [dotnet/runtime#89820]
Summary of the issue:
Randomly getting the error during CI process, but don't see any kind of regularity. As much as we don't see detailed information about problem neither in the log output nor on the internet.

Log from build process:
```
13:55:33 /usr/share/dotnet/sdk/5.0.100/Roslyn/Microsoft.CSharp.Core.targets(71,5): error MSB6006: "csc.dll" exited with code 143. [/var/lib/jenkins/workspace/*.csproj]
13:55:33 MSBUILD : error MSB4166: Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in "/tmp/" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
13:55:33 /usr/share/dotnet/sdk/5.0.100/Roslyn/Microsoft.CSharp.Core.targets(71,5): warning MSB5021: Terminating the task executable "dotnet" and its child processes because the build was canceled. [/var/lib/jenkins/workspace/*.csproj]
13:55:33 /usr/share/dotnet/sdk/5.0.100/Roslyn/Microsoft.CSharp.Core.targets(71,5): error MSB4181: The "Csc" task returned false but did not log an error. [/var/lib/jenkins/workspace/*.csproj]
```

The mentioned in the log output file MSBuild_*.failure.txt is absent. We have several in our /tmp directory, but the time of their creation is significantly differentiate. However, I see a bunch of files that have relevant time stamps, but didn't find any helpful info about them.

```
srwxrwxr-x   1 jenkins       jenkins           0 Jul 23 13:54 MSBuild90636
srwxrwxr-x   1 jenkins       jenkins           0 Jul 23 13:55 MSBuild90655
srwxrwxr-x   1 jenkins       jenkins           0 Jul 23 13:55 MSBuild90671
srwxrwxr-x   1 jenkins       jenkins           0 Jul 23 13:55 MSBuild90689
srwxrwxr-x   1 jenkins       jenkins           0 Jul 23 13:55 MSBuild90707
srwxrwxr-x   1 jenkins       jenkins           0 Jul 23 13:57 MSBuild92987
srwxrwxr-x   1 jenkins       jenkins           0 Jul 23 13:57 MSBuild93003
srwxrwxr-x   1 jenkins       jenkins           0 Jul 23 13:57 MSBuild93019
srwxrwxr-x   1 jenkins       jenkins           0 Jul 23 13:57 MSBuild93038
srwxrwxr-x   1 jenkins       jenkins           0 Jul 23 13:57 MSBuild93066
```

Version used:
dotnet --version 5.0.100

OS:
Linux version 3.10.0-1127.10.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ) dotnet/sdk#1 SMP

Steps to reproduce:
```
dotnet build -c Releas project_name.sln
```

Expected Behavior:
Build SUCCESS.

Actual Behavior:
Build FAILED.

**Comment by joeloff** [comment]
Had a chat with Jared. Suggeted this was/is likely runtime related since there's no stack trace

**Comment by mangod9** [comment]
Since this issue is two years old. @vpapidokha, does this continue to repro for you?

**Comment by vpapidokha** [comment]
No,it stopped reproducing at some moment. But thanks for the response😅

**Comment by mangod9** [comment]
Ok thanks for confirming, will close for now.
