### ISSUE TITLE
[API Proposal]: Add Min and Max properties to SortedDictionary.Keys

### ISSUE THREAD

**Issue by pawchen** [dotnet/runtime#89837]
### Background and motivation

`SortedDictionary<K, V>` is a wrapper over `SortedSet<KeyValuePair<K, V>>`, while `SortedSet<K>` has `Min` and `Max` properties, they are not accessible from `SortedDictionary<K, V>.Keys`.

Using `SortedSet<KeyValuePair<K, V>>` is a workaround, but the implementation of `SortedDictionary<K, V>.set_Item[K key]` is more efficient since it [uses internal](https://source.dot.net/#System.Collections/System/Collections/Generic/SortedDictionary.cs,130) of the underlying `SortedSet`, as well as `ContainsValue`.

### API Proposal

```csharp
namespace System.Collections.Generic;

public sealed class KeyCollection
{
    public TKey Min => _dictionary._set.Min.Key;
    public TKey Max => _dictionary._set.Max.Key;
}
```

### API Usage

```csharp
var dict = new SortedDictionary<int, int>();
dict.Add(0, 1);
dict.Add(1, 1);

var minKey = dict.Keys.Min;
var maxKey = dict.Keys.Max;
```

### Alternative Designs

Add `MaxKey` and `MinKey` to `SortedDictionary<K, V>`.

**Comment by eiriktsarpalis** [comment]
I believe this is proposal is covered by https://github.com/dotnet/runtime/issues/77645, more specifically https://github.com/dotnet/runtime/issues/77645#issuecomment-1551136097

**Comment by pawchen** [comment]
This proposal has nothing to do with views. It simply allows one to query Min and Max without creating a view.

**Comment by eiriktsarpalis** [comment]
> This proposal has nothing to do with views.

See the link I posted earlier:

> more specifically https://github.com/dotnet/runtime/issues/77645#issuecomment-1551136097

**Comment by pawchen** [comment]
The link to the comment proposes `view.Min`, this propose `Keys.Min`. Mentioned in the next comment right after it though.

**Comment by eiriktsarpalis** [comment]
Fair. Why put it on the key collection and not on the main collection though? It seems more difficult to discover.

**Comment by pawchen** [comment]
Yes, putting on the main collection is absolutely acceptable for me. Currently listed in the alternative design.
