### ISSUE TITLE
Does HttpClientHandler Proxy Property Apply to CRL Checks?

### ISSUE THREAD

**Issue by phadtrapong** [dotnet/runtime#89831]
I'm currently using HttpClientHandler in my .NET application and I have a question regarding its Proxy property. I noticed that during SSL connection "CRL Check" my service makes a connection to the Certificate Authority (CA) without using a proxy. However, after setting the DefaultProxy property for HttpClient, the calls to the CA started using the proxy. Is this the intended behavior?

Moreover, I'm curious to know if setting the Proxy property also affects calls to the CA during Certificate Revocation List (CRL) checks? Or is it only used for the main HTTP/HTTPS requests?

Any clarification or guidance would be greatly appreciated. Thanks in advance for your time and assistance!

**Comment by wfurt** [comment]
How do you set the proxy? If you set it via environment or via system setting then the setting is global for every HTTP transaction. If you set it explicitly on the handler it should impact only transation done by that handler. Since CLR/OCSP/AIA uses separate instance there should be no impact.

**Comment by phadtrapong** [comment]
Thank you for the responses, for setting up global proxy, I did it with environment variable Https_Proxy in linux base container. So, setting proxy for HttpClientHandler reference[Reference](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.proxy?view=net-7.0)  will only apply proxy to primary http request but not the CRL, thank you for confirmation.

**Comment by wfurt** [comment]
yes, environment is global e.g. it will impact all instances. Properties are specific to given instance.
