### ISSUE TITLE
Issue with DateTime.Parse in Blazor WebAssembly

### ISSUE THREAD

**Issue by mohanrajsf3477** [dotnet/runtime#89844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using DateTime.Parse in Blazor WebAssembly, I encountered an exception that prevents the method from working correctly. This issue occurs for Arabic culture. I have attached the sample and sample code below. Also, this sample works fine in Blazor Server. The issue occurs only in WebAssembly.

sample : https://github.com/mohanrajsf3477/DateTimeissue

sample code:
`<button @onclick="@parse">click to parse</button>
@code{
    private DateTime arabictoday = DateTime.Now;
    private void parse()
    {
        DateTime parsedate = DateTime.Parse(arabictoday.ToString());
    }
}`

### Expected Behavior

I expected the DateTime.Parse method to correctly parse the arabictoday variable and create a new DateTime object without any exceptions.

### Steps To Reproduce

- Run the sample
- click the "click to parse" button, see the issue.
- exception occur in webassembly project

**Comment by mohanrajsf3477** [comment]
Hi @ilonatommy ,

Any update ?

**Comment by ilonatommy** [comment]
The error for the repro (net6):
```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: String '3‏‏/8‏‏/2023 12:01:29 م' was not recognized as a valid DateTime.
System.FormatException: String '3‏‏/8‏‏/2023 12:01:29 م' was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(ReadOnlySpan`1 s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at System.DateTime.Parse(String s)
   at WasmLocalization.Pages.Index.parse() in WASM\WasmLocalization\Pages\Index.razor:line 12
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[Object](MulticastDelegate delegate, Object arg)
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync(Object arg)
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
   at Microsoft.AspNetCore.Components.EventCallback.InvokeAsync(Object arg)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs)
```

On upgrading to net 7.0.0, the error is gone. @lewing, the investigation is not critical for the net8 release, so I will update the triage.

**Comment by ilonatommy** [comment]
@mohanrajsf3477, could you please remove [right-to-left-mark](https://www.fileformat.info/info/unicode/char/200f/index.htm) fromt the string before putting it into the Parse?
```
DateTime.Parse(arabictoday.ToString().Replace("\u200F", ""))
```
That should work in net6.

**Comment by Clockwork-Muse** [comment]
.... would the rtl mark count as whitespace, that could be removed with the appropriate parse option?

**Comment by ilonatommy** [comment]
> .... would the rtl mark count as whitespace, that could be removed with the appropriate parse option?

If you mean [DateTimeStyle](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.parse?view=net-6.0#parsing-and-style-elements) then all whitespace options are marked as "is always permitted"/"this is the default behavior". I don't know about any build-in option that would remove trl.
