### ISSUE TITLE
System.Diagnostics.Tests.ProcessStartInfoTests.TestWindowStyle failing in CI

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#89842]
```
C:\h\w\C70B0A3A\w\B3E10966\e>"C:\h\w\C70B0A3A\p\dotnet.exe" exec --runtimeconfig System.Diagnostics.Process.Tests.runtimeconfig.json --depsfile System.Diagnostics.Process.Tests.deps.json xunit.console.dll System.Diagnostics.Process.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Diagnostics.Process.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Diagnostics.Process.Tests (found 263 of 290 test cases)
  Starting:    System.Diagnostics.Process.Tests (parallel test collections = on, max threads = 4)
    System.Diagnostics.Tests.ProcessStartInfoTests.TestWindowStyle(windowStyle: Minimized, useShellExecute: True) [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.Windows.cs(119,0): at System.Diagnostics.Tests.ProcessStartInfoTests.TestWindowStyle(ProcessWindowStyle windowStyle, Boolean useShellExecute)
           at InvokeStub_ProcessStartInfoTests.TestWindowStyle(Object, Span`1)
           at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Diagnostics.Tests.ProcessStartInfoTests.ShellExecute_Nano_Fails_Start [SKIP]
      Condition(s) not met: "IsWindowsNanoServer"
    System.Diagnostics.Tests.ProcessTests.NonElevatedUser_QueryProcessNameOfSystemProcess [SKIP]
      Condition(s) not met: "IsNotPrivilegedProcess"
Invalid number of parameters
0 File(s) copied
  Finished:    System.Diagnostics.Process.Tests
=== TEST EXECUTION SUMMARY ===
   System.Diagnostics.Process.Tests  Total: 332, Errors: 0, Failed: 1, Skipped: 2, Time: 122.366s
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=360083
Build error leg or test failing: System.Diagnostics.Tests.ProcessStartInfoTests.TestWindowStyle
Pull request: https://github.com/dotnet/runtime/pull/89836

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "TestWindowStyle",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=360083
**Error message validated:** `TestWindowStyle`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 8/2/2023 6:16:44 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by Jozkee** [comment]
It's not obvious to me what may be causing this error. It may be a simple timeout but this started to fail suddenly on 08/02
https://github.com/dotnet/runtime/blob/10d9e729f9ece24f89d73a5c6df18371c8db9360/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.Windows.cs#L118

And it only happens with `ProcessWindowStyle.Minimized` and `UseShellExecute=true`.
