### ISSUE TITLE
.net 7 Application not running when deployed to windows server.

### ISSUE THREAD

**Issue by bsNetDev** [dotnet/runtime#89850]
### Description

# .net 7 Application not running on the server.

I have a .net 7 application which runs on my machine. I can run it through powershell on my machine with no issue. I have added Console.WriteLine statements to the Program.cs file. When this application is deployed to the server and I try to run it via powershell I get the following output and the Console.WriteLine statements in the Program.cs are not output.

```
Executed as user: *Machine Name*\SYSTEM. 
info: Microsoft.Hosting.Lifetime[0]        
Application started. Press Ctrl+C to shut down.  
info: Microsoft.Hosting.Lifetime[0]        
Hosting environment: Production  
info: Microsoft.Hosting.Lifetime[0]        
Content root path: *application path*
```
For some context
1. I'm creating an IHost
2. I'm using a Worker
3. I'm using .ConfigureLogging(configLogging => configLogging.AddConsole())
4. I'm using .UseContentRoot(Environment.CurrentDirectory)
5. I'm using host.Run()

Thanks in advance for your help.

### Reproduction Steps

1. Open powershell in the application directory.
2.  ./Program.exe

### Expected behavior

It runs the application.

### Actual behavior

The application outputs the following:

```
Executed as user: *Machine Name*\SYSTEM. 
info: Microsoft.Hosting.Lifetime[0]        
Application started. Press Ctrl+C to shut down.  
info: Microsoft.Hosting.Lifetime[0]        
Hosting environment: Production  
info: Microsoft.Hosting.Lifetime[0]        
Content root path: *application path*
```

### Regression?

Not applicable. This is a new application.

### Known Workarounds

N/A

### Configuration

1. .net 7
2. Windows Server x64

### Other information

N/A

**Comment by steveharter** [comment]
Is the logged information in the failure case the same as the success case?

How do you know the app is not running?

Also see https://learn.microsoft.com/aspnet/core/fundamentals/logging/?view=aspnetcore-7.0 to change the logging level to enable more output.
