### ISSUE TITLE
Windows cannot open the folder

### ISSUE THREAD

**Issue by sierks** [dotnet/runtime#89871]
### Description

I am using System.IO.Compression.ZipArchive for .NET 4.7.2 to create Zip files. However, for many of them (but not all), I get an error message when opening the Zip files in Windows. “Windows cannot open the folder.”

The Zip files can be opened via code. They can also be opened via 7zip. But not Windows.

I've tested with dozens of different files and file types and haven't found anything definitive. But in these test PDFs, the "Public" one appears to be causing my issues. And I've validated it and it appears to be a good PDF. But it also happens with other files and file types.

When compared to a Zip file of the same source files created via Windows, the ZipArchive file is significantly larger.

[Fails - DotNetNative.zip](https://github.com/dotnet/runtime/files/12243884/Fails.-.DotNetNative.zip)
[Fails - DotNetNative_ASCII.zip](https://github.com/dotnet/runtime/files/12243885/Fails.-.DotNetNative_ASCII.zip)
[Fails - DotNetNative_ByteArray.zip](https://github.com/dotnet/runtime/files/12243886/Fails.-.DotNetNative_ByteArray.zip)
[Fails - DotNetNative_Fastest.zip](https://github.com/dotnet/runtime/files/12243887/Fails.-.DotNetNative_Fastest.zip)
[Fails - DotNetNative_PublicDeletedAndReAdded.zip](https://github.com/dotnet/runtime/files/12243888/Fails.-.DotNetNative_PublicDeletedAndReAdded.zip)
[Windows.zip](https://github.com/dotnet/runtime/files/12243890/Windows.zip)

### Reproduction Steps

This is my code for creating the Zip. It's very basic. It's all in memory as I have a web app. But this code comes from my Unit Test project and it's basically the same.
```
            using (var ms = new System.IO.MemoryStream())
            {
                using (var archive = new System.IO.Compression.ZipArchive(ms, System.IO.Compression.ZipArchiveMode.Create, true))
                {
                    foreach (var item in all)
                    {
                        var fileInArchive = archive.CreateEntry(item.Name, System.IO.Compression.CompressionLevel.Optimal);

                        using (var entryStream = fileInArchive.Open())
                        using (var fileToCompressStream = new System.IO.MemoryStream(item.Data))
                        {
                            fileToCompressStream.CopyTo(entryStream);
                        }
                    }
                }
            }
        }
```

This code produces the same invalid Zip file:
```
            using (var ms = new System.IO.MemoryStream())
            {
                using (var archive = new System.IO.Compression.ZipArchive(ms, System.IO.Compression.ZipArchiveMode.Create, true))
                {
                    foreach (var item in all)
                    {
                        var fileInArchive = archive.CreateEntry(item.Name, System.IO.Compression.CompressionLevel.Optimal);

                        using (var entryStream = fileInArchive.Open())
                        {
                            entryStream.Write(item.Data, 0, item.Data.Length);
                            entryStream.Flush();
                        }
                    }
                }
            }
```

### Expected behavior

A Zip file that can open via Windows. 
Perhaps a smaller Zip file?

### Actual behavior

The Zip opens via code. And via 7zip. But not via Windows, where I get a "Windows cannot open the folder" error.

### Known Workarounds

If I remove the "Public" PDF, or don't add it, the Zip file works as expected.
[Works - DotNetNative_DoubledNoPublic.zip](https://github.com/dotnet/runtime/files/12243894/Works.-.DotNetNative_DoubledNoPublic.zip)
[Works - DotNetNative_NoPublic.zip](https://github.com/dotnet/runtime/files/12243895/Works.-.DotNetNative_NoPublic.zip)
[Works - DotNetNative_Public.zip](https://github.com/dotnet/runtime/files/12243896/Works.-.DotNetNative_Public.zip)
[Works - DotNetNative_PublicDeleted.zip](https://github.com/dotnet/runtime/files/12243897/Works.-.DotNetNative_PublicDeleted.zip)

### Configuration

Windows 10 & 11.
.NET 4.7.2 running in Azure and locally.
x64

**Comment by carlossanlop** [comment]
Hello @sierks - Have you tested your code using .NET 6 or .NET 7 or .NET 8? Can you please let us know if you see the issue in any of those versions?

We track .NET Framework (4.7.5) issues in Visual Studio Developer Community, and in this repo we track the new .NET Core+.

If you only see your issue in 4.7.5 version, please open a bug here: https://developercommunity.visualstudio.com/dotnet/report

**Comment by danmoseley** [comment]
Anything stands out as special about the bad archive when you validate it eh with unzip -t or whatever?

https://unix.stackexchange.com/questions/197127/test-integrity-of-zip-file#197136

You can also look at detailed info in 7zip, it can list warnings even when it can extract successfully.

**Comment by sierks** [comment]
I will try to upgrade .NET versions and come back with my results.

**Comment by sierks** [comment]
> Anything stands out as special about the bad archive when you validate it eh with unzip -t or whatever?
> 
> https://unix.stackexchange.com/questions/197127/test-integrity-of-zip-file#197136
> 
> You can also look at detailed info in 7zip, it can list warnings even when it can extract successfully.

  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.

**Comment by sierks** [comment]
> Hello @sierks - Have you tested your code using .NET 6 or .NET 7 or .NET 8? Can you please let us know if you see the issue in any of those versions?
> 
> We track .NET Framework (4.7.5) issues in Visual Studio Developer Community, and in this repo we track the new .NET Core+.
> 
> If you only see your issue in 4.7.5 version, please open a bug here: https://developercommunity.visualstudio.com/dotnet/report

Both .NET 6 and .NET 7 have the same issue.
[DotNet6Native.zip](https://github.com/dotnet/runtime/files/12316577/DotNet6Native.zip)
[DotNet7Native.zip](https://github.com/dotnet/runtime/files/12316579/DotNet7Native.zip)

Both result in the same unzip -t error as before, too:
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.

But without that 1 PDF they both work in Windows and pass the unzip -t check.

**Comment by sierks** [comment]
Don't use GetBuffer on a MemoryStream. Use ToArray instead. My bad. Apologize for the wasted time.
