### ISSUE TITLE
NativeAOT fails to resolve PInvoke in `System.Data.SqlClient`

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#89874]
See https://github.com/dotnet/runtime/issues/89782#issuecomment-1662668501 for details.
The failure is really weird - I can confirm that the native dll is next to the AOT compiled app.
Non-AOT version of the app can load the dll just fine (it fails later on for me, but that's not the issue here).
I also tried just a simple app with a PInvoke (using Libuv package and calling into it) and that works just fine even with NativeAOT.

Repro steps:
https://github.com/dotnet/runtime/files/12243049/sqlClient.zip
Publish as AOT and run on win-x64.

```
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'sni.dll' or one of its dependencies: The specified module could not be found.
   at System.Runtime.InteropServices.NativeLibrary.LoadLibErrorTracker.Throw(String) + 0x6f
   at Internal.Runtime.CompilerHelpers.InteropHelpers.FixupModuleCell(InteropHelpers.ModuleFixupCell*) + 0xfd
   at Internal.Runtime.CompilerHelpers.InteropHelpers.ResolvePInvokeSlow(InteropHelpers.MethodFixupCell*) + 0x2f
   at System.Data.SqlClient.SNINativeMethodWrapper.UnmanagedIsTokenRestricted(IntPtr, Boolean&) + 0x31
   at System.Data.Win32NativeMethods.IsTokenRestrictedWrapper(IntPtr) + 0x19
   at System.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrentNative() + 0xb0
   at System.Data.ProviderBase.DbConnectionPoolGroup.GetConnectionPool(DbConnectionFactory) + 0x51
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPool(DbConnection, DbConnectionPoolGroup) + 0x5f
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection, TaskCompletionSource`1, DbConnectionOptions, DbConnectionInternal, DbConnectionInternal&) + 0xb6
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection, DbConnectionFactory, TaskCompletionSource`1, DbConnectionOptions) + 0x118
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1) + 0x101
   at System.Data.SqlClient.SqlConnection.Open() + 0xf8
   at Program.<Main>$(String[] args) + 0x45
   at sqlClient!<BaseAddress>+0x413074
```

**Comment by vitek-karas** [comment]
@MichalStrehovsky any ideas - I can try looking into it, but I don't know where to start really.

**Comment by jkotas** [comment]
`System.Data.SqlClient` is annotated with `DllImportSearchPath.AssemblyDirectory | DllImportSearchPath.System32` 

These search flags get passed correctly into `NativeLibrary.LoadLibraryByName` https://github.com/dotnet/runtime/blob/a743d6034023edb8472e974e20ff2b70cded1b10/src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/NativeLibrary.NativeAot.cs#L37-L40 that masks out `DllImportSearchPath.AssemblyDirectory` and so we are left with just `DllImportSearchPath.System32`.

The problem happens here: https://github.com/dotnet/runtime/blob/a743d6034023edb8472e974e20ff2b70cded1b10/src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/NativeLibrary.NativeAot.cs#L97-L101

We effectively ignore `DllImportSearchPath.AssemblyDirectory`/`searchAssemblyDirectory` and only pass `DllImportSearchPath.System32` into `LoadLibraryHelper`. There is no `sni.dll` in system32 directory and the attempt to load the library fails.

**Comment by vitek-karas** [comment]
That comment reads wrong - NativeAOT already made the decision to put native dependencies next to the exe (instead of the assembly the PInvoke came from), so treating `AssemblyDirectory` as "app directory" would make sense for NativeAOT (also - there's no other location to consider anyway).

**Comment by MichalStrehovsky** [comment]
This was written as "better to be conservative than to get an MSRC later". How does CoreCLR single file compute "the location of the assembly", is `AssemblyDirectory` just bashed to mean `ApplicationDirectory`? We could do the same, but cc @elinor-fung

**Comment by MichalStrehovsky** [comment]
> This was written as "better to be conservative than to get an MSRC later". How does CoreCLR single file compute "the location of the assembly", is `AssemblyDirectory` just bashed to mean `ApplicationDirectory`? We could do the same, but cc @elinor-fung

And how does this distinction look like for the "NativeAOT'd shared library" case?

**Comment by elinor-fung** [comment]
Single-file actually adds the app directory to NATIVE_DLL_SEARCH_DIRECTORIES: https://github.com/dotnet/runtime/pull/42876, https://github.com/dotnet/runtime/issues/42772
`AssemblyDirectory` is currently meaningless for assemblies bundled into the app executable and the app effectively always has `ApplicationDirectory`. (I do think making `AssemblyDirectory` for bundled assemblies mean the directory of the app they are bundled in makes more sense - especially now that single-file apps don't have the runtime native bits separate and next to it)

**Comment by vitek-karas** [comment]
I think this is something we should try to fix for .NET 8. I'll be out for the next week, so if somebody could pick this up?
Just to make it easier for whoever is going to work on this: @elinor-fung could you please paste a link here to where we have CoreCLR/Single-File tests for this? So that we can enable them for NativeAOT once this is fixed.

**Comment by elinor-fung** [comment]
The coreclr test cases are:
https://github.com/dotnet/runtime/blob/fa780339a2ea43e80892556b925e0cfa5c9ac353/src/tests/Interop/NativeLibrary/API/NativeLibraryTests.cs#L176-L177
https://github.com/dotnet/runtime/blob/fa780339a2ea43e80892556b925e0cfa5c9ac353/src/tests/Interop/DllImportSearchPaths/DllImportSearchPathsTest.cs#L30-L31

NativeAOT would need a variation of that though. They both use `Assembly.LoadFile` to load an assembly that is not next to the app and resolve relative to that assembly (corerun adds the app path to the native search directories, so it had to be in a different directory to actually test the `AssemblyDirectory` logic).

**Comment by AaronRobinsonMSFT** [comment]
I'll take a look at this.
