### ISSUE TITLE
Configuration source generator should use ArgumentNullException.ThrowIfNull if it's available

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#89879]
If the compilation has `ArgumentNullException.ThrowIfNull` available, it'd be nice if instead of emitting code like:
```C#
public static void BindCore(IConfiguration configuration, ref Tests.MyConfigSection obj, BinderOptions? binderOptions)
{
    if (obj is null)
    {
        throw new ArgumentNullException(nameof(obj));
    }
    ...
```
it emitted code like:
```C#
public static void BindCore(IConfiguration configuration, ref Tests.MyConfigSection obj, BinderOptions? binderOptions)
{
    ArgumentNullException.ThrowIfNull(obj);
    ...
```

**Comment by eiriktsarpalis** [comment]
If we are making the source generator use newer APIs, we should try to polyfill those in older TFMs rather than conditioning what source gets generated depending on TFM.

**Comment by layomia** [comment]
Self-assigning but happy to take a community contribution here. We should take polypill approach for the reasons stated here https://github.com/dotnet/runtime/pull/89823#discussion_r1283212769.

**Comment by eiriktsarpalis** [comment]
We could always emit a private helper method if a polyfill is not possible.

**Comment by eiriktsarpalis** [comment]
One possible solution might be to factor the logic to a helper method on the emitter, roughly
```C#
private void EmitNullValidation(string variableName)
{
    if (_isNet7OrGreater)
    {
        writer.WriteLine($"ArgumentNullException.ThrowIfNull({variableName});");
    }
    else
    {
         writer.WriteLine($$"""
              if ({{variableName}} is null)
              {
                  throw new ArgumentNullException(nameof({{variableName}}));
              } 
              """);
    }
}
```
So that this concern abstracted away from the method body emitters.

**Comment by stephentoub** [comment]
> We could always emit a private helper method if a polyfill is not possible.

Why would we do that? Either you're emitting code that duplicates a built-in API unnecessarily, or you're still having to branch in the generator and just doing so in a different place.

> One possible solution might be to factor the logic to a helper method on the emitter

If there are multiple places we'd need to invoke this, or if we'd prefer the factoring, sure, that's fine.  I care more here about the generated code than about the code doing the generating. (Though rather than _isNet70OrGreater, it might be based on querying for whether ArgumentNullException.ThrowIfNull exists. The C# compiler itself typically doesn't check TFM for things like this and instead just bases code gen off of whether the desired APIs exist.)
