### ISSUE TITLE
List<T> Insert() - optimize memory copying

### ISSUE THREAD

**Issue by glenn-slayden** [dotnet/runtime#89915]
https://github.com/dotnet/runtime/blob/22841c5b39f0b606afa90ad115f5ef2836d6cda6/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/List.cs#L740-L744

This can be improved for "true" insert cases (i.e., non-append) in any case where resizing is necessary. Currently, when inserting an item at position `ix` in a list of `N` items, and whenever resizing is required, an excess of `N - ix` elements will be unncessarily copied. This is because `Grow` sets the `Capacity` property, which copies all existing elements as part of resizing the array. This includes copying elements `ix ... N-1` into their old positions, which are incorrect considering the current insert operation. `Insert` then continutes by immediately shifting those tail elements again by one index position.

`Insert` should be optimized to include custom resizing code so that, if resizing is required, the tail elements are only copied once, into their final, correct positions.

This change is expected to be a worthwhile performance improvement, since each `List<T>` element can be an arbitrarily large value-type, and the current code involves unnecesasary/excess main memory copying/bus bandwidth as a multiple of `sizeof(T)`.

**Comment by eiriktsarpalis** [comment]
Would it be possible to share a prototype + microbenchmark numbers? We might consider a possible change if these look promising.

**Comment by EgorBo** [comment]
If I understand the proposal correctly, it's only for the case when we need to invoke `Grow` on the list, right? I guess it's supposed to be a rare event since the capacity grows by 2X and users are expected to provide initial capacity if Grow turns out to be a problem. Although, I guess, if the improvement is not super invasive it's nice to have?

**Comment by karakasa** [comment]
i wrote a prototype and did some micro-benchmarks. There is some improvement, especially for small lists.

|              Method |  Size |        Mean |    Error |   StdDev |
|-------------------- |------ |------------:|---------:|---------:|
|      **OriginalInsert** |   **100** |    **223.3 ns** |  **4.35 ns** |  **4.07 ns** |
|      ImprovedInsert |   100 |    200.9 ns |  0.51 ns |  0.43 ns |
| PrepareOriginalList |   100 |    147.9 ns |  0.61 ns |  0.51 ns |
| PrepareImprovedList |   100 |    160.4 ns |  0.56 ns |  0.44 ns |
|      **OriginalInsert** | **10000** | **16,681.8 ns** | **57.91 ns** | **48.36 ns** |
|      ImprovedInsert | 10000 | 16,548.0 ns | 47.18 ns | 41.83 ns |
| PrepareOriginalList | 10000 | 12,777.2 ns | 56.44 ns | 50.04 ns |
| PrepareImprovedList | 10000 | 12,758.9 ns | 32.71 ns | 30.60 ns |

````C#
private void GrowForInsert(int capacity, int indexToInsert)
{
    // follow the original way to calculate newCapacity

    Debug.Assert(_items.Length < capacity);
    int newCapacity = _items.Length == 0 ? DefaultCapacity : 2 * _items.Length;
    if ((uint)newCapacity > Array.MaxLength) newCapacity = Array.MaxLength;
    if (newCapacity < capacity) newCapacity = capacity;

    // reduce 1 copy

    T[] newItems = new T[newCapacity];
    Array.Copy(_items, newItems, indexToInsert);

    if (_size != indexToInsert)
        Array.Copy(_items, indexToInsert, newItems, indexToInsert + 1, _size - indexToInsert);

    _items = newItems;
}

// Inserts an element into this list at a given index. The size of the list
// is increased by one. If required, the capacity of the list is doubled
// before inserting the new element.
//
public void Insert(int index, T item)
{
    // Note that insertions at the end are legal.
    if ((uint)index > (uint)_size)
    {
        ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.index, ExceptionResource.ArgumentOutOfRange_ListInsert);
    }

    if (_size == _items.Length)
    {
        GrowForInsert(_size + 1, index);
    }
    else if (index < _size)
    {
        Array.Copy(_items, index, _items, index + 1, _size - index);
    }

    _items[index] = item;
    _size++;
    _version++;
}
````
<details>
  <summary>Benchmark code</summary>

````C#
using BenchmarkDotNet.Attributes;

namespace Benchmark.Benchmarks
{
    public class ListInsert
    {
        [Params(100, 10000)]
        public int Size { get; set; }
        private List<int> PrepareList1()
        {
            var list = new List<int>(Size);
            for (var i = 0; i < Size; i++) list.Add(Size);
            return list;
        }

        public AnotherList<int> PrepareList2()
        {
            var list = new AnotherList<int>(Size);
            for (var i = 0; i < Size; i++) list.Add(Size);
            return list;
        }

        [Benchmark]
        public int OriginalInsert()
        {
            var list = PrepareList1();
            list.Insert(42, 42);
            return list.Count;
        }

        [Benchmark]
        public int ImprovedInsert()
        {
            var list = PrepareList2();
            list.Insert(42, 42);
            return list.Count;
        }

        [Benchmark]
        public object PrepareOriginalList()
        {
            return PrepareList1();
        }
        [Benchmark]
        public object PrepareImprovedList()
        {
            return PrepareList2();
        }
    }
}
````
</details>

**Comment by karakasa** [comment]
another benchmark:

|         Method | Size |        Mean |    Error |   StdDev |
|--------------- |----- |------------:|---------:|---------:|
| **OriginalInsert** |    **8** |    **92.73 ns** | **0.247 ns** | **0.193 ns** |
| ImprovedInsert |    8 |    84.74 ns | 0.496 ns | 0.439 ns |
| **OriginalInsert** |   **32** |   **412.92 ns** | **1.065 ns** | **0.944 ns** |
| ImprovedInsert |   32 |   369.76 ns | 1.574 ns | 1.229 ns |
| **OriginalInsert** |  **128** | **1,856.27 ns** | **7.028 ns** | **6.230 ns** |
| ImprovedInsert |  128 | 1,713.39 ns | 4.589 ns | 4.068 ns |

````C#
using BenchmarkDotNet.Attributes;

namespace Benchmark.Benchmarks
{
    public class ListInsertOneByOne
    {
        [Params(8, 32, 128)]
        public int Size { get; set; }
        [Benchmark]
        public object OriginalInsert()
        {
            var size = Size;
            var list = new List<int>();
            for (var i = 0; i < size; i++)
            {
                list.Insert(list.Count / 2, i);
            }
            return list;
        }

        [Benchmark]
        public object ImprovedInsert()
        {
            var size = Size;
            var list = new AnotherList<int>();
            for (var i = 0; i < size; i++)
            {
                list.Insert(list.Count / 2, i);
            }
            return list;
        }
    }
}
````

**Comment by karakasa** [comment]
> @karakasa quickly skimming through the numbers there appears to be a regression as well?

What are you referring to? 🤔️ All improved ones are slightly faster than the original one. The ‘PrepareImprovedList’ is creating the list to manipulate (no insertion involved). Idk why it’s slower, though.

**Comment by glenn-slayden** [comment]
> If I understand the proposal correctly, it's only for the case when we need to invoke `Grow` on the list, right?

Yes.

> I guess it's supposed to be a rare event since the capacity grows by 2X and users are expected to provide initial capacity if `Grow` turns out to be a problem.

That's perhaps a good suggestion (or workaround) for users, but I'm not sure it's documented anywhere. Note however, that the user may have cases where the initial capacity cannot be estimated.

And regarding benchmark code, note that the lower the insert index, the worse the problem. The worst-case is when always inserting the first element `ix = 0`, because in this case the entire contents of the list will be moved twice whenever a resize is needed.

**Comment by glenn-slayden** [comment]
Can you tweak the benchmark code to always insert the first item `ix = 0`? This would give the best-case upper limit for the possible/putative performance improvement, to see if this change is worth considering at all.

**Comment by karakasa** [comment]
> Can you tweak the benchmark code to always insert the first item `ix = 0`

np. updated.

**Comment by karakasa** [comment]
updated with insertion at index 0.

I've corrected some issues with my local BenchmarkDotNet package and hopefully the latest results demonstrate performance gains better.

**Comment by glenn-slayden** [comment]
@karakasa Thank you!
