### ISSUE TITLE
NativeAOT on Graviton2 As `armv8.2-a` Fails to Execute

### ISSUE THREAD

**Issue by chrisoverzero** [dotnet/runtime#89937]
### Description

When NativeAOT-compiling an application for deployment onto AWS Lambda, specifying `IlcInstructionSet` with the known, documented supported instruction sets for Graviton2 processors fails to execute with the error message:

> The required instruction sets are not supported by the current CPU.

### Reproduction Steps

For a minimal reproduction, I'm using the code from [maxday's lambda-perf cold start–testing repository](https://github.com/maxday/lambda-perf/tree/main/s3-uploader/runtimes/dotnet7_aot_on_provided_al2/src), but targeting .NET 8's NativeAOT. The meaningful parts of that are:

```csharp
public class Function
{
    private static async Task Main()
    {
        await LambdaBootstrapBuilder.Create(FunctionHandler, new SourceGeneratorLambdaJsonSerializer<LambdaFunctionJsonSerializerContext>())
            .Build()
            .RunAsync();
    }

    public static StatusResponse FunctionHandler()
    {
        return new StatusResponse(statusCode: 200);
    }
}

public record StatusResponse(int statusCode);

[JsonSerializable(typeof(StatusResponse))]
public partial class LambdaFunctionJsonSerializerContext : JsonSerializerContext
{
}
```

…and for .csproj settings:

```xml
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifier>linux-arm64</RuntimeIdentifier>
    <PublishAot>true</PublishAot>
    <AssemblyName>bootstrap</AssemblyName>

    <IlcInstructionSet>armv8.2-a</IlcInstructionSet>
```

### Expected behavior

Because Amazon's Graviton2 processor is [documented](https://github.com/aws/aws-graviton-getting-started#building-for-graviton2-graviton3-and-graviton3e) as revision 8.2-a with support for features "fp16, rcpc, dotprod, crypto" and `ilc` doesn't support "fp16" or "crypto", I expected this:

```xml
<IlcInstructionSet>armv8.2-a,rcpc,dotprod</IlcInstructionSet>
```

…to compile and run. It compiled, but did not run. Figuring that maybe I was trying to add too much sauce, I tried:

```xml
<IlcInstructionSet>armv8.2-a</IlcInstructionSet>
```

…expecting this to compile and run. It compiled, but did not run.

### Actual behavior

Upon execution, this error message is received:

> The required instruction sets are not supported by the current CPU.

### Known Workarounds

Leave off `IlcInstructionSet`, implicitly targeting revision 8.0. This does compile (natch) and run.

### Configuration

I am cross-compiling for arm64 in the Docker image `mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-2.0-cross-arm64`:

```bash
~/.dotnet/dotnet publish -p:SysRoot=/crossrootfs/arm64 -p:LinkerFlavor=lld
```

`dotnet --version` is "8.0.100-rc.1.23402.12"

### Other information

I admit that I'm not certain this is a problem with the NativeAOT compiler, since I don't know how to look into a binary and say "Aha, here is the incorrect instruction."

**Comment by EgorBo** [comment]
I'll try on my M1, does it work if you don't specifcy any ISA at all? `armv8.2-a` should include neon (always enabled), lse (atomicts) and crc + rdma, the last two are unlikely to be hit?

**Comment by am11** [comment]
It is working on M1 with RC1 daily build. You can also specify `native` (since you are on new enough SDK).

`cpufeatures.{c,h}`, `cpuid.h` and `minipalconfig.h` from https://github.com/dotnet/runtime/tree/main/src/native/minipal participate it feature detection and they can be complied independently with this kind of a glue code:

```c
#define TARGET_UNIX
#define TARGET_ARM64

#include <stdio.h>
#include <cpufeatures.h>

int main(void) {
  int actualFeatures = minipal_getcpufeatures();
  printf("actual features: %d\n", actualFeatures);

  // TODO: unpack and print individual feature flags defined in cpufeatures.h

  return 0;
}
```

**Comment by chrisoverzero** [comment]
> You can also specify `native` […]

Even if I'm not building on ARM?

**Comment by am11** [comment]
Ah cross compilation 🙈 
Maybe try using this build container without cross: https://github.com/dotnet/runtime/issues/88971#issuecomment-1646793372.

**Comment by am11** [comment]
> I admit that I'm not certain this is a problem with the NativeAOT compiler, since I don't know how to look into a binary and say "Aha, here is the incorrect instruction."

@EgorBo, @MichalStrehovsky, what do you think about dumping all the supported instruction sets in this error path:

https://github.com/dotnet/runtime/blob/c6fdf522b3cd07606456c3149488430228b99000/src/coreclr/nativeaot/Runtime/startup.cpp#L186-L190

"Supporting instruction sets are: ..."

**Comment by chrisoverzero** [comment]
Setting cross-compilation aside, this also does not work on the Graviton 2 machine I allocated for testing:

```bash
sh-5.2$ ./src/bin/Release/net8.0/linux-arm64/publish/bootstrap 

The required instruction sets are not supported by the current CPU.
Aborted (core dumped)
```

What can I do to get you more information?

**Comment by MichalPetryka** [comment]
> all the supported instruction sets

Listing required ones too would make sense.

**Comment by chrisoverzero** [comment]
Trying the supported options one at a time, the ones which cause failures are:

- `rcpc`
- `dotprod`
- `rdma`

…but I think these are covered in the features line from my previous comment, as "lrcpc", "asimddp", and "asimdrdm". The names are different, but these look like they correspond to `HWCAP_LRCPC`, `HWCAP_ASIMDDP`, and `HWCAP_ASIMDRDM ` from [here](https://github.com/dotnet/runtime/blob/b74dae8dafca909e35c1af282374fdf6765bbba4/src/native/minipal/cpufeatures.c).

I'm _well_ over my head on this, so I don't know where those are `#define`d, or how they're used or detected or anything, really. I do not know what the next steps are.

**Comment by MichalPetryka** [comment]
Could you run some software that can list out supported CPU features on the machine (like for example https://github.com/google/cpu_features#quickstart)?

**Comment by chrisoverzero** [comment]
The output of `list_cpu_features`:

```json
{
  "arch": "aarch64",
  "implementer": 65,
  "variant": 3,
  "part": 3340,
  "revision": 1,
  "flags": ["aes", "asimd", "asimddp", "asimdhp", "asimdrdm", "atomics", "cpuid", "crc32", "dcpop", "evtstrm", "fp", "fphp", "lrcpc", "pmull", "sha1", "sha2", "ssbs"]
}
```

**Comment by MichalStrehovsky** [comment]
> ETA: Oh, I just remembered native. Trying that, now that I'm on Graviton2 natively, does work. 

If you're native on Graviton right now, try adding `<ItemGroup><IlcArg Include="--verbose" /></ItemGroup>` with `native`.

It will dump the list of instruction sets it expanded `native` into at compile time. We can crosscheck with what's expected.

**Comment by MichalStrehovsky** [comment]
> @EgorBo, @MichalStrehovsky, what do you think about dumping all the supported instruction sets in this error path:

Yes, I wanted to change this to `PalPrintFatalError("\nThe required instruction sets are not supported by the current CPU (Guru Meditation %d %d).\n", g_cpuFeatures, g_requiredCpuFeatures);`. We should do that.

**Comment by chrisoverzero** [comment]
> If you're native on Graviton right now, try adding `<ItemGroup><IlcArg Include="--verbose" /></ItemGroup>` with `native`.

```
ILC: The 'native' instruction set expanded to +aes,+crc,+lse,+neon,+sha1,+sha2
```

**Comment by MichalStrehovsky** [comment]
I did a quick check in #89988 and this is a product-build-time issue. I think this is a general product issue, not Native AOT specific. If this `#define` is not set, we would not generate a check for this at all.

```
/__w/1/s/src/native/minipal/cpufeatures.c:359:2: error: No HWCAP_LRCPC
#error No HWCAP_LRCPC
 ^
1 error generated.
```

**Comment by MichalStrehovsky** [comment]
> I'll try on my M1

It would likely not reproduce on M1 because Apple has its own way to detect these. This would be Linux specific.

**Comment by chrisoverzero** [comment]
Fantastic. I look forward to this landing in the daily build. Thanks to all for your efforts.

**Comment by chrisoverzero** [comment]
I confirm that with SDK version 8.0.100-rc.1.23407.1 and:

```xml
<PackageReference Include="Microsoft.DotNet.ILCompiler" Version="8.0.0-rc.1.23406.6" />
<PackageReference Include="runtime.linux-x64.Microsoft.DotNet.ILCompiler" Version="8.0.0-rc.1.23406.6" />
```

…the problem is resolved. I don't know what daily build will incorporate these versions into the SDK, but I can keep working with this.
