### ISSUE TITLE
Exception of type 'Interop+AndroidCrypto+SslException' was thrown in .NET MAUI 8.0 preview

### ISSUE THREAD

**Issue by PrashanthGR** [dotnet/runtime#89943]
### Description

Exception of type 'Interop+AndroidCrypto+SslException' was thrown when my android emulator try to connect my simulator device running in my computer.
wireshark throws Alert (Level: Fatal, Description: Protocol Version) after server hello done. I  have attached the screenshot.
I set TLSV 1.2 during sslsteam connection but I still see Tls 1.0 in wireshark in client hello.

Code:
 ```
 try
  {
      // Set SSL/TLS protocol version for Android
      TcpClient client1 = new TcpClient(ipaddress, 443);
      Console.WriteLine("Client connected.");

      ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

      SslStream abcd = new SslStream(client1.GetStream(), false, RemoteCertificateValidationCallback, LocalCertificateSelectionCallback, EncryptionPolicy.RequireEncryption);

      string name = abcd.TargetHostName;
      var sslclient = new SslClientAuthenticationOptions()
      {
          TargetHost = "Device",
          LocalCertificateSelectionCallback = LocalCertificateSelectionCallback,
          RemoteCertificateValidationCallback = RemoteCertificateValidationCallback,
          EnabledSslProtocols = SslProtocols.Tls12,
          AllowRenegotiation = false,
      };
      abcd.AuthenticateAsClient(sslclient);
      
      bool succ = abcd.IsMutuallyAuthenticated;

      abcd.Close();
      client.Close();

  }

  catch (AuthenticationException e)
  {
      Console.WriteLine("Exception: {0}", e.Message);
      if (e.InnerException != null)
      {
          Console.WriteLine("Inner exception: {0}", e.InnerException.Message);
      }
      Console.WriteLine("Authentication failed - closing the connection.");
      client.Close();
      connectSuccessfull = callbackmessage + "AuthenticationFailed " + e.Message;
      return connectSuccessfull;
  }
```

### Steps to Reproduce

```
 try
  {
      // Set SSL/TLS protocol version for Android
      TcpClient client1 = new TcpClient(ipaddress, 443);
      Console.WriteLine("Client connected.");

      ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

      SslStream abcd = new SslStream(client1.GetStream(), false, RemoteCertificateValidationCallback, LocalCertificateSelectionCallback, EncryptionPolicy.RequireEncryption);

      string name = abcd.TargetHostName;
      var sslclient = new SslClientAuthenticationOptions()
      {
          TargetHost = "Device",
          LocalCertificateSelectionCallback = LocalCertificateSelectionCallback,
          RemoteCertificateValidationCallback = RemoteCertificateValidationCallback,
          EnabledSslProtocols = SslProtocols.Tls12,
          AllowRenegotiation = false,
      };
      abcd.AuthenticateAsClient(sslclient);
      
      bool succ = abcd.IsMutuallyAuthenticated;

      abcd.Close();
      client.Close();

  }

  catch (AuthenticationException e)
  {
      Console.WriteLine("Exception: {0}", e.Message);
      if (e.InnerException != null)
      {
          Console.WriteLine("Inner exception: {0}", e.InnerException.Message);
      }
      Console.WriteLine("Authentication failed - closing the connection.");
      client.Close();
      connectSuccessfull = callbackmessage + "AuthenticationFailed " + e.Message;
      return connectSuccessfull;
  }
```
![wireshark](https://github.com/dotnet/maui/assets/41761328/57fb6c9e-aacd-46a9-97ea-ea80d214046e)
![clienthellotlsversion](https://github.com/dotnet/maui/assets/41761328/01e5521e-b279-441d-95b0-8f3b39c49173)
![visualstudoexception](https://github.com/dotnet/maui/assets/41761328/4d3e4043-b9cf-479e-a8f6-b427cb2c4821)

### Link to public reproduction project repository

eererr

### Version with bug

8.0.0-preview.3.8149

### Affected platforms

Android

### Affected platform versions

Android 12

### Did you find any workaround?

No I did not find any workaround yet. Need urgent help

**Comment by jonathanpeppers** [comment]
This looks like all BCL, so we should move to dotnet/runtime.

**Comment by simonrozsival** [comment]
@PrashanthGR thanks for opening the issue. I haven't been able to replicate the exception so far. This scenario might be something specific to your server or to your client or server certificates and it might be hard to replicate on my side. It would be great if you were able to create a repro project that makes requests to a public server (for example badssl.com).

I've looked into the TLS version discrepancy you're observing. It seems that this is the behavior of the underlying Java APIs and they're putting the TLS 1.0 (0x0301) into the TLS record header for compatibility reasons but the client TLS version in the Client Hello is later specified correctly as TLS 1.2 (0x0303). I've observed the exact same behavior in a Kotlin app. I'm not an expert in TLS so maybe somebody more knowledgeable can confirm that this shouldn't be the issue (cc @wfurt).

**Comment by wfurt** [comment]
yes the 1.0 version in frame header is common. What matters is version(s) in Hello and eventually what is negotiated. The observed behavior is typically caused by client not trusting the server's certificate or some problem with validation. Do you see your `RemoteCertificateValidationCallback` executed @PrashanthGR? What is state of the handed X509Chain?

**Comment by PrashanthGR** [comment]
@wfurt Tls version is used in both client and server is 1.2.
Yes I also think client is not validated the server certificate. One important info we are using custom CA (Root Ca) to sign or issue the client and server certificate.
RemoteCertificateValidationCallback is not executed.

Note: I used network_security_config to trust custom ca but no luck.

**Comment by PrashanthGR** [comment]
I even tried in .net xamarian. But same exception is thrown.

**Comment by simonrozsival** [comment]
@PrashanthGR If I understand the information from the Wireshark screenshot correctly, it's the client that closes the connection after it receives Server Hello. Could you share the whole Client Hello and Server Hello? It seems to me that the client decides to close the connection even before it starts evaluating the certificate, otherwise RemoteCertificateValidationCallback would be executed.

**Comment by simonrozsival** [comment]
We still need more information to identify the problem and we won't make that in time for .NET 8 so I'm moving the issue to .NET 9.
