### ISSUE TITLE
[wasm] AOT: `System.Text.Json.Tests` crashing inexplicably

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#89984]
[Rolling build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=362691&view=results), and [log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-2894ee6890b14cd1b5/normal-System.Text.Json.Tests/1/console.4894b88f.log?helixlogtype=result):

```
...
[21:39:57] info: [STRT] System.Text.Json.Serialization.Tests.CollectionTestsDynamic_SyncStream.ReadSimpleKeyValuePairPartialData
[21:39:57] info: [STRT] System.Text.Json.Serialization.Tests.CollectionTestsDynamic_SyncStream.WriteAsyncEnumerable_CancellationToken_IsPassedToAsyncEnumerator
[21:39:58] info: Process v8 exited with 1
                 
[21:39:58] info: Waiting to flush log messages with a timeout of 120 secs ..
[21:39:58] fail: Application has finished with exit code 1 but 0 was expected
```

Changes since last rolling build: b2e18f84...643087b2 .

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "Starting: *System.Text.Json.Tests.dll\\(?:.*\\)fail: Application has finished with exit code 1 but 0 was expected",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=362691
**Error message validated:** `Starting: *System.Text.Json.Tests.dll\(?:.*\)fail: Application has finished with exit code 1 but 0 was expected`
**Result validation: :x:** Known issue did not match with the provided build.
**Validation performed at:** 8/23/2023 5:53:25 AM UTC

**Comment by radical** [comment]
cc @vargaz

**Comment by vargaz** [comment]
Is this a reproducible, or its a random failure ?
