### ISSUE TITLE
Locking on `Console.Error`

### ISSUE THREAD

**Issue by RenderMichael** [dotnet/runtime#90027]
I'm working around a 3rd party library which unnecessarily logs to `Console.Error` but there seems to be an issue making it block on other threads while this workaround is executing. I have the following code:
```csharp
private static MyObj? _value;

private static MyObj GetValue()
{
    if (_value is null)
    {
        lock (Console.Error) // CA2002: Do not lock on object with weak identity
        {
            if (_value is null)
            {
                var errorStream = Console.Error;
                Console.SetError(StreamWriter.Null);
                MyObj val;
                try
                {
                    val = default; // do logic
                }
                finally
                {
                    Console.SetError(errorStream);
                }
                _value = val
            }
        }
    }
    return _value;
}
```

However, when I turned on some optional analyzers, `lock(Console.Error)` triggered `CA2002`.

Is there any way to block access to `Console.Error` while this code runs, so no other error logging is lost?

**Comment by adamsitnik** [comment]
Hi @RenderMichael 

`Console.SetError` already performs a lock of the private field that is used by `Console.Error`

https://github.com/dotnet/runtime/blob/c0967dcfc1fc280b57f92031956331c60b860fc5/src/libraries/System.Console/src/System/Console.cs#L715-L728

https://github.com/dotnet/runtime/blob/c0967dcfc1fc280b57f92031956331c60b860fc5/src/libraries/System.Console/src/System/Console.cs#L216-L234

So you need to call `Console.SetError(TextWriter.Null)`, without locking `Console.Error`.

> Is there any way to block access to Console.Error while this code runs, so no other error logging is lost?

`Console.Error` is a static singleton, there is no way of disabling it only for some parts of the application.

You should consider using the `ILogger` abstraction that gives you more control over logging and makes it possible to test the code: https://learn.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line
