### ISSUE TITLE
[mono][iOS] AOT fails for CommunityToolkit.WinUI.UI.dll

### ISSUE THREAD

**Issue by kazo0** [dotnet/runtime#90032]
### Description

AOT compilation fails when running for assembly CommunityToolkit.WinUI.UI.dll for net7-ios

Package is here: https://www.nuget.org/packages/Uno.CommunityToolkit.WinUI.UI/

Taking the CommunityToolkit.WinUI.UI.dll file from the Release bin/ folder and running:
`MONO_LOG_LEVEL=debug /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.AOT.osx-x64.Cross.ios-arm64/7.0.5/tools/mono-aot-cross --aot=mtriple=arm64-ios --debug CommunityToolkit.WinUI.UI.dll`

gives the following result:

```xml
Mono: Assembly Loader probing location: 'System.Private.CoreLib.dll'.
Mono: Image addref System.Private.CoreLib[0x7fbb080041f0] (default ALC) -> /Users/steve/src/UnoApp55/UnoApp55/UnoApp55.Mobile/bin/Release/net7.0-ios/ios-arm64/System.Private.CoreLib.dll[0x7fbaff81b600]: 2
Mono: Prepared to set up assembly 'System.Private.CoreLib' (/Users/steve/src/UnoApp55/UnoApp55/UnoApp55.Mobile/bin/Release/net7.0-ios/ios-arm64/System.Private.CoreLib.dll)
Mono: Assembly Loader loaded assembly from location: 'System.Private.CoreLib.dll'.
Mono: Loading assembly System.Private.CoreLib (0x7fbb080041f0) into domain CommunityToolkit.WinUI.UI.dll (0x7fbaff70e870) and ALC 0x7fbaff70e8c0
Mono: Assembly System.Private.CoreLib[0x7fbb080041f0] added to ALC '(null)'[0x7fbaff70e8c0], ref_count=1
Mono: Assembly Loader probing location: 'CommunityToolkit.WinUI.UI.dll'.
Mono: Image addref CommunityToolkit.WinUI.UI[0x7fbb08004a10] (default ALC) -> /Users/steve/src/UnoApp55/UnoApp55/UnoApp55.Mobile/bin/Release/net7.0-ios/ios-arm64/CommunityToolkit.WinUI.UI.dll[0x7fbb08813800]: 2
Mono: Prepared to set up assembly 'CommunityToolkit.WinUI.UI' (/Users/steve/src/UnoApp55/UnoApp55/UnoApp55.Mobile/bin/Release/net7.0-ios/ios-arm64/CommunityToolkit.WinUI.UI.dll)
Mono: Loading assembly CommunityToolkit.WinUI.UI (0x7fbb08004a10) into domain CommunityToolkit.WinUI.UI.dll (0x7fbaff70e870) and ALC 0x7fbaff70e8c0
Mono: Assembly CommunityToolkit.WinUI.UI[0x7fbb08004a10] added to ALC '(null)'[0x7fbaff70e8c0], ref_count=1
Mono: Assembly Loader loaded assembly from location: 'CommunityToolkit.WinUI.UI.dll'.
Mono: Assembly Loader probing location: 'CommunityToolkit.WinUI.UI.dll'.
Mono: Loading assembly CommunityToolkit.WinUI.UI (0x7fbb08004a10) into domain CommunityToolkit.WinUI.UI.dll (0x7fbaff70e870) and ALC 0x7fbaff70e8c0
Mono Ahead of Time compiler - compiling assembly /Users/steve/src/UnoApp55/UnoApp55/UnoApp55.Mobile/bin/Release/net7.0-ios/ios-arm64/CommunityToolkit.WinUI.UI.dll
AOTID A0673B6D-7423-6467-001D-DCB8C36FAD5F
Mono: Requesting loading reference 0 (of 20) of /Users/steve/src/UnoApp55/UnoApp55/UnoApp55.Mobile/bin/Release/net7.0-ios/ios-arm64/CommunityToolkit.WinUI.UI.dll
Mono: Loading reference 0 of /Users/steve/src/UnoApp55/UnoApp55/UnoApp55.Mobile/bin/Release/net7.0-ios/ios-arm64/CommunityToolkit.WinUI.UI.dll (default ALC), looking for System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Mono: Request to load System.Runtime in alc 0x7fbaff70e8c0
Mono: The following assembly referenced from /Users/steve/src/UnoApp55/UnoApp55/UnoApp55.Mobile/bin/Release/net7.0-ios/ios-arm64/CommunityToolkit.WinUI.UI.dll could not be loaded:
     Assembly:   System.Runtime    (assemblyref_index=0)
     Version:    7.0.0.0
     Public Key: b03f5f7f11d50a3a

Mono: Failed to load assembly CommunityToolkit.WinUI.UI[0x7fbb08004a10].
Failed to load method 0x6000001 from '/Users/steve/src/UnoApp55/UnoApp55/UnoApp55.Mobile/bin/Release/net7.0-ios/ios-arm64/CommunityToolkit.WinUI.UI.dll' due to Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies..
Run with MONO_LOG_LEVEL=debug for more information.
AOT of image CommunityToolkit.WinUI.UI.dll failed.
```

### Reproduction Steps

Pull down sample project: https://github.com/kazo0/UnoApp55

run
`cd UnoApp55/UnoApp55.Mobile/`
`dotnet publish -f net7.0-ios -c Release`

### Expected behavior

Build succeeds

### Actual behavior

`error : Failed to AOT compile CommunityToolkit.WinUI.UI.dll, the AOT compiler exited with code 134 [/Users/steve/src/UnoApp55/UnoApp55/UnoApp55.Mobile/UnoApp55.Mobile.csproj::TargetFramework=net7.0-ios]`

### Known Workarounds

Add the following to the project:

```xml
<ItemGroup Condition="'$(Configuration)'=='Release'">
	<TrimmableAssembly Include="CommunityToolkit.WinUI.UI" />
</ItemGroup>
```

**Comment by vargaz** [comment]
It fails because of:
Failed to load method 0x6000001 from '/Users/steve/src/UnoApp55/UnoApp55/UnoApp55.Mobile/bin/Release/net7.0-ios/ios-arm64/CommunityToolkit.WinUI.UI.dll' due to Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies..

which looks like some kind of problem with the build system.

**Comment by lambdageek** [comment]
it probably trimmed out System.Runtime

We need to try to repro this

**Comment by lambdageek** [comment]
Note to repro, you have to uninstall .NET 8 preview 6, if you're trying with preview 7 due to https://github.com/xamarin/xamarin-macios/issues/18667

**Comment by jbtdevgit** [comment]
This happens as well on Visual Studio Mac 17.6.3

**Comment by jbtdevgit** [comment]
> This happens as well on Visual Studio Mac 17.6.3 but with `CommunityToolkit.WinUi.dll` for `net6.0-maccatalyst`. Updated to .net7.0 still happening on `CommunityToolkit.WinUI` and `CommunityToolkit.WinUI.UI`

**Comment by NalonAu** [comment]
Hey @kazo0, in regard to the work around `TrimmableAssembly ` I have tried adding this to a fresh Uno project targeting .NET 7 (called UnoApp1)

I added it to both the UnoApp1.Mobile.csproj and UnoApp1.csproj like this:
`
<ItemGroup Condition="'$(Configuration)'=='Release'">
	<TrimmableAssembly Include="CommunityToolkit.WinUI.UI" />
</ItemGroup>
`

Yet it does not seem to fix the issue, am I doing this wrong? or is there somewhere specifically where I should be adding this?

**Comment by sitecompass** [comment]
> Hey @kazo0, in regard to the work around `TrimmableAssembly ` I have tried adding this to a fresh Uno project targeting .NET 7 (called UnoApp1)
> 
> I added it to both the UnoApp1.Mobile.csproj and UnoApp1.csproj like this: `<ItemGroup Condition="'$(Configuration)'=='Release'"> <TrimmableAssembly Include="CommunityToolkit.WinUI.UI" /> </ItemGroup>`
> 
> Yet it does not seem to fix the issue, am I doing this wrong? or is there somewhere specifically where I should be adding this?

![image](https://github.com/dotnet/runtime/assets/125837011/eb5c411e-6d6f-42c1-8c27-5ae3b1c3e6bb)
