### ISSUE TITLE
WebToolsException when using hot reload to apply change to Blazor WebAssembly app

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#90037]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/WebToolsException-when-using-hot-reload-/10421101)._

---
I got the following error when trying to hot reload a change to my Blazor WebAssemlby app:

```
20:46 51.50 BlazorApp14.Server (Web assembly): Sending updates to running application
20:46 51.56 BlazorApp14.Server (Web assembly): [Error] Applying updates failed: 
20:46 51.56 BlazorApp14.Server (Web assembly): [Error] Applying updates failed: The following error occurred when trying to apply your edits to the running application. 
20:46 51.57 Exception thrown for Apply Code Updates: 0x80131500 - The following error occurred when trying to apply your edits to the running application. The following error occurred when trying to apply your edits to the running application. 
20:46 51.57 Stack trace for WebToolsException:
   at Microsoft.WebTools.ProjectSystem.Components.HotReload.ProjectHotReloadSession.<ApplyUpdatesAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Debugger.Shared.Utilities.LoggerExtensions.<LogOnExceptionAsync>d__3.MoveNext()
20:46 51.57 An unexpected error has occurred, any pending updates have been discarded.
```

Repro steps:

- Create an ASP.NET Core hosted Blazor WebAssembly app using .NET 7
- Add Shared/MyLayout.razor to the Client project

```
@inherits LayoutComponentBase
<h1>MyLayout</h1>
<main>
    @Body
</main>
```
- Update Index.razor to include `@layout MyLayout` just below the `@page` directive
- Run the app without debugging
- Remove the `@layout MyLayout` directive from Index.Razor
- Hot reload the change to the running app

---
#### Feedback Bot on 7/23/2023, 05:58 PM: 

(private comment, text removed)
#### Feedback Bot on 7/24/2023, 01:36 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
@lambdageek, @lewing  this seems to be a hot-reload related issue in WebAssembly runtime.

**Comment by lambdageek** [comment]
Interesting.  It looks like the EnC delta has a modification to a TypeDef row.  I guess there are two possibilities:
* (unlikely) there's some legitimate reason to modify a TypeDef row for a supported edit (maybe *TypeAttributes* ?)
* (more likely) in `apply_enclog_pass1` for the TypeDef case we have logic for "add field" and "add method" that validates that the edit is what we expected, but not for "add property" and "add event" - they just fall through to an error.  Probably they should be allowed.

Assuming it's the latter - we should just allow "add property" and "add event".  The bigger question is why our tests didn't catch this.  We do have some "add stuff to existing classes" testcases.  But for some reason they don't hit the same assertions?

**Comment by isadorasophia** [comment]
Not exactly related to this issue specifically, but could we find a way to propagate the javascript stack to the managed exception? The user only sees the following on the output window:

```
20:46 51.50 BlazorApp14.Server (Web assembly): Sending updates to running application
20:46 51.56 BlazorApp14.Server (Web assembly): [Error] Applying updates failed: 
20:46 51.56 BlazorApp14.Server (Web assembly): [Error] Applying updates failed: The following error occurred when trying to apply your edits to the running application. 
20:46 51.57 Exception thrown for Apply Code Updates: 0x80131500 - The following error occurred when trying to apply your edits to the running application. The following error occurred when trying to apply your edits to the running application. 
20:46 51.57 Stack trace for WebToolsException:
   at Microsoft.WebTools.ProjectSystem.Components.HotReload.ProjectHotReloadSession.<ApplyUpdatesAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Debugger.Shared.Utilities.LoggerExtensions.<LogOnExceptionAsync>d__3.MoveNext()
20:46 51.57 An unexpected error has occurred, any pending updates have been discarded.
```

Which takes a longer time to triage/route/investigate these kind of issues

**Comment by lambdageek** [comment]
So the source change (looking at the generated .cs files for the razor delta) here is the deletion of a custom attribute from a class definition.  Interestingly we had a test in the runtime for deleting a custom attribute from a method.  And that works.  But if I change the test to delete an attribute from a class, it crashes the same way.  We're definitely not handling something propertly
