### ISSUE TITLE
Error: The type initializer for 'Microsoft.DotNet.XHarness.TestRunners.Common.ApplicationOptions' threw an exception.

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#90040]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=363565
Build error leg or test failing: normal-System.Runtime.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/90023

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "The type initializer for 'Microsoft.DotNet.XHarness.TestRunners.Common.ApplicationOptions' threw an exception.",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=363565
**Error message validated:** `The type initializer for 'Microsoft.DotNet.XHarness.TestRunners.Common.ApplicationOptions' threw an exception.`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 8/4/2023 5:58:32 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by akoeplinger** [comment]
No more hits, closing.
