### ISSUE TITLE
Dynamically adding nested properties when using an ExpandoObject instance

### ISSUE THREAD

**Issue by fterrani** [dotnet/runtime#90064]
Greetings,

Currently, the ExpandoObject class supports dynamically adding properties like so:

```csharp
dynamic obj = new ExpandoObject();
obj.first = 1;
```
However if we then do the following:

```csharp
obj.my.nested.property = 2;
```
The following exception is thrown:

```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: ''System.Dynamic.ExpandoObject' does not contain a definition for 'my''
```

For now, the best solution there seem to be is this:

```csharp
obj.my = new ExpandoObject();
obj.my.nested = new ExpandoObject();
obj.my.nested.property = 2;
```

Which I find tedious. It would be great that if a property doesn't exist yet is read to access another non-existing property, this would automatically create a new `ExpandoObject` instance. I feel this might require very precise coding for edge cases and that it might not be possible for technical reasons, but I think it would be worth it if there is a way to do it.

**Comment by huoyaoyuan** [comment]
When comparing to other dynamic languages like JavaScript, they don't allow setting `obj.a.b` without first setting `obj.a` either.

The dynamic runtime is in maintenance mode. It's unlikely to receive new feature.

**Comment by AaronRobinsonMSFT** [comment]
Thanks for the suggestion. 

We can place this in .NET 9. If there is no/little interest/need at that point we will close the issue.

**Comment by cston** [comment]
@fterrani, thanks for the suggestion.

Unfortunately, the System.Linq.Expressions library is effectively archived, and we are only taking changes that address significant bugs or regressions, or changes needed to continue shipping - see [README.md](https://github.com/dotnet/runtime/tree/main/src/libraries/System.Linq.Expressions/README.md).

**Comment by fterrani** [comment]
@cston no problem, thank you for telling me :)

Have a nice day.
