### ISSUE TITLE
TimeProvider GetLocalNow enhancement

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/runtime#90060]
Currently, we're creating a new DateTimeOffset even when the local time zone is the same as UTC

https://github.com/dotnet/runtime/blob/bb0be1387e1536af74a1c436680d6fb447ac6d92/src/libraries/Common/src/System/TimeProvider.cs#L47-L68

Could we use the utc now when the local time zone is UTC, possible update:

``` diff
TimeSpan offset = zoneInfo.GetUtcOffset(utcDateTime);
+ if (offset.Ticks is 0) return utcDateTime;

```

**Comment by tarekgh** [comment]
@WeihanLi did you measure it and see noticeable perf improvement?

**Comment by WeihanLi** [comment]
@tarekgh  here's the test on my local device
![image](https://github.com/dotnet/runtime/assets/7604648/0649e29e-bdd3-436b-a56c-e188aac7346b)

test code:
``` c#
public class TimeProviderLocalTimeTest
{
    private static readonly long s_minDateTicks = DateTime.MinValue.Ticks;
    private static readonly long s_maxDateTicks = DateTime.MaxValue.Ticks;
    
    [Benchmark(Baseline = true)]
    public DateTimeOffset GetLocalNow() 
    {
        var utcDateTime = DateTimeOffset.UtcNow; 
        var zoneInfo = TimeZoneInfo.Utc;
        var offset = zoneInfo.GetUtcOffset(utcDateTime); 
  
        var localTicks = utcDateTime.Ticks + offset.Ticks; 
        if ((ulong)localTicks > (ulong)s_maxDateTicks) 
        { 
            localTicks = localTicks < s_minDateTicks ? s_minDateTicks : s_maxDateTicks; 
        } 
  
        return new DateTimeOffset(localTicks, offset); 
    }
    
    [Benchmark]
    public DateTimeOffset GetLocalNow_Update() 
    { 
        var utcDateTime = DateTimeOffset.UtcNow; 
        var zoneInfo = TimeZoneInfo.Utc;
        var offset = zoneInfo.GetUtcOffset(utcDateTime);
        if (offset.Ticks is 0) return utcDateTime;
  
        var localTicks = utcDateTime.Ticks + offset.Ticks; 
        if ((ulong)localTicks > (ulong)s_maxDateTicks) 
        { 
            localTicks = localTicks < s_minDateTicks ? s_minDateTicks : s_maxDateTicks; 
        }
        return new DateTimeOffset(localTicks, offset); 
    }
}
```

**Comment by tarekgh** [comment]
Thanks @WeihanLi, could you please add the measurement when using non-UTC zone too? to compare the perf cost for the added condition too.

**Comment by WeihanLi** [comment]
@tarekgh test result for the non-UTC test
![image](https://github.com/dotnet/runtime/assets/7604648/48600df8-1af1-44c8-8d2b-0b1faf1665f2)

 I'm using the `TimeZoneInfo.Local`, and my local time zone is UTC+8

``` c#
[MemoryDiagnoser]
public class TimeProviderLocalTimeNonUtcTest
{
    private static readonly long s_minDateTicks = DateTime.MinValue.Ticks;
    private static readonly long s_maxDateTicks = DateTime.MaxValue.Ticks;
    
    [Benchmark(Baseline = true)]
    public DateTimeOffset GetLocalNow() 
    {
        var utcDateTime = DateTimeOffset.UtcNow; 
        var zoneInfo = TimeZoneInfo.Local;
        var offset = zoneInfo.GetUtcOffset(utcDateTime); 
  
        var localTicks = utcDateTime.Ticks + offset.Ticks; 
        if ((ulong)localTicks > (ulong)s_maxDateTicks) 
        { 
            localTicks = localTicks < s_minDateTicks ? s_minDateTicks : s_maxDateTicks; 
        } 
  
        return new DateTimeOffset(localTicks, offset); 
    }
    
    [Benchmark]
    public DateTimeOffset GetLocalNow_Update() 
    { 
        var utcDateTime = DateTimeOffset.UtcNow; 
        var zoneInfo = TimeZoneInfo.Local;
        var offset = zoneInfo.GetUtcOffset(utcDateTime);
        if (offset.Ticks is 0) return utcDateTime;
  
        var localTicks = utcDateTime.Ticks + offset.Ticks; 
        if ((ulong)localTicks > (ulong)s_maxDateTicks) 
        { 
            localTicks = localTicks < s_minDateTicks ? s_minDateTicks : s_maxDateTicks; 
        }
        return new DateTimeOffset(localTicks, offset); 
    }
}
```

**Comment by TonyValenti** [comment]
If I read these stats correctly, it seems like the rare but least-expected, best-case scenario got slightly better but the most expected, normal-case scenario got slightly worse. 

Is that correct?

**Comment by WeihanLi** [comment]
> If I read these stats correctly, it seems like the rare but least-expected, best-case scenario got slightly better but the most expected, normal-case scenario got slightly worse.

From the test result `Ratio`, we would get 17% performance gains for the UTC time zone, for non-UTC timezones, we could still get almost the same performance as before, from the `Mean` result, `0.27ns` downgrade for non-UTC time zones, could it be accepted?

In our cases, our app services are deployed with docker containers and the default timezone, which would be UTC timezone, we would try to use the Utc time while local time may also be used by mistake.
