### ISSUE TITLE
MayBeNullWhen(false) Not Applied

### ISSUE THREAD

**Issue by bitm0de** [dotnet/runtime#90062]
https://github.com/dotnet/runtime/blob/bb0be1387e1536af74a1c436680d6fb447ac6d92/src/libraries/System.Text.Json/src/System/Text/Json/Nodes/JsonObject.cs#L111

Should the `TryGetPropertyValue` not have this attribute applied to the out parameter since it's forwarded from something that does? This messes up nullability analyzers for me.

**Comment by gregsdennis** [comment]
I think I'd expect `[MayBeNullWhen(true)]`.  When the method returns false, null is expected.  But if the method returns true, the output may still be null, signifying the property is present with a JSON `null`.
