### ISSUE TITLE
Non-English output from `build.cmd` are displayed as gibberish

### ISSUE THREAD

**Issue by karakasa** [dotnet/runtime#90069]
### Description

Non-English output from `build.cmd` are displayed as gibberish under East Asian versions of Windows 10 22H2. The building procedure itself seems able to run without issues.

I did a quick search and cannot find similar issues. Is this expected?

### Reproduction Steps

* Clone a fresh repo of dotnet/runtime.
* Run `build.cmd` in an East Asian language version of Windows 10.

### Expected behavior

Messages are correctly displayed.

### Actual behavior

Non-English characters in messages are displayed as gibberish, except a few lines such as "Determining projects to restore", as shown in the picture:

![image](https://github.com/dotnet/runtime/assets/12855165/cd3169b4-54db-4986-b999-25c418bd4ec8)

### Configuration

* Latest dotnet/runtime commit
* OS: Windows 10 22H2 (19045.2546) x64

**Comment by huoyaoyuan** [comment]
The issue was present from late preview of .NET 7, possibly caused by breaking encoding change at SDK side.

**Comment by agocke** [comment]
Unfortunately we don't have the resources to maintain support for building the product in multiple languages. We may take external contributions if the community can maintain them, but cannot commit to maintaining the scenario ourselves.

**Comment by MichalPetryka** [comment]
> Unfortunately we don't have the resources to maintain support for building the product in multiple languages. We may take external contributions if the community can maintain them, but cannot commit to maintaining the scenario ourselves.

Could the script override the SDK output language to english somehow then?

**Comment by huoyaoyuan** [comment]
> Unfortunately we don't have the resources to maintain support for building the product in multiple languages.

I also noted the same problem in shipped SDK, not only the runtime repo. I will collect information once I meet it again.
