### ISSUE TITLE
execvp:ing freezes debugger

### ISSUE THREAD

**Issue by Rosentti** [dotnet/runtime#90076]
### Description

Running execvp while debugging causes the debugger to lock up, not restarting debugging once the process has restarted.
And it also isn't possible to programmatically detach and then reattach the debugger (Debugger.Launch doesn't exist on Linux)
![image](https://github.com/dotnet/runtime/assets/32398752/8f467c26-82f7-444a-b7df-f4900add613b)

### Reproduction Steps

1. Run this program with VSCode's C# debugger (Visual Studio not viable, not available on Linux)
```c#
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

namespace ClientConsole;

public static class Program
{
    public static void Main(string[] args)
    {
        ReExec();
    }

    [SupportedOSPlatform("linux")]
    private static void ReExec()
    {
        if (Environment.GetEnvironmentVariable("CLIENT_HAS_RESTARTED") == "1") {
            Console.WriteLine("Re-executed successfully");
            Debugger.Break();
            return;
        }

        Console.WriteLine("Re-executing");

        [DllImport("libc")]
        static extern int execvp([MarshalAs(UnmanagedType.LPUTF8Str)] string file, [MarshalAs(UnmanagedType.LPArray)] string[] args);

        // C#'s SetEnvironmentVariable doesn't carry to the restarted process
        [DllImport("libc")]
        static extern int setenv([MarshalAs(UnmanagedType.LPUTF8Str)] string name, [MarshalAs(UnmanagedType.LPUTF8Str)] string value, int overwrite);

        setenv("CLIENT_HAS_RESTARTED", "1", 1);
        var fullArgs = Environment.GetCommandLineArgs();

        string executable = Directory.ResolveLinkTarget("/proc/self/exe", false)!.FullName;
        Console.WriteLine("executable: " + executable);
        if (!executable.EndsWith("dotnet")) {
            fullArgs[0] = executable;
        } else {
            fullArgs = fullArgs.Prepend(executable).Append(null).ToArray();
        }

        // Program execution ends here, if execvp returns, it means re-execution failed
        int ret = execvp(executable, fullArgs);
        throw new Exception($"Execvp failed: {ret}");
    }
}
```
2. Debugger doesn't break for "Re-executed successfully", or output new output from the process

### Expected behavior

The process restarts (same PID) and the debugger re-attaches itself.

### Actual behavior

The debugger has no clue what is happening.

### Regression?

Unknown

### Known Workarounds

Don't use execvp, but that stops us from setting LD_PRELOAD while keeping the initial terminal busy

### Configuration

.NET 7
Arch Linux
x64

**Comment by jkotas** [comment]
`!executable.EndsWith("dotnet")` path does not append the trailing null to `fullArgs`. Is the debugger lock-up caused by the process crashing due to missing null terminator by any chance?

> Known Workarounds

You can use restart the process using System.Diagnostics.Process and modify the environment for the restarted process using `ProcessStartInfo.Environment` property. It would save you from dealing with P/Invoke details.

> string executable = Directory.ResolveLinkTarget("/proc/self/exe", false)!.FullName;

Nit: You can just call `Environment.ProcessPath` instead of this.

**Comment by Rosentti** [comment]
I've refactored it to use the Process class and `Process.GetCurrentProcess().Kill(false);`.
Unfortunately, now it just says `The program '[303402] ClientConsole.dll' has exited with code 0 (0x0).`, and doesn't debug the subprocess. Can I force the debugger to switch to the other process from code?

**Comment by tommcdon** [comment]
Thanks for reporting this issue @Rosentti.  The Visual Studio Code debugger and .NET Debugger Libraries were not designed to support the Linux `execvp` API, or to support child process debugging.  I suggest filing a feature request issue on https://github.com/dotnet/vscode-csharp/issues, to allow others to vote on the feature.
