### ISSUE TITLE
Performance Regression with .NET 8 Preview 6

### ISSUE THREAD

**Issue by akade** [dotnet/runtime#90101]
### Description

I recently was playing around with FrozenCollections for my little sideproject [IndexedSet](https://github.com/akade/Akade.IndexedSet) to speed up the dictionary lookups that frequently occur. While I succeeded to do that, I noticed that some areas are significantly slower with .NET 8 Preview 6. While most of the benchmarks are, as expected, either within margin of errors or faster,  the trie-based lookups are slower:

Context: IndexedSet provides an easy way to create in-memory indices on a collection without having to maintain multiple collections / dictionaries. The Prefix / Fulltext Indices are associative tries: Each node holds a dictionary (`System.Collection.Generics.Dictionary<char, TrieNode>`, default comparer) associating the next char with its child nodes as well as elements. Lookup then simply recursivly traverses the trie based on each character within the given key.

### Benchmark results:
```
BenchmarkDotNet v0.13.7, Windows 11 (10.0.22621.2070/22H2/2022Update/SunValley2)
AMD Ryzen 9 5900X, 1 CPU, 24 logical and 12 physical cores
.NET SDK 8.0.100-preview.6.23330.14
  [Host]   : .NET 7.0.9 (7.0.923.32018), X64 RyuJIT AVX2
  .NET 6.0 : .NET 6.0.20 (6.0.2023.32017), X64 RyuJIT AVX2
  .NET 7.0 : .NET 7.0.9 (7.0.923.32018), X64 RyuJIT AVX2
  .NET 8.0 : .NET 8.0.0 (8.0.23.32907), X64 RyuJIT AVX2
```

|                     Method |      Job |  Runtime |        Mean |     Error |    StdDev | Ratio |   Gen0 | Allocated | Alloc Ratio |
|--------------------------- |--------- |--------- |------------:|----------:|----------:|------:|-------:|----------:|------------:|
|            StartsWith_Linq | .NET 6.0 | .NET 6.0 |  3,862.3 ns |  50.22 ns |  46.97 ns |  1.00 | 0.0076 |     128 B |        1.00 |
|      StartsWith_IndexedSet | .NET 6.0 | .NET 6.0 |    612.4 ns |   1.03 ns |   0.86 ns |  0.16 | 0.0086 |     144 B |        1.12 |
|                            |          |          |             |           |           |       |        |           |             |
|            StartsWith_Linq | .NET 7.0 | .NET 7.0 |  2,675.9 ns |  35.73 ns |  31.67 ns |  1.00 | 0.0076 |     128 B |        1.00 |
|      StartsWith_IndexedSet | .NET 7.0 | .NET 7.0 |    ***596.0 ns*** |   2.65 ns |   2.35 ns |  0.22 | 0.0086 |     144 B |        1.12 |
|                            |          |          |             |           |           |       |        |           |             |
|            StartsWith_Linq | .NET 8.0 | .NET 8.0 |  2,239.4 ns |  21.98 ns |  18.36 ns |  1.00 | 0.0076 |     128 B |        1.00 |
|      StartsWith_IndexedSet | .NET 8.0 | .NET 8.0 |    ***770.4 ns*** |   2.23 ns |   1.98 ns |  0.34 | 0.0086 |     144 B |        1.12 |

I created a branch for this, [net8-preview6-perf](https://github.com/akade/Akade.IndexedSet/tree/net8-preview6-perf). Running the benchmarks is simple: Clone the repo, switch to the branch, build and run the benchmarks *PrefixIndexBenchmarks* (and FullTextIndexBenchmarks).  For the further analysis, I started with looking into PrefixIndexBenchmarks.

### Analysis

Profiling shows different top functions:
With **8.0**:
![image](https://github.com/dotnet/runtime/assets/16369295/3d763c61-c445-4c20-b702-24d5a44e6ff4)

With **7.0**:
![image](https://github.com/dotnet/runtime/assets/16369295/570d747d-c27c-4db5-bebf-bfe7b65ef01e)

However, the profiler shows me, that most time is spent on the null check (which I doubt):
![image](https://github.com/dotnet/runtime/assets/16369295/564944e8-5f3b-48d9-894d-1cf8e579dbb4)

Looking at the jitted code using (DissassemblerDiagnoser), it seems that .NET 7 had a whole bunch of methods inlined, in fact, all the methods from entire Trie seem to be inlined if I read the asm correctly. Hoever, using the InlineDiagnoser, I could, even though there are differences, not confirm my suspicion. 

So here I am now, not sure how to continue and a bit confused why `GetAll` and `AddRecursivlyToResult` show as failed inlining in both .NET 7 & 8 but I can only find the methods in the Assembly code within .NET 8... I'd be happy to learn why that is the case.

Is this regression expected?
- If yes => what is the reason & what do you recommend as mitigation? Trying to specify the behavior (i.e. MethodImpl)? (I have some other low hanging fruits, but could well be that they are eaten up by the regression). 
- If not, I'm happy to do further investigation, but would most likely need some help with that.

---
And because it usually is done too rarely: Keep up the good work, I really enjoy .NET!

**Comment by eiriktsarpalis** [comment]
You mentioned using FrozenCollections at the start but I couldn't those being used at all in the repo you shared. Guessing they're not related to the regression per se?

FWIW I ran the benchmark in question locally using `8.0.100-preview.7.23376.3` and this is what I got:

|                Method |      Job |  Runtime |     Mean |    Error |   StdDev |   Gen0 | Code Size | Allocated |
|---------------------- |--------- |--------- |---------:|---------:|---------:|-------:|----------:|----------:|
| StartsWith_IndexedSet | .NET 7.0 | .NET 7.0 | 750.9 ns | 14.76 ns | 17.00 ns | 0.0114 |   3,885 B |     144 B |
| StartsWith_IndexedSet | .NET 8.0 | .NET 8.0 | 736.1 ns | 14.30 ns | 21.41 ns | 0.0114 |   3,671 B |     144 B |

Does using Preview 7 improve performance for you?

**Comment by akade** [comment]
Yep, frozen collection do not play a role here. Sorry for the confusion, they were just one of the reasons I played with .NET 8 yesterday...

Here are my results with the latest bits:

```ini
BenchmarkDotNet v0.13.7, Windows 11 (10.0.22621.2070/22H2/2022Update/SunValley2)
AMD Ryzen 9 5900X, 1 CPU, 24 logical and 12 physical cores
.NET SDK 8.0.100-preview.7.23376.3
  [Host]   : .NET 7.0.9 (7.0.923.32018), X64 RyuJIT AVX2
  .NET 7.0 : .NET 7.0.9 (7.0.923.32018), X64 RyuJIT AVX2
  .NET 8.0 : .NET 8.0.0 (8.0.23.37506), X64 RyuJIT AVX2
```

|                Method |      Job |  Runtime |     Mean |   Error |  StdDev | Code Size |   Gen0 | Allocated |
|---------------------- |--------- |--------- |---------:|--------:|--------:|----------:|-------:|----------:|
| StartsWith_IndexedSet | .NET 7.0 | .NET 7.0 | 587.4 ns | 1.24 ns | 1.16 ns |   3,885 B | 0.0086 |     144 B |
| StartsWith_IndexedSet | .NET 8.0 | .NET 8.0 | 622.4 ns | 0.99 ns | 0.93 ns |   3,671 B | 0.0086 |     144 B |

Much closer. I'd still say it's strange but I think it's okayish like that. Any idea why it's different on your machine than on mine? As the code size is the same, I'd think the JIT produced the same output. So CPU specifics?

**Comment by JulieLeeMSFT** [comment]
@AndyAyersMS, PTAL. CC @dotnet/jit-contrib.

**Comment by AndyAyersMS** [comment]
On my main dev machine I see 8 preview 7 as faster... 

BenchmarkDotNet v0.13.7, Windows 11 (10.0.22621.2134/22H2/2022Update/SunValley2)
Intel Core i7-8700 CPU 3.20GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
.NET SDK 8.0.100-preview.7.23376.3
  [Host]   : .NET 7.0.10 (7.0.1023.36312), X64 RyuJIT AVX2
  .NET 7.0 : .NET 7.0.10 (7.0.1023.36312), X64 RyuJIT AVX2
  .NET 8.0 : .NET 8.0.0 (8.0.23.37506), X64 RyuJIT AVX2


|                Method |      Job |  Runtime |     Mean |    Error |   StdDev |   Gen0 | Code Size | Allocated |
|---------------------- |--------- |--------- |---------:|---------:|---------:|-------:|----------:|----------:|
| StartsWith_IndexedSet | .NET 7.0 | .NET 7.0 | 858.9 ns | 16.55 ns | 15.48 ns | 0.0229 |   3,885 B |     144 B |
| StartsWith_IndexedSet | .NET 8.0 | .NET 8.0 | 806.8 ns | 13.41 ns | 11.89 ns | 0.0229 |   3,658 B |     144 B |

(note this is an intel box, not an AMD)

Let me drill in a bit, and perhaps try this on some of my other machines.

**Comment by AndyAyersMS** [comment]
The times for this benchmark seem to be quite variable. Running it again on the same machine as above, and adding in a run of current main (~ RC1)

BenchmarkDotNet v0.13.7, Windows 11 (10.0.22621.2134/22H2/2022Update/SunValley2)
Intel Core i7-8700 CPU 3.20GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
.NET SDK 8.0.100-preview.7.23376.3
  [Host]     : .NET 7.0.10 (7.0.1023.36312), X64 RyuJIT AVX2
  Job-CJFCPD : .NET 8.0.0 (42.42.42.42424), X64 RyuJIT AVX2
  .NET 7.0   : .NET 7.0.10 (7.0.1023.36312), X64 RyuJIT AVX2
  .NET 8.0   : .NET 8.0.0 (8.0.23.37506), X64 RyuJIT AVX2


|                Method |        Job |  Runtime |     Mean |    Error |   StdDev |   Gen0 | Allocated |
|---------------------- |----------- |--------- |---------:|---------:|---------:|-------:|----------:|
| StartsWith_IndexedSet |  main | ~RC1 | 780.2 ns | 10.87 ns | 10.17 ns | 0.0229 |     144 B |
| StartsWith_IndexedSet |   .NET 7.0 | .NET 7.0 | 782.6 ns |  3.43 ns |  2.68 ns | 0.0229 |     144 B |
| StartsWith_IndexedSet |   .NET 8.0 | .NET 8.0 | 775.9 ns |  3.32 ns |  2.77 ns | 0.0229 |     144 B |

**Comment by AndyAyersMS** [comment]
Results from various machines on 7.0 vs 8p7:

### Intel

BenchmarkDotNet v0.13.7, Windows 11 (10.0.22621.2134/22H2/2022Update/SunValley2) (Hyper-V)
Intel Xeon Platinum 8370C CPU 2.80GHz, 1 CPU, 16 logical and 8 physical cores
.NET SDK 8.0.100-preview.7.23376.3
  [Host]   : .NET 7.0.5 (7.0.523.17405), X64 RyuJIT AVX2
  .NET 7.0 : .NET 7.0.5 (7.0.523.17405), X64 RyuJIT AVX2
  .NET 8.0 : .NET 8.0.0 (8.0.23.37506), X64 RyuJIT AVX2


|                Method |      Job |  Runtime |     Mean |   Error |  StdDev |   Gen0 | Code Size | Allocated |
|---------------------- |--------- |--------- |---------:|--------:|--------:|-------:|----------:|----------:|
| StartsWith_IndexedSet | .NET 7.0 | .NET 7.0 | 914.1 ns | 2.56 ns | 2.27 ns | 0.0057 |   3,885 B |     144 B |
| StartsWith_IndexedSet | .NET 8.0 | .NET 8.0 | 894.7 ns | 4.39 ns | 3.89 ns | 0.0057 |   3,658 B |     144 B |

BenchmarkDotNet v0.13.7, Ubuntu 20.04.6 LTS (Focal Fossa)
Intel Core i7-2720QM CPU 2.20GHz (Sandy Bridge), 1 CPU, 8 logical and 4 physical cores
.NET SDK 8.0.100-preview.7.23376.3
  [Host]     : .NET 7.0.9 (7.0.923.32018), X64 RyuJIT AVX
  Job-UTPSGJ : .NET 7.0.9 (7.0.923.32018), X64 RyuJIT AVX
  Job-XIPSKP : .NET 8.0.0 (8.0.23.37506), X64 RyuJIT AVX


|                Method |  Runtime |     Mean |     Error |    StdDev |   Median | Ratio | RatioSD |   Gen0 | Allocated | Alloc Ratio |
|---------------------- |--------- |---------:|----------:|----------:|---------:|------:|--------:|-------:|----------:|------------:|
| StartsWith_IndexedSet | .NET 7.0 | 1.652 us | 0.0438 us | 0.1291 us | 1.561 us |  1.00 |    0.00 | 0.0458 |     144 B |        1.00 |
| StartsWith_IndexedSet | .NET 8.0 | 1.559 us | 0.0011 us | 0.0010 us | 1.559 us |  0.88 |    0.05 | 0.0458 |     144 B |        1.00 |

### AMD Zen 3

This one is somewhat similar to your machine above.

BenchmarkDotNet v0.13.7, Windows 11 (10.0.22621.2134/22H2/2022Update/SunValley2)
AMD Ryzen 7 5800H with Radeon Graphics, 1 CPU, 16 logical and 8 physical cores
.NET SDK 8.0.100-preview.7.23376.3
  [Host]   : .NET 7.0.9 (7.0.923.32018), X64 RyuJIT AVX2
  .NET 7.0 : .NET 7.0.9 (7.0.923.32018), X64 RyuJIT AVX2
  .NET 8.0 : .NET 8.0.0 (8.0.23.37506), X64 RyuJIT AVX2


|                Method |      Job |  Runtime |     Mean |   Error |  StdDev |   Gen0 | Code Size | Allocated |
|---------------------- |--------- |--------- |---------:|--------:|--------:|-------:|----------:|----------:|
| StartsWith_IndexedSet | .NET 7.0 | .NET 7.0 | 691.6 ns | 5.78 ns | 5.41 ns | 0.0172 |   3,885 B |     144 B |
| StartsWith_IndexedSet | .NET 8.0 | .NET 8.0 | 698.7 ns | 8.99 ns | 8.41 ns | 0.0172 |   3,671 B |     144 B |

So, not quite sure where to go with this.

**Comment by akade** [comment]
Thanks for looking into it. 

I have also some variation between runs but the NET 8.0 came always second. Though, with preview 7 as shown above not as clearly as before:

``` ini
BenchmarkDotNet v0.13.7, Windows 11 (10.0.22621.2070/22H2/2022Update/SunValley2)
AMD Ryzen 9 5900X, 1 CPU, 24 logical and 12 physical cores
.NET SDK 8.0.100-preview.7.23376.3
  [Host]   : .NET 7.0.10 (7.0.1023.36312), X64 RyuJIT AVX2
  .NET 7.0 : .NET 7.0.10 (7.0.1023.36312), X64 RyuJIT AVX2
  .NET 8.0 : .NET 8.0.0 (8.0.23.37506), X64 RyuJIT AVX2
```
|                Method |      Job |  Runtime |     Mean |    Error |   StdDev | Code Size | CacheMisses/Op | BranchMispredictions/Op |   Gen0 | Allocated |
|---------------------- |--------- |--------- |---------:|---------:|---------:|----------:|---------------:|------------------------:|-------:|----------:|
| StartsWith_IndexedSet | .NET 7.0 | .NET 7.0 | 627.0 ns | 12.21 ns | 14.53 ns |   3,885 B |              2 |                       0 | 0.0086 |     144 B |
| StartsWith_IndexedSet | .NET 8.0 | .NET 8.0 | 642.9 ns |  6.58 ns |  5.14 ns |   3,639 B |              2 |                       0 | 0.0086 |     144 B |

And a run directly after it, with different code size:
|                Method |      Job |  Runtime |     Mean |   Error |  StdDev |   Gen0 | Code Size | Allocated |
|---------------------- |--------- |--------- |---------:|--------:|--------:|-------:|----------:|----------:|
| StartsWith_IndexedSet | .NET 7.0 | .NET 7.0 | 598.7 ns | 1.97 ns | 1.84 ns | 0.0086 |   3,885 B |     144 B |
| StartsWith_IndexedSet | .NET 8.0 | .NET 8.0 | 632.1 ns | 0.70 ns | 0.65 ns | 0.0086 |   3,671 B |     144 B |

Anoter code size:
|                Method |      Job |  Runtime |     Mean |   Error |  StdDev |   Gen0 | Code Size | Allocated |
|---------------------- |--------- |--------- |---------:|--------:|--------:|-------:|----------:|----------:|
| StartsWith_IndexedSet | .NET 7.0 | .NET 7.0 | 593.6 ns | 1.69 ns | 1.58 ns | 0.0086 |   3,885 B |     144 B |
| StartsWith_IndexedSet | .NET 8.0 | .NET 8.0 | 629.6 ns | 1.75 ns | 1.64 ns | 0.0086 |   3,658 B |     144 B |


As you can see, I also tried to look into cache misses or branch mispredictions (which could very well be CPU specific) but to no avail. However, I noticed in my and your runs, is that the code size varies slightly with .NET 8.  Is the JIT non-deterministic?

**Comment by akade** [comment]
As the difference is not that big anymore (and it's faster on your machines), I would not be disappointed if you think that the return for the necessary investigation efforts is too small...

**Comment by AndyAyersMS** [comment]
> I noticed in my and your runs, that the code size varies slightly with .NET 8. Is the JIT non-deterministic?

The JIT itself is deterministic but the inputs to the JIT are not.

So there's always been potential for some non-determinism in the generated code (especially so when the application itself is not deterministic) but with PGO there are now many more cases where this can happen.

> As the difference is not that big anymore (and it's faster on your machines), I would not be disappointed if you think that the return for the necessary investigation efforts is too small...

I plan to do a bit more digging. I am curious why there is so much apparent variability from run to run here, and also why we don't do more inlining in the .NET 8 case.

Since you have a nuget package, I wonder if you would consider adding your benchmarks to our "real world" code collection over on https://gitub.com/performance; that way we'd have an ongoing series of measurements of the performance of your code.

**Comment by AndyAyersMS** [comment]
For inlining:
```
  8.0 Inlining
  
  Inlines into 060000E5 [via ExtendedDefaultPolicy] Akade.IndexedSet.DataStructures.Trie`1[System.__Canon]:AddRecursivlyToResult(Akade.IndexedSet.DataStructures.Trie`1+TrieNode[System.__Canon],System.Collections.Generic.List`1[System.__Canon]):
  [INL00 IL=0015 TR=000072 060085D0] [FAILED: callee: has exception handling] System.Collections.Generic.List`1[System.__Canon]:AddRange(System.Collections.Generic.IEnumerable`1[System.__Canon]):this
  [INL00 IL=0034 TR=000016 060084DA] [FAILED: call site: runtime dictionary lookup] System.Collections.Generic.Dictionary`2[ushort,System.__Canon]:GetEnumerator():System.Collections.Generic.Dictionary`2+Enumerator[ushort,System.__Canon]:this
  [INL01 IL=0044 TR=000033 06008500] [INLINED: callee: below ALWAYS_INLINE size] System.Collections.Generic.Dictionary`2+Enumerator[ushort,System.__Canon]:get_Current():System.Collections.Generic.KeyValuePair`2[ushort,System.__Canon]:this
  [INL00 IL=0056 TR=000046 060085BC] [FAILED: call site: runtime dictionary lookup] System.Collections.Generic.KeyValuePair`2[ushort,System.__Canon]:Deconstruct(byref,byref):this
  [INL00 IL=0063 TR=000055 060000E5] [FAILED: callee: has exception handling] Akade.IndexedSet.DataStructures.Trie`1[System.__Canon]:AddRecursivlyToResult(Akade.IndexedSet.DataStructures.Trie`1+TrieNode[System.__Canon],System.Collections.Generic.List`1[System.__Canon])
  [INL00 IL=0070 TR=000021 060084FF] [FAILED: call site: runtime dictionary lookup] System.Collections.Generic.Dictionary`2+Enumerator[ushort,System.__Canon]:MoveNext():bool:this
```
There are some interesting issues here:
* We are unable to inline methods with EH. This is something we ought to explore relaxing in .NET 9.
* `AddRecursivlyToResult` (perhaps unexpectedly) contains EH, because of the use of `foreach` on a `Dictionary`.
* We are also unable to do some inlines that cross from one shared generic class to another. So some of the dictionary methods can't be inlined. This is also something we might get around to fixing in .NET 9.

**Comment by AndyAyersMS** [comment]
Also in the profile there are a a fair number of hits in the `unknown` bin (likely VSD) and in the runtime. Those latter are write barriers, array allocation, and zeroing.

Since your benchmark doesn't do anything interesting with the enumerated string data those impacts are somewhat overstated. In a more realistic test you'd actually look at the data returned and the relative overhead of these would go down.

**Comment by akade** [comment]
Thanks for looking into it and explaining the specifics! I'm happy to learn a few things here & there, and looking into EH & inling was seomthing I planned to do anyway.

I'm happy to add the benchmarks. Would that be in https://github.com/dotnet/performance/tree/main/src/benchmarks/real-world, similar to for example ImageSharp? Would you suggest that I do something with the results in the benchmarks or leave them like they are? We use the package extensivly in one of our projects and I could create less synthetic benchmarks based on that...

---
Yes, you can close the issue. I'm okay with the perf in preview 7.

**Comment by AndyAyersMS** [comment]
> Would that be in https://github.com/dotnet/performance/tree/main/src/benchmarks/real-world, similar to for example ImageSharp? Would you suggest that I do something with the results in the benchmarks or leave them like they are? We use the package extensivly in one of our projects and I could create less synthetic benchmarks based on that...

Yes, that's the right spot. A less synthetic benchmark would be preferable, but if it's a lot of work then consider adding what you already have.
