### ISSUE TITLE
Json outerloop test failure "Reflection-based serialization has been disabled"

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#90121]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=365410
Build error leg or test failing: System.Text.Json.SourceGeneration.Tests.CollectionTests_Default.WriteAsyncEnumerable_LongRunningEnumeration_Cancellation
Pull request: https://github.com/dotnet/runtime/pull/90094

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "typeof(System.InvalidOperationException): Reflection-based serialization has been disabled for this application.",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

Example console log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-90094-merge-442907353b7d42e888/System.Text.Json.SourceGeneration.Roslyn4.4.Tests/1/console.7fe860c2.log?helixlogtype=result

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=365410
**Error message validated:** `typeof(System.InvalidOperationException): Reflection-based serialization has been disabled for this application.`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 8/7/2023 11:08:41 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[365410](https://dev.azure.com/dnceng-public/public/_build/results?buildId=365410)|dotnet/runtime|[System.Text.Json.SourceGeneration.Tests.CollectionTests_Metadata_AsyncStream.WriteAsyncEnumerable_LongRunningEnumeration_Cancellation](https://dev.azure.com/dnceng-public/public/_build/results?buildId=365410&view=ms.vss-test-web.build-test-results-tab&runId=7730050&resultId=104066)|dotnet/runtime#90094|
|[365231](https://dev.azure.com/dnceng-public/public/_build/results?buildId=365231)|dotnet/runtime|[System.Text.Json.SourceGeneration.Tests.CollectionTests_Metadata_String.WriteAsyncEnumerable_LongRunningEnumeration_Cancellation](https://dev.azure.com/dnceng-public/public/_build/results?buildId=365231&view=ms.vss-test-web.build-test-results-tab&runId=7723946&resultId=103872)||
|[365214](https://dev.azure.com/dnceng-public/public/_build/results?buildId=365214)|dotnet/runtime|[System.Text.Json.SourceGeneration.Tests.CollectionTests_Default.WriteAsyncEnumerable_LongRunningEnumeration_Cancellation](https://dev.azure.com/dnceng-public/public/_build/results?buildId=365214&view=ms.vss-test-web.build-test-results-tab&runId=7724054&resultId=103753)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|3|3|3|

**Comment by eiriktsarpalis** [comment]
Looks like an outerloop test that wasn't updated to support sourcegen/Native AOT.
