### ISSUE TITLE
is there any solution pass object to native like mono

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#90134]
we want to embed coreclr, how can we interop pass object, like mono, we can use mono_add_internal_call

**Comment by jkotas** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/39798

Passing objects from/to 3rd party code requires pinning or wrapping the objects in GC handles. We have no plans to enable passing of raw object references to 3rd party code.

**Comment by srxqds** [comment]
ok, thank you
