### ISSUE TITLE
[API Proposal]: Add `CollectionsMarshal.AsMemory(List<T>)`

### ISSUE THREAD

**Issue by Neme12** [dotnet/runtime#90141]
### Background and motivation

The existing `CollectionsMarshal.AsSpan` method is really useful in order to be able to get a span from a `List<T>`, however, in many scenarios, e.g. when calling async methods, what you really need is a `Memory<T>` instead. Since you can't get a `Memory<T>` from a `Span<T>`, you currently need to make a copy of the data. This could be avoided if there was an ability to get a `Memory<T>` directly from a `List<T>`.

### API Proposal

```diff 
 namespace System.Runtime.InteropServices;

 public static class CollectionsMarshal
 {
     // Existing method:
     public static Span<T> AsSpan<T>(List<T>? list)

     // New method:
+    public static Memory<T> AsMemory<T>(List<T>? list)
 }
```
and if #90138 is approved, then also:
```diff
 namespace System.Runtime.InteropServices;

 public static class ImmutableCollectionsMarshal
 {
     // Method proposed in #90138:
     public static Span<T> AsSpan<T>(ImmutableArray<T>.Builder? builder);

     // New method:
+    public static Span<T> AsMemory<T>(ImmutableArray<T>.Builder? builder);
 }
```

### API Usage

```csharp
async Task FooAsync(TextWriter writer)
{
    var list = new List<char>();
    // ...fill the collection
    await writer.WriteAsync(CollectionsMarshal.AsMemory(list));
}
```

**Comment by Tornhoof** [comment]
The ``AsMemory`` method was specifically excluded in the original API Review, see https://github.com/dotnet/runtime/issues/27061#issuecomment-534703891 (and specifically the video).

**Comment by huoyaoyuan** [comment]
See also https://github.com/dotnet/runtime/discussions/87210.

**Comment by stephentoub** [comment]
While `AsSpan(List<T>)` baked in the notion of `List<T>` being backed by contiguous memory, `AsMemory(List<T>)` would effectively bake in the notion of it being backed by a `T[]`.  That's something we'd like to avoid doing right now. (Such an AsMemory could return a Memory backed by a MemoryManager, but that would then either require that AsMemory to start allocating or it would require the list to grow to be able to cache the MemoryManager reference, neither of which we'd want.)

**Comment by Neme12** [comment]
Why would it have to bake in the notion of it being a `T[]`? I don't understand. `Memory<T>` is an abstraction.

**Comment by Neme12** [comment]
I understand that it's possible to get the underlying array from a `T[]`, but only via `MemoryMarshal` and anyone who does that and relies on it being an array could be expected to be broken IMO.

**Comment by stephentoub** [comment]
Because `Memory<T>` is backed by either `T[]` or a `MemoryManager<T>`, and we wouldn't use `MemoryManager<T>` for the reasons I mentioned.

**Comment by Neme12** [comment]
But that would be an implementation detail. The API would still return an abstraction.

**Comment by stephentoub** [comment]
Let's say `List<T>` changed to be backed by something other than `T[]`. What "implementation detail" would you then employ to keep this new `AsMemory` functional and allocation-free?

**Comment by Neme12** [comment]
I mean I wouldn't have the expectation that it has to be 100% allocation free. I would expect that the data wouldn't be copied, but a small allocation just for the memory manager seems fine IMO.

**Comment by stephentoub** [comment]
> I mean I wouldn't have the expectation that it has to be 100% allocation free

It's a key expectation in general for this kind of method, that it's effectively a cheap, allocation-free cast.

**Comment by Neme12** [comment]
> > I mean I wouldn't have the expectation that it has to be 100% allocation free
> 
> It's a key expectation in general for this kind of method, that it's effectively a cheap, allocation-free cast.

I guess we have different expectations. When I'm using `Memory<T>`, I'm aware that there might be a small allocation there for a `MemoryManager` since `Memory<T>` can be backed by that.
