### ISSUE TITLE
[API Proposal]: Expose `FileStream.DefaultBufferSize`

### ISSUE THREAD

**Issue by Neme12** [dotnet/runtime#90157]
### Background and motivation

When creating a `FileStream`, if I want to specify `useAsync` or `FileOptions`, I also have to specify the buffer size parameter. I'd expect to either
a) be able to specify 0 or -1 in order for `FileStream` to use the default buffer size
b) if not, there should be a constant that I could use so that I don't have to hardcode the value.
The documentation says that the default value is 4096 so that's what I always hardcore in these cases, but this means that if `FileStream` ever changes its default buffer size to some other value, I will not get the updated value.

### API Proposal

```diff
 namespace System.IO

 public class FileStream
 {
+    public static int DefaultBufferSize { get; }

     // or
     public const int DefaultBufferSize = 4096;
 }
```

### API Usage

```csharp
using (var fileStream = new FileStream("test.txt", FileMode.Open, FileAccess.Read, FileShare.Read, FileStream.DefaultBufferSize, useAsync: true))
{
    // ...
}
```

### Alternative Designs

As an alternative, `FileStream` could accept either 0 or -1 as the `bufferSize` and translate that to the default buffer size.

**Comment by Zintom** [comment]
Can't you just use the named parameter for useAsync etc?

**Comment by adamsitnik** [comment]
Hi @Neme12 

> When creating a FileStream, if I want to specify useAsync or FileOptions, I also have to specify the buffer size parameter.

Have you tried using the ctor that accepts `FileStreamOptions`? 

```cs
namespace System.IO
{
    public sealed class FileStreamOptions
    {
        public FileStreamOptions() {}
        public FileMode Mode { get; set; }
        public FileAccess Access { get; set; } = FileAccess.Read;
        public FileShare Share { get; set; } = FileShare.Read;
        public FileOptions Options { get; set; }
        public int BufferSize { get; set; } = 4096;
        public long PreallocationSize { get; set; }
    }

    public class FileStream : Stream
    {
        public FileStream(string path, FileStreamOptions options);
    }
}
```

Sample usage:

```cs
var openForReading = new FileStreamOptions { Mode = FileMode.Open };
using FileStream source = new FileStream("source.txt", openForReading);

var createForWriting = new FileStreamOptions
{
    Mode = FileMode.CreateNew,
    Access = FileAccess.Write,
    Options = FileOptions.WriteThrough,
    BufferSize = 0, // disable FileStream buffering
    PreallocationSize = source.Length // specify size up-front
};
using FileStream destination = new FileStream("destination.txt", createForWriting);
source.CopyTo(destination);
```



For more please refer to https://devblogs.microsoft.com/dotnet/file-io-improvements-in-dotnet-6/#filestreamoptions

**Comment by Neme12** [comment]
@adamsitnik I have, but this still feels like an omission.

**Comment by adamsitnik** [comment]
`FileStreamOptions` was introduced to avoid the need of adding more `FileStream` ctors in the future and also avoid the confusion of users who had to provide values like `bufferSize` when using the existing `FileStream` ctors. 

We don't plan to introduce new `FileStream` ctors that don't use it or expose any of the internal flags that are not required to use with `FileStreamOptions`. `FileStreamOptions` is the way to move forward.

**Comment by Neme12** [comment]
What if you want to avoid allocating the options though?

**Comment by adamsitnik** [comment]
> What if you want to avoid allocating the options though?

You can cache and re-use the options instance. But to be honest the cost of allocation will be close to nothing compared to the cost of opening a file.
