### ISSUE TITLE
Is there a document for Coreclr on the Android platform

### ISSUE THREAD

**Issue by CeSun** [dotnet/runtime#90160]
If I want to embed coreclr on an Android app (c++), how should I locate the directory of the standard library? Has there been a change in the way dependencies are loaded?

**Comment by jeffschwMSFT** [comment]
Have you checked out this document?  https://learn.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting

Android is not an officially supported platform for coreclr.  Howerver, we have a mono offering on Android.

**Comment by CeSun** [comment]
Hello, this document I have read, mono I tried on windows platform, mono api and coreclr is very different, I need to maintain two embedded code, which is a lot of trouble.

I see that mono's dynamic library exports coreclr compatible c++ apis, Is it available? Maybe one day Android coreclr is ready and I can easily replace it.

In addition, want to ask the mobile end of coreclr is not planned for the time being? How many.NET versions will still use mono?

**Comment by jeffschwMSFT** [comment]
> In addition, want to ask the mobile end of coreclr is not planned for the time being? How many.NET versions will still use mono?

Nothing to share at this point.  If you have not taken a look, we are shipping an preview version of iOS using Native AOT.

> mono api and coreclr is very different

That is true.  Though depending on your scenario, it likely is less specific code than you might think.  Often these PAL layers are thin and once you have the runtime started, you can do most of the interesting logic in managed (which is shared code).

> I see that mono's dynamic library exports coreclr compatible c++ apis, Is it available?

Can you elaborate?  I am not quite sure what you are asking.

**Comment by CeSun** [comment]
> > In addition, want to ask the mobile end of coreclr is not planned for the time being? How many.NET versions will still use mono?
> 
> Nothing to share at this point. If you have not taken a look, we are shipping an preview version of iOS using Native AOT.
> 
> > mono api and coreclr is very different
> 
> That is true. Though depending on your scenario, it likely is less specific code than you might think. Often these PAL layers are thin and once you have the runtime started, you can do most of the interesting logic in managed (which is shared code).
> 
> > I see that mono's dynamic library exports coreclr compatible c++ apis, Is it available?
> 
> Can you elaborate? I am not quite sure what you are asking.

![3edcd02bb77560c1e989727a7316230d](https://github.com/dotnet/runtime/assets/54771283/46b221d0-9ea8-45cd-8835-561510f6991e)
These apis are the same as those provided by coreclr's dynamic library, are they available?

**Comment by jeffschwMSFT** [comment]
@SamMonoRT who may have some insight on the mono exports

**Comment by SamMonoRT** [comment]
cc @grendello @jonathanpeppers @fanyang-mono

**Comment by fanyang-mono** [comment]
@CeSun those methods that you highlighted are defined in `main-core.c` (https://github.com/dotnet/runtime/blob/7bc9f6bd9652fcfcb850d7ac3f52f9a1bb9d1431/src/mono/mono/mini/main-core.c) When using Mono runtime, they are merely wrappers which call into mono functions eventually. I hope this answer your question.

**Comment by CeSun** [comment]
> @CeSun those methods that you highlighted are defined in (https://github.com/dotnet/runtime/blob/7bc9f6bd9652fcfcb850d7ac3f52f9a1bb9d1431/src/mono/mono/mini/main-core.c) When using Mono runtime, they are merely wrappers which call into mono functions eventually. I hope this answer your question.`main-core.c`

What platforms are supported by these APIs? Does it support mobile platforms?

**Comment by fanyang-mono** [comment]
@CeSun For using Mono on Android, we actually have a complete end to end solution. Have you considered `Xamarin.Android` (https://learn.microsoft.com/en-us/xamarin/android/)? Or if you are looking for cross platform mobile development, there is `.NET MAUII` (https://dotnet.microsoft.com/en-us/apps/maui).

To answer your question directly, I would expect them to work on Android. But I am not 100% sure. Feel free to try it out.

**Comment by akoeplinger** [comment]
Looks like the question was answered, closing this issue.

CoreCLR on Android is also tracked via https://github.com/dotnet/runtime/issues/4296
