### ISSUE TITLE
get attributes from objects created on runtime

### ISSUE THREAD

**Issue by ehsangfl** [dotnet/runtime#90164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`Runtimebject.GetType().GetProperty("prop1").GetCustomAttributes()` raised an error when the runtime object was created through `System.Reflection.Emit.TypeBuilder`

platform: Blazor wasm
version: 7.0.8
browser: Chrome

### Expected Behavior

`Runtimebject.GetType().GetProperty("prop1").GetCustomAttributes()` return a list of attributes contains Display and Required attribute

### Steps To Reproduce

I created a type through `System.Reflection.Emit.TypeBuilder` and named it `RutimeObject`

then I added a property named `prope1`. then add some attributes to the prop1 (`Display` and `Required` attributes)
then I create an instance from `RuntimeObject`
when I try to get custom attributes through reflection 
`Runtimebject.GetType().GetProperty("prop1").GetCustomAttributes();`

this has not happened if you add only one attribute and it happened if add 2 or  more attributes

### Exceptions (if any)

```
dotnet.7.0.7.d6ly7i5yxa.js:5  Error: [MONO] * Assertion at /__w/1/s/src/mono/mono/metadata/assembly.c:735, condition `<disabled>' not met

    at xe (dotnet.7.0.7.d6ly7i5yxa.js:5:509)
    at Object.je (dotnet.7.0.7.d6ly7i5yxa.js:5:792)
    at _mono_wasm_trace_logger (dotnet.7.0.7.d6ly7i5yxa.js:14:104923)
    at 00993286:0x9bf7
    at 00993286:0xa5a65
    at 00993286:0x1c0037
    at 00993286:0x1c00c6
    at 00993286:0x1c0109
    at 00993286:0x1c00dc
    at 00993286:0x33f41
```

### .NET Version

8.0.100-preview.3.23178.7

**Comment by ehsangfl** [comment]
a sample
```

var an = new AssemblyName { Name = "TempAssembly" ,Version = new Version(1, 0, 0, 0) };
            var assemblyBuilder = AssemblyBuilder.DefineDynamicAssembly(an, AssemblyBuilderAccess.Run);
            var moduleBuilder = assemblyBuilder.DefineDynamicModule("TempWorkflowAssembly.dll");
            var tb = moduleBuilder.DefineType("namespace.myclass"
                                            , TypeAttributes.Public |
                                            TypeAttributes.Class |
                                            TypeAttributes.AnsiClass |
                                            TypeAttributes.BeforeFieldInit
                                            , typeof(Entity));

            FieldBuilder fb = tb.DefineField("_prop1",
                                                        typeof(string),
                                                        FieldAttributes.Private);

            var pb = tb.DefineProperty("prop1", PropertyAttributes.HasDefault, typeof(string), null);
            MethodAttributes getSetAttr =
           MethodAttributes.Public | MethodAttributes.SpecialName |
               MethodAttributes.HideBySig;

            // Define the "get" accessor method for prop1.
            MethodBuilder custNameGetPropMthdBldr =
                tb.DefineMethod("get_prop1",
                                           getSetAttr,
                                           typeof(string),
                                           Type.EmptyTypes);

            ILGenerator custNameGetIL = custNameGetPropMthdBldr.GetILGenerator();

            custNameGetIL.Emit(OpCodes.Ldarg_0);
            custNameGetIL.Emit(OpCodes.Ldfld, fb);
            custNameGetIL.Emit(OpCodes.Ret);

            // Define the "set" accessor method for prop1.
            MethodBuilder custNameSetPropMthdBldr =
                tb.DefineMethod("set_prop1",
                                           getSetAttr,
                                           null,
                                           new Type[] { typeof(string) });

            ILGenerator custNameSetIL = custNameSetPropMthdBldr.GetILGenerator();

            custNameSetIL.Emit(OpCodes.Ldarg_0);
            custNameSetIL.Emit(OpCodes.Ldarg_1);
            custNameSetIL.Emit(OpCodes.Stfld, fb);
            custNameSetIL.Emit(OpCodes.Ret);

            // Last, we must map the two methods created above to our PropertyBuilder to
            // their corresponding behaviors, "get" and "set" respectively.
            pb.SetGetMethod(custNameGetPropMthdBldr);
            pb.SetSetMethod(custNameSetPropMthdBldr);


            ///create display attribute
            var dat = typeof(DisplayAttribute);
            CustomAttributeBuilder CAB = new CustomAttributeBuilder(dat.GetConstructor(new Type[0]), 
                new object[0],
                new PropertyInfo[1] { dat.GetProperty(nameof(DisplayAttribute.Name))}, 
                new object[] { "property 1"});
            pb.SetCustomAttribute(CAB);

            //create required attribute
            var rat = typeof(RequiredAttribute);
            CustomAttributeBuilder CABR = new CustomAttributeBuilder(rat.GetConstructor(new Type[0]),
                                new object[0],
                                new PropertyInfo[2] { rat.GetProperty(nameof(RequiredAttribute.ErrorMessageResourceType)),rat.GetProperty(nameof(RequiredAttribute.ErrorMessageResourceName))},
                                new object[] {typeof(MyResources.ValidationErrors), "ObjectRequired" });
            pb.SetCustomAttribute(CABR);

            var objectType = tb.CreateType();
            var instance = (Entity)Activator.CreateInstance(objectType);
```

I found that this is happened if we use resources for attributes

**Comment by lambdageek** [comment]
This should be reproducible in a console app with `<UseMonoRuntime>true</UseMonoRuntime` + `<SelfContained>true</SelfContained>`

**Comment by SamMonoRT** [comment]
cc @ivanpovazan @kotlarmilos

**Comment by lambdageek** [comment]
Self contained repro.  It's not that resources are necessary. it's that you need to use a custom attribute with a `typeof(SomeTypeFromThisAssembly)` parameter.  So the custom attribute in the dynamic assembly has a reference to the current assembly.  

I don't get exactly the same crash (with net8.0 and with net7.0). I get this stack trace:

```
=================================================================
	Native stacktrace:
=================================================================
	0x1027b3f88 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : mono_dump_native_crash_info
	0x102772ea4 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : mono_handle_native_crash
	0x1026df298 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : mono_sigsegv_signal_handler_debug
	0x18c21aa24 - /usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x10264c0c0 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : mono_coop_mutex_lock
	0x10264d024 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : mono_alc_find_assembly
	0x1025afa18 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : mono_assembly_invoke_search_hook_internal
	0x1025b2650 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : mono_assembly_loaded_internal
	0x102637110 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : _mono_reflection_get_type_from_info
	0x102637044 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : mono_reflection_type_from_name_checked
	0x10264b000 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : cattr_type_from_name
	0x10264adf8 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : load_cattr_type
	0x10264a5c0 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : load_cattr_value
	0x102648e54 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : create_custom_attr
	0x102647744 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : mono_custom_attrs_construct_by_type
	0x1026496c0 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : mono_reflection_get_custom_attrs_by_type_handle
	0x1025e0900 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : ves_icall_MonoCustomAttrs_GetCustomAttributesInternal_raw
	0x10251d2f8 - Unknown
	0x10251d124 - Unknown
	0x10251bed4 - Unknown
	0x10251bc0c - Unknown
	0x10251ba1c - Unknown
	0x10251b97c - Unknown
	0x1022b1780 - Unknown
	0x1022b2230 - Unknown
	0x1026e24d4 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : mono_jit_runtime_invoke
	0x1026150f4 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : mono_runtime_invoke_checked
	0x10261cd94 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : do_exec_main_checked
	0x1027353c4 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : mono_jit_exec
	0x102737e60 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : mono_main
	0x1027a147c - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : monovm_execute_assembly
	0x1021d54f8 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libhostpolicy.dylib : _Z19run_app_for_contextRK20hostpolicy_context_tiPPKc
	0x1021d625c - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libhostpolicy.dylib : corehost_main
```


---

`fofa.csproj`:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="true">
      <UseMonoRuntime>true</UseMonoRuntime>
      <SelfContained>true</SelfContained>
  </PropertyGroup>
</Project>
```

`Program.cs`:

```csharp
using System;
using System.Resources;
using System.Reflection;
using System.Reflection.Emit;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace fofa {
    public class M {
        public static void Main() {

            var an = new AssemblyName { Name = "TempAssembly" ,Version = new Version(1, 0, 0, 0) };
            var assemblyBuilder = AssemblyBuilder.DefineDynamicAssembly(an, AssemblyBuilderAccess.Run);
            var moduleBuilder = assemblyBuilder.DefineDynamicModule("TempWorkflowAssembly.dll");
            var tb = moduleBuilder.DefineType("namespace.myclass"
                                            , TypeAttributes.Public |
                                            TypeAttributes.Class |
                                            TypeAttributes.AnsiClass |
                                            TypeAttributes.BeforeFieldInit
                                            , typeof(object));

            FieldBuilder fb = tb.DefineField("_prop1",
                                                        typeof(string),
                                                        FieldAttributes.Private);

            var pb = tb.DefineProperty("prop1", PropertyAttributes.HasDefault, typeof(string), null);
            MethodAttributes getSetAttr =
                MethodAttributes.Public | MethodAttributes.SpecialName |
                MethodAttributes.HideBySig;

            // Define the "get" accessor method for prop1.
            MethodBuilder custNameGetPropMthdBldr =
                tb.DefineMethod("get_prop1",
                                           getSetAttr,
                                           typeof(string),
                                           Type.EmptyTypes);

            ILGenerator custNameGetIL = custNameGetPropMthdBldr.GetILGenerator();

            custNameGetIL.Emit(OpCodes.Ldarg_0);
            custNameGetIL.Emit(OpCodes.Ldfld, fb);
            custNameGetIL.Emit(OpCodes.Ret);

            // Define the "set" accessor method for prop1.
            MethodBuilder custNameSetPropMthdBldr =
                tb.DefineMethod("set_prop1",
                                           getSetAttr,
                                           null,
                                           new Type[] { typeof(string) });

            ILGenerator custNameSetIL = custNameSetPropMthdBldr.GetILGenerator();

            custNameSetIL.Emit(OpCodes.Ldarg_0);
            custNameSetIL.Emit(OpCodes.Ldarg_1);
            custNameSetIL.Emit(OpCodes.Stfld, fb);
            custNameSetIL.Emit(OpCodes.Ret);

            // Last, we must map the two methods created above to our PropertyBuilder to
            // their corresponding behaviors, "get" and "set" respectively.
            pb.SetGetMethod(custNameGetPropMthdBldr);
            pb.SetSetMethod(custNameSetPropMthdBldr);


            ///create display attribute
            var dat = typeof(DisplayAttribute);
            CustomAttributeBuilder CAB = new CustomAttributeBuilder(dat.GetConstructor(new Type[0]), 
                new object[0],
                new PropertyInfo[1] { dat.GetProperty(nameof(DisplayAttribute.Name))}, 
                new object[] { "property 1"});
            pb.SetCustomAttribute(CAB);


            //create required attribute
            var rat = typeof(RequiredAttribute);
            CustomAttributeBuilder CABR = new CustomAttributeBuilder(rat.GetConstructor(new Type[0]),
                                new object[0],
                                new PropertyInfo[2] { rat.GetProperty(nameof(RequiredAttribute.ErrorMessageResourceType)),rat.GetProperty(nameof(RequiredAttribute.ErrorMessageResourceName))},
                                new object[] {typeof(ValidationErrors), "ObjectRequired" });
            pb.SetCustomAttribute(CABR);

            var objectType = tb.CreateType();
            var instance = Activator.CreateInstance(objectType);


            var attrs = instance.GetType().GetProperty("prop1").GetCustomAttributes();
            foreach (var attr in attrs) {
                Console.WriteLine (attr);
                if (attr is RequiredAttribute reqAttr)
                    Console.WriteLine(" RequiredAttribute.FormatErrorMessage(\"abc\") => {0}", reqAttr.FormatErrorMessage("abc"));
            }
        }
    }

    public class ValidationErrors {
        public static string ObjectRequired => "some string"; 
    }

}
```

run with `dotnet run -f net7.0`

**Comment by ehsangfl** [comment]
> Self contained repro. It's not that resources are necessary. it's that you need to use a custom attribute with a `typeof(SomeTypeFromThisAssembly)` parameter. So the custom attribute in the dynamic assembly has a reference to the current assembly.
> 
> I don't get exactly the same crash (with net8.0 and with net7.0). I get this stack trace:
> 
> ```
> =================================================================
> 	Native stacktrace:
> =================================================================
> 	0x1027b3f88 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : mono_dump_native_crash_info
> 	0x102772ea4 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : mono_handle_native_crash
> 	0x1026df298 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : mono_sigsegv_signal_handler_debug
> 	0x18c21aa24 - /usr/lib/system/libsystem_platform.dylib : _sigtramp
> 	0x10264c0c0 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : mono_coop_mutex_lock
> 	0x10264d024 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : mono_alc_find_assembly
> 	0x1025afa18 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : mono_assembly_invoke_search_hook_internal
> 	0x1025b2650 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : mono_assembly_loaded_internal
> 	0x102637110 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : _mono_reflection_get_type_from_info
> 	0x102637044 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : mono_reflection_type_from_name_checked
> 	0x10264b000 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : cattr_type_from_name
> 	0x10264adf8 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : load_cattr_type
> 	0x10264a5c0 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : load_cattr_value
> 	0x102648e54 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : create_custom_attr
> 	0x102647744 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : mono_custom_attrs_construct_by_type
> 	0x1026496c0 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : mono_reflection_get_custom_attrs_by_type_handle
> 	0x1025e0900 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : ves_icall_MonoCustomAttrs_GetCustomAttributesInternal_raw
> 	0x10251d2f8 - Unknown
> 	0x10251d124 - Unknown
> 	0x10251bed4 - Unknown
> 	0x10251bc0c - Unknown
> 	0x10251ba1c - Unknown
> 	0x10251b97c - Unknown
> 	0x1022b1780 - Unknown
> 	0x1022b2230 - Unknown
> 	0x1026e24d4 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : mono_jit_runtime_invoke
> 	0x1026150f4 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : mono_runtime_invoke_checked
> 	0x10261cd94 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : do_exec_main_checked
> 	0x1027353c4 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : mono_jit_exec
> 	0x102737e60 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : mono_main
> 	0x1027a147c - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libcoreclr.dylib : monovm_execute_assembly
> 	0x1021d54f8 - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libhostpolicy.dylib : _Z19run_app_for_contextRK20hostpolicy_context_tiPPKc
> 	0x1021d625c - /private/tmp/fofa/bin/Debug/net7.0/osx-arm64/libhostpolicy.dylib : corehost_main
> ```
> 
> `fofa.csproj`:
> 
> ```
> <Project Sdk="Microsoft.NET.Sdk">
> 
>   <PropertyGroup>
>     <OutputType>Exe</OutputType>
>     <TargetFramework>net7.0</TargetFramework>
>     <ImplicitUsings>enable</ImplicitUsings>
>     <Nullable>enable</Nullable>
>   </PropertyGroup>
> 
>   <PropertyGroup Condition="true">
>       <UseMonoRuntime>true</UseMonoRuntime>
>       <SelfContained>true</SelfContained>
>   </PropertyGroup>
> </Project>
> ```
> 
> `Program.cs`:
> 
> ```cs
> using System;
> using System.Resources;
> using System.Reflection;
> using System.Reflection.Emit;
> using System.ComponentModel.DataAnnotations;
> 
> #nullable disable
> 
> namespace fofa {
>     public class M {
>         public static void Main() {
> 
>             var an = new AssemblyName { Name = "TempAssembly" ,Version = new Version(1, 0, 0, 0) };
>             var assemblyBuilder = AssemblyBuilder.DefineDynamicAssembly(an, AssemblyBuilderAccess.Run);
>             var moduleBuilder = assemblyBuilder.DefineDynamicModule("TempWorkflowAssembly.dll");
>             var tb = moduleBuilder.DefineType("namespace.myclass"
>                                             , TypeAttributes.Public |
>                                             TypeAttributes.Class |
>                                             TypeAttributes.AnsiClass |
>                                             TypeAttributes.BeforeFieldInit
>                                             , typeof(object));
> 
>             FieldBuilder fb = tb.DefineField("_prop1",
>                                                         typeof(string),
>                                                         FieldAttributes.Private);
> 
>             var pb = tb.DefineProperty("prop1", PropertyAttributes.HasDefault, typeof(string), null);
>             MethodAttributes getSetAttr =
>                 MethodAttributes.Public | MethodAttributes.SpecialName |
>                 MethodAttributes.HideBySig;
> 
>             // Define the "get" accessor method for prop1.
>             MethodBuilder custNameGetPropMthdBldr =
>                 tb.DefineMethod("get_prop1",
>                                            getSetAttr,
>                                            typeof(string),
>                                            Type.EmptyTypes);
> 
>             ILGenerator custNameGetIL = custNameGetPropMthdBldr.GetILGenerator();
> 
>             custNameGetIL.Emit(OpCodes.Ldarg_0);
>             custNameGetIL.Emit(OpCodes.Ldfld, fb);
>             custNameGetIL.Emit(OpCodes.Ret);
> 
>             // Define the "set" accessor method for prop1.
>             MethodBuilder custNameSetPropMthdBldr =
>                 tb.DefineMethod("set_prop1",
>                                            getSetAttr,
>                                            null,
>                                            new Type[] { typeof(string) });
> 
>             ILGenerator custNameSetIL = custNameSetPropMthdBldr.GetILGenerator();
> 
>             custNameSetIL.Emit(OpCodes.Ldarg_0);
>             custNameSetIL.Emit(OpCodes.Ldarg_1);
>             custNameSetIL.Emit(OpCodes.Stfld, fb);
>             custNameSetIL.Emit(OpCodes.Ret);
> 
>             // Last, we must map the two methods created above to our PropertyBuilder to
>             // their corresponding behaviors, "get" and "set" respectively.
>             pb.SetGetMethod(custNameGetPropMthdBldr);
>             pb.SetSetMethod(custNameSetPropMthdBldr);
> 
> 
>             ///create display attribute
>             var dat = typeof(DisplayAttribute);
>             CustomAttributeBuilder CAB = new CustomAttributeBuilder(dat.GetConstructor(new Type[0]), 
>                 new object[0],
>                 new PropertyInfo[1] { dat.GetProperty(nameof(DisplayAttribute.Name))}, 
>                 new object[] { "property 1"});
>             pb.SetCustomAttribute(CAB);
> 
> 
>             //create required attribute
>             var rat = typeof(RequiredAttribute);
>             CustomAttributeBuilder CABR = new CustomAttributeBuilder(rat.GetConstructor(new Type[0]),
>                                 new object[0],
>                                 new PropertyInfo[2] { rat.GetProperty(nameof(RequiredAttribute.ErrorMessageResourceType)),rat.GetProperty(nameof(RequiredAttribute.ErrorMessageResourceName))},
>                                 new object[] {typeof(ValidationErrors), "ObjectRequired" });
>             pb.SetCustomAttribute(CABR);
> 
>             var objectType = tb.CreateType();
>             var instance = Activator.CreateInstance(objectType);
> 
> 
>             var attrs = instance.GetType().GetProperty("prop1").GetCustomAttributes();
>             foreach (var attr in attrs) {
>                 Console.WriteLine (attr);
>                 if (attr is RequiredAttribute reqAttr)
>                     Console.WriteLine(" RequiredAttribute.FormatErrorMessage(\"abc\") => {0}", reqAttr.FormatErrorMessage("abc"));
>             }
>         }
>     }
> 
>     public class ValidationErrors {
>         public static string ObjectRequired => "some string"; 
>     }
> 
> }
> ```
> 
> run with `dotnet run -f net7.0`
> 
> expected output with CoreCLR:
> 
> ```
> System.ComponentModel.DataAnnotations.DisplayAttribute
> System.ComponentModel.DataAnnotations.RequiredAttribute
>  RequiredAttribute.FormatErrorMessage("abc") => some string
> ```

this is not a Blazor Webassembly project type. the problem is only on Blazor wasm

**Comment by lambdageek** [comment]
@ehsangfl it's a general problem with Mono and custom attributes.  It happens in Blazor, but it also happens in console apps configured to use Mono.

**Comment by kotlarmilos** [comment]
The RequiredAttribute can't find `ValidationErrors` within the `TempAssembly`, and it's image doesn't have an ALC, so the assembly `customattributes.ValidationErrors, customattributes, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35` can't be found using reflection. If the image's ALC doesn't exist, which might be the case with dynamic objects created during runtime, it should use the default one.

A temporary workaround, until the fix lands main, would be to create the ValidationErrors type within the TempAssembly using the builder.
```c#
// Define the ValidationErrors class
var validationErrorsTypeBuilder = moduleBuilder.DefineType(
    "namespace.ValidationErrors", 
    TypeAttributes.Public | TypeAttributes.Class | TypeAttributes.AnsiClass | TypeAttributes.BeforeFieldInit
);

// Define a static field for the ObjectRequired property
FieldBuilder objectRequiredFieldBuilder = validationErrorsTypeBuilder.DefineField(
    "_ObjectRequired", 
    typeof(string), 
    FieldAttributes.Private | FieldAttributes.Static
);

// Set static field's initial value
var cctor = validationErrorsTypeBuilder.DefineConstructor(
    MethodAttributes.Static | MethodAttributes.Public | MethodAttributes.HideBySig | MethodAttributes.SpecialName | MethodAttributes.RTSpecialName, 
    CallingConventions.Standard, 
    Type.EmptyTypes
);

var cctorIL = cctor.GetILGenerator();
cctorIL.Emit(OpCodes.Ldstr, "some string");
cctorIL.Emit(OpCodes.Stsfld, objectRequiredFieldBuilder);
cctorIL.Emit(OpCodes.Ret);

// Define the static ObjectRequired property to get the value of the static field
var objectRequiredPropertyBuilder = validationErrorsTypeBuilder.DefineProperty(
    "ObjectRequired", 
    PropertyAttributes.None, 
    typeof(string), 
    null
);

var getMethodBuilder = validationErrorsTypeBuilder.DefineMethod(
    "get_ObjectRequired", 
    MethodAttributes.Public | MethodAttributes.Static | MethodAttributes.HideBySig | MethodAttributes.SpecialName, 
    typeof(string), 
    Type.EmptyTypes
);

var getIL = getMethodBuilder.GetILGenerator();
getIL.Emit(OpCodes.Ldsfld, objectRequiredFieldBuilder);
getIL.Emit(OpCodes.Ret);

objectRequiredPropertyBuilder.SetGetMethod(getMethodBuilder);

// Create the ValidationErrors type
var validationErrorsType = validationErrorsTypeBuilder.CreateType();
```
Then, you can use the type from the dynamically created assembly rather than directly referenced `typeof(ValidationErrors)`.
```c#
var rat = typeof(RequiredAttribute);
CustomAttributeBuilder CABR = new CustomAttributeBuilder(rat.GetConstructor(new Type[0]),
                                new object[0],
                                new PropertyInfo[2] { 
                                    rat.GetProperty(nameof(RequiredAttribute.ErrorMessageResourceType)),
                                    rat.GetProperty(nameof(RequiredAttribute.ErrorMessageResourceName))
                                },
                                new object[] {validationErrorsType, "ObjectRequired" });
pb.SetCustomAttribute(CABR);
```
