### ISSUE TITLE
Fail to complete json serialization when using a mix of standard serializer and custom JsonConverter

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#90212]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Fail-to-complete-json-serialization-when/10411758)._

---
I’m using System.Text.Json to serialize/deserialize a complex object that doesn’t work using the standard JsonSerializer. An example of the object is included below. The top level elements of the object work fine but I have had to write a custom class inheriting from `JsonConverter` for the `properties` node because of a semantic dependency between the `columns` and `rows` elements. Deserializing this works fine but when I try to serialize the .net object I get the following:

1.  The opening “{” is written by the standard serializer.
2.  Top level properties “id”, “name”, “type”, “location”, “sku” and “eTag” are all written correctly by the standard serializer.
3.  The `properties` object works fine using my custom JsonConverter.
4.  The closing `}` for the top level object is NOT written.  I expect this to be performed by the standard serializer and that's not happening. 

It seems possible that after the standard serializer delegates to the custom serializer for the `properties` element, it doesn’t continue to write anything after that delegated processing returns. I don’t think my JsonConverter should include this closing “}” since that is at a higher scope in the DOM and my JsonConverter can’t know what else might be written after it’s done.

The following example is a response body from the Azure REST API to query resource consumption:

```  
{
	"id": "subscriptions/redacted/providers/Microsoft.CostManagement/query/c79ed41f-fe45-484d-b111-4ce212e36e52",
	"name": "c79ed41f-fe45-484d-b111-4ce212e36e52",
	"type": "Microsoft.CostManagement/query",
	"location": null,
	"sku": null,
	"eTag": null,
	"properties": {
		"nextLink": null,
		"columns": [
			{
				"name": "CostUSD",
				"type": "Number"
			},
			{
				"name": "BillingMonth",
				"type": "Datetime"
			},
			{
				"name": "ResourceId",
				"type": "String"
			},
			{
				"name": "ResourceType",
				"type": "String"
			},
			{
				"name": "ResourceGroupName",
				"type": "String"
			},
			{
				"name": "ResourceLocation",
				"type": "String"
			},
			{
				"name": "ServiceName",
				"type": "String"
			},
			{
				"name": "Tags",
				"type": "Array"
			},
			{
				"name": "Currency",
				"type": "String"
			}
		],
		"rows": [
				17.638761136184223,
				"2023-04-01T00:00:00",
				"/subscriptions/redacted/resourcegroups/map-devtest-client-resources/providers/microsoft.containerinstance/containergroups/4f377837-d05c-47d0-8ce3-ff823f8c7d2d",
				"microsoft.containerinstance/containergroups",
				"map-devtest-client-resources",
				"US Central",
				"Container Instances",
				[
					"\"environment\":\"development\"",
					"\"managed_by\":\"prm analytics\"",
					"\"clientname\":\"client 1\"",
					"\"asset_owner\":\"tom test pc\"",
					"\"risk_level\":\"4\"",
					"\"profitcenterid\":\"fca103b4-65a3-43b6-9c86-4e34db30ca55\"",
					"\"profitcentername\":\"tom test pc\"",
					"\"clientid\":\"bdcf3688-4ede-4698-bf62-139d406536b5\"",
					"\"contentitemid\":\"0fc982f8-78e4-499f-a18c-b98efebf1752\"",
					"\"contentitemname\":\"storage test 1\"",
					"\"content_token\":\"c024c8d228e19734919f26abf7c25f5c\"",
					"\"database_id\":\"031bf686-a137-4202-8e99-3e50eb11fad8\"",
					"\"publicationrequestid\":\"4f377837-d05c-47d0-8ce3-ff823f8c7d2d\""
				],
				"USD"
			],
			[
				0.05140517698270504,
				"2023-04-01T00:00:00",
				"/subscriptions/redacted/resourcegroups/map-devtest-container-resources/providers/microsoft.containerinstance/containergroups/11b4aed3-f5ce-46ca-96db-480b5b7bb9e9",
				"microsoft.containerinstance/containergroups",
				"map-devtest-container-resources",
				"US Central",
				"Container Instances",
				[
					"\"environment\":\"development\"",
					"\"managed_by\":\"prm analytics\"",
					"\"clientname\":\"new client\"",
					"\"asset_owner\":\"tom test pc\"",
					"\"risk_level\":\"4\"",
					"\"profitcenterid\":\"fca103b4-65a3-43b6-9c86-4e34db30ca55\"",
					"\"profitcentername\":\"tom test pc\"",
					"\"clientid\":\"7cb96dd7-96fd-4673-b34c-7ced6abe307e\"",
					"\"contentitemid\":\"b4f9f2c8-6bd2-4ba2-ad8a-0c77b675984b\"",
					"\"contentitemname\":\"test\"",
					"\"content_token\":\"92d2a2f9016f05322b8bffca15b4f152\"",
					"\"database_id\":\"031bf686-a137-4202-8e99-3e50eb11fad8\"",
					"\"publicationrequestid\":\"11b4aed3-f5ce-46ca-96db-480b5b7bb9e9\""
				],
				"USD"
			]
	}
}
  
```

---
#### Feedback Bot on 7/11/2023, 03:45 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by eiriktsarpalis** [comment]
> I don’t think my JsonConverter should include this closing “}”

Custom JsonConverters are responsible for writing a complete JSON value within the serialized document. Regardless, the serializer would detect if this didn't happen throwing an exception at the end. 

We would need a minimal reproduction to understand the precise issue you are having and offer recommendations.
