### ISSUE TITLE
mono library eglib function offsetof error with 'src/mono/mono/eglib/glib.h'

### ISSUE THREAD

**Issue by microestc** [dotnet/runtime#90210]
### Description

eglib offsetof function 

```
#ifndef offsetof
#   define offsetof(s_name,n_name) (size_t)(char *)&(((s_name*)0)->m_name)
#endif
```

### Reproduction Steps

define offsetof(s_name,n_name) (size_t)(char *)&(((s_name*)0)->n_name)

### Expected behavior

none

### Actual behavior

none

**Comment by lambdageek** [comment]
@microestc What is the error?   Can you say a bit more about what you're trying to do?  What OS/platform are you building on, what exact command are you running?

**Comment by akoeplinger** [comment]
Do we even need this custom offsetof macro anymore? we can probably rely on recent compilers having it and delete it from source.
