### ISSUE TITLE
[mono][docs] Change build/run individual runtime test example

### ISSUE THREAD

**Issue by matouskozak** [dotnet/runtime#90254]
# Description
Provide a different example for building, running, and debugging of individual runtime tests for Mono Testing documentation https://github.com/dotnet/runtime/blob/main/docs/workflow/testing/mono/testing.md. The current example (`JIT/opt/InstructionCombining/DivToMul.csproj`) doesn't generate `.sh` file which could be later used to run or debug the test https://github.com/dotnet/runtime/pull/84284.

This can by "hacked" locally by adding `<RequiresProcessIsolation>True</RequiresProcessIsolation>` to the `DivToMul.csproj` file.

# Tasks
- [x] Change Mono Testing documentation https://github.com/dotnet/runtime/blob/main/docs/workflow/testing/mono/testing.md to reflect current state (https://github.com/dotnet/runtime/pull/96054)
- [x]  Investigate `mono_aot` scenario. Failure log: `The value "/**/*.dll" of the "Include" attribute in element <ItemGroup> in file ".../src/tests/build.proj (122,37)" is a wildcard that results in enumerating all files on the drive, which was likely not intended. Check that referenced properties are always defined.`. (https://github.com/dotnet/runtime/pull/96902)

**Comment by SingleAccretion** [comment]
> Do you know what am I missing?

I don't know if it is supposed to work when passed to the top-level build script (could be a bug). I do know it is supposed to work when `dotnet build`ing individual tests.
