### ISSUE TITLE
Unexpected depth mapping of Matrix4x4.CreateViewport

### ISSUE THREAD

**Issue by PavielKraskouski** [dotnet/runtime#90252]
Let's start with a code example:
``` csharp
using System.Numerics;

float fieldOfView = float.Pi / 4;
float aspectRatio = 16f / 9f;
float nearPlaneDistance = 0.1f;
float farPlaneDistance = 1000f;

Vector4 v1RH = new(5.74f, -3.26f, -nearPlaneDistance, 1);
Vector4 v1LH = new(5.74f, -3.26f, nearPlaneDistance, 1);
Vector4 v2RH = new(4.78f, 0.19f, -farPlaneDistance, 1);
Vector4 v2LH = new(4.78f, 0.19f, farPlaneDistance, 1);

Matrix4x4 perspectiveRH = Matrix4x4.CreatePerspectiveFieldOfView(fieldOfView, aspectRatio, nearPlaneDistance, farPlaneDistance);
Matrix4x4 perspectiveLH = Matrix4x4.CreatePerspectiveFieldOfViewLeftHanded(fieldOfView, aspectRatio, nearPlaneDistance, farPlaneDistance);

v1RH = Vector4.Transform(v1RH, perspectiveRH);
v1RH /= v1RH.W;
v1LH = Vector4.Transform(v1LH, perspectiveLH);
v1LH /= v1LH.W;
v2RH = Vector4.Transform(v2RH, perspectiveRH);
v2RH /= v2RH.W;
v2LH = Vector4.Transform(v2LH, perspectiveLH);
v2LH /= v2LH.W;

Console.WriteLine($"v1RH: {v1RH}");
Console.WriteLine($"v1LH: {v1LH}");
Console.WriteLine($"v2RH: {v2RH}");
Console.WriteLine($"v2LH: {v2LH}");
```
For each coordinate system (right-handed and left-handed), two points were created, lying on the near and far planes of the view frustum. The points in each pair `(v1RH, v1LH)` and `(v2RH, v2LH)` are located in the same place in three-dimensional space, while their z-coordinates have opposite signs in accordance with the direction of the z-axis of their coordinate system. Then all points were transformed from view space to NDC space using the appropriate matrices for each coordinate system.
Here is the output of the code above:
```
v1RH: <77,94891  -78,703354  0  1>
v1LH: <77,94891  -78,703354  0  1>
v2RH: <0,006491217  0,00045870052  1  1>
v2LH: <0,006491217  0,00045870052  1  1>
```
The resulting coordinates in each pair are identical. The depth of points `v1RH` and `v1LH` lying on the near plane equals `0`, and the depth of points `v2RH` and `v2LH` lying on the far plane equals `1`. These are the expected results.
Let's continue the code:
``` csharp
int x = 0;
int y = 0;
int width = 1920;
int height = 1080;
float minDepth = -10;
float maxDepth = 10;

Matrix4x4 viewportRH = Matrix4x4.CreateViewport(x, y, width, height, minDepth, maxDepth);
Matrix4x4 viewportLH = Matrix4x4.CreateViewportLeftHanded(x, y, width, height, minDepth, maxDepth);

v1RH = Vector4.Transform(v1RH, viewportRH);
v1LH = Vector4.Transform(v1LH, viewportLH);
v2RH = Vector4.Transform(v2RH, viewportRH);
v2LH = Vector4.Transform(v2LH, viewportLH);

Console.WriteLine($"v1RH: {v1RH}");
Console.WriteLine($"v1LH: {v1LH}");
Console.WriteLine($"v2RH: {v2RH}");
Console.WriteLine($"v2LH: {v2LH}");
```
This is where the conversion from NDC space to screen space takes place. The new minimum depth is set to `-10` and the new maximum depth is set to `10`.
Here is the output of the code above:
```
v1RH: <75790,95  43039,812  -10  1>
v1LH: <75790,95  43039,812  -10  1>
v2RH: <966,23157  539,7523  -30  1>
v2LH: <966,23157  539,7523  10  1>
```
Depth values in the left-handed coordinate system are as expected (`-10` and `10`), but not in the right-handed coordinate system (`-10` and `-30`). Is this expected behavior or am I misunderstanding how this matrix works for a right-handed coordinate system? In my understanding, the viewport matrix should be the same for both systems and should have the form of the current viewport matrix for the left-handed coordinate system.

**Comment by tannergooding** [comment]
You're passing in what are technically "invalid" depth ranges.

A viewport typically has its `depth` constrained to be in the range `[0, 1]` and it's typically expected that `near < far`. There are scenarios where going outside these bounds or even reversing it so that `near > far` (creating a "reverse z buffer") is desirable, and so they are not blocked, but may give unexpected behavior when done.

**Comment by PavielKraskouski** [comment]
Sorry, but I still don't understand how depth mapping works in right-handed viewport matrix. If we use left-handed viewport matrix, `[0, 1]` range maps to `[minDepth, maxDepth]` range. If we use the current implementation of right-handed viewport matrix, `[0, 1]` range maps to `[minDepth, 2 * minDepth - maxDepth]` range. Is that how it should be? In my understanding both matrices should map `[0, 1]` range to `[minDepth, maxDepth]` range.
