### ISSUE TITLE
LibraryImport cannot handle a property named "System"

### ISSUE THREAD

**Issue by mstefarov** [dotnet/runtime#90299]
### Description

If there is a property named "System" in scope where LibraryImport is used, the generated code will fail to build with error CS0120.

This is probably caused by ambiguity between "System" namespace and "System" property.  Perhaps generated code should prefix types with `global::`?

### Reproduction Steps

```cs
using System;
using System.Runtime.InteropServices;

namespace ClassLibrary1;

public partial class Class1
{
    public int System => GetSystem(out _);

    [LibraryImport("foo.dll")]
    private static partial int GetSystem(out IntPtr handle);
}
```

### Expected behavior

Generated code builds successfully.

### Actual behavior

Build fails with an error in generated code:

> LibraryImports.g.cs(10,13,10,19): error CS0120: An object reference is required for the non-static field, method, or property 'Class1.System'

### Configuration

net7.0 on Windows 10 x64, using VS 17.7.0

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky Are we missing a `global::` prefix in some case?

**Comment by jtschuster** [comment]
Looks like in SkipInit and the DllImportAttribute application we're missing it.

**Comment by AaronRobinsonMSFT** [comment]
I assume this is an easy fix.

**Comment by dotMorten** [comment]
> I assume this is an easy fix.

I just looked at the PR 😬 #Jinx
