### ISSUE TITLE
Function pointer invocation performance

### ISSUE THREAD

**Issue by hypeartist** [dotnet/runtime#90305]
Been benchmarking two ways of method calling: 

1. abstract/override (M1)
2. function pointer (M2)

Now I am confused and in a need of someone who could explain me why is that huge difference in timings since both methods seem to be resulted in very similar codegen?

| Method |       Mean |  StdDev | Ratio | Code Size | Allocated | Alloc Ratio |
|------- |-----------:|--------:|------:|----------:|----------:|------------:|
|     M1 |   460.5 ns | 1.10 ns |  1.00 |      86 B |         - |          NA |
|     M2 | 1,605.9 ns | 3.81 ns |  3.49 |      48 B |         - |          NA |

<details>
<summary>Test cases and codegen</summary>

```csharp
public class Benchmark2
{
	private Base1 _b1;
	private Base2 _b2;

	[GlobalSetup]
	public void Setup()
	{
		_b1 = new Sub1();
		_b2 = new Sub2();
	}

	[Benchmark(Baseline = true)]
	public int M1()
	{
		int r = 0;
		for (int i = 0; i < 1000; i++)
		{
			r += _b1.Method(i);
		}
		return r;
	}

	[Benchmark]
	public int M2()
	{
		int r = 0;
		for (int i = 0; i < 1000; i++)
		{
			r += _b2.Method(i);
		}
		return r;
	}
}

public abstract class Base1
{
	public abstract int Method(int a);
}

public sealed class Sub1 : Base1
{
	private int _a;

	public override int Method(int a) => a - _a;
}

public abstract unsafe class Base2
{
	private readonly delegate*<Base2, int, int> _methodPtr;

	protected Base2(delegate*<Base2, int, int> methodPtr) => _methodPtr = methodPtr;

	public int Method(int a) => _methodPtr(this, a);
}
public sealed unsafe class Sub2 : Base2
{
	private int _a;

	public Sub2() : base(&Method) { }

	private static int Method(Base2 inst, int a) => a - Unsafe.As<Base2, Sub2>(ref inst)._a;
}
```

```asm
; Method CodingLab.ParseIt.Console.Benchmark2:M1():int:this (FullOpts)
G_M000_IG01:                ;; offset=0000H
       push     rdi
       push     rsi
       push     rbx
       sub      rsp, 32
       mov      rbx, rcx

G_M000_IG02:                ;; offset=000AH
       xor      esi, esi
       xor      edi, edi

G_M000_IG03:                ;; offset=000EH
       mov      rcx, gword ptr [rbx+08H]
       mov      edx, edi
       mov      rax, qword ptr [rcx]
       mov      rax, qword ptr [rax+40H]
       call     [rax+20H]CodingLab.ParseIt.Console.Base1:Method(int):int:this ; Calling Sub1::Method (codegen below) via simple jmp stored at [rax+0x20]
       add      esi, eax
       inc      edi
       cmp      edi, 0x3E8
       jl       SHORT G_M000_IG03

G_M000_IG04:                ;; offset=002AH
       mov      eax, esi

G_M000_IG05:                ;; offset=002CH
       add      rsp, 32
       pop      rbx
       pop      rsi
       pop      rdi
       ret      
 ; END METHOD CodingLab.ParseIt.Console.Benchmark2:M1():int:this
; Total bytes of code: 52


; public sealed class Sub1 : Base1
; {
;   private int _a;
;
;	[MethodImpl(MethodImplOptions.AggressiveInlining)]
;	public override int Method(int a)
;	{
;		return a - _a;
      mov       eax,edx  
      sub       eax,dword ptr [rcx+8]  
      ret
```

```asm
; Method CodingLab.ParseIt.Console.Benchmark2:M2():int:this (FullOpts)
G_M000_IG01:                ;; offset=0000H
       push     rdi
       push     rsi
       push     rbx
       sub      rsp, 32
       mov      rbx, rcx

G_M000_IG02:                ;; offset=000AH
       xor      esi, esi
       xor      edi, edi

G_M000_IG03:                ;; offset=000EH
       mov      rcx, gword ptr [rbx+10H]
       mov      rax, qword ptr [rcx+08H]
       mov      edx, edi
       call     rax ; Calling Sub2::Method (codegen below) via simple jmp stored at rax
       add      esi, eax
       inc      edi
       cmp      edi, 0x3E8
       jl       SHORT G_M000_IG03

G_M000_IG04:                ;; offset=0026H
       mov      eax, esi

G_M000_IG05:                ;; offset=0028H
       add      rsp, 32
       pop      rbx
       pop      rsi
       pop      rdi
       ret      
 ; END METHOD CodingLab.ParseIt.Console.Benchmark2:M2():int:this
; Total bytes of code: 48

; public sealed unsafe class Sub2 : Base2
; {
;	private int _a;
;
;	public Sub2() : base(&Method) {}
;
;	private static int Method(Base2 inst, int a)
;	{
;		return a - Unsafe.As<Base2, Sub2>(ref inst)._a;
      mov       eax,edx  
      sub       eax,dword ptr [rcx+10h]  
      ret
```

</details>

**Comment by jkotas** [comment]
> why is that huge difference in timings since both methods seem to be resulted in very similar codegen?

The function pointer goes through an extra indirection. You should be able to see the extra indirection if you step through the assembly code in the debugger.

The indirection is necessary to account for the actual method code changing over time due to tiered compilation. The runtime will back-patch the virtual method slot with the more direct method pointer as this is happening, so the virtual method will avoid the indirection. 

This backpatching is not possible with function pointers. The runtime has no idea about all places where you could have stored the function pointer. It means that the function pointer always pays for the extra indirection.

**Comment by jkotas** [comment]
The large difference should go away if you run your microbenchmark with native AOT. Every method has one and only code pointer with native AOT and so the indirection for the function pointer is not necessary there.

**Comment by hypeartist** [comment]
> The function pointer goes through an extra indirection. You should be able to see the extra indirection if you step through the assembly code in the debugger.

Well, stepping inside assembly code in debugger I see that virtual method call goes thru same one indirection (as I pointed it out in comment `Calling Sub1::Method (codegen below) via simple jmp stored at [rax+0x20]`)

**Comment by jkotas** [comment]
It takes some time for the back-patching to occur. Do you see that indirection even after the code has been running for a while?

**Comment by jkotas** [comment]
>I'm not using TC:

Without TC, the indirection is still necessary for the function pointer to account for lazy JITing. All methods are JITed lazily. It means that function pointer that you get may be pointing to a stub if the method was not JITed yet.

**Comment by MichalPetryka** [comment]
> The function pointer goes through an extra indirection.

Doesn't the overhead from the jump stub here seem a bit too big here though?

**Comment by jkotas** [comment]
Chains of indirect calls and jumps are expensive when you compare them to ordinary instructions or method that does close to nothing. They are not friendly to modern processor pipelines. It is also an area with a lot of variation between Intel/Amd/Arm and between different processor generations.
