### ISSUE TITLE
Tracking issue for "WORKLOAD TIMED OUT"

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#90309]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=368974
Build error leg or test failing: 
Pull request: https://github.com/dotnet/runtime/pull/90119

## Error Message

```json
{
  "ErrorMessage": "ERROR: WORKLOAD TIMED OUT - Killing user command",
  "BuildRetry": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=368974
**Error message validated:** `ERROR: WORKLOAD TIMED OUT - Killing user command`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 8/10/2023 1:38:38 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[749807](https://dev.azure.com/dnceng-public/public/_build/results?buildId=749807)|dotnet/runtime|[iOS.Device.LibraryMode.Test.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=749807&view=ms.vss-test-web.build-test-results-tab&runId=18978680&resultId=109449)|dotnet/runtime#105233|
|[748937](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748937)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748937&view=ms.vss-test-web.build-test-results-tab&runId=18945512&resultId=100001)|dotnet/runtime#103585|
|[748618](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748618)|dotnet/runtime|[System.Numerics.Tensors.Net8.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748618&view=ms.vss-test-web.build-test-results-tab&runId=18934746&resultId=186704)||
|[748590](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748590)|dotnet/runtime|[iOS.Device.Aot.Test.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748590&view=ms.vss-test-web.build-test-results-tab&runId=18934078&resultId=109449)||
|[748320](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748320)|dotnet/runtime|[iOS.Device.Aot.Test.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748320&view=ms.vss-test-web.build-test-results-tab&runId=18924390&resultId=109449)|dotnet/runtime#105167|
|[747478](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747478)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747478&view=ms.vss-test-web.build-test-results-tab&runId=18918292&resultId=100001)|dotnet/runtime#103585|
|[748081](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748081)|dotnet/runtime|[iOS.Device.ExportManagedSymbols.Test.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748081&view=ms.vss-test-web.build-test-results-tab&runId=18915214&resultId=110257)||
|[747944](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747944)|dotnet/runtime|[iOS.Device.ExportManagedSymbols.Test.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747944&view=ms.vss-test-web.build-test-results-tab&runId=18912340&resultId=109449)|dotnet/runtime#105153|
|[747724](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747724)|dotnet/runtime|[iOS.Device.ExportManagedSymbols.Test.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747724&view=ms.vss-test-web.build-test-results-tab&runId=18906404&resultId=109330)|dotnet/runtime#104962|
|[747439](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747439)|dotnet/runtime|[System.Numerics.Tensors.Net8.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747439&view=ms.vss-test-web.build-test-results-tab&runId=18896282&resultId=186645)||
|[746875](https://dev.azure.com/dnceng-public/public/_build/results?buildId=746875)|dotnet/runtime|[iOS.Device.LibraryMode.Test.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=746875&view=ms.vss-test-web.build-test-results-tab&runId=18881494&resultId=109449)|dotnet/runtime#104856|
|[746673](https://dev.azure.com/dnceng-public/public/_build/results?buildId=746673)|dotnet/runtime|[iOS.Device.ExportManagedSymbols.Test.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=746673&view=ms.vss-test-web.build-test-results-tab&runId=18875548&resultId=109449)|dotnet/runtime#104848|
|[746336](https://dev.azure.com/dnceng-public/public/_build/results?buildId=746336)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=746336&view=ms.vss-test-web.build-test-results-tab&runId=18871120&resultId=100001)|dotnet/runtime#103585|
|[746053](https://dev.azure.com/dnceng-public/public/_build/results?buildId=746053)|dotnet/runtime|[iOS.Device.ExportManagedSymbols.Test.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=746053&view=ms.vss-test-web.build-test-results-tab&runId=18857048&resultId=109449)|dotnet/runtime#103755|
|[745979](https://dev.azure.com/dnceng-public/public/_build/results?buildId=745979)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=745979&view=ms.vss-test-web.build-test-results-tab&runId=18854214&resultId=100001)|dotnet/runtime#103585|
|[745513](https://dev.azure.com/dnceng-public/public/_build/results?buildId=745513)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=745513&view=ms.vss-test-web.build-test-results-tab&runId=18840428&resultId=100001)|dotnet/runtime#103585|
|[743450](https://dev.azure.com/dnceng-public/public/_build/results?buildId=743450)|dotnet/runtime|[JIT_opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=743450&view=ms.vss-test-web.build-test-results-tab&runId=18783480&resultId=100051)||
|[743225](https://dev.azure.com/dnceng-public/public/_build/results?buildId=743225)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=743225&view=ms.vss-test-web.build-test-results-tab&runId=18773630&resultId=100001)|dotnet/runtime#103585|
|[743222](https://dev.azure.com/dnceng-public/public/_build/results?buildId=743222)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=743222&view=ms.vss-test-web.build-test-results-tab&runId=18773374&resultId=100001)|dotnet/runtime#103585|
|[740287](https://dev.azure.com/dnceng-public/public/_build/results?buildId=740287)|dotnet/runtime|[System.Numerics.Tensors.Net8.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=740287&view=ms.vss-test-web.build-test-results-tab&runId=18679128&resultId=186585)||
|[739967](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739967)|dotnet/runtime|[JIT_opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739967&view=ms.vss-test-web.build-test-results-tab&runId=18675538&resultId=100049)||
|[739577](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739577)|dotnet/runtime|[Loader_classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739577&view=ms.vss-test-web.build-test-results-tab&runId=18667764&resultId=100059)||
|[739539](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739539)|dotnet/runtime|[Loader_classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739539&view=ms.vss-test-web.build-test-results-tab&runId=18666990&resultId=100057)||
|[737515](https://dev.azure.com/dnceng-public/public/_build/results?buildId=737515)|dotnet/runtime|[JIT_opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=737515&view=ms.vss-test-web.build-test-results-tab&runId=18624056&resultId=100051)||
|[735679](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735679)|dotnet/runtime|[System.Numerics.Tensors.Net8.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735679&view=ms.vss-test-web.build-test-results-tab&runId=18538836&resultId=186520)||
|[735671](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735671)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735671&view=ms.vss-test-web.build-test-results-tab&runId=18538532&resultId=100001)|dotnet/runtime#103585|
|[735197](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735197)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735197&view=ms.vss-test-web.build-test-results-tab&runId=18528332&resultId=178296)||
|[734188](https://dev.azure.com/dnceng-public/public/_build/results?buildId=734188)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=734188&view=ms.vss-test-web.build-test-results-tab&runId=18486422&resultId=186146)||
|[727973](https://dev.azure.com/dnceng-public/public/_build/results?buildId=727973)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=727973&view=ms.vss-test-web.build-test-results-tab&runId=18301960&resultId=178294)||
|[728292](https://dev.azure.com/dnceng-public/public/_build/results?buildId=728292)|dotnet/runtime|[JIT_opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=728292&view=ms.vss-test-web.build-test-results-tab&runId=18300706&resultId=100049)||
|[727276](https://dev.azure.com/dnceng-public/public/_build/results?buildId=727276)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=727276&view=ms.vss-test-web.build-test-results-tab&runId=18265178&resultId=186085)||
|[721722](https://dev.azure.com/dnceng-public/public/_build/results?buildId=721722)|dotnet/runtime|[System.ValueTuple.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=721722&view=ms.vss-test-web.build-test-results-tab&runId=18106474&resultId=185978)||
|[720435](https://dev.azure.com/dnceng-public/public/_build/results?buildId=720435)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=720435&view=ms.vss-test-web.build-test-results-tab&runId=18064930&resultId=100001)|dotnet/runtime#102403|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|19|33|

**Comment by steveisok** [comment]
This is a variation of https://github.com/dotnet/runtime/issues/82637

**Comment by steveisok** [comment]
@akoeplinger something is wrong w/ our classification when there is a crash in a test suite. Check out https://dev.azure.com/dnceng-public/public/_build/results?buildId=494600&view=ms.vss-test-web.build-test-results-tab&runId=11481726&resultId=179767 for example. The net.dot log is huge (350MB) and seems to be logging a crash over and over again.

**Comment by akoeplinger** [comment]
The classification itself is correct, we're timing out because of the loop which logs the crash. I see a potential reason for this, discussing it on Discord.

**Comment by matouskozak** [comment]
Closing this issue because the error message is too general and is matching all kinds of failures (see https://github.com/dotnet/xharness/issues/1188).
