### ISSUE TITLE
PlatformNotSupportedException  thrown for System.ComponentModel.TypeDescriptor.NodeFor

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#90311]
Error when running `/azp run runtime-extra-platforms`
windows.10.amd64.android.open

Several errors like:
```
  Starting:    System.ComponentModel.TypeConverter.Tests (parallel test collections = on, max threads = 2)
    System.ComponentModel.Tests.PropertyDescriptorTests.PropertyDescriptorCanBeCreatedThatAccessesNonPublicPropertyOnAssociatedDesigner [FAIL]
      System.PlatformNotSupportedException : Operation is not supported on this platform.
      Stack Trace:
        /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs(1545,0): at System.ComponentModel.TypeDescriptor.NodeFor(Object instance, Boolean createDelegator)
        /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs(1509,0): at System.ComponentModel.TypeDescriptor.NodeFor(Object instance)
        /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs(892,0): at System.ComponentModel.TypeDescriptor.GetDescriptor(Object component, Boolean noCustomTypeDesc)
        /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs(1299,0): at System.ComponentModel.TypeDescriptor.GetPropertiesImpl(Object component, Attribute[] attributes, Boolean noCustomTypeDesc, Boolean noAttributes)
        /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs(1242,0): at System.ComponentModel.TypeDescriptor.GetProperties(Object component, Boolean noCustomTypeDesc)
        /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs(1232,0): at System.ComponentModel.TypeDescriptor.GetProperties(Object component)
        /_/src/libraries/System.ComponentModel.TypeConverter/tests/PropertyDescriptorTests.cs(221,0): at System.ComponentModel.Tests.PropertyDescriptorTests.PropertyDescriptorCanBeCreatedThatAccessesNonPublicPropertyOnAssociatedDesigner()
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.Mono.cs(22,0): at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(57,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=368974
Build error leg or test failing: 
Pull request: https://github.com/dotnet/runtime/pull/90119

## Error Message
```json
{
  "ErrorMessage": "at System.ComponentModel.TypeDescriptor.NodeFor",
  "BuildRetry": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=368974
**Error message validated:** `at System.ComponentModel.TypeDescriptor.NodeFor`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 8/10/2023 1:46:54 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[374116](https://dev.azure.com/dnceng-public/public/_build/results?buildId=374116)|dotnet/runtime|[System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.CanExport](https://dev.azure.com/dnceng-public/public/_build/results?buildId=374116&view=ms.vss-test-web.build-test-results-tab&runId=7952144&resultId=171016)||
|[373453](https://dev.azure.com/dnceng-public/public/_build/results?buildId=373453)|dotnet/runtime|[System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.CanExport](https://dev.azure.com/dnceng-public/public/_build/results?buildId=373453&view=ms.vss-test-web.build-test-results-tab&runId=7932386&resultId=159220)||
|[373115](https://dev.azure.com/dnceng-public/public/_build/results?buildId=373115)|dotnet/runtime|[System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.Export](https://dev.azure.com/dnceng-public/public/_build/results?buildId=373115&view=ms.vss-test-web.build-test-results-tab&runId=7925228&resultId=171427)|dotnet/runtime#90519|
|[372849](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372849)|dotnet/runtime|[System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.Export](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372849&view=ms.vss-test-web.build-test-results-tab&runId=7919276&resultId=172161)|dotnet/runtime#90519|
|[372550](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372550)|dotnet/runtime|[System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.CanExport](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372550&view=ms.vss-test-web.build-test-results-tab&runId=7912582&resultId=169518)||
|[372445](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372445)|dotnet/runtime|[System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.CanExport](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372445&view=ms.vss-test-web.build-test-results-tab&runId=7908646&resultId=172515)|dotnet/runtime#90270|
|[372307](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372307)|dotnet/runtime|[System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.Export](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372307&view=ms.vss-test-web.build-test-results-tab&runId=7903972&resultId=172250)||
|[372186](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372186)|dotnet/runtime|[System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.CanExport](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372186&view=ms.vss-test-web.build-test-results-tab&runId=7899988&resultId=172325)||
|[372071](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372071)|dotnet/runtime|[System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.Export](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372071&view=ms.vss-test-web.build-test-results-tab&runId=7896140&resultId=172241)||
|[371961](https://dev.azure.com/dnceng-public/public/_build/results?buildId=371961)|dotnet/runtime|[System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.CanExport](https://dev.azure.com/dnceng-public/public/_build/results?buildId=371961&view=ms.vss-test-web.build-test-results-tab&runId=7893098&resultId=172074)|dotnet/runtime#90023|
|[371811](https://dev.azure.com/dnceng-public/public/_build/results?buildId=371811)|dotnet/runtime|[System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.CanExport](https://dev.azure.com/dnceng-public/public/_build/results?buildId=371811&view=ms.vss-test-web.build-test-results-tab&runId=7889786&resultId=172272)||
|[371518](https://dev.azure.com/dnceng-public/public/_build/results?buildId=371518)|dotnet/runtime|[System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.Export](https://dev.azure.com/dnceng-public/public/_build/results?buildId=371518&view=ms.vss-test-web.build-test-results-tab&runId=7883682&resultId=149626)||
|[371313](https://dev.azure.com/dnceng-public/public/_build/results?buildId=371313)|dotnet/runtime|[System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.Export](https://dev.azure.com/dnceng-public/public/_build/results?buildId=371313&view=ms.vss-test-web.build-test-results-tab&runId=7879790&resultId=172100)|dotnet/runtime#90413|
|[370857](https://dev.azure.com/dnceng-public/public/_build/results?buildId=370857)|dotnet/runtime|[System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.Export](https://dev.azure.com/dnceng-public/public/_build/results?buildId=370857&view=ms.vss-test-web.build-test-results-tab&runId=7868352&resultId=149575)||
|[370244](https://dev.azure.com/dnceng-public/public/_build/results?buildId=370244)|dotnet/runtime|[System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.Export](https://dev.azure.com/dnceng-public/public/_build/results?buildId=370244&view=ms.vss-test-web.build-test-results-tab&runId=7856508&resultId=161278)||
|[369565](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369565)|dotnet/runtime|[System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.Export](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369565&view=ms.vss-test-web.build-test-results-tab&runId=7850642&resultId=171443)|dotnet/runtime#90304|
|[369870](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369870)|dotnet/runtime|[System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.CanExport](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369870&view=ms.vss-test-web.build-test-results-tab&runId=7849258&resultId=172312)|dotnet/runtime#89712|
|[369604](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369604)|dotnet/runtime|[System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.Export](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369604&view=ms.vss-test-web.build-test-results-tab&runId=7840440&resultId=171973)|dotnet/runtime#90150|
|[369496](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369496)|dotnet/runtime|[System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.Export](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369496&view=ms.vss-test-web.build-test-results-tab&runId=7836780&resultId=172219)||
|[369482](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369482)|dotnet/runtime|[System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.Export](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369482&view=ms.vss-test-web.build-test-results-tab&runId=7836402&resultId=167231)|dotnet/runtime#90298|
|[369160](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369160)|dotnet/runtime|[System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.CanExport](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369160&view=ms.vss-test-web.build-test-results-tab&runId=7829094&resultId=158834)|dotnet/runtime#90199|
|[368974](https://dev.azure.com/dnceng-public/public/_build/results?buildId=368974)|dotnet/runtime|[System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.Export](https://dev.azure.com/dnceng-public/public/_build/results?buildId=368974&view=ms.vss-test-web.build-test-results-tab&runId=7826116&resultId=161006)|dotnet/runtime#90119|
|[368875](https://dev.azure.com/dnceng-public/public/_build/results?buildId=368875)|dotnet/runtime|[System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.Export](https://dev.azure.com/dnceng-public/public/_build/results?buildId=368875&view=ms.vss-test-web.build-test-results-tab&runId=7819702&resultId=167138)||
|[368230](https://dev.azure.com/dnceng-public/public/_build/results?buildId=368230)|dotnet/runtime|[System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.CanExport](https://dev.azure.com/dnceng-public/public/_build/results?buildId=368230&view=ms.vss-test-web.build-test-results-tab&runId=7801898&resultId=167448)|dotnet/runtime#90184|
|[368204](https://dev.azure.com/dnceng-public/public/_build/results?buildId=368204)|dotnet/runtime|[System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.CanExport](https://dev.azure.com/dnceng-public/public/_build/results?buildId=368204&view=ms.vss-test-web.build-test-results-tab&runId=7800764&resultId=149644)|dotnet/runtime#90225|
|[367894](https://dev.azure.com/dnceng-public/public/_build/results?buildId=367894)|dotnet/runtime|[System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.CanExport](https://dev.azure.com/dnceng-public/public/_build/results?buildId=367894&view=ms.vss-test-web.build-test-results-tab&runId=7791350&resultId=171935)|dotnet/runtime#90150|
|[362691](https://dev.azure.com/dnceng-public/public/_build/results?buildId=362691)|dotnet/runtime|[System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.Export](https://dev.azure.com/dnceng-public/public/_build/results?buildId=362691&view=ms.vss-test-web.build-test-results-tab&runId=7662990&resultId=153547)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|3|26|27|

**Comment by ericstj** [comment]
@JeremyKuhne it looks like this is regression from https://github.com/dotnet/runtime/commit/f43b0c124c2018b7b0fa8be0e173280ebc8031c7

https://github.com/dotnet/runtime/blob/26ae09784c16dfa6707cd73eca2aeb00a28741d0/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs#L1545-L1546

Looks like these are running Mono on Windows.  I guess mono runtime doesn't implement this.  Can we get this condition updated to exclude Mono runtime?

**Comment by ericstj** [comment]
Let's just wrap `TryGetComInstance` in a try/catch(PNSE)
