### ISSUE TITLE
Should we consider sealed the newly introduced attributes for keyed service

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/runtime#90321]
We introduced `ServiceKeyAttribute` and `FromKeyedServicesAttribute` for keyed service, while they are not sealed, and there're no inherits from the repo search result, since they're new types introduced, should we consider making them sealed?

From the `sealed` proposal https://github.com/dotnet/runtime/issues/49944, we may prefer `sealed` for these types

keyed service PR: https://github.com/dotnet/runtime/pull/87183

code search result:
https://github.com/search?q=repo%3Adotnet%2Fruntime%20ServiceKeyAttribute&type=code
https://github.com/search?q=repo%3Adotnet%2Fruntime%20FromKeyedServicesAttribute&type=code

**Comment by WeihanLi** [comment]
@ericstj  thank you very much

**Comment by benjaminpetit** [comment]
By allowing inheritance on `FromKeyedServicesAttribute`, we allow people to use complex object as the key.

Here is an example:

``` csharp
public class CustomKey
{
    public CustomKey(int n, string str)
    {
        N = n;
        Str = str;
    }

    public int N { get; }
    public string Str { get; }
}

public sealed class FromServicesWithCustomKey : FromKeyedServicesAttribute
{
    public FromServicesWithCustomKey(int n, string str)
        : base(new CustomKey(n, str))
    {
    }
}

public class CustomService
{
    private readonly CustomKey _key;

    public CustomService([ServiceKey] CustomKey key)
    {
        _key = key;
    }

    public int N => _key.N;
    public string Str => _key.Str;
}

[Fact]
public void InheritanceTest()
{
    var serviceCollection = new ServiceCollection();
    serviceCollection.AddKeyedTransient<CustomService>(KeyedService.AnyKey);

    var provider = CreateServiceProvider(serviceCollection);

    var service = provider.GetKeyedService<CustomService>(new CustomKey(12, "hello"));

    Assert.Equal(12, service.N);
    Assert.Equal("hello", service.Str);
}
```
