### ISSUE TITLE
[hot reload] Could not parse field signature 0a0008a9 due to: Could not resolve type with token 010001f3 from typeref

### ISSUE THREAD

**Issue by Drammy** [dotnet/runtime#90332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I make a small change in my blazor wasm app, say just a minor change to the class attribute of an html element, `dotnet watch` fails and I get a series of exceptions like that shown below.

I'd at least appreciate some pointers on how to understand the exception and find the cause myself.

### Expected Behavior

I'd expect the simple change to the class attribute to not result in an exception and to instead result in a quick change of the DOM in the web browser page.

At the very least I'd hope that the exception provides me with some information to help find the cause of the problem.

### Exceptions (if any)

    crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
        Unhandled exception rendering component: Field not found: Microsoft.AspNetCore.Components.EventCallback.0_10 Due to: Could not parse field signature 0a0008a9 due to: Could not resolve type with token 010001f3 from typeref (expected class 'Microsoft.AspNetCore.Components.<Main>$' in assembly 'Microsoft.AspNetCore.Components, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60') assembly:Microsoft.AspNetCore.Components, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 type:Microsoft.AspNetCore.Components.<Main>$ member:(null)
        System.MissingFieldException: Field not found: Microsoft.AspNetCore.Components.EventCallback.0_10 Due to: Could not parse field signature 0a0008a9 due to: Could not resolve type with token 010001f3 from typeref (expected class 'Microsoft.AspNetCore.Components.<Main>$' in assembly 'Microsoft.AspNetCore.Components, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60') assembly:Microsoft.AspNetCore.Components, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 type:Microsoft.AspNetCore.Components.<Main>$ member:(null)
        at Fusion.Client.Pages.Browse.Components.DocumentViewer.DocumentNavigator.BuildRenderTree(RenderTreeBuilder __builder)
        at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
        at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)

### .NET Version

7.0.304

### Anything else?

Developing in latest Rider on the latest MacOS.

**Comment by lambdageek** [comment]
@Drammy Can you give a short razor example of the kind of change you're making, I'm not entirely sure what you mean by "say just a minor change to the class attribute of an html element".   Is the html element in the child content of a parent component?  are you changing the class attribute by assigning some literal value or some C# or Blazor expression?

Something like this works for me (this is Counter.razor from the `dotnet new blazorwasm` template):

Pages/Counter.razor before:
```csharp
<p role="status">Current count: @currentCount</p>
```

Pages/Counter.razor after:
```csharp
<p role="status" class="myClass">Current count: @currentCount</p>
```

**Comment by Drammy** [comment]
Yes changing the value of the class attribute causes the hot reload failure, but so do other changes to the razor files.  The class value change was just a simple example.  We're using tailwind so changing a tailwind class can be sufficient to cause hot reload to fail and generate the above exceptions.

I cannot replicate the issue in the `dotnet new blazorwasm` template.

Unfortunately, hot reload degraded slowly over time as our solution grew more complex to the point where it now fails after the first change after a fresh `dotnet watch`.

**Comment by lambdageek** [comment]
> Yes changing the value of the class attribute causes the hot reload failure, but so do other changes to the razor files. The class value change was just a simple example. We're using tailwind so changing a tailwind class can be sufficient to cause hot reload to fail and generate the above exceptions.
> 
> I cannot replicate the issue in the `dotnet new blazorwasm` template.
> 
> Unfortunately, hot reload degraded slowly over time as our solution grew more complex to the point where it now fails after the first change after a fresh `dotnet watch`.

@drammy thanks for the info.  Can you show me a razor snippet that doesn't reload properly? It doesn't have to be self-contained, but if you're using razor components, I'd like to see all the parent elements in the razor markup.  If you're using components that have ChildContent or some templated components, that is probably relevant.

**Comment by lambdageek** [comment]
Notes:

The error message

```
System.MissingFieldException: Field not found: Microsoft.AspNetCore.Components.EventCallback.0_10 Due to: Could not parse field signature 0a0008a9 due to: Could not resolve type with token 010001f3 from typeref (expected class 'Microsoft.AspNetCore.Components.<Main>$' in assembly 'Microsoft.AspNetCore.Components, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60') assembly:Microsoft.AspNetCore.Components, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 type:Microsoft.AspNetCore.Components.<Main>$ member:(null)
    at Fusion.Client.Pages.Browse.Components.DocumentViewer.DocumentNavigator.BuildRenderTree(RenderTreeBuilder __builder)
    at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
```

is pretty confusing to the point where I think hot reload is computing string heap lookups incorrectly.

The name `Microsoft.AspNetCore.Components.<Main>$` is weird: `Microsoft.AspNetCore.Components` is a namespace, and `<Main>$` is a method name that Roslyn normally synthesizes for toplevel statements.  This would mean a `Components.cs` with toplevel statements???

Similarly, `Microsoft.AspNetCore.Components.EventCallback.0_10` is a member called `0_10` inside a class called `Microsoft.AspNetCore.Components.EventCallback` - but `0_10` is a very strange name for a synthesized member
(a name like `g__Foo|0_0` might be created for a nested function, but not just a plain `0_10`).

The token values look reasonable - `0x0a0008a9` is a MemberRef token which makes sense for a field, and `0x010001f3` is a TypeRef.  But the names make no sense at all.

**Comment by Drammy** [comment]
> @Drammy thanks for the info. Can you show me a razor snippet that doesn't reload properly? It doesn't have to be self-contained, but if you're using razor components, I'd like to see all the parent elements in the razor markup. If you're using components that have ChildContent or some templated components, that is probably relevant.

It's not one specific razor file; I can open any razor file and make a minor change to cause the issue.

I'm afraid I'm on annual leave atm and won't be back until early September.  I can try and provide some more details as soon as I'm back from my travels.

**Comment by lambdageek** [comment]
@drammy thanks for the update.  This gives me enough to try some things for now.  Enjoy your time off.

**Comment by lambdageek** [comment]
Can't repro with Tailwind Play CDN. Editing the MainLayout.razor file to change the class on some layout divs works as expected.  I'll try the Tailwind CLI, too...

**Comment by Drammy** [comment]
I can't repro it with a starter solution either.

Our is application is complicated and it worked fine until a point and now fails constantly.  I'd be happy to be told that something we've done has caused the issue.  The main problem is that the error messaging doesn't help us to find the cause or point us in the right direction to start investigating.

Is there anything we can do to improve our chances of finding the culprit?

**Comment by lambdageek** [comment]
@Drammy 

>  The main problem is that the error messaging doesn't help us to find the cause or point us in the right direction to start investigating.
> Is there anything we can do to improve our chances of finding the culprit?

Things will get better in .NET 8 - Blazor apps will be able to customize how the runtime is started and turn on additional diagnostics.  Unfortunately in .NET 7 those options aren't exposed for Blazor apps.

However here is a custom build of the .NET 7 WebAssembly runtime that has adidtional hot reload logging turned on

[Microsoft.NETCore.App.Runtime.Mono.browser-wasm.zip](https://github.com/dotnet/runtime/files/12819970/Microsoft.NETCore.App.Runtime.Mono.browser-wasm.zip)

please unzip this file and the **unzip the contained .nupkg file** to overwrite the nuget cache (on my mac it is in `~/.nuget/packages/microsoft.netcore.app.runtime.mono.browser-wasm/7.0.11` - On Windows it will be in `%userprofile%\.nuget\packages\microsoft.netcore.app.runtime.mono.browser-wasm\7.0.11`).

After that, rebuild your app and run it in debug mode with hot reload enabled.  Clear the browser Application cache (in the developer tools window on the "Application" tab) and reload.  Then, applying a change with hot reload you should be able to see output like this in the browser Console:

```
LOADING basename=(null) delta update.
blazor.webassembly.js:1 delta image=0x1c4cfa0 & dil=0x1c4d1e8
dotnet.7.0.11.03ul0vs24v.js:5 [MONO] delta image size 0x00000238, delta IL size 0x00000015

dotnet.7.0.11.03ul0vs24v.js:5 [MONO] base image string size: 0x00000ccc
dotnet.7.0.11.03ul0vs24v.js:5 [MONO] base image user string size: 0x00000e8c
dotnet.7.0.11.03ul0vs24v.js:5 [MONO] base image blob heap addr: 0x14a3d98
dotnet.7.0.11.03ul0vs24v.js:5 [MONO] base image blob heap size: 0x000004cc
dotnet.7.0.11.03ul0vs24v.js:5 [MONO] Image 'data-0x3724328' has a minimal delta marker
...
```

followed by additional details.  Near the end it shoudl say something like

```
[MONO] >>> EnC delta for base=(null) (generation 1) applied
```

If you could collect this console output and send it here (or email me - there might be method or class names in the output that are proprietary to your app) we can investigate further.

**Comment by Drammy** [comment]
Thanks for getting back to me @lambdageek but unfortunately I've not been able to generate the output you described.

I've done the following:
1. Downloaded the link you posted
2. Unzipped it and placed into `~/.nuget/packages/microsoft.netcore.app.runtime.mono.browser-wasm/7.0.11`, whilst removing the existing `microsoft.netcore.app.runtime.mono.browser-wasm.7.0.11.nupkg` file
3. Edited my appsettings.json file - `"debugMode": true`
4. Within my rider IDE, I opened the terminal and ran `dotnet watch`
5. I opened the browser (safari) and removed the session storage, I then disabled cache in the network settings (
![image](https://github.com/dotnet/runtime/assets/5029037/c1bf34a3-2e00-4fbf-8e21-7fe067a7c770)) and loaded the wasm application
6. I recreated the original, reported issue and saw the problem manifest itself but didn't see any of the output you were expecting me to see.

Any ideas what I might be doing wrong?

**Comment by lambdageek** [comment]
> 1. Downloaded the link you posted
> 2. Unzipped it and placed into `~/.nuget/packages/microsoft.netcore.app.runtime.mono.browser-wasm/7.0.11`, whilst removing the existing `microsoft.netcore.app.runtime.mono.browser-wasm.7.0.11.nupkg` file

> Any ideas what I might be doing wrong?

@Drammy sorry. github doesn't allow me to just upload a .nupkg file, so it had to be inside a zip.

What I meant is to do this:

1. unzip the .zip file and take the .nupkg file that is in there and put it somewhere.
2. unzip the .nupkg file itself so that it overwrites the contents of `~/.nuget/packages/microsoft.netcore.app.runtime.mono.browser-wasm/7.0.11`

in particular the dotnet.wasm and dotnet.js files inside the .nupkg should overwrite the ones in `~/.nuget/packages/microsoft.netcore.app.runtime.mono.browser-wasm/7.0.11/runtimes/browser-wasm/native/`

**Comment by Drammy** [comment]
@lambdageek Thanks for the help and I've followed the steps you provided but I'm still not seeing any output of the kind you described.

A filter in the browser console for `[MONO]` finds nothing at all.  Are steps 3 onwards correct?

3. Edited my appsettings.json file - "debugMode": true
4. Within my rider IDE, I opened the terminal and ran dotnet watch
5. I opened the browser (safari) and removed the session storage, I then disabled cache in the network settings and loaded the wasm application
6. I recreated the original, reported issue and saw the problem manifest itself but didn't see any of the output you were expecting me to see.

**Comment by lambdageek** [comment]
> @lambdageek Thanks for the help and I've followed the steps you provided but I'm still not seeing any output of the kind you described.
> 
> A filter in the browser console for `[MONO]` finds nothing at all. Are steps 3 onwards correct?
> 
> 3. Edited my appsettings.json file - "debugMode": true
> 4. Within my rider IDE, I opened the terminal and ran dotnet watch
> 5. I opened the browser (safari) and removed the session storage, I then disabled cache in the network settings and loaded the wasm application
> 6. I recreated the original, reported issue and saw the problem manifest itself but didn't see any of the output you were expecting me to see.

Yea this seems correct.

Questions:

* did you upgrade to .NET 7.0.12 by any chance? it's possible we are overwriting the wrong ~/.nuget/packages folder
* is the browser console filter set to show all output levels: Verbose, Info, Warnings and Errors?

**Comment by Drammy** [comment]
I've not installed the 7.0.12 release yet.  `dotnet --info` reports `7.0.11` for the runtime and `7.0.401` for the sdk.

This is the directory I replaced (it has been put back to its original state)
![image](https://github.com/dotnet/runtime/assets/5029037/b6a1fd07-bd6f-40be-b7d3-b8610f774882)

I'm using Safari (also tested in Chrome with no difference) but yes the browser console filter is set to show every level.

**Comment by lambdageek** [comment]
Strange. that should've done it.  Can you try deleting your `bin` and `obj` folders and building again from scratch.

By the way, thank you so much for continuing to help out with diagnosing this issue

**Comment by lambdageek** [comment]
Oh, just thought of one other possibility: what do you have in `/usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.browser-wasm/` ? Is there a 7.0.11 folder in there, too?  Could you try overwriting the contents of that 7.0.11 folder with the nuget contents.  (Note: this is fairly dangerous and you will probably need to delete `/usr/local/share/dotnet` and re-install it to clean everything up).

**Comment by Drammy** [comment]
There's only a 7.0.3 folder in `/usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.browser-wasm/`

**Comment by Drammy** [comment]
An update... since deleting the `bin` and `obj` folders I cannot recreate the issue..

I will post an update if it returns but unfortunately atm I'm now unable to recreate
