### ISSUE TITLE
Exception on `MakeGenericMethod` called on a static interface method from `GetInterfaceMap`'s `TargetMethods`

### ISSUE THREAD

**Issue by hamarb123** [dotnet/runtime#90351]
### Description

**_This issue is for adding the tests, see Other information_**

When you use `MakeGenericMethod` on a static generic method, which comes from `GetInterfaceMap`'s `TargetMethods`, it throws an `InvalidOperationException`. It doesn't throw when you get the method directly from the type.

Gotta love static interface methods :)

Originally found by @Joe4evr on the C# discord, just thought I'd report it so it doesn't get lost.

### Reproduction Steps

```csharp
using System;
using System.Linq;
using System.Reflection;
public class C
{
    public static void Main()
    {
        var x1 = typeof(C1).GetMethod("I1.A", (BindingFlags)(-1));
        var x2 = typeof(C1).GetInterfaceMap(typeof(I1)).TargetMethods.Single((x) => x.Name == "I1.A"); //doesn't occur on InterfaceMethods
        Console.WriteLine(x1.MakeGenericMethod(typeof(int)).ContainsGenericParameters);
        Console.WriteLine(x2.MakeGenericMethod(typeof(int)).ContainsGenericParameters); //exception is here (on call to MakeGenericMethod)
    }
}

public interface I1
{
    static abstract void A<T>();
}

public class C1 : I1
{
    static void I1.A<T>() { } //doesn't need to be an explicit implementation
}
```

### Expected behavior

Prints:
```
False
False
```

### Actual behavior

Prints:
```
False
Exception
System.InvalidOperationException: Void I1.A[T]() is not a GenericMethodDefinition. MakeGenericMethod may only be called on a method for which MethodBase.IsGenericMethodDefinition is true.
   at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
   at C.Main()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### Configuration

I tested this in sharplab.io
I have also reproduced locally on macOS 13.4.1 x64 with .NET 7.0.10

### Other information

The above described issue was fixed with other changes. This issue is now for adding tests to ensure we do not regress.
I also found another instance of the original issue: https://github.com/dotnet/runtime/issues/90351#issuecomment-1676179889.

**Comment by ericstj** [comment]
Thank you for the report.  This appears to be an existing bug - I can repro on 7.0 as well.  Moving this to 9.0.0 for us to fix

**Comment by Joe4evr** [comment]
@hamarb123 You were a bit quick on the draw here. This seems to already be fixed [in the nightly builds (rc1)](https://github.com/dotnet/installer#table).

**Comment by jkotas** [comment]
Yes, this appears to be fixed as part of other fixes for static methods. We should add a test for it to make sure that it does not regress.

**Comment by hamarb123** [comment]
I'd be happy to make a PR to test it. What directory/file would it go in?

**Comment by jkotas** [comment]
It can be a new case under https://github.com/dotnet/runtime/blob/5549f72da3b3cea9e74bb81cfbb0f2d27731fc42/src/libraries/System.Runtime/tests/System/Type/TypeTests.cs#L984

**Comment by hamarb123** [comment]
I'm not sure if this is another bug, but I've discovered some weird behaviour while writing the test:
```csharp
void Print(InterfaceMapping map)
{
	for (int i = 0; i < map.InterfaceMethods.Length; i++)
	{
		Console.WriteLine($"{map.InterfaceMethods[i]} ({map.InterfaceMethods[i].DeclaringType}) maps to {map.TargetMethods[i]} ({map.TargetMethods[i].DeclaringType})");
	}
	Console.WriteLine();
}

Print(typeof(C2).GetInterfaceMap(typeof(I2)));
Print(typeof(C2).GetInterfaceMap(typeof(I1)));
Print(typeof(C1).GetInterfaceMap(typeof(I1)));

public interface I1
{
	static abstract void A();
	void B();
}

public class C1 : I1
{
	static void I1.A() { }
	void I1.B() { }
}

public interface I2 : I1
{
	static void I1.A() { }
	void I1.B() { }
}

public class C2 : I2
{
	static void I1.A() { }
	void I1.B() { }
}
```

->

```
Void I1.B() (I2) maps to Void I1.B() (I2)

Void B() (I1) maps to Void I1.B() (C2)
Void A() (I1) maps to Void I1.A() (C2)

Void B() (I1) maps to Void I1.B() (C1)
Void A() (I1) maps to Void I1.A() (C1)
```

the behaviour of the first set seems quite odd, is this what is expected? And if so, why?

**Comment by hamarb123** [comment]
I've found another instance of the original bug which wasn't fixed by recent changes:
```csharp
var x1 = typeof(I2<string>).GetMethod("I1<S>.G", (BindingFlags)(-1));
var x2 = typeof(C2<string>).GetInterfaceMap(typeof(I1<string>)).TargetMethods.Single((x) => x.Name == "I1<S>.G");
Console.WriteLine(x1 == x2);
Console.WriteLine(x1.MakeGenericMethod(typeof(int)).ContainsGenericParameters);
Console.WriteLine(x2.MakeGenericMethod(typeof(int)).ContainsGenericParameters);

interface I1<S>
{
	static abstract void G<T>();
}

interface I2<S> : I1<S>
{
	static void I1<S>.G<T>() { }
}

class C2<S> : I2<S>
{
}
```

->

```
False
False
Unhandled exception. System.InvalidOperationException: Void I1<S>.G[T]() is not a GenericMethodDefinition. MakeGenericMethod may only be called on a method for which MethodBase.IsGenericMethodDefinition is true.
   at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
```

I found it with the tests I'm writing.
