### ISSUE TITLE
[External] Libunwind has suppressed warnings 

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#90359]
Copied from https://github.com/dotnet/runtime/issues/76095 cc @AaronRobinsonMSFT 

The following externally consumed projects require suppression of warnings that are unadvised. We should be fixing these issues and offering those fixes upstream.

## libunwind
https://github.com/dotnet/runtime/blob/56095347ca1bacbc7a95e468f03f02ea808b9d9b/src/native/external/libunwind_extras/CMakeLists.txt#L143

**Comment by tommcdon** [comment]
@mikem8361 @janvorli

**Comment by tommcdon** [comment]
cc @hoyosjs  to determine if there are any warnings left here that we should fix

**Comment by hoyosjs** [comment]
Closing since all the required SDL warnings have been addressed.
