### ISSUE TITLE
[API Proposal]: Allow Setting Proxy for HttpClient Instance Used for CRL Checks

### ISSUE THREAD

**Issue by phadtrapong** [dotnet/runtime#90363]
### Background and motivation

When using HttpClient behind a proxy, users often expect all HTTP calls, including those for Certificate Revocation List (CRL) checks, to go through the specified proxy. Currently, while we can set a proxy for the main HttpClient, it's not clear if this also applies to the HttpClient instance used for CRL checks. This can lead to unexpected behavior, especially in environments where all traffic must go through a proxy.
reference: https://github.com/dotnet/runtime/issues/89831

### API Proposal
Introduce an API or a clear method to allow users to set a proxy specifically for the HttpClient instance that's used for CRL checks. This would ensure that all HTTP calls, whether they're main requests or CRL checks, can be routed through a specified proxy if desired.

```csharp
namespace System.Net.Http
{
    public partial class HttpClientHandler : HttpMessageHandler
    {
               public bool UseProxyForCrlChecks { get; set; }
    }
```

### API Usage

```csharp
HttpClientHandler handler = new HttpClientHandler();
handler.Proxy = new WebProxy("http://myproxy.example.com");
handler.UseProxyForCrlChecks = true; // Proposed property
```

### Benefits

Consistency: Ensures that all HTTP calls, including CRL checks, adhere to the user's proxy settings.
Security: In environments where traffic must be routed through a proxy for security reasons, this ensures that CRL checks aren't inadvertently bypassing the proxy.
Transparency: Provides clearer control to developers over the behavior of their applications in proxy environments.

**Comment by karelz** [comment]
@phadtrapong we believe that you can set global proxy (applied also to CRL) either via environment variable, or via [static HttpClient.DefaultProxy](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultproxy). Did that not work for you?

**Comment by phadtrapong** [comment]
Hi @karelz 

Thank you for taking the time to review my API proposal and for your feedback.

I understand that setting a global proxy via environment variables or `HttpClient.DefaultProxy` should ideally apply to CRL checks as well. However, there are a few reasons I proposed a more explicit control over the proxy settings for CRL checks:

1. Clarity and Explicitness: While global settings might work in many scenarios, having an explicit property like `UseProxyForCrlChecks` provides developers with a clear understanding of where their requests are being routed, especially when dealing with security-sensitive operations like CRL checks.

2. Flexibility: There might be scenarios where developers want to use different proxies for main requests and CRL checks, or bypass the proxy for one of them. The proposed API would offer this flexibility.

3. Troubleshooting: If there's ever an issue with CRL checks, having a separate control would make it easier to diagnose and resolve issues related to proxy settings.

I did try the methods you suggested, and while they work in general scenarios, I believe the added control would be beneficial for the reasons mentioned above. However, I'm open to further discussions and suggestions to ensure we provide the best solution for the community.

**Comment by karelz** [comment]
We have to take into account that too many APIs is distracting to developers. Unless it is common scenario, we tend NOT to add more APIs, to keep the API surface manageable.

Regarding your points:
1. Clarity and Explicitness ... While it is more explicit, it is yet another thing people have to keep in mind and most will wonder "what is it about" and "when do I have to set it to something else than default". Given that this is the first time in 20+ years of .NET somebody brings it up, I would consider it a niche scenario.
2. Flexibility ... Without very clear use case, it is hard to argue it is really needed. Again, given the number of requests (one) for it in 20+ years, perhaps it is not as much valuable.
3. Troubleshooting ... Again, unless it is common pattern with more votes or cases when it was needed, I would not consider it common scenario to justify adding an API.

**Comment by wfurt** [comment]
While some of concerns seems valid, I also feel this is not common scenario. It is neither `HttpClient` nor `SslStream` that does the fetching. If anything we would need to start with `X509Chain` and work it way up. Further more, this is perform by OS on various platforms so it would be really difficult to make it consistent across platforms. 

I'm going to close it for now since there is no clear implementation path and broad demand. We can reopen if we see more demand. (and as I mentioned it does not belong to HTTP)
