### ISSUE TITLE
BinaryFormatter serialization does not roundtrip with IConvertible fields

### ISSUE THREAD

**Issue by ladipro** [dotnet/runtime#90387]
### Description

`IConvertible` seems to interact with binary serialization in an unexpected way.

### Reproduction Steps

```C#
    [Serializable]
    public struct MyStruct
    {
        public IConvertible Value;
    }

    internal class Program
    {
        static void Main()
        {
            MemoryStream stream = new MemoryStream();

            BinaryFormatter bf = new BinaryFormatter();
            bf.Serialize(stream, new MyStruct
            {
                Value = 42
            });

            stream.Position = 0;

            bf.Deserialize(stream);
        }
    }
```

### Expected behavior

Program runs to completion.

### Actual behavior

```
Unhandled exception. System.Runtime.Serialization.SerializationException: Binary stream '42' does not contain a valid BinaryHeader. Possible causes are invalid stream or object version change between serialization and deserialization.
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
```

### Regression?

No, even .NET Framework behaves this way.

### Configuration

8.0.100-preview.7.23376.3 on Windows 11 x64.

**Comment by gfoidl** [comment]
Just noting: `BinaryFormatter` is on the plan to be [obsoleted](https://learn.microsoft.com/en-us/dotnet/core/compatibility/serialization/7.0/binaryformatter-apis-produce-errors).

**Comment by ladipro** [comment]
Fun fact: I found this when working on a regression test for a change replacing the obsoleted `BinaryFormatter` with something else. Not necessarily worth fixing but IMO worth tracking.

**Comment by GrabYourPitchforks** [comment]
The [NRBF decoder I have](https://nrbf-decoder.unsafe.as/) suggests that the serialized stream itself is corrupted, not that it's a problem with BF's deserialization logic. Still investigating.

```txt
System.IO.InvalidDataException: Unexpected record marker 0x2A seen in stream.
   at Pitchfork.BFCompat.BFStreamReader.ReadNextRecordConstrained(AllowedRecordTypeEnumerations allowedRecordTypes) in BFStreamReader.cs:line 117
   at Pitchfork.BFCompat.Graph.NrbfReaderWorker.ProcessNextRecordCommon(AllowedRecordTypeEnumerations allowedRecordTypes) in NrbfReaderWorker.cs:line 73
   at Pitchfork.BFCompat.Graph.NrbfReaderWorker.ReadAndPlaceAnyRecordWorker.Process(NrbfReaderWorker worker) in NrbfReaderWorker.cs:line 362
   at Pitchfork.BFCompat.Graph.NrbfReaderWorker.ReadGraph() in NrbfReaderWorker.cs:line 47
   at Pitchfork.BFCompat.Graph.NrbfReader.ReadGraph(ReadOnlyMemory`1 payload) in NrbfReader.cs:line 18
   at nrbf_azfn_worker.DumpNrbf.Run(HttpRequest req, ILogger log) in DumpNrbf.cs:line 0
```

**Comment by GrabYourPitchforks** [comment]
Note to triage owners - even though this is a legitimate bug (and good job finding it!), it doesn't meet the bar for fixing.

See: https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md#all-outstanding-binaryformatter-related-issues-resolved-wont-fix-net-5

**Comment by osexpert** [comment]
I was curios about this and took a look.
\src\libraries\System.Runtime.Serialization.Formatters\src\System\Runtime\Serialization\Formatters\Binary\BinaryObjectWriter.cs
line 322, method WriteMembers

```
            // If member type does not equal data type, transmit type on object.
            if (memberTypeNameInfo._primitiveTypeEnum == InternalPrimitiveTypeE.Invalid)
            {
                outType = GetType(outObj);
                if (!ReferenceEquals(memberType, outType))
                {
                    memberTypeNameInfo._transmitTypeOnMember = true;
                    memberNameInfo._transmitTypeOnMember = true;
                }
            }
```

If I remove\comment this line\check (_primitiveTypeEnum == InternalPrimitiveTypeE.Invalid), then it works, then it will always enter the "member type does not equal data type" check, regardless of _primitiveTypeEnum .
            
It may seem like an optimization (save a call to GetType) based on an assumption that was "always" true.
But hard to say, maybe this can break other things thou.

**Comment by tannergooding** [comment]
Closing given the bar check done by @GrabYourPitchforks above.
