### ISSUE TITLE
[Mono] Investigate the issue with trimming Mono.Android.dll

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#90403]
When enabling trimming for `Mono.Android.dll`, android app crashed on startup. Investigate and fix the issue behind this.

Then remove the workaround added in #90106

**Comment by lambdageek** [comment]
I think we should disable the hack from #90106 regardless of the outcome of this investigation before the .NET 8 RTM.  If we don't have a real fix, we shouldn't ship the ILStrip feature

**Comment by fanyang-mono** [comment]
This is not needed any more. I've found the root cause of this. See comments at https://github.com/dotnet/runtime/issues/88538#issuecomment-1675451234
