### ISSUE TITLE
Update documentation for the Windows thread pool option

### ISSUE THREAD

**Issue by kouvel** [dotnet/runtime#90444]
- Document the environment/runtimeconfig config options, and how to configure for NativeAOT-published apps
- Update docs for some APIs that are not supported with the Windows thread pool implementation, such as `ThreadPool.BindHandle`, `ThreadPool.SetMinThreads`, `ThreadPool.SetMaxThreads`, etc.

**Comment by eduardo-vp** [comment]
Closing as these were included in https://github.com/dotnet/dotnet-api-docs/pull/9211 and https://github.com/dotnet/docs/pull/36826
