### ISSUE TITLE
[API Proposal]: `Swap()`, a safe way to use external array for building an `ImmutableArray<T>`

### ISSUE THREAD

**Issue by Lehonti** [dotnet/runtime#90464]
### Background and motivation

Currently there is no way (that I know of) to use an external array for building an `ImmutableArray<T>`, so I propose a method for the builder, with this type signature:

```csharp
void Swap (ref T[] backing) 
```

The external array would be passed as a `ref` parameter, and when the method exits, the external variable will have the array that used to be inside the builder, and the array that used to be outside will now be inside, and the builder's `Count` and `Capacity` will reflect that. No need to make it unsafe! To be specific, I think that what was originally propised in issue 83141 should be avoided

### API Proposal

```csharp
ImmutableArray<T>. Builder. Swap (ref T[] backing)
```

### API Usage

```csharp
var values = new [] {1,2,3};
var builder = ImmutableArray.CreateBuilder<int>();
builder.Swap(ref values); // Now 'values' is an empty array
var immutable = builder.MoveToImmutable();
```

**Comment by huoyaoyuan** [comment]
> Currently there is no way (that I know of) to use an external array for building an `ImmutableArray<T>`

The feature has been implemented by #83141 and will ship in .NET 8.

**Comment by jkotas** [comment]
> No need to make it unsafe! T

Your proposed API does not guarantee that the array is not going to be used by the caller after it was swapped in into the builder. It makes it about as unsafe as the `ImmutableCollectionsMarshal` APIs that were implemented as part of https://github.com/dotnet/runtime/issues/83141.

**Comment by Lehonti** [comment]
@jkotas Thank you, I just realized that, and edited the comment. If this issue had not been closed by you, I would have closed it myself :)
