### ISSUE TITLE
C# Collections for docs 

### ISSUE THREAD

**Issue by YataoFeng** [dotnet/runtime#90463]
Is there a data structure document specifically developed for C #? Let people learn.
This includes the principles and performance of all current data structures in C #, as well as potential data structures that may appear in C # in the future.

**Comment by huoyaoyuan** [comment]
The topic is too wide for any "data structure". For collections, I think it worths a documentation about the optimizations and trade-offs (https://github.com/dotnet/runtime/discussions/90059#discussioncomment-6644929).

**Comment by ericstj** [comment]
We have this entry point conceptual doc for collections: https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/collections
