### ISSUE TITLE
EventPipe shutdown and EventPipeEventDispatcher aren't coordinated properly

### ISSUE THREAD

**Issue by davmason** [dotnet/runtime#90472]
If a program returns from main it will clean up EventPipe by calling ep_shutdown, but the EventPipeEventDispatcher thread is still running and may AV when it is trying to use memory owned by EventPipe's buffers.

We should either let the EventPipeEventDispatcher session run past shutdown or put in the appropriate synchronization.

**Comment by tommcdon** [comment]
Changed the milestone 8.0 as this was fixed in 8.0
