### ISSUE TITLE
Question: xml escape/unescape characters

### ISSUE THREAD

**Issue by strangeman375** [dotnet/runtime#90477]
Hello!

I'm working with large amount of small xml's, serializing/deserializing data, using XmlWriter/XmlReader (fastest way to work with xml in dotnet, as I know).
Recently I decide to write hand-coded seialisation/deserialisation to improve performance and reduce allocations.
It should be safe, since data model is easy and small, and logic is good covered by tests.
But now I need a way to escape/unescape characters in tag values EXACTLY as XmlWriter/XmlReader does, to work with already serialized data in same manner.
Is there such an instrument?

Thanks in advance.

**Comment by StephenMolloy** [comment]
This is how XmlReader does it. It's not a simple public API call, but the source is there if your intent is just to replicate the cases and behaviors of XmlReader in your own code.

https://github.com/dotnet/runtime/blob/6cd25fbeb1a2a332561a46cdf2b01d06c1fbb192/src/libraries/System.Private.Xml/src/System/Xml/Core/XmlTextEncoder.cs#L238
