### ISSUE TITLE
JsonNode.GetPropertyName/GetElementIndex  exception message misleading

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/runtime#90474]
### Description

When I try to get the property name with `GetPropertyName` from the root `JsonNode`, an exception is thrown like below

```
Unhandled exception. System.InvalidOperationException: The node must be of type 'JsonObject'.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_NodeWrongType(String typeName)
   at System.Text.Json.Nodes.JsonNode.GetPropertyName()
```

The exception message now is misleading, because the root JsonNode is a JsonObject.

And similar issue for `GetElementIndex` also

```
System.InvalidOperationException: The node must be of type 'JsonArray'.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_NodeWrongType(String typeName)
   at System.Text.Json.Nodes.JsonNode.GetElementIndex()
```

From the source code, there's a check for the parent node 

https://github.com/dotnet/runtime/blob/71a3d36e5cdaf1e2d41957fb1d2cebff8af0e063/src/libraries/System.Text.Json/src/System/Text/Json/Nodes/JsonNode.cs#L262-L290

So the exception message maybe should be `The parent node must be of type 'JsonObject'`?

### Reproduction Steps

```c#
var node = JsonNode.Parse("""{"id": 1, "name": "test", "jobs": ["abc", "def"]}""");
ArgumentNullException.ThrowIfNull(node);
Console.WriteLine(node.GetValueKind());
Console.WriteLine(node.GetPropertyName());
Console.WriteLine(node.GetElementIndex());
```

### Expected behavior

Exception error should relate to the parent node

### Actual behavior

Exception error just says the node

### Configuration

.NET 8 preview 7
Windows x64

**Comment by gregsdennis** [comment]
I wrote about this kind of thing recently: https://blog.json-everything.net/posts/jsonnode-odd-api/

**Comment by eiriktsarpalis** [comment]
This only seems to impact the APIs that were newly added in .NET 8. The other issue I'm noticing is that by checking if `_parent as JsonArray` is `null`, it's actually collapsing two failure modes into one error message: the node not having a parent or the parent not having the expected type. We should try to fix this now.
