### ISSUE TITLE
System.Math.Pow does not return the correct answer if x is negative and y is 0

### ISSUE THREAD

**Issue by tayler6000** [dotnet/runtime#90475]
### Description

Apologies if this is in the wrong place I'm not too familiar with the .NET world.

When running `System.Math.Pow(-256, 0);` it returns `1`, however, this is not the correct answer.  Any negative number to the power of `0` is actually `-1`.

### Reproduction Steps

```C#
use System.Diagnostics;

Debug.Assert((int)System.Math.Pow(-256, 0) == -1);
```

### Expected behavior

I would expect if x was any negative number and y was 0 that it would return -1.

### Actual behavior

x as any negative number and y as 0 will return 1.

### Regression?

I'm sorry, I don't know.

### Known Workarounds

I can just do an if statement to see if the number is negative and if so use `-1` otherwise use `1`.

### Configuration

I'm currently working in Unity 2022.3.5f1, which uses .NET 2.1.  I'm on Windows 10 22H2, x64 architecture.

### Other information

[In the remarks section of the docs](https://learn.microsoft.com/en-us/dotnet/api/system.math.pow?view=net-7.0#remarks), it does say that if "`x` = Any value except `NaN`; `y` = 0, then the return will be 1, so it's possible that this is intended behavior, but if it is I think we should revisit this to see why it is intended behavior, and if we decide to keep it, update the documentation to better point out this edge case where C# is intentionally wrong.

**Comment by rampaa** [comment]
> Any negative number to the power of 0 is actually -1

This is incorrect. (-256)^0 = 1. -256^0 would be -1 but that's akin to writing -1*(256^0) as opposed to (-256)^0=(-1^0)*(-256^0) (i.e., the correct notation for "negative number to the power of 0").
