### ISSUE TITLE
[WASI] wasiconsole template: Instructions in generated README.md incorrect

### ISSUE THREAD

**Issue by henrikrxn** [dotnet/runtime#90482]
### Description

The instructions in README.md are not correct when it comes to using `wasmtime` to run the wasiconsole application

- Path to wasm file is incorrect
  - Path itself is wrong (folder `browser-wasm` is not part of the path and there exists no wasm file with that name)
- Commandline for wasmtime is incorrect

### Reproduction Steps

- Install .NET 8 Preview 7 (or any of the previous previews)
- Open a new prompt and make sure to be using the preview just installed (dotnet --info)
- Install wasi-experimental workload
  `dotnet workload install wasi-experimental`
- Create a new wasi console application
    - `mkdir SampleWasiConsole; cd SampleWasiConsole`
	- `dotnet new wasiconsole MyWasiConsole`
- `dotnet build`
- `dotnet run` 
- `wasmtime .\bin\Debug\net8.0\browser-wasm\AppBundle\MyWasiConsole.wasm`

### Expected behavior

The instructions in the README.md should enable me to run the console application using the standalone `wasmtime` runtime

### Actual behavior

`dotnet build` and `dotnet run` works

But the instructions for wasmtime fails because (i) the path is wrong and (ii) the wasmfile does not exist. Suggest changing to something like known workaround

### Regression?

No. This is new for .NET 8

### Known Workarounds

- `cd .\bin\Debug\net8.0\wasi-wasm\AppBundle\`
- `wasmtime .\dotnet.wasm --dir . MyWasiConsole`

### Configuration

*Which version of .NET is the code running on?*

```
❯  dotnet --info
.NET SDK:
 Version:   8.0.100-preview.7.23376.3
 Commit:    daebeea8ea

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.7.23376.3\

.NET workloads installed:
 [wasi-experimental]
   Installation Source: SDK 8.0.100-preview.7
   Manifest Version:    8.0.0-preview.7.23375.6/8.0.100-preview.7
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-preview.7\microsoft.net.workload.mono.toolchain.current\8.0.0-preview.7.23375.6\WorkloadManifest.json
   Install Type:              Msi

 [wasm-tools-net6]
   Installation Source: VS 17.7.34003.232, VS 17.7.34003.232
   Manifest Version:    8.0.0-preview.7.23375.6/8.0.100-preview.7
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-preview.7\microsoft.net.workload.mono.toolchain.net6\8.0.0-preview.7.23375.6\WorkloadManifest.json
   Install Type:              Msi

 [wasm-tools]
   Installation Source: VS 17.7.34003.232, VS 17.7.34003.232
   Manifest Version:    8.0.0-preview.7.23375.6/8.0.100-preview.7
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-preview.7\microsoft.net.workload.mono.toolchain.current\8.0.0-preview.7.23375.6\WorkloadManifest.json
   Install Type:              Msi


Host:
  Version:      8.0.0-preview.7.23375.6
  Architecture: x64
  Commit:       65b696cf5e
  RID:          win-x64

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  6.0.413 [C:\Program Files\dotnet\sdk]
  7.0.400 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.7.23376.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.7.23375.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.7.23375.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.7.23376.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

What OS and version, and what distro if applicable?
```
Edition	Windows 11 Pro
Version	22H2
Installed on	‎2023-‎02-‎27
OS build	22621.2134
Serial number	R90ZD2LH
Experience	Windows Feature Experience Pack 1000.22659.1000.0
```

*What is the architecture (x64, x86, ARM, ARM64)?*
`x64`

*Do you know whether it is specific to that configuration?*
No

*If you're using Blazor, which web browser(s) do you see this issue in?*
N/A

**Comment by SamMonoRT** [comment]
@radical - I'm marking this as 8.0. Consider updating the milestone if you don't plan to backport the documentation changes PR.
