### ISSUE TITLE
.net 7.0 perf regression with stopwatch

### ISSUE THREAD

**Issue by johnnygiter** [dotnet/runtime#90498]
Same code runs about **15% faster in older .net 6.0 than in 7.0**
tested on Windows 10 and net 7.0.10 runtime

```
          int[] arrayToSort = new int[1000];
          Random random = new Random();
          for (int i = 0; i < arrayToSort.Length; i++)
          {
              arrayToSort[i] = random.Next();
          }

          stopwatch.Reset();
          stopwatch.Start();
          for (int i = 0; i < 500000; i++)
          {
              Array.Sort(arrayToSort);
          }
          stopwatch.Stop();
          totalElapsedTime += stopwatch.ElapsedMilliseconds;
          Console.WriteLine($"Sorting took: {stopwatch.ElapsedMilliseconds} ms");
```

**Comment by Symbai** [comment]
You should use Benchmark.NET. I don't see any regression of 15%.

|      Method |      Job |  Runtime |     Mean |     Error |    StdDev |
|------------ |--------- |--------- |---------:|----------:|----------:|
| Woopie | .NET 6.0 | .NET 6.0 | 3.246 us | 0.0287 us | 0.0268 us |
| Woopie | .NET 7.0 | .NET 7.0 | 3.253 us | 0.0244 us | 0.0216 us |


```C#
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Jobs;
using BenchmarkDotNet.Running;
using System;

BenchmarkRunner.Run<Schmoopi>();

[SimpleJob(RuntimeMoniker.Net60)]
[SimpleJob(RuntimeMoniker.Net70)]
public class Schmoopi
{
    readonly int[] arrayToSort = new int[1000];
    [GlobalSetup]
    public void Setup()
    {
        Random random = new Random();
        for (int i = 0; i < arrayToSort.Length; i++)
        {
            arrayToSort[i] = random.Next();
        }
    }

    [Benchmark]
    public int Woopie()
    {
        Array.Sort(arrayToSort);
        return 0;
    }
}
```

**Comment by johnnygiter** [comment]
Your code is NOT THE SAME arrayToSort.Length just use 500k or 1M value
Why? Asking seriously.
It's real app, no matter how I run this code even outside debugger as console app and does not matter about size of array, always 11-16% drop with 7.0

**Comment by johnnygiter** [comment]
> You should use Benchmark.NET. I don't see any regression of 15%.
> 
> Method	Job	Runtime	Mean	Error	StdDev
> Woopie	.NET 6.0	.NET 6.0	3.246 us	0.0287 us	0.0268 us
> Woopie	.NET 7.0	.NET 7.0	3.253 us	0.0244 us	0.0216 us
> ```cs
> using BenchmarkDotNet.Attributes;
> using BenchmarkDotNet.Jobs;
> using BenchmarkDotNet.Running;
> using System;
> 
> BenchmarkRunner.Run<Schmoopi>();
> 
> [SimpleJob(RuntimeMoniker.Net60)]
> [SimpleJob(RuntimeMoniker.Net70)]
> public class Schmoopi
> {
>     readonly int[] arrayToSort = new int[1000];
>     [GlobalSetup]
>     public void Setup()
>     {
>         Random random = new Random();
>         for (int i = 0; i < arrayToSort.Length; i++)
>         {
>             arrayToSort[i] = random.Next();
>         }
>     }
> 
>     [Benchmark]
>     public int Woopie()
>     {
>         Array.Sort(arrayToSort);
>         return 0;
>     }
> }
> ```
Why shall I test using benchmarkdotnet? Asking seriously.
just use 500k or 1M value, same code as mine it's very simple same code no matter how you will run it, just works slower.
That's the fact.
It's real app, no matter how I run this code even outside debugger as console app and does not matter about size of array, always 11-16% drop with 7.0

**Comment by johnnygiter** [comment]
Discovered weird reason
Run this against 6.0 and 7.0 
This one line changes everything.
Why ``stopwatch = new Stopwatch();`` used even outside of the loop slowing down this code in my case about 20%! about 0.3s
```

using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using System;
using System.Diagnostics;


namespace SortingBenchmark
{
    [MemoryDiagnoser]
    public class SortingBenchmark
    {
        private int[] arrayToSort;
        private Random random;
        private Stopwatch stopwatch;
        private long totalElapsedTime;

        [GlobalSetup]
        public void GlobalSetup()
        {
            arrayToSort = new int[1000];
            random = new Random();
            for (int i = 0; i < arrayToSort.Length; i++)
            {
                arrayToSort[i] = random.Next();
            }

            stopwatch = new Stopwatch();
        }

        [Benchmark]
        public void SortBenchmark()
        {
            for (int i = 0; i < 500000; i++)
            {
                Array.Sort(arrayToSort);
            }
        }

        [GlobalCleanup]
        public void GlobalCleanup()
        {
            // Do any cleanup here if needed.
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var summary = BenchmarkRunner.Run<SortingBenchmark>();
        
        }
    }
}

```

**Comment by huoyaoyuan** [comment]
Use a consistent seed for `Random`, or the result will be totally unreliable.

**Comment by huoyaoyuan** [comment]
See the correct benchmark of sort: https://github.com/dotnet/performance/blob/9ebcab2c612eb49ef71735a40af19f35dd06b42d/src/benchmarks/micro/libraries/System.Collections/Sort.cs#L34

**Comment by johnnygiter** [comment]
> will be totally unreliable

I cannot agree, totally.
1) Results are very consistent and we do not talk there about 1 or 3% but 15-20% so it's perfectly good and enough for this purpose.
2) Topic now is about something else so I'm not sure why you commenting now Array.Sort whereas problem is with something else ``stopwatch = new Stopwatch();``

**Comment by KeterSCP** [comment]
I checked your benchmark both with `stopwatch = new Stopwatch();` line

commented:

|        Method |      Job |  Runtime |    Mean |    Error |   StdDev | Allocated |
|-------------- |--------- |--------- |--------:|---------:|---------:|----------:|
| SortBenchmark | .NET 6.0 | .NET 6.0 | 1.357 s | 0.0167 s | 0.0157 s |    5568 B |
| SortBenchmark | .NET 7.0 | .NET 7.0 | 1.379 s | 0.0233 s | 0.0218 s |     600 B |
| SortBenchmark | .NET 8.0 | .NET 8.0 | 1.314 s | 0.0120 s | 0.0112 s |     400 B |

and uncommented:

|        Method |      Job |  Runtime |    Mean |    Error |   StdDev | Allocated |
|-------------- |--------- |--------- |--------:|---------:|---------:|----------:|
| SortBenchmark | .NET 6.0 | .NET 6.0 | 1.362 s | 0.0263 s | 0.0271 s |     640 B |
| SortBenchmark | .NET 7.0 | .NET 7.0 | 1.668 s | 0.0140 s | 0.0131 s |     600 B |
| SortBenchmark | .NET 8.0 | .NET 8.0 | 1.326 s | 0.0245 s | 0.0229 s |     400 B |

It seems like there was some problem in .NET 7 (maybe OSR?), but in the latest .NET 8 preview 7 it is fixed

**Comment by johnnygiter** [comment]
> It seems like there was some problem in .NET 7 (maybe OSR?), but in the latest .NET 8 preview 7 it is fixed

This is exactly what I'm writing about, I also checked earlier other versions and only version 7.0 seems to have a problem with this.

**Comment by KeterSCP** [comment]
Since .NET 7 is not an LTS release and is going to be superseded by .NET 8 shortly where the problem does not occur, I doubt you should be worried about this.

**Comment by huoyaoyuan** [comment]
Your original code:
|        Method |      Job |  Runtime |    Mean |    Error |   StdDev |
|-------------- |--------- |--------- |--------:|---------:|---------:|
| SortBenchmark | .NET 6.0 | .NET 6.0 | 1.707 s | 0.0063 s | 0.0059 s |
| SortBenchmark | .NET 7.0 | .NET 7.0 | 1.602 s | 0.0138 s | 0.0115 s |

Stopwatch commented out:
|        Method |      Job |  Runtime |    Mean |    Error |   StdDev |
|-------------- |--------- |--------- |--------:|---------:|---------:|
| SortBenchmark | .NET 6.0 | .NET 6.0 | 1.607 s | 0.0222 s | 0.0196 s |
| SortBenchmark | .NET 7.0 | .NET 7.0 | 1.811 s | 0.0036 s | 0.0030 s |

Stopwatch commented out, add `MemoryRandomization` to the benchmark class:
|        Method |  Runtime |    Mean |    Error |   StdDev |
|-------------- |--------- |--------:|---------:|---------:|
| SortBenchmark | .NET 6.0 | 1.659 s | 0.0148 s | 0.0138 s |
| SortBenchmark | .NET 7.0 | 1.518 s | 0.0045 s | 0.0042 s |

Comment out unrelated code often lead to code alignment change.

**Comment by johnnygiter** [comment]
Thanks you all guys for your input.
I no longer check at this point what is faster, I was simply troubled by the specific problem of this strange slowdown with stopwatch, the matter is now clear.
Version 7.0 is not reliable for me, I have to downgrade to 6.0 or wait for 8.0 in my proj.
I just don't know how many similar cases like this stopwatch exist maybe some other "slowdowns" or maybe "just" this? In any case it will be better to avoid version 7

**Comment by huoyaoyuan** [comment]
> I just don't know how many similar cases like this stopwatch exist maybe some other "slowdowns" or maybe "just" this?

This is not slowdown, since randomization changes the result. This is just unstable result of badly-written benchmark.

**Comment by johnnygiter** [comment]
> > I just don't know how many similar cases like this stopwatch exist maybe some other "slowdowns" or maybe "just" this?
> 
> This is not slowdown, since randomization changes the result. This is just unstable result of badly-written benchmark.

LOL, Unfortunately, you are wrong 
I see that you still don't understand the problem, that it's not about any randomization but about stopwatch :)

**Comment by AndyAyersMS** [comment]
> > > I just don't know how many similar cases like this stopwatch exist maybe some other "slowdowns" or maybe "just" this?
> > 
> > 
> > This is not slowdown, since randomization changes the result. This is just unstable result of badly-written benchmark.
> 
> LOL, unfortunately, I see that you still don't understand the problem, that it's not about any randomization but about stopwatch :) so root cause is that line ` stopwatch = new Stopwatch();`

Likely what is happening is that one extra line changes the memory address where the array is allocated slightly and this is what is leading to the performance impact you're seeing. Try adding two or more `new Stopwatch` and you may see performance change yet again.

See eg https://github.com/dotnet/BenchmarkDotNet/issues/1513

If you're interested learning more about the ways today's microarchtectures can make benchmarking tricky you might consider reading about [stabilizer](https://github.com/ccurtsinger/stabilizer/blob/master/README.md).

**Comment by AndyAyersMS** [comment]
@johnnygiter is there is anything we can do for you here aside from the explanations above?

**Comment by AndyAyersMS** [comment]
> > @johnnygiter is there is anything we can do for you here aside from the explanations above?
> 
> Almost all is clear in practice just all, it can be closed, thank you!

Ok, I will close. Feel free to re-open or create new issues if you see other issues with performance. Thanks!
