### ISSUE TITLE
[Proposal] Add byte[] and Stream overloads to AssemblyName.GetAssemblyName method

### ISSUE THREAD

**Issue by montyclt** [dotnet/runtime#905]
I'm in situation where I need to get assembly name from byte array that content the assembly.

I solved it writting the file into the disk (tmp directory), calling `AssemblyName.GetAssemblyName(string)` and deleting the file.

```cs
public static async Task<AssemblyName> GetNameAsync(byte[] assemblyData)
{
    async Task<string> SaveIntoFileAsync(byte[] data)
    {
        string directoryPath = Path.Combine(Path.GetTempPath(), "vadavo/vicim");
        Directory.CreateDirectory(directoryPath);
        string fileName = Path.Combine(directoryPath, Guid.NewGuid().ToString());
        await File.WriteAllBytesAsync(fileName, data);
        return fileName;
    }

    async void DeleteFile(string fileName)
    {
        File.Delete(fileName);
    }

    var savedFile = await SaveIntoFileAsync(assemblyData);
    var name = AssemblyName.GetAssemblyName(savedFile);
    DeleteFile(savedFile);
    return name;
}
```

I propose add two overloads, that accept `byte[]` and `Stream` as assembly sources.

**Comment by jkotas** [comment]
Take a look at System.Reflection.Metadata and [`AssemblyDefinition.GetAssemblyName`](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.metadata.assemblydefinition.getassemblyname?view=netcore-3.1`) API. It allows you to get the assembly name from an assembly in a byte array, Stream or anything else that you can instantiate the MetadataReader over.

**Comment by montyclt** [comment]
Thanks @jkotas 

I done using PEReader

**Comment by montyclt** [comment]
A note, I created a PEReader with async stream and I get exception that cannot read the stream synchronously, so I transformed first to byte array asynchronously and then created the PEReader.

I sugest add too `GetAssemblyDefinitionAsync` method that use `stream.ReadAsync` into the stram to `PEReader` and `MetadataReader`.

**Comment by steveharter** [comment]
Closing; the scenario can be handled without a new API or writing the AssemblyName to disk.
