### ISSUE TITLE
ARM64 unwinder missing support for pac_sign_lr

### ISSUE THREAD

**Issue by kobykahane** [dotnet/runtime#90500]
The runtime has an ARM64 unwinder that seems to have been forked from the OS version of RtlVirtualUnwind a few years ago, before the introduction of PAC (pointer authentication codes) and the `pac_sign_lr` unwind code, as described in https://learn.microsoft.com/en-us/cpp/build/arm64-exception-handling?view=msvc-170#unwind-codes.
This results in unwind failure when the unwind data for a stack frame uses the new unwind code because it was built with signed returns.

https://github.com/dotnet/runtime/blob/9a9d110463bc48c9a4d6e944e8e43d0782e69887/src/coreclr/unwinder/arm64/unwinder.cpp#L1333C1-L1335
https://github.com/dotnet/runtime/blob/9a9d110463bc48c9a4d6e944e8e43d0782e69887/src/coreclr/unwinder/arm64/unwinder.cpp#L1196

This applies to both the compact pdata and full xdata flows. For compact pdata, support for the CR = 2 (chained function with pacibsp signed return address) is missing.

**Comment by janvorli** [comment]
@kobykahane I am not sure how this influences .NET. For Unix, we never generate the pointer authentication in the jitted / crossgened code, so it would not have any effect. For Windows, this code is used for .NET managed debugging only and so it also doesn't seem to be relevant.

**Comment by tommcdon** [comment]
Closing this issue as it seems that pointer authentication is not used in the .NET generated code.  Please let us know if this assessment is incorrect then we will re-evaluate.
