### ISSUE TITLE
Passing CancellationToken best practices

### ISSUE THREAD

**Issue by kimbell** [dotnet/runtime#90507]
When reading all the code written by Microsoft, the CancellationToken is always passed as the last method argument with a default value. 

I recently came across some in-house code that violates this pattern. This code has a lot of methods, so in an effort to save time, they've added a scoped registration to the IServiceCollection. This uses the IHttpContextAccessor to get the HttpContext.RequestAborted value. 

When we enabled all the analyzers, we get a number of warnings on constructors not taking the CancellationToken as the last parameter.

My gut reaction is that this doesn't feel right, but I haven't found any authoritative answer out there that can disprove this way of doing things. The only thing I've found is an article from 2014. https://devblogs.microsoft.com/premier-developer/recommended-patterns-for-cancellationtoken/

Passing the CancellationToken as the last argument, is that a convention or is there something technical that will break if not done that way?

**Comment by stephentoub** [comment]
> When we enabled all the analyzers, we get a number of warnings on constructors not taking the CancellationToken as the last parameter.

Which analyzers?

> Passing the CancellationToken as the last argument, is that a convention or is there something technical that will break if not done that way?

It's convention. What would "break" is if something then relies on that convention, e.g. if another analyzer is relying on it being last and thus won't function correctly.

**Comment by kimbell** [comment]
We get CA1068 on constructors that that looks like this

 ```cs
public SomeConstructor(
    ApplicationDbContext dbContext,  
    CancellationToken cancellationToken,
    ISignalRNotifier signalRNotifier)
 {
 }
```

**Comment by karelz** [comment]
Triage: Question is answered, closing. Please let us know if anything is not clear yet.
