### ISSUE TITLE
RSA.ExportParameters(true) Throw CryptographicException on Redhat 7.9

### ISSUE THREAD

**Issue by TingluoHuang** [dotnet/runtime#90506]
### Description

I have a code in my application that is doing following.
```
var rsa = RSA.Create(2048);
var params = rsa.ExportParameters(true);
```

This code works fine on everywhere but one of my customer is hitting a weird exception when the `rsa.ExportParameters(true)` get executed.

```
~/github/rsa_test/bin/Release/net6.0/linux-x64/publish> ./rsa_test 
Creating new RSA key using 2048-bit key length
Unhandled exception. System.Security.Cryptography.CryptographicException: Object contains only the public half of a key pair. A private key must also be provided.
   at Interop.Crypto.GetPkcs8PrivateKeySize(IntPtr pkey)
   at Interop.Crypto.RentEncodePkcs8PrivateKey(SafeEvpPKeyHandle pkey)
   at System.Security.Cryptography.RSAImplementation.RSAOpenSsl.ExportPrivateKey[T](ExportPrivateKeyFunc`1 exporter)
   at System.Security.Cryptography.RSAImplementation.RSAOpenSsl.ExportParameters(Boolean includePrivateParameters)
   at Program.<Main>$(String[] args) in /workspaces/rsa_test/Program.cs:line 7
Abort
```

The code for this app (a trimmed down version for my customer to repro the issue) can be found at https://github.com/TingluoHuang/rsa_test/blob/main/Program.cs

Here is the Openssl version on the customer's machine
```
> openssl version
OpenSSL 1.1.1k  FIPS 25 Mar 2021
```

The customer is on RedHat 7.9

I would hope i can get some help for how I can debug the problem further, ex: trace event to enable, native trace that i can enable to get more debug info to help me figure out what's wrong with my customer's system.

Thanks a lot.

### Reproduction Steps

n/a

### Expected behavior

not throw `CryptographicException` on `ExportParameters(true)`

### Actual behavior

throw `CryptographicException` on `ExportParameters(true)`

### Configuration

Redhat 7.9
Dotnet 6.0

**Comment by vcsjones** [comment]
This error occurs whenever `EVP_PKEY2PKCS8` from OpenSSL returns NULL and the error in the error queue is not a memory allocation error. This is an assumption - so it very well may be a red herring as far as the error goes:

https://github.com/dotnet/runtime/blob/e1ed4b0953a7e9b87d869de899a5729bb3a441d4/src/libraries/Native/Unix/System.Security.Cryptography.Native/pal_evp_pkey.c#L188-L194

@tmds are you aware of anything that might cause `EVP_PKEY2PKCS8` to fail on RHEL 7.9 with `OpenSSL 1.1.1k  FIPS 25 Mar 2021`?

@TingluoHuang does the customer run their RHEL installation in FIPS mode? If the customer is unsure, I believe they can run `cat /proc/sys/crypto/fips_enabled`. If that file exists and the contents are "1" then the system is in FIPS mode.

This may help me be able to reproduce the issue.

**Comment by vcsjones** [comment]
@TingluoHuang also can you clarify which version of 6.0 runtime is being used? This particular function has changed during some servicing of 6.0, so it would be best to understand exactly what version of 6.0 us being used.

**Comment by TingluoHuang** [comment]
@vcsjones 
6.0.20 would be the runtime i think.

![image](https://github.com/dotnet/runtime/assets/1750815/e562d9b5-d974-4c52-a730-24ef9020e5a4)

**Comment by vcsjones** [comment]
I'm going to close this for now. We (GitHub) are working with the customer on trying to trouble shoot this, but thus far we have not been able to reproduce this or determine how this can happen.

We/I will re-open the issue if we can determine that there is an issue in the runtime.
