### ISSUE TITLE
Assertion failed 'hwintrinsicChild->isContained()'

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#90508]
```cs
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;

public class Tests
{
    public static void Main()
    {
        Div(default, 1);
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static Vector128<double> Div(Vector128<double> v, double b) => v / b;
}
```
Fails on Checked, win-x64, Tier0 with:
```
Assert failure(PID 48468 [0x0000bd54], Thread: 44484 [0xadc4]): Assertion failed 'hwintrinsicChild->isContained()' in 'mytest:Foo(System.Runtime.Intrinsics.Vector128`1[double],double):System.Runtime.Intrinsics.Vector128`1[double]' during 'Generate code' (IL size 8; hash 0xece1a119; Tier0)

    File: C:\prj\runtime-main\src\coreclr\jit\instr.cpp Line: 858
    Image: C:\prj\runtime-main\artifacts\bin\coreclr\windows.x64.Checked\CoreRun.exe
```

**Comment by JulieLeeMSFT** [comment]
Reassigning to @jakobbotsch, PTAL.

**Comment by kunalspathak** [comment]
@EgorBo - I don't see this failure on latest main. Can you confirm if it still repros for you? Also, seems the error message and the test case doesn't match. The error message has `Foo` in it which I presume is `Div` in your example.

**Comment by EgorBo** [comment]
> @EgorBo - I don't see this failure on latest main. Can you confirm if it still repros for you? Also, seems the error message and the test case doesn't match. The error message has `Foo` in it which I presume is `Div` in your example.

I think it still repros, you just need Avx512 for that (because it has the containable broadcasts)
