### ISSUE TITLE
build error when only install professional vs2022

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#90509]
-- The CXX compiler identification is unknown
  CMake Error at CMakeLists.txt:7 (project):
    The CMAKE_C_COMPILER:

      C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/bin/Hostx86/x64/cl.exe

    is not a full path to an existing compiler tool.

    Tell CMake where to find the compiler by setting either the environment
    variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
    the compiler, or to the compiler name if it is in the PATH.

  CMake Error at CMakeLists.txt:7 (project):
    The CMAKE_CXX_COMPILER:

      C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/bin/Hostx86/x64/cl.exe

    is not a full path to an existing compiler tool.

**Comment by huoyaoyuan** [comment]
The cached compiler path is outdated (#82490). Manually deleting all cmake_command_line.txt under artifacts/obj may trigger a force reconfiguration.

**Comment by srxqds** [comment]
yeah
