### ISSUE TITLE
System.Net.Sockets.Tests failing in CI runs

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#90521]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=372462
Build error leg or test failing: System.Net.Sockets.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/90149

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Unhandled exception. System.TimeoutException: Timeout waiting for client connection.",
  "ErrorPattern": "Unhandled exception. System.TimeoutException: Timeout waiting for client connection.",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=372462
**Error message validated:** `Unhandled exception. System.TimeoutException: Timeout waiting for client connection.`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 8/14/2023 3:27:26 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[440271](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440271)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440271&view=ms.vss-test-web.build-test-results-tab&runId=9806200&resultId=208668)||
|[430326](https://dev.azure.com/dnceng-public/public/_build/results?buildId=430326)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=430326&view=ms.vss-test-web.build-test-results-tab&runId=9512276&resultId=212005)|dotnet/runtime#93124|
|[421566](https://dev.azure.com/dnceng-public/public/_build/results?buildId=421566)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=421566&view=ms.vss-test-web.build-test-results-tab&runId=9259870&resultId=211891)|dotnet/runtime#92695|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|3|

**Comment by wfurt** [comment]
all the logs are gone. This is not actionable.
