### ISSUE TITLE
LoggerMessage source generator does not support Message Template Structure Capture Operator

### ISSUE THREAD

**Issue by tbalcom** [dotnet/runtime#90522]
### Description

The `LoggerMessage` source generator does not support using the Message Templates structure capturing operator. From [Message Templates](https://messagetemplates.org/#operators):
> Prefixing a property name with the @ structure capturing operator is a hint that the the structure of the corresponding argument should be preserved, for example, by serialization.

### Reproduction Steps

```csharp
internal static partial class LoggerMessages
{
    [LoggerMessage(
        EventId = 9001,
        Level = LogLevel.Error,
        Message = "Something happened at {@point}")]
    public static partial void SomethingHappenedAtPoint(this ILogger logger, Point point);
}
```
This should be a valid message template but it results in:
1. Warning SYSLIB1015: Argument 'point' is not referenced from the logging message
1. Error SYSLIB1014: Template '@point' is not provided as argument to the logging method
1. Error CS0103: The name 'point' does not exist in the current context

### Expected behavior

I should be able to use the message template structure capturing operator, and it should be rendered to the logger in JSON.

```csharp
internal static partial class LoggerMessages
{
    [LoggerMessage(
        EventId = 9001,
        Level = LogLevel.Error,
        Message = "Something happened at {@point}")]
    public static partial void SomethingHappenedAtPoint(this ILogger logger, Point point);
}
```

Should output:
```json
{
  "Timestamp": "15:26:47 ",
  "EventId": 9001,
  "LogLevel": "Error",
  "Category": "Blah.Blah.Blah",
  "Message": "Something happened at {@point}",
  "State": {
    "Message": "Something happened at {@point}",
    "point": {
        "x": 1,
        "y": 2
    },
    "{OriginalFormat}": "Something happened at {@point}"
  },
  "Scopes": []
}

```

### Actual behavior

`ToString()` appears to be as close as we can get to logging an object with structure because the structure capturing operator is not supported.

```csharp
internal static partial class LoggerMessages
{
    [LoggerMessage(
        EventId = 9001,
        Level = LogLevel.Error,
        Message = "Something happened at {point}")]
    public static partial void SomethingHappenedAtPoint(this ILogger logger, Point point);
}
```

Outputs:
```json
{
  "Timestamp": "15:26:47 ",
  "EventId": 9001,
  "LogLevel": "Error",
  "Category": "Blah.Blah.Blah",
  "Message": "Something happened at {X=1,Y=2}",
  "State": {
    "Message": "Something happened at {X=1,Y=2}",
    "point": "{X=1,Y=2}",
    "{OriginalFormat}": "Something happened at {point}"
  },
  "Scopes": []
}
```

### Known Workarounds

Rely on `ToString` implementation while serializing an object to the logger.

### Configuration

.NET 7
Windows 10
x86

### Other information

This is *not* the same problem as #64779.

**Comment by tarekgh** [comment]
This should be fixed in .NET 8.0 and duplicate to the issue https://github.com/dotnet/runtime/issues/78013. @tbalcom please try to install .NET 8.0 preview version and validate your scenario and let's know if you still seeing any issue with it. Thanks for your report.
