### ISSUE TITLE
IPV6 stack is required for .NET 6 and WSL

### ISSUE THREAD

**Issue by ChadJessup** [dotnet/runtime#90543]
### Description

I can't comment on #59015 - but this is an issue in .Net 6 on WSL2 as well.

Is it possible to get the fix for .Net 7 (https://github.com/dotnet/runtime/pull/69172) ported into .Net 6 since it's a LTS?

Older installs of wsl2 seem to have the appropriate files in: `/proc/net` (tcp6 and udp6) - but newer WSL2 installs seem to not have these files triggering this issue.

### Reproduction Steps

Newer WSL2 install (Ubuntu distro works) and .Net 6.
Verify /proc/net/tcp6 doesn't exist, if it does...uninstall/reinstall WSL2 and it seems to go away?

```c#
System.Net.NetworkInformation.IPGlobalProperties ipProperties = System.Net.NetworkInformation.IPGlobalProperties.GetIPGlobalProperties();
System.Net.IPEndPoint[] ipEndPoints = ipProperties.GetActiveTcpListeners();
```

### Expected behavior

The call to `GetActiveTcpListeners() and GetActiveUdpListeners()` while on a IPv4 network stack should still work if IPv6 isn't enabled.

### Actual behavior

PlatformNotImplemented when trying to access /proc/net/tcp6 or /proc/net/udp6 

```
Unhandled exception. System.PlatformNotSupportedException: The information requested is unavailable on the current platform.
   at System.Net.NetworkInformation.StringParsingHelpers.ParseActiveTcpListenersFromFiles(String tcp4ConnectionsFile, String tcp6ConnectionsFile)
   at System.Net.NetworkInformation.LinuxIPGlobalProperties.GetActiveTcpListeners()
```

### Configuration

WSL2: 5.10.16.3-microsoft-standard-WSL2
.Net: 6.0.410
WSL2 Distro: Ubuntu-20.04

### Other information

Already fixed and in 7.0 milestone (verified fixed on my setup).

**Comment by karelz** [comment]
@ChadJessup the fix is also in 8.0, which will go into go-live RC1 in 1 month. Is that acceptable solution for you?
If not, we would need some business justification (number of customers impacted, severity of the impact, etc.)

**Comment by karelz** [comment]
Related to #88975

**Comment by ChadJessup** [comment]
Hi @karelz! Thank you for getting back to me.

We're still in the process of upgrading to .Net 6.0 from a large multi-decade old codebase and moving to a non-LTS (7.0) or pre-release (8.0) violates policy on our end. Moving to 8.0 has breaking changes that we can't take without extensive work as well (binary serializer changes).

As-is, based on my understanding:
1. Our dev workflow is broken for half of the engineers as a WSL2 update fixing an issue (which is, afaik, a valid change) now triggers this bug. This has caused us to have to completely change dev workflows and spin up VMs for Linux work.
2. Over the next year or so, as people update WSL2, you'll be getting more and more tickets (until Nov 2024 at least) on this.
3. For the rest of .Net 6.0's LTS lifetime, you'll most likely be getting difficult to troubleshoot bugs from customers across many variants of Linux: in WSL2, containers, VMs, and raw servers. (Do Microsoft controlled .Net containers have tests for this quirk, with and without ipv6 enabled?)
4. At any time disabling IPv6 can trigger this bug, across many Linux distros.
5. A bug that can trigger because an entire network stack is disabled, that has little to do with the code being written or ran, seems like a big deal to me, but I don't have the ability to tell how often people look for Open or Listening (TCP or UDP) ports. It seems like that's a fairly common use case?

Thank you again!

**Comment by karelz** [comment]
@ChadJessup thanks for your info! Given that this is only 2nd report so far, I don't think it will be as common as you describe it (although I might be wrong - only time will tell).
The WSL2 angle requires also IPv6 to be disabled, which I assume is minority of customers, especially in dev scenarios.

Personally, I don't quite understand why IPv6 would be disabled, I would expect rather the opposite. Can you shed some light on that from your use case perspective?

That said, given that the fix is simple, I would be ok backporting the fix to 6.0. We will decide in team meeting if we want to report for one more independent report, or just do it right away.

**Comment by ChadJessup** [comment]
Thank you Karel!

As for why ipv6 would be disabled in this case, wsl2 doesn't seem to
support it, so it's disabled there on the kernel option level.

**Comment by karelz** [comment]
OK, if WSL2 does not support IPv6, that would make it more impactful on dev scenarios (although this is the first complain about dev scenario we heard in this context).
@liveans do you have insight into WSL2 IPv6 support?

**Comment by ChadJessup** [comment]
Can you verify the WSL2 version please?

**Comment by danmoseley** [comment]
What distro did you test, and what did you use Stephen?

**Comment by stephentoub** [comment]
> Can you verify the WSL2 version please?

1.2.5

> What distro did you test, and what did you use Stephen?

Ubuntu 22.04.2 LTS

**Comment by ChadJessup** [comment]
@stephentoub  - can you run `wsl.exe --status` to get the Kernel version WSL is using? the `/proc/net` directory is essentially a kernel object exposed to the user.

<img width="438" alt="image" src="https://github.com/dotnet/runtime/assets/618397/28988b63-43a1-45ec-90f6-5c3a8c120d6b">

**Comment by ChadJessup** [comment]
@karelz  - digging in further, I think this can be closed.
There are many ways to disable ipv6, and at least one of them causes the tcp6/udp6 'files' to not exist on WSL2. I have a workaround, now by editing the `.wslconfig` which allows me to pass in kernel cmdline options to resolve my issue.

**Comment by stephentoub** [comment]
> @stephentoub - can you run wsl.exe --status to get the Kernel version WSL is using?

Kernel version: 5.15.90.1

**Comment by karelz** [comment]
Thanks for getting back to us. If we see one more report from a customer on 6.0, I am inclined to backport the fix.
Closing for now.
