### ISSUE TITLE
ToFrozenDictionary function throws ArgumentOutOfRangeException exception in .Net 8 Pewview 7

### ISSUE THREAD

**Issue by CuteLeon** [dotnet/runtime#90567]
### Describe the bug
ToFrozenDictionary function throws ArgumentOutOfRangeException exception in .Net 8 Pewview 7

![image](https://github.com/dotnet/sdk/assets/17419770/30b0092b-fa50-4404-8621-9b7502d70886)

### To Reproduce
```
var test = Enumerable.Empty<string>().ToFrozenDictionary(s => s);
```

### Exceptions (if any)
System.ArgumentOutOfRangeException: 'minimumLength ('-2147483638') must be a non-negative value. (Parameter 'minimumLength')
Actual value was -2147483638.'

### Further technical details
.NET SDK:
 Version:   8.0.100-preview.7.23376.3
 Commit:    daebeea8ea

**Comment by eiriktsarpalis** [comment]
Can reproduce, seems like this code

https://github.com/dotnet/runtime/blob/55c896f28b418893e202b4d20e95f5ed62402b91/src/libraries/System.Collections.Immutable/src/System/Collections/Frozen/FrozenDictionary.cs#L154-L170

does not account for empty dictionary inputs. This appears to be causing this assertion

https://github.com/dotnet/runtime/blob/55c896f28b418893e202b4d20e95f5ed62402b91/src/libraries/System.Collections.Immutable/src/System/Collections/Frozen/String/LengthBucketsFrozenDictionary.cs#L35

to fail in debug builds. cc @adamsitnik @stephentoub

**Comment by skyoxZ** [comment]
@eiriktsarpalis It would fail eariier at Line 167: `Debug.Assert(minLength >= 0 && maxLength >= minLength); `

And another issue:
https://github.com/dotnet/runtime/blob/55c896f28b418893e202b4d20e95f5ed62402b91/src/libraries/System.Collections.Immutable/src/System/Collections/Frozen/FrozenDictionary.cs#L232
https://github.com/dotnet/runtime/blob/55c896f28b418893e202b4d20e95f5ed62402b91/src/libraries/System.Collections.Immutable/src/System/Collections/Frozen/SmallFrozenDictionary.cs#L26

Maybe something is missing to ensure `source` is not empty at first?

**Comment by adamsitnik** [comment]
Both the fix (https://github.com/dotnet/runtime/pull/90595) and backport (https://github.com/dotnet/runtime/pull/90599) got merged.

**Comment by CuteLeon** [comment]
Will this change be deliveried in next release? I downgraded my Visual Studio and .Net 8 SDK to compile my solution.

**Comment by stephentoub** [comment]
Yes, in .NET 8 RC1
