### ISSUE TITLE
JsonConstructorAttribute not working for private/internal ctor in .NET 8.0 preview7

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/runtime#90577]
### Description

Hello @eiriktsarpalis,

I have tested with .NET **8.0 Preview7 SDK** with Rider. It's not working. It's throwing the following exception:

<img width="896" alt="image" src="https://github.com/dotnet/docs/assets/14342773/398f3864-2e15-48c9-8aa8-b52cde229849">

My SDKs:

<img width="900" alt="image" src="https://github.com/dotnet/docs/assets/14342773/d7249006-1e3c-49f2-b55c-6ef2849f2979">

Debug Log:

<img width="1080" alt="image" src="https://github.com/dotnet/docs/assets/14342773/5883187b-2e5a-463b-b29a-7834ee2f5b48">

Employee class:

<img width="733" alt="image" src="https://github.com/dotnet/docs/assets/14342773/857dc898-4eed-46ee-b78b-00039f8b579e">

### Reproduction Steps

Try in Rider with .NET 8.0 preview 7 SDK.

### Expected behavior

It should have worked as mentioned here: https://github.com/dotnet/runtime/pull/88452

### Actual behavior

Not working. Throwing Unsupported exception.

**Comment by eiriktsarpalis** [comment]
Hi @TanvirArjel, would it be possible to share your reproduction in text? It's difficult to transcribe using screenshots.

**Comment by huoyaoyuan** [comment]
The exception message says "parameterless constructor, a singular parameterized constructor or **a parameterized constructor annotated with 'JsonConstructorAttribute'**".

`JsonConstructorAttribute` is meant to be used on the constructor `Employee(int id, string name)`.

**Comment by TanvirArjel** [comment]
@eiriktsarpalis Here it is:

The Program class:
```
using System;
using System.Text.Json;
using ConsoleApp2;

internal class Program
{
    public static void Main(string[] args)
    {
        Employee employee = new(1, "Tanvir");
        string jsonString = JsonSerializer.Serialize(employee);

        Employee deEmployee = JsonSerializer.Deserialize<Employee>(jsonString);
    }
}
```
The employee class:

```
public class Employee
{
    [JsonConstructor]
    private Employee()
    {
    }

    public Employee(int id, string name)
    {
        this.Id = id;
        this.Name = name;
    }
    
    public int Id { get; set; }

    public string Name { get; set; }
}
```

**Comment by huoyaoyuan** [comment]
> For `Employee(int id, string name)` ctor, you don't even need `JsonConstructorAttribute`.

Right, sometimes it can't be determined and needs to be specified.
`JsonConstructorAtttribute` is used for a constructor accepting all properties, not parameterless constructor.

**Comment by TanvirArjel** [comment]
@huoyaoyuan Primary need of `JsonConstructorAtttribute` is to be used in private parameterless ctor. If it does not work then it is useless.

**Comment by eiriktsarpalis** [comment]
Appears to be a bug specific to applying the attribute to parameterless constructors. We should fix this.
