### ISSUE TITLE
NET8 breaking change due to TypeForwardedTo attribute missing for PEFileKinds

### ISSUE THREAD

**Issue by jimm98y** [dotnet/runtime#90578]
### Description

We're trying to upgrade our project from NET Framework to NET8. First, we've upgraded it to NET6 where it is mostly working, then we are trying to update to NET8. After upgrading, we are getting an exception:

> System.TypeLoadException: 'Could not load type 'System.Reflection.Emit.PEFileKinds' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.'

After some investigation, it looks like NET8 version of the mscorlib is missing [assembly: TypeForwardedTo(typeof(PEFileKinds))] along with some other types:

[assembly: TypeForwardedTo(typeof(AssemblyRegistrationFlags))]
[assembly: TypeForwardedTo(typeof(ExporterEventKind))]
[assembly: TypeForwardedTo(typeof(IDispatchImplAttribute))]
[assembly: TypeForwardedTo(typeof(IDispatchImplType))]
[assembly: TypeForwardedTo(typeof(PEFileKinds))]
[assembly: TypeForwardedTo(typeof(RegistrationClassContext))]
[assembly: TypeForwardedTo(typeof(RegistrationConnectionType))]
[assembly: TypeForwardedTo(typeof(SetWin32ContextInIDispatchAttribute))]

The type it's looking for still exists in System.Private.CoreLib, it's just the type forwarding missing. 

### Reproduction Steps

1) Open mscorlib in NET6 using ILSpy
2) See the [assembly: TypeForwardedTo(typeof(PEFileKinds))] attribute
3) Open mscorlib in NET8 using ILSpy
4) [assembly: TypeForwardedTo(typeof(PEFileKinds))] (+ all the other types mentioned) is missing

### Expected behavior

Application should not break after upgrading from NET6 to NET8.

### Actual behavior

Application starts crashing after being upgraded to NET8.

### Regression?

This was working in NET6.

### Configuration

Windows 11 22H2, x64, NET8 preview 7

**Comment by jimm98y** [comment]
Full list of forwarded types missing in NET8 when compared to NET6:
[assembly: TypeForwardedTo(typeof(AssemblyRegistrationFlags))]
[assembly: TypeForwardedTo(typeof(ExporterEventKind))]
[assembly: TypeForwardedTo(typeof(IDispatchImplAttribute))]
[assembly: TypeForwardedTo(typeof(IDispatchImplType))]
[assembly: TypeForwardedTo(typeof(PEFileKinds))]
[assembly: TypeForwardedTo(typeof(RegistrationClassContext))]
[assembly: TypeForwardedTo(typeof(RegistrationConnectionType))]
[assembly: TypeForwardedTo(typeof(SetWin32ContextInIDispatchAttribute))]

**Comment by jkotas** [comment]
cc @ViktorHofer

**Comment by ViktorHofer** [comment]
Thanks for letting us know @jimm98y. I just submitted https://github.com/dotnet/runtime/pull/90669 to fix this and also triggered a backport into .NET 8.

**Comment by ViktorHofer** [comment]
@jimm98y actually here's a follow-up question. As some/all of these type are just stubs on .NETCoreApp and don't do anything, can you please explain why you need them on .NETCoreApp?

**Comment by jimm98y** [comment]
Hi Viktor, thank you very much! In our case, we just need the System.Reflection.Emit.PEFileKinds because we are relying upon an old third-party NET Framework DLL that is using this particular type. I felt it was worth mentioning all the other types, because some other old NET Framework DLLs that are now being used in NET Core with the NET Framework compatibility shim might still require them.
