### ISSUE TITLE
DOTNET_EnableAvx512F=0 does not disable Vector512.IsHardwareAccelerated in WSL

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#90598]
On a Windows machine with AVX512 support, this program:
```C#
using System.Runtime.Intrinsics;
Console.WriteLine("Vector512.IsHardwareAccelerated: " + Vector512.IsHardwareAccelerated);
```
prints `True`. Similarly, when I use WSL on that same machine, that same program prints `True`.

However, if on Windows I set the environment variable:
```
DOTNET_EnableAvx512F=0
```
then the program prints `False`, but if I set the same environment variable in WSL, it still prints `True`.

cc: @tannergooding, @EgorBo

**Comment by stephentoub** [comment]
Thanks.

>  these knobs are case sensitive on one platforms and aren't on others

Why?!

**Comment by tannergooding** [comment]
> Why?!

Because Linux is case sensitive, with respect to environment variables, while Windows is not. It's much like file system defaults on the respective platforms.

The cost required to make Linux appear to be case insensitive would be non-trivial and could potentially break user code and apps that don't expect this behavior.

**Comment by danmoseley** [comment]
This has come up before (I hit this myself). Why would it be non trivial? The change to enable the DOTNET prefix was quite small - aren't these variables all read through that shared code?

**Comment by stephentoub** [comment]
> Because Linux is case sensitive, with respect to environment variables, while Windows is not. It's much like file system defaults on the respective platforms.

We do case-insensitive environment variable matching, regardless of platform, all over the place.

**Comment by stephentoub** [comment]
> Do you have a link to an example?

e.g.
- https://github.com/dotnet/runtime/blob/1eb702ce1efe3581488a37704cee47603a291069/src/libraries/System.Private.CoreLib/src/System/AppContextConfigHelper.cs#L17-L18
- https://github.com/dotnet/runtime/blob/1eb702ce1efe3581488a37704cee47603a291069/src/libraries/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs#L81-L83
- https://github.com/dotnet/runtime/blob/1eb702ce1efe3581488a37704cee47603a291069/src/libraries/Common/src/System/Console/ConsoleUtils.cs#L41-L42
- https://github.com/dotnet/runtime/blob/1eb702ce1efe3581488a37704cee47603a291069/src/libraries/Common/src/System/Net/SocketProtocolSupportPal.cs#L30
- https://github.com/dotnet/runtime/blob/1eb702ce1efe3581488a37704cee47603a291069/src/libraries/Microsoft.Extensions.Logging.Console/src/ConsoleLoggerProvider.cs#L72
- https://github.com/dotnet/runtime/blob/1eb702ce1efe3581488a37704cee47603a291069/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/LocalAppContextSwitches.cs#L21
- https://github.com/dotnet/runtime/blob/1eb702ce1efe3581488a37704cee47603a291069/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/AuthenticationHelper.NtAuth.cs#L42-L43
- https://github.com/dotnet/runtime/blob/1eb702ce1efe3581488a37704cee47603a291069/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RuntimeSettingParser.cs#L24-L26
-

**Comment by stephentoub** [comment]
Ah, ignore my examples: those are about ignoring case on the values, not on the environment variable name itself.  I don't have any of those.

**Comment by am11** [comment]
This is the list of supported environment variables https://github.com/dotnet/runtime/blob/main/src/coreclr/inc/clrconfigvalues.h. All `RETAIL_.*EXTERNAL_.*` configs can be used with `DOTNET_` prefix. Case-sensitivity wise, some names are inconsistent, e.g. "GC" in `DOTNET_gcAllowVeryLargeObjects` vs. `DOTNET_GCLOHThreshold`. 🙂

**Comment by tannergooding** [comment]
> those are about ignoring case on the values, not on the environment variable name itself. I don't have any of those. And this case being discussed here is about the environment variable name itself.

I know we do a lot of value insensitive comparisons. But for names, I'm not aware of any either.

I have concerns around both the cost and the implications of handling names this way and how it may subtly impact or break other downstream usages of such environment variables outside the JIT. Whether that be in tests, tools, profilers, etc.

**Comment by ericstj** [comment]
This Issue is still in the 8.0.0 milestone - @tannergooding @stephentoub are you tracking any 8.0 work around this?

**Comment by jeffhandley** [comment]
We're closing this (won't fix). The environment variable name is case-sensitive on Linux and needs to be `DOTNET_EnableAVX512F`.
