### ISSUE TITLE
[iOS] Make HybridGlobalization the default when nativeaot is enabled

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#90633]
Since both are experimental features on iOS, it would make sense to make HybridGlobalization the default when nativeaot is enabled. This would apply to both runtime for testing and in the iOS SDK. 

For the iOS SDK, the default can be set at https://github.com/xamarin/xamarin-macios/blob/587f722283eba0f27e103205b94090e9d2eaed14/dotnet/targets/Xamarin.Shared.Sdk.targets#L129

**Comment by SamMonoRT** [comment]
This is not well tested, some ICU native api implementations are much slower, possibly causing perf regressions. At this time we shouldn't merge them together.

**Comment by SamMonoRT** [comment]
@steveisok - moving this to 9.0.0 milestone, and can discuss more once we have some perf analysis done.

**Comment by mkhamoyan** [comment]
After https://github.com/dotnet/runtime/pull/93220 HybridGlobalization is default mode.
