### ISSUE TITLE
System.Text.Json: serialize dictionary with JsonExtensionData ignores DefaultIgnoreCondition option

### ISSUE THREAD

**Issue by Drake53** [dotnet/runtime#90670]
### Description

When a property has `JsonExtensionDataAttribute`, its KeyValuePairs are treated as if they are individual properties. However, unlike properties, when the value is `null` and `JsonSerializerOptions.DefaultIgnoreCondition` is set to `JsonIgnoreCondition.WhenWritingNull`, these properties will still be included in the serialized JSON.

### Reproduction Steps

```csharp
public class MyObject
{
    public string? Prop1 { get; set; }

    public string? Prop2 { get; set; }

    [JsonExtensionData]
    public Dictionary<string, object?> UnmappedProperties { get; set; }
}
```
```json
{
    "Prop1": "test",
    "UnknownProp": null
}
```
```csharp
var input = ""; // see above
var options = new JsonSerializerOptions();
options.DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull;

var obj = JsonSerializer.Deserialize<MyObject>(input, options);
var json = JsonSerializer.Serialize(obj, options);
```

### Expected behavior

The serialized JSON should look like this:
```json
{
    "Prop1": "test"
}
```

### Actual behavior

The serialized JSON looks like this:
```json
{
    "Prop1": "test",
    "UnknownProp": null
}
```

### Known Workarounds

I found an existing issue, but it was closed and locked without providing a solution or workaround: https://github.com/dotnet/runtime/issues/31786

**Comment by eiriktsarpalis** [comment]
The [`DefaultIgnoreCondition` property](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.defaultignorecondition?view=net-7.0) governs the ignore condition of the properties on your POCOs, but does not have any impact on JsonExtensionData properties which act as a property bag for all JSON properties that aren't bound to specific .NET properties.

Even if we tried changing this, it would most likely constitute a breaking change.

**Comment by eiriktsarpalis** [comment]
Can I ask what the use case for ignoring JsonExtensionData properties is?

**Comment by Drake53** [comment]
In my case I have included JsonExtensionData to make sure any properties that aren't part of my POCO aren't lost when deserializing and then serializing again. The models I work with can have hundreds to even thousands of properties, so I only include the ones that are relevant for me.

The issue I have is when sending this JSON to some external service, it gives me an error because it doesn't expect certain properties that have been included with a null value in the JSON thanks to JsonExtensionData. Honestly, the input JSON that I deserialize shouldn't have included the property in the first place, but since I retrieve this from the same external service (I get a JSON template, set some values, and send it back), I have no control over it.

I understand changing this would be a breaking change. I wouldn't mind if this would be an opt-in feature, perhaps adding a property to JsonExtensionDataAttribute or some global setting on JsonSerializerSettings, that way it won't be a breaking change.

**Comment by eiriktsarpalis** [comment]
Do you have any need for these null-valued properties or are they just artifacts when deserializing third-party sources against your models? If that's the case you could try implementing the `IJsonOnDeserializing` interface to clear the dictionary after the fact:
```C#
public class MyObject : IJsonOnDeserialized
{
    public string? Prop1 { get; set; }

    public string? Prop2 { get; set; }

    [JsonExtensionData]
    public Dictionary<string, object?> UnmappedProperties { get; set; }

    public void OnDeserialized()
    {
        List<string>? keysToRemove = null;
        foreach (KeyValuePair<string, object?> entry in UnmappedProperties)
        {
            if (entry.Value is null)
            {
                (keysToRemove ??= new()).Add(entry.Key);
            }
        }

        if (keysToRemove != null)
        {
            foreach (string key in keysToRemove)
            {
                UnmappedProperties.Remove(key);
            }
        }
    }
}
```
If implementing the interface is impractical, then you could also try using [contract customization](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/custom-contracts) setting the equivalent [JsonTypeInfo.OnDeserialized](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.metadata.jsontypeinfo.ondeserialized?view=net-8.0) delegate.

**Comment by Drake53** [comment]
Thanks for the workaround, I managed to avoid the error by implementing `IJsonOnDeserialized` as you suggested.
