### ISSUE TITLE
Config binder gen: further tighten filtering constraint for input binding method invocations 

### ISSUE THREAD

**Issue by layomia** [dotnet/runtime#90687]
Address feedback from https://github.com/dotnet/runtime/pull/90619#discussion_r1296254354. cc @eiriktsarpalis.

**Comment by eiriktsarpalis** [comment]
We should aim doing this for RC2. cc @ericstj

**Comment by ericstj** [comment]
Fixed in RC2 with  https://github.com/dotnet/runtime/pull/90746
