### ISSUE TITLE
TryParse for email addresses 

### ISSUE THREAD

**Issue by Grauenwolf** [dotnet/runtime#907]
Currently we have to write this code:

```c#
        public static bool IsEmailAddress(this string value)
        {
            try
            {
                new System.Net.Mail.MailAddress(value);
                return true;
            }
            catch ()
            {
                return false;
            }
        }
```

MailAddress should have a TryParse method like Int32.TryParse.

## Rationale and Usage

Throwing and catching exceptions can have a significant impact on performance. So when possible there should be a non-throwing alternative for methods that commonly fail. An example would be `Int32.Parse` and `Int32.TryParse`.

There is also an impact on debugger. If you have the IDE set to "Break on All Exceptions" in order to see where an exception is being thrown, it will also catch this even though it is not interesting.

## Proposed API

```csharp
class MailAddress {
    public static MailAddress Parse(string address);
    public static MailAddress Parse(string address, string displayName);
    public static MailAddress Parse(string address, string displayName, Encoding displayNameEncoding);

    public static bool TryParse(string address, out MailAddress result);
    public static bool TryParse(string address, string displayName, out MailAddress result);
    public static bool TryParse(string address, string displayName, Encoding displayNameEncoding, out MailAddress result);
}
```

**Comment by davidsh** [comment]
>We should follow the Uri.TryCreate() pattern:

@terrajobst @scalablecory I don't think Uri is the best pattern to follow here. Most of the other types in .NET follow the Parse/TryParse pattern.

**Comment by scalablecory** [comment]
> `Uri.TryCreate` doesn't follow the convention and shouldn't be mimicked. As far as I can tell, it's the only class that uses `TryCreate` instead of `Parse`/`TryParse`.

The feedback API review had for this was that this does not follow `TryParse` convention:

```c#
    public static bool TryParse(string address, string displayName, Encoding displayNameEncoding, out MailAddress result);
```

`TryParse` typically only has a single string + optional style + optional formatter as input, i.e. every argument is intrinsic to parsing. What we have here with `MailAddress.TryParse`, though, is half-way between a parser and a constructor: some of the params are only used for initialization, not parsing.

The suggestion to use `TryCreate` came from `Uri.TryCreate` being prior art for a factory half-way between parser and constructor.

I hope this gives some context. @Grauenwolf @davidsh if you have strong opinion on design and can present a good counter-argument, I will take this back to API review.

**Comment by Grauenwolf** [comment]
Where are all of these extra parameters coming from? We're just asking for the parsing of a single string. 

    bool TryParse(string s, out MailAddress result)

While I assume it's possible, I can't think of any situation where I've had a separate display name and email address but didn't already know the email address was valid.

What we're looking for is to check a single column of values from a database or file feed. Usually as part of some sort of import job or data analysis.

**Comment by Grauenwolf** [comment]
Also note we do have multi-parameter TryParse methods. For example, `DateTime.TryParseExact`. 

https://docs.microsoft.com/en-us/dotnet/api/system.datetime.tryparseexact?view=netframework-4.8

Other multi-parameter TryParse include `Int32.TryParse` and `Timespan.TryParse`

So there is no basis for the claim that TryParse strictly has a single input parameter.

**Comment by scalablecory** [comment]
> Where are all of these extra parameters coming from? We're just asking for the parsing of a single string.

The proposed API currently mirrors all the ctors, which take more than a single string.

> there is no basis for the claim that TryParse strictly has a single input parameter.

This is not a claim anyone made.

Current `TryParse` take only parameters that are specifically *involved in parsing*. In the example above, `displayName` and `displayNameEncoding` are not used for parsing but instead to initialize values.

**Comment by MarcoRossignoli** [comment]
I'm working on this and I agree with @scalablecory if we want to return and "instance" of `MailAddress` from parse we should allow all "possible" combinations allowed by ctors, for intance current code allow to override the display name also if it's present inside address part, we would lose this. I believe that api should be simmetric in this case.
Would be different if the semantic is only a "validation" one like `bool MailAddress.IsValid(string address)` and after we'll compose code `validation+one of ctors`.

**Comment by scalablecory** [comment]
Triage: we like `TryCreate`, can adjust later if there is more discussion. @MarcoRossignoli  would you like me to assign this issue to you?

**Comment by MarcoRossignoli** [comment]
Yes @scalablecory feel free to assign to me.
