### ISSUE TITLE
Math.Pow behavior deviates from documentation

### ISSUE THREAD

**Issue by hgsenger** [dotnet/runtime#90725]
### Description

The documentation of [Math.Pow](https://learn.microsoft.com/en-us/dotnet/api/system.math.pow?view=net-7.0) states in the remarks section:
<html>
<body>

Parameters | Return value
-- | --
x or y = NaN. | NaN

</body>
</html>

The actual return value for x = NaN and y = 0.0 is 1.0 on .NET Core 3.1 and above.

### Reproduction Steps

using System;
					
public class Program
{
	public static void Main()
	{
		Console.WriteLine(Math.Pow(double.NaN, 0.0));
	}
}

### Expected behavior

Documentation and actual behavior match.

### Actual behavior

The actual return value for x = NaN and y = 0.0 is 1.0.

**Comment by tannergooding** [comment]
This would be a docs bug, contributions fixing it are welcome.

As per the IEEE 754 specification (both 2008 and 2019), section 9. Recommended operations:
> pow (x, ±0) is 1 if x is not a signaling NaN

.NET then further does not support signaling NaN and thus it behaves the same as a quiet NaN. That is, we do not raise an IEEE 754 floating-point exception, which is allowed under the "alternative exception handling" of the specification. We simply treat it as always disabled. If it was supported, then you'd see an exception for such an input and not get any result.
