### ISSUE TITLE
AddMetrics can initialize MetricsSubscriptionManager multiple times

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#90779]
### Description

Calling `AddMetrics` initializes the subscription manager:

https://github.com/dotnet/runtime/blob/64243bbf5e9ee53c0c4c5678f2cd8c7f1c9b4f6f/src/libraries/Microsoft.Extensions.Diagnostics/src/Metrics/MetricsServiceExtensions.cs#L33-L35

However, the way this is done isn't resilient to multiple calls to `AddMetrics` by app or library code.

Listeners are initialized multiple times:

https://github.com/dotnet/runtime/blob/64243bbf5e9ee53c0c4c5678f2cd8c7f1c9b4f6f/src/libraries/Microsoft.Extensions.Diagnostics/src/Metrics/MetricsSubscriptionManager.cs#L30-L36

### Reproduction Steps

```cs
services.AddMetrics();
services.AddMetrics();
```

### Expected behavior

Multiple `IConfigurateOptions<MetricsServiceExtensions+NoOpOptions>` aren't registered in DI. `MetricsSubscriptionManager` is initialized once.

### Actual behavior

Multiple `IConfigurateOptions<MetricsServiceExtensions+NoOpOptions>` is registered in DI. Each will instance will call initialize on `MetricsSubscriptionManager`.

I noticed this when the [AddMvc_Twice_DoesNotAddDuplicates](https://github.com/dotnet/aspnetcore/blob/445e2cf36afc3129e0626edaf8bcbf525a6d188e/src/Mvc/Mvc/test/MvcServiceCollectionExtensionsTest.cs#L160-L173) test in aspnetcore started throwing because there were duplicate config options.

**Comment by Tratcher** [comment]
This doesn't seem critical for rc1, there aren't currently any implementations of initialize other than the console, and the early adopters can mitigate this in their own code until rc2.
