### ISSUE TITLE
desired .NET 7.0 p/invoke signature for CallNtPowerInformation() is unclear

### ISSUE THREAD

**Issue by twest820** [dotnet/runtime#90785]
### Analyzer
SYSLIB10	Mark the method 'CallNtPowerInformation' with 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time

### Analyzer source
Visual Studio 17.6.5

### Describe the bug
Can't tell if a fix is possible here, SYSLIB10 needs to be suppressed, or if this is a .NET 7.0 compiler limitation.

### Steps To Reproduce
I've a .NET 6.0 assembly with the following p/invoke.
```C#
    internal static class NativeMethods
    {
        [DllImport("powrprof.dll", SetLastError = true)]
        private static extern UInt32 CallNtPowerInformation([In] Int32 InformationLevel,
                                                            [In] IntPtr lpInputBuffer,
                                                            [In] UInt32 nInputBufferSize,
                                                            [In, Out] PROCESSOR_POWER_INFORMATION[] lpOutputBuffer,
                                                            [In] UInt32 nOutputBufferSize);

        [StructLayout(LayoutKind.Sequential)]
        public struct PROCESSOR_POWER_INFORMATION
        {
            public uint Number;
            public uint MaxMhz;
            public uint CurrentMhz;
            public uint MhzLimit;
            public uint MaxIdleState;
            public uint CurrentIdleState;
        }
    }
```

As best I've been able to figure out so far, in .NET 7.0 this p/invoke is should be

```C#
    internal static partial class NativeMethodsNet7
    {
        [LibraryImport("powrprof.dll", SetLastError = true)]
        private static partial UInt32 CallNtPowerInformation(Int32 InformationLevel,
                                                             IntPtr lpInputBuffer,
                                                             UInt32 nInputBufferSize,
                                                             [MarshalAs(UnmanagedType.LPStruct, SizeParamIndex = 4)] PROCESSOR_POWER_INFORMATION[] lpOutputBuffer,
                                                             UInt32 nOutputBufferSize);

        [StructLayout(LayoutKind.Sequential)]
        public struct PROCESSOR_POWER_INFORMATION
        {
            public uint Number;
            public uint MaxMhz;
            public uint CurrentMhz;
            public uint MhzLimit;
            public uint MaxIdleState;
            public uint CurrentIdleState;
        }
    }
```

However, this method signature cannot be compiled in .NET 7.0 due to the error

> SYSLIB10	The 'MarshalAsAttribute.SizeParamIndex' configuration is not supported by source-generated P/Invokes. If the specified configuration is required, use a regular 'DllImport' instead.

So it seems possible this a situation where Roslyn and the compiler just end up pointing fingers at each other.

### Expected behavior
Microsoft is able to explain `DllImport` to `LibraryImport` migration in a simple way and conversions can be made in a few seconds, consistent with the claim "[LibraryImportAttribute is intended to be a straightforward conversion from DllImportAttribute](https://learn.microsoft.com/en-us/dotnet/standard/native-interop/pinvoke-source-generation)". Providing an updated signature for `CallNtPowerInformation()`—or noting that there isn't one)—over at pinvoke.net seems a simple solution, [but there isn't an entry](http://pinvoke.net/default.aspx/powrprof/CallNtPowerInformation.html) (and I don't think I should add one without more complete understanding).

### Actual behavior
Clearing SYSLIB10 appears complicated or perhaps not possible in this case. Having no luck with Microsoft's documentation, GitHub issues (of which there are several similar in various repos for various analogous calls), and StackOverflow questions (also several similar also no exact match). 

Kinda guessing SYSLIB10 is triggering optimistically here and should be suppressed for now but it'd be nice to confirm. There's enough complexity around updating `[In]`, `[Out]`, and use of `[MarshalAs]` it seems easy to miss finding a SYSLIB10 compatible .NET 7.0 signature for `CallNtPowerInformation()`.

**Comment by AaronRobinsonMSFT** [comment]
@twest820 I think the signature you want, based on the original signature and the fact that `PROCESSOR_POWER_INFORMATION` is blittable is below. 

```csharp
    internal static partial class NativeMethodsNet7
    {
        [LibraryImport("powrprof.dll", SetLastError = true)]
        private static partial UInt32 CallNtPowerInformation(Int32 InformationLevel,
                                                             IntPtr lpInputBuffer,
                                                             UInt32 nInputBufferSize,
                                                             [In, Out] PROCESSOR_POWER_INFORMATION[] lpOutputBuffer,
                                                             UInt32 nOutputBufferSize);

        [StructLayout(LayoutKind.Sequential)]
        public struct PROCESSOR_POWER_INFORMATION
        {
            public uint Number;
            public uint MaxMhz;
            public uint CurrentMhz;
            public uint MhzLimit;
            public uint MaxIdleState;
            public uint CurrentIdleState;
        }
    }
```

**Comment by jtschuster** [comment]
To clarify some of the issues here, you also can use [MarshalUsingAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshalling.marshalusingattribute) and specify the [CountElementName](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshalling.marshalusingattribute.countelementname?view=net-7.0#system-runtime-interopservices-marshalling-marshalusingattribute-countelementname) to indicate the length of the array. The generated code will be identical. In source-generated interop, arrays are handled specially, so there is no need to specify marshalling for them. In addition, since your struct is blittable and doesn't require marshalling, there is no need to specify marshalling for the elements.

@twest820 If anything else is/was unclear when working through this, please let us know and we can answer questions and update the docs.

@AaronRobinsonMSFT @jkoritzinsky Should we maybe point to the MarshalUsingAttribute in the error message or add an aka.ms link for when the MarshalAs is unsupported? At the very least we should reference it in the documentation alongside MarshalAs [here](https://learn.microsoft.com/en-us/dotnet/standard/native-interop/pinvoke-source-generation)

**Comment by AaronRobinsonMSFT** [comment]
> Should we maybe point to the MarshalUsingAttribute in the error message or add an aka.ms link for when the MarshalAs is unsupported?

Sounds like a fine .NET 9 fix.

> At the very least we should reference it in the documentation alongside MarshalAs [here](https://learn.microsoft.com/en-us/dotnet/standard/native-interop/pinvoke-source-generation)

Makes sense to me.

@twest820 I'm going to close this for now. Please let us know if you have any more questions.

**Comment by twest820** [comment]
Hi @AaronRobinsonMSFT, I just had chance to check and Visual Studio 17.7.1 can't compile that signature.
```
1>  NativeMethodsNet7.cs(36,102,36,116): error SYSLIB1051: The provided '[In]' and '[Out]' attributes on this parameter are unsupported on this parameter. The generated source will not handle marshalling of parameter 'lpOutputBuffer'.
```
