### ISSUE TITLE
How can i  enable promotionstructs opt flag ?

### ISSUE THREAD

**Issue by monstercatss** [dotnet/runtime#90784]
Hello,Im first debug corerun in linux 
Im already set COMPlus_JitMinopt=0 and COMPlus_JitNoStructPromotion=0 

but JitDump show promotion opt flag not enabled
 *************** In fgPromoteStructs()
   promotion opt flag not enabled
 *************** Finishing PHASE Morph - Promote Structs

  

```
  if (!opts.OptEnabled(CLFLG_STRUCTPROMOTE))
    {
        JITDUMP("  promotion opt flag not enabled\n");
        return;
    }

    if (fgNoStructPromotion)
    {
        JITDUMP("  promotion disabled by JitNoStructPromotion\n");
        return;
    }
```

**Comment by jakobbotsch** [comment]
Promotion is enabled by default when the JIT is optimizing. So the JIT is not optimizing in the codegen you are looking at. That's usually because of tiered compilation (can be disabled with `DOTNET_TieredCompilation=0`) or because the assembly containing the method was compiled in debug, so that the JIT is producing debuggable code. If you share the full dump we would be able to know exactly.

**Comment by monstercatss** [comment]
head dump
> ****** START compiling StructExample.Program:Main(System.String[]) (MethodHash=a617ca68)
> Generating code for Unix x64
> OPTIONS: compCodeOpt = BLENDED_CODE
> OPTIONS: compDbgCode = true
> OPTIONS: compDbgInfo = true
> OPTIONS: compDbgEnC  = false
> OPTIONS: compProcedureSplitting   = false
> OPTIONS: compProcedureSplittingEH = false
> IL to import:
> IL_0000  00                nop         
> IL_0001  12 00             ldloca.s     0x0
> IL_0003  1f 0a             ldc.i4.s     0xA
> IL_0005  7d 01 00 00 04    stfld        0x4000001
> IL_000a  12 00             ldloca.s     0x0
> IL_000c  1f 14             ldc.i4.s     0x14
> IL_000e  7d 02 00 00 04    stfld        0x4000002
> IL_0013  72 01 00 00 70    ldstr        0x70000001
> IL_0018  12 00             ldloca.s     0x0
> IL_001a  7c 01 00 00 04    ldflda       0x4000001
> IL_001f  28 0b 00 00 0a    call         0xA00000B
> IL_0024  72 1d 00 00 70    ldstr        0x7000001D
> IL_0029  12 00             ldloca.s     0x0
> IL_002b  7c 02 00 00 04    ldflda       0x4000002
> IL_0030  28 0b 00 00 0a    call         0xA00000B
> IL_0035  28 0c 00 00 0a    call         0xA00000C
> IL_003a  28 0d 00 00 0a    call         0xA00000D
> IL_003f  00                nop         
> IL_0040  2a                ret         
> 
> lvaSetClass: setting class for V00 to (00007FA461EFE1D0) System.String[] 
> Arg #0    passed in register(s) rdi
> 
> lvaGrabTemp returning 2 (V02 tmp0) (a long lifetime temp) called for OutgoingArgSpace.
> ; Initial local variable assignments
> ;
> ;  V00 arg0              ref  class-hnd
> ;  V01 loc0           struct <StructExample.Point, 8>
> ;  V02 OutArgs        lclBlk <na>  "OutgoingArgSpace"
> *************** In compInitDebuggingInfo() for StructExample.Program:Main(System.String[])
> getVars() returned cVars = 0, extendOthers = true
> info.compVarScopesCount = 2
>     	VarNum 	LVNum 	      Name 	Beg 	End
>  0: 	00h 	00h 	  V00 arg0 	000h   	041h
>  1: 	01h 	01h 	  V01 loc0 	000h   	041h
> New Basic Block BB01 [0000] created.
> New scratch BB01
> Debuggable code - Add new BB01 [0000] to perform initialization of variables
> info.compStmtOffsetsCount    = 0
> info.compStmtOffsetsImplicit = 0007h ( STACK_EMPTY NOP CALL_SITE )
> *************** In fgFindBasicBlocks() for StructExample.Program:Main(System.String[])
> Jump targets:
>   none
> New Basic Block BB02 [0001] created.
> BB02 [000..041)
> CLFLG_MINOPT set for method StructExample.Program:Main(System.String[])
> IL Code Size,Instr   65,  19, Basic Block count   2, Local Variable Num,Ref count   3,  4 for method StructExample.Program:Main(System.String[])
> IL Code Size,Instr   65,  19, Basic Block count   2, Local Variable Num,Ref count   3,  4 for method StructExample.Program:Main(System.String[])
> OPTIONS: opts.MinOpts() == true
> Basic block list for 'StructExample.Program:Main(System.String[])'


```
 // true if the CLFLG_* for an optimization is set.
        bool OptEnabled(unsigned optFlag)
        {
            return !!(compFlags & optFlag);
        }

```
compFlags=256  optFlat=1024 ,it always sreturn 0

**Comment by jakobbotsch** [comment]
```
OPTIONS: compDbgCode = true
```
This means that the JIT is producing debuggable code. So your `StructExample` was compiled in debug. Compile it in the release configuration and you should see promotion enabled.

**Comment by En3Tho** [comment]
@monstercatss A side question: what tooling/ide you are using to debug it in Linux?

**Comment by monstercatss** [comment]
> ```
> 
> OPTIONS: compDbgCode = true
> 
> ```
> 
> This means that the JIT is producing debuggable code. So your `StructExample` was compiled in debug. Compile it in the release configuration and you should see promotion enabled.

ok，thank you

**Comment by monstercatss** [comment]
> @monstercatss A side question: what tooling/ide you are using to debug it in Linux?

most of time i just use gdb，i also try clion remote

**Comment by monstercatss** [comment]
@jakobbotsch 
`#define MAX_NumOfFieldsInPromotableStruct 4 // Maximum number of fields in promotable struct`
Sorry to bother you, do struct promote must have a four field limit?
Why not optimize for more than four fields？

**Comment by jakobbotsch** [comment]
@monstercatss Before .NET 8 we had one promotion mechanism which indeed only supported promotion with up to 4 fields, mostly for technical reasons due to how the promotion pass worked and how promoted structs were represented in the JIT.

In .NET 8 we introduced a new promotion optimization that can support promotion for structs with an arbitrary number of fields. See #76928 and #88090 that enabled it by default. The source for this new promotion pass lives in promotion.cpp, and it currently runs in addition to the old promotion pass and takes over when the old promotion pass did not kick in.
