### ISSUE TITLE
[API Proposal]: Implement INumber<T> for vector types and operator interfaces for matrix types.

### ISSUE THREAD

**Issue by moonheart08** [dotnet/runtime#90781]
### Background and motivation

This came about while working on heavily generic code for implementation of a DSL. The commands in the DSL for arithmetic make use of generic arguments to determine their type(s), and do **not** use reflection or code generation, instead using the interfaces IAdditionOperators, ISubtractionOperators, IMultiplyOperators, IComparisonOperators, etc, for their supported types.

This works fine for the entire set of numeric types in C#, but requires special purpose, copy-pasted implementations for each vector and matrix type (and combinations), which is needlessly painful.

I initially intended to only propose the operator interfaces, however Vector fits the mold of "a number" well and I think it'd be pointless to not just implement the full interface. An open question is what the definition of ++ and -- should be, and if they're deemed invalid, should every member of INumberBase except those two interfaces be applied, instead?

Implementing these interfaces for Vector<T> seems to currently be out of the question due to the dual nature of that type (providing both float and integer versions).

My point of view here is from DSL creation, so extra perspectives would be good, but I don't see a negative to having these interfaces on a number-like type.

### API Proposal

```csharp
public struct Vector2 : ... 
    INumber<Vector2>
    IMultiplyOperators<Vector2, Single, Vector2>,
    IDivideOperators<Vector2, Single, Vector2>
    
[extend above to all Vector types]

public struct Quaternion : ... 
    INumber<Quaternion>,
    IMultiplyOperators<Quaternion, Single, Quaternion>


public struct Matrix3x2 : ... 
    IAdditionOperators<Matrix3x2, Matrix3x2, Matrix3x2>,
    ISubtractionOperators<Matrix3x2, Matrix3x2, Matrix3x2>,
    IMultiplicativeIdentity<Matrix3x2, Matrix3x2>,
    IMultiplyOperators<Matrix3x2, Matrix3x2, Matrix3x2>,
    IMultiplyOperators<Matrix3x2, Single, Matrix3x2>,
    IUnaryNegationOperators<Matrix3x2, Matrix3x2>

public struct Matrix4x4 : ... 
    IAdditionOperators<Matrix4x4, Matrix4x4, Matrix4x4>,
    ISubtractionOperators<Matrix4x4, Matrix4x4, Matrix4x4>,
    IMultiplicativeIdentity<Matrix4x4, Matrix4x4>,
    IMultiplyOperators<Matrix4x4, Matrix4x4, Matrix4x4>,
    IMultiplyOperators<Matrix4x4, Single, Matrix4x4>,
    IUnaryNegationOperators<Matrix4x4, Matrix4x4>
```

### API Usage

```csharp
public sealed class ImplHolder {
    public TOut MyCustomAdd<TLeft, TRight, TOut>(TLeft left, TRight right)
        where TLeft: IAdditionOperators<TLeft, TRight, TOut>
    {
        return left + right;
    }
}

// ...Somehow get the concrete version of this. My DSL's handling of doing this is too complex to fit here and not relevant,
// so we'll condense it down to a magic function,
//     Func<object?, object?, object?> OperandImplFinder(Type implHolder, Type left, Type right, out Type result)
// which takes a given signature and procures a "shim" we can use to call it. No need for the details of how it works.

object left = ... // We have no idea what this is!
object right = ... // Same here.

var myImpl = OperandImplFinder(typeof(ImplHolder), left.GetType(), right.GetType(), out _);

var result = myImpl(left, right); // Yay! Addition!

```

### Alternative Designs

I'm not sure how one would take an alternate approach to "add some interfaces", unfortunately.

### Risks

No risks **to my knowledge**, aside from the edge case that if INumber<T> were implemented in full for the vector types, the meaning of `++` and `--` would be ambiguous.

**Comment by moonheart08** [comment]
Note: I am 100% up to implementing this myself.

**Comment by tannergooding** [comment]
This is an area that needs more thought/consideration.

We likely wouldn't be implementing `INumber<T>` here but rather defining and implementing some `interface IVector<TSelf, T> where TSelf : IVector, T> where T : INumber<T>` that itself implements the relevant `I*Operators<TSelf, TSelf, TSelf>` interfaces and further defines the special overloads such as `operator *(TSelf left, T right)`.

The general pattern is being experimented with for the `Vector<T>` and `Vector64/128/256/512<T>` types using an internal `ISimdVector` interface. The plan would be to have a separate proposal for that and to expose it in the future if appropriate.

**Comment by tannergooding** [comment]
Going to close this given the above.

Depending on how `ISimdVector` turns out for internal usage, we may look at providing some `IVector` interface which covers this functionality.
