### ISSUE TITLE
Incomplete type errors in lldb/gdb when when using clang-13 or newer

### ISSUE THREAD

**Issue by a74nh** [dotnet/runtime#90791]
### Description

Building runtime with clang-13 or newer, both lldb and gdb will fail to parse many of the common c++ objects.

### Reproduction Steps

build.sh -rc checked -lc release -s clr+libs --clang13
gdb --args corerun helloworld.dll
b compCompile
run
p *this

Similar reproduction with lldb

### Expected behavior

```
(gdb) p *this
$1 = {static MAX_SPILL_TEMP_SIZE = 24, static CHECK_SPILL_ALL = 4294967295, static CHECK_SPILL_NONE = 4294967294,
  static MAX_TREE_SIZE = 200, static jitTotalMethodCompiled = 0, static jitNestingLevel = 0, static MAX_CSE_CNT = 64,
  static MIN_CSE_COST = 2, static s_optCSEhashSizeInitial = 128, static s_optCSEhashGrowthFactor = 2,
  static s_optCSEhashBucketSize = 4, static optEarlyPropRecurBound = 5,
etc
```

### Actual behavior

```
(gdb) p *this
$1 = <incomplete type>
```

### Regression?

Works with llvm-12

### Known Workarounds

Build with llvm-12

### Configuration

X64 or Arm64
Ubuntu Linux 22.04

### Other information

Feels like this is bad DWARF information.
Possibly related to https://github.com/dotnet/runtime/issues/90209 ?

**Comment by janvorli** [comment]
> Possibly related to #90209 ?

The referenced issue is for NativeAOT only where our code generates the DWARF info.

**Comment by janvorli** [comment]
This is clearly specific to some types only. I've tried it with many other types and it worked fine.

**Comment by janvorli** [comment]
I've found that adding `-glldb` option to the compiler options fixes the problem (for both lldb and gdb)
@a74nh if you want to give it a try, you can modify `eng/native/configurecompiler.cmake` by adding 
```cmake
add_compile_options(-glldb)
```
after line 26

**Comment by a74nh** [comment]
> I've found that adding `-glldb` option to the compiler options fixes the problem (for both lldb and gdb) @a74nh if you want to give it a try, you can modify `eng/native/configurecompiler.cmake` by adding
> 
> ```cmake
> add_compile_options(-glldb)
> ```
> 
> after line 26

This works for me, thanks! I'll raise a patch.

It feels odd that we need this - surely `-g` should just work for everything. Quite possibly an llvm issue rather than a runtimes issue.
