### ISSUE TITLE
Is there any way to remove DotNetRuntimeDebugHeader

### ISSUE THREAD

**Issue by Jddl** [dotnet/runtime#90838]
I know, this is similar to #79197.
I confirmed that using` <IlcGenerateStackTraceData>false</IlcGenerateStackTraceData>` does not remove DotNetRuntimeDebugHeader .

![image](https://github.com/dotnet/runtime/assets/11550798/ff458365-6352-4472-b2e9-fff505868ee4)

https://github.com/dotnet/runtimelab/issues/739
https://github.com/dotnet/runtimelab/pull/1479

```
#ifdef TARGET_WINDOWS
#pragma comment (linker, "/EXPORT:DotNetRuntimeDebugHeader,DATA")
#endif
```

**Comment by jkotas** [comment]
Could you please also tell us a bit about your scenario? Why do you want to remove this export?

There is no built-in way to suppress this export currently.

**Comment by Jddl** [comment]
Well, maybe I'm a bit of a clean freak, I want the export to be clean like c language, at least in release mode, it's just a personal opinion.  Since it can't be remove, that's okay，Thank you for your reply.
