### ISSUE TITLE
Equals on EventId from Microsoft.Extensions.Logging checks only ID

### ISSUE THREAD

**Issue by davidkaya** [dotnet/runtime#90831]
### Description

We use OpenTelemetry in our project and I have noticed that ASP.NET Core events with EventId.Id set to `0` do not get exported with:

-  [OTLP Exporter](https://github.com/open-telemetry/opentelemetry-dotnet/blob/5784b45c4e310fc54d84278891bb22d6b93a1246/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/LogRecordExtensions.cs#L96-L99)
- [Geneva Exporter](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/78598baf6f00d411539be599ed6a53b03bbeb70c/src/OpenTelemetry.Exporter.Geneva/TLDExporter/TldLogExporter.cs#L307)

The reason is that both OTLP and Geneva Exporter export the `EventId` only if it is not `default`. The thing with `EventId` is that `new EventId(0, "An Event Id") == default` returns `true`. That means that following events logged by ASP.NET Core will never be exported by OTLP (or Geneva) Exporter:

- https://github.com/search?q=repo%3Adotnet%2Faspnetcore%20EventId(0&type=code
- https://github.com/search?q=repo%3Adotnet%2Faspnetcore+LoggerMessage%280&type=code

My questions are:

1. Is EventId with Id set to 0 expected/supported/intended?
2. Isn't `new EventId(0, "An event") == new EventId(0, "A different event")` returning `true` a bug? Because that would mean that all the logged messages in the ASP.NET Core with matching IDs are equal, which is not the case. It looks like `Equals` in `EventId` checks only `Id` https://github.com/dotnet/runtime/blob/54fbd47c861c1c9f811444d26d4d7cfd31a3fe0c/src/libraries/Microsoft.Extensions.Logging.Abstractions/src/EventId.cs#L77-L80

I understand that theoretically, this could be more of an issue in OTEL exporters, they could decide to export the `EventId` if `EventId.Id != default && EventId.Name != default` to rule out log records which do not have an event associated. But is `new EventId(0, "An event") == new EventId(0, "A different event")` returning `true` really intended?

### Reproduction Steps

`Console.WriteLine(new EventId(0, "An Event") == new EventId(0, "A Different Event"))`

### Expected behavior

Reproduction steps print out `false`.

### Actual behavior

Reproduction steps print out `true`.

**Comment by cdbullard** [comment]
From [the documentation](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.eventid?view=dotnet-plat-ext-7.0) for the EventID struct, it does _seem_ that this design for considering two events equal solely based on the `Id` property is intentional. Digging into this a bit further, I found [this comment](https://github.com/dotnet/extensions/pull/1900#discussion_r298445264) on the PR from July 2019 which added this documentation and it also appears this was ambiguous then as well.

**Comment by tommcdon** [comment]
@noahfalk @davmason

**Comment by davmason** [comment]
I'm not involved enough in the OTel API decisions to make a call, @noahfalk @CodeBlanch @tarekgh would be better to answer this

**Comment by CodeBlanch** [comment]
My personal opinion is that EventId.Equals is broken. Two structs with different fields shouldn't be considered equal, right? At least it feels strange, maybe there are other structs in runtime with that behavior. What I tell users is to always start their events at 1.

Could OTel exporters have their own equality logic and not use the equality as defined on the type? Of course. Does that make sense to do? 🤷 It certainly isn't something we can enforce all exporters do correctly (many don't live in the OTel repos) so it might be nice to fix in runtime.
