### ISSUE TITLE
[8.0] [mono] Test process gets killed

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#90834]
### Error Blob

```json
{
  "ErrorMessage": "Tests' END OF WORK ITEM LOG: Command timed out, and was killed]",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Reproduction Steps

This failure happens often in System.Runtime.Tests specifically.

- PR: https://github.com/dotnet/runtime/pull/90809
- Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=378797&view=logs&j=1f44e919-17d8-5098-631c-31ef11f9e57b&t=d617d884-da52-5b82-bd49-f7613b408af4&l=87
- Queue: `Libraries Test Run release mono linux x64 Debug`
- Log: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-pull-90809-merge-956e379e01714658b2/System.Runtime.Tests/1/console.73e1394a.log?helixlogtype=result
- Output:

```
Console log: 'System.Runtime.Tests' from job 956e379e-0171-4658-b2cd-b234086ec9af workitem 50980a74-2595-4c8f-b4a1-bbcc0991bb7b (ubuntu.1804.amd64.open.svc) executed on machine a005SZ1 running Linux-5.4.0-1109-azure-x86_64-with-Ubuntu-18.04-bionic
+ ./RunTests.sh --runtime-path /datadisks/disk1/work/9F780922/p
----- start Fri Aug 18 17:28:49 UTC 2023 =============== To repro directly: =====================================================
pushd .
/datadisks/disk1/work/9F780922/p/dotnet exec --runtimeconfig System.Runtime.Tests.runtimeconfig.json --depsfile System.Runtime.Tests.deps.json xunit.console.dll System.Runtime.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=AdditionalTimezoneChecks -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
/datadisks/disk1/work/9F780922/w/A2490973/e /datadisks/disk1/work/9F780922/w/A2490973/e
  Discovering: System.Runtime.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Runtime.Tests (found 9160 of 9278 test cases)
  Starting:    System.Runtime.Tests (parallel test collections = on, max threads = 2)
    System.Tests.ArrayEnumeratorTests_int.ICollection_Generic_Remove_ReferenceRemovedFromCollection [SKIP]
      Condition(s) not met: "IsPreciseGcSupported"
['System.Runtime.Tests' END OF WORK ITEM LOG: Command timed out, and was killed]
```

 ### Known issue validation
**Build: :mag_right:** 
**Result validation: :warning:** Validation could not be done without an Azure DevOps build URL on the issue. Please add it to the "**Build: :mag_right:**" line.
**Validation performed at:** 8/29/2023 9:18:10 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[390358](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390358)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390358&view=ms.vss-test-web.build-test-results-tab&runId=8374390&resultId=195975)|dotnet/runtime#91314|
|[390315](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390315)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390315&view=ms.vss-test-web.build-test-results-tab&runId=8372588&resultId=195952)|dotnet/runtime#91239|
|[390327](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390327)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390327&view=ms.vss-test-web.build-test-results-tab&runId=8373528&resultId=195589)||
|[390312](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390312)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390312&view=ms.vss-test-web.build-test-results-tab&runId=8373130&resultId=195595)|dotnet/runtime#91240|
|[390304](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390304)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390304&view=ms.vss-test-web.build-test-results-tab&runId=8373092&resultId=195691)|dotnet/runtime#91311|
|[390232](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390232)|dotnet/runtime|[System.Globalization.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390232&view=ms.vss-test-web.build-test-results-tab&runId=8370694&resultId=200024)|dotnet/runtime#90970|
|[390131](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390131)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390131&view=ms.vss-test-web.build-test-results-tab&runId=8366246&resultId=195939)|dotnet/runtime#91303|
|[389716](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389716)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389716&view=ms.vss-test-web.build-test-results-tab&runId=8355760&resultId=195691)|dotnet/runtime#91293|
|[389636](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389636)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389636&view=ms.vss-test-web.build-test-results-tab&runId=8353138&resultId=196068)|dotnet/runtime#91290|
|[389641](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389641)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389641&view=ms.vss-test-web.build-test-results-tab&runId=8353936&resultId=195595)|dotnet/runtime#91291|
|[389595](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389595)|dotnet/runtime|[System.Net.NetworkInformation.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389595&view=ms.vss-test-web.build-test-results-tab&runId=8352040&resultId=200278)||
|[389529](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389529)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389529&view=ms.vss-test-web.build-test-results-tab&runId=8350968&resultId=196806)|dotnet/runtime#91283|
|[389491](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389491)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389491&view=ms.vss-test-web.build-test-results-tab&runId=8350354&resultId=195565)||
|[389478](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389478)|dotnet/runtime|[Microsoft.Extensions.Configuration.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389478&view=ms.vss-test-web.build-test-results-tab&runId=8349842&resultId=205355)|dotnet/runtime#91239|
|[389287](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389287)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389287&view=ms.vss-test-web.build-test-results-tab&runId=8346670&resultId=195593)|dotnet/runtime#91267|
|[389320](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389320)|dotnet/runtime|[System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389320&view=ms.vss-test-web.build-test-results-tab&runId=8345508&resultId=182018)|dotnet/runtime#91216|
|[389280](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389280)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389280&view=ms.vss-test-web.build-test-results-tab&runId=8344864&resultId=196009)|dotnet/runtime#91264|
|[389142](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389142)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389142&view=ms.vss-test-web.build-test-results-tab&runId=8342628&resultId=196804)|dotnet/runtime#91262|
|[388978](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388978)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388978&view=ms.vss-test-web.build-test-results-tab&runId=8337234&resultId=197678)||
|[388942](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388942)|dotnet/runtime|[normal-System.Threading.Tasks.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388942&view=ms.vss-test-web.build-test-results-tab&runId=8336490&resultId=173687)||
|[388902](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388902)|dotnet/runtime|[Microsoft.Extensions.HostFactoryResolver.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388902&view=ms.vss-test-web.build-test-results-tab&runId=8334882&resultId=205242)|dotnet/runtime#91176|
|[388878](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388878)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388878&view=ms.vss-test-web.build-test-results-tab&runId=8334362&resultId=196066)|dotnet/runtime#91240|
|[388706](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388706)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388706&view=ms.vss-test-web.build-test-results-tab&runId=8334326&resultId=195593)|dotnet/runtime#91245|
|[388797](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388797)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388797&view=ms.vss-test-web.build-test-results-tab&runId=8333016&resultId=195594)|dotnet/runtime#91237|
|[388672](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388672)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388672&view=ms.vss-test-web.build-test-results-tab&runId=8329196&resultId=211026)|dotnet/runtime#91247|
|[388667](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388667)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388667&view=ms.vss-test-web.build-test-results-tab&runId=8330128&resultId=192118)|dotnet/runtime#91246|
|[388556](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388556)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388556&view=ms.vss-test-web.build-test-results-tab&runId=8327704&resultId=195615)|dotnet/runtime#89952|
|[388379](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388379)|dotnet/runtime|[System.IO.Pipes.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388379&view=ms.vss-test-web.build-test-results-tab&runId=8321204&resultId=204850)|dotnet/runtime#91231|
|[388449](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388449)|dotnet/runtime|[System.Net.Http.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388449&view=ms.vss-test-web.build-test-results-tab&runId=8322070&resultId=181405)||
|[388406](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388406)|dotnet/runtime|[System.Security.Cryptography.OpenSsl.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388406&view=ms.vss-test-web.build-test-results-tab&runId=8321262&resultId=181181)|dotnet/runtime#91190|
|[388166](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388166)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388166&view=ms.vss-test-web.build-test-results-tab&runId=8315866&resultId=195692)|dotnet/runtime#91218|
|[388145](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388145)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388145&view=ms.vss-test-web.build-test-results-tab&runId=8315166&resultId=195691)|dotnet/runtime#91154|
|[387880](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387880)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387880&view=ms.vss-test-web.build-test-results-tab&runId=8310336&resultId=194586)|dotnet/runtime#91172|
|[387528](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387528)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387528&view=ms.vss-test-web.build-test-results-tab&runId=8299264&resultId=195583)|dotnet/runtime#91189|
|[387355](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387355)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387355&view=ms.vss-test-web.build-test-results-tab&runId=8294002&resultId=195605)|dotnet/runtime#89952|
|[387323](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387323)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387323&view=ms.vss-test-web.build-test-results-tab&runId=8293014&resultId=196056)|dotnet/runtime#90982|
|[387294](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387294)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387294&view=ms.vss-test-web.build-test-results-tab&runId=8292782&resultId=196020)|dotnet/runtime#91171|
|[387117](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387117)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387117&view=ms.vss-test-web.build-test-results-tab&runId=8286502&resultId=195584)|dotnet/runtime#91160|
|[387116](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387116)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387116&view=ms.vss-test-web.build-test-results-tab&runId=8286068&resultId=173008)||
|[387106](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387106)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387106&view=ms.vss-test-web.build-test-results-tab&runId=8285514&resultId=195577)||
|[386969](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386969)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386969&view=ms.vss-test-web.build-test-results-tab&runId=8279886&resultId=195953)|dotnet/runtime#91154|
|[386929](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386929)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386929&view=ms.vss-test-web.build-test-results-tab&runId=8279566&resultId=195583)|dotnet/runtime#90982|
|[386516](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386516)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386516&view=ms.vss-test-web.build-test-results-tab&runId=8266656&resultId=195566)||
|[386357](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386357)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386357&view=ms.vss-test-web.build-test-results-tab&runId=8262326&resultId=195576)||
|[386352](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386352)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386352&view=ms.vss-test-web.build-test-results-tab&runId=8261766&resultId=196055)|dotnet/runtime#91133|
|[386233](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386233)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386233&view=ms.vss-test-web.build-test-results-tab&runId=8259474&resultId=195582)|dotnet/runtime#91074|
|[386241](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386241)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386241&view=ms.vss-test-web.build-test-results-tab&runId=8258672&resultId=196056)|dotnet/runtime#91107|
|[386139](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386139)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386139&view=ms.vss-test-web.build-test-results-tab&runId=8256076&resultId=195582)|dotnet/runtime#91123|
|[386115](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386115)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386115&view=ms.vss-test-web.build-test-results-tab&runId=8254310&resultId=195582)|dotnet/runtime#91122|
|[386015](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386015)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386015&view=ms.vss-test-web.build-test-results-tab&runId=8251650&resultId=195582)|dotnet/runtime#91116|
|[385733](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385733)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385733&view=ms.vss-test-web.build-test-results-tab&runId=8241216&resultId=195582)|dotnet/runtime#90518|
|[385671](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385671)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385671&view=ms.vss-test-web.build-test-results-tab&runId=8239130&resultId=195582)|dotnet/runtime#91102|
|[385446](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385446)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385446&view=ms.vss-test-web.build-test-results-tab&runId=8236334&resultId=195582)|dotnet/runtime#89405|
|[385484](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385484)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385484&view=ms.vss-test-web.build-test-results-tab&runId=8236224&resultId=195394)||
|[385364](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385364)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385364&view=ms.vss-test-web.build-test-results-tab&runId=8228874&resultId=197859)||
|[385005](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385005)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385005&view=ms.vss-test-web.build-test-results-tab&runId=8225244&resultId=195582)|dotnet/runtime#89102|
|[384990](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384990)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384990&view=ms.vss-test-web.build-test-results-tab&runId=8223646&resultId=195582)|dotnet/runtime#91077|
|[384688](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384688)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384688&view=ms.vss-test-web.build-test-results-tab&runId=8214886&resultId=195520)|dotnet/runtime#91057|
|[384597](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384597)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384597&view=ms.vss-test-web.build-test-results-tab&runId=8212038&resultId=195581)|dotnet/runtime#91050|
|[384450](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384450)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384450&view=ms.vss-test-web.build-test-results-tab&runId=8205280&resultId=195520)|dotnet/runtime#91033|
|[384447](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384447)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384447&view=ms.vss-test-web.build-test-results-tab&runId=8205056&resultId=195581)|dotnet/runtime#91032|
|[384038](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384038)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384038&view=ms.vss-test-web.build-test-results-tab&runId=8201510&resultId=199703)|dotnet/runtime#90790|
|[383772](https://dev.azure.com/dnceng-public/public/_build/results?buildId=383772)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=383772&view=ms.vss-test-web.build-test-results-tab&runId=8190128&resultId=195581)|dotnet/runtime#88034|
|[382759](https://dev.azure.com/dnceng-public/public/_build/results?buildId=382759)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=382759&view=ms.vss-test-web.build-test-results-tab&runId=8188516&resultId=195581)|dotnet/runtime#90954|
|[378797](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378797)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378797&view=ms.vss-test-web.build-test-results-tab&runId=8066972&resultId=195836)|dotnet/runtime#90809|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|18|64|65|

**Comment by carlossanlop** [comment]
Here's another 8.0 repro. This time in osx, but also mono:

- Affected PR: https://github.com/dotnet/runtime/pull/91057
- Queue: `Libraries Test Run release mono osx x64 Debug`
- Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=384688&view=logs&j=ab5d32de-6d19-5068-e03b-b69cf4db6cd5&t=eb2a8345-733e-5823-7aa4-11fb75e4a1ff&l=55
- Log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-91057-merge-18f6ab2e6a76443fb6/System.Runtime.Tests/1/console.dbd0bad1.log?helixlogtype=result
- Output:
```
...
    System.Tests.WeakReferenceTests.NonGeneric [SKIP]
      Condition(s) not met: "IsPreciseGcSupported"
    System.Tests.ArrayEnumeratorTests_int.ICollection_Generic_Remove_ReferenceRemovedFromCollection [SKIP]
      Condition(s) not met: "IsPreciseGcSupported"
['System.Runtime.Tests' END OF WORK ITEM LOG: Command timed out, and was killed]
```

**Comment by akoeplinger** [comment]
I was able to reproduce the deadlock and debug it together with @BrzVlad, he's going to open a PR.

**Comment by carlossanlop** [comment]
> I was able to reproduce the deadlock and debug it together with @BrzVlad, he's going to open a PR.

Thank you very much!
