### ISSUE TITLE
.NET runtime's method of loading Assemblies breaks Win32 LoadLibrary behavior

### ISSUE THREAD

**Issue by wasabii** [dotnet/runtime#90839]
This one is unlikely to be fixed, because it's a consequence of a design which likely isn't going to go anywhere. But maybe there is a creative work around somebody might know.

I have a situation where I have a native library, named 'foo.dll'. This native library is built in C, and depends on another native library 'bar.dll'. I would like to load 'foo.dll' into the .NET process. To do so, I can invoke one of the many ways of dynamically loading native libraries in .NET NativeLibrary, DllImport, or just P/Invoking to LoadLibrary or LoadLibraryEx. In all cases, I would do so by the full path to the assembly, to limit resolution problems.

In all cases, this fails if there exists any managed assembly named 'bar.dll'.

Why is this?

Because the LoadLibrary Win32 function attempts to load dependencies of the library you ask for. And the first step in loading such a library is to check whether a module with the specified name already exists. And because .NET loads MANAGED assemblies using LoadLibrary (for various reasons), there is a loaded module with the name 'bar.dll'. Even though it's managed, and has nothing at all to do with this. So, LoadLibrary, given a full path locations 'foo.dll'. But then tries to load the dependents of foo.dll, such as bar.dll, and in this case, the first (and apparently unavoidable step) is to check if it's already loaded. Which it is. Just, not the right one.

Real world example which I'm trying to solve: I am the current maintainer of IKVM. We are a JDK written in .NET. We distribute a .NET executable named java.exe. Because of how .NET Core works, the .exe is just the apphost, and instead, there exists now a managed assembly named java.dll, which is loaded.

But, we also have some native code peices. Written in C. There's a dozen of these, net.dll, nio.dll, jvm.dll..... and java.dll. And that last one is an issue. net.dll, nio.dll, etc, all depend on java.dll. And as part of our JNI implementation, we have to use LoadLibrary to try to load net.dll. And it fails because it depends on a java.dll, but the executable itself is a module named java.dll (launched by java.exe). Doesn't matter where we move the native libraries: these are differnet files. But merely because their name is the same, we can't do this.

I can't come up with anyway to alter the behavior of either LoadLibrary or LoadLibraryEx to avoid this first step check of whether the module already exists.

**Comment by jkotas** [comment]
> Because of how .NET Core works, the .exe is just the apphost, and instead, there exists now a managed assembly named java.dll, which is loaded.

Try publishing the apphost as single-file (framework-dependent) app. It is going to embed java.dll into the apphost binary and the file is no longer be on the disk and loaded as regular .dll, and the collision with your unmanaged java.dll should be solved.
```
<PublishSingleFile>true</PublishSingleFile>
<SelfContained>false</SelfContained>
```

> I can't come up with anyway to alter the behavior of either LoadLibrary or LoadLibraryEx to avoid this first step check of whether the module already exists.

[Activation contexts](https://learn.microsoft.com/en-us/windows/win32/sbscs/activation-contexts) can be used to force the Windows loader to load multiple version of the same .dll.

**Comment by wasabii** [comment]
@jkotas

Thanks for the suggestions.

So, the single file solution isn't going to cut it for me. At the end of the day, this java.exe is combined with 13 other utilities (representing the full set of utilities one finds in the bin/ directory of a JDK). javac, schemagen, policytool, keytool, etc, etc. They all get shoved into the same directory, with all of their dependents. Overlapping. Exact same versions, etc. Because otherwise the total size of the JDK would be massive. Prohibitively massive.

Though, I bet it would work. Because it forces .NET to use other methods than LoadLibrary to load the managed assemblies. I wonder if there's something I can do there. Maybe my best option is a custom apphost.

Activation contexts... i don't know. I'll have to think of that for a bit. I think my biggest concern is how this would end up interacting with the full scope of what I'm doing. It's a JDK, designed to run user code. And mimic enough of the real Java environment so that real Java code works: including users running Java code that depends on native libraries. The libjava library is loaded through the exact same mechanisms. So... maybe I can use an activation context to load ALL user-provided native libraries.... unless there's Java code out there in the wild that uses activation contexts explicitely. Which there might be. There's a lot of weird things out there.

Actually, thinking of the above: I suspect this is going to run into issues with alternative FFI implementations used in Java. There are a few. And in fact, now that I think about it, I know of a few Java libraries which subvert the Java native loading mechanism and do it themselves with OS specific calls. Those would skip the activation context, probably.

We also intend to provide embedding in the future, and that's probably going to be hard to figure out too: user native code that loads libjvm.so (jvm.dll) and uses it to create a JVM (we'll be wrapping nethost, etc).

I've been taking a look at how this works on Framework, since I don't see that issue there. And the answer is that Framework doesn't require the second java.dll loaded by the apphost (java.exe). What happens in Framework is that java.exe appears as a module: but java.dll does not. Hence there's no conflict between java.exe and java.dll. Makes sense. So this is sort of a byproduct of two things: .NET loading assemblies using LoadLibrary and .NET Core moving the managed code from foo.exe to foo.dll.

For now I'm going to rename my libjava.dll to libsomething.dll or something. Because it seems unlikely, today, to encounter user code that might attempt to link against it: it's not a part of any Java specification. Though, I'm not going to be surprised when I run across that one weird old Java library that includes a native library that does link to it, to make use of some of the functionality specific to Oracle's JVM.

A simple way to disable .NET Core apphost from using LoadLibrary would be neat, though. :)

**Comment by jkotas** [comment]
You can control the list of assemblies that are embedded in the single file .exe using `ExcludeFromSingleFile` https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli#exclude-files-from-being-embedded . This should allow you to leave the dependencies on disk and only embed java.dll into java.exe only.

Yes, activation contexts are not easy to use, and they often create more problem than they solve.

> A simple way to disable .NET Core apphost from using LoadLibrary 

It is unlikely we would add officially supported option like this. It would come with security and performance tradeoffs that are not worth it to deal with.

**Comment by agocke** [comment]
> It is unlikely we would add officially supported option like this. It would come with security and performance tradeoffs that are not worth it to deal with.

Agreed, unfortunately this is a lot of complexity to add for a pretty uncommon scenario. I'm going to close this as Not Planned, but please feel free to continue to ask for further assistance.
