### ISSUE TITLE
Upgrade the Microsoft.CodeAnalysis.* version to use compiler interceptors for source gen

### ISSUE THREAD

**Issue by layomia** [dotnet/runtime#90849]
The RC 1 PR to use interceptors in the config binding generator https://github.com/dotnet/runtime/pull/90835/ upgraded the version MS.CodeAnalysis.* versions for the project alone, [effectively](https://github.com/dotnet/runtime/blob/034d27f4a9420e10601447d0385c88de9b4a2925/src/libraries/Microsoft.Extensions.Configuration.Binder/gen/Microsoft.Extensions.Configuration.Binder.SourceGeneration.csproj#L12-L16) from `4.5.0` -> `4.7.0-3.23314.3`. We should update the version across the entire repo to avoid source-build prebuilt [issues](https://github.com/dotnet/runtime/pull/90835#discussion_r1299011313).

**Comment by layomia** [comment]
cc @ericstj @MichaelSimons @ViktorHofer.

**Comment by jkoritzinsky** [comment]
We can upgrade the repo across-the-board to a stable 4.7.0 release as VS 17.7 has released to the public.
