### ISSUE TITLE
 High base memory usage with .NET 7 and 8 prev 7

### ISSUE THREAD

**Issue by Rikitik** [dotnet/runtime#90843]
### Description

Using dotnet 7 and 8 preview 7 Consumes 11GB Memory (base 5/16GB in use)

OS :Windows 7

### Reproduction Steps

Use dotnet on Windows 7

### Expected behavior

Consume limited amount of memory not everything

### Actual behavior

Consume all available memory without limits bogging down system

### Regression?

My guess related to issue #75049

### Known Workarounds

use dotnet 6

### Configuration

Tried .net 6 7 8pre7
OS :Windows 7
Arch x64
Unknown if it is specific its an old system

**Comment by KeterSCP** [comment]
See https://github.com/dotnet/runtime/issues/79469

**Comment by danmoseley** [comment]
Yes known issue and not fixed because it does not support Windows 7. There are environment variables mentioned in the linked issue that may help.
