### ISSUE TITLE
IAsyncEnumerator question - clear Current when MoveNextAsync is called

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#90855]
I have a question about `IAsyncEnumerator<T>`:

Is it safe according to the `IAsyncEnumerator<T>` contract to clear `Current` when `MoveNextAsync` is first called? The value returned by `Current` could be large, and `MoveNextAsync` could be long-running. Clearing Current would stop rooting the value and potentially allow it to be GCed while `MoveNextAsync` is in progress.

**Comment by stephentoub** [comment]
Yes. IAsyncEnumerable is not thread-safe for concurrent access; MoveNextAsync can make any number of changes to what Current would return as Current must not be accessed until the task returned from MoveNextAsync has completed. An even simpler example of this is T just being a giant struct... if a consumer were to access the value while MoveNextAsync were storing it, the consumer could witness a torn value.

**Comment by JamesNK** [comment]
Ok! I have a follow-up question about `await foreach`.

```cs
private static async IAsyncEnumerable<byte[]> ReadAllAsync()
{
    yield return new byte[1024 * 1024];
    await Task.Delay(TimeSpan.FromSeconds(30);
}

private static async Task DoStuff()
{
    await foreach (var data in ReadAllAsync())
    {
        Console.WriteLine($"Read {data.Length} bytes.");
    }
    Console.WriteLine("Done");
}
```

Does the foreach's `data` variable hang onto the large byte array while the app is waiting for `ReadAllAsync()` to complete?

**Comment by huoyaoyuan** [comment]
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATARgLABQGADAAQY4oDchJ5OArDQbQMzlakDCpA3oaUGkADlACWANwCGAFxj0k5ABykAkgEEAzgE8AdmACiugK4BbGFCnAANjAA8wbXIDaAXQB8pAEowpAE3Vray09MAAKAEoBIX4CIXj6HHIAdlJdGAB3UkcXHGIsFFIAKlI8gtdmBKEMAE5yJAA6ABEYayltMIAVMXMAZWEpXQaAMSgIU16YSF0/TTDWYgiIyqEAX0JowVFJWXkKRQwVDEUmiF6ZYwAzS8jNvjv42tJL6F8wAAtSMOkoUj9ZKSkMS6by+AJBEL6SJROJVe6wuHVHA1MIAEgARD5/Hx/jIpA0ADIwXQAcxk71W2ScME0DXRywea0ZggoKPRp3S9JWgnWBFWQA==

```csharp
                    if (awaiter2.GetResult())
                    {
                        byte[] current = <>7__wrap1.Current;
                        DefaultInterpolatedStringHandler defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(12, 1);
                        defaultInterpolatedStringHandler.AppendLiteral("Read ");
                        defaultInterpolatedStringHandler.AppendFormatted(current.Length);
                        defaultInterpolatedStringHandler.AppendLiteral(" bytes.");
                        Console.WriteLine(defaultInterpolatedStringHandler.ToStringAndClear());
                        goto IL_0084;
                    }
```

According to decompilation, `Current` is used as a local variable and not promoted.

**Comment by JamesNK** [comment]
Thanks all.
