### ISSUE TITLE
[API Proposal]: Expose `System.Text.Json.JsonSerializer.GetTypeInfo`

### ISSUE THREAD

**Issue by miroljub1995** [dotnet/runtime#90852]
### Background and motivation

In some situations I want to know how property will be named when serializing to json, but currently the only way is to manually determine property name and things can get complicated on various `JsonSerializerOptions`. Looking into source I see that there is a method `System.Text.Json.JsonSerializer.GetTypeInfo<T>` and this is exactly what I need, but it is `private`.

Is there a chance that this method, and non-generic,  can be made `public`?

### API Proposal

```csharp
public static JsonTypeInfo GetTypeInfo(JsonSerializerOptions? options, Type inputType)
public static JsonTypeInfo<T> GetTypeInfo<T>(JsonSerializerOptions? options)
```

### API Usage

```csharp
record TestRecord(string TestProp);

JsonSerializerOptions options = new()
{
    PropertyNamingPolicy = JsonNamingPolicy.CamelCase
};

JsonTypeInfo<TestRecord> info = JsonSerializer.GetTypeInfo<TestRecord>(options);
```

**Comment by reflectronic** [comment]
You can see in the code that the private `JsonSerializer.GetTypeInfo` just forwards to `JsonSerializerOptions.Default.GetTypeInfo(Type)`, which is all public. You wouldn't need any new APIs to do this today.

**Comment by eiriktsarpalis** [comment]
Have you tried using https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.gettypeinfo?view=net-7.0

**Comment by miroljub1995** [comment]
I tried, but on dotnet 7, which gave me errors on not initialized for reflection. I see that on dotnet 7 there is a logic before calling `JsonSerializerOptions.GetTypeInfo`:

![image](https://github.com/dotnet/runtime/assets/46632388/8484b468-81c5-45af-8073-d4c5b3bfa462)
but on `main` branch, there is no check for reflection serializer:

![image](https://github.com/dotnet/runtime/assets/46632388/4ad5c000-824c-4ba6-8110-ff8f5ad59516)

That's why I though it's better to expose `JsonSerializer.GetTypeInfo`.

**Comment by krwq** [comment]
on net7 you can either upgrade System.Text.Json package to latest or perform single dummy serialization/deserialization before using options.GetTypeInfo. Alternatively you can do something like:
`(options.TypeInfoResolver ?? new DefaultJsonTypeInfoResolver()).GetTypeInfo(YourTypeHere, options)`

**Comment by miroljub1995** [comment]
Here is a test with 3 Facts and errors:
```cs
using System.Text.Json;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.Extensions.Options;

namespace Example.Tests;

public class SimpleTestEndpoint
{
    private record SimpleDto(string Prop1, string Prop2);

    private class TestApplicationFactory : WebApplicationFactory<DefaultWebApplicationFactory>
    {
        protected override IWebHostBuilder? CreateWebHostBuilder() => WebHost.CreateDefaultBuilder();

        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            builder.Configure(app =>
            {
                app.UseRouting();
                app.UseEndpoints(endpointBuilder =>
                {
                    endpointBuilder.MapGet("type-info",
                        ([FromServices] IOptions<JsonOptions> jsonOptions) =>
                        {
                            jsonOptions.Value.JsonSerializerOptions.GetTypeInfo(typeof(SimpleDto));
                        });

                    endpointBuilder.MapGet("init-serializer-v1",
                        ([FromServices] IOptions<JsonOptions> jsonOptions) =>
                        {
                            JsonSerializer.Serialize(new SimpleDto("Value1", "Value2"),
                                jsonOptions.Value.JsonSerializerOptions);
                        });

                    endpointBuilder.MapGet("init-serializer-v2", 
                        () => Results.Json(new SimpleDto("Value1", "Value2")));
                });
            });
        }
    }

    [Fact]
    public async Task Fail()
    {
        TestApplicationFactory app = new();

        await app.CreateClient().GetAsync("type-info");
    }

    [Fact]
    public async Task Success()
    {
        TestApplicationFactory app = new();

        await app.CreateClient().GetAsync("init-serializer-v1");
        await app.CreateClient().GetAsync("type-info");
    }

    [Fact]
    public async Task ExpectedSuccess()
    {
        TestApplicationFactory app = new();

        await app.CreateClient().GetAsync("init-serializer-v2");
        await app.CreateClient().GetAsync("type-info");
    }
}
```
Fact `Fail()` is the case I experienced error in the first place:
```
Metadata for type 'OpenApiAspNet.Tests.SimpleTestEndpoint+SimpleDto' was not provided by TypeInfoResolver of type '<null>'. If using source generation, ensure that all root types passed to the serializer have been indicated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically.
```

Fact `Success()` is passing since resolver is initialized, like @krwq  explained with dummy serialization/deserialization.

Fact `ExpectedSuccess()` for some reason isn't initializing resolver, error is the same as `Fail()`.

**Comment by miroljub1995** [comment]
Yes
