### ISSUE TITLE
ComInterfaceGenerator Unmanaged to Manage call doesn't update the unmanaged pointer

### ISSUE THREAD

**Issue by rmsimpson** [dotnet/runtime#90868]
### Description

The source code generator for COM interfaces (I haven't tried libraries yet) isn't accounting for native -> managed callbacks in which the native code passes in a buffer and expects managed code to update that buffer and return the updated values.

The generated code copies the native buffer to a managed buffer, executes the managed call, and then fails to copy the managed buffer back to the native buffer.

### Reproduction Steps

Given the following interface defined:
```
[assembly: System.Runtime.CompilerServices.DisableRuntimeMarshalling]

using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace SevenZ.Interfaces
{
	[GeneratedComInterface]
	[Guid("23170F69-40C1-278A-0000-000300030000")]
	[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
	internal partial interface IInStream
	{
		int Read([MarshalAs(UnmanagedType.LPArray, SizeParamIndex = 1)] byte[] data, int dataSize);

		long Seek(long offset, SeekOrigin seekOrigin);
	}
}
```
This interface is implemented in a managed class with `[GeneratedComClass]` defined, and `Read` is called from native code into managed code.
When managed code writes into `data`, the updated values are not marshalled back to the native code.

I've tried the latest source generators from this repo, the relevant source-generated code looks like this:

```
file unsafe partial interface InterfaceImplementation
{
    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_Read(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, byte* __data_native, int dataSize, int* __invokeRetValUnmanaged__param)
    {
        global::SevenZ.Interfaces.IInStream @this = default;
        byte[] data = default;
        ref int __invokeRetValUnmanaged = ref *__invokeRetValUnmanaged__param;
        int __invokeRetVal = default;
        int __retVal = default;
        // Setup - Perform required setup.
        int __data_native__numElements;
        global::System.Runtime.CompilerServices.Unsafe.SkipInit(out __data_native__numElements);
        try
        {
            // Unmarshal - Convert native data to managed data.
            __data_native__numElements = dataSize;
            data = global::System.Runtime.InteropServices.Marshalling.ArrayMarshaller<byte, byte>.AllocateContainerForManagedElements(__data_native, __data_native__numElements);
            global::System.Runtime.InteropServices.Marshalling.ArrayMarshaller<byte, byte>.GetUnmanagedValuesSource(__data_native, __data_native__numElements).CopyTo(global::System.Runtime.InteropServices.Marshalling.ArrayMarshaller<byte, byte>.GetManagedValuesDestination(data));
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::SevenZ.Interfaces.IInStream>(__this_native);
            __invokeRetVal = @this.Read(data, dataSize);
            // NotifyForSuccessfulInvoke - Keep alive any managed objects that need to stay alive across the call.
            __retVal = 0; // S_OK
            // Marshal - Convert managed data to native data.
            __invokeRetValUnmanaged = __invokeRetVal;
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }
```

After the `__invokeRetVal = @this.Read(data, dataSize);` call is made, the results aren't copied back into the unmanaged buffer, so the unmanaged code never receives the updated information.

### Expected behavior

Expected the native caller to receive an updated buffer.

### Actual behavior

The buffer isn't updated.

### Regression?

Works when using regular `[ComImport]` without disabling runtime marshaling.

### Known Workarounds

Would love to hear one ...

### Configuration

.NET 8.0 Preview 7
Also tried with latest source code generators built from the latest pull on this repo.

**Comment by AaronRobinsonMSFT** [comment]
> The source code generator for COM interfaces (I haven't tried libraries yet) isn't accounting for native -> managed callbacks in which the native code passes in a buffer and expects managed code to update that buffer and return the updated values.

Can you try adding the `Out` attribute to the parameter?

`int Read([Out, MarshalAs(UnmanagedType.LPArray, SizeParamIndex = 1)] byte[] data, int dataSize);`

**Comment by rmsimpson** [comment]
I can try it, but when you add `In` and `Out` you'll receive a minor reminder that In/Out is the default behavior for this parameter.

**Comment by rmsimpson** [comment]
OK, so adding `Out` and also `In` works with the latest version of the source generator I pulled from github today, though this seems like a behavioral change from dynamic marshalling.

**Comment by AaronRobinsonMSFT** [comment]
> OK, so adding Out and also In works with the latest version of the source generator I pulled from github today, though this seems like a behavioral change from runtime marshalling.

Thanks for confirming. It is a slight change in the sense that the COM source generator is being designed to have less magic and require explicit intent. The built-in system was far too loose and permissive in determining intent and introduced unnecessary overhead to make marshalling "just work". For the COM source generator, like the `LibraryImport` generator, we are requiring clear and unambiguous intent.

Fixers, analyzers, and updated documentation/tutorials will be provided closer to release and are intended to help provide a path here.

We'll close this issue for now. 

@jtschuster Do we have a document somewhere for this?

**Comment by rmsimpson** [comment]
@AaronRobinsonMSFT 
I'm concerned about closing this prematurely.  The behavior is really inconsistent and confusing without digging through source code.

Runtime marshaling - **works** without additional decoration
Source-generator marshaling - **works** going from managed -> unmanaged
Source-generator marshaling - **fails** going from unmanaged -> managed

**Comment by AaronRobinsonMSFT** [comment]
> I'm concerned about closing this prematurely.

Okay.

**Comment by jtschuster** [comment]
This sounds like https://github.com/dotnet/runtime/issues/89265. The default for blittable arrays was changed after preview 7 in  https://github.com/dotnet/runtime/pull/90054. Using the latest build, it should say that [In] is the default now, not [In, Out]. 

We'll be sure to highlight differences in behavior when making the docs for the COM generator https://github.com/dotnet/runtime/issues/90876.
