### ISSUE TITLE
dotnet/cecil links to cecil.pe which is an unrelated website

### ISSUE THREAD

**Issue by jnm2** [dotnet/runtime#90865]
https://github.com/dotnet/cecil does not allow opening issues, so I'm opening here.

The dotnet fork links people to https://cecil.pe which redirects to `https://time-mx.com/peru/`. The source repository https://github.com/jbevain/cecil currently has no website link.

![image](https://github.com/dotnet/runtime/assets/8040367/177699df-0d57-4176-90b3-bc957b5b7878)

**Comment by jkotas** [comment]
Same as https://github.com/jbevain/cecil/issues/910

**Comment by jkotas** [comment]
Thank you for reporting it. Fixed.
