### ISSUE TITLE
NegotiateAuthentication larger code size and also brings in BigInteger

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/runtime#90898]
Afaik the following PR https://github.com/dotnet/runtime/pull/87930 is part of .NET 8.0 preview 7, it caused a 60kb size regression for us:

preview 6: https://github.com/npgsql/npgsql/actions/runs/5930686472
preview 7: https://github.com/npgsql/npgsql/actions/runs/5931742857

Mostly due to it bringing in BigInteger (and a managed NegotiateAuthentication impl?)

Not sure what we can or want to do here. 

/cc @filipnavara 

<img width="1354" alt="Screenshot 2023-08-22 at 00 04 06" src="https://github.com/dotnet/runtime/assets/4218809/50974491-025c-46f0-9f5f-bea56344590c">

**Comment by wfurt** [comment]
what platforms is this on @NinoFloris? I think we do want to keep the managed implementation in. We can perhaps try to make it more trimming friendly.

**Comment by NinoFloris** [comment]
These builds were done on ubuntu

**Comment by filipnavara** [comment]
It should be trimmed out on Linux for NativeAOT unless the `UseManagedNtlm` option is turned on. I'll have a look.

**Comment by filipnavara** [comment]
Can you try adding this to the test app .csproj?

```xml
<ItemGroup>
  <RuntimeHostConfigurationOption Include="System.Net.Security.UseManagedNtlm" Value="false" />
</ItemGroup>
```

Generally the idea is that the ILLink substitution (https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Security/src/ILLink/ILLink.Substitutions.xml) will turn `System.Net.NegotiateAuthenticationPal.UseManagedNtlm` into `false` and trim away the rest of the code. There are two possible failures that I can think of: 1) the substitution not taking place when the feature option is not specified at all, and 2) the resulting branch trimming not happening.

**Comment by filipnavara** [comment]
I reread the ILLink documentation and it seems we are missing `featuredefault="true"` attribute there.

**Comment by NinoFloris** [comment]
Does that mean it should be fixed for rc2 or where do we stand? Npgsql is a library, I can't ask people to flip these switches for us.

**Comment by filipnavara** [comment]
I will try to submit the fix and then we can see about backports.

**Comment by filipnavara** [comment]
I was not able to get `featuredefault` to do the right thing on NativeAOT yet. I'm trying to figure out whether it is supposed to work, or not. The alternative is to specify the option through `RuntimeHostConfigurationOption` in the NativeAOT build integration. I'll post once I have more details to share.

**Comment by karelz** [comment]
Triage: @wfurt discussed it with @jkotas and his suggestion was to NOT take it for 8.0 as it is size improvement, but not functional impact.

**Comment by filipnavara** [comment]
I generally agree it doesn't meet the bar for 8.0 servicing, but should we try to backport the SDK switch (https://github.com/dotnet/sdk/pull/34903) to make the workaround easier?

**Comment by NinoFloris** [comment]
Thanks, @karelz we are. We have added an explicit opt-in to our slim builder for "integrated security" auth, sidestepping the issue.

**Comment by roji** [comment]
Yeah, agreed this isn't critical for a 8.0 backport.
