### ISSUE TITLE
[API Proposal]: Add an interface to unify property/field access

### ISSUE THREAD

**Issue by Redninja106** [dotnet/runtime#90901]
### Background and motivation

Currently, `FieldInfo` and `PropertyInfo` share a large part of their api surface that doesn't come from `MemberInfo`. This leads to unnessessarily duplicated code. There should be an interface that exposes the common functionality between the types for situations where the intention is to treat them the same.

### API Proposal

```cs
// add new interface:
public interface IVariableInfo : ICustomAttributeProvider // perhaps a different name?
{
    string Name { get; }
    Type VariableType { get; }
    bool CanRead { get; }
    bool CanWrite { get; }
    object? GetValue(object? value);
    void SetValue(object? obj, object? value);
}

class FieldInfo : IVariableInfo
{
    Type IVariableInfo.VariableType => this.FieldType;
    bool IVariableInfo.CanRead => true;
    bool IVariableInfo.CanWrite => !this.IsInitOnly;
}

class PropertyInfo : IVariableInfo
{
    Type IVariableInfo.VariableType => this.PropertyType;
}
```

### API Usage

```cs
// assuming "someObject" is already defined
IEnumerable<IVariableInfo> variables = someObject.GetType().GetMembers().OfType<IVariableInfo>();

foreach (IVariableInfo v in variables)
{
    if (v.CanRead)
    {
        Console.WriteLine(v.GetValue(someObject));
    }
}
```

**Comment by steveharter** [comment]
What is the use case here? The ask seem niche - serializers for example.

Using `OfType<IVariableInfo>()` would likely not be used by performance-sensitive areas due to `OfType` being in the LINQ assembly which is expensive in terms of startup and size on disk. Also, repeatedly calling `GetMembers()` or `GetMembers(BindingFlags)` would allocate and populate an array each time, also not performant (i.e. it would need to be cached by the caller).

The example provided could be changed use an extension method without having to add new members to FieldInfo\PropertyInfo:
```cs
public static class TypeExtensions()
{
    public static IVariableInfo[] GetVariables(this Type type)
    {
        // todo: implement
    }
}

internal class FieldInfoEx : IVariableInfo
{
    // todo: implement
}

internal class PropertyInfoEx : IVariableInfo
{
    // todo: implement
}
```

**Comment by Redninja106** [comment]
I've found use cases for this a surprising number of times, especially when writing [Dear ImGui](https://github.com/ocornut/imgui) debug ui for my projects. When enumerating the members of a type, I want to treat properties/fields the same (silders in ImGui), so my only options are to either duplicate the code, or do as you suggested (which i'm afraid adds more code than it saves).

There's not really any drawbacks to adding this as most of `IVariableInfo`'s members are already implemented by both `FieldInfo` and `PropertyInfo` (with the rest being easily explicitly implemented). The additions have much personal use to me and while I agree it's probably somewhat niche overall, it provides additional flexibility to the user at basically no cost.

Also, I don't touch on accessibility modifiers in my proposal and if/how they should be exposed, I wasn't exactly sure what the best thing to do is so I figured I'd be better off leaving it to the discussion.

**Comment by Neme12** [comment]
I agree that having a shared abstraction over fields and properties would be nice.

**Comment by steveharter** [comment]
This request appears to be an uncommon scenario, and it is anticipated that only a limited number of users will require access to this API. Typically, we provide APIs for common use cases or when it would be challenging for users to achieve the required functionality without assistance from the runtime.

Based on this assessment, this is being closed as Not Planned.
