### ISSUE TITLE
Config binder generator generates uncompilable code when a private nested type is used

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#90909]
This compiles fine:
```C#
using Microsoft.Extensions.Configuration;

internal class Program
{
    private static void Main() { }

    private static C Foo(IConfiguration configuration)
    {
        C c = new();
        configuration.Bind(c);
        return c;
    }

    internal sealed class C
    {
        public int Value { get; set; }
    }
}
```
but changing:
```C#
internal sealed class C
```
to
```C#
private sealed class C
```
produces an error about `C` being inaccessible, as the generator emits code into another class that tries to access that property.

**Comment by layomia** [comment]
I'd say the resolution would be to emit a diagnostic & omit code to support inaccessible members.

**Comment by layomia** [comment]
Needs RC-2 port of https://github.com/dotnet/runtime/pull/91657.

**Comment by layomia** [comment]
Fixed for RC 2 - https://github.com/dotnet/runtime/pull/91967.
