### ISSUE TITLE
Call stack is not as expected if a method is called at last line in caller

### ISSUE THREAD

**Issue by panxn** [dotnet/runtime#90921]
### Description

It happens only if R2R is enabled.

If a method is called at last line of the caller, the call stack is different from normal release build (without R2R), it's hard to describe, please see sample code.

I wonder if it's by design as some kind of optimization. If yes, is there some way to prevent it for certain method?

### Reproduction Steps

We have two projects, DLL and EXE. In DLL project:
```
        class PropertyHolder
        {
            public int Value
            {
                get => _value;
                set
                {
                    var ass = Assembly.GetCallingAssembly();
                    Console.WriteLine(ass.FullName);
                    _value = value;
                }
            }

            private int _value;
        }

        public static void Work()
        {
            var prop = new PropertyHolder();
            // note it must be last line
            prop.Value = 1;
        }
```

In EXE project, call `Work` method.

If R2R is off, it prints the assembly name of dll.
if R2R is on, it prints the assembly name of exe.

### Expected behavior

they should be same

### Actual behavior

they are different

**Comment by EgorBo** [comment]
I am not sure whether it's an expected behavior but clearly inlining is the culprit, simple repro (doesn't even need R2R):
```cs
// Assembly ClassLibrary1:
public class Class1
{
    public static void Test() => Console.WriteLine(Assembly.GetCallingAssembly());
}

// Assembly ClassLibrary2 (references ClassLibrary1):
public class Class2
{
    public static void Test(int a) => ClassLibrary1.Class1.Test();
}

// Assembly ConsoleApp1 (references ClassLibrary2):
class Prog
{
    static void Main()
    {
        for (int i = 0; i < 200; i++)
        {
            Class2.Test(i);
            Thread.Sleep(16);
        }
    }
}
```
The output will be something like:
```
ClassLibrary2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
...
ClassLibrary2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
ClassLibrary2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
ClassLibrary2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
ClassLibrary2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
ClassLibrary2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
hello, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
hello, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
hello, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
hello, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
hello, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
...
hello, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
```
after tiered compilation kicks in and inlines `Class2.Test()` into `Main`.

**Comment by MichalPetryka** [comment]
> the call stack is different from normal release build (without R2R)

There's nothing that guarantees stacktraces to look in a particular way, depending on such behaviour will break someday.

**Comment by EgorBo** [comment]
@panxn https://learn.microsoft.com/en-us/dotnet/api/system.reflection.assembly.getcallingassembly?view=net-7.0#remarks

Per doc it's an expected behaviour, just like in my example above you can manually control inlining via NoInlining attribute but generally it's expected.

**Comment by panxn** [comment]
Thanks for your information!

Our project relies on such an undefined behavior for so many years. It works fine in .net framework and .net6 but breaks in .net8 so I suspected it might be a problem. Now I realize it's our fault. `NoInlining` attribute fixes the problem.

@EgorBo Thanks for your interesting sample. I'm used to write c++ and believe functions are fixed after build. This is good knowledge for me :-)
