### ISSUE TITLE
[Question] Ref reassignment

### ISSUE THREAD

**Issue by hypeartist** [dotnet/runtime#90925]
Below is the simple repro which is quite self-explanatory. The question is - why upon exit from `fn` our char reference `c` is not changed to '**b**' char?
```csharp
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

static void fn(ref char c)
{
    c = ref Unsafe.Add(ref c, 1);
	// now we have c = 'b'
}

var input = "abc";
ref var c = ref MemoryMarshal.GetReference(input.AsSpan());

fn(ref c);
// but on exit we still have c = 'a'
Console.WriteLine(c);
```

**Comment by jkotas** [comment]
> why upon exit from fn our char reference c is not changed to 'b' char?

`c = ref Unsafe.Add(ref c, 1);` reassigns where `c` points to. It does not change the value that `c` points to. It is how `ref` works in C#.

You would need to omit the `ref` to make it do what you are trying to.

Note that string objects are expected to be immutable. It is not legal to modify their content. It breaks the runtime invariants that can lead to a lot of surprising behaviors.

**Comment by hypeartist** [comment]
@jkotas Thank you. That was it. 

PS: as of `string` - yep, it was not best type for example.
