### ISSUE TITLE
dotnet dump  no longer working on OSX 

### ISSUE THREAD

**Issue by hananiel** [dotnet/runtime#90938]
### Description
Running dotnet dump collect -p `<pid>` results in failure: 

Logs from process being dumped: 
```
[createdump] Gathering state for process 18853 
[createdump] thread_get_state(1cb5b09) FAILED 4 (os/kern) invalid argument
[createdump] Target process is alive
```
Logs from dump tool: 
```
Writing dump with heap to /Users/hsarella/core_20230822_130346
Write dump failed - HRESULT: 0x00000000.
```

### Configuration

dotnet-dump version 7.0.430602+c9c987585e1fa9a8a8a5e1ffb60a70f85b0da4ca
MacOs version macOS Ventura 13.5
Chip Apple M1 Pro

dotnet info: 
```
.NET SDK:
 Version:   7.0.101
 Commit:    bb24aafa11

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.5
 OS Platform: Darwin
 RID:         osx.13-x64
 Base Path:   /usr/local/share/dotnet/x64/sdk/7.0.101/

Host:
  Version:      7.0.1
  Architecture: x64
  Commit:       97203d38ba

.NET SDKs installed:
  6.0.404 [/usr/local/share/dotnet/x64/sdk]
  7.0.101 [/usr/local/share/dotnet/x64/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.12 [/usr/local/share/dotnet/x64/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [/usr/local/share/dotnet/x64/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.12 [/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App]

Other architectures found:
  arm64 [/usr/local/share/dotnet]
    registered at [/etc/dotnet/install_location_arm64]
```

### Regression?

Yes, this used to work. Looks related to this https://github.com/dotnet/runtime/pull/79360.

**Comment by hoyosjs** [comment]
@hananiel  You are running against 7.0.1 which is several releases old and several fixes around new kernel protections have been issued. The fix for the issue you noted is for example in 7.0.3. Is it possible for you to please try this against the latest (7.0.10 at this point of time) runtime and report if it repros or fixes the issue?

**Comment by rohanp-91** [comment]
This issue seems to be happening on 7.0.4 for app running in Rosetta mode.

**Comment by mikem8361** [comment]
We don't support collecting dumps in Rosetta emulation. Apple doesn't support basic APIs we need.

**Comment by tommcdon** [comment]
Closing as `dotnet-dump collect` is not supported with Rosetta
