### ISSUE TITLE
ReadItemAsync 'Hangs' in .Net 8.0, but works in .Net 7.0

### ISSUE THREAD

**Issue by gpuchtel** [dotnet/runtime#90943]
this statement works with .Net 7.0, but hangs with .Net 8.0. (that is, <TargetFramework>net8.0</TargetFramework>)

**var result = await container.ReadItemAsync<Foo>(id, <Partition Key>);**

Note: I’m using Microsoft Azure Cosmos Emulator version 2.14.12.0

**Comment by karelz** [comment]
@gpuchtel do you have a small isolated repro (HelloWorld style) for that?
Or does it change behavior only in your larger application?

If it is only in larger application, then it may still be problem in the app code where changes in .NET make it cause problems.

**Comment by wfurt** [comment]
Also note that behavior or timing changes can expose old bugs. Just the fact that does not work with 8.0 does not mean it is runtime fault. It may be but we would need to dig deeper with reasonable repro. 
At this point it is not even clear what is being used -> not actionable for us.

**Comment by wfurt** [comment]
One more note that there was at least one more issue (#89118) related to Cosmos emulator. While the observed behavior was different it is also waiting for more information.

**Comment by AndriySvyryd** [comment]
Note that https://github.com/dotnet/runtime/issues/89118 may appear as hanging as it takes about 10 minutes for all the retries to be exhausted and an exception thrown.

**Comment by wfurt** [comment]
Can you also  try it with `8.0.100-rc.2.23422.11` (or newer) build @gpuchtel?

**Comment by gpuchtel** [comment]
> @gpuchtel do you have a small isolated repro (HelloWorld style) for that? Or does it change behavior only in your larger application?
> 
> If it is only in larger application, then it may still be problem in the app code where changes in .NET make it cause problems.

The program is larger than a 'Hello World', but I don't do much. I get an 'identifier' from an HTTP header and call Cosmos. Again, the 'exact' same code works in .Net 7.0, but fails in .Net 8.0, which makes me think its not my code.

**Comment by gpuchtel** [comment]
I downloaded 8.0.100-preview.7.23376.3, but it still hangs.

![image](https://github.com/dotnet/runtime/assets/5240685/91d4dd5c-3342-434d-a417-710fbf1b3dc4)

**Comment by wfurt** [comment]
`preview.7` does not have the fix that solved the other CosmosDB issue. You would need to use `rc2` @gpuchtel.
Get it from here: https://github.com/dotnet/installer 
(middle column in the table)

**Comment by gpuchtel** [comment]
@wfurt Yes! Success! Whooot! version 8.0.100-rc.2.23431.5 works! Thank you!
