### ISSUE TITLE
JIT assert "(structBaseType != TYP_STRUCT) && (genTypeSize(structBaseType) >= originalSize)" failing in superpmi-collect

### ISSUE THREAD

**Issue by amanasifkhalid** [dotnet/runtime#90944]
On Linux x64 Checked in the runtime-coreclr superpmi-collect pipeline, the assert `(structBaseType != TYP_STRUCT) && (genTypeSize(structBaseType) >= originalSize)` in `src/coreclr/jit/morph.cpp (3321)` is failing in `JIT.HardwareIntrinsics.General._Vector128_1.VectorAs__AsVector3Single:RunReflectionScenario():this` during `Morph - Global`. Here are the [full log](https://helixri107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-da371da3774e43eeb2/HardwareIntrinsics_General_ro/1/console.8cb01cb2.log?sv=2021-08-06&se=2023-11-20T03%3A41%3A07Z&sr=c&sp=rl&sig=fHgUOcalAUifaE3XIKdcRMIcM6XGHdnaKXE6YsUvkzI%3D) and [pipeline results](https://dev.azure.com/dnceng/internal/_build/results?buildId=2249475&view=results).

**Comment by JulieLeeMSFT** [comment]
Hi @BruceForstall, PTAL.

**Comment by BruceForstall** [comment]
The failure only occurs during the "clean" phase replay, not during collection.

**Comment by jakobbotsch** [comment]
Moving to 9.0 since this is a recording/replay issue given what Bruce said.

**Comment by amanasifkhalid** [comment]
I'm not seeing this reproduce anymore.
