### ISSUE TITLE
System.Memory.Tests.Span.StringSearchValuesTests failing with "Exit code was 1 but it should have been 42"

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#90945]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=382187
Build error leg or test failing: GC_API.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/90796

## Error Message

Two tests failing: `Exit code was 1 but it should have been 42`

```
info: An error occurred running System.Memory.Tests.sh
dbug: Exit code: 1
      Std out:
        Discovering: System.Memory.Tests (method display = ClassAndMethod, method display options = None)
        Discovered:  System.Memory.Tests (found 2697 of 2728 test cases)
        Starting:    System.Memory.Tests (parallel test collections = on, max threads = 1)
            Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Exit code was 1 but it should have been 42
            Stack Trace:
              /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(242,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing)
              /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(55,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose()
              /_/src/libraries/System.Memory/tests/Span/StringSearchValues.cs(343,0): at System.Memory.Tests.Span.StringSearchValuesTests.RunUsingInvariantCulture(Action action)
              /_/src/libraries/System.Memory/tests/Span/StringSearchValues.cs(258,0): at System.Memory.Tests.Span.StringSearchValuesTests.TestIndexOfAny_RandomInputs_InvariantCulture()
              /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.Mono.cs(22,0): at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
              /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(57,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
            Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Exit code was 1 but it should have been 42
            Stack Trace:
              /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(242,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing)
              /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(55,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose()
              /_/src/libraries/System.Memory/tests/Span/StringSearchValues.cs(343,0): at System.Memory.Tests.Span.StringSearchValuesTests.RunUsingInvariantCulture(Action action)
              /_/src/libraries/System.Memory/tests/Span/StringSearchValues.cs(204,0): at System.Memory.Tests.Span.StringSearchValuesTests.IndexOfAny_CanProduceDifferentResultsUnderNls()
              /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.Mono.cs(22,0): at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
              /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(57,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
          System.Memory.Tests.Span.StringSearchValuesTests.TestIndexOfAny_RandomInputs_Nls [SKIP]
            Condition(s) not met: "CanTestNls"
        Finished:    System.Memory.Tests
      === TEST EXECUTION SUMMARY ===
         System.Memory.Tests  Total: 49764, Errors: 0, Failed: 2, Skipped: 1, Time: 69.795s
```

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "at System.Memory.Tests.Span.StringSearchValuesTests.",
  "ErrorPattern": ""
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=382187
**Error message validated:** `at System.Memory.Tests.Span.StringSearchValuesTests.`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 8/22/2023 6:40:32 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[384588](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384588)|dotnet/runtime|[System.Memory.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384588&view=ms.vss-test-web.build-test-results-tab&runId=8210852&resultId=182327)||
|[384505](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384505)|dotnet/runtime|[System.Memory.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384505&view=ms.vss-test-web.build-test-results-tab&runId=8207222&resultId=182327)|dotnet/runtime#91019|
|[384350](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384350)|dotnet/runtime|[System.Memory.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384350&view=ms.vss-test-web.build-test-results-tab&runId=8202440&resultId=182327)|dotnet/runtime#90518|
|[383982](https://dev.azure.com/dnceng-public/public/_build/results?buildId=383982)|dotnet/runtime|[System.Memory.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=383982&view=ms.vss-test-web.build-test-results-tab&runId=8194584&resultId=182327)|dotnet/runtime#91008|
|[384031](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384031)|dotnet/runtime|[System.Memory.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384031&view=ms.vss-test-web.build-test-results-tab&runId=8194518&resultId=182327)||
|[383327](https://dev.azure.com/dnceng-public/public/_build/results?buildId=383327)|dotnet/runtime|[System.Memory.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=383327&view=ms.vss-test-web.build-test-results-tab&runId=8177752&resultId=182327)||
|[383261](https://dev.azure.com/dnceng-public/public/_build/results?buildId=383261)|dotnet/runtime|[System.Memory.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=383261&view=ms.vss-test-web.build-test-results-tab&runId=8175026&resultId=182327)|dotnet/runtime#90875|
|[382733](https://dev.azure.com/dnceng-public/public/_build/results?buildId=382733)|dotnet/runtime|[System.Memory.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=382733&view=ms.vss-test-web.build-test-results-tab&runId=8163196&resultId=182327)||
|[382301](https://dev.azure.com/dnceng-public/public/_build/results?buildId=382301)|dotnet/runtime|[System.Memory.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=382301&view=ms.vss-test-web.build-test-results-tab&runId=8155754&resultId=182155)|dotnet/runtime#89554|
|[382187](https://dev.azure.com/dnceng-public/public/_build/results?buildId=382187)|dotnet/runtime|[System.Memory.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=382187&view=ms.vss-test-web.build-test-results-tab&runId=8153650&resultId=182327)|dotnet/runtime#90796|
|[381930](https://dev.azure.com/dnceng-public/public/_build/results?buildId=381930)|dotnet/runtime|[System.Memory.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=381930&view=ms.vss-test-web.build-test-results-tab&runId=8146844&resultId=182155)||
|[381785](https://dev.azure.com/dnceng-public/public/_build/results?buildId=381785)|dotnet/runtime|[System.Memory.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=381785&view=ms.vss-test-web.build-test-results-tab&runId=8142410&resultId=182155)|dotnet/runtime#89550|
|[381403](https://dev.azure.com/dnceng-public/public/_build/results?buildId=381403)|dotnet/runtime|[System.Memory.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=381403&view=ms.vss-test-web.build-test-results-tab&runId=8132878&resultId=182153)||
|[381327](https://dev.azure.com/dnceng-public/public/_build/results?buildId=381327)|dotnet/runtime|[System.Memory.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=381327&view=ms.vss-test-web.build-test-results-tab&runId=8131834&resultId=182153)|dotnet/runtime#90836|
|[381296](https://dev.azure.com/dnceng-public/public/_build/results?buildId=381296)|dotnet/runtime|[System.Memory.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=381296&view=ms.vss-test-web.build-test-results-tab&runId=8130134&resultId=182153)|dotnet/runtime#89696|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|5|15|15|

**Comment by jkotas** [comment]
cc @MihaZupan 

Related to #88394

**Comment by MihaZupan** [comment]
All failures in Kusto are on `ubuntu.1804.amd64.android.29.open.rt` with the same `"RemoteExecutionException : Exit code was 1 but it should have been 42"` error.

Seems related to #66147, which already disabled similar tests on that platform, e.g.

https://github.com/dotnet/runtime/blob/6b67caaedfbfeaf7707478e50ccc9e8bc929e591/src/libraries/System.Globalization/tests/CultureInfo/GetCultureInfo.cs#L160C9-L160C100
