### ISSUE TITLE
Known issue: NuGet "FatalProtocolException : Unable to load the service index"

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#90951]
### Build

https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=382187

Appears to be a known NuGet connectivity issue; adding template to catch these:
https://github.com/dotnet/runtime/issues/81586
https://github.com/dotnet/runtime/issues/33294

### Build leg reported

GC_API.WorkItemExecution

### Pull Request

https://github.com/dotnet/runtime/pull/90796

### Known issue core information

Fill out the known issue JSON section by following the [step by step documentation on how to create a known issue](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step)

```json
 {
    "ErrorMessage" : "NuGet.Protocol.Core.Types.FatalProtocolException : Unable to load the service index for source https://api.nuget.org/v3/index.json.",
    "BuildRetry": false
 }
 ```

 @dotnet/dnceng

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=382187
**Error message validated:** `NuGet.Protocol.Core.Types.FatalProtocolException : Unable to load the service index for source https://api.nuget.org/v3/index.json.`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 8/22/2023 8:25:55 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[443125](https://dev.azure.com/dnceng-public/public/_build/results?buildId=443125)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=443125&view=ms.vss-test-web.build-test-results-tab&runId=9890066&resultId=182704)||
|[442238](https://dev.azure.com/dnceng-public/public/_build/results?buildId=442238)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=442238&view=ms.vss-test-web.build-test-results-tab&runId=9862144&resultId=177951)|dotnet/runtime#91800|
|[441694](https://dev.azure.com/dnceng-public/public/_build/results?buildId=441694)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestHelperMethodsUnrelatedPropertyDoesntHelp](https://dev.azure.com/dnceng-public/public/_build/results?buildId=441694&view=ms.vss-test-web.build-test-results-tab&runId=9844772&resultId=203406)|dotnet/runtime#93182|
|[440640](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440640)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440640&view=ms.vss-test-web.build-test-results-tab&runId=9815618&resultId=182625)|dotnet/runtime#93182|
|[440293](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440293)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440293&view=ms.vss-test-web.build-test-results-tab&runId=9805880&resultId=182482)|dotnet/runtime#91560|
|[438911](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438911)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438911&view=ms.vss-test-web.build-test-results-tab&runId=9767682&resultId=182611)||
|[438199](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438199)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438199&view=ms.vss-test-web.build-test-results-tab&runId=9742922&resultId=174776)||
|[435035](https://dev.azure.com/dnceng-public/public/_build/results?buildId=435035)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodWithIfStatement](https://dev.azure.com/dnceng-public/public/_build/results?buildId=435035&view=ms.vss-test-web.build-test-results-tab&runId=9661394&resultId=102047)||
|[433988](https://dev.azure.com/dnceng-public/public/_build/results?buildId=433988)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=433988&view=ms.vss-test-web.build-test-results-tab&runId=9628308&resultId=182614)|dotnet/runtime#93182|
|[432136](https://dev.azure.com/dnceng-public/public/_build/results?buildId=432136)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=432136&view=ms.vss-test-web.build-test-results-tab&runId=9559238&resultId=182513)||
|[430969](https://dev.azure.com/dnceng-public/public/_build/results?buildId=430969)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=430969&view=ms.vss-test-web.build-test-results-tab&runId=9529216&resultId=182355)||
|[430188](https://dev.azure.com/dnceng-public/public/_build/results?buildId=430188)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=430188&view=ms.vss-test-web.build-test-results-tab&runId=9508160&resultId=182513)||
|[430053](https://dev.azure.com/dnceng-public/public/_build/results?buildId=430053)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestHelperMethodsUnrelatedPropertyDoesntHelp](https://dev.azure.com/dnceng-public/public/_build/results?buildId=430053&view=ms.vss-test-web.build-test-results-tab&runId=9508252&resultId=191393)|dotnet/runtime#93093|
|[429956](https://dev.azure.com/dnceng-public/public/_build/results?buildId=429956)|dotnet/runtime|[LibraryImportGenerator.UnitTests.Compiles.ValidateNoGeneratedOuptutForNoImport](https://dev.azure.com/dnceng-public/public/_build/results?buildId=429956&view=ms.vss-test-web.build-test-results-tab&runId=9502678&resultId=187711)|dotnet/runtime#92974|
|[429653](https://dev.azure.com/dnceng-public/public/_build/results?buildId=429653)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=429653&view=ms.vss-test-web.build-test-results-tab&runId=9495160&resultId=182627)|dotnet/runtime#93109|
|[429167](https://dev.azure.com/dnceng-public/public/_build/results?buildId=429167)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=429167&view=ms.vss-test-web.build-test-results-tab&runId=9488736&resultId=182625)||
|[428630](https://dev.azure.com/dnceng-public/public/_build/results?buildId=428630)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=428630&view=ms.vss-test-web.build-test-results-tab&runId=9469094&resultId=182606)|dotnet/runtime#93061|
|[427248](https://dev.azure.com/dnceng-public/public/_build/results?buildId=427248)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=427248&view=ms.vss-test-web.build-test-results-tab&runId=9454060&resultId=182626)|dotnet/runtime#92927|
|[426337](https://dev.azure.com/dnceng-public/public/_build/results?buildId=426337)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=426337&view=ms.vss-test-web.build-test-results-tab&runId=9385578&resultId=182621)||
|[425987](https://dev.azure.com/dnceng-public/public/_build/results?buildId=425987)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=425987&view=ms.vss-test-web.build-test-results-tab&runId=9378348&resultId=182503)||
|[421117](https://dev.azure.com/dnceng-public/public/_build/results?buildId=421117)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=421117&view=ms.vss-test-web.build-test-results-tab&runId=9340630&resultId=182549)|dotnet/runtime#92728|
|[424272](https://dev.azure.com/dnceng-public/public/_build/results?buildId=424272)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=424272&view=ms.vss-test-web.build-test-results-tab&runId=9330300&resultId=182556)||
|[424145](https://dev.azure.com/dnceng-public/public/_build/results?buildId=424145)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=424145&view=ms.vss-test-web.build-test-results-tab&runId=9325074&resultId=177061)||
|[422198](https://dev.azure.com/dnceng-public/public/_build/results?buildId=422198)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=422198&view=ms.vss-test-web.build-test-results-tab&runId=9277782&resultId=182291)||
|[419010](https://dev.azure.com/dnceng-public/public/_build/results?buildId=419010)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=419010&view=ms.vss-test-web.build-test-results-tab&runId=9193178&resultId=179563)||
|[418441](https://dev.azure.com/dnceng-public/public/_build/results?buildId=418441)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=418441&view=ms.vss-test-web.build-test-results-tab&runId=9175818&resultId=181603)||
|[418094](https://dev.azure.com/dnceng-public/public/_build/results?buildId=418094)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=418094&view=ms.vss-test-web.build-test-results-tab&runId=9165012&resultId=182494)||
|[417183](https://dev.azure.com/dnceng-public/public/_build/results?buildId=417183)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=417183&view=ms.vss-test-web.build-test-results-tab&runId=9136438&resultId=182531)||
|[416738](https://dev.azure.com/dnceng-public/public/_build/results?buildId=416738)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=416738&view=ms.vss-test-web.build-test-results-tab&runId=9121270&resultId=182531)||
|[415368](https://dev.azure.com/dnceng-public/public/_build/results?buildId=415368)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=415368&view=ms.vss-test-web.build-test-results-tab&runId=9075992&resultId=182531)|dotnet/runtime#92375|
|[415028](https://dev.azure.com/dnceng-public/public/_build/results?buildId=415028)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=415028&view=ms.vss-test-web.build-test-results-tab&runId=9064260&resultId=182513)||
|[414911](https://dev.azure.com/dnceng-public/public/_build/results?buildId=414911)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=414911&view=ms.vss-test-web.build-test-results-tab&runId=9061542&resultId=182476)||
|[413889](https://dev.azure.com/dnceng-public/public/_build/results?buildId=413889)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=413889&view=ms.vss-test-web.build-test-results-tab&runId=9033760&resultId=174358)|dotnet/runtime#92375|
|[412715](https://dev.azure.com/dnceng-public/public/_build/results?buildId=412715)|dotnet/runtime|[IntrinsicsInSystemPrivateCoreLib.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=412715&view=ms.vss-test-web.build-test-results-tab&runId=9001624&resultId=182476)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|7|34|

**Comment by ericstj** [comment]
```
            Stack Trace:
                 at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
                 at NuGet.Protocol.ServiceIndexResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
                 at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__16`1[[NuGet.Protocol.ServiceIndexResourceV3, NuGet.Protocol, Version=6.3.3.3, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
                 at NuGet.Protocol.DependencyInfoResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
                 at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__16`1[[NuGet.Protocol.Core.Types.DependencyInfoResource, NuGet.Protocol, Version=6.3.3.3, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
              /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/ReferenceAssemblies.cs(561,0): at Microsoft.CodeAnalysis.Testing.ReferenceAssemblies.GetPackageDependenciesAsync(PackageIdentity packageIdentity, NuGetFramework targetFramework, ImmutableArray`1 repositories, SourceCacheContext cacheContext, ILogger logger, Builder dependencies, CancellationToken cancellationToken)
              /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/ReferenceAssemblies.cs(227,0): at Microsoft.CodeAnalysis.Testing.ReferenceAssemblies.ResolveCoreAsync(String language, CancellationToken cancellationToken)
              /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/ReferenceAssemblies.cs(197,0): at Microsoft.CodeAnalysis.Testing.ReferenceAssemblies.ResolveAsync(String language, CancellationToken cancellationToken)
              /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/ReferenceAssemblies.cs(174,0): at Microsoft.CodeAnalysis.Testing.ReferenceAssemblies.ResolveAsync(String language, CancellationToken cancellationToken)
              /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs(1601,0): at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.<CreateSolutionAsync>d__97[[Microsoft.CodeAnalysis.Testing.Verifiers.XUnitVerifier, Microsoft.CodeAnalysis.Testing.Verifiers.XUnit, Version=1.1.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
              /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs(1416,0): at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.<CreateProjectImplAsync>d__95[[Microsoft.CodeAnalysis.Testing.Verifiers.XUnitVerifier, Microsoft.CodeAnalysis.Testing.Verifiers.XUnit, Version=1.1.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
              /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs(1395,0): at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.<CreateProjectAsync>d__94[[Microsoft.CodeAnalysis.Testing.Verifiers.XUnitVerifier, Microsoft.CodeAnalysis.Testing.Verifiers.XUnit, Version=1.1.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
              /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs(1373,0): at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.<GetSolutionAsync>d__93[[Microsoft.CodeAnalysis.Testing.Verifiers.XUnitVerifier, Microsoft.CodeAnalysis.Testing.Verifiers.XUnit, Version=1.1.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
              /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs(1097,0): at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.<GetSortedDiagnosticsAsync>d__82[[Microsoft.CodeAnalysis.Testing.Verifiers.XUnitVerifier, Microsoft.CodeAnalysis.Testing.Verifiers.XUnit, Version=1.1.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
              /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs(465,0): at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.<VerifyDiagnosticsAsync>d__69[[Microsoft.CodeAnalysis.Testing.Verifiers.XUnitVerifier, Microsoft.CodeAnalysis.Testing.Verifiers.XUnit, Version=1.1.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
              /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs(219,0): at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.<RunImplAsync>d__64[[Microsoft.CodeAnalysis.Testing.Verifiers.XUnitVerifier, Microsoft.CodeAnalysis.Testing.Verifiers.XUnit, Version=1.1.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
              /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs(188,0): at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.<RunAsync>d__63[[Microsoft.CodeAnalysis.Testing.Verifiers.XUnitVerifier, Microsoft.CodeAnalysis.Testing.Verifiers.XUnit, Version=1.1.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
              /_/src/libraries/System.Private.CoreLib/tests/IntrinsicsInSystemPrivatecoreLibAnalyzer.Tests/CSharpAnalyzerVerifier`1.cs(35,0): at IntrinsicsInSystemPrivateCoreLib.Test.CSharpAnalyzerVerifier`1.<VerifyAnalyzerAsync>d__3[[IntrinsicsInSystemPrivateCoreLib.IntrinsicsInSystemPrivateCoreLibAnalyzer, System.Private.CoreLib.Generators, Version=42.42.42.42, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].MoveNext()
              /_/src/libraries/System.Private.CoreLib/tests/IntrinsicsInSystemPrivatecoreLibAnalyzer.Tests/IntrinsicsInSystemPrivateCoreLibUnitTests.cs(578,0): at IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestHelperMethodsUnrelatedPropertyDoesntHelp()
              --- End of stack trace from previous location ---
```

Yikes!  Do we really want our analyzer tests accessing NuGet.org to try to fetch reference assemblies?  That doesn't seem right.  @sharwell do you think these tests are missing something to tell the test framework where to find reference assemblies.  Those must be available as part of the helix payload...

**Comment by jkoritzinsky** [comment]
We have a mechanism in this repo to use the live Reference Pack. We should use it. Alternatively, since this analyzer is just for CoreLib, we should configure the tests to only pull in CoreLib as a reference.
