### ISSUE TITLE
ComWrappers.GetOrCreateObjectForComInstance becomes expensive during the Get cached RCW scenario when called from multiple threads

### ISSUE THREAD

**Issue by manodasanW** [dotnet/runtime#90964]
### Description

From multiple different threads, do calls to `ComWrappers.GetOrCreateObjectForComInstance` to get the RCW for the same existing native object which has already been cached.  Observe that the amount of time this takes can be pretty high due to the mutex in `ExtObjCxtCache` which causes it to become a one at a time operation to do the cached RCW lookup.

https://github.com/dotnet/runtime/blob/7cffd46ec956fbbb0c1e4b0fbe0a3a1b335ef006/src/coreclr/vm/interoplibinterface_comwrappers.cpp#L828

### Configuration

.NET 6

### Regression?

No

**Comment by AaronRobinsonMSFT** [comment]
The fix here would be to use a reader/writer lock instead of a mutex. We should consider this early in .NET 9.

/cc @agocke @jkoritzinsky
