### ISSUE TITLE
Microsoft.NET.CrossGen.targets: stop using legacy runtime graph

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#90977]
The .NET 8 SDK is using the new trimmed graph by default, with the exception of `Microsoft.NET.CrossGen.targets` which is still using the legacy graph.

https://github.com/dotnet/runtime/blob/7881fe334c68ccd2aaa6c8d13976df3786e00e83/src/tasks/Crossgen2Tasks/Microsoft.NET.CrossGen.targets#L446

Relates to https://github.com/dotnet/runtime/issues/90000.

cc @elinor-fung @dsplaisted @ViktorHofer

**Comment by ViktorHofer** [comment]
@elinor-fung I marked this as 8.0 for now. Please take a look.

**Comment by elinor-fung** [comment]
I think we want `BundledRuntimeIdentifierGraphFile` -> `RuntimeIdentifierGraphPath` to match the change @dsplaisted made for the shipping target in sdk: https://github.com/dotnet/sdk/blob/main/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.CrossGen.targets#L447

**Comment by elinor-fung** [comment]
Actually, I don't think we can do that until runtime moves to using an SDK that has the trimmed graph (RC1).

**Comment by ViktorHofer** [comment]
You could the following meanwhile:

`$([MSBuild]::ValueOrDefault('$(RuntimeIdentifierGraphPath)', '$(BundledRuntimeIdentifierGraphFile)'))`

So it reads from the first property and only if that one isn't set, read from the legacy one.
