### ISSUE TITLE
[API Proposal]: Make `ValueTuple<>` implement `IFormattable`

### ISSUE THREAD

**Issue by Neme12** [dotnet/runtime#90992]
### Background and motivation

Currently, `ValueTuple<>.ToString` always formats the items using the current culture and there's no way to get it formatted with the invariant culture. Having everything formatted in the invariant culture is important for some scenarios, be it logging etc. I would expect that when I do `Convert.ToString(object, CultureInfo.InvariantCulture)` that the object will always be formatted with the invariant culture, but this is not true for items inside tuples.

### API Proposal

```diff
 namespace System;

 public struct ValueTuple<T1, T2>
+     : IFormattable
 {
+    public string ToString(string? format, IFormatProvider? formatProvider) =>
+        string.Create(formatProvider, $"({Item1}, {Item2})");

     // Or alternatively, since the "format" argument would be ignored, we could implement the interface explicitly
     // and instead provide a public overload that only takes the `IFormatProvider`:
+    string IFormattable.ToString(string? format, IFormatProvider? formatProvider) => ToString(formatProvider);
+    public string ToString(IFormatProvider? formatProvider) =>
+        string.Create(formatProvider, $"({Item1}, {Item2})");
 }

 // ...and for all other arities
```

### API Usage

```csharp
using System.Globalization;

PrintObject((0, 1.5));

void PrintObject(object obj)
{
    // Unfortunately this doesn't work - it prints the decimal separator of the current culture,
    // because ValueTuple doesn't implement IFormattable and doesn't propagate the culture through.
    Console.WriteLine(Convert.ToString(obj, CultureInfo.InvariantCulture));
}
```

**Comment by Neme12** [comment]
`ISpanFormattable` would be nice as well to improve perf when a tuple is in an interpolated string

**Comment by tannergooding** [comment]
CC. @stephentoub

Any concerns around this? We could make it follow the general format that `records` are using for listing each `T`.

**Comment by Neme12** [comment]
@tannergooding It already overrides `ToString`, which prints `$"({Item1}, {Item2})"` and similar for other arities. The problem is that it always formats the items using the current culture - I'd like to be able to have it formatted with an invariant culture.

**Comment by stephentoub** [comment]
> Any concerns around this?

Regarding "since the "format" argument would be ignored", why would the format argument be ignored?

Separate from that, a concern would be yet further size impact on every generic specialization of `ValueTuple<...>` for Native AOT.

**Comment by jkotas** [comment]
> Any concerns around this?

It is common for apps to have many ValueTuple instantiations. Implementing a new interface that is unlikely to be trimmed on ValueTuple will make every instantiation more expensive. ValueTuples are not cheap to start with. It is likely going be manifest as a measurable regression in AOT scenarios.

> public string ToString(IFormatProvider? formatProvider) =>
>     string.Create(formatProvider, $"({Item1}, {Item2})");

This is fine implementation for invariant culture, but it is not the right implementation for non-invariant cultures. `, ` seperator is necessarily correct for arbitrary culture. We had similar discussion in https://github.com/dotnet/runtime/issues/11604#issue-557926365

**Comment by Neme12** [comment]
> This is fine implementation for invariant culture, but it is not the right implementation for non-invariant cultures. `, ` seperator is not necessarily correct for arbitrary culture. We had similar discussion in [#11604 (comment)](https://github.com/dotnet/runtime/issues/11604#issue-557926365)

Then the current implementation is wrong, because it always uses commas with the current culture.

**Comment by Neme12** [comment]
I would be happy without the interface if the implementation was changed to always use invariant culture, but I don't know if that's acceptable.

**Comment by jkotas** [comment]
> Then the current implementation is wrong, because it always uses commas with the current culture.

Yes, it is the case in general for number of `ToString()` overrides. Historically, we did not have rules for how `ToString()` overrides should deal with current culture. The result is that number of `ToString()` overrides are hodge podge of current culture and invariant culture formatting.

**Comment by Neme12** [comment]
> Regarding "since the "format" argument would be ignored", why would the format argument be ignored?

Because I'm not proposing any new format for tuples, it would still always be `$"({Item1}, {Item2})"`, only the culture would affect it. Although it might be better to throw if the format string isn't empty rather than ignore it.

**Comment by stephentoub** [comment]
> Because I'm not proposing any new custom format for tuples, it would still always be $"({Item1}, {Item2})", only the culture (or IFormatProvider) would affect it.

Accepting a culture means passing that culture to a T's `IFormattable.ToString(string, IFormatProvider)` implementation. Why is it correct to pass along the provider but not the string?

**Comment by Neme12** [comment]
You mean pass the string to every item in the tuple? That seems off to me given that the items could be different types, e.g. an `int` and a `DateTime`. You would need some syntax for specifying the format for each item separately, but that seems like overkill to me - if you do that, you can just format it manually. This should just be for quick formatting in logging, serialization, etc.

**Comment by Neme12** [comment]
Also, if I was able to pass in a `format` string, I'd expect it to apply to the tuple itself - in that tuples would have a few predefined formats, not to the individual items. Just like when formatting a `DateTime`, the format applies to the whole `DateTime` and not to the year, day and month numbers. If you need custom formatting for those numbers, you have to format it manually.

**Comment by stephentoub** [comment]
> You mean pass the string to every item in the tuple? That seems off to me given that the items could be different types, e.g. an int and a DateTime.

Yes. I don't see why it's different for the culture vs a format string. You could have different items you want formatted in different ways, e.g. format one item as invariant and one as fr-FR.  You always have the out of formatting each item individually.

What is your actual use case for this? Why does the culture matter for the output purposes, and why can't you just format it exactly how you want it yourself?

**Comment by Neme12** [comment]
The culture matters because I want my logs always formatted with the invariant culture, not based on the language of the request.

> and why can't you just format it exactly how you want it yourself?

I can of course, it just seemed like something that should work by default. If I do `Convert.ToString(obj, CultureInfo.InvariantCulture)`, I'd expect the object and everything in it to always be formatted with the invariant culture, but because tuples don't implement `IFormattable` and don't pass the culture through, that's not the case.

**Comment by Neme12** [comment]
> Yes. I don't see why it's different for the culture vs a format string. You could have different items you want formatted in different ways, e.g. format one item as invariant and one as fr-FR. 

An `IFormatProvider` is always an `IFormattable` and is the same for all types, but format string differ between types. That's why I think different. If you pass in a format string for Item1 and Item2 is of a different type and doesn't recognize that format, you'll get an error.

**Comment by stephentoub** [comment]
I hear you. And I think it'd be very strange for a wrapper IFormattable to not pass along all its arguments to the wrapped IFormattables, instead selectively choosing to only do some of them.  Combine the lack of an obvious right answer here with the size concerns for native aot, and an easy workaround of just setting the current culture to be invariant, I don't think this is something we should be adding.

**Comment by Neme12** [comment]
Well I can't set the culture to invariant for the entire app. But I guess I can just wrap the call to `ToString` with current culture temporarily changed to invariant.

**Comment by stephentoub** [comment]
> But I guess I can just wrap the call to ToString with current culture temporarily changed to invariant.

Yes

**Comment by Neme12** [comment]
> And I think it'd be very strange for a wrapper IFormattable to not pass along all its arguments to the wrapped IFormattables, instead selectively choosing to only do some of them. 

I don't think that would be a strange at all. The tuple itself just wouldn't support custom formats, that's why you couldn't pass one it. But the culture is sort of an ambient thing that should always be passed down, and not something specific to each thing you're formatting.

**Comment by Neme12** [comment]
> It is common for apps to have many ValueTuple instantiations. Implementing a new interface that is unlikely to be trimmed on ValueTuple will make every instantiation more expensive. ValueTuples are not cheap to start with. It is likely going be manifest as a measurable regression in AOT scenarios.
> 
> >

BTW, I really dislike the fact that these arguments are now used to halt the evolution of .NET in general, not only with this API but with all other APIs as well. The trimmer should just be fixed to be better at removing things like this if they're unused.

**Comment by stephentoub** [comment]
> I really dislike the fact that these arguments are now used to halt the evolution of .NET in general

They don't "halt the evolution of .NET". They're one consideration.

> The trimmer should just be fixed to be better at removing things like this if they're unused.

We'd welcome PRs if you have good ways of addressing the concerns.
