### ISSUE TITLE
Options source generator shouldn't use random names

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#90990]
https://github.com/dotnet/runtime/blob/3ef2c804b4fea8c94c9bd5cc39f79525361a03d2/src/libraries/Microsoft.Extensions.Options/gen/Emitter.cs#L40-L42

Generated code should be deterministic. Many companies and orgs have requirements around deterministic builds.

              Is this the code that prompted https://github.com/dotnet/roslyn-analyzers/pull/6882/? Should we change this code to not use Random, and instead be deterministic?

cc @jaredpar

_Originally posted by @eerhardt in https://github.com/dotnet/runtime/pull/89148#discussion_r1303095388_

**Comment by tarekgh** [comment]
@jaredpar what is the suggestion here? We need to have a class name that is global internal and not conflict when two independent compilations using the generator and one of them is internal visible to the other one. The source gen supports Lang versions 8+. We already detect if using Lang Version 11+ we use `file` keyword and not using random at all.

**Comment by stephentoub** [comment]
> what is the suggestion here?

Incorporate a hash of more data, like the assembly's name.

Or use C#11 and/or don't use InternalsVisibleTo.

**Comment by tarekgh** [comment]
> Or use C#11 and/or don't use InternalsVisibleTo.

I want to avoid restricting the language version only because of that. I am not sure what do you mean by `don't use InternalsVisibleTo.`? It is the user who is using it and not the generator. Do you mean we shouldn't support this scenario? This is a real scenario we got from R9.

> Incorporate a hash of more data, like the assembly's name.

This looks like a reasonable idea to try. Thanks!

**Comment by jaredpar** [comment]
> I want to avoid restricting the language version only because of that.

I would start with requiring C# 11 and wait to see if users push back. Other generators like the regex generator have set  [that standard](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.RegularExpressions/gen/RegexGenerator.cs#L306) and, to my understanding at least, that has not been a problem thus far. I would not invest in making my generator more complex to support this scenario unless I had data saying that would be valuable.

**Comment by tarekgh** [comment]
@geeknoid @stephentoub @eerhardt would you be ok if we require Language version 11+ for the options source gen? 

CC @ericstj

**Comment by stephentoub** [comment]
> . I am not sure what do you mean by don't use InternalsVisibleTo.? It is the user who is using it and not the generator. Do you mean we shouldn't support this scenario?

I mean if incorporating assembly name is insufficient and you absolutely need IVT and you're using the options generator in two assemblies connected by IVT and you're using a language version less than 11, bump it to 11. This is why `file` exists.

**Comment by tarekgh** [comment]
This is fixed by https://github.com/dotnet/runtime/pull/91432
