### ISSUE TITLE
Instructions for building not linked on CONTRIBUTING.md

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#910]
CONTRIBUTING.md should link to the instructions on how to build the repository. 

Note: AFAICT neither README.md or CONTRIBUTING.md links to the build instructions.

**Comment by dhusemann** [comment]
@danmosemsft was this done with the update to readme.md??

**Comment by ViktorHofer** [comment]
Just took a look, there is still no link to the building instructions from the Contributing.md so this is still todo.

**Comment by danmosemsft** [comment]
I'll add something simple to CONTRIBUTING.md. Looks like I only updated README.md.
