### ISSUE TITLE
Retry Counts are high in Http3 Tests

### ISSUE THREAD

**Issue by liveans** [dotnet/runtime#91017]
There are Http3 tests that pass on retries.

Some test examples are:
- System.Net.Http.Functional.Tests.HttpMetricsTest_Http30.RequestDuration_EnrichmentHandler_Success_Recorded
- System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ServerSendsTrailingHeaders_Success
- System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test_Http3.RequestSent_HandlerDisposed_RequestIsUnaffected

**Comment by ManickaP** [comment]
Did some digging, this is still true for some tests. Query:
```
AzureDevOpsTests
| where (TestName has "Http3" or TestName has "Http30") and Outcome != "Pass" and Branch == "main" and Repository == "dotnet/runtime" and RunCompleted >= ago(90d)
| order by RunCompleted desc 
| project-away TestResultId, JobId, JobName, WorkItemId, WorkItemName, WorkItemFriendlyName, BuildDefinitionId, ArgumentHash, Arguments, TestRunId, BuildId
| summarize LastRun=max(RunCompleted) by TestName
```
Result:

<details>

| TestName | LastRun |
| -------- | ------- |
| System.Net.Http.Functional.Tests.SocketsHttpHandler_SocketsHttpHandler_SecurityTest_Http3.SslOptions_CustomPolicy_IgnoresNameMismatch | 2023-07-23T22:10:35.89Z |
| System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Headers_Http3.SendAsync_SpecialHeaderKeyOrValue_Success | 2023-07-26T21:49:38.497Z |
| System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Headers_Http3.GetAsync_LargeHeader_Success | 2023-07-29T13:33:15.707Z |
| System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test_Http3.Expect100Continue_WaitsExpectedPeriodOfTimeBeforeSendingContent | 2023-07-31T11:56:13.413Z |
| System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpRequestErrorTest_Http30.NameResolutionError | 2023-08-01T16:43:07.337Z |
| System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Cookies_Http3.GetAsync_SetCookieContainerMultipleCookies_CookiesSent | 2023-08-03T20:36:26.053Z |
| System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.Public_Interop_ExactVersion_BufferContent_Success | 2023-08-06T11:54:28.983Z |
| System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Headers_Http3.SendAsync_Expires_Success | 2023-08-07T16:48:29.657Z |
| System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test_Http3.PostAsync_CancelDuringRequestContentSend_TaskCanceledQuickly | 2023-08-08T14:02:12.81Z |
| System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Cookies_Http3.GetAsync_ReceiveSetCookieHeader_CookieAdded | 2023-08-10T03:06:53.283Z |
| System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ClientSettingsReceived_Success | 2023-08-10T10:53:02.61Z |
| System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.SendMoreThanStreamLimitRequests_Succeeds | 2023-08-10T10:53:02.61Z |
| System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue | 2023-08-16T13:18:51.04Z |
| System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.StatusCodes_ReceiveSuccess | 2023-08-19T10:10:05.873Z |
| System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ResponseCancellation_BothCancellationTokenAndDispose_Success | 2023-08-25T21:46:03.043Z |
| System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ServerClosesInboundControlStream_ClientClosesConnection | 2023-08-30T20:36:08.21Z |
| System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Cookies_Http3.GetAsync_SetCookieContainer_CookieSent | 2023-09-05T09:58:45.597Z |
| System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_UnsuccessfulRequest_LogsStartFailedStop | 2023-09-07T11:43:58.303Z |
| System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_MaxResponseHeadersLength_Http3.ThresholdExceeded_ThrowsException | 2023-09-10T10:07:37.727Z |
| System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.RequestSendingResponseDisposed_ThrowsOnServer | 2023-09-11T09:34:07.117Z |
| System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_MaxResponseHeadersLength_Http3.LargeSingleHeader_ThrowsException | 2023-09-11T18:40:14.53Z |
| System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.DuplexStreaming_AbortByServer_StreamingCancelled | 2023-09-12T17:26:19.4Z |
| System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ServerSendsTrailingHeaders_Success | 2023-09-12T21:00:02.927Z |
| System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ServerClosesOutboundControlStream_ClientClosesConnection | 2023-09-12T23:17:48.79Z |
| System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.SendAsync_RequestRejected_ClientRetries | 2023-10-02T19:24:10.26Z |
| System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ServerClosesConnection_ThrowsHttpProtocolException | 2023-10-05T00:19:01.517Z |
| System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Headers_Http3.SendAsync_InvalidCharactersInHeader_Throw | 2023-10-07T10:23:46.94Z |
| System.Net.Http.Functional.Tests.SocketsHttpHandler_SocketsHttpHandler_SecurityTest_Http3.SslOptions_InvalidName_Throws | 2023-10-11T16:16:54.7Z |
| System.Net.Http.Functional.Tests.HttpMetricsTest_Http30.RequestDuration_EnrichmentHandler_Success_Recorded | 2023-10-12T11:24:48.05Z |
| System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked | 2023-10-13T11:09:16.363Z |
| System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.Public_Interop_ExactVersion_Success | 2023-10-13T12:32:29.937Z |
| System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.Public_Interop_Upgrade_Request3OrLower_Success | 2023-10-13T12:32:30.073Z |
| System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.Public_Interop_Upgrade_Request2OrHigher_Success | 2023-10-15T12:32:11.003Z |
| System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.ReadAsStreamAsync_HandlerProducesWellBehavedResponseStream | 2023-10-16T10:08:51.993Z |
| System.Net.Http.Functional.Tests.SocketsHttpHandler_RequestContentLengthMismatchTest_Http3.ContentLength_DoesNotMatchRequestContentLength_Throws | 2023-10-16T10:11:33.387Z |
| System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test_Http3.RequestSent_HandlerDisposed_RequestIsUnaffected | 2023-10-16T16:00:19.557Z |
| System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Headers_Http3.GetAsync_EmptyResponseHeader_Success | 2023-10-18T02:23:41.687Z |
| System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.SendStreamLimitRequestsConcurrently_Succeeds | 2023-10-18T02:23:41.95Z |
| System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.SendMoreThanStreamLimitRequestsConcurrently_LastWaits | 2023-10-18T02:23:41.95Z |

</details>

**Comment by ManickaP** [comment]
This is still hapenning.
