### ISSUE TITLE
[API Proposal]: Add span-based `StringInfo.GetNextTextElement`

### ISSUE THREAD

**Issue by Neme12** [dotnet/runtime#91020]
### Background and motivation

`StringInfo` has a span-based overload for `GetNextTextElementLength`, but not for `GetNextTextElement`. It would be convenient to have an overload for `GetNextTextElement` as well that returns a span.

### API Proposal

```diff
 namespace System.Globalization;

 public partial class StringInfo
 {
+    public static ReadOnlySpan<char> GetNextTextElement(ReadOnlySpan<char> str);
+    public static Span<char> GetNextTextElement(Span<char> str);
     public static string GetNextTextElement(string str);
     public static string GetNextTextElement(string str, int index);
     public static int GetNextTextElementLength(ReadOnlySpan<char> str);
     public static int GetNextTextElementLength(string str);
     public static int GetNextTextElementLength(string str, int index);
 }
```

### API Usage

```csharp
while (true)
{
    var textElement = StringInfo.GetNextTextElement(span);
    // ...
    span = span.Slice(0, textElement.Length);
}
```

**Comment by teo-tsirpanis** [comment]
It can be trivially implemented by user code with `GetNextTextElementLength`. One of the reasons I guess they did not do it is to avoid having overloads for read-only and read-write spans.

**Comment by Neme12** [comment]
I know `GetNextTextElementLength` can be used, but having an API that directly returns a span would be much more convenient.

**Comment by vcsjones** [comment]
The original proposal was to return a span, and during API review it was modified to return the length. See https://github.com/dotnet/runtime/issues/28704 for details.

**Comment by Neme12** [comment]
Why not both though?

**Comment by vcsjones** [comment]
cc @GrabYourPitchforks if you can recall - the actual YouTube recording of the API review for 28704 ends before that one was reviewed (though I can see it in Jeremy's tab list of things to review, so I am assuming it was approved in that session)

> Why not both though?

My two cents: two APIs that provide more or less the same purpose but return different types simply for convenience is confusing for some people and bloats developer tooling. As @teo-tsirpanis points out it's trivially implementable as a utility or extension method, and the linked issue states why it was changed: it's more functional to return the length.

**Comment by Neme12** [comment]
> My two cents: two APIs that provide more or less the same purpose but return different types simply for convenience is confusing for some people and bloats developer tooling

But there are already 2 different versions for `string` - `GetNextTextElementLength` and `GetNextTextElement`. Why not have both versions for span as well?

**Comment by vcsjones** [comment]
`GetNextTextElement` goes back to .NET Framework 1.1. It's there because that's how it was originally written. I don't know that it would be there if the type was designed from scratch.

`GetNextTextElementLength` was added in .NET 6 as a generalized solution to determine the length without caring whatever the intended representation is, be it a span, memory, ArraySegment, etc.

**Comment by Neme12** [comment]
I'll just close this one, it looks like this is unwanted.
