### ISSUE TITLE
cross build win-x64 on macOS: app.manifest requireAdministrator not working

### ISSUE THREAD

**Issue by kzhui125** [dotnet/runtime#91047]
### Description

cross build win-x64 on macOS: app.manifest requireAdministrator not working

### Reproduction Steps

On macOS:

1. `dotnet new console` (dotnet 7)
2. add `<ApplicationManifest>app.manifest</ApplicationManifest>` to csproj
3. add app.manifest:
```xml
<?xml version="1.0" encoding="utf-8"?>
<assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1">
  <assemblyIdentity version="1.0.0.0" name="MyApplication"/>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v2">
    <security>
      <requestedPrivileges xmlns="urn:schemas-microsoft-com:asm.v3">
        <requestedExecutionLevel level="requireAdministrator" uiAccess="false" />
      </requestedPrivileges>
    </security>
  </trustInfo>

  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
    </application>
  </compatibility>

</assembly>
```
4. `dotnet build -r win-x64 --no-self-contained`
5. copy the build file to Windows Server.

### Expected behavior

requireAdministrator works

### Actual behavior

the requireAdministrator setting is not working:

<img width="471" alt="image" src="https://github.com/dotnet/runtime/assets/11925432/fd8731d2-c5aa-4868-9127-317aeeccffbd">
<img width="380" alt="image" src="https://github.com/dotnet/runtime/assets/11925432/13648264-3a22-48bd-8045-7884cf40d14a">

**Comment by huoyaoyuan** [comment]
It's a known issue: #66906

**Comment by vitek-karas** [comment]
This is https://github.com/dotnet/runtime/issues/3828. It has been fixed in .NET 8 - you should be able to use the .NET 8 SDK to target net7.0 and the fix should still apply.

**Comment by kzhui125** [comment]
Thanks
