### ISSUE TITLE
Specific Win10/11 Proxysettings cause wrong result in WebRequest.DefaultWebProxy.GetProxy(...)

### ISSUE THREAD

**Issue by ole1986** [dotnet/runtime#91045]
### Description

Believe it or not!

I noticed when running .NET 6 Framework on Win10 Build 1905.3324 with VS 2022 17.6.5 it seem to be important that the URL given in the System -> Proxysetting does not contain any "http://" prefixes in the address field.

As long as Proxysetting is stored with "http://", the following code always returns NULL instead of the proxy Uri

`WebRequest.DefaultWebProxy.GetProxy("https://google.de")`

### Reproduction Steps

1. create a simple console app with `WebRequest.DefaultWebProxy.GetProxy("https://google.de")` to return
2. Configure the Win10 System -> Proxysettings to contain "http://" in the address field (E.g. Address: http://proxy.fqdn.local Port: 3128) and keep the proxy exceptions empty
3. Enable and save the Proxysettings
4. Run the console app and expect a NULL to be returned from `GetProxy(...)` method

### Expected behavior

`WebRequest.DefaultWebProxy.GetProxy("https://google.de")` should return the Proxy URL given in the Proxysettings of the system

### Actual behavior

`WebRequest.DefaultWebProxy.GetProxy("https://google.de")` returns NULL

### Regression?

I assume it worked on .NET 4.x since I used this framework version before migrating to .NET 6

### Known Workarounds

NOW COME THE FUN PART
---

The workaround to use the very old "Internet option" which is still available in Win10

<img width="304" alt="image" src="https://github.com/dotnet/runtime/assets/4850116/a8099b2f-f6cc-4476-9cd0-379e00693e4a">

Since, the Proxy configuration from the "Internet options" dialog causes the proxy address to always be stored without "http://" prefix

### Configuration

1. .NET 6
2. Win10 Build 1905.3324
3. x64 platform
4. Visual Studio 2022 17.6.5

**Comment by ole1986** [comment]
As a side note it might also be a simple OS bug, since the proxy configuration shows inconsistencies between "internet options"  and "System -> Proxysettings"

**Comment by karelz** [comment]
@ole1986 can you try [`HttpClient.DefaultProxy`](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultproxy) instead? (`WebRequest` is obsolete for compat only and although it might be the same implementation behind it, let's stick with proper APIs)
Ideally try it on 7.0 or 8.0 Preview7 bits?
Are you able to reproduce the same problem on more than 1 machine in your environment?

Given that this is the first report, it is a bit suspicious.

**Comment by ole1986** [comment]
@karelz Unfortunately not!

So whenever the registry value ~~`Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Connections\DefaultConnectionSettings` or~~ `Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ProxyServer` contains a "http://" prefix `WebRequest.DefaultWebProxy.GetProxy([...])` and `HttpClient.DefaultProxy([..])` returns NULL

To my surprise `DefaultWebProxy`` and `DefaultProxy` actually translates the proxy url correctly in both cases (with/without "https://" prefix). 

![image](https://github.com/dotnet/runtime/assets/4850116/f0c26afb-4050-49da-b2c2-57697161b2e8)

But `.GetProxy([..])` only succeeded when not "http://" prefix is given in the `ProxyServer` REG_DWORD.

This is most properly the reason why the `Internet option` workaround does the trick

**Comment by ole1986** [comment]
I have tested in on simple console apps using VS 2022 with .NET 6 and VS 2019 with .NET 4.8

VS 2019 .NET 4.8
![image](https://github.com/dotnet/runtime/assets/4850116/7067ff0c-4576-49d5-812d-fe125592ef33)

VS 2022 .NET 6
![image](https://github.com/dotnet/runtime/assets/4850116/e41963cc-c733-42ca-9c7e-12a169a7dea2)

Running on the same machine

Attached are both projects

[ProxyNoIssueNET4.zip](https://github.com/dotnet/runtime/files/12437668/ProxyNoIssueNET4.zip)
[ProxyIssueNET6.zip](https://github.com/dotnet/runtime/files/12437669/ProxyIssueNET6.zip)

**Comment by ole1986** [comment]
Since we are using ArcGIS Pro SDK 3.X we follow the recommendation to use .NET 6 according to ESRI recommendation
https://github.com/Esri/arcgis-pro-sdk/wiki#requirements

**Comment by karelz** [comment]
@ole1986 can you run your test in a HelloWorld console app in your environment? On .NET 7.0 and 8.0 Preview7 (or daily 8.0 builds)?
Then check if you can reproduce the same problem (in the console app) on more than 1 machine in your environment.

**Comment by ole1986** [comment]
Just updated the issue https://github.com/dotnet/runtime/issues/91045#issuecomment-1693070149 containing .NET 7 which does have no problem.

Tested on several machine with same results!!!

Again, since we are using ArcGIS SDK 3.X we cannot switch  to .NET 7 (yet)

**Comment by ole1986** [comment]
Updated comment [1693070149](https://github.com/dotnet/runtime/issues/91045#issuecomment-1693070149) to contain .NET 7
Tested on several machines with same results

**Comment by fabeabe** [comment]
I can reproduce this with:
- VS 2019 .NET 4.8 (no problem)
- VS 2022 .NET 6 (problem occurred)

**Comment by dotMorten** [comment]
Thanks @karelz . I work on a different SDK but will try and find who owns this part of the pro SDK. However since that SDK is for making plugins for a desktop product they probably don’t have the ability to move to .net7+.
It should be possible to try it in an external net7 app though although that won’t help a plug-in user.

**Comment by ole1986** [comment]
@dotMorten example projects are already to my comment for .net 4.8, 6.0 and 7.0

**Comment by ole1986** [comment]
What is the status regarding this issue?

**Comment by karelz** [comment]
The issue is rather confusing.

Originally, 7.0 was supposed to work fine. But it seems that it is not after all.
There seems to be a workaround, so it does not seem to be urgent.

Next steps I see:
- Try it on main (9.0) - reproduce it internally
- Analyze what is wrong and propose a fix (for main = 9.0)
- Based on the findings above + impact on customers, consider servicing it

I think we should be able to get to the next steps in a few weeks.

**Comment by ScotMac** [comment]
What is the status of this?

In general, the WebRequest.DefaultWebProxy.GetProxy() API is useful, since it returns results based on the input Uri. ie, it will return the input Uri if no proxy is needed and will return the system proxy if a proxy is needed. I don't see similar functionality in the HttpClient. Please correct me if i somehow missed it.

**Comment by wfurt** [comment]
This looks like dup of  #38670, does it not? 
as https://github.com/dotnet/runtime/issues/38670#issuecomment-653108954 correctly stated, when the entry starts with `http://` current implementation applies only to http traffic (and not https). That is different than what browsers do.
