### ISSUE TITLE
[API Proposal]: Simplify IEnumerable implementation 

### ISSUE THREAD

**Issue by km-hussain-in** [dotnet/runtime#91043]
### Background and motivation

Implementing IEnumerable&lt;T&gt; requires explicit implementation of IEnumerable.GetEnumerator which can now be implemented as a default method in IEnumerable&lt;T&gt; it self.

### API Proposal

```csharp
namespace System.Collections.Generic;

public class MyFancyCollection<T> : IEnumerable<T>
{
    public void Fancy(T item);
}
```

### API Usage

interface IEnumerable&lt;out T&gt; : IEnumerable
{
    new IEnumerator&lt;T&gt; GetEnumerator();

    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
}

**Comment by huoyaoyuan** [comment]
Correctly,
```csharp
interface IEnumerable<T> : IEnumerable
{
    new IEnumerator<T> GetEnumerator();

    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
}
```

**Comment by km-hussain-in** [comment]
> Correctly,
> 
> ```cs
> interface IEnumerable<T> : IEnumerable
> {
>     new IEnumerator<T> GetEnumerator();
> 
>     IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
> }
> ```



> 

Thanks, the way I put the angular brackets are not visible in HTML view

**Comment by teo-tsirpanis** [comment]
Hello, [adding a default implementation to an existing interface method is an unacceptable breaking change](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/breaking-change-rules.md#:~:text=Adding%20a%20default%20implementation%20of%20an%20existing%20interface%20method%20(IA.Foo)%20on%20an%20existing%20interface%20type%20(IB)). I'm going to close this issue.

**Comment by huoyaoyuan** [comment]
I can see the rationale about breaking, but I don't see the reality for this specific case. Except the non-generic ICollection and IList, I can't see any interface that inherits from non-generic IEnumerable.

**Comment by km-hussain-in** [comment]
It doesn't break existing implementations of IEnumerable&lt;T&gt;

**Comment by tarekgh** [comment]
`IEnumerable<T>` is one of the sensitive interfaces we are not touching because it is supported in the netstandard. This proposal will have issues for users targeting netstandard as the default implementations will not exist in the older platforms (like netfx).
