### ISSUE TITLE
[API Proposal]: Sytem.Net.NameResultion lib support lookup diversiform DNS types

### ISSUE THREAD

**Issue by RichardChen820** [dotnet/runtime#91051]
### Background and motivation

Sytem.Net.NameResultion lib does not support querying DNS types like SRV.

### API Proposal

```csharp
namespace System.Net

public static class DNS
{
    public static  Task<DnsQueryRespones> Resolve(string hostName, RecordType type, CancellationToken ct );
}
```

### API Usage

```csharp
var response = await Dns.Resolve("_srv._tcp.contoso.com", RecordType.Srv, CancellationToke.None)

var anwsers = response.Anwsers;

foreach( var a in answers)
{
    var srv = a as SrvRecord;
   Console.WriteLine(srv.Target);
}
```

**Comment by antonfirsov** [comment]
This looks like duplicate of #19443.

Currently `Dns` relies on OS `getaddrinfo` limiting it to very basic resolution capabilities. To overcome this, we would either need to implement and maintain a proper managed DNS client or to wrap an existing library, which is fairly untrivial work and opens many questions.

@RichardChen820 have you considered trying 3rd party OSS libs like [DnsClient.Net](https://github.com/MichaCo/DnsClient.NET) or [DinoDNS](https://github.com/TurnerSoftware/DinoDNS)?

**Comment by karelz** [comment]
Duplicate of #19443

**Comment by RichardChen820** [comment]
@antonfirsov Thanks for pointing out the main thread of the proposal.

We released a lib that only depends on MS first-party thing (dotnet build-in or Azure SDKs), recently we plan to support a new feature in our lib that relies on the capability of performing SRV DNS lookup. Hence my intuition is to seek first-party support rather than introducing 3rd party OSS lib, to not extend the maintenance scope, keep everything in MS to ensure quick response for any potential vulnerability/security issue in the feature.

**Comment by wfurt** [comment]
My guess is we would need to proceed with #42185. As @antonfirsov mentioned the glibc interface dopes not provide enough functionality on unix. The main issue I see there is consistency with OS resolver e.g. processing all the nsswitch.conf, resolve.conf, hosts and possibly other files.
