### ISSUE TITLE
.NET SDK on Ubuntu 18.04.6 libnethost.a contains inexisting libstdc++ symbol

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/runtime#91067]
### Description

Copied from https://developercommunity.visualstudio.com/t/NET-SDK-on-Ubuntu-18046-libnethosta-/10269507

I am working on a project which uses .NET SDK 6.0 with DNNE to call from C++ into C#. The binary can successfully build and run on Windows and Ubuntu 20.04.5, but failed to run on Ubuntu 18.04.6 with this error:

undefined symbol: _ZNSt18basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev
This symbol is introduced into the binary from libnethost.a:

$ grep '_ZNSt18basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev'  /usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64/6.0.13/runtimes/linux-x64/native/** -R
Binary file /usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64/6.0.13/runtimes/linux-x64/native/libnethost.a matches
Binary file /usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64/6.0.13/runtimes/linux-x64/native/libnethost.so matches
The symbol is supposed to be defined in /usr/lib/x86_64-linux-gnu/libstdc++.so.6. But on Ubuntu 18.04.6, it is an earlier version of the library which doesn’t contain the symbol. We are able to mitigate this problem by using the libstdc++ library that comes with Miniconda (since it is a Python project). But I think this is a bug with .NET SDK which needs to be fixed.

Thanks,
Rui

### Reproduction Steps

https://developercommunity.visualstudio.com/t/NET-SDK-on-Ubuntu-18046-libnethosta-/10269507

### Expected behavior

https://developercommunity.visualstudio.com/t/NET-SDK-on-Ubuntu-18046-libnethosta-/10269507

### Actual behavior

https://developercommunity.visualstudio.com/t/NET-SDK-on-Ubuntu-18046-libnethosta-/10269507

**Comment by jeffschwMSFT** [comment]
https://github.com/dotnet/runtime/issues/1871

**Comment by elinor-fung** [comment]
That symbol maps to a parameterless constructor for basic_stringstream:
```
# c++filt _ZNSt18basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev
std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()
```
I expect this is somehow related to the removal of explicit default constructors: https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0935r0.html. But I'm unclear how it all comes together in a way that affects our compatibility.

We compile on CentOS 7 as the lowest version supported for libc and libstdc++. From the image we use for building (mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-20210714125435-9b5bbc2), that symbol is not in libstdc++:
```
# /sbin/ldconfig -p | grep libstdc++
        libstdc++.so.6 (libc6,x86-64) => /lib64/libstdc++.so.6
# nm -D /lib64/libstdc++.so.6 | grep _ZNSt18basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev
```

But the nethost we build in that environment ends up with it: 
```
# nm artifacts/bin/linux-x64.Release/corehost/libnethost.a | grep _ZNSt18basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev | c++filt
                 U std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()

# nm -D artifacts/bin/linux-x64.Release/corehost/libnethost.so | grep _ZNSt18basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev | c++filt
0000000000021a70 W std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()
```

We've since moved to cross-compiling on Mariner - I think this is fixed in .NET 8. I checked .NET 8 Preview 7 and nethost no longer references that parameterless stringstream constructor:

```
# nm ./dotnet-8-p7/packs/Microsoft.NETCore.App.Host.linux-x64/8.0.0-preview.7.23375.6/runtimes/linux-x64/native/libnethost.a | grep _ZNSt18basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev | c++filt
#
# nm ./dotnet-8-p7/packs/Microsoft.NETCore.App.Host.linux-x64/8.0.0-preview.7.23375.6/runtimes/linux-x64/native/libnethost.a | grep stringstream | c++filt
                 U std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode)
                 U std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()
                 U VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >

# nm -D ./dotnet-8-p7/packs/Microsoft.NETCore.App.Host.linux-x64/8.0.0-preview.7.23375.6/runtimes/linux-x64/native/libnethost.so | grep _ZNSt18basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev | c++filt
#
# nm -D ./dotnet-8-p7/packs/Microsoft.NETCore.App.Host.linux-x64/8.0.0-preview.7.23375.6/runtimes/linux-x64/native/libnethost.so | grep stringstream | c++filt
                 U std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode)
                 U std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()
                 U VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >
```

@sbomer @janvorli any idea what was happening before? Do you know if we did something as part of the switch to mariner  that would have fixed this?

**Comment by elinor-fung** [comment]
Closing, since this is addressed in 8.
