### ISSUE TITLE
`Http2_MultipleConnectionsEnabled` test failures

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#91075]
Related: #89788 that recently modified and/or re-enabled some of these tests

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=381149
Build error leg or test failing: System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_OpenAndCloseMultipleConnections_Success
Pull request: https://github.com/dotnet/runtime/pull/86194

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Http2_MultipleConnectionsEnabled",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=381149
**Error message validated:** `Http2_MultipleConnectionsEnabled`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 8/24/2023 5:18:41 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[387040](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387040)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/387040/logs/968)||
|[385936](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385936)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/385936/logs/2523)|dotnet/runtime#90982|
|[385389](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385389)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/385389/logs/2801)|dotnet/runtime#90517|
|[385356](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385356)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/385356/logs/2073)|dotnet/runtime#91091|

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[390416](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390416)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ResponseDrain_Test.GetAsyncWithMaxConnections_DisposeLargerThanMaxDrainSize_KillsConnection](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390416&view=ms.vss-test-web.build-test-results-tab&runId=8377226&resultId=103836)||
|[390421](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390421)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandler_RemoteServerTest.GetAsync_SetAutomaticDecompression_ContentDecompressed_Deflate](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390421&view=ms.vss-test-web.build-test-results-tab&runId=8377242&resultId=103109)||
|[390415](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390415)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ConnectionPooling_Test.HandlerDroppedWithoutDisposal_NotKeptAlive](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390415&view=ms.vss-test-web.build-test-results-tab&runId=8376522&resultId=103657)||
|[389061](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389061)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ServerCertificates_Test.NoCallback_RevokedCertificate_NoRevocationChecking_Succeeds](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389061&view=ms.vss-test-web.build-test-results-tab&runId=8340468&resultId=103096)||
|[389063](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389063)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ServerCertificates_Test.NoCallback_RevokedCertificate_NoRevocationChecking_Succeeds](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389063&view=ms.vss-test-web.build-test-results-tab&runId=8340284&resultId=103523)||
|[387743](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387743)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ServerCertificates_Test.NoCallback_RevokedCertificate_NoRevocationChecking_Succeeds](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387743&view=ms.vss-test-web.build-test-results-tab&runId=8306036&resultId=103410)||
|[387729](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387729)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandler_RemoteServerTest.GetAsync_SetAutomaticDecompression_ContentDecompressed_Deflate](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387729&view=ms.vss-test-web.build-test-results-tab&runId=8305942&resultId=103223)||
|[387272](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387272)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ServerCertificates_Test.NoCallback_RevokedCertificate_NoRevocationChecking_Succeeds](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387272&view=ms.vss-test-web.build-test-results-tab&runId=8292608&resultId=103297)||
|[387273](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387273)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ServerCertificates_Test.NoCallback_RevokedCertificate_NoRevocationChecking_Succeeds](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387273&view=ms.vss-test-web.build-test-results-tab&runId=8292574&resultId=103060)||
|[386876](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386876)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386876&view=ms.vss-test-web.build-test-results-tab&runId=8277650&resultId=209600)|dotnet/runtime#91126|
|[386867](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386867)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandler_RemoteServerTest.GetAsync_SetAutomaticDecompression_ContentDecompressed_Deflate](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386867&view=ms.vss-test-web.build-test-results-tab&runId=8277696&resultId=103138)||
|[386871](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386871)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandler_RemoteServerTest.GetAsync_SetAutomaticDecompression_ContentDecompressed_Deflate](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386871&view=ms.vss-test-web.build-test-results-tab&runId=8277426&resultId=103210)||
|[386600](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386600)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_IdleConnectionTimeoutExpired_ConnectionRemovedAndNewCreated_3](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386600&view=ms.vss-test-web.build-test-results-tab&runId=8267674&resultId=209125)|dotnet/runtime#91126|
|[386209](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386209)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_OpenAndCloseMultipleConnections_Success_9](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386209&view=ms.vss-test-web.build-test-results-tab&runId=8258474&resultId=208859)|dotnet/runtime#91126|
|[386034](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386034)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_OpenAndCloseMultipleConnections_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386034&view=ms.vss-test-web.build-test-results-tab&runId=8251984&resultId=208608)|dotnet/runtime#85392|
|[386015](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386015)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_OpenAndCloseMultipleConnections_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386015&view=ms.vss-test-web.build-test-results-tab&runId=8251522&resultId=208763)|dotnet/runtime#91116|
|[385965](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385965)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_OpenAndCloseMultipleConnections_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385965&view=ms.vss-test-web.build-test-results-tab&runId=8250680&resultId=208853)|dotnet/runtime#91112|
|[385885](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385885)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandler_RemoteServerTest.GetAsync_SetAutomaticDecompression_ContentDecompressed_Deflate](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385885&view=ms.vss-test-web.build-test-results-tab&runId=8248618&resultId=103337)||
|[385889](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385889)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandler_RemoteServerTest.GetAsync_SetAutomaticDecompression_ContentDecompressed_Deflate](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385889&view=ms.vss-test-web.build-test-results-tab&runId=8248268&resultId=103143)||
|[385886](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385886)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandler_RemoteServerTest.GetAsync_SetAutomaticDecompression_ContentDecompressed_Deflate](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385886&view=ms.vss-test-web.build-test-results-tab&runId=8247592&resultId=104195)||
|[385906](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385906)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_OpenAndCloseMultipleConnections_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385906&view=ms.vss-test-web.build-test-results-tab&runId=8247278&resultId=208675)|dotnet/runtime#90880|
|[385835](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385835)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_OpenAndCloseMultipleConnections_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385835&view=ms.vss-test-web.build-test-results-tab&runId=8245922&resultId=161078)||
|[385825](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385825)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_OpenAndCloseMultipleConnections_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385825&view=ms.vss-test-web.build-test-results-tab&runId=8245450&resultId=208715)|dotnet/runtime#91106|
|[385736](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385736)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_OpenAndCloseMultipleConnections_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385736&view=ms.vss-test-web.build-test-results-tab&runId=8241750&resultId=171815)|dotnet/runtime#90518|
|[385733](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385733)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_OpenAndCloseMultipleConnections_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385733&view=ms.vss-test-web.build-test-results-tab&runId=8241076&resultId=208798)|dotnet/runtime#90518|
|[385719](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385719)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_OpenAndCloseMultipleConnections_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385719&view=ms.vss-test-web.build-test-results-tab&runId=8240540&resultId=209229)|dotnet/runtime#91106|
|[385649](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385649)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_OpenAndCloseMultipleConnections_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385649&view=ms.vss-test-web.build-test-results-tab&runId=8238342&resultId=208678)|dotnet/runtime#91101|
|[385559](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385559)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_OpenAndCloseMultipleConnections_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385559&view=ms.vss-test-web.build-test-results-tab&runId=8236480&resultId=208555)|dotnet/runtime#90970|
|[385396](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385396)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_OpenAndCloseMultipleConnections_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385396&view=ms.vss-test-web.build-test-results-tab&runId=8232050&resultId=208515)|dotnet/runtime#91092|
|[385375](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385375)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_OpenAndCloseMultipleConnections_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385375&view=ms.vss-test-web.build-test-results-tab&runId=8231312&resultId=208628)|dotnet/runtime#91074|
|[385364](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385364)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_OpenAndCloseMultipleConnections_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385364&view=ms.vss-test-web.build-test-results-tab&runId=8230334&resultId=170246)||
|[385334](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385334)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_OpenAndCloseMultipleConnections_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385334&view=ms.vss-test-web.build-test-results-tab&runId=8229784&resultId=208689)|dotnet/runtime#91094|
|[385321](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385321)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_OpenAndCloseMultipleConnections_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385321&view=ms.vss-test-web.build-test-results-tab&runId=8229620&resultId=208848)|dotnet/runtime#90551|
|[385283](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385283)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_OpenAndCloseMultipleConnections_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385283&view=ms.vss-test-web.build-test-results-tab&runId=8226980&resultId=204586)||
|[385005](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385005)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_OpenAndCloseMultipleConnections_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385005&view=ms.vss-test-web.build-test-results-tab&runId=8222990&resultId=208557)|dotnet/runtime#89102|
|[384637](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384637)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandler_RemoteServerTest.GetAsync_SetAutomaticDecompression_ContentDecompressed_Deflate](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384637&view=ms.vss-test-web.build-test-results-tab&runId=8212894&resultId=103682)||
|[384505](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384505)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_OpenAndCloseMultipleConnections_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384505&view=ms.vss-test-web.build-test-results-tab&runId=8207616&resultId=202716)|dotnet/runtime#91019|
|[384350](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384350)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpMetricsTest_Http30.RequestDuration_EnrichmentHandler_Success_Recorded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384350&view=ms.vss-test-web.build-test-results-tab&runId=8202678&resultId=209200)|dotnet/runtime#90518|
|[381149](https://dev.azure.com/dnceng-public/public/_build/results?buildId=381149)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_OpenAndCloseMultipleConnections_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=381149&view=ms.vss-test-web.build-test-results-tab&runId=8127526&resultId=208577)|dotnet/runtime#86194|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|3|42|43|

**Comment by karelz** [comment]
@MihaZupan I assume we should backport it to 8.0 once we have confidence it addresses the test problem in main. How long should we observe based on past occurrence frequency?

**Comment by MihaZupan** [comment]
Looks like it only failed once on 8.0 branches, otherwise, it's passing on rerun.
I'd give it a week to be sure it's fully resolved.
