### ISSUE TITLE
Improvements to NativeAOT compilation via meta-data

### ISSUE THREAD

**Issue by ShalokShalom** [dotnet/runtime#91113]
I just stumbled over this, and wonder if we could use something similar to overcome our issues with reflection heavy code. 

Please just close this, if I failed to find the mirroring implementation of this idea in .Net. 

https://github.com/oracle/graalvm-reachability-metadata

**Comment by ShalokShalom** [comment]
I am a bit confused. How does fixing static analysis warnings make reflection work in AOT executables?

**Comment by Suchiman** [comment]
For example, if you do, `typeof(MyObject).GetProperties()` then `GetProperties` is annotated as `[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicProperties)]` which tells the compiler that all public properties on `MyObject` are dynamically accessed and must be preserved / compiled. Now this is the easy case and the compiler can clearly see what's going on and make it work. If you now have more complicated code, like so
```csharp
internal class Program
{
    static void Main(string[] args)
    {
        Test(typeof(Program));
    }

    static void Test(Type t)
    {
        t.GetProperties();
    }
}
```
then the compiler will warn that
```
Program.cs(10,9,10,26): warning IL2070: 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicProperties' in call to 'System.Type.GetProperties()'. The parameter 't' of method 'Program.Test(Type)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
```
meaning that the indirection that we've caused here makes it impossible for the compiler to detect that it is the Program type for which all public properties need to be preserved. However, the static analysis catches that and suggests that we add annotations.
```csharp
using System.Diagnostics.CodeAnalysis;

internal class Program
{
    static void Main(string[] args)
    {
        Test(typeof(Program));
    }

    static void Test([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicProperties)] Type t)
    {
        t.GetProperties();
    }
}
```
Now the warning goes away and the compiler is once again able to reason that whatever type is passed to the Test method must have all of its public properties preserved.

**Comment by ShalokShalom** [comment]
Does this also work for FSharp?
