### ISSUE TITLE
LoggerMessage source generator does not work with logger from primary constructor.

### ISSUE THREAD

**Issue by stmimon** [dotnet/runtime#91121]
### Description

The source generator for `LoggerMessage` does not work if the logger is injected from the primary constructor.

### Reproduction Steps

Create the project.

* `dotnet new classlib`
* `dotnet add package Microsoft.Extensions.Logging --version 8.0.0-preview.7.23375.6`

Add the following c# file to the project.

```cs
using Microsoft.Extensions.Logging;

namespace Test;

public partial class LoggerFromPrimaryConstructor(ILogger<LoggerFromPrimaryConstructor> logger)
{
    [LoggerMessage(Level = LogLevel.Debug, Message = "This is a test")]
    public partial void LogTest();
}
```

### Expected behavior

The source generator emits code with similar behaviour as if I had written the following.
```cs
public partial class LogWithExplicitProperty
{
    private readonly ILogger<LoggerFromPrimaryConstructor> logger;

    public LogWithExplicitProperty(ILogger<LoggerFromPrimaryConstructor> logger)
    {
        this.logger = logger;
    }

    [LoggerMessage(Level = LogLevel.Debug, Message = "This is a test")]
    public partial void LogTest();
}
```

### Actual behavior

Compilation fails with `error SYSLIB1019: Couldn't find a field of type Microsoft.Extensions.Logging.ILogger in class LoggerFromPrimaryConstructor`.

I also got `error CS1525: Invalid expression term '<'` in another project where the source generator did find the logger for some reason, but generated incorrect code that referenced the logger by the symbol `<logger>P`. I assume this is the generated field name? I could not reproduce it however.

### Regression?

This is not a regression, as primary constructors are not GA.

### Known Workarounds

Use a regular constructor instead of a primary constructor.

### Configuration

I am using .NET 8 preview 7 on Windows 10 Enterprise 22H2 x64.

**Comment by tarekgh** [comment]
Yes, the primary constructors feature is a new compiler feature and is not supported yet with the logging source gen. This is something we can consider supporting in future releases. Thanks for your report. 

CC @geeknoid

**Comment by sloncho** [comment]
@tarekgh 8.0 is now GA and long-term support. Fixing this for 9.0 will leave more than 2 years with unsupported code.

**Comment by tarekgh** [comment]
@sloncho we usually get issues after facts which we address it in the next releases. If we find demands on specific issue, we consider porting the fix back to the service release.

**Comment by stmimon** [comment]
@sloncho If you want to use a primary constructor, another workaround is to explicitly pass the logger instance to the logging methods.
```csharp
[LoggerMessage(Level = LogLevel.Debug, Message = "This is a test")]
public partial void LogTest(ILogger logger);
```

**Comment by timia2109** [comment]
Or you could do something like this: 
```csharp
public partial class Foo(ILogger<Foo> logger) {
    private readonly ILogger _logger = logger;
}
```
