### ISSUE TITLE
[8.0] [wasm] WorkloadNotRequiredForInvariantGlobalization timeout waiting for web server url

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#91143]
### Error Blob

Tagging this for KnownBuildError in case it's happening consistently and we need to fix this in 8.0.

### Reproduction Steps

- Affected PR: https://github.com/dotnet/runtime/pull/91114
- Queue: `browser-wasm linux Release WasmBuildTests`
- Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=421412&view=results
- Log: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-heads-release-80-61236660d11846b789/Workloads-Wasm.Build.Tests.TestAppScenarios.LibraryInitializerTests/1/console.33f2fb09.log?helixlogtype=result
- Output:
```
    Wasm.Build.Tests.Blazor.WorkloadRequiredTests.WorkloadNotRequiredForInvariantGlobalization(config: "Debug", invariant: True, publish: False) [FAIL]
      System.Exception : Timed out waiting for the web server url
      Stack Trace:
        /_/src/mono/wasm/Wasm.Build.Tests/BrowserRunner.cs(86,0): at Wasm.Build.Tests.BrowserRunner.RunAsync(ToolCommand cmd, String args, Boolean headless, Action`1 onConsoleMessage, Action`1 onError, Func`2 modifyBrowserUrl)
        /_/src/mono/wasm/Wasm.Build.Tests/Blazor/BlazorWasmTestBase.cs(190,0): at Wasm.Build.Tests.BlazorWasmTestBase.BlazorRunTest(String runArgs, String workingDirectory, BlazorRunOptions runOptions)
        /_/src/mono/wasm/Wasm.Build.Tests/Blazor/BlazorWasmTestBase.cs(210,0): at Wasm.Build.Tests.BlazorWasmTestBase.BlazorRunTest(String runArgs, String workingDirectory, BlazorRunOptions runOptions)
        /_/src/mono/wasm/Wasm.Build.Tests/Blazor/WorkloadRequiredTests.cs(120,0): at Wasm.Build.Tests.Blazor.WorkloadRequiredTests.WorkloadNotRequiredForInvariantGlobalization(String config, Boolean invariant, Boolean publish)
        --- End of stack trace from previous location ---
      Output:
        [] Executing (Captured Output) - /root/helix/work/workitem/e/dotnet-none/dotnet new blazorwasm  -  in pwd /root/helix/work/workitem/e/wbt/props_req_workload_build_de5ndmlg_kcp
        [] The template "Blazor WebAssembly App" was created successfully.
        [] This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore/8.0-third-party-notices for details.
        [] 
        [] Processing post-creation actions...
        [] Restoring /root/helix/work/workitem/e/wbt/props_req_workload_build_de5ndmlg_kcp/props_req_workload_build_de5ndmlg_kcp.csproj:
        []   Determining projects to restore...
        []   Restored /root/helix/work/workitem/e/wbt/props_req_workload_build_de5ndmlg_kcp/props_req_workload_build_de5ndmlg_kcp.csproj (in 6.98 sec).
        [] Restore succeeded.
        [] 
        [] 
        Updated counter.razor: @page "/counter"
        
        <PageTitle>Counter</PageTitle>
        
        <h1>Counter</h1>
        
        <p role="status">Current count: @currentCount</p>
        
        <button class="btn btn-primary" @onclick="IncrementCount">Click me</button>
        
        @code {
            private int currentCount = 0;
        
            private void IncrementCount()
            {
                currentCount++;
        TestInvariantCulture();
            }
        }
        @code {
            public int TestInvariantCulture()
            {
                // https://github.com/dotnet/runtime/blob/main/docs/design/features/globalization-invariant-mode.md#cultures-and-culture-data
                try
                {
                    System.Globalization.CultureInfo culture = new ("es-ES", false);
                    System.Console.WriteLine($"es-ES: Is-LCID-InvariantCulture: {culture.LCID == System.Globalization.CultureInfo.InvariantCulture.LCID}, NativeName: {culture.NativeName}");
                }
                catch (System.Globalization.CultureNotFoundException cnfe)
                {
                    System.Console.WriteLine($"Could not create es-ES culture: {cnfe.Message}");
                }
        
                System.Console.WriteLine($"CurrentCulture.NativeName: {System.Globalization.CultureInfo.CurrentCulture.NativeName}");
                return 42;
            }
        }
        
        ** -------- build -------- **
        
        Binlog path: /root/helix/work/workitem/uploads/xharness-output/logs/props_req_workload_build_de5ndmlg_kcp/props_req_workload_build_de5ndmlg_kcp-build.binlog
        [] Executing (Captured Output) - /root/helix/work/workitem/e/dotnet-none/dotnet build -bl:/root/helix/work/workitem/uploads/xharness-output/logs/props_req_workload_build_de5ndmlg_kcp/props_req_workload_build_de5ndmlg_kcp-build.binlog -p:Configuration=Debug -nr:false /warnaserror -p:BlazorEnableCompression=false   -  in pwd /root/helix/work/workitem/e/wbt/props_req_workload_build_de5ndmlg_kcp
        	[DOTNET_ROOT] = /root/helix/work/workitem/e/dotnet-none
        	[DOTNET_INSTALL_DIR] = /root/helix/work/workitem/e/dotnet-none
        	[DOTNET_MULTILEVEL_LOOKUP] = 0
        	[DOTNET_SKIP_FIRST_TIME_EXPERIENCE] = 1
        	[PATH] = /root/helix/work/workitem/e/dotnet-none:./dotnet-none:/__w/1/s/artifacts/bin/chromedriver/chromedriver_linux64:/root/helix/work/correlation/dotnet-none:/root/helix/work/correlation/xharness-cli:/root/helix/work/correlation/dotnet-cli:/root/helix/work/correlation/chrome-linux:/root/helix/work/correlation/chromedriver_linux64:/home/helixbot/.jsvu/bin:/home/helixbot/node-v16.19.0-linux-x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        	[EM_WORKAROUND_PYTHON_BUG_34780] = 1
        	[NUGET_PACKAGES] = /root/helix/work/workitem/e/wbt/nuget/props_req_workload_build_de5ndmlg_kcp
        [] MSBuild version 17.7.0+5785ed5c2 for .NET
        []   Determining projects to restore...
        []   Restored /root/helix/work/workitem/e/wbt/props_req_workload_build_de5ndmlg_kcp/props_req_workload_build_de5ndmlg_kcp.csproj (in 3.83 sec).
        [] /root/helix/work/workitem/e/dotnet-none/sdk/8.0.100-rc.1.23415.5/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(311,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/root/helix/work/workitem/e/wbt/props_req_workload_build_de5ndmlg_kcp/props_req_workload_build_de5ndmlg_kcp.csproj]
        []   props_req_workload_build_de5ndmlg_kcp -> /root/helix/work/workitem/e/wbt/props_req_workload_build_de5ndmlg_kcp/bin/Debug/net8.0/props_req_workload_build_de5ndmlg_kcp.dll
        []   props_req_workload_build_de5ndmlg_kcp (Blazor output) -> /root/helix/work/workitem/e/wbt/props_req_workload_build_de5ndmlg_kcp/bin/Debug/net8.0/wwwroot
        []   ** MicrosoftNetCoreAppRuntimePackDir : '/root/helix/work/workitem/e/wbt/nuget/props_req_workload_build_de5ndmlg_kcp/microsoft.netcore.app.runtime.mono.browser-wasm/8.0.0-ci'
        [] 
        [] Build succeeded.
        []     0 Warning(s)
        []     0 Error(s)
        [] 
        [] Time Elapsed 00:00:17.67
        [] Executing - /root/helix/work/workitem/e/dotnet-none/dotnet run -c Debug --no-build  in pwd /root/helix/work/workitem/e/wbt/props_req_workload_build_de5ndmlg_kcp
        	[DOTNET_ROOT] = /root/helix/work/workitem/e/dotnet-none
        	[DOTNET_INSTALL_DIR] = /root/helix/work/workitem/e/dotnet-none
        	[DOTNET_MULTILEVEL_LOOKUP] = 0
        	[DOTNET_SKIP_FIRST_TIME_EXPERIENCE] = 1
        	[PATH] = /root/helix/work/workitem/e/dotnet-none:./dotnet-none:/__w/1/s/artifacts/bin/chromedriver/chromedriver_linux64:/root/helix/work/correlation/dotnet-none:/root/helix/work/correlation/xharness-cli:/root/helix/work/correlation/dotnet-cli:/root/helix/work/correlation/chrome-linux:/root/helix/work/correlation/chromedriver_linux64:/home/helixbot/.jsvu/bin:/home/helixbot/node-v16.19.0-linux-x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        	[EM_WORKAROUND_PYTHON_BUG_34780] = 1
        [] fail: Microsoft.Extensions.Hosting.Internal.Host[11]
        []       Hosting failed to start
        []       System.IO.IOException: Failed to bind to address http://127.0.0.1:5175: address already in use.
        []        ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
        []        ---> System.Net.Sockets.SocketException (98): Address already in use
        []          at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
        []          at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
        []          at System.Net.Sockets.Socket.Bind(EndPoint localEP)
        []          at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
        []          at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
        []          --- End of inner exception stack trace ---
        []          at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
        []          at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
        []          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
        []          at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass28_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
        []       --- End of stack trace from previous location ---
        []          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
        []          --- End of inner exception stack trace ---
        []          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
        []          at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
        []          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
        []          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(ListenOptions[] listenOptions, AddressBindContext context, Func`2 useHttps, CancellationToken cancellationToken)
        []          at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
        []          at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
        []          at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
        []          at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
        []          at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
        [] Unhandled exception. System.IO.IOException: Failed to bind to address http://127.0.0.1:5175: address already in use.
        []  ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
        []  ---> System.Net.Sockets.SocketException (98): Address already in use
        []    at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
        []    at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
        []    at System.Net.Sockets.Socket.Bind(EndPoint localEP)
        []    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
        []    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
        []    --- End of inner exception stack trace ---
        []    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
        []    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
        []    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
        []    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass28_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
        [] --- End of stack trace from previous location ---
        []    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
        []    --- End of inner exception stack trace ---
        []    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
        []    at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
        []    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
        []    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(ListenOptions[] listenOptions, AddressBindContext context, Func`2 useHttps, CancellationToken cancellationToken)
        []    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
        []    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
        []    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
        []    at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
        []    at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
        []    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
        []    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
        []    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
        []    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
        []    at Microsoft.AspNetCore.Components.WebAssembly.DevServer.Program.Main(String[] args)
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=421412&view=results
**Error message validated:** `System.IO.IOException: Failed to bind to address http://127.0.0.1:5000`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 10/2/2023 9:30:07 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[425414](https://dev.azure.com/dnceng-public/public/_build/results?buildId=425414)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.LibraryInitializerTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=425414&view=ms.vss-test-web.build-test-results-tab&runId=9363204&resultId=100148)|dotnet/runtime#92637|
|[425025](https://dev.azure.com/dnceng-public/public/_build/results?buildId=425025)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.LibraryInitializerTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=425025&view=ms.vss-test-web.build-test-results-tab&runId=9351720&resultId=100148)|dotnet/runtime#92904|
|[425004](https://dev.azure.com/dnceng-public/public/_build/results?buildId=425004)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.AppSettingsTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=425004&view=ms.vss-test-web.build-test-results-tab&runId=9351100&resultId=100147)|dotnet/runtime#92503|
|[423529](https://dev.azure.com/dnceng-public/public/_build/results?buildId=423529)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.DownloadResourceProgressTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=423529&view=ms.vss-test-web.build-test-results-tab&runId=9309474&resultId=100148)||
|[422409](https://dev.azure.com/dnceng-public/public/_build/results?buildId=422409)|dotnet/runtime|[Wasm.Build.Tests.Blazor.WorkloadRequiredTests.WorkloadNotRequiredForInvariantGlobalization](https://dev.azure.com/dnceng-public/public/_build/results?buildId=422409&view=ms.vss-test-web.build-test-results-tab&runId=9283596&resultId=100001)|dotnet/runtime#91633|
|[421412](https://dev.azure.com/dnceng-public/public/_build/results?buildId=421412)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.LibraryInitializerTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=421412&view=ms.vss-test-web.build-test-results-tab&runId=9255712&resultId=100147)||
|[421371](https://dev.azure.com/dnceng-public/public/_build/results?buildId=421371)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.LibraryInitializerTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=421371&view=ms.vss-test-web.build-test-results-tab&runId=9254798&resultId=100147)|dotnet/runtime#92745|
|[421097](https://dev.azure.com/dnceng-public/public/_build/results?buildId=421097)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.LazyLoadingTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=421097&view=ms.vss-test-web.build-test-results-tab&runId=9247834&resultId=100147)|dotnet/runtime#92702|
|[420785](https://dev.azure.com/dnceng-public/public/_build/results?buildId=420785)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.DownloadResourceProgressTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=420785&view=ms.vss-test-web.build-test-results-tab&runId=9240724&resultId=100148)|dotnet/runtime#88479|
|[417062](https://dev.azure.com/dnceng-public/public/_build/results?buildId=417062)|dotnet/runtime|[Wasm.Build.Tests.Blazor.BuildPublishTests.DefaultTemplate_WithoutWorkload](https://dev.azure.com/dnceng-public/public/_build/results?buildId=417062&view=ms.vss-test-web.build-test-results-tab&runId=9132228&resultId=100007)|dotnet/runtime#92489|
|[416040](https://dev.azure.com/dnceng-public/public/_build/results?buildId=416040)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.LazyLoadingTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=416040&view=ms.vss-test-web.build-test-results-tab&runId=9099154&resultId=100148)|dotnet/runtime#92406|
|[414888](https://dev.azure.com/dnceng-public/public/_build/results?buildId=414888)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.Blazor.IcuTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=414888&view=ms.vss-test-web.build-test-results-tab&runId=9062714&resultId=100147)||
|[414729](https://dev.azure.com/dnceng-public/public/_build/results?buildId=414729)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.AppSettingsTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=414729&view=ms.vss-test-web.build-test-results-tab&runId=9059192&resultId=100147)|dotnet/runtime#92401|
|[414506](https://dev.azure.com/dnceng-public/public/_build/results?buildId=414506)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.LibraryInitializerTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=414506&view=ms.vss-test-web.build-test-results-tab&runId=9050196&resultId=100148)|dotnet/runtime#92280|
|[413445](https://dev.azure.com/dnceng-public/public/_build/results?buildId=413445)|dotnet/runtime|[Wasm.Build.Tests.Blazor.WorkloadRequiredTests.WorkloadNotRequiredForInvariantGlobalization](https://dev.azure.com/dnceng-public/public/_build/results?buildId=413445&view=ms.vss-test-web.build-test-results-tab&runId=9023946&resultId=100004)||
|[411591](https://dev.azure.com/dnceng-public/public/_build/results?buildId=411591)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.DownloadResourceProgressTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=411591&view=ms.vss-test-web.build-test-results-tab&runId=8962884&resultId=100147)|dotnet/runtime#92277|
|[411449](https://dev.azure.com/dnceng-public/public/_build/results?buildId=411449)|dotnet/runtime|[Wasm.Build.Tests.Blazor.BuildPublishTests.DefaultTemplate_WithoutWorkload](https://dev.azure.com/dnceng-public/public/_build/results?buildId=411449&view=ms.vss-test-web.build-test-results-tab&runId=8957732&resultId=100007)|dotnet/runtime#92057|
|[408123](https://dev.azure.com/dnceng-public/public/_build/results?buildId=408123)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.WasmTemplateTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=408123&view=ms.vss-test-web.build-test-results-tab&runId=8860888&resultId=100147)|dotnet/runtime#92143|
|[404027](https://dev.azure.com/dnceng-public/public/_build/results?buildId=404027)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.DownloadResourceProgressTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=404027&view=ms.vss-test-web.build-test-results-tab&runId=8752402&resultId=100147)|dotnet/runtime#91913|
|[400499](https://dev.azure.com/dnceng-public/public/_build/results?buildId=400499)|dotnet/runtime|[Wasm.Build.Tests.TestAppScenarios.LazyLoadingTests.LoadLazyAssemblyBeforeItIsNeeded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=400499&view=ms.vss-test-web.build-test-results-tab&runId=8649518&resultId=100021)|dotnet/runtime#91482|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|4|20|

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "BuildRetry": false,
  "ErrorPattern": "System.IO.IOException: Failed to bind to address http://127.0.0.1:5000",
  "ExcludeConsoleLog": false
}
```

**Comment by SamMonoRT** [comment]
Assigning to a few folks due to vacations etc.

**Comment by maraf** [comment]
```
        []       Hosting failed to start
        []       System.IO.IOException: Failed to bind to address http://127.0.0.1:5175: address already in use.
```

Randomly picked port number collided with other test?

**Comment by lewing** [comment]
@agocke how do we get errors like this to match so that build analysis will be green?

**Comment by pavelsavara** [comment]
@radical do you remember any details of random port allocation ? could you please take over this ?

**Comment by radical** [comment]
> @agocke how do we get errors like this to match so that build analysis will be green?

It was using an old build that already expired. I updated the url to a new one, and it matches now.

**Comment by radical** [comment]
There are two different issues here:
1. failing tests with port `5000`, this is for `wasmbrowser` template apps
2. Blazor tests failing with the same error but for randomly picked ports (split this into https://github.com/dotnet/runtime/issues/92910)

**Comment by radical** [comment]
> There are two different issues here:
> 
> 1. failing tests with port `5000`, this is for `wasmbrowser` template apps
> 2. Blazor tests failing with the same error but for randomly picked ports (split this into [[wasm] WBT: Blazor tests on windows failing with `Failed to bind to address` for random ports #92910](https://github.com/dotnet/runtime/issues/92910))

(1) has been fixed by https://github.com/dotnet/runtime/pull/92906 . Closing this, as the remaining has been split off as a separate issue.
