### ISSUE TITLE
NativeAot reverse engineering capabilities compared to c/c++

### ISSUE THREAD

**Issue by NCLnclNCL** [dotnet/runtime#91157]
apart from metadata for mirroring, can it reverse engine like java's native graalvm ??

**Comment by jkotas** [comment]
The difficulty of reverse engineering is not something that we consider for native AOT designs.

Any binary can be reverse engineered. The effort required to reverse engineer a binary depends (among other things) on the sophistication of the reverse engineering tools that you use.
