### ISSUE TITLE
Class serialized to an empty array [] with System.Text.Json

### ISSUE THREAD

**Issue by TsengSR** [dotnet/runtime#91155]
### Description

This week I encountered a weird behavior of the System.Json.Text library which took me hours to work around with and find the original issue.

When I serialize a specific object, I would always get `[]` as a result, despite it being a single object and not an empty array and no exception being thrown either.

### Reproduction Steps

This is the simplified example of my use case

```csharp
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;

#nullable enable
public class Program
{
    public static void Main()
    {
        var json = JsonSerializer.Serialize<SampleModel2>(new SampleModel2
        {
            StringValue = "A String",
            DoubleValue = 10.10,
            IntValue = 10
        });
        var json2 = JsonSerializer.Serialize<SampleModel>(new SampleModel
        {
            StringValue = "A String",
            DoubleValue = 10.10,
            IntValue = 10
        });
        Console.WriteLine("Json: " + json);
        Console.WriteLine("Json 2: " + json2);
        // Output: 
        // Json: {"StringValue":"A String","DoubleValue":10.1,"IntValue":10}
        // Json 2: []
    }
	
    public class SampleModel2
    {
        public string StringValue { get; set; } = string.Empty;
        public double DoubleValue { get; set; }
        public int IntValue  { get; set; }
    }

    public class SampleModel : ValidationResultBase
    {
        public string StringValue { get; set; } = string.Empty;
		public double DoubleValue { get; set; }
        public int IntValue { get; set; }
    }

    public class ValidationResultBase : ICollection<ValidationResult>
    {
        private readonly List<ValidationResult> validationResults = new();
        public bool IsValid => Validate();
        protected virtual bool Validate() => !Validations.Any();
        public List<ValidationResult> Validations => validationResults;
        int ICollection<ValidationResult>.Count => validationResults.Count;
        bool ICollection<ValidationResult>.IsReadOnly => true;

        public void AddValidatorResult(string errorCode, string message, string? property = null)
        {
            validationResults.Add(new()
            {
                Code = errorCode,
                Message = message,
                PropertyName = property
            });
        }

        public void Add(ValidationResult item) => validationResults.Add(item);
        void ICollection<ValidationResult>.Clear() => throw new System.NotImplementedException();
        bool ICollection<ValidationResult>.Contains(ValidationResult item) => validationResults.Contains(item);
        void ICollection<ValidationResult>.CopyTo(ValidationResult[] array, int arrayIndex) => validationResults.CopyTo(array, arrayIndex);
        bool ICollection<ValidationResult>.Remove(ValidationResult item) => throw new System.NotImplementedException();
        IEnumerator<ValidationResult> IEnumerable<ValidationResult>.GetEnumerator() => validationResults.GetEnumerator();
        IEnumerator IEnumerable.GetEnumerator() => validationResults.GetEnumerator();
    }

    public class ValidationResult
    {
        public string Code { get; set; } = string.Empty;
        public string? PropertyName { get; set; }
        public string Message { get; set; } = string.Empty;
    }
}
```
Gist: https://gist.github.com/TsengSR/fd97e02757ffefb43fbb7bd9f05d1c6a

### Expected behavior

I'd expect either both to serialize to the same output or at least throw an exception with the exact error.

### Actual behavior

Object serializes into `[]` with no exception, causing very hard to track errors since even unit tests pass with the wrong value when doing `sample2.ToJson().ShouldBe(expectedResult2.ToJson())`

### Regression?

I don't know. Appears in all version of System.Text.Json since 5.0.0 (6.0.0, 7.0.0, 8.0.0 preview builds).
Didn't test with older Runtimes. 

### Known Workarounds

Remove `ValidationBase` base class, but that's not a real workaround.

In my concrete case I was able to remove it since it was new code. but the initial idea of the `ValidationBase` class was to allow Initializer like syntax on the base class, i.e. 

```csharp
SampleModel sample = new()
{
   new ValidationResult() { Code = "SomethingSomething.NotFound", PropertyName = "StringValue", "String Value not found." },
   new ValidationResult() { Code = "SomethingSomething.OutOfRange", PropertyName = "IntValue", "IntValue must be positive." },
}
```

### Configuration

Which version of .NET is the code running on?
.NET 5.0.17, but also an newer versions tested (up to including .NET 8 Preview 3) on dotnet fiddle https://dotnetfiddle.net/hXqb1g

What OS and version, and what distro if applicable?
Windows 11 and Linux (Dockerimage based on aspnet 5.0-alpine)

What is the architecture (x64, x86, ARM, ARM64)?
x64

Do you know whether it is specific to that configuration?
It happens independent of architecture or configuration

**Comment by gregsdennis** [comment]
I think this is a by-design behavior. Types that implement `IEnumerable<T>` are considered arrays (unless they're string-keyed dictionaries).  As such, extra properties aren't serialized.

I think you're going to need a custom converter for this.

**Comment by layomia** [comment]
This is indeed by-design. The easiest way to achieve the desired behavior is to modify the contract of the type to be `JsonTypeInfoKind.Object` : https://learn.microsoft.com/dotnet/standard/serialization/system-text-json/custom-contracts#configurable-aspects/
