### ISSUE TITLE
Incorrect nullable annotation on Validator.TryValidateValue's `value`?

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#91162]
It's defined like:
```C#
public static bool TryValidateValue(object value, ValidationContext validationContext, ICollection<ValidationResult>? validationResults, IEnumerable<ValidationAttribute> validationAttributes)
```
and the XML doc comment states:
```C#
/// <param name="value">The value to test.  It cannot be null.</param>
```
However, the implementation appears to permit null (the only place it's used is being passed to an `object?` argument in a helper method), the purpose of an attribute like `[Required]` is to validate one isn't null (which suggests null could otherwise be valid, and the new .NET 8 source generator for options is having to emit code like:
```C#
if (!global::System.ComponentModel.DataAnnotations.Validator.TryValidateValue(options.Path!, context, validationResults, validationAttributes))
{
    builder.AddResults(validationResults);
}
```
(note the `!` on the first argument) because the input might be null but the method is defined to not accept null.

cc: @jeffhandley, @eiriktsarpalis

**Comment by jeffhandley** [comment]
I tried doing some archaeology to figure out where the mismatch between the comment and the behavior came from, but I came up empty-handed.
