### ISSUE TITLE
GetRuntimeDirectory for WindowsDesktop apps

### ISSUE THREAD

**Issue by bstordrup** [dotnet/runtime#91182]
If I need to get information about the runtime directory for a netcore library like System.dll, I can use the RuntimeEnvironment.GetRuntimeDirectory.

But how do I get information about the runtime directory for a WindowsDesktop library like System.Windows.Forms.dll? Seems like the RuntimeEnvironmnet is missing functionality for this.

**Comment by huoyaoyuan** [comment]
The whole `RuntimeEnvironment` type is not updated with modern .NET concepts (https://github.com/dotnet/runtime/issues/87908#issuecomment-1602545180). The actual file layout can also change depending on deployment model, including framework-dependent, self-contained and single-file. With single-file deployment, there's no such directory at all.

**Comment by bstordrup** [comment]
I'm trying to generate code runtime, and the code needs references to System.Windows.Forms.dll, but that does not reside in the directory being returned from GetRuntimeDirectory. In order to make a reference using the Roslyn compilation object, I need the directory for Windows Desktop runtime.

**Comment by jkotas** [comment]
`Assembly.Load("System.Windows.Forms").Location` will give you the filename for `System.Windows.Forms` implementation assembly. As @huoyaoyuan pointed out, the filename is not available for single-file deployments. 

Alternatively, you can use reference assemblies for this scenario. The reference assemblies for core runtime and WinForms+WPF are available in https://www.nuget.org/packages/Microsoft.NETCore.App.Ref and https://www.nuget.org/packages/Microsoft.WindowsDesktop.App.Ref packages. You can bundle the reference assemblies that you need with your app and pass their paths to Roslyn.

**Comment by bstordrup** [comment]
@jkotas, does the App.Ref packages come in versions supporting `netstandard2.0`?

**Comment by jkotas** [comment]
> does the App.Ref packages come in versions supporting netstandard2.0?

No. WinForms does not support netstandard2.0.

https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies.net462 has reference assemblies for .NET Framework.

**Comment by agocke** [comment]
> In order to make a reference using the Roslyn compilation object, I need the directory for Windows Desktop runtime.

Compiling against runtime assemblies (effectively, anything you get on disk at runtime) is not supported by Roslyn. You must compile against ref assemblies. That means that you have to either use the package @jkotas provided for compiling against .NET Framework, or the WindowsForms for .NET Core package at https://www.nuget.org/packages/Microsoft.WindowsDesktop.App.Ref
