### ISSUE TITLE
PeriodicTimer bug when cancelling with token

### ISSUE THREAD

**Issue by pedroveiga99** [dotnet/runtime#91204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In blazor, if I start a PeriodicTimer and cancel it when I dispose the component cancel the cancellation Token there is an error in the browser console but it cannot be catched in the component.

```
dotnet.7.0.10.wpkm25c5x9.js:5 Error: [MONO] * Assertion at /__w/1/s/src/mono/mono/metadata/class.c:2112, condition `<disabled>' not met

    at xe (dotnet.7.0.10.wpkm25c5x9.js:5:509)
    at Object.je (dotnet.7.0.10.wpkm25c5x9.js:5:792)
    at _mono_wasm_trace_logger (dotnet.7.0.10.wpkm25c5x9.js:14:104923)
    at 009931b2:0x9bf7
    at 009931b2:0xa5a2f
    at 009931b2:0x1c0001
    at 009931b2:0x1c0090
    at 009931b2:0x1c00d3
    at 009931b2:0x1c00a6
    at 009931b2:0x390d6
```

### Steps To Reproduce

I achieved to reproduce it in a [minimalistic project](https://github.com/pedroveiga99/NavigationBug). To reproduce the error run the solution and go to the navigation tab. 

When the page is initialized there is a loop that is started and every second appends the current time to an array. This loop needs to be stopped when exiting the page. This is done by passing a cancelation token to the WaitForNextTickAsync method and cancelling the token in the DisposeAsync method.

When clicking in the button it was expected that after 3s the user was redirected to the root page. 

Ps: I know that I use async methods that are not needed. This is a minimalistic project trying to mimic a much bigger project where I need to use async methods and, in order to mimic the best way possible, I maintained the methods async.

**Comment by pavelsavara** [comment]
I was able to reproduce it on Net7, but on Net8 this just works.

![image](https://github.com/dotnet/runtime/assets/271576/5d93efb5-059a-4ed2-ab8f-b8513fa57365)

**Comment by pavelsavara** [comment]
https://github.com/dotnet/runtime/blob/59a1e88eaa84c1d8d34862fcfc5339440d23cd48/src/mono/mono/metadata/class.c#L2112

**Comment by pavelsavara** [comment]
Interestingly this also works fine on Net7

```csharp
        _ = Task.Run(async () =>
        {
            do
            {
                await Task.Delay(1000);
                times = times.Append(DateTime.Now).ToArray();
                StateHasChanged();
            } while (!workersCancelationSource.IsCancellationRequested);
        });

```

**Comment by pedroveiga99** [comment]
You are right, it all works fine in net8. I didn't want to update already to net8, as this part of a big enterprise project, but now I have one more reason to do so.

> Interestingly this also works fine on Net7
> 
> ```cs
>         _ = Task.Run(async () =>
>         {
>             do
>             {
>                 await Task.Delay(1000);
>                 times = times.Append(DateTime.Now).ToArray();
>                 StateHasChanged();
>             } while (!workersCancelationSource.IsCancellationRequested);
>         });
> ```

Yes, this solution will also work but, in my case at least, it has downside. I know that in my minimalist repo it does not work that way, but in the real project the method inside the loop is async. So the times will be a bit off.

```
Ticks  *_________*_________*_________*_________*_________*_________*
Mine   *---*_____*-----*___*------------**--*__*---*_____*
Yours  *---*_________*-----*_________*------------*_________*
```

The workaround I'm using (until I upgrade to net8) is this 


```
  PeriodicTimer _timer = new(TimeSpan.FromSeconds(fullStatusUpdateInterval));
  do
  {
      try
      {
          await SomeAsyncMethod();
      }
      catch (Exception ex)
      {
          // Exception Logic
      }

      await _timer.WaitForNextTickAsync();
  } while (!workersCancelationSource.Token.IsCancellationRequested);
```
