### ISSUE TITLE
Add DebuggerTypeProxy for ListDictionaryInternal

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#91254]
[This PR](https://github.com/dotnet/runtime/pull/91224) added debugger display to `ListDictionaryInternal`. A DebuggerTypeProxy should also be added to improve displaying the collection's contents.

The current display in VS:
![image](https://github.com/dotnet/runtime/assets/303201/eab047b4-2920-4354-80ce-378093deb5a6)

For example: https://github.com/dotnet/runtime/blob/86252f7b723eeae2a827144ee9c15bc675028ad8/src/libraries/System.Private.CoreLib/src/System/Collections/ArrayList.cs#L2640-L2653

**Comment by arturek** [comment]
@tarekgh yes, thanks. I wrote the code, but I cannot find ListDictionaryInternal's unit tests.

**Comment by tarekgh** [comment]
@arturek ListDictionaryInternal is an internal thingy, so I don't think we have unit tests for it. Can't you test it through the Exception class? or add new tests for it if needed.
