### ISSUE TITLE
Config binding gen omits a needed comma in an emitted Configure overload replacement

### ISSUE THREAD

**Issue by martincostello** [dotnet/runtime#91258]
### Description

Updating to .NET SDK `8.0.100-rc.2.23428.11` from `8.0.100-rc.2.23427.4` introduces [compilation errors](https://github.com/martincostello/costellobot/actions/runs/6010809962/job/16303508696?pr=821#step:9:87) in the configuration binding source generator:

```
Error: /home/runner/work/costellobot/costellobot/src/Costellobot/Microsoft.Extensions.Configuration.Binder.SourceGeneration/Microsoft.Extensions.Configuration.Binder.SourceGeneration.ConfigurationBindingGenerator/BindingExtensions.g.cs(59,227): error CS1003: Syntax error, ',' expected [/home/runner/work/costellobot/costellobot/src/Costellobot/Costellobot.csproj]
Error: /home/runner/work/costellobot/costellobot/src/Costellobot/Microsoft.Extensions.Configuration.Binder.SourceGeneration/Microsoft.Extensions.Configuration.Binder.SourceGeneration.ConfigurationBindingGenerator/BindingExtensions.g.cs(58,35): error CS0246: The type or namespace name 'IOptionsChangeTokenSource<>' could not be found (are you missing a using directive or an assembly reference?) [/home/runner/work/costellobot/costellobot/src/Costellobot/Costellobot.csproj]
Error: /home/runner/work/costellobot/costellobot/src/Costellobot/Microsoft.Extensions.Configuration.Binder.SourceGeneration/Microsoft.Extensions.Configuration.Binder.SourceGeneration.ConfigurationBindingGenerator/BindingExtensions.g.cs(58,76): error CS0246: The type or namespace name 'ConfigurationChangeTokenSource<>' could not be found (are you missing a using directive or an assembly reference?) [/home/runner/work/costellobot/costellobot/src/Costellobot/Costellobot.csproj]
```

/cc @layomia

### Reproduction Steps

1. Clone https://github.com/martincostello/costellobot/commit/09ae9eab3d6780af4710b93051e6442f065b3c18.
2. Run `build.ps1` in the root of the repository.

### Expected behavior

The application compiles.

### Actual behavior

The application fails to compile with `CS1003` and `CS0246` errors.

### Regression?

Yes compared to recent preview builds.

### Known Workarounds

None.

### Configuration

.NET SDK `8.0.100-rc.2.23428.11`

**Comment by ShreyasJejurkar** [comment]
cc @layomia

**Comment by stephentoub** [comment]
Simple repro:
```C#
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

IServiceCollection services = null!;
IConfiguration configuration = null!;
services.Configure<MyOptions>(configuration.GetSection("repro"));

class MyOptions { }
```

**Comment by layomia** [comment]
Thanks folks. I [fixed](https://github.com/dotnet/runtime/pull/91180/files#diff-f121399b11b6b576d4842478ea52c76e9092085dc37e68dca3225009ff745579R63) this in https://github.com/dotnet/runtime/pull/91180, which introduced build coverage for all the options-binding-extension methods to prevent regressions.

@martincostello, please try the fix when you get a chance.

**Comment by layomia** [comment]
I ran into a different issue unrelated to this one when testing the fix on the `costellobot` project https://github.com/martincostello/costellobot/commit/09ae9eab3d6780af4710b93051e6442f065b3c18.

I'll share details shortly & will likely create a separate issue.

**Comment by layomia** [comment]
> I ran into a different issue unrelated to this one when testing the fix on the `costellobot` project [martincostello/costellobot@09ae9ea](https://github.com/martincostello/costellobot/commit/09ae9eab3d6780af4710b93051e6442f065b3c18).
> 
> I'll share details shortly & will likely create a separate issue.

Scratch this, all's well. I verified that the fix works in your project. Pls let us know if you still face issues here & I'll reopen the issue.

**Comment by layomia** [comment]
@martincostello thanks. That issue is fixed with https://github.com/dotnet/runtime/pull/91107. 

https://github.com/dotnet/runtime/issues/90851 describes it more, and this [LOC](https://github.com/martincostello/apple-fitness-workout-mapper/blob/4a1c6268b58ca95190a167dc834c461160dfba29/src/AppleFitnessWorkoutMapper/Program.cs#L45) is a sample test case. Workaround would be to move the `.Configure` call to the same LOC as `builder.Services`, but that won't be needed when the fix flows through.
