### ISSUE TITLE
File operations are not in case sensitive on cross-platform (i.e. Linux)

### ISSUE THREAD

**Issue by msx752** [dotnet/runtime#91250]
### Description
File operations on Linux are currently case-sensitive, contrary to the expected cross-platform behavior. While Windows OS maintains case sensitivity, the Linux file operations exhibit case-insensitive behavior for consistent user experience across platforms. Presently, methods like `File.Exists()` lack case sensitivity on Linux, which diverges from the anticipated behavior.

### Configuration
- **Linux Version:** Ubuntu 20.04
- **.NET Version:** .NET 7
- **Namespace:** System.IO
- **Namespace:** Microsoft.Extensions.FileProviders

### Other Information
- **Behavior Example:**
  - **Scenario:** Checking file existence using `File.Exists()`.
  - **Expected Result:** `File.Exists("myfile.txt")` should return `true` if `MyFile.txt` exists.
  - **Current Result:** `File.Exists("myfile.txt")` returns `false`, indicating a mismatch in case sensitivity.

- **PhyscalFileProvider.cs:**
  - The `PhyscalFileProvider.cs` class within the 'Microsoft.Extensions.FileProviders' namespace also exhibits case-sensitive behavior on Linux. This inconsistency affects the behavior of the `StaticFiles` functionality on website projects.

- **Reproduction Steps:**
  1. Create a file named `MyFile.txt` on Linux.
  2. Use the `File.Exists("myfile.txt")` method to check for its existence.
  3. Observe that the method incorrectly returns `false`.

- **Error Message:**
  - No specific error message is generated; the issue lies in the case-sensitive behavior of the file operations.

- **Workaround:**
  - As a workaround, developers can manually handle case-insensitive checks using custom code, but this complicates code maintenance and diminishes cross-platform uniformity.

This issue substantially impacts cross-platform development, leading to unexpected behavior for users working with files. Ensuring that file operations are consistently case-insensitive on Linux will significantly improve usability and maintain a seamless experience across different operating systems.

**Comment by tmds** [comment]
> Ensuring that file operations are consistently case-insensitive

It's not possible to make a case-sensitive system appear as case-sensitive. File entries can exists that differ only by case, and that makes it impossible to pick 'right' one.

In addition, a case-sensitive system doesn't have an efficient way to do a case-insensitive lookup, so there would be a significant performance cost to do this in user-space.

**Comment by adamsitnik** [comment]
As @tmds wrote, this is by design.

**Comment by msx752** [comment]
Linux doesn't care case sensitivity but File.Exist does which is not right for the cross-platforms, and there is no any choice to handling by framework at the moment.

 this is not right.

**Comment by Clockwork-Muse** [comment]
> File.Exist does which is not right for the cross-platforms

Why?  The majority of platforms are case-sensitive, which means that it's Windows that's "off" here (note that, among other things, Windows is gradually adopting ICU for cultural data, instead of their own sources).
Also, it's possible to create such differing-case files in Windows as well, at which point which one is opened is undefined.

**Comment by msx752** [comment]
I think File.Exists() should be in case sensitive on Linux, and case sensitive on Windows OS, It should be dependent on the OS. 

For example, Path.Combine() can behave differently depending on the operating system, so why not **File.Exists()** as well?

**that's my point, no body claims **Path.Combine** why different than Windows OS, because that is correct behavior for the Linux OS**

**Comment by adamsitnik** [comment]
For file operations, everything that .NET does is calling the right OS API (sys-call) with a file path or a file descriptior of an opened file. The sys-call internally calls the file system-specific code, which decides whether it's case sensitive or not. .NET has no control over how this is handled. There is also no alternative.

`Path.Combine` does not require touching the file system, so it's implemented in managed code.
