### ISSUE TITLE
JIT: automate release/check jit codegen comparison

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#9129]
We should be verifying that release and checked jits produce the same code.

Currently this requires some ad-hoc testing. We could leverage the information in the jit event stream to automate this. The current event stream includes a method length which can be used as a first indicator of diffs. It can miss detecting some kinds of diffs. but it should work out fairly well.

dotnet/runtime#9112 contains some ideas for enhancing this to include extra information to further refine detection of diffs.

category:correctness
theme:testing
skill-level:intermediate
cost:medium

**Comment by BruceForstall** [comment]
This was implemented with https://github.com/dotnet/runtime/pull/61335
