### ISSUE TITLE
[API Proposal]: Please reinstate CustomMarshalers.TypeToTypeInfoMarshaler for COM

### ISSUE THREAD

**Issue by mfeemster** [dotnet/runtime#91307]
### Background and motivation

The `TypeToTypeInfoMarshaler` marshaller made it very easy to get proper type information from the object that `__ComObject` wraps because it helped avoid the usual tedious boilerplate code required by COM.

This was covered in detail in this great Code Project article from 2013:
https://www.codeproject.com/Articles/523417/Reflection-with-IDispatch-based-COM-objects

Sadly, this was removed with the move to .NET Core. I've read on various tickets here that the COM code was needlessly stripped out. But when the .NET team realized that many people still relied on COM, they put some of it back in.

However, there appears to be some missing parts, such as this custom marshaller. Another very useful, but missing method I need is `Marshal.GetMethodInfoForComSlot()`.

I understand the aim is to be cross platform, but since there is already COM-related functionality still left in `Marshal`, it's clear that there can be some code that only runs on Windows, but is disabled elsewhere, within .NET.

I desperately need this functionality back, and also can't go back to .NET 4.8. So I think it would be a good idea to re-add it because COM has a 25+ year long history and isn't going away.

Thank you.

### API Proposal

```csharp
[MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef =
        typeof(System.Runtime.InteropServices.CustomMarshalers.TypeToTypeInfoMarshaler))]
```

### API Usage

```csharp
void GetTypeInfo(int typeInfoIndex, int lcid,
        [MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef =
        typeof(System.Runtime.InteropServices.CustomMarshalers.TypeToTypeInfoMarshaler))]
        out Type typeInfo);
```

### Alternative Designs

There are none, this relates specifically to missing COM interop functionality.

### Risks

None, this code already exists, it just needs to be merged back in.

**Comment by AaronRobinsonMSFT** [comment]
@mfeemster Thanks for the the suggestion. This API is about imbuing the built-in system will new functionality in .NET 8+. The interop team is not investing additional effort in the built-in COM interop system and so this work doesn't fit into any future facing plans. There is hope however with the [COM source generators](https://github.com/dotnet/runtime/issues/66674) that are NAOT friendly, trim safe and have better opportunities for performance improvements.

We will move this into future to continue to track this information.

**Comment by mfeemster** [comment]
The reason I made this ticket is because those methods I mentioned above work great for when a type is not known at compile time. For example, using `Activator.CreateInstance("sometypesuppliedatruntime")`. Perhaps I am not fully understanding the new way of doing things, but it appears that the source generators are for working with types that you know about at compile time?

If I am not wrong, then that means you are phasing out COM interop for types only known at runtime?

**Comment by AaronRobinsonMSFT** [comment]
> but it appears that the source generators are for working with types that you know about at compile time?

That is accurate. All potential types should be known. Activating an arbitrary COM type and using `IDispatch` to reflect over isn't something we are likely to invest any more time in. Outside of what can be achieved using `dynamic`.

> If I am not wrong, then that means you are phasing out COM interop for types only known at runtime?

The best way forward there would be to use the `dynamic` keyword for calling. For inspection, using .NET Reflection is another option, but only if the `IDispatch` type has already been projected into .NET by a PIA or another projection technology.

**Comment by mfeemster** [comment]
I'm a little disheartened , but if that's the way it has to go, then so be it.

I know this isn't Stackoverflow, but for my own knowing, and in the case someone else stumbles upon this from searching. Could you either explain or provide a brief example of the best way to reflect on a `__ComObject` to get its methods? You mentioned using `dynamic`, which I am fine with. But even using `dynamic` with `__ComObject `doesn't seem to get the methods of the underlying COM type. I hope I am just doing it wrong.

Thanks.

PS: If I may request it, I think it would be really beneficial to include this functionality in the new COM interop architecture you're currently developing, so we can easily reflect over COM types which are only known at runtime.

**Comment by AaronRobinsonMSFT** [comment]
> Could you either explain or provide a brief example of the best way to reflect on a __ComObject to get its methods?

That is a perfectly reasonable request and I think would make for a good sample. Coincidentally we are entering the part of the cycle where we focus on docs and samples. I will write one up. Thanks for the suggestion.

/cc @agocke @dotnet/interop-contrib
