### ISSUE TITLE
Unable to build dotnet/runtime source code locally with dot net framework 4.6.2 as target framework

### ISSUE THREAD

**Issue by SudeerG** [dotnet/runtime#91316]
I am trying to build the source code locally for System.Text.Json, System.Buffers and System.ValueTuple etc. but unable to build. I just need these dlls by building their source code locally for dot net framework 4.6.2. I downloaded code base from URL( https://github.com/dotnet/runtime/tree/v7.0.2 ) and changed target framework from net7.0 to net462(which is required) and failed to build source code. The downloaded source code builds successfully with target framework "net 7.0" only. I just want to build with dot net framework 4.6.2.

Can any one please help me how i can get/build the source code locally with target framework "dot net framework 4.6.2" ?

**Comment by ViktorHofer** [comment]
> and failed to build source code

What's the error?

**Comment by ritesh685** [comment]
the source code you downloaded is designed to target .NET 7.0 and you want to build it with .NET Framework 4.6.2 instead, there are several challenges you might face. .NET Framework and .NET Core/.NET 5+ (now referred to as .NET) have some fundamental differences that could cause compatibility issues. However, here are the general steps you can take to attempt the conversion:

Update Package References: .NET 7.0 could be using packages that are not compatible with .NET Framework 4.6.2. You would need to find and update these package references to versions that are compatible with .NET Framework 4.6.2. This might involve searching for older versions of the packages that still support .NET Framework 4.6.2.

API Compatibility: Check if the code uses APIs or features that are not available in .NET Framework 4.6.2. You might need to replace or refactor these portions of code to use compatible APIs.

Async and Await: .NET 7.0 might use newer async/await patterns that might not work smoothly in .NET Framework 4.6.2. You might need to refactor async/await-related code to work with the older pattern.

Language Features: .NET 7.0 might be using C# language features that are not available in older versions of .NET. You will need to modify the code to use features compatible with C# versions that .NET Framework 4.6.2 supports.

Configuration and Setup: .NET and .NET Framework have differences in how projects are configured and set up. You would need to adjust project files, references, and build configurations to match the older framework.

Platform-Specific Code: If the codebase contains platform-specific code (for example, Linux/macOS-specific or Windows-specific code), you will need to replace or modify these parts to work on the Windows platform with .NET Framework 4.6.2.

Testing and Debugging: After making the necessary changes, you'll need to thoroughly test the application to ensure it behaves correctly on .NET Framework 4.6.2. Debugging and fixing any issues that arise will be part of this process.

Documentation and Community: If the project has an active community or documentation, you might find guidance from others who have attempted similar conversions. This can save you time and help you address common challenges.

It's important to note that converting a project from .NET 7.0 to .NET Framework 4.6.2 might not always be straightforward, especially if the codebase heavily relies on newer features and APIs. Depending on the complexity of the project, it might be more feasible to consider migrating your own environment to support .NET 7.0 or a later version to take full advantage of the modern features and benefits that the latest versions of .NET offer.

**Comment by ritesh685** [comment]
> the source code you downloaded is designed to target .NET 7.0 and you want to build it with .NET Framework 4.6.2 instead, there are several challenges you might face. .NET Framework and .NET Core/.NET 5+ (now referred to as .NET) have some fundamental differences that could cause compatibility issues. However, here are the general steps you can take to attempt the conversion:
> 
> Update Package References: .NET 7.0 could be using packages that are not compatible with .NET Framework 4.6.2. You would need to find and update these package references to versions that are compatible with .NET Framework 4.6.2. This might involve searching for older versions of the packages that still support .NET Framework 4.6.2.
> 
> API Compatibility: Check if the code uses APIs or features that are not available in .NET Framework 4.6.2. You might need to replace or refactor these portions of code to use compatible APIs.
> 
> Async and Await: .NET 7.0 might use newer async/await patterns that might not work smoothly in .NET Framework 4.6.2. You might need to refactor async/await-related code to work with the older pattern.
> 
> Language Features: .NET 7.0 might be using C# language features that are not available in older versions of .NET. You will need to modify the code to use features compatible with C# versions that .NET Framework 4.6.2 supports.
> 
> Configuration and Setup: .NET and .NET Framework have differences in how projects are configured and set up. You would need to adjust project files, references, and build configurations to match the older framework.
> 
> Platform-Specific Code: If the codebase contains platform-specific code (for example, Linux/macOS-specific or Windows-specific code), you will need to replace or modify these parts to work on the Windows platform with .NET Framework 4.6.2.
> 
> Testing and Debugging: After making the necessary changes, you'll need to thoroughly test the application to ensure it behaves correctly on .NET Framework 4.6.2. Debugging and fixing any issues that arise will be part of this process.
> 
> Documentation and Community: If the project has an active community or documentation, you might find guidance from others who have attempted similar conversions. This can save you time and help you address common challenges.
> 
> It's important to note that converting a project from .NET 7.0 to .NET Framework 4.6.2 might not always be straightforward, especially if the codebase heavily relies on newer features and APIs. Depending on the complexity of the project, it might be more feasible to consider migrating your own environment to support .NET 7.0 or a later version to take full advantage of the modern features and benefits that the latest versions of .NET offer.

#91316

**Comment by SudeerG** [comment]
Thanks for the reply.
I just need source code of System.Text.Json, System.Buffers and System.ValueTuple etc. for dot net framework 4.6.2 due to this I am trying to change target framework. Do you have any idea where i can get source code?

**Comment by SudeerG** [comment]
Where i can get source code of System.Text.Json, System.Buffers and System.ValueTuple etc. for dot net framework 4.6.2 ?

**Comment by ritesh685** [comment]
The source code for .NET Framework libraries like System.Text.Json, System.Buffers, and System.ValueTuple is available on GitHub. However, please note that these libraries might not have been backported to work specifically with .NET Framework 4.6.2, as they were developed with a focus on .NET Core and later versions of .NET.

If you're interested in exploring the source code for these libraries, you can visit the official .NET GitHub repository:

System.Text.Json: Source code for JSON serialization and deserialization library.
Repository: https://github.com/dotnet/runtime/tree/main/src/libraries/System.Text.Json

System.Buffers: Source code for memory pooling and array segment manipulation.
Repository: https://github.com/dotnet/runtime/tree/main/src/libraries/System.Buffers

System.ValueTuple: Source code for the ValueTuple struct that provides value-based tuple types.
Repository: https://github.com/dotnet/runtime/tree/main/src/libraries/System.ValueTuple

Keep in mind that even if you find the source code for these libraries, adapting them to work with .NET Framework 4.6.2 might be a non-trivial task, as these libraries were designed and optimized for newer versions of .NET. You might need to address compatibility issues and potential differences in API availability between .NET Framework and newer .NET versions.

**Comment by ericstj** [comment]
What @ViktorHofer mentioned is correct.  I'd also like to clarify that rebuilding these shouldn't be needed for Net462 - just use the nuget packages which include support for `net462`.   EG:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net4.6.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="7.0.3" />
  </ItemGroup>

</Project>
```
