### ISSUE TITLE
[API Proposal]: Fast cache-contention aware counters

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#91319]
### Background and motivation

When we need to increment a global variable from different threads we might hit a terribly performance penalty due to extreme CPU cache contention, a simple repro:
```cs
static Timer timer;

static long current_I = 0;
static long total_I = 0;

static void StartWork_Interlocked()
{
    for (int i = 0; i < 100; i++)
    {
        new Thread(_ =>
        {
            while (true)
            {
                Interlocked.Increment(ref current_I);
                Interlocked.Increment(ref total_I);
                DoWork(100, 42);
                Interlocked.Decrement(ref current_I);
            }
        }).Start();
    }
}

[MethodImpl(MethodImplOptions.NoInlining)]
static long DoWork(long a, long b) => a / b;

static void Main()
{
    long lastTotal = 0;

    timer = new Timer(_ =>
        {
            long total = total_I;
            Console.WriteLine($"RPS: {total - lastTotal:N}");
            lastTotal = total;
        }, null, 0, 1000);

    StartWork_Interlocked();

    Console.ReadKey();
}
```
This minimal repro actually replicates the real counters [used by aspnet core](https://github.com/dotnet/aspnetcore/blob/7eec26ec37f0277f13340ed959e2bec778b647fd/src/Hosting/Hosting/src/Internal/HostingEventSource.cs#L53-L66). On my machine (16 cores, 32 virtual cores) it prints around 22.000.000 RPS to the console:
```
...
RPS: 22,750,731
RPS: 22,748,215
RPS: 22,794,553
RPS: 23,839,057
RPS: 22,697,042
RPS: 23,605,986
RPS: 22,404,121
...
```

The idea that we should avoid incrementing a single cell from multiple threads and instead - use multiple cells (per core or e.g. TLS) and then sum them all when we need to aggregate data. 

So, let me rewrite the same code using an implementation I copied from [here](https://github.com/epeshk/ConcurrencyToolkit/blob/master/src/ConcurrencyToolkit/Metrics/ThreadSafeCounter64.cs) (developed by @epeshk): https://gist.github.com/EgorBo/427f8332b027f4023c0d125b6d5ace5a and run it:
```
RPS: 413,950,984
RPS: 333,793,902
RPS: 315,896,613
RPS: 342,220,688
RPS: 325,139,199
RPS: 357,034,430
```
*(I am sure the impl can be improved further)*

It's now **16x** times faster!

### API Proposal

```csharp
namespace System.Threading; // or System.Diagnostics.* ? 

public class ThreadCounter64 // or e.g. FastLongCounter
{
    public void Add(long val);
    public void Subtract(long val);
    public void Increment();
    public void Decrement();
    public long Get();
    public long GetAndReset();
}
```

### API Usage

As demonstrated in https://gist.github.com/EgorBo/427f8332b027f4023c0d125b6d5ace5a

**Comment by EgorBo** [comment]
NOTE: Other languages/platforms have a similar public API.

Also, the original context: https://github.com/dotnet/aspnetcore/issues/50412

**Comment by Szer** [comment]
Interesting how Go does it.
https://github.com/prometheus/client_golang/blob/51d24f86807c24ce866355d0c82258420f571c17/prometheus/counter.go#L99-L104

They are keeping both original double bits and integer representation of it
and counter update is atomic with just a CAS
```go
	ival := uint64(v)
	if float64(ival) == v {
		atomic.AddUint64(&c.valInt, ival)
		return
	}

	for {
		oldBits := atomic.LoadUint64(&c.valBits)
		newBits := math.Float64bits(math.Float64frombits(oldBits) + v)
		if atomic.CompareAndSwapUint64(&c.valBits, oldBits, newBits) {
			return
		}
	}
```

**Comment by stephentoub** [comment]
Or you can just use a `ThreadLocal<T>`, which was created in part for these kinds of aggregations, is already in the box, isn't limited to a `long`, etc.

When I run your gist locally, I get results like:
```
RPS: 93,592,209.00
RPS: 87,935,554.00
RPS: 94,441,232.00
RPS: 95,101,734.00
RPS: 90,721,404.00
RPS: 90,855,483.00
RPS: 96,250,404.00
RPS: 81,589,440.00
```
If I then replace the `ThreadCounter64` with `ThreadLocal<long>`, e.g.
```C#
    static ThreadLocal<long> current_T = new();
    static ThreadLocal<long> total_T = new(trackAllValues: true);
```
and replace the updates to just operate on `.Value` instead of calling dedicated methods on the counter type, e.g.
```C#
                    current_T.Value++;
                    total_T.Value++;
                    DoWork(100, 42);
                    current_T.Value--;
```
and the summing for reporting to:
```C#
long total = total_T.Values.Sum();
```
I then get numbers like this:
```
RPS: 180,293,996.00
RPS: 193,640,306.00
RPS: 207,393,067.00
RPS: 181,191,413.00
RPS: 201,701,007.00
RPS: 201,414,539.00
```

The ASP.NET example would also be better off just using a `[ThreadStatic]`. While those `_totalRequests`/`_currentRequests`/`_failedRequests` are all instance fields, they're actually just on a singleton instance, so they could instead just be normal `[ThreadStatic]`s because there's no need or desire to differentiate based on what EventSource instance is being used.  That then does even better:
```
RPS: 774,752,266.00
RPS: 878,106,073.00
RPS: 844,240,868.00
RPS: 834,498,939.00
RPS: 859,420,734.00
RPS: 897,911,059.00
RPS: 825,278,438.00
```

**Comment by EgorBo** [comment]
@stephentoub wow, I wasn't aware `ThreadLocal.Values` existed! Awesome!

Also @Szer shared an interesting workaround to avoid the lock we have in https://github.com/dotnet/runtime/blob/9c3f8b3727d9be4de483a1d725c2bda22f956688/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/CounterAggregator.cs#L19

**Comment by EgorBo** [comment]
> The ASP.NET example would also be better off just using a [ThreadStatic].

How do we sum all `[ThreadStatic]` fields then (just like with `ThreadLocal<>`) ?

**Comment by omariom** [comment]
Or it could use per processor store
similar to the following:

```C#
public class ScalableCounter
{
	private ValueHolder[] counters = new ValueHolder[Environment.ProcessorCount];
	
	public void Increment()
	{
	    Add(1);
	}
	
       [MethodImpl(MethodImplOptions.AggressiveInlining)]
	public void Add(int value)
	{
		int index = GetCurrentProcessorNumber();
		
		// If processor count has increased
		if (index >= counters.Length)
		{
		    index %= counters.Length;
		}
		
		Interlocked.Add(ref counters[index].Value, value);
	}
		
	public long GetValue()
	{
		long sum = 0;
		
		// This is just for load-aquire barrier 
		ValueHolder[] countersLocal = Volatile.Read(ref counters); 
		int lastI = countersLocal.Length - 9;
		
		for (int i = 0; i < countersLocal.Length; i++)
		{
			sum += countersLocal[i].Value;	
		}
		
		return sum;
	}
	
        [StructLayout(LayoutKind.Explicit, Size = 64 + sizeof(long))]
	struct ValueHolder
	{
            [FieldOffset(64)]
            public long Value;
	}
		
	[DllImport("kernel32", SetLastError = false), SuppressUnmanagedCodeSecurity]
	static extern int GetCurrentProcessorNumber();
}
```

**Comment by EgorBo** [comment]
> Or it could use per processor store

isn't this exactly what my proposal proposed?

**Comment by omariom** [comment]
@EgorBo 
> isn't this exactly what my proposal proposed?

Exactly :)

I haven't looked at the gist

**Comment by EgorBo** [comment]
Hm.. I am not sure why I closed this since the solution with `ThreadLocal` actually not the same due to possible leaks and is not suitable for precise counting

**Comment by noahfalk** [comment]
@stephentoub does your example in https://github.com/dotnet/runtime/issues/91319#issuecomment-1699279717 still work in the face of threads that increment the counter and then exit? My recollection is that this was a problem that was preventing people from using ThreadLocal for that purpose. I think it would be nice if we could solve it.

**Comment by stephentoub** [comment]
> @stephentoub does your example in [#91319 (comment)](https://github.com/dotnet/runtime/issues/91319#issuecomment-1699279717) still work in the face of threads that increment the counter and then exit? My recollection is that this was a problem that was preventing people from using ThreadLocal for that purpose. I think it would be nice if we could solve it.

My next comment on that thread included:

> That's not perfect, as the boxes will end up being stored indefinitely, which means every thread that touches this will end up contributing, but you get the idea. If we actually wanted to pursue that for ASP.NET's example, there are solutions.

> This highlights one benefit of a per-core rather than per-thread approach: you don't need to worry about leaks stemming from lots of threads coming and going.
