### ISSUE TITLE
Failing test - System.Tests.Types.ModifiedTypeTests.TypeMembers

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#91339]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=390619
Build error leg or test failing: System.Tests.Types.ModifiedTypeTests.TypeMembers
Pull request: https://github.com/dotnet/runtime/pull/91331

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "at System.Tests.Types.ModifiedTypeTests.TypeMembers",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[390619](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390619)|dotnet/runtime|[System.Reflection.Tests.TypeTests.TestBaseType](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390619&view=ms.vss-test-web.build-test-results-tab&runId=8380440&resultId=158410)|dotnet/runtime#91331|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|1|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=390619
**Error message validated:** `at System.Tests.Types.ModifiedTypeTests.TypeMembers`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 8/30/2023 4:17:44 PM UTC

**Comment by ivanpovazan** [comment]
@radical I looked through the CI logs and these failing tests seem to be flaky, as they occurred only once.

Additionally, I reran the failing jobs manually on the PR in question: https://dev.azure.com/dnceng-public/public/_build/results?buildId=390619&view=results and all the `System.Runtime.Tests` seem to be passing on a retry (logs available here: https://helix.dot.net/api/jobs/18ed7c53-dfaa-43a6-bca2-cc07ff9678f8/workitems/System.Runtime.Tests?api-version=2019-06-17)

The same applies for the other two reported issues:
https://github.com/dotnet/runtime/issues/91338
https://github.com/dotnet/runtime/issues/91341

I believe we can close these issues as they don't seem to be reproducible. 

What do you think?

**Comment by radical** [comment]
@ivanpovazan Sounds good to me. I'm not familiar enough with the code to say whether this needs to be investigated more. I think we can close this for now.
