### ISSUE TITLE
Failing test - System.Reflection.Tests.TypeTests.TestBaseType

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#91338]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=390619
Build error leg or test failing: System.Reflection.Tests.TypeTests.TestBaseType
Pull request: https://github.com/dotnet/runtime/pull/91331

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "System.Reflection.Tests.TypeTests.TestBaseType",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=390619
**Error message validated:** `System.Reflection.Tests.TypeTests.TestBaseType`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 8/30/2023 4:07:16 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[390619](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390619)|dotnet/runtime|[System.Reflection.Tests.TypeTests.TestBaseType](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390619&view=ms.vss-test-web.build-test-results-tab&runId=8380440&resultId=158410)|dotnet/runtime#91331|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|1|

**Comment by ivanpovazan** [comment]
As noted in: https://github.com/dotnet/runtime/issues/91339#issuecomment-1706312396 these failures seem to be flaky. Closing the issue.
