### ISSUE TITLE
NativeLib is ignored without PublishAot

### ISSUE THREAD

**Issue by CLTanuki** [dotnet/runtime#91353]
If `NativeLib` is set to `Static`, but `PublishAot` is not set, `NativeLib` property is silently ignored. It's totally implicit behaviour.

According to https://github.com/dotnet/runtime/issues/84583, I think, that an assertion should be placed.

**Comment by MichalStrehovsky** [comment]
Can you provide an example of a property that errors out if it's not applicable to the current build?

I'm not aware of such behavior for any other property. E.g. setting TrimMode without also specifying PublishTrimmed doesn't do anything and I could give dozens of such examples. If PublishAot is not specified, the `.targets` files that interpret `NativeLib` property are not even evaluated by MSBuild.

**Comment by CLTanuki** [comment]
Seems like some logging of used flags would be very helpful just to check if flag is applied or not. Otherwise, developer could stuck with [undefined behaviour](https://en.cppreference.com/w/cpp/language/ub).

**Comment by MichalStrehovsky** [comment]
> Seems like some logging of used flags would be very helpful just to check if flag is applied or not. Otherwise, developer could stuck with [undefined behaviour](https://en.cppreference.com/w/cpp/language/ub).

That sounds like a suggestion for the dotnet/msbuild repo. Note there are a lot of flags that may only mean something when building in a certain way (with/without optimization, for a specific operating system/platform/etc.). Emitting info on unused properties will generate _a lot_ of noise.

**Comment by CLTanuki** [comment]
I mean only emitting list of used flags.
