### ISSUE TITLE
Reading a file in with StreamReader and writing it out with StreamWriter unconditionally adds a BOM when encoding detection is enabled

### ISSUE THREAD

**Issue by gundermanc** [dotnet/runtime#91362]
### Description

The StreamReader implementation supports automatic encoding detection using the byte order mark at the start of the file (if any). This detected encoding is then set as StreamReader.CurrentEncoding, enabling the consumer to use that same encoding to overrte or copy that file elsewhere, perhaps via a StreamWriter.

The encodings set to CurrentEncoding use the static encoding properties (e.g.: Encoding.UTF8) on the `Encoding` class resulting in `encoderShouldEmitIdentifier` always being true for the respective encoding.

What this means is that:
- Using StreamReader to read in a file without a BOM and then passing StreamReader.CurrentEncoding to some other means to re-write it adds a BOM where there was none before.

- Usages of StreamReader that depend on knowledge of the BOM have to implement their own encoding detection on the stream. `StreamReader.CurrentEncoding.Preable` is always non-zero length, regardless of whether or not the file has a BOM.

### Reproduction Steps

1) Create a UTF-8 text file with no BOM

2) Open it for reading with StreamReader and call ReadLine() once.

### Expected behavior

StreamReader.CurrentLine.Preamble is zero length, much as it is with:
 `new UTF8Encoding(encoderShouldEmitUTF8Identifier: false).GetPreamble()`

### Actual behavior

StreamReader.CurrentLine.Preamble is 3 bytes in length, much as it is with:
 `new UTF8Encoding(encoderShouldEmitUTF8Identifier: true).GetPreamble()`

### Regression?

No, it seems to have been this way historically back through .NET Framework according to the Reference Source repository.

### Known Workarounds

Write your own encoding detection on the stream and use that to determine the preamble. This work-around is fine though I'd expect users working in a blended OS environment where BOMs aren't common or required to hit this more frequently than in Windows where BOMs tend to be fairly 'standard'.

### Configuration

Dotnet v6.0.407 on Windows 11 22621.2134 x64

Does not seem to be configuration specific.

**Comment by adamsitnik** [comment]
Hi @gundermanc 

> it seems to have been this way historically back through .NET Framework according to the Reference Source repository

Whether we like it or not, we can not change this behavior because it would be a breaking change.

Which means that if you want to use the encoding exposed by the reader for writing without BOM, you need to create a new encoding

```cs
static Encoding GetEncodingWithoutBom(Encoding readerEncoding)
    => readerEncoding switch
    {
        UTF8Encoding utf8Encoding when utf8Encoding.Preamble.Length > 0 => new UTF8Encoding(encoderShouldEmitUTF8Identifier: false),
        _ => readerEncoding
    };
```

**Comment by gundermanc** [comment]
This example above only works if you know there's no BOM. In the cases where there might be, one has to write their own BOM parsing code and run it on the start of the stream.

Seems like it would be reasonable to expose a new property that has the encoding with the correct BOM/no-BOM setting. This would maintain back compat.
