### ISSUE TITLE
Constructor function of System.IO.FileInfo won't throw other exceptions?

### ISSUE THREAD

**Issue by livisen** [dotnet/runtime#91369]
### Description

For the source code of constructor of System.IO.FileInfo, now it only throw ArgumentNullException.
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/IO/FileInfo.cs#L16

But from the help doc, it would throw many other exceptions.
https://learn.microsoft.com/en-us/dotnet/api/system.io.fileinfo.-ctor?view=net-8.0#system-io-fileinfo-ctor(system-string)
![image](https://github.com/dotnet/runtime/assets/23472460/a5c374d1-2057-44e9-aaeb-d712cb49c742)

So Constructor function of System.IO.FileInfo won't throw other exceptions?

### Reproduction Steps

I noticed this because  System.IO.FileInfo is used to check if filename is valid, e.g. no invalid characters, path not too long...

Test code is simple. Below code will throw System.IO.PathTooLongException in .NET Framework 4.7.
Now in latest .NET 6, the exception won't be thrown.

try
{
    string filename = "C:\\temp\\vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq.csv";
    System.IO.FileInfo fileInfo = new System.IO.FileInfo(filename);
    long nLength = fileInfo.Length;
    Console.WriteLine("No exception");
}
catch (System.Exception e)
{
    Console.WriteLine("Exception:");
    
    Console.WriteLine(e.Message);
}

### Expected behavior

Throw exception?
So is this a bug or a behavior by design?

### Actual behavior

No exception.

### Known Workarounds

Any other suggestions of switching to which function to check the validation of a file name? (Note: file name is to save a file, not for opening a file).

### Configuration

.NET Framework 6
OS: Windows.

**Comment by stephentoub** [comment]
The constructor delegates to another constructor:
https://github.com/dotnet/runtime/blob/b715349c6bed12a4645a9971e1f75a0845469c6f/src/libraries/System.Private.CoreLib/src/System/IO/FileInfo.cs#L17
which calls `Path.GetFullPath`, so anything `Path.GetFullPath` can throw can also emerge here.

**Comment by adamsitnik** [comment]
As @stephentoub wrote, it calls the other ctor:

https://github.com/dotnet/runtime/blob/6d3be9e69dc385722851b0c165255cc4828aec7c/src/libraries/System.Private.CoreLib/src/System/IO/FileInfo.cs#L17

which calls `Path.GetFullPath`:

https://github.com/dotnet/runtime/blob/6d3be9e69dc385722851b0c165255cc4828aec7c/src/libraries/System.Private.CoreLib/src/System/IO/FileInfo.cs#L28

which delegates to `GetFullPathInternal`

https://github.com/dotnet/runtime/blob/6d3be9e69dc385722851b0c165255cc4828aec7c/src/libraries/System.Private.CoreLib/src/System/IO/Path.Windows.cs#L58

which delegates to `PathHelper.Normalize`:

https://github.com/dotnet/runtime/blob/6d3be9e69dc385722851b0c165255cc4828aec7c/src/libraries/System.Private.CoreLib/src/System/IO/Path.Windows.cs#L143

which delegates to `GetFullPathName`

https://github.com/dotnet/runtime/blob/6d3be9e69dc385722851b0c165255cc4828aec7c/src/libraries/System.Private.CoreLib/src/System/IO/PathHelper.Windows.cs#L30

which performs the actual work by calling [GetFullPathNameW](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfullpathnamew)

https://github.com/dotnet/runtime/blob/6d3be9e69dc385722851b0c165255cc4828aec7c/src/libraries/System.Private.CoreLib/src/System/IO/PathHelper.Windows.cs#L77

which may fail and throw an exception:

https://github.com/dotnet/runtime/blob/6d3be9e69dc385722851b0c165255cc4828aec7c/src/libraries/System.Private.CoreLib/src/System/IO/PathHelper.Windows.cs#L86-L89

So to `FileInfo` constructor may still throw.

**Comment by livisen** [comment]
Hi @adamsitnik , @stephentoub ,

Thought it has code of throw exception, but for these two cases, 
System.IO.Path.GetFullPath(...) also won't throw the exception.

Here's some example code and execute result.
![image](https://github.com/dotnet/runtime/assets/23472460/34d3581b-f492-4146-80d4-7343c40c23c8)
![image](https://github.com/dotnet/runtime/assets/23472460/0eb32104-1636-4211-ad79-2b91c03901d5)

**Comment by livisen** [comment]
- For the exception: [PathTooLongException](https://learn.microsoft.com/en-us/dotnet/api/system.io.pathtoolongexception?view=net-8.0).

"Apps that target the .NET Framework 4.6.2 and later versions", path can be longer, beyond 260.
Strange, I tested in .NET Framework 4.7,  above code still can throw this PathTooLongException.
So this may explain why PathTooLongException isn't thrown in .NET 6.
![image](https://github.com/dotnet/runtime/assets/23472460/b065d929-309b-4a39-80f1-d5671e14bef5)

- For the exception: [ArgumentException](https://learn.microsoft.com/en-us/dotnet/api/system.argumentexception?view=net-8.0) which should thrown when there are invalid characters.

Only get this from [help doc](https://learn.microsoft.com/en-us/dotnet/api/system.io.fileinfo.-ctor?view=net-8.0#system-io-fileinfo-ctor(system-string)).
So does it mean System.IO.Fileinfo also won't be throw exception though there are invalid characters in the file name.
![image](https://github.com/dotnet/runtime/assets/23472460/0e1b910a-6a60-4b2d-b777-887b997a611d)


If the constructor of System.IO.Fileinfo won't throw exception any more, are there other backup functions that can validate file name?

**Comment by adamsitnik** [comment]
@livisen `FileInfo` ctor is no longer throwing on invalid characters, this breaking change was introduced in .NET Core 2.1, you can read more about it here: https://learn.microsoft.com/en-us/dotnet/core/compatibility/corefx#net-core-21

**Comment by livisen** [comment]
@adamsitnik Thanks for replying.

I see, for those two case's exception, FileInfo won't throw exceptions for some reasons.
For the Invalid character exception, using GetInvalidPathChars(), GetInvalidFileNameChars() instead to validate characters.
