### ISSUE TITLE
[API Proposal]: Specify default value for OrDefault Linq Methods

### ISSUE THREAD

**Issue by kandicst** [dotnet/runtime#91396]
### Background and motivation

After watching these two videos ([video1](https://www.youtube.com/watch?v=Jf1_AmXO6Zc), [video2](https://www.youtube.com/watch?v=HRLdcMil7Ec)) and reading about Null Object Pattern it occurred to me that it would be pretty useful to be able to specify your own default value when using `FirstOrDefault` and `SingleOrDefault` methods.

I could just implement them as extension methods but it would be even better if this were a part of the standard library.

### API Proposal

```csharp
using System.Collections.Generic;

namespace System.Linq;

public static partial class Enumerable
{
   public static TSource? FirstOrDefault<TSource>(this IEnumerable<TSource> source, TSource? defaultValue = default) {}

   public static TSource? FirstOrDefault<TSource>(this IEnumerable<TSource> source, Func<TSource, bool> predicate, TSource? defaultValue = default) {}

   public static TSource? SingleOrDefault<TSource>(this IEnumerable<TSource> source, TSource? defaultValue = default) {}

   public static TSource? SingleOrDefault<TSource>(this IEnumerable<TSource> source, Func<TSource, bool> predicate, TSource? defaultValue = default) {}
}
```

### API Usage

```csharp

public class ComplexObject
{
    public static ComplexObject Default { get; } = new ComplexObject(...);
    
    // properties and methods
}

public static ComplexObject Get(IEnumerable<ComplexObject> objects) 
{
    return objects.FirstOrDefault(defaultValue: ComplexObject.Default);
}
```

### Risks

There should be no risks as this would not be a breaking change as old code would work the same

**Comment by svick** [comment]
If we're talking about reference types, then you can use e.g. `objects.FirstOrDefault() ?? ComplexObject.Default`. I think that makes the proposed overloads much less useful.

**Comment by tarekgh** [comment]
I agree with @svick, the proposed APIs are not adding much value considering using the `??` syntax. I am closing this issue; we can consider it in the future if we see more demand from users. Thanks for your report.
