### ISSUE TITLE
TaskAsyncEnumerableExtensions.WithCancellation does not override a cancelled token with an active one.

### ISSUE THREAD

**Issue by baal2000** [dotnet/runtime#91397]
### Description

While working on the IAsyncEnumerable<T> pattern I noticed that that [WithCancellation](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskasyncenumerableextensions.withcancellation?view=net-7.0) doesn't substitute the original canceled token even if an uncancelled token is provided. I've illustrated this behavior in the example below.

The framework appears to employ an "OR" strategy between the tokens, opting for the canceled one when determining if the enumeration should be terminated, regardless of whether it's the original or introduced via WithCancellation.

If this functionality is intentional, it might be helpful to reflect this detail in the documentation.

### Reproduction Steps

```
    [Fact]
    public async Task CancellationOverrideTest()
    {
        IAsyncEnumerable<string> EnumerateAsync(IAsyncEnumerable<string> enumerable, in CancellationToken token = default)
        {
            return GetDataAsync(token);

            async IAsyncEnumerable<string> GetDataAsync([EnumeratorCancellation] CancellationToken cancellationToken = default)
            {
                await foreach (var item in enumerable)
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    yield return item;
                }
            }
        }

        var collection = new[] { "1", "2", "3", "4" }.ToAsyncEnumerable();
        using var activeCts = new CancellationTokenSource();
        using var cancelledCts = new CancellationTokenSource();
        cancelledCts.Cancel();

        // Expected to generate OperationCanceledException.
        await Assert.ThrowsAsync<OperationCanceledException>(async () =>
            await EnumerateAsync(collection).WithCancellation(cancelledCts.Token).GetAsyncEnumerator().MoveNextAsync());
        // Expected to generate OperationCanceledException.
        await Assert.ThrowsAsync<OperationCanceledException>(async () =>
            await EnumerateAsync(collection, activeCts.Token).WithCancellation(cancelledCts.Token).GetAsyncEnumerator().MoveNextAsync());

        // Is not expected to generate OperationCanceledException if activeCtsToken overrides the original cancelled  one,
        // but it does and the test fails here.
        await EnumerateAsync(collection, cancelledCts.Token).WithCancellation(activeCts.Token).GetAsyncEnumerator().MoveNextAsync();
    }
```

### Expected behavior

The test passes

### Actual behavior

The test fails on its last line

### Configuration

.NET 7.0

**Comment by stephentoub** [comment]
This is by design. _Both_ tokens are considered. You can see the logic the compiler generates for this in [sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATARgLABQGADAAQY4oDchJ5OAdAEoCuAdgC4CWAtjAwGEIPAA5cANjCgBlKQDcuYGAGcaRMhQYAVABawAhgBMubAOZraAZnJZSA0gG9CpF65cBJAILKAnmzAAomwsfFD6wJIAPBTEAHykQSFS+hww3n5gABRevv6JoeFRMfEwwQURMAA0pCZ2+v4w4uIpXBBsWhAA1qWkHF09ALykhjAAZvos4hwAlM5urk4E88vkAOykAOIwHAAiKfrp/pl93WzTFksrbhgAHKQ5GfnJFdE4cZvbexwHuVkA2k8wn0oAJ6komi02gBdOoNCHcNodU6kMBgxrNBHtfpsUhDEbjSYzOZXFyLEkrDAATlIo2gMH0YB0pEycn0UBqqR4NRxpSSYQqs0u5LcZOFV1RcIxrSxp20eggAHd3KNQZLIWwmDAAI4sFSpQyZc7EsXzCg4NYcmA8NQm1wAX2NVwdQvmzrtQA==)... search for where it's using CancellationTokenSource.CreateLinkedTokenSource.

More information about this is available at https://learn.microsoft.com/en-us/archive/msdn-magazine/2019/november/csharp-iterating-with-async-enumerables-in-csharp-8

**Comment by baal2000** [comment]
Upon reviewing the [paper](https://learn.microsoft.com/en-us/archive/msdn-magazine/2019/november/csharp-iterating-with-async-enumerables-in-csharp-8), I've come to understand its intended use:

> In corner-cases, it can also be advantageous to pass the token to GetAsyncEnumerator, as doing so avoids “burning in” the token in the case where the single enumerable will be enumerated multiple times.

However, with Roslyn analyzers like [MA0079](https://github.com/meziantou/Meziantou.Analyzer/blob/main/docs/Rules/MA0079.md) mandating the use of the WithCancellation pattern for every foreach, there's potential for confusion. This arises especially when the behavior deviates from expectations based solely on the local context—like when an IAsyncEnumerable<T> instance with an embedded cancelled token is transferred between different components.

Thus, incorporating a note akin to the one above into the [WithCancellation](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskasyncenumerableextensions.withcancellation?view=net-7.0) documentation would be beneficial for clarity.

**Comment by baal2000** [comment]
Closing, feel free to reopen and make it an action item.
