### ISSUE TITLE
SslStream hangs on client when SslStream server fails on protocol mismatch

### ISSUE THREAD

**Issue by the-black-wolf** [dotnet/runtime#914]
Ok, the new preview and my bug caused the public/private key issue. However, there is still one issue left. On protocol mismatch, the server side throws an SSL error (`SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL`). However, the client side is apparently unaware of the protocol failure and hangs (presumably waiting for server handshake to continue) . The only way to kick the client out of hang is to kill the underlaying connection on server, but then the exception showin in client is `Authentication failed because the remote party has closed the transport stream.` which is pretty useless for resolution.
Once again, this is done and tested on Linux, I have not tried the same on Win/Mac.

```csharp
using System;
using System.Net;
using System.Net.Security;
using System.Net.Sockets;
using System.Security.Authentication;
using System.Security.Cryptography.X509Certificates;
using System.Threading;
using System.Threading.Tasks;

namespace SslFail
{
	internal static class Program
	{
		private static async Task StartClientAndAuthenticate(ClientServerState state, IPEndPoint endPoint)
		{
			try
			{
				state.Client.Connect(endPoint.Address, endPoint.Port);
				state.ClientStream = new SslStream(state.Client.GetStream(), false,
					(a1, a2, a3, a4) => true,
					(a1, a2, a3, a4, a5) => null);
				await state.ClientStream.AuthenticateAsClientAsync("localhost", null, SslProtocols.Tls12, false);
				state.ClientAuthenticated.Set();
			}
			catch (Exception e)
			{
				Console.WriteLine($"Exception in Client: {e.Message} {e.InnerException?.Message}");
			}
		}

		private static async Task StartServerAndAuthenticate(ClientServerState state)
		{
			try
			{
				state.Listener.Start();

				var s = new X509Store(StoreName.My, StoreLocation.CurrentUser, OpenFlags.ReadOnly);
				var serverCert = s.Certificates[0];

				state.ServerClient = await state.Listener.AcceptTcpClientAsync();
				state.ServerStream = new SslStream(state.ServerClient.GetStream(), false,
					(a1, a2, a3, a4) => true,
					(a1, a2, a3, a4, a5) => serverCert, EncryptionPolicy.RequireEncryption);
				await state.ServerStream.AuthenticateAsServerAsync(serverCert, false, SslProtocols.Tls13, false);
				state.ServerAuthenticated.Set();
			}
			catch (Exception e)
			{
				Console.WriteLine($"Exception in Server: {e.Message} {e.InnerException?.Message}");
			}
			finally
			{
				// if I do not do this, the client is hang (presumably until connection dies)
				// even then, the error is dropped connection and not a protocol mismatch, so there is no
				// way to course correct. 
				// state.ServerClient?.Close();  	
			}
		}

		private class ClientServerState
		{
			public TcpListener Listener { get; set; }
			public TcpClient Client { get; } = new TcpClient();
			public TcpClient ServerClient { get; set; }
			public SslStream ServerStream { get; set; }
			public SslStream ClientStream { get; set; }
			public AutoResetEvent ServerAuthenticated { get; } = new AutoResetEvent(false);
			public AutoResetEvent ClientAuthenticated { get; } = new AutoResetEvent(false);
		}

		private static void Main(string[] args)
		{
			var endPoint = new IPEndPoint(IPAddress.Loopback, 35454); 
			var state = new ClientServerState { Listener = new TcpListener(endPoint) };
			try
			{
				#pragma warning disable CS4014
				StartServerAndAuthenticate (state);
				StartClientAndAuthenticate (state, endPoint);
				#pragma warning enable CS4014
				state.ServerAuthenticated.WaitOne();
				state.ClientAuthenticated.WaitOne();
				Console.WriteLine("All is well, no bug detected!");
			} finally {
				state.ClientStream?.Dispose ();
				state.Client.Close ();
				state.ServerStream?.Dispose ();
				state.ServerClient?.Close ();
				state.Listener.Stop ();
			}
		}
	}
}
```

**Comment by cheenamalhotra** [comment]
I'm wondering if this is what causes hangs in SqlClient when connecting in Linux images that do not support TLS 1.0 and 1.1 protocols while servers do.

Refer issue https://github.com/dotnet/SqlClient/issues/126 and https://github.com/dotnet/SqlClient/issues/201

The driver does not seem to have any control over which protocol version is negotiated with server, which leads to come down to Sockets and SslStream classes.

Our implementation of TCP Handle can be found in [SNITCPHandle.cs](https://github.com/dotnet/SqlClient/blob/master/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNITcpHandle.cs). Please let us know if there's a workaround we can use or if this issue is going to be addressed sometime.

**Comment by TechnologyAnimal** [comment]
Hello everyone. I recently ran into an issue with System.Net.Security.SslStream and it's really ruining my day. I asked a question on [reddit](https://www.reddit.com/r/csharp/comments/fippha/systemnetsecuritysslstream_authenticateasclient/), and some very nice person pointed me to this thread.  Details can be found in that thread, but will summarize here as well.

I [wrote code](https://github.com/TechnologyAnimal/Test-TlsProtocols/blob/master/Test-TlsProtocols/Test-TlsProtocols.psm1) to that attempts to establishes ssl connections with remote systems to output what tls protocols a client can successfully establish with a server.  This code is used to successfully scan hundreds of thousands of systems, but I continue to run into edge cases that cause my process thread to hang and I have no choice but to terminate the process.

In those cases, I have no problems creating a socket connection, creating the net stream and the ssl stream.  The problem occurs when I attempt to use the ssl stream to [authenticate as client](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslstream.authenticateasclient?view=netcore-3.1).  It doesn't matter if I use .NET Core 3.1 on Mac OSX or Windows Server 2016.  It also doesn't matter if I use .NET Framework 4.8.

I am working in a very large environment without admin rights on these remote systems, but started to fingerprint these edge case services that are causing the thread to hang.  Here are three example cases that I can consistently reproduce the failures:

* Integrated Dell Remote Access Controller / Linux 2.4-2.6 / Embedded Device / F5 Big Networks Big IP -- 4001/tcp open nclockmgr 1-4 (RPC #100021)

* Windows 2008 R2 -- 9090/tcp open zeus-admin?

* Oracle Enterprise Linux 7.7 -- 8888/tcp open http Tornado htttpd 6.0.3

Full source code was provided above, but here is a code snippet, with the final line being the problem:

$Socket = [System.Net.Sockets.Socket]::new([System.Net.Sockets.SocketType]::Stream, [System.Net.Sockets.ProtocolType]::Tcp)
$Socket.Connect($fqdn, $Port)
$NetStream = [System.Net.Sockets.NetworkStream]::new($Socket, $true)
$SslStream = [System.Net.Security.SslStream]::new($NetStream, $true, { $true })
$SslStream.AuthenticateAsClient($fqdn, $null, $ProtocolName, $false)

I would be more than happy to provide any additional information, test a fix, or anything else that might be helpful to bring resolution to the issue.

Any suggested workarounds would be greatly appreciated.

**Comment by TechnologyAnimal** [comment]
Bump?!

**Comment by pbsis** [comment]
I'm getting the same issue on both .NET 4.8 and Core 3.1. I've written a simple SMTP/IMAP proxy to implement some extra security and my STARTTTLS implementation won't work with either facebook or office365. When they try and send us emails I get a hang when calling AuthenticateAsServer. Tried all the various TLS versions but can't get it to work. I suspect it's a cipher mismatch but without an exception bubbling up it's difficult to debug. Just adding my +1 that it would be good to get this fixed. Thanks!

**Comment by TechnologyAnimal** [comment]
Can someone at least acknowledge this issue and offer some sort of assurance that this is being looked at?  My concern is the untriaged tag being removed.  I hope that doesn't mean someone is under the impression this issue has actually been fixed...  Thank you.

@karelz karelz

**Comment by davidsh** [comment]
>Can someone at least acknowledge this issue and offer some sort of assurance that this is being looked at? My concern is the untriaged tag being removed. I hope that doesn't mean someone is under the impression this issue has actually been fixed... Thank you.

The issue is still Active and not Closed. It is assigned to @wfurt and will be investigated for fixing during our current .NET 5 milestone.

**Comment by TechnologyAnimal** [comment]
> > Can someone at least acknowledge this issue and offer some sort of assurance that this is being looked at? My concern is the untriaged tag being removed. I hope that doesn't mean someone is under the impression this issue has actually been fixed... Thank you.
> 
> The issue is still Active and not Closed. It is assigned to @wfurt and will be investigated for fixing during our current .NET 5 milestone.

Thanks for the reply!  I am using this daily to scan hundreds of thousands of servers for tls configuration.  Due to no tls alert and no error messages, I've had to put less than ideal workarounds in place to workaround the bug.  I am eager to get that mess out of the code base, so if there is anything I can help test or clarify, I would be happy to do so.  Thanks again.

**Comment by wfurt** [comment]
Some improvements were maid. Part of the problem is that Schannel does not generate alert in all cases - version mismatch is one of them. However, the AuthenticateAs*() will throw and in case of server, that would typically close connection and client would see that as IOException. 

If you have sample code or packet captures let me know @TechnologyAnimal. I left this one open to look at macOS

**Comment by wfurt** [comment]
one more note @TechnologyAnimal is that the alert was not generated on the server side. It seems like your scenario is client. With that, if server does not sent alert and does not close connection, there is really nothing we can do besides timeout.

**Comment by TechnologyAnimal** [comment]
> one more note @TechnologyAnimal is that the alert was not generated on the server side. It seems like your scenario is client. With that, if server does not sent alert and does not close connection, there is really nothing we can do besides timeout.

Hi @wfurt .  I [replied above ](https://github.com/dotnet/runtime/issues/914#issuecomment-599169905) with a detailed breakdown of what I've been experiencing, along with the code I have been using.  Unfortunately, it's written in PowerShell, which I assume is less than ideal, but it's all that I have.

My goal is to scan a few hundred thousand servers regularly to identify what TLS protocols are supported by a server.  In a handful of edge cases, there is no TLS alert sent from the server to the client.  The end result is that those requests completely hang.  No exception is thrown.  No timeout occurs.  The process hangs forever, which I assume is not the expected behavior.

I was able to [workaround](https://github.com/TechnologyAnimal/Test-TlsProtocols/blob/dotnet-bug-workaround-testing/Example/Invoke-TlsProtocolTest.ps1) the issue by wrapping these calls up inside jobs and assigning a timeout value, but I find it to be really messy.

Any suggestions or advice would be greatly appreciated.

**Comment by wfurt** [comment]
In that case this GH issue is really irrelevant. The servers you connecting to may or may not have updated .NET or may not run .NET at all. 

I'm not familiar with PowerShell and their APIs so I'll outline few strategies. 
You generally deal with situation when you expect response from server but it is not coming - neither error nor success. I think in that case (short?) timeout is really only option IMHO. 

From .NET API prospective, SslStream really only creates and decodes TLS frames. It depends on underlying Stream given to it to handle IO and timeout.  In typical case, the sequence would be Socket -> NetworkStream -> SslStream. You can create wrapper stream to throw after some time or you can use select/poll. You can probably use  [HttpCient](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.timeout?view=netcore-3.1) with timeout. That could work for servers others then HTTP. You would get OperationCanceled for timeout, AuthenticationException for TLS issues and anything else for protocol mismatch.  

If I would do that in shell my self, would probably spawn a process - like `openssl s_client` or other app to do the handshake. With that I can kill it easily if that does not finish on time as well as I could do more in parallel/background.  That is more expensive than doing everything synchronously inline but given the conditions, I don't think there is other easy way unless you find way how to control timeout.

**Comment by wfurt** [comment]
reading through the thread, it seems like your use case is different @pbsis. Do you limit ciphers or TLS versions when you do AuthenticaterAsServer()? What OS you running on? It may be worth of trying [daily](https://github.com/dotnet/installer) builds and posting packet capture. (from side between client and your proxy e.g. .NET plays server)
