### ISSUE TITLE
Webassembly size and performance 

### ISSUE THREAD

**Issue by sajjadarashhh** [dotnet/runtime#91437]
In .net ecosystem one of the most important goals and the greatest advantages of this ecosystem is performance
When i started working with blazor in three years ago i see many performance problems like size of project at that time my project size is equals to 65mb
Gradually with the arrival of new versions that size is reduced to ~20mb
That's still very bad!
When we compare blazor wasm vs js frameworks such as react and... This size is not acceptable
And when project is downloaded user must be wait for a few seconds to project get starting
After all، a question arises in our minds
Why deployed webassembly application that compiled and compressed size is equals to 22mb?
which one of features that available in blazor is not available in another frameworks such as react and etc?
Everything that blazor do react do
But that size and startup performance and runtime performance is very better that blazor
When i see [https://krausest.github.io/js-framework-benchmark/current.html](kaurest benchmarks)  for first time i check for vanilla js and wasm performance comparison
Wasm is more faster in some scenarios
 in blazor that used wasm but why that very very slower than that
And in some scenarios react is equals to vanillajs

**Comment by radical** [comment]
cc @javiercn @lewing @pavelsavara

**Comment by maraf** [comment]
Are you refering to a download size (from browser devtools)? Is the app published in release configuration?

The published app from blazor template is about ~1MB in download size, which is still more that react, but that is the price for bringing in also a runtime (where as react and other js framework use the "javascript runtime" that is already in place).

One of the great benefits of blazor (or .NET in browser in general) is unified codebase. "All code" that you already have in .NET, can be used in browser as well, whether it's some domain specific logic or an existing nuget package, like QR image generator.

**Comment by pavelsavara** [comment]
@sajjadarashhh we are very aware of the importance of size/performance of dotnet wasm and we spend significant efforts each release to make it better or at least not worse than previous release.

We have an article which explains how you could make your dotnet application smaller. 
It also explains why the dotnet is bigger than JavaScript native applications.
It also has sort section about choosing the right technology, depending on your needs.

Please see https://aka.ms/dotnet-wasm-features

If you have specific ideas on how to improve dotnet, we welcome PRs :)

**Comment by sajjadarashhh** [comment]
@maraf no thats not 1mb!
Thats have weight across a 4-7mb with compression mode thats weight equals to 1mb

**Comment by sajjadarashhh** [comment]
dear @pavelsavara i dont know why do you close this issue
but we must be known why and how to solve this problem soon
i see end of that page writed you could be use blazor or .net wasm where  performance is not critical
but which website is available in the world that no need performance?
