### ISSUE TITLE
Item4 is missing in some `ValueTuple`s' `IStructuralEquatable.Equals`

### ISSUE THREAD

**Issue by skyoxZ** [dotnet/runtime#91457]
### Description

Some `ValueTuple`s' `IStructuralEquatable.Equals` methods skip comparing Item4.

https://github.com/dotnet/runtime/blob/91ac6b3544d53fcf9e6962575813c1cd54aa27bd/src/libraries/System.Private.CoreLib/src/System/ValueTuple.cs#L1123-L1128

Search `vt.Item3) &&` in that file to find more.

### Reproduction Steps

```csharp
using System.Collections;

IStructuralEquatable a = ValueTuple.Create(1, 2, 3, 4, 5);
IStructuralEquatable b = ValueTuple.Create(1, 2, 3, 0, 5);

Console.WriteLine(a.Equals(b, EqualityComparer<object>.Default));
await Task.Delay(-1);
```

### Expected behavior

False

### Actual behavior

True

**Comment by jeffhandley** [comment]
This will be fixed in .NET 8 but we've concluded the risk of changing this behavior in .NET 6/7 servicing outweighs the benefit without reports of customers being affected and blocked. Please file a new issue if this bug is affecting you in a blocking way on a supported .NET version.
