### ISSUE TITLE
[API Proposal]: Add `Deconstruct` method to `Rune`

### ISSUE THREAD

**Issue by Neme12** [dotnet/runtime#91509]
### Background and motivation

Currently, `Rune` has a constructor that takes a high surrogate and a low surrogate. It would be nice to have a corresponding `Deconstruct` method that allows deconstructing the `Rune` back to a high and a low surrogate. Currently, the only way to do this is by using the `EncodeToUtf16` method which takes a `Span<char>`, meaning you have to create a buffer and it's not as easy to get the surrogates back into 2 variables.

### API Proposal

```diff
 namespace System.Text;
 
 public readonly partial struct Rune
 {
     // Existing constructor:
     public Rune(char highSurrogate, char lowSurrogate);
 
     // Proposed method:
+    public void Deconstruct(out char highSurrogate, out char lowSurrogate);
 }
```

### API Usage

```csharp
var (highSurrogate, lowSurrogate) = rune;
```

**Comment by MihaZupan** [comment]
What if the rune represents a code point in the BMP? I'd find a deconstructor throwing to be very unintuitive.

Wouldn't a `bool TryGetSurrogates(out char, out char)` method be more appropriate?

**Comment by Neme12** [comment]
> What if the rune represents a code point in the BMP?

Uh, to be honest, I didn't really think about that. I suppose it could return `highSurrogate` with the value and leave `lowSurrogate` null, to mirror how `EcodeToUtf16 `works but having the second `char` as 0 if there is no second `char`. But that might be weird/unexpected. And I agree that throwing would be bad.
