### ISSUE TITLE
[wasm-node] Node process exits after C# main exits

### ISSUE THREAD

**Issue by Elringus** [dotnet/runtime#91511]
### Description

When running in node, the runtime seem to invoke `process.exit()` after invoking program's entry point.

### Reproduction Steps

1. Clone repro project: https://github.com/Elringus/JSInteropTest
2. Run `dotnet publish`
3. Run `node main.js` under `bin/Release/net8.0/browser-wasm/AppBundle` directory

### Expected behavior

Node process doesn't exit after invoking C# Main(). "Runtime run." and further messages are logged.

### Actual behavior

Process exits after C# Main is invoked.

### Configuration

.NET 8.0.100-rc.2.23418.10
Node.js v20.5.1.

### Other information

It works in browser as expected. To test, html-serve the index.html file under AppBundle directory.

**Comment by Elringus** [comment]
Upd: this also happens when running in VS Code web extension environment (I guess it's also detected as node?).

**Comment by pavelsavara** [comment]
on node that is as designed, why you want it to continue running there ?

**Comment by pavelsavara** [comment]
You can use 
```js
import { dotnet } from './_framework/dotnet.js'
const { runMain } = await dotnet.create();
await runMain();
```

That should not exit

**Comment by Elringus** [comment]
> on node that is as designed, why you want it to continue running there ?
For services, like language servers. Though, even generally, I feel it's a bit unusual for a side-loaded WASM module to shut down host node process. 

The `runMain` works perfectly though, in both node and VS Code, thank you!
