### ISSUE TITLE
ClaimsPrincipal and ClaimsIdentity type proxies hide properties on derived types

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#91526]
### Description

A PR to improve debugging claims debugging added type proxies for ClaimsPrincipal and ClaimsIdentity: https://github.com/dotnet/runtime/pull/86424

These types aren't sealed, and WindowsPrincipal and WindowsIdentity inherit from them and add new properties. For example, [WindowsPrincipal.DeviceClaims](https://learn.microsoft.com/en-us/dotnet/api/system.security.principal.windowsprincipal.deviceclaims?view=net-7.0). These properties are hidden by the type proxies.

Two possible solutions:
1. Remove type proxies. The proxies improve the display of some `IEnumerable<Claims>` properties, which I believe could be replaced by placing [DebuggerDisplayAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.debuggerdisplayattribute?view=net-7.0) on those properties. I haven't seen `DebuggerDisplayAttribute` used on properties before, but its attribute usage allows it.
2. Add type proxies for WindowsPrincipal and WindowsIdentity. This would improve debugging of these types, but anyone else who inherits from the base claim types and adds new properties will still have them hidden.

### Reproduction Steps

Create WindowsPrinicipal and debug.

### Expected behavior

WindowsPrinicipal.DeviceClaims is visible in the default debugging view.

### Actual behavior

Only ClaimsPrinicipal properties are visible in the default debugging view.

### Regression?

Yes. These properties were visible by default when debugging .NET 7.

**Comment by JamesNK** [comment]
Should this be fixed in .NET 8 RC2?

**Comment by vcsjones** [comment]
> 2\. Add type proxies for WindowsPrincipal and WindowsIdentity. This would improve debugging of these types, but anyone else who inherits from the base claim types and adds new properties will still have them hidden.

As a point of reference, [looking across GitHub](https://github.com/search?q=%2Fclass.*%3A%5CsClaims%28Principal%7CIdentity%29%2F+lang%3AC%23&type=code), I can see a number of places where 3rd parties are deriving from this type.

My vote would be a fix that benefits all folks that derive from these types.

**Comment by JamesNK** [comment]
> 1. Remove type proxies. The proxies improve the display of some `IEnumerable<Claims>` properties, which I believe could be replaced by placing [DebuggerDisplayAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.debuggerdisplayattribute?view=net-7.0) on those properties. I haven't seen `DebuggerDisplayAttribute` used on properties before, but its attribute usage allows it.

Unfortunately, this doesn't work. There is a bug in Roslyn: https://github.com/dotnet/roslyn/issues/4134

**Comment by Jozkee** [comment]
Removing the proxies and add DebuiggerDisplay to the Claims property after https://github.com/dotnet/roslyn/issues/4134 gets fixed (if ever) seems best to me.

> create a List<Claim> and return that

Not sure if it's worth to add allocations for debugging purposes. cc @bartonjs
