### ISSUE TITLE
File does not contain a valid CIL image

### ISSUE THREAD

**Issue by mario-campos** [dotnet/runtime#91525]
### Description

I'm trying to run the [GitHub Actions runner](https://github.com/actions/runner) on a BSD operating system using Mono. However, any attempt to run `bin/Runner.Listener.exe` (or any executable file for that matter) results in the `File does not contain a valid cil image` error message.

For what it's worth, I also attempted to test this on Ubuntu Linux (23.04) and I got the same error message.

### Reproduction Steps

1. Spin up Ubuntu or FreeBSD
2. Install Mono.

```
 # Ubuntu
apt install mono-runtime

# FreeBSD
pkg install -y mono
```

3. Download and unpack the runner:

```
wget https://github.com/actions/runner/releases/download/v2.308.0/actions-runner-win-x64-2.308.0.zip
unzip actions-runner-win-x64-2.308.0.zip
```

4. Run failing command:

```
mono bin/Runner.Listener.exe --version
```

### Expected behavior

```
$ mono bin/Runner.Listener.exe --version
2.308.0
```

### Actual behavior

```
$ mono bin/Runner.Listener.exe --version
Cannot open assembly 'bin/Runner.Listener.exe': File does not contain a valid CIL image.
```

### Regression?

I don't know.

#### Mono

```
$ mono --version
Mono JIT compiler version 6.8.0.105 (Debian 6.8.0.105+dfsg-3.3 Wed Dec 14 17:29:20 UTC 2022)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

#### Ubuntu

```
$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 23.04"
NAME="Ubuntu"
VERSION_ID="23.04"
VERSION="23.04 (Lunar Lobster)"
VERSION_CODENAME=lunar
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=lunar
LOGO=ubuntu-logo
$ uname -a
Linux wol-test 6.2.0-1010-azure #10-Ubuntu SMP Wed Aug 16 20:06:07 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jkotas** [comment]
GitHub Actions runner requires .NET 6. It won't work on Mono.

https://wiki.freebsd.org/.NET has summary of the .NET for FreeBSD project, including links to prebuilt binaries.

https://github.com/actions/runner/issues/385 is issue tracking FreeBSD support in github actions that lists some more options.
