### ISSUE TITLE
Consider adding an `AggregateBy` method to LINQ

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#91533]
## Background & Motivation

It is fairly common for LINQ users to want to calculate an aggregate for enumerables, grouped by a specific key. This is currently achievable using the `GroupBy` methods, however this approach is often inefficient as it forces intermediate `IGrouping` allocations. This is highlighted as the motivation of the [`CountBy` API proposal](https://github.com/dotnet/runtime/issues/77716).

`AggregateBy` is an extension of the existing `Aggregate` methods that lets users fold a source enumerable, grouped by key. It is a useful method that generalizes methods such as `GroupBy` and `CountBy`, but also works well for other applications. Similar APIs available in frameworks like Spark are called [`foldByKey`](https://spark.apache.org/docs/latest/api/python/reference/api/pyspark.RDD.foldByKey.html) and [`aggregateByKey`](https://spark.apache.org/docs/latest/api/python/reference/api/pyspark.RDD.aggregateByKey.html).

## API Proposal

```C#
namespace System.Linq;

public static partial class Enumerable
{
    public static IEnumerable<KeyValuePair<TKey, TAccumulate>> AggregateBy<TSource, TAccumulate, TKey>(
        this IEnumerable<TSource> source,
        TAccumulate seed,
        Func<TAccumulate, TSource, TAccumulate> func,
        Func<TSource, TKey> keySelector,
        IEqualityComparer<TKey>? keyComparer = null) where TKey : notnull;

    public static IEnumerable<KeyValuePair<TKey, TAccumulate>> AggregateBy<TSource, TAccumulate, TKey>(
        this IEnumerable<TSource> source,
        Func<TKey, TAccumulate> seed,
        Func<TKey, TAccumulate, TSource, TAccumulate> func,
        Func<TSource, TKey> keySelector, 
        IEqualityComparer<TKey>? keyComparer = null) where TKey : notnull;
}

public static partial class Queryable
{
    public static IQueryable<KeyValuePair<TKey, TAccumulate>> AggregateBy<TSource, TAccumulate, TKey>(
        this IQueryable<TSource> source,
        TAccumulate seed,
        Expression<Func<TAccumulate, TSource, TAccumulate>> func,
        Expression<Func<TSource, TKey>> keySelector,
        IEqualityComparer<TKey>? keyComparer = null) where TKey : notnull;

    public static IQueryable<KeyValuePair<TKey, TAccumulate>> AggregateBy<TSource, TAccumulate, TKey>(
        this IQueryable<TSource> source,
        Expression<Func<TKey, TAccumulate>> seed,
        Expression<Func<TKey, TAccumulate, TSource, TAccumulate>> func,
        Expression<Func<TSource, TKey>> keySelector, 
        IEqualityComparer<TKey>? keyComparer = null) where TKey : notnull;
}
```

### Implementing `LongCountBy`

```C#
static IEnumerable<KeyValuePair<TKey, long>> LongCountBy<TSource, TKey>(IEnumerable<TSource> source, Func<TSource, TKey> keySelector)
    => source.AggregateBy(seed: 0L, (count, _) => ++count, keySelector);
```

### Implementing `GroupBy`

```C#
static IEnumerable<KeyValuePair<TKey, List<TSource>>> GroupBy<TSource, TKey>(IEnumerable<TSource> source, Func<TSource, TKey> keySelector)
    => source.AggregateBy(seed: _ => new List<TSource>(), (_, group, element) => { group.Add(element); return group; }, keySelector);
```

### Calculating total scores by key

```C#
var data = new (string id, int score)[]
{
    ("0", 42),
    ("1", 5),
    ("2", 4),
    ("1", 10),
    ("0", 25),
};

data.AggregateBy(seed: 0, (totalScore, curr) => totalScore += curr.score, keySelector: entry => entry.id);
//(0, 67)
//(1, 15)
//(2, 4)
```

## Open Questions

We might want to consider the order of type parameters and delegates in the type signature. As proposed it follows the convention that `TKey` and the `keySelector` delegate go to the end of the method signature but perhaps that's not as natural here.

## Reference Implementation

```C#
public static IEnumerable<KeyValuePair<TKey, TAccumulate>> AggregateBy<TSource, TAccumulate, TKey>(
    this IEnumerable<TSource> source,
    TAccumulate seed,
    Func<TAccumulate, TSource, TAccumulate> func,
    Func<TSource, TKey> keySelector) where TKey : notnull
{
    using IEnumerator<TSource> enumerator = source.GetEnumerator();

    if (!enumerator.MoveNext())
    {
        yield break;
    }

    foreach (KeyValuePair<TKey, TAccumulate> entry in PopulateDictionary(enumerator))
    {
        yield return entry;
    }

    Dictionary<TKey, TAccumulate> PopulateDictionary(IEnumerator<TSource> enumerator)
    {
        var dict = new Dictionary<TKey, TAccumulate>();
        do
        {
            TSource value = enumerator.Current;
            TKey key = keySelector(value);
            ref TAccumulate? acc = ref CollectionsMarshal.GetValueRefOrAddDefault(dict, key, out bool exists);
            acc = func(exists ? acc! : seed, value);
        } while (enumerator.MoveNext());

        return dict;
    }
}
```

_Originally posted by @eiriktsarpalis in https://github.com/dotnet/runtime/issues/77716#issuecomment-1660855159_

**Comment by viceroypenguin** [comment]
I would suggest that the `seed` may be determined by the key, so I propose:
```cs
public static IEnumerable<KeyValuePair<TKey, TAccumulate>> AggregateBy<TSource, TKey, TAccumulate>(
	this IEnumerable<TSource> source,
	Func<TSource, TKey> keySelector,
	Func<TKey, TAccumulate> seedSelector,
	Func<TAccumulate, TKey, TSource, TAccumulate> accumulator)
```

**Comment by chrisoverzero** [comment]
> I would suggest that the seed may be determined by the key […]

What does this mean? Which `TKey` value would be passed to this function? Can you show an example of using this proposed signature?

**Comment by viceroypenguin** [comment]
@chrisoverzero Dummy example for how the method would be called:
```cs
var sum = Enumerable.Range(1, 100)
  .AggregateBy(
    keySelector: x => x % 10,
    seedSelector: k => k + 100,
    accumulator: (sum, key, src) => sum + src);
```

It's probably rare that the seed would need to be selected per key, but it would be simple to design for it and would help significantly in those cases.

**Comment by viceroypenguin** [comment]
@eiriktsarpalis Fair enough. 

Two more questions:
* Why put `func` parameter before `keySelector` parameter?
* Should this be an `IReadOnlyDictionary<,>` or similar, to match prompt behavior of `Aggregate`, similar to the discussion in #77716?

**Comment by eiriktsarpalis** [comment]
> Why put func parameter before keySelector parameter?

Because we tend to put the key selector delegate at the very end of a method signature in `*By` variants, but didn't give it much thought beyond that.

> Should this be an IReadOnlyDictionary<,> or similar, to match prompt behavior of Aggregate, similar to the discussion

Possibly, what ends up being used in `CountBy` will most likely influence the design here.

**Comment by eiriktsarpalis** [comment]
I've just updated the OP with a full-blown proposal and examples. Your feedback would be appreciated.

**Comment by viceroypenguin** [comment]
@eiriktsarpalis Thanks for updating the proposal. I like the overload option of using a static `seed` vs a dynamic one.

I would argue that the `keySelector` should be the first parameter in both overloads. I know that `keySelector` is the last parameter in some `*By` variants, but I think this is the wrong way to look at it. Instead, I would say that it is, in every operator, the first non-sequence parameter.

* `GroupBy`: first parameter
* `CountBy`: first parameter
* `MaxBy`/`MinBy`: first parameter
* `OrderBy`/`ThenBy`: first parameter
* `UnionBy`: sequence, then `keySelector`
* `IntersectBy`: sequence, then `keySelector`
* `DistinctBy`: sequence, then `keySelector`
* `ExceptBy`: sequence, then `keySelector`

In the most relevant similarity (`GroupBy`), it is the first parameter, which leads naturally into following parameters which answer: "what are we doing with the key?", "what are we doing with the group?", etc. 

In the set-based `*By` variants, the parameters follow an order: bind two sequences together, then define how to identify the key that binds the sequences together. This is also a natural read, but is less relevant, because there is no need for a follow-up parameter after `keySelector`. 

So, from a reading standpoint, the most natural order of parameters to me would go: 1. select a key, 2. define a seed from the key (or use a static key), 3. accumulate based on the group selected by the key. 

I welcome any comments to the contrary, as this is just my opinion on the matter.

**Comment by viceroypenguin** [comment]
Also, if we are allowing more than one overload, does it make sense to offer a `resultSelector` overload as well?

**Comment by eiriktsarpalis** [comment]
> Also, if we are allowing more than one overload, does it make sense to offer a `resultSelector` overload

The existing overloads have full control over the aggregate and how it is folder, why add another transform at the end? Even if it were necessary in certain scenaria, it seems to me that chaining it with a `Select` call is probably preferable.

**Comment by manandre** [comment]
I am a bit late here as it is already approved, but why don't we have an overload without the seed as in the existing `Aggregate` Linq operator?

**Comment by viceroypenguin** [comment]
> I am a bit late here as it is already approved, but why don't we have an overload without the seed as in the existing Aggregate Linq operator?

Not providing the `seed` would require that consumers specify all types for the generic method, in order to specify the `TAccumulate` type. This would reduce usability in many cases (anonymous types, long tuples, etc.).

**Comment by manandre** [comment]
> > I am a bit late here as it is already approved, but why don't we have an overload without the seed as in the existing Aggregate Linq operator?
> 
> Not providing the `seed` would require that consumers specify all types for the generic method, in order to specify the `TAccumulate` type. This would reduce usability in many cases (anonymous types, long tuples, etc.).

I was thinking about this kind of overload, without `TAccumulate`:
```cs
public static IEnumerable<KeyValuePair<TKey, TSource>> AggregateBy<TSource, TSource, TKey>(
    this IEnumerable<TSource> source,
    Func<TSource, TKey> keySelector,
    Func<TSource, TSource, TSource> func,
    IEqualityComparer<TKey>? keyComparer = null) where TKey : notnull;
```

**Comment by eiriktsarpalis** [comment]
> I was thinking about this kind of overload

This is a reducer method, so should most probably be called `ReduceBy` rather than `AggregateBy`.

**Comment by manandre** [comment]
The [CountBy implementation](https://github.com/dotnet/runtime/pull/91507) has just been merged. It is then time to go to the next level!
@eiriktsarpalis I can handle the implementation for `AggregateBy` if you agree.

**Comment by eiriktsarpalis** [comment]
@manandre go for it 👍
