### ISSUE TITLE
[iOS][tvOS] Building tests fails with "Trimming assemblies requires .NET Core 3.0 or higher"

### ISSUE THREAD

**Issue by simonrozsival** [dotnet/runtime#91535]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=394436
Build error leg or test failing: Build / tvos-arm64 Release AllSubsets_Mono_RuntimeTests / Build Tests
Pull request: https://github.com/dotnet/runtime/pull/91520

The last scheduled CI run of `runtime-extra-platforms` on `main` built correctly on Aug 31, 2023 at 11:00 AM GMT+2 (`ff2de363f393f2270d5752eeb3db345fcf770c5c`, https://dev.azure.com/dnceng-public/public/_build/results?buildId=391626&view=results).

The next scheduled CI run on Aug 31, 2023 at 11:00 PM GMT+2 failed (`cd4a25371c721f83be3fa3367be6cb143709dadc`, https://dev.azure.com/dnceng-public/public/_build/results?buildId=392353&view=logs&j=59056779-c81b-5864-b8d0-ad352b49f318&t=8f67da1d-4989-5758-2e5c-fa15a4fd6276) and CI has been failing since.

Affected pipelines:
- runtime-extra-platforms
- runtime-ioslike

## Error Message

```json
{
  "ErrorMessage": "error NETSDK1124: Trimming assemblies requires .NET Core 3.0 or higher.",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=394436
**Error message validated:** `error NETSDK1124: Trimming assemblies requires .NET Core 3.0 or higher.`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 9/4/2023 9:41:44 AM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[397682](https://dev.azure.com/dnceng-public/public/_build/results?buildId=397682)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/397682/logs/2378)|dotnet/runtime#91468|
|[397525](https://dev.azure.com/dnceng-public/public/_build/results?buildId=397525)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/397525/logs/957)||
|[397233](https://dev.azure.com/dnceng-public/public/_build/results?buildId=397233)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/397233/logs/713)|dotnet/runtime#91684|
|[397052](https://dev.azure.com/dnceng-public/public/_build/results?buildId=397052)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/397052/logs/704)|dotnet/runtime#91458|
|[397028](https://dev.azure.com/dnceng-public/public/_build/results?buildId=397028)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/397028/logs/671)|dotnet/runtime#91290|
|[396849](https://dev.azure.com/dnceng-public/public/_build/results?buildId=396849)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/396849/logs/846)|dotnet/runtime#91019|
|[396755](https://dev.azure.com/dnceng-public/public/_build/results?buildId=396755)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/396755/logs/657)|dotnet/runtime#91660|
|[396634](https://dev.azure.com/dnceng-public/public/_build/results?buildId=396634)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/396634/logs/784)||
|[396207](https://dev.azure.com/dnceng-public/public/_build/results?buildId=396207)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/396207/logs/659)|dotnet/runtime#91468|
|[396162](https://dev.azure.com/dnceng-public/public/_build/results?buildId=396162)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/396162/logs/1710)|dotnet/runtime#91468|
|[396111](https://dev.azure.com/dnceng-public/public/_build/results?buildId=396111)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/396111/logs/938)||
|[395837](https://dev.azure.com/dnceng-public/public/_build/results?buildId=395837)|dotnet/runtime|Run Trimming Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/395837/logs/68)|dotnet/runtime#91468|
|[395833](https://dev.azure.com/dnceng-public/public/_build/results?buildId=395833)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/395833/logs/657)|dotnet/runtime#91468|
|[395791](https://dev.azure.com/dnceng-public/public/_build/results?buildId=395791)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/395791/logs/607)|dotnet/runtime#91458|
|[395438](https://dev.azure.com/dnceng-public/public/_build/results?buildId=395438)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/395438/logs/696)|dotnet/runtime#91458|
|[395416](https://dev.azure.com/dnceng-public/public/_build/results?buildId=395416)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/395416/logs/819)||
|[395186](https://dev.azure.com/dnceng-public/public/_build/results?buildId=395186)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/395186/logs/792)||
|[394754](https://dev.azure.com/dnceng-public/public/_build/results?buildId=394754)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/394754/logs/673)|dotnet/runtime#91116|
|[394654](https://dev.azure.com/dnceng-public/public/_build/results?buildId=394654)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/394654/logs/844)||
|[394471](https://dev.azure.com/dnceng-public/public/_build/results?buildId=394471)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/394471/logs/750)||
|[394436](https://dev.azure.com/dnceng-public/public/_build/results?buildId=394436)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/394436/logs/106)|dotnet/runtime#91520|
|[394347](https://dev.azure.com/dnceng-public/public/_build/results?buildId=394347)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/394347/logs/763)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|8|22|22|

**Comment by simonrozsival** [comment]
cc @akoeplinger @ViktorHofer @sbomer @vitek-karas

**Comment by ViktorHofer** [comment]
cc @sbomer @agocke @vitek-karas

**Comment by vitek-karas** [comment]
@sbomer - there's a somewhat weird case here. The project gets `PublishTrimmed=true` - because we want to trim all executables in the subtree. But the project is a library, so it actually won't be trimmed - this alone is not a good reason since `PublishAot=true` has the same effect and that can work on a library. But we don't publish the project, we just build it (publishing a library is effectively an undefined operation for SDK in lot of situations). In the end by normal logic, it should not matter that trimming doesn't work on `netstandard2.0` library, if nobody tried to publish it.

That said, this is something few people will run into - `PublishTrimmed` is expected to be set on per-project basis, not globally for entire subtrees. So this is probably not something we need to fix (and the fix is problematic, SDK has a hard time differentiating between normal build and publish for such a core piece as "resolve framework references").

**Comment by vitek-karas** [comment]
Side question - how does one get a binlog for the internal MSbuild execution which happens during `RestoreTaskEx`? Normal `/bl` is useless unfortunately:
![image](https://github.com/dotnet/runtime/assets/10670590/5f569400-57cd-46e6-9202-fad6be2753a7)

It seems to propagate most properties inside automagically (unlike normal tasks which take parameters but don't react to MSBuild properties inside the task).

**Comment by kotlarmilos** [comment]
> In the end by normal logic, it should not matter that trimming doesn't work on `netstandard2.0` library, if nobody tried to publish it.

I agree. Should we open an issue in the `msbuild` or `sdk` repo?

**Comment by vitek-karas** [comment]
That would in the sdk repo, but the priority of this is so low I doubt we'll bother with it. If we some day actually define a behavior for "trimming libraries" we would actually want the current behavior, so it's not that bad to keep it :-)

I think the cleaner solution would be to actually define "publish for libraries", even if it means "invalid" - but that's a very complex problem to solve currently (mostly we don't know if somebody has dependencies on the existing semi broken behavior).
