### ISSUE TITLE
Expose System.SizedReference in coreclr

### ISSUE THREAD

**Issue by KKhurin** [dotnet/runtime#9153]
This API existed back in the desktop .NET framework and System.Runtime.Caching has a dependency on SizedRef to implement a feature allowing to limit cache size. This is a somewhat unique cache feature not found in many other cache implementations and it has a widespread usage in desktop .NET application. While there is a number of possible approaches to implement this functionality, the desktop framework approach using SizedRef worked well for its purpose. 

The actual implementation of the SizedRef is still in CoreClr GC code – only mscorlib layer got removed so adding it back should be relatively simple from API design standpoint.

**Comment by stephentoub** [comment]
Closing as dup of https://github.com/dotnet/runtime/issues/24200.
