### ISSUE TITLE
Is there a way to hot reload a particular .wasm module after the runtime already initialised? 

### ISSUE THREAD

**Issue by socreative** [dotnet/runtime#91539]
I am incorporating the dotnet.js runtime in the Angular app and we have scenarios when I need to reload a couple of .WASM modules after the dotnet.js runtime has already loaded and initialised. Is there a clean way of doing that with dotnet.js?

**Comment by maraf** [comment]
cc @lambdageek

**Comment by lambdageek** [comment]
> Is there a clean way of doing that with dotnet.js?

Short answer: no

Longer answer: yes, kind of, but we don't ship all the pieces.  Basically the way hot reload for .NET works is that you don't just ship brand new updated versions of the .dlls (or on webassembly .wasm) files. you have to ship "EnC deltas".  The only way to create "EnC deltas" is using the Roslyn C# compiler running in some kind of tooling like Visual Studio or in `dotnet watch`, and in the browser you need a hot reload agent to receive the EnC deltas and apply them (using [`System.Reflection.Metadata.MetadataUpdater.ApplyUpdate`](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.metadata.metadataupdater.applyupdate?view=net-7.0#system-reflection-metadata-metadataupdater-applyupdate(system-reflection-assembly-system-readonlyspan((system-byte))-system-readonlyspan((system-byte))-system-readonlyspan((system-byte))))).  The only hot reload agent we ship is part of BlazorWASM.

In principle you can build your own version of all the tooling (for example by consuming the Roslyn APIs using [hotreload-utils](https://github.com/dotnet/hotreload-utils) or by hacking `dotnet watch` to support WASM non-Blazor projects), but in practice that's a ton of work.

**Comment by socreative** [comment]
@lambdageek Thanks for you reply. 
I have another question then. Is it possible to completely destroy the dotnet runtime and reinitialise without refreshing the browser page?

**Comment by lambdageek** [comment]
> @lambdageek Thanks for you reply. I have another question then. Is it possible to completely destroy the dotnet runtime and reinitialise without refreshing the browser page?

Have we tried that, @maraf? Everything hangs off of the `getDotnetRuntime(n: number): DotnetModule` global, right? If you re-run the startup stuff you'll get runtime `n+1`.  Is there a way to clear a previous one?  Does it clean up after itself if the wasm process shuts down?

**Comment by maraf** [comment]
That is possible since all the state is in es6 modules.

**Comment by maraf** [comment]
> Have we tried that, @maraf? Everything hangs off of the `getDotnetRuntime(n: number): DotnetModule` global, right? If you re-run the startup stuff you'll get runtime `n+1`. Is there a way to clear a previous one? Does it clean up after itself if the wasm process shuts down?

I forgot about `getDotnetRuntime`. I'll check it.

We tests for starting multi runtime and checking that they don't interfere. I don't check proper clean up there yet and it's a room for improvement.

**Comment by maraf** [comment]
> I forgot about `getDotnetRuntime`. I'll check it.

Unfortunatelly, the .NET runtime remains in the list forever. We don't have a way to remove it from there yet.

**Comment by pavelsavara** [comment]
> Unfortunatelly, the .NET runtime remains in the list forever. We don't have a way to remove it from there yet.

Not really, there is weak reference. 

I think that in order to replace dotnet module sucesfully you have to 
- use dynamic `import("dotnet.js?instance=aa729821-af37-4899-b866-b839840a143a")` and use different query string for each instance
- get rid of all the references to it. 

Second point may be difficult. For example any event handlers leading chain of functions into `JSExport` or any of it's APIs could hold it alive.

To at least free most of the large objects and wasm memory, I'm attempting to implement `RuntimeAPI.dispose()` [here](https://github.com/dotnet/runtime/pull/92480) which will break some of the links inside dotnet.

**Comment by pavelsavara** [comment]
Even with quite explicit cleanup on my branch, something is holding the wasm memory alive.

Firefox
![image](https://github.com/dotnet/runtime/assets/271576/52d85e03-db45-4024-80de-95519686181e)

Chrome
![image](https://github.com/dotnet/runtime/assets/271576/81bc78b9-3222-4c4d-8404-4465ac6f61a4)
