### ISSUE TITLE
[browser] Unnecessary browser and node calls breaking usage in restricted environments

### ISSUE THREAD

**Issue by elringus** [dotnet/runtime#91558]
I'm trying to build .NET 8 library for VS Code [web extension](https://code.visualstudio.com/api/extension-guides/web-extensions), where neither browser APIs (window/document), nor node modules are available. Previously (in .NET 6) I had to strip generated JS wrapper from various unconditional usages of such APIs. I hoped in .NET 8 it's solved (and I can see lots of changes in this direction), but unfortunately there are stilll issues. For example, `createDotnetRuntime` function has following (from bundled library sources, so it's bit mangled):

![63881f3024a9af0730ba65c668c811cb](https://github.com/dotnet/runtime/assets/2056864/95c61790-302f-46c0-98b9-e4aa34167239)

`document` is undefined in VS Code and `require('url')` causes exception. I'm injecting all the requires resources (runtime.wasm, dotnet.runtime.js, etc) via the assets in config, so no IO should be required to boot the runtime.

Is it possible to guard browser/node-specific calls like this for .NET 8?

# The Specific Offenders in .NET 8

Here is the link to the patch I'm using to strip all the offenders: https://github.com/elringus/bootsharp/blob/main/src/cs/Bootsharp.Publish/Pack/ModulePatcher/InternalPatcher.cs After the patch, bundlers are only complaining about `module` and `process` unresolved externals (tested with webpack, rollup, esbuild, vite) and the bundled runtime is working in browsers, node, deno, bun and VS Code web extensions.

Regarding `module` and `process` — would be optimal to guard them as well, though I wasn't able to find a straightforward way to do that (conditional usage still trigger bundlers). As a workaround, I'm marking them as global (eg, `-g process,module` in rollup), which seem to satisfy the bundlers.

**Comment by Elringus** [comment]
Trying to find the culprit in the sources, but stuck here: https://github.com/dotnet/runtime/blob/main/src/mono/wasm/runtime/es6/dotnet.es6.lib.js#L60

There are no other " _scriptDir" vars in the codebase, so it must be it, but not sure where `require('url')` comes from.

**Comment by Elringus** [comment]
So I was able to pin-point 3 offending cases, 2 of them are in `dotnet.native.js`, which I assume is auto-generated by emscripten (as I wasn't able to find it in the dotnet codebase):

# dotnet.native.js:3

![686b26d9205b42a8a151113411d9f5f7](https://github.com/dotnet/runtime/assets/2056864/8446b7bf-2a96-4cf9-ab03-cb3cbaf308ec)

# dotnet.native.js:780

![f2074e91b47b11687d5fba82ad013532](https://github.com/dotnet/runtime/assets/2056864/73160eb9-ce78-4084-8f03-f3da54d0ba02)

# dotnet.js (comes from [polyfill.ts](https://github.com/dotnet/runtime/blob/main/src/mono/wasm/runtime/loader/polyfills.ts#L42))

![47c12e5bdda1a6f536d37b3ee6c68eae](https://github.com/dotnet/runtime/assets/2056864/31f8e567-d48d-42e4-9209-ae7779fedf52)

When replacing all 3 of those `import.meta.url` -> `"file:/"`, the runtime starts up in VS Code web extension fine. Though it exits immedeintly after invoking C#'s `Program.Main()`, but I've already reported this via #91511.

Any chance these issues can be solved in .NET 8 or it's too late now? @pavelsavara

**Comment by radical** [comment]
cc @pavelsavara @maraf

**Comment by pavelsavara** [comment]
`require` in the emscripten code is quite annoying. 
Perhaps it would go away if you pass
```
  <PropertyGroup>
     <EmccEnvironment>web,worker</EmccEnvironment>
  </PropertyGroup>
```
But that would make it node incompatible.

For the `import.meta.url` I thought we solved it by https://github.com/dotnet/runtime/pull/90392
We are not going back to CJS.

**Comment by Elringus** [comment]
> But that would make it node incompatible.

I hope we can me it work in both both node, browser and restricted environments w/o special builds for each. This is already working on my end with those 3 modifications I've mentioned above.

> For the import.meta.url I thought we solved it by https://github.com/dotnet/runtime/pull/90392

Yeah, that was essential, but not enough for VS Code, unfortunately (sorry I wasn't able to test at the time, had to rewrite the whole library for .NET 8 and new interop). If those 3 calls to `import.meta` and `new URL` could be guarded somehow, it would solve the issue completely. The workaround with stripping them on build post-process will work for the time being.

**Comment by pavelsavara** [comment]
> Yeah, that was essential, but not enough for VS Code

Could you please point me to more details about VS Code constraints ? Documentation ?

**Comment by Elringus** [comment]
Here: https://code.visualstudio.com/api/extension-guides/web-extensions#migrate-extension-with-code

Due to V8 cache not available on node (and dotnet runtime requiring it), we also have to use the web format for standalone VS Code environment. Basically, we can't use any import/require, except the pre-defined `vscode`, which provide limited VS Code API. Also, no window/documents, etc browser-specific stuff.

**Comment by pavelsavara** [comment]
> Due to V8 cache not available on node (and dotnet runtime requiring it)

Cache API ? This should disable it.

```
dotnet
    .withConfig({
        cacheBootResources: false,
    })
```

**Comment by Elringus** [comment]
Presumably it's something about v8 code caching: https://v8.dev/blog/code-caching I didn't really investigate it properly. Just had `invalid host defined options` error when attempted to run the extension in node and prompt googling showed that it's because of the cache API not available in modules. The extension I'm working on works fine in web anyway, so I don't really need it.

**Comment by pavelsavara** [comment]
Could you please update the top level description and list specific offenders ? That would make at least some of them more actionable.

**Comment by Elringus** [comment]
Done. Thanks for looking into this!

**Comment by pavelsavara** [comment]
Migrated into https://github.com/dotnet/runtime/issues/80045
