### ISSUE TITLE
Request for Extension Methods for Char in .NET Platform

### ISSUE THREAD

**Issue by SaeedMolaiy** [dotnet/runtime#91573]
### Background and motivation

**Problem:**
Currently, in the .NET platform, there are no extension methods available for the `char` data type, such as `ToLower` or `ToUpper`, which are commonly found for the `string` data type. This omission makes working with `char` values less intuitive and less consistent with the usage of `string` methods.

**Suggested Solution:**
I propose that extension methods for the `char` data type be added to the .NET platform to improve the consistency and ease of use for developers. Specifically, we should have extension methods like `ToLower` and `ToUpper` for `char` objects, similar to what we have for `string` objects. This would make code more readable and maintainable when dealing with character manipulation.

**Example:**
With the introduction of extension methods for `char`, developers could write code like this:

```csharp
char myChar = 'A';
char lowerChar = myChar.ToLower(); // This currently doesn't work, but we want it to.
```

**Benefits:**
1. Improved code readability: Extension methods would make it clear and consistent when working with character casing.

2. Reduced cognitive load: Developers wouldn't have to remember the separate `char.ToLower` and `char.ToUpper` methods; they could use familiar extension method syntax.

3. Enhanced developer productivity: This change would streamline code and reduce the need for extra documentation or comments.

**Implementation Details:**
The implementation could involve adding new extension methods to the `System` or another appropriate namespace that extends the functionality of the `char` data type.

Contributing to the Implementation:
I'm willing to contribute to the implementation of these extension methods if it's feasible and aligns with the .NET platform's development guidelines. If there's an interest in pursuing this enhancement, please let me know how I can assist in the process.

I believe this enhancement would greatly benefit the .NET developer community by simplifying common character manipulation tasks. Thank you for considering this proposal, and I look forward to seeing it implemented in a future release of the .NET platform.

### API Proposal

```csharp
namespace System
{
    public static class CharExtensions
    {

        /// <summary>
        /// Converts the specified character to lowercase using the invariant culture.
        /// </summary>
        /// <param name="c">The character to convert to lowercase.</param>
        /// <returns>The lowercase equivalent of the character using the invariant culture.</returns>
        public static char ToLower(this char c)
        {
            // Implementation logic for converting 'c' to lowercase using the invariant culture.
            // Example implementation:
            // return char.ToLowerInvariant(c);
        }

        /// <summary>
        /// Converts the specified character to uppercase using the invariant culture.
        /// </summary>
        /// <param name="c">The character to convert to uppercase.</param>
        /// <returns>The uppercase equivalent of the character using the invariant culture.</returns>
        public static char ToUpper(this char c)
        {
            // Implementation logic for converting 'c' to uppercase using the invariant culture.
            // Example implementation:
            // return char.ToUpperInvariant(c);
        }

        /// <summary>
        /// Converts the specified character to lowercase using the specified culture.
        /// </summary>
        /// <param name="c">The character to convert to lowercase.</param>
        /// <param name="culture">The culture-specific information to use for casing rules.</param>
        /// <returns>The lowercase equivalent of the character.</returns>
        public static char ToLower(this char c, CultureInfo culture)
        {
            // Implementation logic for converting 'c' to lowercase using the specified culture.
            // Example implementation:
            // return char.ToLower(c, culture);
        }

        /// <summary>
        /// Converts the specified character to uppercase using the specified culture.
        /// </summary>
        /// <param name="c">The character to convert to uppercase.</param>
        /// <param name="culture">The culture-specific information to use for casing rules.</param>
        /// <returns>The uppercase equivalent of the character.</returns>
        public static char ToUpper(this char c, CultureInfo culture)
        {
            // Implementation logic for converting 'c' to uppercase using the specified culture.
            // Example implementation:
            // return char.ToUpper(c, culture);
        }
    }
}
```

### API Usage

```csharp
char myChar = 'A';
char lowerChar = myChar.ToLower(); 
```

**Comment by huoyaoyuan** [comment]
This isn't necessary to be extension method. It can just be instance method of `char`.

**Comment by SaeedMolaiy** [comment]
> This isn't necessary to be extension method. It can just be instance method of `char`.

I agree. It doesn't necessarily have to be an extension method; it can simply be an instance method of the 'char'

**Comment by tarekgh** [comment]
I am not seeing this is adding any value here. Writing `Char.ToLower(c)` is clear in reading and understandable. The new method is not saving much writing either. I am going to close this and we can watch if we see more demand on this request in the future to consider it. 

Related issue https://github.com/dotnet/runtime/issues/90999
