### ISSUE TITLE
Unable to run app as administrator at runtime with runas verb

### ISSUE THREAD

**Issue by sancheolz** [dotnet/runtime#91574]
### Description

I want to ask for administrator permissions at runtime with runas verb in my application.

### Reproduction Steps

Run this code
```cs
using System.Diagnostics;
using System.Reflection;

var processInfo = new ProcessStartInfo
{
    Verb = "runas"
};
var uri = new Uri(Assembly.GetExecutingAssembly().GetName().CodeBase);
processInfo.FileName = uri.LocalPath;
processInfo.UseShellExecute = false;
processInfo.RedirectStandardError = true;
Console.WriteLine("starting '{0}'", uri.LocalPath);
var process = Process.Start(processInfo); 
var stream = process.StandardError;
Console.WriteLine(stream.ReadToEnd());
process.WaitForExit();
```

project file
```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

</Project>
```

### Expected behavior

My application will start with administrator rights.

### Actual behavior

My application did not start with administrator rights and now the following error is in stdErr
`Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.`

### Configuration

.NET SDK (reflecting any global.json):
 Version:   6.0.310
 Commit:    99a8aa0f90

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.310\

global.json file:
  Not found

Host:
  Version:      6.0.15
  Architecture: x64
  Commit:       5edef4b20b

.NET SDKs installed:
  5.0.416 [C:\Program Files\dotnet\sdk]
  6.0.310 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jeffschwMSFT** [comment]
.NET Core requires a host to run (unlike .NET Framework).  The code both has an issue when choosing what application to run.

```
var uri = new Uri(Assembly.GetExecutingAssembly().GetName().CodeBase);
```
CodeBase will return the .NET Core entry point assembly yourapp.dll where as the host is yourapp.exe.  

Once that is addressed, you can validate if the runas verb is working as you expect.

**Comment by sancheolz** [comment]
@jeffschwMSFT Thank you.
This is working solution for me. Also `UseShellExecute` must be set to true.

```cs
using System.Diagnostics;
using System.Reflection;
using System.Security.Principal;

WindowsPrincipal pricipal = new WindowsPrincipal(WindowsIdentity.GetCurrent());
if (pricipal.IsInRole(WindowsBuiltInRole.Administrator))
{
    Console.WriteLine("IsAdmin");
    return;
}

Console.WriteLine("IsGuest");

var processInfo = new ProcessStartInfo
{
    Verb = "runas"
};
var uri = new Uri(Assembly.GetExecutingAssembly().GetName().CodeBase);
var filename = uri.LocalPath.Replace(".dll", ".exe");
processInfo.FileName = filename;
processInfo.UseShellExecute = true;
Console.WriteLine("starting '{0}'", filename);
var process = Process.Start(processInfo);
process.WaitForExit();
```
