### ISSUE TITLE
Add Support for Saving Files with Progress Tracking in C#/.NET

### ISSUE THREAD

**Issue by SaeedMolaiy** [dotnet/runtime#91575]
### Background and motivation

I would like to suggest the addition of a feature to the .NET platform that allows developers to save files with progress tracking, including the percentage of completed progress. Currently, there is no built-in mechanism in .NET for tracking the progress of file-saving operations, which can be valuable in various scenarios, such as large file transfers or batch processing.

**Proposed Solution:**
I propose adding a new API or extending existing file I/O methods in .NET that would enable developers to track the progress of file-saving operations. This feature could include callbacks or events to report the progress as a percentage and allow developers to update their user interfaces accordingly.

**Use Case:**
An example use case for this feature could be a file transfer application where users want to see the progress of uploading or downloading files in real-time. Another use case could be a file backup utility that provides feedback on the progress of copying files to a remote location.

**Possible Implementation:**

One possible approach to implementing this feature is to introduce a new class or method in the .NET libraries that allows developers to pass a progress callback or subscribe to events or a simple method to return percentage of completed progress. 

**Implementation (Optional):**
I am willing to implement this feature myself if it aligns with the goals and guidelines of the .NET platform. I would appreciate any guidance or feedback from the maintainers of the project on how to proceed with the implementation.

**Additional Information:**
- This feature would enhance the usability of the .NET platform in scenarios involving file I/O and long-running file operations.
- It could improve the user experience of applications that deal with file management.
- It could also support saving multiple files.

Thank you for considering this feature request. I look forward to your feedback and guidance on how to proceed with its implementation.

### API Proposal

```csharp
using System;
using System.IO;
using System.Threading.Tasks;

public class FileSaveProgressEventArgs : EventArgs
{
    public double ProgressPercentage { get; }

    public FileSaveProgressEventArgs(double progressPercentage)
    {
        ProgressPercentage = progressPercentage;
    }
}

public class TrackableFileSaver
{
    public event EventHandler<FileSaveProgressEventArgs> ProgressChanged;

    public async Task SaveFileWithProgressAsync(string filePath, byte[] data)
    {
        //saving logic here, its just demo
    }

    protected virtual void OnProgressChanged(double progressPercentage)
    {
        ProgressChanged?.Invoke(this, new FileSaveProgressEventArgs(progressPercentage));
    }
}
```

### API Usage

```csharp
//its just a demo
public class Program
{
    public static async Task Main()
    {
        var fileSaver = new TrackableFileSaver();

        fileSaver.ProgressChanged += (sender, e) =>
        {
            Console.WriteLine($"Progress: {e.ProgressPercentage}%");
        };

        byte[] dataToSave = // Your file data here

        // Example usage:
        var filePath = "example.txt";

        await fileSaver.SaveFileWithProgressAsync(filePath, dataToSave);

        Console.WriteLine("File saved successfully.");
    }
}
```

**Comment by Zintom** [comment]
This sounds like a very specific use case, the BCL provides all the necessary tooling to create this yourself using FileStream and Delegates.

**Comment by SaeedMolaiy** [comment]
> This sounds like a very specific use case, the BCL provides all the necessary tooling to create this yourself using FileStream and Delegates.

Yes, you're correct, but .NET has very simple built-in methods like ToLower. So, why shouldn't we add this feature for every developer at all levels to use when we can easily implement ToLower ourselves?

**Comment by Jozkee** [comment]
I agree with @Zintom, I don't think would belongs in the BCL but instead be publicly offered as a NuGet package.

**Comment by huoyaoyuan** [comment]
File is a specific version of stream, and saving is a specific operation with progress. Saving byte array is also a specific way to save. For example, `CopyTo` can be used to save network stream to file.

`EventArgs` is way too heavy. The existing `IProgress<T>` is also somehow heavy.
