### ISSUE TITLE
Using the profiler or metadata APIs is it possible to know whether runtime was trimmed?

### ISSUE THREAD

**Issue by kalikin** [dotnet/runtime#91598]
Is there a way, using unmanaged [profiler](https://learn.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/) or  [metada](https://learn.microsoft.com/en-us/dotnet/framework/unmanaged-api/metadata/) API, to know whether runtime was trimmed. Specifically the `System.Private.CoreLib.dll` assembly.

I know you can inspect the metadata and find out from there. But is there something that tells your right away if trimming was used, even if nothing was trimmed in the process.

In our use case we need to simply disable a profiling mode which relies on the untrimmed metadata.

**Comment by MichalStrehovsky** [comment]
There isn't such mechanism. The profiler should instead check if the things it needs are present. The application could be trimmed even if CoreLib wasn't touched at all.

**Comment by vitek-karas** [comment]
There's been a discussion on this topic in the past here: https://github.com/dotnet/linker/issues/1194

But in general I think the problem @MichalStrehovsky mentions still exists. For this to be useful there would have to be an app-wide information whether the app, or any part of it was modified from the original. But defining what that actually means and how it actually behaves is difficult. For example - is Ready2Run a modification or not? For some apps it is (changed performance behavior), for others it's not.

There are other extreme considerations for the use cases similar to yours - for example, what if the app is self-contained and is built with some modified version of CoreLib - it wasn't trimmed, but somebody modified it some other way. The profiler might still not work - how would you detect that?

**Comment by kalikin** [comment]
Thank you for your answers. Will continue to inspect the metadata to decide if a certain profiler feature is applicable.

**Comment by MichalStrehovsky** [comment]
It's also possible to force include an assembly into the app at build time and preserve all of it's contents.

E.g. might be possible to ask people to add the instrumentation assembly to the app and the instrumentation assembly is guaranteed to be not trimmed and a profiler could generate calls into it. But it is a different workflow from just dropping a completely new assembly into the app at runtime so I don't know if it would work for you.
