### ISSUE TITLE
Regressions in System.Memory.Span<Char>

### ISSUE THREAD

**Issue by cincuranet** [dotnet/runtime#91619]
Looks like `System.Memory.Span<Char>IndexOfValue` recently regressed on AMD (only) on Windows x64. [Here's a link](https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACn1UTXObMBC9+1foBrSYAHGcxCmZcdxDMp00aXDbQ6eTUWBtlOqDkURtOv3xXSB1wGk6XMTue0/7pF1xsOTegrEkIU5aGwsiuAahdB2kJZXvFgXV58GVzGF7s/pCeQVuyn7BjBxFseecjXjDN5Zqu2QCUCSnFiwu3TiMD8fhdBweLcPTWXw8m0yCaTSNJ9Hx2zCchaHXsdNCafuRCjAdG78HDu5dJT9VUMHMWM3k2iftX4N7injk28j5ymSuNiaIwmAu8ukkiMPLOLjZ8OAW9MrxibNhcrydTsZU5I7/D0J0ehkFS7YG/YLCpAXekD4/VNJWqB1OgrkWyPoL5QilTQT1S9DQR8cNut1jKM9fkY9OXidEJ0NK38auoCCtng10VRmM0Az6lBT0TxQf+tjs+xh9PxtdA0U+CJDWjH6TTYEJclExnt9BqUiCHZMrK8EeaDSAd+4MUReayqxocRpW5qAAmpsDQZl8BuI1L5RcsXWlqWVKGgx8wEpblmCZVnuic50VzEJmsbIWhOfiEKVfybam/rPdQomS8XZ9rfKOYxlC82fSEsejabwm2c7KILNQaB70UpVPq12WGRClrd0Xm96u1bIuwRs6awYotXj+5Lw3UogxlRBU49QRqtf3gm7dFt+U5JM3Hnmo9wT8Xcl+47idHNQptXrEo3kBvgNTcZtoLD93e5a6+By7ha5R6dAbqD0qJskPvKqESQm6P8dK9oEa8PXQpGmQDF8TSzbMFsQ1oBmYZDfWPtlmildCJvv11V3cJF1BCLTMckic9/jWYPfWT7/tC+RK4zUxU3JmE7oF4/0Bu/QbXOQEAAA=) to ADX query.

Taken from https://github.com/dotnet/perf-autofiling-issues/issues/21342.

**Comment by adamsitnik** [comment]
The link to ADX query is missing, but the referenced issue [has it](https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACn1UTXObMBC9+1foBrSYAHGcxCmZcdxDMp00aXDbQ6eTUWBtlOqDkURtOv3xXSB1wGk6XMTue0/7pF1xsOTegrEkIU5aGwsiuAahdB2kJZXvFgXV58GVzGF7s/pCeQVuyn7BjBxFseecjXjDN5Zqu2QCUCSnFiwu3TiMD8fhdBweLcPTWXw8m0yCaTSNJ9Hx2zCchaHXsdNCafuRCjAdG78HDu5dJT9VUMHMWM3k2iftX4N7injk28j5ymSuNiaIwmAu8ukkiMPLOLjZ8OAW9MrxibNhcrydTsZU5I7/D0J0ehkFS7YG/YLCpAXekD4/VNJWqB1OgrkWyPoL5QilTQT1S9DQR8cNut1jKM9fkY9OXidEJ0NK38auoCCtng10VRmM0Az6lBT0TxQf+tjs+xh9PxtdA0U+CJDWjH6TTYEJclExnt9BqUiCHZMrK8EeaDSAd+4MUReayqxocRpW5qAAmpsDQZl8BuI1L5RcsXWlqWVKGgx8wEpblmCZVnuic50VzEJmsbIWhOfiEKVfybam/rPdQomS8XZ9rfKOYxlC82fSEsejabwm2c7KILNQaB70UpVPq12WGRClrd0Xm96u1bIuwRs6awYotXj+5Lw3UogxlRBU49QRqtf3gm7dFt+U5JM3Hnmo9wT8Xcl+47idHNQptXrEo3kBvgNTcZtoLD93e5a6+By7ha5R6dAbqD0qJskPvKqESQm6P8dK9oEa8PXQpGmQDF8TSzbMFsQ1oBmYZDfWPtlmildCJvv11V3cJF1BCLTMckic9/jWYPfWT7/tC+RK4zUxU3JmE7oF4/0Bu/QbXOQEAAA=)

It seems that the benchmark is back to the previous level for arm64:

![image](https://github.com/dotnet/runtime/assets/6011991/6865e5a2-7591-4cec-9f31-60b5df5cd032)

But for AMD it became super noisy (it was stable in the past for a long time):

![image](https://github.com/dotnet/runtime/assets/6011991/addc4aef-37cd-43f7-87a1-7c2836cc8378)

I believe that we should get the disassembly and see if there are any important changes before we decide what's next.
