### ISSUE TITLE
Regressions in System.Buffers.Text.Tests.Utf8ParserTests

### ISSUE THREAD

**Issue by cincuranet** [dotnet/runtime#91623]
Seems to be only AMD.

### Regressions in System.Buffers.Text.Tests.Utf8ParserTests

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[TryParseInt32 - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.19042/amd/System.Buffers.Text.Tests.Utf8ParserTests.TryParseInt32(value%3a%202147483647).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Buffers/Utf8ParserTests.cs#L41-#L43>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACn1UXW/TMBR976/wWxJIszQNXdspSN14GEKDsXbiAaHJa25bD39E9s3aIn48N8noko6hSJF97znH99i+loDsDsEhy5g33zsEFZ2XqxVYFy1gh/Rz6KJbXI2vuXVgm/nC7uvpR43DxH/ksoQpSwbpaToejtLTwDvryUrZIbe4EApIPucISEM/iZNhPx7143eLeDJNRtPBJEpPR8NhPHkbx9M4Dhr2fGMsfuYKXMOm716Cf1PqryXQgg6t0OuQ1bMK9xQJ2Pee903o3GxdNIijmcpHaZTEl0n0ZSuja7ArL2TeVuj+bpT2ucq98B+EweRyEC3EGuwLitAIsiLd3pcaS9KO02hmFbH+QiVBeRUh/QIstNFJha7X6MrLV+QH49cJg3GX0rZxKCial88GmqocRfgS2pQ52EcS7/rYHvvo/TjrXQEnPijQ6Hq/2XZDCXZeCpnfQGFYRncpN6gBTywZoDP3uqhzy/VyU+MsrNzJBnjuThQX+hlIx3xh9EqsS8tRGO0o8IkqrVlKLK05Ep3Z5UYgLJEqq0G0Lx4z9pVsbeo/y10YVQhZj69M3nBQEDR/JlXNUF28Kll3USdzYcg8dYwpnkaHrHCgCtz7Lxa9XpvFvoCg66xqoDnS/rP3rZYijCuV4lb8Asbt+k7xnV/jq5JC9iZg9/sjgfBQclg5rjuHdAprHmhrXoBvwJUSM0vl537LUhOf0W3ha1IaBh21ByM0+0lHlQmtwbb72Og20ILOKV9dkOWGXLGtwA3z6ZUR4LJDW4dstzSyVDo7rm/fxF3WFERAFCgh8z7QW0O3d/80rV8gX7ugirlCCsz4DlzwBx2qvCv+BAAA>)</li></ul> | 9.49 ns | 12.83 ns | 1.35 | 0.07 | False | | |
|<ul><li>[TryParseInt32 - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.19042/amd/System.Buffers.Text.Tests.Utf8ParserTests.TryParseInt32(value%3a%2012345).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Buffers/Utf8ParserTests.cs#L41-#L43>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACn1UUW+bMBB+z6/wG7ARCiSNmlRMSruHTVO3rkm1h2mqXLgEd9hG9tGEaT9+B3QppOuEhOy77/t8n+1zAcjuECyyhDmr2iLI4KLabMDYYA17pJ9FG9zi5uyaGwumm69N3U4/KpzE7iMvKliwKJ5MTz3nfFQ0oha5wbWQQMoZR0AaunEYT8bhbByersP5Ip4tonkwm4fT+Tx8G4aLMPQ69irXBj9zCbZj03dfgHtTqa8V0FoWjVBbn7WzBvcU8dj3kfNNqEzvbBCFwVJms2kQhx/i4MuuCK7BbByfOTuhxvvZdMxl5vj/IETzD1GwFlswLyhCIRQN6fa+UliRdjgNlkYS6y+0IChvIqRfgoE+Om7Q7RpD+eIV+ejsdUJ0NqT0bRwKClbVs4GuKksRnkKfsgLzSOJDH7tjH6Mf56Mr4MQHCQrt6Dfb5ZRgF5UoshsoNUvoGmUaFeCJIQN05s4QdWG4SvMWZ2BjT3LgmT2RXKhnIB3zpVYbsa0MR6GVpcAnqrRlSZEafSS6NGkuEFKkyloQ7YvDtHkl25r6z3KXWpaiaMdXOus4KAiaPZOaPmguXpNsG2iQudRknppFl0+jQ1ZYkCXW7otFr7d6XZfgDZ01DbRC2n/2rtdShLGVlNyIX8C42d5JvndbfFOSz9547L4+EvAPJfuN47ZzSKc0+oG25gX4BmxVYGKo/MztWeriS7otfEtKE2+g9qCFYj/pqBKhFJh+H2vVBxpQGeWbC5Lm5IrtBObMpQdGgE0Obe2zfaqLSqrkuL66i9ukK4iAKLCAxHlPbw3d3vpp2r5ArrJeE7NlITDhe7DeHwPabUT5BAAA>)</li></ul> | 5.25 ns | 7.01 ns | 1.33 | 0.06 | False | | |
|<ul><li>[TryParseUInt32 - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.19042/amd/System.Buffers.Text.Tests.Utf8ParserTests.TryParseUInt32(value%3a%204294967295).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Buffers/Utf8ParserTests.cs#L48-#L50>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACn1UXU/bMBR976/wW5ItDUlaCinKpMIemBAbo0V7mCZkmtvWzB+RfUObaT9+NwkrbRlTpMi+95zje2xfS0B2j+CQ5cyb1g5BRefVYgHWRTPYIP0cuugOF6c33Dqw3Xxm63Z690njIPWfuKxgzIZpNsxGJ2l2HHhnPdlIO+QWZ0IB6RccAWnop3E66Mejfnw8i7NxOhonWZTFg8FJkr2P43EcBx17ujIWP3MFrmPT9yDBv6301wpoQYdW6GXI2lmDe44E7HvP+yZ0YdYuSuJooorRMErjyzT6spbRDdiFFzJvLXR/Mxr2uSq88B+EJLtMoplYgn1FERpBNqS7h0pjRdrxMJpYRay/UElQ3kRIvwQLu+i0Qbdr7MvLN+ST07cJyek+ZdfGtqBoWr0Y6KpyFOFz2KVMwT6R+L6P9aGP3o+z3jVw4oMCja73m61XlGDnlZDFLZSG5XSZCoMa8MiSATpzbx91brmer1qchYU7WgEv3JHiQr8A6ZgvjF6IZWU5CqMdBa6o0palxNyaA9GJna8EwhypshZE++IxY9/Itqb+s9yFUaWQ7fjaFB0HBUGLF1LTDc3Fa5JtG+1lLgyZp5Yx5fNomxUOVIm1/2rRm6WZ1SUE+86aBpoi7T/7sNNShHGVUtyKX8C4Xd4rvvFbfFNSyN4F7KE+EAi3JYeN47ZzSKe05pG25hX4FlwlMbdUfuHvWOriE7otfElKg2BP7dEIzX7SUeVCa7C7fWz0LtCCLijfXJD5ilyxtcAV8+mZEeDybVuHbDM3slI6P6yv7uIu7woiIAqUkHsf6a2h21s/T9sXyNcuaGKulAJzvgEX/AFHawbI/wQAAA==>)</li></ul> | 8.52 ns | 10.31 ns | 1.21 | 0.03 | False | | |
|<ul><li>[TryParseUInt32 - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.19042/amd/System.Buffers.Text.Tests.Utf8ParserTests.TryParseUInt32(value%3a%2012345).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Buffers/Utf8ParserTests.cs#L48-#L50>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACn1UUW+bMBB+z6/wG7ARCiSN0lRMSruHTVO3rkm1h2mqXLgEd9hG9tGEaT9+B3QppOuEhOy77/t8n+1zAcjuECyyhDmr2iLI4KLabMDYYA17pJ9FG9ziZn7NjQXTzdembqe3HxVOYveRFxUsWBRPpqeecz4qGlWL3OBaSCDpjCMgDd04jCfjcDYOT9fh2SKeLeIwiKLpfBaGb8NwEYZex17l2uBnLsF2bPruC3BvKvW1AlrLohFq67N21uCeIh77PnK+CZXpnQ2iMFjKbDYN4vBDHHzZFcE1mI3jM2cn1Hg/m465zBz/H4To7EMUrMUWzAuKUAhFQ7q9rxRWpB1Og6WRxPoLLQjKmwjpl2Cgj44bdLvGUL54RT6av06I5kNK38ahoGBVPRvoqrIU4Sn0KSswjyQ+9LE79jH6cT66Ak58kKDQjn6zXU4JdlGJIruBUrOE7lGmUQGeGDJAZ+4MUReGqzRvcQY29iQHntkTyYV6BtIxX2q1EdvKcBRaWQp8okpblhSp0UeiS5PmAiFFqqwF0b44TJtXsq2p/yx3qWUpinZ8pbOOg4Kg2TOpaYTm4jXJtoMGmUtN5qlbdPk0OmSFBVli7b5Y9Hqr13UJ3tBZ00ArpP1n73otRRhbScmN+AWMm+2d5Hu3xTcl+eyNx+7rIwH/ULLfOG47h3RKox9oa16Ab8BWBSaGys/cnqUuvqTbwrekNPEGag9aKPaTjioRSoHp97FWfaABlVG+uSBpTq7YTmDOXHphBNjk0NY+26e6qKRKjuuru7hNuoIIiAILSJz39NbQ7a2fpu0L5CrrNTFbFgITvgfr/QG3PdXJ+gQAAA==>)</li></ul> | 5.01 ns | 6.17 ns | 1.23 | 0.06 | False | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/09_05_2023/refs/heads/main_x64_Windows%2010.0.19042/amd_Regression/System.Buffers.Text.Tests.Utf8ParserTests_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/09_05_2023/refs/heads/main_x64_Windows%2010.0.19042/amd_Regression/System.Buffers.Text.Tests.Utf8ParserTests_2.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/09_05_2023/refs/heads/main_x64_Windows%2010.0.19042/amd_Regression/System.Buffers.Text.Tests.Utf8ParserTests_3.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/09_05_2023/refs/heads/main_x64_Windows%2010.0.19042/amd_Regression/System.Buffers.Text.Tests.Utf8ParserTests_4.png>)

Taken from https://github.com/dotnet/perf-autofiling-issues/issues/21347.

**Comment by stephentoub** [comment]
These have mostly recovered, and any remaining difference looks to be sub-nanosecond.
