### ISSUE TITLE
[API Proposal]: Suggestion for adding another argument to IServiceProvider.GetService() for a more control over lookup

### ISSUE THREAD

**Issue by jarogor** [dotnet/runtime#91638]
### Background and motivation

(sorry for my english, it's actually google translation from russian because i don't speak english well)

A common problem with a container is getting different implementations of the same interface. The latest version has expanded the contract and added the ability to register by key. In fact, this is a bad idea and it's easier to put an implementation dependency than to end up doing almost the same thing specifying a specific key.

```cs
// For example instead of this:
builder.Services.AddKeyedSingleton<INotificationService, SmsNotificationService>("sms");
builder.Services.AddKeyedSingleton<INotificationService, EmailNotificationService>("email");
builder.Services.AddKeyedSingleton<INotificationService, PushNotificationService>("push");
...
public Sender([FromKeyedServices("sms")] INotificationService email)
public Sender([FromKeyedServices("email")] INotificationService email)
public Sender([FromKeyedServices("push")] INotificationService email)

// It's easier to put this:
public Sender(SmsNotificationService sms)
public Sender(EmailNotificationService email)
public Sender(PushNotificationService push)
```

If I have 150 controllers in which I need to clarify the dependency in 100 of them, then I need to fix all 100 controllers anyway. It makes no sense to fix with a specific key, if it's easier to put a specific implementation. It turns out that there is no difference between passing a specific implementation and passing an interface with a specific key.

But it is possible to supplement the `System.IServiceProvider` contract. Or you can create a new contract (yes, that's a big change). In general, you can add a method for requesting an object of some type and pass another type of the one that requests it. The meaning of this addition is that when someone requests a dependency, he can present a criterion to the provider, according to which the provider can resolve and give different dependencies.

In the DI logic of the container, you need to add a bearer pass to the method everywhere that requests the dependency. For example, controller. And do so always and everywhere, passing information about who requested the dependency. And in this way, you can delegate dependency resolution to the provider, if it is defined.

It is now possible to have 150 controllers with a single interface dependency, but manage the delivery of a particular implementation from the provider.

### API Proposal

```csharp
namespace System;

public interface IServiceBearerProvider : System.IServiceProvider
{
    object? GetService(Type serviceType, Type bearer);
}
```

### API Usage

```csharp
public class NotificationServiceProvider : IServiceBearerProvider
{
    private readonly NotificationServiceOptions _options;

    public NotificationServiceProvider(IOptions<NotificationServiceOptions> options)
    {
        _options = options.Value;
    }

    public object? GetService(Type serviceType, Type bearer)
    {
        if (_options.SmsCondition(bearer))
        {
            return new SmsNotificationService();
        }

        if (_options.PushCondition(bearer))
        {
            return new PushNotificationService();
        }

        return GetService(serviceType);
    }

    // default
    public object? GetService(Type serviceType)
    {
        return new EmailNotificationService();
    }
}

// And register instead of several different implementations one provider for them
builder.Services.AddSingleton<INotificationService, NotificationServiceProvider>();

```

**Comment by steveharter** [comment]
> The latest version has expanded the contract and added the ability to register by key. In fact, this is a bad idea and it's easier to put an implementation dependency than to end up doing almost the same thing specifying a specific key.
...
builder.Services.AddKeyedSingleton<INotificationService, SmsNotificationService>("sms");
builder.Services.AddKeyedSingleton<INotificationService, EmailNotificationService>("email");
builder.Services.AddKeyedSingleton<INotificationService, PushNotificationService>("push");

For this example, yes the string-based key doesn't add anything. The cases where a key is most useful is when doing late-bound adding of keys such as based on config section names. See this [ask for keyed services support](https://github.com/dotnet/extensions/issues/2937) which has the example from a different DI framework:
```cs
var reader = scope.Resolve<ConfigReader>(new NamedParameter("configSectionName", "sectionName"));
```
For the new APIs proposed, I can see value in essentially having a callback to get the service, but this also goes against some best practices for DI IMO such as doing what the "service location antipattern" does which is where the service dependencies get sort of lost and embedded in logic instead of being declared as part of the constructor arguments, for example.

Also we have request https://github.com/dotnet/runtime/issues/92012 to also have more flexibility for more fine-grain service lookup. I think it would be good to reconcile both together.

**Comment by jarogor** [comment]
@steveharter I think there are no violations or antipatterns here. On the contrary, I would call it managing polymorphism and maintaining one-way dependencies. The service has a dependence on the abstraction and receives some kind of implementation from the outside, without caring about how this happens.

One can imagine that everything remains as it is, only it becomes possible, instead of implementing a contract, to register the implementation of a supplier to whom decision-making can be delegated. Then the DI container, when requesting something from it, could check whether the received object is a provider? If yes, then you need to delegate resolution to him. But the most important thing is to provide information about who wants to receive it. Without information about the requester, this entire mechanism is meaningless.

Perhaps I'm just a bad storyteller and I was poorly able to explain the essence of the problem and solution. The idea is primarily to complement the concept of a dependency container with a small mechanism that opens up great possibilities.

Thanks for understanding

**Comment by HHobeck** [comment]
What you are requesting in this issue here is exactly the behavior of the new feature IKeyedServiceProvider:

```csharp
public interface IKeyedServiceProvider : IServiceProvider
{
    public object? GetKeyedService(Type serviceType, object? serviceKey);
}

public interface IKeyedServiceProvider<TService> : IKeyedServiceProvider
{
    public TService? GetKeyedService(object? serviceKey);
}
```

You should be able to do something like the following:

```csharp
public class KeyedServiceProvider : IKeyedServiceProvider
{
    public IServiceProvider ServiceProvider { get; }

    public KeyedServiceProvider(IServiceProvider serviceProvider)
    {
        ServiceProvider = serviceProvider ?? throw new ArgumentNullException(nameof(serviceProvider));
    }

    public virtual object? GetService(Type serviceType)
    {
        return ServiceProvider.GetService(serviceType);
    }

    public virtual object? GetKeyedService(Type serviceType, object? serviceKey)
    {
        Type keyedServiceProviderType = typeof(IKeyedServiceProvider<>).MakeGenericType(serviceType);
        var keyedServiceProvider = (IKeyedServiceProvider)ServiceProvider.GetRequiredService(keyedServiceProviderType);
        return keyedServiceProvider.GetKeyedService(serviceType, serviceKey);
    }
}

public record NotificationServiceOptions
{
    public bool IsSmsConditionComplied(Type serviceType)
    {
        return true;
    }

    public bool IsEmailConditionComplied(Type serviceType)
    {
        return true;
    }
}

public sealed class NotificationServiceProvider : IKeyedServiceProvider<INotificationService>
{
    private readonly NotificationServiceOptions _options;

    public IServiceProvider ServiceProvider { get; }

    public NotificationServiceProvider(IServiceProvider serviceProvider, IOptions<NotificationServiceOptions> options)
    {
        ServiceProvider = serviceProvider ?? throw new ArgumentNullException(nameof(serviceProvider));
        _options = options?.Value ?? throw new ArgumentNullException(nameof(options));
    }

    public object? GetService(Type serviceType)
    {
        if (serviceType != typeof(INotificationService))
        {
            throw new ArgumentException("The service type cannot be requested.", nameof(serviceType));
        }

        return GetKeyedService(null);
    }

    public object? GetKeyedService(Type serviceType, object? serviceKey)
    {
        if (serviceType != typeof(INotificationService))
        {
            throw new ArgumentException("The service type cannot be requested.", nameof(serviceType));
        }

        return GetKeyedService(serviceKey);
    }

    public INotificationService? GetKeyedService(object? serviceKey)
    {
        if (serviceKey is Type serviceType)
        {
            if (_options.IsSmsConditionComplied(serviceType))
            {
                return ServiceProvider.GetRequiredService<SmsNotificationService>();
            }

            if (_options.IsEmailConditionComplied(serviceType))
            {
                return ServiceProvider.GetRequiredService<EmailNotificationService>();
            }
        }

        return ServiceProvider.GetRequiredService<PublishNotificationService>();
    }
}
```

and

```csharp
ServiceCollection serviceCollection = new();
ServiceCollection.AddOptions();
serviceCollection.AddSingleton<IKeyedServiceProvider<INotificationService>, NotificationServiceProvider>();
serviceCollection.AddTransient<SmsNotificationService>();
serviceCollection.AddTransient<EmailNotificationService>();
serviceCollection.AddTransient<PublishNotificationService>();
IServiceProvider serviceProvider = serviceCollection.BuildServiceProvider();

var keyedServiceProvider = serviceProvider.GetRequiredService<IKeyedServiceProvider<INotificationService>>();
INotificationService notificationService = keyedServiceProvider.GetKeyedService(serviceKey: typeof(WhatEverClassYouLike));
```

**Comment by jarogor** [comment]
@HHobeck What you wrote is a complexly formulated imitation of a solution, which can be simplified to a direct request for a specific implementation.

```
builder.Services.AddKeyedSingleton<SmsNotificationService>();
...
public Sender(SmsNotificationService sms) {}
```

There is no conceptual or practical difference between a specific key and a specific implementation. Both are not dependency inversion. But registering and getting a specific implementation is much easier.

Especially when it comes to autowiring, automatic dependency injection, for example in controller designers.

I came up with a very plausible example that shows that you will have to go through all the controllers and fix them. And do this every time the need arises. And this is the main problem for which the container does not offer a solution. What if there are not 150 controllers, but 1500? It will be difficult to maintain and develop such code.

**Comment by HHobeck** [comment]
> @HHobeck What you wrote is a complexly formulated imitation of a solution, which can be simplified to a direct request for a specific implementation.
> 
> ```
> builder.Services.AddKeyedSingleton<SmsNotificationService>();
> ...
> public Sender(SmsNotificationService sms) {}
> ```
> 
> There is no conceptual or practical difference between a specific key and a specific implementation. Both are not dependency inversion. But registering and getting a specific implementation is much easier.
> 
> Especially when it comes to autowiring, automatic dependency injection, for example in controller designers.
> 
> I came up with a very plausible example that shows that you will have to go through all the controllers and fix them. And do this every time the need arises. And this is the main problem for which the container does not offer a solution. What if there are not 150 controllers, but 1500? It will be difficult to maintain and develop such code.

Actually I'm not agree. It is completely different. The point here is that the implementation of the service class e.g. Sender doesn't care about the concrete implemenation like in your example SmsNotificationService. You can think of the behavior like a generic type. If you specify IEnumerable<T> then the implementarion of this interface doesn't care about T.

If you take your code:

```csharp
public class NotificationServiceProvider : IServiceBearerProvider
{
    private readonly NotificationServiceOptions _options;

    public NotificationServiceProvider(IOptions<NotificationServiceOptions> options)
    {
        _options = options.Value;
    }

    public object? GetService(Type serviceType, Type bearer)
    {
        if (_options.SmsCondition(bearer))
        {
            return new SmsNotificationService();
        }

        if (_options.PushCondition(bearer))
        {
            return new PushNotificationService();
        }

        return GetService(serviceType);
    }

    // default
    public object? GetService(Type serviceType)
    {
        return new EmailNotificationService();
    }
}
```

and mine:

```csharp
public sealed class NotificationServiceProvider : IKeyedServiceProvider<INotificationService>
{
    private readonly NotificationServiceOptions _options;

    public IServiceProvider ServiceProvider { get; }

    public NotificationServiceProvider(
        IServiceProvider serviceProvider, IOptions<NotificationServiceOptions> options)
    {
        ServiceProvider = serviceProvider ?? throw new ArgumentNullException(nameof(serviceProvider));
        _options = options?.Value ?? throw new ArgumentNullException(nameof(options));
    }

    public object? GetService(Type serviceType)
    {
        if (serviceType != typeof(INotificationService))
        {
            throw new ArgumentException("The service type cannot be requested.", nameof(serviceType));
        }

        return GetKeyedService(null);
    }

    public object? GetKeyedService(Type serviceType, object? serviceKey)
    {
        if (serviceType != typeof(INotificationService))
        {
            throw new ArgumentException("The service type cannot be requested.", nameof(serviceType));
        }

        return GetKeyedService(serviceKey);
    }

    public INotificationService? GetKeyedService(object? serviceKey)
    {
        if (serviceKey is Type serviceType)
        {
            if (_options.IsSmsConditionComplied(serviceType))
            {
                return ServiceProvider.GetRequiredService<SmsNotificationService>();
            }

            if (_options.IsEmailConditionComplied(serviceType))
            {
                return ServiceProvider.GetRequiredService<EmailNotificationService>();
            }
        }

        return ServiceProvider.GetRequiredService<PublishNotificationService>();
    }
}
```

where is the different!? If you ask me there is no different from the sense of what the code does.

**Comment by jarogor** [comment]
@HHobeck The difference is how the provider enters the criterion. You are just looking in the wrong place. You look at the similarity of implementations, but the whole point is how the criterion is passed to the provider. The point of my proposal is to make the mechanism for transferring the requester automatic. So that you don’t have to write the key manually in the constructor, but manage resolution dynamically from the provider.

You are simply deviating from the example I suggested. Try to return to it and explain how you will use your provider by key without touching the controllers? Obviously this is impossible. Then what is the point of registering using a key? Instead of a specific key, I will indicate a specific implementation and will not do much extra at all. Yes, this will violate the conceptual purity of the dependency inversion principle. But registration by key does not solve this problem anyway. So let it violate the principle, but the code will be many times less in practice.

**Comment by HHobeck** [comment]
I'm grounded and cannot follow your thoughts. If you take the following example then you see there is concrete key involved. Thus you don't need to touch your controller to change the injection:

```
public class MyController : IController
{
    public readonly INotificationService NotificationService;

    public Sender([FromKeyedServices] INotificationService notificationService)
    {
        NotificationService = notificationService;
    }
}
```

**Comment by jarogor** [comment]
@HHobeck Think about how the resolution key is passed to the provider. You place it manually in the constructor. I don't understand why you don't notice this. I proposed not to do this, but to automate the presentation of criteria for resolution.

A similar idea already exists in Castle.Windsor ([example from the comments of my article in Russian](https://habr.com/ru/articles/761268/#comment_25971440))

```
Component.For<Controller4>().DependsOn(Dependency.OnComponent<ILogger, RabbitMqLogger>()),
Component.For<Controller5>().DependsOn(Dependency.OnComponent<ILogger, PostgreSqlLogger>())
```

**Comment by davidfowl** [comment]
I don't think we want to further complicate the design of DI by allowing people to have arbitrary lookup criteria. Resolving by target type is reasonable idea that has existed in DI containers like windsor and ninject for ages, that said, we don't need to be in a rush to add it as there are pretty reasonable workarounds (like using a factory or using open generics).

Keyed services aren't great for replacing factories that require unique context (something beyond simple keys), but are great when keys are simple, and the interface can't be defined per key. As an example, injecting an HttpClient based on the name (similar to what the http client factory does today):

```C#
builder.Services.AddKeyedTransient("basket", (sp, key) => new HttpClient
{
    BaseAddress = new Uri("http://localhost:5001")
});

builder.Services.AddKeyedTransient("catalog", (sp, key) => new HttpClient
{
    BaseAddress = new Uri("http://localhost:5000")
});
```

If you control all of the types, the make a type per key.

Now back to the original request: Resolving services based on the target type. You can simulate this today using the target type as the key in the keyed service, and writing some code to resolve parameters based on the target type:

```C#
public static IServiceCollection AddTargetTypeSingleton<TTarget>(this IServiceCollection services)
    where TTarget : class
{
    // TODO: Replace with constructor selection logic
    var ctor = typeof(TTarget).GetConstructors().Single();
    var parameteter = ctor.GetParameters();
    var invoker = ConstructorInvoker.Create(ctor);

    return services.AddSingleton(sp =>
    {
        Span<object?> local = [null, null, null, null];

        Span<object?> args = parameteter.Length switch
        {
            0 => [],
            <= 4 => local[..parameteter.Length],
            _ => new object[parameteter.Length]
        };

        for (int i = 0; i < args.Length; i++)
        {
            var p = parameteter[i];
            if (sp is IKeyedServiceProvider keyed)
            {
                // Use the type as the key, or fallback to normal service resolution
                args[i] = keyed.GetKeyedService(p.ParameterType, typeof(TTarget)) ?? sp.GetRequiredService(p.ParameterType);
            }
            else
            {
                args[i] = sp.GetRequiredService(p.ParameterType);
            }
        }

        return (TTarget)invoker.Invoke(args);
    });
}
```

The above logic (except for the constructor selection) could be used to resolve the services based on the target type, using the type as the key:


```C#
services.AddMemoryCache();
services.AddKeyedSingleton<IMemoryCache, MemoryCache2>(typeof(SomeController));

services.AddTargetTypeSingleton<SomeController>();
services.AddTargetTypeSingleton<AnotherController>();

class SomeController(IMemoryCache cache)
{
}

class AnotherController((IMemoryCache cache)
{
}
```


> If I have 150 controllers in which I need to clarify the dependency in 100 of them, then I need to fix all 100 controllers anyway. It makes no sense to fix with a specific key, if it's easier to put a specific implementation. It turns out that there is no difference between passing a specific implementation and passing an interface with a specific key.

In either case, you need to describe the mapping somewhere, the argument is about moving that into a single place rather than in each of the callsites.

**Comment by HHobeck** [comment]
> @HHobeck Think about how the resolution key is passed to the provider. You place it manually in the constructor. I don't understand why you don't notice this. I proposed not to do this, but to automate the presentation of criteria for resolution.
> 
> A similar idea already exists in Castle.Windsor ([example from the comments of my article in Russian](https://habr.com/ru/articles/761268/#comment_25971440))
> 
> ```
> Component.For<Controller4>().DependsOn(Dependency.OnComponent<ILogger, RabbitMqLogger>()),
> Component.For<Controller5>().DependsOn(Dependency.OnComponent<ILogger, PostgreSqlLogger>())
> ```

Okay thank you for clarification. ;)

**Comment by gao-artur** [comment]
Both suggestions, by @HHobeck and @davidfowl are working solutions, but both require special changes in the consumer implementation, like adding `[FromKeyedServices]`:
```c#
public MyController([FromKeyedServices] INotificationService notificationService)
{
    NotificationService = notificationService;
}
```

Or in the consumer registration, like replacing `AddSingleton` with `AddTargetTypeSingleton`
```c#
services.AddTargetTypeSingleton<SomeController>();
services.AddTargetTypeSingleton<AnotherController>();
```

It would be nice to provide an extension point instead to register the implementation selector class, which will be triggered if found in the DI, similar to how `IConfigureOptions<TOptions>` is triggered before resolving options.
```c#
public class NotificationServiceSelector : IServiceSelector<INotificationService>
{
    public INotificationService GetService(IServiceProvider serviceProvider, Type consumer)
    {
        // the implementation selector based on some criteria
    }
}
```

This way, nothing has changed except the new type implementation and registration.

**Comment by davidfowl** [comment]
The DI container doesn't want to call your code at runtime to decide how to resolve services for the target type (that's inefficient). That's what the registration methods are for, and you can already define a factory for your type.

**Comment by jarogor** [comment]
@davidfowl Yes, doing this in runtime is unjustified, especially if there is a way to register in advance. Maybe it’s worth adding at least your extension to the Nuget package and its documentation indicating that such an opportunity exists, so that people know about it. Because this is a flaw of the DI API, which each person has to design additionally, so many bad recipes have been invented

**Comment by jarogor** [comment]
I suggest closing the issue if it doesn't make sense.
