### ISSUE TITLE
KeyPerFile Configuration provider does not reload configuration when K8S config maps mapped to volumes changes

### ISSUE THREAD

**Issue by madhub** [dotnet/runtime#91640]
### Description

KeyPerFile configuration provider doesn't  seems to reload the configuration values when directory is of **K8S configmap** mounted volumes .

### Reproduction Steps

Sample application  reproduce this issue : [Demo App](https://github.com/madhub/cmdemo/tree/master)

1. Use the AddKeyPerFile for loading configuration values from  **K8S configmap** mounted volumes .
2. For demonstration , add API to return values from config mounted volume.
3. Deploy the application in K8S with configmap mounted volume,
4. Edit the configmap values , perform step 2 , to check updated values are returned.

### Expected behavior

Updated ConfigMap values should be reflected inside the application when config map is edited & saved..

### Actual behavior

Application only see the original values of configmap  read at the application startup , it seems reload of configuration is not happening.

### Regression?

no

### Known Workarounds

I have not found any workaround

### Configuration

.NET version : dotnet 6.  Runtime 6.0.20
OS Linux: "Debian GNU/Linux 11 (bullseye)" base image.
Kubernetes : 1.25.9. ( Kubernetes with Docker desktop) 

### Other information
Also tested on 
.NET version : dotnet 7.  Runtime 7.0.9
OS Linux: "Debian GNU/Linux 11 (bullseye)" base image.
Kubernetes : 1.25.9. ( Kubernetes with Docker desktop) 

_No response_

**Comment by tarekgh** [comment]
This could be related to the issue https://github.com/dotnet/runtime/issues/88240 too.

**Comment by CDR-FarooqK** [comment]
I also see the same behaviour in .NET 8, in AKS pod though the secret in the pod is updated which is loaded as volume mount. .NET Core doesn't pick the change. This issue doesn't happen when running locally on windows machine outside of AKS. Wondering when you guys thinking of fixing this issue?

**Comment by davidfowl** [comment]
Isn’t this because you need to turn on the polling file watcher?
