### ISSUE TITLE
Failure in System.Threading.RateLimiting.Test.ConcurrencyLimiterTests.DoesNotDeadlockCleaningUpCanceledRequestedLease_Post

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#91653]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=396297
Build error leg or test failing: System.Threading.RateLimiting.Test.ConcurrencyLimiterTests.DoesNotDeadlockCleaningUpCanceledRequestedLease_Post
Pull request: https://github.com/dotnet/runtime/pull/91651

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Actual:   Task { Status = RanToCompletion }",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```
Seems like it might be a timing issue with the test?

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=396297
**Error message validated:** `Actual:   Task { Status = RanToCompletion }`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 9/6/2023 2:17:55 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[717524](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717524)|dotnet/runtime|[System.Threading.RateLimiting.Test.ConcurrencyLimiterTests.DoesNotDeadlockCleaningUpCanceledRequestedLease_Post](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717524&view=ms.vss-test-web.build-test-results-tab&runId=17972352&resultId=134641)|dotnet/runtime#103738|
|[714212](https://dev.azure.com/dnceng-public/public/_build/results?buildId=714212)|dotnet/runtime|[System.Threading.RateLimiting.Test.ConcurrencyLimiterTests.DoesNotDeadlockCleaningUpCanceledRequestedLease_Post](https://dev.azure.com/dnceng-public/public/_build/results?buildId=714212&view=ms.vss-test-web.build-test-results-tab&runId=17867306&resultId=132612)|dotnet/runtime#103738|
|[705232](https://dev.azure.com/dnceng-public/public/_build/results?buildId=705232)|dotnet/runtime|[System.Threading.RateLimiting.Test.ConcurrencyLimiterTests.DoesNotDeadlockCleaningUpCanceledRequestedLease_Post](https://dev.azure.com/dnceng-public/public/_build/results?buildId=705232&view=ms.vss-test-web.build-test-results-tab&runId=17588536&resultId=168835)|dotnet/runtime#103195|
|[701087](https://dev.azure.com/dnceng-public/public/_build/results?buildId=701087)|dotnet/runtime|[System.Threading.RateLimiting.Test.ConcurrencyLimiterTests.DoesNotDeadlockCleaningUpCanceledRequestedLease_Post](https://dev.azure.com/dnceng-public/public/_build/results?buildId=701087&view=ms.vss-test-web.build-test-results-tab&runId=17448820&resultId=155371)|dotnet/runtime#103177|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|4|

**Comment by mangod9** [comment]
@BrennanConroy fyi..

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by lewing** [comment]
failed in https://github.com/dotnet/runtime/pull/128224

**Comment by svick** [comment]
@lewing This KBE is too broad, so it's matching CI test failures that are unrelated to System.Threading.RateLimiting. I couldn't find the failure you mentioned to narrow the KBE down, so I'm going to close this issue for now.
