### ISSUE TITLE
Dictionary.TryGetValue(key, out boolvalue) sets boolvalue to false

### ISSUE THREAD

**Issue by woodmage** [dotnet/runtime#91689]
### Description

When using a Dictionary defined as Dictionary<int, bool> dict = new();, a key not found in a dict.TryGetValue(key, out boolvalue) will set the output boolean to false.

### Reproduction Steps

Dictionary<int,bool> dict = new Dictionary<int, bool>();
dict[0] = true;
bool boolvalue = true;
Console.WriteLine("Boolean value is " + boolvalue);
dict.TryGetValue(2, out boolvalue); //should be true (still) since key is not in dictionary
Console.WriteLine("Boolean value is " + boolvalue);

### Expected behavior

Boolean value is true
Boolean value is true

### Actual behavior

Boolean value is true
Boolean value is false

### Regression?

Dunno.

### Known Workarounds

I changed my code to use a out bool tempboolvalue and if key is found copy tempboolvalue to boolvalue.

### Configuration

This is .Net 6, I'm running Windows 10 and Windows 11 and it happens on both.  Both of them are x64.

**Comment by GalaxiaGuy** [comment]
From the docs

https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.trygetvalue?view=net-7.0

> When this method returns, contains the value associated with the specified key, if the key is found; otherwise, the default value for the type of the value parameter.

**Comment by MihaZupan** [comment]
This is the documented behavior - https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2.trygetvalue

`value`:
> When this method returns, contains the value associated with the specified key, if the key is found; otherwise, the default value for the type of the value parameter. This parameter is passed uninitialized.

Similar for other `Try-` methods - e.g. `int.TryParse(out value)` will set `value` to 0 if the parsing failed.

You can't expect the value you pass via `out` to be unmodified.

**Comment by woodmage** [comment]
> This is the documented behavior - https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2.trygetvalue
> 
> `value`:
> 
> > When this method returns, contains the value associated with the specified key, if the key is found; otherwise, the default value for the type of the value parameter. This parameter is passed uninitialized.
> 
> Similar for other `Try-` methods - e.g. `int.TryParse(out value)` will set `value` to 0 if the parsing failed.
> 
> You can't expect the value you pass via `out` to be unmodified.

Obviously, you don't know me!  I ***DID*** expect it to be unmodified!  🤪 Funny thing is I "read" those docs three or so times before doing my little bug report.  And for some stupid reason, "default value for the type of the value parameter" somehow translated in my head as "doesn't modify value".  It's been a long day, night, and day.  I'll close this issue now.  👍😎

**Comment by huoyaoyuan** [comment]
According to C# language rule, `out` parameters are considered unassigned in the callee, and must be assigned upon exit. So it's original value will never be preserved.
