### ISSUE TITLE
check-labels action doesn't remove past results

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#91691]
I'm not sure what to change but I noticed that the `check-labels` action doesn't remove past results.  Here's an example:
<img width="981" alt="image" src="https://github.com/dotnet/runtime/assets/8918108/e4a3d156-b2a0-43ef-a2da-c351094d1bb5">
From PR https://github.com/dotnet/runtime/pull/91602

This makes it look like the PR was merged with failing checks, when it wasn't. @hoyosjs @carlossanlop

**Comment by akoeplinger** [comment]
Haven't seen this again, probably some temporary GitHub issue.
