### ISSUE TITLE
MailMessage Subject encoding does not work if an attachment added

### ISSUE THREAD

**Issue by furkanhb** [dotnet/runtime#917]
# MailMessage Subject encoding does not work if an attachment added

When I add an attachment to MailMessage object and subject contains unicode characters such as "İ", mail subject text encoding does not work. No problem, if no attachment is added

Ex: When i set Subject property as
"20 İstanbul" 		mail subject is "20 Ä°stanbul"
"20 İstanbul ş" 	mail subject is "20 Ä°stanbul ÅŸ" 
"20 İstanbul şş" 	mail subject is "20 İstanbul şş" (no problem)

I tested with 

```C#
MailMessage mail = new MailMessage(new MailAddress("noreply@xxxx.com", "xxxx"), new MailAddress("xxx@xxxx.com")) {
    Subject = "20 İstanbul şş",
    Body = "20 İstanbul",
    IsBodyHtml = true
};
mail.Attachments.Add(new Attachment(new MemoryStream(new byte[] { 65, 65, 65, 65, 65 }), "test.txt", MediaTypeNames.Text.Plain)); // if comment this line everything works fine
using (SmtpClient smtp = new SmtpClient("smtp.office365.com", 587)) {
    smtp.UseDefaultCredentials = false;
    smtp.Credentials = new NetworkCredential("username", "pass");
    smtp.EnableSsl = true;
    smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
    await smtp.SendMailAsync(mail);
}
```

**Comment by karelz** [comment]
@MihaZupan did you try to reproduce it yourself? If yes and you couldn't, let's close it ...
