### ISSUE TITLE
Unify RuntimeType with the shared RuntimeType

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#91704]
Optimistically placing this in 9.0 milestone.

We should unify the reflection stack with the stack shared with Mono/CoreCLR-JIT.

Things we can enable once that's done:

- [ ] Roll back #91660. Instead of doing the extra analysis, we should no longer need to generate any metadata for unconstructed MethodTables (basically roll back EETypeNode/ConstructedEETypeNode/etc. to how it looked before #85810 that triggered the bugfix)
- [ ] Preinitialization of System.RuntimeType instances and related RyuJIT features that can directly reference System.RuntimeType addresses.
- [ ] Allocate lazily created System.RuntimeType instances on frozen heap

**Comment by MichalPetryka** [comment]
Wouldn't this require NativeAOT to get rid od the RuntimeType subclasses for this?

**Comment by MichalStrehovsky** [comment]
> Wouldn't this require NativeAOT to get rid of the RuntimeType subclasses for this?

Yes, that's the intention.

**Comment by jkotas** [comment]
> Preinitialization of System.RuntimeType instances and related RyuJIT features that can directly reference System.RuntimeType addresses.

@MichalStrehovsky Feel free to pick this up and enable this optimization in ilc. It should be pretty straightforward now that RuntimeType is prepared for it. I do not think that I am going to have time to do it anytime soon.

**Comment by EgorBo** [comment]
I can help with the JIT side once RuntimeType become frozen, ideally it's a matter of implementing some, currently no-op, JIT-VM apis and might need some JIT changes as well for relocable constants

**Comment by MichalStrehovsky** [comment]
> > Preinitialization of System.RuntimeType instances and related RyuJIT features that can directly reference System.RuntimeType addresses.
> 
> @MichalStrehovsky Feel free to pick this up and enable this optimization in ilc. It should be pretty straightforward now that RuntimeType is prepared for it. I do not think that I am going to have time to do it anytime soon.

Looking into it!

Thanks for the help offer Egor!

**Comment by MichalStrehovsky** [comment]
This has been resolved.
