### ISSUE TITLE
How to use System.IO.FileSystem.AccessControl in netstandard2.0?

### ISSUE THREAD

**Issue by bgavrilMS** [dotnet/runtime#91729]
### Description

[Microsoft Identity SDK uses System.IO.FileSystem.AccessControl](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/main/src/client/Microsoft.Identity.Client.Extensions.Msal/Microsoft.Identity.Client.Extensions.Msal.csproj#L23) to set some file permissions on Windows. We recently upgraded the library from supporting `net45` and `netcoreapp2.0` and  `netstandard2.0` to supporting only `netstandard2.0`

However, this creates problems downstream, because now apps end up referencing **[System.IO.FileSystem.AccessControl](https://www.nuget.org/packages/System.IO.FileSystem.AccessControl/5.0.0)** which is **deprecated** 

There is no alternative for System.IO.FileSystem.AccessControl on NetStandard as far as I can tell? 

### Reproduction Steps

1. Create a lib and target `netstandard2.0`
2. Try to use File security, e.g. `FileSecurity security = new FileSecurity();` from `System.Security.AccessControl` namespace 
3. This namespace doesn't exist, as assembly reference must be added 

![image](https://github.com/dotnet/runtime/assets/12273384/152323cd-6007-4c2a-9926-90ed0585ca56)

4. Try to add a reference to `System.IO.FileSystem.AccessControl`

### Expected behavior

`System.IO.FileSystem.AccessControl` to not be deprecated on nuget.org

### Actual behavior

`System.IO.FileSystem.AccessControl` is deprecated on nuget.org

### Regression?

No

### Known Workarounds

The workaround would be to drop support for `netstandard2.0` and to add support for `net462` and `net6`. 

I would like a confirmation from you folks that this is the only path forward for an SDK, as `netstandard` continues to be recommended.

**Comment by adamsitnik** [comment]
cc @ViktorHofer @ericstj

**Comment by ViktorHofer** [comment]
Hello @bgavrilMS, thanks for reaching out. You are correct that when targeting .NET Standard, the System.IO.FileSystem.AccessControl package needs to be referenced. I just un-deprecated the 5.0.0 version. Please open a new issue if you still experience issues with it.

**Comment by teo-tsirpanis** [comment]
@bgavrilMS I would still recommend you to multi-target to .NET 6, where the functionality is built-in and you would not need to reference the `System.IO.FileSystem.AccessControl` package.
