### ISSUE TITLE
Stopwatch.Frequency different Windows and Linux

### ISSUE THREAD

**Issue by jerviscui** [dotnet/runtime#91726]
### Description

`Stopwatch.Frequency` in Windows is 10000000, and in Linux is 1000000000.

### Reproduction Steps

The filed description: 
Gets the frequency of the timer as the number of ticks per second. This field is read-only.

所以，Windows 和 Linux 具有不同值是符合预期的吗？

### Expected behavior

Maybe the values should be kept consistent.

### Actual behavior

none

**Comment by stephentoub** [comment]
This is by design. Stopwatch exposes the OS' high frequency timer, and thus has whatever frequency it has. That's why Frequency is exposed to begin with, as it can vary from system to system.

**Comment by jerviscui** [comment]
Ok.
So now I need to use `TimeSpan.TicksPerSecond` as the conversion ratio between `DateTime.Ticks` and seconds.
