### ISSUE TITLE
How to locate executables in nuget packages

### ISSUE THREAD

**Issue by lilith** [dotnet/runtime#9172]
I'm looking for a way to access a nuget-packaged native executable (similar to how unmanaged dlls are loaded from the `runtimes/[rid]/native` folders of nuget packages because the DLL search path is modified). 

If there's a way to determine or access these search paths, then it should be possible to locate an executable from a (or any) NuGet package.

Hopefully this is the right repo?

**Comment by rseanhall** [comment]
All of the `runtimes/[rid]/native` folders, for the `rid` of the platform that the code is currently running on, is added to the `NATIVE_DLL_SEARCH_DIRECTORIES` value in `AppContext`. This is how I use it to find a native executable: https://github.com/wixtoolset/Core.Native/blob/8296f237c69743d3e6cbdc58fc07e8470562b92e/src/WixToolset.Core.Native/WixNativeExe.cs#L83.

I think it's supposed to be possible to use the [`Microsoft.Extensions.DependencyModel`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencymodel) namespace to parse the .deps.json file and get the path that way, but that API is very poorly documented.
