### ISSUE TITLE
Assert failure: !"UnwindManagedExceptionPass1: PAL_VirtualUnwind failed"

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#91723]
### Error Blob

```json
{
  "ErrorMessage": "!\"UnwindManagedExceptionPass1: PAL_VirtualUnwind failed\"",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Reproduction Steps

Seen on linux-arm32 in this runtime run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=398053&view=ms.vss-test-web.build-test-results-tab&runId=8591602&resultId=191289&paneView=debug
Console log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-91674-merge-ddf2d2aee0784f84b4/System.Runtime.Tests/1/console.ecdf2f0f.log?helixlogtype=result

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=398053
**Error message validated:** `!"UnwindManagedExceptionPass1: PAL_VirtualUnwind failed"`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 9/7/2023 11:10:49 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by jkotas** [comment]
cc @janvorli

**Comment by janvorli** [comment]
Unfortunately the dump is not debuggable. Neither lldb nor gdb is able to unwind past the ProcAbort for some reason, even though I can do it manually using data on the stack. I am trying to repro it using the stuff downloaded by runfo.

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by janvorli** [comment]
It looks like this issue is gone, closing it now.
