### ISSUE TITLE
Bump iOS/tvOS minimum supported version to 12.2

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#91736]
Xcode 15 drops support for targeting iOS 11.0 (our current baseline) and bumping to 12.2 allows us to rely on the Swift libraries shipped with the OS.

Also bump the MacCatalyst versions (`apple-iosXY-macabi`) to 15.0 since that is the lowest which works on macOS 12

**Comment by vcsjones** [comment]
> bumping to 12 allows us to rely on the Swift libraries shipped with the OS.

Isn't it technically 12.2? What happens if a device is 12.1?

**Comment by akoeplinger** [comment]
Thanks, I've corrected the description to 12.2.

> What happens if a device is 12.1?

The same as on any older version, the App Store won't offer the app to you.

**Comment by AaronRobinsonMSFT** [comment]
Tagging https://github.com/dotnet/runtime/pull/94298#discussion_r1380756982 as a follow up when this issue is addressed.

**Comment by jkotas** [comment]
> Tagging https://github.com/dotnet/runtime/pull/94298#discussion_r1380756982 as a follow up when this issue is addressed.

There is nothing to follow up wrt that PR. We would need to bump the min iOS version to 13 to enable `aligned_alloc` for iOS.
