### ISSUE TITLE
[API Proposal]: Make `string` implement `IReadOnlyList<char>`

### ISSUE THREAD

**Issue by Neme12** [dotnet/runtime#91756]
### Background and motivation

`System.String` already fulfills the contract of `IReadOnlyList<char>` in that it is `IEnumerable<char>` and has an indexer and a count, but it doesn't actually implement the interface. Implementing the interface would allow more efficient usage in LINQ as `TryGetNonEnumeratedCount` could then work, as well as indexer-based optimizations for `FirstOrDefault`, `LastOrDefault`, etc.

These methods could of course be changed to special-case `string` instead of `string` implementing the interface, but I don't see a downside to implementing the interface. As an added bonus, anyone could pass `string` to a method that takes `IReadOnlyList<T>` where `T` is `char``.

### API Proposal

```diff
 public sealed partial class String :
     IEnumerable<char>,
     IEnumerable,
     ICloneable,
     IComparable,
     IComparable<string?>,
     IConvertible,
     IEquatable<string?>,
     IParsable<string>,
     ISpanParsable<string>,
+    IReadOnlyList<char>
 {
 
 }
```

### API Usage

```csharp
// LINQ usage, e.g.
var ch = str.LastOrDefault();
// is now more efficient, as well as things that take advantage of TryGetNonEnumeratedCount, like:
var array = str.ToArray();
var array2 = str.ToImmutableArray();
// because TryGetNonEnumeratedCount returned true and an array of the exact size was allocated
```

**Comment by vcsjones** [comment]
This has been previously proposed at https://github.com/dotnet/runtime/issues/57484 and https://github.com/dotnet/runtime/issues/19609.

**Comment by Neme12** [comment]
https://github.com/dotnet/runtime/issues/19609#issuecomment-349415239

> String isn't (logically) a collection of chars, so giving a read-only view seems off.

It isn't? What else is it then? 😕

**Comment by Neme12** [comment]
I still think this should be reconsidered.

**Comment by eiriktsarpalis** [comment]
> with no additional cost.

Adding more interface implementations to exceedingly common types such as `string` does come with runtime overhead. I don't see a lot of value in adding this, most applications I can think of where you'd want to view strings as a list of chars you're better off using `ReadOnlySpan<char>` instead.

cc @jkotas

**Comment by Neme12** [comment]
But people do most commonly use `string` in practice, and people also use LINQ. This would just make that more efficient.

**Comment by Neme12** [comment]
I agree that people should use spans more, and I personally would use a span in the cases, but why not just make the code that people *already write, today*, more efficient?

**Comment by jkotas** [comment]
> > String isn't (logically) a collection of chars, so giving a read-only view seems off.

> It isn't? What else is it then?

String is (logically) sequence of code points. 

> Adding more interface implementations to exceedingly common types such as string does come with runtime overhead.

Yes, it is something to consider too, but it would not be my primary concern.

**Comment by Neme12** [comment]
As I said, I wouldn't do that personally, but people do actually do it in practice. E.g. people use `Last()` or `LastOrDefault()` instead of `str[str.Length - 1]` because it's more convenient and reads nicer.

**Comment by Neme12** [comment]
> String is (logically) sequence of code points.

Yes, and a sequence is a (kind of) collection.

**Comment by eiriktsarpalis** [comment]
> E.g. people use `Last()` or `LastOrDefault()` instead of `str[str.Length - 1]` because it's more convenient and reads nicer.

Using ranges it's now possible to write `str[^1]` to achieve the same thing instead.

**Comment by Neme12** [comment]
> As I said, I wouldn't do that personally, but people do actually do it in practice. E.g. people use `Last()` or `LastOrDefault()` instead of `str[str.Length - 1]` because it's more convenient and reads nicer.

And people do things like `str.ToArray()` and `str.ToImmutableArray()`, which would also become more efficient under this proposal.

**Comment by Neme12** [comment]
> > E.g. people use `Last()` or `LastOrDefault()` instead of `str[str.Length - 1]` because it's more convenient and reads nicer.
> 
> Using ranges it's now possible to write `str[^1]` to achieve the same thing instead.

I agree (except for the OrDefault one).

**Comment by eiriktsarpalis** [comment]
> And people do things like `str.ToArray()` and `str.ToImmutableArray()`, which would also become more efficient under this proposal.

This would be extremely inefficient compared to just taking its span. Could you point to examples or codebases where this would be beneficial?

**Comment by Neme12** [comment]
> > > 
> > 
> > 
> > Code point is not `char`. Code point is `Rune`.
> 
> But a `string` isn't a sequence of `Rune`, it's a sequence of `char`. Indexing indexes by `char`, not by code points. `String` already has a public API that exposes the contract of `IReadOnlyList<char>` - indexing by `char` and having a length, in chars.

Some abstract concept of a "string" may be thought of as a sequence of code points, but no `System.String`. `System.String` is a sequence of `chars` and you have to keep that in mind when indexing, doing `Substring` etc.

**Comment by Neme12** [comment]
> Could you point to examples or codebases where this would be beneficial?

I mean I guess I could search on https://grep.app/search?q=text.toarray&filter[lang][0]=C%23 although that's only a small part of the real usage because the variable might be named whatever other than `text`. Now I agree that in most, if not all of those cases, using `AsSpan()` is the better option. But the point is that people do have code like this today, and most developers still aren't familiar with spans, and this small change would make all that existing code more efficient.

**Comment by Neme12** [comment]
> The top hits in that list could be calling the dedicated ToCharArray() method instead

I agree, that sounds like a good idea for an analyzer.

**Comment by Neme12** [comment]
So does using `str[^1]` instead of `str.Last()` and `str[0]` instead of `str.First()`

**Comment by eiriktsarpalis** [comment]
I still don't see a compelling use case for implementing `IReadOnlyList` in string. Why do this just to optimize coding patterns that we don't want to encourage in the first place?

**Comment by Neme12** [comment]
I guess I don't really see a downside to implementing it, it just seems like goodness on multiple fronts to me - the perf benefits and the usability benefits of being able to pass a `string` to a method that takes `IReadOnlyList<char>`, like people have asked for before in other issues.

**Comment by DrkWzrd** [comment]
I didn't see the logic behind using `IReadOnlyList<char>` directly over the `string` when now we have the marvelous "zero" alloc Spans.

Why someone will choose to use an allocating way of do something that can be done "almost free"? Only for avoid using `.AsSpan()`?

The problem I see here is "I think `string` is a list of chars" and I think it isn't, a `string` isn't a collection/list, is a chain. The pure primitive unit that you recognizes as `string` is a wrapper (or merely helper methods https://github.com/torvalds/linux/blob/master/lib/string.c) around a chain of `char`s (and can be different types of chars, 7-8-16...) with known length or null-terminated. Is more like an `IEnumerable` than a `IList`. Is like and stream of bytes (essentially, everything is a stream of bytes from one block to another, haha).

And here, this a purely philosophical conversation rather than a developing improvement.

P.S.: IMHO. I think `string` is an echo of the past, an always-copying-itself monster, mantained only because is "the more common and straight way of manage text", `Span` and create helper methods (they already exist) to print for we, the inferior humans, is the way to go. Besides, it doesn't hurt getting dirty with slices, addresses, pointers and lengths from time to time.

**Comment by Neme12** [comment]
Not implementing it seems just as weird to me as something having a GetEnumerator() method and an enumerator but not actually implementing `IEnumerable` (except for ref structs), or as having a Dispose() method but not actually implementing `IDisposable` (again, except for ref structs). My view is that a class/struct should always implement all the standard interfaces that correspond to the functionality the class/struct *already provides*, as it only adds benefits for consumers of this API for no extra work. Please consider taking this viewpoint as well.

The way I came across this was when I tried passing a `string` to a method that took `IReadOnlyList<char>` and it struck me that it didn't work, as I would have expected it to.

**Comment by Neme12** [comment]
> > 
> 
> But a `string` isn't a sequence of `Rune`, it's a sequence of `char`. Indexing indexes by `char`, not by code points. `String` already has a public API that exposes the contract of `IReadOnlyList<char>` - indexing by `char` and having a length, in chars.

I *wish* it was a sequence of `Rune`s. Or better yet, a sequence of graphemes. But it's not - it's a sequence of `char` - it's indexed by `char` and has a length in `char`s, and everyone working with strings and doing indexing/slicing operations on them needs to know that fact - that it's not a sequence of code points or graphemes (which is what most people think of when they think of the word "character"), but rather a sequence of UTF-16 code units.

**Comment by CyrusNajmabadi** [comment]
These aren't compelling arguments for me.  Just because something can be a thing doesn't mean it should be that thing.  

> My view is that a class/struct should always implement all the standard interfaces that correspond to the functionality the class/struct already provides

Strong disagree.  I don't think people should really think of strings as collections of chars.  Indeed, i think people should move *away* from that thinking as much as possible as it's what really trips people up and causes them to get things wrong there all the time.  Compounding a problematic view of this type is not a positive to me.

**Comment by Neme12** [comment]
@CyrusNajmabadi What else should people think of strings as, if not a sequence of `char`s? I mean that's what it is, and every time you index into a string or slice it etc, you have to keep that fact in mind, that you're dealing with UTF-16 code units.

**Comment by CyrusNajmabadi** [comment]
> What else should people think of strings 

A sequence of runes. Which doesn't imply collection.

**Comment by Neme12** [comment]
> A sequence of runes

But it's not a sequence of runes :D If you assume that when you enumerate a string, you're enumerating runes, that's an incorrect assumption and you can introduce bugs as a result of that. Whenever you're enumerating/indexing/slicing a string, you have to keep in mind that you're working with UTF-16 code units, not runes.

**Comment by CyrusNajmabadi** [comment]
Right. And that's why I wouldn't add interfaces here. It only compounds a not good situation. 

Absent *hugely* compelling use cases here, I def would not do this.

**Comment by CyrusNajmabadi** [comment]
> Whenever you're enumerating/indexing/slicing a string, you have to keep in mind that you're working with UTF-16 code units, not runes.

And we shouldn't compound things by exposing even more single-char oriented collection operations.

Again, this request (and those that came before) lack highly compelling scenarios to motivate this. The argument that "just because it can implement an interface that it should" hold no weight for me.

**Comment by Neme12** [comment]
I would close this then as it seems there's no interest in this from the .NET team. But on the other hand, this keeps reappearing for some reason. All the previous closed issues, and I had just found a new one a few days ago: #97954. 🤔 And I think it would be unfair from me to everyone who upvoted this if I decided to close this on my own.

**Comment by Neme12** [comment]
> Right. And that's why I wouldn't add interfaces here. It only compounds a not good situation.

By the same logic though, did the ability to convert a `string` to a `ReadOnlySpan<char>` (i.e. a sequence of chars) make this situation worse as well? Was `ReadOnlySpan<char>` a mistake? 🤔 I don't quite understand the logic for why seeing a `string` as a `ReadOnlySpan<char>` is OK and desired but for `IReadOnlyList<char>` it isn't.

**Comment by CyrusNajmabadi** [comment]
No. Because the apis that operate on ROS<chat> explicitly understand that this is a sequence of utf16 Chars.  


Apis that take IList<char> almost certainly do not. This is another point in favor of not doing this.

**Comment by En3Tho** [comment]
Well, you should consider that Span and RO Span are very performant abstractions that support very fast indexing, splicing, can be easily backed up by pointer memory, are recognized by the jit, have special optimized overloads so they can be used as effective string replacements, etc
 
Interface doesn't give you these benefits. It just makes a virtual call every time you access a char. Not the same.

Also, with upcoming roles feature you will be able to extend types with whatever interface you want so if there is a strong demand in your particular codebase then nothing will stop you from doing that.

Also, for cases like first/last etc you could write an interceptor which will make those calls much faster and remove the need of interface implementation entirely. Perhaps, such an interceptor could be used across all of the ecosystem so maybe give it a try?
