### ISSUE TITLE
[Android][arm64] Use of undeclared identifier 'ICALL_SIG_TYPE__Bool'

### ISSUE THREAD

**Issue by simonrozsival** [dotnet/runtime#91779]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=399447
Build error leg or test failing: Build / android-arm64 Release AllSubsets_Mono / Build product
Pull request: https://github.com/dotnet/runtime/pull/91520

Android arm64 builds are failing (x64 and arm builds don't seem to be affected) with the following error:
```
 /__w/1/s/src/mono/mono/metadata/icall.c:7252:1: error: use of undeclared identifier 'ICALL_SIG_TYPE__Bool'; did you mean 'ICALL_SIG_TYPE_bool'?
```

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "(NETCORE_ENGINEERING_TELEMETRY=Build) The command \" cmake --build . --target install --config Release --parallel 4\" exited with code 2.",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=399447
**Error message validated:** `(NETCORE_ENGINEERING_TELEMETRY=Build) The command " cmake --build . --target install --config Release --parallel 4" exited with code 2.`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 9/8/2023 8:20:10 AM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[2263085](https://dev.azure.com/dnceng/internal/_build/results?buildId=2263085)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2263085/logs/863)||
|[2262965](https://dev.azure.com/dnceng/internal/_build/results?buildId=2262965)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2262965/logs/859)||
|[2262899](https://dev.azure.com/dnceng/internal/_build/results?buildId=2262899)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2262899/logs/877)||
|[399826](https://dev.azure.com/dnceng-public/public/_build/results?buildId=399826)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/399826/logs/280)|dotnet/runtime#91800|
|[2262858](https://dev.azure.com/dnceng/internal/_build/results?buildId=2262858)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2262858/logs/1039)||
|[2262801](https://dev.azure.com/dnceng/internal/_build/results?buildId=2262801)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2262801/logs/880)||
|[2262800](https://dev.azure.com/dnceng/internal/_build/results?buildId=2262800)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2262800/logs/157)||
|[2262760](https://dev.azure.com/dnceng/internal/_build/results?buildId=2262760)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2262760/logs/859)||
|[399499](https://dev.azure.com/dnceng-public/public/_build/results?buildId=399499)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/399499/logs/313)||
|[2262713](https://dev.azure.com/dnceng/internal/_build/results?buildId=2262713)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2262713/logs/875)||
|[399447](https://dev.azure.com/dnceng-public/public/_build/results?buildId=399447)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/399447/logs/25)|dotnet/runtime#91520|
|[399419](https://dev.azure.com/dnceng-public/public/_build/results?buildId=399419)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/399419/logs/272)|dotnet/runtime#91774|
|[2262662](https://dev.azure.com/dnceng/internal/_build/results?buildId=2262662)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2262662/logs/155)||
|[399203](https://dev.azure.com/dnceng-public/public/_build/results?buildId=399203)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/399203/logs/209)|dotnet/runtime#91713|
|[398919](https://dev.azure.com/dnceng-public/public/_build/results?buildId=398919)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/398919/logs/254)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|15|15|15|

**Comment by lambdageek** [comment]
Related to the C11 changes recently probably

**Comment by lambdageek** [comment]
We shouldn't use the bareword `bool` in macro magic

**Comment by lewing** [comment]
This should be resolved, waiting for a green build to close it.  There will be a follow-up to reintroduce the changes that were reverted.
