### ISSUE TITLE
Custom JsonIgnore condition

### ISSUE THREAD

**Issue by whoaskedfrfr** [dotnet/runtime#91789]
Hey,

Excuse me if this is not the right place to ask this, but here it goes. Is there a way to customize `JsonIgnore` condition?

As in, fully developer controlled thing? My idea was some kind of interface with single method `bool Ignore()` that is overridable. Is there something like this?

**Comment by Pentadome** [comment]
Better ask in https://github.com/dotnet/runtime/discussions
