### ISSUE TITLE
SslStream: Rewrite AuthenticateAs* handshake code to use async/await

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#918]
It's currently implemented with APM, with the Task-based APIs wrapping the legacy Begin/End APIs.  The internal implementation is a mess of callbacks that makes the logic difficult to follow, and incurs costs of transitioning between Tasks and APM at multiple stages.

**Comment by wfurt** [comment]
fixed by https://github.com/dotnet/runtime/pull/453. 
That change caused some regressions and follow-up changes are tracked by other issues.
