### ISSUE TITLE
Do not edit the file if the function is centered

### ISSUE THREAD

**Issue by NCLnclNCL** [dotnet/runtime#91837]
### Description

I use regex to read and edit files, but only the first and last functions work. I used notepad to check and found it unedited, if I bring it to the bottom of the function it works

### Reproduction Steps

using System.Text.RegularExpressions;
class regex
{

    static void Main()
    {
        Console.WriteLine("start");
        string basepath = @"background.js";
        string ct = File.ReadAllText(basepath);

        string pattern2 = "this.enableWhiteList=()=>{this.store.enabled=!0";
        string replacement2 = "this.enableWhiteList=()=>{this.store.enabled=!1";
        string result2 = Regex.Replace(ct, pattern2, replacement2);
        File.WriteAllText(basepath, result2);

        string pattern3 = "this.store={enabled:!0,whitelists";
        string replacement3 = "this.store={enabled:!1,whitelists";
        string result3 = Regex.Replace(ct, pattern3, replacement3);
        File.WriteAllText(basepath, result3);

        string pattern9 = "browser.windows.onFocusChanged.addListener";
        string replacement9 = "browser.windows.ncl?.onFocusChanged.addListener";
        string result9 = Regex.Replace(ct, pattern9, replacement9);
        File.WriteAllText(basepath, result9);

        string pattern4 = "template:{enabled:!0,whitelists";
        string replacement4 = "template:{enabled:!1,whitelists";
        string result4 = Regex.Replace(ct, pattern4, replacement4);
        File.WriteAllText(basepath, result4);

        Console.ReadKey();
    }
}

### Expected behavior

working for all

### Actual behavior

only first and last ones working,The middle ones won't work, if I swap the middle ones to the bottom it will work

### Regression?

dont known

### Configuration

.net core 8 preview 7
window 10
x64

**Comment by stephentoub** [comment]
It's not clear to me what problem you're having. Can you share a small repro, with the minimal but complete code necessary to highlight the problem, and show both what you get and what you expected to get?

**Comment by ovska** [comment]
You are writing all results to the same path, but you only load the file contents to `ct` once at the beginning.
