### ISSUE TITLE
Failure in building devcontainer with tag v7.0.9. 

### ISSUE THREAD

**Issue by KatsutoshiOtogawa** [dotnet/runtime#91836]
I get the following error when apt update with Docker file.

```
Err:1 https://dl.yarnpkg.com/debian stable InRelease 
The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
```

This is because the public key for the yarn package is out of date.
If you insert the following code between lines 12 and 13 of the .devcontainer/Dockerfile, the public key of the yarn package will be updated,
Docker Image can be built.

```dokerfile

# update yarn pubkey
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor --batch --yes -o /usr/share/keyrings/yarn-archive-keyring.gpg

```

A fix will be required when a new 7.0 series is released.

[yarn pkg pubkey issue](https://github.com/yarnpkg/yarn/issues/4505)

**Comment by NikolaMilosavljevic** [comment]
[Triage] @lbussell is this something our team owns? I don't see any previous changes by anyone on the team.

**Comment by NikolaMilosavljevic** [comment]
[Triage] This is not related to the .NET Docker containers - updating area.

**Comment by akoeplinger** [comment]
The devcontainer images are maintained by https://github.com/devcontainers/images/tree/main/src/dotnet so I'd suggest filing an issue there if you still see the issue. Thanks!
