### ISSUE TITLE
Can native aot run on windows 7?

### ISSUE THREAD

**Issue by codetool03** [dotnet/runtime#91830]
I use dotnet 8, it doesn't support win 7, but I compile native aot with windows 10, I want to ask, can it run in windows 7 ??

**Comment by jkotas** [comment]
The supported OS versions for native AOT are same as for other .NET runtime publish types.

If your .NET app works on Windows 7, nothing blocks you from running it there. However, any issues you run into on Windows 7 are unlikely to be fixed.
