### ISSUE TITLE
Dereference of a managed function pointer is not invariant

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#91846]
```cs
static void Test()
{
    for (int i = 0; i < 1000; i++)
        DoWork(&MyMethod);
}

static void MyMethod() {}

[MethodImpl(MethodImplOptions.NoInlining)]
static void DoWork(delegate*<void> _) {}
```

Codegen for `Test` with crossgen:
```asm
; Assembly listing for method Prog:Test() (FullOpts)
; ReadyToRun compilation
       push     rsi
       push     rbx
       sub      rsp, 40
       xor      ebx, ebx
       mov      rsi, qword ptr [(reloc 0x4000000000420068)] ; function address
G_M14333_IG03:
       mov      rcx, rsi
       call     [Prog:DoWork(ulong)]
       inc      ebx
       cmp      ebx, 0x3E8
       jl       SHORT G_M14333_IG03
G_M14333_IG04:
       add      rsp, 40
       pop      rbx
       pop      rsi
       ret
; Total bytes of code 41
```
Presumably, IND(ftnptr) should not be hoisted from the loop because it's not invariant in fact (e.g. tiering).

**Comment by MichalPetryka** [comment]
> Presumably, IND(ftnptr) should not be hoisted from the loop because it's not invariant in fact (e.g. tiering).

Doesn't it always return the address to the tiering stub?

**Comment by AndyAyersMS** [comment]
@EgorBo do we know for sure this always calls the Tier0 version?

**Comment by jakobbotsch** [comment]
Yeah, the function pointer here is pointing to the prestub (it has to since `&DoWork` must be a stable value), so it won't go to tier 0 after tiering. I don't think there is an issue here.
