### ISSUE TITLE
[API Proposal]: update ICustomQueryInterface signature to take the guid by in, not ref

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#91858]
### Background and motivation

We forgot to include this in #85911. Same concept, we should update the signature now that it's allowed:

```diff
namespace System.Runtime.InteropServices
{
    public interface ICustomQueryInterface
    {
-        CustomQueryInterfaceResult GetInterface([In]ref Guid iid, out IntPtr ppv);
+        CustomQueryInterfaceResult GetInterface(in Guid iid, out IntPtr ppv);
    }
}
```

**Comment by AaronRobinsonMSFT** [comment]
This would be a breaking change on a user implemented interface that has existed since [.NET Framework 4.0](https://learn.microsoft.com/dotnet/api/system.runtime.interopservices.icustomqueryinterface). This change also offers very little utility for the cost of breaking impact.

**Comment by Sergio0694** [comment]
Just so I understand, why would that be a breaking change? Is that because `in` would have `[In]` as a `modreq`? 🤔
Because as of C# 12, that signature change would not be a breaking change for non interface methods.

**Comment by AaronRobinsonMSFT** [comment]
> Because as of C# 12, that signature change would not be a breaking change for non interface methods

I can't comment on the C# 12 aspect of this, but the issue can be observed trivially [here](https://sharplab.io/#v2:C4LglgNgNAJiDUAfAAgJgIwFgBQPkGYACMAO2AFMAnAMwEMBjcwgSQEEcBvHQnw5AFkIBZABSVy1QgHEArmBiEA5gEoA3IQD0GwgGEZlSt15a+g0aWlyFK9SYCqABxi0KUQnUgBnHAF8ceIjRCVkIQFhCubF4+QLMxCUt5JWUjHkjov2wfIA). All currently implementers of this interface would be broken if the signature was changed.

**Comment by Sergio0694** [comment]
I mean of course, but this proposal was specifically relying on that signature change being legal in C# 12 😅

**Comment by stephentoub** [comment]
> I mean of course, but this proposal was specifically relying on that signature change being legal in C# 12

Even in C# 12 you can't implement an interface method taking an `in` parameter via a method that takes it as `ref`. They're incompatible.
