### ISSUE TITLE
HttpClient: Alt-Svc response header has partial value.

### ISSUE THREAD

**Issue by Indomitable** [dotnet/runtime#91868]
### Description

Hi,
    Yesterday I discovered that HttpClient doesn't return whole value of a response header.
Calling this public api: 
```
curl -v https://countriesnow.space/api/v0.1/countries/capital
```
returns:
![image](https://github.com/dotnet/runtime/assets/1831191/32a3f5e8-3c20-4130-b514-e4f58e40da57)
tested with other tools and the browser `alt-svc` has value: `h3=":443"; ma=86400`

while when using the HttpClient I get it  
![image](https://github.com/dotnet/runtime/assets/1831191/8e0331a3-9691-4915-b399-0001cd3a9b49)
where `Alt-Svc` has value of `h3=":443"`

OS: Linux
dotnet version: 7.0.302

### Reproduction Steps

Use HttpClient to get response headers from: `https://countriesnow.space/api/v0.1/countries/capital`

### Expected behavior

Header `alt-svc` should have value: `h3=":443"; ma=86400`

### Actual behavior

Header `alt-svc` has value: `h3=":443"`

### Configuration

OS: Linux
.NET: 7.0.302
Arch: x64

**Comment by ManickaP** [comment]
Value `ma=86400` is default value for max age = 24 hours, see https://httpwg.org/specs/rfc7838.html#rfc.section.3.1.
When we parse and reconstruct the header, we omit it because it is the same as not having this parameter.

**Comment by Indomitable** [comment]
Thank you @ManickaP, although that I don't like the behavior. My personal opinion is that framework classes should not try to be too smart, but I assume it is an architecture design so I'm closing the issue.
