### ISSUE TITLE
a question about CS1686

### ISSUE THREAD

**Issue by aknmjz** [dotnet/runtime#91861]
internal class Class2
    {
        public unsafe void Test(Class1 class1)
        {
            bool a = false;
            bool b = true;
            bool* p =&a;
            class1.TestEvent += () =>
            {
                a = true;
                Console.WriteLine(a);
            };
            class1.OnTestEvent();
        }
    }
CS1686: Local variable or its members cannot have their address taken and be used inside an anonymous method or lambda expression.
Why ?
is the lambda let `a` out of the stack frame?

**Comment by LeaFrock** [comment]
It's by design due to memory access security. 

>Some C# syntax is prohibited in lambda expressions and anonymous methods.

The [doc](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/lambda-expression-errors#syntax-limitations-in-lambda-expressions) is clear.
