### ISSUE TITLE
[LINQ] Combine Where and ToList() statement

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#91889]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/LINQ-Combine-Where-and-ToList-statem/10175763)._

---
I would like to suggest to have a new features in LINQ, which is to combine ToList() and Where() statement.

Example current code : 
```
List GoodEmployeeList = EmployeeList.Where(h => h.Performance > 0.8).ToList();
```

Suggested improvement :
```
List GoodEmployeeList = EmployeeList.ToList(h => h.Performance > 0.8);
```

---
#### Feedback Bot on 10/18/2022, 08:12 PM: 

(private comment, text removed)

**Comment by terrajobst** [comment]
The problem is that that there multiple sinks for queries, such as `ToArray()`, `ToList()`, `ToHashSet()` etc. Sure, some are more frequently used with others, but if we start merging `Where()` into the sinks I'm afraid it becomes a never ending project of adding more and more overloads.

**Comment by huoyaoyuan** [comment]
For me, it's extremely unclear when ToCollection takes a lambda: is it for Where, or Select? Both operations are commonly used.
