### ISSUE TITLE
ilc crash while compiling System.Text.Json.SourceGeneration.Roslyn tests

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#91885]
`/__w/1/s/artifacts/bin/coreclr/linux.arm64.Checked/build/Microsoft.NETCore.Native.targets(302,5): error MSB3073: The command ""/__w/1/s/artifacts/bin/coreclr/linux.arm64.Checked/x64/ilc/ilc" @"/__w/1/s/artifacts/obj/System.Text.Json.SourceGeneration.Roslyn4.4.Tests/Release/net9.0/native/System.Text.Json.SourceGeneration.Roslyn4.4.Tests.ilc.rsp"" exited with code 137.` 

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=400925
Build error leg or test failing: Build / linux-x64 Release NativeAOT_Libs
Pull request: https://github.com/dotnet/runtime/pull/91831

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "ilc.*System.Text.Json.SourceGeneration.Roslyn.*exited with code 137",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=400925
**Error message validated:** `ilc.*System.Text.Json.SourceGeneration.Roslyn.*exited with code 137`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 9/11/2023 3:20:56 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[431002](https://dev.azure.com/dnceng-public/public/_build/results?buildId=431002)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/431002/logs/69)|dotnet/runtime#93176|
|[425526](https://dev.azure.com/dnceng-public/public/_build/results?buildId=425526)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/425526/logs/69)|dotnet/runtime#92864|
|[424143](https://dev.azure.com/dnceng-public/public/_build/results?buildId=424143)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/424143/logs/84)||
|[422615](https://dev.azure.com/dnceng-public/public/_build/results?buildId=422615)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/422615/logs/84)||
|[422196](https://dev.azure.com/dnceng-public/public/_build/results?buildId=422196)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/422196/logs/84)||
|[415477](https://dev.azure.com/dnceng-public/public/_build/results?buildId=415477)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/415477/logs/69)|dotnet/runtime#92465|
|[415013](https://dev.azure.com/dnceng-public/public/_build/results?buildId=415013)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/415013/logs/61)|dotnet/runtime#92407|
|[414818](https://dev.azure.com/dnceng-public/public/_build/results?buildId=414818)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/414818/logs/69)|dotnet/runtime#92427|
|[414812](https://dev.azure.com/dnceng-public/public/_build/results?buildId=414812)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/414812/logs/67)|dotnet/runtime#92385|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|9|

**Comment by MichalStrehovsky** [comment]
ARM64 Linux and ILC is compiled with `OptimizationPreference=Speed`. Could be related to #86929.

**Comment by MichalStrehovsky** [comment]
> ARM64 Linux and ILC is compiled with `OptimizationPreference=Speed`. Could be related to #86929.

Ah, cross build to ARM64, not ARM64.

**Comment by jkotas** [comment]
Also, this looks like ILC running on CoreCLR. We need dumps for crashes during the build to make a good progress on issues like this one.

**Comment by agocke** [comment]
This looks like an OOM kill.

**Comment by jtschuster** [comment]
Reopening this as I'm seeing this in CI recently and it's blocking tests from being run.

Additional context: https://github.com/dotnet/runtime/issues/87078#issuecomment-1579859383

**Comment by MichalStrehovsky** [comment]
> Reopening this as I'm seeing this in CI recently and it's blocking tests from being run.

Where do you see this? I disabled the test on Linux in #95896

**Comment by jtschuster** [comment]
Ah, I saw it in https://github.com/dotnet/runtime/pull/95808 which last ran before that change was merged. Should we keep this open as the tracking issue?

**Comment by MichalStrehovsky** [comment]
> Ah, I saw it in #95808 which last ran before that change was merged. Should we keep this open as the tracking issue?

I don't think there's anything we can do about the test besides maybe completely disabling parallel build (I don't want to do that). It's a big test, and it's not platform specific, so we get enough coverage on Windows.
