### ISSUE TITLE
Linux Mono DsaNotDirectlySupported Rfc3279DerSequence failed to sign 

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#91898]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=401993
Build error leg or test failing: System.Security.Cryptography.X509Certificates.Tests.CertificateCreation.CrlBuilderTests.DsaNotDirectlySupported
Pull request: https://github.com/dotnet/runtime/pull/91892

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Signing key verifies the CRL",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=401993
**Error message validated:** `Signing key verifies the CRL`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 9/11/2023 9:09:17 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by vcsjones** [comment]
This seems... strange. I will stress the test and see if I can get it to reproduce, or if it was a transient failure.

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by vcsjones** [comment]
I think we should close this one out

1. I can't reproduce it
2. It has not been reported in several months
