### ISSUE TITLE
LINQ should have a PartitionTo operator

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#91890]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/LINQ-should-have-a-PartitionTo-operator/10206209)._

---
\[severity:Other\]  
It would be nice if LINQ were to have a `PartitionTo` operator that takes a predicate and two `ICollection` parameters. If the predicate returns `true` the value is added to the first `ICollection`, otherwise to the second. Alternatively, the first parameter could be a function that returns an integer that picks one of two or more destination collection parameters.

---
#### Feedback Bot on 11/20/2022, 08:01 PM: 

(private comment, text removed)
#### Chaojie Yang [MSFT] on 2/27/2023, 01:29 AM: 

(private comment, text removed)
#### Feedback Bot on 2/27/2023, 06:39 PM: 

(private comment, text removed)

**Comment by terrajobst** [comment]
This feels incredibly niche to me; I'm not convinced that this makes the bar for inclusion.

**Comment by eiriktsarpalis** [comment]
Agreed.

**Comment by reflectronic** [comment]
This is similar to https://github.com/dotnet/runtime/issues/39443 which was also rejected.

**Comment by daveyostcom** [comment]
Turns out that this functionality is available, as [`groupBy` in F#](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections-seqmodule.html#groupBy) and [`groupBy` in LINQ](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.groupby)
```F#
[1; 2; 3; 4; 5; 6]
|> Seq.groupBy (fun n -> n % 2 = 0)
|> Seq.iter (fun (key, group) ->
    printfn "%s:" (if key then "Even" else "Odd")
    for number in group do
        printfn "%d" number)
  (*
Odd:
1
3
5
Even:
2
4
6
  *)
```
