### ISSUE TITLE
SslStream RemoteCertificateValidationCallback cannot access protocol/cipher info

### ISSUE THREAD

**Issue by DaveRandom** [dotnet/runtime#919]
The `RemoteCertificateValidationCallback` is [documented](https://msdn.microsoft.com/en-us/library/ms145057(v=vs.110).aspx?f=255&mspperror=-2147217396#Anchor_2) as being able to access these values and potentially choose to reject the connection based on them:

> The security protocol and cryptographic algorithms are already selected when the `userCertificateValidationCallback` delegate's method is invoked. You can use the method to determine whether the selected cryptographic algorithms and strengths are sufficient for your application. If not, the method should return false to prevent the `SslStream` from being created.

Currently this doesn't work, because attempting to access them [throws an `InvalidOperationException`](https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/src/System/Net/Security/SslState.cs#L244). Ideally, please can this be fixed to work as documented (I only skimmed the code briefly but I don't see any need for the `authSuccessCheck` here?).

If it's not practical to make it work as advertised for some reason, please can the documentation be fixed - which I will happily do myself if someone points me in the direction of the right place to PR.

N.B. I am trying to implement this with `AuthenticateAsServer()`, I haven't checked whether it may work as documented for a client-side stream, I will try it out when I can and update the issue if no-one else has checked it first.

Related to https://github.com/dotnet/corefx/issues/24588 / https://github.com/dotnet/corefx/issues/21577 in the sense that if I was able to specify the cipher set that can be used, I wouldn't need to do this as I could simply disable the ciphers I want to disallow with high-level configuration rather than manually checking per-connection.

**Comment by karelz** [comment]
@wfurt is it dupe of the work you're tracking?

**Comment by wfurt** [comment]
it is not. but easy enough to fix.
