### ISSUE TITLE
[Http Metrics] Replace http.error.reason with OTel standard error.type

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#91909]
Align attribute name and semantics with the OpenTelemetry spec (which was finalized yesterday 2023/9/11 - see https://github.com/open-telemetry/semantic-conventions/pull/205) -- `http.error.reason` attribute has been standardized under name `error.type`. We need to:
- Rename `http.error.reason` to `error.type`.
- Report `error.type` also for valid responses where the HTTP status code indicates an error (4xx and 5xx) -- in such case, the value should be the string representation of the HTTP status code.
    - Note: Currently we report `http.error.reason` only when the underlying handler fails to fetch a response.

See `error.type` in [the spec](https://github.com/open-telemetry/semantic-conventions/blob/2bad9afad58fbd6b33cc683d1ad1f006e35e4a5d/docs/http/http-spans.md#common-attributes) for more details.

For context: We introduced the attribute `http.error.reason` in PR #89809 (on 2023/8/3) based on the in-progress draft of the OTel spec (https://github.com/open-telemetry/semantic-conventions/pull/205).

Given that this is new 8.0 feature, we should adapt to the spec in 8.0 to avoid breaking changes with 9.0.

**Comment by karelz** [comment]
Reopening to track backport to 8.0

**Comment by karelz** [comment]
Fixed in main (9.0) in PR #91910 and in 8.0 (RC2) in PR #91996
