### ISSUE TITLE
Should GeneratedRegex method be static?

### ISSUE THREAD

**Issue by EgoPingvina** [dotnet/runtime#91927]
MSDN contains an example how to use `GeneratedRegex `, where the method is marked as `static`.
https://learn.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-source-generators#source-generation
Should it be `static` or in which case it should be like this?

**Comment by alexrp** [comment]
I *think* the source generator allows `[GeneratedRegex]` on instance methods, though that seems like an odd thing to do given that the generated `Regex` object is a singleton.
