### ISSUE TITLE
IHostedService.StopAsync(...) not called when SIGTERM issued on ACA

### ISSUE THREAD

**Issue by emilmuller** [dotnet/runtime#91926]
Hi,

I'm deploying a .NET 7 web application to ACA (Azure Container Apps). It's based on this Docker base image: mcr.microsoft.com/dotnet/aspnet:7.0.

I have an IHostedService which implements StartAsync and StopAsync. **StopAsync does not seem to get triggered**. There is nothing in the ACA console logs either, from when a specific replica is taken down. The logs just have a hard stop.

Given that ACA is based on Kubernetes, I'm inclined to think that a SIGTERM is indeed issued, but not handled correctly by .NET 7.

According to this, there should be a 30 second delay after a SIGTERM is issued, until it is taken down: https://learn.microsoft.com/en-us/azure/container-apps/application-lifecycle-management.

Kind regards, Emil

**Comment by am11** [comment]
Does this answer help: https://stackoverflow.com/a/73498966/863980?

**Comment by emilmuller** [comment]
> Does this answer help: https://stackoverflow.com/a/73498966/863980?

Unfortunately, those methods aren't available in .NET 7. At least when using

`var builder = WebApplication.CreateBuilder(args);`

**Comment by emilmuller** [comment]
> Does this answer help: https://stackoverflow.com/a/73498966/863980?

I was optimistic at one point there. The code can't be copied exactly, so I modified it slightly to fit .NET 7:

```
var builder = WebApplication.CreateBuilder(args);

builder.Host.UseConsoleLifetime();
```

But still, StopAsync is not called. My app is abruptly terminated.

**Comment by am11** [comment]
I did an experiment.

`web01/web01.csproj`
```csproj
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
```

`web01/Program.cs`
```c#
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

internal static class Program
{
    public static async Task Main()
        => await new HostBuilder()
            .UseConsoleLifetime()
            .ConfigureServices(s => s.AddHostedService<MyBackgroundService>())
            .ConfigureLogging(l => l.AddConsole())
            .Build()
            .RunAsync();
}

internal sealed class MyBackgroundService : IHostedService
{
    private readonly ILogger<MyBackgroundService> _logger;

    public MyBackgroundService(ILogger<MyBackgroundService> logger)
    {
        _logger = logger;
    }

    public Task StartAsync(CancellationToken cancellationToken)
    {
        _logger.LogInformation("StartAsync called");
        return Task.CompletedTask;
    }

    public Task StopAsync(CancellationToken cancellationToken)
    {
        _logger.LogInformation("StopAsync called");
        return Task.CompletedTask;
    }
}
```

`web01/Dockerfile`
```dockerfile
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /app
COPY ./ ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "web01.dll"]
```

in terminal 1:
```sh
$ docker build . -t app1 
$ docker run --name app1_i1 app1
```

in terminal 2:
```sh
$ docker stop app1_i1
```

in terminal 1, I see:
```
info: MyBackgroundService[0]
      StartAsync called
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app/
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
info: MyBackgroundService[0]
      StopAsync called
```

Same output if I explicitly pass SIGTERM

```sh
# create new instance (i2) in terminal 1
$ docker run --name app1_i2 app1

# in terminal 2, kill it with SIGTERM
$ docker kill --signal=SIGTERM app1_i2

# terminal 1 now shows "StopAsync called"
```

If deploying this to ACA doesn't yield the same result, you can probably capture the exact signal the pod is sending to app to it figure out locally.

**Comment by steveharter** [comment]
This could be an ACA issue; see [Replica not shutting down gracefully (no SIGTERM sent/received) on consumption workload profile + VNet](https://github.com/microsoft/azure-container-apps/issues/802) which has the constraints:
_Our setup uses an environments with a default consumption workload profile, combined with a custom VNet.
As a comparison we tested with the 'older' environments (without workload profiles and without VNet). In that case all seems to be working as expected_

@emilmuller does this match your environment and\or sound familiar?
