### ISSUE TITLE
how override array with env

### ISSUE THREAD

**Issue by yedajiang44** [dotnet/runtime#91939]
### Describe

I have a `appsetting.json` file:

```json
{
  "array": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
}
```

I went reset to three items like this in docker compose:

```docker
array__0: 11
array__1: 22
array__2: 33
```

But I still get 10 items `[11,22,33,4,5,6,7,8,9,10]`, so how to override array not reset item?

---

Tried the following env, but still got 10 items:

```docker
array__0: 11
array__1: 22
array__2: 33
array__Length: 3
```

### Further

|        |               |
| ------ | ------------- |
| sdk    | net 7.0       |
| os     | win and linux |
| vscode | 1.82.0        |

**Comment by tarekgh** [comment]
Yes, this has been discussed in https://github.com/dotnet/runtime/issues/36569 and decided no plan to change the current design or to support this behavior in the near future. If we see more demand on that in the future we can try to support that though some flag or API to enable that.

**Comment by yedajiang44** [comment]
I got it, thanks for your time. @KalleOlaviNiemitalo @tarekgh

**Comment by yedajiang44** [comment]
oh god~ thanks! I'll try it tomorrow. @KalleOlaviNiemitalo
