### ISSUE TITLE
NET 6.0 do not recognise encoding 1252, is there an easy way to add

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#91940]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-60-do-not-recognise-encoding-1252-/10371190)._

---
[severity:I'm unable to use this version]
I tried to upgrade my app to use NET 6.0 but it's not possible because 'encoding 1252' is not recognized. I just get  the warning "'Site' must not be null in order to access a required service", or an error "System.NotSupportedException: 'No data is available for encoding 1252".  What 'required service' for what 'Site'?
The app works fine using NET 4.8, but I can't use any of the newer features of Visual Studio.

---
#### Feedback Bot on 5/22/2023, 06:33 PM: 

(private comment, text removed)
#### John Qiao [MSFT] on 5/23/2023, 00:16 AM: 

(private comment, text removed)
#### Tom Loewen on 7/16/2023, 09:28 AM: 

(private comment, text removed)
#### Tom Loewen on 5/23/2023, 10:47 AM: 

(private comment, text removed)
#### John Qiao [MSFT] on 5/23/2023, 07:40 PM: 

(private comment, text removed)
#### Tom Loewen on 5/26/2023, 07:39 PM: 

(private comment, text removed)
#### Feedback Bot on 5/28/2023, 08:10 PM: 

(private comment, text removed)
#### Andy Gocke [MSFT] on 7/5/2023, 02:23 PM: 

(private comment, text removed)
#### Tom Loewen on 7/7/2023, 06:00 AM: 

(private comment, text removed)
#### Andy Gocke [MSFT] on 7/13/2023, 11:10 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by tarekgh** [comment]
You may follow the [doc](https://learn.microsoft.com/en-us/dotnet/api/system.text.encodingprovider?view=net-7.0#remarks) for more explanation how to enable the codepage encodings. In short, in the app initialization call:

```C#
// https://learn.microsoft.com/en-us/dotnet/api/system.text.codepagesencodingprovider.instance?view=net-7.0#remarks
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance)
```
