### ISSUE TITLE
ARM JIT support for "jump stamps" for ReJIT

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/runtime#9194]
ReJIT sometimes needs to replace the first bytes of a JIT-generated method's prologue with a branch to replacement code.  We need to decide what that branch looks like to determine the minimum size of a prologue when ReJIT support is required.  Also, enable support for generating said minimum-sized prologues.

category:reach
theme:runtime
skill-level:expert
cost:small

**Comment by jkotas** [comment]
We are no longer using jump stamps after https://github.com/dotnet/coreclr/pull/26740
