### ISSUE TITLE
Process::TotalProcessorTime is about 42 times lower than expected on ARM64 Mac

### ISSUE THREAD

**Issue by ForNeVeR** [dotnet/runtime#91958]
### Description

Let's consider this process on my system that has PID of 66358 (as shown by the Activity Monitor):
<img width="409" alt="image" src="https://github.com/dotnet/runtime/assets/92793/eb2fe61c-6352-4cf9-8cbf-4a5347910a72">

It has about 22 hours of CPU time.

### Reproduction Steps

Write and run this program:
```csharp
using System.Diagnostics;

var process = Process.GetProcessById(66358);
Console.WriteLine(process.TotalProcessorTime);
Console.WriteLine(process.TotalProcessorTime * 42);
```

### Expected behavior

This program should output about 22 hours in the first line, and some nonsensical value in the second line.

### Actual behavior

```
00:00:32.3739259
00:22:39.7048878
```

### Known Workarounds

Multiply the result by 42 on ARM64 Mac :)

### Configuration

Macbook Pro M2 Max, ARM64
.NET SDK 7.0.202

### Other information

This is not the first time this API behaves problematically on macOS. The previous fix was https://github.com/dotnet/corefx/pull/37637

I suspect that the fix was incorrect: in reality, we should call `mach_timebase_info` to get the coefficient to convert the value returned by the underlying API to nanoseconds, and apparently that value may be system-dependent.

**Comment by adamsitnik** [comment]
Hi @ForNeVeR 

Thank you for a detailed bug report. Since you have tracked down the issue, would you be also interested in sending a PR with a fix?

**Comment by ForNeVeR** [comment]
Yep, sure, I'll try to get it done.
