### ISSUE TITLE
Perf pipeline broken with `dpkg was interrupted, you must manually run 'sudo dpkg ...`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#91959]
This is on PERFTIGER172, and for some reason all the jobs got scheduled on that (maybe because each completed so quickly?).

```
+ sudo apt-get -y install python3-venv
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
```

cc @LoopedBard3 @cincuranet

**Comment by LoopedBard3** [comment]
Getting PERFTIGER172 taken offline to give more time to look into this problem.

**Comment by LoopedBard3** [comment]
Once offline, I will rerun the pipeline since all the packages are already built and machines open for testing to see if any other machines are hitting problems. It also looks like affecting most linux x64 runs.

**Comment by LoopedBard3** [comment]
Was able to repro on the machine over ssh and attempting to run the failing "sudo apt-get -y install python3-venv". After running the suggested fix of "sudo dpkg --configure -a" the python3-venv install worked as expected. Waiting to add machine back into the queue until after the restarted run finishes and it shows this as a likely a transient error.

**Comment by LoopedBard3** [comment]
Having the machine reactived. Will close after making sure the machine doesn't cause more errors once added.
