### ISSUE TITLE
Test ARM32 fast tailcall hook for profiler

### ISSUE THREAD

**Issue by sywhang** [dotnet/runtime#9196]
Profiler ELT hooks for ARM32 tailcall has not been tested yet, because JIT optimizations for tailcall is missing on ARM32. The tailcall hook for arm32 has already been added by @rartemev with dotnet/coreclr#14713, so once JIT optimizations are added in, we need to test this hook.

**Comment by davmason** [comment]
At this point there are ELT tests up and running on arm32, so I am assuming the issue is fixed.
