### ISSUE TITLE
[API Proposal]: `Array.Sort` overloads with `Comparison` delegate

### ISSUE THREAD

**Issue by timcassell** [dotnet/runtime#91970]
### Background and motivation

Because `Array.Sort` accepting an `IComparer<T>` allocates (https://github.com/dotnet/runtime/issues/69701), I would like an overload to pass in the `Comparison` delegate directly to avoid such allocation.

### API Proposal

```csharp
public static void Sort<T> (T[] array, int index, int length, Comparison<T> comparison);

public static void Sort<TKey,TValue> (TKey[] keys, TValue[]? items, Comparison<TKey> comparison);

public static void Sort<TKey,TValue> (TKey[] keys, TValue[]? items, int index, int length, Comparison<TKey> comparison);
```

### API Usage

```csharp
Array.Sort(myArray, 0, count, (item1, item2) => item1.Key.CompareTo(item2.Key));
```

**Comment by stephentoub** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/23587, which we ended up not being able to do because of ambiguity issues.

**Comment by timcassell** [comment]
Ah, that's unfortunate. Well, at least there's a workaround.

```cs
new Span<MyType>(myArray, 0, count).Sort((item1, item2) => item1.Key.CompareTo(item2.Key));
```
