### ISSUE TITLE
[API Proposal]: InitialCapacity for CborWriter

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#91978]
### Background and motivation

The `CborWriter` class currently has an internal buffer that grows as data is written to the buffer.

Callers that write large CBOR documents may end up spending a significant amount time constantly re-allocating and copying the buffer as it grows. This was observed in #91969. In this scenario, 98% of the time spent was in `Array.Resize`.

Callers that know before hand that they are going to write a large CBOR document currently don't have an easy way to give a hint that the internal buffer should be larger than the default.

Conversely, callers that know they are going to create small CBOR documents may give a smaller-than-the-default hint to avoid over-allocating the internal buffer.

This is similar to [what we did for AsnWriter](https://github.com/dotnet/runtime/issues/69573) except now we are doing it for `CborWriter`.

### API Proposal

```C#
namespace System.Formats.Cbor;

public partial class CborWriter {
    public CborWriter(int initialCapacity, CborConformanceMode conformanceMode = CborConformanceMode.Strict, bool convertIndefiniteLengthEncodings = false, bool allowMultipleRootLevelValues = false);
}
```

### API Usage

```csharp
CborWriter writer = new CborWriter(initialCapacity: 10000000);
// write 1000000 bytes of stuff to the writer.
```

**Comment by eiriktsarpalis** [comment]
Sounds reasonable to me.

**Comment by bartonjs** [comment]
* We changed from an initial required parameter to a trailing defaulted parameter (and consequently will update the existing constructor to no longer have defaults, and now be never-browsable

```C#
namespace System.Formats.Cbor;

public partial class CborWriter {
    [EditorBrowsable(Never)]
    public CborWriter(
       CborConformanceMode conformanceMode,
       bool convertIndefiniteLengthEncodings,
       bool allowMultipleRootLevelValues);

    public CborWriter(
       CborConformanceMode conformanceMode = CborConformanceMode.Strict,
       bool convertIndefiniteLengthEncodings = false,
       bool allowMultipleRootLevelValues = false,
       int initialCapacity = -1);
}
```
