### ISSUE TITLE
System.IO.FileSystem.AccessControl can't set ACLs on files with long paths

### ISSUE THREAD

**Issue by hach-que** [dotnet/runtime#91980]
### Description

When attempting to set ACLs on a file with a long path on Windows, `SetAccessControl` throws `ArgumentException: Invalid name`:

```
Failed to grant Everyone full control of 'C:\ProgramData\UET\SDKs\Android-android-33-33.0.1-3.10.2.4988404-25.1.8937393-jdk-11.0.19+7\Sdk\cmdline-tools\lib\external\com\google\guava\listenablefuture\9999.0-empty-to-avoid-conflict-with-guava\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar'. Exception was: System.ArgumentException: Invalid name. (Parameter 'name')    at System.Security.AccessControl.NativeObjectSecurity.Persist(String name, SafeHandle handle, AccessControlSections includeSections, Object exceptionContext)    at System.Security.AccessControl.FileSystemSecurity.Persist(String fullPath)
```

### Reproduction Steps

```csharp
var dacl = file.GetAccessControl(AccessControlSections.Access);
dacl.AddAccessRule(new FileSystemAccessRule(_everyoneWindows.Value, FileSystemRights.FullControl, AccessControlType.Allow));
file.SetAccessControl(dacl);
```

where `file` is a `FileInfo` pointing to a file with a long path.

### Expected behavior

`SetAccessControl` should work with long paths on Windows.

### Actual behavior

`SetAccessControl` throws `ArgumentException: Invalid name`.

### Known Workarounds

I tried to workaround this with this code:

```csharp
var dacl = new FileSecurity(@"\\?\" + file.FullName, AccessControlSections.Access);
dacl.AddAccessRule(new FileSystemAccessRule(_everyoneWindows.Value, FileSystemRights.FullControl, AccessControlType.Allow));
dacl.Persist(@"\\?\" + file.FullName);
```

however, `Persist` is internal/protected and not available to user code. You also can't inherit from `FileSystemSecurity` to access the protected method, as all constructors on that class are internal.

### Configuration

.NET 7

**Comment by adamsitnik** [comment]
Triage: I've marked this issue as `help wanted`. Whoever wants to work on it should attach a debugger and see which sys-call is being used in that scenario:
- the one that takes a name: https://github.com/dotnet/runtime/blob/35fc3c087c3729947b4eddbca5d87951addce012/src/libraries/System.Security.AccessControl/src/System/Security/AccessControl/Win32.cs#L278C44-L278C45
- the one that takes a handle:  https://github.com/dotnet/runtime/blob/35fc3c087c3729947b4eddbca5d87951addce012/src/libraries/System.Security.AccessControl/src/System/Security/AccessControl/Win32.cs#L290

I suspect it's the one that takes the `string name`. In such case we need to ensure that we call the sys-call in the right way, if we do and it's impossible to get it working we should most likely open the file on our own via `File.OpenHandle` and use the sys-call that accepts a file handle.
