### ISSUE TITLE
Network Traffic Statistics on Linux

### ISSUE THREAD

**Issue by skyoxZ** [dotnet/runtime#91982]
Recently I'm working on getting network traffic (bytes received/sent) on Linux. I learned that it can be done by reading `/proc/net/dev`. But later I found this has already been implemented in `NetworkInterface` and it just does the same thing: parsing `/proc/net/dev`.

https://github.com/dotnet/runtime/blob/3aeefbdd5e975e287effaa8670422837dc661d68/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/StringParsingHelpers.Statistics.cs#L404-L446

I notice that it uses `line.Contains(name)` to locate the specific adapter. I'm curious if it's safe to do so. For example, is it possible that both `eth1` and `eth10` exist?

**Comment by wfurt** [comment]
The `Contains` seems problematic. However, the file seems to be ordered by interface index and it would work IMHO if `eth10` comes after `eth1`. But we should probably fix it anyway.

**Comment by Clockwork-Muse** [comment]
Various parts of Linux allow you to rename various devices, including network interfaces.  I've had to do that for a device deployment.  

I don't know if this file would be safe from or subject to the  naming restrictions, but "interface index" might not be safe in those cases.

**Comment by gfoidl** [comment]
Aside from that https://github.com/dotnet/runtime/blob/3aeefbdd5e975e287effaa8670422837dc661d68/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/StringParsingHelpers.Statistics.cs#L411-L416 the `stackalloc` inside the loop may also be problematic. (isn't there an analyzer flagging this?)

**Comment by MihaZupan** [comment]
We'll return right after the `stackalloc`, so it's fine in this case given it'll only run once.
