### ISSUE TITLE
.NET 8 RC1 can not compile with Windows app sdk and CsWinRT

### ISSUE THREAD

**Issue by Gaoyifei1011** [dotnet/runtime#91981]
### Description

.NET 8 RC1 can not compile with Windows app sdk and CsWinRT

In.net8 RC1, the Marshal.QueryInterface() method is defined from
public static int QueryInterface (IntPtr pUnk, ref Guid iid, out IntPtr ppv);
Become a
public static int QueryInterface (IntPtr pUnk, in Guid iid, out IntPtr ppv);
Please update the content in WinRT.cs immediately, otherwise the application will not compile

![image](https://github.com/microsoft/WindowsAppSDK/assets/49179966/6e70d625-fb75-49dc-9a31-6a1c72559a29)

### Reproduction Steps

In describe bug

### Expected behavior

In describe bug

### Actual behavior

The Marshal.QueryInterface() method should be compatible with both ref and in arguments

### Configuration

.NET 8 RC1
Windows App SDK 1.4.0
CSWINRT 2.0.3

### Other information

None

**Comment by AaronRobinsonMSFT** [comment]
This seems like a breaking change introduced in https://github.com/dotnet/runtime/pull/89736.

@tannergooding I don't see any mitigations for the above change. There should have been a breaking change discussion, I wasn't involved so am unclear how to frame this to users.

**Comment by AaronRobinsonMSFT** [comment]
@Gaoyifei1011 The change to `in` here was a bit too aggressive. It should be either `ref readonly` or stay as `ref`. I will put up a PR shortly.

**Comment by Gaoyifei1011** [comment]
> @Gaoyifei1011 The change to `in` here was a bit too aggressive. It should be either `ref readonly` or stay as `ref`. I will put up a PR shortly.

OK.Thanks for the quick fix

**Comment by hamarb123** [comment]
@Gaoyifei1011 could you please see https://github.com/dotnet/runtime/pull/91983#issuecomment-1717253358. Specifically, I'm interested if you have set warnings to errors, and if so you should be able to get VS to generate a `#pragma warning disable` for you to ignore the warning. Or are you using an outdated version of roslyn / VS preview, which may be causing it to show as an error?
