### ISSUE TITLE
[mono] Android x64: No pending exception expected: java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by jandupej** [dotnet/runtime#92000]
Occurred on `Build android-x64 Release AllSubsets_Mono_RuntimeTests minijit` and `android-x64 Release AllSubsets_Mono_RuntimeTests_Interp monointerpreter`.

Log: https://[helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-91925-merge-14240024556a44e6be/PayloadGroup0/1/console.18bcda7f.log?helixlogtype=result](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-91925-merge-14240024556a44e6be/PayloadGroup0/1/console.18bcda7f.log?helixlogtype=result)

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=402917
Build error leg or test failing: baseservices/exceptions/unhandled/unhandled/unhandled.sh
Pull request: https://github.com/dotnet/runtime/pull/91925

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Abort message: 'No pending exception expected: java.lang.ClassNotFoundException: throw",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=402917
**Error message validated:** `Abort message: 'No pending exception expected: java.lang.ClassNotFoundException: throw`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 9/13/2023 12:21:14 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by simonrozsival** [comment]
The test was disabled in https://github.com/dotnet/runtime/pull/92728 and is being tracked in https://github.com/dotnet/runtime/issues/92723
