### ISSUE TITLE
[API Proposal]: Interportability between Diagnostics.TraceLevel and Diagnostics.SourceLevels

### ISSUE THREAD

**Issue by patelmitul** [dotnet/runtime#92004]
## Background and Motivation
Many times we define log filter in settings file and those values may be defined as string in JSON. In the code we will use those values two different ways. First wither to log file using one of the conditional statement and other way we will write to log and let log filter it later on. In first case the TraceLevel enum will be used while in log filter the SouceLevel enum will be used. 
As of right now only Info/Information is the only enum which is in both but defined differently thus we can't parse the string value interchangeably. I only see benefit by allowing string to be parsed by either enum.

## API Proposal
Add these two enum values in [Diagnostics.TraceLevel](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.TraceSource/src/System/Diagnostics/TraceLevel.cs)
Critical = 1
Information = 3

Add this one enum value in [Diagnostics.SourceLevels](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.TraceSource/src/System/Diagnostics/SourceLevels.cs)
Info = 0x0F

## API Usage
```
string str = "Info";

System.Diagnostics.TraceLevel traceLevel = (System.Diagnostics.TraceLevel) Enum.Parse(typeof(System.Diagnostics.TraceLevel), str);
System.Diagnostics.SourceLevels filterLevel = (System.Diagnostics.SourceLevels) Enum.Parse(typeof(System.Diagnostics.SourceLevels), str);
```

This will allow "String" value to be parse-able by either one of these diagnostic levels.
This will help making custom trace switch "Info" to work with both `Trace.WriteLineIf(_traceSwitch.TraceInfo, "Msg")` and at source level using `Trace.TraceInformation("Msg")` 

## Alternative Designs
As of now Critical enum is in SourceLevel but not in TraceLevel. It may be a part of discussion if we want to add that enum in TraceLevel to be same as Error.

## Risks
Low

## Benefits
Allowing string to be parsed by either enum will add more flexibility and less errors.

**Comment by ericstj** [comment]
This looks like an API suggestion to add new enum names that overlap with existing values.  @patelmitul could you please format your issue like an API request?  https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md#steps

**Comment by ericstj** [comment]
Getting late in .NET 9.0 for this one, moving out and marking ready for review.  Adding a couple overlapping enum values.

**Comment by tarekgh** [comment]
I am not sure if this proposal is correct. In `SourceLevel`, the `Critical` and `Error` have different values `1` and `3`. While the proposal suggesting adding `Critical` to `TraceLevel` with value `1` which is same as the defined `Error` value in that Enum? 

Are we sure we want to do that? 

CC @ericstj
