### ISSUE TITLE
Unsafe.AsRef in .NET 8 RC-1 

### ISSUE THREAD

**Issue by virzak** [dotnet/runtime#92008]
### Description

`public static ref T AsRef<T>(scoped in T source)`

being changed into

`public static T ReadUnaligned<T>(ref readonly byte source)`

Is a breaking change despite #89736 stating otherwise.

### Reproduction Steps

```cs
var mySpan = MemoryMarshal.CreateSpan(ref Unsafe.AsRef(1 + 2), 1);
Console.WriteLine(mySpan[0]);
```

### Expected behavior

`3` should be printed

[sharplab](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAIAYAEqCMA6AJWmAEsBbAUzwGEB7MgBxIBsKwBlNgNxIGMKAzgG4AsACgM2fESilKeAJKy2tBpzA9+w8agBMOHQGZsuzNUwBvcZhsnTVsbaeYuAQzCYyAT3YNXUTABeTABZCjJaMC8Q9wEAC1dmGjAKV2AKX38AChSAM0wAVSgBV1yqAEEBAgpcrJxMRExdAEoYTBxm0UdnG1wATizvTKgAbXQAXU7rWwBfcRmgA=)

### Actual behavior

Compilation error:

Error	CS1620	Argument 1 must be passed with the 'ref' keyword

### Configuration

.NET 8 RC-1 

### Other information

FYI @tannergooding

**Comment by stephentoub** [comment]
For your repro, I get:
```
warning CS9193: Argument 1 should be a variable because it is passed to a 'ref readonly' parameter
```
not an error.  And the warning is highlighting exactly what it was intended to highlight, that you're getting a ref to an rvalue.

What does your repro csproj look like?  What version of the C# compiler are you using?  It sounds like you might be using an older one (is this in a Visual Studio build that might not be up-to-date rather than from the command-line)?

**Comment by virzak** [comment]
So sorry,  had my `TreatWarningsAsErrors` on. Not an issue.

**Comment by virzak** [comment]
And yeah. Version 17.8.0 Preview 1.0 shows CS1620, but compilation doesn't fail.

**Comment by rickbrew** [comment]
This is happening for me too. I am not getting a warning, it is error CS1620, and compilation does fail. `Unsafe.AsRef(in foo)` does not work at all and I'm completely blocked. Only started happening when I installed the RC1 SDK. I'm on VS 2022 17.8.0 Preview 1.0, it says it's up-to-date.

BTW it does work if I run `dotnet build` outside of VS (as per @reflectronic 's suggestion). So I guess we just hope a new VS 2022 Preview update comes out ........ soon?

```cs
public static class ReadOnlySpan
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ReadOnlySpan<T> Create<T>(in T element, int length = 1)
    {
        return MemoryMarshal.CreateReadOnlySpan(ref Unsafe.AsRef(in element), length);
    }
}
```
