### ISSUE TITLE
[API Proposal]: Analyzer to detect if method called twice

### ISSUE THREAD

**Issue by HakamFostok** [dotnet/runtime#92018]
### Background and motivation

Some methods should not be called twice inside the same caller method. <br/>
It could lead to at least performance degradation in the best case or some subtle errors in the worst case. <br/>
The best example I can come up with is the extension methods that are used to register services in ASP.NET CORE, What are the benefits of calling `services.AddHttpContextAccessor()` twice? <br/>
Sometimes there is middleware that should be registered twice. <br/>
Of course, the user code would use this feature also.
I would suggest adding an attribute and the analyzer will use to detect if this method is called twice (considering the passing of the same parameters)

### API Proposal

```csharp
namespace System.Runtime.CompilerServices;

[System.AttributeUsage(System.AttributeTargets.Method, AllowMultiple = false)]
public sealed class PreventMethodBeingCalledTwiceAttribute : Attribute
{
}
```

### API Usage

```csharp
public static class Test 
{
   [PreventMethodBeingCalledTwiceAttribute]
   public static void Method() {}
}

public class OtherClass 
{
    public void Caller() 
    {
          Test.Method(); // no warning from the compiler
          Test.Method(); // compiler will give a warning on this line
    }
}
```

**Comment by KennethHoff** [comment]
This is highly domain specific and also a fairly easy analyzer to create. Try to create one yourself first and come back here if you get stuck! 🫡

**Comment by stephentoub** [comment]
Thanks for the idea. As was suggested, this would be better for now in a custom nuget package rather than built into the SDK.
