### ISSUE TITLE
CustomMarshaller uses confusion

### ISSUE THREAD

**Issue by Gsonovb** [dotnet/runtime#92049]
Hi, everybody

I was recently working on a project that used a library that outputs DLL classes using CGO,
The library has an initializer and registers a callback function.

The callback takes a pointer,

It might be:
1. char* string pointer
2. A custom struct pointer contains several fixed-length char arrays and a character pointer
```c
typedef struct {
char name[32];
char time[64];
char* data;
} CallbackEventData;

```

There is a free function in GO .
```go
//export Free
func Free(p unsafe.Pointer) {
C.free(p)
}

```

When receiving a callback, if it contains Chinese characters, it will be garbled.

I tried to create a custom CustomMarshaller and I was a bit confused
1. Creating a custom CustomMarshaller What methods should be provided, are they based on their names?

2. What's the difference between MarshalMode, such as marshalMode.elementin, and marshalMode.elementOut?

3. What's the difference between stateful and stateless?

4. When do you need to use a Caller-Allocated Buffer? What are the advantages?

In this [documents](https://github.com/dotnet/runtime/blob/main/docs/design/libraries/LibraryImportGenerator/UserTypeMarshallingV2.md)
I saw some instructions, but for the most part generics should not be needed.

**Comment by huoyaoyuan** [comment]
> if it contains Chinese characters, it will be garbled.

Can you share the original code you are using? What encoding are you using?

**Comment by AaronRobinsonMSFT** [comment]
@Gsonovb I recommend reading through the [type marshalling documentation](https://learn.microsoft.com/dotnet/standard/native-interop/type-marshalling).

> > if it contains Chinese characters, it will be garbled.

> Can you share the original code you are using? What encoding are you using?

+1. Without seeing the C# signatures of the functions and types it is hard to determine how marshalling is occuring.

**Comment by Gsonovb** [comment]
> > if it contains Chinese characters, it will be garbled.
> 
> Can you share the original code you are using? What encoding are you using?


Hi ,  @huoyaoyuan  @AaronRobinsonMSFT 
This is my demo code ,https://github.com/Gsonovb/goland-and-csharp-with-callback

Now the C# code is buggy and I'm trying to write different types CustomMarshaller to test their behavior.

**Comment by huoyaoyuan** [comment]
`UnmanagedType.ByValTStr` should mean ASNI code page-based encoding, e.g. GB2312 for Chinese system. There isn't a ByVal UTF8 option available.

**Comment by Gsonovb** [comment]
> `UnmanagedType.ByValTStr` should mean ASNI code page-based encoding, e.g. GB2312 for Chinese system. There isn't a ByVal UTF8 option available.

I'm currently testing CustomStringMarshaller, I haven't tested struct transfer yet. 'UnmanagedType.ByValTStr' should be system encoded, like GB2303. In GO, the default encoding is UTF8.

**Comment by Gsonovb** [comment]
what diff ICustomMarshaler vs  CustomMarshallerattribute ?

and  [MarshalUsing(typeof(CustomStringMarshaller))] vs //[MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(CustomStringMarshaller))]

The first one is not applied and the result is garbled code. The second will give you an error and a new request to implement ICustomMarshaler

**Comment by AaronRobinsonMSFT** [comment]
> what diff ICustomMarshaler vs CustomMarshallerattribute ?

The [`ICustomMarshaler`](https://learn.microsoft.com/dotnet/api/system.runtime.interopservices.icustommarshaler) is for the built-in interop system - see [here](https://learn.microsoft.com/dotnet/api/system.runtime.interopservices.icustommarshaler#applying-marshalasattribute) for how to use. The `MarshalUsingAttribute` doesn't support `ICustomMarshaler` and instead is part of the source generator solution - see [here](https://learn.microsoft.com/dotnet/standard/native-interop/custom-marshalling-source-generation) for usage.

The source generator uses the `LibraryImportAttribute` whereas the `DllImportAttribute` is for built-in interop and permits usage of the `ICustomMarshaler`.

**Comment by Gsonovb** [comment]
@AaronRobinsonMSFT 

```
// 回调函数1指针
[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
public delegate void CallBack1(
    [MarshalUsing(typeof(CustomStringMarshaller))]
    string data
    );

```
I tried to apply [MarshalUsing(typeof(CustomStringMarshaller))] to the arguments, but it didn't work
