### ISSUE TITLE
`Process.Start` will `System.ExecutionEngineException:“Exception_WasThrown”` in VS debug.

### ISSUE THREAD

**Issue by Coloryr** [dotnet/runtime#92046]
When use `Visual Studio`  start debug code, and use 
```
Process.Start("explorer");
```
was crash
![image](https://github.com/dotnet/runtime/assets/26276037/589a4a23-2822-41cc-b8fb-7843dba6c3de)

But if not use VS debug, that work.

![image](https://github.com/dotnet/runtime/assets/26276037/71f2cd66-b04b-40b7-a213-996c9604a489)
![image](https://github.com/dotnet/runtime/assets/26276037/4e93faeb-a5c9-4dc6-b1e0-19ceb6858447)

**Comment by jkotas** [comment]
Thank you for reporting this issue. This was fixed by https://github.com/dotnet/runtime/pull/90826. The fix is included in .NET 8 RC2.
