### ISSUE TITLE
System.Net.Dns.RunAsync() does not decrement telemetry for canceled requests

### ISSUE THREAD

**Issue by sandersaares** [dotnet/runtime#92045]
If a call that ends up in `Dns.RunAsync()` is canceled, nothing ever calls `NameResolutionTelemetry.AfterResolution()` and so the variable `NameResolutionTelemetry._currentLookups` remains forever incremented by one.

The unmatched `BeforeResolution()` is called in `Dns.RunAsync()` here: https://github.com/dotnet/runtime/blob/9101b853a1f5194de3e7bc495454a57df0da300e/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs#L652C16-L652C16

![image](https://github.com/dotnet/runtime/assets/9914262/b49b7e2e-46e4-49e5-82c2-f95b9c814c14)

**Comment by karelz** [comment]
Triage: Worth having, but not critical, moving to 9.0.
We should consider including it in servicing of #81023 if we come to that.
