### ISSUE TITLE
[Proposal]: Make MemoryStream use an unrolled linked list as the internal buffer

### ISSUE THREAD

**Issue by fandrei** [dotnet/runtime#92078]
[Unrolled linked list](https://en.wikipedia.org/wiki/Unrolled_linked_list)
Doing so would remove the cost of reallocation and copying of the buffer (sometimes it has to be done multiple times and costs a lot of time), as it would be enough to just allocate a new segment and keep the existing data intact, while having negligible negative effect on perfomance of the stream operations and memory consumption.
At the first sight, it looks like it can be done without changing the public API.

**Comment by fandrei** [comment]
PS also, it would make it possible to remove the size limit of 2GB

**Comment by startewho** [comment]
You can use the https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream,
it shoud support your need

**Comment by Kodealot** [comment]
@startewho I see, thanks.

**Comment by fandrei** [comment]
@startewho I see, thanks.
