### ISSUE TITLE
`url.scheme` tag is emitted as part of `http.client.request.duration` metric that does not match the OTel spec

### ISSUE THREAD

**Issue by vishweshbankwar** [dotnet/runtime#92077]
### Description

`url.scheme` is added by default on `http.client.request.duration` metric from `System.Net.Http`. However, it is not part of the required/recommended attributes from the spec. 

v1.21
https://github.com/open-telemetry/semantic-conventions/blob/v1.21.0/docs/http/http-metrics.md#metric-httpclientduration

Main
https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-metrics.md#metric-httpclientrequestduration

### Reproduction Steps

Test on .NET8.0 RC1 using OTel SDK

Configure SDK

```csharp
Sdk.CreateMeterProviderBuilder()
.AddMeter("System.Net.Http")
.Build()
```

### Expected behavior

`url.scheme` is not included by default.

### Actual behavior

`url.scheme` tag is added by default on `http.client.request.duration` metric

Sample output from sdk
> Export http.client.request.duration, The duration of outbound HTTP requests., Unit: s, Meter: System.Net.Http
(2023-09-14T18:44:41.6943865Z, 2023-09-14T18:44:48.7866188Z] http.request.method: GET http.response.status_code: 302 network.protocol.version: 1.1 server.address: www.bing.com **url.scheme**: http Histogram

https://github.com/dotnet/runtime/blob/f7a7b2b8b12dac91aa86a31e59ef6c1028d7113e/src/libraries/System.Net.Http/src/System/Net/Http/Metrics/MetricsHandler.cs#L192

**Comment by lmolkova** [comment]
Created https://github.com/open-telemetry/semantic-conventions/issues/356 ton otel and proposing https://github.com/open-telemetry/semantic-conventions/issues/357 to fix it on the otel side

**Comment by vishweshbankwar** [comment]
Closing this issue assuming the https://github.com/open-telemetry/semantic-conventions/issues/356 will be merged.
