### ISSUE TITLE
[API Proposal]: Update `System.Memory` nuget package with `Span<T>.Sort` extensions

### ISSUE THREAD

**Issue by timcassell** [dotnet/runtime#92081]
### Background and motivation

I was looking to use `Span<T>.Sort` in Unity, and found that it does not exist. I found that it's only supported in .Net 5+, but I also saw the `System.Memory` nuget package contains `MemoryExtensions` helpers. I thought it would contain `Sort` extensions, but it doesn't.

### API Proposal

```csharp
public static void Sort<T,TComparer> (this Span<T> span, TComparer comparer) where TComparer : System.Collections.Generic.IComparer<T>;

public static void Sort<T> (this Span<T> span);

public static void Sort<T> (this Span<T> span, Comparison<T> comparison);

public static void Sort<TKey,TValue,TComparer> (this Span<TKey> keys, Span<TValue> items, TComparer comparer) where TComparer : System.Collections.Generic.IComparer<TKey>;

public static void Sort<TKey,TValue> (this Span<TKey> keys, Span<TValue> items);

public static void Sort<TKey,TValue> (this Span<TKey> keys, Span<TValue> items, Comparison<TKey> comparison);
```

### API Usage

```csharp
span.Sort();
```

**Comment by teo-tsirpanis** [comment]
Unfortunately this is pretty unlikely to happen, the `System.Memory` package is not being actively developed. The latest version of its sources are [in a deleted branch of an archived repository](https://github.com/dotnet/corefx/tree/release/2.1/src/System.Memory).

**Comment by stephentoub** [comment]
Even if we wanted to resuscitate this package, we can't extend these types in the nuget package without breaking compatibility. They would need to be brand new methods on some new type. We have no plans to invest here. Thanks, though.
