### ISSUE TITLE
Additional read from memory when reading a field in a struct

### ISSUE THREAD

**Issue by Anthonywolfe** [dotnet/runtime#92093]
When reading from a field in a struct the JIT seems to read a byte from the base address before doing the read from the offset in memory. I've tried unsuccessfully to try and find any documentation describing what's going on here but I'm not exactly sure what I'm looking for and a quick dive into previous issues didn't turn up anything useful.

I'm assuming this is supposed to be a check/test to make sure the pointer is valid before being read from the offset, I've provided some code on sharplab that shows the issue I'm seeing.
[SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAJI8YUCAAcAymIBuvMDFwBuGjQYaGAbSkYoHMBgAy2AJ4QOGABQnzlgNK8uAExYBRBBIA2C3hgCUALrqmsQAzAy4egYYDABiAAoA4gCCbDAA5rxRYrghGgDe+ZoaWnG8MF7OAPIAZrW4MNZ0CCl0dChBTBEcTrEAKikAGkIA+gBCAKpSo1KD/dOq1CUlxSXhDL08DOnYzrrYGBy4Vv4MALwAfAyDIxPTs/OLa6ERwBAQXjfYCLwAIk0YIYLtcrLcxlMZnMUgspAwAGQMFoADnaaPaZwAhOckUsSgBfNS0CJkBgAYQYRWWmj6Yi42C+zCQDFgewgXC8pk2XFw2FqMHiyTSmWyGFyACpBakRGKoLVsIo8ZpirSoPSvtxefymChyQALIEAawBYsMMGcp2KVJWmlk2CgDBNQLFzguUpSMrE8sUcEu/R+/0BhiVGkJ1HxQA=)

```
FPGARegisters.ReadStatus()
    L0000: cmp [rcx], cl
    L0002: mov eax, [rcx+0xa004]
    L0008: ret

FPGARegisters.get_TaxiDetect()
    L0000: cmp [rcx], cl ; Can see here what I assume is a test of the pointer before doing a read from the offset
    L0002: xor eax, eax
    L0004: test dword ptr [rcx+0xa004], 0x80000000
    L000e: setne al
    L0011: ret
```

```
; Total bytes of code 496

; Assembly listing for method ServerApp.FPGARegisters:get_TaxiDetect():bool:this
; Emitting BLENDED_CODE for generic ARM64 CPU - Unix
; debuggable code
; fp based frame
; fully interruptible
; No PGO data

G_M000_IG01:                ;; offset=0000H
        A9BE7BFD          stp     fp, lr, [sp,#-0x20]!
        910003FD          mov     fp, sp
        F9000FA0          str     x0, [fp,#0x18]
 
G_M000_IG02:                ;; offset=000CH
        D2937F00          movz    x0, #0x9BF8
        F2AADB40          movk    x0, #0x56DA LSL #16
        F2DFFFE0          movk    x0, #0xFFFF LSL #32
        B9400000          ldr     w0, [x0]
        34000040          cbz     w0, G_M000_IG04
 
G_M000_IG03:                ;; offset=0020H
        978582F8          bl      CORINFO_HELP_DBG_IS_JUST_MY_CODE
 
G_M000_IG04:                ;; offset=0024H
        F9400FA0          ldr     x0, [fp,#0x18]
        39C0001F          ldrsb   wzr, [x0] ;;Same here, doing a byte read before doing the actual read
        F9400FA0          ldr     x0, [fp,#0x18]
        D2940081          mov     x1, #0xA004
        B8616800          ldr     w0, [x0, x1]
        12010000          and     w0, w0, #0x80000000
        7100001F          cmp     w0, #0
        9A9F07E0          cset    x0, ne
 
G_M000_IG05:                ;; offset=0044H
        A8C27BFD          ldp     fp, lr, [sp],#0x20
        D65F03C0          ret     lr
```

To add some additional context to the issue I am using a .Net 7 application on a Xilinx Ultrascale+ chip which has 4 ARM64 cores and a FPGA, the Arm cores running a custom ARM64 linux kernel. 
My application is controlling the FPGA by reading and writing registers from a [AXI-Lite](https://www.xilinx.com/products/intellectual-property/axi_lite_ipif.html) interface that is mmaped from a [UIO](https://www.kernel.org/doc/html/latest/driver-api/uio-howto.html) device.

![image](https://github.com/dotnet/runtime/assets/1762872/4f409713-1429-4d8d-a84c-71c94e256fc9)
This image shows the AXI transaction that's caused by this read on the FPGA side.

So to get to the core of my issue, I don't have total control over what reading from offset 0 of the struct does. Depending on the hardware IP I have the struct wrapped around it could just be the first byte of a version number or it could try and pop an element out of a hardware FIFO.

I'm also not sure if this is a regression as this isn't something we have noticed before when debugging AXI communications on. But I can try installing some older versions of .NET / .Net Core to check

**Comment by jkotas** [comment]
Yes, the read from the offset is null-check. Note that this explicit null check is only done for reading for offsets larger than a page. You won't see it for small offset.

I has always been like that.

**Comment by MichalPetryka** [comment]
> that is mmaped from a [UIO](https://www.kernel.org/doc/html/latest/driver-api/uio-howto.html) device.

Keep in mind that dotnet does not support working with device memory on ARM64.

**Comment by EgorBo** [comment]
You can use explicit nullchecks to give JIT hints it doesn't need the implicit ones, e.g.:
```cs
var iface = FPGAInterface;
if (iface == null)
    throw new NullReferenceException();
var Detected = iface->TaxiDetect;
```

but it's fragile.

**Comment by Anthonywolfe** [comment]
> Yes, the read from the offset is null check. Note that this explicit null check is only done for reading for offsets larger than a page. You won't see it for small offset.
> 
> It has always been like that.

Ah this might be the reason I've only ran into it just now as our previous structs have been smaller than a page.
Is there a way I can get around this null check by explicitly providing hints or do I have to break my struct into along the page boundaries and use multiple views of the memory mapped region?


> > that is mmaped from a [UIO](https://www.kernel.org/doc/html/latest/driver-api/uio-howto.html) device.
> 
> Keep in mind that dotnet does not support working with device memory on ARM64.

In what way? The UIO device maps a chunk of native memory that's mapped in the hardware and device tree to a file in /dev that I can then open as a file and then use mmap to get a virtual address I can manipulate in my program. 


> You can use explicit nullchecks to give JIT hints it doesn't need the implicit ones, e.g.:
> 
> ```cs
> var iface = FPGAInterface;
> if (iface == null)
>     throw new NullReferenceException();
> var Detected = iface->TaxiDetect;
> ```
> 
> but it's fragile.

I can't do a null check on a struct and explicit null checking of the pointer didn't help avoid the null check on page boundaries.

**Comment by MichalPetryka** [comment]
> In what way? The UIO device maps a chunk of native memory that's mapped in the hardware and device tree to a file in /dev that I can then open as a file and then use mmap to get a virtual address I can manipulate in my program.

https://github.com/dotnet/runtime/blob/main/docs/design/specs/Memory-model.md#unmanaged-memory-access

**Comment by Anthonywolfe** [comment]
> > In what way? The UIO device maps a chunk of native memory that's mapped in the hardware and device tree to a file in /dev that I can then open as a file and then use mmap to get a virtual address I can manipulate in my program.
> 
> https://github.com/dotnet/runtime/blob/main/docs/design/specs/Memory-model.md#unmanaged-memory-access and [#66082 (comment)](https://github.com/dotnet/runtime/issues/66082#issuecomment-1067065478) for the explaination.

I see that makes sense to me.
> As of this writing there is no specific support for operating with incoherent memory, device memory or similar. Passing non-ordinary memory to the runtime by the means of pointer operations or native interop results in Undefined Behavior.

I assume the limitation would still apply to access via https://learn.microsoft.com/en-us/dotnet/api/system.io.memorymappedfiles.memorymappedfile?view=net-7.0 as it's still operating on device memory that it loaded through wrappers around native interop.
