### ISSUE TITLE
.Net 8 RC1 WASM - compatibility - lack of support for older systems

### ISSUE THREAD

**Issue by KubaGluszkiewicz** [dotnet/runtime#92117]
### Description

After changing from DotNet 7 to DotNet 8 RC1 for webassembly browser project (not blazor), we are unable to run our application on Tizen (Samsung) and WebOS (LG) devices. 
Those devices are serving host environment based on Chromium. usually those are older versions like 85,
WebAssembly portability is crucial feature for us, as we can ship our application to the users on wide range of systems.

After migrating to DotNet 8 RC1 we are not able to instantinate dotnet runtime at all,
we are getting bunch of errors just at the begining of creating dotnet runtime like this:
```
logging.ts:32 MONO_WASM: TypeError: Cannot read property 'mono_wasm_abort' of undefined
    at Object.Module._mono_wasm_abort [as mono_wasm_abort] (http://127.0.0.1:9000/_framework/dotnet.native.js:8:127389)
    at Object.Ll.l.abort (http://127.0.0.1:9000/_framework/dotnet.runtime.js:3:214656)
    at w (http://127.0.0.1:9000/_framework/dotnet.runtime.js:3:1229)
    at http://127.0.0.1:9000/_framework/dotnet.runtime.js:3:201358
    at async http://127.0.0.1:9000/_framework/dotnet.runtime.js:3:201217
```

do you have plans to maintain high compatibility for wasm projects in DotNet 8 or it's designed to work only with newest modern browsers?

Also i'm affraid that SIMD support in WASM will be also problem, hopefully we will be able to rebuild using wasm-tools to disable any SIMD operations as older browser doesn't support them.

### Configuration

Tizen SSSP6.5
Chrome 85

### Reproduction Steps

using DotNet RC1
create BrowserWasmProject
build default configuration
you should see correct output in modern browsers

try to run project on Chrome 85, it will throw errors as in above description

### Expected behavior

WasmBrowser should cover wide range of browser including legacy ones, to be able to deploy application into wide range of older mobile devices or modern TV systems where OS backbone is older Chrommium version

### Actual behavior

Unable to run WASM Browser project on older browsers

**Comment by maraf** [comment]
```
Uncaught (in promise) TypeError: Module.asm is undefined
    _mono_wasm_abort dotnet.native.js:8
    abort startup.ts:356
    w globals.ts:94
    preInit startup.ts:379
    preInit startup.ts:170
    preInit startup.ts:167
    preInit startup.ts:78
    createDotnetRuntime dotnet.native.js:8
    ze run.ts:463
    Ne run.ts:505
    Ne run.ts:428
    create run.ts:362
    run main.js:11
    <anonymous> main.js:30
```

Tested with Firefox 89, .NET 8.0.100-rc.1.23455.8

**Comment by KubaGluszkiewicz** [comment]
@maraf yes, it helped, i didn't check on Tizen yet but i checked in Chrome 85 where previously application didn't start. Thank you so much for your help, actually i feel embarassed i could figure out this setting by my own, considering i know there is no SIMD support on legacy browsers.

**Comment by maraf** [comment]
No problem. We had some problems with disabling SIMD in previews and it's actually good that we revisited it once more.

**Comment by LostBeard** [comment]
Just tested a simple Blazor WASM .Net RC 2 app on Firefox Android 181.2.0 and Firefox Android Nightly 120.0a1 and it failed with an error about SIMD not being supported. WASM exceptions are according to a quick run of [wasm-feature-detect](https://github.com/GoogleChromeLabs/wasm-feature-detect). 

It is working in Chrome Android on the same device so this is obviously a missing feature on Firefox Android. 

Is there a recommended way to handle this to keep compatibility but also take advantage of SIMD when available?

My current plan is to use a custom Blazor.Start() Javascript method to detect SIMD support (and maybe some others) and then modify the resource paths to load the compatible _framework. I did a diff of a build with SIMD and 1 without and only 3 files changed. dotnet.native.wasm, dotnet.native.8.0.0-rc.2.23479.6.4zb5gic473.js, and blazor.boot.json. 

The latest Firefox Android isn't exactly an older system.

**Comment by LostBeard** [comment]
And I just tested the same Blazor WASM app on an Android tablet with Firefox 118.2.0 and it works with SIMD. Not sure what is causing the difference.

**Comment by maraf** [comment]
> My current plan is to use a custom Blazor.Start() Javascript method to detect SIMD support (and maybe some others) and then modify the resource paths to load the compatible _framework.

This is the best approach I can recommend at the moment. We might have some built-in support in .NET 9

**Comment by LostBeard** [comment]
@maraf Thank you. 

I have written up a small guide on how to detect SIMD support and how to build a compatibility build to use if needed, in the Discussion section of my primary Blazor WASM project repo. 

[SIMD Compatibility](https://github.com/LostBeard/SpawnDev.BlazorJS/discussions/19)

Interesting note. I have noticed that my devices or browsers that do not support SIMD also throw an error ```MONO_WASM: Disabling jiterpreter after 2 failures``` if ```BlazorWebAssemblyJiterpreter``` is not also disabled. Disabling both SIMD and the jiterpreter when SIMD is not supported works without any further issues on my test devices.

I love Blazor (obvious looking at my repos.) Keep up the great work. 👍

**Comment by LostBeard** [comment]
I created a basic demo repo [BlazorWASMSIMDDetectExample](https://github.com/LostBeard/BlazorWASMSIMDDetectExample) and added an example of how to also handle service working caching.

**Comment by maraf** [comment]
> Interesting note. I have noticed that my devices or browsers that do not support SIMD also throw an error MONO_WASM: Disabling jiterpreter after 2 failures if BlazorWebAssemblyJiterpreter is not also disabled. (The app still runs with the error.) Disabling both SIMD and the jiterpreter when SIMD is not supported works without any further issues on my test devices.

cc @kg
