### ISSUE TITLE
RandomNumberGenerator bad performance on GetString and possible reason

### ISSUE THREAD

**Issue by Ponant** [dotnet/runtime#92130]
### Description

I was using .Net 7 and did not have available a way to generate a random string based on the Base64 url encoded characters and SO answers were showing low perf code. So I made one during this summer until I noticed yesterday that .Net 8 has a new `GetString` so I jumped into it . The one I have is faster up to 10 times for a 32 long string. Culprit and code below.

### Configuration
.Net 8 RC1, Windows 11 Pro 64 V 22H2, Thinkpad X1 Yoga

### Data for length = 11 (YouTube ids)

| Method     | Mean       | Error    | StdDev   | Median     | Gen0   | Allocated |
|----------- |-----------:|---------:|---------:|-----------:|-------:|----------:|
| GetString2 |   158.7 ns |  3.22 ns |  7.64 ns |   160.7 ns | 0.0114 |      48 B |
| GetString  | 1,002.2 ns | 20.08 ns | 46.93 ns | 1,027.0 ns | 0.0114 |      48 B |

### Analysis

Problem is calling `GetInt32` in the loop

```
       private static void GetItemsCore<T>(ReadOnlySpan<T> choices, Span<T> destination)
        {
            for (int i = 0; i < destination.Length; i++)
            {
                destination[i] = choices[GetInt32(choices.Length)];
            }
        }
```

### Limits
Limits of my approach. I must have a  `choices` string for which the length is a power of 2 <256. That is the case for `Length64String` and it is enough for my purposes and I believe for most web developpers.
I did not dig into your code to see if you have the same limitation, i.e. whether you need to abide to in order to ensure a uniform distribution.

### Solution

If you have that same limitation (I do not expect, a priori), then the API must be corrected to ensure uniformity.
If you do not have this limitation, I still believe it is worth having specialized methods to generate strings that are a power of 2 while < 256 or review the `GetItemsCore` to improve perfomance.

### Code Program.cs

```
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using System.Security.Cryptography;

BenchmarkRunner.Run<RandomBase64StringGenerator>();

[MemoryDiagnoser]
public class RandomBase64StringGenerator
{
    const int length = 11; 

    [Benchmark]
    public void GetString2()
    {
       RandomGenerator.New64(length);
    }

    [Benchmark]
    public void GetString()
    {
        RandomNumberGenerator.GetString(RandomGenerator.Constants.Length64String,length);
    }
}

public sealed class RandomGenerator
{
    public class Constants
    {
        public const string Length64String = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-";
    }

    const int _stackAllocThreshold = 32;

    public static string New64(int length = 11)
    {
        return GetRandomString(length, Constants.Length64String);
    }

    private static string GetRandomString(int length, ReadOnlySpan<char> characters)
    {
        // No plan to go beyond _stackAllocThreshold, so we throw
        if (length <= 0 || length > _stackAllocThreshold)
            throw new ArgumentException($"{nameof(length)} must be at least one" +
                $" and lower or equal to {_stackAllocThreshold}");

        Span<byte> bytes = stackalloc byte[length];
        Span<char> chars = stackalloc char[length];

        RandomNumberGenerator.Fill(bytes);

        int mask = 256 / characters.Length;

        for (var i = 0; i < bytes.Length; i++)
            chars[i] = characters[bytes[i] / mask];

        return new string(chars);
    }
}
```

**Comment by bartonjs** [comment]
There's probably already a significant timing differential between an alphabet of 32 and 33 characters, since 33 would involve a lot of rejected sampling in GetInt32(alphabet.Length); so it's probably reasonable to special case a power of two alphabet in GetItemsCore.

> If you have that same limitation (I do not expect, a priori), then the API must be corrected to ensure uniformity.

I don't agree that it _must_ be corrected, but it does seem reasonable.  But, no, our GetString (and GetItems in general) is explicitly designed to make pulling from a non-power-of-two "alphabet" safe.  Making the power-of-two special case faster is just goodness.

And by the by, I'd expect this variant to be even faster, still uniform, and doesn't have a limit of how much stack it's willing to use (since it uses the pending string buffer as a place to hold the random data)

```C#

        public static unsafe string GetStringPow2(ReadOnlySpan<char> choices, int length)
        {
            if (choices.IsEmpty)
            {
                throw new ArgumentException("Choices cannot be empty", nameof(choices));
            }

            int choicesLength = choices.Length;

            if ((choicesLength & (choicesLength - 1)) != 0)
            {
                throw new ArgumentException("Choices must be a power of two", nameof(choices));
            }

            if (length < 0)
            {
                throw new ArgumentOutOfRangeException(nameof(length), "Value cannot be negative");
            }

#pragma warning disable 8500
            return string.Create(length,
                (IntPtr)(&choices),
                static (destination, state) =>
                {
                    ReadOnlySpan<char> choices = *(ReadOnlySpan<char>*)state;
                    Span<byte> rand = MemoryMarshal.AsBytes(destination).Slice(0, destination.Length);
                    RandomNumberGenerator.Fill(rand);
                    int mask = choices.Length - 1;

                    for (int i = destination.Length - 1; i >= 0; i--)
                    {
                        destination[i] = choices[rand[i] & mask];
                    }
                });
#pragma warning restore 8500
        }
```

**Comment by RenderMichael** [comment]
Maybe this could be even faster if `string.Create`'s callback was left intentionally empty. The initial destination contains garbage, and if garbage was left there then the method would be even faster

**Comment by Suchiman** [comment]
> Maybe this could be even faster if `string.Create`'s callback was left intentionally empty. The initial destination contains garbage, and if garbage was left there then the data would remain random.

AFAIK, [FastAllocateString](https://source.dot.net/System.Private.CoreLib/R/78a459e3adf6b1d6.html) does not use the [GC_ALLOC_FLAGS](https://source.dot.net/System.Private.CoreLib/src/System/GC.CoreCLR.cs.html#73187579b139a5f7).[GC_ALLOC_ZEROING_OPTIONAL](https://source.dot.net/System.Private.CoreLib/src/System/GC.CoreCLR.cs.html#1412e910e8571a47) flag meaning that strings will be allocated from zero'd memory, and even if zeroing is optional, that doesn't mean that you're guaranteed to get non zero'd memory. Even if it were though, it could be pointing to a prior string instance and potentially leak sensitive data that was thought to be deleted.

**Comment by sylveon** [comment]
Relying on uninitialized for randomness is not good practice in general

**Comment by GrabYourPitchforks** [comment]
> > Maybe this could be even faster if `string.Create`'s callback was left intentionally empty. The initial destination contains garbage, and if garbage was left there then the data would remain random.
> 
> AFAIK, [FastAllocateString](https://source.dot.net/System.Private.CoreLib/R/78a459e3adf6b1d6.html) does not use the [GC_ALLOC_FLAGS](https://source.dot.net/System.Private.CoreLib/src/System/GC.CoreCLR.cs.html#73187579b139a5f7).[GC_ALLOC_ZEROING_OPTIONAL](https://source.dot.net/System.Private.CoreLib/src/System/GC.CoreCLR.cs.html#1412e910e8571a47) flag meaning that strings will be allocated from zero'd memory, and even if zeroing is optional, that doesn't mean that you're guaranteed to get non zero'd memory. Even if it were though, it could be pointing to a prior string instance and potentially leak sensitive data that was thought to be deleted.

Back in 2021 I ran an experiment where certain string APIs attempted to skip the zero-init process. Results were mixed. The conclusion was that since most strings are very short (maybe a few dozen chars max?), they're better suited being served directly from the prezeroed gen-0 heap, and passing the flag isn't buying you much. We only reliably saw perf improvements when dealing with large strings (100k+ chars) or workloads which consumed large strings, like ML or compiler workloads. Even were we to pursue this, it wouldn't have done much for the scenario discussed here.

**Comment by Ponant** [comment]
The main reason for the performance benefit comes from the use of the buitwise AND `&` rather than integer division. `string.Create` or the unsafe setting did not improve performance, not on my machine at least.
