### ISSUE TITLE
[API Proposal]: Add static factory methods for collections in System.Collections.Generic

### ISSUE THREAD

**Issue by jcracknell** [dotnet/runtime#92133]
### Background and motivation

Please consider adding static factory methods matching those provided in the System.Collections.Immutable namespace to the concrete collection implementations in System.Collections.Generic. These permit non-postfix materialization of a collection with type inferral.

Instead of writing:

```csharp
var list = (
  from a in as
  where a.IsHappy
  select a.B
)
.ToList();
```

I tend to prefer:

```csharp
var list = Enumerable.ToList(
  from a in as
  where a.IsHappy
  select a.B
);
```

which is more aesthetically pleasing, eliminates anguish around mixing of styles and indentation, and puts information about the result type of the LINQ transformation closer to the definition of the variable. Unfortunately it also feels like an abuse of the extension method.

There are a few collections where the static class would potentially conflict with legacy non-generic versions defined in System.Collections (Stack, SortedList, and Queue), however this should be perfectly feasible for most of the commonly used collections.

### API Proposal

```csharp
namespace System.Collections.Generic;

public static class List
{
  public static List<A> Create<A>(A item) =>
    new List<A>(1) { item };

  public static List<A> Create<A>(params A[] items) =>
    CreateRange(items);

  public static List<A> CreateRange<A>(IEnumerable<A> items) =>
    new List<A>(items);
}

public static class Dictionary
{
  public static Dictionary<K, V> Create<K, V>(KeyValuePair<K, V> item) where K : notnull =>
    Create(EqualityComparer<K>.Default, item);
    
  public static Dictionary<K, V> Create<K, V>(IEqualityComparer<K> keyComparer, KeyValuePair<K, V> item) where K : notnull =>
    new Dictionary<K, V>(1, keyComparer) { [item.Key] = item.Value };

  public static Dictionary<K, V> Create<K, V>(params KeyValuePair<K, V>[] items) where K : notnull =>
    CreateRange(EqualityComparer<K>.Default, items);
    
  public static Dictionary<K, V> Create<K, V>(IEqualityComparer<K> keyComparer, params KeyValuePair<K, V>[] items) where K : notnull =>
    CreateRange(keyComparer, items);
    
  public static Dictionary<K, V> CreateRange<K, V>(IEnumerable<KeyValuePair<K, V>> items) where K : notnull =>
    CreateRange(EqualityComparer<K>.Default, items);
  
  public static Dictionary<K, V> CreateRange<K, V>(IEqualityComparer<K> keyComparer, IEnumerable<KeyValuePair<K, V>> items) where K : notnull =>
    new Dictionary<K, V>(items, keyComparer);
}
```

### API Usage

```csharp
var list = List.CreateRange(
  from a in as
  where a.IsHappy
  select a.B
);
```

**Comment by huoyaoyuan** [comment]
With the upcoming [collection expression](https://github.com/dotnet/csharplang/issues/5354
) language feature, you will be able to directly write `List<int> l = [..(from xxx)];`.

Generally, we don't add such simple wrapper methods unless they serve for language feature.

**Comment by jcracknell** [comment]
I feel this is justifiable purely from a consistency standpoint. In addition passing a collection expression as a Func is noisy and repetitive.

**Comment by eiriktsarpalis** [comment]
> which is more aesthetically pleasing, eliminates anguish around mixing of styles and indentation, and puts information about the result type of the LINQ transformation closer to the definition of the variable. 

I don't think we'd want to consider API proposals purely out of style considerations, which can often be subjective.

>  the problem with collection expressions is that they do not deal with type inferral

Collection literals work using target typing which is as close to the definition of the variable as you can get.

I'd be inclined to close this, however the introduction of `CollectionBuilderAttribute` means that most collections types will need to ship at least some factory methods goind forward. Maybe we could consider expand these factories to accept IEnumerable parameters or equality comparers where applicable. @stephentoub @CyrusNajmabadi thoughts?

**Comment by stephentoub** [comment]
>  however the introduction of CollectionBuilderAttribute means that most collections types will need to ship at least some factory methods goind forward

Not really; collection expressions inherit collection initializers support, so any collection that implements `IEnumerable<T>` and has an Add method is already covered. `[CollectionBuilder(...)]`, at least with the pattern it supports today, ends up handling more niche cases:
- Immutable collections that don't support adding to the target instance
- Cases where a collection could be constructed meaningfully more efficiently if the compiler-generated code expended the effort to build up a `ReadOnlySpan<T>` that could then be passed off to the collection in a way that the collection could more efficiently construct itself.
