### ISSUE TITLE
[PERF] Regression in Math.Single and Char_IsLower Benchmarks on Ubuntu Arm64

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#92162]
These were found during the manual perf comparison for 8.0 RC1.

* https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_ubuntu%2020.04/System.MathBenchmarks.Single.Exp10.html
* https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_ubuntu%2020.04/System.MathBenchmarks.Single.Exp2.html
* https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_ubuntu%2020.04/System.MathBenchmarks.Single.Exp10M1.html
* https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_ubuntu%2020.04/System.MathBenchmarks.Single.Exp2M1.html
* https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_ubuntu%2020.04/System.MathBenchmarks.Single.ExpM1.html
* https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_ubuntu%2020.04/System.MathBenchmarks.Single.Exp.html

This is the range of commits https://github.com/dotnet/runtime/compare/ddfaf2750e8dcf127a8baf0a3e5a2bd4835f79c7...ec06321141611cc131c18761808abce15d097db3. I suspect this is either https://github.com/dotnet/runtime/pull/80789, or https://github.com/dotnet/runtime/pull/80353

For the IsLower this is the only regressed scenario. https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_ubuntu%2020.04/System.Tests.Perf_Char.Char_IsLower(input:%20%22Good%20afternoon,%20Constable!%22).html

The range is https://github.com/dotnet/runtime/compare/35af395b40002a245a744d2f1db1f1cd06e1bafe...bfef7ccc856ac307fd5102c00ea54ddbe0b06fa3 and nothing jumps out at me.

**Comment by tannergooding** [comment]
These all defer into the C runtime, so any perf difference is going to end up being not relevant to the APIs themselves.

**Comment by MichalPetryka** [comment]
> These all defer into the C runtime, so any perf difference is going to end up being not relevant to the APIs themselves.

I don't think Char_IsLower does.

**Comment by tannergooding** [comment]
I missed `char.IsLower`. It's implementation has likewise not changed and this is more than likely caused by some other factor, such as the loop unrolling changing how BDN measures things.
