### ISSUE TITLE
`GetFromJsonAsAsyncEnumerable` extension default json serialize option is not the same as `GetFromJson`

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/runtime#92179]
### Description

`GetFromJsonAsAsyncEnumerable` extension default json serialize option is not the same as `GetFromJson`, for `GetFromJsonAsync<TValue>` etc extensions using the `new JsonSerializerOptions(JsonSerializerDefaults.Web)`, while the new `GetFromJsonAsAsyncEnumerable` extensions using the `JsonSerializerOptions.Default`

https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http.Json/src/System/Net/Http/Json/HttpClientJsonExtensions.cs#L19

https://github.com/dotnet/runtime/blob/fa1bf3c0f9ec4e204203a49191170f9d53cd549a/src/libraries/System.Net.Http.Json/src/System/Net/Http/Json/JsonHelpers.cs#L15C10-L15C10

https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http.Json/src/System/Net/Http/Json/HttpClientJsonExtensions.Get.AsyncEnumerable.cs#L138

https://github.com/dotnet/runtime/pull/89258/files#diff-096816e722c9256aa978e030242edf422dd8e41be616ab27bd7175cd522789e2R138

### Reproduction Steps

```c#

using var httpClient = new HttpClient();
httpClient.BaseAddress = new Uri("http://localhost:5297");
// we assume the response returned like
// [{"id":1,"title":"job_0 --- 09/16/2023 21:32:26 +08:00"},{"id":2,"title":"job_1 --- 09/16/2023 21:32:27 +08:00"}]
var stream = httpClient.GetFromJsonAsAsyncEnumerable<Job>("api/Jobs");
await foreach (var job in stream)
{
    Console.WriteLine(job);
    Console.WriteLine(DateTimeOffset.Now);
}

public sealed class Job
{
    public required int Id { get; set; }
    public required string Title { get; set; }
    public override string ToString() => $"JobId: {Id}, JobTitle: {Title}";
}
```

### Expected behavior

Think it should behave like `GetFromJsonAsync` to use the `JsonSerializerDefault.Web`

### Actual behavior

![image](https://github.com/dotnet/runtime/assets/7604648/40de0999-94af-4a18-bbcb-c6763d2f415e)

### Known Workarounds

The `HttpContent` extension `ReadFromJsonAsAsyncEnumerable` is working

```c#
using var httpClient = new HttpClient();
httpClient.BaseAddress = new Uri("http://localhost:5297");
using var response = await httpClient.GetAsync("api/Jobs", HttpCompletionOption.ResponseHeadersRead);
ArgumentNullException.ThrowIfNull(response.Content);
var stream = response.Content.ReadFromJsonAsAsyncEnumerable<Job>();
await foreach (var job in stream)
{
    Console.WriteLine(job);
    Console.WriteLine(DateTimeOffset.Now);
}
```

### Configuration

.NET 8 RC 1

**Comment by eiriktsarpalis** [comment]
Thanks, we should fix this in .NET 8
