### ISSUE TITLE
[API Proposal]: add `JsonSerializerOptions.Web` for `JsonSerializerOptions`

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/runtime#92181]
### Background and motivation

Propose a public `JsonSerializerOptions` for the web, it could help avoid some duplicate cache

For example, if we extend the `AsyncEnumerable` for legacy frameworks, we could use the shared `JsonSerializerOptions.Web` without creating a new `JsonSerializerOptions`, and the original cache in runtime/aspnetcore etc would also benifit from this

`new JsonSerializerOptions(JsonSerializerDefaults.Web)` usage from grep:

https://grep.app/search?q=JsonSerializerOptions%28JsonSerializerDefaults.Web%29&filter[lang][0]=C%23

This may also help with the new analyzer rule

https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1869

### API Proposal

```diff
namespace System.Text.Json;

public sealed partial class JsonSerializerOptions
{
    public static JsonSerializerOptions Default { get; }
+   public static JsonSerializerOptions Web { get; }
}
```

### API Usage

```csharp
using var httpClient = new HttpClient();
httpClient.BaseAddress = new Uri("http://localhost:5297");
await using var responseStream = await httpClient.GetStreamAsync("api/Jobs");
// var stream = JsonSerializer.DeserializeAsyncEnumerable<Job>(responseStream, new JsonSerializerOptions(JsonSerializerDefaults.Web));
var stream = JsonSerializer.DeserializeAsyncEnumerable<Job>(responseStream, JsonSerializerOptions.Web);
```

**Comment by krwq** [comment]
Can you explain the specific settings you're suggesting to be changed?

**Comment by WeihanLi** [comment]
Maybe just use the `new JsonSerializerOptions(JsonSerializerDefaults.Web)` to align with the `JsonSerializerDefaults.Web`

https://github.com/dotnet/runtime/blob/f276c514fe5fe4d9120420286ab7c6299f874992/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs#L142-L147

**Comment by bartonjs** [comment]
* We discussed several naming options (`Web`, `WebDefaults`, `DefaultWeb`, and `DefaultsForWeb`) and stuck with `Web` as straight parity from the enum.

```diff
namespace System.Text.Json;

public sealed partial class JsonSerializerOptions
{
    public static JsonSerializerOptions Default { get; }
+   public static JsonSerializerOptions Web { get; }
}
```

**Comment by eiriktsarpalis** [comment]
Update the milestone to reflect the PR that's in progress.
