### ISSUE TITLE
[browser] Support structs with JavaScript interop

### ISSUE THREAD

**Issue by Elringus** [dotnet/runtime#92198]
New JS interop works great, but is quite limiting in that it doesn't allow packing supported types into structs or records.

As a workaround, I'm serializing structs to JSON before sending them to JS, then parse the JSON in JS. And for result, it's again serialized to JSON on JS side and parsed back in C#, which is terribly inefficient. 

Is it possible to support structs natively, similar to native interop? (https://learn.microsoft.com/en-us/dotnet/standard/native-interop/custom-marshalling-source-generation)

**Comment by Elringus** [comment]
@pavelsavara sorry for the ping, but the issue probably got lost due to wrong area assigned initially.

**Comment by pavelsavara** [comment]
We would have to implement some kind of serialization/deserialization too. 
And most likely it would not have better performance than native `JSON.serialize` or the `System.Text.Json` (with codegen). 
Also `System.Text.Json` has benefit of well known behavior and configuration we don't have to re-invent.

To make it better dev experience I think https://github.com/dotnet/runtime/issues/77784 is better.

**Comment by pavelsavara** [comment]
> for instance, it can't marshal a `float[]` even as a `Float32Array` despite both being natural types in C# and JS respectively. you have to first convert it to a `double[]` on the C# side, and then copy the contents of the `Float64Array` to a `Float32Array` on the JS side. 

That could be separate issue.

> similarly, it marshals `byte[]` arrays to `Uint8Array`, which is fine unless you need it to be a `Uint8ClampedArray` 

Again, please open separate issue. 

Both will need new `JSType.Json` member and API review.

**Comment by Elringus** [comment]
> We would have to implement some kind of serialization/deserialization too.
Is that because JS can run on different runtimes (V8, WebKit, node, etc) and each has different object layout in memory? Could it be possible to detect the runtime and marshal the struct accordingly?

**Comment by pavelsavara** [comment]
> Is that because JS can run on different runtimes (V8, WebKit, node, etc) and each has different object layout in memory? Could it be possible to detect the runtime and marshal the struct accordingly?

We don't have access to JS engine internals in the browser. We could have it in NodeJS I guess, but it's not good idea.

**Comment by Elringus** [comment]
I see, thanks for the explanation. Looks like it's the same issue in other languages (eg, in Rust they also serialize arbitrary structs to JSON).
