### ISSUE TITLE
Json source generator regression

### ISSUE THREAD

**Issue by MaherJendoubi** [dotnet/runtime#92214]
### Description

The source generator doesn't generate the code when we use [JsonSerializable(typeof(Class))]

### Reproduction Steps

https://devblogs.microsoft.com/dotnet/announcing-dotnet-8-rc1/#jsoncontent-create-overloads-accepting-jsontypeinfo

### Expected behavior

The expected behavior is to generate the MyContext.Book.g.cs file.

### Actual behavior

<img width="921" alt="Capture d’écran 2023-09-18 à 12 39 17" src="https://github.com/dotnet/runtime/assets/1798510/e9def2a1-d478-4cf8-a470-baa5df18e472">

### Regression?

Yes

### Known Workarounds

I am not sure that there is a known workaround but the only solution I find for the moment is to implement members.

```csharp
public partial class MyContext : JsonSerializerContext
{
    public MyContext(JsonSerializerOptions? options) : base(options)
    {
    }

    public override JsonTypeInfo? GetTypeInfo(Type type)
    {
        throw new NotImplementedException();
    }

    protected override JsonSerializerOptions? GeneratedSerializerOptions { get; }
}
```
### Configuration

dotnet --version = 8.0.100-rc.1.23455.8

macOS: Ventura 13.5.2
Architecture: ARM64

**Comment by eiriktsarpalis** [comment]
I can reproduce on my own mac using .NET 8 RC1. The issue appears to be with Rider, the snippet works as expected in VS Code or when building from the command line. I would recommend filing an issue with them: https://www.jetbrains.com/help/rider/Getting_Help.html

cc @auduchinok
