### ISSUE TITLE
Remaining .NET 8 work for TensorPrimitives

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#92219]
### RC2
- [x] Add naive implementations of `Add`, `AddMultiply`, `Cosh`, `Divide`, `Exp`, `Log`, `Multiply`, `MultiplyAdd`, `Negate`, `Subtract`, `Sinh`, `Tanh` - @tannergooding
- [x] Add naive implementations of `CosineSimilarity`, `Distance`, `Dot`, `Norm`, `Sigmoid`, `SoftMax` - @michaelgsharp  
- [x] Add naive implementations of `Max/Min{Magnitude}`, `IndexOfMax/Min{Magnitude}`, `ConvertToHalf/Single`, `Log2` - @stephentoub 
- [x] Add vectorized implementations of `Abs`, `Sum`, `SumOfSquares`, `SumOfMagnitudes`, `Product`, `ProductOfSums`, `ProductOfDifferences` - @stephentoub
- [x] Vectorize `Add`, `Subtract`, `Multiply`, `Divide`, `Negate`, `AddMultiply`, `MultiplyAdd` - @stephentoub
- [x] Backport merged functionality to release/8.0-rc2 - @michaelgsharp 
- [x] Rename `L2Normalize` to `Norm`? - @stephentoub

### GA
- [x] Consider source rename of `netcore.cs` and `netstandard.cs` since they don't only apply to those target framework identifiers? per @stephentoub it maps to our existing naming conventions
- [x] Ensure packages set up to ship XML docs correctly.
- [x] Review/update XML comments for API docs - @stephentoub
- [x] Update the API proposal issue to reflect the new APIs we added since that issue was approved - @stephentoub
- [x] Add content to the RC2 release notes with call to action to try out preview package - @luisquintanilla 
  - [x] Collect benchmarks to include in the post - @michaelgsharp 
- [x] Make it safe across all operations to use an input span as a destination, as well, test, and document - @stephentoub
- [x] Update `CosineSimilarity` implementations to vectorize remainder processing - @stephentoub
- [x] Update `Aggregate` helper to vectorize remainder processing (`Distance`, `Dot`, `Norm`, `Sum`, `SumOfSquares`, `SumOfMagnitudes`, `Product`, `ProductOfSums`, `ProductOfDifferences`) - @stephentoub
- [x] Vectorize `Exp` - @tannergooding
- [x] Vectorize `Softmax` - @stephentoub
- [x] Vectorize `Sigmoid` - @stephentoub
- [x] Vectorize `Log` - @tannergooding
- [x] Vectorize `Log2` - @tannergooding
- [x] Vectorize `Cosh` - @stephentoub
- [x] Vectorize `Sinh` - @stephentoub
- [x] Vectorize `Tanh` - @stephentoub
- [x] Vectorize `Max` - @stephentoub
- [x] Vectorize `Max` element-wise - @stephentoub
- [x] Vectorize `Min` - @stephentoub
- [x] Vectorize `Min` element-wise - @stephentoub
- [x] Vectorize `MaxMagnitude` - @stephentoub
- [x] Vectorize `MaxMagnitude` element-wise - @stephentoub
- [x] Vectorize `MinMagnitude` - @stephentoub
- [x] Vectorize `MinMagnitude` element-wise - @stephentoub
- [x] Vectorize `ConvertToHalf` - @stephentoub
- [x] Vectorize `ConvertToSingle` - @stephentoub
- [x] Determine if we want to revert or backport FMA commit - @tannergooding (partial revert by @stephentoub)
- [x] Decide whether to throw for unsupported span overlaps (today it's just undefined behavior) - @stephentoub 
- [x] Fix functional correctness issues found during ML.NET adoption testing - @tannergooding (issues were due to in-place operations which weren't supported in RC2 but were since supported by @stephentoub)
- [x] Assess `CpuMath` APIs for methods and update the backlog below - @michaelgsharp
- [x] Validate perf of APIs (e.g. vectorized speedups are reasonable, comparison of scalar against naive implementations make sense) - @michaelgsharp
- [x] Vectorize `IndexOfMax` @michaelgsharp
- [x] Vectorize `IndexOfMin` @michaelgsharp
- [x] Vectorize `IndexOfMaxMagnitude` - @michaelgsharp
- [x] Vectorize `IndexOfMinMagnitude` - @michaelgsharp
- [x] Alignment review/guidance/updates to existing methods - @tannergooding
  - [x] Rerun perf comparisons to ensure this addresses performance penalities for small sets
  - [x] Unary methods
  - [x] Binary and ternary methods
  - [x] Aggregate and methods not using the shared helpers
  - Moved to post-GA:  `ConvertToHalf`, `ConvertToSingle`, `CosineSimilarity`, `IndexOfMin`, `IndexOfMax`, `IndexOfMinMagnitude`, `IndexOfMaxMagnitude`
- [x] Confirm required ordering semantics in `IndexOfXx` methods - @tannergooding - e.g. https://github.com/dotnet/runtime/blob/d05415704826f0bd084d2c27f99e4dbe74f62464/src/libraries/System.Numerics.Tensors/src/System/Numerics/Tensors/TensorPrimitives.cs#L602
- [x] Backport final functionality to release/8.0
- [x] Adopt in ML.NET - @michaelgsharp 
  - Methods that use indices will remain in ML.NET but could go into the TensorPrimitives backlog below
  - Methods that require composition will remain in ML.NET (for now), e.g. calculate max magnitude and subtract the mean
  - [x] Add
  - [x] AddScale
  - [x] AddScaleCopy
  - [x] Scale
  - [x] ScaleAdd (via composition, but could be improved) -- Added to backlog
  - [x] MulElementWise
  - [x] Sum
  - [x] SumSq
  - [x] SumAbs (via composition)
  - [x] MaxAbs
  - [x] MaxAbsDiff (via composition)
  - [x] DotProductDense
  - [x] L2DistSquared
  - Add (with indices) -- Added to backlog
  - AddScale (with indices) -- Added to backlog
  - DotProductSparse -- Added to backlog
  - MatrixTimesSource -- Added to backlog
  - SdcaL1UpdateDense -- Added to backlog
  - SdcaL1UpdateSparse -- Added to backlog
  - ZeroMatrixItems -- Added to backlog
- [x] Adopt in SemanticKernel once RC2 nuget package is available - @stephentoub

**Comment by luisquintanilla** [comment]
cc: @rgesteve

**Comment by bencyoung-Fignum** [comment]
Hi, I think this work is fantastic but are there any plans for a double precision version of all this?

**Comment by stephentoub** [comment]
> Hi, I think this work is fantastic but are there any plans for a double precision version of all this?

The surface area that's there is what will ship in .NET 8. We intend to create generic versions for post-. NET 8.

**Comment by jeffhandley** [comment]
All of the work for dotnet/runtime in .NET 8 GA is completed. We will have a pull request into dotnet/machinelearning to bring in the adoption of these APIs. We also have #93286 for tracking additional effort in this space.
