### ISSUE TITLE
Will #88851 be backported to .NET Core 6 or 7?

### ISSUE THREAD

**Issue by sophiewigmore** [dotnet/runtime#92239]
Hi there, I was wondering if the fix introduced in https://github.com/dotnet/runtime/pull/88851 will be backported to .NET Core 6 and/or 7. I see it is only available in .NET Core 8.0 as of now. If not, why?
Thanks!

**Comment by buyaa-n** [comment]
It is not planned for backport, mainly because there is a workaround. What is your issue/scenario that needs it to be backported NET 6 or 7?

**Comment by sophiewigmore** [comment]
Ah yea, unfortunately this issue is occuring in the context of a docker build in which a user wouldn't have root access (for security reasons) to run the `sudo ln -s /usr/lib/x86_64-linux-gnu/libldap-2.5.so.0 /usr/lib/x86_64-linux-gnu/libldap-2.4.so.2` workaround

**Comment by ericstj** [comment]
The 8.0 package still supports 6.0 and 7.0 - can you use that?   This component isn't part of the .Net runtime, it just ships with it.

**Comment by sophiewigmore** [comment]
@ericstj for clarity - you mean if I upgrade to .NET Core 8, it should still work for my .NET Core 6 builds? Or have I misunderstood?

**Comment by buyaa-n** [comment]
Not upgrading to .NET Core 8.0, [System.DirectoryServices.Protocols](https://www.nuget.org/packages/System.DirectoryServices.Protocols#versions-body-tab) is a separate nuget package so you could reference the 8.0 version: `<PackageReference Include="System.DirectoryServices.Protocols" Version="8.0.0-rc.1.23419.4" />`

**Comment by sophiewigmore** [comment]
Ah! I see. Thanks for the clarification. Let me look into that

**Comment by sophiewigmore** [comment]
Hey again @buyaa-n and @ericstj, after upgrading the Nuget package version, we now encounter:
 ```
failed to establish connection to domain: exception: The LDAP server is unavailable.
2023-09-29T11:58:07.789+05:30 [APP/PROC/WEB/0] [OUT] Stack trace: at System.DirectoryServices.Protocols.LdapConnection.BindHelper(NetworkCredential newCredential, Boolean needSetCredential)
2023-09-29T11:58:07.789+05:30 [APP/PROC/WEB/0] [OUT] at System.DirectoryServices.Protocols.LdapConnection.Bind()
```
Are there docs anywhere you can point us to that might help us resolve how to start using System.DirectoryServices.Protocols 8.0 more easily?

**Comment by sophiewigmore** [comment]
Hey again @buyaa-n and @ericstj, after upgrading the Nuget package version, we now encounter:
 ```
failed to establish connection to domain: exception: The LDAP server is unavailable.
[APP/PROC/WEB/0] [OUT] Stack trace: at System.DirectoryServices.Protocols.LdapConnection.BindHelper(NetworkCredential newCredential, Boolean needSetCredential)
 [APP/PROC/WEB/0] [OUT] at System.DirectoryServices.Protocols.LdapConnection.Bind()
```
Are there docs anywhere you can point us to that might help us resolve how to start using System.DirectoryServices.Protocols 8.0 more easily?

**Comment by buyaa-n** [comment]
> Are there docs anywhere you can point us to that might help us resolve how to start using System.DirectoryServices.Protocols 8.0 more easily?

There is not specific doc, I don't think there is anything else needed that updating the package version.

> failed to establish connection to domain: exception: The LDAP server is unavailable.

Have you double checked that the LDAP server is actually running? Could you restart the LDAP server and try to connect again?

**Comment by buyaa-n** [comment]
Hi @sophiewigmore this doc might be helpful: https://github.com/dotnet/runtime/blob/42a6776e6cb1569fe277181f424ccbbe243cf386/docs/project/dogfooding.md#obtaining-daily-builds-of-nuget-packages
