### ISSUE TITLE
[8.0] Expected and actual version of WASI SDK does not match. Please delete /usr/local/wasi-sdk/ folder to provision a new version.

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#92233]
### Error Blob

Opening a KnownBuildError issue to ensure the release/8.0 failures get tagged as known. This will be fixed by https://github.com/dotnet/runtime/pull/92143

```json
{
  "ErrorMessage": "Expected and actual version of WASI SDK does not match. Please delete /usr/local/wasi-sdk/ folder to provision a new version.",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

Build: https://github.com/dotnet/runtime/pull/92143

### Reproduction Steps

Currently blocking https://github.com/dotnet/runtime/pull/92143

Affected queues: `Build wasi-wasm linux Release LibraryTests_Smoke` and `Build wasi-wasm linux Release WasmBuildTests`

 ### Known issue validation
**Build: :mag_right:** 
**Result validation: :warning:** Validation could not be done without an Azure DevOps build URL on the issue. Please add it to the "**Build: :mag_right:**" line.
**Validation performed at:** 9/18/2023 5:23:29 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[409849](https://dev.azure.com/dnceng-public/public/_build/results?buildId=409849)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/409849/logs/1436)|dotnet/runtime#92205|
|[409973](https://dev.azure.com/dnceng-public/public/_build/results?buildId=409973)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/409973/logs/2626)|dotnet/runtime#91809|
|[409871](https://dev.azure.com/dnceng-public/public/_build/results?buildId=409871)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/409871/logs/2645)|dotnet/runtime#92109|
|[2269929](https://dev.azure.com/dnceng/internal/_build/results?buildId=2269929)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2269929/logs/3507)||
|[2270082](https://dev.azure.com/dnceng/internal/_build/results?buildId=2270082)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2270082/logs/938)||
|[410091](https://dev.azure.com/dnceng-public/public/_build/results?buildId=410091)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/410091/logs/464)||
|[2270064](https://dev.azure.com/dnceng/internal/_build/results?buildId=2270064)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2270064/logs/986)||
|[409965](https://dev.azure.com/dnceng-public/public/_build/results?buildId=409965)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/409965/logs/243)|dotnet/runtime#92208|
|[409935](https://dev.azure.com/dnceng-public/public/_build/results?buildId=409935)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/409935/logs/407)|dotnet/runtime#92211|
|[409938](https://dev.azure.com/dnceng-public/public/_build/results?buildId=409938)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/409938/logs/406)|dotnet/runtime#92211|
|[409931](https://dev.azure.com/dnceng-public/public/_build/results?buildId=409931)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/409931/logs/243)|dotnet/runtime#92223|
|[409906](https://dev.azure.com/dnceng-public/public/_build/results?buildId=409906)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/409906/logs/77)|dotnet/runtime#92226|
|[409877](https://dev.azure.com/dnceng-public/public/_build/results?buildId=409877)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/409877/logs/243)|dotnet/runtime#92220|
|[409855](https://dev.azure.com/dnceng-public/public/_build/results?buildId=409855)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/409855/logs/392)|dotnet/runtime#92135|
|[409314](https://dev.azure.com/dnceng-public/public/_build/results?buildId=409314)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/409314/logs/1424)|dotnet/runtime#92204|
|[409435](https://dev.azure.com/dnceng-public/public/_build/results?buildId=409435)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/409435/logs/2238)|dotnet/runtime#92108|
|[409708](https://dev.azure.com/dnceng-public/public/_build/results?buildId=409708)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/409708/logs/305)|dotnet/runtime#92143|
|[409641](https://dev.azure.com/dnceng-public/public/_build/results?buildId=409641)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/409641/logs/347)|dotnet/runtime#92056|
|[409721](https://dev.azure.com/dnceng-public/public/_build/results?buildId=409721)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/409721/logs/340)|dotnet/runtime#92177|
|[409589](https://dev.azure.com/dnceng-public/public/_build/results?buildId=409589)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/409589/logs/403)|dotnet/runtime#92174|
|[409567](https://dev.azure.com/dnceng-public/public/_build/results?buildId=409567)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/409567/logs/243)|dotnet/runtime#92215|
|[409520](https://dev.azure.com/dnceng-public/public/_build/results?buildId=409520)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/409520/logs/193)|dotnet/runtime#92208|
|[409514](https://dev.azure.com/dnceng-public/public/_build/results?buildId=409514)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/409514/logs/420)|dotnet/runtime#92209|
|[409503](https://dev.azure.com/dnceng-public/public/_build/results?buildId=409503)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/409503/logs/393)|dotnet/runtime#92057|
|[409319](https://dev.azure.com/dnceng-public/public/_build/results?buildId=409319)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/409319/logs/241)|dotnet/runtime#92205|
|[409264](https://dev.azure.com/dnceng-public/public/_build/results?buildId=409264)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/409264/logs/243)|dotnet/runtime#89587|
|[409247](https://dev.azure.com/dnceng-public/public/_build/results?buildId=409247)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/409247/logs/243)|dotnet/runtime#92199|
|[409233](https://dev.azure.com/dnceng-public/public/_build/results?buildId=409233)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/409233/logs/408)|dotnet/runtime#92197|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|28|28|

**Comment by radical** [comment]
The wasi sdk version was updated in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/914 and it was meant for use with `main`, but the same image is used by 8.0 branch too.

**Comment by radical** [comment]
Closing, as this is fixed now by using specific versions of the images.
