### ISSUE TITLE
StructLayout And MarshalAs(UnmanagedType.ByValArray)Memory layout error when using two attributes simultaneously

### ISSUE THREAD

**Issue by snikeguo** [dotnet/runtime#92237]
**Version Used**: 

**Steps to Reproduce**:

```csharp
using Microsoft.Win32;
using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Threading.Tasks;

namespace ConsoleApp1
{

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public unsafe struct SubStruct
    {
        public int SubField1;
        public int SubField2;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public unsafe struct BaseStruct
    {
        public int Field1;   //FieldNumber:1     
        public int Field2;   //FieldNumber:2  
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 32)]//when removing this line, the memory layout is ok
        public SubStruct[] SubStruct;
    }
    class Program
    {
       
        static unsafe void Main(string[] args)
        {
            var baseStruct=(BaseStruct*)Marshal.AllocHGlobal(Marshal.SizeOf<BaseStruct>());
            
            IntPtr field1Addr = (IntPtr) (&baseStruct->Field1);
            IntPtr baseStructAddr= (IntPtr) (baseStruct);

            Debug.Assert(field1Addr == baseStructAddr);
            Console.WriteLine("hello world!");
            Console.ReadLine();
        }
    }
}
```
![image](https://github.com/dotnet/roslyn/assets/20830435/89619a46-effb-48ff-9414-8a40adb386c0)

A minimal repro, with source-code provided, is ideal.  Using [sharplab](https://sharplab.io/) is preferred for compiler/language issues whenever possible.

**Diagnostic Id**:

If this is a report about a bug in an analyzer, please include the diagnostic if possible (e.g. `"IDE0030"`).

**Expected Behavior**:

**Actual Behavior**:

**Comment by jaredpar** [comment]
Appears to be a question about how these attributes function at execution time vs. what the compiler is emitting so transfering to runtime.

**Comment by AaronRobinsonMSFT** [comment]
```csharp
            IntPtr field1Addr = (IntPtr) (&baseStruct->Field1);
            IntPtr baseStructAddr= (IntPtr) (baseStruct);
```

This is undefined behavior. The reason being `BaseStruct` is [non-blittable](https://learn.microsoft.com/dotnet/framework/interop/blittable-and-non-blittable-types). It is invalid to assume layout on non-blittable types. The [`unmanaged`](https://learn.microsoft.com/dotnet/csharp/language-reference/builtin-types/unmanaged-types) type in C# is very closely related to being blittable, but there are some differences unless [runtime marshalling is disabled](https://learn.microsoft.com/dotnet/standard/native-interop/disabled-marshalling). The attribute in question let's the runtime know how it can marshal the type during an interop call and will project the desired state, but validating type layouts of non-blittable types is not supported and should not be attempted.

The above scenario could be done in a supported manner using [`InlineArrayAttribute`](https://learn.microsoft.com/dotnet/api/system.runtime.compilerservices.inlinearrayattribute) in .NET 8.
