### ISSUE TITLE
Remove usage of InterceptorsPreview feature after updating to 8.0 RC2 SDK

### ISSUE THREAD

**Issue by mthalman** [dotnet/runtime#92248]
Once the runtime repo has been updated to use 8.0 RC2 SDK, the usage of the `InterceptorsPreview` feature can be removed from Microsoft.Extensions. See the changes in https://github.com/dotnet/runtime/pull/92247 that indicate what needs to be removed.

**Comment by ericstj** [comment]
Marked this as a tracking issue to remind us to cleanup the source.  This isn't blocking release and these settings don't leak to customers in the product, but would be nice to clean up.
