### ISSUE TITLE
.NET 8 RC1 build fails on Ubuntu ARM64 with "Cannot find mkstemps nor mkstemp on this platform"

### ISSUE THREAD

**Issue by mateusrodrigues** [dotnet/runtime#92244]
### Describe the Bug

I'm building the .NET 8 RC1 bootstrap package on Ubuntu 23.10 devel branch (Mantic) using sbuild and I keep hitting this error when the script starts building the native parts of the runtime:

```
-- Performing Test HAVE_MKSTEMPS
-- Performing Test HAVE_MKSTEMPS - Failed
-- Performing Test HAVE_MKSTEMP
-- Performing Test HAVE_MKSTEMP - Failed
CMake Error at /<<PKGBUILDDIR>>/src/runtime/artifacts/source-build/self/src/src/native/libs/configure.cmake:822 (message):
  Cannot find mkstemps nor mkstemp on this platform.
Call Stack (most recent call first):
  /<<PKGBUILDDIR>>/src/runtime/artifacts/source-build/self/src/src/native/libs/CMakeLists.txt:116 (include)
```

Here's a [full build log](https://launchpadlibrarian.net/686929996/buildlog_ubuntu-mantic-arm64.dotnet8_8.0.100-8.0.0~rc1~bootstrap+arm64-0ubuntu1~ppa1_BUILDING.txt.gz) from Launchpad and the [package itself](https://launchpad.net/~mateus-morais/+archive/ubuntu/dotnet8.0.100-rc1-arm64-bootstrap/+packages) in the PPA.

It's worth mentioning that this bug only happens inside an sbuild schroot environment. Invoking `./build.sh` directly on the machine 

I came across dotnet/runtime#66340 and the error looks really similar, however LTO is already disabled in my build. Ubuntu Mantic is currently on glibc 2.38.

I'm happy to provide any additional info that may be useful, I'm just not sure what they would be at this point, since this is a really strange error.

### Steps to Reproduce

1. Unpack the [VMR tarball](https://launchpad.net/~mateus-morais/+archive/ubuntu/dotnet8.0.100-rc1-arm64-bootstrap/+sourcefiles/dotnet8/8.0.100-8.0.0~rc1~bootstrap+arm64-0ubuntu1~ppa1/dotnet8_8.0.100-8.0.0~rc1~bootstrap+arm64.orig.tar.xz) and the [debian folder](https://launchpad.net/~mateus-morais/+archive/ubuntu/dotnet8.0.100-rc1-arm64-bootstrap/+sourcefiles/dotnet8/8.0.100-8.0.0~rc1~bootstrap+arm64-0ubuntu1~ppa1/dotnet8_8.0.100-8.0.0~rc1~bootstrap+arm64-0ubuntu1~ppa1.debian.tar.xz) in the same directory.
2. Also keep the file `dotnet8_8.0.100-8.0.0~rc1~bootstrap+arm64.orig.tar.xz` in the parent directory of the source tree
3. Run `$ mk-sbuild mantic` on an arm64 machine to build an Ubuntu Mantic schroot
4. Run `$ sbuild -d mantic --purge-build=successful --debbuildopts='--buildinfo-option=-O' --no-run-lintian` from within the source tree

### Other Information

The sbuild command builds the source tree from an "isolated" schroot environment, I'm suspecting this might have something to do with a configuration within this environment. I'm just not sure what it is or what to look for.

**Comment by MichaelSimons** [comment]
Transferred from source-build to runtime as this is runtime specific.

**Comment by mateusrodrigues** [comment]
This issue has been solved, posting the solution for documentation purposes:

According to [CMakeConfigureLog.yaml.gz](https://github.com/dotnet/runtime/files/12664484/CMakeConfigureLog.yaml.gz), the MKSTEMP(S) tests failed with the following error:
```
...
clang: error: argument unused during compilation: '-fstack-clash-protection' [-Werror,-Wunused-command-line-argument]
...
```
The same error also occurred a few times throughout the log.

We fixed the error by stripping this flag from the default toolchain compiler flags with
```
ifeq ($(DEB_HOST_ARCH), arm64)
	export DEB_CFLAGS_MAINT_STRIP = -fstack-clash-protection
	export DEB_CXXFLAGS_MAINT_STRIP = -fstack-clash-protection
endif
```
which, then, resulted in a [successful build](https://launchpad.net/~mateus-morais/+archive/ubuntu/dotnet8.0.100-rc1-arm64-bootstrap/+build/26720499).

**Comment by MichaelSimons** [comment]
Thanks for responding with the solution.  Closing.
