### ISSUE TITLE
Error NETSDK1013: The TargetFramework value '' was not recognized.

### ISSUE THREAD

**Issue by Warentan** [dotnet/runtime#92251]
### Description

Hello. I am trying to play a videogame that runs on .NET to run. Whenever I try to build the server file, it throws an exception. I have never used dotnet before, and it seems that this issue is not commonly referenced;

usr/lib/dotnet/sdk/7.0.111/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(92,5): error NETSDK1013: The TargetFramework value ' ' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly. [/home/[CENSOR]/SS14DEV/space-station-14/Content.Server/Content.Server.csproj]

The block where the error leads to shows;

  <Target Name="_CheckForUnsupportedTargetFramework"
          BeforeTargets="_CheckForInvalidConfigurationAndPlatform;RunResolvePackageDependencies;GetFrameworkPaths;GetReferenceAssemblyPaths;Restore"
          Condition="'$(_UnsupportedTargetFrameworkError)' == 'true'"
          >
    **<NETSdkError Condition="!$(TargetFramework.Contains(';'))"**
                 ResourceName="CannotInferTargetFrameworkIdentifierAndVersion"
                 FormatArguments="$([MSBuild]::Escape('$(TargetFramework)'))" />

    <NETSdkError Condition="$(TargetFramework.Contains(';'))"
                 ResourceName="TargetFrameworkWithSemicolon"
                 FormatArguments="$([MSBuild]::Escape('$(TargetFramework)'))" />
  </Target>

I have bolded the exact issue. Any leads?

### Reproduction Steps

Attempt to run dotnet build Anywhere it should be

### Expected behavior

Simply build the code with no fatal errors

### Actual behavior

Throws an "Unrecognized value" error.

### Regression?

Used to work on an unknown build. I have no records of the build working, so I cannot make them tangible.

### Configuration

7.0.111
Ubuntu 22.04.3
x64

**Comment by ericstj** [comment]
As @vcsjones mentions, https://github.com/space-wizards/space-station-14/ is a better place to open this issue.
