### ISSUE TITLE
Inconsistent behavior between TimeProvider in .NET 8 and .NET 6 during testing

### ISSUE THREAD

**Issue by egil** [dotnet/runtime#92264]
### Description

It seems the fix https://github.com/dotnet/runtime/pull/90489 has not solved the problem reported in https://github.com/dotnet/runtime/issues/85326. There is still a difference in behavior between .NET 8 and earlier versions using the `Microsoft.Bcl.TimeProvider` package.

### Reproduction Steps

The following tests pass when run under .NET 8, but fail with .NET 6.

```c#
[Fact]
public void Delayed_task_is_cancelled()
{
    using var cts = new CancellationTokenSource();
    var sut = new FakeTimeProvider();
    var task = sut.Delay(TimeSpan.FromMilliseconds(1), cts.Token);

    cts.Cancel();

    Assert.Equal(TaskStatus.Canceled, task.Status);
}

[Fact]
public async Task WaitAsync_callbacks_runs_synchronously()
{
    // arrange
    var sut = new FakeTimeProvider();
    var callbackCount = 0;
    var continuationTask = Continuation(sut, () => callbackCount++);

    // act
    sut.Advance(TimeSpan.FromSeconds(10));

    // assert
    Assert.Equal(1, callbackCount);
    await continuationTask;

    static async Task Continuation(TimeProvider timeProvider, Action callback)
    {
        try
        {
            await Task
                .Delay(TimeSpan.FromDays(1))
                .WaitAsync(TimeSpan.FromSeconds(10), timeProvider);
        }
        catch (TimeoutException)
        {
            callback();
        }
    }
}
```

Adding in a `await Task.Yield();` to the tests before the assertions fix the issue.

### Expected behavior

The behavior should be the same with both .NET 8 and .NET 6.

### Actual behavior

Tests pass when target framework is .NET 8 and fail when target framework is .NET 6

### Known Workarounds

Add a `await Task.Yield()` before the assertions in the tests cause the tests to pass, however, this is not an ideal solution and may not work consistently, e.g. if the tests are executed on slower hardware, e.g. CI pipeline.

### Other information

Versions used:

```xml
<PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" Version="8.0.0-rc.1.23453.1" />
<PackageReference Include="Microsoft.Bcl.TimeProvider" Version="8.0.0-rc.1.23419.4" />
```

**Comment by egil** [comment]
cc. @tarekgh

**Comment by tarekgh** [comment]
We have investigated this, and we see the difference in behavior of the underlying platform; there's very little TimeProvider can do here to paper over that difference. Fortunately, the difference is minor, and it is easy to work around it.

**Comment by egil** [comment]
> nit: `WaitAsync_callbacks_runs_synchronously` isn't a threadsafe test.  The modification of `callbackCount` may not be correctly propagated across threads.

Yeah, the callbackCount variable should be volatile, right, to ensure this?

**Comment by Clockwork-Muse** [comment]
> Yeah, the callbackCount variable should be volatile, right, to ensure this?

You can't have a `volatile` local.

Even then, [apparently not](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/volatile):
> On a multiprocessor system, a volatile read operation does not guarantee to obtain the latest value written to that memory location by any processor. Similarly, a volatile write operation does not guarantee that the value written would be immediately visible to other processors.

The specific problem here is that you only read the value once, and so even if `volatile` disables certain optimizations that make the value propagate, it happens "eventually", not necessarily in time for the next temporal execution (the traditional example uses a loop for a reason).

So you need either a `lock` or a set of `Interlocked` operations (both for read and write - the value can't be torn since it's an `int`, but the thing you're worried about is propagation, so you need a barrier for both).

**Comment by egil** [comment]
> > Yeah, the callbackCount variable should be volatile, right, to ensure this?
> 
> You can't have a `volatile` local.
> 
> Even then, [apparently not](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/volatile):
> > On a multiprocessor system, a volatile read operation does not guarantee to obtain the latest value written to that memory location by any processor. Similarly, a volatile write operation does not guarantee that the value written would be immediately visible to other processors.
> 
> The specific problem here is that you only read the value once, and so even if `volatile` disables certain optimizations that make the value propagate, it happens "eventually", not necessarily in time for the next temporal execution (the traditional example uses a loop for a reason).
> 
> So you need either a `lock` or a set of `Interlocked` operations (both for read and write - the value can't be torn since it's an `int`, but the thing you're worried about is propagation, so you need a barrier for both).

Yeah, multi processor issues are fun. Good point, although not something that affects this particular issue, but good to be aware of none the less 🙂
