### ISSUE TITLE
Support xcode 15

### ISSUE THREAD

**Issue by chenrui333** [dotnet/runtime#92260]
### Description

Right now when building mono for macOS Sonoma (which is using xcode 15), homebrew run into the following build failure

```
/private/tmp/mono--fsharp-20230918-6684-1q8b9ad/eng/common/tools.sh: line 447: /private/tmp/mono--fsharp-20230918-6684-1q8b9ad/.dotnet/dotnet: Bad CPU type in executable
Build failed (exit code '126').
Error preparing build (exit code '126').
```
full log in here, https://github.com/Homebrew/homebrew-core/actions/runs/6223635919/job/16890078885

We might need similar fix like https://github.com/dotnet/runtime/pull/76433 to support xcode 15

previous homebrew fix PR for ventura, https://github.com/Homebrew/homebrew-core/pull/117052

### Reproduction Steps

N/A

### Expected behavior

pass the build

### Actual behavior

failed, log as attached above

### Configuration

- macOS sonoma

**Comment by lambdageek** [comment]
(This is about https://github.com/mono/mono, not about the Mono runtime in the dotnet/runtime repo.)

**Comment by akoeplinger** [comment]
Please file this in https://github.com/mono/mono instead which tracks the legacy Mono. Note that we don't support Homebrew officially and you're encouraged to install the .pkg from https://www.mono-project.com/download/stable/#download-mac instead.
