### ISSUE TITLE
Configuration-binding source generator error in .NET 8

### ISSUE THREAD

**Issue by rstropek** [dotnet/runtime#92273]
### Description

Configuration-binding source generator generates syntactically incorrect code.

### Reproduction Steps

* Create a new ASP.NET Core API with Native AOT: `dotnet new webapiaot`
* Add a class receiving options at the end of *Program.cs*:

    ```cs
    public class AppFeatures { public bool ProvideMasterdata { get; set; } }
    ```

* Add code reading a config section:

    ```cs
    ...
    var builder = WebApplication.CreateSlimBuilder(args);
    var section = builder.Configuration.GetSection("AppFeatures"); // <<< added
    builder.Services.Configure<AppFeatures>(section); // <<< added
    ....
    ```

* Add `global using Microsoft.Extensions.Options;` at the very top of *Program.cs*
* Build app: `dotnet build`

Note that the error can also be reproduced by running the sample code [in the docs](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8#configuration-binding-source-generator):

* `dotnet new console`
* Change `Sdk` in *.csproj* to `Microsoft.NET.Sdk.Web`
* Add `global using Microsoft.Extensions.Options;` at the very top of *Program.cs*
* `dotnet build` -> same error (details see below)

### Expected behavior

Program compiles without error.

### Actual behavior

Source generator generates code that does not compile because of a syntax error. The syntax error is: `/tmp/ConfigurationBinderError/Microsoft.Extensions.Configuration.Binder.SourceGeneration/Microsoft.Extensions.Configuration.Binder.SourceGeneration.ConfigurationBindingGenerator/BindingExtensions.g.cs(56,227): error CS1003: Syntax error, ',' expected [/tmp/ConfigurationBinderError/ConfigurationBinderError.csproj]`

Generated code (snippet; generated with `EmitCompilerGeneratedFiles`):

```cs
...new Microsoft.Extensions.Options.ConfigureNamedOptions<TOptions>(name, obj => BindCoreMain(configuration, obj, typeof(TOptions)configureOptions)));
```

Comma seems to be missing between `typeof(TOptions)` and `configureOptions`.

### Configuration

* Runtime: Microsoft.AspNetCore.App 8.0.0-rc.1.23421.29
* SDK: 8.0.100-rc.1.23455.8
* OS: Linux

**Comment by ericstj** [comment]
I repro'ed this on RC1 and confirmed it's fixed in RC2.  If you'd like to try out the fix you can do the following:

Add NuGet.config for nightly builds of .NET 8:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="dotnet8" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

Reference latest RC2 build:
```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.0-rc.2.23466.4" />
  </ItemGroup>
```

**Comment by rstropek** [comment]
@ericstj Thank you, nightly works fine.

**Comment by ericstj** [comment]
Thank you for the report and the confirmation, @rstropek
