### ISSUE TITLE
.NET 8 RC1: NativeAOT fails to build for linux-bionic-arm64 when specifying project as library (Linker error)

### ISSUE THREAD

**Issue by LittleCodingFox** [dotnet/runtime#92272]
### Description

I was trying out .NET 8 RC1 for NativeAOT for android bionic, and I get an error regarding ld.lld with a missing symbol for `_init` and `_fini`.

### Reproduction Steps

Using the default steps to make a NativeAOT project for android:

`dotnet new console -o HelloBionic --aot`

open the csproj and edit the type to `Library` instead of `Exe`

Finally, change the `Program.cs` file to not use top-level statements. Something empty such as an empty namespace and/or class should suffice.

`dotnet publish -r linux-bionic-arm64 -p:DisableUnsupportedError=true -p:PublishAotUsingRuntimePack=true`

### Expected behavior

It should create the library rather than error. It creates the executable properly when it's set as `Exe`.

### Actual behavior

Get error:

```
ld.lld : error : version script assignment of 'V1.0' to symbol '_init' failed: symbol not defined [HelloBionic\HelloBionic.csproj]
ld.lld : error : version script assignment of 'V1.0' to symbol '_fini' failed: symbol not defined [HelloBionic\HelloBionic.csproj]
clang : error : linker command failed with exit code 1 (use -v to see invocation) [HelloBionic\HelloBionic.csproj]

...\.nuget\packages\microsoft.dotnet.ilcompiler\8.0.0-rc.1.23419.4\build\Microsoft.NETCore.Native.targets(364
,5): error MSB3073: The command ""clang" "obj\Release\net8.0\linux-bionic-arm64\native\HelloBionic.o" -o "bin\Release\n
et8.0\linux-bionic-arm64\native\HelloBionic.so" -Wl,--version-script=obj\Release\net8.0\linux-bionic-arm64\native\Hello
Bionic.exports -gz=zlib -fuse-ld=lld ...\.nuget\packages\microsoft.netcore.app.runtime.nativeaot.linux-bionic
-arm64\8.0.0-rc.1.23419.4/runtimes/linux-bionic-arm64/\native\libbootstrapperdll.o ...\.nuget\packages\micros
oft.netcore.app.runtime.nativeaot.linux-bionic-arm64\8.0.0-rc.1.23419.4/runtimes/linux-bionic-arm64/\native\libRuntime.
WorkstationGC.a ...\.nuget\packages\microsoft.netcore.app.runtime.nativeaot.linux-bionic-arm64\8.0.0-rc.1.234
19.4/runtimes/linux-bionic-arm64/\native\libeventpipe-disabled.a ...\.nuget\packages\microsoft.netcore.app.ru
ntime.nativeaot.linux-bionic-arm64\8.0.0-rc.1.23419.4/runtimes/linux-bionic-arm64/\native\libstdc++compat.a ...\.nuget\packages\microsoft.netcore.app.runtime.nativeaot.linux-bionic-arm64\8.0.0-rc.1.23419.4/runtimes/linux-bionic-
arm64/\native\libSystem.Native.a ...\.nuget\packages\microsoft.netcore.app.runtime.nativeaot.linux-bionic-arm
64\8.0.0-rc.1.23419.4/runtimes/linux-bionic-arm64/\native\libSystem.IO.Compression.Native.a ...\.nuget\packag
es\microsoft.netcore.app.runtime.nativeaot.linux-bionic-arm64\8.0.0-rc.1.23419.4/runtimes/linux-bionic-arm64/\native\li
bSystem.Security.Cryptography.Native.OpenSsl.a --target=aarch64-linux-android21 -g -Wl,-rpath,"$ORIGIN" -Wl,--build-id=
sha1 -Wl,--as-needed -Wl,-e0x0 -pthread -ldl -lz -llog -lm -shared -Wl,-z,relro -Wl,-z,now -Wl,--eh-frame-hdr -Wl,--dis
card-all -Wl,--gc-sections -Wl,-T,"obj\Release\net8.0\linux-bionic-arm64\native\sections.ld"" exited with code 1. [...\HelloBionic\HelloBionic.csproj]
```

### Configuration

.NET version: 8.0.100-rc.1.23455.8
OS: Windows 10 (constantly updated so I assume latest version)
Architecture: x64
I'm not sure if it's specific to this configuration

**Comment by MichalStrehovsky** [comment]
What's the Android NDK that is on your PATH? This doesn't repro for me - it generates an .so file fine (even though there were no UnmanagedCallersOnly methods so it's a bit of a nonsensical library).

**Comment by LittleCodingFox** [comment]
The Android NDK in my PATH is `C:/Users/User/AppData/Local/Android/Sdk/ndk/26.0.10792818/toolchains/llvm/prebuilt/windows-x86_64/bin`, so `26.0.10792818`.

Thank you!

**Comment by LittleCodingFox** [comment]
Will do, I'll have a look and let you know the results!

**Comment by LittleCodingFox** [comment]
I just tried r23c and it did build the .so properly! So this seems an issue with r26.

Would be good to see if it's possible to make this work with r26 too, since r23 is considered an unsupported version now (it showed in the "Unsupported Downloads" page for NDK).

Thank you for your time!

**Comment by am11** [comment]
A workaround could be something like:

(untested)
```csproj
<!-- your .csproj -->
<ItemGroup Condition="'$(RuntimeIdentifier)' == 'linux-bionic'">
  <LinkerArg Include="-Wl,--defsym,_init=__libc_init" />
  <LinkerArg Include="-Wl,--defsym,_fini=__libc_fini" />
</ItemGroup
```

If it works, we can add it next to:
https://github.com/dotnet/runtime/blob/5883b728c8b29a7026cf3a807a22928cee844bc5/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Unix.targets#L162

**Comment by LittleCodingFox** [comment]
Hello @am11, it seems to have worked! At least, it doesn't complain anymore.

**Comment by CasualPokePlayer** [comment]
I ran into this issue on my own project trying to go to the latest NDK LTS (which is currently 26.2.11394342), and it seems the workaround no longer works for that version.
```
ld.lld : error : --defsym:1: symbol not found: __libc_fini
ld.lld : error : --defsym:1: symbol not found: __libc_init
```

**Comment by CasualPokePlayer** [comment]
Looking at the .so produced by older NDK, it actually looks like there's no _init or _fini defined in the first place. Looking at the error, it seems to be triggered for `--no-undefined-version`, which got switched to being [the default in clang 16](https://reviews.llvm.org/D135402), indicating it only ever "worked" before due to clang not erroring due to the missing symbols (which even then, at runtime these missing symbols don't seem to cause any issues? at least for my project)

**Comment by am11** [comment]
Thanks for the investigation @CasualPokePlayer. I was able to repro it with LTS and your workaround fixed it. Would you like to send a PR updating https://github.com/dotnet/runtime/blob/9b57a265c7efd3732b035bade005561a04767128/src/coreclr/nativeaot/docs/android-bionic.md#known-issues? An additional correction was required in the condition:
`<ItemGroup Condition="$(RuntimeIdentifier.StartsWith('linux-bionic'))">`
