### ISSUE TITLE
Httpclient dns translation should be configurable

### ISSUE THREAD

**Issue by alons1** [dotnet/runtime#92314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm using HttpClientFactory to issue http requests to a hostname (e.g. login.microsoft.com) 
My customer has a proxy blocking that allows requests only to that hostname.
.NET core resolves the hostname to an ip and then initiates the connection, which caused the request to get blocked since it's allowed only to the hostname.

Also, the ip range for login.microsoft.com is dynamic so they can't even whitelist those.

Requests with Postman for example work because it doesn't do dns translations.

HTTP:Request, CONNECT 20.190.181.1:443   - with .NET

HTTP:Request, CONNECT login.microsoftonline.com:443 - with Postman

### Describe the solution you'd like

Give a way to disable dns translations

**Comment by wfurt** [comment]
What API do you use and how do you set your proxy? AFAIK the name should be preserved as it also impacts SNI during TLS handshake.

**Comment by alons1** [comment]
> What API do you use and how do you set your proxy? AFAIK the name should be preserved as it also impacts SNI during TLS handshake.

What do you mean by API?
As stated in my original post I'm using HttpClientFactory to make the requests.

The proxy is set at the windows level under Internet Options with the "Use automatic configuration script" enabled which points to a PAC file

**Comment by ManickaP** [comment]
@alons1 could you post a repro case and do a packet capture? From my own test the outgoing connect request looks like:
```
CONNECT github.com:443 HTTP/1.1\r\n
    [Expert Info (Chat/Sequence): CONNECT github.com:443 HTTP/1.1\r\n]
        [CONNECT github.com:443 HTTP/1.1\r\n]
        [Severity level: Chat]
        [Group: Sequence]
    Request Method: CONNECT
    Request URI: github.com:443
    Request Version: HTTP/1.1
```

**Comment by alons1** [comment]
I have an ongoing Microsoft support case about this.
Will update when I know the solution

**Comment by ManickaP** [comment]
I used Wireshark and entered proxy address and port for http / https in internet options.

**Comment by alons1** [comment]
> I used Wireshark and entered proxy address and port for http / https in internet options.

In my case the issue happened when using an http url that leads to a PAC file in internet options
Not an ip:port combination

**Comment by ManickaP** [comment]
Could you still do a packet capture with Wireshark and share your repro code? In your environment with your settings.
