### ISSUE TITLE
[API Proposal]: JsonNumberHandling.AllowReadingEmptyStringAsDefault

### ISSUE THREAD

**Issue by fowl2** [dotnet/runtime#92331]
### Background and motivation

JSON that puts numbers in double quotes exists, and is supported with `JsonNumberHandling.AllowReadingFromString`. It's even the default for "Web".

JSON that puts numbers in double quotes, and represents "no value" as an empty string also exists, and currently is difficult to deal with. 

``` csharp
class Person
{
    public string Name { get; set; }
    public double? Age { get; set; }
}
```

``` json
[
  { "name": "Jane", "age": null }, // works out of the box
  { "name": "Alice", "age": 80 }, // works out of the box
  { "name": "Jane", "age": "10" }, // works with JsonNumberHandling.AllowReadingFromString
  { "name": "John", "age": "" }, // error! proposed: JsonNumberHandling.AllowReadingEmptyStringAsDefault
]
```

I'm not proposing making this the default in any situation.

- previously reported: https://github.com/dotnet/runtime/issues/46448

### API Proposal

```csharp
namespace System.Text.Json.Serialization;

[Flags]
public enum JsonNumberHandling
{
    AllowReadingEmptyStringAsDefault = 8 | AllowReadingFromString,
}
```

Specifying `AllowReadingEmptyStringAsDefault` implies `AllowReadingFromString` - it could be an error instead.

### API Usage

```csharp
new JsonSerializerOptions
{
    NumberHandling = JsonNumberHandling.AllowReadingEmptyStringAsDefault,
}
```

### Alternative Designs

1. A custom or in-box `JsonConverter`. 

Example for `double?`, haven't considered being more generic:

``` csharp
sealed class JsonEmptyStringIsNullDoubleConverter : JsonConverter<double?>
{
    public static readonly JsonEmptyStringIsNullDoubleConverter Instance = new();

    private JsonEmptyStringIsNullDoubleConverter() { }

    public override double? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.ValueTextEquals(""))
        {
            return null;
        }

        if (Utf8Parser.TryParse(reader.ValueSpan, out double retval, out int bytesConsumed)
            && reader.ValueSpan.Length == bytesConsumed)
        {
            return retval;
        }

        throw new JsonException();
    }

    public override void Write(Utf8JsonWriter writer, double? value, JsonSerializerOptions options)
        => throw new NotImplementedException(); // not clear if reading implies/writing, how they could compose
}
```

It could also implemented in terms of built in JsonConverter.

2. Making `Utf8JsonWriter.GetDecimalWithQuotes()` or similar public.

### Risks

Performance: An additional branch in `GetDecimalWithQuotes`

Complexity: If similar handling needed to be added for eg. empty strings as null for objects, it could be confusing which mechanism to use.

**Comment by eiriktsarpalis** [comment]
Agreed that this doesn't appear to be a common enough scenario to required a dedicated `JsonNumberHandling` value. I would recommend authoring a custom converter for your number type instead.

**Comment by fowl2** [comment]
Sure I accept that.

For backlink purposes, this was also reported at https://github.com/dotnet/runtime/issues/58289 - so there's at least three of us 😅
