### ISSUE TITLE
[Breaking change?] Exception "Reflection-based serialization has been disabled for this application" is thrown on Mac Release

### ISSUE THREAD

**Issue by idigra** [dotnet/runtime#92345]
### Description

When moving from .NET 7 to .NET 8 (RC1), we started to experience "Reflection-based serialization has been disabled for this application" exception.
The exception is thrown only on very specific conditions - Mac, Release configuration and only on specific tester app (but not in another app).
Because it's release-only failure it's hard to provide more information using a debugger.

I looked in the breaking changes document but couldn't find a documentation of exactly this kind of failure. I found something that seems related, but I failed to find an explaining for the type of exception we're experiencing: https://learn.microsoft.com/en-us/dotnet/core/compatibility/serialization/8.0/metadata-resolving

Following "What's new" section about "Disabling reflection defaults" seems more related, but yet I failed to find something that could break when moving to .NET 8 after it's used to work on .NET 7: https://devblogs.microsoft.com/dotnet/system-text-json-in-dotnet-8/#disabling-reflection-defaults
Based on this, I believe that setting JsonSerializer.IsReflectionEnabledByDefault to false would workaround the issue, but I'm not sure if it's the right thing to do.

### Reproduction Steps

As I wrote in the description, it's very hard to reduce the case into a specific compact scenario and rootcause, because I'm failing to use a debugger for this release-only failure. Sharing the whole tester app is both too large and contain internal binaries. If no known such breaking change which I can look for, I'll be available to provide more details and do some trials when asked.

### Expected behavior

Code should behave just like in .NET 7 and not throw.

### Actual behavior

Exception "Reflection-based serialization has been disabled for this application" is thrown

### Regression?

Yes. Worked on .NET 7.

### Known Workarounds

Setting JsonSerializer.IsReflectionEnabledByDefault to false would probably solve it.

**Comment by jkotas** [comment]
The System.Text.Json reflection is disabled by default for trimmed apps. Does your tester app use trimming (look for `PublishTrimmed` or `PublishAot` in project files and build scripts)?

**Comment by eiriktsarpalis** [comment]
> Based on this, I believe that setting JsonSerializer.IsReflectionEnabledByDefault to false would workaround the issue, but I'm not sure if it's the right thing to do.

Correct, adding the property
```xml
<JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
```
to your project configuration should you back the behavior in .NET 7.

**Comment by idigra** [comment]
> The System.Text.Json reflection is disabled by default for trimmed apps. Does your tester app use trimming (look for `PublishTrimmed` or `PublishAot` in project files and build scripts)?

Yes, we're using PublishTrimmed=true (with the non default TrimMode=partial, if it matters).

However:
- We used same trimming on .NET 7 and it was not an issue.
- Same DLL, built with PublishTrimmed=true, is not failing when hosted in another app (I guess this can be explained by the fact that the top level executable of the other app is not trimmed? It's actually a native app that hosts the .NET binaries).

**Comment by eiriktsarpalis** [comment]
> We used same trimming on .NET 7 and it was not an issue.

Reflection serialization _can_ work in trimmed applications, be warned though that it can be fragile and is subject to breaks even with subtle (and superficially unrelated) changes to your code.

**Comment by idigra** [comment]
> Reflection serialization _can_ work in trimmed applications, be warned though that it can be fragile and is subject to breaks even with subtle (and superficially unrelated) changes to your code.

I see. Then what is the right way to mitigate the issue - I mean, what would be a stable solution, rather than the breakable workaround of setting JsonSerializerIsReflectionEnabledByDefault to true?

**Comment by jkotas** [comment]
Use [System.Text.Json source generator](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation-modes). It is the only fully reliable option with trimming.

**Comment by vitek-karas** [comment]
I'm curious - you should be getting a warning when publishing the trimmed app in this case. Did it no happen in your case?

**Comment by idigra** [comment]
> I'm curious - you should be getting a warning when publishing the trimmed app in this case. Did it no happen in your case?

What warning exactly? If this warning shown on .NET 7 too, then we probably already silented it.

**Comment by vitek-karas** [comment]
For example, `JsonSerializer.Serialize` call should produce a warning.
You would get that warning on .NET 7 as well.

Silencing these warnings means that you're in "undefined" territory. In another way, we consider it acceptable to change/break behavior of trimmed apps which ignore trim related warnings. It may or may not work, and even if it works, it can be broken by an upgrade.

**Comment by idigra** [comment]
> For example, `JsonSerializer.Serialize` call should produce a warning. You would get that warning on .NET 7 as well.
> 
> Silencing these warnings means that you're in "undefined" territory. In another way, we consider it acceptable to change/break behavior of trimmed apps which ignore trim related warnings. It may or may not work, and even if it works, it can be broken by an upgrade.

Is there a closed set of warning codes that are related to such breakable behavior? I'd like to search these in our NoWarn directives.

**Comment by vitek-karas** [comment]
Basically all `IL####` warning codes. Some of them might be OK to ignore, but vast majority of them are not OK to ignore.
There's a property which suppresses them in bulk [`SuppressTrimAnalysisWarnings`](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-7-0#analysis-warnings).

**Comment by idigra** [comment]
Well yeah, we have some IL####s silented. We're aware of the risks, that's why we use partial trimming mode and carefully selecting what to optimize out. It results in large package size but it's a large effort to adapt our huge long-running codebase to modern linking mechanism without risk. We have future backlog item to do so :)
Anyway, for your question - yes, seems that it's expected as probably the relevant warnings are silented.

**Comment by vitek-karas** [comment]
Thanks for the info - I absolutely understand that it's a large effort to make existing code bases trim compatible. Feel free to create issues/discussions if you're stuck, we'll be happy to help.
