### ISSUE TITLE
How are we doing in the repo? -- spot check

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#92378]
![image](https://github.com/dotnet/runtime/assets/6385855/bd3fe7e2-61e5-477f-af0f-980a62ab3d04)

It's midyear between our surveys and we'd like to hear from you how we're doing.

<link removed>

If you are reading this, we'd welcome your input. There's only one question so it should take just seconds (unless you want to write something)

-- dotnet/runtime maintainers

**Comment by danmoseley** [comment]
I should add, if you aren't happy, we'd particularly be grateful if you'd write something there too!

**Comment by Ponant** [comment]
You guys are awesome. Enjoy your 5k+ issues! :)
Thanks for the work. I suggested a change a few days ago, one day later it was included in a PR. I guess a thank you would have been welcomed but with 5k+ issues I understand :):).
Keep it up and we do too, outsite.

**Comment by danmoseley** [comment]
cc @dotnet/dotnet-runtime-triage in case any of those folks have not had a chance and would like to.

**Comment by danmoseley** [comment]
thanks everyone, here's the results for this repo. for context, NSAT (net satisfaction) is an aggregate measure we use a lot to summarize. The range is 0-200 and above 100 is considered good. Error is quite low as there were 37 responses.

| NSAT | NSAT (spring 2023) | NSAT (spring 2022) | NSAT (spring 2021) |
| ---- | ------------------ | ------------------ | ------------------ |
| 126  | 120                | 127                | 102                |

Themes in the comments
1. Be more responsive - particularly on PR's and API proposals, and also one ask to be more transparent if discussion is happening off thread for some reason. Responsiveness was the top theme.
2. Reduce time between a fix and a released build (example of a change in runtime 3 weeks before RC1 that didn't get into RC1)
3. Make local builds faster.
4. Clarify when to use discussions vs. issues.
5. Avoid internal dependencies
6. Decision making - one respondent felt that 'politics' was weighing into feature decisions

It would be good to know more specifics about the last two.

Thank you so much for taking time to share all this... discussions here are welcome, meantime I will un-pin and close the survey.

**Comment by ViktorHofer** [comment]
> Reduce time between a fix and a released build (example of a change in runtime 3 weeks before RC1 that didn't get into RC1)

cc @SteveMCarroll @mmitche

> Make local builds faster.

cc @dotnet/runtime-infrastructure, @agocke. We (libraries team) want to further optimize the libraries build as there's still room for improvement (basically the build graph is double the size that it needs to be because of the ref/src split). That said, the majority of time spent is in the native build (coreclr + host) which needs to be built to run tests.

> Clarify when to use discussions vs. issues.

Agreeing on that. From a maintainer perspective, it's hard to keep track of discussions. Example: https://github.com/dotnet/runtime/discussions/92126#discussioncomment-7171733
