### ISSUE TITLE
.NET 8 preview 7 and RC 1 seem to be ignoring IlcGenerateStackTraceData property

### ISSUE THREAD

**Issue by evgeniykarimov** [dotnet/runtime#92373]
### Description

We are using native AOT with IlcDisableReflection=true and IlcGenerateStackTraceData=true.

Up until .NET 8 Preview 6 all was working fine, stack trace metadata was not generated.

When upgrading to .NET 8 Preview 7 or .NET 8 RC1, stack trace metadata started appearing in the resulting published binary despite the IlcGenerateStackTraceData property being true.

### Reproduction Steps

Unpack [StmBugExample.zip](https://github.com/dotnet/runtime/files/12677224/StmBugExample.zip)
Build using .NET 8 RC 1, with a commands like this:

`dotnet publish -c Release -r win-x64`

### Expected behavior

1. The "\StmBugExample\StmBugExample\bin\Release\net8.0\win-x64\publish\StmBugExample.exe" file should not contain "ExampleMethod" string.
2. Execute the "\StmBugExample\StmBugExample\bin\Release\net8.0\win-x64\publish\StmBugExample.exe" it should output something like this:

MT140695185673168: Test exception
   at StmBugExample!<BaseAddress>+0xb0ffb
   at StmBugExample!<BaseAddress>+0xb0f9e

### Actual behavior

1. The "\StmBugExample\StmBugExample\bin\Release\net8.0\win-x64\publish\StmBugExample.exe" file contains "ExampleMethod" string.
2. Execute the "\StmBugExample\StmBugExample\bin\Release\net8.0\win-x64\publish\StmBugExample.exe", it outputs:

MT140695610888528: Test exception
   at StmBugExample.ExampleClass.ExampleMethod() + 0x2b
   at Program.<Main>$(String[]) + 0x1e

### Regression?

Yes, it worked in .NET 8 Preview 6. Stopped working in .NET Preview 7.

### Configuration

- .NET 8 RC 1.
- Windows 11.
- x64
- I do not know that.

### Other information

ILC compiler seems to be ignoring IlcGenerateStackTraceData protperty starting from .NET 8 Preview 7.

**Comment by SingleAccretion** [comment]
The property was changed to `StackTraceSupport` in https://github.com/dotnet/runtime/pull/88235.

**Comment by MichalStrehovsky** [comment]
> The property was changed to `StackTraceSupport` in #88235.

I'd extend to: the uncodumented and unsupported property was changed to a [documented and supported](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-7-0#trimming-framework-library-features) one.
