### ISSUE TITLE
Add additional `ThrowIf[CONDITION]` to more exceptions

### ISSUE THREAD

**Issue by jamespfluger-ava** [dotnet/runtime#92370]
## Is your feature request related to a problem? Please describe.

Note # 1: This feature is NOT related to  a problem or a bug, but a feature request.
Note # 2: This is for .NET 6 - I have not been able to upgrade higher, but that is a separate issue. I don't know if patching backwards is standard practice for smaller issues (other than security ones)

**The main problem is I am seeking more static `.ThrowIf` conditions on Exceptions**

### A clear and concise description of what the problem is.
Example: I am trying to reduce the amount of code in my project. Currently we have a _**lot**_ of `null` checks at the beginning of each method. `ArgumentNullException.ThrowIfNull(source, nameof(source));` - [referenced here](https://github.com/dotnet/runtime/blob/b4be77b69d426f3e83777b024ee7d98e325bf593/src/libraries/System.Private.CoreLib/src/System/ArgumentNullException.cs#L54) - has been a HUUUGE benefit for us and the analyzers we use since it simplifies the checks automatically. Is it a trivial task? Partially, yes. But it'd be a big benefit for us.

I want to clarify I'm **not** proposing this be added to **every** exception, but the most commonly used ones _where it makes sense_ to add

### Describe the solution you'd like
I would like to see more `[EXCEPTION_TYPE]Exception.ThrowIf[CONDITION[(...);` to reduce the amount of code. NOT every exception should have this method, as they don't always make sense and would be extremely cumbersome.

---

### Implementation
These are what the following implementations would look like in practice:
`NullReferenceException.ThrowIfNull(object?)`  
`ArithmeticException(int?)`

#### Example \# 1
Here's an example I've added to `NullReferenceException` _(which is what I'm **primarily** interested in)_

```
/// <summary>Throws an <see cref="NullReferenceException"/> if <paramref name="argument"/> is null.</summary>
/// <param name="argument">The reference type argument to validate as non-null.</param>
/// <param name="paramName">The name of the parameter with which <paramref name="argument"/> corresponds.</param>
public static void ThrowIfNull([NotNull] object? argument, [CallerArgumentExpression(nameof(argument))] string? paramName = null)
{
    if (argument is null)
    {
        Throw(argument);
    }
}
```

#### Example \# 2
Here's another example for `UriFormatException`  
```
/// <summary>Throws an <see cref="UriFormatException"/> if <paramref name="uriName"/> is null or whitespace.</summary>
/// <param name="uriName">The name of the Uri to check if is null or whitespace.</param>
public static void ThrowIfNull([NotNull] [string|Uri]? uriName, [CallerArgumentExpression(nameof(uriName))])
{
    if (uriName is null || string.IsNullOrWhiteSpace(uriName))
    {
        Throw(uriName);
    }
}
```

### Additional context
If possible, _I would like to implement these myself_, but in order to do that, I would prefer a list of possible `System` Exceptions that this could be used for. My current thoughts are at least the following:
- **`NullReferenceException`** (when the parameter is null?  _And possibly a different method to include whitespace?_
- `UriFormatException` (when the format of a URI is null or does not confirm to RFC 2396)
- `DirectoryNotFoundException` (when the directory isn't found or the input is null)
- `FileNotFoundException` (when the file is simply just not there or the input is null)
- Other exceptions _**where it makes sense**_ - I don't have the answer for that

**Comment by tannergooding** [comment]
> Note # 2: This is for .NET 6 - I have not been able to upgrade higher, but that is a separate issue. I don't know if patching backwards is standard practice for smaller issues (other than security ones)

We cannot version in-box APIs on already shipped target frameworks. Any APIs would be available in .NET 9 or later at this point, if they were deemed appropriate to take to API review and were to receive consensus that they should be added.

-------------------

> NullReferenceException (when the parameter is null? And possibly a different method to include whitespace?

This is non-standard and isn't something we'd expose. Argument validation should throw `ArgumentNullException` and `NullReferenceException` should only occur implicitly as part of an actual null dereference.

> UriFormatException (when the format of a URI is null or does not confirm to RFC 2396)
> DirectoryNotFoundException (when the directory isn't found or the input is null)
> FileNotFoundException (when the file is simply just not there or the input is null)

The input being null should throw `ArgumentNullException`. We wouldn't expose APIs that throw these exceptions on `null`

For the two IO exceptions, this is technically a race condition to check things like `if (!File.Exists(...))`. The OS can and does run general IO operations concurrently with your program and so you can do a check and then have it no longer be correct by the time the call returns. In the case of things like network IO, you can even have arbitrary other processes run as part of accessing a file/directory.

@jaredpar generally likes to chime in on such proposals and I believe has a blog post or two covering the general topic of IO and `exists` checks and the types of pitfalls that can be encountered from them.

**Comment by jamespfluger-ava** [comment]
#### .NET 9

> We cannot version in-box APIs on already shipped target frameworks. Any APIs would be available in .NET 9 or later at this point, if they were deemed appropriate to take to API review and were to receive consensus that they should be added.

Understood

---

#### Examples

As far as the examples go, they were conditionals  or ones I think could be similar. I expected this to have few implications.
The example exceptions were conditionals I could think of that might be the same or have similar issues. Of course I don't know all the exceptions off the top of my head so I grabbed a few I remember.

My _main_ frustration is when writing extension methods and having to write
```
if (source == null)
{
    throw new NullReferenceException();
}

```
in every method. Sure a helper method works, but it becomes tedious across multiple projects and solutions when it shouldn't be exposed when it could be condensed.

---

### Questions for me to learn:
> Argument validation should throw ArgumentNullException and NullReferenceException should only occur implicitly as part of an actual null dereference.

Why is that? Is it just standard practice or is there documentation going over that? I would've thought argument null validation should take place when it is also dereferenced.

**THANK YOU!**

**Comment by tannergooding** [comment]
> Why is that? Is it just standard practice or is there documentation going over that? I would've thought argument null validation should take place when it is also dereferenced.

Standard practice because you want to be able to differentiate between "The user did something wrong, by passing in `null` to something that didn't expect it" (`ArgumentNullException`) and "The application has done something wrong and may have corrupted state, partial mutations, etc" (`NullReferenceException`).

They basically allow differentiating between manual validation vs an actual access violation.

**Comment by jamespfluger-ava** [comment]
That's fair.

Last question before I close the issue - I ran through mscorlib and only found one instance of `ThrowIf`  - on `ArgumentNullException`.

Are there plans to expand this static method to other exceptions?

**Comment by tannergooding** [comment]
We have several `ThrowIf` methods:
* `ArgumentException.ThrowIfNullOrEmpty`
* `ArgumentException.ThrowIfNullOrWhitespace`
* `ArgumentNullException.ThrowIfNull`
* `ArgumentOutOfRangeException.ThrowIfEqual`
* `ArgumentOutOfRangeException.ThrowIfGreaterThan`
* `ArgumentOutOfRangeException.ThrowIfGreaterThanOrEqual`
* `ArgumentOutOfRangeException.ThrowIfLessThan`
* `ArgumentOutOfRangeException.ThrowIfLessThanOrEqual`
* `ArgumentOutOfRangeException.ThrowIfNegative`
* `ArgumentOutOfRangeException.ThrowIfNegativeOrZero`
* `ArgumentOutOfRangeException.ThrowIfNotEqual`
* `ArgumentOutOfRangeException.ThrowIfZero`
* `ObjectDisposedException.ThrowIf`
* etc

These may be expanded based on needs and common practice.

**Comment by jamespfluger-ava** [comment]
Hmmm, I guess my code either my Assembly scan didn't cover those, or if they're internal, or they're above .NET 6

Regardless, I'll close it since it won't be implemented.

**Comment by tannergooding** [comment]
They're new in .NET 7 and/or .NET 8 (which is the next LTS and has a "go live" license as of RC1)

We add tons of new APIs every release and so every release is better than the last and worth checking out!
