### ISSUE TITLE
[browser] setModuleImports() can only be used once?

### ISSUE THREAD

**Issue by Elringus** [dotnet/runtime#92386]
I'm attempting to late-bind JS functions (`JSImport`), but it looks like consequent calls to `setModuleImports` are not updating the bindings. Is that by design? In .NET 6 I was able to bind function at any point, which was quite handy, eg for unit-testing, where I've been assigning mocks to functions once per test w/o the need to re-initialize the runtime.

**Comment by radical** [comment]
cc @pavelsavara @maraf

**Comment by maraf** [comment]
Yes, `JSImport` binds javascript function just once. It was implemented that way in 7 and remained the same in 8. 
You can easily wrap the function you want to replace in another function and bind this wrapper.

```js
let functionToCall = () => console.log(1);

function wrapper() {
  functionToCall();
}

const { setModuleImports } = await dotnet.create();

setModuleImports("main.js", {
    Sample: {
        Test: {
            func: wrapper
        }
    }
});

// Run test case in .NET

functionToCall = console.log(2);

// Run second test case in .NET
```

**Comment by pavelsavara** [comment]
I thought that the problem is calling it multiple times with different functions, but always before first C# call.
We are not going to re-bind it.

**Comment by Elringus** [comment]
The workaround with wrappers worked, thank you!

Here is how I've solved it in case someone will find this looking for similar stuff:

```js
export const Imports = {
    Foo: {
        //  the wrapper is stored in `_fun` to prevent allocations on each function access.
        get fun() { return this._fun; },
        set fun($fun) { this._fun = () => this.$fun(); this.$fun = $fun; }
    }
};

setModuleImports("main.js", Imports);

// Imports can now be bind at any point
Imports.Foo.fun = () => {};

// Original function can be accesed like this (eg, for reading mock info)
Imports.Foo.fun = mock.fn();
Imports.Foo.$fun.mock.calls;
```
