### ISSUE TITLE
System.Text.Json: `JsonIgnoreCondition.WhenWritingNull` is not working

### ISSUE THREAD

**Issue by rcdailey** [dotnet/runtime#92383]
### Description

When serializing types that have properties set to `null`, those properties still get serialized out with `null` values instead of being omitted.

### Reproduction Steps

I don't have steps and I struggled to reproduce this in a simple MCVE, so I'm just going to link to my open source project. I created a branch named `json-serializing-nullable-fields-issue` that demonstrates the issue. You can look at the diff to see the new unit test I introduced that you can run to repro the issue.

See the test named `DemoNullableNotWorking()` (below):

```cs
[Test]
public void DemoNullableNotWorking()
{
    var fs = new MockFileSystem();

    var jsonFile = fs.CurrentDirectory().File("testdata.json");
    fs.AddSameFileFromEmbeddedResource(jsonFile, typeof(QualityProfileConfigPhaseTest));
    jsonFile.Refresh();

    using var data = jsonFile.OpenRead();

    var unboxed = JsonSerializer.Deserialize<QualityProfileDto>(data, GlobalJsonSerializerSettings.Services);
    var boxed = JsonSerializer.Serialize(unboxed, GlobalJsonSerializerSettings.Services);
}
```

If you inspect `boxed` in your debugger, you'll see the entire serialized JSON string. Look at the `"items"` array for an element like this:

```json
    {
      "id": null,
      "name": null,
      "allowed": true,
      "quality": {
        "id": 7,
        "name": "Bluray-1080p",
        "source": "bluray",
        "resolution": 1080
      },
      "items": []
    },
```

Link to my repo and the relevant test file is below:

https://github.com/recyclarr/recyclarr/blob/json-serializing-nullable-fields-issue/src/tests/Recyclarr.Cli.Tests/Pipelines/QualityProfile/PipelinePhases/QualityProfileConfigPhaseTest.cs#L274

### Expected behavior

Properties `"id"` and `"name"` should not be serialized because they are `null`.

### Actual behavior

Null values are serialized when they shouldn't be.

### Configuration

.NET 7

**Comment by pinkfloydx33** [comment]
Unless I'm missing something, I think [your modifiers](https://github.com/recyclarr/recyclarr/blob/394bf6de7858da8c5ed00babd516b5d24f051c43/src/Recyclarr.Json/GlobalJsonSerializerSettings.cs#L23) are causing the properties to [be serialized](https://github.com/recyclarr/recyclarr/blob/394bf6de7858da8c5ed00babd516b5d24f051c43/src/Recyclarr.Json/JsonSerializationModifiers.cs#L38).

They [don't have the attribute](https://github.com/recyclarr/recyclarr/blob/0afe1ee0059eb7aa51aa4fe6e4df590794f6f2cc/src/Recyclarr.Cli/Pipelines/QualityProfile/Api/QualityProfileDto.cs#L27), so `HasAttribute` would return `false` and you say to serialize iif it's `false`

**Comment by rcdailey** [comment]
Ok that's interesting. I thought the `ShouldSerialize` property supplemented the existing conditions like whether or not a property is null. So I am overriding that setting? How do I make `ShouldSerialize` only kick in after the other logic has been checked? I do not want to overwrite previous logic.

**Comment by pinkfloydx33** [comment]
I might be wrong. I'm not sure of the exact rules... Just an observer and that's what popped out at me

**Comment by rcdailey** [comment]
For now, I modified my logic to this and I think it works:

```cs
public static class JsonSerializationModifiers
{
    public static void IgnoreNoSerializeAttribute(JsonTypeInfo type)
    {
        var propertiesToRemove = type.Properties
            .Where(x => x.AttributeProvider?.IsDefined(typeof(JsonNoSerializeAttribute), false) ?? false)
            .ToList();

        foreach (var prop in propertiesToRemove)
        {
            prop.ShouldSerialize = (_, _) => false;
        }
    }
}
```

It's still really confusing, though. Maybe one of the devs can drop in to clarify the behavior and how this should be done.
