### ISSUE TITLE
CborWriter should use doubling for buffer growth

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#92425]
Currently, `CborWriter` increases its buffer 1024 bytes at a time:

https://github.com/dotnet/runtime/blob/51498964d35068ded252ec98baf4fe6ebf6a4612/src/libraries/System.Formats.Cbor/src/System/Formats/Cbor/Writer/CborWriter.cs#L210-L212

For large CBOR documents, this can be result in a lot of array resizing. We should instead change the strategy to do doubling.

**Comment by eiriktsarpalis** [comment]
To add context, this was determined to be the root cause for the perf issue as reported in https://github.com/dotnet/runtime/issues/91969.
