### ISSUE TITLE
runtime-nativeaot-outerloop started to run by default on PR's

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#92432]
`runtime-nativeaot-outerloop` seems to be running by default on PR's. My PR (https://github.com/dotnet/runtime/pull/90436) which only changes Mono codebase triggered `runtime-nativeaot-outerloop` pipeline, which was redundant.

**Comment by fanyang-mono** [comment]
This may have already been resolved by https://github.com/dotnet/runtime/pull/92389

**Comment by radical** [comment]
> This may have already been resolved by #92389

Nope, it is still running by default.

**Comment by jkoritzinsky** [comment]
I worked with First Responders to fix this offline. I've validated that it's fixed now.
