### ISSUE TITLE
System.Private.Corelib R2R PDB is not included in runtime pack

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#92456]
Profilers can't get information about R2R methods without this.

**Comment by mangod9** [comment]
@hoyosjs is this a regression or always been this way? Adding @trylek @davidwrighton

**Comment by hoyosjs** [comment]
It's a regression in packaging. The PDB itself is still getting produced.

**Comment by mangod9** [comment]
Ok adding @ivdiazsa as well. Perhaps he can investigate a fix.

**Comment by ivdiazsa** [comment]
Hmmm... I find this regression interesting. By packaging are we referring to the `packs` subset?

**Comment by ivdiazsa** [comment]
Upon further investigation, we found out the issue was fixed at some point in time because the missing `System.Private.CoreLib.ni.pdb` is actually there in the current builds, so closing this issue now.
