### ISSUE TITLE
[Mono]: Crash in interpreter delegate wrapper when calling AOT:ed virtual delegate target method in mixed mode.

### ISSUE THREAD

**Issue by lateralusX** [dotnet/runtime#92466]
### Description

In .net8 we did some changes to how we generate delegate wrapper, https://github.com/dotnet/runtime/pull/83461. Turns out that  the change around calling a virtual target method through delegate wrapper using `CALLI` doesn't work in mixed mode (full AOT + interpreter):

https://github.com/dotnet/runtime/blob/main/src/mono/mono/metadata/marshal-lightweight.c#L2106

Running a test like `System.Buffers` in full AOT with interpreter fallback will hit a scenario where the delegate wrapper ends up being executed by interpreter since we didn't have needed `gsharedvt` version available in the AOT image. That means we will now do an icall to `mono_get_addr_compiled_method` get the native function pointer to the target method, and since that exists in AOT image, it will be returned and `CALLI` instruction will then get that native function pointer as argument. Problem is that `CALLI` instruction implementation on interpreter assumes the argument to be an `imethod` (or a struct in llvm only case):

https://github.com/dotnet/runtime/blob/main/src/mono/mono/mini/interp/interp.c#L4108

leading up to a crash when trying to use the `imethod`, that is a native function pointer.

The underlying issue could be fixed by implement a new op code for this scenario calling a virtual target method from a delegate wrapper and then implement different lowering of that op code on jit/aot and interpreter.

A different way to mitigate the issue is making sure we include the missing `gsharedvt` delegate wrappers in the AOT image, making sure we don't end up in the interpreter executing the wrapper. One benefit of this approach is that we won't get into interpreter, since once that happens we will also stick around in interpreter running the target delegate method.

A final fix would probably use both above strategies to both optimize the AOT scenario as well as making sure we won't hit similar issues in the future, if we end up executing other versions of delegate wrappers in the interpreter when running in mixed mode.

### Reproduction Steps

Run `System.Buffers` library test using full AOT + interpreter should repro the issue. Alternative the following small sample should hit similar delegate wrapper issue running under full AOT + interpreter.

```
using System;

public class Tests
{
    public struct FooStruct { }

    public virtual FooStruct AStruct { get; set; }

    public static int Main ()
    {
        var t = new Tests ();
        Console.WriteLine ("A: " + typeof (Tests).GetProperty ("AStruct").GetValue (t));
	return 0;
    }
}
```

### Expected behavior

No crash, even if the delegate wrappers are not part of the AOT image.

### Actual behavior

Crash if the delegate wrapper is not part of the AOT image (but target method is) and delegate wrapper is executed by interpreter.

**Comment by SamMonoRT** [comment]
@lateralusX - is this happening on .NET RC builds or just in main? (Trying to determine if we need to backport the fix).

**Comment by vargaz** [comment]
The referenced PR will work around the issue.

**Comment by lateralusX** [comment]
> @lateralusX - is this happening on .NET RC builds or just in main? (Trying to determine if we need to backport the fix).

I hit this using .net8 RC1 (bumping downstream repros from .net7 to .net8 and hit a bunch of issues).

**Comment by BrzVlad** [comment]
This seems to have been fixed. At this point I'm not whether running the delegate wrapper with interpreter, if the target method is aot, is relevant. Ideally we would still run the compiled wrapper.
