### ISSUE TITLE
IFloatingPoint missing ReadSignificandLittleEndian and other readers

### ISSUE THREAD

**Issue by alex4998** [dotnet/runtime#92485]
I don't understand how that is possible and cannot believe that it is true. There are methods for writing the value as byte array like WriteSignificandLittleEndian but there is no method for reading it like ReadSignificandLittleEndian. So, what's good in writing then. Maybe it is hidden somewhere too deep but all my tries to find it failed. Can somebody confirm that they are missing or tell me how to read what was written with methods like WriteSignificandLittleEndian?

**Comment by jeffhandley** [comment]
@alex4998 You are correct that there aren't methods for directly reading the significand. [System.Buffers.Binary.BinaryPrimitives](https://learn.microsoft.com/dotnet/api/system.buffers.binary.binaryprimitives?view=net-8.0) offers [`ReadSingleLittleEndian`](https://learn.microsoft.com/dotnet/api/system.buffers.binary.binaryprimitives.readsinglelittleendian?view=net-8.0) though, where the floating point can be read as little endian.

Can you elaborate on your scenario for needing to read only the significand please?

**Comment by tannergooding** [comment]
It's worth noting the consideration here is that the significand and exponent are not `IFloatingPoint` but rather a form of `IBinaryInteger` and so should be read and manipulated using an integer type.

You can then convert those two parts to some `IFloatingPoint` value using `ConvertTruncating` and then reconstruct the full value using something like `ScaleB`

**Comment by alex4998** [comment]
I guess this is what I was looking for. It was too long ago to remember all the details. That code was written differently with the derived classes implementing abstract base class methods dealing with the writing and reading byte buffers. Thank you, anyway, I guess we can consider refactoring and simplification.
