### ISSUE TITLE
 Algorithm 'AesGcm' is not supported on this platform but platform is supported

### ISSUE THREAD

**Issue by quintushr** [dotnet/runtime#92482]
### Description

When I use the constructor of the AesGcm class on macOS Monterey, an exception is thrown with the message 'Algorithm 'AesGcm' is not supported on this platform.' I checked the documentation, and it only mentions that  [browser, iOS, and tvOS are not supported](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.aesgcm?view=net-6.0).

### Reproduction Steps

Run this code on Macos : 

```csharp
public static void Main()
{
  var aesGcm = new AesGcm(key);
}
```

### Expected behavior

no exception

### Actual behavior

Exception : 
 `PlatformNotSupportedException: Algorithm 'AesGcm' is not supported on this platform.`

**Comment by vcsjones** [comment]
In .NET 7, `AesGcm` has a dependency on OpenSSL being installed and configured on macOS. It needs to be installed, and the libraries need to be in a path that macOS will load libraries from. See https://github.com/dotnet/runtime/issues/89006#issuecomment-1638818976 for an example.

Starting in .NET 8, `AesGcm` has removed the dependency on OpenSSL and relies on CryptoKit, so it should "just work" out of the box.

**Comment by karakasa** [comment]
I suppose it should be better documented

**Comment by vcsjones** [comment]
> and throw a more detailed Exception?

Well, the exception is gone in .NET 8, and changing the exception for .NET 6 or 7 probably won't meet the servicing bar. For other OpenSsl backed primitives, the exception was already improved for .NET 8 with #89046.

**Comment by vcsjones** [comment]
I think we can close this issue out. To summarize:

- `AesGcm` on macOS requires installing and configuring OpenSSL in .NET 7 or below.
- In .NET 8, `AesGcm` uses CryptoKit, so the exception will no longer occur.
- The remaining types that continue to use OpenSSL on macOS have their exception text improved in .NET 8.

Please feel free to re-open this issue if there are issues you believe are unaddressed.
