### ISSUE TITLE
[macOS] NativeAOT unable to produce executables when using the Xcode 15 toolchain

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#92491]
When the new linker from Xcode 15 is used on object files produced by NativeAOT, the Xcode linker produces artifacts that crash during the first stack walk.

As a workaround it is possible to install Xcode 14.3.1 in parallel and set it as the default toolchain using `xcode-select`.

This affects arm64 and x64 Macs when using the `-p:PublishAot=true` option with .NET 8

It also affects the experimental ios NativeAOT support.

There is already a PR to fix the the underlying issue here: 
* https://github.com/dotnet/llvm-project/pull/471 (for net9)
* https://github.com/dotnet/llvm-project/pull/472 (for net8.0-rc2 or net8.0-rtm)

I'm opening this issue mostly for tracking purposes

**Comment by lambdageek** [comment]
Do we need to fix net7, too?

**Comment by filipnavara** [comment]
macOS and iOS was not supported for NativeAOT on . NET 7, so no

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by filipnavara** [comment]
Another Xcode 15 breakage was reported in https://github.com/dotnet/runtime/issues/92297. Preliminary analysis suggests that we hit the same bug with non-`MH_SUBSECTIONS_VIA_SYMBOLS` object files getting the unwind tables corrupted. In this case, however, it's for the assembly code in both CoreCLR and NativeAOT runtime. For NativeAOT we are much less likely to observe this as a problem but it's easily observable on CoreCLR.

A possible fix is to update the assembly code to use `MH_SUBSECTIONS_VIA_SYMBOLS` and thus avoid hitting the linker bug. I have done an experiment with that (https://github.com/filipnavara/runtime/commit/aba0b02bb5312904d694bd077f1b853538fa7b8b) and now I am waiting for a feedback.

Crucially, I didn't audit Mono code or other components that may run into the same issue.

**Comment by lambdageek** [comment]
> Crucially, I didn't audit Mono code or other components that may run into the same issue.

What would we need to audit:
* handwritten asm files comprising libmonosgen or other platform libraries;
* the aot object files that are linked using the platform toolchain linker when targeting apple platforms
anything else?

And I suppose @dalexsoto the macios team should likewise look at their code?

@steveisok do we have any xcode15 testing lanes?

**Comment by filipnavara** [comment]
> handwritten asm files comprising libmonosgen or other platform libraries;

If you emit DWARF or compact unwinding there, yes. I am not sure if, and to what extent, MonoVM does that.

> anything else?

The assembly files and AOT output are the only two things that come to mind. C/C++/ObjC always produces object files with the subsections-via-symbols flag.

> And I suppose @dalexsoto the macios team should likewise look at their code?

They should...but in their case it's slightly less urgent. On the Xcode 15 branch they currently detect the Xcode version and force the old linker to be used by `-ld_classic` linker flag. There's an open issue to evaluate whether it is still needed (it is), and to remove it. 

Forcing the old linker is an option, but it's logistically challenging since you need to also detect Xcode tools version. Apple already stated that they will eventually remove the old linker, so this strategy only buys some time.

**Comment by steveisok** [comment]
> @steveisok do we have any xcode15 testing lanes?
> 
> 

We have a scouting queue with an older beta on it.  We could probably update it quickly ourselves if need be.

**Comment by lambdageek** [comment]
> > handwritten asm files comprising libmonosgen or other platform libraries;
> 
> If you emit DWARF or compact unwinding there, yes. I am not sure if, and to what extent, MonoVM does that.
> 
> > anything else?
> 
> The assembly files and AOT output are the only two things that come to mind. C/C++/ObjC always produces object files with the subsections-via-symbols flag.
> 
> > And I suppose @dalexsoto the macios team should likewise look at their code?
> 
> They should...but in their case it's slightly less urgent. On the Xcode 15 branch they currently detect the Xcode version and force the old linker to be used by `-ld_classic` linker flag. There's an open issue to evaluate whether it is still needed (it is), and to remove it.
> 
> Forcing the old linker is an option, but it's logistically challenging since you need to also detect Xcode tools version. Apple already stated that they will eventually remove the old linker, so this strategy only buys some time.


Seems like Mono is ok:

1. We've been using `.subsections_via_symbols` since https://github.com/mono/mono/commit/c60098a18a2724fa8ded55a32fa8e7f9be2ea26d
2. I tried net8.0 RC1 with Xcode 15 and the following:
   ```console
   $ dotnet new console
   # add SelfContained and UseMonoRuntime options to the .csproj
   $ cd bin/Release/net8.0/osx-arm64/publish
   $ MONO_PATH=`pwd` MONO_ENV_OPTIONS='--aot=full,dwarfdebug,soft-debug' ./hw *.dll
   ...
   $ MONO_PATH=`pwd` MONO_ENV_OPTIONS='--full-aot' ./hw *.dll
   ...
   ```
   and the app ran without crashing

The app:

```csharp
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;

public class C {
        public static void Main()
        {
                Helper(20, 10);
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        public static void Helper (int throwOnFrame, int catchOnFrame)
        {
                if (throwOnFrame == 0)
                        throw new Exception("Throwing");
                if (catchOnFrame == 0)
                {
                        try {
                                Helper (throwOnFrame - 1, -1);
                        } catch (Exception e) {
                                Console.WriteLine ($"Caught {e}");
                                var st = new StackTrace (e);
                                var frames = st.GetFrames();
                                int frameNum = 0;
                                foreach (var frame in frames) {
                                        Console.WriteLine ($"frame {frameNum++}: {frame}");
                                }
                        }
                        return;
                }
                Helper (throwOnFrame - 1, catchOnFrame - 1);
        }
}
```

**Comment by MichalStrehovsky** [comment]
I assume this is all resolved and we won't ship something that wouldn't work with xcode 15.
