### ISSUE TITLE
Clean up dependencies on 8.0 packages.

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#92502]
Having a look through https://github.com/dotnet/runtime/blob/main/eng/Versions.props we still depend on a few 8.0 packages. 

Summarizing the ones I see and tagging the folks who might need to take action.  Feel free to update this as needed.
- [x] Arcade @mmitche do we have a new build of arcade for 9.0 that we can start picking up? https://github.com/dotnet/runtime/blob/e51acb55cd57eecaefac5f3008ca91c6364b4223/eng/Versions.props#L84-L100 
- [x] ILAsm looks like a bad merge here has frozen our version for some time.  Fixing in https://github.com/dotnet/runtime/pull/92500 
https://github.com/dotnet/runtime/blob/e51acb55cd57eecaefac5f3008ca91c6364b4223/eng/Versions.props#L107-L108 
- [x] Runtime-assets - @carlossanlop can you help update our subscription and make sure we have a 9.0 build of runtime-assets. https://github.com/dotnet/runtime/blob/e51acb55cd57eecaefac5f3008ca91c6364b4223/eng/Versions.props#L141-L155  
- [x] XHarness   Looks like this is still branded as 8.0 - https://github.com/dotnet/runtime/blob/e51acb55cd57eecaefac5f3008ca91c6364b4223/eng/Versions.props#L182-L185
- [ ] Intellisense @carlossanlop we should retarget this to 9.0 when we're ready - https://github.com/dotnet/runtime/blob/e51acb55cd57eecaefac5f3008ca91c6364b4223/eng/Versions.props#L208
- [x] MSQuic @karelz can you help find someone to help here https://github.com/dotnet/runtime/blob/e51acb55cd57eecaefac5f3008ca91c6364b4223/eng/Versions.props#L219 
- [x] 8.0 version @ViktorHofer can you help with this, once we have a final build of 8.0? https://github.com/dotnet/runtime/blob/e51acb55cd57eecaefac5f3008ca91c6364b4223/eng/Versions.props#L10

**Comment by ViktorHofer** [comment]
> 8.0 version @ViktorHofer can you help with this, once we have a final build of 8.0? https://github.com/dotnet/runtime/blob/e51acb55cd57eecaefac5f3008ca91c6364b4223/eng/Versions.props#L10C6-L10C24

@steveisok usually takes care of updating these

**Comment by akoeplinger** [comment]
Only the Intellisense package is left here, @carlossanlop for my own understanding: where is this package produced?

**Comment by ViktorHofer** [comment]
Exactly. We usually keep using the previous major versioned package until we produce a new one. I think that's fine.

**Comment by akoeplinger** [comment]
Could we generate one for .NET 9 so we could remove our dotnet8/dotnet8-transport feed dependencies?

**Comment by ViktorHofer** [comment]
> Could we generate one for .NET 9 so we could remove our dotnet8/dotnet8-transport feed dependencies?

We manually push that package to the corresponding feed. In this case, we can just download the latest available package and push it into the dotnet9-transport feed.

**Comment by akoeplinger** [comment]
Ok can you do that? I don't have permission.

**Comment by ViktorHofer** [comment]
We need to ask someone from core-eng to do that for us. We don't have permissions anymore.

**Comment by ViktorHofer** [comment]
I think this issue should now be closed. dotnet8 feeds were removed with https://github.com/dotnet/runtime/pull/95860. We don't plan to update to a new Intellisense package until later in the release.

**Comment by akoeplinger** [comment]
Yep, I filed https://github.com/dotnet/runtime/issues/96084 to track the intellisense package upgrade
