### ISSUE TITLE
[tvos] System.Runtime.Loader.Test.AssemblyNotSupported could not be loaded

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#92522]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=415540&view=logs&j=acac6bf3-3edd-5022-4e45-3362a02520b1&t=311ccc8e-0304-52d0-3115-8f8cb0052fd2
Build error leg or test failing: tvOS Library tests
Pull request: https://github.com/dotnet/runtime/pull/89895

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "The project file could not be loaded. Could not find a part of the path '/Users/runner/work/1/s/src/libraries/System.Runtime.Loader/tests/System.Runtime.Loader.Test.AssemblyNotSupported/System.Runtime.Loader.Test.AssemblyNotSupported.csproj",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

/cc: @teo-tsirpanis

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=415540
**Error message validated:** `The project file could not be loaded. Could not find a part of the path '/Users/runner/work/1/s/src/libraries/System.Runtime.Loader/tests/System.Runtime.Loader.Test.AssemblyNotSupported/System.Runtime.Loader.Test.AssemblyNotSupported.csproj`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 9/23/2023 11:19:26 AM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[416794](https://dev.azure.com/dnceng-public/public/_build/results?buildId=416794)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/416794/logs/41)|dotnet/runtime#92523|
|[416766](https://dev.azure.com/dnceng-public/public/_build/results?buildId=416766)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/416766/logs/205)|dotnet/runtime#92057|
|[416738](https://dev.azure.com/dnceng-public/public/_build/results?buildId=416738)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/416738/logs/178)||
|[416292](https://dev.azure.com/dnceng-public/public/_build/results?buildId=416292)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/416292/logs/383)||
|[415899](https://dev.azure.com/dnceng-public/public/_build/results?buildId=415899)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/415899/logs/37)|dotnet/runtime#92471|
|[415534](https://dev.azure.com/dnceng-public/public/_build/results?buildId=415534)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/415534/logs/1263)||
|[415540](https://dev.azure.com/dnceng-public/public/_build/results?buildId=415540)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/415540/logs/211)|dotnet/runtime#92057|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|4|7|7|

**Comment by teo-tsirpanis** [comment]
Working on it.

**Comment by teo-tsirpanis** [comment]
Working on it.
