### ISSUE TITLE
Array of multidimensional arrays has wrong name

### ISSUE THREAD

**Issue by jburzynski** [dotnet/runtime#92535]
### Description

It seems like the `System.Type.Name` property displays array brackets in reverse order when single-dimensional and multidimensional arrays are mixed together. For example, the value of `typeof(int[][,]).Name` is `"Int32[,][]"` and should be `"Int32[][,]"`. 

This happens for longer configurations as well. For example, the value of `typeof(int[][,][,,,][,,]).Name` is currently `"Int32[,,][,,,][,][]"`.

### Reproduction Steps

Read the value of `typeof(int[][,]).Name`.

### Expected behavior

Should be `"Int32[][,]"`.

### Actual behavior

Currently is `"Int32[,][]"`.

### Configuration

.NET 7
C# 11
Console Application
Windows 11 Pro x64

**Comment by karakasa** [comment]
`int[][,]` is indeed `(int[,])[]`. I would say it's more or less a discrepancy between C# grammar and type name system.

The typename is deduced here:

https://github.com/dotnet/runtime/blob/bbe5c66c50201816c14149fd3f259db86bc1f493/src/coreclr/vm/typestring.cpp#L750-L751

**Comment by jkotas** [comment]
> C# grammar and type name system

Correct. This name returned by this API follows a grammar similar to the grammar for fully qualified names https://learn.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/specifying-fully-qualified-type-names#grammar-for-type-names

There are number of other more substantial discrepancies between C# names and the names returned by this API. For example, this API returns `Int32&` for what is `ref int` in C#.

Perhaps we just need to highlight this detail in the documentation. Changing the grammar and rules for interpreting fully qualified names would be a major breaking change.

**Comment by jburzynski** [comment]
Thanks, I understand that this is the notation of the type system (which is different from C# notation) and cannot be changed due to backward compatibility.

I'm wondering though what was originally the reason for this notation (most specific array qualifier first).
Most languages (e.g. C#, C++, C (to some extent), VB.NET) use the opposite notation - most specific array qualifier last. Unless for example you add round brackets, like `(int[,])[]`, as mentioned before (but the type name does not specify any round brackets).

`Int32&` representing `ref int` is a bit different, because it just uses `&` to represent a reference instead of `ref`. But the array brackets notation uses a popular, existing notation and changes the details - it's kind of like writing the number 123 as 321.

**Comment by MichalStrehovsky** [comment]
https://ericlippert.com/2009/08/17/arrays-of-arrays/ discusses the C# language choice in details. Reflection constructs types by appending the qualifier so this makes arrays consistent with `&`/`*`.

I'd say the reflection notation choice makes more sense when looked at in isolation (when not thinking about how these get initialized in code, etc. - the considerations that drove C# choice here, and are of little concern for reflection), because adding "from the middle" feels a bit weird.

**Comment by jburzynski** [comment]
Ok, thanks, it makes sense why this notation was used.

As @jkotas mentioned, I agree that it might be helpful to add information about this discrepancy (and maybe others) between C# syntax and type names to the documentation.

On the one hand arrays like this are rarely used in actual code, so this "issue" would probably mostly come up when somebody writes a library or a piece of code that has to handle all code constructs. But since people typically don't study the type name system separately, it might be confusing if the type name does not match what they are used to seeing in code (like e.g. in my case).
