### ISSUE TITLE
Standalone GC, GC_IsCompatibleWithRuntime(), building a standalone GC for multiple runtime versions

### ISSUE THREAD

**Issue by lap1nou** [dotnet/runtime#92536]
Hello,

I'm trying to load a custom GC as explained in [#91857](https://github.com/dotnet/runtime/issues/91857). The loading works fine on the .NET runtime 7 and 9 took directly from GitHub, however when I want to use the GC DLL on an older .NET runtime version (`v4.0.30319`), it tries to `GetProcAddress` a function called `GC_IsCompatibleWithRuntime()` which I never heard of and isn't described in the Wiki: https://github.com/dotnet/runtime/blob/main/docs/design/features/standalone-gc-loading.md, here is the call captured from API Monitor:

![image](https://github.com/dotnet/runtime/assets/10383569/63667257-a81b-4fc6-86fa-574488e07969)

If I try to implement this function by adding this snippet in `gcloader.cpp`:
```cpp
GC_EXPORT
bool LOCALGC_CALLCONV
GC_IsCompatibleWithRuntime()
{
    return true;
}
```

The `GetProcAddress` seems to run fine:
![image](https://github.com/dotnet/runtime/assets/10383569/c9365a85-0348-48bd-a20f-ea34423537b0)

But then I got this error while starting `powershell.exe` for example:
```
Starting the CLR failed with HRESULT 80004005.
```

I understand that my Standalone GC (which is just the default GC of .NET 7/9) is probably not compatible with the older runtime, but how can I know which method to add / remove depending on the runtime version ? How can I create multiple GC compatible with different versions of the runtime ?

Also I don't have logging enabled since the runtime is the one installed for my system, how can I build an older runtime for debugging purpose ? On Github there is only runtime v.5 and higher, but not v4, v2, ...

**Comment by jkotas** [comment]
> v4.0.30319

This version is .NET Framework . .NET Framework is closed source and the standalone GC build from open source dotnet/runtime repo is not compatible with it. The GC contract in .NET Framework is not documented.

**Comment by mangod9** [comment]
Jan is correct, the standalone GC is not supported with .NET Framework, its supported with .NET 5/6 onwards. Do you have a specific scenario where standalone GC would help in legacy framework?

**Comment by lap1nou** [comment]
Hello,

Thank you a lot for your answers @jkotas and @mangod9.

I didn't knew that difference between legacy .NET and the actual runtime that is open source and cross-platform, and I have to admit it, I was confused at first.

> The GC contract in .NET Framework is not documented.

But the concept of the standalone GC would work the same for the legacy .NET right ? Or legacy .NET doesn't support a standalone GC at all ?

> Do you have a specific scenario where standalone GC would help in legacy framework?

Well, not really, however I have the feeling that the whole standalone GC idea is basically useless if a lot of the installation of Windows can't take benefit of it. Most Windows users probably run the legacy .NET version.

I understand that the GC contract is closed source for .NET legacy, however is there a version correspondance between .NET legacy and .NET open-source ? In that case a developper could take the "closest" version resemblance and implement the contract, even if some function could just be dummy function.

**Comment by jkotas** [comment]
The standalone GC is not generally supported for .NET Framework. We do not plan to change that.

As you have observed, some of the standalone GC env variables are recognized by .NET Framework. It is meant to be used only for internal testing purposes in .NET Framework.

> I have the feeling that the whole standalone GC idea is basically useless

It may not work for what you wanted to do with it, but that does not make it useless.
