### ISSUE TITLE
Add IsUnreferencedCodeAvailable feature switch

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#92541]
This is meant to be the dual to `RequiresUnreferencedCode`. This is a bit of a retcon of how `RequiredUnreferencedCode` is defined.

Effectively, all `Requires` attributes would now refer to generic "platform requirements" which may or may not be available in any given configuration. `UnreferencedCode` would be a requirement that is provided by-default in untrimmed apps, and trimming would not provide such a requirement.

IsUnreferencedCodeAvailable would be a switch to indicate whether that platform requirement is available in the current app configuration. It could be used by apps to check if a requirement is available before calling a method with such a requirement.

**Comment by teo-tsirpanis** [comment]
How about we also add a `RuntimeHelpers.IsUnreferencedCodeAvailable` property?

**Comment by MichalPetryka** [comment]
> How about we also add a `RuntimeHelpers.IsUnreferencedCodeAvailable` property?

I think it'd rather be in `RuntimeFeatures`.

**Comment by teo-tsirpanis** [comment]
Oh yeah, that was the class these things are in. 🤦🏻‍♂️

**Comment by agocke** [comment]
Yeah, I think we can close this. I think we have alternative paths we can go down instead.
