### ISSUE TITLE
Is the `_TEST` section a typo?

### ISSUE THREAD

**Issue by filipnavara** [dotnet/runtime#92553]
https://github.com/dotnet/runtime/blob/bbe5c66c50201816c14149fd3f259db86bc1f493/src/coreclr/vm/amd64/jithelpers_fast.S#L523-L531

Is this really supposed to be a `_TEST` section or should it be `_TEXT`? cc @jakobbotsch

**Comment by filipnavara** [comment]
In ARM64 it's the `_TEXT` section so I am going to assume it's a typo.

**Comment by jakobbotsch** [comment]
Yes, that looks like a typo.
