### ISSUE TITLE
[API Proposal]: ref T MemoryMarshal.ReadRef<T>(ReadOnlySpan<byte>) API

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#92559]
### Background and motivation

There are scenarios where it's useful to get a view as a given type over some memory location (especially in interop scenarios). It's common to expose views on these memory locations as `ReadOnlySpan<byte>`, so the API boundary is safe. When you then need to reinterpret those views though, there's currently no way of doing that that isn't either clunky or not safe. Consider:

```csharp
void UseData(ReadOnlySpan<byte> span)
{
    ref Data data = ...; // < --- this is the issue

    // Use the data
}

struct Data
{
    public int A;
    // etc. (assume this type is quite fat)
}
```

Currently, to make this safe, you need to manually check the size and then do `Unsafe.As<byte, Data>(ref MemoryMarshal.GetReference(span))`. The proposal is to introduce a new "companion" overload for `MemoryMarshal.Read` that does exactly the same (converts `byte` to `T` and also automatically validates the size of the span), but returning a `ref`.

### API Proposal

```csharp
namespace System.Runtime.InteropServices;

public static class MemoryMarshal
{
    public static ref T ReadRef<T>(ReadOnlySpan<byte> data)
        where T : struct;
}
```

### API Usage

```csharp
void UseData(ReadOnlySpan<byte> span)
{
    ref Data data = ref MemoryMarshal.ReadRef<Data>(span);

    // Use the data
}
```

For instance, this would be used in [ComputeSharp](https://github.com/Sergio0694/ComputeSharp) to map a view on the native constant buffer for D2D1 pixel shaders into the source generated native layout type mapping that memory view, so its fields can then be copied from to the managed object.

### Example implementation

```csharp
public static ref T ReadRef<T>(ReadOnlySpan<byte> data)
    where T : struct
{
    if (RuntimeHelpers.IsReferenceOrContainsReferences<T>())
    {
        ThrowHelper.ThrowInvalidTypeWithPointersNotSupported(typeof(T));
    }

    if (sizeof(T) > source.Length)
    {
        ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.length);
    }

    return ref Unsafe.As<byte, T>(ref GetReference(source));
}
```

### Alternative options

@EgorBo suggested this other equivalent shape instead:

```csharp
namespace System.Runtime.InteropServices;

public static class MemoryMarshal
{
    public static ref TTo GetReferenceAs<TFrom, TTo>(ReadOnlySpan<TFrom> data)
        where TFrom : struct
        where TTo : struct;
}
```

**Comment by EgorBo** [comment]
While technically it can be done via `ref Unsafe.As<T, byte>(ref MemoryMarshal.GetReference(span))` I like this proposal because it makes this `Unsafe.As ref refref` hell a bit less verbose:

![image](https://github.com/dotnet/runtime/assets/523221/d1690348-364c-4615-bf79-7a5867669b8f)

**Comment by Sergio0694** [comment]
Nevermind, it already exists — missed it because it's not available in the OOB `System.Memory` package 🤣
Thanks @DaZombieKiller for bringing this up!

https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.memorymarshal.asref
