### ISSUE TITLE
Casting very large number as int results in a negative number

### ISSUE THREAD

**Issue by Panache1** [dotnet/runtime#92588]
### Description

If a value greater than the maximum integer value is cast as an int, instead of throwing an exception, the value returned is the **minimum** integer value minus one, ie. 2147483648 returns -2147483648.  I could understand it returned the maximum integer value, ie **positive** 2147483648, but returning a **negative** value results in unexpected errors.

### Reproduction Steps

`double value = 2147483648;
 int integerValue = (int)value;
 Debug.WriteLine(integerValue);`

### Expected behavior

This is the exception thrown by

`integerValue = Convert.ToInt32(value);
`

> Exception thrown: 'System.OverflowException' in System.Private.CoreLib.dll
> An exception of type 'System.OverflowException' occurred in System.Private.CoreLib.dll but was not handled in user code
> Value was either too large or too small for an Int32.

### Actual behavior

-2147483648

### Known Workarounds

`integerValue = Convert.ToInt32(value);
`
or
`integerValue = (int)Math.Min(value, int.MaxValue);`

### Configuration

.NET 6.0 on Microsoft Visual Studio Community 2022 (64-bit) Version 17.7.4

**Comment by stephentoub** [comment]
Whether such a cast throws is based on whether the operation is being performed in a `checked` context.
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/checked-and-unchecked
By default, such checking is not enabled and overflows from such casts do not throw.

**Comment by gfoidl** [comment]
>  I could understand it returned the maximum integer value, ie positive 2147483648, but returning a negative value results in unexpected errors

As background see [Integer overflow](https://en.wikipedia.org/wiki/Integer_overflow).
Also -- depending on what you're trying to do -- you could use `uint` / `long` instead of `int` iff you need a signed number greater than `int.MaxValue`.
