### ISSUE TITLE
6.x.x or 7.x.x packages for a .NET 6 application?

### ISSUE THREAD

**Issue by HazNut** [dotnet/runtime#92596]
Hi,

I've recently been updating a .NET Core 3.1 app to .NET 6. I'm also updating NuGet packages as a part of this.

For Microsoft packages, I've noticed they seem to be on versions 7.0.0, which are compatible with .NET 6 and .NET 7. E.g. Microsoft.Extensions.DependencyInjection.

Will versions 6.x.x of Microsoft NuGets continue to get patches while 7.x.x do not? As .NET 6 is long term support, I'm not sure if this extends to NuGet packages. I'm not sure if it would be better to stick with 6.x.x packages while we're on .NET 6, from a security and support perspective.

My knowledge of how these packages are produced is pretty limited, so would welcome some more information on that :)

I know that this does apply to EF Core, as EF Core 6 is getting LTS while Core 7 does not.

**Comment by ericstj** [comment]
> Will versions 6.x.x of Microsoft NuGets continue to get patches while 7.x.x do not?

Yes, that's correct.  We service the packages along-side the release which they were part of.  We also test the packages together with the release they ship out of.  If these matter to you - then try to keep your packages aligned on the release you're targeting.

We do support backwards compatibility - so if wish to get the latest features and are willing to upgrade packages more often (say - move to 8.0 when 7.0 goes out of support) then you may choose to use the 7.0 packages.  When the 7.0.0 packages go out of support we will have 8.0.0 packages available that are in support.

More information about this is available here: https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core
