### ISSUE TITLE
[API Proposal]: Use [RuntimeDirectivesAttribute] to mark RuntimeDirectives Types when use reflection in aot.

### ISSUE THREAD

**Issue by dameng324** [dotnet/runtime#92593]
### Background and motivation

I have learned Rd.xml, but It's very difficute to use, so can we use Attrbute to mark the type/property/method which should  contain the metadata in aot compile time?

I do not know the [RuntimeDirectivesAttribute] name is suitable or not, maybe there is a more Intuitive name.

### API Proposal

```cs
public class RuntimeDirectivesAttribute:Attribute{}
```

### API Usage

```cs
[RuntimeDirectivesAttribute]
public class Person
{
    [RuntimeDirectivesAttribute]
    public string FirstName { get; set; }
    
    [RuntimeDirectivesAttribute]
    public string GetFirstName()
    {
        return FirstName;
    }
}
```

**Comment by jkotas** [comment]
Take a look at [`DynamicallyAccessedMembersAttribute`](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming?pivots=dotnet-8-0#dynamicallyaccessedmembers) and [`DynamicDependencyAttribute`](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming?pivots=dotnet-8-0#dynamicdependency). These attributes are the recommended way to mark the type/property/method that should accessible via reflection at runtime.

> I have learned Rd.xml, but It's very difficute to use,

We agree that Rd.xml is very difficult to use. We do not recommend using it. We plan to remove the support for Rd.Xml in future .NET version.

**Comment by dameng324** [comment]
@jkotas thanks for your reply, I will forget Rd.xml and try these Attribute.
