### ISSUE TITLE
Deoptimization returns different versions of code when R2R is used

### ISSUE THREAD

**Issue by mikelle-rogers** [dotnet/runtime#92616]
### Description

Stepping into a R2R method while debugging for the first time that does not result in a deoptimized method.

### Reproduction Steps

```
using System.Runtime.CompilerServices;

class Program
{
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    static void Main()
    {
        Console.Write(5);
        Console.Write(5);
    }
}
```

When using a release runtime, step in 4 times, then out 1, then in 2 times

### Expected behavior

Should be in the `WriteSpan` method.

### Actual behavior

Ends up in the `Flush` method instead of the `WriteSpan` method.

**Comment by tommcdon** [comment]
Fixed via https://github.com/dotnet/runtime/pull/92665
