### ISSUE TITLE
[Feature Request]: Add synchronous gauge instrument

### ISSUE THREAD

**Issue by noahfalk** [dotnet/runtime#92625]
***Edited by @tarekgh***

OpenTelemetry has introduced the [`Gauge`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#gauge) instrument, designed to record non-additive values when changes occur. For example, it can measure the background noise level, where summing the values from multiple rooms would be nonsensical.

## Proposal

```C#
namespace System.Diagnostics.Metrics;

public class Meter : IDisposable
{
	public Gauge<T> CreateGauge<T>(string name) where T : struct {}

	public Gauge<T> CreateGauge<T>(string name, string? unit = null, string? description = null, IEnumerable<KeyValuePair<string, object?>>? tags = null) where T : struct {}
}

public sealed class Gauge<T> : Instrument<T> where T : struct
{
	public void Record(T value) {}

	public void Record(T value, KeyValuePair<string, object?> tag) { }

	public void Record(T value, KeyValuePair<string, object?> tag1, KeyValuePair<string, object?> tag2) { }

	public void Record(T value, KeyValuePair<string, object?> tag1, KeyValuePair<string, object?> tag2, KeyValuePair<string, object?> tag3) { }

	public void Record(T value, params ReadOnlySpan<KeyValuePair<string, object?>> tags) { }

	public void Record(T value, params KeyValuePair<string, object?>[] tags) { }

	public void Record(T value, in TagList tagList) { }
	
	//
	// Instrument<T> properties
	//
	
	public Meter Meter { get; }
        public string Name { get; }
        public string? Description { get; }
        public string? Unit { get; }
        public IEnumerable<KeyValuePair<string, object?>>? Tags { get; }
        public bool Enabled { get; }
        public virtual bool IsObservable { get; }
}

```

## Usage Example

```C#
    Meter meter = new Meter("MeasurmentLibrary.Sound");
 
    Gauge<int> gauge= meter.CreateGauge<int>(name: "NoiseLevel", unit: "dB", description: "Background Noise Level"); // dB is Decibel, the sound intensity level unit
    
    gauge.Record(10, new TagList { "Room1", "dB"});
```

## Original Description

OpenTelemetry has now defined a synchronous gauge. If the OTel maintainers agree the spec is sufficiently stable we should implement it in System.Diagnostics.Metrics. Feel free to replace this stub with a more complete description of the new API surface.

In addition to adding the API, we also need to add support for it to the MetricsEventSource.

OTel issue: https://github.com/open-telemetry/opentelemetry-dotnet/issues/4805

cc @tarekgh

**Comment by lsoft** [comment]
Does any workaround exists now?

I've written

```C#
public sealed class SingleItemGauge<T>
    where T : struct
{
    private readonly ObservableGauge<T> _gauge;

    private bool _valueSent = false;

    public bool ValueSent => _valueSent;

    public SingleItemGauge(
        Meter parentMeter,
        string counterName,
        string counterDescription,
        string counterUnit,
        T counterValue,
        KeyValuePair<string, object?>[] counterTags
        )
    {
        _gauge =
            parentMeter.CreateObservableGauge<T>(
                name: counterName,
                () =>
                {
                    if (_valueSent)
                    {
                        return new Measurement<T>[0];
                    }

                    _valueSent = true;

                    return
                        new[]
                        {
                            new Measurement<T>(
                                value: counterValue,
                                tags: counterTags
                                )
                        };
                },
                unit: counterUnit,
                description: counterDescription
                );
    }
}
```

but I'm not sure if `return new Measurement<T>[0];` means that no more data will be send to otel.

**Comment by lsoft** [comment]
@KalleOlaviNiemitalo I'm a newbie in otel\prometheus area, so does I understand correctly that `MeterListener.RecordObservableInstruments` obtain "my value" but does not send it? if so, does any way to workaround this exists?

anyway, my workaround is just a workaround in absense of "NonObservableGauge" and I'm using it in the application where only one `Meter` and `MeterProvider` exists and non of `MeterListener` declared explicitly...

I've only been learning OTEL+Prometheus for a few days, so I understand a little, but looks like dotnet OTEL is in early stage of its life. For example, prometheus exemplars is not supported, sync Gauge is not supported... etc... Will wait for its mature :)

**Comment by xakep139** [comment]
@lsoft you can also check JS polyfill shared in https://github.com/open-telemetry/opentelemetry-specification/issues/2318#issuecomment-1527376902 and adopt it to C#,
The solution there does support updating the value to be reported though.

**Comment by tarekgh** [comment]
@cijothomas @CodeBlanch @noahfalk @reyang could you please let me know if you have any feedback regarding the proposal https://github.com/dotnet/runtime/issues/92625#issue-1912726479?

**Comment by cijothomas** [comment]
> @cijothomas @CodeBlanch @noahfalk @reyang could you please let me know if you have any feedback regarding the proposal [#92625 (comment)](https://github.com/dotnet/runtime/issues/92625#issue-1912726479)?

LGTM.

**Comment by CodeBlanch** [comment]
LGTM

**Comment by noahfalk** [comment]
LGTM

**Comment by terrajobst** [comment]
Looks good as proposed.

```C#
namespace System.Diagnostics.Metrics;

public partial class Meter : IDisposable
{
	public static Gauge<T> CreateGauge<T>(string name) where T : struct;
	public static Gauge<T> CreateGauge<T>(string name, string? unit = null, string? description = null, IEnumerable<KeyValuePair<string, object?>>? tags = null) where T : struct;
}

public sealed class Gauge<T> : Instrument<T> where T : struct
{
	public void Record(T value);
	public void Record(T value, KeyValuePair<string, object?> tag);
	public void Record(T value, KeyValuePair<string, object?> tag1, KeyValuePair<string, object?> tag2);
	public void Record(T value, KeyValuePair<string, object?> tag1, KeyValuePair<string, object?> tag2, KeyValuePair<string, object?> tag3);
	public void Record(T value, params ReadOnlySpan<KeyValuePair<string, object?>> tags);
	public void Record(T value, params KeyValuePair<string, object?>[] tags);
	public void Record(T value, in TagList tagList);
}
```
