### ISSUE TITLE
System.Text.Json can't deserialize nested records inside class

### ISSUE THREAD

**Issue by Sophisticated-IS** [dotnet/runtime#92629]
### Description

System.Text.Json can't deserialize nested records inside class. It reads all properties and sets null foreach.

### Reproduction Steps

```
public class  ConfiguratorConfig
{
    public AppSettings AppSettings { get; } 
}
public record AppSettings(string Name, string Version)
{
    public string Name { get;  } = Name;
    public string Version { get;  } = Version;
}
```

```
var bytes = await File.ReadAllBytesAsync(fullPath);
var config =JsonSerializer.Deserialize<ConfiguratorConfig>(bytes);
```

### Expected behavior

Record read only properties inside class must be not null and correctly deserialized.

### Actual behavior

All record read only properties are set to null by JsonSerializer and ignored;

### Known Workarounds

If you set record instead of class for root type then deserialization will work correctly.

### Configuration

.NET 7
Windows 10
x64

**Comment by Tornhoof** [comment]
Is there a reason why your ``ConfiguratorConfig`` type has no setter?

**Comment by eiriktsarpalis** [comment]
Either that, or adding a constructor like your nested type does. You need to give the serializer a way to populate the property and there currently isn't one.

**Comment by Sophisticated-IS** [comment]
> Is there a reason why your `ConfiguratorConfig` type has no setter? Try adding one, it will probably work then.

Yeah the type is immutable intentionally cuz it is like the config of full application that read only once and must not be changed accidentally. By default JsonSerializer must deserialize correctly readonly properties.

**Comment by eiriktsarpalis** [comment]
> Yeah the type is immutable intentionally cuz it is like the config of full application that read only once and must not be changed accidentally.

You can use a constructor or an init-only setter to make the type immutable.

> By default JsonSerializer must deserialize correctly readonly properties.

How? You're assuming that a getter might have a backing field but that's not always true and not trivial to determine if it does.
