### ISSUE TITLE
[API Proposal]: ReadAllLinesEnumerable method

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#92636]
### Background and motivation

I suggest adding such a method to the Fille class

### API Proposal

```
IEnumerable<string> ReadAllLinesEnumerable(string file)
{
    using var read = new StreamReader(file);
    while (!read.EndOfStream)
    {
        yield return read.ReadLine();
    }
}
```

### API Usage

`File.ReadAllLinesEnumerable("file.txt").Select(a=>int.Parse(a)).ToList();`

**Comment by Mr0N** [comment]
and async version
```
async IAsyncEnumerable<string> ReadAllLinesEnumerableAsync(string file)
{
    using var read = new StreamReader(file);
    while (!read.EndOfStream)
    {
        yield return await read.ReadLineAsync();
    }
}
```

**Comment by jkotas** [comment]
These methods exist already - take a look at `File.ReadLines` and `File.ReadLinesAsync`

**Comment by Mr0N** [comment]
> These methods exist already - take a look at `File.ReadLines` and `File.ReadLinesAsync`

in the example, the methods do not load information into RAM, File.ReadAllLines loads information into RAM before and then returns the data array

**Comment by jkotas** [comment]
There are two different methods: `File.ReadAllLines` and`File.ReadLines` .

`File.ReadAllLines` loads everything into an array as you have said. `File.ReadLines` returns IEnumerable and reads the file lazily, just like your proposal.
