### ISSUE TITLE
`UnsafeAccessor` throws `MissingFieldException` on generic field (`T`)

### ISSUE THREAD

**Issue by AoshiW** [dotnet/runtime#92633]
### Description

`UnsafeAccessor` throws `MissingFieldException` on generic field (`T`) in generic type,  where genetic `T` is:
- `class`  (e.g. `string`)
- `struct` that has `class` as a generic parameter  (e.g. `ArraySegment<string>`)

### Reproduction Steps

```cs
[UnsafeAccessor(UnsafeAccessorKind.Field, Name = "_items")]
static extern ref string[] GetItems(List<string> list);

GetItems(new());
```

### Expected behavior

getting field

### Actual behavior

throws exception
```
System.MissingFieldException: Field not found: 'System.Collections.Generic.List`1._items'.
```

### Configuration

.NET SDK: 8.0.100-rc.1.23455.8

**Comment by jkotas** [comment]
cc @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
Boo. For my original implementation of the signature match this worked. When I switched to the more robust, but stricter, built-in element compare this support was lost. Le sigh. There is little chance this sort of fix meets the servicing bar. I will take a little bit to try and make it work, but this is likely a .NET 9 fix.

**Comment by AaronRobinsonMSFT** [comment]
Yep, this is a future fix. If the `T` is anywhere in the field or method signature this is going to fail.

Let me add some tests for this.

**Comment by AaronRobinsonMSFT** [comment]
With how this is currently implemented there is some overlap with https://github.com/dotnet/runtime/issues/89439. The core issue being how we parse and compare signatures.

**Comment by AaronRobinsonMSFT** [comment]
I've added disabled tests in https://github.com/dotnet/runtime/pull/92657 and fixed some issues with NAOT.

**Comment by AaronRobinsonMSFT** [comment]
I'm going to close this as duplicate since this work will be included in https://github.com/dotnet/runtime/issues/89439. I've already got the static/instance fields working and have re-enabled the failing tests in my [working branch](https://github.com/AaronRobinsonMSFT/runtime/tree/generic_unsafe_accessors).
