### ISSUE TITLE
System.Text.Json.JsonElement.TryGetDouble() succeeds when the value is not representable as a double

### ISSUE THREAD

**Issue by mwadams** [dotnet/runtime#92631]
### Description

TryGetDouble() documents its behaviour when the value is outside the range of a double - returning +ve or -ve infinity which makes it possible to detect the issue.

However, when the value has excess precision, it succeeds and silently truncates the value, leaving you with no way of detecting the error.

Clearly, this is problematic in many numeric scenarios where truncation of this nature might be significant.

### Reproduction Steps

```csharp
// A number representable as a decimal, but not as a double
using JsonDocument doc = JsonDocument.Parse("1234567890.1234567891");

if (doc.RootElement.TryGetDouble(out double someValue)
{
  Debug.Assert(someValue == 1234567890.1234567); // Sadly true
}
```

### Expected behavior

I would expect this to return `false` as the number is not representable as a double.

### Actual behavior

Returns true and truncates the double.

### Known Workarounds

Because you cannot detect the truncation, there are no workarounds for this issue.

### Configuration

net8.0

### Other information

The problem ultimately lies in how `Utf8Parser.Number.cs` handles automatically rounding to representable numbers, without providing any information  about the `nonZeroTail` in either part of the parsing.

https://github.com/dotnet/runtime/blob/f276c514fe5fe4d9120420286ab7c6299f874992/src/libraries/System.Private.CoreLib/src/System/Buffers/Text/Utf8Parser/Utf8Parser.Number.cs#L16C5-L16C5

**Comment by mwadams** [comment]
I would suggest that this straddles area-System.Numerics and area-System.Text.Json

**Comment by ericstj** [comment]
It seems to be implemented in https://github.com/dotnet/runtime/blob/f47c963e966f000b59c79dc9acb5305a07d0031a/src/libraries/System.Private.CoreLib/src/System/Buffers/Text/Utf8Parser/Utf8Parser.Number.cs

CC @dotnet/area-system-buffers @dotnet/area-system-text-json 

Leaving this in @dotnet/area-system-numerics for now to get the opinion of our double experts.

**Comment by tannergooding** [comment]
If you need to accurately represent decimal numbers, especially with more than 15-17 significant digits; then you should use `System.Decimal` which allows accurate tracking of up to 28 significant digits (and partial tracking of 29 digits).

That itself will also introduce rounding error if the underlying string has more than 28 significant digits and will not surface such loss. That's just how floating-point types work in most programming languages.

**Comment by mwadams** [comment]
Okay; that all makes sense - this is equivalent to the float/double roundtrip (of which 0.3 is the canonical example).

And a JavaScript number is defined to be a 64bit IEEE 754 number internally, so any other representation we choose when deserializing from JSON is fundamentally implementation dependent.

That makes sense.
