### ISSUE TITLE
[API Proposal]: Deprecate non-generic collections

### ISSUE THREAD

**Issue by colejohnson66** [dotnet/runtime#92640]
### Background and motivation

For the past decade plus (almost two decades since .NET Framework 2.0), non-generic collections (from `System.Collections`) have been discouraged in favor of generic ones (from `System.Collections.Generic`). However, the non-generic ones have never been deprecated. They should be.

Usage of non-generic collections incurs boxing when using structs/primitives, and unboxing/cast checks when retrieving. This is a performance waster that is easily remedied by using generics.

Users could easily "fix" their code by using `object` as the generic parameters, but the real fix would be to use the proper types.

Note: I am not proposing to deprecate non-generic interfaces or abstract base classes in `System.Collections` (such as `CollectionBase` or `IEnumerable`), as the interfaces have legitimate uses in some cases, and the abstract base classes would require refactoring to not use. Perhaps the abstract base classes could be deprecated in the future, but that is not part of this proposal.

### API Proposal

```csharp
namespace System.Collections;

// dummy messages are used here; they would be changed if approved

[Obsolete("Use System.Collections.Generic.List<T>.")]
public class ArrayList : ...
{ ... }

[Obsolete("Use System.Collections.Generic.Dictionary<TKey,TValue>.")]
public class Hashtable : ...
{ ... }

[Obsolete("Use System.Collections.Generic.Queue<T>.")]
public class Queue : ...
{ ... }

[Obsolete("Use System.Collections.Generic.SortedList<TKey,TValue> or System.Collections.Generic.SortedDictionary<TKey,TValue>.")]
public class SortedList : ...
{ ... }

[Obsolete("Use System.Collections.Generic.Stack<T>.")]
public class Stack : ...
{ ... }
```

### API Usage

Old usage:

```csharp
ArrayList possibleResults = new ArrayList();
// add integer data here through boxing
int result = (int)possibleResults[42]; // get through unboxing and cast checks
```

Simple fix:
```csharp
ArrayList possibleResults = new ArrayList();
// add integer data here through boxing
int result = (int)possibleResults[42]; // get through unboxing and cast checks
```

Real fix:
```csharp
List<int> possibleResults = new List<int>();
// add integer data here without boxing
int result = possibleResults[42]; // get without unboxing or cast checks
```

### Alternative Designs

[DE0006](https://github.com/dotnet/platform-compat/blob/master/docs/DE0006.md) supposedly already "exists" to flag usage of non-generic collections, and is even linked to in the documentation, but it doesn't work. Visual Studio and [SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMBGAWACgsAGAAizwDoBhAewBtGBTAYwSnpgGcBuYsQCCyZBACeAGSg8E5RjLkBecjBYB3ABQBKAUQWzqQgCbHNeXcQMIjpzTktFiAM3rIWENgAtym+sAArdjkWVjByWHlFbWJyOMo8AE5NUJYwXSA) show no warnings.

![A screenshot of `ArrayList a = new()` in Visual Studio showing a lack of warnings](https://github.com/dotnet/runtime/assets/11381599/5084d40a-0e03-4e2a-b0ca-f46e2d66ae78)

Perhaps that analyzer could be resurrected and used, but the one for `[Obsolete]` already exists and works (as [CS0418](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0618)).

### Risks

A possible risk would be additional warnings to users who have a legitimate need to use non-generic collections. For example, a business application might be interacting with a DLL that uses `ArrayList` (instead of `List<T>`), and would therefore _have_ to construct an `ArrayList`. However, I believe this risk is nonexistent; Any DLLs that use non-generic collections are (almost certainly) stuck on .NET Framework, and won't be updated. Even then, users on .NET 9 that have some need to use `ArrayList` could silence the warning:

```csharp
if (doBusinessLogic)
{
#pragma warning disable CS0418
    // CS0418 is for `[Obsolete]`; `ArrayList` must be used because X, Y, and Z
    ArrayList myList = new ArrayList();
    ...
#pragma warning restore CS0418
}

**Comment by huoyaoyuan** [comment]
They are still exposed by some (old) public APIs, and can be derived in some places.

Currently in .NET, deperecating a type is a "hard" change. It will cause warings on properties/methods referencing them, and derived types.

**Comment by MichalPetryka** [comment]
I guess that adding a built-in performance analyzer would be the better option here.

**Comment by colejohnson66** [comment]
> They are still exposed by some (old) public APIs, and can be derived in some places.
> 
> Currently in .NET, deperecating a type is a "hard" change. It will cause warings on properties/methods referencing them, and derived types.

Deprecating the constructors themselves could be a better option then. Then only the users who construct them would get a warning. Old .NET APIs that expose them would disable the warning when constructing, but users would not be warned.

```csharp
public ArrayList GetSomeListThroughOldApi()
{
#pragma warning disable CS0418
    ArrayList result = new();
#pragma warning restore CS0418

    // add values
    return result;
}
```

Sidenote: what are these non-deprecated APIs that use these non-generic collections? Could those APIs be deprecated _themselves_? Or are they returning non-generic collections? Could all these APIs be replaced with overloads that use generic types?

**Comment by Clockwork-Muse** [comment]
> Could all these APIs be replaced with overloads that use generic types?

You can't overload based on return type, so no.
You'd need a new method.

**Comment by karakasa** [comment]
Some of the old types have slightly different behavior and guarantees than their generic version. An analyzer on constructors is better afaic

**Comment by colejohnson66** [comment]
> > Could all these APIs be replaced with overloads that use generic types?
> 
> You can't overload based on return type, so no. You'd need a new method.

Which would be fine. You'd deprecate the non-generic returning method in favor of the (new) generic returning one. That still doesn't answer the question of *what* these APIs are.

**Comment by karakasa** [comment]
I assume there are more in WinForm.

### System.Security.SecurityElement

* Void set_Attributes(System.Collections.Hashtable)
* Void set_Children(System.Collections.ArrayList)
* System.Collections.Hashtable Attributes
* System.Collections.ArrayList Children

### System.ComponentModel.TypeDescriptor

* Void AddEditorTable(System.Type, System.Collections.Hashtable)

### System.Diagnostics.CorrelationManager

* System.Collections.Stack LogicalOperationStack

### System.Diagnostics.TraceEventCache

* System.Collections.Stack LogicalOperationStack

### System.Net.WebProxy

* System.Collections.ArrayList BypassArrayList

### System.Runtime.Serialization.DataContracts.DataContractSet

* System.Collections.Hashtable SurrogateData

### System.Xml.Schema.XmlSchemaValidator

* Void GetUnspecifiedDefaultAttributes(System.Collections.ArrayList)

### System.Xml.Serialization.XmlSerializerImplementation

* System.Collections.Hashtable ReadMethods
* System.Collections.Hashtable WriteMethods
* System.Collections.Hashtable TypedSerializers

**Comment by colejohnson66** [comment]
Fair. I wonder how useful those properties/methods are, though.

The vast majority of that list is for, I would argue, niche use cases, and could be deprecated in favor of typed generic versions. For example, instead of `System.Collections.Specialized.CollectionsUtil.CreateCaseInsensitiveHashtable`, one should use `Dictionary<TKey,TValue>` with a custom `System.StringComparer` instance. In fact, I would also argue that half of `System.Collections.Specialized` should be deprecated and/or with generic versions. `Dictionary<string, string>` should be used instead of `StringDictionary`, `Collection<string>` or `List<string>` instead of `StringCollection`, etc.

I do, however, see that `System.Runtime.Serialization.DataContracts` was released with .NET 7. Why did the developers go with a non-generic dictionary there?

**Comment by karakasa** [comment]
> I do, however, see that `System.Runtime.Serialization.DataContracts` was released with .NET 7. Why did the developers go with a non-generic dictionary there?

There're no relating comments in that file. I'm assuming because of `HashTable` is (kind of) thread safe, compared to `Dictionary<, >`

**Comment by eiriktsarpalis** [comment]
I don't believe we have any plans on deprecating non-generic collections in the near future. There are still valid reasons to depend on them, including legacy and different concurrency guarantees (e.g. comparing `HashTable` with `Dictionary<K,V>`).

cc @jeffhandley @terrajobst @stephentoub

**Comment by colejohnson66** [comment]
> I don't believe we have any plans on deprecating non-generic collections in the near future. There are still valid reasons to depend on them, including legacy and different concurrency guarantees (e.g. comparing `HashTable` with `Dictionary<K,V>`).

Then why was DE0006 ever a thing? The presence of it, at one point, indicates that the team at least wanted to discourage them (somewhat of a partial deprecation).

**Comment by huoyaoyuan** [comment]
> indicates that the team at least wanted to discourage them (somewhat of a partial deprecation).

That's true. The term "deprecate" is a bit too strong, and breaking for WarnAsError users.

**Comment by stephentoub** [comment]
`Hashtable`'s implementation makes it safe for any number of readers to be using it concurrently with a single writer.  That means if you might have many readers and writers all accessing the table concurrently, you can lock just around the writes.

**Comment by colejohnson66** [comment]
So does `ConcurrentDictionary<TK,TV>`. Reading does not involve locks, and writing only does if necessary. Concurrent, generic, alternatives with the same guarantees exist for all the types I mentioned in the proposal. For example, with `ArrayList`, use `List<T>`. If atomic read/writes on the index (`get_Item` and `set_Item`) are desired, wrap `T` in a `StongBox<T>` and create a new one on updates:

```csharp
List<StrongBox<MyBigType>> list = new();
// ...
MyBigType oldValue = list[5].Value; // reading index 5 is guaranteed to not tear
MyBigType newValue = ...;
list[5] = new(newValue); // writing index 5 is guaranteed to not tear
```

Disregarding that, if non-generic collections make some guarantees that the generic ones don't, then new (generic) collections should be added that make those same guarantees.

Barring all of that, there's no requirement that all the collections I mentioned above must be deprecated at the same time. If `Hashtable` still has uses, then just don't deprecate it. For example, there's nothing in `Hashtable` that would prevent deprecating, say, `ArrayList`.

**Comment by stephentoub** [comment]
> So does ConcurrentDictionary<TK,TV>. Reading does not involve locks, and writing only does if necessary

Writing to a ConcurrentDictionary always locks.

> If Hashtable still has uses, then just don't deprecate it. For example, there's nothing in Hashtable that would prevent deprecating, say, ArrayList.

Several of these are still heavily used, including both Hashtable and ArrayList. From my perspective, marking these as obsoleted or deprecated will do more harm than good. If your goal is to flag when they're used in a codebase you own, you can use an analyzer like the banned API analyzer to flag uses of them.
