### ISSUE TITLE
[API Proposal]: GC.RegisterNonGCSegment (custom NonGC heaps)

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#92650]
### Background and motivation

Some people were interested in [NonGC segments](https://github.com/dotnet/runtime/blob/main/docs/design/features/NonGC-Heap.md) (formely known as "Frozen") e.g. few people working on a game engine, etc. This feature is already used by one of our big 1P customers (and even made public via https://github.com/microsoft/FrozenObjects) - it allows to create your own managed heaps and do things like mmaping large files with objects referecing each other or containing primitives directly to memory (you only need to fixup some pointers) + saves work for GC as it will never scan/collect/compact them + they're effectively pinned. Some of the people raised a concern that a private API means we're not responsible to keep it/maintain it in long run. So I wonder if we should expose it and have some documentation on how to work with it. An API proposal may look like this:

### API Proposal

```cs
namespace System
{
    public static class NonGC
    {
        public static bool IsSupported { get; } // CoreCLR, NativeAOT both support it, Mono doesn't currently.

        public static Segment RegisterSegment(IntPtr memAddr, nint allocated);
        
        public static void UnregisterSegment(Segment segment);

        public struct Segment
        {
            public IntPtr Handle { get; }
        }
    }
}
```

NOTE: NonGC also allows dynamic expansion but it's very hard to make it correct so I intentionally didn't include `UpdateNonGCSegment` API here to focus mostly on deserialization scenarios.

### API Usage

TODO: a usage example. 
_I posted a joking example on twitter: https://twitter.com/EgorBo/status/1706316706316996947_

### Alternative Designs

Alternatively, we can discuss a more advanced `NonGC` manager API that will also expose some helpers typically needed for this task such as `int GetObjectSize(object obj, out int alignment)` etc.

### Risks

We're sort of exposing inner object layout that we might change in future (e.g. getting rid of object's header). Same for field layout to satisfy VM - it might make it difficult to update to newer version of .NET for customers. However, this feature implies deep knowledge of CLR internals as is.

**Comment by EgorBo** [comment]
cc @jkotas @Maoni0 @cshung @mjsabby

**Comment by jkotas** [comment]
> Some of the people raised a concern that a private API means we're not responsible to keep it/maintain it in long run

Right, I do not think we want to tie our hands and set the current frozen segment data structures in stone that would be required to maintain binary compatibility. 

I think the internal API is appropriate for this purpose. It communicates that you are depending on internal implementation details of the specific runtime version. I do not see a problem with it.

**Comment by EgorBo** [comment]
No strong opinion on that, just wanted to have an api proposal with an explanation why it's not public

**Comment by mjsabby** [comment]
@EgorBo absolutely! I've been meaning to do it, but did not get a chance.

**Comment by cshung** [comment]
From a scenario perspective, being able to use nongc heap segments for dynamically allocated objects can be a big win for situations [Frozen collections](https://github.com/dotnet/runtime/tree/66f4a1df77a0a979a0b9c0941700eaf2ee808de5/src/libraries/System.Collections.Immutable/src/System/Collections/Frozen) addresses. 

I wonder how big they will be in practice, but if it is significant and is practically alive forever, moving it outside of the GC can save big on background GC time.

NonGC heap segments can also serve as an arena. In scenarios where people could manage to make sure they have a phase where within a phase, their object graph is self-contained, and outside of that phase, the object graph is gone as a whole, dynamic NonGC heap segment will fit perfectly, with no GC cost.

With the change of the naming, we should also change our thinking. These NonGC heap segments aren't frozen at all. They can be changed, we just have to be careful about what kind of changes are allowed. The precise rule of what changes are allowed for Frozen objects is still pretty tricky, the fact that we can't change references is rather unfortunate, that's a restriction only for segments.

If there is enough interest, we should give it a try and see how much win we could have with this.

To pull that off, you need at least the capability to allocate an object on the nongc segment, which is prototyped in my test case [here](https://github.com/dotnet/runtime/blob/main/src/tests/GC/API/Frozen/Frozen.cs). The test also specified precisely what changes are allowed.

Meanwhile, I think we should keep this API internal.
