### ISSUE TITLE
[QUIC] Authentication failed because the remote party sent a TLS alert  'UserCanceled'

### ISSUE THREAD

**Issue by IlGalvo** [dotnet/runtime#92669]
### Description

Error during: `await QuicConnection.ConnectAsync(options)`.

When connetting the handshake (probably) fails and:
`Authentication failed because the remote party sent a TLS alert  'UserCanceled'`
is thrown.

As you can see in the screen below:
![immagine](https://github.com/dotnet/runtime/assets/17992288/e0b993f0-bac2-4289-8af1-04ab99798b25)

If you try to play comment/uncomment in the project, nothing changes.
[QuicTest.zip](https://github.com/dotnet/runtime/files/12732176/QuicTest.zip)

I tried all I could, but nothing changed.
I need to use this library in a business app.

### Reproduction Steps

Use the test project attached.

### Expected behavior

`await QuicConnection.ConnectAsync(options)` does not throw an exception.

### Actual behavior

`await QuicConnection.ConnectAsync(options)` throws an exception.

### Regression?

Don't know.

### Known Workarounds

Unfortunately no.

### Configuration

OS:
![immagine](https://github.com/dotnet/runtime/assets/17992288/609257bf-da46-487f-941f-3e1bf98f3a06)

SDK:
dotnet 7.0.401

### Other information

If you need further info, ask me, i will be glad to answer.
Thank you in advance.

**Comment by ManickaP** [comment]
The example (with some minor fixes) works on Linux. But doesn't work on WIndows. This looks like the same problem in #88298. @wfurt the repro here uses yours recommended RSA but it still doesn't work. Any ideas?
Also I'd interested in knowing how to troubleshoot this, where to look for supported algorithms, etc.

**Comment by IlGalvo** [comment]
I was able to replicate your error by doind this:
![immagine](https://github.com/dotnet/runtime/assets/17992288/a13a729c-e0bd-40ca-8d57-a89433358b01)
and
![immagine](https://github.com/dotnet/runtime/assets/17992288/1a7c98d8-ebb5-4ee2-9bfc-546f0bb9b0a0)

So I guess it's a problem in certificate generation.

About this I have two questions:

1. Is it mandatory to use certificates (client/server)?
I'm just interested in server
2. If it works on linux, what is the real problem (windows)?

I await a kind response from you.
Thank you in advance.

**Comment by ManickaP** [comment]
> Is it mandatory to use certificates (client/server)?
> I'm just interested in server.

For server it is, for client isn't.

> If it works on linux, what is the real problem (windows)?

MsQuic uses SChannel on Windows (OpenSSL on Linux) and apparently it isn't happy about that cert. If you check the original issue, that cert will fail with `SslStream` as well. But I'm not security expert to tell you exactly what is wrong with the cert. We'll have to wait for @wfurt.

**Comment by IlGalvo** [comment]
So, just to clafity, the correct inatialization wuold be (based on my repo and recommendations):

Server:
![immagine](https://github.com/dotnet/runtime/assets/17992288/ef0cafe9-82cb-4280-a92b-f0375dd3fae5)

Client:
![immagine](https://github.com/dotnet/runtime/assets/17992288/ec829bfc-ae67-4681-a227-9f59d728a43c)

Am I missing something?
For the rest I await a kind response from @wfurt.

Thank you @ManickaP.

**Comment by ManickaP** [comment]
> So, just to clafity, the correct inatialization wuold be (based on my repo and recommendations):

Yep, that's it, server needs the certificate and client needs the validation callback.

**Comment by ManickaP** [comment]
You will see the client getting `UserCancelled`, but the server logs will tell you more info:
```
Connection handshake failed: System.Security.Authentication.AuthenticationException: Authentication failed. ConfigurationLoadCredential failed: QUIC_STATUS_CERT_NO_CERT
```
which corresponds to https://github.com/dotnet/runtime/issues/88298

**Comment by IlGalvo** [comment]
Ok, thank you for the clarification @ManickaP.

That's all for now.
I await a kind response from @wfurt.

**Comment by wfurt** [comment]
schannel cannot work with ephemeral keys. We should probably port to  https://github.com/dotnet/runtime/pull/83436 for Quic as well to get better diagnostic @ManickaP.

Can you try to add something like this as workaround @IlGalvo ? 

https://github.com/dotnet/runtime/blob/a707e940e6982b04b2f2832e9850e17e0f8dcfac/src/libraries/System.Net.Security/tests/FunctionalTests/TestHelper.cs#L211-L216

**Comment by IlGalvo** [comment]
Hi @wfurt,
thanks to the change you recommended, I was able to make it work as intended.

Now my `CreateSelfSignedCertificate` looks like this:
```
static X509Certificate2 CreateSelfSignedCertificate()
{
    using var rsa = RSA.Create();
    var certificateRequest = new CertificateRequest("CN=localhost", rsa, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);
    certificateRequest.CertificateExtensions.Add(
        new X509BasicConstraintsExtension(
            certificateAuthority: false,
            hasPathLengthConstraint: false,
            pathLengthConstraint: 0,
            critical: true
        )
    );
    certificateRequest.CertificateExtensions.Add(
        new X509KeyUsageExtension(
            keyUsages:
                X509KeyUsageFlags.DigitalSignature | X509KeyUsageFlags.KeyEncipherment |
                X509KeyUsageFlags.CrlSign | X509KeyUsageFlags.KeyCertSign,
            critical: false
        )
    );
    certificateRequest.CertificateExtensions.Add(
        new X509EnhancedKeyUsageExtension(
            new OidCollection
            {
                //new Oid("1.3.6.1.5.5.7.3.2"), // TLS Client auth
                new Oid("1.3.6.1.5.5.7.3.1")  // TLS Server auth
            },
            false));

    certificateRequest.CertificateExtensions.Add(
        new X509SubjectKeyIdentifierExtension(
            key: certificateRequest.PublicKey,
            critical: false
        )
    );

    var sanBuilder = new SubjectAlternativeNameBuilder();
    sanBuilder.AddDnsName("localhost");
    certificateRequest.CertificateExtensions.Add(sanBuilder.Build());

    var cert = certificateRequest.CreateSelfSigned(DateTimeOffset.Now.AddDays(-1), DateTimeOffset.Now.AddYears(5));

    // windows only
    return new X509Certificate2(cert.Export(X509ContentType.Pfx), (string?)null, X509KeyStorageFlags.Exportable);
}
```

if by any chance you see other things that could be changed or improved,
I would be grateful if you let me know.

Thank you!

**Comment by ManickaP** [comment]
Closing as the question is answered.
