### ISSUE TITLE
Relax DynamicMethod to permit ref returns

### ISSUE THREAD

**Issue by MichalPetryka** [dotnet/runtime#92670]
As per documentation, DynamicMethod currently blocks returning refs from itself:
![image](https://github.com/dotnet/runtime/assets/35800402/a5f693fe-e6d5-40f5-84ca-efab78b6e16e)
Since this seems to be a legacy behaviour from the times when ref returns in general weren't allowed, would it be possible to unblock defining such DynamicMethods?
My current workaround for this is wrapping the return in a single element span and then using GetReference to extract it.

**Comment by jkotas** [comment]
This was fixed by https://github.com/dotnet/coreclr/pull/15106 for .NET Core 2.1. We just forgot to update the docs: https://github.com/dotnet/dotnet-api-docs/pull/9335

**Comment by MichalPetryka** [comment]
> This was fixed by [dotnet/coreclr#15106](https://github.com/dotnet/coreclr/pull/15106) for .NET Core 2.1. We just forgot to update the docs: [dotnet/dotnet-api-docs#9335](https://github.com/dotnet/dotnet-api-docs/pull/9335)

Ah I've only checked with older runtimes and the docs, good to know then.
