### ISSUE TITLE
[mono][aot] Use compile restart to emit a placeholder method body

### ISSUE THREAD

**Issue by jandupej** [dotnet/runtime#92688]
https://github.com/dotnet/runtime/pull/91261 needs to emit a stand-in method body that only contains one `throw` in certain cases. This is currently done explicitly (`method-to-ir.c`: `method_make_alwaysthrow_typeloadfailure`), but after discussion with @vargaz a different approach might be more advantageous. Try and use compilation restart to emit that dummy method body.

**Comment by kotlarmilos** [comment]
Obsolete, lower priority compared to other tasks.
