### ISSUE TITLE
Content security policy issue for embedded browser(chromium) in Blazor Web assembly .js file with eval() 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#92698]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Content-security-policy-issue-for-embedd/10447805)._

---
[severity:It's more difficult to complete my work]
Working on Blazor web assembly app which is hosted and executed on an embedded browser of FDI(Field Device Integration) Reference runtime environment. Though we changed the CSP in the application in meta tag as mentioned below:

<meta charset="utf-8" http-equiv="Content-Security-Policy"
          content="base-uri 'self';
               default-src 'none';
               img-src 'self' 
            data: https:;
               object-src 'none';
           connect-src 'self' ;
               script-src 'self'
                          'unsafe-eval';
               style-src 'self'
                        'unsafe-inline';
               upgrade-insecure-requests;">

and used "unsafe-eval", it gives errors on console as attached. 

![image](https://github.com/dotnet/runtime/assets/271576/05b86126-154e-4f67-94cc-b2d3735bf7ca)

Tested with .NET Runtime 8 preview 7 but errors still exist.
Eval() used in blazor.webassembly.js file causing this issue, can we have fix for this in .NET runtime 8 final release?

---
#### Feedback Bot on 8/23/2023, 01:31 AM: 

(private comment, text removed)
#### Artak Mkrtchyan [MSFT] on 8/25/2023, 10:40 AM: 

(private comment, text removed)
#### Manasi Dixit on 9/5/2023, 11:28 PM: 

(private comment, text removed)
#### Feedback Bot on 9/5/2023, 10:55 PM: 

(private comment, text removed)
#### Feedback Bot on 9/10/2023, 09:34 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
@pavelsavara any thoughts?

**Comment by pavelsavara** [comment]
We still need `wasm-unsafe-eval` and that's not possible to solve.
There is also `new Function` in legacy interop, but not in part that Blazor in Net8 uses.

Other than that we should be eval free. If that's not the case it's a bug.

Is there any `eval` or `new Funtion` in `blazor.webassembly.js`  code/text ?

**Comment by pavelsavara** [comment]
I updated the picture from the original feedback and that explains it, it's a `wasm-unsafe-eval`. Won't fix.
