### ISSUE TITLE
ReadOnlySpan<T>(in T) breaking changes

### ISSUE THREAD

**Issue by 2A5F** [dotnet/runtime#92693]
### Description

https://learn.microsoft.com/en-us/dotnet/api/system.readonlyspan-1.-ctor?view=net-8.0#system-readonlyspan-1-ctor(-0@)

![image](https://github.com/dotnet/runtime/assets/13982338/2dfb85e5-442f-4047-8101-add3f34981b1)

https://learn.microsoft.com/en-us/dotnet/api/system.readonlyspan-1.-ctor?view=net-7.0#system-readonlyspan-1-ctor(-0@)

![image](https://github.com/dotnet/runtime/assets/13982338/1a9cbec6-acc7-4976-a637-12bc2e0d4367)

### Reproduction Steps

NA

### Expected behavior

```cs
var a = new ReadOnlySpan<T>(in some);
```

### Actual behavior

```cs
var a = new ReadOnlySpan<T>(ref some);
```

### Regression?

NA

### Configuration

```
.Net 8.0.100-rc.1.23463.5
```

**Comment by huoyaoyuan** [comment]
This is intentional. Se #85911.

The correct modifier should be `ref readonly` now. Is there any documentation tool update required?

**Comment by KeterSCP** [comment]
Should this breaking change be documented in https://learn.microsoft.com/en-us/dotnet/core/compatibility/8.0?

**Comment by stephentoub** [comment]
The docs are showing it incorrectly: it wasn't changed to `ref` but to `ref readonly`. What problem are you actually observing from it?
