### ISSUE TITLE
JIT: Failed ccmp recognition

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#92699]
```csharp
public struct Point
{
    public long X, Y;

    public static unsafe bool Equals(in Point left, in Point right)
    {
        return (left.X == right.X) & (left.Y == right.Y);
    }
}
```

generates
```asm
G_M28859_IG01:  ;; offset=0x0000
            stp     fp, lr, [sp, #-0x10]!
            mov     fp, sp
						;; size=8 bbWeight=1 PerfScore 1.50
G_M28859_IG02:  ;; offset=0x0008
            ldr     x2, [x0]
            ldr     x3, [x1]
            cmp     x2, x3
            cset    x2, eq
            ldr     x0, [x0, #0x08]
            ldr     x1, [x1, #0x08]
            cmp     x0, x1
            cset    x0, eq
            and     w0, w2, w0
						;; size=36 bbWeight=1 PerfScore 14.50
G_M28859_IG03:  ;; offset=0x002C
            ldp     fp, lr, [sp], #0x10
            ret     lr
						;; size=8 bbWeight=1 PerfScore 2.00
```

I would expect to see `ccmp`.

**Comment by jakobbotsch** [comment]
The problem is that assertion prop marks `left.Y` and `right.Y` as non-faulting, and as part of this sets `GTF_ORDER_SIDEEFF` on them. At the same time the left `GT_EQ` has `GTF_GLOB_REF` on it since it contains two indirections. This makes it illegal to reorder the left `GT_EQ` with the indirections on the right to produce the cmp/ccmp sequence.

**Comment by EgorBo** [comment]
can we use SIMD here 🙂 e.g. recognize `GT_INTRINSIC memcmp` and then expand it (we already have LowerMemcmp)

**Comment by jakobbotsch** [comment]
> can we use SIMD here 🙂 e.g. recognize `GT_INTRINSIC memcmp` and then expand it (we already have LowerMemcmp)

Yeah, that's probably better (for the specific case). I think it should be another issue -- the underlying problem here is around our use of conservative flags for side effect checking in linear IR.
