### ISSUE TITLE
ToString format on DateTime not working under Local System Account

### ISSUE THREAD

**Issue by yoyos** [dotnet/runtime#92707]
### Description

```
var todayStr = DateTime.UtcNow.ToString("yyyy/MM/dd");
File.WriteAllText("file.txt", todayStr);
```

Should output the right Date format in any case.
Under Local System account, that is not the case

### Reproduction Steps

create a .NET 7.0.11 console app doing:

```
var todayStr = DateTime.UtcNow.ToString("yyyy/MM/dd");
File.WriteAllText("file.txt", todayStr);
```

### Expected behavior

When the program is ran through any user or admin account
file content should be 2023/09/23

### Actual behavior

When the program is ran trough nssm under Local System account (service started) :
file content is 2023-09-23

### Known Workarounds

var todayStr = DateTime.UtcNow.ToString("yyyy/MM/dd").Replace("-", "/");

### Configuration

On Windows 10 with .NET 7.011 x64
Debug/Release is the same

**Comment by skyoxZ** [comment]
https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#dateSeparator

> The "/" custom format specifier represents the date separator, which is used to differentiate years, months, and days. The appropriate localized date separator is retrieved from the [DateTimeFormatInfo.DateSeparator](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.datetimeformatinfo.dateseparator) property of the current or specified culture.

I didn't know this for years of development and I believe I'm not alone. I think it's worth to add a bold tip at the beginning of the docs of [DateTime.ToString(String)](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.tostring?view=net-7.0#system-datetime-tostring(system-string)).

**Comment by skyoxZ** [comment]
Use `yyyy'/'MM'/'dd`. (See the docs above to get more details)

**Comment by tarekgh** [comment]
@yoyos using single quotation around the date separator `'/'` should work. You may review the doc section https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#Literals which states the following:

```
By enclosing the entire literal string in quotation marks or apostrophes. The following example is like the previous one, except that "pst" is enclosed in quotation marks to indicate that the entire delimited string should be interpreted as character literals.
```

I am closing this issue, feel free to send any more questions if you have any and we'll be happy to help you with.

**Comment by yoyos** [comment]
Big thanks :)
