### ISSUE TITLE
Correlation payload not found in Build browser-wasm linux Release WasmBuildTests build leg

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#92732]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=419957
Build error leg or test failing: Build / browser-wasm linux Release WasmBuildTests / Send to Helix
Pull request: https://github.com/dotnet/runtime/pull/92661

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "Correlation Payload '[A-Za-z_:\\\/\\\\]+microsoft.netcore.app.ref(\\\\|\\\/)' not found.",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=419957
**Error message validated:** `Correlation Payload '[A-Za-z_:\/\\]+microsoft.netcore.app.ref(\\|\/)' not found.`
**Result validation: :x:** Known issue did not match with the provided build.
**Validation performed at:** 9/27/2023 5:57:04 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by radical** [comment]
Looks like a side-effect of the PR was that `artifacts/bin/microsoft.netcore.app.ref` is not created any more for the WBT build, thus breaking the build.
