### ISSUE TITLE
System.Text.Json.SourceGeneration: SYSLIB0012 Assembly.CodeBase/EscapedCodeBase is obsolete

### ISSUE THREAD

**Issue by msedi** [dotnet/runtime#92752]
This is not really a bug and I wonder why this hasn't been reported before. Using the System.Text.Json source generator I get mutliple : SYSLIB0012 warnings since it obviously uses Assembly.CodeBase or Assembly.EscapedCodeBase.

Its a bit annyoing that these product libraries how these warnings since we are using the source generator very often and it spoils our output.

Will this be solved in .NET 8?

**Comment by eiriktsarpalis** [comment]
Could you share a repro? Unless you're explicitly trying to serialize `System.Reflection.Assembly` this is most likely a bug that got fixed in .NET 8.

**Comment by msedi** [comment]
@eiriktsarpalis. I tried to create a sample project but now I cannot reproduce it anymore. I'm switching between NET7 and NET8 so it could be that there are some leftovers whem I switch from NET7 to NET8. When cleaning the output the messages do not show up. So I would close this now until I see it again.
