### ISSUE TITLE
`System.Net.NameResolution.Functional.Tests` - crashed with `Process terminated. Assertion failed.`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#92793]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=421754
Build error leg or test failing: System.Net.NameResolution.Functional.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/92703

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "System.Net.NameResolution.Functional.Tests.*\n.*Process terminated. Assertion failed.",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** 
**Result validation: :warning:** Provided build not found. Provide a valid build in the "**Build: :mag_right:**" line.
**Validation performed at:** 11/10/2023 10:50:38 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by danmoseley** [comment]
``` 

Process terminated. Assertion failed.
   at System.Net.NetEventSource.Info(String thisOrContextObject, String memberName, String message) in /_/src/libraries/Common/src/System/Net/Logging/NetEventSource.Common.cs:line 80
   at System.Net.NetEventSource.Info(Object thisOrContextObject, FormattableString formattableString, String memberName) in /_/src/libraries/Common/src/System/Net/Logging/NetEventSource.Common.cs:line 67
   at System.Net.Dns.<>c.<GetHostEntryAsync>b__6_0(Task`1 t, Object s) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 126
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs:line 140
``` 
There is a dump

**Comment by danmoseley** [comment]
``` 

        [Event(InfoEventId, Level = EventLevel.Informational, Keywords = Keywords.Default)]
        private void Info(string thisOrContextObject, string? memberName, string? message)
        {
            Debug.Assert(IsEnabled()); //<<<<<
``` 
This is on a Threadpool thread - some race here?

@Miha

**Comment by MihaZupan** [comment]
This could happen if one thread was disabling the specific `EventSource` as another is executing the above `Info` call.
The place that hit the assert just has a particularly large window between checking `IsEnabled` and the call to log.

The only tests using this `EventSource` are these:
https://github.com/dotnet/runtime/blob/7d9b92dee3f7687571a4505f00edb72458743ce7/src/libraries/System.Net.NameResolution/tests/FunctionalTests/LoggingTest.cs#L31-L140
They should be using `RemoteExecutor` instead.
