### ISSUE TITLE
[8.0] File used by another process in Wasm.Build.Tests.Blazor.SimpleRunTests.BlazorBuildAndRunForDifferentOutputPaths

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#92805]
### Error Blob

```json
{
  "ErrorMessage": "Wasm.Build.Tests.Blazor.SimpleRunTests.BlazorBuildAndRunForDifferentOutputPaths(config: \"Debug\", appendRID: False, useArtifacts: True) [FAIL]",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": true
}
```

### Reproduction Steps

- 8.0 PR: https://github.com/dotnet/runtime/pull/92762
- Run: `browser-wasm windows Release WasmBuildTests`
- Job: https://dev.azure.com/dnceng-public/public/_build/results?buildId=421749&view=logs&j=0b2e5ab0-105d-5e21-8497-262338385634&t=5d54f742-8faa-5589-ce3d-1371921d4699&l=143
- Log: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-pull-92762-merge-4ff629fca3084a7483/Workloads-NoWebcil-Wasm.Build.Tests.Blazor.SimpleRunTests/1/console.1c6396e2.log?helixlogtype=result
- Output:
```
    Wasm.Build.Tests.Blazor.SimpleRunTests.BlazorBuildAndRunForDifferentOutputPaths(config: "Debug", appendRID: False, useArtifacts: True) [FAIL]
      System.IO.IOException : The process cannot access the file '\\?\C:\helix\work\workitem\e\wbt\Debug_1d5edcc3_j20' because it is being used by another process.
      Stack Trace:
           at System.IO.FileSystem.RemoveDirectoryInternal(String fullPath, Boolean topLevel, Boolean allowDirectoryNotEmpty)
           at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
           at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
        /_/src/mono/wasm/Wasm.Build.Tests/Common/SharedBuildPerTestClassFixture.cs(56,0): at Wasm.Build.Tests.SharedBuildPerTestClassFixture.RemoveDirectory(String path)
        /_/src/mono/wasm/Wasm.Build.Tests/Common/SharedBuildPerTestClassFixture.cs(34,0): at Wasm.Build.Tests.SharedBuildPerTestClassFixture.RemoveFromCache(String buildPath, Boolean keepDir)
        /_/src/mono/wasm/Wasm.Build.Tests/BuildTestBase.cs(576,0): at Wasm.Build.Tests.BuildTestBase.Dispose()
        /_/src/xunit.execution/Extensions/ReflectionAbstractionExtensions.cs(79,0): at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource)
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=421749
**Error message validated:** `Wasm.Build.Tests.Blazor.SimpleRunTests.BlazorBuildAndRunForDifferentOutputPaths(config: "Debug", appendRID: False, useArtifacts: True) [FAIL]`
**Result validation: :x:** Known issue did not match with the provided build.
**Validation performed at:** 9/29/2023 1:15:06 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by SamMonoRT** [comment]
@radical - please triage, and set milestone accordingly.

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not been hit in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by pavelsavara** [comment]
cc @maraf
