### ISSUE TITLE
The JIT uses an redundant rbp register

### ISSUE THREAD

**Issue by oleg-st** [dotnet/runtime#92818]
### Description

The JIT uses an redundant `rbp` register.

Code:
```c#
public class C
{
    public static int M1(int x, int y)
    {
        return (x == 0 && y == 0) ? 1 : 0;
    }

    public static bool M2(int x, int y)
    {
        return (x == 0 && y == 0);
    }
}
```

ASM:
```asm
// coreclr trunk-20230907+17b60e35528ec0f1eba8a6606168412738bade59

C:M1(int,int):int (FullOpts):
       push     rbp
       mov      rbp, rsp
       or       edi, esi
       sete     al
       movzx    rax, al
       pop      rbp
       ret      

C:M2(int,int):ubyte (FullOpts):
       or       edi, esi
       sete     al
       movzx    rax, al
       ret      
```

[godbolt](https://godbolt.org/z/1r9Mbqjz5)

**Comment by EgorBo** [comment]
Generally, we always setup a frame for stack walking, there are cases on x64 where can omit it for leaf functions (it's not important for the real world as hot small functions are generally inlined anyway). In the given case, jit decided to setup a frame due to basic block count:
```
; Decided to create an EBP based frame for ETW stackwalking (BasicBlock Count)
```

**Comment by EgorBo** [comment]
Probably, in the given case a `ifConversion` phase (or optOptimizeBool) should make it branchless and then leave just one block - not sure why it didn't kick in here, probably becase some opts don't love `return <cond>` kinds of blocks.

**Comment by EgorBo** [comment]
Ah, stale `fgBBcount`
