### ISSUE TITLE
PAL_VirtualUnwindOutOfProc isn't implemented for non x64 platforms

### ISSUE THREAD

**Issue by chsienki** [dotnet/runtime#9282]
On platforms other than x64 _PAL_VirtualUnwindOutOfProc(...)_ is stubbed out to return FALSE  ([remote-unwind.cpp#L1081](https://github.com/dotnet/coreclr/blob/88527bb6bdec8662a5cef5efcadb22c7fcabae50/src/pal/src/exception/remote-unwind.cpp#L1081)).

The current implementation falls back to using DataTarget4->VirtualUnwind on platforms where the PAL method is not implemented, but this will not work in the dump debugging scenario.

**Comment by mikem8361** [comment]
This is now supported on Linux arm32, arm64, amd64 and MacOS amd64.
