### ISSUE TITLE
Add support for detecting page faults within async/await coroutines

### ISSUE THREAD

**Issue by unicomp21** [dotnet/runtime#9284]
Something similar to structured exception handling which can bubble up along the async/await exception handling chain.  Possible use case:

Task taskHasPageFaulted = Task.RunInPageFaultScheduler(MyCoroutine);

Task nextPageFaultedCoroutine = await Task.WaitAny(arrayOfAboveCoroutines);
// run a coroutine which is ready

The dream setup would be using UMS (User Mode Scheduler) from .Net Core.  UMS nailed the page fault thing, when combined w/ structured exception handling.

The intention is being able to multiplex 100k+ coroutines efficiently.

**Comment by stephentoub** [comment]
Closing as asked/answered.  Please re-open if there's something remaining I missed.  Thanks.
