### ISSUE TITLE
Dereference of NULL pointer

### ISSUE THREAD

**Issue by VoroninArtemii** [dotnet/runtime#92858]
After having been compared to a NULL value, pointer `g_pUniqueStackCrst` is passed as 1st parameter in call to class `CrstHolder`, where it is dereferenced.

Call:

https://github.com/dotnet/runtime/blob/3bc1508bb72cf9c24c5f66b1226fd5f1d71ab7dd/src/coreclr/vm/threads.cpp#L5932-L5950

And dereference inside:

https://github.com/dotnet/runtime/blob/3bc1508bb72cf9c24c5f66b1226fd5f1d71ab7dd/src/coreclr/vm/crst.h#L374-L378
https://github.com/dotnet/runtime/blob/3bc1508bb72cf9c24c5f66b1226fd5f1d71ab7dd/src/coreclr/vm/crst.h#L183-L187

Found by Linux Verification Center ([portal.linuxtesting.ru](http://portal.linuxtesting.ru/)) with SVACE.
Author A. Voronin.

**Comment by EgorBo** [comment]
@VoroninArtemii isn't `g_pUniqueStackCrst` never null after `InterlockedCompareExchangeT` ?

**Comment by VoroninArtemii** [comment]
> @VoroninArtemii isn't `g_pUniqueStackCrst` never null after `InterlockedCompareExchangeT` ?

As far as Iunderstand, after `InterlockedCompareExchangeT` pointer `g_pUniqueStackCrst` is always equal to `Attempt`. And what happens if memory allocation fails? Will `g_pUniqueStackCrst` be **NULL**?

**Comment by EgorBo** [comment]
> As far as Iunderstand, after InterlockedCompareExchangeT pointer g_pUniqueStackCrst is always equal to Attempt

After `InterlockedCompareExchangeT` it's either `Attempt` we've just allocated or whatever that was set in parallel and have won the race condition (in that case we deallocate our local `Attempt`).

> And what happens if memory allocation fails?

Of what specifically? Presumably, if an allocation fails we're in trouble anyway
