### ISSUE TITLE
JIT: Addressing mode is not recognized properly

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#92861]
```cs
void Test(int* a, int i) => a[i + 1] = 42;
```
Emits:
```asm
       inc      edx
       movsxd   rax, edx
       mov      dword ptr [rcx+4*rax], 42
```
Expected:
```asm
       movsxd   rax, edx
       mov      dword ptr [rcx+4+4*rax], 42
```

It's important to "contain" the constant offset for proper vectorization in https://github.com/dotnet/runtime/pull/92852

**Comment by jakobbotsch** [comment]
Are they equivalent? One has the cast before the addition, the other has it after.

**Comment by EgorBo** [comment]
> Are they equivalent? One has the cast before the addition, the other has it after.

Do you mean for checked context?

**Comment by jakobbotsch** [comment]
No, I mean that the "expected" codegen in your example behaves differently from the "actual" codegen when `i == int.MaxValue`.
