### ISSUE TITLE
JIT Arm64: Incorrectly optimizes out narrowing

### ISSUE THREAD

**Issue by CallumDev** [dotnet/runtime#92865]
### Description

Arm64 JIT in release mode eliminates a long to int conversion when used to access an array, even though the upper bits of the long may contain data. This causes an AccessViolationException to occur.

### Reproduction Steps

Run the test case (reduced from [WattleScript](https://github.com/WattleScript/wattlescript/blob/af640a2a91512f21603d91ffd1cd756a7c5bd552/src/WattleScript.Interpreter/Execution/VM/Instruction.cs)) as a console app in release mode `dotnet run -c Release`

```cs
using System.Runtime.CompilerServices;
struct TwoValues
{
    ulong _data;
    public int NumVal => (int) (_data >> 7);
    
    public TwoValues(int numval)
    {
    	_data = (ulong) (0xFFFUL << 39) |
		((ulong) (uint) numval) << 7;
    }
}

static class MainClass
{
	static readonly string[] strings = {
		"hello",
		"world",
		"37",
		"times"
	};
	static TwoValues[] data = new TwoValues[6];
	public static void Main(string[] args)
	{
		data[3] = new TwoValues(0);
		data[4] = new TwoValues(1);
		Run(3);
		Run(4);
	}
	
	[MethodImpl(MethodImplOptions.NoInlining)]
	static void Run(int index)
	{
		Console.WriteLine(strings[data[index].NumVal]);
	}
}
```

### Expected behavior

Program should print:

hello
world

x86_64 release mode behaviour, and all platforms debug behaviour

### Actual behavior

Program generates access violation exception

### Regression?

Worked ok with .NET 6

### Known Workarounds

Narrow type manually with `& 0xFFFFFFFF`

### Configuration

Ubuntu 23.04
dotnet SDK 7.0.111
arm64 (ARMv8.0, Raspberry Pi 400)

**Comment by EgorBo** [comment]
Looks like the bug is in GenIntCastDesc

**Comment by CallumDev** [comment]
Is this eligible for backport to 7.0 given it segfaults instead of IndexOutOfRangeException?

**Comment by CallumDev** [comment]
While it won't probably change anything, .NET 7 is still in active support and tiering is the default configuration. The wind down of support isn't meant to happen until Dec, being those 6 months before EOL. Surely a crash bug like this falls under the scope of active support?
