### ISSUE TITLE
[mono][jit] Zero SIMD vectors with movi on arm64

### ISSUE THREAD

**Issue by jandupej** [dotnet/runtime#92873]
The reverse engineering document (https://dougallj.github.io/applecpu/firestorm.html) does not indicate that M1 recognizes `eor v0,v0,v0` as a zeroing idiom (like an x64 CPU would). Instead, there is the `movi` instruction (https://developer.arm.com/documentation/dui0801/l/A64-SIMD-Vector-Instructions/MOVI--vector---A64-?lang=en) that can initialize all lanes of a SIMD vector. Dougall Johnson's document shows that for zero, this is internally resolved with register renaming.

Also use this for `OP_XONES`.

**Comment by EgorBo** [comment]
Oh, interesting, looks like `mov x, #0` is also better than `mov x, xzr` on Apple, e.g.: https://godbolt.org/z/6rh4rn5G3
