### ISSUE TITLE
Implement real fix for C5271 in IJW test build

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#92879]
Recent VS upgrade introduces C5271, and causes a build break like this:

```
src\native\corehost\test\ijw\ijw.cpp(6): warning C5271: consider replacing #using <System.Console.dll>  with command line argument /FU "F:\dotnet\runtime2\.dotnet\packs\Microsoft.NETCore.App.Ref\8.0.0-rc.1.23414.4\ref\net8.0\System.Console.dll"
src\native\corehost\test\ijw\ijw.cpp(7): warning C5271: consider replacing #using <System.Runtime.Loader.dll>  with command line argument /FU "F:\dotnet\runtime2\.dotnet\packs\Microsoft.NETCore.App.Ref\8.0.0-rc.1.23414.4\ref\net8.0\System.Runtime.Loader.dll"
```

https://github.com/dotnet/runtime/pull/92878 disables the warning. This issue is to track implementing a real fix for this and removing the warning disable.

**Comment by GrabYourPitchforks** [comment]
FYI this issue causing build failures in the **release/\*** branches because https://github.com/dotnet/runtime/pull/92878 exists only in main.
