### ISSUE TITLE
[browser] Rollup removes `webpackIgnore` comments in release builds

### ISSUE THREAD

**Issue by maraf** [dotnet/runtime#92888]
All `/* webpackIgnore: true */` comments are removed in Release builds, in Debug builds they remain in-place

**Comment by pavelsavara** [comment]
We could try to add `!` like `/*! webpackIgnore: true */`
Or we could use https://github.com/terser/terser#format-options `comments` callback function if above doesn't help

**Comment by maraf** [comment]
I quickly tried the `comments`, but it seems that the terser plugin accepts minify options, not format options
