### ISSUE TITLE
Excessive zero extension

### ISSUE THREAD

**Issue by OwnageIsMagic** [dotnet/runtime#92887]
### Description

```c#
[MethodImpl(MethodImplOptions.NoInlining)]
static bool isDigit(char c)
{
    return ((uint)(c - 48u)) <= 9u;
}

static bool call(char c)
{
    return isDigit(c);
}
```
```asm
// coreclr trunk-20230907+17b60e35528ec0f1eba8a6606168412738bade59

Cc:isDigit(ushort):ubyte (FullOpts):
       movzx    rax, di
       add      eax, -48
       cmp      eax, 9
       setbe    al
       movzx    rax, al
       ret      

Cc:call(ushort):ubyte (FullOpts):
       movzx    rdi, di
       tail.jmp [Cc:isDigit(ushort):ubyte]
```

https://godbolt.org/z/hGq7TjdjY

### Analysis

I think at least 2 of `movzx` here can be eliminated and 32 bit regs used (Clang is doing this). Or it is part of managed ABI?

**Comment by jakobbotsch** [comment]
Yes, it's part of the managed calling convention. In the managed calling convention the callee is responsible for widening the return value. It means for example that .NET can generate more efficient code than Clang for the caller instead:
https://godbolt.org/z/8o331dEYq

It's one of the few places where the managed ABI differs from the platform ABI. Generally we follow the same ABI as the underlying platform.

**Comment by OwnageIsMagic** [comment]
@jakobbotsch what about using 32bit regs? They don't require `REX` prefix, so better binary size\code locality.

**Comment by jakobbotsch** [comment]
The JIT already prefers registers that are encodable without REX prefix. If you are referring to `movzx rax, al` then we actually encode that as `movzx eax, al`, we just display it as the full size register always since it's equivalent.

**Comment by OwnageIsMagic** [comment]
@jakobbotsch oh, it kinda confusing. Thanks for answers.
