### ISSUE TITLE
Consider using memfd_create instead of shm_open in MemoryMappedFile if it's available

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#92905]
When this code was originally written, memfd_create didn't exist. Now that it does, we can consider using it instead of shm_open if it's available (e.g. on Linux)

**Comment by gfoidl** [comment]
From [Chromium source](https://source.chromium.org/chromium/chromium/src/+/main:third_party/perfetto/src/tracing/ipc/memfd.cc;l=52-53;drc=15fd919ebc4222f581aeaec71fc2c63092796ad1):
> ```
> // Check kernel version supports memfd_create(). Some older kernels segfault
> // executing memfd_create() rather than returning ENOSYS (b/116769556).
> ```
But I don't know if Linux kernels older than 3.17 are still in use / supported or meet the .NET baseline (can't find that info right now :-()

**Comment by adamsitnik** [comment]
cc @tmds
