### ISSUE TITLE
[API Proposal]: Change `System.String..ctor(System.SByte*)` et all to use UTF-8 on Windows

### ISSUE THREAD

**Issue by DaZombieKiller** [dotnet/runtime#92919]
### Background and motivation
Currently, the `sbyte*` constructors available for `System.String` will use the active codepage on Windows and UTF-8 on all other platforms. The constructors [are documented](https://learn.microsoft.com/en-us/dotnet/api/system.string.-ctor?view=net-7.0#system-string-ctor(system-sbyte*)) to use whatever encoding is specified by `Encoding.Default`, which is UTF-8 on all platforms today:
![image](https://github.com/dotnet/runtime/assets/6316315/6f0838f9-11b1-4cb6-b020-cc4afb872710)
Either the documentation requires an update, or the constructor should be made consistent on all platforms.

### API Proposal
Change the behavior of the following APIs:
```cs
namespace System;

public partial class String
{
    public unsafe String(sbyte* value);
    public unsafe String(sbyte* value, int startIndex, int length);
}
```
To interpret the input buffer as a UTF-8 sequence on Windows for consistency with the documentation and other platforms.

### Risks
If any callers are relying on this Windows-specific behavior and are executing the code in an environment where the active codepage is not UTF-8, they will encounter different behavior for input containing Unicode.

**Comment by tannergooding** [comment]
This probably needs input from @dotnet/interop-contrib and @GrabYourPitchforks

**Comment by jkoritzinsky** [comment]
A breaking change here might be too wide, especially given the fact that a failure mode would be pretty inscrutable. However, in the interop space, we generally direct people to the Marshal APIs. I can't find the tool, but if we could see the relative usage numbers of these constructors vs Marshal.PtrToStringAnsi, that might assuage my concerns.

**Comment by AaronRobinsonMSFT** [comment]
The biggest concern for me would be C++/CLI. Typical interop scenarios, as mentioned by @jkoritzinsky, should be conditioned to use the suite of `Marshal` APIs or some of the new marshalling types under `System.Runtime.InteropServices.Marshalling`.

/cc @tgani-msft

**Comment by MichalPetryka** [comment]
I feel like the breaking changes from this far outweigh any benefits, as such I think that changing the documentation would make more sense.

**Comment by tgani-msft** [comment]
C++/CLI resolves a const char* argument to the int8* constructor of System.String. Any change here would be a break from previous behavior. While C++ has had UTF-8 encoded string literals for a while and C++20 now has the new std::u8string class, char8_t has not been added to C++/CLI yet. Even if it were, System.SByte is alread mapped to 'signed char' and changing it to map to char8_t would be a breaking change. 

I would recommend not perturbing this API.

**Comment by AaronRobinsonMSFT** [comment]
> C++/CLI resolves a const char* argument to the int8* constructor of System.String. 

This makes this proposal a non-starter. We should update the doc as suggested in https://github.com/dotnet/runtime/issues/92919#issuecomment-1747019396.

**Comment by DaZombieKiller** [comment]
(I should clarify that updating the documentation was intended to be part of this proposal as an alternative, but I suppose I should have made it clearer by adding an alternatives section instead of just mentioning it in passing)
