### ISSUE TITLE
CI failure: The file crossgen2.pdb to be packed was not found on disk.

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#92930]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=425474
Build error leg or test failing: Build / Installer Build and Test coreclr  freebsd_x64 Release / Build
Pull request: https://github.com/dotnet/runtime/pull/92852

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "The file '/__w/1/s/artifacts/bin/crossgen2_publish/x64/Release/linux-x64/publish/crossgen2.pdb' to be packed was not found on disk.",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=425474
**Error message validated:** `The file '/__w/1/s/artifacts/bin/crossgen2_publish/x64/Release/linux-x64/publish/crossgen2.pdb' to be packed was not found on disk.`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 10/3/2023 12:06:47 PM UTC

**Comment by EgorBo** [comment]
Failing in other PRs as well e.g. https://github.com/dotnet/runtime/pull/92926

**Comment by ViktorHofer** [comment]
@jkoritzinsky seems like a regression of https://github.com/dotnet/runtime/pull/92826. I unfortunately overlooked that error when merging the PR.
