### ISSUE TITLE
ChangeDocumentationFileForPackaging causes incremental build issues inside VS

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#92940]
This target picks the intellisense file from the `Microsoft.Private.Intellisense` package : https://github.com/dotnet/runtime/blob/88f25474334bfb0da10e0b5acb0219a64a04828b/eng/intellisense.targets#L43-L51

Because of using that prebuilt asset, the earliest output in the output directory dates back to when the package was last updated which results in incremental build issues.

> WARNING: Potential build performance issue in 'System.Text.RegularExpressions.csproj'. The project does not appear up-to-date after a successful build: Input 'C:\git\runtime2\Directory.Build.props' is newer (10/3/2023 3:15:00 PM) than earliest output 'C:\git\runtime2\artifacts\bin\System.Text.RegularExpressions\Debug\net9.0\System.Text.RegularExpressions.xml' (9/18/2023 11:26:32 PM), not up-to-date. See https://aka.ms/incremental-build-failure.

@carlossanlop @ericstj

**Comment by ericstj** [comment]
Are we ever using that file for an up-to-date check or is this just the tooling issue?

I don't see inputs/outputs on the target you mention, so I'm inclined to think the latter.

Regardless, if we want to quiet this warning we should just use `Touch` on the copied file.

**Comment by ViktorHofer** [comment]
This is a warning emitted by the [up-to-date check by VS](https://github.com/dotnet/project-system/blob/main/docs/up-to-date-check.md), not the incremental build feature from msbuild. cc @drewnoakes

**Comment by ericstj** [comment]
@ViktorHofer why not try setting `UpToDateCheckInput="false"` metadata on that `DocFileItem` as suggested in the doc and see if it resolves the issue?

Alternatively you can add a `Touch` to a target that would update the timestamp after the file is copied out of the package.

**Comment by ViktorHofer** [comment]
While the warning is emitted by the up-to-date check feature, I believe this really prevents msbuild to not requeue a build:

<img width="1598" alt="image" src="https://github.com/dotnet/runtime/assets/7412651/85aa4b9d-6ec3-468c-a2c0-9df91a205a64">

Even with putting `UpToDateCheckInput="false"` on that item, VS always builds the project (incrementally) instead of skipping it (because it should be up-to-date).

**Comment by ericstj** [comment]
I see, well if we can't get that suppression to work, then the right thing to do would be to have that target copy it and touch the copy.  It should put it somewhere in a subfolder in obj so that we can still preserve the compiler-emitted one.

**Comment by ViktorHofer** [comment]
@carlossanlop can you help with that? The target should be in intellisense.targets.
