### ISSUE TITLE
[API Proposal]: Support true singletons through IServiceCollection

### ISSUE THREAD

**Issue by jochenz** [dotnet/runtime#92957]
### Background and motivation

During host startup, we configure the `IServiceCollection`. Sometimes, we want to add singletons and we want to make sure that they are true singletons, not that someone else already registered the same dependency earlier in the call stack.

It looks like `TryAddSingleton` is a good option for that, but it really isn't:

- it's a kind of silent failure if you don't throw when it returns false
- it depends on the order of execution of two invocations which one wins (a simple swap of some lines of code might provide suprising results)
- it requires a developer's attention to detail to detect potential conflicts (if at all possible to detect that from his perspective on the code)

Basically, if you want to add a singleton, you should only have to write `AddSingleton<T>` or `AddSingleton<TInterface, TImpl>` and be confident that you have a **true** singleton, which is not the case now.

If in have the line `services.AddSingleton<T>()` multiple times in your code (no matter how far apart) and they get invoked twice, the `ServiceCollection` will create two instances of what you expect is a singleton type.

The behaviour of 

```csharp
// written by first developer
services.AddSingleton<TInterface, TImpl1>();
// written by second developer, somewhere deep down in an assembly
services.AddSingleton<TInterface, TImpl2>();
```

is even more problematic, since a request for `TInterface` will return `TImpl2`. Developer 1 will be really surprised about this and developer 2 will probably not realize that he has overruled the intentions of developer 1.

Therefore, I think we need to be able to enforce a stricter rule on singletons, on a selected scope (e.g. our own assemblies), so we don't introduce backwards compatibility issues.

### API Proposal

```csharp
using System;
using System.Collections.Generic;

namespace Microsoft.Extensions.DependencyInjection;

public interface IServiceCollection : IList<ServiceDescriptor>
{
    IServiceCollection EnforceStrictSingletonsWhen(Func<Type, bool> typeFilter);
}
```

### API Usage

```csharp
namespace Demo;

// predicate to check if type is in demo assembly
bool InDemoAssembly(Type type) => type.Namespace?.StartsWith("Demo") ?? false;

// enforce strict singletons for the demo assembly
services.EnforceStrictSingletonsWhen(InDemoAssembly);

services.AddSingleton<X>();
// boom! throws exception, not allowed, no more silent unexpected behaviour
services.AddSingleton<X>();

class X {}
```

### Alternative Designs

- As an extension method, but I don't see how it can be implemented then...
- As an overload or options on `BuildServiceProvider()`, so it is not enforcing strict singletons during registration, but instead during container build.

### Risks

Of course backwards compatibility of an existing interface. And not just a tiny one which isn't often used, but a very core one...

Functionally, it is backwards compatible (at least I think so).
Binary, it of course isn't.

**Comment by jochenz** [comment]
I now see that I first should have started a discussion on this topic, sorry about that...

**Comment by jochenz** [comment]
I've started [a discussion](https://github.com/dotnet/runtime/discussions/92959) on this topic.

**Comment by steveharter** [comment]
Closing this for now; will re-open if the discussion nets a path forward.

Basically, users depend on the replacement mechanism today so there would need to be an opt-in validation mechanism. If that is done, code outside of the user's knowledge may not make the same assumptions and rely on replacement.
