### ISSUE TITLE
crossgen2.pdb not found on disk for Build Installer Build and Test coreclr freebsd_x64 Release

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#92961]
### Error Blob

```json
{
  "ErrorMessage": "The file '/__w/1/s/artifacts/bin/crossgen2_publish/x64/Release/linux-x64/publish/crossgen2.pdb' to be packed was not found on disk.",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": true
}
```

 ### Known issue validation
**Build: :mag_right:** 
**Result validation: :warning:** Validation could not be done without an Azure DevOps build URL on the issue. Please add it to the "**Build: :mag_right:**" line.
**Validation performed at:** 10/3/2023 7:06:13 PM UTC

**Comment by jkoritzinsky** [comment]
Fixed by https://github.com/dotnet/runtime/pull/92948
