### ISSUE TITLE
Missing Microsoft.Extensions.* package README files

### ISSUE THREAD

**Issue by Tratcher** [dotnet/runtime#92963]
(Fork of https://github.com/dotnet/aspnetcore/issues/48392)

The NuGet team has noticed that your package on NuGet.org is missing a README file. Please take a moment to add a README file to your package repository.

Our customer research indicates that one of the top problems that package consumers face is insufficient package documentation such as README files. Adding a README file to your package will help users quickly understand what the package is and what it does. Since your README will be the first impression for users when they view your package on NuGet.org, it is crucial for authors to write and include high-quality READMEs for their packages.

Please add a README file to your package so that users can understand at a glance what the package contains and how to use it.

There is no specific format or structure to a good README – instead it’s about effectively communicating the purpose and functionality of your package to potential users. If you are unsure of where to start, check out our [blog post](https://devblogs.microsoft.com/nuget/write-a-high-quality-readme-for-nuget-packages/) for some README best practices and a template file.
If you are new to NuGet README, learn more about [how to add a README to your NuGet Package](https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/).

### Additional context

Your feedback is very important to us. If you experience any issue using READMEs or have ideas for improvements – please feel free to contact us by replying to this issue

### README Template
[https://raw.githubusercontent.com/lyndaidaii/NuGetReadMeTemplate/main/README.md](https://raw.githubusercontent.com/lyndaidaii/NuGetReadMeTemplate/main/README.md)

Package Name | Package Version | Status | Done
-- | -- | -- | --
microsoft.extensions.caching.memory | 7.0.0
microsoft.extensions.configuration | 7.0.0
microsoft.extensions.configuration.abstractions | 7.0.0
microsoft.extensions.configuration.binder | 7.0.4
microsoft.extensions.configuration.environmentvariables | 7.0.0
microsoft.extensions.configuration.fileextensions | 7.0.0
microsoft.extensions.configuration.json | 7.0.0
microsoft.extensions.configuration.usersecrets | 7.0.0
microsoft.extensions.dependencyinjection | 7.0.0
microsoft.extensions.dependencyinjection.abstractions | 7.0.0
microsoft.extensions.hosting | 7.0.1
microsoft.extensions.hosting.abstractions | 7.0.0
microsoft.extensions.hosting.windowsservices | 7.0.0
microsoft.extensions.http | 7.0.0
microsoft.extensions.logging | 7.0.0
microsoft.extensions.logging.abstractions | 7.0.0
microsoft.extensions.logging.console | 7.0.0
microsoft.extensions.options | 7.0.1
microsoft.extensions.options.configurationextensions | 7.0.0

**Comment by tarekgh** [comment]
@ViktorHofer is tracking that in https://github.com/dotnet/runtime/pull/92228 for all FX packages. @ViktorHofer will be good to double check if your list is missing any package from what listed here. I'll let you decide if you want to keep this issue opened or your tracking is good enough.

**Comment by ViktorHofer** [comment]
Yes, all of the packages in the above list are already tracked either by https://github.com/dotnet/runtime/pull/91210 or https://github.com/dotnet/runtime/pull/92228.

I would prefer to close this issue over https://github.com/dotnet/runtime/pull/92228 which tracks the remaining work.
