### ISSUE TITLE
What really defines the result of typeof(MyType).GetHashCode()?

### ISSUE THREAD

**Issue by amather** [dotnet/runtime#92973]
I maneuvered myself into a situation that breaks DependencyInjection, resulting in the questions:

- Is this known, but an unsupported scenario?
**or**
- Does DependencyInjection unknowingly depend too much on `Type.GetHashCode()` as it is used to _uniquely_ identify the types it wants to instantiate/provide?

Most likely my issue is related to the fact that I load assemblies left and right and tried to build a modular application that can run a ASP.NET minimal API from a dynamically loaded assembly that itself can load additional services from other assemblies. 

So at one point I add a Singleton to a service collection like `services.AddSingleton<IKDFService, KDFService>();` but the ASP.NET endpoint cannot resolve that service, even though it exists in the `ServiceProvider` that powers the endpoint invocation.

I debugged it down to the fact that the `ServiceProvider` uses `ServiceIdentifier` internally for `Dictionary` keys and `ServiceIdentifier` implements `IEquatable` [using the `GetHashCode()` of the `Type` that is about to be resolved](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceIdentifier.cs#L53).

And this `GetHashCode()` on the type returns a different result when the endpoint is invoked from when then type is originally added to the `IServiceCollection`. Which most likely means that, whatever was originally added/available, was another instance/view of the type (as seen by the runtime?).

I've tried different ways of assembly loading, e.g. `Assembly.Load()`, `Assembly.LoadFile()`, `AssemblyLoadContext.Default.LoadFromAssemblyPath()`, etc. Before starting ASP.NET as well as at the endpoint itself, `AppDomain.CurrentDomain.GetAssemblies()` reports the questionable assembly being loaded only once. It's also a project dependency, so could it be that it is loaded by the runtime, yet not reported under `GetAssemblies()`?

Since I'm already at 15ish projects in the solution, giving you an overview or a reproducible example is hard (I've tried). There's a console application loading assemblies that can act as program entry points, but also some, possibly the same assemblies, that provide services that will run in their own thread. The program entry points themself load assemblies and instantiating and calling types (e.g. for providing API endpoints), 

So while I don't expect anyone to help me assist in this madness I've created, I'd highly appreciate anyone who can tell me more about situations in which `typeof(MyType).GetHashCode()` can produce different results during the same application run, though called from different assemblies. Thank you!

 
PS: I'm on net8-rc1

PPS: [asked on StackOverflow first](https://stackoverflow.com/q/77225110/1649108), but looks like that's a question better asked directly here...

**Comment by EgorBo** [comment]
My guess that it can happen with unloadable ALCs, e.g. you load an assembly context with `Foo.Bar` type, its `GetHashCode` is `0x1234`, then you unload that ALC and load again - it's going to have a different `GetHashCode` for `Foo.Bar` now.

**Comment by amather** [comment]
@EgorBo thank you! I've just rechecked every corner and indeed, there was still an `Assembly.LoadFile()` call in an getter. Refactoring everything so that loads happen only with `AssemblyLoadContext.Default.LoadFromAssemblyPath()` fixed the issue!
