### ISSUE TITLE
DllImport on Linux ignoring an already loaded module

### ISSUE THREAD

**Issue by MichalSanak** [dotnet/runtime#92995]
### Description

On Linux, using a `[DllImport]` attribute, the runtime seems to always be trying to locate and load the module when an imported method is called for the first time, even if the module has already been loaded and is visible in `Process.GetCurrentProcess().Modules`.
What I am trying to achieve is preloading the module prior to calling any imported function. The reason is that I have multiple versions of the same library in different locations, and want to have control over which library is used at run time.
The preloading works perferctly on Windows, but does not on Linux.

### Reproduction Steps

We have a simple library import:

```c#
public static class ImportedLibrary
{
    [DllImport("my_module.so", EntryPoint = "test")]
    public static extern void test();
}
``` 

We preload the library from a location that is not on the libraries search path:
```c#
NativeLibrary.Load("/home/my_lib/my_module.so");
```

We call the imported function:
```c#
ImportedLibrary.test();
```

### Expected behavior

`ImportedLibrary.test()` call should succeed, as the library is loaded in the process memory.

### Actual behavior

On Windows, this works.
On Linux, a `System.DllNotFoundException` exception is thrown, as `DllImport` is trying to locate `my_module.so` on library search paths.

### Known Workarounds

use `NativeLibrary.SetDllImportResolver`

### Configuration

OS: Debian GNU/Linux 11 (bullseye)
Architecture: x64
Microsoft.NETCore.App 7.0.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by MichalStrehovsky** [comment]
Why not use [`NativeLibrary.SetDllImportResolver`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary.setdllimportresolver?view=net-7.0) and resolve the DLL yourself? The API was designed for these use cases.

**Comment by MichalSanak** [comment]
Hi Michal, thanks, yes, that is a workaround that we have used and I forgot to mention it. Still would love to know if this behaviour is expected though.

**Comment by MichalStrehovsky** [comment]
I think you're running into OS-specific loader behaviors. On all OSes, the runtime will eventually call into OS APIs. On Windows, [the docs say](https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order) that the loaded module list is searched as one of the very first things. On Linux, the behaviors will be as documented there (not going to search for it).

> is a workaround

It's not a workaround, it's the correct fix.

**Comment by vitek-karas** [comment]
I can't comment on all Linux behavior, but we ran into this in the hosting layer. In short at least on some Linuxes the loader will only return the same module if it's asked to load the exact same file again - by file path. On Windows you can call `LoadLibrary("libname.dll")` and it would return the already loaded one. On Linux it won't, you have to know the full path to the library, then it will return the already loaded module.
