### ISSUE TITLE
Multi-platform compilation: System.Configuration.ConfigurationManager.GetSection throws error on NetCoreApp

### ISSUE THREAD

**Issue by yvinap** [dotnet/runtime#930]
**Background:**
We are in the process of migrating .Net application to .Net Core.
As a strategy, we would like to keep the existing functionality intact on Full framework while migrating portion of the application to .Net Core.  Full application would support .services over Net remoting and REST API whereas .Net core application will only support REST API services.
We have decided to keep the same code base for entire application and support compilation on multiple platforms (NetcoreApp2.1 and Net472).  
There is a single application configuration file. Most of the components are dependent on the information  stored in this file. Thus we would like to retain the single configuration file for both platforms.
I used System.Configuration.ConfigurationManager package to access configuration information.

**Issue:** 
ConfigurationManager.GetSection(string) throws exception on .Net core platform whereas it works fine on Net472.
Error Message: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: Unrecognized configuration section system.runtime.remoting

**Work around tried so far:**
ConfigurationManager.OpenExeConfiguration(configurationUserLevel).GetSection(string) works perfect on both the platforms for fetching the same section

**Sample Application:**
See attached sample application.
[TestConfigManager.zip](https://github.com/dotnet/corefx/files/2081728/TestConfigManager.zip)

**Comment by danmosemsft** [comment]
@JeremyKuhne is the fix here simply to add
```xml
  <section name="system.runtime.remoting" type="System.Configuration.IgnoreSection, System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" allowLocation="false" />
        <section name="windows" type="System.Configuration.IgnoreSection, System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" allowLocation="false" />
```
to these
https://github.com/dotnet/corefx/blob/master/src/System.Configuration.ConfigurationManager/src/System/Configuration/ImplicitMachineConfigHost.cs#L78

**Comment by JeremyKuhne** [comment]
> is the fix here simply to add

Yes. And add tests, of course. The repro [above ](https://github.com/dotnet/runtime/issues/930#issuecomment-412988350) should be relatively easy to add a test for. Loading a custom `Configuration` with that in it via `ConfigurationManager.OpenExeConfiguration` (as other tests do) should suffice.

**Comment by danmosemsft** [comment]
@yvinap any interest in offering a PR - i know this is old now...

**Comment by ckadluba** [comment]
@danmosemsft I would try to fix this. Could you please assign it to me?

**Comment by ckadluba** [comment]
I tried now to add a unit test to System.Configuration.ConfigurationManager.Tests.csproj to reproduce the error within the runtime. Unfortunately no exception ocurrs when the test is executed while I was able to reproduce the error with the TestConfigManager sample application attached above, even when I upgraded that sample app to the latest nightly build of dotnet runtime 5.0 to have a better comparability to my unit test. 

I added my test in ```ConfigurationTests.cs``` and it looks like this.

```csharp
        [Fact]
        public void GetSectionReturnsRemotingSettings()
        {
            using (var temp = new TempConfig(TestData.SystemRuntimeRemotingConfig))
            {
                ConfigurationManager.OpenExeConfiguration(temp.ExePath);
                var appSettings = ConfigurationManager.AppSettings;
                Assert.NotNull(appSettings);
            }
        }
```

I defined ```TestData.SystemRuntimeRemotingConfig``` in ```TestData.cs``` like the following.

```csharp
        public static string SystemRuntimeRemotingConfig =
@"<?xml version='1.0' encoding='utf-8' ?>
<configuration>
  <system.runtime.remoting>
    <application>
      <channels>
        <channel ref='tcp' port='1111' />
      </channels>
    </application>
  </system.runtime.remoting>
</configuration>";
```

When debugging both programs I found differences during the initialization of the ConfigurationManager between the TestConfigManager sample and my unit test but I'm not yet shure why.

I will investigate it further but any clues are welcome.

**Comment by deeprobin** [comment]
Is this still reproducable on .NET 6/7?

**Comment by buyaa-n** [comment]
still reproduceable with the attached project on .NET 6/7

**Comment by mpidash** [comment]
> > is the fix here simply to add
> 
> Yes. And add tests, of course. The repro [above ](https://github.com/dotnet/runtime/issues/930#issuecomment-412988350) should be relatively easy to add a test for. Loading a custom `Configuration` with that in it via `ConfigurationManager.OpenExeConfiguration` (as other tests do) should suffice.

As @ckadluba pointed out, using `ConfigurationManager.OpenExeConfiguration` is not going to work for testing as it uses `ClientConfigurationHost` which directly constructs a `Configuration` leading to `InternalConfigRecord._isDesignTime` set to `true`. This means that local errors are being ignored and no exception is thrown. This is also observed in the original repro from @yvinap.

When calling `ConfigurationManager.GetSection`, a `ClientConfigurationSystem` is used which internally creates the `IInternalConfigRecord` with a `ConfigSystem`, setting `InternalConfigRecord._isDesignTime` to `false`. This then leads to an exception being thrown when encountering `system.runtime.remoting` as local errors are not ignored.

I propose to use similar tests as in `ConfigurationPathTests`:
```csharp
[ConditionalFact(typeof(RemoteExecutor), nameof(RemoteExecutor.IsSupported))]
public void RuntimeAppSettingsSystemRuntimeRemotingSectionIsSupported()
{
    using (var temp = new TempConfig(TestData.SystemRuntimeRemotingSectionConfig))
    {
        RemoteExecutor.Invoke((string configFilePath) => {
            AppDomain.CurrentDomain.SetData("APP_CONFIG_FILE", configFilePath);
            Assert.NotNull(ConfigurationManager.GetSection("system.runtime.remoting"));
        }, temp.ConfigPath).Dispose();
    }
}
```

I would be interested in providing a PR for this, so please assign this issue to me.
