### ISSUE TITLE
ILLink fails to resolve method's base interface method if the interface method doesn't have newslot

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#93008]
This is based of a repro from F#. The interface definition of a method in F# looks like this:
```
.method public hidebysig specialname abstract virtual 
	instance valuetype MyLib.OS get_OS () cil managed 
{
} // end of method IPlatformData::get_OS
```

Note that it doesn't have a `newslot` flag.

Similar interface definition in C# looks basically the same except that it has `newslot` as well.

When illink resolves methods and their base methods, it will not consider interface methods which don't have `newslot` on them (I don't know why).
https://github.com/dotnet/runtime/blob/64862501b238512db10eff9ed4b05ba94412974d/src/tools/illink/src/linker/Linker/TypeMapInfo.cs#L154

As a result, implementing the above interface in C# and trimming the result will create the implementation type without any of the interface method implementations.

**Comment by vitek-karas** [comment]
@MichalStrehovsky as the expert on IL - I assume it's correct to have an interface method without `newslot`... and thus illink should fix this.

**Comment by edgarfgp** [comment]
cc @vzarytovskii

**Comment by vzarytovskii** [comment]
I'm not sure, but highly likely that it's a bug. Need to consult with spec though.

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky as the expert on IL - I assume it's correct to have an interface method without `newslot`... and thus illink should fix this.

Reading through the spec, I don't see the bit required anywhere. I guess it's implicit because nothing else than introducing a new slot makes sense.

**Comment by charlesroddie** [comment]
> I guess it's implicit because nothing else than introducing a new slot makes sense.

That is consistent with F# which treats non-final methods of interface types as IsNewSlot even if they don't have it marked. https://github.com/dotnet/fsharp/pull/11426/files

**Comment by charlesroddie** [comment]
> Reading through the spec, I don't see the bit required anywhere.

It seems that a `newslot` requirement exists in a [proposed specification change to ECMA-335](
https://github.com/dotnet/runtime/blob/4bdd4905e85f26201ffd2126c013dce0311fb208/docs/design/specs/Ecma-335-Augments.md?plain=1#L430) around default interface methods:

> **Section** "II.12.1 Implementing interfaces" is extended to say all virtual instance methods defined on an interface must be abstract, be marked with newslot and not have an associated MethodImpl which uses the method as its Impl, or final without newslot and with a MethodImpl that uses the method as its Impl entry.

Should F# conform to the proposed specification here @vzarytovskii ?

**Comment by vzarytovskii** [comment]
> > Reading through the spec, I don't see the bit required anywhere.
> 
> 
> 
> A `newslot` requirement exists in a [proposed specification change to ECMA-335](
> 
> https://github.com/dotnet/runtime/blob/4bdd4905e85f26201ffd2126c013dce0311fb208/docs/design/specs/Ecma-335-Augments.md?plain=1#L430) around default interface methods:
> 
> 
> 
> > **Section** "II.12.1 Implementing interfaces" is extended to say all virtual instance methods defined on an interface must be abstract, be marked with newslot and not have an associated MethodImpl which uses the method as its Impl, or final without newslot and with a MethodImpl that uses the method as its Impl entry.
> 
> 
> 
> Should F# conform to the proposed specification here @vzarytovskii ?

Probably yes, unless we rely on existing codegen somewhere (where we miss sigdata) and it'll be a breaking change.

**Comment by ivanpovazan** [comment]
I tested the same sample with ILC and NativeAOT trimming does not seem to have this problem. Therefore, I believe we should try to fix this in the linker.

**Comment by vitek-karas** [comment]
F# people on this thread - when I run the repro for this through the trimmer I get:
```
resource ILLink.Substitutions.xml in FSharp.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a(3,6): warning IL2040: FSharp.Core: Could not find embedded resource 'FSharpOptimizationCompressedData.FSharp.Core' to remove in assembly 'FSharp.Core'.
resource ILLink.Substitutions.xml in FSharp.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a(5,6): warning IL2040: FSharp.Core: Could not find embedded resource 'FSharpSignatureCompressedData.FSharp.Core' to remove in assembly 'FSharp.Core'.
```

That seems like a bug in the `FSharp.Core` - if that assembly is meant to be trim compatible, it should not produce warnings on its own.

**Comment by vzarytovskii** [comment]
> F# people on this thread - when I run the repro for this through the trimmer I get:
> 
> ```
> resource ILLink.Substitutions.xml in FSharp.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a(3,6): warning IL2040: FSharp.Core: Could not find embedded resource 'FSharpOptimizationCompressedData.FSharp.Core' to remove in assembly 'FSharp.Core'.
> resource ILLink.Substitutions.xml in FSharp.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a(5,6): warning IL2040: FSharp.Core: Could not find embedded resource 'FSharpSignatureCompressedData.FSharp.Core' to remove in assembly 'FSharp.Core'.
> ```
> 
> That seems like a bug in the `FSharp.Core` - if that assembly is meant to be trim compatible, it should not produce warnings on its own.

These are _kind of_ expected, since we can have both compressed and uncompressed resources in F# assemblies, it used it work, but then warning was added. It can be ignored, we will remove uncompressed onces in time.

**Comment by vitek-karas** [comment]
> These are kind of expected, since we can have both compressed and uncompressed resources in F# assemblies, it used to work, but then warning was added by default. It can be ignored, we will remove uncompressed onces in time.

Would it be possible to build the assembly in such a way that it only has the substitution entries for resources which are actually part of it?

For example for System.Private.CoreLib there are multiple pieces of `ILLink.Substitutions.xml` which are combined at built time when we know for which target we're building the assembly so that we can pick the right pieces (not adding WASM specific substitutions to x64 build of the library for example).

**Comment by MichalStrehovsky** [comment]
>  it used to work, but then warning was added by default

FWIW this warning has been there since forever. It was probably just not tested with PublishTrimmed, only PublishAot. PublishAot currently has a bug (or feature) that it doesn't generate these warnings. The file format is borderline undocumented (there are docs for it in the repo only as we don't really want to inflict this XML headache on general population).

Is the contents of the resource stream for compiler internal use? This blob seems to be generated into anything the F# compiler generates. Instead of doing something special for FSharp.Core only, it would be good to get in a place where all F# libraries can have this trimmed.

This could be solved by the F# compiler embedding the substitution file to remove it into all libraries, but that is suboptimal - it would be better to just place the data where it can be trimmed naturally so that F# compiler doesn't take a dependency on this borderline undocumented file format. Nobody likes these XML files. The biggest problem with them is that they're only respected by the trimming tools and introduce a potential F5 Debug-time vs publish-time difference (what if the user app is looking for this resource for whatever wrong reason?). We typically want a publish-time warning whenever there is a potential for a behavioral difference. The XML formats are absolutely last resort because they break this fundamental expectation.

There are many options here: for example, the data could just be placed in a separate PE section (outside .NET metadata), or as data for a RVA-static field with a well known name (this would be within the .NET metadata, but if the field is unreachable, we'd trim it like any other field).

**Comment by vzarytovskii** [comment]
> > it used to work, but then warning was added by default
> 
> FWIW this warning has been there since forever. It was probably just not tested with PublishTrimmed, only PublishAot. PublishAot currently has a bug (or feature) that it doesn't generate these warnings. The file format is borderline undocumented (there are docs for it in the repo only as we don't really want to inflict this XML headache on general population).
> 

Yes, I believe this is more correct, it was on, but maybe wasn't tested with F#, or was ignored (was first discovered here: https://github.com/dotnet/runtime/pull/78034)

> Is the contents of the resource stream for compiler internal use? This blob seems to be generated into anything the F# compiler generates. Instead of doing something special for FSharp.Core only, it would be good to get in a place where all F# libraries can have this trimmed.
> 
> This could be solved by the F# compiler embedding the substitution file to remove it into all libraries, but that is suboptimal - it would be better to just place the data where it can be trimmed naturally so that F# compiler doesn't take a dependency on this borderline undocumented file format. Nobody likes these XML files. The biggest problem with them is that they're only respected by the trimming tools and introduce a potential F5 Debug-time vs publish-time difference (what if the user app is looking for this resource for whatever wrong reason?). We typically want a publish-time warning whenever there is a potential for a behavioral difference. The XML formats are absolutely last resort because they break this fundamental expectation.
> 

So, the resources are for compiler use only (for compile-time pretty much, and have no use in runtime), however we don't wan't to trim them by default, since there's a subset of cases, when people still want to trim their assemblies, but keep resoutces, mostly community tools (like formatters, analyzers sdk, REPL story, etc).

> There are many options here: for example, the data could just be placed in a separate PE section (outside .NET metadata), or as data for a RVA-static field with a well known name (this would be within the .NET metadata, but if the field is unreachable, we'd trim it like any other field).

As with above, we don't necessary want to trim them by default. For FSharp.Core, we will probably just generate the XML during build/publish, which will match which type of resource is actually used.

**Comment by vitek-karas** [comment]
> we don't necessary want to trim them by default.

But that's exactly what the XML does today - if the resource is there, the trimmer will remove it. That's what the XML tells it to do. Based on your description there are two cases:
* People just building normal apps with F# - the resources are not needed in this case and should be removed to save size.
* People using F# for some specialized tools - some of these might want to keep the resources.

If this is the goal, I personally would prefer we trim them by default but allow for an override, probably via a feature switch (like) setting. The second group (tools which want the resources) would have to opt-in to keep them if they do trim their tool.

**Comment by vzarytovskii** [comment]
> > we don't necessary want to trim them by default.
> 
> 
> 
> But that's exactly what the XML does today - if the resource is there, the trimmer will remove it. That's what the XML tells it to do. Based on your description there are two cases:
> 

I meant from all libraries (including user libraries), we don't want to generate the xml to trim out resources by default.

> * People just building normal apps with F# - the resources are not needed in this case and should be removed to save size.
> 
> * People using F# for some specialized tools - some of these might want to keep the resources.
> 
> 
> 
> If this is the goal, I personally would prefer we trim them by default but allow for an override, probably via a feature switch (like) setting. The second group (tools which want the resources) would have to opt-in to keep them if they do trim their tool.


That would be a breaking change for the second group, if they already are using it, just by upgrading the sdk, we usually don't do that.

**Comment by vitek-karas** [comment]
> I meant from all libraries (including user libraries), we don't want to generate the xml to trim out resources by default.

There are ways we could do this for all assemblies without adding specific XML into each... but that's beside the point. I wonder how much size are we discussing here... how big are these resources typically?

> That would be a breaking change for the second group, if they already are using it, just by upgrading the sdk, we usually don't do that.

We could tie this to a TFM - I agree that breaking changes just by upgrading SDK is not something we should do. But breaking changes between TFMs is something we do all the time.

**Comment by vzarytovskii** [comment]
> > I meant from all libraries (including user libraries), we don't want to generate the xml to trim out resources by default.
> 
> There are ways we could do this for all assemblies without adding specific XML into each... but that's beside the point. I wonder how much size are we discussing here... how big are these resources typically?
> 

Depending on the library, for corelib it can be substantial (half or third of the size of dll).

> > That would be a breaking change for the second group, if they already are using it, just by upgrading the sdk, we usually don't do that.
> 
> We could tie this to a TFM - I agree that breaking changes just by upgrading SDK is not something we should do. But breaking changes between TFMs is something we do all the time.

Yes, we can do that. Either way, we'll be looking into how to improve it.

**Comment by vzarytovskii** [comment]
> If there is an expectation that user code might read this, it is simply a bug to embed xml to unconditionally remove this.

There's via the compiler SDK, it reads it as part of checking/compiling pipeline. So, one example of the use-case is when there's a REPL which loads assemblies (for example, F#.Core), and uses info from blobs (type info, optimization, inlining info, etc) to evaluate user's input.

For F# core, which we distribute with SDK, we always want to trim, since it's designed to be used only in runtime, for any user scenarios, when they bundle F# core or their own libraries, we want a strict opt-in at this point.
