### ISSUE TITLE
[mono][net7] Cherrypick fixes to build runtime with Xcode 15

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#93009]
Our official builds use an older Xcode for creating .NET 7 packages, but if we ever upgrade the build machines here's what we will need to cherrypick to get net7 building with Xcode 15:

* #88261
   * Not sure if we need the App Builder changes; for sure we need the cindex.py changes
* #86256
* https://github.com/dotnet/runtime/pull/87190/files#diff-1b1edde0c18ae50547eda0255286553a9cdc5d8d2e381b6cca7db559e3bd6215 - just the offsets-tool.py changes from that PR

**Comment by lambdageek** [comment]
CoreCLR macOS builds probably need changes too, although I don't know what those might entail

**Comment by steveisok** [comment]
@akoeplinger please take care of this.

**Comment by akoeplinger** [comment]
PR is in https://github.com/dotnet/runtime/pull/93543

> Not sure if we need the App Builder changes; for sure we need the cindex.py changes

I decided not to backport the AppBuilder changes since they're only needed for tests and we probably can live without them for now.

> CoreCLR macOS builds probably need changes too, although I don't know what those might entail

I built CoreCLR with xcode 15 and it built fine without changes.

**Comment by akoeplinger** [comment]
Fixed by #93543
