### ISSUE TITLE
Cannot use Blazor 8 RC1 wasm on GitHub pages

### ISSUE THREAD

**Issue by AceHack** [dotnet/runtime#93017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I get the following errors when hosting on GitHub pages a blazor app
https://github.com/dotnet/AspNetCore.Docs/issues/30535

### Expected Behavior

Blazor app to work on GitHub pages

### Steps To Reproduce

Create a new blazor app
Try to host it on GitHub pages

### Exceptions (if any)

See https://github.com/dotnet/AspNetCore.Docs/issues/30535

### .NET Version

8 RC1

**Comment by radical** [comment]
https://github.com/dotnet/AspNetCore.Docs/pull/30542/ - adds a section saying that the property is not supported for github pages.
I don't think property is ready for use in 8.0 at all. So, we should not be suggesting using it at all. Feel free to correct me.
cc @lewing @fanyang-mono @mkArtakMSFT

**Comment by guardrex** [comment]
That PR was reverted at Dan's request. He thinks this is a bug.

**Comment by fanyang-mono** [comment]
> [dotnet/AspNetCore.Docs#30542](https://github.com/dotnet/AspNetCore.Docs/pull/30542) - adds a section saying that the property is not supported for github pages. I don't think property is ready for use in 8.0 at all. So, we should not be suggesting using it at all. Feel free to correct me. cc @lewing @fanyang-mono @mkArtakMSFT

It should be advertised as an opt-in feature for people to try out. Before shipping it to .NET8 RC1, I did test it with Blazor WASM template app and it worked. I am curious what might have caused the issue. I will look into it.

**Comment by guardrex** [comment]
@fanyang-mono ... I was told to cover it as opt-out for 8.0 or later (it was opt-in in 6.0/7.0 coverage) ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/tooling?view=aspnetcore-8.0&pivots=windows#single-instruction-multiple-data-simd

Is it still opt-in for 8.0? I can research and see when/where/who told me it's opt-out, but I'm away from my desk for the next few hours ... I'll need to get back to you in a bit.

**Comment by fanyang-mono** [comment]
@guardrex `WasmStripILAfterAOT` is a complete new feature that I introduced in .NET8 RC1. It was tested on limited scenarios before shipping. Thus, we shipped it as an opt-in feature. Those two links that you listed are not related to this feature.

**Comment by guardrex** [comment]
My apologies ... I'm buried in work here at the moment 😅. The correct link is ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-8.0#trim-net-il-after-ahead-of-time-aot-compilation

... and it is ***opt-in***.

It seems that we need to make some remarks about enabling it. I'll be back, but it's tough to reach this at the moment. I'll get to it as soon as I can.

**Comment by fanyang-mono** [comment]
This issue should have been fixed in .NET9. @AceHack Could you try .NET9 to see if this issue still exit?

**Comment by lewing** [comment]
I believe this is fixed, please reopen if not
