### ISSUE TITLE
HttpListenerRequest.UserAgent should be attributed as nullable

### ISSUE THREAD

**Issue by wsheemsft** [dotnet/runtime#93033]
### Description

[HttpListenerRequest.UserAgent](https://github.com/dotnet/runtime/blob/a166bb71dea362129a25822852c23dbea1d802ed/src/libraries/System.Net.HttpListener/src/System/Net/HttpListenerRequest.cs#L205C77-L205C77) has a return type of `string` but it returns null if the request does not have a `User-Agent` header. Other public properties, such as [ContentType](https://github.com/dotnet/runtime/blob/a166bb71dea362129a25822852c23dbea1d802ed/src/libraries/System.Net.HttpListener/src/System/Net/HttpListenerRequest.cs#L109) and [UrlReferrer](https://github.com/dotnet/runtime/blob/a166bb71dea362129a25822852c23dbea1d802ed/src/libraries/System.Net.HttpListener/src/System/Net/HttpListenerRequest.cs#L211) are correctly attributed.

UserAgent uses the null-forgiving operator when reading the value:

```csharp
public string UserAgent => Headers[HttpKnownHeaderNames.UserAgent]!;
```

The same file also checks it for null:

```csharp
if (UserAgent != null && CultureInfo.InvariantCulture.CompareInfo.IsPrefix(UserAgent, "UP"))
```

Can UserAgent return `string?` instead of `string`? It matches the behavior both internally (above) and externally (requests missing `User-Agent` header).

It's especially confusing because other properties _are_ attributed.

### Reproduction Steps

Create an HTTP listener and send it a request without a `User-Agent` header. The `UserAgent` property will be null even though the return type is not attributed as such.

### Expected behavior

`UserAgent` property is attributed as nullable because it can easily be null.

### Actual behavior

`UserAgent` property is not attributed as nullable.

### Regression?

N/A. I think it was overlooked during #41189

**Comment by MichalPetryka** [comment]
`User agents SHOULD include this field with requests.`
Standard seems to suggest that it's optional so making it nullable makes sense here.

**Comment by ManickaP** [comment]
Seems reasonable. We would be happy to accept a PR for this, it seems straightforward.

**Comment by TheMaximum** [comment]
I'd be interested to take a crack at this one. Have wanted to get involved in the dotnet repositories and this seems like a (really) simple issue to get started with.

**Comment by ManickaP** [comment]
It's yours @TheMaximum :smiley:
