### ISSUE TITLE
DEREF_OF_NULL in /src/coreclr/jit/lsrabuild.cpp

### ISSUE THREAD

**Issue by ellena13** [dotnet/runtime#93048]
Pointer `GenTree::gtGetOp1(...)`, that can have __only NULL value__, is passed as 1st parameter in call to function `LinearScan::BuildUse`

https://github.com/dotnet/runtime/blob/e40b3abf1b41621d4298642a5fd300ebf7cccf6d/src/coreclr/jit/lsraxarch.cpp#L211-L216

where it __is dereferenced__ at

https://github.com/dotnet/runtime/blob/e40b3abf1b41621d4298642a5fd300ebf7cccf6d/src/coreclr/jit/lsrabuild.cpp#L2929-L2930

https://github.com/dotnet/runtime/blob/e40b3abf1b41621d4298642a5fd300ebf7cccf6d/src/coreclr/jit/lsrabuild.cpp#L2964-L2967

Found by Linux Verification Center ([portal.linuxtesting.ru](https://portal.linuxtesting.ru/)) with SVACE.

Author E. Bykhanova.

**Comment by jakobbotsch** [comment]
Looks like dead code, we don't have those kind of passthrough GT_NOP nodes in LIR.
