### ISSUE TITLE
DEREF_AFTER_NULL in /src/coreclr/jit/hwintrinsiccodegenxarch.cpp

### ISSUE THREAD

**Issue by ellena13** [dotnet/runtime#93050]
After having been compared to a __NULL value__ at 

https://github.com/dotnet/runtime/blob/e40b3abf1b41621d4298642a5fd300ebf7cccf6d/src/coreclr/jit/hwintrinsiccodegenxarch.cpp#L1154

pointer  `op1` __is dereferenced__ at 

https://github.com/dotnet/runtime/blob/e40b3abf1b41621d4298642a5fd300ebf7cccf6d/src/coreclr/jit/hwintrinsiccodegenxarch.cpp#L1370-L1373

No NULL check is performed before potential dereference.

Found by Linux Verification Center ([portal.linuxtesting.ru](https://portal.linuxtesting.ru/)) with SVACE.

Author E. Bykhanova.

**Comment by jakobbotsch** [comment]
The code looks fine to me. The number of operands depends on the specific intrinsic ID, so we know in those sub cases that the operands are non-null.
