### ISSUE TITLE
[mono][aot] Improve toolchain configuration in Mono AOT compiler

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#93052]
The Mono AOT compiler comes with a predefined set of toolchain configurations for particular platforms. 

https://github.com/dotnet/runtime/blob/ffa4ef75ec135a64a30e14df5c2afca340ee1203/src/mono/mono/mini/aot-compiler.c#L13202-L13216

The current implementation does not allow for full extensibility in cases when the default toolchain is not available. To mitigate this, the https://github.com/dotnet/runtime/pull/92057 introduces the `as_name` and `as_options`, along with `ld_name` and `ld_options` to allow specific toolchain configuration.

However, there are cases where the default properties are combined with parameters. For example, even though the `ld-name` is passed as an argument, if the `LD_NAME` is not defined, the default configuration is used:
https://github.com/dotnet/runtime/blob/ffa4ef75ec135a64a30e14df5c2afca340ee1203/src/mono/mono/mini/aot-compiler.c#L13351-L13375

In order to enable easier code maintenance and to improve flexibility in utilizing different toolchains, the proposal is to introduce the `PlatformConfig` struct:
```c
typedef struct {
    const char* as_name;
    const char* as_options;
    const char* as_object_file_suffix;
    const char* ld_name;
    const char* ld_options;
} PlatformConfig;
```
It can be defined as follows:
```c
void compile_asm(MonoAotCompile* acfg, const CompileConfig* config)
```
And utilized as below:
```c
compile_asm(acfg, &CONFIG_WIN32_MSVC);
// or
compile_asm(acfg, &CONFIG_LINUX);
```

The structs may be defined in a separate configuration file that is linked with the AOT compiler. This approach would enable the creation of default configurations according to the host OS and architecture in a structured manner and allow parameterizing these options.

/cc: @vargaz @lambdageek

**Comment by vargaz** [comment]
We have an utils/options-def.h file with some support for options which are compile time constants, perhaps this stuff can be added there ?

**Comment by kotlarmilos** [comment]
Lower priority compared to other tasks.
