### ISSUE TITLE
[mono][perf] iOS disk size regression on 3 Oct 2023

### ISSUE THREAD

**Issue by LeVladIonescu** [dotnet/runtime#93072]
### Description

Disk size (SOD) regressions detected in HelloiOS app for both llvm and nollvm configurations.

#### Details

Date | Diff | Change | Size increase (bytes) | Size increase (%)
--|--|--|--|--
3 Oct 2023 | https://github.com/dotnet/runtime/compare/88f25474334bfb0da10e0b5acb0219a64a04828b...d2e24fa59d5259000b803cb4efc0dfd2c7ea0b37 | https://github.com/dotnet/runtime/pull/90764 | 1066800 | 5,01 

![273588138-a8439c5e-2f14-4ddc-b9a3-f32cf8d7427a](https://github.com/dotnet/runtime/assets/114913836/492995db-38e7-4f68-a4a1-cab5f49b6f76)

#### Steps to get the app sizes

1. `git checkout b9e01455c2247454ec0301b8465f7168eebd6a09` (checkout to our commit's parent)
2. `cd src/mono/sample/iOS`
3. `sudo make runtimepack TARGET=iossimulator MONO_ARCH=arm64 MONO_CONFIG=Release` (build the runtime)
4. `sudo make run-sim MONO_CONFIG=Release MONO_ARCH=arm64` (build the app bundle)
5. `ls -la bin/iossimulator-arm64/Bundle/HelloiOS/Release-iphonesimulator/HelloiOS.app` (the app to look for is HelloiOS)

**Comment by SamMonoRT** [comment]
Regression as seen in https://msit.powerbi.com/groups/me/apps/54e0e83f-07bc-45bf-87b7-a7677ff3af2a/reports/161e76f5-dad3-4b78-b4d2-56db2da6bdc4/ReportSectionc6d3e2c09b9adee234d0?experience=power-bi  

![image](https://github.com/dotnet/runtime/assets/46026722/a8439c5e-2f14-4ddc-b9a3-f32cf8d7427a)

**Comment by MichalPetryka** [comment]
Could this be #90764?

**Comment by LeVladIonescu** [comment]
I've got locally the results showing the size increase after https://github.com/dotnet/runtime/pull/90764.

**Comment by matouskozak** [comment]
Closing in favor of https://github.com/dotnet/runtime/issues/105701, feel free to re-open if you think this issue requires a separate atention.
