### ISSUE TITLE
[API Proposal]: Add a library for working with pictures

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#93075]
### Background and motivation

I suggest adding a library for working with photos that would be compatible with all operating systems, not just Windows. There are open-source libraries available for image manipulation, but they tend to be temporary solutions, as they may change their license or simply cease library support.

### API Proposal

-

### API Usage

-

**Comment by Sergio0694** [comment]
Building an efficient image processing library that supports multiple codecs, is efficient, has a good API design, is fast and safe, is fully trimmable and AOT friendly, is fully managed, cross platform, etc. is a _monumental_ amount of work, that would take years and multiple people working on it. It also requires extremely specialized knowledge. Thankfully [ImageSharp](https://github.com/SixLabors/ImageSharp) already exists 😄

**Comment by Mr0N** [comment]
> Building an efficient image processing library that supports multiple codecs, is efficient, has a good API design, is fast and safe, is fully trimmable and AOT friendly, is fully managed, cross platform, etc. is a _monumental_ amount of work, that would take years and multiple people working on it. It also requires extremely specialized knowledge. Thankfully [ImageSharp](https://github.com/SixLabors/ImageSharp) already exists 😄

Microsoft developed Windows, so I think they can handle a library somehow).

**Comment by ViktorHofer** [comment]
Closing as not planned. As @Sergio0694 mentioned, ImageSharp and other alternatives already exist.
