### ISSUE TITLE
[API Proposal]: `KeyValuePair<K, V>.Deconstruct`

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#93080]
### Background and motivation

Enumerating a dictionary should be as simple as:

```cs
foreach ((string path, string content) in changedDocuments)
{
}
```

But instead, we have to do this:

```cs
foreach (KeyValuePair<string, string> pair in changedDocuments)
{
    string path = pair.Key;
    string content = pair.Value;
}
```

Deconstruct methods should be added where it's common to want to break components out, and very clearly predictable which components and their order will come out. KeyValuePair checks all the boxes.

This has been suggested several times (e.g. https://github.com/dotnet/runtime/issues/19397), but each time, it seems it somehow got missed or dismissed.

### API Proposal

```csharp
public class KeyValuePair<K, V>
{
    public void Deconstruct<TKey, TValue>(out TKey key, out TValue value) => (key, value) = (this.Key, this.Value);
}
```

### API Usage

```cs
Dictionary<string, string> changedDocuments;
foreach ((string path, string content) in changedDocuments)
{
}
```

**Comment by vcsjones** [comment]
[There is a `Deconstruct` in `KeyValuePair`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.keyvaluepair-2.deconstruct?view=net-7.0). It was introduced in .NET Core 2.0 / .NET Standard 2.1.

**Comment by stephentoub** [comment]
And just for completeness, as a result the cited example compiles fine:
[SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATARgLABQGADAAQY4oDchhGAzOVqQMKkDehp35jGKpALIAKACIBLMABdxEAHYBDKAE8APBWIAacjmIA+UmAAWCuQHMYAE1EQwAVwC2MOVIDOASg5cePgGbQYBWNSYWENUgAHBSkjbXDIF2cpT3E5QxNzKxt7JxcPbx9uTgJCngBfAtIKgjKgA===)

**Comment by AArnott** [comment]
Ah, gee. I forgot I was in a multi-targeting project when I saw it wasn't working. Well, I'm delighted to see the API is already there. :)

**Comment by vcsjones** [comment]
> I forgot I was in a multi-targeting project

You can polyfill Deconstruct with an extension method for older frameworks if you would like it to work down level.

**Comment by AArnott** [comment]
Yup, I love that.
