### ISSUE TITLE
[Mono] AdvSimd.Arm64 [Load/Store]Vector64 and [Load/Store]Vector128 for 2,3 and 4 variants with LLVM

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#93081]
Refer to https://github.com/dotnet/runtime/issues/84510 for the full list of API's. Re-enable tests being disabled tests.

Part of the work of this issue is to handle tuple type input arguments in those API's. To implement it, see the following example for inspiration
https://github.com/dotnet/runtime/blob/4325acccb730221b98ddba17fdc63731e819176b/src/mono/mono/mini/simd-intrinsics.c#L4183

AdvSimd and AdvSimd.Arm64 intrinsics are currently only supported by LLVM. So these new intrinsics will follow this trend.

This is the list of APIs for AdvSimd:
- [x] LoadVector64x2 - @fanyang-mono 
- [x] LoadVector64x3 - @fanyang-mono 
- [x] LoadVector64x4 - @fanyang-mono 
- [x] LoadVector64x2AndUnzip - @fanyang-mono 
- [x] LoadVector64x3AndUnzip - @fanyang-mono 
- [x] LoadVector64x4AndUnzip - @fanyang-mono 
- [x] LoadAndInsertScalar - @fanyang-mono
- [x] LoadAndReplicateToVector64x2 - @fanyang-mono 
- [x] LoadAndReplicateToVector64x3 - @fanyang-mono 
- [x] LoadAndReplicateToVector64x4 - @fanyang-mono 
- [x] StoreVector64x2 - @jkurdek 
- [x] StoreVector64x3 - @jkurdek 
- [x] StoreVector64x4 - @jkurdek 
- [x] StoreVector64x2AndZip - @jkurdek 
- [x] StoreVector64x3AndZip - @jkurdek 
- [x] StoreVector64x4AndZip - @jkurdek 
- [x] StoreSelectedScalar  - @fanyang-mono 

This is the list of APIs for AdvSimd.Arm64:
- [x] LoadVector128x2 - @fanyang-mono 
- [x] LoadVector128x3 - @fanyang-mono 
- [x] LoadVector128x4 - @fanyang-mono 
- [x] LoadVector128x2AndUnzip - @fanyang-mono 
- [x] LoadVector128x3AndUnzip - @fanyang-mono 
- [x] LoadVector128x4AndUnzip - @fanyang-mono 
- [x] LoadAndInsertScalar - @fanyang-mono
- [x] LoadAndReplicateToVector128x2 - @fanyang-mono 
- [x] LoadAndReplicateToVector128x3 - @fanyang-mono 
- [x] LoadAndReplicateToVector128x4 - @fanyang-mono 
- [x] StoreVector128x2 - @jkurdek 
- [x] StoreVector128x3 - @jkurdek 
- [x] StoreVector128x4 - @jkurdek 
- [x] StoreVector128x2AndZip - @jkurdek 
- [x] StoreVector128x3AndZip - @jkurdek 
- [x] StoreVector128x4AndZip - @jkurdek 
- [x] StoreSelectedScalar  - @fanyang-mono

**Comment by kunalspathak** [comment]
@fanyang-mono - this should help you!

![image](https://github.com/dotnet/runtime/assets/12488060/0e8e0af0-d7b6-43e4-831b-0a243c0719f9)

**Comment by fanyang-mono** [comment]
Closing this issue, as all the tasks listed here are done.
