### ISSUE TITLE
Environment.GetfolderPath( Environment.SpecialFolder.Personal ) not returning FolderPath in .net 8.0 rc1

### ISSUE THREAD

**Issue by speed2048** [dotnet/runtime#93094]
### Description

Calling Environment.GetfolderPath( Environment.SpecialFolder.Personal )   will return a null or empty string.  

Environment : wsl2
OS:  Ubuntu 22.04.2 LTS

.net 7.0 does not have issues.

Other virtual machines are also exhibiting this issue via programs calling  this method. . Physical machines work just fine.

### Reproduction Steps

namespace testdevdrive
{
    internal class Program
    {
        static void Main(string[] args)
        {
            string home_directory = Environment.GetFolderPath(Environment.SpecialFolder.Personal);
            if (!string.IsNullOrEmpty(home_directory))
            {
                Console.WriteLine($"Home Directory = {home_directory} ");
            }
            else
                Console.WriteLine("Cannot find home directory.");
        }
    }
}

### Expected behavior

Should return the users home directory.

### Actual behavior

Returns null.

### Regression?

net 7.0 returns home directory.

### Configuration

**<B>RUNNING** WSL2 - ubuntu.
uname -a
Linux wks-win10-002 5.15.123.1-microsoft-standard-WSL2 #1 SMP Mon Aug 7 19:01:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
****
.NET SDK:
 Version:   8.0.100-rc.1.23455.8
 Commit:    e14caf947f

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.100-rc.1.23455.8/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-rc.1.23419.4
  Architecture: x64
  Commit:       92959931a3
  RID:          linux-x64

.NET SDKs installed:
  8.0.100-rc.1.23455.8 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.13 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.1.23421.29 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.13 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.1.23419.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/lib/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by jkotas** [comment]
Likely introduced by https://github.com/dotnet/runtime/pull/68610 and documented as a breaking change at https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/8.0/getfolderpath-unix

cc @eerhardt

**Comment by jkotas** [comment]
cc @Miepee

**Comment by speed2048** [comment]
Thanks for the info, I have a workaround and modified my code to use Environment.SpecialFolder.UserProfile instead of Environment.SpecialFolder.Personal.

**Comment by danmoseley** [comment]
@speed2048 What is the value if any of XDG_DOCUMENTS_DIR in your virtual machines and in your physical machines?

**Comment by jkotas** [comment]
@danmoseley This should repro in any WSL. 

https://github.com/dotnet/runtime/blob/f21a2666c577306e437f80fe934d76cdb15072a5/src/libraries/System.Private.CoreLib/src/System/Environment.GetFolderPathCore.Unix.cs#L23 returns fallback path that is `$HOME/Documents` . This path does not exist and we return an empty string here: https://github.com/dotnet/runtime/blob/f21a2666c577306e437f80fe934d76cdb15072a5/src/libraries/System.Private.CoreLib/src/System/Environment.GetFolderPathCore.Unix.cs#L35-L40 .

`Environment.GetFolderPath(Environment.SpecialFolder.Personal, Environment.SpecialFolderOption.Create)` returns the expected value.

**Comment by Miepee** [comment]
Is this WSL specific? I only have a linux box, so would like to know whether just spinning up an ubuntu VM would let me be able to repro. 

That said, looking at this a little, this does *seem* like intended behaviour.:
I. `GetFolderPath` returns an empty string by default if path does not exist
II. `MyDocuments`/`Personal` used to return $HOME in .NET 7. HOME usually always exists, so this returned a path fine
III. `MyDocuments`/`Personal` returns the documents folder. Assuming WSL does not create anything more than the essentials (it has been a few years since I used it), the documents folder does not exist. Thus going back to I and returning an empty path.

**Comment by speed2048** [comment]
@danmoseley  - Value of XDG_DOCUMENTS_DIR  for virtual and physical boxes is not defined.

WSL VM and my other VM the Documents directory does not exist. 

If I add Environment.SpecialFolderOption.DoNotVerify the method will return /home/user/Documents.

And of course if I create the  Documents directory the calls work. 

I didnt catch the behavior change of Environment.SpecialFolder.Personal on Linux and was hunting down why the app wasnt working correctly...

PR closed?

**Comment by Miepee** [comment]
Yeah, seems like this is invalid then.
FWIW the [link here from jkotas](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/8.0/getfolderpath-unix#recommended-action) does detail that A) personal is an alias for mydocuments and B) one shouldnt try to thus use Personal to get the home folder

**Comment by jkotas** [comment]
> PR closed?

I agree. The behavior change is expected and documented in the breaking change notice.
