### ISSUE TITLE
[API Proposal]: AppendFormat<TValue>(ReadOnlySpan<char> format, ReadOnlySpan<char> strArg = default, params TValue[] args) where TValue: INumber<TValue>();

### ISSUE THREAD

**Issue by Shpendicus** [dotnet/runtime#93091]
### Background and motivation

Background and motivation

Same as with the last of my Proposal, regarding an addition to StringBuilder with Replace(spans), I wanted to suggest another, similar way of allowing even further reduction of allocation, because usually the case of using a StringBuilder is mostly anyway in scenarios where you have big loops and need to concatenate alot of strings or chunks of data into a big chain of data and this usually happens in either loops OR alot of calls to a function from whatever sources, like server requests and such, so my proposal would be to Add an overload to the current "stringBuilder.AppendFormat(string, object0..objectX)" which would be:

  ```CSharp
public StringBuilder AppendFormat<TValue>(ReadOnlySpan<char> format, ReadOnlySpan<char> strArg = default, params TValue[] args) where TValue: INumber<TValue>();

  public StringBuilder AppendFormat<TValue>(ReadOnlySpan<char> format, ReadOnlySpan<char> strArg = default, params TValue arg0, TValue arg1, TValue arg2) where TValue: INumber<TValue>();
```

I think this approach could allow for more reusable approach in terms of string-usages, by allowing a ROS to be passed and also a params TValue[] args could (maybe) allow the strong (then .NET 9) compiler to determine (hopefully) all the different numeric-types at compile time, hence without the need to box these into heap territory :)

As always thanks for the amount of work you put in .NET ecosystem and the love of detail which has evolved this project so much!

Best regards

### API Proposal

```csharp
 
public StringBuilder AppendJoin<TValue>(ReadOnlySpan<char> format, ReadOnlySpan<char> strArg = default, params TValue[] args) where TValue: INumber

public StringBuilder AppendJoin<TValue>(ReadOnlySpan<char> format, ReadOnlySpan<char> strArg = default, params TValue arg0....TValue argX) where TValue: INumber
```

I have added an "ReadOnlySpan<char> strArg = default" because if u want to add a string to the StringBuilder you would else indeed be forced to use object[] args otherwise its not possible to put it in, but by making it an explicit extra parameter this can leave the Tvalue[] alone which can be all allocated only once in the heap without the boxing for each of them.

### API Usage

Example from: [https://learn.microsoft.com/de-de/dotnet/api/system.text.stringbuilder.appendformat?view=net-7.0#code-try-2](url)
```csharp

   static StringBuilder sb = new StringBuilder();

    public static void Main()
    {
        //you can do this to force only 1 alloc of the format string and not have more when u for instance need only the 0th, or 0th and 1th, and so on
        scoped ReadOnlySpan<char> bigFormat = "{0}, {1}, {2}, {3}, {4}, {5}";  
                                  
        sb.AppendFormat(bigFormat, 10, 11.298d, 12.24f, -13, 634784733242L);     //sb-contains:  "10, 11.298, 12.24, -13, 634784733242"
        sb.AppendFormat(bigFormat.Slice(0, 7), 120, 0.24d);                      //sb-contains:  "120, 0.24"
        sb.AppendFormat(bigFormat.Slice(0, 16), 260, 044d, -45);                 //sb-contains:  "260, 0.44, -45"
        return null;       
    }
//OR this approach

    public static void Main2()
    {
        scoped ReadOnlySpan<char> bigFormat = "{0}, {1}, {2}, {3}, {4}, {5}, {6}, {7}, {8}, {9}, {10}";
        StringBuilder sb = new();
        
        const int WHATEVER = 35; //whatever the max is here...
        int length = 7;  //7 chars means we get the '}' from the {1} code
        
        //we append here 5 numbers all ints
        AppendFormat(bigFormat, string.Empty, 11, 12, 13, 14);

        int moviePrice = 20;
        char movieSort = 'M';
        double movieLen = 120.45d;
        float movieRanking = 6.8f;
        string movieName = "Mr Knuckles";
        long movieProductionCost = 250_000_000L; 

        //Scenario: 0
        for (int i = 0; i < WHATEVER; i++)
        {
            AppendFormat(bigFormat, movieName, moviePrice, movieLen, movieRanking, movieSort);
        }

        //Scenario: 1
        var empty = Array.Empty<TValue>();
        
//    "{0}, {1}, {2}" => bigFormat[..15]
//    "{0}, {1}" => bigFormat[..8]

        AppendFormat(bigFormat[..15], movieName, moviePrice, movieRanking, movieLen);
        AppendFormat(bigFormat[..8], ReadOnlySpan<char>.Empty,movieSort, movieProductionCost);
        
        return null;
    }


```

This would create only 1 format-string for the entire loop and with the "INumber" constraint on "TValue" we should be able to reduce the allocations to 2 basically, the 1 being the format string and the 2. being the TValue[] array, which is a big win, because we avoid the boxing if i am not mistaken.

### Alternative Designs

None.

### Risks

Afaik None.

**Comment by stephentoub** [comment]
I don't understand the scenario here.  Can you point to a real codebase that would use this?  If you know the format string well enough to be able to slice it at specific indices, why not just use string interpolation?

**Comment by Shpendicus** [comment]
> I don't understand the scenario here. Can you point to a real codebase that would use this? If you know the format string well enough to be able to slice it at specific indices, why not just use string interpolation?

Yes, you are right, I for some reason fully forgot that option, okay the "format" adaption is from the table, got it, and what you think of the change in "object[] args" ----> "TValue[] args"?  Are my accusations true regarding the memory allocation overhead of the former version?

Sadly i cant directly pooint to an existent codebase , this idea sprang out of my mind during work on a project so I thought it could fit in.

**Comment by stephentoub** [comment]
> and what you think of the change in "object[] args" ----> "TValue[] args"?

That requires all of the arguments to be of the same type, and still ends up allocating an array. That's entirely avoided with string interpolation.  And in .NET 8, there are overloads that take a CompositeFormat and that have strongly-typed arguments for the most commonly used arities.

**Comment by Shpendicus** [comment]
> > and what you think of the change in "object[] args" ----> "TValue[] args"?
> 
> That requires all of the arguments to be of the same type, and still ends up allocating an array. That's entirely avoided with string interpolation. And in .NET 8, there are overloads that take a CompositeFormat and that have strongly-typed arguments for the most commonly used arities.

okay thx for the clear-up, i will mark this post as resolved, wish you all a good week!
