### ISSUE TITLE
ConfigurationBindingGenerator: The given line is '63' characters long, which is fewer than the provided character number '65'

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#93128]
Building the "TodosApi" benchmark on a mac with .net 8 RC1, I get the above error from the source generator:

```
/Users/alklig/work/TodosApiNaot/Benchmarks/src/BenchmarksApps/TodosApi/Microsoft.Extensions.Configuration.Binder.SourceGeneration/Microsoft.Extensions.Configuration.Binder.SourceGeneration.ConfigurationBindingGenerator/BindingExtensions.g.cs(37,132): error CS9143: The given line is '63' characters long, which is fewer than the provided character number '65'. [/Users/alklig/work/TodosApiNaot/Benchmarks/src/BenchmarksApps/TodosApi/TodosApi.csproj]
```

Repro:
1. Check out aspnet/Benchmarks@5e95f15
2. go to `src/BenchmarkApps/TodosApi`
3. `dotnet build`

Problems:

1. The path in the error message doesn't exist.
2. even if I turn on `/p:EmitCompilerGeneratedFiles=true` then the genrated file is `obj/Debug/net8.0/generated/Microsoft.Extensions.Configuration.Binder.SourceGeneration/Microsoft.Extensions.Configuration.Binder.SourceGeneration.ConfigurationBindingGenerator/BindingExtensions.g.cs` and it contains
   ```csharp
       [InterceptsLocationAttribute(@"/Users/alklig/work/TodosApiNaot/Benchmarks/src/BenchmarksApps/TodosApi/AppSettings.cs", 36, 65)]
        public static OptionsBuilder<TOptions> BindConfiguration<TOptions>(this OptionsBuilder<TOptions> optionsBuilder, string configSectionPath, Action<BinderOptions>? configureOptions = null) where TOptions : class
   ```
   The line in `AppSettings.cs` is:
   ```csharp
           var optionsBuilder = services.AddOptions<AppSettings>()
   ```
   and the line after is:
   ```
                  .BindConfiguration(nameof(AppSettings));
   ```

It seems like it wants to intercept the `BindingConfiguration` call but the intercepts location attribute is aiming at the wrong line.

I'm on an M1 mac - not sure if the platform makes a difference (maybe it's something to do with line endings?)

**Comment by lambdageek** [comment]
workaround is not split the call on two lines and just combine them:

```csharp
        var optionsBuilder = services.AddOptions<AppSettings>().BindConfiguration(nameof(AppSettings));
```

**Comment by stephentoub** [comment]
This was a bug in RC1 that was fixed for RC2.

**Comment by tarekgh** [comment]
@lambdageek this issue should be addressed through the PR https://github.com/dotnet/runtime/pull/91237. Can you try more recent version and confirm?

**Comment by tarekgh** [comment]
CC @ericstj

**Comment by lambdageek** [comment]
yep, fixed. thanks
