### ISSUE TITLE
[wasm] runtime tests timing out on `Build Tests` step for rolling builds

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#93134]
Runtime tests job has been timing out on rolling builds, specifically on the `Build Tests` step. The last passing rolling build was https://dev.azure.com/dnceng-public/public/_build/results?buildId=428248 , and the first failing one https://dev.azure.com/dnceng-public/public/_build/results?buildId=429084 .

The changes between them 52aca8c5...9dfbb61a .

There were 3 PRs with changes in `src/tests`:
- #92728
- #92029
- #93012

cc @fanyang-mono @trylek @akoeplinger 

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by radical** [comment]
@trylek The runtime tests job on your PR https://github.com/dotnet/runtime/pull/92029 timed out too, but the PR was merged before the job was completed. Could you please take a look at this?

**Comment by akoeplinger** [comment]
An important thing to notice here is this message which gets shown in the root log:
```
##[warning]Agent  was purged, cancelling the pipeline.
,##[warning]Received request to deprovision: The request was cancelled by the remote provider.
```

As far as I know this means the AzDO agent was killed somehow. Maybe we're hitting OOM with the AOT compiler due to the increased number of tests in the merged tests setup? But it's weird given this is a `monointerpreter` job so I assume it should do little AOTing.

**Comment by radical** [comment]
@lewing we might be hitting container limits for runtime tests again. These have been failing since Oct 5, so we are not running any runtime tests.

**Comment by radical** [comment]
> An important thing to notice here is this message which gets shown in the root log:
> 
> ```
> ##[warning]Agent  was purged, cancelling the pipeline.
> ,##[warning]Received request to deprovision: The request was cancelled by the remote provider.
> ```
> 
> As far as I know this means the AzDO agent was killed somehow. Maybe we're hitting OOM with the AOT compiler due to the increased number of tests in the merged tests setup? But it's weird given this is a `monointerpreter` job so I assume it should do little AOTing.

Actually, if it was hitting container limits then it should have failed much sooner, but the job failed/got-cancelled after `4h 1m 9s`!

**Comment by radical** [comment]
@akoeplinger is there any way to get the console log from that that, even if it might be truncated near the end?

**Comment by akoeplinger** [comment]
@radical I don't think so, it looks like AzDO doesn't preserve the log in this case...

> but the job failed/got-cancelled after 4h 1m 9s!

It is wildly different between runs, I've also seen it after 1h50m.

**Comment by radical** [comment]
@trylek Could you please take a look at this? I think https://github.com/dotnet/runtime/pull/92029 might be the one causing this. This is happening consistently since Oct 5.
cc @lewing

Meanwhile, I'm trying a revert - https://github.com/dotnet/runtime/pull/93362 .

**Comment by lewing** [comment]
this is super frustrating, not only does the build get cancelled by infrastructure with no details but then the github integration doesn't see the cancellation reliably so the build gets stuck in an inconsistent state.  @JulieLeeMSFT @agocke is there a way to deal with the build analysis/infrastructure issue here?

**Comment by radical** [comment]
Fixed by https://github.com/dotnet/runtime/pull/93646 .
