### ISSUE TITLE
[wasm] Resource loader override is ignored by worker in multithreading mode

### ISSUE THREAD

**Issue by Elringus** [dotnet/runtime#93133]
### Description

I'm trying to boot WASM runtime in MT mode with the following setup: 

```js
const config = {
    mainAssemblyName: "JSInteropTest.dll",
    resources: {
        jsModuleRuntime: { "dotnet.runtime.js": "" },
        jsModuleNative: { "dotnet.native.js": "" },
        jsModuleWorker: { "dotnet.native.worker.js": "" },
        wasmNative: { "dotnet.native.wasm": "" },
        assembly: {
            "System.Private.CoreLib.wasm": "",
            "System.Runtime.InteropServices.JavaScript.wasm": "",
            "System.Console.wasm": "",
            "System.Linq.wasm": "",
            "System.Threading.Channels.wasm": "",
            "OtherAssembly.wasm": "",
            "JSInteropTest.wasm": "",
        }
    }
};

const runtime = await dotnet.withConfig(config).withModuleConfig({
    locateFile: (path, prefix) => {
        return "/_framework/bin/" + path;
    }
}).withResourceLoader((type, name, defaultUri, integrity, behavior) => {
    return "/_framework/bin/" + name;
}).create();
```

— which throws:

```
worker sent an error! :0: TypeError: error loading dynamically imported module: http://localhost:3000/_framework/dotnet.native.js
```

Notice worker is requesting `http://localhost:3000/_framework/dotnet.native.js` ignoring both `withModuleConfig.locateFile` and `withResourceLoader` overrides.

### Reproduction Steps

1. Clone https://github.com/Elringus/JSInteropTest
2. Run `dotnet publish`
3. Serve `AppBundle/index.html`

### Expected behavior

Runtime boots and prints test messages to the console.

### Actual behavior

Error is thrown.

### Known Workarounds

None.

### Configuration

.NET 8 RC1
Windows 10 x64

**Comment by Elringus** [comment]
UPD: I've tried both `withModuleConfig.locateFile` and `withResourceLoader`, but it seems it doesn't work in MT, as worker seem to ignore the setting:

```js
const runtime = await dotnet.withConfig(config).withModuleConfig({
    locateFile: (path, prefix) => {
        return "/_framework/bin/" + path;
    }
}).withResourceLoader((type, name, defaultUri, integrity, behavior) => {
    return "/_framework/bin/" + name;
}).create();
```

— throws:

```
worker sent an error! :0: TypeError: error loading dynamically imported module: http://localhost:3000/_framework/dotnet.native.js
```

**Comment by Elringus** [comment]
I've updated the issue description.

**Comment by maraf** [comment]
It's MT only. The `resourceLoader` is not passed to the worker and so it doesn't know where to look for `dotnet.runtime.js`.

**Comment by Elringus** [comment]
It seems `resolvedUrl` is reset to default when fetching wasm module as well. And `withModuleConfig.locateFile` override is ignored.

**Comment by pavelsavara** [comment]
I guess we need to figure out which callbacks need to be dispatched between threads in Net9.
I'm not sure `locateFile` is one of them. 

Not overwriting existing `resolvedUrl` is probably way to go.

**Comment by Elringus** [comment]
> Not overwriting existing resolvedUrl is probably way to go.

So effectively, given milestone, in .NET 8 it won't be possible to store the runtime files anywhere, but under the same directory as the entry point? And `withResourceLoader` will remain broken for this LTS cycle?

**Comment by maraf** [comment]
> I guess we need to figure out which callbacks need to be dispatched between threads in Net9. I'm not sure `locateFile` is one of them.
> 
> Not overwriting existing `resolvedUrl` is probably way to go.

I don't think that's the case. I think we can just use the `resolvedUrl` passed from the main thread.

**Comment by Elringus** [comment]
> MT is not supported in Net8 and I struggle to see if it's worth the risk to merge this fix as late in the Net8 cycle.

It's ok, I've found a workaround. When in mt I'm assigning the relative path to name of the non-assembly resources (assemblies are getting the resolvedUrl in the worker):

```ts
function buildAsset(res: BinaryResource, behavior: AssetBehaviors,
    module?: unknown, optional?: boolean, mt?: boolean): AssetEntry {
    const url = `${resources.root}/${res.name}`;
    return {
        name: (!mt || res.content || behavior === "assembly") ? res.name : url,
        resolvedUrl: (res.content || !resources.root) ? undefined : url,
        buffer: typeof res.content === "string" ? decodeBase64(res.content) : res.content,
        moduleExports: module,
        isOptional: optional,
        behavior
    };
}
```
