### ISSUE TITLE
SuperPMI: Improve superpmi-diffs pipeline parallelism

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#93137]
Each of asmdiffs and tpdiff are done for a single platform on a single Helix machine. As we increase the number and size of SuperPMI collections, the time to run the asmdiffs and tpdiff steps increases. We should investigate introducing parallelism into this process by running portions of the process (e.g., a subset of MCH files) on different Helix machines. This would require changing how diffs summarization is done (see https://github.com/dotnet/runtime/issues/80719).
 
Related: https://github.com/dotnet/runtime/issues/80718

category:eng-sys
theme:super-pmi
skill-level:intermediate
cost:medium
impact:medium

**Comment by jakobbotsch** [comment]
Fixed by #106759
