### ISSUE TITLE
Lack of ahead-of-time HttpConnectionPool warming leads to very long latencies on cold starts

### ISSUE THREAD

**Issue by Stabzs** [dotnet/runtime#93156]
### Description
When adding new pods to a deployment, we are observing that the HttpConnectionPool instances servicing a variety of HttpClient usages (IHttpClientFactory for service-to-service calls, CosmosDb, Azure Storage Account Queue, etc etc) will experience ramping latency as the number of requests exceeds the rate at which the pool can grow.

This leads to long `RequestLeftQueue` durations while new connections are slowly added to the pool, causing significant latency across all http calls. Eventually, the pool reaches equilibrium with the traffic rate and latency returns to normal.

While this isn't an API Design issue, this issue is trying to understand the correct way to potentially pre-warm the HttpConnectionPool instances to a known level so that bursts of traffic do not cause excessive queueing during ramp-up.

### Configuration
* Which version of .NET is the code running on? .NET 7, although similar behavior has been observed in all other versions of .NET
* What OS version, and what distro if applicable? Alpine Linux, although the same behavior is observed on Windows
* What is the architecture (x64, x86, ARM, ARM64)? x64

### Regression?
No, this is a consistent performance gap across all versions of .NET.

### Data
While the service is first taking load, `RequestLeftQueue` times may be only a few milliseconds. However, as the API takes load (up to +4000 concurrent outbound connections), we start to see values like the following:

Event = System.Net.Http - RequestLeftQueue:timeOnQueueMilliseconds=7356.7927 versionMajor=1 versionMinor=1
Event = System.Net.Http - RequestLeftQueue:timeOnQueueMilliseconds=7356.0786 versionMajor=1 versionMinor=1 
Event = System.Net.Http - RequestLeftQueue:timeOnQueueMilliseconds=7355.8958 versionMajor=1 versionMinor=1 
Event = System.Net.Http - RequestLeftQueue:timeOnQueueMilliseconds=7355.8481 versionMajor=1 versionMinor=1 
Event = System.Net.Http - RequestLeftQueue:timeOnQueueMilliseconds=7355.2501 versionMajor=1 versionMinor=1 
Event = System.Net.Http - RequestLeftQueue:timeOnQueueMilliseconds=7354.8752 versionMajor=1 versionMinor=1 
Event = System.Net.Http - RequestLeftQueue:timeOnQueueMilliseconds=7353.1933 versionMajor=1 versionMinor=1 
Event = System.Net.Http - RequestLeftQueue:timeOnQueueMilliseconds=7352.5281 versionMajor=1 versionMinor=1 
Event = System.Net.Http - RequestLeftQueue:timeOnQueueMilliseconds=7352.08 versionMajor=1 versionMinor=1 
Event = System.Net.Http - RequestLeftQueue:timeOnQueueMilliseconds=7350.8539 versionMajor=1 versionMinor=1 
Event = System.Net.Http - RequestLeftQueue:timeOnQueueMilliseconds=7349.627 versionMajor=1 versionMinor=1 
Event = System.Net.Http - RequestLeftQueue:timeOnQueueMilliseconds=7348.3961 versionMajor=1 versionMinor=1 
Event = System.Net.Http - RequestLeftQueue:timeOnQueueMilliseconds=7330.9594 versionMajor=1 versionMinor=1 
Event = System.Net.Http - RequestLeftQueue:timeOnQueueMilliseconds=7330.8522 versionMajor=1 versionMinor=1 
Event = System.Net.Http - RequestLeftQueue:timeOnQueueMilliseconds=7329.8733 versionMajor=1 versionMinor=1

### Analysis
In order to somewhat mitigate the above, we have added a number of concurrent outbound to various upstream destinations in the startup of the api in order to attempt to pre-pool as many connections as possible. Ideally, we could configure the pools at startup to do this automatically.

**Comment by MihaZupan** [comment]
> `timeOnQueueMilliseconds=7356`

This is a really long time for establishing a new connection.

Are you setting `MaxConnectionsPerServer`? If you're hitting the limit there, that could explain the higher queue times.

On a side note given you're using so many connections, have you considered using HTTP/2 instead?

**Comment by Stabzs** [comment]
I was very surprised by the time. Can you please clarify if that time is spent opening the connection or simply waiting in line TO open a connection? Reading the source I've interpreted it as the latter, rather than waiting for any DNS resolution or initial handshaking.

We're not setting `MaxConnectionsPerServer` and other trace logs show that the connection limit is essentially unbounded:

msg="Event = Private.InternalDiagnostics.System.Net.Http - HandlerMessage:poolId=12470207 workerId=0 requestId=0 memberName=CheckForHttp11ConnectionInjection message=Available HTTP/1.1 connections: 0, Requests in the queue: 2, Requests without a connection attempt: 2, Pending HTTP/1.1 connections: 1, Total associated HTTP/1.1 connections: 8, Max HTTP/1.1 connection limit: 2147483647, Will inject connection: True."

We haven't switched to HTTP/2 yet since we still have a few critical dependencies that are on HTTP/1.1 only. Once those are migrated, we can retest. For that scenario, would you recommend a single HTTP/2.0 connection or multiple connections? We would be targeting several hundred concurrent calls per second per upstream destination.

**Comment by Stabzs** [comment]
@MihaZupan thanks for the research steps. It'll take a bit for us to be able to scrape these metrics, but I'll put something together as soon as possible.
