### ISSUE TITLE
AV in LibraryImport tests

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#93155]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=430060
Build error leg or test failing: LibraryImportGenerator.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/93125

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "'LibraryImportGenerator.Tests' END OF WORK ITEM LOG: Command exited with -1073741819",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

```
  Discovering: LibraryImportGenerator.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  LibraryImportGenerator.Tests (found 126 test cases)
  Starting:    LibraryImportGenerator.Tests (parallel test collections = on, max threads = 2)
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at LibraryImportGenerator.IntegrationTests.NativeExportsNE+MarshallingFails.FillRangeArray2D(SharedTypes.IntStructWrapper[][], Int32, Int32[], Int32)
   at LibraryImportGenerator.IntegrationTests.CollectionMarshallingFails+<>c__DisplayClass8_0.<MultiDimensionalOutAttributedArray_EnsureAllCleaned>b__0()
   at Xunit.Assert.RecordException(System.Func`1<System.Object>)
   at Xunit.Assert.Throws[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Func`1<System.Object>)
   at LibraryImportGenerator.IntegrationTests.CollectionMarshallingFails.MultiDimensionalOutAttributedArray_EnsureAllCleaned()
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=430060
**Error message validated:** `'LibraryImportGenerator.Tests' END OF WORK ITEM LOG: Command exited with -1073741819`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 10/7/2023 4:20:08 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[464917](https://dev.azure.com/dnceng-public/public/_build/results?buildId=464917)|dotnet/runtime|[LibraryImportGenerator.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=464917&view=ms.vss-test-web.build-test-results-tab&runId=10548944&resultId=209373)|dotnet/runtime#94563|
|[459871](https://dev.azure.com/dnceng-public/public/_build/results?buildId=459871)|dotnet/runtime|[LibraryImportGenerator.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=459871&view=ms.vss-test-web.build-test-results-tab&runId=10381438&resultId=213236)|dotnet/runtime#94361|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|2|2|

**Comment by jkotas** [comment]
@jtschuster Could you please take a look? This test was introduced by https://github.com/dotnet/runtime/pull/88060.
