### ISSUE TITLE
8.0.0-rc.1 Library not loaded: /System/Library/Frameworks/CryptoKit.framework/Versions/A/CryptoKit

### ISSUE THREAD

**Issue by zhenlinyang** [dotnet/runtime#93167]
### Description

System.DllNotFoundException: Unable to load shared library 'libSystem.Security.Cryptography.Native.Apple' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 

dlopen(???/dotnet-sdk/shared/Microsoft.NETCore.App/8.0.0-rc.1.23419.4/libSystem.Security.Cryptography.Native.Apple.dylib, 1): Library not loaded: /System/Library/Frameworks/CryptoKit.framework/Versions/A/CryptoKit

macOS Mojave 10.14.6

### Reproduction Steps

Use ```System.Security.Cryptography.MD5.Create();``` in ```macOS Mojave 10.14.6```.

### Expected behavior

Same as .Net 7.0, can be used normally.

### Actual behavior

System.DllNotFoundException: Unable to load shared library 'libSystem.Security.Cryptography.Native.Apple' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 

dlopen(???/dotnet-sdk/shared/Microsoft.NETCore.App/8.0.0-rc.1.23419.4/libSystem.Security.Cryptography.Native.Apple.dylib, 1): Library not loaded: /System/Library/Frameworks/CryptoKit.framework/Versions/A/CryptoKit

### Configuration

8.0.0-rc.1.23419.4 error
7.0.x correct

**Comment by vcsjones** [comment]
> macOS Mojave 10.14.6

[.NET 8 requires macOS 10.15 or later.](https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md#macos)

macOS 10.14 does not include the CryptoKit library that .NET 8 uses for cryptography purposes.

**Comment by vcsjones** [comment]
The installer should be blocking installation on 10.14. Are you saying that you were able to run the pkg installer on 10.14 and it did not block installation?

https://github.com/dotnet/runtime/blob/f21a2666c577306e437f80fe934d76cdb15072a5/src/installer/pkg/sfx/bundle/shared-framework-distribution-template-x64.xml#L10

> I recommend that .Net 8 be compatible with macOS 10.14.

Making 10.15 allowed solving numerous challenges to help .NET gain support for some cryptographic primitives without a dependency on third party software.

Additionally, it is far too late in the .NET 8 release cycle to consider undoing those changes.

**Comment by zhenlinyang** [comment]
Yes, I can run ```8.0.100-rc.1``` pkg installer on ```macOS 10.14.6```, it did not block installation, and the installation was successful. I can even get this to run fine without using a library that doesn't exist.

**Comment by vcsjones** [comment]
I see. I think the problem is here:

https://github.com/dotnet/installer/blob/a382864dae552097c5a3245bcbf92d226f3d1fe9/src/redist/targets/GeneratePKG.targets#L98

The installer says 10.13 is the minimum here. @akoeplinger should we be bumping this version in the installer?

**Comment by akoeplinger** [comment]
Yes, we do set the min macOS version in dotnet/runtime here which affects e.g. the standalone shared framework .pkg: https://github.com/dotnet/runtime/blob/f21a2666c577306e437f80fe934d76cdb15072a5/Directory.Build.props#L67

I'll send a PR to installer to fix this there too.

**Comment by richlander** [comment]
> Starting from macOS10.15+, macOS no longer supports 32-bit software, which makes projects that rely on 32-bit tool chains unable to run. 

Can you elaborate on that? What's the 32-bit software being discussed? We've only ever offered a 64-bit build for macOS.

**Comment by vcsjones** [comment]
> What's the 32-bit software being discussed?

Apple completely removed the ability to run 32-bit applications on 10.15. I assume the author is saying that, if you have 32-bit apps you still want to run, then you cannot upgrade to 10.15. So they are stuck in a position of needing to stay on 10.14 for 32-bit app support for [some other software].

**Comment by zhenlinyang** [comment]
> > What's the 32-bit software being discussed?
> 
> Apple completely removed the ability to run 32-bit applications on 10.15. I assume the author is saying that, if you have 32-bit apps you still want to run, then you cannot upgrade to 10.15. So they are stuck in a position of needing to stay on 10.14 for 32-bit app support for [some other software] and not being able to use .NET 8.

Yes, I mean that.

**Comment by adamsitnik** [comment]
> [.NET 8 requires macOS 10.15 or later.](https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md#macos)

> macOS 10.14 does not include the CryptoKit library that .NET 8 uses for cryptography purposes.

Since this is by design and the installer is about to get fixed (https://github.com/dotnet/installer/pull/17480), I am closing the issue.
