### ISSUE TITLE
marshalling va_list crossplatform p/invoke binding

### ISSUE THREAD

**Issue by mfkl** [dotnet/runtime#9316]
Hello from VideoLAN!

We're currently implementing a new crossplatform .NET binding over `libvlc` and have ran into a bit of an issue. Our libvlc log callback prototype looks like this:

`typedef void(* libvlc_log_cb) (void *data, int level, const libvlc_log_t *ctx, const char *fmt, va_list args)`

We need to marshal this from native to managed in a crossplatform way.

What is the recommended way to perform `va_list` marshalling with P/Invoke in a crossplatform way (i.e. Xamarin platforms + friends)?

From what we see in [clrvarargs.cpp](https://github.com/dotnet/coreclr/blob/master/src/vm/clrvarargs.cpp), we assume this is currently unsupported on Linux. What is needed to be done to be able to support this?

Related issues:
https://github.com/dotnet/coreclr/issues/9204
https://github.com/dotnet/standard/issues/20

Thanks for any pointers you may provide.

/cc @jeremyVignelles

**Comment by tom-corwin** [comment]
Have there been any updates on this issue? I seem to have ran into this issue as well while looking into writing a binding for [raylib](https://github.com/raysan5/raylib).

**Comment by jeremyVignelles** [comment]
Hello.
We didn't manage to propose a correct API shape, so at VideoLAN, we came up with a manual solution of using the libraries available on the platform :

https://github.com/videolan/libvlcsharp/blob/ff246a39fb9e35541357ffcd90062a8c0cc431f6/src/LibVLCSharp/Shared/LibVLC.cs#L729

https://github.com/videolan/libvlcsharp/blob/ff246a39fb9e35541357ffcd90062a8c0cc431f6/src/LibVLCSharp/Shared/Helpers/MarshalUtils.cs#L66

We're not satisfied with the solution, but it seems to work. Still feels hackish.

We have also explored the possibility to change the API, but we faced strong opposition from the libvlc developpers.

Do you also need that for logs?
Feel free to come and chat with us on the LibVLCSharp gitter 🙂

**Comment by AaronRobinsonMSFT** [comment]
Closing here and tracking in https://github.com/dotnet/runtime/issues/48796.
