### ISSUE TITLE
Deadlock in ThreadPool.GetMaxThreads() during app start.

### ISSUE THREAD

**Issue by avparuch** [dotnet/runtime#93175]
### Description

There is a deadlock that occurs transiently when our .NET 6.0 application is starting. From the call stack, the application is hanging on a call to Threadpool.GetMaxThreads(). Looking at the dump with repro with the 2 deadlocked threads, the deadlock involves locking around the ThreadPool type constructor and a lock taken in the EventListener class:

![image](https://github.com/dotnet/runtime/assets/55294511/11d032ec-259d-4ead-b0b9-e60bbf8080c8)

![image](https://github.com/dotnet/runtime/assets/55294511/53047fce-04d0-4f48-95b7-ae872783c7e4)

The dump has been shared with the .NET team, filing this issue at the request of the .NET team for tracking.

### Reproduction Steps

It's a not trivial repro. It involves running a .NET 6.0 app that calls into Threadpool.GetMaxThreads() during application startup and an external entity (on the same machine) triggering an ETW session that, in turn instantiates EventSource inside the application at the same time.

From David Mason (@davmason):
![image](https://github.com/dotnet/runtime/assets/55294511/ec57ef93-1c5b-432e-aede-27d93a2f8342)

### Expected behavior

No deadlock.

### Actual behavior

There is a deadlock.

### Known Workarounds

@davmason  suggested creating the EventListener explicitly before calling ThreadPool.GetMaxThreads() as a workaround. I can confirm this works.

    class RuntimeEventListener : EventListener
    {
        internal static int eventCount;

        protected override void OnEventSourceCreated(EventSource eventSource)
        {
            base.OnEventSourceCreated(eventSource);

            if (eventSource.Name.Equals("System.Runtime"))
            {
                Dictionary<string, string> refreshInterval = new Dictionary<string, string>();
                refreshInterval["EventCounterIntervalSec"] = "1";
                EnableEvents(source, EventLevel.Informational, (EventKeywords)(-1), refreshInterval);
            }
        }

        protected override void OnEventWritten(EventWrittenEventArgs eventData)
        {
            base.OnEventWritten(eventData);
        }
    }

And then create one at the beginning of Main before calling ThreadPool.GetMaxThreads(): 
                `RuntimeEventListener listener = new RuntimeEventListener();`

### Configuration

.NET 6.0.20

**Comment by mangod9** [comment]
@kouvel, have you seen this issue before?

**Comment by kouvel** [comment]
I haven't seen the issue before, but it makes sense and it sounds like @davmason has looked into it a bit. @davmason, is this something that can be generically fixed from the `EventSource` side? It should be possible to fix from the `ThreadPool` side too, though it may not be the only case where this lock ordering occurs.

**Comment by davmason** [comment]
The problem here is that we try to populate the counter values while holding the EventSource EventListenerLock. We should instead create the counters and not immediately populate the values, then let them populate when the timer fires on a different thread.

**Comment by PJB3005** [comment]
I know this isn't the most productive but I would just like to say that Rider automatically attaches EventPipe on app start now, which makes *any* code that runs ThreadPool's cctor extremely likely to deadlock just on startup. This is now forcing me to disable Rider's monitoring feature as I cannot start my app 5 times in a row from deadlocks.

**Comment by ldy985** [comment]
My team had the same problem with the rider, which led me here.

Note: I needed a way to +1. If anyone else has the problem, make a thumbs-up on @PJB3005's comment.

**Comment by mdh1418** [comment]
I believe this is fixed by https://github.com/dotnet/runtime/pull/105548. I was able to repro the issue on .NET Sdk 8.0.300, and using a local build of runtime with the PR I could not trigger the deadlock.
