### ISSUE TITLE
[Wasm] Very large methods cause interpreter tiering to fail and allocates a lot of unmanaged memory

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/runtime#93192]
### Description

When a very large C# method is encountered the interpreter tries to optimize that method, seemingly fails to do so and leaks memory every time the method is invoked, eventually exhausing the wasm heap.

### Reproduction Steps

Build an app with the following t4 template:

```t4
﻿<#@template language="C#"#>
<#@output extension="g.cs" #>

public class LargeMethodTest
{
    public static Test(string value)
    {
        int value = 0;

        switch(value)
        {
            <# for(int i=0; i<20000; i++) { #>
            case "<#= i #>":
                value++;
                break;
            <# } #>
            default:
            break;
        }
    }
}
```

Then create a loop over the `Test` method:

```csharp
  staticvoid TestLargeSwitchCase()
  {
      var sw = Stopwatch.StartNew();

      // Over 1000 iterations so that tiering kicks in
      for (int i = 0; i < 2000; i++)
      {
          LargeMethodTest.Test("42");
      }

      Console.WriteLine($"Elapsed: {sw.Elapsed}");
  }
```

### Expected behavior

The code does not fail and runs to the end.

### Actual behavior

The app fails as follows:

```
 Cannot enlarge memory, asked to go up to 4294918144 bytes, but the limit is 4294901760 bytes!

_emscripten_resize_heap	@	dotnet.native.js:4293
$sbrk	@	dotnet.native.wasm:0x2ce8fa
$dlmalloc	@	dotnet.native.wasm:0x2cc5b5
$monoeg_malloc	@	dotnet.native.wasm:0x9fbaf
$mono_mempool_alloc	@	dotnet.native.wasm:0x119464
$interp_link_bblocks	@	dotnet.native.wasm:0x8d21e
$handle_branch	@	dotnet.native.wasm:0x8f585
$generate_code	@	dotnet.native.wasm:0x85cbd
$generate	@	dotnet.native.wasm:0x9306d
$mono_interp_transform_method	@	dotnet.native.wasm:0x92b30
$tier_up_method	@	dotnet.native.wasm:0x9c627
$mono_interp_tier_up_frame_enter	@	dotnet.native.wasm:0x9c37b
$mono_interp_exec_method	@	dotnet.native.wasm:0x762dc
$interp_entry	@	dotnet.native.wasm:0x7bbad
$interp_entry_instance_1	@	dotnet.native.wasm:0x7bdb8
$aot_instances_aot_wrapper_gsharedvt_in_sig_void_this_obj
```

Each invocation of the method will show a trace like this one:

![image](https://github.com/dotnet/runtime/assets/5839577/10e34cae-6897-4e42-a39c-7ea4bba681ea)

### Regression?

Not sure, it may have worked before tiering.

### Known Workarounds

Use smaller methods

### Configuration

.NET 8 RC1

**Comment by BrzVlad** [comment]
I'm not seeing any leak here. The method in question contains 20000 calls to `String.op_Equality`, which is being aggressively inlined together with a bunch of span helper code that requires data to be increasingly allocated into the compilation mempool (which is emptied only after the entire method is compiled). Sure we might allocate more data than we need and some data might be candidate for freeing earlier, but I'm not sure doing this is worth it.

Normally we might want to stop inlining if some sort of threshold is reached, but I'm not sure what exactly would make sense here.

**Comment by jeromelaban** [comment]
@BrzVlad thanks for the update! It makes sense, and in a larger app I thought these were multiple calls but that may have been because of the max-depth clipping of the profiler.

Considering Wasm cannot reclaim allocated heap memory, this may be a problem for some, indeed.

**Comment by BrzVlad** [comment]
Some fixes recently addressed compilation performance with some of our vectorization code (https://github.com/dotnet/runtime/pull/97514). Also https://github.com/dotnet/runtime/pull/98701 addresses wasteful memory allocation with the specific scenario from this issue. I'm sure there is still room for improvement. Closing this for now. A closer to real world scenario where excessive memory is allocated during compilation would be helpful.
