### ISSUE TITLE
High number of connections waiting for SSL handshake

### ISSUE THREAD

**Issue by arekpalinski** [dotnet/runtime#93208]
### Description

We have run into an issue where RavenDB server (https://github.com/ravendb/ravendb) has stopped responding to any requests. We noticed high number of connections:

```
sudo netstat -aln | grep 443 | wc -l
5012
```

There were 3630 established and 809 time_wait connections

```
tcp        0      0 10.0.0.4:443            1.2.3.4:23733   ESTABLISHED
tcp        0      0 10.0.0.4:443            1.2.3.4:24537   ESTABLISHED
tcp        0      0 10.0.0.4:443            1.2.3.4:19542   ESTABLISHED
tcp        0      0 10.0.0.4:443            1.2.3.4:3780    ESTABLISHED
tcp        0      0 10.0.0.4:443            1.2.3.4:3853    ESTABLISHED
tcp        0      0 10.0.0.4:443            1.2.3.4:4966    TIME_WAIT
tcp        0      0 10.0.0.4:443            1.2.3.4:18492   ESTABLISHED
tcp        0      0 10.0.0.4:443            1.2.3.4:4557    TIME_WAIT
tcp        0      0 10.0.0.4:443            1.2.3.4:3680    TIME_WAIT
```

After the service restart we got errors that RavenDB server couldn't connect itself over HTTPS using public address. We managed to capture stacktraces. Since no request could be handled there wasn't much activity there. Although there are two stacktraces which seems to be interesting. They are very similar up to `System.Net.Security!System.Net.Security.SslStream.GenerateToken()` call

- multiple threads waiting in `AllocateSslContext()`
```
"ThreadIds": [
        31001,
        31003,
        31005,
        31006,
        31007,
        31008,
        31009,
        31011,
        31013,
        31014,
        31016,
        31019,
        31020,
        31021,
        31022,
        31024,
        31025,
        31026,
        31029,
        31030,
        31031,
        31032,
        31033,
        31034,
        31038,
        31105,
        31107,
        31108,
        31109,
        31110,
        31111,
        31112,
        31113,
        31115,
        31116,
        31117,
        31119,
        31121,
        31122,
        31123,
        31124,
        31155,
        31162,
        31170,
        31197,
        31204,
        31212,
        31223,
        31308,
        31332,
        31341,
        31359,
        31367,
        31368,
        31369,
        31370,
        31371,
        31372,
        31373,
        31374,
        31375,
        31376,
        31377,
        31398,
        31416
      ],
      "StackTrace": [
        "[Native Frames]",
        "?!?",
        "System.Net.Security!Interop+Ssl.SslCtxCreate(int)",
        "System.Net.Security!Interop+OpenSsl.AllocateSslContext(class System.Net.Security.SslAuthenticationOptions,value class System.Security.Authentication.SslProtocols,bool)",
        "System.Net.Security!Interop+OpenSsl.AllocateSslHandle(class System.Net.Security.SslAuthenticationOptions)",
        "System.Net.Security!System.Net.Security.SslStreamPal.HandshakeInternal(class System.Net.Security.SafeDeleteSslContext&,value class System.ReadOnlySpan`1<unsigned int8>,unsigned int8[]&,class System.Net.Security.SslAuthenticationOptions,class System.Net.Security.SelectClientCertificate)",
        "System.Net.Security!System.Net.Security.SslStream.GenerateToken(value class System.ReadOnlySpan`1<unsigned int8>,unsigned int8[]&)",
        "System.Net.Security!System.Net.Security.SslStream.NextMessage(value class System.ReadOnlySpan`1<unsigned int8>)",
        "System.Net.Security!System.Net.Security.SslStream.ProcessBlob(int32)",
        "System.Net.Security!System.Net.Security.SslStream+<ReceiveBlobAsync>d__147`1[System.Net.Security.AsyncReadWriteAdapter].MoveNext()",
        "System.Private.CoreLib!System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start(!!0&)",
        "System.Net.Security!System.Net.Security.SslStream.ReceiveBlobAsync(value class System.Threading.CancellationToken)",
        "System.Net.Security!System.Net.Security.SslStream+<ForceAuthenticationAsync>d__146`1[System.Net.Security.AsyncReadWriteAdapter].MoveNext()",
        "System.Private.CoreLib!System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start(!!0&)",
        "Microsoft.AspNetCore.Server.Kestrel.Core!Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.DoOptionsBasedHandshakeAsync(class Microsoft.AspNetCore.Connections.ConnectionContext,class System.Net.Security.SslStream,class Microsoft.AspNetCore.Server.Kestrel.Core.Internal.TlsConnectionFeature,value class System.Threading.CancellationToken)",
        "Microsoft.AspNetCore.Server.Kestrel.Core!Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware+<OnConnectionAsync>d__17.MoveNext()",
        "System.Private.CoreLib!System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start(!!0&)",
        "Microsoft.AspNetCore.Server.Kestrel.Core!Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(class Microsoft.AspNetCore.Connections.ConnectionContext)",
        "Microsoft.AspNetCore.Server.Kestrel.Core!Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1+<ExecuteAsync>d__6[System.__Canon].MoveNext()",
        "System.Private.CoreLib!System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start(!!0&)",
        "Microsoft.AspNetCore.Server.Kestrel.Core!Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1[System.__Canon].ExecuteAsync()",
        "Microsoft.AspNetCore.Server.Kestrel.Core!Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1[System.__Canon].System.Threading.IThreadPoolWorkItem.Execute()",
        "System.Private.CoreLib!System.Threading.ThreadPoolWorkQueue.Dispatch()",
        "System.Private.CoreLib!System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()"
      ]
    }
```

- one thread doing `OpenSslDirectoryBasedStoreProvider.OpenDisallowedStore()` and apparently hanging on `Directory.Exists()`

```
{
      "ThreadIds": [
        31448
      ],
      "StackTrace": [
        "[Native Frames]",
        "System.Private.CoreLib!Interop+Sys.Stat(unsigned int8&,value class FileStatus&)",
        "System.Private.CoreLib!Interop+Sys.Stat(value class System.ReadOnlySpan`1<wchar>,value class FileStatus&)",
        "System.Private.CoreLib!System.IO.Directory.Exists(class System.String)",
        "System.Security.Cryptography!System.Security.Cryptography.X509Certificates.OpenSslDirectoryBasedStoreProvider.OpenDisallowedStore(value class System.Security.Cryptography.X509Certificates.OpenFlags)",
        "System.Security.Cryptography!System.Security.Cryptography.X509Certificates.ChainPal.BuildChainCore(bool,class System.Security.Cryptography.X509Certificates.ICertificatePal,class System.Security.Cryptography.X509Certificates.X509Certificate2Collection,class System.Security.Cryptography.OidCollection,class System.Security.Cryptography.OidCollection,value class System.Security.Cryptography.X509Certificates.X509RevocationMode,value class System.Security.Cryptography.X509Certificates.X509RevocationFlag,class System.Security.Cryptography.X509Certificates.X509Certificate2Collection,value class System.Security.Cryptography.X509Certificates.X509ChainTrustMode,value class System.DateTime,value class System.TimeSpan,bool)",
        "System.Security.Cryptography!System.Security.Cryptography.X509Certificates.ChainPal.BuildChain(bool,class System.Security.Cryptography.X509Certificates.ICertificatePal,class System.Security.Cryptography.X509Certificates.X509Certificate2Collection,class System.Security.Cryptography.OidCollection,class System.Security.Cryptography.OidCollection,value class System.Security.Cryptography.X509Certificates.X509RevocationMode,value class System.Security.Cryptography.X509Certificates.X509RevocationFlag,class System.Security.Cryptography.X509Certificates.X509Certificate2Collection,value class System.Security.Cryptography.X509Certificates.X509ChainTrustMode,value class System.DateTime,value class System.TimeSpan,bool)",
        "System.Security.Cryptography!System.Security.Cryptography.X509Certificates.X509Chain.Build(class System.Security.Cryptography.X509Certificates.X509Certificate2,bool)",
        "System.Net.Security!System.Net.Security.SslStreamCertificateContext.Create(class System.Security.Cryptography.X509Certificates.X509Certificate2,class System.Security.Cryptography.X509Certificates.X509Certificate2Collection,bool,class System.Net.Security.SslCertificateTrust,bool)",
        "System.Net.Security!System.Net.Security.SslStream.AcquireServerCredentials(unsigned int8[]&)",
        "System.Net.Security!System.Net.Security.SslStream.GenerateToken(value class System.ReadOnlySpan`1<unsigned int8>,unsigned int8[]&)",
        "System.Net.Security!System.Net.Security.SslStream.NextMessage(value class System.ReadOnlySpan`1<unsigned int8>)",
        "System.Net.Security!System.Net.Security.SslStream.ProcessBlob(int32)",
        "System.Net.Security!System.Net.Security.SslStream+<ReceiveBlobAsync>d__147`1[System.Net.Security.AsyncReadWriteAdapter].MoveNext()",
        "System.Private.CoreLib!System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start(!!0&)",
        "System.Net.Security!System.Net.Security.SslStream.ReceiveBlobAsync(value class System.Threading.CancellationToken)",
        "System.Net.Security!System.Net.Security.SslStream+<ForceAuthenticationAsync>d__146`1[System.Net.Security.AsyncReadWriteAdapter].MoveNext()",
        "System.Private.CoreLib!System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start(!!0&)",
        "Microsoft.AspNetCore.Server.Kestrel.Core!Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.DoOptionsBasedHandshakeAsync(class Microsoft.AspNetCore.Connections.ConnectionContext,class System.Net.Security.SslStream,class Microsoft.AspNetCore.Server.Kestrel.Core.Internal.TlsConnectionFeature,value class System.Threading.CancellationToken)",
        "Microsoft.AspNetCore.Server.Kestrel.Core!Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware+<OnConnectionAsync>d__17.MoveNext()",
        "System.Private.CoreLib!System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start(!!0&)",
        "Microsoft.AspNetCore.Server.Kestrel.Core!Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(class Microsoft.AspNetCore.Connections.ConnectionContext)",
        "Microsoft.AspNetCore.Server.Kestrel.Core!Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1+<ExecuteAsync>d__6[System.__Canon].MoveNext()",
        "System.Private.CoreLib!System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start(!!0&)",
        "Microsoft.AspNetCore.Server.Kestrel.Core!Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1[System.__Canon].ExecuteAsync()",
        "Microsoft.AspNetCore.Server.Kestrel.Core!Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1[System.__Canon].System.Threading.IThreadPoolWorkItem.Execute()",
        "System.Private.CoreLib!System.Threading.ThreadPoolWorkQueue.Dispatch()",
        "System.Private.CoreLib!System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()"
      ]
    }
```
    
RavenDB server was running as `ravendb` user. There isn't any `disallowed` directory under `.dotnet/corefx/cryptography/x509stores/`
    
```
> sudo ls -l /home/ravendb/.dotnet/corefx/cryptography/x509stores/
total 4
drwxr-xr-x 2 ravendb ravendb 4096 Oct 29  2022 ca
```

It happened on Ubuntu 22. 

Can you advise anything to help investigating that if it happens again in the future? We know we could use `strace` but now it's already after the fact. If you can recommend something that would be helpful.
    

### Reproduction Steps

We don't have a way to reproduce consistently.

### Expected behavior

Connections will be established

### Actual behavior

Multiple connections waiting for SSL handshake

### Configuration

- .NET 7.0 SDK (v7.0.401) 
- Ubuntu 22
- x64

**Comment by rzikm** [comment]
Since the code is a third party one, did you consider opening an issue on RavenDB repository?

As for additional info, it would be useful to know where in OpenSSL those threads are being stuck (the callstack points to SSL_CTX_new, but still it would be good to know if there is a specific global lock that all threads are trying to grab. Try installing openssl debug symbols and check.

I have no knowledge of why would a call to `stat` hang. Are you sure the thread was stuck there all the time?.

**Comment by rzikm** [comment]
There are potentially some locks in openssl, that’s why I suggested installing debug symbols for openssl and checking the native callstack, that might uncover something.

Tagging @wfurt in case he has some other ideas.

**Comment by wfurt** [comment]
This question is if the call is really stack there or if it just happen to be there at the moment when the stack was done. 
cc: @tmds for any more shouts on kernel IO. 

Is there option for you to to downgrade OS @arekpalinski? I cannot point at specifics but Ubuntu 22 comes with OpenSSL  3.0 and that had many issues around locking and new internal architecture. Using Ubuntu 20 _may_ be interim workaround. 

This is also curious as there should be only need to create the context once per server/certificate. If we see SSL_CTX_new  during "normal" operation we should investigate IMHO.

**Comment by rzikm** [comment]
> This is also curious as there should be only need to create the context once per server/certificate. If we see SSL_CTX_new during "normal" operation we should investigate IMHO.

I think it is because the server code does not pass the certificate as `ServerCertificateContext`, so the context does not get reused and new one is created for each connection.

https://github.com/search?q=repo%3Aravendb%2Fravendb%20SslServerAuthenticationOptions&type=code

@arekpalinski That is something we would recommend to change anyway if your targetting allows that. Instead of passing the `X509Certificate2` instance directly, create the `SslServerCertificateContext` once and reuse it across SslStream instances. See
- https://learn.microsoft.com/en-us/dotnet/api/system.net.security.sslserverauthenticationoptions.servercertificatecontext?view=net-7.0
- https://learn.microsoft.com/en-us/dotnet/core/extensions/sslstream-best-practices#specify-a-server-certificate

The certificate context option avoids some repeated operations and allows for features such as TLS/SSL resume which will further reduce resource usage.

**Comment by wfurt** [comment]
I think that is handled by asp.net
https://github.com/dotnet/aspnetcore/blob/e4aac84b8cc256c584a41abe8335457063613470/src/Servers/Kestrel/Core/src/Middleware/HttpsConnectionMiddleware.cs#L58

I assume the context would be always used, right @Tratcher ?

**Comment by Tratcher** [comment]
Yes, we take care of that in .NET 7+
https://github.com/dotnet/aspnetcore/blob/e4aac84b8cc256c584a41abe8335457063613470/src/Servers/Kestrel/Core/src/Middleware/HttpsConnectionMiddleware.cs#L106-L108

**Comment by arekpalinski** [comment]
@rzikm Thanks for the hint regarding `SslServerCertificateContext`. We already had it planned and will bump the priority of this.

@wfurt 
The downgrade of OS isn't an option that we'd like to go. 
That's interesting and a bit worrying:
> Ubuntu 22 comes with OpenSSL 3.0 and that had many issues around locking and new internal architecture

We're investigating this in the direction that it was somehow connected to much higher number of connections than usual. So maybe then it was easier to run into the lock issue inside openssl.

**Comment by rzikm** [comment]
> I think that is handled by asp.net

> Yes, we take care of that in .NET 7+, unless you're using the server cert selection callback.

I am sure ASP.NET uses it under the cover, but I said it because I saw it being passed to the `SslStream.AuthenticateAsServerAsync` directly in the codebase, hence the link to code search https://github.com/search?q=repo%3Aravendb%2Fravendb%20SslServerAuthenticationOptions&type=code

**Comment by rzikm** [comment]
> Thanks for the hint regarding SslServerCertificateContext. We already had it planned and will bump the priority of this.

@arekpalinski, let us know once you are able to test out that change. Meanwhile, I don't see anything more that would be actionable on our side, unless you can share memory dumps for us to investigate (you can share those privately on my work mail radekzikmund (at) microsoft.com).

**Comment by ppekrol** [comment]
I've opened PR for this https://github.com/ravendb/ravendb/pull/17507 (WIP)
But not sure if this is the issue, because there are only two places where we are using SslServerAuthenticationOptions directly
1. PostgreSQL integration
2. TCP connections

From the stack that @arekpalinski pasted before, we see that Kestrel is involved, which would point me more into HTTPS flow.

The third place that touches that is: https://github.com/ravendb/ravendb/blob/v6.0/src/Raven.Server/Https/HttpsConnectionMiddleware.cs 
here: https://github.com/ravendb/ravendb/blob/d04e3e50001466f495e12fce6c6f6c5c7a3eda41/src/Raven.Server/Https/HttpsConnectionMiddleware.cs#L61

Configured like that:
```
                                listenOptions
                                    .UseHttps()
                                    .Use(_httpsConnectionMiddleware.OnConnectionAsync);
```

But I'm assuming as @rzikm wrote that Kestrel/ASP.NET is handling that properly underneath anyway? 

We will continue investigation and report back.

**Comment by rzikm** [comment]
> Yes, we take care of that in .NET 7+, unless you're using the server cert selection callback.

ravendb is using the cert selection callback here:

https://github.com/ravendb/ravendb/blob/v6.0/src/Raven.Server/Https/HttpsConnectionMiddleware.cs#L58

so I think that is the cause why the SslCtxContext is not being cached.

**Comment by arekpalinski** [comment]
That's right. We are using the cert selection calback because we're handling the renewals of Let's encrypt certificates automatically. 

We opened a new PR where we're using `ServerCertificate` instead of `ServerCertificateSelector` and use `OnAuthenticate()` callback to check if the certificate got changed, if so then we update the cert and ssl context via `sslServerAuthenticationOptions`:

https://github.com/ravendb/ravendb/pull/17511/files#diff-1253ffbf38108f263294a83bebdea685e76a600ee1ad1694391b3da797c949eaL59-R74

We wonder what's the issue with using the callback. Couldn't it create the ssl context then as well, and update it only if the callback returns a different cert?

**Comment by wfurt** [comment]
Note that there is also https://learn.microsoft.com/en-us/dotnet/api/system.net.security.sslstream.authenticateasserverasync?view=net-8.0#system-net-security-sslstream-authenticateasserverasync(system-net-security-serveroptionsselectioncallback-system-object-system-threading-cancellationtoken) capable of returning whole SslOptions including the context. With that you would be able to keep the current flow if you wish. 

And the callback returns `ValueTask<SslServerAuthenticationOptions>` e.g. one can do Async work inside if needed.

**Comment by Tratcher** [comment]
> We wonder what's the issue with using the callback. Couldn't it create the ssl context then as well, and update it only if the callback returns a different cert?

ServerCertificateSelector is for advanced scenarios and we make no assumptions about anything. It's up to the caller to do any caching.

The best extension to use here is public static ListenOptions UseHttps(this ListenOptions listenOptions, TlsHandshakeCallbackOptions callbackOptions)​, so you don't need to set a cert or context in advance, you always choose it in the callback.
https://github.com/dotnet/aspnetcore/blob/3d83ad986828391652e48ebd037c5f485b4edd26/src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs#L248


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by arekpalinski** [comment]
I'd like to confirm that the issue was related to the usage of `ServerCertificateSelector` callback. Once we moved away from using it we no longer see the problem with unresponsive RavenDB nodes even if many connections are established. We're able to handle much more connections, everything is operational even if the system is heavily stressed. Thank you all or your help.
