### ISSUE TITLE
System.GC.Name: "clrgc.dll" not working in docker

### ISSUE THREAD

**Issue by nsinitsyn** [dotnet/runtime#93218]
We use .NET 7 application with old gc by set next parameter in runtimeconfig.template.json file:
`"System.GC.Name": "clrgc.dll"`
and it's work in Windows.
But now we are trying to use this application in docker (Linux) and got the next error with starting:
`GC initialization failed with error 0x8007007E`
`Failed to create CoreCLR, HRESULT: 0x8007007E`

If we remove System.GC.Name parameter then it's work in docker. But it's important to run application with this parameter for us.

Also I created the simple console application with the same behavior in docker which confirms the problem is in System.GC.Name parameter.

**Comment by mangod9** [comment]
on linux the standalone GC is named libclrgc.so. So you should change the config to 
`System.GC.Name": "libclrgc.so"`

That said we have fixed a bunch of issues with GC Regions in latest 7 servicing releases. Is there a reason you need to fallback still? Thx.

**Comment by nsinitsyn** [comment]
Thanks! It works. I think we will remove this parameter after .NET 8 release and check our case.
