### ISSUE TITLE
DotNet6.0 - Incorrect DateTimeFormat for CultureInfo

### ISSUE THREAD

**Issue by Kushagra6154** [dotnet/runtime#93215]
### Description

new CultureInfo(“en-in”,false).DateTimeFormat.FirstDayOfWeek

When using the bove code dateTimeFormat does not return correct value for different cultures when testing on different locale machine.
For example when trying to access the DateTimeFormat values on “en-us” prod machine for “en-in”, 6.0.22 returns Monday but 7.0.11 return Sunday(correct)
 
dotnet --fx-version 6.0.22 TestFirstDayOfWeek.dll
Hello, World!
en-US
Sunday 
en-IN
Monday
dotnet --fx-version 7.0.11 TestFirstDayOfWeek.dll
Hello, World!
en-US
Sunday 
en-IN
Sunday 

Similarly for the LongDatePattern 

new CultureInfo(“ja-jp”,false).DateTimeFormat.LongDatePattern
Expected: yyyy年M月d日dddd
Actual: yyyy'年'M'月'd'日'

### Reproduction Steps

Run below code on US machine on 6.0.22 and 7.0.11

new CultureInfo(“en-in”,false).DateTimeFormat.FirstDayOfWeek

new CultureInfo(“ja-jp”,false).DateTimeFormat.LongDatePattern

### Expected behavior

FirstDayOfWeek(en-in): Sunday
LongDatePattern(ja-jp) : yyyy年M月d日dddd

### Actual behavior

FirstDayOfWeek(en-in): Sunday
LongDatePattern(ja-jp): yyyy'年'M'月'd'日'

**Comment by tarekgh** [comment]
@Kushagra6154 were you running `6.0.22` and `7.0.11` on the same machine? I am asking because if you are running on different machines, it is possible each machine has different version of ICU library which can have different globalization data. Would be good if you can share more info by running the following code in both cases and send the output:

```C#
        public static void PrintEnvironmentInfo()
        {
            try { CultureInfo ci = CultureInfo.GetCultureInfo("ja-JP"); } catch {}

            Console.WriteLine($"{RuntimeInformation.OSDescription}");
            Console.WriteLine($"{RuntimeInformation.FrameworkDescription}");
            try
            {
                foreach (ProcessModule module in Process.GetCurrentProcess().Modules)
                {
                    if (module.FileName!.Contains("icu"))
                        Console.WriteLine($".... {module.FileName}: {module.FileVersionInfo.FileVersion}");
                }

                Type? interopGlobalization = Type.GetType("Interop+Globalization, System.Private.CoreLib");
                if (interopGlobalization != null)
                {
                    MethodInfo? methodInfo = interopGlobalization.GetMethod("GetICUVersion", BindingFlags.NonPublic | BindingFlags.Static);
                    if (methodInfo != null)
                    {
                        int version = (int)methodInfo.Invoke(null, null)!;
                        Console.WriteLine($".... ICU Version: {new Version(version >> 24, (version >> 16) & 0xFF, (version >> 8) & 0xFF, version & 0xFF)}");
                    }
                }

#pragma warning disable IL2026
#pragma warning disable IL2075
                Console.WriteLine($".... UseNls:                 {typeof(object).Assembly.GetType("System.Globalization.GlobalizationMode")!.GetProperty("UseNls", BindingFlags.Static | BindingFlags.NonPublic)!.GetValue(null)} ....");
                Console.WriteLine($".... Invariant:              {typeof(object).Assembly.GetType("System.Globalization.GlobalizationMode")!.GetProperty("Invariant", BindingFlags.Static | BindingFlags.NonPublic)!.GetValue(null)} ....");
                Console.WriteLine($".... PredefinedCulturesOnly: {typeof(object).Assembly.GetType("System.Globalization.GlobalizationMode")!.GetProperty("PredefinedCulturesOnly", BindingFlags.Static | BindingFlags.NonPublic)!.GetValue(null)} ....");
#pragma warning restore IL2075
#pragma warning restore IL2026
            }
            catch
            {
                Console.WriteLine($".... UseNls: Couldn't Evaluate it ....");
            }
        }
```

**Comment by Kushagra6154** [comment]
@tarekgh We ran both dotnet6 and dotnet7 on the same machine

dotnet --fx-version 6.0.22 TestFirstDayOfWeek.dll
CurrentCulture: en-US
FirstDayOfWeek: Sunday
LongDatePattern: dddd, MMMM d, yyyy

Setting CurrentCulture to ja-jp
FirstDayOfWeek: Sunday
LongDatePattern: yyyy'?'M'?'d'?'

Setting CurrentCulture to en-in
FirstDayOfWeek: Monday
LongDatePattern: dd MMMM yyyy

OSDescription: Microsoft Windows 10.0.17763
FrameworkDescription: .NET 6.0.22
.... ICU Version: 0.0.0.0
.... UseNls:                 True ....
.... Invariant:              False ....
.... PredefinedCulturesOnly: False ....

dotnet --fx-version 7.0.11 TestFirstDayOfWeek.dll
CurrentCulture: en-US
FirstDayOfWeek: Sunday
LongDatePattern: dddd, MMMM d, yyyy

Setting CurrentCulture to ja-jp
FirstDayOfWeek: Sunday
LongDatePattern: yyyy?M?d?dddd

Setting CurrentCulture to en-in
FirstDayOfWeek: Sunday
LongDatePattern: dddd, d MMMM, yyyy

OSDescription: Microsoft Windows 10.0.17763
FrameworkDescription: .NET 7.0.11
.... C:\Windows\SYSTEM32\icuuc.dll: 61, 1, 0, 0
.... C:\Windows\SYSTEM32\icuin.dll: 61, 1, 0, 0
.... ICU Version: 61.1.0.0
.... UseNls:                 False ....
.... Invariant:              False ....
.... PredefinedCulturesOnly: False ....

`using System.Diagnostics;
using System.Globalization;
using System.Reflection;
using System.Runtime.InteropServices;

 

Console.WriteLine("CurrentCulture: " + CultureInfo.CurrentCulture.Name);
Console.WriteLine("FirstDayOfWeek: "+ CultureInfo.CurrentCulture.DateTimeFormat.FirstDayOfWeek);
Console.WriteLine("LongDatePattern: " + CultureInfo.CurrentCulture.DateTimeFormat.LongDatePattern);
Console.WriteLine();

 

Console.WriteLine("Setting CurrentCulture to " + "ja-jp");
CultureInfo.CurrentCulture = new CultureInfo("ja-jp", false);
Console.WriteLine("FirstDayOfWeek: " + CultureInfo.CurrentCulture.DateTimeFormat.FirstDayOfWeek);
Console.WriteLine("LongDatePattern: " + CultureInfo.CurrentCulture.DateTimeFormat.LongDatePattern);
Console.WriteLine();

 

 

Console.WriteLine("Setting CurrentCulture to " + "en-in");
CultureInfo.CurrentCulture = new CultureInfo("en-in", false);
Console.WriteLine("FirstDayOfWeek: " + CultureInfo.CurrentCulture.DateTimeFormat.FirstDayOfWeek);
Console.WriteLine("LongDatePattern: " + CultureInfo.CurrentCulture.DateTimeFormat.LongDatePattern);
Console.WriteLine();

 

 

Console.WriteLine($"OSDescription: {RuntimeInformation.OSDescription}");
Console.WriteLine($"FrameworkDescription: {RuntimeInformation.FrameworkDescription}");
try
{
    foreach (ProcessModule module in Process.GetCurrentProcess().Modules)
    {
        if (module.FileName!.Contains("icu"))
            Console.WriteLine($".... {module.FileName}: {module.FileVersionInfo.FileVersion}");
    }

 

    Type? interopGlobalization = Type.GetType("Interop+Globalization, System.Private.CoreLib");
    if (interopGlobalization != null)
    {
        MethodInfo? methodInfo = interopGlobalization.GetMethod("GetICUVersion", BindingFlags.NonPublic | BindingFlags.Static);
        if (methodInfo != null)
        {
            int version = (int)methodInfo.Invoke(null, null)!;
            Console.WriteLine($".... ICU Version: {new Version(version >> 24, (version >> 16) & 0xFF, (version >> 8) & 0xFF, version & 0xFF)}");
        }
    }

 

#pragma warning disable IL2026
#pragma warning disable IL2075
    Console.WriteLine($".... UseNls:                 {typeof(object).Assembly.GetType("System.Globalization.GlobalizationMode")!.GetProperty("UseNls", BindingFlags.Static | BindingFlags.NonPublic)!.GetValue(null)} ....");
    Console.WriteLine($".... Invariant:              {typeof(object).Assembly.GetType("System.Globalization.GlobalizationMode")!.GetProperty("Invariant", BindingFlags.Static | BindingFlags.NonPublic)!.GetValue(null)} ....");
    Console.WriteLine($".... PredefinedCulturesOnly: {typeof(object).Assembly.GetType("System.Globalization.GlobalizationMode")!.GetProperty("PredefinedCulturesOnly", BindingFlags.Static | BindingFlags.NonPublic)!.GetValue(null)} ....");
#pragma warning restore IL2075
#pragma warning restore IL2026
}
catch
{
    Console.WriteLine($".... UseNls: Couldn't Evaluate it ....");
}`

**Comment by tarekgh** [comment]
I noticed you have `... UseNls: True ....` when running with .NET 6.0. This means you have enabled the NLS mode when compiling against 6.0. This is why you are seeing the difference. You may look at https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#use-nls-instead-of-icu to know how the NLS mode can be enabled so you can disable it. After doing that you should see consistent results with 7.0. I am closing the issue but feel free to reply back with any question if you have any.

**Comment by Kushagra6154** [comment]
@tarekgh We tried disabling the NLS by useNLS but it still gave it as True

dotnet TestFirstDayOfWeek.dll
OSDescription: Microsoft Windows 10.0.17763
FrameworkDescription: .NET 6.0.22
.... ICU Version: 0.0.0.0
.... UseNls:                 True ....

We are running dotnet 6 on windows server 2019 while ICU is supported on windows server 2022 and above. We suspect this is why it is falling back to NLS. Is this correct understanding?

Could you please help us with below questions
- Why is NLS not giving correct datetimeformat?
- How do we enable ICU on older windows server?

**Comment by Clockwork-Muse** [comment]
>Why is NLS not giving correct datetimeformat?

This is an incorrect perception of what's happening.  
To an extent, localized formats are subjective, and there may not be a single correct answer.  Even on newer systems using ICU, those libraries are updated multiple times a year, so the format values change (Linux generally updates these quickly, but Windows releases these on a slower cadence, last I knew).  You should generally expect that different systems will have different formats for cultures.

If you're using dotnet core, is running on a Linux server possible, say inside a Docker container?

**Comment by tarekgh** [comment]
> We are running dotnet 6 on windows server 2019 while ICU is supported on windows server 2022 and above. We suspect this is why it is falling back to NLS. Is this correct understanding?

.NET 6.0 doesn't support loading ICU on Windows Server 2019. We added support for loading ICU in .NET 7.0 https://learn.microsoft.com/en-us/dotnet/core/compatibility/globalization/7.0/icu-globalization-api. 
If you want to enable loading ICU on Windows Server 2019, you can use ICU app-locale https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#app-local-icu which you can deploy the ICU with your app. 

> Why is NLS not giving correct datetimeformat?

@Clockwork-Muse is correct. In general, what you are getting from ICU is more recent and correct data if you compare it to NLS. ICU data is picked up from Unicode CLDR https://github.com/unicode-org/cldr/tree/main/common/main which should reflect the most updated data. If you disagree with any data there, you can file a ticket to discuss it.
