### ISSUE TITLE
Reading file on an Kubernetes NFS volume with dotnet 6 application freezes thread

### ISSUE THREAD

**Issue by aloene** [dotnet/runtime#93227]
### Description

I am deploying a dotnet 6 application (API) to OpenShift.
Our OpenShift cluster provides a preconfigured NFS StorageClass to be used by applications.

I already used this storage class with Java applications without any issue with ReadWriteMany PVC.

When trying to **read** files with my dotnet 6 application, the current thread freezes on trying to (probably) lock file (eg. File.ReadAllBytes() or other classes used by external libraries).
This is an example of the call stack after such freeze :
```
System.Private.CoreLib!Microsoft.Win32.SafeHandles.SafeFileHandle.Init(class System.String,value class System.IO.FileMode,value class System.IO.FileAccess,value class System.IO.FileShare,value class System.IO.FileOptions,int64)
  System.Private.CoreLib!Microsoft.Win32.SafeHandles.SafeFileHandle.Open(class System.String,value class System.IO.FileMode,value class System.IO.FileAccess,value class System.IO.FileShare,value class System.IO.FileOptions,int64)
  System.Private.CoreLib!System.IO.Strategies.OSFileStreamStrategy..ctor(class System.String,value class System.IO.FileMode,value class System.IO.FileAccess,value class System.IO.FileShare,value class System.IO.FileOptions,int64)
  System.Private.CoreLib!System.IO.Strategies.FileStreamHelpers.ChooseStrategy(class System.IO.FileStream,class System.String,value class System.IO.FileMode,value class System.IO.FileAccess,value class System.IO.FileShare,int32,value class System.IO.FileOptions,int64)
  System.Private.CoreLib!System.IO.File.Open(class System.String,value class System.IO.FileMode,value class System.IO.FileAccess,value class System.IO.FileShare)
```
Note 1: **Writing** files works from the same dotnet 6 application.
Note 2: I can successfully read and write files with the same user in container without dotnet.

I assume this is a locking issue but I do not how to fix it for now.
Are there guidelines for setting up this NFS Storage class on OpenShift side ? May wrong mount options have been used ? I could share this information with admins.
Is it a known bug (I could find this one I believe to be exactly the same: #32738) ?
Any idea to fix/workaround it ?

### Reproduction Steps

* Create a dotnet 6 application that will create a file and then will read it with File.ReadAllBytes()
* Deploy the application to OpenShift and use a PVC volume based on an NFS StorageClass for file path 
* Try to run application

### Expected behavior

The application should run and should be able to read file.

### Actual behavior

The application freezes on file reading. (no exception)

### Regression?

Do not know.

### Known Workarounds

None

### Configuration

.NET 6 + ASP.NET (API)
Rootless ubi8/dotnet on OpenShift (x64)

**Comment by aloene** [comment]
After having created this issue, I have found I can prevent dotnet from locking files with the `DOTNET_SYSTEM_IO_DISABLEFILELOCKING` environment variable to `true`... Mentioned [here](https://devblogs.microsoft.com/dotnet/file-io-improvements-in-dotnet-6/#unix).
This fixes the issue.

**Comment by danmoseley** [comment]
Reopening so the area owners can verify this is expected.

**Comment by tmds** [comment]
> Are there guidelines for setting up this NFS Storage class on OpenShift side ? May wrong mount options have been used ? I could share this information with admins.

Here you find some information: https://github.com/dotnet/runtime/issues/48757#issuecomment-1041277707.

**Comment by tmds** [comment]
@aloene were you able to resolve the issue?

**Comment by aloene** [comment]
> @aloene were you able to resolve the issue?

Yes, by using environment variable as mentioned above (https://github.com/dotnet/runtime/issues/93227#issuecomment-1753272038)

**Comment by aloene** [comment]
> > Are there guidelines for setting up this NFS Storage class on OpenShift side ? May wrong mount options have been used ? I could share this information with admins.
> 
> Here you find some information: [#48757 (comment)](https://github.com/dotnet/runtime/issues/48757#issuecomment-1041277707).

Thanks for this explanation btw.
