### ISSUE TITLE
Apply `[ExcludeFromCodeCoverage]` to generated code

### ISSUE THREAD

**Issue by gfoidl** [dotnet/runtime#93236]
Code generated by source generators accounts to code coverage results too (w/o any adanved configuration).
As the generators often spit our more code (standard boilerplate, etc.) than what's actually executed the results for coverage may get biased (in a sense that the generated code isn't under the control of the user writing the code that should be covered).

So should generated code be decorated with `[ExcludeFromCodeCoverage]`?

A simple example for repro:
```c#
using System.Text.RegularExpressions;

public class WithPlainRegex
{
    public bool IsMatched(string input)
    {
        return Regex.IsMatch(input, @"\w+");
    }
}

public partial class WithGeneratedRegex
{
    public bool IsMatched(string input)
    {
        return Get().IsMatch(input);
    }

    [GeneratedRegex(@"\w+")]
    private static partial Regex Get();
}
```

<details>
  <summary>Test code</summary>

```c#
using NUnit.Framework;

[TestFixture]
public class Tests
{
    [Test]
    public void WithPlainRegexTest()
    {
        WithPlainRegex sut = new();

        bool actual = sut.IsMatched("foobar");

        Assert.That(actual, Is.True);
    }

    [Test]
    public void WithGeneratedRegexTest()
    {
        WithGeneratedRegex sut = new();

        bool actual = sut.IsMatched("foobar");

        Assert.That(actual, Is.True);
    }
}
```
</details>

Coverage (collected with `coverlet.msbuild`, report created with `reportgenerator` global tool no special config, etc.) reports:

![grafik](https://github.com/dotnet/runtime/assets/5755834/1314bb39-5cf4-4bb8-a2e3-761d306b9dd4)

**Comment by buyaa-n** [comment]
Makes sense to me, if @stephentoub supportive, we can put `help-wanted` attribute

**Comment by stephentoub** [comment]
Generated code is already annotated as such, e.g.
```C#
[GeneratedCodeAttribute("System.Text.RegularExpressions.Generator", "8.0.8.47906")]
```
I don't think we should be making a call on all consumers behalf that this code is not relevant for code coverage.  Instead, code coverage tooling can be told to ignore generated code, e.g. with coverlet using `--exclude-by-attribute 'GeneratedCode'`. There are even testing benefits to not applying ExcludeFromCodeCoverage. With regex, for example, I can tell now how much my tests are exercising my regex.

**Comment by buyaa-n** [comment]
> I don't think we should be making a call on all consumers behalf that this code is not relevant for code coverage. Instead, code coverage tooling can be told to ignore generated code, e.g. with coverlet using `--exclude-by-attribute 'GeneratedCode'`.

Thanks, closing as not planned
