### ISSUE TITLE
R2RDumpTests failing under gcstress with "App Exit Code: 259"

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#93233]
### Error Blob

```json
{
  "ErrorMessage": "",
  "BuildRetry": false,
  "ErrorPattern": "Running test: readytorun/r2rdump/FrameworkTests/R2RDumpTests/R2RDumpTests.dll\\nApp Exit Code: 259",
  "ExcludeConsoleLog": false
}
```

### Reproduction Steps

See readytorun.0.1 work item failures in https://dev.azure.com/dnceng-public/public/_build/results?buildId=431262&view=ms.vss-test-web.build-test-results-tab&runId=9537426&resultId=166901&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=431262
**Error message validated:** `Running test: readytorun/r2rdump/FrameworkTests/R2RDumpTests/R2RDumpTests.dll\nApp Exit Code: 259`
**Result validation: :x:** Known issue did not match with the provided build.
**Validation performed at:** 10/9/2023 3:27:25 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by mangod9** [comment]
@trylek @cshung

**Comment by jakobbotsch** [comment]
Also cc @markples, I seem to recall him having some similar issues around GCStress when doing the JIT test merging. Not sure how we ended up resolving it.

**Comment by markples** [comment]
This test needs to have RequiresProcessIsolation set. The merged infrastructure doesn't handle GCStressIncompatible, so we need to go back to the cmd/sh logic for now. @trylek Can you please check the steps that you used to convert this directory to see if there are any others like this? (Did ILTransform miss it, or was another technique used here?)
