### ISSUE TITLE
LINQ Groupby has no memory efficient implementation

### ISSUE THREAD

**Issue by ckilmer** [dotnet/runtime#93237]
### Description
The existing api signature for Groupby Enumerable extensions all implement the `IGrouping<TKey, TElement>` interface using an array to store `TElement` see [here](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq/src/System/Linq/Grouping.cs#L54). Given `IGrouping` only needs to implement `IEnumerable` interface, there is opportunity for differed execution on the grouping, such that groups do not need to be stored in memory if the input is known to be sorted by `TKey` selector.

This causes groupby to store all records immediately into memory, even if they are not needed. Examples could be reading a query result set from a database, where the records are sorted by key, and some internal group operation is done, then written to a file.

See example at: https://github.com/ckilmer/MemoryEfficientGroupBy for an example implementation that does not have this problem

**Comment by eiriktsarpalis** [comment]
> See example at: https://github.com/ckilmer/MemoryEfficientGroupBy for an example implementation that does not have this problem

> Assumes that the IEnumerable is "sorted" by the key selector.
> Sorted is used loosely to mean items with equivalent keys are guaranteed to be adjacent

This is a pretty strong precondition that invalidates most use cases for `GroupBy`. How would you rewrite your example such that:

1. it removes the need for matching keys being adjacent,
2. enumerating the second grouping isn't dependent on having enumerated the first grouping and
3. ensures that individual groupings can be enumerated in a thread-safe manner.

More importantly though, would such an implementation show improved memory efficiency in benchmarks in a way that doesn't regress performance? If so, then we might consider a potential improvement.

**Comment by Clockwork-Muse** [comment]
> ensures that individual groupings can be enumerated in a thread-safe manner.

LINQ isn't generally otherwise threadsafe, though.

> Examples could be reading a query result set from a database, where the records are sorted by key, and some internal group operation is done

Databases are more likely to have built-in grouping operations than ordering operations as a query function.  On top of that, in most cases the database will be able to perform the grouping operation more efficiently than the application server.

**Comment by eiriktsarpalis** [comment]
> LINQ isn't generally otherwise threadsafe, though.

Generally speaking a LINQ `IEnumerable<T>` should be thread-safe to enumerate (modulo mutation in source collections, or side-effects in LINQ lambdas). Extending this principle to Linq methods that return multiple enumerables (in this case enumerables of enumerables) it should be possible to enumerate each individual grouping independent of each other. The existing `GroupBy` implementation achieves this using a backing array for each grouping, the proposed implementation however doesn't.
