### ISSUE TITLE
System.Diagnostics.Metrics - Prevent Instrument memory leak

### ISSUE THREAD

**Issue by slang25** [dotnet/runtime#93241]
We've recently ran into a memory leak in production, which ultimately was our fault but could have been saved with an analyzer, and would be an easy thing for other developers to fall into without it.

Sample code (adapted from the docs);
```csharp
static Meter s_meter = new Meter("HatCo.Store");
Counter<int> s_hatsSold = s_meter.CreateCounter<int>("hatco.store.hats_sold");
```

In the above case, the `Meter` has been correctly initialized to a `static` field, however the instrument was assigned to an instance member.

In our case, this cause a big memory leak, which also resulted in CPU spike.

### Describe suggestions on how to achieve the rule

I propose an analyzer that identifies:
* A static field or property of type `System.Diagnostics.Metrics.Meter`
* Usages of this member to initialize a non-static field or property

The analyzer would say something to the effect of "Potential memory leak due to non-static instrument initialization".
We'd need to be very mindful of false positives, if developers were using their own singleton service, they could have a mix of static and non-static, while being a little odd, wouldn't suffer from a memory leak. 

### Additional context

Graph of our memory usage post release:
![image](https://github.com/dotnet/roslyn-analyzers/assets/1341446/2fb95e3a-bc3e-4c75-b160-3985936edd90)

**Comment by tommcdon** [comment]
@noahfalk @tarekgh

**Comment by noahfalk** [comment]
@slang25 - If you update to .NET 8 I expect this leak will be gone. Starting in .NET 8 the Meter caches counters by name so that if you call CreateCounter multiple times with the same name you will get back the same object rather than a new object each time. Does that sound like it would resolve the issue for you?

**Comment by slang25** [comment]
That does indeed resolve it 😄 Just tested here, and the new behaviour mitigates this exact issue. Thanks @noahfalk
