### ISSUE TITLE
[NETSDKE2E]CoreCLR symbols are missing while debugging IL Symbols in VS 17.8 preview 3.

### ISSUE THREAD

**Issue by vdanche** [dotnet/runtime#93256]
Affected Build: VS 17.8 preview 3 sign-off build:[Pipelines - Run rel.d17.8-34205.153 (visualstudio.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevdiv.visualstudio.com%2FDevDiv%2F_build%2Fresults%3FbuildId%3D8497505%26view%3Dresults&data=05%7C01%7Cv-danche%40microsoft.com%7C14716b8d51cb4c37188908dbc68e5a03%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638322087024543333%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=F67oYIh7BMadtBnkbuDc7yFFsoksRULhtl%2BX8c6S1fk%3D&reserved=0)

Steps to reproduce
Testing on Windows with VS -

1.Goto Tools -> options -> Debugging
Under General
a. Uncheck 'Enable Just My Code'
b. Check 'Suppress JIT optimization on module load (Managed only)'
Under Symbols
a. Check 'Microsoft Symbol Servers'

2.Create a new ASP.NET Razor project by doing
mkdir razor
cd razor
dotnet new razor

3.you can add this line of code on Program.cs file and Place a breakpoint on that line
Console.WriteLine("x " + 3);
![image](https://github.com/dotnet/sdk/assets/65637796/0c11fc5a-506c-4a14-99ee-490622f93106)

4.Run the application until it hit that breakpoint (F5) and Press F11

Expected Result:
It will step into ToString()  method directly.

Actual Result:
below dialog displays
![image](https://github.com/dotnet/sdk/assets/65637796/658ccba1-2aa1-484c-889f-dc0c0bfdb4a2)

Click "Open"
![image](https://github.com/dotnet/sdk/assets/65637796/4d4620ee-c667-40ef-aae4-2691f2803870)
Click "Cancel"
![image](https://github.com/dotnet/sdk/assets/65637796/85b92fd4-3a78-4d4b-85d8-2a9eccc4ac09)

Note:
Click "Browse" manually, it will step into ToString() method correctly.

dotnet --info:
.NET SDK:
 Version:   8.0.100-rc.2.23502.2
 Commit:    0abacfc2b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.25398
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-rc.2.23502.2\

.NET workloads installed:
 [maui-windows]
   Installation Source: VS 17.8.34205.153
   Manifest Version:    8.0.0-rc.2.9373/8.0.100-rc.2
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.maui\8.0.0-rc.2.9373\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: VS 17.8.34205.153
   Manifest Version:    16.4.8968-net8-rc2/8.0.100-rc.2
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.maccatalyst\16.4.8968-net8-rc2\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: VS 17.8.34205.153
   Manifest Version:    16.4.8968-net8-rc2/8.0.100-rc.2
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.ios\16.4.8968-net8-rc2\WorkloadManifest.json
   Install Type:              Msi

 [android]
   Installation Source: VS 17.8.34205.153
   Manifest Version:    34.0.0-rc.2.468/8.0.100-rc.2
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.android\34.0.0-rc.2.468\WorkloadManifest.json
   Install Type:              Msi

Host:
  Version:      8.0.0-rc.2.23479.6
  Architecture: x64
  Commit:       0b25e38ad3

.NET SDKs installed:
  8.0.100-rc.2.23502.2 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.2.23480.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.2.23479.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-rc.2.23479.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by richaverma1** [comment]
@vdanche does this repro on the released build of 17.8 Preview 3 ?

**Comment by vdanche** [comment]
@richaverma1 This issue not repro on VS 17.8 preview 3 build. so we can close it now
![image](https://github.com/dotnet/runtime/assets/65637796/86e9c9a9-732e-45e4-9def-5f8ea58e142f)
