### ISSUE TITLE
Jitted Methods Counting Test Fails When Hardware Intrinsics are Disabled

### ISSUE THREAD

**Issue by ivdiazsa** [dotnet/runtime#93261]
Tracking issue following up #93163.

The above-mentioned issue exposed a bug with the _Jitted Methods Counting Test_, regarding Hardware Intrinsics. When `DOTNET_EnableHWIntrinsic=0`, there is a much higher JIT activity, which in turn returns a much higher amount of jitted methods than the test was designed for. As per @jkotas' feedback, `DOTNET_EnableHWIntrinsic=0` has a similar effect to `DOTNET_ReadyToRun=0`, so this test ought not be run in those cases.

For general information and context, here's how to build and run the test locally.

```bash
# Build the runtime and libraries.

./build.sh --subset clr+libs --runtimeConfiguration Checked --librariesConfiguration Release

# Build the tests and core root.

src/tests/build.sh -x64 -checked -generatelayoutonly
src/tests/build.sh -x64 -checked -test:readytorun/JittedMethodsCountingTest/JittedMethodsCountingTest.csproj

# Setup and run the tests.

cd artifacts/tests/coreclr/linux.x64.Checked
export CORE_ROOT=$(pwd)/Tests/Core_Root
./readytorun/JittedMethodsCountingTest/JittedMethodsCountingTest.sh
```

**Comment by ivdiazsa** [comment]
@trylek FYI

**Comment by jkotas** [comment]
`DOTNET_EnableHWIntrinsic=0` is very similar to `DOTNET_ReadyToRun=0`. Both prevent some or all precompiled code from being used. I think that a solution that follows the current test design would be to check for `DOTNET_EnableHWIntrinsic=0` and skip the test when it is set.

There are other env. variables that have same effect. For example, I expect the test to fail on x64 if `DOTNET_SSE=0` is set. We may end up with checks for number of the env variables over time, based on what we hit in the outer loop test runs.

**Comment by ivdiazsa** [comment]
> `DOTNET_EnableHWIntrinsic=0` is very similar to `DOTNET_ReadyToRun=0`. Both prevent some or all precompiled code from being used. I think that a solution that follows the current test design would be to check for `DOTNET_EnableHWIntrinsic=0` and skip the test when it is set.
> 
> There are other env. variables that have same effect. For example, I expect the test to fail on x64 if `DOTNET_SSE=0` is set. We may end up with checks for number of the env variables over time, based on what we hit in the outer loop test runs.

Oh okok got it. Then let me change it so that it's disabled as well when `DOTNET_EnableHWIntrinsic=0`. Thanks for the observation Jan.
