### ISSUE TITLE
Invalid import in `bin/Release/net8.0/browser-wasm/AppBundle/main.mjs`

### ISSUE THREAD

**Issue by ncave** [dotnet/runtime#93274]
### Description

The default generated `dotnet.js` import path in `bin/Release/net8.0/browser-wasm/AppBundle/main.mjs` is incorrect when `WasmRuntimeAssetsLocation` is not defined, i.e. when:
```xml
<WasmRuntimeAssetsLocation Condition="'$(WasmRuntimeAssetsLocation)' == ''">_framework</WasmRuntimeAssetsLocation>
```

### Reproduction Steps

`dotnet publish -c Release /p:RunAOTCompilation=true /p:RuntimeIdentifier=browser-wasm`

### Expected behavior

`bin/Release/net8.0/browser-wasm/AppBundle/main.mjs`:

```js
import { dotnet } from './_framework/dotnet.js'
await dotnet.run();
```

### Actual behavior

`bin/Release/net8.0/browser-wasm/AppBundle/main.mjs`:

```js
import { dotnet } from './dotnet.js'
await dotnet.run();
```

### Known Workarounds

Build with:
```xml
    <!-- Put "framework" (dotnet.js, dlls, etc) files directly into the AppBundle -->
    <WasmRuntimeAssetsLocation>./</WasmRuntimeAssetsLocation>
```

### Configuration

.NET 8.0 RC1, WSL2, Ubuntu

**Comment by maraf** [comment]
How did you generate the project? Do you have updated `wasm-experimental` workload (and thus the wasm templates)? What versions does it print when you run `dotnet workload list`?

**Comment by maraf** [comment]
You have old template. Templates are distributed as part of `wasm-experimental` workload or the nuget can be installed separately. Running `dotnet workload install wasm-experimental` will fix the issue

**Comment by ncave** [comment]
I tried the most recent wasm workflows in .NET 8.0 RC2, but the same problem is still there in the template, for both of them:
```
Installed Workload Id      Manifest Version                     Installation Source
-----------------------------------------------------------------------------------
wasm-experimental          8.0.0-rc.2.23479.6/8.0.100-rc.2      SDK 8.0.100-rc.2   
```
and
```
Installed Workload Id      Manifest Version                     Installation Source
-----------------------------------------------------------------------------------
wasm-tools                 8.0.0-rc.2.23479.6/8.0.100-rc.2      SDK 8.0.100-rc.2   
```

**Comment by maraf** [comment]
It seems something didn't happened as it should on your machine. Can you please share a template engine cache file located at `"{USER HOME}\.templateengine\dotnetcli\8.0.100-rc.2.23502.2\templatecache.json"`?

**Comment by ncave** [comment]
@maraf 
Yes, you're absolutely right that the [Microsoft.NET.Runtime.WebAssembly.Templates/8.0.0-rc.2.23479.6](https://nuget.info/packages/Microsoft.NET.Runtime.WebAssembly.Templates/8.0.0-rc.2.23479.6) console template is correct.

I understand now that the change in the default framework path in the new template means that I need to update my local `main.mjs` in my project that was generated using an older template for .NET 7.0.
I'm sure this is documented somewhere as a migration step for updating existing projects..

Anyway, my mistake, closing this. Thank you very much for your help!
