### ISSUE TITLE
HttpClient - error An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by PetrMarekTytyot** [dotnet/runtime#93276]
I use HttpClient to reach API, this error is raised on post-calling
`
SocketException: An existing connection was forcibly closed by the remote host. 
` 

Configuration
Which version of .NET is the code running on? .NET core 6
What OS and version, and what distro if applicable? Windows 11 Enterprise version 22H2
What is the architecture (x64, x86, ARM, ARM64)? x64
Do you know whether it is specific to that configuration? no
If you're using Blazor, which web browser(s) do you see this issue in? no Blazor

`

            var client = new new HttpClient();
            client.BaseAddress = new Uri("https://webapi.developers.erstegroup.com/api/csas/sandbox/v1/sandbox-idp");
                  {
                        var postData = new Dictionary<string, string> 
                        {
                            { "code", "<some auth code>" },
                            { "client_id", "<some client id>" }, 
                            { "client_secret", "<some secret id>" },
                            { "redirect_uri", "<some redirect uri>" },
                            { "grant_type", "authorization_code" }
                        };

            var content = new FormUrlEncodedContent(postData);
            content.Headers.Clear();
            content.Headers.Add("Content-Type", "application/x-www-form-urlencoded");

            HttpResponseMessage response = await this.clientoAuth.PostAsync($"token", content);
`

**Comment by ManickaP** [comment]
The exception message: `SocketException: An existing connection was forcibly closed by the remote host. ` means that server closed the connection. However, there's not much info to give you better help. You can try to do packet capture and/or you can turn on internal HTTP logging. Also check your environment for things that might affect outgoing traffic, like proxies, antivirus etc. Have you tried to do the same thing via different language/tool? E.g. with curl or python.

BTW, I just tried to get the URI you shared and I had no problems with it.
