### ISSUE TITLE
[API Proposal]: `Task.FromResult`, but for enumerations

### ISSUE THREAD

**Issue by colejohnson66** [dotnet/runtime#93281]
### Background and motivation

`Task.FromResult` exists to avoid allocation. However, it only considers an _extremely_ limited range of supported values. Even in the `default(T)` case, it only considers integer value types. I propose it be extended to also consider `Enum` types, even if just for the `default(TEnum)` case.

### API Proposal

```csharp
namespace System.Threading.Tasks;

public class Task
{
    // extend this method
    public static Task<TResult> FromResult<TResult>(TResult result);
}
```

### API Usage

```csharp
public Task<MyEnum> GetResult() =>
    Task.FromResult(MyEnum.WhateverValueIsZero);
```

### Alternative Designs

The current solution is to have the user either: (1) construct/allocate a new `Task` each time, or (2) cache the task themselves.

**Comment by stephentoub** [comment]
> I propose it be extended to also consider Enum types, even if just for the default(TEnum) case.

That's already the case in .NET 8.  See the DayOfWeek example at https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-8/#tasks.

Thanks.
