### ISSUE TITLE
JIT\Stress\ABI\pinvokes_d tests timed out

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#93297]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=431083
Build error leg or test failing: JIT.Stress.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/93186

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```
      Stressing pinvokes
      OSVersion: Microsoft Windows NT 10.0.14393.0
      OSArchitecture: X64
      ProcessArchitecture: X86
      Selecting win86 ABI
      50 callers done
      100 callers done
      150 callers done
      200 callers done
      250 callers done
      300 callers done
      350 callers done
      400 callers done
      450 callers done
      500 callers done
      550 callers done
      600 callers done
      650 callers done
      700 callers done
      750 callers done
      800 callers done
      850 callers done
      900 callers done
      950 callers done
      1000 callers done
        Done with 0 mismatches
      
      cmdLine:C:\h\w\B8B90999\w\B2310A3A\e\JIT\Stress\ABI\pinvokes_d\pinvokes_d.cmd Timed Out
```

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "JIT.Stress.ABI.pinvokes_d.pinvokes_d.*timed.*out",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=431083
**Error message validated:** `JIT.Stress.ABI.pinvokes_d.pinvokes_d.*timed.*out`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 10/10/2023 4:44:06 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by jakobbotsch** [comment]
The test exits right after writing the "Done" message that is present in the logs:
https://github.com/dotnet/runtime/blob/715293eeeddf76593679fba7ab8cfd451980225b/src/tests/JIT/Stress/ABI/Program.cs#L137-L138

**Comment by JulieLeeMSFT** [comment]
@jakobbotsch, assigned this ABI issue to you.

**Comment by jakobbotsch** [comment]
Moved this to 9.0 and unmarked it as blocking since we haven't seen it failing since.

**Comment by JulieLeeMSFT** [comment]
The issue that the build-analysis bot removes milestone has been fixed. 
Resetting it to 9.0.

**Comment by jakobbotsch** [comment]
Haven't seen this since.
