### ISSUE TITLE
Memory Leaks in HttpHandler and the underneath infrastructure

### ISSUE THREAD

**Issue by okarpov** [dotnet/runtime#93294]
### Description

Memory Leaks in HttpHandler and the underneath infrastructure on long running.

### Configuration

.Net 7
Windows/Linux
x64

### Other information

Attached are two projects to easily reproduce the issue.

Steps to run and reproduce:

1. Go to the TestWebApp folder and run web server as following:
dotnet run --launch-profile https
This is required just to be able to send requests and get responses.

2. Start VisualStudio/Debugger with "Run As Administrator"
3. Open the TestHttpClientStringMemoryLeaks project and let it run for a while (more than 3 hours)
Process Memory grows indefinitely causing GC to be triggered more and more often.
The longer it runs the more Memory it consumes.

[TestHttpClientStringMemoryLeaks.zip](https://github.com/dotnet/core/files/12859123/TestHttpClientStringMemoryLeaks.zip)

**Comment by karelz** [comment]
This is likely something in the debugger process holding on something.
Might be good to find out what is being help by which component from memory dump analysis -- that may help us route it. @okarpov are you able to do it?

**Comment by okarpov** [comment]
> This is likely something in the debugger process holding on something. Might be good to find out what is being help by which component from memory dump analysis -- that may help us route it. @okarpov are you able to do it?

same behaviour without debugger. at some point it eats whole RAM on VPS and getting killed

**Comment by ManickaP** [comment]
`dotnet dump collect -p <pid>`

**Comment by okarpov** [comment]
> `dotnet dump collect -p <pid>`

so the testing app needs to be run out of any debugger, right?

**Comment by ManickaP** [comment]
Yep.

**Comment by karelz** [comment]
@okarpov

> so the testing app needs to be run out of any debugger, right?

Always make repro as minimal as possible and run them in simplest environment as possible. It is easier to debug (often time 10x or 100x easier) - less components involved.
Imagine that someone reported a bug to you ... would you want a complicated story involving dozens of steps, screenshots and settings which are likely not relevant at all and make even understanding of the problem harder?

**Comment by okarpov** [comment]
> @okarpov
> 
> > so the testing app needs to be run out of any debugger, right?
> 
> Always make repro as minimal as possible and run them in simplest environment as possible. It is easier to debug (often time 10x or 100x easier) - less components involved. Imagine that someone reported a bug to you ... would you want a complicated story involving dozens of steps, screenshots and settings which are likely not relevant at all and make even understanding of the problem harder?

sure, no problem. 
running via dotnet XXXX.dll

**Comment by okarpov** [comment]
seems there is no noticable leaks running out of VS
