### ISSUE TITLE
Assertion failed 'compiler->compIsaSupportedDebugOnly(HWIntrinsicInfo::lookupIsa(intrin.id))' in 'Runtime_92537:Mul

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#93299]
Happened on `runtime-coreclr jitstress-isas-arm` pipeline

```
01:33:06.392 Running test: JIT/Regression/JitBlue/Runtime_92537/Runtime_92537/Runtime_92537.dll

Assert failure(PID 23 [0x00000017], Thread: 23 [0x0017]): Assertion failed 'compiler->compIsaSupportedDebugOnly(HWIntrinsicInfo::lookupIsa(intrin.id))' in 'Runtime_92537:Mul(ushort,uint):long' during 'Generate code' (IL size 7; hash 0x0ac4d9ce; FullOpts)

    File: /__w/1/s/src/coreclr/jit/hwintrinsiccodegenarm64.cpp Line: 210
    Image: /root/helix/work/correlation/corerun
```

https://dev.azure.com/dnceng-public/public/_build/results?buildId=432598&view=ms.vss-test-web.build-test-results-tab&runId=9582022&resultId=120829&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by BruceForstall** [comment]
New test from #93003

**Comment by jakobbotsch** [comment]
@kunalspathak @c272 can one of you take a look? The test does not use any special intrinsics so this seems like a bug in the original transform in #91886.

**Comment by jakobbotsch** [comment]
I guess the problem is just that `TryLowerNegToMulLongOp` is missing the

```cpp
    if (!JitConfig.EnableHWIntrinsic())
        return nullptr;
```

that is already present in `TryLowerAddSubToMulLongOp`. I can submit the fix.

As a side note, it seems odd that we're tying transformations like this to whether or not HW intrinsics are enabled.
