### ISSUE TITLE
[Metrics] `error.type` doesn't report `Exception.FullName`

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#93302]
`http.client.request.duration`'s `error.type` contains `Exception.Name` for cases which do not map to `HttpRequestError` values, which is inconsistent with aspnet's implementation that reports `Exception.FullName` -- see https://github.com/dotnet/aspnetcore/pull/51084.

The [wording of the .NET Metrics spec](https://github.com/lmolkova/semantic-conventions/blob/dotnet8-metrics/docs/dotnet/dotnet-http-metrics.md#metric-httpclientrequestduration), is somewhat ambivalent:

> When error.type attribute is reported, it contains one of [HTTP Request errors](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/HttpRequestError.cs), a full exception type, or a string representation of received status code.

As https://github.com/dotnet/runtime/pull/93254#discussion_r1352865229 pointed out, this could also mean to *"use HttpRequestException instead of just 'Http' or 'HttpException'"*. Moreover, reporting the full name doesn't bring any value, the set of exceptions we can see here is limited, collisions are not expected. 

I assume this is not the case with aspnet, where exceptions may come from an arbitrarily large set. My recommendation would be to leave and document the current behaviors as-is.

@JamesNK @noahfalk we should make a decision ASAP.

**Comment by lmolkova** [comment]
No opinion here, just adding a few points:
- changing attribute value later would NOT be breaking from OTel perspective
- it might(?) be possible to get custom exceptions if users provide custom certificate check callback (maybe there are other cases?)

**Comment by noahfalk** [comment]
My preference would be to use FullName. I recognize it doesn't provide much value in terms of error disambiguation on this metric, but I do think it could provide value for consistency across metrics. If an engineer was writing queries to process metrics from different parts of .NET it would be a simpler mental model for them if the exception names reported in error.type are always FullName rather than some metrics use Name and others use FullName.

**Comment by JamesNK** [comment]
+1 for consistency.

**Comment by antonfirsov** [comment]
Ok. Gonna add this to #93254, and raise a separate PR for the HTTP part.

**Comment by MihaZupan** [comment]
Are we saying `FullName` is the right choice here? We could also change ASP.NET to use `Name` to get consistency instead :)

**Comment by antonfirsov** [comment]
@MihaZupan I considered proposing that option, but I assume ASP.NET logs `FullName` because they have to handle arbitrary exceptions and want to avoid ambiguity caused by name collisions.  If it's not the case (unlikely), we could have a discussion whether using `Name` is better accross the .NET stack, and change aspnet instead, but IMO we are too late in the release cycle to carry out this discussion in an async way and implement+bacport ASP.NET changes. To avoid risking the sync-up for GA, I prefer to proceed with the current plan.

@JamesNK can you elaborate on your choice of using `FullName` so we have higher confidence that we are doing the right thing?

**Comment by JamesNK** [comment]
> have to handle arbitrary exceptions and want to avoid ambiguity caused by name collisions

Yes. A `TaskException` could mean the built-in exception or a custom `TaskException` exception thrown from a calendar app that allows people to schedule tasks. Those exceptions would be intermingled.

`error.type` doesn't mention whether the exception type must be fully qualified. I'll poke the semantic conventions people to clarify the spec. I do see that `exception.type` [does explicitly say the type should be fully qualified](https://github.com/open-telemetry/semantic-conventions/blob/b127e121b9b458e83a0fee8a32f7eb6721912951/docs/exceptions/exceptions-logs.md?plain=1#L43).

**Comment by antonfirsov** [comment]
Fixed by #93414 on `release/8.0`, and by #93322 on `main`.
