### ISSUE TITLE
Custom Marshaller codefix uses `nint` by default for unmanaged type with no indication that it should be changed

### ISSUE THREAD

**Issue by jtschuster** [dotnet/runtime#93315]
The Custom Marshaller codefix will fill in `nint` as the default native type for structs and classes. Without any other indications, this can seem like the "right" type, and the user should implement the method to return an `nint`. I did this for `IntStruct` and cast `int` to `nint` for marshalling. This led to https://github.com/dotnet/runtime/issues/93155. We may want to add some indication that these methods should return the native representation of the managed type.

Related: https://github.com/dotnet/runtime/issues/89514

**Comment by jkoritzinsky** [comment]
Let's track this in #89514
