### ISSUE TITLE
Native AOT build fails on Ubuntu 22.04 and Clang 14.0.0-1ubuntu1.1 with error : cannot find -lstdc++: No such file or directory

### ISSUE THREAD

**Issue by sun1000** [dotnet/runtime#93317]
**dotnet sdk 7.0.109**: 

**Steps to Reproduce**:

1. create a simple console application
2. Add `<PublishAot>true</PublishAot>` to project file.
3. try to run dotnet `publish -r linux-x64 -c Release`

**Expected Behavior**:
it should build the native binary

**Actual Behavior**:
it fails with this error :
```
MSBuild version 17.4.8+6918b863a for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  ConsoleApp4 -> /home/neo/Projects/Personal/ConsoleApp4/ConsoleApp4/bin/Release/net7.0/linux-x64/ConsoleApp4.dll
  /usr/bin/ld: cannot find -lstdc++: No such file or directory
clang : error : linker command failed with exit code 1 (use -v to see invocation) [/home/neo/Projects/Personal/ConsoleApp4/ConsoleApp4/ConsoleApp4.csproj]
```

**clang version used** :
```
Ubuntu clang version 14.0.0-1ubuntu1.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

the point is there is no `libstdc++.so` in `/usr/bin/`

here is what it founds :
```
neo@Intel:/usr/lib$ find . | grep libstd
./x86_64-linux-gnu/libstdc++.so.6.0.30
./x86_64-linux-gnu/libstdc++.so.6
./gcc/x86_64-linux-gnu/11/libstdc++.so
./gcc/x86_64-linux-gnu/11/x32/libstdc++.so
./gcc/x86_64-linux-gnu/11/x32/libstdc++_pic.a
./gcc/x86_64-linux-gnu/11/x32/libstdc++fs.a
./gcc/x86_64-linux-gnu/11/x32/libstdc++.a
./gcc/x86_64-linux-gnu/11/libstdc++fs.a
./gcc/x86_64-linux-gnu/11/32/libstdc++.so
./gcc/x86_64-linux-gnu/11/32/libstdc++_pic.a
./gcc/x86_64-linux-gnu/11/32/libstdc++fs.a
./gcc/x86_64-linux-gnu/11/32/libstdc++.a
./gcc/x86_64-linux-gnu/11/libstdc++.a
```

so I had to do :
`neo@Intel:/usr/lib$ sudo cp ./gcc/x86_64-linux-gnu/11/libstdc++.so libstdc++.so`

to make the native binary building successful

**Comment by agocke** [comment]
@MichalStrehovsky Could you investigate? Our docs do not specify that libc++ is required for linking, so we might need to update our docs if it is.

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky Could you investigate? Our docs do not specify that libc++ is required for linking, so we might need to update our docs if it is.

We don't need it as of .NET 8. This looks specific to .NET 7.

@sun1000 can you upgrade to .NET 8? Otherwise libc++ needs to be installed, but I don't even know what package that would be in. Normally it's installed when you install clang; I never saw an issue like this.
