### ISSUE TITLE
[API Proposal]: System.Net.NetworkInformation.IPv4InterfaceProperties.Index should be uint

### ISSUE THREAD

**Issue by lianghaoGao** [dotnet/runtime#93316]
### Background and motivation

It wraps some ip helper function which return index as uint. Almost all win32 APIs assume index is unsigned.

When working with both managed c# and native c++ win32 apis, I need to cast from signed from c# in order to pass it to some c++ APIs. 

### API Proposal

```csharp
namespace System.Net.NetworkInformation.IPv4InterfaceProperties;

    public abstract class IPv4InterfaceProperties
    {
    	...
        
        /// Gets the interface index for the Internet Protocol (IP) address.
        public abstract uint Index{get;}

        ...
    }
```

### API Usage

```csharp
// Get the value
NetworkInterface[] interfaces = NetworkInterface.GetAllNetworkInterfaces()
foreach (NetworkInterface iface in interfaces)
{
uint index = iface.GetIPProperties().GetIPv4Properties().Index;
}

```

**Comment by antonfirsov** [comment]
This would be a binary breaking change that would break a very high amount of users when updating to the next .NET version. Such changes are [explicitly disallowed by our guidelines](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/breaking-change-rules.md#property-field-parameter-and-return-values).

The workaround on your side (casting) seems to be very straightforward.

**Comment by huoyaoyuan** [comment]
Binary breaking change that breaks type or method loading will never be considered, since it's a hard exception and can't be workarounded. This will break any code compiled with old version.

In .NET we generally prefer Int32 instead of the type closest to underlying data, for example the IP Port number is Int32 instead of UInt16.
