### ISSUE TITLE
Missing space for timezone in "en-US" culture LongTimePattern in MacOS Sonoma & .NET 7

### ISSUE THREAD

**Issue by philipmat** [dotnet/runtime#93310]
### Description

The `LongTimePattern` of the `en-US` culture seems to have changed on MacOS Sonoma with .NET 7.

It is now reporting as `h:mm:sstt` where it used to have a space before the AM/PM: `h:mm:ss tt`

### Reproduction Steps

Code:
```
Console.WriteLine($".NET Version={Environment.Version}");
Console.WriteLine($"OS={System.Runtime.InteropServices.RuntimeInformation.OSDescription}");
Console.WriteLine($"Long Time Pattern={new System.Globalization.CultureInfo("en-US").DateTimeFormat.LongTimePattern}");
```

### Expected behavior

On MacOS Ventura 13.6
```
❯ dotnet run
.NET Version=7.0.2
OS=Darwin 22.6.0 Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6000
Long Time Pattern=h:mm:ss tt
```

On Windows 10
```
❯ dotnet run
.NET Version=7.0.11
OS=Microsoft Windows 10.0.19045
Long Time Pattern=h:mm:ss tt
```

### Actual behavior

On MacOS Sonoma 14.0
```
❯ dotnet run
.NET Version=7.0.11
OS=Darwin 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:57 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8112
Long Time Pattern=h:mm:sstt
```

### Configuration

* Which version of .NET is the code running on? *.NET 7.0.11* and *.NET 6.0.22*
* What OS and version, and what distro if applicable? *macOS Sonoma 14.0*
* What is the architecture (x64, x86, ARM, ARM64)? *ARM64 (M2 processor)*
* Do you know whether it is specific to that configuration? *Same issue when running with .NET 6.0.22 on same machine*

**Comment by tarekgh** [comment]
This should be fixed in .NET 8.0 https://github.com/dotnet/runtime/issues/83571. Is it possible to use .NET 8.0 instead?

**Comment by philipmat** [comment]
Can confirm it's fixed with .NET 8.0.100-rc.2.23502.2 

```
❯ dotnet run
.NET Version=8.0.0
OS=Darwin 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:57 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8112
Long Time Pattern=h:mm:ss tt
```
