### ISSUE TITLE
Repo tag for v7.0.12 is for v7.0.11

### ISSUE THREAD

**Issue by Thefrank** [dotnet/runtime#93328]
https://github.com/dotnet/runtime/blob/ecb34f85ec92e1b3c814edf7da83337e199e7f66/eng/Versions.props#L6-L8

`git diff tags/v7.0.11 tags/v7.0.12 --stat`
(nothing)
`git diff tags/v7.0.10 tags/v7.0.11 --stat`
```
97 files changed, 2103 insertions(+), 944 deletions(-)
```

**Comment by hoyosjs** [comment]
@carlossanlop @rbhanda

**Comment by hoyosjs** [comment]
@dotnet/source-build-internal since I think this would be partner impacting.

**Comment by MichaelSimons** [comment]
> @dotnet/source-build-internal since I think this would be partner impacting.

Thanks for the heads up.  This should not affect source build as the graph is defined by the shas defined in version.details.xml starting at dotnet/installer.

**Comment by michaldobrodenka** [comment]
I've encountered this issue when I tried to build dotnet for armv6.

**Comment by michaldobrodenka** [comment]
Also tag for v8.0.rc.2 is missing

**Comment by rbhanda** [comment]
created the tags in runtime https://github.com/dotnet/runtime/releases/tag/v8.0.0-rc.2.23479.6 and https://github.com/dotnet/runtime/releases/tag/v7.0.12

**Comment by Thefrank** [comment]
Is this correct? 
https://github.com/dotnet/runtime/blob/4a824ef37caa51072221584c64cbf15455f406ca/eng/Versions.props#L182
I have only seen `-ci` items when doing my own builds outside of tags. I am not sure the build will be able to find this package

It is not listed here either: 
https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-public/NuGet/Microsoft.Native.Quic.MsQuic.Schannel/versions/

**Comment by michaldobrodenka** [comment]
I can't build it.

```
Build FAILED.

/root/2/runtime/src/libraries/System.Net.Quic/src/System.Net.Quic.csproj : error NU1603: System.Net.Quic depends on Microsoft.Native.Quic.MsQuic.Schannel (>= 2.2.3-ci.391104) but Microsoft.Native.Quic.MsQuic.Schannel 2.2.3-ci.391104 was not found. An approximate best match of Microsoft.Native.Quic.MsQuic.Schannel 2.2.3 was resolved. [/root/2/runtime/Build.proj]
    0 Warning(s)
    1 Error(s)
```

**Comment by Thefrank** [comment]
@rbhanda `Microsoft.Native.Quic.MsQuic.Schannel` `2.2.3-ci.391104` still seems to be missing from the default channels that the build uses any workaround?

**Comment by carlossanlop** [comment]
> Is this correct?
> 
> https://github.com/dotnet/runtime/blob/4a824ef37caa51072221584c64cbf15455f406ca/eng/Versions.props#L182
> 
> 
> I have only seen `-ci` items when doing my own builds outside of tags. I am not sure the build will be able to find this package
> It is not listed here either: https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-public/NuGet/Microsoft.Native.Quic.MsQuic.Schannel/versions/

Workaround: Please update that dependency to 2.2.3:

```cs
 <MicrosoftNativeQuicMsQuicVersion>2.2.3</MicrosoftNativeQuicMsQuicVersion> 
```

**Comment by Thefrank** [comment]
> 
> Workaround: Please update that dependency to 2.2.3:
> 
> ```cs
>  <MicrosoftNativeQuicMsQuicVersion>2.2.3</MicrosoftNativeQuicMsQuicVersion> 
> ```

This allows the build to complete
Closing this as done, thank you all!
