### ISSUE TITLE
.NET 8.0 RC1 and RC2 lag spikes

### ISSUE THREAD

**Issue by Nuklon** [dotnet/runtime#93341]
### Description

I've tried RC1 a month ago with two of my web apps and ran into lag spikes, so I moved back to .NET 7.0. Now with RC2 being out, I tried it again and it has the same problem. After ~2 hours of running, the .NET 8.0 sites start to produce spikes in response times.

![image](https://github.com/dotnet/runtime/assets/23340481/8d38f2f0-203f-4241-9f83-91771f393faf)

Here's the .NET 7.0 graph (which can run nicely for a month without any spikes):
![image](https://github.com/dotnet/runtime/assets/23340481/b1924294-41be-4d1e-86fc-0bc4da1b44eb)

It's happening to two sites I've tried; they're both hosted through IIS. The machine doesn't run out of memory as it has plenty.
On one site it happens a bit faster, probably because there's more traffic through it.

### Configuration

.NET: 8.0 RC2
OS: Windows Server 2022 (latest update at time of writing).
Architecture: x64

### Regression?

Yes, works in .NET 7.0.

**Comment by KeterSCP** [comment]
On your top plot you have scale from 0 to 700, and on the bottom one from 5 to 8.
Maybe your .NET7 app also has the same spikes but you can't see them due to plot scaling?

**Comment by Nuklon** [comment]
> On your top plot you have scale from 0 to 700, and on the bottom one from 5 to 8. Maybe your .NET7 app also has the same spikes but you can't see them due to plot scaling?

They scale automatically. Even when you put the period at 1 week there are no spikes with .NET 7.0. With .NET 8.0 always spikes after a couple of hours. I also tried with Ready2Run but it has the same issue.

**Comment by recumbented** [comment]
If you're facing with same issue with me and if your app run in InProcess hosting model, try switching to OutOfProcess hosting model may resolve the issue.
.NET 8 with IIS InProcess hosting model seems to may cause Thread Leak on HTTP request canceled.

**Comment by Nuklon** [comment]
> If you're facing with same issue with me and if your app run in InProcess hosting model, try switching to OutOfProcess hosting model may resolve the issue. .NET 8 with IIS InProcess hosting model seems to may cause Thread Leak on HTTP request canceled.

If you refer to: https://github.com/dotnet/aspnetcore/issues/51121
Mine keeps running, there's no OutOfMemoryException. I might give out of process a try though.
