### ISSUE TITLE
Incorrect value in FirstDayOfWeek test

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#93354]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=432866
Build error leg or test failing: System.Globalization.Tests.DateTimeFormatInfoFirstDayOfWeek.FirstDayOfWeek
Pull request: https://github.com/dotnet/runtime/pull/93224

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Expected: Monday",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

```
info: Expected: Monday
info: Actual:   Sunday
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=432866
**Error message validated:** `Expected: Monday`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 10/11/2023 5:08:28 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[441921](https://dev.azure.com/dnceng-public/public/_build/results?buildId=441921)|dotnet/runtime|[normal-System.Globalization.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=441921&view=ms.vss-test-web.build-test-results-tab&runId=9851498&resultId=182357)|dotnet/runtime#93368|
|[440108](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440108)|dotnet/runtime|[normal-System.Globalization.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440108&view=ms.vss-test-web.build-test-results-tab&runId=9805516&resultId=172615)|dotnet/runtime#93409|
|[440065](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440065)|dotnet/runtime|[normal-System.Globalization.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440065&view=ms.vss-test-web.build-test-results-tab&runId=9799716&resultId=172615)|dotnet/runtime#93565|
|[439944](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439944)|dotnet/runtime|[normal-System.Globalization.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439944&view=ms.vss-test-web.build-test-results-tab&runId=9799302&resultId=182352)|dotnet/runtime#93223|
|[440049](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440049)|dotnet/runtime|[normal-System.Globalization.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440049&view=ms.vss-test-web.build-test-results-tab&runId=9798918&resultId=172615)|dotnet/runtime#93564|
|[440042](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440042)|dotnet/runtime|[normal-System.Globalization.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440042&view=ms.vss-test-web.build-test-results-tab&runId=9798656&resultId=172615)|dotnet/runtime#93563|
|[439988](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439988)|dotnet/runtime|[normal-System.Globalization.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439988&view=ms.vss-test-web.build-test-results-tab&runId=9796914&resultId=172615)|dotnet/runtime#93558|
|[439923](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439923)|dotnet/runtime|[normal-System.Globalization.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439923&view=ms.vss-test-web.build-test-results-tab&runId=9795140&resultId=172615)|dotnet/runtime#93553|
|[439839](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439839)|dotnet/runtime|[normal-System.Globalization.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439839&view=ms.vss-test-web.build-test-results-tab&runId=9795074&resultId=172615)|dotnet/runtime#93178|
|[439911](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439911)|dotnet/runtime|[normal-System.Globalization.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439911&view=ms.vss-test-web.build-test-results-tab&runId=9794922&resultId=172615)|dotnet/runtime#93556|
|[439914](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439914)|dotnet/runtime|[WasmTestOnNodeJS-System.Globalization.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439914&view=ms.vss-test-web.build-test-results-tab&runId=9794736&resultId=187540)|dotnet/runtime#93556|
|[439871](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439871)|dotnet/runtime|[normal-System.Globalization.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439871&view=ms.vss-test-web.build-test-results-tab&runId=9793794&resultId=172615)|dotnet/runtime#90436|
|[439461](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439461)|dotnet/runtime|[normal-System.Globalization.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439461&view=ms.vss-test-web.build-test-results-tab&runId=9793680&resultId=182352)|dotnet/runtime#93545|
|[439861](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439861)|dotnet/runtime|[normal-System.Globalization.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439861&view=ms.vss-test-web.build-test-results-tab&runId=9793556&resultId=172615)|dotnet/runtime#92550|
|[439825](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439825)|dotnet/runtime|[WasmTestOnBrowser-System.Globalization.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439825&view=ms.vss-test-web.build-test-results-tab&runId=9792648&resultId=118679)|dotnet/runtime#93548|
|[439488](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439488)|dotnet/runtime|[normal-System.Globalization.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439488&view=ms.vss-test-web.build-test-results-tab&runId=9792498&resultId=182352)|dotnet/runtime#93547|
|[439718](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439718)|dotnet/runtime|[normal-System.Globalization.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439718&view=ms.vss-test-web.build-test-results-tab&runId=9790496&resultId=172615)|dotnet/runtime#90771|
|[439417](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439417)|dotnet/runtime|[normal-System.Globalization.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439417&view=ms.vss-test-web.build-test-results-tab&runId=9788908&resultId=172615)|dotnet/runtime#93542|
|[439521](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439521)|dotnet/runtime|[normal-System.Globalization.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439521&view=ms.vss-test-web.build-test-results-tab&runId=9788066&resultId=172615)|dotnet/runtime#93280|
|[439482](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439482)|dotnet/runtime|[WasmTestOnBrowser-System.Globalization.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439482&view=ms.vss-test-web.build-test-results-tab&runId=9784736&resultId=115030)|dotnet/runtime#93223|
|[439467](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439467)|dotnet/runtime|[normal-System.Globalization.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439467&view=ms.vss-test-web.build-test-results-tab&runId=9784638&resultId=172615)|dotnet/runtime#93546|
|[439458](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439458)|dotnet/runtime|[normal-System.Globalization.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439458&view=ms.vss-test-web.build-test-results-tab&runId=9784338&resultId=172615)|dotnet/runtime#93472|
|[437781](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437781)|dotnet/runtime|[normal-System.Globalization.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437781&view=ms.vss-test-web.build-test-results-tab&runId=9734280&resultId=172614)|dotnet/runtime#93380|
|[437294](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437294)|dotnet/runtime|[normal-System.Globalization.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437294&view=ms.vss-test-web.build-test-results-tab&runId=9721078&resultId=182349)|dotnet/runtime#93440|
|[435814](https://dev.azure.com/dnceng-public/public/_build/results?buildId=435814)|dotnet/runtime|[normal-System.Globalization.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=435814&view=ms.vss-test-web.build-test-results-tab&runId=9689468&resultId=172614)|dotnet/runtime#93380|
|[435815](https://dev.azure.com/dnceng-public/public/_build/results?buildId=435815)|dotnet/runtime|[normal-System.Globalization.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=435815&view=ms.vss-test-web.build-test-results-tab&runId=9684544&resultId=172614)|dotnet/runtime#93380|
|[435488](https://dev.azure.com/dnceng-public/public/_build/results?buildId=435488)|dotnet/runtime|[normal-System.Globalization.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=435488&view=ms.vss-test-web.build-test-results-tab&runId=9676236&resultId=182349)|dotnet/runtime#93182|
|[432866](https://dev.azure.com/dnceng-public/public/_build/results?buildId=432866)|dotnet/runtime|[WasmTestOnBrowser-System.Globalization.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=432866&view=ms.vss-test-web.build-test-results-tab&runId=9589148&resultId=187826)|dotnet/runtime#93224|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|27|28|

**Comment by SmartmanApps** [comment]
![image](https://github.com/dotnet/runtime/assets/20635275/b33056c6-0054-4b35-a666-cb1d57cc5ebd)

**Comment by ilonatommy** [comment]
@SmartmanApps thank you for trying to help. However, it is not that simple. This failure is in test that checks all locales available on WASM (~200) and makes sure native JS code returns the correct day of the week for them. I wish all locales had the same response to `new CultureInfo(locale_code_string).DateTimeFormat.FirstDayOfWeek` but they do not. If you re interested, you can see https://github.com/dotnet/runtime/blob/8c21eadb558028181919be879bf125603546ff68/src/libraries/System.Globalization/tests/DateTimeFormatInfo/DateTimeFormatInfoFirstDayOfWeek.cs#L20 to have a better understanding what values we expect from each locales. I can't reproduce the error to detect which locale is the offender, so I created a PR that will surface this information in the error message.

**Comment by lewing** [comment]
Is this happening consistently or just occationally?

**Comment by radical** [comment]
> Is this happening consistently or just occasionally?

Oddly, I don't see any failures in rolling builds in the last 2 weeks!

**Comment by radical** [comment]
And the tests ran on the last PR that bumped the chrome version, where they didn't fail either.

**Comment by ilonatommy** [comment]
> Is this happening consistently or just occasionally?

Occasionally but quite often. It never fails for me when I try to reproduce. Pavel has an idea that it might depend on location of data center where CI tests are run, so next step would be to try to repro changing TZ on the machine to see if I find the one that fails.
