### ISSUE TITLE
[8.0] Test failure: System.ComponentModel.Tests.DefaultValueAttributeTests.Ctor_TypeDescriptorNotFound_ExceptionFallback - Exit code was -1073740791 but it should have been 42

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#93372]
### Error Blob

```json
{
  "ErrorMessage": "System.ComponentModel.Tests.DefaultValueAttributeTests.Ctor_TypeDescriptorNotFound_ExceptionFallback",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": true
}
```

### Reproduction Steps

- 8.0 PR: https://github.com/dotnet/runtime/pull/93096
- Queue: `Libraries Test Run checked coreclr windows x64 Release`
- Affected test: `System.ComponentModel.Tests.DefaultValueAttributeTests.Ctor_TypeDescriptorNotFound_ExceptionFallback`
- Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=429573&view=logs&j=51e4640a-c078-5be6-cc1b-f971e75d762f&t=a795459e-9f5a-52e6-9047-d38ac6fe5fb4&l=56
- Log file: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-pull-93096-merge-8522e5f33dfb4ef9b3/System.Runtime.Tests/1/console.b66a85c5.log?helixlogtype=result
- Callstack:
```
    System.ComponentModel.Tests.DefaultValueAttributeTests.Ctor_TypeDescriptorNotFound_ExceptionFallback(type: typeof(int), returnNull: False, stringToConvert: "42", expectedValue: 42) [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Exit code was -1073740791 but it should have been 42
      Stack Trace:
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(242,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing)
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(55,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose()
        /_/src/libraries/System.Runtime/tests/System/ComponentModel/DefaultValueAttributeTests.cs(79,0): at System.ComponentModel.Tests.DefaultValueAttributeTests.Ctor_TypeDescriptorNotFound_ExceptionFallback(Type type, Boolean returnNull, String stringToConvert, Int32 expectedValue)
           at InvokeStub_DefaultValueAttributeTests.Ctor_TypeDescriptorNotFound_ExceptionFallback(Object, Span`1)
           at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=429573
**Error message validated:** `System.ComponentModel.Tests.DefaultValueAttributeTests.Ctor_TypeDescriptorNotFound_ExceptionFallback`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 10/16/2023 6:55:11 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by ericstj** [comment]
Looks to me like this issue was originally filed to capture `System.ComponentModel.Tests.DefaultValueAttributeTests.Ctor_TypeDescriptorNotFound_ExceptionFallback` however the match string `but it should have been 42` is causing it to match to any RemoteExecutor failure.
https://github.com/dotnet/arcade/blob/57f6c7f2e8a121049af4da85db2a2985f666935e/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs#L26C26-L26C42
https://github.com/dotnet/arcade/blob/57f6c7f2e8a121049af4da85db2a2985f666935e/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeOptions.cs#L35
https://github.com/dotnet/arcade/blob/57f6c7f2e8a121049af4da85db2a2985f666935e/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs#L242

Please be careful when crafting matches to not over-match.

**Comment by ericstj** [comment]
All of the failures matched in this issue are not due to the original problem.  I updated the match string and opened a new issue to capture the majority of the failures this was previously matching.

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not been hit in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by steveharter** [comment]
Closing; please re-open if there are hits. Likely a remote executor fluke.
