### ISSUE TITLE
.net6 custom string and long converters do not take effect

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#93385]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/net6-custom-string-and-long-converters-/10478685)._

---
[severity:Other]
In the process of using .net6, you need to perform JsonConverter custom converters for long and string fields, but during use, it is found that the string and long custom converters do not take effect, and will not go to read and write. Does net6 have restrictions on built-in types? Built-in types have default serialization, so can't customize converters?

---
#### Feedback Bot on 9/28/2023, 03:20 AM: 

(private comment, text removed)
#### 锐 羊 on 10/9/2023, 10:14 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by eiriktsarpalis** [comment]
That shouldn't be the case, could you share a minimal reproduction please?

**Comment by gregsdennis** [comment]
@eiriktsarpalis I can't help but notice that the person who opened the issue hasn't been tagged (if they even have a GH account).  It _is_ linked in the discussion, I guess...

**Comment by eiriktsarpalis** [comment]
It is unfortunate, but as you're pointing out we can't link vs feedback accounts to gh accounts. Once the decision has been made to move the issue for triage on github, we can only hope that the user follows up and responds to new feedback here.
