### ISSUE TITLE
[API Proposal]: LINQ GroupBy to expose IReadOnlyList instead of IEnumerable

### ISSUE THREAD

**Issue by KaliCZ** [dotnet/runtime#93386]
### Background and motivation

It's generally frowned upon to enumerate an IEnumerable multiple times. There's even a check for it - `CA1851`.

However, GroupBy methods in LINQ are exposing `IEnumerable` interface even though they are in fact enumerated, they know the amount of items. They could expose `IReadOnlyList` interface instead, so that the usages wouldn't violate the `CA1851` rule. 

It is however a breaking change, because the parameter is of type `Func<TKey, IEnumerable<TElement>, TResult>`. So most usages will continue working and just change the type of the lambda parameter. But if somebody has the Func stored in a property or passing through another function, then the compiler would complain about type mismatch and it would probably also result in runtime exceptions.

### API Proposal

```csharp
namespace System.Linq;

public static partial class Enumerable
{
    // Other Overloads

    public static IEnumerable<TResult> GroupBy<TSource, TKey, TResult>(this IEnumerable<TSource> source, Func<TSource, TKey> keySelector, Func<TKey, IReadOnlyList<TSource>, TResult> resultSelector) =>
        new GroupedResultEnumerable<TSource, TKey, TResult>(source, keySelector, resultSelector, null);

    public static IEnumerable<TResult> GroupBy<TSource, TKey, TElement, TResult>(this IEnumerable<TSource> source, Func<TSource, TKey> keySelector, Func<TSource, TElement> elementSelector, Func<TKey, IReadOnlyList<TElement>, TResult> resultSelector) =>
        new GroupedResultEnumerable<TSource, TKey, TElement, TResult>(source, keySelector, elementSelector, resultSelector, null);

    public static IEnumerable<TResult> GroupBy<TSource, TKey, TResult>(this IEnumerable<TSource> source, Func<TSource, TKey> keySelector, Func<TKey, IReadOnlyList<TSource>, TResult> resultSelector, IEqualityComparer<TKey>? comparer) =>
        new GroupedResultEnumerable<TSource, TKey, TResult>(source, keySelector, resultSelector, comparer);

    public static IEnumerable<TResult> GroupBy<TSource, TKey, TElement, TResult>(this IEnumerable<TSource> source, Func<TSource, TKey> keySelector, Func<TSource, TElement> elementSelector, Func<TKey, IReadOnlyList<TElement>, TResult> resultSelector, IEqualityComparer<TKey>? comparer) =>
        new GroupedResultEnumerable<TSource, TKey, TElement, TResult>(source, keySelector, elementSelector, resultSelector, comparer);
}

public interface IGrouping<out TKey, out TElement> : IReadOnlyList<TElement>
{
    TKey Key { get; }
}
```

See example implementation here: https://github.com/dotnet/runtime/compare/main...KaliCZ:dotnet-runtime:group-by-enumerated?expand=1

### API Usage

In this usage, You can have some conditions evaluated in the GroupBy lambda without the compiler telling you that you're enumerating the grouping result multiple times. I can't really produce a useful business logic example here, because our business logic is quite complicated. But generally speaking, it makes sense to have logic executed for each group and store the result.
```csharp
IEnumerable<string> strings = Enumerable.Empty<string>();
var something = strings.GroupBy(s => s.Length, (length, textsWithSameLength) =>
{
    var allTextsContainAWhiteSpace = textsWithSameLength.All(text => text.Any(c => c.IsWhiteSpaceCharacter()));
    return allTextsContainAWhiteSpace
        ? textsWithSameLength.Sum(text => text.Length)
        : 0;
});
```

### Risks

As stated in the background, it is a breaking change. Albeit one that will not break the vast majority of calls.

Creating another overload would mean that compiler wouldn't know which one to choose...

Is there a way to put this on a list of some .net release where we would be willing to make such breaking changes?

**Comment by huoyaoyuan** [comment]
> It is however a breaking change, because the parameter is of type `Func<TKey, IEnumerable<TElement>, TResult>`. So most usages will continue working and just change the type of the lambda parameter.

This is binary breaking. It will break any usage compiled with old framework. This is definitely unacceptable.

**Comment by eiriktsarpalis** [comment]
It would be a binary breaking change, so it wouldn't be possible to entertain such a change. See https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/breaking-change-rules.md#signatures for more details.

**Comment by eiriktsarpalis** [comment]
Note, there's also this related proposal we're currently considering: https://github.com/dotnet/runtime/issues/92165
