### ISSUE TITLE
[API Proposal]: Make OpCode.StackChange() public

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#93419]
### Background and motivation

[OpCodes](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Reflection/Emit/OpCodes.cs#L258) represents MS IL instructions that used for emitting IL with [ILGenerator](https://learn.microsoft.com/dotnet/api/system.reflection.emit.ilgenerator). An `OpCode` instruction may pop value(s) from stack as an operand of the instruction and also may push value(s) into the stack as a result.  This stack change is needed for calculating [MaxStack](https://learn.microsoft.com/dotnet/api/system.reflection.methodbody.maxstacksize) value that is essential for populating method body. I could use the   `StackBehaviourPop` and `StackBehaviourPush` properties of `OpCode` to calculate this, but there is an internal method that gives this info directly:
https://github.com/dotnet/runtime/blob/946c5245aea149d9ece53fd0debc18328c29083b/src/libraries/System.Private.CoreLib/src/System/Reflection/Emit/Opcode.cs#L48-L49
Making this public will be useful for calculating `MaxStack` faster
Related to https://github.com/dotnet/runtime/pull/93244/files#r1353013060

### API Proposal

```diff
namespace System.Reflection.Emit

public readonly partial struct OpCode : System.IEquatable<System.Reflection.Emit.OpCode>
{
    ...
    public StackBehaviour StackBehaviourPop { get }
    public StackBehaviour StackBehaviourPush { get }
    ...
+   public int EvaluationStackDelta { get }
}
```
### Alternative Designs

Other naming options: `EvaluationStackDelta`, `StackSizeDelta`, `StackTransitionDelta` or `StackDepthDelta` as it is showing the difference of evaluation stack transition.

### API Usage

```csharp
    private void UpdateStackSize(OpCode opCode)
    {
        _currentStack += opCode.EvaluationStackDelta;
        _maxStackSize = Math.Max(_maxStackSize, _currentStack);
    }
```

**Comment by alexrp** [comment]
Seems like this should be a property?

**Comment by buyaa-n** [comment]
> Seems like this should be a property?

Yes, can be a property and that is mentioned in the `Alternative Designs` part

**Comment by terrajobst** [comment]
How expensive is the computation?

I assume it's just a switch over the op code as the values are static? In that case I'd be in favor of a property.

I also assume a positive value means the op code net-ads to the evaluation stack (pushing), a negative value means net consumption (popping), and zero means no change or equal amounts of pushing and popping.

If so, I think I'd prefer `EvaluationStackDelta`.

@dotnet/fxdc?

**Comment by buyaa-n** [comment]
> How expensive is the computation?

The OpCode has this info in the upper 4 bits of `m_flags` field:
https://github.com/dotnet/runtime/blob/d18295e107a297dfe4e12ef5b34c28a63548ab31/src/libraries/System.Private.CoreLib/src/System/Reflection/Emit/Opcode.cs#L34
So the computation is just shifting those bits:
https://github.com/dotnet/runtime/blob/d18295e107a297dfe4e12ef5b34c28a63548ab31/src/libraries/System.Private.CoreLib/src/System/Reflection/Emit/Opcode.cs#L48-L49


> I also assume a positive value means the op code net-ads to the evaluation stack (pushing), a negative value means net consumption (popping), and zero means no change or equal amounts of pushing and popping.

Yep, that is right

**Comment by terrajobst** [comment]
Oh wow. I didn't realize the op code value encoded the stack change. In preview metadata readers I've always seen people doing switches *facepalm*

Also, I didn't realize we already have properties called `StackBehaviuor(Push|Pop)`. In that I rescind my proposal to include the term `Evalutation`. I think I still prefer the word `Delta` over difference.

Anyone else on @dotnet/fxdc?

```C#
namespace System.Reflection.Emit

public readonly partial struct OpCode : System.IEquatable<System.Reflection.Emit.OpCode>
{
    // Existing:
    // public StackBehaviour StackBehaviourPop { get; }
    // public StackBehaviour StackBehaviourPush { get; }

    public int StackDelta { get; }
}
```

**Comment by buyaa-n** [comment]
Another option could be `StackTransitionDelta`, as it is showing the difference of evaluation stack transition/movement, also could be `StackDepthDelta`.

**Comment by terrajobst** [comment]
Either of those names work for me :-)

**Comment by bartonjs** [comment]
Looks good as proposed.

```C#
namespace System.Reflection.Emit

public readonly partial struct OpCode : System.IEquatable<System.Reflection.Emit.OpCode>
{
    public int EvaluationStackDelta { get }
}
```
