### ISSUE TITLE
Cascading JsonSourceGenerator Not Working

### ISSUE THREAD

**Issue by jeff-simeon** [dotnet/runtime#93439]
### Description

We have an incremental source generator that generates C# classes that are used extensively for JSON serialization. We would like to also emit JsonSerializerContexts for all of these classes. Doing so does not recursively trigger the JsonSourceGenerator incremental generator. 

### Reproduction Steps

Create an incremental generator that emits a POCO and a corresponding JsonSerializerContext with the JsonSerializable attribute applied. The JsonSourceGenerator does not contribute to the JsonSerializerContext partial class. 

### Expected behavior

I should be able to emit a JsonSerializerContext for my generated classes. 

### Actual behavior

The JsonSourceGenerator does not contribute to the JsonSerializerContext. 

### Known Workarounds

I realize this isn’t a supported scenario for incremental generators altogether (except to have a PostInitialization emitted source trigger generation via an incremental value provider). But the JsonSourceGenerator should provide some way for me to emit the required code for my classes. Even if it’s just making a public Execute method that takes a named type symbol. The only way I’ve been able to get this to work is by referencing the analyzer DLL directly from the System.Text.Json nuget package and manually invoking the ReportDiagnosticsAndEmitSource method using private reflection.

**Comment by eiriktsarpalis** [comment]
This is currently a restriction of source generators in general. SGs in a given project are run in a non-deterministic order, as such it is not currently possible for the output of one SG to be passed as input in another.

I'll forward this to the @dotnet/roslyn folks for a more authoritative response on the matter.

**Comment by jeff-simeon** [comment]
@eiriktsarpalis understood - so wouldn’t a good compromise be to make a public method available so I can chain your generator directly from mine?

**Comment by eiriktsarpalis** [comment]
It's an interesting thought, but I don't think that the current manifestation of the source generator is particularly amenable to composition. If you're feeling really adventurous, you could try referencing the source generator dll directly (the [source generator class](https://github.com/dotnet/runtime/blob/3fd4432df6c80b04739aebd9deedb09cb9b360d2/src/libraries/System.Text.Json/gen/JsonSourceGenerator.Roslyn4.0.cs) is public) and see if that works. Be warned that these APIs are not supported for direct consumption and are subject to change in the future.

Perhaps as a better interim solution, you could try breaking up your components into separate projects: one project running the STJ source generator and another project running yours on top of the generated code.

**Comment by jeff-simeon** [comment]
@eiriktsarpalis  - yes as I mentioned in the original post, I was able to get it working by doing this:
`
The only way I’ve been able to get this to work is by referencing the analyzer DLL directly from the System.Text.Json nuget package and manually invoking the ReportDiagnosticsAndEmitSource method using private reflection.
`
I hate to take a dependency on a private method though.

How are you imagining I would solve this by working in separate projects? The other project would still need a generator to somehow create the triggering JsonSerializerContext partial classes, which would incur the same problem, no?

**Comment by eiriktsarpalis** [comment]
> How are you imagining I would solve this by working in separate projects? The other project would still need a generator to somehow create the triggering JsonSerializerContext partial classes, which would incur the same problem, no?

Ah, so your source generator would just be there to emit `JsonSerializerContext` partial classes for the specific purpose of triggering the STJ generator? Yeah, I don't think that's possible or something we'd be looking to support in the future.

Depending on what you are trying to achieve though, I think that [this proposal](https://github.com/dotnet/runtime/issues/91495) might be a better alternative. Effectively it would be using interceptors to make defining `JsonSerializerContext` types optional.

**Comment by jeff-simeon** [comment]
today the source generator emits thousands of POCO classes used for source generation - the goal is just to make the serialization of these generated classes as fast as possible (preferably by getting JSON source generation enabled for them)
