### ISSUE TITLE
[NativeAOT] set StaticICULinking results in a CmakeLists.txt that violates policy CMP0000 of Cmake (affects CMake version >= 3.9.0)

### ISSUE THREAD

**Issue by Neo-vortex** [dotnet/runtime#93436]
### Intro:
when compiling with `NativeAOT` and `StaticICULinking` flags, the resulting `CmakeLists.txt` does not respect [policy CMP0000 of Cmake ](https://cmake.org/cmake/help/latest/policy/CMP0000.html) and produces a warning : 
```
 CMake Warning (dev) in CMakeLists.txt:
    No cmake_minimum_required command is present.  A line of code such as
  
      cmake_minimum_required(VERSION 3.22)
  
    should be added at the top of the file. 
```

### steps to produce
1- create a new dotnet console project
2- add ` <StaticICULinking>true</StaticICULinking>
        <PublishAot>true</PublishAot>` to `.csproj` file 
3- add `Microsoft.Dotnet.ILCompiler 8.0.0-rc.2.23479.6` nuget
4- run ` dotnet publish -r linux-x64 -c Release  --self-contained`

### Expected Behavior 
no warning should be emitted by Cmake 

### Actual Behavior 
Cmake emits warning about policy CMP0000

### Other Areas Effected ?
perhaps
`System.IO.Compression.Native`,
`System.Security.Cryptography.Native`,
`System.Security.Cryptography.Native.Android`,
`System.Security.Cryptography.Native.Apple`
...

### Solution
myabe setting the min version of cmake to the version that reflects
`https://github.com/dotnet/runtime/blob/main/src/coreclr/CMakeLists.txt` 
or
`https://github.com/dotnet/runtime/blob/main/src/native/libs/CMakeLists.txt`

### Tested System
1- `dotnet 8.0.100-rc.2.23502.2`
2- `cmake version 3.22.1` , This affects CMake version >= 3.9.0 
3- `Linux neo-Intel 6.2.0-34-generic #34~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 13:12:03 UTC 2 x86_64 
     x86_64 x86_64 GNU/Linux`
4- `Microsoft.Dotnet.ILCompiler 8.0.0-rc.2.23479.6` nuget

**Comment by jkoritzinsky** [comment]
I would expect this to be an issue with the infrastructure behind the StaticICU option, not with any of the libraries you've mentioned. @lewing do you know who owns the Static ICU experience?

**Comment by jkotas** [comment]
`StaticICULinking` is native AOT option. It is owned by native AOT team. (It was contributed by AWS.)

**Comment by Neo-vortex** [comment]
> I would expect this to be an issue with the infrastructure behind the StaticICU option, not with any of the libraries you've mentioned. @lewing do you know who owns the Static ICU experience?

Those libraries I mentioned can also be compiled statically with Native AOT and having the same structure as static ICU.
Did you cleck the PR? It will make sense hopefully.

**Comment by jkoritzinsky** [comment]
The libraries you’ve updated are compiled during the runtime build. As far as I can tell, they are linked in as static libraries in the NativeAOT targets. CMake is not involved at this point. Same thing with StaticIcuLinking. Can you share the CMake command line that’s being run?

**Comment by Neo-vortex** [comment]
@jkoritzinsky 
here is the result with :
`dotnet publish -r linux-x64 -c Release  --self-contained -v n`

[logs.txt](https://github.com/dotnet/runtime/files/12891144/logs.txt)

**Comment by jkotas** [comment]
@jkoritzinsky We include the System.Native.Globalization sources in the NAOT nuget package and compile them on the user machine against the exact ICU static library version present on the user machine. It is like a mini source build.

Docs for how to use this are at 
https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/compiling.md#using-statically-linked-icu
