### ISSUE TITLE
Add display name filtering in merged tests

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#93452]
The merged test wrapper currently only supports filtering by fully qualified name, which is very frustrating for two reasons:
1. Running a merged test wrapper does not print the fully qualified name of the tests it is running anywhere, so you have to know what string it is expecting and go look it up for your test
2. Multiple tests can have the same fully qualified name, making it impossible to actually filter down to what you want (e.g. tests with the fully qualified name `OVFTest.TestEntryPoint` are present 9 times in `jit64_5` which is what actually sparked this issue)

Can we just match the input string on both the fully qualified name and the display name?

cc @jkoritzinsky @markples

**Comment by jkoritzinsky** [comment]
I'm okay adding DisplayName support, but I want to match the dotnet test/xunit syntax as much as possible.

**Comment by markples** [comment]
Just to be clear, do you mean like in https://learn.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests?pivots=xunit? Therefore, the minimal support here would be `DisplayName~<name>`.

The display name that we are using is specific to the dotnet repo.  If I recall correctly, it was to minimize test name churn when converting the tests to merged groups (or more specifically to xunit-style at all).  Do you plan to remove this at some point to get rid of the special case?  I guess perhaps that should be after figuring out how to merge the building of tests too, at which point these tests would fail to build and need to be updated with unique names.

**Comment by jkoritzinsky** [comment]
> Just to be clear, do you mean like in https://learn.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests?pivots=xunit? Therefore, the minimal support here would be `DisplayName~<name>`.

Yep that's what I'm thinking of. The TestFilter type already has support for it, but I never implemented the parsing.

> 
> The display name that we are using is specific to the dotnet repo.  If I recall correctly, it was to minimize test name churn when converting the tests to merged groups (or more specifically to xunit-style at all).  Do you plan to remove this at some point to get rid of the special case?  I guess perhaps that should be after figuring out how to merge the building of tests too, at which point these tests would fail to build and need to be updated with unique names.

Yes, I hope eventually we can get rid of issues.targets, the compat DisplayName generation, and merge the test builds for any non-out-of-proc tests. Once we do that work, there's even further simplifications we can do in our test infra to make it significantly easier to maintain.

Like the TestFilter infra, there's a few other elements of the merged test system that I initially added that can help preserve/improve the inner loop experience (build-time test filtering and being able to do BuildAsStandalone for the merged wrapper entry point for a simple "just run tests" experience) that we can utilize to help in the transition.
