### ISSUE TITLE
Auto-filling of tracking issues for CI jobs failures on main

### ISSUE THREAD

**Issue by matouskozak** [dotnet/runtime#93468]
**Goal**
Whenever new failure happens on a CI pipeline ran on the main branch, an auto-filled tracking issue gets created and assigned to preselected owner(s) of failed CI.

**Motivation**
Speed-up detection time of failing CI lines, especially optional ones which do not run on every PR. Additionally, improve Build Analysis experience on opened PRs.

**Possible hurdles**
- How to select error message (or pattern) from failed test to correctly fill the tracking issue.
- The created issues must get resolved quickly to keep the issue list size reasonable.
- iOS/TvOS reporting is different to the others (the failing tests are not shown in the console output)

---

Let me know what you think about this feature request.

cc: @SamMonoRT @kotlarmilos @ivanpovazan @fanyang-mono

**Comment by fanyang-mono** [comment]
My understanding is that the build analysis is the first step towards this final goal. Your idea is aligned where we are now. :)

**Comment by matouskozak** [comment]
@fanyang-mono My goal was to improve experience with using build analysis when a lot of un-tracked failures appear on a PR. Build analysis does highlight the tracked and un-tracked issues and it provides an option to create tracking issues for failing tests. However, in a scenario where issue is un-tracked you may still have to check manually if it is failing on main to determine if the failure is related to your PR. My idea was to remove this step (checking manually against main), so that everything failing on main is always tracked thus marked as "known test failure" in the build analysis.

**Comment by kotlarmilos** [comment]
Great initiative! Such bot could help us being more proactive about resolving failing jobs. Here is an API the bot could use: https://dev.azure.com/dnceng-public/public/_apis/build/builds/436308/Timeline

Feel free to provide additional information about the design and concept so that we can explore this idea further. It could be a relatively simple effort worth experimenting with.

**Comment by kotlarmilos** [comment]
Closing this issue as not planned.
