### ISSUE TITLE
System.IO.Compression.SubReadStream Read Makes Unnecessary Calls

### ISSUE THREAD

**Issue by debracey** [dotnet/runtime#93478]
### Description

The most recent patches for the dot net framework (v4.8 on Windows 11) are now seeing excessive calls to Stream.Read where the requested byte count during the read operation is 0. Is this expected? Shouldn't the read operation be blocked if the count is known to be 0?

### Reproduction Steps

```c#
using (var zipArchive = new ZipArchive(someStreamHere))
{
    var zipArchiveEntry = zipArchive.GetEntry("testFile.txt");
    using (var zipEntry = zipArchiveEntry.Open())
    {
        using (var streamReader = new StreamReader(zipEntry))
        {
            var fileContents = streamReader.ReadToEnd();
           // Do something with the file
        }
    }
}
``` 

### Expected behavior

The stream provided to the `ZipArchive` should be read, but the calls to the underlying Stream.Read should not request reads with count = 0

### Actual behavior

Calls are made to read the stream (`someStreamHere` in the example) with byte counts = 0

### Regression?

Unknown. I am still investigating this. It is possible this sample code always called Read with byte counts = 0, but I am not sure.

### Known Workarounds

None

### Configuration

Windows 11, x64. 
Dot net framework 4.8.09032

### Other information

From decompiling SubReadStream.cs from System.IO.Compression, we can see that the decompiled code appears to not account for the zero byte count case.

```c#
public override int Read(byte[] buffer, int offset, int count)
{
  this.ThrowIfDisposed();
  this.ThrowIfCantRead();
  
  if (this._superStream.Position != this._positionInSuperStream)
      this._superStream.Seek(this._positionInSuperStream, SeekOrigin.Begin);
  
  if (this._positionInSuperStream + (long) count > this._endInSuperStream)
      count = (int) (this._endInSuperStream - this._positionInSuperStream);
  
  // BUG: Count could be 0 here. Is calling this.superStream.Read with count = 0 expected?  
  int num = this._superStream.Read(buffer, offset, count);
  this._positionInSuperStream += (long) num;
  
  return num;
}
```

**Comment by danmoseley** [comment]
Hi @debracey this repo is actually for .NET Core/.NET 5+. The place where .NET Framework feedback reports go is [here](https://developercommunity.visualstudio.com/dotnet?port=1025&fsid=11683a65-ffec-4488-8d5e-c75e75f4c4f2)

That said, I wonder whether this, which relates to .NET Core, might still be relevant: https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams

**Comment by debracey** [comment]
Sorry, didn't realize this repo was only for .NET Core. I've cross posted this to the VS dev community:

https://developercommunity.visualstudio.com/t/SystemIOCompressionSubReadStream-Read/10491601

Yes, I think the link @danmoseley found is relevant, but in this case the code is running and compiled against full framework/.NET 4.8.
