### ISSUE TITLE
[API Proposal]: Add protected factory method for creating Label in ILGenerator, abstract out LocalBuilder

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#93497]
### Background and motivation

For adding [`AssemblyBuilder.Save()` equivalent in .NET Core](https://github.com/dotnet/runtime/issues/62956) we have [abstracted](https://github.com/dotnet/runtime/issues/78542) most of the System.Refleciton.Emit types and adding new implementations for them. This abstraction did not cover `Label` and `LocalBuilder` types and its constructors are internal, so I could not create an instance from the new `ILGenerator` implementation.

### API Proposal
- For `LocalBuilder` we need to unseal the `LocalBuilder` class and make it abstract, make the `internal` constructor `protected`, also add a public getter that exposes the `method` the local belongs to.

  ```diff
  namespace System.Reflection.Emit;

  -public sealed class LocalBuilder : System.Reflection.LocalVariableInfo
  +public abstract class LocalBuilder : System.Reflection.LocalVariableInfo
  {
  -   internal LocalBuilder(int localIndex, Type localType, MethodInfo method, bool isPinned) { }
  +   protected LocalBuilder() { }
  +   public abstract MethodInfo LocalMethod { get; }
  }
  ```

  Abstract `LocalMethod` property can be used for validation. Parent `LocalVariableInfo` has public virtual properties like `LocalType`, `LocalIndex`, `IsPinned`.

- For `Label` struct we need a protected factory method in the abstract `ILGenerator` type so that we can create an instance from derived types. 

  ```diff
  namespace System.Reflection.Emit;

  public abstract class ILGenerator
  {
      protected ILGenerator() { }
      ...
      public abstract Label DefineLabel();
  +   protected static Label CreateLabel(int id) { throw null; }
  }

  public readonly partial struct Label : System.IEquatable<System.Reflection.Emit.Label>
  {
      ...
  +   public int Id { get; }
  }
  ```

### API Usage

```csharp
internal sealed class ILGeneratorImpl : ILGenerator
{
    public override Label DefineLabel()
    {
        LabelHandle metadataLabel = _il.DefineLabel();
        Label emitLabel = CreateLabel(metadataLabel.Id);
        _labelTable.Add(emitLabel, metadataLabel);
        return emitLabel;
    }
}
```

Related to https://github.com/dotnet/runtime/issues/92975

CC @steveharter

**Comment by teo-tsirpanis** [comment]
How about we add a way to get the ID of a label, either as an `Id` property of `Label`, or (preferably) as a `protected int GetLabelId(Label label);` method on `ILGenerator`?

**Comment by buyaa-n** [comment]
> How about we add a way to get the ID of a label, either as an Id property of Label, or (preferably) as a protected int GetLabelId(Label label); method on ILGenerator?

That can be useful for handling labels, I think it should be added to the `Label` struct, also added `LocalMethod` property for `LocalBuilder`.

**Comment by teo-tsirpanis** [comment]
How about we make `CreateLabel` static?

```diff
- protected Label CreateLabel(int id) { throw null;}
+ protected static Label CreateLabel(int id) { throw null; }
```

**Comment by buyaa-n** [comment]
> How about we make `CreateLabel` static?

Updated, thanks!

**Comment by bartonjs** [comment]
There was discussion around `LocalBuilder.LocalMethod` being an abstract property or a value passed in via the constructor.  Since everything else in the hierarchy is abstract properties, it is locally consistent as proposed.

Since the method isn't a feature of the local, but instead describes the context where it exists, the property should be `Method` not `LocalMethod`

```C#
namespace System.Reflection.Emit;

-public sealed class LocalBuilder : System.Reflection.LocalVariableInfo
+public abstract class LocalBuilder : System.Reflection.LocalVariableInfo
{
-   internal LocalBuilder(int localIndex, Type localType, MethodInfo method, bool isPinned) { }
+   protected LocalBuilder() { }
+   public abstract MethodInfo Method { get; }
}

public abstract class ILGenerator
{
    protected ILGenerator() { }
    ...
    public abstract Label DefineLabel();
+   protected static Label CreateLabel(int id) { throw null; }
}

public readonly partial struct Label : System.IEquatable<System.Reflection.Emit.Label>
{
    ...
+   public int Id { get; }
}
```

**Comment by lambdageek** [comment]
This API seems wrong to me:

> `public abstract MethodInfo LocalMethod { get; }`

I think this needs to be `MethodBase`, not `MethodInfo`. Constructors can have locals, too

**Comment by buyaa-n** [comment]
@bartonjs and @dotnet/fxdc there were [push back](https://github.com/dotnet/runtime/pull/93809#discussion_r1372409121) on adding `MethodInfo Method` property for `LocalBuilder`, mono implementation uses ILGenerator instead of the Method the local belongs to. We had some [discussion](https://github.com/dotnet/runtime/pull/93809#discussion_r1373344639) in the PR and experts suggesting to not expose this property. Sorry for the inconvenience and I ask to remove the property from the approved API

```diff
-   public abstract MethodInfo Method { get; }
```

**Comment by buyaa-n** [comment]
Confirmed that removing the new Property is OK, no need any other action
