### ISSUE TITLE
[6.0, 7.0] System.Diagnostics.Tests.ProcessTests.Test*WorkingSet* assert failures

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#93491]
### Error Blob

Affecting both 6.0 and 7.0 and both TestWorkingSet and TestWorkingSet64

```json
{
  "ErrorMessage": "",
  "BuildRetry": false,
  "ErrorPattern": "at System.Diagnostics.Tests.ProcessTests.Test.*WorkingSet",
  "ExcludeConsoleLog": true
}
```

### Reproduction Steps

- Affected 7.0 PR: https://github.com/dotnet/runtime/pull/92980
- Affected 6.0 PRs: https://github.com/dotnet/runtime/pull/93396 , https://github.com/dotnet/runtime/pull/93395
- Queue: `Libraries Test Run release mono Linux x64 Debug`
- Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=437130&view=logs&j=b4344b0d-0f92-5d69-ccaf-e0b24fbf14a2&t=65a58faa-a542-5344-b5c8-897139f242cd&l=103
- Log file: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-pull-92980-merge-e1e1a34e95a948d8ab/System.Diagnostics.Process.Tests/1/console.a0886c34.log?helixlogtype=result
- Output:
  - TestWorkingSet
```
    System.Diagnostics.Tests.ProcessTests.TestWorkingSet [FAIL]
      Assert.InRange() Failure
      Range:  (1 - 2147483647)
      Actual: 0
      Stack Trace:
        /_/src/libraries/System.Diagnostics.Process/tests/ProcessTests.cs(2081,0): at System.Diagnostics.Tests.ProcessTests.TestWorkingSet()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs(69,0): at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```
  - TestWorkingSet64
  ```
    System.Diagnostics.Tests.ProcessTests.TestWorkingSet64 [FAIL]
      Assert.InRange() Failure
      Range:  (1 - 9223372036854775807)
      Actual: 0
      Stack Trace:
        /_/src/libraries/System.Diagnostics.Process/tests/ProcessTests.cs(822,0): at System.Diagnostics.Tests.ProcessTests.TestWorkingSet64()
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodInvoker.Mono.cs(33,0): at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=437130
**Error message validated:** `at System.Diagnostics.Tests.ProcessTests.Test.*WorkingSet`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 10/16/2023 6:29:54 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[440191](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440191)|dotnet/runtime|[System.Diagnostics.Tests.ProcessTests.TestPeakWorkingSet](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440191&view=ms.vss-test-web.build-test-results-tab&runId=9806750&resultId=135144)|dotnet/runtime#93395|
|[440236](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440236)|dotnet/runtime|[System.Diagnostics.Tests.ProcessTests.TestWorkingSet64](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440236&view=ms.vss-test-web.build-test-results-tab&runId=9804698&resultId=161753)||
|[440233](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440233)|dotnet/runtime|[System.Diagnostics.Tests.ProcessTests.TestPeakWorkingSet](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440233&view=ms.vss-test-web.build-test-results-tab&runId=9804312&resultId=136039)||
|[440099](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440099)|dotnet/runtime|[System.Diagnostics.Tests.ProcessTests.TestPeakWorkingSet64](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440099&view=ms.vss-test-web.build-test-results-tab&runId=9799866&resultId=135299)||
|[440091](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440091)|dotnet/runtime|[System.Diagnostics.Tests.ProcessTests.TestWorkingSet](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440091&view=ms.vss-test-web.build-test-results-tab&runId=9799598&resultId=155370)||
|[440086](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440086)|dotnet/runtime|[System.Diagnostics.Tests.ProcessTests.TestWorkingSet64](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440086&view=ms.vss-test-web.build-test-results-tab&runId=9799566&resultId=142311)||
|[439891](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439891)|dotnet/runtime|[System.Diagnostics.Tests.ProcessTests.TestPeakWorkingSet](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439891&view=ms.vss-test-web.build-test-results-tab&runId=9794090&resultId=131512)|dotnet/runtime#93554|
|[439429](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439429)|dotnet/runtime|[System.Diagnostics.Tests.ProcessTests.TestPeakWorkingSet](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439429&view=ms.vss-test-web.build-test-results-tab&runId=9792420&resultId=139302)|dotnet/runtime#93543|
|[439643](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439643)|dotnet/runtime|[System.Diagnostics.Tests.ProcessTests.TestWorkingSet](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439643&view=ms.vss-test-web.build-test-results-tab&runId=9790566&resultId=157364)|dotnet/runtime#93395|
|[439131](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439131)|dotnet/runtime|[System.Diagnostics.Tests.ProcessTests.TestWorkingSet](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439131&view=ms.vss-test-web.build-test-results-tab&runId=9772858&resultId=130661)|dotnet/runtime#93530|
|[439030](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439030)|dotnet/runtime|[System.Diagnostics.Tests.ProcessTests.TestWorkingSet](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439030&view=ms.vss-test-web.build-test-results-tab&runId=9770756&resultId=157986)|dotnet/runtime#93395|
|[438653](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438653)|dotnet/runtime|[System.Diagnostics.Tests.ProcessTests.TestWorkingSet](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438653&view=ms.vss-test-web.build-test-results-tab&runId=9759848&resultId=160922)|dotnet/runtime#93395|
|[438403](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438403)|dotnet/runtime|[System.Diagnostics.Tests.ProcessTests.TestWorkingSet](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438403&view=ms.vss-test-web.build-test-results-tab&runId=9749924&resultId=132035)|dotnet/runtime#93505|
|[438355](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438355)|dotnet/runtime|[System.Diagnostics.Tests.ProcessTests.TestWorkingSet](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438355&view=ms.vss-test-web.build-test-results-tab&runId=9748198&resultId=129624)||
|[438271](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438271)|dotnet/runtime|[System.Diagnostics.Tests.ProcessTests.TestWorkingSet64](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438271&view=ms.vss-test-web.build-test-results-tab&runId=9745520&resultId=171901)|dotnet/runtime#93395|
|[438277](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438277)|dotnet/runtime|[System.Diagnostics.Tests.ProcessTests.TestWorkingSet](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438277&view=ms.vss-test-web.build-test-results-tab&runId=9745496&resultId=164871)|dotnet/runtime#93390|
|[438264](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438264)|dotnet/runtime|[System.Diagnostics.Tests.ProcessTests.TestWorkingSet](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438264&view=ms.vss-test-web.build-test-results-tab&runId=9744782&resultId=126977)||
|[438244](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438244)|dotnet/runtime|[System.Diagnostics.Tests.ProcessTests.TestWorkingSet](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438244&view=ms.vss-test-web.build-test-results-tab&runId=9744712&resultId=137047)||
|[438152](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438152)|dotnet/runtime|[System.Diagnostics.Tests.ProcessTests.TestWorkingSet64](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438152&view=ms.vss-test-web.build-test-results-tab&runId=9741872&resultId=146734)|dotnet/runtime#92979|
|[437229](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437229)|dotnet/runtime|[System.Diagnostics.Tests.ProcessTests.TestWorkingSet64](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437229&view=ms.vss-test-web.build-test-results-tab&runId=9739286&resultId=151968)|dotnet/runtime#93396|
|[437672](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437672)|dotnet/runtime|[System.Diagnostics.Tests.ProcessTests.TestWorkingSet](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437672&view=ms.vss-test-web.build-test-results-tab&runId=9732252&resultId=147925)|dotnet/runtime#93395|
|[437130](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437130)|dotnet/runtime|[System.Diagnostics.Tests.ProcessTests.TestWorkingSet](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437130&view=ms.vss-test-web.build-test-results-tab&runId=9718794&resultId=134680)|dotnet/runtime#92980|
|[436528](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436528)|dotnet/runtime|[System.Diagnostics.Tests.ProcessTests.TestWorkingSet64](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436528&view=ms.vss-test-web.build-test-results-tab&runId=9712432&resultId=150119)|dotnet/runtime#93395|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|9|23|23|

**Comment by lambdageek** [comment]
Maybe we need https://github.com/dotnet/runtime/pull/85649 ?

**Comment by carlossanlop** [comment]
Should be fixed with https://github.com/dotnet/runtime/pull/93572 and https://github.com/dotnet/runtime/pull/93574
