### ISSUE TITLE
ConfigurationBinder source generator encounters namespace conflicts in using statements

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#93498]
### Description

When the first part of a namespace of a bound type exists under the Microsoft namespace an error will occur
```c#
using Microsoft.Extensions.Configuration;
var c = new ConfigurationBuilder().Build();
c.Get<Foo.Bar.BType>();

namespace Microsoft.Foo
{
    internal class AType {}
}

namespace Foo.Bar
{
    internal class BType {}
}
```

> C:\scratch\namespaceConflict\Microsoft.Extensions.Configuration.Binder.SourceGeneration\Microsoft.Extensions.Configuration.Binder.SourceGeneration.ConfigurationBindingGenerator\BindingExtensions.g.cs(22,15): error CS0234: The type or namespace name 'Bar' does not exist in the namespace 'Microsoft.Foo' (are you missing an assembly reference?) [C:\scratch\namespaceConflict\namespaceConflict.csproj]

This is happening because the generator places using statements in a namespace `Microsoft.Extensions.Configuration.Binder.SourceGeneration` and this will cause the compiler to first search in containing namespaces at every level before considering the global namespace for usings placed in that namespace.

Hit this when porting eShopOnContainers.

### Reproduction Steps

Build 
[namespaceConflict.zip](https://github.com/dotnet/runtime/files/12900998/namespaceConflict.zip)

### Expected behavior

Builds without issue

### Actual behavior

Compilation error.

### Regression?

No

### Known Workarounds

Alias the reference that has the conflicting namespace, change namespace names, etc.

**Comment by eerhardt** [comment]
I'm hitting this same issue trying to use the ConfigBinder Source Generator with the Azure SDK:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
    <NoWarn>$(NoWarn);SYSLIB1100;SYSLIB1101</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.0-rtm.23511.16" />
    <PackageReference Include="Azure.Data.Tables" Version="12.8.1" />
  </ItemGroup>

</Project>
```

```csharp
using Azure.Data.Tables;
using Microsoft.Extensions.Configuration;

Console.WriteLine("Hello, World!");

static void BindToConfiguration(TableClientOptions options, IConfiguration configuration)
{
    var configurationOptionsSection = configuration.GetSection("ConfigurationOptions");
    configurationOptionsSection.Bind(options);
}
```

results in:

```
1>C:\Users\eerhardt\source\repos\ConsoleApp101\ConsoleApp101\Microsoft.Extensions.Configuration.Binder.SourceGeneration\Microsoft.Extensions.Configuration.Binder.SourceGeneration.ConfigurationBindingGenerator\BindingExtensions.g.cs(22,17,22,21): error CS0234: The type or namespace name 'Core' does not exist in the namespace 'Microsoft.Extensions.Azure' (are you missing an assembly reference?)
1>C:\Users\eerhardt\source\repos\ConsoleApp101\ConsoleApp101\Microsoft.Extensions.Configuration.Binder.SourceGeneration\Microsoft.Extensions.Configuration.Binder.SourceGeneration.ConfigurationBindingGenerator\BindingExtensions.g.cs(23,17,23,21): error CS0234: The type or namespace name 'Data' does not exist in the namespace 'Microsoft.Extensions.Azure' (are you missing an assembly reference?)
1>C:\Users\eerhardt\source\repos\ConsoleApp101\ConsoleApp101\Microsoft.Extensions.Configuration.Binder.SourceGeneration\Microsoft.Extensions.Configuration.Binder.SourceGeneration.ConfigurationBindingGenerator\BindingExtensions.g.cs(71,71,71,89): error CS0246: The type or namespace name 'DiagnosticsOptions' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\eerhardt\source\repos\ConsoleApp101\ConsoleApp101\Microsoft.Extensions.Configuration.Binder.SourceGeneration\Microsoft.Extensions.Configuration.Binder.SourceGeneration.ConfigurationBindingGenerator\BindingExtensions.g.cs(145,71,145,83): error CS0246: The type or namespace name 'RetryOptions' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\eerhardt\source\repos\ConsoleApp101\ConsoleApp101\Microsoft.Extensions.Configuration.Binder.SourceGeneration\Microsoft.Extensions.Configuration.Binder.SourceGeneration.ConfigurationBindingGenerator\BindingExtensions.g.cs(195,71,195,84): error CS0246: The type or namespace name 'ClientOptions' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\eerhardt\source\repos\ConsoleApp101\ConsoleApp101\Microsoft.Extensions.Configuration.Binder.SourceGeneration\Microsoft.Extensions.Configuration.Binder.SourceGeneration.ConfigurationBindingGenerator\BindingExtensions.g.cs(249,71,249,89): error CS0246: The type or namespace name 'TableClientOptions' could not be found (are you missing a using directive or an assembly reference?)
```

The issue here is that all the Azure SDK libraries put some extensions class in the `Microsoft.Extensions.Azure` namespace, and the compiler gets confused at this source generated code:

```csharp
namespace Microsoft.Extensions.Configuration.Binder.SourceGeneration
{
    using Azure.Core;
    using Azure.Data.Tables;
```

Since it is in `Microsoft.Extensions.....` it thinks `using Azure.Core` means `using Microsoft.Extensions.Azure` and there is no `Core` namespace in there. I think the other errors are the same as #94065.

**Comment by ericstj** [comment]
We need to use a global prefix when importing namespaces here.

**Comment by ericstj** [comment]
We should actually never add using statements here.  Those using statements are being driven by types referenced across many files, combining all the using statements in a single file can cause name conflicts (even ignoring this special case).

I heard from @captainsafia via @eerhardt 
> if you always prefix `global::` for all types coming from users code, and never let users code add a using statement to your generated code, then you should be good

We need to do this.

**Comment by captainsafia** [comment]
Yep, [here](https://github.com/dotnet/aspnetcore/blob/73e0b536d411a38c745b2a7ee5b04f04ee4fe6ea/src/Http/Http.Extensions/gen/StaticRouteHandlerModel/Emitters/EmitterConstants.cs) is the configuration we use for displaying type names in RDG.
