### ISSUE TITLE
Test failure: JIT/opt/AssertionPropagation/ArrBoundElim/ArrBoundElim.dll

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#93508]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=437587
Build error leg or test failing: JIT.opt.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/93446

## Error Message

```
03:13:37.921 Running test: JIT/opt/AssertionPropagation/ArrBoundElim/ArrBoundElim.dll
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Tests.MulOverflow()
   at Program.RunTestThrows(System.Action)
   at Program.TestEntryPoint()
   at Program.<<Main>$>g__TestExecutor4|0_5(System.IO.StreamWriter, System.IO.StreamWriter, <>c__DisplayClass0_0 ByRef)
   at Program.<Main>$(System.String[])
App Exit Code: -1073741819
```

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "at Tests.MulOverflow()",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=437587
**Error message validated:** `at Tests.MulOverflow()`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 10/14/2023 5:23:40 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[439749](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439749)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439749&view=ms.vss-test-web.build-test-results-tab&runId=9792516&resultId=112723)|dotnet/runtime#93282|
|[439744](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439744)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439744&view=ms.vss-test-web.build-test-results-tab&runId=9792176&resultId=112723)|dotnet/runtime#93549|
|[439069](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439069)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439069&view=ms.vss-test-web.build-test-results-tab&runId=9772002&resultId=112723)|dotnet/runtime#93282|
|[438819](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438819)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438819&view=ms.vss-test-web.build-test-results-tab&runId=9763764&resultId=113321)|dotnet/runtime#93523|
|[438708](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438708)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438708&view=ms.vss-test-web.build-test-results-tab&runId=9760884&resultId=112723)|dotnet/runtime#93282|
|[438494](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438494)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438494&view=ms.vss-test-web.build-test-results-tab&runId=9754150&resultId=112723)||
|[438414](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438414)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438414&view=ms.vss-test-web.build-test-results-tab&runId=9750694&resultId=120159)||
|[438399](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438399)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438399&view=ms.vss-test-web.build-test-results-tab&runId=9750230&resultId=112723)||
|[437587](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437587)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437587&view=ms.vss-test-web.build-test-results-tab&runId=9750076&resultId=113321)|dotnet/runtime#93446|
|[438312](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438312)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438312&view=ms.vss-test-web.build-test-results-tab&runId=9749016&resultId=120159)||
|[438310](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438310)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438310&view=ms.vss-test-web.build-test-results-tab&runId=9748168&resultId=112723)||
|[438277](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438277)|dotnet/runtime|[JIT.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438277&view=ms.vss-test-web.build-test-results-tab&runId=9746528&resultId=102268)|dotnet/runtime#93390|
|[437551](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437551)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437551&view=ms.vss-test-web.build-test-results-tab&runId=9743256&resultId=113321)|dotnet/runtime#93429|
|[437724](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437724)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437724&view=ms.vss-test-web.build-test-results-tab&runId=9735056&resultId=112723)|dotnet/runtime#93470|
|[437683](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437683)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437683&view=ms.vss-test-web.build-test-results-tab&runId=9735054&resultId=113321)|dotnet/runtime#93465|
|[437731](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437731)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437731&view=ms.vss-test-web.build-test-results-tab&runId=9734168&resultId=112723)|dotnet/runtime#93282|
|[437581](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437581)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437581&view=ms.vss-test-web.build-test-results-tab&runId=9733710&resultId=113321)|dotnet/runtime#93280|
|[437666](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437666)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437666&view=ms.vss-test-web.build-test-results-tab&runId=9732740&resultId=113321)|dotnet/runtime#93437|
|[437533](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437533)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437533&view=ms.vss-test-web.build-test-results-tab&runId=9728936&resultId=113321)|dotnet/runtime#93407|
|[437498](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437498)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437498&view=ms.vss-test-web.build-test-results-tab&runId=9727948&resultId=113321)|dotnet/runtime#93463|
|[437456](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437456)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437456&view=ms.vss-test-web.build-test-results-tab&runId=9726888&resultId=120757)||
|[437471](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437471)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437471&view=ms.vss-test-web.build-test-results-tab&runId=9726914&resultId=113321)|dotnet/runtime#93367|
|[437458](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437458)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437458&view=ms.vss-test-web.build-test-results-tab&runId=9726472&resultId=113321)|dotnet/runtime#93345|
|[437422](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437422)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437422&view=ms.vss-test-web.build-test-results-tab&runId=9725252&resultId=113321)|dotnet/runtime#93450|
|[437377](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437377)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437377&view=ms.vss-test-web.build-test-results-tab&runId=9723946&resultId=113321)|dotnet/runtime#93407|
|[437331](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437331)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437331&view=ms.vss-test-web.build-test-results-tab&runId=9722462&resultId=113321)|dotnet/runtime#93446|
|[437309](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437309)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437309&view=ms.vss-test-web.build-test-results-tab&runId=9722388&resultId=120757)||
|[437314](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437314)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437314&view=ms.vss-test-web.build-test-results-tab&runId=9722208&resultId=113321)|dotnet/runtime#93445|
|[437294](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437294)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437294&view=ms.vss-test-web.build-test-results-tab&runId=9721368&resultId=113321)|dotnet/runtime#93440|
|[436887](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436887)|dotnet/runtime|[JIT.opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436887&view=ms.vss-test-web.build-test-results-tab&runId=9719342&resultId=113321)|dotnet/runtime#93346|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|2|30|30|

**Comment by jkotas** [comment]
@BruceForstall @jakobbotsch This looks like another symptom of https://github.com/dotnet/runtime/issues/93442#issuecomment-1761247844

**Comment by jakobbotsch** [comment]
Disabled in #93451.
