### ISSUE TITLE
Fix regression or document breaking change in BinaryReader

### ISSUE THREAD

**Issue by jozkee** [dotnet/runtime#93500]
Follow-up to https://github.com/dotnet/runtime/pull/80331#discussion_r1283813869.

On the following code:
```cs
var ms = new MemoryStream(new byte[] { 0x01, 0xC2 });
using (var br = new BinaryReader(ms))
{
    string s = br.ReadString();

    Console.WriteLine(s);
    Console.WriteLine(s.Length);
    Console.WriteLine(s == "\uFFFD");
}
```

`ReadString` returns empty string on .NET 8 or prior. After https://github.com/dotnet/runtime/pull/80331, it returns "\uFFFD". 

Thanks @GrabYourPitchforks for pointing the error after merge and share the affected scenario in question.
cc @teo-tsirpanis @adamsitnik

**Comment by adamsitnik** [comment]
I've missed the notification. @teo-tsirpanis PTAL

**Comment by teo-tsirpanis** [comment]
This new behavior seems the correct one, and matches Unicode standards, and [a breaking change](https://learn.microsoft.com/en-us/dotnet/core/compatibility/corefx#replacing-ill-formed-utf-8-byte-sequences-follows-unicode-guidelines) done in .NET Core 3.0.

**Comment by jeffhandley** [comment]
Thanks, @teo-tsirpanis! Closing this issue since the new behavior is correct and intentional, and it was documented.

**Comment by Jozkee** [comment]
@jeffhandley that document is for 3.0, it may be surprising for customers jumping from 8.0 or lower to not find this documented as part of 9.0 breaking changes.

**Comment by jozkee** [comment]
https://github.com/dotnet/docs/issues/42564
