### ISSUE TITLE
SuperPMI replay failure: (unsigned)reg < ArrLen(regMasks)

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#93527]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=438916
Build error leg or test failing: Build / SuperPMI replay windows x64 checked / Send job to Helix (Windows)
Pull request: https://github.com/dotnet/runtime/pull/93429

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "(unsigned)reg < ArrLen(regMasks)",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

Failed in 3 different PRs, log: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-92844-merge-5ef593d10a7842f881/linux-arm64-2/1/console.17223591.log?helixlogtype=result

cc @dotnet/jit-contrib 

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=438916
**Error message validated:** `(unsigned)reg < ArrLen(regMasks)`
**Result validation: :x:** Known issue did not match with the provided build.
**Validation performed at:** 10/15/2023 3:53:49 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[439272](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439272)|dotnet/runtime|[HardwareIntrinsics_Arm_ro.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439272&view=ms.vss-test-web.build-test-results-tab&runId=9777234&resultId=118772)||
|[439144](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439144)|dotnet/runtime|[HardwareIntrinsics_Arm_ro.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439144&view=ms.vss-test-web.build-test-results-tab&runId=9773234&resultId=118775)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|2|2|

**Comment by EgorBo** [comment]
cc @kunalspathak might be related to the intrinsics you added

**Comment by BruceForstall** [comment]
Related: https://github.com/dotnet/runtime/pull/93197

**Comment by BruceForstall** [comment]
Looks like linux-arm64, JitStressRegs=8
