### ISSUE TITLE
LibraryImport issue

### ISSUE THREAD

**Issue by nijaguna2018** [dotnet/runtime#93544]
I have been trying to use this code in the WPF application developed using .NET 7.

```
 [DllImport("user32.dll")]
 internal static extern bool InsertMenu(IntPtr Menu, Int32 Position, Int32 Flags, Int32 IDNewItem, string NewItem);
```

However I get the SYSLIB1054 message : "Mark the method 'InsertMenu' with 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time"

I changed the code as below

```
[LibraryImport("user32.dll")]
[return: MarshalAs(UnmanagedType.Bool)]
internal static partial bool InsertMenu(IntPtr Menu, Int32 Position, Int32 Flags, Int32 IDNewItem, [MarshalAs(UnmanagedType.LPUTF8Str)] string NewItem);
```

Then I get this error : "Unable to find an entry point named 'InsertMenu' in DLL 'user32.dll'."

How do I fix this?

**Comment by Gaoyifei1011** [comment]
This function has two alias, insertmenua and insertmenuw. The previous dllimportattribute can determine the alias entry by setting the charset field, but now libraryimport does not have this feature. You need to specify entrypoint as insertmenuw

**Comment by huoyaoyuan** [comment]
Note that for `W` variant of methods, `LPUTF8Str` is incorrect. Use `LPWSTR` on the parameter or `StringMarshalling.Utf16` on the attributes.

Most Windows APIs don't use UTF8 at all. UTF16 is the standard of Windows.

**Comment by Gaoyifei1011** [comment]
> Note that for `W` variant of methods, `LPUTF8Str` is incorrect. Use `LPWSTR` on the parameter or `StringMarshalling.Utf16` on the attributes.
> 
> Most Windows APIs don't use UTF8 at all. UTF16 is the standard of Windows.

Yes, your answer is correct. If you use libraryimport, we could add stringmarshalling by following visual studio's smart prompts
