### ISSUE TITLE
[API Proposal]: Base 64 Decoding Should Have An Auto-Padding Option

### ISSUE THREAD

**Issue by jpbulman** [dotnet/runtime#93552]
### Background and motivation

The current behavior of `System.Convert.FromBase64String` is to throw a `FormatException` when a string does not have a valid length for a base-64 string  (i.e. is not a multiple of four). A common remediation is to append `=`, the padding character in base-64, until the string is a valid length such that the exception will not be thrown.

Instead, `System.Convert.FromBase64String` should have a way to pad invalid strings automatically such that the caller does not have to worry about this formatting issue. 

### API Proposal

Ideally, there should be no change to the current signature of the function and it should fix this problem in the implementation.
```csharp
namespace System;

public class Convert
{
    public static unsafe byte[] FromBase64String(string s);
}
```

### API Usage

```csharp
// Current behavior
var test = System.Convert.FromBase64String("VGhpcyBpcyBhIHRlc3Q");  // Throws an exception

// Ideal behavior
var test = System.Convert.FromBase64String("VGhpcyBpcyBhIHRlc3Q");  // Does *not* throw an exception
Console.WriteLine(System.Text.Encoding.Default.GetString(test));    // "This is a test"
```

### Alternative Designs

There could also be an overload of this method to take in some sort of enum to indicate how this padding should be treated
```csharp
using System;
var i = Convert.FromBase64String("VGhpcyBpcyBhIHRlc3Q", Convert.Base64Format.Strict); // Throws exception
var j = Convert.FromBase64String("VGhpcyBpcyBhIHRlc3Q", Convert.Base64Format.WithPadding); // ✔️
```

**Comment by gfoidl** [comment]
> pad invalid strings automatically such that the caller does not have to worry about this formatting issue

A invalid base64 string is...: invalid. So it should not (by no means) made automatically valid. 
That could open several security holes, be a breaking change as lots of code relies on the validating behavior of the implementation.

If this is considered, then like presented in "Alternative Designs".

But: why do you have invalid base64 strings at all?
Did you confuse base64 with bas64Url (the url-encoded form that has no padding, and `+` -> `-` as well `/` -> `_`)?

**Comment by vcsjones** [comment]
> why do you have invalid base64 strings at all?

There are a couple of RFCs that use "modified base64" which basically omit the base64 padding, often seen around UTF-7.

Even RFC 4648 says:

> In some circumstances, the use of padding ("=") in base-encoded data
   is not required or used.  In the general case, when assumptions about
   the size of transported data cannot be made, padding is required to
   yield correct decoded data.

>   Implementations MUST include appropriate pad characters at the end of
   encoded data unless the specification referring to this document
   explicitly states otherwise.

Even `ssh` likes to refer to key thumbprints in base64 but omits padding.

I personally agree with the assessment that the existing APIs should not become lax around padding. However I can understand why someone might have unpadded base64 data.

**Comment by tannergooding** [comment]
Based on the conversation given so far, I don't think this is actionable "as is".

It might be conceivable to go with one of the alternative designs where supporting no padding can be given via an explicit opt-in, but the proposal would need to be updated to follow that.
