### ISSUE TITLE
Outerloop test System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash crashing often

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#93569]
### Error Blob

```json
{
  "ErrorMessage": "System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": true
}
```

I noticed a lot of failures for this test being flagged by https://github.com/dotnet/runtime/issues/93372.

Opening up a dedicated issue for this one.

Failures look like:
```
    System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Exit code was 139 but it should have been 42
      Stack Trace:
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(242,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing)
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(55,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose()
        /_/src/libraries/System.Diagnostics.DiagnosticSource/tests/DiagnosticSourceEventSourceBridgeTests.cs(1183,0): at System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(57,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
  Finished:    System.Diagnostics.DiagnosticSource.Tests
```

Many seem to have dumps associated.  

Looks like @stephentoub added this test in https://github.com/dotnet/runtime/commit/ce44605dfcd681e49b14921efaf5b1528ac6a80d.

Not clear to me if this is a recent regression or if it's always been this way.  The couple weeks of history we have in AzDo from manual outerloop runs does not show any trends.

 ### Known issue validation
**Build: :mag_right:** 
**Result validation: :warning:** Validation could not be done without an Azure DevOps build URL on the issue. Please add it to the "**Build: :mag_right:**" line.
**Validation performed at:** 10/16/2023 7:05:46 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[449202](https://dev.azure.com/dnceng-public/public/_build/results?buildId=449202)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=449202&view=ms.vss-test-web.build-test-results-tab&runId=10066878&resultId=106172)||
|[449201](https://dev.azure.com/dnceng-public/public/_build/results?buildId=449201)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=449201&view=ms.vss-test-web.build-test-results-tab&runId=10066820&resultId=104251)||
|[449203](https://dev.azure.com/dnceng-public/public/_build/results?buildId=449203)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=449203&view=ms.vss-test-web.build-test-results-tab&runId=10066846&resultId=104247)||
|[449198](https://dev.azure.com/dnceng-public/public/_build/results?buildId=449198)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=449198&view=ms.vss-test-web.build-test-results-tab&runId=10066704&resultId=104247)||
|[449204](https://dev.azure.com/dnceng-public/public/_build/results?buildId=449204)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=449204&view=ms.vss-test-web.build-test-results-tab&runId=10066950&resultId=104246)||
|[449185](https://dev.azure.com/dnceng-public/public/_build/results?buildId=449185)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=449185&view=ms.vss-test-web.build-test-results-tab&runId=10066926&resultId=104249)||
|[449184](https://dev.azure.com/dnceng-public/public/_build/results?buildId=449184)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=449184&view=ms.vss-test-web.build-test-results-tab&runId=10066632&resultId=104251)||
|[447495](https://dev.azure.com/dnceng-public/public/_build/results?buildId=447495)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=447495&view=ms.vss-test-web.build-test-results-tab&runId=10019224&resultId=104247)||
|[446969](https://dev.azure.com/dnceng-public/public/_build/results?buildId=446969)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=446969&view=ms.vss-test-web.build-test-results-tab&runId=10003302&resultId=104247)||
|[446970](https://dev.azure.com/dnceng-public/public/_build/results?buildId=446970)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=446970&view=ms.vss-test-web.build-test-results-tab&runId=10003212&resultId=104248)||
|[446957](https://dev.azure.com/dnceng-public/public/_build/results?buildId=446957)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=446957&view=ms.vss-test-web.build-test-results-tab&runId=10003172&resultId=104004)||
|[446569](https://dev.azure.com/dnceng-public/public/_build/results?buildId=446569)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=446569&view=ms.vss-test-web.build-test-results-tab&runId=9991720&resultId=104251)||
|[446577](https://dev.azure.com/dnceng-public/public/_build/results?buildId=446577)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=446577&view=ms.vss-test-web.build-test-results-tab&runId=9991696&resultId=104246)||
|[446578](https://dev.azure.com/dnceng-public/public/_build/results?buildId=446578)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=446578&view=ms.vss-test-web.build-test-results-tab&runId=9991680&resultId=104248)||
|[446573](https://dev.azure.com/dnceng-public/public/_build/results?buildId=446573)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=446573&view=ms.vss-test-web.build-test-results-tab&runId=9991636&resultId=104246)||
|[446558](https://dev.azure.com/dnceng-public/public/_build/results?buildId=446558)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=446558&view=ms.vss-test-web.build-test-results-tab&runId=9991536&resultId=104247)||
|[445346](https://dev.azure.com/dnceng-public/public/_build/results?buildId=445346)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=445346&view=ms.vss-test-web.build-test-results-tab&runId=9961152&resultId=104247)||
|[445352](https://dev.azure.com/dnceng-public/public/_build/results?buildId=445352)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=445352&view=ms.vss-test-web.build-test-results-tab&runId=9961090&resultId=104246)||
|[445350](https://dev.azure.com/dnceng-public/public/_build/results?buildId=445350)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=445350&view=ms.vss-test-web.build-test-results-tab&runId=9961112&resultId=104248)||
|[445348](https://dev.azure.com/dnceng-public/public/_build/results?buildId=445348)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=445348&view=ms.vss-test-web.build-test-results-tab&runId=9961244&resultId=104247)||
|[445337](https://dev.azure.com/dnceng-public/public/_build/results?buildId=445337)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=445337&view=ms.vss-test-web.build-test-results-tab&runId=9961230&resultId=104250)||
|[445357](https://dev.azure.com/dnceng-public/public/_build/results?buildId=445357)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=445357&view=ms.vss-test-web.build-test-results-tab&runId=9960962&resultId=104250)||
|[445358](https://dev.azure.com/dnceng-public/public/_build/results?buildId=445358)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=445358&view=ms.vss-test-web.build-test-results-tab&runId=9960840&resultId=104005)||
|[443806](https://dev.azure.com/dnceng-public/public/_build/results?buildId=443806)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=443806&view=ms.vss-test-web.build-test-results-tab&runId=9917380&resultId=104247)||
|[443795](https://dev.azure.com/dnceng-public/public/_build/results?buildId=443795)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=443795&view=ms.vss-test-web.build-test-results-tab&runId=9917404&resultId=104000)||
|[443799](https://dev.azure.com/dnceng-public/public/_build/results?buildId=443799)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=443799&view=ms.vss-test-web.build-test-results-tab&runId=9917282&resultId=104247)||
|[442370](https://dev.azure.com/dnceng-public/public/_build/results?buildId=442370)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=442370&view=ms.vss-test-web.build-test-results-tab&runId=9868604&resultId=104246)||
|[442383](https://dev.azure.com/dnceng-public/public/_build/results?buildId=442383)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=442383&view=ms.vss-test-web.build-test-results-tab&runId=9868404&resultId=104247)||
|[440809](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440809)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440809&view=ms.vss-test-web.build-test-results-tab&runId=9821840&resultId=104247)||
|[440822](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440822)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440822&view=ms.vss-test-web.build-test-results-tab&runId=9821816&resultId=104254)||
|[439445](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439445)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439445&view=ms.vss-test-web.build-test-results-tab&runId=9783782&resultId=104247)||
|[439452](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439452)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439452&view=ms.vss-test-web.build-test-results-tab&runId=9783770&resultId=104250)||
|[439447](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439447)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439447&view=ms.vss-test-web.build-test-results-tab&runId=9783730&resultId=104247)||
|[439444](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439444)|dotnet/runtime|[System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439444&view=ms.vss-test-web.build-test-results-tab&runId=9783704&resultId=104248)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|7|28|34|

**Comment by davmason** [comment]
This test was deadlocking due to the same issue as #92236, it is fixed in main and 8.0 GA. If we continue to see failures please reopen
