### ISSUE TITLE
[NETSDKE2E] CoreFX symbols are missing while debugging IL Symbols on MacOS

### ISSUE THREAD

**Issue by WenJunJi01** [dotnet/runtime#93586]
### Environment
**Affected OS:** MacOS
**Affected Build:** 
VS Code: 1.83.1 from [Download Visual Studio Code - Mac, Linux, Windows](https://code.visualstudio.com/download)
C# Extension version: v2.6.24 (latest release from the marketplace)
CLI/SDK: 8.0.100-rtm.23512.16(runtime-8.0.0-rtm.23511.16) from [dotnet/installer: .NET SDK Installer (github.com)](https://github.com/dotnet/installer)

### Reproduction Steps

Testing on Linux with VSCode -

1. Create a new ASP.NET Razor project by doing
```
mkdir razor
cd razor
dotnet new razor
```
2. Install VS code
3. Launch VSCode and install the latest release C# extension.
4. Use File -> Open Folder to open the razor folder you have created in step 1
5. It may ask at the bottom right to install assets to build and debug, say yes.
6. After it has done this it will have created a .vscode directory in the ‘razor’ directory and a ‘launch.json’ file in that directory. Open the ‘.vscode’ directory, and double click on the ‘launch.json to edit it.
7. Add the following lines after the “name” line of the “Configurations” object. (This allows debugging through the framework.
```
"justMyCode": false,
"symbolOptions": {
"searchMicrosoftSymbolServer": true
},
"suppressJITOptimizations": true,

```
8. Add the following line to the Program.cs file
Console.WriteLine("x " + 3);
9. Place a breakpoint on that line (F9).

10. Run the application until it hit that breakpoint (F5). It will load symbols from the Microsoft symbol server, and may take a few seconds to hit the breakpoint. You should see 20-30 lines of ‘Loaded XXX Symbols loaded’. Lines as it does this).

11. Step into the concatination method (F11).

### Expected behavior

CoreCLR symbols are displayed in step13.

### Actual behavior

CoreCLR symbols are missing in step13.
![image](https://github.com/dotnet/runtime/assets/87680983/6e7d115d-580d-48cb-a657-a103d2b4e1a6)

### Known Workarounds
Manually running the following commands can sometimes solve this problem.
dotnet nuget locals all --clear
dotnet dev-certs https --clean
dotnet dev-certs https --trust

**dotnet --info**
.NET SDK:
 Version:           8.0.100-rtm.23512.16
 Commit:            cbfd87357c
 Workload version:  8.0.100-manifests.cbd66cf7

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.0
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.100-rtm.23512.16/

.NET workloads installed:
 Workload version: 8.0.100-manifests.cbd66cf7
There are no installed workloads to display.

Host:
  Version:      8.0.0-rtm.23511.16
  Architecture: x64
  Commit:       256bf22a3d

.NET SDKs installed:
  8.0.100-rtm.23512.16 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-rtm.23512.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.23 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rtm.23511.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by WenJunJi01** [comment]
Debug log please refer to [Logs.zip](https://github.com/dotnet/runtime/files/12925886/Logs.zip)

**Comment by tommcdon** [comment]
I wasn't able to reproduce the issue on the latest daily release/8.0 build.  

Build used:
`sudo ./dotnet-install.sh --version 8.0.100-rtm.23517.9 --install-dir /usr/local/share/dotnet`

I should also point out there is a known issue related to ready-to-run binaries tracked on [Application crash while stepping into if 'justMyCode' is disabled · Issue #68018 · dotnet/runtime (github.com)](https://github.com/dotnet/runtime/issues/68018).  To workaround the bug, please try setting DOTNET_ReadyToRun=0 in the launch.json.

![image](https://github.com/dotnet/runtime/assets/12520929/86e87c7e-685a-456c-b652-accfd249469a)

**Comment by WenJunJi01** [comment]
@tommcdon I still reproduced this issue with the latest daily release/8.0 even setting DOTNET_ReadyToRun=0 in the launch.json.
SDK version: 8.0.100-rtm.23518.11(runtime-8.0.0-rtm.23517.16) 
VSCode version: 1.83.1
C# extenstion version: 2.7.25
![image](https://github.com/dotnet/runtime/assets/87680983/b892d629-1d9e-4386-a1f4-ec6522fe4c0b)
![image](https://github.com/dotnet/runtime/assets/87680983/1bcedb4f-6502-4b2e-aa45-455c7f50da6a)

**Comment by richaverma1** [comment]
@WenJunJi01 is this repro'ng on the coherent build of .NET 8 GA

**Comment by WenJunJi01** [comment]
@richaverma1 No, this issue is not repro on the coherent build of .NET 8 GA. 
We only met this problem which is by design. ->[Bug 1893711](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1893711): [Blue][NETSDKE2E] With .NET 8 RC2 and C# extention installed, "Cannot find or open the PDB file" pops up while debugging IL Symbols
