### ISSUE TITLE
Dividing by 0 does not throw an exception

### ISSUE THREAD

**Issue by CwjXFH** [dotnet/runtime#93587]
```C#
var val = Div(10, 0);
Console.WriteLine(val); // print int.MinValue
// Console.WriteLine(int.MinValue);

int Div(long left, long right)
{
    return (int)(left * 1.0 / right);
    // return (int)(left / right); will throw DivideByZeroException
}
```

.NET Version: 7
OS : Win 11

As the above sample shows, the **Div** method returns `-2147483648`  which is the int.MinValue value, is this a design intention or a bug?

Thanks!

**Comment by hez2010** [comment]
You are doing floating-point division operation, which doesn't apply to divide by zero exception by IEEE754.

**Comment by huoyaoyuan** [comment]
Dividing by zero in floating point results in NaN, and the default representation of NaN (-qNaN defined in IEEE754) converts to -Max of integer.
