### ISSUE TITLE
[wasm] WBT tests failing because of missing test app output

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#93583]
[Build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440172), and [log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-ff2f87fff88148febc/Workloads-Wasm.Build.Tests.WasmBuildAppTest/1/console.72391d22.log?helixlogtype=result):

```
    Wasm.Build.Tests.WasmBuildAppTest.PropertiesFromRuntimeConfigJson(buildArgs: BuildArgs { ProjectName = placeholder, Config = Release, AOT = False, ProjectFileContents = placeholder, ExtraBuildArgs =  }, host: Chrome, id: "4lpskvor_yvt") [FAIL]
      Assert.Contains() Failure
      Not found: test_runtimeconfig_json: 25
```
..
```
                 [wasm test-browser] info: Application arguments: --run runtime_config_Release_False.dll
                 [wasm test-browser] info: Silently starting separate runtime instance as another ES6 module to populate caches...
                 [wasm test-browser] info: MONO_WASM: forceDisposeProxies done: 0 imports, 0 exports, 0 GCHandles, 0 JSHandles.
                 [wasm test-browser] info: browser: [main] Console websocket connected.
                 [wasm test-browser] info: Initializing dotnet version 9.0.0-ci commit hash 45ed0ab41c138ad1683b333b5b937b8240f3e4d8
                 [wasm test-browser] info: test-main.js exiting runtime_config_Release_False.dll with result 42
                 [wasm test-browser] info: http://127.0.0.1:49387/_framework/dotnet.js 2:1372 Array(1)
                 [wasm test-browser] info: WASM EXIT 42
                 [wasm test-browser] dbug: Reached wasm exit
                 [wasm test-browser] info: Waiting to flush log messages with a timeout of 120 secs ..
                 [wasm test-browser] warn: Message processor is not running anymore.
                 [wasm test-browser] info: {"method":"console.info","payload":"WASM EXIT 42","arguments":[]}
                 [wasm test-browser] dbug: Reading console messages from websocket stopped
                 [wasm test-browser] dbug: Failed trying to read log messages via selenium: OpenQA.Selenium.WebDriverException: invalid session id
                 [wasm test-browser]          at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
                 [wasm test-browser]          at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
                 [wasm test-browser]          at OpenQA.Selenium.Remote.RemoteWebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
                 [wasm test-browser]          at OpenQA.Selenium.Remote.RemoteLogs.GetLog(String logKind)
                 [wasm test-browser]          at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmBrowserTestRunner.RunSeleniumLogMessagePump(IWebDriver driver, CancellationToken token) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs:line 214
                 [wasm test-browser] dbug: Saving diagnostics data to 'C:\helix\work\workitem\e\diagnostics.json'
```

Diff since the last good commit for rolling builds: 44a2b2d0...45ed0ab4 which includes https://github.com/dotnet/runtime/pull/93010 for which the PR had a similar failure but the PR was merged on red.

cc @pavelsavara 

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "Not found: test_runtimeconfig_json: 25|Not found: Hashed: |Not found: args#: 2|Not found: Could not create es-ES culture",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=440172
**Error message validated:** `Not found: test_runtimeconfig_json: 25|Not found: Hashed: |Not found: args#: 2|Not found: Could not create es-ES culture`
**Result validation: :x:** Known issue did not match with the provided build.
**Validation performed at:** 10/17/2023 1:25:04 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[441599](https://dev.azure.com/dnceng-public/public/_build/results?buildId=441599)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.MainWithArgsTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=441599&view=ms.vss-test-web.build-test-results-tab&runId=9843532&resultId=100147)||
|[441403](https://dev.azure.com/dnceng-public/public/_build/results?buildId=441403)|dotnet/runtime|[Workloads-Wasm.Build.Tests.MainWithArgsTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=441403&view=ms.vss-test-web.build-test-results-tab&runId=9842610&resultId=100146)|dotnet/runtime#93066|
|[441571](https://dev.azure.com/dnceng-public/public/_build/results?buildId=441571)|dotnet/runtime|[Workloads-Wasm.Build.Tests.MainWithArgsTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=441571&view=ms.vss-test-web.build-test-results-tab&runId=9842352&resultId=100146)|dotnet/runtime#93571|
|[441216](https://dev.azure.com/dnceng-public/public/_build/results?buildId=441216)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.WasmBuildAppTest.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=441216&view=ms.vss-test-web.build-test-results-tab&runId=9832028&resultId=100146)|dotnet/runtime#93606|
|[441152](https://dev.azure.com/dnceng-public/public/_build/results?buildId=441152)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.MainWithArgsTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=441152&view=ms.vss-test-web.build-test-results-tab&runId=9830624&resultId=100146)|dotnet/runtime#93558|
|[440565](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440565)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.MainWithArgsTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440565&view=ms.vss-test-web.build-test-results-tab&runId=9814754&resultId=100146)|dotnet/runtime#93182|
|[440539](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440539)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.WasmBuildAppTest.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440539&view=ms.vss-test-web.build-test-results-tab&runId=9813324&resultId=100147)|dotnet/runtime#93571|
|[440404](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440404)|dotnet/runtime|[Workloads-Wasm.Build.Tests.NativeLibraryTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440404&view=ms.vss-test-web.build-test-results-tab&runId=9809708&resultId=100147)|dotnet/runtime#92095|
|[439521](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439521)|dotnet/runtime|[Workloads-Wasm.Build.Tests.MainWithArgsTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439521&view=ms.vss-test-web.build-test-results-tab&runId=9788806&resultId=100147)|dotnet/runtime#93280|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|7|9|9|

**Comment by radical** [comment]
Failing tests:
https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-ff2f87fff88148febc/Workloads-Wasm.Build.Tests.WasmBuildAppTest/1/console.72391d22.log?helixlogtype=result
https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-ff2f87fff88148febc/Workloads-Wasm.Build.Tests.NativeLibraryTests/1/console.b119e0be.log?helixlogtype=result
https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-444fb3ba110e4eb2ae/Workloads-NoWebcil-Wasm.Build.Tests.MainWithArgsTests/1/console.94d3fa1c.log?helixlogtype=result
https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-75da9917927147d090/Workloads-NoWebcil-Wasm.Build.Tests.InvariantGlobalizationTests/1/console.d6422600.log?helixlogtype=result

**Comment by pavelsavara** [comment]
I see I made bad merge in https://github.com/dotnet/runtime/pull/93010 and it contains the logging changes which I believed I moved to https://github.com/dotnet/runtime/pull/93472 🤦‍♂️

**Comment by radical** [comment]
This is fixed by https://github.com/dotnet/runtime/pull/93618 .
