### ISSUE TITLE
[API Proposal]: Make LocalBuilder abstract

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#93580]
### Background and motivation

For adding [`AssemblyBuilder.Save()` equivalent in .NET Core](https://github.com/dotnet/runtime/issues/62956) we have [abstracted](https://github.com/dotnet/runtime/issues/78542) most of the System.Refleciton.Emit types and adding new implementations for them. This abstraction did not cover `LocalBuilder` type and its constructor is internal, so I could not create an instance from the new `ILGenerator` implementation. We need a same treatment for this type: to unseal the `LocalBuilder` class and make it abstract, make the `internal` constructor `protected`, also add a public getter that exposes the `method` the local belongs.

Related to https://github.com/dotnet/runtime/issues/92975

### API Proposal

```diff
namespace System.Reflection.Emit;

-public sealed class LocalBuilder : System.Reflection.LocalVariableInfo
+public abstract class LocalBuilder : System.Reflection.LocalVariableInfo
{
-   internal LocalBuilder(int localIndex, Type localType, MethodInfo method, bool isPinned) { }
+   protected LocalBuilder() { }
+   public abstract MethodInfo LocalMethod { get; }
}
```
Abstract `LocalMethod` property can be used for validation. Parent `LocalVariableInfo` has public virtual properties like `LocalType`, `LocalIndex`, `IsPinned`.

**Comment by buyaa-n** [comment]
Intergrated with https://github.com/dotnet/runtime/issues/93497

**Comment by lambdageek** [comment]
> `public abstract MethodInfo LocalMethod { get; }`

I think this needs to be `MethodBase`, not `MethodInfo`.  Constructors can have locals, too
