### ISSUE TITLE
Cannot reestablish communication with serial device through SerialPort

### ISSUE THREAD

**Issue by cholas** [dotnet/runtime#93599]
### Description

I'm working with a device that replies either '{STX}ACK\x0d' or '{STX}NAK\x0d'. 

After I close my app (or after it crashes) I cannot receive any data from the usb device. 

I've checked the SerialPort object when it works and when it does not work but its properties do not change.

### Reproduction Steps

`static void Main(string[] args)
{
    System.IO.Ports.SerialPort p = new System.IO.Ports.SerialPort("COM3", 115200, System.IO.Ports.Parity.None, 8, System.IO.Ports.StopBits.One);
    p.Open();

    /
    string command = "command";
    string response = "";
    int n = 0;
    
    while (true && n < 5)
    {
       
        p.Write(command);
        Thread.Sleep(500);
        response = p.ReadExisting();
        Console.WriteLine(response);
        response = "";
        n++;
    }`
    
    After the first execution of this code i cannot launch it a second time and have it working. 

### Expected behavior

I'm expecting to keep receiving data even on different executions in a row. 

### Actual behavior

The overmentioned code works only once, after that I've found some workarounds to make it work again.

### Known Workarounds

The only two workarounds are:

1. Send some data to the device through a 3rd party software (could be a simply send in a python shell, a c# console program written with a  different c# library like SerialPortStream). Using a 3rd party software i can write/read data without any limitations. After that the overmentioned code start working again, but only once.

2. Unplug/plug the usb cable. After that the overmentioned code start working again, but only once.

**Comment by wfurt** [comment]
Is it failing to open the port again? Or write or read? There is not enough information for triage @cholas.
