### ISSUE TITLE
AOT Compilation Error (.NET 8.0)

### ISSUE THREAD

**Issue by dadavadd** [dotnet/runtime#93605]
### Description

I'm trying to compile an exe with registration through keyauth.cc. Everything works fine with regular compilation, but when I use Native AOT compilation, I get several warnings in the console. After that, when I run the compiled AOT exe and click "Login", a console window pops up saying "You must run the function KeyAuthApp.init(); first", and it closes after 5 seconds. (translate with Google Translator).

Warnings:
![image](https://github.com/dotnet/runtime/assets/111659964/967dd181-4db8-4545-956c-3902153aa430)

Line 1117:
![image](https://github.com/dotnet/runtime/assets/111659964/def97375-8f83-4e65-8ffa-b31c961a0c87)

Line 1129:
![image](https://github.com/dotnet/runtime/assets/111659964/56615090-4f2a-4e7b-82b8-30fc8ea00445)

KeyAuth.cs link:
https://github.com/KeyAuth/KeyAuth-CSHARP-Example/blob/main/Console/KeyAuth.cs

Error when clicking "Login" (Function KeyAuthApp.init(); already written into the code before compilation. But as I said earlier, with regular compilation (not AOT), the program works correctly.):
![image](https://github.com/dotnet/runtime/assets/111659964/f0bc89c7-c3f8-4c25-918f-332eaed9518c)

I'm pretty sure the issue is likely due to these warnings. I'd appreciate any help. Thanks.

### Reproduction Steps

I tried to properly remove this segment of code, but it didn't work out.

### Expected behavior

After clicking the "Login" button, the program should switch to the next Imgui frame (I'm using Imgui.NET).

### Actual behavior

Output to the console: "You must run the function KeyAuthApp.init(); first" when clicking "Login". Moreover, if an incorrect login and password are entered, the program simply closes without any messages. The console message is displayed specifically when the entered login and password are present in the KeyAuth database.

**Comment by MichalStrehovsky** [comment]
`DataContractJsonSerializer` is not compatible with trimming and the result app can be broken in all sorts of ways. It probably can be made to work, but you'll never be sure if there's edge cases when it won't.

I recommend switching to [System.Text.Json with source generation](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation?pivots=dotnet-8-0) that is compatible with trimming and will not generate warnings.
