### ISSUE TITLE
[8.0] [wasm] Test failure in System.Numerics.Tensors.Tests.TensorPrimitivesTests.MaxMagnitude(tensorLength: 53)

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#93620]
### Error Blob

```json
{
  "ErrorMessage": "System.Numerics.Tensors.Tests.TensorPrimitivesTests.MaxMagnitude",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": true
}
```

### Reproduction Steps

- Affected 8.0 PR: https://github.com/dotnet/runtime/pull/93355
- Queue: `browser-wasm linux Release LibraryTests`
- Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=441315&view=logs&j=d4e38924-13a0-58bd-9074-6a4810543e7c&t=7a581d54-fbdb-5b9d-4377-cc346f489112&l=79
- Log file: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-pull-93355-merge-a0b48bf28d5545f6ab/normal-System.Numerics.Tensors.Tests/1/console.a884f849.log?helixlogtype=result
- Output:
```
info: Incoming arguments: --run WasmTestRunner.dll System.Numerics.Tensors.Tests.dll -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
info: Application arguments: --run WasmTestRunner.dll System.Numerics.Tensors.Tests.dll -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
info: console.info: Initializing dotnet version 8.0.0-ci commit hash 6bc727c9d89abbe51b90e901c77699a44cb76fab
info: Discovering: System.Numerics.Tensors.Tests.dll (method display = ClassAndMethod, method display options = None)
info: Discovered:  System.Numerics.Tensors.Tests.dll (found 138 of 138 test cases)
info: Using random seed for test cases: 1089632055
info: Using random seed for collections: 1089632055
info: Starting:    System.Numerics.Tensors.Tests.dll
fail: [FAIL] System.Numerics.Tensors.Tests.TensorPrimitivesTests.MaxMagnitude(tensorLength: 53)
info: Assert.Equal() Failure
info: Expected: -0.9888806939125061
info: Actual:   0.9888806939125061
info:    at System.Numerics.Tensors.Tests.TensorPrimitivesTests.MaxMagnitude(Int32 tensorLength)
info:    at System.Object.InvokeStub_TensorPrimitivesTests.MaxMagnitude(Object , Span`1 )
info:    at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
info: Finished:    System.Numerics.Tensors.Tests.dll
info: 
info: === TEST EXECUTION SUMMARY ===
info: Total: 13011, Errors: 0, Failed: 1, Skipped: 0, Time: 12.851104s
```

 ### Known issue validation
**Build: :mag_right:** 
**Result validation: :x:**  There was a problem creating a known issue. Check the exception message and proceed accordingly: `Invalid pattern '[FAIL] System.Numerics.Tensors.Tests.TensorPrimitivesTests.MaxMagnitude(tensorLength' at offset 84. Not enough )'s.`
**Validation performed at:** 10/18/2023 1:51:34 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

**Comment by ericstj** [comment]
@carlossanlop -- looks like your regex didn't match.   I've updated this to see if it's still happening.

**Comment by lewing** [comment]
the builds are gone and there are no recent hits, I'm going to close this but please reopen if it is seen again
