### ISSUE TITLE
Blazor Init Log Messages on Safari

### ISSUE THREAD

**Issue by rudiv** [dotnet/runtime#93622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm not sure that this can be considered a "bug" in Blazor (most likely Safari), but it seems primarily like strange behaviour.

When using Safari, there are no initialisation messages logged to the console.

The `assetsCache.ts` code uses [console.groupCollapsed](https://developer.mozilla.org/en-US/docs/Web/API/Console/groupCollapsed) which is supported in Safari, so it's almost like some form of environment detection is failing, yet it's only using `typeof (window) === "object"` so I'm not sure how that's possible.

### Expected Behavior

A message, similar to the following, printed to the browser console.

```
assetsCache.ts:30
dotnet Loaded 11.21 MB resources
This application was built with linking (tree shaking) disabled.
Published applications will be significantly smaller if you install wasm-tools workload. See also https://aka.ms/dotnet-wasm-features
````

### Steps To Reproduce

Open any Blazor WASM app in Safari.

### .NET Version

8.0.100-rc.2.23502.2

**Comment by maraf** [comment]
- The `loaderHelpers.debug` is `0` in safari, althoutgh with the build of app, it's `-1` in Edge
- The `loaderHelpers.debug !==0 ` guads logging of download stats
