### ISSUE TITLE
.NET Runtime Support for Swift Interop

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#93631]
# Background

The [Swift](https://developer.apple.com/swift/) programming language is developed primarily by Apple for use in their product lines. It is a successor to the previous official language for these platforms, Objective-C. C# has had limited Objective-C interop support for quite a while and it powers frameworks like MAUI and Xamarin Forms that run on Apple devices.

Swift is now becoming the dominant language on Apple devices and eclipsing Objective-C. Many important libraries are now Swift-first or Swift-only. Objective-C binding is also becoming more difficult for these libraries. To continue to interoperate with external libraries and frameworks, C# needs to be able to interoperate directly with Swift, without going through an intermediate language.

## Goals

In short, we should completely eliminate the required C/assembly sandwich that's currently required to call Swift from C# code, and potentially vice versa. In particular, neither C# nor Swift users should have to deal with lower-level system state, like registers or stack state, to call Swift from C#.

## Non-goals

C# and Swift are different languages with different language semantics. It is not a goal to map every construct from one language to the other. However, there are some terms in both languages that are sufficiently similar that they can be mapped to an identical semantic term in the other language. Interop should be seen as a Venn diagram where each language forms its own circle, and interop is in the (much smaller) space of equivalent terms that are shared between them.

## Work

The exact scope of work is bind the CryptoKit library with the projection tooling and runtime support. We'll need the calling convention work (described above) in the runtime. Above the OS level we'll need a code generation strategy to generate C# bindings for Swift. An existing project to do that exists as [Binding Tools for Swift](https://github.com/xamarin/binding-tools-for-swift). This work also needs further definition, but is out of scope of the .NET runtime itself.

For the runtime we can focus on system-level interfacing. For that we will need:

- [x] Calling convention design
  - [x] [Spec](https://github.com/dotnet/designs/blob/main/proposed/swift-interop.md)
  - [x] https://github.com/dotnet/runtime/pull/95065
  - [x] https://github.com/dotnet/runtime/issues/100543
- [x] Call basic functions
  - [x] https://github.com/dotnet/runtime/pull/96707
  - [x] Implement CoreCLR support for Swift calling convention
    - [x] https://github.com/dotnet/runtime/pull/98586
    - [x] https://github.com/dotnet/runtime/pull/99132
    - [ ] Fix/enable SwiftInvalidCallConv tests for CoreCLR 
  - [x] Implement Mono support for Swift calling convention
    - [x] https://github.com/dotnet/runtime/issues/94081
    - [x] https://github.com/dotnet/runtime/pull/98429
    - [x] https://github.com/dotnet/runtime/pull/94764
  - [x] Implement UnmanagedCallersOnly support for Swift calling convention
    - [X] https://github.com/dotnet/runtime/pull/100018
    - [x] https://github.com/dotnet/runtime/issues/100010
  - [x] Frozen structs marshalling
    - [X] CoreCLR VM Support
      - [X] https://github.com/dotnet/runtime/pull/99438
    - [X] NativeAOT/Crossgen2 type system support
      - [X] https://github.com/dotnet/runtime/pull/98831
      - [X] https://github.com/dotnet/runtime/pull/99337
    - [x] RyuJIT support
      - [X] https://github.com/dotnet/runtime/pull/99294
      - [X] https://github.com/dotnet/runtime/pull/99704
      - [X] https://github.com/dotnet/runtime/pull/100018
      - [X] https://github.com/dotnet/runtime/pull/100091
      - [X] https://github.com/dotnet/runtime/pull/100344
      - [x] https://github.com/dotnet/runtime/pull/103576
      - [x] https://github.com/dotnet/runtime/pull/103570
    - [x] MonoVM support
      - [x] https://github.com/dotnet/runtime/pull/99439
      - [x] https://github.com/dotnet/runtime/issues/102077
      - [x] https://github.com/dotnet/runtime/pull/104171
      - [x] https://github.com/dotnet/runtime/pull/104111
- [ ] [Memory management](https://github.com/dotnet/designs/pull/312)
- [ ] Unit tests in .NET runtime
  - [x] https://github.com/dotnet/runtime/issues/102079
  - [x] https://github.com/dotnet/runtime/issues/102082
  - [ ] Add stress tests with generic structs
  - [ ] Add tests for structs with InlineArray attribute

**Comment by kotlarmilos** [comment]
@agocke Here is a list of libraries/frameworks people have asked for: https://github.com/xamarin/xamarin-macios/issues?q=is%3Aopen+is%3Aissue+label%3Arequires-swift. Most of them are Swift-only and could be used as definition of done (DoD) along with the CryptoKit.

**Comment by ShikiSuen** [comment]
Is this repo aim to allow Swift (on Windows / Linux / macOS) to directly use dotNet 9 APIs without RemObject toolchains?

**Comment by filipnavara** [comment]
> Is this PR aim to allow Swift (on Windows / Linux / macOS) to directly use dotNet 9 APIs without RemObject toolchains?

No, this is mapping in the opposite direction, allowing .NET 9+ to call Swift APIs.

**Comment by jkoritzinsky** [comment]
.NET Runtime support for Swift is feature complete for .NET 9. Any additional runtime work will be in .NET 10.

**Comment by jkoritzinsky** [comment]
For .NET 9 we focused on Apple platforms. In the future we may look at supporting Swift interop on more platforms.

**Comment by Felix-Dev** [comment]
> .NET Runtime support for Swift is feature complete for .NET 9. Any additional runtime work will be in .NET 10.

Appreciate all the hard work you guys have been dping over the past months! Looking forward to testing out Swift interop and future improvements by the team.
