### ISSUE TITLE
[API Proposal]:  Idea for a convenient Replace

### ISSUE THREAD

**Issue by Zombach** [dotnet/runtime#93637]
### Background and motivation

Idea for a convenient Replace. I understand that this is just an concept. And my implementation leaves much to be desired. But I hope it will find a positive solution and will be finalized by specialists. Improve both compactness and code readability.
Finally, it will be possible to change the character by index.

This is always sufficient, but the question here is about the convenience of usage, writing speed, readability, and compactness. If this functionality were added to the String class, it would enable more convenient usage of Replace. For instance, there's a similar implementation using Range for Substring. Why not introduce syntactic sugar for Replace` as well?

```
` string text = "Message";
int l = text.Length - 1;

text = text.Substring(2);
text = text[2..];
text = text.Substring(1, 3);
text = text[1..3];
text = text.Substring(0, l);
text = text[..l]; // || text[..^1]

text = text.Replace('e', 'e');
text = text['e', 'e'] //Example
text = text.Replace("Mes", string.Empty);
text = text["Mes", string.Empty] //Example
text = text.Replace("Mes", string.Empty, StringComparison.OrdinalIgnoreCase);
text = text["Mes", string.Empty, StringComparison.OrdinalIgnoreCase] //Example
text = text.Replace("Mes", string.Empty, true, CultureInfo.CurrentCulture);
text = text["Mes", string.Empty, true, CultureInfo.CurrentCulture] //Example
//Does not exist
text = text[1, 'e'] //Example
```

### API Proposal
```
using System;

public partial class String
{
    #region Base for String.Manipulation.cs
    internal const int StackallocCharBufferSizeLimit = 256;
    private readonly int _stringLength;
    private readonly unsafe char* _firstChar;
    #endregion

    public unsafe String(string text)
    {
        _stringLength = text.Length;
        fixed (char* charPtr = text)
        {
            _firstChar = charPtr;
        }
    }

    /// <summary>
    /// Convenient replace call using an indexer
    /// </summary>
    /// <param name="oldValue">The value to be replaced</param>
    /// <param name="newValue">The new value</param>
    /// <param name="culture">The culture</param>
    /// <param name="options">The options</param>
    /// <returns>value string</returns>
    public unsafe string? this[string oldValue, string newValue, CultureInfo? culture = default, CompareOptions options = CompareOptions.Ordinal]
    {
        get
        {
            if (_stringLength is 0) { return string.Empty; }
            ReadOnlySpan<char> searchSpace = new(_firstChar, _stringLength);
            return ReplaceCore(searchSpace, oldValue.AsSpan(), newValue.AsSpan(), culture?.CompareInfo ?? CultureInfo.CurrentCulture.CompareInfo, options);
        }
    }

    /// <summary>
    /// Analogous call for character replacement by char.
    /// </summary>
    /// <param name="oldChar"></param>
    /// <param name="newChar"></param>
    /// <returns></returns>
    /// 
    public string this[char oldChar, char newChar] => string.Empty;
    /// <summary>
    /// Analogous call for character replacement by index
    /// </summary>
    /// <param name="index"></param>
    /// <param name="newChar"></param>
    /// <returns></returns>
    public string this[int index, char newChar] => string.Empty;

    #region Base for String.Manipulation.cs
    private static string? ReplaceCore(ReadOnlySpan<char> searchSpace, ReadOnlySpan<char> oldValue, ReadOnlySpan<char> newValue, CompareInfo compareInfo, CompareOptions options)
    {
        Debug.Assert(!oldValue.IsEmpty);
        Debug.Assert(compareInfo != null);

        var result = new ValueStringBuilder(stackalloc char[StackallocCharBufferSizeLimit]);
        result.EnsureCapacity(searchSpace.Length);

        bool hasDoneAnyReplacements = false;

        while (true)
        {
            int index = compareInfo.IndexOf(searchSpace, oldValue, options, out int matchLength);

            // There's the possibility that 'oldValue' has zero collation weight (empty string equivalent).
            // If this is the case, we behave as if there are no more substitutions to be made.

            if (index < 0 || matchLength == 0)
            {
                break;
            }

            // append the unmodified portion of search space
            result.Append(searchSpace.Slice(0, index));

            // append the replacement
            result.Append(newValue);

            searchSpace = searchSpace.Slice(index + matchLength);
            hasDoneAnyReplacements = true;
        }

        // Didn't find 'oldValue' in the remaining search space, or the match
        // consisted only of zero collation weight characters. As an optimization,
        // if we have not yet performed any replacements, we'll save the
        // allocation.

        if (!hasDoneAnyReplacements)
        {
            result.Dispose();
            return null;
        }

        // Append what remains of the search space, then allocate the new string.

        result.Append(searchSpace);
        return result.ToString();
    }
    #endregion
}

```
### API Usage
//Replace by string
string text = "Necsage";
string newLine = text["Nec", "Mes"];
result = "Message"

//Replace by char
string text = "Meccage";
string newLine = text['c', 's'];
result = "Message"

//Replace by index
string text = "Mescage";
string newLine = text[3, 's'];
result = "Message"

### Alternative Designs
ReplaceWrapper
![изображение_2023-10-18_142044241](https://github.com/dotnet/runtime/assets/52016832/431fa8c5-8771-49e8-bfc4-abb0f9e3d471)

 or Move it to extensions System.String; But I think that this should be added inside the string class System.String

### Risks

Improvement needed. Since my skills are not enough to write at the same level as System.String.

**Comment by Clockwork-Muse** [comment]
> But I think that this should be added inside the string class System.String

There already exists a [`Replace(char, char)` method](https://learn.microsoft.com/en-us/dotnet/api/system.string.replace?view=net-7.0#system-string-replace(system-char-system-char))

For some of the more involved per-instace replacements, there's the various [`Replace` methods on `StringBuilder`](https://learn.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.replace?view=net-7.0#system-text-stringbuilder-replace(system-char-system-char)).

Is there something about the existing implementations that isn't sufficient for your use case?

**Comment by Zombach** [comment]
This is always sufficient, but the question here is about the convenience of usage, writing speed, readability, and compactness. If this functionality were added to the String class, it would enable more convenient usage of Replace. For instance, there's a similar implementation using Range for Substring. Why not introduce syntactic sugar for Replace` as well?

` string text = "Message";
 int l = text.Length - 1;

 text = text.Substring(2);
 text = text[2..];
 text = text.Substring(1, 3);
 text = text[1..3];
 text = text.Substring(0, l);
 text = text[..l]; // || text[..^1]

 text = text.Replace('e', 'e');
 text = text['e', 'e']  //Example
 text = text.Replace("Mes", string.Empty);
 text = text["Mes", string.Empty]   //Example
 text = text.Replace("Mes", string.Empty, StringComparison.OrdinalIgnoreCase);
 text = text["Mes", string.Empty, StringComparison.OrdinalIgnoreCase]  //Example
 text = text.Replace("Mes", string.Empty, true, CultureInfo.CurrentCulture);
 text = text["Mes", string.Empty, true, CultureInfo.CurrentCulture]  //Example
 //Does not exist
 text = text[1, 'e'] //Example

**Comment by Zombach** [comment]
> > But I think that this should be added inside the string class System.String
> 
> There already exists a [`Replace(char, char)` method](https://learn.microsoft.com/en-us/dotnet/api/system.string.replace?view=net-7.0#system-string-replace(system-char-system-char))
> 
> For some of the more involved per-instace replacements, there's the various [`Replace` methods on `StringBuilder`](https://learn.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.replace?view=net-7.0#system-text-stringbuilder-replace(system-char-system-char)).
> 
> Is there something about the existing implementations that isn't sufficient for your use case?

This is always sufficient, but the question here is about the convenience of usage, writing speed, readability, and compactness. If this functionality were added to the String class, it would enable more convenient usage of Replace. For instance, there's a similar implementation using Range for Substring. Why not introduce syntactic sugar for Replace` as well?

` string text = "Message";
 int l = text.Length - 1;

 text = text.Substring(2);
 text = text[2..];
 text = text.Substring(1, 3);
 text = text[1..3];
 text = text.Substring(0, l);
 text = text[..l]; // || text[..^1]

 text = text.Replace('e', 'e');
 text = text['e', 'e']  //Example
 text = text.Replace("Mes", string.Empty);
 text = text["Mes", string.Empty]   //Example
 text = text.Replace("Mes", string.Empty, StringComparison.OrdinalIgnoreCase);
 text = text["Mes", string.Empty, StringComparison.OrdinalIgnoreCase]  //Example
 text = text.Replace("Mes", string.Empty, true, CultureInfo.CurrentCulture);
 text = text["Mes", string.Empty, true, CultureInfo.CurrentCulture]  //Example
 //Does not exist
 text = text[1, 'e'] //Example

**Comment by Clockwork-Muse** [comment]
> `if(isSet) { _value = chars; }`

Actually, I didn't catch this before... Are you trying to do an in-place modification of the string?  That's not happening, given strings are immutable.

**Comment by Zombach** [comment]
I am aware of that, and I have no intention of altering the string. My primary goal is to introduce syntactic sugar for a more convenient use of Replace, as well as to enhance code readability.

> > `if(isSet) { _value = chars; }`
> 
> Actually, I didn't catch this before... Are you trying to do an in-place modification of the string? That's not happening, given strings are immutable.

**Comment by MihaZupan** [comment]
> readability

> `text.Replace('e', 'e')` => `text['e', 'e']`
> `text["Mes", string.Empty]`

IMO this hurts readability. Calling `Replace` is very clear in what it's doing. The alternative isn't.
If I saw that, my initial guess would be that this is doing something like a `SubstringBetween(a, b)`, not a replace (since `text[a..b]` gets a substring of the range).

**Comment by Zombach** [comment]
> > readability
> 
> > `text.Replace('e', 'e')` => `text['e', 'e']`
> > `text["Mes", string.Empty]`
> 
> IMO this hurts readability. Calling `Replace` is very clear in what it's doing. The alternative isn't. If I saw that, my initial guess would be that this is doing something like a `SubstringBetween(a, b)`, not a replace (since `text[a..b]` gets a substring of the range).

Well, Range is a relatively new addition, and it wasn't always available. These are all recent innovations that weren't present before. Just like the recent addition of taking a Range from a collection:

```
int[] array = {1, 2, 3, 4};
IEnumerable<int> collection = array[..];
```

Also, the new primary constructor:
`public class MyClass(int x, string line) {}`

These features are very convenient, and you quickly get used to them. However, initially, it might leave you with mixed feelings.
