### ISSUE TITLE
[8.0] Windows x64 NativeAOT PNSE: Arrays with non-zero lower bounds are not supported

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#93632]
### Error Blob

```json
{
  "ErrorMessage": "System.PlatformNotSupportedException: Arrays with non-zero lower bounds are not supported.",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": true
}
```

### Reproduction Steps

- Found in an unrelated 8.0 PR (mono): https://github.com/dotnet/runtime/pull/93617
- Queue: `windows-x64 Checked NativeAOT`
- Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=441408&view=logs&j=ea7d6d51-d18d-5306-47bd-e3b7db04467e&t=64748b58-8f78-5277-67c1-1790606dd9c0&l=29
- Log file: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-pull-93617-merge-65dd3410cb96491db2/Loader.classloader/1/console.a10ce94d.log?helixlogtype=result
- Output:
```
    Loader\classloader\regressions\GitHub_93597\GitHub_93597\GitHub_93597.cmd [FAIL]
      Unhandled Exception: System.PlatformNotSupportedException: Arrays with non-zero lower bounds are not supported.
         at System.Array.InternalCreate(RuntimeType, Int32, Int32*, Int32*) + 0x173
         at System.Array.CreateInstance(Type, Int32[], Int32[]) + 0xb8
         at ReproGH93597.NonZeroLowerBoundArray(Array szArrayContents, Int32 lowerBound) + 0x6a
         at ReproGH93597.Main() + 0x36
         at GitHub_93597!<BaseAddress>+0x17b288
      
      Return code:      1
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=441408
**Error message validated:** `System.PlatformNotSupportedException: Arrays with non-zero lower bounds are not supported.`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 10/17/2023 9:57:53 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[441408](https://dev.azure.com/dnceng-public/public/_build/results?buildId=441408)|dotnet/runtime|[Loader\\classloader\\regressions\\GitHub_93597\\GitHub_93597\\GitHub_93597.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=441408&view=ms.vss-test-web.build-test-results-tab&runId=9839222&resultId=100206)|dotnet/runtime#93617|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|1|1|

**Comment by MichalStrehovsky** [comment]
We should not merge the PR that introduces the test without first disabling the test on native AOT. We don't support non-zero lower bounds since .NET Native days because no customer used them.
