### ISSUE TITLE
Parallel.ForAsync memory leak when used with a CancellationToken

### ISSUE THREAD

**Issue by antoniofreire** [dotnet/runtime#93664]
### Description

When calling Parallel.ForAsync overload with cancellation support in a long running loop, the memory usage grows indefinitely.

### Reproduction Steps

```
using CancellationTokenSource cts = new();

var cancellationToken = cts.Token;

while (true)
{
    await Parallel.ForAsync(0, 10, cancellationToken,  (_, _) => ValueTask.CompletedTask);
}
```

### Expected behavior

No memory leak

### Actual behavior

Memory usage grows indefinitely, with lots of objects going to gen2.

### Known Workarounds

Don't pass a CancellationToken or periodically cancels it

### Configuration

.NET 8.0.100-rc.2.23479.10, Windows x64

**Comment by MihaZupan** [comment]
Looks like the `ForEachState<T>` implementation here
https://github.com/dotnet/runtime/blob/93fc05c01c985c787dc1fea9a1a756935612a84b/src/libraries/System.Threading.Tasks.Parallel/src/System/Threading/Tasks/Parallel.ForEachAsync.cs#L748C30-L748C42
is missing a `DisposeAsync` implementation that would dispose the `_registration` CTR.

**Comment by stephentoub** [comment]
Thanks for reporting the issue. It's been fixed both in main and for .NET 8.
