### ISSUE TITLE
crossgen2 error due to .NET 8 dependency in source build

### ISSUE THREAD

**Issue by mthalman** [dotnet/runtime#93666]
See failure in https://github.com/dotnet/installer/pull/17524

> /vmr/src/runtime/artifacts/source-build/self/src/dotnet.sh /vmr/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/linux.x64.Release/x64/crossgen2/tools/crossgen2.dll -o:/vmr/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/linux.x64.Release/System.Private.CoreLib.dll -r:/vmr/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/linux.x64.Release/IL/*.dll --targetarch:x64 --targetos:linux -O /vmr/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/linux.x64.Release/IL/System.Private.CoreLib.dll --perfmap-format-version:1 --perfmap --perfmap-path:/vmr/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/linux.x64.Release/
      You must install or update .NET to run this application.
      App: /vmr/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/linux.x64.Release/x64/crossgen2/tools/crossgen2.dll
      Architecture: x64
      Framework: 'Microsoft.NETCore.App', version '8.0.0-preview.7.23375.6' (x64)
      .NET location: /vmr/.dotnet/ 
      The following frameworks were found:
        9.0.0-alpha.1.23470.17 at [/vmr/.dotnet/shared/Microsoft.NETCore.App]

The SDK being used is 9.0 but crossgen has a dependency on 8.0 runtime which is not installed.

Related: https://github.com/dotnet/runtime/pull/93450

/cc @ViktorHofer

**Comment by steveisok** [comment]
@mthalman since this appears to no longer be an issue, I'm going to close. If that's incorrect, please reopen and let me know what you're still seeing.
