### ISSUE TITLE
ConfigurationBinder.Get<T> incorrect nullability of return value

### ISSUE THREAD

**Issue by davidmilligan** [dotnet/runtime#93668]
### Description

The implementation of `Microsoft.Extensions.ConfigurationConfigurationBinder.Get<T>` will return null if T is a reference type. This is quite obvious from inspecting the source of this method, but also it is clearly stated in the documentation for the return value:

> The new instance of T if successful, default(T) otherwise.

However, the signature of the method does not indicate to the compiler's nullability analysis that this is case. Leading to the situation of using this method from a project with nullable reference types turned on, but not getting a warning when attempting to us the return value from this method without first checking for null.

This has bitten me on more than one occasion, and typically in a really bad spot (this method is commonly used in asp.net core app startup to load configuration), with the app crashing on startup with a `NullReferenceException` when those had basically become a thing of the past thanks to recent C# nullable analysis features.

### Reproduction Steps

assuming a regular class called `MySettingsType` with a property called `MyConfigProperty`, here's an example asp.net core `Startup` class
``` C#
#nullable enable

public IConfiguration Configuration { get; }

public void ConfigureServices(IServiceCollection services)
{
    var settings = Configuration.GetSection("MySettings").Get<MySettingsType>().MyConfigProperty; // no nullable warning on this line
    // ...
}
```

### Expected behavior

a compiler warning on the line with the comment `// no nullable warning on this line`

### Actual behavior

no compiler warning on the line with the comment `// no nullable warning on this line`

### Configuration

net6.0

**Comment by tarekgh** [comment]
This is fixed in .NET 7.0 https://github.com/dotnet/runtime/pull/57418.
