### ISSUE TITLE
Trying to save application settings crashes the application.

### ISSUE THREAD

**Issue by Jodsderechte** [dotnet/runtime#93671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When trying to save a user value the application crashes.

### Expected Behavior

it saves

### Steps To Reproduce

```csharp
 Console.WriteLine($"[REQUEST] {DateTime.Now.ToString("HH:mm:ss")} Please input your bot token");
 string token = Console.ReadLine();
 DiscordQuery.Default.BotToken = token;
 DiscordQuery.Default.Save();
```

```
<?xml version='1.0' encoding='utf-8'?>
<SettingsFile xmlns="http://schemas.microsoft.com/VisualStudio/2004/01/settings" CurrentProfile="(Default)" GeneratedClassNamespace="DiscordQueryBot" GeneratedClassName="DiscordQuery">
  <Profiles />
  <Settings>
    <Setting Name="BotToken" Type="System.String" Scope="User">
      <Value Profile="(Default)" />
    </Setting>
  </Settings>
</SettingsFile>
```

### Exceptions (if any)

Unable to cast object of type 'System.Configuration.ConfigurationUserLevel' to type 'System.Configuration.ConfigurationFileMap

### .NET Version

7.0.402

### Anything else?

I found this issue https://github.com/dotnet/runtime/issues/25748 which seem to reference the same issue but that seems to have been fixed and merged long time ago so no idea what is the issue.

.NET SDK:
 Version:   7.0.402
 Commit:    791db8e2d8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.402\
 
 using Visual studio 2022 17.7.5
 
 asp.net core version 7.0.12
 
 
 Tried asking here: https://stackoverflow.com/questions/77303703/trying-to-save-application-settings-crashes-the-application-what-am-i-doing-wro

**Comment by buyaa-n** [comment]
> .NET SDK:
> Version: 7.0.402

@Jodsderechte I was not able to repro the issue, what version of `System.Configuration.ConfigurationManager` you are using? I suspect you are referencing an old one that doesn't have the fix done with https://github.com/dotnet/runtime/issues/25748, please try out with the version 7.0.0 or above https://www.nuget.org/packages/System.Configuration.ConfigurationManager/7.0.0

**Comment by Jodsderechte** [comment]
indeed it seems that there was an old version being referenced eventhough the package was installed / the application created after the fix went in. No idea how that happened thx for the help!
