### ISSUE TITLE
[wasm] dotnet.native.wasm was re-generated because the list of .o files in emcc-link.rsp is non-deterministic

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#93689]
dotnet.native.wasm was re-generated during incremental build, when it shouldn't. It was triggered because the list of .o files in emcc-link.rsp is non-deterministic.

Please re-enable corresponding tests upon fixing this.

**Comment by radical** [comment]
The issue was that `ILStrip`'s output assemblies were not in a deterministic order. They should be returned in the same order as the input. I have pushed fixes to the original PR - #90436 .
