### ISSUE TITLE
[wasm] The way of getting the path of `runtimeconfig.json` file is not always reliable

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#93692]
In wasm build process, the path of `runtimeconfig.json` file was generated based the location of the main app assembly. This would work with the assumption that `runtimeconfig.json` file lived in the same folder as the main app assembly file. This assumption was broken when enabling IL trim by default for wasm apps in my PR (https://github.com/dotnet/runtime/pull/90436). When the main app assembly file gets trimmed, the newly generated trimmed assembly lives in a separated directory than the `runtimeconfig.json` file. We need a more robust way of finding `runtimeconfig.json` file.

**Comment by radical** [comment]
The assumption is correct because runtimeconfig.json files are always next to the assembly. But in the ILStrip PR case, because the assembly when stripped moves to a different location, the old path is no longer reachable. Thus the old path needs to be retained, and used.
