### ISSUE TITLE
NotSupportedException trying to deserialize JSON in the "trim unused code" published app

### ISSUE THREAD

**Issue by highfield** [dotnet/runtime#93714]
### Description

The problem is in the deserialization of a JSON string. The code works fine either in development mode and when released. However, when **published,** if the flag "trim unused code" is checked, the deserialization raises an exception:
`Unhandled exception: System.NotSupportedException: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported.
`
If that flag is clear, the published app works fine.

### Reproduction Steps

Create an empty NET 7 console app.
Add a class module like this one:

    public sealed class MyClass
    {
        public int Foo { get; init; }
        public bool Baz { get; init; }
    }

Then add this code in the `Program` module:

```
using System.Text.Json;

string json = """{ "Foo": 123, "Baz": true }""";

var result = JsonSerializer.Deserialize<MyClass>(json);
if (result != null)
{
    Console.WriteLine(result.Foo);
    Console.WriteLine(result.Baz);
}
```
From within Visual Studio (both in Debug and Release mode) the app correctly writes:
```
123
true
```
Now, publish the app onto a folder. In my case, that is the profile:
```
<?xml version="1.0" encoding="utf-8"?>
<!--
https://go.microsoft.com/fwlink/?LinkID=208121.
-->
<Project>
  <PropertyGroup>
    <Configuration>Release</Configuration>
    <Platform>Any CPU</Platform>
    <PublishDir>bin\Release\net7.0\publish\win-x64\</PublishDir>
    <PublishProtocol>FileSystem</PublishProtocol>
    <_TargetId>Folder</_TargetId>
    <TargetFramework>net7.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishReadyToRun>false</PublishReadyToRun>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>
</Project>
```
Note the `PublishTrimmed` set to true.

### Expected behavior

The app should work correctly and writing:
```
123
true
```

### Actual behavior

The published app raises this exception:
```
Unhandled exception. System.NotSupportedException: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'ProvaConsoleApp.MyClass'. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
 ---> System.NotSupportedException: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'ProvaConsoleApp.MyClass'.
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(ReadStack& , Utf8JsonReader& , NotSupportedException)
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_DeserializeNoConstructor(Type, Utf8JsonReader&, ReadStack& )
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack& , T& )
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack& , T& )
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader&, JsonSerializerOptions, ReadStack& )
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1, JsonTypeInfo, Nullable`1 )
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1, JsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String , JsonSerializerOptions )
   at Program.<Main>$(String[]) in C:\Users\verna\source\repos\ConsoleApp4\ProvaConsoleApp\Program.cs:line 5
```

### Regression?

Did not try.

### Known Workarounds

The only workaround so far is clearing the "trim unused code" flag, but that leads to a huge resulting file.

### Configuration

```
2.2.204 [C:\Program Files\dotnet\sdk]
3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]
5.0.408 [C:\Program Files\dotnet\sdk]
7.0.402 [C:\Program Files\dotnet\sdk]
```

**Comment by startewho** [comment]
you can use the Json source generator to support the trimming
https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation?pivots=dotnet-8-0

**Comment by highfield** [comment]
@startewho I can, but I also wonder how many other things won't work without notice.
For instance, what if the deserialization is part of a 3rd-part library?

**Comment by eiriktsarpalis** [comment]
> but I also wonder how many other things won't work without notice.

Wasn't there a build warning about the JSON APIs when you tried to publish your trimmed application?

**Comment by highfield** [comment]
@eiriktsarpalis I don't see anything. Where are supposed to be?
Here is the output of the publication:
```
Build started...
1>------ Publish started: Project: ProvaConsoleApp, Configuration: Release Any CPU ------
1>Determining projects to restore...
1>All projects are up-to-date for restore.
1>ProvaConsoleApp -> C:\Users\verna\source\repos\ConsoleApp4\ProvaConsoleApp\bin\Release\net7.0\win-x64\ProvaConsoleApp.dll
1>ProvaConsoleApp -> C:\Users\verna\source\repos\ConsoleApp4\ProvaConsoleApp\bin\Release\net7.0\publish\win-x64\
========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
========== Build started at 14:49 and took 01,306 seconds ==========
========== Publish: 1 succeeded, 0 failed, 0 skipped ==========
========== Publish started at 14:49 and took 01,306 seconds ==========

```

**Comment by eiriktsarpalis** [comment]
This is what I'm seeing when trying to build with same code and configuration:
```console
C:\Users\eitsarpa\source\repos\ConsoleApp1\ConsoleApp1\Program.cs(5,14): warning IL2026: Using member 'System.Text.Json.JsonSerializer.Deserialize<TValue>(String, JsonSerializerOptions)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming applicat
ion code. JSON serialization and deserialization might require types that cannot be statically analyzed. Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved. [C:\Users\eitsarpa\source\repos\ConsoleApp1\Console
App1\ConsoleApp1.csproj]
```

**Comment by highfield** [comment]
@eiriktsarpalis nothing anywhere. Nor in the output pane (even rebuilding), nor as underlining in the code.
I'm stick to the official VS 17.7.5: no preview installed yet. It's matter of a couple of weeks, BTW!

**Comment by eiriktsarpalis** [comment]
I'm getting the same warning in 17.7.5 as well, so something else must be going on. Try looking for any warning suppressions that might have been made in your project, including suppressions in any `Directory.Build.props` files.

**Comment by highfield** [comment]
@eiriktsarpalis I've never touched thos things. I don't see any Directory.Build.props (neither in the parent folders), and here is how the project is set for the build:
![image](https://github.com/dotnet/runtime/assets/2127695/cc4c6dc3-ffc5-4e0e-8b6f-a6dcbb078dcf)

Anyway, in my case the behavior is pretty easy to reproduce: I found the problem in another problem, then I made up that small console app for this post.
I might setup a fresh install of VS in a VM, but that will take some time.

**Comment by eiriktsarpalis** [comment]
I'm not sure what the issue might be, but it seems related to local state or repo configuration. There's not much I can do without a repro. I would recommend trying a different machine and see if that helps.

**Comment by eiriktsarpalis** [comment]
Regarding the underlying issue, this is expected behaviour when using the reflection serializer in trimmed applications. Our recommendation in such cases is to switch to using the source generator.

**Comment by jkotas** [comment]
`<PublishTrimmed>true</PublishTrimmed>` does not change the binaries produced by `dotnet build` or binaries used by `F5` in Visual Studio. You still need run `dotnet publish` or Publish in Visual Studio to produce the trimmed binaries.

`<PublishTrimmed>true</PublishTrimmed>` enables trimming analyzer that runs during `dotnet build` or when you have your project open in Visual Studio, so you can see warnings related to trim unsafe code.
