### ISSUE TITLE
Dotnet run breaks when AssemblyName ends on Service

### ISSUE THREAD

**Issue by jorros** [dotnet/runtime#93716]
### Describe the bug
`dotnet run` breaks and immediately returns code 137 on a project that has got `AssemblyName` with a value ending with `.Service` configured.

This only started to happen once I upgraded my OS to macOS 14 (Sonoma)

Also this only happens with `dotnet run`. Building works fine and then using `dotnet path/to/Test.Service.dll` works fine.

### To Reproduce
Use the console template:
`dotnet new console`

Add to the csproj:
 `<AssemblyName>Test.Service</AssemblyName>`

Run `dotnet run`

This should immediately exit and the return code should be 137.

### Further technical details

.NET SDK:
 Version:   7.0.402
 Commit:    791db8e2d8

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.0
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.402/

Host:
  Version:      7.0.12
  Architecture: arm64
  Commit:       4a824ef37c

.NET SDKs installed:
  6.0.200 [/usr/local/share/dotnet/sdk]
  6.0.201 [/usr/local/share/dotnet/sdk]
  6.0.302 [/usr/local/share/dotnet/sdk]
  6.0.400 [/usr/local/share/dotnet/sdk]
  6.0.402 [/usr/local/share/dotnet/sdk]
  6.0.403 [/usr/local/share/dotnet/sdk]
  6.0.404 [/usr/local/share/dotnet/sdk]
  7.0.100 [/usr/local/share/dotnet/sdk]
  7.0.101 [/usr/local/share/dotnet/sdk]
  7.0.102 [/usr/local/share/dotnet/sdk]
  7.0.400 [/usr/local/share/dotnet/sdk]
  7.0.401 [/usr/local/share/dotnet/sdk]
  7.0.402 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.1.23421.29 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by elinor-fung** [comment]
Can you check the `Console` app for any additional information or crash report? If it says anything about code signing or being blocked for security, maybe try running the new [`syspolicy_check` tool](https://developer.apple.com/documentation/macos-release-notes/macos-14-release-notes#Trusted-Execution) on the `Test.Service` executable?

**Comment by jorros** [comment]
There is no additional info. When running the syspolicy_check I do get the following:
```
Codesign Error
    File: /Users/jorgrosenauer/Git/dotnet-bug/bin/Debug/net7.0/Test.Service
    Severity: Fatal
    Full Error: Gatekeeper rejected this file. If there isn't a more
        descriptive error elsewhere in this output, please file a Feedback
        through Feedback Assistant.app so we can continue to improve
        syspolicy_check. Please include the app bundle you are checking and a
        sysdiagnose taken immediately after running syspolicy_check.
    Type: Notary Error
```

But this also appears for any build, even with a different assembly name that works.

**Comment by vcsjones** [comment]
I can reproduce this.

> ASP: Security policy would not allow process: 24369, /Users/vcsjones/Projects/My/bin/Debug/net8.0/My.Service

Is in the Console. I don't get that on applications that do run successfully.

There seems to be similar reports of issues where executables ending in .Service are problematic. https://developer.apple.com/forums/thread/737080

I can reproduce this without .NET.

1. Create an empty file with the name `foo.Service`
2. Set the content to

    ```bash
    #!/usr/bin/env bash
    echo "hello!"
    ```
3. Make it executable with `chmod +x foo.Service`
4. Run it with `./foo.Service`
5. Observe: It gets killed by Gatekeeper.
6. Rename `foo.Service` to `foo.Potato` with `mv foo.Service foo.Potato`
7. Run it with `./foo.Potato`
8. Observe: "hello!" is printed to the console.

So, this seems to be a behavior of Sonoma that is not .NET specific. For whatever reason, Sonoma does not appear to like executables ending in `.Service`.

**Comment by bjosttveit** [comment]
It seems to also happen when the name ends with `.App` as well

**Comment by elinor-fung** [comment]
Thanks for investigating, @vcsjones. It looks like this is some restriction from the OS for what things can be named. If anyone has a link to public doc from Apple (I couldn't find anything), we can link to it. Otherwise, I don't think there's anything we can do here.

**Comment by danmoseley** [comment]
mention here as well, but still no list just a note there's many.
https://www.reddit.com/r/MacOS/comments/esfx1e/how_to_prevent_os_catalina_showing_folder_name/?rdt=38463
