### ISSUE TITLE
Native AOT (.NET 8.0) functions hook. (Native DLL Inject)

### ISSUE THREAD

**Issue by dadavadd** [dotnet/runtime#93730]
If I compile the Native AOT library (.dll), can I somehow hook functions in processes? For example: by offset, redirect a method to my dll using jmp? If yes, then how?

**Comment by jkotas** [comment]
You can use libraries like https://github.com/microsoft/Detours together with native AOT.

Note that hooking existing functions is very advanced topic. Here is an example of an issue that you can run into with hooking existing functions https://github.com/dotnet/runtime/issues/78086.
