### ISSUE TITLE
FIleNotFoundException occurs

### ISSUE THREAD

**Issue by ChidanandMurugaiah** [dotnet/runtime#93747]
### Description

When we try to get the Satellite Assembly from the instance of the assembly. It throws the exception. Kindly refer the code snippet to replicate it.

```
 Assembly lookupAssembly = Assembly.GetEntryAssembly();
 lookupAssembly = lookupAssembly.GetSatelliteAssembly(CultureInfo.CurrentUICulture);
```

Stack Trace:

 	mscorlib.dll!System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(string name, System.Globalization.CultureInfo culture, System.Version version, bool throwOnFileNotFound, ref System.Threading.StackCrawlMark stackMark)	Unknown	Non-user code. Skipped loading symbols.
 	mscorlib.dll!System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(System.Globalization.CultureInfo culture, System.Version version, ref System.Threading.StackCrawlMark stackMark)	Unknown	Non-user code. Skipped loading symbols.
 	mscorlib.dll!System.Reflection.RuntimeAssembly.GetSatelliteAssembly(System.Globalization.CultureInfo culture)	Unknown	Non-user code. Skipped loading symbols.
	WindowsFormsApp.exe!WindowsFormsApp.Form1.Form1() Line 22	C#	Symbols loaded.
 	WindowsFormsApp.exe!WindowsFormsApp.Program.Main() Line 19	C#	Symbols loaded.

### Reproduction Steps

Just run the sample with the code snippet

### Expected behavior

![image](https://github.com/dotnet/runtime/assets/124787498/1bf96bb9-8732-4cb4-9836-e5cf04329714)

### Actual behavior

Need to run properly

### Regression?

It works properly in .NetCore.

### Configuration

* .Net Framework 4.8
* Windows 10 21H2 
* AnyCPU

**Comment by jkotas** [comment]
Visual Studio developer community is the right place for .NET Framework questions and issue. Could you please file it there instead?

https://developercommunity.visualstudio.com/home
