### ISSUE TITLE
[API Proposal]: Make String::FastAllocateString(int) public, or add a public proxy

### ISSUE THREAD

**Issue by Slxdy** [dotnet/runtime#93740]
### Background and motivation

Currently, there is no way to allocate a string in an unsafe context without filling it (with `String::.ctor(System.Char,System.Int32)`).
It would be great to have a way to do so, as it could speed up some unsafe code that wants to allocate a string without additionally formatting it.

### API Proposal

```csharp
// System.String

[MethodImpl(MethodImplOptions.InternalCall)]
internal static extern string FastAllocateString(int length);

public static string UnsafeAllocateString(int length) => FastAllocateString(length);
```

### API Usage

```csharp
var buffer = string.UnsafeAllocateString(10);

fixed (char* p = buffer)
{
    SomeDllImport(p, buffer.Length);
}
```

**Comment by DaZombieKiller** [comment]
A `string` in .NET is considered immutable. Code outside of the runtime is not supposed to mutate string instances, by doing so you risk corrupting things. The "public" version of `FastAllocateString` is [`string.Create<TState>`](https://learn.microsoft.com/en-us/dotnet/api/system.string.create?view=net-7.0#system-string-create-1(system-int32-0-system-buffers-spanaction((system-char-0)))).

That API will use `FastAllocateString` and then give you a mutable `Span<char>` over the string's data that you are allowed to mutate from within that callback. This is a contract that the runtime will uphold and will continue to be safe, unlike directly mutating `string` data yourself.

All of that said, `new string('\0', length)` [already works as an equivalent to calling `FastAllocateString`](https://github.com/dotnet/runtime/blob/04ede0dadfbf2f1082d3bd218cea6fe46bbbed4a/src/libraries/System.Private.CoreLib/src/System/String.cs#L298-L303), but I still would not recommend relying on this for the reasons I described above. `string.Create<TState>` is the intended API to use.

**Comment by reflectronic** [comment]
This has been discussed before and rejected in https://github.com/dotnet/runtime/issues/36989

**Comment by vcsjones** [comment]
Doesn’t `string.Create` fulfill this?

Something along the lines of

```C#
string str = string.Create(10, (object)null, (buffer, _) => {
    fixed (char* p = buffer) {
        SomeDllImport(p, 10);
    }
});
```

**Comment by Slxdy** [comment]
> Doesn’t `string.Create` fulfill this?
> 
> Something along the lines of
> 
> ```cs
> string str = string.Create(10, (object)null, (buffer, _) => {
>     fixed (char* p = buffer) {
>         SomeDllImport(p, 10);
>     }
> });
> ```

Honestly, this does actually seem like a great solution, however, I still feel like having to create an additional function only to unsafely modify a string is kinda unnecessary, AND having the `state` parameter makes no sense in so many cases.

But thanks for all the input everyone. I guess I will just use this as an alternative for now.

**Comment by teo-tsirpanis** [comment]
> having the `state` parameter makes no sense in so many cases

It actually does make sense in most cases. You can avoid allocating a delegate every time you call `String.Create` by only using `state` and not capturing anything else.
