### ISSUE TITLE
[WSL] Can't Spawn Window with Process.Start()

### ISSUE THREAD

**Issue by guilhas07** [dotnet/runtime#93755]
I have been trying to spawn a process in another windows terminal from my main Program.cs:

```
var p = new Process();
p.StartInfo = new()
{
    CreateNoWindow = false,
    UseShellExecute = true,
    FileName = @"../test2/bin/Debug/net6.0/test2",
};
p.Start();
```
However I can't get it to work on WSL, and can't find people with the same problem as me. It is worth to note that with the dotnet runtime installed on windows I could indeed spawn another windows terminal.

Sorry if this is not the correct place to report this issue, I reported this here because of being related with the Process class. 
Thank you for your help!

Versions used:
- dotnet-sdk 6
- wsl2 - ubuntu 22.04
- terminal - both windows terminal and terminal preview

Test2 csproj and _file_ command ouput: 
`ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=1bf4e69b17ed4ad6df6f8094c9573b3c479d19c4, stripped`
```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
</Project>
```

**Comment by radical** [comment]
On linux you need to explicitly use `dotnet` to run the assembly, like `dotnet ../test2/bin/Debug/net6.0/test2.exe`. You also need to use the full filename.

**Comment by guilhas07** [comment]
> On linux you need to explicitly use `dotnet` to run the assembly, like `dotnet ../test2/bin/Debug/net6.0/test2.exe`. You also need to use the full filename.
Hi! Thank you for your reply!

I still couldn't create other terminal window. Both examples run in the same terminal, with exactly the same behaviour. Changes:
```
var file = Path.GetFullPath("../test2/bin/Debug/net6.0/test2.dll");
p.StartInfo = new()
{
    CreateNoWindow = false,
    UseShellExecute = true,
    FileName = "dotnet",
    Arguments = $"{file}",
};
```
The closer alternative that I found was to force open the windows terminal using "wt.exe" as the `StartInfo.FileName`, but this doesn't seem the correct approach.

Please let me know If I misunderstood what you said. Thank you again for the help.

**Comment by Jozkee** [comment]
I'm not familiar with how you can spawn terminals/consoles from WSL, you should try starting a discussion on https://github.com/microsoft/WSL.
