### ISSUE TITLE
EnumConverter ignores naming policy for property names on deserialization

### ISSUE THREAD

**Issue by dferretti** [dotnet/runtime#93765]
### Description

I am trying to apply a kebab case naming policy to an enum type in all places that it might be used. Dictionaries with this enum as a key are failing to round trip.

I read through as many comments as I could find on old PRs, leading me to this one: https://github.com/dotnet/runtime/pull/73348#discussion_r938787749
but I am not sure if I understand the decision. I know that [DictionaryKeyPolicy](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.dictionarykeypolicy?view=net-7.0#remarks) specifically is not supported for deserializing. But this EnumConverter that keeps track of its own internal naming policy doesn't necessarily need to follow suit does it?

### Reproduction Steps

```c#
var d = new Dictionary<TestEnum, TestEnum> { [TestEnum.YesNo] = TestEnum.YesNo };
var json = JsonSerializer.Serialize(d);
Console.WriteLine(json); // prints {"yes-no":"yes-no"}
var d2 = JsonSerializer.Deserialize<Dictionary<TestEnum, TestEnum>>(json);

[JsonConverter(typeof(KebabConverter))]
public enum TestEnum { YesNo }

public class KebabConverter : JsonStringEnumConverter
{
  public KebabConverter() : base(JsonNamingPolicy.KebabCaseLower, allowIntegerValues: false) { }
}
```

results in
```
Unhandled exception. System.Text.Json.JsonException: The JSON value could not be converted to TestEnum. Path: $.yes-no | LineNumber: 0 | BytePositionInLine: 10.
   at System.Text.Json.ThrowHelper.ThrowJsonException(String message)
   at System.Text.Json.Serialization.Converters.EnumConverter`1.ReadAsPropertyNameCore(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
```

### Expected behavior

Naming policy is honored during dictionary deserialization for keys and values

### Actual behavior

Exception is thrown

### Configuration

Tried on 7.0.12 and .NET 8 Preview 3

**Comment by eiriktsarpalis** [comment]
This looks like a bug. The comment in https://github.com/dotnet/runtime/pull/73348#discussion_r938787749 concerns `DictionaryKeyPolicy` semantics which is ignored on deserialization by design. The concerns listed on https://github.com/dotnet/runtime/issues/30142 do not apply to enum deserialization, so I think we should honor the converter naming policy in dictionary key serialization.

This probably wasn't caught so far because the only available naming policy until today was camelCase, which happens to work because the enum parser is case insensitive.

**Comment by dferretti** [comment]
Awesome, thanks for the fast turnaround! Guessing this is too close to make it in to .net 8?

**Comment by eiriktsarpalis** [comment]
> Guessing this is too close to make it in to .net 8?

Unfortunately, yes. It also doesn't meet the bar for a servicing fix. As a workaround you could try authoring a custom converter dictionary key conversion the right way (by overriding the `WriteAsPropertyName`/`ReadAsPropertyName` methods).
