### ISSUE TITLE
[wasm] Typo in browser-bench wasm app

### ISSUE THREAD

**Issue by matouskozak** [dotnet/runtime#93777]
In the browser-bench app (in wasm sample app folder), the name of the measurement should be ToTitleCase, not ToTileCase.
https://github.com/dotnet/runtime/blob/04ede0dadfbf2f1082d3bd218cea6fe46bbbed4a/src/mono/sample/wasm/browser-bench/String.cs#L139

Not sure if simple renaming would work as it could break connection with past measurements.

---

cc: @ilonatommy

**Comment by lewing** [comment]
We could rename the Test :)

**Comment by radekdoulik** [comment]
I think it is fine to rename. The new measurements will end in a new graph. This measurement didn't change lately, so we it will be fine. If needed, we can later also rename the measurement in the data.

![image](https://github.com/dotnet/runtime/assets/4147484/4b71d919-1163-4858-9f7e-18a8ed03fb82)
