### ISSUE TITLE
NativeAOT iOS/osx/tvos legs are timing out on many PRs

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#93784]
Example from https://github.com/dotnet/runtime/pull/93773

<img width="599" alt="image" src="https://github.com/dotnet/runtime/assets/6668460/4f245f9f-ffd9-45a0-a539-886125860728">

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by jkotas** [comment]
@agocke @ivanpovazan Is it intentional that we run all flavors in PR CI? There does not seem to be enough capacity for it, leading to frequent timeouts.

**Comment by ivanpovazan** [comment]
Yes, on Friday `OSX.1200.Amd64.Open` helix queue seemed to be pretty backed up, causing timeouts for all runtime flavours. We enabled `ios/tvos` lanes with NativeAOT to run functional smoke tests by default, as we wanted to catch any regression early-on regarding the iOS platforms support during preparation for RC releases (introduced by: https://github.com/dotnet/runtime/commit/55828b9aa911a98fe81c8bcbb9a4d8b1ae90ae29).

These lanes run only functional smoke tests in the following setup:
- The `tvos-arm64` lane executes one functional test on a device - https://helix.dot.net/api/jobs/7e15e9f6-646a-4323-b76e-f6e05dbd479d/workitems?api-version=2019-06-17 
- The `ios-arm64` lane executes two functional tests on a device - https://helix.dot.net/api/jobs/a45cba58-70c0-4609-8cb4-1652ae01a7a5/workitems?api-version=2019-06-17

This was called out previously here: https://github.com/dotnet/runtime/pull/87773/files#r1291590026
and here: https://github.com/dotnet/runtime/pull/87773#issuecomment-1710609189

If this started affecting CI capacity we might consider enabling these lanes in the `runtime-nativeaot-outerloop` pipeline instead (PS: they are already enabled in `runtime-extra-platforms`).

**Comment by steveisok** [comment]
Around snap time we have this issue due to increased number of overall work items. Let's see if this continues and go from there.

**Comment by akoeplinger** [comment]
Seems like we no longer see these timeouts, closing.
