### ISSUE TITLE
ILLink: TrimmerRootAssembly: error IL1032: Root assembly '…' could not be found

### ISSUE THREAD

**Issue by ygoe** [dotnet/runtime#93799]
### Description

I've been following the instructions from the [documentation](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming?pivots=dotnet-7-0).

When running the `dotnet publish …` command, I get the error in the title.

I'm trying to make my library "DeepConvert" trimming-ready. It has another project "DeepConvert.Tests" in the same solution which I use as entry project to publish here. This is the test project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <PublishTrimmed>true</PublishTrimmed>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.7.2" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.1.1" />
    <PackageReference Include="MSTest.TestFramework" Version="3.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DeepConvert\DeepConvert.csproj" />
    <TrimmerRootAssembly Include="DeepConvert" />
  </ItemGroup>

</Project>
```

### Reproduction Steps

See above

### Expected behavior

No error? At least the documentation doesn't mention any.

### Actual behavior

The error.

### Known Workarounds

None, I'm stuck here. Cannot make my library trimmable.

### Configuration

.NET 7.0.12 on Windows 11 x64

**Comment by vitek-karas** [comment]
What is the exact error you get - is it about the `DeepConvert` assembly or some other?

**Comment by ygoe** [comment]
I lost interest in this subject. After some more investigations I found that it's impossible to trim this library. For newer projects, I'm not using it and those run successfully with AOT. So while I guess that error reporting could be improved around complicated reflection cases, I can't spend the time to help in this.

**Comment by vitek-karas** [comment]
Closing due to insufficient information from the user.
