### ISSUE TITLE
Disposal of System.Threading.RateLimiting.ConcurrencyLease

### ISSUE THREAD

**Issue by wasker** [dotnet/runtime#93808]
### Description

It seems that ConcurrencyLimiter.AttemptAcquireCore and ConcurrencyLimiter.AcquireAsyncCore return cached instances of SuccessfulLease, FailedLease, and QueueLimitLease.

If the pattern of usage is

```
using var lease = rateLimiter.AtemptAcquire(1);
```

then all those cached instances will be disposed at some point.

Is this expected?

### Reproduction Steps

Run

```
using var lease = rateLimiter.AtemptAcquire(1);
```

in the concurrent scenario and observe that SuccessfulLease / FailedLease are being disposed multiple times.

### Expected behavior

Not dispose instances that were disposed earlier.

### Actual behavior

Same instances are being disposed multiple times.

**Comment by BrennanConroy** [comment]
The cached instances don't do anything on dispose so it's not really an issue if they get disposed multiple times. Are you seeing an issue?
