### ISSUE TITLE
NativeAOT: Invalid handling of `nosinglewarnassembly`

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#93819]
Using a project file like this:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

<Target Name="ConfigureTrimming"
        BeforeTargets="PrepareForILLink">
  <ItemGroup>
    <ManagedAssemblyToLink Condition="'%(Filename)' == 'System.Xml'">
      <TrimmerSingleWarn>false</TrimmerSingleWarn>
    </ManagedAssemblyToLink>
  </ItemGroup>
</Target>

</Project>
```

This should end up adding `--nosinglewarnassembly:System.Xml` to the ilc command line. But in reality it adds `--nosinglewarnassembly:System`.

The bug is very likely in 
https://github.com/dotnet/runtime/blob/c7fd55cd4051b009d4cb7564c8246b6b8b337724/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets#L276C45-L276C45

The item group `_IlcNoSingleWarnAssemblies` already contains simple names of assemblies, not file names. So using `%(Filename)` seems to remove another "extension" from the name.

**Comment by LakshanF** [comment]
I believe this was fixed with #101799
