### ISSUE TITLE
System.Security.Cryptography.Tests timing out

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#93840]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=447058
Build error leg or test failing: System.Security.Cryptography.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/93815

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "['System.Security.Cryptography.Tests' END OF WORK ITEM LOG: Command timed out, and was killed]",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=447058
**Error message validated:** `['System.Security.Cryptography.Tests' END OF WORK ITEM LOG: Command timed out, and was killed]`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 10/23/2023 3:23:27 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[480505](https://dev.azure.com/dnceng-public/public/_build/results?buildId=480505)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=480505&view=ms.vss-test-web.build-test-results-tab&runId=11027438&resultId=197487)|dotnet/runtime#95233|
|[480381](https://dev.azure.com/dnceng-public/public/_build/results?buildId=480381)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=480381&view=ms.vss-test-web.build-test-results-tab&runId=11024524&resultId=197487)|dotnet/runtime#95233|
|[480271](https://dev.azure.com/dnceng-public/public/_build/results?buildId=480271)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=480271&view=ms.vss-test-web.build-test-results-tab&runId=11020710&resultId=197487)|dotnet/runtime#95234|
|[480263](https://dev.azure.com/dnceng-public/public/_build/results?buildId=480263)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=480263&view=ms.vss-test-web.build-test-results-tab&runId=11020628&resultId=197489)|dotnet/runtime#95235|
|[480184](https://dev.azure.com/dnceng-public/public/_build/results?buildId=480184)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=480184&view=ms.vss-test-web.build-test-results-tab&runId=11018054&resultId=197487)||
|[480177](https://dev.azure.com/dnceng-public/public/_build/results?buildId=480177)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=480177&view=ms.vss-test-web.build-test-results-tab&runId=11017760&resultId=197487)|dotnet/runtime#95229|
|[479921](https://dev.azure.com/dnceng-public/public/_build/results?buildId=479921)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=479921&view=ms.vss-test-web.build-test-results-tab&runId=11009904&resultId=197487)|dotnet/runtime#95221|
|[479747](https://dev.azure.com/dnceng-public/public/_build/results?buildId=479747)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=479747&view=ms.vss-test-web.build-test-results-tab&runId=11004574&resultId=197479)|dotnet/runtime#94621|
|[479715](https://dev.azure.com/dnceng-public/public/_build/results?buildId=479715)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=479715&view=ms.vss-test-web.build-test-results-tab&runId=11003524&resultId=197479)|dotnet/runtime#93220|
|[479663](https://dev.azure.com/dnceng-public/public/_build/results?buildId=479663)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=479663&view=ms.vss-test-web.build-test-results-tab&runId=11002820&resultId=197479)|dotnet/runtime#95175|
|[479660](https://dev.azure.com/dnceng-public/public/_build/results?buildId=479660)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=479660&view=ms.vss-test-web.build-test-results-tab&runId=11002842&resultId=197479)|dotnet/runtime#95208|
|[479427](https://dev.azure.com/dnceng-public/public/_build/results?buildId=479427)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=479427&view=ms.vss-test-web.build-test-results-tab&runId=10995382&resultId=197479)|dotnet/runtime#93879|
|[479411](https://dev.azure.com/dnceng-public/public/_build/results?buildId=479411)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=479411&view=ms.vss-test-web.build-test-results-tab&runId=10994886&resultId=197479)|dotnet/runtime#94621|
|[478740](https://dev.azure.com/dnceng-public/public/_build/results?buildId=478740)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=478740&view=ms.vss-test-web.build-test-results-tab&runId=10972450&resultId=197478)|dotnet/runtime#95154|
|[477835](https://dev.azure.com/dnceng-public/public/_build/results?buildId=477835)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=477835&view=ms.vss-test-web.build-test-results-tab&runId=10945074&resultId=197443)||
|[476935](https://dev.azure.com/dnceng-public/public/_build/results?buildId=476935)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=476935&view=ms.vss-test-web.build-test-results-tab&runId=10916628&resultId=197443)|dotnet/runtime#95066|
|[476445](https://dev.azure.com/dnceng-public/public/_build/results?buildId=476445)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=476445&view=ms.vss-test-web.build-test-results-tab&runId=10899612&resultId=197441)|dotnet/runtime#94673|
|[476404](https://dev.azure.com/dnceng-public/public/_build/results?buildId=476404)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=476404&view=ms.vss-test-web.build-test-results-tab&runId=10898624&resultId=197441)|dotnet/runtime#91229|
|[475832](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475832)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475832&view=ms.vss-test-web.build-test-results-tab&runId=10879312&resultId=197433)|dotnet/runtime#94955|
|[475485](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475485)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475485&view=ms.vss-test-web.build-test-results-tab&runId=10871052&resultId=197433)|dotnet/runtime#94647|
|[474827](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474827)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474827&view=ms.vss-test-web.build-test-results-tab&runId=10846504&resultId=197429)||
|[473549](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473549)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473549&view=ms.vss-test-web.build-test-results-tab&runId=10807294&resultId=197411)|dotnet/runtime#94896|
|[473545](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473545)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473545&view=ms.vss-test-web.build-test-results-tab&runId=10807266&resultId=197411)|dotnet/runtime#93493|
|[473190](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473190)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473190&view=ms.vss-test-web.build-test-results-tab&runId=10795128&resultId=197409)|dotnet/runtime#93493|
|[472133](https://dev.azure.com/dnceng-public/public/_build/results?buildId=472133)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=472133&view=ms.vss-test-web.build-test-results-tab&runId=10766582&resultId=197408)|dotnet/runtime#88620|
|[471508](https://dev.azure.com/dnceng-public/public/_build/results?buildId=471508)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=471508&view=ms.vss-test-web.build-test-results-tab&runId=10747252&resultId=206322)||
|[469910](https://dev.azure.com/dnceng-public/public/_build/results?buildId=469910)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=469910&view=ms.vss-test-web.build-test-results-tab&runId=10697512&resultId=197397)|dotnet/runtime#93493|
|[468498](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468498)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468498&view=ms.vss-test-web.build-test-results-tab&runId=10655494&resultId=197386)|dotnet/runtime#92095|
|[467295](https://dev.azure.com/dnceng-public/public/_build/results?buildId=467295)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=467295&view=ms.vss-test-web.build-test-results-tab&runId=10618338&resultId=197401)|dotnet/runtime#94640|
|[466434](https://dev.azure.com/dnceng-public/public/_build/results?buildId=466434)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=466434&view=ms.vss-test-web.build-test-results-tab&runId=10592348&resultId=197333)|dotnet/runtime#93906|
|[466415](https://dev.azure.com/dnceng-public/public/_build/results?buildId=466415)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=466415&view=ms.vss-test-web.build-test-results-tab&runId=10591926&resultId=197402)|dotnet/runtime#94597|
|[466380](https://dev.azure.com/dnceng-public/public/_build/results?buildId=466380)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=466380&view=ms.vss-test-web.build-test-results-tab&runId=10591090&resultId=197402)|dotnet/runtime#94239|
|[466040](https://dev.azure.com/dnceng-public/public/_build/results?buildId=466040)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=466040&view=ms.vss-test-web.build-test-results-tab&runId=10583508&resultId=197402)|dotnet/runtime#94606|
|[465525](https://dev.azure.com/dnceng-public/public/_build/results?buildId=465525)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=465525&view=ms.vss-test-web.build-test-results-tab&runId=10568396&resultId=197402)|dotnet/runtime#94497|
|[465485](https://dev.azure.com/dnceng-public/public/_build/results?buildId=465485)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=465485&view=ms.vss-test-web.build-test-results-tab&runId=10567638&resultId=197402)|dotnet/runtime#94548|
|[464521](https://dev.azure.com/dnceng-public/public/_build/results?buildId=464521)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=464521&view=ms.vss-test-web.build-test-results-tab&runId=10537600&resultId=206255)|dotnet/runtime#92226|
|[464460](https://dev.azure.com/dnceng-public/public/_build/results?buildId=464460)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=464460&view=ms.vss-test-web.build-test-results-tab&runId=10535808&resultId=197420)|dotnet/runtime#93191|
|[464383](https://dev.azure.com/dnceng-public/public/_build/results?buildId=464383)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=464383&view=ms.vss-test-web.build-test-results-tab&runId=10531754&resultId=194649)|dotnet/runtime#94554|
|[463881](https://dev.azure.com/dnceng-public/public/_build/results?buildId=463881)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=463881&view=ms.vss-test-web.build-test-results-tab&runId=10518500&resultId=201495)||
|[464046](https://dev.azure.com/dnceng-public/public/_build/results?buildId=464046)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=464046&view=ms.vss-test-web.build-test-results-tab&runId=10517544&resultId=202015)|dotnet/runtime#93986|
|[459752](https://dev.azure.com/dnceng-public/public/_build/results?buildId=459752)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=459752&view=ms.vss-test-web.build-test-results-tab&runId=10376366&resultId=197393)|dotnet/runtime#94239|
|[457199](https://dev.azure.com/dnceng-public/public/_build/results?buildId=457199)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=457199&view=ms.vss-test-web.build-test-results-tab&runId=10295388&resultId=197389)|dotnet/runtime#94241|
|[456951](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456951)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456951&view=ms.vss-test-web.build-test-results-tab&runId=10288278&resultId=197389)|dotnet/runtime#94239|
|[456898](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456898)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456898&view=ms.vss-test-web.build-test-results-tab&runId=10286270&resultId=197389)|dotnet/runtime#94237|
|[456798](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456798)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456798&view=ms.vss-test-web.build-test-results-tab&runId=10284168&resultId=197389)|dotnet/runtime#94226|
|[456760](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456760)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456760&view=ms.vss-test-web.build-test-results-tab&runId=10283088&resultId=197389)|dotnet/runtime#93223|
|[454774](https://dev.azure.com/dnceng-public/public/_build/results?buildId=454774)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=454774&view=ms.vss-test-web.build-test-results-tab&runId=10218616&resultId=206282)||
|[454428](https://dev.azure.com/dnceng-public/public/_build/results?buildId=454428)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=454428&view=ms.vss-test-web.build-test-results-tab&runId=10207246&resultId=197365)|dotnet/runtime#93907|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|18|48|

**Comment by jeffhandley** [comment]
Added this to the 9.0.0 milestone because of the frequency
