### ISSUE TITLE
[API Proposal]: Return Matcher from MatcherExtensions

### ISSUE THREAD

**Issue by ngarside** [dotnet/runtime#93866]
### Background and motivation

The [`AddInclude`](https://github.com/dotnet/runtime/blob/20e3bbf9ee6a3f6a465f6d0b12ed0d3efd4fef22/src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/Matcher.cs#L134C35-L134C35) and [`AddExclude`](https://github.com/dotnet/runtime/blob/20e3bbf9ee6a3f6a465f6d0b12ed0d3efd4fef22/src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/Matcher.cs#L152C35-L152C35) methods both return the current `Matcher` instance, allowing them to be chained.

However the [`AddIncludePatterns`](https://github.com/dotnet/runtime/blob/20e3bbf9ee6a3f6a465f6d0b12ed0d3efd4fef22/src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/MatcherExtensions.cs#L35C30-L35C30) and [`AddExcludePatterns`](https://github.com/dotnet/runtime/blob/20e3bbf9ee6a3f6a465f6d0b12ed0d3efd4fef22/src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/MatcherExtensions.cs#L19C38-L19C38) extensions do not return the `Matcher` instance, meaning these can not be chained.

I'm proposing that `AddIncludePatterns` and `AddExcludePatterns` return the `Matcher` instance, to better match the behaviour of `AddInclude` and `AddExclude`, and to allow chaining.

### API Proposal

```diff
namespace Microsoft.Extensions.FileSystemGlobbing;

public static class MatcherExtensions
{
-   public static void AddIncludePatterns(this Matcher matcher, params IEnumerable<string>[] includePatternsGroups) { ... }
+   public static Matcher AddIncludePatterns(this Matcher matcher, params IEnumerable<string>[] includePatternsGroups) { ... }

-   public static void AddExcludePatterns(this Matcher matcher, params IEnumerable<string>[] excludePatternsGroups) { ... }
+   public static Matcher AddExcludePatterns(this Matcher matcher, params IEnumerable<string>[] excludePatternsGroups) { ... }
}
```

### API Usage

```csharp
var matched = new Matcher()
    .AddExcludePatterns(excluded)
    .AddIncludePatterns(included)
    .Execute(new DirectoryInfoWrapper("..."));
```

### Risks

This should be low risk, as it simply changes the return value from `void` -> `Matcher`.

**Comment by huoyaoyuan** [comment]
Change the returning type of a method is a hard breaking change, and will cause code compiled with old package to fail loading.

The compatibility requirement of extension packages can be weaker than inbox libraries, but this may still bd rejected.

**Comment by Jozkee** [comment]
Please refer to https://learn.microsoft.com/dotnet/core/compatibility/library-change-rules to find out what's [not] allowed to change.
