### ISSUE TITLE
[GC] DATAS Tuning to improve pauses and heap volatility

### ISSUE THREAD

**Issue by mangod9** [dotnet/runtime#93891]
.NET 8 introduced Dynamic GC mode to improve memory utilization. This issue tracks further tuning work to improve the performance of this new functioality:

- [x] Reduce Throughput Regression 
- [x] Reduce pause times when updating heap counts
- [x] Reduce heap_count volatility

**Comment by hez2010** [comment]
We did a simple BinaryTree benchmark against DATAS but it seems that the perf regression of DATAS is quite large: https://github.com/dotnet/runtime/issues/101006. While the memory utilization and pause time did get some improvements.

**Comment by mangod9** [comment]
@hez2010, can you try with the latest .NET preview 5 release? We had done some additional tuning as part of that.

**Comment by hez2010** [comment]
@mangod9 Tested with the latest nightly build (9.0.100-preview.7.24355.2).

| Method           | Job                  | maxDepth | Mean      | Error    | StdDev   | Gen0       | Gen1       | Gen2      | Allocated  |
|----------------- |--------------------- |--------- |----------:|---------:|---------:|-----------:|-----------:|----------:|-----------:|
| ClassBinaryTree  | DynamicAdaptation GC | 17       | 250.39 ms | 4.893 ms | 7.902 ms | 20500.0000 |   500.0000 |         - | 1120.67 MB |
| StructBinaryTree | DynamicAdaptation GC | 17       | 102.89 ms | 2.044 ms | 3.242 ms |  8333.3333 |   500.0000 |  166.6667 |  446.67 MB |
| ClassBinaryTree  | Server GC            | 17       | 254.49 ms | 4.878 ms | 5.991 ms | 21333.3333 |   333.3333 |         - | 1120.67 MB |
| StructBinaryTree | Server GC            | 17       | 100.69 ms | 2.009 ms | 3.466 ms |  8166.6667 |   333.3333 |         - |  446.67 MB |
| ClassBinaryTree  | Workstation GC       | 17       | 217.65 ms | 2.934 ms | 2.450 ms | 75666.6667 | 11333.3333 | 1000.0000 | 1120.67 MB |
| StructBinaryTree | Workstation GC       | 17       |  81.03 ms | 1.607 ms | 3.173 ms | 30285.7143 |  1428.5714 |  428.5714 |  446.67 MB |

Seems that the performance of DATAS has been improved and it does not regress the SRV GC performance in this benchmark anymore. While WKS GC is the fastest one in this binary-tree benchmark.

**Comment by mangod9** [comment]
ok good to know that the regression is gone.
