### ISSUE TITLE
New TimeSpan.From overloads which take integers.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#93890]
### Summary

`TimeSpan` exposes several `From*` methods that allow users to create a timespan using a `double`. However, `double` is a binary based floating-point format and thus has natural imprecision that can introduce error. For example, `TimeSpan.FromSeconds(101.832)` is not `101 seconds, 832 milliseconds`, but rather is `101 seconds, 831.9999999999936335370875895023345947265625 milliseconds`.

This has, over time, led to repeated user confusion and bugs in the API surface that users have had to rationalize and deal with. It is also one of the less efficient ways to represent this data and makes it problematic for users wanting or expecting a particular behavior

As such, it is proposed that new overloads be provided, allowing users to pass in integers so they can get the desired and intended behavior. It may be worth considering whether or not the `double` overloads should be "deprecated" (either via obsoletion or some analyzer) to help direct users towards success.

### API Proposal

```csharp
namespace System;

public partial struct TimeSpan
{
    public static TimeSpan FromDays(int days, int hours = 0, int minutes = 0, int seconds = 0, int milliseconds = 0, int microseconds = 0);
    public static TimeSpan FromHours(int hours, int minutes = 0, int seconds = 0, int milliseconds = 0, int microseconds = 0);
    public static TimeSpan FromMinutes(int minutes, int seconds = 0, int milliseconds = 0, int microseconds = 0);
    public static TimeSpan FromSeconds(int seconds, int milliseconds = 0, int microseconds = 0);
    public static TimeSpan FromMilliseconds(int milliseconds, int microseconds = 0);
    public static TimeSpan FromMicroseconds(int microseconds);
}
```

### Additional Considerations

It may be desirable to not use default parameters. However, this provides a benefit that a user can do something like `FromDays(5, seconds: 30)` if that were appropriate for their use case.

After these APIs are exposed, calling `From(x)` where `x` was an integer may produce a different result in various edge cases.

APIs where the user specifies a `uint`, `long`, or `ulong` would still end up calling the `double` overload due to the implicit conversion that exists in C#. Thus, an analyzer or deprecation of the `double` overloads may be desirable to help users achieve success.

Exposing overloads that take `decimal` could also be desirable and would avoid the issues around precision loss, but would be much less performant than breaking it apart like this.

**Comment by tannergooding** [comment]
Opened in response to https://github.com/dotnet/runtime/issues/93831 and the numerous other issues where the various `TimeSpan` APIs which take `double` have shown themselves to be problematic.

CC. @tarekgh

**Comment by vcsjones** [comment]
`TimeSpan` has constructors that largely do the same thing, unless I am misunderstanding. There was also the recent addition of constructors that take microseconds in https://github.com/dotnet/runtime/issues/23799.

Are the constructors reasonable enough?

**Comment by tarekgh** [comment]
> public static TimeSpan FromHours(int hours = 0, int minutes = 0, int seconds = 0, int milliseconds = 0, int microseconds = 0);

@tannergooding did you mean to have the `hours` parameter with default value? 

@vcsjones the idea here is having the users not providing a lot of value as the constructor requires. Having default parameter values will help.

**Comment by tannergooding** [comment]
>  did you mean to have the hours parameter with default value?

Nope. The first parameter should be non-defaultable. Fixed.

Please feel free to mark `api-ready-for-review` if you think this is in the right shape and good for API review.

> Are the constructors reasonable enough? If not, should the focus instead be on improving the constructors?

I think the constructors are worse in a lot of ways over static methods. For example, `new TimeSpan(1, 2, 3)` and `new TimeSpan(1, 2, 3, 4)` having arguments not line up (one is `hours` first the other is `days` first). You can't expose defaultable parameters without causing ambiguities. `new TimeSpan(...)` in general doesn't help provide clarity or intent, at a glance, etc.

The explicit `From*` APIs, on the other hand, avoid most of these issues and provide additional clarity to the code in question (as a personal preference, `TimeSpan.FromHours(5, 1, 30)` also looks a lot cleaner than `new TimeSpan(5, 1, 30)` and is more visually appealing in code).

**Comment by skyoxZ** [comment]
> After these APIs are exposed, calling `From(x)` where `x` was an integer may produce a different result in various edge cases.

Really? I thought `double` deals Integer without precision loss. Then these APIs seem useless.

**Comment by tannergooding** [comment]
>  I thought double deals Integer without precision loss

No. `double` can only accurately represent integers up to 2^53, after this point it is lossy. It introduces "loss" for fractional data far before this. This likewise means a loss of data when representing things like `FromDays()` where the scale is large, because they become a large integral value that can exceed this boundary. -- For `float`, this boundary is 2^24

The exclusively integer based approach as proposed here is more accurate and likely to be faster for several scenarios. It likewise doesn't need to handle edge cases such as `NaN` or `Infinity`. The difference in result is that it will return a precise answer matching exactly what the user intended and will not introduce minor inaccuracies due to underlying limitations of a binary based floating-point representation. -- There are notably ways to improve the accuracy of the `double` based overloads, and we've done several of those. But there is fundamentally still some level of error since what the user types as a literal is not always going to be the actual value represented, especially when fractional data is involved.

**Comment by Clockwork-Muse** [comment]
I'm pretty sure @tarekgh meant `int` specifically here, and as a 32-bit type would be less than the precision issues of `double`.

**Comment by Clockwork-Muse** [comment]
... Sure, but all the internal representation is integer based, so that only applies to the constructor.

**Comment by tannergooding** [comment]
@Clockwork-Muse, I'm unsure what you're trying to say or point you're making. Could you please clarify?

What I'm stating is that `TimeSpan` is backed by a 64-bit data type that tracks 100ns ticks. The constructors are setup in a way that makes them confusing (potentially violates some framework design guidelines) and which cannot allow them to use things like defaultable parameters, so they cannot be used here. The `From*` methods currently take a `double`, this introduces error with fractional data and due to the current implementation error with integer data when it is scaled by the `TicksPer*` value, causing it to pass 2^53. It cannot be trivially changed due to it the significant and negative impact it would have on performance.

These new functions address those various concerns and give a much friendlier way to express the data, both from a performance and usability perspective.

**Comment by tcortega** [comment]
@bartonjs @tannergooding I'd be interested in working on this issue if it's still available. I have a few clarifying questions:

1. What's the plan for the double overloads? Will they remain unchanged or is there an intent to deprecate them?
2. I'm assuming the TimeSpan constructors will remain as they are. Can you confirm this?
3. The original issue mentioned the addition of analyzers. Is integrating an analyzer a requisite for resolving this issue?

**Comment by tarekgh** [comment]
@tcortega thanks for willing to help with this one. You can work on it. 

> What's the plan for the double overloads? Will they remain unchanged or is there an intent to deprecate them?

No, we are not touching these overloads nor deprecating it. 

> I'm assuming the TimeSpan constructors will remain as they are. Can you confirm this?

Yes, we are not touching the constructors.

> The original issue mentioned the addition of analyzers. Is integrating an analyzer a requisite for resolving this issue?

No. analyzer work shouldn't block this issue.

**Comment by tarekgh** [comment]
@tcortega are you going to work in this one?

**Comment by tcortega** [comment]
> @tcortega are you going to work in this one?

Yes, can you assign it to me please?

**Comment by tcortega** [comment]
@tarekgh I've submitted a preliminary pull request with my current modifications. It'd be great if you could review it and provide feedback on any issues. In the meantime, I'll be working on the test cases for the new methods.

**Comment by colejohnson66** [comment]
As an outsider: what is the purpose of special casing `long.MinValue` and `long.MaxValue` with checks to return the static `TimeSpan.MinValue` and `TimeSpan.MaxValue`? `new TimeSpan(long.MinValue)` is *identical* to `TimeSpan.MinValue`. And because it’s a `struct`, there’s no allocations to worry about.

Is this a runtime optimization/inlining thing? If it is, I’d argue it should be called out in the source for future readers.

**Comment by tcortega** [comment]
> As an outsider: what is the purpose of special casing `long.MinValue` and `long.MaxValue` with checks to return the static `TimeSpan.MinValue` and `TimeSpan.MaxValue`? `new TimeSpan(long.MinValue)` is _identical_ to `TimeSpan.MinValue`. And because it’s a `struct`, there’s no allocations to worry about.
> 
> Is this a runtime optimization/inlining thing? If it is, I’d argue it should be called out in the source for future readers.

I'd argue that it is due to allocations purpose but I simply attempted to copy the current structure of the `IntervalFromDoubleTicks` that performs an equivalent check:

```csharp
private static TimeSpan IntervalFromDoubleTicks(double ticks)
{
    if ((ticks > long.MaxValue) || (ticks < long.MinValue) || double.IsNaN(ticks))
        ThrowHelper.ThrowOverflowException_TimeSpanTooLong();
    if (ticks == long.MaxValue)
        return MaxValue;
    return new TimeSpan((long)ticks);
}
```

**Comment by tcortega** [comment]
@colejohnson66 You were right anyways, I refactored the code.

**Comment by tcortega** [comment]
@tarekgh In our prior conversation on PR #94143, you mentioned I should align the overflow check with the existing one in the constructor found at https://github.com/dotnet/runtime/blob/cf9bb86cd908a00fa50459ae17ec9c4a76f85fe6/src/libraries/System.Private.CoreLib/src/System/TimeSpan.cs#L142

However, it appears that the current validation is flawed, as demonstrated by the following inconsistency when using `csharprepl`:
```cs
> new TimeSpan(2142483647, 0, 0, 0, 0, 0)
7443823.15:41:44.4838400

> TimeSpan.FromDays(2142483647)
┌───────────────────────Exception───────────────────────┐
│ TimeSpan overflowed because the duration is too long. │
└───────────────────────────────────────────────────────┘
```

**Comment by tarekgh** [comment]
@tcortega this is a bug we can fix. It doesn't mean we should follow this wrong behavior.

**Comment by tcortega** [comment]
I had a lot on my plate today, so I'm planning to knock this out tomorrow or the day after.
