### ISSUE TITLE
Access to the port 'ttyS0' is denied

### ISSUE THREAD

**Issue by aliajboy** [dotnet/runtime#93908]
### Description

I am working on Serial port of Orange Pi PC and whatever I do, I get this error on opening port :
`Unhandled exception. System.UnauthorizedAccessException: Access to the port 'ttyS0' is denied.
 ---> System.IO.IOException: Unknown error 203
   --- End of inner exception stack trace ---
   at System.IO.Ports.SafeSerialDeviceHandle.Open(String portName)
   at System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
   at System.IO.Ports.SerialPort.Open()
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\SoftwarePC\Desktop\ConsoleApp1\ConsoleApp1\Program.cs:line 31
Aborted`

- I am using .Net SDK 7, Latest Visual Studio and Latest IO.Ports, Latest updates on Orange Pi PC with Ubuntu Focal.
- Nothing Except serial port is connected.  
- My user has Both Dialout and TTY Groups and Permission of /dev/ttyS0 is 666. 
- No difference in running in sudo or not.
- I am running my console app on Arm32 Ubuntu in Orange Pi PC.

### Reproduction Steps

Here is my Code:
`using System.IO.Ports;

namespace ConsoleApp1;

class Program
{
    static SerialPort _serialPort;
    static bool _continue;
    static void Main(string[] args)
    {
        string name;
        string message;
        StringComparer stringComparer = StringComparer.OrdinalIgnoreCase;

       
        _serialPort = new SerialPort();

        
        _serialPort.PortName = "ttyS0";
        _serialPort.BaudRate = 115200;
        _serialPort.Parity = Parity.None;
        _serialPort.DataBits = 8;
        _serialPort.StopBits = StopBits.One;
        _serialPort.Handshake = Handshake.None;

      
        _serialPort.ReadTimeout = 500;
        _serialPort.WriteTimeout = 500;
        
        _serialPort.Open();
        _continue = true;

        Console.WriteLine("Type QUIT to exit");

        while (_continue)
        {
            message = Console.ReadLine();

            if (stringComparer.Equals("quit", message))
            {
                _continue = false;
            }
            else
            {
                _serialPort.WriteLine(
                    String.Format( message));
            }
        }

        _serialPort.Close();
    }
}`

### Expected behavior

Orange Pi Send String to PC via USB to TTL Serial Port

### Actual behavior

Permission Error

**Comment by aliajboy** [comment]
I am now see that even running ' sudo cat </dev/ttyS0 ' Can give  me -bash: /dev/ttyS0: Permission denied

**Comment by colejohnson66** [comment]
That’s not a .NET problem. Check your file permissions. Your user might not have access to read that device.

**Comment by wfurt** [comment]
are you sure your serial ports comes as `ttyS0`? I'm not familiar with your particular board but it _may_ be different name. You can check output from `dmesg` (or kernel boot)

**Comment by aliajboy** [comment]
Thanks.
I fixed it. ttyS0 is for debug port. I enable ttyS1 in orangepi-config then use it.
