### ISSUE TITLE
[release/8.0][wasm] WBT completely broken on 8.0 branch

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#93900]
Broken build - [20231023.109](https://dev.azure.com/dnceng-public/public/_build/results?buildId=448681&view=results), and [log](https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-heads-release-80-68eb4e1c553c43f3a4/Workloads-NoWebcil-Wasm.Build.NativeRebuild.Tests.FlagsChangeRebuildTests/1/console.80772c30.log?helixlogtype=result).

```
    Wasm.Build.NativeRebuild.Tests.FlagsChangeRebuildTests.ExtraEmccFlagsSetButNoRealChange [FAIL]
      System.TypeInitializationException : The type initializer for 'Wasm.Build.Tests.BuildTestBase' threw an exception.
      ---- System.Exception : Expected the multithreading runtime pack to be available when running on CI. IsRunningOnCI is true but IsWorkloadWithMultiThreadingForDefaultFramework is false.
```

[Last passing build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=448014&view=results). Diff since then: e1da68dc...d8d69276

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Expected the multithreading runtime pack to be available when running on CI",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[468826](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468826)|dotnet/runtime|[Wasm.Build.Tests.TestAppScenarios.LazyLoadingTests.LoadLazyAssemblyBeforeItIsNeeded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468826&view=ms.vss-test-web.build-test-results-tab&runId=10665564&resultId=100100)|dotnet/runtime#94516|
|[468825](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468825)|dotnet/runtime|[Wasm.Build.Tests.ConfigSrcTests.ConfigSrcAbsolutePath](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468825&view=ms.vss-test-web.build-test-results-tab&runId=10665522&resultId=100101)||
|[468614](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468614)|dotnet/runtime|[Wasm.Build.Tests.PInvokeTableGeneratorTests.DllImportWithFunctionPointers_WarningsAsMessages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468614&view=ms.vss-test-web.build-test-results-tab&runId=10661406&resultId=100091)|dotnet/runtime#94605|
|[468612](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468612)|dotnet/runtime|[Wasm.Build.Tests.MainWithArgsTests.TopLevelWithArgs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468612&view=ms.vss-test-web.build-test-results-tab&runId=10661320&resultId=100099)|dotnet/runtime#94516|
|[468207](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468207)|dotnet/runtime|[Wasm.Build.Tests.TestAppScenarios.LazyLoadingTests.LoadLazyAssemblyBeforeItIsNeeded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=468207&view=ms.vss-test-web.build-test-results-tab&runId=10648828&resultId=100100)|dotnet/runtime#94516|
|[467856](https://dev.azure.com/dnceng-public/public/_build/results?buildId=467856)|dotnet/runtime|[Wasm.Build.Tests.TestAppScenarios.LibraryInitializerTests.LoadLibraryInitializer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=467856&view=ms.vss-test-web.build-test-results-tab&runId=10637818&resultId=100099)|dotnet/runtime#94605|
|[467271](https://dev.azure.com/dnceng-public/public/_build/results?buildId=467271)|dotnet/runtime|[Wasm.Build.Tests.WasmTemplateTests.ConsoleBuildAndRunForSpecificTFM(config: \"Debug\", extraNewArgs: \"-f net8.0\", expectedTFM: \"net8.0\")](https://dev.azure.com/dnceng-public/public/_build/results?buildId=467271&view=ms.vss-test-web.build-test-results-tab&runId=10617578&resultId=100100)|dotnet/runtime#94605|
|[466825](https://dev.azure.com/dnceng-public/public/_build/results?buildId=466825)|dotnet/runtime|[Wasm.Build.Tests.IcuTests.FullIcuFromRuntimePackWithInvariant](https://dev.azure.com/dnceng-public/public/_build/results?buildId=466825&view=ms.vss-test-web.build-test-results-tab&runId=10602660&resultId=100098)|dotnet/runtime#94605|
|[465971](https://dev.azure.com/dnceng-public/public/_build/results?buildId=465971)|dotnet/runtime|[Wasm.Build.Tests.MainWithArgsTests.AsyncMainWithArgs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=465971&view=ms.vss-test-web.build-test-results-tab&runId=10582062&resultId=100099)|dotnet/runtime#94605|
|[465523](https://dev.azure.com/dnceng-public/public/_build/results?buildId=465523)|dotnet/runtime|[Wasm.Build.Tests.BuildPublishTests.BuildThenPublishWithAOT](https://dev.azure.com/dnceng-public/public/_build/results?buildId=465523&view=ms.vss-test-web.build-test-results-tab&runId=10568490&resultId=100098)||
|[465312](https://dev.azure.com/dnceng-public/public/_build/results?buildId=465312)|dotnet/runtime|[Wasm.Build.Tests.TestAppScenarios.SatelliteLoadingTests.LoadSatelliteAssembly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=465312&view=ms.vss-test-web.build-test-results-tab&runId=10565744&resultId=100101)|dotnet/runtime#94516|
|[465301](https://dev.azure.com/dnceng-public/public/_build/results?buildId=465301)|dotnet/runtime|[Wasm.Build.Tests.WasmSIMDTests.Build_NoAOT_ShouldNotRelink](https://dev.azure.com/dnceng-public/public/_build/results?buildId=465301&view=ms.vss-test-web.build-test-results-tab&runId=10564508&resultId=100099)||
|[464819](https://dev.azure.com/dnceng-public/public/_build/results?buildId=464819)|dotnet/runtime|[Wasm.Build.Tests.WasmSIMDTests.PublishWithSIMD_AOT](https://dev.azure.com/dnceng-public/public/_build/results?buildId=464819&view=ms.vss-test-web.build-test-results-tab&runId=10546792&resultId=100094)|dotnet/runtime#94033|
|[464329](https://dev.azure.com/dnceng-public/public/_build/results?buildId=464329)|dotnet/runtime|[Wasm.Build.Tests.WasmTemplateTests.ConsoleBuildAndRunForSpecificTFM(config: \"Debug\", extraNewArgs: \"-f net8.0\", expectedTFM: \"net8.0\")](https://dev.azure.com/dnceng-public/public/_build/results?buildId=464329&view=ms.vss-test-web.build-test-results-tab&runId=10531072&resultId=100102)||
|[464303](https://dev.azure.com/dnceng-public/public/_build/results?buildId=464303)|dotnet/runtime|[Wasm.Build.Tests.WasmTemplateTests.ConsoleBuildAndRunForSpecificTFM(config: \"Debug\", extraNewArgs: \"-f net8.0\", expectedTFM: \"net8.0\")](https://dev.azure.com/dnceng-public/public/_build/results?buildId=464303&view=ms.vss-test-web.build-test-results-tab&runId=10531084&resultId=100098)|dotnet/runtime#94516|
|[464117](https://dev.azure.com/dnceng-public/public/_build/results?buildId=464117)|dotnet/runtime|[Wasm.Build.Tests.WasmTemplateTests.ConsoleBuildAndRunForSpecificTFM(config: \"Debug\", extraNewArgs: \"-f net8.0\", expectedTFM: \"net8.0\")](https://dev.azure.com/dnceng-public/public/_build/results?buildId=464117&view=ms.vss-test-web.build-test-results-tab&runId=10527060&resultId=100100)||
|[463909](https://dev.azure.com/dnceng-public/public/_build/results?buildId=463909)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.WorkloadTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=463909&view=ms.vss-test-web.build-test-results-tab&runId=10522582&resultId=100149)|dotnet/runtime#93915|
|[463897](https://dev.azure.com/dnceng-public/public/_build/results?buildId=463897)|dotnet/runtime|[Wasm.Build.Tests.WasmSIMDTests.PublishWithoutSIMD_AOT](https://dev.azure.com/dnceng-public/public/_build/results?buildId=463897&view=ms.vss-test-web.build-test-results-tab&runId=10523790&resultId=100093)|dotnet/runtime#94035|
|[463891](https://dev.azure.com/dnceng-public/public/_build/results?buildId=463891)|dotnet/runtime|[Wasm.Build.Tests.ConfigSrcTests.ConfigSrcAbsolutePath](https://dev.azure.com/dnceng-public/public/_build/results?buildId=463891&view=ms.vss-test-web.build-test-results-tab&runId=10520904&resultId=100101)|dotnet/runtime#94032|
|[463888](https://dev.azure.com/dnceng-public/public/_build/results?buildId=463888)|dotnet/runtime|[Wasm.Build.Tests.WasmTemplateTests.ConsoleBuildAndRunForSpecificTFM(config: \"Debug\", extraNewArgs: \"-f net8.0\", expectedTFM: \"net8.0\")](https://dev.azure.com/dnceng-public/public/_build/results?buildId=463888&view=ms.vss-test-web.build-test-results-tab&runId=10521106&resultId=100099)|dotnet/runtime#94031|
|[463866](https://dev.azure.com/dnceng-public/public/_build/results?buildId=463866)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.WorkloadTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=463866&view=ms.vss-test-web.build-test-results-tab&runId=10520194&resultId=100149)||
|[463894](https://dev.azure.com/dnceng-public/public/_build/results?buildId=463894)|dotnet/runtime|[Wasm.Build.Tests.Blazor.AppsettingsTests.FileInVfs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=463894&view=ms.vss-test-web.build-test-results-tab&runId=10518766&resultId=100101)|dotnet/runtime#94033|
|[463558](https://dev.azure.com/dnceng-public/public/_build/results?buildId=463558)|dotnet/runtime|[Wasm.Build.Tests.TestAppScenarios.LazyLoadingTests.FailOnMissingLazyAssembly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=463558&view=ms.vss-test-web.build-test-results-tab&runId=10515074&resultId=100100)|dotnet/runtime#94520|
|[456390](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456390)|dotnet/runtime|[Wasm.Build.Tests.WasmSIMDTests.PublishWithoutSIMD_AOT](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456390&view=ms.vss-test-web.build-test-results-tab&runId=10276200&resultId=100099)|dotnet/runtime#94031|
|[456530](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456530)|dotnet/runtime|[Wasm.Build.Tests.NativeBuildTests.SimpleNativeBuild](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456530&view=ms.vss-test-web.build-test-results-tab&runId=10276004&resultId=100099)||
|[456406](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456406)|dotnet/runtime|[Wasm.Build.Tests.RebuildTests.NoOpRebuild](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456406&view=ms.vss-test-web.build-test-results-tab&runId=10274292&resultId=100101)|dotnet/runtime#94035|
|[456397](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456397)|dotnet/runtime|[Wasm.Build.Tests.SatelliteAssembliesTests.ResourcesFromProjectReference](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456397&view=ms.vss-test-web.build-test-results-tab&runId=10273746&resultId=100099)|dotnet/runtime#94033|
|[456393](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456393)|dotnet/runtime|[Wasm.Build.Tests.WasmRunOutOfAppBundleTests.RunOutOfAppBundle](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456393&view=ms.vss-test-web.build-test-results-tab&runId=10273510&resultId=100095)|dotnet/runtime#94032|
|[456020](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456020)|dotnet/runtime|[Wasm.Build.Tests.WorkloadTests.FilesInUnixFilesPermissionsXmlExist](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456020&view=ms.vss-test-web.build-test-results-tab&runId=10265796&resultId=100101)|dotnet/runtime#94196|
|[448681](https://dev.azure.com/dnceng-public/public/_build/results?buildId=448681)|dotnet/runtime|[Wasm.Build.NativeRebuild.Tests.NoopNativeRebuildTest.NoOpRebuildForNativeBuilds](https://dev.azure.com/dnceng-public/public/_build/results?buildId=448681&view=ms.vss-test-web.build-test-results-tab&runId=10051252&resultId=100101)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|12|30|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=448681
**Error message validated:** `Expected the multithreading runtime pack to be available when running on CI`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 10/25/2023 4:57:34 PM UTC

**Comment by carlossanlop** [comment]
From our chat conversation, my understanding is that there is another failure with the same root cause but different error messages and this KnownBuildError is not including those. To make it easier, I'll open a _new_ issue but mention it's related to this. I just want to make sure we have the failure tagged.

**Comment by radical** [comment]
This is fixed now, thanks to @lewing and @carlossanlop !
