### ISSUE TITLE
Consider allowing user-defined PrintMembers via extension method for sealed types 

### ISSUE THREAD

**Issue by oising** [dotnet/runtime#93934]
The C# record `ToString` implementation is very useful to display human readable contents of records easily, but it won't dump the contents of enumerables because these types defer to `object.ToString` and as such dump the type name. For types like `List<T>`, it's easy to derive a new type and override `ToString`, or provide a `PrintMembers(StringBuilder)` implementation yourself. But for sealed types like `ImmutableList<T>`, this is not possible. It seems that the use of immutable collections in records is far more frequent than mutable ones and so a hole remains in coverage, IMO.

This issue was partially discussed at https://github.com/dotnet/runtime/issues/47235 where it was suggested to retroactively add support to immutable collections, but it was (rightly) pointed out that this may lead to leakage of sensitive information. So, I suggest an opt-in model with extension methods:

```csharp

public static class ImmutableExtensions {
    public static void PrintMembers(this ImmutableList<Foo> self, StringBuilder builder) { ... }
}
```

**Comment by huoyaoyuan** [comment]
Extension methods can't be called like virtual or interface method, since they can't be late bounded.

The new C# extension to implement interface for existing type may unblock this, but the feature is still in early designing.

**Comment by oising** [comment]
> Extension methods can't be called like virtual or interface method, since they can't be late bounded.

Right, but I thought ToString handling was source generated for records? If not, then yes, it couldn't work (unless a source generator was introduced)

**Comment by huoyaoyuan** [comment]
The body of ToString is generated by compiler at the compilation of the assembly containing the record. Nothing can be involved afterwards.

**Comment by eiriktsarpalis** [comment]
The benefit of having printable collections comes from composing these types with records, i.e.
```C#
Console.WriteLine(new MyRecord([1, 2, 3])); // MyRecord { Values = [1, 2, 3] }

public record MyRecord(List<int> Values);
```
In that sense if we do address this eventually I would prefer it if we had a solution along the lines of https://github.com/dotnet/runtime/issues/47235. Arguably though that will never happen out of breaking change concerns, or perhaps it could be added as an opt-in feature switch.
