### ISSUE TITLE
.NET 8 slight different result in DateTime.UnixEpoch.AddSeconds(double)

### ISSUE THREAD

**Issue by normj** [dotnet/runtime#93937]
### Description

While updating unit tests to target .NET 8 RC2 I noticed a very small difference when working with UnixEpochs.

If I use the the value for `1480841523.477` as seconds to add to a UnixEpoch I get ticks of `636164383234770000` with .NET 6 and for .NET 8 I get `636164383234769999`. 

I know the difference is very small and is probably a rounding error but a change between versions makes me nervous what impact this might have on users. 

### Reproduction Steps

Using project file
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net6.0;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
```

and code

```csharp
var doubleSeconds = 1480841523.477;

#if NET8_0
Console.WriteLine(".NET 8: " + DateTime.UnixEpoch.AddSeconds(doubleSeconds).Ticks);
#elif NET6_0
Console.WriteLine(".NET 6: " + DateTime.UnixEpoch.AddSeconds(doubleSeconds).Ticks);
#endif
```

Here is my output running in both .NET 6 and .NET 8

```
> dotnet run -c Release -f net6.0
Hello, World!
.NET 6: 636164383234770000
 ~\source\repos\TicksDifference\TicksDifference
> dotnet run -c Release -f net8.0
Hello, World!
.NET 8: 636164383234769999
 ~\source\repos\TicksDifference\TicksDifference
>
```

### Expected behavior

The computed value for ticks should be the same between .NET 6 and .NET 8

### Actual behavior

The values are one tick different

### Regression?

Yes

### Known Workarounds

In my case I can update my tests to handle rounding. I'm just think this is worth an investigation on why this happening and is there a bigger issue. It reminds me of the 90s Pentium bug :smile:

**Comment by tarekgh** [comment]
This is a breaking change we have made in .NET 7.0 https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/7.0/datetime-add-precision. You may look at the comment https://github.com/dotnet/runtime/issues/78452#issuecomment-1318803247 for more info. The original change is made for better precision to address issues like https://github.com/dotnet/runtime/issues/66815.

**Comment by normj** [comment]
> This is a breaking change we have made in .NET 7.0 https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/7.0/datetime-add-precision. You may look at the comment [#78452 (comment)](https://github.com/dotnet/runtime/issues/78452#issuecomment-1318803247) for more info. The original change is made for better precision to address issues like #66815.

Perfect, thanks for the information.
