### ISSUE TITLE
Metric description for `http.client.request.duration` does not match the spec

### ISSUE THREAD

**Issue by vishweshbankwar** [dotnet/runtime#93945]
### Description

Metric description on `http.client.request.duration` does not match the spec description
https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-metrics.md#metric-httpclientrequestduration
<html>
<body>

Name | Instrument Type | Unit (UCUM) | Description
-- | -- | -- | --
http.client.request.duration | Histogram | s | Duration of HTTP client requests.

</body>
</html>

Src link:
https://github.com/dotnet/runtime/blob/b09e18e8b6092e35611c2567bd55e8909ea78d7d/src/libraries/System.Net.Http/src/System/Net/Http/Metrics/MetricsHandler.cs#L29-L32

### Reproduction Steps

NA

### Expected behavior

Description matches with spec

### Actual behavior

Description does not match

**Comment by danmoseley** [comment]
Cc @JamesNK

**Comment by JamesNK** [comment]
Worth changing but low priority. Can happen in 9.

**Comment by MihaZupan** [comment]
Triage: We should update the description to match the spec, but the current wording is also understandable, so this can happen anytime. Marking it as up for grabs since it should be a trivial change.

**Comment by danmoseley** [comment]
Want to offer the PR @vishweshbankwar ?

**Comment by vishweshbankwar** [comment]
opened https://github.com/dotnet/runtime/pull/94061.
