### ISSUE TITLE
Empty string Deserialize can null Enum with System.Text.Json

### ISSUE THREAD

**Issue by zhangzw218** [dotnet/runtime#93960]
Because of the legacy of history, in my code, there are a lot of front-end to pass empty strings to the back end, and the back end automatically converts to int? enum? long?

Now that I've upgraded to System.Text.Json, this conversion is starting to break.

Because you don't know how big the scope is, it's hard to get the front end to modify it.

Is there a way to automatically convert an empty string to null in the back end?

**Comment by huoyaoyuan** [comment]
A custom converter for `SomeEnum?` may be sufficient. Note that there's a difference between `null` and `""` in json.

**Comment by eiriktsarpalis** [comment]
Here's a solution using a custom converter acting on all nullable enums. Note, this won't work in Native AOT since it's using `Type.MakeGenericType` calls - a generic variant of the same factory type would be needed in that case.
```C#
using System.Diagnostics;
using System.Text.Json;
using System.Text.Json.Serialization;

var options = new JsonSerializerOptions { Converters = { new IgnoreEmptyStringNullableEnumConverter() } };
var result = JsonSerializer.Deserialize<MyEnum?>("\"\"", options);
Console.WriteLine(result is null); // True

public enum MyEnum { Value1, Value2 };

public class IgnoreEmptyStringNullableEnumConverter : JsonConverterFactory
{
    public override bool CanConvert(Type typeToConvert)
    {
        if (!typeToConvert.IsValueType || 
            !typeToConvert.IsGenericType ||
            typeToConvert.GetGenericTypeDefinition() != typeof(Nullable<>))
        {
            return false;
        }

        Type underlyingType = typeToConvert.GetGenericArguments()[0];
        return underlyingType.IsEnum; // Replace with whatever check is appropriate
    }

    public override JsonConverter? CreateConverter(Type typeToConvert, JsonSerializerOptions options)
    {
        Debug.Assert(CanConvert(typeToConvert));
        Type underlyingType = typeToConvert.GetGenericArguments()[0];
        Type converterType = typeof(IgnoreEmptyStringNullableEnumConverter<>).MakeGenericType(underlyingType);
        JsonConverter underlyingConverter = options.GetConverter(underlyingType);
        return (JsonConverter)Activator.CreateInstance(converterType, underlyingConverter)!;
    }
}

public class IgnoreEmptyStringNullableEnumConverter<T>(JsonConverter<T> underlyingConverter) : JsonConverter<T?>
    where T : struct
{
    public override T? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader is { TokenType: JsonTokenType.Null }
                   or { TokenType: JsonTokenType.String, ValueSpan.Length: 0 })
        {
            return null;
        }

        return underlyingConverter.Read(ref reader, typeof(T), options);
    }

    public override void Write(Utf8JsonWriter writer, T? value, JsonSerializerOptions options)
    {
        if (value is null)
        {
            writer.WriteNullValue();
            return;
        }

        underlyingConverter.Write(writer, value.Value, options);
    }
}
```

**Comment by zhangzw218** [comment]
> A custom converter for may be sufficient. Note that there's a difference between and in json.`SomeEnum?``null``""`

I wrote a StringToLongNull and StringToIntNull, and then write StringToEnumNull encountered a problem, debug a few hours did not solve, to github asked, is there a global jsonConverter to solve this problem.

**Comment by zhangzw218** [comment]
> Here's a solution using a custom converter acting on all nullable enums. Note, this won't work in Native AOT since it's using `Type.MakeGenericType` calls - a generic variant of the same factory type would be needed in that case.
> 
> ```cs
> using System.Diagnostics;
> using System.Text.Json;
> using System.Text.Json.Serialization;
> 
> var options = new JsonSerializerOptions { Converters = { new IgnoreEmptyStringNullableEnumConverter() } };
> var result = JsonSerializer.Deserialize<MyEnum?>("\"\"", options);
> Console.WriteLine(result is null); // True
> 
> public enum MyEnum { Value1, Value2 };
> 
> public class IgnoreEmptyStringNullableEnumConverter : JsonConverterFactory
> {
>     public override bool CanConvert(Type typeToConvert)
>     {
>         if (!typeToConvert.IsValueType || 
>             !typeToConvert.IsGenericType ||
>             typeToConvert.GetGenericTypeDefinition() != typeof(Nullable<>))
>         {
>             return false;
>         }
> 
>         Type underlyingType = typeToConvert.GetGenericArguments()[0];
>         return underlyingType.IsEnum; // Replace with whatever check is appropriate
>     }
> 
>     public override JsonConverter? CreateConverter(Type typeToConvert, JsonSerializerOptions options)
>     {
>         Debug.Assert(CanConvert(typeToConvert));
>         Type underlyingType = typeToConvert.GetGenericArguments()[0];
>         Type converterType = typeof(IgnoreEmptyStringNullableEnumConverter<>).MakeGenericType(underlyingType);
>         JsonConverter underlyingConverter = options.GetConverter(underlyingType);
>         return (JsonConverter)Activator.CreateInstance(converterType, underlyingConverter)!;
>     }
> }
> 
> public class IgnoreEmptyStringNullableEnumConverter<T>(JsonConverter<T> underlyingConverter) : JsonConverter<T?>
>     where T : struct
> {
>     public override T? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
>     {
>         if (reader is { TokenType: JsonTokenType.Null }
>                    or { TokenType: JsonTokenType.String, ValueSpan.Length: 0 })
>         {
>             return null;
>         }
> 
>         return underlyingConverter.Read(ref reader, typeof(T), options);
>     }
> 
>     public override void Write(Utf8JsonWriter writer, T? value, JsonSerializerOptions options)
>     {
>         if (value is null)
>         {
>             writer.WriteNullValue();
>             return;
>         }
> 
>         underlyingConverter.Write(writer, value.Value, options);
>     }
> }
> ```


Thank you very much. This is a very good method.

When I changed (return underlyingType.IsEnum) to (return underlyingType.IsValueType), it solved all my problems
