### ISSUE TITLE
100GB memory usage in .NET 8 RC-2 and RC-1

### ISSUE THREAD

**Issue by albahari** [dotnet/runtime#93966]
### Description

I have a WPF/WinForms application that has been running without issue on every .NET version since .NET 3.1, on > 100,000 machines. On .NET 8 RC-2, however, I have run into a very strange issue during testing. After around a minute of use, memory usage spikes from its usual 200MB-300MB to a figure that ranges from a few GB to 100GB. In the worst cases, this leads to system-wide memory starvation, with the whole computer almost freezing. A few seconds to a couple of minutes later, memory consumption starts to drop, and eventually reduces back to 200-300MB.

Here's what I've found so far:	

- Visual Studio memory profiler crashes with a NRE when trying to diagnose the issue.
- Red Gate ANTS Memory Profiler shows the excess memory consumption to be in the unmanaged heap.
- Specifically, ANTS claims that the excess unmanaged memory was allocated by the coreclr module. To test the validity of this claim, I tried allocating 1GB of memory with Marshall.AllocHGlobal and ANTS correctly showed this as "Unmanaged memory allocated by managed code".
- The issue occurs on X64, ARM64, and X86.
- On X86, the peak memory spike is limited to 1-2GB, and is released much more quickly.
- I have reproduced the problem on two X64 Win11 machines, one ARM64 Win11 machine, and an X64 Hyper-V instance running Win10. I have not successfully reproduced this on Windows Sandbox.
- Disabling Windows Antivirus doesn't make any difference.
- The Visual Studio CPU profiling tool shows no significant function calls during the memory spiking period.
- Today, I tried installing every .NET 8 preview from Preview 1 to RC-2 to see at what point the issue started. It seems that it started between Preview.7 and RC-1.

### Reproduction Steps

I'm as yet unable to reproduce this problem with a simple WPF app - it seems to require an app with some complexity. I've tried disabling various modules in an attempt to isolate a specific trigger, but no success so far.
 
There is of course a possibility that something in my code that's triggering this. If so, how do I go about diagnosing it? What kinds of things could I do (wrong) in order to create this scenario? And why would it show up only from .NET 8 RC-1?

### Expected behavior

See above

### Actual behavior

See above

### Regression?

Yes

### Configuration

See above

### Other information

![image](https://github.com/dotnet/runtime/assets/4536177/6d200d8f-b1ac-44e5-947e-89d057848690)

**Comment by jakobbotsch** [comment]
This looks like a very likely duplicate of #93342 and #93520 in which case the issue has been fixed already and will be part of the GA release of .NET 8.

Are you able to capture and post a stack trace from all threads taken when the memory starts growing? It will allow us to validate that it is indeed that issue.

**Comment by albahari** [comment]
Thanks: I can confirm that this is indeed the tiered compilation issue, and that the newer build fixes it.

**Comment by danmoseley** [comment]
Thanks for the excellent report @albahari and please let us know if you encounter any other problem with the latest builds.
