### ISSUE TITLE
GC.GetConfigurationVariables() not showing 'System.GC.LOHThreshold'

### ISSUE THREAD

**Issue by mdenhoedt** [dotnet/runtime#93963]
### Description

I am investigating a performance degradation after upgrading from .NET 6 to .NET 7. I suspected it could be due to [.NET 7 breaking change: environment variable precedence](https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/7.0/environment-variable-precedence). That's why I want to log the GC settings used.

I haven't figured out the reason of the performance degradation, I am still investigating this. But I already wanted to share the problem I encountered with `GC.GetConfigurationVariables()`.

*EDIT: still don't understand the performance problems I observe with .NET 7. However the same code runs faster in .NET 8 RC2, even when comparing with .NET 6. Therefore I will just wait until .NET 8 is officially released. I still think `GC.GetConfigurationVariables()` needs improvement, to list all GC settings (e.g. `gcLOHThreshold`) even if users didn't override them.*

### Reproduction Steps

I use the following code to log all GC settings:
```csharp
IReadOnlyDictionary<string, object> gcConfig = GC.GetConfigurationVariables();
logger.LogInformation("{GC.GetConfigurationVariables}", JsonConvert.SerializeObject(gcConfig));
```

### Expected behavior

I expect it also logs `gcLOHThreshold`, especially because I have set the following two environment variables:

```yaml
env:
  - name: DOTNET_GCHeapHardLimitPercent
    value: '0x5F'
  - name: DOTNET_GCLOHThreshold
    value: '0x7A120'
```

### Actual behavior

I get the following log with .NET 8 RC2:
```json
{
    "serverGC": true,
    "concurrentGC": true,
    "retainVM": false,
    "noAffinitize": false,
    "gcCpuGroup": false,
    "gcLargePages": false,
    "heapCount": 4,
    "maxHeapCount": 0,
    "gcHeapAffinitizeMask": 0,
    "gcHeapAffinitizeRanges": "",
    "gcHighMemPercent": 0,
    "gcHeapHardLimit": 8160437862,
    "gcHeapHardLimitPercent": 95,
    "gcHeapHardLimitSOH": 0,
    "gcHeapHardLimitLOH": 0,
    "gcHeapHardLimitPOH": 0,
    "gcHeapHardLimitSOHPercent": 0,
    "gcHeapHardLimitLOHPercent": 0,
    "gcHeapHardLimitPOHPercent": 0,
    "gcConserveMem": 0,
    "gcName": "",
    "gcDynamicAdaptationMode": 0
}
```

### Regression?

Not a regression.

In .NET 7 it doesn't correctly log `gcHeapHardLimitPercent`. I found #84198 and #84201 which fixed the problem for `gcHeapHardLimitPercent` in .NET 8 RC 2, but not for `gcLOHThresshold`.

### Known Workarounds

Not that I know of.

### Configuration

On Windows 10 Enterprise x64.

```powershell
> dotnet --version
8.0.100-rc.2.23502.2
```

**Comment by mangod9** [comment]
@mrsharm can you please take a look here?

**Comment by mrsharm** [comment]
Hi @mdenhoedt, can you please confirm if this issue is present in .NET 8? We made a fix there and if needed, we can always port it back to .NET 7. Thanks in advance!

**Comment by mdenhoedt** [comment]
@mrsharm, the 'actual behavior' is observed with .NET 8 RC2, so `gcLOHThreshold` is missing even in .NET 8. I have updated my initial comment to make this more clear. Shouldn't all GC settings (e.g. `gcLOHThreshold`) be listed in the `IReadOnlyDictionary<string, object>` returned by `GC.GetConfigurationVariables()`, even if users don't override the defaults?

The performance problems I mentioned are only observed in .NET 7. My code is slightly faster in .NET 8 RC2 than in .NET 6. So I guess I will wait a few weeks until .NET 8 is officially released.

**Comment by mrsharm** [comment]
Thanks for the details, @mdenhoedt. We'll have a fix for this merged soon: https://github.com/dotnet/runtime/pull/94068
