### ISSUE TITLE
Unneccesary `Task.Run` in Microsoft.Extensions.Hosting.Host

### ISSUE THREAD

**Issue by stevejgordon** [dotnet/runtime#93970]
The [code](https://github.com/dotnet/runtime/blob/v8.0.0-rc.2.23479.6/src/libraries/Microsoft.Extensions.Hosting/src/Internal/Host.cs#L366) used to collect and then `WhenAll` the asynchronous tasks from registered `IHostedLifeycleService`s, dispatches them with `Task.Run` which appears unnecessary. After discussing with @stephentoub, he confirms this can likely be a minor optimisation to avoid this by directly adding the existing task to the list.

cc/ @steveharter

**Comment by steveharter** [comment]
Previous discussion: https://github.com/dotnet/runtime/issues/88603#issuecomment-1665893893

**Comment by joegoldman2** [comment]
Will be fixed by #93949.

**Comment by steveharter** [comment]
@pedrobsaila can you provide detail on why `Task.Run()` was used when adding the concurrent mode in https://github.com/dotnet/runtime/pull/85191.

Was it used to ensure the tasks are truly run concurrently, without any assumptions about the scheduler?

Thanks

**Comment by pentp** [comment]
This `Task.Run` is basically a no-op - the `token` applies only to the running of the lambda, so there's theoretically a way for the cancellation to apply, but it's close to zero and doesn't do what the original author probably thought (it doesn't apply to the returned task). Source: [Task.Run](https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs,0fb2b4d9262599b9).

**Comment by pedrobsaila** [comment]
See https://github.com/dotnet/runtime/pull/84048#issuecomment-1518238553

> I just happened upon this PR and was discussing with @buyaa-n and @stephentoub. Because we are still running Select over a set of async methods StartAsync|StopAsync the synchronous portion of these methods will still run sequentially on the thread calling Task.WhenAll in order to obtain Tasks to then wait on. If you wanted the synchronous portion of these methods to instead run on a background thread (and concurrently) then you'd want to wrap the call of these async methods in Task.Run.

**Comment by steveharter** [comment]
> The code seems different now. It used to be :
> ...
> So Task.Run was wrapping the call StartAndTryToExecuteAsync.

Thanks I see.  The sync portion of the async was concurrent, and now it's not concurrent (only the code after the first await is concurrent now). The advantage of that is that the sync portions have a guaranteed order if there are >1 implementations of `IHostedService` which can be useful and also allows an efficient way to do a noop for the new Starting\Started\Stopping\Stopped without having to wrap in a Task.Run() to call the noop. I suppose existing implementations that don't use an async pattern (and are all sync) may not be compatible with this approach, however.

**Comment by steveharter** [comment]
Fixed with https://github.com/dotnet/runtime/pull/93949
