### ISSUE TITLE
ECDsa.TrySignData(...) returns true, with bytes written == 64 for null values

### ISSUE THREAD

**Issue by brentschmaltz** [dotnet/runtime#93972]
Calling:  ECDsa.TrySignData(data, destination, HashAlgorithmName, DSASignatureFormat.IeeeP1363FixedFieldConcatenation, out bytesWritten);

where:
data =  Encoding.UTF8.GetBytes("foobar");
destination = ((byte[])(null)).AsSpan<byte>();
HashAlgorithmName = HashAlgorithmName.SHA256

returns:
true
bytesWritten == 64;

Crypto siging issue.

**Comment by vcsjones** [comment]
@eerhardt were you intending to fix this, or would you like me to take a look?

**Comment by vcsjones** [comment]
My guess here is that CNG thinks "Oh you are specifying a signature length of zero, you must be trying to ask me how large the signature is. The signature is 132 bytes! I successfully told you the signature size."

From the NCryptSignHash docs

> If this parameter is NULL, this function will calculate the size required for the signature and return the size in the location pointed to by the pcbResult parameter.

If we change `destination` to this:


```C#
Span<byte> destination = stackalloc byte[1].Slice(1);
```

Then it correctly "fails". So This seems like a problem of "Pinning null-ref span results in nullptr".

**Comment by eerhardt** [comment]
> @eerhardt were you intending to fix this, or would you like me to take a look?

No I wasn't. Please take a look if you have time.

**Comment by vcsjones** [comment]
Repros back to .NET 6, so not a recent regression.

**Comment by jkoritzinsky** [comment]
We had a marshaller proposal for this years ago that got shot down. We can easily bring it back for internal usage.

**Comment by vcsjones** [comment]
> We had a marshaller proposal for this years ago that got shot down. We can easily bring it back for internal usage.

Thanks. The fix for this PR is more surgical since we may want to backport it.

Presumably the way to do this then is to [take the existing one](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshalling/SpanMarshaller.cs#L173) and have `GetPinnableReference ` return a ref to some location (doesn't matter where, could be 0x01 or whatever) if the ref is null and the span length is zero.

Does that sound right?

---

Unrelated from my marshaling questions, this issue also impacts DSA and RSA.

**Comment by jkoritzinsky** [comment]
> > We had a marshaller proposal for this years ago that got shot down. We can easily bring it back for internal usage.
> 
> Thanks. The fix for this PR is more surgical since we may want to backport it.
> 
> Presumably the way to do this then is to [take the existing one](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshalling/SpanMarshaller.cs?rgh-link-date=2023-10-25T18%3A24%3A23Z#L173) and have `GetPinnableReference ` return a ref to some location (doesn't matter where, could be 0x01 or whatever) if the ref is null and the span length is zero.
> 
> Does that sound right?

Last time we did this, we took a `ref` to a static byte field or to `Array.Empty<byte>()` so it at least looks like a valid address.

> Unrelated from my marshaling questions, this issue also impacts DSA and RSA.

Good to know

> > doesn't matter where, could be 0x01 or whatever
> 
> Why not Array.Empty?

We can't use `Array.Empty` as-is as that hits the span zero-length normalization. But doing a ref to the first element of Array.Empty is a good idea.

**Comment by vcsjones** [comment]
Re-opening for backport consideration.

**Comment by brentschmaltz** [comment]
Thanks.

**Comment by brentschmaltz** [comment]
left open for backport.

**Comment by vcsjones** [comment]
Closing - the backport has been merged for .NET 8.
