### ISSUE TITLE
.Net 6.0 Application shows error prompt for ".Net Desktop Runtime"

### ISSUE THREAD

**Issue by sourdig** [dotnet/runtime#93977]
### Description

I have an application with target framework ".Net Core 6.0". The application installer is packaged with .Net 6.0.20.
The application install logs show that the .Net runtime was installed properly.
There were some recent OS software upgrades which installed the higher version 6.0.22.
Post this, I am getting following error prompt while launching the app with the message  - 

**ERROR** - **"You must install .Net Desktop Runtime to run this application".**

But the .Net Desktop runtime is already available, I verified from the dotnet install locations.
Also the error prompt is not a blocker, and I can cancel the error dialog and continue with the app.
Can someone help with the root cause for this issue ? 

This is the corresponding error  in Event Viewer - 
Description: A .NET application failed.
Message: A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.22'.

Attached the snapshot for the error dialog - 
![image](https://github.com/dotnet/runtime/assets/140644521/4d1bc05d-1076-4702-bb25-47a770d07ff3)

### Reproduction Steps

Launch the app targeted and build for .Net 6 after .Net upgrade on the machine

### Expected behavior

The app should launch without any error dialog for the need to install .Net Desktop runtime

### Actual behavior

Error dialog shows up asking to install the .Net desktop runtime which is already installed

### Configuration

OS - Windows 10
Application architecture - x86
.Net version - .Net 6.0

**Comment by elinor-fung** [comment]
> Also the error prompt is not a blocker, and I can cancel the error dialog and continue with the app.

This is definitely surprising. We should only be showing the dialog as the final step of the app failing to launch.

I'm also not sure why we end up looking for `hostpolicy` in `C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.22`.

Could you collect and share a host trace of the failure per https://learn.microsoft.com/dotnet/core/tools/dotnet-environment-variables#corehost_trace? Note that it does contain things like file paths from your machine, so only share the full thing if you are comfortable with it.

**Comment by agocke** [comment]
Closing as no-repro
