### ISSUE TITLE
Stock Blazor Wasm template throws exception on some Chrome Android devices when AOT enabled

### ISSUE THREAD

**Issue by akolman** [dotnet/runtime#93980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The stock Blazor Webassembly app provided with NET 8 rc2 fails to load completely in Chrome on some Android devices when AOT is enabled.  App begins to load but gets "An unhandled exception has occurred".  The error from console is:

`blazor.webassembly.js:1 Error: AggregateException_ctor_DefaultMessage (SyntaxError: Unexpected token '<some binary>', "<more binary> 3,2]" is not valid JSON)`

where \<some binary\> and \<more binary\> are some binary binary junk that I couldn't copy.

The site is able to load in other browsers on android where it fails to load on Chrome (e.g. Samsung browser, Firefox).  I've read that static web apps on Azure can't handle content negotiation, but the error seems to happen even when compression is disabled.  App is also able to load on all desktop browsers I've tested, and is able to load on problematic Androids when AOT is disabled.  **This only seems to be an issue with AOT.**

Demo site can be found here:

https://polite-sky-049359510-preview.centralus.4.azurestaticapps.net/

and sample project here:

https://github.com/akolman/BTest1

which is just the Blazor Wasm template from NET 8 rc2 deployed as a static web app.  This issue has been present prior to rc's and in previous version of Chrome.  For completeness, the same app with AOT **disabled** can be found here:

https://calm-dune-09b272110-preview.centralus.4.azurestaticapps.net/

Currently I've tested against two Samsung S10e, and a Moto Edge 5g UW, both on Chrome 118.0.5993.80 with same unsuccessful result (although I have not verified console output is identical).

Thanks,

Andrew

### Expected Behavior

Stock blazor wasm app loads on all chrome android devices

### Steps To Reproduce

Open demo app (https://polite-sky-049359510-preview.centralus.4.azurestaticapps.net/) on Samsung S10e
Observe that Blazor exception is thrown

### Exceptions (if any)

blazor.webassembly.js:1 Error: AggregateException_ctor_DefaultMessage (SyntaxError: Unexpected token '<some binary>', "<more binary> 3,2]" is not valid JSON)

### .NET Version

8.0.0-rc.2.23480.2

**Comment by radical** [comment]
cc @pavelsavara @maraf

**Comment by SamMonoRT** [comment]
Assigning to @pavelsavara @maraf @radical for tracking - this is hit in 8.0.RC2 build - please triage and add milestone if planning to backport fix.

**Comment by radical** [comment]
@akolman do you have more of that stack trace? And any other error messages.

@pavelsavara @maraf could this be due to hitting memory limits? Is this how the issue might manifest?

**Comment by akolman** [comment]
> @akolman do you have more of that stack trace? And any other error messages.
> 
> @pavelsavara @maraf could this be due to hitting memory limits? Is this how the issue might manifest?

Is there any additional chrome or Android logging to look at? I can try attaching debug while opening from my phone in the morning, but my guess is the exception doesn't surface there.

Also, interestingly, my phone which previously had no issue is unable to load the site today. No changes or updates that I'm aware of, beyond a one build update of Chrome. Moto G Stylus, Android 11, Chrome 118.

**Comment by akolman** [comment]
Full stack trace from Moto G Stylus:

blazor.webassembly.js:1 Error: AggregateException_ctor_DefaultMessage (SyntaxError: Unexpected token ' ', "                3,2]" is not valid JSON)
    at Jn (dotnet.runtime.8.0.0-rc.2.23479.6.y1z69fbyqg.js:3:31627)
    at Ul (dotnet.runtime.8.0.0-rc.2.23479.6.y1z69fbyqg.js:3:181804)
    at 02d61b5a:0x1aac12
    at 02d61b5a:0x1ac58b
    at 02d61b5a:0x1b1c58
    at 02d61b5a:0x6592be
    at 02d61b5a:0x6cdf75
    at c7cbb3c6:0x56
    at 02d61b5a:0x6ca5b6
    at 02d61b5a:0x6be2d1
callEntryPoint @ blazor.webassembly.js:1
await in callEntryPoint (async)
rn @ blazor.webassembly.js:1
await in rn (async)
hn @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1

**Comment by akolman** [comment]
This seems to be fixed with either Chrome v119-120 or the November 8.0.0 release.  I updated a personal app to 8.0.0 and no longer see the issue.  However, I no longer see the issue with my demo app, either, which wasn't upgraded.  Chrome has since upgraded, however.  At any rate, I suppose this can be closed, and nice work!
