### ISSUE TITLE
`System.Linq.Queryable.Tests` native crash for `mono_interpreter` `Debian.11.Amd64`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#93990]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=450804
Build error leg or test failing: System.Linq.Queryable.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/93968

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "RunTests.sh:.*Aborted.*core dumped.*System.Linq.Queryable.Tests",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=450804
**Error message validated:** `RunTests.sh:.*Aborted.*core dumped.*System.Linq.Queryable.Tests`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 10/25/2023 7:14:52 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[710955](https://dev.azure.com/dnceng-public/public/_build/results?buildId=710955)|dotnet/runtime|[System.Linq.Queryable.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=710955&view=ms.vss-test-web.build-test-results-tab&runId=17767660&resultId=120032)|dotnet/runtime#103607|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|1|

**Comment by BrzVlad** [comment]
This was probably fixed by https://github.com/dotnet/runtime/pull/100832
