### ISSUE TITLE
CoreCLR replaces methods in BitConverter with a exteremely slower version

### ISSUE THREAD

**Issue by jasonkuo41** [dotnet/runtime#94001]
BitConverter method double / float <-> ulong / uint gets replaced by a slower method in CoreCLR JIT implementation than the C# source code.

This also affects the performance of BinaryPrimitives double / float endian reading method.

### Description

The affected methods in `System.BitConverter` are as follow:
```cs
[Intrinsic]
public static unsafe ulong DoubleToUInt64Bits(double value) => *((ulong*)&value);
[Intrinsic]
public static unsafe double UInt64BitsToDouble(ulong value) => *((double*)&value);
[Intrinsic]
public static unsafe uint SingleToUInt32Bits(float value) => *((uint*)&value);
[Intrinsic]
public static unsafe float UInt32BitsToSingle(uint value) => *((float*)&value);
```

The slower implementation for JIT in `runtime/src/coreclr/jit/utils.cpp` are as follow: 
```cpp
double BitOperations::UInt64BitsToDouble(uint64_t value)
{
    double result;
    memcpy(&result, &value, sizeof(uint64_t));
    return result;
}
//Other similar methods have the same issues, omitted for brevity
```
Instead of directly casting the pointers like the C# version, instead `memcpy` is invoked, which creates a copy of the value instead. 
This, in turn, caused the C# implementation to be actually 12 times faster than the replaced method.
```
.NET SDK 7.0.202
  [Host]     : .NET 7.0.4 (7.0.423.11508), X64 RyuJIT AVX2
  DefaultJob : .NET 7.0.4 (7.0.423.11508), X64 RyuJIT AVX2

| Method          | Mean      | Error     | StdDev    | Ratio | RatioSD |
|---------------- |----------:|----------:|----------:|------:|--------:|
| BitConverterVer | 0.5341 ns | 0.0176 ns | 0.0147 ns |  1.00 |    0.00 |
| UnsafeVer       | 0.0428 ns | 0.0205 ns | 0.0182 ns |  0.08 |    0.03 |
```

Placing the code on [sharplabs](https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzmAPgAQEwEYCwAUJgAwAEmuAdAEoCuMCUYAplQMID2YADlADYsATgGVhANygBjFigDcRTAGYK2MuzIBvImV0UVlAGxkGKCADMWZACac6wQWQCSjQwBYAQlAQoAKpwAROwcWAAp+ThgAczJxCH46FgBKMgBeAD4yACpQ0Nt7QSykgDI4hOSFQj19ClxjUwsrfJDnV09vP0DgwQBVGDNLcMiYssSUjLI+gbYAQRQAHgjouBtulnTQoRZzWPixyurlWvr+xtWCqxcEdy8ffyCL264YcWEEYSHo3fLxzKfI15Cd5CKhXG4de5rUKjCpEAC+QA=) to confirm that the output JIT asm did include some unnecessary instructions.
```asm
C.Int64BitsToDoubleUnsafe(Int64)
    L0000: sub esp, 8
    L0003: vzeroupper
    L0006: vmovsd xmm0, [esp+0xc]
    L000c: vmovsd [esp], xmm0
    L0011: fld st, qword ptr [esp]
    L0014: add esp, 8
    L0017: ret 8

C.Int64BitsToDoubleBitConverter(Int64)
    L0000: sub esp, 0x10
    L0003: vzeroupper
    L0006: mov eax, [esp+0x14]
    L000a: mov edx, [esp+0x18]
    L000e: mov [esp], eax
    L0011: mov [esp+4], edx
    L0015: vmovsd xmm0, [esp]
    L001a: vmovsd [esp+8], xmm0
    L0020: fld st, qword ptr [esp+8]
    L0024: add esp, 0x10
    L0027: ret 8
```

### Analysis / Solution
Replace `memcpy` with simple `reinterpret_cast`
```cpp
double BitOperations::UInt64BitsToDouble(uint64_t value)
{
    return *reinterpret_cast<double*>(&value);
}
//Other similar methods have the same issues, omitted for brevity
```

Let me know if there's a reason memcpy was used instead. 
Should be a relatively easy fix, I can create a PR for it if needed.

**Comment by huoyaoyuan** [comment]
Current code in BitConverter is using `Unsafe.BitCast`:

https://github.com/dotnet/runtime/blob/db558253fbd598ed682272c736ae6102673bd921/src/libraries/System.Private.CoreLib/src/System/BitConverter.cs#L899-L900

The C++ version isn't used for the intrinsic. JIT inserts bit cast node directly:

https://github.com/dotnet/runtime/blob/db558253fbd598ed682272c736ae6102673bd921/src/coreclr/jit/importercalls.cpp#L3813-L3835

It's indeed 64 bit value handling on 32 bit platform. The code quality on x64 is fine.

> Should be a relatively easy fix, I can create a PR for it if needed.

No, it is a hard problem in JIT.

**Comment by En3Tho** [comment]
You link to sharplab points to x86 version of the code. X64 codegen is completely different

**Comment by MichalPetryka** [comment]
1. The methods you linked are for internal runtime use, they're not used for the intrinsics.
2. 
> ```c++
> *reinterpret_cast<double*>(&value);
> ```
Such casting is UB in C++, you have to either use memcpy or bit_cast there.
3. The assembly you provided is for x86, which is not a performance improvement priority, especially with 64bit data types.
4. In .Net 8 all of your samples provide the same codegen, although slightly regressed from .Net 7:
```asm
G_M000_IG01:                ;; offset=0x0000
       push     ebp
       mov      ebp, esp
       sub      esp, 8
       vzeroupper 
G_M000_IG02:                ;; offset=0x0009
       vmovsd   xmm0, qword ptr [ebp+0x08]
       vmovsd   qword ptr [ebp-0x08], xmm0
       fld      qword ptr [ebp-0x08]
G_M000_IG03:                ;; offset=0x0016
       mov      esp, ebp
       pop      ebp
       ret      8
```

**Comment by EgorBo** [comment]
X64 .NET 8.0 codegen for your sharplab snippet:
```asm
; Method C:Int64BitsToDouble(long):double (FullOpts)
G_M54004_IG01:  ;; offset=0x0000
       vzeroupper 
G_M54004_IG02:  ;; offset=0x0003
       vmovd    xmm0, rcx
G_M54004_IG03:  ;; offset=0x0008
       ret      
; Total bytes of code: 9

; Method C:Int64BitsToDoubleUnsafe(long):double (FullOpts)
G_M63774_IG01:  ;; offset=0x0000
       vzeroupper 
G_M63774_IG02:  ;; offset=0x0003
       vmovd    xmm0, rcx
G_M63774_IG03:  ;; offset=0x0008
       ret      
						;; size=1 bbWeight=1 PerfScore 1.00
; Total bytes of code: 9

; Method C:Int64BitsToDoubleBitConverter(long):double (FullOpts)
G_M46987_IG01:  ;; offset=0x0000
       vzeroupper 
G_M46987_IG02:  ;; offset=0x0003
       vmovd    xmm0, rcx
G_M46987_IG03:  ;; offset=0x0008
       ret      
; Total bytes of code: 9
```

Can the issue be closed as it seems it's already answered?

**Comment by tannergooding** [comment]
> Can the issue be closed as it seems it's already answered?

I think so, there's potentially a 32-bit (x86) improvement to be made. That would require us to add decomp support to the bitcast, but I think that can/should be tracked seperately.
