### ISSUE TITLE
[MT][browser] `TestCancelAsync` failure

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#94050]
Failing after enabling all MT library tests (https://github.com/dotnet/runtime/pull/91536). [log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-93596-merge-630d961119a8405b98/WasmTestOnBrowser-System.ComponentModel.EventBasedAsync.Tests/1/console.a1c059dc.log?helixlogtype=result)

```
[FAIL] System.ComponentModel.EventBasedAsync.Tests.BackgroundWorkerTests.TestCancelAsync
info: Assert.True() Failure
info: Expected: True
info: Actual:   False
info:    at System.ComponentModel.EventBasedAsync.Tests.BackgroundWorkerTests.TestCancelAsync()
info:    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
info:    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by pavelsavara** [comment]
Does this still happen after https://github.com/dotnet/runtime/pull/94214 ?
If so, it would be good to find root cause.
