### ISSUE TITLE
[wasm] Runtime tests' build gets terminated with `exited with code 137`

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#94077]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=452279
Build error leg or test failing: Build / browser-wasm linux Release AllSubsets_Mono_RuntimeTests monointerpreter / Build Tests
Pull request: https://github.com/dotnet/runtime/pull/94064, https://github.com/dotnet/runtime/pull/94056

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "exited with code 137.",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

log:
```
   Regressions -> /__w/1/s/artifacts/tests/coreclr/browser.wasm.Release/Regressions/Regressions/browser-wasm/publish/
  /__w/1/s/dotnet.sh: line 27: 35452 Killed                  ${dotnetPath} "$@"
/__w/1/s/src/tests/build.proj(610,5): error MSB3073: The command ""/__w/1/s/dotnet.sh" msbuild /__w/1/s/src/tests/build.proj /t:Build "/p:TargetArchitecture=wasm" "/p:Configuration=Release" "/p:LibrariesConfiguration=Release" "/p:TasksConfiguration=Release" "/p:TargetOS=browser" "/p:ToolsOS=" "/p:PackageOS=" "/p:RuntimeFlavor=mono" "/p:RuntimeVariant=monointerpreter" "/p:CLRTestBuildAllTargets=" "/p:UseCodeFlowEnforcement=" "/p:__TestGroupToBuild=3" "/p:__SkipRestorePackages=1" /nodeReuse:false /m:1 /bl:/__w/1/s/artifacts//log/Release/InnerManagedTestBuild.3.binlog" exited with code 137.

```

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[622813](https://dev.azure.com/dnceng-public/public/_build/results?buildId=622813)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/622813/logs/1639)|dotnet/runtime#100266|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|1|

 ### Known issue validation
**Build: :mag_right:** 
**Result validation:** :warning: Provided build not found. Provide a valid build in the "**Build:** :mag_right:" line.
**Validation performed at:** 3/4/2024 8:25:30 AM UTC

**Comment by lewing** [comment]
This time of failure is usually due to hitting container memory limits

**Comment by lewing** [comment]
Many lanes across coreclr and mono are hitting container limits and getting a 137 exit code.  137 in a container is kill -9 + 128 from the container and is a generic failure, there isn't much value in adding the test name and making it more specific.
