### ISSUE TITLE
When debugging in Roslyn-generated assembly in Visual Studio, it reports that the source file is different from the module was built.

### ISSUE THREAD

**Issue by dmitry-medvedev** [dotnet/runtime#94074]
### Description

We use Roslyn to dynamically compile C# code into the DLL. If we try to debug this assembly in Visual Studio, it reports that the source file is different from the module was built.  Ignoring this warning allows us to contune debugging.

The same code compiled with CodeDOM works as expected.

### Reproduction Steps

Please run the attached WinForms project under the Visual Studio 2022 debugger. 
Clicking on the CodeDOM button should open the C# file and stop the execution at the following line of code:
System.Diagnostics.Debugger.Break(); 

Clicking on the Roslyn button displays the above warning first, and then if you click Yes in the dialog box, it stops the execution at the following line of code:
System.Diagnostics.Debugger.Break(); 

### Expected behavior

No warning should be displayed.

### Actual behavior

![image](https://github.com/dotnet/runtime/assets/64202511/b85e812f-501c-4361-b902-91493b6431ae)
[DebugSample.zip](https://github.com/dotnet/runtime/files/13184586/DebugSample.zip)

### Known Workarounds

We could not find any workaround. Looking at pdb and dll files generated by CodeDOM and Roslyn, we can see some extra attributes added in the Roslyn-generated library, such as RefSafetyRulesAttribute - this might be the reason for confusing Visual Studio debugger. 

Would be great to find out if there's a workaround for this problem.

**Comment by tommcdon** [comment]
@dmitry-medvedev thanks for opening this issue.  Unfortunately this is not a .NET runtime issue and is instead looks like an issue in Visual Studio.  Please open a [Visual Studio feedback item](https://learn.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) to report this issue.
