### ISSUE TITLE
Bring Windows.Storage namespace into System.IO

### ISSUE THREAD

**Issue by HEIC-to-JPEG-Dev** [dotnet/runtime#94092]
System.IO has great performance, but there are missing parts that only WinRT Windows.Storage can provide - such as 
- GetImagePropertiesAsync
- GetVideoPropertiesAsync

Of course it is possible to use the WinRT versions, but the performance of those is so bad that it can cripple an application.

For example, to enumerate my OneDrive photos folder with 50,000 files take System.IO 0.63s, WinRT takes 1m 17s - getting the dimensions of the photos requires using WinRT because they are sparse files, and that takes 37 minutes.

So, the request is to bring the missing API's for storage into System.IO so that we have performant file access services.

**Comment by HEIC-to-JPEG-Dev** [comment]
That assumes OneDrive, there are also other providers such as iCloud; so it has to be the local System.IO API (or WinRT) as the information is help in the files sparse data. WinRT has a function to see what data is stored locally (dimensions, thumbnail, etc.) then get information without causing a download.

**Comment by HEIC-to-JPEG-Dev** [comment]
So I did some performance work on calling the WinRT disk IO. I used empty projects, one WinUI, the other UWP, the exact same code in both returns massively different performance results. WinUI took 3 minutes vs UWP took 14 seconds. Normal system.IO in WinUI massively outperforms WinRT, but when you **need** WinRT calls, it hits a wall. This is why I want the WinRT call brought over to native .Net - for my project I have to go back to UWP and I miss C#11 and .Net 7 :(

**Comment by jkotas** [comment]
It sounds like a performance issue in WinUI that should be fixed in WinUI. Could you please report it in https://github.com/microsoft/cswinrt or https://github.com/microsoft/microsoft-ui-xaml repos instead?

It does not make sense to introduce app-model specific APIs in .NET BCL to work-around performance issues elsewhere.

**Comment by adamsitnik** [comment]
> It does not make sense to introduce app-model specific APIs in .NET BCL to work-around performance issues elsewhere.

I agree with @jkotas, having said that I am going to close the issue.
