### ISSUE TITLE
Potential perf improvement for Native AOT runtime tests

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#94102]
I was doing some investigation of the latest [runtime-nativeaot-outerloop](https://dev.azure.com/dnceng-public/public/_build?definitionId=265&_a=summary) test runs and noticed that the coreclr tests spent a fair amount of time in the `findvcvarsall.bat` script.

Looking at a binlog...
![image](https://github.com/dotnet/runtime/assets/515774/ed64cf68-b369-4255-829e-23e16b11d354)

That `SetupOSSpecificProps` looks like it's running findvcvarsall, and it's taking ~51 minutes of CPU time. I wonder if we could avoid this by just running the script once and then passing down the relevant variables.

**Comment by jkotas** [comment]
> I wonder if we could avoid this by just running the script once and then passing down the relevant variables.

There is an `IlcUseEnvironmentalTools` env variable to enable this scenario.

**Comment by MichalStrehovsky** [comment]
Already tried this in the past, here's some old context: https://github.com/dotnet/runtime/pull/82080

**Comment by am11** [comment]
We can set `IlcUseEnvironmentalTools=true` along with `CppLinker` and `CppLibCreator` by manually running the script once, then capturing and setting the values in test invocation script (that is dynamically written by runtime's test infra). Unless helix setups differ from instance to instance, that would work by running once on host in the test preparation step. On local dev machine, paths will stay the same during the course of test run.
