### ISSUE TITLE
Exclude properties of delegate types in configuration source generator

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#94117]
Presently, the configuration source generator generates binding code for properties employing `delegate`, `Func`, or `Action` types. However, there is no means to bind configuration to such types. Consequently, the generator generates an abundance of code for all types associated with these delegates, many of which will not be utilized and may lead to code that does not compile. Here's an example:

https://github.com/dotnet/extensions/blob/14943b99572078f1bcf2c51e9507cf2631133fae/src/Libraries/Microsoft.Extensions.Resilience/Resilience/Internal/FailureEventMetricsOptions.cs#L11

This issue is tracking to fix the source generator to skip generating any code for such properties or types.

**Comment by tarekgh** [comment]
CC @eerhardt @ericstj

**Comment by ericstj** [comment]
We should match the exclusions used by JSON: https://github.com/dotnet/runtime/blob/9461f4b5bd036005f37e78516c48b13396f76750/src/libraries/System.Text.Json/gen/JsonSourceGenerator.Parser.cs#L1687C26-L1687C43

**Comment by tarekgh** [comment]
This is now is completed.
