### ISSUE TITLE
PInvoke Source generation stops after first method with `global using`

### ISSUE THREAD

**Issue by Danielku15** [dotnet/runtime#94150]
### Description

When defining a `global using` for the `LibraryImportAttribute` the related source generator only emits the first method with this alias. 

### Reproduction Steps

```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net7.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
</Project>

```

```cs
global using CustomLibraryImport = System.Runtime.InteropServices.LibraryImportAttribute;

namespace PInvokeGenAlias;

using System.Runtime.InteropServices;

public static partial class Example
{
    [LibraryImport("mylib", EntryPoint = "MyFunc")]
    public static partial nint MyFunc();
    
    [LibraryImport("mylib", EntryPoint = "MyFunc2")]
    public static partial nint MyFunc2();
    
    [CustomLibraryImport("mylib", EntryPoint = "MyFunc")]
    public static partial nint MyFuncGlobalAlias();
    
    [CustomLibraryImport("mylib", EntryPoint = "MyFunc")]
    public static partial nint MyFuncGlobalAlias2();
    
    [CustomLibraryImport("mylib", EntryPoint = "MyFunc")]
    public static partial nint MyFunc2GlobalAlias();
}
```

### Expected behavior

The generated pinvoke code should contain partial implementations for all methods. 

### Actual behavior

The source generator only produces code for the first method with the `CustomLibraryImportAttribute`, the others are missing :

```cs
// <auto-generated/>
namespace PInvokeGenAlias
{
    public static unsafe partial class Example
    {
        [System.Runtime.InteropServices.DllImportAttribute("mylib", EntryPoint = "MyFunc", ExactSpelling = true)]
        public static extern partial nint MyFunc();
    }
}
namespace PInvokeGenAlias
{
    public static unsafe partial class Example
    {
        [System.Runtime.InteropServices.DllImportAttribute("mylib", EntryPoint = "MyFunc2", ExactSpelling = true)]
        public static extern partial nint MyFunc2();
    }
}
namespace PInvokeGenAlias
{
    public static unsafe partial class Example
    {
        [System.Runtime.InteropServices.DllImportAttribute("mylib", EntryPoint = "MyFunc", ExactSpelling = true)]
        public static extern partial nint MyFuncGlobalAlias();
    }
}

```

### Known Workarounds

Not changing the name seems to work: 

```
global using LibraryImportAttribute = System.Runtime.InteropServices.LibraryImportAttribute;
```

### Configuration

global.json
```json
{
  "sdk": {
    "version": "7.0.0",
    "rollForward": "latestFeature",
    "allowPrerelease": false
  }
}
```

.net SDK
Windows 11 Pro 22H2
x64

### Other information

I want to multi-target my project to net7.0, net6.0 and netstandard2.0 but the pinvoke source generation only works for net7.0. Therefore I created a custom source generator tailored to my needs. In net7.0 I use the official source generation and for netstandard2.0 and net6.0 I use my custom one. 

For this I introduced a `MyLibLibraryImport` attribute which is either aliased via global usings or pointing to a custom attribute in the lib.

**Comment by huoyaoyuan** [comment]
> For this I introduced a `MyLibLibraryImport` attribute which is either aliased via global usings or pointing to a custom attribute in the lib.

As an alternative, you can define the same `LibraryImportAttribute` under the same namespace, and conditionally opt-out it under `NET7_0_OR_GREATER`.

**Comment by agocke** [comment]
@jkoritzinsky  is this still an issue?

**Comment by jkoritzinsky** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/74468
