### ISSUE TITLE
.NET 8, missing StartsWithAny and EndsWithAny methods in MemoryExtensions

### ISSUE THREAD

**Issue by silkfire** [dotnet/runtime#94155]
I've been looking through the methods located on the [MemoryExtensions](https://learn.microsoft.com/en-us/dotnet/api/system.memoryextensions?view=net-8.0) class, which I'm very excited about, especially the ones ending in `-Any()` (`ContainsAny`, `IndexOfAny`, `SplitAny`), allowing the consumer to supply a list of multiple entries to search for.

I was surprised that the `StartsWith` and `EndsWith` methods don't come with a `StartsWithAny` and `EndsWithAny` equivalent. Is there a reason for this? Is the recommended approach to just use a loop and an `||` (or) statement instead as a workaround?

**Comment by neon-sunset** [comment]
`StartsWithAny` and `EndsWithAny` is already expressible today with e.g. `str is ["hello", ..] or ["world", ..]`.

**Comment by MihaZupan** [comment]
Related: #87689

**Comment by silkfire** [comment]
This would be useful if you want to check a string for a list of prefixes, e.g.

```csharp
if (span.StartsWithAny(listOfPrefixes)) { ... }
```

**Comment by silkfire** [comment]
@MihaZupan  What's the status on this? I saw that .NET 9 will support `SearchValues` with a `string`  - [SearchValues.Create(ReadOnlySpan<string> values, StringComparison comparisonType)](https://learn.microsoft.com/en-us/dotnet/api/system.buffers.searchvalues.create?view=net-9.0#system-buffers-searchvalues-create(system-readonlyspan((system-string))-system-stringcomparison)) - perhaps this API could be added specifically for strings?

**Comment by tannergooding** [comment]
This would need to be updated to be a proper API suggestion following the general template detailed in https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md

Once that happens, this could be marked ready-for-review and taken to API review. I don't expect this would happen for .NET 9 at this point.
