### ISSUE TITLE
There is a difference in the Regex judgment results.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#94156]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/There-is-a-difference-in-the-Regex-judgm/10488451)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:17.7.4]

Hello.

[situation]
There are files "080-5792-0097.pdf" and "A080-5792-0097.pdf" on the desktop.
Of these, I am trying to obtain only "080-5792-0097.pdf".

[question]
When I tried the code below in C#, I noticed that the results were different.
Why is "C:\Users\nishida\Desktop\080-5792-0097.pdf" not set in files2?

[Execution environment]
Windows 11 Professional Japanese version
Visual Studio 2022 Version 17.7.4

---------------------------------------------------------------------------------------
```c#
 List<string> patterns = @"^[0-9]+[-][0-9]+[-][0-9]+.pdf,".Split(',').ToList();
            foreach (var pattern in patterns)
            {
                //
                // Nothing is set in files2.
                //
                var reg = new Regex(pattern);
                string[] files1 = Directory.GetFiles(@"C:\Users\nishida\Desktop")
                                     .Where(delegate (string f)
                                     {
                                         return reg.IsMatch(f);
                                     })
                                     .ToArray();
                Console.WriteLine("");
            }
```
---------------------------------------------------------------------------------------

---
#### Feedback Bot on 10/11/2023, 07:11 AM: 

(private comment, text removed)
#### 建一郎 西田 on 10/11/2023, 09:19 AM: 

(private comment, text removed)
#### Ahmet Ibrahim Aksoy [MSFT] on 10/18/2023, 01:02 PM: 

(private comment, text removed)
#### 建一郎 西田 on 10/19/2023, 02:24 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by danmoseley** [comment]
The pattern looks ok (although it is more typical to use `-` than `[-]`)
Can you use a debugger or log to console what steering is being passed to the Regex.IsMatch? If it's a full path then the `^` will prevent a match.

**Comment by FunFunNishida** [comment]
Hi,
There is something missing in the above code.
The following code is what I reported.

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Test
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {

        }

        private void button1_Click(object sender, EventArgs e)
        {
            Test(sender);
        }

        private void button2_Click(object sender, EventArgs e)
        {
            Test(sender);
        }

        private void Test(object sender)
        {

            List<string> patterns = @"^[0-9]+[-][0-9]+[-][0-9]+.pdf,".Split(',').ToList();

            foreach (var pattern in patterns)
            {
                Button btn = (Button)sender;
                switch (btn.Name)
                {
                    case "button1":

                        //
                        // “C:\Users\nishida\Desktop\080-5792-0097.pdf” is set for files1.
                        //

                        string[] files1 = Directory.GetFiles(@"C:\Users\nishida\Desktop")
                                                   .Where(file => Regex.IsMatch(Path.GetFileName(file), pattern))
                                                   .ToArray();
                        break;

                    case "button2":

                        //
                        // Nothing is set in files2.
                        //

                        var reg = new Regex(pattern);
                        string[] files2 = Directory.GetFiles(@"C:\Users\nishida\Desktop")
                                                   .Where(delegate (string f)
                                                   {
                                                       return reg.IsMatch(f);
                                                   })
                                                   .ToArray();
                        break;
                }
            }
        }
    }
}

**Comment by MihaZupan** [comment]
With `files1`, you're matching against `Path.GetFileName(file)`, so `080-5792-0097.pdf`.
With `files2`, you're matching against `C:\Users\nishida\Desktop\080-5792-0097.pdf`.

The difference isn't between `new Regex(pattern).IsMatch(path)` and `Regex.IsMatch(path, pattern)`, but between using the full path vs just the file name.

**Comment by FunFunNishida** [comment]
danmoseley, MihaZupan

Thank you for your reply!
Below is the code that incorporates the suggested modifications. 
I have confirmed that this code produces the expected results.


                        var reg = new Regex(pattern);
                        //string[] files2 = Directory.GetFiles(@"C:\Users\nishida\Desktop\")
                        //                           .Where(delegate (string f)
                        //                           {
                        //                               return reg.IsMatch(f);
                        //                           })
                        //                           .ToArray();
                        string[] files2 = Directory.GetFiles(@"C:\Users\nishida\Desktop")
                                                   .Where(delegate (string f)
                                                   {
                                                       Console.WriteLine(f);
                                                       return reg.IsMatch(Path.GetFileName(f));
                                                   })
                                                   .ToArray();

**Comment by danmoseley** [comment]
Ok good I will close this then.
