### ISSUE TITLE
Loop Invariant Cause of Perf Drops Of System.Collections.IndexerSet<String>.Span(Size: 512) 

### ISSUE THREAD

**Issue by mayadav1** [dotnet/runtime#94161]
I have observed performance drops for System.Collections.IndexerSet<String>.Span(Size: 512) then I have analyzed the profiler summary of the benchmark and found following source is cause of  performance drops. 
	
Source Line	Source	CPU Time: Total	CPU Time: Self
63	        public T Span()		
64	        {		
65	            T result = default;	2.3%	47.638ms
66	            var collection = new Span<T>(_array);		
67	            for (int i = 0; i < collection.Length; i++)	42.4%	877.120ms
68	                collection[i] = default;	1.6%	32.104ms
69	            return result;		
70	        }

Current ASM code:

Source Line	Assembly	CPU Time: Total	CPU Time: Self
0	Block 39:		
67	xor eax, eax	0.8%	15.780ms
67	cmp dword ptr [rsp+0x30], 0x0		
67	jle 0x7ffe06b6455c <Block 42>		
0	Block 40:		
68	cmp eax, dword ptr [rsp+0x30]		/*  Duplicate Condition    */
68	jnb 0x7ffe06b64564 <Block 43>		
0	Block 41:		
68	mov rcx, qword ptr [rsp+0x28]		
68	mov edx, eax	0.8%	15.953ms
68	xor r8d, r8d		
68	mov qword ptr [rcx+rdx*8], r8		
67	inc eax	40.9%	845.354ms
67	cmp eax, dword ptr [rsp+0x30]		
67	jl 0x7ffe06b64540 <Block 40>	0.8%	15.986ms
0	Block 42:		
69	xor eax, eax		
0	add rsp, 0x40	0.8%	16.206ms
0	pop rbx		
0	ret 		

Block 40 is a duplicate condition which is iterating until loop finish. Isn't an incorrect code? right one should like below.

Expected ASM code:

Source Line	Assembly	CPU Time: Total	CPU Time: Self
0	Block 39:		
67	xor eax, eax	0.8%	15.780ms
67	cmp dword ptr [rsp+0x30], 0x0		
67	jle 0x7ffe06b6455c <Block 42>		
0	Block 40:		
68	cmp eax, dword ptr [rsp+0x30]		/*  Duplicate Condition    */
68	jnb 0x7ffe06b64564 <Block 43>		
0	Block 41:		
68	mov rcx, qword ptr [rsp+0x28]		
68	mov edx, eax	0.8%	15.953ms
68	xor r8d, r8d		
68	mov qword ptr [rcx+rdx*8], r8		
67	inc eax	40.9%	845.354ms
67	cmp eax, dword ptr [rsp+0x30]		
67	jl 0x7ffe06b64540 <Block 41>	0.8%	15.986ms  /* Hand made change, I am expecting code look like it*/
0	Block 42:		
69	xor eax, eax		
0	add rsp, 0x40	0.8%	16.206ms
0	pop rbx		
0	ret

I am suspecting it cause of performance drops.

Please anyone help me out.

**Comment by AndyAyersMS** [comment]
Do you mean [this benchmark](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_Windows%2010.0.18362%2fSystem.Collections.IndexerSet(Int32).Span(Size%3a%20512).html)?

What kind of drop are you seeing? From our data, performance has been fairly stable over time (windows intel x64):

![newplot - 2023-10-30T101538 854](https://github.com/dotnet/runtime/assets/10121823/cbd04ead-23c2-42ee-b79b-4fa53ea21ba6)

(linux intel x64)

![newplot - 2023-10-30T101731 835](https://github.com/dotnet/runtime/assets/10121823/b4320214-6082-4450-8fd1-c155d6ce4c5f)

**Comment by mayadav1** [comment]
Thanks for the updates!
Yes this benchmark shows perf differences for AMD vs Intel for net8.0. Does your logs show stable comparison net6.0 vs net8.0? I profiled  on my machine and observed  duplicate condition. Does this condition not consume extra cycles?

**Comment by JulieLeeMSFT** [comment]
Ping @AndyAyersMS .

> Thanks for the updates! Yes this benchmark shows perf differences for AMD vs Intel for net8.0. Does your logs show stable comparison net6.0 vs net8.0? I profiled on my machine and observed duplicate condition. Does this condition not consume extra cycles?

**Comment by AndyAyersMS** [comment]
@mayadav1 our tests do not show regressions here. Modern CPUs are pretty good at hiding the cost of correlated branches so it could be the redundancy looks bad but does not impact perf.

If you can provide benchmark results showing an impact, then we can take another look.
