### ISSUE TITLE
[API Proposal]: Add LINQ methods: `TryGetFirst` and `TryGetLast`

### ISSUE THREAD

**Issue by colejohnson66** [dotnet/runtime#94164]
### Background and motivation

When given a collection, sometimes it is desirable to only take the first or last element and discard the rest. In those cases, we have `First()` and `Last()` that will throw on empty enumerables. For non-throwing behavior, there are `FirstOrDefault()` and `LastOrDefault()`. Often, these are sufficient.

Issues are encountered, however, when `default(T)` is a valid value. For example, with classes and `Nullable<T>`, `null` could be a valid element. And with structs, this is even worse if `default(T)` is a usable/valid value. For example, `default(int)` is just zero, which could be the first/last element, and we'd have no way of knowing.

There are a few solutions:
1. Use a `try/catch` (and suffer the performance hit if an exception occurs)
2. Implement the iterator yourself (using `IEnumerator<T>`)
3. Use multiple enumeration
4. (for structs only): Cast `T` to `T?` (i.e. `Nullable<T>`)

The first and second solutions are "inelegant":

```csharp
try
{
    T value = enumerable.First();
    // frob the value
}
catch (InvalidOperationException)
{
    // enumerable was empty
}
```

```csharp
using (IEnumerator<T> e = enumerable.GetEnumerator())
{
    if (e.MoveNext())
    {
        T value = e.Current;
        // frob the value
    }
    else
    {
        // enumerable was empty
    }
}
```

The third solution is not "safe" as some enumerations do not support multiple enumeration, opting to throw an exception when `Reset()` is called:

```csharp
if (enumerable.Any())
{
    T value = enumerable.First(); // multiple enumeration!
    // frob the value
}

// alternatively
if ((enumerable.TryGetNonEnumeratedCount(out int count) && count > 0) || enumerable.Any())
{
    T value = enumerable.First(); // multiple enumeration if `TryGetNonEnumeratedCount` fails!
    // frob the value
}
```

And finally, the fourth solution, which is only for `structs` (that are not already `Nullable<T>`), we can `Cast<T?>()`. This is the most "elegant", but has a slight performance overhead:

```csharp
// when `typeof(T).IsValueType` is `true`
T? value = enumerable
    .Cast<T?>()
    .FirstOrDefault();
if (value is not null)
{
    // frob the value
}

// alternatively
if (enumerable.Cast<T?>().FirstOrDefault() is T value)
{
    // frob the value
}
```

### API Proposal

```csharp
namespace System.Linq;

public static class Enumerable
{
    public static bool TryGetFirst<T>(this IEnumerable<T> source, out T result);
    public static bool TryGetFirst<T>(this IEnumerable<T> source, Func<T, bool> predicate, out T result);

    public static bool TryGetLast<T>(this IEnumerable<T> source, out T result);
    public static bool TryGetLast<T>(this IEnumerable<T> source, Func<T, bool> predicate, out T result);
}
```

### API Usage

```csharp
if (enumerable.TryGetFirst(out T value))
{
    // frob the value
}
```

### Alternative Designs

The alternatives are the four forms presented in the "background" section, or the user implementing these extensions themselves as needed.

### Risks

None.

**Comment by colejohnson66** [comment]
In addition, a `TryGetFirst` (with or without a predicate) would satisfy the need for an `Any` that returns the match as an out parameter.

**Comment by eiriktsarpalis** [comment]
Related to https://github.com/dotnet/runtime/issues/94153. I would rather see this issue resolved once the language gets support for discriminated unions and true optional types. Try-methods aren't particularly amenable to LINQ's composition model, so we try not to add them (the one exception to that rule is `TryGetNonEnumeratedCount`, but that is a helper method serving a somewhat different purpose).

Per https://github.com/dotnet/runtime/issues/94153#issuecomment-1784950488, have you considered using collection pattern matching to address the issue?

**Comment by colejohnson66** [comment]
Understandable. Proper DU types would be great. Then an `Option<T>` enumerable could be safely used in a `FirstOrNone` (or whatever it would be called). If the result exists, you would get a nested `Option`.

The problem users have is: how long have discriminated unions been "coming soon"? It seems that every year will be the year they land, but it's been... almost a decade? I understand it's not an easy problem, but it's frustrating.
