### ISSUE TITLE
[browser] Allow `WasmDebugLevel=0` for debug builds

### ISSUE THREAD

**Issue by maraf** [dotnet/runtime#94174]
- Currently we force non-zero debug level for debug builds
- We override the value even when user explicitly specify `0`
- Beside other effects, it forces runtime to download pdbs and there is not direct way for user to bypass it

https://github.com/dotnet/runtime/blob/3295789aa9a959a637b2a6b59eb1df1870df4658/src/mono/wasm/build/WasmApp.targets#L146

https://github.com/dotnet/runtime/blob/3295789aa9a959a637b2a6b59eb1df1870df4658/src/mono/nuget/Microsoft.NET.Sdk.WebAssembly.Pack/build/Microsoft.NET.Sdk.WebAssembly.Browser.targets#L208

**Comment by maraf** [comment]
@radical Do we remember why we enforced non-zero debug level for debug builds?

**Comment by radical** [comment]
> @radical Do we remember why we enforced non-zero debug level for debug builds?

To allow debugging, and get the debug messages from the runtime, I assume. cc @thaystg 
Not downloading pdb files sounds like a very niche case, and if we want to support that then it should be by some other mechanism. We should not change the default for that case.

**Comment by thaystg** [comment]
We force -1 to allow debugging and do NOT get debug messages from the runtime.
To get debug messages from the runtime we need to pass numbers >= 1.

**Comment by maraf** [comment]
Is it the correct behavior if user explicitly want it turned off (by setting WasmDebugLevel=0 in csproj/cmd)?

**Comment by radical** [comment]
> Is it the correct behavior if user explicitly want it turned off (by setting WasmDebugLevel=0 in csproj/cmd)?

Hm that does sound a bit wrong. I think we might have had `WasmDebugLevel=0` being set by default elsewhere, and this was reacting to it. Try changing the condition to `<WasmDebugLevel Condition="'$(WasmDebugLevel)' == '' and ('$(DebuggerSupport)' == 'true' or '$(Configuration)' == 'Debug')">-1</WasmDebugLevel>` and see how WBT fares. And try debugging blazor, and wasm template apps.

**Comment by radical** [comment]
Also, see https://github.com/dotnet/runtime/blob/c9a985d75b2255035062398557ba5a281e537b64/eng/testing/tests.browser.targets#L179-L188 . And check debugging library tests also, though I haven't tried it in quite some time, but the wasmapphost PR had it working.
