### ISSUE TITLE
`dotnet test` is not running tests for .NETFramework targets

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#94183]
### Description

When running `dotnet test` on a test project in dotnet/runtime that targets .NETFramework I expect tests to run, but they do not.  Seems like we have lots of other issues mentioning this, but I couldn't find an active one.

### Reproduction Steps

build clr+libs -rc Release
cd src\libraries\System.Collections.Immutable\tests
dotnet test -f:net462

### Expected behavior

Tests run.
```
    Discovering: System.Collections.Immutable.Tests (app domain = on [no shadow copy], method display = ClassAndMethod,
   method display options = None)
    Discovered:  System.Collections.Immutable.Tests (found 4008 of 4123 test cases)
    Starting:    System.Collections.Immutable.Tests (parallel test collections = on, max threads = 16)
```

### Actual behavior

No tests run:
```
Test run for c:\src\dotnet\runtime\artifacts\bin\System.Collections.Immutable.Tests\Debug\net462\System.Collections.Immutable.Tests.dll (.NETFramework,Version=v4.6.2)
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
No test is available in c:\src\dotnet\runtime\artifacts\bin\System.Collections.Immutable.Tests\Debug\net462\System.Collections.Immutable.Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
```

### Regression?

I think this is a recent regression.  I believe this used to work as I remember seeing test failures on framework when running with dotnet test.

### Known Workarounds

Directly invoke the `test` target.

> \src\dotnet\runtime\.dotnet\dotnet build /t:test -f:net462

**Comment by ViktorHofer** [comment]
Someone needs to debug this. This likely also impacts VS Text Explorer which uses the VSTest runner underneath. There are settings to get more verbose logs returned by VSTest.

**Comment by ViktorHofer** [comment]
One more thought, that could be related to the recent xunit 2.5.x upgrade.

**Comment by ViktorHofer** [comment]
```
Version=0.2.8.21101, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Error: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginDiscoverer.GetTestExtensionsFromAssembly[TPluginInfo,TExtension](Assembly assembly, Dictionary`2 pluginInfos, String filePath) in /_/src/Microsoft.TestPlatform.Common/ExtensionFramework/TestPluginDiscoverer.cs:line 158
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Microsoft.Bcl.AsyncInterfaces, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginCache.CurrentDomainAssemblyResolve(Object sender, AssemblyResolveEventArgs args) in /_/src/Microsoft.TestPlatform.Common/ExtensionFramework/TestPluginCache.cs:line 513
   at System.Runtime.Loader.AssemblyLoadContext.GetFirstResolvedAssemblyFromResolvingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
```

`--diag:log.txt`

**Comment by ViktorHofer** [comment]
Filed https://github.com/xunit/visualstudio.xunit/issues/390

**Comment by bradwilson** [comment]
Are you're linking against xunit.runner.utility for some reason? If so, then you're frozen to using whatever version of xunit.runner.utility the VS adapter uses (because VSTest demands all dependencies be copied into the output folder). 99%+ of users don't do this so this isn't a general problem.

**Comment by bradwilson** [comment]
The only reason to link against xunit.runner.utility is because you're creating your own runner. Tests should never link against this unless they're forced to because they're testing the runner you're writing.

**Comment by bradwilson** [comment]
For a bit of architectural background...

xUnit.net splits what it does into two separate sections which do not directly interact except via very strict contracts. There are "runner" and "execution" halves of the system. In v1/v2 when using .NET Framework, these two halves can be optionally separated by an app domain boundary (and in v2 .NET Core, they live in the same process). In v3 against all target platforms, they're separated by a process boundary.

- Tests lives in the "execution" half, and are linked against `xunit.core` and `xunit.execution.*` (and usually `xunit.assert`, though that's optional).
- Runners live in the "runner" half, and are linked against `xunit.runner.utility.*` (and maybe other runner related things).
- The only common assembly that lives in both half, and comprises the communication contract, is `xunit.abstractions`. It has been frozen since we shipped 2.0 (we have shipped newer version of the NuGet assembly just to add extra targets, but the DLL itself remains unchanged since we shipped it).

By keeping this strong separation and frozen contracts, we have both backward compatibility (newer runners can run older tests) and major forward compatibility (older v2 runners can run newer v2 tests).

If your tests link against `xunit.runner.utility.*`, you're bringing the runner half of things where it normally doesn't live or belong. This is unavoidable if you're writing your own runner, and want to test that runner (we obviously do this, but it should be very very rare). Normally this wouldn't be a problem _except_ when you're using VSTest, because there is a requirement placed by VSTest that we copy the VSTest adapter into your output folder, which of course means we also have to copy the runner utility libraries (`xunit.runner.utility.*` and `xunit.runner.reporters.*`). This is the only scenario where we end up with potential collisions between versions of the runner utility libraries, so when you're in this scenario, you must very explicitly remain frozen to use the same version of the runner utility libraries as the VSTest adapter is that you're using.

In addition, there is no guarantee that any particular version of `xunit.runner.visualstudio` will use any particular version of `xunit.runner.utility`. We shipped 2.5.3 of the former at the same time as 2.5.2 of the latter, but even simultaneous shipment isn't guaranteed (and in fact they lived _very_ separate lives back when @clairernovotny owned the VSTest adapter).

When I shipped core framework 2.5.3, it had no runner utility changes that would've necessitated bringing in a new version for the VSTest adapter, so I didn't bother to ship a new one. It appears that when I ship the next core framework drop (which I'm planning to number 2.6.0), this will still be true, so again I'm not likely to ship another VSTest adapter version.

**Comment by ViktorHofer** [comment]
Wow, that's quite a detailed comment. Thank you for spending your time on writing this up. I just reproduced this locally and I don't see our tests linking against any of the `xunit.runner.*` assemblies.

What I see is that because of us wanting to support both xunit.console and VSTest, we bring in `xunit.runner.utility.net452.dll` from the xunit.console and explicitly exclude the one from xunit.runner.visualstudio which results in that version collision.

> This is the only scenario where we end up with potential collisions between versions of the runner utility libraries, so when you're in this scenario, you must very explicitly remain frozen to use the same version of the runner utility libraries as the VSTest adapter is that you're using.

Exactly that.

This begs the question why we ever chose a design that made us copy the xunit.console runner into the test app's output directory. While VSTest requires that, xunit.console shouldn't.

**Comment by bradwilson** [comment]
Yeah, that operation makes no sense to me. You were basically just waiting to explode. 😁 

Each runner has to bring along their own copy of `xunit.runner.utility.*` that they're linked against. It's just the VSTest adapter which insists on copying it into _your_ output folder; all the other runners just live elsewhere and are invoked by hand, so the assemblies are never mixed together.

**Comment by bradwilson** [comment]
To be even more explicit: xunit.console would never use `xunit.runner.utility.*` from the test's folder. It would need to live along side `xunit.console.exe` so that .NET Framework could do the appropriate implicit loading. If you're copying the contents of xunit.console's NuGet package into your test output folder, you should stop doing that. It's unnecessary and counterproductive. Just run it from wherever it lives (in `~/.nuget/packages` or some equivalent).

**Comment by ViktorHofer** [comment]
> you should stop doing that. It's unnecessary and counterproductive. Just run it from wherever it lives (in ~/.nuget/packages or some equivalent).

Just to share some context. We invoke our tests in CI on different machines than the build agents. We use `Helix` for that, which is a distributed machine testing orchestration infrastructure. Because of that, we can't rely on the package cache. Instead we should have just sent that dependency as an additional "payload" (dependency) to that helix test agent.

Unfortunately our infrastructure here has become quite complex with so many different app models and ways of testing that this change will probably require some time.

But for what is worth, this is indeed our own fault. Thanks for help diagnosing the issue :)

**Comment by bradwilson** [comment]
Good luck! 😄

**Comment by ericstj** [comment]
@ViktorHofer did you have a suggestion for what needs to happen to fix this?

I gather that by copying xunit runner binaries over to the output directory this is somehow causing the test-discoverer to fail before it gets a chance to examine our test assembly, is that correct?

**Comment by ViktorHofer** [comment]
The gist (IIRC) is to not copy xunit.console's assemblies into the output directory and just invoke it from the package cache (as intended). Only copy it into the output directory when archiving the test assemblies for helix submissions (property: `/p:ArchiveTests=true`).

xunit.runner.visualstudio is designed to be copied into the app output directory but xunit.console isn't. So avoiding the latter makes sense on a local machine.

**Comment by bradwilson** [comment]
> xunit.runner.visualstudio is designed to be copied into the app output directory

That makes it sound like we do something special here. We don't. The copy is an unfortunate requirement from the VSTest team; if we don't copy the DLLs into the output directory, then whoever runs `dotnet test` (or equivalent) needs to specify the location of the test adapter path on disk via an additional command line argument.

**Comment by bradwilson** [comment]
If it helps, we could add an MSBuild property that we look for to prevent the file copies. They would need to stay on by default but if you know what you're doing, skipping the copies could make sense.

**Comment by ViktorHofer** [comment]
I think this really is an issue on our side and needs a fix in our test infrastructure. The xunit.console copying is just wrong and also in-efficient. I should have done this differently in the past.

**Comment by ericstj** [comment]
Yeah, other repos don't copy.  It's not so hard to make that work, but it does require changes in a few places.

One thing that was odd to me is that we're saying that our binaries are self-consistent and would work if we merely delete files that aren't needed.  That tells me we might also have a bug / design-change ask for the `dotnet test` scenario to not halt when it encounters binding problems in other assemblies in the output directory.

**Comment by ViktorHofer** [comment]
> It's not so hard to make that work, but it does require changes in a few places.

I was suggesting something simpler for a quick fix. Keep the xunit.console in the app output directory but only when `ArchiveTests=true`. Otherwise (locally) use the xunit.console from the nuget cache.

**Comment by ericstj** [comment]
@akoeplinger found other places that still rely on xunit.console in the output directory.

> it looks like https://github.com/dotnet/runtime/pull/96826 is breaking a couple things 
> - A couple wasm projects set BundleXunitRunner but now they don't get the xunit.console.dll locally unless they set ArchiveTests=true
> - It also breaks the enterprise-linux pipeline since it uses dotnet build /t:Test instead of dotnet test: https://dev.azure.com/dnceng-public/public/_build/results?buildId=537464&view=logs&j=03b95830-93c2-599b-7e4d-1efb940adc28&t=deab5cac-2f83-5667-2973-63a6919b97de
>
> The latter seems more problematic since we document /t:Test in a couple places and I know many people are still in the habit of using it vs dotnet test and in some cases you don't want the vstest runner

**Comment by ViktorHofer** [comment]
> The latter seems more problematic since we document /t:Test in a couple places and I know many people are still in the habit of using it vs dotnet test and in some cases you don't want the vstest runner

`dotnet build /t:Test` should still work with https://github.com/dotnet/runtime/pull/96826. What are we missing here?

**Comment by ViktorHofer** [comment]
Moving this back into 9.0.0 as this makes debugging .NET Framework tests with `dotnet test` harder. We can move it back to 10.0.0 if we don't get to it though.

**Comment by ericstj** [comment]
Here's the current output from `dotnet test` on a project with a netfx targetframework.

```
C:\src\dotnet\runtime\src\libraries\System.Data.Odbc\tests>\src\dotnet\runtime\.dotnet\dotnet.exe test /bl

  Determining projects to restore...
  All projects are up-to-date for restore.
  TestUtilities -> C:\src\dotnet\runtime\artifacts\bin\TestUtilities\Debug\net8.0\TestUtilities.dll
  ILLink.RoslynAnalyzer -> C:\src\dotnet\runtime\artifacts\bin\ILLink.RoslynAnalyzer\Debug\netstandard2.0\ILLink.RoslynAn
  alyzer.dll
  ILLink.CodeFixProvider -> C:\src\dotnet\runtime\artifacts\bin\ILLink.CodeFixProvider\Debug\netstandard2.0\ILLink.CodeFi
  xProvider.dll
  Mono.Linker -> C:\src\dotnet\runtime\artifacts\bin\Mono.Linker\ref\Debug\net10.0\illink.dll
  Mono.Linker -> C:\src\dotnet\runtime\artifacts\bin\Mono.Linker\Debug\net10.0\illink.dll
  ILLink.Tasks -> C:\src\dotnet\runtime\artifacts\bin\ILLink.Tasks\Debug\net\ILLink.Tasks.dll
  System.Data.Odbc -> C:\src\dotnet\runtime\artifacts\bin\System.Data.Odbc\ref\Debug\net10.0\System.Data.Odbc.dll
  System.Data.Odbc -> C:\src\dotnet\runtime\artifacts\bin\System.Data.Odbc\Debug\net10.0-windows\System.Data.Odbc.dll
  System.Data.Odbc.Tests -> C:\src\dotnet\runtime\artifacts\bin\System.Data.Odbc.Tests\Debug\net10.0-windows\System.Data.
  Odbc.Tests.dll
Test run for C:\src\dotnet\runtime\artifacts\bin\System.Data.Odbc.Tests\Debug\net10.0-windows\System.Data.Odbc.Tests.dll (.NETCoreApp,Version=v10.0)
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:01.31]     System.Data.Odbc.Tests.DependencyCheckTest.OdbcConnection_OpenWhenOdbcNotInstalled_ThrowsException [SKIP]
[xUnit.net 00:00:01.31]     System.Data.Odbc.Tests.OdbcConnectionSchemaTests.TestConnectionSchemaOnOpenConnection [SKIP]
  Skipped System.Data.Odbc.Tests.DependencyCheckTest.OdbcConnection_OpenWhenOdbcNotInstalled_ThrowsException [1 ms]
  Skipped System.Data.Odbc.Tests.OdbcConnectionSchemaTests.TestConnectionSchemaOnOpenConnection [1 ms]
[xUnit.net 00:00:01.42]     System.Data.Odbc.Tests.OdbcParameterTests.RunTest [SKIP]
[xUnit.net 00:00:01.60]     System.Data.Odbc.Tests.ReaderTests.GetDataTypeName [SKIP]
[xUnit.net 00:00:01.60]     System.Data.Odbc.Tests.CommandBuilderTests.QuoteIdentifier_UseConnection [SKIP]
[xUnit.net 00:00:01.60]     System.Data.Odbc.Tests.ConnectionTests.DbConnectionFactories_GetFactory_from_connection [SKIP]
[xUnit.net 00:00:01.60]     System.Data.Odbc.Tests.SmokeTest.CreateInsertSelectTest [SKIP]
[xUnit.net 00:00:01.61]     System.Data.Odbc.Tests.ReaderTests.GetFieldTypeIsNotSupportedInSqlite [SKIP]
[xUnit.net 00:00:01.61]     System.Data.Odbc.Tests.CommandBuilderTests.QuoteIdentifier_CustomPrefixSuffix [SKIP]
[xUnit.net 00:00:01.61]     System.Data.Odbc.Tests.ReaderTests.IsDbNullIsNotSupportedInSqlite [SKIP]
[xUnit.net 00:00:01.61]     System.Data.Odbc.Tests.ReaderTests.InvalidRowName [SKIP]
  Skipped System.Data.Odbc.Tests.OdbcParameterTests.RunTest [1 ms]
  Skipped System.Data.Odbc.Tests.CommandBuilderTests.QuoteIdentifier_UseConnection [1 ms]
  Skipped System.Data.Odbc.Tests.ReaderTests.GetDataTypeName [1 ms]
  Skipped System.Data.Odbc.Tests.ConnectionTests.DbConnectionFactories_GetFactory_from_connection [1 ms]
  Skipped System.Data.Odbc.Tests.SmokeTest.CreateInsertSelectTest [1 ms]
  Skipped System.Data.Odbc.Tests.ReaderTests.GetFieldTypeIsNotSupportedInSqlite [1 ms]
  Skipped System.Data.Odbc.Tests.CommandBuilderTests.QuoteIdentifier_CustomPrefixSuffix [1 ms]
  Skipped System.Data.Odbc.Tests.ReaderTests.IsDbNullIsNotSupportedInSqlite [1 ms]
  Skipped System.Data.Odbc.Tests.ReaderTests.InvalidRowName [1 ms]
[xUnit.net 00:00:01.62]     System.Data.Odbc.Tests.ReaderTests.GetValueFailsWithBigIntWithBackwardsCompatibility [SKIP]
[xUnit.net 00:00:01.62]     System.Data.Odbc.Tests.ReaderTests.EmptyReader [SKIP]
[xUnit.net 00:00:01.62]     System.Data.Odbc.Tests.ReaderTests.InvalidRowIndex [SKIP]
[xUnit.net 00:00:01.62]     System.Data.Odbc.Tests.ReaderTests.GetValues [SKIP]
  Skipped System.Data.Odbc.Tests.ReaderTests.GetValueFailsWithBigIntWithBackwardsCompatibility [1 ms]
  Skipped System.Data.Odbc.Tests.ReaderTests.EmptyReader [1 ms]
  Skipped System.Data.Odbc.Tests.ReaderTests.InvalidRowIndex [1 ms]
  Skipped System.Data.Odbc.Tests.ReaderTests.GetValues [1 ms]
Results File: C:\src\dotnet\runtime\artifacts\bin\System.Data.Odbc.Tests\Debug\net10.0-windows\TestResults\ericstj_CPC-erics-1RABK_2025-08-22_07_25_06.trx
Html test results file : C:\src\dotnet\runtime\artifacts\bin\System.Data.Odbc.Tests\Debug\net10.0-windows\TestResults\TestResult_ericstj_CPC-erics-1RABK_20250822_072507.html

Passed!  - Failed:     0, Passed:     3, Skipped:    15, Total:    18, Duration: 372 ms - System.Data.Odbc.Tests.dll (net10.0)
  Microsoft.Interop.SourceGeneration -> C:\src\dotnet\runtime\artifacts\bin\Microsoft.Interop.SourceGeneration\Debug\nets
  tandard2.0\Microsoft.Interop.SourceGeneration.dll
  DownlevelLibraryImportGenerator -> C:\src\dotnet\runtime\artifacts\bin\DownlevelLibraryImportGenerator\Debug\netstandar
  d2.0\Microsoft.Interop.LibraryImportGenerator.Downlevel.dll
  TestUtilities -> C:\src\dotnet\runtime\artifacts\bin\TestUtilities\Debug\net481\TestUtilities.dll
  System.Data.Odbc.Tests -> C:\src\dotnet\runtime\artifacts\bin\System.Data.Odbc.Tests\Debug\net481\System.Data.Odbc.Test
  s.dll

C:\src\dotnet\runtime\src\libraries\System.Data.Odbc\tests>
```

The console logging is missing for test execution of the `net481` target, however the binlog shows that it ran, and the testresults exist in the output directory.

**Comment by ericstj** [comment]
As suggested by @akoeplinger, specifying ` /tl:off` gives correct behavior:
```
  System.Data.Odbc.Tests -> C:\src\dotnet\runtime\artifacts\bin\System.Data.Odbc.Tests\Debug\net481\System.Data.Odbc.Test
  s.dll
Test run for C:\src\dotnet\runtime\artifacts\bin\System.Data.Odbc.Tests\Debug\net481\System.Data.Odbc.Tests.dll (.NETFramework,Version=v4.8.1)
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:01.52]     System.Data.Odbc.Tests.OdbcConnectionSchemaTests.TestConnectionSchemaOnOpenConnection [SKIP]
[xUnit.net 00:00:01.56]     System.Data.Odbc.Tests.DependencyCheckTest.OdbcConnection_OpenWhenOdbcNotInstalled_ThrowsException [SKIP]
[xUnit.net 00:00:01.59]     System.Data.Odbc.Tests.OdbcParameterTests.RunTest [SKIP]
[xUnit.net 00:00:01.59]     System.Data.Odbc.Tests.CommandBuilderTests.QuoteIdentifier_UseConnection [SKIP]
  Skipped System.Data.Odbc.Tests.OdbcConnectionSchemaTests.TestConnectionSchemaOnOpenConnection [1 ms]
  Skipped System.Data.Odbc.Tests.DependencyCheckTest.OdbcConnection_OpenWhenOdbcNotInstalled_ThrowsException [1 ms]
  Skipped System.Data.Odbc.Tests.OdbcParameterTests.RunTest [1 ms]
  Skipped System.Data.Odbc.Tests.CommandBuilderTests.QuoteIdentifier_UseConnection [1 ms]
[xUnit.net 00:00:01.61]     System.Data.Odbc.Tests.CommandBuilderTests.QuoteIdentifier_CustomPrefixSuffix [SKIP]
[xUnit.net 00:00:01.61]     System.Data.Odbc.Tests.ReaderTests.GetDataTypeName [SKIP]
[xUnit.net 00:00:01.61]     System.Data.Odbc.Tests.SmokeTest.CreateInsertSelectTest [SKIP]
[xUnit.net 00:00:01.62]     System.Data.Odbc.Tests.ReaderTests.GetFieldTypeIsNotSupportedInSqlite [SKIP]
[xUnit.net 00:00:01.62]     System.Data.Odbc.Tests.ReaderTests.IsDbNullIsNotSupportedInSqlite [SKIP]
[xUnit.net 00:00:01.63]     System.Data.Odbc.Tests.ReaderTests.InvalidRowName [SKIP]
[xUnit.net 00:00:01.63]     System.Data.Odbc.Tests.ReaderTests.GetValueFailsWithBigIntWithBackwardsCompatibility [SKIP]
[xUnit.net 00:00:01.64]     System.Data.Odbc.Tests.ReaderTests.EmptyReader [SKIP]
[xUnit.net 00:00:01.64]     System.Data.Odbc.Tests.ReaderTests.InvalidRowIndex [SKIP]
  Skipped System.Data.Odbc.Tests.CommandBuilderTests.QuoteIdentifier_CustomPrefixSuffix [1 ms]
  Skipped System.Data.Odbc.Tests.ReaderTests.GetDataTypeName [1 ms]
  Skipped System.Data.Odbc.Tests.SmokeTest.CreateInsertSelectTest [1 ms]
  Skipped System.Data.Odbc.Tests.ReaderTests.GetFieldTypeIsNotSupportedInSqlite [1 ms]
  Skipped System.Data.Odbc.Tests.ReaderTests.IsDbNullIsNotSupportedInSqlite [1 ms]
  Skipped System.Data.Odbc.Tests.ReaderTests.InvalidRowName [1 ms]
  Skipped System.Data.Odbc.Tests.ReaderTests.GetValueFailsWithBigIntWithBackwardsCompatibility [1 ms]
  Skipped System.Data.Odbc.Tests.ReaderTests.EmptyReader [1 ms]
  Skipped System.Data.Odbc.Tests.ReaderTests.InvalidRowIndex [1 ms]
[xUnit.net 00:00:01.65]     System.Data.Odbc.Tests.ReaderTests.GetValues [SKIP]
  Skipped System.Data.Odbc.Tests.ReaderTests.GetValues [1 ms]
Results File: C:\src\dotnet\runtime\artifacts\bin\System.Data.Odbc.Tests\Debug\net481\TestResults\ericstj_CPC-erics-1RABK_2025-08-22_07_33_27.trx
Html test results file : C:\src\dotnet\runtime\artifacts\bin\System.Data.Odbc.Tests\Debug\net481\TestResults\TestResult_ericstj_CPC-erics-1RABK_20250822_073327.html

Passed!  - Failed:     0, Passed:     3, Skipped:    14, Total:    17, Duration: 139 ms - System.Data.Odbc.Tests.dll (net481)

C:\src\dotnet\runtime\src\libraries\System.Data.Odbc\tests>
```

**Comment by ericstj** [comment]
Bizarrely, this is caused by https://github.com/dotnet/runtime/blob/674d359c926ca590a62d588a786bc7e4eb88c51f/Directory.Build.rsp#L2

When `-tl:off|false` is specified in the RSP, the `_VSTestConsole` target is used, just like when specifying `-tl:off` from the commandline, but the build only logs one of the test runs.  So something about setting the -tl:off in the rsp is different than passing in from the commandline.

I can reproduce this with a normal test project outside the dotnet/runtime infra.
[xunitTest.zip](https://github.com/user-attachments/files/21941036/xunitTest.zip)

We could remove our disabling of the terminal logger entirely -- https://github.com/dotnet/runtime/issues/119012

Or we could just remove the .rsp, since that's really only used when folks are manually invoking `dotnet build` or `dotnet test`.  I'm inclined to do the latter.

I'd still like to understand why using the rsp is different than a commandline parameter @rainersigwald in case he has an idea.

**Comment by ericstj** [comment]
So it looks like the difference in these two scenarios is that when `/tl:off` isn't passed in on the commandline, `dotnet test` itself is passing `VsTestUseMSBuildOutput`

<img width="666" height="228" alt="Image" src="https://github.com/user-attachments/assets/3ac6535f-542d-466b-8e46-1d1810bb2bfb" />

This is coming from here https://github.com/dotnet/sdk/blob/55044e9a14e10600c07dcb22ea669b5faad890fc/src/Cli/dotnet/Commands/Test/TestCommand.cs#L102

So it's "by design" in a way.  Test isn't aware of our RSP file.  I'll still file the issue and see what SDK folks say.

**Comment by ericstj** [comment]
Adjusting area-path here.  This is caused by the rsp file in the root.  It breaks all test output, not just libraries.

We either need a fix for https://github.com/dotnet/sdk/issues/50441 or just remove `-tl:off` from the RSP.

I'm inclined to just remove from rsp.  The root build scripts already disable the terminal logger for `build` from the root.  This RSP is just being used when folks run dotnet commands on individual projects.  IMO we can let folks get the terminal logger there since that's what our customers get.

What do you think @akoeplinger @ViktorHofer @ManickaP @jkoritzinsky @jkotas 

Also cc @SingleAccretion @agocke who just changed https://github.com/dotnet/runtime/pull/119282 so probably have other workflows to use `dotnet build|test`.

**Comment by jkotas** [comment]
> just remove from rsp
> What do you think

I do not have an opinion. I have the terminal logger force disabled using `MSBUILDTERMINALLOGGER=off` on my machines as I have mentioned in https://github.com/dotnet/runtime/issues/119012#issuecomment-3215164539 . I assume that this env variable is still going to be respected with this change.

**Comment by ManickaP** [comment]
@ericstj does that mean that none of the problems I mentioned in https://github.com/dotnet/runtime/issues/119012#issuecomment-3219848478 are solved yet we're still doing #119012?

**Comment by SingleAccretion** [comment]
> Also cc SingleAccretion ...

My opinion is that it does not makes sense to make the build experience different between the root build script and `dotnet build`. There are projects that I interact with through the root script (e. g. `runtime.proj` / `build-native.proj`). There are projects that I never use the root build script for (individual libraries, libraries tests, runtime tests). Some "native" projects have documented targets for building them manually ([example](https://github.com/dotnet/runtime/blob/655ec8aae923a79d49d2d4b504c1411c71810628/src/mono/browser/browser.proj#L374)).

I also strongly agree with what has been written in #119012, that enabling the terminal logger would be a net regression for the default `/runtime` development experience. Which is not necessarily the case for many non-`/runtime` projects, since they have much simpler build setups.

**Comment by ericstj** [comment]
> does that mean that none of the problems I mentioned

I *think* that those are all side-effects of using `build /t:Test` instead of `test`.  The build behavior does not do the same thing as test so you end up running tests differently and not getting the runner behavior that's optimized for the terminal logger.  I think you'll get a better experience (and one that matches what customers see) by using `test`.  It still may have some issues, but those are good for us to find and report against the product.

If we keep disabling this it this means we're building an experience for our customers that doesn't work well enough for ourselves.  Doesn't that strike you as busted?  @baronfel

By disabling default experiences like this it makes us operate in the fringe - where our problems end up being our own and time spent by our developers to improve things doesn't improve the product itself.  Part of working on this product is that we need to use the product in the form that we ship and suffer through some of the user-experience issues so that we make things better.

I think there is work planned to improve the terminal logger in the CI scenario - https://github.com/dotnet/msbuild/issues/12486 -that could help us to use it for root builds.

**Comment by jkotas** [comment]
> If we keep disabling this it this means we're building an experience for our customers that doesn't work well enough for ourselves. Doesn't that strike you as busted?

Our default experiences are optimized for small ordinary .NET projects. This repo is not anything like that. It does not strike me as busted when we need to diverge from the default experience. I agree that it would be nice to do that as little as possible and understand the reasoning. I expect that every large project of similar complexity needs to override number of defaults for good reasons and that's by design.
