### ISSUE TITLE
Extreme Performance issues using SetMinimumLevel

### ISSUE THREAD

**Issue by joepperkins** [dotnet/runtime#94186]
### Description

Adding SetMinimumLevel to the logging options causes extreme performance degradation. 

            services.AddLogging(builder =>
            {
                builder.AddApplicationInsights(client.LoggingSettings.InstrumentationKey);
                builder.AddFilter<ApplicationInsightsLoggerProvider>(string.Empty, LogLevel.Trace);
                builder.SetMinimumLevel(LogLevel.Trace);

                if (Debugger.IsAttached)
                {
                    builder.AddConsole();
                }
            });     

### Configuration

This was observed in both AspNet Core 6,7 - Windows

### Regression?

This was the first time implemented.

### Data

The API baseline single call tests that had implemented SetMinimumLevel response time went from 110 ms response to 2s response. 

The API baseline simultaneous call load test (50 calls) that had implemented SetMinimumLevel response time went from 2s response to 30s response. 

### Analysis

Simply adding the code below caused the performance issue, removing fixed the issue.

builder.SetMinimumLevel(LogLevel.Trace);

**Comment by teo-tsirpanis** [comment]
I believe this performance degradation is expected. Setting the minimum level to `LogLevel.Trace` likely causes significantly more events to be logged.

**Comment by joepperkins** [comment]
> I believe this performance degradation is expected. Setting the minimum level to `LogLevel.Trace` likely causes significantly more events to be logged.

Setting it to "None" has the same performance impact.

**Comment by tarekgh** [comment]
@joepperkins can you past the perf numbers you are seeing? If you can attach a complete sample, you are using to measure it will be good.

**Comment by joepperkins** [comment]
In the screen shot below he only difference is removing the line of code **builder.SetMinimumLevel(LogLevel.Trace);**. Please note setting this option to None (**builder.SetMinimumLevel(LogLevel.None)**) has the same performance impact. 

![image](https://github.com/dotnet/runtime/assets/13791515/e9455c16-260f-45d9-aa33-100e2c38fa9b)

**Comment by tarekgh** [comment]
@joepperkins thanks for the info, can you please a complete small sample demonstrate the issue?
