### ISSUE TITLE
[WASM] DotnetHostBuilder withDebugging does not accept a value of 0

### ISSUE THREAD

**Issue by JakeYallop** [dotnet/runtime#94238]
### Description

Trying to call `withDebugging(0)` on the dotnet host builder triggers
```
Error: Assert failed: must be number
```
This is due to the check inside `withDebugging` using `&&`, which means the falsy value of 0 causes the assert to fire:
https://github.com/dotnet/runtime/blob/748dd8edecc3cc2b671cab7437adc4b0c750d0be/src/mono/wasm/runtime/loader/run.ts#L252-L256

I hit this issue when trying to provide an options object - if the user does not provide a debugging value, I want to default it to 0.

Potentially related - https://github.com/dotnet/runtime/issues/94174 - although that issue is about the MSBuild property, not the `withDebugging` call.

### Reproduction Steps

```typescript
await dotnet
      .withDebugging(0)
      .create();
```

### Expected behavior

No assert is thrown.

### Actual behavior

```
Uncaught (in promise) Error: Assert failed: must be number
    at De (libraryInitializers.ts:22:72)
    at Object.withDebugging (run.ts:450:85)
```

### Regression?

Not sure

### Known Workarounds

```javascript
.withConfig({
    debugLevel: 0
})
```

**Comment by radical** [comment]
cc @pavelsavara

**Comment by pavelsavara** [comment]
@JakeYallop, thanks for reporting! 

This work-around could help for Net8. 

```
.withConfig({
    debugLevel: 0
})
```

I will create fix for Net9 later.
