### ISSUE TITLE
[wasm] Playwright failing

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#94240]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=456409
Build error leg or test failing: Wasm.Build.Tests.Blazor.SimpleRunTests.BlazorBuildRunTest
Pull request: https://github.com/dotnet/runtime.git/pull/94209

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "src/Playwright/Transport/Connection.cs.*at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=456409
**Error message validated:** `src/Playwright/Transport/Connection.cs.*at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 10/31/2023 8:53:30 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[729150](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729150)|dotnet/runtime|[Workloads-NoWebcil-ST-Wasm.Build.Tests.TestAppScenarios.DownloadThenInitTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729150&view=ms.vss-test-web.build-test-results-tab&runId=18331658&resultId=100178)|dotnet/runtime#104356|
|[722139](https://dev.azure.com/dnceng-public/public/_build/results?buildId=722139)|dotnet/runtime|[Workloads-NoWebcil-ST-Wasm.Build.Tests.Blazor.SimpleRunTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=722139&view=ms.vss-test-web.build-test-results-tab&runId=18119620&resultId=100151)|dotnet/runtime#104049|
|[715775](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715775)|dotnet/runtime|[Wasm.Build.Tests.Blazor.BuildPublishTests.Test_WasmStripILAfterAOT](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715775&view=ms.vss-test-web.build-test-results-tab&runId=17912850&resultId=100110)|dotnet/runtime#103755|
|[713049](https://dev.azure.com/dnceng-public/public/_build/results?buildId=713049)|dotnet/runtime|[Workloads-NoWebcil-ST-Wasm.Build.Tests.Blazor.SimpleRunTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=713049&view=ms.vss-test-web.build-test-results-tab&runId=17832318&resultId=100176)|dotnet/runtime#103689|
|[712763](https://dev.azure.com/dnceng-public/public/_build/results?buildId=712763)|dotnet/runtime|[Workloads-ST-Wasm.Build.Tests.AspNetCore.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=712763&view=ms.vss-test-web.build-test-results-tab&runId=17824468&resultId=100176)|dotnet/runtime#103635|
|[712534](https://dev.azure.com/dnceng-public/public/_build/results?buildId=712534)|dotnet/runtime|[Workloads-NoWebcil-ST-Wasm.Build.Tests.Blazor.MiscTests3.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=712534&view=ms.vss-test-web.build-test-results-tab&runId=17817338&resultId=100175)|dotnet/runtime#100334|
|[712239](https://dev.azure.com/dnceng-public/public/_build/results?buildId=712239)|dotnet/runtime|[Workloads-ST-Wasm.Build.Tests.AspNetCore.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=712239&view=ms.vss-test-web.build-test-results-tab&runId=17807030&resultId=100175)|dotnet/runtime#103638|
|[712203](https://dev.azure.com/dnceng-public/public/_build/results?buildId=712203)|dotnet/runtime|[Workloads-ST-Wasm.Build.Tests.TestAppScenarios.LazyLoadingTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=712203&view=ms.vss-test-web.build-test-results-tab&runId=17805592&resultId=100176)|dotnet/runtime#103144|
|[710789](https://dev.azure.com/dnceng-public/public/_build/results?buildId=710789)|dotnet/runtime|[Workloads-ST-Wasm.Build.Tests.Blazor.IcuTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=710789&view=ms.vss-test-web.build-test-results-tab&runId=17761038&resultId=100174)|dotnet/runtime#101337|
|[710004](https://dev.azure.com/dnceng-public/public/_build/results?buildId=710004)|dotnet/runtime|[Workloads-ST-Wasm.Build.Tests.TestAppScenarios.SatelliteLoadingTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=710004&view=ms.vss-test-web.build-test-results-tab&runId=17738956&resultId=100176)|dotnet/runtime#103422|
|[709765](https://dev.azure.com/dnceng-public/public/_build/results?buildId=709765)|dotnet/runtime|[Workloads-NoWebcil-ST-Wasm.Build.Tests.Blazor.MiscTests3.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=709765&view=ms.vss-test-web.build-test-results-tab&runId=17729274&resultId=100176)|dotnet/runtime#100334|
|[703834](https://dev.azure.com/dnceng-public/public/_build/results?buildId=703834)|dotnet/runtime|[Workloads-ST-Wasm.Build.Tests.Blazor.MiscTests3.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=703834&view=ms.vss-test-web.build-test-results-tab&runId=17579012&resultId=100176)|dotnet/runtime#100334|
|[702554](https://dev.azure.com/dnceng-public/public/_build/results?buildId=702554)|dotnet/runtime|[Workloads-ST-Wasm.Build.Tests.Blazor.SimpleRunTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=702554&view=ms.vss-test-web.build-test-results-tab&runId=17499996&resultId=100178)|dotnet/runtime#103195|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|13|

**Comment by pavelsavara** [comment]
cc @maraf

**Comment by lewing** [comment]
still trickling in

**Comment by pavelsavara** [comment]
```
System.TimeoutException : Timeout 30000ms exceeded.
     Stack Trace:
        /_/src/Playwright/Transport/Connection.cs(164,0): at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](String guid, String method, Object args)
        /_/src/Playwright/Transport/Connection.cs(475,0): at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal)
        /_/src/Playwright/Core/BrowserType.cs(61,0): at Microsoft.Playwright.Core.BrowserType.LaunchAsync(BrowserTypeLaunchOptions options)
        /_/src/mono/wasm/Wasm.Build.Tests/BrowserRunner.cs(112,0): at Wasm.Build.Tests.BrowserRunner.SpawnBrowserAsync(String browserUrl, Boolean headless)
        /_/src/mono/wasm/Wasm.Build.Tests/BrowserRunner.cs(136,0): at Wasm.Build.Tests.BrowserRunner.RunAsync(ToolCommand cmd, String args, Boolean headless, Action`2 onConsoleMessage, Action`1 onServerMessage, Action`1 onError, Func`2 modifyBrowserUrl)
        /_/src/mono/wasm/Wasm.Build.Tests/Blazor/BlazorWasmTestBase.cs(202,0): at Wasm.Build.Tests.BlazorWasmTestBase.BlazorRunTest(String runArgs, String workingDirectory, BlazorRunOptions runOptions)
        /_/src/mono/wasm/Wasm.Build.Tests/Blazor/BlazorWasmTestBase.cs(229,0): at Wasm.Build.Tests.BlazorWasmTestBase.BlazorRunTest(String runArgs, String workingDirectory, BlazorRunOptions runOptions)
        /_/src/mono/wasm/Wasm.Build.Tests/TestAppScenarios/AppTestBase.cs(121,0): at Wasm.Build.Tests.TestAppScenarios.AppTestBase.RunSdkStyleApp(RunOptions options, BlazorRunHost host)
        /_/src/mono/wasm/Wasm.Build.Tests/TestAppScenarios/DownloadThenInitTests.cs(30,0): at Wasm.Build.Tests.TestAppScenarios.DownloadThenInitTests.NoResourcesReFetchedAfterDownloadFinished(String config)
        --- End of stack trace from previous location ---
```

Maybe we could set the timeout shorter and do re-try when it's `System.TimeoutException`

cc @ilonatommy
