### ISSUE TITLE
The new SZGenericArrayEnumerator unexpectedly throws errors for empty collections

### ISSUE THREAD

**Issue by icom85** [dotnet/runtime#94256]
### Description

Hello! We encountered an issue related to the base `SZGenericArrayEnumerator` type and its **Current** position. This seems to be a breaking change as the issue got introduced in .NET 8 preview 2 - https://versionsof.net/core/8.0/8.0.0-preview.2/.

### Reproduction Steps

Create an empty list like this:
```C#
 List<int> items = new List<int>();
```
Imagine that you have a more generic method accepting IEnumerable<int> as a parameter and you call that method and pass the empty list. Inside the method you want to move and access the current item: 
```C#
private void GetNext(IEnumerable<int> items)
{
    IEnumerator<int> enumerator = items.GetEnumerator();
    enumerator.MoveNext();
    int current = enumerator.Current;
}

```
If you check for the Current directly, you will get: _System.InvalidOperationException: 'Enumeration has not started. Call MoveNext.'_
If you call MoveNext() and then check the Current, you will get: _System.InvalidOperationException: 'Enumeration already finished.'_

The type of the enumerator is: **SZGenericArrayEnumerator**. 
![image](https://github.com/dotnet/runtime/assets/5156494/a03e8ebe-30aa-4607-91f0-c74ee924a85b)

Prior to NET 8 preview 2, in the same setup you would get a **System.Collections.Generic.List<int>.Enumerator** and you would not get errors, the **Current** would be **0**. 

It seems that the new and concrete implementation for the enumerator that is returned for the base types is causing the error. This may cause runtime issues with existing application if they are run in .net8.0.

### Expected behavior

The Current should not throw.

### Actual behavior

Errors are thrown.

### Regression?

Yes, the behavior was different in .NET 8 preview 1 and before.

### Known Workarounds

Use MoveNext and only access the Current item if the enumerator has successfully moved to the next position.
```C#
private void GetNext(IEnumerable<int> items)
{
    IEnumerator<int> enumerator = items.GetEnumerator();
    if (enumerator.MoveNext())
    {
        int current = enumerator.Current;
    }
}

```

**Comment by lilinus** [comment]
I says in the documentation for IEnumerable<T> that `Current` is undefined if:
> The last call to `MoveNext` returned `false`, which indicates the end of the collection.

I wouldnt expect any particular behaivour where it explicitly says it is undefined?

**Comment by eiriktsarpalis** [comment]
This is still within contract for IEnumerator types. You're not supposed to evaluate `Current` unless the earlier call to `MoveNext()` has returned `true`.

**Comment by icom85** [comment]
I agree that you should not evaluate Current unless, it's MoveNext is successful. Still, that is a breaking change compared to previous versions and it may break existing applications. In my opinion it should be listed and documented.

**Comment by eiriktsarpalis** [comment]
I wouldn't agree with that. Calling `Current` after `MoveNext()` returns false is undefined behavior and users shouldn't be relying on that.

**Comment by icom85** [comment]
Let's say that the undefined behavior has changed 🙂 I understand that you don't want to consider this an issue because of the incorrect usage. Just have in mind that many existing applications for one reason or another may depend on this undefined behavior and upgrading to .NET8 may cause issues.

**Comment by Joe4evr** [comment]
~~Sounds like a skill issue.~~ :trollface:

But for real, relying on Undefined Behavior is a programming cardinal sin and you should repent. If this were in C/C++ [you could find the compiler rewriting your method eliding any and all evaluation, and even time-travel that result up to all its callers](https://devblogs.microsoft.com/oldnewthing/20140627-00/?p=633).
