### ISSUE TITLE
System.Text.Json not Serializing nested objects (treating it as max depth 1) when object is declared internal instead of public

### ISSUE THREAD

**Issue by knightian** [dotnet/runtime#94251]
### Description

System.Text.Json not Serializing nested objects (treating it as max depth 1) when object is declared internal instead of public

### Reproduction Steps

internal struct RequiredResourceAccess
{
     internal List<ResourceAccess> resourceAccess { get; set; }
     internal Guid resourceAppId { get; set; }
 }

expando = ExpandoObject();
expando.name="ThisIsAName";
expando.requiredResourceAccess = /* Code to create new RequiredResourceAccess */

If I try serialize the ExpandoObject with JsonSerializer.Serialize(expando);

It returns JSON like this:
```
{
    name: ThisIsAName,
    requiredResourceAccess: {[]}
}
```

### Expected behavior

I would expect JSON like this:

```
{
    name: ThisIsAName,
    requiredResourceAccess: 
    {
        resourceAcess: /* etc etc */,
        resourceAppId: 12343434
    }
}
```

If I make the struct PUBLIC instead of INTERNAL it works fine. 

### Actual behavior

It seems that System.Json.Text is treating Internal scoped objects differently to Public scoped objects. 

My understanding of internal is that it restricts use of the object within the same binary, so surely the JsonSerializer.Serialize() call within the same binary is fine? And even if it was not.... shouldn't it throw an exception not just return empty JSON?????

**Comment by eiriktsarpalis** [comment]
This by design, STJ will only include members declared as `public` in the JSON contract even though the type itself might be `internal` or `private`. Starting with STJ version 8 you can opt-in non-public members using the `JsonInclude` attribute:
```C#
internal struct RequiredResourceAccess
{
    [JsonInclude]
    internal List<int> resourceAccess { get; set; }
    [JsonInclude]
    internal Guid resourceAppId { get; set; }
}
```

**Comment by knightian** [comment]
> This by design, STJ will only include members declared as `public` in the JSON contract even though the type itself might be `internal` or `private`. Starting with STJ version 8 you can opt-in non-public members using the `JsonInclude` attribute:
> 
> ```cs
> internal struct RequiredResourceAccess
> {
>     [JsonInclude]
>     internal List<int> resourceAccess { get; set; }
>     [JsonInclude]
>     internal Guid resourceAppId { get; set; }
> }
> ```
> 
> FWIW this is unrelated to the use of `ExpandoObject` in the reproduction.

Thanks for the information. Ok got it, good to know.

Do you think it might be worth throwing an exception when someone passes an object that won't be serialized? I feel like just silently reporting back with incomplete Json is not great, took me a fair amount of time to catch on that the internal scoping was the cause.

And then if people are indeed wanting the empty JSON they can just catch the exception and continue on?

Food for thought anyway. Thanks for the response.

**Comment by eiriktsarpalis** [comment]
> Do you think it might be worth throwing an exception when someone passes an object that won't be serialized?

You mean failing if all members in a type are non-public? I think that would be a breaking change for a few folks, in some cases serializing an empty JSON object is actually desirable.

**Comment by knightian** [comment]
> > Do you think it might be worth throwing an exception when someone passes an object that won't be serialized?
> 
> You mean failing if all members in a type are non-public? I think that would be a breaking change for a few folks, in some cases serializing an empty JSON object is actually desirable.

You're right, I didn't consider the fact existing code will start to throw unexpectedly if it's done like that. Perhaps a compiler warning?

**Comment by eiriktsarpalis** [comment]
Like I said, I don't think either a runtime error or compiler warning are desirable because in certain cases not having any JSON properties can be a desirable trait.

**Comment by knightian** [comment]
> Like I said, I don't think either a runtime error or compiler warning are desirable because in certain cases not having any JSON properties can be a desirable trait.

How does one learn this though? Like I had an object that had a bunch of internal scoped child objects and they were returning empty and I had no clue why.

The internal scope is used to limit classes within the same assembly, so it seems that the internal scope is now being used to limit returning JSON even when parsed in the same assembly, something should educate me that internal means it will not be serialized, instead of me lodging an issue.

I did google search the issue and I didn't come to any documentation about this behaviour.

**Comment by eiriktsarpalis** [comment]
Does this help? https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/migrate-from-newtonsoft?pivots=dotnet-8-0#non-public-property-setters-and-getters
