### ISSUE TITLE
HostedService does not capture current SynchronizationContext

### ISSUE THREAD

**Issue by noelex** [dotnet/runtime#94252]
### Description

I expect lifecycle callbacks of `IHostedService` and `IHostedLifecycleService` to be executed within 'current' `SynchronizationContext`, which should be captured at the time of the call to `IHost.RunAsync`.

But it seem that currently `IHost.RunAsync` does not capture current `SynchronizationContext` and lifecycle callbacks are called on an arbitrary thread, due to several async method calls in [`Host.StartAsync`](https://github.com/dotnet/runtime/blob/f4ee321b662068ebf819aec725c2a4fd0eee2bb6/src/libraries/Microsoft.Extensions.Hosting/src/Internal/Host.cs#L73) being awaited with `ConfigureAwait(false)`. 

### Reproduction Steps

```csharp
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

var syncContext = new MySynchronizationContext();
SynchronizationContext.SetSynchronizationContext(syncContext);

var builder = Host.CreateApplicationBuilder();
builder.Services.AddHostedService<MyService>();

await builder.Build().RunAsync();

class MyService : IHostedLifecycleService
{
    public Task StartAsync(CancellationToken cancellationToken)
    {
        Console.WriteLine($"Start: {SynchronizationContext.Current}");
        return Task.CompletedTask;
    }

    public async Task StartingAsync(CancellationToken cancellationToken)
    {
        Console.WriteLine($"Starting: {SynchronizationContext.Current}");
        await Task.CompletedTask.ConfigureAwait(ConfigureAwaitOptions.ForceYielding);
    }

    public Task StopAsync(CancellationToken cancellationToken)
    {
        Console.WriteLine($"Stop: {SynchronizationContext.Current}");
        return Task.CompletedTask;
    }

    public Task StartedAsync(CancellationToken cancellationToken) => Task.CompletedTask;

    public Task StoppedAsync(CancellationToken cancellationToken) => Task.CompletedTask;

    public Task StoppingAsync(CancellationToken cancellationToken) => Task.CompletedTask;
}

class MySynchronizationContext : SynchronizationContext { }
```

The above code yields the following output:
```
Starting: MySynchronizationContext
Start: 
Stop: 
```

While I'm expecting the following result:
```
Starting: MySynchronizationContext
Start: MySynchronizationContext
Stop: MySynchronizationContext
```

### Expected behavior

`SynchronizationContext.Current` is captured and lifecycle callbacks are executed in the captured context.

### Actual behavior

`IHost.RunAsync` resumes execution on an arbitrary thread and calls lifecycle callbacks without `SynchronizationContext` that is expected to be captured.

**Comment by steveharter** [comment]
I'll look at the inconsistency with StartingAsync

**Comment by NeverMorewd** [comment]
any update?

**Comment by Nihagy** [comment]
> My English is not very good and I used part of a translator, but I created an alternative, it may not be the best way but it works for the example given and you have to implement a constructor and the StartingAsync and StartAsync Methods I left them different on purpose just for example and added a GetCurrentSynchronizationContext method that uses reflection, which I don't recommend.
> 
> ### Known Workarounds
> ```cs
> using Microsoft.Extensions.DependencyInjection;
> using Microsoft.Extensions.Hosting;
> 
> var syncContext = new MySynchronizationContext();
> SynchronizationContext.SetSynchronizationContext(syncContext);
> 
> var builder = Host.CreateApplicationBuilder();
> builder.Services.AddHostedService<MyService>();
> 
> await builder.Build().RunAsync();
> 
> class MyService : IHostedLifecycleService
> {
>     private readonly SynchronizationContext _syncContext;
>
>     public MyService()
>     {
>           _syncContext = SynchronizationContext.Current;
>     }
>
>     public async Task StartingAsync(CancellationToken cancellationToken)
>     {
>         Console.WriteLine($"Starting: {_syncContext}");
>         await Task.CompletedTask;
>     }
>
>     public Task StartAsync(CancellationToken cancellationToken)
>     {
>         var value = GetCurrentSynchronizationContext();
>         Console.WriteLine($"Start: {value}");
>         return Task.CompletedTask;
>     }
> 
>     public Task StopAsync(CancellationToken cancellationToken)
>     {
>         SynchronizationContext.SetSynchronizationContext(_syncContext);
>         Console.WriteLine($"Stop: {SynchronizationContext.Current}");
>         return Task.CompletedTask;
>     }
> 
>     public Task StartedAsync(CancellationToken cancellationToken) => Task.CompletedTask;
> 
>     public Task StoppedAsync(CancellationToken cancellationToken) => Task.CompletedTask;
> 
>     public Task StoppingAsync(CancellationToken cancellationToken) => Task.CompletedTask;
>
>     public static SynchronizationContext GetCurrentSynchronizationContext()
>     {
>        var field = typeof(Thread).GetField("_synchronizationContext", BindingFlags.NonPublic | BindingFlags.Instance);
>        return (SynchronizationContext)field.GetValue(Thread.CurrentThread);
>     }
> }
> 
> class MySynchronizationContext : SynchronizationContext { }
> ```
> 
> O código acima produz a seguinte saída:
> 
> ```
> Starting: MySynchronizationContext
> Start: MySynchronizationContext
> Stop: MySynchronizationContext
> ```

**Comment by steveharter** [comment]
> I'll look at the inconsistency with StartingAsync

StartingAsync works since a new thread was not created.

> Why should it? I'm not sure why this API is special and should automatically propagate the sync context.

Agree

>My English is not very good and I used part of a translator, but I created an alternative, it may not be the best way but it works for the example given and you have to implement a constructor and the StartingAsync and StartAsync Methods I left them different on purpose just for example and added a GetCurrentSynchronizationContext method that uses reflection, which I don't recommend.

That workaround doesn't work for me - using reflection to get the `_synchronizationContext` value is the same as the [implementation.
](https://github.com/dotnet/runtime/blob/3e572e9d09026f386a57302bfd624abd7b660fb5/src/libraries/System.Private.CoreLib/src/System/Threading/SynchronizationContext.cs#L16)
