### ISSUE TITLE
Redundant conditional in OleDbDataReader.ProcessResults?

### ISSUE THREAD

**Issue by omajid** [dotnet/runtime#94262]
https://github.com/dotnet/runtime/blob/163bc5800b469bcb86d59b77da21965916a0f4ce/src/libraries/System.Data.OleDb/src/OleDbDataReader.cs#L1184-L1191

Seems we do the same thing in either branch. Is that intentional?

**Comment by stephentoub** [comment]
It looks like those two lines used to be different, each taking a different third argument to the ProcessResults call, but the third argument was actually being ignored by ProcessResults and so was removed in https://github.com/dotnet/runtime/pull/72667, resulting the if/else blocks being identical. They can be consolidated now back into a single call.
