### ISSUE TITLE
Conditional in HttpConnection.cs seems redundant?

### ISSUE THREAD

**Issue by omajid** [dotnet/runtime#94261]
https://github.com/dotnet/runtime/blob/7e316e20d65554aecdd6b7d45aebd1587b8945c3/src/libraries/System.Net.HttpListener/src/System/Net/Managed/HttpConnection.cs#L519-L533

The same code is executed if the conditional is true or false. Is the conditional supposed to do something different?

**Comment by stephentoub** [comment]
This code originally came from Mono, and history in this repo has those two blocks always being the same; looking in mono/mono, it goes back upwards of 15 years, and arrived like this after multiple refactorings.  I'm not sure what the original intent was, but we can delete the duplication now.
