### ISSUE TITLE
Should we AOT the XunitLogChecker tool?

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#94270]
The XunitLogChecker targets the tool runtime today (an LKG runtime).

We don't deploy this runtime during libraries testing, nor do we really want to take a dependency on deploying that runtime to the test machines.  We'll instead let the tool roll-forward and run on the test runtime.

This will work - except for the case that there is such a bad bug that the tool crashes too.

One thing @agocke suggested was that try native-AOT for the tool to make it work without a runtime dependency.  This would potentially make the tool less subject to runtime breaks.

**Comment by carlossanlop** [comment]
Closely related to https://github.com/dotnet/runtime/issues/94722

**Comment by agocke** [comment]
Fixed by https://github.com/dotnet/runtime/pull/103795
