### ISSUE TITLE
Host tests should move out of the build and use the libraries test infrastructure

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#94271]
Today host tests run on the build machine inside the build itself.  This causes problems - test failures are build failures, they only run on the configurations we happen to build on, etc.

We need to move those tests out of the build.  Since they are written as plain old xunit tests they should be able leverage the libraries test infrastructure.

**Comment by vitek-karas** [comment]
@elinor-fung has been working towards that for a while - we need to cleanup how the tests get their "Assets" first.

**Comment by elinor-fung** [comment]
This is the list I wrote up awhile back for what I think needed to happen:
- https://github.com/dotnet/runtime/issues/77800

**Comment by ViktorHofer** [comment]
> should be able leverage the libraries test infrastructure.

I would go as far as saying "they should leverage the Arcade common test infrastructure". The libraries test infrastructure is more complex and Arcade should already offer everything needed. AFAIK the host tests already use the VSTest runner and submitting to helix is fairly trivial with the Helix Sdk.

**Comment by agocke** [comment]
I'm going to close this as a dup of https://github.com/dotnet/runtime/issues/77800, as I think that covers everything we need
