### ISSUE TITLE
[InlineArray] should not have [EditorBrowsableState(Never)]

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#94283]
### Description

The `[InlineArray]` type is marked with `[EditorBrowsable(EditorBrowsableState.Never)]`:

https://github.com/dotnet/runtime/blob/655b177da2e423a04a60a331bc6c11fe5ec427c3/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/InlineArrayAttribute.cs#L11-L13

This seems... Wrong? There's no built-in C# syntax for inline arrays for now, so the attribute has to be used explicitly in user code. The fact it's hidden makes this clunkier than it needs to be. The attribute is already buried in a namespace that's explicitly documented as "unsafe" and only for advanced users, so this feels unnecessary.

Shouldn't we just remove this?
And if so, I take it the ship has sailed for .NET 8 GA at this point?

**Comment by MichalStrehovsky** [comment]
Cc @VSadov - I can't find where the EditorBrowsable came from. I don't see the API review mentioning this.

**Comment by stephentoub** [comment]
> Shouldn't we just remove this?

Yes, this should not be EditorBrowsableState.Never. We should remove it, and ideally service that for 8.

**Comment by Sergio0694** [comment]
Happy to take this and make a PR if this is up for grabs. I can also add the missing XML docs while at it 🙂

**Comment by tannergooding** [comment]
@Sergio0694, assigned to you

**Comment by VSadov** [comment]
I think the attribute was simply copied from other similar types when we still had assumptions that users will not need to put the attribute directly in the code, but instead compilers would emit it when implementing inline-array-like features.  
In the final design of the feature on C# side there is indeed no special syntax to declare inline array types and thus it requires using the attribute. 

@Sergio0694  Thanks for fixing this!!
