### ISSUE TITLE
Wasm Test failure: 'C:\helix\work\workitem\e\wbt' is not a valid project file

### ISSUE THREAD

**Issue by sbomer** [dotnet/runtime#94281]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=457776
Build error leg or test failing: Wasm.Build.Templates.Tests.InterpPgoTests.FirstRunGeneratesTableAndSecondRunLoadsIt(config: \"Release\")
Pull request: https://github.com/dotnet/runtime/pull/94101

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "C:\helix\work\workitem\e\wbt' is not a valid project file.",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

Output:
```
Executing - C:\helix\work\workitem\e\dotnet-latest\dotnet.exe run --no-silent -c Release --no-build --project C:\helix\work\workitem\e\wbt artifacts\browser_Release_jgn53utv_lea\browser_Release_jgn53utv_lea.csproj --forward-console  in pwd C:\helix\work\workitem\e\wbt artifacts\browser_Release_jgn53utv_lea
        	[DOTNET_ROOT] = C:\helix\work\workitem\e\dotnet-latest
        	[DOTNET_INSTALL_DIR] = C:\helix\work\workitem\e\dotnet-latest
        	[DOTNET_MULTILEVEL_LOOKUP] = 0
        	[DOTNET_SKIP_FIRST_TIME_EXPERIENCE] = 1
        	[PATH] = C:\helix\work\workitem\e\dotnet-latest;C:\helix\work\workitem\e\\dotnet-latest;D:\a\_work\1\s\artifacts\bin\chromedriver\chromedriver_win32;C:\helix\work\correlation\dotnet-latest;C:\helix\work\correlation\xharness-cli;C:\helix\work\correlation\dotnet-cli;C:\helix\work\correlation\chrome-win;C:\helix\work\correlation\chromedriver_win32;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Users\ContainerAdministrator\AppData\Local\Microsoft\WindowsApps;C:\Python;C:\python\scripts;C:\Program Files\nodejs\;C:\7z;C:\git\cmd;C:\Users\ContainerAdministrator\AppData\Roaming\npm;C:\Users\ContainerAdministrator\.jsvu\bin
        	[EM_WORKAROUND_PYTHON_BUG_34780] = 1
        [] 'C:\helix\work\workitem\e\wbt' is not a valid project file.
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=457776
**Error message validated:** `C:\helix\work\workitem\e\wbt' is not a valid project file.`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 11/1/2023 11:27:15 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[457776](https://dev.azure.com/dnceng-public/public/_build/results?buildId=457776)|dotnet/runtime|[Workloads-Wasm.Build.Templates.Tests.InterpPgoTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=457776&view=ms.vss-test-web.build-test-results-tab&runId=10316780&resultId=100150)|dotnet/runtime#94101|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|1|1|

**Comment by maraf** [comment]
Should be fixed by https://github.com/dotnet/runtime/pull/94265

cc @kg @ilonatommy

**Comment by ilonatommy** [comment]
You are right, closing.
