### ISSUE TITLE
[API Proposal]: Indexer / GetItem for {Immutable}HashSet

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#94302]
### Background and motivation

Hashsets have a TryGetValue member that allows you to TRY to get the value associated with an item in the hashset.  This is useful when you want the actual item in the hashset and not the "match" that might be generated by the comparer.

Hashsets should be extended with either an indexer or GetItem method that will get the value from the hashset or throw if it is not present (much like ```var x = dictionary[...];```)

### API Proposal

```csharp
namespace System.Collections.Generic;

public class Hashset<T> 
{
   public T this[T] {get;}
}
```

```csharp
namespace System.Collections.Immutable;

public class ImmutableHashset<T> 
{
   public T this[T] {get;}
}
```

### API Usage

```csharp

var GoodValue = MyHashset[OriginalValue];
```

### Alternative Designs

You could optionally add a    ```public T this[T] {set;}``` to set items in the hashsets as well.

### Risks

None that I can think of.

**Comment by vcsjones** [comment]
The indexer has previously been suggested at https://github.com/dotnet/runtime/issues/20073#issuecomment-277858966, however was removed before it went to API review because it's usefulness was questionable.

**Comment by eiriktsarpalis** [comment]
Agreed, it's a niche use case addressable using the `TryGetValue` methods. I don't think it would make sense to make it more accessible using an indexer.
