### ISSUE TITLE
dotnet run quits immediately on Mac (Apple Silicon) in certain scenarios.

### ISSUE THREAD

**Issue by gdar91** [dotnet/runtime#94315]
### Description

`dotnet run` quits immediately on Mac (Apple Silicon) when a project contains dots and the word Service in its name.

### Reproduction Steps

dotnet new webapi -o My -n My.Service
cd My
dotnet run

### Expected behavior

It should start the application.

### Actual behavior

It quits without outputting anything.

### Configuration

.NET SDK 7.0.402
MacOS Sonoma 14.1
Apple Silicon

**Comment by vcsjones** [comment]
This is related to, or a duplicate of, https://github.com/dotnet/runtime/issues/93716.

**Comment by gdar91** [comment]
> This is related to, or a duplicate of, #93716.

I couldn't find that issue when I tried searching with similar terms. Thank you for pointing it out. It's the same problem, so this is a duplicate. I'm closing it.
