### ISSUE TITLE
System.Text.Json JsonConverter doesn't serialize nullable properties

### ISSUE THREAD

**Issue by bengarrison** [dotnet/runtime#94314]
### Description

Hey, not sure if this is a bug or intended.. but I was hoping to use jsonconverter for a nullable decimal property to return 0 instead of null.. but it only performs the conversion when deserializing.  Doesn't even hit the breakpoint in the Write function, but it does on the Read when deserializing.  

### Reproduction Steps

Don't have my exact code on me, but here's chatGPT's code:

```
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

public class NullableDecimalToZeroConverter : JsonConverter<decimal?>
{
    public override decimal? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType == JsonTokenType.Null)
            return 0;

        return reader.GetDecimal();
    }

    public override void Write(Utf8JsonWriter writer, decimal? value, JsonSerializerOptions options)
    {
        if (!value.HasValue)
            writer.WriteNumberValue(0);
        else
            writer.WriteNumberValue(value.Value);
    }
}

public class Product
{
    [JsonConverter(typeof(NullableDecimalToZeroConverter))]
    public decimal? Price { get; set; }
}

public void DoTheJsonSerialization()
{
    var options = new JsonSerializerOptions
    {
        Converters = { new NullableDecimalToZeroConverter() }
    };

    string jsonString = JsonSerializer.Serialize(new Product(), options);
}
```

### Expected behavior

resulting serialized json should be 
`{"Price":0}`

### Actual behavior

but it's still
`{"Price":null}`

### Known Workarounds

tried newtonsoft.json but had the same issue.

### Other information

Wasn't sure if this is a bug or not, but since the purpose of json converter is to convert the json.. I figured this should be something that is possible :)

**Comment by ovska** [comment]
You need to override the `HandleNull`-property of `JsonConverter`. Without this, the serializer doesn't pass null json tokens to the converter at all.

With the following override in the converter, your example produces a desired result for me.

```cs
public override bool HandleNull => true;
```

**Comment by eiriktsarpalis** [comment]
It's what @ovska said. I hope this answers your question.

**Comment by bengarrison** [comment]
@ovska that was it! thank you, and sorry i'm not sure how i missed this!
