### ISSUE TITLE
Replace HashHelpers.Combine with HashCode.Combine

### ISSUE THREAD

**Issue by morganbr** [dotnet/runtime#9433]
```System.HashCode``` was recently added in order to make high-quality fast hashing easy. We should replace usage of ```HashHelpers.Combine```, an internal low-quality hash combiner with ```HashCode.Combine```. It should lead to better distribution in dictionaries and the hashing should be nearly as fast.

**Comment by stephentoub** [comment]
What we planned to do here has been done.
