### ISSUE TITLE
Unhandled NullReferenceException in System.Net.Sockets.SocketPal.GetIPPacketInformation() causing process termination

### ISSUE THREAD

**Issue by ShreyasZare** [dotnet/runtime#94346]
### Description

I recently updated application code to use `Socket.ReceiveMessageFromAsync()` instead of `Socket.ReceiveFromAsync()` to be able to read socket's local IP address from `SocketReceiveMessageFromResult.PacketInformation.Address`. While it works as expected, I am getting reports from users that the application is crashing on Windows 10 with .NET Runtime error logged in Windows Event Viewer.

The exception is thrown in .NET Runtime causing the process to terminate. The exception occurs only once or twice in 24 hrs and there is an Windows Event Log entry with stack trace shown below:

```
Application: DnsService.exe
CoreCLR Version: 7.0.1323.51816
.NET Version: 7.0.13
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.Sockets.SocketPal.GetIPPacketInformation(ControlData* controlBuffer)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationReceiveMessageFrom()
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSyncSuccess(Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.SocketAsyncEventArgs.<>c.<.cctor>b__176_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading.ThreadPoolTypedWorkItemQueue`2.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

I tried to downgrade to .NET 7.0.10 which the application previously used and still seeing same error in Windows Event Viewer:

```
Application: DnsService.exe
CoreCLR Version: 7.0.1023.36312
.NET Version: 7.0.10
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.Sockets.SocketPal.GetIPPacketInformation(ControlData* controlBuffer)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationReceiveMessageFrom()
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSyncSuccess(Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.SocketAsyncEventArgs.<>c.<.cctor>b__176_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading.ThreadPoolTypedWorkItemQueue`2.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

The stack trace indicates that the exception is coming from inside of .NET Runtime and thus it cannot be handled from application code.

### Reproduction Steps

The application uses something similar to code snippet shown below with proper exception handling being done:

```
IPEndPoint localEP = new IPEndPoint(IPAddress.Any, 53);
Socket udpListener = new Socket(localEP.AddressFamily, SocketType.Dgram, ProtocolType.Udp);
udpListener.Bind(localEP);

byte[] recvBuffer = new byte[1024];
EndPoint epAny = new IPEndPoint(IPAddress.Any, 0);
SocketReceiveMessageFromResult result;

try
{
   while (true)
   {
      result = await udpListener.ReceiveMessageFromAsync(recvBuffer, SocketFlags.None, epAny);

      if (result.ReceivedBytes > 0)
      {
         IPAddress localAddress = result.PacketInformation.Address;
        //process the UDP request
      }
   }
}
catch (Exception ex)
{
   //log error
}
```

### Expected behavior

The application process should not terminate.

### Actual behavior

The application process terminates due to unhandled exception thrown inside of .NET Runtime as per logs in Windows Event Viewer.

### Regression?

Tried it on .NET Version: 7.0.13 and .NET Version: 7.0.10 and had same issue. The only difference with the application is that its now using `Socket.ReceiveMessageFromAsync()` instead of `Socket.ReceiveFromAsync()`.

### Configuration

- Tried with .NET Version: 7.0.10 and .NET Version: 7.0.13 and had same results.
- The issue was reported on Windows 10. The same application running on Linux did not have any issues.
- The platform with crash reports had x64 CPU. Not tested on any other platform.
- The issue came on 3 different Windows 10 machines independently so does not seem to be related to any specific config.

**Comment by wfurt** [comment]
Any chance you can share core dump @ShreyasZare? The error happens on ThreadPool and that is the reason why normal `catch` does not work. From the brief look it seems like the `controlBuffer` is not set by OS once in a while - a condition .NET does not expect. 

Just to clarify: from the code above it does not seems like you use `SocketAsyncEventArgs` directly or there would be multiple concurrent receives, right? 

This code did not change for years so I would not expect any differences with upgrades (still appreciate the effort to try)

**Comment by ShreyasZare** [comment]
There is another error entry seen in Event Viewer a few times against .NET Runtime with details as below:
```
Application: DnsService.exe
CoreCLR Version: 7.0.1323.51816
.NET Version: 7.0.13
Description: The process was terminated due to an internal error in the .NET Runtime at IP 0x00007FFBC1A27E07 (0x00007FFBC1960000) with exit code 0x80131506.
```
Not sure if this is related to the original issue. Here is the crash dump that got generated for the above error log: 
[DnsService.exe.13888.dmp](https://github.com/dotnet/runtime/files/13437441/DnsService.exe.13888.dmp)

**Comment by ShreyasZare** [comment]
> Just to clarify: from the code above it does not seems like you use `SocketAsyncEventArgs` directly or there would be multiple concurrent receives, right?

There are multiple Tasks running that call `ReceiveMessageFromAsync` async. You can refer the [implementation here](https://github.com/TechnitiumSoftware/DnsServer/blob/master/DnsServerCore/Dns/DnsServer.cs#L357) if that helps.

**Comment by wfurt** [comment]
Can you please try to reproduce it with 8.0 @ShreyasZare? There was quite a big change in UDP processing at the end of the release and it _may_ help. (and 7.0 will be out of support soon) 

I failed to decode managed info from the dumps ;( Do you know if that was Windows 64bit process? There is also some setting for mini dump to collect different amount of info. Perhaps set that to full would be useful. 


I'm also somewhat curious about the motivation., Would you expect `Address` be anything else than the Socket's local address? The `ReceiveMessageFromAsync` is somewhat significantly more expensive than `ReceiveFromAsync`. Maybe that is not critical. (and also `ReceiveFromAsync` got some updates in 8.0 to avoid constant allocations of `EndPoint` to make it even more efficient.

**Comment by wfurt** [comment]
I can understand what DHCP would need the interface. I suspect that the `controlBuffer` sometimes does not have everything set (perhaps function of the load) and we do not have safe checks in place to catch that. Decoding managed structures from `FinishOperationReceiveMessageFrom` would be crucial IMHO.

**Comment by wfurt** [comment]
Do you have any update @ShreyasZare?

**Comment by wfurt** [comment]
I don't know why the update would fix it ... but I'm happy to hear it is better. I'm going to close now, feel free to reopen if there is update.
