### ISSUE TITLE
Incorrect GNU linker detection when cross-compiling on non-GNU-linker host OS

### ISSUE THREAD

**Issue by directhex** [dotnet/runtime#94355]
### Description

LLD, the LLVM linker, does not support s390x architecture. As a result, it is necessary to link using BFD or Gold, the GNU linkers. If you don't pass any `-fuse-ld=` flags to Clang, it assumes BFD. However, if you _only_ have BFD for the target architecture (i.e. `s390x-linux-gnu-ld` without `ld`, then our linker detection fails:

https://github.com/dotnet/runtime/blob/df6fdefa27068126794b253d4d822706221a92db/eng/native/configuretools.cmake#L80

will error out with:

```
clang-16: error: unable to execute command: Executable "ld" doesn't exist!
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```

Which, in our logic, causes the final `else()` block to apply, setting `LD_OSX`:

https://github.com/dotnet/runtime/blob/df6fdefa27068126794b253d4d822706221a92db/eng/native/configuretools.cmake#L85-L93

Later, this value is used to determine command line flags passed to the linker:

https://github.com/dotnet/runtime/blob/df6fdefa27068126794b253d4d822706221a92db/eng/native/functions.cmake#L256-L268

BFD does not support the OSX `-exported_symbols_list,` syntax, it needs to be passed with the `--version-script=` syntax from the earlier `if` block:

```
  /usr/local/bin/s390x-linux-gnu-ld:/home/directhex/Projects/runtime/artifacts/obj/linux-s390x.Release/fxr/standalone/hostfxr.exports: file format not recognized; treating as linker script
  /usr/local/bin/s390x-linux-gnu-ld:/home/directhex/Projects/runtime/artifacts/obj/linux-s390x.Release/fxr/standalone/hostfxr.exports:1: syntax error
```

This problem can be worked around by adding a valid `--target=<triple>` flag to the `-Wl,--version` call in configuretools.cmake (which adds the triple prefix to the forked ld command), but with the twisty nesting of imports, it's not clear to me yet how to get the triple into that file.

**Comment by directhex** [comment]
@uweigand

**Comment by am11** [comment]
> This problem can be worked around by adding a valid `--target=<triple>`

Sounds like this will fix the error: https://github.com/dotnet/arcade/compare/main...am11:arcade:patch-6. I don't have test apparatus set up for s390x atm, can you give it a go?

**Comment by directhex** [comment]
Amazing as always, Adeel

```
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:05:24.70
```

**Comment by am11** [comment]
Great! I learned this trick from @ayakael (https://github.com/dotnet/arcade/commit/dd41f2747ec2a1171eeed1efdcf6a87bb92bc565) 😆

**Comment by directhex** [comment]
@am11 are you planning to PR your Arcade patch?
