### ISSUE TITLE
GeneratedComClass doesn't apply to inherited classes

### ISSUE THREAD

**Issue by jtschuster** [dotnet/runtime#94357]
Placing GeneratedComClass on a base class doesn't enable deriving types to work with source generated COM.

Should we check for base classes that have the IComExposedDetails as well here?
https://github.com/dotnet/runtime/blob/df6fdefa27068126794b253d4d822706221a92db/src/libraries/System.Runtime.InteropServices/src/System/Runtime/InteropServices/Marshalling/IComExposedDetails.cs#L21C49-L21C49

```
	[GeneratedComInterface]
	[Guid("c5356681-8f8c-423a-959c-2d91f17215d3")]
	internal partial interface IFoo
	{
		int get();
	}

	[GeneratedComClass]
	[Guid("9f826481-4d92-4499-ab26-c40d9f77435b")]
	internal partial class FooBase : IFoo
	{
		public int get() => 42;
	}

	internal class Foo<T> :FooBase
	{
	}
int Main()
{
                        var cw = new StrategyBasedComWrappers();
			var foo = new Foo<int>();
			nint iptr = cw.GetOrCreateComInterfaceForObject(foo, CreateComInterfaceFlags.None);
			IFoo f = (IFoo)cw.GetOrCreateObjectForComInstance(iptr, CreateObjectFlags.None); // Fails - iptr does not implement IFoo
}
```

**Comment by AaronRobinsonMSFT** [comment]
I'd like to understand this scenario before we go after it. I have some questions about how overrides are expected to and what benefits we gain as opposed to just having people place it on the most derived type.

**Comment by jtschuster** [comment]
The more I think about it, I'm not sure there's a great way to do this without breaking trimming and AOT. Maybe we should just require it on all classes that are exposed to COM.

**Comment by jkoritzinsky** [comment]
There's also no efficient way to detect this scenario in a source generator. We should just require it on all classes that are exposed to COM.

**Comment by AaronRobinsonMSFT** [comment]
> There's also no efficient way to detect this scenario in a source generator. We should just require it on all classes that are exposed to COM.

Nice. Does it make sense to detect that if the immediate base class has `GeneratedComClass` that we emit a warning? I can imagine people doing odd things with managed inheritance for COM class implementation but I'm not sure that is something we should encourage.

**Comment by jkoritzinsky** [comment]
Yes, we can write an analyzer that detects that case and emits a warning in an efficient way.
