### ISSUE TITLE
Blazor WASM NET 6.0 app fail to build with NET8 RC2 SDK under Framework

### ISSUE THREAD

**Issue by wasabii** [dotnet/runtime#94379]
### Description

>C:\dev\test\Client\Program.cs(16,48): error CS0234: The type or namespace name 'App' does not exist in the namespace
'test.Client' (are you missing an assembly reference?) [C:\dev\test\Client\test.Client.App.csproj] during Build in VS, as well as running 'msbuild' command. Additionally receives this warning: 

>CSC : warning CS9057: The analyzer assembly 'C:\Program Files\dotnet\sdk\8.0.100-rc.2.23502.2\Sdks\Microsoft.NET.Sdk.
Razor\source-generators\Microsoft.NET.Sdk.Razor.SourceGenerators.dll' references version '4.8.0.0' of the compiler, whi
ch is newer than the currently running version '4.7.0.0'. [C:\dev\test\Client\test.Client.App.csproj]

'dotnet build' command succeeds.

### Reproduction Steps

Create a new Blazor WASM app using the dotnet new tool, specifying net6.0 as the Framework. Add global.json changing SDK to 8.0 (enable prerelease, etc, etc). Rebuild in VS. The error above shows for the App class.

However, after a couple minutes, VS intellisense is able to hilight and show the App class in green. Build still fails.

### Expected behavior

Should work.

### Actual behavior

Doesn't work.

### Regression?

Yes?

### Other information

My hypothesis is the design time build is succeeding, thus intellisense has an assembly to play with. But builds in the .NET 8 SDK on Framework both in VS and from command line have something wrong.

**Comment by huoyaoyuan** [comment]
How about `dotnet build` in command line? `msbuild` command is shipped with VS, instead of .NET SDK.

Are you using VS 17.7 (stable channel), which contains version 4.7 of compiler? The recent version of .NET 8 SDK seems to be only compatible with VS 17.8 Preview.

**Comment by maraf** [comment]
I'm not able to reproduce the issue on my machine. Can you please share binlogs? Here is how can you collect them in VS https://github.com/dotnet/msbuild/blob/main/documentation/wiki/Providing-Binary-Logs.md#capturing-binary-logs-through-visual-studio or if the error occurs also when building from command line, you can pass `-bl` argument, eg. `dotnet build -bl`.

**Comment by wasabii** [comment]
So, I think I isolated it to putting:

```
{
    "sdk": {
        "version": "8.0.100-rc.2.23502.2",
        "allowPrerelease": true
    }
}
```

In global.json.

**Comment by wasabii** [comment]
In Framework, it fails on CoreCompile.

On Framework, it uses csc.exe from:

C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\Roslyn\csc.exe 

On Core it uses csc from:

C:\Program Files\dotnet\dotnet.exe exec "C:\Program Files\dotnet\sdk\8.0.100-rc.2.23502.2\Roslyn\bincore\csc.dll"

**Comment by huoyaoyuan** [comment]
Can you pin SDK to a **lower** version installed in your machine? 8.0 SDK RC is incompatible with lower version of VS.

**Comment by wasabii** [comment]
Okay. As long as this is expected, it's not a bug. I didn't expect it, since it's only a single project type that fails.
