### ISSUE TITLE
Not so sure about this.

### ISSUE THREAD

**Issue by tactical-drone** [dotnet/runtime#94373]
https://github.com/dotnet/runtime/blob/b4823d05c38d7eb44de0db41ba9ba6c6a2df4e46/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Sources/ManualResetValueTaskSourceCore.cs#L164

I would put it further down, after the return.

**Comment by stephentoub** [comment]
It's correct where it is. It has to be set before the interlocked.
