### ISSUE TITLE
Why would the continuation be null at this stage? Where did this code come from?

### ISSUE THREAD

**Issue by tactical-drone** [dotnet/runtime#94375]
https://github.com/dotnet/runtime/blob/18ee31dc1e265750b792ec1b1ee57794e4a87b04/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Sources/ManualResetValueTaskSourceCore.cs#L222

**Comment by stephentoub** [comment]
If the operation completes before the consumer hooks up a continuation.
