### ISSUE TITLE
Test timeout in System.Security.Cryptography.OpenSsl.Tests on mono Amd64 OSX

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#94436]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=461011
Build error leg or test failing: System.Security.Cryptography.OpenSsl.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/94417

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "[Long Running Test] 'System.Security.Cryptography.Rsa.Tests.RSAKeyFileTests.ReadEncryptedRsa16384'",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

[net9.0-osx-Debug-x64-Mono_release-OSX.1200.Amd64.Open](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=461011&view=ms.vss-test-web.build-test-results-tab&runId=10415762&resultId=204456)

Seems like the test hung?
```
System.Security.Cryptography.OpenSsl.Tests: [Long Running Test] 'System.Security.Cryptography.Rsa.Tests.RSAKeyFileTests.ReadEncryptedRsa16384', Elapsed: 00:02:06
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=461011
**Error message validated:** `[Long Running Test] 'System.Security.Cryptography.Rsa.Tests.RSAKeyFileTests.ReadEncryptedRsa16384'`
**Result validation: :x:** Known issue did not match with the provided build.
**Validation performed at:** 11/10/2023 9:43:34 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[481157](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481157)|dotnet/runtime|[System.Security.Cryptography.OpenSsl.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481157&view=ms.vss-test-web.build-test-results-tab&runId=11050232&resultId=200117)|dotnet/runtime#94664|
|[480314](https://dev.azure.com/dnceng-public/public/_build/results?buildId=480314)|dotnet/runtime|[System.Security.Cryptography.OpenSsl.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=480314&view=ms.vss-test-web.build-test-results-tab&runId=11022674&resultId=208746)||
|[479427](https://dev.azure.com/dnceng-public/public/_build/results?buildId=479427)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=479427&view=ms.vss-test-web.build-test-results-tab&runId=10995382&resultId=197479)|dotnet/runtime#93879|
|[479421](https://dev.azure.com/dnceng-public/public/_build/results?buildId=479421)|dotnet/runtime|[System.Security.Cryptography.OpenSsl.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=479421&view=ms.vss-test-web.build-test-results-tab&runId=10994998&resultId=208738)||
|[479411](https://dev.azure.com/dnceng-public/public/_build/results?buildId=479411)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=479411&view=ms.vss-test-web.build-test-results-tab&runId=10994886&resultId=197479)|dotnet/runtime#94621|
|[478503](https://dev.azure.com/dnceng-public/public/_build/results?buildId=478503)|dotnet/runtime|[System.Security.Cryptography.OpenSsl.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=478503&view=ms.vss-test-web.build-test-results-tab&runId=10964754&resultId=200094)||
|[478488](https://dev.azure.com/dnceng-public/public/_build/results?buildId=478488)|dotnet/runtime|[System.Security.Cryptography.OpenSsl.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=478488&view=ms.vss-test-web.build-test-results-tab&runId=10964636&resultId=200100)|dotnet/runtime#95143|
|[478160](https://dev.azure.com/dnceng-public/public/_build/results?buildId=478160)|dotnet/runtime|[System.Security.Cryptography.OpenSsl.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=478160&view=ms.vss-test-web.build-test-results-tab&runId=10955880&resultId=204262)|dotnet/runtime#94882|
|[477375](https://dev.azure.com/dnceng-public/public/_build/results?buildId=477375)|dotnet/runtime|[System.Security.Cryptography.OpenSsl.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=477375&view=ms.vss-test-web.build-test-results-tab&runId=10929614&resultId=199818)|dotnet/runtime#94918|
|[475783](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475783)|dotnet/runtime|[System.Security.Cryptography.OpenSsl.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475783&view=ms.vss-test-web.build-test-results-tab&runId=10878478&resultId=204491)|dotnet/runtime#94861|
|[474932](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474932)|dotnet/runtime|[System.Security.Cryptography.OpenSsl.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474932&view=ms.vss-test-web.build-test-results-tab&runId=10850438&resultId=198257)|dotnet/runtime#94915|
|[474901](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474901)|dotnet/runtime|[System.Security.Cryptography.OpenSsl.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474901&view=ms.vss-test-web.build-test-results-tab&runId=10850012&resultId=200051)|dotnet/runtime#94647|
|[474827](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474827)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474827&view=ms.vss-test-web.build-test-results-tab&runId=10846504&resultId=197429)||
|[474685](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474685)|dotnet/runtime|[System.Security.Cryptography.OpenSsl.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474685&view=ms.vss-test-web.build-test-results-tab&runId=10842038&resultId=200051)|dotnet/runtime#94737|
|[472393](https://dev.azure.com/dnceng-public/public/_build/results?buildId=472393)|dotnet/runtime|[System.Security.Cryptography.OpenSsl.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=472393&view=ms.vss-test-web.build-test-results-tab&runId=10771742&resultId=208674)|dotnet/runtime#92483|
|[466316](https://dev.azure.com/dnceng-public/public/_build/results?buildId=466316)|dotnet/runtime|[System.Net.Quic.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=466316&view=ms.vss-test-web.build-test-results-tab&runId=10589808&resultId=201274)|dotnet/runtime#94590|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|9|16|

**Comment by Jozkee** [comment]
> Result validation: ❌ Known issue did not match with the provided build.

@dotnet/dnceng build analysis looking at the latest attempt but the error is on attempt 1 so issue validation is failing.

**Comment by markwilkie** [comment]
@AlitzelMendez and @missymessa
