### ISSUE TITLE
System.Net.Sockets.SocketException (10049): The requested address is not valid in its context.

### ISSUE THREAD

**Issue by tactical-drone** [dotnet/runtime#94430]
### Description

Ever since the latest .net8 nightlies (6 months ago) I got this error. (AddressNotAvailable)

Maybe a year ago when .net8 just came out no such issues existed. This is new. 

### Reproduction Steps

Try use `socket.SendToAsync` where the socket is in UDP mode (sending to different destinations). Only in Release mode and only when not running in the IDE will it give this error 50% of the time. Some destinations just wont work even though there is a UDP listener there. 

It also happens to the first couple of UDP sockets then suddenly everything just works. I create many sockets, like the first one succeeds, the next 4 fail and from then on it just works. Very strange. 

### Expected behavior

$

### Actual behavior

Void Throw() System.Net.Sockets.SocketException (10049): The requested address is not valid in its context.

### Regression?

Most definitely. 

Digging into the code reveals that this error is mapped from interop as `EADDRNOTAVAIL` or `ENOENT`. But which one?

I am stuck, this needs to be fixed. 

### Configuration

SDK Version: 8.0.200-preview.23530.15

**Comment by wfurt** [comment]
Do you actually use debug runtime? If not the actual binaries are the same. The issue is difficult to act on as it does not have much information. Do you use dual mode `Socket`  and/or IPv6 destinations? Some sample repro code would be beneficial.

**Comment by tactical-drone** [comment]
Turns out those ports were suddenly being used by my operating system, that is why they were not available.

**Comment by tactical-drone** [comment]
Still does not explain why it worked 50% of the time but anyway.

**Comment by tactical-drone** [comment]
Something is broken.

![image](https://github.com/dotnet/runtime/assets/1815319/aaf78f79-5e1e-4479-8ec8-46f332b9ed3e)

**Comment by tactical-drone** [comment]
Turn sout those ports are in use.

**Comment by tactical-drone** [comment]
No that was bad luck on one port. Something is still broken
