### ISSUE TITLE
Usability Issues in HttpClient

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/runtime#94471]
I've moved most of this issue to dotnet dos. Remaining things to discuss here:

* Should `PostAsync()` and `GetAsync()` have an overload that takes `HttpCompletionOption`?
* The lack of character set differentation in `ReadStringAsync()` be addressed or just documented as-is?

-------------------------------

As some may recall we built a custom client to deal with the fact that even the synchronous Send API will deadlock if called from a threadpool thread. (This comes as a big surprise when the only sign of async is the ASP.NET Core controller twenty stack frames below). However, more async-capable calls have appeared to outside servers, thus we are trying to use the stock HttpClient again.

We have encountered the following design issues (some of these may only be doc issues but even so ...)

1) It's not clear how to abort generating the request body in the middle (due to a thrown exception while generating content). That is, bailing out of HttpContent.SerializeToStreamAsync() needs proper documentation for how to do it, if it works at all. On my first attempt I found it would not bail out of the request but the server would see the partial request as a complete request.

2) On calling HttpResponse.Content.ReadAsStreamAsync() we end up in the worst of both worlds. We have documentation on one hand that reads "Serialize the HTTP content and return a stream that represents the content as an asynchronous operation." and on the other hand it reads "Note that this method will internally buffer the content unless CreateContentReadStreamAsync() has been implemented to do otherwise." with no clear way to guarantee as the response receiver which behavior you get. This leads to having all the downsides of reading the whole response into a memory stream at once but also all the downsides of having to manage the lifetime of the HttpResponse and the HttpClient as that stream ascends up the stack past where the HttpClient should normally be disposed. (Yes we know about HttpClientFactory...)

[As a side note; in my custom client this works correctly; the ContentStream is the live stream, not a memory stream, and you dispose the client while ascending the stack, and the stream can still be read from.]

3) Ever try to call an infinite source with HttpResponse.Content.ReadAsStreamAsync()? It doesn't work right. HttpClient.GetStreamAsync() does, assuming you don't have to look at the response headers. Trying to make this work via GetAsync() was beyond reach of stackoverflow. https://stackoverflow.com/questions/77282656/how-to-retrieve-a-truly-large-file-using-system-net-http-httpclient (Question is actually talking about a >2GB file; I always had both scenarios in mind.)

4) HttpResponse.Content.ReadAsStringAsync() does content encoding detection in a stupid way and I guarantee you there's a lot of stuff out there that works by accident because of it. It should either be a lot smarter or it should be better documented. Example: Third party server returns json with content-type "application/json"; client calls ReadAsStringAsync() and passes the string to NewtsonSoft.JSON (which doesn't take a byte array); after a server upgrade, the server starts encoding some responses in UTF-16 (valid JSON encodings are UTF-8, UTF-16LE, UTF-16BE, UTF-32LE, UTF-32BE) and doesn't include a BOM because the JSON spec says don't do that. ReadAsStringAsync() starts returning garbage, and the developer has _no idea_ what's wrong. (There's no such content type as application/json; charset=UTF-16.) Browsers do tons of encoding autodetection that's a lot harder to fool; thus the apparently identical APIs in Javascript don't have similar issues.

**Comment by ManickaP** [comment]
> 1. It's not clear how to abort generating the request body in the middle (due to a thrown exception while generating content). That is, bailing out of HttpContent.SerializeToStreamAsync() needs proper documentation for how to do it, if it works at all. On my first attempt I found it would not bail out of the request but the server would see the partial request as a complete request.

Throwing an exception is the way. I just tested it (HTTP/1.1 against Kestrel) and it closes the connection as expected and the server is reporting unexpected end of stream (or just closed connection without any data sent if the content data didn't exceed the client connection buffer of 4KB). If you're observing different behavior, can you share your client code and server details?

> 2. On calling HttpResponse.Content.ReadAsStreamAsync() we end up in the worst of both worlds. We have documentation on one hand that reads "Serialize the HTTP content and return a stream that represents the content as an asynchronous operation." and on the other hand it reads "Note that this method will internally buffer the content unless CreateContentReadStreamAsync() has been implemented to do otherwise." with no clear way to guarantee as the response receiver which behavior you get. This leads to having all the downsides of reading the whole response into a memory stream at once but also all the downsides of having to manage the lifetime of the HttpResponse and the HttpClient as that stream ascends up the stack past where the HttpClient should normally be disposed. (Yes we know about HttpClientFactory...)

You have to use `HttpCompletionOption.ResponseHeadersRead` if you don't want the response content to be buffered, which is the default behavior. All `HttpClient` methods returning `HttpResponseMessage` have an overload taking this argument, e.g.:https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.getasync?view=net-7.0#system-net-http-httpclient-getasync(system-string-system-net-http-httpcompletionoption). When you set this to `ResponseHeadersRead` you'll get response content stream instead of `MemoryStream` as expected.

> 3. Ever try to call an infinite source with HttpResponse.Content.ReadAsStreamAsync()? It doesn't work right. HttpClient.GetStreamAsync() does, assuming you don't have to look at the response headers. Trying to make this work via GetAsync() was beyond reach of stackoverflow. https://stackoverflow.com/questions/77282656/how-to-retrieve-a-truly-large-file-using-system-net-http-httpclient (Question is actually talking about a >2GB file; I always had both scenarios in mind.)

Same as point 2., answered above.

> 4. HttpResponse.Content.ReadAsStringAsync() does content encoding detection in a stupid way and I guarantee you there's a lot of stuff out there that works by accident because of it. It should either be a lot smarter or it should be better documented. Example: Third party server returns json with content-type "application/json"; client calls ReadAsStringAsync() and passes the string to NewtsonSoft.JSON (which doesn't take a byte array); after a server upgrade, the server starts encoding some responses in UTF-16 (valid JSON encodings are UTF-8, UTF-16LE, UTF-16BE, UTF-32LE, UTF-32BE) and doesn't include a BOM because the JSON spec says don't do that. ReadAsStringAsync() starts returning garbage, and the developer has no idea what's wrong. (There's no such content type as application/json; charset=UTF-16.) Browsers do tons of encoding autodetection that's a lot harder to fool; thus the apparently identical APIs in Javascript don't have similar issues.

Once again, I did a small test and `ReadAsStringAsync` does take into account charset specified in the "Content-Type" header. Could you please share you example of a response (header and body) and the client code for which it doesn't work?

**Comment by jhudsoncedaron** [comment]
@ManicaP: Not seeing that overload on PostAsync : https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.postasync?view=net-7.0 ; however SendAsync has such an overload.

It would be really easy to fix the documentation for ReadAsStreamAsync to reference SendAsync and HttpCompletionOption .

The `ReadAsStringAsync()` nonsense is easy to reproduce; but it too may well be a doc issue (as in this is expected to not work). Minimized reproduction:

```
using System.Net;
using System.Net.Http;
using System.Net.Sockets;
using System.Text;

var s = new Socket(SocketType.Stream, ProtocolType.Tcp);
var e = new IPEndPoint(IPAddress.Loopback, 0);
s.Bind(e);
s.Listen();

new System.Threading.Thread(() =>
{
    for (; ; )
    {
        // Ghetto HTTP CLient
        var s2 = s.Accept();
        var buf = new byte[4096];
        s2.Receive(buf);
        s2.Send(Encoding.ASCII.GetBytes("HTTP/1.0 200 OK\r\nContent-Type:application/json\r\n\r\n"));
        s2.Send(Encoding.Unicode.GetBytes("{\"n\":0}"));
        s2.Close();
    }
}).Start();

var h = new HttpClient();
var str = h.GetAsync("http://localhost:" + ((IPEndPoint)s.LocalEndPoint!).Port.ToString() + "/").Result.Content.ReadAsStringAsync().Result;
Console.WriteLine(str.Length); // Reports 14, should be 7
Console.WriteLine(str);
```

**Comment by jhudsoncedaron** [comment]
"[Bail out of request] Throwing an exception is the way. I just tested it " Did you close the stream? The obvious construction for a generator would do `using var writer = new StreamWriter(stream)` in the callback method. I'm pretty sure since you got it to work this too needs only a doc fixup.

**Comment by ManickaP** [comment]
> "[Bail out of request] Throwing an exception is the way. I just tested it " Did you close the stream? The obvious construction for a generator would do `using var writer = new StreamWriter(stream)` in the callback method. I'm pretty sure since you got it to work this too needs only a doc fixup.

The stream is passed as an argument, you're not the owner of it, you cannot close it or dispose it. If you need to use `StreamWriter` you should tell it not to dispose the stream, e.g. this [constructor](https://learn.microsoft.com/en-us/dotnet/api/system.io.streamwriter.-ctor?view=net-7.0#system-io-streamwriter-ctor(system-io-stream-system-text-encoding-system-int32-system-boolean)) takes `leaveOpen` argument.

> Not seeing that overload on PostAsync : https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.postasync?view=net-7.0 ; however SendAsync has such an overload.

My bad, the argument is present in `GetAsync` and `SendAsync`. 

> It would be really easy to fix the documentation for ReadAsStreamAsync to reference SendAsync and HttpCompletionOption .

`HttpClient` is not the only user of `HttpContent`, whereas the concept of buffering the response content is specific to `HttpClient`.  For example, if you use `HttpMessageInvoker` directly, no buffering will take place. 
Side note, you can also use [HttpClient.GetStreamAsync](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.getstreamasync?view=net-7.0) to avoid buffering.

> The ReadAsStringAsync() nonsense is easy to reproduce; but it too may well be a doc issue (as in this is expected to not work). Minimized reproduction:

I see, you're not sending charset. There's no automatic encoding detection from the data itself happening. You either need to know what the server is sending and read the data appropriately yourself. Or there's encoding detection from BOM baked in [`StreamReader`](https://learn.microsoft.com/en-us/dotnet/api/system.io.streamreader.-ctor?view=net-7.0#system-io-streamreader-ctor(system-io-stream-system-boolean)) which you could use.

**Comment by jhudsoncedaron** [comment]
Well that settles it. Every last thing is a doc issue but I'm going "how on earth was I expected to know that". I knew the ReadAsStringAsync() one only from reading the source code. I would have otherwise assumed it would do some baseline encoding detect if no BOM given; however it does not.

**Comment by ManickaP** [comment]
I see you filed an documentation issue, thank you.
I'll close this then.
