### ISSUE TITLE
Add publish option for NativeAOT to produce .lib file for shared libs

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#94480]
### Background and motivation

We're experimenting with using NativeAOT to build shared libraries to consume from native applications. This works great, but it's currently pretty clunky to use, as it requires you to use `LoadLibrary` (or `LoadPackagedLibrary`), and then `GetProcAddress`. It would be nice to be able to just get a .lib file as well in the publish folder, so that you could then just use `__declspec(dllimport)` in your header, and the linker would do all the extra binding work for you.

> [!NOTE]
> To clarify: I'm aware that NativeAOT can produce a .lib for static libs, but this is about having a .lib for shared libs (ie. .dll-s).

It is possible to manually create a .lib (ie. using `dumpbin` -> create the exports file -> `lib`), but it's super clunky. It would be much better if NativeAOT just produced the .lib file for you, since it should be able to do that by just asking the linker.

cc. @MichalStrehovsky @AaronRobinsonMSFT

### Use case example

Essentially, the following should work:

```csharp
[UnmanagedCallersOnly(EntryPoint = "Foo")]
public static int Foo(int x) => x + 1;
```

- `dotnet publish -r win-x64 /p:NativeLib=Shared`
- Copy the .dll and .lib

```cpp
extern "C" __declspec(dllimport) int32_t __stdcall Foo(int32_t x);

int x = Foo(1); // x is 2
```

I could see two possible approaches:
- On Windows, using `/p:NativeLib=Shared` would just always also produce the .lib file
- We could have some new opt-in MSBuild prop to request the .lib file

I don't feel strongly about either, though maybe the former makes more sense and is easier to use?

**Comment by jkotas** [comment]
The export lib gets produced by default. Look under `bin\Release\net8.0\win-x64\native\*.lib`.

We are not doing anything special for this. The MSVC linker produces the export .lib by default.

**Comment by MichalPetryka** [comment]
> The export lib gets produced by default. Look under `bin\Release\net8.0\win-x64\native\*.lib`.
> 
> We are not doing anything special for this. The MSVC linker produces the export .lib by default.

Should it maybe be copied to the `publish` directory?

**Comment by jkotas** [comment]
> Should it maybe be copied to the publish directory?

Publish directory is meant to contain files required for deployment. The export .lib file is needed for deployment. When publishing without native AOT, the reference assemblies are not copied to the publish directory either.

**Comment by Sergio0694** [comment]
Ooh well that's even better, completely missed that we already had .lib files being generated 😄
Will just close this, thank you for the info Jan!
