### ISSUE TITLE
[mono][System.Reflection.Emit] VTable initialization failure for class implementing an interface

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#94490]
When using System.Reflection.Emit with Mono, using `MethodBuilder.SetReturnType` and `MethodBuilder.SetParameters` on methods that are supposed to implement interface methods does not work - the method is not considered to implement the interface method.  Using the long form of `TypeBuilder.DefineMethod` works.

```csharp
using System;
using System.Reflection;
using System.Reflection.Emit;

public interface IStr
{
    public string MStr(string x);
}

public class P {
    public static void Main()
    {
        var aname = "TestAssembly";
        var assemblyName = new AssemblyName(aname);
        var assemblyBuilder = AssemblyBuilder.DefineDynamicAssembly(assemblyName, AssemblyBuilderAccess.Run);
        var moduleBuilder = assemblyBuilder.DefineDynamicModule(aname);

        var typeBuilder = moduleBuilder.DefineType("TestType", TypeAttributes.Public, typeof(object), new Type[] { typeof(IStr) });

#if false
        //works
        var methodBuilder = typeBuilder.DefineMethod("MStr", MethodAttributes.Public | MethodAttributes.Virtual, typeof(string), new Type[] { typeof(string) });
#else
        // throws "Invalid VTable" from CreateInstance, below
        var methodBuilder = typeBuilder.DefineMethod("MStr", MethodAttributes.Public | MethodAttributes.Virtual);
        methodBuilder.SetReturnType(typeof(string));
        methodBuilder.SetParameters(new Type[] { typeof(string) });
#endif

        var ilg = methodBuilder.GetILGenerator();
        ilg.Emit(OpCodes.Ldarg_1);
        ilg.Emit(OpCodes.Ret);

        var type = typeBuilder.CreateType();
        var obj = Activator.CreateInstance(type);
        var m = type.GetMethod("MStr");
        var r = m.Invoke(obj, new object[] { "hello" });
        Console.WriteLine($"r = {r}");
    }
}
```

*Update* simpler repro and better diagnosis; original issue below

---

Needs some investigation still.  Some of the System.Reflection.Emit code generates a class with a bad vtable on net8.0.

The TypedClientBuilder is from aspnetcore:

https://github.com/dotnet/aspnetcore/blob/556f39af49b1a32f14089d3809557825932e4ca5/src/SignalR/server/Core/src/Internal/TypedClientBuilder.cs#L49

Repro:

Clone this repo https://github.com/lambdageek/repro-iclientproxy-vtable-fail

**Expected**

```console
$ dotnet run
SendCoreAsync - M1
```

**Actual**

```console
$ dotnet run
Unhandled Exception:
System.TypeLoadException: VTable setup of type Microsoft.AspNetCore.SignalR.TypedClientBuilder.I1Impl failed
   at System.RuntimeType.GetMethodsByName(String name, BindingFlags bindingAttr, MemberListType listType, RuntimeType reflectedType)
   at System.RuntimeType.GetMethodCandidates(String name, BindingFlags bindingAttr, CallingConventions callConv, Type[] types, Int32 genericParamCount, Boolean allowPrefixLookup)
   at System.RuntimeType.GetMethodImpl(String name, Int32 genericParamCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConvention, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetMethod(String name, BindingFlags bindingAttr)
   at Retrofit.TypedClientBuilder`1[[I1, promo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].GenerateClientBuilder() in /private/tmp/promo/TypedClientBuilder.cs:line 42
   at System.Lazy`1[[System.Func`2[[Retrofit.IClientProxy, promo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[I1, promo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1[[System.Func`2[[Retrofit.IClientProxy, promo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[I1, promo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1[[System.Func`2[[Retrofit.IClientProxy, promo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[I1, promo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CreateValue()
   at System.Lazy`1[[System.Func`2[[Retrofit.IClientProxy, promo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[I1, promo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Value()
   at Retrofit.TypedClientBuilder`1[[I1, promo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Build(IClientProxy proxy) in /private/tmp/promo/TypedClientBuilder.cs:line 24
   at P.Main() in /private/tmp/promo/Program.cs:line 19
   at P.<Main>()
```

**Comment by lambdageek** [comment]
This is making aspnetcore tests fail with net8.0 when Mono is used as the runtime.

See https://github.com/dotnet/runtime/pull/94437#issuecomment-1799757995

**Comment by lambdageek** [comment]
Oh I bet I know what it is.

https://github.com/lambdageek/repro-iclientproxy-vtable-fail/blob/5f9da0a04fb30087cb08902a27e739e878e7ce00/TypedClientBuilder.cs#L50

I bet something goes wrong when this `typeof(T)` parameter is used as an interface for `moduleBuilder.DefineType`.

Although I'm not sure how we actually end up seeing a generic param there.  Running with `MONO_ENV_OPTIONS=--interp` or with `MONO_ENV_OPTIONS=--optimize=-gshared` still fails.

**Comment by tmds** [comment]
cc @uweigand @janani66 @Sapana-Khemkar @Swapnali911 @omajid

**Comment by lambdageek** [comment]
It's not really a vtable problem. It's some problem with the IL generation in `TypedClientBuilder.BuildMethod`.  Somehow the IL in there ends up being bad and mono ends up not creating a method

**Comment by lambdageek** [comment]
Ok, really it has to do with `typeBuilder.DefineMethod` and `methodBuidler.SetReturnType`.

Apparently if you use `methodBuilder = typeBuilder.DefineMethod(methodName, methodAttributes, returnType, paramTypes)` instead of

```csharp
   methodBuilder = typeBuidler.DefineMethod(methodName, methodAttributes);
   methodBuilder.SetReturnType(returnType);
   methodBuilder.SetParameters(paramTypes);
```

the code works.

The problem is that if you use the longer version with `SetParameters`, mono doesn't consider that the `methodBuilder` implements an interface method and when it goes to construct the class it fails because not all the interface methods are implemented.

Simple repro:

```csharp
public interface IStr
{
    public string MStr(string x);
}

public class P {
    public static void Main()
    {
        var aname = "TestAssembly";
        var assemblyName = new AssemblyName(aname);
        var assemblyBuilder = AssemblyBuilder.DefineDynamicAssembly(assemblyName, AssemblyBuilderAccess.Run);
        var moduleBuilder = assemblyBuilder.DefineDynamicModule(aname);

        var typeBuilder = moduleBuilder.DefineType("TestType", TypeAttributes.Public, typeof(object), new Type[] { typeof(IStr) });

#if false
        //works
        var methodBuilder = typeBuilder.DefineMethod("MStr", MethodAttributes.Public | MethodAttributes.Virtual, typeof(string), new Type[] { typeof(string) });
#else
        // throws "Invalid VTable" from CreateInstance, below
        var methodBuilder = typeBuilder.DefineMethod("MStr", MethodAttributes.Public | MethodAttributes.Virtual);
        methodBuilder.SetReturnType(typeof(string));
        methodBuilder.SetParameters(new Type[] { typeof(string) });
#endif

        var ilg = methodBuilder.GetILGenerator();
        ilg.Emit(OpCodes.Ldarg_1);
        ilg.Emit(OpCodes.Ret);

        var type = typeBuilder.CreateType();
        var obj = Activator.CreateInstance(type);
        var m = type.GetMethod("MStr");
        var r = m.Invoke(obj, new object[] { "hello" });
        Console.WriteLine($"r = {r}");
    }
}
```

**Comment by lambdageek** [comment]
@tmds @uweigand @janani66 consider patching aspnetcore here:

https://github.com/dotnet/aspnetcore/blob/a2536e6a4e384182825e89ee064115b5d841e97e/src/SignalR/server/Core/src/Internal/TypedClientBuilder.cs#L119-L137

to replace 

```csharp
  var methodBuilder = type.DefineMethod(interfaceMethodInfo.Name, methodAttributes);
  ...
  methodBuilder.SetReturnType(interfaceMethodInfo.ReturnType);
  methodBuilder.SetParameters(paramTypes);
```

by

```csharp
  var methodBuilder = type.DefineMethod(interfaceMethodInfo.Name, methodAttributes, interfaceMethodInfo.ReturnType, paramTypes);
   ...
```

**Comment by alhad-deshpande** [comment]
@lambdageek 
Ran the aspnetcore tests with above fix on ppc64le architecture and both Signalr tests passed.

Test Run Results:
`Passed! - Failed:    0, Passed:  819, Skipped:    4, Total:  823, Duration: 1 m 17 s - Microsoft.AspNetCore.SignalR.Client.FunctionalTests.dll (net8.0)
Passed! - Failed:    0, Passed:  426, Skipped:    1, Total:  427, Duration: 17 s - Microsoft.AspNetCore.SignalR.Tests.dll (net8.0)`

Source code patch:
`diff --git a/src/SignalR/server/Core/src/Internal/TypedClientBuilder.cs b/src/SignalR/server/Core/src/Internal/TypedClientBuilder.cs
index 985dc14e96..d5c3a39c50 100644
--- a/src/SignalR/server/Core/src/Internal/TypedClientBuilder.cs
+++ b/src/SignalR/server/Core/src/Internal/TypedClientBuilder.cs
@@ -116,7 +116,7 @@ internal static class TypedClientBuilder<T>
         var returnType = interfaceMethodInfo.ReturnType;
         bool isInvoke = returnType != typeof(Task);

-        var methodBuilder = type.DefineMethod(interfaceMethodInfo.Name, methodAttributes);
+        var methodBuilder = type.DefineMethod(interfaceMethodInfo.Name, methodAttributes, returnType, paramTypes);

         MethodInfo invokeMethod;
         if (isInvoke)
@@ -133,9 +133,6 @@ internal static class TypedClientBuilder<T>
                 new[] { typeof(string), typeof(object[]), typeof(CancellationToken) }, null)!;
         }

-        methodBuilder.SetReturnType(interfaceMethodInfo.ReturnType);
-        methodBuilder.SetParameters(paramTypes);
-
         // Sets the number of generic type parameters
         var genericTypeNames =
             paramTypes.Where(p => p.IsGenericParameter).Select(p => p.Name).Distinct().ToArray();`

**Comment by tmds** [comment]
@lambdageek will this issue be fixed on the short term?

If not, it would be good to include your workaround directly in aspnetcore so SignalR gets fixed for everyone doing Mono based .NET builds.

**Comment by lambdageek** [comment]
@tmds I think the fix will probably miss the first couple of servicing releases for .NET 8 due to winter holidays and scheduling.

That said, here's what I think needs to be fixed @ivanpovazan @buyaa-n 

Compare `SetSignatureCore` between CoreCLR:

https://github.com/dotnet/runtime/blob/8ebe00362d2dfbf371ee1df32c0a422b22a75bd3/src/coreclr/System.Private.CoreLib/src/System/Reflection/Emit/RuntimeMethodBuilder.cs#L624-L633

and Mono:

https://github.com/dotnet/runtime/blob/8ebe00362d2dfbf371ee1df32c0a422b22a75bd3/src/mono/System.Private.CoreLib/src/System/Reflection/Emit/RuntimeMethodBuilder.Mono.cs#L595-L606

I think Mono should do:

```csharp
if (returnType != null)
  rtype = returnType;
```

`SetSignatureCore` is called from `SetParameters` and `SetReturnType`:

https://github.com/dotnet/runtime/blob/8ebe00362d2dfbf371ee1df32c0a422b22a75bd3/src/libraries/System.Private.CoreLib/src/System/Reflection/Emit/MethodBuilder.cs#L77-L89

**Comment by ivanpovazan** [comment]
Reopening until the backport is not merged:
- [ ] https://github.com/dotnet/runtime/pull/95271

**Comment by akoeplinger** [comment]
@ivanpovazan the PR was approved by tactics so you can merge it

**Comment by ivanpovazan** [comment]
Thanks @akoeplinger!

Closing as the backport has also been merged.
