### ISSUE TITLE
Docs and XML comments for Min/MaxMagnitude are incorrect

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#94500]
It looks like a copy and paste error from Min/Max, e.g. `INumberBase<>.MinMagnitude` says:
https://learn.microsoft.com/en-us/dotnet/api/system.numerics.inumberbase-1.minmagnitude?view=net-7.0
```
Compares two values to compute which is lesser.
```
and
```
x if it is less than y; otherwise, y.
```
which makes it sound like it's just comparing x and y, but it's actually comparing the absolute values of x and y.

**Comment by sejo6549** [comment]
May I be assigned to this issue?

**Comment by skyoxZ** [comment]
This issue is not fully completed yet. As the issue mentioned, Returns and XML comments also need to be fixed.
And also `INumberBase<>.Min/MaxMagnitudeNumber`'s Returns.
