### ISSUE TITLE
CultureInfo.Parent under LC_ALL=C does not refer to itself

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#94505]
`CultureInfo.CurrentCulture` under `LC_ALL=C` returns an invariant culture instance.
This invariant culture instance's `Parent` property does not refer to itself.

This loops twice:
```cs
CultureInfo culture = CultureInfo.CurrentCulture;
while (true)
{
    Console.WriteLine("Invariant: " + CultureInfo.InvariantCulture.Equals(culture));
    if (object.ReferenceEquals(culture, culture.Parent))
    {
        break;
    }
    culture = culture.Parent;
}
```

```
$ LC_ALL=C dotnet run
Invariant: True
Invariant: True
```

@tarekgh is this intentional?

**Comment by tarekgh** [comment]
@tmds why you care if it is same object or not?

**Comment by tarekgh** [comment]
It is possible to create multiple instances of invariant culture in general using `new CultureInfo("")`. So, it is wrong to assume a singleton invariant culture. For current culture, we always create a new culture instance for it when reading the setting from the OS. I am closing the issue. Feel free to send more questions if you still have any. Thanks!
