### ISSUE TITLE
[API Proposal]: Expose the remaining const values in TimeSpan

### ISSUE THREAD

**Issue by IDisposable** [dotnet/runtime#94545]
***Edited By @tarekgh***

This proposal has been approved before https://github.com/dotnet/runtime/issues/94545#issuecomment-2166531840. There was some feedback from @tannergooding and @IDisposable. 

@tannergooding said:  the concern I raised is that there are scenarios this can cause problems since `days * TimeSpan.HoursPerDay` could overflow. For example, if `days > 89,478,485` then this will overflow to a negative `int`.
`HoursPerDay` happens to be the only case where it is "sensible" for it to be `int`, since both `MaxDays` (`10,675,199`) and `MaxHours` (`256,204,778`) are within `int.MaxValue`. That is also why the signatures are `FromDays(int days, int hours, long minutes, long milliseconds, long microseconds)`. So other values, like `MinutesPerDay` (`1440`), `MinutesPerHour` (`60`), or even the existing `MillisecondsPerTick` (`10,000`) are all expected to be used in contexts where `long` is the target type.
When considering TimeSpan, which is where these constants are defined, hours and days are int, all other units are long.

---

### Background and motivation

In the [`TimeSpan`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/TimeSpan.cs) class there are a few [`public const` values](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/TimeSpan.cs#L59C1-L63C119) that are generally applicable that are usefully exposed.

There are *also* a bunch more that are [`internal const`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/TimeSpan.cs#L65C1-L81C77) but would be generally useful for other code and are not more implementation driven than the already exposed const values.

**These values should be exposed publicly on the TimeSpan class.**

Note: NOT suggesting we expose the truly [`internal const`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/TimeSpan.cs#L83C1-L106C77) values that are related to `MinTicks` and `MaxTicks`. They could be included but are just not as naturally useful elsewhere.

### API Proposal

```csharp
namespace System.Collections.Generic;

public class TimeSpan: // elided details
{
        // more elision

        public const long MicrosecondsPerMillisecond = TicksPerMillisecond / TicksPerMicrosecond; //           1,000
        public const long MicrosecondsPerSecond = TicksPerSecond / TicksPerMicrosecond;           //       1,000,000
        public const long MicrosecondsPerMinute = TicksPerMinute / TicksPerMicrosecond;           //      60,000,000
        public const long MicrosecondsPerHour = TicksPerHour / TicksPerMicrosecond;               //   3,600,000,000
        public const long MicrosecondsPerDay = TicksPerDay / TicksPerMicrosecond;                 //  86,400,000,000

        public const long MillisecondsPerSecond = TicksPerSecond / TicksPerMillisecond;           //           1,000
        public const long MillisecondsPerMinute = TicksPerMinute / TicksPerMillisecond;           //          60,000
        public const long MillisecondsPerHour = TicksPerHour / TicksPerMillisecond;               //       3,600,000
        public const long MillisecondsPerDay = TicksPerDay / TicksPerMillisecond;                 //      86,400,000

        public const long SecondsPerMinute = TicksPerMinute / TicksPerSecond;                     //              60
        public const long SecondsPerHour = TicksPerHour / TicksPerSecond;                         //           3,600
        public const long SecondsPerDay = TicksPerDay / TicksPerSecond;                           //          86,400

        public const long MinutesPerHour = TicksPerHour / TicksPerMinute;                         //              60
        public const long MinutesPerDay = TicksPerDay / TicksPerMinute;                           //           1,440

        public const long HoursPerDay = TicksPerDay / TicksPerHour;                               //              24
}
```

### API Usage

```csharp

if (TimeSpan.MinutesPerHour * numHours) > TimeSpan.MinutesPerDay * 7)
    Console.WriteLine("That's really weeks");
```

### Alternative Designs

N/A

### Risks

Since these are compile-time constant values, there would be no runtime cost in either memory or execution overhead. Additionally they would centralize basic real-world facts to one logical location (TimeSpan).

**Comment by IDisposable** [comment]
Is this something we can add to the API review?

**Comment by tannergooding** [comment]
CC. @tarekgh, this is a relatively simple ask and I know I've had to redefine such constants myself in personal projects to help with various extension methods or other time related structs used (such as a `Timestamp` struct used to track frame timings in a game engine).

**Comment by tarekgh** [comment]
I am fine to proceed with the proposal. I don't have any feedback as the proposal looks good to me as it is. I'll mark this as ready for review.

**Comment by IDisposable** [comment]
Should I reopen the PR or start a new one? :)

**Comment by tarekgh** [comment]
@IDisposable please wait till the issue get reviewed by the design committee and then we can reopen the PR. Thanks!

**Comment by bartonjs** [comment]
* The consts that can be `int` should be
* Otherwise, looks good as proposed.

```C#
namespace System.Collections.Generic;

public partial class TimeSpan
{
        public const int MicrosecondsPerMillisecond = TicksPerMillisecond / TicksPerMicrosecond; //           1,000
        public const int MicrosecondsPerSecond = TicksPerSecond / TicksPerMicrosecond;           //       1,000,000
        public const int MicrosecondsPerMinute = TicksPerMinute / TicksPerMicrosecond;           //      60,000,000
        public const long MicrosecondsPerHour = TicksPerHour / TicksPerMicrosecond;               //   3,600,000,000
        public const long MicrosecondsPerDay = TicksPerDay / TicksPerMicrosecond;                 //  86,400,000,000

        public const int MillisecondsPerSecond = TicksPerSecond / TicksPerMillisecond;           //           1,000
        public const int MillisecondsPerMinute = TicksPerMinute / TicksPerMillisecond;           //          60,000
        public const int MillisecondsPerHour = TicksPerHour / TicksPerMillisecond;               //       3,600,000
        public const int MillisecondsPerDay = TicksPerDay / TicksPerMillisecond;                 //      86,400,000

        public const int SecondsPerMinute = TicksPerMinute / TicksPerSecond;                     //              60
        public const int SecondsPerHour = TicksPerHour / TicksPerSecond;                         //           3,600
        public const int SecondsPerDay = TicksPerDay / TicksPerSecond;                           //          86,400

        public const int MinutesPerHour = TicksPerHour / TicksPerMinute;                         //              60
        public const int MinutesPerDay = TicksPerDay / TicksPerMinute;                           //           1,440

        public const int HoursPerDay = TicksPerDay / TicksPerHour;                               //              24
}
```

**Comment by julealgon** [comment]
What was the underlying reason to not expose these when they were first introduced? Was it just a matter of YAGNI, or was there more to it?

**Comment by IDisposable** [comment]
@bartonjs  
 
> The consts that can be int should be

In general, I certainly agree, I was just adjusting the visibility of what was already there... so moving them to `int` from `long` would have to be carefully checked in the _current_ consumers of these `internal` values to make sure that this change doesn't accidentally introduce cases where binary operations that were dealing with an `int` combined with one of these `long` constants wouldn't break (overflow/etc.) if it's now ant `int` *op* `int`. I will ensure I've got tests for that in the final PR

**Comment by tarekgh** [comment]
> What was the underlying reason to not expose these when they were first introduced? Was it just a matter of YAGNI, or was there more to it?

Usually, such constants get introduced when implementing other approved features. To expose anything, it needs to go as a separate proposal to design review it. That is what happened here.

**Comment by tannergooding** [comment]
>  so moving them to int from long would have to be carefully checked 

If we find this is problematic, then please comment back and we can keep them as `long` with the annotation that they need to be so that regular usage doesn't cause overflow or other problems.

I can easily get the sign-off for that over e-mail and just chalk it up to a consideration no one thought about in the 60s it took to review the APIs 😆

**Comment by IDisposable** [comment]
Okay, I'll take the work on to ensure it breaks nothing internal to the assemblies and report back (since these are `internal const`s now, that's the most exposure we risked). I _frankly_ doubt this is an issue... just wanted to surface the risk.

**Comment by IDisposable** [comment]
In light of that, maybe we should steer them to the well of success and keep them as `long` constants in this?

**Comment by IDisposable** [comment]
Looked through the sources in System.Private.CoreLib and there's a lot of places where `(uint)` casts `int` arguments and uses of `Math.BigMul` with unchecked (range) arguments are used. I think the risk of changing these, even just if still `internal const`s would be enormous. I would recommend they stay `long` constants.

**Comment by IDisposable** [comment]
It also appears that similar internal constants (e.g. `MicrosecondsPerMillisecond`, `HoursPerDay`) are declared in [System.Private.CoreLib\src\System\DateTime.cs](https://github.com/dotnet/runtime/blob/f8f450953d71dabe3fd01961c1d05b57c61e8faf/src/libraries/System.Private.CoreLib/src/System/DateTime.cs#L59-L74) and those constants used in [System.Private.CoreLib\src\System\DateTimeOffset.cs](https://github.com/dotnet/runtime/blob/f8f450953d71dabe3fd01961c1d05b57c61e8faf/src/libraries/System.Private.CoreLib/src/System/DateTimeOffset.cs#L253) and other places.

Similarly, `SecondsPerDay` could be shared into [System.Private.CoreLib\src\System\Globalization\CalendricalCalculationsHelper.cs](https://github.com/dotnet/runtime/blob/f8f450953d71dabe3fd01961c1d05b57c61e8faf/src/libraries/System.Private.CoreLib/src/System/Globalization/CalendricalCalculationsHelper.cs#L18) as well as [/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs](https://github.com/dotnet/runtime/blob/f8f450953d71dabe3fd01961c1d05b57c61e8faf/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs#L58)

We would probably want the final PR actually _use_ the newly exposed constants we would be publicizing from TimeSpan.cs in these other places. Would a table of change-sites be useful in the API review, or would deferring to the actual PR be sufficient?

**We would NOT likely want to change `src\coreclr\vm\comdatetime.cpp` and other CPP/COM/VM stuff.**

**Comment by tarekgh** [comment]
@bartonjs @tannergooding @terrajobst Is it hard requirement to change the type from `long` to `int`. I prefer to keep it `long` too. These constants will be used in context which can multiply it to some other values and very possible to overflow. Defining them as `long` will save us from troubles that users can run into.

> We would probably want the final PR actually use the newly exposed constants we would be publicizing from TimeSpan.cs in these other places. Would a table of change-sites be useful in the API review, or would deferring to the actual PR be sufficient?

These are internal implementation details and no need to design review it. It is fine to use the new constants in other places too and include that in your PR.

**Comment by IDisposable** [comment]
When breaking compatibility (as exposing these new fields will do) should I:

Resurrect the [\dotnet\runtime\src\coreclr\System.Private.CoreLib\CompatibilitySuppressions.xml](https://github.com/dotnet/runtime/commit/2bfd1b44200de244a66b7f4a7604be1f2d5585bc#diff-80b8cceb2155b097a536baecd12004d4c771062e23633a35e469f0a8920d4f3c) file to include the needed `CP0002` changes (was cleaned up recently, would have to recreate with only the CP0002 changes.

OR 

Update the ref [\dotnet\runtime\src\libraries\System.Runtime\ref\System.Runtime.cs](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Runtime/ref/System.Runtime.cs#L5943-L5949)

**Comment by bartonjs** [comment]
> These constants will be used in contexts where they might be multiplied with other values, potentially leading to overflow.

The one that really stood out to me is `HoursPerDay`.

```C#
int totalHours = days * TimeSpan.HoursPerDay;
```

looks like it should be legal (and is, provided the number of days isn't in excess of 500M or so); but if that const is a `long` then it doesn't compile.

Similarly, if someone is calling an `(..., int timeoutMs)` function they'd expect to be able to write `(..., allowedSeconds * TimeSpan.MillisecondsPerSecond)`.

So, maybe all of the "TicksPer" should be long, but for some of the constants being a long is a bit ridiculous, and limits their utility.  Perhaps "if it can be `int` it should be" was the wrong threshold, but so is "they're all `long`."

**Comment by IDisposable** [comment]
After cleanup and switching everyone to use the new TimeSpan public const values, the only compile time errors are
```
D:\Dev\dotnet\runtime\src\libraries\System.Private.CoreLib\src\System\Globalization\Calendar.cs(172,36): error CS1503: Argument 3: cannot convert from 'long' to 'int' [D:\Dev\dotnet\runtime\src\coreclr\System.Pr
ivate.CoreLib\System.Private.CoreLib.csproj]
D:\Dev\dotnet\runtime\src\libraries\System.Private.CoreLib\src\System\Globalization\Calendar.cs(184,37): error CS1503: Argument 3: cannot convert from 'long' to 'int' [D:\Dev\dotnet\runtime\src\coreclr\System.Pr
ivate.CoreLib\System.Private.CoreLib.csproj]
D:\Dev\dotnet\runtime\src\libraries\System.Private.CoreLib\src\System\Globalization\Calendar.cs(196,39): error CS1503: Argument 3: cannot convert from 'long' to 'int' [D:\Dev\dotnet\runtime\src\coreclr\System.Pr
ivate.CoreLib\System.Private.CoreLib.csproj]
D:\Dev\dotnet\runtime\src\libraries\System.Private.CoreLib\src\System\Globalization\Calendar.cs(228,39): error CS1503: Argument 3: cannot convert from 'long' to 'int' [D:\Dev\dotnet\runtime\src\coreclr\System.Pr
ivate.CoreLib\System.Private.CoreLib.csproj]

```

**Comment by IDisposable** [comment]
I've updated the original branch and thus the [closed PR](https://github.com/dotnet/runtime/pull/94627) to reflex all this discussion. Went the route of changing the `ref` for the assembly, let me know if that is not appropriate.

I can open a new PR if that would be cleaner for everyone.

**Comment by tarekgh** [comment]
Yes, please open a new PR so we can comment on the proposed changes. Thanks!

**Comment by IDisposable** [comment]
Opened and running :)

**Comment by tarekgh** [comment]
Thanks for opening the PR. I'll try to look later.

**Comment by tarekgh** [comment]
@bartonjs 

I merged the changes but I missed your comment https://github.com/dotnet/runtime/issues/94545#issuecomment-2168854247. We went with `long` types for the new constants but if you think `HoursPerDay` should be `int` we can submit another PR to change that. Please let me know and sorry for missing your comment. 

CC @tannergooding @terrajobst

**Comment by IDisposable** [comment]
Preparing a change to make the smaller constants `int` instead of `long` per [this comment](https://github.com/dotnet/runtime/issues/94545#issuecomment-2166531840) but given the [concerns about accidental overflows](https://github.com/dotnet/runtime/issues/94545#issuecomment-2166880624),  and [other feedback](https://github.com/dotnet/runtime/issues/94545#issuecomment-2168854247) maybe push back on keeping these two as `long` as well (as they're the most likely to unintentionally overflow) to parallel what was done with the `MicrosecondsPerHour` and `MicrosecondsPerDay` in the revised proposal

```
        public const long MillisecondsPerHour = TicksPerHour / TicksPerMillisecond;               //       3,600,000
        public const long MillisecondsPerDay = TicksPerDay / TicksPerMillisecond;                  //      86,400,000
```

**Comment by tarekgh** [comment]
@IDisposable let's apply the approved proposal and then we can track any further changes to bring it back to the design review.

**Comment by IDisposable** [comment]
New PR https://github.com/dotnet/runtime/pull/103721

**Comment by IDisposable** [comment]
Since you reopened the PR, would you like me to reuse that branch instead of the extra PR?

**Comment by bartonjs** [comment]
Based on the domain (the `TimeSpan` type itself), the belief is that `long` is correct for everything except `HoursPerDay` (`int`).

While that's not so nice for `seconds * TimeSpan.MillisecondsPerSecond` for passing to (e.g.) `new CancellationTokenSource(int)`, it is more appropriate for working with the TimeSpan type itself.

```C#
namespace System.Collections.Generic;

public class TimeSpan: // elided details
{
        // more elision

        public const long MicrosecondsPerMillisecond = TicksPerMillisecond / TicksPerMicrosecond; //           1,000
        public const long MicrosecondsPerSecond = TicksPerSecond / TicksPerMicrosecond;           //       1,000,000
        public const long MicrosecondsPerMinute = TicksPerMinute / TicksPerMicrosecond;           //      60,000,000
        public const long MicrosecondsPerHour = TicksPerHour / TicksPerMicrosecond;               //   3,600,000,000
        public const long MicrosecondsPerDay = TicksPerDay / TicksPerMicrosecond;                 //  86,400,000,000

        public const long MillisecondsPerSecond = TicksPerSecond / TicksPerMillisecond;           //           1,000
        public const long MillisecondsPerMinute = TicksPerMinute / TicksPerMillisecond;           //          60,000
        public const long MillisecondsPerHour = TicksPerHour / TicksPerMillisecond;               //       3,600,000
        public const long MillisecondsPerDay = TicksPerDay / TicksPerMillisecond;                 //      86,400,000

        public const long SecondsPerMinute = TicksPerMinute / TicksPerSecond;                     //              60
        public const long SecondsPerHour = TicksPerHour / TicksPerSecond;                         //           3,600
        public const long SecondsPerDay = TicksPerDay / TicksPerSecond;                           //          86,400

        public const long MinutesPerHour = TicksPerHour / TicksPerMinute;                         //              60
        public const long MinutesPerDay = TicksPerDay / TicksPerMinute;                           //           1,440

        public const int HoursPerDay = TicksPerDay / TicksPerHour;                               //              24
}
```

**Comment by IDisposable** [comment]
That makes perfect sense, let me know when/what the final should be and I will resubmit

**Comment by tannergooding** [comment]
You should feel free to submit a PR matching it at any time now, we're in agreement as to the handling here now.

**Comment by tarekgh** [comment]
@IDisposable 

> let me know when/what the final should be and I will resubmit

It is ready now so you can resurrect or create a new PR now.

**Comment by IDisposable** [comment]
Working on it... do we have a decision about the casting at call-site or modifying the parameters type as [mentioned here](https://github.com/dotnet/runtime/pull/103498#discussion_r1643640684)? 

We had settled on casting at the call site, last I remember... and suspect we should go that route now.

**Comment by IDisposable** [comment]
PR #103993 has _hopefully_ final iteration :)
