### ISSUE TITLE
Pinning ROS with known length causes unnecessary code generation.

### ISSUE THREAD

**Issue by Raphtaliyah** [dotnet/runtime#94559]
Pinning a ``ReadOnlySpan<>`` where the length is constant generates code that checks the length.

This managed code
```csharp
static void Main()
{
    var data = new byte[128];
    fixed (byte* ptr = (ReadOnlySpan<byte>)data)
    {
        DoSomething(ptr);
    }
}

[MethodImpl(MethodImplOptions.NoInlining)]
static void DoSomething(byte* bob) { }
```
generates this assembly on x64 for pinning (from godbolt, using the latest runtime):
```x86asm
mov      edi, 128
xor      rcx, rcx
test     edi, edi
cmovne   rcx, rax
mov      bword ptr [rsp], rcx
```

The JIT is able to figure out that the length is constant (``mov edi, 128``) which makes the rest of the code unnecessary. ``test edi, edi`` will always clear ``ZF`` because ``edi`` is constant not zero which will cause ``cmovne rcx, rax`` to always execute which will overwrite rcx that just got zerod. This whole sequence could be converted to a ``mov bword ptr [rsp], rax`` when the length can be proven to be constant.

The codegen on .NET 7 uses a jump instead of ``cmovne`` but the ``test``ing of constant is still present, .NET 6 does things differently (and worse) so this issue probably only applies to .NET 7 and newer.

**Comment by jakobbotsch** [comment]
This happens because the JIT ends up with IR that represents something like:

```csharp
var arr = new byte[128];

ref byte r;
int length;
if (arr != null)
{
  r = ref arr[0];
  length = arr.Length;
}
else
{
  r = null;
  length = 0;
}

byte* pinned = null;
if (length > 0)
  pinned = &r;
```

We fold the `arr != null` but it's too late to also be able to know that `length` is a constant. So naturally, `DOTNET_JitOptRepeat=*` fixes it. The sparse propagation during VN I was planning to work on in .NET 9 should fix this too.

**Comment by MichalPetryka** [comment]
FYI If you don't need the "empty span to null ref" normalization, doing `MemoryMarshal.GetReference` on the span before pinning will result in better codegen.
