### ISSUE TITLE
Unexpected result for string.IndexOf((char)0, StringComparison.InvariantCultureIgnoreCase)

### ISSUE THREAD

**Issue by KlestovAlexej** [dotnet/runtime#94556]
C# .NET 7

// 0
Console.WriteLine("qwerty".IndexOf((char)0, StringComparison.InvariantCultureIgnoreCase));

// -1
Console.WriteLine("qwerty".IndexOf((char)0));

// -1
Console.WriteLine("qwerty".IndexOf('z'));

// -1
Console.WriteLine("qwerty".IndexOf('z', StringComparison.InvariantCultureIgnoreCase));

**Comment by huoyaoyuan** [comment]
See #46569, #47145, #54951 and so on.

**Comment by huoyaoyuan** [comment]
Should we link to some description of this behavior in the documentation of `string.IndexOf`? Currently I'm not seeing any.

**Comment by tarekgh** [comment]
@huoyaoyuan we have doc at https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#stringindexof for this behavior but I think it will be a good idea add something to IndexOf. Are you interested in submitting PR for it?
