### ISSUE TITLE
Stack buffer overrun exception occuring in System.Security.Cryptography

### ISSUE THREAD

**Issue by mshortt96** [dotnet/runtime#94569]
### Description

Hi,

We have recently set up an ASP.NET 7 web API running in a Windows Azure App Service. The web API has dependencies on the Microsoft.AspNetCore.Authentication.JwtBearer and Microsoft.Azure.Cosmos packages. Both of these packages are up-to-date and are intermittently running into stack buffer overrun exceptions when they call `HashAlgorithm`'s `ComputeHash`, crashing the app several times per day across varying controller actions.

I have attached two crash dumps. We're aware that calls to `ComputeHash` are not thread safe and that singletons of `HashAlgorithm` objects should be avoided, however in our case the references to the `HashAlgorithm` and calls to `ComputeHash` are at the package level; we have no access to the calling code. In the provided crash dump for Microsoft.AspNetCore.Authentication.JwtBearer, for example, the crash is occurring when the request middleware is attempting to validate the user's web token.

[Crash 1](https://github.com/dotnet/runtime/files/13308797/Crash.1.txt)
[Crash 2](https://github.com/dotnet/runtime/files/13308798/Crash.2.txt)

We're currently out of ideas and are posting this in the (unlikely?) off-chance this could be an issue in System.Security.Cryptography? Thanks in advance.

### Reproduction Steps

The app is an ASP.NET 7 web API living in a Windows Azure App Service and utilizing the JWT authentication middleware provided by Microsoft.AspNetCore.Authentication.JwtBearer. In some cases, before requests reach the controller actions, the middleware may experience a stack buffer overrun exception when it calls `ComputeHash` to verify the user's JWT.

In other cases the exception will occur when business logic calls Microsoft.Azure.Cosmos methods to perform database reads and writes.

### Expected behavior

No crash

### Actual behavior

Intermittent crashes due to stack buffer overrun exceptions

### Configuration

ASP.NET 7
Microsoft.AspNetCore.Authentication.JwtBearer 7.0.13
Microsoft.AspNetCore.Authentication.JwtBearer 3.36.0
64bit Windows via Microsoft Azure App Service

**Comment by vcsjones** [comment]
The two crashes are:


```plain
     InlinedCallFrame
     InlinedCallFrame
     Interop+BCrypt.<BCryptHashData>g____PInvoke|28_0(IntPtr, Byte*, Int32, Int32)
     Interop+BCrypt.BCryptHashData(Microsoft.Win32.SafeHandles.SafeBCryptHashHandle, System.ReadOnlySpan`1<Byte>, Int32, Int32)
     System.Security.Cryptography.HashProviderCng.AppendHashData(System.ReadOnlySpan`1<Byte>)
     System.Security.Cryptography.HashProvider.AppendHashData(Byte[], Int32, Int32)
     System.Security.Cryptography.HashAlgorithm.ComputeHash(Byte[])
```

Which basically corresponds to this:

https://github.com/dotnet/runtime/blob/3d31c2ec8e6bb3876ebb67058c711666e8febe98/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/HashProviderCng.cs#L63-L73

I honestly do not see how this code can overrun a stack buffer.

> We're aware that calls to ComputeHash are not thread safe and that singletons of HashAlgorithm objects should be avoided

If the code really is using a `HashAlgorithm` instance from multiple threads then I think all bets are off. I can't easily say if that is happening or not.

It could also be memory corruption that happened many other frames ago that only after several more calls finally results in an error if conditions are right.

To really figure out what might be happening here, reproducing it is probably going to be required. Are you able to put together a sample application that reproduces the issue?

**Comment by mshortt96** [comment]
Hi, apologies for the delay. We have set up an MRE [here](https://github.com/mshortt96/HashAlgorithmCrashReprod).

As the ReadMe says, we are starting to think the issue may be occurring because of a `TokenValidationParameters` object being deep cloned in our code. While processing a number of concurrent requests, a CryptographicException or IDE crash will occur on Windows. A colleague on MacOS experiences a double-free malloc error. While not the exact issue observed with `ComputeHash`, could this be the catalyst to the memory corruption you suggested?

I'll keep the issue open for discussion's sake but by the looks of things this is a code issue on our end with a different library.

**Comment by jkotas** [comment]
Yes, libraries like ObjectCloner have a significant risk of introducing very hard to debug crashes when used on arbitrary object graphs that include types not specifically designed to be cloneable. You may want to reconsider your dependency on the ObjectCloner library.
