### ISSUE TITLE
Indirect call guard check detected invalid control transfer.

### ISSUE THREAD

**Issue by olegsavelos** [dotnet/runtime#94562]
### Description

I am trying to implement com wrappers in Native AOT and getting "Indirect call guard check detected invalid control transfer." error when target process try to call functions on my com wrapper.

The class I am trying to implement is IClassFactory https://learn.microsoft.com/en-us/windows/win32/api/unknwn/nn-unknwn-iclassfactory

Here is the com wrapper class code

```
 [GeneratedComClass()]
 internal unsafe partial class ClassFactory : IClassFactory
 {
     public int CreateInstance(nint self, nint outer, Guid* guid, nint* instance)
     {
         throw new NotImplementedException();
     }

     public int LockServer(nint self, [MarshalAs(UnmanagedType.Bool)] bool @lock)
     {
         throw new NotImplementedException();
     }
 }

 [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
 [GeneratedComInterface(Options = ComInterfaceOptions.ManagedObjectWrapper)]
 [Guid("00000001-0000-0000-C000-000000000046")]
 internal unsafe partial interface IClassFactory
 {
     [PreserveSig()]
     int CreateInstance(IntPtr self, IntPtr outer, Guid* guid, IntPtr* instance);

     [PreserveSig()]
     int LockServer(IntPtr self,[MarshalAs(UnmanagedType.Bool)] bool @lock);
 }
```

This is the code I use to return the wrapper class

```
  [UnmanagedCallersOnly(EntryPoint = "DllGetClassObject")]
  public static unsafe int DllGetClassObject(Guid* rclsid, Guid* riid, IntPtr* ppv)
  {
      if (rclsid->CompareTo(Constants.TAP_GUID) == 0)
      {
          *ppv = _comWrappers.GetOrCreateComInterfaceForObject(_factory, CreateComInterfaceFlags.None);

          return HResult.S_OK;
      }

      return HResult.E_FAIL;
  }
```

The compiler also spits out this error 

`D:\Test\XamlDiag\XamlTap\Microsoft.Interop.ComInterfaceGenerator\Microsoft.Interop.ComInterfaceGenerator\XamlTap.IClassFactory.cs(12,31,12,54): warning CA2256: Type 'InterfaceImplementation' has the 'DynamicInterfaceCastableImplementationAttribute' applied to it but does not provide an implementation of all interface members defined in inherited interfaces (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2256)`
As I understand this is due IUknown implementation missing from the wrapper class? Based on the documentation and auto generated class the IUnknown functions are auto implemented (at least on vtable level)

Did I miss something ?
Thanks!

### Reproduction Steps

N/A

### Expected behavior

Com wrapper functions being called.

### Actual behavior

Indirect call guard check detected invalid control transfer error happens.

### Known Workarounds

Manually using vtables to map functions works.

### Configuration

.NET 8 latest 
Windows
x64

**Comment by AaronRobinsonMSFT** [comment]
The code snippet above is incomplete. Note that [`GetOrCreateComInterfaceForObject()`](https://learn.microsoft.com/dotnet/api/system.runtime.interopservices.comwrappers.getorcreatecominterfaceforobject#returns) returns an instance of `IUnknown`, not the IID that is requested by `riid`. The implementation should be updated as follows. 

```csharp
  [UnmanagedCallersOnly(EntryPoint = "DllGetClassObject")]
  public static unsafe int DllGetClassObject(Guid* rclsid, Guid* riid, IntPtr* ppv)
  {
      IntPtr res; 
      if (rclsid->CompareTo(Constants.TAP_GUID) == 0)
      {
          res = _comWrappers.GetOrCreateComInterfaceForObject(_factory, CreateComInterfaceFlags.None);
      }
      else
      {
          return HResult.E_FAIL;
      }
     
      int hr = Marshal.QueryInterface(res, ref *riid, out *ppv); // Query for the requested interface.
      Marshal.Release(res); // Release the AddRef() from ComWrappers above.
      return hr; // Forward the query HRESULT.
  }
```

It would also be advised to wrap the entire function body in a `try`/`catch` block so exceptions don't escape.  If an exception is thrown, the [associated HRESULT](https://learn.microsoft.com/dotnet/api/system.exception.hresult) can be returned.
