### ISSUE TITLE
Chrome / Chromium 119 Breaks .NET 6.0 Webassembly

### ISSUE THREAD

**Issue by legistek** [dotnet/runtime#94570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

My users are all suddenly experiencing out of memory crashes ("Aw Snap!" (ugh)) in Chrome and Edge 119 (Windows desktop) with my .NET6 Blazor Webassembly app that do not occur in 118 or earlier or on Firefox or Safari.

Looking at memory usage in Task Manager, the affected tab starts out fine but over time and depending on activity the memory usage keeps growing at an exponential rate - seemingly slow at first and then extremely fast. The growth occurs even when the app is idle (but not minimized). CPU usage also skyrockets.

After updating to .NET 8 RC2 the problem goes away.

I know 119 adds WASM GC but my understanding is .NET6 doesn't use this. Still the coincidence is striking.

Wish I had more to say but if anyone has any idea what the cause might be or how to rectify it other than moving to .NET8 please let me know.

### Expected Behavior

Chrome should not crash; memory usage should be stable when the app is idle and CPU usage should consistently stay at or close to 0.

### .NET Version

6

**Comment by lewing** [comment]
@legistek just to verify, you are seeing this on .NET6 ?

**Comment by legistek** [comment]
@lewing yes, just .NET6, and also it's interpreted WASM (not AOT).

.NET8 seems fine - in fact memory usage is much better overall.
Haven't tried .NET7.

**Comment by pavelsavara** [comment]
I wonder if chromium/edge also fails. Does the problem reproduce on osx and linux ?

**Comment by legistek** [comment]
@pavel

> I wonder if chromium/edge also fails. Does the problem reproduce on osx and linux ?

Edge too. I updated the issue title.

Haven't tried Chrome on OSX or Linux sorry.

**Comment by pavelsavara** [comment]
Is there deployment I could have look at, online ?

**Comment by legistek** [comment]
@pavelsavara I'd be happy to give you access to the application sure. Is there a way to reach you privately?

I hope you all think it's plausible that something systemic happened that isn't just my own fault somehow - wouldn't want anyone to be chasing geese.

**Comment by pavelsavara** [comment]
> @pavelsavara I'd be happy to give you access to the application sure. Is there a way to reach you privately?

pavelsavara@microsoft.com

> I hope you all think it's plausible that something systemic happened that isn't just my own fault somehow - wouldn't want anyone to be chasing geese.

There are many things which could go wrong. I will give it quick look and I hope to learn something. Perhaps the problem is latent for later versions of .NET too.

**Comment by legistek** [comment]
@pavelsavara awesome thank you. Let me set up a private workspace for you with enough material to help reproduce the issue and I'll email you. You probably won't be able to make it crash (t can take 1-2 hours of use - this is a productivity app so we have people logged on all day) but you should at least see the bizarre memory behavior in Task Manager. I'll also note that memory usage in the Javascript VM remains normal so Task Manager seems to be the only tipoff that something's awry.

**Comment by legistek** [comment]
Well thanks to @pavelsavara and @lewing this was traced back to #62705 and #62227 and per his suggestion, updating the SDK and runtimes to 6.0.23 solved the problem (just updating the Nuget packages isn't enough). Specifically the 6.0.0 runtime appears to be creating thousands of DOMTimer's which, at least in Chrome 119, are leading to runaway memory usage.

After re-building with the updated SDKs and installing the updated runtimes on the host machines, the problem is gone. 

Many many thanks to the Microsoft team for their extraordinarily fast and helpful assistance!
