### ISSUE TITLE
   App crashes when running with enabled AOT in .NET 7 Android

### ISSUE THREAD

**Issue by anasonov1992** [dotnet/runtime#94571]
### Description

Hi!

I am using the following AOT properties in my .NET Android project file - ILive.Droid.csproj:

![Screenshot 2023-11-09 at 17 50 23](https://github.com/xamarin/xamarin-android/assets/39626896/1842b1c0-60ad-449a-b7ab-9930af98ea17)

When I run my project in **Release** mode I am getting crash and the following error:

**[com.ILive.Droi] * Assertion at /__w/1/s/src/mono/mono/mini/aot-runtime.c:2459, condition `is_ok (error)' not met, function:decode_cached_class_info, Image out of date: ILive.Droid.dll.so**

where ILive.Droid.dll.so is precompiled library file for my runnable .NET Android project.

What could be the reason of that crash?
How can I handle it?

Before migration my project from Xamarin to .NET 7 the deprecated now property **$(AotAssemblies)** worked fine.

### Relevant log output

```shell
[com.ILive.Droi] * Assertion at /__w/1/s/src/mono/mono/mini/aot-runtime.c:2459, condition `is_ok (error)' not met, function:decode_cached_class_info, Image out of date: ILive.Droid.dll.so
```

### Reproduction Steps

1. Set AOT properties for a .NET Android project to:

![Screenshot 2023-11-09 at 17 50 23](https://github.com/xamarin/xamarin-android/assets/39626896/d679e18e-b419-401d-8edf-01bac72f28b4)

2. Run the project in **Release** mode.
3. Get an error

[com.ILive.Droi] * Assertion at /__w/1/s/src/mono/mono/mini/aot-runtime.c:2459, condition `is_ok (error)' not met, function:decode_cached_class_info, Image out of date: ILive.Droid.dll.so

where ILive.Droid.dll.so is precompiled library file for my runnable .NET Android project.

### Expected behavior

App runs successfully.

### Actual behavior

App crashes.

### Known Workarounds

No workaround.

### Configuration

.NET 7.0.310
.NET Runtime 7.0.13
.NET Android (net7.0-android, etc.)
OS Android ARM64
VS 2022 17.6.6, building on Mac OS x86

**Comment by fanyang-mono** [comment]
@anasonov1992 Thanks for providing detailed information. I will take a look this week.

**Comment by vargaz** [comment]
These errors indicate a problem with the build, the assemblies in the final app don't match the assemblies which were aot-ed.

**Comment by fanyang-mono** [comment]
@anasonov1992 I tried to reproduce and wasn't able to. This is what I did
```
dotnet new android -o myAndroidTempApp
dotnet add package Mono.AotProfiler.Android
dotnet build -t:BuildAndStartAotProfiling
dotnet build -t:FinishAotProfiling
dotnet build -c release -r android-arm64 -t:run -p:RunAOTCompilation=true -p:AndroidEnableProfiledAot=true
```

I used .NET8 RC2 sdk. Is there anything that you do differently?
