### ISSUE TITLE
HashSet.SetEquals() violates symmetric property

### ISSUE THREAD

**Issue by Timovzl** [dotnet/runtime#94584]
### Description

I presume that hash set equality is intended to be reflexive, symmetric, and transitive. Please correct me if I'm wrong there.

As it is, `HashSet<T>.SetEquals()` (and possibly other set implementations as well) violates the symmetric property. This is easily demonstrated by [this code](https://dotnetfiddle.net/Y1gnpF), also provided in the reproduction steps.

### Reproduction Steps

```cs
public class Program
{
	public static void Main()
	{
		var left = new HashSet<string>() { "a", "A", };
		var right = new HashSet<string>(StringComparer.OrdinalIgnoreCase) { "A", };
		
		var leftEqualsRight = left.SetEquals(right);
		var rightEqualsLeft = right.SetEquals(left);
		
		Console.WriteLine($"Set contents are equal from both perspectives: {ShouldBeEqual(left, right)}"); // True
		Console.WriteLine($"Left equals right: {leftEqualsRight}"); // False (this result is incorrect)
		Console.WriteLine($"Right equals left: {rightEqualsLeft}"); // True (this result is correct)
		Console.WriteLine($"Same answer: {leftEqualsRight == rightEqualsLeft}"); // False (violates symmetric property)
	}
	
	private static bool ShouldBeEqual(HashSet<string> left, HashSet<string> right)
	{
		foreach (var leftElement in left)
			if (!right.Contains(leftElement))
				return false;
		
		foreach (var rightElement in right)
			if (!left.Contains(rightElement))
				return false;
		
		return true;
	}
}
```

### Expected behavior

The symmetric property dictates that `left.SetEquals(right)` should equal `right.SetEquals(left)`.

Although a difference in comparers makes this more complicated to reason about, I daresay the simplest, most sensible, and most _useful_ reasoning is that for two hash sets to be equal, they must _each_ consider the other equal, from their own perspective (i.e. comparer).

Why? If each of the sets finds that the other contains everything that it contains, then lookups into the sets are indistinguishable.

### Actual behavior

The sets do not honor the perspective of the other, thus making claims that violate the symmetric property.

### Regression?

I'm not sure if this behavior was different before, but it seems to be caused by the optimization that works hard to prevent enumerating twice.

### Known Workarounds

```cs
	private static bool SetEquals<T>(HashSet<T> left, HashSet<T> right)
	{
		foreach (var leftElement in left)
			if (!right.Contains(leftElement))
				return false;
		
		foreach (var rightElement in right)
			if (!left.Contains(rightElement))
				return false;
		
		return true;
	}
```

### Configuration

.NET Fiddle, using .NET 8 Preview 3, from the Edge browser

### Other information

The [implementation](https://github.com/dotnet/runtime/blob/e138ff137f4d727448ed171c6015905fb2d4781a/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/HashSet.cs#L842) seems to make great effort to avoid enumerating twice. That optimization might be the cause of the asymmetry.

**Comment by tfenise** [comment]
> I presume that hash set equality is intended to be reflexive, symmetric, and transitive.

But the signature of `HashSet.SetEquals()` is `bool SetEquals(IEnumerable<T> other)`. `other` may not even be a set at all. What should symmetric property mean in this case?

> I daresay the simplest, most sensible, and most useful reasoning is that for two hash sets to be equal, they must each consider the other equal, from their own perspective (i.e. comparer).

Again, `other` may not even be a set at all. Do you suggest `SetEquals` should test if `other` is an `ISet<T>` or `IReadOnlySet<T>`?

**Comment by eiriktsarpalis** [comment]
> I presume that hash set equality is intended to be reflexive, symmetric, and transitive.

For set equality to be well-defined, instances need a shared notion of element equality. If that isn't the case (i.e. different comparers are being used) all bets are off.

> I daresay the simplest, most sensible, and most useful reasoning is that for two hash sets to be equal, they must each consider the other equal, from their own perspective (i.e. comparer).

As @tfenise is pointing out, the RHS argument is an IEnumerable so we can't assume that it has set structure (NB the implementation [does make that runtime check](https://github.com/dotnet/runtime/blob/b38ccb5d0e8984361ea37728cf64300f485d55f5/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/HashSet.cs#L818-L819), but it's only as a performance optimization). 

Related to https://github.com/dotnet/runtime/issues/69218

**Comment by Timovzl** [comment]
> But the signature of HashSet.SetEquals() is bool SetEquals(IEnumerable<T> other). other may not even be a set at all.

Good point. I guess there’s no symmetry. 😅
