### ISSUE TITLE
Xamarin MAUI iOS using .NET 7 & 8 and OData client throwing Attempting to JIT compile method '(wrapper dynamic-method) 

### ISSUE THREAD

**Issue by ImGonaRot** [dotnet/runtime#94594]
### Description

I have a Xamarin MAUI iOS project that uses Microsoft.OData.Client.
When the code uses a DataServiceQuery to call the OData endpoint, iOS will throw an exception.

> System.ExecutionEngineException: Attempting to JIT compile method '(wrapper delegate-invoke) void :invoke_callvirt_void_GlobalOption_int (Test.Service.Models.GlobalOption,int)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
> 
> at System.Linq.Expressions.Interpreter.ActionCallInstruction`2[[Test.Service.Models.GlobalOption, Test.Mobile.MAUI, Version=23.9.29.0, Culture=neutral, PublicKeyToken=null],[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Run(InterpretedFrame )
> at System.Linq.Expressions.Interpreter.Interpreter.Run(InterpretedFrame )
> at System.Linq.Expressions.Interpreter.LightLambda.RunVoid(Object[] )
> at System.Dynamic.Utils.DelegateHelpers.ActionThunk2[Object,Object](Func`2 handler, Object t1, Object t2)
> at Microsoft.OData.Client.Metadata.ClientPropertyAnnotation.SetValue(Object instance, Object value, String propertyName, Boolean allowAdd)
> at Microsoft.OData.Client.Materialization.StructuralValueMaterializationPolicy.ApplyDataValue(ClientTypeAnnotation type, ODataProperty property, Object instance)
> at Microsoft.OData.Client.Materialization.EntryValueMaterializationPolicy.MaterializeResolvedEntry(MaterializerEntry entry, Boolean includeLinks)
> at Microsoft.OData.Client.Materialization.EntryValueMaterializationPolicy.Materialize(MaterializerEntry entry, Type expectedEntryType, Boolean includeLinks)
> at Microsoft.OData.Client.Materialization.ODataEntityMaterializer.DirectMaterializePlan(ODataEntityMaterializer materializer, MaterializerEntry entry, Type expectedEntryType)
> at Microsoft.OData.Client.Materialization.ODataEntityMaterializerInvoker.DirectMaterializePlan(Object materializer, Object entry, Type expectedEntryType)
> at Microsoft.OData.Client.ProjectionPlan.Run(ODataEntityMaterializer materializer, ODataResource entry, Type expectedType)
> at Microsoft.OData.Client.Materialization.ODataEntityMaterializer.ReadImplementation()
> at Microsoft.OData.Client.MaterializeAtom.MoveNextInternal()
> at Microsoft.OData.Client.MaterializeAtom.MoveNext()
> at System.Linq.Enumerable.d__42`1[[Test.Service.Models.GlobalOption, Test.Mobile.MAUI, Version=23.9.29.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
> at System.Linq.Enumerable.TryGetFirst[GlobalOption](IEnumerable`1 , Boolean& )
> at System.Linq.Enumerable.FirstOrDefault[GlobalOption](IEnumerable`1 source)

This only happens in Release mode.
I have tried .NET 7 and .NET 8, but both have the same problem.
I tried several of the following:

1. Added `<UseInterpreter>true</UseInterpreter>` to the project file.
2. Added `<MtouchInterpreter>-all,Microsoft.OData.Client</MtouchInterpreter>` to the project file.
3. Added `<MtouchInterpreter>all,-Microsoft.OData.Client</MtouchInterpreter>` to the project file.
4. Created a LinkDescription.xml file with build action of LinkDescription. Added `<assembly fullname="Microsoft.OData.Client"/>` to the `<linker>` section.
5. Added `<TrimmerRootDescriptor Include="Platforms\iOS\LinkDescription.xml" />` to the project file.
6. `<LinkDescription Include="Platforms\iOS\LinkDescription.xml" />` to the project file.

When I tried this in Xamarin.Forms iOS with the same LinkDescription.xml file, it works in Release mode.

### Reproduction Steps

Create a new Xamarin MAUI iOS project.
Add the following NuGets

1. Microsoft.OData.Client
2. Microsoft.OData.Core
3. Microsoft.OData.Edm
4. Microsoft.Spatial

Connect to an OData endpoint and use DataServiceQuery to build out a query and then call ExecuteAsync() on the query.

### Expected behavior

The DataServiceQuery should work that same as it does in Xamarin.Forms .iOS.

### Actual behavior

Getting generic exception.

> System.ExecutionEngineException: Attempting to JIT compile method '(wrapper delegate-invoke) void :invoke_callvirt_void_GlobalOption_int (Test.Service.Models.GlobalOption,int)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
> 
> at System.Linq.Expressions.Interpreter.ActionCallInstruction`2[[Test.Service.Models.GlobalOption, Test.Mobile.MAUI, Version=23.9.29.0, Culture=neutral, PublicKeyToken=null],[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Run(InterpretedFrame )
> at System.Linq.Expressions.Interpreter.Interpreter.Run(InterpretedFrame )
> at System.Linq.Expressions.Interpreter.LightLambda.RunVoid(Object[] )
> at System.Dynamic.Utils.DelegateHelpers.ActionThunk2[Object,Object](Func`2 handler, Object t1, Object t2)
> at Microsoft.OData.Client.Metadata.ClientPropertyAnnotation.SetValue(Object instance, Object value, String propertyName, Boolean allowAdd)
> at Microsoft.OData.Client.Materialization.StructuralValueMaterializationPolicy.ApplyDataValue(ClientTypeAnnotation type, ODataProperty property, Object instance)
> at Microsoft.OData.Client.Materialization.EntryValueMaterializationPolicy.MaterializeResolvedEntry(MaterializerEntry entry, Boolean includeLinks)
> at Microsoft.OData.Client.Materialization.EntryValueMaterializationPolicy.Materialize(MaterializerEntry entry, Type expectedEntryType, Boolean includeLinks)
> at Microsoft.OData.Client.Materialization.ODataEntityMaterializer.DirectMaterializePlan(ODataEntityMaterializer materializer, MaterializerEntry entry, Type expectedEntryType)
> at Microsoft.OData.Client.Materialization.ODataEntityMaterializerInvoker.DirectMaterializePlan(Object materializer, Object entry, Type expectedEntryType)
> at Microsoft.OData.Client.ProjectionPlan.Run(ODataEntityMaterializer materializer, ODataResource entry, Type expectedType)
> at Microsoft.OData.Client.Materialization.ODataEntityMaterializer.ReadImplementation()
> at Microsoft.OData.Client.MaterializeAtom.MoveNextInternal()
> at Microsoft.OData.Client.MaterializeAtom.MoveNext()
> at System.Linq.Enumerable.d__42`1[[Test.Service.Models.GlobalOption, Test.Mobile.MAUI, Version=23.9.29.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
> at System.Linq.Enumerable.TryGetFirst[GlobalOption](IEnumerable`1 , Boolean& )
> at System.Linq.Enumerable.FirstOrDefault[GlobalOption](IEnumerable`1 source)

### Regression?

This works in Xamarin.Forms iOS using .NET Standard 2.0 with a linker xml file and in Release mode.

### Configuration

Using .NET 7 and 8.
OS is Windows 10, Visual Studio 2022 17.7.6
ARM64 on physical iPhone device using iOS 15.
Debug configuration works fine but Release does not work.

**Comment by huoyaoyuan** [comment]
Microsoft.OData.Client is invoking dynamic feature that isn't supported in AOT only environment. Please contact them at https://github.com/OData/odata.net for proper support for AOT.

**Comment by ImGonaRot** [comment]
@huoyaoyuan I would agree with this except for the following:

1. This has been working in my Xamarin.Forms iOS project, while using a linker xml file, published in the Apple App Store since 2018.
2. According to this article [Mono interpreter on iOS and Mac Catalyst](https://learn.microsoft.com/en-us/dotnet/maui/macios/interpreter) we should be able to set `<UseInterpreter>true</UseInterpreter>` to get by this error. This article [oData Client "JIT compile method in AOT mode" error when build to IOS device](https://github.com/dotnet/runtime/issues/76261) said it works but it does not. 
3. Based on the interpreter article above, we should also be able to list specific dlls to ignore AOT complilation by using the `<MtouchInterpreter>all,-Microsoft.OData.Client</MtouchInterpreter>`.

None of which seems to work in my version of Visual Studio 2022 using either .NET 7 or .NET 8, **yet** this works perfectly fine in debug mode both in .NET 7 and .NET 8 on physical devices **and** has been working fine for my Xamarin.Forms app in the Apple App Store since 2018.

**Comment by ImGonaRot** [comment]
I finally got it to work.
I had to edit a few settings in the project file.
```
  <MtouchLink>SdkOnly</MtouchLink>
  <MtouchUseLlvm>True</MtouchUseLlvm>
  <EnableSGenConc>True</EnableSGenConc>
  <MtouchNoSymbolStrip>True</MtouchNoSymbolStrip>
  <MtouchProfiling>False</MtouchProfiling>
  <MtouchInterpreter>-all,Microsoft.OData.Client</MtouchInterpreter>
```
