### ISSUE TITLE
[API Proposal]: ISimdVector<TSelf, T>.GetMatchCount() and .IndexOfFirstMatch()

### ISSUE THREAD

**Issue by neon-sunset** [dotnet/runtime#94639]
### Background and motivation

While implementing https://github.com/dotnet/runtime/pull/94472 I noticed pre-existing `IndexOfLastMatch(TSelf)` defined by `ISimdVector<TSelf, T>` in https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Runtime/Intrinsics/ISimdVector_2.cs#L556

This API proposal is for extending the interface with the other two methods for finding/counting elements.

### API Proposal

```csharp
namespace System.Runtime.Intrinsics
{
    internal partial interface ISimdVector<TSelf, T>
       where TSelf : ISimdVector<TSelf, T>?
    {
        // Other members
        // ...
        static abstract int GetMatchCount(TSelf vector);
        static abstract int IndexOfFirstMatch(TSelf vector);
    }
```

### API Usage

```csharp
var vector = Vector128.Create(1, 2, 2, 3);
var mask = Vector128.Equals(vector, Vector128.Create(2));

Assert.Equal(2, Vector128.GetMatchCount(mask));
Assert.Equal(1, Vector128.IndexOfFirstMatch(mask));
```

### Alternative Designs

Provided the quality of codegen in .NET 9 reaches the point where hoisting of the vector broadcast/load is guaranteed for most loop variants, a higher level API could be offered (or perhaps it might find its home in `Vector<T>`?)

```csharp
namespace System.Runtime.Intrinsics
{
    internal partial interface ISimdVector<TSelf, T>
       where TSelf : ISimdVector<TSelf, T>?
    {
        static abstract int Count(TSelf vector, T value);
        static abstract int IndexOf(TSelf vector, T value);
        static abstract int LastIndexOf(TSelf vector, T value);
    }
```

### Risks

N/A, a lot of time to reconsider the API before .NET 9 release.

**Comment by EgorBo** [comment]
Is GetMatchCount useful? 
I assume typically you either need a position of a first/last match or you need raw bits to be able to iterate over them, with GetMatchCount you can't iterate.

**Comment by neon-sunset** [comment]
It seems this issue has now been superseded by https://github.com/dotnet/runtime/issues/98055
