### ISSUE TITLE
[API Proposal]: Generic State Parameter for Linq operators

### ISSUE THREAD

**Issue by hesselmonk** [dotnet/runtime#94654]
### Background and motivation

Adding a generic state parameter to Linq operators can reduce the amount of `Delegate` heap allocations significantly (mostly from once per call to once per declaration).

### API Proposal

The Any operator could work like this for example:

```csharp
public static partial class Enumerable
{
    public static bool Any<TSource, TState>(this IEnumerable<TSource> source, TState state, Func<TSource, TState, bool> predicate)
    {
        if (source == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.source);
        }

        if (predicate == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.predicate);
        }

        foreach (TSource element in source)
        {
            if (predicate(element, state))
            {
                return true;
            }
        }

        return false;
    }
}
```

### API Usage

```csharp
using System;
using System.Collections.Generic;
using System.Linq;

public class C 
{
    public int Threshold;
    
    // allocates per call
    public bool MethodA(List<int> list) 
    {
        return list.Any(i => i > Threshold);
    }

    // allocates once    
    public bool MethodB(List<int> list) 
    {
        return list.Any(this, (i, s) => i > s.Threshold);
    }
}
```

### Alternative Designs

To avoid confusion for methods with longer, or more varied, signatures the `WithState` suffix might be used:

```csharp
public static bool AnyWithState<TSource, TState>(this IEnumerable<TSource> source, TState state, Func<TSource, TState, bool> predicate)
{
}
```

### Risks

The state parameter only makes sense if it has no (or very little) type constraints, which might make it easier to accidentally provide the wrong argument (especially with type inference).

Edit: explicitly mention `Delegate` allocation, to avoid confusion with `IEnumerable<T>` allocations

**Comment by huoyaoyuan** [comment]
There are numerous of sources that can allocate in LINQ, namely the allocation of `IEnumerator<T>`, though it's heavily optimized away by checking known types.
In addition, the cost of virtual call is not ignorable either. Inlining delegates in some way can solve both the issues.

**Comment by huoyaoyuan** [comment]
The main concern here is complexity, of course. Adding one type parameter can help to reduce closure allocation. What about another one for collection type to reduce `IEnumerator`? What about adding another type parameter for struct-constrained interface call?

**Comment by hesselmonk** [comment]
All right, fair enough. 

The `Any` overload was just an example though. Creating a complete list of all the useful operators that would benefit from this would've taken me too long. 

I agree that rewriting a simple any usage to a loop is trivial. The reason I thought this would be valuable in the API is because to roll your own, you would need to copy/recreate the original implementation for each Linq operator. This would introduce new code, new bugs and potentially miss out on existing optimizations 🤷

**Comment by eiriktsarpalis** [comment]
Understood, the main reason why wouldn't want to include state parameters in principle is that it seems to contravene the general natures and trade-offs involved with using LINQ. For performance sensitive applications concerned with avoiding allocations, it is advisable to just write an imperative loop.
