### ISSUE TITLE
Performance Issue with DeserializeAsyncEnumerable on Small JSON Objects Stream

### ISSUE THREAD

**Issue by JKamsker** [dotnet/runtime#94657]
### Description
I'm encountering a significant delay when using `JsonSerializer.DeserializeAsyncEnumerable` to process a stream of small JSON objects. The delay occurs before the first object is yielded to the client. A temporary workaround I've found is to reduce the buffer size to approximately 32 bytes, which improves the response time.

I have a server-client setup where the server streams a series of small JSON objects to the client. Generating each object takes only a few milliseconds, but currently, the client experiences a 17-second delay before receiving the first object. After this initial delay, thousands of objects are received in quick succession. Adjusting the buffer size down to 32 bytes has shown that the delay can be significantly reduced.

Code Example Illustrating the Issue:

_Server-Side Code:_
```csharp
public async IAsyncEnumerable<SomeObject> GetSomeObjects(CancellationToken cancellationToken)
{
    for (int i = 0; !cancellationToken.IsCancellationRequested; i++)
    {
        await Task.Delay(1, cancellationToken); // Simulating a slow data source
        yield return new SomeObject { Id = i, Name = "Some name" };
    }
}
```

_Client-Side Code:_
```csharp
var count = 0;
var request = client.CreateRequest("GetSomeObjects").AsStream<SomeObject>();
await foreach (var someObject in request)
{
    if (++count > 5)
    {
        break; // Client cancels after 5 objects
    }
}
```

In this example, the server continues to generate objects well beyond the client's requirements. The client can only signal an cancellation request after receiving the first 5 objects, which is after the serialization buffer has already filled with thousands of objects. 

### Configuration

- .NET version: 6
- OS version: Win 10 / 22H2 / 19045.3570
- Architecture: x64
- Machine specs: AMD Ryzen 9 3900X 12-Core | 64 GB RAM

### Regression?

This behavior has been consistent across the recent versions of .NET; it is not a regression.

### Data

Upon reducing the buffer size to approximately 32 bytes, the initial delay is significantly reduced. This suggests that the buffering strategy could be optimized for handling streams of small JSON objects.

### Analysis

The current implementation of `DeserializeAsyncEnumerable` seems to wait for the internal buffer to fill before yielding objects. This is inefficient for scenarios where objects are small and numerous. I propose introducing an option to allow for immediate yield of deserialized objects as soon as `ReadAsync` returns with any data. This would improve the responsiveness and reduce latency for real-time streaming applications.

**Comment by JKamsker** [comment]
During creating the reproduction code,  i noticed in linqpad, that the issue doesnt seem to persist. The reason for that seems like it's behaving different in dotnet 7 than in dotnet 6.

I guess it can be closed now.
```csharp
using System.IO.Pipelines;
using System.Text.Json;

namespace InteropDemo;
internal class StreamingDemo
{
    public static async Task DemoMain()
    {
        var pipe = new Pipe();
        var cancellationTokenSource = new CancellationTokenSource();

        // Task for the producer to simulate server-side object generation.
        var producerTask = ProduceJsonAsync(pipe.Writer, cancellationTokenSource.Token);

        // Task for the consumer to simulate client-side object consumption.
        var consumerTask = ConsumeJsonAsync(pipe.Reader, cancellationTokenSource);

        // Wait for both to complete
        await Task.WhenAll(producerTask, consumerTask);
    }

    private static async Task ProduceJsonAsync(PipeWriter writer, CancellationToken cancellationToken)
    {
        await JsonSerializer.SerializeAsync(writer.AsStream(), Generator(cancellationToken));

        // Signal to the reader that we're done writing
        await writer.CompleteAsync();
    }

    private static async IAsyncEnumerable<SomeObject> Generator(CancellationToken token)
    {
        for (int i = 0; !token.IsCancellationRequested; i++)
        {
            // Simulate some data generation delay
            await Task.Delay(1);

            // Serialize the object to JSON and write to the pipe
            var someObject = new SomeObject { Id = i }; //, Name = "Some name"
            yield return someObject;
        }

    }

    private static async Task ConsumeJsonAsync(PipeReader reader, CancellationTokenSource cancellationTokenSource)
    {
        try
        {
            // Use DeserializeAsyncEnumerable to read from the pipe
            var items = JsonSerializer.DeserializeAsyncEnumerable<SomeObject>(reader.AsStream(), cancellationToken: cancellationTokenSource.Token);
            await foreach (var someObject in items)
            {
                Console.WriteLine($"Received object: {someObject.Id}");

                // After receiving 5 objects, cancel further reading and hence signal the producer to stop producing
                if (someObject.Id >= 4)
                {
                    cancellationTokenSource.Cancel();
                    break;
                }
            }
        }
        catch (OperationCanceledException)
        {
            Console.WriteLine("Operation has been canceled.");
        }
        finally
        {
            await reader.CompleteAsync();
        }

    }

    public class SomeObject
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

```

**Comment by eiriktsarpalis** [comment]
> During creating the reproduction code, i noticed in linqpad, that the issue doesnt seem to persist. The reason for that seems like it's behaving different in dotnet 7 than in dotnet 6.

Yep, it's a duplicate of https://github.com/dotnet/runtime/issues/70107
