### ISSUE TITLE
Consider enabling EnforceCodeStyleInBuild in runtime to validate IDE rules on build

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#94658]
See https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview?tabs=net-7#enable-on-build

`IDEXXXX` rules aren't validated in a `dotnet build`. Should we enable that validation by setting the `EnforceCodeStyleInBuild` property?

As an example, license headers aren't validated outside of a design time build inside VS: https://github.com/dotnet/runtime/blob/2454fe6785570d4b7d75e366289bcda2f4c363e4/eng/CodeAnalysis.src.globalconfig#L1734-L1735

Related:
- https://github.com/dotnet/runtime/issues/78414
- https://github.com/dotnet/runtime/pull/94085

@stephentoub @akoeplinger

**Comment by ViktorHofer** [comment]
cc @jkotas as this relates to https://github.com/dotnet/runtime/pull/94085 on which you just commented.

**Comment by stephentoub** [comment]
> IDEXXXX rules aren't validated in a dotnet build
> As an example, license headers aren't validated outside of a design time build inside VS:

This is not the case. I just tried removing a header, and IDE0073 triggered with a `dotnet build` at the command-line.

<img width="1459" alt="image" src="https://github.com/dotnet/runtime/assets/2642209/d113f7cc-690e-47dd-91f1-b9c0e3e0eeb3">

We explicitly reference the nuget package containing many of the VS IDE analyzers:
https://github.com/dotnet/runtime/blob/622f34e6546cb75d11902090d59f6ed0a87cf74a/eng/Analyzers.targets#L24
so we get those regardless of whether VS is installed or EnforceCodeStyleInBuild is being used.

It may not be all of them, but it's many of them, and I believe it's most (if not all?) of those we have configured as warnings.

I don't know what the difference is between using that nuget and setting EnforceCodeStyleInBuild.

**Comment by akoeplinger** [comment]
Interesting, looks like that package overrides the built-in codestyle rules:

<img width="1158" alt="image" src="https://github.com/dotnet/runtime/assets/1376924/219ca1b1-5fcb-4fd5-97c1-9461a0ff5ae9">

From what I can see we redistribute that package inside of the SDK so the behavior is the same (modulo version differences): https://github.com/dotnet/sdk/blob/fcc367b2164e4b41b8fb6622110aeb9f3247dd92/src/Layout/redist/redist.csproj#L39

So yeah looks like we don't need to set `EnforceCodeStyleInBuild`.

**Comment by ViktorHofer** [comment]
Alright, thanks for checking. I didn't know that referencing the package overrides that setting.
