### ISSUE TITLE
How can i get the filed "m_length" of "ILGenerator" ?

### ISSUE THREAD

**Issue by owencyc** [dotnet/runtime#94662]
In DotNet 6

`public static int GetILGeneratorLength(ILGenerator ilg)`
`{`
`    System.Reflection.FieldInfo fi = typeof(ILGenerator).GetField("m_length", BindingFlags.Instance | BindingFlags.NonPublic);`
`    return (int)fi.GetValue(ilg);`
`}`

But, in DotNet 8, The **fi** is **null**

With Debug Picture, the First is in Net6, the second is in Net8 
![67b5b8b403de1a38adee472fc9fdc333_](https://github.com/dotnet/runtime/assets/17449095/f0543fd6-5e7f-42c2-a922-f01cd6ea00a8)
![fba05ed36fd590cd3f91b05dc2977b01_](https://github.com/dotnet/runtime/assets/17449095/21583de8-0d7b-43e9-a1e7-2bc48952d1ed)

So, How can i get "m_length" from "ILGenerator" in **NET 8**

**Comment by jkotas** [comment]
`m_length` field is internal implementation detail that was moved to a different type in .NET 8. Code outside the .NET runtime is not supposed to access internal implementation details using private reflection (`BindingFlags.NonPublic`).

You should be able to use the public `ILOffset` property instead:
```
public static int GetILGeneratorLength(ILGenerator ilg) => ilg.ILOffset;
```

**Comment by owencyc** [comment]
> `m_length` field is internal implementation detail that was moved to a different type in .NET 8. Code outside the .NET runtime is not supposed to access internal implementation details using private reflection (`BindingFlags.NonPublic`).
> 
> You should be able to use the public `ILOffset` property instead:
> 
> ```
> public static int GetILGeneratorLength(ILGenerator ilg) => ilg.ILOffset;
> ```

Thinks for your reply!
Background: I'm trying to upgrade a application (from .NET 5 to .NET 8)
The code somewhere indeed need get `m_length` field's value.

By search some document, `ILOffset` is just offset, but `m_length` means total length. Are they both the same concept?

I read this [(issue)](https://github.com/dotnet/runtime/pull/86594#issuecomment-1558189166)
And try to transform my code. Ridiculously, it worked🤣
![image](https://github.com/dotnet/runtime/assets/17449095/9c4b1ea1-da2d-4a19-a734-d5623b21c7d9)

**Comment by jkotas** [comment]
> search some document, ILOffset is just offset, but m_length means total length.

ILOffset is the current offset, that is effectively the total length.

> And try to transform my code. Ridiculously, it worked

Note that inspecting internal implementation details of the runtime like you are doing here is not supported and it is considered a bad practice. It is likely going to break regularly.

**Comment by owencyc** [comment]
> > search some document, ILOffset is just offset, but m_length means total length.
> 
> ILOffset is the current offset, that is effectively the total length.
> 
> > And try to transform my code. Ridiculously, it worked
> 
> Note that inspecting internal implementation details of the runtime like you are doing here is not supported and it is considered a bad practice. It is likely going to break regularly.

Thank you for your answer, I will carefully evaluate the "ILOffset" solution😁
And after a few rounds of simple testing, I found that there is no difference between the two values🤩
![image](https://github.com/dotnet/runtime/assets/17449095/1e97ee98-cc7e-4d5a-95ef-9569e59d1c50)
