### ISSUE TITLE
[wasi] Improve error message for missing WASI SDK

### ISSUE THREAD

**Issue by RReverser** [dotnet/runtime#94671]
### Description

Trying to build a project targeting wasi-wasm with latest preview results in:

> C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Wasi.Sdk\8.0.0-rc.2.23479.6\Sdk\WasiApp.Native.targets(54,5): error : Could not fin 
d wasi-sdk. Either set $(WASI_SDK_PATH), or use workloads to get the sdk. SDK is required for building native files.

### Reproduction Steps

Build any project with `<RuntimeIdentifier>wasi-wasm</RuntimeIdentifier>`, e.g. the default wasi console template while not having WASI SDK installed globally.

### Expected behavior

It should provision WASI SDK automatically when installing the `wasi-experimental` workload. It seems there is some code for this in the repo https://github.com/dotnet/runtime/blob/af0227fad06abc47fe109960a695054b0dcdd473/src/mono/mono.proj#L174-L186 but I guess it's not hooked up all the way?

Alternatively, at least provide a clear error message on how to retrieve one manually for now.

### Actual behavior

The error message says

> or use workloads to get the sdk

even though that doesn't seem to be supported.

**Comment by radical** [comment]
> It seems there is some code for this in the repo

That code is specifically for provisioning the sdk for the runtime build.

> It should provision WASI SDK automatically when installing the wasi-experimental workload.

The aim is to make it be a part of the workload itself. This work is being tracked in https://github.com/dotnet/runtime/issues/82788 . cc @directhex

**Comment by RReverser** [comment]
Yeah I saw the other issue, but wanted to raise one specifically for the error message (hence the title before it was edited).

As far as I understand, the actual integration will take some time, and for the .NET 8.0 release it would be good to fix the error message itself so that it doesn't confuse other users.

**Comment by RReverser** [comment]
Do you mind if I edit the title back so that this issue is not accidentally confused with / as a duplicate of #82788?

**Comment by radical** [comment]
> Do you mind if I edit the title back so that this issue is not accidentally confused with / as a duplicate of #82788?

Indeed the message can be improved.

**Comment by RReverser** [comment]
Oh oops we edited at the same time 😅
