### ISSUE TITLE
File uploader crashes app on iOS when "use device camera" is used instead of "photo library".

### ISSUE THREAD

**Issue by MalleshRavichandran** [dotnet/runtime#94698]
### Description

*File uploader crashes app on iOS when "use device camera" is used instead of "photo library".*

Sample : https://blazorplayground.syncfusion.com/hDVqiMNqfNfGGKup

### Reproduction Steps

1] Run the sample
2] Click the Browse button
3] use camera functionality of mobile browsers and upload it.
4] see the issue ( File uploader crashes )

### Expected behavior

It should upload the file properly.

### Actual behavior

When try to upload the file its crashes the application . 

### Configuration

 iPhone SE 2nd generation with iOS 17 public beta running

### Other information

*The issue is occurring on an iPhone SE 2nd generation with iOS 17 public beta running. We have checked this issue with both the iPhone 14+ and iPhone 12 the issue is not occurring.*

**Comment by steveisok** [comment]
@MalleshRavichandran can you provide what exactly the crash says? The sample link just hangs for me and I don't see anything.

**Comment by YohapujaSelvakumaran** [comment]
@steveisok No, it seemed like it would just crash and restart the app.

**Comment by ivanpovazan** [comment]
> @ivanpovazan it seems to repro only on iPhone SE - do we have a device like that available somewhere?

At the moment, I don't think so.

@YohapujaSelvakumaran is this still occurring with the official release of iOS 17 ?
