### ISSUE TITLE
[Performance] String.IndexOf(StringComparison.OrdinalIgnoreCase) regressed 20% in .NET 8

### ISSUE THREAD

**Issue by ladipro** [dotnet/runtime#94713]
### Description

Case insensitive substring search got considerably slower in .NET 8 compared to .NET 7.

### Configuration

x64
Observed on several different HW configurations - Intel/AMD, VM/bare.

### Regression?

Yes.

### Data

BenchmarkDotNet benchmark:

```C#
using System;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Jobs;

namespace benchmark
{
    [SimpleJob(RuntimeMoniker.Net70)]
    [SimpleJob(RuntimeMoniker.Net80)]
    public class Benchmarks
    {
        internal static string s_haystack = new string('A', 64000);

        internal static string s_needle = "Needle";

        [Benchmark]
        public int IndexOf()
        {
            return s_haystack.IndexOf(s_needle, StringComparison.OrdinalIgnoreCase);
        }   
    }
}
```

Results:

![image](https://github.com/dotnet/runtime/assets/12206368/772def2f-bb27-4acf-9125-e1c130ded589)

**Comment by tannergooding** [comment]
I can repro, I'd guess this is a side effect of: https://github.com/dotnet/runtime/pull/85437

```
BenchmarkDotNet v0.13.10, Windows 11 (10.0.22631.2715/23H2/2023Update/SunValley3)
AMD Ryzen 9 7950X, 1 CPU, 32 logical and 16 physical cores
.NET SDK 8.0.100
  [Host]   : .NET 7.0.14 (7.0.1423.51910), X64 RyuJIT AVX2
  .NET 7.0 : .NET 7.0.14 (7.0.1423.51910), X64 RyuJIT AVX2
  .NET 8.0 : .NET 8.0.0 (8.0.23.53103), X64 RyuJIT AVX2


| Method  | Job      | Runtime  | Mean     | Error     | StdDev    |
|-------- |--------- |--------- |---------:|----------:|----------:|
| IndexOf | .NET 7.0 | .NET 7.0 | 1.208 us | 0.0239 us | 0.0294 us |
| IndexOf | .NET 8.0 | .NET 8.0 | 1.830 us | 0.0220 us | 0.0184 us |
```

It's possible (and potentially likely) that this is simply representative of a non-real scenario as I can also reproduce the performance improvements from @stephentoub's PR where it is searching for real words in real text (many IndexOf calls over sliced text):

| Method  | Job      | Runtime  | Needle     | Mean       | Error     | StdDev     | Median     |
|-------- |--------- |--------- |----------- |-----------:|----------:|-----------:|-----------:|
| Count   | .NET 7.0 | .NET 7.0 | elementary | 361.897 us | 6.8873 us |  7.6552 us | 357.051 us |
| Count   | .NET 8.0 | .NET 8.0 | elementary |  27.513 us | 0.7627 us |  2.2368 us |  28.185 us |
| Count   | .NET 7.0 | .NET 7.0 | holmes     | 270.492 us | 4.9469 us |  7.0947 us | 269.793 us |
| Count   | .NET 8.0 | .NET 8.0 | holmes     |  37.138 us | 2.1970 us |  6.4779 us |  39.993 us |
| Count   | .NET 7.0 | .NET 7.0 | the        | 399.716 us | 7.5714 us |  7.0823 us | 395.404 us |
| Count   | .NET 8.0 | .NET 8.0 | the        |  79.006 us | 3.8579 us | 11.3145 us |  79.545 us |
| Count   | .NET 7.0 | .NET 7.0 | watson     |  80.405 us | 6.9679 us | 20.5451 us |  68.625 us |
| Count   | .NET 8.0 | .NET 8.0 | watson     |  25.939 us | 0.6225 us |  1.8355 us |  26.524 us |

I also tested this, as an edge case
| Count   | .NET 7.0 | .NET 7.0 | AAAAAAA    | 283.529 us | 5.5541 us |  6.8210 us | 283.607 us |
| Count   | .NET 8.0 | .NET 8.0 | AAAAAAA    |  17.588 us | 0.2625 us |  0.2455 us |  17.580 us |

**Comment by stephentoub** [comment]
Right, it's expected that there are cases where this change could make things a little slower in exchange for common cases where it gets way, way faster. The change makes it so that rather than just searching for the first character (in this case, either 'N' or 'n'), it searches for both the first character (either 'N' or 'n') or the last character (either 'E' or 'e').  That means the inner loop of vectorized routine gets a few more instructions.  If the first character _never_matches, as in this example, that means we're spending a few additional instructions per vector unnecessarily.  But if the first character ever does match, the chances that the last character also matches significantly decrease the number of false positives that cause the algorithm to need to break out of its tight inner loop.

**Comment by ladipro** [comment]
Thank you for the quick analysis. I've run into this when benchmarking a piece of code to detect certain patterns in build logs. One of the patterns looks like `[something]` while most log line have no brackets in them. I wouldn't consider it a non-real scenario but I understand the tradeoffs so I think it's not the end of the world.

**Comment by danmoseley** [comment]
Are you searching often for the same thing? Might `SearchValues<T>` help in this case?

**Comment by rainersigwald** [comment]
`SearchValues` would help but there's no way to feed it a set of strings, is there? I could only find a set of characters, which isn't quite what we want.

**Comment by stephentoub** [comment]
> SearchValues would help but there's no way to feed it a set of strings, is there? I could only find a set of characters, which isn't quite what we want.

That's already been merged for .NET 9.  It didn't make .NET 8's cut-off, unfortunately.
