### ISSUE TITLE
Performance Regression with .NET 8 (inlining seems broken in multiple conditions)

### ISSUE THREAD

**Issue by zezba9000** [dotnet/runtime#94750]
### Description
Inlining seems to be broken in .NET 8 (while .NET 7 works perfectly)

## JIT condition .NET 7 (works correctly)
* Open RayTraceBenchmark
* Make sure "#define INLINE" is ENABLED in Benchmark.cs
* Compile for Release & x64
* Results are performant as expected

## JIT condition .NET 7 (works correctly)
* Open RayTraceBenchmark
* Make sure "#define INLINE" is DISABLED in Benchmark.cs
* Compile for Release & x64
* Results are performant as expected

## JIT condition .NET 8 (works mostly correctly)
* Open RayTraceBenchmark
* Make sure "#define INLINE" is ENABLED in Benchmark.cs
* Compile for Release & x64
* Results are performant (however a little regressive from .NET 7)

## JIT condition .NET 8 (huge performance regression)
* Open RayTraceBenchmark
* Make sure "#define INLINE" is DISABLED in Benchmark.cs
* Compile for Release & x64
* Results are much slower than expected

Now here is where it gets strange

## AOT condition .NET 8 (huge performance regression)
* Open RayTraceBenchmark
* Make sure "#define INLINE" is ENABLED in Benchmark.cs
* Compile for Release & x64
* Results are much slower than expected (about the same as INLINE disabled with the JIT)

## AOT condition .NET 8 (works mostly correctly)
* Open RayTraceBenchmark
* Make sure "#define INLINE" is DISABLED in Benchmark.cs
* Compile for Release & x64
* Results are performant

RayTraceBenchmark: https://1drv.ms/u/s!Alt5wRhQYKD7gfwzrRJkcJg7ZNw9jQ?e=kfsqhR

### Configuration
Windows 11
.NET 8 with builds targeting x64
Visual Studio 2022 17.8

### Regression?
.NET 7 does not have this issue

### Analysis
It appears maybe some internal compiler flag involving inlining could be set incorrectly.

**Comment by jakobbotsch** [comment]
Seems like PGO causes us to stop inlining in some cold blocks, but that heavily impacts codegen of the hot blocks. If I disable tiered PGO (`DOTNET_TieredPGO=0`) then NET 8 is 5-10% faster than .NET 7 on my machine (without `#define INLINE` in the source).

cc @EgorBo @AndyAyersMS

**Comment by zezba9000** [comment]
Part of this was caused from this borked line.
.NET 8 JIT is now faster.
However AOT in .NET 8 is still a lot slower. (but this should be a new ticket if anything)
![image](https://github.com/dotnet/runtime/assets/1857902/f793ecc8-0ee8-459d-a460-1ccaf39892e6)

**Comment by lakecherry** [comment]
After setting "TargetFramework=.NET8", JIT seems to be unable to inline/optimize in release mode ... at least stepping through disassembly looks like debug code ... after switching back to "TargetFramework=.NET7", everything as expected ...
