### ISSUE TITLE
dotnet publish with RID pull latest runtime packages and can fail

### ISSUE THREAD

**Issue by xoofx** [dotnet/runtime#94763]
### Description

Hello runtime folks 🙂 

Yesterday, all of our CI at Unity suddenly failed in some unexpected ways while running dotnet publish. We have a NuGet proxy in front of NuGet and it tried to pull a package like `microsoft.netcore.app.runtime.win-x64.7.0.14.nupkg` and for some reasons, it failed with this kind of error:

```
error NU1102: Unable to find package Microsoft.NETCore.App.Runtime.win-x64 with version (= 7.0.14)
```

Our CI is configured to use/pin a specific .NET version e.g `7.0.102`, but it happens that at the same time, a new .NET 7 version was published SDK 7.0.404 (so .NET Runtime 7.0.14), while our locally version was older.

I can see that locally in the folder `C:\Program Files\dotnet\sdk\7.0.111\Sdks\Microsoft.DotNet.ILCompiler\runtime.json`, my runtime json is like this:

```json
{
  "runtimes": {
    "linux-arm": {
      "#import": [],
      "Microsoft.DotNet.ILCompiler": {
        "runtime.linux-arm.Microsoft.DotNet.ILCompiler": "[7.0.11, )"
      }
    },
    "linux-arm64": {
      "#import": [],
      "Microsoft.DotNet.ILCompiler": {
        "runtime.linux-arm64.Microsoft.DotNet.ILCompiler": "[7.0.11, )"
      }
    },
    "linux-musl-arm64": {
      "#import": [],
      "Microsoft.DotNet.ILCompiler": {
        "runtime.linux-musl-arm64.Microsoft.DotNet.ILCompiler": "[7.0.11, )"
      }
    },
    "linux-musl-x64": {
      "#import": [],
      "Microsoft.DotNet.ILCompiler": {
        "runtime.linux-musl-x64.Microsoft.DotNet.ILCompiler": "[7.0.11, )"
      }
    },
    "linux-x64": {
      "#import": [],
      "Microsoft.DotNet.ILCompiler": {
        "runtime.linux-x64.Microsoft.DotNet.ILCompiler": "[7.0.11, )"
      }
    },
    "osx-x64": {
      "#import": [],
      "Microsoft.DotNet.ILCompiler": {
        "runtime.osx-x64.Microsoft.DotNet.ILCompiler": "[7.0.11, )"
      }
    },
    "win-arm64": {
      "#import": [],
      "Microsoft.DotNet.ILCompiler": {
        "runtime.win-arm64.Microsoft.DotNet.ILCompiler": "[7.0.11, )"
      }
    },
    "win-x64": {
      "#import": [],
      "Microsoft.DotNet.ILCompiler": {
        "runtime.win-x64.Microsoft.DotNet.ILCompiler": "[7.0.11, )"
      }
    }
  }
}
```

So, I have 3 questions:

- Do I understand correctly that ILCompiler is configured to pull the latest package version?
- Could this behavior be disabled in some ways?
- If not, could we pin the ILCompiler version instead so that we avoid pulling a different version in our CI?

Thanks!

### Reproduction Steps

- Install an older .NET 7 SDK (e.g 7.0.102) (But don't have installed a latest 7.0 version)
- Create a new console app `dotnet new console -n TestNet7`
- `dotnet publish -p:PublishAot=true -c Release -r win-x64 -v diag TestNet7\TestNet7.csproj`

During the restore phase, you will see in the log:

```
Downloading a package from 'https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app.runtime.win-x64/7.0.14/microsoft.netcore.app.runtime.win-x64.7.0.14.nupkg'
```

### Expected behavior

`dotnet publish` with `PublishAot = true` should only pull the associated ILCompiler version of the .NET SDK instead of pulling a latest version.

### Actual behavior

`dotnet publish` with `PublishAot = true` is pulling the latest version of ILCompiler and not respecting the local version.

### Regression?

No

### Configuration

- Windows 10.0.22621
- .NET 7 version installed `7.0.111 [C:\Program Files\dotnet\sdk]`

**Comment by xoofx** [comment]
Actually, it's probably not related to ILCompiler, but just specifying a RID `win-x64` is downloading these packages in their latest version form?

**Comment by agocke** [comment]
Right, background is that the runtime-RID packages are what we call "runtime packs", and they basically contain the components of the runtime and framework to be delivered to self-contained applications. ILCompiler is the same idea, but instead of coreclr+libs it has the AOT runtime+libs.

The intent is that the runtime pack pulled exactly matches the version of the SDK that you're using. This would mean that you would get the same version of the runtime if you're using a framework-dependent deployment or a self-contained deployment. 

I think there are a few options:

1. Use a NuGet feature to pull some packages from an upstream repo. This would let you pull from NuGet if the package isn't in your internal feed.
2. Add new packages to your internal feed every time you update your SDK
3. Use a global.json to lock the SDK version you're using. If this one sounds a little scary because you might miss security updates, it should. But that's the same experience as if you locked the runtime pack version. Any security patches that appear in the framework or runtime wouldn't come into your publish.

I think ideally you would grab every patch version that comes out, since many of those patches contain security fixes.

**Comment by xoofx** [comment]
> 3\. Use a global.json to lock the SDK version you're using. If this one sounds a little scary because you might miss security updates, it should. But that's the same experience as if you locked the runtime pack version. Any security patches that appear in the framework or runtime wouldn't come into your publish.

Ok, great, thanks for confirming. I think we will select this option. I have been pinning the SDK version for all my OSS projects due to preview .NET versions sometimes creating trouble (and folks reporting invalid errors) but never realized that if a SDK was not pinned, latest version of runtime packages could still be downloaded. I always thought that pinning was only preventing to switch to another local SDK installed.

For Unity, it is critical that we have a predictable build that doesn't change overnight (as it did yesterday in addition to a bug likely in our NuGet proxy) and that we actually validate the new versions before bumping, even it they are patches.

Thanks for the clarification!

**Comment by agocke** [comment]
> I always thought that pinning was only preventing to switch to another local SDK installed.

It is, but in this case the SDK you're using to publish decides what version of the runtime pack to use, so functionally by letting the installed version of the SDK float, you're letting the runtime pack reference float. It's actually implemented by the SDK adding an implicit package reference of the given version to the project.

**Comment by xoofx** [comment]
> It is, but in this case the SDK you're using to publish decides what version of the runtime pack to use, so functionally by letting the installed version of the SDK float, you're letting the runtime pack reference float. It's actually implemented by the SDK adding an implicit package reference of the given version to the project.

Yep, exactly, that was the missing bit (SDK float -> runtime pack float)
