### ISSUE TITLE
new DirectoryEntry(nativeMember) becomes out of scope and is not disposed

### ISSUE THREAD

**Issue by achufistov** [dotnet/runtime#94777]
### Description

dotnet 6.0

File: /src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/SAM/SAMQuerySet.cs:838

Problem: new DirectoryEntry(nativeMember) becomes out of scope and is not disposed

### Reproduction Steps

1) Role: detected
detected
[SAMQuerySet.cs:[838:0]]

2) Role: tracepoint
2.1 Step 1: Condition groupDE.Properties["objectSid"] == null taking false branch
[SAMQuerySet.cs:[824:17]]
2.2 Step 2: Condition groupDE.Properties["objectSid"].Count == 0 taking false branch
[SAMQuerySet.cs:[824:60]]
2.3 Step 3: Entering the foreach
[SAMQuerySet.cs:[834:64]]
2.4 created in constructor System.DirectoryServices.DirectoryEntry.DirectoryEntry(object)
[SAMQuerySet.cs:[838:43]]
2.5 no escape
[SAMQuerySet.cs:[838:43]]
2.6 assigned
[SAMQuerySet.cs:[838:32]]
2.7 no escape
[SAMQuerySet.cs:[841:21]]
2.8 Step 4: Condition memberDE.Properties["objectSid"] == null taking false branch
[SAMQuerySet.cs:[841:21]]
2.9 no escape
[SAMQuerySet.cs:[841:65]]
2.10 Step 5: Condition memberDE.Properties["objectSid"].Count == 0 taking false branch
[SAMQuerySet.cs:[841:65]]
2.11 no escape
[SAMQuerySet.cs:[847:44]]
2.12 end of scope
[SAMQuerySet.cs:[857:28]]

### Expected behavior

memory leak

### Actual behavior

memory leak

### Other information

Found by Linux Verification Center (linuxtesting.org) with SVACE.

**Comment by achufistov** [comment]
I would like to suggest a pull request.

**Comment by buyaa-n** [comment]
Looks simple fix, can be covered with https://github.com/dotnet/runtime/issues/94772, closing
