### ISSUE TITLE
SDSUtils.BuildDirectoryEntry(_ctxBase.Path, _credentials, _authTypes) becomes out of scope and is not disposed

### ISSUE THREAD

**Issue by achufistov** [dotnet/runtime#94780]
### Description

dotnet 6.0

File: /src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/SAM/SAMStoreCtx.cs:647

Problem: SDSUtils.BuildDirectoryEntry(_ctxBase.Path, _credentials, _authTypes) becomes out of scope and is not disposed

### Reproduction Steps

1) Role: detected
detected
[SAMStoreCtx.cs:[647:0]]

2) Role: tracepoint
2.1 Step 1: Condition p.fakePrincipal taking true branch
[SAMStoreCtx.cs:[616:18]]
2.2 created in method System.DirectoryServices.AccountManagement.SDSUtils.BuildDirectoryEntry(string, System.DirectoryServices.AccountManagement.NetCred, System.DirectoryServices.AuthenticationTypes)
[SAMStoreCtx.cs:[647:44]]
2.3 no escape
[SAMStoreCtx.cs:[647:44]]
2.4 Step 2: Condition principalSid == null taking true branch
[SAMStoreCtx.cs:[657:21]]
2.5 Step 3: Statement throw new InvalidOperationException(SR.StoreCtxNeedValueSecurityIdentityClaimToQuery); throws exception
[SAMStoreCtx.cs:[660:27]]
2.6 end of scope
[SAMStoreCtx.cs:[672:24]]

### Expected behavior

memory leak

### Actual behavior

memory leak

### Other information

Found by Linux Verification Center (linuxtesting.org) with SVACE.

**Comment by achufistov** [comment]
I would like to suggest a pull request.

**Comment by buyaa-n** [comment]
Similar to https://github.com/dotnet/runtime/issues/94779, closing as duplicate
