### ISSUE TITLE
SDSUtils.BuildDirectoryEntry(_ctxBase.Path, _credentials, _authTypes) is not disposed at the end of the function

### ISSUE THREAD

**Issue by achufistov** [dotnet/runtime#94781]
### Description

dotnet 6.0

File: /src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/SAM/SAMStoreCtx_Query.cs:88

Problem: SDSUtils.BuildDirectoryEntry(_ctxBase.Path, _credentials, _authTypes) is not disposed at the end of the function

### Reproduction Steps

1) Role: detected
detected
[SAMStoreCtx_Query.cs:[88:0]]

2) Role: tracepoint
2.1 created in method System.DirectoryServices.AccountManagement.SDSUtils.BuildDirectoryEntry(string, System.DirectoryServices.AccountManagement.NetCred, System.DirectoryServices.AuthenticationTypes)
[SAMStoreCtx_Query.cs:[88:40]]
2.2 no escape
[SAMStoreCtx_Query.cs:[88:40]]
2.3 Step 1: Condition ps.QueryFilter != null taking true branch
[SAMStoreCtx_Query.cs:[94:17]]
2.4 return
[SAMStoreCtx_Query.cs:[108:20]]

### Expected behavior

memory leak

### Actual behavior

memory leak

### Other information

Found by Linux Verification Center (linuxtesting.org) with SVACE.

**Comment by achufistov** [comment]
I would like to suggest a pull request.

**Comment by buyaa-n** [comment]
Similar to https://github.com/dotnet/runtime/issues/94779, closing as duplicate
