### ISSUE TITLE
Microsoft.Extensions.FileProviders.Abstractions 8.0.0 miss net7.0 TFM

### ISSUE THREAD

**Issue by iwedaz** [dotnet/runtime#94812]
### Description

I think there is inconsistency in TFM:

* Microsoft.Extensions.FileProviders.Abstractions 8.0.0 doesn't have net7.0 TFM, despite the fact that Physical and Composite implementations have it.
I see no reason for deleting net7.0 TFM.

* Microsoft.Extensions.FileProviders.Embedded 8.0.0 also doesn't have net7.0 TFM.
It might be intended. It's a part of aspnetcore and have different config in csproj.

### Reproduction Steps

Check [Microsoft.Extensions.FileProviders.Abstractions nuget](https://www.nuget.org/packages/Microsoft.Extensions.FileProviders.Abstractions#supportedframeworks-body-tab)

Check [Microsoft.Extensions.FileProviders.Embedded nuget](https://www.nuget.org/packages/Microsoft.Extensions.FileProviders.Embedded/#supportedframeworks-body-tab)

### Expected behavior

Because most of Microsoft.Extensions.* 8.0.0 assemblies keep net7.0 TFM, it should be there.

Also assemblies have net7.0 TFM:
* Microsoft.Extensions.FileProviders.Physical
* Microsoft.Extensions.FileProviders.Composite

### Actual behavior

src/libraries/Microsoft.Extensions.FileProviders.Abstractions/src/Microsoft.Extensions.FileProviders.Abstractions.csproj

`<TargetFrameworks>$(NetCoreAppCurrent);$(NetCoreAppMinimum);netstandard2.0;$(NetFrameworkMinimum)</TargetFrameworks>`

Miss $(NetCoreAppPrevious)

**Comment by Jozkee** [comment]
Probably an overlook because the ref project does have $(NetCoreAppPrevious):
https://github.com/dotnet/runtime/blob/94694710183845273add3bf4f532cc08c1c73b70/src/libraries/Microsoft.Extensions.FileProviders.Abstractions/ref/Microsoft.Extensions.FileProviders.Abstractions.csproj#L3

@iwedaz is not clear to me how does this affect your use case? cc @carlossanlop.
