### ISSUE TITLE
Configuration Binding inconsitent handling of initial values for unset options

### ISSUE THREAD

**Issue by nic547** [dotnet/runtime#94814]
### Description

The behavior of the new source-generator configuration binder seems to handle unset options differently than the old reflection based one.
Given an "options" class with an int property with an initial value of 1 and a json file that doesn't contain this property, the
old ConfigurationBinder will return an option object with the property set to 1. The new one however will return the object with the value set to 0. 

I'm not quite sure whether this is intended or not.

### Reproduction Steps

Minimal example, using
`Microsoft.Extensions.Configuration`
`Microsoft.Extensions.Configuration.Binder`
`Microsoft.Extensions.Configuration.Json`

```
using Microsoft.Extensions.Configuration;

namespace ConfigTest;

internal class Program
{
    static void Main(string[] args)
    {
        ConfigurationBuilder builder = new();
        builder.AddJsonFile("./test.json");
        var config = builder.Build();

        var options = config.GetSection("Test").Get<Options>();

        Console.WriteLine(options?.NoValue);
    }

    public class Options
    {
        public int NoValue { get; set; } = 8080;
    }
}
```

```{
  "Test": {
    "Value": 1
  }
}
```

### Expected behavior

Running the application with `<EnableConfigurationBindingGenerator>false</EnableConfigurationBindingGenerator>` or `<EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>` will yield the same result.

### Actual behavior

`<EnableConfigurationBindingGenerator>false</EnableConfigurationBindingGenerator>` will cause NoValue to be set to 8080
`<EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>` will cause NoValue to be set to 0

### Regression?

No

### Configuration

Windows 11 22H2, x64, NET 8.0
The issue also seems to happen on Debian/Raspberry Pi OS Bullseye ARM64, NET 8.0

**Comment by mockjv** [comment]
I'm seeing similar results with `TimeSpan` and `Enum` types.  I'm also observing that `.Bind()` extension isn't exhibiting this behavior.

The minimal example that I'd put together that reproduces this:

```csharp
var config = new ConfigurationManager().AddJsonFile("appsettings.json").Build();
var jsonOpts = new JsonSerializerOptions {WriteIndented = true};

// Get<TType>()
var getResult = config.GetSection("Section").Get<MyConfiguration>();
Console.WriteLine("Get<TType>()");
Console.WriteLine(JsonSerializer.Serialize(getResult, jsonOpts));

// Bind()
var bindResult = new MyConfiguration();
config.Bind("Section", bindResult);
Console.WriteLine($"{Environment.NewLine}Bind()");
Console.WriteLine(JsonSerializer.Serialize(bindResult, jsonOpts));

public class MyConfiguration
{
    public int IntVal1 { get; set; } = 8080;
    public string StrVal1 { get; set; } = "default1";
    public string StrVal2 { get; set; } = "default2";
    public TimeSpan TimeSpanVal1 { get; set; } = TimeSpan.FromHours(1);
    public Uri UriVal1 { get; set; } = new("https://default:5001");
    public MyEnum EnumVal1 { get; set; } = MyEnum.enum4;
}

public enum MyEnum
{
    enum1,
    enum2,
    enum3,
    enum4
}
```

The result when `EnableConfigurationBindingGenerator` is enabled:

```text
Get<TType>()
{
  "IntVal1": 0,
  "StrVal1": "changed!",
  "StrVal2": "default2",
  "TimeSpanVal1": "00:00:00",
  "UriVal1": "https://default:5001",
  "EnumVal1": 0
}

Bind()
{
  "IntVal1": 8080,
  "StrVal1": "changed!",
  "StrVal2": "default2",
  "TimeSpanVal1": "01:00:00",
  "UriVal1": "https://default:5001",
  "EnumVal1": 3
}
```

**Comment by mgaffigan** [comment]
I'm hit with this as well.  I've not confirmed, but it seems like this might be coming from the logic at https://github.com/dotnet/runtime/blob/0588f245dba6418349c22894b40337afc34f1cfc/src/libraries/Microsoft.Extensions.Configuration.Binder/gen/Emitter/CoreBindingHelpers.cs#L873-L877

The change seems to have come in from https://github.com/dotnet/runtime/pull/91899, which was based on a seemingly oppositely related issue https://github.com/dotnet/runtime/issues/86333
