### ISSUE TITLE
HTTP client metrics: url.scheme should be opt-in, server.port should be required

### ISSUE THREAD

**Issue by lmolkova** [dotnet/runtime#94829]
### Description

OTel HTTP semconv made the last-minute change https://github.com/open-telemetry/semantic-conventions/pull/459 before stability and now HTTP client metrics are not fully aligned with the spec (sorry).

Even though it's a pretty minor difference it'd be nice to align with the OTel spec at some point.

### Reproduction Steps

N/A

### Expected behavior

- `url.scheme` is now opt-in, so should be set when explicitly enabled (or not set at all)
- `server.port` should be set even when it has a default value 

### Actual behavior

scheme is always set, port is set when not default.

https://github.com/dotnet/runtime/blob/33d7f9815a4cf0ceb19f7014f978137218855a32/src/libraries/System.Net.Http/src/System/Net/Http/Metrics/MetricsHandler.cs#L192-L198

**Comment by antonfirsov** [comment]
The current state (having a redundant scheme tag, not reporting default ports) doesn't actively hurt users from a practical POV. Given it's such a minor aspect, I wonder if maintaining maximum standard-compatibility is worth the burden of a breaking change where we may need to implement a compatibility switch, which would add complexity to the code. @noahfalk what's your take on this?

**Comment by antonfirsov** [comment]
Triage: adding this to 9.0 for decision making, and potential fixing (see comment above).

**Comment by antonfirsov** [comment]
Related: #103302. Opt-in attributes likely need an API addition. Punting this to .NET 10.

**Comment by lmolkova** [comment]
would it be possible to report `server.port` (and don't change anything for scheme)? It would not require API changes, it does not seem to have any downsides (telemetry volume is the same, not breaking) and would align .NET metrics with OTel better.

**Comment by antonfirsov** [comment]
I was confused, since I was looking at the wrong metrics. We should add `server.port`.
