### ISSUE TITLE
Incorrect SYSLIB1102 error

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#94826]
### Description

I updated grpc/grpc-dotnet to use .NET 8 SDK. A new error showed up in a project with `<PublishTrimmed>true</PublishTrimmed>`: SYSLIB1102

![image](https://github.com/dotnet/runtime/assets/303201/2c7e5f12-0114-438d-b5c6-1a73eac0dc1b)

The description at https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib1100-1118 says C# 11 or later is required. I verified my app is using C# 11:

```xml
<Target Name="WriteVersion" BeforeTargets="BeforeCompile">
  <Message Importance="High" Text="Version: $(LangVersion)" />
</Target>
```

```
Build started at 11:38 am...
1>------ Build started: Project: LinkerTestsWebsite, Configuration: Debug Any CPU ------
1>Version: 11.0
1>CSC(1,1,1,1): error SYSLIB1102: (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1102)
1>Done building project "LinkerTestsWebsite.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 3 up-to-date, 0 skipped ==========
========== Build completed at 11:38 am and took 00.520 seconds ==========
```

The problem disappeared after I changed `<LangVersion>` to 12.0.

### Reproduction Steps

See https://github.com/grpc/grpc-dotnet/pull/2321

Change the version back to 11.0 to see the error.

### Expected behavior

Either works with C# 11, or the warning correctly says C# 12 is required.

### Actual behavior

Breaks with C# 11, and a warning says C# 11 or later is required.

### Regression?

I think this regressed between .NET 8 RC1 and .NET 8 RTM (although I might not have been using the final version of RC1. It definitely worked during .NET 8 previews)

**Comment by tarekgh** [comment]
The error message is wrong. it should specify `12` not `11`. The source gen is using the compiler [interceptors](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-12#interceptors) feature which is introduced in v12.

**Comment by JamesNK** [comment]
If you look at the screenshot and build output, you’ll also see there is no error message, just the link. I think that should be fixed as well.

**Comment by tarekgh** [comment]
> If you look at the screenshot and build output, you’ll also see there is no error message, just the link. I think that should be fixed as well.

That is interesting. We have tests to check the diag https://github.com/dotnet/runtime/blob/45978bd7191fcbb793dc12b162540022063551b6/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/SourceGenerationTests/GeneratorTests.cs#L30. Do you see this happen for only this generator and this message? or does it happen with other generators? 

You may try the code like https://github.com/dotnet/runtime/blob/45978bd7191fcbb793dc12b162540022063551b6/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/SourceGenerationTests/GeneratorTests.cs#L42 and look what you get for other diags. I'll try to look too when I get a chance.
