### ISSUE TITLE
LibraryImport generator can't generate correct syntax for ref struct

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/runtime#94840]
The current generated syntax is `internal ref unsafe partial struct`. However, current C# version requires `unsafe` to be in front of `ref`, e.g. `internal unsafe ref partial struct`.

The error message is also confusing now (type name required).

Related: https://github.com/dotnet/csharplang/blob/main/meetings/2018/LDM-2018-04-04.md#ordering-of-ref-and-partial-keywords

**Comment by AaronRobinsonMSFT** [comment]
@jtschuster Is this something you can quickly address?

**Comment by jtschuster** [comment]
Yeah, I'll take a look at it
