### ISSUE TITLE
[.NET 8][iOS] AOT compiler exited with code 134

### ISSUE THREAD

**Issue by akravch** [dotnet/runtime#94841]
### Description

Since updating to .NET 8, I am unable to build the project that uses the `Silk.NET.OpenAL` package. I am not completely sure that it is not the package to blame, but since it builds on .NET 7 this looks more like a .NET regression to me.

### Reproduction Steps

Run the following command in terminal:

```
dotnet new ios --output AotIssue && \
dotnet add AotIssue package Silk.NET.OpenAL --version 2.19.0 && \
dotnet build AotIssue
```

### Expected behavior

The app builds successfully.

### Actual behavior

Compilation fails with the following error:

```
usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.0.8478/targets/Xamarin.Shared.Sdk.targets(1211,3): error : Failed to AOT compile Silk.NET.OpenAL.dll, the AOT compiler exited with code 134. [/Users/username/source/AotIssue/AotIssue.csproj]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.0.8478/targets/Xamarin.Shared.Sdk.targets(1211,3): error : Failed to AOT compile aot-instances.dll, the AOT compiler exited with code 134. [/Users/username/source/AotIssue/AotIssue.csproj]
```

Running the command with diagnostic verbosity I see that there is a failed assertion in mono code:

```
Tool /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.AOT.osx-arm64.Cross.iossimulator-arm64/8.0.0/Sdk/../tools/mono-aot-cross execution finished (exit code = 134).
         (TaskId:183)
Mono Ahead of Time compiler - compiling assembly /Users/username/source/AotIssue/obj/Debug/net8.0-ios/iossimulator-arm64/linked/Silk.NET.OpenAL.dll
AOTID 9089B537-2843-EFEF-1C24-AEDFC6367DF7
* Assertion at /Users/runner/work/1/s/src/mono/mono/metadata/marshal.c:3837, condition `!sig->has_type_parameters' not met
```

### Regression?

This works if you change the project target framework from `net8.0-ios` to `net7.0-ios`.

### Known Workarounds

I was able to make the sample compile by forcibly trimming the assembly with `<TrimMode>partial</TrimMode>` and `<TrimmableAssembly Include="Silk.NET.OpenAL" />`, but this is not an option for our simulator builds.

### Configuration

.NET 8.0.100
iOS workload 17.0.8478/8.0.100
XCode 15.0.1
macOS 13.6 (22G120) on an M1 chip

**Comment by lambdageek** [comment]
https://github.com/dotnet/runtime/blob/487d7f010b90a82178d55eea21e72dc6dedf9d5d/src/mono/mono/metadata/marshal.c#L3837

It's complaining about some managed to native wrapper with in `mono_marshal_get_native_func_wrapper_indirect`

**Comment by Perksey** [comment]
Can you confirm whether this occurred on Silk.NET 2.17 or 2.18? If the runtime bug is first triggered in 2.18 and 2.19 then I know exactly what's causing it.

**Comment by Perksey** [comment]
cc @dotnet/silk-dotnet also @okaniku wrt dotnet/Silk.NET#1770 (2.19) and dotnet/Silk.NET#1680 (2.18)

On closer inspection it could be the use of `char` in the delegate* signature.

**Comment by akravch** [comment]
> Can you confirm whether this occurred on Silk.NET 2.17 or 2.18? If the runtime bug is first triggered in 2.18 and 2.19 then I know exactly what's causing it.

2.18, 2.17 and 2.16 do not compile either. Actually, bisecting through the versions 1.9.0 is the last stable version that compiles. 2.0.0-preview still compiles too, but anything from 2.0.0-preview2 fails with the same failed assertion.

**Comment by Perksey** [comment]
Oh wow, you really went back huh. Okay so it's not what I thought it was, so there's probably something more sinister in the runtime happening here. We used System.Reflection.Emit to emit calli instructions up until 2.0.0-preview2 because C# did not have function pointers at this time.

Will leave the Mono team to investigate, just wanted to make sure it wasn't a really recent change that caused this! Thanks for looking into this.

**Comment by ivanpovazan** [comment]
I inspected further the problem with referencing the `Silk.NET.OpenAL` library and confirmed that the AOT compiler crashes when we try to compile the GSHAREDVT variant of the following method:

```csharp
// Silk.NET.OpenAL.Extensions.FormatExtensionBase<TExtendedBufferFormat>
public unsafe void BufferData(uint buffer, TExtendedBufferFormat format, void* data, int size, int frequency)
{
	((System.UIntPtr/*delegate* unmanaged[Cdecl]<uint, TExtendedBufferFormat, void*, int, int, void>*/)(void*)(long)(base.CurrentVTable as _B)._I)(buffer, format, data, size, frequency);
}
```
ref: https://github.com/dotnet/Silk.NET/blob/d4d55347bb5d4aa9f316b516abf05ed4d8a66bfe/src/OpenAL/Silk.NET.OpenAL/Extensions/FormatExtensionBase.cs#L25

The problem seems to be related to casting a IntPtr into a unmanaged function pointer with a generic parameter.
The crash is also reproducible with .NET7

### Smaller repro for reference

native code:
```objc
void* getNativeFunctionPointer()
{
    return printMe;
}

void printMe(int num)
{
    os_log_info (OS_LOG_DEFAULT, "Printing out number: '%d'.", num);
}
```

managed code:
```cs
public static class InteropUtil
{
    [DllImport("__Internal")]
    public static extern IntPtr getNativeFunctionPointer();
}

unsafe public class NativeInvoker<T>
{
    public void Invoke(IntPtr fptr, T arg)
    {
        var func = (delegate* unmanaged<T, void>)fptr;
        func(arg);
    }
}

// ...

var invoker = new NativeInvoker<int>();
invoker.Invoke(InteropUtil.getNativeFunctionPointer(), 42);
        
```

Crashes with:
```
error : * Assertion at /Users/ivan/repos/runtime-mono-iOS/src/mono/mono/metadata/marshal.c:3837, condition `!sig->has_type_parameters' not met
```

---

I will take a look at fixing this.

**Comment by Perksey** [comment]
A user has encountered this again in .NET 8 again recently: dotnet/Silk.NET#2209. Is there any update on this CoreCLR/NativeAOT vs Mono issue?

**Comment by jkurdek** [comment]
@ivanpovazan I verified that on net9 the repro you shared compiles correctly as macios sample app.

**Comment by jkurdek** [comment]
The issue is not reproducible anymore. I'm closing it. Please reopen should you encounter it again.
