### ISSUE TITLE
AES-GCM is supported for `net8.0` TFM but not for `net8.0-maccatalyst` TFM

### ISSUE THREAD

**Issue by MartyIX** [dotnet/runtime#94848]
### Description

AES-GCM is supported for the `net8.0` TFM on my Apple Silicon M1 machine (arm64) but it is not supported for `net8.0-maccatalyst` TFM (seemingly). 

I was looking forward to the .NET 8 release but to my surprise the feature is now supported but only for console applications but not .NET MAUI (MacCatalyst) ones.

I would say that https://learn.microsoft.com/en-us/dotnet/standard/security/cross-platform-cryptography is a bit confusing as is because it does not mention that `macOS` does not cover MacCatalyst. 

### Reproduction Steps

`dotnet new console` and modify `Program.cs` as follows:

```cs
// See https://aka.ms/new-console-template for more information
using System.Data.SqlTypes;
using System.Security.Cryptography;

byte[] bytes = new byte[32];
AesGcm aes = new(bytes, 16); // Works OK, no exception.
```

Then `dotnet new maui` and modify `MainPage.xaml.cs` as follows:

```diff
private void OnCounterClicked(object sender, EventArgs e)
{
	count++;

	if (count == 1)
		CounterBtn.Text = $"Clicked {count} time";
	else
		CounterBtn.Text = $"Clicked {count} times";

+	try {
+		byte[] bytes = new byte[32];
+		AesGcm aes = new(bytes, 16); // throws
+	} catch (Exception ex) {
+		CounterBtn.Text = $"{ex}";
+	}
}
```

I can see that `NotSupportedException` is thrown.

### Expected behavior

My original expectation was that MacCatalyst would be supported too.

### Actual behavior

My .NET MAUI MacCatalyst app throws `NotSupportedException`.

### Regression?

I don't think so.

### Known Workarounds

No. I would really love to know if there is one.

### Configuration

* Apple Silicon M1, macOS Sonoma 14.1
* .NET 8

**Comment by vcsjones** [comment]
Mac Catalyst apps use the iOS platform, not the macOS platform, unfortunately. We were not able to add AES-GCM support for iOS, but that work is tracked in https://github.com/dotnet/runtime/issues/91523. When iOS support is added, Catalyst should get it at the same time.

This is working more or less "as expected" for me, but sorry to say that getting CryptoKit in for iOS (and by extension, Catalyst) was not done for .NET 8.

> No. I would really love to know if there is one.

@filipnavara can perhaps offer some advice here, if it is possible at all.

**Comment by filipnavara** [comment]
Unfortunately I don't expect this to be fixed until .NET 9 where we bumped the minimum version requirement. :-/ There's no workaround for the `AesGcm` class itself, and calling the CryptoKit API directly would require writing a native shim in the same way .NET does (and limit you to Mac Catalyst 15+ or so).

**Comment by vcsjones** [comment]
>  would say that https://learn.microsoft.com/en-us/dotnet/standard/security/cross-platform-cryptography is a bit confusing as is because it does not mention that macOS does not cover MacCatalyst.

This is reasonable feedback. I think we can clarify the tables and text there that MacCatalyst is a separate platform.

**Comment by neon-sunset** [comment]
Libsodium apparently supports Catalyst and given that C# bindings for it exist (and writing your own is [very simple](https://github.com/KubaZ2/NetCord/blob/aaa730010e2219349e187ed71fc346c203009ecb/NetCord/Gateway/Voice/Encryption/Libsodium.cs) if needed), you could try it as an alternative for the time being.

**Comment by akoeplinger** [comment]
https://github.com/dotnet/runtime/issues/91523 tracks the main work, I see that @vcsjones already opened a PR to clarify the docs (thanks!) so this is working as expected for net8.0 and we'll make it work for net9.0.
