### ISSUE TITLE
Support SSLKEYLOGFILE for SslStream on Windows

### ISSUE THREAD

**Issue by rzikm** [dotnet/runtime#94843]
https://github.com/dotnet/runtime/pull/90429 implemented support for SSLKEYLOGFILE for Linux. Additional work is needed to support the "feature" on Windows and SChannel (quotes because it is available only for Debug builds of the libraries and thus not available in public releases).

Inspiration can be drawn from source code of MsQuic, which allows extracting TLS 1.3 secrets (exposed in runtime via https://github.com/dotnet/runtime/pull/83001)

Original issue #37915

**Comment by rzikm** [comment]
Triage: not critical for 9.0, putting to Future for now.

**Comment by wfurt** [comment]
I'm not sure if this is feasible besides Quic but we can taka a look.
