### ISSUE TITLE
Improve Unix Console.ReadLine by borrowing from PowerShell's ReadLineFromConsole

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#94860]
On Unix, .NET uses its own Console.ReadLine implementation which is very minimalistic.

PowerShell has a more feature rich ReadLine implementation here: https://github.com/PowerShell/PowerShell/blame/5cd04f2377b624dedd17a85ff3f38a0343292477/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs#L1567.
It include things like: arrows keys, home, end, delete, ...

We can borrow some things from that to improve the UX of Console.ReadLine on Unix.

cc @dotnet/area-system-console @adamsitnik @stephentoub

**Comment by gfoidl** [comment]
@tmds from the title

> Improve Unix Console.WriteLine

Can you change that to be `Console.ReadLine`?

**Comment by adamsitnik** [comment]
We would get #38051 fixed? That would be great! I am supportive of that idea.

**Comment by tmds** [comment]
Yes, arrow keys are part of this.

You can assign this to me.
