### ISSUE TITLE
Obtaining a Span<Base> out of an array of Derived reference type

### ISSUE THREAD

**Issue by TomSolomon** [dotnet/runtime#94874]
class Base{}
class Derived : Base {}
Given Derive[] , is it possible to get a Span<Base> out of it without a copy?

**Comment by stephentoub** [comment]
`ReadOnlySpan<T>` will "just work", as it doesn't support writing and thus doesn't need the covariance checks I assume you're running into.  You can just do:
```C#
var array = new Derived[...];
var span = new ReadOnlySpan<Base>(array);
```
and it'll work fine.

`Span<T>` won't "just work", as its `Span<T>(T[])` constructor will validate that typeof(T[]) == array.GetType(). Without that, if you had a `Span<Base>` and you had both `Derived : Base` and `AlsoDerived : Base`, and if the `Span<Base>` was actually backed by a `Derived[]` as in your example, you could end up writing an `AlsoDerived` into that `Derived[]`, which would violate type safety.

If you're willing to accept that risk and promise not to do such things, you can use unsafe code to achieve it, via the MemoryMarshal.CreateSpan method, for example:
```C#
Span<Base> span = MemoryMarshal.CreateSpan(ref MemoryMarshal.GetArrayDataReference<Base>(array), array.Length)
```
Just keep in mind the concern above: you've bypassed the safety guards in doing this.

**Comment by TomSolomon** [comment]
Thanks for the reply, You can close the question
