### ISSUE TITLE
FreeBSD tests fail to build on Windows 10. Suspect is System.Private.mscorlib.dll

### ISSUE THREAD

**Issue by RussellHaley** [dotnet/runtime#9487]
I submitted a pull request some days back with no comments yet (7days). I am splitting out the issue I am having into a separate er, issue. I modified the build-test.cmd to get them to run, but the build failure seems to be with missing portions of the mscorlib. (see pull request https://github.com/dotnet/coreclr/pull/15627 for changes)

I have not been able to get the FreeBSD tests to successfully build on Windows 10. First I build the FreeBSD corlib, then build the tests:

build.cmd -freebsdmscorlib
Which builds successfully. Running build-test.cmd -buildos FreeBSD sets __buildOS=FreeBSD, __noCrossgen=1, __targetWindows=0

build-test.cmd -buildos FreeBSD
...
baseservices.compilerservices.XUnitWrapper.cs(20,83): error CS0117: 'Assembly' does not contain a definition for 'GetExecutingAssembly' 

[c:\Users\russh\Git\dotnet\coreclr\bin\tests\FreeBSD.x64.Debug\TestWrappers\baseservices.compilerservices\baseservices.compilerservices.XUnitWrapper.csproj]

My conjecture at this point is that the correct partial classes for Assembly.cs are not being added when building the FreeBSD System.Private.MsCorlib.dll via build.cmd -freebsdmscorlib

Thoughts? Please let me know which build outputs you would like (pertaining to the aforementioned error).

**Comment by wfurt** [comment]
this is so old and probably not applicable any more. We should now be able to build & run tests on FreeBSD.
