### ISSUE TITLE
.NET 9, Android: AOT compiler currently fails with an assertion

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/runtime#94880]
### Description

This started happening in our PR moving to .NET 9:

https://github.com/xamarin/xamarin-android/pull/8366

`dotnet build -c Release` fails with:
```
Microsoft.Android.Sdk.Aot.targets(109,5): Precompiling failed for obj\Release\android-arm64\linked\Java.Interop.dll with exit code 57005.
Mono Ahead of Time compiler - compiling assembly C:\a\_work\1\a\TestRelease\11-15_21.06.00\temp\BasicProjectTrue\obj\Release\android-arm64\linked\Java.Interop.dll
AOTID AF248EDF-40DF-6D3F-1C1A-A37FAD329420
Using profile data file 'C:\a\_work\1\s\bin\Release\dotnet\packs\Microsoft.Android.Sdk.Windows\34.99.0-ci.darc-main-583d6f71-0641-4428-9c9f-b64ebed2e33e.85\targets\dotnet.aotprofile'
Added 167 methods from profile.
* Assertion at D:\a\_work\1\s\src\mono\mono\mini\mini-arm64.c:673, condition `imms >= 0 && imms < 128' not met 
```

### Reproduction Steps

1. `dotnet new android`
2. `dotnet build -c Release`

### Expected behavior

No build error

### Actual behavior

Build error with assertion in `mini-arm64.c`

### Regression?

Yes

### Known Workarounds

You could disable the AOT compiler with `RunAOTCompilation=false`.

### Configuration

.NET SDK: 9.0.100-alpha.1.23563.1
Runtime: 9.0.0-alpha.1.23557.14

### Other information

Binlog: [net9aot.zip](https://github.com/dotnet/runtime/files/13384722/net9aot.zip)

I tried updating the AOT profile, just to see if it would help: https://github.com/xamarin/xamarin-android/pull/8366/commits/2bf05c3c28c1b3bac278e7405c44025390ed1ac6

But I get the same issue, still.

**Comment by steveisok** [comment]
@vargaz can you look into this?

**Comment by vargaz** [comment]
Seems to be caused by:
https://github.com/dotnet/runtime/pull/93606

**Comment by vargaz** [comment]
Can't test it, but the problem might be in the definition of ```mono_lzcnt32```/```mono_lzcnt64``` on windows:

```
int mono_lzcnt32 (guint32 x)
{
#ifdef _MSC_VER
	unsigned long index = 0;
	if ( _BitScanReverse( &index, x ) )
		return (int)index;
	else
		return 32;
#else
	return __builtin_clz(x);
#endif
}
```

For 12, __builtin_clz () returns 28, while according to msdn,  _BitScanReverse () returns 3:
https://learn.microsoft.com/en-us/cpp/intrinsics/bitscanreverse-bitscanreverse64?view=msvc-170

**Comment by vargaz** [comment]
https://github.com/dotnet/runtime/pull/94901

**Comment by vargaz** [comment]
Could you bump the version in the PR to see if #94901 fixes it ?

**Comment by jonathanpeppers** [comment]
It looks like the dotnet/runtime in dotnet/installer is about 3 weeks old.

For now, I tried moving ahead to get the latest runtime: https://github.com/xamarin/xamarin-android/pull/8366/commits/5702a63a6ebb4fd338bd7a3bb68e484edcfd85ef

**Comment by jonathanpeppers** [comment]
It took a little work to get the right runtime bits installed, but this appears to be fixed now.

We still have some test failures, but all of the AOT failures before look to be gone. Thanks!
