### ISSUE TITLE
DateTime.ParseExact throws exception with message missing original string

### ISSUE THREAD

**Issue by azhmur** [dotnet/runtime#94907]
### Description

If incorrect string passed to ParseExact, exception message misses original string and reports empty string instead.

### Reproduction Steps

DateTime.ParseExact("XXXXX", "MM/dd/yyyy", CultureInfo.InvariantCulture);

### Expected behavior

net7:
System.FormatException: String 'XXXXX' was not recognized as a valid DateTime.

### Actual behavior

net8:
System.FormatException: String '' was not recognized as a valid DateTime.

### Regression?

Yes. Works correctly in net7.

### Configuration

net8, windows-x64

**Comment by vcsjones** [comment]
Closing as a duplicate of https://github.com/dotnet/runtime/issues/94837.
