### ISSUE TITLE
Regex engine treats non-capture groups as Captures

### ISSUE THREAD

**Issue by NidusUmbra** [dotnet/runtime#94905]
### Description

It is quite difficult as is to tease out what should easily manifest from a properly written regex pattern and search due to a lot of object-nesting, however there is a key issue that is simply an error, which is what is treated as "Capture", which is essentially everything in the pattern, including (?:this), which is non-capturing-group notation. There is also a curious workaround among the Regex options called "Explicit capture", which shouldn't be needed in the first place, but also does not work. Everything that matches the regex gets included.

If this is not a bug, then it's nonetheless an error. There is no regex flavor that treats non-capture groups as capture groups.

### Reproduction Steps

Run this code...

Regex pattern = new Regex("(?:U\\+)(?<start>[A-F0-9]{4})(?:\\.\\.U\\+)(?<end>[A-F0-9]{4})", RegexOptions.ExplicitCapture);

var body = @" 0 BMP	U+0700..U+074F	Syriac	80	77	Syriac
 0 BMP	U+0750..U+077F	Arabic Supplement	48	48	Arabic
 0 BMP	U+0780..U+07BF	Thaana	64	50	Thaana
 0 BMP	U+07C0..U+07FF	NKo	64	62	N’Ko
 0 BMP	U+0800..U+083F	Samaritan	64	61	Samaritan";

var captured = pattern.Matches(body);
foreach (var item in captured)
{
	if (item is Match match)
		foreach (var cap in match.Captures)
			Console.WriteLine(cap);
}

You could also run a default config regex with unnamed captures like so:
new Regex("(?:U\\+)([A-F0-9]{4})(?:\\.\\.U\\+)([A-F0-9]{4})")
With the same result as listed below.

### Expected behavior

0700
074F
0750
077F
... and so on.

### Actual behavior

U+0700..U+074F
U+0750..U+077F
U+0780..U+07BF
U+07C0..U+07FF
U+0800..U+083F

### Regression?

I'm not sure.

### Known Workarounds

Elaborate extension methods, possibly. These would then include secondary regex searches to finally get accurate output.

### Configuration

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

Device name	****
Processor	Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz   3.30 GHz
Installed RAM	16.0 GB
Device ID	D8C20252-2F0E-4C03-B38E-B2A1C7E05A35
Product ID	00330-50418-97307-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 11 Pro
Version	22H2
Installed on	‎2/‎23/‎2023
OS build	22621.2715
Experience	Windows Feature Experience Pack 1000.22677.1000.0

### Other information

I realize that if this is established code and not a bug, any fundamental change to the class can be breaking, and when regex breaks it does so horribly. One possible solution would be to add an enum-member to RegexOptions whereunder the proper syntax gets to define the result. This way it would not be breaking and also comparatively easy to fix.

**Comment by redflitzi** [comment]
Maybe I am wrong here, but I feel that this Regex behavior is correct.

What you get printed this way, is the captured "group[0]" of each Match, which always contains the whole expression that matched the whole Regex pattern.
You do not see captured (and uncaptured) subexpression here, as you might expect. You can access these  with accessing subsequent groups, not captures.

Please correct me if I am wrong.

**Comment by stephentoub** [comment]
> Please correct me if I am wrong.

You are not wrong.

> Regex engine treats non-capture groups as Captures

It does not. Those non-capture groups are in fact non-capture groups and do not capture. As @redflitzi says, you're seeing result of the design where the entire match is group[0]; there aren't any other captures here beyond that.

**Comment by stephentoub** [comment]
I'm not sure what argument you're making.  Non-capture groups evaporate entirely as part of parsing: after the regex is parsed, they literally don't exist as far as the engine is concerned.  For example, this:
```C#
using System.Text.RegularExpressions;

Console.WriteLine(Regex.Match("IT AT", "(?:I)(T)(?: AT)").Groups.Count);
Console.WriteLine(Regex.Match("IT AT", "(I)(T)( AT)").Groups.Count);
```
prints out:
```
2
4

Or if you have this:
```C#
static partial class Examples
{
    [GeneratedRegex("(?:I)(T)(?: AT)")]
    public static partial Regex NonCapturing();

    [GeneratedRegex("(I)(T)( AT)")]
    public static partial Regex Capturing();
}
```
and hover over the first and second, you'll see this:

<img width="155" alt="image" src="https://github.com/dotnet/runtime/assets/2642209/b7e99d5e-34b5-4420-adc5-ea190a493053">

<img width="167" alt="image" src="https://github.com/dotnet/runtime/assets/2642209/2e4d2f3c-cb64-4bbd-858c-52ecb6287923">

Note how the latter explicitly calls out capturing the groups, and the former is as if there weren't any groups at all, because there weren't... the non-capture groups evaporated.

> A more clear example of the problem

Again, this isn't showing what you're saying it's showing.  This:
```C#
Console.WriteLine(Regex.Matches("IT AT", "(?:I)(T)(?: AT)")[0].Captures.Count);
```
outputs:
```
1

There's a single capture, Captures[0], for the entire match.  That's always implicit.  You'll have that regardless of the pattern being used and what capturing or non-capturing groups it may or may not contain.  Case in point, this:
```C#
using System.Text.RegularExpressions;

Console.WriteLine(Regex.Matches("asdf", "")[0].Captures.Count);
```
also prints `1`.

**Comment by redflitzi** [comment]
If you want the matched content for `(T)` or `(?<named>T)`, you're just looking in the wrong place.

Captures are subordinate to Groups, which are subordinate to Match.
If you omit Groups in the hierachy, Groups[0] is assumed. And this Groups[0] contains the whole matched expression. Subsequent groups hold the inner matching ... ehm, groups.
So look into Groups[1] or Groups["named"], there you will find the value "T".

Captures are another thing. They come into play when there are more instances of _the same group_ (when the Regex pattern allow this). But in more simple scenarios, the subpatterns are captured in the different Groups (with the whole thng in Groups[0]), and each of them have only one Capture.

**Comment by NidusUmbra** [comment]
> If you want the matched content for `(T)` or `(?<named>T)`, you're just looking in the wrong place.
> 
> Captures are subordinate to Groups, which are again subordinate to Match. If you omit Groups in the hierachy, Groups[0] is assumed. And this Groups[0] contains the whole matched expression. Subsequent groups hold the inner matching ... ehm, groups. So look into Groups[1] or Groups["named"], there you will find the value "T".
> 
> Captures are another thing. They come into play when there are more instances of _the same group_ (when the Regex pattern allow this). But in more simple scenarios, the subpatterns are captured in the different Groups (with the whole thing in Groups[0]), and each of them have only one Capture.

I am looking for captures specifically, not matches. See further comments below.

> I'm not sure what argument you're making. Non-capture groups evaporate entirely as part of parsing: after the regex is parsed, they literally don't exist as far as the engine is concerned. For example, this:
> 
> ```cs
> using System.Text.RegularExpressions;
> 
> Console.WriteLine(Regex.Match("IT AT", "(?:I)(T)(?: AT)").Groups.Count);
> Console.WriteLine(Regex.Match("IT AT", "(I)(T)( AT)").Groups.Count);
> ```
> 
> prints out:
> 
> ```
> 2
> 4
> 
> Or if you have this:
> ```C#
> static partial class Examples
> {
>     [GeneratedRegex("(?:I)(T)(?: AT)")]
>     public static partial Regex NonCapturing();
> 
>     [GeneratedRegex("(I)(T)( AT)")]
>     public static partial Regex Capturing();
> }
> ```
> 
> and hover over the first and second, you'll see this:
> 
> <img alt="image" width="155" src="https://user-images.githubusercontent.com/2642209/284010294-b7e99d5e-34b5-4420-adc5-ea190a493053.png"> <img alt="image" width="167" src="https://user-images.githubusercontent.com/2642209/284010311-2e4d2f3c-cb64-4bbd-858c-52ecb6287923.png">
> Note how the latter explicitly calls out capturing the groups, and the former is as if there weren't any groups at all, because there weren't... the non-capture groups evaporated.
> 
> > A more clear example of the problem
> 
> Again, this isn't showing what you're saying it's showing. This:
> 
> ```cs
> Console.WriteLine(Regex.Matches("IT AT", "(?:I)(T)(?: AT)")[0].Captures.Count);
> ```
> 
> outputs:
> 
> ```
> 1
> 
> There's a single capture, Captures[0], for the entire match.  That's always implicit.  You'll have that regardless of the pattern being used and what capturing or non-capturing groups it may or may not contain.  Case in point, this:
> ```C#
> using System.Text.RegularExpressions;
> 
> Console.WriteLine(Regex.Matches("asdf", "")[0].Captures.Count);
> ```
> 
> also prints `1`.

I am looking for captures specifically, not matches which is why I am querying the property ".Captures" of type CaptureCollection which per the specs should contain:
"//
// Summary:
// Represents the set of captures made by a single capturing group. The collection
// is immutable (read-only) and has no public constructor.
[DefaultMember("Item")]
public class CaptureCollection"...

This implies your line 
"Console.WriteLine(Regex.Matches("asdf", "")[0].Captures.Count)"
Should print "0", because there is no capture, only a match.

Also your prior lines don't reflect my example, perhaps that was not the intention but for clarity:
"Console.WriteLine(Regex.Matches("IT AT", "(?:I)(T)(?: AT)")[0].Captures.Count);"
Will indeed print 1, but a print-foreach loop will print:
IT AT
Which is not conducive to documentation or the canonical meaning of Capture. It should only print "T".

I noted earlier that CaptureCollection yields Match'es, not Capture's or Group's (see the GetType() prints). I genuinely think a mistake has been made, I am not arguing for any personal preference.

**Comment by stephentoub** [comment]
> but a print-foreach loop will print: IT AT

Yes, it's printing the single capture of the entire match. As noted, every match implicitly captures the whole match, that's part of the design. The output in your example of  "IT AT" has nothing to do with the groups used inside the expression.

**Comment by redflitzi** [comment]
Yes you are looking for captures. And it seems to me that you search Match.Captures because you assume that there, in that CaptureCollection, should somehow be all captures included that the Match contains.

But this is wrong.
You are implicitely caught inside Groups[0]. And Groups[0] has only and exactly one Capture, and that is the whole expression that matched the whole Regex pattern.

> Also your prior lines don't reflect my example, perhaps that was not the intention but for clarity:
> "Console.WriteLine(Regex.Matches("IT AT", "(?:I)(T)(?: AT)")[0].Captures.Count);"
> Will indeed print 1, but a print-foreach loop will print:
> IT AT
> Which is not conducive to documentation or the canonical meaning of Capture. It should only print "T".
> 

No, it should not.
Your `Matches[0].Captures.Count` is implicitely `Matches[0].Groups[0].Captures.Count`.
And as I wrote above, that is 1 and it contains the whole "IT AT" hit.

Inside a Match, there is no independent "root" Captures hierarchy that has all captures of all groups.
It may look like this, but is only syntactical sugar over Groups[0].Captures.
So if you want the capture that has the "T", you will have to access Matches[0].Groups[1].Captures.
You won't find it in Matches[0].Captures.

**Comment by danmoseley** [comment]
Note also that this regex engine is unusual, possibly unique, in that it gives you every matching location of a capture not just the last one. That makes the API a little more complicated, but it can be useful.

**Comment by NidusUmbra** [comment]
> Note also that this regex engine is unusual, possibly unique, in that it gives you every matching location of a capture not just the last one. That makes the API a little more complicated, but it can be useful.

It is useful for sure. One of the best in fact. But having non-capture groups and whole matches showing up under a property named "Captures", of type "CaptureCollection", with the stated behavior "Represents the set of captures made by a single capturing group." isn't useful.

Anyway, all regex engine implementations (in languages) I've used have something idiosyncratic going on and actual regex standards aren't implemented anywhere that I know of, so it's not the end of the world. :)

Straightforward solution:
var namedcaptures = pattern.Matches(body).Where(x => x.Name != "" && x.Name is not null);

**Comment by danmoseley** [comment]
The API can't be changed, but if you believe the help can be improved you are welcome to offer a PR.

**Comment by NidusUmbra** [comment]
> The API can't be changed, but if you believe the help can be improved you are welcome to offer a PR.

Can it be added to? I had the idea of introducing another member to the RegexOptions-enum ("RegexOptions.simplified" perhaps) and adding method/s, or branching the ".Captures" getter, such that returns are simply any and all captured matches in the canonical sense, i.e. "(this)", when the flag is set. Extension methods work too of course. I make my own but I doubt they will be as performant as anything dotnet-devs can produce.

**Comment by danmoseley** [comment]
It's breaking changes we can't make. You're welcome to open an API proposal for any API suggestions.
