### ISSUE TITLE
[browser] improve behavior after exit

### ISSUE THREAD

**Issue by bogdancucosel** [dotnet/runtime#94906]
We should

- be louder about it when you are calling into stopped runtime
        was there any message in the console ?
        was there unhandled exception from your onClick ?
- the error messages could point out what's the fix
- change the browser template to use exit-less runMain and keep one with exit only for console template
- dotnet.run jsdoc should say that it's going to stop the runtime

**Comment by HendrikMennen** [comment]
I noticed too that in my app all attempts of reading a file asynchronous will block. In net7 this was working fine. I know that using async read in an webassembly with one thread makes no big sense, but my code is shared with Desktop too (Avalonia), so it is a breaking limitation/bug

**Comment by radical** [comment]
cc @maraf @pavelsavara

**Comment by bogdancucosel** [comment]
In the mean time, I saw that dotnet.run() actually runs dotnetInstance.runMainAndExit().
If I call 
```
//await dotnet.run();
await dotnetInstance.runMain(config.mainAssemblyName, []);
```
calling from the button handler works. 

I think that makes sense in a way . Not sure why other asyncs except the IO ones work, but calling exit does imply that probably app context will be shutdown etc...

So, I guess, this is normal ?

**Comment by pavelsavara** [comment]
You don't have to call `await dotnet.run();` at all, you could just call your export.
Also there is `runMain` and `runMainAndExit`.

```
const { runMain } = await dotnet.create()
await runMain("mainAssemblyName", []);
```

process exit (and exit code) matters for use-cases like unit tests and nodejs/console apps.
for web page it maybe doesn't make that much sense to shut down by default.

I think we should
- be louder about it when you are calling into stopped runtime 
    - was there any message in the console ? 
    - was there unhandled exception from your onClick ?
-  possibly the error messages could point out what's the fix
- change the browser template to use exit-less runMain and keep one with exit only for console template

**Comment by bogdancucosel** [comment]
> was there any message in the console ?
was there unhandled exception from your onClick ?

No, I had no messages or exceptions . 

Thanks a lot for the info . 
You can close this issue now, if you will not use it to track the changes you mentioned.
It's all clear now , thanks again

**Comment by pavelsavara** [comment]
original description:


### Description

Created a simple WASM app by using 

```
dotnet create wasmbrowser
```

I am running with dotnet 8.0.100 sdk.

Created an async method that is exported to js. The method creates and writes some text to a file and then reads it async , by using File.ReadAllTextAsync.

```
    [JSExport]
    public static async Task CreateFileSyncReadAsync(string path)
    {
        var text = "The text written to the file";
        File.WriteAllText(path, text);
        Console.WriteLine($"Sync written to file {path}: {text}");

        var textReadSync = File.ReadAllText(path);
        Console.WriteLine($"Sync read file {path}: {textReadSync}");

        Console.WriteLine("Will start to read async the file; this will block when called from onclick of the button...");
        var textReadAsync = await File.ReadAllTextAsync(path);
        Console.WriteLine($"Async read file {path}: {textReadAsync}");
    }
```

When called from main.js, it works.
When called from an html's button onclick , it is blocked in File.ReadAllTextAsync.

```
document.getElementById('btn1').onclick = async () => {
    console.log('Start calling CreateFileSyncReadAsync from button click');
    await exports.MyClass.CreateFileSyncReadAsync("/testFromBtn1.txt");
    console.log('End calling CreateFileSyncReadAsync from button click');
};
```

Am I calling it wrong from the onclick handler ?

await Task.Delay(500); works in both cases

### Reproduction Steps

Pull https://github.com/bogdancucosel/ReproWasmBlocking and run the project.
In the browser's console you will see:

```
Start calling CreateFileSyncReadAsync from main.js
Sync written to file /testFromMain.txt: The text written to the file
Sync read file /testFromMain.txt: The text written to the file
Will start to read async the file; this will block when called from onclick of the button...
Async read file /testFromMain.txt: The text written to the file
End calling CreateFileSyncReadAsync from main.js

Start calling CreateFileSyncReadAsync from button click
Sync written to file /testFromBtn1.txt: The text written to the file
Sync read file /testFromBtn1.txt: The text written to the file
Will start to read async the file; this will block when called from onclick of the button...
``` 

### Expected behavior

```
var textReadAsync = await File.ReadAllTextAsync(path); 
```

The above call should fetch data from the file and return.

### Actual behavior

```
var textReadAsync = await File.ReadAllTextAsync(path); 
``` 

the above code does not return; it's not calling the open/read methods in js.

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_
