### ISSUE TITLE
Segmentation fault when running in emulated amd64 container on M1 Mac

### ISSUE THREAD

**Issue by anthony-c-martin** [dotnet/runtime#94909]
### Description

This is a stripped down repro of https://github.com/Azure/bicep/issues/10245, which has been reported by a number of our users trying to use a VSCode extension in an amd64 emulated devcontainer image.

It seems like the usage of [Regex.Match](https://learn.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.match?view=net-7.0) is causing a segmentation fault when run in an amd64 image emulated on an M1 Mac.

### Reproduction Steps

Open a `bash` prompt in an amd64 Docker container on an M1 Mac:

```bash
docker container run -it --platform=linux/amd64 mcr.microsoft.com/vscode/devcontainers/python:0-3.10-bullseye bash
```

Run the following to repro the issue:
```bash
wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
chmod +x ./dotnet-install.sh
./dotnet-install.sh --channel 7.0

git clone https://github.com/anthony-c-martin/dotnet-regex-rosetta-repro.git
cd dotnet-regex-rosetta-repro

/root/.dotnet/dotnet run
```

### Expected behavior

The console app should log "Success!"

### Actual behavior

The following is logged:
```
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault
```

**Comment by vcsjones** [comment]
Setting `DOTNET_EnableWriteXorExecute=0` fixes it:

> `DOTNET_EnableWriteXorExecute=0 /root/.dotnet/dotnet run`
> Success!

So I am assuming this has something to do with double memory mapping.

If I am not mistaken, [Docker uses QEMU emulation](https://www.docker.com/blog/the-magic-behind-the-scenes-of-docker-desktop/) to run x86_64 on Apple Silicon, and .NET [is not supported in QEMU](https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md#qemu).

**Comment by sergiorru** [comment]
@vcsjones 

Since docker version [4.25.0](https://docs.docker.com/desktop/release-notes/#4250) the QEMU is not the default emulation used anymore, it's Rosetta2.

Using the working around as you proposed (add DOTNET_EnableWriteXorExecute=0) worked for [this](https://github.com/anthony-c-martin/dotnet-regex-rosetta-repro.git) sample.

**Comment by stephentoub** [comment]
> and .NET [is not supported in QEMU](https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md#qemu).

Yup, this was discussed here:
https://github.com/dotnet/runtime/issues/78340#issuecomment-1581660624

**Comment by anthony-c-martin** [comment]
Thanks! I'll make sure we document that qemu is unsupported. It would be amazing if there's a way to detect this and warn the user (not sure how feasible however).

To make sure I'm understanding correctly, the following are **both** required to support the scenario:
1. Use Rosetta2 emulation (simplest option is to just upgrade to Docker desktop v4.25.0 or higher)
1. Set the `DOTNET_EnableWriteXorExecute` env var to `0`

@stephentoub do you happen to have an explanation for why the env var is required? Is this to work around an issue in Rosetta2? Are you aware of any recommended approaches to detecting an emulated environment?

**Comment by steveisok** [comment]
re: why `DOTNET_EnableWriteXorExecute=0` is required... I have to guess that the running container can't tell Rosetta is involved. From https://github.com/dotnet/runtime/pull/70912, it appears double mapping isn't supported when running in Rosetta. If we can't tell, then we'll take the x64 default.

@jkotas does that sound right?

**Comment by vcsjones** [comment]
Note that this will be better in .NET 9: https://github.com/dotnet/runtime/pull/102509
