### ISSUE TITLE
[NativeAOT] [osx-arm64] dotnet publish fails on latest sdk (8.0.100) with missing build-local.sh

### ISSUE THREAD

**Issue by ruby0x1** [dotnet/runtime#94951]
### Description

Hi!
I have a very simple empty cs project that I'm trying to build for osx-arm64 on an arm64 host, but it fails on an internal build step. Maybe I missed something but I think this is standard user space workflow that has an issue?

M2 Max arm64 host, with MacOS Sonoma 14.1.1
SDK: Downloaded latest arm64 from [here](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-8.0.100-macos-arm64-installer) as 8.0.100.

The error seems to be [this missing file](https://github.com/dotnet/runtime/blob/main/src/native/libs/build-local.sh). (The comment in the file says it's linux only, but maybe that's outdated.) 
```js
/Users/ruby/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/8.0.0/native/src/libs/build-local.sh: No such file or directory
```
The contents of the nuget package doesn't include a native/ folder at all:

<img width="732" alt="image" src="https://github.com/dotnet/runtime/assets/236374/2a538c86-217c-439f-9fb0-5eb78e987ac9">

The command executed with log:

```js
ruby@unvoid csproj % dotnet publish -r osx-arm64
MSBuild version 17.8.3+195e7f5a3 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  game -> /Users/ruby/dev/test/csharp/csproj/bin/Release/net8.0/osx-arm64/game.dll
  /var/folders/02/329x9k4x37n30lz3l012715m0000gn/T/MSBuildTempruby/tmpfada3f95384144f4a64c4db2d7b18e05.exec.cmd: line 2: /Users/ruby/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/8.0.0/native/src/libs/build-local.sh: No such file or directory
/Users/ruby/.nuget/packages/microsoft.dotnet.ilcompiler/8.0.0/build/Microsoft.NETCore.Native.Unix.targets(241,5): error MSB3073: The command "CC="clang" "/Users/ruby/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/8.0.0/native/src/libs/build-local.sh" "/Users/ruby/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/8.0.0/" "obj/Release/net8.0/osx-arm64/" System.Globalization.Native" exited with code 127. [/Users/ruby/dev/test/csharp/csproj/game.csproj]
```

The cs project itself:

```js
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <StaticICULinking>true</StaticICULinking>
    <StaticOpenSslLinking>true</StaticOpenSslLinking>
    <PublishAot>true</PublishAot>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
```

### Reproduction Steps

run `dotnet publish -r osx-arm64` on the latest sdk

### Expected behavior

I'd expect the build to succeed

### Actual behavior

There's a blocking error in the internal build steps

### Regression?

No, this is a new feature in .net 8 (I didn't test on any pre-release sdks for .net 8)

### Known Workarounds

none

**Comment by filipnavara** [comment]
```
    <StaticICULinking>true</StaticICULinking>
    <StaticOpenSslLinking>true</StaticOpenSslLinking>
```

These options are only supported on Linux. macOS always links to the system ICU and the native security libraries.

**Comment by ruby0x1** [comment]
Oh there we go, it's working now. Thanks @filipnavara! 

(I'd imagine a clearer error message for that would be a handy addition for posterity).

Side note, I copied this project from a previous one I was using on .net7, and I'm fairly certain I was working on Windows and not Linux at the time... those flags didn't cause a build failure (maybe they just do nothing there?). Maybe I'm misremembering, but figured I'd mention.

**Comment by filipnavara** [comment]
> (I'd imagine a clearer error message for that would be a handy addition for posterity).

Agreed. I didn't even know the option was documented so I didn't really pay much attention to it.

> Side note, I copied this project from a previous one I was using on .net7, and I'm fairly certain I was working on Windows and not Linux at the time... those flags didn't cause a build failure (maybe they just do nothing there?). Maybe I'm misremembering, but figured I'd mention.

There are two different `.targets` files in the SDK that split the Windows and Unix build logic. The property is ignored in the Windows one. macOS and Linux share the Unix build logic and that's why it falls into the trap. Since macOS was not officially supported until .NET 8 we were less likely to see anyone hitting this.
