### ISSUE TITLE
[Enhancement] Provide More Detailed Information in System.TypeLoadException for Incorrect MethodImplAttribute Marking

### ISSUE THREAD

**Issue by lindexi** [dotnet/runtime#94967]
I encountered an issue when incorrectly marking the MethodImplAttribute attribute on a method, specifically choosing the MethodImplOptions.InternalCall parameter. This results in a System.TypeLoadException being thrown before the type is accessed, with the error message "Internal call method with non_NULL RVA". 

The System.TypeLoadException is thrown before the type is accessed and only includes the TypeName property to indicate which type is causing the error. It does not provide further information to indicate which specific method has been incorrectly marked with the attribute.

This lack of detailed information can significantly slow down the debugging process, especially when dealing with a type that contains hundreds of methods, some of which may be correctly marked and others not. Without specific information about which method is causing the issue, it can take a considerable amount of time to identify the problem.

As my demo code (https://github.com/lindexi/lindexi_gd/tree/96014b44231c7e6920abf4373521359705e8cb0c/GagageheLoqearrergi ), you can find the exception be thrown in the Line 3.

I propose that the exception thrown in this scenario should include more detailed information, such as which specific method has been incorrectly defined. This would greatly improve the efficiency of the debugging process.

Thank you for considering this enhancement request. I look forward to your feedback.

**Comment by lindexi** [comment]
The "Internal call method with non_NULL RVA" message is defined in mscorc.rc

https://github.com/dotnet/runtime/blob/47a94224e865195fd89cf8336ebd022e769d978d/src/coreclr/dlls/mscorrc/mscorrc.rc#L588

**Comment by jkotas** [comment]
Changing `BuildMethodTableThrowException(BFA_INTERNAL_METHOD_WITH_RVA)` to `BuildMethodTableThrowException(BFA_INTERNAL_METHOD_WITH_RVA, tok)` should fix this. Similar for surrounding BuildMethodTableThrowException calls - some of them are passing the token already.

The change should be made in methodtablebuilder.cpp. 

`classcompat.*` is an archived copy of the type loader used by built-in COM interop. We prefer to keep it alone.

**Comment by jkotas** [comment]
@lindexi Are you interested in submitting the fix?

**Comment by MichalPetryka** [comment]
Would it maybe make sense to mark InternalCall as EditorBrowseableState.Never?

**Comment by lindexi** [comment]
@MichalPetryka When do we need to use InternalCall ?

**Comment by MichalPetryka** [comment]
AFAIR the only case an user would have to use it is with Mono Embedding API (which is a really advanced scenario already).

**Comment by lindexi** [comment]
I agree with you. Maybe it's a better idea to mark it as EditorBrowseableState.Never.

**Comment by jkotas** [comment]
> @MichalPetryka When do we need to use InternalCall ?

InternalCall is used to define built-in COM interop. Also, it can be used for inspection - reflection or System.Reflection.Metadata.

**Comment by lindexi** [comment]
> @lindexi Are you interested in submitting the fix?

@jkotas Sorry, I'm afraid I don't have enough ability to modify this module.

**Comment by lindexi** [comment]
Thank you very much.
