### ISSUE TITLE
[API Proposal]: DefaultMeterFactory should probably not be internal

### ISSUE THREAD

**Issue by EugeneKrapivin** [dotnet/runtime#94972]
### Background and motivation

Making this class internal will lead to "copy-paste" it from the runtime source in cases a project does not use the dotnet DI solution. I'm working on an older project which still uses Ninject (we are net6, migrating our infra projects to net8).

```csharp
public static class MetricsNinjectExtensions
{
    /// <summary>
    /// Adds metrics services to the specified <see cref="IKernel" />.
    /// </summary>
    /// <param name="services">The <see cref="IKernel" /> to add services to.</param>
    /// <returns>The <see cref="IKernel"/> so that additional calls can be chained.</returns>
    public static IMetricsRegistrar AddMetrics(this IKernel services)
    {
        ArgumentNullException.ThrowIfNull(services, nameof(services));

        if (services.GetBindings(typeof(IMetricsRegistrar)).Any()) 
            return services.Get<IMetricsRegistrar>();

        services.Bind<IMeterFactory>()
            .To<DefaultMeterFactory>()
            .InSingletonScope();

        var builder = new BaseMetricsBuilder(services);

        services.Bind<IMetricsRegistrar>().ToConstant(builder);
        
        return builder;
    }
}
```
my code uses the [`DefaultMeterFactory`](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Diagnostics/src/Metrics/DefaultMeterFactory.cs#L11C5-L11C46) so that we could inject it down the line.

### API Proposal

Do:
```csharp
    public sealed class DefaultMeterFactory : IMeterFactory
```
Instead of:
```csharp
    internal sealed class DefaultMeterFactory : IMeterFactory
```

### API Usage

```csharp
        services.Bind<IMeterFactory>() // services is a Ninject Kernel instance
            .To<DefaultMeterFactory>() // currently impossible due to scoping
            .InSingletonScope();
```

**Comment by steveharter** [comment]
> in cases a project does not use the dotnet DI solution

The [Microsoft.Extensions.DependencyInjection.MetricsServiceExtensions.AddMetrics](https://learn.microsoft.com/dotnet/api/microsoft.extensions.dependencyinjection.metricsserviceextensions.addmetrics) 
 is located in the assembly `Microsoft.Extensions.Diagnostics`, not a DI assembly.

Is the issue you need to have different semantics than AddMetrics()?

**Comment by EugeneKrapivin** [comment]
Hey! thanks for the response.

`AddMetrics` is a method that only supports the default dotnet dependency injection through `IServiceCollection`. 
In the internals it binds the `IMeterFactory` to `DefaultMeterFactory`; While `IMeterFactory` is a public interface, the `DefaultMeterFactory` implementation of this interface is marked as `internal`.

The assumption that everybody uses the `IServiceCollection` is a bit strong, there are plenty of older projects that use other DI solutions (for example we unfortunately still use Ninject). Projects that do not use the dotnet DI solution can not use `AddMetrics` obviously, but due to the fact that `DefaultMeterFactory` is marked as `internal` we also can not implement our own extension of `AddMetrics` for Ninject without copying the `DefaultMeterFactory` implemetnation as well.

I think it would be better to have `DefaultMeterFactory` marked as `public`, so that older projects using other DI solutions could create their own "AddMetrics" without having to copy-paste code from the dotnet runtime

**Comment by steveharter** [comment]
I see why exposing `DefaultMeterFactory` may be useful, but to make this a public class requires more demand. Also, it's only [~100 LOC](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Diagnostics/src/Metrics/DefaultMeterFactory.cs).

Closing; we can re-evaluate if there's more demand here. Thanks.
