### ISSUE TITLE
net 8.0 cannot compile nativeAOT executable for macOS x64.

### ISSUE THREAD

**Issue by fenginsc** [dotnet/runtime#94973]
### Description

Seeing `https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/?tabs=net8plus%2CmacOS#publish-native-aot-using-the-cli` 
here it says NET 8.0 now supports x64 nativeAOT compilation for macOS, I downloaded the latest .net 8.0 SDK and tried to compile the nativeAOT executable using macOS 13, typing `dotnet publish -a x64 -c Release -p:PublishAot=true` in the terminal, but got an error:
```
MSBuild version 17.8.3+195e7f5a3 for .NET
  Determining projects to restore...
Error: /xxxxx/sdk/8.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1204: Ahead-of-time compilation is not supported on the current platform 'osx-x64'.
Error: Process completed with exit code 1.
```
What is this? Is it a bug or is there something wrong with my compilation command?

### Reproduction Steps

Build the simplest C# Hello World program and then compile the nativeAOT executable on macOS using the above commands

### Expected behavior

Successful compilation

### Actual behavior

Compilation fails because osx-x64 is not supported.

### Regression?

not have

### Known Workarounds

not have

### Configuration

Latest version of .net 8.0.100 SDK, system is macOS 13.6 Ventura x64

**Comment by MichalPetryka** [comment]
Does it work if you use `-r osx-x64` instead of `-a x64`?

**Comment by jkotas** [comment]
You project needs to target .NET 8. Try changing TargetFramework in your .csproj file to `<TargetFramework>net8.0</TargetFramework>`.

**Comment by fenginsc** [comment]
> Does your app target .Net 8? Does it work if you use `-r osx-x64` instead of `-a x64`?

Using `-r osx-x64` still gives the same error, I think maybe I didn't adjust the target to .net 8, I'll try again, thanks!

**Comment by fenginsc** [comment]
@jkotas @MichalPetryka Thanks a lot, I checked my target framework version was net7.0 and when I switched to net8.0 it works fine now, thanks again!
