### ISSUE TITLE
Unhandled error: System.IO.FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

### ISSUE THREAD

**Issue by RedhwanGhailan** [dotnet/runtime#95000]
### Description

Description
I have a .net framework app using 4.7.1 - It is a Class Library.

I am trying to connect to Blob storage using the connection string using this code

            var blobServiceClient = new BlobServiceClient(_settings.ConnectionString);
            var containerClient = blobServiceClient.GetBlobContainerClient(_settings.ContainerName);
            var blobClient = containerClient.GetBlobClient(blobName);

I get this error:
Unhandled error: System.IO.FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

App.config :
      <dependentAssembly>
        <assemblyIdentity name="System.Diagnostics.DiagnosticSource" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.1" newVersion="6.0.0.1" />
      </dependentAssembly>

Package file
  <package id="System.Diagnostics.DiagnosticSource" version="6.0.1" targetFramework="net471" />

Any clue why the error above?

### Reproduction Steps

Try to use Azure.core to upload a file to an SFTP:
            var blobServiceClient = new BlobServiceClient(_settings.ConnectionString);
            var containerClient = blobServiceClient.GetBlobContainerClient(_settings.ContainerName);
            var blobClient = containerClient.GetBlobClient(blobName);

### Expected behavior

To connect to Axure blob storage using ConnectionString:
            var blobServiceClient = new BlobServiceClient(_settings.ConnectionString);

### Actual behavior

Error when trying to get clinet 
            var blobServiceClient = new BlobServiceClient(_settings.ConnectionString);

**Comment by tommcdon** [comment]
@RedhwanGhailan thanks for posting the issue.  I suggest adding a direct package reference to System.Diagnostics.DiagnosticSource to the .NET Framework 4.7.1 project and ensure that the class library referencing System.Diagnostics.DiagnosticSource is Netstandard 2.0 per https://learn.microsoft.com/dotnet/standard/net-standard?tabs=net-standard-2-0.
