### ISSUE TITLE
Bug in DateTime.TryFormat method on dotnet 8

### ISSUE THREAD

**Issue by leandromoh** [dotnet/runtime#95012]
### Description

as usual I was updating my library [RecordParser](https://github.com/leandromoh/RecordParser) to the new version of dotnet. but this time, different of the other upgrades I did in the past (dotnet 5, 6 and 7) some unit tests failed simply by change the framework version. 

after some analysis I could find the bug and reproduce it: `DateTime.TryFormat` is behaving differently.
basically the method check if there is enought space in the `Span<char> destination` parameter and...
- if yes, it writes the value in `destination` and sets the `out int charsWritten` parameter.
- if no, it does not write anything and returns zero in `out int charsWritten`. 

this is how the method always have behaved and the same happens for `TryFormat` method of other primitive types.

now in dotnet 8, I found a situation where if the buffer is not large enough for the value, the method returns `false` and sets zero in `charsWritten` (correct) but writes something in the destination buffer (not correct). 

I searched for any documented breaking change but could not find.

I was able to caught the bug because in some unit tests of my library I am checking that when `TryFormat` returns `false` and `zero` the buffer must be unwritten.

### Reproduction Steps

After some tries, I was able to reproduce the bug outside my personal project and could reproduce it on dotnetfiddle.

```csharp
using System;

Span<char> destination = stackalloc char[50];

var instance = (Name: "foo bar baz", Birthday: new DateTime(2020, 05, 23));
var success = instance.Item2.TryFormat( destination.Slice(16, 9), out var charsWritten, "yyyy.MM.dd".AsSpan(), null);

Console.WriteLine(success + " " + charsWritten);
Console.WriteLine(destination.ToString());
```

### Expected behavior

in versions 5, 6 and 7 the output is 

```csharp
False 0

```

[dotnetfiddle](https://dotnetfiddle.net/fwanjH)

### Actual behavior

in versions 8 the output is 

```csharp
False 0
2020.05.
```

[dotnetfiddle](https://dotnetfiddle.net/HXfPwi)

### Regression?

yes, the behaviour is correct in all previous versions of framework I tested (version 5, 6 and 7).

### Known Workarounds

none. the value in the buffer is overwritten.

### Configuration

- dotnet 8.0.100
- the problem happened on Windows 10 Pro (My PC) and on Unix (dotnetfiddle)
- My PC is x64

**Comment by stephentoub** [comment]
>  but writes something in the destination buffer (not correct)

Thank you for the report, but this has always been possible with TryFormat methods in general, and in general with anything that writes into a span. Typically these methods, especially ones that are composed of multiple pieces, will write into the destination as they're going, and it's only when they run out of room that they know they need to return false; at that point, they've already written into the destination. The only way to avoid that would be a temporary buffer.  The fact that DateTime.TryFormat didn't used to was an (inefficient) implementation detail.

**Comment by leandromoh** [comment]
I agree with you that since the return was `false` it should not be a big troubble, but Isn't it inconsistent to returns zero in `charsWritten` when in fact 8 chars were written (`2020.05.`) ?

In the documented scenario, the correct behaviour should return `false` since the write failed, but returns the correct number of chars written in `charsWritten`

**Comment by stephentoub** [comment]
> but Isn't it inconsistent to returns zero in charsWritten when in fact 8 chars were written (2020.05.) ?

charsWritten is really how many _usable_ characters were written; the method is saying none of them are usable.

**Comment by leandromoh** [comment]
the `usable` word makes a lot of difference here.. but is not in the documentation..

https://learn.microsoft.com/en-us/dotnet/api/system.datetime.tryformat?view=net-7.0
![image](https://github.com/dotnet/runtime/assets/11452028/39a7a31a-188a-4dd0-b447-4df3bb65b292)

better to add it there.

**Comment by tarekgh** [comment]
@leandromoh feel free to submit a PR suggesting any change in the doc.
