### ISSUE TITLE
The input string 'System.ReadOnlySpan<Byte>[2]' was not in a correct format.

### ISSUE THREAD

**Issue by xparadoxical** [dotnet/runtime#95044]
### Description

`System.Number.ThrowFormatException(ReadOnlySpan<>)` calls object.ToString on the parameter, which results in the thrown exception containing the type's display name instead of the value of the span. https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Number.Parsing.cs,1391
I think it should convert the value of the span to UTF-16 and use that in message formatting.

### Reproduction Steps

dotnet new console -f net8.0
echo _ = int.Parse(stackalloc byte[2]); > Program.cs
dotnet run

### Expected behavior

```
Unhandled exception. System.FormatException: The input string '
```

(to match `int.Parse("\0\0")` behavior, which I'm not a fan of)

### Actual behavior

```
Unhandled exception. System.FormatException: The input string 'System.ReadOnlySpan<Byte>[2]' was not in a correct format.
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at System.Int32.Parse(ReadOnlySpan`1 utf8Text, NumberStyles style, IFormatProvider provider)
   at Program.<Main>$(String[] args) in path\Program.cs:line 1
```

### Configuration

net8.0

**Comment by tannergooding** [comment]
CC. @GrabYourPitchforks, @stephentoub 

Any concerns with doing this? What should the behavior be if the ROSpan<byte> contains an invalid UTF-8 string such that conversion cannot occur?

**Comment by stephentoub** [comment]
Seems reasonable. If it's not valid UTF8, we should probably just have it say "The input string was not in a correct format", i.e. leave out the argument.  Or alternatively have it say "The input string contained invalid UTF8", since that's a factor in it not successfully parsing.
