### ISSUE TITLE
`Math.Sin` difference between FW and 8

### ISSUE THREAD

**Issue by karakasa** [dotnet/runtime#95059]
### Description

I was porting an [algorithm](https://gamma.cs.unc.edu/RVO2/downloads/cs-2.0/rvo2-cs-2.0.1.zip) from .NET FW to 8, but found the output is very different. For the example `Circle` program, .NET FW takes **708.75** steps to coverage while .NET 8 takes **1024** steps. Random is not used in the `Circle` example.

I further looked into steps of the code and discovered some numerical calculation difference. I'm unsure if there're more.

### Reproduction Steps

For example, I found one:

[sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoIgBgAIiyA6AJXwwEsBbGZgYQjcADpwA2MKAGVJAN05gYAZwDc1IgGZGJev3oBvavWPaShqicv1ZAQyj0AZvQC8um2LA4xNjDAAUZCQArACUahZWxkwAnH4AJABE+g4gAGIatAC+CWFGkdZ29MAAnr5KLvQAQpwYgniykr5QzADiMBiVpcp+DrkRkQ7QMDZgABZ+tvbA9Jx4RV1KIXmR5vlWdUoQEswA6lA1/on6wJn0OeFrmcuW11f99NcA2gCy7aMQACYAkiJifq8Yd7fX4AeWEXAgeCUzAAchAvngxLNZgBzEIAXWuwn2tl8jDISEcYggPjcHi8Pn8swwMyW91W+SIAHZ6CRaLRmLQnAAqeg9Yk+ELPHyjZhSWZ+Tj0XkkTk8+jCwHMAAKX3oAHpWUEOVy+pY7pkgA)

```
using System;
using System.Runtime.CompilerServices;
public class C {
    public static void Main(){
        var f = Calculate(125);
        var bytes = BitConverter.GetBytes(f);
        foreach(var b in bytes)
        {
            Console.Write($"{b} ");
        }
       
    }
    
    [MethodImpl(MethodImplOptions.NoInlining)]
    private static float Calculate(int i)
    {
        return 200.0f * (float)Math.Sin(i * 2.0f * Math.PI / 250.0f);
    }
}
```

If you want the complete test, plz:
* Download the algorithm solution above
* Compile it (originally it's in .NET FW)
* Execute `Circle > circle.txt` and the last line writes `708.75`.
* Migrate the code to .NET 8 by rewriting `csproj` files (and exclude the `Blocks.cs` file)
* Compile it again and execute the same command, and the last line writes `1024`.

### Expected behavior

.NET FW and 8 have same outputs.

### Actual behavior

For the minimal example, .NET 8 prints

```
0.000000000000024492936839945120
222 156 220 40 
```

.NET FW prints

```
0.000000000000024492130000000000
0 155 220 40 
```

### Regression?

Maybe. .NET FW and .NET 8 prints different result. I don't know which is "more" correct.

### Configuration

.NET: 8.0.100 and FW 4.8
OS: Win10 1809
archi: x64
Both codes are tested in `Debug` mode.

### Other information

In the minimal example, `Math.Sin` calculates differently for the same input.

I understand the result should be `0` and the overall result can be drastically different due to acuumulated errors. I'm just wondering if the breaking change is anticipated or documented anywhere.

Codegen of .NET 8
```
C.Calculate(Int32)
    L0000: sub rsp, 0x28
    L0004: vzeroupper
    L0007: vxorps xmm0, xmm0, xmm0
    L000b: vcvtsi2ss xmm0, xmm0, ecx
    L000f: vaddss xmm0, xmm0, xmm0
    L0013: vcvtss2sd xmm0, xmm0, xmm0
    L0017: vmulsd xmm0, xmm0, [0x7ff9c3d602b8]
    L001f: vdivsd xmm0, xmm0, [0x7ff9c3d602c0]
    L0027: call 0x00007ffa15405370
    L002c: vcvtsd2ss xmm0, xmm0, xmm0
    L0030: vmulss xmm0, xmm0, [0x7ff9c3d602c8]
    L0038: add rsp, 0x28
    L003c: ret
```

Codegen of .NET FW
```
C.Calculate(Int32)
    L0000: sub rsp, 0x28
    L0004: vzeroupper
    L0007: vxorps xmm0, xmm0, xmm0
    L000c: vcvtsi2ss xmm0, xmm0, ecx
    L0011: vmulss xmm0, xmm0, [rip+0x36]
    L001a: vcvtss2sd xmm0, xmm0, xmm0
    L001f: vmulsd xmm0, xmm0, [rip+0x30]
    L0028: vdivsd xmm0, xmm0, qword [rip+0x2f]
    L0031: call System.Math.Sin(Double)
    L0036: vcvtsd2ss xmm0, xmm0, xmm0
    L003b: vmulss xmm0, xmm0, [rip+0x24]
    L0044: add rsp, 0x28
    L0048: ret
```

**Comment by hez2010** [comment]
.NET Framework is not [IEEE-compliant](https://standards.ieee.org/standard/754-2019.html) in floating-point number parsing and formatting, while .NET 8 is.

This change was introduced since .NET Core 3.0, you may see the breaking change mentioned here: https://learn.microsoft.com/en-us/dotnet/core/compatibility/corefx#floating-point-formatting-and-parsing-behavior-changed

**Comment by karakasa** [comment]
> .NET Framework is not [IEEE-compliant](https://standards.ieee.org/standard/754-2019.html) in floating-point number parsing and formatting, while .NET 8 is.

I don't believe parsing/formatting is involved. In the minimal example, binary representations of the two floats are different.

**Comment by karakasa** [comment]
Found an old PR in dotnet/coreclr.
https://github.com/dotnet/coreclr/pull/4847

**Comment by hez2010** [comment]
Also note that the behavior of .NET 8 is matching the behavior of C++: https://godbolt.org/z/M1dvqocPa
