### ISSUE TITLE
why we need dotnet.wasm?

### ISSUE THREAD

**Issue by sajjadarashhh** [dotnet/runtime#95076]
why we need dotnet.wasm?
while browser that have owned runtime and we can execute wasm codes in that
if we compile c# modules directly to webassembly modules then why we need dotnet.wasm?

_Originally posted by @sajjadarashhh in https://github.com/dotnet/runtime/discussions/94636_

**Comment by sajjadarashhh** [comment]
there's any original roadmap from dotnet contribution group for .net NativeAOT llvm in runtime lab to add that to .net runtime?

**Comment by pavelsavara** [comment]
This was already answered in https://github.com/dotnet/runtime/discussions/94636#discussioncomment-7543530
