### ISSUE TITLE
.NET 8 `QuicConnection` AuthenticationException: RemoteCertificateNameMismatch

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/runtime#95072]
### Description

In .NET Interactive environment (.NET 7.0.14), `QuicConnection.ConnectAsync` successful, but in .NET 8 console app, it fails with `System.Security.Authentication.AuthenticationException` due to `RemoteCertificateNameMismatch`.

### .NET 7 interactive notebook successful
![image](https://github.com/dotnet/runtime/assets/4510984/3f8cea68-5849-4b2a-9bb9-a607ec575c14)

### .NET 8 console app exception
![image](https://github.com/dotnet/runtime/assets/4510984/8d58dca1-92eb-4d45-b775-f221da0524d6)

 

### Reproduction Steps

Just create a new .NET 8 console app and run the following code:

```c#
using System.Net.Quic;
using System.Net.Security;
using System.Net;

using var cts = new CancellationTokenSource(10_000);

await using var connection = await QuicConnection.ConnectAsync(new QuicClientConnectionOptions {
    RemoteEndPoint = new DnsEndPoint("unfiltered.adguard-dns.com", 853),
    DefaultStreamErrorCode = 0,
    DefaultCloseErrorCode = 0,
    ClientAuthenticationOptions = new SslClientAuthenticationOptions {
        ApplicationProtocols = [new SslApplicationProtocol("doq")]
    }
}, cts.Token);

Console.WriteLine("Connected.");
```

### Expected behavior

Connect to the `unfiltered.adguard-dns.com` successful.

### Actual behavior

Got exception `AuthenticationException` due to `RemoteCertificateNameMismatch`.

### Regression?

Works well in `VSCode Polyglot Notebooks v1.0.4562010` with .NET 7 (7.0.14) environment.

### Configuration

.NET 8
Win11 22H2 22621.2715 
x64

**Comment by wfurt** [comment]
Can you hook certificate validation callback and dump the chain status & error?

**Comment by GF-Huang** [comment]
> Can you hook certificate validation callback and dump the chain status & error?

It's empty.

![image](https://github.com/dotnet/runtime/assets/4510984/1b01576f-5abf-44f0-bb27-85068d20db78)

**Comment by rzikm** [comment]
That looks very wrong. I will have a look

**Comment by rzikm** [comment]
Right, so this is actually not a regression. In 7.0 we did not validate peer certificate against against the expected host name. so the following should work

```cs
using System.Net.Quic;
using System.Net.Security;
using System.Net;

using var cts = new CancellationTokenSource(10_000);

await using var connection = await QuicConnection.ConnectAsync(new QuicClientConnectionOptions {
    RemoteEndPoint = new DnsEndPoint("unfiltered.adguard-dns.com", 853),
    DefaultStreamErrorCode = 0,
    DefaultCloseErrorCode = 0,
    ClientAuthenticationOptions = new SslClientAuthenticationOptions {
        ApplicationProtocols = [new SslApplicationProtocol("doq")],
        TargetHost = "unfiltered.adguard-dns.com" // <-- add this
    }
}, cts.Token);

Console.WriteLine("Connected.");
```

**Comment by GF-Huang** [comment]
> Let me know if this fix works for you.

After add `TargetHost = "unfiltered.adguard-dns.com"`, it works as excepted. Thank you!

**Comment by rzikm** [comment]
It is something that we can possibly add, but then there would be a behavior difference with SslStream, which does not (and cannot) do any such detection.

**Comment by wfurt** [comment]
I think it would be OK to take it .... even if `SslStream` does not. Leaving it empty is really not that useful IMHO.
If somebody really wants to disable SNI that can probably use `String.Empty` but that seems like corner case.

**Comment by ManickaP** [comment]
Triage: re-opening for 9.0, seems easy to fix and seems fair as we do the same for SNI in client hello, we should just use the same string for validation as well.
