### ISSUE TITLE
[mono][wasm] Add interpreter support for calls to UnmanagedCallersOnly EntryPoint without managed delegate reference

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#95087]
https://github.com/dotnet/runtime/pull/94615#issuecomment-1813789511

#94615 added EntryPoint support to UCO on wasm (it was missing before)
```csharp
 
        [UnmanagedCallersOnly(EntryPoint = "display_meaning")]
        public static void DisplayMeaningExport(int meaning)
        {
            Console.WriteLine($"The meaning of life is {meaning}");
        }
```
but there is currently an issue with when invoking the export from unmanaged when there is no managed delegate pointing to it and something akin to the following workaround is required:

```csharp
   Intptr workaround = (IntPtr)(delegate* unmanaged<int,void>)&display_meaning;  // needs to be in method loaded by interp prior to unmanaged call 
```

This is because `get_native_to_interp` must be called before attempting to invoke the unmanaged entry point or the call will fail.  Without the call `wasm_native_to_interp_ftndescs` is never initialized.  For the workaround to work the delegate * does not need to be reached/reachable, the interpreter simply needs to resolve the method prior to calling it from unmanaged.

**Comment by lewing** [comment]
@maraf this is essentially the same issue you are hitting in with the JSExport for nativeAOT changes

**Comment by lewing** [comment]
cc @vargaz @BrzVlad

**Comment by lewing** [comment]
@steveisok @vitek-karas this is blocking wasi work

**Comment by vargaz** [comment]
The generator probably needs to generate some extra code to lookup the MonoMethod*, and call something like ```mono_jit_compile_method ()``` on it to have the interpreter initialize the pointers.

**Comment by vargaz** [comment]
Something like:
```
MonoMethod *
mono_marshal_get_managed_wrapper (MonoMethod *method, MonoClass *delegate_klass, MonoGCHandle target_handle, MonoError *error);

	MonoError error;
	mono_error_init (&error);
	MonoMethod* m = lookup_dotnet_method("Wasi.Console.Sample", "", "Test", "DisplayMeaningExport", 1);
	MonoMethod *w = mono_marshal_get_managed_wrapper (m, NULL, 0, &error);
	printf ("X: %p\n", mono_compile_method (w));
```

Will force the pointers to be initialized. This can be done either on startup at the end of ```mono_wasm_load_runtime ()```, or on demand in the generated pinvoke func, i.e.
```
void display_meaning (int arg0) {
   if (!wasm_native_to_interp_ftndescs [2].func) <INIT>
  ((WasmInterpEntrySig_2)wasm_native_to_interp_ftndescs [2].func) ((int*)&arg0, wasm_native_to_interp_ftndescs [2].arg);
}
```
```

**Comment by knutwannheden** [comment]
@lewing Do you have any more details (or even better an example I can look at) on the mentioned workaround? I tried adding some code like that to the `Main` method, but that didn't really help.

**Comment by maraf** [comment]
> Do you have any more details (or even better an example I can look at) on the mentioned workaround? I tried adding some code like that to the `Main` method, but that didn't really help.

@knutwannheden It's something that can't be done in user. I needs to happen in generate C code that works as a trampoline to call managed code

**Comment by knutwannheden** [comment]
Excellent news! Looking forward to the next release containing this fix ❤️
