### ISSUE TITLE
[8.0] [OSX] Long Running Test: System.Security.Cryptography.Rsa.Tests.RSAKeyFileTests.ReadEncryptedRsa16384

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#95094]
### Error Blob

```json
{
  "ErrorMessage": "[Long Running Test] 'System.Security.Cryptography.Rsa.Tests.RSAKeyFileTests.ReadEncryptedRsa16384'",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Reproduction Steps

- PR: https://github.com/dotnet/runtime/pull/94918
- Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=477375&view=results
- Queue: `Libraries Test Run checked coreclr osx x64 Debug`
- Job: https://dev.azure.com/dnceng-public/public/_build/results?buildId=477375&view=logs&j=69b60b53-a417-56e9-d4e0-3a40344d5e67&t=3caa942a-fc58-5e1f-0b98-b7d7725d89c0&l=55
- Log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-94918-merge-ec27bc4a95764e0488/System.Security.Cryptography.OpenSsl.Tests/1/console.c1b58157.log?helixlogtype=result
- Output:
```
   System.Security.Cryptography.OpenSsl.Tests: [Long Running Test] 'System.Security.Cryptography.Rsa.Tests.RSAKeyFileTests.ReadEncryptedRsa16384', Elapsed: 00:02:00
['System.Security.Cryptography.OpenSsl.Tests' END OF WORK ITEM LOG: Command timed out, and was killed]
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=477375
**Error message validated:** `[Long Running Test] 'System.Security.Cryptography.Rsa.Tests.RSAKeyFileTests.ReadEncryptedRsa16384'`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 11/21/2023 11:55:18 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[529634](https://dev.azure.com/dnceng-public/public/_build/results?buildId=529634)|dotnet/runtime|[System.Security.Cryptography.OpenSsl.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=529634&view=ms.vss-test-web.build-test-results-tab&runId=12485766&resultId=203186)||
|[522376](https://dev.azure.com/dnceng-public/public/_build/results?buildId=522376)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.CertificateCreation.CertificateRequestUsageTests.SimpleSelfSign_RSA](https://dev.azure.com/dnceng-public/public/_build/results?buildId=522376&view=ms.vss-test-web.build-test-results-tab&runId=12283192&resultId=206747)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|2|

**Comment by vcsjones** [comment]
We may want to back port https://github.com/dotnet/runtime/pull/95284 to other releases, seeing as it is a test-only change. What do you think @bartonjs?

**Comment by bartonjs** [comment]
Absent an issue like this one, I'd think it was unnecessary.  Given that the issue exists, seems reasonable.

**Comment by vcsjones** [comment]
This was fixed by https://github.com/dotnet/runtime/pull/95310.
