### ISSUE TITLE
Backport #72274 Avoid adding an HttpClient.Timeout message to ConnectTimeout exceptions to 6.0 branch

### ISSUE THREAD

**Issue by konjac** [dotnet/runtime#95097]
Hi @MihaZupan,

#72274 is only in 7.0+ branches. Could we consider backport it to 6.0?

Thanks

**Comment by rzikm** [comment]
Porting the fix to .NET 6 needs a business justification. Please coordinate with @karelz

**Comment by karelz** [comment]
@konjac why do you need the change in 6.0? How much is it hurting your app? How many of your clients does it impact?
Did you consider upgrading to 7.0 or 8.0 if you need LTS?
