### ISSUE TITLE
Add a local live live leg in PR validation to protect local development.

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#951]
Since CI and local live live have different behaviors as on CI we take some shortcuts, it is very simple to introduce a break in local development. We should add 1 leg that does build.cmd/sh with a simple plaform matrix of something like:

- Windows_x86_Release
- Unix_x64_Debug
- macOS_x64_Release

cc: @dotnet/runtime-infrastructure

**Comment by trylek** [comment]
How do we deal with the CoreCLR checked mode? Should we cater for that too?

**Comment by safern** [comment]
> How do we deal with the CoreCLR checked mode? Should we cater for that too?

I don't think so. I think this is just a matter of protecting the local development dependency flow as we've seen some issues since this was enabled on Friday because the behavior on CI and local is different and the paths can change. So we should just protect from breaking the local development. Configurations shouldn't change this as the paths are calculated based on the configuration property we flow and also, checked configuration is only known by coreclr.

**Comment by trylek** [comment]
Hmm, I was under the impression that, as the CoreCLR repo supports the three configurations (build / checked / release), the "combined build" should also support the same three configurations - build, checked, release - and either just collapse them for CoreFX that just supports two configurations (Debug / Release) or optionally allow specifying an explicit configuration for CoreFX build. I can easily imagine that some of these configurations might not make sense for the installer - e.g. I don't know if Davis can sign debug bits - but that should be just transparently filtered out in the scripts I believe. Otherwise a CoreCLR developer wanting to use the checked build (I believe @janvorli  often does that and so do I) would have to use some very hacky local workflow for pulling off successful builds - which is, after all, what JanV is currently hitting.

**Comment by trylek** [comment]
In fact, I would be inclined to suggest we run all 6 combinations building the product and maybe a small set of tests, perhaps without actually running them. By six combinations I mean the Cartesian product of the three CoreCLR configurations (build - checked - release) times the two CoreFX configurations (Build - Release) we can probably distribute among the three OS'es (for now I'd be inclined to run three on OSX, two on Linux and one on Windows according to their performance).

**Comment by jaredpar** [comment]
The goal here is to add a reasonable level of confidence that changes to the repository don't break the local developer work flow. For most repositories this only needs a small sanity check because the build paths between local and CI are virtually the same. The runtime repository diverges quite a bit more because of the number of configurations that we need to test and the improvements we can get in throughput from doing so. 

> In fact, I would be inclined to suggest we run all 6 combinations building the product and maybe a small set of tests, perhaps without actually running them

I think it's possible that we end up here but I'd prefer if we start smaller. Say just roughly the three jobs that @safern originally listed. Then if we find that isn't suitably protecting developer workflow when we expand to ensure that it is.

**Comment by trylek** [comment]
Sounds good to me.

**Comment by ViktorHofer** [comment]
> Since CI and local live live have different behaviors as on CI we take some shortcuts

Why not instead build the same way on CI as locally? I understand that testing isn't that trivial and needs to have the artifacts output available but I was under the assumption that just building the repo with `build.cmd/sh` under a single pipeline should be sufficient for at least the Build step.

**Comment by safern** [comment]
Because we want to parallelize the build in order to make CI faster. Running build.cmd/sh doesn’t allow us building multiple partitions in parallel.

**Comment by ViktorHofer** [comment]
How much do we gain by doing that? I would instead focus on improving the local build time by parallizing where possible.

**Comment by trylek** [comment]
I think that one fundamental difference is that, in the CI, we often run variations for multiple platforms and I'm not sure if we always want to have CoreCLR and CoreFX correspond to each other 1:1 so we basically need to build a cross-machine graph for the build - for instance, I would expect that CoreCLR checked and release builds in the PR run should collapse to the same CoreFX Release build.

I actually don't have a strong opinion on that and I agree that unifying local and lab build as much as possible is generally desirable, it just seems to me that dust hasn't yet settled down on the new repo and I'm only just finishing live-live changes to the remaining CoreCLR pipelines - I doubt that spending two more weeks refactoring all of them to use Jeremy's global build logic is not the most efficient use of our time. I'm fully open to discussing any optimizations and cleanups once we have both local and lab build (including signing and installer tasks) in good shape.

**Comment by safern** [comment]
I think first we need to get the single pipeline working and then see if it is worth doing the optimizations or not. 

however, with regards to the optimizations, whenever we get a S.P.CoreLib and if we make our tests assemblies not depend on runtime assemblies, we could gain a LOT, because once we have the ref assembly for S.P.CoreLib, and we could build libraries ref assemblies in parallel, and then build tests at the same time as product. We might be able to save some time, but we would have to measure how much, machine provisioning, checkout and restore costs us at the end.

But I think we shouldn't change direction now until we have the single pipeline and official build.

**Comment by ViktorHofer** [comment]
> I think that one fundamental difference is that, in the CI, we often run variations for multiple platforms and I'm not sure if we always want to have CoreCLR and CoreFX correspond to each other 1:1

Building coreclr and libraries in the same build invocation shouldn't necessarily mean that they build against the same _configuration, platform or OS_. I can already do that with the [switches](https://github.com/dotnet/runtime/blob/master/eng/liveBuilds.targets#L4-L7) that @jkoritzinsky introduced.

> I think that spending two more weeks refactoring all of them to use Jeremy's global build logic is not the most efficient use of our time. I'm fully open to discussing any optimizations and cleanups once we have both local and lab build (including signing and installer tasks) in good shape.

Definitely, I was not proposing to do this right now as official builds, live-live everywhere and a single pipeline are much more important. To use our resources efficiently, I want to make sure that we are aligned and have the same vision regarding our builds and pipelines. We just discussed this in the stand-up and I will start with writing up a vision doc on which we can collaborate.

> I think first we need to get the single pipeline working and then see if it is worth doing the optimizations or not.

I fully agree with getting the single pipeline done first as a precursor.

> however, with regards to the optimizations, whenever we get a S.P.CoreLib and if we make our tests assemblies not depend on runtime assemblies, we could gain a LOT, because once we have the ref assembly for S.P.CoreLib, and we could build libraries ref assemblies in parallel, and then build tests at the same time as product. We might be able to save some time, but we would have to measure how much, machine provisioning, checkout and restore costs us at the end.

Absolutely, I hope that we can save up to 10 minutes by sequencing our subsets efficiently.
