### ISSUE TITLE
Optimize out write barriers for fields in ref-like structs

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#9512]
From https://github.com/dotnet/coreclr/pull/15745#issuecomment-355481958 :

> > Hmm, I wonder if there are sufficient guarantees that by ref like types only live on the stack for the JIT to be able to eliminate GC write barriers when writing to fields of such types.

> Yes, there are. It would be nice optimization to have.

cc @mikedn

category:cq
theme:barriers
skill-level:expert
cost:small

**Comment by markples** [comment]
#86820, #89064, and #89116 are related (for struct copies)
