### ISSUE TITLE
[mono] ICU data file is not part of the bundle in library mode

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#95124]
When using library mode `NativeLib=shared|static` with bundling turned on, the icu data file is not part of the bundle. This requires you to carry the file separately, which is something we don't want to do. 

Since custom ICU is wasm specific, the data file should be added in their respective targets. At the end of the day, it should end up in:

https://github.com/dotnet/runtime/blob/ebf881ed4d954b007c3f53a443e201d418457764/src/mono/msbuild/common/LibraryBuilder.targets#L56-L60

**Comment by JCash** [comment]
I'm also pinging here, as I'm currently hitting this case as well.

> This requires you to carry the file separately

Are there any instructions on how to achieve this?

**Comment by ivanpovazan** [comment]
@JCash https://gist.github.com/ivanpovazan/0f0c1c588895bb399ee5eacac552cce3 you might find this helpful (it is an unofficial set of notes for .net8/.net9 iOS library mode with NativeAOT)

**Comment by ivanpovazan** [comment]
@steveisok since we now use HybridGlobalization on iOS by default and the system ICU data file, should this be wasm library mode issue instead ?

**Comment by steveisok** [comment]
> @steveisok since we now use HybridGlobalization on iOS by default and the system ICU data file, should this be wasm library mode issue instead ?
> 
> 

Yeah, that would be correct.

**Comment by steveisok** [comment]
> @lewing can someone from your team maybe pick this up? 

Actually, this is specific to ios. Wasm has their own way. Should be ok to close

**Comment by ivanpovazan** [comment]
Thanks for the confirmation! Closing as not planned.
