### ISSUE TITLE
[Regression] Segmentation fault during 'dotnet build' via qemu

### ISSUE THREAD

**Issue by mxschmitt** [dotnet/runtime#95120]
### Description

When running 'dotnet build' in a `linux/arm64' Docker container on a 'linux/amd64' host via qemu I get a Segmentation fault.

This did not occur in net6.0/net7.0 and started happening in net8.0.

### Reproduction Steps

Minimal reproduction steps are here: https://github.com/mxschmitt/dotnet-build-segfault

### Expected behavior

Works/does not crash.

### Actual behavior

```
Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
Segmentation fault (core dumped)

Core was generated by `dotnet build'.
#0  0x00000055024598d8 in ?? ()
   from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
```

### Regression?

Yes:

Good: `./repro.sh 6.0`
Good: `./repro.sh 7.0`
Bad: `./repro.sh 8.0`

Will try to bisect it more, maybe even try to compile `dotnet/core` on my own to get a coredump with symbols.

**Comment by vcsjones** [comment]
> `linux/arm64' Docker container on a 'linux/amd64' host via qemu I get a Segmentation fault.

QEMU emulation is [not support for .NET 8](https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md#qemu).

This was true for .NET 7 [as well](https://github.com/dotnet/core/blob/main/release-notes/7.0/supported-os.md#qemu). If it worked in .NET 7 or 6 then it was by chance, not by intentionally supporting it.

**Comment by mxschmitt** [comment]
Thanks for the quick response, closing by that!
