### ISSUE TITLE
[6.0] An attempt was made to transition a task to a final state when it had already completed.

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#95158]
### Error Blob

```json
{
  "ErrorMessage": "An attempt was made to transition a task to a final state when it had already completed.",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Reproduction Steps

- PR: https://github.com/dotnet/runtime/pull/95150
- Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=477586
- Queue: `Libraries Test Run release coreclr Linux x64 Release`
- Job: https://dev.azure.com/dnceng-public/public/_build/results?buildId=477586&view=logs&j=b9b7de4d-2126-5581-6453-1576f9aaac5f&t=db048d48-40e8-5399-9b14-d587763f33ff&l=2526
- Log file: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-heads-release-60-staging-9e11600b7c9a443cb4/System.Net.Http.Functional.Tests/1/console.c16efe14.log?helixlogtype=result
- Output:
```    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http3_Mock.EchoServerStreaming_DifferentMessageSize_Success(messageSize: 100) [FAIL]
      System.InvalidOperationException : An attempt was made to transition a task to a final state when it had already completed.
      Stack Trace:
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskCompletionSource.cs(91,0): at System.Threading.Tasks.TaskCompletionSource.SetException(Exception exception)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/Mock/MockConnection.cs(470,0): at System.Net.Quic.Implementations.Mock.MockConnection.StreamLimit.CloseWaiters()
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/Mock/MockConnection.cs(385,0): at System.Net.Quic.Implementations.Mock.MockConnection.Dispose(Boolean disposing)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/Mock/MockConnection.cs(336,0): at System.Net.Quic.Implementations.Mock.MockConnection.CloseAsync(Int64 errorCode, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(106,0): at System.Net.Quic.QuicConnection.CloseAsync(Int64 errorCode, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3Connection.cs(122,0): at System.Net.Http.Http3Connection.CheckForShutdown()
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3Connection.cs(97,0): at System.Net.Http.Http3Connection.Dispose()
        /_/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/List.cs(572,0): at System.Collections.Generic.List`1.ForEach(Action`1 action)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(1952,0): at System.Net.Http.HttpConnectionPool.Dispose()
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPoolManager.cs(452,0): at System.Net.Http.HttpConnectionPoolManager.Dispose()
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionHandler.cs(31,0): at System.Net.Http.HttpConnectionHandler.Dispose(Boolean disposing)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs(214,0): at System.Net.Http.DiagnosticsHandler.Dispose(Boolean disposing)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs(165,0): at System.Net.Http.RedirectHandler.Dispose(Boolean disposing)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpMessageHandler.cs(39,0): at System.Net.Http.HttpMessageHandler.Dispose()
        /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClientHandler.cs(60,0): at System.Net.Http.HttpClientHandler.Dispose(Boolean disposing)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs(702,0): at System.Net.Http.HttpClient.Dispose(Boolean disposing)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpMessageInvoker.cs(126,0): at System.Net.Http.HttpMessageInvoker.Dispose()
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs(1090,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.EchoServerStreaming_DifferentMessageSize_Success(Int32 messageSize)
        --- End of stack trace from previous location ---
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=477586
**Error message validated:** `An attempt was made to transition a task to a final state when it had already completed.`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 11/23/2023 2:27:38 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[513219](https://dev.azure.com/dnceng-public/public/_build/results?buildId=513219)|dotnet/runtime|[System.IO.FileSystem.Watcher.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=513219&view=ms.vss-test-web.build-test-results-tab&runId=12023908&resultId=104425)||
|[512008](https://dev.azure.com/dnceng-public/public/_build/results?buildId=512008)|dotnet/runtime|[System.IO.FileSystem.Watcher.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=512008&view=ms.vss-test-web.build-test-results-tab&runId=11989476&resultId=104425)||
|[510973](https://dev.azure.com/dnceng-public/public/_build/results?buildId=510973)|dotnet/runtime|[System.IO.FileSystem.Watcher.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=510973&view=ms.vss-test-web.build-test-results-tab&runId=11956700&resultId=104488)||
|[496593](https://dev.azure.com/dnceng-public/public/_build/results?buildId=496593)|dotnet/runtime|[System.IO.FileSystem.Watcher.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=496593&view=ms.vss-test-web.build-test-results-tab&runId=11542460&resultId=104487)||
|[496474](https://dev.azure.com/dnceng-public/public/_build/results?buildId=496474)|dotnet/runtime|[System.IO.FileSystem.Watcher.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=496474&view=ms.vss-test-web.build-test-results-tab&runId=11537566&resultId=104267)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|3|5|

**Comment by ManickaP** [comment]
@carlossanlop this is test bug, MockConnection is only used for tests. Are you OK with keeping it as-is or do you want us to put up a 6.0 PR to disable the test?

**Comment by carlossanlop** [comment]
If there is no intention to fix it, please disable the test so the CI in PRs goes back to green.

**Comment by ManickaP** [comment]
Test disabled in #95407, closing.

**Comment by karelz** [comment]
Test disabled only in 6.0.x branch in PR #95407.
