### ISSUE TITLE
Failed to debug coreCLR using a simple project

### ISSUE THREAD

**Issue by hawonor** [dotnet/runtime#95168]
### Description

What I want to do is debug coreCLR on Windows-11-x64. So I download the runtime sourceCode and successfully build it.
![image](https://github.com/dotnet/runtime/assets/57853329/2daabd82-e27d-417e-be48-0ac2e62a74d3)
![image](https://github.com/dotnet/runtime/assets/57853329/fcfc9de5-c0ea-47fd-bcfd-bdcce7efed2d)

My VisualStudio version = 17.8.1 (Latest one currently) as it supports dotnet 8.
I just setup INSTALL as startup and below are the project configs:
![image](https://github.com/dotnet/runtime/assets/57853329/151ae391-304d-42d8-a719-8153eb69e628)

The DebugProject.dll is from VS publish, and I only copy that single dll into D:\Codes\RT\artifacts\bin\coreclr\windows.x64.Debug\
However when I debug running, I got error as:
![image](https://github.com/dotnet/runtime/assets/57853329/7325961a-1a63-4a90-81af-2d3359be817b)

### Reproduction Steps

dotnet runtime code is the version of last day. VS version = 17.8.1

### Expected behavior

clr run normally in debug mode.

### Actual behavior

Exception generated as above.

**Comment by huoyaoyuan** [comment]
`artifacts\bin\coreclr` doesn't contain necessary bits to run a program. You need also the `libs` subset.

You can follow the [Debug Instructions](https://github.com/dotnet/runtime/blob/main/docs/workflow/debugging/coreclr/debugging-runtime.md#using-visual-studio) and set CORE_ROOT and CORE_LIBRARIES appropriately.
Note that currently the open folder instruction seems broken. CLR on Windows doesn't accept `/` from CORE_LIBRARIES on Windows now.

**Comment by hawonor** [comment]
Oh one thing I just missed is that, I couldn't find the right folder under D:\Codes\RT\artifacts\bin\runtime
![image](https://github.com/dotnet/runtime/assets/57853329/3c79cfe8-9afa-426a-8827-311459bca52f)
what I need is actually net8.0-windows-Debug-x64 as I should config it in INSTALL project Environment but I can only see "net9.0xxx"

**Comment by huoyaoyuan** [comment]
> Oh one thing I just missed is that, I couldn't find the right folder under D:\Codes\RT\artifacts\bin\runtime

The `bin\runtime` folder are built by the `libs` subset, if I'm remembering correctly.

**Comment by hawonor** [comment]
> `artifacts\bin\coreclr` doesn't contain necessary bits to run a program. You need also the `libs` subset.
> 
> You can follow the [Debug Instructions](https://github.com/dotnet/runtime/blob/main/docs/workflow/debugging/coreclr/debugging-runtime.md#using-visual-studio) and set CORE_ROOT and CORE_LIBRARIES appropriately. Note that currently the open folder instruction seems broken. CLR on Windows doesn't accept `/` from CORE_LIBRARIES on Windows now.

OK let me try it.

**Comment by hawonor** [comment]
Now I can debug it successfully! Thank you @huoyaoyuan !
