### ISSUE TITLE
[7.0] jit-dasm failed with error MSB3971

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#95161]
### Error Blob

```json
{
  "ErrorMessage": "jit-dasm failed",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Reproduction Steps

- PR: https://github.com/dotnet/runtime/pull/95149
- Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=477709
- Queue: outerloop `Formatting Linux x64`
- Step: `Run jitformat.py`
- Job: https://dev.azure.com/dnceng-public/public/_build/results?buildId=477709&view=logs&j=20a65740-9277-5bdf-9b3b-48126fa53bad&t=fccc3167-fed5-57cb-ad2e-2f07876cb0c6
- Output:
```
Microsoft (R) Build Engine version 16.7.3+2f374e28e for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /tmp/tmpdds8ib7e/jitutils/src/jit-dasm/jit-dasm.csproj (in 112 ms).
/__t/dotnet/sdk/3.1.426/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v6.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK. [/tmp/tmpdds8ib7e/jitutils/src/jit-dasm/jit-dasm.csproj]
ERROR: dotnet publish of ./src/jit-dasm failed.
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=477709
**Error message validated:** `jit-dasm failed`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 11/23/2023 2:39:53 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by jeffschwMSFT** [comment]
was not seen recently... dropping blocking-clean-ci

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0
