### ISSUE TITLE
.NET 8 Blazor Lazy loading failed with assembly naming like "requests.wasm"

### ISSUE THREAD

**Issue by hoangdovan** [dotnet/runtime#95169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

- With .Net 7, we have no problem with naming assembly for lazy loading like "requests.dll".

- But with .Net 8, we have change extension from dll to wasm and have problem with lazy loading for assembly which naming like "requests.wasm".

- The reason maybe coming from conflict with name of auto-generated files of Blazor. There is auto generated file with naming and link "http://localhost:56012/_framework/requests.wasm" which prevent lazy loading with user assembly same naming "requests.wasm".

### Expected Behavior

- There should be solution allow user assembly with naming like "requests.wasm" can be lazy loaded without any problem.
- Or at least, there should be a list of naming developer should not use for lazy loading in official document.

### Steps To Reproduce

Create a simple lazy loading example with naming "requests.wasm" for target assembly. There will be error happen.

### .NET Version

.Net 8.0.0

**Comment by javiercn** [comment]
@maraf do you have thoughts?

**Comment by maraf** [comment]
@hoangdovan Thank you for contacting us. I tried to reproduce the issue, but if I have a classlib `requests.wasm` and lazy load if on counter page, it works. I'm attaching the sample I have created [BlazorRequestsDllLazyLoad.zip](https://github.com/dotnet/runtime/files/13447559/BlazorRequestsDllLazyLoad.zip). Am I missing something?

**Comment by hoangdovan** [comment]
@maraf Thank you for your response! I already confirm again and it seems happen only when I try to upgrade from .Net 7 project to .Net 8, maybe because of caching problem. Sorry to bother you.

**Comment by fingers10** [comment]
@hoangdovan Please can you assist on what is the solution here? I'm also facing the same issue when I migrate from `.NET 7` to `.NET 8`. Here is the link to my issue [#52373](https://github.com/dotnet/aspnetcore/issues/52373)

**Comment by hoangdovan** [comment]
@fingers10 Hello, I doubt this problem because of caching problem when upgrade from .NET 7 to .NET 8. And could you try some actions like me: Change to another PC for development. Or rename of failed lazy loading modules? (Purpose of change name: to remove caching effect). Good luck!

**Comment by fingers10** [comment]
> @fingers10 Hello, I doubt this problem because of caching problem when upgrade from .NET 7 to .NET 8. And could you try some actions like me: Change to another PC for development. Or rename of failed lazy loading modules? (Purpose of change name: to remove caching effect). Good luck!

Rename worked. Thanks for your inputs and support.

**Comment by maraf** [comment]
Also, there is a write up on recomended steps when upgrading to a new major version https://github.com/dotnet/aspnetcore/issues/52022
