### ISSUE TITLE
VS default settings drops rejit requests without failing them

### ISSUE THREAD

**Issue by weltkante** [dotnet/runtime#95172]
### Description

as diagnosed in https://github.com/microsoft/CLRInstrumentationEngine/issues/572 the default VS settings of "hot reload" (enabled by default for both running with or without debugger) prevents rejit from working. It is particular surprising that running code without attaching the debugger still affects the process when being started by VS.

What happens is that the runtime accepts the rejit requests without failure but never acts on them. It would be nice if the runtime could report an error (instead of accepting and then silently dropping rejit requests) to make this problem diagnosable, ideally not just a generic error so (in the future) people can have a chance at searching for the error code.

### Reproduction Steps

Full repro scenario (using CLRIE as intermediate API) available in the linked issue and https://github.com/weltkante/RejitTest

### Expected behavior

either rejit requests are acted on or the request fails

### Actual behavior

rejit requests are accepted successfully but never acted on

### Regression?

desktop framework does not have this problem, rejit works regardless of VS settings

### Known Workarounds

disable hot reload in VS settings or launch.json (see linked issue) or run the application outside VS

### Configuration

tested under .NET 7 and 8 combined with VS 2022 (current preview)

### Other information

details of the investigation in the linked issue

**Comment by tommcdon** [comment]
@weltkante thanks for reporting the issue.  This looks like a duplicate to https://github.com/dotnet/runtime/issues/91963#issuecomment-1780114780 and so I will close this one so we have one issue tracking the request.
cc @davmason
