### ISSUE TITLE
[API Proposal]: Add a `Utf8JsonWriter.WriteRawValue(ReadOnlySequence<byte>)` overload.

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/runtime#95185]
### Background and motivation

To avoid extra allocations, it would be nice to able to write raw data in segments, but [`Utf8JsonWriter.WriteRawValue`](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter.writerawvalue) input "is expected that the input content is a single complete JSON value".

### API Proposal

```csharp
public class Utf8JsonWriter
{
    public void WriteRawValue(ReadOnlySequence<byte> utf8Json, bool skipInputValidation = false);
}
```

### API Usage

TODO

The current implementation of `Utf8JsonWriter.WriteRawValue`, inserts a comma between invocations.

**Comment by eiriktsarpalis** [comment]
I'm talking about the validation done at the writer level, i.e. the exception you're showing in your example. How could the writer validate that all the raw fragments constitute a valid JSON object when put together? It seems like this might be easier to achieve with an overload that accepts `ReadOnlySegment<byte>` since at least then the method has access to all the relevant data.

**Comment by paulomorgado** [comment]
A set of `BeginWriteRaw`. `WriteRaw` and `EndWriteRaw` segments would take care of that.

**Comment by eiriktsarpalis** [comment]
This is not a question of API design, it is a question of whether it should be possible to incorporate full-blown JSON validation across fragments. It's currently done like so for self-contained raw values:

https://github.com/dotnet/runtime/blob/ddd663d257aa2206583287309a2109e1835f1b2f/src/libraries/System.Text.Json/src/System/Text/Json/Writer/Utf8JsonWriter.WriteValues.Raw.cs#L165-L168

But it's not clear to me how it could be done without tracking an `Utf8JsonReader` ref struct across multiple write operators. It introduces the sort of complexity that would require new branching in all the hot path methods of `Utf8JsonWriter`. A `ReadOnlySequence` overload would be much easier to implement in that respect.

**Comment by paulomorgado** [comment]
> A `ReadOnlySequence` overload would be much easier to implement in that respect.

I can live with that.

**Comment by eiriktsarpalis** [comment]
> > A `ReadOnlySequence` overload would be much easier to implement in that respect.
> 
> I can live with that.

Would it be possible to update the API proposal and title to reflect the new requirement?

**Comment by paulomorgado** [comment]
Or close this with a link to the `ReadOnlySequence<byte>` proposal?

**Comment by paulomorgado** [comment]
I was referring to #67337. This quest started when I tried to write a `ReadOnlySequence<byte>` as base-64.

I don't know if it makes much sense updating this one to add support for `ReadOnlySequence<char>`.

**Comment by eiriktsarpalis** [comment]
#67337 covers streaming support for JSON strings, it is not the same as this one which covers non-streaming `ReadOnlySequence<byte>` support for raw values.

**Comment by eiriktsarpalis** [comment]
The proposal in #67337 covers segmented writing of JSON strings, which includes Base-64 encoded strings. This is unlike this proposal which proposes support for arbitrary raw JSON values.

**Comment by paulomorgado** [comment]
That was due to my misunderstanding of the API.
