### ISSUE TITLE
Make typeof(T).GUID an intrinsic on NAOT where possible (like .NET Native)

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#95184]
### Description

Especially in interop scenarios, it's rather common to use `typeof(T).GUID` to get the `Guid` associated with a given type. This currently causes a whole lot of reflection cruft to be preserved, which just on its own can exceed 300 KB of stuff, purely rooted by `typeof(T).GUID`. I was wondering whether it would be possible to make this an intrinsic, at least for NativeAOT. In theory, shouldn't the compiler always have all the necessary information to compute the GUID ahead of time? Or at least, could it not do that in all cases where the type `T` has the `[Guid]` attribute applied to it? IIRC, .NET Native has a similar optimization, where it can just bake all of these `typeof(T).GUID` uses directly into the codegen, making this pretty much free.

Could we do the same on NativeAOT?

### Configuration

.NET 8.0.100

### Regression?

No, always been this way.

### Data

This is a screenshot from @MichalStrehovsky's sizoscope tool, from a ComputeSharp sample, after removing `typeof(T).GUID`:

![image](https://github.com/dotnet/runtime/assets/10199417/780bd675-d10f-4530-8308-a099d89f1ac1)

This is from https://github.com/Sergio0694/ComputeSharp/pull/669. Just this saved a total of **304 KB** in my sample.

Here's some precompiled diffs with MSTAT info, for baseline and with that PR applied to it: [native-guid_diffs.zip](https://microsofteur-my.sharepoint.com/:u:/g/personal/sergiopedri_microsoft_com/EWLB3iHv3F9AnwtgCKc68BgBnenivvROB1RE_7jBX4x4Jw?e=O223Ki).

> [!NOTE]
> Related to #91518.

**Comment by jkotas** [comment]
> This currently causes a whole lot of reflection cruft to be preserved, which just on its own can exceed 300 KB of stuff

This cruft was pulled in by universal custom attribute reader that handles all types that can show up in custom attributes. Most of it was the type loader that is not really reflection. https://github.com/dotnet/runtime/pull/95212 removes this dependency by using a reader that just handles strings (the only case required for GuidAttribute).

> Make typeof(T).GUID an intrinsic

I do not think it makes sense to complicate JIT with this.
