### ISSUE TITLE
vsdbg quits when resuming from a breakpoint if stepping over a line that throws an exception 

### ISSUE THREAD

**Issue by dcpower0** [dotnet/runtime#95189]
### Description

I noticed some odd behavior with how vsdbg v17.0.10712.2 behaves when running after stopping on a breakpoint on a line that will throw an exception. I am using dotnet 6.0.11.

If I stop at a breakpoint on a line that will throw a null reference exception, the debugger halts as expected. If I then try to step, the program quits. If I were to run, the program executes as expected.

### Reproduction Steps
```
            try
            {
                string a = null;
                a.Trim();
            }
            catch 
            {
            
            }
```

Put a breakpoint on a.Trim();
Run the debugger on this code. Then step. Program quits.
Run the debugger on this code. Then run. Program proceeds.
Run the debugger on this code without a breakpoint. The debugger halts, if you've elected to stop on first-chance exceptions, but runs fine if you step or run after.

### Expected behavior

Program should not quit when attempting to resume from a breakpoint, on a line with a null reference exception.

### Actual behavior

Program crashes when attempting to resume from a breakpoint by stepping over a line with a null reference exception.

**Comment by tommcdon** [comment]
Hi @dcpower0, I am not able to reproduce this issue on Windows x64 configuration with .NET runtime version 6.0.25.  What OS and architecture is the app running on?  Did you see this as a regression with a specific version of the C# extension or .NET runtime update?

**Comment by dcpower0** [comment]
Oh yeah sorry I failed to mention some key details. Running on Linux arm64. C# language version 3,

I hope that helps.

**Comment by dcpower0** [comment]
Also, I am using a Yocto built version of Linux, remote debugging to a system based on imx8mm processor.

**Comment by tommcdon** [comment]
Sorry for the delay @dcpower0!  I was able to reproduce the issue on ubuntu server 22.04.4 arm64.
