### ISSUE TITLE
JIT: Assertion failed 'i < BitSetTraits::GetSize(env)' during profile synthesis

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#95199]
If I run SPMI replay of `coreclr_tests` with `-jitoption JitSynthesizeCounts=1` I hit this assert on a few contexts:
```scala
*************** Inline @[000028] Starting PHASE Profile incorporation
Synthesizing profile data

New BlockSet epoch 1, # of blocks (including unused BB00): 4, bitset array size: 1 (short)
ISSUE: <ASSERT> #1 C:\dev\dotnet\runtime4\src\coreclr\jit\bitsetasshortlong.h (316) - Assertion failed 'i < BitSetTraits::GetSize(env)' in 'Program:<<Main>$>g__TestExecutor88|0_89(System.IO.StreamWriter,System.IO.StreamWriter,byref)' during 'Morph - Inlining' (IL size 271; hash 0x78af786b; FullOpts)
```

The inlinee inherits the EH table from the inliner (why?), so the RPO should probably skip handlers for inlinees. Or we should stop inheriting the EH table (I don't really see why we would do this).

**Comment by AndyAyersMS** [comment]
> The inlinee inherits the EH table from the inliner (why?), so the RPO should probably skip handlers for inlinees. Or we should stop inheriting the EH table (I don't really see why we would do this).

I ran into this in #83610 and from my notes it looks like there is one place in inline pinvoke analysis where we query EH properties of a root block while compiling the inlinee. The PR says I will plan to clean this up separately, but I never did, and I didn't note how exactly I was going to do this.

When we work on inlining methods with EH this will undoubtedly come up again....
