### ISSUE TITLE
Missing Git tags for several 4.x releases

### ISSUE THREAD

**Issue by fviernau** [dotnet/runtime#95198]
I'm trying to find out from which exact source (repo, revision) the following packages have been build.
I've been looking in https://github.com/dotnet/corefx and in this repository without any success.
Any hints?

System.Memory 4.5.5
System.Security.Cryptography.ProtectedData 4.7.0
System.Threading.Tasks.Extensions 4.5.4

**Comment by fviernau** [comment]
Seems like https://github.com/dotnet/source-build-reference-packages/blob/e902a14ab1bc85639853ff054ae16f591d81cf3e/src/referencePackages/src/system.memory/4.5.5/lib/netstandard2.0/System.Memory.cs#L18 indicates that the SHA1 may be https://github.com/dotnet/corefx/tree/32b491939fbd125f304031c35038b1e14b4e3958. However, that does not exist in the corefx repository. 

So, I guess the Git history of corefx has been lost. Is there any publicly available backup of that repo, which still has the Git history?

**Comment by ViktorHofer** [comment]
> So, I guess the Git history of corefx has been lost

**Comment by ViktorHofer** [comment]
@carlossanlop @mmitche it looks like those packages were built internally and the corresponding code changes were never synced back. Is that intentional?

**Comment by ViktorHofer** [comment]
Sourcelink uses the SHA to link to the public source so I'm surprised that the hash wasn't preserved during the code merge.

**Comment by fviernau** [comment]
Thanks @ericstj  and @ViktorHofer , that's really helpful!
I actually had a copy & paste mistake in the issue description. 
I meant to also ask for `System.Threading.Tasks.Extensions 4.5.4`. 
Would you mind giving me a hint on the SHA1 ?

Anyhow, apart from that, is there any general receipe you can share how to figure out SHA1s for 4.x release, so that I can do that myself in the future. E.g. things like 

> System.Security.Cryptography.ProtectedData 4.7.0 was part of the GA release of 3.1

are not obvious to me.

**Comment by ericstj** [comment]
Most packages and binaries will contain the hash of the build that produced them usually this build is also a release tag but even if it isn't you can trust this hash as the exact one that built that binary.  In some rare cases these will not match a public hash (the System.Memory case you shared) - in those cases you should be able to identify the build by finding the first release/tag that included the change that updated the package version.

> I meant to also ask for System.Threading.Tasks.Extensions 4.5.4.
Would you mind giving me a hint on the SHA1 ?

This one is easier: https://www.nuget.org/packages/System.Threading.Tasks.Extensions/4.5.4 shows 7601f4f6225089ffb291dc7d58293c7bbf5c5d4f which is https://github.com/dotnet/corefx/commit/7601f4f6225089ffb291dc7d58293c7bbf5c5d4f

Note the same method worked for System.Security.Cryptography.ProtectedData 4.7.0 - though in this package it was missing the hash from the package readme but downloading the package you can see the hash in the binary metadata:
<img width="289" alt="image" src="https://github.com/dotnet/runtime/assets/8918108/7cb96d7c-d8d3-4326-9cdc-8ffab940f3fb">
```C#
[assembly: AssemblyInformationalVersion("3.1.0+0f7f38c4fd323b26da10cce95f857f77f0f09b48")]
```

For all newer packages they should have the source information in the nuspec.  For example: https://www.nuget.org/api/v2/package/System.Text.Json/8.0.0
```xml
    <repository type="git" url="https://github.com/dotnet/runtime" commit="5535e31a712343a63f5d7d796cd874e563e5ac14" />
```

It's only for older packages that you might need to look at the binary for this information.

**Comment by carlossanlop** [comment]
Closing as the latest comment gives the right answer. Feel free to open a new issue if you still have questions.
