### ISSUE TITLE
HttpClient: How to disable hostcert verification when using SocketsHttpHandler ?

### ISSUE THREAD

**Issue by kjpgit** [dotnet/runtime#95190]
✅ SocketsHttpHandler has `PooledConnectionLifetime ` property so DNS isn't cached forever
✅ HttpClientHandler has `ServerCertificateCustomValidationCallback` so our self signed certs for dev work
🛑 I have no idea how to make a `HttpClient()` that uses both of the above settings

**Comment by MihaZupan** [comment]
If you have a `SocketsHttpHandler`, you can set the `handler.SslOptions.RemoteCertificateValidationCallback` instead, which serves the same purpose as the property on `HttpClientHandler`.

**Comment by kjpgit** [comment]
@MihaZupan  I looked at the doc previously:
https://learn.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.ssloptions?view=net-8.0

but it says:
Property Value
[SslClientAuthenticationOptions](https://learn.microsoft.com/en-us/dotnet/api/system.net.security.sslclientauthenticationoptions?view=net-8.0)
**The set of options used for client TLS authentication.**

So I didn't bother looking further at that class, because it implies it's for client certs, not server verification.

Never thought about looking at a class called `SslClientAuthenticationOptions` for this, but it does appear to be there.  Thanks.
