### ISSUE TITLE
[wasm] Changing DllImport does not result in a new wasm module

### ISSUE THREAD

**Issue by silesmo** [dotnet/runtime#95192]
### Description

Rebuilding a project targeting the wasi-experimental workload when changing the arguments in the DllImport attribute doesn't result in a new wasm module to be built.

I have built this tool that you can use to see all the imports and exports easily directly in the browser, that can hopefully assist when checking the produced wasm: https://wa2.dev/

@lewing 

### Reproduction Steps

Build module using nightly targeting wasi-experimental workload

Example function:
```csharp

    internal static class Float32ParamInterop
    {
        [WasmImportLinkage]
        [DllImport("foo", EntryPoint = "float32-param")]
        internal static extern void wasmImportFloat32Param(float p0);
    }
```
Then change the `EntryPoint` to "float32-param-test":
```csharp

    internal static class Float32ParamInterop
    {
        [WasmImportLinkage]
        [DllImport("foo", EntryPoint = "float32-param-test")]
        internal static extern void wasmImportFloat32Param(float p0);
    }
```
Rebuild using `dotnet build -c Release`
Observe that the import name hasn't changed.

If I delete the bin folder and run `dotnet build -c Release` then all the files except the wasm module is created in `bin/Release/net9.o/wasi-wasm/AppBundle`
![image](https://github.com/dotnet/runtime/assets/4481430/ed771a81-f6c0-4194-b410-bbadb7d4b5b4)

It's not until I delete the obj folder that it actually builds and produces the new wasm module as expected.

### Expected behavior

That the module is rebuilt and produces a new wasm module with the correct import module and function name.

### Actual behavior

Doesn't produce a new wasm module without deleting the obj folder.

### Regression?

Related to: https://github.com/dotnet/runtime/pull/94615

### Known Workarounds

Delete obj folder and rebuild.

**Comment by lewing** [comment]
Sounds like something isn't doing incremental builds correctly right now in the wasi targets, @radical can you take a look.  

@silesmo thanks for the report, was ceased wasi work somewhat abruptly last year and the targets still have some very rough edges that we've mostly forgotten about since, thank you for helping us find them.  Do you have a sample csproj, I can probably offer some suggestions to make things soother while we clean things up.
