### ISSUE TITLE
Is it possible to optimize Array.IndexOf(...) for Type? 

### ISSUE THREAD

**Issue by TrayanZapryanov** [dotnet/runtime#95242]
### Description

Recently I've found a loop over Type[] which pretends to be faster that Dictionary - [DataStorage](https://github.com/dotnet/runtime/blob/804556015e1ff6bc911dac99d7c8c21825fd40e7/src/libraries/System.Data.Common/src/System/Data/Common/DataStorage.cs#L360C13-L360C13) and was surprised. Of course made a benchmark and it is truth :(.
Then I opened [Array class](https://github.com/dotnet/runtime/blob/804556015e1ff6bc911dac99d7c8c21825fd40e7/src/libraries/System.Private.CoreLib/src/System/Array.cs#L1519) and saw that for some specific types there are already optimizations.

Do you think if it will be valuable to add something similar for Type? Maybe there are more places in the code that can benefit from it..

### Configuration

Here it is my simple benchmark:
```
public class IndexOfBenchmarks
{
	private static readonly Type?[] s_storageClassType = new Type?[] {
		null,
		typeof(object),
		typeof(DBNull),
		typeof(bool),
		typeof(char),
		typeof(sbyte),
		typeof(byte),
		typeof(short),
		typeof(ushort),
		typeof(int),
		typeof(uint),
		typeof(long),
		typeof(ulong),
		typeof(float),
		typeof(double),
		typeof(decimal),
		typeof(DateTime),
		typeof(TimeSpan),
		typeof(string),
		typeof(Guid),

		typeof(byte[]),
		typeof(char[]),
		typeof(Type),
		typeof(DateTimeOffset),
		typeof(System.Numerics.BigInteger),
		typeof(Uri),

		typeof(SqlBinary),
		typeof(SqlBoolean),
		typeof(SqlByte),
		typeof(SqlBytes),
		typeof(SqlChars),
		typeof(SqlDateTime),
		typeof(SqlDecimal),
		typeof(SqlDouble),
		typeof(SqlGuid),
		typeof(SqlInt16),
		typeof(SqlInt32),
		typeof(SqlInt64),
		typeof(SqlMoney),
		typeof(SqlSingle),
		typeof(SqlString),
		//            typeof(SqlXml),
	};

	private static readonly int[] s_Ints = Enumerable.Range(0, 50).Select(i => i).ToArray();

	[Benchmark(Baseline = true)]
	public int IndexOf() => Array.IndexOf(s_storageClassType, typeof(Guid));

	[Benchmark]
	public int Loop()
	{
		var dataType = typeof(Guid);
		for (int i = 0; i < s_storageClassType.Length; ++i)
		{
			if (dataType == s_storageClassType[i])
			{
				return i;
			}
		}

		return -1;
	}

	[Benchmark]
	public int IndexOfInts() => Array.IndexOf(s_Ints, 20);
}
```
### Regression?

No

### Data

BenchmarkDotNet v0.13.10, Windows 11 (10.0.22621.2715/22H2/2022Update/SunValley2)
11th Gen Intel Core i9-11900K 3.50GHz, 1 CPU, 16 logical and 8 physical cores
.NET SDK 8.0.100
  [Host]     : .NET 8.0.0 (8.0.23.53103), X64 RyuJIT AVX2
  DefaultJob : .NET 8.0.0 (8.0.23.53103), X64 RyuJIT AVX2

| Method      | Mean      | Error     | StdDev    | Ratio |
|------------ |----------:|----------:|----------:|------:|
| IndexOf     | 16.535 ns | 0.2491 ns | 0.2330 ns |  1.00 |
| Loop        | 11.681 ns | 0.1376 ns | 0.1220 ns |  0.71 |
| IndexOfInts |  2.803 ns | 0.0595 ns | 0.0556 ns |  0.17 |

**Comment by huoyaoyuan** [comment]
> Do you think if it will be valuable to add something similar for Type?

It is not possible. Primitive number types are much more special to be optimized. `Type` doesn't `IEquatable<T>` and it's just a plain reference type for `IndexOf`.

**Comment by TrayanZapryanov** [comment]
@huoyaoyuan Thank you for the information.
Do you know if this is the best way of finding Type - with loop?
Looks like the code that I've found in DataStorage is on hot path.

**Comment by steveharter** [comment]
Closing; Array.IndexOf performance is not a hot path that I'm aware and if it is, it is unlikely to benefit in a worthwhile manner from special-casing primitive types.
