### ISSUE TITLE
Uuuh I caught linux-x86 on dotnet 7.0

### ISSUE THREAD

**Issue by DeafMan1983** [dotnet/runtime#95240]
### Description

Why did you not tell me truth because I catch compilation log like `linux-bionic-x66`?

I have proof
![image](https://github.com/dotnet/runtime/assets/57066679/687c149b-7124-4621-b42b-b0358940f97f)

Why does NativeAOT not support for dotnet 7.0 on Linux? Woah! I thought Dotnet 7.0 has support with `linux-x86`

### Reproduction Steps

net 7.0 tried to compile with `-r linux-x86` since I checked history of compilation-log. 

### Expected behavior

I expected Microsoft betrays us. Because linux-x86 supported on Linux whatever it works. I bet sure because Microsoft shouldn't betray to C#/F# developers.

Please release 32 bit version on Linux now! 

### Actual behavior

Feel shy cause hidden history of compilation-log and I caught it.

### Regression?

net7.0 and net8.0

### Known Workarounds

Workaround on net7.0 and 8.0 with `linux-x64` = ok
But it cannot compiled to 32 bit.
` /usr/share/dotnet/sdk/8.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1203: Ahead-of-time compilation is not supported for the target runtime identifier 'linux-x86'.`

What did you about?

### Configuration

x64

### Other information

I already installed clang / gcc for x64 and x86

**Comment by NCLnclNCL** [comment]
Window x86 32 bit too dont supported, I think Linux x86 32 bit is really dead

**Comment by DeafMan1983** [comment]
Thank you for explanation! But why does Microsoft forgets to remove died linux-*-x86 from supported rid-lists. 

I will respect everyone.. I am sorry for hesitation for hidden rid-lists. Please forgive me!

**Comment by hez2010** [comment]
> Okay. But why does dotnet not support for NativeAot?

See https://github.com/dotnet/runtime/issues/86573

Currently the x86 support for NativeAOT still has a lot of issues need to be resolved, but no one has time to look into it.
If you have any interest, you can see the previous attempt to enable x86 support: https://github.com/dotnet/runtimelab/pull/1531.  A PR that enables x86 support for NativeAOT from the community is highly welcomed and appreciated.
