### ISSUE TITLE
.net core 8 not working on a brand new Mac ARM 64

### ISSUE THREAD

**Issue by vf-lennin** [dotnet/runtime#95259]
### Description

In a Mac ARM64 laptop dotnet--info fails due to libhostpolicy.dylib error.

### Reproduction Steps

Upon installing dotnet using the binaries 
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-8.0.100-macos-arm64-binaries

and installing in dotnet directory 

mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-8.0.100-osx-arm64.tar.gz -C $HOME/dotnet
export DOTNET_ROOT=$HOME/dotnet
export PATH=$PATH:$HOME/dotnet

when running dotnet --info

### Expected behavior

no errors reported

### Actual behavior

Failed to load /Users/user1/dotnet/shared/Microsoft.NETCore.App/8.0.0/libhostpolicy.dylib, error: dlopen(/Users/user1/dotnet/shared/Microsoft.NETCore.App/8.0.0/libhostpolicy.dylib, 0x0001): tried: '/Users/user1/dotnet/shared/Microsoft.NETCore.App/8.0.0/libhostpolicy.dylib' (code signature in <5D23F46E-5D5D-3FAE-A6DA-42D9581D6836> '/Users/user1/dotnet/shared/Microsoft.NETCore.App/8.0.0/libhostpolicy.dylib' not valid for use in process: library load disallowed by system policy), '/System/Volumes/Preboot/Cryptexes/OS/Users/user1/dotnet/shared/Microsoft.NETCore.App/8.0.0/libhostpolicy.dylib' (no such file), '/Users/user1/dotnet/shared/Microsoft.NETCore.App/8.0.0/libhostpolicy.dylib' (code signature in <5D23F46E-5D5D-3FAE-A6DA-42D9581D6836> '/Users/user1/dotnet/shared/Microsoft.NETCore.App/8.0.0/libhostpolicy.dylib' not valid for use in process: library load disallowed by system policy)
An error occurred while loading required library libhostpolicy.dylib from [/Users/user1/dotnet/shared/Microsoft.NETCore.App/8.0.0]

Host:
  Version:      8.0.0
  Architecture: arm64
  Commit:       5535e31a71
  RID:          osx-arm64

.NET SDKs installed:
  8.0.100 [/Users/user1/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0 [/Users/user1/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0 [/Users/user1/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/Users/user1/dotnet]
  DOTNET_ROOT_ARM64 [/Users/user1/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

### Configuration

In a Mac ARM64 laptop

uname -a

Darwin xxxx 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:32:11 PDT 2023; root:xnu-10002.41.9~7/RELEASE_ARM64_T6030 arm64

using .net 8 sdk
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-8.0.100-macos-arm64-binaries

**Comment by vf-lennin** [comment]
@EgorBo   I don't have admin rights. so can I only test on a user profile.  Package installer only works if you have admin rights.

**Comment by lambdageek** [comment]
This happens to me as well sometimes, I think there's some problem with the binary signing.  macOS ends up quarantining  the dylib files from a newly downloaded app.

As a workaround you can do this to remove the quarantine 

```console
$ cd $DOTNET_ROOT
$ xattr -d -r com.apple.quarantine .
```

**Comment by vf-lennin** [comment]
@lambdageek thank you that fixes the issue.
