### ISSUE TITLE
Trim analyzer doesn't warn on mismatched annotations through method group conversions

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#95258]
### Description

Noticed a trim analyzer bug that's currently affecting CsWinRT, as I was working on some tweaks there. It seems that the linker analyzer fails to correctly warn on mismatched annotations when passing the target method through method group conversions. This is hitting CsWinRT [here](https://github.com/microsoft/CsWinRT/blob/71169932920500310921b4c3fadba1e5a99c6138/src/WinRT.Runtime/ObjectReference.cs#L601C68-L601C74), where no warning is produced despite this call not being trim safe.

### Reproduction Steps

```csharp
public static class Foo
{
    public static int Bar([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicFields)] Type type)
    {
        return 0;
    }
}

public class Baz<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.NonPublicConstructors)] T>
{
    public void Blah()
    {
        static int InnerBlah(int x)
        {
            return Foo.Bar(typeof(T));
        }

        new ConcurrentDictionary<int, int>().GetOrAdd(0, InnerBlah);
    }
}
```

### Expected behavior

This should be produced on that `Foo.Bar(typeof(T))` call:

> "warning IL2087: 'type' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicFields' in call to 'Foo.Bar(Type)'. The generic parameter 'T' of 'Baz<T>' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to."

### Actual behavior

No warnings are produced. Note: this only happens with a method group conversion. Using `x => InnerBlah(x)` does warn.

**Comment by vitek-karas** [comment]
@Sergio0694 do you think we should try to backport the fix (whatever it is for now)

**Comment by Sergio0694** [comment]
I think there's other broken trimming warnings in .NET 8 too (eg. the missing `MakeGenericType` from #93785 is another example), so we might want to consider all of them together? This doesn't seem particularly different than that in terms of importance. I would say if there's no plans to backport that either, probably not worth it to do it for this one? Or otherwise if we would consider to backport this one, I think it might be nice to do the same for the other one as well. Given .NET 8 is LTS and the first such version with official NativeAOT support, personally I think it'd be nice to help library authors out. If these are just some analyzer fixes and with no runtime/BCL changes, is the risk considered low and such that this could be doable for a servicing release? 🤔
