### ISSUE TITLE
DOTNET_JitDisasm output (redirected to file) gets garbled with big dumps

### ISSUE THREAD

**Issue by hypeartist** [dotnet/runtime#95261]
While dumping (to file) disassembly of some of my apps I get the resulted file of size ~5mb and at some point (around mid-file) disassembly starts to look more and more like this:

![image](https://github.com/dotnet/runtime/assets/3519388/32343418-607f-481c-99b0-a27eb7a79532)

**Comment by EgorBo** [comment]
@hypeartist is this crossgen/ilc? if so, it can be workarounded by --parallelism 1. Although, it may happen with normal jit too - we don't take any lock to print disasm so if two compilations have JitDisasm set (or it's *) we can hit this issue.

cc @dotnet/jit-contrib if we already have an issue for it somewhere (I remember we discussed it few times).

**Comment by MichalPetryka** [comment]
Duplicate of #88413.

**Comment by hypeartist** [comment]
@EgorBo No it's not crossgen/ilc. Just an ordinary compilation. A WinForms app that is being run like this:
`del dis.asm >nul 2>&1 && set DOTNET_ReadyToRun=0 && set DOTNET_JitDisasm=*.*:* && set DOTNET_JitStdOutFile=dis.asm && WindowsFormsApp.exe`
I've noticed that things get messed right when threading/syncing methods getting jitted, so I guess @MichalPetryka is right linking my issue with 88413.
