### ISSUE TITLE
Environment.GetFolderPath returns different than .NET 7 on MacOS in .NET 8

### ISSUE THREAD

**Issue by enisn** [dotnet/runtime#95269]
### Description

In .NET8 `Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData)` returns different things than .NET7 on MacOS with M1 Chipset

.NET7:
![image](https://github.com/dotnet/runtime/assets/23705418/0a876d44-0bff-4099-92fe-00a2c72692b1)

.NET8:
![image](https://github.com/dotnet/runtime/assets/23705418/d114bf03-99e2-4949-ae46-bf645d12ca7e)

I don't know which one is correct but it's annoying getting different paths according to runtime.

### Reproduction Steps

- Create a new console app
  ```bash
  dotnet new console -n EnvironmentTest
  ```

- Update the csproj:
  ```xml
  <TargetFrameworks>net7.0;net8.0</TargetFrameworks>
  ```

- Update the **Program.cs**
  
  ```csharp
  Console.WriteLine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData));
  ```

- And run on both framework:
  ```bash
  dotnet run --framework net7.0
  dotnet run --framework net8.0
  ```

<img width="617" alt="image" src="https://github.com/dotnet/runtime/assets/23705418/7da89d74-349c-46ff-a851-e6338a7b5fbe">

### Expected behavior

Both runtime should return the same thing or there should be a compatibility

### Actual behavior

Returns completely different paths on different target frameworks

### Regression?

There is no difference between .NET6 and .NET7. I'm not sure for earlier versions

### Known Workarounds

None yet

### Configuration

**.NET Versions:** 7.0 and 8.0
**OS:** MacOS
**Architecture:** Apple Silicon M1 (ARM64)

**Comment by vcsjones** [comment]
This is a documented breaking change for .NET 8. See [.NET 8 breaking change: GetFolderPath behavior on Unix - .NET | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/8.0/getfolderpath-unix) for more information.

**Comment by enisn** [comment]
Ok, sorry I missed it. I'm closing this issue.

I'll migrate application files according to [Recommended Actions](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/8.0/getfolderpath-unix#recommended-action)
