### ISSUE TITLE
Failing test -`System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime` on windows/x86

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#95298]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=481491
Build error leg or test failing: System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime
Pull request: https://github.com/dotnet/runtime/pull/95146

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "WritingShouldUpdateWriteTime_After_SetLastAccessTime",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=481491
**Error message validated:** `WritingShouldUpdateWriteTime_After_SetLastAccessTime`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 11/27/2023 10:59:45 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[482898](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482898)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/482898/logs/1440)|dotnet/runtime#95292|

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[482764](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482764)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482764&view=ms.vss-test-web.build-test-results-tab&runId=11110540&resultId=142277)||
|[482742](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482742)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482742&view=ms.vss-test-web.build-test-results-tab&runId=11109470&resultId=154952)|dotnet/runtime#94737|
|[482734](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482734)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482734&view=ms.vss-test-web.build-test-results-tab&runId=11109168&resultId=141706)|dotnet/runtime#94528|
|[482667](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482667)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482667&view=ms.vss-test-web.build-test-results-tab&runId=11105002&resultId=143538)|dotnet/runtime#94684|
|[482658](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482658)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482658&view=ms.vss-test-web.build-test-results-tab&runId=11104886&resultId=139693)|dotnet/runtime#95352|
|[482571](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482571)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482571&view=ms.vss-test-web.build-test-results-tab&runId=11101868&resultId=141911)|dotnet/runtime#93220|
|[482565](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482565)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482565&view=ms.vss-test-web.build-test-results-tab&runId=11101494&resultId=142277)|dotnet/runtime#95341|
|[482515](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482515)|dotnet/runtime|[WasmTestOnBrowser-System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482515&view=ms.vss-test-web.build-test-results-tab&runId=11099948&resultId=184854)|dotnet/runtime#92462|
|[482507](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482507)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482507&view=ms.vss-test-web.build-test-results-tab&runId=11099924&resultId=141911)|dotnet/runtime#85978|
|[482460](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482460)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482460&view=ms.vss-test-web.build-test-results-tab&runId=11098564&resultId=144186)|dotnet/runtime#95260|
|[482400](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482400)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482400&view=ms.vss-test-web.build-test-results-tab&runId=11096938&resultId=144730)|dotnet/runtime#95180|
|[482375](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482375)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482375&view=ms.vss-test-web.build-test-results-tab&runId=11096322&resultId=143552)|dotnet/runtime#95334|
|[482361](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482361)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482361&view=ms.vss-test-web.build-test-results-tab&runId=11096192&resultId=143827)|dotnet/runtime#95333|
|[482336](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482336)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482336&view=ms.vss-test-web.build-test-results-tab&runId=11095588&resultId=140996)|dotnet/runtime#95329|
|[482326](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482326)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482326&view=ms.vss-test-web.build-test-results-tab&runId=11095072&resultId=143439)|dotnet/runtime#95332|
|[482247](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482247)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482247&view=ms.vss-test-web.build-test-results-tab&runId=11092580&resultId=145532)|dotnet/runtime#95274|
|[482248](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482248)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482248&view=ms.vss-test-web.build-test-results-tab&runId=11092576&resultId=157264)|dotnet/runtime#95274|
|[482145](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482145)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482145&view=ms.vss-test-web.build-test-results-tab&runId=11087638&resultId=143413)|dotnet/runtime#93220|
|[482039](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482039)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482039&view=ms.vss-test-web.build-test-results-tab&runId=11086032&resultId=129527)||
|[481445](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481445)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481445&view=ms.vss-test-web.build-test-results-tab&runId=11085310&resultId=140495)|dotnet/runtime#95278|
|[482022](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482022)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482022&view=ms.vss-test-web.build-test-results-tab&runId=11083828&resultId=144240)|dotnet/runtime#93220|
|[482040](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482040)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482040&view=ms.vss-test-web.build-test-results-tab&runId=11083664&resultId=141125)||
|[481152](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481152)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481152&view=ms.vss-test-web.build-test-results-tab&runId=11083250&resultId=143723)|dotnet/runtime#94764|
|[482006](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482006)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482006&view=ms.vss-test-web.build-test-results-tab&runId=11082938&resultId=142277)||
|[481904](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481904)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481904&view=ms.vss-test-web.build-test-results-tab&runId=11079820&resultId=144031)|dotnet/runtime#94868|
|[481870](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481870)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481870&view=ms.vss-test-web.build-test-results-tab&runId=11078886&resultId=151554)|dotnet/runtime#95308|
|[481857](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481857)|dotnet/runtime|[WasmTestOnBrowser-System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481857&view=ms.vss-test-web.build-test-results-tab&runId=11078300&resultId=184846)|dotnet/runtime#95307|
|[481867](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481867)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481867&view=ms.vss-test-web.build-test-results-tab&runId=11078868&resultId=143558)|dotnet/runtime#95301|
|[481824](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481824)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481824&view=ms.vss-test-web.build-test-results-tab&runId=11077782&resultId=141369)|dotnet/runtime#95146|
|[481704](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481704)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481704&view=ms.vss-test-web.build-test-results-tab&runId=11072398&resultId=142287)|dotnet/runtime#95301|
|[481669](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481669)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481669&view=ms.vss-test-web.build-test-results-tab&runId=11070384&resultId=144880)|dotnet/runtime#91229|
|[481561](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481561)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481561&view=ms.vss-test-web.build-test-results-tab&runId=11070252&resultId=129600)||
|[481304](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481304)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481304&view=ms.vss-test-web.build-test-results-tab&runId=11069068&resultId=143875)|dotnet/runtime#95233|
|[481625](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481625)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481625&view=ms.vss-test-web.build-test-results-tab&runId=11068574&resultId=159981)|dotnet/runtime#94825|
|[481560](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481560)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481560&view=ms.vss-test-web.build-test-results-tab&runId=11065084&resultId=139905)||
|[481512](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481512)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481512&view=ms.vss-test-web.build-test-results-tab&runId=11063770&resultId=157147)|dotnet/runtime#95288|
|[481502](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481502)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481502&view=ms.vss-test-web.build-test-results-tab&runId=11063144&resultId=143108)||
|[480681](https://dev.azure.com/dnceng-public/public/_build/results?buildId=480681)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=480681&view=ms.vss-test-web.build-test-results-tab&runId=11063122&resultId=129544)|dotnet/runtime#95221|
|[481491](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481491)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481491&view=ms.vss-test-web.build-test-results-tab&runId=11062326&resultId=147463)|dotnet/runtime#95146|
|[481451](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481451)|dotnet/runtime|[WasmTestOnBrowser-System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481451&view=ms.vss-test-web.build-test-results-tab&runId=11061212&resultId=184846)|dotnet/runtime#94587|
|[481483](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481483)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481483&view=ms.vss-test-web.build-test-results-tab&runId=11062198&resultId=144188)|dotnet/runtime#94684|
|[481466](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481466)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481466&view=ms.vss-test-web.build-test-results-tab&runId=11062116&resultId=144211)|dotnet/runtime#95287|
|[481271](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481271)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481271&view=ms.vss-test-web.build-test-results-tab&runId=11060362&resultId=139780)|dotnet/runtime#95275|
|[481352](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481352)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481352&view=ms.vss-test-web.build-test-results-tab&runId=11056376&resultId=143351)|dotnet/runtime#93220|
|[481337](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481337)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481337&view=ms.vss-test-web.build-test-results-tab&runId=11056210&resultId=168900)|dotnet/runtime#91297|
|[481217](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481217)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481217&view=ms.vss-test-web.build-test-results-tab&runId=11054190&resultId=144202)|dotnet/runtime#94370|
|[481290](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481290)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481290&view=ms.vss-test-web.build-test-results-tab&runId=11052780&resultId=163404)|dotnet/runtime#95260|
|[481137](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481137)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481137&view=ms.vss-test-web.build-test-results-tab&runId=11049220&resultId=141443)|dotnet/runtime#95180|
|[481085](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481085)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481085&view=ms.vss-test-web.build-test-results-tab&runId=11047610&resultId=143060)|dotnet/runtime#95264|
|[480926](https://dev.azure.com/dnceng-public/public/_build/results?buildId=480926)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=480926&view=ms.vss-test-web.build-test-results-tab&runId=11044476&resultId=142258)|dotnet/runtime#94211|
|[480847](https://dev.azure.com/dnceng-public/public/_build/results?buildId=480847)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=480847&view=ms.vss-test-web.build-test-results-tab&runId=11040198&resultId=143342)|dotnet/runtime#93938|
|[480774](https://dev.azure.com/dnceng-public/public/_build/results?buildId=480774)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=480774&view=ms.vss-test-web.build-test-results-tab&runId=11038024&resultId=141427)|dotnet/runtime#95180|
|[480761](https://dev.azure.com/dnceng-public/public/_build/results?buildId=480761)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=480761&view=ms.vss-test-web.build-test-results-tab&runId=11037458&resultId=160451)|dotnet/runtime#85951|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|34|54|54|

**Comment by Jozkee** [comment]
@smx-smx @adamsitnik, is this related to https://github.com/dotnet/runtime/issues/95096?

**Comment by adamsitnik** [comment]
It is. I'll try to repro that and most likely provide a C++ repro for the Windows Team.
