### ISSUE TITLE
SetEnvironmentVariable does not work properly on Unix 

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#9529]
This is related to dotnet/runtime#4103 and dotnet/coreclr#3140.
In my case I use 

``` c#
Environment.SetEnvironmentVariable("all_proxy",` "http://10.121.122.110:3128");
```
and I expect HTTP Handler to honor it same way is if set before process start. 
In this case, we do no fork child process so fix-up for process start is not applicable. 

I understand that setenv() is not thread safe and that we choose not to actually set  environment variables but to work on our copy instead. 
We may perhaps re-consider and fix it. 
There is similar pattern calling openssl where init function is not thread safe. To address that we simply added lock around the call to make it thread safe. 
This would be needed only for Linux (PAL?) and I would think the setenv() call is not likely on performance critical path.  

I also verified that when i call setnev() via [DllImport] works as expected. 
It is workaround but it would be nice if the SetEnvironmentVariable just work.

**Comment by parched** [comment]
Can this note be added to [these docs](https://docs.microsoft.com/en-us/dotnet/api/system.environment.setenvironmentvariable?view=net-6.0)? It would've saved me a fair bit of debugging time.

**Comment by danmoseley** [comment]
@parched  feel free to offer a PR to improve the doc (click edit button on doc page)

I'll close this as apparently that was originally intended
