### ISSUE TITLE
GeneratedRegex source file RegexGenerator.g.cs not found by debugger

### ISSUE THREAD

**Issue by coderb** [dotnet/runtime#95293]
### Description

I've got a regex in my class using the `GeneratedRegex` attribute.  Code compiles and runs but when I try to step in to the partial method Visual Studio 17.8.0 can't find the source file.

I don't see it existing anywhere in my project tree and I also don't see it listed under `Dependencies > Analyzers > System.Text.RegularExpressions.Generator > System.Text.RegularExpressions.Generator.RegexGenerator > RegexGenerator.g.cs` per the docs at https://learn.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-source-generators.

Using dotnet 8 RTM under windows / visual studio 2022 64 bit.

### Reproduction Steps

see above

### Expected behavior

source file for regex

### Actual behavior

not found

**Comment by steveharter** [comment]
FYI the doc is:
`
In Visual Studio, right-click on your partial method declaration and select Go To Definition. Or, alternatively, select the project node in Solution Explorer, then expand Dependencies > Analyzers > System.Text.RegularExpressions.Generator > System.Text.RegularExpressions.Generator.RegexGenerator > RegexGenerator.g.cs to see the generated C# code from this regex generator.
`

**Comment by steveharter** [comment]
@stephentoub have you seen issues with the generated code not being visible and\or debuggable through step-in?

**Comment by coderb** [comment]
@steveharter yeah, i tried "Go to Definition"... VS opens a tab titled "RegexGenerator.g.c" under "Miscellaneaous Files" but the contents are empty.  As I stated above, there are no child nodes under the Analyzer tree.  :-(

**Comment by coderb** [comment]
btw, i just updated to the latest patch VS 17.8.2 and still no bueno.

**Comment by coderb** [comment]
also, when i mentioned it's not in my source tree, i did a file system search under my source code directory.

where, physically, would the `.g.cs` file be generated to on the file system?  thanks.

**Comment by stephentoub** [comment]
> @stephentoub have you seen issues with the generated code not being visible and\or debuggable through step-in?

I haven't. It's always "just worked" for me.

> where, physically, would the .g.cs file be generated to on the file system?

You need:
```xml
<PropertyGroup>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
</PropertyGroup>
```
in your .csproj for the files to be persisted to disk.

**Comment by coderb** [comment]
@stephentoub `EmitCompilerGeneratedFiles` did cause the file to be generated as you said.

As it turns out.... resharper is the culprit for go to definition not working.  After disabling the extension everything seems to work properly.

Thank you stephen, the dotnet community is very lucky to have you.
