### ISSUE TITLE
System.Net.IPNetwork - not working

### ISSUE THREAD

**Issue by suchoss** [dotnet/runtime#95321]
### Description

System.Net.IPNetwork seems to be broken. It doesn`t work and always throws an exception: "System.FormatException: An invalid IP network was specified."

### Reproduction Steps

```csharp
//this IPNetwork works
var works = Microsoft.AspNetCore.HttpOverrides.IPNetwork.Parse("192.168.1.1/24");
//this IPNetwork doesnt work
var doesntWork = System.Net.IPNetwork.Parse("192.168.1.1/24");
```

### Expected behavior

I would expect that this wont throw any exception `var doesntWork = System.Net.IPNetwork.Parse("192.168.1.1/24");`

### Actual behavior

I am getting `System.FormatException: An invalid IP network was specified.` exception. And I am confused how to use this `System.Net.IPNetwork`

### Configuration

dotnet 8.0.100
Apple M1 Pro
macOS 14.1.1

But we tested it even on windows machine and we are getting the same results.

### Other information

When I tried to step into (limited functionality on MacOS) i found this issue `The specified baseAddress has non-zero bits after the network prefix. (Parameter 'baseAddress')`

**Comment by MihaZupan** [comment]
See https://learn.microsoft.com/en-us/dotnet/api/system.net.ipnetwork?view=net-8.0#remarks

> This type disallows arbitrary IP-address/prefix-length CIDR pairs. [BaseAddress](https://learn.microsoft.com/en-us/dotnet/api/system.net.ipnetwork.baseaddress?view=net-8.0#system-net-ipnetwork-baseaddress) must be defined so that all bits after the network prefix are set to zero. In other words, [BaseAddress](https://learn.microsoft.com/en-us/dotnet/api/system.net.ipnetwork.baseaddress?view=net-8.0#system-net-ipnetwork-baseaddress) is always the first usable address of the network. The constructor and the parsing methods will throw in case there are non-zero bits after the prefix.

In your case, that would mean that the input has to be `192.168.1.0/24` instead of `192.168.1.1/24`

**Comment by suchoss** [comment]
@MihaZupan Thanks a lot. It helped.

**Comment by mishun** [comment]
Hi!
Apologies for bumping closed issue, but am I undestanding correctly that parsing inputs like `192.168.1.1/24` is currently basically impossible with `IPNetwork`? (and incidentally, getting `IPNetwork` from adapter's IP address and prefix length is pretty hard?)

**Comment by suchoss** [comment]
Sorry for the broad answer. From my understanding of the issue it works as following:
 
IP address is "a composite" of two addresses: Network address and computer address.

Network address is the left part of IP, computer address is the right part of IP. 

E.g.
From `10.10.100.1` - you are not able to easily say which part is network address and which is computer address.
From `10.10.100.1/8` - you are able to say which part is network and which is computer since `/8` says that the first 8 bits from the left is network address and the rest is computer address. But in order to have 'System.Net.IPNetwork' working here, you need to have only Network address without computer address bits set. So it would have to be `10.0.0.0.`

It is maybe a bit more understandable if you imagine it like bits.
`10.10.100.1/8` => `00001010.00001010.01100100.00000001` => this is not going to be accepted by 'System.Net.IPNetwork`, because after 8 bit from the left there are bits set to true (1)
`10.0.0.0/8` => `00001010.00000000.00000000.00000000` => this will be ok for 'System.Net.IPNetwork' there are only zeros after 8 bit from the left.

If you know network mask `/x`, then you can write your own parser using bitwise `&` operation to set right bits to zeros and then input it to  'System.Net.IPNetwork'.

**Comment by mishun** [comment]
Wow, that's really nice explanation!

I looked the implementation up:
https://github.com/dotnet/runtime/blob/bacdea3e4dc18d751494464018eb62979ecf5b2c/src/libraries/System.Net.Primitives/src/System/Net/IPNetwork.cs#L180-L201
and it more or less confirms it.

Regarding 'can write your own parser' part, well, I was hoping to replace existing DIY stuff with `IPNetwork`. Frankly, pairs of ethernet interface address and network prefixe is probably the most common context CIDR string occur, so `IPNetwork` looks pretty much useless as is.
