### ISSUE TITLE
DateTime.Parse exception missing input value in .NET 8

### ISSUE THREAD

**Issue by LeeArbon** [dotnet/runtime#95331]
### Description

When an incorrectly formatted string is provided to the DateTime.Parse method, a FormatException is thrown showing the invalid value, for example: "String '01/23/2023' was not recognized as a valid DateTime."

When switching to .NET 8, the exception message is missing the value between the two single quotes and so instead reads "String '' was not recognized as a valid DateTime."

### Reproduction Steps

1. Create a .NET 7 console application
2. Add DateTime.Parse("01/23/2023", new CultureInfo("en-GB")); to Program.cs
3. Debug the application and note the exception thrown shows the input value
4. Change the project to .NET 8
5. Debug the application and note the exception is now missing the value passed in and instead shows an empty value between the two single quotes

### Expected behavior

The message in the FormatException should read "String '01/23/2023' was not recognized as a valid DateTime."

### Actual behavior

The message in the FormatException reads "String '' was not recognized as a valid DateTime."

### Regression?

This is new behaviour in .NET 8

### Configuration

.NET 8
Windows 11 Business
x64

**Comment by stephentoub** [comment]
@tarekgh, yet another report. We should backport the fix, assuming this is indeed the same issue.

**Comment by karakasa** [comment]
The issue was fixed in #91303 for .NET 9

**Comment by tarekgh** [comment]
>  yet another report. We should backport the fix, assuming this is indeed the same issue.

I'll take a look and will work on fixing and porting the fix to 8.0 servicing.

**Comment by tarekgh** [comment]
https://github.com/dotnet/runtime/issues/94837
https://github.com/dotnet/runtime/issues/94907

**Comment by tarekgh** [comment]
Fixed by the attached PR.
