### ISSUE TITLE
httpclient need proxy for each request

### ISSUE THREAD

**Issue by NCLnclNCL** [dotnet/runtime#95342]
Like python 
r = requests.get(url, headers=headers, proxies=proxies)
I find that currently having to create a new httpclient with httphandle is too expensive and will cause socket exhaustion, Could there be a better solution?

**Comment by wfurt** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/35992? Or do I miss anything @NCLnclNCL?

**Comment by MihaZupan** [comment]
> having to create a new httpclient with httphandle is too expensive and will cause socket exhaustion

How does python behave differently in this case to avoid such issues?

**Comment by NCLnclNCL** [comment]
> > having to create a new httpclient with httphandle is too expensive and will cause socket exhaustion
> 
> How does python behave differently in this case to avoid such issues?

it like this https://github.com/mboukhlouf/WebProxyService/tree/master, 1 httpclient with many proxy

**Comment by ManickaP** [comment]
Feel free to continue the discussion about python, but this is duplicate of #35992, closing.
