### ISSUE TITLE
System.Net.Http.StreamContent.ReadAsStreamAsync() doesn't reset to stream to initial position

### ISSUE THREAD

**Issue by filipnavara** [dotnet/runtime#95344]
### Description

The contract of `HttpContent` seems to be that it can be read multiple times or throw an exception on the second attempt to read.

`StreamContent` violates the contract when the first read is performed with `CopyToAsync` method which reads the underlying stream and doesn't seek back to the beginning (expected), followed by `ReadAsStreamAsync` which doesn't seek back (unexpected).

This is a practical problem because we may log the request content by using `content.CopyToAsync` method and `NSUrlSessionHandler` on iOS/macOS uses the `ReadAsStreamAsync` method which erroneously returns unseeked stream and so the request is sent with no content.

### Reproduction Steps

```
using System;
using System.IO;
using System.Net.Http;

Console.WriteLine("StreamContent:");
TestHttpContent(new StreamContent(new MemoryStream("Hello World"u8.ToArray())));

Console.WriteLine("ByteArrayContent:");
TestHttpContent(new ByteArrayContent("Hello World"u8.ToArray()));

static async void TestHttpContent(HttpContent content)
{
    using var duplicate1 = new MemoryStream();
    await content.CopyToAsync(duplicate1);
    duplicate1.Position = 0;
    Console.WriteLine("1: " + new StreamReader(duplicate1).ReadToEnd());
                      
    var duplicate2 = await content.ReadAsStreamAsync();
    Console.WriteLine("2: " + new StreamReader(duplicate2).ReadToEnd());

    using var duplicate3 = new MemoryStream();
    await content.CopyToAsync(duplicate3);
    duplicate3.Position = 0;
    Console.WriteLine("3: " + new StreamReader(duplicate3).ReadToEnd());
}
```

### Expected behavior

Prints
```
StreamContent:
1: Hello World
2: Hello World
3: Hello World
ByteArrayContent:
1: Hello World
2: Hello World
3: Hello World
```

### Actual behavior

Prints
```
StreamContent:
1: Hello World
2: 
3: Hello World
ByteArrayContent:
1: Hello World
2: Hello World
3: Hello World
```

### Other information

Possible fix is to add `PrepareContent()` call to `StreamContent.CreateContentReadStream` and `StreamContent.CreateContentReadStreamAsync()`.

**Comment by ManickaP** [comment]
A similar thing, just without the rewinding, is done in `HttpConnectionResponseContent`: 
https://github.com/dotnet/runtime/blob/413efe748ac4c5daabf087ed8ed0d59c511e5cf2/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionResponseContent.cs#L72-L73

So this seem like reasonable ask and fairly easy to do.
