### ISSUE TITLE
Improve UX for publishing existing project as wasi

### ISSUE THREAD

**Issue by richlander** [dotnet/runtime#95345]
I've started converting existing projects to Wasi. I always get this error first:

```bash
rich@Richs-Air count % dotnet run
WasmAppHost --runtime-config /Users/rich/git/convenience/wordcount/count/bin/Debug/net8.0/wasi-wasm/AppBundle/count.runtimeconfig.json
Error: no perHostConfigs found
```

I then remember that I need the following file:

```bash
% cat runtimeconfig.template.json 
{
    "wasmHostProperties": {
        "perHostConfig": [
            {
                "name": "wasmtime",
                "Host": "wasmtime"
            }
        ]
    }
}
```

It would be good if we could make `wasmtime` the default. I'm glad that this is configurable, however.

Ideally, we'd upgrade the current `RuntimeIdentifier` approach to be more like `PublishWasi`, just like `PublishAot`. And then have an optional `WasmHost` property.

```xml
<PropertyGroup>
   <PublishWasi>true</PublishWasi>
   <WasmHost>wasmtime</WasmHost>
</PropertyGroup>
```

We should also decide if parameters to the `WasmHost` should be handled here. I'd ideally like to be able to `dotnet run` a wasm app that requires directory mapping, for example.

**Comment by radical** [comment]
How did you create this project? Did you use the `wasiconsole` template?

**Comment by KieranFoot** [comment]
I used the template and the file is indeed missing.
