### ISSUE TITLE
Strange 'BinarySearch' behavior with some special unicode characters

### ISSUE THREAD

**Issue by makeman-p81** [dotnet/runtime#95363]
### Description

According documentation `IndexOf` and `BinarySearch` methods should return negative values when a search item is not present at a collection or an array. But there are strange cases with some sort of unicode characters when results with methods inconsistent

[magic 14 on sharplab.io](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAIAYAEqCMAWAbgFgAoUjbHANkoDoBhAeygGdGAbAU2LJIDcAhmEwBbAQHMAlgGN8mALyYonAO6YAMpJbAAPLnQA+ABQBKUgG9MAIkDnMICuYK5gC+PUgHUwk4J03KjYqVk8BmZgAUlWIyscACYrExMCTAB6ZMwAMQF2Fk53T29fTn8JGXxaAEkoOE4ADwB5ADMo2PjElLSAWhw8rx8IooDS4IAhCKEATwBlTiFpAAtmuISk1MwunoL+01cSD17C4sCypigwiJZmvFaVtMzs3N38vr9BoIqq2sbL6/a17sf9ltXmVRlAJtNZgtoldlr8sDpFCo5uNMFhzt4BHA/pgAIR4jbPIqJUgEg7A4InM6RKyARThAFeQP1WdxypKBJTelWq9SatIZsNW6wBmxe7JBYzAUxmYHmUXpjLS8MRyNRmHRMyxXVx+KFhO2QA==)
```
var magic14 = new List<string>()
{ "೧೪" };

WriteLine(magic14.Contains("12")); // False
WriteLine(magic14.IndexOf("12")); // -1
WriteLine(magic14.BinarySearch("12")); // -1
WriteLine();

WriteLine(magic14.Contains("14")); // False
WriteLine(magic14.IndexOf("14")); // -1
WriteLine(magic14.BinarySearch("14")); // 0 <= why 0 instead -1 !!!
WriteLine();

WriteLine(magic14.Contains("๑৪")); // False
WriteLine(magic14.IndexOf("๑৪")); // -1
WriteLine(magic14.BinarySearch("๑৪")); // 0 <= why 0 instead -1 !!!
WriteLine();
```
and [more magic numbers on sharplab.io](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAIAYAEqCMAWAbgFgAoUjbHANkoDoBhAeygGdGAbAU2LJIDcAhmEwQWEAewAyASxbBMAXkxROAd0wy5AHlzoAfAAoAlKQDemAETp0FmJfQ5b9gExOrAZjfo8XgKxeqLwB2LwAOLwBONxwbOwscRzicVyTPJJ8k/0wAXx5SQWEAWwEAc2kAY015JRV1Kp0YwxMScytAM8gvQEU4L0ALqC9AS8gvQCvIL0BSeC9AG0gvQHU4L0ALMC9Ae0ho2MsE6JS1tMtAc5hAK5horNzSUgB1MGlgThkVA1FxKVlgBmZgAWlWAytXIyMCTAA9ADMAAVSCcM4XK43Th3MQSKq0ACSUDgnAAHgB5ABmX3QPz+gOBzkhl2uH1h9wRT1oACEPkIAJ4AZU4QnKAAs8QT/kDMCTeOcyTCvn1FEoLD9ecCAGISFgQkhC6EUvFihQS/EWQl8uXsBUnJVQ8m3YplSo0phQN4fFjc7U62XyxXKk2ws0VREotFY3HfB3SzAAWhwpJVptKnpp9KgTNZ7K5/t+gecmC0SgARhB5BiAA6ccpXODKTglATAaR8TgAQlrmB6mGrSmcQA=)
```
var usualList = new List<string>()
{ "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15" };

var magicList = new List<string>()
{ "0০", "0๑", "0૨", "0৩", "0৪", "0༥", "0६", "0๗", "0٨", "0९", "10", "11", "12", "13", "೧೪", "15" };

WriteLine(usualList.Contains("02")); // True
WriteLine(usualList.IndexOf("02")); // 2
WriteLine(usualList.BinarySearch("02")); // 2

WriteLine("૨" == "2"); // False
WriteLine("0૨" == "02"); // False

WriteLine(magicList.Contains("02")); // False
WriteLine(magicList.IndexOf("02")); // -1
WriteLine(magicList.BinarySearch("02")); // 2 <= but expected negative!!! ૨ != 2
```

In simple words for `BinarySearch` 
```
"0" == "০"
"1" == "๑"
"2" == "૨"
"3" == "৩"
"4" == "৪"
etc
"14" == "೧೪" == "๑৪"
```
Looks weird.

Can anybody explain this behavior? Or is it a bug?

### Reproduction Steps

Use provided links on sharplab.io

### Expected behavior

According documentation `IndexOf` and `BinarySearch` methods should return negative values when a search item is not present at a collection or an array. But there are strange cases with some sort of unicode characters when results with methods inconsistent

### Actual behavior

According documentation `IndexOf` and `BinarySearch` methods should return negative values when a search item is not present at a collection or an array. But there are strange cases with some sort of unicode characters when results with methods inconsistent

**Comment by huoyaoyuan** [comment]
`BinarySearch` uses `IComparable` implementation if available:

https://github.com/dotnet/runtime/blob/7543b056d8ae0654f266b6298e8c14c0fb69f871/src/coreclr/System.Private.CoreLib/src/System/Collections/Generic/ArraySortHelper.CoreCLR.cs#L26-L29

The `IComparable` implementation of string uses current culture:

https://github.com/dotnet/runtime/blob/7543b056d8ae0654f266b6298e8c14c0fb69f871/src/libraries/System.Private.CoreLib/src/System/String.Comparison.cs#L521-L524

In contrast, `Contains` and `IndexOf` uses `IEquatable` implementation, which doesn't use culture on string.

The difference on current-culture-by-default is a known pain on string.

**Comment by makeman-p81** [comment]
@huoyaoyuan
Than for details! Sure
```
Console.WriteLine("೧೪".CompareTo("12")); // 1
Console.WriteLine("೧೪".CompareTo("14")); // 0
```
But seems that `BinarySort` should be synced with `Contains`, `IndexOf` and `OrderBy`.

In my case `BinarySort` used in an ordered by `Linq` list with default implicit comparison for better search performance, but sometimes it causes unexpected results like described upper.

**Comment by huoyaoyuan** [comment]
The real problem is that `IComparable` and `IEquatable` implementation are out of sync. The other methods are depending on these two interfaces. `BinarySort` and `OrderBy` are both using `IComparable`.

As a workaround, you can always specify `String(Comparer/Comparison).(Ordinal/CurrentCulture)`.

**Comment by wstaelens** [comment]
maybe related: https://github.com/dotnet/runtime/discussions/93961

**Comment by makeman-p81** [comment]
@huoyaoyuan
Understand you. But actually, in real cases it is dangerous hidden behavior...

For example, there is a competition in text compression area [Hutter Prize](http://prize.hutter1.net/) which attract me.

At a first stage my algorithm split text on unique tokens via regexes and count rate for each. It is implemented like `Dictionary<string, int>` where the key is a token, and the value is a rate.

Then for next stages the algorithm order tokens into List to attach index (zero-based offset) for them and it is expected that each token is unique!

My approach works perfectly for little text data, but on a large set weird collisions start to appear, because for default `BinarySearch` and `OrderBy` implementations the uniqueness of tokens is no longer respected.

Actually, we have hidden default string comparison inconsistence between:

from the one side
 `== and != opertors`, `string dictionary keys`,  `Contains`, `IndexOf` 
from another
`BinarySearch` and `OrderBy`

**Comment by eiriktsarpalis** [comment]
This is not a collections issue, per @huoyaoyuan's comment the problem is an inconsistency between the IEquatable and IComparable implementations for string:
```C#
Console.WriteLine("೧೪".CompareTo("14") == 0); // True
Console.WriteLine("೧೪".Equals("14")); // False
```
While equality should be implied from comparison, I suspect this couldn't be changed for fear of breaking changes. The recommendation is to simply adopt ordinal comparison when working with string collections:
```C#
var cmp = StringComparer.Ordinal;
Console.WriteLine(cmp.Compare("೧೪", "14") == 0); // False
Console.WriteLine(cmp.Equals("೧೪", "14")); // False
```

**Comment by tarekgh** [comment]
@huoyaoyuan is correct that the `BinarySearch` is by default using the `IComparer` which will compare the strings using current culture. While `IndexOf` by default will compare the strings as ordinal and not using CurrentCulture. I agree too with @makeman-p81 this can lead to some problems. This cannot be fixed without a breaking change which can be a serious breaking. Mybe the way can help here is introduce a new analyzer catching such cases like when using `BinarySearch` will inform to use explicit comparer and when using `IndexOf` inform to use explicit `IEquatble` but we need to expose a new `IndexOf` overload that accept `IEqualityComparer`.

**Comment by makeman-p81** [comment]
Suspect that if `default culture` of string comparers for `BinarySearch` and `OrderBy` will be replaced from `Current` to `Invariant`, instead of breaking something it may automatically fix large range of Sredinger-like bugs in the world.

Because in my case inconsistence and related collisions has been detected accidentally by data.

Before reading this issue, do you believed that `Dictionary`, `IndexOf` and `BinarySearch`, `OrderBy` compare strings by default in different ways?

Usually _culture attentive thing_ are `DateTime`, `double`, etc... But `simple strings` has been a surprise even for my 10+ years of experience with C#.

Looks that this sort of programmer's mistakes cause accidentally crashes of starships 🚀

Seriously, possible, this problem deserves more attention...

**Comment by eiriktsarpalis** [comment]
> Before reading this issue, do you believed that `Dictionary`, `IndexOf` and `BinarySearch`, `OrderBy` compare strings by default in different ways?

Yes. `IndexOf` and `Dictionary` use _equality comparison_ whereas `BinarySearch` and `OrderBy` use _order comparison_. While these are related they are also subtly different.

**Comment by tarekgh** [comment]
> Suspect that if default culture of string comparers for BinarySearch and OrderBy will be replaced from Current to Invariant, instead of breaking something it may automatically fix large range of Sredinger-like bugs in the world.

I doubt that. both current and invariant cultures are performing linguistic comparisons which are very close and most of the time will not notice any differences.

**Comment by makeman-p81** [comment]
@eiriktsarpalis 
I don't mean intuitive sustentation that "CASE" and "case" may be equals, but that "14" may be equals "೧೪" into default English culture. Do anybody really suspect about this?

**Comment by makeman-p81** [comment]
@jkotas @eiriktsarpalis 
what are you think about suggestion to replace `Current` culture to `Invariant` into default comparers for BinarySearch and OrderBy?

**Comment by makeman-p81** [comment]
Guys, thank you for clarifications!

A lesson for me:
Sometimes implicit things by default lead to unexpected behavior, therefore you should specify explicit behavior to achieve desired results.

**Comment by MichalPetryka** [comment]
> switching from NLS to ICU broke already a lot of applications because characters suddenly had zero weight

Those apps would have already been broken though if somebody would use them on Linux.
