### ISSUE TITLE
Discrepancies in reported primitive type size

### ISSUE THREAD

**Issue by Yefim-Gulkovich** [dotnet/runtime#95366]
### Description

I've used two diverse ways to obtain the size of System.Char and System.Boolean. The second way produces wrong results.

### Reproduction Steps

1.
System.Console.WriteLine("A {0} is {1} byte(s)", typeof(char).Name, sizeof(char));    // char is 2 byte(s)
System.Console.WriteLine("A {0} is {1} byte(s)", typeof(bool).Name, sizeof(bool));   // bool is 1 byte(s)

2.1.
int typeSize = Marshal.SizeOf(typeof(char));

CSharpCodeProvider provider = new CSharpCodeProvider();
string typeName = provider.GetTypeOutput(new CodeTypeReference(type));

Console.WriteLine("{0} is {1} byte(s)", typeName, typeSize);  // char is 1 byte(s)

2.2.
...
Console.WriteLine("{0} is {1} byte(s)", typeName, typeSize);  // bool is 4 byte(s)

### Expected behavior

Both ways ought to produce the same results.

### Actual behavior

The second way produces wrong result.

### Configuration

• The code is running on the latest version of .NET.
• Windows 11.
• x64.
• No, I do not.
• I am using Visual Studio Community 2022.

**Comment by jkotas** [comment]
`sizeof` returns the managed size of the type. `Marshal.SizeOf` returns the size of the unmanaged marshalled instance of the type. These two sizes can differ - it is mentioned in the [`Marshal.SizeOf` documentation](https://learn.microsoft.com/dotnet/api/system.runtime.interopservices.marshal.sizeof).
