### ISSUE TITLE
[wasi] `System.Globalization.Tests` AOT build fails with `LLVM ERROR: out of memory` on Windows

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#95365]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=481587
Build error leg or test failing: System.Globalization.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/95146

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "LLVM ERROR: out of memory.*C:.*ProxyProjectForAOTOnHelix.proj",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

From the console log:
```
error : Failed to compile C:\helix\work\workitem\e\wasm_build\obj\wasm\for-build\aot-instances.dll.bc -> C:\helix\work\workitem\e\wasm_build\obj\wasm\for-build\aot-instances.dll.o [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : C:\helix\work\workitem\e\publish>C:\Windows\System32\chcp.com 65001 1>nul  [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : C:\helix\work\workitem\e\publish>setlocal [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : C:\helix\work\workitem\e\publish>set errorlevel=dummy  [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : C:\helix\work\workitem\e\publish>set errorlevel=  [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : C:\helix\work\workitem\e\publish>C:\helix\work\correlation\build\\wasi-sdk\\bin\clang.exe "@C:\helix\work\correlation\build\microsoft.netcore.app.runtime.wasi-wasm\runtimes\wasi-wasm\native\src\wasi-default.rsp"  "@C:\helix\work\workitem\e\wasm_build\obj\wasm\for-build\wasi-compile-bc.rsp" -c -o "C:\Users\ContainerAdministrator\AppData\Local\Temp\tmpmr5st5.tmp" "C:\helix\work\workitem\e\wasm_build\obj\wasm\for-build\aot-instances.dll.bc"  [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : clang version 16.0.0 [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : Target: wasm32-unknown-wasi [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : Thread model: posix [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : InstalledDir: C:/helix/work/correlation/build//wasi-sdk//bin [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error :  (in-process) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error :  "C:/helix/work/correlation/build/wasi-sdk/bin/clang.exe" -cc1 -triple wasm32-unknown-wasi -emit-obj -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name aot-instances.dll.bc -mrelocation-model static -mframe-pointer=none -ffp-contract=on -fno-rounding-math -mconstructor-aliases -target-cpu generic -fvisibility=hidden -mllvm -treat-scalable-fixed-error-as-warning -debug-info-kind=constructor -dwarf-version=4 -debugger-tuning=gdb -v -fcoverage-compilation-dir=C:/helix/work/workitem/e/publish -resource-dir C:/helix/work/correlation/build/wasi-sdk/lib/clang/16 -Oz -fdebug-compilation-dir=C:/helix/work/workitem/e/publish -ferror-limit 19 -fgnuc-version=4.2.1 -vectorize-slp -o "C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\tmpmr5st5.tmp" -x ir "C:\\helix\\work\\workitem\\e\\wasm_build\\obj\\wasm\\for-build\\aot-instances.dll.bc" [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : clang -cc1 version 16.0.0 based upon LLVM 16.0.0 default target wasm32-wasi [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : LLVM ERROR: out of memory [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : Allocation failed [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script. [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : Stack dump: [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : 0.	Program arguments: C:\\helix\\work\\correlation\\build\\\\wasi-sdk\\\\bin\\clang.exe @C:\\helix\\work\\correlation\\build\\microsoft.netcore.app.runtime.wasi-wasm\\runtimes\\wasi-wasm\\native\\src\\wasi-default.rsp @C:\\helix\\work\\workitem\\e\\wasm_build\\obj\\wasm\\for-build\\wasi-compile-bc.rsp -c -o C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\tmpmr5st5.tmp C:\\helix\\work\\workitem\\e\\wasm_build\\obj\\wasm\\for-build\\aot-instances.dll.bc [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : 1.	Code generation [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : Exception Code: 0xC000001D [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : 0x00A1FB73 <unknown module> [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : 0x7133C902 <unknown module> [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : 0x00A023A1 <unknown module> [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : 0x00E7FD3C <unknown module> [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : 0x00E7FFBC <unknown module> [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : 0x00E80133 <unknown module> [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : 0x008DE5CF <unknown module> [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : clang: error: clang frontend command failed due to signal (use -v to see invocation) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : clang version 16.0.0 [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : Target: wasm32-unknown-wasi [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : Thread model: posix [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : InstalledDir: C:/helix/work/correlation/build//wasi-sdk//bin [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
error : clang: note: diagnostic msg: Error generating preprocessed source(s) - no preprocessable inputs. [took 93.46s] [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=481587
**Error message validated:** `LLVM ERROR: out of memory.*C:.*ProxyProjectForAOTOnHelix.proj`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 11/28/2023 11:22:33 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[544686](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544686)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544686&view=ms.vss-test-web.build-test-results-tab&runId=13066120&resultId=100002)|dotnet/runtime#95402|
|[544678](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544678)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544678&view=ms.vss-test-web.build-test-results-tab&runId=13062458&resultId=100002)|dotnet/runtime#96895|
|[544646](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544646)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544646&view=ms.vss-test-web.build-test-results-tab&runId=12954838&resultId=100002)|dotnet/runtime#97216|
|[544782](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544782)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544782&view=ms.vss-test-web.build-test-results-tab&runId=12946716&resultId=100002)|dotnet/runtime#97660|
|[544045](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544045)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544045&view=ms.vss-test-web.build-test-results-tab&runId=12935132&resultId=100002)|dotnet/runtime#97604|
|[544662](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544662)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544662&view=ms.vss-test-web.build-test-results-tab&runId=12934604&resultId=100002)|dotnet/runtime#93619|
|[544814](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544814)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544814&view=ms.vss-test-web.build-test-results-tab&runId=12932804&resultId=100002)|dotnet/runtime#97651|
|[544810](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544810)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544810&view=ms.vss-test-web.build-test-results-tab&runId=12932686&resultId=100002)|dotnet/runtime#97361|
|[544798](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544798)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544798&view=ms.vss-test-web.build-test-results-tab&runId=12932324&resultId=100002)|dotnet/runtime#97643|
|[544772](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544772)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544772&view=ms.vss-test-web.build-test-results-tab&runId=12932056&resultId=100002)|dotnet/runtime#97658|
|[544575](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544575)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544575&view=ms.vss-test-web.build-test-results-tab&runId=12931754&resultId=100002)|dotnet/runtime#97640|
|[544717](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544717)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544717&view=ms.vss-test-web.build-test-results-tab&runId=12930494&resultId=100002)|dotnet/runtime#97654|
|[544681](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544681)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544681&view=ms.vss-test-web.build-test-results-tab&runId=12929368&resultId=100002)|dotnet/runtime#95543|
|[544692](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544692)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544692&view=ms.vss-test-web.build-test-results-tab&runId=12929410&resultId=100002)|dotnet/runtime#97052|
|[544677](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544677)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544677&view=ms.vss-test-web.build-test-results-tab&runId=12929294&resultId=100002)|dotnet/runtime#97589|
|[544670](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544670)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544670&view=ms.vss-test-web.build-test-results-tab&runId=12928788&resultId=100002)|dotnet/runtime#93953|
|[544190](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544190)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544190&view=ms.vss-test-web.build-test-results-tab&runId=12927456&resultId=100002)|dotnet/runtime#97632|
|[544304](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544304)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544304&view=ms.vss-test-web.build-test-results-tab&runId=12926670&resultId=100002)|dotnet/runtime#97508|
|[544584](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544584)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544584&view=ms.vss-test-web.build-test-results-tab&runId=12926396&resultId=100002)|dotnet/runtime#97559|
|[544550](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544550)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544550&view=ms.vss-test-web.build-test-results-tab&runId=12924952&resultId=100002)|dotnet/runtime#86674|
|[544478](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544478)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544478&view=ms.vss-test-web.build-test-results-tab&runId=12923324&resultId=100002)|dotnet/runtime#97644|
|[544354](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544354)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544354&view=ms.vss-test-web.build-test-results-tab&runId=12919556&resultId=100002)|dotnet/runtime#97388|
|[544295](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544295)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544295&view=ms.vss-test-web.build-test-results-tab&runId=12917740&resultId=100002)|dotnet/runtime#97637|
|[544240](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544240)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544240&view=ms.vss-test-web.build-test-results-tab&runId=12916018&resultId=100002)|dotnet/runtime#91317|
|[544273](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544273)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544273&view=ms.vss-test-web.build-test-results-tab&runId=12916610&resultId=100002)|dotnet/runtime#96910|
|[544187](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544187)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544187&view=ms.vss-test-web.build-test-results-tab&runId=12914320&resultId=100002)|dotnet/runtime#97441|
|[544167](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544167)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544167&view=ms.vss-test-web.build-test-results-tab&runId=12913078&resultId=100002)|dotnet/runtime#97559|
|[544105](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544105)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544105&view=ms.vss-test-web.build-test-results-tab&runId=12911392&resultId=100002)|dotnet/runtime#96910|
|[544091](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544091)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544091&view=ms.vss-test-web.build-test-results-tab&runId=12911208&resultId=100002)|dotnet/runtime#97340|
|[544037](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544037)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544037&view=ms.vss-test-web.build-test-results-tab&runId=12909192&resultId=100002)|dotnet/runtime#91317|
|[543656](https://dev.azure.com/dnceng-public/public/_build/results?buildId=543656)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=543656&view=ms.vss-test-web.build-test-results-tab&runId=12893542&resultId=100002)|dotnet/runtime#97592|
|[543240](https://dev.azure.com/dnceng-public/public/_build/results?buildId=543240)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=543240&view=ms.vss-test-web.build-test-results-tab&runId=12883292&resultId=100002)|dotnet/runtime#97592|
|[541985](https://dev.azure.com/dnceng-public/public/_build/results?buildId=541985)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=541985&view=ms.vss-test-web.build-test-results-tab&runId=12842158&resultId=100002)|dotnet/runtime#91317|
|[540864](https://dev.azure.com/dnceng-public/public/_build/results?buildId=540864)|dotnet/runtime|[System.Buffers.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=540864&view=ms.vss-test-web.build-test-results-tab&runId=12809036&resultId=100666)|dotnet/runtime#97441|
|[540620](https://dev.azure.com/dnceng-public/public/_build/results?buildId=540620)|dotnet/runtime|[System.Buffers.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=540620&view=ms.vss-test-web.build-test-results-tab&runId=12803174&resultId=100666)|dotnet/runtime#97391|
|[540294](https://dev.azure.com/dnceng-public/public/_build/results?buildId=540294)|dotnet/runtime|[System.Buffers.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=540294&view=ms.vss-test-web.build-test-results-tab&runId=12794078&resultId=100666)|dotnet/runtime#97391|
|[540124](https://dev.azure.com/dnceng-public/public/_build/results?buildId=540124)|dotnet/runtime|[System.Buffers.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=540124&view=ms.vss-test-web.build-test-results-tab&runId=12789898&resultId=100666)|dotnet/runtime#97441|
|[522619](https://dev.azure.com/dnceng-public/public/_build/results?buildId=522619)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=522619&view=ms.vss-test-web.build-test-results-tab&runId=12281132&resultId=100002)|dotnet/runtime#96455|
|[518255](https://dev.azure.com/dnceng-public/public/_build/results?buildId=518255)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=518255&view=ms.vss-test-web.build-test-results-tab&runId=12230318&resultId=100002)|dotnet/runtime#96455|
|[517013](https://dev.azure.com/dnceng-public/public/_build/results?buildId=517013)|dotnet/runtime|[System.Collections.Specialized.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=517013&view=ms.vss-test-web.build-test-results-tab&runId=12141294&resultId=100002)|dotnet/runtime#96455|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|5|40|

**Comment by lewing** [comment]
cc @steveisok

**Comment by steveisok** [comment]
Quite possible https://github.com/dotnet/runtime/pull/97096 will fix.
