### ISSUE TITLE
ImmutableHashSet.Contains is annotated to disallow nulls, while explicitly coded to support nulls

### ISSUE THREAD

**Issue by jnm2** [dotnet/runtime#95360]
### Description

The warning would imply that you should insert a null check before calling Contains, but that would be redundant. There is already an explicit null check in `ImmutableHashSet<T>.Contains`:

https://github.com/dotnet/runtime/blob/e07f80ac344b291b54a3fd5a333906782ab4809e/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableHashSet_1.cs#L420-L423

https://github.com/dotnet/runtime/blob/e07f80ac344b291b54a3fd5a333906782ab4809e/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableHashSet_1.cs#L668-L678

### Reproduction Steps

```cs
class C
{
    bool M(ImmutableHashSet<string> set, string? optionalParam = null)
    {
        // ⚠️ CS8604 Possible null reference argument for parameter 'item' in 'bool ImmutableHashSet<string>.Contains(string item)'.
        //                  ↓↓↓↓↓↓↓↓↓↓↓↓↓
        return set.Contains(optionalParam);
    }
}
```

### Expected behavior

Maybe-null expressions accepted without warning.

### Actual behavior

Maybe-null expressions cause a warning.

**Comment by stephentoub** [comment]
> ImmutableHashSet supports adding null elements

But you've used a non-nullable string as T (i.e. `ImmutableHashSet<string>` rather than `ImmutableHashSet<string?>`) and have thus said that null is explicitly outside the range of allowed values. If you change your T to be nullable, you won't get a warning.

This is the same as https://github.com/dotnet/runtime/issues/1775.

**Comment by jnm2** [comment]
Oops, I'm sorry, I quickly added the "supports adding null elements" and removed it again, but not fast enough.

Thanks for reminding me of #1775. The push to add a redundant null check still bothers me, but this was indeed considered already.

**Comment by jnm2** [comment]
If you would naturally yourself in the situation of the compiler binding to a `List<T>.Contains(object)` method, as you do with `List<T>.Contains(T)` when trying to pass a nullable expression, I think we might have gone the other direction on the decision.
