### ISSUE TITLE
lambda selection bug on newest .net sdk 

### ISSUE THREAD

**Issue by tan61** [dotnet/runtime#95375]
### Description

I am use the newest .net sdk(version=8.100), and make a Dictionary with Turple value,
I want use lambda to select the Dictionary,but the two way are not the same result,
as you can by the test code:

`Dictionary<string, (string C, string U)> dic = new();
dic["p1"] = ("c1", "u1");
dic["p2"] = ("c1", "u2");
dic["p3"] = ("c1", "u1");

//except retun one record ,but there isn't any 
var lst1=dic.Where(kvp => kvp.Key != "p1" && kvp.Value.C == "c1" && kvp.Value.U == "u1");

//retun one record as excpeted
var lst2=dic.Where(kvp => kvp.Key != "p1" && kvp.Value.Item1 == "c1" && kvp.Value.Item2 == "u1");`

### Reproduction Steps

it's easy to test it ,just make a blank prject,and run the code

### Expected behavior

lst1 is equal to lst2

### Actual behavior

lst1 is empty and lst2 is not

**Comment by huoyaoyuan** [comment]
How did you observed the difference? By output or by inspecting with debugger?

The two expressions should be compiled into exactly same code. Can you provide a simple console program to reproduce the issue?
