### ISSUE TITLE
JIT: Widespread jitstress failures with "Assertion failed 'node->OperIsLIR()'"

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#95388]
E.g. https://dev.azure.com/dnceng-public/public/_build/results?buildId=483238&view=results

```scala
05:32:58.596 Running test: JIT/Directed/cmov/Bool_And_Op_cs_d/Bool_And_Op_cs_d.dll

Assert failure(PID 24 [0x00000018], Thread: 24 [0x0018]): Assertion failed 'node->OperIsLIR()' in 'testout1:Sub_Funclet_1():int' during 'Rationalize IR' (IL size 527; hash 0x96161c08; MinOpts)

    File: /__w/1/s/src/coreclr/jit/lir.cpp Line: 1616
    Image: /root/helix/work/correlation/corerun
```

```json
{
  "ErrorMessage": "Assertion failed 'node->OperIsLIR()'",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

Introduced/exposed by #95249, cc @EgorBo 

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=483238
**Error message validated:** `Assertion failed 'node->OperIsLIR()'`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 11/29/2023 9:46:24 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[484631](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484631)|dotnet/runtime|[System.Globalization.Extensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484631&view=ms.vss-test-web.build-test-results-tab&runId=11161566&resultId=100100)||
|[483315](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483315)|dotnet/runtime|[System.Globalization.Extensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483315&view=ms.vss-test-web.build-test-results-tab&runId=11128472&resultId=100100)||
|[483238](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483238)|dotnet/runtime|[GC\\Scenarios\\DoublinkList\\dlbigleakthd\\dlbigleakthd.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483238&view=ms.vss-test-web.build-test-results-tab&runId=11126604&resultId=103949)||
|[482941](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482941)|dotnet/runtime|[GC\\API\\NoGCRegion\\Callback_Svr\\Callback_Svr.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482941&view=ms.vss-test-web.build-test-results-tab&runId=11117566&resultId=103514)|dotnet/runtime#95326|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|4|4|

**Comment by EgorBo** [comment]
Oops, I should run more outerloops on my PRs 😞 

This one is already fixed in https://github.com/dotnet/runtime/pull/95353 

the assert happens because we encounter a GT_NOP of type TYP_LONG in LIR and it's produced by fgStress64RsltMulCB (`tree->AsOp()->gtOp1 = pComp->gtNewOperNode(GT_NOP, TYP_LONG, tree->AsOp()->gtOp1);`)

**Comment by EgorBo** [comment]
Fixed by https://github.com/dotnet/runtime/pull/95353
