### ISSUE TITLE
[HTTP3] [outerloop] Requesting HTTP version 3.0 with version policy RequestVersionExact while unable to establish HTTP/3 connection

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#95413]
### Error Blob

```json
{
  "ErrorMessage": "Requesting HTTP version 3.0 with version policy RequestVersionExact while unable to establish HTTP/3 connection",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Reproduction Steps

@dotnet/ilc-contrib @dotnet/ncl PTAL

**Note**: This issue might be related to https://github.com/dotnet/runtime/issues/73290, but as I wasn't sure, I created this one so I could mark it as a `KnownBuildError` so we could track the number of hits.

- Affected PR: https://github.com/dotnet/runtime/pull/94868 via `/azp run runtime-nativeaot-outerloop`
- Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=483727
- Jobs:
  - https://dev.azure.com/dnceng-public/public/_build/results?buildId=483727&view=logs&j=1a903bec-56c1-5f69-7b57-f0ab9c1e238e&t=2fed0c68-9f2b-551e-de27-060b59e2b30c&l=70
  - https://dev.azure.com/dnceng-public/public/_build/results?buildId=483727&view=logs&j=abdbb26b-d534-5e94-28a6-1260271ac680&t=669f6d83-cb64-5444-422f-fe4972234da6
- Queues:
  - `linux-arm64 Release NativeAOT_Libs`
  - `linux-x64 Release NativeAOT_Libs`
- Log files:
  - https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-94868-merge-6a7c0f61e2f54aa0a5/System.Net.Http.Functional.Tests/3/console.4c62795f.log?helixlogtype=result
  - https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-94868-merge-77f3e8adef9f43219d/System.Net.Http.Functional.Tests/3/console.0d77b66b.log?helixlogtype=result
- Output: 
```
[FAIL] System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked
System.Net.Http.HttpRequestException : Requesting HTTP version 3.0 with version policy RequestVersionExact while unable to establish HTTP/3 connection.
---- System.OperationCanceledException : The operation was canceled.
   at System.Net.Http.HttpConnectionPool.ThrowGetVersionException(HttpRequestMessage, Int32, Exception) + 0x108
   at System.Net.Http.HttpConnectionPool.<TrySendUsingHttp3Async>d__87.MoveNext() + 0x1fc
--- End of stack trace from previous location ---
   at System.Net.Http.HttpConnectionPool.<SendWithVersionDetectionAndRetryAsync>d__89.MoveNext() + 0x614
--- End of stack trace from previous location ---
   at System.Net.Http.RedirectHandler.<SendAsync>d__4.MoveNext() + 0x194
--- End of stack trace from previous location ---
   at System.Net.Http.HttpClient.<<SendAsync>g__Core|83_0>d.MoveNext() + 0x400
--- End of stack trace from previous location ---
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.<>c__DisplayClass29_0.<<ConnectionAttemptCanceled_AuthorityNotBlocked>b__1>d.MoveNext() + 0x46c
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task) + 0x2c
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.<WhenAllOrAnyFailed>d__10.MoveNext() + 0x2c0
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.<WhenAllOrAnyFailed>d__8.MoveNext() + 0xe8
--- End of stack trace from previous location ---
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.<ConnectionAttemptCanceled_AuthorityNotBlocked>d__29.MoveNext() + 0x1a8
--- End of stack trace from previous location ---
--- End of stack trace from previous location ---
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Quic.ValueTaskSource.TryComplete(Exception) + 0x8c
   at System.Net.Quic.ValueTaskSource.<>c.<TryInitialize>b__10_0(Object obj, CancellationToken cancellationToken) + 0x7c
   at System.Threading.CancellationTokenSource.Invoke(Delegate, Object, CancellationTokenSource) + 0x94
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean) + 0x15c
   at System.Threading.CancellationTokenSource.Invoke(Delegate, Object, CancellationTokenSource) + 0x44
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean) + 0x15c
   at System.Threading.CancellationTokenSource.Invoke(Delegate, Object, CancellationTokenSource) + 0x44
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean) + 0x15c
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.<>c__DisplayClass29_1.<ConnectionAttemptCanceled_AuthorityNotBlocked>b__3(Object _, X509Certificate _, X509Chain _, SslPolicyErrors _) + 0x30
   at System.Net.Quic.QuicConnection.SslConnectionOptions.ValidateCertificate(QUIC_BUFFER*, QUIC_BUFFER*, X509Certificate2&) + 0x1bc
   at System.Net.Quic.QuicConnection.HandleEventPeerCertificateReceived(QUIC_CONNECTION_EVENT._Anonymous_e__Union._PEER_CERTIFICATE_RECEIVED_e__Struct&) + 0x2c
   at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT&) + 0x94
   at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE*, Void*, QUIC_CONNECTION_EVENT*) + 0x1a4
--- End of stack trace from previous location ---
   at System.Net.Quic.ValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16) + 0x18
   at System.Net.Quic.QuicConnection.<FinishConnectAsync>d__34.MoveNext() + 0x60c
--- End of stack trace from previous location ---
   at System.Net.Quic.QuicConnection.<<ConnectAsync>g__StartConnectAsync|2_0>d.MoveNext() + 0x168
--- End of stack trace from previous location ---
   at System.Net.Quic.QuicConnection.<<ConnectAsync>g__StartConnectAsync|2_0>d.MoveNext() + 0x480
--- End of stack trace from previous location ---
   at System.Net.Http.ConnectHelper.<ConnectQuicAsync>d__3.MoveNext() + 0x1c4
--- End of stack trace from previous location ---
   at System.Net.Http.HttpConnectionPool.<GetHttp3ConnectionAsync>d__86.MoveNext() + 0x8ec
--- End of stack trace from previous location ---
   at System.Net.Http.HttpConnectionPool.<TrySendUsingHttp3Async>d__87.MoveNext() + 0x314
--- End of stack trace from previous location ---
   at System.Net.Http.HttpConnectionPool.<SendWithVersionDetectionAndRetryAsync>d__89.MoveNext() + 0x614
--- End of stack trace from previous location ---
   at System.Net.Http.RedirectHandler.<SendAsync>d__4.MoveNext() + 0x194
--- End of stack trace from previous location ---
   at System.Net.Http.HttpClient.<<SendAsync>g__Core|83_0>d.MoveNext() + 0x140
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=483727
**Error message validated:** `Requesting HTTP version 3.0 with version policy RequestVersionExact while unable to establish HTTP/3 connection`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 11/29/2023 5:31:56 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[484823](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484823)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484823&view=ms.vss-test-web.build-test-results-tab&runId=11168346&resultId=213474)|dotnet/runtime#95370|
|[484795](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484795)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484795&view=ms.vss-test-web.build-test-results-tab&runId=11167108&resultId=210082)|dotnet/runtime#95411|
|[484712](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484712)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484712&view=ms.vss-test-web.build-test-results-tab&runId=11164988&resultId=210082)|dotnet/runtime#93220|
|[484684](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484684)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484684&view=ms.vss-test-web.build-test-results-tab&runId=11164452&resultId=130533)||
|[484685](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484685)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484685&view=ms.vss-test-web.build-test-results-tab&runId=11163706&resultId=213371)||
|[484659](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484659)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484659&view=ms.vss-test-web.build-test-results-tab&runId=11163154&resultId=213475)|dotnet/runtime#95404|
|[484656](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484656)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484656&view=ms.vss-test-web.build-test-results-tab&runId=11162806&resultId=213465)||
|[484569](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484569)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484569&view=ms.vss-test-web.build-test-results-tab&runId=11159344&resultId=210083)|dotnet/runtime#94737|
|[484361](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484361)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484361&view=ms.vss-test-web.build-test-results-tab&runId=11155136&resultId=208566)|dotnet/runtime#91229|
|[484362](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484362)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484362&view=ms.vss-test-web.build-test-results-tab&runId=11153870&resultId=210082)|dotnet/runtime#91229|
|[484357](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484357)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484357&view=ms.vss-test-web.build-test-results-tab&runId=11153784&resultId=210082)|dotnet/runtime#95426|
|[484278](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484278)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484278&view=ms.vss-test-web.build-test-results-tab&runId=11152006&resultId=213481)|dotnet/runtime#95303|
|[484240](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484240)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484240&view=ms.vss-test-web.build-test-results-tab&runId=11151264&resultId=213475)|dotnet/runtime#95404|
|[484154](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484154)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484154&view=ms.vss-test-web.build-test-results-tab&runId=11150518&resultId=167221)||
|[484167](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484167)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484167&view=ms.vss-test-web.build-test-results-tab&runId=11149840&resultId=210082)|dotnet/runtime#95426|
|[484155](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484155)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484155&view=ms.vss-test-web.build-test-results-tab&runId=11149638&resultId=209980)||
|[484159](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484159)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484159&view=ms.vss-test-web.build-test-results-tab&runId=11150130&resultId=213474)|dotnet/runtime#95384|
|[484147](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484147)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484147&view=ms.vss-test-web.build-test-results-tab&runId=11150052&resultId=213474)|dotnet/runtime#95425|
|[484062](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484062)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484062&view=ms.vss-test-web.build-test-results-tab&runId=11146832&resultId=210074)||
|[484007](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484007)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=484007&view=ms.vss-test-web.build-test-results-tab&runId=11145416&resultId=213474)|dotnet/runtime#94684|
|[483997](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483997)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483997&view=ms.vss-test-web.build-test-results-tab&runId=11145244&resultId=203805)|dotnet/runtime#95384|
|[483950](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483950)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483950&view=ms.vss-test-web.build-test-results-tab&runId=11143852&resultId=210082)|dotnet/runtime#94169|
|[483889](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483889)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483889&view=ms.vss-test-web.build-test-results-tab&runId=11143046&resultId=210082)|dotnet/runtime#95416|
|[483861](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483861)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483861&view=ms.vss-test-web.build-test-results-tab&runId=11142054&resultId=210082)|dotnet/runtime#95411|
|[483851](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483851)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483851&view=ms.vss-test-web.build-test-results-tab&runId=11142022&resultId=210082)|dotnet/runtime#95324|
|[483844](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483844)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483844&view=ms.vss-test-web.build-test-results-tab&runId=11141844&resultId=210082)|dotnet/runtime#95412|
|[483803](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483803)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483803&view=ms.vss-test-web.build-test-results-tab&runId=11140824&resultId=213474)|dotnet/runtime#94353|
|[483786](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483786)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483786&view=ms.vss-test-web.build-test-results-tab&runId=11140482&resultId=213474)|dotnet/runtime#95408|
|[483780](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483780)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483780&view=ms.vss-test-web.build-test-results-tab&runId=11140304&resultId=213474)|dotnet/runtime#95402|
|[483770](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483770)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483770&view=ms.vss-test-web.build-test-results-tab&runId=11139860&resultId=210082)|dotnet/runtime#95260|
|[483727](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483727)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483727&view=ms.vss-test-web.build-test-results-tab&runId=11139862&resultId=174267)|dotnet/runtime#94868|
|[483751](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483751)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483751&view=ms.vss-test-web.build-test-results-tab&runId=11139546&resultId=213412)|dotnet/runtime#95405|
|[483743](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483743)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483743&view=ms.vss-test-web.build-test-results-tab&runId=11139156&resultId=210082)|dotnet/runtime#95404|
|[483661](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483661)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483661&view=ms.vss-test-web.build-test-results-tab&runId=11138084&resultId=213474)|dotnet/runtime#95398|
|[483626](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483626)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483626&view=ms.vss-test-web.build-test-results-tab&runId=11137154&resultId=213474)|dotnet/runtime#95396|
|[483591](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483591)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483591&view=ms.vss-test-web.build-test-results-tab&runId=11136052&resultId=210082)|dotnet/runtime#95274|
|[483531](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483531)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ConnectionAttemptCanceled_AuthorityNotBlocked](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483531&view=ms.vss-test-web.build-test-results-tab&runId=11134118&resultId=213474)|dotnet/runtime#93220|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|36|37|37|

**Comment by jkotas** [comment]
@wfurt Do we need to disable this test when Quic is not available?

**Comment by ManickaP** [comment]
This test has gotten as far as cert validation, so seems like MsQuic is present and it's not https://github.com/dotnet/runtime/issues/73290.
More digging shows that this might have been broken by https://github.com/dotnet/runtime/pull/94211 @rzikm. The failures seem relevant.

**Comment by wfurt** [comment]
There should not be reason why this impacts only AOT, right @ManickaP? 
There is also #88832 @rzikm disabled recently.

**Comment by rzikm** [comment]
Weird enough, I can't reproduce the failure locally. I will have to dig a bit deeper.
