### ISSUE TITLE
DateTime.Parse("30.02.2023") throws System.FormatException: String '' was not recognized as a valid DateTime.

### ISSUE THREAD

**Issue by Palsskv** [dotnet/runtime#95428]
### Description

`DateTime.Parse("30.02.2023")` throws `System.FormatException: String '' was not recognized as a valid DateTime.`

Not sure whether such dates should be representable, but the exception is wrong.

### Reproduction Steps

Run `DateTime.Parse("30.02.2023")` 

### Expected behavior

`System.FormatException: String '30.02.2023' was not recognized as a valid DateTime.`

### Actual behavior

`System.FormatException: String '' was not recognized as a valid DateTime.`

**Comment by tarekgh** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/95331
