### ISSUE TITLE
Run single test using docker image

### ISSUE THREAD

**Issue by verdie-g** [dotnet/runtime#95436]
In [docs/workflow/testing/libraries/testing.md](https://github.com/dotnet/runtime/blob/main/docs/workflow/testing/libraries/testing.md?plain=1#L82) it states that  `dotnet build` should be used to run a single library/test but it doesn't seem to be available in the docker image. Is this scenario supported by the docker image?

**Comment by vcsjones** [comment]
If you mean run a single library in a Codespace, use `dotnet.sh` instead of `dotnet`.

Like `dotnet.sh build /t:Test /p:XUnitOptions="-class Test.ClassUnderTests"`

**Comment by verdie-g** [comment]
Oh thanks. Would it make sense to replace `dotnet` with `dotnet.sh` in the doc or most devs use the former?

**Comment by ViktorHofer** [comment]
`dotnet` works well if it's installed globally on the machine. Right now that should be case for most devs as we depend on the stable 8.0.100 SDK. We encourage devs to install the required SDK on their machines for optimal tooling support, i.e. VS and VSCode.

`dotnet.sh` either uses the globally installed SDK (if the version matches) or downloads the SDK and puts it into the repository under the `.dotnet` folder (repo local SDK).

**Comment by verdie-g** [comment]
So what are the recommendations `dotnet.sh` VS global `dotnet`?

cc @ViktorHofer

**Comment by ViktorHofer** [comment]
If the machine doesn't have the required (specified in the repo's global.json) SDK installed, use dotnet.cmd/sh, otherwise use `dothet` on the path.
