### ISSUE TITLE
FileStream(path, FileMode.Open) trying to create file

### ISSUE THREAD

**Issue by montella1507** [dotnet/runtime#95447]
### Description
We have .NET Core API application with this code
```

             bool fileExists = global::System.IO.File.Exists(filePath);
                if (fileExists)
                {
                    var stream = new FileStream(filePath, FileMode.Open);
                    return File(stream, "application/octet-stream", filename);
                }
```
But we are getting random exception which does not make sense (sorry i have this only as a picture):
<img width="878" alt="image" src="https://github.com/dotnet/core/assets/10418323/6d178444-d98f-41b6-840e-12264ada654c">

As you can see. There is SafeFileHandle.CreateFile called, despite of the FileMode.Open being used. 

It should have never tried to create a file with  FileMode.Open. It should have thrown the System.IO.NotFoundException.

It should have tried to create file only when FileMode.OpenOrCreate is used...

Another strange thing is... there is "unix" enum in callstack.. but it runs on windows platform. 

### Configuration
.NET 7
WIndowsServer 2019

### Regression?
Not sure

**Comment by adamsitnik** [comment]
Hi @montella1507 

> As you can see. There is SafeFileHandle.CreateFile called, despite of the FileMode.Open being used.

This is just an implementation detail, to tell the long story short the sys-call that .NET uses for opening files is called `CreateFileW` and our helper method is also called that way. But it allows for both opening an existing files, creating new ones, truncating files etc.

> Another strange thing is... there is "unix" enum in callstack.. but it runs on windows platform.

This is also implementation detail, we share code between Windows and Unix implementations and in that case the Windows implementation simply ignores the Unix arguments.

> It should have thrown the System.IO.NotFoundException.

It throws the right exception, which tells you that given file is used by other process. When opening a file on Windows you need to specify how you want to share the file with others. You can let them read the file, write to it, delete it or none or all of the above. In this particular case some other process/thread has opened the file and not allowed for access that you have requested.

https://github.com/dotnet/runtime/blob/ff6b26f0474698ee2fafd3639069c5ef0cc2d9e5/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.cs#L120-L121

https://github.com/dotnet/runtime/blob/ff6b26f0474698ee2fafd3639069c5ef0cc2d9e5/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.cs#L16

So `new FileStream(filePath, FileMode.Open)` maps to "I want to read or write to the file and let others just read from it".

You can most likely fix it by specifying that you want to just  read and let others reading as well.

```diff
- new FileStream(filePath, FileMode.Open);
+ new FileStream(filePath, FileMode.Open, FileAccess.Read, FileShare.Read);
```

Or simply use `File.OpenRead(path)` which does exactly that:

https://github.com/dotnet/runtime/blob/ff6b26f0474698ee2fafd3639069c5ef0cc2d9e5/src/libraries/System.Private.CoreLib/src/System/IO/File.cs#L615-L616

if that does not solve the problem you need to figure out who is opening the file and what kind of lock they request. If it's our own code, then you need to specify `FileShare.Read` as well.
