### ISSUE TITLE
build runtime faild  Failed to build "CoreCLR component".

### ISSUE THREAD

**Issue by dreamxgn** [dotnet/runtime#95449]
### Description

  /home/zhangqiang/proj/net/runtime/src/coreclr/pal/src/arch/amd64/context2.S:183:5: error: instruction requires: AVX-512 BW ISA
      kmovq k6, qword ptr [rdi + ((6*8)+8 +2 +2 +2 +2 +2 +2 +4 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +(4*8)+(24*16)+96 +(16*26)+8 +8 +8 +8 +8 +8 +8 +8 +(16*16) + 6 * 8)]
      ^
  /home/zhangqiang/proj/net/runtime/src/coreclr/pal/src/arch/amd64/context2.S:184:5: error: instruction requires: AVX-512 BW ISA
      kmovq k7, qword ptr [rdi + ((6*8)+8 +2 +2 +2 +2 +2 +2 +4 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +(4*8)+(24*16)+96 +(16*26)+8 +8 +8 +8 +8 +8 +8 +8 +(16*16) + 7 * 8)]
      ^
  pal/src/CMakeFiles/coreclrpal.dir/build.make:1236: recipe for target 'pal/src/CMakeFiles/coreclrpal.dir/arch/amd64/context2.S.o' failed
  make[2]: *** [pal/src/CMakeFiles/coreclrpal.dir/arch/amd64/context2.S.o] Error 1
  make[2]: *** Waiting for unfinished jobs....
  CMakeFiles/Makefile2:2267: recipe for target 'pal/src/CMakeFiles/coreclrpal.dir/all' failed
  make[1]: *** [pal/src/CMakeFiles/coreclrpal.dir/all] Error 2
  make[1]: *** Waiting for unfinished jobs....
  [ 46%] Built target cee_dac
  [ 54%] Built target cee_wks_core
  Makefile:135: recipe for target 'all' failed
  make: *** [all] Error 2
  ~/proj/net/runtime/src/coreclr
  Failed to build "CoreCLR component".
/home/zhangqiang/proj/net/runtime/src/coreclr/runtime.proj(94,5): error MSB3073: 命令“"/home/zhangqiang/proj/net/runtime/src/coreclr/build-runtime.sh" -x64 -debug -os linux -outputrid linux-x64”已退出，代码为 2。

生成失败。

/home/zhangqiang/proj/net/runtime/src/coreclr/runtime.proj(94,5): error MSB3073: 命令“"/home/zhangqiang/proj/net/runtime/src/coreclr/build-runtime.sh" -x64 -debug -os linux -outputrid linux-x64”已退出，代码为 2。
    0 个警告
    1 个错误

### Reproduction Steps

  /home/zhangqiang/proj/net/runtime/src/coreclr/pal/src/arch/amd64/context2.S:183:5: error: instruction requires: AVX-512 BW ISA
      kmovq k6, qword ptr [rdi + ((6*8)+8 +2 +2 +2 +2 +2 +2 +4 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +(4*8)+(24*16)+96 +(16*26)+8 +8 +8 +8 +8 +8 +8 +8 +(16*16) + 6 * 8)]
      ^
  /home/zhangqiang/proj/net/runtime/src/coreclr/pal/src/arch/amd64/context2.S:184:5: error: instruction requires: AVX-512 BW ISA
      kmovq k7, qword ptr [rdi + ((6*8)+8 +2 +2 +2 +2 +2 +2 +4 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +(4*8)+(24*16)+96 +(16*26)+8 +8 +8 +8 +8 +8 +8 +8 +(16*16) + 7 * 8)]
      ^
  pal/src/CMakeFiles/coreclrpal.dir/build.make:1236: recipe for target 'pal/src/CMakeFiles/coreclrpal.dir/arch/amd64/context2.S.o' failed
  make[2]: *** [pal/src/CMakeFiles/coreclrpal.dir/arch/amd64/context2.S.o] Error 1
  make[2]: *** Waiting for unfinished jobs....
  CMakeFiles/Makefile2:2267: recipe for target 'pal/src/CMakeFiles/coreclrpal.dir/all' failed
  make[1]: *** [pal/src/CMakeFiles/coreclrpal.dir/all] Error 2
  make[1]: *** Waiting for unfinished jobs....
  [ 46%] Built target cee_dac
  [ 54%] Built target cee_wks_core
  Makefile:135: recipe for target 'all' failed
  make: *** [all] Error 2
  ~/proj/net/runtime/src/coreclr
  Failed to build "CoreCLR component".
/home/zhangqiang/proj/net/runtime/src/coreclr/runtime.proj(94,5): error MSB3073: 命令“"/home/zhangqiang/proj/net/runtime/src/coreclr/build-runtime.sh" -x64 -debug -os linux -outputrid linux-x64”已退出，代码为 2。

生成失败。

/home/zhangqiang/proj/net/runtime/src/coreclr/runtime.proj(94,5): error MSB3073: 命令“"/home/zhangqiang/proj/net/runtime/src/coreclr/build-runtime.sh" -x64 -debug -os linux -outputrid linux-x64”已退出，代码为 2。
    0 个警告
    1 个错误

### Expected behavior

  /home/zhangqiang/proj/net/runtime/src/coreclr/pal/src/arch/amd64/context2.S:183:5: error: instruction requires: AVX-512 BW ISA
      kmovq k6, qword ptr [rdi + ((6*8)+8 +2 +2 +2 +2 +2 +2 +4 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +(4*8)+(24*16)+96 +(16*26)+8 +8 +8 +8 +8 +8 +8 +8 +(16*16) + 6 * 8)]
      ^
  /home/zhangqiang/proj/net/runtime/src/coreclr/pal/src/arch/amd64/context2.S:184:5: error: instruction requires: AVX-512 BW ISA
      kmovq k7, qword ptr [rdi + ((6*8)+8 +2 +2 +2 +2 +2 +2 +4 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +(4*8)+(24*16)+96 +(16*26)+8 +8 +8 +8 +8 +8 +8 +8 +(16*16) + 7 * 8)]
      ^
  pal/src/CMakeFiles/coreclrpal.dir/build.make:1236: recipe for target 'pal/src/CMakeFiles/coreclrpal.dir/arch/amd64/context2.S.o' failed
  make[2]: *** [pal/src/CMakeFiles/coreclrpal.dir/arch/amd64/context2.S.o] Error 1
  make[2]: *** Waiting for unfinished jobs....
  CMakeFiles/Makefile2:2267: recipe for target 'pal/src/CMakeFiles/coreclrpal.dir/all' failed
  make[1]: *** [pal/src/CMakeFiles/coreclrpal.dir/all] Error 2
  make[1]: *** Waiting for unfinished jobs....
  [ 46%] Built target cee_dac
  [ 54%] Built target cee_wks_core
  Makefile:135: recipe for target 'all' failed
  make: *** [all] Error 2
  ~/proj/net/runtime/src/coreclr
  Failed to build "CoreCLR component".
/home/zhangqiang/proj/net/runtime/src/coreclr/runtime.proj(94,5): error MSB3073: 命令“"/home/zhangqiang/proj/net/runtime/src/coreclr/build-runtime.sh" -x64 -debug -os linux -outputrid linux-x64”已退出，代码为 2。

生成失败。

/home/zhangqiang/proj/net/runtime/src/coreclr/runtime.proj(94,5): error MSB3073: 命令“"/home/zhangqiang/proj/net/runtime/src/coreclr/build-runtime.sh" -x64 -debug -os linux -outputrid linux-x64”已退出，代码为 2。
    0 个警告
    1 个错误

### Actual behavior

  /home/zhangqiang/proj/net/runtime/src/coreclr/pal/src/arch/amd64/context2.S:183:5: error: instruction requires: AVX-512 BW ISA
      kmovq k6, qword ptr [rdi + ((6*8)+8 +2 +2 +2 +2 +2 +2 +4 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +(4*8)+(24*16)+96 +(16*26)+8 +8 +8 +8 +8 +8 +8 +8 +(16*16) + 6 * 8)]
      ^
  /home/zhangqiang/proj/net/runtime/src/coreclr/pal/src/arch/amd64/context2.S:184:5: error: instruction requires: AVX-512 BW ISA
      kmovq k7, qword ptr [rdi + ((6*8)+8 +2 +2 +2 +2 +2 +2 +4 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +(4*8)+(24*16)+96 +(16*26)+8 +8 +8 +8 +8 +8 +8 +8 +(16*16) + 7 * 8)]
      ^
  pal/src/CMakeFiles/coreclrpal.dir/build.make:1236: recipe for target 'pal/src/CMakeFiles/coreclrpal.dir/arch/amd64/context2.S.o' failed
  make[2]: *** [pal/src/CMakeFiles/coreclrpal.dir/arch/amd64/context2.S.o] Error 1
  make[2]: *** Waiting for unfinished jobs....
  CMakeFiles/Makefile2:2267: recipe for target 'pal/src/CMakeFiles/coreclrpal.dir/all' failed
  make[1]: *** [pal/src/CMakeFiles/coreclrpal.dir/all] Error 2
  make[1]: *** Waiting for unfinished jobs....
  [ 46%] Built target cee_dac
  [ 54%] Built target cee_wks_core
  Makefile:135: recipe for target 'all' failed
  make: *** [all] Error 2
  ~/proj/net/runtime/src/coreclr
  Failed to build "CoreCLR component".
/home/zhangqiang/proj/net/runtime/src/coreclr/runtime.proj(94,5): error MSB3073: 命令“"/home/zhangqiang/proj/net/runtime/src/coreclr/build-runtime.sh" -x64 -debug -os linux -outputrid linux-x64”已退出，代码为 2。

生成失败。

/home/zhangqiang/proj/net/runtime/src/coreclr/runtime.proj(94,5): error MSB3073: 命令“"/home/zhangqiang/proj/net/runtime/src/coreclr/build-runtime.sh" -x64 -debug -os linux -outputrid linux-x64”已退出，代码为 2。
    0 个警告
    1 个错误

### Other information

  /home/zhangqiang/proj/net/runtime/src/coreclr/pal/src/arch/amd64/context2.S:183:5: error: instruction requires: AVX-512 BW ISA
      kmovq k6, qword ptr [rdi + ((6*8)+8 +2 +2 +2 +2 +2 +2 +4 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +(4*8)+(24*16)+96 +(16*26)+8 +8 +8 +8 +8 +8 +8 +8 +(16*16) + 6 * 8)]
      ^
  /home/zhangqiang/proj/net/runtime/src/coreclr/pal/src/arch/amd64/context2.S:184:5: error: instruction requires: AVX-512 BW ISA
      kmovq k7, qword ptr [rdi + ((6*8)+8 +2 +2 +2 +2 +2 +2 +4 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +(4*8)+(24*16)+96 +(16*26)+8 +8 +8 +8 +8 +8 +8 +8 +(16*16) + 7 * 8)]
      ^
  pal/src/CMakeFiles/coreclrpal.dir/build.make:1236: recipe for target 'pal/src/CMakeFiles/coreclrpal.dir/arch/amd64/context2.S.o' failed
  make[2]: *** [pal/src/CMakeFiles/coreclrpal.dir/arch/amd64/context2.S.o] Error 1
  make[2]: *** Waiting for unfinished jobs....
  CMakeFiles/Makefile2:2267: recipe for target 'pal/src/CMakeFiles/coreclrpal.dir/all' failed
  make[1]: *** [pal/src/CMakeFiles/coreclrpal.dir/all] Error 2
  make[1]: *** Waiting for unfinished jobs....
  [ 46%] Built target cee_dac
  [ 54%] Built target cee_wks_core
  Makefile:135: recipe for target 'all' failed
  make: *** [all] Error 2
  ~/proj/net/runtime/src/coreclr
  Failed to build "CoreCLR component".
/home/zhangqiang/proj/net/runtime/src/coreclr/runtime.proj(94,5): error MSB3073: 命令“"/home/zhangqiang/proj/net/runtime/src/coreclr/build-runtime.sh" -x64 -debug -os linux -outputrid linux-x64”已退出，代码为 2。

生成失败。

/home/zhangqiang/proj/net/runtime/src/coreclr/runtime.proj(94,5): error MSB3073: 命令“"/home/zhangqiang/proj/net/runtime/src/coreclr/build-runtime.sh" -x64 -debug -os linux -outputrid linux-x64”已退出，代码为 2。
    0 个警告
    1 个错误

**Comment by dreamxgn** [comment]
[ 41%] Built target eventpipe_objs
/home/zhangqiang/proj/net/runtime/src/coreclr/pal/src/arch/amd64/context2.S:141:5: error: instruction requires: AVX-512 ISA
    vinsertf64x4 zmm0, zmm0, ymmword ptr [rdi + ((6*8)+8 +2 +2 +2 +2 +2 +2 +4 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +8 +(4*8)+(24*16)+96 +(16*26)+8 +8 +8 +8 +8 +8 +8 +8 +(16*16)+(8*8) + 0 * 32)], 1

**Comment by huoyaoyuan** [comment]
What's your distro and compiler tools version?

**Comment by dreamxgn** [comment]
> What's your distro and compiler tools version?

os : ubuntu 18.04
cmake version 3.28.0-rc5
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
I don't know  something cause this wrong

**Comment by dreamxgn** [comment]
using docker ,it’s works
