### ISSUE TITLE
The character filter in HTTP StatusDescription is incorrect or there is a problem with the language pack.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#95454]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/The-character-filter-in-HTTP-StatusDescr/10470402)._

---
The .net framework Korean language pack is installed.  
The default error message from the .net framework is contained in value.StatusDescription.  
decompiled code screen at System.ServiceModel.dll!System.ServiceModel.Channels.HttpOutput.ListenerResponseHttpOutput.PrepareHttpSend(System.ServiceModel.Channels.Message message)  
![image](https://github.com/dotnet/runtime/assets/32671551/4a6c530a-e9ec-49fe-8655-6a4c4bcd4f6e)
What it means is "This service does not support WebSocket connections."

The code that appears to be a filter in System.dll!System.Net.HttpListenerResponse.StatusDescription.set(string value) throws an exception.  
![image](https://github.com/dotnet/runtime/assets/32671551/1626230e-7798-4b40-9e05-8836d9105808)
Strangely, the error type changes to ArgumentException.

---
#### Feedback Bot on 9/20/2023, 09:46 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ManickaP** [comment]
Closing, explained in comment above.
