### ISSUE TITLE
NativeAOT: Memset/Memcpy helpers don't throw NRE

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#95517]
Compile the following program and run:
```cs
static unsafe void Main(string[] args)
{
    Unsafe.InitBlock(null, 0, 1000);
}
```
CoreCLR:
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
```
NativeAOT:
```
no exception, exits.
```

I assume this is what these comments mean: https://github.com/dotnet/runtime/blob/3e551673a1215a3fdad2a38b4c406895ef29703c/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/JitHelper.cs#L118-L123
so I decided to file a tracking issue.

(while CoreCLR wraps memset/memcpy calls into non-inlineable/without tail calls helpers)

**Comment by filipnavara** [comment]
This can happen when unboxing tries to use `memcpy`:
```
struct X { int a, b, c, d, e, f, g, h, ... };
X? x = null;
object box = (object)x;
int val = (X)box;
```

Instead of getting a `NullReferenceException` it results in a crash inside `memcpy` with null dereference that is practically undebuggable (no stack trace available due to native code optimizations).
