### ISSUE TITLE
[Default interfaces] Interfaces implemented by arrays

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#9552]
The way default interface methods got implemented in CoreCLR likely means we can't add default interface methods to any of the generic interfaces implemented by arrays.

**Comment by mangod9** [comment]
Hi @MichalStrehovsky is this still an issue post .net 5? Thx

**Comment by MichalStrehovsky** [comment]
Yes, but since this only affects interfaces that are 100% under our control, we can fix this if/when this becomes an issue (i.e. the libraries team decides it wants to add new methods to e.g. `ICollection<T>`).
