### ISSUE TITLE
ambiguous call on 'OptionsBuilderExtensions'

### ISSUE THREAD

**Issue by mm6502** [dotnet/runtime#95524]
target runtime: net6

I am trying to validate Configuration on application start:
```
        services.AddOptions<RenderReportuSampleJobConfiguration>()
            .BindConfiguration(nameof(RenderReportuSampleJob))
            .ValidateDataAnnotations()
            .ValidateOnStart(); // ambiguous method
```
and I am getting error:
```
CS0433: The type 'OptionsBuilderExtensions' exists in both 'Microsoft.Extensions.Hosting, Version=6.0.0.0,
Culture=neutral, PublicKeyToken=adb9793829ddae601 and 'Microsoft.Extensions.Options, Version=8.0.0.0,
Culture=neutral, PublicKeyToken=adb9793829ddae60'
```

How can I resolve this? Upgrading to net8 is not an option atm. The other reference comes from third party 
library which I need to use, and I have no control over. 

In the .Net Framework I would just alias the library reference. Can it be done in net6?

**Comment by tarekgh** [comment]
How did you get the v8 `Microsoft.Extensions.Options` reference into your project in the first place? 

Can you try manually referencing Microsoft.Extensions.Hosting v8.0.0 in your project and see if it will help?

CC @ericstj @steveharter

**Comment by mm6502** [comment]
> How did you get the v8 Microsoft.Extensions.Options reference into your project in the first place?

Easily. Just added package reference:
```
dotnet add package Microsoft.Extensions.Options
```
Without specifying version, it picks up the v8.0.0. 

> Can you try manually referencing Microsoft.Extensions.Hosting v8.0.0 in your project and see if it will help?

Doh. Yes. This helped. Thanks.

**Comment by ericstj** [comment]
This is an expected (and unfortunate) side-effect when we push types down.  We can't make the assembly lower in the stack reference the new version of the package the type was moved from.  Updating both when you see this error is the right thing to do.
