### ISSUE TITLE
Inconsistent CSharpCodeProvider.GenerateCodeFromCompileUnit output between net472 and net6/7/8

### ISSUE THREAD

**Issue by sungam3r** [dotnet/runtime#95553]
### Description

See https://github.com/PublicApiGenerator/PublicApiGenerator/issues/301

### Reproduction Steps

See https://github.com/PublicApiGenerator/PublicApiGenerator/issues/301 and https://github.com/PublicApiGenerator/PublicApiGenerator/pull/339

To reproduce this issue one may comment line
`gennedClass = Regex.Replace(gennedClass, @$"{Environment.NewLine}\s+;{Environment.NewLine}", ";" + Environment.NewLine); // bug-fix for https://github.com/PublicApiGenerator/PublicApiGenerator/issues/301` from `CodeNormalizer.cs` file and then run `Should_Render_Semicolon_Properly_2` test on NET472 TFM from https://github.com/PublicApiGenerator/PublicApiGenerator/pull/339 

### Expected behavior

Printing C# code should provide the same output for NET6/NET7/NET472 

```
public interface Interface2
{
    void ConfigureMapping<T, U>()
        where T :  class;
}
```

### Actual behavior

Printing C# code now provides correct output only for not NET RAMEWORK targets 

```
public interface Interface2
{
    void ConfigureMapping<T, U>()
        where T :  class;
}
```

For NET472 it provides different code (with semicolon on new line) like
```
public interface Interface2
{
    void ConfigureMapping<T, U>()
        where T :  class
    ;
}
```

**Comment by cston** [comment]
Closing since this is a style difference, and because the library is effectively archived - see [README.md](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.CSharp/README.md).
