### ISSUE TITLE
[OCSP Stapling] OCSP Reponse has expired in .NET Linux

### ISSUE THREAD

**Issue by cdlliuy** [dotnet/runtime#95567]
### Description

Running on 7.0.14 version

We opened https://github.com/dotnet/runtime/issues/89907 previously for the invalid ocsp response when the application is started. 
A fix is made, but however it is not backported to .NET7.0.14 version yet.

Now, we met another OCSP expired failure on a long-running application instance which ran for about 10 days: 

```
curl --cert-status --connect-timeout 10 <host>
Exception: curl: (91) OCSP response has expired 
```

This failure didn't observed on all long-running instances, but just a bunch of them.

Per previous discussion in https://github.com/dotnet/runtime/issues/89907#issuecomment-1665979637,  I wonder whether an invalid OCSP response was returned during the re-new operation, then caused this issue. 

Can anyone help to take a further investigation on this? 

### Reproduction Steps

See above

### Expected behavior

See above

### Actual behavior

See above

**Comment by rzikm** [comment]
@cdlliuy  Please see https://github.com/dotnet/runtime/issues/89907#issuecomment-1697080508. I believe there should be no problem with servicing the 7.0 release with the fix if you provide us the business justification.

**Comment by karelz** [comment]
Also, keep in mind that 7.0 will be out of support in May - https://github.com/dotnet/core/blob/main/releases.md
I expect your 8.0 update is in progress, isn't it?
The earliest we can get 7.0 servicing is February if I am not mistaken - that leaves you with 3 month with the fix, before it goes out of support. We can make it happen with the right business justification.

**Comment by vcsjones** [comment]
>  I don't see any provision for checking expiration. Perhapses @vcsjones can comment on.

It's _possible_ if the CA itself is serving expired OCSP stapled data. One of the things that `X509DecodeOcspToExpiration` does is make sure the response's expiration is valid. If it isn't, then it errors, but the previous issue is that the error was basically ignored. This doesn't seem _likely_ to me though, as CAs have a strong incentive to never return an expired OCSP response.

> And is you expiration local time or UTC?

OCSP (and X.509 in general) should be doing everything in UTC.

**Comment by cdlliuy** [comment]
> Also is it possible some of the failing systems have incorrect time @cdlliuy? And is you expiration local time or UTC?

I believe the failing system should have the same time as well.  We are running .NET application within a container hosted on Kubernetes cluster ,  so all of the containers are configured to use the same timestamp.

**Comment by cdlliuy** [comment]
> Also, keep in mind that 7.0 will be out of support in May - https://github.com/dotnet/core/blob/main/releases.md I expect your 8.0 update is in progress, isn't it? The earliest we can get 7.0 servicing is February if I am not mistaken - that leaves you with 3 month with the fix, before it goes out of support. We can make it happen with the right business justification.

Thanks for the reminder.  I will check further on the .NET 8 migration schedule for our service.

**Comment by cdlliuy** [comment]
> I don't know if backport would be sufficient. #90200 added checks for invalid responses but I don't see any provision for checking expiration. Perhapses @vcsjones can comment on.

@wfurt   @vcsjones ,   if  #90200 is not sufficient for this issue, can you help to dive down for a proper fix. Thanks !

**Comment by karelz** [comment]
@cdlliuy it does not make sense to start the backport without strong business case justifying the backport. Let's sort that out first please. Feel free to ping me on Teams.

**Comment by wfurt** [comment]
Can you perhaps get packet capture of the successful and failing session @cdlliuy? Hopefully we would see what is being sent.

**Comment by danmoseley** [comment]
Note that 7.0 is now only servicing security issues as it's within 6 months of EOL.

https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

**Comment by cdlliuy** [comment]
Thanks for reminder.  We have plan to kick off the .NET8 migration soon, so not insist to any fix of backport.

However, per previous discussion, the issue may not only in .NET7 .   It might happen in .NET8 path as well.  So need your further investigation.

@wfurt ,  sorry,  the broken system has been restarted , so no reproduced log for the failed packet in hand now ..

**Comment by cdlliuy** [comment]
Update:  when upgrading to .NET8, the OSCP stabling is disabled on Linux now .. 
Is that the desired behavior? 
```
curl --cert-status --connect-timeout 10 -vvv <target-url>
...
*  SSL certificate verify ok.
* No OCSP response received
* Closing connection 0
* TLSv1.3 (OUT), TLS alert, close notify (256):
curl: (91) No OCSP response received
```

Searching the code,  it should due to the commit:  https://github.com/dotnet/runtime/commit/43542978d7bea0f4760de4606b39d2c373bd5914
![image](https://github.com/dotnet/runtime/assets/17263036/a4914b71-6d29-440f-a133-1f7944d285b4)
in which "noOcspFetch == true" in the call stack , and the fix is added to .net8 related release only.

Prior to .net8,  i.e. .NET7,  without the explicit setting of `noOcspFetch` flag,  the below code is invoked in which noOcspFetch= false,  so the behavior on .NET7 and .NET8 is different ...
![image](https://github.com/dotnet/runtime/assets/17263036/c0e0c6f9-2681-43c3-bd0c-675e441ad348)

Will .net8 go head with OCSP disabled by default?

**Comment by rzikm** [comment]
Judging from the PR (https://github.com/dotnet/runtime/pull/83013) text the change was intentional, I will let @wfurt confirm.

> I was thinking about deleting the test but I decided to keep it and modify the behavior instead.
This would IMHO preserve legacy behavior. When single certificate is used it would act as it always did - e.g. no OCSP.
>
> When SslStreamCertificateContext is created and provided by user we would take is as intention to reuse it over time and we would handle TLS resume & OCSP. This is currently recommended use as it also offers other performance benefits.

You can reenable OCSP by providing the certificate using `SslServerAuthenticationOptions.ServerCertificateContext` as recommended.

**Comment by wfurt** [comment]
yes, it was intentional but somewhat poorly documented. AFAIK we may not have docs about stapling at all as there is no API surface to control it. And for that reason I wanted to give some control to the callers by enabling it in one case and disabling it in other. As @rzikm mentioned above there are other features like TLS Resume that are linked to the context as well. 

Perhaps we should track it as docs issue @rzikm ????
And/or have opt-out switch for cases when it misbehaves and causes problems like this.

**Comment by cdlliuy** [comment]
Thanks for the clarification @wfurt, @rzikm 

Given OSCP stapling related issues that surfaced in .NET7 linux,  yes, I think disabling it in .NET8 by default & provide a switch that user can control is a good approach for us.

**Comment by rzikm** [comment]
> Perhaps we should track it as docs issue @rzikm ???? And/or have opt-out switch for cases when it misbehaves and causes problems like this.

Agreed, filed separate issue for that. https://github.com/dotnet/runtime/issues/96395. When it is done we can backport the appcontext switch to 8.0 if it will help with migration. @cdlliuy.

Is there anything else regarding the original problem? from the last few comments I understand that you will soon migrate to .NET 8 so there is no need to backport #89907 to 7.0. Is that correct?
