### ISSUE TITLE
Configuration binding generator produces incorrect type 

### ISSUE THREAD

**Issue by mshwf** [dotnet/runtime#95561]
### Description

This was discovered while I was upgrading to .NET 8 from .NET 6. There were numerous errors in this code:

```
builder.Services.AddAuthentication().AddJwtBearer(JwtBearerDefaults.AuthenticationScheme, options =>
{
    // Nearly 300 errors caused by this line👇, all say: "Property ... is not supported" or "Cannot create instance of type..."
    builder.Configuration.Bind("JwtSettings", options);
});
```

I created a minimal project to reproduce, and I found the configuration binder fails (or may be expected to fail in this case) to generate the correct type when there is explicit type casting from an inherited member.

### Reproduction Steps

Create these models (these are similar to how `JwtBearerOptions` is structured which confuses the configuration binder):

```
public class SomeEvent { }
public class MyOptions : MyBaseOptions
{
    public new SomeEvent Events
    {
        get => (SomeEvent)base.Events!;
        set => base.Events = value;
    }
}
public class MyBaseOptions
{
    public object? Events { get; set; }
}
```

and try to bind `MyOptions` from a configuration section:
```
var myOptions = new MyOptions();
builder.Configuration.Bind("MyOptions", myOptions);
```

and add this to the CSProj file:
`<EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
`
Try to build the project.

### Expected behavior

I'd expect the same behavior as the .NET 6 configuration system, and no compilation errors.

### Actual behavior

Compilation error due to incorrect source code generated by the configuration binder:
> Cannot implicitly convert type 'string' to 'WebApplication8.SomeEvent'	WebApplication8	~\WebApplication8\WebApplication8\Microsoft.Extensions.Configuration.Binder.SourceGeneration\Microsoft.Extensions.Configuration.Binder.SourceGeneration.ConfigurationBindingGenerator\BindingExtensions.g.cs	137	Active	

This is the generated method that produces the error:

```
public static void BindCore(IConfiguration configuration, ref MyOptions instance, bool defaultValueIfNotFound, BinderOptions? binderOptions)
{
    ValidateConfigurationKeys(typeof(MyOptions), s_configKeys_MyOptions, configuration, binderOptions);

    if (configuration["Events"] is string value10)
    {
        instance.Events = value10; // ❌👈 Cannot implicitly convert type 'string' to 'WebApplication8.SomeEvent' 
    }
}
```

**Comment by tarekgh** [comment]
https://github.com/dotnet/runtime/issues/94071

**Comment by ericstj** [comment]
This was fixed in https://github.com/dotnet/runtime/pull/94588

Can you make sure you update your package reference (if using the package) or update your SDK you aren't?
```xml
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.2" />
```

**Comment by mshwf** [comment]
@ericstj I'm using the latest version of Visual Studio - v17.10.5 (so SDK is updated?), also added the mentioned package Microsoft.Extensions.Configuration.Binder (should I do something with it or it's for the SDK?), still have the same errors.

**Comment by ericstj** [comment]
It could be a namespace collision in your project with some other types you haven't shared.

Here's an isolated repro that shows it working:
[testBindEvent.zip](https://github.com/user-attachments/files/16589041/testBindEvent.zip)


You can see the generated code has 
```c#
        public static void BindCore(IConfiguration configuration, ref global::MyOptions instance, bool defaultValueIfNotFound, BinderOptions? binderOptions)
        {
            ValidateConfigurationKeys(typeof(global::MyOptions), s_configKeys_MyOptions, configuration, binderOptions);

            if (AsConfigWithChildren(configuration.GetSection("Events")) is IConfigurationSection section0)
            {
                instance.Events ??= new global::SomeEvent();
            }
        }
```
