### ISSUE TITLE
[API Proposal]: Linq method for getting value and index

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#95563]
### Background and motivation

There is an existing Linq method for returning an enumerable's value and index, but it was added pre-tuples which makes it clunky as it forces the caller to create a type representation for the combination of the value and index, for example using this:

```C#
IEnumerable<string> lines = GetLines();

foreach (var (line, lineIndex) in lines.Select((l, i) => (l, i)))
{
    // ...
}
```

### API Proposal

```C#
namespace System.Linq;

public static partial class Enumerable
{
    public static IEnumerable<(T Value, int Index)> WithIndex<T>(this IEnumerable<T> source);
}

public static partial class Queryable
{
    public static IQueryable<(T Value, int Index)> WithIndex<T>(this IQueryable<T> source);
}
```

### API Usage

Using `WithIndex`, one can express this idea much more succinctly:

```C#
IEnumerable<string> lines = GetLines();

foreach (var (line, lineIndex) in lines.WithIndex())
{
    // ...
}
```

### Risks

None.

**Comment by KeterSCP** [comment]
I also want to point out that name `SelectIndex` is very unintuitive. It implies that you select only index, which is not true. `SelectWithIndex` or `ZipWithIndex` are more verbose, but at least they do not introduce confusion

**Comment by terrajobst** [comment]
@eiriktsarpalis that makes sense. Personally, I'd prefer @marklio's suggestion `WithIndex` over `ZipIndex` because it seems easier to understand.

**Comment by eiriktsarpalis** [comment]
Methods starting with `With` are typically associated with update expressions e.g. in fluent APIs or records. This is not in the same boat.

**Comment by aloraman** [comment]
1) How about `AsIndexed` or just `Indexed`?
2) What's the intended meaning of `EventualNameOfThisMethod` in `IQueryable`, e.g. should it be translated into `ROW_NUMBER()`?

**Comment by viceroypenguin** [comment]
The same method in MoreLinq and SuperLinq is just `Index()`. This is likely not a good choice for the name, but raising awareness of the community implementations of this.

**Comment by terrajobst** [comment]
> I'm sure more than ample debate will be expended on the naming.

<img src="https://media3.giphy.com/media/AWv3UAFkgz39u/giphy.gif"/>

**Comment by y0ung3r** [comment]
What about `IndexableSelect` or `IndexedSelect`? 😂

**Comment by terrajobst** [comment]
* We decided to return `Index` first, `Value` second because it feels more natural despite the fact that the existing `Select()` method provides value first and index second.
    ```C#
    IEnumerable<string> lines = GetLines();

    foreach (var (i, line) in lines.Index())
    {
        // ...
    }
    ```
* We should match the existing `Select`'s method behavior when enumerating a source that returns more than `int.MaxValue` items

```C#
namespace System.Linq;

public static partial class Enumerable
{
    public static IEnumerable<(int Index, T Value)> Index<T>(this IEnumerable<T> source);
}

public static partial class Queryable
{
    public static IQueryable<(int Index, T Value)> Index<T>(this IQueryable<T> source);
}
```
