### ISSUE TITLE
[Default interfaces] Debugger support

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#9556]
This tracks checking whether we need any work on the debugger side to be able to invoke default interface methods and if any work is needed, this will track the work in question.

At minimum, we'll need:
- [ ] Support for invoking shared instance methods on generic interfaces. Those are kind of special.
- [ ] Stepping into/over interface calls that hit the diamond inheritance problem. (These throw exception in an unexpected place.)

**Comment by tommcdon** [comment]
Closing as the work to support default interfaces is done to the best of our knowledge
