### ISSUE TITLE
Unable to get Entire Certificate Chain in SSL Communication when creating a c++ Socket client using openSSL.

### ISSUE THREAD

**Issue by jadavparesh06** [dotnet/runtime#95578]
### Description

So the issue is my Server is in C# where I used TcpListener and created SSLStream with my pfx file which contains Server Certificate, Private Key, Chain information(CA Details). 
My client is build in c++ via OpenSSL. 

so the issue is I am only getting leaf certificate and not entire chain on the Server. Do we have any way to explicitly tell SSLStream about my CA certificate as well as server Certificate both.

### Reproduction Steps

So the issue is my Server is in C# where I used TcpListener and created SSLStream with my pfx file which contains Server Certificate, Private Key, Chain information(CA Details). 
My client is build in c++ via OpenSSL. 

so the issue is I am only getting leaf certificate and not entire chain on the Server. Do we have any way to explicitly tell SSLStream about my CA certificate as well as server Certificate both.
Note : Both my CA & Server Certificate are installed in Trusted CA at Windows Store and in code also I am reading it from same Trusted CA Store only.

### Expected behavior

I expect there should be directly linked and provided to client counter part since my pfx itself has all the required details about the chain.

### Actual behavior

I am only getting the server certificate and not the entire chain(server certificate + CA) on client side.

**Comment by wfurt** [comment]
Did you try [SslStreamCertificateContext](https://learn.microsoft.com/en-us/dotnet/api/system.net.security.sslstreamcertificatecontext?view=net-8.0)?? That should allow you to set all the intermediates as well. Just use that in `SslServerAuthenticationOptions` instead of `ServerCertificate`.
