### ISSUE TITLE
ReferenceEquals returns true for two objects with the same value in a different memory location.

### ISSUE THREAD

**Issue by PeterHlavenka** [dotnet/runtime#95573]
Hello,

We updated our solution to .NET 8 and encountered an issue with ReferenceEquals. In .NET 6, ReferenceEquals for two string objects with same value returns false, but in .NET 8, it returns true. Thank you for your assistance.

P.

### Description

        [Test]
        public void EqualityTest()
        {
            string s100A = 100.ToString(CultureInfo.InvariantCulture);
            string s100B = 100.ToString(CultureInfo.InvariantCulture);
            
            // Reference types:
            var test = ReferenceEquals(s100A, s100B);  // should be false, but it is true.. 
            
            Assert.That(ReferenceEquals(s100A, s100B), Is.False);
        }

### Configuration

.net8
Windows 10
x64

### Regression?

In .net6 it have expected behavior.

**Comment by huoyaoyuan** [comment]
This is expected. `ToString` results of small integers are cached and will always return the same object. The cache range was increased in #79061.

https://github.com/dotnet/runtime/blob/b69f79c2b6cd69a4979146774329260870b35dcb/src/libraries/System.Private.CoreLib/src/System/Number.Formatting.cs#L1962-L1970

https://github.com/dotnet/runtime/blob/b69f79c2b6cd69a4979146774329260870b35dcb/src/libraries/System.Private.CoreLib/src/System/Number.Formatting.cs#L287-L292

Don't make assumptions about reference identity of string, if they are not explicitly created by yourself via `new string` or `string.Create`.

**Comment by GrabYourPitchforks** [comment]
> if they are not explicitly created by yourself via new string or string.Create

Even in this case, we make no guarantee that you're going to get a new instance of a string. `new string(...)` is special-cased by the runtime to call a special factory method rather than go through the normal instantiation process. That factory method, like `int.ToString(...)`, can cache outputs. This is most evident when creating zero-length strings.
