### ISSUE TITLE
CA2017 reports Logging has wrong number of arguments

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#95584]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/CA2017-reports-Logging-has-wrong-number-/10520714)._

---
[severity:I'm unable to use this version] [regression] [worked-in:17.7.last]
I have just updated my Visual Studio to 18.8 and am now gettin an error when I attempt to build my application.

The projects is as follows:
```
<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
		<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
	</PropertyGroup>

<ItemGroup>
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.13" />
	  <PackageReference Include="Polly.Extensions.Http" Version="3.0.0" />
	</ItemGroup>

</Project>
```

The error is `CA2017: Parameter count mismatch`.  The line of code is:

```
_logger. LogError(ex, "my string", myListOfObjects);
```

This is a Azure App Service and `_logger` is `ILogger<TheCurrentClass>`.

According to the Microsoft [Documentation](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loggerextensions.logerror?view=dotnet-plat-ext-8.0#microsoft-extensions-logging-loggerextensions-logerror(microsoft-extensions-logging-ilogger-system-exception-system-string-system-object())), the example given matches my code:

```
logger. LogError(exception, "Error while processing request from {Address}", address)
```

If I am to stick with this version of Visual Studio, then I'd have to go **against** MS's advice and to suppress the CA2017 warning using
```
	<PropertyGroup>
	  <NoWarn>1701; 1702; CA2017</NoWarn>
	</PropertyGroup>
```

---
#### Feedback Bot on 11/21/2023, 04:00 AM: 

(private comment, text removed)
#### Noah Doughton on 11/21/2023, 03:16 PM: 

(private comment, text removed)
#### Radek Zikmund [MSFT] on 11/30/2023, 00:01 PM: 

(private comment, text removed)

---
#### Jonathan Griffiths solved on 11/20/2023, 01:13 PM, 1 votes: 

<p>I found another workaround which is to change:</p>
<blockquote>
<p>_logger. LogError(ex, “my string”, myListOfObjects);</p>
</blockquote>
<p>to</p>
<blockquote>
<p>_logger. LogError(ex, “my string”, new [] { myListOfObjects });</p>
</blockquote>
<p>Previously, this wasn’t necessary and is contrary to the example given on <a target='_blank' href="https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loggerextensions.logerror?view=dotnet-plat-ext-8.0#microsoft-extensions-logging-loggerextensions-logerror(microsoft-extensions-logging-ilogger-system-exception-system-string-system-object()">https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loggerextensions.logerror?view=dotnet-plat-ext-8.0#microsoft-extensions-logging-loggerextensions-logerror(microsoft-extensions-logging-ilogger-system-exception-system-string-system-object()</a>)</p>

**Comment by tarekgh** [comment]
We need a small repro example to be able to investigate. My guess here is `myListOfObjects` is not defined as array.

**Comment by oskarjf** [comment]
I just updated as well and all my logger.LogError messages are now throwing CS2017.
Adding new[] { myParamObject } for the params object parameter fixes the error as suggested above.

**Comment by tarekgh** [comment]
@oskarjf what is the type of `myParamObject`? can you provide a complete small reproduce example?
