### ISSUE TITLE
Simplify the 'emit immediate' logic in emitxarch

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#9559]
In `emitxarch`, we have a some duplicated logic for emitting immediate values to handle the imm8 and the imm16/imm32 case (ex: https://github.com/dotnet/coreclr/pull/14736/files/59db2cef21998c9680670a95939e77ee29ebc595#diff-a51165bc1fd2c0fa3987370e2e714356R8201).

It would be useful to create a helper method and contain this logic centrally where possible.

category:implementation
theme:emitter
skill-level:intermediate
cost:small

**Comment by BruceForstall** [comment]
Closing.
