### ISSUE TITLE
Investigate moving the types in `System.Numerics.Vectors` to use Hardware Intrinsics

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#956]
Today, hardware acceleration of certain types in the `System.Numerics.Vectors` project is achieved via `[Intrinsic]` attributes and corresponding runtime support. There are a few downsides to this approach:
* Minor tweaks to the backing implementation require shipping a new runtime
* It is not obvious that the code has a hardware accelerated path (outside reading documentation)
* Many of the types (such as the Matrix types) are not directly hardware accelerated

In `netcoreapp30`, the new Hardware Intrinsics feature is supposed to ship. This feature also allows hardware acceleration but at a much more fine-grained level (APIs typically have a 1-to-1 mapping with underlying instructions).

We should investigate moving the types in `System.Numerics.Vectors` to use hardware intrinsics as this has multiple potential benefits:
* The hardware acceleration is still tied to the runtime, but minor tweaks can be made without having to ship a new runtime
* The code having a hardware accelerated path becomes obvious as does the code that will be generated for a given platform/cpu
* It will become much easier to add hardware acceleration support to types currently missing it (such as `Matrix4x4`)

**Comment by tannergooding** [comment]
I had done an initial investigation of this in https://github.com/dotnet/coreclr/pull/27483, but it was closed due to generating more complex trees and therefore missing some optimizations. This is not something that could be readily handled today.

@CarolEidt, @jkotas, @AndyAyersMS.

Unless you have any objections, I plan on closing this as unactionable until the blocking issues are addressed. Do we have issues currently tracking the needed improvements?

As an aside, with us looking at introducing more AOT/R2R options, the ISA specific paths codified in the JIT are becoming more problematic and we are needing to block more methods due to this (e.g. https://github.com/dotnet/runtime/pull/33090). This also means consumers can't see the benefits of the ISA specific perf improvements when they are available. On the other hand, ISA specific paths codified in managed code don't have this problem and we are able to support both paths relatively trivially. We also have better codegen support in general (especially around containment). and so addressing some of the currently blocking issues may become more necessary as we move forward.

**Comment by jkotas** [comment]
>  I plan on closing this as unactionable until the blocking issues are addressed

I think that this can be kept open to keep track of the progress. It is something we want to do, it just cannot be done today.
 
Agree with the rest.

**Comment by tannergooding** [comment]
Going to close this as most off the SIMD intrinsics have already been ported to use HWIntrinsics internally during importation.
