### ISSUE TITLE
Replacing runtime framework assembly works in C# but not in C++/CLI

### ISSUE THREAD

**Issue by adv12** [dotnet/runtime#95607]
### Description

I'm porting a C++/CLI app from Framework to .NET 8, and there's a third-party Framework library we link against that uses a Framework class (System.Security.Cryptography.ProtectedMemory) that is missing in .NET Core.  I was trying to follow the guidelines in #37695 to replace the compatibility shim System.Security.dll with a customized version that forwards to an implementation of ProtectedMemory, but it didn't seem to be working from C++/CLI.

I was able to get the whole setup working with a C# project, so I created an analogous C++/CLI app to demonstrate the differences.  I put them in a combined solution hosted here: https://github.com/adv12/ShimTest

Both the C# app and the C++/CLI app add an assembly reference to my customized System.Security.dll to get it into their .deps.json files.  I've verified it shows up there with my bumped version number (5.0.0.0, up from 4.0.0.0).  Each app links against a Framework dll that tries to load the ProtectedMemory class and write its assembly's location to the console.  The C# app gets System.Security.dll 5.0 and everything works; the C++ app gets System.Security.dll 4.0 and a TypeLoadException.

At runtime I'm inspecting the TRUSTED_PLATFORM_ASSEMBLIES property and can observe that in the C# app, the custom System.Security.dll is at the top of the TPA list; in the C++ app, it just lists C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Security.dll.

Mostly I'm wondering whether there's *some way* to make this work in C++/CLI.  It doesn't have to work the same way, but I don't know enough about assembly loading in C++/CLI to guess what to tweak.

### Reproduction Steps

Clone and build the ShimTest solution from https://github.com/adv12/ShimTest

Run CSharpApp and observe that the custom System.Security.dll 5.0.0.0 is loaded and ProtectedMemory is found.

Run CppApp and observe that System.Security.dll 4.0.0.0 (inbox version) is loaded and ProtectedMemory is not found.

### Expected behavior

C++/CLI behaves like C#

### Actual behavior

C++ app loads the inbox System.Security.dll

### Configuration

.NET 8, Windows 11, x64

And I hope this isn't considered rude, but based on other conversations, my best guesses as to who can help are @jkotas, @elinor-fung, and @vitek-karas.

**Comment by huoyaoyuan** [comment]
> I've verified it shows up there with my bumped version number (5.0.0.0, up from 4.0.0.0).

The version number of .NET 8 framework assembly is 8.0.0.0. Have you tried some higher version, e.g. 8.1.0.0?

**Comment by jkotas** [comment]
> > I've verified it shows up there with my bumped version number (5.0.0.0, up from 4.0.0.0).

> The version number of .NET 8 framework assembly is 8.0.0.0. 

System.Security.dll is a compat shim. It has assembly version locked at 4.0.0.0 even in .NET 8.

The host is picking up overriden System.Security.dll correctly. From `set COREHOST_TRACE=1`:
```
corehost_resolve_component_dependencies results: {
  assembly_paths: 'C:\ShimTest\x64\Debug\CppCliDll.dll;C:\ShimTest\x64\Debug\FrameworkLib.dll;C:\ShimTest\x64\Debug\System.Security.Bonus.dll;C:\ShimTest\x64\Debug\System.Security.dll;'
  native_search_paths: ''
  resource_search_paths: ''
}
```

Looks like a problem in how assembly load contexts are setup by IJW hosting.

**Comment by jkotas** [comment]
Related to #61105

**Comment by adv12** [comment]
After reading some loader code, I think I understand what's going on here a little better.

ijwhost loads the managed parts of a mixed DLL via a [call to a loadInMemoryAssembly delegate](https://github.com/dotnet/runtime/blob/548830bae60bf17e17c6ee59ebacc602d9d6e02e/src/native/corehost/ijwhost/ijwthunk.cpp#L148) that resolves to [Internal.Runtime.InteropServices.InMemoryAssemblyLoader.LoadInMemoryAssembly](https://github.com/dotnet/runtime/blob/2bfa26cebc917d05a3363078fa277ab5fee2651b/src/coreclr/System.Private.CoreLib/src/Internal/Runtime/InteropServices/InMemoryAssemblyLoader.cs#L27C1-L27C1).

For resolving this assembly's dependencies, that method [adds an event handler to AssemblyLoadContext.Default.Resolving](https://github.com/dotnet/runtime/blob/2bfa26cebc917d05a3363078fa277ab5fee2651b/src/coreclr/System.Private.CoreLib/src/Internal/Runtime/InteropServices/InMemoryAssemblyLoader.cs#L81C1-L90C23).

That event handler [uses corehost_resolve_component_dependencies](https://github.com/dotnet/runtime/blob/2bfa26cebc917d05a3363078fa277ab5fee2651b/src/libraries/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyDependencyResolver.cs#L55C1-L64C28) to get the right DLLs out of the .deps.json file, but  the Resolve event is only fired if the assembly is not found first by earlier loading steps.

As I understand it, those earlier steps will search TRUSTED_PLATFORM_ASSEMBLIES, which, as I observed in the original post, contains the version-bumped DLL in the C# app but not the C++ app.  There must be some earlier host setup step where the .deps.json file should be considered for TRUSTED_PLATFORM_ASSEMBLIES and is not.

But maybe that's what you were saying about assembly load context setup.

**Comment by adv12** [comment]
Digging further, I think this is what's happening:

Because ijwhost needs the LoadInMemoryAssembly delegate to load mixed-mode assemblies, the first .NET assembly to be loaded is the one that contains that method.  [get_load_in_memory_assembly_delegate](https://github.com/dotnet/runtime/blob/ec173a350f000d7868d031e79eb714f82cdfae01/src/native/corehost/ijwhost/ijwhost.cpp#L23) calls [load_fxr_and_get_delegate](https://github.com/dotnet/runtime/blob/ec173a350f000d7868d031e79eb714f82cdfae01/src/native/corehost/fxr_resolver.h#L21C30-L21C30), which [initializes the host with hostfxr_initialize_for_runtime_config](https://github.com/dotnet/runtime/blob/ec173a350f000d7868d031e79eb714f82cdfae01/src/native/corehost/fxr_resolver.h#L82C13-L82C13), which respects .runtimeconfig.json but not .deps.json.

**Comment by adv12** [comment]
I spent several days familiarizing myself with the loader code and concluded that supporting this scenario would involve some pretty invasive changes.  We've decided to ship our app with a local DOTNET_ROOT.  I won't close this issue in case MS decides this is worth the investment, but my needs are met.  Thanks @jkotas  for responding.

**Comment by AaronRobinsonMSFT** [comment]
@adv12 Glad you are unblocked. C++/CLI scenarios are typically rather narrow and we don't plan to invest in them specifically. @elinor-fung may have additional thoughts on ways to improve the overall experience but it is unlikely we are going to improve C++/CLI-centric scenarios. I'm going to close this for now.
