### ISSUE TITLE
Upgrade to .NET 9 SDK

### ISSUE THREAD

**Issue by mthalman** [dotnet/runtime#95605]
This repo should be targeting the .NET 9 SDK from the global.json file. This is a requirement necessary for .NET source build in order to target the `net9.0` TFM. If necessary, this change can be made after the first public preview release.

Related to https://github.com/dotnet/source-build/issues/3770

**Comment by lewing** [comment]
runtime updates its sdk via arcade which is typically once there is a new publicly released sdk

cc @ViktorHofer

**Comment by ViktorHofer** [comment]
Replied directly in the uber issue: https://github.com/dotnet/source-build/issues/3770#issuecomment-1840274306
