### ISSUE TITLE
Icorrect comment for the year pattern in DateTimeFormat

### ISSUE THREAD

**Issue by Guiorgy** [dotnet/runtime#95629]
Using more than 2 `y` characters in the format results in the year being formatted with leading zeroes, for example:

```cs
Console.WriteLine((new DateTime(23, 1, 2, 3, 4, 5, 6)).ToString("yyy")); // result: 023
Console.WriteLine(DateTime.Now.ToString("yyyyyy")); // result: 002023
```

This is correctly documented in [learn.microsoft.com](https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings):

|   |   |   |
| :--- | :--- | :--- |
| "yyy" | The year, with a minimum of three digits. | 0001-01-01T00:00:00 -> **001** |
|  | More information: The "yyy" Custom Format Specifier. | 0900-01-01T00:00:00 -> 900 |
|  |  | 1900-01-01T00:00:00 -> 1900 |
|  |  | 2009-06-15T13:45:30 -> 2009 |
| "yyyy" | The year as a four-digit number. | 0001-01-01T00:00:00 -> **0001** |
|  | More information: The "yyyy" Custom Format Specifier. | 0900-01-01T00:00:00 -> **0900** |
|  |  | 1900-01-01T00:00:00 -> 1900 |
|  |  | 2009-06-15T13:45:30 -> 2009 |
| "yyyyy" | The year as a five-digit number. | 0001-01-01T00:00:00 -> **00001** |
|  | More information: The "yyyyy" Custom Format Specifier. | 2009-06-15T13:45:30 -> **02009** |

However, the comments above [DateTimeFormat](https://github.com/dotnet/runtime/blob/6249fd2e59ed1308eb7cf976fb48c1ecab5eaa4e/src/libraries/System.Private.CoreLib/src/System/Globalization/DateTimeFormat.cs#L74) and the ['y' case](https://github.com/dotnet/runtime/blob/6249fd2e59ed1308eb7cf976fb48c1ecab5eaa4e/src/libraries/System.Private.CoreLib/src/System/Globalization/DateTimeFormat.cs#L621) say otherwise:

> "**yyyyy**" "D5"        year                                  **2000**

and

> // yyy/yyyy/yyyyy/... : Print year value.  **No leading zero**.

It would be more correct to mention the leading zeroes, for example:

```cs
/*
"yyyyy" "D5"        year with leading zeroes               02000
...
*/
```

and

```cs
// yyy/yyyy/yyyyy/... : Print year value.  With leading zeroes.
```

**Comment by tarekgh** [comment]
@Guiorgy are you interested to submit a PR to fix this?

**Comment by MichalPetryka** [comment]
> are you interested to submit a PR to fix this?

Would this be a documentation change or behaviour change?

**Comment by tarekgh** [comment]
@MichalPetryka this is just fixing the comments in the source files:

https://github.com/dotnet/runtime/blob/6249fd2e59ed1308eb7cf976fb48c1ecab5eaa4e/src/libraries/System.Private.CoreLib/src/System/Globalization/DateTimeFormat.cs
https://github.com/dotnet/runtime/blob/6249fd2e59ed1308eb7cf976fb48c1ecab5eaa4e/src/libraries/System.Private.CoreLib/src/System/Globalization/DateTimeFormat.cs#L621C52-L621C52

**Comment by Guiorgy** [comment]
@tarekgh Is #95650 satisfactory?

**Comment by tarekgh** [comment]
Right, all `yy`, `yyy``, `yyyy`, and `yyyyy` are using leading zeros if the year number has number of digits less than the number of y's.
