### ISSUE TITLE
 Split on Span and Count disfunctioning (bug) when multiple separators given

### ISSUE THREAD

**Issue by egbertn** [dotnet/runtime#95625]
### Description

When using Count (extension) on multiple separators, only one item is counted, always.
Split same problem.

### Reproduction Steps

```c#
var hello = "The _ yellow fox_jumped".AsSpan();
var helloStr = "The _ yellow fox_jumped";

var splitted = helloStr.Split(separator:(char[])['_', ' '], StringSplitOptions.RemoveEmptyEntries);
int correctCount = splitted.Length;

ReadOnlySpan<char> splitters = ['_', ' '];
var count = hello.Count(splitters);

Span<Range> ranges = stackalloc Range[count + 1];

hello.Split(ranges, splitters, StringSplitOptions.RemoveEmptyEntries);
foreach (var range in ranges)
{
    Console.WriteLine($"start = {range.Start}, {range.End}");
}
```

### Expected behavior

Count and split should work on the whole span
 The example should have Count = 5
There should be 4 filled ranges.
```text
[0] [string]:
"The"
[1] [string]:
"yellow"
[2] [string]:
"fox"
[3] [string]:
"jumped"
```
### Actual behavior

Count and split stop after being == 1
```text
[0] [string]:
"The " <--- note the space
[1] [string]:
"yellow fox_jumped"
```
### Regression?

This is .NET 8.0

### Known Workarounds

None

### Configuration

Just targetframework 8.0

**Comment by GalaxiaGuy** [comment]
I don't think the span version interprets the `separator` parameter as a collection of separators, but a single (potentially multi character) separator.

So your span example is the same as splitting on the string "_ ".

https://learn.microsoft.com/en-us/dotnet/api/system.memoryextensions.split?view=net-8.0#system-memoryextensions-split(system-readonlyspan((system-char))-system-span((system-range))-system-readonlyspan((system-char))-system-stringsplitoptions)

**Comment by egbertn** [comment]
If so, the behavior is expected, but the sister Split behaves differently, so very confusing.

**Comment by egbertn** [comment]
Comments are faulty then.
It should say: "Separator" not 'separators'.
```text
        //     Parses the source System.ReadOnlySpan`1 for one of the specified separators,
        //     populating the destination span with System.Range instances representing the
        //     regions between the separators.
        //
```
