### ISSUE TITLE
[browser] Validate that browser template debugging works

### ISSUE THREAD

**Issue by maraf** [dotnet/runtime#95627]
The `wasmbrowser` template has `launchSettings.json` with `inspectUri` used by VS when starting debugging. We should validate that this URL is correct and ideally that the whole process works.

We could use `vscode-js-debug` extension to write such test. Other option would be to have a manual test scenario

**Comment by maraf** [comment]
cc @thaystg @radical

**Comment by radical** [comment]
> Other option would be to have a manual test scenario

We should do this irrespective of the automated test.

**Comment by maraf** [comment]
**Manual test instructions**

1. Run `dotnet workload install wasm-experimental` to install templates
2. Run `dotnet new wasmbrowser -o WasmBrowser` to create application from template
3. Open the project with Visual Studio
4. Open Program.cs
5. Insert breakpoint on line 12 (`Console.WriteLine(text);`)
6. Run the project (F5)
7. Browser should open and debugger should stop in VS on the breakpoint
8. Check that variable `text` contains URL that is opened in the browser

**Comment by maraf** [comment]
Closing as the manual test is setup
