### ISSUE TITLE
Issue with Delegate Pointers in .NET Core AOT using EasyHook

### ISSUE THREAD

**Issue by blackmaple** [dotnet/runtime#95624]
I've recently been working with .NET Core AOT to implement some hooks using EasyHook. During this process, I encountered a behavior with delegate pointers that seems unusual and problematic.
Specifically, it appears that delegate pointers are evaluated based on the condition (pointer address's lower 8 bits) & 2 == 0. This condition seems to be a critical factor in the delegate's execution path. However, I've noticed that function pointers returned by third-party libraries like EasyHook do not undergo alignment processing, which leads to the delegate pointer being misinterpreted and erroneously redirected to an error path.
This behavior, particularly the evaluation of (pointer address's lower 8 bits) & 2 == 0, is unclear to me. I'm unsure of its purpose and implications in this context. It seems to create compatibility issues with unaligned function pointers from libraries such as EasyHook.
Could someone provide clarity on why delegate pointers are subjected to this specific evaluation? Understanding this could help in determining if this is a bug or a feature that requires a workaround when integrating with certain third-party libraries.

48 8B 4C 24 28        - mov rcx,[rsp+28]
48 8B C1              - mov rax,rcx
//????
F6 C1 02              - test cl,02 { 2 }
75 0D                 - jne Maple.Test+A8
48 8B CF              - mov rcx,rdi
48 8B D3              - mov rdx,rbx
4C 8B C6              - mov r8,rsi
FF D0                 - call rax
EB 10                 - jmp Maple.Test+B8
48 8B 48 06           - mov rcx,[rax+06]
48 8B D7              - mov rdx,rdi
4C 8B C3              - mov r8,rbx
4C 8B CE              - mov r9,rsi
FF 50 FE              - call qword ptr [rax-02]

**Comment by MichalStrehovsky** [comment]
This is a flag in managed function pointers to indicate whether the function pointer is a fat function pointer.

This should be transparent as long as everything is being used as it should - places that expect to see a pointer to a function with a managed calling convention only see pointers to managed functions, and places that expect a function pointer for a native calling convention only see function pointer with native calling conventions (those never have the flag).

If you're using function with native calling conventions in places that expect a managed function, it's unsupported and it will not work.

**Comment by MichalPetryka** [comment]
The runtime relies on the fact that all managed methods are aligned to 16B, hacking the runtime and causing methods to not behave like this is not supported.

**Comment by MichalStrehovsky** [comment]
I assume this was answered.
