### ISSUE TITLE
[browser] Running `Scenario=WasmTestOnNodeJS` does not set `ENVIRONMENT_IS_NODE`

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#95639]
Because of it, we are unable to detect `PlatformDetection.IsNodeJS` for HybridGlobalization tests. Expected test results differ between hosts, browser expected short months
`"jan.", "feb.", "mars",..`
NodeJS expected short months:
`"jan.", "feb.", "mar.",...`

Blocking this test case till fixed.

**Comment by radical** [comment]
> Blocking this test case till fixed.

Which test case?

**Comment by ilonatommy** [comment]
https://github.com/dotnet/runtime/pull/95324/commits/661d0461c73d69558826442ae8c15c81eff6910f
but it's still under investigation. Most probably it will get closed as locally it was passing. However, test run had a failure on Win with no proper log, so I need to re-check it.
