### ISSUE TITLE
Failing test `tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.cmd` on mono/osx

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#95669]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=489942
Build error leg or test failing: tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.cmd
Pull request: https://github.com/dotnet/runtime/pull/95281

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=489942
**Error message validated:** `nativeruntimeeventsource.sh: line 458: 99201 Abort trap: 6`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 12/6/2023 5:03:58 AM UTC

**Comment by tommcdon** [comment]
Moving to future and removing `blocking-clean-ci` label as this seems to have a very low hit count
