### ISSUE TITLE
[API Proposal]: `InvalidEnumArgumentException` should support `uint/long/ulong`-backed enumerations

### ISSUE THREAD

**Issue by colejohnson66** [dotnet/runtime#95696]
### Background and motivation

Currently, `InvalidEnumArgumentException` only "supports" `int`-backed enumerations (and consequently `byte`, `sbyte`, `ushort`, and `short`) as it requires a cast to an `int` for the `invalidValue` parameter. This is unnecessarily restrictive, as the parameter is immediately formatted into the message string before being forgotten; It's never stored into a field/property. This can be seen in the source:

https://github.com/dotnet/runtime/blob/41dbe9c916319d5228d56edaa5c99a0ab6269325/src/libraries/System.ComponentModel.Primitives/src/System/ComponentModel/InvalidEnumArgumentException.cs#L47-L54

Overloads accepting `uint`, `long`, and `ulong` should be added.

### API Proposal

```csharp
using System;

namespace System.ComponentModel;

public InvalidEnumArgumentException : ArgumentException
{
    // original proposal
    public InvalidEnumArgumentException(string? argumentName, uint invalidValue, Type enumClass);
    public InvalidEnumArgumentException(string? argumentName, long invalidValue, Type enumClass);
    public InvalidEnumArgumentException(string? argumentName, ulong invalidValue, Type enumClass);

    // alternative suggestion by @stephentoub
    public InvalidEnumArgumentException(
        object invalidValue,
        [CallerArgumentExpression(nameof(invalidValue))] string? argumentName = null);

    // or...
    [DoesNotReturn]
    public static void Throw<TEnum>(
        TEnum invalidValue,
        [CallerArgumentExpression(nameof(invalidValue))] string? argumentName = null)
        where TEnum : struct, Enum;
    public static void ThrowIf<TEnum>(
        [DoesNotReturnIf(true)] bool condition,
        TEnum invalidValue,
        [CallerArgumentExpression(nameof(invalidValue))] string? argumentName = null)
        where TEnum : struct, Enum;
}
```

### API Usage

```csharp
enum MyEnum : ulong
{
    ValueBiggerThanInt = 1 << 40,
}

public void DoStuff(MyEnum value)
{
    // existing code could do `(int)value`, but that drops the upper 32 bits leaving `0` for `ValueBiggerThanInt`
    if (value is not MyEnum.ValueBiggerThanInt)
        throw new InvalidEnumArgumentException(nameof(value), (ulong)value, typeof(MyEnum));
    // ...
}
```

With the idea from @stephentoub:
```csharp
public void DoStuff(MyEnum value)
{
    InvalidEnumArgumentException.ThrowIf(value is not MyEnum.ValueBiggerThanInt, value);
    // ...
}
```

### Alternative Designs

The `uint` overload is not strictly necessary, as all `uint` values will up-cast to `long`. However, providing it would avoid, on 32-bit systems, the usage of two registers when passing the value around.

**EDIT**: @stephentoub has also proposed two options: (1) a single constructor that takes just an `object` and uses reflection to get the numeric value and type (and validate it as an enum with `Type.IsEnum`), and (2) a "throw" method with a generic constraint on enumerations (`Throw` and `ThrowIf`). In both options, the "argument name" parameter can be moved to the end and be filled in with `[CallerAgumentExpression]`.

### Risks

None. Existing code requires a cast to `int`, so it will not use the new overloads, and, as such, will continue to work the same.

Potentially, some misbehaving code is parsing the `Message` of the exception to pull out the value with `int.(Try)Parse` and would break with 64-bit numbers, but this is unlikely.

**Comment by steveharter** [comment]
The main issue is "loss of data" since long-based enums are cast to int, losing 4 bytes.

**Comment by stephentoub** [comment]
I'd be inclined to just add a single constructor that takes an Object. You can then just pass in the actual enum value, and the constructor could validate both it's non-null and its GetType.IsEnum. It'll box, but a) it's getting boxed in the implementation anyway, and b) were about to throw an exception, so boxing is a drop in the bucket.

Alternatively, a Create factory method with an enum constraint on the value.

**Comment by colejohnson66** [comment]
An object parameter would work too. You could then remove the `Type` parameter and just use `value.GetType()`.

**Comment by colejohnson66** [comment]
That's a good idea, as it would also remove the issue of having to know the backing field's type (changing an enum from `int` to `long` would require updating all call sites). I've updated my proposal with your ideas (using `Throw` and `ThrowIf`).

**Comment by bartonjs** [comment]
In API Review we felt that this type isn't generally used (and most usages that "should" use it use ArgumentOutOfRangeException instead), and we feel that there's not sufficient value in modifying this legacy type.
