### ISSUE TITLE
Enum.ToObject(typeof(MyEnum), 3.0) does not throw an ArgumentException

### ISSUE THREAD

**Issue by timothylcooke** [dotnet/runtime#95697]
### Description

See https://github.com/timothylcooke/EnumToObjectTests for a minimal repro.

When calling `Enum.ToObject(typeof(MyFlags), 3.0)`, net8.0 returns `(MyFlags)0`:

Previous versions of the framework throw an ArgumentException:

> System.ArgumentException: 'The value passed in must be an enum base or an underlying type for an enum, such as an Int32. (Parameter 'value')'

![image](https://github.com/dotnet/runtime/assets/8904110/0bb59691-763b-4b41-94b6-938508dd1022)

### Reproduction Steps

Convert a double value to enum:

    Enum.ToObject(typeof(MyFlags), 3.0);

### Expected behavior

This should throw an ArgumentException

> System.ArgumentException: 'The value passed in must be an enum base or an underlying type for an enum, such as an Int32. (Parameter 'value')'

### Actual behavior

It returns `(MyFlags)0`

### Regression?

This is new behavior in net8.0

### Configuration

I've tested on x64 win10 and win11. It also behaves the same in Maui on Win11

**Comment by MichalPetryka** [comment]
Looking at the code, it internally seems to do what it's supposed to do, the docs don't require the passed value to be the same as the enum underlying type.

**Comment by timothylcooke** [comment]
Links for reference:

* [Code](https://github.com/dotnet/runtime/blob/eafe8187aaef010016a6b76fccc0b2db4f678e2f/src/libraries/System.Private.CoreLib/src/System/Enum.cs#L2194C67-L2194C67)
* [Docs](https://learn.microsoft.com/en-us/dotnet/api/system.enum.toobject?view=net-8.0#system-enum-toobject(system-type-system-object))

**Comment by timothylcooke** [comment]
My thoughts:
1. It's weird to see a change in behavior for something that has worked the same way for many versions of the framework
2. I don't generally think of doubles based on their binary representation. As a layperson, I would expect `Convert(enumType, 3.0)` to return the same value as `Convert(enumType, 3)` or even `Convert(enumType, 3.8)` (think standard truncation to integer). I suppose binary representation makes sense, given the context, but it's not what I would immediately intuit.

**Comment by MichalPetryka** [comment]
> 2. I don't generally think of doubles based on their binary representation. As a layperson, I would expect `Convert(enumType, 3.0)` to return the same value as `Convert(enumType, 3)` or even `Convert(enumType, 3.8)` (think standard truncation to integer). I suppose binary representation makes sense, given the context, but it's not what I would immediately intuit.

Well the API seems to accept any enum backing type and blocking double-backed enums here would be weird.

**Comment by jkotas** [comment]
This was introduced by Enum rewrite in: this commit: https://github.com/dotnet/runtime/pull/78580/commits/2dd12d0833afa4383af5b9b251fc9cf54efedb0c#diff-f7c1029305b8ff70a95e36e675c08e17c8f816c5a1be8a204dc42d0595129e18R2274-R2275

@stephentoub Would it be better to revert it? I remember we went back and forth on the details of the double-backed enums.

> blocking double-backed enums here would be weird.

The support for double-backed enums is not 100% consistent for APIs like `Enum.ToObject`. For example, `Enum.GetTypeCode` does not handle them either: https://github.com/dotnet/runtime/blob/f6e5e243a5bd7d3f98e37809bc1cd61bd9dcb841/src/libraries/System.Private.CoreLib/src/System/Enum.cs#L2162-L2177 and I expect that fixing that would not be an improvement.

**Comment by stephentoub** [comment]
> Would it be better to revert this commit

You mean essentially removing those two lines so that boxed floats/doubles throw again? I'm ok with that.
