### ISSUE TITLE
[iOS] `System.Globalization.CultureInfo.DefaultThreadCurrentCulture` is not respected

### ISSUE THREAD

**Issue by marwalsch** [dotnet/runtime#95692]
### Description

Migrated from [here](https://github.com/unoplatform/uno/issues/11391). 

### Reproduction Steps

[DefaultThreadCurrentUICulture](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.defaultthreadcurrentuiculture?view=net-7.0) and [DefaultThreadCurrentCulture](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.defaultthreadcurrentculture?source=recommendations&view=net-7.0) currently do not work on iOS.
When setting CultureInfo.DefaultThreadCurrentUICulture = new CulturInfo($"{culture}");, subsequent calls to CultureInfo.CurrentUICulture or CultureInfo.CurrentCulture still return the System's default.
The issue is not present when targeting Android, Windows, or plainly .NET. 

### Expected behavior

Same behaviour as on other platforms

### Actual behavior

Value is ignored.

### Known Workarounds

Rely on polyfills.

### Configuration

```
Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maui-windows               8.0.3/8.0.100          VS 17.8.34309.116
maccatalyst                17.0.8478/8.0.100      VS 17.8.34309.116
ios                        17.0.8478/8.0.100      VS 17.8.34309.116
android                    34.0.43/8.0.100        VS 17.8.34309.11
```
The issue was also present in .NET 6.

**Comment by steveisok** [comment]
There are some slight code path differences w/ iOS because we carry our own version of ICU, but there doesn't appear to be anything special about `DefaultThreadCurrentUICulture`. What's even weirder is if the culture you try to set is not found, we throw.

@mkhamoyan when you have a moment, please triage.

**Comment by jkotas** [comment]
> subsequent calls to CultureInfo.CurrentUICulture or CultureInfo.CurrentCulture still return the System's default.

This means that some code in your application or in the libraries your app depends on set the thread culture explicitly. The DefaultThreadCurrentUICulture is ignored once the thread culture is set explicitly.

For example, try to run this as a console application:
```
using System.Globalization;

CultureInfo.CurrentUICulture = CultureInfo.CurrentUICulture; // Explicitly set the current thread culture to system default
CultureInfo.DefaultThreadCurrentUICulture = new CultureInfo("cz-CZ");
Console.WriteLine(CultureInfo.CurrentUICulture); // This prints the system default. DefaultThreadCurrentUICulture set on previous line is ignored.
```

**Comment by mkhamoyan** [comment]
From attached `ThreadCulture.zip` here is the code used to set culture
```
var currentCulture = CultureInfo.CurrentCulture;
var cultureOverride = currentCulture.Name == "en-GB" ? "ga" : "en-GB";
CultureInfo.DefaultThreadCurrentCulture = new(cultureOverride);
```

I tried it in sample app and `CultureInfo.DefaultThreadCurrentCulture` and `Culture.CurrentCulture` are same.
As @jkotas mentioned already if you see different values that means `CurrentCulture` or `CurrentUICulure` are set.

**Comment by jkotas** [comment]
> I thought that DefaultThreadCurrentUICulture only affects new threads?

That's not correct. `DefaultThreadCurrentUICulture` applies to all threads without explicitly set culture. For example, try running this as a console app:
```
using System.Globalization;

CultureInfo.DefaultThreadCurrentUICulture = new CultureInfo("cz-CZ");
Console.WriteLine(CultureInfo.CurrentUICulture); // Prints cz-CZ

CultureInfo.DefaultThreadCurrentUICulture = new CultureInfo("pl-PL");
Console.WriteLine(CultureInfo.CurrentUICulture); // Prints pl-PL
```
