### ISSUE TITLE
Thanks @Jericho for the feedback. Please re-open if this re-appears.

### ISSUE THREAD

**Issue by Shiezy** [dotnet/runtime#95691]
Originally posted by @steveharter in https://github.com/dotnet/runtime/issues/57579#issuecomment-902939972_

I am experiencing these two errors when I run the program using roslyn in the buildpipeline.
Error CS0534: 'XXXJsonContext' does not implement inherited abstract member 'JsonSerializerContext.GeneratedSerializerOptions.get'

Error CS0534: 'XXXJsonContext' does not implement inherited abstract member 'JsonSerializerContext.GetTypeInfo(Type)'

This error does not occur if I build from VS or on CLI with msbuild.

I am using System.text.json version 8.0.0. Visual studio 17. All the types being serialized are within the same namespace as the custom context class.

**Comment by eiriktsarpalis** [comment]
Would it be possible to provide a standalone reproduction please? #57579 was closed because we were missing one.
