### ISSUE TITLE
HttpResponseMessage does not contain Content-Type and Content-Length headers in DelegatingHandler

### ISSUE THREAD

**Issue by janseris** [dotnet/runtime#95708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When inside `DelegatingHandler`, which is a HTTP request/response interceptor implementation for C#/.NET, (maybe somewhere else as well), `HttpResponseMessage.Headers` does not contain `Content-Length` and `Content-Type`, although the actual underlying HTTP response contains them.
They might have been case-insensitive (that's allowed by HTTP RFC) in name but they are not detected at all.

Edit: might be related: https://developercommunity.visualstudio.com/t/Getting-Content-Length-when-using-HttpCl/1187153?space=21&q=git+rebase+--continue

The following must be used in order to get these two headers - the response body ("content") must be read (unexpected and unwanted):

```
await response.Content.LoadIntoBufferAsync();
var bodySizeBytes = response.Content.Headers.ContentLength;
```

Why actual content must be seemingly read to know content length header value which was created to know content length without reading the content? (the header is not mandatory (HTTP RFC ), but it is "removed" from the response in C#).

### Expected Behavior

`HttpResponseMessage.Headers` contains `Content-Length` and `Content-Type` headers when they are sent in HTTP response so that `HttpResponseMessage.Content` does not have to be read into buffer to be able to get `Content-Length` header value (_response body/content size in bytes_).

### Steps To Reproduce

Do a HttpClient GET call with using the following MessageHandler:

```
/// <summary>
/// Must be registered as transient
/// </summary>
public class HttpRequestInfoInterceptor : DelegatingHandler
{
    protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        var response = await base.SendAsync(request, cancellationToken);

        //TEST
        var responseHasContent = response.Content is not null;
        Trace.WriteLine($"Response has content: {responseHasContent}");
        Trace.WriteLine("--------");
        Trace.WriteLine("Response headers:");
        var headers = response.Headers.ToDictionary(kvp => kvp.Key, kvp => kvp.Value);
        foreach(var header in headers)
        {
            Trace.WriteLine($"{header.Key}: {header.Value}");
        }

        Trace.WriteLine("--------");

        await response.Content.LoadIntoBufferAsync(); //needs to called else the following line fails
        var contentLength = response.Content.Headers.ContentLength;
        Debug.WriteLine("Response headers ("from content"):");
        var contentHeaders = response.Content.Headers.ToDictionary(kvp => kvp.Key, kvp => kvp.Value);
        foreach (var header in contentHeaders)
        {
            Trace.WriteLine($"{header.Key}: {header.Value}");
        }

        return response;
    }
}
```
Set up in DI like this:

```
public static IServiceCollection AddApiClient<T>(this IServiceCollection services)
    where T : class //and where T has HttpClient constructor parameter
{
    services.AddTransient<HttpRequestInfoInterceptor>();

    //.AddHttpClient -> NuGet package Microsoft.Extensions.Http
    services.AddHttpClient<T>(httpClient =>
    {
        httpClient.BaseAddress = new Uri("https://www.example.com/");
    }).AddHttpMessageHandler<HttpRequestInfoInterceptor>();
    return services;
}
```

Output:
```
Response has content: True
--------
Response headers:
Date: System.String[]
Server: System.String[]
X-Powered-By: System.String[]
X-XSS-Protection: System.String[]
X-Frame-Options: System.String[]
Set-Cookie: System.String[]
Upgrade: System.String[]
Connection: System.String[]
Vary: System.String[]
Transfer-Encoding: System.String[]
--------
Response headers ("from content"):
Content-Type: System.String[]
Content-Length: System.String[]
```

When I call the endpoint manually via Swagger UI (which calls `curl` and displays the result in web UI) (note: _from what I read on the internet, `gzip` might be an important piece here_):

``` cache-control: no-store,no-cache,must-revalidate  
content-encoding: gzip 
content-length: 25
content-type: text/plain;charset=UTF-8  
date: Wed,06 Dec 2023 18:54:37 GMT  
expires: Thu,19 Nov 1981 08:52:00 GMT  
pragma: no-cache  
server: Apache  
vary: Accept-Encoding  
x-firefox-spdy: h2  
x-frame-options: SAMEORIGIN  
x-powered-by: CENSORED  
x-xss-protection: 1; mode=block 
```

### .NET Version

8.0.100

**Comment by janseris** [comment]
Note 3: And because of this, ProgressMessageHandler does not know TotalBytes nor ProgressPercentage.

**Comment by MihaZupan** [comment]
Are you setting `AutomaticDecompression` at any point?

**Comment by janseris** [comment]
@MihaZupan No unless generated ApiClient from NSwag Studio would be doing it.

**Comment by MihaZupan** [comment]
The missing headers in your case appear to be "content-encoding" and "content-length".
This is consistent with the behavior you would see for compressed responses when you have `AutomaticDecompression` set.
See #42789 - The `Content-Length` that the server sends indicates how many bytes long the content will be. But if we're decompressing the content, that content length value is now misleading as it doesn't match the amount of decompressed data you can read from the `HttpContent`. `Content-Encoding` would likewise be misleading as the content is no longer encoded, and so the header is removed.

> Note 2: response.Content.Stream.Length nor response.Content.Stream.Position are supported

Unless the content is explicitly buffered beforehand, the response streams aren't seekable (as indicated by the `CanSeek` property).

---

Can you run the program under the debugger and check if the HttpClientHandler used has `AutomaticDecompression` set?
If not, can you provide a minimal runnable project that reproduces the issue?

**Comment by janseris** [comment]
> The missing headers in your case appear to be "content-encoding" and "content-length". This is consistent with the behavior you would see for compressed responses when you have `AutomaticDecompression` set. See #42789 - The `Content-Length` that the server sends indicates how many bytes long the content will be. But if we're decompressing the content, that content length value is now misleading as it doesn't match the amount of decompressed data you can read from the `HttpContent`. `Content-Encoding` would likewise be misleading as the content is no longer encoded, and so the header is removed.
> 
> > Note 2: response.Content.Stream.Length nor response.Content.Stream.Position are supported
> 
> Unless the content is explicitly buffered beforehand, the response streams aren't seekable (as indicated by the `CanSeek` property).
> 
> Can you run the program under the debugger and check if the HttpClientHandler used has `AutomaticDecompression` set? If not, can you provide a minimal runnable project that reproduces the issue?

I am using System.Net.Http.DelegatingHandler.
Where can I find that AutomaticDecompression property?

**Comment by MihaZupan** [comment]
> Where can I find that AutomaticDecompression property?

In your `DelegatingHanlder`, you can access the `HttpClientHandler` through the `InnerHandler` property (may have to go through multiple delegating handlers to reach it). That handler will have an `AutomaticDecompression` property.

> Content-Length in HttpResponseMessage.Headers would be gzip Content-Length

We can't know the decompressed size until you read and decompress the whole content, and in a delegating handler the content isn't buffered by default.

**Comment by janseris** [comment]
> > Where can I find that AutomaticDecompression property?
> 
> In your `DelegatingHanlder`, you can access the `HttpClientHandler` through the `InnerHandler` property (may have to go through multiple delegating handlers to reach it). That handler will have an `AutomaticDecompression` property.
> 
> > Content-Length in HttpResponseMessage.Headers would be gzip Content-Length
> 
> We can't know the decompressed size until you read and decompress the whole content, and in a delegating handler the content isn't buffered by default.

Thanks. I will check the InnerHandler.
I don't need to know decompressed size. I need to know the origin Content-Length from the HTTPResponse which is the gzipped content length (I care about how many bytes are transferred through the network which is exactly that).

**Comment by MihaZupan** [comment]
For that the only current workaround is not to use automatic decompression - see https://github.com/dotnet/runtime/issues/42789#issuecomment-699628305

**Comment by janseris** [comment]
> For that the only current workaround is not to use automatic decompression - see [#42789 (comment)](https://github.com/dotnet/runtime/issues/42789#issuecomment-699628305)

What is the reason that it is removed? That is unexpected. Why workaround? Are there any plans to include that back properly? It seems like a basic functionality of HTTP Request and Response.

**Comment by MihaZupan** [comment]
> What is the reason that it is removed?

The values are no longer correct for the decompressed content.

https://github.com/dotnet/runtime/issues/95708#issuecomment-1850455664

> See #42789 - The `Content-Length` that the server sends indicates how many bytes long the content will be. But if we're decompressing the content, that content length value is now misleading as it doesn't match the amount of decompressed data you can read from the `HttpContent`. `Content-Encoding` would likewise be misleading as the content is no longer encoded, and so the header is removed.

**Comment by janseris** [comment]
Thanks.

> The values are no longer correct for the decompressed content.

Yes and that's not expected. HTTP Response header content-length talks about how many data are sent over the network and this info should not be silently dropped.
If the content is then somehow transformed, it makes sense that HttpContent.Length would change after decompression or similar because it refers to the C# representation of the response body. 
But headers of the response should be referring to the headers that the response contains.
