### ISSUE TITLE
ReadOnlySpan<byte> SequenceEqual method seems to have regressed 25-30% between .Net 6 and .Net 8

### ISSUE THREAD

**Issue by radurd** [dotnet/runtime#95703]
### Description

Here is the Benchmark.Net code that shows the problem:
```csharp
public class BenchCompareByteArrays
{
    [Params(100, 1000, 100000)]
    public int ItemsCount { get; set; }

    public byte[] Array1 { get; set; }
    public byte[] Array2 { get; set; }

    [GlobalSetup]
    public void GlobalSetup()
    {
        Array1 = new byte[ItemsCount];
        Array2 = new byte[ItemsCount];
        var random = new Random();
        random.NextBytes(Array1);
        Array1.CopyTo(Array2, 0);
    }

    [Benchmark]
    public bool CompareSpan() => AreEqual(Array1, Array2);

    static bool AreEqual(ReadOnlySpan<byte> bytes1, ReadOnlySpan<byte> bytes2) => bytes1.SequenceEqual(bytes2);
}
```

Here is how I run it:
`dotnet run -c Release -f net6.0 --runtimes net6.0 net8.0 -m -d --filter *BenchCompareByteArrays* --join`

### Configuration

Here are the results:
`BenchmarkDotNet v0.13.6, Windows 10 (10.0.19044.3693/21H2/November2021Update)
12th Gen Intel Core i9-12900H, 1 CPU, 20 logical and 14 physical cores
.NET SDK 8.0.100
  [Host]     : .NET 6.0.25 (6.0.2523.51912), X64 RyuJIT AVX2
  Job-RMGMFV : .NET 6.0.25 (6.0.2523.51912), X64 RyuJIT AVX2
  Job-EGTDYB : .NET 8.0.0 (8.0.23.53103), X64 RyuJIT AVX2

|      Method |  Runtime | ItemsCount |         Mean |      Error |     StdDev | Ratio | Code Size | Allocated |
|------------ |--------- |----------- |-------------:|-----------:|-----------:|------:|----------:|----------:|
| CompareSpan | .NET 6.0 |        100 |     2.771 ns |  0.0569 ns |  0.0475 ns |  1.00 |     403 B |         - |
| CompareSpan | .NET 8.0 |        100 |     3.608 ns |  0.0338 ns |  0.0316 ns |  1.30 |     399 B |         - |
|             |          |            |              |            |            |       |           |           |
| CompareSpan | .NET 6.0 |       1000 |    16.148 ns |  0.1903 ns |  0.1589 ns |  1.00 |     403 B |         - |
| CompareSpan | .NET 8.0 |       1000 |    17.886 ns |  0.3620 ns |  0.5075 ns |  1.12 |     399 B |         - |
|             |          |            |              |            |            |       |           |           |
| CompareSpan | .NET 6.0 |     100000 | 1,997.293 ns | 36.3205 ns | 33.9742 ns |  1.00 |     403 B |         - |
| CompareSpan | .NET 8.0 |     100000 | 2,536.925 ns |  8.8756 ns |  7.4115 ns |  1.27 |     399 B |         - |`

**Comment by EgorBo** [comment]
Looks like a dup of https://github.com/dotnet/runtime/issues/95346 ?

**Comment by JulieLeeMSFT** [comment]
Hi @radurd, closing this as a duplicate. Please feel free to reopen if you think it is not.
 
> Looks like a dup of #95346 ?
