### ISSUE TITLE
FrozenDictionary case insensitive comparer not working correctly

### ISSUE THREAD

**Issue by jprpicw** [dotnet/runtime#95732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Trying to get a value by a string key with a case insensitive comparer does not work as intended.

Initializing a FrozenDictionary with a StringComparer.OrdinalIgnoreCase comparer and then trying a GetValueOrDefault returns empty string if the key within the dictionary and passed parameter differ in casing.

### Expected Behavior

Behavior should be the same as when doing the same with plain Dictionary.

### Steps To Reproduce

            var frozenDict = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
		{
			{ "key", "value" }
		}.ToFrozenDictionary();
		
		var dict = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
		{
			{ "key", "value" }
		};
		
		Console.WriteLine(frozenDict.GetValueOrDefault("KEY"));
		Console.WriteLine(dict.GetValueOrDefault("KEY"));

### .NET Version

8.0

**Comment by martincostello** [comment]
@danmoseley Yeah the aspnetcore triagers group don't have the ability to do that. My hunch is that you need write access to both the source and the target to be allowed to do that.

If that's the case, maybe there could be some sort of fabric bot command that lets triagers ask it do do the honours?
