### ISSUE TITLE
[API Proposal]: Remove Minimum or Maximum from SortedSet<T> in O(log n) time without comparisons

### ISSUE THREAD

**Issue by richardcocks** [dotnet/runtime#95780]
### Description
Given a collection `var items = SortedSet<T>`, I want to remove the Minimum Value from `items`.

Currently to do this, I have to do `items.Remove(item.Min)`.

In practical profiling this is slow because it has to first navigate the tree down the left for the node, then find the same node again with a tree search to remove it in `SortedSet.Remove`.

To find top 50 items from 100_000_000, I found it faster to use a regular array and do an `Array.sort` after every insert than to use a `SortedSet` over the top 50 items. I was expecting better performance from a `SortedSet`, the data structure ought to be ideal for this purpose.

This performance bottleneck could be fixed with a `RemoveMin()` method which removes the left-most node directly without having to also find the node.

### Configuration

BenchmarkDotNet v0.13.11, Windows 10 (10.0.19045.3693/22H2/2022Update)
AMD Ryzen 7 3800X, 1 CPU, 16 logical and 8 physical cores
.NET SDK 8.0.100
  [Host]     : .NET 8.0.0 (8.0.23.53103), X64 RyuJIT AVX2
  DefaultJob : .NET 8.0.0 (8.0.23.53103), X64 RyuJIT AVX2

### Data

| Method               | TopN | HaystackSize | Mean           | Error        | StdDev       | Ratio | RatioSD | Gen0     | Gen1     | Gen2     | Allocated     | Alloc Ratio |
|--------------------- |----- |------------- |---------------:|-------------:|-------------:|------:|--------:|---------:|---------:|---------:|--------------:|------------:|
| NaiveOrderByTake     | 50   | 10000        |       159.4 μs |      2.05 μs |      1.92 μs |  0.70 |    0.01 |  23.6816 |   7.8125 |        - |     195.97 KB |        9.98 |
| WithVisitor          | 50   | 10000        |       226.8 μs |      2.49 μs |      2.33 μs |  1.00 |    0.00 |   2.1973 |        - |        - |      19.63 KB |        1.00 |
| WithSortedSetVisitor | 50   | 10000        |       153.5 μs |      2.59 μs |      2.42 μs |  0.68 |    0.01 |   1.7090 |        - |        - |      15.05 KB |        0.77 |
|                      |      |              |                |              |              |       |         |          |          |          |               |             |
| NaiveOrderByTake     | 50   | 1000000      |    28,075.8 μs |    213.35 μs |    199.57 μs |  3.35 |    0.05 | 187.5000 | 187.5000 | 187.5000 |   19531.99 KB |      591.63 |
| WithVisitor          | 50   | 1000000      |     8,391.1 μs |    120.66 μs |    112.87 μs |  1.00 |    0.00 |        - |        - |        - |      33.01 KB |        1.00 |
| WithSortedSetVisitor | 50   | 1000000      |    11,174.5 μs |    166.84 μs |    156.06 μs |  1.33 |    0.02 |        - |        - |        - |      25.08 KB |        0.76 |
|                      |      |              |                |              |              |       |         |          |          |          |               |             |
| NaiveOrderByTake     | 50   | 100000000    | 2,044,716.6 μs | 32,768.88 μs | 30,652.03 μs |  2.43 |    0.08 |        - |        - |        - | 1953126.05 KB |   40,670.27 |
| WithVisitor          | 50   | 100000000    |   839,108.0 μs | 16,651.02 μs | 21,058.21 μs |  1.00 |    0.00 |        - |        - |        - |      48.02 KB |        1.00 |
| WithSortedSetVisitor | 50   | 100000000    | 1,147,082.3 μs | 21,936.01 μs | 24,381.82 μs |  1.37 |    0.04 |        - |        - |        - |      36.44 KB |        0.76 |

`NaiveOrderByTake` is `.OrderByDescending(x => x.score).Take(this.TopN).ToList()`, this is fast for a small haystack and very expensive for a large one.

`WithVisitor` is an implementation of using a simple array of length `TopN`, then appending to `items[]` or once full overwriting `items[0]`, then calling `Array.Sort(items)` after every `Add`.

`WithSortedSetVisitor` was an attempt for more efficiency by using `SortedSet<T>` instead of an array so it would not need re-sorting.

With a `TopN` size of 50, the Array solution is most efficient (once the `Haystack` is large enough that the naive approach fails), but I believe that without the redundant time spent searching in `SortedSet<T>.Remove()` that it would be quickest.

I am working to prove this within this benchmark, but it's not easy to port the full `SortedSet<T>` code, but I may produce a cut-down equivalent R-B tree implementation to prove the case that `RemoveMin` would be a significant speedup.

### API Proposal

```csharp
namespace System.Collections.Generic;

public class SortedSet<T>
{
    public void RemoveMin(); // Removes the Minimum from the SortedSet in O(log n) and without comparisons
    public void RemoveMax(); // Removes the Maximum from the SortedSet in O(log n) and without comparisons
}
```

### Current 
```csharp
var c = new SortedSet<int>(){2,1,7,4,5};
c.Remove(c.Min); // This is an "expensive" operation
c.Remove(c.Max); // This likewise has to do comparisons while walking a tree it already walked when getting Max.
```
Set is now `{2, 3, 4}`.

### Proposed
```csharp
var c = new SortedSet<int>(){2,1,7,4,5};
c.RemoveMin();
c.RemoveMax();
```
Set is now `{2, 3, 4}`.

### Alternative Designs

Alternatively, similar functionality could be provided by a `BoundedSortedSet<T>` which always efficiently trims entries from the tree to maintain a given `Capacity`.

### Risks

"API bloat" is a risk, some people may be opposed to adding more public properties to `SortedSet`. In that case, a specialised `BoundedSortedSet<T>` which always prunes to a given capacity may be preferable.

**Comment by richardcocks** [comment]
Additional justification:

`LinkedList<T>` has methods `RemoveFirst()` and `RemoveLast()`.

**Comment by eiriktsarpalis** [comment]
I'm not sure I understand what these benchmark results are measuring, could you share the code? An apples-to-apples comparison would require using a custom SortedSet implementation with the proposed APIs that only measures the "remove max" and "remove min" operations in isolation.

That aside, the proposed APIs seem weirdly specific and I doubt they would benefit many users. Both the existing workaround and proposed solution are $\mathcal O(\log n)$, the only difference is avoiding a secondary search. I'm not sure how the cost of that compares to the cost of updating the tree, but a relevant benchmark should be able to shed light on that.

**Comment by eiriktsarpalis** [comment]
> I disagree that it is "weirdly specific" given there are similar methods for other collections.

Are there any cases beyond LinkedList? I would argue that it's a different data structure that has been designed with this type of manipulation in mind.

**Comment by richardcocks** [comment]
I should note however that after further investgiation the performance difference in my original post wasn't due to this, sorting small arrays is just a lot faster than it has any right to be.

**Comment by Clockwork-Muse** [comment]
> Currently to do this, I have to do `items.Remove(item.Min)`

As the size of your source increases, especially in proportion to the "top" items, you're pretty quickly going to get to a case where you don't have to add items to the set anymore.  This code implies that you add and remove an item for every element visited, which isn't necessary.

```
for each element in source:
  if element value is less than saved minimum, skip to next element
  add element to sorted collection
  if collection size is greater than desired maximum, remove saved minimum and update saved minimum
```
In the average case you can probably eliminate half the tree traversals just by saving off the minimum value (in the worst case you still have to walk the tree the same number of times, though).

With the use of a specialty data structure you can probably do better at insertions and updates (eg, to avoid things like needing to rebalance the tree).

**Comment by richardcocks** [comment]
@Clockwork-Muse  - Indeed, and I'm already doing that. 

I'll try to clean up my examples and share some code.

I'm sure a special data structure will be even faster, I was just surprised that a `SortedSet` is performing worse than an array and calling `Array.Sort` after every insert.

That said, the bucket sizes I've tested are very small (50-1000) of so I suppose it's not surprising that `Array.Sort` is quicker than any kind of node manipulation or overhead of a tree.
