### ISSUE TITLE
[wasm] `Assertion: should not be reached at D:/a/_work/1/s/src/mono/mono/sgen/sgen-scan-object.h:93` in `System.Reflection.Tests`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#95805]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=629971
Build error leg or test failing: WasmTestOnBrowser-System.Linq.Expressions.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/95738

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "Assertion: should not be reached at .*src/mono/mono/sgen/sgen-scan-object.h:93",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-100855-merge-a6d1666c5b5d48cd86/WasmTestOnBrowser-System.Reflection.Tests/1/console.37d2541d.log?helixlogtype=result)
```
[08:32:20] fail: [0x05bf02f0-long 08:32:20.979] [MONO] * Assertion: should not be reached at /__w/1/s/src/mono/mono/sgen/sgen-scan-object.h:93
                 
                 Error
                     at cu (http://127.0.0.1:46083/_framework/dotnet.runtime.js:3:201010)
                     at wasm_trace_logger (http://127.0.0.1:46083/_framework/dotnet.native.wasm:wasm-function[199]:0x14ac1)
                     at eglib_log_adapter (http://127.0.0.1:46083/_framework/dotnet.native.wasm:wasm-function[693]:0x4bdf2)
                     at monoeg_g_logv_nofree (http://127.0.0.1:46083/_framework/dotnet.native.wasm:wasm-function[615]:0x4a203)
                     at monoeg_assertion_message (http://127.0.0.1:46083/_framework/dotnet.native.wasm:wasm-function[619]:0x4a324)
                     at mono_assertion_message_unreachable (http://127.0.0.1:46083/_framework/dotnet.native.wasm:wasm-function[622]:0x4a38d)
                     at drain_gray_stack (http://127.0.0.1:46083/_framework/dotnet.native.wasm:wasm-function[1042]:0x5b8b8)
                     at finish_gray_stack (http://127.0.0.1:46083/_framework/dotnet.native.wasm:wasm-function[958]:0x573b6)
                     at major_do_collection (http://127.0.0.1:46083/_framework/dotnet.native.wasm:wasm-function[932]:0x553f9)
                     at sgen_perform_collection (http://127.0.0.1:46083/_framework/dotnet.native.wasm:wasm-function[928]:0x54543)
                     at sgen_gc_collect (http://127.0.0.1:46083/_framework/dotnet.native.wasm:wasm-function[945]:0x5674a)
                     at mono_gc_collect (http://127.0.0.1:46083/_framework/dotnet.native.wasm:wasm-function[3189]:0xf1e7f)
                     at ves_icall_System_GC_InternalCollect (http://127.0.0.1:46083/_framework/dotnet.native.wasm:wasm-function[3118]:0xee579)
                     at do_icall (http://127.0.0.1:46083/_framework/dotnet.native.wasm:wasm-function[338]:0x28e37)
                     at do_icall_wrapper (http://127.0.0.1:46083/_framework/dotnet.native.wasm:wasm-function[267]:0x2648f)
                     at mono_interp_exec_method (http://127.0.0.1:46083/_framework/dotnet.native.wasm:wasm-function[258]:0x18d33)
                     at interp_runtime_invoke (http://127.0.0.1:46083/_framework/dotnet.native.wasm:wasm-function[297]:0x2711d)
                     at mono_jit_runtime_invoke (http://127.0.0.1:46083/_framework/dotnet.native.wasm:wasm-function[3349]:0xfd935)
                     at do_runtime_invoke (http://127.0.0.1:46083/_framework/dotnet.native.wasm:wasm-function[2629]:0xd01b2)
                     at mono_runtime_invoke_checked (http://127.0.0.1:46083/_framework/dotnet.native.wasm:wasm-function[2628]:0xd0142)
                     at ves_icall_InternalInvoke_raw (http://127.0.0.1:46083/_framework/dotnet.native.wasm:wasm-function[1985]:0xaab63)
                     at do_icall (http://127.0.0.1:46083/_framework/dotnet.native.wasm:wasm-function[338]:0x28edf)
                     at do_icall_wrapper (http://127.0.0.1:46083/_framework/dotnet.native.wasm:wasm-function[267]:0x2648f)
                     at mono_interp_exec_method (http://127.0.0.1:46083/_framework/dotnet.native.wasm:wasm-function[258]:0x18d33)
                     at interp_runtime_invoke (http://127.0.0.1:46083/_framework/dotnet.native.wasm:wasm-function[297]:0x2711d)
                     at mono_jit_runtime_invoke (http://127.0.0.1:46083/_framework/dotnet.native.wasm:wasm-function[3349]:0xfd935)
                     at do_runtime_invoke (http://127.0.0.1:46083/_framework/dotnet.native.wasm:wasm-function[2629]:0xd01b2)
                     at mono_runtime_invoke_checked (http://127.0.0.1:46083/_framework/dotnet.native.wasm:wasm-function[2628]:0xd0142)
                     at start_wrapper (http://127.0.0.1:46083/_framework/dotnet.native.wasm:wasm-function[2777]:0xd735b)
                     at Object.invokeEntryPoint (http://127.0.0.1:46083/_framework/dotnet.native.js:8:69009)
                     at handleMessage (http://127.0.0.1:46083/_framework/dotnet.native.worker.js:1:2306)
```

cc @vargaz @lambdageek

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[671701](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671701)|dotnet/runtime|[WasmTestOnChrome-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671701&view=ms.vss-test-web.build-test-results-tab&runId=16654494&resultId=177510)||
|[670314](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670314)|dotnet/runtime|[WasmTestOnChrome-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670314&view=ms.vss-test-web.build-test-results-tab&runId=16619106&resultId=177550)|dotnet/runtime#100266|
|[670311](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670311)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Collections.Concurrent.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670311&view=ms.vss-test-web.build-test-results-tab&runId=16619104&resultId=186085)|dotnet/runtime#100266|
|[670263](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670263)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670263&view=ms.vss-test-web.build-test-results-tab&runId=16617996&resultId=177529)||
|[669665](https://dev.azure.com/dnceng-public/public/_build/results?buildId=669665)|dotnet/runtime|[WasmTestOnChrome-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=669665&view=ms.vss-test-web.build-test-results-tab&runId=16617592&resultId=177473)|dotnet/runtime#101871|
|[670251](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670251)|dotnet/runtime|[WasmTestOnChrome-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670251&view=ms.vss-test-web.build-test-results-tab&runId=16617552&resultId=177550)|dotnet/runtime#101681|
|[670248](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670248)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670248&view=ms.vss-test-web.build-test-results-tab&runId=16617536&resultId=177529)|dotnet/runtime#102039|
|[669355](https://dev.azure.com/dnceng-public/public/_build/results?buildId=669355)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=669355&view=ms.vss-test-web.build-test-results-tab&runId=16600238&resultId=177529)|dotnet/runtime#101977|
|[667200](https://dev.azure.com/dnceng-public/public/_build/results?buildId=667200)|dotnet/runtime|[WasmTestOnChrome-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=667200&view=ms.vss-test-web.build-test-results-tab&runId=16562336&resultId=177550)|dotnet/runtime#101934|
|[667292](https://dev.azure.com/dnceng-public/public/_build/results?buildId=667292)|dotnet/runtime|[WasmTestOnChrome-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=667292&view=ms.vss-test-web.build-test-results-tab&runId=16550392&resultId=177550)|dotnet/runtime#101337|
|[666657](https://dev.azure.com/dnceng-public/public/_build/results?buildId=666657)|dotnet/runtime|[WasmTestOnChrome-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=666657&view=ms.vss-test-web.build-test-results-tab&runId=16538016&resultId=176671)|dotnet/runtime#101717|
|[666620](https://dev.azure.com/dnceng-public/public/_build/results?buildId=666620)|dotnet/runtime|[WasmTestOnChrome-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=666620&view=ms.vss-test-web.build-test-results-tab&runId=16537074&resultId=177550)|dotnet/runtime#101844|
|[666493](https://dev.azure.com/dnceng-public/public/_build/results?buildId=666493)|dotnet/runtime|[WasmTestOnChrome-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=666493&view=ms.vss-test-web.build-test-results-tab&runId=16532222&resultId=177550)|dotnet/runtime#101681|
|[666136](https://dev.azure.com/dnceng-public/public/_build/results?buildId=666136)|dotnet/runtime|[WasmTestOnChrome-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=666136&view=ms.vss-test-web.build-test-results-tab&runId=16522634&resultId=177507)|dotnet/runtime#101843|
|[665654](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665654)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665654&view=ms.vss-test-web.build-test-results-tab&runId=16510466&resultId=177486)|dotnet/runtime#101843|
|[665447](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665447)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665447&view=ms.vss-test-web.build-test-results-tab&runId=16503796&resultId=173262)|dotnet/runtime#101871|
|[664531](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664531)|dotnet/runtime|[WasmTestOnChrome-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664531&view=ms.vss-test-web.build-test-results-tab&runId=16483010&resultId=177507)|dotnet/runtime#101842|
|[664390](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664390)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664390&view=ms.vss-test-web.build-test-results-tab&runId=16477222&resultId=177529)||
|[664211](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664211)|dotnet/runtime|[WasmTestOnChrome-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664211&view=ms.vss-test-web.build-test-results-tab&runId=16471528&resultId=177550)|dotnet/runtime#101162|
|[664022](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664022)|dotnet/runtime|[WasmTestOnChrome-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664022&view=ms.vss-test-web.build-test-results-tab&runId=16465504&resultId=177510)|dotnet/runtime#101828|
|[663140](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663140)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663140&view=ms.vss-test-web.build-test-results-tab&runId=16442076&resultId=177529)|dotnet/runtime#101716|
|[662281](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662281)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662281&view=ms.vss-test-web.build-test-results-tab&runId=16417604&resultId=177529)||
|[661662](https://dev.azure.com/dnceng-public/public/_build/results?buildId=661662)|dotnet/runtime|[WasmTestOnChrome-MT-System.Collections.Concurrent.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=661662&view=ms.vss-test-web.build-test-results-tab&runId=16403256&resultId=186106)|dotnet/runtime#100266|
|[661154](https://dev.azure.com/dnceng-public/public/_build/results?buildId=661154)|dotnet/runtime|[WasmTestOnChrome-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=661154&view=ms.vss-test-web.build-test-results-tab&runId=16387440&resultId=177425)|dotnet/runtime#101715|
|[661111](https://dev.azure.com/dnceng-public/public/_build/results?buildId=661111)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=661111&view=ms.vss-test-web.build-test-results-tab&runId=16386232&resultId=176650)||
|[661068](https://dev.azure.com/dnceng-public/public/_build/results?buildId=661068)|dotnet/runtime|[WasmTestOnChrome-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=661068&view=ms.vss-test-web.build-test-results-tab&runId=16385310&resultId=175743)|dotnet/runtime#101712|
|[660999](https://dev.azure.com/dnceng-public/public/_build/results?buildId=660999)|dotnet/runtime|[WasmTestOnChrome-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=660999&view=ms.vss-test-web.build-test-results-tab&runId=16383086&resultId=177550)|dotnet/runtime#100266|
|[661010](https://dev.azure.com/dnceng-public/public/_build/results?buildId=661010)|dotnet/runtime|[WasmTestOnChrome-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=661010&view=ms.vss-test-web.build-test-results-tab&runId=16382982&resultId=177550)|dotnet/runtime#101693|
|[661006](https://dev.azure.com/dnceng-public/public/_build/results?buildId=661006)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Threading.Tasks.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=661006&view=ms.vss-test-web.build-test-results-tab&runId=16382830&resultId=186359)|dotnet/runtime#101693|
|[660346](https://dev.azure.com/dnceng-public/public/_build/results?buildId=660346)|dotnet/runtime|[WasmTestOnChrome-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=660346&view=ms.vss-test-web.build-test-results-tab&runId=16363210&resultId=177506)|dotnet/runtime#101162|
|[660018](https://dev.azure.com/dnceng-public/public/_build/results?buildId=660018)|dotnet/runtime|[WasmTestOnChrome-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=660018&view=ms.vss-test-web.build-test-results-tab&runId=16354246&resultId=177549)|dotnet/runtime#101318|
|[659851](https://dev.azure.com/dnceng-public/public/_build/results?buildId=659851)|dotnet/runtime|[WasmTestOnChrome-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=659851&view=ms.vss-test-web.build-test-results-tab&runId=16348920&resultId=177506)||
|[659547](https://dev.azure.com/dnceng-public/public/_build/results?buildId=659547)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=659547&view=ms.vss-test-web.build-test-results-tab&runId=16337924&resultId=177526)|dotnet/runtime#101529|
|[659097](https://dev.azure.com/dnceng-public/public/_build/results?buildId=659097)|dotnet/runtime|[WasmTestOnChrome-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=659097&view=ms.vss-test-web.build-test-results-tab&runId=16325882&resultId=177547)|dotnet/runtime#101672|
|[658322](https://dev.azure.com/dnceng-public/public/_build/results?buildId=658322)|dotnet/runtime|[WasmTestOnChrome-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=658322&view=ms.vss-test-web.build-test-results-tab&runId=16305656&resultId=177547)|dotnet/runtime#101653|
|[658219](https://dev.azure.com/dnceng-public/public/_build/results?buildId=658219)|dotnet/runtime|[WasmTestOnChrome-System.Memory.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=658219&view=ms.vss-test-web.build-test-results-tab&runId=16303386&resultId=184213)||
|[657933](https://dev.azure.com/dnceng-public/public/_build/results?buildId=657933)|dotnet/runtime|[WasmTestOnChrome-MT-System.Collections.Concurrent.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=657933&view=ms.vss-test-web.build-test-results-tab&runId=16295236&resultId=186102)||
|[657224](https://dev.azure.com/dnceng-public/public/_build/results?buildId=657224)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=657224&view=ms.vss-test-web.build-test-results-tab&runId=16275018&resultId=177527)|dotnet/runtime#101599|
|[656949](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656949)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656949&view=ms.vss-test-web.build-test-results-tab&runId=16266476&resultId=186856)|dotnet/runtime#101532|
|[656887](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656887)|dotnet/runtime|[WasmTestOnChrome-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656887&view=ms.vss-test-web.build-test-results-tab&runId=16265048&resultId=177505)||
|[656594](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656594)|dotnet/runtime|[WasmTestOnChrome-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656594&view=ms.vss-test-web.build-test-results-tab&runId=16256986&resultId=177548)|dotnet/runtime#101538|
|[656049](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656049)|dotnet/runtime|[WasmTestOnChrome-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656049&view=ms.vss-test-web.build-test-results-tab&runId=16241098&resultId=177548)|dotnet/runtime#100141|
|[655885](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655885)|dotnet/runtime|[WasmTestOnChrome-System.Collections.Concurrent.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655885&view=ms.vss-test-web.build-test-results-tab&runId=16236908&resultId=186104)|dotnet/runtime#101378|
|[655832](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655832)|dotnet/runtime|[WasmTestOnChrome-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655832&view=ms.vss-test-web.build-test-results-tab&runId=16236254&resultId=177424)|dotnet/runtime#101330|
|[655742](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655742)|dotnet/runtime|[WasmTestOnChrome-System.Collections.Concurrent.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655742&view=ms.vss-test-web.build-test-results-tab&runId=16233054&resultId=186061)|dotnet/runtime#101532|
|[655571](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655571)|dotnet/runtime|[WasmTestOnChrome-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655571&view=ms.vss-test-web.build-test-results-tab&runId=16228068&resultId=191596)|dotnet/runtime#101392|
|[655262](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655262)|dotnet/runtime|[WasmTestOnChrome-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655262&view=ms.vss-test-web.build-test-results-tab&runId=16219312&resultId=177548)|dotnet/runtime#101460|
|[655218](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655218)|dotnet/runtime|[WasmTestOnV8-System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655218&view=ms.vss-test-web.build-test-results-tab&runId=16217912&resultId=175297)|dotnet/runtime#101318|
|[655024](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655024)|dotnet/runtime|[WasmTestOnChrome-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655024&view=ms.vss-test-web.build-test-results-tab&runId=16210316&resultId=177548)|dotnet/runtime#101509|
|[653322](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653322)|dotnet/runtime|[WasmTestOnChrome-System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653322&view=ms.vss-test-web.build-test-results-tab&runId=16202062&resultId=180754)|dotnet/runtime#101188|
|[653807](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653807)|dotnet/runtime|[WasmTestOnChrome-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653807&view=ms.vss-test-web.build-test-results-tab&runId=16175532&resultId=177510)|dotnet/runtime#101442|
|[653607](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653607)|dotnet/runtime|[WasmTestOnChrome-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653607&view=ms.vss-test-web.build-test-results-tab&runId=16170106&resultId=177468)|dotnet/runtime#101397|
|[653383](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653383)|dotnet/runtime|[WasmTestOnChrome-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653383&view=ms.vss-test-web.build-test-results-tab&runId=16163964&resultId=177511)|dotnet/runtime#101330|
|[653346](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653346)|dotnet/runtime|[WasmTestOnV8-System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653346&view=ms.vss-test-web.build-test-results-tab&runId=16163628&resultId=165481)|dotnet/runtime#101425|
|[653343](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653343)|dotnet/runtime|[WasmTestOnChrome-System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653343&view=ms.vss-test-web.build-test-results-tab&runId=16161910&resultId=180754)|dotnet/runtime#101424|
|[652841](https://dev.azure.com/dnceng-public/public/_build/results?buildId=652841)|dotnet/runtime|[WasmTestOnChrome-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=652841&view=ms.vss-test-web.build-test-results-tab&runId=16145202&resultId=177455)|dotnet/runtime#101263|
|[652424](https://dev.azure.com/dnceng-public/public/_build/results?buildId=652424)|dotnet/runtime|[WasmTestOnChrome-System.Collections.Concurrent.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=652424&view=ms.vss-test-web.build-test-results-tab&runId=16135434&resultId=186052)|dotnet/runtime#101397|
|[652287](https://dev.azure.com/dnceng-public/public/_build/results?buildId=652287)|dotnet/runtime|[WasmTestOnChrome-ST-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=652287&view=ms.vss-test-web.build-test-results-tab&runId=16131046&resultId=177455)|dotnet/runtime#100697|
|[652019](https://dev.azure.com/dnceng-public/public/_build/results?buildId=652019)|dotnet/runtime|[WasmTestOnChrome-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=652019&view=ms.vss-test-web.build-test-results-tab&runId=16123476&resultId=100604)|dotnet/runtime#101381|
|[650948](https://dev.azure.com/dnceng-public/public/_build/results?buildId=650948)|dotnet/runtime|[WasmTestOnChrome-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=650948&view=ms.vss-test-web.build-test-results-tab&runId=16092734&resultId=177490)|dotnet/runtime#101345|
|[650709](https://dev.azure.com/dnceng-public/public/_build/results?buildId=650709)|dotnet/runtime|[WasmTestOnChrome-System.Collections.Concurrent.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=650709&view=ms.vss-test-web.build-test-results-tab&runId=16087530&resultId=177357)|dotnet/runtime#101339|
|[650699](https://dev.azure.com/dnceng-public/public/_build/results?buildId=650699)|dotnet/runtime|[WasmTestOnChrome-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=650699&view=ms.vss-test-web.build-test-results-tab&runId=16087296&resultId=177490)|dotnet/runtime#101337|
|[650691](https://dev.azure.com/dnceng-public/public/_build/results?buildId=650691)|dotnet/runtime|[WasmTestOnChrome-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=650691&view=ms.vss-test-web.build-test-results-tab&runId=16087044&resultId=177490)|dotnet/runtime#101335|
|[650687](https://dev.azure.com/dnceng-public/public/_build/results?buildId=650687)|dotnet/runtime|[WasmTestOnChrome-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=650687&view=ms.vss-test-web.build-test-results-tab&runId=16086808&resultId=169559)|dotnet/runtime#101334|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|64|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=569971
**Error message validated:** `[Assertion: should not be reached at .*src/mono/mono/sgen/sgen-scan-object.h:93`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 2/17/2024 12:38:23 PM UTC

**Comment by pavelsavara** [comment]
there is new occurrence [Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-98492-merge-392e856ffbaa4b27b8/WasmTestOnBrowser-System.Reflection.Tests/1/console.87ffb8be.log?helixlogtype=result)

**Comment by lewing** [comment]
cc @lambdageek

**Comment by pavelsavara** [comment]
Note reflections tests are disabled as [active issue](https://github.com/dotnet/runtime/issues/100932) now for MT, otherwise this would report many more

**Comment by pavelsavara** [comment]
This one is single-threaded OOM followed by broken GC, [Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-101318-merge-db3e89079de642c9af/WasmTestOnV8-System.Text.Json.Tests/1/console.f7655908.log?helixlogtype=result)

```
[23:08:00] info: [FAIL] System.Text.Json.Tests.Utf8JsonWriterTests.WriteJsonOnlyWritesToStreamOnDemand_FlushAsync
[23:08:00] info: System.OutOfMemoryException : Out of memory
[23:08:00] info:    at System.GC.AllocateArray[Char](Int32 length, Boolean pinned)
[23:08:00] info:    at System.Text.StringBuilder.ExpandByABlock(Int32 minBlockCharCount)
...
[23:08:00] info: [MONO] * Assertion: should not be reached at /__w/1/s/src/mono/mono/sgen/sgen-scan-object.h:93
[23:08:00] info: 
[23:08:00] info: Error
[23:08:00] info:     at Kc (/root/helix/work/workitem/e/_framework/dotnet.runtime.js:3:171784)
[23:08:00] info:     at wasm_trace_logger (wasm://wasm/00b9ea7a:wasm-function[163]:0xb23f)
[23:08:00] info:     at eglib_log_adapter (wasm://wasm/00b9ea7a:wasm-function[648]:0x438e1)
[23:08:00] info:     at monoeg_g_logv_nofree (wasm://wasm/00b9ea7a:wasm-function[571]:0x41840)
[23:08:00] info:     at monoeg_assertion_message (wasm://wasm/00b9ea7a:wasm-function[574]:0x41931)
[23:08:00] info:     at mono_assertion_message_unreachable (wasm://wasm/00b9ea7a:wasm-function[576]:0x4198b)
[23:08:00] info:     at simple_nursery_serial_scan_object (wasm://wasm/00b9ea7a:wasm-function[1049]:0x5bcad)
[23:08:00] info:     at simple_nursery_serial_drain_gray_stack (wasm://wasm/00b9ea7a:wasm-function[1046]:0x5ac89)
[23:08:00] info:     at finish_gray_stack (wasm://wasm/00b9ea7a:wasm-function[893]:0x4ee72)
[23:08:00] info:     at collect_nursery (wasm://wasm/00b9ea7a:wasm-function[868]:0x4ca0f)
[23:08:00] info:     at sgen_perform_collection_inner (wasm://wasm/00b9ea7a:wasm-function[866]:0x4c2bf)
[23:08:00] info:     at sgen_perform_collection (wasm://wasm/00b9ea7a:wasm-function[864]:0x4c12f)
[23:08:00] info:     at sgen_ensure_free_space (wasm://wasm/00b9ea7a:wasm-function[863]:0x4c0d6)
[23:08:00] info:     at sgen_alloc_obj_nolock (wasm://wasm/00b9ea7a:wasm-function[849]:0x4b4f8)
[23:08:00] info:     at mono_gc_alloc_vector (wasm://wasm/00b9ea7a:wasm-function[3047]:0xe92b9)
[23:08:00] info:     at mono_array_new_specific_internal (wasm://wasm/00b9ea7a:wasm-function[2616]:0xcf478)
[23:08:00] info:     at mono_array_new_specific_checked (wasm://wasm/00b9ea7a:wasm-function[2617]:0xcf4af)
```

Note, it's not the same stack trace, there are 2 different fails, which means that (possibly another) OOM corrupted the memory for the GC.
Maybe `malloc` returned -1 and the return value was not tested (for which we don't have the stack trace)

**Comment by pavelsavara** [comment]
this seems to be good now, closing. Please open another issue if this appears again
