### ISSUE TITLE
FileSystemWatcher Not working when dotnet8 publish with native aot

### ISSUE THREAD

**Issue by harry266i** [dotnet/runtime#95811]
### Description
FileSystemWatcher Not working when dotnet8 publish with native aot。
step1: use dotnet8 sdk to write a console program
step2: use FileSystemWatcher to watch dir
just like 
```csharp
  public override void InitWatch()
        {
            Watcher = new FileSystemWatcher(fileWatchOption.Path)
            {
                Filter = fileWatchOption.FileName,
                NotifyFilter = NotifyFilters.LastWrite | NotifyFilters.Size | NotifyFilters.FileName
            };
            Watcher.Changed += OnChanged;
            Watcher.IncludeSubdirectories = true;
            Watcher.EnableRaisingEvents = true;

            Console.WriteLine("file watch start to work");

        }

        private void OnChanged(object sender, FileSystemEventArgs e)
        {
            var changeFilePath = e.FullPath;
            HandlerFileChange(changeFilePath);
        }
```

step3: publish the project
add `<PublishAot>true</PublishAot>` to csprjc file
use command `dotnet publish -r win-x64 -c release `

step 4:
when I add `<PublishAot>true</PublishAot>` and publish the app ,the FileSystemWatcher not emit then Onchange Function.
i remove `<PublishAot>true</PublishAot>` and publish the app,it works normally.

### Configuration

system: win10 1909
dotnetsdk: 8.0.100
runtime: Microsoft.WindowsDesktop.App 8.0.0

**Comment by Jozkee** [comment]
I was unable to repro. Had to add a Console.ReadKey since the program was ending before OnChange was called.
I made sure to add `<PublishAot>true</PublishAot>` to csproj file and use command `dotnet publish -r win-x64 -c release`.
```cs
// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");

var dir = Directory.CreateTempSubdirectory();
File.WriteAllText(Path.Combine(dir.FullName, "foo.txt"), "42");

using(var watcher = InitWatch(dir.FullName, "foo.txt"))
{
    File.AppendAllText(Path.Combine(dir.FullName, "foo.txt"), "43");
    Console.ReadKey();
}

static FileSystemWatcher InitWatch(string path, string filter)
{
    var Watcher = new FileSystemWatcher(path)
    {
        Filter = filter,
        NotifyFilter = NotifyFilters.LastWrite | NotifyFilters.Size | NotifyFilters.FileName
    };
    Watcher.Changed += OnChanged;
    Watcher.IncludeSubdirectories = true;
    Watcher.EnableRaisingEvents = true;

    Console.WriteLine("file watch start to work");
    return Watcher;
}

static void OnChanged(object sender, FileSystemEventArgs e)
{
    var changeFilePath = e.FullPath;
    Console.WriteLine($"OnChanged {changeFilePath}");//HandlerFileChange(changeFilePath);
}
```

**Comment by harry266i** [comment]
Thank you for replying to me，I have checked the code on my end
```cashrp
//await new HostBuilder().RunConsoleAsync();
Console.ReadKey();
```
when i use ` HostBuilder().RunConsoleAsync();` the `FileSystemWatcher` not work in native aot,
 i use `console.readKey` to replace `HostBuilder().RunConsoleAsync`,then it works! 

Thank you for your help！
