### ISSUE TITLE
Attempt to use of dynamically created type in the attribute leads to exception

### ISSUE THREAD

**Issue by SnarkOrBoojum2** [dotnet/runtime#95829]
### Description

I dynamically create the type with method that have an attribute. Attribute(not dynamic itself) have a  parameter of type System.Type. As parameter I use another dynamically created type. That is lead to exception whenever I try to get that attribute later using System.Reflection.

### Reproduction Steps

Here, the simple console project that reproduces that problem. Extract the archive, build the project, run ConsoleApp2 application. There will be exception at the last line of method Main().
[ReproductionSolution.zip](https://github.com/dotnet/runtime/files/13625520/ReproductionSolution.zip)

### Expected behavior

It must be allowed to use dynamically created types in the attributes of dynamically created types.

### Actual behavior

While dynamic generation of attributed type by specified method in itself does not lead to exception, the later attempt to read attributes from that type with help of Syste.Reflection spawns it (System.IO.FileNotFound). 

### Regression?

The same functionality works OK under .NET Framework

### Known Workarounds

I don't know any workaround. 
Attempt to help .NET find the dynamic assembly through Resolving event from AssemblyLoadContext leads to unmanaged exception inside the module.

### Configuration

.NET 6
Windows 10
x64

**Comment by buyaa-n** [comment]
> Attempt to help .NET find the dynamic assembly through Resolving event from AssemblyLoadContext leads to unmanaged exception inside the module.

@elinor-fung could you take a look? The repro is attached in the issue description

**Comment by buyaa-n** [comment]
> ### Regression?
> The same functionality works OK under .NET Framework

@SnarkOrBoojum2 the same example actually throws the same exception, not sure what I missed ...

**Comment by elinor-fung** [comment]
> > Attempt to help .NET find the dynamic assembly through Resolving event from AssemblyLoadContext leads to unmanaged exception inside the module.
> 
> @elinor-fung could you take a look? The repro is attached in the issue description

`AssemblyLoadContext.Resolving` does not allow returning dynamically-emitted assemblies (as it affects how they get cached for the ALC). `AppDomain.AssemblyResolve` does.

**Comment by SnarkOrBoojum2** [comment]
Works ok under .NET Framework, if before that line with exception  you insert event handler for AppDomain.CurrentDomain.AssemblyResolve+=(sender,resolveArgs)=>assemblyBuilder;15 февр. 2024 г., в 22:05, Buyaa Namnan ***@***.***> написал(а):﻿

Regression?
The same functionality works OK under .NET Framework

@SnarkOrBoojum2 the same example actually throws the same exception, not sure what I missed ...

**Comment by SnarkOrBoojum2** [comment]
Yes, it was my mistake/ I have the same code for .NET Framework(with name
check and all) but thinking that under .NET new functionality must be used
and I tried

пт, 16 февр. 2024 г. в 00:49, Buyaa Namnan ***@***.***>:

**Comment by SnarkOrBoojum2** [comment]
Yes it was my mistake, i have the same code under .NET Framework with name
check and all, but thinking that under .NET - new functionality must be
used and I tried

AssemblyLoadContext.Default.Resolving+=(AssemblyLoadContext context,
AssemblyName assemblyName) =>
assemblyName.FullName == _assemblyBuilder.FullName ? _assemblyBuilder :
null;

But this doesnt not work(engine exception)

пт, 16 февр. 2024 г. в 00:49, Buyaa Namnan ***@***.***>:

**Comment by elinor-fung** [comment]
> But this doesnt not work(engine exception)

We don't allow returning a dynamically emitted assembly from `AssemblyLoadContext.Resolving`, so the error is expected. In .NET 7 and later, this should come through more clearly:
```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'DynamicAssemblyExample, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
File name: 'DynamicAssemblyExample, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
 ---> System.InvalidOperationException: Dynamically emitted assemblies are unsupported during host-based resolution.
 ```
Whereas it looks like .NET 6 just reported internal error.

**Comment by SnarkOrBoojum2** [comment]
Fixed!

The solution with resolving assemblies through AppDomain.AssemblyResolve is
completely acceptable. If only this functionality (with AppDomain)  will
not become obsolete in the future

пт, 16 февр. 2024 г. в 19:14, Elinor Fung ***@***.***>:
