### ISSUE TITLE
HttpClient Support Data URLs (scheme data:)

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#95838]
### Description

Data urls https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs are a common embed for inline sources where a server connection is not required, however .NET has no way of decoding them.

As they are used interchangeably with http and https a string forward approach would be for HttpClient to understand them; especially since it understand the mime encodings and mime types which can be part of the data url.

### Reproduction Steps

```csharp
using HttpClient httpClient = new();
var result = await httpClient.GetStringAsync ("data:text/plain;base64,SGVsbG8sIFdvcmxkIQ==");
Console.WriteLine(result);
```

### Expected behavior

Console outputs
"Hello World!"

### Actual behavior

ArgumentException `Only 'http' and 'https' schemes are allowed. (Parameter 'requestUri')`

### Regression?

Feature request

**Comment by MihaZupan** [comment]
Is this functionality you would expect `HttpClient` to handle implicitly as opposed to having a dedicated API - e.g. #85164?

At first glance, it feels odd to me that an **Http**Client would be responsible for this, and it could likewise be unexpected for existing code (e.g. with assumptions about the Uris passed through `HttpMessageHandler`s having a host/port).

**Comment by wfurt** [comment]
I agree. Bolting something that is not HTTP to HttpClient seems odd. We should find some better home IMHO if we want to move forward.

**Comment by benaadams** [comment]
> Is this functionality you would expect HttpClient to handle implicitly as opposed to having a dedicated API

Yes as `data:` is a scheme that is equally present where `http:`/`https:` are and looks identical to consumer of content (as well as mime decode); and is simpler to integrate rather than every checking the scheme of the url and then having `if`/`else` logic for handling it.

**Comment by MihaZupan** [comment]
I appreciate the fact that it could simplify scenarios where http & data uris are commonly mixed, but I fear this would not integrate well with the existing APIs on HttpClient(Handler).

Doing this by default is problematic:
- Making data uris a special case in HttpClient to short-circuit and manufacture a response means bypassing custom handlers, which could break users relying on them for things like logging, creating custom response types, etc.
- Flowing the "request" through custom handlers is also problematic as it can easily break assumptions (that HTTP is being used, about the Uri format ...).

Such content is also much more likely to end up in telemetry/logs, as the request isn't describing the location of a resource, but is the resource itself.

Another example could be that file and http uris are also commonly mixed, but we expect the user to handle those themselves.

> and is simpler to integrate rather than every checking the scheme of the url and then having if/else logic for handling it

@CarnaViire offered a suggestion that you could move such logic into a custom `HttpMessageHandler`, making it opt-in while not complicating the calling code. Example: [DataUriHandler.cs](https://gist.github.com/MihaZupan/bfc22cfd9f326505e1b1a50c11f9d6b1)
Would that be a sufficient workaround for your scenarios?

**Comment by ManickaP** [comment]
@benaadams could you answer @MihaZupan questions from https://github.com/dotnet/runtime/issues/95838#issuecomment-1852262732?

**Comment by MihaZupan** [comment]
Any thoughts on the above: https://github.com/dotnet/runtime/issues/95838#issuecomment-1852262732?

**Comment by benaadams** [comment]
> Would that be a sufficient workaround for your scenarios?

Not really as my scenario is being a provider of the html, md or json; and then getting complaints from the consumers that following the links throw or if try/catched are empty if data uris are used when using .NET

Providing additional documentation to say if following links with .NET vs JS; use this hacky parser doesn't feel like pit of success for our users.

**Comment by karelz** [comment]
Triage: As discussed above, we think #85164 is the right way go. The logic does not belong into HttpClient.
Closing. Thanks @benaadams!
