### ISSUE TITLE
NTLM header authentication stopped remembering passwords

### ISSUE THREAD

**Issue by peminator** [dotnet/runtime#95848]
### Description

In Chrome for Android, on intranet website using NTLM auth header, chrome on android offers to store the password every time i enter it, but everytime i return to the site, it shows the login dialog, but DOES NOT offer prefill with my saved password. I suspect the dialog has been modified? Bc it is a popup dialog, similar to javascript alert, confirm, etc... 

Not sure but possible issue, the **page does not use https**

### Reproduction Steps

1. use a website with a NTLM auth header login using Chrome for Android
2. use valid credentials to log in 
3. browser should offer store credentials
4. log out, clear cache
5. revisit website
6. browser asks for credentials using the chrome dialog, but DOES NOT fill the fields, also on username field focus does not offer to fill
7. check, pasword is stored in passwords manager - it is stored

### Expected behavior

in step 6, browser should offer using the stored credentials on focusing any of the dialog fields

### Actual behavior

on revisiting the site in new session, it does not offer the use of stored password for login, 

### Regression?

i dont know version number, but im sure it worked on my phone few weeks ago. Now it does not on Chrome 120.0.6099.43

### Configuration

Andoid 13, Samsung S20FE,  Chrome 120.0.6099.43

**Comment by rzikm** [comment]
I do see how is this related to .NET. From the description it seems .NET is not involved on the client side at all. Is the server implemented in .NET?

Can you check if the Chrome browser was updated recently or check with a previous versions(s)?

**Comment by peminator** [comment]
Awww, somehow used wrong repo. Marking here as closed. Will post to chrome
