### ISSUE TITLE
System.Net.IPNetwork parse CIDR issue

### ISSUE THREAD

**Issue by changhuixu** [dotnet/runtime#95865]
### Description

The official documentation is too succinct that doesn't have much meaningful content.

Now, `IPNetwork` can parse simple CIDR string like this `IPNetwork.TryParse("192.168.1.0/24", out var _)`

but failed to parse
```csharp
IPNetwork.TryParse("2001:0db8::1/64", out var _);
```

Is there a plan to improve this functionality?

### Reproduction Steps

https://dotnetfiddle.net/0j9T3g

You can try this dotnet fiddle

### Expected behavior

Can parse CIDR correctly.

### Actual behavior

not yet

### Configuration

.NET 8 
Windows, x64

**Comment by antonfirsov** [comment]
As the [docs note](https://learn.microsoft.com/en-us/dotnet/api/system.net.ipnetwork#remarks)

> This type disallows arbitrary IP-address/prefix-length CIDR pairs. [BaseAddress](https://learn.microsoft.com/en-us/dotnet/api/system.net.ipnetwork.baseaddress?view=net-8.0#system-net-ipnetwork-baseaddress) must be defined so that all bits after the network prefix are set to zero. In other words, [BaseAddress](https://learn.microsoft.com/en-us/dotnet/api/system.net.ipnetwork.baseaddress?view=net-8.0#system-net-ipnetwork-baseaddress) is always the first usable address of the network. The constructor and the parsing methods will throw in case there are non-zero bits after the prefix.

@changhuixu is this limitation problematic for you?
