### ISSUE TITLE
Failing test - `System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest` on Linux/arm64

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#95873]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=495334
Build error leg or test failing: System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest
Pull request: https://github.com/dotnet/runtime/pull/95819

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Exit code was 134 but it should have been 42",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

Similar to https://github.com/dotnet/runtime/issues/85960 ?
cc @lateralusX @lambdageek 

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=495334
**Error message validated:** `Exit code was 134 but it should have been 42`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 12/11/2023 6:41:24 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[662557](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662557)|dotnet/runtime|[System.Reflection.Metadata.ApplyUpdateTest.TestAddStaticLambda](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662557&view=ms.vss-test-web.build-test-results-tab&runId=16427048&resultId=195330)|dotnet/runtime#101580|
|[659776](https://dev.azure.com/dnceng-public/public/_build/results?buildId=659776)|dotnet/runtime|[Microsoft.Gen.OptionsValidation.Unit.Test.EmitterTests.InaccessibleValidationAttributesTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=659776&view=ms.vss-test-web.build-test-results-tab&runId=16347166&resultId=174331)|dotnet/runtime#101691|
|[657767](https://dev.azure.com/dnceng-public/public/_build/results?buildId=657767)|dotnet/runtime|[System.Net.Tests.ServicePointManagerTest.FindServicePoint_ReturnedServicePointMatchesExpectedValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=657767&view=ms.vss-test-web.build-test-results-tab&runId=16292390&resultId=100600)|dotnet/runtime#101137|
|[656607](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656607)|dotnet/runtime|[System.Reflection.Metadata.ApplyUpdateTest.TestStaticLambdaRegression](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656607&view=ms.vss-test-web.build-test-results-tab&runId=16258388&resultId=186981)|dotnet/runtime#101580|
|[655791](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655791)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.CooperativeBlockingWithProcessingThreadsAndGoalThreadsAndAddWorkerRaceTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655791&view=ms.vss-test-web.build-test-results-tab&runId=16237660&resultId=187779)|dotnet/runtime#101537|
|[651352](https://dev.azure.com/dnceng-public/public/_build/results?buildId=651352)|dotnet/runtime|[System.Reflection.Metadata.ApplyUpdateTest.TestReflectionAddNewMethod](https://dev.azure.com/dnceng-public/public/_build/results?buildId=651352&view=ms.vss-test-web.build-test-results-tab&runId=16104382&resultId=147773)|dotnet/runtime#101353|
|[650676](https://dev.azure.com/dnceng-public/public/_build/results?buildId=650676)|dotnet/runtime|[System.Security.Cryptography.Tests.Sha256ManagedTests.HashAlgorithm_TransformFinalBlock_ConcurrentUseDoesNotCrashProcess](https://dev.azure.com/dnceng-public/public/_build/results?buildId=650676&view=ms.vss-test-web.build-test-results-tab&runId=16086754&resultId=191922)|dotnet/runtime#99339|
|[650178](https://dev.azure.com/dnceng-public/public/_build/results?buildId=650178)|dotnet/runtime|[Microsoft.Extensions.Diagnostics.Tests.ListenerSubscriptionTests.RuleMatchesNegativeTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=650178&view=ms.vss-test-web.build-test-results-tab&runId=16073130&resultId=100035)|dotnet/runtime#101318|
|[648973](https://dev.azure.com/dnceng-public/public/_build/results?buildId=648973)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=648973&view=ms.vss-test-web.build-test-results-tab&runId=16041070&resultId=163236)|dotnet/runtime#100962|
|[648857](https://dev.azure.com/dnceng-public/public/_build/results?buildId=648857)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=648857&view=ms.vss-test-web.build-test-results-tab&runId=16037986&resultId=167907)|dotnet/runtime#100962|
|[648059](https://dev.azure.com/dnceng-public/public/_build/results?buildId=648059)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=648059&view=ms.vss-test-web.build-test-results-tab&runId=16014154&resultId=163236)|dotnet/runtime#100962|
|[641780](https://dev.azure.com/dnceng-public/public/_build/results?buildId=641780)|dotnet/runtime|[System.Threading.Tests.EtwTests.WaitHandleWaitEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=641780&view=ms.vss-test-web.build-test-results-tab&runId=15827364&resultId=167476)|dotnet/runtime#100386|
|[640958](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640958)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640958&view=ms.vss-test-web.build-test-results-tab&runId=15803136&resultId=146293)|dotnet/runtime#100765|
|[640844](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640844)|dotnet/runtime|[System.Threading.Tests.EtwTests.WaitHandleWaitEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640844&view=ms.vss-test-web.build-test-results-tab&runId=15798916&resultId=138288)|dotnet/runtime#100951|
|[640688](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640688)|dotnet/runtime|[System.Threading.Tests.EtwTests.WaitHandleWaitEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640688&view=ms.vss-test-web.build-test-results-tab&runId=15794182&resultId=152606)|dotnet/runtime#93014|
|[640353](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640353)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640353&view=ms.vss-test-web.build-test-results-tab&runId=15783968&resultId=172459)|dotnet/runtime#100743|
|[639593](https://dev.azure.com/dnceng-public/public/_build/results?buildId=639593)|dotnet/runtime|[System.Threading.Tests.EtwTests.WaitHandleWaitEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=639593&view=ms.vss-test-web.build-test-results-tab&runId=15762840&resultId=152038)|dotnet/runtime#100669|
|[639437](https://dev.azure.com/dnceng-public/public/_build/results?buildId=639437)|dotnet/runtime|[System.Threading.Tests.EtwTests.WaitHandleWaitEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=639437&view=ms.vss-test-web.build-test-results-tab&runId=15759404&resultId=142493)|dotnet/runtime#100520|
|[638524](https://dev.azure.com/dnceng-public/public/_build/results?buildId=638524)|dotnet/runtime|[System.Threading.Tests.EtwTests.WaitHandleWaitEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=638524&view=ms.vss-test-web.build-test-results-tab&runId=15731988&resultId=156598)|dotnet/runtime#100767|
|[637807](https://dev.azure.com/dnceng-public/public/_build/results?buildId=637807)|dotnet/runtime|[System.Threading.Tests.EtwTests.WaitHandleWaitEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=637807&view=ms.vss-test-web.build-test-results-tab&runId=15710790&resultId=147670)|dotnet/runtime#100489|
|[637534](https://dev.azure.com/dnceng-public/public/_build/results?buildId=637534)|dotnet/runtime|[System.Runtime.InteropServices.Tests.PendingExceptionTests.ValidateSetMessageSendPendingException](https://dev.azure.com/dnceng-public/public/_build/results?buildId=637534&view=ms.vss-test-web.build-test-results-tab&runId=15704142&resultId=159168)|dotnet/runtime#100823|
|[636703](https://dev.azure.com/dnceng-public/public/_build/results?buildId=636703)|dotnet/runtime|[System.Tests.PosixSignalRegistrationTests.SignalHandlerCalledForRawSignals](https://dev.azure.com/dnceng-public/public/_build/results?buildId=636703&view=ms.vss-test-web.build-test-results-tab&runId=15680698&resultId=156033)|dotnet/runtime#100147|
|[636603](https://dev.azure.com/dnceng-public/public/_build/results?buildId=636603)|dotnet/runtime|[System.Threading.Tests.EtwTests.WaitHandleWaitEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=636603&view=ms.vss-test-web.build-test-results-tab&runId=15675838&resultId=145076)|dotnet/runtime#100802|
|[636443](https://dev.azure.com/dnceng-public/public/_build/results?buildId=636443)|dotnet/runtime|[System.Threading.Tests.EtwTests.WaitHandleWaitEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=636443&view=ms.vss-test-web.build-test-results-tab&runId=15670652&resultId=145095)|dotnet/runtime#100821|
|[635653](https://dev.azure.com/dnceng-public/public/_build/results?buildId=635653)|dotnet/runtime|[System.ComponentModel.Composition.CompositionExceptionTests.Message_ShouldFormatCountOfRootCausesUsingTheCurrentCulture](https://dev.azure.com/dnceng-public/public/_build/results?buildId=635653&view=ms.vss-test-web.build-test-results-tab&runId=15645184&resultId=105617)|dotnet/runtime#99278|
|[635054](https://dev.azure.com/dnceng-public/public/_build/results?buildId=635054)|dotnet/runtime|[System.Threading.Tests.EtwTests.WaitHandleWaitEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=635054&view=ms.vss-test-web.build-test-results-tab&runId=15622818&resultId=142650)|dotnet/runtime#100778|
|[634307](https://dev.azure.com/dnceng-public/public/_build/results?buildId=634307)|dotnet/runtime|[System.ComponentModel.Composition.CompositionExceptionTests.Message_ShouldFormatCountOfRootCausesUsingTheCurrentCulture](https://dev.azure.com/dnceng-public/public/_build/results?buildId=634307&view=ms.vss-test-web.build-test-results-tab&runId=15599176&resultId=108376)|dotnet/runtime#99278|
|[633731](https://dev.azure.com/dnceng-public/public/_build/results?buildId=633731)|dotnet/runtime|[System.ComponentModel.Composition.CompositionExceptionTests.Message_ShouldFormatCountOfRootCausesUsingTheCurrentCulture](https://dev.azure.com/dnceng-public/public/_build/results?buildId=633731&view=ms.vss-test-web.build-test-results-tab&runId=15579922&resultId=115275)|dotnet/runtime#99278|
|[631865](https://dev.azure.com/dnceng-public/public/_build/results?buildId=631865)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=631865&view=ms.vss-test-web.build-test-results-tab&runId=15527556&resultId=153137)|dotnet/runtime#100676|
|[631246](https://dev.azure.com/dnceng-public/public/_build/results?buildId=631246)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=631246&view=ms.vss-test-web.build-test-results-tab&runId=15510212&resultId=157780)|dotnet/runtime#99659|
|[631044](https://dev.azure.com/dnceng-public/public/_build/results?buildId=631044)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=631044&view=ms.vss-test-web.build-test-results-tab&runId=15503964&resultId=155259)|dotnet/runtime#100497|
|[630711](https://dev.azure.com/dnceng-public/public/_build/results?buildId=630711)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=630711&view=ms.vss-test-web.build-test-results-tab&runId=15493944&resultId=155753)|dotnet/runtime#100650|
|[629121](https://dev.azure.com/dnceng-public/public/_build/results?buildId=629121)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=629121&view=ms.vss-test-web.build-test-results-tab&runId=15443642&resultId=164734)|dotnet/runtime#100489|
|[629043](https://dev.azure.com/dnceng-public/public/_build/results?buildId=629043)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=629043&view=ms.vss-test-web.build-test-results-tab&runId=15441886&resultId=155014)|dotnet/runtime#100589|
|[628975](https://dev.azure.com/dnceng-public/public/_build/results?buildId=628975)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=628975&view=ms.vss-test-web.build-test-results-tab&runId=15440042&resultId=157780)|dotnet/runtime#100141|
|[628555](https://dev.azure.com/dnceng-public/public/_build/results?buildId=628555)|dotnet/runtime|[System.ComponentModel.Composition.CompositionExceptionTests.Message_ShouldFormatCountOfRootCausesUsingTheCurrentCulture](https://dev.azure.com/dnceng-public/public/_build/results?buildId=628555&view=ms.vss-test-web.build-test-results-tab&runId=15429072&resultId=106407)|dotnet/runtime#99278|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|4|36|

**Comment by lateralusX** [comment]
Yes, seems to include the same pattern as seen in https://github.com/dotnet/runtime/issues/85960, so terminating runtime with an exit and since that doesn't wait for managed threads to complete, we still have managed threads calling into EventPipe while cleaning up EventPipe artifacts and that leads to the assert.

**Comment by buyaa-n** [comment]
Failing again on https://github.com/dotnet/runtime/pull/98234
From [log:](https://helix.dot.net/api/2019-06-17/jobs/0f59c27d-f6d6-4a32-b207-2354d42c8b6b/workitems/System.Threading.ThreadPool.Tests/console)
```log
Exiting early due to double fault.
[Inferior 1 (process 41724) detached]
    System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Exit code was 255 but it should have been 42
      Stack Trace:
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(242,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing)
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(55,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose()
        /_/src/libraries/System.Threading.ThreadPool/tests/ThreadPoolTests.cs(1118,0): at System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest()
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.Mono.cs(22,0): at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(57,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
    System.Threading.ThreadPools.Tests.ThreadPoolTests.MetricsTest [SKIP]
      Condition(s) not met: "IsMetricsTestSupported"
  Finished:    System.Threading.ThreadPool.Tests
=== TEST EXECUTION SUMMARY ===
   System.Threading.ThreadPool.Tests  Total: 66, Errors: 0, Failed: 1, Skipped: 1, Time: 12.072s
```

**Comment by mangod9** [comment]
Closing since this hasn't reproed for a few months.
