### ISSUE TITLE
 net9.0-ios-Release-arm64-NativeAOT_Release-OSX.13.Amd64.Iphone.Open leg failing without running tests

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#95875]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=495665
Build error leg or test failing: iOS.Device.Aot.Test.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/95133

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Work item iOS.Device.Aot.Test",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

https://[helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-95133-merge-1c6045ed42fb416782/iOS.Device.Aot.Test/1/console.646ae97e.log?helixlogtype=result](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-95133-merge-1c6045ed42fb416782/iOS.Device.Aot.Test/1/console.646ae97e.log?helixlogtype=result)
e.g.
```
Welcome to .NET 8.0!
---------------------
SDK Version: 8.0.100

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate, run 'dotnet dev-certs https --trust'
Learn about HTTPS: https://aka.ms/dotnet-https

----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
MSBuild version 17.8.3+195e7f5a3 for .NET
/private/tmp/helix/working/A93B0950/p/dotnet-cli/sdk/8.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1314,3): warning MSB4011: "/tmp/helix/working/A93B0950/p/build/microsoft.net.illink.tasks/net8.0/build/Microsoft.NET.ILLink.targets" cannot be imported again. It was already imported at "/tmp/helix/working/A93B0950/p/build/apple/AppleBuild.targets (22,3)". This is most likely a build authoring error. This subsequent import will be ignored. [/private/tmp/helix/working/A93B0950/w/A15008CD/e/publish/ProxyProjectForAOTOnHelix.proj]
  ** Building a proxy for the original test project, to AOT on helix. In order to do that, this recreates the original inputs for the *iOS/tvOS* part of the build. See /private/tmp/helix/working/A93B0950/w/A15008CD/e/publish/ProxyProjectForAOTOnHelix.proj, and . **
  Generating native code
  Running: cmake -S. -BiOS.Device.Aot.Test -GXcode -DTARGETS_APPLE_MOBILE=1 -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0
  Using working directory: /tmp/helix/working/A93B0950/w/A15008CD/e/apple_build/AppBundle/
  Exit code: 0
  Running: xcodebuild ONLY_ACTIVE_ARCH=YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO -arch arm64 -sdk iphoneos -configuration Release
  Using working directory: /tmp/helix/working/A93B0950/w/A15008CD/e/apple_build/AppBundle/iOS.Device.Aot.Test
  Exit code: 0
  
  APP size: 16.7 Mb.
  
  Xcode: /tmp/helix/working/A93B0950/w/A15008CD/e/apple_build/AppBundle/iOS.Device.Aot.Test/iOS.Device.Aot.Test.xcodeproj
  App: /tmp/helix/working/A93B0950/w/A15008CD/e/apple_build/AppBundle/iOS.Device.Aot.Test/Release-iphoneos/iOS.Device.Aot.Test.app
  App moved to: /private/tmp/helix/working/A93B0950/w/A15008CD/e/iOS.Device.Aot.Test.app/
/private/tmp/helix/working/A93B0950/p/dotnet-cli/sdk/8.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(166,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 9.0.  Either target .NET 8.0 or lower, or use a version of the .NET SDK that supports .NET 9.0. Download the .NET SDK from https://aka.ms/dotnet/download [/private/tmp/helix/working/A93B0950/w/A15008CD/e/publish/ProxyProjectForAOTOnHelix.proj]
Signing bundle /tmp/helix/working/A93B0950/w/A15008CD/e/iOS.Device.Aot.Test.app
    "/Users/helix-runner/Library/Keychains/signing-certs.keychain-db"
     0 valid identities found
No valid signing identities found in the keychain
Removing empty log files:
ls: /tmp/helix/working/A93B0950/w/A15008CD/uploads/xunit-*.xml: No such file or directory
+ exit_code=23
+ '[' -f /tmp/helix/working/A93B0950/w/A15008CD/e/.retry ']'
+ '[' -f /tmp/helix/working/A93B0950/w/A15008CD/e/.reboot ']'
+ exit 23
+ export _commandExitCode=23
+ _commandExitCode=23
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=495665
**Error message validated:** `Work item iOS.Device.Aot.Test`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 12/11/2023 7:54:49 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[496572](https://dev.azure.com/dnceng-public/public/_build/results?buildId=496572)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/496572/logs/981)|dotnet/runtime#95701|
|[496557](https://dev.azure.com/dnceng-public/public/_build/results?buildId=496557)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/496557/logs/774)|dotnet/runtime#95896|
|[496530](https://dev.azure.com/dnceng-public/public/_build/results?buildId=496530)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/496530/logs/911)||
|[496518](https://dev.azure.com/dnceng-public/public/_build/results?buildId=496518)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/496518/logs/989)|dotnet/runtime#95898|
|[496502](https://dev.azure.com/dnceng-public/public/_build/results?buildId=496502)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/496502/logs/2036)|dotnet/runtime#94764|
|[496476](https://dev.azure.com/dnceng-public/public/_build/results?buildId=496476)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/496476/logs/2675)||
|[496464](https://dev.azure.com/dnceng-public/public/_build/results?buildId=496464)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/496464/logs/591)|dotnet/runtime#95854|
|[496384](https://dev.azure.com/dnceng-public/public/_build/results?buildId=496384)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/496384/logs/2151)|dotnet/runtime#95894|
|[496381](https://dev.azure.com/dnceng-public/public/_build/results?buildId=496381)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/496381/logs/2292)|dotnet/runtime#95701|
|[496278](https://dev.azure.com/dnceng-public/public/_build/results?buildId=496278)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/496278/logs/1416)|dotnet/runtime#95753|
|[496239](https://dev.azure.com/dnceng-public/public/_build/results?buildId=496239)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/496239/logs/1171)|dotnet/runtime#95701|
|[496226](https://dev.azure.com/dnceng-public/public/_build/results?buildId=496226)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/496226/logs/1038)|dotnet/runtime#95816|
|[496164](https://dev.azure.com/dnceng-public/public/_build/results?buildId=496164)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/496164/logs/1809)|dotnet/runtime#95880|
|[496128](https://dev.azure.com/dnceng-public/public/_build/results?buildId=496128)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/496128/logs/1103)|dotnet/runtime#95879|
|[496079](https://dev.azure.com/dnceng-public/public/_build/results?buildId=496079)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/496079/logs/1190)|dotnet/runtime#95877|
|[496052](https://dev.azure.com/dnceng-public/public/_build/results?buildId=496052)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/496052/logs/1947)|dotnet/runtime#95701|
|[496055](https://dev.azure.com/dnceng-public/public/_build/results?buildId=496055)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/496055/logs/1107)|dotnet/runtime#95808|
|[495988](https://dev.azure.com/dnceng-public/public/_build/results?buildId=495988)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/495988/logs/948)||
|[495783](https://dev.azure.com/dnceng-public/public/_build/results?buildId=495783)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/495783/logs/2631)|dotnet/runtime#95872|
|[495928](https://dev.azure.com/dnceng-public/public/_build/results?buildId=495928)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/495928/logs/2429)||
|[495880](https://dev.azure.com/dnceng-public/public/_build/results?buildId=495880)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/495880/logs/2360)|dotnet/runtime#95513|
|[495665](https://dev.azure.com/dnceng-public/public/_build/results?buildId=495665)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/495665/logs/2622)|dotnet/runtime#95133|
|[495879](https://dev.azure.com/dnceng-public/public/_build/results?buildId=495879)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/495879/logs/24)|dotnet/runtime#94999|
|[495763](https://dev.azure.com/dnceng-public/public/_build/results?buildId=495763)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/495763/logs/1105)|dotnet/runtime#94811|
|[495697](https://dev.azure.com/dnceng-public/public/_build/results?buildId=495697)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/495697/logs/17)|dotnet/runtime#94999|
|[495706](https://dev.azure.com/dnceng-public/public/_build/results?buildId=495706)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/495706/logs/1912)|dotnet/runtime#95065|
|[495612](https://dev.azure.com/dnceng-public/public/_build/results?buildId=495612)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/495612/logs/1008)|dotnet/runtime#95864|
|[495463](https://dev.azure.com/dnceng-public/public/_build/results?buildId=495463)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/495463/logs/2431)|dotnet/runtime#95701|
|[495352](https://dev.azure.com/dnceng-public/public/_build/results?buildId=495352)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/495352/logs/1977)|dotnet/runtime#95788|
|[495230](https://dev.azure.com/dnceng-public/public/_build/results?buildId=495230)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/495230/logs/1012)|dotnet/runtime#95853|
|[495196](https://dev.azure.com/dnceng-public/public/_build/results?buildId=495196)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/495196/logs/76)|dotnet/runtime#95757|
|[495192](https://dev.azure.com/dnceng-public/public/_build/results?buildId=495192)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/495192/logs/750)||
|[495036](https://dev.azure.com/dnceng-public/public/_build/results?buildId=495036)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/495036/logs/24)|dotnet/runtime#94999|
|[494938](https://dev.azure.com/dnceng-public/public/_build/results?buildId=494938)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/494938/logs/1421)|dotnet/runtime#95753|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|29|34|34|

**Comment by steveisok** [comment]
@akoeplinger as we discussed, likely a cert issue with one or more devices. Please address

**Comment by akoeplinger** [comment]
This is a dnceng issue, filed https://github.com/dotnet/dnceng/issues/1542

**Comment by akoeplinger** [comment]
This was fixed by dnceng.
