### ISSUE TITLE
.Net 7/8 failed to fork process at Linux

### ISSUE THREAD

**Issue by xingwu1** [dotnet/runtime#95890]
### Description

I tried to p/invoke libc fork/vfork function to create process (to set running context with specified uid). However, the fork function doesn't work as expect at .Net 7/.Net 8, though the exactly same code works fine at .Net 6. 

### Reproduction Steps

```
        [DllImport("libc", SetLastError = true)]
        public unsafe static extern int vfork();

        static void Main(string[] args)
        {
            int child_pid = vfork();
            if (child_pid > 0)
            {
                Console.WriteLine("the child's process ID is {0}", child_pid);
            }
            else if (child_pid == 0)
            {
                Console.WriteLine("hello from child");
                Environment.Exit(255);
            }
            else
            {
                Console.WriteLine("fork failed");
            }
            Console.WriteLine("hello from main");
        }


### Expected behavior

Compiled with .net 6:

```
hello from child
the child's process ID is 38
hello from main
```


### Actual behavior

Compiled with .net 7/8

```
Segmentation fault
```


### Regression?

Looks like a regression.

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

**Comment by tmds** [comment]
After `fork`/`vfork` you only have one thread left, every thread that makes .NET runtime work (threadpool, GC, ...) is gone. So using .NET code in the child is _undefined behavior_.
With `vfork` the memory remains shared with the parent, so the child can mess up the parent too.

If you want to do something custom between `(v)fork` and `exec`, you should write it in C (and still be extra careful).

If you think others may want to do the same thing, you can write an API request for extending `ProcessStartInfo` to enable that use-case.

**Comment by xingwu1** [comment]
Thank you for replying.
Does .net core has plan to add rlimit setting to Process? That is major reason we would want to use pinvoke.

**Comment by tmds** [comment]
I'm not aware of an issue for adding that.

May be instead of starting the process directly, you can start a shell which runs `ulimit <limit>; <program>`.
