### ISSUE TITLE
ProgressMessageHandler fires too often and cannot be configured

### ISSUE THREAD

**Issue by janseris** [dotnet/runtime#95897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is not a bug per se.
There is not much documentation on `ProgressMessageHandler` in the official docs and not many articles on the internet mentioning it in more advanced scenarios than subscribing to its events (not a real world example). I wonder if it is used in real world apps then and it might be because of the following:

When using `ProgressMessageHandler` with `HttpClient`, download speed decreases from 30 MB/s to 800 kB/s when using `Debug.WriteLine` in Visual Studio to track the progress. I assume I'm using jumbo packets but I am not sure.

This makes any other form of progress tracking either make implement custom buffer for the events fired from the handler or make a CPU-bottleneck in the application if using the events directly to report progress.

Is there any way to configure the behavior to fire less often or is this for some reason, intended behavior?
In the source code, I can see that `ProgressStream` class is hooked onto the response content stream. 
That is probably the place where this limitation happens.

What I am trying to achieve: when using managed `HttpClient` instances (via `.AddHttpClient()`) and because of this, registering `DelegatingHandler`s (`.AddMessageHandler()`) registered as transient, I need to track large files download and upload progress.

### Expected Behavior

Some kind of buffer size is configurable or some other solution. I don't know where the problem is exactly.

### .NET Version

8.0.100

### Anything else?

Related to https://github.com/dotnet/runtime/issues/95708 and find source code there.

**Comment by wfurt** [comment]
Why did you transfer here @javiercn, this is not runtime type AFAIK. It seems like it belongs to https://github.com/aspnet/AspNetWebStack

**Comment by janseris** [comment]
> Why did you transfer here @javiercn, this is not runtime type AFAIK. It seems like it belongs to https://github.com/aspnet/AspNetWebStack

This is 
#region Assembly System.Net.Http.Formatting, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
// C:\Users\Jan\.nuget\packages\microsoft.aspnet.webapi.client\6.0.0\lib\netstandard2.0\System.Net.Http.Formatting.dll

for clarity

**Comment by ManickaP** [comment]
Seems like this should've been filed in https://github.com/aspnet/AspNetWebStack. Unfortunately, there's no option to transfer between orgs, the issue must be copied. @janseris could you file it there? I'll close this one.
