### ISSUE TITLE
Building core-setup: Microsoft.NETCore.DotNetAppHost.nuspec: no viable conversion from 'X' to 'Y'

### ISSUE THREAD

**Issue by assyadh** [dotnet/runtime#959]
Hi,

When trying to build core-setup on Amazon Linux (RHEL 64), I am running into the following error:

```
Microsoft.NETCore.DotNetAppHost -> /build/core-setup/artifacts/packages/Release/specs/Microsoft.NETCore.DotNetAppHost.nuspec
/build/core-setup/src/corehost/cli/fxr/host_context.cpp:131:29: error: no viable conversion from 'const hostpolicy_contract_t' to 'corehost_load_fn' (aka 'int (*)(const host_interface_t *)')
    , hostpolicy_contract { hostpolicy_contract }
                            ^~~~~~~~~~~~~~~~~~~
/build/core-setup/src/corehost/cli/fxr/host_context.cpp:132:37: error: no viable conversion from 'const corehost_context_contract' to 'size_t' (aka 'unsigned long')
    , hostpolicy_context_contract { hostpolicy_context_contract }
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
gmake[2]: *** [cli/fxr/CMakeFiles/hostfxr.dir/host_context.cpp.o] Error 1
gmake[1]: *** [cli/fxr/CMakeFiles/hostfxr.dir/all] Error 2
gmake: *** [all] Error 2
/build/core-setup/src/corehost/build.proj(41,5): error MSB3073: The command "/build/core-setup/src/corehost/build.sh --configuration Release --arch x64 --apphostver 3.1.0 --hostver 3.1.0 --fxrver 3.1.0 --policyver 3.1.0 --commithash 65f04fb6db7a5e198d05dbebd5c4ad21eb018f89 -portable" exited with code 2.
```

I am having trouble figuring out what is going on here. I don't have trouble building .NET Core 2.1, but the host_context.cpp file was introduced with 3.0. Any ideas?

Thanks for the help.

**Comment by vitek-karas** [comment]
@lpereira or @elinor-fung can you please take a look?

**Comment by lpereira** [comment]
I don't understand what's going on here either.  It doesn't make any sense.

**Comment by elinor-fung** [comment]
It seems like it is going through aggregate initialization instead of copy? Looks like that was a [defect reported](https://en.cppreference.com/w/cpp/language/list_initialization) and changed between C++11 and 14 (I don't know how this is handled by different compilers). If that is actually what you are hitting here, I'm guessing switching the `{...}` list initialization to `(...)` to explicitly make it copy would get the intended behaviour.

**Comment by assyadh** [comment]
> I don't understand what's going on here either. It doesn't make any sense. I suspect a bug in the compiler; can you please share either a full build log, or at least versions used here?

Hi @lpereira, I am running clang 3.6.2 on Amazon Linux 2018.03

**Comment by assyadh** [comment]
Switching to copy fixed the issue.

Thanks for the help.
