### ISSUE TITLE
[API Proposal]: public ctor for CookieException with string parameter

### ISSUE THREAD

**Issue by mateusz-dobrowolny** [dotnet/runtime#95965]
### Background and motivation

CDD - Cookie Driven Development

### API Proposal

```csharp
namespace System.Net
{
    [Serializable]
    [...]
    
    public class CookieException : FormatException, ISerializable
    {
        public CookieException() : base()
        {
        }

        // Please make this public
        public CookieException(string? message) : base(message)
        {
        }
```

Please change access modifier for ctor with string? to public.

### API Usage

```csharp
throw new CookieException("🥮");
throw new CookieException("🍥");
throw new CookieException("🍪");
throw new CookieException("🍩");
throw new CookieException("🍰");
```

### Alternative Designs

Alternatively make it protected, so I still can initialize CookieException with particular cookie.

### Risks

Instance of CookieMonster may appear unexpectedly.

**Comment by antonfirsov** [comment]
Triage: assigned to Future given it's not critical. Once the API is approved, we can mark it `help wanted`, since it's a good candidate for community contribution.

**Comment by terrajobst** [comment]
* We should also add the one that takes inner exceptions, for consistency with other exceptions

```C#
namespace System.Net;

public partial class CookieException
{
    // Existing ctors:
    // public CookieException();
    // public CookieException(SerializationInfo, StreamingContext);
    public CookieException(string? message);
    public CookieException(string? message, Exception? innerException);
 }
```

**Comment by mateusz-dobrowolny** [comment]
@terrajobst Incredible! Attached video - transparency level 1000. 
I am impressed. Really.

**Comment by terrajobst** [comment]
@mateusz-dobrowolny 

Glad you like it! You can find an aggregate of all our notes [here](https://github.com/dotnet/apireviews), in case you're ever curious why a given API ended up like it did. I also link notes from API Catalog, for example [here](https://apisof.net/catalog/c694e60347bb1a66121ae183c30345cc).

**Comment by deeprobin** [comment]
@terrajobst @vcsjones Can I implement the feature? Happy to assign me.
