### ISSUE TITLE
Assertion failed '(jmpGroup->igFlags & IGF_HAS_ALIGN) == 0'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#95975]
SPMI replay pipeline is failing with this assert.

x86 JitStressRegs=2 libraries_tests.run.windows.x86.Release.mch
x86 JitStressRegs=0x80 libraries_tests.run.windows.x86.Release.mch
x86 JitStressRegs=0x1000 libraries_tests.run.windows.x86.Release.mch

https://dev.azure.com/dnceng-public/public/_build/results?buildId=498325&view=results

@kunalspathak Is this what you fixed with https://github.com/dotnet/runtime/pull/95845?

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

**Comment by kunalspathak** [comment]
> @kunalspathak Is this what you fixed with #95845?

Yes and the replay appears [green](https://dev.azure.com/dnceng-public/public/_build/results?buildId=498279&view=results).
