### ISSUE TITLE
Wrong display of ShortDatePattern (en-CA) on Debian 12 (bookworm)

### ISSUE THREAD

**Issue by Thieum** [dotnet/runtime#95974]
### Description

Display of ShortDatePattern date in en-CA on Debian 12 displays the wrong format MM/dd/yyyy instead of yyyy-MM-dd. We discovered this bug when upgrading from .NET7 to .NET8 and changing the base image for our dockers.
In WSL, with Debian 12, where the bug can be reproduced with .NET7 and .NET8, version of libicu-dev is 72.1-3. (ubuntu 22.04 is still on libicu-dev 70.1-2)

Appropriate date formatting in Canada is documented here: https://www.noslangues-ourlanguages.gc.ca/en/favourite-articles/faqs-on-writing-the-date.html

### Reproduction Steps

A reproduction project can be found here: https://github.com/Thieum/ReproDotNet8Culture where we display the date with:

`Console.WriteLine(DateTime.Now.ToString("d", System.Globalization.CultureInfo.CreateSpecificCulture("en-CA")));`

1. Launch the console app in WSL (Debian), display is wrong.
2. Launche the console app in WSL (Ubuntu), display is valid.

### Expected behavior

The date should be displayed as yyyy-MM-dd with the short date pattern in the culture 'en-CA' regardless of the platform used.

### Actual behavior

The date is displayed as MM/dd/yyyy with the short date pattern in the culture 'en-CA' on Debian 12.

### Regression?

It was working on previous version of .NET Core and .NET Framework. The dependency on libicu-dev breaks the uniformity of the behavior historically, and across the different actual platforms.

### Known Workarounds

Do not use the default .net8 docker images, use ubuntu based docker images (jammy) if you are handling dates in en-CA.

### Configuration

- .NET8 (same issue with .NET7 on the same plaftorm)
- Debian 12 (bookworm)
- x64
- specific to Debian 12 (libicu-dev 72.1-3) AFAIK
- N/A

**Comment by Clockwork-Muse** [comment]
> The date should be displayed as yyyy-MM-dd with the short date pattern in the culture 'en-CA' regardless of the platform used.

This is a wrong expectation.
We pull formatting data from ICU on Linux, so by default it's _always_ going to depend on the platform and it's installed packages.
You can always use an [app-local ICU](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#app-local-icu), although this is generally discouraged.

If you believe there to be an incorrect format in the ICU data the appropriate place to log a bug is with them.  However, note that the page you've linked isn't necessarily an authoritative source for all use of dates in Canada (as opposed to government document guidelines), and the group maintaining the ICU data may prefer to reflect "as in daily use by citizens".

Why do you care what the formats are?  In most cases this isn't something you should explicitly control or worry about.

**Comment by Thieum** [comment]
> > The date should be displayed as yyyy-MM-dd with the short date pattern in the culture 'en-CA' regardless of the platform used.
> 
> This is a wrong expectation. We pull formatting data from ICU on Linux, so by default it's _always_ going to depend on the platform and it's installed packages. You can always use an [app-local ICU](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#app-local-icu), although this is generally discouraged.

I'll adjust my expectations accordingly.
> 
> If you believe there to be an incorrect format in the ICU data the appropriate place to log a bug is with them. However, note that the page you've linked isn't necessarily an authoritative source for all use of dates in Canada (as opposed to government document guidelines), and the group maintaining the ICU data may prefer to reflect "as in daily use by citizens".

After digging through the ICU ticket system, it seems a discussion about en-CA short date format occurred last year. @jefgen tried to weigh in against the change based on his personal experience as a fellow Canadian citizen, and the survey used at the time: https://unicode-org.atlassian.net/browse/ICU-22013 .

Sure enough, there is confusion around the date format that should be used as seen in this article references: https://en.wikipedia.org/wiki/Date_and_time_notation_in_Canada .

I guess I'll take my users' grievance to the ICU.

> 
> Why do you care what the formats are? In most cases this isn't something you should explicitly control or worry about.

I wish I wouldn't need to care about it either, but here I am, migrating an app from .NET7 to .NET8, and having a third of my user base potentially having their date displayed and date printed on their documents changed from en_CA to en_US without any valid explanation, and forcing me to handle that special case in my code.

**Comment by Clockwork-Muse** [comment]
> I wish I wouldn't need to care about it either, but here I am, migrating an app from .NET7 to .NET8, and having a third of my user base potentially having their date displayed and date printed on their documents changed from en_CA to en_US without any valid explanation, and forcing me to handle that special case in my code.

This isn't a .NET7 vs .NET8 thing, it's solely OS dependent, so updating your deployment environment for your existing application can cause this change as well.

I would recommend against explicitly coding to account for this case, and instead use either an app-local ICU, or control the version of the native ICU package, as both of these will be more sustainable and require less special casing on your end.  

That said... Depending on what you're doing with these documents, I would still advise against doing that.  Keep in mind that localization data can change at any time, to anything (the US could switch to an ISO format too, for example).  Instead it may be preferable for users to be able to set their own date format for a given field.  This may be relevant for cases like somebody in Canada writing a document to be used in another country, among other things.  There are additional considerations depending on other factors - for example, in desktop systems where the user is able to customize their date format.

**Comment by Clockwork-Muse** [comment]
Also, the issue you linked seems to be saying "no, ISO should be correct, nothing to see here".  I don't know if you meant to link another issue or something, but potentially it is a data bug if they or CLDR don't have other issues about it.

**Comment by Thieum** [comment]
@Clockwork-Muse Thank you for your valuable advice.

**Comment by MichalPetryka** [comment]
I agree that relying on the OS language for the date format on documents is weird, such things should probably be controlled by the user.

**Comment by Clockwork-Muse** [comment]
> I agree that relying on the OS language for the date format on documents is weird, such things should probably be controlled by the user.

To be clear, it's useful to expect the OS to provide a default.  Overridable, but a default.
But writing application culture/format interactions is hard for arbitrary user interaction....

**Comment by tarekgh** [comment]
Closing as the @Clockwork-Muse replies addressed all questions and explained the behavior.
