### ISSUE TITLE
[blazor-wasm] Improve handling OOM error, and surface it better

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#95971]
Example issue: https://github.com/dotnet/aspnetcore/issues/40528

If the initial heap size is too big (set via `$(EmccTotalMemory)`) then the user sees:

```
_framework/blazor.boot.json
blazor.webassembly.js?v=pD9dkEr0gbzoZKvepQmzbYKQYka7z-K9H2I-m5Inpxc:1 Streaming compilation failed. Falling back to ArrayBuffer instantiation.  RangeError: WebAssembly.instantiate(): Out of memory: wasm memory
blazor.webassembly.js?v=pD9dkEr0gbzoZKvepQmzbYKQYka7z-K9H2I-m5Inpxc:1 TypeError: Failed to execute 'arrayBuffer' on 'Response': body stream already read
window.Module.s.printErr @ blazor.webassembly.js?v=pD9dkEr0gbzoZKvepQmzbYKQYka7z-K9H2I-m5Inpxc:1
(anonymous) @ blazor.webassembly.js?v=pD9dkEr0gbzoZKvepQmzbYKQYka7z-K9H2I-m5Inpxc:1
await in (anonymous) (async)
window.Module.s.instantiateWasm @ blazor.webassembly.js?v=pD9dkEr0gbzoZKvepQmzbYKQYka7z-K9H2I-m5Inpxc:1
createWasm @ dotnet.6.0.2-mauipre.1.22102.15.0nf0a6txvs.js?v=sha256-/5MtncfJpmo16luI9orAGCmbYEhUFE8G+iO2w9+y4x8=:1
(anonymous) @ dotnet.6.0.2-mauipre.1.22102.15.0nf0a6txvs.js?v=sha256-/5MtncfJpmo16luI9orAGCmbYEhUFE8G+iO2w9+y4x8=:1
blazor.webassembly.js?v=pD9dkEr0gbzoZKvepQmzbYKQYka7z-K9H2I-m5Inpxc:1 Uncaught (in promise) TypeError: Failed to execute 'arrayBuffer' on 'Response': body stream already read
    at blazor.webassembly.js?v=pD9dkEr0gbzoZKvepQmzbYKQYka7z-K9H2I-m5Inpxc:1:36928
    at async blazor.webassembly.js?v=pD9dkEr0gbzoZKvepQmzbYKQYka7z-K9H2I-m5Inpxc:1:36900
    at async blazor.webassembly.js?v=pD9dkEr0gbzoZKvepQmzbYKQYka7z-K9H2I-m5Inpxc:1:36636
```

We should instead catch the OOM error, and maybe surface it as better error that the app can catch, and surface to the user. And log a useful error message on how to fix it, for the the app developer.
And with https://github.com/dotnet/aspnetcore/issues/40547 , it won't make an unnecessary second attempt.

@kg @lewing @pranavkm

**Comment by pavelsavara** [comment]
`RangeError: WebAssembly.instantiate(): Out of memory: wasm memory` should be easy to catch [here](https://github.com/dotnet/runtime/blob/7fae7f80e2c6f26cdadd6d404c551e4ced281561/src/mono/browser/runtime/startup.ts#L506)

We could translate that error to something which would be easier to understand for the developer.

We don't fallback in instantiation anymore. We do it in the [compilation](https://github.com/dotnet/runtime/blob/7fae7f80e2c6f26cdadd6d404c551e4ced281561/src/mono/browser/runtime/loader/assets.ts#L810-L825)
But that should not fail on OOM.

**Comment by mkhamoyan** [comment]
Error message was added by https://github.com/dotnet/runtime/pull/104963
