### ISSUE TITLE
Combine common paths for codegen of SSE, SSE2, SSE3, SSE4.1, SSE4.2 hardware intrinsics

### ISSUE THREAD

**Issue by 4creators** [dotnet/runtime#9597]
There a several common operations which are repeated in several SSE ISAs. To reduce repetitive code refactor SSE, SSE2, SSE3, SSE4.1, SSE4.2 hardware intrinsics Jit processing into common, abstracted operations.

category:implementation
theme:intrinsics
skill-level:intermediate
cost:medium

**Comment by CarolEidt** [comment]
I believe that this has been addressed with the move to table-based code generation. @4creators - feel free to reopen with any remaining code duplication you see.
