### ISSUE TITLE
[wasm] HybridGlobalization: V8 crash on `System.Runtime.Serialization.Schema.Tests`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#95981]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=498273
Build error leg or test failing: normal-System.Runtime.Serialization.Schema.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/95959

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "correlation/v8.*sh.* Killed",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

```
[16:50:04] info: Discovered:  System.Runtime.Serialization.Schema.Tests.dll (found 22 of 22 test cases)
[16:50:04] info: Using random seed for test cases: 839143001
[16:50:04] info: Using random seed for collections: 839143001
[16:50:04] info: Starting:    System.Runtime.Serialization.Schema.Tests.dll
[16:50:08] info: Microsoft.CSharp.CSharpCodeProvider
[16:51:38] info: Process v8-12.0.267.sh exited with 137
                 
[16:51:38] info: /root/helix/work/correlation/v8-12.0.267/v8-12.0.267.sh: line 3:    95 Killed                  "$__SCRIPT_DIR/d8" --snapshot_blob="$__SCRIPT_DIR/snapshot_blob.bin" "$@"
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=498273
**Error message validated:** `correlation/v8.*sh.* Killed`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 12/13/2023 10:20:53 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by radical** [comment]
Same failure for [System.Runtime.Tests](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-95959-merge-82a509c8475241788a/normal-System.Runtime.Tests/1/console.fbd1975f.log?helixlogtype=result) also.

**Comment by radical** [comment]
cc @ilonatommy

**Comment by ilonatommy** [comment]
Recorded cases: (Linux, never on Windows):
- normal-System.Runtime.Serialization.Schema.Tests
- normal-System.Runtime.Tests
- WasmTestOnBrowser-System.Runtime.Serialization.Schema.Tests
- WasmTestOnBrowser-System.Runtime.Tests

v8 in crash logs: `v8-12.0.267`
ChromeDriver `120.0.6099.0`

Trying to repro locally

**Comment by vargaz** [comment]
Is this a crash in v8 ?

**Comment by radical** [comment]
12.0.267 is the latest stable version.

**Comment by pavelsavara** [comment]
no hits recently, closing
