### ISSUE TITLE
[API Proposal]: Operator overload of `/` for combining DirectoryInfo and FileInfo instead of Path.Combine

### ISSUE THREAD

**Issue by mungojam** [dotnet/runtime#95982]
### Background and motivation

pathlib in python has a very nice feature where you can combine paths in an OS safe way with:

```
dir / subPath / "someOtherDir" / "file.txt"
```

When using C# (which I love), I often find I am doing a similar operation and it feels clunky and harder to read to do Path.Combine, and other devs often don't do it so end up with OS compat issues later on.

### API Proposal

It would need multiple overloads, but here is one example

```csharp
    public static FileSystemInfo operator /(MyDirectoryInfo dirInfo, string fileOrDirectoryName)
    {
        var combinedPath = Path.Combine(dirInfo.DirectoryInfo.FullName, fileOrDirectoryName);
        return new FileSystemInfo (combinedPath);
    }
```

### API Usage

```csharp
var targetFile = new DirectoryInfo(Environment.GetEnvironmentVariable("USERPROFILE")) / "my-app" / "log.txt"
```

### Alternative Designs

Maybe Extensions anywhere or Roles will let us do this with a nuget package in a future .net version

### Risks

I can't think of any, but I'm no expert

**Comment by Jozkee** [comment]
This looks great from the usability standpoint. Some concerns:
* Seems like a pit of failure performance-wise because you would need to allocate n-1 operands.
* How do you know when to return `FileInfo` or `DirectoryInfo` when you mix them?

**Comment by vcsjones** [comment]
This has been previously proposed at https://github.com/dotnet/runtime/issues/1928.

**Comment by mungojam** [comment]
> This looks great from the usability standpoint. Some concerns:
> 
> * Seems like a pit of failure performance-wise because you would need to allocate n-1 where n is the number of operands.

I'll leave that to the experts 🙂, but it wouldn't be an issue for our uses

> * How do you know when to return `FileInfo` or `DirectoryInfo`? e.g: `someDirectoryInfo / someFileInfo`. You could pick the type of the right-hand operand, but I don't see it being so easy for the `string` overload.

For string it would have to return FileSystemInfo as the only viable option

**Comment by mungojam** [comment]
> This has been previously proposed at #1928. While that proposal was for strings, the concept is similar enough.

True, I hadn't found that and it appears to be locked. The reasons against it were very valid for strings, I think there is more of an argument for FileInfo etc.

**Comment by Jozkee** [comment]
> For string it would have to return FileSystemInfo as the only viable option

We cannot return a FileSystemInfo because its abstract, unless we make an internal FileSystemInfo implementation just for being returned by the operator; not ideal.

**Comment by mungojam** [comment]
> > For string it would have to return FileSystemInfo as the only viable option
> 
> We cannot return a FileSystemInfo because its abstract, unless we make an internal FileSystemInfo implementation just for being returned by the operator; not ideal.

I see, it could only really work with some new fangled target typing then (feels a bit like collection expressions), I don't think that's currently possible.

Stumped 😞

**Comment by Jozkee** [comment]
I don't think we will act on this proposal given the implications. Closing.

**Comment by tannergooding** [comment]
Noting that this wouldn't pass API review either

As per the framework design guidelines: https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/operator-overloads
> ❌ DO NOT be cute when defining operator overloads.

> 
> Operator overloading is useful in cases in which it is immediately obvious what the result of the operation will be. For example, it makes sense to be able to subtract one [DateTime](https://learn.microsoft.com/en-us/dotnet/api/system.datetime) from another DateTime and get a [TimeSpan](https://learn.microsoft.com/en-us/dotnet/api/system.timespan). However, it is not appropriate to use the logical union operator to union two database queries, or to use the shift operator to write to a stream.

Using the IL `op_Division` operator to do path combination has always been considered to be in this same category, it is explicitly something that is undesirable compared to simply using a verbatim string such as `@"C:\Users\tagoo"` or `"/home/tagoo"`, or even interpolation such as `$@"C:\Users\{username}`, etc...

There are likewise explicit APIs such as `Path.Combine()` which allow this to be done piecemeal and in a very readable way.

**Comment by mungojam** [comment]
> compared to simply using a verbatim string such as `@"C:\Users\tagoo"` or `"/home/tagoo"`, or even interpolation such as `$@"C:\Users\{username}`, etc...

Please note that these aren't good ways to define these paths. User profile directories can differ in different environments and those aren't cross os compatible

**Comment by tannergooding** [comment]
> Please note that these aren't good ways to define these paths. User profile directories can differ in different environments and those aren't cross os compatible

The mechanism used in the top post via `Environment.GetEnvironmentVariable("USERPROFILE")` isn't a "good way" either. The "correct" way is to use `Environment.GetFolderPath` alongside the appropriate `Environment.SpecialFolder` value, such as `Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)`

The intent was to give a trivial example of how to specify a path without requiring being "cute" with operator overloads. Many examples are not representative of how to write real world code and may contain bad practices or may not fully function as expected.
