### ISSUE TITLE
Assertion failed 'optLoopTable != nullptr' during 'Hoist loop code' with jit dumps enabled

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#95987]
Think the latest round of revisions has lead to this.

What is the replacement for `optPrintLoopTable`?

**Comment by AndyAyersMS** [comment]
FYI @dotnet/jit-contrib

**Comment by jakobbotsch** [comment]
Sorry about that. I can submit a fix.

> What is the replacement for `optPrintLoopTable`?

There's no replacement (yet), we just log the new loops whenever we find them.

**Comment by BruceForstall** [comment]
Looks like the fix is:
```
diff --git a/src/coreclr/jit/compiler.cpp b/src/coreclr/jit/compiler.cpp
index db533fcf382..34e14152eba 100644
--- a/src/coreclr/jit/compiler.cpp
+++ b/src/coreclr/jit/compiler.cpp
@@ -4841,6 +4841,7 @@ void Compiler::compCompile(void** methodCodePtr, uint32_t* methodCodeSize, JitFl
         // The loop table is no longer valid.
         optLoopTableValid = false;
         optLoopTable      = nullptr;
+        optLoopCount      = 0;
     }

 #ifdef DEBUG
@@ -5912,6 +5913,7 @@ void Compiler::RecomputeLoopInfo()
     // anymore.
     optLoopTableValid = false;
     optLoopTable      = nullptr;
+    optLoopCount      = 0;
     fgDomsComputed    = false;
 }
```

**Comment by jakobbotsch** [comment]
That looks good to me. Do you mind submitting it @BruceForstall? I will add some proper dumping of the new loops when I'm back.

**Comment by BruceForstall** [comment]
> What is the replacement for optPrintLoopTable?

Can we add the equivalent of `fgDumpFlowGraphLoops` but for dumping into the JitDump?

And also add debugging dLoop/dLoopPtr/dLoops?
