### ISSUE TITLE
ilc.exe is not passed arguments

### ISSUE THREAD

**Issue by katanakatana123** [dotnet/runtime#95997]
I built native aot with the following arument to build : dotnet publish -p:PublishAot=true;OptimizationPreference=Size , it should have been passed to ilc with the --Os argument, I used process explorer to see the command line but there was only "C:\Users\ PC\.nuget\packages\runtime.win-x64.microsoft.dotnet.ilcompiler\9.0.0-alpha.1.23611.1\tools\ilc" @"obj\Release\net9.0\win-x64\native\ sele.ilc.rsp" and with the linker it has a command line of "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\link.exe" @"obj\Release\net9.0\win-x64\native\link.rsp",

**Comment by jkotas** [comment]
It works fine for me with `<TargetFramework>net8.0</TargetFramework>` in .csproj file. Do you have `<TargetFramework>net8.0</TargetFramework>` in your .csproj file?

If you have older target framework in your .csproj file, you have to also explicitly pass `-c Release` to make sure that your project is compiled with optimizations on. `-c Release` is set by default for `dotnet publish` starting with .NET 8.

**Comment by NCLnclNCL** [comment]
> It works fine for me with `<TargetFramework>net8.0</TargetFramework>` in .csproj file. Do you have `<TargetFramework>net8.0</TargetFramework>` in your .csproj file?
> 
> If you have older target framework in your .csproj file, you have to also explicitly pass `-c Release` to make sure that your project is compiled with optimizations on. `-c Release` is set by default for `dotnet publish` starting with .NET 8.

yes, i use dotnet 8 and 9, Have you checked the command line being passed to ilc??

**Comment by katanakatana123** [comment]
> It works fine for me with `<TargetFramework>net8.0</TargetFramework>` in .csproj file. Do you have `<TargetFramework>net8.0</TargetFramework>` in your .csproj file?
> 
> If you have older target framework in your .csproj file, you have to also explicitly pass `-c Release` to make sure that your project is compiled with optimizations on. `-c Release` is set by default for `dotnet publish` starting with .NET 8.

i think it passed  with file .rsp

**Comment by jkotas** [comment]
> i think it passed with file .rsp

Yes, the full command line is in the .rsp file. If you want to see all command line arguments, you have to open the .rsp file in an editor. You should find the `--Os` switch in the .rsp file.

**Comment by HighPerfDotNet** [comment]
You can pass args more explicitly from the project file: 

<ItemGroup>
    <IlcArg Include="--Ot" />
    <IlcArg Include="--instruction-set=x86-x64-v3" />
</ItemGroup>
