### ISSUE TITLE
Remove repo zip + unzip steps from CI bulds

### ISSUE THREAD

**Issue by mmitche** [dotnet/runtime#96]
https://dev.azure.com/dnceng/public/_build/results?buildId=430659&view=logs&j=9269f66d-1f85-5c3b-5cd1-c24f22859cb8

I believe this was added to workaround the throttling that was happening when building coreclr. Since this got fixed via a network reconfiguration on the GitHub side, this can probably be removed.

**Comment by hoyosjs** [comment]
We no longer do this.
