### ISSUE TITLE
HttpClientBuilderExtensions.SetHandlerLifetime()  and HttpClient.Timeout

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#96029]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/HttpClientBuilderExtensionsSetHandlerLi/10540698)._

---
When we modify HttpClient.Timeout value, for example, set it to 3 minutes, do we need to also increase HttpMessageHandler lifespan by using HttpClientBuilderExtensions.SetHandlerLifetime() method, so that HttpMessageHandler does not times out before HttpClient?

---
#### Feedback Bot on 12/13/2023, 11:23 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by karelz** [comment]
Yes, you can have lower `HttpClient.Timeout` (which is timeout of request) than `SetHandlerLifetime` which when handler will be scheduled for removal.
When handler is scheduled for removal it is kept around until all requests finish or timeout.

Write a small repro and you can confirm for yourself.
