### ISSUE TITLE
dotnet.timezones.blat & dotnet.timezones.blat.gz do not have the same contents on Publish (stale file in publish folder)

### ISSUE THREAD

**Issue by mikelyncheski** [dotnet/runtime#96033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The symptom is receiving the following message when trying to load the published website on our test server:

`Failed to find a valid digest in the 'integrity' attribute for resource 'http://SERVER_NAME:5555/_framework/dotnet.timezones.blat' with computed SHA-256 integrity '44J/Hf/X8VbgiBAazDB8c0FaVrAFYOb4BbGyQwuzNyk='. The resource has been blocked.`

Based on feedback on a previous issue ([#27752](https://github.com/dotnet/aspnetcore/issues/27752)), I deleted the dotnet.timezones.blat.gz and the site started functioning again.

The dotnet.timezones.blat.gz file looks like this:

talb4  [["zone.tab",17593],["Australia/Eucla",314],["Australia/ACT",904],["Australia/Lindeman",325],["Australia/Brisbane",289],["Australia/Queensland",289],["Australia/Broken_Hill ....

The dotnet.timezones.blat looks like this:

talb4  [["zone.tab",17593],["Atlantic/Azores",1453],["Atlantic/Jan_Mayen",676],["Atlantic/Faroe",441],["Atlantic/Faeroe",441],["Atlantic/South_Geo

My guess is that the checksum is built off the uncompressed file version, but IIS serves up the compressed version of the file if available.  

Other points:
- It is not just my machine.  Another developer on the project is having the same issue with the publish.  
- We are using AspNetCore 6.0.7.
- Build/Clean did not help.
- Whacking the publish folder did not help.

For now, we will delete the dotnet.timezones.blat.gz as part of our publishing.

### Expected Behavior

The website should load properly without checksum error.

### Steps To Reproduce

"$MSBUILD" $SOLUTION/Arup.Server/Xxx.Server.csproj '/property:Configuration='$TARGET '/property:DeployOnBuild=true' '/property:PublishProfile=InstallToZip'

### .NET Version

6.0.7

**Comment by mkArtakMSFT** [comment]
@lewing  FYI

**Comment by steveisok** [comment]
@lewing I'll put this on 9.0 for now. Feel free to move it around.

**Comment by pavelsavara** [comment]
I think this is yet another manifestation of broken incremental publish https://github.com/dotnet/runtime/issues/98690

**Comment by lewing** [comment]
closing as a duplicate of https://github.com/dotnet/runtime/issues/98690
