### ISSUE TITLE
Add missing Async methods to System.Threading.Channels on .NET Standard 2.0

### ISSUE THREAD

**Issue by Metadorius** [dotnet/runtime#96039]
There is a backport package for async interfaces that can be included on .NET Standard 2.0. @almazik said the following in https://github.com/dotnet/runtime/issues/38046#issuecomment-647642261:

> @joperezr By adding a NS2.1 target we will actually expose the same set of APIs as with NCA3.0, so that would be A+B.

> And, on the contrary, if we just add Microsoft.Bcl.AsyncInterfaces to NS2.0, then the NS2.1 project consuming the System.Threading.Channels package will have a collision of NS2.1 IAsyncEnumerable with Microsoft.Bcl's IAsyncEnumerable exposed by System.Threading.Channels package. That would match "A+C" definition in your example

I am not quite sure if this is true because as far as I know we can specifically include the backport package _only_ on .NS2.0, so there's no reason to exclude .NS2.0 which is a very valid target because of .NET Framework compatibility. The consuming .NS2.1 package will just use the .NS2.1 version and not .NS2.0 version.

**Comment by Metadorius** [comment]
This is actually needed for `SurrealDB.NET` to support the .NS2.0 target, see the mention above.

**Comment by davidfowl** [comment]
What is needed exactly?

**Comment by Metadorius** [comment]
> What is needed exactly?

`ReadAllAsync` is only available on .NS2.1. It would be beneficial to add it to .NS2.0. 

It's a continuation of the discussion I referenced that is now in the locked thread, from which I gathered it's not hard to do so if we include `Microsoft.Bcl.AsyncInterfaces`.

**Comment by WeihanLi** [comment]
> ChannelReader.ReadAllAsync (and possibly some other stuff) is only available on .NS2.1. It would be beneficial to add it to .NS2.0.

I had the same issue, think it's safe to add it, currently, I add an extension method with the implementation in our project

**Comment by WeihanLi** [comment]
This should be fixed by https://github.com/dotnet/runtime/pull/94417
