### ISSUE TITLE
Assertion failed '(fgEntryBB->bbRefs == 1) && (fgEntryBB->bbPreds == nullptr)'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#96038]
test: baseservices/exceptions/regressions/V1/SEH/VJ/HandlerException/HandlerException.cmd

Fails in many jitosr_stress_random architecture runs

https://dev.azure.com/dnceng-public/public/_build/results?buildId=494517&view=ms.vss-test-web.build-test-results-tab

@AndyAyersMS @dotnet/jit-contrib

**Comment by jakobbotsch** [comment]
This was fixed by #95871
