### ISSUE TITLE
AOT compilation to publish program the code from the dependency libraries cannot be included in the DLL

### ISSUE THREAD

**Issue by MosPassWords** [dotnet/runtime#96036]
### Description

n .NET 8, when using local AOT compilation to publish a program, if you choose to publish it as an EXE, all the dependency libraries can be properly included, and the program will run correctly. However, if you choose to publish it as a DLL, the code from the dependency libraries cannot be included in the DLL. Do you know the reason behind this?

### Reproduction Steps

NONE

### Expected behavior

NONE

### Actual behavior

NONE

**Comment by am11** [comment]
Could you share a small repro with build steps, expected and actual behaviors? All code _consumed_ from referenced libraries by the project being published should be included in the native shared lib (.dll, .so, .dylib). Note that the dead code might get trimmed; i.e. the code not used by call-chains of any entrypoint.

The entrypoints (or methods which you wish to export from the library) in the code need to be decorated with `[UnmanagedCallersOnly(EntryPoint = "<name here>")]` so it is accessible by external C/C++ code (which can then use `extern ..` statement to import those entrypoints) and the native linker.
