### ISSUE TITLE
Plan for CoreCLR and Mono to run corefx tests in their CI

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#961]
I've opened this issue to have a discussion on what would be the best plan to follow regarding on CoreFX delivering test assets to Mono and CoreCLR.

I know that @mikem8361 has been doing some work to publish tests assets to an azure blob storage with a well known name, and then CoreCLR would restore that. However there has been some discussion on why using blob storage and not NuGet packages.

I know that @ericstj had some points against using NuGet packages, regarding the package size and the layout of the package as it will not be following any NuGet conventions.

cc: @marek-safar @danmosemsft @jkotas @RussKeldorph

**Comment by jkotas** [comment]
This is no longer relevant after repo consolidation.

**Comment by marek-safar** [comment]
Is there any doc/pointer how are CoreCLR tests run during CI in the new repo?
