### ISSUE TITLE
[API Proposal]: aot export api stdcall,UnmanagedCallersOnly for vb6

### ISSUE THREAD

**Issue by xiaoyaocode163** [dotnet/runtime#96103]
### Background and motivation

HOW TO EXPORT API IN VB.NET? LIKE:DotNetRuntimeDebugHeader

c# can export stdcall api  by UnmanagedCallersOnly,but vb.net can't do this,how can you fix?
or i can use 
public function add_export_stdcall(a as long,b as long) as long
return a+b
end function

aot will auto set add_export_stdcall to export as :add

`public static class MyFunctions
{
    [UnmanagedCallersOnly(EntryPoint = "Add")]
    public static int Add(int a, int b)
    {
        return a + b;
    }

    [UnmanagedCallersOnly(EntryPoint = "PrintString")]
    public static void PrintString(IntPtr str)
    {
        Console.WriteLine(Marshal.PtrToStringAnsi(str));
    }

    [UnmanagedCallersOnly(EntryPoint = "GetSystemInfoWrite")]
    public static void GetSystemInfo()
    {
        Console.WriteLine($"ProcessorCount: {Environment.ProcessorCount}");
        Console.WriteLine($"MachineName: {Environment.MachineName}");
    }

}`

### API Proposal

```csharp
namespace System.Collections.Generic;

public class MyFancyCollection<T> : IEnumerable<T>
{
    public void Fancy(T item);
}
```

### API Usage

```csharp
// Fancy the value
var c = new MyFancyCollection<int>();
c.Fancy(42);

// Getting the values out
foreach (var v in c)
    Console.WriteLine(v);
```

**Comment by am11** [comment]
I assume this is because `UnmanagedCallersOnly` is not CLS complaint: https://github.com/dotnet/runtime/issues/40461. VB compiler gives `error BC37316: 'UnmanagedCallersOnly' attribute is not supported` :(

Bad workaround: manually inject attribute in IL using reflection etc.
Better workaround: use C# project to expose your API with `<ProjectReference Include="path\to\your.vbproj" />` in csproj.

**Comment by jkotas** [comment]
It is by design that Visual Basic cannot do everything that C# can do. [.NET language strategy](https://learn.microsoft.com/en-us/dotnet/fundamentals/languages) explains our approach in more detail.

> use C# project to expose your API

Yes, this is the right solution.

**Comment by MichalStrehovsky** [comment]
Cc @dotnet/interop-contrib - UnamangedCallersOnlyAttribute cannot be used with VB due to the non-CLS compliant constructor
