### ISSUE TITLE
Improve documentation for common globalization issues

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/runtime#96101]
Given the ongoing reporting of ICU or general culture-data-related formatting issues reported (eg, https://github.com/dotnet/runtime/issues/96022, https://github.com/dotnet/runtime/issues/95974), should we consider adding a bug category for culture-related data bugs, including things like instructions on checking the actual culture data and simple troubleshooting steps to verify whether it's just their expectations about the culture data, or an actual bug on our end (which does happen occasionally)

**Comment by danmoseley** [comment]
Do you mean add another issue template, with customized text/comments that give that info?

**Comment by Clockwork-Muse** [comment]
Yes, another issue template.

**Comment by danmoseley** [comment]
I expect they'd take a PR to try it

**Comment by MichalPetryka** [comment]
I think that adding a docs page explaining this makes more sense here. Although adding a bug report for `Bugs with localization data` that redirects to the ICU repo makes sense too.

**Comment by danmoseley** [comment]
If we wanted to experiment with new issue templates for common bug categories, another possible one might be memory investigations: it could ask about GC settings, point to info about investigations, etc.

**Comment by Clockwork-Muse** [comment]
Fixed in the docs repo with https://github.com/dotnet/docs/pull/40492
