### ISSUE TITLE
Mixed Assembly Loading in .NET

### ISSUE THREAD

**Issue by ericcdub** [dotnet/runtime#96110]
I'm trying to load a. NET 6 assembly and its reference assemblies into a custom assembly load context, but my code kept throwing exceptions when loading certain reference assemblies which happen to be mixed C++/CLI assemblies.

I temporarily changed my load context to be non collectible but now it's throwing a BadImageFormatException for certain reference assemblies. I don't know much about mixed assemblies other than that they can contain both managed and unmanaged code, and I'm unclear from documentation as to the level of support for mixed assemblies in .NET.

I've also tried just loading the assemblies into the default load context using Assembly.LoadFrom inside a simple .NET test app I created, but that produces a FileNotFoundException, even though the file exists on disk, so the exception is probably misleading.

It didn't seem to be an issue in. NET Framework but this assembly is from a project that was upgraded to. NET, so I'm wondering is what I'm trying to do when possible now in the latter.

Any advice appreciated, cheers

**Comment by vitek-karas** [comment]
@janvorli on unlodability - I don't remember if we can unload C++/CLI assembly

As for the rest, it's hard to help without more information. `BadImageFormatException` is typically thrown if the assembly is of the wrong architecture (like trying to load x86 assembly into an x64 process). `FileNotFoundException` can have multiple reasons, so without seeing the callstack and the details of the exception it's hard to tell what's wrong.

> Any advice appreciated, cheers

It should be possible load C++/CLI assemblies into a custom load context. Other than that, you didn't really describe what you're trying to do, so I can't comment if it's possible or not.

**Comment by janvorli** [comment]
> I don't remember if we can unload C++/CLI assembly

No, we cannot, see https://github.com/dotnet/runtime/blob/main/docs/design/features/unloadability.md#unsupported-scenarios

**Comment by agocke** [comment]
Closing as answered
