### ISSUE TITLE
`HasExited` throws Access Denied for the Idle process on Windows

### ISSUE THREAD

**Issue by simendsjo** [dotnet/runtime#96124]
### Description

`OpenProcess` in ProcessManager.Windows.cs fails when opening the Idle process.

This causes errors in certain situations, e.g. when checking if the process has exited.

https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/ProcessManager.Windows.cs#L250-L253

### Reproduction Steps

`System.Diagnostics.Process.GetProcessById(0).HasExited`

### Expected behavior

Returns false

### Actual behavior

Throws `Win32Exception(Interop.Errors.ERROR_ACCESS_DENIED)`

### Known Workarounds

Avoid calling certain processes on the Idle process. HasExited will probably always be false ;)

### Configuration

Windows

**Comment by Jozkee** [comment]
It looks to me that [the condition](https://github.com/dotnet/runtime/blob/4cf19ee05d3efc5372b8f308240688bacce09208/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/ProcessManager.Windows.cs#L250-L253 ) is an effort to align the system Idle Process with other Windows' core processes like System (pid 4), therefore it may be unwise to remove it.

**Comment by simendsjo** [comment]
> This issue has been marked needs-author-action and may be missing some important information.

Not sure if I can give more information here. It's unfortunate the special pid 0 is used as a special "error" pid rather than e.g. a negative pid, but it's probably not a big problem in practice.

**Comment by Jozkee** [comment]
I haven't checked the consequences of removing the condition but considering that it's been there since .NET Framework (+10 years) I suspect is not a huge issue.

any objections with closing this issue?

**Comment by simendsjo** [comment]
> I haven't checked the consequences of removing the condition but considering that it's been there since .NET Framework (+10 years) I suspect is not a huge issue to have it.

I found it due to a bug in my code causing the pid I checked to not being set and thus 0. If it didn't trigger an error, my bug might be harder to find.

> any objections with closing this issue?

No, go ahead. It's probably more of a theoretical problem than a practical one.
