### ISSUE TITLE
[API Proposal]: Parallel.ForEachAsync with Partitioner support

### ISSUE THREAD

**Issue by Bazalii** [dotnet/runtime#96126]
### Background and motivation

There is an implementation for `Parallel.ForEach` with overload that takes `Partitioner` as an argument. In my opinion, It would be a great option to have an overload for `Parallel.ForEachAsync` that will also use `Partitioner`. As a result, we will be able to process batches of collections effectively without having to process each element separately.

If this feature has some drawbacks and because of them it has not been implemented, I would appreciate an explanation of the drawbacks.

### API Proposal

```csharp
namespace System.Threading.Tasks
{
    public static partial class Parallel
    {
        public static Task ForEachAsync<TSource>(Partitioner<TSource> source, Func<TSource, CancellationToken, ValueTask> body);
    }
}
```

### API Usage

```csharp
const int numberOfElementsInList = 100_000;
var list = Enumerable
    .Range(0, numberOfElementsInList)
    .ToArray();
var result = await MapListParallelAsync(list);

return;

async Task<List<MappedModel>> MapListParallelAsync(int[] inputList)
{
    var result = new ConcurrentBag< MappedModel >();

    var partitioner = Partitioner.Create(0, inputList.Length);

    await Parallel.ForEachAsync(partitioner, async (range, _) =>
    {
        for (var i = range.Item1; i < range.Item2; i++)
        {
            // Some async operations for getting data for mapping process

            result.Add(new MappedModel
            {
                A = <retuned-data-1>,
                B = <retuned-data-2>
            });
        }
    });

    return result.ToList();
}

class MappedModel
{
    public int A { get; set; }
    public float B { get; set; }
}
```

**Comment by stephentoub** [comment]
The partitioner support is more valuable when the cost of getting the next element from the enumerator and the cost of invoking the body delegate are tiny; in such cases, the cost of synchronizing and the overheads of the interface dispatch can add measurable overhead.  That is not the expected case with ForEachAsync.  Can you share a real example where this would be valuable, and some performance numbers that demonstrate the expected win?

**Comment by Bazalii** [comment]
Sorry for inactivity. In my particular case I had to go to another service to get some information for mapping of models asynchronously. When we have several thousands of elements to process using `Parallel.ForEach`, usage of partitioner helps us to have optimal number of partitions for workstation where the application is running and, as a result, to have less contention for synchronizing of our collection to which we add our mapping elements.

For example, if we have collection of 10_000 elements that we have to map on workstation with 8 cores we will get only 24 partitions(when using default `Partitioner.Create`) that will be processed concurrently and which we will have to "merge" to our resulting collection. But when we do not use partitioner, it is needed to synchronize 10_000 operations with only one element of collection. Therefore, the contention for synchronization of main collection will be high.

Actually, which drawbacks do you see for implementation for `ForEachAsync` with partitioner?

**Comment by stephentoub** [comment]
> For example, if we have collection of 10_000 elements that we have to map on workstation with 8 cores we will get only 24 partitions(when using default Partitioner.Create) that will be processed concurrently and which we will have to "merge" to our resulting collection. But when we do not use partitioner, it is needed to synchronize 10_000 operations with only one element of collection. Therefore, the contention for synchronization of main collection will be high.

I'm not following. With 8 cores by default you'll not have more than 8 concurrent operations in a ForEachAsync (you can change that via MaxDegreeOfParallelism). How does a partitioner help with that?

**Comment by Bazalii** [comment]
Yes, if we have 8 cores, we can process maximum 8 concurrent operations. But as we know, the more synchronization is required, the less effective parallel code is. That is what I wanted to say about partitioner. As I understand partitioner reduces need of synchronization because it divides collection into several continuous parts each of which can be processed at once at one core.

Let's say we have 2 cores and such a collection: {1, 2, 3, 4, 5, 6, 7, 8, ... , 58, 59, 60}. If we use a partitioner we will get 6 collections of 10 elements each: `int rangeSize = (int) (((long) toExclusive - (long) fromInclusive) / (long) (Environment.ProcessorCount * 3));` and two cores will compete for getting one of 6 collections and after getting one each of the cores will be able to load and process 10 elements at once in their local cache. If we don't use a partitioner, cores will have to compete for each element in collection with more contention and less parallel effectiveness.

Am I missing something?

**Comment by stephentoub** [comment]
That gets back to my comment:

> The partitioner support is more valuable when the cost of getting the next element from the enumerator and the cost of invoking the body delegate are tiny; in such cases, the cost of synchronizing and the overheads of the interface dispatch can add measurable overhead. That is not the expected case with ForEachAsync. Can you share a real example where this would be valuable, and some performance numbers that demonstrate the expected win?

What is your _asynchronous_ processing doing that it's so cheap as to have the synchronization on the source be a dominating factor?

**Comment by Bazalii** [comment]
So, your point actually is that partitioner optimization will not influence the performance of ForEachAsync and there is no need in implementation of ForEachAsync with partitioner support, isn't it?

**Comment by stephentoub** [comment]
Yes:

> The partitioner support is more valuable when the cost of getting the next element from the enumerator and the cost of invoking the body delegate are tiny; in such cases, the cost of synchronizing and the overheads of the interface dispatch can add measurable overhead. That is not the expected case with ForEachAsync. Can you share a real example where this would be valuable, and some performance numbers that demonstrate the expected win?
