### ISSUE TITLE
Debugging With InteractiveAuto When Changes To Webassembly

### ISSUE THREAD

**Issue by wisamidris7** [dotnet/runtime#96137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I Made In Blazor A Auto Render Mode
The Problem Is Webassembly
When Making Auto Or Webassembly
Or When Auto Complete Download Webassembly

The Debugging Is Not Pointing And I Made It Server Render Mode
Everything Works Prefect But I Want To Debug The Webassembly Authentication Or
Some Of Things What Works In Server Side And Not Working With Webassembly 
These Things Take A Long Time To Get It Without Debug

So Can You Tell Me A Solution For This
Or If It Bug In Blazor To Fix It

And Thanks!

**Comment by radical** [comment]
cc @ilonatommy @thaystg

**Comment by wisamidris7** [comment]
ok i was meaning to do issue in aspnetcore repo cause it for blazor
or not in this repo

**Comment by ilonatommy** [comment]
@wisamidris7 Thank you for the report. It is understandable that it is harder for you to develop the project when debugging does not work as you expected.
- What version of dotnet is your project using (`TargetFramework`)?
- In case it's an older version, this issue about debugging with authentication might be related: https://github.com/dotnet/runtime/issues/87407. Do you see a similar behavior?
- "Some Of Things What Works In Server Side And Not Working With Webassembly", what beyond debugging the authentication code do you mean here? It is easier for us to find and fix the bug when we have specific examples of faulty behavior, or even better - if you could show us a sample application code with the unexpected behavior.

**Comment by wisamidris7** [comment]
> "Some Of Things What Works In Server Side And Not Working With Webassembly", what beyond debugging the authentication code do you mean here? It is easier for us to find and fix the bug when we have specific examples of faulty behavior, or even better - if you could show us a sample application code with the unexpected behavior.

[In This Issue](https://github.com/dotnet/aspnetcore/issues/53007)

**Comment by thaystg** [comment]
Hi, the other issue is closed. Is this issue still reproducible?
