### ISSUE TITLE
[runtime-jit-experimental] Assertion failed 'loops->NumLoops() == 0'

### ISSUE THREAD

**Issue by amanasifkhalid** [dotnet/runtime#96145]
`runtime-jit-experimental` is blocked by the following assert:

```
Assert failure(PID 976 [0x000003d0], Thread: 3776 [0x0ec0]): Assertion failed 'loops->NumLoops() == 0' in 'hello_leaveintotrybody_leaves_il.Class1:Main():int' during 'Place 'align' instructions' (IL size 244; hash 0xc0639335; Tier1-OSR)

    File: D:\a\_work\1\s\src\coreclr\jit\compiler.cpp Line: 5436
    Image: C:\h\w\B03D09B3\p\corerun.exe
```

[Example run](https://dev.azure.com/dnceng-public/public/_build/results?buildId=502570&view=results)

cc @dotnet/jit-contrib

**Comment by jakobbotsch** [comment]
I can take a look. The failure is with OSR enabled for this test that has a `leave` instruction from a handler back into its associated try region:
https://github.com/dotnet/runtime/blob/fb3e9d90910ef2528608a9649a884da6dee5bb47/src/tests/JIT/Methodical/eh/leaves/leaveintotrybody.il#L157
Probably this results in some weird loop structure, but more worryingly, the JIT has a number of places where it models that a try region can only be entered at its first block.
