### ISSUE TITLE
Add RIDs for Alpine 3.19

### ISSUE THREAD

**Issue by lbussell** [dotnet/runtime#96155]
[Alpine 3.19](https://alpinelinux.org/posts/Alpine-3.19.0-released.html) was released on 2023-12-07. 

I believe we need the RID ASAP due to https://github.com/PowerShell/PowerShell/issues/20945 which is blocking PowerShell support in https://github.com/dotnet/dotnet-docker/pull/5065.

Related: https://github.com/dotnet/core/issues/9013

**Comment by am11** [comment]
The future-proof way is to switch to portable RIDs (e.g. `linux-musl-x64`), to avoid getting blocked each time there is a new version of some distro released. See https://github.com/dotnet/docs/issues/36527.

**Comment by tmds** [comment]
> which is blocking PowerShell support in https://github.com/dotnet/dotnet-docker/pull/5065.

In the .NET 6 and .NET 7 images you can force the rid by setting the `DOTNET_RUNTIME_ID` envvar to the portable rid (`linux-musl-x64`/`linux-musl-arm64`).

This is not needed for .NET 8, because .NET 8 will use the portable rid automatically.

**Comment by tmds** [comment]
> by setting the DOTNET_RUNTIME_ID envvar

Depending on how much of the existing graph behavior you want, you can set it to the portable rid (`linux-musl-x64`), the alpine rid (`alpine-x64`), or the latest alpine version that is in the .NET 6/.NET 7 graph (`alpine.3.18-x64`).

**Comment by tmds** [comment]
cc @ViktorHofer @elinor-fung @wfurt

**Comment by agocke** [comment]
As mentioned above, we no longer provide support for OS-version-specific RIDs. `linux-musl-x64`/`-arm64` is the recommended RID going forward.

**Comment by richlander** [comment]
Re-opened this issue. This is breaking .NET 6/7 Alpine container images.

https://github.com/dotnet/dotnet-docker/issues/5243

**Comment by richlander** [comment]
Alpine 3.20 is likely not that far off. We should add support for it at the same time.

https://alpinelinux.org/releases/

**Comment by elinor-fung** [comment]
@ayakael added both 3.19 and 3.20 for .NET 6 in https://github.com/dotnet/runtime/pull/99560. It should be in the 6.0.29 release.
