### ISSUE TITLE
Restore the Microsoft.NETCore.DotNetHostResolver package as a non-shipping package

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#96151]
We have internal dependencies upstack that include hostfxr.dll directly. We need to restore this package to allow these dependencies to continue to use the live hostfxr version.

In the long term, we should instead consider using the nethost APIs to enable these upstack use cases to discover hostfxr without having to ship a copy of their own.

**Comment by marcpopMSFT** [comment]
We'll need this fixed before the first insertion into VS. That won't be until preview 4 but we'll start prepping the insertion with preview 1. Right now installer main is hardcoded to an 8.0 RC1 version of the host resolver package.
https://github.com/dotnet/installer/blob/main/eng/Versions.props#L111

**Comment by ViktorHofer** [comment]
@agocke @elinor-fung

**Comment by elinor-fung** [comment]
Can they not use the live `hostfxr` from the `Microsoft.NETCore.App.Runtime.*` packages?

**Comment by ViktorHofer** [comment]
@marcpopMSFT

**Comment by jkoritzinsky** [comment]
Yep, the same file was packaged in both packages.

**Comment by marcpopMSFT** [comment]
Looks like the build passed. We'll know for sure once we try to insert into VS but I think this can be closed.
