### ISSUE TITLE
Why do HttpHeaders.GetValues() throw when header does not exist?

### ISSUE THREAD

**Issue by thomaseyde** [dotnet/runtime#96176]
https://github.com/dotnet/runtime/blob/c282395b63c1757d4f4c1dc2e236680cfe2e7f96/src/libraries/System.Net.Http/src/System/Net/Http/Headers/HttpHeaders.cs#L201

I expect a method with the signature `IEnumerable<string> GetValues(string name)` to return empty, not throw, when nothing is found for the given `name`.

Calling `GetValues(x).FirstOrDefault()` does not making sense in this context. But you wouldn't know until production.

There was an indexer some time ago where I could:
```
var apiKey = req.Headers["x-api-key"];
var bearerToken = req.Headers["Authorization"];
```

Now I have to do silly things like:
```
  var apiKeys = req.Headers.TryGetValues("x-api-key", out var values)
            ? values
            : Enumerable.Empty<string>();
        
  var apiKey = apiKeys.FirstOrDefault();
        
  var bearerTokens = req.Headers.TryGetValues("Authorization", out values)
            ? values
            : Enumerable.Empty<string>();
        
  var bearerToken = bearerTokens.FirstOrDefault();
```

**Comment by MihaZupan** [comment]
Such behavior is very common for APIs that have a `Try-` counterpart.
`Try` gives you a yes/no, whereas the non-try variant throws.

If you find it easier to use, you can include a helper method in your project along the lines of
```c#
public static IEnumerable<string> GetValuesOrEmpty(this HttpHeaders headers, string name) =>
    headers.TryGetValues(name, out IEnumerable<string> values)
        ? values
        : Enumerable.Empty<string>();
```

**Comment by thomaseyde** [comment]
> Such behavior is very common for APIs that have a `Try-` counterpart.

Still, it's a breaking change from earlier behaviour.

**Comment by MihaZupan** [comment]
I think you have a different collection in mind, System.Net.Http.HttpHeaders never had an indexer AFAIK
