### ISSUE TITLE
SqlServer Operations too slow in Ubuntu

### ISSUE THREAD

**Issue by TejasPatadiya10** [dotnet/runtime#96171]
Currently we have one scenario where certain queries getting executed in windows in in 5 seconds and same queries are taking time of more than 2 minutes in Ubuntu linux.

We are using latest version of Microsoft.Data.SqlClient and we have also check that certain posts regarding the same in this repo and it shows that it is fixed but still we are facing this.

Please guide to avoid this slowness in Ubuntu.

**Comment by Wraith2** [comment]
This probably belongs in the https://github.com/dotnet/SqlClient repository if someone with permissions wants to move it.

We will need a reproduction example of what is slow to investigate this effectively.

**Comment by TejasPatadiya10** [comment]
OK. Reported under https://github.com/dotnet/SqlClient/issues/2280 , hence closing this one
