### ISSUE TITLE
Memory footprint decreases when application is launched as a console, but does not when launched through a Windows service

### ISSUE THREAD

**Issue by stealthin** [dotnet/runtime#96179]
### Description

I've created a .NET 8 Console application with the following settings:
```
<PublishAot>true</PublishAot>
<ServerGarbageCollection>true</ServerGarbageCollection>
<GarbageCollectionAdaptationMode>1</GarbageCollectionAdaptationMode>
```

I expect the [GC DATAS feature](https://maoni0.medium.com/dynamically-adapting-to-application-sizes-2d72fcb6f1ea) to kick in, so that memory consumption decreases to the bare minimum when application is idle.

When the application is launched via console, I indeed notice the memory consumption decreases a lot, from ~800MB to ~100MB when it is idle and no allocation takes place, as shown below.

![DATAS](https://github.com/dotnet/runtime/assets/127829617/f0112b19-5a4f-4697-acb5-38feda4a49a1)

However, when the application is launched through a Windows service, the memory consistantly stays at 800MB and do not decrease.

Is there anything to do in order to get the same behavior whether app is running in console or Windows service?
 
### Configuration

Windows Server 2019 / x64 
8vCPU / 16 GB RAM

**Comment by mangod9** [comment]
Hi @stealthin, is there any specific behavior in your app which might be different when running as a service? Are you able to confirm that the 800mb is all consumed by the GC heap and not native memory?

**Comment by mangod9** [comment]
Ok thanks for the details. If you are able to provide a repro that would be great so we can try to repro the behavior with that code. One other thing to try would be to check if the behavior changes when not publishing as AOT? Thanks
