### ISSUE TITLE
[NativeAOT] No usable version of libssl was found on linux-bionic-arm64

### ISSUE THREAD

**Issue by xljiulang** [dotnet/runtime#96184]
I compiled a webSocket client executable file according to the documentation of [android-bionic.md](https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/android-bionic.md), but when I made a wss connection, I encountered the error 'No usable version of libssl was found'. I want to know which versions of libssl are supported. I tried v1.1.1 and v3.2.0 and got the same error.

```
-rwxrwxrwx 1 shell shell 12647728 2023-12-19 21:41 webSocket-client
-rw-rw-rw- 1 shell shell    66472 2023-10-31 22:47 libSystem.Globalization.Native.so
-rw-rw-rw- 1 shell shell   723560 2023-10-31 22:47 libSystem.IO.Compression.Native.so
-rw-rw-rw- 1 shell shell    93952 2023-10-31 22:47 libSystem.Native.so
-rw-rw-rw- 1 shell shell   175192 2023-10-31 22:47 libSystem.Security.Cryptography.Native.OpenSsl.so
-rw-rw-rw- 1 shell shell  2865208 2023-12-19 21:52 libcrypto.so
lrwxrwxrwx 1 shell shell       18 2023-12-19 22:02 libcrypto.so.1.1 -> libcrypto.so
-rw-rw-rw- 1 shell shell   614928 2023-12-19 21:52 libssl.so
lrwxrwxrwx 1 shell shell       18 2023-12-19 22:02 libssl.so.1.1 -> libssl.so
```

**Comment by am11** [comment]
I think you just need to set `LD_LIBRARY_PATH`, since libssl does not seem to be in the system path.

```sh
LD_LIBRARY_PATH=$(pwd) ./webSocket-client
```

**Comment by xljiulang** [comment]
> I think you just need to set `LD_LIBRARY_PATH`, since libssl does not seem to be in the system path.
> 
> ```shell
> LD_LIBRARY_PATH="$(pwd)" ./webSocket-client
> ```

Your opinion is correct, thank you.
