### ISSUE TITLE
[AssemblyLoadContext]: Restriction dlls for new Plugins

### ISSUE THREAD

**Issue by sajjadarashhh** [dotnet/runtime#96207]
### Background and motivation

hi everyone i have an application that writed with aspnetcore and now i wana to create plugin managment system for that.
my users have high level data that must be cared from leaking or threatened by their competitors.
now we must be create open base plugin manager system that everyone can create plugin for us
but their must be request permission to access data or network or fileIO
i wana to restrict them to access Folder that i give them access like it:
Folder: approot/plugins/pluginName/....
and i wana to restrict them to access network just for send and receive http request and response just for urls that them requested and accepted by user like it:
plugin requested: google.com/signup....
user accepted that and now i just accept to get and send requests to that url!
how can i do that in .net 8?
there is no available resources for it in documentation or stackoverflow!

### API Proposal

.

### API Usage

.

**Comment by huoyaoyuan** [comment]
> my users have high level data that must be cared from leaking or threatened by their competitors.
> now we must be create open base plugin manager system that everyone can create plugin for us
> but their must be request permission to access data or network or fileIO

The .NET runtime has no way to enforce such control. They can always define P/Invoke themselves, or use unsafe operations to steal other information within the process.

The code access security feature has been proved as a false sense of security. The suggested way for access control is to rely on the operation system, use different processes and user identities for different access.

**Comment by sajjadarashhh** [comment]
This might be bad scenario for my problem!
How can i load plugins with different permissions? 😂
Create another console application for each of them and execute that with different user????

**Comment by huoyaoyuan** [comment]
Trying to set different permissions in the same process has been proven very flaky. It can be bypassed by enormous of ways.

**Comment by sajjadarashhh** [comment]
I try to using mocked runtime assembly but i dont know why types not equal 😂

**Comment by sajjadarashhh** [comment]
when i load types from different load Context i cant cast types between them :|

**Comment by vitek-karas** [comment]
> when i load types from different load Context i cant cast types between them :|

If you load the same assembly into two different load contexts, runtime treats them as two completely separate assemblies (even if they come from the exact same file) and thus types defined by these assemblies are also treated as completely separate. As such you can't cast from one to the other.

The recommendation is to define a set of assemblies which are used to "communicate" between the plugins and the host, and these will always come from the host - the plugins should not even ship with them. That way you only load them once and thus avoid problems with duplicate type definitions.

**Comment by agocke** [comment]
Closed as answered -- ALCs provide cooperative separation, if that's acceptable.
