### ISSUE TITLE
String comparison regression bug

### ISSUE THREAD

**Issue by clement911** [dotnet/runtime#96205]
### Description

The String comparison logic returns incorrect result for some string.

### Reproduction Steps

```csharp
using System;
using System.Globalization;

public class Program
{
   public static void Main()
   {
       Console.WriteLine(new CultureInfo("en-US").CompareInfo.Compare("ʻ", "", CompareOptions.IgnoreNonSpace));
   }
}
```

### Expected behavior

Console prints 0

### Actual behavior

Console prints 1

### Regression?

It's a regression.
It works fine in .NET framework 4.7.2 so it appears the bug is limited to .NET core

### Known Workarounds

None that I'm aware of.

### Configuration

.NET 8 Windows x64

### Other information

This seems to be a regression. It works in .NET framework but not .NET core

**Comment by huoyaoyuan** [comment]
There is wide globalization change between .NET Framework and .NET Core. .NET Framework uses Windows NLS while .NET Core uses [ICU](https://github.com/unicode-org/icu) by default. See https://learn.microsoft.com/dotnet/core/extensions/globalization-icu .

With that said, this may be a bug of CompareOptions.IgnoreNonSpace handling in .NET Core.

**Comment by clement911** [comment]
@huoyaoyuan the doc says that ICU is used from .NET 5 onwards but I can reproduce the issue even with .NET Core 3.1 so it might not be related to the ICU change

**Comment by clement911** [comment]
Actually sorry, I **cannot** reproduce with .NET Core 3.1
We came across this bug because it makes `SqlString` comparison not consistent with sql server's behavior.

**Comment by tarekgh** [comment]
Closing this as per replies. Apps want to get the old behavior can use [use nls instead of icu](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#use-nls-instead-of-icu). We don't recommend it though as in the future this will be legacy obsolete behavior.
