### ISSUE TITLE
Executing http request in node-wasm does not work anymore

### ISSUE THREAD

**Issue by bogdancucosel** [dotnet/runtime#96210]
Trying to execute a http request in dotnet 9.0 fails with the error 

```
node:internal/deps/undici/undici:6916
            throw new TypeError("Failed to parse URL from " + input, { cause: err });
                  ^

TypeError: Failed to parse URL from
```

https://github.com/dotnet/runtime/blob/8bd23f0792c6339478222ebc6635266e8f4098b4/src/mono/browser/runtime/http.ts#L21-L42

In dotnet 8.0 it works fine, since checking if request streaming is supported was not yet implemented.

**Comment by maraf** [comment]
@bogdancucosel What version of node are testing with? We are running HTTP unit tests on CI with node v18.17.1 and they pass regularly

**Comment by bogdancucosel** [comment]
@maraf I am using 21.5.0 . Will try to use v18 , and get back

**Comment by maraf** [comment]
I was able to run all our tests with node v21.6. I just had to remove the unsupported arg `--experimental-wasm-eh`

**Comment by bogdancucosel** [comment]
@maraf sorry it took so long. took the main branch , recompiled the runtime and then my project would not compile; there are some changes in the new targets (browser folder etc...) . 
Anyway managed to compile and indeed it does not repro anymore.
If it matters it was failing on the 2f8ef582a8e2e7e7996267694cd7ac73f9e8f34b commit . 
Thanks a lot
