### ISSUE TITLE
string.IndexOf(string) poor performance in other cultures

### ISSUE THREAD

**Issue by bennil** [dotnet/runtime#96221]
### Description

After migrating an old .NET Framework 4.7.2 windows app to .NET 8.0 I was suprised by it's poor performance.
I traced it down to an 11x times slower string.IndexOf(string) call on a large string (500 kilobyte).

But this happens only if the current culture is set other than English/Invariant.

### Benchmark running in German culture context
```

BenchmarkDotNet v0.13.11, Windows 11 (10.0.22621.2861/22H2/2022Update/SunValley2)
Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R), 1 CPU, 8 logical and 4 physical cores
  [Host]               : .NET Framework 4.8.1 (4.8.9181.0), X64 RyuJIT VectorSize=256
  .NET 5.0             : .NET 5.0.7 (5.0.721.25508), X64 RyuJIT AVX2
  .NET 8.0             : .NET 8.0.0 (8.0.23.53103), X64 RyuJIT AVX2
  .NET Framework 4.7.2 : .NET Framework 4.8.1 (4.8.9181.0), X64 RyuJIT VectorSize=256


```
| Method                                    | Job                  | Runtime              | Mean      | Error     | StdDev    | Ratio | RatioSD |
|------------------------------------------ |--------------------- |--------------------- |----------:|----------:|----------:|------:|--------:|
| IndexOfOfNotContainingStringInLargeString | .NET 5.0             | .NET 5.0             | 20.210 ms | 0.3075 ms | 0.2877 ms | 12.79 |    0.16 |
| IndexOfOfNotContainingStringInLargeString | .NET 8.0             | .NET 8.0             | 17.440 ms | 0.2713 ms | 0.2538 ms | 11.04 |    0.15 |
| IndexOfOfNotContainingStringInLargeString | .NET Framework 4.7.2 | .NET Framework 4.7.2 |  1.578 ms | 0.0098 ms | 0.0087 ms |  1.00 |    0.00 |

### Benchmark running in US culture context (perf as expected)

| Method                                    | Job                  | Runtime              | Mean       | Error    | StdDev   | Ratio | RatioSD |
|------------------------------------------ |--------------------- |--------------------- |-----------:|---------:|---------:|------:|--------:|
| IndexOfOfNotContainingStringInLargeString | .NET 5.0             | .NET 5.0             | 1,133.2 μs |  7.46 μs |  6.98 μs |  0.71 |    0.02 |
| IndexOfOfNotContainingStringInLargeString | .NET 8.0             | .NET 8.0             |   789.0 μs |  3.95 μs |  3.30 μs |  0.50 |    0.01 |
| IndexOfOfNotContainingStringInLargeString | .NET Framework 4.7.2 | .NET Framework 4.7.2 | 1,587.1 μs | 31.59 μs | 31.03 μs |  1.00 |    0.00 |

### Reproduce

[BenchmarkDotNet StringIndexOfFrameworkPerfTest repo](https://github.com/bennil/StringIndexOfFrameworkPerfTest)

You can easily switch the culture context in the BenchmarkDotNet setup method.

**Comment by tarekgh** [comment]
This is tracked by https://github.com/dotnet/runtime/issues/40942
