### ISSUE TITLE
HttpClient: Deadlock in `SendAsync` when `AllowDuplex` is true under specific conditions

### ISSUE THREAD

**Issue by huntharo** [dotnet/runtime#96223]
### Description

HttpClient will not send the `HEADERS` frame for requests that do have `Content` but do not have `EndStream` set when `SendHeadersAsync` is called.  It appears the only case that this applies to may be `AllowDuplex = true` in a custom `Content` object.

### Reproduction Steps

Complete example code:

https://github.com/huntharo/httpclient-duplex-deadlock

Video demonstrating the issue and the fix:

[![Reproduction of the deadlock issue in HttpClient and demonstration of possible fixes](https://img.youtube.com/vi/UN2oHXhKQf0/0.jpg)](https://www.youtube.com/watch?v=UN2oHXhKQf0)

### Expected behavior

It seems that `SendHeadersAsync` should *always* cause a flush as:
- Causing a flush when headers are written appears to be happening for everything *except* `AllowDuplex = true`
- Holding headers back seems like the wrong thing to do, ever, in that it will prevent the remote server from starting the request - delays here are bad
- At the very least, requests that have `AllowDuplex = true` should also be added to the `mustFlush` list

### Actual behavior

The behavior is changed by subsequent requests sent on the same connection:
- Subsequent `AllowDuplex = true` requests can cause a flush if there are enough parallel requests sent AND they have enough headers set (the values may need to be unique to avoid deduplication)
  - Under the right conditions this can make it appear that the problem does not exist
- Subsequent requests that set `ExpectContinue` will cause a flush
  - Setting ExpectContinue will always cause this to work, but results in an additional round trip (confirm?) and is not desirable
- Requests that either have no `Content` or that have `EndStream` set (essentially: `AllowDuplex = false`) will cause a flush
  - Sending a GET request (or POST with ready-at-send `Content`) will cause the stuck request to send its `HEADERS` frame
  - The `HEADERS` frame will be delayed up to the time that the GET request is sent

Failure to use one of the above workarounds will cause the request to timeout without ever sending the `HEADERS` frame.

### Regression?

- Did not test prior versions of dotnet
- There is issue #1511 
  - This issue says to support bidirectional content over Http2
  - The support is nearly 100% there, this was the only issue I discovered in hundreds of millions of requests that read the response body (to completion) before sending the request body
  - My project was observing periodic 5 second hangs that corresponded to a 5 second interval of a "ping" GET request sent over the same HttpClient 

### Known Workarounds

See actual behavior, but it appears that `ExpectContinue = true` is a workaround, as is sending a ton of headers.

### Configuration

- dotnet 8.0 / also `release/8.0` branch built locally as of 2023-12-20
- Mac OS X Sonoma
- ARM64
- The problem does not appear to be specific to this configuration at all

### Other information

Possibly the simplest fix is that the callback in `SendHeadersAsync` should *always* return `true`, causing a flush.  The nominal case of non-duplex requests essentially always causes this to return `true` and it seems only this odd case of duplex requests is causing it to return `false`.
https://github.com/dotnet/runtime/blob/2f1fbb009cccc137092429e2a7f367ad7bed92b9/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L1684

However, a more narrow fix is to add in `mustFlush: ... || duplex` here after moving the `bool duplex = ` line to be above the `SendHeadersAsync` call: https://github.com/dotnet/runtime/blob/2f1fbb009cccc137092429e2a7f367ad7bed92b9/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L1999

I would love to make the PR and add tests for this after the approach is approved.

**Comment by MihaZupan** [comment]
See https://github.com/dotnet/runtime/issues/30295#issuecomment-516210081

The gist is that if you want the headers to be sent immediately, even if you don't have any data to send yet using a custom HttpContent, you can call `FlushAsync` on the output stream to force the headers to be sent.

The same is true for HTTP/1.1.

**Comment by huntharo** [comment]
> See [#30295 (comment)](https://github.com/dotnet/runtime/issues/30295#issuecomment-516210081)
> 
> The gist is that if you want the headers to be sent immediately, even if you don't have any data to send yet using a custom HttpContent, you can call `FlushAsync` on the output stream to force the headers to be sent.
> 
> The same is true for HTTP/1.1.

Thanks for the quick reply!

From looking at the Functional tests, it appears that the behavior you described is untested as the custom `HttpContent` classes do not perform this `FlushAsync` call on their `Stream` and only a single request is sent on each connection / client in each test.

While the behavior is goofy and unfriendly to developers (it took me ~8 hours to figure out this deadlock), I can confirm the `FlushAsync` works but I'd really like to get tests in place with custom `HttpContent` implementations that demonstrate this so it is as least somewhat easier for others to discover how to handle it correctly.

Do you think it would be possible to augment the timeout exception to indicate that unflushed `HEADERS` were pending when the connection timed out?

**Comment by CarnaViire** [comment]
> it appears that the behavior you described is untested as the custom HttpContent classes do not perform this FlushAsync call on their Stream

The behavior _is tested_, we just do it directly on the stream for clarity, see e.g.:

https://github.com/dotnet/runtime/blob/623cf77a58f7a233b94dcc1c3ef8eb8d67e8d948/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs#L2440-L2446

https://github.com/dotnet/runtime/blob/623cf77a58f7a233b94dcc1c3ef8eb8d67e8d948/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs#L716-L719

Though it is definitely possible to incorporate it inside the content implementation as well, e.g. gRPC does it [here](https://github.com/grpc/grpc-dotnet/blob/87cce280d7c014d0e068ce7735998ccb6698ddd5/src/Grpc.Net.Client/Internal/Http/PushStreamContent.cs#L45-L47).
