### ISSUE TITLE
[Fuzzlyn] Assertion failed 'tgtIG' during 'Generate code' 

### ISSUE THREAD

**Issue by amanasifkhalid** [dotnet/runtime#96224]
[Last Fuzzlyn run](https://dev.azure.com/dnceng-public/public/_build/results?buildId=503543&view=results) failed on OS X ARM64 with the following assert:

Reduced example:
```csharp
// Generated by Fuzzlyn v1.6 on 2023-12-24 17:50:10
// Run on Arm64 MacOS
// Seed: 17421103114350285504
// Reduced from 177.9 KiB to 1.7 KiB in 00:01:10
// Hits JIT assert in Release:
// Assertion failed 'tgtIG' in 'Program:Main(Fuzzlyn.ExecutionServer.IRuntime)' during 'Generate code' (IL size 96; hash 0xade6b36b; FullOpts)
// 
//     File: /Users/runner/work/1/s/src/coreclr/jit/emit.cpp Line: 5174
// 
using System.Runtime.CompilerServices;

public class Program
{
    public static IRuntime s_rt;
    public static byte[] s_4;
    public static long s_25;
    public static bool s_29;
    public static ushort[] s_46;
    public static long s_59;
    public static void Main()
    {
        CollectibleALC alc = new CollectibleALC();
        System.Reflection.Assembly asm = alc.LoadFromAssemblyPath(System.Reflection.Assembly.GetExecutingAssembly().Location);
        System.Reflection.MethodInfo mi = asm.GetType(typeof(Program).FullName).GetMethod(nameof(MainInner));
        System.Type runtimeTy = asm.GetType(typeof(Runtime).FullName);
        mi.Invoke(null, new object[]{System.Activator.CreateInstance(runtimeTy)});
    }
    
    public static void MainInner(IRuntime rt)
    {
        long[] vr5 = new long[]{0};
        for (int vr6 = 0; vr6 < 2; vr6++)
        {
            var vr7 = new int[]{1};
            vr5[0] = (M50(vr7) & 0) / (int)M58();
            s_rt.WriteLine("c_339", s_46[0]);
            s_rt.WriteLine("c_340", 5566640345371016742UL);
        }
    }

    public static int M50(int[] arg0)
    {
        if (s_29)
        {
            s_59 = s_25;
        }

        return arg0[0];
    }

    public static ulong M58()
    {
        s_4 = new byte[]{0};
        return 5566640345371016742UL;
    }
}

public interface IRuntime
{
    void WriteLine<T>(string site, T value);
}

public class Runtime : IRuntime
{
    public void WriteLine<T>(string site, T value) => System.Console.WriteLine(value);
}

public class CollectibleALC : System.Runtime.Loader.AssemblyLoadContext
{
    public CollectibleALC(): base(true)
    {
    }
}
```

cc @dotnet/jit-contrib, does anyone have an ARM64 Mac they can repro this failure on?

**Comment by BruceForstall** [comment]
This looks like a possible GC info issue: running with `DOTNET_GCStress=0xC` might make it reproduce more reliably.

**Comment by jakobbotsch** [comment]
The GC issue reproduces intermittently. I have never been able to reproduce it reliably.

The reduced example here looks unrelated to the GC issue (different seed). Not sure why it does not show anything interesting in the comment header (please include it, the seed can be quite important)

**Comment by jakobbotsch** [comment]
From the logs, the original program that resulted in the reduced example above hit the following assert:
```scala
Found example with seed 16090003956643131594 that hits error
JIT assert failed:
Assertion failed 'tgtIG' in 'Program:M49(byte):uint' during 'Generate code' (IL size 1628; hash 0x56b90d1c; FullOpts)

File: /Users/runner/work/1/s/src/coreclr/jit/emit.cpp Line: 5174

Reducing 16090003956643131594
Running: /tmp/helix/working/BBC30A1C/p/exploratory/Fuzzlyn --host /tmp/helix/working/BBC30A1C/p/CoreRoot/corerun --reduce --seed 16090003956643131594 --output /tmp/helix/working/BBC30A1C/t/tmpt6tohw_b/16090003956643131594.cs
```
Based on the comment header the reduced example might or might not hit the same assert (again, not totally sure what happened there, I will add it to my todo list to investigate this from the Fuzzlyn side once I'm back)

**Comment by amanasifkhalid** [comment]
The `tgtIG` assert was hit with by a few smaller example programs in the latest run. Here's one such example:
```csharp
// Generated by Fuzzlyn v1.6 on 2023-12-24 17:50:10
// Run on Arm64 MacOS
// Seed: 17421103114350285504
// Reduced from 177.9 KiB to 1.7 KiB in 00:01:10
// Hits JIT assert in Release:
// Assertion failed 'tgtIG' in 'Program:Main(Fuzzlyn.ExecutionServer.IRuntime)' during 'Generate code' (IL size 96; hash 0xade6b36b; FullOpts)
// 
//     File: /Users/runner/work/1/s/src/coreclr/jit/emit.cpp Line: 5174
// 
using System.Runtime.CompilerServices;

public class Program
{
    public static IRuntime s_rt;
    public static byte[] s_4;
    public static long s_25;
    public static bool s_29;
    public static ushort[] s_46;
    public static long s_59;
    public static void Main()
    {
        CollectibleALC alc = new CollectibleALC();
        System.Reflection.Assembly asm = alc.LoadFromAssemblyPath(System.Reflection.Assembly.GetExecutingAssembly().Location);
        System.Reflection.MethodInfo mi = asm.GetType(typeof(Program).FullName).GetMethod(nameof(MainInner));
        System.Type runtimeTy = asm.GetType(typeof(Runtime).FullName);
        mi.Invoke(null, new object[]{System.Activator.CreateInstance(runtimeTy)});
    }
    
    public static void MainInner(IRuntime rt)
    {
        long[] vr5 = new long[]{0};
        for (int vr6 = 0; vr6 < 2; vr6++)
        {
            var vr7 = new int[]{1};
            vr5[0] = (M50(vr7) & 0) / (int)M58();
            s_rt.WriteLine("c_339", s_46[0]);
            s_rt.WriteLine("c_340", 5566640345371016742UL);
        }
    }

    public static int M50(int[] arg0)
    {
        if (s_29)
        {
            s_59 = s_25;
        }

        return arg0[0];
    }

    public static ulong M58()
    {
        s_4 = new byte[]{0};
        return 5566640345371016742UL;
    }
}

public interface IRuntime
{
    void WriteLine<T>(string site, T value);
}

public class Runtime : IRuntime
{
    public void WriteLine<T>(string site, T value) => System.Console.WriteLine(value);
}

public class CollectibleALC : System.Runtime.Loader.AssemblyLoadContext
{
    public CollectibleALC(): base(true)
    {
    }
}
```

**Comment by jakobbotsch** [comment]
Let's repurpose this issue to track the `tgtIG` assert. I do not think there is anything actionable here for the GC issue, unfortunately.

**Comment by BruceForstall** [comment]
@jakobbotsch I'm not able to reproduce this assert locally. Is there anything special I need to do?

Here's what I've done:
1. `dotnet new console`
2. Replace Program.cs contents with one of the test cases from https://dev.azure.com/dnceng-public/public/_build/results?buildId=526788&view=ms.vss-build-web.run-extensions-tab
3. `dotnet build -c Release`
4. build Checked and Release runtime (osx-arm64).
5. Create Core_Roots
6. copy libclrjit.dylib from Checked to Release
7. corerun the test, e.g., `~/gh/runtime2/artifacts/tests/coreclr/osx.arm64.Release/Tests/Core_Root/corerun /Users/bruce/bugs/96224/bin/Release/net8.0/96224.dll`

I've tried with and without `DOTNET_TieredCompilation=0`. I've tried with a pure Checked Core_Root.

I notice the assertion is:
```
Assertion failed 'tgtIG' in 'Program:Main(Fuzzlyn.ExecutionServer.IRuntime)'
```
but the test fragment doesn't have a `Main` that takes a `Fuzzlyn.ExecutionServer.IRuntime` and in fact I don't see any `Fuzzlyn` class/namespace. So is there some magic here we're not seeing?

**Comment by BruceForstall** [comment]
One thing I noticed with the original repro is it compiled fine (I couldn't repro the assert), but it failed to run. Maybe that's standard behavior for a Fuzzlyn repro? It was because `public static IRuntime s_rt;` was never initialized. Making that `public static IRuntime s_rt = new Runtime();` fixed it. Is that expected?

**Comment by jakobbotsch** [comment]
> One thing I noticed with the original repro is it compiled fine (I couldn't repro the assert), but it failed to run. Maybe that's standard behavior for a Fuzzlyn repro? It was because `public static IRuntime s_rt;` was never initialized. Making that `public static IRuntime s_rt = new Runtime();` fixed it. Is that expected?

Yeah, it's expected. Since the interesting behavior here is an assertion, no code was actually running, so Fuzzlyn was able to remove all of the initialization as part of simplifying the program.

**Comment by BruceForstall** [comment]
I can repro the test failure with the linked repro-24575.zip MC file.

The failure is because of the following:
1. In the phase to create throw helper blocks we create 3 blocks; 2 are for DIV (DIV_BY_ZERO, OVERFLOW).
2. During PHASE Calculate stack level slots, we decide 2 of the throw helper blocks are unreachable, including the OVERFLOW block, due to the dividend being a constant zero such that OVERFLOW is no longer possible:
```
N003 (  1,  2) [000210] -----------                  t210 =    CNS_INT   int    0 $c5
N005 ( 14,  2) [000028] --CXG------                   t28 =    CALL      long   Program:M58():ulong $183
                                                            /--*  t28    long
N006 ( 15,  4) [000032] --CXG------                   t32 = *  CAST      int <- long $301
                                                            /--*  t210   int
                                                            +--*  t32    int
N007 ( 51, 13) [000033] --CXG------                   t33 = *  DIV       int    $303
```
3. Later, LSRA inserts a RELOAD node for the constant zero:
```
N089 (  1,  2) [000210] ----------Z                  t210 =    CNS_INT   int    0 REG x0 $c5
                                                            /--*  t210   int
               [000243] -----------                  t243 = *  RELOAD    int    REG x1
N091 ( 14,  2) [000028] --CXG------                   t28 =    CALL      long   Program:M58():ulong REG x0 $183
                                                            /--*  t28    long
N093 ( 15,  4) [000032] --CXG------                   t32 = *  CAST      int <- long REG x0 $301
                                                            /--*  t243   int
                                                            +--*  t32    int
N095 ( 51, 13) [000033] --CXG------                   t33 = *  DIV       int    REG x0 $303
```
4. After that, `GenTree::CanDivOrModPossiblyOverflow()` no longer sees the constant zero dividend, and says that overflow is possible.
5. Thus, during codegen, it looks for the throw helper block that has already been removed.
6. In the current code, it finds a block that is no longer in the block list despite `acdUsed == false`.
7. Since this block isn't in the block list, it was never given a codegen label, so `tgtIG` is nullptr when branch codegen is done.

One fix is to pay more attention to `acdUsed` (checking it, asserting on it). The other is to teach `GenTree::CanDivOrModPossiblyOverflow()` about RELOAD, or otherwise not change the result of `GenTree::OperExceptions()` between `Calculate stack level slots` (StackLevelSetter phase) and codegen (basically, through LSRA).
