### ISSUE TITLE
DOTNET_EnableDiagnostics=0 disables profiling in .NET 8

### ISSUE THREAD

**Issue by nr-ahemsath** [dotnet/runtime#96227]
### Description

It appears that setting `DOTNET_EnableDiagnostics=0` (or `COMPlus_EnableDiagnostics=0`) disables profiling in .NET 8.  This is a behavior change from .NET 7.  I believe what causes this are the changes in this PR: https://github.com/dotnet/runtime/pull/90159

I'm an engineer on New Relic's .NET agent team and this issue was brought to our attention by a customer who observed that our agent (which is a profiler) stopped working for them in .NET 8 when they had `COMPlus_EnableDiagnostics` set to 0.

### Reproduction Steps

See the attached repro: [EnableDiagnosticsDemo2.zip](https://github.com/dotnet/runtime/files/13733288/EnableDiagnosticsDemo2.zip)

This Docker project adds the New Relic .NET agent to a sample webapi project and configures our profiling environment variables.  The entrypoint is a script that runs the app and then checks to see if any New Relic log files have been created.  If log files are created, the profiler is working as expected.  If no log files are created, profiling is broken.  A line is printed with the results.  By running the repro with and without `DOTNET_EnableDiagnostics` set to 0, you can see the behavior difference:

```
PS C:\workspace\scratch\EnableDiagnosticsDemo2> docker build . -t enable_diagnostics_demo
(build output)
PS C:\workspace\scratch\EnableDiagnosticsDemo2> docker run enable_diagnostics_demo
Found 1 New Relic logs, profiling is working.
PS C:\workspace\scratch\EnableDiagnosticsDemo2> docker run -e DOTNET_EnableDiagnostics=0 enable_diagnostics_demo
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:8080
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
No New Relic logs found; profiling is disabled.
```

### Expected behavior

Similar behavior to .NET 7 where setting `DOTNET_EnableDiagnostics=0` doesn't disable profiling.

I checked to see if this behavior change was announced here: https://learn.microsoft.com/en-us/dotnet/core/compatibility/8.0
but I didn't see anything at first glance.  My understanding of the PR I linked in the description is to give customers finer-grained controls over what aspects of .NET runtime diagnostics to enable or disable, but it looks like it also makes it so the generic `DOTNET_EnableDiagnostics` disables/enables all three (profiling, debugging, and IPC), which it previously did not do.

### Actual behavior

Setting `DOTNET_EnableDiagnostics=0` disables profiling in .NET 8.

### Regression?

This is a behavior change from .NET 7 to .NET 8.

### Configuration

See the Dockerfile in the repro project.  I have reproduced this issue on Windows 11 (x64) as well as in the Debian docker container.

**Comment by tommcdon** [comment]
Hi @nr-ahemsath!  I apologize for the oversight in our breaking change documentation.  I agree our [documentation](https://learn.microsoft.com/dotnet/core/tools/dotnet-environment-variables#dotnet_enablediagnostics) should be clearer - `DOTNET_EnableDiagnostics` disables if `0` / enables if `1` all of diagnostics including the [Diagnostic Port](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/diagnostic-port), Debugging, and Profiling.  The current docs simply state setting it to `1` enables it.  Setting `DOTNET_EnableDiagnostics=0` overrides the sub-configuration variables, and the docs do not mention that behavior either.

As you have correctly pointed out, in .NET 8 we added new configuration knobs that will allow you to more granularly enable/disable diagnostics:

* [DOTNET_EnableDiagnostics_IPC](https://learn.microsoft.com/dotnet/core/tools/dotnet-environment-variables#dotnet_enablediagnostics_ipc) - enables the [Diagnostic Port](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/diagnostic-port)
* [DOTNET_EnableDiagnostics_Debugger](https://learn.microsoft.com/dotnet/core/tools/dotnet-environment-variables#dotnet_enablediagnostics_debugger) - enables debugging
* [DOTNET_EnableDiagnostics_Profiler](https://learn.microsoft.com/dotnet/core/tools/dotnet-environment-variables#dotnet_enablediagnostics_profiler) - enables profiling

To emulate previous behavior, I suggest setting the following to ensure the behavior is as intended:

```sh
export DOTNET_EnableDiagnostics=1
export DOTNET_EnableDiagnostics_IPC=0
export DOTNET_EnableDiagnostics_Debugger=0
export DOTNET_EnableDiagnostics_Profiler=1
```

I'll mark this issue as a documentation bug.  Hope this helps!  Thanks for reporting the issue!

**Comment by nr-ahemsath** [comment]
@tommcdon Thanks for the quick response, I'll let our customer know what the workaround is.
