### ISSUE TITLE
[DataTable] Decimal Column Bug, within parallel

### ISSUE THREAD

**Issue by TyKaSt** [dotnet/runtime#96234]
### Description

Hello :)

within DataTable / DataRow there is a bug, when you use a decimal field.
It happens if you set the fields in a parallel loop, tasks and so on...

The decimal field is sometimes not set. There is no exception when setting it, but if you check the field after setting, its DBNULL
See the minimal sample. I didnt test every Datatype, but on string, int, int64, double  this never happens.
On decimal it happens about 0.01 % of the row count

### Reproduction Steps

```
    DataTable tab = new DataTable();
    tab.Columns.Add("ValueDec", typeof(decimal));        


    Parallel.For(0, 10000, (rowid) =>
    {
//this produces about 9 errors for me, maybe you must adjust the loop target...
        DataRow row;
        lock (tab)
        {
            row = tab.NewRow();
        }
        Decimal d = new Decimal(1234);
        row[0] = d;
        if (row[0] == DBNull.Value)
        {
            Console.WriteLine($"this should not happen... rowid: {rowid}");
            //throw new Exception("this should not happen...");
        }
    });
```

### Expected behavior

field should not be DBNULL.Value

### Actual behavior

sometimes it is DBNULL

### Known Workarounds

I have huge DataTables that must be filled and posted to DB.
To get this faster i set the fields in parallel loops.
Currently workaround is i dont set decimal fields in parallel loops anymore :/

### Configuration

W10
.NET 7
x64/x64

**Comment by huoyaoyuan** [comment]
DataTable doesn't support parallel write. Each DataRow isn't independent, they are just interfaces of the storage of DataTable.

**Comment by Clockwork-Muse** [comment]
> I have huge DataTables that must be filled and posted to DB.

`DataTable`s are maybe not the best tool.  All major RDBMSs I'm aware of have dedicated import utilities that will parse a variety of formats and upload them.  Beyond that, there are other libraries/interfaces that are better suited for that role.

**Comment by roji** [comment]
Agreed with the above - concurrent mutation of DataTable isn't something that's supported AFAIK.. While it's interesting that an error occurs only for decimal and not for other types, there are no plans to make DataTable thread-safe in general.

I also agree with @Clockwork-Muse that DataTable isn't the right tool for doing bulk import. If import speed is important enough that you want to parallelize the DataTable population, you most definitely want to look into e.g. SqlBulkCopy (for SQL Server); you're likely to see far more significant performance gains by using the database's dedicated bulk import facility than you are from parallelizing DataTable population.

I'll go ahead and close this, but feel free to post back if there's any additional info or questions.

**Comment by MichalPetryka** [comment]
> While it's interesting that an error occurs only for decimal and not for other types

It may be something with decimal not being atomic to write/read I guess.

**Comment by roji** [comment]
@MichalPetryka that would more likely cause corruption in the actual decimal values getting inserted - but note that the OP hasn't posted what exact error they're actually getting.
