### ISSUE TITLE
UDP Socket.ReceiveFrom with receive timeout and SocketAddress shows inconsistent behavior between Windows and Linux 

### ISSUE THREAD

**Issue by compujuckel** [dotnet/runtime#96237]
### Description

When using `ReceiveFrom(Span<Byte>, SocketFlags, SocketAddress)` on an UDP socket with a receive timeout specified, the behavior between Windows and Linux is different when a timeout occurs.

On Linux, the `Size` property of the `SocketAddress` is set to 0, which causes subsequent calls to `ReceiveFrom` with the same `SocketAddress` to fail:
```
System.ArgumentOutOfRangeException: Provided SocketAddress is too small for given AddressFamily. (Parameter 'receivedAddress')
```

On Windows, the `Size` property is untouched.

### Reproduction Steps

```csharp
var socket = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);
socket.ReceiveTimeout = 1000;
socket.Bind(new IPEndPoint(IPAddress.Any, 12345));

var address = new SocketAddress(AddressFamily.InterNetwork);
var buffer = new byte[1500];

while (true)
{
    try
    {
        var bytesRead = socket.ReceiveFrom(buffer, SocketFlags.None, address);
    }
    catch (SocketException ex) when (ex.SocketErrorCode == SocketError.TimedOut) { }
}
````

### Expected behavior

Same behavior on all platforms (ideally leaving the `Size` property untouched)

### Actual behavior

Different behavior between Windows and Linux (see description)

### Known Workarounds

Manually resetting the size after a timeout "fixes" the issue.
`address.Size = address.Buffer.Length`

### Configuration

Windows 10 x64, .NET 8
Ubuntu 20.04 x64, .NET 8

**Comment by wfurt** [comment]
It is strange that the address would have size when nothing is received. I feel if anything we should update the Windows behavior. 
Using `address.Size = SocketAddress.GetMaximumAddressSize(socket.AddressFamily))` is probably best as it would also work for dual mode sockets.
