### ISSUE TITLE
Thread calling CancellationTokenSource.Cancel() continues with another task and after that released task by this thread is never run.

### ISSUE THREAD

**Issue by sufasah** [dotnet/runtime#96238]
### Description

Hello,

Some strange behavior happens which can be reproduced with simplified code below. It is encountered with .net core 3.1.426 but it can be reproduced in .net core 6.

```c#
public class Program
{
    private static readonly SemaphoreSlim SemSlimLock = new SemaphoreSlim(1, 1);
    private static CancellationTokenSource Cts = new CancellationTokenSource();

   public static async Task Main()
    {
        var retryThread = new Thread(async () =>
        {
            await WaitTask();
        })
        {
            Name = "WaitThread",
            IsBackground = true
        };
        retryThread.Start();

        await Request();
    }

    public static async Task WaitTask()
    {
        try
        {
            await Task.Delay(int.MaxValue, Cts.Token);
        }
        catch (OperationCanceledException) { }

        SemSlimLock.Wait();

        Cts.Dispose();
        Cts = new CancellationTokenSource();

        SemSlimLock.Release();
    }

    public static async Task Request()
    {
        SemSlimLock.Wait();

        await Task.Delay(2000);

        Cts.Cancel();

        SemSlimLock.Release();
    }
}
```

### Reproduction Steps

1. `WaitThread` calls `WaitTask` starts at first and this thread waits at the line of `Task.Delay` inside try block.
2. Main thread calls `Request` method then it acquires semaphore lock. Waits 2 seconds for `Task.Delay` then calls `Cts.Cancel`
3. At this point, Thread executing `Request` method switches to and run `WaitTask` and continues from the `Task.Delay` line inside it. `OpreationCancelledException` is thrown then it waits for semaphore lock which is already acquired in step 2.
4. Not executed code part inside `Request` Method after the `Cts.Cancel` line is never executed by any thread. The lock is never released and the program never stops.

### Expected behavior

I was expecting it to continue and finish the program even if the same thread calling `Cts.Cancel` in `Request` method is blocked at `SemSlimLock.Wait` as a dead lock situation. Some available or new thread generated for this remaining execution should continue after `Cts.Cancel` call and release the lock instead of waiting the same thread.

### Actual behavior

Not executing code part inside `Request` method after cancelling the cancellation token is a strange behavior. It looks like bug to me and I couldn't get how it happens because of cancelling the CancellationTokenSource.

**Comment by Clockwork-Muse** [comment]
You have a deadlock due to the use of `SemSlimLock`.

I suspect you're using it because the compiler warned you that a regular `lock` statement is forbidden in an async context.  This is why.
`SemaphoreSlim` has [`WaitAsync`](https://learn.microsoft.com/en-us/dotnet/api/system.threading.semaphoreslim.waitasync?view=net-8.0) that _may_ (without testing on my part) solve this particular issue.  However long term you will likely be better served by adjusting how you handle resource locking in your code.

**Comment by sufasah** [comment]
At first, thanks for the comment. Yes it is obviously a deadlock. I tried `WaitAsync` and it didn't solve. I commented out `SemSlimLock` lines in `WaitAsync` and it worked. Lines after `Cts.Cancel` call (currently it is only semaphore release) are executed with same thread when it is not blocked this way. Any other thread is not allowed to execute there as I see.  I wanted to highlight `CancellationTokenSource` part here. I wonder why it makes the same thread executing `WaitTask` method which executes `Request` method before and why only this same thread can execute after Cts.Cancel again.

**Comment by MihaZupan** [comment]
Looks like you ran into the same issue as #64051, which was fixed by #64217 in .NET 7.0.

**Comment by Clockwork-Muse** [comment]
@MihaZupan - Ah, yes, I knew there was an issue floating around for this.

**Comment by sufasah** [comment]
Yes, the issue looks like same with https://github.com/dotnet/runtime/issues/64051. Written test in the changes of https://github.com/dotnet/runtime/pull/64217 also looks like checking for the same case as descripted in the issue here and has much fewer lines.

My example case isn't reproducible with latest .net 8.0 when I try. We can close the issue since it is fixed for later versions. Thank you.
