### ISSUE TITLE
TimeZoneInfo.IsInvalidTime(DateTime) returns false for times which don't exist in Samoa Standard Time

### ISSUE THREAD

**Issue by daviddotcs** [dotnet/runtime#96269]
### Description

The `TimeZoneInfo.IsInvalidTime(DateTime)` method returns `false` when supplied any time within the 24 hour time hole that occurred for _Samoa Standard Time_ when their base UTC offset jumped forward 24 hours at the end of 2011, e.g.; _2011-12-31 12:00_. I believe this to be an error because those times don't exist within that time zone - they went straight from _2011-12-31 00:59:59 -10:00_ to _2012-01-01 01:00:00 +14:00_.

### Reproduction Steps

```csharp
var zone = TimeZoneInfo.FindSystemTimeZoneById("Samoa Standard Time");
var dateTime = new DateTime(2011, 12, 31, 12, 0, 0, DateTimeKind.Unspecified);

var isInvalid = zone.IsInvalidTime(dateTime); // false

var offset = zone.GetUtcOffset(dateTime); // -10:00

var dateTimeOffset = new DateTimeOffset(dateTime, offset);
dateTimeOffset = TimeZoneInfo.ConvertTime(dateTimeOffset, zone); // 2012-01-01 12:00:00 +14:00
```

### Expected behavior

I expect `zone.IsInvalidTime(dateTime)` to return `true`.

### Actual behavior

`zone.IsInvalidTime(dateTime)` returns `false`.

_2011-12-31 12:00_ is reported to be a valid time with UTC offset _-10:00_ within _Samoa Standard Time_, but creating a DateTimeOffset within that zone results in _2012-01-01 12:00:00 +14:00_, which has a different date and offset because _2011-12-31 12:00_ is not actually a valid time in that zone.

### Regression?

No, I experience the same behaviour on both .NET Framework 4.8 and .NET 8.

**Comment by Clockwork-Muse** [comment]
We pull date/time offset info from the OS, so we need OS info (platform, build number, etc) to figure out the data source.  This is particularly important, because older versions of Windows didn't carry the full history of some zones.

Also, bugs get fixed, so we need the version/build of .NET you're using.

**Comment by daviddotcs** [comment]
This is on **Microsoft Windows 10 Enterprise 10.0.19045** and occurs with both **.NET 8.0.0** and **.NET Framework 4.8.9195.0**.

It does have the applicable adjustment rules based on the results of the following which shows the 24 hour gap, so the `IsInvalidTime` results above seem inconsistent with this:
```csharp
var zone = TimeZoneInfo.FindSystemTimeZoneById("Samoa Standard Time");
var afterChangeDateTimeOffset = new DateTimeOffset(2012, 1, 1, 1, 0, 0, TimeSpan.FromHours(14));

var beforeChange = TimeZoneInfo.ConvertTime(afterChangeDateTimeOffset.AddTicks(-1), zone); // 2011-12-31 00:59:59 -10:00
var afterChange = TimeZoneInfo.ConvertTime(afterChangeDateTimeOffset, zone); // 2012-01-01 01:00:00 +14:00
```

**Comment by tarekgh** [comment]
This is a limitation on Windows TZ data that stored in the registry `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Time Zones\Samoa Standard Time\Dynamic DST`. The stored data can specify only one time transition during every year. Year 2011, The stored data specifying the transition between April and September. 

```
DateStart                  : 1/1/2011 12:00:00 AM (Unspecified)
DateEnd                    : 12/31/2011 12:00:00 AM (Unspecified)
DaylightDelta              : 01:00:00
DaylightTransitionStart    : M:9, D:1, W:4, DoW:Saturday, Time:1/1/0001 3:00:00 AM, FixedDate:False
DaylightTransitionEnd      : M:4, D:1, W:1, DoW:Saturday, Time:1/1/0001 4:00:00 AM, FixedDate:False
BaseUtcOffsetDelta         : -1.00:00:00
```

The data cannot specify the transition `Fri, Dec 30 at 12:00 am	+24 hours (DST increasing)	UTC+14h`. We are considering at some point switching to use the TZ data that stored in ICU instead when running on Windows, but this work is not done yet.
