### ISSUE TITLE
System.Data.Odbc/OleDb - DbProviderFactories.GetFactory(connection) fails

### ISSUE THREAD

**Issue by jdippner** [dotnet/runtime#96278]
### Description

This appears to go back to .NET framework and continues to exist in .NET8.  DbProviderFactories.GetFactory(connection) where connection is a valid ODBC connection returns null.  IT appears that the private member ProviderFactory never gets set.

### Reproduction Steps

DbProviderFactories.RegisterFactory("System.Data.Odbc", "System.Data.Odbc.OdbcFactory, System.Data.Odbc, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51");
var factory = DbProviderFactories.GetFactory("System.Data.Odbc");
var connection = factory.CreateConnection();
connection.ConnectionString = "your connection string";
var adapter = DbProviderFactories.GetFactory(connection).CreateDataAdapter(); // throws NullReferenceException
// private member connection.DbProviderFactory is never set
// note: can make direct call to OdbcFactory.Instance.CreateDataAdapter() and get an object

### Expected behavior

DbProviderFactories.GetFactory(connection).CreateDataAdapter(); // should return valid data adapter

### Actual behavior

DbProviderFactories.GetFactory(connection).CreateDataAdapter(); // throws NullReferenceException

### Regression?

fails as far back as .net Framework 4.8

### Known Workarounds

Can make direct call to OdbcFactory.Instance.CreateDataAdapter() and get an object, but this beats the purpose of using the abstracted interface.  As my current needs require this, I have to use reflection to locate OdbcFactory.Instance.

### Configuration

.NET - framework 4.8 - .NET 8.0 inclusive
OS - any
architecture - any cpu

**Comment by roji** [comment]
Thanks, yeah - seems like OdbcConnection isn't overriding the DbProviderFactory property. I'll submit a PR.

**Comment by jdippner** [comment]
Shay,

Thanks for looking into this  I see that this also applies to OLEDB
factory.  Should I submit a second incident report?

**Comment by roji** [comment]
@jdippner thank you for filing.

I think we can use this issue to track both ODBC and OleDB - I'll update the title.
