### ISSUE TITLE
,NET Core 3.1.32 - ExecuteEngineException (0x80131506) on hostile memory conditions

### ISSUE THREAD

**Issue by denis-dbm** [dotnet/runtime#96275]
### Description

Hi all

I encountered an "Execute Engine Error" on .NET Core 3.1.32 when the following warning is triggered by Windows System about virtual memory:

> Windows has successfully diagnosed an insufficient virtual memory condition. The following programs consumed the most virtual memory: svchost.exe (840) consumed 6985805824 bytes, coreServiceShell.exe (1476) consumed 317431808 bytes, and TrustedInstaller.exe (4692) consumed 160571392 bytes.

After that, some Windows Services were aborted, including my .NET application that runs as a Windows Service. When my application is aborted, the execute engine error code is associated conforming to the following log:

> Application: my_app.exe
CoreCLR Version: 4.700.22.55902
.NET Core Version: 3.1.32
Description: The process was terminated due to an internal error in the .NET Runtime at IP .... (....) with exit code **80131506**.

Is that behavior a GC's bug or similar? Do they believe the GC or the .NET Runtime can handle* the low VM condition without crashing (or with a more appropriate error code)? If yes, do the recent versions handle the case?

I haven't tested that yet on recent .NET versions.

*PS: I know it can be very hard or impossible due the hostile conditions. But I choose to ask the experts anyway 😉

### Reproduction Steps

* Windows report low virtual memory condition
* .NET Runtime crashes with Execute Engine Code (0x80131506)

### Expected behavior

* Runtime don't crash or if possible a more appropriate error code

### Actual behavior

* .NET Runtime crashes with Execute Engine Code (0x80131506)

**Comment by huoyaoyuan** [comment]
.NET Core 3.1 has reached EOL for a year. The only suggestion is to update to a supported version and see if the same issue still reproduces.
