### ISSUE TITLE
[Mono][RISC-V] Undefined Behavior caused by return ulong as uint8 without cast

### ISSUE THREAD

**Issue by Xinlong-Wu** [dotnet/runtime#96276]
When I was debugging Mono RISC-V using regression testing, the testcase [JIT/Regression/JitBlue/DevDiv_545500/DevDiv_545500.il](https://github.com/dotnet/runtime/blob/main/src/tests/JIT/Regression/JitBlue/DevDiv_545500/DevDiv_545500.il) failed. 

The main reason for the failure is that testcase returns a value with type ulong via function uint8 Test(...) and comparing the return values. it causes an undefined behavior on RISC-V.

## Details

start from the line `126` of `DevDiv_545500.il`,

```
.method public hidebysig static uint8 
          Test(float32 f, int32 i, int64 l) cil managed noinlining
  {
          ....
         cgt         
         shr.un      
         neg         
         ret 
  } // end of method DevDiv_545500:Test
```

in which, `cgt` compare two value and push `1` to the value stack. `shr.un` shift value `0xffffffff` to right 1 bit, the result is `0x7fffffff`. `neg` result the value `0xFFFFFFFF80000001` which should be a `ulong` value. 

at `DevDiv_545500:Main`, 

```
method public hidebysig static int32  Main() cil managed
  {
    .custom instance void [xunit.core]Xunit.FactAttribute::.ctor() = (
        01 00 00 00
    )
    .entrypoint
    .locals init ([0] int32 retVal, [1] int32 testResult)

         ldc.i4     100
         stloc.0
         ldc.r4     1.0
         ldc.i4     1
         ldc.i8     3
         call       uint8 DevDiv_545500::Test(float32 f, int32 i, int64 l)
         stloc.1
         ldloc.1
         ldc.i4.1
         ceq
         brtrue.s  L1
        .....
}
```
it just compare the return value of `DevDiv_545500::Test` with `1`. but in fact the function returns a ulong without casting.
That cause the problem.

I am compare with same program runs on x86 arch, x86 move return value by `mov %al, %rax`, which `%al` is the lower part of `%rax`, I think it can be treat as a kind of implict casting. 
But RISC-V only has fixed length registers, we can't do it like that.

Also, I'm trying to make it reappear using C# code:

```
using System;

public class Test
{
    public static Byte TestRun(uint u)
    {
        return (-(u>>1));
    }
    
    public static void Main()
    {
        uint i = 0xffffffff;
        Console.WriteLine(i);
    }
}
```

the compiler will report `Cannot implicitly convert type 'long' to 'byte'. An explicit conversion exists (are you missing a cast?)`. It means C# also don't accept coding like that. 

I'm wondering what this testcase trying to test? If it doesn't test this point, can we add a casting code like `conv.u1`? cuz I don't think the runtime should care about this **unsafe** behavior.

Or, How can I skip it?

---
cc: https://github.com/dotnet/runtime/issues/96117

**Comment by jkotas** [comment]
> shr.un shift value 0xffffffff to right 1 bit, the result is 0x7fffffff. neg result the value 0xFFFFFFFF80000001 which should be a ulong value.

According to [ECMA-335](https://www.ecma-international.org/publications-and-standards/standards/ecma-335), the result of this sequence of operations is int32. This int32 is expected to be converted (trucated) to uint8 when returned from the method (look for "implicit conversions" in the ECMA-335 spec).

> I'm wondering what this testcase trying to test? 

This looks like an auto-generated test case. It is trying to test a sequence of operations that hit a codegen bug at some point in the past.

> can we add a casting code like conv.u1? 

I do not see any problem with the test case.

> I don't think the runtime should care about this unsafe behavior.

The test case is valid IL. The JIT should insert the cast implicitly when generating the code.

**Comment by am11** [comment]
> How can I skip it?

To skip tests, you can add an `ItemGroup` conditioned on `mono+riscv64` like the following in `src/tests/issues.targets` file:
https://github.com/dotnet/runtime/blob/14127ea770cf748509b9057b7a8ed5a3471ebfed/src/tests/issues.targets#L2514

**Comment by Xinlong-Wu** [comment]
I have find the problems.

at https://github.com/dotnet/runtime/blob/e9d53b7d7de81a6ae9f19f50a83401e6c204760a/src/mono/mono/mini/method-to-ir.c#L2234-L2253

There is a Microdef called `MONO_ARCH_LLVM_SUPPORTED` it allows Mono JIT engine insert a extra Inst to truncate the widen return value.

The comment saids
> LLVM code doesn't uses zero extend the full word while jit expects it.

Actually, not only LLVM doesn't uses zero extend the full word, but at laest RISC-V and ARM64 also doesn't do that.

So I think the name of Microdef might be kind of cobfused.

Should we rename it as somthing like `MONO_ARCH_NEED_EXTRA_TRUNCATE_OP` ?

**Comment by vargaz** [comment]
What happens there is the mono jit zero/sign extends return values to 32/64 bits, while llvm doesn't, which means the upper bits are undefined and can be anything. This is why we sign/zero extend the return values received from llvm code or native code. I think it would be easier if the riscv backend would also sign/zero extend the return value, in mono_arch_emit_epilog () for example.
