### ISSUE TITLE
Question about dll resolution in hostfxr

### ISSUE THREAD

**Issue by mrtflv** [dotnet/runtime#96271]
Hello everyone, i'm using a c# dll net core 8 in windows environment using hostfxr from c++.
I have a main program c++ that load a c# dll class and this dll references others dll.
All of dll information are inside the c# dll.deps.json.
Inside c# i need to load a specific dll defines at runtime via reflection and i do this goal using 
var loadContext = AssemblyLoadContext.GetLoadContext(typeof(..).Assembly);
assembly = loadContext.LoadFromAssemblyPath("Path to dll"));
In this way i can use the dll, but a problem appears when the loaded dll has dependencies not defined inside the .deps.json, i always get an exception that the assembly could not be found even if it exists .
I tried to add inside the c# dll an  AppDomain.CurrentDomain.AssemblyResolve and inside this event load the dependent dll but the error is the same.
Is there any way to load a dll not described inside the deps.json ?
Thanks for any idea.
Flavio

**Comment by vitek-karas** [comment]
I would recommend reading this https://learn.microsoft.com/en-us/dotnet/core/dependency-loading/overview. It gives a good overview of what's going on in the runtime. The answer to your question depends on if you're using secondary `AssemblyLoadContext` (ALC) instances. Ideally the dependency resolution would happen inside the ALC which asked for it. This is what the sample in the docs does for plugin ALCs.

Using the `AppDomain.AssemblyResolve` might also work correctly. But without know how it fails and what your code does, it's hard to tell what's wrong. High-level I think you're using the right APIs. I would suggest you debug this - put a breakpoint into your `AssemblyResolve` handler and see what name it's asked for and what does it return.

Another source of diagnostic information might be tracing: https://learn.microsoft.com/en-us/dotnet/core/dependency-loading/collect-details
