### ISSUE TITLE
Issue when coupling with System.Json.Text source generator

### ISSUE THREAD

**Issue by HakamFostok** [dotnet/runtime#96273]
### Description

It took me 2 days to catch the problem.
I am using 
1.0.0-beta08
.NET 7
Visual studio 2022

Add an enum in one class library
```
[NetEscapades.EnumGenerators.EnumExtensions]
public enum Enum1
{
    Value1,
    Value2,
}
```

Add class **In another class library (very important, if added in the same class library then everything is ok)**

```
public class JsonModel
{
    public Enum1 Enum { get; set; }
}
```

Now try to add System.Text.Json Source generator for the `JsonModel` class by doing the following

```
[JsonSerializable(typeof(JsonModel))]
public partial class MyJsonContext : JsonSerializerContext { }
```

the Json source generator will emit NOTHING.

go the the enum and remove or comment `[NetEscapades.EnumGenerators.EnumExtensions]` above the enum.
save the changes and wait a little bit, and the json source generator will emit the serializing.
If you do that while the Anaylizer is expanded for the both project, it will appears in more vivid way.

![image](https://github.com/andrewlock/NetEscapades.EnumGenerators/assets/12747172/908f08e2-85a0-47ac-8307-418389681deb)

There is a conflict between the 2 source generators, 
and the NetEscapades.EnumGenerator source-generator prevents the Json source-generator from working.

### Reproduction Steps

here is a repo that reproduces the bug 
https://github.com/HakamFostok/NetEscapadesError

### Expected behavior

both source generators must be working

### Actual behavior

only one source generator generates code

### Known Workarounds

none

### Other information

[original bug reported on NetEscapades.EnumGenerators repo](https://github.com/andrewlock/NetEscapades.EnumGenerators/issues/69),
but @andrewlock suggested me to open this bug on this repo

**Comment by HakamFostok** [comment]
Original bug

https://github.com/andrewlock/NetEscapades.EnumGenerators

**Comment by eiriktsarpalis** [comment]
Does the issue reproduce in .NET 8? We fixed a number of bugs related to cross-assembly references in the latest release.

**Comment by eiriktsarpalis** [comment]
I tested your repro locally and can confirm that it has been fixed in .NET 8.

**Comment by HakamFostok** [comment]
Yes, I can confirm that I updated to .NET 8, and the bug magically disappeared.
Have no idea how, but happy to see that
