### ISSUE TITLE
ObjectDisposedException from FileConfigurationProvider in net8.0

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#96282]
### Description

Configuration providers might be built multiple times from the same source.  Creating and disposing one provider should not "break" the source.

### Reproduction Steps

Sample user reported repro:
```c#
using Microsoft.Extensions.Configuration;

var config = new ConfigurationManager() as IConfigurationBuilder;

_ = config.AddJsonFile("./appsettings.json", optional: false, reloadOnChange: true);
//  workaround
//_ = config.AddJsonFile(config.GetFileProvider(), "./appsettings.json", optional: false, reloadOnChange: true);


// change properties after setting up Json config
_ = config.Properties.Remove("ConfigurationBuilderPropertiesObserverKey");
_ = config.Properties.Remove("SecretObserverExtensionsConfigurationBuilderPropertiesObserverKey");
```

Or even simpler (though more artificial):
```C#
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Configuration.Json;

var builder = new ConfigurationBuilder();
var jsonSource = new JsonConfigurationSource()
{
    Path = "appsettings.json",
    ReloadOnChange = true
};
((IDisposable)jsonSource.Build(builder)).Dispose();
_ = jsonSource.Build(builder);
```

### Expected behavior

Disposing one provider should not break others.  Once the last provider is disposed from a source, that source should still be able to build more providers that function correctly.

### Actual behavior

After disposing one provider, all others are broken, and newly built providers are also broken.

### Regression?

Yes, due to https://github.com/dotnet/runtime/pull/86455

### Known Workarounds

Specify a file provider when adding a FileConfigurationSource.

For example, instead of 
```C#
_ = config.AddJsonFile("./appsettings.json", optional: false, reloadOnChange: true);
```
Use this:
```C#
_ = config.AddJsonFile(config.GetFileProvider(), "./appsettings.json", optional: false, reloadOnChange: true);
```

### Configuration

Can repro in net6, net7, net8 when using the 8.0 version of Microsoft.Extensions.Configuration.

**Comment by vcsjones** [comment]
Dup of https://github.com/dotnet/runtime/issues/95745?

**Comment by tarekgh** [comment]
thanks @vcsjones. Yes this looks the same issue.
