### ISSUE TITLE
Scoped ServiceProvider not releasing disposing HttpClient

### ISSUE THREAD

**Issue by Seabizkit** [dotnet/runtime#96296]
### Description

i have spent some time narrowing this down to the smallest reproducible example
consider the below...

basically when using '  using (var scope = s.ServiceProvider.CreateScope())' im expecting that anything created in this scope is disposed when the scope is ended..

this does not seem to be the case for Typed HttpClients, where you register the client with  'AddHttpClient'

my testing it looks like its only disposed of when some internal 2min for holding on the to HttpCleint has been reached.

there should be no more references to the scoped context once disposed.

```
public sealed class Plugin : IParadoxComponent
{
    
    private Action<IServiceCollection, IConfiguration> SetupServices()
    {
        Action<IServiceCollection, IConfiguration> @delegate = (services, config) =>
        {
            services.AddLogging();
            services.AddHttpClient<ICustomerClient, CustomClientTest>();

        };
        return @delegate;
    }


    public async Task<PluginResponse> ExecuteAsync(ExecutingContext e, CancellationToken ct = default)
    {
        var response = new PluginResponse();
        using (var s = new Startup(SetupServices()))
        {
            using (var scope = s.ServiceProvider.CreateScope())
            {
                var services = scope.ServiceProvider;

                var client = services.GetRequiredService<ICustomerClient>();

            }
        }
        return response;
    }


}

public interface ICustomerClient
{
}

public class CustomClientTest : ICustomerClient
{
    HttpClient _httpClient;
    public CustomClientTest(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }
}

```

### Reproduction Steps

- create typed client
- request typed client from within a scoped ServiceProvider
- when the ServiceProvider is done check if HttpClient and CustomClientTest are complete free-ed
- it will not be for 2min, which means something in AddHttpClient does not respect being created in a scope.
- I put in loop to create many while watching memory and implenet a weekref to see when it free'ed only done after 2min

`GC.Collect();
GC.WaitForPendingFinalizers();`

```
private static void Main(string[] args)
 {
     Console.WriteLine("Hello, World!");

     for (int i = 0; i < 10000; i++) {

         var s = GetStuff();
         using (var scope = s.CreateScope())
         {
             var services = scope.ServiceProvider;
             var client = services.GetRequiredService<ICustomerClient>();
         }

         if (i % 100 == 0)
         {
             Console.WriteLine($"{i}");
             GC.Collect();
             GC.WaitForPendingFinalizers();
             Thread.Sleep(100);
         }
     }
    
 }

 public static IServiceProvider GetStuff()
 {

     ////register Configuration
     /********************************/
     var environment = Environment.GetEnvironmentVariable("ASPNET_ENVIROMENT") ??
                     Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") ?? "Development";

     string global = Directory.GetCurrentDirectory();
     string LocalPath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);


     // Create a dedicated FileProvider based on the /config directory
     var provider = new PhysicalFileProvider(LocalPath);

     var builder = new ConfigurationBuilder()
         .SetBasePath(global)
         .AddJsonFile("appsettings.json", true, false)
         .AddJsonFile($"appsettings.{environment}.json", optional: true, reloadOnChange: false)
         .AddJsonFile(provider, "appsettings.json", true, false)
         .AddJsonFile(provider, $"appsettings.{environment}.json", true, false);


     var config = builder.Build();
     /********************************/

     var services = new ServiceCollection();
     services.AddHttpClient<ICustomerClient, CustomClientTest>();

     var _serviceProvider = services.BuildServiceProvider();
     return _serviceProvider;
 }
```

mem should not be climbing all the time....

### Expected behavior

the scoped service and all of its services should be completely disposed... including type clients

### Actual behavior

scoped service hangs around until the typed client starts its internal cleanup like 2min later

### Known Workarounds

dont know of any

**Comment by Seabizkit** [comment]
how do i allow my scope to control lifetimes

**Comment by Seabizkit** [comment]
https://github.com/dotnet/runtime/issues/47091

looks like its simular...

come about for me as i try to test plugins and releasing of them.. it will not and its not clear why... its the code hanging on to instance via the underlying stuff of the factory stuffs which its not disposabled even tho the scope is simplicity told its finished.. this does not respect that scope.

**Comment by steveharter** [comment]
@Seebizkit can you clarify -- if https://github.com/dotnet/runtime/issues/47091 is addressed, what work is expected to still need to be done?

Thanks

**Comment by Seabizkit** [comment]
@steveharter well my understanding is they are basically the same thing, [could be wrong]

my issue is there is currently no why to actually control this that im aware of or could find, [well im hoping for alternative]
yes i can set [HandlerLifetime] but this does not actually do what i want. i want its scope to be the scope of the "var scope = s.ServiceProvider.CreateScope()"

aka how would i code for this... if the answer is https://github.com/dotnet/runtime/issues/47091 is addressed, then fair enough. otherwise am i missing something and this can actually be configure in such way that the scope is the scope.

if 47091 does not actually resolve this then, part of 47091 should be that this functionality behaves in such a way that one would expect.

as this is cause issue when trying

**Comment by buyaa-n** [comment]
@CarnaViire is this issue can be handled with https://github.com/dotnet/runtime/issues/47091? if so, we could close this as dup

**Comment by CarnaViire** [comment]
Yes, I confirm this is a dup of https://github.com/dotnet/runtime/issues/47091
