### ISSUE TITLE
Provide access to dynamically created instruments via DI

### ISSUE THREAD

**Issue by thompson-tomo** [dotnet/runtime#96305]
## Is there an existing issue for this?
I have searched the existing issues but can't find one

## Is your feature request related to a problem? Please describe the problem.
I want to make it as simple as possible for a developer to control the metrics which are being recorded. The recording of the metrics should be in a consistent manner. 

## Describe the solution you'd like
During setup/start up it should be possible to call an extension method AddMetricProvider() which adds IMetricProvider to the Service collection. If the extension method is not passed a configuration object, the meters are dynamically created on first usage otherwise they are pre-created based on the config.

IMetricProvider offers the following methods
- RecordValue (string instrumentName, string value) used for histogram
- RecordMeasurement<T>(string instrumentName, T value) used for Counter
- RecordMeasurementChange<T>(string instrumentName, T value) used for UpDownCounter

The configuration object Needs to Allow the following to be defined:
- collection of instruments to be created
- Name
- Tags
- Version

Each instrument needs to allow for the following to be defined:
- Name
- Description
- Enabled
- Tags
- Unit

## Additional context
No additional information

**Comment by tarekgh** [comment]
@thompson-tomo in .NET 8.0 we have added the metrics configuration, please look at https://github.com/dotnet/runtime/issues/85684#issuecomment-1670049087 and https://github.com/dotnet/runtime/issues/77514#issuecomment-1553414738. Does this match what you were proposing here?

CC @noahfalk

**Comment by thompson-tomo** [comment]
#85864 is somewhat similar but not quite. Effectively I would like to have my instrumentation rules (MetricsOptions) defined in my config system with these configuration simply resolved at startup and used to determine which rules are enabled etc.

**Comment by tarekgh** [comment]
I think all of that is already supported. MetricsOptions is supported with the configuration like the following. 

```C#
            var services = new ServiceCollection();
            services.AddOptions();
            services.Configure<MetricsOptions>(options => options.EnableMetrics(meterName));

            var container = services.BuildServiceProvider();
            var options = container.GetRequiredService<IOptions<MetricsOptions>>();
```

If you want to enable it at the startup time you follow the pattern of using [ValidateOnStart](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.optionsbuilderextensions.validateonstart?view=dotnet-plat-ext-8.0). 

What exactly is missing here? 

CC @noahfalk @Tratcher

**Comment by thompson-tomo** [comment]
Ahh you are correct @tarekgh i had missed the proposed changes for Microsoft.Extensions.Diagnostics.Configuration.dll. That does solve it hence closing this issue.
