### ISSUE TITLE
Offer Azure storage as a FileProvider

### ISSUE THREAD

**Issue by thompson-tomo** [dotnet/runtime#96304]
## Is there an existing issue for this?
I have searched the existing issues but can't find one

## Is your feature request related to a problem? Please describe the problem.
I wish to seamlessly connect to my files stored in Azure storage just like I can do for locally stored files 

## Describe the solution you'd like
I would like to be able to install a nuget package which enables me to connect to files stored in Azure. The file provider is registered during setup/start up and is available via dependency injection. The file providers to be supported are: 
- Azure.Storage.Files.DataLake
- Azure.Storage.Files.Shares
- Azure.Storage.Blobs

## Additional context
Not sure if issue should be here or under azure

**Comment by huoyaoyuan** [comment]
.NET BCL doesn't provide support for any particular service. The request should be submitted to azure SDK.

**Comment by davidfowl** [comment]
This is a fine request for the azure sdk (where the other azure providers live)

**Comment by thompson-tomo** [comment]
Ok, have recreated Issue As: https://github.com/Azure/azure-sdk-for-net/issues/40884 and will close this one.
