### ISSUE TITLE
Cast to nullable integer surprisingly fails on non-integers

### ISSUE THREAD

**Issue by ploeh** [dotnet/runtime#96314]
### Description

`JsonNode` allows various casts, among others to `int?` (`Nullable<int>`). One would expect that such a cast would return a 'populated' value when the `JsonNode` contains something that represents an integer, and `null` otherwise.

### Reproduction Steps

Create an xUnit.net test library. Add these three test methods in a test class:

```csharp
[Fact]
public void ParseInt()
{
    var json = """{"i":42}""";
    var j = System.Text.Json.Nodes.JsonNode.Parse(json);

    var i = (int?)j?["i"];

    Assert.Equal(42, i);
}

[Fact]
public void ParseDecimal()
{
    var json = """{"i":4.2}""";
    var j = System.Text.Json.Nodes.JsonNode.Parse(json);

    var i = (int?)j?["i"];

    Assert.Null(i);
}

[Fact]
public void ParseString()
{
    var json = """{"i":"foo"}""";
    var j = System.Text.Json.Nodes.JsonNode.Parse(json);

    var i = (int?)j?["i"];

    Assert.Null(i);
}
```

### Expected behavior

All three tests should pass.

### Actual behavior

The `ParseInt` test passes, but the two other tests fail.

```
$ dotnet test
  Determining projects to restore...
  All projects are up-to-date for restore.
  IntParse -> [redacted]\IntParse\bin\Debug\net8.0\IntParse.dll
Test run for [redacted]\IntParse\bin\Debug\net8.0\IntParse.dll (.NETCoreApp,Version=v8.0)
Microsoft (R) Test Execution Command Line Tool Version 17.8.0 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:00.56]     IntParse.Repro.ParseString [FAIL]
[xUnit.net 00:00:00.57]     IntParse.Repro.ParseDecimal [FAIL]
  Failed IntParse.Repro.ParseString [4 ms]
  Error Message:
   System.InvalidOperationException : An element of type 'String' cannot be converted to a 'System.Int32'.
  Stack Trace:
     at System.Text.Json.Nodes.JsonValue`1.ConvertJsonElement[TypeToConvert]()
   at System.Text.Json.Nodes.JsonValue`1.GetValue[T]()
   at System.Text.Json.Nodes.JsonNode.op_Explicit(JsonNode value)
   at IntParse.Repro.ParseString() in [redacted]\IntParse\Repro.cs:line 33
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
  Failed IntParse.Repro.ParseDecimal [< 1 ms]
  Error Message:
   System.FormatException : One of the identified items was in an invalid format.
  Stack Trace:
     at System.Text.Json.ThrowHelper.ThrowFormatException()
   at System.Text.Json.JsonElement.GetInt32()
   at System.Text.Json.Nodes.JsonValue`1.ConvertJsonElement[TypeToConvert]()
   at System.Text.Json.Nodes.JsonValue`1.GetValue[T]()
   at System.Text.Json.Nodes.JsonNode.op_Explicit(JsonNode value)
   at IntParse.Repro.ParseDecimal() in [redacted]\IntParse\Repro.cs:line 22
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)

Failed!  - Failed:     2, Passed:     1, Skipped:     0, Total:     3, Duration: 7 ms - IntParse.dll (net8.0)
```

### Known Workarounds

One may write a helper function like the following, but it really should be part of the reusable library.

```csharp
private static int? TryInt(this JsonNode? node)
{
    if (node is null)
        return null;
        
    if (node.GetValueKind() != JsonValueKind.Number)
        return null;

    try
    {
        return (int)node;
    }
    catch (FormatException)
    {
        return null;
    }
}
```

### Configuration

- .NET 8
- Windows 11 x64

### Other information

I was looking for a safe way to extract specific values (e.g. integers) from a JSON DOM. I couldn't find a `TryInt` method or similar, but I did find explicit casts to e.g. `int?`.

In Functional Programming, it's very common to use 'option-valued' return types (`option` in F#, `Maybe` in Haskell) for 'parse-like' operations such as trying to convert a string to a number, etc. Thus, I expected that casting `JsonNode` to `int?` would work in the same way.

Instead, it (quite surprisingly) throws an exception if the cast isn't possible.

This is surprising, since such a cast should always be possible. Specifically, the function should return `null` when the value is _not_ convertible to an integer. That would make the cast a total function. Right now, it's a [partial function](https://en.wikipedia.org/wiki/Partial_function).

It may be argued that changing this behaviour is a breaking change, but I don't see how: By _not_ throwing exceptions, you'd be [strengthening postconditions](https://blog.ploeh.dk/2021/12/13/backwards-compatibility-as-a-profunctor). Any existing code that 'relies' on those exceptions being thrown will still work, although the `catch` block will never be executed.

Casts to non-nullable values should remain as they currently are. Only casts to nullable values should change behaviour.

**Comment by gregsdennis** [comment]
I think this is expected behavior.

If you need the number extraction method, check out my _Json.More.Net_ library.  It has [`.GetInteger()`](https://docs.json-everything.net/api/Json.More/JsonNodeExtensions/#getintegerthis-jsonvalue-value) and [`.GetNumber()`](https://docs.json-everything.net/api/Json.More/JsonNodeExtensions/#getnumberthis-jsonvalue-value) extensions.

**Comment by ploeh** [comment]
> I think this is expected behavior.

Clearly, then, _"expected"_ is subjective, because I find it quite unexpected, for the reasons outlined above.

**Comment by huoyaoyuan** [comment]
The behavior aligns with casting objects. Casting `object` to `int?` only allows null and boxed int, and throws for other types. You are requiring an operatio similar to the `as` operator.

**Comment by elgonzo** [comment]
Well, i would find returning null in this case instead of throwing not only unexpected behavior, but actually incorrect behavior, since returning null would suggest the json data containing a null value for the property _i_ , e.g. `{"i": null}` and not suggest that a value conversion failed. The behavior you wish for would introduce ambiguity and and i find it for that reason alone an undesirable behavior.

In my opinion, a better solution/fix for your problem would be a `JsonNode.TryGetValue<T>` method, a solution you have already identified yourself in your remarks. And which already exists: It is implemented in the JsonValue class: https://learn.microsoft.com/en-us/dotnet/api/system.text.json.nodes.jsonvalue.trygetvalue


	if ((j as System.Text.Json.Nodes.JsonValue)?.TryGetValue(out int? i) == true)
		Console.WriteLine($"i = {i}");
	else
		Console.WriteLine("i is not an integer");


As a side note, the current documentation for JsonNode's explicit conversion operators (https://learn.microsoft.com/en-us/dotnet/api/system.text.json.nodes.jsonnode.op_explicit) doesn't mention anything about exceptions. While i believe this to be a flaw in the documentation and not an indication of the intended behavior (because the aforementioned ambiguity problem), it's up to the dotnet and documentation folks to sort this out...

**Comment by gregsdennis** [comment]
> > I think this is expected behavior.

> Clearly, then, "expected" is subjective, because I find it quite unexpected, for the reasons outlined above.

Allow me to clarify: this is _intended_ behavior.  As such, the .Net team expects it.

**Comment by eiriktsarpalis** [comment]
> It may be argued that changing this behaviour is a breaking change, but I don't see how: By not throwing exceptions, you'd be strengthening postconditions. Any existing code that 'relies' on those exceptions being thrown will still work, although the catch block will never be executed.

This assumes that the catch block treats the result as being `null`, but we cannot make that assumption in the general case. For example, the following method returns a different result depending on the chosen semantics for casting:
```C#
Console.WriteLine(Test(4.2));

static int? Test(object? value)
{
    try
    {
        return (int?)value;
    }
    catch (InvalidCastException)
    {
        return 0;
    }
}
```
In other words, the two semantics aren't observationally equivalent.

As pointed out by others in this thread, the `as` keyword should serve to provide the desired behavior (or similarly the `TryGetValue` method for the case of `JsonValue` instances).
