### ISSUE TITLE
Property getter not getting inlined

### ISSUE THREAD

**Issue by Barsonax** [dotnet/runtime#9632]
I ran into a performance issue when I used a property for the HCost + GCost field [here](https://github.com/Barsonax/Pathfindax/blob/5af5686de82a6307bb54ffdfd3d4343c32e38d92/Source/Code/Pathfindax/Nodes/AstarNode.cs#L43). One would expect these to be inlined as this makes a big difference in performance in my case and the body is really small.

Without the property the perf numbers are this (benchmarks can be run using [this](https://github.com/Barsonax/Pathfindax/blob/5af5686de82a6307bb54ffdfd3d4343c32e38d92/Source/Code/Pathfindax.Benchmarks/Program.cs)):
![image](https://user-images.githubusercontent.com/19387223/35611662-0eb0e9b0-0666-11e8-8be5-424e82bad5a3.png)

But if I replace the HCost + GCost code with a FCost property that returns HCost + GCost I get this:
![image](https://user-images.githubusercontent.com/19387223/35611471-66ae47c6-0665-11e8-9fb0-8624f4e2cde3.png)

Then I decided to look at the generated assembly and noticed that for the [Sortup](https://github.com/Barsonax/Pathfindax/blob/5af5686de82a6307bb54ffdfd3d4343c32e38d92/Source/Code/Pathfindax/Collections/IndexMaxHeap.cs#L155) method (which plays a crucial role in the perf of the pathfinding) that without the property there are 2 call instructions and with the FCost property there are 4 call instructions (the 2 extra calls here are the calls to the FCost property I believe). It also seems that due to inlining further optimizations are possible which could explain the huge difference in benchmark times as I don't think method call overhead alone is responsible for this.

It seems that the compiler inlines everything except the properties for some reason. Manually making a getter method and adding [MethodImpl(MethodImplOptions.AggressiveInlining)] did not make a difference here. Why is the compiler skipping this optimization when it makes so much of a difference here?

Since iam not that good with assembly code (read: I have zero experience) you can find the generated assembly here:
- [WithoutProperty](https://gist.github.com/Barsonax/882c3e1031d4e866e4393529e15b7971)
- [WithProperty](https://gist.github.com/Barsonax/8056a9a4bdbad747528b53651788b0b2)

category:cq
theme:inlining
skill-level:expert
cost:small

**Comment by AndyAyersMS** [comment]
Suspect with dynamic PGO this is no longer an issue. I am going to close this.

@Barsonax looks like the repo you linked above has been quiet recently; is there some successor repo we could look at?

**Comment by Barsonax** [comment]
Nope, it's been a while since that repo was active and there's no successor.

Good that this is now fixed though.
