### ISSUE TITLE
[iOS][non-icu] HybridGlobalization rafactor condition checks / clean up the code

### ISSUE THREAD

**Issue by mkhamoyan** [dotnet/runtime#96328]
- [x]  Define APPLE_HYBRID_GLOBALIZATION symbol for the 3 OSes and use it throughout the implementation instead of defined(TARGET_MACCATALYST) || defined(TARGET_IOS) || defined(TARGET_TVOS) conditions in all files under `https://github.com/dotnet/runtime/tree/main/src/native/libs/System.Globalization.Native`
- [x] `HybridGlobalization` is supported only on iOS/tvOS/macCatalyst not OSX. Rename `IsHybridGlobalizationOnOSX` / `IsNotHybridGlobalizationOnOSX` to `IsHybridGlobalizationOnApplePlatform ` / `IsNotHybridGlobalizationOnApplePlatform ` https://github.com/dotnet/runtime/blob/main/src/libraries/Common/tests/TestUtilities/System/PlatformDetection.cs#L384.
- [x] Remove `IsIcuGlobalizationAndNotHybrid`  property 
- [x] ~Check if possible to include `"pal_utilities.h"` in `pal_placeholders.h` instead of defining asserts, look discussion https://github.com/dotnet/runtime/pull/96684#discussion_r1447523970~
 we shouldn't mix our configs with pal_config.h.in, so we will keep the way it was implemented.

Contributes to https://github.com/dotnet/runtime/issues/80689

**Comment by jkotas** [comment]
> IsHybridGlobalizationOniOS 

This should be IsHybridGlobalizationOnApplePlatform. It returns true on more OSes, not just iOS. The name does not need to encode the fact that the hybrid globalization is not available in macOS currently.
