### ISSUE TITLE
unexpected exception in C# dynamic method invocation with optional struct parameter in .NET48

### ISSUE THREAD

**Issue by TymurGubayev** [dotnet/runtime#96330]
### Description

Invoking a method of a `dynamic` where an optional parameter is `DateTime` (or any struct) causes `System.FormatException: 'Encountered an invalid type for a default value.'` in .NET 4.8.1. It works in .NET8.

### Reproduction Steps

```cs
var h = new Helper();
h.M();

dynamic dyn = new Helper();
dyn.M(); //throws with NET48

public class Helper
{
    public void M(DateTime dt = default)
    {
        Console.WriteLine(dt);
    }
}
```

### Expected behavior

No exception.

### Actual behavior

Throws `System.FormatException: 'Encountered an invalid type for a default value.'`

### Known Workarounds

Use `System.Runtime.InteropServices.OptionalAttribute`:

```cs
        public void M([Optional] DateTime dt)
        {
            Console.WriteLine(dt);
        }
```

### Configuration

.NET 4.8.1
x64
I'm relatively sure it's not specific to this configuration.

**Comment by jkotas** [comment]
This issue was tracked and fixed in .NET Core/.NET 5+ by https://github.com/dotnet/runtime/issues/24574.

There is no plan to port this fix to .NET Framework. .NET Framework receives security and critical fixes only.
