### ISSUE TITLE
"No LC_RPATH's found" when loading native libraries on macOS

### ISSUE THREAD

**Issue by TheSpydog** [dotnet/runtime#96337]
### Description

When using `DllImport` to load a native library on macOS with CoreCLR, if the native library has any dependent dylibs that are referenced via rpath, then the library will fail to load its dependencies, and will ultimately fail to load itself.

### Reproduction Steps

1. Download and unzip [this sample project](https://github.com/dotnet/runtime/files/13781433/rpath_test.zip).
2. In the terminal, enter the project directory and run `dotnet run`. (If prompted, allow the SDL2 and FNA3D dylibs to be executed in System Settings > Privacy and Security.)
3. Notice that the program runs to completion without error.
4. Swap lines 11 and 12 of `Program.cs`, so that the FNA3D function gets called first.
5. `dotnet run`, and notice the error:
```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libFNA3D.0.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.0/libFNA3D.0.dylib, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.0/libFNA3D.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.0/libFNA3D.0.dylib' (no such file), '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.0/libFNA3D.0.dylib' (no such file)
dlopen(/Users/calebcornett/Desktop/csharp/rpath_test/bin/Debug/net8.0/libFNA3D.0.dylib, 0x0001): Library not loaded: @rpath/libSDL2-2.0.0.dylib
  Referenced from: <7107F5A6-F399-3B5C-8F0F-DB28F89E5CD1> /Users/calebcornett/Desktop/csharp/rpath_test/bin/Debug/net8.0/libFNA3D.0.dylib
  Reason: no LC_RPATH's found
```

### Expected behavior

The load order should not matter, since the FNA3D library is supposed to dynamically load SDL2 if needed. This can be verified by checking the output of `otool -l libFNA3D.0.dylib`, which includes:
```
Load command 12
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libSDL2-2.0.0.dylib (offset 24)
   time stamp 2 Wed Dec 31 18:00:02 1969
      current version 2801.2.0
compatibility version 2801.0.0
```

### Actual behavior

The load order does matter, presumably because the executable's `rpath` is not set.

### Known Workarounds

1. Changing the library load order in the C# program, as seen in the sample program.
2. Setting the environment variable: `DYLD_LIBRARY_PATH=bin/Debug/net8.0/`
3. Running the following on the executable binary, every time you build the project:
```
install_name_tool -add_rpath @executable_path/. rpath_test
codesign -s - -f --deep rpath_test
```

### Configuration

.NET 8.0.100
macOS Sonoma 14.0 (ARM64)

### Other information

The executable that is generated in the `bin/Debug/net8.0` directory does not set an `rpath` value by default.  This can be verified by checking for `LC_RPATH` in the `otool -l` output. If it were to set its `rpath` to the executable directory, like in the third workaround, then the issue would be resolved.

**Comment by AaronRobinsonMSFT** [comment]
After discussion in https://github.com/dotnet/runtime/pull/96367, it has been determined this is by-design and not something we think is appropriate to fix.

**Comment by agocke** [comment]
@TheSpydog We decided that changing the default loading behavior in the .NET runtime is too risky. However, the library author does have the capability to fix this, as described in https://github.com/dotnet/runtime/pull/96367#issuecomment-1872602767. It looks like the build of the top level dylib should have set the appropriate rpath when building. If they fix this issue, presumably the problem will be fixed.
