### ISSUE TITLE
Pathological performance degradation with a specific regex using `Regex.Match`

### ISSUE THREAD

**Issue by mklement0** [dotnet/runtime#96340]
### Description

The regex below is undoubtedly poorly constructed, but the resulting runtime behavior is pathological.

On my M1 Mac, the sample code takes about 1 minute(!) to run.

```csharp
using System.Diagnostics;
using System.Text.RegularExpressions;

var body = """
{
  "data": {
    "message": "text"
  }
}
""";

Console.WriteLine("Starting...");

var sw = Stopwatch.StartNew();

var result = Regex.Match(body, @"""data""(.*?|\n)+},");

sw.Stop();

Console.WriteLine("Finished in {0:N2} secs.", sw.Elapsed.TotalSeconds);
```

### Configuration

.NET SDK 8.0.100 on macOS 14.2.1, Windows 11 22H2

### Regression?

No.
.NET 7 performs equally poorly.

### Data

Sample output from the code above:

```none
Starting...
Finished in 58.15 secs.
```

**Comment by stephentoub** [comment]
This is what's referred to as "catastrophic backtracking". Any backtracking-based regex engine is susceptible. If you don't want to improve the pattern, you can specify the RegexOptions.NonBacktracking flag to switch to a non-backtracking engine.

https://devblogs.microsoft.com/dotnet/regular-expression-improvements-in-dotnet-7/#backtracking-and-regexoptions-nonbacktracking
