### ISSUE TITLE
The native aot DLL library for redirecting methods.

### ISSUE THREAD

**Issue by dadavadd** [dotnet/runtime#96345]
Hi. I have a question. In C++, there is a library that allows you to redirect methods to your DLL, which is injected into the process by pointer. The library is called MinHook:

Here is a simple hook of a function that takes in 4 arguments:
![image](https://github.com/dotnet/runtime/assets/111659964/dba79ba7-be20-413f-bc17-2a0d1f8dca5b)

I tried to do the same in Native AOT as a DLL project. I started using MinHook.NET for this task. Here is my code:
![image](https://github.com/dotnet/runtime/assets/111659964/2539a42b-e02d-4c1c-aef5-d8fb042798cb)

Call:
![image](https://github.com/dotnet/runtime/assets/111659964/033cbe6c-aa20-4468-b24b-56fed465f364)

I call this method in DLL_PROCESS_ATTACH, but in the process the method I need is not redirected to my DLL. What should I do? Is there any way to hack a function to redirect to my DLL and call with arguments?

**Comment by jkotas** [comment]
It is not possible to implement DllMain in managed code like your code fragment shows. Managed implementation of DllMain is going to lead to loader deadlocks and crashes. 

From https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-best-practices#general-best-practices: 
```
You should never perform the following tasks from within [DllMain](https://learn.microsoft.com/en-us/windows/win32/dlls/dllmain):
- Use managed code.
```

NativeAOT does not change this equation.

**Comment by jkotas** [comment]
> What should I do? Is there any way to hack a function to redirect to my DLL and call with arguments?

This is a question about MinHook.NET library. The right place to ask these questions is https://github.com/CCob/MinHook.NET.
