### ISSUE TITLE
Deflate returning different results from net40

### ISSUE THREAD

**Issue by MaxHayman** [dotnet/runtime#96343]
### Description

Using deflate and compressing data and then decompressing data returns different results from net40 to net7.0

```
net40
The original string length is 52428800 bytes.
The compressed stream length is 52444795 bytes.
The decompressed string length is 52428800 bytes, same as the original length.


net7.0
The original string length is 52428800 bytes.
The compressed stream length is 52444780 bytes.
The decompressed string length is 8187 bytes, same as the original length.
```

### Reproduction Steps

using the code example from here
https://learn.microsoft.com/en-us/dotnet/api/System.IO.Compression.DeflateStream.Write?view=net-8.0

however instead loading the data from a file instead of a static string

Project with demo code can be seen here
https://github.com/MaxHayman/DeflateTest

50mb test file is from here
http://xcal1.vodafone.co.uk/

### Expected behavior

"decompressed string length" should be the same as "original string length"

### Actual behavior

```
net40
The original string length is 52428800 bytes.
The compressed stream length is 52444795 bytes.
The decompressed string length is 52428800 bytes, same as the original length.


net7.0
The original string length is 52428800 bytes.
The compressed stream length is 52444780 bytes.
The decompressed string length is 8187 bytes, same as the original length.
```

### Regression?

Bug in 

- 7.0
- 8.0

Working in
- 40
- 481

**Comment by stephentoub** [comment]
This is buggy:
https://github.com/MaxHayman/DeflateTest/blob/2437e784a3a0fc1009d6f7ac27a6906d38dec99a/DeflateTest/Program.cs#L51
Stream.Read isn't guaranteed to return as many bytes as was requested. You either need to loop until Read returns 0 or use a helper like ReadAtLeast that does it for you.
