### ISSUE TITLE
Update performance tests to build against netcoreapp

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#9635]
Performance tests are building against .NET Standard 1.4: https://github.com/dotnet/coreclr/blob/master/tests/src/JIT/config/benchmark/benchmark.csproj#L5

This is a problem for testing netcoreapp-specific APIs. We have hit with `MemoryMarshal.CreateSpan` API that was changed to netcoreapp-specific. The test for this API was disable via `#if false` and link to this issue: https://github.com/dotnet/coreclr/pull/16091

category:correctness
theme:testing
skill-level:expert
cost:small

**Comment by AndyAyersMS** [comment]
No longer relevant.
