### ISSUE TITLE
On Linux .NET 6, get unexpected AuthenticationException with HttpWebRequest and wildcard usage

### ISSUE THREAD

**Issue by maurar3** [dotnet/runtime#96360]
### Description

I found this issue running .NET 6.
I see the problem when running on a Linux machine.
But I do not see the problem when I run on Windows.

When using System.Net.HttpWebRequest class,
and running similar code to below, where
Where client request is : buz.example.net
url param is:                    b*z.example.net

Expected these to match. Instead, I got :
System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.

Works fine on Windows.
When url param is:   buz.example.net, it matches and works as expected.

Below is an excerpt from the RFC 6125, which indicates that it should match.

Excerpt from RFC 6125:
https://datatracker.ietf.org/doc/html/rfc6125

6.4.3 Checking of Wildcard Certificates
3.  The client MAY match a presented identifier in which the wildcard
       character is not the only character of the label (e.g.,
       baz*.example.net and *baz.example.net and b*z.example.net would
       be taken to match baz1.example.net and foobaz.example.net and
       buzz.example.net, respectively).  However, the client SHOULD NOT
       attempt to match a presented identifier where the wildcard
       character is embedded within an A-label or U-label [IDNA-DEFS] of
       an internationalized domain name [IDNA-PROTO].

### Reproduction Steps

Example Code:

using System.Net;

string url;

HttpWebRequest request = (HttpWebRequest)WebRequest.Create(url);
request.ServerCertificateValidationCallback = ValidateServerCertificate;

Where client request is : buz.example.net
url param is:             b*z.example.net

### Expected behavior

Expected the same behavior on both Windows and Linux platform, where expectation is that it would conform to RFC 6125,
where client url would match with the specified wildcard in the url string. 

Forour test cases that conform to RFC 6125, there was no need to add additional coding to our custom ValidateServerCertificate callback.

### Actual behavior

It does not match on Linux platform.

### Configuration

.NET 6, Linux, x86-x64
Operating System: Rocky Linux 8.6 (Green Obsidian), don't believe it is applicable to this configuration

**Comment by wfurt** [comment]
That comes from openssl. There was discussion here https://github.com/openssl/openssl/issues/4293 and the community decided not to support it. 

In general .NET depends on platform validation to ensure consistency with other software and in this case that leafs to observed difference.

**Comment by bartonjs** [comment]
While I can't find an explicit rule limiting wildcards to only all or nothing (`*.example.net` vs `b*.example.net` or `*z.example.net`); the CA/Browser Forum's [Baseline Requirements](https://cabforum.org/wp-content/uploads/CA-Browser-Forum-BR-v2.0.1.pdf) defines a "Wildcard certificate" as

> Wildcard Certificate: A Certificate containing at least one Wildcard Domain Name in the Subject
Alternative Names in the Certificate.

and

> Wildcard Domain Name: A string starting with “*.” (U+002A ASTERISK, U+002E FULL STOP)
immediately followed by a Fully‐Qualified Domain Name.

So "b*z.example.org" isn't something that a public CA is allowed to issue a SAN entry for.  If your private PKI is issuing certs with wildcards like that, I recommend you change to match industry standards.

**Comment by rzikm** [comment]
I have trouble grasping what exactly is the problem here. Are you actually connecting to a server with such a certificate? As bartonjs pointed out, the CA should not give out certs containing `b*z.` pattern. And if OpenSSL is rejecting it, then likely no Linux program using OpenSSL can connect to that server without bypassing validation.

**Comment by maurar3** [comment]
I came across an  inconsistency with this testcase on .NET Linux vs Windows.  It is not allowed on Linux, but is accepted on Windows. We are following guidelines from RFC 6125, and it states there that "The client **MAY** match a presented identifier...."

I entered this issue mostly because of the inconsistency. I found this while testing. We do not issue certificates like this.

**Comment by maurar3** [comment]
That is fine. Thanks
