### ISSUE TITLE
VB.NET cannot AOT compile into DLL. I hope to add exported DLL dynamic library and ACTIVEX DLL.

### ISSUE THREAD

**Issue by xiaoyaocode163** [dotnet/runtime#96379]
### Description

VB.NET cannot AOT compile into DLL. I hope to add exported DLL dynamic library and ACTIVEX DLL.
.net class libraries are essentially ACTIVEX DLL and com dll. AOT has lost all these functions, which is so disappointing.
Maybe .NET has a large number of system class libraries and TLB INFO is too complicated.
It is also possible if it can support the creation of a COM DLL that exports the most basic data types, without using .NET reflection.
Just use traditional ITypeInfo, IDispatch, FUNCDESC, vtable, function ptr
Can support parameter types: string, integer, decimal, logic, event triggering, method attributes.
In fact, this is not difficult, it just depends on whether Microsoft wants to implement it.

I asked why VB.NET does not support exported function API, github project: official reply

[ UnamangedCallersOnlyAttribute cannot be used with VB due to the non-CLS compliant constructor]
https://learn.microsoft.com/en-us/dotnet/fundamentals/languages
-----------------------
It is by design that Visual Basic cannot do everything that C# can do. .NET language strategy explains our approach in more detail.
use C# project to expose your API,Yes, this is the right solution.
-----------------------
I assume this is because UnmanagedCallersOnly is not CLS complaint: #40461. VB compiler gives error BC37316: 'UnmanagedCallersOnly' attribute is not supported :(

Bad workaround: manually inject attribute in IL using reflection etc.
Better workaround: use C# project to expose your API with <ProjectReference Include="path\to\your.vbproj" /> in csproj.
-----------------------

TIOBE releases December programming language rankings: C# is expected to become the programming language of the year
https://www.ithome.com/0/738/532.htm

In fact, we do not require VB.NET to have the same number of functions as C#, such as only a small amount of optimization and updates.
VB.NET can only create console programs and ordinary EXEs, and cannot create standard DLL export functions.
.net cannot create activex dll using AOT compilation (nor can it be turned into a .NET class library and called by C# or VB.NET standard projects)
Is this a joke?

.NET's compilation mechanism first compiles high-level languages ??(such as C#, VB) into intermediate language (IL), and then converts the intermediate language (IL) into machine language through CLR (Common Language Runtime)
In this process, it should be possible to add the UnmanagedCallersOnly attribute to VB.NET or export a certain function. It mainly depends on whether Microsoft engineers want to do it or not. It should be possible.

It doesn't matter if the VB.NET syntax is as concise as VB6. In fact, why can't msgbox abc run? It must be converted into msgbox (abc),
Of course, the correct way is Microsoft.VisualBasic.msgbox (abc.tostring())

.NET core is cross-platform, which is the real golden age of .net development. Not every programmer, business developer, and office worker needs to learn and use such complex languages ??as C++ and C#.
As a result, during this critical period, VB.NET was directly abandoned, making PYTHON the world's number one programming language, but its syntax happened to be VISUAL BASIC.
Microsoft cut off its own legs and ceded the market to its competitors. I think of the BASIC compiler that Bill Gates developed for others when he was just in college. It could be completed in 1-3 months.
Isn’t it possible that cross-platform VBA and VBS can’t be built in 3 months? What about 3 years? As a result, it took 30 years to complete. Even after 25 years, IE is not doing well. It is really difficult to use. It should have been given up long ago and directly switched to the Google Chrome kernel.

### Reproduction Steps

VB.NET NEED SOME support

### Expected behavior

It would be great if WEBVIEW2 was launched 10 years earlier. But this thing VB6 and VBA cannot be used, and everything is full of bugs. Is it difficult to directly create a web page object using VBA or vbs?

Like set ie=CreateObject("InternetExplorer.Application").Visible=true
IE.Navigate "http://www.bing.com"
Wouldn't it be very simple if it was changed to webview2? Recruit a new one

### Actual behavior

need export api/tlb info

### Other information

To be honest, the usage of Pascal syntax:= seems very rubbish. Some of its syntax is similar to C#, and some is similar to VB.

procedure TForm1.ProcConst(const Value: string);
begin
OrigNum:=Value+' Me';
lblReturn.Caption:=OrigNum;//为'Hello Me‘
lblOrig.Caption:=Value;//为'Hello Me'
end;

**Comment by xiaoyaocode163** [comment]
In fact, it is very simple to make F# or VB.NET into a new version of VBS. After all, WINDOWS has the automatic compiler FBC.EXE.
I hate powershell. Can it replace PYTHON and become an efficient scripting tool? Absolutely not.
But the system comes with a small 1MB IDE for writing C#, vb.net code, and writing scripts for system settings and work arrangements. Isn't it very convenient?
If necessary, it can be packaged into a ZIP or compiled into an EXE.


I have looked at the development progress of C# in the past few years, and it has been lagging far behind JAVA. It may be that it only has 20-50% of the market of JAVA.
In the past year, its market share and popularity among developers have finally caught up with JAVA. Microsoft's 25 years of hard work has only achieved this.
Of course, C# + vb.net is the real capability. Unfortunately, TIOBE has never used such a correct comparison method, causing Microsoft itself to dislike vb.net syntax.

I remember that in order to ban DELPHI, Microsoft asked them not to use BASIC language to develop IDE. As a result, Microsoft itself completely abandoned the VB family.
VBS will soon be banned from use in WIN11, and VBA will be replaced by PYTHON to perform table formula calculations on the server.

**Comment by xiaoyaocode163** [comment]
A simple look at F#, his grammar is too anti-human, like VB, but it is many times more complex than VB6, on the contrary, VB.NET although a lot of code, but only ordinary grammar can also replace VBS.
Professionals don't code to write fewer words.
JS,PYTHON,java, the mainstream scripting language, simple and easy to understand, really no need to simplify, but ordinary programmers can not understand.
If F# is not developed (spending more dollars and talent) and the life of VB.NET is extended by 20 years, it is a great progress for mankind, but it is a pity that VB.net was terminated while Bill Gates was still alive.

**Comment by jkotas** [comment]
Please stay focused on your scenario when opening issues like this one, and avoid commenting on unrelated concerns. This issue is not actionable.

> .net class libraries are essentially ACTIVEX DLL

That is not correct. [Active X](https://en.wikipedia.org/wiki/ActiveX) is deprecated technology. We are not going to invest into for VB nor for the other .NET language.
