### ISSUE TITLE
Rust built WASM library in Blazor project fails on wasm-opt when being published

### ISSUE THREAD

**Issue by shakenov-chinga** [dotnet/runtime#96394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi guys,
I've been trying to publish my project with this error. I've searched a lot and tried a bunch of stuff, but none of them worked. Then I stumbled upon the [issue](https://github.com/dotnet/aspnetcore/issues/39825) where [BlazeOrbit](https://github.com/SteveSandersonMS/BlazeOrbital/tree/main/BlazeOrbital) was recommended to verified the issue. The same error occurs on that project too.

![image](https://github.com/dotnet/aspnetcore/assets/12277921/f584a753-82ab-4e59-a7f5-325c25b06bf6)
I get this error:
[error.log](https://github.com/dotnet/aspnetcore/files/13781945/error.log)

### Expected Behavior

It should have published the project

### Steps To Reproduce

My steps are:

1. Run command in PowerShell `BlazeOrbital\rustqr> cargo build --target wasm32-unknown-emscripten`
2. In BlazeOrbital\rustqr\Cargo.toml change from `crate-type = ["staticlib"]` to `crate-type = ["dylib"]` (I need dll for BlazeOrbital.Accounting)
3. Run command `BlazeOrbital\rustqr> cargo build --target x86_64-pc-windows-msvc`
4. Build solution in Visual Studio 2022
5. Press "Publish" on BlazeOrbital.ManufacturingHub project
6. Select folder profile with default values
7. Press "Publish"

### .NET Version

6.0

**Comment by maraf** [comment]
No worries, the issue won't get closed without resolution. Sorry I didn't get to it earlier. I'm going to investigate it now

**Comment by shakenov-chinga** [comment]
I had problems with .NET 8 before I found and reproduced it on BlazeOrbit. I haven't tried BlazeOrbit using .NET 8.

**Comment by maraf** [comment]
Publishing BlazeOrbit from VS worked on my machine. Can you please publish it using command line `dotnet publish -c Release -bl` and share the binlogu?

**Comment by shakenov-chinga** [comment]
Binlog file: [msbuild.binlog.zip](https://github.com/dotnet/runtime/files/14028096/msbuild.binlog.zip). 
The actual error in cmd:
```
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\6.0.25\Sdk\WasmApp.Native.targets(386,5): error MSB3073: The command "wasm-opt.exe --strip-dwarf "C:\Users\user_0\source\repos\BlazeOrbital\ManufacturingHub\obj\Release\net6.0\wasm\for-publish\dotnet.wasm" -o "C:\Users\user_0\source\repos\BlazeOrbital\ManufacturingHub\obj\Release\net6.0\wasm\for-publish\dotnet.wasm"" exited with code 1. [C:\Users\user_0\source\repos\BlazeOrbital\ManufacturingHub\BlazeOrbital.ManufacturingHub.csproj]
```

**Comment by maraf** [comment]
The .NET 6 demo doesn't work because incompatiblity between cargo and wasm-opt that is shipped in wasm-tools-net6 workload. For more info see
- https://github.com/rust-lang/rust/issues/109807
- https://github.com/bytecodealliance/cargo-wasi/issues/137
- https://github.com/Shopify/function-examples/issues/255

After upgrading the demo to .NET 8 publish passed successfully.

What problems are you facing with .NET 8? Can you share more details or simple repro?

**Comment by shakenov-chinga** [comment]
Hi, thank you very much!

Turns out I gave you wrong info about using .NET 8. I used .NET 8 for every project except for blazor project itself, because it gave me weird error like this:
`DISABLE_EXCEPTION_THROWING was set (likely due to -fno-exceptions), which means no C++ exception throwing support code is linked in, but exception catching code appears. Either do not set DISABLE_EXCEPTION_THROWING (if you do want exception throwing) or compile all source files with -fno-except (so that no exceptions support code is required); also make sure DISABLE_EXCEPTION_CATCHING is set to the right value - if you want exceptions, it should be off, and vice versa.`
The whole build output: [build_error.log](https://github.com/dotnet/runtime/files/14069043/build_error.log).

I wasn't able to find any information about this error anywhere, and I wanted to finish testing things on Blazor and WASM on new year's day offs. So, I just switched the Blazor project to .NET 7, which gave the same error in my very first comment.

Could you, please, provide me some info on how deal with this error, if you have any, so that I would be able to confirm that project publishes without any issues on .NET 8.

Also, I wasn't able to look though the links above. I plan to do it on this weekends.

Thanks! )

**Comment by maraf** [comment]
IIRC disabling WASM EH did the trick `<WasmEnableExceptionHandling>false</WasmEnableExceptionHandling>`. 
A better solution would be to instruct rust to the opposite, but I'm not familier with the tooling.

**Comment by lewing** [comment]
> Hi, thank you very much!
> 
> Turns out I gave you wrong info about using .NET 8. I used .NET 8 for every project except for blazor project itself, because it gave me weird error like this: `DISABLE_EXCEPTION_THROWING was set (likely due to -fno-exceptions), which means no C++ exception throwing support code is linked in, but exception catching code appears. Either do not set DISABLE_EXCEPTION_THROWING (if you do want exception throwing) or compile all source files with -fno-except (so that no exceptions support code is required); also make sure DISABLE_EXCEPTION_CATCHING is set to the right value - if you want exceptions, it should be off, and vice versa.` The whole build output: [build_error.log](https://github.com/dotnet/runtime/files/14069043/build_error.log).
> 
> I wasn't able to find any information about this error anywhere, and I wanted to finish testing things on Blazor and WASM on new year's day offs. So, I just switched the Blazor project to .NET 7, which gave the same error in my very first comment.
> 
> Could you, please, provide me some info on how deal with this error, if you have any, so that I would be able to confirm that project publishes without any issues on .NET 8.
> 
> Also, I wasn't able to look though the links above. I plan to do it on this weekends.
> 
> Thanks! )

I see the build is using sqlite are you building it yourself or using existing packages?

**Comment by shakenov-chinga** [comment]
Hi @maraf,
Thanks you very much. I apologize for the long answer. I was able to compile, publish and run my project on .net8 using `<WasmEnableExceptionHandling>false</WasmEnableExceptionHandling>` property.

Hi @lewing,
For .net8 I didn't use pre-build `e_sqlite3.o`, I've found somewhere that I should reference `<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.1" />` instead.

**Comment by lewing** [comment]
It appears at first glance that the problem you were seeing is because of a c++ native library that was built with different ABI settings than the runtime.  Are you referencing any other native libraries?

**Comment by shakenov-chinga** [comment]
@lewing, except for rustqr? No. I didn't make any changes in BlazeOrbital sqlite package reference and nuget packages update.

**Comment by lewing** [comment]
@SteveSandersonMS you are up ;)

**Comment by SteveSandersonMS** [comment]
@lewing Can you clarify - are you asking me a question? From reading the thread above it seems like @maraf was able to debug what's going on and tracked it down to some version incompatibilities.

**Comment by maraf** [comment]
I'm going to close this issue now as I believe the problem lies with rust tooling configuration. In my previous comment there are hints I was about to found, but I'm not expert there. Whether to maintain BlazorOrbital sample up to date with every .NET release is more of a question for that repo.

Feel free to reopen the issue if you see problem on .NET runtime side.
