### ISSUE TITLE
Opt-out switch for disabled OCSP Stapling by default

### ISSUE THREAD

**Issue by rzikm** [dotnet/runtime#96395]
https://github.com/dotnet/runtime/pull/83013 disabled OCSP fetch by default for certificates provided via `SslServerAuthenticationOptions.ServerCertificate` property. This was an undocumented behavior breaking change between .NET 7 and .NET 8. We should make sure this is documented.

It would be good to provide an AppContext switch to bring out the old behavior in case the change breaks users (such as in https://github.com/dotnet/runtime/issues/95567#issuecomment-1862174997).

**Comment by antonfirsov** [comment]
> We should make sure this is documented.

Is there a tracking issue for the doc addition?
