### ISSUE TITLE
Official test runs should use crossgened bits 

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#964]
Right now we do not test crossgen'ed bits in the Corefx official test runs. This is because the product is not crossgen'ed until the code reaches core-setup. This means we are not testing what the customer actually uses and are implicitly relying on higher level repos to do this testing.

It should be possible to crossgen in CoreFX official builds purely for the purpose of tests (we would throw the images away after). 

cc @ViktorHofer @jkotas

**Comment by ViktorHofer** [comment]
Closing in favor of https://github.com/dotnet/runtime/issues/487
