### ISSUE TITLE
[API Proposal]: Expose `JsonObject` constructor that accepts a known-length `IReadOnlyCollection` to avoid unnecessary array resize operations

### ISSUE THREAD

**Issue by olo-ntaylor** [dotnet/runtime#96417]
### Background and motivation

[Note: this is similar to [this issue](https://github.com/dotnet/runtime/issues/91467), but that issue is for _de-_ serialization. This one is for serialization.]

**Bottom Line:** Being able to specify the capacity of `JsonPropertyDictionary` up-front would improve performance by avoiding unnecessary `Resize` calls (and resultant allocations).

**Context:** We have some high-volume serialization logic that directly encodes tuples of `(string, JsonNode)` into a `JsonNode` via the `.Add` method on the `JsonObject` type.

Because of the way that `JsonObject.IDictionary` works, its [initialization method](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/src/System/Text/Json/Nodes/JsonObject.IDictionary.cs#L196) never calls the [constructor](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/src/System/Text/Json/JsonPropertyDictionary.cs#L29) of `JsonPropertyDictionary` that takes in a `capacity` parameter. The rub there (for our use case) is that we end up with tons of wasted `Resize` calls--because the `new List` constructor ([internal ](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/src/System/Text/Json/JsonPropertyDictionary.cs#L32)to `JsonPropertyDictionary`) starts as an empty array, then instantiates with a default capacity of 4, then will follow the usual double, double, double... resize pattern as-needed.  

This is wasted effort for our use case because we know up-front the number of tuples we are putting in the `JsonObject` (and it is almost always more than 4), but we have no way to "tell" the `JsonPropertyDictionary` to just start with the correct capacity to begin with. Multiply that by many thousands of API requests per minute and we quickly hit a memory allocation wall.

### API Proposal

```csharp
// in JsonObject.cs
namespace System.Text.Json.Nodes;

public sealed partial class JsonObject : JsonNode
{
    private readonly int? _initialCapacity = null;

    // update the existing public constructor that takes an `IEnumerable` to check whether it is an `ICollection`
    public JsonObject(IEnumerable<KeyValuePair<string, JsonNode?>> properties, JsonNodeOptions? options = null) : this(options)
    {
        if (properties is ICollection<KeyValuePair<string, JsonNode?>> propertiesCollection)
        {
            _initialCapacity = properties.Count;
        }

        foreach (KeyValuePair<string, JsonNode?> node in properties)
        {
            Add(node.Key, node.Value);
        }
    };
}
```

```csharp
// in JsonObject.IDictionary.cs

namespace System.Text.Json.Nodes;

public partial class JsonObject : IDictionary<string, JsonNode?>
{
    // update internals of `InitializeDictionary` to...
    private JsonPropertyDictionary<JsonNode?> InitializeDictionary()
    {
        // ... existing
        if (dictionary is null) {
            // ... existing
            dictionary = _initialCapacity.HasValue
                ? new JsonPropertyDictionary<JsonNode?>(caseInsensitive, _initialCapacity.Value) // NEW: use capacity argument if available
                : new JsonPropertyDictionary<JsonNode?>(caseInsensitive);
            // ... existing
        }
    }
}
```

### API Usage

For our specific use-case, it might look like this (in F#)

```fsharp
    /// Encode an object using a list of property names and encoded values.
    let object (values: (string * JsonNode) list) : JsonNode =
        let values = values |> List.map (fun (k, v) -> KeyValuePair(k, v))        
        JsonObject(values) // F# list implements IReadonlyCollection, so this would use the new, known-capacity constructor
```

But, frankly, the usage change _should_ be transparent to consumers. Any time a `JsonObject` is manually constructed with a known-length collection, it should know to use the known-capacity constructor.

### Alternative Designs

An alternative approach may be to alter the `JsonNodeOptions` to include some kind of object capacity value (but that feels clunkier/less transparent). 

### Risks

Unknown.

**Comment by olo-ntaylor** [comment]
Not sure where to add, but I am happy to help however I can with these changes if/when they make sense 😄

**Comment by to11mtm** [comment]
Would it make more sense to just have better behavior in the existing constructor?

e.x.

```
        public JsonObject(IEnumerable<KeyValuePair<string, JsonNode?>> properties, JsonNodeOptions? options = null) : this(options)
        {
            if(properties is IReadOnlyCollection<KeyValuePair<string, JsonNode?>> c)
            {
                SetInitialCapacity(c.Capacity);
            }
            foreach (KeyValuePair<string, JsonNode?> node in properties)
            {
                Add(node.Key, node.Value);
            }
        }
```

**Comment by olo-ntaylor** [comment]
@to11mtm that seems perfectly reasonable 👍

**Comment by olo-ntaylor** [comment]
@to11mtm do you think it would be appropriate at this point for me to open up a draft PR sketching out these changes?

**Comment by to11mtm** [comment]
> @to11mtm do you think it would be appropriate at this point for me to open up a draft PR sketching out these changes?

To be clear I mostly lurk here and cannot say for certain :). But I think it's totally worth doing!

I do think to improve the likelihood of a smooth acceptance (based on my experience contributing to other OSS and observing here) you may want to:

 - make sure that we do our best to not add any additional fields/etc and instead use what's there to pre-set the Dictionary's size... Goal should be 'improve performance for overwhelming majority with minimal to no regression for original case'. I think the type-check bypass will easily fall into that category.
 - If there's (an) existing benchmark(s) around this, have before/after numbers.
 - If there aren't benchmarks, or they don't cover enough cases, consider adding them (note: IDK if there is additional process for this in runtime)
   - Make sure to add them -before- your changes so that you can provide before/after numbers
   - Make sure to measure both the optimized path and the unoptimized path

**Comment by olo-ntaylor** [comment]
@to11mtm thanks so much for your guidance here.

I've opened a draft PR sketching out the minimal changes. It's very small 😄. I'd appreciate it if you could take a quick glance at it and make sure it's aligned with the direction you suggested. If it is, I will move forward with getting my head around the tests/benchmarks stuff that you mentioned. (First time in this repo, so bear with me 😅)

Speaking of tests-- I'm not sure how to unit test the behavior without making the `JsonPropertyDictionary` `internal` instead of `private`.  My initial thought was to use a list with a specific length (like 5 or 7) to force a capacity that would never be produced by the "normal" resize pattern of 4 -> 8 -> 16 -> ... But I'm not sure how to access to that `JsonPropertyDictionary` to check the `.Capacity` without changing its visibility. Any help/ideas there would be appreciated! (Of course, I could use reflection in the unit tests to get at the private field, but that feels yucky and I don't see any precedent for it in the existing tests.)

**Comment by eiriktsarpalis** [comment]
I agree with @to11mtm that this should preferably accept `IEnumerable` and have the constructor make the necessary runtime checks. In recent versions of .NET this can be delegated to the `Enumerable.TryGetNonEnumeratedCount` method which covers more collection types as well. @olo-ntaylor would it be possible to update the proposal in the OP so that the new shape is reflected?

A further point is that we might want to consider addressing this problem using collection literals instead. This language feature similarly addresses the resizing issue since it feeds the constructor with a span of all elements, however `JsonObject` is effectively a dictionary type and we currently only have support list literals but not dictionary literals. For this reason I'd be inclined to hold off from this feature until design for dictionary literals has crystalized, after which point we could add support for literals in both the `JsonArray` and `JsonObject` types.

**Comment by olo-ntaylor** [comment]
@eiriktsarpalis thanks for the feedback!

I will update the PR and my initial comment to go with `Enumerable.TryGetNonEnumeratedCount` 👍 

To clarify on your point about collection literals- are you saying we should hold off on this request altogether to wait for collection literals? Or just wait to use collection literals until they're supported for both arrays and dictionaries?

**Comment by eiriktsarpalis** [comment]
> I will update the PR and my initial comment to go with `Enumerable.TryGetNonEnumeratedCount` 👍

As with any API proposal, this will need to go through [review](https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md) where it may or may not get approved, or it may get approved with substantial alterations. As such, I would recommend holding off from creating a pull request.

> To clarify on your point about collection literals- are you saying we should hold off on this request altogether to wait for collection literals? Or just wait to use collection literals until they're supported for both arrays and dictionaries?

I'm saying we should hold off from doing anything on this space until we have a clear design for dictionary literals.

> EDIT: actually I'm not sure if it's possible to use TryGetNonEnumeratedCount, since, if I understand correctly, STJ still has netstandard 2.0 and net462 as targets. I could use compiler directives, I suppose, but that might result in potentially surprising behaviors between different build targets. Did you have something in mind to achieve this?

Yes, that would require a polyfilled implementation (assuming we went down the constructor route).

**Comment by eiriktsarpalis** [comment]
I actually missed the fact that an IEnumerable constructor has already been exposed, so no API review is necessary and we're not blocked on future collection literal development it seems.

You can just go ahead and continue work on your PR, my recommendation is to use `TryGetNonEnumeratedCount` for targets that have it, and implement a simpler implementation for those that don't have it, roughly:
```C#
#if NETCOREAPP
if (source.TryGetNonEnumeratedCount(out int count)
#else
if (source is ICollection<..> or IReadOnlyCollection<..>)
#endif
```
