### ISSUE TITLE
Unexpected result from evaluated method

### ISSUE THREAD

**Issue by maciejaszyk** [dotnet/runtime#96416]
### Description

We noticed one of our tests is occasionally failing. After some investigation, we found one of our function (which is basically comparing double values) returns wrong value when called from other function. It's worth to mentioning that it's doesn't always return the wrong value, but it requires 100s/1000s of iteration of test (which typically passes without any issues). 

![image](https://github.com/dotnet/runtime/assets/86351904/447595fc-178e-42c1-b2d7-b5641e9de2e6)
The first two conditions are true. When we enter the IsEqual method and evaluate the expressions, it returns true:
![image](https://github.com/dotnet/runtime/assets/86351904/d3eb65ca-dbb3-4151-adfc-90b00e984f5a)
However, in the caller, the entire expression is false because it somehow receives false as the result:
![image](https://github.com/dotnet/runtime/assets/86351904/f0cf63a5-5f1d-402e-8c1b-bb25e4bfa6c6)

I recorded video to demonstrate the issue in debugging mode:
https://drive.google.com/file/d/10EDKKgUOsZOUZF5EGHJhAOP8-Esfdb8m/view

### Reproduction Steps

Branch: https://github.com/maciejaszyk/ravendb/tree/IsEqualRepro

Since reproduction is not deterministic, here's the way I reproduce the issue:
We spotted this failing on `x64/x86` but I've only managed to reproduce it on `x86`.

1. Run the Tryouts project in x86/Debug mode (I've used ` dotnet build -c Debug -r  win-x86 ;  dotnet run -c Debug -r  win-x86` )
2. When the issue occurs, the background of terminal will change color to red. After that attach to the process and put breakpoint here:
https://github.com/maciejaszyk/ravendb/blob/d838595cefa7e4716d567c79e431dacf42be7498/src/Raven.Server/Documents/Indexes/Persistence/Corax/CoraxIndexReadOperation.cs#L673-L681

3. Put a breakpoint at line 72: https://github.com/maciejaszyk/ravendb/blob/d838595cefa7e4716d567c79e431dacf42be7498/src/Corax/Querying/Matches/TermProviders/TermProvider.NumericRange.cs#L74-L83

4. The problem happens during query-creation time so run ` queryMatch = CoraxQueryBuilder.BuildQuery(builderParameters, out orderByFields)` in intermediate window and it should move your cursor into breakpoint in `TermProvider.NumericRange`

Please note that there can be other exceptions (test failures) in the meantime, but most of them are due to memory limits on the x86 platform. Also, when test get stuck, please rerun.

### Expected behavior

Function should return true.

### Actual behavior

Returns false

### Regression?

We spotted this bug on .NET7 too, we have migrated to .NET8 and the problem still occurs.

### Known Workarounds

In original code we used switch with `when ()` syntax. We rewrote the conditional into `if-statments` tree but problem still exists.

### Configuration

.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.6c33ef20

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\8.0.100\

.NET workloads installed:
 Workload version: 8.0.100-manifests.6c33ef20
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: x86
  Commit:       5535e31a71

.NET SDKs installed:
  6.0.417 [C:\Program Files (x86)\dotnet\sdk]
  7.0.203 [C:\Program Files (x86)\dotnet\sdk]
  8.0.100 [C:\Program Files (x86)\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.26 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.30 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.25 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.26 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.30 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.26 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.30 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x64   [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation]

**Comment by JulieLeeMSFT** [comment]
@EgorBo, PTAL.

**Comment by maciejaszyk** [comment]
Hi @EgorBo, any news about the issue?

**Comment by EgorBo** [comment]
@maciejaszyk um.. according to video the bug repros in JetBrains Rider which has it's own debugger? Does it repro in VS too? If not then it should be filed against Rider I guess...

**Comment by maciejaszyk** [comment]
@EgorBo it's repro on Visual Studio too.

**Comment by arekpalinski** [comment]
@EgorBo This issue is occasionally affecting our tests which aren't run with the debugger. @maciejaszyk just managed to find a way to catch and investigate that with the debugger attached.

**Comment by EgorBo** [comment]
I've tried to follow the repro steps but it quickly fails with:
```
Starting to run 500505
Raven.Client.Exceptions.RavenException: System.InvalidOperationException: Index 3539 was successfully committed, but the apply failed.
 ---> Raven.Client.Exceptions.Database.DatabaseLoadFailureException: Failed to start database CreateDatabase_1007
```

**Comment by maciejaszyk** [comment]
Does it terminate the process? I've seen similar errors on my end, but after some time, the whole system becomes stable and starts testing normally (then the error occurs).

**Comment by EgorBo** [comment]
Can you dump `double` values which are passed to that function? via `BitConverter.DoubleToUInt64Bits`

**Comment by tannergooding** [comment]
It’s worth noting your code is probably not doing what you think it’s doing.

`double.Epsilon` is the smallest non-zero value and so the only thing that reports true for `Math.Abs(x) < double.Epsilon` is zero. That is, you’re basically doing a very expensive `x == y` check, just one that also fails for Infinity (since inf - inf is nan)

On that note are you p/invoking into any native libraries that modify the floating-point control word? Potentially something that modifies how subnormal values are handled?

**Comment by maciejaszyk** [comment]
From numeric range (retrieved in immediate window with `BitConverter.DoubleToUInt64Bits(((DoubleLookupKey)(object)key).Value)` )
`key` : 4611686018427387904
`_low`: 4611686018427387904

From `IsEqual` function:
```
BitConverter.DoubleToUInt64Bits(Value)
4611686018427387904
BitConverter.DoubleToUInt64Bits(o.Value)
4611686018427387904
```

**Comment by maciejaszyk** [comment]
@tannergooding We're P/invoking a lot in our code, but if our code somehow changed the floating-point word, that would mean this behavior would reproduce every time after the first occurrence, right? The problem with this is when we got this behavior on one thread, the rest works just normally. Also from post above it looks like those represent same number.

**Comment by arekpalinski** [comment]
@EgorBo any update on this? Is there anything that we can provide from our side to help you here?

**Comment by EgorBo** [comment]
> @tannergooding We're P/invoking a lot in our code, but if our code somehow changed the floating-point word, that would mean this behavior would reproduce every time after the first occurrence, right? The problem with this is when we got this behavior on one thread, the rest works just normally. Also from post above it looks like those represent same number.

The repro project is too big to easily track it

> @EgorBo any update on this? Is there anything that we can provide from our side to help you here?

Does it still repro if you change double.Epsilon to a more realistic threshold? As Tanner noted, `math.abs(val1 - val2) < epsilon` is not a correct way to compare doubles

**Comment by tannergooding** [comment]
> We're P/invoking a lot in our code, but if our code somehow changed the floating-point word, that would mean this behavior would reproduce every time after the first occurrence, right? The problem with this is when we got this behavior on one thread, the rest works just normally. Also from post above it looks like those represent same number.

It depends on a number of factors including processor core or software thread, save and restore state accounting for the fpcw (which .NET might not do), etc.

If you have a semi-reliable repro you might try to add an assert like the following (to prevent JIT optimizations/constant folding):
```csharp
[MethodImpl(MethodImplOptions.NoInlining)]
static bool AreBitwiseEqual(double value, ulong bits)
{
    return BitConverter.DoubleToUInt64Bits(value) == bits;
}
```

and then simply `Debug.Assert(AreBitwiseEqual(double.Epsilon, 1))`.

Given that your double is bitwise `4611686018427387904` (which is `2.0`), the only way this could really fail is if `epsilon` is somehow getting treated as `0` via `denormals as zero`, in which case `0 < 0` is `false`.

It's possible there is some weird JIT bug as well, but this is the first failure reported like this so it doesn't appear to be more widespread. If you could get the JIT disassembly for the method in question (`set DOTNET_JitDisasm="MethodName"`) that might also help shed some light as to what's going on.

**Comment by maciejaszyk** [comment]
I've changed the way we compare doubles in codepaths, and it doesn't reproduce now.
Thanks for your help.
