### ISSUE TITLE
Cleanup handling of SIMD instructions in the emitter

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#9641]
Today, the emitter special cases the handling of many SIMD instructions or their special encoding requirements (such as the VEX encoding, which takes 3 operands, or the 4-byte AVX/SSE4.1 encodings).

The hardware intrinsics feature has added direct support for handling many of these same scenarios with dedicated code paths.

It may be beneficial to do a cleanup of this code, in general, and remove the special handling in favor of calling the explicit code paths.

This would likely result in fewer unnecessary checks/handling and provide more maintainable/understandable code.

category:implementation
theme:emitter
skill-level:intermediate
cost:medium
impact:medium

**Comment by BruceForstall** [comment]
@tannergooding Has this been done already? If not, can you add some more details?

**Comment by tannergooding** [comment]
I think most of this has been done/cleaned up now and we are going through the `emitIns_SIMD_*` paths even for regular binary ops today.
