### ISSUE TITLE
Calling `MoveNext` on a readonly `List<int>.Enumerator` field does nothing

### ISSUE THREAD

**Issue by monomere** [dotnet/runtime#96424]
### Description

I'm not sure if this is a tooling issue (the tooling not reporting this and this being expected behavior) or a runtime issue.

### Reproduction Steps

```csharp
using System.Collections.Generic;
using System;

public class Program {
    private readonly List<int> C = [1, 2, 3, 4];
    private readonly List<int>.Enumerator E;
    
    public Program()
    {
        E = C.GetEnumerator();
        E.MoveNext();
    }
    
    public void Test()
    {
        Console.WriteLine(E.Current); // 1
        E.MoveNext();
        Console.WriteLine(E.Current); // 1 (expected 2)
    }
    
    public static void Main() => new Program().Test();
}
```

[The same code in sharplab.io, but with some useful other things](https://sharplab.io/#v2:EYLgtghglgdgNAFxFANgHwAIAYAEGCMALANwCwAUNnvgHQDCA9iigKYDGCUDMAzjQJJgwAVwQRgrMpQBM+ChQwBmPNOoB2HAG8KOXTgAOAJygA3CAhY5DLCABNuKAJ44AMlB4IAPLAQA+HHQ4ALw4ANr4cDjSkYqRhAC6Uno4APQpBsZmFlY29jBOOIIiYhIsAIKGhhCO3jB+AcFhEVExcYny5MlpGabmlm4etX40AKIwwmAsVQgMhjgjxKnpAO6zANY8OnrdRr3Z1nYOzgNePr6j45PTs/OL3fYsPDAA5Ag4q4ZrW7q7WZYHeQK/DGEym5lmQ38CyW73Wm06em+eGUBDUAAoAJRI7QI5K6EaNOg0ADiLAQIKu4MMmKSePxNAAsgwTCwAHIsAAeCBpSIAvkikUo8IQcAAVR7crG4rRI5IEACcaJG9GElRYdQxtLpyqZLPZXJ50rl+EVyroqusGq1OH50sF0lUQX8MBYy3UmJo4o8ht5QA===)

### Expected behavior

The expected output is `1 2`

### Actual behavior

The actual output is `1 1`

### Known Workarounds

Using an `IEnumerator<int>` (for the snippet provided) works. But that doesn't work when using something an `ImmutableArray` for example (`ImmutableArray<T>.Enumerator` isn't convertible to `IEnumerator<T>`)

### Configuration

- `dotnet --version`: `8.0.100`
- Arch Linux x86_64
- Kernel: 6.6.1-arch1-1
- The bug is present when running in sharplab, so the issue probably isn't OS-related

### Other information

Looking at the CIL in sharplab (in Release mode), looks like the `E` field is copied when passed in `MoveNext` when readonly (because `List<T>.Enumerator` is a struct). So this seems like a tooling issue, not warning about this? But then how would this work if you need to use `ImmutableArray`?

**Comment by stephentoub** [comment]
Your enumerator field is readonly.  Calling a method on it is going to result in C# then making a copy to preserve the readonly-ness.  Remove the readonly from your field.

**Comment by sharwell** [comment]
This is related to https://github.com/dotnet/roslyn-analyzers/pull/5454 and https://github.com/dotnet/roslyn-analyzers/pull/3520. I would love to see the analyzer infrastructure add support for value copy callbacks to make the underlying analysis more reliable.

**Comment by monomere** [comment]
> Your enumerator field is readonly. Calling a method on it is going to result in C# then making a copy to preserve the readonly-ness. Remove the readonly from your field.

Yes, I know that works. What I'm saying is that this is completely silent to the user. I should've made the issue in some other repo though.

**Comment by monomere** [comment]
Looks like this is a frontend issue, closing this.
