### ISSUE TITLE
[RISC-V] Update TODOs for RiscV64 Machine and Architecture in Crossgen2 

### ISSUE THREAD

**Issue by gbalykov** [dotnet/runtime#96438]
Currently in RISC-V Crossgen2 port `(Architecture)9` and `(Machine)0x5064` are used instead of `Architecture.RiscV64` and `Machine.RiscV64` correspondingly, because those are not yet propagated to .NET SDK. Update them when new .NET SDK is shipped.

Related PR with initial RISC-V support in Crossgen2: https://github.com/dotnet/runtime/pull/95188.

cc @clamp03 @ashaurtaev

**Comment by am11** [comment]
Blocked on https://github.com/dotnet/runtime/pull/95980.
