### ISSUE TITLE
[mono][perf] iOS Mono HelloWorld startup regression

### ISSUE THREAD

**Issue by matouskozak** [dotnet/runtime#96449]
# Description
Mono regressed in startup times after updating OSX version to osx.13 (https://github.com/dotnet/runtime/commit/4dffd80c4d77c27e772a0be26e8036af77fbb26e).

Update: at the same time, xcode and iOS were updated to versions 15 and 17, respectively. 

Date | Diff | Change | Slowdown (ms) | Slowdown (%) 
--|--|--|--|--
16 Dec 2023 | https://github.com/dotnet/runtime/compare/22844957b51e7020215196d2896dbda6fefd449e...4dffd80c4d77c27e772a0be26e8036af77fbb26e | https://github.com/dotnet/runtime/commit/4dffd80c4d77c27e772a0be26e8036af77fbb26e | 8.3 | 18.8

![image](https://github.com/dotnet/runtime/assets/55735845/009d14b2-7e17-4df1-a916-e50e94c394e7)

## Affected scenarios: 
- iOS Mono
- iOS nativeAOT
- MAUI (TBC - perf measurements not working)

---

cc: @ivanpovazan @LoopedBard3 
fyi: @SamMonoRT @akoeplinger @kotlarmilos

**Comment by SamMonoRT** [comment]
cc @rolfbjarne fyi  - this seems like an OS upgrade causing the regression.

**Comment by rolfbjarne** [comment]
Is this testing on an actual device? Because it would be really weird for the macOS version used to build the app would affect the launch performance of the app on the device.

**Comment by matouskozak** [comment]
> Is this testing on an actual device? Because it would be really weird for the macOS version used to build the app would affect the launch performance of the app on the device.

I believe the test are running on real iPhones in the lab (@LoopedBard3 correct me if I am wrong).

**Comment by LoopedBard3** [comment]
Yes, these tests are running on the devices themselves. At the same time we updated to OSX.13 and to xcode 15, we also updated to the iOS devices to run iOS 17.

**Comment by rolfbjarne** [comment]
Not sure if there's anything for us to do here, since this seems to be a regression in iOS itself.

**Comment by matouskozak** [comment]
Based on further investigation, the "regression" was introduced by a new lab device. After introducing split view for different devices (thank you @LoopedBard3), we can see that no significant regression happened in the studied period. ![image](https://github.com/dotnet/runtime/assets/55735845/a7294775-4620-4254-b14a-cd947351f137)
