### ISSUE TITLE
Vector128.LessThan broken for some UIntPtr values on mono

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#96443]
Repro:
```C#
        [Theory]
        [InlineData(0ul)]
        [InlineData(1ul)]
        [InlineData(127ul)]
        [InlineData(128ul)]
        [InlineData(129ul)]
        [InlineData((ulong)int.MaxValue)]
        [InlineData(ulong.MaxValue)]
        public void Repro2(ulong ulValue)
        {
            Vector128<UIntPtr> vector = Vector128.Create((UIntPtr)ulValue);
            Assert.True(Vector128.EqualsAll(Vector128.LessThan(vector, Vector128<UIntPtr>.Zero), Vector128<UIntPtr>.Zero));
        }
```

That test passes for all of the supplied values (I haven't tried others) except for ulong.MaxValue, which fails:
```
    System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Repro2(ulValue: 18446744073709551615) [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/System.Runtime.Intrinsics/tests/Vectors/Vector128Tests.cs(44,0): at System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Repro2(UInt64 ulValue)
           at System.Object.InvokeStub_Vector128Tests.Repro2(Object , Span`1 )
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(95,0): at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

I haven't tried other values.

https://dev.azure.com/dnceng-public/public/_build/results?buildId=512965&view=ms.vss-test-web.build-test-results-tab&runId=12013976&resultId=129149&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by fanyang-mono** [comment]
The test produced incorrect result when `ulValue` is `ulong.MaxValue`.

**Comment by fanyang-mono** [comment]
@stephentoub I believe that you created `System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Repro2` to narrow down the issue you ran into. Is there another test failing because of this? I would like to enable it in my PR.

**Comment by stephentoub** [comment]
I didn't merge that. It'd also be good to have tests for all the methods you mentioned, presumably for both uint and ulong and with various values. @tannergooding can likely recommend the best tests to augment. 

And it'd be good to enable the tests that are currently ActiveIssue'd against the associated issue.

**Comment by fanyang-mono** [comment]
@stephentoub  All the methods that I mentioned in my PR shared the code path, in terms of this specific bug. I've added a test for `LessThan` with `nuint.MaxValue`, which should be sufficient for locking down this behavior.
