### ISSUE TITLE
[Arm64] Script SIMD HW intrinsic test like #15771

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#9645]
There is a lot of similarity between X86 and ARM64 Simd tests.  
They should be able to use same/similar test generation scripting approaches.

X86 added a test generation script in dotnet/coreclr#15771.  

Refactor test/templates to allow use on both platforms.

Arm64 has some different issues
+ CoreCLR is ahead of API review & CoreFX.  Test will need to be disabled `#if`.
+ Vector64<T> is the same length as `double`, `ulong`, & `long`.  Therefore Vector64<T> generics only support 7 primitive types.

category:correctness
theme:intrinsics
skill-level:intermediate
cost:medium

**Comment by CarolEidt** [comment]
@tannergooding @echesakovMSFT - I believe this has been completed. Feel free to open a new issue if there's remaining test templating work to be done.
