### ISSUE TITLE
JIT assert on Unix in `ReturnTypeDesc::InitializeStructReturnType`

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#96461]
The new logic in https://github.com/dotnet/runtime/pull/96455#issuecomment-1875921135 is triggering an assert on OSX/Linux:
```
Assert failure(PID 10027 [0x0000272b], Thread: 85988 [0x14fe4]): Assertion failed '!m_inited' in 'System.Runtime.Intrinsics.VectorMath:Log2Single[System.Runtime.Intrinsics.Vector128`1[float],System.Runtime.Intrinsics.Vector128`1[int],System.Runtime.Intrinsics.Vector128`1[uint]](System.Runtime.Intrinsics.Vector128`1[float]):System.Runtime.Intrinsics.Vector128`1[float]' during 'Importation' (IL size 976; hash 0xefb066b7; Tier0)
```

The failure is possibly related to the use of generics + static virtuals in interfaces + the vector types being HVAs on these platforms.

**Comment by tannergooding** [comment]
This is blocking some of the work in the `TensorPrimitives` area as we're wanting to ensure the vectorized primitives are getting exposed as part of the .NET 9 surface area.

We're still going to be able to make progress as part of the out of band package, but it's going to involve some extra work with the code and additional code duplication until the issue is resolved.

**Comment by JulieLeeMSFT** [comment]
@jakobbotsch, PTAL this blocking issue.
