### ISSUE TITLE
System.Text.Json.Serealization (JsonPropertyName) is not converting json properties to dto classes

### ISSUE THREAD

**Issue by Th-Lima** [dotnet/runtime#96482]
### Description

When using the System.Text.Json.Serealization package with the [JsonPropertyName] annotation, it is not possible to convert JSON properties to classes, if, in the class, the properties have different names than the JSON properties, even using the [JsonPropertyName] annotation.

### Reproduction Steps

Having the JSON of the response below:
`{
  "data": {
    "update_products": [
      {
        "indice": "06ab6dda-a9ee-4747-bfb5-91b843da99b6"
      }
    ]
  }
}`

AND

Having the DTO below:
`public class DtoMessageResponse
    {
        [JsonPropertyName("indice")]
        public Guid IndiceGuid { get; set; }
    }`

The result obtained for Guid is:
`00000000-0000-0000-0000-000000000000`

If I change the name of my property to `public Guid Indice { get; set; }` will work correctly.

The conclusion I obtained is that `[JsonPropertyName("")]` does not work correctly.

### Expected behavior

It's expected result was that the property `public Guid IndiceGuid { get; set; }` get the correct value in JSON

### Actual behavior

The result obtained for Guid is:
`00000000-0000-0000-0000-000000000000`

### Known Workarounds

If I change the name of my property to `public Guid Indice { get; set; }` will work correctly.

### Configuration

.NET 6

**Comment by eiriktsarpalis** [comment]
Your reproduction appears to be missing information, e.g. the type that is being passed to the deserialization call. Assuming you just tried deserialize the payload using `DtoMessageResponse` as the root type, then getting an empty Guid is the expected result -- the shape of the JSON doesn't match the schema of `DtoMessageResponse`.

I tried filling the gaps and defined container types that match your schema:
```C#
string json = """{ "data": { "update_products": [ { "indice": "06ab6dda-a9ee-4747-bfb5-91b843da99b6" } ] } }""";
var result = JsonSerializer.Deserialize<MessageBody>(json);
Console.WriteLine(result.Data.UpdateProducts[0].IndiceGuid);

public class MessageBody
{
    [JsonPropertyName("data")]
    public Data Data { get; set; }
}

public class Data
{
    [JsonPropertyName("update_products")]
    public DtoMessageResponse[] UpdateProducts { get; set; }
}

public class DtoMessageResponse { [JsonPropertyName("indice")] public Guid IndiceGuid { get; set; } }
```
And this immediately worked as expected.

**Comment by ouzdev** [comment]
Hi, could you be using the Deserialize method in the Newtonsoft library when deserializing ?

**Comment by Th-Lima** [comment]
I used the `System.Text.Json.Serealization` package to deserialize

**Comment by eiriktsarpalis** [comment]
@Th-Lima we would still need a minimal reproduction to be able to assist you.
