### ISSUE TITLE
Is there a way to Request the "Profiler" if one is attached to the CLR to request a "Flush" or harvest from Managed code?

### ISSUE THREAD

**Issue by skyhoshi** [dotnet/runtime#96485]
Context: 
Dotnet6 Application Running in Docker (Linux Container) in Kubernetes, sidecars, with a Profiler setup.

Problem: When we call for the application to shut down Kubernetes sidecar itsio (networking) ends before we can finish sending profilers logs out to the cloud. 

Question:
Is there a way our managed application (net6) can call up to the CLR and trigger a "flush" or "collection" so that we don't have to wait the 2 mins for the profiler to flush itself?

Currently we are putting in a process wait time at the end of our application to wait 120 seconds to accommodate for the "Flush" time. 

if we could manage to trigger the profiler flush (Abandoning any data that would be collected after our request for a flush of course) and allow the application to shutdown. 

I know this sounds like a profiler design issue. but that's what i'm after. I just want to trigger the profilers collection so i can minimize or do away with the 120 wait. 

I was hoping for something like what we have with Garbage collection, we can trigger it manually via code. I was hoping for something like that for Profiling. 

Kubernetes IS going to solve this problem with by allowing controlled process shutdown of sidecars. so a solution is coming. but again

**Comment by jkotas** [comment]
Can you P/Invoke your profiler library from your application?

**Comment by tommcdon** [comment]
@davmason

**Comment by skyhoshi** [comment]
I'm going to look into the P/Invoke process. 
Can I call 
https://learn.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/icorprofilercallback-appdomainshutdownstarted-method
And Or
https://learn.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/icorprofilercallback-shutdown-method

I'm struggling to find the AppDomainId required for the AppDomain Shutdown started method.  and that seems more inclusive than the "Shutdown" method but then again, i don't understand what is subscribed or listening at that point. 

I'm thinking that if I found the "Application Is About to shutdown start last collection and flush" method and wired that up as an extern it would/should kick off the collection in the context of the CLR. 
I think that's the AppDomainShutdownStarted Method
at least thats what I hope.
Any Additional suggestions would be wonderful as well.

**Comment by skyhoshi** [comment]
will "AppDomain.CurrentDomain.Id" work for the AppDomainShutdownstarted Method?

**Comment by skyhoshi** [comment]
I'm struggling to execute those methods.

**Comment by davmason** [comment]
Hi @skyhoshi,

With those methods you mention (ICorProfilerCallback::Shutdown and ICorProfilerCallback::AppDomainShutdownStarted) those are callback methods that a registered profiler will receive from the runtime when shutdown has started. They are not methods that you can call with a PInvoke.

When you talk about a profiler above, do you mean a native ICorProfiler based profiler? If one is already attached to the runtime then you should get Shutdown callbacks on non-error cases for the app, and blocking in that method will prevent shutdown from continuing.
