### ISSUE TITLE
[TieredCompilation] Performance regression due to extra indirections (non-virtual case)

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#965]
Repro: https://gist.github.com/jkotas/56b1bdf1cdc98ab5b6d92974ff01b322

Results on current master Windows x64:

`COMPlus_TieredCompilation=1`: 20969ms
`COMPlus_TieredCompilation=0`: 11156ms

cc @kouvel @noahfalk

**Comment by yahorsi** [comment]
Hi,

Could you please share the plans on fixing this in 3.0/3.1?
Our team observes ~25% perf degradation after migrating to the 3.1
We are currently investigating but this might be it.

Thank you!
