### ISSUE TITLE
Executable published for osx-arm64 does not work on the new Macs

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/runtime#96501]
### Description

Moved from https://developercommunity.visualstudio.com/t/Executable-published-for-osx-arm64-does-/10550167

### Reproduction Steps

If you use a Windows machine and build a simple Console application in C# dotnet version 8 and publish for osx-arm64, the generated executable will not work on the new Macs i.e. osx-arm64.

### Expected behavior

Works

### Actual behavior

Not working

**Comment by elinor-fung** [comment]
This was publishing for single-file. From the developer community ticket:
```
  <PropertyGroup>
    <AssemblyVersion>13.3.0.0</AssemblyVersion>
    <FileVersion>13.3.0.0</FileVersion>
    <Version>13.3.0.0-beta</Version>
    <Configuration>Release</Configuration>
    <Platform>Any CPU</Platform>
    <PublishDir>..\executableforosx-arm64\</PublishDir>
    <PublishProtocol>FileSystem</PublishProtocol>
    <TargetFramework>net8.0</TargetFramework>
    <SelfContained>false</SelfContained>
    <RuntimeIdentifier>osx-arm64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>
  ```

**Comment by agocke** [comment]
This is likely the lack of codesign.

**Comment by agocke** [comment]
Closing as dup of https://github.com/dotnet/sdk/issues/34917
