### ISSUE TITLE
Different JavaScript Objects are wrapped by the same JSObject instance.

### ISSUE THREAD

**Issue by boris-richter** [dotnet/runtime#96512]
### Description

Some JavaScript objects are returned as the same JSObject instance depending on the order they are retrieved.

```
Console.WriteLine(JSHost.GlobalThis.GetPropertyAsJSObject("EventTarget"));
Console.WriteLine(JSHost.GlobalThis.GetPropertyAsJSObject("Node"));
Console.WriteLine(JSHost.GlobalThis.GetPropertyAsJSObject("Element"));
```
All lines return the same JSObject instance:
```
(js-obj js '2')
(js-obj js '2')
(js-obj js '2')
```

If the members are retrieved in reverse order, different objects are returned:
```
Console.WriteLine(JSHost.GlobalThis.GetPropertyAsJSObject("Element"));
Console.WriteLine(JSHost.GlobalThis.GetPropertyAsJSObject("Node"));
Console.WriteLine(JSHost.GlobalThis.GetPropertyAsJSObject("EventTarget"));
```
Output:
```
(js-obj js '2')
(js-obj js '3')
(js-obj js '4')
```

### Reproduction Steps

Console.WriteLine(JSHost.GlobalThis.GetPropertyAsJSObject("EventTarget"));
Console.WriteLine(JSHost.GlobalThis.GetPropertyAsJSObject("Node"));
Console.WriteLine(JSHost.GlobalThis.GetPropertyAsJSObject("Element"));

### Expected behavior

Different JavaScript objects should be wrapped by different JSObject instances no matter in which order they are retrieved.

### Actual behavior

The properties return the same JSObject instance.

### Configuration

.NET 8.0.100

**Comment by pavelsavara** [comment]
That's just a handle which is being re-used. There could be different speed of collecting the proxy and re-using the handle.
Or are you able to see the actual object being confused with each other ?
