### ISSUE TITLE
Solution with mixed Framework/Core/Standard libraries gives errors for Microsoft.Extensions.Logging.Abstractions v6.0.4

### ISSUE THREAD

**Issue by Kolky** [dotnet/runtime#96529]
I'm not sure where else to place this question then here.

**Introduction**
I've got a visual studio solution with many class libraries and applications. All applications we're originally developed in .NET Framework together with Entity Framework 6. We're now plowing through an upgrade for most of these applications to .NET6 (and somewhere soon to .NET8). For one application we have decided to stick to .NET Framework and we're never going to upgrade it but we'll have to support it for some time (it's an ASP.NET MVC4 portal which is going to be rebuild entirely). The application stack with project dependencies looks something like this:

* Common class libraries - .net standard 2.0
  * Entity & repository class library (uses Entity Framework 6) - mixed .net framework 4.7.2 and .net6
    * Business logic class libraries - .net standard 2.0
      * Application that will be upgraded - .net6
      * Application that will not be upgraded - .net framework 4.7.2

**Problem**
We recently tried to migrate our logging solution to the `Microsoft.Extensions.Logging.Abstractions` library with the `ILogger` interface. So inside one Common class library lives a dependency on v6.0.4 of this library. One of our business logic class libraries requires the package `Microsoft.Extensions.Caching.Memory` v6.0.1 which targets v6.0.0 or higher of the logging library, so we've added the logging library with v6.0.4 to it so it uses the same version as our other class libraries.

Now I'm getting the following error:

`error CS1705: Assembly 'XXX.Repository' with identity 'XXX.Repository, Version=1.20.0.0, Culture=neutral, PublicKeyToken=XXX' uses 'Microsoft.Extensions.Logging.Abstractions, Version=6.0.0.4, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.Extensions.Logging.Abstractions' with identity 'Microsoft.Extensions.Logging.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' [D:\a\1\s\XXX.BusinessLogic\XXX.BusinessLogic.csproj]`

Which was very confusing to me, as we nowhere use this version 6.0.0 of the logging library!

Digging a bit further I found that inside the Nuget package of the `Microsoft.Extensions.Logging.Abstractions` for v6.0.4 are the following DLLs:
* .net461 - v6.0.4
* .net6.0 - v6.0.0
* .netstandard2.0 - v6.0.0

So this is causing the issue! I can fix compilation and get everything working if I remove the extra dependency I added in the business logic library. But then I get the following warning:

```
There was a conflict between "Microsoft.Extensions.Logging.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" and "Microsoft.Extensions.Logging.Abstractions, Version=6.0.0.4, Culture=neutral, PublicKeyToken=adb9793829ddae60".
    "Microsoft.Extensions.Logging.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" was chosen because it was primary and "Microsoft.Extensions.Logging.Abstractions, Version=6.0.0.4, Culture=neutral, PublicKeyToken=adb9793829ddae60" was not.
    References which depend on "Microsoft.Extensions.Logging.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" [D:\Dev\XXX\packages\microsoft.extensions.logging.abstractions\6.0.4\lib\netstandard2.0\Microsoft.Extensions.Logging.Abstractions.dll].
        D:\Dev\XXX\packages\microsoft.extensions.logging.abstractions\6.0.4\lib\netstandard2.0\Microsoft.Extensions.Logging.Abstractions.dll
          Project file item includes which caused reference "D:\Dev\XXX\packages\microsoft.extensions.logging.abstractions\6.0.4\lib\netstandard2.0\Microsoft.Extensions.Logging.Abstractions.dll".
            D:\Dev\XXX\packages\microsoft.extensions.logging.abstractions\6.0.4\lib\netstandard2.0\Microsoft.Extensions.Logging.Abstractions.dll
    References which depend on "Microsoft.Extensions.Logging.Abstractions, Version=6.0.0.4, Culture=neutral, PublicKeyToken=adb9793829ddae60" [].
        D:\Dev\XXX\XXX.Entities\bin\x64\DebugSystemTest\net472\XXX.Entities.dll
          Project file item includes which caused reference "D:\Dev\XXX\XXX.Entities\bin\x64\DebugSystemTest\net472\XXX.Entities.dll".
            D:\Dev\XXX\XXX.Entities\bin\x64\DebugSystemTest\net472\XXX.Entities.dll
        D:\Dev\XXX\XXX.Common\bin\x64\DebugSystemTest\netstandard2.0\XXX.Common.dll
          Project file item includes which caused reference "D:\Dev\XXX\XXX.Common\bin\x64\DebugSystemTest\netstandard2.0\XXX.Common.dll".
            D:\Dev\XXX\XXX.Common\bin\x64\DebugSystemTest\netstandard2.0\XXX.Common.dll
            D:\Dev\XXX\XXX.Entities\bin\x64\DebugSystemTest\net472\XXX.Entities.dll
```

How do I fix my solution so that I do not get this warning!? There are two things I can think of;
* Have all business logic class libaries multi target .net framework 4.7.2 and .net6, but this will really hinder development in the future and is a lot of work.
* Or downgrading the logging package to v6.0.0. But I'm not sure if that poses a security risk?

**Comment by Kolky** [comment]
What I also would like to have answered, is it normal that in a specific version (6.0.4 in this case) of a NuGet package we can see different versions for the different targets? Or was that a mistake?

**Comment by ericstj** [comment]
> is it normal that in a specific version (6.0.4 in this case) of a NuGet package we can see different versions for the different targets? Or was that a mistake

Yes that's normal.

Consider project A references project B.  Both use package X.

Two things to avoid:
1. Downgrading a package - project A references X:1 B references X:2.
2. Referencing a netframework project from a NETStandard or NETCore project - B above would be NETFramework and A is NETStandard or NETCore.  We only support using NETFramework libraries from NETStandard or NETCore projects for compatibility.  When you do this you lose reference checking and you also invite these versioning problems.

Both of these cases should result in warnings, but you may have suppressed them.
https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1605
https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1701

If I look at the above I see `XXX.BusinessLogic.csproj` is getting a direct reference to `6.0.0.0` and an indirect reference to `6.0.0.4` from XXX.Entities.
That tells me that it either downgraded the package reference (case 1 above) or it's a NETCore or NETStandard project referencing a NETFramework project (case 2).

Based on what you shared (business logic is netstandard 2.0), I'm pretty sure this is case 2.  Why is XXX.Entities targeting NETFramework and not either multi-targeting or targeting NETStandard?

> Have all business logic class libaries multi target .net framework 4.7.2 and .net6, but this will really hinder development in the future and is a lot of work.

You don't need to do this, just make sure your projects don't need to reference a NETFramework library from a non-NETFramework project.

**Comment by Kolky** [comment]
> The conflict warning you are getting was compile or run time warning? and if run time, were you targeting 4.7.2 at that time? I am asking because maybe binding redirect can help in this case.
>
@tarekgh 
The warning is at compile time. And I have all binding redirects set up in the final .NET Framework applications.

> If I look at the above I see `XXX.BusinessLogic.csproj` is getting a direct reference to `6.0.0.0` and an indirect reference to `6.0.0.4` from XXX.Entities. That tells me that it either downgraded the package reference (case 1 above) or it's a NETCore or NETStandard project referencing a NETFramework project (case 2).
> 
> Based on what you shared (business logic is netstandard 2.0), I'm pretty sure this is case 2. Why is XXX.Entities targeting NETFramework and not either multi-targeting or targeting NETStandard?
> 
@ericstj Our XXX.Entities project is multi-targetting .NET Framework 4.7.2 and .NET6 (since it uses Entity Framework 6). So that is why I don't understand I'm getting this issue. I checked and all my projects use the same version. This started appearing only after I added a using for the logger inside the XXX.Entities project. So I was before getting, as you also suggest, NU1701 warnings. Now after adding this using it stopped compiling.

For now I'm using the 6.0.0 version everywhere. Since we're only using the ILogger interface from the library. And in the .NET Framework applications we have our own implementation of the interface, so not using any of the code-generation that got updated in the versions after it.

But the issue is still confusing to me, and I still suspect it has to do with the mixed versions in the NuGet package. I'll try to make a reproduction case.

**Comment by Kolky** [comment]
[Runtime96529.zip](https://github.com/dotnet/runtime/files/13940014/Runtime96529.zip)

Here is a reproduction scenario, it is based off of my problem. Built it then the project "BusinessLogicImplementation" will throw the error as mentioned.

**Comment by ericstj** [comment]
In this case you have `BusinessLogicInterfaces` (netstandard2.0) referencing `Entities` (net472;net6.0).

This is causing the `BusinessLogicInterfaces` project to actually get the `net472` implementation of `Entitites` since neither `net472` nor `net6.0` are compatible with `netstandard2.0` -- they are both "more specific" in that they have more API.  This does surface as a warning:

> Warning	NU1702	ProjectReference 'C:\scratch\Runtime96529\Entities\Entities.csproj' was resolved using '.NETFramework,Version=v4.7.2' instead of the project target framework '.NETStandard,Version=v2.0'. This project may not be fully compatible with your project.	BusinessLogicInterfaces

To fix this, add `netstandard2.0` to `Entitites`.  When doing this all your SLN's warnings and errors should go away.
```xml
    <TargetFrameworks>net472;netstandard2.0;net6.0</TargetFrameworks>
```

**Comment by tarekgh** [comment]
I am closing this issue as it looks like no more action is needed from our side. @Kolky feel free to send any more questions if you still have any.

**Comment by tarekgh** [comment]
I am closing this issue as it looks like no more actions are needed from our side. @Kolky feel free to send any more questions if you still have any.

**Comment by Kolky** [comment]
@ericstj I can't change that project, since it depends on EntityFramework. Which has no .NET Standard 2.0 version available.

**Comment by ericstj** [comment]
You can depend on EF6 while targeting netstandard2.0 and isolate the case where you need to suppress NU1702 to that Entities project.  That's more in-line with what the whole compatibility support for .NETFramework was meant for - enabling use of an old component which isn't building for newer frameworks.  I think if you did that here it would work since it looks like EF6 doesn't bring in any other dependencies which would cause these version differences (unlike your new code which is referencing the latest packages).

**Comment by ericstj** [comment]
I see - EntityFramework itself makes it difficult to use from a `netstandard2.0` project because it has assets in the root `build` and `buildTransitive` folders - so NuGet includes those and won't include any of its libs.  Seems like this broke between EF6 `6.2.0` and `6.3.0`.

Probably that's a request for EF6 if you want it to be consumable in `netstandard2.0` projects.  They could make that easier by only including their targets in folders that match the TFMs that their lib targets.

You could probably workaround this by manually including the libs.  I would want the EF team to approve of any workaround here, but this should work in a `netstandard2.0` project.
```xml
    <PackageReference Include="EntityFramework" Version="6.4.4" GeneratePathProperty="true"/>
    <Reference Include="$(PkgEntityFramework)\lib\net45\EntityFramework.dll"/>
    <Reference Include="$(PkgEntityFramework)\lib\net45\EntityFramework.SqlServer.dll"/>
```
