### ISSUE TITLE
Returning a ReadOnlySpan<byte> from a LibraryImport fails

### ISSUE THREAD

**Issue by ThadHouse** [dotnet/runtime#96525]
### Description

Returning a ReadOnlySpan<byte> from a call generated by LibraryImport fails to compile, even though it should. It correctly works with a byte[] as the return type instead of ReadOnlySpan<byte>

### Reproduction Steps

Compile the following code definition

```
    [LibraryImport("wpiutil", EntryPoint = "WPI_GetResource_wpilib_128_png")]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    [return: MarshalUsing(CountElementName = nameof(len))]
    public static unsafe partial ReadOnlySpan<byte> GetResourceWpilib128Png(out nuint len);
```

### Expected behavior

The code should compile

### Actual behavior

The code fails with the following error 

```
C:\Users\thadh\Documents\GitHub\robotdotnet\WPILib\src\wpiutil\Natives\ImagesNative.cs(13,53): error SYSLIB1051: The specified parameter needs to be marshalled from unmanaged to managed, but the marshaller type 'global::System.Runtime.InteropServices.Marshalling.ReadOnlySpanMarshaller<,>' does not support it. The generated source will not handle marshalling of the return value of method 'GetResourc
eWpilib128Png'. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1051) [C:\Users\thadh\Documents\GitHub\robotdotnet\WPILib\src\wpiutil\wpiutil.csproj]
C:\Users\thadh\Documents\GitHub\robotdotnet\WPILib\src\wpiutil\Microsoft.Interop.LibraryImportGenerator\Microsoft.Interop.LibraryImportGenerator\LibraryImports.g.cs(574,68): error CA1420: Managed parameter or return types require runtime marshalling to be enabled (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1420) [C:\Users\thadh\Documents\GitHub\robotdotnet\WPILib\ 
src\wpiutil\wpiutil.csproj]
```

### Configuration

.NET 8

**Comment by AaronRobinsonMSFT** [comment]
@jtschuster Can you take a look at this?

**Comment by ThadHouse** [comment]
Talking with @jkoritzinsky this is expected behavior, since the ReadOnlySpan can't be written to later in the source generator. So not a bug.

**Comment by AaronRobinsonMSFT** [comment]
> Talking with @jkoritzinsky this is expected behavior, since the ReadOnlySpan can't be written to later in the source generator. So not a bug.

Agreed on it being by-design for now. I'm going to recommend we look at how to make this more natural in this release. The model should have a way to express both a read-only and read-write concept with respect to types. This is a low-priority issue, but definitely will a win for expressing intent for interop scenarios.
