### ISSUE TITLE
[API Proposal]: Add MinValue/MaxValue to INumber

### ISSUE THREAD

**Issue by oliversaggau** [dotnet/runtime#96534]
### Background and motivation

With the introduction of INumber one can finally introduce generic methods to handle all number types. Sometimes in those methods one needs to access MinValue and/or MaxValue so it would be nice to have them available in the INumber interface like for example `INumber.Zero` is

### API Proposal

```csharp
public interface INumberBase<TSelf>  : ... where TSelf : INumberBase<TSelf>?
{
	static abstract TSelf MaxValue { get; }
	static abstract TSelf MinValue { get; }
	...
}
```

### API Usage

```csharp
public static void SomeGenericNumberMethod<T>(T value) where T : INumber<T>
{
	if (value == T.MaxValue)
	{
		...
	}
	...
}
```

**Comment by oliversaggau** [comment]
I just realized this is already possible with [IMinMaxValue](https://learn.microsoft.com/en-us/dotnet/api/system.numerics.iminmaxvalue-1?view=net-8.0) 🙈 Sorry for creating this proposal

**Comment by tannergooding** [comment]
Just noting that it is explicitly separate because not all numbers have a min/max value possible. Consider, for example, `BigInteger`.
