### ISSUE TITLE
NativeAOT packages contain two copies of msbuild files

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#96556]
We have to packages for the NativeAOT compiler: `Microsoft.Dotnet.ILCompiler` and then the platform specific `runtime-win-x64.Microsoft.Dotnet.ILCompiler`. Both packages have a `build` directory in them which contains the MSBuild files (`.targets`, `.props`).

During publish, we only use the files from the platform agnostic package. There's no reason to ship the same files again the platform specific package as well.

There are some other files in `tools\netstandard` directory which seem to also be duplicated unnecessarily.

**Comment by MichalStrehovsky** [comment]
Related (that was closed): https://github.com/dotnet/runtime/issues/75468
