### ISSUE TITLE
MarshalMode.ElementOut expects a ConvertToUnmanged function to exist

### ISSUE THREAD

**Issue by ThadHouse** [dotnet/runtime#96564]
### Description

MarshalMode.ElementOut should only be used for Unmanaged to Manged Array Conversions, however when specified as a CustomAttribute, a ConvertToUnmanged  function is required or SYSLIB1057 error occurs. 

### Reproduction Steps

```
using System.Runtime.InteropServices.Marshalling;

[CustomMarshaller(typeof(ManagedType), MarshalMode.ElementOut, typeof(MyCustomMarshaller))]
public static class MyCustomMarshaller
{
    public static ManagedType ConvertToManaged(UnmanagedType unmanaged)
    {
        return new ManagedType
        {
            topic = unmanaged.topic,
        };
    }
}

public struct UnmanagedType
{
    public int topic;
}

public struct ManagedType {
    public int topic;
}
```

### Expected behavior

Code should compile successfully

### Actual behavior

```
C:\Users\thadh\DotNetBuilds\Class1.cs(3,71): error SYSLIB1057: The type 'MyCustomMarshaller' specifies that it supports the 'ElementOut' marshal mode for 'ManagedType' but does not provide a one-parameter 'ConvertToUnmanaged' method that takes a 'ManagedT
ype' as a parameter and returns a value of an 'unmanaged' type (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1057) [C:\Users\thadh\DotNetBuilds\DotNetBuilds.csproj]
```

### Other information

The example at https://learn.microsoft.com/en-us/dotnet/standard/native-interop/tutorial-custom-marshaller doesn't compile due to this bug

**Comment by jkoritzinsky** [comment]
The `Element*` marshal modes must support both managed->unmanaged and unmanaged->managed scenarios because an `out T[]` parameter needs managed->unmanaged in a P/Invoke or Com Object Wrapper scenario and unmanaged->managed in a Reverse P/Invoke or Managed Object Wrapper scenario.
