### ISSUE TITLE
MemoryExtensions.Split with white space seprator and StringSplitOptions.TrimEntries trims the seprator of last range if destination isn't enough long

### ISSUE THREAD

**Issue by aianlinb** [dotnet/runtime#96579]
### Description

I'm making an Enumerator for `ReadOnlySpan<char>.Split`
Which calls Split in a loop that use last Range of `destination` from the previous result as the `source`.
It works in most case but the following:

According to the document:
> If there are more regions in `source` than will fit in `destination`, the first `destination` length minus 1 ranges are stored in `destination`, and a range for the remainder of `source` is stored in `destination`.

But when using a white space `' '` as the seprator with `StringSplitOptions.TrimEntries` as the options, and the destination isn't enough long to contain all results, the seprator in the last element may be trimmed.

### Reproduction Steps

```cs
[TestMethod]
public void Split() {
	ReadOnlySpan<char> source = "X X  X X";
	Span<Range> destination = stackalloc Range[5];

	MemoryExtensions.Split(source, destination, ' ', StringSplitOptions.TrimEntries);

	foreach (var range in destination)
		Debug.WriteLine(source[range].ToString());
	/*
			
	Result:
	"X"
	"X"
	""
	"X"
	"X"

	*/
}

[TestMethod]
public void SplitWithNotEnoughLongDestination() {
	ReadOnlySpan<char> source = "X X  X X";
	Span<Range> destination = stackalloc Range[3];

	MemoryExtensions.Split(source, destination, ' ', StringSplitOptions.TrimEntries);
	/*
	result of `destination` here:
	Excepted:
	"X"
	"X"
	" X X"

	Actual:
	"X"
	"X"
	"X X"

	*/

	// Split remaining
	Span<Range> destination2 = stackalloc Range[2];

	MemoryExtensions.Split(source[destination[^1]], destination2, ' ', StringSplitOptions.TrimEntries);

	foreach (var range in destination[..^1])
		Debug.WriteLine(source[range].ToString());
	foreach (var range in destination2)
		Debug.WriteLine(source[range].ToString());
}
```

### Expected behavior

Output of `SplitWithNotEnoughLongDestination()` should be the same as `Split()`:
"X"
"X"
""
"X"
"X"

### Actual behavior

Output of `SplitWithNotEnoughLongDestination()`:
"X"
"X"
"X"
"X"

### Known Workarounds

Don't use StringSplitOptions.TrimEntries and manually trims each element of the result

### Configuration

.Net 8.0

**Comment by stephentoub** [comment]
Thanks, but I'm not clear on what the problem is? TrimEntries results in every returned result being trimmed, that's by design. MemoryExtensions.Split is matching String.Split's behavior there, too.

**Comment by aianlinb** [comment]
> Thanks, but I'm not clear on what the problem is? TrimEntries results in every returned result being trimmed, that's by design. MemoryExtensions.Split is matching String.Split's behavior there, too.

If that's by design, does this mean that if I don't know the length required by `destination`, I will have no way to ensure a complete splitting result of the full string with `TrimEntries`, and have to split without `TrimEntries` and trim them manually instead?

Is there a better way or may there be a better API in the future to achieve this?

**Comment by aianlinb** [comment]
Okay, I got it. Thank you for your explanation.
