### ISSUE TITLE
possibly memory leak in .net 8

### ISSUE THREAD

**Issue by netetireallyhuman** [dotnet/runtime#96581]
### Description

Maybe it's a duplicate of https://github.com/dotnet/runtime/issues/93966, so I apologize in advance, but I just want to be safe.
Now here is my problem:
I have a WPF application written in C# that runs on Windows 10 and is heavily multithreaded.
This setup runs stable and without memory leaks for several hours and even days on .net 7.0.
Additionally, my software has been running stable in a production environment on .net up to 4.6.2 for over 8 years.
Lately, I've been porting this software from .net 7 to .net 8.0.100 using Visual Studio 17.9.0 Preview 2.0 and I'm experiencing memory leaks (unmanaged heap slowly increasing with no visible limits).

### Reproduction Steps

I'm sorry I can't provide a simplified test program at the moment, but my simple programs haven't caused a memory leak so far.

### Expected behavior

no memory leaks

### Actual behavior

Lately, I've been porting my software from .net 7 to .net 8.0.100 using Visual Studio 17.9.0 Preview 2.0 and I'm experiencing memory leaks (unmanaged heap slowly increasing with no visible limits).
This behaviour is the same for debug and release builds.
The linked "vmmap"-screenshots show that the increased memory usage occurs in the unmanaged heap and that within the additional memory blocks, the string "ASYNC" dominates the "Strings" view.
![20231231](https://github.com/dotnet/runtime/assets/58332714/09c7b2b3-a3d3-4818-8270-8f56650944d0)
![20231231_ASYNC](https://github.com/dotnet/runtime/assets/58332714/7c631192-c53d-47d7-b877-a728a67a764a)

### Regression?

In the meantime, I imported my few software customizations from the .net 8.0 version back to the .net 7.0 version, rebuilt everything and tested it again:
The .net 7.0 version continues to run stable (software identical to the .net 8.0 version)!
The software runs stable and without memory leaks for several hours and even days on .net 7.0.
Additionally, my software has been running stable in a production environment on .net up to 4.6.2 for over 8 years.

### Known Workarounds

I can temporarily reduce my application's memory consumption by penetrating my workstation through other applications, but as long as my application runs alone, it continues to eat up more memory. This reminds me a bit of SQL Server's memory management.

### Configuration

WPF application written in C#, heavily multithreaded
Runtime .net 8.0.100, Visual Studio 17.9.0 Preview 2.0, Windows 10 64bit,
Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz   1.99 GHz, 32,0 GB

**Comment by netetireallyhuman** [comment]
Under "Actual behavior" I wrote "ASYNC" but it should be "ASYC", sorry.

**Comment by danmoseley** [comment]
Hello, is it possible to progressively simplify your app (or parts that are exercised) to try to narrow it down?

**Comment by netetireallyhuman** [comment]
Thank you for your response!
I'm sorry that I could not manage to reduce my software yet, but hopefully, some additional info may help:
My software consists of 29 basic dlls and additionally loads several monitoring dlls dynamically by reflection.

That's the way I start the Threads:
	this._starterThread = new Thread((te) =>
	{
	    Thread.CurrentThread.Name = "tryRunAsyncWhileIsRunRequired";
	    this.TryRunAsyncWhileIsRunRequired((TreeEvent?)te);
	});
	this._starterThread.SetApartmentState(ApartmentState.STA); // necessary because of dynamically loaded WPF-modules
	this._starterThread.IsBackground = true;
	try
	{
	    _starterThread.Start(source); // source is a nullable user obect
	}
	...
	
here is a part of my log:
...                    
		vishnu.exe ..\NetEti\Jobs\CheckAll 8.0.2.0 release build (Nimwegen)
							memory	cpu  threads    objects
Vishnu Start:	31.12.2023 13:20 -   178.080	03	30		61		(process id: 22092)
             	        31.12.2023 14:53 -   563.344	03    30		63		======== MEMORY LEAK ========
             	        31.12.2023 17:49 - 1.241.584	04    29		57		======== MEMORY LEAK ========
			(...\Profiling\PerfView\8020_rebuilt_binaries_identical_source_release_build_memory_leak\)
...

**Comment by danmoseley** [comment]
Have you tried using Visual Studio memory profiler?

**Comment by netetireallyhuman** [comment]
Frankly, I must suggest, that I don't know, how to examine the unmanaged heap with Visual Studio memory profiler.
By the way: I have no professional license, instead using the Community edition.
:sweat:

**Comment by gfoidl** [comment]
@netetireallyhuman please try to follow along [Debug a memory leak in .NET](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/debug-memory-leak) (VS Community isn't needed for this, only dotnet-tools). That should give you more insights.

**Comment by netetireallyhuman** [comment]
Hello gfoidl, thank you for your advice, I'll take a close look at all of this and apply it to my application where possible. This will definitely take some time.
Should I change the status of this issue in the meantime?

**Comment by gfoidl** [comment]
>  Should I change the status of this issue in the meantime?

No -- and if so someone of the team will add propers labels, etc. according the triage process.

Good luck in finding the cause, and please keep us updated.

**Comment by MichalPetryka** [comment]
If you start a lot of threads then the issue probably is #95362.

**Comment by netetireallyhuman** [comment]
Hello Michal, hello again Günther and Dan, 
thank you all for your help.
@Günther: I visited the site you suggested before, but even now I can't see a good approach for the unmanaged heap there.
I think I'm still missing something, but thanks anyway.
I believe now, Michal may be right. I will wait for the GA release of .NET 8.
Best wishes
Erik🖐😎👍

**Comment by danmoseley** [comment]
The fix for #95362 will be in 8.0.2 which will be released Feb 13.

@kunalspathak maybe you can help them validate on a nightly build

**Comment by danmoseley** [comment]
(Assuming it's that, it's just a guess, which is why a validation would be good)

**Comment by netetireallyhuman** [comment]
Great, I'll try it out and post my experiences here.😀

**Comment by netetireallyhuman** [comment]
Hello everyone,
the problem is solved. With dotnet runtime 8.0.2 the memory leak disappeared.
Many thanks to you all!
Best regards
Erik
