### ISSUE TITLE
Unable to open https://source.dot.net/ because the certificate has expired. SEC_ERROR_EXPIRED_CERTIFICATE

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/runtime#96601]
I am unable to open https://source.dot.net/. 
Browser report SEC_ERROR_EXPIRED_CERTIFICATE error.
The certificate is valid until Sun, 07 Jan 2024 12:40:33 GMT

Is it possible to renew the certificate for the https://source.dot.net/ site?

**Comment by niekschoemaker** [comment]
As a temp workaround (at least for firefox) when opening the site in incognito mode you can bypass the HSTS header and use the "Accept the risk and continue" while waiting for the proper fix.

**Comment by AlexRadch** [comment]
> As a temp workaround (at least for firefox) when opening the site in incognito mode you can bypass the HSTS header and use the "Accept the risk and continue" while waiting for the proper fix.

Thanks, I didn't know it was possible to bypass the HSTS header in private browsing mode.

**Comment by AshbyGeek** [comment]
Yeah, couldn't do that in chrome, but FireFox still allows it.

**Comment by stephentoub** [comment]
This should be fixed now. Thanks, @garath.
