### ISSUE TITLE
 Are only AMD64 and I386 hosts supported for the Linux cross-architecture component?

### ISSUE THREAD

**Issue by MinxuanZ** [dotnet/runtime#96608]
https://github.com/dotnet/runtime/blob/21b4a8585362c1bc12d545b63e62a0d9dd4e8673/eng/native/functions.cmake#L1-L9

**Comment by janvorli** [comment]
@monstercatss yes, that's the case. I have just found though that adding arm64 there just works. I needed to cross compile runtime for arm on arm64 and adding it to the place you've referred to was sufficient to make it work. I'll create a PR with that change soon.
Can you please share the reason why you were interested in it? I am just curious.

**Comment by MinxuanZ** [comment]
#99252
