### ISSUE TITLE
Decimal validation against XSD

### ISSUE THREAD

**Issue by makersky** [dotnet/runtime#96610]
### Description

XSD validation for decimal type is done after parsing string to decimal. Because parsing involves rounding validation is not always correct. 

For example a XSD with `fractionDigit = 3` correctly identifies validation error for input from range 0.9999 to 0.9...9(28 nines).
But 0.9..9(29 nines and more) is rounded to 1.0 (28 zeros) and is recognized as valid input. In this case neither `factionDigit` nor `totalDigits` works.

### Reproduction Steps

1. sample.xsd

```xml
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="DecimalType">
        <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="3"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="Test">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Value" type="DecimalType" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
```

2. Test.cs

```cs
public record Test
{
    public decimal Value { get; set; }
}
```

3. Program.cs

```cs
using System.Xml;
using System.Xml.Schema;
using System.Xml.Serialization;
using XsdFractionDigitFacet;

XmlSchema schema = XmlSchema.Read(new StreamReader("sample.xsd"), null)!;
XmlSchemaSet _schemaSet = new();
_schemaSet.Add(schema);
_schemaSet.Compile();

var _settings = new XmlReaderSettings();
_settings.Schemas.Add(_schemaSet);
_settings.ValidationType = ValidationType.Schema;
_settings.ValidationFlags = XmlSchemaValidationFlags.ReportValidationWarnings;
_settings.ValidationEventHandler += (sender, e) => Console.WriteLine($"Validation: {e.Message}");

var serializer = new XmlSerializer(typeof(Test));

foreach (var xml in GenerateSample())
{
    Console.WriteLine($"Xml       : {xml}");

    using var reader = XmlReader.Create(new StringReader(xml), _settings);
    var x = serializer.Deserialize(reader);
    Console.WriteLine($"Value     : {x}");
}

static IEnumerable<string> GenerateSample()
{
    //for (var i = '0'; i <= '9'; i++)
    var i = '9';
    {
        for (var j = 0; j < 50; j++)
        {
            yield return $"<Test><Value>0.{new string(i, j)}</Value></Test><!-- number of fraction digits: {j} -->";
        }
    }
}

```

### Expected behavior

Validation error should occur.

### Actual behavior

Input is recognized as valid against XSD.

### Configuration

* .NET 8
* Windows
* x64

**Comment by krwq** [comment]
I skimmed through https://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/datatypes.html#decimal
and https://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/datatypes.html#rf-fractionDigits

and this seems a bit tricky... per spec:

> The term fractionDigits is chosen to reflect the fact that it restricts the [·value space·](https://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/datatypes.html#dt-value-space) to those values that can be represented lexically in decimal notation using at most fractionDigits to the right of the decimal point. Note that it does not restrict the [·lexical space·](https://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/datatypes.html#dt-lexical-space) directly; a lexical representation that adds non-significant leading or trailing zero digits is still permitted.

which suggests we should be converting to decimal first but then at the same time I agree that most of the users would probably expect that to cause validation errors. Spec also mentions that IEEE allows some variation of rounding.

I'd personally treat 0.9999.... equivalent to 1.0 and most likely it's a result of some rounding error - at the same time it should have been rounded when it got serialized to XML.

@tannergooding do you perhaps have any extra opinion on this? It seems a bit moot to be honest - perhaps there is some clarification in the next version of spec (I haven't checked yet)

**Comment by makersky** [comment]
> @makersky out of curiosity, can you clarify what's your scenario? Are you trying to prevent this input for any particular reason?

Sorry for the late response. In my scenario, the XML is required to be 100% compatible with the XSD and the input values cannot be rounded. As a workaround, I switched to `XElement` and for nodes that may be subject to rounding perform additional checks on the original string.

**Comment by jeffhandley** [comment]
I'm glad you found a workaround approach, @makersky. Per the discussion, we wouldn't pursue changing this behavior, so I'm closing this issue.
