### ISSUE TITLE
TrimmerRootAssembly results in incoherent trimming and hence integrity check error

### ISSUE THREAD

**Issue by zorgoz** [dotnet/runtime#96620]
### Description

After publishing, an assembly marked as trim root is still trimmed in the compressed versions, while kept unchanged as uncompressed. The compressed version is served, but its integrity check hash is not the correct one, being rejected by the browser.

### Reproduction Steps

Steps to reproduce:
1. Create new hosted asp.net Blazor WebaAssembyl project
2. Add "Blazicons.MaterialDesignIcons" library reference to the client project
3. Use one of the icons on a page.
4.  Add timming opt-out to csproj (based on this [docs page](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-8-0#root-assemblies)):
```
<ItemGroup>
  <TrimmerRootAssembly Include="Blazicons.MaterialDesignIcons" />
</ItemGroup>
```
4. Create folder publish profile (Release, .net 7, portable)
5. Observe `\wwwroot\_framework` (**the uncompressed file is not trimmed, the compressed ones are**)
 ![Enabled](https://github.com/dotnet/linker/assets/1569170/548465a8-8af0-4304-9027-33c3c2b7dae8)
6 . Try to run the published project. You will get:
> Failed to find a valid digest in the 'integrity' attribute for resource 'https://.../_framework/Blazicons.MaterialDesignIcons.dll' with computed SHA-256 integrity 'gMXbZ3OfWdujY73B/l1KFNoubyP8nqgEYJ/OZjVnvaM='. The resource has been blocked.
7. If you download the file directly, you will get the compressed one.
8. Remove 4. from csproj.
9. Republish and observe folder (all are trimmed coherently):
![Disabled](https://github.com/dotnet/linker/assets/1569170/653ca0c2-8fbd-4832-bf42-ea0bcef11122)
10. Reload page. No error this time.a 

### Expected behavior

1. Consistently not to be trimmed
2. Correct hash

### Actual behavior

1. Compressed versions are still trimmed
2. Incorrect hash is provided for integrity check

### Configuration

Project is **.net 7** (with 8 installed): [dotnet --info](https://github.com/dotnet/runtime/files/13860922/info.txt)
Served from under IIS: [web.config](https://github.com/dotnet/runtime/files/13860953/web.config.txt)

**Comment by pavelsavara** [comment]
I think this is yet another manifestation of broken incremental publish https://github.com/dotnet/runtime/issues/98690

**Comment by lewing** [comment]
closing in favor of https://github.com/dotnet/runtime/issues/98690
