### ISSUE TITLE
Unnecessary expensive UnsafeQueueCustomWorkItem call from TaskCompletionSource.TrySetCanceled after Task.WhenAny

### ISSUE THREAD

**Issue by IlyaGrebnov** [dotnet/runtime#9662]
We using TaskCompletionSource to signal timeouts and cancellations after period of time from dedicated dispatcher / timer thread. TaskCompletionSource created with RunContinuationsAsynchronously to prevent hijacking this dedicated thread by continuations.  During timeouts and cancellations pattern works as expected, but if timeout is not necessary (underlying operation completed on time) we attempt to cleanup TaskCompletionSource by calling TrySetCanceled (part of IDisposable pattern along some other things). And this TrySetCanceled show some expense call stack due to UnsafeQueueCustomWorkItem attempting to schedule singleTaskCompletionAction registered for Task.WhenAny promise, but this promise already completed and scheduling is not necessary.

So the ask is would it be possible to optimize for this scenario? The trick is that ITaskCompletionAction only implements Invoke(Task) method and we would need something to indicate that invocation and scheduling callback is not necessary.

Here is minimal repro program:

        public static async Task Main(string[] args)
        {
            var tcs = new TaskCompletionSource<bool>(TaskCreationOptions.RunContinuationsAsynchronously);
            await Task.WhenAny(Task.Delay(10), tcs.Task);

            // Triggers UnsafeQueueCustomWorkItem for already completed promise.
            tcs.TrySetCanceled();
        }

**Comment by stephentoub** [comment]
Closing, per the above.  Thanks.
