### ISSUE TITLE
"Unexpected end of archive" while unzipping test assets

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#96627]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=517925
Build error leg or test failing: Build / Libraries Test Run release coreclr windows x64 Debug / Unzip Test Assets
Pull request: https://github.com/dotnet/runtime/pull/96602

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Unexpected end of archive",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=517925
**Error message validated:** `Unexpected end of archive`
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 1/8/2024 4:31:59 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0
