### ISSUE TITLE
[wasm] AOT: `System.Numerics.Tensors.Tests` - `aot-instances.dll with exit code 137`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#96631]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=517640&view=results
Build error leg or test failing: System.Numerics.Tensors.Tests
Pull request:

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "aot-instances.dll.* Exec .*System.Numerics.Tensors.Tests.dll",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[521087](https://dev.azure.com/dnceng-public/public/_build/results?buildId=521087)|dotnet/runtime|[normal-System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=521087&view=ms.vss-test-web.build-test-results-tab&runId=12243004&resultId=162713)|dotnet/runtime#95980|
|[519928](https://dev.azure.com/dnceng-public/public/_build/results?buildId=519928)|dotnet/runtime|[normal-System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=519928&view=ms.vss-test-web.build-test-results-tab&runId=12213400&resultId=164571)|dotnet/runtime#96696|
|[519750](https://dev.azure.com/dnceng-public/public/_build/results?buildId=519750)|dotnet/runtime|[normal-System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=519750&view=ms.vss-test-web.build-test-results-tab&runId=12210058&resultId=164571)|dotnet/runtime#96618|
|[519035](https://dev.azure.com/dnceng-public/public/_build/results?buildId=519035)|dotnet/runtime|[normal-System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=519035&view=ms.vss-test-web.build-test-results-tab&runId=12191900&resultId=172421)|dotnet/runtime#95980|
|[518510](https://dev.azure.com/dnceng-public/public/_build/results?buildId=518510)|dotnet/runtime|[normal-System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=518510&view=ms.vss-test-web.build-test-results-tab&runId=12177678&resultId=161154)|dotnet/runtime#96618|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|5|5|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=517640
**Error message validated:** `aot-instances.dll.* Exec .*System.Numerics.Tensors.Tests.dll`
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 1/8/2024 6:11:29 PM UTC

**Comment by radical** [comment]
This started being hit with [db90a849](https://github.com/dotnet/runtime/commit/db90a849eab60d9843b8151ab14ba998faee3825) ([build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=514508&view=results)). The last passing build was [7957edc2](https://github.com/dotnet/runtime/commit/7957edc2594634cd01efa06be146c007d2234655) ([build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=513866&view=results)).

The diff should be within 7957edc2594634cd01efa06be146c007d2234655...db90a849eab60d9843b8151ab14ba998faee3825 .

**Comment by radical** [comment]
cc @tannergooding @vargaz

**Comment by tannergooding** [comment]
I'd presume that it's https://github.com/dotnet/runtime/tree/d3be0ecf5a384189acd82f6c5b2631c1db423873

But that's just fixing a minor issue from https://github.com/dotnet/runtime/pull/94555 (https://github.com/dotnet/runtime/commit/7e51126799d19552cbf5ee52687d31f11438dda2) and isn't doing anything really unique here, it's just taking an already generic method and dispatching to one of two concrete implementations based on the type of `T`

**Comment by vargaz** [comment]
This is probably an OOM. It started with 7e51126799d19552cbf5ee52687d31f11438dda2, which seems to have a caused the aot compiler to generate way more generic instances. Will investigate.

**Comment by tannergooding** [comment]
Possibly the same issue as https://github.com/dotnet/runtime/issues/96630 then. I had initially thought the OOM might be due to the new `static virtuals` + `generics` methods, but hitting that even after breaking it apart to 8 concrete APIs.

**Comment by vargaz** [comment]
It looks like the failure is actually caused by the generic classes added to the test suite i.e. TensorPrimitives.Generic.cs.

**Comment by vargaz** [comment]
Compiling this test suite with <WasmDedup>false</WasmDedup> will probably work around the failure.

**Comment by tannergooding** [comment]
Which property needs to be set to `false`?

**Comment by vargaz** [comment]
```<WasmDedup>false</WasmDedup>```

**Comment by tannergooding** [comment]
Do you expect https://github.com/dotnet/runtime/issues/96630 is the same issue?

That one appears to be getting hit for `System.Private.Corelib` so it may not be as easy or as desirable to use that property there?

**Comment by tannergooding** [comment]
Keeping this open so that the underlying issue with LLVM can be tracked/resolved.

**Comment by vargaz** [comment]
Its tracked here:
https://github.com/dotnet/runtime/issues/95791

**Comment by radical** [comment]
this is still being hit for `System.Numerics.Tensors.Net8.Tests` which needs `WasmDedup=false` also.
[log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-96108-merge-cf61a9bfa65e4e2280/normal-System.Numerics.Tensors.Tests/1/console.dea697e9.log?helixlogtype=result).

And the failure on `System.Numerics.Tensors.Tests` is for the test assembly now instead of `aot-instances.dll` ([log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-7751c1e4f3d5420592/normal-System.Numerics.Tensors.Tests/1/console.e2a109c4.log?helixlogtype=result):
```
  [System.Numerics.Tensors.Tests.dll] Exec (with response file contents expanded) in /root/helix/work/workitem/e/publish: MONO_PATH=/root/helix/work/workitem/e/publish:/root/helix/work/correlation/build/microsoft.netcore.app.runtime.browser-wasm/runtimes/browser-wasm/native/:/root/helix/work/correlation/build/microsoft.netcore.app.runtime.browser-wasm/runtimes/browser-wasm/lib/net9.0 MONO_ENV_OPTIONS= /root/helix/work/correlation/build/cross/mono-aot-cross --wasm-exceptions --debug --llvm "--aot=no-opt,static,direct-icalls,deterministic,mattr=simd,dwarfdebug,llvm-path=/root/helix/work/correlation/build/emsdk/upstream/bin/,static,trimming-eligible-methods-outfile=/root/helix/work/workitem/e/wasm_build/obj/wasm/for-build/tokens/System_Numerics_Tensors_Tests_dll_compiled_methods.txt,llvmonly,interp,asmonly,llvm-outfile=/root/helix/work/workitem/e/wasm_build/obj/wasm/for-build/System.Numerics.Tensors.Tests.dll.bc.tmp,temp-path=/root/helix/work/workitem/e/wasm_build/obj/wasm/for-build/System.Numerics.Tensors.Tests.dll.tmp" "System.Numerics.Tensors.Tests.dll"
```

**Comment by radical** [comment]
I'll open two separate issues.
