### ISSUE TITLE
Size regression on win-x64 with managed objwriter

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#96665]
On win-x64, the object size is smaller with managed implementation, but final executable size regresses.
```pwsh
> Set-Alias -Name dotnet9 -Value ~/.dotnet9/dotnet
> dotnet9 --version
9.0.100-alpha.1.24059.1

> dotnet9 new webapiaot -n web1
> cd web1

# managed
> dotnet9 publish -c Release -o dist
> wsl du -b dist/web1.exe obj/Release/net9.0/win-x64/native/web1.obj

9504768 dist/web1.exe
51874490        obj/Release/net9.0/win-x64/native/web1.obj

# native
> rm -r -fo obj
> $env:DOTNET_USE_LLVM_OBJWRITER="1"
> dotnet9 publish -c Release -o dist2
> wsl du -b dist2/web1.exe obj/Release/net9.0/win-x64/native/web1.obj

9241088 dist2/web1.exe
55142434        obj/Release/net9.0/win-x64/native/web1.obj
```

**Comment by am11** [comment]
cc @filipnavara

**Comment by filipnavara** [comment]
Thanks for filing it. I'll look into it soon.

**Comment by filipnavara** [comment]
Preliminary examination seems to be that the difference is the .rdata section of the executable. The .rdata sections in the source .obj files have identical size. There's multiple .rdata section with COMDAT symbols so it's possible that some folding is not taking place while it should. However, the regression is more likely to come from the .xdata (exception data) section which happens to be bigger in the .obj file produced by the managed code. I'll check that.
