### ISSUE TITLE
ILDasm crashes when dumping statistics for an invalid module

### ISSUE THREAD

**Issue by yitzhaks** [dotnet/runtime#9668]
I had the pleasure of investigating an InvalidProgramException our product was throwing when loading one of our modules. As a step in that investigation I wanted to compare the IL of the module with a known good version, so I tried dumping both version with ILDasm. The valid module worked as expected, but ILDasm crashed when dumping the module statistics for the invalid one.

The code in question is (crashing line marked with arrow) from [dasm.cpp:](https://github.com/dotnet/coreclr/blob/master/src/ildasm/dasm.cpp)
```cpp
                BYTE *sectsBegin = (BYTE *) (pMethod->GetCode() + pMethod->GetCodeSize());
                const COR_ILMETHOD_SECT *pSect = pMethod->GetSect();
                const COR_ILMETHOD_SECT *pOldSect;
                if (pSect != NULL) {
                    // Keep skipping a pointer past each section.
                    do
                    {
                        pOldSect = pSect;
->                      if (((COR_ILMETHOD_SECT_FAT *) pSect)->GetKind() & CorILMethod_Sect_FatFormat)
                        {
                            ++fatSections;
                            pSect = (COR_ILMETHOD_SECT *)((BYTE *) pSect + ((COR_ILMETHOD_SECT_FAT *) pSect)->GetDataSize());
                        }
                        else
                        {
                            ++smallSections;
                            pSect = (COR_ILMETHOD_SECT *)((BYTE *) pSect + ((COR_ILMETHOD_SECT_SMALL *) pSect)->DataSize);
                        }
                        pSect = (COR_ILMETHOD_SECT *) (((UINT_PTR) pSect + 3) & ~3);
                    }
                    while (pOldSect->More());
```

As far as I can tell (by examining pOldSect), one of the sections has an invalid data size, which leads to pSect pointing to a junk address after processing the invalid section.

I can share the module and/or crash dump if that would help.

**Comment by briansull** [comment]
Need a repro for this issue.

**Comment by danmosemsft** [comment]
@yitzhaks I'm guessing you no longer have your repro 2.5 years on..

**Comment by yitzhaks** [comment]
@danmosemsft, surprisingly enough I still have the repro, but can't share it publicly. Is there a way to share it with you privately?

**Comment by danmosemsft** [comment]
If you want to share a file securely, we recommend you create an issue at [Dev Community](https://developercommunity.visualstudio.com/spaces/61/index.html) for .NET Framework (even though this isn't for .NET Framework), attach the file, and share the link to the issue here. 

Or if email is secure enough (your decision) then @briansull might share his address.

**Comment by briansull** [comment]
Yes, I can share my email address: briansul @ microsoft dot com

**Comment by yitzhaks** [comment]
@briansull yup, that's already mentioned in your GitHub profile, so I took the liberty to email you the repro yesterday.

**Comment by TIHan** [comment]
It has been a few years since this has been looked at. @yitzhaks , was this ever resolved? If you have a simpler repo, that would be best.

**Comment by yitzhaks** [comment]
I am not aware of any resolution. Unfortunately, in the years that passed I lost the repro, so unless @briansull still has it there's not much we can do here.

**Comment by TIHan** [comment]
That's unfortunate. While we definitely should not have ILDASM crash, if there isn't a repo then this issue should be closed. We can re-open this and/or file a new issue if it comes up again.
