### ISSUE TITLE
X509Certificates tests fail with PlatformNotSupportedException on Apple devices

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#96690]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=519095
Build error leg or test failing: System.Security.Cryptography.X509Certificates.Tests.CertTests.PublicPrivateKey_IndependentLifetimes_DSA
Pull request: https://github.com/dotnet/runtime/pull/96658

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "System.PlatformNotSupportedException : Operation is not supported on this platform.   Exception stack traces:    at System.Security.Cryptography.DSA.CreateCore",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=519095
**Error message validated:** `System.PlatformNotSupportedException : Operation is not supported on this platform.   Exception stack traces:    at System.Security.Cryptography.DSA.CreateCore`
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 1/9/2024 4:11:23 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[519644](https://dev.azure.com/dnceng-public/public/_build/results?buildId=519644)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=519644&view=ms.vss-test-web.build-test-results-tab&runId=12207790&resultId=203403)|dotnet/runtime#96684|
|[519095](https://dev.azure.com/dnceng-public/public/_build/results?buildId=519095)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=519095&view=ms.vss-test-web.build-test-results-tab&runId=12195038&resultId=203442)|dotnet/runtime#96658|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|2|2|2|

**Comment by mkhamoyan** [comment]
This is not related to https://github.com/dotnet/runtime/pull/96658 , but https://github.com/dotnet/runtime/pull/96685 .
