### ISSUE TITLE
Mono JIT being called each time a function pointer is called

### ISSUE THREAD

**Issue by bholmes** [dotnet/runtime#96710]
### Description

Filing a bug to see if we can patch the stub.

There are 2 scenarios in main.  The ICallScenario shows that even if you JIT compile an icall wrapper before getting the address, that address will point to the stub.

### Reproduction Steps

Compile and run the following program with the Mono runtime.
Observe the number of times mono_jit_compile_method_with_opt is called for the Add or GetAllocatedBytesForCurrentThread methods. 

```cs

using System;
internal class Program
{

    static int Add(int a, int b)
    {
        return a + b;
    }

    private unsafe static void Main(string[] args)
    {
        ManagedScenario();
        ICallScenario();
    }

    static void ManagedScenario()
    {
        // Assign a function pointer to a managed method and call it from a loop
        // Set a breakpoint in mono_jit_compile_method_with_opt at the lookup_start label
        // The break will hit for each call to Add
        // Can we find a way to avoid calling jit_compile for this method after the first time?
        ManagedTest();
    }

    static void ICallScenario()
    {
        // Call an icall function then assign it to a function pointer and call from loop
        // Set a breakpoint in mono_jit_compile_method_with_opt at the lookup_start label
        // The break will hit for each call to GetAllocatedBytesForCurrentThread
        // For some reason icalls are being directed to the JIT even when they are called/compiled before getting the address
        GC.GetAllocatedBytesForCurrentThread();
        ICallTest();
    }

    private unsafe static void ManagedTest()
    {
        var fnPtr = (delegate*<int, int, int>)&Add;
        for (var i = 0; i < 10; ++i) { fnPtr(1,2); }
    }

    private unsafe static void ICallTest()
    {
        var fnPtr = (delegate*<long>)&GC.GetAllocatedBytesForCurrentThread;
        for (var i = 0; i < 10; ++i) { fnPtr(); }
    }
}
```

### Expected behavior

mono_jit_compile_method_with_opt only be called once (per process) for Add and once for GetAllocatedBytesForCurrentThread

### Actual behavior

mono_jit_compile_method_with_opt is called each time these methods are called.

### Regression?

No

### Configuration

Running with Mono on desktop Linux, but I expect this with any platform that JITs.

**Comment by steveisok** [comment]
@bholmes did zoltan's PR fix this for you?

**Comment by bholmes** [comment]
@steveisok yes we have the patch in our Mono fork and have resolved the Unity issue.  Thanks!
