### ISSUE TITLE
[Blazor] Unable to debug in lazy loaded assemblies

### ISSUE THREAD

**Issue by standbych** [dotnet/runtime#96736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

breakpoints will not be hit in a assemblies loaded by lazy loading in .NET 8.
In previous versions (.NET 7) it works as expected. If the assemblies are not loaded by lazy loading the debugger will hit.

### Expected Behavior

breakpoints should be hit in assemblies lazy loaded in .NET 8

### Steps To Reproduce

There are two commits in this repo: https://github.com/standbych/bug-blazor-lazyload-net8/settings
initial commit: .net7 *debugger works as expected*
migration commit: .net8 *debugger does not work in lazy loaded assemblies*

### Exceptions (if any)

![image](https://github.com/dotnet/aspnetcore/assets/54892597/3d2421c0-f740-442d-88cb-9c2c7bf63095)

### .NET Version

8.0.100

### Anything else?

VS 17.8.3

**Comment by thaystg** [comment]
This is related to webcil, as a workaround you can disable webcil in your projects:
`<WasmEnableWebcil>false</WasmEnableWebcil>`

**Comment by Arsync** [comment]
Unable to debug in lazy loaded assemblies. Again, but when `Remote Authentication` failed.
Forked from previous author, webcli disabled:

https://github.com/Arsync/bug-blazor-lazyload-net8

When authentication failed for some reasons (authority not found, login required, etc),
breakpoint in lazy module will work only at first page, but when you try to open other pages in that module, breakpoints will be hit only if target page was changed from last debug session.

Project has fake authority, "configured" in Program.cs, let it as is.

Steps to reproduce:
1. Launch server project, it will navigate directly to `/lazy` page with 'launchUrl' defined in `launchSettings.json`
2. Breakpoint will be hit at first page (always).
2. Click at link "Now click here" and navigate to the '/lazy-second' page
3. Perhaps, at first launch breakpoint will be hit.
4. Re-run debugging, now the second page will not stopped at line 28.
5. Do some text changes in LazySecondPage.razor and run project again
6. Breakpoint matched
7. Repeat steps 4-7
