### ISSUE TITLE
[NETSDKE2E][Regression] With VSCode on Linux, debugging a .NET 9 project is failed with Unknown Error 0x80131c3c Unable to attach to CoreCLR.

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/runtime#96747]
### Description

With VSCode on Linux, debugging a .NET 9 project is failed with Unknown Error 0x80131c3c Unable to attach to CoreCLR.

### Reproduction Steps

1. On Ubuntu 23.04 or 20.04, install VSCode with C# extension or CDK extension.
2. Install .NET 9.0.100-alpha.1.24059.25
3. Create a console app and open its folder via VSCode
4. Debug it and observe

### Expected behavior

Debugging works fine.

### Actual behavior

Debugging is failed with Unknown Error 0x80131c3c Unable to attach to CoreCLR.
![image](https://github.com/dotnet/runtime/assets/1578239/912a7d05-134e-4367-87a5-e1c3f4274ace)

### Regression?

This issue is not repro with previous build .NET 9.0.100-alpha.1.24053.14

### Configuration

OS: Ubuntu 23.04 X64 or Ubuntu 20.04
VS Code version:1.85.1
C# Extension version:2.14.8
.NET SDK: 9.0.100-alpha.1.24059.25 from [dotnet/installer: .NET SDK Installer (github.com)](https://github.com/dotnet/installer)

`dotnet --info` output:
.NET SDK:
 Version:           9.0.100-alpha.1.24059.25
 Commit:            db253f6088
 Workload version:  9.0.100-manifests.d08d94a9

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  23.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/9.0.100-alpha.1.24059.25/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      9.0.0-alpha.1.24058.10
  Architecture: x64
  Commit:       b4ec422386

.NET SDKs installed:
  9.0.100-alpha.1.24059.25 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-alpha.1.24058.9 [/usr/share/dotnet/shared/Micsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-alpha.1.24058.10 [/usr/share/dotnet/shared/Microft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by tommcdon** [comment]
This looks like a regression on main.  The `0x80131c3c` error is `CORDBG_E_DEBUG_COMPONENT_MISSING`.

**Comment by tommcdon** [comment]
The root cause is that that `dlopen` fails with the following error: `undefined symbol: minipal_get_length_utf16_to_utf8` in `LOADLoadLibraryDirect`:
https://github.com/dotnet/diagnostics/blob/e01dddacec76df94dbd83b15d8b55aa5a6bb3b9e/src/shared/pal/src/loader/module.cpp#L1260

**Comment by tommcdon** [comment]
Regression caused by #96099
