### ISSUE TITLE
 Blazor WASM (8.0 RC2) does not work on iOS 15.8

### ISSUE THREAD

**Issue by MorneZaayman** [dotnet/runtime#96748]
@mwarvik Sorry for late reply, I was OOF. Can you please verify if this site loads for you https://maraf.github.io/dotnet-wasm-nosimd/ ? It's a .NET on WASM template with SIMD disabled. It works in my iOS 15.5 simulator

_Originally posted by @maraf in https://github.com/dotnet/runtime/issues/94231#issuecomment-1839252723_

I would like to reopen this. I can replicate that site not working when using the WebKit browser provided by Playwright. This is also breaking my application when running on certain iOS devices.

**Comment by maraf** [comment]
@MorneZaayman Can you please extra a simple repro for the WebKit and Playwright case? On the iOS devices, based on the issue title, you are hitting the issue with iPhone with iOS 15.8, right?

**Comment by MorneZaayman** [comment]
The easiest is to run `.\playwright.ps1 wk` after installing Playwright in a unit test project. Then go to https://maraf.github.io/dotnet-wasm-nosimd in the browser. You'll see it just crashes the page. I've also attached a gif showing the console.
![a8cDW7IkQ8](https://github.com/dotnet/runtime/assets/25976312/bcf4d186-a374-4e0f-bd38-580301adb420)

**Comment by maraf** [comment]
Thank you. It seems that webkit installed by playwright doesn't support WebAssembly at all

![image](https://github.com/dotnet/runtime/assets/10020471/29685931-4f11-4165-95fc-fd288d7fe940)

I dunno whether it's disabled somewhere or that the webkit doesn't support
