### ISSUE TITLE
NuGet authenticate task used by jitrollingbuild is deprecated

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#96745]
The internal jitrollingbuild pipeline is hitting this warning:
```
Task 'NuGet authenticate' version 0 (NuGetAuthenticate@0) is deprecated. This task will be removed. From January 31, 2024, onwards it may no longer be available.
```
We should fix this before the specified date.

cc @dotnet/jit-contrib

**Comment by akoeplinger** [comment]
I fixed the repo-local usages withhttps://github.com/dotnet/runtime/pull/96651, the remaining usages are in eng/common so will be fixed with the next arcade update.

**Comment by akoeplinger** [comment]
Sure. https://github.com/dotnet/runtime/pull/95904 is the PR to watch (it's currently blocked).

**Comment by akoeplinger** [comment]
This if fixed now.
