### ISSUE TITLE
[API Proposal]: Parse RFC 1779 compliant Distinguished Names

### ISSUE THREAD

**Issue by enzian** [dotnet/runtime#96750]
### Background and motivation

When X.509 are used in a mTLS use case, the client will provide a certificate with a `Subject` name:

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            3c:8a:c0:93:d5:d3:d2:7f:a2:25:55:37:df:2a:97:c9:48:4a:4e:c3
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: C=AU, ST=Some-State, O=Internet Widgits Pty Ltd
        Validity
            Not Before: Jan  9 22:33:24 2024 GMT
            Not After : Oct  5 22:33:24 2026 GMT
        Subject: O=org, OU=group, CN=username
[truncated]
```

This name is usually formatted in the form of a Distinguished Name (DN) and hold identifying information about whom the certificate was issued to. It is common for servers to the use the DN to get the information it needs to authorize the client (like the name and group).

The existing API `X509Certificate2` exposes a the `Subject` field as a string. This is where a new API should support in parse the Distinguished Name as outlined in [RFC 1779](https://www.rfc-editor.org/rfc/rfc1779.html#section-2.2)

If there is a need to get information in the DN, an implementation along the lines of the following needs to be built:

```fsharp
let subjectNameRegex = new System.Text.RegularExpressions.Regex(@"(?<name>\w*)=(?<value>\w*)")

[...]

events.OnCertificateValidated <- fun context ->
let keys = 
        subjectNameRegex.Matches(context.ClientCertificate.Subject)
        |> Seq.cast<System.Text.RegularExpressions.Match>
        |> Seq.map (fun m -> m.Groups.["name"].Value, m.Groups.["value"].Value)
        |> Map.ofSeq
    let claims = [
        new Claim(
            ClaimTypes.Name,
            keys.["CN"],
            ClaimValueTypes.String, context.Options.ClaimsIssuer)
        new Claim(
            ClaimTypes.GroupSid,
            keys.["OU"],
            ClaimValueTypes.String, context.Options.ClaimsIssuer)
    ]
    let identities = [new ClaimsIdentity(claims, context.Scheme.Name)]
    context.Principal = new ClaimsPrincipal(identities)

    context.Success()
    System.Threading.Tasks.Task.CompletedTask
```

### API Proposal

```csharp
namespace System.Security.Cryptography.X509Certificates

public class DistinguisedNameExtensions
{
    public static (IDictionary<string, string>, bool) TryParseDistinguishedName(this string distinguishedName)
    public static string ToDistinguishedName (this IDictionary<string, string> components)
}
```

### API Usage

With these new APIs the handler for client certificates could now be writter much more concisely:

```fsharp
fun context ->
    let (name_components, parsed) = context.ClientCertificate.Subject.TryParseDistinguishedName()
    // error handling based on the `parsed` variable
    let claims = [
        new Claim(
            ClaimTypes.Name,
            name_component.["CN"],
            ClaimValueTypes.String, context.Options.ClaimsIssuer)
        new Claim(
            ClaimTypes.GroupSid,
            name_component.["OU"],
            ClaimValueTypes.String, context.Options.ClaimsIssuer)
    ]
    let identities = [new ClaimsIdentity(claims, context.Scheme.Name)]
    context.Principal = new ClaimsPrincipal(identities)
    context.Success()
    System.Threading.Tasks.Task.CompletedTask
```

The API could also be used to compare DNs when validating custom certificate chains.

### Alternative Designs

An alternative design could be to add a new field in `X509Certificate2` which would contain the split DN which is more intrusive and complex as it requires the DN split to occur even if there is not actual need for it and would increase the complexity of `X509Certificate2` with little return.

With this proposal, whether or not the DN is split into it's parts or not remains up to the developer who is free to do it on an as-needed basis.

### Risks

As the proposed API is purely additive and touches none of the existing APIs in either form or function this would be a non-breaking change, there is no risk of impacting existing functionality or causing performance issues for anyone not using the API explicity.

**Comment by enzian** [comment]
Hey, yes, very close actually. We still have to jump through a few hoops:

```fsharp
let rdn = context.ClientCertificate.SubjectName.EnumerateRelativeDistinguishedNames()
let kvs = rdn |> Seq.map (fun x -> x.GetSingleElementType().FriendlyName, x.GetSingleElementValue()) |> Map.ofSeq
```

However this one line is not enough of a case for a new API.

**Comment by enzian** [comment]
> That may not be something you need to consider or not, but that is one reason the existing API is designed as it is. Another other is that some people may care about the order in which RDNs are encoded.

I absolutely see the reason why the API is designed the way it is - makes sense! Close this then?

**Comment by vcsjones** [comment]
> Close this then?

Seems to be the appropriate thing here. Nevertheless thanks for taking the time to write an API proposal!

**Comment by bartonjs** [comment]
Be careful depending on `FriendlyName` as it's not always the same across all OSes, and in some cases it can depend on the user's UI language.

It's safe enough (on any given version of .NET) to use the values in https://github.com/dotnet/runtime/blob/72db600a20d581fdc6776edce1863bcf8da0b1cd/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/OidLookup.cs#L170-L274 (or the equivalent segment for any particular version of .NET); but I definitely recommend any real logic (especially logic for a security context) to do matching based on the `oid.Value` value.
