### ISSUE TITLE
[.NET 8.0.1] <PublishTrimmed> no longers works but throws build process for an infinite loop

### ISSUE THREAD

**Issue by DierkDroth** [dotnet/runtime#96766]
### Description

@vitek-karas @sbomer this is in reference to #94831 - which appears not be fixed.

I just updated to dotnet 8.0.1 and found that the issue still is not resolved: I re-applied `<PublishTrimmed>true</PublishTrimmed>` to the project file and found that the build still does not terminate: I aborted the build after 30 minutes - it took 1-2 minutes with .NET 7.

The is pretty much the same binary - apart from a few minor changes - still the same size and complexity.

What am I missing?	

### Reproduction Steps

see above

### Expected behavior

see above

### Actual behavior

see above

### Regression?

yes

### Known Workarounds

none

### Configuration

see above

**Comment by vitek-karas** [comment]
The change to servicing (8.0) has been merged only last week, so it could not have made the 8.0.1 release. I assume it should be in the next one.

**Comment by DierkDroth** [comment]
Thanks for your feedback @vitek-karas.
