### ISSUE TITLE
[8.0] runtime-extra-platforms: ios and tvos - Trimming assemblies requires .NET Core 3.0 or higher

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#96793]
### Error Blob

```json
{
  "ErrorMessage": "Trimming assemblies requires .NET Core 3.0 or higher",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": true
}
```

### Reproduction Steps

- Seems to affect ios and tvos queues: `ios-arm64 Release AllSubsets_Mono_RuntimeTests`, `tvos-arm64 Release AllSubsets_NativeAOT_RuntimeTests`, `tvos-arm64 Release AllSubsets_Mono_RuntimeTests`
- Affected step: `Build Tests`
- Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=521016&view=logs&j=6ad81d5f-e956-5767-2437-61a9fc4dc8db&t=abc62672-a7a9-524c-ea0a-8da0338b9173
- Output:
```
/Users/runner/.dotnet/sdk/8.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1124: Trimming assemblies requires .NET Core 3.0 or higher. [/Users/runner/work/1/s/src/tests/Common/XUnitWrapperGenerator/XUnitWrapperGenerator.csproj] [/Users/runner/work/1/s/src/tests/build.proj]
##[error]/Users/runner/.dotnet/sdk/8.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1124: Trimming assemblies requires .NET Core 3.0 or higher. [/Users/runner/work/1/s/src/tests/Common/XUnitWrapperGenerator/XUnitWrapperGenerator.csproj]
    Nothing to do. None of the projects specified contain packages to restore.
/Users/runner/work/1/s/src/tests/build.proj(543,5): error MSB3073: The command ""/Users/runner/.dotnet/dotnet" restore -r tvos-arm64 Common/XUnitWrapperGenerator/XUnitWrapperGenerator.csproj  /p:SetTFMForRestore=true /p:TargetOS=tvos /p:TargetArchitecture=arm64 /p:Configuration=Release /p:CrossBuild=" exited with code 1.
##[error]src/tests/build.proj(543,5): error MSB3073: The command ""/Users/runner/.dotnet/dotnet" restore -r tvos-arm64 Common/XUnitWrapperGenerator/XUnitWrapperGenerator.csproj  /p:SetTFMForRestore=true /p:TargetOS=tvos /p:TargetArchitecture=arm64 /p:Configuration=Release /p:CrossBuild=" exited with code 1.

Build FAILED.
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=521016
**Error message validated:** `Trimming assemblies requires .NET Core 3.0 or higher`
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 1/10/2024 6:05:59 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[526413](https://dev.azure.com/dnceng-public/public/_build/results?buildId=526413)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/526413/logs/628)||
|[526231](https://dev.azure.com/dnceng-public/public/_build/results?buildId=526231)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/526231/logs/756)||
|[526046](https://dev.azure.com/dnceng-public/public/_build/results?buildId=526046)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/526046/logs/741)||
|[525794](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525794)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/525794/logs/650)||
|[525544](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525544)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/525544/logs/615)||
|[525537](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525537)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/525537/logs/679)||
|[524696](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524696)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/524696/logs/1370)||
|[523644](https://dev.azure.com/dnceng-public/public/_build/results?buildId=523644)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/523644/logs/442)||
|[523004](https://dev.azure.com/dnceng-public/public/_build/results?buildId=523004)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/523004/logs/939)||
|[520498](https://dev.azure.com/dnceng-public/public/_build/results?buildId=520498)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/520498/logs/1329)||
|[522376](https://dev.azure.com/dnceng-public/public/_build/results?buildId=522376)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/522376/logs/469)||
|[521035](https://dev.azure.com/dnceng-public/public/_build/results?buildId=521035)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/521035/logs/685)||
|[521016](https://dev.azure.com/dnceng-public/public/_build/results?buildId=521016)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/521016/logs/557)||
|[520561](https://dev.azure.com/dnceng-public/public/_build/results?buildId=520561)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/520561/logs/559)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|11|14|

**Comment by carlossanlop** [comment]
I found it in this PR: https://github.com/dotnet/runtime/pull/96724

**Comment by akoeplinger** [comment]
This was fixed in main with https://github.com/dotnet/runtime/pull/91542, I started the backport.

**Comment by akoeplinger** [comment]
Backport got merged: https://github.com/dotnet/runtime/pull/96994
