### ISSUE TITLE
Document the commands required to resolve ApiCompat issues

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#968]
It doesn't look like we currently have the commands/steps required to resolve ApiCompat issues in the docs section anywhere.

It would be useful to ensure that these are documented so that users can easily reference the docs and workaround the issue where necessary.
* As a nicety, we could also update the task failure messages to link to said documentation

**Comment by ViktorHofer** [comment]
Stumbled over this while triaging the backlog. @ericstj as you have most context here, would you mind documenting the switches, presumably in Arcade where the tool lives and link to it?

**Comment by ericstj** [comment]
@ViktorHofer I already did that here: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.ApiCompat/README.md
