### ISSUE TITLE
Missing String.IndexOfAny method overload for System.Buffers.SearchValues<T>

### ISSUE THREAD

**Issue by okyrylchuk** [dotnet/runtime#96813]
### Description

In the [.NET 8 release notes](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8#performance-focused-types), there is an introduction of the `System.Buffers.SearchValues<T>` type.

There is information that the `String.IndexOfAny` and `MemoryExtensions.IndexOfAny` methods have overloads to accept the instance of the `System.Buffers.SearchValues<T>` type.

I was trying to play with it and discovered that `String.IndexOfAny` doesn't have such an overload. I didn't check the `MemoryExtensions.IndexOfAny` method.

### Reproduction Steps

```
using System.Buffers;

var @char = 'O';
var searchChar = new ReadOnlySpan<char>(ref @char);
var searchValue = SearchValues.Create(searchChar);

var searchedString = "aaaaOaaaa";

searchedString.IndexOfAny(searchValue);
```

### Expected behavior

The `String.IndexOfAny` method should have the overload to accept the `System.Buffers.SearchValues<T>` type.

### Actual behavior

There  `String.IndexOfAny` method doens't have the the overload to accept the `System.Buffers.SearchValues<T>` type.

https://github.com/dotnet/runtime/blob/07fbf073848b141e252a2718262acef010efedd1/src/libraries/System.Private.CoreLib/src/System/String.Searching.cs#L111

### Configuration

- .NET 8.0.101
- Windows 11 Version 10.0.22621 Build 22621
- x64 architecture

**Comment by stephentoub** [comment]
The release notes are incorrect; the support for this is over spans via the extensions methods in MemoryExtensions.

In your example, you would change:
```C#
searchedString.IndexOfAny(searchValue);
```
to instead be:
```C#
searchedString.AsSpan().IndexOfAny(searchValue);
```

I've put up https://github.com/dotnet/docs/pull/39084 to fix the release notes.

**Comment by okyrylchuk** [comment]
@stephentoub, thanks for clarification. I'm closing the issue!
