### ISSUE TITLE
XUnitLogChecker: Unable to find dumps in Linux

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#96818]
I created a test PR to see the status of XUnitLogChecker. https://github.com/dotnet/runtime/pull/96806

I discovered that XUnitLogChecker is unable to find dumps in the expected directory in Unix. Did anything change recently? This was working in my last PR.

Examples:

-	Checked coreclr linux_musl arm release: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-96806-merge-bcf715a4513549059e/System.IO.Compression.Brotli.Tests/1/console.829a3ceb.log?helixlogtype=result
-	Checked coreclr linux_musl arm64 release: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-96806-merge-0cdd72f5aa8d4e8ab9/System.IO.Compression.Brotli.Tests/1/console.e65b9872.log?helixlogtype=result
-	Checked coreclr linux arm64 debug: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-96806-merge-07c6060c04104f1a93/System.IO.Compression.Brotli.Tests/1/console.6f7834a8.log?helixlogtype=result
-	Release coreclr linux_musl x64 debug: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-96806-merge-11ee917c93f1447592/System.IO.Compression.Brotli.Tests/1/console.0abc73fd.log?helixlogtype=result
-	Checked coreclr linux_musl x64 debug: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-96806-merge-c8d99cbd262d4c54b4/System.IO.Compression.Brotli.Tests/1/console.f51a0833.log?helixlogtype=result
-	Release coreclr linux x64 debug: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-96806-merge-ed71aaed398a4c2c87/System.IO.Compression.Brotli.Tests/1/console.e692ee99.log?helixlogtype=result
-	Checked coreclr linux x64 release: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-96806-merge-5b63e51c591547a992/System.IO.Compression.Brotli.Tests/1/console.2076f615.log?helixlogtype=result

@ivdiazsa @hoyosjs @JulieLeeMSFT

**Comment by ericstj** [comment]
@carlossanlop are you setting DOTNET variables to trigger dump creation?  I think we were supposed to set DOTNET_DbgMiniDumpName and maybe some others.  cc @hoyosjs

**Comment by carlossanlop** [comment]
Yes, they're being set:

https://github.com/dotnet/runtime/blob/31fa0794d63a41a1b5db50bc4a5e3eadb6a786eb/eng/testing/RunnerTemplate.sh#L125-L127

**Comment by ericstj** [comment]
I see - so given the docs of those variables they should produce a dump, but they didn't.  Looks like all those logs have this:
```
[createdump] Gathering state for process 56 dotnet
[createdump] Crashing thread 0047 signal 11 (000b)
[createdump] Writing crash report to file /home/helixbot/dotnetbuild/dumps/coredump.56.dmp.crashreport.json
[createdump] Crash report successfully written
waitpid() returned successfully (wstatus 0000008b) WEXITSTATUS 0 WTERMSIG b
```

@hoyosjs wouldn't that indicate a problem with CoreCLR's dump writing logic?  Looks like it's only writing `.crashreport.json` and not the `.dmp`

**Comment by ericstj** [comment]
Have a look at https://dev.azure.com/dnceng-public/public/_build/results?buildId=522611&view=ms.vss-test-web.build-test-results-tab&runId=12281022&paneView=debug&resultId=207997
There are dumps captured and uploaded - they were probably configured as system dumps.  @hoyosjs - could that be what's going on?  Some system setting is taking precedence over the environment variables?

**Comment by hoyosjs** [comment]
The environment variable configured dumps happen prior to process teardown. That means their dump, which is declared successful, happens before system dump.

**Comment by ericstj** [comment]
But there was no dump created -- it only created a report.  Could it be that `createdump` has a bug here?
https://github.com/dotnet/runtime/blob/54530c73d7e9f044ad4205338efb9d81f9dc8edb/src/coreclr/debug/createdump/createdumpunix.cpp#L74-L78

Or do you think someone set https://github.com/dotnet/runtime/blob/54530c73d7e9f044ad4205338efb9d81f9dc8edb/docs/design/coreclr/botr/xplat-minidump-generation.md?plain=1#L68?

I couldn't find any evidence of the latter - so this really looks like a problem with createdump.

**Comment by tommcdon** [comment]
> But there was no dump created -- it only created a report. Could it be that createdump has a bug here?

@mikem8361

**Comment by ericstj** [comment]
Maybe the test scripts could clear the `DOTNET_EnableCrashReportOnly` variable just to rule that out.  I didn't see anyone setting this in any dotnet repo - but I can't say I trust my search to catch every bit of code that runs on the helix machines.

**Comment by mikem8361** [comment]
Is there anyway to turn on createdump logging with DOTNET_CreateDumpVerboseDiagnostics?  That should tell us a lot more about what is going on.

**Comment by ericstj** [comment]
I think those can just be set in https://github.com/carlossanlop/runtime/blob/TestXULC/eng/testing/RunnerTemplate.sh#L125-L127 and it should give info.

I went ahead and gave this a try by making the edit directly in @carlossanlop's branch. https://github.com/carlossanlop/runtime/commit/8088cb355b136535ed275491c7b05d29265f45cd

We can observe how that impacts the PR validation: https://github.com/dotnet/runtime/pull/96806

**Comment by mikem8361** [comment]
It looks like after the createdump logging was enabled, the dumps in the various runs I looked at were successful.  The logging did expose some sign extension bugs on arm32 which I'm fixing, but the rest of the platforms looked ok.

**Comment by ericstj** [comment]
I went ahead and removed the `DOTNET_CreateDumpVerboseDiagnostics` setting.  We can see if the problem returns.  If it does then perhaps we'll need to look into other ways to understand why the dumps aren't created.

**Comment by tommcdon** [comment]
Hi @ericstj, just checking in - please let us know if there is any further action for the diagnostics team or if this issue can be closed.

**Comment by ericstj** [comment]
Tagging @carlossanlop to help as well.

You should be able to look at the linked PR to see if its producing dumps or not.  That's effectively testing createdump on the CI machines.  I just had a look and it seems to me it's not producing the dumps:
https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-96806-merge-a9ff7e2f92b842e080/System.IO.Compression.Brotli.Tests/1/console.8faf5d93.log?helixlogtype=result

As you can see, createdump is doing something:
```
[createdump] Gathering state for process 25502 dotnet
[createdump] Crashing thread 63ae signal 11 (000b)
./RunTests.sh: line 180: 25502 Segmentation fault      (core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.IO.Compression.Brotli.Tests.runtimeconfig.json --depsfile System.IO.Compression.Brotli.Tests.deps.json xunit.console.dll System.IO.Compression.Brotli.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
```

But still no `.dmp` file produced.
```
No dumps found in /home/helixbot/dotnetbuild/dumps.
```

I think the next steps might be to iterate in that PR to test that createdump will work correctly in the CI machines.

**Comment by ericstj** [comment]
I wonder if the system dump being produced interferes with createdump, and enabling more verbose logging slows down createdump enough so that the system dump process no longer interferes?  Just guessing as I don't know why createdump might not produce a dump at all even when running.

**Comment by JulieLeeMSFT** [comment]
@carlossanlop, can you link the example PR that shows it does not create dump?

**Comment by ericstj** [comment]
Yeah, it's the same PR as before.  Check the linux coreCLR legs (the above is from an x64 one).

What I do to check is examine all failing tests, then look for the .dmp and the console log for the stack.
https://dev.azure.com/dnceng-public/public/_build/results?buildId=548264&view=ms.vss-test-web.build-test-results-tab

**Comment by mikem8361** [comment]
It looks like the test PR is successfully creating dumps.  Juan rebased it on the latest which had a remote stack unwinder fix.

**Comment by ericstj** [comment]
Confirmed, https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-96806-merge-48852c8dc9bb4f22bc/System.IO.Compression.Brotli.Tests/1/console.47cae588.log?helixlogtype=result

@mikem8361 @hoyosjs - could one of you link the PR that fixed this?  Are you putting tests in place to make sure it doesn't regress again?
