### ISSUE TITLE
[libs][iOS] AdvSimdEncode hits PlatformNotSupportedException

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#96828]
### Description

After https://github.com/dotnet/runtime/pull/95513 was merged, some tests that eventually invoke `EncodeToUtf8` such as https://github.com/dotnet/runtime/blob/31fa0794d63a41a1b5db50bc4a5e3eadb6a786eb/src/libraries/System.Collections/tests/Generic/PriorityQueue/PriorityQueue.PropertyTests.cs#L19 began failing with `PlatformNotSupportedException` on iOS/tvOS arm64 lanes. 
```
Test collection for System.Collections.Tests.PriorityQueue_PropertyTests
Test name: System.Collections.Tests.PriorityQueue_PropertyTests.HeapSort_Heapify_String
Exception messages: System.PlatformNotSupportedException : 
Exception stack traces:    at System.Runtime.Intrinsics.Arm.AdvSimd.Arm64.LoadVector128x3AndUnzip(Byte* address)
at System.Buffers.Text.Base64.EncodeToUtf8(ReadOnlySpan`1 bytes, Span`1 utf8, Int32& bytesConsumed, Int32& bytesWritten, Boolean isFinalBlock)
at System.Convert.ToBase64CharsLargeNoLineBreaks(ReadOnlySpan`1 bytes, Span`1 chars, Int32 charLengthRequired)
at System.Convert.ToBase64String(ReadOnlySpan`1 bytes, Base64FormattingOptions options)
at System.Convert.ToBase64String(Byte[] inArray)
at System.Collections.Tests.PriorityQueue_PropertyTests.GenString(Random random)
at System.Collections.Tests.PriorityQueue_PropertyTests.GenArray[String](Func`2 genElement, Random random)
at System.Collections.Tests.PriorityQueue_PropertyTests.<>c.<GetRandomStringArrays>b__16_0(Random random)
at System.Collections.Tests.PriorityQueue_PropertyTests.<GenerateMemberData>d__18`1[[System.String[], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
at System.Linq.Enumerable.SelectEnumerableIterator`2[[System.Object, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object[], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
```

It looks like `LoadVector128x3AndUnzip` is possibly the culprit, as https://github.com/dotnet/runtime/issues/84510 doesn't seem to account for mono.

### Reproduction Steps

On OSX with an iOS device
```bash
./build.sh -s mono+libs -os ios -arch arm64 -c debug
./dotnet.sh build src/libraries/System.Collections/tests/System.Collections.Tests.csproj /t:Test /p:TargetOS=ios /p:TargetArchitecture=arm64 /p:Configuration=Debug /p:DevTeamProvisioning=<dev team provisioning ID> /p:XunitMethodName=System.Collections.Tests.PriorityQueue_PropertyTests.HeapSort_Heapify_String /p:MonoEnableLLVM=true /p:RunAOTCompilation=true
```

### Expected behavior

Test doesn't fail with PlatformNotSupportedException

### Actual behavior

Various tests eventually that end up calling ` AdvSimd.Arm64.LoadVector128x3AndUnzip` on iOS/tvOS fail with `PlatformNotSupportedException`

### Regression?

Yes

### Known Workarounds

No-op `AdvSimdEncode` on mono

**Comment by mdh1418** [comment]
cc: @kunalspathak @SwapnilGaikwad @fanyang-mono @lambdageek

**Comment by kunalspathak** [comment]
@vargaz, @fanyang-mono - do you know what is needed on mono side? We did that previously for Store APIs in https://github.com/dotnet/runtime/pull/93223/files#diff-012b47a27abc5dbc9d2a0b6fdef4adec27fa207a7d2b53823a8bc80f6539f5af.

**Comment by vargaz** [comment]
Would suggest adding an ifdef MONO around that code until this is fixed.

**Comment by fanyang-mono** [comment]
There is not software fallback codepath for `AdvSimd.Arm64.LoadVector128x3AndUnzip`. When it is not intrinsified by the runtime, it will throw `System.PlatformNotSupportedException`. Current solution would be avoid using `AdvSimd.Arm64.LoadVector128x3AndUnzip` and other new API's in https://github.com/dotnet/runtime/issues/84510 for BCL methods when using Mono runtime, until they are implemented by Mono.

**Comment by kunalspathak** [comment]
> Current solution would be avoid using `AdvSimd.Arm64.LoadVector128x3AndUnzip` and other new API's in #84510 for BCL methods when using Mono runtime, until they are implemented by Mono

Should we create an issue to implement these or is it already captured somewhere?

**Comment by fanyang-mono** [comment]
@kunalspathak I've created one to track that work. https://github.com/dotnet/runtime/issues/93081

**Comment by jeffhandley** [comment]
With #93081 open, is there anything more to do on this issue or can it be closed?

**Comment by fanyang-mono** [comment]
I will run this test locally to see if it is passing now. If so, we could close this issue. Since https://github.com/dotnet/runtime/issues/93081 has been completed.

**Comment by tannergooding** [comment]
@lambdageek, were you able to complete the testing?

I did some basic testing locally and it looked to be working as expected

**Comment by tannergooding** [comment]
Going to close this as the local validation shows its no longer an issue and I don't see failures in recent CI runs.

Please reopen if the issue repros anywhere else.
