### ISSUE TITLE
[browser][AOT] wasm-ld : error : initial memory too small

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#96840]
We are doing some estimate how much memory we need, based on binary size. I guess this estimate is no good in this case.

### Error Blob

```json
{
  "ErrorMessage": "wasm-ld : error : initial memory too small",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Reproduction Steps

[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-96696-merge-fd37d32dda2b4351a7/WasmTestOnBrowser-System.Numerics.Tensors.Tests/1/console.47b9495a.log?helixlogtype=result)

```
  Linking for initial memory $(WasmInitialHeapSize)=18874368 bytes. Set this msbuild property to change the value.
  Linking with emcc with -O2 -Wl,-O0 -Wl,--lto-O0. This may take a while ...
   "C:/helix/work/correlation/build/emsdk/node/14.18.2_64bit/bin/node.exe" C:\helix\work\correlation\build\emsdk\upstream\emscripten\src\compiler.js C:\Users\ContainerAdministrator\AppData\Local\Temp\tmppkdhk_2y.json --symbols-only
   "C:/helix/work/correlation/build/emsdk/upstream/bin\wasm-ld.exe" @C:\Users\ContainerAdministrator\AppData\Local\Temp\emscripten_w6_esgr0.rsp.utf-8
wasm-ld : error : initial memory too small, 19468624 bytes needed [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]

```

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=523499

cc @radical

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=523499
**Error message validated:** `wasm-ld : error : initial memory too small`
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 1/11/2024 2:03:08 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by radical** [comment]
the computed size from the binlog: `WasmInitialHeapSize=18939904`. And the error has `19468624 bytes needed`. difference of ~500kb.

**Comment by radical** [comment]
cc @radekdoulik
