### ISSUE TITLE
ILLink doesn't keep most specific static default interface method

### ISSUE THREAD

**Issue by sbomer** [dotnet/runtime#96855]
Similar to https://github.com/dotnet/runtime/issues/96516, but not fixed by https://github.com/dotnet/runtime/pull/96821. Here the base interface method is `virtual`, not `abstract`. The output is valid IL, but we don't keep the most specific default implementation.

```csharp
Console.WriteLine(M<Instance>());

static int M<T>() where T : IBase {
    return T.Value;
}

interface IBase {
    static virtual int Value => 0;
}

interface IDerived : IBase {
    static int IBase.Value => 1;
}

struct Instance : IDerived {
}
```

Trimmed output:

```
internal interface IBase
{
	static virtual int Value => 0;
}
internal interface IDerived : IBase
{
}
[StructLayout(0, Size = 1)]
internal struct Instance : IDerived, IBase
{
}
```

`dotnet run` prints `1`, but the trimmed app prints `0`.

**Comment by agocke** [comment]
@jtschuster can you take a look?
