### ISSUE TITLE
Some questions about profiler API

### ISSUE THREAD

**Issue by ww898** [dotnet/runtime#9685]
1. Our profiler excavates static variable values during the GC finished event and everything works perfectly till the GC where the first collectible assembly was silently unloaded. And we get crash after that. Now we disabled static variables for collectible assemblies. How to detect the moment during GC after that I can understand that the module was collected?

2. Our profiler gathers field names information in every object and assign it to incoming references. It's a bit complicated algorithm which depends on some current CLR undocumented behavior. The most important is: I expect that you process arrays from lower index to high one during GC. I did it because the alghoritm is O(x^2) and it's very very slow for large arrays.

The last one trouble is virtual references in objects from collectible assemblies. CLR add the virtual reference to `System.Reflection.LoadAllocator` object as first element of array of references in profiling API. It works for array types and most object types except following types and its inheritors (because there is the reflection in native for manages fields):
- `System.RuntimeType` see `m_keepalive`
- `System.Reflection.RuntimeAssembly` see `m_syncRoot`
- `System.Delegate` see `_methodBase`

Could you please make our live more simple - extend profiler API to get ability to get additional information for references such as:
- the array index
- the virtual collectible reference flag
- the real offset in object?

3. Add ability to resolve `ModuileID`+`mdTypeRef` to `ModuleID`+`mdTypeDef`.

**Comment by davmason** [comment]
Closing since it seems the question was answered
