### ISSUE TITLE
[wasm][wasi] No main function should be required when building a library

### ISSUE THREAD

**Issue by silesmo** [dotnet/runtime#96869]
### Description

Currently mono requires a main function when building for wasi. This shouldn't be required.

Related: https://github.com/dotnet/runtime/issues/96419

@AaronRobinsonMSFT @lewing @yowl @jsturtevant

### Reproduction Steps

Try to build example with `main` removed.
Example: https://github.com/silesmo/wasm-unmanaged-callers-bug/blob/main/mono-example/MonoEntrypoint.cs

### Expected behavior

No main function should be required for a library.

### Actual behavior

Main function is required.

**Comment by maraf** [comment]
Similar requirement tracked for browser in https://github.com/dotnet/runtime/issues/77191

**Comment by pavelsavara** [comment]
This should be triggered by `<OuputType>library</OutputType>`

**Comment by maraf** [comment]
One problem I encountered last year was IL trimmer complaining about missing root

**Comment by maraf** [comment]
We probably might need a different mechanism to compile library as wasm library. Currently we need `RuntimeIdentifier=*-wasm` + `OutputType=exe`.
- RuntimeIndentifier defines API surface that we can use (like JS interop)
- OutputType=exe ensures that wasm build happen.

In typicaly solution user would have several library projects and (one or some) exe projects that are applications. Those library projects might have RID set to *-wasm to enable wasm API. Currenly only the application projects would do the wasm build. Which is correct IMO. If we support wasm build on OutputType=library, it would a lot of additional steps in such solution.

Other parts of .NETE SDK include special steps in build by including a special SDKs in project definition (like `Microsoft.NET.Sdk.Razor`). We should do the same and do wasm library only when the project references `Microsoft.NET.Sdk.WebAssembly`.
