### ISSUE TITLE
Test failure: baseservices_threading._coverage_Nullref_CS_TimerNullRefEx_CS_TimerNullRefEx_/_coverage_Nullref_CS_TimerNullRefEx_CS_TimerNullRefEx_cmd

### ISSUE THREAD

**Issue by dotnet-mc-bot** [dotnet/runtime#9686]
Opened on behalf of @Sunny-pu

The test `baseservices_threading._coverage_Nullref_CS_TimerNullRefEx_CS_TimerNullRefEx_/_coverage_Nullref_CS_TimerNullRefEx_CS_TimerNullRefEx_cmd` has failed.

Error: Could not load file or assembly 'System.Threading.Timer, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
     (Exception from HRESULT: 0x80070002)
    Error compiling CS_TimerNullRefEx.org: Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
    Error: compilation failed for "CS_TimerNullRefEx.org" (0x80131621)
    
    
    Return code:      1
    Raw output file:      /home/helixbot/dotnetbuild/work/57f7ca23-1e3d-48fc-b2d3-384dc70b5c03/Work/11fe8906-5486-4188-900b-9ff33f49b953/Unzip/Reports\baseservices.threading\coverage\Nullref\CS_TimerNullRefEx\CS_TimerNullRefEx.output.txt
    Raw output:
    BEGIN EXECUTION
    in takeLock
    /home/helixbot/dotnetbuild/work/57f7ca23-1e3d-48fc-b2d3-384dc70b5c03/Payload/crossgen /Platform_Assemblies_Paths /home/helixbot/dotnetbuild/work/57f7ca23-1e3d-48fc-b2d3-384dc70b5c03/Payload:/home/helixbot/dotnetbuild/work/57f7ca23-1e3d-48fc-b2d3-384dc70b5c03/Work/11fe8906-5486-4188-900b-9ff33f49b953/Unzip/coverage/Nullref/CS_TimerNullRefEx/IL:/home/helixbot/dotnetbuild/work/57f7ca23-1e3d-48fc-b2d3-384dc70b5c03/Work/11fe8906-5486-4188-900b-9ff33f49b953/Unzip/coverage/Nullref/CS_TimerNullRefEx /in CS_TimerNullRefEx.org /out CS_TimerNullRefEx.exe
    Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
    Copyright (c) Microsoft Corporation.  All rights reserved.
    
    Crossgen failed with exitcode: 33
    in ReleaseLock
    Test Harness Exitcode is : 1
    
    To run the test:
    > set CORE_ROOT=/home/helixbot/dotnetbuild/work/57f7ca23-1e3d-48fc-b2d3-384dc70b5c03/Payload
    > /home/helixbot/dotnetbuild/work/57f7ca23-1e3d-48fc-b2d3-384dc70b5c03/Work/11fe8906-5486-4188-900b-9ff33f49b953/Unzip/coverage/Nullref/CS_TimerNullRefEx/CS_TimerNullRefEx.sh
    
    Expected: True
    Actual:   False

        Stack Trace:

        null
Build : Master - 20180207.13 (Ready-To-Run Tests)
Failing configurations:
- ubuntu.1604.amd64
  - x64

Details:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcoreclr~2Fmaster~2F/type/test~2Ffunctional~2Fr2r~2Fcli~2F/build/20180207.13/workItem/baseservices.threading.XUnitWrapper/analysis/xunit/baseservices_threading._coverage_Nullref_CS_TimerNullRefEx_CS_TimerNullRefEx_~2F_coverage_Nullref_CS_TimerNullRefEx_CS_TimerNullRefEx_cmd

**Comment by kouvel** [comment]
I wasn't able to repro the failure on a recent build and it looks like it hasn't occurred recently, closing
