### ISSUE TITLE
[wasm] Setting `WasmBuildNative` to false produces no output wasm binary

### ISSUE THREAD

**Issue by silesmo** [dotnet/runtime#96863]
### Description

Adding the following `<WasmBuildNative>false</WasmBuildNative>` to a property group in csproj and then building a project results in a successful build but no wasm binary is produces.

Related: https://github.com/dotnet/runtime/issues/96419

@AaronRobinsonMSFT @lewing @yowl @jsturtevant

### Reproduction Steps

Add `<WasmBuildNative>false</WasmBuildNative>` and to Numbers.csproj in example project found below and build.
https://github.com/silesmo/wasm-unmanaged-callers-bug/blob/main/mono-example/Numbers.csproj

### Expected behavior

I would expect a non AoT build to be performed and a wasm binary to be outputted.

### Actual behavior

Successful build but no wasm binary produced.

**Comment by radical** [comment]
Is this with a browser-wasm or wasi-wasm project?

**Comment by radical** [comment]
> Is this with a browser-wasm or wasi-wasm project?

This seems to be a wasi-wasm project. What was the build output?

**Comment by radical** [comment]
How did you try to build this? I can build it locally, and get:
````
$ ls bin/Debug/net9.0/wasi-wasm/AppBundle
csharp-wasm.runtimeconfig.json  node.mjs                        run-wasmtime.sh*
dotnet.wasm*                    run-node.sh*                    tmp/
```

Make sure you have the `wasi-experimental` workload.

**Comment by silesmo** [comment]
> How did you try to build this? I can build it locally, and get:
> 
> ```
> $ ls bin/Debug/net9.0/wasi-wasm/AppBundle
> csharp-wasm.runtimeconfig.json  node.mjs                        run-wasmtime.sh*
> dotnet.wasm*                    run-node.sh*                    tmp/
> ```
> 
> Make sure you have the `wasi-experimental` workload.
> ```

Yes that's what I get as well. But that's not the correct wasm file. It should be named charp-wasm.wasm. If you inspect the wasm file you have there you will see it only contains the dotnet mono runtime and not the code for the project. @radical

**Comment by radical** [comment]
`WasmBuildNative=false` means we don't relink dotnet, so you get the default `dotnet.wasm` that you can use to run the assembly.
Don't set that if you want to get a single .wasm with everything, and use `WasmSingleFileBundle=true`.

**Comment by silesmo** [comment]
Oh okay, that wasn't apparent from the name. I did use WasmSingleFileBundle=true at the same time but that still resulted in the same output as you got. If the settings aren't compatible with each other shouldn't that produce an error or warning or something? @radical
