### ISSUE TITLE
[wasm] AOT: System.Numerics.Tensors.Net8.Tests - aot-instances.dll with exit code 137

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#96865]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=522800
Build error leg or test failing: normal-System.Numerics.Tensors.Net8.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/96108

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "aot-instances.dll.* Exec .*System.Numerics.Tensors.Net8.Tests.dll",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=522800
**Error message validated:** `aot-instances.dll.* Exec .*System.Numerics.Tensors.Net8.Tests.dll`
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 1/11/2024 9:08:27 PM UTC

cc @vargaz @tannergooding 

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[524793](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524793)|dotnet/runtime|[normal-System.Numerics.Tensors.Net8.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524793&view=ms.vss-test-web.build-test-results-tab&runId=12347642&resultId=162894)|dotnet/runtime#95583|
|[523904](https://dev.azure.com/dnceng-public/public/_build/results?buildId=523904)|dotnet/runtime|[normal-System.Numerics.Tensors.Net8.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=523904&view=ms.vss-test-web.build-test-results-tab&runId=12318780&resultId=162714)|dotnet/runtime#96618|
|[523499](https://dev.azure.com/dnceng-public/public/_build/results?buildId=523499)|dotnet/runtime|[normal-System.Numerics.Tensors.Net8.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=523499&view=ms.vss-test-web.build-test-results-tab&runId=12306674&resultId=164572)|dotnet/runtime#96696|
|[522876](https://dev.azure.com/dnceng-public/public/_build/results?buildId=522876)|dotnet/runtime|[normal-System.Numerics.Tensors.Net8.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=522876&view=ms.vss-test-web.build-test-results-tab&runId=12289010&resultId=164580)|dotnet/runtime#96455|
|[522800](https://dev.azure.com/dnceng-public/public/_build/results?buildId=522800)|dotnet/runtime|[normal-System.Numerics.Tensors.Net8.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=522800&view=ms.vss-test-web.build-test-results-tab&runId=12287734&resultId=162714)|dotnet/runtime#96108|
|[522684](https://dev.azure.com/dnceng-public/public/_build/results?buildId=522684)|dotnet/runtime|[normal-System.Numerics.Tensors.Net8.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=522684&view=ms.vss-test-web.build-test-results-tab&runId=12284188&resultId=162714)|dotnet/runtime#96696|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|6|6|

**Comment by vargaz** [comment]
This is because the test suite for this class lib contains like 6k generic instances. I think we need to disable this on wasm+aot until 
https://github.com/dotnet/runtime/issues/95791
is fixed.

**Comment by tannergooding** [comment]
@vargaz, what's the right way to disable this for wasm+aot?

I'd guess that we can't just do the standard `[SkipOnMono]` approach since the failure looks to be a bit earlier... Is there a project level property that will work, I don't see anything covering that here: https://github.com/dotnet/runtime/blob/e458d68a3879d968faa1da9de38876e23935c166/docs/workflow/testing/libraries/filtering-tests.md

**Comment by radical** [comment]
Add the project in https://github.com/radical/runtime/blob/ebbc65763af9f8f1b01489afa520728db1db7e8b/src/libraries/tests.proj#L73-L82
