### ISSUE TITLE
Mariner 1 and Mariner 2 runtime-deps rpm package dependencies (x86_64 and aarch64) need to include ca-certificates

### ISSUE THREAD

**Issue by leecow** [dotnet/runtime#96874]
Mariner (Azure Linux) minimum image only includes Microsoft intermediate CAs which are insufficient for any https transactions. nuget restore requires https by default so event simple `dotnet new console` will fail unless you first install `ca-certificates`.

Current dotnet-runtime-deps-8.0.0-cm.2* dependencies:

```
rpm -qpR dotnet-runtime-deps-8.0.0-cm.2-x64.rpm
warning: dotnet-runtime-deps-8.0.0-cm.2-x64.rpm: Header V4 RSA/SHA256 Signature, key ID 3135ce90: NOKEY
icu
krb5
openssl-libs
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
```

**Comment by MichaelSimons** [comment]
This should only apply to Mariner2.0 because 1.0 reached EOL on July 31, 2023.

**Comment by NikolaMilosavljevic** [comment]
[Triage] Please fix.
