### ISSUE TITLE
`XmlNode.Prefix` should have `[AllowNull]`

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/runtime#96882]
### Description

`XmlNode.Prefix` is annotated as non-nullable, but its setter actually accepts null.

### Reproduction Steps

```csharp
#nullable enable
        var doc = new System.Xml.XmlDocument();
        doc.LoadXml(@"
<p1:Hello xmlns:p1=""https://platform.uno/prefix1"">
    <Child>ChildContent</Child>
</p1:Hello>
");

        doc.FirstChild!.Prefix = null; // Cannot convert null literal to non-nullable reference type
```

### Expected behavior

The API is designed such that there is no warning for the above case. I think best to do is to add AllowNullAttribute to the property.

Example code:

```csharp
#nullable enable

using System;
using System.Diagnostics.CodeAnalysis;

var node = new XmlNode();

_ = node.Prefix.ToString(); // no warning. Getter is always non-null.
node.Prefix = null; // no warning. Setter accepts null.

public class XmlNode
{
    [AllowNull]
    public object Prefix
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }
}
```

### Actual behavior

API isn't annotated properly

### Regression?

No.

**Comment by eiriktsarpalis** [comment]
Judging by the implementation(s) it seems like a reasonable thing to allow. Would you like to submit a PR adding this?

**Comment by krwq** [comment]
I can't remember the details but make sure all implementations actually accept null. If you're not seeing any warnings after the change feel free to send a PR.
