### ISSUE TITLE
Make Type.IsGenericType and GetGenericTypeDefinition() JIT intrinsics (and JIT time constants)

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#96898]
### Overview

This is one more codegen improvement we could leverage for CsWinRT, related to #95929. One scenario we have ([here](https://github.com/microsoft/CsWinRT/blob/eb066e4a179767e5598fd901652a625941f0b9db/src/WinRT.Runtime/Marshalers.cs#L1483C113-L1483C121)) is to check whether a given type `T` is some `KeyValuePair<,>` instantiation. This needs to be marshalled in a specific way to match the expectations of WinRT. Right now however, the only way we have to check for this case is to use `IsGenericType` and `GetGenericTypeDefinition()`, which are not JIT intrinsics. This makes the linker not see this special case, and therefore not correctly trim the code away (or just specialize it on the other hand). This is both marginally slower, but most importantly leaves some codegen size reduction opportunities on the table. We're seeing a bunch of `KeyValuePair<__Canon, __Canon>` instantiations in sizoscope even in sample WinRT components that never use `KeyValuePair<,>` at all anywhere. It would be nice if this could just be properly inlined as a constant instead.

### Codegen

```csharp
using SharpLab.Runtime;

[JitGeneric(typeof(System.Collections.Generic.KeyValuePair<int, int>))]
[JitGeneric(typeof(int))]
static bool IsKVP<T>()
{
    return typeof(T).IsGenericType && typeof(T).GetGenericTypeDefinition() == typeof(System.Collections.Generic.KeyValuePair<,>);
}
```

**Current codegen on .NET 8 x64 ([sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAIBlAC2ygAcAZbYAOgCUBXAOwwEt8MANwBYAFDiA2gCk+GAOIxuMKHzAAKDAE96MCADN1xAIwpWAaRhaAatgA2nGAAVsfKAB4+vNOS8YAfACUgQC64iZI5MAQEHbkAJK45tZO7gAq/uqB4gDe4uQF5MQA7OTaugbqaYGsiYrKqmBpOjDkAGRtZS2V1ayKCkoqas26ACIw+l5yfBDcWeQAvAtdFYYmZpY29o4ubu5oQaJiAL5AA===))**:
```asm
Program.<<Main>$>g__IsKVP|0_0[[System.Collections.Generic.KeyValuePair`2[[System.Int32, System.Private.CoreLib],[System.Int32, System.Private.CoreLib]], System.Private.CoreLib]]()
    L0000: sub rsp, 0x28
    L0004: mov rcx, 0x23e784e3260
    L000e: call qword ptr [0x7ffb1060a518]
    L0014: test eax, eax
    L0016: je short L0040
    L0018: mov rcx, 0x23e784e3260
    L0022: call qword ptr [0x7ffb1060a568]
    L0028: mov rcx, 0x23e783e2728
    L0032: cmp rax, rcx
    L0035: sete al
    L0038: movzx eax, al
    L003b: add rsp, 0x28
    L003f: ret
    L0040: xor eax, eax
    L0042: add rsp, 0x28
    L0046: ret

Program.<<Main>$>g__IsKVP|0_0[[System.Int32, System.Private.CoreLib]]()
    ; pretty much the same as above
```

**Expected codegen**:
```asm
Program.<<Main>$>g__IsKVP|0_0[[System.Collections.Generic.KeyValuePair`2[[System.Int32, System.Private.CoreLib],[System.Int32, System.Private.CoreLib]], System.Private.CoreLib]]()
    L0000: mov eax, 1
    L0005: ret

Program.<<Main>$>g__IsKVP|0_0[[System.Int32, System.Private.CoreLib]]()
    L0000: xor eax, eax
    L0002: ret
```

cc. @jkoritzinsky @MichalStrehovsky @EgorBo

**Comment by Sergio0694** [comment]
Sharing some notes from Discord:
- @MichalPetryka mentioned that `IsConstructedGenericType` would be easier to make an intrinsic compared to `IsGenericType`, and it would still be sufficient for this scenario. Either of them would be completely fine, really.
- @SingleAccretion mentioned that making `GetGenericTypeDefinition()` could be difficult to make an intrinsic, but it would be possible to just make direct comparisons over that return value be an intrinsic. That would also work in this scenario.

**Comment by EgorBo** [comment]
grep.app:

- https://grep.app/search?q=typeof%5C%28%2A.%5C%29.IsGenericType&regexp=true&filter[lang][0]=C%23
- https://grep.app/search?q=typeof%5C%28%2A.%5C%29.GetGenericTypeDefinition&regexp=true&filter[lang][0]=C%23

**Comment by GerardSmit** [comment]
There are more hits with GitHub Search:

- https://github.com/search?q=%2Ftypeof%5C%28%5BA-Za-z0-9.%5D*%5C%29%5C.IsGenericType%2F+language%3AC%23&type=code&l=C%23
- https://github.com/search?q=%2Ftypeof%5C%28%5BA-Za-z0-9.%5D*%5C%29%5C.GetGenericTypeDefinition%5C%28%5C%29%2F+language%3AC%23&type=code

**Comment by teo-tsirpanis** [comment]
It would also help with F#'s `typedefof`.

**Comment by hez2010** [comment]
Can we also intrinsify `typeof(T).IsConstructedGenericType` as well?

**Comment by Sergio0694** [comment]
Thank you for volunteering! 😄
