### ISSUE TITLE
BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGeneration intermittent test failures

### ISSUE THREAD

**Issue by jtschuster** [dotnet/runtime#96904]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=524448
Build error leg or test failing: BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGeneration
Pull request: https://github.com/dotnet/runtime/pull/96858

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGeneration",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=524448
**Error message validated:** `BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGeneration`
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 1/15/2024 9:33:19 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[528129](https://dev.azure.com/dnceng-public/public/_build/results?buildId=528129)|dotnet/runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGeneration](https://dev.azure.com/dnceng-public/public/_build/results?buildId=528129&view=ms.vss-test-web.build-test-results-tab&runId=12451024&resultId=138927)|dotnet/runtime#96960|
|[528222](https://dev.azure.com/dnceng-public/public/_build/results?buildId=528222)|dotnet/runtime|[System.Diagnostics.Tracing.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=528222&view=ms.vss-test-web.build-test-results-tab&runId=12443654&resultId=218851)||
|[528027](https://dev.azure.com/dnceng-public/public/_build/results?buildId=528027)|dotnet/runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover](https://dev.azure.com/dnceng-public/public/_build/results?buildId=528027&view=ms.vss-test-web.build-test-results-tab&runId=12438470&resultId=150948)|dotnet/runtime#96983|
|[527994](https://dev.azure.com/dnceng-public/public/_build/results?buildId=527994)|dotnet/runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGeneration](https://dev.azure.com/dnceng-public/public/_build/results?buildId=527994&view=ms.vss-test-web.build-test-results-tab&runId=12436936&resultId=160812)|dotnet/runtime#97005|
|[527832](https://dev.azure.com/dnceng-public/public/_build/results?buildId=527832)|dotnet/runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGeneration](https://dev.azure.com/dnceng-public/public/_build/results?buildId=527832&view=ms.vss-test-web.build-test-results-tab&runId=12432222&resultId=139058)|dotnet/runtime#96890|
|[527644](https://dev.azure.com/dnceng-public/public/_build/results?buildId=527644)|dotnet/runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGeneration](https://dev.azure.com/dnceng-public/public/_build/results?buildId=527644&view=ms.vss-test-web.build-test-results-tab&runId=12428150&resultId=153700)|dotnet/runtime#96991|
|[527109](https://dev.azure.com/dnceng-public/public/_build/results?buildId=527109)|dotnet/runtime|[System.Diagnostics.Tracing.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=527109&view=ms.vss-test-web.build-test-results-tab&runId=12413078&resultId=218852)||
|[527156](https://dev.azure.com/dnceng-public/public/_build/results?buildId=527156)|dotnet/runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover](https://dev.azure.com/dnceng-public/public/_build/results?buildId=527156&view=ms.vss-test-web.build-test-results-tab&runId=12413378&resultId=160627)|dotnet/runtime#96890|
|[524448](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524448)|dotnet/runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGeneration](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524448&view=ms.vss-test-web.build-test-results-tab&runId=12338244&resultId=187665)|dotnet/runtime#96858|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|6|9|9|

**Comment by jkotas** [comment]
#96816 tried to fix this.

cc @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
I'll take another look.
