### ISSUE TITLE
[API Proposal]: IZero and IOne interfaces

### ISSUE THREAD

**Issue by Shadowblitz16** [dotnet/runtime#96915]
### Background and motivation

Recently I was trying to implement a Utility class that provides math helpers for both numbers, vectors and matrices 
I ran into an issue when implementing Abs and Sign.
There doesn't seem to be a way to get One and Zero from vectors and matrices without implementing the INumber or INumberBase interfaces for both vectors and matrices

Now INumber and INumberBase are really big interfaces and they don't entirely suit vectors and matrices so here is the suggestion...

Can INumber and INumberBase One and Zero be put into IOne and IZero interfaces respectively 
You guys also might have an idea on extending this to other methods but this is the one I came to realize I need. 

### API Proposal

```csharp
namespace System.Collections.Generic;

// New
public interface IOne<TSelf> where TSelf : IOne<TSelf>
{
        public static abstract TSelf One();
}

public interface IZero<TSelf> where TSelf : IZero<TSelf>
{
        public static abstract TSelf Zero();
}


//Existing
public interface INumberBase<TSelf> : IOne<TSelf>, IZero<TSelf>
{

}

public interface INumber<TSelf> INumberBase<TSelf>
{

}
```

### API Usage

```csharp
public static class Math 
{
    public static bool InRange<T>(T value, T min, T max) where T : IComparisonOperators<T, T, bool>
    { 
        return (value >= min) && (value <= max); 
    }


    public static T Wrap<T>(T value, T min, T max)  
        where T : 
        IComparisonOperators   <T, T, bool>, 
        IMultiplyOperators     <T, T, T>, 
        IAdditionOperators     <T, T, T>,
        ISubtractionOperators  <T, T, T>,
        IUnaryPlusOperators    <T, T>,
        IUnaryNegationOperators<T, T>, 
        IZero<T>, 
        IOne <T>
    {
        var diff = Abs(max-min);
        if (diff == T.Zero) return T.Zero;

        while (value <  min) value += diff;
        while (value >= max) value -= diff;
        return value;
    }
    public static T Clamp<T>(T value, T min, T max)  
        where T : 
        IComparisonOperators   <T, T, bool>, 
        IMultiplyOperators     <T, T, T>, 
        ISubtractionOperators  <T, T, T>,
        IUnaryPlusOperators    <T, T>,
        IUnaryNegationOperators<T, T>, 
        IZero<T>, 
        IOne <T>
    {
        var diff = Abs(max-min);
        if (diff == T.Zero) return T.Zero;

        if (value <  min) return min;
        if (value >= max) return max;
        return value;
    }

    public static T Abs <T>(T value) where T : 
        IComparisonOperators   <T, T, bool>, 
        IMultiplyOperators     <T, T, T>, 
        IUnaryNegationOperators<T, T>, 
        IZero<T>, 
        IOne <T>
    {
        if (value < T.Zero) return value * -T.One;
        return value;

    }
    public static T Sign<T>(T value) where T :
        IComparisonOperators   <T, T, bool>, 
        IUnaryNegationOperators<T, T>, 
        IZero<T>, 
        IOne <T>
    {
        if (value < T.Zero) return -T.One;
        if (value > T.Zero) return T.One;
        return value;
    }
}
```

### Alternative Designs

There could be a IVector or IMatrix interface that implements INumber
But that sounds like it would be worse.

### Risks

Explicit INumber and INumberBase implementations for One and Zero would  need to be modified to be explicit implementations for IOne and IZero.

**Comment by tannergooding** [comment]
Vectors and Matrices aren't really "numbers" so much as they are collections of numbers, they likely need their own interfaces, such as  `IVector<TSelf, T>` and `IMatrix<TSelf, T>`. These interfaces would expose their own concept of zero, one.

Otherwise, you have concepts like the `IAdditiveIdentity` and `IMultiplicativeIdentity` which cover the broader mathematical use case.

**Comment by tannergooding** [comment]
Several of the examples given are notably also not the most efficient or natural ways to do the operations.

For example, I would expect `Clamp` and `Wrap` to become `min/max` if they are equivalent. After all, `Clamp(value: 5, min: 10, max: 10)` should return `10`, not `0`.

Something like `Wrap` is very similar and has many scenarios where simply doing `value += diff` wouldn't be correct. For example, `Wrap(value: 7, min: 2, max: 4)` has a diff of `2`, but `7 - 2 == 5` which is still out of range. Thus, you really need to return `min/max` if they are equal and produce `0` (potentially accounting for the existence of `-0`, `Infinity`, and `NaN` for floating-point) and then need to perform a modulo operation to ensure that `Wrap(7, 2, 4)` becomes `4` (assuming min/max are inclusive).

For `Abs` simply multiplying by `-1` isn't sufficient given that `int.MinValue * -1 == int.MinValue` and remains negative. This may be acceptable for some scenarios, but there are better ways to compute that such as simply doing `0 - x` for negative `x`

`Sign` looks to be mirroring `Math.Sign` which is itself somewhat of a legacy API as it doesn't correctly account for the existence of `-0.0`. APIs like `IsNegative`, `IsZero`, `IsPositive`, and `CopySign` are better alternatives for almost all scenarios.

**Comment by Clockwork-Muse** [comment]
For the matrix scenario, the more relevant concept is almost certainly the [Identity Matrix](https://en.wikipedia.org/wiki/Identity_matrix).  I've read at least one sci-fi story where a character was referring to `0`/`1` in a statistics sense with `Identity`/`Unity`.  Those terms also show up in mathematics as well (ie, the identity function meaning "add 0"), although they can be concept-specific...

**Comment by tannergooding** [comment]
Yep!

And for vectors/matrices we've historically had it so that something like `Zero` or `One` means all elements equal this value. So a `Vector4.One` is `[1, 1, 1, 1]` and a `Matrix4x4.One` would logically be:
```
[ [ 1, 1, 1, 1 ],
  [ 1, 1, 1, 1 ],
  [ 1, 1, 1, 1 ],
  [ 1, 1, 1, 1 ] ]
```

Thus, `Matrix4x4.One != MultiplicativeIdentity` and can cause issues if that's what you had intended.

**Comment by MichalPetryka** [comment]
> with `Identity`

[An example of this.](https://docs.unity3d.com/2023.3/Documentation/ScriptReference/Quaternion-identity.html)
