### ISSUE TITLE
mono_install_marshal_callbacks is not reentrant?

### ISSUE THREAD

**Issue by bodong1987** [dotnet/runtime#96929]
### Description

I want to use C# by integrating MonoRuntime in a C++ application. I use mono_jit_init_version to initialize and mono_jit_cleanup to de-initialize. But when called for the second time (that is, repeated initialization and de-initialization during the life of the application), subsequent initialization will fail.

Looking through the call stack, it appears that the cause of the crash is that mono_install_marshal_callbacks are not reentrant. Because the lightweight_cb_inited global variable is only set to TRUE during initialization, but not set to FALSE during de-initialization. Personally, I think it can be initialized only when lightweight_cb_inited is FALSE, or the correct cleanup process can be performed. Make sure that when mono is initialized for the second time, the logic here is correct and assert is not triggered.

```C++
 	ntdll.dll!LdrpCallInitRoutine()	未知	非用户代码。符号已加载，没有源信息。
 	ntdll.dll!LdrShutdownProcess()	未知	非用户代码。符号已加载，没有源信息。
 	ntdll.dll!RtlExitUserProcess()	未知	非用户代码。符号已加载，没有源信息。
 	kernel32.dll!ExitProcessImplementation()	未知	非用户代码。符号已加载，没有源信息。
 	coreclr.dll!exit_or_terminate_process(const unsigned int return_code) 行 137	C++	已加载符号。
 	coreclr.dll!common_exit(const int return_code, const _crt_exit_cleanup_mode cleanup_mode, const _crt_exit_return_mode return_mode) 行 274	C++	已加载符号。
 	coreclr.dll!monoeg_assertion_message(const char * format, ...) 行 210	C	已加载符号。
 	coreclr.dll!mono_assertion_message(const char * file, int line, const char * condition) 行 226	C	已加载符号。
 	[内联框架] coreclr.dll!mono_install_marshal_callbacks(MonoMarshalLightweightCallbacks *) 行 6415	C	已加载符号。
>	coreclr.dll!mono_marshal_lightweight_init() 行 3400	C	已加载符号。
 	coreclr.dll!mini_init(const char * filename) 行 4637	C	已加载符号。
 	coreclr.dll!mono_jit_init_version(const char * root_domain_name, const char * runtime_version) 行 2824	C	已加载符号。

```

```C++
static MonoMarshalLightweightCallbacks marshal_lightweight_cb;
static gboolean lightweight_cb_inited = FALSE;

void
mono_install_marshal_callbacks (MonoMarshalLightweightCallbacks *cb)
{
	g_assert (!lightweight_cb_inited);
	g_assert (cb->version == MONO_MARSHAL_CALLBACKS_VERSION);
	memcpy (&marshal_lightweight_cb, cb, sizeof (MonoMarshalLightweightCallbacks));
	lightweight_cb_inited = TRUE;
}

static MonoMarshalLightweightCallbacks *
get_marshal_cb (void)
{
	g_assert (lightweight_cb_inited);
	return &marshal_lightweight_cb;
}


```

### Reproduction Steps

During an application's startup process, mono initialization and deinitialization are performed multiple times.

### Expected behavior

no assert.

### Actual behavior

assert with : g_assert (!lightweight_cb_inited);

**Comment by vargaz** [comment]
The mono runtime cannot be shut down and restarted. The only way to maybe make that work is to put it into a shared library, and unload and reload that shared library.

**Comment by bodong1987** [comment]
> The mono runtime cannot be shut down and restarted. The only way to maybe make that work is to put it into a shared library, and unload and reload that shared library.

thank you. I just discovered this problem.
