### ISSUE TITLE
[API Proposal]: Safe API for covariant cast of ReadOnlySpan<T>

### ISSUE THREAD

**Issue by reflectronic** [dotnet/runtime#96952]
### Background and motivation

It is always safe to convert a `ReadOnlySpan<U>` to a `ReadOnlySpan<T>` when `U` inherits from `T` (and neither are value types). However, performing such a cast is remarkably ugly and requires unsafe APIs:
```cs
public static ReadOnlySpan<object> FromStrings(ReadOnlySpan<string> stringSpan)
    => MemoryMarshal.CreateReadOnlySpan(ref Unsafe.As<string, object>(ref MemoryMarshal.GetReference(stringSpan)), stringSpan.Length); 
```
A safe and easy-to-use API can be provided for performing such conversions.

### API Proposal

```csharp
namespace System;

public ref struct ReadOnlySpan<T>
{
    public static ReadOnlySpan<T> CastUp<TDerived>(ReadOnlySpan<TDerived> items) where TDerived : class, T;
}
```

There is prior art in [`ImmutableArray.CastUp`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutablearray-1.castup) which I have followed in this proposal.

### API Usage

```csharp
public static ReadOnlySpan<object> FromStrings(ReadOnlySpan<string> stringSpan)
    => ReadOnlySpan<object>.CastUp(stringSpan);
```

### Alternative Designs

The method could be provided on `MemoryExtensions` as an extension method.
```cs
namespace System;

public static class MemoryExtensions
{
    // <T, TDerived> or <TDerived, T>?
    public static ReadOnlySpan<T> CastUp<T, TDerived>(this ReadOnlySpan<TDerived> items) where TDerived : class, T
}
```

 However, type inference would not be possible for the type parameters:
```csharp
public static ReadOnlySpan<object> FromStrings(ReadOnlySpan<string> stringSpan)
    => stringSpan.CastUp<object, string>(stringSpan);
```

It could be confusing to remember whether `T` or `TDerived` comes first in the generic type argument list.

This would be inconsistent with the existing `ImmutableArray` API. The difference is purely aesthetic, and presumably the ergonomic tradeoffs were considered during the review of that API, so sticking with the prior art seems best.

**Comment by tannergooding** [comment]
CC. @stephentoub, @GrabYourPitchforks for a second glance. This seems like a fine API with prior art, so I'd lean towards marking it `ready-for-review` and taking it to API review

**Comment by bartonjs** [comment]
We opted for the static method on `ReadOnlySpan<T>` as that ends up only needing to specify one type argument at the call site, vs two for the extension method.

```C#
namespace System;

public ref struct ReadOnlySpan<T>
{
    public static ReadOnlySpan<T> CastUp<TDerived>(ReadOnlySpan<TDerived> items) where TDerived : class, T;
}
```
