### ISSUE TITLE
docker: Error response from daemon: failed to create endpoint affectionate_thompson on network nat: Windows does not support host IP addresses in NAT settings.

### ISSUE THREAD

**Issue by Harshit-Goyal10** [dotnet/runtime#96954]
I am trying to run an image in a  container and getting the given below error.
this command , I have used in this way  : docker run -p 127.0.0.1:3000:3000 webdckq

docker: Error response from daemon: failed to create endpoint affectionate_thompson on network nat: Windows does not support host IP addresses in NAT settings.

**Comment by antonfirsov** [comment]
@Harshit-Goyal10 how is this issue related to .NET? Can you please provide more context?

**Comment by Harshit-Goyal10** [comment]
I think this issue is not related to .NET, But this issue is related with the docker desktop tool, for mapping the host and container port, because this issue comes when I am trying to run a container in the docker after building an image of a project.

**Comment by antonfirsov** [comment]
In that case you should try to get help from docker folks:
https://forums.docker.com/
https://github.com/docker/for-win
https://www.docker.com/support/

Not a .NET issue, closing.
