### ISSUE TITLE
Unable to profile Mac Catalyst apps with `dotnet trace`

### ISSUE THREAD

**Issue by beeradmoore** [dotnet/runtime#96970]
(EDIT: Works now with some modificiations, see bottom of this post for full info)

### Description

Trying to find some resource issues with CollectionViews in MAUI on macOS I decided to try use dotnet trace to see if I can narrow down what is happening. Trying multiple methods to get it to work I was not able to get anything to work. Going back to a brand new app as shown below I was still unable to get it working.

### Reproduction Steps

1. `mkdir MAUI_TEST`
2. `cd MAUI_TEST`
3. `dotnet new maui`
4. `dotnet build -c Release -f net8.0-maccatalyst -r maccatalyst-x64`
5. `dotnet trace collect --format speedscope -- bin/Release/net8.0-maccatalyst/maccatalyst-x64/MAUI_TEST.app/Contents/MacOS/MAUI_TEST`

### Expected behavior

`speedscope.json` file is generated.

### Actual behavior

App launches, is functional. Terminal outputs this
```
% dotnet trace collect --format speedscope -- bin/Release/net8.0-maccatalyst/maccatalyst-x64/MAUI_TEST.app/Contents/MacOS/MAUI_TEST

No profile or providers specified, defaulting to trace profile 'cpu-sampling'

Provider Name                           Keywords            Level               Enabled By
Microsoft-DotNETCore-SampleProfiler     0x0000F00000000000  Informational(4)    --profile 
Microsoft-Windows-DotNETRuntime         0x00000014C14FCCBD  Informational(4)    --profile 

Launching: bin/Release/net8.0-maccatalyst/maccatalyst-x64/MAUI_TEST.app/Contents/MacOS/MAUI_TEST 
```

About 5 seconds later the app then crashes and terminal outputs this.
```
Unable to start tracing session - the target app failed to connect to the diagnostics port. This may happen if the target application is running .NET Core 3.1 or older versions. Attaching at startup is only available from .NET 5.0 or later.
[ERROR] System.TimeoutException: The operation has timed out.
   at Microsoft.Diagnostics.NETCore.Client.HandleableCollection`1.Handle(Handler handler, TimeSpan timeout) in /_/src/Microsoft.Diagnostics.NETCore.Client/HandleableCollection.cs:line 155
   at Microsoft.Internal.Common.Utils.DiagnosticsClientBuilder.Build(CancellationToken ct, Int32 processId, String diagnosticPort, Boolean showChildIO, Boolean printLaunchCommand)
   at Microsoft.Diagnostics.Tools.Trace.CollectCommandHandler.Collect(CancellationToken ct, IConsole console, Int32 processId, FileInfo output, UInt32 buffersize, String providers, String profile, TraceFileFormat format, TimeSpan duration, String clrevents, String clreventlevel, String name, String diagnosticPort, Boolean showchildio, Boolean resumeRuntime, String stoppingEventProviderName, String stoppingEventEventName, String stoppingEventPayloadFilter) in /_/src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs:line 204
```

### Regression?

Unsure.

### Known Workarounds

None.

### Configuration

.NET SDK 8.0.100
macOS (14.2.1)
x64

### Other information

Unsure if it is related to this, #73715

I have also tried the information listed [here](https://github.com/xamarin/xamarin-macios/wiki/Profiling) with no luck.
```
dotnet build -c Debug -f net8.0-maccatalyst -r maccatalyst-x64 
DOTNET_DiagnosticPorts=~/my-desktop-port,suspend bin/Debug/net8.0-maccatalyst/maccatalyst-x64/MAUI_TEST.app/Contents/MacOS/MAUI_TEST
dotnet-trace collect --diagnostic-port ~/my-desktop-port --format speedscope
```

With the above the command that starts by setting `DOTNET_DiagnosticPorts` outputs
```
The runtime has been configured to pause during startup and is awaiting a Diagnostics IPC ResumeStartup command from a Diagnostic Port.
DOTNET_DiagnosticPorts="/Users/beeradmoore/my-desktop-port,suspend"
DOTNET_DefaultDiagnosticPortSuspend=0
```

The other command in a different terminal window says 
```
No profile or providers specified, defaulting to trace profile 'cpu-sampling'

Provider Name                           Keywords            Level               Enabled By
Microsoft-DotNETCore-SampleProfiler     0x0000F00000000000  Informational(4)    --profile 
Microsoft-Windows-DotNETRuntime         0x00000014C14FCCBD  Informational(4)    --profile 

Waiting for connection on /Users/beeradmoore/my-desktop-port
Start an application with the following environment variable: DOTNET_DiagnosticPorts=/Users/beeradmoore/my-desktop-port
```

But at no point does the application start.

### Update - all is fixed
```
mkdir MAUI_TEST
cd MAUI_TEST
dotnet new maui
```

Edit csproj to add 

```xml
<RuntimeIdentifier>maccatalyst-x64</RuntimeIdentifier>
```

(or maccatalyst-arm64)

For debug builds,
```
dotnet build -c Debug -f net8.0-maccatalyst
dotnet trace collect --format speedscope -- bin/Debug/net8.0-maccatalyst/maccatalyst-x64/MAUI_TEST.app/Contents/MacOS/MAUI_TEST
```

For release builds,
Add the following to csproj, (a comment [here](https://github.com/dotnet/runtime/issues/96970#issuecomment-1957534566) as to why)
```xml
<ItemGroup>
	<_MonoComponent Include="diagnostics_tracing" />
</ItemGroup>
```

Disable sandbox by removing 
```xml
        <key>com.apple.security.app-sandbox</key>
        <true/>
```
from your Mac Catalyst Entitlements.plist 

You can now, 
```
dotnet build -c Release -f net8.0-maccatalyst -r maccatalyst-x64
dotnet trace collect --format speedscope -- bin/Release/net8.0-maccatalyst/maccatalyst-x64/MAUI_TEST.app/Contents/MacOS/MAUI_TEST
```

**Comment by steveisok** [comment]
@mdh1418 can you please look into this?

**Comment by mdh1418** [comment]
Hi @beeradmoore, I believe the [diagnostics_tracing](https://github.com/dotnet/runtime/blob/3149a75d94f5e18144f477b347890884b4337817/docs/design/mono/diagnostics-tracing.md) [runtime component](https://github.com/dotnet/runtime/blob/3149a75d94f5e18144f477b347890884b4337817/docs/design/mono/components.md#L4) is not enabled by default in Release configuration when using the SDK, and that component is necessary to complete the EventPipe connection with the diagnostics tooling. In the SDK, the `diagnostics_tracing` component inclusion is determined at [this step](https://github.com/xamarin/xamarin-macios/blob/b0c3ae5fec1e69f036d5abb243e393fdb2c72075/dotnet/targets/Xamarin.Shared.Sdk.targets#L447), where `_BundlerDebug` is true in Debug builds.

If you build for Debug, `dotnet trace collect --format speedscope -- bin/Debug/net8.0-maccatalyst/maccatalyst-x64/MAUI_TEST.app/Contents/MacOS/MAUI_TEST` should work.

However if you need to trace the Release app, you could try manually including the runtime component (though I'm not sure if there are other moving parts that would be provided in debug configurations) by adding this ItemGroup to your csproj 
```
<ItemGroup>
	<_MonoComponent Include="diagnostics_tracing" />
</ItemGroup>
```
To note, there is a [known issue](https://github.com/dotnet/runtime/issues/94114#issuecomment-1784761813) with EventPipe not working with sandboxed apps, and I believe Release apps are sandboxed by default, so you would need to ensure that the entitlements of your app do not set the sandbox mode to true.
For me, I removed the key value pair from the dict in `Platforms/MacCatalyst/Entitlements.Release.plist`
```
        <key>com.apple.security.app-sandbox</key>
        <true/>
```

**Comment by beeradmoore** [comment]
Hey @mdh1418 , building and trying to profile with the command you said did not work.

```
dotnet build -c Debug -f net8.0-maccatalyst -r maccatalyst-x64 
dotnet trace collect --format speedscope -- bin/Debug/net8.0-maccatalyst/maccatalyst-x64/MAUI_TEST.app/Contents/MacOS/MAUI_TEST
```
results in the following
```
No profile or providers specified, defaulting to trace profile 'cpu-sampling'

Provider Name                           Keywords            Level               Enabled By
Microsoft-DotNETCore-SampleProfiler     0x0000F00000000000  Informational(4)    --profile 
Microsoft-Windows-DotNETRuntime         0x00000014C14FCCBD  Informational(4)    --profile 

Launching: bin/Debug/net8.0-maccatalyst/maccatalyst-x64/MAUI_TEST.app/Contents/MacOS/MAUI_TEST 
Unable to start tracing session - the target app failed to connect to the diagnostics port. This may happen if the target application is running .NET Core 3.1 or older versions. Attaching at startup is only available from .NET 5.0 or later.
[ERROR] System.TimeoutException: The operation has timed out.
   at Microsoft.Diagnostics.NETCore.Client.HandleableCollection`1.Handle(Handler handler, TimeSpan timeout) in /_/src/Microsoft.Diagnostics.NETCore.Client/HandleableCollection.cs:line 155
   at Microsoft.Internal.Common.Utils.DiagnosticsClientBuilder.Build(CancellationToken ct, Int32 processId, String diagnosticPort, Boolean showChildIO, Boolean printLaunchCommand)
   at Microsoft.Diagnostics.Tools.Trace.CollectCommandHandler.Collect(CancellationToken ct, IConsole console, Int32 processId, FileInfo output, UInt32 buffersize, String providers, String profile, TraceFileFormat format, TimeSpan duration, String clrevents, String clreventlevel, String name, String diagnosticPort, Boolean showchildio, Boolean resumeRuntime, String stoppingEventProviderName, String stoppingEventEventName, String stoppingEventPayloadFilter) in /_/src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs:line 204
```

With sandbox disabled (or it could just be new SDK from since when I first filed the issue) build no longer builds with the original command,
```
dotnet build -c Release -f net8.0-maccatalyst -r maccatalyst-x64

/usr/local/share/dotnet/sdk/8.0.100/Current/SolutionFile/ImportAfter/Microsoft.NET.Sdk.Solution.targets(27,5): error NETSDK1134: Building a solution with a specific RuntimeIdentifier is not supported. If you would like to publish for a single RID, specify the RID at the individual project level instead. [/Users/beeradmoore/MAUI_TEST/MAUI_TEST.sln]
```
so I changed target frameworks to 
```xml
<TargetFrameworks>net8.0-maccatalyst</TargetFrameworks>`
and changed the build command to
```
dotnet build -c Release -f net8.0-maccatalyst
```
Still no dice.

BUT, then adding in
```xml
<ItemGroup>
	<_MonoComponent Include="diagnostics_tracing" />
</ItemGroup>
```

and just profiling with 
```
dotnet trace collect --format speedscope -- bin/Release/net8.0-maccatalyst/maccatalyst-x64/MAUI_TEST.app/Contents/MacOS/MAUI_TEST
```
gives
```
No profile or providers specified, defaulting to trace profile 'cpu-sampling'

Provider Name                           Keywords            Level               Enabled By
Microsoft-DotNETCore-SampleProfiler     0x0000F00000000000  Informational(4)    --profile 
Microsoft-Windows-DotNETRuntime         0x00000014C14FCCBD  Informational(4)    --profile 

Launching: bin/Release/net8.0-maccatalyst/maccatalyst-x64/MAUI_TEST.app/Contents/MacOS/MAUI_TEST 
Process        : /Users/beeradmoore/MAUI_TEST/bin/Release/net8.0-maccatalyst/maccatalyst-x64/MAUI_TEST.app/Contents/MacOS/MAUI_TEST
Output File    : /Users/beeradmoore/MAUI_TEST/MAUI_TEST_20240222_111337.nettrace
[00:00:00:08]	Recording trace 3.6998   (MB)
Press <Enter> or <Ctrl+C> to exit...33   (MB)
Stopping the trace. This may take several minutes depending on the application being traced.

Trace completed.
Writing:	/Users/beeradmoore/MAUI_TEST/MAUI_TEST_20240222_111337.speedscope.json
Conversion complete
```

which produced this which appears to work on [speedscope.app](https://www.speedscope.app)
[MAUI_TEST_20240222_111337.speedscope.json](https://github.com/dotnet/runtime/files/14366466/MAUI_TEST_20240222_111337.speedscope.json)


So end result is still can't do it for debug builds, but also probably shouldn't be.

Is there a doc or md file somewhere that should be updated with the csproj and sandbox changes above?
The sandbox changes are a pain because for a larger app because if it isn't built with sandbox disabled then suddenly disabling it will have other consequences like `FileSystem.Current.AppDataDirectory` is now `~/Library/` and not even an app specific directory which can cause very bad things to happen to the users system if they do things expecting it to be their private path.

**Comment by mdh1418** [comment]
Hi @beeradmoore, sorry to hear it didn't work, I'll try it out on mac x64 after I charge it (I'm using mac arm64). If the failure to trace repro's reliably, would you mind either inspecting the `.binlog` or sending it to me so I can inspect it?
In your project, delete the artifacts `MAUI_TEST/bin` `MAUI_TEST/obj`
`dotnet build -c debug -f net8.0-maccatalyst /bl` (/bl will produce a msbuild.binlog file)

I use this MSBuildStructuredLogViewer https://github.com/KirillOsenkov/MSBuildStructuredLog/ and looked for the `_MonoSelectRuntimeComponents` target, checking what was added to `_MonoRuntimeSelectedComponents`
![Screenshot 2024-02-21 at 7 39 42 PM](https://github.com/dotnet/runtime/assets/16830051/2b5188f3-f25e-44ca-8e98-854250df5249)

I also am noticing needing to remove the `-r maccatalyst-<arch>` and specifying it in a `RuntimeIdentifier` property like `<RuntimeIdentifier>maccatalyst-arm64</RuntimeIdentifier>`

I was using dotnet sdk version `8.0.300-preview.24107.20`, so let me try out 8.0.100. Maybe a fix went in between the two.
-------
> Is there a doc or md file somewhere that should be updated with the csproj and sandbox changes above?

I'm not aware if any docs contain the note yet, but there is the open issue that I plan on looking into https://github.com/dotnet/runtime/issues/94114

**Comment by beeradmoore** [comment]
Hey @mdh1418 , I am not sure what happened to change things on my end as I was writing that last response. I know I did a VS4Mac update (+.NET 7 update) and a workload update, I don't recall if that was before or during.

But attempting to run the debug line to build gives the same error as above of specifying RID. 
Adding in 
```xml
<RuntimeIdentifier>maccatalyst-x64</RuntimeIdentifier>
```

I can indeed build and profile as expected,
```
dotnet build -c Debug -f net8.0-maccatalyst                   
```

```
dotnet trace collect --format speedscope -- bin/Debug/net8.0-maccatalyst/maccatalyst-x64/MAUI_TEST.app/Contents/MacOS/MAUI_TEST
```

```
No profile or providers specified, defaulting to trace profile 'cpu-sampling'

Provider Name                           Keywords            Level               Enabled By
Microsoft-DotNETCore-SampleProfiler     0x0000F00000000000  Informational(4)    --profile 
Microsoft-Windows-DotNETRuntime         0x00000014C14FCCBD  Informational(4)    --profile 

Launching: bin/Debug/net8.0-maccatalyst/maccatalyst-x64/MAUI_TEST.app/Contents/MacOS/MAUI_TEST 
Process        : /Users/beeradmoore/MAUI_TEST/bin/Debug/net8.0-maccatalyst/maccatalyst-x64/MAUI_TEST.app/Contents/MacOS/MAUI_TEST
Output File    : /Users/beeradmoore/MAUI_TEST/MAUI_TEST_20240222_130019.nettrace
[00:00:00:04]	Recording trace 10.7174  (MB)
Press <Enter> or <Ctrl+C> to exit...76   (MB)
Stopping the trace. This may take several minutes depending on the application being traced.

Trace completed.
Writing:	/Users/beeradmoore/MAUI_TEST/MAUI_TEST_20240222_130019.speedscope.json
Conversion complete
```

This is even without  the `<_MonoComponent Include="diagnostics_tracing" />` (but as you said, debug builds do this automatically).

As far as I am concerned this is now down to a few steps required to work (going to edit first post to include it). If you don't need anything else from me I am happy for this to be closed as solved and hopefully the required information can be put in documentation somewhere.

**Comment by mdh1418** [comment]
Glad it works :)  Thank you for trying out the tools!
