### ISSUE TITLE
[Mono][RISCV] How can I Debugging Multi-thread problems of Mono

### ISSUE THREAD

**Issue by Xinlong-Wu** [dotnet/runtime#96971]
Hi,
I'm trying to implement RISCV64 support on Mono as https://github.com/dotnet/runtime/issues/96117 planed. 

But I have met some problems happened at running `System.Thread`. It is hard to located the problem when jobs runing in a parallel and racing way.

So I am here to asking for help. Is there any thing/tools can help me for debugging?

I have found that tools like `dotnet-sos`, `dotnet-dump` and `dotnet-trace` may help me. Is that right? 

Im trying to install sos by command `dotnet-sos install`. but it it seems don't have riscv64 binary. what should I do?

**Comment by am11** [comment]
> Im trying to install sos by command `dotnet-sos install`. but it it seems don't have riscv64 binary. what should I do?

@viewizard implemented it relatively recently in https://github.com/dotnet/diagnostics/pull/4385, you can try building https://github.com/dotnet/diagnostics/ from source and use it.

Threading races are probably still hard to discover with lldb. Maybe try instrumenting bunch of loggings in mono-threads-posix.c and mono-threads-posix-signals.c, add isolated repro code in `src/mono/sample/HelloWorld/Program.cs` and `make` run it.

**Comment by vargaz** [comment]
We usually try something like the following:
- make the race as reproducible as possible
- reduce the test case as much as possible
- run it under lldb to debug and/or add prints to the runtime to gather more information.
- You can run the mono runtime as a binary i.e. mono-sgen <app>, it just needs some env variables to be set, in particular MONO_PATH needs to be set to the directory which contains corlib, then to the directory which can the rest of the assemblies. Also, you might have to set LD_LIBRARY_PATH etc to the dir which contains libSystem.Native.so etc.

**Comment by jkotas** [comment]
> Im trying to install sos by command dotnet-sos install. but it it seems don't have riscv64 binary. what should I do?

SOS is CoreCLR specific debugger extension. It won't work for Mono.

For Mono, you have to use low-level debugger or printf debugging as @vargaz suggested.

**Comment by dkurt** [comment]
Is there an options to disable threading at all? I've found only [DISABLE_THREADS](https://github.com/search?q=repo%3Adotnet%2Fruntime+DISABLE_THREADS+&type=code) but is seems WASM related mostly.
