### ISSUE TITLE
The DiagnosticsHelper.CompareTags method assumes that the list for the default meter factory create method is sorted, but the list is not sorted.”

### ISSUE THREAD

**Issue by yoziv** [dotnet/runtime#96979]
### Description

When creating a new meter, the CompareTags method in the [DiagnosticsHelper](https://github.com/dotnet/runtime/blob/092cbed116fe0c661d40bf8657fbe759020b0cab/src/libraries/Common/src/System/Diagnostics/DiagnosticsHelper.cs) class is used in the [default meter factory](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Diagnostics/src/Metrics/DefaultMeterFactory.cs) to check the cached meters dictionary. the method assumes that the first list is sorted. However, when you create the Factory meter at the end of the factory (specifically in line 57), the options.tags variable is never sorted.

Consequently, it never gets sorted in .NET. It’s up to the user to always pass a sorted list. But if the user passes a sorted list and every list that is saved is also sorted, there is no need for the complex function to compare tags.

I am wondering about the purpose of this function. I’m not sure if I’m missing something, but this seems like a major bug or a performance issue.

### Reproduction Steps

any use of the default meter factory would have that symptom if the tags are not sorted in the user side 

### Expected behavior

sort the list somewhere in the meter factory 

### Actual behavior

no sorting, possible bug in the sorting 

### Known Workarounds

sort in the user side

### Configuration

.net8

**Comment by yoziv** [comment]
@tarekgh  who is the author of most of these files

**Comment by tarekgh** [comment]
Default meter factory is creating FactoryMeter passing the options tags:

https://github.com/dotnet/runtime/blob/a77c0b4548e0a9b0d46d11610b976f8cd616619b/src/libraries/Microsoft.Extensions.Diagnostics/src/Metrics/DefaultMeterFactory.cs#L57

Factory meter constructor will call the Meter constructor:

https://github.com/dotnet/runtime/blob/a77c0b4548e0a9b0d46d11610b976f8cd616619b/src/libraries/Microsoft.Extensions.Diagnostics/src/Metrics/DefaultMeterFactory.cs#L91

Meter constructor will call Initialize method

https://github.com/dotnet/runtime/blob/a77c0b4548e0a9b0d46d11610b976f8cd616619b/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/Meter.cs#L70

Initialize will sort the tags 

https://github.com/dotnet/runtime/blob/a77c0b4548e0a9b0d46d11610b976f8cd616619b/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/Meter.cs#L81

Could you please provide a sample code demonstrate the problem you are talking about?

**Comment by yoziv** [comment]
thanks @tarekgh  that was what i was missing
