### ISSUE TITLE
StartTransportLayerSecurity(...) method throw an exception when using System.DirectoryServices.Protocols in version 8.0.0 on Linux

### ISSUE THREAD

**Issue by ManuStangSE** [dotnet/runtime#96988]
### Description

On Linux, when i want to connect to an LDAP server using Start TLS, an exception is thrown, with error code 81.
The exception occurs when calling the method StartTransportLayerSecurity(null).
This problem was not present in version 7 of the "System.DirectoryServices.Protocols" package.

### Reproduction Steps

0) Use Linux (Ubuntu 22 for me) and .Net 8 framework
1) Confirure an Ldap server with Start TLS on port 389
2) Install LibLdap library and create a symbolic link
    ```
    sudo apt-get update
    sudo apt-get install libldap-2.5-0
    sudo ln -s /usr/lib/x86_64-linux-gnu/libldap-2.5.so.0.1.11 /usr/lib/x86_64-linux-gnu/libldap-2.4.so.2
    ```

3) Reference "System.DirectoryServices.Protocols" package in version 8.0.0 in your project

4) Execute this code : 

          string ipAddress = "{Ldap_server_Ip_Address}";
          int port = 389;
          string domain = "{Your domain}";
          string userName = "{UserName}";
          string password = "{Password}";

          var server = new LdapDirectoryIdentifier(ipAddress, port);
          var ldapConnection = new LdapConnection(server, new NetworkCredential(userName, password));
          ldapConnection.SessionOptions.ProtocolVersion = 3;
          
          ldapConnection.SessionOptions.StartTransportLayerSecurity(null);
          

### Expected behavior

No exception is thrown when "StartTransportLayerSecurity" method is called

### Actual behavior

Exception is thrown when calling "StartTransportLayerSecurity" method : 

![image](https://github.com/dotnet/runtime/assets/156678511/dfb202d7-59dd-481f-9806-c7404f2736d1)

### Regression?

Yes

### Known Workarounds

Use 7.0.0 version of "System.DirectoryServices.Protocols" package

### Configuration

.Net 8
Linux (Ubuntu 22)
x64

### Other information

It works under windows in version 8

**Comment by buyaa-n** [comment]
> Install LibLdap library and create a symbolic link

I wonder if the issue caused by this, FYI in .NET 8 we [fixed](https://github.com/dotnet/roslyn-analyzers/pull/6838) the [bug](https://github.com/dotnet/runtime/issues/69456) what was requiring this workaround. Could you try again by removing the symbolic link
