### ISSUE TITLE
"Unknown switch" when trying to compile NativeAOT.

### ISSUE THREAD

**Issue by dadavadd** [dotnet/runtime#97006]
I accidentally broke something in "PowerShell for Developers". When I try to compile NativeAOT, it tells me that the switch is unknown. Is there a command to reset these settings?

I also get some message in the console: “Key: -”. (You should see this in the screenshot).
![image](https://github.com/dotnet/runtime/assets/111659964/75918771-a306-4077-9fdf-59a6363f2e5f)

**Comment by MichalStrehovsky** [comment]
You have too many spaces on the command line. It should be `dotnet publish -r win-x64 -c Release`
