### ISSUE TITLE
Can't build with libs.src+libs.ref on Windows

### ISSUE THREAD

**Issue by usr-sse2** [dotnet/runtime#97029]
### Description

Subset `clr.nativeprereqs+clr.corelib+libs.sfx+libs.oob+libs.src+libs.ref+libs.pretest+libs.tests` can't be built on Windows, although it builds successfully on macOS.

### Reproduction Steps

```cmd
git clone https://github.com/dotnet/runtime
cd runtime
git checkout v8.0.1
build.cmd clr.nativeprereqs+clr.corelib+libs.sfx+libs.oob+libs.src+libs.ref+libs.pretest+libs.tests -restore -rebuild -configuration Release -arch x64
```

### Expected behavior

Successful build

### Actual behavior

The following errors are emitted: 
[errors.log](https://github.com/dotnet/runtime/files/13950199/errors.log)

### Known Workarounds

Build `clr.nativeprereqs+clr.corelib+libs.sfx+libs.oob+libs.pretest+libs.tests`, then build `libs.src+libs.ref` separately. Both are built successfully, and then even the original build command works too.

### Configuration

- 8.0.1
- Windows 11
- x64
- No
- N/A

**Comment by usr-sse2** [comment]
> `libs.ref+libs.src` subset aren't necessary anymore as `libs.sfx+libs.oob` it the superset. They shouldn't be used anymore and will eventually be removed. Are those still documented somewhere? Also, you shouldn't need to pass `-restore -rebuild` in.

I'm running it under a static code analyzer, and my goal as to build all C# code in dotnet/runtime repository while building as little C/C++ as possible (to save time), and always rebuild everything. That's why I try to exclude subsets that contain only native code and pass `-restore -rebuild`.

**Comment by ViktorHofer** [comment]
Please remove the `libs.ref+libs.src` subsets and try your command again.

**Comment by usr-sse2** [comment]
I understood now. Without libs.ref+libs.src it works.
