### ISSUE TITLE
[RyuJIT] rename var_types JITtype2varType(CorInfoType type) and improve description

### ISSUE THREAD

**Issue by 4creators** [dotnet/runtime#9703]
`var_types JITtype2varType(CorInfoType type)` in:

https://github.com/dotnet/coreclr/blob/a1c3279a88f780029e09df458c0032f329789340/src/jit/ee_il_dll.hpp#L149

converts `TYP_ULONG` to `TYP_LONG` due to wrong entry in ` varTypeMap` 

category:implementation
theme:jit-coding-style
skill-level:intermediate
cost:small

**Comment by BruceForstall** [comment]
Closing
