### ISSUE TITLE
error C3611: 'System::Numerics::INumberBase::System::IUtf8SpanFormattable.Try Format': a sealed function cannot have a pure-specifier

### ISSUE THREAD

**Issue by robindegen** [dotnet/runtime#97036]
### Description

Exactly the same as #94998.
However this issue is closed and I can no longer comment.

I am trying to build the runtime from the 8.0.1 tag.

I simply run:
.\build.cmd -s Host.Native -c debug

And I get these failures:

```
ijw.cpp(22): error C3611: 'System::Numerics::INumberBase::System::IUtf8SpanFormattable.TryFormat': a sealed function cannot have a pure-specifier
```

The issue mentions that it is supposedly fixed in a newer version of Visual Studio. I installed 17.8.4 and the problem persists.

Is there perhaps something wrong in how the compiler version is selected with cmake? I use cmake 3.28.1

### Reproduction Steps

Install latest (as of now) Visual Studio 17.8.4
Install latest (as of now) Cmake 3.28.1
In powershell:
Clone the repo
Check out tag 8.0.1
Build with: 
.\build.cmd -s Host.Native -c debug

### Expected behavior

Correct build. 8.0.0 built without errors this way.

### Actual behavior

Build failure.
error C3611: 'System::Numerics::INumberBase::System::IUtf8SpanFormattable.TryFormat': a sealed function cannot have a pure-specifier

**Comment by tannergooding** [comment]
I imagine the wrong toolset version is being selected and it isn't picking the latest `v143` tools or that isn't installed as part of your VS build. Could you please confirm that you have it installed and which version is installed if possible?

**Comment by robindegen** [comment]
> I imagine the wrong toolset version is being selected and it isn't picking the latest `v143` tools or that isn't installed as part of your VS build. Could you please confirm that you have it installed and which version is installed if possible?

Your question prompted me to verify all the versions. It indeed has to do with cmake(?) selecting the wrong toolset somehow. I had 2 versions installed: Latest and 14.37-17.7 (not sure why; I just regularly update visual studio without selecting additional things). I removed 14.37-17.7 and just kept "Latest". After this it worked.

Should the version perhaps be enforced/checked in the cmake scripting somehow?

**Comment by tannergooding** [comment]
Yes, likely. But that's not an area I'm super familiar with.

@ViktorHofer might have a better idea, a quick search shows we might want https://cmake.org/cmake/help/latest/variable/CMAKE_GENERATOR_TOOLSET.html

**Comment by ViktorHofer** [comment]
This might be a better question for @jkoritzinsky or @akoeplinger

**Comment by jkoritzinsky** [comment]
The toolset selector only works for the VS generator. The Ninja generator picks up the toolset from the environment variables, so that depends on how the VS Dev Prompt gets configured.

**Comment by tannergooding** [comment]
Moving to area-infrastructure to decide if adding some minimal version check is desirable or not.

**Comment by agocke** [comment]
We would accept a fix, but this work is not planned, and I don't like keeping an unlimited backlog of infra issues.
