### ISSUE TITLE
Replace DOS stub due to potential copyright issue

### ISSUE THREAD

**Issue by joshudson** [dotnet/runtime#97048]
Whenever dotnet build or dotnet pack is ran, it copies this 64 byte part of itself into the output binary (the MS-DOS stub). Guess what license that 64 byte block of code has...

It's certainly not the license for the code I'm shipping on nuget.

Right now I'm casting about, looking for anything interesting I can do about it. I have a replacement for that 64 byte block of code, but trying to replace it in a post build step results in an infinite regression trying to replace the 64 byte block of code in the code that runs the post build step.

An alternative: if you could locate where the code lives in the build tools; I could provide a replacement, and explicitly dedicate it to the public domain so nobody ever has to have this problem again.

**Comment by marcpopMSFT** [comment]
@richlander may want to take a look at this one.

**Comment by richlander** [comment]
Can I ask why this matters? The commit in question is from 11 years ago and has produced A LOT of executables in that time.

Is there a concern that the copyright holder is going to act or that one of your users will ask for clarity on these bytes in your executables?

**Comment by joshudson** [comment]
I got concerned when running a scan for MS-owned code and my own binaries matched on these bytes.

Since I'm dealing with GPL'd .NET binaries I really do have to account for the provenance of all executable code.

There's something else I know that I'm keeping close to the chest right now. The discovery pathway didn't start with .NET binaries; it started with EFI binaries.

**Comment by richlander** [comment]
PTAL: https://github.com/dotnet/core/pull/9069

**Comment by joshudson** [comment]
@richlander : It's entirely possible you have a completely different interpretation of the license than I do. I read your document.

**Comment by richlander** [comment]
> completely different interpretation

Hopefully not _completely_ different.

The intent of the additional statement was to say that the binaries the compiler produces carry no additional license burden.

I do want to clarify that we (the authors of that doc) are representing Microsoft, which happens to own those bytes in question as well. Putting .NET Foundation aside for the moment, there is only one copyright holder at play here.

Can you give me a hint on what you'd like to see? Or do I misunderstand your response?

**Comment by joshudson** [comment]
I was ready to say it was good enough once it hits master.

I just found it odd that it says it's already the case, which doesn't really matter.

**Comment by richlander** [comment]
I think the primary issue was that there hasn't been any clarity on this point. I hope the doc resolves that.

It would be helpful for you to approve the PR if you are good with it, as the OP of this issue.

**Comment by joshudson** [comment]
Doesn't look like I can review PRs on this repo.

**Comment by richlander** [comment]
Apologies. GH permissions don't work the way I thought. A comment would be great.

**Comment by richlander** [comment]
This is now resolved.

https://github.com/dotnet/core/blob/main/license-information.md
