### ISSUE TITLE
TcpClient.Client nullability declaration and actual behavior mismatch 

### ISSUE THREAD

**Issue by Trojaner** [dotnet/runtime#97050]
### Description

The Client property of the TcpClient class is not marked as nullable but will return null regardless if it's disposed: https://github.com/dotnet/runtime/blob/6584a5968f9b57e2cbce3c864dd0dc7b289f693a/src/libraries/System.Net.Sockets/src/System/Net/Sockets/TCPClient.cs#L95-L97

As you can already see here, the nullability checks are bypassed here on purpose by suppressing any warnings or errors with `!`.

### Reproduction Steps

```cs
var client = new TcpClient(...);
client.Dispose();

if (client.Client != null) 
{
   // Analysis will report this code as never reachable as client.Client is supposedly never null
   Console.WriteLine("Bug occured"); // will output regardless in this case
}
```

### Expected behavior

Either the analyzer should not report the code as never reachable or it should be actually never reachable (in other words, never return null)

### Actual behavior

Analyzer reports actually reachable code as not reachable 

### Regression?

Not to my knowledge

### Known Workarounds

Disabling analyzer or nullability for affected code.

### Configuration

This issue is still applicable to latest `main` branch code as of report date.
It seems like all platforms are affected as the implementation does not seem be platform-specific.

### Other information

Suggested solutions:
- the Client property can be correctly defined as `Socket?` 
- the Client property will never return null, even if disposed

**Comment by stephentoub** [comment]
Using an object after it's disposed is considered invalid and to invalidate the contract of the type. As such, nullable reference annotations on the core libraries do not factor in things that might become null once they're disposed.

From https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/api-guidelines/nullability.md
> DO NOT be concerned with the validity of annotations after an object has been Dispose'd. In general in .NET, using an instance after it's been disposed is a violation of its contract, and so similarly we generally (if the object isn't supposed to be used after disposal) don't consider the nullable annotations to be meaningful after disposal. This means, for example, that if a property is initialized in a ctor and is always non-null until disposal but then may return null after disposal, it should still be annotated as non-nullable.

**Comment by Trojaner** [comment]
Closing in favor of https://github.com/dotnet/roslyn/issues/71661
