### ISSUE TITLE
Set the property to look for in JsonDerivedType

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#97067]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Set-the-property-to-look-for-in-JsonDeri/10396433)._

---
.NET 7 provide polymophic deserialisation. Works fine but the way it is implemented has some drawbacks.
1. it only looks for the $Type property in a json object
2. $Type must be the first property in a json object

change requests 
- rename typeDiscriminator to typeDiscriminatorValue
- add typeDiscriminatorName = the name of the property to look for and match its value with the typeDiscriminatorValue
- do not require the typediscriminator property to be the first property in the json

---
#### Feedback Bot on 6/20/2023, 08:31 PM: 

(private comment, text removed)

**Comment by eiriktsarpalis** [comment]
> it only looks for the $Type property in a json object

The actual name of type discriminator property can be configured using the [`JsonPolymorphic`](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonpolymorphicattribute?view=net-8.0) attribute.

> $Type must be the first property in a json object

This is tracked by https://github.com/dotnet/runtime/issues/72604. We expect a fix to make its way in .NET 9.

> rename typeDiscriminator to typeDiscriminatorValue

Renaming APIs that have already shipped is a breaking change that we couldn't consider, unfortunately.

Hope this answers your questions.
