### ISSUE TITLE
Same culture behaves inconsistently across Windows and Linux

### ISSUE THREAD

**Issue by yang-xiaodong** [dotnet/runtime#971]
**Environment** :  netcoreapp 3.0 

```
Console.WriteLine("http://google.com".StartsWith("?"));

Thread.CurrentThread.CurrentCulture = new CultureInfo("th-TH");

Console.WriteLine("http://google.com".StartsWith("?"));
```

**Windows output:**
```
False
False
```

**Linux output:**
```
False
True
```

**Comment by wfurt** [comment]
cc: @tarekgh

**Comment by tarekgh** [comment]
It is expected to have different behaviors between different OS's or different versions of the same OS. we use the underlying OS to perform the collation operations. This is by design for the .NET. on Windows we use the NLS Win32 APIs for collations while on Linux/OSX we use ICU library.

In next release (i.e. net core 5.0) we are going to support using ICU on Windows which will allow consistent behavior.

**Comment by wfurt** [comment]
While this may be generally true, why do we think `http://google.com` starts with `?` @tarekgh

**Comment by tarekgh** [comment]
> Why do we think http://google.com starts with ? @tarekgh

Characters have sort weights. different cultures can assign different sort weights for characters. For culture like "th-TH" it can assign 0 sort weight for '?' which will make the character treated as if it is not exist at all. which will make any string will start with '?' like 

```C#
            CultureInfo.CurrentCulture = new CultureInfo("th-TH");
            Console.WriteLine("abcd".StartsWith("?")); // return true 
```

Users can switch to use Ordinal comparisons if they want to avoid such interesting cases.

**Comment by yang-xiaodong** [comment]
By default, The Thai developers need to pass `StringComparer.InvariantCulture` in all places that affect string sorting, and they cannot found it on Windows

**Comment by yang-xiaodong** [comment]
I think this issue should not be closed, so anyone who develops international applications using dotnet core may encounter this problem

**Comment by tarekgh** [comment]
> By default, The Thai developers need to pass StringComparer.InvariantCulture in all places that affect string sorting, and they cannot found it on Windows, there may be problems including the third-party libraries they used.

I am not I understand what you mean by "and they cannot found it on Windows"? The same APIs exposed on Linux is exposed on Windows. 

> I think this issue should not be closed, so anyone who develops international applications using dotnet core may encounter this problem

As I mentioned we are going to support using ICU on Windows in the next release and that will help in this scenario. In general the apps cannot expect to have consistent sorting behavior even between different versions of the same OS. Apps should evaluate the exact scenario they need to support and use the proper functionality. for example uses Invariant culture if they want to get closest consistency. They can use Ordinal too if they don't need the linguistic functionality.
