### ISSUE TITLE
The "Build / browser-wasm linux Release LibraryTests_EAT" leg's build fails with "Nothing to show. Final logs are missing."

### ISSUE THREAD

**Issue by kouvel** [dotnet/runtime#97117]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=530447
Build error leg or test failing: Build / browser-wasm linux Release LibraryTests_EAT
Pull request: https://github.com/dotnet/runtime/pull/94873

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Nothing to show. Final logs are missing. This can happen when the job is cancelled or times out.",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

## Additional info

The [pipeline details](https://dev.azure.com/dnceng-public/public/_build/results?buildId=530447&view=logs&jobId=47112925-2a34-5176-3619-2b56a9d343eb&j=47112925-2a34-5176-3619-2b56a9d343eb&t=6d8af0d9-4e37-5996-9573-3c69c8af399d) show that it failed with no logs:

> "Nothing to show. Final logs are missing. This can happen when the job is cancelled or times out."

The leg also appears to be in progress in the [PR's checks tab](https://github.com/dotnet/runtime/pull/94873/checks?check_run_id=20590451074) even though it appears to have completed with a failure. The leg appears to have passed in other recent PRs in about 1h 17m, and seems to have lasted about 1h 5m in the above PR.

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by kouvel** [comment]
Another hit in https://github.com/dotnet/runtime/pull/97227. In this run the [Build product](https://dev.azure.com/dnceng-public/public/_build/results?buildId=537672&view=logs&jobId=47112925-2a34-5176-3619-2b56a9d343eb&j=47112925-2a34-5176-3619-2b56a9d343eb&t=6d8af0d9-4e37-5996-9573-3c69c8af399d) step seems to have failed with the same error.

**Comment by lewing** [comment]
This is the same issue we're tracking in https://github.com/dotnet/runtime/issues/97044 it appears to be an illink hang
