### ISSUE TITLE
Simple net8 Blazor WASM AOT compiled App not working on Android11 downwards

### ISSUE THREAD

**Issue by Norsotec** [dotnet/runtime#97119]
### Description

If i create a basic simple .net8 Blazor WASM App with asp.net core hosted backend, and **compile it with AOT,** it's not working on "older" Android Devices. I've tested it on Android 10,11 and 12 (all with same newest chrome version) and it's only working on Android 12.

I'll provide detailed reproduction steps

### Reproduction Steps

GitHub Repo: [https://github.com/Norsotec/Net8AotOldAndroidProblem](https://github.com/Norsotec/Net8AotOldAndroidProblem)
Hosted Website to Test: [https://net8test.bonisda.at/](https://net8test.bonisda.at)

### Reproduce with your own Code:
**STEP 1: CREATE BASIC .net8 blazor wasm AOT App (asp.net core hosted)**
1. Create a new Project with template "ASP.NET CORE-WEB-API"  named "NET8AOT.Server", Select .NET 8 and use the default template settings.
2. Add another Project with template "Blazor-WebAssembly App" named "NET8AOT.Client", select .Net 8 and use default template settings.
3. Open NuGet Manager and update all outstanding updates (in my case only Swashbuckle.aspnetcore) 
4. In server-project install the NuGet "Microsoft.AspNetCore.Components.WebAssembly.Server"
5. In the server-project add a project-reference to the client-project.
6. in the server project open folder "Properties" > "launchSettings.json" and change all "launchUrl" properties from "swagger" to "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}" the property name has to be changed from "launchUrl" to "inspectUri".
7. In the server project do following changes to Program.cs:
- change "builder.Services.AddControllers()" to "builder.Services.AddControllersWithViews()" and add "builder.Services.AddRazorPages()" to the next line.
- In the http request pipeline configuration add "app.UseWebAssemblyDebugging()" to use vs studio debugging also for client wasm project.
- between "app.UseHttpsRedirection();" and "app.UseAuthorization();" add another two entries: "app.UseBlazorFrameworkFiles()" and "app.UseStaticFiles()"
- after "var builder = WebApplication.CreateBuilder(args)" add another row with "builder.WebHost.UseStaticWebAssets()"
- last step: above "app.MapControllers()" add the row "app.MapRazorPages()" and underneath add "app.MapFallbackToFile("index.html")"

**STEP 2: Deploy and test**
Now you can successfully test, debug and deploy this app.
Now i add the project file of the client and add RunAOTCompilation=true to the PropertyGroup
Afterwards i've add a publishprofile with IIS Web Deploy and publised the page. (See above Hosted Website to Test: [https://net8test.bonisda.at/](https://net8test.bonisda.at/))

**Client csproj:**
`<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
		<RunAOTCompilation>true</RunAOTCompilation>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.1" PrivateAssets="all" />
	</ItemGroup>
	<ItemGroup>
		<ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
	</ItemGroup>
</Project>
`

**Server csproj:**
`<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NET8AOT.Client\NET8AOT.Client.csproj" />
  </ItemGroup>
</Project>
`

### Expected behavior

I would expect normal page loading, like it can be discovered on **Android 12 with Chrome 120.0.6099.210** perfectly. No errors in browser-console and register the service worker.

### Actual behavior

On Android 10 with Chrome 120.0.6099.210 or Android 11 with Chrome 120.0.6099.210 I always get an exception. The same behavior on newest MS-Edge and FireFox. The exception is shown on this screenshot:

![android10](https://github.com/dotnet/runtime/assets/46633945/70a4996e-eb6d-4d3a-88bb-3262fef116d6)

### Regression?

i've never had this problem and went through all the .net6 and .net7 releases.

### Known Workarounds

So far I haven't found a workaround, hopefully not downgrading the project to .net7 again.

You could disable AOT, but i need to use it!
`<RunAOTCompilation>true</RunAOTCompilation>`

### Development Machine:
**Microsoft Windows 11 Pro 10.0.22631 Build 22631**
**MS Visual Studio 2022 (V17.8.5 / x64)**
**dotnet --list-sdks:**
- 8.0.101

**dotnet workload list**
- android 34.0.52/8.0.100
- wasm-tools 8.0.1/8.0.100
- maui-windows 8.0.3/8.0.100
- maccatalyst 17.2.8004/8.0.100
- ios 17.2.8004/8.0.100

### Hosting Server:
**Microsoft Windows Server 2019 Essentials  10.0.17763 Build 17763**
**dotnet --list-runtimes**
- Microsoft.AspNetCore.App 6.0.26
- Microsoft.AspNetCore.App 7.0.15
- Microsoft.AspNetCore.App 8.0.1
- Microsoft.NETCore.App 6.0.26
- Microsoft.NETCore.App 7.0.15
- Microsoft.NETCore.App 8.0.1

### Other information

I already using same project structure with .net6 and .net7, nothing has changed in the deployment settings (pretty default deployment with IIS Web Deploy)

I uninstalled wasm-tools, reboot Dev Machine and installed again with reboot again --> no change.

Do i miss something or can you confirm it's a buggy behave?

**Comment by Norsotec** [comment]
Due to the surprise of so few reactions to this ticket, does WASM aot finds so little use in the real world?

**Comment by maraf** [comment]
Sorry for later reply. I have tested the site in emulator (since I didn't get to a real device with Android 10). I fails with because of lacking support for SIMD (which is on by default in .NET 8). Can please try to publish the site with disabled SIMD like in https://github.com/maraf/dotnet-wasm-nosimd/blob/main/src/NoSIMD/NoSIMD.csproj#L5-L6

**Comment by Norsotec** [comment]
Thank you, disabling the SIMD feature fixed the problem. I didn't know that the default behavior has changed.
