### ISSUE TITLE
Can't build COMReference with dotnet build

### ISSUE THREAD

**Issue by Dolotboy** [dotnet/runtime#97125]
### Description

I added the "Microsoft Word 16.0 Object Library" COMReference to my C# WPF MVVM .NET 6. Because the [NuGet package](https://www.nuget.org/packages/Microsoft.Office.Interop.Word) isn't compatible.
I also use Entity Framework which requires to execute the commande "dotnet build". But I get an error saying this:
```
C:\Program Files\dotnet\sdk\8.0.101\Microsoft.Common.CurrentVersion.targets(3010,5): error MSB4803: The task "ResolveCo
mReference" is not supported on the .NET Core version of MSBuild. Please use the .NET Framework version of MSBuild.
```
What can I do to be able to use this librairy. I've tried every work around I could find but nothing seems to work and all the other librairies don't do exactly what I need them to do.

### Reproduction Steps

Create WPF app on .NET 6.0 -> Right click on project -> Add -> COMReference -> Microsoft Word 16.0 Object Library -> Execute command "dotnet build"

### Expected behavior

Build succeeded

### Actual behavior

Build failed:
C:\Program Files\dotnet\sdk\8.0.101\Microsoft.Common.CurrentVersion.targets(3010,5): error MSB4803: The task "ResolveCo
mReference" is not supported on the .NET Core version of MSBuild. Please use the .NET Framework version of MSBuild.

### Known Workarounds

- Create a .NET framework app, add the lib in this app and then reference this app in my main app
- Use another lib like OpenXML, GemBox, IronPDF

### Configuration

- .NET 6.0
- Win 10
- x86
- Not specific to that config

**Comment by AaronRobinsonMSFT** [comment]
This is currently by design. Using `ComReference` to generate a PIA or other assembly requires using the .NET Framework MSBuild. This is being tracked with https://github.com/dotnet/msbuild/issues/3986.

**Comment by Dolotboy** [comment]
Will it be fixed ?

**Comment by AaronRobinsonMSFT** [comment]
> @AaronRobinsonMSFT Will it be fixed ? Cuz it doesnt seems to be a normal behaviour for the newer version. Newer versions like .NET 6,7,8 should be able to do what older version did

COM support was added in this manner in .NET Core 3.0 with this behavior as is. We determine at that time that certain COM scenarios were lower priority if there were reasonable workarounds. Defining what "reasonable" means is subjective, but building COM scenarios using the built-in support is limited to Windows only so additional support is lower in priority relative to other interop related concerns (that is, Swift and Native AOT support).

The short answer is, it is unlikely to be fixed in the forseable future. The workaround, as noted in the error message, is to use .NET Framework's MSBuild.

**Comment by Dolotboy** [comment]
> > @AaronRobinsonMSFT Will it be fixed ? Cuz it doesnt seems to be a normal behaviour for the newer version. Newer versions like .NET 6,7,8 should be able to do what older version did
> 
> COM support was added in this manner in .NET Core 3.0 with this behavior as is. We determined at that time that certain COM scenarios were lower priority if there were reasonable workarounds. Defining what "reasonable" means is subjective, but building COM scenarios using the built-in support is limited to Windows only so additional support is lower in priority relative to other interop related concerns (that is, Swift and Native AOT support).
> 
> The short answer is, it is unlikely to be fixed in the forseable future. The workaround, as noted in the error message, is to use .NET Framework's MSBuild.

Ayt big thx ! Ill find a way to build my .NET 6 WPF app with the .NET framework MsBuild !
