### ISSUE TITLE
NullReferenceException in double arithmetic C++/CLR Jit Stage 2 assambly

### ISSUE THREAD

**Issue by MB512** [dotnet/runtime#97136]
### Description

I have a quite big project where i use some existing c code compiled with C++/CLR into managed IL.

The code is crashing after 1000+ calls in release build. Just after JIT Stage 2 is performed. When trying to debug the code it is running fine. Setting, hitting and removing a breakpoint at the crashing line makes the code run fine again.

### Reproduction Steps

I have set up a small demo project here https://github.com/MB512/CSJitHiccup

Run it in **release** build in Visual Studio 2022

### Expected behavior

The code should run fine

### Actual behavior

The code is crashing when JIT stage 2 is performed

### Regression?

It is working in DotNet 7

### Configuration

DotNet: 8.0
OS: Windows 10  (10.0.19045)
Architecture: x64
Don't know if it is specific but since JIT is involved i think it is

### Other information

Crash in demo project at CppLib/shared.cpp line 50 

Assembly code around crash:

        ret.I = K;
    00007FF87B39ABC7  vmovsd      xmm1,qword ptr [rsp+398h]  
    00007FF87B39ABD0  vmovsd      qword ptr [rsp+468h],xmm1  
        ret.L = 1e3 / Z / D * ((-F + J) / (pow(J, 2) - R * F));
    00007FF87B39ABD9  vmovsd      xmm1,qword ptr [<Module>.MainCalc(Double*, Double, Double)+0468h (07FF87B39AD38h)]  
    00007FF87B39ABE1  vmovaps     xmm0,xmm7  
    00007FF87B39ABE5  call        00007FF8DAECF140  
    00007FF87B39ABEA  vsubsd      xmm1,xmm7,mmword ptr [rsp+300h]  
    00007FF87B39ABF3  vmulsd      xmm2,xmm8,mmword ptr [rsp+300h]  
    00007FF87B39ABFC  vsubsd      xmm2,xmm0,xmm2  
    00007FF87B39AC00  vdivsd      xmm1,xmm1,xmm2  
    00007FF87B39AC04  vmovsd      xmm2,qword ptr [<Module>.MainCalc(Double*, Double, Double)+0470h (07FF87B39AD40h)]  
    00007FF87B39AC0C  vdivsd      xmm2,xmm2,mmword ptr [rsp+2D0h]  
    00007FF87B39AC15  vmulsd      xmm1,xmm1,xmm2  
    00007FF87B39AC19  vmovsd      qword ptr [rsp+480h],xmm1  
        ret.K = (F - pow(J, 2) / R) / S;
    00007FF87B39AC22  vdivsd      xmm0,xmm0,xmm8  
    00007FF87B39AC27  vmovsd      xmm0,qword ptr [rsp+300h]  
    00007FF87B39AC30  vmovdqu     xmm0,xmmword ptr [rax]  
    00007FF87B39AC34  vmovdqu     xmmword ptr [rsp+410h],xmm0  
    00007FF87B39AC3D  mov         rax,qword ptr [rax+10h]  
    00007FF87B39AC41  mov         qword ptr [rsp+420h],rax  
    00007FF87B39AC49  vmovsd      xmm0,qword ptr [rsp+410h]  
    00007FF87B39AC52  vdivsd      xmm0,xmm0,mmword ptr [rsp+2E8h]  
    00007FF87B39AC5B  vmovsd      qword ptr [rsp+478h],xmm0  

Crashing on the following line:

    00007FF87B39AC30  vmovdqu     xmm0,xmmword ptr [rax]

I have seen in debugging that the previous call at address 00007FF87B39ABE5 (which seams to be the call for pow or Math.Pow) is changing the rax register and that the optimized assembly in JIT Stage 2 seams to think that this call schould not change rax.

**Comment by JulieLeeMSFT** [comment]
CC @kunalspathak, @tannergooding for NRE at vmovdqu.

**Comment by tannergooding** [comment]
Does the same code fail if written in C#?

Notably `rax` is the return register and it is considered always volatile, therefore it must be preserved by the caller. It's entirely possible this is a C++/CLI bug in how it emits the IL to call `pow` or similar as well as it doesn't appear to be a proper P/Invoke (not even a SuppressGCTransition P/Invoke) as I would expect.

It would be helpful if we could get an IL dump of the `MainCalc` method as produced by C++/CLI for starters.

**Comment by jkotas** [comment]
The repro fails with assert on checked runtime:
```
Assert failure(PID 15036 [0x00003abc], Thread: 15780 [0x3da4]): Assertion failed 'genActualType(lclTyp) == genActualType(op1->gtType) || (genActualType(lclTyp) == TYP_I_IMPL && op1->OperIs(GT_LCL_ADDR)) || (genActualType(lclTyp) == TYP_I_IMPL && (op1->gtType == TYP_BYREF || op1->gtType == TYP_REF)) || (genActualType(op1->gtType) == TYP_I_IMPL && lclTyp == TYP_BYREF) || (varTypeIsFloating(lclTyp) && varTypeIsFloating(op1->TypeGet())) || ((genActualType(lclTyp) == TYP_BYREF) && genActualType(op1->TypeGet()) == TYP_REF) : Possibly bad IL with CEE_stloc.s at offset 001Eh (op1=double op2=NULL stkDepth=0)' in '<Module>:MainCalc(ulong,double,double):MainCalcResults' during 'Importation' (IL size 432; hash 0x584b8df9; Tier0)
```

Start of IL dump of the MainCalc method is:
```
.method assembly static valuetype MainCalcResults modopt([System.Runtime.CompilerServices.VisualC]System.Runtime.CompilerServices.CallConvCdecl) 
        MainCalc(float64* modopt([System.Runtime]System.Runtime.CompilerServices.IsConst) modopt([System.Runtime]System.Runtime.CompilerServices.IsConst) x21,
                 float64 p,
                 float64 T) cil managed
{
  .vtentry 1 : 1
  // Code size       432 (0x1b0)
  .maxstack  5
  .locals (float64 V_0,
           float64 V_1,
           float64 V_2,
           float64 V_3,
           float64 V_4,
           float64 V_5,
           valuetype MainCalcResults V_6,
           valuetype InnerResults2 V_7,
           valuetype InnerResults2 V_8,
           valuetype InnerResults4 V_9,
           valuetype InnerResults4 V_10,
           valuetype InnerResults4 V_11,
           valuetype InnerResults4 V_12,
           valuetype InnerResults3 V_13,
           valuetype InnerResults3 V_14,
           valuetype InnerResults3 V_15,
           valuetype InnerResults2 V_16,
           valuetype InnerResults2 V_17,
           valuetype InnerResults2 V_18,
           valuetype InnerResults2 V_19,
           valuetype InnerResults1 V_20)
  IL_0000:  ldarg.0
  IL_0001:  call       valuetype InnerResults1 modopt([System.Runtime.CompilerServices.VisualC]System.Runtime.CompilerServices.CallConvCdecl) InnerCalc0(float64* modopt([System.Runtime]System.Runtime.CompilerServices.IsConst) modopt([System.Runtime]System.Runtime.CompilerServices.IsConst))
  IL_0006:  stloc.s    V_20
  IL_0008:  ldloca.s   V_20
  IL_000a:  ldc.i4.s   24
  IL_000c:  add
  IL_000d:  ldobj      InnerResults0
  IL_0012:  ldarg.1
  IL_0013:  ldarg.2
  IL_0014:  call       valuetype InnerResults2 modopt([System.Runtime.CompilerServices.VisualC]System.Runtime.CompilerServices.CallConvCdecl) InnerCalc2(valuetype InnerResults0,
                                                                                                                                                         float64,
                                                                                                                                                         float64)
  IL_0019:  stloc.s    V_19
  IL_001b:  ldloca.s   V_19
  IL_001d:  ldind.r8
  IL_001e:  stloc.s    V_18
  IL_0020:  ldloca.s   V_19
  IL_0022:  ldc.i4.8
...
```

The IL at IL_001e is invalid. It is trying to store `double` into `InnerResults2` local variable. There are number of other similar type mismatches. It is likely that these type mismatches make the JIT to generate bad code. 

Bug in managed C++ compiler.

**Comment by jkotas** [comment]
I have moved this issue to https://developercommunity.visualstudio.com/t/NullReferenceException-in-double-arithme/10572636 to get it routed to the Visual Studio C++ compiler.
