### ISSUE TITLE
Add CreateLogger<T> to ILoggerFactory

### ISSUE THREAD

**Issue by qsdfplkj** [dotnet/runtime#97139]
### Background and motivation

There are a couple of ways to create a `ILogger` from an `ILoggerFactory`.

    - ILogger ILoggerFactory.CreateLogger(string categoryName)
    - ILogger LoggerFactoryExtensions.CreateLogger(this ILoggerFactory factory, Type type)
    - ILogger<T> LoggerFactoryExtensions.CreateLogger<T>(this ILoggerFactory factory)

Of these only the last one is not cached by the loggerFactory. Note that caching is depending on the concrete LoggerFactory implementation.

### API Proposal

Extend the `ILoggerFactory` with a default interface implementation to support caching for 'ILogger<T>`

Add this default implemenation:

```csharp
       public interface ILoggerFactory : IDisposable
       {
           ILogger<T> CreateLogger<T>() => new Logger<T>(this);
       }
```  

### API Usage

There are 2 places  that we need update.

First make sure the `LoggerFactoryExtensions` calls the default implemenation.
Note that any call to this extension method will be replaced by a call to the default implementatoins. 
Only calls that use `LoggerFactoryExtensions.CreateLogger<T>(...)` will still call this one.

```csharp
        public static ILogger<T> CreateLogger<T>(this ILoggerFactory factory)
        {
            ThrowHelper.ThrowIfNull(factory);

            return factory.CreateLogger<T>();
        }
```

Next is to implement the caching on the LoggerFactory 

```csharp
       private readonly ConcurrentDictionary<Type, ILogger> _loggersOfT = new ConcurrentDictionary<Type, ILogger>();

       public ILogger<T> CreateLogger<T>()
        { 
            if (CheckDisposed())
            {
                throw new ObjectDisposedException(nameof(LoggerFactory));
            }

            if (!_loggersOfT.TryGetValue(typeof(T), out ILogger? logger))
            {
                lock (_sync)
                {
                    if (!_loggersOfT.TryGetValue(typeof(T), out logger))
                    {
                        logger = new Logger<T>(this);
                        _loggersOfT[typeof(T)] = logger;
                    }
                }
            }

            return (ILogger<T>)logger;
        }
```        

### Risks

There seems no risk as the `ILogger<T>`  itself already uses a cached `ILogger`.

**Comment by tarekgh** [comment]
I am not sure this is worth the complication extending the interface. If you care about caching, `ILogger<T> LoggerFactoryExtensions.CreateLogger<T>(this ILoggerFactory factory)` is creating very small object wrapping the cached logger created by `ILogger LoggerFactoryExtensions.CreateLogger(this ILoggerFactory factory, Type type)` . So the real logger still cached. Does your concern about this extra small allocated object?

**Comment by qsdfplkj** [comment]
I think it's even more complicated than I anticipated. CreateLogger(typeof(T).FullName), CreateLogger<T> and CreateLogger(typeof(T)) all should return the same instance.
