### ISSUE TITLE
SeekableDeviceFileStreamStandaloneConformanceTests test failed with overlapped error in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#97133]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=530433
Build error leg or test failing: System.IO.Tests.SeekableDeviceFileStreamStandaloneConformanceTests.Write_Read_Success
Pull request: https://github.com/dotnet/runtime/pull/97078

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "'overlapped' was not allocated by this ThreadPoolBoundHandle instance",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=530433
**Error message validated:** `'overlapped' was not allocated by this ThreadPoolBoundHandle instance`
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 1/18/2024 3:39:11 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by adamsitnik** [comment]
> "'overlapped' was not allocated by this ThreadPoolBoundHandle instance"

This is something very new to me Oo

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0
