### ISSUE TITLE
[mono] Incorrect cast_class for IntPtr[]

### ISSUE THREAD

**Issue by WhiteSmoogy** [dotnet/runtime#97145]
### Description

mono repo has a  intptr array Unit Test code:
https://github.com/dotnet/runtime/blob/13ab6eb58e1c16856cfd3bff2fe69da13d6642af/src/mono/mono/mini/arrays.cs#L693
This test case argues that an integer type array  should be able to convert the pointer type array
It's produce difference value
.Net Framwork = 0
.Net Core = 5

It like there's something wrong with the .Net Framework

**Comment by lambdageek** [comment]
I think it's a problem in `class_composite_fixup_cast_class`:

https://github.com/dotnet/runtime/blob/24f9706ad654bf23e966c04c85c0dafb96a85316/src/mono/mono/metadata/class-init.c#L1021-L1053

the code was introduced in https://github.com/mono/mono/commit/28645403c7a8641648fcfae6f6cf45e018e85f7c and hasn't been updated for .NET 5+

it should probably set `class->cast_cast = mono_defaults.int_class` for `MONO_TYPE_I` and `MONO_TYPE_U`.
(although this code is kind of fragile, so there might be some cascading failures)
