### ISSUE TITLE
Drag and drop the latest outlook mail to the uploader is not working

### ISSUE THREAD

**Issue by YohapujaSelvakumaran** [dotnet/runtime#97150]
### Description

When drag and drop the mail from latest outlook to the uploader  is not working.

**Sample:** https://stackblitz.com/edit/typescript-rypqrp?file=index.html

**Outlook Version**
Version is **1.2024.103.100** (Production).

Client Version is **20240105004.04 .**

### Reproduction Steps

1. Run the sample.
2. Drag and drop the outlook mail to the uploader.

### Expected behavior

Drag and drop the outlook mail should uploaded

### Actual behavior

Drag and drop the outlook mail shouldn't uploaded

**Comment by stephentoub** [comment]
This doesn't appear to be related to .NET, which is the focus of this repo.
