### ISSUE TITLE
System.Text.Json: returning JsonElement[] from WebApi Controller results in huge memory consumption

### ISSUE THREAD

**Issue by the-Dust** [dotnet/runtime#97157]
### Description

When get a large amount of data (hundreds of megabytes to gigabytes) from blob storage, deserialize it as a JsonElement[]  and then return it from a controller, memory consumption suddenly increases by several times and then goes into an infinite sawtooth shape (see the screenshot). 
The problem appears precisely at the stage of returning data from controller. 

![stj_huge_annotations](https://github.com/dotnet/runtime/assets/20787804/e6a28145-e959-4587-aa6b-025d7249ba60)

### Reproduction Steps

The problem can be reproduced on a clean .NET 8 web project.
Code example
```
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Specialized;
using Microsoft.AspNetCore.Mvc;
using System.IO.Compression;
using System.Text.Json;

namespace WebApplication1.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {
        [HttpGet]
        public async Task<JsonElement[]> GetData()
        {
            await using var stream = await GetBlobStreamAsync("path");
            using var decompressed = new GZipStream(stream, CompressionMode.Decompress);
            var result = JsonSerializer.Deserialize<JsonElement[]>(decompressed);
            return result;
        }

        private static async Task<Stream> GetBlobStreamAsync(string path)
        {
            var name = "name";
            var connection = "connection";
            var blob = new BlobContainerClient(connection, name);
            var blobClient = blob.GetBlockBlobClient(path);
            return await blobClient.OpenReadAsync(false);
        }
    }
}
```

### Expected behavior

No additional memory consumption, no infinite sawtooth memory allocations. 

### Actual behavior

Memory consumption suddenly increases by several times and then goes into an infinite sawtooth shape

### Regression?

Also tested on .NET 6 web projects

### Known Workarounds

There is no any problems if deserialize to object[] (or something different from JsonElement[]) but this eliminates all advantages System.Text.Json serializer.

**Comment by eiriktsarpalis** [comment]
Also, does setting the `JsonSerializerOptions.DefaultBufferSize` to a value that is closer to the expected payload eliminate the sawtooth pattern? That would be consistent with the serializer attempting to grow its buffer to a size that fits the full payload.

**Comment by the-Dust** [comment]
@eiriktsarpalis Thank you for the reply.

> In order for us to be able to take a closer look, we would need a minimal and standalone reproduction, i.e. a console app that doesn't use aspnetcore or GZipStream, as well as a means to generate the JSON data you are consuming.

Does it have any sense? The problem appears exactly in the moment of returning data from controller. The data from blob storage deserializes correctly - I can see all rows and their contents under debug.

>Also, does setting the JsonSerializerOptions.DefaultBufferSize to a value that is closer to the expected payload eliminate the sawtooth pattern? That would be consistent with the serializer attempting to grow its buffer to a size that fits the full payload.

I'll try to add this setting to controllers setup and write back later

**Comment by eiriktsarpalis** [comment]
> Does it have any sense? The problem appears exactly in the moment of returning data from controller. The data from blob storage deserializes correctly - I can see all rows and their contents under debug.

But it also serializes correctly as well right? My understanding is that this is a performance issue and not a functional issue. Nevertheless, as mentioned without a self-contained reproduction (that includes the data) I can only speculate as to what might be causing the problem.

**Comment by the-Dust** [comment]
Hi @eiriktsarpalis !
Seems I can reproduce this behavior in a plain console app. The issue can be reproduced on NET6 and NET7, on NET8 I got OOM (so initially I was wrong when I said that this can be reproduced on NET8; anyway OOM looks strange too since I got enough memory).

```
using System.Text.Json;

internal class Program
{
    private const int ArraySize = 2_500_000;

    static void Main(string[] args)
    {
        var memoryStream = new MemoryStream();
        var stream = GenerateData(memoryStream);
        BaseStep(stream);
        Console.ReadLine();
    }

    private static void BaseStep(Stream stream)
    {
        var arr = JsonSerializer.Deserialize<JsonElement[]>(stream);
        var serialized = JsonSerializer.Serialize(arr);
        stream.Position = 0;
    }

    private static Stream GenerateData(MemoryStream memoryStream)
    {
        var str = "{\"Field0\":false,\"Field1\":-1000,\"Field2\":1234,\"Field3\":\"1234\",\"Field4\":\"test1\",\"Field5\":false,\"Field6\":null,\"Field7\":\"test2\",\"Field8\":203,\"Field9\":\"test3\",\"Field10\":203,\"Field11\":\"test4\",\"Field12\":515,\"Field13\":\"test5\",\"Field14\":3433,\"Field15\":\"1122\",\"Field16\":\"test6\",\"Field17\":false,\"Field18\":\"test7\",\"Field19\":null,\"Field20\":false,\"Field21\":null,\"Field22\":\"\",\"Field23\":null,\"Field24\":\"\",\"Field25\":\"test8\",\"Field26\":true,\"Field27\":false,\"Field28\":false,\"Field29\":null,\"Field30\":false,\"Field31\":false,\"Field32\":null,\"Field33\":true,\"Field34\":4,\"Field35\":\"test9\",\"Field36\":\"test10\",\"Field37\":\"test11\",\"Field38\":\"test12\",\"Field39\":null,\"Field40\":null,\"Field41\":0}"; 
        var map = JsonSerializer.Deserialize<Dictionary<string, object>>(str);
        
        var arr = new Dictionary<string, object>[ArraySize];
        for (int i = 0; i < arr.Length; i++)
            arr[i] = map;
        JsonSerializer.Serialize(memoryStream, arr);

        memoryStream.Position = 0;
        return memoryStream;
    }
}
```

**Comment by eiriktsarpalis** [comment]
That repro is doing a number of things, so I'm not sure what I should be focusing on. Judging by the OP I would guess it concerns the final serialization operation and everything up to that point is creating the data? The OOM is expected as presumably it is trying to write to a string that exceeds the maximum permitted length. 

I should say though that this is not an accurate representation of what aspnetcore is doing since it always writes directly to the network stream. If I alter the repro to do that then it completes as expected without incurring substantially more allocations compared to the generation phase:
```C#
using System.Text.Json;

internal class Program
{
    private const int ArraySize = 2_500_000;

    static void Main(string[] args)
    {   
        var elements = GenerateData();
        Console.WriteLine("Data generated");
        GC.Collect();

        BaseStep(elements);
        Console.WriteLine("Done");
    }

    private static void BaseStep(JsonElement[] elements)
    {
        using var fs = new FileStream(@"\\.\NUL", FileMode.OpenOrCreate, FileAccess.Write);
        JsonSerializer.Serialize(fs, elements);
    }

    private static JsonElement[] GenerateData()
    {
        using var memoryStream = new MemoryStream();
        var str = "{\"Field0\":false,\"Field1\":-1000,\"Field2\":1234,\"Field3\":\"1234\",\"Field4\":\"test1\",\"Field5\":false,\"Field6\":null,\"Field7\":\"test2\",\"Field8\":203,\"Field9\":\"test3\",\"Field10\":203,\"Field11\":\"test4\",\"Field12\":515,\"Field13\":\"test5\",\"Field14\":3433,\"Field15\":\"1122\",\"Field16\":\"test6\",\"Field17\":false,\"Field18\":\"test7\",\"Field19\":null,\"Field20\":false,\"Field21\":null,\"Field22\":\"\",\"Field23\":null,\"Field24\":\"\",\"Field25\":\"test8\",\"Field26\":true,\"Field27\":false,\"Field28\":false,\"Field29\":null,\"Field30\":false,\"Field31\":false,\"Field32\":null,\"Field33\":true,\"Field34\":4,\"Field35\":\"test9\",\"Field36\":\"test10\",\"Field37\":\"test11\",\"Field38\":\"test12\",\"Field39\":null,\"Field40\":null,\"Field41\":0}";
        var map = JsonSerializer.Deserialize<Dictionary<string, object>>(str)!;

        var arr = new Dictionary<string, object>[ArraySize];
        for (int i = 0; i < arr.Length; i++)
            arr[i] = map;
        JsonSerializer.Serialize(memoryStream, arr);

        memoryStream.Position = 0;
        return JsonSerializer.Deserialize<JsonElement[]>(memoryStream)!;
    }
}
```
My recommendation remains that you should configure your serializer options so that the `DefaultBufferSize` is set to a sufficiently large number such that it can fit the expected `JsonElement` size.

Hope this helps.

**Comment by the-Dust** [comment]
Hi @eiriktsarpalis ! Sorry for the late answer.

> That repro is doing a number of things, so I'm not sure what I should be focusing on. Judging by the OP I would guess it concerns the final serialization operation and everything up to that point is creating the data?

Yes, I can't just attach 2gb file, so I need to generate some data. The problem appears exact at this point
`var serialized = JsonSerializer.Serialize(arr);`

> I should say though that this is not an accurate representation of what aspnetcore is doing since it always writes directly to the network stream.

I didn't intend to reproduce the exact work of aspnetcore because I can't take into account all the subtleties, instead I wanted to achieve the result I see in my prod using clean console app.

> My recommendation remains that you should configure your serializer options so that the DefaultBufferSize is set to a sufficiently large number such that it can fit the expected JsonElement size.

Do you have any guides on how to configure this setting? I set it to the maximum value (due to huge amounts of data) and it didn't help.

**Comment by eiriktsarpalis** [comment]
> Do you have any guides on how to configure this setting?

I can't provide any concrete guidelines, it's a setting that should be tuned using experimentation on the requirements at hand. The default/initial buffer size is 16K so if the expected payload of the nested `JsonElement` values is expected to be substantially over that, you'd want to pick a value that minimizes the number of resizes per serialization operation. 

I should add that each `JsonElement` instance stores its data using an underlying buffer that has to be allocated for each instance (regardless of how it gets deserialized). Assuming that your data deserializes into multiple `JsonElement` instances each of which incurs a LOH allocation, this will impact the performance of your application no matter what. You might want to consider following a different strategy to read the data (e.g. use a POCO instead of `JsonElement` that explicitly declares the subset of data that your application cares about).

> I set it to the maximum value (due to huge amounts of data) and it didn't help.

Can you clarify? Setting it to `int.MaxValue` will result in OOM being thrown by definition (no array can be that long).
