### ISSUE TITLE
Native AOT "RhpReversePInvoke" and RhpReversePInvokeReturn functions?

### ISSUE THREAD

**Issue by dadavadd** [dotnet/runtime#97162]
![image](https://github.com/dotnet/runtime/assets/111659964/3116a50b-5f50-4ecf-b6b6-710b742dbe35)
I compiled my method using NativeAOT. But after compilation, two more methods were added to it. What are they for?

![image](https://github.com/dotnet/runtime/assets/111659964/91e42d76-34fd-47bd-a9ef-5c88d31df243)

**Comment by jkotas** [comment]
Thread suspension for GC needs to know whether the thread is running a managed code currently. These methods update the thread local state that tracks whether the thread is running a managed code.

You can read more about how it works in https://github.com/dotnet/runtime/blob/main/docs/design/coreclr/botr/threading.md#suspension .
