### ISSUE TITLE
System.NotImplementedException:: ILCompiler.DependencyAnalysis.ReadyToRunHelperNode.EmitInlineTLSAccess  

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#97168]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=531462
Build error leg or test failing: Build / windows-x64 Release NativeAOT_Checked_Libs_SizeOpt / Build product
Pull request: https://github.com/dotnet/runtime/pull/97062

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "ILCompiler.DependencyAnalysis.ReadyToRunHelperNode.EmitInlineTLSAccess",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=531462
**Error message validated:** `ILCompiler.DependencyAnalysis.ReadyToRunHelperNode.EmitInlineTLSAccess`
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 1/18/2024 6:35:26 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[532499](https://dev.azure.com/dnceng-public/public/_build/results?buildId=532499)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/532499/logs/82)||
|[531604](https://dev.azure.com/dnceng-public/public/_build/results?buildId=531604)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/531604/logs/82)||
|[531462](https://dev.azure.com/dnceng-public/public/_build/results?buildId=531462)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/531462/logs/67)|dotnet/runtime#97062|
|[530911](https://dev.azure.com/dnceng-public/public/_build/results?buildId=530911)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/530911/logs/82)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|2|4|4|

**Comment by jkotas** [comment]
Introduced by #89472.

@kunalspathak Number of tests in outter loop native AOT runs are failing with this crash. Could you please take a look?

**Comment by kunalspathak** [comment]
I will take a look

**Comment by kunalspathak** [comment]
We do not inline TLS access if there is a preference for size as seen here:

https://github.com/dotnet/runtime/blob/2f63046c28f2f57f2c8666845f1c1de8696b1626/src/coreclr/jit/helperexpansion.cpp#L445-L460

As stated in https://github.com/dotnet/runtime/pull/89472#discussion_r1458016819, ignoring the `preferSize` increases the binary size. I will add back the hand assembly code.

**Comment by jkotas** [comment]
> ignoring the preferSize increases the binary size. I will add back the hand assembly code.

The binary size increase is very small. I would be fine to take it to make things simpler.

**Comment by kunalspathak** [comment]
> The binary size increase is very small. I would be fine to take it to make things simpler.

Yes, they are. So, I will just ignore the `preferSize`.

| Timeline | Compilation mode | Size of reproNative.exe (in KB) |
|---|---|---|
| Before this PR | --Os | 3981 |
| This PR | --OS | 3981 |
| This PR + ignore preferSize | --OS | 3985 |
| Before this PR | -O | 4041 |
| This PR | -O | 4044 |
