### ISSUE TITLE
C# program stops at wrong line after IndexOutOfRangeException

### ISSUE THREAD

**Issue by graciez** [dotnet/runtime#97175]
### Description

C# program stops at the wrong line after an IndexOutOfRangeException is thrown. The issue repros on .NET and .NET framework. Both VS debugger and WinDbg show the line after the one where the exception is thrown. It seems that runtime doesn't not tell the correct instruction where we are stopped. BTW, the issue only repros on setting.

![image](https://github.com/dotnet/runtime/assets/69225371/36e26b96-0a4b-4836-8d32-67460a12c433)

### Reproduction Steps

1. create a simple C# .NET console app and add the code like below
```
internal class Program
{
    static void Main(string[] args)
    {
        double[,] mat = new double[3, 3];
        mat[3, 1] = 2;                     // set a value
        Console.WriteLine(mat[0, 0]);      // debugger stops here
    }
}
```

2. start debugging

### Expected behavior

The program stops at the correct instruction.

### Actual behavior

The program stops at one line after the exception is thrown.

**Comment by thaystg** [comment]
Fixed partially in #98953, the other part was fixed on VS/VSCode side.
