### ISSUE TITLE
add test queue for RedHat 8

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#972]
While we sunsetting RH6, (#423) RH8 is out. Since we support last to major versions we should be testing them as well. 

https://developers.redhat.com/blog/2019/05/07/red-hat-enterprise-linux-8-now-generally-available/

cc: @tmds

**Comment by ViktorHofer** [comment]
cc @bartonjs @danmosemsft

**Comment by ViktorHofer** [comment]
We need this for 5.0 as we state to support 7+. cc @safern

**Comment by NikolaMilosavljevic** [comment]
This is not installer or setup related.

**Comment by dleeapho** [comment]
RHEL VMs are not suitable for public-facing infra since it requires `subscription-manager` registration to be functional. I would suggest using CentOS instead per Red Hat's guidance. An alternative is to switch to containerized solutions such as [UBI](https://developers.redhat.com/products/rhel/ubi)

**Comment by safern** [comment]
We do have a CentOS8 docker image already for building but not for testing. @MattGal @Chrisboh do you think someone from the dnceng team could help adding a helix image to test on CentOS 8?

https://github.com/dotnet/dotnet-buildtools-prereqs-docker/tree/master/src/centos/8

**Comment by MattGal** [comment]
> RHEL VMs are not suitable for public-facing infra since it requires `subscription-manager` registration to be functional. I would suggest using CentOS instead per Red Hat's guidance. An alternative is to switch to containerized solutions such as [UBI](https://developers.redhat.com/products/rhel/ubi)

@dleeapho : Let's chat when you can, perhaps in a different venue.   We have been providing public-facing Helix RHEL 6 and 7 VMs for some time, there's some magic in the Azure gallery images that doesn't require us to deal with subscription managers.

**Comment by ericstj** [comment]
@MattGal / @dleeapho any update on this?

**Comment by MattGal** [comment]
> @MattGal / @dleeapho any update on this?

I haven't had a conversation with Dan, but I think I know everything I need to know in this space.

- We have some real challenges for test machines w.r.t. core availability in the post-COVID world, as such we're trying very hard to avoid growing new Linux queues where possible.  
- With RedHat, docker-ization from an Ubuntu machine (or any non-RHEL) is blocked, so we'd have to stand up such machines as a new queue (possibly installing docker on RHEL 7 / 8 and using this for future RHEL?)
- RHEL 6 goes out of service in a few months (11/30/2020) so its queue capacity could contribute to RHEL 8's.

@Chrisboh will discuss this Thursday @ CI council.

**Comment by ViktorHofer** [comment]
Note to myself, we should discuss this in next CI council's meeting. Also we should discuss if we need this for 5.0 and 3.x/2.x.

**Comment by MattGal** [comment]
From chatting with Eric it looks like RHEL 6 usage is already way down and could be swapped out for 8 soon.

**Comment by ViktorHofer** [comment]
@MattGal do you think we should replace RHEL6 with RHEL8 in servicing branches as well?

**Comment by MattGal** [comment]
Ideally, it should be remove from 2.x and 3.1 before we remove support for it from Helix, so it doesn't fail your test runs.  

As for adding RHEL 8 support to the release branches, I think that's more of a @leecow question and I think would hinge based on whether we officially state support for RedHat 8 for that release.

**Comment by dleeapho** [comment]
RHEL6 is also a @leecow question.

**Comment by danmosemsft** [comment]
@leecow ?

**Comment by leecow** [comment]
RHEL 6 will reach 'end of maintenance' 11/30 so we'll change our support statement for 2.1 and 3.1 with the December release (meaning November will be the last month RHEL 6 is supported).

**Comment by tmds** [comment]
@MattGal @leecow it would be very useful to have a RHEL8 CI machine because both Microsoft and Red Hat will be supporting .NET 5 on RHEL8.

Can you also look into adding a RHEL8 arm64 machine? We're seeing some issues: https://github.com/dotnet/runtime/issues/43349.
We want to provide .NET on arm64 when we are able to source-build it.

cc @omajid

**Comment by MattGal** [comment]
> @MattGal @leecow it would be very useful to have a RHEL8 CI machine because both Microsoft and Red Hat will be supporting .NET 5 on RHEL8.
> 
> Can you also look into adding a RHEL8 arm64 machine? We're seeing some issues: #43349.
> We want to provide .NET on arm64 when we are able to source-build it.
> 
> cc @omajid

AFAIK, RedHat still doesn't directly support running inside non-redhat docker hosts.  Generally, Centos support has been deemed sufficient to cover this on ARM64.

**Comment by tmds** [comment]
> AFAIK, RedHat still doesn't directly support running inside non-redhat docker hosts. Generally, Centos support has been deemed sufficient to cover this on ARM64.

CentOS8 and RHEL8 are built from the same source code. RHEL8 is supported by Red Hat, and CentOS8 is supported by the CentOS community. Using either in the CI setup is fine.

Does this issue also track adding an ARM64 RHEL8/CentOS8 machine? Any idea when these machines will be added?

**Comment by karelz** [comment]
@wfurt is this still needed or did we forget to close it?
Can you please update milestone to 5.0.x (5.0 servicing) or 6.0 as appropriate? Thanks!

**Comment by karelz** [comment]
@wfurt ping?

**Comment by wfurt** [comment]
it seems like there is still no helix queue: https://helix.dot.net

I see that in some cases we use  both Centosx7 and RedHat.7. It would make sense to me to flip one of them to 8 as testing both seems to provide little value. (@tmds to confirm) 

While debate about ARM may linger, I still see value in x64 -> to cover issues with different library versions (like OpenSSL traditionally gives us ongoing pain)

**Comment by MattGal** [comment]
That is correct.  I had a chat with @wfurt and created https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/389/files which we believe addresses test coverage for RHEL8.

**Comment by wfurt** [comment]
thanks to @MattGal, we have images and I have PR ready for runtime. 
Since Hollidays are upon us, I start wondering if it is wise to merge even if it comes clean. 
Unless somebody feels there is urgency, I'll hold off the merge until next year to decrease risk of disturbance.
