### ISSUE TITLE
Emulated x86 and x64 .NET 8 on AARCH64 can't restore project

### ISSUE THREAD

**Issue by kurt-mueller-osumc** [dotnet/runtime#97228]
### Description

Similar to https://github.com/dotnet/runtime/issues/71856, on arm64 computer (i.e. macbook pro) when targeting the `linux/amd64` platform during a docker build, commands like `dotnet restore` will hang indefinitely.

The only way to rectify this is be setting the `DOTNET_EnableWriteXorExecute=0` environment variable. However, this cause the docker container to respond slowly (I use the docker container as a dev environment).

A simple repo with this reproduced is found here:

https://github.com/kurt-mueller-osumc/dotnet-amd64/tree/main

### Reproduction Steps

1. Be on an arm64 computer like a macbook pro.
2. Clone this repo: https://github.com/kurt-mueller-osumc/dotnet-amd64/tree/main
3. Run the command `docker build --platform linux/amd64 .`

### Expected behavior

Ideally, `dotnet restore` should simply work :).

### Actual behavior

`dotnet restore` hangs.

### Known Workarounds

Add this line to the Dockerfile:

```Dockerfile
ENV DOTNET_EnableWriteXorExecute=0
```

**Comment by mangod9** [comment]
@kurt-mueller-osumc, is this still failing for you on the latest .NET 8 servicing release?

**Comment by janvorli** [comment]
The issue was fixed in .NET 9 and it was backported to .NET 8 where it will go into a servicing release.
