### ISSUE TITLE
Unable to resolve service for type '...' while attempting to activate '...'.

### ISSUE THREAD

**Issue by qsdfplkj** [dotnet/runtime#97239]
### Description

The following cause the invalid operation exception: 

_Unable to resolve service for type '...' while attempting to activate '...'_

```csharp
public interface IIssue { }

public class Issue : IIssue { }

public interface ITest { }

public class Test(in IIssue issue) : ITest       //<-- note the in keyword that cause the issue.
{
    private readonly IIssue _issue = issue;
}

public class Extensions
{
    public static IServiceCollection AddTestCase(this IServiceCollection services)
    {
        services.TryAdd(ServiceDescriptor.Singleton<IIssue, Issue>());
        services.TryAdd(ServiceDescriptor.Singleton<ITest, Test>());
        return services;
    }
}

    public void TestIt()
    {
        ServiceCollection services = new();
        services.AddTestCase();
        var serviceProvider = services.BuildServiceProvider();
        var test = serviceProvider.GetRequiredService<ITest>();
    }
```

### Reproduction Steps

See above.

### Expected behavior

The service should be resolved. 

### Actual behavior

It cause an exception:
  System.InvalidOperationException : Unable to resolve service for type '...**.&**' while attempting to activate '...'.
  
Note that the message also contains the & symbol.

### Known Workarounds

remove `in` from the primary constructor

### Configuration

Windows 11 VS 2022 .Net 8

**Comment by huoyaoyuan** [comment]
Note that using `in` with claas type is meaningless. It should only be used with *large* struct type.

**Comment by qsdfplkj** [comment]
When used outside of the dependency container it requires the read only property. Otherwise you can't specify it to be read only.

**Comment by tannergooding** [comment]
> When used outside of the dependency container it forces the read only parameter to be read only. Otherwise you can't specify it to be read only.

It does not: https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7NAExAGoAfAAQCYBGAWAChGA3AQygAIwOBeDvGAHcOAYQAUASgDcjCjQCcYsADoAGtMaMRygLJKNDOYpXqZTQwGYO1URwDejDk+tWAlngwdV9jgHMYGFIcAM4BQQC+js5RThRWckjWKBx67rZgEjH2Wc5carwcAKxmuZEMZUA==

It does disallow something like this:
```csharp
public static void N(in C c)
{
    c = new C();
}
```

But that is an implementation detail of `N` and is not externally visible to the user. As such it serves no real purpose, could instead be handled as an analyzer if you wanted to prevent yourself from reassigning a parameter locally, and definitively causes perf issues because it adds another indirection onto every access of `c` (which in turn can prevent other optimizations, devirtualizations, etc).

It being `in` and being an additional indirection also only means that `M` can't reassign. It is entirely valid for another thread or context to also have access to `c` and to reassign it, which `M` would then pick up and that can also be undesirable in most scenarios.

**Comment by tannergooding** [comment]
It sounds like you want `public static void N(readonly C c)`, which is covered by https://github.com/dotnet/csharplang/blob/main/proposals/readonly-parameters.md and various related discussions on the csharplang repo.

This would still be shallow immutability, much like `readonly C c;` as the field of a class or struct is, but it covers what seems to be your desire without the pessimizations or other issues that using `in C c` or `ref readonly C c` will cause.

I'd recommend voicing your need and use case on the related discussion thread/issues.

**Comment by qsdfplkj** [comment]
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/method-parameters?WT.mc_id=dotnet-00000-bramin#in-parameter-modifier

_"The in modifier allows the compiler to create a temporary variable for the argument and pass a **readonly** reference to that argument."_



> It sounds like you want `public static void N(readonly C c)`, which is covered by https://github.com/dotnet/csharplang/blob/main/proposals/readonly-parameters.md and various related discussions on the csharplang repo.
> 
> This would still be shallow immutability, much like `readonly C c;` as the field of a class or struct is, but it covers what seems to be your desire without the pessimizations or other issues that using `in C c` or `ref readonly C c` will cause.
> 
> I'd recommend voicing your need and use case on the related discussion thread/issues.

I'm not sure about the difference between readonly and the in parameter. But either way I want the serviceprovider to be able to resolve my dependency with or without the in modifier.

**Comment by qsdfplkj** [comment]
@tannergooding  I did some more reading and I do get it now. The in parameter is more like a ref. So can be changed indeed across threads. The serviceprovider shouldn't try to resolve something like that.
