### ISSUE TITLE
Process Start method behaving differently

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/runtime#97233]
### Description

Earlier, the `Process.Start()` method would identify the appropriate application when passed with the scheme (if it's a URI) or the file extension (if the argument is a file).

But now it's throwing a Win32 exception. See other info for stack trace.

### Reproduction Steps

* Create a console app
* Open the Program.cs file
* Add this piece of code at the fag end
* Build and run the app

```cs
System.Diagnostics.Process.Start("https://egvijayanand.in/");
```

### Expected behavior

This should open the default Web Browser (as argument is URL with scheme is http(s)) and try to load the URL provided.

Try to pass a filename (like Word Document/Excel Workbook) and it behaves the same.

### Actual behavior

Ends up in a Win32 exception. See other info for stack trace.

### Regression?

Not sure. But have worked with this before.

### Known Workarounds

Haven't found anything.

### Configuration

.NET Version: 8.0.200-preview.23624.5
Windows 11 x64: 10.0.22631.3007

### Other information

```
Unhandled exception. System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'https://egvijayanand.in/' with working directory 'E:\Tasks\ConsoleApp'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Program.<Main>$(String[] args) in E:\Tasks\ConsoleApp\Program.cs:line 6
```

**Comment by MichalPetryka** [comment]
In .Net 6-8 and Core you have to set `ProcessStartInfo.UseShellExecute` to `true` to enable opening of non executables like this.

**Comment by egvijayanand** [comment]
> In .Net 6-8 and Core you have to set `ProcessStartInfo.UseShellExecute` to `true` to enable opening of non executables like this.

This should've been an implicit action if the input is a URI.

**Comment by danmoseley** [comment]
@egvijayanand The breaking change note is here: it was done for performance.

https://learn.microsoft.com/en-us/dotnet/core/compatibility/fx-core#change-in-default-value-of-useshellexecute
