### ISSUE TITLE
CryptographicException with app crash when signing XML using System.Security.Cryptography.Xml

### ISSUE THREAD

**Issue by MssGpr75** [dotnet/runtime#97242]
### Description

ComputeSignature method of System.Cryptography.Xml.SignedXml raises a CryptographicException when app is built in release mode.

In debug mode works fine.

In Xamarin the same code worked fine for years.

### Steps to Reproduce

1. Create a new MAUI project
2. Create a new page with a single button
3. Implement digital signature of an XML document following MS documentation [MSLearn](https://learn.microsoft.com/en-us/dotnet/standard/security/how-to-sign-xml-documents-with-digital-signatures)
4. Click the button: in release the application crashes

### Link to public reproduction project repository

https://github.com/MssGpr75/MauiAppCrash.git

### Version with bug

8.0.5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12, Android 13

### Did you find any workaround?

Workaround: in Project settings unckeck "Enable Ahead-of-Time (AOT) compilation" and "Enable trimming" for Release configuration

**Comment by danmoseley** [comment]
Can you share stack trace and exception message?

**Comment by vcsjones** [comment]
This is a trimming issue. Your CryptographicException is probably:

> CryptographicException
System.Security.Cryptography.CryptographicException: Could not create hash algorithm object. If the application has been trimmed, ensure the required algorithm implementations are preserved.

Which is supported by your work around that disabling trimming fixes it. You should be getting a trimming warning when you build your application:

> Trim analysis warning IL2026: MauiAppCrash.SecurityHelper.RASSignXml(XmlDocument&, String&): Using member 'System.Security.Cryptography.Xml.SignedXml.SignedXml(XmlDocument)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. The algorithm implementations referenced in the XML payload might be removed. Ensure the required algorithm implementations are preserved in your application.

S.S.C.Xml [is known](https://github.com/dotnet/runtime/issues/73432#issuecomment-1206604301) to not be trimming friendly.

You can fix this by ensuring the necessary types are kept from being trimmed. 

First, create an XML file in your project:

```xml
<linker>
    <assembly fullname="System.Security.Cryptography">
        <type fullname="System.Security.Cryptography.SHA1" />
        <type fullname="System.Security.Cryptography.SHA256" />
        <type fullname="System.Security.Cryptography.SHA1CryptoServiceProvider" />
        <type fullname="System.Security.Cryptography.SHA256CryptoServiceProvider" />
        <type fullname="System.Security.Cryptography.SHA1Managed" />
        <type fullname="System.Security.Cryptography.SHA256Managed" />
        <type fullname="System.Security.Cryptography.RSAPKCS1SignatureFormatter" />
        <type fullname="System.Security.Cryptography.RSAPKCS1SignatureDeformatter" />
    </assembly>
</linker>
```

Then, in your project file, add this to an `ItemGroup`:


```xml
<TrimmerRootDescriptor Include="trim.xml" />
```

Where the name of the XML file is what you added to your project.

That will stop the necessary things from being trimmed. In the example I gave above, it will keep all of the parts for SHA-1 and SHA-256. If you expect you will need to handle more hash algorithms, then you should add the SHA384/SHA512 variants as well.

**Comment by MssGpr75** [comment]
This worked for me.
Tomorrow I will do some additional tests, and I will post final results.
By now, really thank you @vcsjones !

**Comment by vcsjones** [comment]
> This worked for me.

Glad to hear it. I opened #97274 as a separate issue to see if we can make this "just work" or improve the experience.
