### ISSUE TITLE
System.IO.Pipelines Specified argument was out of the range of valid values (Thread safety)

### ISSUE THREAD

**Issue by DomenPigeon** [dotnet/runtime#97247]
### Description

It's really strange but it seems to me that pipe.Writer.Write method is not threadsafe.

### Reproduction Steps

Non working test:
```csharp
    [Fact]
    public async Task PipeTest()
    {
        const int count = 1000;
        var pipe = new Pipe();

        var tasks = new List<Task>();
        for (var i = 0; i < count; i++)
        {
            tasks.Add(Task.Run(async () =>
            {
                pipe.Writer.Write(Encoding.Default.GetBytes("test"));
                await Task.Yield();
                pipe.Writer.Write(Encoding.Default.GetBytes("test"));
            }));
        }

        await Task.WhenAll(tasks);

        await pipe.Writer.FlushAsync();
        await pipe.Writer.CompleteAsync();
        var result = await pipe.Reader.ReadAsync();

        var message = Encoding.Default.GetBytes("test");
        Assert.Equal(2 * count * message.Length, result.Buffer.Length);
    }
```

But the test is flaky, so for me in order to get 100% failure rate I need to do this:
```csharp
    [Fact]
    public async Task RunTests()
    {
        for (var i = 0; i < 100; i++)
        {
            await PipeTest();
        }
    }
```
This throws: `System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'bytes')`

But the same test passes all the time for me if I add a lock:
```csharp
 [Fact]
    public async Task PipeTestLock()
    {
        const int count = 1000;
        var syncRoot = new object();
        var pipe = new Pipe();

        var tasks = new List<Task>();
        for (var i = 0; i < count; i++)
        {
            tasks.Add(Task.Run(() =>
            {
                lock (syncRoot)
                    pipe.Writer.Write(Encoding.Default.GetBytes("test"));

                lock (syncRoot)
                    pipe.Writer.Write(Encoding.Default.GetBytes("test"));
            }));
        }

        await Task.WhenAll(tasks);

        await pipe.Writer.FlushAsync();
        await pipe.Writer.CompleteAsync();
        var result = await pipe.Reader.ReadAsync();

        var message = Encoding.Default.GetBytes("test");
        Assert.Equal(2 * count * message.Length, result.Buffer.Length);
    }
```

This passes for me 100% of the time:
```csharp
    [Fact]
    public async Task RunTestsLock()
    {
        for (var i = 0; i < 100; i++)
        {
            await PipeTestLock();
        }
    }
```

### Expected behavior

No exception is thrown, write method is thread safe.

### Actual behavior

No exception is thrown, write method is thread safe.ystem.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'bytes')

### Regression?

I tested this on .net8.0

**Comment by stephentoub** [comment]
Pipelines is single-writer/single-reader, meaning it's thread safe to be using a writer and a reader for the same pipe concurrently, but it is not safe for multiple threads to use the same writer concurrently or for multiple threads to use the same reader concurrently. If you need that, you need to supply your own synchronization, eg locking around the writes your repro.

**Comment by danmoseley** [comment]
@DomenPigeon are the docs unclear on this point? If so, we would welcome a PR to tweak them. Click the pencil icon on the doc page.

**Comment by DomenPigeon** [comment]
@stephentoub Thanks for you answer and sorry for not being attentive enough.
@danmoseley I have rechecked the docs and indeed this is stated
I was my assumption that they are thread safe as pipes are by default used in async contexts, just not in the way I have assumed.
