### ISSUE TITLE
In a blazor wasm component, CultureInfo.GetCultureInfo("tr-TR").DateTimeFormat.DayNames returns not the Turkish names, but English day names

### ISSUE THREAD

**Issue by sedatyilmazer** [dotnet/runtime#97252]
### Description

I've a Blazor WebAssemly Standalone App, where I need to display the Turkish names. When I use the following code in the webassembly componet:

```c#
    var dayNames = CultureInfo.GetCultureInfo("tr-TR").DateTimeFormat.DayNames;
```

I get English day names. If I use the same in a console app, it returns Turkish day names as it should. Is there anything wrong with the wasm System.Globalization assembly?

Note: Same line returns French and German day names correctly (when I switch the culture). Are there some missing culture definitions to minimize the assembly size? If so, is there a way to add a custom culture definition for unsupported cultures?

Regards.

### Reproduction Steps

In the default blazor webassembly standalone app, add the following line after  Welcome header

```c#
ToDay: @CultureInfo.GetCultureInfo("tr-TR").DateTimeFormat.DayNames[(int)DateTime.Now.DayOfWeek];
```

### Expected behavior

It should display a Turkish day name (  "Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma", "Cumartesi", "Pazar" )

### Actual behavior

It displays the current day in English

### Configuration

.NET core 8

**Comment by maraf** [comment]
By default Blazor app uses "Sharded globalization", meaning that based on selected culture, it loads part of the globalization data. This selection is happening before any C# code running. You have two options

a) Select culture before Blazor starts. This solution is good if you know that you will need a single culture in your app. Update the `index.html`
```html
<script src="_framework/blazor.webassembly.js" autostart="false"></script>
<script>
    Blazor.start({
        applicationCulture: 'tr-TR'
    });
</script>
```

b) Load all globalization data. This solution is good if you know you will need to use multiple cultures in your app. Note that this option will increase your download size. Update the `csproj`
```xml
<PropertyGroup>
  <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
</PropertyGroup>
```

**Comment by ilonatommy** [comment]
@sedatyilmazer, as @maraf pointed out, you can choose between the two listed options or the 3rd one:

c) Prepare custom ICU bundle, following the steps from [doc](https://github.com/dotnet/runtime/blob/89bba37a92053f52e38d5a5c81a1f3510319dabf/docs/design/features/globalization-icu-wasm.md?plain=1#L17). There's also a discussion how to do it [here](https://github.com/dotnet/runtime/issues/53239#issuecomment-1358010791). Then you would be able e.g. to add "tr-TR" to the default [EFIGS bundle](https://github.com/ilonatommy/icu/blob/dotnet/main/icu-filters/icudt_EFIGS.json) and replace the existing one.
