### ISSUE TITLE
System.InvalidOperationException on custum Content-Type for HttpClient

### ISSUE THREAD

**Issue by ramin-guliyev** [dotnet/runtime#97271]
I am trying to set custom Content-Type for System.Net.Http.HttpClient. I am getting  InvalidOperationException when add custom content type for httpclient .  Code example is in below:
```c#
using (HttpClient httpClient = new HttpClient())
{
    httpClient.BaseAddress = new Uri("https://www.google.com/");
    httpClient.DefaultRequestHeaders.Clear();
    try
    {
        httpClient.DefaultRequestHeaders.Add("Content-Type",
            "application/vnd.my.response+json;version=2");
    }
    catch (Exception ex)
    {
        //InvalidOperationException 
        throw;
    }
}
```

Exception says: System.InvalidOperationException: 'Misused header name, 'Content-Type'. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects.'

I tryed the same thing with old System.Net.WebClient and RestSharp all works as expected. How can I add custom content type to my requests?

**Comment by chrisoverzero** [comment]
As the error message says, this is wrong place to set the “content-type” header. Because it is a content header, it should be set on the content of the request. (That is, it should be set on the value which you are assigning to the `Content` property of a value of type `HttpRequestMessage`.)

**Comment by ramin-guliyev** [comment]
@chrisoverzero thanks for your comment, can you provide
