### ISSUE TITLE
[API Proposal]: Add analyzer to remind of awaits without ConfigureAwait(false)

### ISSUE THREAD

**Issue by ygoe** [dotnet/runtime#97275]
### Background and motivation

I'm currently writing lots of library code. From what I can read, all library code should only `await` with `ConfigureAwait(false)` to avoid scheduler posting issues. The problem is, I always forget that while I'm writing the `await` call. I don't even notice awaiting anything anymore, so there's no hook in my brain that I could attach that additional (and somewhat annoying) method call to.

### API Proposal

I think there could be some csproj option that would indicate that this is a library project and all `await`s without `ConfigureAwait(false)` are not desired. I would get aware of this suggestion or warning and could fix it.

### API Usage

```xml
<PropertyGroup>
  <RequireConfigureAwait>true</RequireConfigureAwait>
</PropertyGroup>
```

An option in the .editorconfig file to change the severity from suggestion to warning (if not already the default) would be helpful to make this more visible.

### Alternative Designs

Manual work: find in all files `await` and scan through all results where that method call is missing at the end of the line. It's a tedious task and will give false positives when the await call is wrapped over multiple lines.

### Risks

None. It's opt-in and just an analyzer.

**Comment by stephentoub** [comment]
This already exists:
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2007

**Comment by vcsjones** [comment]
There is already an analyzer for this for rule [CA2007](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2007). You just need to enable it.

Put an `.editorconfig` file next to your project file, and add something like this to it:

```ini
[*.cs]
dotnet_diagnostic.CA2007.severity = warning
```

With the rule enabled:

<img width="887" alt="image" src="https://github.com/dotnet/runtime/assets/361677/9be0c43c-2224-4a23-9d83-09713e9293f3">

**Comment by ygoe** [comment]
@vcsjones Nice, thank you! And I like your response better because it actually told me how to enable it. 🙂 I was searching here for such issues but guess I've overlooked it elsewhere.
