### ISSUE TITLE
CI unable to find file copied from runtime-assets

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#97307]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=535117
Build error leg or test failing: System.Text.RegularExpressions.Tests.RegexKnownPatternTests.PatternsDataSet_ConstructRegexForAll
Pull request: https://github.com/dotnet/runtime/pull/97283

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "System.IO.FileNotFoundException : Could not find file.*Regex_RealWorldPatterns.json",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=535117
**Error message validated:** `System.IO.FileNotFoundException : Could not find file.*Regex_RealWorldPatterns.json`
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 1/22/2024 2:09:37 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[535117](https://dev.azure.com/dnceng-public/public/_build/results?buildId=535117)|dotnet/runtime|[System.Text.RegularExpressions.Tests.RegexKnownPatternTests.PatternsDataSet_ConstructRegexForAll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=535117&view=ms.vss-test-web.build-test-results-tab&runId=12641790&resultId=200832)|dotnet/runtime#97283|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|1|1|

**Comment by akoeplinger** [comment]
Pretty sure this is because of this test which was added in https://github.com/dotnet/runtime/pull/96462 since it uses `Environment.CurrentDirectory = TestDirectory;` and if another test runs concurrently the working directory will be different:

https://github.com/dotnet/runtime/blob/86f25ad9bd314d5ffaca2c4aa18c56347497aaa7/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/Regex.CompileToAssembly.Tests.cs#L42-L69

Other tests which modify `CurrentDirectory` do so in a RemoteExecutor, @stephentoub would that be acceptable here or does it interfere with the "simple" use case of this test?

**Comment by ViktorHofer** [comment]
This seems to be an issue specific to the Regex test invocation. I can see the `Regex_RealWorldPatterns.json` file in the test payload folder (the test output directory that gets sent to Helix to run the test):

![image](https://github.com/dotnet/runtime/assets/7412651/f528d2f7-11bb-49ac-ac8e-1444e3daaa72)


Payload URL: https://helixde107v0xdeko0k025g8.blob.core.windows.net/helix-job-efb12d6f-348f-4962-a382-df1277914ca47d8fcc2dcf04fccba/System.Text.RegularExpressions.Tests.zip?helixlogtype=result

Looking at the path `/private/tmp/helix/working/A43408F3/t/#RegexCompileToAssemblyTests_yiwsruqa.fkz/Regex_RealWorldPatterns.json`, I'm not sure if that's the right path based on the console log. `/private/tmp/helix/working/A43408F3/w/B74809A4/e` seems to be the folder that contains the json file.

**Comment by stephentoub** [comment]
@akoeplinger is likely right. I'll fix.
