### ISSUE TITLE
JsonDocument JsonSerializer.Deserialize does not match JsonDocument.Parse for null root elements 

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/runtime#97323]
### Description

Given the following code 

```cs
using System.Text.Json;

JsonSerializer.Deserialize<JsonDocument>("null");
```

It returns null instead of JsonDocument.s_nullLiteral.

I'm assuming this is because the converter was never implemented with an overridden HandleNull in https://github.com/dotnet/runtime/pull/34537.

For T = JsonElement things work right due to the converter defaulting to HandleNullOnRead as it's a struct type.

### Reproduction Steps

See description

### Expected behavior

Returns "null" not null

### Actual behavior

Returns null

**Comment by eiriktsarpalis** [comment]
> I'm assuming this is because the converter was never implemented with an overridden HandleNull in #34537.

It seems like a reasonable assumption, this should be updated so that `null` values are handled appropriately. Would you like to contribute a PR?

Related to https://github.com/dotnet/runtime/issues/68128.
