### ISSUE TITLE
JIT: Assert `varTypeUsesFloatReg(tree)` blocking libraries-jitstress

### ISSUE THREAD

**Issue by amanasifkhalid** [dotnet/runtime#97345]
[runtime-coreclr libraries-jitstress](https://dev.azure.com/dnceng-public/public/_build?definitionId=138&_a=summary) is blocked on multiple platforms by the following assert:

```
Assert failure(PID 73722 [0x00011ffa], Thread: 73738 [0x1200a]): Assertion failed 'varTypeUsesFloatReg(tree)' in 'System.Numerics.Tensors.TensorPrimitives:<InvokeSpanScalarIntoSpan>g__Vectorized256|223_2[ulong,System.Numerics.Tensors.TensorPrimitives+IdentityOperator`1[ulong],System.Numerics.Tensors.TensorPrimitives+MinMagnitudePropagateNaNOperator`1[ulong]](byref,ulong,byref,ulong)' during 'Hoist loop code' (IL size 2145; hash 0x61d9c93c; FullOpts)

    File: /__w/1/s/src/coreclr/jit/optimizer.cpp Line: 4167
    Image: /datadisks/disk1/work/B0A70986/p/dotnet
```

[Failure log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-97184-merge-cd16be0e43514d5899/System.Numerics.Tensors.Net8.Tests/1/console.5da3f8ad.log?helixlogtype=result) from a recent run on Windows x64. cc @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
Looks like only x86/x64, on 2 Tensors tests.

cc @tannergooding
