### ISSUE TITLE
Update of libunwind to 1.8.0 has broken remote unwind 

### ISSUE THREAD

**Issue by janvorli** [dotnet/runtime#97343]
While running some debugging tests, I've hit a SIGSEGV in the unwinder during remote unwind. It stems from an incorrect change made in the libunwind in src/dwarf/Gget_proc_info_in_range.c in https://github.com/libunwind/libunwind/pull/524. Reverting change in that file fixes the problem.

**Comment by am11** [comment]
Fixed by https://github.com/dotnet/runtime/pull/97813.
