### ISSUE TITLE
AOT compiler generates invalid assembler code for Mac Catalyst in .NET 9

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#97342]
### Description

AOT compiler generates invalid assembler code for Mac Catalyst in .NET 9

### Reproduction Steps

Test case: [aot-compiler-test-case-fa0f17e.zip](https://github.com/dotnet/runtime/files/14014981/aot-compiler-test-case-fa0f17e.zip)

Unzip and run test.sh. The script will download the AOT compiler for 9.0.0-alpha.1.24066.33 and AOT compile the file `linked/Microsoft.Maui.Controls.dll` + (try to) compile the resulting assembler code.

### Expected behavior

Valid assembler code.

### Actual behavior

```
Microsoft.Maui.Controls.dll.s:91707:10: error: unexpected token in '.loc' directive
.loc 107 -8 0
         ^
Microsoft.Maui.Controls.dll.s:224390:10: error: unexpected token in '.loc' directive
.loc 249 -11 0
         ^
Microsoft.Maui.Controls.dll.s:445252:10: error: unexpected token in '.loc' directive
.loc 431 -3 0
         ^
Microsoft.Maui.Controls.dll.s:452970:10: error: unexpected token in '.loc' directive
.loc 445 -44 0 prologue_end
         ^
```

Resulting .s file: 
[Microsoft.Maui.Controls.dll.s.zip](https://github.com/dotnet/runtime/files/14014998/Microsoft.Maui.Controls.dll.s.zip)

### Regression?

Yes, this works in .NET 8.

### Known Workarounds

None

### Configuration

9.0.0-alpha.1.24066.33

### Other information

This is blocking MAUI from building packages for .NET 9.

**Comment by rolfbjarne** [comment]
CC @vargaz

**Comment by steveisok** [comment]
@vargaz can you please look into this?

**Comment by vargaz** [comment]
This appears to be a problem with either the debug info in the pdb file, or its decoding. Need more time to investigate, added a workaround in a PR.

**Comment by vargaz** [comment]
I think this is caused by:
https://github.com/dotnet/runtime/pull/96497

**Comment by vargaz** [comment]
The problematic PR was reverted on master/9.0.
