### ISSUE TITLE
[API Proposal]: Get the managed size of a System.Type instance

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#97344]
### Background and motivation

As part of the same problem as https://github.com/dotnet/runtime/issues/97341, we have a scenario where we have a `System.Type`, we cannot rewrite the code in an AOT-safe manner to represent the type as a generic argument, and we want to be able to call `Unsafe.SizeOf<T>` for our `System.Type` instance.

This issue proposes a new method to get the size of the instance of a managed type from its `RuntimeTypeHandle`.

### API Proposal

```diff
namespace System.Runtime.CompilerServices;

public class RuntimeHelpers
{
+    public static int SizeOf(RuntimeTypeHandle type);
}
```

### API Usage

```csharp
var abi_element_size = RuntimeHelpers.SizeOf(AbiType.TypeHandle);
var byte_length = length * abi_element_size;
m._array = Marshal.AllocCoTaskMem(byte_length);
m._marshalers = new object[length];
var element = (byte*)m._array.ToPointer();
for (int i = 0; i < length; i++)
{
    m._marshalers[i] = Marshaler<T>.CreateMarshaler(array[i]);
    Marshaler<T>.CopyAbi(m._marshalers[i], (IntPtr)element);
    element += abi_element_size;
}
```

### Alternative Designs

We could place the API on `System.Runtime.CompilerServices.Unsafe` next to `SizeOf<T>()`.

**Comment by AaronRobinsonMSFT** [comment]
Related https://github.com/dotnet/runtime/issues/24200

**Comment by MichalStrehovsky** [comment]
Would this work for both reference types and value types? My proposal would be to either make this throw for non-valuetypes, or have it return `IntPtr.Size`, same as `Unsafe.SizeOf<T>`.

Size of classes is tricky (do we want the aligned or unaligned size?) and unless we have a use case to decide what size this is, it's better to just proactively block it. Nothing good would probably come out of it.

**Comment by jkoritzinsky** [comment]
I honestly don't care about the experience for reference types. I think either having it throw or return `IntPtr.Size` is reasonable.

**Comment by EgorBo** [comment]
Should it be

```diff
namespace System.Runtime.CompilerServices
{
  public static class Unsafe
  {
    public static int SizeOf<T>();
+   public static int SizeOf(Type type);
    ...
```

instead? To improve API discoverability and I think we use this pattern for some other APIs, e.g. `RuntimeHelpers.IsReferenceOrContainsReferences`

**Comment by tannergooding** [comment]
👍 to Egor's suggestion, having it as a neighboring overload is definitely more consistent with how we do it for other overloads.

Is there any particular reason why it needs to be `RuntimeTypeHandle` instead of simply `Type`?

**Comment by jkoritzinsky** [comment]
I'm like using RuntimeTypeHandle when it needs to be a runtime-loaded type as opposed to a user-provided derived type.

I'm okay changing it if that's desirable.

**Comment by tannergooding** [comment]
Are there any benefits or drawbacks to using one over the other here?

AFAIR, `RuntimeTypeHandle` is basically just a thin wrapper over `RuntimeType` and so I believe taking `Type` will just make it easier for users to use the API if they don't have a concrete type available.

**Comment by MichalPetryka** [comment]
The JIT is able to fold all conversions away FYI:
![image](https://github.com/dotnet/runtime/assets/35800402/641136b2-22dc-4bf9-8c41-27374fc8da92)
![image](https://github.com/dotnet/runtime/assets/35800402/2f80dc87-e863-4e44-9775-08e54c7b1005)

**Comment by jkotas** [comment]
> Are there any benefits or drawbacks to using one over the other here?

If the API takes Type, it needs to validate whether the Type is RuntimeType first. This validation takes a few extra instructions.

Type is more usable. RuntimeTypeHandle is more oriented towards low-level perf oriented.

> The JIT is able to fold all conversions away FYI

If you know the concrete type, it is better to use the existing generic SizeOf method. It is going to faster (or at least as fast) than this method.

**Comment by tannergooding** [comment]
Sounds like `RuntimeTypeHandle` is the right thing here and API review can discuss if we want it on `RuntimeHelpers` or `Unsafe` next to `SizeOf`, so I've marked this `ready-for-review`

**Comment by bartonjs** [comment]
* Looks good as proposed

```c#
namespace System.Runtime.CompilerServices;

public partial class RuntimeHelpers
{
     public static int SizeOf(RuntimeTypeHandle type);
}
```
