### ISSUE TITLE
When compiling NativeAOT, is the deferred information stored in a PDB file with field pointers like in C++?

### ISSUE THREAD

**Issue by dadavadd** [dotnet/runtime#97346]
NativeAOT PDB file loaded into IDA:

![image](https://github.com/dotnet/runtime/assets/111659964/c25f3976-3ede-4e58-b63a-535b695f133f)

C++ pdb loaded into IDA:
![image](https://github.com/dotnet/runtime/assets/111659964/f134ecf5-c075-4a7e-8675-1689692b2b07)

Or does information about the fields disappear during compilation, even from a PDB file?

**Comment by SingleAccretion** [comment]
The AOT compiler does produce debugging information for fields, among other things. It can also produce information needed by reflection for fields that may be reflected on (this is usually a rather small subset of all fields) in a custom format that is stored directly in the binary.

**Comment by dadavadd** [comment]
> Yes, the AOT compiler does produce debugging information for fields, among other things. It can also produce information needed by reflection for fields that may be reflected on (this is usually a rather small subset of all fields) in a custom format that is stored directly in the binary.

Is there any way to view them in IDA PRO while loading debugging information (.pdb)?

**Comment by SingleAccretion** [comment]
I do not know (this would be an IDA question). I would presume that the "shape" of debug information produced is sufficiently different from C++'s that it is not picked up by the decompiler by default.

**Comment by dadavadd** [comment]
Indeed, this is noticeable with strings. They are marked in ida pro as "unk_1234567".

> I do not know (this would be an IDA question). I would presume that the "shape" of debug information produced is sufficiently different from C++'s that it is not picked up by the decompiler by default.

Indeed, this is noticeable with strings. They are marked in ida pro as "unk_1234567".

**Comment by MichalStrehovsky** [comment]
> Indeed, this is noticeable with strings. They are marked in ida pro as "unk_1234567".

The string in Native AOT look nothing like typical strings in native languages - first is a pointer to the vtable, next is the size of the string, followed by the characters. IDA would need to learn to understand these.

**Comment by Thealexbarney** [comment]
I remember back in the CoreRT days IDA was a lot better at loading debug info. It got worse somewhere along the way, although I seem to recall IDA loading a lot more stuff from DWARF info compared to PDBs back then.

**Comment by MichalStrehovsky** [comment]
I think the question has been answered and I don't see anything else actionable.
