### ISSUE TITLE
Set licence type on packages

### ISSUE THREAD

**Issue by thompson-tomo** [dotnet/runtime#97370]
### Is your feature request related to a problem? Please describe.
In dependency track this package is reporting as not having a licence type specified

### Describe the solution you'd like
The PackageLicenseExpression property is set in the csproj so that the NUGET package has the information. This can then be included in the SBOM so that analysis can occur in the appropriate tools

### Describe alternatives you've considered
Ignore them, bundle licence file into package & reference the file.

### Additional context
Impacted packages
- NetStandard.Library
- System.Buffers
- System.Data.DataSetExtensions
- System.Memory
- System.Numerics.Vectors
- System.Runtime
- System.Threading.Tasks.Extensions

Note those are only the packages I have identified as missing based on my projects but no doubt there will be more.

**Comment by tannergooding** [comment]
CC. @ericstj this is more of a meta/infrastructure issue and may need someone to look at it

**Comment by ericstj** [comment]
All the packages listed are no longer being built.  All packages built in both dotnet/runtime, and to be built in dotnet/maintainence-packages do set license expression.  cc @ViktorHofer @carlossanlop
