### ISSUE TITLE
Performance regression on ASP.NET

### ISSUE THREAD

**Issue by sebastienros** [dotnet/runtime#97406]
![image](https://github.com/dotnet/runtime/assets/1165805/623857b0-83b9-4925-a65c-0efddf4fb255)

Could only isolate on this commit range since there were no successful builds for 3 days. Seems to impact all scenarios indifferently.

https://github.com/dotnet/runtime/compare/dbb335c6ba14...a18d8cdab4c7

It doesn't impact NativeAOT (JIT?), and is visible on Windows and Linux.

![image](https://github.com/dotnet/runtime/assets/1165805/dc137b29-dcf7-4e6b-8d7b-d573f995df9d)

Could be related to https://github.com/dotnet/runtime/issues/97399#issuecomment-1906562748 . The date doesn't match but there weren't any builds since 1/17 until 1/19 so this could be the same reason.

Crank commands:

Before

```
crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/plaintext.benchmarks.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/ci.profile.yml --scenario mvc --profile gold-win-app --profile gold-load-load --application.framework net9.0 --application.collectDependencies true --application.options.collectCounters true --application.aspNetCoreVersion 9.0.0-alpha.1.24069.2 --application.runtimeVersion 9.0.0-alpha.1.24069.4 --application.sdkVersion 9.0.100-alpha.1.24069.3
```

After

```
crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/plaintext.benchmarks.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/ci.profile.yml --scenario mvc --profile gold-win-app --profile gold-load-load --application.framework net9.0 --application.collectDependencies true --application.options.collectCounters true --application.aspNetCoreVersion 9.0.0-alpha.1.24068.16 --application.runtimeVersion 9.0.0-alpha.1.24066.33 --application.sdkVersion 9.0.100-alpha.1.24068.28
```

**Comment by jkotas** [comment]
Dup of https://github.com/dotnet/runtime/issues/97399#issuecomment-1906562748 ?

**Comment by sebastienros** [comment]
Fixed and verified in benchmarks.
