### ISSUE TITLE
Unhandled exception from DllImportCallback.cpp::TheUMEntryPrestubWorker when doing native interop after hostfxr_main returns

### ISSUE THREAD

**Issue by jkotalik** [dotnet/runtime#9741]
Hi, I am currently running into an Unhandled exception from the coreclr when doing native/managed interop. Here are the steps I am preforming.

1. From a native module, I load hostfxr.dll and call hostfxr_main. 
2. Managed code has callbacks into native via DllImport, as well as callbacks from native into managed via function assignment.
3. Interop occurs and then managed code exits, causing hostfxr_main to return. 
4. From my console window, I forcibly terminate the process (click X at the top).
5. The process crashes, saying:

```
Unhandled exception at 0x00007FFE67C34008 (KernelBase.dll) in iisexpress.exe: 0xC0020001: The string binding is invalid (parameters: 0xFFFFFFFF8007042B).

>	KernelBase.dll!RaiseException()	Unknown	Symbols loaded.
 	coreclr.dll!TheUMEntryPrestubWorker(UMEntryThunk * pUMEntryThunk) Line 1064	C++	Symbols loaded.
 	coreclr.dll!TheUMEntryPrestub() Line 67	Unknown	Symbols loaded.
 	KernelBase.dll!CtrlRoutine()	Unknown	Symbols loaded.
 	kernel32.dll!BaseThreadInitThunk()	Unknown	Symbols loaded.
 	ntdll.dll!RtlUserThreadStart()	Unknown	Symbols loaded.

```

Based on the stacktrace, an initial guess I have is I have a dll import call that doesn't return. Is there a way to guarantee all DllImportCallback calls will not be triggered after hostfxr_main returns?

Any idea of what I am doing wrong/ issues with DllImportCallback?

cc/ @steveharter

**Comment by jkotas** [comment]
This was most likely fixed by https://github.com/dotnet/coreclr/pull/24847
