### ISSUE TITLE
LinkerArg doesn't seem to work on net8.0-macos NativeAOT app

### ISSUE THREAD

**Issue by vaind** [dotnet/runtime#97414]
### Description

`LinkerArg` doesn't seem to work when publishing NativeAOT targeting `net8.0-macos`. Maybe I'm missing something, or misinterpreting the reproduction steps but at least that's what it looks like. The actual issue where I'm coming from is that the linker fails when adding a static library that depends on `curl`, even when `-lcurl` is added as `LinkerArg`. The same works just fine when targeting `net8.0`

### Reproduction Steps

Steps to Reproduce
1. Create new macOS app: `dotnet new macos`
2. Add `<PublishAot>true</PublishAot>` to .csproj
3. Add some linker args that should fail the build, e.g. 
```
  <ItemGroup>
    <LinkerArg Include="-foobar"/>
    <LinkerArg Include="-lnonexistentlib"/>
  </ItemGroup>
```
4. `dotnet publish -flp:logfile=build.log --runtime=osx-arm64`

### Expected behavior

publishing fails

### Actual behavior

publishing succeeds

### Other information

Related to:
* https://github.com/getsentry/sentry-dotnet/issues/3070

**Comment by filipnavara** [comment]
The macOS binding use their own linker step. You can use one of the more specific items to add linker arguments (which work both for `net8.0` and `net8.0-macos`:
https://github.com/xamarin/xamarin-macios/blob/34f6b6aa8bdc633fcea24939a1ea6e9e0af9d8ac/dotnet/targets/Xamarin.Shared.Sdk.targets#L1332-L1336

In this case it's likely `<NativeSystemLibrary>curl</NativeSystemLibrary>`. For generic linker arguments it's `<ExtraLinkerArg>`. `<LinkerArg>` is an implementation detail.

**Comment by vaind** [comment]
> ExtraLinkerArg

These docs are wrong/incomplete then? https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/interop#linking

**Comment by filipnavara** [comment]
> These docs are wrong/incomplete then?

Yeah, they should be updated.

**Comment by vaind** [comment]
`ExtraLinkerArg` seems to fix the issue, thanks

**Comment by vaind** [comment]
> > These docs are wrong/incomplete then?
> 
> Yeah, they should be updated.

https://github.com/dotnet/docs/pull/39230/files

**Comment by agocke** [comment]
Closing as not a nativeaot issue. This looks like a xamarin issue and was resolved with additional docs over there.
