### ISSUE TITLE
Reading in Stream from ZipPackagePart results in incomplete read of file

### ISSUE THREAD

**Issue by jlocke427** [dotnet/runtime#97431]
### Description

We recently ran into and issue around reading the contents of a compressed Zip file when we upgrade our application from .NET Framework 4.8 to .NET 7.0 where the latter part of an XML was not being read in from the zip file. The snippet of code provided works on .NET Framework 4.8 just fine currently, however the System.IO.Packages from NuGet when using .NET (Tested on 6, 7, 8) seem to have an issue reading the whole XML file from the zip. 

### Reproduction Steps

When using the attached customizations.zip the following will not fully read the customizations.xml that is inside the zip file. This previously worked in .NET Framework 4.8, but no longer seems to work on .NET (Currently using 7.0).

You can look at the readBuff variable in the debugger and see that after index 125069the array indexes are not assign. For us this causes issues downstream where we attempt to read in the XML into an XMLDocument.

```
using System;
using System.IO;
using System.IO.Packaging;

public class Program
{
    public static void Main(string[] args)
    {
        string xmlFQDN = Path.GetFullPath("customizations.zip");

        ZipPackage zipPackage = (ZipPackage)Package.Open(xmlFQDN, FileMode.Open, FileAccess.Read, FileShare.Read);
        ZipPackagePart part = (ZipPackagePart)zipPackage.GetPart(new Uri("/customizations.xml", UriKind.Relative));

        // Reads the ZipPackagePart stream using the Read() method.
        // For some reason when we use this method of reading the customizations.xml it
        // results in the returned buffer missing the indexes 125069+ to be unassigned.
        byte[] readBuff;

        using (Stream strm = part.GetStream())
        {
            long len = strm.Length;
            readBuff = new byte[len];
            strm.Read(readBuff, 0, (int)len);
        }
    }
}
```

[customizations.zip](https://github.com/dotnet/runtime/files/14031451/customizations.zip)

### Expected behavior

The expected behaviors is that the entire byte[] is populated with the contents of the customization.xml file like it was in .NET Framework. 

### Actual behavior

What we are seeing is that the remainder of the byte[] is full of unassigned values
![image](https://github.com/dotnet/runtime/assets/19756608/cb09e07a-01de-460c-ad64-69eebf4d9b6c)

### Regression?

This currently work in .NET Framework 4.8

### Known Workarounds

I was able to workaround the issue in .NET by copying the contents of the ZipPackagePart Stream into a MemoryStream and then using the ToArray() method. 

```
using System;
using System.IO;
using System.IO.Packaging;

public class Program
{
    public static void Main(string[] args)
    {
        string xmlFQDN = Path.GetFullPath("customizations.zip");

        ZipPackage zipPackage = (ZipPackage)Package.Open(xmlFQDN, FileMode.Open, FileAccess.Read, FileShare.Read);
        ZipPackagePart part = (ZipPackagePart)zipPackage.GetPart(new Uri("/customizations.xml", UriKind.Relative));

        // Reads the ZipPackagePart stream by copying to a MemoryStream and then using the ToArray();
        // This also correctly reads in the customizations.xml from the specified zip file.
        byte[] copyBuff;

        using (Stream strm = part.GetStream())
        using (var memoryStream = new MemoryStream((int)strm.Length))
        {
            strm.CopyTo(memoryStream);
            copyBuff = memoryStream.ToArray();
        }
    }
}
```

### Configuration

.NET versions: 6, 7 and 8 were tested
OS: Windows 11 Version 10.0.22631 Build 22631
Architecture: X64

**Comment by vcsjones** [comment]
You are running in to a known breaking change in .NET 6:

https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams

> `strm.Read(readBuff, 0, (int)len);`

[`Read` is not guaranteed](https://learn.microsoft.com/dotnet/api/system.io.stream.read?view=net-8.0) to read `len` bytes and you are ignoring the return value from `Read` which indicates how many bytes were actually read.

> An implementation is free to return fewer bytes than requested even if the end of the stream has not been reached.

>  (Currently using 7.0).

In that case you can use `ReadExactly` or `ReadAtLeast` to ensure a minimum number of bytes have been read. Alternatively, you can continue to use `Read` but do so in a loop.

**Comment by jlocke427** [comment]
Thank you, That did the trick!
