### ISSUE TITLE
GC/API/Refresh/Refresh failing in outer loop runs

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#97437]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=538357
Build error leg or test failing: GC/API/Refresh/Refresh/Refresh.sh
Pull request: https://github.com/dotnet/runtime/pull/97424

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "GC\\API\\Refresh\\Refresh\\Refresh.cmd [FAIL]",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=538357
**Error message validated:** `GC\API\Refresh\Refresh\Refresh.cmd [FAIL]`
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 1/24/2024 5:50:43 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[539641](https://dev.azure.com/dnceng-public/public/_build/results?buildId=539641)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=539641&view=ms.vss-test-web.build-test-results-tab&runId=12786170&resultId=121496)|dotnet/runtime#97415|
|[539815](https://dev.azure.com/dnceng-public/public/_build/results?buildId=539815)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=539815&view=ms.vss-test-web.build-test-results-tab&runId=12784184&resultId=121308)||
|[539169](https://dev.azure.com/dnceng-public/public/_build/results?buildId=539169)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=539169&view=ms.vss-test-web.build-test-results-tab&runId=12775008&resultId=121310)|dotnet/runtime#92974|
|[539193](https://dev.azure.com/dnceng-public/public/_build/results?buildId=539193)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=539193&view=ms.vss-test-web.build-test-results-tab&runId=12766370&resultId=121308)||
|[2361235](https://dev.azure.com/dnceng/internal/_build/results?buildId=2361235)|dotnet-runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2361235&view=ms.vss-test-web.build-test-results-tab&runId=52942339&resultId=121308)||
|[539028](https://dev.azure.com/dnceng-public/public/_build/results?buildId=539028)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=539028&view=ms.vss-test-web.build-test-results-tab&runId=12760000&resultId=121308)|dotnet/runtime#97411|
|[538912](https://dev.azure.com/dnceng-public/public/_build/results?buildId=538912)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=538912&view=ms.vss-test-web.build-test-results-tab&runId=12756664&resultId=121310)|dotnet/runtime#92974|
|[538562](https://dev.azure.com/dnceng-public/public/_build/results?buildId=538562)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=538562&view=ms.vss-test-web.build-test-results-tab&runId=12744860&resultId=121308)||
|[538552](https://dev.azure.com/dnceng-public/public/_build/results?buildId=538552)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=538552&view=ms.vss-test-web.build-test-results-tab&runId=12744178&resultId=121308)|dotnet/runtime#97409|
|[538519](https://dev.azure.com/dnceng-public/public/_build/results?buildId=538519)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=538519&view=ms.vss-test-web.build-test-results-tab&runId=12743162&resultId=121308)||
|[538453](https://dev.azure.com/dnceng-public/public/_build/results?buildId=538453)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=538453&view=ms.vss-test-web.build-test-results-tab&runId=12740530&resultId=121308)||
|[538421](https://dev.azure.com/dnceng-public/public/_build/results?buildId=538421)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=538421&view=ms.vss-test-web.build-test-results-tab&runId=12739384&resultId=121308)||
|[538422](https://dev.azure.com/dnceng-public/public/_build/results?buildId=538422)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=538422&view=ms.vss-test-web.build-test-results-tab&runId=12739380&resultId=121308)||
|[538404](https://dev.azure.com/dnceng-public/public/_build/results?buildId=538404)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=538404&view=ms.vss-test-web.build-test-results-tab&runId=12738444&resultId=121308)||
|[538394](https://dev.azure.com/dnceng-public/public/_build/results?buildId=538394)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=538394&view=ms.vss-test-web.build-test-results-tab&runId=12738246&resultId=121308)|dotnet/runtime#97387|
|[538392](https://dev.azure.com/dnceng-public/public/_build/results?buildId=538392)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=538392&view=ms.vss-test-web.build-test-results-tab&runId=12738248&resultId=121308)|dotnet/runtime#97387|
|[538357](https://dev.azure.com/dnceng-public/public/_build/results?buildId=538357)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=538357&view=ms.vss-test-web.build-test-results-tab&runId=12737368&resultId=121308)|dotnet/runtime#97424|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|13|17|17|

**Comment by jkotas** [comment]
@cshung Could you please take a look? The test is failing in number of outer loop legs. 

The test was added as outer loop only, but it does not look like the outer loop run was done to validate the test is passing in outer  loop. You can use `/azp run runtime-coreclr outerloop` on your PR to validate that the test is passing in outerloop.

**Comment by cshung** [comment]
@jkotas, my bad, the test was not meant for platforms without regions.
