### ISSUE TITLE
[NativeAOT] Publish NativeAOT Got Dependency Error

### ISSUE THREAD

**Issue by dongfengxin** [dotnet/runtime#97442]
### Description

Publish NativeAOT Project with Configure Manager Got the follwing error

Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'Microsoft.Extensions.Configuration.Abstractions'.
File name: 'Microsoft.Extensions.Configuration.Abstractions'
   at Internal.Runtime.TypeLoaderExceptionHelper.CreateFileNotFoundException(ExceptionStringID, String) + 0x43
   at Internal.Runtime.CompilerHelpers.ThrowHelpers.ThrowFileNotFoundException(ExceptionStringID, String) + 0x9

Further more with the command : dotnet publish -r win-x64 did not got the published  exe file, don't known why.

### Reproduction Steps

        public T GetConfiguration<T>(string Key) where T : class, new()                  
        {
            var t = iServices.Configure<T>("From Json Configuration", Options => iConfiguration.GetSection(Key).Get<T>()).BuildServiceProvider().GetService<IOptionsSnapshot<T>>();
            return t!.Value;
        }

        public void SetConfiguration<T>(string Key, T Value) where T : class, new()             
        {
            iServices.Configure<T>("From Json Configuration", Options => iConfiguration[Key] = Value!.ToString()).BuildServiceProvider().GetService<IOptionsSnapshot<T>>();
        }

### Expected behavior

No Error

### Actual behavior

Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'Microsoft.Extensions.Configuration.Abstractions'.
File name: 'Microsoft.Extensions.Configuration.Abstractions'
   at Internal.Runtime.TypeLoaderExceptionHelper.CreateFileNotFoundException(ExceptionStringID, String) + 0x43
   at Internal.Runtime.CompilerHelpers.ThrowHelpers.ThrowFileNotFoundException(ExceptionStringID, String) + 0x9

**Comment by dongfengxin** [comment]
Find another

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'Microsoft.Data.SqlClient.SNI.dll' or one of its dependencies: The specified module could not be found.
   at System.Runtime.InteropServices.NativeLibrary.LoadLibErrorTracker.Throw(String) + 0x6f
   at Internal.Runtime.CompilerHelpers.InteropHelpers.FixupModuleCell(InteropHelpers.ModuleFixupCell*) + 0xfd
   at Internal.Runtime.CompilerHelpers.InteropHelpers.ResolvePInvokeSlow(InteropHelpers.MethodFixupCell*) + 0x2f
   at Microsoft.Data.SqlClient.SNINativeMethodWrapper.UnmanagedIsTokenRestricted(IntPtr, Boolean&) + 0x31
   at Microsoft.Data.Win32NativeMethods.IsTokenRestrictedWrapper(IntPtr) + 0x19
   at Microsoft.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrentNative() + 0xb1
   at Microsoft.Data.ProviderBase.DbConnectionPoolGroup.GetConnectionPool(DbConnectionFactory) + 0x53
   at Microsoft.Data.ProviderBase.DbConnectionFactory.GetConnectionPool(DbConnection, DbConnectionPoolGroup) + 0xa3
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection, TaskCompletionSource`1, DbConnectionOptions, DbConnectionInternal, DbConnectionInternal&) + 0x5c
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection, DbConnectionFactory, TaskCompletionSource`1, DbConnectionOptions) + 0x118
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1, SqlConnectionOverrides) + 0x1a9
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides) + 0x1ed

**Comment by jkotas** [comment]
Could you please share complete repro steps to reproduce the problem? (.csproj + .cs)

**Comment by dongfengxin** [comment]
Solution Structure

![image](https://github.com/dotnet/runtime/assets/17286415/fa3c6586-fa7a-4319-90cc-29bd54a88942)

**Comment by dongfengxin** [comment]
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    public class ConfigureManager
    {
        public IConfiguration iConfiguration { get; set; }

        private IServiceCollection iServices;

        public T GetConfiguration<T>(string Key) where T : class, new()
        {
            var t = iConfiguration.GetSection(Key).Get<T>();
            return t!;
        }

        public T GetConfiguration<T>() where T : class, new()
        {
            var t = iConfiguration.GetSection(typeof(T).Namespace + ":" + typeof(T).Name).Get<T>();
            return t!;
        }

        public T GetConfiguration<T>(string Key, bool Candidate) where T : class, new()                     //Need To Be Update To Remove The Candidate para
        {
            var t = iServices.Configure<T>("From Json Configuration", Options => iConfiguration.GetSection(Key).Get<T>()).BuildServiceProvider().GetService<IOptionsSnapshot<T>>();
            return t!.Value;
        }

        public void SetConfiguration(string Key, object Value)
        {
            iConfiguration[Key] = Value.ToString();
        }

        public void SetConfiguration<T>(T Value)
        {
            var PI = typeof(T).GetProperties();
            var RootKey = typeof(T).Namespace + ":" + typeof(T).Name;
            int i = 0;
            foreach (var pi in PI)
            {
                var Key = RootKey + ":" + pi.Name;
                iConfiguration[Key] = PI[i].GetValue(Value, null)!.ToString();
                i++;
            }
        }

        public void SetConfiguration<T>(string Key, T Value, bool Candidate) where T : class, new()             //Need To Be Update To Remove The Candidate para
        {
            iServices.Configure<T>("From Json Configuration", Options => iConfiguration[Key] = Value!.ToString()).BuildServiceProvider().GetService<IOptionsSnapshot<T>>();
        }
    }
}

**Comment by dongfengxin** [comment]
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    public class ProgressBarModeArgs
    {
        public ProgressBarModeArgs()
        {
            configuremanager = new ConfigureManager();
        }

        public ConfigureManager configuremanager { get; set; }

        private string progressbarmode;
        public string ProgressBarMode
        {
            get
            {
                progressbarmode = configuremanager.GetConfiguration<ProgressBarModeOptions>().ProgressBarMode!;
                return progressbarmode;
            }
            set
            {
                configuremanager.SetConfiguration(new ProgressBarModeOptions { ProgressBarMode = value });
                progressbarmode = value;
            }
        }
    }
}

**Comment by dongfengxin** [comment]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    public class ProgressBarModeOptions
    {
        public string? ProgressBarMode { get; set; }
    }
}

**Comment by dongfengxin** [comment]
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

namespace ConsoleApp1
{
    public class Program
    {
        static void Main(string[] args)
        {
            var progressbarmodeargs = new ProgressBarModeArgs();
            Console.WriteLine("Hello, World!");
            Console.WriteLine(progressbarmodeargs.ProgressBarMode);
        }
    }
}

**Comment by dongfengxin** [comment]
{
    "ProgressBars.Models": {
        "ProgressBarModeOptions": {
            "ProgressBarMode": "Production"
        }
    }
}

**Comment by dongfengxin** [comment]
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.1" />
  </ItemGroup>

</Project>

**Comment by dongfengxin** [comment]
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.1" />
  </ItemGroup>

</Project>

**Comment by dongfengxin** [comment]
![image](https://github.com/dotnet/runtime/assets/17286415/8aa3898b-978b-4db6-ac9e-bf2362cebd84)

**Comment by jkotas** [comment]
`dotnet publish` works fine for me on this project. Does this project fail with the same error as you reported originally? 

Your original error mentioned `Microsoft.Data.SqlClient`, but this project does not reference `Microsoft.Data.SqlClient` anywhere.

**Comment by dongfengxin** [comment]
> `dotnet publish` works fine for me on this project. Does this project fail with the same error as you reported originally?
> 
> Your original error mentioned `Microsoft.Data.SqlClient`, but this project does not reference `Microsoft.Data.SqlClient` anywhere.



the above project is a demo which shows the problem , as you mentioned the problem doesn't happen again.  and when I optimize it again, I got the error same like the above again.:

Unhandled Exception: System.TypeInitializationException: A type initializer threw an exception. To determine which type, inspect the InnerException's StackTrace property.
 ---> System.IO.FileNotFoundException: Could not find file 'Microsoft.Extensions.Configuration.Abstractions'.
File name: 'Microsoft.Extensions.Configuration.Abstractions'
   at Internal.Runtime.TypeLoaderExceptionHelper.CreateFileNotFoundException(ExceptionStringID, String) + 0x43
   at Internal.Runtime.CompilerHelpers.ThrowHelpers.ThrowFileNotFoundException(ExceptionStringID, String) + 0x9
   at Indexs.Models.IndexArgs.get_RiskMonitorID() + 0x15
   at Indexs.Models.IndexArgs..ctor() + 0x3ce
   at Indexs.Models.IndexArgs.DefaultHolder..cctor() + 0x1c
   at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0xb9
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0x14a
   at System.Runtime.CompilerServices.ClassConstructorRunner.CheckStaticClassConstructionReturnGCStaticBase(StaticClassConstructionContext*, Object) + 0xd

**Comment by dongfengxin** [comment]
and when publish in the right click of the project , the publish action success, but when I publish the project with command dotnet publish ,there is no error message, but did not got the publish exe file and the folder bin\release\net8.0\publish\win-x64

**Comment by jkotas** [comment]
> when I publish the project with command dotnet publish ,there is no error message, but did not got the publish exe file

Could you please share the output of the `dotnet publish` command?

**Comment by dongfengxin** [comment]
Dereference of a possibly null reference.
16>Dereference of a possibly null reference.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Observe the awaitable result of this method call by awaiting it, assigning to a variable, or passing it to another method (https://github.com/Microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD110.md)
16>Observe the awaitable result of this method call by awaiting it, assigning to a variable, or passing it to another method (https://github.com/Microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD110.md)
16>Observe the awaitable result of this method call by awaiting it, assigning to a variable, or passing it to another method (https://github.com/Microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD110.md)
16>Observe the awaitable result of this method call by awaiting it, assigning to a variable, or passing it to another method (https://github.com/Microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD110.md)
16>Observe the awaitable result of this method call by awaiting it, assigning to a variable, or passing it to another method (https://github.com/Microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD110.md)
16>Observe the awaitable result of this method call by awaiting it, assigning to a variable, or passing it to another method (https://github.com/Microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD110.md)
16>Observe the awaitable result of this method call by awaiting it, assigning to a variable, or passing it to another method (https://github.com/Microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD110.md)
16>Observe the awaitable result of this method call by awaiting it, assigning to a variable, or passing it to another method (https://github.com/Microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD110.md)
16>Observe the awaitable result of this method call by awaiting it, assigning to a variable, or passing it to another method (https://github.com/Microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD110.md)
16>Synchronously waiting on tasks or awaiters may cause deadlocks. Use await or JoinableTaskFactory.Run instead. (https://github.com/Microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD002.md)
16>Using member 'System.Exception.TargetSite.get' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Exception.TargetSite.get' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Exception.TargetSite.get' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Observe the awaitable result of this method call by awaiting it, assigning to a variable, or passing it to another method (https://github.com/Microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD110.md)
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Observe the awaitable result of this method call by awaiting it, assigning to a variable, or passing it to another method (https://github.com/Microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD110.md)
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
16>Using member 'System.Reflection.MethodBase.GetCurrentMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.

**Comment by dongfengxin** [comment]
16>ILC: Method '[Services]Services.Models.UpdateModelArgs.get_UpdateModel()' will always throw because: Failed to load assembly 'Microsoft.Extensions.Configuration.Abstractions'

**Comment by dongfengxin** [comment]
using dotnet publish command Error message:

MSBuild version 17.9.0-preview-23618-08+82d381eb2 for .NET
  Determining projects to restore...
C:\Program Files\dotnet\sdk\8.0.200-preview.23624.5\NuGet.targets(169,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [D:\Solutions\NativeAOT\PublishNativeAOT\PublishNativeAOT.CLI.csproj]
C:\Program Files\dotnet\sdk\8.0.200-preview.23624.5\NuGet.targets(169,5): error :   The SSL connection could not be established, see inner exception. [D:\Solutions\NativeAOT\PublishNativeAOT\PublishNativeAOT.CLI.csproj]
C:\Program Files\dotnet\sdk\8.0.200-preview.23624.5\NuGet.targets(169,5): error :   Received an unexpected EOF or 0 bytes from the transport stream. [D:\Solutions\NativeAOT\PublishNativeAOT\PublishNativeAOT.CLI.csproj]

**Comment by dongfengxin** [comment]
dotnet publish success,  but right click the project to publish NativeAOT still not working. No matter , a  success way have got!

**Comment by dongfengxin** [comment]
> > when I publish the project with command dotnet publish ,there is no error message, but did not got the publish exe file
> 
> Could you please share the output of the `dotnet publish` command?

Thank you for your help, dotnet publish success, but right click the project to publish NativeAOT still not working. No matter , a success way have got!

**Comment by jkotas** [comment]
> right click the project to publish NativeAOT still not working

What does it do? Do you see any errors? Could you please share your VS publish profile for the project?

If the publish profile has "Target Runtime" set to `portable`, you need to change it to `win-x64`.

![image](https://github.com/dotnet/runtime/assets/6668460/25ca4d4e-4ba1-4a92-b5c4-9aba10a4d766)
