### ISSUE TITLE
SslStream.AuthenticateAsClient correct way to avoid sending SNIs

### ISSUE THREAD

**Issue by roji** [dotnet/runtime#97444]
### Discussed in https://github.com/dotnet/runtime/discussions/97443

<div type='discussions-op-text'>

<sup>Originally posted by **Evengard** January 24, 2024</sup>
Hello!

In some cases, it is needed to construct an SslStream which doesn't send any SNIs to the target host. It seems this is possible by setting the targetHost parameter to an empty string, but we wonder if there is any side effects associated with that? Won't that break any other certificate checks under the hood? How safe is it to just omit targetHost for disabling SNI? Or maybe there are any other ways to do it?

Also, while in the documentation it is stated that TargetHost can't be null, the existing code seems to accept null without a problem. Is it intended behaviour with documentation being slightly out of date, or just a mishap?</div>

**Comment by roji** [comment]
Note that re Host nullability, this isn't only a documentation quesiton, is an NRT annotation question.

**Comment by krwq** [comment]
On the server side (at least .NET) the SNI is just a hint to allow picking the right cert. Basically cert is being picked by (in SslServerAuthenticationOptions):
- ServerCertificate
- ServerCertificateSelectionCallback
you set one or the other to decide the cert - with first API it basically is meaningless.
In the callback case server may choose to ignore that value and it's basically up to specific app to pick what to do with that string.

Per spec this value is used to guide certificate selection but it doesn't have any other special meaning or enforcements.

Specs: https://datatracker.ietf.org/doc/html/rfc6066 & https://datatracker.ietf.org/doc/html/rfc5246

PR where support was added is here:
https://github.com/dotnet/corefx/pull/28278/files

**Comment by krwq** [comment]
W.r.t. nullability part of the question - from spec point of view it could be nullable - i.e. null meaning lack of extension while empty could mean extension with empty string but I do not know/remember if that's what is actually happening - I'd imagine the answer could potentially be platform specific.

**Comment by Evengard** [comment]
The question is more about the client side of things, although thanks for the heads up.

**Comment by wfurt** [comment]
I think using `string.Empty` is the best IMHO. There are already cases when the client does not send SNI - like RFC forbids to send IP literal e.g. `http://127.0.0.1/` will go out with SNI. And also it is optional extension in case you want multiple certificates for the same server. 

With that, `SslStream` has no clue where you are connecting to and what it should expect. So you will have to register validation callback and do your own validation @roji.

**Comment by vonzshik** [comment]
> With that, SslStream has no clue where you are connecting to and what it should expect. So you will have to register validation callback and do your own validation @roji.

If we're talking about `RemoteCertificateValidationCallback` then we (Npgsql) already do [pass our own](https://github.com/npgsql/npgsql/blob/eb050c0a0fd4b70f9d11c6d41027076e9e4e01c1/src/Npgsql/Internal/NpgsqlConnector.cs#L839-L871). Taking that into account, does it mean that passing `string.Empty` will just result in us not sending SNI so we do not have to do anything else? I'm mostly interested in [SslVerifyFullValidation](https://github.com/npgsql/npgsql/blob/eb050c0a0fd4b70f9d11c6d41027076e9e4e01c1/src/Npgsql/Internal/NpgsqlConnector.cs#L1600-L1602) where we assert that there were no sslPolicyErrors. One of the errors we can get is `SslPolicyErrors.RemoteCertificateNameMismatch` and I wonder whether `SslStream` uses `TargetHost` to validate that...

**Comment by wfurt** [comment]
You _will_ get validation error complaint about the name e.g. the `TargetName` is used for certificate validation.

You can do something like this to suppress it.
https://github.com/dotnet/runtime/blob/3a3d212903440e3bc039e7f4f7853c7bec2f0edc/src/libraries/System.Net.Security/tests/FunctionalTests/SslStreamSniTest.cs#L213-L228

But than you _should_ validate the name on your own as `SslStream` cannot do that.

**Comment by vonzshik** [comment]
OK, I think I mostly understand what's doing what exactly. Thank you @wfurt!
Just one more thing from me. Since Npgsql still supports .NET 6 (and we might support it up to Npgsql 9), we can't set `CertificateChainPolicy` (as it doesn't exist in .NET 6). From my understanding, the flag from your example only makes it so `sslPolicyErrors` passed to `RemoteCertificateValidationCallback` is going to be `SslPolicyErrors.RemoteCertificateNameMismatch` (strictly speaking it just sets that specific flag as there could be other errors, but let's assume that it was the only error) and in the example you provided it's not really necessary since all errors are ignored anyway, correct?

**Comment by roji** [comment]
@vcsjones the details are on the original issue which triggered this: https://github.com/npgsql/npgsql/issues/5543

**Comment by vcsjones** [comment]
Thanks.

> The "conformant" libpq library doesn't seem to send SNI on SSL connections at all

libpq sets SNI by default as of 2021: https://github.com/postgres/postgres/commit/5c55dc8b47338e72a4e598c155d2048d756fd10e

> when there is an IP address sent in SNI (when you connect not to a hostname, but to an IP address).

[RFC 6066](https://datatracker.ietf.org/doc/html/rfc60660 SNI forbids IP literals:

> Literal IPv4 and IPv6 addresses are not permitted in "HostName".

So if anything I would say the bug is that we are sending the SNI extension that contains a IP literal. I could understand a TLS server closing a connection for getting a bad extension.

**Comment by roji** [comment]
> libpq sets SNI by default as of 2021

Right (note that you can opt out though, [docs](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT-SSLSNI)).

**Comment by rzikm** [comment]
Please have a look at https://learn.microsoft.com/en-us/dotnet/core/extensions/httpclient-sni

**Comment by rzikm** [comment]
> So if anything I would say the bug is that we are sending the SNI extension that contains a IP literal. I could understand a TLS server closing a connection for getting a bad extension.

Btw. On linux, we had an issue where we would mistakenly send out IP literals in SNI extensions. https://github.com/dotnet/runtime/issues/81590, it was fixed for 8.0

**Comment by vcsjones** [comment]
> it was fixed for 8.0

Great. So, I think then the take aways are:

1. The documentation doesn't explicitly have a way to say "Do not send an SNI extension". Should the `TargetHost` be set to `null`? Do we have a test for this?

2. [The docs say](https://learn.microsoft.com/en-us/dotnet/api/system.net.security.sslclientauthenticationoptions.targethost?view=net-8.0#system-net-security-sslclientauthenticationoptions-targethost)

    > Gets or sets the name of the server the client is trying to connect to. That name is used for server certificate validation. It can be a DNS name **or an IP address**."

    That seems misleading. The IP address part should be removed from the docs.

**Comment by wfurt** [comment]
The IP is still used for validation - see #95072. It will try to mach altName ... if present @vcsjones
