### ISSUE TITLE
Expression.Lambda() performance degradation and system outage with over 16 arguments

### ISSUE THREAD

**Issue by hannasm** [dotnet/runtime#97466]
### Description

The application's performance should not degrade by more than a factor of 1000 dealing with over 16 types, using types from collectible assemblies, or employing pass-by-reference parameters in Expression.Lambda(). Notably, these conditions trigger the **slow path**, and it is noticeable that the duration of the slow path increases progressively with each subsequent call to Expression.Lambda()

### Steps to reproduce:

=================================

Sample repro

-------------------

```c#
//Issue reproducible with Struct, Static class as well

public static class MyClass { }

internal class Program
{
  static void Main(string[] args)
  {
      for (int a = 0; a < 10; a++)
      {
          long durration = 0;

          for (int i = 0; i < 1000; i++)
              durration += SampleFunc();

          Console.WriteLine("iteration " + a + " took " + durration + "ms");

      }
      Console.ReadKey();
  }

  static long SampleFunc()
  {
      var timer = Stopwatch.StartNew();


      //if this is smaller than 17 performance is fine (0ms)
      var argTypes = new Type[17]; 

      

      for (int i = 0; i < argTypes.Length; i++)
          argTypes[i] = typeof(int);                       

 

      //or, don’t put a class in there and performance is fine (0ms)
      argTypes[argTypes.Length - 1] = typeof(MyClass);
 

      var args = argTypes.Select(t => Expression.Parameter(t));
      var dictExpr = Expression.Convert(Expression.Parameter(typeof(int)), typeof(object));
      var invokeExpr = Expression.Lambda(dictExpr, args);
 

      timer.Stop();
      return timer.ElapsedMilliseconds;
  }

}
```
 

Output

```
iteration 0 took 281ms
iteration 1 took 1445ms
iteration 2 took 2122ms
iteration 3 took 2844ms
iteration 4 took 3752ms
iteration 5 took 4145ms
iteration 6 took 4882ms
iteration 7 took 5882ms
iteration 8 took 6705ms
iteration 9 took 8276ms
 ```

Note: This is 1000s of times slower than w/o a class or <17 types, progressively getting slower, which appears to be exponential.

**Comment by brianrob** [comment]
The main issue here is that there is a fast path for cases with 16 or fewer arguments as long as the arguments are not passed by reference.  The fast path uses `Action<...>` and `Func<...>` to avoid the reflection costs.

Once you end up on the slow path, you end up doing reflection, and the more custom types that get created, the more expensive they become to create due to management of the underlying data structures.

Not sure if there are good options for expanding the cases where a fast path can be used.  One potential workaround is to use intermediate types to encapsulate the parameters.

**Comment by hannasm** [comment]
In performance critical code, and especially in a long lived server
application, the slow path is unacceptable. Throwing an exception on the
slow path branch would be preferable to the slow (and difficult to
diagnose) death of the application by performance degradation. The
performance degradation can lead to SLA violations and outages.

Calls to expression.lambda() with these types of conditions can occur
frequently with linq code under the right conditions. It might even be
possible to trigger this issue with an entity framework query (I have not
tried). If code generated by the c# compiler uses expression.lambda() under
the hood, that could also be a route to triggering this issue.

Ideally there should be an option to disable the slow path in performance
critical code. An exception would have shown up under normal testing and
been an easy fix.

I definitely have places where using the slow path would be appropriate, in
my same application, so an option to enable and disable the slow path on a
per thread basis at runtime would be the right way to do it.

If there are ways to reduce or eliminate  cases that need the slow path
behavior that would be the best option. Perhaps there is another approach
involving runtime code generation.

The fast path could always be expanded to a higher number of arguments. The
code that led to this issue was using 25 arguments.

My understanding is that certain uses of garbage collectible types and uses
of ref arguments may present cases that will always require this slow path,
and the  option of last resort in my case would be to get an exception and
try to rewrite my code.

**Comment by cston** [comment]
It looks like the behavior reported repros with .NET Framework 4.7.2, but not with .NET 8.0.7.

.NET Framework 4.7.2:
```
iteration 0 took 1ms
iteration 1 took 36ms
iteration 2 took 959ms
iteration 3 took 1009ms
iteration 4 took 1681ms
iteration 5 took 1998ms
iteration 6 took 2459ms
iteration 7 took 2904ms
iteration 8 took 3180ms
iteration 9 took 3550ms
```

.NET 8.0.7:
```
iteration 0 took 5ms
iteration 1 took 0ms
iteration 2 took 0ms
iteration 3 took 0ms
iteration 4 took 0ms
iteration 5 took 0ms
iteration 6 took 0ms
iteration 7 took 0ms
iteration 8 took 0ms
iteration 9 took 0ms
```

**Comment by cston** [comment]
Closing since this does not appear to repro with .NET 8.
