### ISSUE TITLE
ICorDebugFunction5::DisableOpimizations causes target app to be terminated on Linux

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/runtime#97461]
### Description

If a debugger uses ICorDebugFunction5::DisableOpimizations on Linux (and I am assuming macOS as well, but I didn't test) the target app will be terminated. Before terminated, the following message is printed:

```
Unknown debugger event type: 0x258
```

This message is from [this code](https://github.com/dotnet/runtime/blob/093fdabc28310bc8f60fcaecbcbf38a59d878056/src/coreclr/debug/shared/dbgtransportsession.cpp#L2504), and the event type is `DB_IPCE_DISABLE_OPTS`.

### Reproduction Steps

1. Create a new .NET 8 console application
2. Configure the debugger to disable Just My Code, and load symbols for System.Console (enable downloading symbol from the Microsoft symbol server)
3. Set a breakpoint on the call to Console.WriteLine
4. Step in

### Expected behavior

Console.WriteLine should be deoptimized and the step should complete

### Actual behavior

Target process is aborted

### Regression?

This is a new feature in .NET 8. So, it is a regression in that the VS debuggers will automatically use it if it is present and that causes the target to crash. 

### Known Workarounds

Don't use the new feature

### Configuration

I am using .NET Runtime 8.0.1 on Linux-x64

**Comment by delmyers** [comment]
In newer versions of VS, you can turn off automatic deoptimizations as a work-around.
