### ISSUE TITLE
Multiple dispose called for chained dependency injection - Is it actual a bug? 

### ISSUE THREAD

**Issue by aDisplayName** [dotnet/runtime#97475]
### Description

Dependency injection will try to dispose same instance multiple times:

Suppose we have the following interface, and the class which implements the interface:
```csharp
internal interface IMethod {}

internal interface INewMethod: IMethod {}

internal class MethodClass : INewMethod, IAsyncDisposable
{
    private readonly SemaphoreSlim _lock = new(1, 1);
    public async ValueTask DisposeAsync()
    {   
        await _lock.WaitAsync();
        _lock.Release();
        _lock.Dispose();
    }
}
```

and a host class uses the instance of the said interface
```csharp
class HostClass(
    IMethod method,
    IHostApplicationLifetime appLifetime) : IHostedService
{

    public Task StartAsync(CancellationToken cancellationToken)
    {
        appLifetime.StopApplication();
        return Task.CompletedTask;
    }

    public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;
}
```

With the following code, exception will be thrown when dependency injection container trying to dispose the instantiated HostClass twice
```csharp
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
var builder= Host.CreateEmptyApplicationBuilder(new HostApplicationBuilderSettings());
builder.Services
    .AddHostedService<HostClass>()
    .AddSingleton<IMethod>(sp => sp.GetRequiredService<INewMethod>())
    .AddSingleton<INewMethod, MethodClass>();
        
var host = builder.Build();
await host.RunAsync();

/* 
Exception will thrown at the end.
Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Threading.SemaphoreSlim'.
   at System.Threading.SemaphoreSlim.WaitAsync(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.SemaphoreSlim.WaitAsync()
   at MethodClass.DisposeAsync() in \ConsoleApp1\Program.cs:line 22
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.<DisposeAsync>g__Await|26_0(Int32 i, ValueTask vt, List`1 toDispose)
   at Microsoft.Extensions.Hosting.Internal.Host.<DisposeAsync>g__DisposeAsync|21_0(Object o)
   at Microsoft.Extensions.Hosting.Internal.Host.DisposeAsync()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Program.<Main>$(String[] args) in \ConsoleApp1\Program.cs:line 10
   at Program.<Main>(String[] args)
*/

```

By looking at the exception site, I noticed there are two `MethodClass` instances need to be disposed by dependency container: 
![image](https://github.com/dotnet/runtime/assets/19527258/4c841715-7d41-4a5f-ab8e-905816c983e7)

In this case, toDispose[6] and toDispose[5] are pointing to the same instance.
So my question is:
1. Is the current behavior expected behavior? 
2. Would it be reasonable avoid duplicated placement to the toDispose array so that we can avoid possible multiple dispose?

### Reproduction Steps

Full code can be found at https://github.com/aDisplayName/bugsamplecode/tree/main/20240124

### Expected behavior

The singleton should only be disposed once.

### Actual behavior

The singleton instance has been disposed twice.

### Known Workarounds

As the workaround, I can add my own guard code to avoid double dispose.

### Configuration

.NET 8

**Comment by huoyaoyuan** [comment]
In the documentation of [IDisposable](https://learn.microsoft.com/dotnet/api/system.idisposable.dispose?view=net-8.0):

> If an object's [Dispose](https://learn.microsoft.com/en-us/dotnet/api/system.idisposable.dispose?view=net-8.0) method is called more than once, the object must ignore all calls after the first one.

It is a contract that multiple calls to Dispose should be allowed.

**Comment by steveharter** [comment]
I was unable to repro the issue in v8 or v9 Preview 1.

There is a typo, and I'm not sure the intent; this won't compile:
```
            .AddSingleton<IMethod>(sp => sp.GetRequiredService<INewMethod>())
```

**Comment by halter73** [comment]
I don't think that is worth fixing. It's similar to registering the same instance multiple times as the same interface and IEnumerable-resolving them. The same insurance will be disposed multiple times.
