### ISSUE TITLE
The `m_CallConv` of `System.String::Ctor` is inconsistent with `System.String::.ctor`

### ISSUE THREAD

**Issue by nikolahua** [dotnet/runtime#97499]
### Description

I'm trying to run HelloWorld on linux-x64 with the interpreter but it seems to be broken at the initialization phase. I find that the `m_CallConv` of `System.String::Ctor` is inconsistent with `System.String::.ctor` in .NET8, which used to be consistent in .NET6.
The inconsistency of `m_CallConv` which affects result of `MetaSig:HasThis()` causes the inconsistent examination of 'This' arg in `DoCallWork()` and `GenerateInterpreterStub()`.

|          | `System.String::Ctor` | `System.String::.ctor` | 
|-------|-----------------------|------------------------|
| .NET8 | HasThis()==false      | HasThis()==true        |
| .NET6 | HasThis()==true       | HasThis()==true        |

The log of interpreter execution in .NET8. There is a 'This' arg passed as arg[0] but it is regarded as part of `valueclass` in ` String:Ctor(valueclass)` incorrectly.
```
  0x1c: ret
  Returning to method Span`1:ToString():class, stub num 34.
         0: valueclass: <ReadOnlySpan`1>: [0xb0 0x1b 0xff 0xff 0xff 0x7f 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00]
  0x35: newobj
# 'This' as arg[0], `valueclass` above as arg[1]
TID 3378: In PreStubWorker for System.String::.ctor
TID 3378: DoPrestub: method 0x7fff7903ce18
TID 3378: In PreStubWorker for System.String::Ctor
TID 3378: DoPrestub: method 0x7fff7903ce58
TID 3378:     In PrepareILBasedCode, calling JitCompileCode
TID 3378: JitCompileCode(0x7fff7903ce58, ILStub: false) for System.String::Ctor
TID 3378: CrstBase::DebugInit 0x5555556319e0
TID 3378: { Jitting method (0x7fff7903ce58) System.String.Ctor(System.ReadOnlySpan`1<Char>) string *(valuetype System.ReadOnlySpan`1<char>)
TID 3378: Calling invokeCompileMethod...
Generating interpretation stub (# 48 = 0x30, hash = 0xdf6fb278) for String:Ctor.
TID 3378: Got through invokeCompileMethod
TID 3378: Done Jitting method System.String::Ctor  string *(valuetype System.ReadOnlySpan`1<char>) }
TID 3378: D::JITComplete: md:0x7fff7903ce58 (System.String::Ctor), address:0x7fff77afe8f0.
TID 3378: JitComplete completed successfully
TID 3378: Jitted Entry at 00007fff`77afe8f0 method System.String::Ctor string *(valuetype System.ReadOnlySpan`1<char>)
TID 3378: CrstBase::Destroy 0x5555556319e0
Entering method #61 (= 0x3d): String:Ctor(valueclass):class.
 arguments:
# String:Ctor(valueclass) take arg[0] as part of `valueclass` incorrectly because HasThis()==false
         0: valueclass: <ReadOnlySpan`1>: [0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0xb0 0x1b 0xff 0xff 0xff 0x7f 0x00 0x00]

      <empty>
     0: nop

```

### Reproduction Steps

dotnet run hello.dll

```
DOTNET_LogEnable=1;
DOTNET_LogToConsole=1;
DOTNET_LogLevel=10;
DOTNET_JitFunctionTrace=1;
DOTNET_ForceInterpreter=1;
DOTNET_Interpret=*;
DOTNET_ZapDisable=1;
DOTNET_ReadyToRun=0;
DOTNET_DumpInterpreterStubs=1;
DOTNET_TraceInterpreterEntries=1;
DOTNET_TraceInterpreterIL=1;
DOTNET_TraceInterpreterOstack=1
```

### Expected behavior

|          | `System.String::Ctor` | `System.String::.ctor` | 
|-------|-----------------------|------------------------|
| .NET8 | HasThis()==true      | HasThis()==true        |
| .NET6 | HasThis()==true       | HasThis()==true        |

### Actual behavior

|          | `System.String::Ctor` | `System.String::.ctor` | 
|-------|-----------------------|------------------------|
| .NET8 | HasThis()==false      | HasThis()==true        |
| .NET6 | HasThis()==true       | HasThis()==true        |

**Comment by huoyaoyuan** [comment]
This comes from a code unification at #62936. The helper code has special recognition of string constructors and clears `HasThis` on it.
/cc @jkotas

**Comment by jkotas** [comment]
The interpreter needs to do a check like https://github.com/dotnet/runtime/pull/62936/files#diff-2b3fca81989bfe1e489ae6e784574792a3ef32aeca37ac640bf42f5651f4655eR1272 somewhere.

You are likely going to run into more bugs once this one is fixed. The CoreCLR interpreter is not maintained or tested.

**Comment by nikolahua** [comment]
Update HasThis check for string constructor in PR https://github.com/dotnet/runtime/pull/97849. @huoyaoyuan @jkotas

**Comment by nikolahua** [comment]
This issue can be closed.
