### ISSUE TITLE
`JsonNode.DeepEquals()` erroneously considers number representation

### ISSUE THREAD

**Issue by gregsdennis** [dotnet/runtime#97490]
### Description

When a `JsonValue` with an integer value is compared to a `JsonValue` with a decimal that has been initialized with a zero fractional part, `object.Equals()` returns true, but `JsonValue.DeepEquals()` returns false.

In JSON, all numbers are treated equally, with arbitrary precision.  As such, `4` and `4.0` are equivalent JSON values.

### Reproduction Steps

```c#
public void Repro()
{
    JsonNode intFour = 4;
    JsonNode floatFour = 4.0m;

    Console.WriteLine("4 == 4.0:   {0}", 4 == 4.0m);  // true
    Console.WriteLine("DeepEquals: {0}", JsonNode.DeepEquals(intFour, floatFour));  // false
}
```

### Expected behavior

I expect both to return true.

### Actual behavior

`JsonValue.DeepEquals()` returns false.

### Regression?

No.  `JsonNode.DeepEquals()` is new to .Net 8.

### Known Workarounds

I have defined my own equality methods, published in _Json.More.Net_, but was hoping to be able to remove this functionality for .Net 8.

### Configuration

.Net 8 (any build), x64.

**Comment by huoyaoyuan** [comment]
`4 == 4.0m` or `4.0m.Equals(4)` is converting the `int` to `decimal` with implicit conversion. The `object.Equals(object)` overload returns false.

If we take the concept that JSON has only one number type, how should we deal with the precision of `long`?

**Comment by gregsdennis** [comment]
> If we take the concept that JSON has only one number type, how should we deal with the precision of `long`?

You answered it: we take the concept that JSON has only one number type.

If the numerical value is the same, then they're JSON-equal.

**Comment by gregsdennis** [comment]
Yeah I initially did something similar, but considerably less efficient. I would `.ToString()` the two numbers and compare the output.

But recently, I figured out that `decimal` encodes the significant digits in order to output them again.  Thus with `decimal`s, 4 isn't exactly the same as 4.0 because their precision is different.

I've since moved on to this: https://github.com/gregsdennis/json-everything/blob/master/Json.More%2FJsonNodeExtensions.cs#L50-L52.  `.GetNumber()` extracts the value as a `decimal`, so now I'm doing a`decimal` equality check.  This limits me to the `decimal` value range, but I'm comfortable with that.

**Comment by lphilippidis** [comment]
4 and 4.0 have different meanings in scientific notation. significant digits and the like. they could be converted to one another but should not be considered equal in scientific calculations.

**Comment by gregsdennis** [comment]
Granted, and I don't disagree.  But I'm after JSON equality here.

**Comment by eiriktsarpalis** [comment]
They are equal in JavaScript which is what we should want to emulate.
