### ISSUE TITLE
ClientWebSocket.ConnectAsync hangs if the response content is buffered. Is this expected behavior?  

### ISSUE THREAD

**Issue by demchenkov** [dotnet/runtime#97502]
### Description

Hello!
I am trying to use `ClientWebSocket` in my ASP.NET 8 Minimal API application. 
Something like: 
```csharp
  app.MapGet("/", async () =>
  {
    var uri = new Uri("wss://example.com/?encoding=json");

    using (var socket = new ClientWebSocket())
    {
      await socket.ConnectAsync(uri, CancellationToken.None);
      Console.WriteLine("Connected 1!");
    }

    using (var socket = new ClientWebSocket())
    {
      await socket.ConnectAsync(uri, CancellationToken.None);
      Console.WriteLine("Connected 2!");
    } 
  });
```

And it works fine. 

But as soon as I added OpenTelemetry and started buffering the response content stream into memory via `Content.LoadIntoBufferAsync()` to enrich my OTel data, the provided example stopped working. 

If wait long enough I can get 
`System.ArgumentException: The base stream is not writeable. (Parameter 'stream')`
I did an investigation and realized that WebSocket was created by `WebSocket.CreateFromStream` but as soon as the response content was already buffered the concrete type which was passed into the method is `System.IO.MemoryStream(writeable: false)` instead of `RawConnectionStream`.

So my question is: is this expected behavior? 

### Reproduction Steps

Minimal reprodusible example

```csharp 
using System.Net.WebSockets;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddTransient<BufferingHandler>();
builder.Services.AddHttpClient("buffering")
  .AddHttpMessageHandler<BufferingHandler>();

var app = builder.Build();

app.MapGet("/", async (IHttpClientFactory factory, ILoggerFactory loggerFactory) =>
{
  var logger = loggerFactory.CreateLogger("example");
  var clientWithBuffering = factory.CreateClient("buffering");
  var client = factory.CreateClient();
  var uri = new Uri("wss://example.com/?encoding=json");

  var socket = new ClientWebSocket();
  await socket.ConnectAsync(uri, client, CancellationToken.None);
  logger.LogWarning("Connected without buffering!");
  socket.Dispose();

  socket = new ClientWebSocket();
  await socket.ConnectAsync(uri, clientWithBuffering, CancellationToken.None);
  logger.LogWarning("Connected buffered!");
  socket.Dispose();

});

app.Run();

public class BufferingHandler : DelegatingHandler
{
  protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  {
    var response = await base.SendAsync(request, cancellationToken);
    await response.Content.LoadIntoBufferAsync();
    return response;
  }
}

```

### Expected behavior

I can use `ClientWebSocket` even with buffered content

### Actual behavior

`ClientWebSocket` hangs if the response content was buffered before.

### Configuration

.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.71b9f198

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100\

.NET workloads installed:
 Workload version: 8.0.100-manifests.71b9f198
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

**Comment by MihaZupan** [comment]
WebSockets is a live bi-directional protocol. By blocking to buffer one side of the communication, you're preventing `ClientWebSocket` from receiving/parsing/replying to new messages as they come in.
Waiting until all data is received (`LoadIntoBufferAsync`) will always break such communication.

If you want a copy of the transferred data for logging purposes, you can wrap the content stream with a custom one that saves the data as it's flowing through instead, thus letting `ClientWebSocket` consume the data as it's coming in. You can use https://learn.microsoft.com/aspnet/core/fundamentals/http-logging as an inspiration.

**Comment by demchenkov** [comment]
Thank you very much!
So I assumed correctly that this is expected behavior, I'll close the issue
