### ISSUE TITLE
Error ! .Net 8 Maui Cannot run some machines, but .Net 6 can run these machines, now you force update vs 2022 to use .net8 ,it give me big trouble！！！！！！！

### ISSUE THREAD

**Issue by blackcatpolice** [dotnet/runtime#97516]
### Description

Net 8 Maui Cannot run some machines, but .Net 6 can run these machines, now you force update vs 2022 to use .net8 ,it give me big trouble！！！！！！！

### Reproduction Steps

Can not find any error message. Even I use vs 2022 latest in these machine , the project cannot run(F5) .

### Expected behavior

Lanch

### Actual behavior

Cannot run

**Comment by blackcatpolice** [comment]
I can not find any launch error message. The vs 2022 latest version cannot run project in these machines,  and there is no any message in output

**Comment by hoyosjs** [comment]
@jonathanpeppers any reports or ideas?

**Comment by blackcatpolice** [comment]
> @jonathanpeppers any reports or ideas?

The key is why vs 2022 latest version force update to .net 8 ? and not support .net 6 ? My .net 6 project can not open. So I have to uprade my project . But .net 8 is not perfect! My production environment is now severely affected.

Use vs 2022 latest version open .net project is like this:
![image](https://github.com/dotnet/runtime/assets/4312114/ae9fc21d-7060-4232-a17f-262c54f07df4)

**Comment by colejohnson66** [comment]
Install the .NET 6.0 SDK.

**Comment by jonathanpeppers** [comment]
.NET 6 is out of support for MAUI: https://dotnet.microsoft.com/platform/support/policy/maui

So the error message about, you'd get if you tried to build a `net6.0-*` MAUI app with the .NET 8 SDK (or higher).

You can install the .NET 6 or 7 SDK & optional workloads to use it in an unsupported fashion. You'd also need a `global.json` to pin back to the older SDK.

**Comment by blackcatpolice** [comment]
> .NET 6 不再支持 MAUI： https: [//dotnet.microsoft.com/platform/support/policy/maui](https://dotnet.microsoft.com/platform/support/policy/maui)
> 
> `net6.0-*`因此，如果您尝试使用 .NET 8 SDK（或更高版本）构建 MAUI 应用程序，您会收到有关错误消息。
> 
> 您可以安装 .NET 6 或 7 SDK 和可选工作负载，以不受支持的方式使用它。您还需要一个`global.json`固定回旧版 SDK 的方法。

Can you  tell me how to use the global.json .Set the global.json on common path or project path? Thanks

**Comment by blackcatpolice** [comment]
> 科尔

This is  upgrade to .net8, I originally used .net6

**Comment by blackcatpolice** [comment]
> .NET 6 is out of support for MAUI: https://dotnet.microsoft.com/platform/support/policy/maui
> 
> So the error message about, you'd get if you tried to build a `net6.0-*` MAUI app with the .NET 8 SDK (or higher).
> 
> You can install the .NET 6 or 7 SDK & optional workloads to use it in an unsupported fashion. You'd also need a `global.json` to pin back to the older SDK.

Can you tell me how to use the global.json .Set the global.json on common path or project path? Thanks

I tried global.json many months ago , but it doesn't work

**Comment by blackcatpolice** [comment]
> Install the .NET 6.0 SDK.

This is upgrade to .net8, I originally used .net6. 

This is  caused by VS latest version force upgrade to .net 8 .

If I upgrade the project to .net8 . I can deploy the package . But the package[msix, .net8] not work on some win10 machine. 

And on these not work machines, I install VS latest version, and run the project[.net8], it also don't work

**Comment by blackcatpolice** [comment]
![image](https://github.com/dotnet/runtime/assets/4312114/bf491aba-f200-41c8-b425-830bad2faab2)
![image](https://github.com/dotnet/runtime/assets/4312114/0a9bb712-b9af-441e-bed3-9831ee3675b6)

I created global.json in the project and globally and .net6 sdk is installered. But the VS also alert error: “Unable to identify target 

platform”

![image](https://github.com/dotnet/runtime/assets/4312114/f97f0d72-b4fc-42aa-b2c7-d9a4b5c4c46a)

It means VS can not recognize the old version project file?

@jonathanpeppers

**Comment by huoyaoyuan** [comment]
There are a few things to consider:

What's the output of `dotnet workload list` *inside the project folder*? It should take the `global.json` and list the workloads associated to 6.0 SDK.
You can also run `dotnet workload install` to install maui workloads.

Once workloads are correctly installed for 6.0, is there any difference between command line build result and Visual Studio?
