### ISSUE TITLE
[API Proposal]:  Allow replace ArrayPool<T>.Shared to custom pool

### ISSUE THREAD

**Issue by kefyru** [dotnet/runtime#97512]
### Background and motivation

There are many discussions about memory corruption using ArrayPool<T>.Shared
1. Forget to return
2. Double return
3. Return and continue using

Worst of all, it is hard to debug such problems...
Proposal is to allow set Shared array pool before class initialisation

[See experiment](https://github.com/kefyru/ArrayPoolExperiment.git)

| Method       | Mean     | Error    | StdDev   | Allocated |
|------------- |---------:|---------:|---------:|----------:|
| Default | 10.77 ns | 0.019 ns | 0.017 ns |         - |
| Mock     | 11.24 ns | 0.026 ns | 0.023 ns |         - |

### API Proposal

```csharp
[AttributeUsage(AttributeTargets.Assembly)]
public class DefaultSharedArrayPoolAttribute(Type type) : Attribute
{
  public Type Type { get; } = type;
}

/// <summary>
/// Mock class (simulates System.Buffers.ArrayPool[T])
/// </summary>
/// <typeparam name="T"></typeparam>
public abstract class ArrayPool<T>
{
  protected static ArrayPool<T>? Default { get; private set; }

  private static readonly ArrayPool<T> s_shared;
  public static ArrayPool<T> Shared => s_shared;

  static ArrayPool()
  {
    Default = new SharedArrayPool<T>();
    try {
      var type = Assembly.GetEntryAssembly()
                        ?.GetCustomAttribute<DefaultSharedArrayPoolAttribute>()
                        ?.Type;

      if (type is not null)
        s_shared = (ArrayPool<T>)Activator
         .CreateInstance(type.MakeGenericType([typeof(T)]))!;
    }
    finally {
      s_shared ??= Default;
      Default  =   null;
    }

  }

  public abstract T[] Rent(int size);
  public abstract void Return(T[] array);
}
```

### API Usage

```csharp
[assembly: DefaultSharedArrayPool(typeof(ArrayPoolWithTracking<>))]
namespace ArrayPoolExperiment;
public static class Program
{
  public static void Main(params string[]? args)
  {
    var arr = ArrayPool<byte>.Shared.Rent(1024);
    ArrayPool<byte>.Shared.Return(arr); // ok
    ArrayPool<byte>.Shared.Return(arr); // should output message
    
    BenchmarkRunner.Run<Test>();
  }
}
```

```csharp

public sealed class ArrayPoolWithTracking<T> : ArrayPool<T>
{
  private static readonly ArrayPool<T> s_default;
  private static readonly long             s_hash = Random.Shared.NextInt64();
  
  static ArrayPoolWithTracking()
  {
    s_default = Default!;
    if (s_default is null) throw new InvalidOperationException();
  }

  public override T[] Rent(int size)
  {
    var array = s_default.Rent(size);
    if (typeof(T) == typeof(byte) || typeof(T) == typeof(char)) {
      ref var hash = ref Unsafe.As<byte, long>(ref MemoryMarshal.GetArrayDataReference((Array)array));
      if (hash != s_hash) {
        if (GC.GetGeneration(array) != 0) // gen = 0, more likely it is new array
          throw new InvalidOperationException($"{array.GetType()} was used after returning to pool");
      }

      hash = 0;
    }
    // update statistics to detect leaks...
    // other checks...
    return array;
  }
  public override void Return(T[] array)
  {
    if (typeof(T) == typeof(byte) || typeof(T) == typeof(char)) {
      ref var hash = ref Unsafe.As<byte, long>(ref MemoryMarshal.GetArrayDataReference((Array)array));
      if (hash == s_hash) {
        // Possible double return
        // stop the program to check code manually in this point
        var stackTrace = new StackTrace();
        Console.WriteLine("Possible double return array to pool");
        Console.WriteLine(stackTrace);
        // if (Debugger.IsAttached) Debugger.Break();
        // we won't return this array to pool, just in case
        return;
      }

      hash = s_hash;
    }
    // update statistics to detect leaks...
    // other checks...
    s_default.Return(array);
  }
}

```

**Comment by Wraith2** [comment]
You, the consumer, do not own the ArrayPool and so it does need testing by you. You should test your code and trust others to test theirs.

**Comment by kefyru** [comment]
ArrayPool, by it self, does not need to testing, but it allow to corrupt data. It is very possible in large business projects with many developers.
Using different pool will cause unnecessary memory usage, because all core libs use SharedArrayPool and my app will use another pool, both allocate memory (for each thread by the way).
Using proxy (to ArrayPool.Shared) for in-app using also does not resolve problem. For example, to check double return byte[] or char[] we should set any signature (hash) to those arrays  when returning and check it when renting. But core libs do not do this and we cant manage this process.

Suggestion is to manage ArrayPool.Shared on application level (not by Libs from Nuget packeges) thats why DefaultSharedArrayPoolAttribute usage is AttributeTargets.Assembly and ArrayPool should get implementation from entry assembly only.

If no implementation found, ArrayPool just use default SharedArrayPool and there will be no any performance changes.

**Comment by tannergooding** [comment]
There are no plans to allow user customization of the default shared pool.

The proposed approach is not AOT/trim friendly and may prevent various JIT optimizations. There may also be correctness, usability, or even security concerns from making the existing API now able to use any user defined implementation without an explicit opt-in (there is also the consideration of potential conflicts if multiple pieces of code try to override the default).

If you need to customize array poool behavior, such as for testing or other purposes, you should allow it to be passed in as a parameter or provide your own wrapper that allows it to be customized for your app (then using the wrapper for all of your own needs).
