### ISSUE TITLE
RuntimeILGenerator emits bad IL for Ldc_I4 with values >= -128 and <= 127

### ISSUE THREAD

**Issue by wasabii** [dotnet/runtime#97520]
### Description

[Ldc_I4](https://github.com/dotnet/runtime/blob/135fec006e727a31763271984cd712f1659ccbd3/src/coreclr/System.Private.CoreLib/src/System/Reflection/Emit/RuntimeILGenerator.cs#L423)

This call favors the overload that accepts a short. Thus emitting a short argument, instead of a byte argument as required by Ldc_I4_S.

This is.... well.... I don't know. This seems basic. I'm surprised nobody noticed.

I get the feeling nobody uses ILGenerator anymore since you can't save.

I noticed because I forked ILGenerator to implement saving.

My guess here is, well, nobody has been using ILGenerator in years in any significant way. And if that's true, all of these optimizations are suspect.

Also they're terrible. How can I track instruction length when I emit instructions if the generator just changes them automatically!!!

Bug doensn't exist in Framework (which adds no optimizations).

### Reproduction Steps

il.Emit(Opcodes.Ldc_I4, 1);

### Expected behavior

Uses a single byte argument.

### Actual behavior

Uses a two byte argument.

### Regression?

From framework, yes. Framework does no optimizations here, changing IL for a user. Thank goodness.

### Known Workarounds

Do range checks yourself first and cast yourself first to avoid this Emit(opc, int) path.

**Comment by stephentoub** [comment]
> This call favors the overload that accepts a short. Thus emitting a short argument, instead of a byte argument as required by Ldc_I4_S.

I don't understand the concern.  The code you linked to passes in an sbyte:
https://github.com/dotnet/runtime/blob/135fec006e727a31763271984cd712f1659ccbd3/src/coreclr/System.Private.CoreLib/src/System/Reflection/Emit/RuntimeILGenerator.cs#L423
which is what that instruction supports:
https://learn.microsoft.com/en-us/dotnet/api/system.reflection.emit.opcodes.ldc_i4_s?view=net-8.0
"The following [Emit](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.emit.ilgenerator.emit?view=net-8.0) method overloads can use the ldc.i4.s opcode:

[ILGenerator.Emit(OpCode, Byte)](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.emit.ilgenerator.emit?view=net-8.0#system-reflection-emit-ilgenerator-emit(system-reflection-emit-opcode-system-byte))
[ILGenerator.Emit(OpCode, SByte)](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.emit.ilgenerator.emit?view=net-8.0#system-reflection-emit-ilgenerator-emit(system-reflection-emit-opcode-system-sbyte))"

> I get the feeling nobody uses ILGenerator anymore since you can't save.

We use ILGenerator it many places, for dynamic code generation at run time.  For example, when you use RegexOptions.Compiled, or as part of ASP.NET Routing, or as part of the DependencyInjection library, and so on.

> Bug doensn't exist in Framework (which adds no optimizations).

The .NET Framework _does_ optimize instructions, just not as much. For example, if you specify ldloc, it'll try to optimize to use ldloc_0, ldloc_1, ldloc_2, ldloc_3, or ldloc_s if possible:
https://referencesource.microsoft.com/#mscorlib/system/reflection/emit/ilgenerator.cs,876

> Reproduction Steps

Can you please share a runnable repro showing the problem?  For example, this prints out `1`, as I'd expect:
```C#
using System.Reflection.Emit;

DynamicMethod dm = new DynamicMethod("GetValue", typeof(int), null);
ILGenerator il = dm.GetILGenerator();
il.Emit(OpCodes.Ldc_I4, 1); // your repro
il.Emit(OpCodes.Ret);

Func<int> f = dm.CreateDelegate<Func<int>>();
Console.WriteLine(f());
```

**Comment by wasabii** [comment]
I'm so sorry. And embarressed. Looks like there is an sbyte overload available in the base class of RuntimeILGenerator. And it was being ingnored in my local build environment for other reasons, so the C# compiler was favoring the short version as the nearest.

Closing. This isn't an issue. I'm an idiot.
