### ISSUE TITLE
dotnet/runtime fails to build on Ubuntu 22.04 with /p:PortableBuild=false

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#97521]
When following the [build requirements](https://github.com/dotnet/runtime/blob/main/docs/workflow/requirements/linux-requirements.md) for Ubuntu 22.04, I get the following issue when building without `PortableBuild` true:

`./build.sh -c Release /p:PortableBuild=false`

```
ld.lld : error : undefined symbol: OpenSSL_version_num [/home/vihofer/git/runtime/src/coreclr/tools/aot/crossgen2/crossgen2_publish.csproj]
ld.lld : error : undefined symbol: OPENSSL_init_ssl [/home/vihofer/git/runtime/src/coreclr/tools/aot/crossgen2/crossgen2_publish.csproj]
ld.lld : error : undefined symbol: CRYPTO_get_ex_new_index [/home/vihofer/git/runtime/src/coreclr/tools/aot/crossgen2/crossgen2_publish.csproj]
ld.lld : error : undefined symbol: OCSP_RESPONSE_free [/home/vihofer/git/runtime/src/coreclr/tools/aot/crossgen2/crossgen2_publish.csproj]
ld.lld : error : undefined symbol: ERR_peek_last_error [/home/vihofer/git/runtime/src/coreclr/tools/aot/crossgen2/crossgen2_publish.csproj]
ld.lld : error : undefined symbol: ERR_clear_error [/home/vihofer/git/runtime/src/coreclr/tools/aot/crossgen2/crossgen2_publish.csproj]
ld.lld : error : undefined symbol: ERR_error_string_n [/home/vihofer/git/runtime/src/coreclr/tools/aot/crossgen2/crossgen2_publish.csproj]
ld.lld : error : undefined symbol: EVP_MD_CTX_new [/home/vihofer/git/runtime/src/coreclr/tools/aot/crossgen2/crossgen2_publish.csproj]
ld.lld : error : undefined symbol: EVP_md5 [/home/vihofer/git/runtime/src/coreclr/tools/aot/crossgen2/crossgen2_publish.csproj]
ld.lld : error : undefined symbol: EVP_MD_CTX_set_flags [/home/vihofer/git/runtime/src/coreclr/tools/aot/crossgen2/crossgen2_publish.csproj]
ld.lld : error : undefined symbol: EVP_DigestInit_ex [/home/vihofer/git/runtime/src/coreclr/tools/aot/crossgen2/crossgen2_publish.csproj]
ld.lld : error : undefined symbol: EVP_MD_CTX_free [/home/vihofer/git/runtime/src/coreclr/tools/aot/crossgen2/crossgen2_publish.csproj]
ld.lld : error : undefined symbol: EVP_DigestUpdate [/home/vihofer/git/runtime/src/coreclr/tools/aot/crossgen2/crossgen2_publish.csproj]
ld.lld : error : undefined symbol: EVP_DigestFinal_ex [/home/vihofer/git/runtime/src/coreclr/tools/aot/crossgen2/crossgen2_publish.csproj]
ld.lld : error : undefined symbol: EVP_MD_get_size [/home/vihofer/git/runtime/src/coreclr/tools/aot/crossgen2/crossgen2_publish.csproj]
ld.lld : error : undefined symbol: EVP_MD_fetch [/home/vihofer/git/runtime/src/coreclr/tools/aot/crossgen2/crossgen2_publish.csproj]
ld.lld : error : undefined symbol: EVP_sha1 [/home/vihofer/git/runtime/src/coreclr/tools/aot/crossgen2/crossgen2_publish.csproj]
ld.lld : error : undefined symbol: EVP_sha256 [/home/vihofer/git/runtime/src/coreclr/tools/aot/crossgen2/crossgen2_publish.csproj]
ld.lld : error : undefined symbol: EVP_sha384 [/home/vihofer/git/runtime/src/coreclr/tools/aot/crossgen2/crossgen2_publish.csproj]
ld.lld : error : undefined symbol: EVP_sha512 [/home/vihofer/git/runtime/src/coreclr/tools/aot/crossgen2/crossgen2_publish.csproj]
```

**Comment by ViktorHofer** [comment]
@agocke mentioned that this might be related to https://github.com/dotnet/runtime/issues/66859

**Comment by agocke** [comment]
This is definitely https://github.com/dotnet/runtime/issues/66859.

I'm still thinking about the right fix for that.

In the meantime, I've realized that the crossgen_publish condition is wrong. It shouldn't be conditioned on source build, it should be conditioned on portable. I'll submit a fix.

**Comment by blowdart** [comment]
The SDL requires a cryptoboard exception for static linking OpenSSL and you'd have to produce patches for every security release.

Let's not head down that route.

**Comment by jkotas** [comment]
> The SDL requires a cryptoboard exception for static linking OpenSSL

This issue has no effect on the bits that Microsoft ships and supports. This issue is about the build configuration used by Linux distros build. Linux distros are in the full control of that configuration and they have very similar (sometimes even stricter) concerns to cryptoboard, but their ultimate decision is outside of the Microsoft cryptoboard jurisdiction.

> enable StaticOpenSslLinking

We just need the part of StaticOpenSslLinking that passes `-lssl -lcrypto` to the linker. It is not desirable to statically include openssl copy in the crossgen binary as @blowdart pointed out. We just need to pass `-lssl -lcrypto` to the linker for non-portable build. One way to do it:
- Drop a `nonportablebuild.txt` cookie file to the package when producing non-portable build of nativeaot
- Build targets check for the existence of the cookie and pass `-lssl -lcrypto` arguments to the linker when it is present

We do the same thing for debug CRT on Windows: https://github.com/search?q=repo%3Adotnet%2Fruntime%20debugucrt.txt&type=code

**Comment by blowdart** [comment]
Ah it's for source build? 

As long as none of those builds are run in our own services it's fine ... but can that be promised?

**Comment by jkoritzinsky** [comment]
I don't believe we have any desire to ship support for non-portable NativeAOT in this aspect; my comment was only about using it within the repository (where we can implement it entirely within MSBuild). @agocke mentioned he was also apprehensive about using it in-repo as well.

In any case, we're fixing the build failure with #97523 by using the single file configuration for non-portable builds.

**Comment by bartonjs** [comment]
Non-portable AOT should just be using normal dynamic linking... as Jan said, the `-lssl -lcrypto` options.

**Comment by jkotas** [comment]
Fixed by #97523

**Comment by agocke** [comment]
I think the very concept of "non-portable Native AOT" is somewhat broken, and more likely to get us into bad customer experiences later.

That is, a "non-portable" copy of Native AOT is basically a copy of Native AOT that can only _build for_ the _exact_ OS it was _built on_. So an Ubuntu 22.04 would only be able to build for Ubuntu 22.04. Not RHEL, not Arch, not even Ubuntu 20.04.

This is like shipping a copy of gcc that could only build for the exact OS you're running on.

I think this is more likely to produce customer confusion and mixups than actually provide benefits. The Native AOT build currently doesn't support non-portable build. I would prefer if we not add it at all.

**Comment by jkotas** [comment]
> I think the very concept of "non-portable Native AOT" is somewhat broken, and more likely to get us into bad customer experiences later.

Why is it broken? It is exactly same as the concept of non-portable runtime packs that exist today. @tmds Does Red Hat build and ships the non-portable runtime packs?

**Comment by jkotas** [comment]
I do not expect that Microsoft is going to ship these non-portable runtime packs. The non-portable runtime packs are for Linux distros that have different requirements and expectations.

**Comment by tmds** [comment]
> I think the very concept of "non-portable Native AOT" is somewhat broken, and more likely to get us into bad customer experiences later.

The default of a non-portable SDK is still to use the portable assets.

To use the non-portable packs, the user needs to explicitly opt-in by setting the platform rid (like `fedora.39-x64`).
This also makes clear to the user that what he is building is platform specific.

> It is exactly same as the concept of non-portable runtime packs that exist today. @tmds Does Red Hat build and ships the non-portable runtime packs?

Yes, we include these in our rpms.

> The non-portable runtime packs are for Linux distros that have different requirements and expectations.

Yes, we care about being able to build and distribute features from source.

**Comment by tmds** [comment]
> This is like shipping a copy of gcc that could only build for the exact OS you're running on.

With this analogy.

Being able to build for other OSes is an important gcc feature.

The distro maintainers will care about gcc being built from source for their OS, and all software on their OS getting built with the distro gcc.

**Comment by agocke** [comment]
> It is exactly same as the concept of non-portable runtime packs that exist today.
> To use the non-portable packs, the user needs to explicitly opt-in by setting the platform rid (like fedora.39-x64).
> This also makes clear to the user that what he is building is platform specific.

Right, I forgot that we ship the compiler itself inside the runtime packs, so we don't have to worry about the wrong compiler being used for a target it wasn't prepared for.

I do find it unfortunate that, by default, the system only provides compilers that can build for the host platform. I don't find this to be a particularly good user experience. I would prefer if all source build platforms built and bundled the portable versions of our runtime packs instead.

**Comment by tmds** [comment]
> I would prefer if all source build platforms built and bundled the portable versions of our runtime packs instead.

This isn't possible because distro guidelines don't allow including pre-compiled binaries.
And, building the portable assets from source isn't feasible because they rely on things that a distro won't provide, like an old glibc version.

Though the resulting binaries won't run on other OSes, they bring the feature to the OS itself by meeting the requirement of building it from source.

> That said, I'm no longer worried that people will hit an unusual situation with Native AOT, compared to self-contained publish. In both cases, you would have to explicitly specify hostRid-arch in order to get a host-specific build. Specifying a RID like linux-x64 would get you appropriately portable bits.

Yes, I also find this important for the UX. The user needs to be explicit about the platform.
