### ISSUE TITLE
JIT: Assertion failed '!"Extra flags on tree"' during 'Post-Morph'

### ISSUE THREAD

**Issue by amanasifkhalid** [dotnet/runtime#97524]
### Error Blob

```json
{
  "ErrorMessage": "",
  "BuildRetry": false,
  "ErrorPattern": "Extra flags on tree",
  "ExcludeConsoleLog": false
}
```

### Reproduction Steps

Example test run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=540840&view=results
Example console log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-97488-merge-c4d5c6c8a7f64d9baf/System.Runtime.InteropServices.Tests/1/console.3fbb3808.log?helixlogtype=result

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=540840
**Error message validated:** `Extra flags on tree`
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 1/25/2024 9:05:04 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[541598](https://dev.azure.com/dnceng-public/public/_build/results?buildId=541598)|dotnet/runtime|[System.Runtime.InteropServices.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=541598&view=ms.vss-test-web.build-test-results-tab&runId=12830290&resultId=212118)||
|[540840](https://dev.azure.com/dnceng-public/public/_build/results?buildId=540840)|dotnet/runtime|[System.Runtime.InteropServices.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=540840&view=ms.vss-test-web.build-test-results-tab&runId=12809492&resultId=212059)|dotnet/runtime#97488|
|[540774](https://dev.azure.com/dnceng-public/public/_build/results?buildId=540774)|dotnet/runtime|[System.Runtime.InteropServices.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=540774&view=ms.vss-test-web.build-test-results-tab&runId=12807304&resultId=212110)|dotnet/runtime#97517|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|3|3|3|

**Comment by amanasifkhalid** [comment]
cc @dotnet/jit-contrib. This is blocking `runtime-coreclr libraries-jitstress`.

**Comment by jakobbotsch** [comment]
Most likely from one of my recent changes. Odd though since I ran libraries-jitstress in them.

**Comment by jakobbotsch** [comment]
Gah, the libraries-jitstress run in #97411 did have those failures, I just misidentified them as #97437.

**Comment by amanasifkhalid** [comment]
> Gah, the libraries-jitstress run in https://github.com/dotnet/runtime/pull/97411 did have those failures, I just misidentified them as https://github.com/dotnet/runtime/issues/97437.

No worries; thanks for the fix!
