### ISSUE TITLE
[API Proposal]: Support await'ing a Task<T> without throwing

### ISSUE THREAD

**Issue by aromaa** [dotnet/runtime#97556]
### Background and motivation

Continuation on the #22144 where the decision was made to disallow `ConfigureAwaitOptions.SuppressThrowing` for `Task<TResult>`. I have stumbled upon a use case where returning `default` on failure would be useful. This was cut from the original proposal to simplify it and one of the concerns was that it would break the nullability annotations.

I'm suggesting adding a new method which appends the `ConfigureAwaitOptions.SuppressThrowing` implicitly and modifies the return value the be a nullable one.

### API Proposal

```diff
namespace System.Threading.Tasks;

public partial class Task<TResult>
{
+	public ConfiguredTaskAwaitable<TResult?> ConfigureAwaitWithSuppressThrowing(ConfigureAwaitOptions additionalOptions = ConfigureAwaitOptions.None);
}
```

### API Usage

```csharp
public static async Task<string?> Example(Task<string> task)
{
    return await task.ConfigureAwaitWithSuppressThrowing();
}
```

### Alternative Designs

Should it be a extension method instead? We could also add it to the `ConfiguredTaskAwaitable<TResult>` itself but does it hinder the discoverability?

```diff
namespace System.Runtime.CompilerServices;

public partial readonly struct ConfiguredTaskAwaitable<TResult>
{
+    public ConfiguredTaskAwaitable<TResult?> WithSuppressThrowing();
}
```
With that the example would look like the following:
```csharp
public static async Task<string?> Example(Task<string> task)
{
    return await task.ConfigureAwait(false).WithSuppressThrowing();
}
```

### Risks

The current analyzer that suggests the `Task` based implementation should be modified.

**Comment by zlatanov** [comment]
I these rare cases, wouldn't something like this suffice:

```c#
var task = ComputeAsync();
await ((Task)task).ConfigureAwait(ConfigureAwaitOptions.SuppressThrowing);

var result = task.IsCompletedSuccessfully ? task.Result : 42;
Console.WriteLine(result);

static async Task<int> ComputeAsync()
{
    await Task.Delay(1000);

    throw new Exception("Boom!");
}
```

**Comment by aromaa** [comment]
It would but its quite bulky and I need it a lot. I wrote small helper for myself to get this all in one line without extra allocations:
```csharp
internal static bool TryGetOrSuppressThrowing<T>(this ValueTask<T> task, out T? value, out Awaiter<T> awaiter)
{
	if (task.IsCompletedSuccessfully)
	{
		value = task.Result;
		awaiter = default;

		return true;
	}
	else
	{
		value = default;
		awaiter = new Awaiter<T>(task.AsTask());

		return false;
	}
}

internal readonly struct Awaiter<T> : ICriticalNotifyCompletion
{
	private readonly ConfiguredTaskAwaitable.ConfiguredTaskAwaiter awaitable;

	internal Awaiter(Task task)
	{
		this.awaitable = task.ConfigureAwait(ConfigureAwaitOptions.SuppressThrowing).GetAwaiter();
	}

	public bool IsCompleted => this.awaitable.IsCompleted;

	public T? GetResult()
	{
		this.awaitable.GetResult();

		return default;
	}

	public void OnCompleted(Action continuation) => this.awaitable.OnCompleted(continuation);
	public void UnsafeOnCompleted(Action continuation) => this.awaitable.UnsafeOnCompleted(continuation);

	public Awaiter<T> GetAwaiter() => this;
}
```

**Comment by colejohnson66** [comment]
What about:

```cs
public static class TaskExtensions
{
    public static async Task<T?> GetResultOrDefault<T>(this Task<T> task)
        where T : class
    {
        ArgumentNullException.ThrowIfNull(task);
        await ((Task)task).ConfigureAwait(ConfigureAwaitOptions.SuppressThrowing);
        return task.IsCompletedSuccessfully ? task.Result : null;
    }
}
```

**Comment by aromaa** [comment]
That allocates new `Task` which I tried to avoid with the above example

**Comment by stephentoub** [comment]
I'm going to close this as I don't see us adding such an API. If the TResult isn't constrained, then making the return type TResult? is a nop for value types, such that there'd be no indication for a consumer whether the operation succeeded. And even for reference types, a null result can be a valid result, so in general just getting back null isn't an indication that a failure occurred. We also wouldn't want to advocate for usage like in the usage example, as there the exception is being completely ignored, rather than the code checking after the await to examine a possible exception and see what may have gone wrong. For cases where you want to await a generic Task without throwing, you can simply add the `((Task)t)`, as was noted above. Thanks for the suggestion, though.

**Comment by aromaa** [comment]
I see, that makes sense.

In my use case the default value is indeed "valid" return value but its used to indicate that the operation was not successful. So whatever the default value comes from the producer or due to the exception is irrelevant for my use case. The producer might fail with cancellation exception which I would like to ignore without cluttering a lot of try/catch blocks around the callers.
