### ISSUE TITLE
Regular high HTTP response times with HTTPClientFactory

### ISSUE THREAD

**Issue by alanq82** [dotnet/runtime#97562]
### Description

We have an application that performs HTTP requests to an another in-house microservice. After upgrading from dotnet 7 to dotnet 8, we are seeing the HTTP response times for these HTTP requests spike regularly, from 100ms to around 1 second. These spikes do not occur for every request but do happen every couple of minutes. Below is the HTTP response times from before and after dotnet upgrade:
![HighLevel-1](https://github.com/dotnet/runtime/assets/10810437/b8c86979-b639-481d-a2c5-0b5971ca34ba)

Here is a closer look at the response times showing the periodic spikes:
![Detail-1](https://github.com/dotnet/runtime/assets/10810437/2233fea7-6cc5-4b42-8127-33d9bda9bbbf)

Metrics from the called microservice indicate all response were made within a 1 to 3 ms time, indicating the external service is not the source of the performance degradation observed.
![ExternalService-1](https://github.com/dotnet/runtime/assets/10810437/5230b76d-b030-4098-a689-67fec27d1954)

The application is hosted on AWS Fargate. No change was made to the CPU and RAM resources assigned to the Fargate tasks. As part of the migration to dotnet 8 we changed the underlying docker image from mcr.microsoft.com/dotnet/aspnet:7.0-alpine3.16 to mcr.microsoft.com/dotnet/aspnet:8.0. When we upgraded from dotnet 6 to 7, we experienced similar behaviour with aspnet:7.0-alpine3.17. Downgrading to aspnet:7.0-alpine3.16 reduced the size of the spikes.

We are using HTTPClientFactory to send the HTTP requests and all other metrics for the application are comparable with what we saw with dotnet 7. It is only the HTTP response times that have deteriorated, which suggests this is where the issue is. We believe this is the correct way to implement HTTPClientFactory.

```builder.Services.AddHttpClient<IExternalClient, ExternalClient>("ExternalClient");```

The ExternalClient HTTP class
```c#
public class ExternalClient : IExternalClient
{
    private readonly HttpClient c_httpClient;

    public ExternalClient(
        HttpClient httpClient)
    {
        this.c_httpClient = httpClient;
        this.c_httpClient.Timeout = TimeSpan.FromSeconds(2);
    }


    public async Task<Response> ExecuteAsync(
        ClientURL url,
        Request request)
    {
        const string _mediaTypeHeaderValue = "application/json";

        var _serialisedRequest = JsonConvert.SerializeObject(request);
        var _content = new StringContent(_serialisedRequest);
        _content.Headers.ContentType = new MediaTypeHeaderValue(_mediaTypeHeaderValue);

        var _responseMessage = await this.c_httpClient.PostAsync(url, _content);
        var _stringResult = await _responseMessage.Content.ReadAsStringAsync();

        return JsonConvert.DeserializeObject<Response>(_stringResult);
    }
}
```

Its called from the controller
```return await this.c_externalClient.ExecuteAsync(url, request);```

**Comment by antonfirsov** [comment]
@alanq82 we need more information to see the root cause behind this issue. Can you please [collect traces using dotnet-trace](https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/telemetry/events#dotnet-trace) for a period that exposes the described behavior, including the follwiong providers:

```
System.Net.Sockets
System.Net.Security
System.Net.Http
System.Net.NameResolution
Private.InternalDiagnostics.System.Net.Http
```

Eg. a command like this could do the job:

```
dotnet-trace collect --providers System.Net.Http,Private.InternalDiagnostics.System.Net.Http,System.Net.Security,System.Net.Sockets,System.Net.NameResolution,System.Threading.Tasks.TplEventSource:0x80:4 --process-id <PID>
```
