### ISSUE TITLE
[API Proposal]: Expose span-based `char.[Try]Parse` publicly

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/runtime#97598]
### Background and motivation

I was doing some string manupulations, which included a bunch of slicing, so I decided to use `ReadOnlySpan`s to improve perf. As a part of my algorythm after slicing a specific part of string I needed to convert it to char with error recovery, so it was natural to use `char.TryParse` for that. At this point I was unpleasantly surprised to discover that even in latest .NET 8 there is no public overload of `char.TryParse` which takes `ReadOnlySpan<char>` as an input. Sure, this is a trivial thing to do, but I think such helper method should be publicly available, especially considering that an internal implementation of it already exists. For consistency purposes span-based `Parse` method should be made public too

### API Proposal

```diff
namespace System;

public readonly struct Char : ...
{
-    internal static char Parse(ReadOnlySpan<char> s)
+    public static char Parse(ReadOnlySpan<char> s)

-    internal static bool TryParse(ReadOnlySpan<char> s, out char result)
+    public static bool TryParse(ReadOnlySpan<char> s, out char result)
}
```

### API Usage

```csharp
using System;

var arg = "--my-char-option=c";
var value = arg.AsSpan(17); // c
if (!char.TryParse(value, out var charOption))
{
    Console.WriteLine("Parse error");
}
```

### Risks

No risks. APIs already exist and string-based public APIs uses them under the hood, so this is just a matter of accessibility modifiers

**Comment by tannergooding** [comment]
It was an explicit decision to not expose this since it was a 1-liner and should be very unnecessary outside of generic contexts.

You have basically 4 options, depending on you're desired behavior:
* `s[0]`
* `!s.IsEmpty ? s[0] : throw new Exception()`
* `(s.Length == 1) ? s[0] : throw new Exception()`
* `(s.Length == 1) ? s[0] : '\0'`

That isn't necessarily a hard "we won't expose this", but that was what API review had already discussed and decided upon when we were initially adding the support.

CC. @stephentoub

**Comment by tannergooding** [comment]
I'd almost say that if this was really desired, it might be better to instead expose `s.Single()` and `s.SingleOrDefault()` APIs which mirror LINQ's methods. With the proposed `ref structs` in generics feature C# is looking at, such APIs might even become available  as a side effect of that work.

**Comment by DoctorKrolic** [comment]
> You have basically 4 options, depending on you're desired behavior:

I don't think there is a 1-line alanog of `TryParse` though. Also string-based APIs are already exposed, making `char` somewhat inconsistent from other .NET types (which are either not parsable at all or expose both string-based and span-based parse methods). And span-based APIs are doing the thing under the hood anyway, so what are arguments for saying "no" then? Maintatce burden? Do you think there will ever be a need to change something about them? If not this then what?

**Comment by tannergooding** [comment]
> I don't think there is a 1-line alanog of TryParse though.

This was the fourth option: `(s.Length == 1) ? s[0] : '\0'`, which you can trivially integrate into your `if` or other expression as needed. You might end up breaking it apart in some cases, but it remains functionally a one liner.

> And span-based APIs are doing the thing under the hood anyway, so what are arguments for saying "no" then? Maintatce burden? Do you think there will ever be a need to change something about them? If not this then what?

I'd have to go back to the original API review to remember the exact reason. A lot of times simple APIs get rejected because they are simple/uncommon and so it is trivial for a user to define their own helper if they really need it.

**Comment by stephentoub** [comment]
> I don't think there is a 1-line alanog of TryParse though. 

The example you gave was:
```C#
if (!char.TryParse(value, out var charOption))
{
    Console.WriteLine("Parse error");
}
```
which as Tanner alluded to is just:
```C#
if (value.IsEmpty)
{
    Console.WriteLine("Parse error");
}
```
IMO, both shorter and cleaner. And if you actually need the value, you just index, eg instead of:
```C#
if (char.TryParse(value, out var charOption))
{
    Console.WriteLine(charOption);
}
```
it's
```C#
if (!value.IsEmpty)
{
    Console.WriteLine(value[0]);
}
```
There's nothing to "parse" here: you have a char already.

**Comment by stephentoub** [comment]
> why does [Try]Parse taking strings exist

From my 20-20 hindsight perspective, a mistake made 20 years ago. And we don't need to double down on mistakes.

**Comment by tannergooding** [comment]
> does mention "generic contexts" where exposing span overloads could be desirable

We already expose the necessary interfaces and explicitly implement the interface members so that they are available from a generic context.

This is only a question about whether `char.Parse(ROSpan<char>)` should also be exposed, and API review has already gone over the point and decided "no", as per the above.

**Comment by colejohnson66** [comment]
> > does mention "generic contexts" where exposing span overloads could be desirable
> 
> We already expose the necessary interfaces and explicitly implement the interface members so that they are available from a generic context.
> 
> This is only a question about whether `char.Parse(ROSpan<char>)` should also be exposed, and API review has already gone over the point and decided "no", as per the above.

Ah, they indeed are exposed as explicit interface implementations. My bad. I was looking at the source and didn't see them; They're required through `INumberBase<T>` (from `IUnsignedNumber<T>`). Ignore what I said then.

I do agree with the decision to not expose them publicly.

**Comment by DoctorKrolic** [comment]
> I think the complaint here isn't so much about needing an API, but about the discrepancy between various types and overloads

Correct. My chain of though was something like this: I need to "parse" char from a string → Is there some helper method in `char`, which can do it in 1 line? → Yes, there is `TryParse` → Wait, there is no overload, which takes ROS\<char\>?! → _Filling this form_
I don't think I would complain about this if I never met string-based overload in the first place

> a mistake made 20 years ago

Unfortunatelly, this means that there is no good answer to this proposal. You either have inconsistent API (like it is currently) or 1 more set of "bad" APIs (if this proposal could be accepted). It seems you've chosen (and by "you" I mean the whole API review crew) to be inconsistent rather then have more "bad" APIs. Understandable. Closing the proposal then.
