### ISSUE TITLE
Unable to delete assembly file after plugin uninstall

### ISSUE THREAD

**Issue by zengqinglei** [dotnet/runtime#976]
**Describe the bug**

When I use the sample code: https://github.com/dotnet/samples/tree/master/core/tutorials/Unloading
Then I want to remove the assembly file after the plugin is uninstalled and I get an exception:

![image](https://user-images.githubusercontent.com/7374317/70961451-cb998d80-20bc-11ea-837c-601b70c8e52a.png)

**Run Environment**
* .NET CORE 3.1
* Windows 10 
![image](https://user-images.githubusercontent.com/7374317/70961722-a8231280-20bd-11ea-852a-eb42a443ac45.png)

Thanks in advance to the .net core team for answering my questions. Thank you!

**Comment by janvorli** [comment]
I've just tried that locally and it worked fine. I wonder if the issue is due to something in your visual studio. Can you please try to run the tests without debugging (use Debug / Start Without Debugging menu option and see if that helps? You can add `Console.WriteLine($"Delete file: {ex}");` to the catch so that you'd see if there was a problem or not.

**Comment by zengqinglei** [comment]
> I've just tried that locally and it worked fine. I wonder if the issue is due to something in your visual studio. Can you please try to run the tests without debugging (use Debug / Start Without Debugging menu option and see if that helps? You can add `Console.WriteLine($"Delete file: {ex}");` to the catch so that you'd see if there was a problem or not.

I just tested it and it works fine in non-debug mode. Is this a problem with Visual Studio? Will you solve this problem?

**Comment by janvorli** [comment]
I think that the problem is that Visual Studio has that Assembly loaded for debugging purposes and holds on it. Which version of Visual Studio are you using? 
cc: @tommcdon

**Comment by zengqinglei** [comment]
> I think that the problem is that Visual Studio has that Assembly loaded for debugging purposes and holds on it. Which version of Visual Studio are you using?
> cc: @tommcdon

I have tried Visual Studio 16.4.0 and Visual Studio 16.4.2, both have this problem.

**Comment by janvorli** [comment]
It works fine for me in Visual Studio 16.4.0. Does it still happen to you if you don't have any breakpoints and don't step through the code and run it with debugging?

**Comment by zengqinglei** [comment]
> It works fine for me in Visual Studio 16.4.0. Does it still happen to you if you don't have any breakpoints and don't step through the code and run it with debugging?

When I didn't have any breakpoints and didn't step through the code and run it through debugging, the file was finally deleted successfully without exception.
But I think it should also be deleted in debug mode. 
Is it necessary to improve it?

**Comment by janvorli** [comment]
Thank you for testing it. I just wanted to try to understand why VS behaves differently on your and my machine. I can repro the problem too now if I set breakpoint somewhere in the plugin (e.g. on the PluginClass.GetMessage method. This confirms that it is a problem in the Visual Studio.
Using ProcessExplorer during the time the host is trying to delete the Plugin.dll to search for process holding the file open, it shows "devenv.exe", which also confirms that.
I would recommend reporting this problem to the Visual Studio team using the "Send feedback" button / "Report a problem" submenu in the Visual Studio itself (in the upper right corner of the visual studio window)

**Comment by zengqinglei** [comment]
> Thank you for testing it. I just wanted to try to understand why VS behaves differently on your and my machine. I can repro the problem too now if I set breakpoint somewhere in the plugin (e.g. on the PluginClass.GetMessage method. This confirms that it is a problem in the Visual Studio.
> Using ProcessExplorer during the time the host is trying to delete the Plugin.dll to search for process holding the file open, it shows "devenv.exe", which also confirms that.
> I would recommend reporting this problem to the Visual Studio team using the "Send feedback" button / "Report a problem" submenu in the Visual Studio itself (in the upper right corner of the visual studio window)

OK, I have followed your comments to report this issue on Visual Studio!
thank you very much!
