### ISSUE TITLE
[Question] Case sensitivity for GetFullPath(string, string) with drive relative paths

### ISSUE THREAD

**Issue by AnakinRaW** [dotnet/runtime#97615]
### Description

When working with `GetFullPath(string, string)` and a drive relative scenario, I noticed that the method returns different results depending on the capitalization of the dirve letter. 

I was wondering why the check is implemented using ordinal (*case sensitive*) comparison when I was actually expecting it to be case insensitive. 

Looking through the original PR comments https://github.com/dotnet/coreclr/pull/15579 did not help (unless I overread something).

### Reproduction Steps

```cs
var basePath = "c:/a/b/c/";
var relativePath = "c:test";
var sameButDifferent = "C:test";

Console.WriteLine(Path.GetFullPath(relativePath, basePath));
Console.WriteLine(Path.GetFullPath(sameButDifferent, basePath));
```

Outputs
```
c:\a\b\c\test
C:\test
```

https://sharplab.io/#v2:C4LgTgrgdgPgAgJgIwFgBQcAMACOSB0AkgPIDc66AbgIZjYBG1AzgKYAK1wAFtgLzYAiAMYgA9NVH1RQ0QPJoadMCwA2nAJaV2nHv2EhgLJsDlVa2JtQC2LAEIRgAEXUAzFy2VRgfQQGEDRibyFBhIAJwAFBzc+ADiLMAAYhAqKtFcEcpqwJra3AA0DMx5XACUpfJ4kelxCcmp6RGWNvZOru6ewIWMrOnlpEA===

### Expected behavior

I expected the the path's root is checked case *in*sensitive

### Actual behavior

the path's root is checked case sensitive

**Comment by colejohnson66** [comment]
Indeed:

https://github.com/dotnet/runtime/blob/7a60900cd1be3361773237d0d0d0293146db5547/src/libraries/System.Private.CoreLib/src/System/IO/Path.Windows.cs#L92

That doesn't make sense, as Windows treats drive letters as case-insensitive. It should probably be `EqualsOrdinalIgnoreCase`.

**Comment by AnakinRaW** [comment]
If that's indeed something that should be changed/fixed, i already have a PR ready to post.
