### ISSUE TITLE
Unnecessary buffer allocations when writing base64 values with `Utf8JsonWriter`.

### ISSUE THREAD

**Issue by habbes** [dotnet/runtime#97628]
### Description

`Utf8JsonWriter.WriteBase64StringValue(ReadOnlySpan<byte>)` implementation calls the [following method](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/src/System/Text/Json/Writer/Utf8JsonWriter.WriteValues.Helpers.cs#L38) to base64-encode the input bytes and write the result to the output buffer:

```c#
[MethodImpl(MethodImplOptions.AggressiveInlining)]
private void Base64EncodeAndWrite(ReadOnlySpan<byte> bytes, Span<byte> output, int encodingLength)
{
    byte[]? outputText = null;

    Span<byte> encodedBytes = encodingLength <= JsonConstants.StackallocByteThreshold ?
        stackalloc byte[JsonConstants.StackallocByteThreshold] :
        (outputText = ArrayPool<byte>.Shared.Rent(encodingLength));

    OperationStatus status = Base64.EncodeToUtf8(bytes, encodedBytes, out int consumed, out int written);
    Debug.Assert(status == OperationStatus.Done);
    Debug.Assert(consumed == bytes.Length);

    encodedBytes = encodedBytes.Slice(0, written);
    Span<byte> destination = output.Slice(BytesPending);

    Debug.Assert(destination.Length >= written);
    encodedBytes.Slice(0, written).CopyTo(destination);
    BytesPending += written;

    if (outputText != null)
    {
        ArrayPool<byte>.Shared.Return(outputText);
    }
}
```

The `Base64EncodeAndWrite` method allocates/rents the `encodedBytes` buffer, uses it to perform the base64 encoding then copies the contents to the output buffer. When you have a lot of concurrent writes (from different requests) and values larger than 256 bytes, the allocations can start to add up.

I think we can skip the temporary buffer and perform the encoding directly into the output buffer like in the snippet below:

```c#
private void Base64EncodeAndWrite(ReadOnlySpan<byte> bytes, Span<byte> output, int encodingLength)
{
  Span<byte> destination = output.Slice(BytesPending);
  OperationStatus status = Base64.EncodeToUtf8(
    bytes,
    destination,
    out int consumed,
    out int written
  );
  
  // removed Debug.Assert statements for brevity
  
  BytesPending += written;
}
```

If you think the proposed change is okay, I can go ahead and create a PR.

### Configuration

.NET 8

### Data

Here's sample call stack where `Base64EncodeAndWrite` contributes to `byte[]` allocations in the large-object-heap.

![image](https://github.com/dotnet/runtime/assets/8460169/a4c39715-187f-4207-b7a7-fb0230908602)

**Comment by eiriktsarpalis** [comment]
Seems like something we could address in conjunction with https://github.com/dotnet/runtime/issues/67337

**Comment by habbes** [comment]
Hi @eiriktsarpalis, should I work on a PR or wait for #67337 to be addressed?

**Comment by eiriktsarpalis** [comment]
Feel free to submit a PR if you can, #67337 is not being prioritized currently. Thanks.
