### ISSUE TITLE
System.Numerics.Tensors tests timing out under DOTNET_JITMinOpts=1 on x86

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#97629]
### Error Blob

```json
{
  "ErrorMessage": "'System.Numerics.Tensors.Tests' END OF WORK ITEM LOG: Command timed out, and was killed",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Reproduction Steps

These tests are timing out when run with `DOTNET_JITMinOpts=1`.

Example run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=543546&view=ms.vss-test-web.build-test-results-tab
Example log: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-07f52de3725e4b168a/System.Numerics.Tensors.Net8.Tests/1/console.78bd6b1b.log?helixlogtype=result

@tannergooding @stephentoub are these tests long-running enough for this to be expected? Should we just disable them in stress configurations?

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=543546
**Error message validated:** `'System.Numerics.Tensors.Tests' END OF WORK ITEM LOG: Command timed out, and was killed`
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 1/29/2024 9:36:30 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[558298](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558298)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558298&view=ms.vss-test-web.build-test-results-tab&runId=13309856&resultId=205213)||
|[557623](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557623)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557623&view=ms.vss-test-web.build-test-results-tab&runId=13290824&resultId=205213)|dotnet/runtime#98096|
|[557612](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557612)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557612&view=ms.vss-test-web.build-test-results-tab&runId=13290768&resultId=205213)|dotnet/runtime#98107|
|[557374](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557374)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557374&view=ms.vss-test-web.build-test-results-tab&runId=13283630&resultId=205213)|dotnet/runtime#98048|
|[556608](https://dev.azure.com/dnceng-public/public/_build/results?buildId=556608)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=556608&view=ms.vss-test-web.build-test-results-tab&runId=13263538&resultId=205205)||
|[554712](https://dev.azure.com/dnceng-public/public/_build/results?buildId=554712)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=554712&view=ms.vss-test-web.build-test-results-tab&runId=13209692&resultId=205200)||
|[553688](https://dev.azure.com/dnceng-public/public/_build/results?buildId=553688)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=553688&view=ms.vss-test-web.build-test-results-tab&runId=13185124&resultId=205080)|dotnet/runtime#97897|
|[551611](https://dev.azure.com/dnceng-public/public/_build/results?buildId=551611)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=551611&view=ms.vss-test-web.build-test-results-tab&runId=13118016&resultId=205079)|dotnet/runtime#97897|
|[548901](https://dev.azure.com/dnceng-public/public/_build/results?buildId=548901)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=548901&view=ms.vss-test-web.build-test-results-tab&runId=13044804&resultId=204959)||
|[544009](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544009)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544009&view=ms.vss-test-web.build-test-results-tab&runId=12907514&resultId=204932)||
|[543546](https://dev.azure.com/dnceng-public/public/_build/results?buildId=543546)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=543546&view=ms.vss-test-web.build-test-results-tab&runId=12888680&resultId=204932)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|4|8|11|

**Comment by stephentoub** [comment]
They take ~40s in release on my machine. They also rely heavily on generic specialization, inlining, and unused code being eliminated early. Might be worth a short investigation to understand what's causing the timeouts, eg is it just the tests taking longer, is the jit itself actually taking too long, etc

**Comment by jakobbotsch** [comment]
I took a quick look at one of the timeouts; that one seems to make good progress until `System.Numerics.Tensors.Tests.ConvertTests.ConvertTruncatingAndSaturating`.  We end up in code like
https://github.com/dotnet/runtime/blob/a78ddcc5ce0d4af6d2f790d2041dae3ff318e122/src/libraries/System.Private.CoreLib/src/System/Half.cs#L1948-L2000
and
https://github.com/dotnet/runtime/blob/a78ddcc5ce0d4af6d2f790d2041dae3ff318e122/src/libraries/System.Private.CoreLib/src/System/Int128.cs#L1731-L1786
which, when unfolded, invokes the `JIT_GetRuntimeType` fcall a number of times, which is itself quite slow in checked builds. A perfview trace for a couple of minutes when running this test single threaded gives

![image](https://github.com/dotnet/runtime/assets/7887810/69bff5c8-9f19-41c9-8187-77c3ef15b7c3)

![image](https://github.com/dotnet/runtime/assets/7887810/3cdc5e57-51e2-4d2c-ad9d-98105310d296)


I didn't see any indication that something is deadlocked, so seems like we should just disable under minopts/stress.

**Comment by jakobbotsch** [comment]
That test `System.Numerics.Tensors.Tests.ConvertTests.ConvertTruncatingAndSaturating` takes a long time even in release (multiple minutes on my machine). Should perhaps be made a bit more lightweight.

**Comment by stephentoub** [comment]
> That test `System.Numerics.Tensors.Tests.ConvertTests.ConvertTruncatingAndSaturating` takes a long time with a checked runtime, even without `JITMinOpts=1` (multiple minutes on my machine). Should perhaps be made a bit more lightweight.

The whole test suite takes ~40s on my machine. I'm surprised that one test would be taking minutes. That's with a release runtime?

**Comment by tannergooding** [comment]
I'm not sure how much more light weight such tests can really be made either. We have complex functionality here that needs to be tested. Due to the API signature and the need to use generics, we need to type check to ensure efficiency, and we need to test a range of edge case behaviors.

Would splitting it out into more tests help here?

**Comment by jakobbotsch** [comment]
> Would splitting it out into more tests help here?

I think that would help as well.

I do wonder if the overall total of conversions could be reduced, however. Currently it is doing 17 * 17 (all from/to combinations) * 256 * 255 (different tensor lengths) conversions. Perhaps not every combination of from/to needs to try all possible tensor lengths in that range.
