### ISSUE TITLE
iOS app crashes on release mode when performing a .Sum on a List of 20k+ items

### ISSUE THREAD

**Issue by andyx48** [dotnet/runtime#97625]
### Description

Our production app is crashing without leaving any stacktrace when performing a .Sum or .Average on a List of ~20k items in release mode.

When manually performing the operation in a foreach instead of using .Sum, works as expected.

I have also tried to replicate the .Sum method on my code to see where the issue arises, and it seems that the use of Generics is what is making the app to crash, when changing the generics data types to defined data types, the app does not crash.

I have attached a basic reproduction app.

### Steps to Reproduce

1. Create a new dotnet MAUI app.
2. Create a List of a custom model with one of the properties being a decimal.
3. Add 20k elements to the list.
4. Perform a List.Sum(x=>x.DecimalProperty)

Expected result:
To perform the sum of the items.

Actual results:
The app crashes when attempting to perform the operation, but only on Release mode, works as expected when on Debug mode

### Link to public reproduction project repository

https://github.com/andyx48/GenericsCrashRepro

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15 and up to the latest version

### Did you find any workaround?

No

**Comment by rolfbjarne** [comment]
FWIW I reproduced using @drasticactions's project: https://github.com/drasticactions/MauiRepros/tree/main/GenericCrash, and building it like this:

> dotnet build /p:RuntimeIdentifier=ios-arm64 /p:Configuration=Release /bl GenericCrash.csproj

**Comment by steveisok** [comment]
@vargaz can you please take a look?

**Comment by vargaz** [comment]
I can reproduce.

**Comment by charlesroddie** [comment]
This is the same as https://github.com/dotnet/runtime/issues/97224 in that it involves ios, mono, gc writebarrier, linq average, and decimal.

The one we are getting is vaguely similar but involves, ios, gc, a writing guard exception, and linq. But it's coreclr/nativeaot and no decimal.

**Comment by ivanpovazan** [comment]
FWIW, these were detected as failures on tvos-arm64 runs and relevant tests got disabled in https://github.com/dotnet/runtime/pull/97511 

As @charlesroddie suggested the tracking issue is: https://github.com/dotnet/runtime/issues/97224

**Comment by steveisok** [comment]
@vitek-karas since this was hit in .net 8, it would make sense to backport. What do you think?

**Comment by vitek-karas** [comment]
I agree - especially since it was customer reported. It should be easy to make the case to get this to servicing.
@vargaz could you please backport the fix to 8.0-servicing?
