### ISSUE TITLE
Source generator in System.Text.Json does not handle shadowed members correctly

### ISSUE THREAD

**Issue by garryxiao** [dotnet/runtime#97621]
### Description

C# 12, source generator failed for 'new' or 'override' properties.

### Reproduction Steps

```C#
public record PlaceBase
{
    public string? Region { get; init; }
}
public record PlaceCommon : PlaceBase
{
    public new required string Region { get; init; }
}

[JsonSerializable(typeof(PlaceBase))]
[JsonSerializable(typeof(PlaceCommon))]
public partial class ApiModelJsonSerializerContext : JsonSerializerContext
{
}
```

### Expected behavior

PlaceCommon's 'Region' should be generated with its own Place property and ignore PlaceBase's 'Region' property.

### Actual behavior

Double 'Region' property generated with "Error CS1912 Duplicate initialization of member 'Region‘"

**Comment by garryxiao** [comment]
Luckly there is a intesting way to overcome it, chang the line "public string? Region { get; init; }" to "public string? Region { get; set; }", it works again.

**Comment by eiriktsarpalis** [comment]
Presumably you meant to have `PlaceCommon : PlaceBase`? I can reproduce the issue.

**Comment by garryxiao** [comment]
> Presumably you meant to have `PlaceCommon : PlaceBase`? I can reproduce the issue.

Sorry, Yes. :)

**Comment by eiriktsarpalis** [comment]
> Luckly there is a intesting way to overcome it, chang the line "public string? Region { get; init; }" to "public string? Region { get; set; }", it works again.

Yes, this is related to how `required` and/or `init` properties are being handled by the source generator. Removing either should result in the duplicate code not being generated.
