### ISSUE TITLE
DateTime.ParseExact in .NET8 on Linux fails to parse date strings which were parsed with .NET7

### ISSUE THREAD

**Issue by ajuch** [dotnet/runtime#97627]
### Description

Our test pipeline fails after upgrading the SDK to .NET 8. DateTime.ParseExact fails for the same strings that were successfully parsed in .NET 7. It is easily reproducible with dotnet fsi. Please note that the problem is NOT the missing string in the exception message. The exactly same string is parsed fine with .NET 7 SDK!

### Reproduction Steps

```
let culture = System.Globalization.CultureInfo.GetCultureInfo("en");;
System.DateTime.ParseExact("4/6/2023, 6:14 AM", $"{culture.DateTimeFormat.ShortDatePattern}, {culture.DateTimeFormat.ShortTimePattern}", culture);;
```

For .NET 7 SDK the output is:
```
PS C:\Users\juch.andreas> docker run -it --rm mcr.microsoft.com/dotnet/sdk:7.0
root@e189d30f43fd:/# dotnet fsi

Microsoft (R) F# Interactive version 12.7.403.0 for F# 7.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> let culture = System.Globalization.CultureInfo.GetCultureInfo("en");;
val culture: System.Globalization.CultureInfo = en

> System.DateTime.ParseExact("4/6/2023, 6:14 AM", $"{culture.DateTimeFormat.ShortDatePattern}, {culture.DateTimeFormat.ShortTimePattern}", culture);;
val it: System.DateTime = 04/06/2023 06:14:00 {Date = 04/06/2023 00:00:00;
                                               Day = 6;
                                               DayOfWeek = Thursday;
                                               DayOfYear = 96;
                                               Hour = 6;
                                               Kind = Unspecified;
                                               Microsecond = 0;
                                               Millisecond = 0;
                                               Minute = 14;
                                               Month = 4;
                                               Nanosecond = 0;
                                               Second = 0;
                                               Ticks = 638163584400000000L;
                                               TimeOfDay = 06:14:00;
                                               Year = 2023;}

>
```

With .NET 8 on Windows it also works:
```
PS C:\Users\juch.andreas> dotnet fsi

Microsoft (R) F# Interactive, Version 12.8.0.0 für F# 8.0
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

Um Hilfe zu erhalten, geben Sie "#help;;" ein.

> let culture = System.Globalization.CultureInfo.GetCultureInfo("en");;
val culture: System.Globalization.CultureInfo = en

> System.DateTime.ParseExact("4/6/2023, 6:14 AM", $"{culture.DateTimeFormat.ShortDatePattern}, {culture.DateTimeFormat.ShortTimePattern}", culture);;
val it: System.DateTime = 06.04.2023 06:14:00 {Date = 06.04.2023 00:00:00;
                                               Day = 6;
                                               DayOfWeek = Thursday;
                                               DayOfYear = 96;
                                               Hour = 6;
                                               Kind = Unspecified;
                                               Microsecond = 0;
                                               Millisecond = 0;
                                               Minute = 14;
                                               Month = 4;
                                               Nanosecond = 0;
                                               Second = 0;
                                               Ticks = 638163584400000000L;
                                               TimeOfDay = 06:14:00;
                                               Year = 2023;}

>
```

With .NET8 on Linux (Docker for Windows as well as native Docker on Linux) however, I get an exception.
```
PS C:\Users\juch.andreas> docker run -it --rm mcr.microsoft.com/dotnet/sdk:8.0
root@22da19b2e8e4:/# dotnet fsi

Microsoft (R) F# Interactive version 12.8.0.0 for F# 8.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> let culture = System.Globalization.CultureInfo.GetCultureInfo("en");;
val culture: System.Globalization.CultureInfo = en

> System.DateTime.ParseExact("4/6/2023, 6:14 AM", $"{culture.DateTimeFormat.ShortDatePattern}, {culture.DateTimeFormat.ShortTimePattern}", culture);;
System.FormatException: String '' was not recognized as a valid DateTime.
   at System.DateTime.ParseExact(String s, String format, IFormatProvider provider)
   at <StartupCode$FSI_0003>.$FSI_0003.main@() in /stdin:line 2
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
Stopped due to error
>
```

### Expected behavior

The string should be parsed to a valid DateTime on every platform.

### Actual behavior

An exception is thrown on Linux systems.

### Regression?

Yes it worked in .NET 7

**Comment by huoyaoyuan** [comment]
See #95620. The separator between time and AM/PM for en-US has changed to `\u202`.

If you need to parse datetime value with an invariant format, you should hard code the format string instead. I don't know if `InvariantCulture` is guaranteed to be unchanged.

**Comment by huoyaoyuan** [comment]
The missing message issue is #94837. The fix will be included in upcoming servicing release.

**Comment by huoyaoyuan** [comment]
> If it was consistent over all platforms, it would be fine for me as using a non-breking space here totally makes sense. But the inconsistent behavior in different platforms is annoying and hard to figure out.

I'm agreed with that. Maybe the runtime can provide more information about which ICU version is being used.

> but if my format is depending on the culture I'd have to maintain a format string for every culture.

I'm not sure about your detailed, usage, but culture-aware datetime formatting is for displaying. Parsing it back is an anti-pattern. Invariant formats like `ToString("O")` or `ToString("u")` are better for interchange.

**Comment by tarekgh** [comment]
@ajuch 

- The date/time format for any culture can change at any time. Never assume the culture data is table and never change. Unicode standards keep evolving the culture data. 
- To guarantee date/time parsing you need to use well-known format something like `O`/`R` formats. Or always used Invariant culture which never changes its data. 

> I'm using it for UI testing with playwright and I need to parse the strings shown in the UI.

Do you have control how the data shown in the UI in the first place? If not, then you cannot assume parsing is always going to succeed. In such a scenario, you may use `TryParse` instead of `ParseExact` which may try to do extra heuristics during the parsing but to have parsing to succeed is not guaranteed.  


To know the ICU version used in each case, you may try run code like:

```C#
                foreach (ProcessModule module in Process.GetCurrentProcess().Modules)
                {
                    if (module.FileName.IndexOf("icu", StringComparison.OrdinalIgnoreCase) >= 0)
                        Console.WriteLine($".... {module.FileName}: {module.FileVersionInfo.FileVersion}");
                }
```

**Comment by Clockwork-Muse** [comment]
As a point of interest here - the fact that the parsing failed on upgrading .NET7 to .NET8 is likely a red herring.  It's more likely that (especially if you're using containers in your pipeline) you just have an updated ICU library.  That is, it could fail on .NET7 too.  

> But I'm sure that a constant behavior would have saved me and potentially others a few hours.

No culture-specific data is ever constant.  The other thing you may want to consider when testing localization code is supplying a [psuedolocalization](https://learn.microsoft.com/en-us/globalization/methodology/pseudolocalization).  Testing-specific resource files and custom `CultureInfo` instances with well-known data.

**Comment by ajuch** [comment]
> As a point of interest here - the fact that the parsing failed on upgrading .NET7 to .NET8 is likely a red herring. It's more likely that (especially if you're using containers in your pipeline) you just have an updated ICU library. That is, it could fail on .NET7 too.

Yes, once you know the implementation details, it is clear why this happens. It's also documented here: https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-globalization-cultureinfo

> > But I'm sure that a constant behavior would have saved me and potentially others a few hours.
> 
> No culture-specific data is ever constant. The other thing you may want to consider when testing localization code is supplying a [psuedolocalization](https://learn.microsoft.com/en-us/globalization/methodology/pseudolocalization). Testing-specific resource files and custom `CultureInfo` instances with well-known data.

Sorry, constant is a typo, I meant consistent. The unexpected thing for me was that different OSes return slightly different patterns. If a UI test fails and the failure is unreproducible on my local machine, it gets hard for me to determine the cause.

**Comment by Clockwork-Muse** [comment]
> The unexpected thing for me was that different OSes return slightly different patterns.

heh.

You're not even guaranteed that two different runs on the same machine will return the same result (if the ICU data was updated in between).  Depending on how things are handled, it's maybe possible that two near-concurrently running processes on the same machine could use different data.  Across different machines is just widening the potential failure cases.
Which is why for interchange it's vital to use specific formats or an invariant culture, and for UI testing to create/use pseudo locales.

Note that this includes timezones, which people tend to forget about....
