### ISSUE TITLE
JIT: checked/release diffs

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#97638]
superpmi-asmdiffs-checked-release failed on Saturday and Sunday. Here is Saturday's run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=543147&view=results

The pipeline passed last weekend, so the regression seems to be introduced somewhere in the last week.

cc @dotnet/jit-contrib

**Comment by jakobbotsch** [comment]
I bisected this to #96386, can you please take a look @kunalspathak?

**Comment by kunalspathak** [comment]
> I bisected this to #96386, can you please take a look @kunalspathak?

Will take a look. I wish we can show the diffs in "Extensions" page, similar to we show it in `superpmi-diff` pipeline.
