### ISSUE TITLE
[WASI] Best pattern for Native DLL Pinvokes using wasi workload?

### ISSUE THREAD

**Issue by kkukshtel** [dotnet/runtime#97656]
I've been looking around to try and figure out the best pattern for understanding how to get the WASI workload working with native compiled DLLs and am coming up short on any documentation around if this is or isn't supported and how.

I've got some platform-specific DLLs from C/C++ code that I'd like to invoke from a compiled wasm file, but I'm unsure if this is possible or if I should be instead compiling the C/C++ code to their own wasm modules and using something like wasmtime-dotnet to load them into a host dotnet application that is then itself compiled to wasm?

Would love any sort of guidance or best practices here on how to handle this, especially along the "wasm in dotnet" vs. "dotnet compiled to wasm" boundary.

**Comment by mkhamoyan** [comment]
@kkukshtel To add custom C source files into runtime or to link against unmanaged libraries, you can use `NativeFileReference` or `NativeLibrary`, like done in this sample app https://github.com/dotnet/runtime/blob/efd7ecc92bcd652fa60ea003370a1c0a7d1745b2/src/mono/sample/wasi/native/Wasi.Native.Sample.csproj#L14

For more information, check out the documentation on NativeFileReference [here](https://github.com/dotnet/runtime/blob/5f067ce8b50087e032d13a1b97ae5ec39fc54739/src/mono/wasm/features.md?plain=1#L109) and NativeLibrary [here](https://github.com/dotnet/runtimelab/tree/feature/NativeAOT/samples/NativeLibrary).

**Comment by kkukshtel** [comment]
Just to bump this with some of my own learning and the intent of the question. You don't PInvoke into DLLs with wasm/wasi. Instead, libraries need to be statically compiled into the application itself using NativeFileReference, as indicated by @mkhamoyan above. You can also include files other than c source, with more info in the docs here: [https://learn.microsoft.com/en-us/aspnet/core/blazor/webassembly-native-dependencies?view=aspnetcore-8.0](https://learn.microsoft.com/en-us/aspnet/core/blazor/webassembly-native-dependencies?view=aspnetcore-8.0)

The workflow is to statically compile dependent libs, then compile those directly into the file exe.
