### ISSUE TITLE
TypeLoadException on minimal, correct and compiling program

### ISSUE THREAD

**Issue by cyanite** [dotnet/runtime#97667]
### Description

A small program which compiles under .NET 6-8 and executes correctly on .NET 6-7, crashes on .NET 8 with a TypeLoadException about a failed generic constraint. Manual inspection shows that this constraint is not violated. For us (my company), this is a serious bug, as it completely prevents us from moving to .NET 8.

### Reproduction Steps

Use `dotnet run` on a console program with the following code:

```csharp
var a = new LifSharedVersion<object>();

public interface ILifVersionReadable<TA> {}

public class LifVersion<TVersion, TIVersionReadable>
    where TVersion : TIVersionReadable
{}

public class LifSharedVersion<TSharedVersionData> :
    LifVersion<LifSharedVersion<TSharedVersionData>, ILifSharedVersionReadable<TSharedVersionData>>,
    ILifSharedVersionReadable<TSharedVersionData>
{}

public interface ILifSharedVersionReadable<TSharedVersionData> :
    ILifVersionReadable<LifSharedVersion<TSharedVersionData>>
{}
```

This is a reduction from the bug we found in our code base. It is not immediately possible to reduce the program further, without the error going away.

This crash also occurs when compiling for .NET 6 and using `DOTNET_ROLL_FORWARD=LatestMajor` or similar.

### Expected behavior

The program completes without output.

### Actual behavior

The program crashes with the following exception:

```
Unhandled exception. System.TypeLoadException: GenericArguments[0], 'LifSharedVersion`1[TSharedVersionData]', on 'LifVersion`2[TVersion,TIVersionReadable]' violates the constraint of type parameter 'TVersion'.
   at Program.<Main>$(String[] args)
```

that is, System.TypeLoadException: GenericArguments[0], 'LifSharedVersion\`1[TSharedVersionData]', on 'LifVersion\`2[TVersion,TIVersionReadable]' violates the constraint of type parameter 'TVersion'.

### Regression?

There is no crash on .NET 6 or .NET 7.

### Known Workarounds

Removing anything from the reproduction example removes the problem. However, this reproduction example is a massively reduced version of a very large code base, so we have no easy way to work around this problem in what is supposed to soon be production code.

### Configuration

.NET 8, latest version. Otherwise, nothing special.

**Comment by dioptryk** [comment]
I can confirm this fails under NET 8, previous versions execute it fine. I tried looking into `coreclr/vm/typedesc.cpp`, but found nothing suggesting this kind of breaking change.

**Comment by lambdageek** [comment]
Maybe it's the flag refactoring in https://github.com/dotnet/runtime/pull/89061 - although so far I didn't see anything obviously wrong.

(PS: provided example works properly in Mono)

**Comment by lambdageek** [comment]
FYI @davidwrighton

**Comment by davidwrighton** [comment]
This is fundamentally caused by the performance work done as part of https://github.com/dotnet/runtime/pull/54588  At the time is was not fully realized that the open interface type could still appear as a real instantiation under any circumstance, but with this construction, it becomes possible (as the current code considers the open type to be the same as the type instantiated over its typical arguments) We will need to determine if that is just an incorrect approach, or if we can tweak this in some way to allow this to work.

**Comment by davidwrighton** [comment]
Turns out we found a slight variation on this problem much earlier, but the test case that got written up did not handle the casting or constraint scenarios. See PR #55372

I'm working on extending that fix to be more completely correct.
