### ISSUE TITLE
Assertion failed 'hwintrinsicChild->isContained()' in 'System.Numerics.Tensors.TensorPrimitives+ScaleBOperator

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#97688]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=545442
Build error leg or test failing: System.Numerics.Tensors.Net8.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/97677

## Error Message

```json
{
  "ErrorMessage": "Assertion failed 'hwintrinsicChild->isContained()'",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=545442
**Error message validated:** `Assertion failed 'hwintrinsicChild->isContained()'`
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 1/31/2024 5:13:01 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[548264](https://dev.azure.com/dnceng-public/public/_build/results?buildId=548264)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=548264&view=ms.vss-test-web.build-test-results-tab&runId=13029204&resultId=204890)|dotnet/runtime#96806|
|[548257](https://dev.azure.com/dnceng-public/public/_build/results?buildId=548257)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=548257&view=ms.vss-test-web.build-test-results-tab&runId=13029096&resultId=204961)||
|[548221](https://dev.azure.com/dnceng-public/public/_build/results?buildId=548221)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=548221&view=ms.vss-test-web.build-test-results-tab&runId=13028606&resultId=204961)|dotnet/runtime#97767|
|[548157](https://dev.azure.com/dnceng-public/public/_build/results?buildId=548157)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=548157&view=ms.vss-test-web.build-test-results-tab&runId=13026160&resultId=204961)|dotnet/runtime#97773|
|[548066](https://dev.azure.com/dnceng-public/public/_build/results?buildId=548066)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=548066&view=ms.vss-test-web.build-test-results-tab&runId=13023674&resultId=204961)|dotnet/runtime#97778|
|[547904](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547904)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547904&view=ms.vss-test-web.build-test-results-tab&runId=13023262&resultId=204961)|dotnet/runtime#97740|
|[548008](https://dev.azure.com/dnceng-public/public/_build/results?buildId=548008)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=548008&view=ms.vss-test-web.build-test-results-tab&runId=13021374&resultId=204961)|dotnet/runtime#97664|
|[547961](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547961)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547961&view=ms.vss-test-web.build-test-results-tab&runId=13020544&resultId=204961)|dotnet/runtime#97774|
|[547926](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547926)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547926&view=ms.vss-test-web.build-test-results-tab&runId=13020020&resultId=204961)|dotnet/runtime#97605|
|[547894](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547894)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547894&view=ms.vss-test-web.build-test-results-tab&runId=13019376&resultId=204961)|dotnet/runtime#97216|
|[547683](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547683)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547683&view=ms.vss-test-web.build-test-results-tab&runId=13018612&resultId=204961)|dotnet/runtime#97388|
|[547825](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547825)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547825&view=ms.vss-test-web.build-test-results-tab&runId=13017934&resultId=204961)|dotnet/runtime#97560|
|[547573](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547573)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547573&view=ms.vss-test-web.build-test-results-tab&runId=13017582&resultId=201778)|dotnet/runtime#97763|
|[547779](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547779)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547779&view=ms.vss-test-web.build-test-results-tab&runId=13016414&resultId=204961)|dotnet/runtime#97756|
|[547760](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547760)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547760&view=ms.vss-test-web.build-test-results-tab&runId=13015190&resultId=204961)|dotnet/runtime#97640|
|[547699](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547699)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547699&view=ms.vss-test-web.build-test-results-tab&runId=13013310&resultId=201779)|dotnet/runtime#97767|
|[547672](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547672)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547672&view=ms.vss-test-web.build-test-results-tab&runId=13012534&resultId=201779)|dotnet/runtime#97643|
|[547638](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547638)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547638&view=ms.vss-test-web.build-test-results-tab&runId=13011874&resultId=201778)|dotnet/runtime#97508|
|[547619](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547619)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547619&view=ms.vss-test-web.build-test-results-tab&runId=13011244&resultId=201778)|dotnet/runtime#97766|
|[547521](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547521)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547521&view=ms.vss-test-web.build-test-results-tab&runId=13011192&resultId=201778)|dotnet/runtime#97761|
|[547609](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547609)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547609&view=ms.vss-test-web.build-test-results-tab&runId=13010992&resultId=201778)|dotnet/runtime#97757|
|[547529](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547529)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547529&view=ms.vss-test-web.build-test-results-tab&runId=13008416&resultId=204960)|dotnet/runtime#97759|
|[547360](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547360)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547360&view=ms.vss-test-web.build-test-results-tab&runId=13006634&resultId=204960)|dotnet/runtime#97751|
|[547475](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547475)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547475&view=ms.vss-test-web.build-test-results-tab&runId=13006066&resultId=204960)|dotnet/runtime#97757|
|[547471](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547471)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547471&view=ms.vss-test-web.build-test-results-tab&runId=13006024&resultId=204960)|dotnet/runtime#97756|
|[547240](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547240)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547240&view=ms.vss-test-web.build-test-results-tab&runId=13005952&resultId=204960)|dotnet/runtime#97560|
|[547458](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547458)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547458&view=ms.vss-test-web.build-test-results-tab&runId=13005892&resultId=204960)|dotnet/runtime#97755|
|[547408](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547408)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547408&view=ms.vss-test-web.build-test-results-tab&runId=13005300&resultId=204960)|dotnet/runtime#97754|
|[547335](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547335)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547335&view=ms.vss-test-web.build-test-results-tab&runId=13003126&resultId=204960)|dotnet/runtime#97746|
|[547283](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547283)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547283&view=ms.vss-test-web.build-test-results-tab&runId=13001916&resultId=204960)|dotnet/runtime#97743|
|[547258](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547258)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547258&view=ms.vss-test-web.build-test-results-tab&runId=13001396&resultId=204960)||
|[547227](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547227)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547227&view=ms.vss-test-web.build-test-results-tab&runId=12999678&resultId=204957)||
|[547222](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547222)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547222&view=ms.vss-test-web.build-test-results-tab&runId=12999684&resultId=204961)|dotnet/runtime#97683|
|[547203](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547203)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547203&view=ms.vss-test-web.build-test-results-tab&runId=12999098&resultId=204961)|dotnet/runtime#97590|
|[547014](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547014)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547014&view=ms.vss-test-web.build-test-results-tab&runId=12996366&resultId=204961)|dotnet/runtime#97683|
|[547000](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547000)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=547000&view=ms.vss-test-web.build-test-results-tab&runId=12996210&resultId=201771)|dotnet/runtime#97482|
|[546991](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546991)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546991&view=ms.vss-test-web.build-test-results-tab&runId=12996142&resultId=204960)|dotnet/runtime#97674|
|[546984](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546984)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546984&view=ms.vss-test-web.build-test-results-tab&runId=12995604&resultId=201771)|dotnet/runtime#97605|
|[546906](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546906)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546906&view=ms.vss-test-web.build-test-results-tab&runId=12993510&resultId=204960)|dotnet/runtime#97739|
|[546846](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546846)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546846&view=ms.vss-test-web.build-test-results-tab&runId=12992104&resultId=204970)|dotnet/runtime#97350|
|[546726](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546726)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546726&view=ms.vss-test-web.build-test-results-tab&runId=12987812&resultId=201771)|dotnet/runtime#97694|
|[546685](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546685)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546685&view=ms.vss-test-web.build-test-results-tab&runId=12986066&resultId=204960)|dotnet/runtime#97733|
|[546639](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546639)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546639&view=ms.vss-test-web.build-test-results-tab&runId=12984566&resultId=204960)|dotnet/runtime#97725|
|[546475](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546475)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546475&view=ms.vss-test-web.build-test-results-tab&runId=12984308&resultId=204960)|dotnet/runtime#97643|
|[546582](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546582)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546582&view=ms.vss-test-web.build-test-results-tab&runId=12983064&resultId=204960)|dotnet/runtime#97710|
|[546576](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546576)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546576&view=ms.vss-test-web.build-test-results-tab&runId=12983010&resultId=204960)|dotnet/runtime#97681|
|[546555](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546555)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546555&view=ms.vss-test-web.build-test-results-tab&runId=12982898&resultId=204960)|dotnet/runtime#97675|
|[546485](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546485)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546485&view=ms.vss-test-web.build-test-results-tab&runId=12981650&resultId=204960)|dotnet/runtime#97722|
|[546420](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546420)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546420&view=ms.vss-test-web.build-test-results-tab&runId=12980458&resultId=204960)|dotnet/runtime#97720|
|[546413](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546413)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546413&view=ms.vss-test-web.build-test-results-tab&runId=12980250&resultId=204960)|dotnet/runtime#97724|
|[546196](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546196)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546196&view=ms.vss-test-web.build-test-results-tab&runId=12979384&resultId=204960)|dotnet/runtime#97675|
|[546389](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546389)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546389&view=ms.vss-test-web.build-test-results-tab&runId=12979230&resultId=204960)||
|[546348](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546348)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546348&view=ms.vss-test-web.build-test-results-tab&runId=12978372&resultId=204960)|dotnet/runtime#96707|
|[546294](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546294)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546294&view=ms.vss-test-web.build-test-results-tab&runId=12976046&resultId=204960)|dotnet/runtime#97182|
|[546239](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546239)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546239&view=ms.vss-test-web.build-test-results-tab&runId=12975046&resultId=204960)|dotnet/runtime#97482|
|[546220](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546220)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546220&view=ms.vss-test-web.build-test-results-tab&runId=12974558&resultId=204960)|dotnet/runtime#97415|
|[546178](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546178)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546178&view=ms.vss-test-web.build-test-results-tab&runId=12973118&resultId=204952)|dotnet/runtime#97713|
|[546163](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546163)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546163&view=ms.vss-test-web.build-test-results-tab&runId=12972814&resultId=204952)|dotnet/runtime#97710|
|[545972](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545972)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545972&view=ms.vss-test-web.build-test-results-tab&runId=12971674&resultId=204952)|dotnet/runtime#96650|
|[546114](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546114)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546114&view=ms.vss-test-web.build-test-results-tab&runId=12971316&resultId=204952)|dotnet/runtime#97052|
|[546109](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546109)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546109&view=ms.vss-test-web.build-test-results-tab&runId=12971284&resultId=204952)|dotnet/runtime#97052|
|[546073](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546073)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546073&view=ms.vss-test-web.build-test-results-tab&runId=12970050&resultId=204952)|dotnet/runtime#97705|
|[546035](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546035)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546035&view=ms.vss-test-web.build-test-results-tab&runId=12968842&resultId=204952)|dotnet/runtime#97699|
|[546024](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546024)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=546024&view=ms.vss-test-web.build-test-results-tab&runId=12968708&resultId=204952)|dotnet/runtime#97640|
|[545957](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545957)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545957&view=ms.vss-test-web.build-test-results-tab&runId=12968290&resultId=204952)|dotnet/runtime#97388|
|[545908](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545908)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545908&view=ms.vss-test-web.build-test-results-tab&runId=12966004&resultId=201763)|dotnet/runtime#97508|
|[545898](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545898)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545898&view=ms.vss-test-web.build-test-results-tab&runId=12965914&resultId=201763)|dotnet/runtime#96941|
|[545890](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545890)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545890&view=ms.vss-test-web.build-test-results-tab&runId=12965522&resultId=201763)|dotnet/runtime#97696|
|[545844](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545844)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545844&view=ms.vss-test-web.build-test-results-tab&runId=12963756&resultId=201763)|dotnet/runtime#97694|
|[545813](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545813)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545813&view=ms.vss-test-web.build-test-results-tab&runId=12962720&resultId=201763)|dotnet/runtime#97052|
|[545808](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545808)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545808&view=ms.vss-test-web.build-test-results-tab&runId=12962514&resultId=201763)|dotnet/runtime#97052|
|[545781](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545781)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545781&view=ms.vss-test-web.build-test-results-tab&runId=12961208&resultId=201763)|dotnet/runtime#97216|
|[2365483](https://dev.azure.com/dnceng/internal/_build/results?buildId=2365483)|dotnet-runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2365483&view=ms.vss-test-web.build-test-results-tab&runId=52974283&resultId=204937)||
|[545581](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545581)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545581&view=ms.vss-test-web.build-test-results-tab&runId=12957314&resultId=204939)|dotnet/runtime#97216|
|[545558](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545558)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545558&view=ms.vss-test-web.build-test-results-tab&runId=12955844&resultId=204939)||
|[545521](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545521)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545521&view=ms.vss-test-web.build-test-results-tab&runId=12954750&resultId=204939)|dotnet/runtime#97686|
|[545514](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545514)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545514&view=ms.vss-test-web.build-test-results-tab&runId=12954200&resultId=204937)||
|[545504](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545504)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545504&view=ms.vss-test-web.build-test-results-tab&runId=12954128&resultId=204939)|dotnet/runtime#97685|
|[545497](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545497)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545497&view=ms.vss-test-web.build-test-results-tab&runId=12953938&resultId=204939)|dotnet/runtime#97675|
|[545493](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545493)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545493&view=ms.vss-test-web.build-test-results-tab&runId=12953824&resultId=204939)|dotnet/runtime#97684|
|[545442](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545442)|dotnet/runtime|[System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545442&view=ms.vss-test-web.build-test-results-tab&runId=12951718&resultId=204939)|dotnet/runtime#97677|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|47|81|81|

**Comment by AndyAyersMS** [comment]
FYI @dotnet/jit-contrib

**Comment by jakobbotsch** [comment]
I can't repro this locally so probably requires AVX512. @tannergooding @EgorBo any chance one of you could take a look since this is blocking innerloop?

**Comment by tannergooding** [comment]
Will take a look. Worth noting, however, that AltJit should allow you to test AVX512 codegen even if you can't execute it

**Comment by tannergooding** [comment]
Fix should be here: https://github.com/dotnet/runtime/pull/97783
