### ISSUE TITLE
Support adding links to Activity after it is created

### ISSUE THREAD

**Issue by vishweshbankwar** [dotnet/runtime#97680]
OpenTelemetry has added [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#link) for supporting link addition to spans after the span is created. PR marking spec as stable - https://github.com/open-telemetry/opentelemetry-specification/pull/3887.

 This is currently not possible in .NET. Links can only be added when the activity is being created see [this](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activitysource.createactivity?view=net-8.0#system-diagnostics-activitysource-createactivity(system-string-system-diagnostics-activitykind-system-string-system-collections-generic-ienumerable((system-collections-generic-keyvaluepair((system-string-system-object))))-system-collections-generic-ienumerable((system-diagnostics-activitylink))-system-diagnostics-activityidformat))

Opening the issue for tracking as supporting this new feature would require addition of new API in System.Diagnostics.DiagnosticSource.

### API Proposal

```C#
namespace System.Diagnostics
{
    public partial class Activity : IDisposable
    {
        public System.Diagnostics.Activity AddLink(System.Diagnostics.ActivityLink link);
    }
}
```

**Comment by tarekgh** [comment]
@vishweshbankwar I have marked this for future release till we get the OTel stable and then we can bring it back to current release as needed.

**Comment by hahn-kev** [comment]
I'm also interested in this, there's a library that I'd like to enrich an activity with a link but I can't since it's already been created.

**Comment by martinjt** [comment]
@tarekgh this has now been marked stable in the spec.

https://github.com/open-telemetry/opentelemetry-specification/pull/3887

**Comment by tarekgh** [comment]
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#link

@vishweshbankwar could you please add the API proposal on the top? I guess this will be a simple like `Activity.AddLink(ActivityLike link)`

**Comment by vishweshbankwar** [comment]
> https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#link
> 
> @vishweshbankwar could you please add the API proposal on the top? I guess this will be a simple like `Activity.AddLink(ActivityLike link)`

@tarekgh Added.

**Comment by antonfirsov** [comment]
```csharp
System.Diagnostics.Activity AddLink(System.Diagnostics.ActivityLink link);
```

Do we really need `AddLink` to create & return an activity? Would this cover all activity creation concerns? [`ActivitySource.CreateActivity`](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activitysource.createactivity?view=net-8.0) has multiple overloads with many args.

**Comment by vishweshbankwar** [comment]
> ```cs
> System.Diagnostics.Activity AddLink(System.Diagnostics.ActivityLink link);
> ```
> 
> Do we really need `AddLink` to create & return an activity? Would this cover all activity creation concerns? [`ActivitySource.CreateActivity`](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activitysource.createactivity?view=net-8.0) has multiple overloads with many args.

@antonfirsov - The proposal is consistent with how the current Add* extensions work

e.g. https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activity.addevent?view=net-8.0

**Comment by antonfirsov** [comment]
Ok, missed that Activity has fluent APIs.

Anything preventing us from marking this `api-ready-for-review`? It is a prerequisite for an optimal implementation of #93832, so it would be nice to have a review scheduled soonish.

**Comment by bartonjs** [comment]
* We generally don't do the fluent pattern, but that's consistent with the type already.
* So, looks good as proposed.

```c#
namespace System.Diagnostics
{
    public partial class Activity
    {
        public System.Diagnostics.Activity AddLink(System.Diagnostics.ActivityLink link);
    }
}
```
