### ISSUE TITLE
The SocketsHttpHandler cannot authenticate NTLM with the username format domain\samAccountName

### ISSUE THREAD

**Issue by vinhdp195** [dotnet/runtime#97691]
### Description

I have previously posted a similar issue here:  https://github.com/dotnet/runtime/issues/94303
However, authentication with UPN (user@domain.com) is not possible in that case.

This issue can be resolved by upgrading to .NET 8 and setting the UseManagedNtlm property to TRUE. 
However, with UseManagedNtlm set to TRUE, authentication with the username format domain\samAccountName is currently not possible. 
Authentication is successful only if UseManagedNtlm is not set to TRUE.

### Reproduction Steps

Environment:
Currently running on iOS devices with version 15/16 (iPhone/iPad).
Visual Studio 2022 version 17.8.5
Xcode 15.2

Project sample:
https://github.com/vinhdp195/HttpRequestSample

Code sample:
https://github.com/vinhdp195/HttpRequestSample/blob/main/MauiApp1/MainPage.xaml.cs

### Expected behavior

The SocketsHttpHandler cannot authenticate NTLM with the username format domain\samAccountName

### Actual behavior

The SocketsHttpHandler can authenticate NTLM with the username format domain\samAccountName

**Comment by karelz** [comment]
FYI @filipnavara

**Comment by filipnavara** [comment]
It should work if you specify the user name and domain name as separate parameters to the `NetworkCredential` constructor.

**Comment by vinhdp195** [comment]
@filipnavara 
Thank you for your response. I understand the solution.

However, I would like to know the reason why there is no error when the UseManagedNtlm property is not configured. Is this a library issue when using UseManagedNtlm correctly?

**Comment by filipnavara** [comment]
On Unix-like systems, in GSSAPI, the user name and domain is passed as single string to the `gss_import_name` API (with `GSS_C_NT_USER_NAME` type). There is a conversion between the two formats [here](
https://github.com/dotnet/runtime/blob/cd460dbda99c080b9f9ec1cbdcd233f25ba8c189/src/libraries/System.Net.Security/src/System/Net/NegotiateAuthenticationPal.Unix.cs#L483-L505) and it extracts the domain from the `DOMAIN\name` format.

On Windows, it is [not done though](https://github.com/dotnet/runtime/blob/cd460dbda99c080b9f9ec1cbdcd233f25ba8c189/src/libraries/System.Net.Security/src/System/Net/NegotiateAuthenticationPal.Windows.cs#L681-L683).

I agree it seems inconsistent. I'm not sure if Windows does any conversion in the API internally.

**Comment by rzikm** [comment]
Closing as answered, if there are any more problems, feel free to open another issue.
