### ISSUE TITLE
Jump into Try/Catch Region

### ISSUE THREAD

**Issue by mariam-abdulla** [dotnet/runtime#97693]
Hello,

I would like to ask if it's possible to have a jump into a try/catch region.
I have tried the logic below but I'm getting a compiler error: **No such label 'label' within the scope of the goto statement**.
Is there any way I can generate such a logic?

```
        public void Example()
        {
            int i = 1;
            goto Somewhere;

            ThrowMethod();
            try
            {
                int j = 1;
                Somewhere:
                int k = 1;
                ThrowMethod();
            }
            catch
            {
                DoesNotThrow();
            }
        }
```

Thank you!

**Comment by SingleAccretion** [comment]
No, it is not possible to enter a `try` from outside the first block (broadly speaking). You can introduce a condition variable to work around this:
```cs
public void Example()
{
    bool flag = false;

    if (some_condition)
    {
        flag = true;
        goto TryStart;
    }

    ThrowMethod();
TryStart:
    try
    {
        if (flag)
        {
            goto Somewhere;
        }
        int j = 1;

    Somewhere:
        int k = 1;
        ThrowMethod();
    }
    catch
    {
        DoesNotThrow();
    }
}
```
Obviously, such a construct has suboptimal readability characteristics at best.

**Comment by jakubch1** [comment]
@SingleAccretion is it somehow assured by ECMA rules that you always need to go through first instruction of try to be inside try block?

**Comment by teo-tsirpanis** [comment]
This is codified in section I.12.4.2.8.2.7 of ECMA-335:

> If the source of the branch is within a protected block, filter, or handler, the target(s) shall be within the same protected block, filter, or handler

> If any target of the branch is within a protected block, except the first instruction of that protected block, the source shall be within the same protected block.

> If any target of the branch is within a filter or handler, the source shall be within the same filter or handler.
