### ISSUE TITLE
[mono] remove runtime support for cominterop

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#97703]
It's just dead code now: we never enable mono's built-in COM support on any configuration.  If there's a need to support COM with Mono, we should instead focus on the COM interop generator.

In particular, we should delete code like:
```c
  if (MONO_CLASS_IS_IMPORT(...)) {
   // COM stuff
   ...
  }
```
and
```c
#ifndef DISABLE_COM
// other COM stuff
#endif
```

**Comment by jkoritzinsky** [comment]
I'll take a look into this today.
