### ISSUE TITLE
UdpClient don't receive packets (Mac OS)

### ISSUE THREAD

**Issue by fabio-stein** [dotnet/runtime#97718]
### Description

Hello, I have been trying to develop a UDP server to receive packets with .NET, I tried to use UdpClient in many different ways, I can only send packets but never receive.

The code I'm running now is from the example at https://learn.microsoft.com/en-us/dotnet/framework/network-programming/using-udp-services

```csharp
using System;
using System.Net;
using System.Net.Sockets;
using System.Text;

public class UDPListener
{
    private const int listenPort = 11000;

    private static void StartListener()
    {
        UdpClient listener = new UdpClient(listenPort);
        IPEndPoint groupEP = new IPEndPoint(IPAddress.Any, listenPort);

        try
        {
            while (true)
            {
                Console.WriteLine("Waiting for broadcast");
                byte[] bytes = listener.Receive(ref groupEP);

                Console.WriteLine($"Received broadcast from {groupEP} :");
                Console.WriteLine($" {Encoding.ASCII.GetString(bytes, 0, bytes.Length)}");
            }
        }
        catch (SocketException e)
        {
            Console.WriteLine(e);
        }
        finally
        {
            listener.Close();
        }
    }

    public static void Main()
    {
        StartListener();
    }
}
```

Important Note:
The problem only happen when I send a UDP package from another device on my network such as my phone UDP test app to my Computer. If I send locally from my computer to itself, then it receives successfully.

- I tried to add the compiled executable to firewall rules
- I tried to execute as admin (sudo app....)

I didn't tested on other OS

## How do I know the package is arriving at computer but not on .NET?
I did tried to use **socat** as an alternative to .NET code for testing, and socat easily receives the UDP packet
```
socat - UDP-LISTEN:5000
```

I can also see the packet on wireshark:

<img width="1321" alt="image" src="https://github.com/dotnet/core/assets/12297337/bb2c59d1-d41c-48a7-bd56-4307db111ec4">

### Configuration

Which version of .NET is the code running on?
- 6.0.202
- 8.0.101 tested on both

What OS and version, and for Linux, what distro?
- Mac OS Sonoma 14.2.1

What is the architecture (x64, x86, ARM, ARM64)?
- ARM64

**Comment by wfurt** [comment]
I cannot reproduce you results (with 8.0) @fabio-stein. 
Testing with `socat` as well from Linux machine:
```
 echo aa | socat -u - udp-datagram:255.255.255.255:11000,broadcast,reuseaddr
```

my MacBook running 13.6.4:

```
Shining:udp furt$ dotnet run
Waiting for broadcast
Received broadcast from 10.211.55.5:38004 :
 aa

Waiting for broadcast
```


I also tried directed broadcast (10.211.55.255 in my case) and unicast. And I'm able to receive the message in all cases.
Perhaps check firewall or any other security software. I'm not sure why `socat` from command line would be any different but it may be with of try. You should also see your socket with `netstats -an`. Also make sure there is nothing else (like old instance) eating your packets. 

Wireshark _is_ different as it graces packet from interface in promiscuous mode. Still useful to see that the packet are sent.   


Note that `UdpClient` is not that great IMHO. If you can, I would suggest use `Socket` directly to avoid indirections. 
It should not matter for this particular case but it still may be better choice for anything serious.

**Comment by fabio-stein** [comment]
After few more tests I got some new test cases.

**Yes**, it seems to be related to firewall.

- If I turn firewall off, restart machine, then it works as expected
- With firewall on, I didn't figured out how to fix it

I tried many different settings on firewall and didn't get success.
- Tried publishing entire program into single file self contained, then add that file to firewall whitelist
- Tried to add terminal, IDE, dotnet to firewall.
- Tested TcpClient/TcpListener and have same failed results.

For comparison, there is an interesting example
I have installed the npm http-server, when I simply run the command **http-server**, it prompts me to allow firewall for that program

<img width="808" alt="image" src="https://github.com/dotnet/runtime/assets/12297337/74367aca-1e6f-4416-9be8-7e626dc08879">

I think that having a similar process for the .NET app would probably fix the issue. Is there anything I can do to "trigger" that action fot .NET? Or any suggestion for firewall tests

**Comment by wfurt** [comment]
I don't know if they (could) do that for UDP.  TCP has clear handshake while somebody can flood you with UDP. 

https://support.apple.com/guide/mac-help/change-firewall-settings-on-mac-mh11783/mac does not look that interesting, but https://apple.stackexchange.com/questions/360491/mac-os-x-firewall-rules-to-block-udp-connection-to-an-external-server suggest you can add rules manually. You may need to study the syntax a little bit but it goes beyond .NET.

**Comment by fabio-stein** [comment]
Ok, thanks for the support, I'll close this issue since it's too specific to Mac firewall and is outside the scope of .NET
