### ISSUE TITLE
Massive performance downgrade when using latest .NET 8 linux runtime image caused by libssl3

### ISSUE THREAD

**Issue by adomass** [dotnet/runtime#97727]
We are running our workloads on AWS ECS Fargate linux containers.
After migrating to .net 8 we have experienced very high cpu usage and slow responses. 

We use [AmazonCloudfrontUrlSigner](https://github.com/aws/aws-sdk-net/blob/d5ec588535f39d2dad37a91eac9ee465672e7335/sdk/src/Services/CloudFront/Custom/AmazonCloudFrontUrlSigner.cs#L266)
This library uses System.Security.Cryptography that calls native openssl libraries.
In dotnet 7 base images there was libssl1.1 used. But [.net 8](https://github.com/dotnet/dotnet-docker/blob/2a1898ab514a234625386591ee63b7b25736c6f4/src/runtime-deps/8.0/bookworm-slim/amd64/Dockerfile) uses libssl3

There are big performance issues with openssl3.0
https://github.com/openssl/openssl/issues/15199
https://github.com/openssl/openssl/issues/17064

This makes impossible to use .net 8 base images with heavy load. In our case bottleneck seems to be going via [this ](https://github.com/dotnet/runtime/blob/b76ef7fa73c758daaa663a4d36d78d536df152fe/src/native/libs/System.Security.Cryptography.Native/pal_evp_pkey.c#L161) method call.
Is there any solution to this? Perhaps it would be possible to switch to openssl1.1 before the issues are fixed on openssl?

Here is what we capture from dotTrace using .net 8
![image](https://github.com/dotnet/runtime/assets/4628301/73e93654-3779-4275-9e54-ff5897b91bc4)

Running same performance test on same instance same code using .net 7
![image](https://github.com/dotnet/runtime/assets/4628301/81169072-d11e-45a1-be89-4fa6279de9c1)

**Comment by vcsjones** [comment]
I think I can make the importing RSAParameters quicker, so I'll take a look at that.

**Comment by adomass** [comment]
> I think I can make the importing RSAParameters quicker, so I'll take a look at that.

Without using openssl? I thought the culprit is openssl installed in linux base image.

**Comment by vcsjones** [comment]
> Without using openssl? 

We are using two OpenSSL APIs for importing the key, `d2i_PKCS8_PRIV_KEY_INFO` and `EVP_PKCS82PKEY`. These two APIs were hit particularly hard in the OpenSSL 1.1 to 3.0 move performance-wise.

There are other APIs that, I suspect, will have better performance under OpenSSL 3. In particular, `EVP_PKEY_CTX_new_from_name` and `EVP_PKEY_CTX_set_params`. These would be better suited for an RSAParameters used in `ImportParameters` which is your hot path. I haven't confirmed whether the performance change is significant, but avoiding all of the ASN.1 processing should help.

**Comment by adomass** [comment]
> > Without using openssl?
> 
> We are using two OpenSSL APIs for importing the key, `d2i_PKCS8_PRIV_KEY_INFO` and `EVP_PKCS82PKEY`. These two APIs were hit particularly hard in the OpenSSL 1.1 to 3.0 move performance-wise.
> 
> There are other APIs that, I suspect, will have better performance under OpenSSL 3. In particular, `EVP_PKEY_CTX_new_from_name` and `EVP_PKEY_CTX_set_params`. These would be better suited for an RSAParameters used in `ImportParameters` which is your hot path. I haven't confirmed whether the performance change is significant, but avoiding all of the ASN.1 processing should help.

Ok. Lets give it a try. But I am wondering if it doesn't help perhaps it would be possible to create dotnet8 runtime with libssl1.1 and escalate the issue to openssl. Seems like its not fixed for many years.

**Comment by vcsjones** [comment]
> possible to create dotnet8 runtime image with libssl1.1 and escalate the issue to openssl

OpenSSL 1.1.1 is end of life.

https://www.openssl.org/blog/blog/2023/09/11/eol-111/index.html

**Comment by adomass** [comment]
> > possible to create dotnet8 runtime image with libssl1.1 and escalate the issue to openssl
> 
> OpenSSL 1.1.1 is end of life.
> 
> https://www.openssl.org/blog/blog/2023/09/11/eol-111/index.html

I know, but I also don't see any other solution. I hope your changes will help! Perhaps there are fixes in latest openssl version. I saw that the one used in dotnet 8 bookworm-slim base image is not the latest one?
![image](https://github.com/dotnet/runtime/assets/4628301/6f1a1a4a-5f4b-4502-a191-e745bbe71c55)

**Comment by adomass** [comment]
> > > possible to create dotnet8 runtime image with libssl1.1 and escalate the issue to openssl
> > 
> > 
> > OpenSSL 1.1.1 is end of life.
> > https://www.openssl.org/blog/blog/2023/09/11/eol-111/index.html
> 
> I know, but I also don't see any other solution. I hope your changes will help! Perhaps there are fixes in latest openssl version. I saw that the one used in dotnet 8 bookworm-slim base image is not the latest one? ![image](https://private-user-images.githubusercontent.com/4628301/300980397-82d9521f-d21b-4fd3-b286-161428cfbfbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NTQ5MzgsIm5iZiI6MTcwNjY1NDYzOCwicGF0aCI6Ii80NjI4MzAxLzMwMDk4MDM5Ny04MmQ5NTIxZi1kMjFiLTRmZDMtYjI4Ni0xNjE0MjhjZmJmYmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzBUMjI0MzU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTYwNzQyNjJiNWQ2YTU3Zjc5MDUyNjYxNzMwY2UwZTkyMjUyNDM0OTA1YjE3YjUwNmY0ODNiNDBhN2Y0YThlNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rW6EFNQxCu00l0bXdr4r24Rotkg9KyvY4KKekK6wZAM)
> 
> There quite some performance fixes in the release notes https://www.openssl.org/news/cl32.txt

Just checked https://packages.qa.debian.org/o/openssl.html and seems to be the latest stable version

**Comment by vcsjones** [comment]
You may want to also open an issue with the AWS SDK. Looking at this code:

https://github.com/aws/aws-sdk-net/blob/d5ec588535f39d2dad37a91eac9ee465672e7335/sdk/src/Services/CloudFront/Custom/AmazonCloudFrontUrlSigner.cs#L529-L531

```C#
var rsa = RSA.Create();
rsa.ImportParameters(rsaParams);
return rsaParams;
```

They import the parameters into an RSA object then throw it away. If I had to guess they are doing this to validate the parameters. But then they just import it again here:

https://github.com/aws/aws-sdk-net/blob/d5ec588535f39d2dad37a91eac9ee465672e7335/sdk/src/Services/CloudFront/Custom/AmazonCloudFrontUrlSigner.cs#L510

They essentially calling `ImportParameters` twice for every key.

**Comment by adomass** [comment]
> You may want to also open an issue with the AWS SDK. Looking at this code:
> 
> https://github.com/aws/aws-sdk-net/blob/d5ec588535f39d2dad37a91eac9ee465672e7335/sdk/src/Services/CloudFront/Custom/AmazonCloudFrontUrlSigner.cs#L529-L531
> 
> ```cs
> var rsa = RSA.Create();
> rsa.ImportParameters(rsaParams);
> return rsaParams;
> ```
> 
> They import the parameters into an RSA object then throw it away. If I had to guess they are doing this to validate the parameters. But then they just import it again here:
> 
> https://github.com/aws/aws-sdk-net/blob/d5ec588535f39d2dad37a91eac9ee465672e7335/sdk/src/Services/CloudFront/Custom/AmazonCloudFrontUrlSigner.cs#L510
> 
> They essentially calling `ImportParameters` twice for every key.

Ok I will create an issue on their side. Yes you I right i saw that in profiling trace as well that its called twice.

**Comment by vcsjones** [comment]
Analysis shows that the majority of the performance change is due to `EVP_PKEY_check` which got slower in OpenSSL 3.

Benchmark of `EVP_PKEY_check`:

| Version | Time (seconds) | Key Size (bits) |
|--------|--------|--------|
| OpenSSL 1.1.1w | 0.003178 | 2048 |
| OpenSSL 1.1.1w | 0.014472 | 4096 |
| OpenSSL 3.2.0 | 0.036450 | 2048 |
| OpenSSL 3.2.0 | 0.219848 | 4096 | 

Which is where the bulk of the time is spent when importing an RSA key. This results in a 10x to 20x slow down when importing a key.

Work is underway to remove our dependency on `EVP_PKEY_check` for RSA. Other key algorithms will continue to use the OpenSSL method. ECDSA in particular does not appear to be as strongly impacted.

**Comment by NotTsunami** [comment]
> Analysis shows that the majority of the performance change is due to `EVP_PKEY_check` which got slower in OpenSSL 3.
> 
> Benchmark of `EVP_PKEY_check`:
> 
> Version	Time (seconds)	Key Size (bits)
> OpenSSL 1.1.1w	0.003178	2048
> OpenSSL 1.1.1w	0.014472	4096
> OpenSSL 3.2.0	0.036450	2048
> OpenSSL 3.2.0	0.219848	4096
> Which is where the bulk of the time is spent when importing an RSA key. This results in a 10x to 20x slow down when importing a key.
> 
> Work is underway to remove our dependency on `EVP_PKEY_check` for RSA. Other key algorithms will continue to use the OpenSSL method. ECDSA in particular does not appear to be as strongly impacted.

Thanks for this. What are the chances of seeing this get backported to 8.x?

**Comment by vcsjones** [comment]
Re-opening while we make a decision about back porting.

**Comment by bartonjs** [comment]
This will be part of the 8.0.3 release as PR https://github.com/dotnet/runtime/pull/98010.  Since there's no further action to take, I'm closing the issue again.
