### ISSUE TITLE
.NET hangs for an unknown reason

### ISSUE THREAD

**Issue by Khhs167** [dotnet/runtime#97731]
### Describe the bug
For whatever reason, sometimes .net hangs when trying to access a large pool of memory.  
Why this happens is a mystery and I've been trying to figure out the crash. Hence I'll include
a number of things that more or less create the same issue.

### To Reproduce

Here is the main shared code between the two issues:
https://gist.github.com/Khhs167/93048c7e66488390c48a4ce1d7a37252  
it is a simple content loading system.

The current code(which hangs) is
https://gist.github.com/Khhs167/a1019fbb0709d64f1bdcfbd208dde4f8

And the other one is simply converting the byte[] to a string, splitting that at '\n' and iterating
with a foreach loop. this also hangs 

### Exceptions (if any)

It *does* exit with code 139

### Further technical details
dotnet --info
```
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.102/

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  6.0.113 [/usr/share/dotnet/sdk]
  7.0.102 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.NETCore.App 6.0.13 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/share/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

IDE: Rider, but just `dotnet run` also has the same issue

**Comment by adamsitnik** [comment]
> It does exit with code 139

Your program tried to access a memory location it had no permissions to access, so the operating system killed it.

The provided code is not enough to repo it and find the reason. Could you please provide a standalone repro app?

**Comment by Khhs167** [comment]
I tried replicating the issue using whatever code scraps I could find, but sadly to no avail.

I feel like the cause of this issue might not be possible to replicate, sadly.

**Comment by adamsitnik** [comment]
> I tried replicating the issue using whatever code scraps I could find, but sadly to no avail.

> I feel like the cause of this issue might not be possible to replicate, sadly.

@Khhs167 in such case we have two options:

1. You can attach a debugger to the hang process and check which thread is performing the blocking call.
2. You can capture a memory dump from the process that exited with 139 and analyze it or share with MS and we may identify the issue.

**Comment by adamsitnik** [comment]
No input from the author for a few months, closing.
