### ISSUE TITLE
[NativeAOT] xcode15+ linker issue

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#97745]
There is a chance that this is something with my machine, but it looks like I cannot build run tests with 8.0
It could be related to xcode 15+ 

I have 15.2 and tried downgrade to 15.0 with the same result. It does not seem possible to downgrade further as older versions claim to be incompatible with the new OS.

I am using the following command: 

`/build.sh clr.alljits+clr.tools+clr.nativeaotlibs+clr.nativeaotruntime+libs -rc Release -lc Release ; src/tests/build.sh nativeaot Release 'tree nativeaot' ; src/tests/run.sh --runnativeaottests Release`

That works fine on `main` branch (product and tests build and tests pass).
But on `release/8.0` branch I get a bunch of errors like:

/Users/vs/Hosting01/runtime/artifacts/bin/coreclr/osx.arm64.Release/build/Microsoft.NETCore.Native.targets(308,5): error MSB3073: The command ""/Users/vs/Hosting01/runtime/artifacts/bin/coreclr/osx.arm64.Release/ilc-published/ilc" @"/Users/vs/Hosting01/runtime/artifacts/tests/coreclr/obj/osx.arm64.Release/Managed/nativeaot/SmokeTests/StackTraceMetadata/StackTraceMetadata_Stripped/native/StackTraceMetadata_Stripped.ilc.rsp"" exited with code 139.

**Comment by VSadov** [comment]
@filipnavara - could this be another linker issue similar to https://github.com/dotnet/runtime/pull/92520? 
Or maybe even the same issue, just showing up in a different way?

**Comment by MichalStrehovsky** [comment]
```
The command "".../ilc" @"..,/StackTraceMetadata_Stripped.ilc.rsp"" exited with code 139.
```

This is ILC crashing. One option to troubleshoot would be just to re-run this line under a debugger.

**Comment by VSadov** [comment]
Passing `-ld64` to ILC build and to the `Microsoft.NETCore.Native.Unix.targets` fixes the problem the ILC is functional can build tests and tests pass.

This does seem to be some kind of incompatibility with the new linker.

**Comment by filipnavara** [comment]
> could this be another linker issue similar to #92520?

Generally speaking, yes. I won’t have time to look into it until next week, unfortunately.

**Comment by VSadov** [comment]
I think nothing is blocked on this yet, so this is mostly a heads up.
Since the lab uses xcode14, it is not affected. Also I am unsure if xcode15+ is a supported end user configuration for 8.0. Since the lab is still on 14, probably not yet.

**Comment by VSadov** [comment]
> Yes, it is supported. Prerequisites in our documentation do not ask for a specific old XCode version.

That is desirable, but practically it is hard to guarantee support for something newer than what the lab runs. 
That said, moving to new xcode has been mostly uneventful in the past. It is just v15 brings a new linker with a bunch of incompatibilities. I would not rule out that some of those incompatibilities are unintentional and basically bugs that may eventually be fixed. 

Maybe the right course of action for 8.0 is to use `-ld_classic` until all that becomes more stable?

**Comment by jkotas** [comment]
> it is hard to guarantee support for something newer than what the lab runs

Yes, we have same problem for support of new OS versions. We take fixes for these types of issues in servicing.

**Comment by filipnavara** [comment]
Nevermind, there is definitely something broken even on `main` with the new linker. I updated to Xcode 15.2 and I get crash in `nativeaot/SmokeTests/FrameworkStrings/Baseline` test at the end. Relinking with `-ld_classic` and no other changes makes it go away. I'll investigate next week.

**Comment by filipnavara** [comment]
The issue I get in the `Baseline` test is trashed SP after a caught exception (before: `0x000000016fdff1a0`; after: `0x00000001814790e0`). The unwinding information may be corrupted.

**Comment by filipnavara** [comment]
So far I traced it to `UnwindHelpers::GetUnwindProcInfo` returning bogus info belonging to a different method than asked for. The unwinding data itself in the executable is likely fine. I did a spot check on it, and `lldb` unwinds the same stack trace just fine.

**Comment by filipnavara** [comment]
So, the linker indeed produces garbage unwind tables (as verified by `objdump -u`):
```
    Second level index[6]: offset in section=0x0000a3f8, base function offset=0x000f55f0
      [0]: function offset=0x000f55f0, encoding=0x44000000
      [1]: function offset=0x000f5640, encoding=0x03011500
      [2]: function offset=0x000f56f0, encoding=0x03011528
      [3]: function offset=0x000f5740, encoding=0x0301154c
...
      [106]: function offset=0x000f92d0, encoding=0x03011e00
      [107]: function offset=0x000f9320, encoding=0x03011e24
      [108]: function offset=0x0018a5c8, encoding=0x00000000
      [109]: function offset=0x000f93e0, encoding=0x03011e4c
      [110]: function offset=0x0018a608, encoding=0x00000000
      [111]: function offset=0x000f9440, encoding=0x03011e70
      [112]: function offset=0x0018a668, encoding=0x00000000
      [113]: function offset=0x000f94c0, encoding=0x03011e94
      [114]: function offset=0x0018a6e8, encoding=0x00000000
      [115]: function offset=0x000f9580, encoding=0x03011eb8
      [116]: function offset=0x0018a7a8, encoding=0x00000000
      [117]: function offset=0x000f9620, encoding=0x03011ee0
      [118]: function offset=0x0018a848, encoding=0x00000000
      [119]: function offset=0x000f96b0, encoding=0x44000000
      [120]: function offset=0x0018a8d8, encoding=0x00000000
      [121]: function offset=0x000f96e0, encoding=0x44000000
      [122]: function offset=0x0018a908, encoding=0x00000000
      [123]: function offset=0x000f9710, encoding=0x44000000
      [124]: function offset=0x0018a938, encoding=0x00000000
      [125]: function offset=0x000f9740, encoding=0x44000000
      [126]: function offset=0x0018a968, encoding=0x00000000
      [127]: function offset=0x000f9790, encoding=0x44000000
      [128]: function offset=0x0018a9b8, encoding=0x00000000
      [129]: function offset=0x000f97b0, encoding=0x03011f04
      [130]: function offset=0x0018a9d8, encoding=0x00000000
      [131]: function offset=0x000f9960, encoding=0x03011f30
      [132]: function offset=0x0018ab88, encoding=0x00000000
…
```

The function offsets are supposed to be sorted.

**Comment by filipnavara** [comment]
Feedback sent to Apple. For reference, here's the repro with files and a `build.sh` script:
[ld64-repro.zip](https://github.com/dotnet/runtime/files/14158487/ld64-repro.zip)

Broken linker will produce unsorted unwind tables, which can be verified with `objdump -u Baseline`.

**Comment by filipnavara** [comment]
The bogus unwinding information comes from functions in the `__unbox` section. We currently don't generate any unwind information for that so presumably the linker generates its own "dummy" one and fails to sort it properly. I'll investigate whether generating it ourselves makes a difference.

**Comment by filipnavara** [comment]
Response from Apple:

> Thank you for filing the feedback report. This is a bug in our linker.
>
> You can use the following workaround until a fix become available:
Please use the -Wl,-Id_classic linker option

**Comment by ivanpovazan** [comment]
Regarding:
> Maybe the right course of action for 8.0 is to use -ld_classic until ld_prime becomes more stable?

Apple announced that they are removing this linker option in https://developer.apple.com/documentation/xcode-release-notes/xcode-16-release-notes so this problem becomes more pressing.

**Comment by filipnavara** [comment]
Apple updated my Feedback tickets with request to try Xcode 16 and report back.

**Comment by filipnavara** [comment]
The original problem with corrupted unwind tables seems to be fixed on the few small samples that I tried. We need to do a full run to make sure that there are no other issues.

**Comment by am11** [comment]
FWIW, with Xcode 16 (released last Monday), we get: `  ld: warning: -ld_classic is deprecated and will be removed in a future release` with PublishAot=true.

**Comment by filipnavara** [comment]
> FWIW, with Xcode 16 (released last Monday), we get: ` ld: warning: -ld_classic is deprecated and will be removed in a future release` with PublishAot=true.

I am aware of this. I run the smoke tests with ld-prime from Xcode 16 release and it seems to be ok. Likewise, the macOS/iOS/tvOS workloads were updated last week to use ld-prime on Xcode 16+: https://github.com/xamarin/xamarin-macios/pull/21231.

_Technically we are still relying on some unwritten guarantees about layout. I have two issues open with Apple to further investigate the usage of `.alt_entry` to mitigate that. The gist is that ld-prime has a bug with multiple symbols defined at the same address which could lead to incorrect dead-stripping (workaroundable with the `N_NO_DEAD_STRIP` flag on ILC output). Unfortunately, ld64 has a different bug which limits the number of consecutive `.alt_entry` symbols due to recursive algorithm running out of stack space._

**Comment by agocke** [comment]
I think this is fixed right?

**Comment by jkotas** [comment]
Should we stop passing `-ld_classic` to Xcode 16+ before closing this issue?

https://github.com/dotnet/runtime/blob/a7fc1ea0014b7a0dc88d968dd3cc5dcc916ff9a7/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Unix.targets#L285

Note that Xamarin iOS made that change in their build targets https://github.com/xamarin/xamarin-macios/pull/21231/files#diff-2e24f1b6f44df7580244d00f106fa1a9e2257536fbca9d7bbdc74571549324a9R1631

**Comment by jkotas** [comment]
@agocke Fixed by https://github.com/dotnet/runtime/pull/110542 ?

**Comment by agocke** [comment]
Yes I think we can call this complete. I’m not sure if we will need to backport this to 8, but we can see if that’s needed later.
