### ISSUE TITLE
System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.RefreshOcspResponse_BeforeExpiration test failure

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#97779]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=547335
Build error leg or test failing: System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.RefreshOcspResponse_BeforeExpiration
Pull request: https://github.com/dotnet/runtime/pull/97746

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.RefreshOcspResponse_BeforeExpiration",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=547335
**Error message validated:** `System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.RefreshOcspResponse_BeforeExpiration`
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 1/31/2024 6:25:26 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by filipnavara** [comment]
Likely caused by https://github.com/dotnet/runtime/pull/97099. /cc @rzikm

**Comment by lewing** [comment]
see https://github.com/dotnet/runtime/issues/97836

**Comment by EgorBo** [comment]
This (and its variations https://github.com/dotnet/runtime/issues/97936 and https://github.com/dotnet/runtime/issues/97836) has been consistently failing on all (at least for the JIT team) PRs for last two weeks. Can we fix it or I should just go and disable it?

cc @rzikm @dotnet/area-system-security

**Comment by rzikm** [comment]
looks like https://github.com/dotnet/runtime/pull/97979 did not help, I will look into it
