### ISSUE TITLE
[wasm] Not opening the browser when starting a Wasm Browser App from VS

### ISSUE THREAD

**Issue by thaystg** [dotnet/runtime#97770]
Steps:
- create a WebAssembly Browser App from VS targetting .NET 8
- Run it from VS. 

Expected behavior:
- Open the browser

**Comment by maraf** [comment]
@thaystg There is an incorrect `inspectUri` in .NET 8 SDK, fixed and backported in https://github.com/dotnet/runtime/pull/95418.
Can you please check if you have the correct `inspectUri` in the generated app?

**Comment by thaystg** [comment]
![image](https://github.com/dotnet/runtime/assets/4503299/7cd52f92-029f-4f10-a4fe-0481064bb818)

**Comment by thaystg** [comment]
These are my dotnet installed, should I check something else?
```
7.0.405 [C:\Program Files\dotnet\sdk]
8.0.101 [C:\Program Files\dotnet\sdk]
8.0.200-preview.24060.48 [C:\Program Files\dotnet\sdk]
8.0.200 [C:\Program Files\dotnet\sdk]
9.0.100-preview.2.24081.5 [C:\Program Files\dotnet\sdk]
```

**Comment by thaystg** [comment]
My question is, why this is the wrong one?

**Comment by maraf** [comment]
> My question is, why this is the wrong one? Am I using the incorrect sdk?

Yes, the backport will be part of 8.0.2

**Comment by maraf** [comment]
It's probably an older version of the package with incorrect uri
