### ISSUE TITLE
[API Proposal]: NotAllowedValuesAttribute

### ISSUE THREAD

**Issue by jointvirt** [dotnet/runtime#97785]
### Background and motivation

I know there is an "AllowedValuesAttribute" attribute, but why not the other way around like "NotAllowedValuesAttribute"? I have repeatedly encountered a situation where there are some values that cannot be in this property.

### API Proposal

```csharp
namespace System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

public class MyClass
{
    [NotAllowedValues("Hello", "World")]
    public IReadOnlyCollection<string> Values { get; set; }
}
```

### API Usage

```csharp
namespace System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

public class MyClass
{
    [NotAllowed(Values = new string[] { "Hello", "World" } )]
    public IReadOnlyCollection<string> Values { get; set; }
}
```

**Comment by eiriktsarpalis** [comment]
Guessing you're looking for [DeniedValuesAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.deniedvaluesattribute?view=net-8.0)?
