### ISSUE TITLE
Setting\getting a function pointer field with reflection not supported

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#97830]
In the Core runtime, a `FieldAccessException` is thrown.

Found by newly added tests in https://github.com/dotnet/runtime/pull/97784

Repro
```cs
FieldInfo fieldInfo = typeof(MyStruct).GetField(nameof(MyStruct.fcnPtr));
fieldInfo.SetValue(new MyStruct(), (IntPtr)200);
// Result: assert or does nothing

public struct MyStruct
{
    public unsafe delegate*<void> fcnPtr = (delegate*<void>)44;

    public MyStruct() { }
}
```

Asserts include
```
type 0x1b not handled in ves_icall_FieldInfo_SetValueInternal
type 0x1b not handled in mono_field_get_value_object
```

**Comment by lambdageek** [comment]
In `mono_copy_value` we already have the case for `MONO_TYPE_FNPTR`.  It has a couple of callers that take a `deref_pointer` argument as `value && field->type->type == MONO_TYPE_PTR`.  I think that needs to be `value && (field->type->type == MONO_TYPE_PTR || field->type->type == MONO_TYPE_FNPTR)`. 

Other work is in the type case analysis in the functions that were mentioned in the asserts:
* `ves_icall_FieldInfo_SetValueInternal`
* ` mono_field_get_value_object_checked`

**Comment by lambdageek** [comment]
@steveharter the issue description is incorrect, right?  The expected behavior is to allow the access, not to throw a FAE, right?  The NativeAOT issue #97833 is correct?
