### ISSUE TITLE
Remove trim warnings from ComponentModel APIs that take Type as a parameter

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#97841]
WinForms have calls to ComponentModel APIs with a type as a parameter that gets trim warnings due to these APIs having RequiresUnreferencedCodeAttribute. Consider making trim compatible versions of these APIs, perhaps with a feature switch set.

 - [System.ComponentModel.TypeDescriptor.GetConverter(Type)](https://github.com/dotnet/winforms/blob/0a2908781a7fd13b4cff83561c23d2330a4707c4/src/System.Windows.Forms/src/System/Windows/Forms/Internal/Formatter.cs#L288)
 - [System.ComponentModel.TypeDescriptor.GetProperties(Type)](https://github.com/dotnet/winforms/blob/904487a9da4bb66f2149edeaab1cc92b67bcc5b2/src/System.Windows.Forms/src/System/Windows/Forms/DataBinding/Binding.cs#L496)
 - [System.ComponentModel.TypeDescriptor.GetProperties(Type, Attribute[])](https://github.com/dotnet/winforms/blob/0a2908781a7fd13b4cff83561c23d2330a4707c4/src/System.Windows.Forms/src/System/Windows/Forms/DataBinding/ListBindingHelper.cs#L602)
 - [System.ComponentModel.PropertyDescriptor.Converter.get](https://github.com/dotnet/winforms/blob/0a2908781a7fd13b4cff83561c23d2330a4707c4/src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/Control.ActiveXImpl.cs#L1149)

Note that some of these APIs have the pattern object.GetType() to get the type parameter. A fuller list of these APIs can be found, 
[Default_Trimmed_Warnings_wpf_attributes_excluded_ComponentModel_Type.txt](https://github.com/dotnet/runtime/files/14168011/Default_Trimmed_Warnings_wpf_attributes_excluded_ComponentModel_Type.txt)

**Comment by steveharter** [comment]
If this is an API suggestion, please add that. For example, I assume to be trim compatible will will want generic versions of these methods.
