### ISSUE TITLE
Remove designer related attributes from ComponentModel when trimming applications

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#97840]
Consider removing design time attributes from `ComponentModel` assemblies for trimmed applications.

There are significant number of trim warnings generated for a simple WinForms application due to the `System.Windows.Forms.Design` assembly pulling in design time attributes from `ComponentModel`. In general, simple WinForms apps should not need the `System.Windows.Forms.Design` assembly at all for trimming, and there will be significant size benefits as well from not including this assembly.

If there is no reason to have these attributes during application execution time, a possible solution to this could be:
- Introduce a new feature switch, something like System.ComponentModel.DesignerAttributes.Enabled.
- Add ILLink.LinkAttributes.xml as a resource to System.ComponentModel.Primitives and System.ComponentModel.TypeConverter and annotated these attributes for removal. See [this](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/ILLink/ILLink.LinkAttributes.Shared.xml) as an example how we do this for lot of other attributes. These annotations would be conditional on the feature switch.
- Modify trimmer defaults in MSBuild to set the new feature switch to true by default when trimming/AOT is enabled. We could probably do this for all apps, not just WinForms as a size optimization.

An XML file, similar to below, could be used to remove the attributes.

```xml
<linker>
  <assembly fullname="System.ComponentModel.Primitives">
    <type fullname="System.ComponentModel.DesignerAttribute">
        <attribute internal="RemoveAttributeInstances" />
    </type>
    <type fullname="System.ComponentModel.EditorAttribute">
        <attribute internal="RemoveAttributeInstances" />
    </type>
  </assembly>

  <assembly fullname="System.ComponentModel.TypeConverter">
    <type fullname="System.ComponentModel.ToolboxItemAttribute">
        <attribute internal="RemoveAttributeInstances" />
    </type>
  </assembly>
</linker>
```

**Comment by MichalStrehovsky** [comment]
Isn't this the same as #92043?

**Comment by LakshanF** [comment]
Duplicate of #92043
