### ISSUE TITLE
SemaphoreSlim.Dispose does not work

### ISSUE THREAD

**Issue by paxhujing** [dotnet/runtime#97851]
![image](https://github.com/dotnet/sdk/assets/13563757/ba608d79-2dcd-480e-9a6c-2f94d6c0453f)

After call _semaphore.Dispose(), the statement 'await _semaphore.WaitAsync()' does not throw ObjectDisposedException.

**Comment by lsoft** [comment]
`Dispose` is not thread-safe. Call `Dispose` if you are 100% sure that semaphore is not using at that moment.

Or, DO NOT dispose `SemaphoreSlim` at all if you did NOT accessed its `WaitHandle` (in this case `Dispose` does almost nothing).

**Comment by Seabizkit** [comment]
you code should be 

`
SemaphoreSlim _semaphore = new(1,1)
var _diposed = false;

var task = new Task[2];

for(var i = 0;i < task.length;i++)
{
	do stuffs
}
await Task.WhenAll(tasks);
_semaphore.Dispose();
`

**Comment by stephentoub** [comment]
Closing as answered. Thanks.
