### ISSUE TITLE
ValidateEnumeratedItemsAttribute does not validate Dictionaries

### ISSUE THREAD

**Issue by DanielHabenicht** [dotnet/runtime#97873]
### Description

The new Recursive Validation does not work for Dictionaries

### Reproduction Steps

```C#
public class ExampleConfig
{
    // Both do not work
    [ValidateEnumeratedItems]
    [ValidateObjectMembers]
    public Dictionary<string, SubConfig> DictionaryOfSubConfig { get; set; }
}

public class SubConfig
{
    [Required(AllowEmptyStrings = false)] public string Attribute1 { get; set; }
}


public class ValidationClientTests : UnitTestBase
{

    [Fact]
    public void ValidateWorking()
    {
        var config = new ExampleConfig()
        {
            DictionaryOfSubConfig = new Dictionary<string, SubConfig>()
            {
                {
                    "test",
                    new SubConfig()
                    {

                    }
                }
            }
        };

        var context = new ValidationContext(config);

        var validationResults = new List<ValidationResult>();
        var isValid = Validator.TryValidateObject(config, context, validationResults, true);
        validationResults.Should().HaveCount(1);
    }
    
    public ValidationClientTests(ITestOutputHelper outputHelper) : base(outputHelper)
    {
    }
}
```

### Expected behavior

The Validation should fail.

### Actual behavior

The validation does not fail.

### Regression?

I am not sure. 

### Known Workarounds

Custom Attribute `[ValidateDictionary]`

```C#
public class ValidateDictionary : ValidationAttribute
    {
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            var results = new List<ValidationResult>();
            if (value != null)
            {

                if (value is IEnumerable enumerable)
                {
                    foreach (object obj2 in enumerable)
                    {
                        foreach (PropertyInfo propertyInfo in
                                 ((IEnumerable<PropertyInfo>) obj2.GetType().GetProperties())
                                 .Where<PropertyInfo>((Func<PropertyInfo, bool>) (prop =>
                                     prop.CanRead && prop.GetIndexParameters().Length == 0)).ToList<PropertyInfo>())
                        {
                            if (!(propertyInfo.PropertyType == typeof(string)) &&
                                !propertyInfo.PropertyType.IsValueType)
                            {
                                object obj1 =
                                    obj2.GetType().GetProperty(propertyInfo.Name)
                                        ?.GetValue((object) obj2, (object[]) null) ?? (object) string.Empty;

                                var context = new ValidationContext(obj1, null, null);

                                Validator.TryValidateObject(obj1, context, results, true);
                            }
                        }
                    }
                }
            }

            if (results.Count != 0)
            {
                var compositeResults = new CompositeValidationResult(
                    $"Validation for {validationContext.DisplayName} failed!");
                results.ForEach(compositeResults.AddResult);

                return compositeResults;
            }

            return ValidationResult.Success;
        }
```

### Configuration

Used Dotnet 8.0.101. Here is the system info:

.NET SDK:
 Version:           8.0.101   
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.8a1da915

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.101\

.NET workloads installed:
 Workload version: 8.0.100-manifests.8a1da915
 [wasm-tools]
   Installation Source: SDK 8.0.100, VS 17.8.34408.163
   Manifest Version:    8.0.1/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.current\8.0.1\WorkloadManifest.json
   Install Type:              Msi

 [wasm-tools-net7]
   Installation Source: VS 17.8.34408.163
   Manifest Version:    8.0.1/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.net7\8.0.1\WorkloadManifest.json
   Install Type:              Msi

Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92

.NET SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.818 [C:\Program Files\dotnet\sdk]
  3.1.414 [C:\Program Files\dotnet\sdk]
  5.0.415 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]
  6.0.302 [C:\Program Files\dotnet\sdk]
  6.0.404 [C:\Program Files\dotnet\sdk]
  8.0.100 [C:\Program Files\dotnet\sdk]
  8.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  arm64 [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\arm64\InstallLocation]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

**Comment by tarekgh** [comment]
You may do the following:

```C#

public class ExampleConfig
{
    public Dictionary<string, SubConfig> DictionaryOfSubConfig { get; set; }

    [ValidateEnumeratedItems]
    public IEnumerable<SubConfig> SubConfigValues => DictionaryOfSubConfig.Values;
}
```

**Comment by DanielHabenicht** [comment]
> You may do the following:
> 
> ```cs
> public class ExampleConfig
> {
>     public Dictionary<string, SubConfig> DictionaryOfSubConfig { get; set; }
> 
>     [ValidateEnumeratedItems]
>     public IEnumerable<SubConfig> SubConfigValues => DictionaryOfSubConfig.Values;
> }
> ```

Sorry for the delay. 
That seems to be working, but it's still a workaround that I would not expect to be using. right?
I mean Dictionary is an `IEnumerable` and the name of `ValidateEnumeratedItems` indicates that it should validate it.

**Comment by tarekgh** [comment]
> I mean Dictionary is an IEnumerable and the name of ValidateEnumeratedItems indicates that it should validate it.

It depends on how you see it :-) 

In your case the dictionary will be `IEnumerable<KeyValuePair<string, SubConfig>>`, the KeyValuePair has the properties `Key` and `Value` are not tagged with any validation attributes which will not get any validation. Except if you are asking to have the validation engine to not only check the attributed properties and analyze the property types deeply to try to find any deep nested property may have a property tagged with validation attribute. 

Imagine something like

```C#

public  class MyClass
{
     public KeyValuePair<Type1, Type2> Property { get; }
}

public class Type1 { public Type3 Type { get; }  }
public class Type3 { public Type4 Type { get; }  }
public class Type4 { public Type5 Type { get; }  }
public class Type5 { [Required(AllowEmptyStrings = false)] public string Type { get; }  }

... Type2 can have nesting too.

```

Anyway, this is not how the validation engine work and we don't have any plan to support that.
