### ISSUE TITLE
[API Proposal]: A way to change volume of a played sound with `SoundPlayer`

### ISSUE THREAD

**Issue by ficcialfaint** [dotnet/runtime#97926]
### Background and motivation

.NET apps using SoundPlayer to play audio have no built-in way to let the user adjust the volume of a played sound which could make the user experience significantly worse

### API Proposal

```csharp
namespace System.Media;

public class SoundPlayer : Component, ISerializable
{
    public PlayWithGain(float gain);
}
```

### API Usage

```csharp
// Adjust the audio volume by 20db
var sound = new SoundPlayer("audio.wav");
sound.PlayWithGain(20f);
```

### Alternative Designs

Could also use percentage of the current volume instead of a specific amount of decibels to adjust. For example, `PlayWithVolume(100);` would play the audio at its regular volume; `PlayWithVolume(200);` would make the audio's volume twice louder; `PlayWithVolume(50);` -- twice quieter, etc.

**Comment by huoyaoyuan** [comment]
`SoundPlayer` is a direct wrapper of winmm PlaySound function, which is highly legacy and does not support such functionality.

**Comment by Zintom** [comment]
> `SoundPlayer` is a direct wrapper of winmm PlaySound function, which is highly legacy and does not support such functionality.

I think anyone wanting to do any kind of sound work should use NAudio, it has basic classes for the kind of thing OP wants, but then you can go into real detail of how things are processed if you want.

**Comment by ficcialfaint** [comment]
Apologies for the issue, do I just close it or is fine to leave it open for future SoundPlayer reworks or something?

**Comment by huoyaoyuan** [comment]
I don't believe it's feasible to rework it in the future, given its legacy API shape and containing package.

**Comment by ericstj** [comment]
We aren't investing in SoundPlayer.  It exists only for compatibility, please consider other APIs / packages for this functionality.

**Comment by julealgon** [comment]
> ...please consider other APIs

@ericstj what other APIs are there that are native to the framework or handled by Microsoft?

Could you list a few potential replacement options for reference?
