### ISSUE TITLE
'System.CodeDom.Compiler.CodeDomProvider.CreateValidIdentifier(string)` fails on potential identifiers that begin with a number (C#)

### ISSUE THREAD

**Issue by domportera** [dotnet/runtime#97945]
### Description

See reproduction steps - CreateValidIdentifier does not correctly modify an invalid identifier starting with a number by prepending it with an underscore

### Reproduction Steps

```
    CodeDomProvider codeDomProvider = CodeDomProvider.CreateProvider("C#");
	string namespaceComponent = "3d";

    if (!codeDomProvider.IsValidIdentifier(namespaceComponent))
    {
        namespaceComponent = codeDomProvider.CreateValidIdentifier(namespaceComponent);
    }

	// fails
	Debug.Assert(namespaceComponent == "_3d");
```

### Expected behavior

It would prepend a string such as "3d" with an underscore so that the result is "_3d"

### Actual behavior

it simply returns "3d"

### Known Workarounds

check identifier validity after running the method and prepend the underscore manually

### Configuration

.Net Core 8
Windows 10 x64

### Other information

I'm not sure if this is intentional due to code styling standards or something, but if it is it seems like an unintuitive place to enforce that

**Comment by buyaa-n** [comment]
The [doc](https://learn.microsoft.com/en-us/dotnet/api/system.codedom.compiler.codedomprovider.createvalididentifier?view=dotnet-plat-ext-8.0#remarks) mentions only reserved or language keywords, so it sounds like was intentional.

> [CreateValidIdentifier](https://learn.microsoft.com/en-us/dotnet/api/system.codedom.compiler.codedomprovider.createvalididentifier?view=dotnet-plat-ext-8.0) tests whether the identifier conflicts with reserved or language keywords, and if so, attempts to return a valid identifier name that does not conflict. Usually the returned identifier is only slightly modified to differentiate the identifier from the keyword; for example, the name might be preceded by the underscore ("_") character.

Though I don't see an issue for covering identifiers starts with a number, what is your use case for needing this?

**Comment by domportera** [comment]
> The [doc](https://learn.microsoft.com/en-us/dotnet/api/system.codedom.compiler.codedomprovider.createvalididentifier?view=dotnet-plat-ext-8.0#remarks) mentions only reserved or language keywords, so it sounds like was intentional.
> 
> > [CreateValidIdentifier](https://learn.microsoft.com/en-us/dotnet/api/system.codedom.compiler.codedomprovider.createvalididentifier?view=dotnet-plat-ext-8.0) tests whether the identifier conflicts with reserved or language keywords, and if so, attempts to return a valid identifier name that does not conflict. Usually the returned identifier is only slightly modified to differentiate the identifier from the keyword; for example, the name might be preceded by the underscore ("_") character.
> 
> Though I don't see an issue for covering identifiers starts with a number, what is your use case for needing this?

I think this is just my fault in misunderstanding the purpose of the function. My (incorrect) thought was that this should turn an arbitrary identifier into a language-valid one. Sorry, feel free to close this if you like!

**Comment by buyaa-n** [comment]
> Sorry, feel free to close this if you like!

OK then closing
