### ISSUE TITLE
SizeLimit always discard new items if size is exceeded

### ISSUE THREAD

**Issue by davide-pi** [dotnet/runtime#97962]
### Description

Setting the SizeLimit in a MemoryCache instance, when the size of actual keys + size of a new key exceed the limit the new key is always discarded. Resulting in the inability to enter new keys until a previous key expires!

In the following image is possible to see that KEY3 is never inserted
![image](https://github.com/dotnet/runtime/assets/133281491/675b590f-7665-4e7f-8028-452546874298)

### Reproduction Steps

To reproduce the behaviour you can use the following simple code:

```csharp

using Microsoft.Extensions.Caching.Memory;

using System;

namespace InMemoryCacheTest;

internal class Program
{
    static void Main(string[] args)
    {
        var sizeLimitInBytes = 11;

        var cache = new MemoryCache(
        new MemoryCacheOptions
        {
            SizeLimit = sizeLimitInBytes,
            TrackStatistics = true,
        });

        Console.WriteLine("INSERT KEYS:");
        GetValue(cache, "KEY1", 1, sizeLimitInBytes);
        GetValue(cache, "KEY2", 2, sizeLimitInBytes);
        GetValue(cache, "KEY3", 3, sizeLimitInBytes);

        Console.WriteLine("\nTRY TO RETRIEVE VALUES:");
        GetValue(cache, "KEY3", 3, sizeLimitInBytes);
        GetValue(cache, "KEY2", 2, sizeLimitInBytes);
        GetValue(cache, "KEY1", 1, sizeLimitInBytes);
        GetValue(cache, "KEY3", 3, sizeLimitInBytes);
        GetValue(cache, "KEY3", 3, sizeLimitInBytes);
        GetValue(cache, "KEY3", 3, sizeLimitInBytes);
        GetValue(cache, "KEY3", 3, sizeLimitInBytes);
        GetValue(cache, "KEY2", 2, sizeLimitInBytes);
        GetValue(cache, "KEY1", 1, sizeLimitInBytes);
    }


    public static void GetValue(MemoryCache cache, string key, int value, int sizeLimit)
    {
        var memoryCacheOptions = new MemoryCacheEntryOptions()
            .SetAbsoluteExpiration(new TimeSpan(0, 10, 0))
            .SetSize(sizeof(int));

        if (!cache.TryGetValue<int>(key, out var value2))
        {
            Console.WriteLine($"\t{key} not found, try insert");
            cache.Set(key, value, memoryCacheOptions);
        }
        else
        {
            Console.WriteLine($"\t{key} value is {value2}");
        }
        Console.WriteLine($"\t\tEntry count: {cache.GetCurrentStatistics().CurrentEntryCount}");
        Console.WriteLine($"\t\tEstimate size: {cache.GetCurrentStatistics().CurrentEstimatedSize}/{sizeLimit}");
    }
}

```

Otherwise is sufficient to create a new MemoryCache setting a SizeLimit in its options. And try to add some keys with specific sizes until one new key will exceed the limit previously set. Trying to retrieve these last value you will see that it wasn't iserted!

### Expected behavior

The new key is always inserted.
If the new key exceed the size limit, then one of the previous keys will be removed using some euristic metric.

Possible metric, the keys with the lowest remaining TTL whose size sum allows it to fall within the size limit. Or more complex metrics that involve also the GC statistics.

### Actual behavior

New keys that exceeds the size limit set in the MemoryCache instance are always discarded.

### Configuration

- The actual code run on .NET8.0 but also in .NET6.0 is present
- OS used is Win10
- Architecture: x64

**Comment by adamsitnik** [comment]
Hello @davide-pi 

Thank you for a very detailed bug report.

This is a known bug: https://github.com/dotnet/runtime/issues/36039, https://github.com/dotnet/runtime/issues/42624. I don't see myself having the time to fix it anytime soon, but both issues are marked as "help-wanted" so please feel free to step up and send a PR with a fix (cc @manadre and @teo-tsirpanis who provided a lot of high quality PRs in the past and may be interested in helping here as well).

I am going to close the issue as a duplicate.

Thanks!
