### ISSUE TITLE
Blazor webassembly project Program.cs cannot be debugged

### ISSUE THREAD

**Issue by HolyOne** [dotnet/runtime#97987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In a webassembly project, Program.cs (Client Project) cannot be debugged in Visual Studio
I have no idea if the lines work or not.

There are existing issues that label this one fixed. But I am using the latest VS and .net version and I have this problem.

### .NET Version

8.0.200-preview.23624.5

**Comment by HolyOne** [comment]
Today it is working  :|
Sorry, I am sure I tried several times before but since the problem doesnt seem to happen now, i cant provide output console.

**Comment by tommcdon** [comment]
Possibly related to #98208
@thaystg

**Comment by tommcdon** [comment]
> Sorry, I am sure I tried several times before but since the problem doesnt seem to happen now, i cant provide output console.

@HolyOne no worries at all!  Please feel free to reach out again if this issue re-occurs.  I'll close this issue for now until we have more details on the source of the problem.
