### ISSUE TITLE
DirectoryNotFoundException on Directory.Create

### ISSUE THREAD

**Issue by Evangelink** [dotnet/runtime#97980]
Hi runtime team,

As per @adamsitnik suggestion, I am opening an issue here and assigning @carlossanlop and @JeremyKuhne.

On MSTest repo, we have some bug report https://github.com/microsoft/testfx/issues/2219 of a call to `Directory.Create` that throws some `DirectoryNotFoundException`. From the logs, there doesn't seem to have any issue with the path and the user says it's not a mapped drive.

What are the other reasons/cases for this exception to be thrown? Looking at the code and user comments, the only hypotesis I have is some concurrency access but I am not sure this would be causing this exception.

**Comment by Jozkee** [comment]
Looks like this was explained in https://github.com/microsoft/testfx/issues/2219#issuecomment-1938251276.
