### ISSUE TITLE
superpmi replay jobs are failing

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#97985]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=553348&view=logs&j=83516c17-6666-5250-abde-63983ce72a49&t=2694d93b-a574-5310-1876-2e252085b877

```
  Sent Helix Job; see work items at https://helix.dot.net/api/jobs/b47a93c4-8af2-4a04-949b-ebb658a3820a/workitems?api-version=2019-06-17
  Waiting for completion of job b47a93c4-8af2-4a04-949b-ebb658a3820a on Windows.10.Amd64.Open (Details: https://helix.dot.net/api/jobs/b47a93c4-8af2-4a04-949b-ebb658a3820a/details?api-version=2019-06-17 )
D:\a\_work\1\s\.packages\microsoft.dotnet.helix.sdk\9.0.0-beta.24081.4\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(68,5): error : RestApiException`1: The response contained an invalid status code 500 Internal Server Error [D:\a\_work\1\s\src\coreclr\scripts\superpmi-replay.proj]
D:\a\_work\1\s\.packages\microsoft.dotnet.helix.sdk\9.0.0-beta.24081.4\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(68,5): error :  [D:\a\_work\1\s\src\coreclr\scripts\superpmi-replay.proj]
D:\a\_work\1\s\.packages\microsoft.dotnet.helix.sdk\9.0.0-beta.24081.4\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(68,5): error : Body: {"Message":"An error occured.","ActivityId":"6cb7aa8a81198fa6ab6b0758ba6ba59b"} [D:\a\_work\1\s\src\coreclr\scripts\superpmi-replay.proj]
D:\a\_work\1\s\.packages\microsoft.dotnet.helix.sdk\9.0.0-beta.24081.4\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(68,5): error :    at Microsoft.DotNet.Helix.Client.Job.OnDetailsFailed(Request req, Response res) in /_/src/Microsoft.DotNet.Helix/Client/CSharp/generated-code/Job.cs:line 493 [D:\a\_work\1\s\src\coreclr\scripts\superpmi-replay.proj]
D:\a\_work\1\s\.packages\microsoft.dotnet.helix.sdk\9.0.0-beta.24081.4\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(68,5): error :    at Microsoft.DotNet.Helix.Client.Job.DetailsAsync(String job, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/Client/CSharp/generated-code/Job.cs:line 455 [D:\a\_work\1\s\src\coreclr\scripts\superpmi-replay.proj]
D:\a\_work\1\s\.packages\microsoft.dotnet.helix.sdk\9.0.0-beta.24081.4\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(68,5): error :    at Microsoft.DotNet.Helix.Sdk.WaitForHelixJobCompletion.WaitForHelixJobAsync(String jobName, String queueName, String helixJobCancellationToken, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/Sdk/WaitForHelixJobCompletion.cs:line 56 [D:\a\_work\1\s\src\coreclr\scripts\superpmi-replay.proj]
D:\a\_work\1\s\.packages\microsoft.dotnet.helix.sdk\9.0.0-beta.24081.4\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(68,5): error :    at Microsoft.DotNet.Helix.Sdk.WaitForHelixJobCompletion.ExecuteCore(CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/Sdk/WaitForHelixJobCompletion.cs:line 33 [D:\a\_work\1\s\src\coreclr\scripts\superpmi-replay.proj]
D:\a\_work\1\s\.packages\microsoft.dotnet.helix.sdk\9.0.0-beta.24081.4\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(68,5): error :    at Microsoft.DotNet.Helix.Sdk.HelixTask.Execute() in /_/src/Microsoft.DotNet.Helix/Sdk/HelixTask.cs:line 61 [D:\a\_work\1\s\src\coreclr\scripts\superpmi-replay.proj]
D:\a\_work\1\s\.packages\microsoft.dotnet.helix.sdk\9.0.0-beta.24081.4\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(68,5): error :  [D:\a\_work\1\s\src\coreclr\scripts\superpmi-replay.proj]

```

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "The response contained an invalid status code 500 Internal Server Error",
  "ErrorPattern": "The response contained an invalid status code 500 Internal Server Error",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[553812](https://dev.azure.com/dnceng-public/public/_build/results?buildId=553812)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/553812/logs/1696)|dotnet/runtime#97989|
|[551401](https://dev.azure.com/dnceng-public/public/_build/results?buildId=551401)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/551401/logs/2712)|dotnet/runtime#97891|
|[553826](https://dev.azure.com/dnceng-public/public/_build/results?buildId=553826)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/553826/logs/899)|dotnet/runtime#95001|
|[553841](https://dev.azure.com/dnceng-public/public/_build/results?buildId=553841)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/553841/logs/427)|dotnet/runtime#97537|
|[553450](https://dev.azure.com/dnceng-public/public/_build/results?buildId=553450)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/553450/logs/1529)|dotnet/runtime#97977|
|[553592](https://dev.azure.com/dnceng-public/public/_build/results?buildId=553592)|dotnet/runtime|Send tests to Helix (Windows)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/553592/logs/3324)|dotnet/runtime#97929|
|[553596](https://dev.azure.com/dnceng-public/public/_build/results?buildId=553596)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/553596/logs/1902)|dotnet/runtime#97979|
|[553506](https://dev.azure.com/dnceng-public/public/_build/results?buildId=553506)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/553506/logs/512)|dotnet/runtime#97977|
|[553784](https://dev.azure.com/dnceng-public/public/_build/results?buildId=553784)|dotnet/runtime|Send job to Helix (Windows)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/553784/logs/65)|dotnet/runtime#97234|
|[553785](https://dev.azure.com/dnceng-public/public/_build/results?buildId=553785)|dotnet/runtime|Send job to Helix (Windows)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/553785/logs/171)|dotnet/runtime#97234|
|[553714](https://dev.azure.com/dnceng-public/public/_build/results?buildId=553714)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/553714/logs/1640)|dotnet/runtime#97865|
|[553726](https://dev.azure.com/dnceng-public/public/_build/results?buildId=553726)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/553726/logs/1574)|dotnet/runtime#97970|
|[2370362](https://dev.azure.com/dnceng/internal/_build/results?buildId=2370362)|dotnet-runtime|Send job to Helix (Unix)|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2370362/logs/1542)||
|[553674](https://dev.azure.com/dnceng-public/public/_build/results?buildId=553674)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/553674/logs/2558)|dotnet/runtime#97784|
|[553691](https://dev.azure.com/dnceng-public/public/_build/results?buildId=553691)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/553691/logs/1633)|dotnet/runtime#97885|
|[553615](https://dev.azure.com/dnceng-public/public/_build/results?buildId=553615)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/553615/logs/2613)|dotnet/runtime#97982|
|[553620](https://dev.azure.com/dnceng-public/public/_build/results?buildId=553620)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/553620/logs/1426)|dotnet/runtime#97983|
|[553557](https://dev.azure.com/dnceng-public/public/_build/results?buildId=553557)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/553557/logs/1772)|dotnet/runtime#97976|
|[553217](https://dev.azure.com/dnceng-public/public/_build/results?buildId=553217)|dotnet/runtime|Send tests to Helix (Windows)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/553217/logs/511)|dotnet/runtime#97921|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|19|19|19|

**Comment by jakobbotsch** [comment]
Tracking issue https://github.com/dotnet/dnceng/issues/1951
