### ISSUE TITLE
[wasm] `runtime-wasm-perf` not running on PRs anymore

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#97998]
The last run was on Jan 26 - https://dev.azure.com/dnceng-public/public/_build?definitionId=156 .
cc @akoeplinger

**Comment by lewing** [comment]
cc @sblom

**Comment by sblom** [comment]
We're investigating.

**Comment by radical** [comment]
Can this be closed now?

**Comment by radical** [comment]
Closing this as the pipeline is indeed being run for PRs now.
