### ISSUE TITLE
[browser][mt] Changes broke dotnet build in Http solution

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#98000]
https://github.com/dotnet/runtime/pull/97560 broke calling `dotnet build` in `src/libraries/System.Net.Http`. It works on the previous commit (I did a binary search to find the exact commit that broke this).

Error:
```
/home/manicka/repositories/runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/RuntimeInformation.cs(76,8): error CS1029: #error: 'Unknown Architecture' [/home/manicka/repositories/runtime/src/coreclr/System.Private.CoreLib/System.Private.CoreLib.csproj]
```

@ilonatommy PTAL

**Comment by ilonatommy** [comment]
@ManickaP, could you please help me reproduce? I tried on new codespaces, I did:
```
./build.sh mono+libs -c release -os browser
cd src/libraries/System.Net.Http
dotnet build
```
and it finished with success, no errors. What am I doing wrong?

**Comment by ManickaP** [comment]
I use `./build.sh clr+libs -rc release`. I'm also on Linux if that plays any role. And my globally installed dotnet is:
```
.NET SDK:
 Version:           9.0.100-alpha.1.24068.28
 Commit:            cc3d47d4cb
 Workload version:  9.0.100-manifests.745f81b6

Runtime Environment:
 OS Name:     arch
 OS Version:
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/9.0.100-alpha.1.24068.28/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      9.0.0-alpha.1.24061.26
  Architecture: x64
  Commit:       22ba7d607b
```

**Comment by pavelsavara** [comment]
cc @ViktorHofer

**Comment by ManickaP** [comment]
Ok, so this is somehow fixed in main. I did another search and it was fixed by : https://github.com/dotnet/runtime/commit/cb0e160e50593ab014064a2e675b8d2e54ca3107
