### ISSUE TITLE
Android: HttpClient POST request adds unwanted Content-Type header

### ISSUE THREAD

**Issue by rgroenewoudt** [dotnet/runtime#98029]
### Description

In .NET 8 Android when doing a HttpClient POST request (without setting Content-Type header), the header `"Content-Type": "application/x-www-form-urlencoded"` is automatically added, which is incorrect.

When using SocketsHttpHandler (and not native Android HttpClientHandler), the problem doesn't occur.

### Reproduction Steps

```
// https://httpbin.org/post returns the request including headers
public async Task TestAndroidHttpClient()
{
    var client = new HttpClient(new HttpClientHandler());
    using var response = await client.PostAsync("https://httpbin.org/post", new StreamContent(Stream.Null));
    var responseBody = await response.Content.ReadAsStringAsync();
    Console.WriteLine($"TestAndroidHttpClient: {responseBody}");
}

public async Task TestSocketsHttpClient()
{
    var client = new HttpClient(new SocketsHttpHandler());
    using var response = await client.PostAsync("https://httpbin.org/post", new StreamContent(Stream.Null));
    var responseBody = await response.Content.ReadAsStringAsync();
    Console.WriteLine($"TestSocketsHttpClient: {responseBody}");
}
```

Setting HttpContent.Headers.ContentType explicitly to null also doesn't help.

Empty test app with the 2 methods:
[AndroidApp10.zip](https://github.com/dotnet/runtime/files/14179104/AndroidApp10.zip)

### Expected behavior

Content-Type header is not present in request.

### Actual behavior

HttpClientHandler: includes `"Content-Type": "application/x-www-form-urlencoded"`
SocketsHttpHandler: like expected it isn't present.

Setting HttpContent.Headers.ContentType explicitly to null also doesn't help.

### Configuration

.NET 8.0.1 Android
VS2022 17.8.6

**Comment by simonrozsival** [comment]
@rgroenewoudt If I remember correctly this header (and also `User-Agent`, `Accept-Encoding`, `Content-Length`) are set to some default value by the native java HTTP stack (`HttpURLConnection`) when you don't provide your own value.

If you want to be in control of the `Content-Type` for the empty content, you might want to consider implementing your own content class:
```c#
private class EmptyContent : HttpContent
{
    public EmptyContent()
    {
        Headers.ContentType = new MediaTypeHeaderValue("text/plain");
    }

    protected override Task SerializeToStreamAsync(Stream stream, TransportContext? context) => Task.CompletedTask;
    protected override bool TryComputeLength(out long length)
    {
        length = 0;
        return true;
    }
}
```
