### ISSUE TITLE
Proposal: allow marking native exports in NativeAOT as PRIVATE

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#98047]
### Background and motivation

When authoring WinRT component, you have to also export the [`DllCanUnloadNow`](https://learn.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-dllcanunloadnow) function, as part of the WinRT contract.
When doing so, MSVC emits the following warning:
> "warning LNK4104: export of symbol 'DllCanUnloadNow' should be PRIVATE"

This makes the authoring experience with CsWinRT not ideal, so wondering if we could do better.
Possible solutions (with wildly different costs):
- Add some `bool IsPrivate` property to `[UnmanagedCallersOnly]` to indicate whether to exclude it from the .lib file
- Add some MSBuild property to indicate which exports to keep as private
- Special case just `DllCanExecuteNow` and always export it as PRIVATE
- Just make users (or, CsWinRT in a .targets) add `LNK4104` to `NoWarn` and call it a day

Of course, that `bool IsPrivate` is more general and flexible, but also more costly. Not entirely sure how much of an appetite there is for this feature in general outside of this specific case (as in, don't think I've seen that specific feature request before).

Leaving this blank so we can think about which approach would be preferrable, before potentially making this a real proposal.

**Comment by AaronRobinsonMSFT** [comment]
> Just make users (or, CsWinRT in a .targets) add LNK4104 to NoWarn and call it a day

Yes, that is the solution. The `PRIVATE` notion is an MSVC concept and reflects what is present in the import lib. This is not something we would be inclined to attempt to mitigate at the API layer or even internally as it is a Windows-centric issue.
