### ISSUE TITLE
.net TLS 1.2 enable Ed25519 in signature algorithms extension

### ISSUE THREAD

**Issue by mkitby** [dotnet/runtime#98067]
### Is your feature request related to a problem? Please describe.
I am trying to use .net System.Net.Security Sslstream to communicate with a TLS server which only support ED25519 signature algorithm. The problem is ED25519 is missed in signature algorithms extension in client hello, which is not accepted by TLS server.

reference code: https://learn.microsoft.com/en-us/dotnet/api/system.net.security.sslstream?view=net-7.0

### Describe the solution you'd like
I want to enable ED25519 in tls

### Additional context
bad case
![Snipaste_2023-09-13_15-19-09](https://github.com/dotnet/sdk/assets/15389150/d508f251-30e5-4300-ac94-e47f601cdbdd)

good case
![Snipaste_2023-09-13_15-20-00](https://github.com/dotnet/sdk/assets/15389150/bd9c6ca8-bc02-431b-9fa2-c936bd66cf19)

**Comment by wfurt** [comment]
What OS do you use @mkitby? The default list comes from the platform e.g. on Windows you can impact it by registry setting, on Linux you can modify openssl.conf

**Comment by wfurt** [comment]
BTW here is list of supported suites on different Windows versions: https://learn.microsoft.com/en-us/windows/win32/secauthn/cipher-suites-in-schannel
