### ISSUE TITLE
Fix underlying bug in Named Pipes preventing setting ReadMode after creation

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#98060]
Follow up of the discussion in this API proposal (please read it for context): https://github.com/dotnet/runtime/issues/83072

We need to match the behavior of both .NET Framework and Linux. Porting the constructor is not the only answer or even the best answer.

The alternatives are:

### Fix the bug in the existing APIs

This is the ideal scenario and the most straightforward, and the one this issue intends to address.

- Fix  the bug in the Acl factory method `Create`.
  - Ensure the user can set the access rights on pipe creation, not after creation.
  - Change the default access rights to prevent the bug if the user passes no access rights on creation.
  - This would be an acceptable breaking change.
  - We can reuse some of the code found in this workaround: https://github.com/carlossanlop/experiments/tree/NamedPipeClientStream_ReadMode

### Merge assemblies

Additional separate scenario.

We originally created all the `System.*.AccessControl` assemblies because we didn't want to mix OS-specific APIs. But we now have the `SupportedOSPlatform` attribute, which allows having OS-specific APIs in the same assembly. In other words, we could merge the AccessControl assemblies with the base assembly they were extending.
 
### Port _all_ the missing constructors

Additional separate scenario.

No point in porting only one missing .NET Framework constructor that we didn't add to .NET Core+. If we are doing the effort for one, let's just do the same for all.

**Comment by ericstj** [comment]
I don't think we need this.  I've clarified the API request.  I'll give that one more attempt at getting approved.
