### ISSUE TITLE
Merge bounds check nodes

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/runtime#9808]
The `GT_ARR_BOUNDS_CHECK` and `GT_SIMD_CHK` nodes shouldn't need to be separate operators, as their semantic differences are captured in the `gtThrowKind` on the `GenTreeBoundsChk` node. In addition, a `GT_HW_INTRINSIC_CHK` is being added, which is also not really needed.
It may be that there are some entanglements with existing array bounds check elimination (or other) code that will need to be sorted before merging these.

category:implementation
theme:bounds-checks
skill-level:expert
cost:medium

**Comment by SingleAccretion** [comment]
Fixed in #62088.
