### ISSUE TITLE
[aot] Library tests failures on Windows, assertion `elems <= MAX_VECTOR_ELEMS / 2' not met

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#98099]
`Assertion at D:\a\_work\1\s\src\mono\mono\mini\mini-llvm.c:8581, condition `elems <= MAX_VECTOR_ELEMS / 2' not met `

### Error Blob

```json
{
  "ErrorMessage": "",
  "BuildRetry": false,
  "ErrorPattern": "Assertion.*llvm.*elems.*MAX_VECTOR_ELEMS",
  "ExcludeConsoleLog": false
}
```

### Reproduction Steps

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=556904&view=logs&jobId=b455efc5-4fe2-50ab-5106-412ad73c23a0

[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-98087-merge-c993776aaf5a4db99f/WasmTestOnBrowser-Microsoft.Extensions.Configuration.Json.Tests/1/console.7fd1e719.log?helixlogtype=result)
```
  [System.Private.CoreLib.dll] Exec (with response file contents expanded) in C:\helix\work\workitem\e\wasm_build\obj\wasm\for-build\aot-in: MONO_PATH=C:\helix\work\workitem\e\wasm_build\obj\wasm\for-build\aot-in;C:\helix\work\correlation\build\microsoft.netcore.app.runtime.browser-wasm\runtimes\browser-wasm\native\;C:\helix\work\correlation\build\microsoft.netcore.app.runtime.browser-wasm\runtimes\browser-wasm\lib\net9.0 MONO_ENV_OPTIONS= C:\helix\work\correlation\build\cross\mono-aot-cross.exe --wasm-exceptions --debug --llvm "--aot=no-opt,static,direct-icalls,deterministic,mattr=simd,dwarfdebug,llvm-path=C:\helix\work\correlation\build\emsdk\upstream\bin\,static,dedup-skip,trimming-eligible-methods-outfile=C:\helix\work\workitem\e\wasm_build\obj\wasm\for-build\tokens\System_Private_CoreLib_dll_compiled_methods.txt,llvmonly,interp,asmonly,llvm-outfile=C:\helix\work\workitem\e\wasm_build\obj\wasm\for-build\System.Private.CoreLib.dll.bc.tmp,temp-path=C:\helix\work\workitem\e\wasm_build\obj\wasm\for-build\System.Private.CoreLib.dll.tmp" "System.Private.CoreLib.dll"
  
C:\helix\work\correlation\build\wasm-shared\WasmApp.Common.targets(677,5): error : Precompiling failed for C:\helix\work\workitem\e\wasm_build\obj\wasm\for-build\aot-in\System.Private.CoreLib.dll with exit code -1073740791. [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
C:\helix\work\correlation\build\wasm-shared\WasmApp.Common.targets(677,5): error : Mono Ahead of Time compiler - compiling assembly C:\helix\work\workitem\e\wasm_build\obj\wasm\for-build\aot-in\System.Private.CoreLib.dll [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
C:\helix\work\correlation\build\wasm-shared\WasmApp.Common.targets(677,5): error : * Assertion at D:\a\_work\1\s\src\mono\mono\mini\mini-llvm.c:8581, condition `elems <= MAX_VECTOR_ELEMS / 2' not met [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=556904
**Error message validated:** `[Assertion.*llvm.*elems.*MAX_VECTOR_ELEMS`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 2/7/2024 6:07:06 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[564149](https://dev.azure.com/dnceng-public/public/_build/results?buildId=564149)|dotnet/runtime|LLVM AOT compile CoreCLR tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/564149/logs/1185)||
|[563468](https://dev.azure.com/dnceng-public/public/_build/results?buildId=563468)|dotnet/runtime|LLVM AOT compile CoreCLR tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/563468/logs/1177)||
|[562884](https://dev.azure.com/dnceng-public/public/_build/results?buildId=562884)|dotnet/runtime|LLVM AOT compile CoreCLR tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/562884/logs/31)|dotnet/runtime#92057|
|[562464](https://dev.azure.com/dnceng-public/public/_build/results?buildId=562464)|dotnet/runtime|LLVM AOT compile CoreCLR tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/562464/logs/31)|dotnet/runtime#92057|
|[562296](https://dev.azure.com/dnceng-public/public/_build/results?buildId=562296)|dotnet/runtime|LLVM AOT compile CoreCLR tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/562296/logs/1185)||
|[562067](https://dev.azure.com/dnceng-public/public/_build/results?buildId=562067)|dotnet/runtime|LLVM AOT compile CoreCLR tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/562067/logs/1185)||
|[562000](https://dev.azure.com/dnceng-public/public/_build/results?buildId=562000)|dotnet/runtime|LLVM AOT compile CoreCLR tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/562000/logs/916)|dotnet/runtime#98279|
|[561823](https://dev.azure.com/dnceng-public/public/_build/results?buildId=561823)|dotnet/runtime|LLVM AOT compile CoreCLR tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/561823/logs/1177)||
|[561414](https://dev.azure.com/dnceng-public/public/_build/results?buildId=561414)|dotnet/runtime|LLVM AOT compile CoreCLR tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/561414/logs/1185)||
|[560509](https://dev.azure.com/dnceng-public/public/_build/results?buildId=560509)|dotnet/runtime|LLVM AOT compile CoreCLR tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/560509/logs/32)|dotnet/runtime#92057|

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[2376960](https://dev.azure.com/dnceng/internal/_build/results?buildId=2376960)|dotnet-runtime|[x64.micro_mono.net9.0.Partition9.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2376960&view=ms.vss-test-web.build-test-results-tab&runId=53059281&resultId=100030)||
|[2376359](https://dev.azure.com/dnceng/internal/_build/results?buildId=2376359)|dotnet-runtime|[x64.micro_mono.net9.0.Partition9.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2376359&view=ms.vss-test-web.build-test-results-tab&runId=53054393&resultId=100030)||
|[2376039](https://dev.azure.com/dnceng/internal/_build/results?buildId=2376039)|dotnet-runtime|[x64.micro_mono.net9.0.Partition9.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2376039&view=ms.vss-test-web.build-test-results-tab&runId=53051577&resultId=100030)||
|[2375871](https://dev.azure.com/dnceng/internal/_build/results?buildId=2375871)|dotnet-runtime|[x64.micro_mono.net9.0.Partition9.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2375871&view=ms.vss-test-web.build-test-results-tab&runId=53049895&resultId=100030)||
|[2375785](https://dev.azure.com/dnceng/internal/_build/results?buildId=2375785)|dotnet-runtime|[release.Partition9.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2375785&view=ms.vss-test-web.build-test-results-tab&runId=53049163&resultId=100030)||
|[2375653](https://dev.azure.com/dnceng/internal/_build/results?buildId=2375653)|dotnet-runtime|[x64.micro_mono.net9.0.Partition9.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2375653&view=ms.vss-test-web.build-test-results-tab&runId=53047833&resultId=100030)||
|[2375545](https://dev.azure.com/dnceng/internal/_build/results?buildId=2375545)|dotnet-runtime|[release.Partition9.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2375545&view=ms.vss-test-web.build-test-results-tab&runId=53047117&resultId=100030)||
|[2375475](https://dev.azure.com/dnceng/internal/_build/results?buildId=2375475)|dotnet-runtime|[release.Partition9.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2375475&view=ms.vss-test-web.build-test-results-tab&runId=53047011&resultId=100030)||
|[2375394](https://dev.azure.com/dnceng/internal/_build/results?buildId=2375394)|dotnet-runtime|[x64.micro_mono.net9.0.Partition9.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2375394&view=ms.vss-test-web.build-test-results-tab&runId=53046623&resultId=100030)||
|[2375312](https://dev.azure.com/dnceng/internal/_build/results?buildId=2375312)|dotnet-runtime|[x64.micro_mono.net9.0.Partition9.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2375312&view=ms.vss-test-web.build-test-results-tab&runId=53046221&resultId=100030)||
|[2375166](https://dev.azure.com/dnceng/internal/_build/results?buildId=2375166)|dotnet-runtime|[release.Partition9.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2375166&view=ms.vss-test-web.build-test-results-tab&runId=53045221&resultId=100030)||
|[2375008](https://dev.azure.com/dnceng/internal/_build/results?buildId=2375008)|dotnet-runtime|[release.Partition9.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2375008&view=ms.vss-test-web.build-test-results-tab&runId=53044617&resultId=100030)||
|[2374634](https://dev.azure.com/dnceng/internal/_build/results?buildId=2374634)|dotnet-runtime|[release.Partition9.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2374634&view=ms.vss-test-web.build-test-results-tab&runId=53042191&resultId=100030)||
|[2374376](https://dev.azure.com/dnceng/internal/_build/results?buildId=2374376)|dotnet-runtime|[release.Partition9.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2374376&view=ms.vss-test-web.build-test-results-tab&runId=53040887&resultId=100030)||
|[2374218](https://dev.azure.com/dnceng/internal/_build/results?buildId=2374218)|dotnet-runtime|[x64.micro_mono.net9.0.Partition9.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2374218&view=ms.vss-test-web.build-test-results-tab&runId=53039703&resultId=100030)||
|[2373987](https://dev.azure.com/dnceng/internal/_build/results?buildId=2373987)|dotnet-runtime|[x64.micro_mono.net9.0.Partition9.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2373987&view=ms.vss-test-web.build-test-results-tab&runId=53038781&resultId=100030)||
|[2373755](https://dev.azure.com/dnceng/internal/_build/results?buildId=2373755)|dotnet-runtime|[release.Partition9.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2373755&view=ms.vss-test-web.build-test-results-tab&runId=53036207&resultId=100030)||
|[2373510](https://dev.azure.com/dnceng/internal/_build/results?buildId=2373510)|dotnet-runtime|[release.Partition9.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2373510&view=ms.vss-test-web.build-test-results-tab&runId=53034859&resultId=100030)||
|[2373349](https://dev.azure.com/dnceng/internal/_build/results?buildId=2373349)|dotnet-runtime|[x64.micro_mono.net9.0.Partition9.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2373349&view=ms.vss-test-web.build-test-results-tab&runId=53033819&resultId=100030)||
|[2373235](https://dev.azure.com/dnceng/internal/_build/results?buildId=2373235)|dotnet-runtime|[x64.micro_mono.net9.0.Partition9.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2373235&view=ms.vss-test-web.build-test-results-tab&runId=53032999&resultId=100030)||
|[2372973](https://dev.azure.com/dnceng/internal/_build/results?buildId=2372973)|dotnet-runtime|[release.Partition9.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2372973&view=ms.vss-test-web.build-test-results-tab&runId=53030799&resultId=100030)||
|[2372666](https://dev.azure.com/dnceng/internal/_build/results?buildId=2372666)|dotnet-runtime|[release.Partition9.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2372666&view=ms.vss-test-web.build-test-results-tab&runId=53028641&resultId=100030)||
|[557221](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557221)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.Serialization.Xml.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557221&view=ms.vss-test-web.build-test-results-tab&runId=13280178&resultId=158455)|dotnet/runtime#98093|
|[557210](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557210)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.Serialization.Xml.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557210&view=ms.vss-test-web.build-test-results-tab&runId=13279422&resultId=163992)|dotnet/runtime#98087|
|[556904](https://dev.azure.com/dnceng-public/public/_build/results?buildId=556904)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.Serialization.Xml.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=556904&view=ms.vss-test-web.build-test-results-tab&runId=13273312&resultId=163992)|dotnet/runtime#98087|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|35|

**Comment by vargaz** [comment]
Should be fixed by:
https://github.com/dotnet/runtime/pull/98114

**Comment by fanyang-mono** [comment]
This is not a WASM only issue. It is also seen on desktop linux. See logs here: https://dev.azure.com/dnceng-public/public/_build/results?buildId=560509&view=logs&j=d25dc2c0-518b-5583-f661-5ac905106679&t=47cb0142-4d6b-5edf-a0a8-cf81fa3f7e05 @jkurdek Could you take a look?

**Comment by jkurdek** [comment]
I am aware of the regression on llvm linux x64. Looking into it.

**Comment by pavelsavara** [comment]
Could we close this ?
