### ISSUE TITLE
[RyuJit/R2R/JitStress=1] JIT\Regression\JitBlue\DevDiv_255294 fails with timeout.

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#9810]
JIT Compilation time report:
  Compiled 2 methods.
  Compiled 810553 bytecodes total (810534 max, 405276.50 avg).
  Time: total: 71636680.662 Mcycles/21027407.414 ms

So the test takes 5 hours to crossgen with JitStress=1.
[arm ci example](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_r2r_jitstress1_tst_prtest/18/), [amd64 ci example.](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_r2r_jitstress1/lastFailedBuild/testReport/).

The fix is known, but it requires not a one-line change.

category:correctness
theme:testing
skill-level:intermediate
cost:medium

**Comment by sandreenko** [comment]
The issue is similar to #8034 that happens with the same artificial test. The problem is in our reachability algorithm that could be quadratic (in time and memory) in the worst case because we don't use predecessors/successors lists there and iterate all blocks after each change.

If I remember correctly I had a change that was fixing the algorithm by keeping a set of changing blocks. However, it was requiring pred lists that were not available at that moment, and building them was leading to a worse TP in general but was fixing this artificial test failure. 

Another problem was in the discrepancy between our existing pred list and methods that are used for successors in the reachability algorithm, one ignores EH edges and the other does not.

**Comment by BruceForstall** [comment]
Closing this in favor of https://github.com/dotnet/runtime/issues/44341
