### ISSUE TITLE
New analyzer: Do not call ToList on variable which is already a List

### ISSUE THREAD

**Issue by DanAvni** [dotnet/runtime#98146]
I have the code below, The function foo returns a list of strings. Calling ToList on the returned value is redundant (except for a case that for some reason I want to replace the List instance with a new one). The same applies to other Linq ToX functions and their respective types (Array, HashSet, etc). 

Please add a new analyzer and a fix for that
```
void Main()
{
	List<string> fooList = foo().ToList(); //ToList is redundant
}
List<string> foo(){
	List<string> result = new List<string>();
	result.Add("bar");
	return result;
}
```

**Comment by En3Tho** [comment]
What if you need a copy? This will lead to a large amount of false positives in such cases

**Comment by eiriktsarpalis** [comment]
What @En3Tho said. There are valid use cases for this pattern.
