### ISSUE TITLE
[API Proposal]: LD_PRELOAD equivalent 

### ISSUE THREAD

**Issue by whoaskedfrfr** [dotnet/runtime#98157]
### Background and motivation

It would be awesome if there was a way to override the loaded modules with custom written ones.

### API Proposal

N/A

### API Usage

`CLR_PRELOAD=/tmp/my_impl/System.Text.Json.dll dotnet run`

**Comment by agocke** [comment]
I believe [startup hooks](https://github.com/dotnet/runtime/blob/main/docs/design/features/host-startup-hook.md) solve this problem
