### ISSUE TITLE
[API Proposal]: An official way to determine whether the given value is JIT-time constant or not

### ISSUE THREAD

**Issue by MineCake147E** [dotnet/runtime#98153]
### Background and motivation

```csharp
[MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
public static bool IsConstant(int value)
    => Vector128.CreateScalarUnsafe(value - ~value).GetElement(1) != 0;
```
```asm
    L0000: vzeroupper
    L0003: mov eax, ecx
    L0005: not eax
    L0007: sub ecx, eax
    L0009: vmovd xmm0, ecx
    L000d: vpextrd eax, xmm0, 1
    L0013: test eax, eax
    L0015: setne al
    L0018: movzx eax, al
    L001b: ret
```
The code above currently allows me to guess whether the `value` is a JIT-time constant in x86-64 environments.
The `Vector128.CreateScalarUnsafe(value)` usually does the same thing with `Vector128.CreateScalar(value)` (which is `vmovd xmm*, r*d`) which clears all upper elements with 0, but it does `Vector128.Create(value)` which broadcasts the `value`, when the `value` is a constant.
The `value - ~value` is guaranteed to be nonzero, as [LLVM says](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:2,endLineNumber:6,positionColumn:2,positionLineNumber:6,selectionStartColumn:2,selectionStartLineNumber:6,startColumn:2,startLineNumber:6),source:'%23include+%3Ccstdint%3E%0A%0Abool+A(uint64_t+v)%0A%7B%0A++++return+(v+-+~v)+!!%3D+0%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:49.10775875962996,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:clang_trunk,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'1',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-Ofast+-std%3Dc%2B%2B2c+-march%3Dsapphirerapids',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+clang+(trunk)+(Editor+%231)',t:'0')),k:50.892241240370055,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4), and it obviously differs by `value`.
By checking whether the second element is nonzero or not, it returns `true` when the `value` is a constant, `false` otherwise.
Inlining the `IsConstant(constant)` simply boils down to `mov eax, 1` as shown [here](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8lAbhvqfIDoARAS2wBzAHYRcGfmFztajZtwAy/EQEdZnBQDkArvhhQpMjvJ4AlHSMn7uAYQj4ADvwA2BgMoGAblJjG5XNwAKjAIGBqmAKwRgRZW/DYAklYGEI6eUD5gfjEKcdYw3MkYhiK4RrnmlgVFVqXl0twAGgAcSDHuABbYUI6K2MDc+QkwGgDMXEhMpAwA+vPzAILLyzQA3jQMWwwA2gCyMBidEAAmiU4uABQHR6fnji4A8o6SEGXci0JCsLjlXjDJFwqFRCBiEBg3Y5nC7PV7vT7fPx/GCwhL8ABe2DhAEoALqbbbECbMKbACAQFwMRK4exlDDYKyXFQYBhebAuHQwbEE7bbAC8AD4GAA1GBgDDQcikFp2WBYmDuMDsnoAVTK2AAZjBLmyOTAGHAGAA/XWc7HcADihwAom59IzyNiGABCPkMOiyXk8pjE8ik8mUgBCpEu3OovN5gqpNLeEgZGEudGxnsJvv9FIYthDYYj/KF1NpccZZgZJwc3C6PRgJ24WlCCexyZoAF8gA===).

Such behavior is really useful when I deal with some SIMD optimization, as some instructions only take constant value.
It also helps me to replicate something like what [System.Buffer.Memmove](https://github.com/dotnet/runtime/blob/a78ddcc5ce0d4af6d2f790d2041dae3ff318e122/src/libraries/System.Private.CoreLib/src/System/Buffer.cs#L132) does for small constant lengths, without modifying the CoreCLR.
But it's an undefined behavior, and I'm not sure if it works with ARM-based processors, so I propose the APIs below for official support.

### API Proposal

```csharp
namespace System.Runtime.CompilerServices;

public static class Unsafe
{
    public static bool IsConstant<T>(T value) where T : unmanaged;
}
```

### API Usage

```csharp
// The method takes `[ConstantExpected] int index` and `Vector512<ushort> zmm2` as parameter
if (Unsafe.IsConstant(index))
{
    // some processing that needs the index to be a constant value
    return zmm2.GetElement(index);
}
// some processing that don't need the index to be a constant value
return Avx512BW.PermuteVar32x16(zmm2, Vector512.CreateScalarUnsafe((ushort)index)).GetElement(0);
```

### Alternative Designs

* There may be a better place for `IsConstant` to be.
* There may be a better name for `IsConstant`.

### Risks

None

**Comment by EgorBo** [comment]
You api usage example sounds like something JIT should optimize itself when index is constant without extra help? Do you have other examples where this could be useful?

We already have an internal API for it called `RuntimeHelpers.IsKnownConstant` but I am not sure it should be exposed in public since it's quite fragile, e.g. https://github.com/dotnet/runtime/issues/89379 we'd prefer improving JIT rather than exposing low-level hacky APIs to assist it.

**Comment by colejohnson66** [comment]
Just my two cents: "is known constant" is a weird method name. I get what it's implying: not all constants are "known" when inlining occurs, but it's one you have to think about. Should an API be exposed, I'd vote for "is *inlined* constant".

**Comment by tannergooding** [comment]
Moved to the right area, but noting this is `blocked` on the JIT team signing off on it being a good thing to expose.

As @EgorBo has pointed out, there are limitations with this and there are many things it won't catch or handle. That being said, it could still be useful in the same ways it's been useful to us in the BCL.

@jkotas may also have opinions on this.

**Comment by jkotas** [comment]
We had this method as internal API to experiment with for number of years, it has proven to be difficult to use. It is used in 6 places total currently, and 2 of those are being deleted in #98186.

**Comment by jkotas** [comment]
> System.Buffer.Memmove does for small constant lengths

Egor tried to optimize Memmove using this API in #83638, but it was too difficult to make it work. The intrinsic JIT expansion was implemented instead.

**Comment by EgorBo** [comment]
Right, here is that fully managed unrolling (for String.Equals and String.StartsWith): https://github.com/dotnet/runtime/pull/64821/files
1) Inliner's budget quickly runs out
2) You rely on all opts being folded in the end which could be fragile
3) IsKnownConstant increases IL size and JIT currently can't precisely predict it will be able to fold branches like `if (IsKnownConstant(str) && str.Length == 42)`

But it was a funny experiment 🙂

**Comment by MichalPetryka** [comment]
I'd guess one reasonable use case would be for checking inputs in SIMD code that then dispatches either to fast paths with `ConstantExpected` or slower paths for variable data.

**Comment by tannergooding** [comment]
Going to close this based on the above.

Getting targeted JIT improvements around inlining, constant propagation, and potentially DPGO, are likely to be better long goals; particularly given the extreme limitations that the API in question has.
