### ISSUE TITLE
PortableSourceBuild failures in runtime-dev-innerloop

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#98160]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=558205
Build error leg or test failing: Build / linux-x64 Release PortableSourceBuild / Build
Pull request: https://github.com/dotnet/runtime/pull/98143

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "SourceBuildArcadeBuild.targets",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

Looks like something's broken in InstallWorkloadFromArtifacts.cs:
```
  /__w/1/s/artifacts/sb/src/src/tasks/WorkloadBuildTasks/InstallWorkloadFromArtifacts.cs(61,38): error CS8795: Partial method 'InstallWorkloadFromArtifacts.bandVersionRegex()' must have an implementation part because it has accessibility modifiers. [/__w/1/s/artifacts/sb/src/src/tasks/WorkloadBuildTasks/WorkloadBuildTasks.csproj::TargetFramework=net8.0]
      0 Warning(s)
      1 Error(s)
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=558205
**Error message validated:** `[SourceBuildArcadeBuild.targets`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 2/8/2024 2:50:14 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[558752](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558752)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/558752/logs/41)|dotnet/runtime#98131|
|[2373593](https://dev.azure.com/dnceng/internal/_build/results?buildId=2373593)|dotnet-runtime|Build|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2373593/logs/970)||
|[558620](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558620)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/558620/logs/41)|dotnet/runtime#98156|
|[2373524](https://dev.azure.com/dnceng/internal/_build/results?buildId=2373524)|dotnet-runtime|Build|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2373524/logs/968)||
|[558601](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558601)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/558601/logs/41)|dotnet/runtime#98155|
|[558576](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558576)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/558576/logs/41)|dotnet/runtime#97508|
|[558570](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558570)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/558570/logs/41)|dotnet/runtime#97766|
|[558543](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558543)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/558543/logs/49)|dotnet/runtime#98152|
|[558407](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558407)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/558407/logs/49)|dotnet/runtime#97447|
|[557931](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557931)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557931/logs/116)|dotnet/runtime#98113|
|[558048](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558048)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/558048/logs/116)|dotnet/runtime#97953|
|[558049](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558049)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/558049/logs/116)|dotnet/runtime#97953|
|[558359](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558359)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/558359/logs/49)|dotnet/runtime#98148|
|[558320](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558320)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/558320/logs/546)||
|[558309](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558309)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/558309/logs/49)|dotnet/runtime#98144|
|[558291](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558291)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/558291/logs/49)|dotnet/runtime#98007|
|[558285](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558285)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/558285/logs/49)|dotnet/runtime#98016|
|[558257](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558257)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/558257/logs/49)|dotnet/runtime#98016|
|[558240](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558240)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/558240/logs/49)|dotnet/runtime#98133|
|[558235](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558235)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/558235/logs/49)|dotnet/runtime#98133|
|[558230](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558230)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/558230/logs/49)|dotnet/runtime#98131|
|[558208](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558208)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/558208/logs/49)|dotnet/runtime#98084|
|[558205](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558205)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/558205/logs/41)|dotnet/runtime#98143|
|[558199](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558199)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/558199/logs/44)|dotnet/runtime#98142|
|[558194](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558194)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/558194/logs/49)|dotnet/runtime#97835|
|[558189](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558189)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/558189/logs/49)|dotnet/runtime#98125|
|[558146](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558146)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/558146/logs/41)|dotnet/runtime#98129|
|[558107](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558107)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/558107/logs/41)|dotnet/runtime#97432|
|[558080](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558080)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/558080/logs/41)|dotnet/runtime#98133|
|[558065](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558065)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/558065/logs/41)|dotnet/runtime#98141|
|[558061](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558061)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/558061/logs/41)|dotnet/runtime#97356|
|[558041](https://dev.azure.com/dnceng-public/public/_build/results?buildId=558041)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/558041/logs/41)|dotnet/runtime#98135|
|[557607](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557607)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557607/logs/3239)||
|[557817](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557817)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557817/logs/131)|dotnet/runtime#98125|
|[557993](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557993)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557993/logs/41)|dotnet/runtime#98007|
|[557987](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557987)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557987/logs/41)|dotnet/runtime#98140|
|[557969](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557969)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557969/logs/41)|dotnet/runtime#97350|
|[557870](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557870)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557870/logs/117)|dotnet/runtime#98134|
|[557958](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557958)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557958/logs/41)|dotnet/runtime#98133|
|[557938](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557938)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557938/logs/41)|dotnet/runtime#98070|
|[557925](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557925)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557925/logs/41)|dotnet/runtime#98054|
|[557910](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557910)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557910/logs/41)|dotnet/runtime#98136|
|[557907](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557907)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557907/logs/41)|dotnet/runtime#98135|
|[557867](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557867)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557867/logs/41)|dotnet/runtime#98134|
|[557861](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557861)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557861/logs/41)|dotnet/runtime#98133|
|[557850](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557850)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557850/logs/41)|dotnet/runtime#98127|
|[557842](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557842)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557842/logs/41)|dotnet/runtime#98077|
|[557846](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557846)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557846/logs/41)|dotnet/runtime#98084|
|[557833](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557833)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557833/logs/41)|dotnet/runtime#98131|
|[557811](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557811)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557811/logs/49)|dotnet/runtime#97784|
|[557814](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557814)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557814/logs/49)|dotnet/runtime#97432|
|[557779](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557779)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557779/logs/52)|dotnet/runtime#98129|
|[557773](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557773)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557773/logs/49)|dotnet/runtime#98128|
|[557679](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557679)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557679/logs/49)|dotnet/runtime#97432|
|[557667](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557667)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557667/logs/49)|dotnet/runtime#98077|
|[557663](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557663)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557663/logs/49)|dotnet/runtime#98120|
|[557659](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557659)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557659/logs/50)|dotnet/runtime#98007|
|[557630](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557630)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557630/logs/49)|dotnet/runtime#98015|
|[557620](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557620)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557620/logs/49)|dotnet/runtime#98070|
|[557615](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557615)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557615/logs/49)|dotnet/runtime#98063|
|[557595](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557595)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557595/logs/49)|dotnet/runtime#98113|
|[557583](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557583)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557583/logs/49)|dotnet/runtime#96806|
|[557560](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557560)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557560/logs/49)|dotnet/runtime#97465|
|[557542](https://dev.azure.com/dnceng-public/public/_build/results?buildId=557542)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/557542/logs/49)|dotnet/runtime#97935|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|64|64|64|

**Comment by ViktorHofer** [comment]
Got fixed with https://github.com/dotnet/runtime/issues/98130
