### ISSUE TITLE
[API Proposal]:Replace method CountBy

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#98169]
### Background and motivation

I suggest replacing the CountBy method with an extension method GetOptions for the IGrouping interface. The class that implements the IGrouping interface have a Count property.
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq/src/System/Linq/Grouping.cs#L187

https://sharplab.io/#gist:82115629152af3807e7d054c3f1d1dd7

### API Proposal

```csharp
static class ExtMethod{
       public static Options GetOptions<TKey,TSource>(this IGrouping<TKey, TSource> gr){
           
           return new Options(){ Count = gr.Count()};//The Count method can be replaced with a method of the Grouping<TKey, TElement> class.

       } 
       
}
struct Options{
    public int Count{set;get;}
}
```

### API Usage

```csharp
var res = Enumerable.Range(0,10).GroupBy(a=>a);
foreach(var obj in res){
    Console.WriteLine($"{obj.GetOptions().Count}");
}
```

**Comment by Mr0N** [comment]
> What is the goal of this suggestion? Improved performance?

In my opinion, adding another method for counting the number of groups is excessive.

**Comment by colejohnson66** [comment]
If your goal is to just get the count of elements in each group, that logic already exists (as you've shown). It's just hidden behind an explicitly implemented interface member. So either use the LINQ `Count()` method, or just work on the interface.

```cs
// using LINQ `Count()`
foreach (int groupLength in Enumerable.Range(0, 10).GroupBy(x => x).Select(x => x.Count()))
    Console.WriteLine(groupLength);

// or

// using the `Count` property
foreach (IGrouping<int, int> group in Enumerable.Range(0, 10).GroupBy(x => x))
    Console.WriteLine(((ICollection<int>)group).Count);
```

**Comment by eiriktsarpalis** [comment]
The point of the `CountBy` and `AggregateBy` methods is to avoid the allocation of `IGrouping` allocations (each of which defines its own buffer of grouped elements).
