### ISSUE TITLE
[API Proposal]: DistinctBy for IAsyncEnumerable

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#98172]
### Background and motivation

IEnumerable and IAsyncEnumerable are sisters.  If something works for one, it should work for the other.

```DistinctBy``` and other ```_By``` methods are currently only implemented for IEnumerable.

### API Proposal

Not sure.

### API Usage

```csharp

var Query = GetAsyncEnumerable();
var Values = Query.DistinctBy(x => x.Id);

```

**Comment by stephentoub** [comment]
System.Linq.Async isn't in this repo:
https://github.com/dotnet/reactive/tree/main/Ix.NET/Source/System.Linq.Async
