### ISSUE TITLE
Memory stolen from sql server when using CLR SQLDataReader

### ISSUE THREAD

**Issue by erickcruzf** [dotnet/runtime#98181]
### Description

I got a function implemented on a CLR using .Net Framework 4.8, this function is called millions of times a day, and each time it's called 1000 times, it acummulates around 80kb permanently on MEMORYCLERK_SQLGENERAL > memory obj MEMOBJ_GLOBALPMO of sqlserver 2022(16.0.1000.6) database.

I can't find a solution to this memory leak, can anyone help me, on what i'm doing wrong? This goes on until it goes above 16gigabytes of stolen memory and starts timing out queries on the sql server. The GC seems to be working, but this memory is outside the dll? When I drop the dll the memory is still stolen from the server.

### Reproduction Steps

I'm using this tool to reproduce it
![image](https://github.com/dotnet/SqlClient/assets/42284872/2a44f4b0-cb12-4749-9d3b-63f66c7009ad)

if I put 1000 threads almost 80mb is allocated and are forever stolen, the only solution to this is to do a full restart on the server machine. I can see the memory go down, but only about 20% of what is alocated is being fred. From the day to day this memory keep as it is, growing a little on each use.

```c#
[SqlFunction(
    FillRowMethodName = "FillRow_Test",
    TableDefinition = @"Origem tinyint,
                        Lancamento int",
    DataAccess = DataAccessKind.Read,
    SystemDataAccess = SystemDataAccessKind.Read
)]
public static IEnumerable Fn_Test()
{
    return TestFunction();
}


  private static IEnumerable TestFunction()
  {
      using (var conn = new SqlConnection("context connection=true"))
      {
          conn.Open();

          using (var sql = new SqlCommand
          {
              Connection = conn,
              CommandTimeout = 0,

              CommandText = "SELECT l.Origem, l.Lancamento FROM dbo.Lancamentos l WHERE l.Origem = 1 AND l.Lancamento = 300" //Any Query
          })
          {
              using (var reader = sql.ExecuteReader())
              {
                  if (reader.HasRows)
                  {
                      reader.Read();
                      _ = reader.GetByte(0);
                      _ = reader.GetInt32(1);
                  }
              }
          }
      }

        return null;
    }
    
    protected static void FillRow_Test(object obj,
                                           out byte origem,
                                           out int lancamento)
{

    var acrescimos = (Acrescimo)obj;

    origem = acrescimos.Origem;
    lancamento = acrescimos.Lancamento;
}
```
Queries
```sql
SELECT TOP(10) [type] AS [ClerkType],
SUM(pages_kb) / 1024 AS [SizeMb],
SUM(pages_kb) AS [SizeKb]
FROM sys.dm_os_memory_clerks WITH (NOLOCK)
GROUP BY [type]
ORDER BY SUM(pages_kb) DESC

SELECT top 5 omo.type, sum(omo.pages_in_bytes)/1024/1024 as pages_in_bytes , omo.partition_type_desc, omo.memory_node_id
FROM sys.dm_os_memory_objects omo
JOIN sys.dm_os_memory_clerks omc
ON omo.page_allocator_address = omc.page_allocator_address
WHERE omc.type = 'MEMORYCLERK_SQLGENERAL'
group by omo.type, partition_type_desc ,omo.memory_node_id
ORDER BY pages_in_bytes DESC;

create assembly [CLR]
from 'C:\Users\...\CLR.dll'
with permission_set = unsafe;
go

CREATE FUNCTION [dbo].[fn_Teste]
    ()
RETURNS  TABLE 
        (
            Origem tinyint, 
            Lancamento int
        ) WITH EXECUTE AS CALLER
AS 
    EXTERNAL NAME [CLR].[Fn_Test]
GO
ALTER AUTHORIZATION ON [dbo].[fn_Teste] TO  SCHEMA OWNER 
GO
```

![image](https://github.com/dotnet/SqlClient/assets/42284872/7d54454d-c058-4a08-917f-3b96bbdb0ab5)

### Expected behavior

The memory shouldn't stack forever.

### Actual behavior

Memory is going up forever taking down resources of sql server

### Regression?

The problem only happens on ssms standard, does not happen on ssms express 2019 (15.0.4153), so we only detected this problem in prod.

### Known Workarounds

none

### Configuration

.NET Framework 4.8
Windows 10 x86

**Comment by jkotas** [comment]
@erickcruzf This repo is dedicated to .NET Core/5+.

We track .NET Framework issues via Visual Studio dev community. If you believe that this is issue in .NET Framework, please report it at https://developercommunity.visualstudio.com/home
