### ISSUE TITLE
[Perf] Investigate bimodal swings of BenchI/Fib

### ISSUE THREAD

**Issue by michellemcdaniel** [dotnet/runtime#9818]
We swing between 590ms and 546ms on master

category:correctness
theme:benchmarks
skill-level:intermediate
cost:small

**Comment by kunalspathak** [comment]
The benchmark is unstable and looks like duration remains stable, the overhead invocation swings. 

windows/x64:

<img width="749" alt="image" src="https://user-images.githubusercontent.com/12488060/209053089-f7b36a20-1381-43f2-8a7e-74a74348b032.png">

<img width="1821" alt="image" src="https://user-images.githubusercontent.com/12488060/209053290-41c3e77c-0805-43ca-ac3a-9dea36f18cec.png">

<img width="1700" alt="image" src="https://user-images.githubusercontent.com/12488060/209053326-deb64df3-f55c-4420-9d8b-5001e706ed9f.png">

<img width="1478" alt="image" src="https://user-images.githubusercontent.com/12488060/209053395-a0cf2903-25e7-4fae-ad6a-468ee960caa0.png">


Linux/x64:

<img width="728" alt="image" src="https://user-images.githubusercontent.com/12488060/209053134-4dff2375-11cc-4c53-abb0-5df018369f60.png">
