### ISSUE TITLE
Application crash when calling a function in Linux

### ISSUE THREAD

**Issue by alexdrl** [dotnet/runtime#982]
Hello, I am getting an application crash when calling a Library with PInvoke in Linux.

The library is https://github.com/alexdrl/lkh and is made using CMake.

The .NET 3.0 code is this https://github.com/alexdrl/ReproNetCore30. The library also builds on windows, and the calling .NET code works as expected in the TSP and TSP2 files.

I have tried to remove all the parameters from the library entrypoint with no luck... 
https://github.com/alexdrl/lkh/blob/423a05253b8394150546dea016cea750b54d9fcc/SRC/LKHmain.c#L165 calling from the TSP3 code:
https://github.com/alexdrl/ReproNetCore30/blob/9d13e9767d1d9f5c54ec94b00755ab01b332d296/TSP3.cs#L159

If I build a C entrypoint https://github.com/alexdrl/lkh/blob/adelrincon_cmake_windows/TEST/testTsp.c and start this entrypoint as a process, the StandardOutput is shown correctly, so the library works on Linux...

Any input?

**Comment by jkotas** [comment]
cc @jkoritzinsky

**Comment by AaronRobinsonMSFT** [comment]
@alexdrl If you could narrow down where the crash is occurring that would be helpful. Is this crashing at invocation, during the call, or during the return? Simple `printf()` style output at the beginning and end of the native function would help us to narrow down where the problem might be.

**Comment by alexdrl** [comment]
@AaronRobinsonMSFT I have tested this with printf and I have "solved" the problem. 

The application crashed in this line https://github.com/alexdrl/lkh/blob/423a05253b8394150546dea016cea750b54d9fcc/SRC/LKHmain.c#L21
which is defined here https://github.com/alexdrl/lkh/blob/423a05253b8394150546dea016cea750b54d9fcc/SRC/LKH.h#L357.

I changed the code in the header file to a int pointer reference and it works correctly.

Why the initial code works on the C runtime and not in the CLR?

**Comment by AaronRobinsonMSFT** [comment]
>Why the initial code works on the C runtime and not in the CLR?

@alexdrl That is a good question. I am not entirely sure without see the crash itself. If you can collect a core dump it should be possible to see what kind of failure is occurring and then determine why. This could be related to how we are loading the library. As an experiment try loading the library from another binary via [`dlopen`](https://linux.die.net/man/3/dlopen) and then get the entry point using [`dlsym`](https://linux.die.net/man/3/dlsym). Call the entry point through the returned function pointer and see if the same behavior occurs - this is basically how the CLR is performing a P/Invoke.

**Comment by alexdrl** [comment]
@AaronRobinsonMSFT Yes, I can repro this with dlopen, without much hassle.

See https://github.com/alexdrl/lkh/blob/adelrincon_cmake_windows/TEST/testDlopen.c

To repro this, the code in SRC must be built in this commit https://github.com/alexdrl/lkh/commit/2ffe3fff5562b90bdb2ed30c8224cef749cce512. If the code is built in the adelrincon_cmake_windows branch, the dlopen and the call works OK.

I do not have a lot of skill in C and compilers, but it is very curious that in MSVC this works and in GCC it does not at it seems an undefined behaviour.

**Comment by AaronRobinsonMSFT** [comment]
@alexdrl I've not gotten a chance to investigate this but given it isn't technically a specific .NET interop issue I am going to close this. Please let us know if you feel this is a blocking issue for consuming .NET.
