### ISSUE TITLE
double.Cos and double.SinCos can produce very different results

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#98204]
Repro:
```C#
double d = 1e18;
double cos1 = double.Cos(d);
(_, double cos2) = double.SinCos(d);
Console.WriteLine(cos1);
Console.WriteLine(cos2);
```
outputs:
```
0.11837199021871073
-0.9929693207404051
```
on .NET 8

**Comment by tannergooding** [comment]
SinCos is returning sin for both values. Looks to repro for debug and release

**Comment by tannergooding** [comment]
Looks to be Windows specific as well.

**Comment by tannergooding** [comment]
Looks to be a bug in MSVC for `float_control(precise, off)` (that is `/fp:fast`) which is used in the ecall wrappers. It repros in a standalone C++ application.

We're generating:
```asm
mov         qword ptr [rsp+8],rbx  
push        rdi  
sub         rsp,20h  
movaps      xmm1,xmm0  
mov         rdi,r8  
xorps       xmm0,xmm0  
mov         rbx,rdx  
movsd       xmm0,xmm1  
call        __libm_sse2_sincos_ (07FF705521F90h)  
movsd       mmword ptr [rbx],xmm0  
mov         rbx,qword ptr [rsp+30h]  
shufpd      xmm0,xmm0,1  
movsd       mmword ptr [rdi],xmm0  
add         rsp,20h  
pop         rdi  
ret  
```

So it looks like the expectation is that `__libm_sse2_sincos` takes in `value` in `xmm0` (these matches the expecting calling convention) and then returns the result in `xmm0[0]` and `xmm0[1]`. However, `sin` is in both elements instead.

The API is internally calling `__vdecl_sin2` which dispatches to `__sse4_sin2@@16`. The bug looks to be in here as it is not setting the results correctly.

This also explains why it reproduces on .NET 6, as we are dynamically invoking the C runtime and the underlying implementation has changed in the past couple years (it appears we are using SVML in some places now).

**Comment by tannergooding** [comment]
There is indeed a `__vdecl_sincos2` that should have been the target instead, looks to be an explicit bug in the `__libm_sse2_sincos_` helper.

**Comment by tannergooding** [comment]
Just copy/pasting my analysis from the PR

> It looks like __libm_sse2_sincos is trying to rely on the fact that sin(x + PI / 2) == cos(x) and so adjusts the second input by that much. This is correct for infinitely precise arithmetic, but for floating-point means that cos is less accurate than it should be for regular values and will not work at all for large values due to the increasing gap between which numbers are representable (it breaks down entirely around 1e16, but starts showing issues far earlier).
>
> Given that its just calling into SVML and SVML provides a dedicated __vdecl_sincos2, that should really be getting used instead.
> 
> We missed this because we were testing normal input ranges and not testing anything quite so large, effectively relying on the fact that the underlying libm implementation is expected to be largely correct, and that we simply want to minimally validate the bindings are accurate and that it matches any IEEE 754 required behavior (such as sin(+0) == +0 and sin(-0) == -0, with no exception)

**Comment by tannergooding** [comment]
The MSVC bug has been filed here: https://developercommunity.visualstudio.com/t/MSVCs-sincos-implementation-is-incorrec/10582378
