### ISSUE TITLE
Test duration reported by `dotnet test` is inaccurate for xUnit async tests, but only at certain verbosity levels

### ISSUE THREAD

**Issue by rmunn** [dotnet/runtime#98205]
### Description

When running a series of asynchronous xUnit tests with `dotnet test`, the time elapsed reported at the end of `dotnet test` is wrong. It appears to be failing to measure the time taken by the first test, and only measuring the time elapsed starting with the second test to run.

### Reproduction Steps

Clone https://github.com/rmunn/dotnet-test-xunit-timing-repro and run `dotnet test`. Note the time elapsed is the time taken by the *second* test to run.

Then try adding a third and fourth test, each waiting for a different number of seconds. Note that the time elapsed is the total time taken up by all tests, minus the time the first test spends waiting.

Run `dotnet test /v:q`. Bug still occurs.

Run `dotnet test /v:n`. Bug still occurs.

Run `dotnet test --logger "console;verbosity=quiet"`. Bug still occurs.

Run `dotnet test --logger "console;verbosity=normal"`. Bug does **NOT** occur (!). Total time elapsed is correct.

### Expected behavior

The time elapsed reported by `dotnet test` would include all tests.

### Actual behavior

The first test to run asynchronously does not have its time recorded in the time elapsed that `dotnet test` reports, **except** when you run with the option `--logger "console;verbosity=normal"`. That makes the time elapsed correct, while `--logger "console;verbosity=quiet"` still exhibits the bug.

### Regression?

I remember seeing a bug report several years ago (when the latest version of .Net Core was 2.0 or 2.1) about incorrect time reported by dotnet test, but I can't find it now. However, this makes me think that this is not a regression.

### Known Workarounds

Running tests with MSTest or NUnit do not exhibit this behavior, so one workaround could, in theory, be to switch from xUnit to NUnit or MSTest. This is unlikely to be practical in any real project with a non-trivial number of tests already written, though.

Running with `--logger "console;verbosity=normal"` reports correct time elapsed, where `--logger "console;verbosity=quiet"` still reports the wrong time. Both `/v:n` and `/v:q`, in the absence of a `--logger` parameter, still report the wrong time.

### Configuration

Linux Mint 21.3 (based on Ubuntu 22.04), running dotnet 8.0. I haven't yet tried this on other machines, so I don't know if this behavior is Linux-specific or not.

<details><summary>Output of dotnet --info:</summary>

```
.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.ba313bcd

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  21.3
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.101/

.NET workloads installed:
 Workload version: 8.0.100-manifests.ba313bcd
 [android]
   Installation Source: SDK 8.0.100
   Manifest Version:    34.0.52/8.0.100
   Manifest Path:       /usr/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.android/34.0.52/WorkloadManifest.json
   Install Type:        FileBased

 [maui-android]
   Installation Source: SDK 8.0.100
   Manifest Version:    8.0.3/8.0.100
   Manifest Path:       /usr/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.3/WorkloadManifest.json
   Install Type:        FileBased

 [wasm-tools]
   Installation Source: SDK 8.0.100
   Manifest Version:    8.0.1/8.0.100
   Manifest Path:       /usr/share/dotnet/sdk-manifests/8.0.100/microsoft.net.workload.mono.toolchain.current/8.0.1/WorkloadManifest.json
   Install Type:        FileBased

 [wasi-experimental]
   Installation Source: SDK 8.0.100
   Manifest Version:    8.0.1/8.0.100
   Manifest Path:       /usr/share/dotnet/sdk-manifests/8.0.100/microsoft.net.workload.mono.toolchain.current/8.0.1/WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92

.NET SDKs installed:
  6.0.418 [/usr/share/dotnet/sdk]
  7.0.405 [/usr/share/dotnet/sdk]
  8.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.26 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.15 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.26 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.15 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/share/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

</details>

**Comment by MichalPetryka** [comment]
> Running tests with MSTest or NUnit do not exhibit this behavior, so one workaround could, in theory, be to switch from xUnit to NUnit or MSTest. 

This should probably be reported to XUnit instead then?

**Comment by rmunn** [comment]
@MichalPetryka - You might be right; reported at https://github.com/xunit/visualstudio.xunit/issues/401. Closing this issue for now, will reopen if necessary.

**Comment by bradwilson** [comment]
@MichalPetryka The bug appears to be in VSTest, because simply changing the verbosity gets you to report the right time:

![image](https://github.com/dotnet/runtime/assets/16944/2117f579-4e69-437c-8a66-166844067472)

Unless you can tell me how that is xUnit.net's fault, I'm going to assume it's your code. Thanks.

**Comment by bradwilson** [comment]
(Also, I updated to the latest versions of our NuGet packages, and that does not change the result.)

**Comment by rmunn** [comment]
I've updated the test repro to the latest versions of the NuGet packages. Bug still occurs. As bradwilson notes, `--logger "console;verbosity=normal"` produces correct results, but `--logger "console;verbosity=quiet"` still produces the wrong timing resutls (the first test is skipped in calculating the total duration).

Also, running with `/v:q` and `/v:n` both still reproduce the bug. Reopening since it's becoming more likely that the buggy code is indeed somewhere in the dotnet test runner, not in xUnit. I've updated the README in the repro, and will update the issue description with these findings as well.

**Comment by bradwilson** [comment]
> Configuration
>
> Linux Mint 21.3 (based on Ubuntu 22.04), running dotnet 8.0. I haven't yet tried this on other machines, so I don't know if this behavior is Linux-specific or not.

I ran the tests on Windows 11 23H2 (22631.3085) and it reproduced there.

**Comment by vcsjones** [comment]
@MarcoRossignoli @nohwnd can you help get this issue to the right place?

**Comment by nohwnd** [comment]
I can move issues only within the same organization, but our repo is in microsoft/, created a new issue there: https://github.com/microsoft/vstest/issues/4894
