### ISSUE TITLE
[infra] Exclude 0-test groups to reduce the number of machines allocated on Helix

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#98213]
## Description

The Mono runtime jobs currently execute only a Xunit subset of runtime tests but report the entire set as executed. Here is an example: https://helix.dot.net/api/jobs/040d7180-cbe4-4947-9fac-3480890ed589/workitems/profiler.assembly?api-version=2019-06-17.

The CoreCLR Prio0 jobs execute the full suite of tests. It appears that the Mono jobs may be misconfigured, as they utilize the same pipeline as CoreCLR jobs.

/cc: @trylek

**Comment by jkoritzinsky** [comment]
A number of the filtering mechanisms in the src/tests tree (issues.targets, DisableProjectBuild, SkipOnMono/SkipOnCoreCLR) don't produce test assemblies or are automatically excluded from the source-generated runner at build time and not included in the test counts, total or skipped.

When Mono was onboarded, many tests were disabled pending triage, some of which never happened.

Other areas, like the profiler subset you linked, aren't applicable on Mono, but there's no good way in the legacy test wrapper system to exclude 0-test groups.

**Comment by kotlarmilos** [comment]
Lower priority compared to other tasks.
