### ISSUE TITLE
Decompression handler is case-sensitive

### ISSUE THREAD

**Issue by kimmmmmik** [dotnet/runtime#98236]
### Description

Reference to [RFC](https://www.rfc-editor.org/rfc/rfc2616#section-3.5) All content-coding values are case-insensitive, although [DecompressionHandler](https://github.com/dotnet/runtime/blob/bb2376cf22172196bcac715d2f26ddfcb1b991cf/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/DecompressionHandler.cs#L81) is case-sensitive

It seems this issue exist in .NET Framework 4.6.2 project

### Reproduction Steps

Provide "Gzip" instead of "gzip" in the header

### Expected behavior

handle both "Gzip" and "gzip"

### Actual behavior

Did not handle "Gzip"

private const string Gzip = "gzip";

 

if (GZipEnabled && last == Gzip)
{
    response.Content = new GZipDecompressedContent(response.Content);
}

### Known Workarounds

Provide "gzip"

**Comment by ManickaP** [comment]
Triage: looks as a bug. The fix seems pretty straight forward. So we'd gladly accept a contribution to fix this.
