### ISSUE TITLE
Does this work with .NET 8?

### ISSUE THREAD

**Issue by testpushhydra** [dotnet/runtime#98235]
### Type of issue

Code doesn't work

### Description

I keep getting 0xE0434352 error code

Host:

```cpp
// TestDllExportCPP.cpp : This file contains the 'main' function. Program execution begins and ends there.
//

#include <iostream>
#include <Windows.h>
#include "nethost.h"
#include "coreclr_delegates.h"
#include "hostfxr.h"
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <iostream>

#define DIR_SEPARATOR L'\\'

using string_t = std::basic_string<char_t>;

// Globals to hold hostfxr exports
hostfxr_initialize_for_runtime_config_fn init_fptr;
hostfxr_get_runtime_delegate_fn get_delegate_fptr;
hostfxr_close_fn close_fptr;

bool FileExists(string_t szPath)
{
	DWORD dwAttrib = GetFileAttributes(szPath.c_str());

	return (dwAttrib != INVALID_FILE_ATTRIBUTES &&
		!(dwAttrib & FILE_ATTRIBUTE_DIRECTORY));
}

void* load_library(const char_t* path)
{
	HMODULE h = ::LoadLibraryW(path);
	assert(h != nullptr);
	return (void*)h;
}

void* get_export(void* h, const char* name)
{
	void* f = ::GetProcAddress((HMODULE)h, name);
	assert(f != nullptr);
	return f;
}

// Using the nethost library, discover the location of hostfxr and get exports
bool load_hostfxr()
{
	// Pre-allocate a large buffer for the path to hostfxr
	char_t buffer[MAX_PATH];
	size_t buffer_size = sizeof(buffer) / sizeof(char_t);
	int rc = get_hostfxr_path(buffer, &buffer_size, nullptr);
	if (rc != 0)
		return false;

	// Load hostfxr and get desired exports
	void* lib = load_library(buffer);
	init_fptr = (hostfxr_initialize_for_runtime_config_fn)get_export(lib, "hostfxr_initialize_for_runtime_config");
	get_delegate_fptr = (hostfxr_get_runtime_delegate_fn)get_export(lib, "hostfxr_get_runtime_delegate");
	close_fptr = (hostfxr_close_fn)get_export(lib, "hostfxr_close");

	return (init_fptr && get_delegate_fptr && close_fptr);
}

// Load and initialize .NET Core and get desired function pointer for scenario
load_assembly_and_get_function_pointer_fn get_dotnet_load_assembly(const char_t* config_path)
{
	// Load .NET Core
	void* load_assembly_and_get_function_pointer = nullptr;
	hostfxr_handle cxt = nullptr;
	int rc = init_fptr(config_path, nullptr, &cxt);

	if (rc != 0 || cxt == nullptr)
	{
		std::cerr << "Init failed: " << std::hex << std::showbase << rc << std::endl;
		close_fptr(cxt);
		return nullptr;
	}

	// Get the load assembly function pointer
	rc = get_delegate_fptr(
		cxt,
		hdt_load_assembly_and_get_function_pointer,
		&load_assembly_and_get_function_pointer);
	if (rc != 0 || load_assembly_and_get_function_pointer == nullptr)
		std::cerr << "Get delegate failed: " << std::hex << std::showbase << rc << std::endl;

	close_fptr(cxt);
	return (load_assembly_and_get_function_pointer_fn)load_assembly_and_get_function_pointer;
}

int __cdecl wmain(int argc, wchar_t* argv[])
{
	// Get the current executable's directory
		// This sample assumes the managed assembly to load and its runtime configuration file are next to the host
	char_t host_path[MAX_PATH];

	auto size = ::GetFullPathNameW(argv[0], sizeof(host_path) / sizeof(char_t), host_path, nullptr);
	assert(size != 0);

	string_t root_path = host_path;
	auto pos = root_path.find_last_of(DIR_SEPARATOR);
	assert(pos != string_t::npos);
	root_path = root_path.substr(0, pos + 1);

	if (!load_hostfxr())
	{
		assert(false && "Failure: load_hostfxr()");
		return EXIT_FAILURE;
	}

	const string_t config_path = root_path + L"runtimeconfig.json";
	load_assembly_and_get_function_pointer_fn load_assembly_and_get_function_pointer = nullptr;

        // error here

	load_assembly_and_get_function_pointer = get_dotnet_load_assembly(config_path.c_str());
	assert(load_assembly_and_get_function_pointer != nullptr && "Failure: get_dotnet_load_assembly()");

	const char_t* dotnet_type = L"ClassLibrary2.Class1";
	const char_t* dotnet_type_method = L"Test";
	string_t dotnetlib_path;

	dotnetlib_path = root_path + L"..\\..\\ClassLibrary2\\bin\\Debug\\net8.0\\ClassLibrary2.dll";

	if (!FileExists(dotnetlib_path))
	{
		assert(false && "Failure: FileExist(dotnetlib_path)");
		return EXIT_FAILURE;
	}

	struct lib_args
	{
		const char_t* message;
		int number;
	};

	lib_args args
	{
		L"from host!",
		-1
	};

	// Function pointer to managed delegate
	// Function pointer to managed delegate with non-default signature
	typedef void (CORECLR_DELEGATE_CALLTYPE* custom_entry_point_fn)(lib_args args);
	custom_entry_point_fn custom = nullptr;
	int rc = load_assembly_and_get_function_pointer(
		dotnetlib_path.c_str(),
		dotnet_type,
		L"CustomEntryPointUnmanaged" /*method_name*/,
		UNMANAGEDCALLERSONLY_METHOD,
		nullptr,
		(void**)&custom);
	assert(rc == 0 && custom != nullptr && "Failure: load_assembly_and_get_function_pointer()");

	custom(args);

	return 1;
}
```

Assembly:
```csharp
using System;
using System.Runtime.InteropServices;

namespace ClassLibrary2
{
    public static class Class1
    {
        [StructLayout(LayoutKind.Sequential)]
        public struct LibArgs
        {
            public IntPtr Message;
            public int Number;
        }

        public static void Test()
        {
            Console.WriteLine("Test");
        }

        public delegate void CustomEntryPointDelegate(LibArgs libArgs);
        public static void CustomEntryPoint(LibArgs libArgs)
        {
            Console.WriteLine($"Hello, world! from {nameof(CustomEntryPoint)} in {nameof(Class1)}");
            PrintLibArgs(libArgs);
        }

        [UnmanagedCallersOnly]
        public static void CustomEntryPointUnmanaged(LibArgs libArgs)
        {
            CustomEntryPoint(libArgs);
        }

        private static void PrintLibArgs(LibArgs libArgs)
        {
            string message = RuntimeInformation.IsOSPlatform(OSPlatform.Windows)
                ? Marshal.PtrToStringUni(libArgs.Message)
                : Marshal.PtrToStringUTF8(libArgs.Message);

            Console.WriteLine($"-- message: {message}");
            Console.WriteLine($"-- number: {libArgs.Number}");
        }

    }
}

```

Libs, dll's and headers from here:
C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Host.win-x86\8.0.0\runtimes\win-x86\native

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting?source=docs

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tutorials/netcore-hosting.md

### Document Version Independent Id

a98926cc-64ab-2911-e4b8-1eaf4573dfe4

### Article author

@mjrousos

### Metadata

* ID: 83da7030-b5f1-72ad-71f6-424ff45b8b7f 
* Service: **dotnet-fundamentals**

**Comment by vitek-karas** [comment]
Try attaching a managed debugger - it should be able to see the managed exception and tell you what's wrong.
You might also look into the event log, there might be an event there about the failure as well.

**Comment by testpushhydra** [comment]
Hi Vitek, thanks for responding.  I got it working!  Turning on the managed debugger (mixed mode) did wonders.  Thank you!

**A few suggestions:**
1. Include C# sample
2. Mention type names are required to be assembly qualified, i.e:
string_t dotnet_type = L"ClassLibrary2.Class1, ClassLibrary2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null";
3. The method has to either conform to the passed in delegate type or the default one.  You did note that in your article, but a few examples out on the web are simply misleading.
4. runtimeconfig.json is key.  Include examples.

Working C++ host:
`
	const string_t config_path = root_path + L"runtimeconfig.json";
	load_assembly_and_get_function_pointer_fn load_assembly_and_get_function_pointer = nullptr;
	load_assembly_and_get_function_pointer = get_dotnet_load_assembly(config_path.c_str());
	assert(load_assembly_and_get_function_pointer != nullptr && "Failure: get_dotnet_load_assembly()");

	string_t dotnet_type = L"ClassLibrary2.Class1, ClassLibrary2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null";
	string_t dotnet_type_method = L"ComponentEntryPointUnmanaged";
	string_t dotnetlib_path;
	string_t delegateTypeName = L"ClassLibrary2.Class1+CustomEntryPointDelegate, ClassLibrary2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null";

	dotnetlib_path = root_path + L"..\\..\\..\\ClassLibrary2\\bin\\Debug\\net8.0\\ClassLibrary2.dll";

	if (!FileExists(dotnetlib_path))
	{
		assert(false && "Failure: FileExist(dotnetlib_path)");
		return EXIT_FAILURE;
	}

	struct lib_args
	{
		const char_t* message;
		int number;
	};

	lib_args args
	{
		L"from host!",
		-1
	};

	// Function pointer to managed delegate
	// Function pointer to managed delegate with non-default signature
	typedef void (CORECLR_DELEGATE_CALLTYPE* custom_entry_point_fn)(lib_args args);
	custom_entry_point_fn custom = nullptr;
	int rc = load_assembly_and_get_function_pointer(
		dotnetlib_path.c_str(),
		dotnet_type.c_str(),
		dotnet_type_method.c_str(),
		UNMANAGEDCALLERSONLY_METHOD,
		nullptr,
		(void**)&custom);
	assert(rc == 0 && custom != nullptr && "Failure: load_assembly_and_get_function_pointer()");

	custom(args);
`

Working C#:

`
using System;
using System.Runtime.InteropServices;

namespace ClassLibrary2
{
    public static class Class1
    {
        // just here for reference but this can be custom
        public delegate int ComponentEntryPoint(IntPtr args, int sizeBytes);

        [UnmanagedCallersOnly]
        public static int ComponentEntryPointUnmanaged(IntPtr args, int sizeBytes)
        {
            Console.WriteLine($"Hello, world! from {nameof(ComponentEntryPointUnmanaged)} in {nameof(Class1)}");
            return 0;
        }
    }
}
`

**Comment by vitek-karas** [comment]
Thanks for the suggestions and I'm happy it works for you.

I believe we did "fix" most of the recommendations:
The guide: https://learn.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting
The sample: https://github.com/dotnet/samples/tree/main/core/hosting

The sample contains everything, including C# and `.runtimeconfig.json`.
The only thing missing is that the guide doesn't explicitly callout the format for the type name.

Did you find these resources before this?
