### ISSUE TITLE
dotnot-host installer not found on system, cannot repair, install, fix or upgrade

### ISSUE THREAD

**Issue by jorgt** [dotnet/runtime#98286]
Hi, 

I am stuck behind this screen:

![image](https://github.com/dotnet/runtime/assets/2444503/40f3aab5-21a3-444b-989c-032b8194ff93)

I can NOT find this file anywhere on my computer or the internet. I can also not remove dotnet, reinstall it, fix it, repair it, upgrade or downgrade it without this pop up and the file mentioned. 

Suggestions?

**Comment by NikolaMilosavljevic** [comment]
@jorgt it seems that something on your machine has cleaned up the installer cache. To recover, you would need to download  .NET runtime installer: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-6.0.26-windows-x64-installer When you run it, select the Repair option. After that, you will be able to remove this version or upgrade to a new one.

**Comment by NikolaMilosavljevic** [comment]
[Triage] Closing - feel free to reopen if the proposed solution did not work.
