### ISSUE TITLE
[mono][marshal] Assertion should not be reached in mono_marshal_shared_conv_to_icall 

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#98307]
### Error Blob

```json
{
  "ErrorMessage": "Assertion: should not be reached at /__w/1/s/src/mono/mono/metadata/marshal-shared.c:471",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": true
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=560509&view=logs&j=d25dc2c0-518b-5583-f661-5ac905106679&t=47cb0142-4d6b-5edf-a0a8-cf81fa3f7e05
**Result validation:** :warning: Validation could not be done without an Azure DevOps build URL on the issue. Please add it to the "**Build:** :mag_right:" line.
**Validation performed at:** 2/12/2024 4:58:51 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[564149](https://dev.azure.com/dnceng-public/public/_build/results?buildId=564149)|dotnet/runtime|LLVM AOT compile CoreCLR tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/564149/logs/1185)||
|[563637](https://dev.azure.com/dnceng-public/public/_build/results?buildId=563637)|dotnet/runtime|LLVM AOT compile CoreCLR tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/563637/logs/809)|dotnet/runtime#98320|
|[563468](https://dev.azure.com/dnceng-public/public/_build/results?buildId=563468)|dotnet/runtime|LLVM AOT compile CoreCLR tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/563468/logs/1177)||
|[562296](https://dev.azure.com/dnceng-public/public/_build/results?buildId=562296)|dotnet/runtime|LLVM AOT compile CoreCLR tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/562296/logs/1185)||
|[562067](https://dev.azure.com/dnceng-public/public/_build/results?buildId=562067)|dotnet/runtime|LLVM AOT compile CoreCLR tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/562067/logs/1185)||
|[562000](https://dev.azure.com/dnceng-public/public/_build/results?buildId=562000)|dotnet/runtime|LLVM AOT cross-compile CoreCLR tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/562000/logs/924)|dotnet/runtime#98279|
|[560509](https://dev.azure.com/dnceng-public/public/_build/results?buildId=560509)|dotnet/runtime|LLVM AOT compile CoreCLR tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/560509/logs/32)|dotnet/runtime#92057|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|2|7|7|

**Comment by lambdageek** [comment]
Breaking when the AOT compiler is compiling these two tests:
```
aot-compile: compiling /__w/1/s/artifacts/tests/coreclr/linux.x64.Release/Interop/Interop/AnsiBStrTest.dll; MONO_PATH: /__w/1/s/artifacts/tests/coreclr/linux.x64.Release/Interop/Interop:/__w/1/s/artifacts/tests/coreclr/linux.x64.Release/Tests/Core_Root
  Mono Ahead of Time compiler - compiling assembly /__w/1/s/artifacts/tests/coreclr/linux.x64.Release/Interop/Interop/AnsiBStrTest.dll
```

and

```
aot-compile: compiling /__w/1/s/artifacts/tests/coreclr/linux.x64.Release/Interop/Interop/BSTRTest.dll; MONO_PATH: /__w/1/s/artifacts/tests/coreclr/linux.x64.Release/Interop/Interop:/__w/1/s/artifacts/tests/coreclr/linux.x64.Release/Tests/Core_Root
  Mono Ahead of Time compiler - compiling assembly /__w/1/s/artifacts/tests/coreclr/linux.x64.Release/Interop/Interop/BSTRTest.dll
  AOTID AD838859-9056-1E7A-B96E-AD46B2CD0FAD
  * Assertion: should not be reached at /__w/1/s/src/mono/mono/metadata/marshal-shared.c:471
```

**Comment by jkoritzinsky** [comment]
If it's just the BStr tests, than I probably removed some BStr case that was connected to the COM stuff. Alternatively, it might be some COM path where we need to bail out more cleanly.

In any case, I'll take a look.

**Comment by lambdageek** [comment]
We just started running the LLVM aot runtime tests again after the recent slate of PRs to make the LLVM compilation use less memory, so this was probably missed because the tests didn't run on the COM PR yet

**Comment by lambdageek** [comment]
I guess it's in this PR: https://github.com/dotnet/runtime/pull/92057

**Comment by lambdageek** [comment]
Actually I take it back. it's failing in `runtime-extra-platforms` on other `main`, too:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=562296&view=results

https://dev.azure.com/dnceng-public/public/_build/results?buildId=562296&view=logs&j=d25dc2c0-518b-5583-f661-5ac905106679&t=47cb0142-4d6b-5edf-a0a8-cf81fa3f7e05&l=1453
