### ISSUE TITLE
Support HttpClient custom logging outslide of HttpClientFactory

### ISSUE THREAD

**Issue by markm77** [dotnet/runtime#98312]
Hi there,

Due to the need to support an arbitrary number of MTLS setups, I create long-lived `HttpClient` instances (each with a different transport cert) rather than use `HttpClientFactory`.

I was reading about the new .NET 8 custom logging support in this blog: https://devblogs.microsoft.com/dotnet/dotnet-8-networking-improvements/#httpclientfactory

I am interested in using this custom logging in my case and, looking into it, it seems I could add a custom (wrapping) logger by using something like the following:
```csharp
var clientHandler = new SocketsHttpHandler(); // then customise
IHttpClientLogger httpClientLogger = new MyLogger(); // my custom logger
var httpClient = new HttpClient(new HttpClientLoggerHandler(httpClientLogger) { InnerHandler = clientHandler });
```

However this is not possible as `HttpClientLoggerHandler` from `Microsoft.Extensions.Http.Logging` is marked `internal`.

Could you consider officially supporting use of custom logging outside of `HttpClientFactory`, e.g. by making `HttpClientLoggerHandler` public?

Also a follow-up question: the blog warns against reading request/response Content (e.g. for full trace logging). So it therefore seems the only safe way to log content is by doing do outside of the `HttpClient` instance, thus creating multiple log messages again? Can you consider providing a safe mechanism for Content logging so any or all details of an HTTP request can be directed to a single log message (which I believe would be in line with the goals of this feature)?

BR,
Mark

**Comment by markm77** [comment]
After reflection and experimentation, I've decided to keep my HTTP logging outside of a handler like `HttpClientLoggerHandler` in order to enable safe inclusion of request/response Content as required.

I've still managed though to move the output formatting into an implementation of `IHttpClientLogger` to keep things aligned with `HttpClientFactory` expected future practice.

So I'll close this as I don't require any changes but would be great if you can keep in mind those of us who use long-lived `HttpClient` instances rather than `HttpClientFactory`.

Many thanks and any comments welcome!

**Comment by silkfire** [comment]
I could really use for `HttpClientLoggerHandler` to become public as I need to unit test my client logger. Has this been considered by the team or are there any workarounds?
