### ISSUE TITLE
[6.0] [warning] [android] [mono] libc.so.6 error - GLIBC_2.28 not found in node20, using node16 instead. Need OS upgrade.

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#98313]
- Found in unrelated deps flow 6.0 PR: https://github.com/dotnet/runtime/pull/98171
- Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=558824&view=results
- Affected queues: 
  - `Build Android x64 Release AllSubsets_Mono_RuntimeTests_Interp`
  - `Build Android x86 Release AllSubsets_Mono`
  - `Build Android x64 Release AllSubsets_Mono`

- Output:
```
/usr/local/vss-agent/3.232.3/externals/node20_1/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/vss-agent/3.232.3/externals/node20_1/bin/node)
##[warning]The container operating system doesn't support Node20. Using Node16 instead. Please upgrade the operating system of the container to remain compatible with future updates of tasks: https://github.com/nodesource/distributions
Generating script.
```

@dotnet/dnceng

**Comment by steveisok** [comment]
Seeing this is 6.0, we should just disable them.

**Comment by akoeplinger** [comment]
Yes though I've seen this in main as well in some jobs which still use Ubuntu 18.04 hosts/containers

**Comment by matouskozak** [comment]
This happens on 7.0 as well (see https://dev.azure.com/dnceng-public/public/_build/results?buildId=609321&view=logs&j=47685575-de8e-52df-4903-abd1d81ad414&t=09458842-80f7-5a71-6463-14738f3eedda). What is the best approach to fix this? Disable or update the hosts/containers?

**Comment by vitek-karas** [comment]
@matouskozak is this still happening?

**Comment by matouskozak** [comment]
> @matouskozak is this still happening?

The .NET 6.0 runs are clear, closing the issue
