### ISSUE TITLE
[API Proposal]: Proposal for Automatic Temporary Directory Management

### ISSUE THREAD

**Issue by mrconter1** [dotnet/runtime#98349]
### Background and motivation

In .NET development, managing temporary files and directories is a common necessity across various types of applications. While the `System.IO` namespace provides comprehensive support for file and directory operations, it currently lacks a straightforward mechanism for creating temporary directories that are automatically cleaned up when they are no longer needed or when the application exits. This proposal aims to introduce a new API that simplifies the creation and management of temporary directories, ensuring they are automatically cleaned up, thereby reducing the manual cleanup burden on developers and minimizing the risk of leaving behind temporary data.

### API Proposal

```csharp
using System;
using System.Collections.Generic;
using System.IO;

namespace System.IO
{
    public static class TemporaryDirectory
    {
        private static readonly List<string> TempDirectories = new List<string>();

        static TemporaryDirectory()
        {
            AppDomain.CurrentDomain.ProcessExit += (sender, e) => CleanupTempDirectories();
            AppDomain.CurrentDomain.DomainUnload += (sender, e) => CleanupTempDirectories();
        }

        private static void CleanupTempDirectories()
        {
            foreach (var dir in TempDirectories)
            {
                if (Directory.Exists(dir))
                {
                    try
                    {
                        Directory.Delete(dir, true);
                    }
                    catch
                    {
                        // Log or handle the failure to delete the directory as needed
                    }
                }
            }
        }

        public static TemporaryDirectoryHandle Create()
        {
            var tempPath = Path.GetTempPath();
            var tempDirectoryName = Path.GetRandomFileName();
            var tempDirectoryFullPath = Path.Combine(tempPath, tempDirectoryName);
            Directory.CreateDirectory(tempDirectoryFullPath);

            lock (TempDirectories)
            {
                TempDirectories.Add(tempDirectoryFullPath);
            }

            return new TemporaryDirectoryHandle(tempDirectoryFullPath, TempDirectories);
        }
    }

    public class TemporaryDirectoryHandle : IDisposable
    {
        public string Path { get; private set; }
        private readonly List<string> _tempDirectories;
        private bool _disposed = false;

        internal TemporaryDirectoryHandle(string path, List<string> tempDirectories)
        {
            Path = path;
            _tempDirectories = tempDirectories;
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        protected virtual void Dispose(bool disposing)
        {
            if (!_disposed)
            {
                if (disposing)
                {
                    // Managed resource cleanup
                }

                if (Directory.Exists(Path))
                {
                    try
                    {
                        Directory.Delete(Path, true);
                        lock (_tempDirectories)
                        {
                            _tempDirectories.Remove(Path);
                        }
                    }
                    catch
                    {
                        // Log or handle the failure to delete the directory as needed
                    }
                }

                _disposed = true;
            }
        }

        ~TemporaryDirectoryHandle()
        {
            Dispose(false);
        }
    }
}
```

### API Usage

```csharp
// Example of using the proposed API with automatic cleanup when the application exits
var tempDirHandle = TemporaryDirectoryHandle.Create();
Console.WriteLine($"Temporary directory created at: {tempDirHandle.Path}");
// The temporary directory will be automatically deleted when the application exits or the handle is disposed.

// Example of explicitly disposing of the temporary directory
using (var anotherTempDir = TemporaryDirectoryHandle.Create())
{
    Console.WriteLine($"Another temporary directory created at: {anotherTempDir.Path}");
    // Perform operations with the temporary directory
} // The directory is deleted here when exiting the using block.
```

### Alternative Designs

One alternative could involve enhancements to existing Path or Directory classes to include temporary directory management capabilities. However, this approach might clutter the API of these well-established classes with very specific functionality. Another alternative could be the introduction of a more general resource management API that handles not just directories, but temporary files with similar lifecycle management. This broader approach, while more flexible, could introduce additional complexity that might not be necessary for most use cases.

### Risks

One potential risk is the handling of unexpected application terminations (e.g., crashes or forced exits) which might not trigger the cleanup logic as expected. Additionally, there could be security considerations around the creation and deletion of directories, especially in environments with strict permissions or where directory traversal attacks are a concern. Ensuring that this API behaves consistently across different operating systems (Windows, Linux, macOS) and their various file system permissions models is also crucial.

**Comment by hopperpl** [comment]
https://learn.microsoft.com/en-us/dotnet/api/system.io.fileoptions?view=net-8.0

`FileOptions` has `DeleteOnClose`


with directories ...

... this can cause a lot of problems when other applications traverse these directories when they only exist for a very small time; applications like virus scanners, indexers, backup tools etc that see a new directory and start "investigating", this causes race conditions with the FindFile API functions

... then there is the issue with network directories, removable storage, etc. which can all be used (and are used) as %TEMP% somewhere; 

... then what happens if another application creates their own file into such a temporary folder, e.g. `explorer` creates `desktop.ini` or `thumb.db` ; do these files get deleted too? indexing applications and services *love* to create extra files everywhere

I'm not sure if transferring this responsibility for directories to the runtime is a good idea, because I don't see how this can be made reliable. And if it's not reliable then some extra code outside the runtime is needed either way to cleanup.

On top, Windows, Linux and MacOS all do cleanup %TEMP% (/tmp respectively) in certain intervals. Either during boot or during storage pressure or via schedule.

**Comment by Zintom** [comment]
@hopperpl I agree.

I think the responsibility should lie with the application and its security and logistical requirements.

Delegating this behaviour to the runtime introduces too many edge cases that might not be caught and might present vulnerabilities or just poor practice.

**Comment by Jozkee** [comment]
I'm not currently convinced we should add this, as other mentioned this can be achievable with existing APIs. We can reconsider in the future depending on user feedback.

**Comment by julealgon** [comment]
The only way I see this working is if the file only existed for the running process (i.e. some kind of virtual, memory-mapped file handle that was tied/owned to a specific process): when the process dies, that memory is gone like any other memory.

If the file ends up in the file system, I don't see how the .NET runtime can properly "keep track of it" without suffering interference from unknown external processes, which just makes it completely unreliable and thus defeats the purpose.
