### ISSUE TITLE
Process.WaitForExitAsync does not return when awaited process is killed if output is redirected

### ISSUE THREAD

**Issue by chrishamm** [dotnet/runtime#98347]
### Description

With .NET 6 on Linux arm32 it seems like Process.WaitForExitAsync does not return before all the child processes are terminated *if* stdout/stderr are redirected. If I remove the output redirection and call WaitForExitAsync(), it returns as soon as the awaited process is terminated, which is expected.

For my current application, removing the output redirection as a work-around is sufficient but not really ideal.
Here my original code that let me reproduce it: https://github.com/Duet3D/DuetSoftwareFramework/blob/9328685a0d3c4d65c3fe693fbea86f084c0d9882/src/DuetPluginService/Commands/StartPlugin.cs#L93
And here my current work-around that works as expected without console redirection: https://github.com/Duet3D/DuetSoftwareFramework/blob/b225e9beb845053c1b5cafa88648a224dfd346a6/src/DuetPluginService/Commands/StartPlugin.cs#L125

In my case, I call an update application that needs to keep running when the awaited process is terminated. However, this eventually led to a deadlock because the parent application did not update the PID because WaitForExitAsync does not behave as expected with console redirection enabled.

### Reproduction Steps

- Make a .NET console application A that starts another .NET console app B, which calls a long-running process C
- Let the main process A await the second process B with console redirection enabled
- Terminate the second application B using SIGTERM/SIGKILL while leaving its subprocess C running

### Expected behavior

Even though application B is terminated and C is still running, WaitForExitAsync does NOT return but only if console redirection is enabled. If it is disabled, it returns as soon as B is terminated

### Actual behavior

WaitForExitAsync returns only as soon as B and C have been terminated

### Regression?

I am not sure if #81896 or #51277 are related

### Known Workarounds

Do not enable output redirection

### Configuration

.NET 6 on Linux arm32

### Other information

In my case, app A is the linked plugin host application, app B a custom plugin app that calls dpkg, and the child process C (with other child processes) dpkg/unattended-upgrade, which performs a system upgrade and may replace B as well

**Comment by tmds** [comment]
> only if console redirection is enabled

Process A can't distinguish between the output of process B and process C, so it waits for both of them.

.NET doesn't have an API that allows you to completely ignore a process' output, which is what you want to do here for C (or maybe even B). https://github.com/dotnet/runtime/issues/28838 is for adding such an API.

You can work around it by using a shell to redirect stdout/stdin/stderr.
Instead of starting your application directly, instead start: `[ "/bin/sh", "-c", "'exec {app} {args} 2>&1  >/dev/null </dev/null" ]`. The `{app}` and `{args}` need to be properly escaped (for dealing with whitespaces, quotes, ...).

**Comment by chrishamm** [comment]
I see, thanks for the quick response - that makes sense, but AFAICS it isn't documented yet. I had expected WaitForExit(Async) behaves the same no matter if console redirection is enabled or not.

**Comment by tmds** [comment]
I'll close this. The discussion continues on the API issue: https://github.com/dotnet/runtime/issues/28838.
