### ISSUE TITLE
[Perf][x86] Investigate performance regression in FannkuchRedux_2 and FannkuchRedux_5

### ISSUE THREAD

**Issue by nategraf** [dotnet/runtime#9836]
There appears a 5% and 3% performance regression in release/2.1 as compared 7f143364a8ed1ebc51356195fc90bbe972c2c038

A possible cause for this regression has yet be found

category:cq
theme:benchmarks
skill-level:intermediate
cost:small

**Comment by AndyAyersMS** [comment]
Issues seen here are addressed by other open issues. So closing.
