### ISSUE TITLE
Question: best way to get operator method in reflection

### ISSUE THREAD

**Issue by lilinus** [dotnet/runtime#98402]
Question: What is best practice to find an operator overload method in reflection?

I believe the names of the methods are for example "op_Addition" and such, but I can't find any official documentation on this.

Is there good way to do this without using magic string based on inofficial information?

What I'm trying to implement a IQueryExpressionInterceptor, in which i need to identify for example the addition operator.

**Comment by DaZombieKiller** [comment]
You can find all of the operator method names documented [here](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/operator-overloads).

**Comment by steveharter** [comment]
Yes the name can be checked; I am not aware of a property or other way to determine whether a given method is an operator overload.
