### ISSUE TITLE
Allow dump from createdump to be piped to another program (e.g. for compression)

### ISSUE THREAD

**Issue by loop-evgeny** [dotnet/runtime#9840]
Full memory (core) dumps can be very large, possibly even exceeding the amount of available disk space. They compress very well, but `createdump` doesn't make it easy to compress them on the fly, without creating a temporary file.

```dotnet/shared/Microsoft.NETCore.App/2.0.5/createdump --full --name /dev/stdout PID |xz >dump.xz```
doesn't work, because `createdump` also writes other output to stdout.

Using a pipe works, but is a bit awkward:
```
mkfifo -m 600 dumppipe
xz -z -1 -c dumppipe >dump.xz &
dotnet/shared/Microsoft.NETCore.App/2.0.5/createdump --full --name dumppipe PID &
```
(The code has to be much more complicated than this in practice to allow for either xz or createdump failing, e.g. due to lack of permissions for the output directory or the process.)

Please create a way to easily pipe the dump to another program. It may be as simple as writing all messages to stderr.

**Comment by mikem8361** [comment]
Dup of https://github.com/dotnet/runtime/issues/58747
