### ISSUE TITLE
`FileSystemWatcher` does not work when there is more than 1 instance of it

### ISSUE THREAD

**Issue by dehghani-mehdi** [dotnet/runtime#98424]
### Description

I have 2 console apps running, and each of them has its own `FileSystemWatcher` instance, when I run the first app, everything works as expected, but when I start the second one, only one of them works properly. _as soon as I stop one of them, the other one starts working_.

### Reproduction Steps

1. Create 2 console apps with the following code:
```
var fsw = new FileSystemWatcher
{
    Path = "path/to/target/directory",
    Filter = "*.*",
    EnableRaisingEvents = true,
    IncludeSubdirectories = true,
    NotifyFilter = NotifyFilters.LastWrite | NotifyFilters.FileName | NotifyFilters.Size | NotifyFilters.LastAccess
};

fsw.Changed += (s, e) => {};
fsw.Deleted += (s, e) => {};
fsw.Created += (s, e) => {};
fsw.Renamed += (s, e) => {};
```

### Expected behavior

`FileSystemWatcher` should work, no matter how many instances are watching the same directory.

### Actual behavior

Only one instance of `FileSystemWatcher` works when there is more than one instance of it, watching the same path.

### Regression?

I don't know, I'm using .net8.0

### Other information

- Windows 10 x64
- Version 1909
- Build 18363.592

**Comment by Clockwork-Muse** [comment]
Like all I/O, and especially all file I/O, it is entirely dependent on the behavior of the host OS.
We need the details of your host OS.

**Comment by dehghani-mehdi** [comment]
@Clockwork-Muse 
- Windows 10 x64
- Version 1909
- Build 18363.592

_I also updated my first comment_

**Comment by Jozkee** [comment]
I was not able to repro on Windows 11. Can you add an Error event and see if that catches something?

**Comment by dehghani-mehdi** [comment]
My main projects are too complex. I tested with 2 simple console apps, (as I mentioned in my first post), and everything works as expected, so I have to test more. for now, I close this issue, if I find something related to `FileSystemWatcher`, I'll post it here.
