### ISSUE TITLE
Allows setting of 4 spaces indentation or 2 spaces indentation in JsonSerializerOptions.[API Proposal]: 

### ISSUE THREAD

**Issue by bzuidgeest** [dotnet/runtime#98423]
### Background and motivation

As #1174 is closed and locked, I am adding this back. Maybe I can provide a better motivation for this than "looks nice" in the previous request.

New reason: The default of "2" is in conflict with the default spacing choice of .net's primary development tool. In Visual Studio the default is "4". Now when I generate JSON everything has to be reformatted every time. 
This default is explicitly stated here:
https://learn.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-all-languages-tabs?view=vs-2022

### API Proposal
```
public partial class JsonSerializerOptions
{
    /// <summary>The number of spaces to write per indentation level when <see cref="WriteIndented" /> is enabled.</summary>
    public int IndentSize { get; set; }
}
```
### API Usage

Auto generating json content for tools like visual studio and others that. Or more general, allow the formatting to be adjusted to whatever convention a group of developers uses and not just force something that is not a general convention.

**Comment by elgonzo** [comment]
That's apparently going to be a feature in .NET 9. See here: https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-9/overview#serialization

**Comment by bzuidgeest** [comment]
I didn't know that. Thanks for the quick reply. This can wait till the next major version. Even if its a little annoying :)

**Comment by eiriktsarpalis** [comment]
> This can wait till the next major version. Even if its a little annoying :)

You could just download the 9.0.0 NuGet package preview [which is already available](https://www.nuget.org/packages/System.Text.Json/9.0.0-preview.1.24080.9). No need to update the .NET version.
