### ISSUE TITLE
dotnet CLI commands no longer work in .NET 7/8 with detached console

### ISSUE THREAD

**Issue by Wedgetable** [dotnet/runtime#98441]
### Describe the bug

We have some Azure pipelines that run some .NET commands through Wine on Linux agents. Upon trying to upgrade from .NET 6 to .NET 8, we can no longer run any `dotnet` command from Wine (for example, `/opt/wine-stable/bin/wine64 $HOME/win-dotnet/dotnet.exe --version`) on our pipelines. Instead we get an exception:
```
Unhandled exception. System.IO.IOException: Invalid access.
   at System.ConsolePal.SetConsoleOutputEncoding(Encoding enc)
   at System.Console.set_OutputEncoding(Encoding value)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```
I'm using `dotnet --version` as an example in this bug, but it happens for `dotnet *anything*`.

* Running `/path/to/wine64 /path/to/dotnet.exe --version` from the Azure agent pipeline job **works on .NET 5/6**
* Running `/path/to/wine64 /path/to/dotnet.exe --version` **in a regular Terminal on the same agent** works on .NET 5/6/7/8
* Native Linux .NET 8 commands work from the pipeline, if `dotnet-sdk` is installed

In Wine, we get the following warning when running from an Azure agent:
`0024:warn:console:console_ioctl Incorrect access to Shell-no-window console (ioctl=50403c)`

Which possibly was not a problem until hitting this code that was added: https://github.com/dotnet/sdk/commit/697d62c7fdec87ff1b2c81a47e02b1294dab9e7b

### To Reproduce

Prereq: an Azure agent that runs on Linux

1. Install the latest version of `wine-stable` on the agent
1. Download and unzip the latest version of .NET 7 or .NET 8 **for Windows** somewhere on the agent, for example `$HOME/win-dotnet`
1. In a pipeline script targeting the agent, run `/opt/wine-stable/bin/wine64 $HOME/win-dotnet/dotnet.exe --version`
1. Run pipeline -> hit exception.

Example pipeline file: https://gist.github.com/Wedgetable/e75b08ae1eb3b2fb10cc2a53a9953745

### Exceptions (if any)

```
Unhandled exception. System.IO.IOException: Invalid access.
   at System.ConsolePal.SetConsoleOutputEncoding(Encoding enc)
   at System.Console.set_OutputEncoding(Encoding value)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```
### Further technical details
- Agent version: 3.232.1
- OS: Ubuntu 20.04.6 LTS 64-bit
- wine64 version: wine-9.0
- .NET SDK for Windows version(s): 7.0.405, 8.0.101

Not sure if this is a .NET bug, a Wine bug, or an Azure pipelines agent bug. We are currently getting technical support from CodeWeavers on this issue as well.

**Comment by jkotas** [comment]
Moved to dotnet/runtime and updated the title to make it clear that this is not a Wine-specific problem.

**Comment by nick-beer** [comment]
@jkotas - yes, I'll try to get something posted soon.

**Comment by joshudson** [comment]
`isatty()` doesn't work too good because you could be redirected to a printer. This is one ugly edge case. Too bad SetConsoleOutputCP doesn't take a file handle.

I've worked out an actual solution involving CreateFile("CONOUT$") and CompareObjects. If nothing else appears I might be able to do something about this next week.

**Comment by nick-beer** [comment]
@jkotas - thinking about this over the last few hours, I wonder if the complexity/risk to reward tradeoff is right here?  We were previously talking about handling an extremely rare exception in the SDK.  The impact of handling the exception is the same as if we hadn't set the property at all - exposing the previous bug (but not crashing).  However, we're now talking about making changes to the console APIs that could (?) change behavior for an unkown number of applications, to fix an issue that hasn't been reported (presumably).  Thoughts?

**Comment by jkotas** [comment]
If we take the workaround in the SDK, we are saying that all uses of Console.OutputEncoding setter should better have try/catch around it. It does not make sense to me. For example, are you going to hit the problem for [similar call](https://github.com/dotnet/roslyn/blob/56cd40a063f4adc77b03fb1d9b187bd4a2772c41/src/Compilers/Core/CommandLine/ConsoleUtil.cs#L25) in Roslyn next?

I think that the fix in the console APIs can be very low-risk and simple. I would just ignore the "Invalid Handle" error code from SetConsoleOutputCP API.

**Comment by nick-beer** [comment]
@jkotas - the error returned when the process is run with DETACHED_PROCESS is ERROR_INVALID_HANDLE (0x00000006).  The error returned in the case we (@Wedgetable and I) are encountering is ERROR_INVALID_ACCESS (0x0000000C).  I'll submit the PR to ignore INVALID_HANDLE, but do you think it's inappropriate to also ignore INVALID_ACCESS?

**Comment by jkotas** [comment]
> ignore INVALID_ACCESS?

It would be ok with me.

**Comment by nick-beer** [comment]
[PR created](https://github.com/dotnet/runtime/pull/98641)
