### ISSUE TITLE
[BUG] Cancellation token doesn't seem to respect the cancellation times

### ISSUE THREAD

**Issue by ShivangiReja** [dotnet/runtime#98452]
Transferring issue https://github.com/Azure/azure-sdk-for-net/issues/33369 from the .NET SDK repository to this repository as per the ongoing discussion.

For further context, please see the discussion within the original issue.

CC: @mattgotteiner, @ccurrens

**Comment by MihaZupan** [comment]
This is not currently actionable from our side. We will need more info (e.g. a repro)

**Comment by wfurt** [comment]
It would be also interesting to see if it can be reproduced with 8.0.

**Comment by ccurrens** [comment]
We haven't reproduced this in the last year or in later .NET versions. We are currently running 8.0.

So for now, I think it's best to close the issue until it can be reproduced again.
