### ISSUE TITLE
Call to extension yield method is ignored if the returned values are discarded.

### ISSUE THREAD

**Issue by Lucasharskamp** [dotnet/runtime#98489]
### Description

Imagine the following code, where we execute a method that may take a while. (Following code is just a cropped example, imagine a task with a whole lot of steps that takes a while to complete, with of course error codes being send back in case of partial failure). This is great for Blazor, where we can update the front-end with new status reports every time a part of a task has been executed. It yields the new status of the task, which then gets rendered to front-end.

```
public static IEnumerable<TaskProgress> CreateAccount(this AccountModel account)
{
      Debug.Assert(account.IsValid())
      yield return new TaskProgress(Status.Ok, 10);
      logger.LogInformation($"Start saving account {account.Id} {account.FullName} {account.Email}");

      DatabaseCallToSaveAccount(account).Wait();
      yield return new TaskProgress(Status.Ok, 50);
      logger.LogInformation($"Account saved of {account.Id} {account.FullName} {account.Email}");

      SendInvitationEmail(account).Wait();
      yield return new TaskProgress(Status.Complete, 100);
      logger.LogInformation($"Invitation send to {account.Id} {account.FullName} {account.Email}");
}
```
The returned values are simply the percentages of the progress of the task at hand along with other important details. This will then be used in the frontend for the user:

```
  foreach (var taskProgress in account.CreateAccount())
  {
     // update Blazor component
      UploadProcessCard.UpdateItem(account, taskProgress.ProgressPercentage, taskProgress.State);
  }
```

However, there isn't always a frontend, and the logger takes care of any issues and task progression anyways if things go awry.

In that case, we simply want the code to execute and we discard the returned items.

```
_ = account.CreateAccount();
```

in that case, the method call will be ignored, meaning no account gets created.

### Reproduction Steps

Method call does not appear on the call stack and consequently doesn't appear on breakpoints.

### Expected behavior

Despite the fact the returned values are ignored, the method should proceed anyways.

### Actual behavior

Method is ignored.

### Regression?

tested on .NET 8 

### Known Workarounds

simply create a for-loop, but ignore the values returned, and it works fine.

```
foreach(var x in account.CreateAccount())
{
   // ignore
}
```

### Configuration

.NET 8
Windows 11
X64
Blazor web application

**Comment by huoyaoyuan** [comment]
This is not a runtime issue.
The code after first `yield` statement is lazy as expected. The C# feature has been compiled into such form.

Using `yield` and `IEnumerable` to simulate task is not recommended. You can use `async`/`await` and pass in a parameter to receive progress.

**Comment by bencyoung-Fignum** [comment]
It's the same as for any lazy enumerable. E.g

_ = [1, 2, 3].Select(x => {Console.WriteLine(x); return x})

will also not print anything

If you need to force this you can use something like 

_ = account.CreateAccount().Last();

to make the loop to run.

**Comment by julealgon** [comment]
Clear misunderstanding of how iterators work here.

I would perhaps suggest the `Consume` extension from morelinq:
- https://github.com/morelinq/MoreLINQ?tab=readme-ov-file#consume

```csharp
_ = account.CreateAccount().Consume();
```

**Comment by Lucasharskamp** [comment]
@julealgon I've been using (or abusing, depending on your mindset) these iterators solely for the purpose of providing intermittent "status updates". For the purposes of Blazor, that suits the employer fine enough. 

The reason I made this issue in error was that I was wrongly informed that a discard operator
should make the iterator complete its run (or enter a stackoverflow ) which of course isn't the case.

Anyway, I'd prefer to use a myriad of other ways to make the code execute the entire method rather than add a whole NuGet package just for `Consume()`.

We're now moving these methods towards background services (Azure) though, using messages to keep the user informed about the execution state, so this will soon be a thing of the past.
