### ISSUE TITLE
[browser][MT] WasmEnableThreads=true should fail without workload installed

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/runtime#98496]
### Description

The `wasm-tools` workload is required to build a multithreading-enabled WebAssembly app. 

By default, people do not have the `wasm-tools` workload installed. In this scenario, if they create a Blazor WebAssembly app and set `<WasmEnableThreads>true</WasmEnableThreads>`, then it will fail at runtime as follows:

![image](https://github.com/dotnet/runtime/assets/1101362/8be97079-021d-46ca-92a9-d58195fb05a5)

This doesn't help the developer to understand the problem or how to fix it.

### Reproduction Steps

Using an SDK without `wasm-tools`, create a .NET 9 Blazor WebAssembly Standalone app, set `<WasmEnableThreads>true</WasmEnableThreads>`, and `dotnet run`.

### Expected behavior

Ideally it would fail at build time with a message like `WasmEnableThreads is set to true, but the wasm-tools workload is not installed. To build this project, first run 'dotnet workload install wasm-tools'`.

The second best behavior would be failing at runtime with a message like the above.

### Actual behavior

Currently it fails saying "Can't find method ... InstallMainSynchronizationContext", giving no clue how to fix it.

### Regression?

No

### Known Workarounds

n/a

### Configuration

.NET 9 + WebAssembly

**Comment by SteveSandersonMS** [comment]
cc @lewing @pavelsavara

**Comment by pavelsavara** [comment]
I think this `WasmEnableThreads` needs to be added to `_WasmNativeWorkloadNeeded`. 
Right @maraf ?

**Comment by lewing** [comment]
https://github.com/dotnet/runtime/pull/98498

**Comment by ilonatommy** [comment]
`HostedBlazorWebassemblyApp` sample app with threads on - installing workload does not help with the error, why do we link it with workloads?

```
.NET SDK:
 Version:           9.0.100-preview.2.24112.1
 Commit:            ab44b49a39
 Workload version:  9.0.100-manifests.18bf7498

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Users\..\aspnetcore\aspnetcore\.dotnet\sdk\9.0.100-preview.2.24112.1\

.NET workloads installed:
 [wasm-tools]
   Installation Source: SDK 9.0.100-preview.2
   Manifest Version:    9.0.0-preview.2.24115.1/9.0.100-preview.2
   Manifest Path:       C:\Users\..\aspnetcore\aspnetcore\.dotnet\sdk-manifests\9.0.100-preview.2\microsoft.net.workload.mono.toolchain.current\9.0.0-preview.2.24115.1\WorkloadManifest.json
   Install Type:        FileBased
```

**Comment by lewing** [comment]
> `HostedBlazorWebassemblyApp` sample app with threads on - installing workload does not help with the error, why do we link it with workloads?
> 
> ```
> .NET SDK:
>  Version:           9.0.100-preview.2.24112.1
>  Commit:            ab44b49a39
>  Workload version:  9.0.100-manifests.18bf7498
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.22621
>  OS Platform: Windows
>  RID:         win-x64
>  Base Path:   C:\Users\..\aspnetcore\aspnetcore\.dotnet\sdk\9.0.100-preview.2.24112.1\
> 
> .NET workloads installed:
>  [wasm-tools]
>    Installation Source: SDK 9.0.100-preview.2
>    Manifest Version:    9.0.0-preview.2.24115.1/9.0.100-preview.2
>    Manifest Path:       C:\Users\..\aspnetcore\aspnetcore\.dotnet\sdk-manifests\9.0.100-preview.2\microsoft.net.workload.mono.toolchain.current\9.0.0-preview.2.24115.1\WorkloadManifest.json
>    Install Type:        FileBased
> ```

Yeah, I'm not 100% sure this failure is related but making sure the workload is installed for mt will reduce configurations we're testing for MT immediately which will reduce the search space.
