### ISSUE TITLE
Excessive exceptions generated in StackTraceSymbols when using Portable PDB

### ISSUE THREAD

**Issue by wasabii** [dotnet/runtime#98506]
I have discovered a situation when attempting to build and use a portable PDB file which is causing a performance degredation in my application by emitting unneccessary exceptions when collecting stack traces (for exceptions).

https://github.com/dotnet/runtime/blob/bd5f6eb73f6dffe91386f75d3ed5531ddcb2aeb6/src/libraries/System.Diagnostics.StackTrace/src/System/Diagnostics/StackTraceSymbols.cs#L66

There is at least one situation where this code can be entered into with a handle of value 0x06000000. That is, technically, a nil token, but with an invalid row ID. In the case I have observed it is because a dynamic method is on the stack and that dynamic method is attached to an existing type from an assembly with an associated portable PDB.

Thus the check in StackTraceSymbols which checks if it's Kind == MethodDef succeeds. The code continues, converts it to a MethodDebugInformation token, and then attempts to look it up from the MetadataReader, which then calls Throw.OutOfBounds. Which causes another exception.

The problem seems to appear all the way back to .NET 6.

**Comment by tommcdon** [comment]
cc @mikem8361

**Comment by mikem8361** [comment]
Do you have a simple app that repro's this problem (with a dynamic method on stack, etc)?

**Comment by jkotas** [comment]
Minimal repro - copy&paste it into default console template:
```
using System.Reflection.Emit;

var dm = new DynamicMethod(
    "MyMethod",
    typeof(object),
    null,
    typeof(Program), true);

var stackTrace = typeof(Environment).GetMethod("get_StackTrace");
var il = dm.GetILGenerator();
il.Emit(OpCodes.Call, stackTrace);
il.Emit(OpCodes.Pop);
il.Emit(OpCodes.Call, stackTrace);
il.Emit(OpCodes.Ret);

var a = dm.CreateDelegate<Func<object>>();
Console.WriteLine(a());
```

When run under windbg, you should see exceptions at:
```
coreclr!IL_Throw+0xb9 [D:\a\_work\1\s\src\coreclr\vm\jithelpers.cpp @ 4247] 
System_Reflection_Metadata!System.Reflection.Throw.OutOfBounds+0x48 [/_/src/libraries/System.Reflection.Metadata/src/System/Reflection/Throw.cs @ 167] 
System_Reflection_Metadata!System.Reflection.Metadata.Ecma335.MethodDebugInformationTableReader.GetSequencePoints+0x5c [/_/src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/PortablePdb/Tables.Debug.cs @ 106] 
System_Reflection_Metadata!System.Reflection.Metadata.MethodDebugInformation.get_SequencePointsBlob+0x1e [/_/src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/PortablePdb/MethodDebugInformation.cs @ 35] 
System_Diagnostics_StackTrace!System.Diagnostics.StackTraceSymbols.GetSourceLineInfo+0xf9 [/_/src/libraries/System.Diagnostics.StackTrace/src/System/Diagnostics/StackTraceSymbols.cs @ 71] 
System_Private_CoreLib!System.Diagnostics.StackFrameHelper.InitializeSourceInfo+0x1c5 [/_/src/coreclr/System.Private.CoreLib/src/System/Diagnostics/StackFrameHelper.cs @ 142] 
System_Private_CoreLib!System.Diagnostics.StackTrace.CaptureStackTrace+0x43 [/_/src/coreclr/System.Private.CoreLib/src/System/Diagnostics/StackTrace.CoreCLR.cs @ 64] 
System_Private_CoreLib!System.Diagnostics.StackTrace..ctor+0x13 [/_/src/libraries/System.Private.CoreLib/src/System/Diagnostics/StackTrace.cs @ 46] 
System_Private_CoreLib!System.Environment.get_StackTrace+0x1c [/_/src/libraries/System.Private.CoreLib/src/System/Environment.cs @ 225] 
repro!DynamicClass.MyMethod()+0x1e
repro!Program.<Main>$+0x204 [C:\repro\Program.cs @ 17] 
```

**Comment by mikem8361** [comment]
@jkotas thanks for the easy repro!
