### ISSUE TITLE
Unhandled exception. System.Exception: Profilee returned exit code 139 instead of expected exit code 100

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#98500]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=567850
Build error leg or test failing: profiler/multiple/multiple/multiple.sh
Pull request: https://github.com/dotnet/runtime/pull/98351

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Unhandled exception. System.Exception: Profilee returned exit code 139 instead of expected exit code 100",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=567850
**Error message validated:** `[Unhandled exception. System.Exception: Profilee returned exit code 139 instead of expected exit code 100`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 2/15/2024 3:58:36 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[572193](https://dev.azure.com/dnceng-public/public/_build/results?buildId=572193)|dotnet/runtime|[profiler.multiple.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=572193&view=ms.vss-test-web.build-test-results-tab&runId=13709726&resultId=114001)|dotnet/runtime#98681|
|[571926](https://dev.azure.com/dnceng-public/public/_build/results?buildId=571926)|dotnet/runtime|[profiler.multiple.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=571926&view=ms.vss-test-web.build-test-results-tab&runId=13703978&resultId=114001)|dotnet/runtime#98660|
|[571544](https://dev.azure.com/dnceng-public/public/_build/results?buildId=571544)|dotnet/runtime|[profiler.multiple.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=571544&view=ms.vss-test-web.build-test-results-tab&runId=13693324&resultId=114001)|dotnet/runtime#98484|
|[570181](https://dev.azure.com/dnceng-public/public/_build/results?buildId=570181)|dotnet/runtime|[profiler.multiple.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=570181&view=ms.vss-test-web.build-test-results-tab&runId=13648582&resultId=114001)|dotnet/runtime#98573|
|[570165](https://dev.azure.com/dnceng-public/public/_build/results?buildId=570165)|dotnet/runtime|[profiler.multiple.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=570165&view=ms.vss-test-web.build-test-results-tab&runId=13648072&resultId=114001)|dotnet/runtime#98580|
|[570057](https://dev.azure.com/dnceng-public/public/_build/results?buildId=570057)|dotnet/runtime|[profiler.multiple.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=570057&view=ms.vss-test-web.build-test-results-tab&runId=13645744&resultId=114001)|dotnet/runtime#97135|
|[569974](https://dev.azure.com/dnceng-public/public/_build/results?buildId=569974)|dotnet/runtime|[profiler.multiple.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=569974&view=ms.vss-test-web.build-test-results-tab&runId=13644374&resultId=114001)|dotnet/runtime#97529|
|[569936](https://dev.azure.com/dnceng-public/public/_build/results?buildId=569936)|dotnet/runtime|[profiler.multiple.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=569936&view=ms.vss-test-web.build-test-results-tab&runId=13643444&resultId=114001)|dotnet/runtime#91764|
|[569660](https://dev.azure.com/dnceng-public/public/_build/results?buildId=569660)|dotnet/runtime|[profiler.multiple.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=569660&view=ms.vss-test-web.build-test-results-tab&runId=13637140&resultId=114001)|dotnet/runtime#98563|
|[569132](https://dev.azure.com/dnceng-public/public/_build/results?buildId=569132)|dotnet/runtime|[profiler.multiple.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=569132&view=ms.vss-test-web.build-test-results-tab&runId=13620942&resultId=113695)|dotnet/runtime#98545|
|[568776](https://dev.azure.com/dnceng-public/public/_build/results?buildId=568776)|dotnet/runtime|[profiler.multiple.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=568776&view=ms.vss-test-web.build-test-results-tab&runId=13612006&resultId=113692)|dotnet/runtime#98332|
|[568489](https://dev.azure.com/dnceng-public/public/_build/results?buildId=568489)|dotnet/runtime|[profiler.multiple.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=568489&view=ms.vss-test-web.build-test-results-tab&runId=13604432&resultId=113692)|dotnet/runtime#98508|
|[568219](https://dev.azure.com/dnceng-public/public/_build/results?buildId=568219)|dotnet/runtime|[profiler.multiple.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=568219&view=ms.vss-test-web.build-test-results-tab&runId=13596810&resultId=113692)|dotnet/runtime#98512|
|[567850](https://dev.azure.com/dnceng-public/public/_build/results?buildId=567850)|dotnet/runtime|[profiler.multiple.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=567850&view=ms.vss-test-web.build-test-results-tab&runId=13581946&resultId=113692)|dotnet/runtime#98351|
|[567664](https://dev.azure.com/dnceng-public/public/_build/results?buildId=567664)|dotnet/runtime|[profiler.multiple.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=567664&view=ms.vss-test-web.build-test-results-tab&runId=13575246&resultId=113692)|dotnet/runtime#98485|
|[567442](https://dev.azure.com/dnceng-public/public/_build/results?buildId=567442)|dotnet/runtime|[profiler.multiple.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=567442&view=ms.vss-test-web.build-test-results-tab&runId=13566930&resultId=113692)|dotnet/runtime#98474|
|[565017](https://dev.azure.com/dnceng-public/public/_build/results?buildId=565017)|dotnet/runtime|[profiler.handles.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=565017&view=ms.vss-test-web.build-test-results-tab&runId=13501058&resultId=113785)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|16|17|

**Comment by tommcdon** [comment]
@davmason would you mind taking a look?

**Comment by davmason** [comment]
There's a bug in the test, it only waits for 2 profilers to detach before exiting and there are 3 profilers attached. Sometimes the 3rd profiler requests detach after the runtime has exited
