### ISSUE TITLE
[android] .NET Preview 2, AOT w/ LLVM fails with `mini-llvm.c:8581, condition elems <= MAX_VECTOR_ELEMS / 2' not met`

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/runtime#98501]
### Description

We first noticed this happening here: https://github.com/xamarin/xamarin-android/pull/8716

It appears any `Release` build using `-p:EnableLLVM` fails with:
```
Precompiling failed for /Users/runner/work/1/s/tests/Mono.Android-Tests/Runtime-Microsoft.Android.Sdk/obj/Release/net9.0-android/android-x64/linked/System.Private.CoreLib.dll with exit code 134.
Mono Ahead of Time compiler - compiling assembly /Users/runner/work/1/s/tests/Mono.Android-Tests/Runtime-Microsoft.Android.Sdk/obj/Release/net9.0-android/android-x64/linked/System.Private.CoreLib.dll
AOTID 22717FEB-1950-D4F1-D7BF-6FD5FD5FFC96
* Assertion at /Users/runner/work/1/s/src/mono/mono/mini/mini-llvm.c:8581, condition `elems <= MAX_VECTOR_ELEMS / 2' not met
```

### Reproduction Steps

* `dotnet new android`
* `dotnet build -c Release -p:EnableLLVM=true`

### Expected behavior

`Release` builds using `-p:EnableLLVM` succeed.

### Actual behavior

`Release` builds using `-p:EnableLLVM` fail with an assertion.

### Regression?

Yes, this was working previously in .NET 9 and .NET 8.

### Known Workarounds

Use `-p:EnableLLVM=false`.

### Configuration

.NET SDK 9.0.0-preview.2.24109.4
.NET runtime 9.0.0-preview.2.24109.4

Changes: https://github.com/dotnet/installer/compare/fb7b9a4b9e...ab44b49a39
Changes: https://github.com/dotnet/runtime/compare/d40c654c27...a79c62ddc8

### Other information

Here is a `.binlog`: 

[run-Mono.Android.NET_Tests-AotLlvm.binlog.zip](https://github.com/dotnet/runtime/files/14299394/run-Mono.Android.NET_Tests-AotLlvm.binlog.zip)

**Comment by jonathanpeppers** [comment]
/cc @steveisok 

I'll also try the newest build in case there is a recent fix for this.

**Comment by steveisok** [comment]
@vargaz can you please take a look?

**Comment by vargaz** [comment]
Should be fixed by this:
https://github.com/dotnet/runtime/pull/98320

**Comment by lewing** [comment]
https://github.com/xamarin/xamarin-android/pull/8716 is green now, closing

**Comment by jonathanpeppers** [comment]
I don't know why, but Maestro PRs only trigger CI like 50% of the time. It should have ~46 green checks when it's green.

I queued one, and will reopen if there is still an issue here:

https://github.com/xamarin/xamarin-android/pull/8716#issuecomment-1946995081
