### ISSUE TITLE
Possible DependencyInjection service scope validation regression, blocking dependency flow into dotnet/aspnetcore

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/runtime#98551]
### Description

The automated dependency update PR from `runtime` to `aspnetcore` is currently failing: https://github.com/dotnet/aspnetcore/pull/54055

Two tests are failing:

 * `WebApplicationBuilder_EnablesServiceScopeValidationByDefaultInDevelopment` (https://github.com/dotnet/aspnetcore/blob/9db62024cbe3c3cb28efe372541fc1bdfcdb375e/src/DefaultBuilder/test/Microsoft.AspNetCore.Tests/WebApplicationTests.cs#L1784)
 * `Build_InDevelopment_ConfiguresWithServiceProviderWithScopeValidation` (https://github.com/dotnet/aspnetcore/blob/9db62024cbe3c3cb28efe372541fc1bdfcdb375e/src/Components/WebAssembly/WebAssembly/test/Hosting/WebAssemblyHostBuilderTest.cs#L95)

In both cases the failure is of the form "expected an exception to be thrown, but no exception was thrown". Example of failing build: https://github.com/dotnet/aspnetcore/runs/21630956214

I notice that this started after https://github.com/dotnet/runtime/pull/96254 was merged 2 days ago, and that PR changes the logic around service scope validation. The PR is not meant to affect the behavior (since it's only intended to add caching) but perhaps it does affect the behavior.

### Reproduction Steps

Example of failing build: https://github.com/dotnet/aspnetcore/runs/21630956214

### Expected behavior

Service scope validation behavior should be unchanged.

### Actual behavior

It no longer throws at the same time that it did before.

### Regression?

The behavior was correct in commit ad25468103550b322351efb21a45fb54566a8127, which is the last one we successfully ingested to `dotnet/aspnetcore`. The change must have happened since then.

**Comment by christiaanderidder** [comment]
I would happily have a look at this, since I authored the original PR.

**Comment by christiaanderidder** [comment]
I was able to reproduce the issue with the following test in `Microsoft.Extensions.DependencyInjection.Tests.ServiceProviderValidationTests`

```
[Fact]
public void BuildServiceProvider_ValidateOnBuild_Throws_WhenScopedIsInjectedIntoSingleton()
{
    // Arrange
    var serviceCollection = new ServiceCollection();
    serviceCollection.AddScoped<IBar, Bar>();
    serviceCollection.AddSingleton<IFoo, Foo>();

    // Act + Assert
    var aggregateException = Assert.Throws<AggregateException>(() => serviceCollection.BuildServiceProvider(new ServiceProviderOptions() { ValidateOnBuild = true, ValidateScopes = true }));
}
```

Which indeed does not throw as expected, while the following test does throw: 
```
[Fact]
public void BuildServiceProvider_ValidateOnBuild_Throws_WhenScopedIsInjectedIntoSingleton_ReverseOrder()
{
    // Arrange
    var serviceCollection = new ServiceCollection();
    serviceCollection.AddSingleton<IFoo, Foo>();
    serviceCollection.AddScoped<IBar, Bar>();

    // Act + Assert
    var aggregateException = Assert.Throws<AggregateException>(() => serviceCollection.BuildServiceProvider(new ServiceProviderOptions() { ValidateOnBuild = true, ValidateScopes = true }));
}
```

Note the difference in order of registering the dependencies).

I will address the issue and submit a PR.

**Comment by christiaanderidder** [comment]
@SteveSandersonMS The issue looks to be resolved and passes existing and new tests in the runtime repo. I don't know how to test these changes directly against the aspnetcore repo, so I could not verify them there.
