### ISSUE TITLE
NativeAOT publish fails on fi_FI.utf8 locale

### ISSUE THREAD

**Issue by De-Crypted** [dotnet/runtime#98550]
### Describe the bug
Trying to publish freshly created console application with `dotnet publish /p:PublishAot=true` produces error:
```
MSBuild version 17.9.4+90725d08d for .NET
/home/user/.nuget/packages/microsoft.dotnet.ilcompiler/8.0.2/build/Microsoft.DotNet.ILCompiler.SingleEntry.targets(9,16): error MSB4086: A numeric comparison was attempted on "$(_indexOfPeriod)" that evaluates to "−1" instead of a number, in condition "'$(_indexOfPeriod)' > -1". [/home/user/sources/project/daemon/daemon.csproj]
```

Note that the first -1 actually has "U+2212 : MINUS SIGN" printed in the console.

As a workaround locale can be set to en_US.utf8 and the publish works as expected.

### To Reproduce
On Linux machine set locale to fi_FI.utf8
Create console application with
```
dotnet new console -n app
```
Publish it with
```
dotnet publish /p:PublishAot=true
```

### Further technical details
```
.NET SDK:
 Version:           8.0.200
 Commit:            438cab6a9d
 Workload version:  8.0.200-manifests.cdf2cc8e

Runtime Environment:
 OS Name:     manjaro
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/tk/.dotnet/sdk/8.0.200/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2

.NET SDKs installed:
  8.0.200 [/home/tk/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.2 [/home/tk/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.2 [/home/tk/.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/share/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
  ```

**Comment by akoeplinger** [comment]
This regressed with https://github.com/dotnet/runtime/commit/413efe748ac4c5daabf087ed8ed0d59c511e5cf2.

It looks like `<_indexOfPeriod>$(_originalTargetOS.IndexOf('.'))</_indexOfPeriod>` causes the int->string conversion to happen with current culture.

**Comment by akoeplinger** [comment]
We can't use `.ToString(CultureInfo.InvariantCulture)` since `CultureInfo` is not allowed in msbuild.

A workaround I found is using `.ToString('0;-0')` to use an explicit minus sign for negative numbers in the format string.
Or we could just duplicate the `.IndexOf()` call instead of using the msbuild property as an intermediate.

Any preferences?

**Comment by tmds** [comment]
> .NET SDKs installed:
  8.0.200 [/home/tk/.dotnet/sdk]

I wonder if you're seeing this because of https://github.com/dotnet/msbuild/pull/9449.

If you `export MSBUILDDISABLEFEATURESFROMVERSION=17.10`, does it work?

**Comment by akoeplinger** [comment]
@tmds I don't think so, that PR only changes the culture of the Exec task which is not used here.

**Comment by MichalStrehovsky** [comment]
> We can't use `.ToString(CultureInfo.InvariantCulture)` since `CultureInfo` is not allowed in msbuild.
> 
> A workaround I found is using `.ToString('0;-0')` to use an explicit minus sign for negative numbers in the format string. Or we could just duplicate the `.IndexOf()` call instead of using the msbuild property as an intermediate.
> 
> Any preferences?

Maybe duplicating would be better. We can use `Contains` to make a it bit more readable, although it still looks like LISP.

```xml
<_originalTargetOS Condition="$(_originalTargetOS.Contains('.'))">$(_originalTargetOS.SubString(0, $(_originalTargetOS.IndexOf('.'))))</_originalTargetOS>
```

**Comment by akoeplinger** [comment]
Yeah I like Contains better too.

**Comment by akoeplinger** [comment]
https://github.com/dotnet/runtime/pull/98552

**Comment by tmds** [comment]
> I don't think so, that PR only changes the culture of the Exec task which is not used here.

I don't suspect that either, though it's a weird coincidence that this is reported with 8.0.200 which is the first SDK to include that change.

I'm surprised the result of the evaluation depends on the system culture. I had expected msbuild to be using the invariant culture when it evaluates them.

**Comment by akoeplinger** [comment]
> If you export MSBUILDDISABLEFEATURESFROMVERSION=17.10, does it work?

I tried that and it didn't fix the issue.

**Comment by danmoseley** [comment]
@rainersigwald 

> It looks like <_indexOfPeriod>$(_originalTargetOS.IndexOf('.'))</_indexOfPeriod> causes the int->string conversion to happen with current culture:

this seems like something MSBuild should consider fixing -- by whatever trick inside the binder. Anything culture-specific by default in a build seems like a bug to me. wdyt?
