### ISSUE TITLE
FileNotFoundExceptions caused by Windows Update installing updates for .NET

### ISSUE THREAD

**Issue by markoweb2** [dotnet/runtime#98576]
### Description

Ever since I moved my app from .NET Framework 4.x to .NET 6, I keep getting reports each month of FileNotFoundExceptions right around the time Windows Update runs on machines. I waited patiently and upgraded to .NET 8, hoping these issues would be ironed out over time, but still they persist.
I find it unacceptable, that running Windows Updates breaks applications already running on the system.
My app runs in studios that are open from 8AM to 10PM and the app is used for the entire day non stop.
Windows Updates have active hours set for the same duration as the studio open times, but all that does is avoid a restart during those hours. Updates are still installed whenever Windows sees fit during the day and this breaks my app.

### Reproduction Steps

1) Write a business app that actually does something useful. **Publish it in Framework dependent mode.**
2) Install win 11 + .NET 8.0.0 + your app
3) Run the app
4) Let Windows Update update .NET to 8.0.1 for example, but don't restart the computer
5) Try using some functions inside the app, then notice all sorts of different FileNotFoundExceptions

### Expected behavior

I expect the application to keep running without issues like it did with .NET Framework.
I would expect Windows Update to detect that a .NET app is currently running, thus not actively patch files that are currently in use. Rather prepare a file patch list and apply it when the system restarts.

Lets be honest here, every patch Tuesday involves a Cumuluative Update for Windows itself. So a restart is a 100% guaranteed requirement. Thus it is easy to make Windows patch the .NET files during the restart of the system.

### Actual behavior

What Windows Update does during the .NET update, is install newer versions of .NET core libraries. These are libraries that are placed in GAC for example. My running application is expecting to find version 8.0.0 binaries, as those were present when the app loaded, but after Windows Update runs mid-day, those versions are no longer present, and for what ever reason .NET is not clever enough to start using the newer 8.0.1 versions until the app is restarted (or maybe it required a full system restart, not sure at the moment).

Here are some examples of the exceptions thrown:

* System.Net.Mail.SmtpException: Failure sending mail.
---> System.IO.FileNotFoundException:
File name: 'System.Net.ServicePoint, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at System.Net.TlsStream..ctor(NetworkStream stream, Socket socket, String host, X509CertificateCollection clientCertificates)
   at System.Net.Mail.SmtpConnection.GetConnection(String host, Int32 port)
   at System.Net.Mail.SmtpTransport.GetConnection(String host, Int32 port)
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   
* System.IO.FileNotFoundException:
File name: 'System.Xml.XDocument, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at DocumentFormat.OpenXml.Packaging.PackageUriHandlingExtensions.MalformedUriHandlingPackage.System.IDisposable.Dispose()
   at DocumentFormat.OpenXml.Packaging.PackageFeatureCollection.DocumentFormat.OpenXml.Features.IContainerDisposableFeature.Dispose()
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Dispose(Boolean disposing)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Dispose()
   
 * ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.FileSystem.DriveInfo, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.IO.FileSystem.DriveInfo, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

* **Majority of errors were with this file in .NET 6 era**
System.IO.FileNotFoundException: Could not load file or assembly 'System.Security.Cryptography.Csp, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Security.Cryptography.Csp, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

* System.IO.FileNotFoundException: Could not load file or assembly 'System.Drawing.Primitives, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Drawing.Primitives, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

(I copied over exceptions from both .NET 6 and .NET 8 era, so the missing file version numbers are shown accordingly)

As you can see the exceptions are all over the place and I can't tell why some studios get one exception vs the other.
Maybe one studio gets the System.Security.Cryptography.Csp file not found, while another studio at the same time gets System.Net.ServicePoint file not found.

Maybe it is related to how exactly the app was used during the update, so maybe some files were locked during the update, I don't know...

Also notice that all exceptions are with the core System.x.y libraries, so nothing to do with external nuget packages or such.

The exceptions won't go away until you restart the app (or the system), so trying to run the same function like an hour later will throw up the same error.

### Regression?

.NET Framework did not have this issue.

### Configuration

Most likely all ".NET" versions are affected - 5, 6, 7, 8. I have specifically ran version 6 and 8.
OS = both Win 10 and Win 11 experience this issue.
Architecture = x64
Not configuration specific issue, but a general issue in how Windows Update patches .NET

**Comment by danmoseley** [comment]
@joeloff  is this the right repo for this issue?

**Comment by joeloff** [comment]
Probably, we don't have a centralized location for setup because it's spread across many repos. We need to start tracking this type of issue in one place, we've multiple issues related to how AU interacts with running applications.

[This](https://github.com/dotnet/runtime/issues/60144) is probably the issue with the most information, though there's more to share.

It's also similar to https://github.com/dotnet/runtime/issues/90869

A dedicated label for this would help so we can find all of them

**Comment by joeloff** [comment]
And another related one: https://github.com/dotnet/runtime/issues/100452
