### ISSUE TITLE
JIT should fold repeated bounds checks for readonly access

### ISSUE THREAD

**Issue by Suchiman** [dotnet/runtime#98583]
With code such as the following, you'll end up with 4 bounds check, one for every array access. This can be avoided by checking index 4 first but the JIT should be able to optimize this without having to bend the code as there are no differences in observable side effects for readonly code

```csharp
    static bool Test2(string str)
    {
        return 
            str[1] == 't' &&
            str[2] == 'y' &&
            str[3] == 'p' &&
            str[4] == 'e';
    }
```

**Comment by jilles-sg** [comment]
There are two observable side effects in this code:

- If a comparison results in not equal, the method returns false immediately, so a lower length is sufficient to avoid an exception. For example, `Test2(".t")` will throw but `Test2("..")` will not.
- The line number in the thrown exception.

Replicating this behaviour while having a fast path for `str.Length > 4` seems like it will result in more machine code, so it may not be a performance win over the whole application.

I suggest changing the condition to something like `str.AsSpan(1, 4).SequenceEqual("test")` or `str.AsSpan(1).StartsWith("test", StringComparison.Ordinal)` depending on the exact exception behaviour desired.
