### ISSUE TITLE
Add `Volatile.Read(in X)` overloads: 

### ISSUE THREAD

**Issue by WalkerCodeRanger** [dotnet/runtime#98592]
### Background and motivation

All the `Volatile.Read()` overloads take their parameters with `ref`. However, logically, they perform a read, and `in` should be sufficient. If one has a `readonly` member on a struct, that member should be able to perform a volatile read on a member of the struct value. However, currently one gets `CS1605 Cannot use '<Member>' as a ref or out value because it is read-only`. This forces one to not mark the struct member(s) as `readonly`.

I believe it would be a breaking change to change the `Read(ref X)` methods to `Read(in X)`.  So instead I propose adding overloads that take their parameter with `in`.

### API Proposal

```csharp
namespace System.Threading;

public static class Volatile
{
    public static int Read (in int location);
    // Along with similar overloads for all the other 
}
```

### API Usage

```csharp
public struct Example
{
    public readonly bool Value => Volatile.Read(in _value);

    private bool _value;
}
```

### Alternative Designs

This can be worked around using the `Unsafe` class. The example above would become:
```csharp
public struct Example
{
    public readonly bool Value => Volatile.Read(ref Unsafe.AsRef(in _value));

    private bool _value;
}
```

### Risks

I believe this should be safe and not introduce any breaking changes or issues.

**Comment by stephentoub** [comment]
All the relevant Volatile methods were changed in .NET 8 to take a `ref readonly` instead of `ref`.

What version are you using?

**Comment by WalkerCodeRanger** [comment]
I didn't realize that. The [online docs](https://learn.microsoft.com/en-us/dotnet/api/system.threading.volatile.read?view=net-8.0) don't seem to indicate that.

We are currently on .NET 7. I have confirmed you can call `Volatile.Read(in _value)` in .NET 8.

Given that, I am closing this request.
