### ISSUE TITLE
Performance issue with generic method returning struct ref

### ISSUE THREAD

**Issue by sicusa** [dotnet/runtime#98598]
### Description

I'm trying to implement my Entity-Component-System framework (https://github.com/sicusa/Sia.NET). Recently I noticed a strange  performance issue pertaining to generic method:

In https://github.com/sicusa/Sia.NET/blob/main/Sia/Entities/EntityRef.cs, there's a method to get component `ref` by its type:

```C#
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public unsafe ref TComponent Get<TComponent>()
{
    nint offset = Descriptor.GetOffset<TComponent>();
    if (offset == -1) {
        throw new ComponentNotFoundException("Component not found: " + typeof(TComponent));
    }
    ref var entityRef = ref Host.GetSpan(Slot)[0];
    return ref Unsafe.AsRef<TComponent>(
        (void*)((IntPtr)Unsafe.AsPointer(ref entityRef) + offset));
}
```

An ECS framework would normally manage a lot of entities/components in continuous memory and user iterate through them using query object. Here I have 100,000 entities with only one integer as entity component (https://github.com/sicusa/Sia.NET/blob/main/Sia.Examples/Example14_Parallel.cs):

```C#
foreach (var entity in query) {
    entity.Get<int>()++;
}
```

It takes 0.023 seconds on average. But when I copy the code of Get method directly into foreach loop, the performance is improved more than 100%, which indicates that inlining or other runtime optimizations may not take effect as intended:

```C#
foreach (var entity in query) {
    // entity.Get<int>()++;
    nint offset = entity.Descriptor.GetOffset<int>();
    if (offset == -1) {
        throw new ComponentNotFoundException("Component not found: " + typeof(int));
    }
    ref var entityRef = ref entity.Host.GetSpan(entity.Slot)[0];
    unsafe {
        ref var v = ref Unsafe.AsRef<int>(
            (void*)((IntPtr)Unsafe.AsPointer(ref entityRef) + offset));
        v++;
    }
}
```

### Configuration

Version: .NET 8.0
OS: macOS 14.2.1
Machine: MacBook Pro M2 Max

**Comment by huoyaoyuan** [comment]
Note: 
Converting a `ref` to GC-managed position with `Unsafe.AsPointer` is not GC safe. You should do pointer arithmetic in managed reference, with the help of `System.Runtime.CompilerServices.Unsafe`.

If you want the span to do bound check for you:
```csharp
ref MemoryMarshal.Cast<byte, T>(span)[offset];
```
This won't work if T is reference type, or a struct contains fields of reference type. This can be indicated by `RuntimeHelpers.IsReferenceOrContainsReferences<T>`. For reference field, you need to manually recreate the span:

```csharp
MemoryMarshal.CreateSpan(ref Unsafe.As<byte, T>(ref MemoryMarshal.GetReference(span)), span.Length / Unsafe.SizeOf<T>())
```

 If you want to bypass the range check:

```csharp
ref Unsafe.Add(ref Unsafe.As<byte, T>(ref MemoryMarshal.GetReference(span)), offset);
```


Performance around looping on a span has been observed as sensitive to code alignment issues. You may manually inspect the generated assembly code and find if there's anything suspicious.

**Comment by sicusa** [comment]
> Note: Converting a `ref` to GC-managed position with `Unsafe.AsPointer` is not GC safe. You should do pointer arithmetic in managed reference, with the help of `System.Runtime.CompilerServices.Unsafe`.
> 
> If you want the span to do bound check for you:
> 
> ```cs
> ref MemoryMarshal.Cast<byte, T>(span)[offset];
> ```
> 
> This won't work if T is reference type, or a struct contains fields of reference type. This can be indicated by `RuntimeHelpers.IsReferenceOrContainsReferences<T>`. For reference field, you need to manually recreate the span:
> 
> ```cs
> MemoryMarshal.CreateSpan(ref Unsafe.As<byte, T>(ref MemoryMarshal.GetReference(span)), span.Length / Unsafe.SizeOf<T>())
> ```
> 
> If you want to bypass the range check:
> 
> ```cs
> ref Unsafe.Add(ref Unsafe.As<byte, T>(ref MemoryMarshal.GetReference(span)), offset);
> ```
> 
> Performance around looping on a span has been observed as sensitive to code alignment issues. You may manually inspect the generated assembly code and find if there's anything suspicious.

thanks for your help!
