### ISSUE TITLE
System.Text.Json source generator doesn't handle `ReadOnlySpan<T>` properties correctly

### ISSUE THREAD

**Issue by jp2masa** [dotnet/runtime#98590]
### Description

When using the System.Text.Json source generator with `ReadOnlySpan<T>` properties, the generated code is invalid. Also, `IgnoreReadOnlyProperties` doesn't skip getter-only properties.

### Reproduction Steps

```cs
    class Test(string value)
    {
        public string Value =>
            value;

        public ReadOnlySpan<char> AsSpan =>
            value;
    }

    [JsonSourceGenerationOptions(IgnoreReadOnlyProperties = true)]
    [JsonSerializable(typeof(Test))]
    internal partial class AppJsonSerializerContext : JsonSerializerContext
    {
    }
```

### Expected behavior

No compilation error. Also, if `IgnoreReadOnlyProperties` is supposed to ignore getter-only properties, both properties above should be skipped.

### Actual behavior

Multiple compilation errors on generated code, because `ReadOnlySpan<char>` was used as a generic argument.

Example:

> CS0306 The type 'ReadOnlySpan<char>' may not be used as a type argument

<details>
<summary>Relevant part of the generated code</summary>

```cs
        private static global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[] TestPropInit(global::System.Text.Json.JsonSerializerOptions options)
        {
            var properties = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[2];

            var info0 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<string>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::TestApp.Test),
                Converter = null,
                Getter = static obj => ((global::TestApp.Test)obj).Value,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Value",
                JsonPropertyName = null
            };
            
            properties[0] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<string>(options, info0);

            var info1 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::System.ReadOnlySpan<char>>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::TestApp.Test),
                Converter = null,
                Getter = static obj => ((global::TestApp.Test)obj).AsSpan,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "AsSpan",
                JsonPropertyName = null
            };
            
            properties[1] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::System.ReadOnlySpan<char>>(options, info1);

            return properties;
        }
```

</details>

### Configuration

.NET 8.0.200

Also tried using the latest preview version of `System.Text.Json` from NuGet.

**Comment by elgonzo** [comment]
> Also, `IgnoreReadOnlyProperties` doesn't skip getter-only properties.

It does. The issue you are seeing here is specifically with ReadOnlySpan/Span-typed properties/fields, not with getter-only properties in general. Commenting out the `AsSpan` property, serializing a `Test` instance will result in an empty json object `{}`.

If you see a getter-only property (that is not a Span type) not being ignored, please post a code example that reproduces this behavior.

**Comment by eiriktsarpalis** [comment]
`IgnoreReadOnlyProperties` is a run-time setting that can be overridden, as such it has no impact as to what metadata is being generated. That being said, I was surprised to discover that it's not even possible to avoid generation using a `JsonIgnore` attribute. We should try to fix this in the future. 

In the meantime as a workaround you could either mark the property internal or convert it to a method.

**Comment by jp2masa** [comment]
Unfortunately, it's not my code, but it's open source, so I can fork it. Would skipping all properties whose type `IsByRef` be an acceptable solution? The generated code will always be invalid, I think.

The only alternative I can think of would be implementing an API for conversion or explicit casting of types like:

```cs
[JsonSourceGenerationConvert(typeof(ReadOnlySpan<char>), typeof(string))]
```

In this case, the property type would be replaced with `string`, and conversion would be done in the generated code.

I was also a bit disappointed to find that I can't declare a member with the same name as the generated one to replace it, as the generator doesn't care if it's creating a duplicate declaration. Is this by design, or would it be acceptable to skip already declared members? This would make it much easier to workaround bugs or customize generated code.

If it helps, I can work on a PR to fix this.

**Comment by eiriktsarpalis** [comment]
More likely, it would involve updating the SG so that all ref-like property types get skipped.
