### ISSUE TITLE
Why doesn't C++/CLI write the name of the library when calling extern functions?

### ISSUE THREAD

**Issue by dadavadd** [dotnet/runtime#98606]
![image](https://github.com/dotnet/runtime/assets/111659964/688026b2-65c1-4db5-b180-8d8054d51390)
Why is the library not specified here and this is not considered an error? After all, when I copy this code into my project, it is considered error CS0591.

![image](https://github.com/dotnet/runtime/assets/111659964/fb192818-8ace-4df0-99b3-67c67d242d3b)

**Comment by jkotas** [comment]
Managed C++ produces mixed mode binaries. The IL to C# decompiler is not fully accurate for the mixed mode binaries.

Managed C++ compiler is the only compiler that is able to produce the mixed mode binaries. The mixed mode binaries are non-portable and Windows specific. They contain both managed code (IL) and native code (e.g. x86/x64/arm64) in the same file. The managed code is able to reference the native code in the binary by encoding the offset of the native code in metadata RVA field. You can find the details of how it works by looking for "[EarlyBound PInvoke](https://github.com/dotnet/runtime/blob/a6396867c276e61b48df4db498750f8f58f7de33/src/coreclr/vm/method.hpp#L2751)" in the coreclr implementation.

**Comment by dadavadd** [comment]
> Managed C++ produces mixed mode binaries. The IL to C# decompiler is not fully accurate for the mixed mode binaries.
> 
> Managed C++ compiler is the only compiler that is able to produce the mixed mode binaries. The mixed mode binaries are non-portable and Windows specific. They contain both managed code (IL) and native code (e.g. x86/x64/arm64) in the same file. The managed code is able to reference the native code in the binary by encoding the offset of the native code in metadata RVA field. You can find the details of how it works by looking for "[EarlyBound PInvoke](https://github.com/dotnet/runtime/blob/a6396867c276e61b48df4db498750f8f58f7de33/src/coreclr/vm/method.hpp#L2751)" in the coreclr implementation.

That is, I won’t be able to get the exact C# code in any decompiler?

**Comment by jkotas** [comment]
Correct. There is no way to represent the code produced by managed C++ in C#.

**Comment by dadavadd** [comment]
> Correct. There is no way to represent the code produced by managed C++ in C# in this case.

Thank

**Comment by jkotas** [comment]
> Is a combination of C++/CLI and NativeAOT being considered?

No. We have no plans to add C++/CLI support in native AOT. (It would be complicated to implement it and it would not produce single-file binary. The managed C++ binary would have to stay as a separate file.)
