### ISSUE TITLE
[browser][MT] lock_thread: g_assert (thread->longlived->synch_cs)

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#98604]
### Error Blob

```json
{
  "ErrorMessage": "",
  "BuildRetry": false,
  "ErrorPattern": "Assertion.*threads.c:517",
  "ExcludeConsoleLog": false
}
```

### Reproduction Steps

[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-98555-merge-dbe932cd55094d9ab0/WasmTestOnBrowser-System.Text.Json.Tests/1/console.0759917b.log?helixlogtype=result)
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=569381
```
[14:59:35] info: [STRT] System.Text.Json.Tests.JsonDocumentTests.ParseJson_UnseekableStream_Async_WithBOM(compactData: False, type: DeepTree, jsonString: "[\n  {\n    \"_id\": \"5af4bfbe93ba383385d9047a\","···)
[14:59:35] fail: [0x2e440000-long 14:59:35.778] [MONO] * Assertion at /__w/1/s/src/mono/mono/metadata/threads.c:517, condition `<disabled>' not met
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=569381
**Error message validated:** `[Assertion.*threads.c:517`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 2/17/2024 12:34:27 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[595316](https://dev.azure.com/dnceng-public/public/_build/results?buildId=595316)|dotnet/runtime|[WasmTestOnBrowser-System.Net.WebSockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=595316&view=ms.vss-test-web.build-test-results-tab&runId=14402964&resultId=187242)|dotnet/runtime#98986|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|1|

**Comment by lambdageek** [comment]
One idea might be to change `init_thread_object` from this:

```c
	thread->longlived = g_new0 (MonoLongLivedThreadData, 1);
	init_longlived_thread_data (thread->longlived);
```

to this

```c
	MonoLongLivedThreadData *lltd = g_new0 (MonoLongLivedThreadData, 1)
	init_longlived_thread_data (lltd);
	thread->longlived = lltd;
```

because otherwise some thread might see `thread->longlived != NULL && thread->longlived->synch_cs == NULL`.

With the fixed order, the membarrier inside `init_longlived_thread_data` will ensure that if `thread->longlived != NULL` then `thread->longlived->synch_cs != NULL`.

**Comment by pavelsavara** [comment]
no more occurrences, please reopen if you see it again
