### ISSUE TITLE
Segmentation fault in System.Runtime.Serialization.Formatters.Tests

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#98609]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=570605
Build error leg or test failing: System.Runtime.Serialization.Formatters.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/96370

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": " Segmentation fault.*System.Runtime.Serialization.Formatters.Tests",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=570605
**Error message validated:** `[ Segmentation fault.*System.Runtime.Serialization.Formatters.Tests`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 2/17/2024 3:21:22 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by jkotas** [comment]
cc @JulieLeeMSFT This issue is not diagnosable because of missing crash dump.

**Comment by hoyosjs** [comment]
cc: @mikem8361

**Comment by jeffhandley** [comment]
Closing as there haven't been recent hits, and it wasn't diagnosable.
