### ISSUE TITLE
[API Proposal]: `X86Base.Rep*` intrinsics

### ISSUE THREAD

**Issue by MichalPetryka** [dotnet/runtime#98621]
### Background and motivation

Modern X64 CPUs provide fast version of the `rep/repe/repne` family of instructions which are utilized by many high performance methods like the native `memcpy/memmove` implementations.
While their performance characteristics might be hard to estimate, in some cases they can be better than manually written SIMD assembly due to the microcode having CPU specific optimizations.
Since their performance depends on CPU generations and CPUID bits set, being able to use them conditionally with the JIT could be useful for highly optimized code or internal runtime code like `Buffer.Memmove` due to not requiring runtime checks.

### API Proposal

```csharp
namespace System.Runtime.Intrinsics.X86
{
    public class X86Base
    {
        public static bool EnhancedRepMovsbStosb { get; } // CPUID EAX=7, ECX=0: EBX[9]
        public static bool FastShortRepMovsb { get; } // CPUID EAX=7, ECX=0: EDX[4]
        public static bool FastZeroLengthRepMovsb { get; } // Intel CPUID EAX=7, ECX=1: EAX[10]
        public static bool FastShortRepStosb { get; } // Intel CPUID EAX=7, ECX=1: EAX[11], AMD CPUID EAX=80000021h: EAX[10]
        public static bool FastShortRepCmpsbScasb { get; } // Intel CPUID EAX=7, ECX=1: EAX[12]
        public static bool FastShortRepeCmpsb { get; } // AMD CPUID EAX=80000021h: EAX[11]

        public static void RepMovsb(ref byte source, ref byte destination, nuint count);
        public static void RepMovsw(ref ushort source, ref ushort destination, nuint count);
        public static void RepMovsd(ref uint source, ref uint destination, nuint count);

        public static void RepStosb(ref byte destination, byte value, nuint count);
        public static void RepStosw(ref ushort destination, ushort value, nuint count);
        public static void RepStosd(ref uint destination, uint value, nuint count);

        public static nuint RepeCmpsb(ref byte first, ref byte second, nuint count);
        public static nuint RepeCmpsw(ref ushort first, ref ushort second, nuint count);
        public static nuint RepeCmpsd(ref uint first, ref uint second, nuint count);

        public static nuint RepeScasb(ref byte memory, byte comparand, nuint count);
        public static nuint RepeScasw(ref ushort memory, ushort comparand, nuint count);
        public static nuint RepeScasd(ref uint memory, uint comparand, nuint count);

        public static nuint RepneCmpsb(ref byte first, ref byte second, nuint count);
        public static nuint RepneCmpsw(ref ushort first, ref ushort second, nuint count);
        public static nuint RepneCmpsd(ref uint first, ref uint second, nuint count);

        public static nuint RepneScasb(ref byte memory, byte comparand, nuint count);
        public static nuint RepneScasw(ref ushort memory, ushort comparand, nuint count);
        public static nuint RepneScasd(ref uint memory, uint comparand, nuint count);

        public class X64
        {
            public static void RepMovsq(ref ulong source, ref ulong destination, nuint count);

            public static void RepStosq(ref ulong destination, ulong value, nuint count);

            public static nuint RepeCmpsq(ref ulong first, ref ulong second, nuint count);

            public static nuint RepeScasd(ref ulong memory, ulong comparand, nuint count);

            public static nuint RepneCmpsq(ref ulong first, ref ulong second, nuint count);

            public static nuint RepneScasd(ref ulong memory, ulong comparand, nuint count);
        }
    }
}
```

### API Usage

```csharp
public static void FastCopy(ReadOnlySpan<byte> source, Span<byte> destination)
{
    if (source.Length != destination.Length)
    {
        throw new InvalidOperationException();
    }
    // such checks should probably be added to the runtime impl of Buffer.Memmove
    if (X86Base.EnhancedRepMovsbStosb && source.Length > 4095)
    {
        X86Base.RepMovsb(ref MemoryMarshal.GetReference(source), ref MemoryMarshal.GetReference(destination), (uint)source.Length);
    }
    else
    {
        source.CopyTo(destination);
    }
}
```

### Alternative Designs

The APIs could be exposed under a separate `Rep` class that derrives from `X86Base` to keep the API cleaner.

### Risks

Users might use it in cases where Span methods and other BCL methods would be better.

**Comment by tannergooding** [comment]
I don't think we should expose these directly, rather we could just recognize `NativeMemory.Copy` or other relevant APIs as intrinsic and do the right thing in the JIT, which is what C/C++ compilers do to support the same.

CC. @jkotas

**Comment by jkotas** [comment]
> we could just recognize NativeMemory.Copy or other relevant APIs as intrinsic and do the right thing in the JIT, which is what C/C++ compilers do to support the same.

I agree. The perf advantage of user code using these instructions explicitly vs. runtime using them internally where appropriate should very small.

Also, selecting the best way to do memory copy and similar operations is very complicated on x86 architectures. It only got more complicated with time. I would be surprised if Intel and AMD are done with changing the recommended implementations of these operations. It is another reason for keeping it centralized as an internal runtime detail.

**Comment by tannergooding** [comment]
Closing this given the above.

Please feel free to open a new issue tracking some implicit lightup in the JIT based on what the hardware supports.
