### ISSUE TITLE
[Native AOT shared library] Request: Statement on support of system linkers

### ISSUE THREAD

**Issue by ceztko** [dotnet/runtime#98627]
Up to .NET 8, the [`Microsoft.DotNet.ILCompiler`](https://github.com/dotnet/runtime/tree/main/src/coreclr/nativeaot/BuildIntegration) is currently using, directly or indirectly, system linkers (`link.exe`, `ld`, `ld64` in the major platforms) to perform the final linking step of generating an AOT shared library. I have some C++ NAPI, JNI interop trampolines methods that I wanted to plug in the process (generated automatically with a solution I talked about [here](https://github.com/dotnet/runtime/discussions/90445)). Instead of manually linking a NAOT static library, which is a process that it's currently cumbersome (apparently in the course of being [improved](https://github.com/dotnet/runtime/issues/70277)), I had the idea of plugging the static library with the symbols I wanted to export inside the msbuild process, something that required the library to be compiled correctly and the list of additional symbols to export, at least in linux/Mac platforms. While this is working perfectly (see the full example below), and I'm confident I will be able to use this strategy at least for all the .NET 8.0 support lifecycle, I'm concerned that it may become unsupported in the future as you may choose to abandon using system linkers in favor of handling the entire process with .NET tools (something that would also make cross-compilation very easy, I guess). My questions here are:
1. What are your plans for the continuing use of system linkers? Do you already know if/when you'll stop using them?
2. With or without system linkers, would you consider in the future adding support for plugging static libraries with symbols to export within the msbuild driven Native AOT generation? Or for this use case you will just recommend/support Native AOT static library generation and manual linking?

For interested people only, and just for reference, here is the full example of the process. In the NAOT enabled `.csproj` I have this `ItemGroup`:

```XML
 <ItemGroup Condition="'$(MyGlueCodeTargetDir)' != ''">
    <CustomLinkerArg Include="$([System.IO.Path]::Combine('$(MyGlueCodeTargetDir)', 'MyGlueCode.lib'))" Condition="'$(_targetOS)' == 'win'" />
    <CustomLinkerArg Include="$([System.IO.Path]::Combine('$(MyGlueCodeTargetDir)', 'libMyGlueCode.a'))" Condition="'$(_targetOS)' != 'win'" />
    <CustomLinkerArg Include="/INCLUDE:MyExports" Condition="'$(_targetOS)' == 'win'" />
    <CustomLinkerArg Include="-lstdc++ -Wl,--require-defined,MyExports &quot;-Wl,--version-script=$([System.IO.Path]::Combine('$(MyGlueCodeTargetDir)', 'symbols.ld.exports'))&quot;" Condition="'$(_targetOS)' == 'linux'" />
    <CustomLinkerArg Include="-lc++ -Wl,-u,_MyExports -exported_symbols_list &quot;$([System.IO.Path]::Combine('$(MyGlueCodeTargetDir)', 'symbols.ld64.exports'))&quot;" Condition="'$(_targetOS)' == 'osx'" />
  </ItemGroup>
```

For GNU `ld`, `symbols.ld.exports` is a [version script](https://www.gnu.org/software/gnulib/manual/html_node/LD-Version-Scripts.html) that gets a little bit abused not to specify different versions of symbols but just to plug another section without conflicting the other ones (multiple scripts can be specified with `--version-script`):
```
MYSECTION {
    global: _init; _fini;
        napi_register_module_v1;
        # ...
    local: *;
};
```

For Apple platforms `ld64`, `symbols.ld64.exports` is just a newline separated of symbols to exports. You can specify multiple lists in the linker with [`-exported_symbols_list`](https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/DynamicLibraryDesignGuidelines.html#//apple_ref/doc/uid/TP40002013-SW5):

```
_napi_register_module_v1
# ...
```

`MyExports` is a single symbol that references all the other required symbols, defined in C++ like the example below. I found this necessary in some platforms: MSVC linker, because you can't have multiple [`/DEF`](https://learn.microsoft.com/en-us/cpp/build/reference/def-specify-module-definition-file) switches and GNU `ld` (if I remember correctly) otherwise the symbols got elided anyway:

```C++
extern "C"
{
    void* MyExports[] = {
        (void*)napi_register_module_v1
        // ...
    };
}
```

As a final consideration, symbols to be exported could be theoretically inferred from the static library itself also in non-MSVC platforms (if manual [visibility](https://gcc.gnu.org/wiki/Visibility) is correctly set-up), but there's no high available tool that can't enlist these symbols in both linux and Apple.

**Comment by am11** [comment]
> What are your plans for the continuing use of system linkers? Do you already know if/when you'll stop using them?

@filipnavara mentioned that the new ObjWriter (written in C#) in .NET 9 can be extended to support full linking process. I'm not aware of the concrete plans. Even if it pans out, we may end up keeping the system linker option (as well as implement support for users symbol in managed implementation).

> For GNU ld, symbols.ld.exports is a [version script](https://www.gnu.org/software/gnulib/manual/html_node/LD-Version-Scripts.html) that gets a little bit abused not to specify different versions of symbols

Just an FYI, we are using version script (`--version-script`) and linker script (`-T`) options in AOT publishing process for different reasons:
https://github.com/dotnet/runtime/blob/d7acf9cd0bb995b0ba074a0808d383069bcdba18/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets#L342
https://github.com/dotnet/runtime/blob/d7acf9cd0bb995b0ba074a0808d383069bcdba18/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets#L349
https://github.com/dotnet/runtime/blob/d7acf9cd0bb995b0ba074a0808d383069bcdba18/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets#L367
(these options are supported by GNU and LLVM linkers but note that they are not 100% drop-in replacement of each other https://maskray.me/blog/2020-12-19-lld-and-gnu-linker-incompatibilities and the fact that we had to specify `OVERWRITE_SECTIONS` piece for lld v13+)

As you figured out, user can provide their own version and linker scripts and all these scripts eventually get concatenated by system linker in order. `version script` can be embedded inside the `linker script`, but we didn't  had a reason to unify them. User can choose to embed their version script into the linker script.

**Comment by filipnavara** [comment]
> 1. Do you already know if/when you'll stop using them?

There’s no plan to stop using them at the moment. Linkers are complex and replacing them would be a huge task.

**Comment by jkotas** [comment]
We have no plans to abandon system linkers.

**Comment by ceztko** [comment]
> We have no plans to abandon system linkers.

Thank you for your prompt answer! I will do some more research and consider doing a proposal for supporting plugging static libraries with symbols to be exported, which may be a more convenient way to extend Native AOT generation than manually linking a NAOT generated static library.

**Comment by jkotas** [comment]
> symbols to be exported

#95816 introduced ability to export additional symbols: ``<IlcArg Include="--export-dynamic-symbol:MyAdditionalSymbolToExport" />`. It may be what you are looking for.

Note that this is internal undocumented option currently. We reserve the right to change it without breaking change notice.
