### ISSUE TITLE
[mono] set alc collectible

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#98649]
I found this pr https://github.com/dotnet/runtime/pull/77399 set mono collectiable always be false https://github.com/dotnet/runtime/blob/0f6df43ff9bfb98f0fcac781125ce9b4e5b5ba66/src/mono/mono/metadata/assembly-load-context.c#L43

these lead the memory manager always use default
https://github.com/dotnet/runtime/blob/0f6df43ff9bfb98f0fcac781125ce9b4e5b5ba66/src/mono/mono/metadata/memory-manager.c#L476-L497

@vargaz

**Comment by filipnavara** [comment]
There's a tracking issue - https://github.com/dotnet/runtime/issues/79711 - to enable the unloadable ALCs on Mono.

**Comment by srxqds** [comment]
yeah, but we want collectible = true  work, I have remove this line : [runtime/src/mono/mono/metadata/assembly-load-context.c](https://github.com/dotnet/runtime/blob/0f6df43ff9bfb98f0fcac781125ce9b4e5b5ba66/src/mono/mono/metadata/assembly-load-context.c#L43)

will crash ,there are so many `fixme` leave.

**Comment by agocke** [comment]
Closing as dup of https://github.com/dotnet/runtime/issues/79711
