### ISSUE TITLE
SPMI: Unknown reloc type 260 when replaying with -applyDiff

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#98666]
When I run win-x64 replay with -applyDiff arg I see a bunch of these messages:
```scala
ERROR: Unknown reloc type 260
```

cc @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
This is probably `IMAGE_REL_SECREL` from the NativeAOT TLS work. that and the other new TLS added relocations:

```
#define IMAGE_REL_SECREL                0x104

// Linux x64
// GD model
#define IMAGE_REL_TLSGD                 0x105

// Linux arm64
//    TLSDESC  (dynamic)
#define IMAGE_REL_AARCH64_TLSDESC_ADR_PAGE21   0x107
#define IMAGE_REL_AARCH64_TLSDESC_LD64_LO12    0x108
#define IMAGE_REL_AARCH64_TLSDESC_ADD_LO12     0x109
#define IMAGE_REL_AARCH64_TLSDESC_CALL         0x10A
```

 need handling in `CompileResult::applyRelocs()` in src\coreclr\tools\superpmi\superpmi-shared\compileresult.cpp.
