### ISSUE TITLE
Set DotNetReleaseShipping metadata for assets in Manifest.xml

### ISSUE THREAD

**Issue by MilenaHristova** [dotnet/runtime#98662]
Add a boolean property named `ProducesNetCoreAssets` in `Publishing.props` for repos that produce .NET shipping packages (packages that we ship with the release infra)
Based on this property we will select which packages to ship as part of .NET on release day.

Add the metadata to assets in `prepare-artifacts.proj` since runtime doesn't use arcades default publishing

**This is a infrastructure only change.** It will add extra metadata to the `MergedManifest.xml` produced during CI build.

Details are in [Set ProducesNetCoreAssets property for repos that produce .NET packages issue](https://github.com/dotnet/release/issues/822)

**Comment by ViktorHofer** [comment]
That property name is misleading. `NetCore` refers to .NET builds for the `.NETCoreApp` TargetFrameworkIdentifier (meaning the modern version of .NET and not .NET Framework or .NET Standard).

What about something like `ProducesNetReleaseDayShippingArtifacts` or `ProducesShippingArtifacts`?

cc @mmitche

**Comment by mmitche** [comment]
`ProducesShippingArtifacts` is too generic for sure. Maybe `ProducesDotNetReleaseArtifacts`?

**Comment by MilenaHristova** [comment]
Finally it's `ProducesNetReleaseShippingAssets`
The reasoning is we have 3 categories of assets: non-shipping, release-shipping (shipped as part of .NET release) and self-shipping (shipped separately from .NET release)

**Comment by MilenaHristova** [comment]
PRs: https://github.com/dotnet/runtime/pull/98665 and https://github.com/dotnet/runtime/pull/98824
