### ISSUE TITLE
.NET 8: Non-Breaking Space Being Added in DateTime & TimeOnly ToString Calls on Linux

### ISSUE THREAD

**Issue by deruitda** [dotnet/runtime#98664]
### Description

I have a fairly simple test that works fine on Windows and MacOS, it also used to work fine on Alpine Linux containers no problem. Everything was working until I migrated to .NET 8. I am seeing tests fail due to a non-breaking space being added before the "AM" or "PM" in a DateTime or TimeOnly. Here is a simple test that can reproduce the issue:

```
        [TestMethod]
        public void Dates2()
        {
            TimeOnly time = new TimeOnly(1, 1, 1);
            var timeStr = time.ToString();
            timeStr.Should().Be("1:01 AM"); // FAILS
            
            
            DateTime dt = new DateTime(1, 1, 1, 1, 1, 1);
            var dateTimeStr = dt.ToString(CultureInfo.CurrentCulture);
            dateTimeStr.Should().Be("1/1/0001 1:01:01 AM"); // FAILS
        }
```

The test fails because:
> Expected string to be "1:01 AM", but "1:01 AM" differs near " AM" (index 4).

I dumped the strings that are generated by the ToString calls on the TimeOnly and DateTime structs, I can see a strange unicode character before "AM" that appears to be a non-breaking space character. 

> Expected string to be "1:01 AM", but "1:01�M-^@�AM" differs near "�M-^@�AM" (index 4).

I do not see this non-breaking space being added on any OS other than linux. Any idea why this is happening? This is not just one application having this issue, it extends to dozens of other apps that I'm maintaining. 

I did find a similar issue that looks to have been solved in .NET 8, however the issue I'm having does seem slightly different: https://github.com/dotnet/runtime/issues/90627

### Reproduction Steps

1. Use this dockerfile: 

```
# Use the official .NET 8 SDK Alpine image as the base image
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# Set the working directory to /app
WORKDIR /app

# Copy the project file and restore dependencies
COPY . ./
RUN dotnet restore

# Build the application
RUN dotnet build -c Release

# Run tests
RUN dotnet test --logger:"trx;LogFileName=testresults.trx" -c Release

# Create a runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS runtime

WORKDIR /app

# Copy the built artifacts from the build image
COPY --from=build /app/bin/Release/netcoreapp3.1/ .

# Set the entry point for the application
ENTRYPOINT ["dotnet", "YourProjectName.dll"]
```

2. Create a basic .NET 8 application with a test project. Create a test similar to the one above that calls ToString on a TimeOnly or DateTime that is using a culture such as en-US that includes "AM" or "PM" in the string representation.
3. Build the dockerfile and observe the failed results

### Expected behavior

A normal space should separate the time and the "AM" "PM" indicator.

### Actual behavior

A NBSP is added between the time and the AM / PM indicator.

**Comment by deruitda** [comment]
I dug a bit more into this, and tried the same test dockerfile out on the same code but switched everything over to .NET 6. I am seeing the same test error on the .NET 6 container, so there must be something I'm missing in this dockerfile to have the functionality mimic what we see on MacOS / Windows.

**Comment by Clockwork-Muse** [comment]
The problem is that a newer container nabbed you a new version of libicu, which contains new behavior (the non-breaking space in the format string).

The dotnet runtime does not control this data, it's not something we distribute (it's part of the host OS/packages).  

> Expected behavior
>
> A normal space should separate the time and the "AM" "PM" indicator.

Your expectation is wrong - formatting data isn't stable, and can unexpectedly change at any time for any platform (as you're experiencing here).

>  so there must be something I'm missing in this dockerfile to have the functionality mimic what we see on MacOS / Windows.

You're not guaranteed that any two machines running two identical versions of the same OS will generate the same formatted data, because among other things (especially on Windows), the end user can customize their format strings (I set all my stuff to ISO/24 hour time, for example).

> I have a fairly simple test that works fine on Windows and MacOS 

You're testing against host-dependent data; this is brittle and can break at any time (and in fact will when Windows/MacOS also pick up the updated ICU libraries).  

Don't do that.

When testing localization, either only test for a non-empty string, or construct and use your own (stable) pseudo locale.

If this is for interchange purposes, use the `InvariantCulture` and explicit format strings.

**Comment by deruitda** [comment]
Thanks for the reply and the info regarding a new libicu version, I see the new version and the change that is causing this issue.

You're correct regarding the tests not being ideal, unfortunately we have many services and teams so sometimes bad tests will sneak through. I should have phrased this more as a question, _why is this happening now_ rather than _this is not working as intended_. I was looking for a solution to see if we can still run our .NET 8 containers without having to change a bunch of services. Now that I know libicu is the culprit I have an idea of what we can do to solve this. Thanks!

**Comment by Clockwork-Muse** [comment]
> Now that I know libicu is the culprit I have an idea of what we can do to solve this.

The way you've phrased this makes me concerned.  If you're thinking of changing the bundled ICU version, please don't.

> I was looking for a solution to see if we can still run our .NET 8 containers without having to change a bunch of services.

You're going to need to do this.  At minimum you'll need to fix your tests (and set your automated test runners to run in the UTC zone, plus probably a few others).  Then you'll have to evaluate whether your code actually needs to perform customer-visible localization or not - it's unusual for a server-side service to need to perform customer-facing localization (normally limited to some form of "compiled page" data, like for marketing emails).  If it's for any form of interchange, you shouldn't be using localized values at all, but one of the round-trip formats.

If you're not using it already, [`DateTimeStyles.AllowWhiteSpaces`](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.datetimestyles?view=net-8.0) can help you bridge the gap on parse, removing the whitespace differences.

**Comment by deruitda** [comment]
Yeah I'm not modifying the libicu version in the containers, I have a plan for teams to update their failing tests.
