### ISSUE TITLE
Why does this code always print `0.000000`?

### ISSUE THREAD

**Issue by iahung2** [dotnet/runtime#98693]
### Discussed in https://github.com/dotnet/runtime/discussions/98650

<div type='discussions-op-text'>

<sup>Originally posted by **iahung2** February 19, 2024</sup>
LibC.cs

```
using System;
using System.Runtime.InteropServices;

unsafe class LibC {
	#if WINDOWS
		const string libc = "msvcrt";
	#else
		const string libc = "libc";
	#endif
	
	[DllImport(libc, CallingConvention = CallingConvention.Cdecl), SuppressGCTransition]
	public static extern int printf(byte* format, double x);
	
	public static int print(double x) {
		unsafe {
			var format = "%f\n"u8;
			fixed (byte* fmt = &format[0])
			{
				return printf(fmt, x);
			}
		}
	}
}

```

test.cs

```
using System;
using static LibC;

namespace ConsoleApp1
{
	class Program
	{
		static void Main(string[] args) {
			print(0.12345);
		}
	}
}

```
</div>

Update: `printf` with an integer works, so it seems it's only problematic with floating point numbers.

**Comment by danmoseley** [comment]
@AaronRobinsonMSFT

**Comment by jkotas** [comment]
This was answered in the discussion by @huoyaoyuan and @MichalPetryka in the discussion: https://github.com/dotnet/runtime/discussions/98650#discussioncomment-8520524

The varargs is support is tracked by https://github.com/dotnet/runtime/issues/82081 and related issues. Resolving as duplicate.
