### ISSUE TITLE
HTTP version selection

### ISSUE THREAD

**Issue by scalablecory** [dotnet/runtime#987]
This API will update HttpClient behavior to enable more useful version selection from users. This will make possible [prenegotiated HTTP/2 cleartext](https://github.com/dotnet/corefx/issues/41621), H2C upgrade, prenegotiated HTTP/3, and leave the door open for Alt-Svc to migrate connections in the future.

If accepted, would supersede #988 and allow us to get rid of the current AppContext switch for prenegotiated H2C.

## Proposed API

```c#
class HttpClient
{
    //Version DefaultVersion { get; set; } // Exists today - will be interpreted as Min or Max based on new API below.
    public HttpVersionPolicy DefaultVersionPolicy { get; set; } = HttpVersionPolicy.RequestVersionOrLower;
}

class HttpRequestMessage
{
    //Version Version { get; set; } // Exists today - will be interpreted as Min or Max based on new API below.
    public HttpVersionPolicy VersionPolicy { get; set; } = HttpVersionPolicy.RequestVersionOrLower;
}

public enum HttpVersionPolicy
{
    RequestVersionOrLower,
    RequestVersionOrHigher,
    RequestVersionExact
}
```

## Behavior

The default would have identical behavior to what we have today.

- `RequestVersionOrLower`: start as high as possible (HTTP/1.1, or ALPN if available) up to `HttpRequestMessage.Version`.
- `RequestVersionOrHigher`: start as high as possible (at least `HttpRequestMessage.Version`, or ALPN if available), and upgrade (via H2C upgrade or Alt-Svc) if possible. Enables prenegotiated H2C.
- `RequestVersionExact`: use explicitly the version the user asked for, and if server requires an upgrade/downgrade for a specific request, return an appropriate error. Enables prenegotiated H2C.

## Example: User doesn't know, but use whatever server has available.

```c#
var msg = new HttpRequestMessage { VersionPolicy = HttpVersionPolicy.RequestVersionOrHigher };
// ...
```

## Example: Prenegotiated HTTP/3

```c#
var msg = new HttpRequestMessage { Version = HttpVersion.Version30, VersionPolicy = VersionPolicy = HttpVersionPolicy.RequestVersionOrHigher };
// ...
```

## Example: H2C upgrade

```c#
var msg = new HttpRequestMessage { VersionPolicy = HttpVersionPolicy.RequestVersionOrHigher };
```

## Example: [Prenegotiated H2C](https://github.com/dotnet/corefx/issues/41621)

```c#
var msg = new HttpRequestMessage
{
    Version = HttpVersion.Version20,
    VersionPolicy = HttpVersionPolicy.RequestVersionOrHigher
    RequestUri = new Uri("http://unsecure-url.com")
};
```

## Example: app depends on Connection: close
```c#
var msg = new HttpRequestMessage { }; // default policy just fine.
msg.Headers.ConnectionClose = true;
```

**Comment by JamesNK** [comment]
1. What would happen if you've configured prenegotiated H2C, but you're using TLS?

2. What would happen here?

```cs
var handler = new SocketsHttpHandler
{
   AllowVersionDowngrade = false,
   AllowVersionUpgrade = true
};
var msg = new HttpRequestMessage { Version = HttpVersion.Version20 };
// ...
```

3. Is HTTP/3 without TLS ever a thing?

**Comment by Tratcher** [comment]
Seems workable. A few questions and corner cases:
- What about per-request overrides for this behavior? If I needed to use multiple protocols then keeping track of multiple handlers and clients would be inconvenient. Consider that request scheme is per-request and causes significantly different behavior depending on the protocol version.
- You said this allows for H2C upgrade, but don't give an example? Would that be an HTTP/1 request without TLS and opting into upgrades?
- Is there any way to express a preference for HTTP/3 with a fallback to HTTP/2? E.g. incomplete prior knowledge, you know the server supports it but you don't know if you have end-to-end connectivity. Would setting the version to HTTP/3 and allowing downgrades work?
- What about ranges? E.g. if I wanted HTTP/1 or HTTP/2 but not HTTP/3 I'd have to set my request version to HTTP/2 and allow downgrades but not upgrades? Or if I wanted HTTP/2 or HTTP/3 but not HTTP/1 I'd have to set my request version to HTTP/2 and allow upgrades but not downgrades?
- How well is this future proofed against an eventual HTTP/4? It looks like opting into upgrades now for HTTP/3 also opts you into all future upgrades for things like HTTP/4.

@JamesNK 

> 1. What would happen if you've configured prenegotiated H2C, but you're using TLS?

HTTP/2 with TLS mandates using ALPN. In this case you'd use ALPN and only specify H2, not HTTP/1.1. If the server didn't allow ALPN or HTTP/2 you'd get a connection error.

> 2\. What would happen here without TLS? What would happen here with TLS?

You'd get H2C. There's no H3 upgrade from H2C (except maybe alt-svc?).

> Is HTTP/3 without TLS ever a thing?

No.

**Comment by scalablecory** [comment]
>     * You said this allows for H2C upgrade, but don't give an example? Would that be an HTTP/1 request without TLS and opting into upgrades?

Yes, I've added an example.

**Comment by scalablecory** [comment]
> What about per-request overrides for this behavior? If I needed to use multiple protocols then keeping track of multiple handlers and clients would be inconvenient. Consider that request scheme is per-request and causes significantly different behavior depending on the protocol version.

This seems useful to consider. Perhaps these properties should be on the `HttpRequestMessage`.

**Comment by scalablecory** [comment]
> There's no H3 upgrade from H2C (except maybe alt-svc?).

Alt-Svc can do it, but we probably won't allow it ... automatic insecure->secure transition is a bit iffy.

**Comment by scalablecory** [comment]
>     * It looks like opting into upgrades now for HTTP/3 also opts you into all future upgrades for things like HTTP/4.

Yes, and this is intentional.

**Comment by scalablecory** [comment]
> Is there any way to express a preference for HTTP/3 with a fallback to HTTP/2? E.g. incomplete prior knowledge, you know the server supports it but you don't know if you have end-to-end connectivity. Would setting the version to HTTP/3 and allowing downgrades work?

You would accomplish this by setting `AllowVersionDowngrade = false` and `AllowVersionUpgrade = true`, and `Version = HttpVersion.Version20`.

**Comment by Tratcher** [comment]
> > Is there any way to express a preference for HTTP/3 with a fallback to HTTP/2? E.g. incomplete prior knowledge, you know the server supports it but you don't know if you have end-to-end connectivity. Would setting the version to HTTP/3 and allowing downgrades work?
> 
> You would accomplish this by setting `AllowVersionDowngrade = false` and `AllowVersionUpgrade = true`, and `Version = HttpVersion.Version20`.

That's not a preference for HTTP/3, that's a preference for HTTP/2.

**Comment by Tratcher** [comment]
> > Is there any way to express a preference for HTTP/3 with a fallback to HTTP/2? E.g. incomplete prior knowledge, you know the server supports it but you don't know if you have end-to-end connectivity. Would setting the version to HTTP/3 and allowing downgrades work?
> 
> You would accomplish this by setting `AllowVersionDowngrade = false` and `AllowVersionUpgrade = true`, and `Version = HttpVersion.Version20`, and letting it upgrade. You wouldn't be able to try prenegotiated first and then fallback -- this seems of limited utility, though a user could probably implement this themselves by retrying the request if they really needed it.

It seems like I should be able to with this configuration:
```
var handler = new SocketsHttpHandler
{
   AllowVersionDowngrade = true,
   AllowVersionUpgrade = false
};
var msg = new HttpRequestMessage { Version = HttpVersion.Version30 };
```

**Comment by scalablecory** [comment]
> It seems like I should be able to with this configuration:

Under the rules outlined in the issue, this would mean "starting from HTTP/1, upgrade up to HTTP/3 if server advertises it".

**Comment by Tratcher** [comment]
Ok, I re-read the rules and think I understand. AllowVersionDowngrade is going to need a clearer name, it doesn't match the description. These rules might be alternately summarized as `UpgradeToSpecifiedVersion` `UpgradePastSpecifiedVersion`.

When both options are true does HttpRequestMessage.Version matter at all?

I'm starting to think this should be an enum rather than a set of bools. That would allow for new policies in the future as well.
- RequestVersionOrLower - current behavior, opportunistic upgrade to a max version
- RequestVersionOrHigher - Future proof
- OnlyRequestVersion - exact, H2C, direct H3
- AnyVersion - APLN, then ALT-SVC

HttpRequestMessage could have this as a nullable option to override the transport. HttpClient could also have it as a nullable option to mirror DefaultRequestVersion. Hmm, if you had it on HttpClient & HttpRequestMessage, would you need it on SocketsHttpHandler? Or would that handler just have a hard coded default if nothing was specified up stack?

**Comment by scalablecory** [comment]
> I'm starting to think this should be an enum rather than a set of bools. It would allow for more precise names, and would allow for new policies in the future.

Yes, that seems more clear.

> HttpClient could also have it as a nullable option to mirror DefaultRequestVersion.

We currently have a weird behavior in that `HttpClient.DefaultRequestVersion` actually doesn't do anything if you set it to HTTP/2. I would love to revisit that choice, but if we stick with it, we might follow suit and not put this upgrade logic on `HttpClient either.

> Hmm, if you had it on HttpClient & HttpRequestMessage, would you need it on SocketsHttpHandler?

Nope. I put it on `SocketsHttpHandler` originally because other handlers would simply ignore such a property, but if we're putting it on the request message now, that becomes impossible to avoid.

**Comment by Tratcher** [comment]
> We currently have a weird behavior in that `HttpClient.DefaultRequestVersion` actually doesn't do anything if you set it to HTTP/2. I would love to revisit that choice, but if we stick with it, we might follow suit and not put this upgrade logic on `HttpClient either.

? I've used this, it works great. Or are you talking about the non-TLS scenarios?

**Comment by scalablecory** [comment]
> ? I've used this, it works great. Or are you talking about the non-TLS scenarios?

I should clarify: it only works for the convenience methods, not the base `SendAsync`. See https://github.com/dotnet/corefx/issues/41836

**Comment by Tratcher** [comment]
> I should clarify: it only works for the convenience methods, not the base `SendAsync`. See [dotnet/corefx#41836](https://github.com/dotnet/corefx/issues/41836)

Oh, I don't mind the current behavior, it's clear enough with the doc clarification.

**Comment by halter73** [comment]
Is there any scenario that this proposal supports that wouldn't also be supported by simply having a `MinVersion` and `MaxVersion`? I think having just a min and max version would be way easier to understand than the proposals I see so far.

One thing that might not be communicated with a min and max version is which order the client should try to the protocols in. But given that it seems even with "AllowVersionDowngrade" set to true, the client would counterintuitively still try HTTP/1 first, this doesn't seem to be too big of a concern. I'm not sure it even makes sense to allow the order to be configurable outside of the special case of trying a single protocol in which case the min and max would be the same.

Another issue with a min and max version is that the max version would probably have to be represented by `HttpRequestMessage.Version` since it already exists instead of adding a new property called `MaxVersion`. I don't think it's a big deal though, because once you have both `HttpRequestMessage.Version` and  `HttpRequestMessage.MinVersion`, I think it becomes pretty clear `HttpRequestMessage.Version` is the max, especially since it's already the max today.

**Comment by scalablecory** [comment]
> Is there any scenario that this proposal supports that wouldn't also be supported by simply having a `MinVersion` and `MaxVersion`? I think having just a min and max version would be way easier to understand than the proposals I see so far.

I'm not strongly against it, but I did intentionally avoid it here to see what ideas would come out. I expect `AllowVersionUpgrade=true` to be the fundamental thing people actually want. Anything more, like a min/max, is just extra to think about.

The `AllowVersionDowngrade=false` option is basically only there for gRPC and to simplify testing -- I think very few people will directly use it in a meaningful way.

**Comment by Tratcher** [comment]
I still think an enum would work better here than multiple bools, and it allows for supporting additional scenarios later.

**Comment by scalablecory** [comment]
This API will update HttpClient behavior to enable more useful version selection from users. This will make possible [prenegotiated HTTP/2 cleartext](https://github.com/dotnet/corefx/issues/41621), H2C upgrade, prenegotiated HTTP/3, and leave the door open for Alt-Svc to migrate connections in the future.

## Proposed API

```c#
class HttpClient
{
    public HttpVersionPolicy DefaultVersionPolicy { get; set; } = HttpVersionPolicy.RequestVersionOrLower;
}

class HttpRequestMessage
{
   public HttpVersionPolicy VersionPolicy { get; set; } = HttpVersionPolicy.RequestVersionOrLower;
}

public enum HttpVersionPolicy
{
    RequestVersionOrLower,
    RequestVersionOrHigher
}
```

## Behavior

The default would have identical behavior to what we have today.

- `RequestVersionOrLower`: start as high as possible (HTTP/1.1, or ALPN if available) up to `HttpRequestMessage.Version`.
- `RequestVersionOrHigher`: start as high as possible (at least `HttpRequestMessage.Version`, or ALPN if available), and upgrade (via H2C upgrade or Alt-Svc) if possible. Enables prenegotiated H2C.

## Example: User doesn't know, but use whatever server has available.

```c#
var msg = new HttpRequestMessage { VersionPolicy = HttpVersionPolicy.RequestVersionOrHigher };
// ...
```

## Example: Prenegotiated HTTP/3

```c#
var msg = new HttpRequestMessage { Version = HttpVersion.Version30, VersionPolicy = VersionPolicy = HttpVersionPolicy.RequestVersionOrHigher };
// ...
```

## Example: H2C upgrade

```c#
var msg = new HttpRequestMessage { VersionPolicy = HttpVersionPolicy.RequestVersionOrHigher };
```

## Example: [Prenegotiated H2C](https://github.com/dotnet/corefx/issues/41621)

```c#
var msg = new HttpRequestMessage
{
    Version = HttpVersion.Version20,
    VersionPolicy = VersionPolicy = HttpVersionPolicy.RequestVersionOrHigher
    RequestUri = new Uri("http://unsecure-url.com")
};
```

## Example: app depends on Connection: close
```c#
var msg = new HttpRequestMessage { }; // default policy just fine.
msg.Headers.ConnectionClose = true;
```

**Comment by Tratcher** [comment]
Much clearer, thanks.

> RequestVersionOrHigher: start as high as possible (at least HttpRequestMessage.Version, or ALPN if available), and upgrade (via H2C upgrade or Alt-Svc) if possible

Rephrased: Default to HttpRequestMessage.Version and upgrade if possible via ALPN, Alt-Svc, h2c Upgrade, etc..

> ```cs
> // Maybe useful for testing, but not much real-world utility. Feel like leaving off is reasonable.
>     // Exact
> ```

Scenarios for Exact:
- Only allow HTTP2, not Http/1.x or Http/3. gRPC might need this @JamesNK?
- H2C - It's not clear why you'd want OrHigher for H2C, the only upgrade mechanism would be Alt-Svc? And how would you opt out of that upgrade?

**Comment by Tratcher** [comment]
> ```cs
> Maybe useful for testing, 
> ```

Indeed, never underestimate the need for precision in testing.

**Comment by JamesNK** [comment]
> Only allow HTTP2, not Http/1.x or Http/3. gRPC might need this @JamesNK?

gRPC needed prenegotated H2C for the non-TLS scenario. There is no gRPC need to ever require HTTP/1.1.

As for HTTP/3, can you have HTTP/3 without TLS? There is no reason why gRPC would want to require HTTP/3 today, but who knows what the future holds 🤷‍♂

**Comment by Tratcher** [comment]
@JamesNK to clarify, will gRPC need to restrict requests to HTTP/2, or is HTTP/2-Or-Later (H3) ok?

**Comment by JamesNK** [comment]
There isn't much information at the moment: https://github.com/grpc/grpc/issues/19126

Unless HTTP/3 drops features in HTTP/2 then gRPC should be forward compatible.

**Comment by scalablecory** [comment]
> * H2C - It's not clear why you'd want OrHigher for H2C, the only upgrade mechanism would be Alt-Svc? And how would you opt out of that upgrade?

Upgrading from http to https via Alt-Svc is certainly possible but leaves some important questions to iron out to ensure good security. My initial PR simply disallows it.

I think we need to decide how we want to handle prenegotiated H2C. Some options are:
- Just enable it, but users using http:// URIs with Version20 will see sudden failure against servers that don't have 2.0.
- Use `RequestVersionOrHigher` as an implicit "I know what I'm doing" to enable it (this is what I've chosen to do here, but I'm absolutely not strong on that opinion).
- Introduce the `Exact` policy and only enable it if users ask for it specifically. It's mostly (hopefully) only going to be used in very controlled environments where you own both the client and the server, so this would probably be fine if a bit inflexible.
- Introduce some extra API for opt-in e.g. https://github.com/dotnet/runtime/issues/988, but I am not super keen on that. The fewer switches we have the better.

**Comment by scalablecory** [comment]
> * Only allow HTTP2, not Http/1.x or Http/3. gRPC might need this @JamesNK 

Alt-Svc should only ever be advertised if the alternate can handle ALL requests. Under this rule, gRPC library shouldn't need to explicitly use HTTP/2 exactly -- if the server advertises it, upgrades are fine.

**Comment by karelz** [comment]
Triage: Networking team agreed to take `RequestVersionExact` - see updates above.
@scalablecory please update top post with our latest proposal and let's bring it to full API review.

**Comment by terrajobst** [comment]
* Looks good as proposed
    - We may want to change `HttpVersionPolicy.RequestXxx` to `HttpVersionPolicy.RequestedXxx`

```C#
namespace System.Net.Http
{
    public partial class HttpClient
    {
        // Exists today - will be interpreted as Min or Max based on new API below.
        // Version DefaultVersion { get; set; }
        public HttpVersionPolicy DefaultVersionPolicy { get; set; } = HttpVersionPolicy.RequestVersionOrLower;
    }

    public partial class HttpRequestMessage
    {
        // Exists today - will be interpreted as Min or Max based on new API below.
        // Version Version { get; set; }
        public HttpVersionPolicy VersionPolicy { get; set; } = HttpVersionPolicy.RequestVersionOrLower;
    }

    public enum HttpVersionPolicy
    {
        RequestVersionOrLower,
        RequestVersionOrHigher,
        RequestVersionExact
    }
}
```
