### ISSUE TITLE
Error: Assert failed: Expected Promise for GCHandle

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#98721]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=571836
Build error leg or test failing: WasmTestOnBrowser-System.Net.WebSockets.Client.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime.git/pull/98657

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Error: Assert failed: Expected Promise for GCHandle",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=571836
**Error message validated:** `[Error: Assert failed: Expected Promise for GCHandle`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 2/20/2024 9:46:33 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[595316](https://dev.azure.com/dnceng-public/public/_build/results?buildId=595316)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=595316&view=ms.vss-test-web.build-test-results-tab&runId=14403214&resultId=100164)|dotnet/runtime#98986|
|[595290](https://dev.azure.com/dnceng-public/public/_build/results?buildId=595290)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=595290&view=ms.vss-test-web.build-test-results-tab&runId=14402798&resultId=100164)|dotnet/runtime#99380|
|[595206](https://dev.azure.com/dnceng-public/public/_build/results?buildId=595206)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=595206&view=ms.vss-test-web.build-test-results-tab&runId=14401066&resultId=100164)|dotnet/runtime#99422|
|[595169](https://dev.azure.com/dnceng-public/public/_build/results?buildId=595169)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=595169&view=ms.vss-test-web.build-test-results-tab&runId=14399870&resultId=100166)|dotnet/runtime#98559|
|[594953](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594953)|dotnet/runtime|[WasmTestOnBrowser-System.Net.WebSockets.Client.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594953&view=ms.vss-test-web.build-test-results-tab&runId=14401684&resultId=187927)|dotnet/runtime#98492|
|[595061](https://dev.azure.com/dnceng-public/public/_build/results?buildId=595061)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=595061&view=ms.vss-test-web.build-test-results-tab&runId=14396184&resultId=100164)|dotnet/runtime#99351|
|[595123](https://dev.azure.com/dnceng-public/public/_build/results?buildId=595123)|dotnet/runtime|[WasmTestOnBrowser-System.Private.Xml.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=595123&view=ms.vss-test-web.build-test-results-tab&runId=14399322&resultId=182444)|dotnet/runtime#98802|
|[594959](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594959)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594959&view=ms.vss-test-web.build-test-results-tab&runId=14393372&resultId=100164)|dotnet/runtime#99446|
|[594917](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594917)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594917&view=ms.vss-test-web.build-test-results-tab&runId=14391086&resultId=100164)|dotnet/runtime#99351|
|[594856](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594856)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594856&view=ms.vss-test-web.build-test-results-tab&runId=14389476&resultId=100164)|dotnet/runtime#99392|
|[594832](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594832)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594832&view=ms.vss-test-web.build-test-results-tab&runId=14388652&resultId=100164)||
|[594911](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594911)|dotnet/runtime|[WasmTestOnBrowser-System.Net.WebSockets.Client.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594911&view=ms.vss-test-web.build-test-results-tab&runId=14389882&resultId=100441)|dotnet/runtime#99275|
|[594763](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594763)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594763&view=ms.vss-test-web.build-test-results-tab&runId=14386252&resultId=100164)|dotnet/runtime#99397|
|[594775](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594775)|dotnet/runtime|[WasmTestOnBrowser-System.Private.Xml.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594775&view=ms.vss-test-web.build-test-results-tab&runId=14386460&resultId=181901)|dotnet/runtime#98802|
|[593590](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593590)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593590&view=ms.vss-test-web.build-test-results-tab&runId=14384182&resultId=100001)|dotnet/runtime#99403|
|[594273](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594273)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594273&view=ms.vss-test-web.build-test-results-tab&runId=14364658&resultId=100164)|dotnet/runtime#99267|
|[594166](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594166)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594166&view=ms.vss-test-web.build-test-results-tab&runId=14362666&resultId=100164)|dotnet/runtime#99081|
|[593674](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593674)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593674&view=ms.vss-test-web.build-test-results-tab&runId=14355594&resultId=100163)|dotnet/runtime#99351|
|[591905](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591905)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591905&view=ms.vss-test-web.build-test-results-tab&runId=14354860&resultId=100164)|dotnet/runtime#99340|
|[593606](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593606)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593606&view=ms.vss-test-web.build-test-results-tab&runId=14353264&resultId=100164)|dotnet/runtime#99392|
|[593575](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593575)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593575&view=ms.vss-test-web.build-test-results-tab&runId=14351812&resultId=100164)|dotnet/runtime#98986|
|[593498](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593498)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593498&view=ms.vss-test-web.build-test-results-tab&runId=14350626&resultId=100164)|dotnet/runtime#96332|
|[593511](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593511)|dotnet/runtime|[WasmTestOnBrowser-System.Private.Xml.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593511&view=ms.vss-test-web.build-test-results-tab&runId=14350454&resultId=181741)|dotnet/runtime#98802|
|[593365](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593365)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593365&view=ms.vss-test-web.build-test-results-tab&runId=14348344&resultId=100164)|dotnet/runtime#98559|
|[593229](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593229)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593229&view=ms.vss-test-web.build-test-results-tab&runId=14343096&resultId=100001)|dotnet/runtime#99403|
|[593250](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593250)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593250&view=ms.vss-test-web.build-test-results-tab&runId=14343086&resultId=100164)|dotnet/runtime#99188|
|[591783](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591783)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591783&view=ms.vss-test-web.build-test-results-tab&runId=14326364&resultId=100164)|dotnet/runtime#99347|
|[592800](https://dev.azure.com/dnceng-public/public/_build/results?buildId=592800)|dotnet/runtime|[WasmTestOnBrowser-System.Private.Xml.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=592800&view=ms.vss-test-web.build-test-results-tab&runId=14328246&resultId=181896)|dotnet/runtime#98802|
|[592048](https://dev.azure.com/dnceng-public/public/_build/results?buildId=592048)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=592048&view=ms.vss-test-web.build-test-results-tab&runId=14301554&resultId=100164)||
|[591885](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591885)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591885&view=ms.vss-test-web.build-test-results-tab&runId=14300168&resultId=100164)|dotnet/runtime#99343|
|[591609](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591609)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591609&view=ms.vss-test-web.build-test-results-tab&runId=14292718&resultId=100164)|dotnet/runtime#98981|
|[591685](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591685)|dotnet/runtime|[WasmTestOnBrowser-System.Private.Xml.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591685&view=ms.vss-test-web.build-test-results-tab&runId=14294034&resultId=181732)|dotnet/runtime#98802|
|[591452](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591452)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591452&view=ms.vss-test-web.build-test-results-tab&runId=14288726&resultId=100164)|dotnet/runtime#99355|
|[591326](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591326)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591326&view=ms.vss-test-web.build-test-results-tab&runId=14285026&resultId=100164)|dotnet/runtime#99188|
|[591360](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591360)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591360&view=ms.vss-test-web.build-test-results-tab&runId=14285268&resultId=100166)|dotnet/runtime#99350|
|[591287](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591287)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591287&view=ms.vss-test-web.build-test-results-tab&runId=14282156&resultId=100164)|dotnet/runtime#99273|
|[591279](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591279)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591279&view=ms.vss-test-web.build-test-results-tab&runId=14280954&resultId=100166)|dotnet/runtime#98495|
|[590978](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590978)|dotnet/runtime|[WasmTestOnBrowser-System.Private.Xml.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590978&view=ms.vss-test-web.build-test-results-tab&runId=14270720&resultId=181770)|dotnet/runtime#98802|
|[590802](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590802)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590802&view=ms.vss-test-web.build-test-results-tab&runId=14262902&resultId=100166)|dotnet/runtime#99277|
|[590663](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590663)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590663&view=ms.vss-test-web.build-test-results-tab&runId=14259026&resultId=100166)|dotnet/runtime#99185|
|[590220](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590220)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590220&view=ms.vss-test-web.build-test-results-tab&runId=14244378&resultId=100166)|dotnet/runtime#99296|
|[590245](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590245)|dotnet/runtime|[WasmTestOnBrowser-System.Private.Xml.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590245&view=ms.vss-test-web.build-test-results-tab&runId=14245340&resultId=182583)|dotnet/runtime#98802|
|[590138](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590138)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590138&view=ms.vss-test-web.build-test-results-tab&runId=14241432&resultId=100166)|dotnet/runtime#99328|
|[590127](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590127)|dotnet/runtime|[WasmTestOnBrowser-System.Net.WebSockets.Client.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590127&view=ms.vss-test-web.build-test-results-tab&runId=14241400&resultId=186549)|dotnet/runtime#99327|
|[590117](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590117)|dotnet/runtime|[WasmTestOnBrowser-System.Net.WebSockets.Client.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590117&view=ms.vss-test-web.build-test-results-tab&runId=14241036&resultId=100441)|dotnet/runtime#99275|
|[589684](https://dev.azure.com/dnceng-public/public/_build/results?buildId=589684)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=589684&view=ms.vss-test-web.build-test-results-tab&runId=14231366&resultId=100166)|dotnet/runtime#98802|
|[589664](https://dev.azure.com/dnceng-public/public/_build/results?buildId=589664)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=589664&view=ms.vss-test-web.build-test-results-tab&runId=14230990&resultId=100166)|dotnet/runtime#99259|
|[588921](https://dev.azure.com/dnceng-public/public/_build/results?buildId=588921)|dotnet/runtime|[WasmTestOnBrowser-System.Net.WebSockets.Client.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=588921&view=ms.vss-test-web.build-test-results-tab&runId=14211300&resultId=186713)|dotnet/runtime#99273|
|[587640](https://dev.azure.com/dnceng-public/public/_build/results?buildId=587640)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=587640&view=ms.vss-test-web.build-test-results-tab&runId=14171210&resultId=100166)|dotnet/runtime#99040|
|[587167](https://dev.azure.com/dnceng-public/public/_build/results?buildId=587167)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=587167&view=ms.vss-test-web.build-test-results-tab&runId=14153894&resultId=100163)|dotnet/runtime#98910|
|[587069](https://dev.azure.com/dnceng-public/public/_build/results?buildId=587069)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=587069&view=ms.vss-test-web.build-test-results-tab&runId=14149300&resultId=100166)|dotnet/runtime#98986|
|[586983](https://dev.azure.com/dnceng-public/public/_build/results?buildId=586983)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=586983&view=ms.vss-test-web.build-test-results-tab&runId=14146508&resultId=100166)|dotnet/runtime#99040|
|[586000](https://dev.azure.com/dnceng-public/public/_build/results?buildId=586000)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=586000&view=ms.vss-test-web.build-test-results-tab&runId=14114136&resultId=100166)|dotnet/runtime#98540|
|[585735](https://dev.azure.com/dnceng-public/public/_build/results?buildId=585735)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=585735&view=ms.vss-test-web.build-test-results-tab&runId=14108106&resultId=100166)|dotnet/runtime#98986|
|[585615](https://dev.azure.com/dnceng-public/public/_build/results?buildId=585615)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=585615&view=ms.vss-test-web.build-test-results-tab&runId=14105252&resultId=100166)|dotnet/runtime#98559|
|[585288](https://dev.azure.com/dnceng-public/public/_build/results?buildId=585288)|dotnet/runtime|[WasmTestOnBrowser-System.Net.WebSockets.Client.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=585288&view=ms.vss-test-web.build-test-results-tab&runId=14095228&resultId=100441)|dotnet/runtime#97537|
|[583555](https://dev.azure.com/dnceng-public/public/_build/results?buildId=583555)|dotnet/runtime|[WasmTestOnBrowser-System.Net.WebSockets.Client.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=583555&view=ms.vss-test-web.build-test-results-tab&runId=14036894&resultId=186944)|dotnet/runtime#99083|
|[581925](https://dev.azure.com/dnceng-public/public/_build/results?buildId=581925)|dotnet/runtime|[WasmTestOnBrowser-System.Net.WebSockets.Client.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=581925&view=ms.vss-test-web.build-test-results-tab&runId=13986338&resultId=186921)||
|[581903](https://dev.azure.com/dnceng-public/public/_build/results?buildId=581903)|dotnet/runtime|[WasmTestOnBrowser-System.Net.WebSockets.Client.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=581903&view=ms.vss-test-web.build-test-results-tab&runId=13985414&resultId=100441)|dotnet/runtime#99021|
|[581490](https://dev.azure.com/dnceng-public/public/_build/results?buildId=581490)|dotnet/runtime|[WasmTestOnBrowser-System.Net.WebSockets.Client.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=581490&view=ms.vss-test-web.build-test-results-tab&runId=13973868&resultId=100441)|dotnet/runtime#98969|
|[579201](https://dev.azure.com/dnceng-public/public/_build/results?buildId=579201)|dotnet/runtime|[WasmTestOnBrowser-System.Private.Xml.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=579201&view=ms.vss-test-web.build-test-results-tab&runId=13904202&resultId=188985)|dotnet/runtime#98802|
|[577156](https://dev.azure.com/dnceng-public/public/_build/results?buildId=577156)|dotnet/runtime|[WasmTestOnBrowser-System.Net.WebSockets.Client.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=577156&view=ms.vss-test-web.build-test-results-tab&runId=13844610&resultId=186904)|dotnet/runtime#98761|
|[576845](https://dev.azure.com/dnceng-public/public/_build/results?buildId=576845)|dotnet/runtime|[WasmTestOnBrowser-System.Private.Xml.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=576845&view=ms.vss-test-web.build-test-results-tab&runId=13835844&resultId=181170)|dotnet/runtime#98802|
|[576320](https://dev.azure.com/dnceng-public/public/_build/results?buildId=576320)|dotnet/runtime|[WasmTestOnBrowser-System.Private.Xml.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=576320&view=ms.vss-test-web.build-test-results-tab&runId=13822576&resultId=181169)|dotnet/runtime#98802|
|[576100](https://dev.azure.com/dnceng-public/public/_build/results?buildId=576100)|dotnet/runtime|[WasmTestOnBrowser-System.Net.WebSockets.Client.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=576100&view=ms.vss-test-web.build-test-results-tab&runId=13816606&resultId=100441)|dotnet/runtime#98826|
|[575939](https://dev.azure.com/dnceng-public/public/_build/results?buildId=575939)|dotnet/runtime|[WasmTestOnBrowser-System.Private.Xml.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=575939&view=ms.vss-test-web.build-test-results-tab&runId=13812402&resultId=181169)|dotnet/runtime#98802|
|[575938](https://dev.azure.com/dnceng-public/public/_build/results?buildId=575938)|dotnet/runtime|[WasmTestOnBrowser-System.Net.WebSockets.Client.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=575938&view=ms.vss-test-web.build-test-results-tab&runId=13812104&resultId=186903)|dotnet/runtime#98802|
|[575598](https://dev.azure.com/dnceng-public/public/_build/results?buildId=575598)|dotnet/runtime|[WasmTestOnBrowser-System.Private.Xml.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=575598&view=ms.vss-test-web.build-test-results-tab&runId=13804590&resultId=181169)|dotnet/runtime#98802|
|[575530](https://dev.azure.com/dnceng-public/public/_build/results?buildId=575530)|dotnet/runtime|[WasmTestOnBrowser-System.Net.WebSockets.Client.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=575530&view=ms.vss-test-web.build-test-results-tab&runId=13802476&resultId=100441)|dotnet/runtime#98291|
|[575094](https://dev.azure.com/dnceng-public/public/_build/results?buildId=575094)|dotnet/runtime|[WasmTestOnBrowser-System.Net.WebSockets.Client.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=575094&view=ms.vss-test-web.build-test-results-tab&runId=13789238&resultId=100441)|dotnet/runtime#98781|
|[574940](https://dev.azure.com/dnceng-public/public/_build/results?buildId=574940)|dotnet/runtime|[WasmTestOnBrowser-System.Private.Xml.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=574940&view=ms.vss-test-web.build-test-results-tab&runId=13786592&resultId=180269)|dotnet/runtime#98118|
|[574236](https://dev.azure.com/dnceng-public/public/_build/results?buildId=574236)|dotnet/runtime|[WasmTestOnBrowser-System.Net.WebSockets.Client.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=574236&view=ms.vss-test-web.build-test-results-tab&runId=13766532&resultId=100441)|dotnet/runtime#98700|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|69|

**Comment by lewing** [comment]
This appears likely be a variant of https://github.com/dotnet/runtime/issues/98406

**Comment by pavelsavara** [comment]
PR #99259 probably didn't help. There are another occurrences. [Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-7a71d6cb73d04ea286/Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests/1/console.807b1a80.log?helixlogtype=result)

**Comment by lewing** [comment]
Looks like this has been resolved, will leave the issue open a little longer just to be sure

**Comment by lewing** [comment]
This is presumed fixed now, leaving the issue open a little longer to verify
