### ISSUE TITLE
[API Proposal]: Why filesystem APIs like `Directory.CreateDirectory`. `DirectoryInfo.EnumerateFiles`, `File.Create` etc... not `async`

### ISSUE THREAD

**Issue by paule96** [dotnet/runtime#98736]
### Background and motivation

> Warning: This issue is created with not-so-good knowledge of how the OS is handling these operations.

Hi dotnet team,

I recently was using the FileSystem Apis of dotnet to generate complex folders and file structures search in them and delete them.
The problem that I was found most of these APIs are sync. And with very big structures (like 1 million or more objects) it becomes very unresponsive to call `DirectoryInfo.EnumerateFiles`.
That wouldn't be a big problem, but because of its sync nature, it becomes quite fast the bottleneck.

Because I'm sure that I'm not the first one who found this, I ask here more for an explanation/documentation, why it is what it is, because I couldn't find it.
If I'm really the first one and it is possible, it would be nice to get `async` methods for the following methods:

- `Directory.CreateDirectory`
- `Directory.Delete`
- `DirectoryInfo.EnumerateFiles`
- `File.Create`

have a good day :)

### API Proposal

```csharp
Task<IDirectoryInfo> CreateDirectoryAsync(string path);
```

### API Usage

```csharp
await Directory.CreateDirectoryAsync("myAsyncFolder");
```

**Comment by huoyaoyuan** [comment]
Because none of the underlying OSes support such async API natively. See #63153 #67587 #85834 and so on.

Closing as non-actionable currently.
