### ISSUE TITLE
Consider refactoring of Compiler::numArgsOfHWIntrinsic function to improve performance

### ISSUE THREAD

**Issue by 4creators** [dotnet/runtime#9874]
See discussion from this comment on: 

https://github.com/dotnet/coreclr/pull/16736#issuecomment-370188525

category:implementation
theme:intrinsics
skill-level:intermediate
cost:small

**Comment by CarolEidt** [comment]
Closing this, as the code has been somewhat refactored, and there doesn't seem to be evidence that this merits further work.
