### ISSUE TITLE
System.Runtime.Caching MemoryCache.CacheMemoryLimit on macos number seems not correct.

### ISSUE THREAD

**Issue by Nothing-Works** [dotnet/runtime#98793]
```csharp
using System.Runtime.Caching;

Console.WriteLine(MemoryCache.Dafault.CacheMemoryLimit);
```
and I got `1099511627776` back as a result which is around 1 TB, I wish I could have that much memory.

and I saw "MemoryCache.PhysicalMemoryLimit property is only supported on windows." on [NuGet page](https://www.nuget.org/packages/System.Runtime.Caching)

so I am not sure if this is a documentation issue or a runtime bug?

![image](https://github.com/dotnet/runtime/assets/18606648/51beace9-d9a4-4bd9-9746-e5f3dca0f5e4)

**Comment by huoyaoyuan** [comment]
https://github.com/dotnet/runtime/blob/9da53590c9d624b51fddcfb85f76641c78a415d4/src/libraries/System.Runtime.Caching/src/System/Runtime/Caching/CacheMemoryMonitor.cs#L77-L84

Since it doesn't implement physical memory querying for Unix, it simply sets the limit to effectively unlimited.

**Comment by Nothing-Works** [comment]
@huoyaoyuan then should we update the docs to avoid future confusion?
