### ISSUE TITLE
Access to the path 'c:\temp\filename' is denied

### ISSUE THREAD

**Issue by einavha** [dotnet/runtime#98796]
### Description

When I try to create a file with the same name as one of the subfolders - i get - Access to the path 'filename' is denied 

### Reproduction Steps

1. open file explorer
2. go to c:\temp 
3. mkdir filename 
4. create console .net c# app 
5. `public static void Main()
{
    Console.WriteLine(System.IO.File.Exists(@"c:\temp\filename"));
    var f = System.IO.File.Create(@"c:\temp\filename", 100);
}
`

### Expected behavior

the exception should be - "the path or file 'c:\temp\filename' is already exists 

### Actual behavior

Access to the path 'c:\temp\filename' is denied

**Comment by colejohnson66** [comment]
This error is coming from Windows:

https://github.com/dotnet/runtime/blob/6b26684883e4b4bad25a271c231d328f770563d5/src/libraries/System.Private.CoreLib/src/Microsoft/Win32/SafeHandles/SafeFileHandle.Windows.cs#L98-L115

The P/Invoke error retrieved on line 106 is `5`, which is `ERROR_ACCESS_DENIED`.
