### ISSUE TITLE
Failed to setup SSL connection with .NET8 Linux-Container Image with failure "Received an unexpected EOF or 0 bytes from the transport stream" 

### ISSUE THREAD

**Issue by cdlliuy** [dotnet/runtime#98797]
### Description

* We are using http client to ping external website with below code snippets:
```c#
HttpClient client = new HttpClient();
client.DefaultRequestHeaders.Add("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9");
client.Timeout = TimeSpan.FromMilliseconds(5000);
try
{
    var url = "https://data.ad-score.com/img?pid=1000943&tt=g&tid=27152&l1=229666&l2=3090&l3=8070911";
    var response = await client.GetAsync(url, HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(false);
    var statusCode = (int)response.StatusCode;
    var statusCodeString = response.StatusCode.ToString();
    Console.WriteLine($"{DateTime.UtcNow} RunTasks: Status code of Impression Tracking Url is {statusCode} {statusCodeString}");
}
catch ( Exception ex )
{
    Console.WriteLine($"{DateTime.UtcNow} RunTasks: thrown exception {ex}");
}
```
* The target framework is `net80` in csproj
* When running this code on Windows,  no issue reported
* When running this code with .NET8 linux container, 
```
FROM mcr.microsoft.com/dotnet/aspnet:8.0
...
CMD ["dotnet", "yinghttpconnectiontest.dll"]
```
I got exception below:
```
2/22/2024 8:03:33 AM RunTasks: thrown exception System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
...
```
* When running this code with .NET7 Linux container as base + copy .NET8 runtime to add .NET8 support
```
FROM mcr.microsoft.com/dotnet/aspnet:7.0
COPY --from=mcr.microsoft.com/dotnet/aspnet:8.0 /usr/share/dotnet /usr/share/dotnet
...
```
It works good again with above setting.  I can't distinguish whether it is an issue for .NET runtime, or anything wrong in mcr.microsoft.com/dotnet/aspnet8.0 image itself

=============

To support the debug,  we collected below information:
* a tcpdump when accessing the url but failed: 
[tcpdump.txt](https://github.com/dotnet/runtime/files/14371051/tcpdump.txt)  ==> please rename to *.cap to open in wireshark
* the ssl trace log for "System.Net.Security" when it worked successfully in  .NET7 base image
[net7base.good.txt](https://github.com/dotnet/runtime/files/14371097/net7base.good.txt)
* the ssl trace log for "System.Net.Security" when it failed in  .NET8 base image
[net8base.bad.txt](https://github.com/dotnet/runtime/files/14371107/net8base.bad.txt)

I expect to understand why .NET8 linux container can't run this code pieces correctly

### Reproduction Steps

see description above

### Expected behavior

see description above

### Actual behavior

see description above

### Regression?

yes, works in .net7

**Comment by cdlliuy** [comment]
@wfurt , can you help to triage ? Thanks a lot!

**Comment by cdlliuy** [comment]
@rzikm ,    you do "dotnet run" instead of "docker run" when trying to reproduce the issue. 
with "dotnet run" , I think you execute the program on Windows , so it can't reproduce at all.

Here is my code and repro (see the readme file):
https://github.com/cdlliuy/yinghttpconnectiontest/tree/master

**Comment by rzikm** [comment]
Interestingly enough, the "default" behavior of `openssl s_client` is different than .NET's (s_client connects even without the config change above). Although we don't set anything special and rely on the default config settings.

tagging @wfurt in case he remembers something.

**Comment by rzikm** [comment]
I will keep this task open to remind me to investigate the difference between the two behaviors. But currently I don't see anything actionable from the dotnet/runtime point of view.

**Comment by rzikm** [comment]
I am not sure yet, that's what I want to investigate.

**Comment by wfurt** [comment]
we can test it e.g. setup public instance with Kestrel and see what adding `DEFAULT@SECLEVEL=2` would do to the security rating. I would probably like the level more than list of specific cipherusptes as it can change over time. 

We can probably also chase openssl change that removed the block and study reasons behind it.

**Comment by cdlliuy** [comment]
OK, I verified that copy the openssl.cnf from aspnet:7.0 can workaround the issue. 
```
FROM mcr.microsoft.com/dotnet/aspnet:8.0
COPY --from=mcr.microsoft.com/dotnet/aspnet:7.0 /etc/ssl/openssl.cnf /etc/ssl/openssl.cnf
```

@rzikm  @wfurt ,  for RSA support, keeping the consistent behavior across Windows, Linux should be one of criteria to evaluate the different cipher setting.   
If .NET runtime behavior won't change, should we ask for `dotnet/dotnet-docker` to backport the openssl.cnf ?

**Comment by rzikm** [comment]
> What is the decision for the cipher setting DEFAULT@SECLEVEL=2 in .NET runtime?

We did not decide yet, first, we want to see what it does to SslLabs score, but that requires the server to be publicly accessible so it takes some time to set up. It is still on our todo list.

**Comment by bartonjs** [comment]
The list that we have as our default was assigned by the Microsoft Crypto Board.  We can't add insecure ciphersuites to it.  Anyone who needs a less secure ciphersuite has to change system configuration, or use the per-call configuration options.

**Comment by wfurt** [comment]
_maybe_ the constant is ok. But we do not respect setting the OS has e.g. `openssl s_client` works but `SslStream` does not. Perhaps we need more adjustments for OpenSSL 3 and their default configurations.

Asking `openssl.cnf` modifications on client is problematic IMHO as the applications typically don't own the OS (and should not IMHO as I would be pissed personally if each app install changes my crypto)

I also check `Edge` browser on Windows and it offers 16 cipherusptes including `TLS_RSA_AES_128_GCM_SHA256` so it probably is not that bad. Perhaps we should have different defaults for client & server?  I don't really see good reason why `HttpClient` needs to drop anything different than browser. 
  
Since this is now also our default docker image I feel it is going to be problematic unless we do something.

**Comment by bartonjs** [comment]
> But we do not respect setting the OS has

The change that we made was that if someone has expressed opinions in openssl.cnf, we respect those.  But we don't respect OpenSSL's defaults because it allows too much bad stuff in.

>  also check Edge browser on Windows and it offers 16 cipherusptes including TLS_RSA_AES_128_GCM_SHA256

Windows has complicated history of back-compat concerns.  When we changed our defaults on Linux we were told to make them to a higher standard.

**Comment by rzikm** [comment]
Considering that:
- a workaround exists, see [this comment](https://github.com/dotnet/runtime/issues/98797#issuecomment-1961125933)
- current behavior is by design, see [bartonjs's comment](https://github.com/dotnet/runtime/issues/98797#issuecomment-1981825405)
- There have been few reports of the issue until now

We don't plan to make any changes at this time. In case more users hit this issue, either upvote the issue or file a new one. If a lot of users are being affected by this issue, we will reconsider our position on this.
