### ISSUE TITLE
ReadOnly Attribute on Directory results in AccessDenied-Exception

### ISSUE THREAD

**Issue by AliveDevil** [dotnet/runtime#98807]
### Description

When trying to delete a folder that was customized through e.g. Windows Explorer, I cannot delete that folder, without first going through each and every directory removing all Read-Only attributes on everything.

### Reproduction Steps

CsWin32-Dependency
<details>
<summary>NativeMethods.txt</summary>

```
CreateFile
GENERIC_ACCESS_RIGHTS
``` 
</details>

<details>
<summary>Program.cs</summary>

```
﻿using Windows.Win32.Foundation;
using Windows.Win32.Storage.FileSystem;
using static Windows.Win32.PInvoke;
var path = Path.GetFullPath("Delete-Test");
Directory.CreateDirectory(path);

using (CreateFile(
	path,
	(uint)GENERIC_ACCESS_RIGHTS.GENERIC_READ,
	(FILE_SHARE_MODE)7,
	null,
	FILE_CREATION_DISPOSITION.OPEN_EXISTING,
	FILE_FLAGS_AND_ATTRIBUTES.FILE_FLAG_BACKUP_SEMANTICS | FILE_FLAGS_AND_ATTRIBUTES.FILE_FLAG_DELETE_ON_CLOSE,
	null))
{
	File.SetAttributes(path, FileAttributes.ReadOnly);
	Directory.Delete(path, true);
}
```
</details>

### Expected behavior

Deletion should not be blocked by ReadOnly-attribute.

### Actual behavior

```
Unhandled exception. System.IO.IOException: Access to the path '\\?\C:\Users\jmalek\Desktop\delete-test\Delete-Test' is denied.
   at System.IO.FileSystem.RemoveDirectoryInternal(String fullPath, Boolean topLevel, Boolean allowDirectoryNotEmpty)
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Program.<Main>$(String[] args) in C:\Users\jmalek\Desktop\delete-test\Program.cs:line 17
```

### Known Workarounds

Manually navigate through folder structure, then try to remove read only attribute, retry delete.

### Configuration

- **.NET Framework**: Any
- **.NET**: All, Windows
- **Platform**: Any Architecture, Windows

### Other information

MSVC has fixed this in STL: [microsoft/STL#1559](https://redirect.github.com/microsoft/STL/pull/1559)

**Comment by Jozkee** [comment]
For better or for worse, this is expected in Windows and is [documented](https://learn.microsoft.com/en-us/dotnet/api/system.io.file.delete?view=net-8.0&redirectedfrom=MSDN#exceptions).

> 
> UnauthorizedAccessException
> path specified a read-only file.
