### ISSUE TITLE
mono: Implement support for generic unmanaged calli

### ISSUE THREAD

**Issue by hez2010** [dotnet/runtime#98819]
As per https://github.com/dotnet/runtime/pull/97079#discussion_r1498219789
We have implemented support for generic unmanaged calli in both CoreCLR and NativeAOT. We should also implement it for mono.

Work items:
- [ ] Support generic unmanaged calli for blittable types
- [ ] Enabling generic unmanaged calli can technically enable generic varargs as well, make sure to block generic varargs usage ( in CoreCLR we throw a `NotSupportedException`).

Optional:
- Add an error mode to throw `MarshalDirectiveException` for runtime marshaling (i.e. generic unmanaged calli with non-blittable types). Note that NativeAOT doesn't verify this and will simply produce bad codegen.

After the implementation, we will also need to re-enable tests for generic calli in `src/tests/Interop/Interop.csproj`.

And we are skipping tests on mono, make sure to enable them as well: https://github.com/dotnet/runtime/blob/main/src%2Ftests%2FInterop%2FMarshalAPI%2FFunctionPointer%2FGenericFunctionPointer.cs#L11-L12

**Comment by vargaz** [comment]
With the PRs above, this should mostly work now.

**Comment by hez2010** [comment]
Note that tests are still being skipped on mono.
