### ISSUE TITLE
Question about exception handling

### ISSUE THREAD

**Issue by MrDave1999** [dotnet/runtime#98815]
I'm curious about this line:
https://github.com/dotnet/runtime/blob/6b26684883e4b4bad25a271c231d328f770563d5/src/coreclr/vm/exceptionhandling.cpp#L237

A global array is used to store the stack trace but a lock is created so that other threads cannot alter the array until the current thread unlocks it. If a thread A throws an exception, the rest of the threads must wait until the stack trace array is unlocked.
Am I right or did I misunderstand?

**Comment by jkotas** [comment]
There is no global array. The stack trace array is per exception object. Note that nothing prevents the same exception object to be thrown on multiple threads at the same time.

There is global lock. The lock does not have to be global, it would be fine for the lock to be per stacktrace array, but it is not how it is implemented.
