### ISSUE TITLE
BitArray.CopyTo(Array, int) throws an ArgumentException, if BitArray.Length has been reduced to a multiple of 32

### ISSUE THREAD

**Issue by fsc-sma** [dotnet/runtime#98813]
### Description

BitArray.CopyTo(Array, int) throws an ArgumentException, if BitArray.Length has been reduced to a multiple of 32

### Reproduction Steps

The following code works as expected:
```
using System.Collections;

var bitArray = new BitArray(256);
bitArray.Length = 33;

var intArray = new int[2];
bitArray.CopyTo(intArray, 0);
```

But if the length is further reduced to 32 then an ArgumentException is thrown:
```
using System.Collections;

var bitArray = new BitArray(256);
bitArray.Length = 32;

var intArray = new int[2];
bitArray.CopyTo(intArray, 0);
```

### Expected behavior

The relevant values get copied.

### Actual behavior

ArgumentException if BitArray.Length is reduced to a multiple of 32. Reasons seems to be that the length that should be copied is not calculated using the BitArray.Length. Instead the length of the underlying int array is used: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Collections/src/System/Collections/BitArray.cs#L764

Problem is the underlying int array is not resized when the BitArray.Length is reduced by a small amount (< BitArray._ShrinkThreshold).

### Regression?

In .NET 4.8 the length that should be copied is calculated using the BitArray.Length: https://referencesource.microsoft.com/#mscorlib/system/collections/bitarray.cs,370

**Comment by eiriktsarpalis** [comment]
Seems like a bug in this specific branch of the `CopyTo` implementation. Should be using `m_length` instead of `m_array.Length`.

https://github.com/dotnet/runtime/blob/e86f8d00c62386b4c1b85e8f56be5d63cad5fbb8/src/libraries/System.Collections/src/System/Collections/BitArray.cs#L761-L765

Would you be interested in contributing a PR?
