### ISSUE TITLE
XDocument parses strings with ASCII HTML number to ASCII Symbol

### ISSUE THREAD

**Issue by david-jng** [dotnet/runtime#98810]
### Description

I want to load a xml file which contains` &#127;` in a string value of an XML-Element attribute. XDocument parses this to the ASCII Symbol.

**For example:**
`&#126;` becomes `~`
`&#127;` becomes `DEL`

### Reproduction Steps

You can use the following code with the attached XML-file to reproduce the issue.

**C#-Code:**
```
        private static void testASCII()
        {

            string inputFile = @"F:\original-document.xml";
            string outputFile = @"F:\parsed-document.xml";

            if (File.Exists(outputFile))
            {
                File.Delete(outputFile);
            }

            StringBuilder sb = new StringBuilder();
            StreamReader reader = new StreamReader(inputFile);
                                   
            while (reader.Peek() >= 0)
            {
                sb.Append((char)reader.Read());
            }

            XDocument originalDocument = XDocument.Parse(sb.ToString());

            // write to file
            StreamWriter writer = new StreamWriter(outputFile);
            using (writer)
            {
                writer.Write(originalDocument);
            }
        }
    }
```

**XML-File:**

```
<?xml version="1.0" encoding="UTF-8"?>
<TCXML>
	<Option value="X&amp;@lxqu@x}h}@hn}rouyrhjspiqy@~nuyz&#127;}oyChyqlC-y-y/(-."/>
</TCXML>
```

### Expected behavior

The created XML-file should be equal to the original document.

### Actual behavior

The created XML-file converted the ASCII HTML number to the ASCII-Symbol.

### Known Workarounds

No workaround found.

### Configuration

Microsoft Visual Studio Community 2022
Version 17.9.0
VisualStudio.17.Release/17.9.0+34607.119
Microsoft .NET Framework
Version 4.8.09037

Installierte Version: Community

ASP.NET and Web Tools   17.9.195.45391
ASP.NET and Web Tools

Azure App Service-Tools v3.0.0   17.9.195.45391
Azure App Service-Tools v3.0.0

C#-Tools   4.9.0-3.24081.11+989117396f26e5453ff157df610d22ce45b6b0a9
C#-Komponenten, die in der IDE verwendet werden. Abhängig von Ihrem Projekttyp und den zugehörigen Einstellungen kann eine andere Version des Compilers verwendet werden.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet-Paket-Manager   6.9.1
NuGet-Paket-Manager in Visual Studio. Weitere Informationen zu NuGet finden Sie unter https://docs.nuget.org/.

TypeScript-Tools   17.0.30103.2001
TypeScript-Tools für Microsoft Visual Studio

Visual Basic-Tools   4.9.0-3.24081.11+989117396f26e5453ff157df610d22ce45b6b0a9
Visual Basic-Komponenten, die in der IDE verwendet werden. Abhängig von Ihrem Projekttyp und den zugehörigen Einstellungen kann eine andere Version des Compilers verwendet werden.

Visual F# Tools   17.9.0-beta.23614.3+a521e1cd420beb56c15faf6836184fadd2b7937a
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
KI-gestützte Entwicklung für Visual Studio.

**Comment by colejohnson66** [comment]
This is probably by design. XML entities should be evaluated by the parser, not the consumer.

**Comment by danmoseley** [comment]
@david-jng What are you trying to achieve?

**Comment by jeffhandley** [comment]
@david-jng I can't come up with any way to easily achieve what you're looking to do here, which as I understand it is to get the _raw_ attribute value without any unescaping being done by the reader. As @colejohnson66 mentioned, this is by design as the parser processes these values (safely). You might want to consider an approach where both sides of your comparison are parsed and perhaps re-saved so that the content will have the same escaping.
