### ISSUE TITLE
Dependency Name does not contain 'Microsoft.SourceBuild.Intermediate.' error in source build leg

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#98822]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=573783
Build error leg or test failing: Build / linux-x64 Release PortableSourceBuild / Build
Pull request: https://github.com/dotnet/runtime/pull/98731

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Dependency Name does not contain 'Microsoft.SourceBuild.Intermediate.'",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

**Comment by akoeplinger** [comment]
This was caused by https://github.com/dotnet/runtime/pull/98554 which was reverted in https://github.com/dotnet/runtime/pull/98737, I think the PR you mentioned just happened to be in the broken time window.
