### ISSUE TITLE
[Analyzer Proposal]: Warn on use of StreamReader.EndOfStream in async methods

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#98834]
StreamReader.EndOfStream is a pernicious little property.
https://learn.microsoft.com/en-us/dotnet/api/system.io.streamreader.endofstream?view=net-8.0

It seems harmless, like it's just checking something quick and easy. And if there's already some data buffered in the StreamReader, it is: if there's remaining data to read, it's not at the end of the stream. But if there's no data buffered, the only way it can know if it's at the end of the stream is to try to read from the stream and wait until either at least a byte of data is available or it gets back eof. That is a synchronous blocking operation.

In the last month, I've seen several uses of EndOfStream along the lines of:
```C#
while (!reader.EndOfStream)
{
    string? line = await reader.ReadLineAsync();
    ...
}
```
This is problematic because while the developer obviously intended to do their I/O asynchronously, there's a really good chance most of it will end up being done synchronously as part of EndOfStream, making the API synchronously instead of asynchronously blocking. Separately, even if this were intended to be entirely synchronous, this doesn't actually need to use EndOfStream: ReadLine{Async} will give back null if at EOF, so that can be used instead of EndOfStream.

While there's rarely a good reason to use EndOfStream, I'm not sure it rises to the level of obsoleting it. But we should have an analyzer that warns on any use of it in an async method, as it's almost always going to be doing the wrong thing there.

**Comment by colejohnson66** [comment]
Why is EndOfStream bad (ignoring redundancy from null returns)? Sure, that property getter will be synchronous, but then the await will bounce the task to the thread pool.

**Comment by stephentoub** [comment]
> Why is EndOfStream bad (ignoring redundancy from null returns)? Sure, that property getter will be synchronous, but then the await will bounce the task to the thread pool.

I don't understand the comment. EndOfStream itself calls a synchronous read method. By the time it returns, the damage is done.

**Comment by colejohnson66** [comment]
Ah. I was not aware that it would perform a read; I was under the impression it was getter for a privately set flag.

**Comment by stephentoub** [comment]
Yup, as I wrote above, "But if there's no data buffered, the only way it can know if it's at the end of the stream is to try to read from the stream and wait until either at least a byte of data is available or it gets back eof. That is a synchronous blocking operation."

**Comment by bartonjs** [comment]
* Detect when an input parameter or a local could be ReadOnlySpan or ReadOnlyMemory instead of Span or Memory
* The analyzer shouldn't analyze parameters on overridden members
* The analyzer will probably not provide analysis for a Span that gets used in a `fixed` statement, rather than decide if it has read semantics or write semantics on the pointer.
* It should be on by default for non-visible members, with an opt-in for public.
  * Pipedream: It should run on "new code", if we could determine that.

Fixer: Obviously
Category: Reliability
Severity: Info

**Comment by mpidash** [comment]
I would like to work on this analyzer if that's okay :)

**Comment by lindexi** [comment]
I'm really looking forward to this feature.

My WPF application is hangs because of this problem.

I wrote the [Chinese blog](https://blog.lindexi.com/post/dotnet-%E5%B7%B2%E7%9F%A5%E9%97%AE%E9%A2%98-%E8%AD%A6%E6%83%95-StreamReader-%E7%9A%84-EndOfStream-%E5%8D%A1%E4%BD%8F%E7%BA%BF%E7%A8%8B.html) about this.

And the demo code:

```csharp
var fooStream = new FooStream();
var streamReader = new StreamReader(fooStream);

while (!streamReader.EndOfStream)
{
    var line = await streamReader.ReadLineAsync();
    if (line is null)
    {
        break;
    }
}

class FooStream : Stream
{
    public FooStream()
    {
        _buffer = "123\r\n"u8.ToArray();
    }

    private readonly byte[] _buffer;

    public override void Flush()
    {
    }

    public override int Read(byte[] buffer, int offset, int count)
    {
        // 模拟卡顿
        Thread.Sleep(10000);

        if (count >= _buffer.Length)
        {
            count = _buffer.Length;

            Array.Copy(_buffer, 0, buffer, offset, count);
        }

        return count;
    }

    public override long Seek(long offset, SeekOrigin origin)
    {
        return offset;
    }

    public override void SetLength(long value)
    {
    }

    public override void Write(byte[] buffer, int offset, int count)
    {
    }

    public override bool CanRead => true;
    public override bool CanSeek => false;
    public override bool CanWrite => false;
    public override long Length => long.MaxValue;
    public override long Position { get; set; }
}
```

You can find all my demo code in [github](https://github.com/lindexi/lindexi_gd/tree/96a09bc149186f9122f263f887257dcbf209d4e3/Workbench/HerrigeedaJardarkewel)

**Comment by fabianoriccardi** [comment]
I've just met this issue... Can you add a remark in the official docs? There is no reference to the fact that EndOfStream property takes time and can blocks asynchronous operations.

**Comment by stephentoub** [comment]
https://github.com/dotnet/dotnet-api-docs/pull/10661 adds a note to the docs, but better is https://github.com/dotnet/roslyn-analyzers/pull/7390, which actually adds a diagnostic.
