### ISSUE TITLE
BitArray.CopyTo throws IndexOutOfRangeException under certain conditions

### ISSUE THREAD

**Issue by lilinus** [dotnet/runtime#98859]
### Description

If `BitArray.CopyTo` is invoked with:
- destination array being an `int[]` (does not reproduce with `bool[]` nor `byte[]`)
- the destination array is too small
- bit count in `BitArray` is not divisible by 32.

Throwing of `ArgumentException` is delegated to calling of `Array.Copy`.
Although if the `BitArray` contains "extra bits", this check is not done for the last extra bits, so `IndexOutOfRangeException` can be thrown. The check is essentially of-by one under these circumstances.

### Reproduction Steps

```
new BitArray(33).CopyTo(new int[1], 0);
```

### Expected behavior

It should throw `ArgumentException` according to documentation

### Actual behavior

It throws `IndexOutOfRangeException`

### Other information

It's a bit of an edge case I think this is probably an oversight and not by design (ie. not incorrect documentation)

**Comment by eiriktsarpalis** [comment]
What do the `CopyTo` implementations in other collection types do in this case? I think this should inform whether we update the implementation or correct the documentation.
