### ISSUE TITLE
Introduction of File Provider Registry for DI

### ISSUE THREAD

**Issue by thompson-tomo** [dotnet/runtime#98850]
### Background and motivation

I want to have the ability to register multiple file providers to the DI container based on config & then use keyed services to obtain the provider based on the name. 

Still work in progress

### API Proposal

```csharp
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddSingleton<FileProviderMetrics>();
builder.Services.AddFileProviderRegistry(s => {
s.AddProvider<IFileProvider>(sectionName)
});
```

### API Usage

```csharp
// Getting the provider out

public class ValuesController : ControllerBase
 {
        private readonly IFileProvider _fileProvider;
        public ValuesController(IFileProviderCollection fileProviderCollection)
        {
            _ fileProvider = fileProviderRegistry.GetProvider("providerName");
        }
     //Other methods
  }

```

**Comment by pinkfloydx33** [comment]
Would registering it as a keyed service work?

**Comment by thompson-tomo** [comment]
Thanks for the tip @pinkfloydx33 yes keyed services would be useful in the implementation.

**Comment by pinkfloydx33** [comment]
I meant as _the_ solution. A lot of provider/registry/factory interfaces that existed up to this point could likely be replaced with keyed services instead. Then you don't need an extra provider/registry interface/implementation. 

This pattern exists in a few libraries we use. For us, the most prevalent (outside of HttpClient) is the Azure SDK where if you have more than one instance of a particular type you need to use their factories plus a name. The implementation has always been _a bit annoying_ and I'm sure they'd have used keyed services instead had they existed at the time. My point is that I don't think we should be adding additional infrastructure for things that can be solved with keyed services... plus a trivial wrapper by the consumer if they really needed it. 

(Though, I suppose it depends on who the target is. I'm not sure if keyed services can be used outside of net8 via an OOB package or similar)

**Comment by thompson-tomo** [comment]
As i have been working through the details of the proposal, it emerged more that the current functionality offered by file providers is substantially more limited than i thought it was and is not really suitable for what i am needing hence closing issue
