### ISSUE TITLE
[API Proposal]: Support JsonCommentHandling.Allow in JsonNode

### ISSUE THREAD

**Issue by martincostello** [dotnet/runtime#98865]
### Background and motivation

I've been working on [a .NET Tool](https://github.com/martincostello/dotnet-bumper) where edits are made to user-provided content on disk to make targeted edits to their files to facilitate upgrading from one version of .NET to another by automatically applying "known" changes to the repository (for example, changing the .NET SDK version in `global.json` from `6.0.xxx` to `8.0.201`).

As part of these edits, I would like to preserve the user's original documents as much as possible with minimally invasive changes (keep their line endings https://github.com/dotnet/runtime/issues/84117#issuecomment-1961684841, retain any UTF-8 BOM marks, etc.).

As such I would also like to preserve any comments the user may have in a JSON file, such as in a Visual Studio Code `launch.json` file where these can be common.

Here's an example of such a file that surfaced this to me during testing, which looks a lot like it was copy-pasted from an example somewhere:

<details>

<summary>.vscode/launch.json</summary>

```jsonc
{
    "version": "0.2.0",
    "configurations": [
        {
            // Use IntelliSense to find out which attributes exist for C# debugging
            // Use hover for the description of the existing attributes
            // For further information visit https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            // If you have changed target frameworks, make sure to update the program path.
            "program": "${workspaceFolder}/test/MyApp.Tests/bin/Debug/net6.0/MyApp.Tests.dll",
            "args": [],
            "cwd": "${workspaceFolder}/test/MyApp.Tests",
            // For more information about the 'console' field, see https://aka.ms/VSCode-CS-LaunchJson-Console
            "console": "internalConsole",
            "stopAtEntry": false
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach"
        }
    ]
}
```

</details>

Using the `JsonNode` APIs today allows me to at least _tolerate_ comments and not throw an exception (oops 😅) with `JsonCommentHandling.Skip`, but when saving any edits back to disk any user comments are lost. The user can of course reject the edits when they review the Git diff and just keep the bits that were intended, but that's more user friction that I would like for the purpose of the tool.

Ideally, I could set `CommentHandling` on `JsonDocumentOptions` to `JsonCommentHandling.Allow` and the comments would be preserved when the edits are written back to disk.

I did try to find an existing issue for this or something concrete on a definite reason why this would never be supported, but I couldn't find anything that seemed specific to `JsonNode`.

### API Proposal

Change `JsonDocument.CommentHandling` to allow `Allow` for more scenarios and not throw.

https://github.com/dotnet/runtime/blob/973ceee20c4807c780f72e24a1859a2c695ddf39/src/libraries/System.Text.Json/src/System/Text/Json/Document/JsonDocumentOptions.cs#L33-L34

### API Usage

```csharp
using System.Text.Json;
using System.Text.Json.Nodes;

JsonNode node;
using (var stream = File.OpenRead(fileName))
{
    var documentOptions = new JsonDocumentOptions()
    {
        AllowTrailingCommas = true,
        CommentHandling = JsonCommentHandling.Allow
    };
    node = JsonNode.Parse(stream, documentOptions: documentOptions); // <-- Doesn't throw
}

bool edited = false;

// Do some processing that might edit the file

if (edited)
{
    var writerOptions = new JsonWriterOptions() { /* Whatever */ };

    using var stream = File.OpenWrite(fileName)
    using var writer = new Utf8JsonWriter(stream, writerOptions);

    node.WriteTo(writer);

    await writer.FlushAsync();
    stream.SetLength(stream.Position);
}
```

### Alternative Designs

Introduce a new type or extend `JsonNodeOptions` to allow for this. The latter seems like a bit of a foot gun though as there would be two parameters to `JsonNode.Parse()` with the same properties of the same type on them, but one would work for this case and the other not.

**Comment by gregsdennis** [comment]
If you're not editing the json, m you might look into `JsonDocument`/`JsonElement` instead of nodes.  It'll be a little more cumbersome to work with, but I think it preserves that stuff.

**Comment by eiriktsarpalis** [comment]
Preserving comments is certainly something possible in the case of `JsonDocument` since it's an immutable DOM building on top of the underlying JSON encoding. I don't think it can be done for the case of the mutable `JsonNode` without some kind of first-class support for comments in the model itself, however a can't think of a good way that this could be achieved.

**Comment by slang25** [comment]
Roslyn has the concept of "trivia nodes" for whitespace for example, would adding an option to include similar sorts of nodes be feasible, or would it break the semantics of the current design?

**Comment by eiriktsarpalis** [comment]
> or would it break the semantics of the current design?

I think it would. For example `JsonObject` is explicitly modelled as `IDictionary<string, JsonNode>` so it's not clear how comments would fit in that mould: are comments within JSON objects associated with a specific property? What if you have an empty object that contains comments? One thought might be to have a `JsonNode.Comments` that contains comments associated with a particular node, although such an association would be imprecise and would generally result in non-roundtripable JSON.

**Comment by eiriktsarpalis** [comment]
I would be inclined to close this, unfortunately the ship has sailed when it comes to `JsonNode` representing comments in an accurate manner.
