### ISSUE TITLE
Could not load file or assembly \bin\Debug\net8.0\atlas.clinicmanagement.exe'. Format of the executable (.exe) or library (.dll) is invalid.'

### ISSUE THREAD

**Issue by LeoAguanta** [dotnet/runtime#98868]
### Description

After upgrading from .Net 6 to .Net 8 my reference project did not work anymore, this was working in .Net 6.
![image](https://github.com/dotnet/runtime/assets/49972225/d52f485e-199d-44f0-997d-db4df9b90b89)

### Reproduction Steps

When running the application

### Expected behavior

Should be working fine

### Actual behavior

An error occured 
![image](https://github.com/dotnet/runtime/assets/49972225/c1972d07-059a-49eb-96fd-5f33f4de83a7)

**Comment by vitek-karas** [comment]
The `.exe` should not be loaded as an assembly, in .NET 6+ the exe is just plain native executable, not a managed assembly.
Is that the main executable of the application? Or is it a "secondary" executable.
Do you know where it comes from? What is trying to load it? The callstack on the exception might be able to tell.

**Comment by LeoAguanta** [comment]
Hi @vitek-karas , Thank you for the response

The .exe is my reference project , that project is a Winform .Net Framework 4.8, and contains all of my logic and services.
but why it is working if I downgrade my to .Net 6? 
here is the screen shot of may projects. the atlas.clinicmanagement is the .exe and the atlas.clinicmanagement.web is my main application where the error occured
![image](https://github.com/dotnet/runtime/assets/49972225/bd8d05fe-af77-4056-80f8-177d8f23f76e)

**Comment by LeoAguanta** [comment]
![image](https://github.com/dotnet/runtime/assets/49972225/ddcb705f-667c-44e5-9de1-55477baba3e6)

**Comment by LeoAguanta** [comment]
I am also using Autofac for Dependency Injection. 
![image](https://github.com/dotnet/runtime/assets/49972225/238cba60-9db5-45c6-afcf-5cd02c05623c)
![image](https://github.com/dotnet/runtime/assets/49972225/4d0c700b-d76e-4a05-bd03-c96fcc81c9cb)

**Comment by LeoAguanta** [comment]
should I transfer my logic and services to a different project?

**Comment by elinor-fung** [comment]
Do you have a minimal repro you could share?
The callstack of the exception or a dump file would also be helpful.
