### ISSUE TITLE
[API Proposal]: Track Exceptions in flight (information about the state that existed for the thread when the exception occurred)

### ISSUE THREAD

**Issue by Yun-Ting** [dotnet/runtime#98878]
### Background and motivation

Currently, [Marshal.GetExceptionPointers](https://github.com/dotnet/runtime/blob/cd850233414468a8ffe84fc8fa05a36d0b3b1316/src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.NativeAot.cs#L225) is not supported in native AOT.

See the environment control flag in runtime: https://github.com/dotnet/runtime/blob/b80048efbdd1d547efafefe8667d82de9a074850/src/libraries/Common/tests/TestUtilities/System/PlatformDetection.cs#L97

See https://github.com/open-telemetry/opentelemetry-dotnet/pull/5374#issuecomment-1956963500 on how this could be achieved.

### API Proposal

Currently, getting in-flight exception is not supported in native AOT:
https://github.com/dotnet/runtime/blob/b80048efbdd1d547efafefe8667d82de9a074850/src/coreclr/vm/comutilnative.cpp#L394

I propose to enable this feature in native AOT:
```cpp
FCIMPL0(EXCEPTION_POINTERS*, ExceptionNative::GetExceptionPointers)
{
    FCALL_CONTRACT;

    EXCEPTION_POINTERS* retVal = NULL;

    Thread *pThread = GetThread();
    if (pThread->IsExceptionInProgress())
    {
        retVal = pThread->GetExceptionState()->GetExceptionPointers();
    }

    return retVal;
}
FCIMPLEND
```

### API Usage

See this issue: https://github.com/open-telemetry/opentelemetry-dotnet/issues/5358

**Comment by jkotas** [comment]
> Currently, getting in-flight exception is not supported in native AOT:

The `Marshal.GetExceptionPointers` API is not the right API to use for your scenario. It is both unnecessarily compilated API to handle your scenario and also not 100% reliable for your scenario as pointed out in https://github.com/open-telemetry/opentelemetry-dotnet/pull/5374#issuecomment-1957058293 and our offline discussion.

Could you please describe what you would like to actually achieve in your scenario? We can then work on the design on the right API that is both reliable and not unnecessarily compilated.

**Comment by Yun-Ting** [comment]
> Could you please describe what you would like to actually achieve in your scenario? We can then work on the design on the right API that is both reliable and not unnecessarily compilated.

Hi @jkotas, automatically detect exceptions and set Activity status is what we want to achieve.
See more details here: https://github.com/open-telemetry/opentelemetry-dotnet/issues/1853
Thank you.

**Comment by jkotas** [comment]
I am not able to figure out the desired semantics from this issue and from the code. (I know what your current code does, but I do not think that it is the semantics you actually want.)

Could you please describe the desired semantics? When is `ExceptionProcessor` expected to call `SetStatus(ActivityStatusCode.Error)` on the activity?

**Comment by MichalStrehovsky** [comment]
@reyang or @CodeBlanch could you give us some details on what semantics are needed for tracking exception in flight in OpenTelemetry? This is in reference to https://github.com/open-telemetry/opentelemetry-dotnet/pull/1858. We see `Marshal.GetExceptionPointers` is used and numerical values it returns are being compared. We don't document the numerical value, only the structure that is pointed by the pointer. It's not clear to us what comparing numerical values is achieving.

**Comment by jkotas** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/89724
