### ISSUE TITLE
.NET 8 - Blazor Web App - Sample solution doesn't work on Safari 

### ISSUE THREAD

**Issue by AleAntonellis** [dotnet/runtime#98872]
### Description

I deployed the sample Blazor Web App project on Azure and I was not able to use the Counter on Safari, iPhone and iPad.
I didn't modify anything from the sample project.

<img width="1280" alt="BlazorWebAppScreen" src="https://github.com/dotnet/runtime/assets/34882045/3a1bfc95-c139-4a38-9cdb-b5b78c8e8cfa">

Here my Azure host if it can help: [blazorapp120240220220522.azurewebsites.net ](https://blazorapp120240220220522.azurewebsites.net/) 

### Reproduction Steps

- Create the Blazor Web App in Visual Studio
- Deploy the App on Azure
- Open it on Safari
- Use the Counter

### Expected behavior

The counter should increase the number

### Actual behavior

The counter doesn't work with errors in Console

### Regression?

Blazor Web Assembly in .NET 6 works as expected

### Known Workarounds

Downgrade to .NET 6

**Comment by vcsjones** [comment]
> Counter on Safari, iPhone and iPad.

What version of Safari is this? Older Safari does not work with SIMD, which is enabled by default in .NET 8. You can disable SIMD as documented at https://learn.microsoft.com/aspnet/core/blazor/tooling?view=aspnetcore-8.0&pivots=windows#single-instruction-multiple-data-simd by adding this to your project file:

```xml
<PropertyGroup>
  <WasmEnableSIMD>false</WasmEnableSIMD>
</PropertyGroup>
```

> Here my Azure host if it can help: [blazorapp120240220220522.azurewebsites.net](https://blazorapp120240220220522.azurewebsites.net/)

Your sample project works for me in Safari 17.

**Comment by maraf** [comment]
Also the error message points to a documentation
