### ISSUE TITLE
Combination of generics, ref struct and ref parameter causes type constraint IL verification errors

### ISSUE THREAD

**Issue by mikernet** [dotnet/runtime#98892]
### Description

Some combination of generics, `ref struct` and `ref` parameters causes validation to fail for the code below. Making `BinaryReader` a normal non-ref `struct` or making the parameters non-ref causes the validation error to go away.

### Reproduction Steps

[Sharplab link](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoIgBgAIiyA6AYQgBsOYwMBLCHgDOAbmp1GLACJ8AhgHM8EIfzBC2EACYwAgnlkcAnkL6jxDJswBK+fgFsYGuwAc+3KAGUYUAG58wMGZU4gDM9LAAZvQquLz0AEJ8+lCGVjCy2lAAPAAq8YYYMADyUJkAfPQA7gAW3jD0eQXFpd70IJJhAN4AvtSh9LLAMbJxpA2GzjAAClAQAUJC0Lll1J3U9BuMYYPDoyj0aRm5+YUl5QAUkQlJsimHmcdNZ94VsBneAJTrmz81dQ0nZqZNodMRUXrBKhCdLcTSMEj0ACSeAwMzmgUWUBBOQm01m80xWSSGBWVDWVB+RDCEB83igfG0jH290epxaUDKlxgUUSyVS6QejTZ5XCAs+3w25J+lLIAE5zgASABE9wG9E6GFxEAi5yFQM+zAAcrIHN16MSAIRKj5gn4QiHiEhdCXwhFS6UbHy3UXvLEAXnoeBglWufPu3iyOigUFkhk5NpdPyDIeRqPxGOg5w+1gFXKib0yCYpm3tQA==)
```cs
public ref struct BinaryReader<TByteOrder> where TByteOrder : IEnumerable {}

public abstract class TypeProcessor<T>
{
    public abstract void Read<TByteOrder>(ref BinaryReader<TByteOrder> reader)
        where TByteOrder : IEnumerable;
}

sealed class IntProcessor : TypeProcessor<int>
{
    public override void Read<TByteOrder>(ref BinaryReader<TByteOrder> reader)
    {
        Console.WriteLine($"Read a {typeof(TByteOrder).Name} int!");
    }
}

public static class Program {
    public static void Main() {
        var reader = new BinaryReader<Array>();
        // System.Security.VerificationException: Method SharpLab.Runtime.Internal.Flow.ReportRefValue: type argument 'BinaryReader`1[TByteOrder]' violates the constraint of type parameter 'T'.
        new IntProcessor().Read(ref reader);
    }
}
```

### Expected behavior

Should not throw validation errors.

### Actual behavior

Throws validation errors.

### Configuration

.NET 8.0.0

**Comment by KeterSCP** [comment]
The exception is thrown from Sharplab validation, not runtime. You probably should report it to the sharplab repo instead

**Comment by mikernet** [comment]
Apologies, my mistake. I thought IL verify was also tripping up because of this but it I think that is a separate issue. I will close for now.
