### ISSUE TITLE
NativeAOT Convert C# Struct to C++ Pointer Failed

### ISSUE THREAD

**Issue by dongfengxin** [dotnet/runtime#98922]
### Description

NativeAOT Convert C# Struct to C++ Pointer Failed

There is a C# Struct like this :

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    internal struct OPEN_SETTING_EXT
    {
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
        public SERVER_INFO[] siServer;

        public uint nServerNum;

        public DataMsgHandler pfnMsgHandler;

        public SystemMsgHandler pfnSysMsgNotify;

        public IntPtr szMarkets;

        public IntPtr szResvMarkets;

        public IntPtr szSubScriptions;

        public uint nTypeFlags;

        public int nTime;

        public uint nConnectionID;
    }

and will be Convert to a C++ Intptr with the fllowing method:

        [RequiresDynamicCode("Calls System.Runtime.InteropServices.Marshal.StructureToPtr(Object, nint, Boolean)")]
        public static IntPtr CopyStructToGlobalMem(object obj, Type typeInfo)
        {
            IntPtr intPtr = Marshal.AllocHGlobal(Marshal.SizeOf(typeInfo));
            Marshal.StructureToPtr(obj, intPtr, fDeleteOld: false);
            return intPtr;
        }

last will be used like this:

                Console.WriteLine("Ready To Run CopyStructToGlobalMem");
                m_pSettings = LibWrapHelper.CopyStructToGlobalMem(m_openSetting_ext, typeof(TDF_OPEN_SETTING_EXT));
                Console.WriteLine("CopyStructToGlobalMem Runed");

### Reproduction Steps

The Above function runs well in normal release way, but  didnot runs well in NativeAOT.

### Expected behavior

![image](https://github.com/dotnet/runtime/assets/17286415/778d6357-d10f-4f48-a659-dc06f3ad52e9)

### Actual behavior

![image](https://github.com/dotnet/runtime/assets/17286415/f64954e1-7b42-4937-9ea7-4ff750250d3c)
The Second line returns the failed message.

**Comment by huoyaoyuan** [comment]
As the `RequiresDynamicCode` message says, `StructureToPtr(Object)` is unfriendly with AOT compiler. `StructureToPtr<T>` is the alternative.

Can you change the function to generic and see if it solves the problem?

```csharp
    public static IntPtr CopyStructToGlobalMem<T>(T obj)
    {
        IntPtr intPtr = Marshal.AllocHGlobal(Marshal.SizeOf<T>());
        Marshal.StructureToPtr(obj, intPtr, fDeleteOld: false);
        return intPtr;
    }
```

In addition, please do not ignore AOT/trim warnings during NativeAOT publishing. Methods with `RequiresDynamicCode` are likely to break with AOT.

**Comment by dongfengxin** [comment]
> As the `RequiresDynamicCode` message says, `StructureToPtr(Object)` is unfriendly with AOT compiler. `StructureToPtr<T>` is the alternative.
> 
> Can you change the function to generic and see if it solves the problem?
> 
> ```cs
>     public static IntPtr CopyStructToGlobalMem<T>(T obj)
>     {
>         IntPtr intPtr = Marshal.AllocHGlobal(Marshal.SizeOf<T>());
>         Marshal.StructureToPtr(obj, intPtr, fDeleteOld: false);
>         return intPtr;
>     }
> ```
> 
> In addition, please do not ignore AOT/trim warnings during NativeAOT publishing. Methods with `RequiresDynamicCode` are likely to break with AOT.

Thank you so much! It Works Well.

**Comment by dongfengxin** [comment]
> As the `RequiresDynamicCode` message says, `StructureToPtr(Object)` is unfriendly with AOT compiler. `StructureToPtr<T>` is the alternative.
> 
> Can you change the function to generic and see if it solves the problem?
> 
> ```cs
>     public static IntPtr CopyStructToGlobalMem<T>(T obj)
>     {
>         IntPtr intPtr = Marshal.AllocHGlobal(Marshal.SizeOf<T>());
>         Marshal.StructureToPtr(obj, intPtr, fDeleteOld: false);
>         return intPtr;
>     }
> ```
> 
> In addition, please do not ignore AOT/trim warnings during NativeAOT publishing. Methods with `RequiresDynamicCode` are likely to break with AOT.

And there a a lot of waring, further more , I with little experience of nativeaot update, sometimes, did not no the solution action with the warnings。 lot of knowledge to learn with nativeaot.
