### ISSUE TITLE
Two build related questions

### ISSUE THREAD

**Issue by ghost** [dotnet/runtime#9894]
1. `one-less dependency`: is dependency on gettext hard? can it be replaced by libicu? currently both libs are in use.
2. `more compilers to build with please`: is there any future plan to support GCC compiler to build CoreCLR? main `build.sh` is too strict to let go unknown operating systems based on `uname` and clang is a requirement.

Many (>90%) Unix-like systems are GCC-first and clang / llvm come from package managers. As an example, i am trying to build CoreCLR on SmartOS and Clang5 is broken (libstdc++ location in clang is hardcoded and package manager of Solaris-like OS need to keep the patches up to date). It was the same case with SmartOS few years ago: https://github.com/dotnet/coreclr/issues/803#issuecomment-164936893. The current way is to take the pkgsrc zone image, create 2017Q4 sandbox, and compile clang/llvm 6, then clone CoreCLR. Using SmartOS hypervisor in virtual machine then creating a sandbox in a zone that run on top of that hypervisor is too complex.

Technically when CMake is already in place, GCC 4.8+ support can be added without disturbing the current setup.

**Comment by stephentoub** [comment]
The original poster of this question deleted their account and is now a "ghost", so I'm going to close this issue.  Thanks.
