### ISSUE TITLE
Using EnableConfigurationBindingGenerator and Uri property wrong binding when null

### ISSUE THREAD

**Issue by bdovaz** [dotnet/runtime#98943]
### Description

Previously if you had a property of type Uri and in the json file the value is set to null, at the time of making the binding it will also have null.

This is not the case with `<EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>`.

In that case it is not null.

### Reproduction Steps

Setting `EnableConfigurationBindingGenerator` to `true` the log shows that it is not null but if set to `false` it is.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
```

```json
{
  "Options": {
    "Uri": null
  }
}
```

```csharp
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

IConfiguration configuration = new ConfigurationBuilder()
    .AddJsonFile("appsettings.json")
    .Build();

IServiceCollection services = new ServiceCollection();
services.Configure<CustomOptions>(configuration.GetSection("Options"));

IServiceProvider serviceProvider = services.BuildServiceProvider();

Uri? uri = serviceProvider.GetRequiredService<IOptions<CustomOptions>>().Value.Uri;

Console.WriteLine($"Uri is null: {uri != null}");

class CustomOptions
{
    public Uri? Uri { get; set; }
}
```

### Expected behavior

It must be null.

### Actual behavior

It is not null.

### Regression?

Yes because I understand that regardless of whether you use `EnableConfigurationBindingGenerator` or not, the binding behavior should be the same.

**Comment by ericstj** [comment]
I don't observe a repro where this ever returns `true`.  I tried your repro and removed `EnableConfigurationBindingGenerator` and it still prints `Uri is null: False`.  I then rolled it back to `6.0.0` versions of the packages and `net6.0` and it still prints `Uri is null: False`.

I don't think this is a behavior difference.  I think this has always been this way, and it's due to https://github.com/dotnet/runtime/issues/36510
