### ISSUE TITLE
Queue<T>.Dequeue throws NullReferenceException in .NET 8 Release build

### ISSUE THREAD

**Issue by TahirAhmadov** [dotnet/runtime#98961]
### Description

Calling `Queue<T>.Dequeue()` throws NRE in .NET 8 in Release build (ReadyToRun is **off**). This is running on Win Server 2019 - I attached with remote debugger to troubleshoot. 
If you see, R9 register is zero. However, the `Queue<T>` instance is in a correct state. No other threads are touching any of these instances (all this exists in the context of a web request without any sharing or static stuff).

### Reproduction Steps

![image](https://github.com/dotnet/runtime/assets/16783987/5d76997f-a9ac-489f-bdb9-1cdc42325431)

![image](https://github.com/dotnet/runtime/assets/16783987/701cb104-5547-4d47-b100-f2676889c6e1)

![image](https://github.com/dotnet/runtime/assets/16783987/2e4c1286-00d3-4048-87e4-a56991dad92f)

![image](https://github.com/dotnet/runtime/assets/16783987/618d6136-d07a-43ac-a800-582fa6489c45)

### Expected behavior

NRE

### Actual behavior

Success

### Regression?

This worked in .NET 6.

### Known Workarounds

Works correctly in debug mode, also sometimes works in release mode.

### Configuration

- .NET 8.0.2
- Windows: ![image](https://github.com/dotnet/runtime/assets/16783987/6086563a-d8b4-4fcc-be5c-97a44ab319a0)
- x64
- Not tested on other platforms
- N/A

### Other information

Together with the [ReadyToRun](https://github.com/dotnet/runtime/issues/96225) issue, unfortunately it looks like .NET 8 is not ready for production. Let this be a warning for those who are considering an upgrade to .NET 8 - you should wait for a few more updates so that all these bugs are fixed before making the switch.

**Comment by TahirAhmadov** [comment]
@MichalPetryka that was the first thing I checked - no other threads accessing this instance or even executing the same code at the time of this exception. I purposefully ensured that only one web request was made to the server to diagnose the problem.

**Comment by TahirAhmadov** [comment]
The strange part is that it when it works, it always works for the duration of the process's uptime. Other process startups (in this case w3wp.exe with the website loaded using the standard .NET Core hosting mechanism) it doesn't work regardless of how many times I try. There is some corruption going on, but it's literally the same code in both cases. That's why I have a feeling this is a runtime issue.

**Comment by TahirAhmadov** [comment]
Just tried running release build on my laptop both with and without debugger and cannot reproduce the issue. So it may be something to do with the WinSrv2019? It's a VMware 6.5 VM.

**Comment by eiriktsarpalis** [comment]
It wouldn't be possible for us to help without some form of reproduction. Creating a minimal repro should help isolate the problem and let us fix the issue at hand, if it exists.
