### ISSUE TITLE
Internal CLR error in System.Reflection.FieldAccessor.GetValue

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#98998]
https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-98947-merge-04b2eb6f6b03445584/System.Net.Sockets.Tests/1/console.f8a1785a.log?helixlogtype=result

```
      Condition(s) not met: "IsNotWindowsNanoNorServerCore"
Fatal error. Internal CLR error. (0x80131506)
   at System.Reflection.FieldAccessor.GetValue(System.Object)
   at System.ValueType.Equals(System.Object)
   at System.Net.Sockets.SocketAsyncEventArgs.FreePinHandles()
   at System.Net.Sockets.SocketAsyncEventArgs.FreeInternals()
   at System.Net.Sockets.SocketAsyncEventArgs.Finalize()
----- end Tue 02/27/2024  7:03:02.56 ----- exit code -1073741819 ----------------------------------------------------------
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=580520
Build error leg or test failing: System.Net.Sockets.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/98947

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "at System.Reflection.FieldAccessor.GetValue(System.Object)",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=580520
**Error message validated:** `[at System.Reflection.FieldAccessor.GetValue(System.Object)`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 2/27/2024 5:07:23 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[589245](https://dev.azure.com/dnceng-public/public/_build/results?buildId=589245)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=589245&view=ms.vss-test-web.build-test-results-tab&runId=14219424&resultId=217521)|dotnet/runtime#98218|
|[588964](https://dev.azure.com/dnceng-public/public/_build/results?buildId=588964)|dotnet/runtime|[System.Net.Http.WinHttpHandler.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=588964&view=ms.vss-test-web.build-test-results-tab&runId=14212906&resultId=218388)|dotnet/runtime#99185|
|[2392255](https://dev.azure.com/dnceng/internal/_build/results?buildId=2392255)|dotnet-runtime|[release.Partition24.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2392255&view=ms.vss-test-web.build-test-results-tab&runId=53166629&resultId=100059)||
|[586363](https://dev.azure.com/dnceng-public/public/_build/results?buildId=586363)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=586363&view=ms.vss-test-web.build-test-results-tab&runId=14122456&resultId=217338)|dotnet/runtime#99185|
|[584716](https://dev.azure.com/dnceng-public/public/_build/results?buildId=584716)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=584716&view=ms.vss-test-web.build-test-results-tab&runId=14074010&resultId=217502)|dotnet/runtime#99011|
|[580520](https://dev.azure.com/dnceng-public/public/_build/results?buildId=580520)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=580520&view=ms.vss-test-web.build-test-results-tab&runId=13943346&resultId=216690)|dotnet/runtime#98947|
|[579650](https://dev.azure.com/dnceng-public/public/_build/results?buildId=579650)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=579650&view=ms.vss-test-web.build-test-results-tab&runId=13917166&resultId=217269)|dotnet/runtime#98877|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|2|5|7|

**Comment by jkotas** [comment]
@steveharter Looks like a GC hole in the new `FieldAccessor` implementation

**Comment by MihaZupan** [comment]
Should we consider reverting d3ebc972c6c878a22201629833683de544e8f532 for the time being?

Running http tests locally consistently crashes on most runs for me, while being stable 1 commit earlier.
```
dotnet build .\src\libraries\System.Net.Http\tests\FunctionalTests\ /t:Test /p:OuterLoop=true
```

cc: @dotnet/ncl in case others run into this one

**Comment by AndyAyersMS** [comment]
Ran into this running some TE Benchmarks:
```
[application] The following scenarios were enabled:
[application]   MvcDbFortunesEf -> /mvc/fortunes/ef
[application]
[application] Database: PostgreSql
[application] ConnectionString: Server=10.0.0.105;Database=hello_world;User Id=benchmarkdbuser;Password=benchmarkdbpass;Maximum Pool Size=18;Enlist=false;Max Auto Prepare=4;Multiplexing=true;Write Coalescing Buffer Threshold Bytes=1000
[application] Using server Kestrel
[application] Server GC is currently ENABLED
[application] Using Sockets with 12 threads
[application] Hosting environment: Production
[application] Content root path: C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-8540\qtefmswt.qvg\src\Benchmarks\published
[application] Now listening on: https://10.0.0.110:5000
[application] Application started. Press Ctrl+C to shut down.
[11:36:17.850] 'application' is running ... http://asp-perf-win:5001/jobs/101/output
[11:36:20.569] Starting job 'load' ...
[11:36:20.579] Submitted job: http://asp-perf-db:5001/jobs/48
[11:36:21.620] 'load' has been selected by the server ...
[11:36:21.638] 'load' is now building ... http://asp-perf-db:5001/jobs/48/buildlog
[11:36:24.663] 'load' is running ... http://asp-perf-db:5001/jobs/48/output
[application] [STDERR] Fatal error. Internal CLR error. (0x80131506)
[application] [STDERR]    at System.Reflection.FieldAccessor.GetValue(System.Object)
[application] [STDERR]    at System.Reflection.RtFieldInfo.GetValue(System.Object)
[application] [STDERR]    at System.ValueType.Equals(System.Object)
```

**Comment by AndyAyersMS** [comment]
@sebastienros fyi, in case you see failures.

Seems like we should revert the change?
