### ISSUE TITLE
Possible memory leak with Native Host API

### ISSUE THREAD

**Issue by jeffersoncarpenter-tru** [dotnet/runtime#98995]
### Describe the bug
A program based on [this example](https://github.com/dotnet/samples/tree/main/core/hosting/src/NativeHost) that initializes, uses, and closes hostfxr contexts in a loop, allocates more and more memory, and does not free it.  Letting the program run, takes up >1GB of memory in a matter of minutes.

### To Reproduce
To reproduce, call the Dotnet Native Hosting API using the following files: [Program.cs](https://gist.github.com/jeffersoncarpenter-tru/7d959fe22cbdf93b088fb7a7d0867048) and [main.cpp](https://gist.github.com/jeffersoncarpenter-tru/0097d782958f356317b244428570f8e2)

My exact steps:

1. Create a dotnet project with `dotnet new console -o MyApp -f net7.0`
2. In the generated csproj file, remove the line `<OutputType>Exe</OutputType>` and replace it with

```
<OutputType>Library</OutputType>
<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
```

3. Replace the generated `Program.cs` file with the one provided above.
4. Build the dotnet application with `dotnet publish`
5. Compile and execute the C++ program provided above with

```
g++ -L"$DOTNET_LIB" -isystem "$DOTNET_LIB" -lnethost -ldl -pthread main.cpp -o main
LD_LIBRARY_PATH=$DOTNET_LIB ./main
```

where `$DOTNET_LIB` points to the `dotnet/.../native` directory with the native hosting header and so files, and `$DOTNET_ROOT` points to the dotnet SDK root directory.

### Exceptions (if any)
No exceptions.  Normally I would debug memory leaks using Valgrind, but when I run the program under Valgrind I get `GC heap initialization failed with error 0x8007000E` and the program exits.

### Further technical details
My `dotnet --info` output is

```
$ dotnet --info
.NET SDK:
 Version:   7.0.401
 Commit:    eb26aacfec

Runtime Environment:
 OS Name:     rhel
 OS Version:  7
 OS Platform: Linux
 RID:         rhel.7-x64
 Base Path:   /data00/development/dotnet/dotnet-sdk/sdk/7.0.401/

Host:
  Version:      7.0.11
  Architecture: x64
  Commit:       ecb34f85ec

.NET SDKs installed:
  7.0.401 [/data00/development/dotnet/dotnet-sdk/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.11 [/data00/development/dotnet/dotnet-sdk/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.11 [/data00/development/dotnet/dotnet-sdk/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

I'd like to know if the code I posted properly frees everything that it needs to.

Edit: Tried on SDK version 8, the program still leaks memory.

**Comment by jeffersoncarpenter-tru** [comment]
I think we would be open to changing our marshalling pattern as well (using different attributes, etc.).  We would just like to be able to pass data back and forth between C++ and C# without leaking memory.

**Comment by jeffersoncarpenter-tru** [comment]
Okay, I've found out a few things.  I had thought calling the `hostfxr_close_fn` function would clean up all the data from our calls from C++ to C#, including any memory that the marshaller allocated.  That idea was from [this example](https://github.com/dotnet/samples/blob/4ae0f852f7adce078979110bf8aadf557aaf0b7c/core/hosting/src/NativeHost/nativehost.cpp#L191-L257), where it looks like the hostfxr context must exist for the lifetime of the calls into to the hosted C# code.  In that example, `close_fptr` is called after the C# program is finished executing.  However, the [Library example](https://github.com/dotnet/samples/blob/4ae0f852f7adce078979110bf8aadf557aaf0b7c/core/hosting/src/NativeHost/nativehost.cpp#L98-L189) in that same file calls `close_fptr` earlier, and this actual behavior is also described well in Step 2 of the [Native hosting tutorial](https://learn.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting).

So we should load our assembly and call `hostfxr_close` earlier in our code - indeed outside of the for loop.

That raises the question, how do we free the memory allocated by the marshaller?  It allocates an array and places it into a `ref Bar[]` on the C# side, which is a `Bar**` on the C++ side.  Is making a call to a function obtained through `load_assembly_and_get_function_ptr_fn` defined as something that may allocate resources?  If so, there ought to be a call that frees the resources.  If we allocate resources in our code, we should free them in our code.  At the suggestion of a coworker, I tried adding a `delete` statement to the C++ code to delete the `bars` array returned from the marshaller just to see if it reduced the memory leak, and it did.  However, I don't think this is the right solution because (1) we did not call `new`, (2) we would have to write code to delete all sub-objects as well, including any strings inside of our "Bar" struct, and (3) I don't have documentation that `delete` can be used to free resources allocated by the Marshaller, so this may change or break in the future.

It looks like we can marshal our variable-length `Bars` array from C# to C++ with a few steps, which I will summarize:
* Turn the `Bar[]` array from a function argument into a static class member.  Delete the `ref Bar[]` and `Bar**` function arguments.  In the `Test` function in C#, assign this static class member instead of writing to the `ref Bar[]` argument.  Place the length of the array into the `ref int` as before.
* Add a "copy data" function that takes an `IntPtr` on the C# side and a `Bar*` on the C++ side.  In C++, allocate storage for the array of `Bar` objects of the length given by the call to `Test`, and pass that storage into this function.  In C#, call `Marshal.StructureToPtr` in a loop to write the `Bar` values into this array.
* Add a "cleanup" function that takes an `IntPtr` on the C# side and a `Bar*` on the C++ side.  Call this function in C++ after processing the array returned from C#.  In C#, call `Marshal.DestroyStructure` in a loop to delete all of the `Bar` objects (in particular, any of their sub-objects such as `string`s).
* After calling "cleanup", free the storage for the `Bar` array in C++.

This seems to work without leaking memory.  However, I'm still looking for the best and simplest solution.  I would appreciate any advice on returning variable-length data from C# to C++ using the Native Host APIs.  Thanks!

**Comment by jkotas** [comment]
> how do we free the memory allocated by the marshaller? 

Memory allocated by the marshaller can be freed in native code using `free` from C runtime on Unix, and `CoTaskMemFree` on Window. This applies to memory allocated for marshalled strings as well.

> we can marshal our variable-length Bars array from C# to C++ with a few steps, which I will summarize:

This will work too, but it comes with extra overhead.

**Comment by jeffersoncarpenter-tru** [comment]
> Memory allocated by the marshaller can be freed in native code using `free` from C runtime on Unix, and `CoTaskMemFree` on Window. This applies to memory allocated for marshalled strings as well.

Ahh, that's interesting!  Admittedly I find it surprising that I have to call `free` when I did not call `malloc`.  There are C standard library functions that also work like this such as `strdup`, but the man page for that says it allocates memory using `malloc` and the programmer can free it using `free`.  Thanks!

**Comment by jeffersoncarpenter-tru** [comment]
@jkotas We have implemented those changes (calling `free` on Unix and `CoTaskMemFree` on Windows) and are now running in constant memory.  I'll go ahead and close this issue.  Thanks!
