### ISSUE TITLE
Enable the auto-merge bot

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#99]
Seems the auto-merge bot isn't triggering for dotnet/runtime: https://github.com/dotnet/runtime/pull/91#issuecomment-555075096. Probably a config switch somewhere?

cc @Anipik @danmosemsft

**Comment by ViktorHofer** [comment]
@Anipik kindly asking for a status. The last time I tried the auto-merge bot, it posted the expected message but didn't merge the PR. Thanks.

**Comment by Anipik** [comment]
fabrics team deployed our requirement if auto-merging the pr when the runtime check is passed. This will resolve our issues. I updated the tasks today.

**Comment by Anipik** [comment]
Auto-merge wont work on documentation prs as they dont run the runtime check.
