### ISSUE TITLE
[.NET 8] [android] case where Mono debugger doesn't "break" correctly on unhandled exceptions

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/runtime#99007]
### Description

Certain runtime exceptions in a .NET MAUI application do not "break" at the appropriate location when debugging on Android.

This can happen if you have subtly invalid XAML, such that you get no build error and the error is presented at runtime instead.

### Reproduction Steps

See instructions on the sample here: https://github.com/jonathanpeppers/MonoDebuggerRepro

### Expected behavior

The Mono debugger breaks in this location:

![workaround](https://github.com/dotnet/runtime/assets/840039/9bed8059-e062-432f-bdf3-2a4688c04ecb)

### Actual behavior

The Mono debugger breaks here instead:

![problem](https://github.com/dotnet/runtime/assets/840039/8bc1a033-dc5c-41cc-a5b1-223ef3624fec)

### Regression?

No, I don't think this is a regression

### Known Workarounds

For some reason, changing the app to use different XAML in `AppShell.xaml`:

```xaml
<!-- Change this -->
<ShellContent
    Title="Home"
    ContentTemplate="{DataTemplate local:MainPage}" />

<!-- To this -->
<ShellContent Title="Home">
    <local:MainPage />
</ShellContent>
```

It works as expected; note that the workaround no longer has `Activator.CreateInstance()` in
the call stack.

### Configuration

.NET 8.0.200 SDK, 8.0.2 runtime

**Comment by thaystg** [comment]
I enabled all the exceptions:
![image](https://github.com/user-attachments/assets/79d087a1-f84b-49f2-a7c2-c2183c451dd4)

I have just tested and it's working for me both scenarios:

AppShell.xaml:
```
<?xml version="1.0" encoding="UTF-8" ?>
<Shell
    x:Class="MonoDebuggerRepro.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:MonoDebuggerRepro"
    Shell.FlyoutBehavior="Disabled"
    Title="MonoDebuggerRepro">

    <ShellContent
        Title="Home"
        ContentTemplate="{DataTemplate local:MainPage}"
        Route="MainPage" />

    <!-- Uncomment for workaround -->
    <!--<ShellContent Title="Home">
        <local:MainPage />
    </ShellContent>-->

</Shell>

```

![image](https://github.com/user-attachments/assets/290c9cc4-4ef4-4846-9b8c-622329bf1b19)

**Comment by jonathanpeppers** [comment]
Still happens for me:

![image](https://github.com/user-attachments/assets/42211351-35d6-48c6-9532-4476ca9acdd3)

I have:
![image](https://github.com/user-attachments/assets/9ad9297f-d6fc-41f6-bd0e-682b0573e856)

```
> dotnet --version
8.0.303
> dotnet workload list

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
macos                      14.2.8053/8.0.100      VS 17.10.35027.167
maccatalyst                17.2.8053/8.0.100      VS 17.10.35027.167
ios                        17.2.8053/8.0.100      VS 17.10.35027.167
maui-windows               8.0.61/8.0.100         VS 17.10.35027.167
android                    34.0.95/8.0.100        VS 17.10.35027.167
```

The only thing, maybe it's because I'm debugging on arm64, it is a Pixel 7 device.

**Comment by jonathanpeppers** [comment]
I think I have the 8.0.7 runtime if that helps.

**Comment by thaystg** [comment]
Can you test in a emulator?
