### ISSUE TITLE
Verify performance of available algorithms for implementing SSE/SSE2 HW helper intrinsics

### ISSUE THREAD

**Issue by 4creators** [dotnet/runtime#9901]
Native compilers like MSVC, Clang and GCC tend to use different algorithms (sequences of SIMD instructions) to implement helper intrinsics which are equivalent to `SetAllVector128`, `SetVector128` and similar. We have implemented this intrinsics using some of this patterns, however, we do not know what would be performance differences between different algorithms running on .NET Core.

To make sound decisions we need to profile different algorithms and set some performance tests for HW intrinsics to make continuous observations of performance impact of ongoing implementation work.

Related discussion https://github.com/dotnet/coreclr/pull/16817#discussion_r173206209

category:cq
theme:intrinsics
skill-level:expert
cost:large

**Comment by CarolEidt** [comment]
Closing this issue in favor of #9908
