### ISSUE TITLE
Incorrect value returned by `Environment.ProcessorCount` when running on GCP Cloud Run resulting in memory problems.

### ISSUE THREAD

**Issue by mnebes** [dotnet/runtime#99046]
### Description

We noticed a strange behavior of our containers deployed to Google Cloud Platform's Cloud Run since upgrading to .NET 8. We were alerted that the containers are being terminated because they used too much memory. We usually allocate 1 CPU and 512MB/1GB Memory to all our containers and it was always enough. After ruling out memory leaks in our code we started logging GC stats and noticed that `Environment.ProcessorCount` returned 2 even though the container only had 1 CPU available.

That in turn seems to have caused the GC to use Server Mode, whereas according to the [documentation](https://github.com/dotnet/docs/blob/main/docs/standard/garbage-collection/workstation-server-gc.md), a single-CPU machine should always use Workstation GC.

We managed to crrect this behavior by setting the `DOTNET_PROCESSOR_COUNT` environment variable.

I'm not sure if anything changed to the way the processor count is being reported in .NET 8, but to my knowledg this behavior was different in prior versions.

See the related issue in the google-cloud-dotnet repo: https://github.com/googleapis/google-cloud-dotnet/issues/11404

### Reproduction Steps

1. Follow the quickstart steps described in the official Cloud Run docs: https://cloud.google.com/run/docs/quickstarts/build-and-deploy/deploy-dotnet-service
2. Add the following line in `Program.cs`: 
```
app.Logger.Log(LogLevel.Information, "Processor count: {ProcessorCount}", Environment.ProcessorCount);
```
3. Deploy to Cloud Run.
4. Observe the logs.

### Expected behavior

`Environment.ProcessorCount` should return `1` on a single CPU container and in turn set the Garbage Collector to Workstation mode.

### Actual behavior

`Environment.ProcessorCount` returns `2` on a single-CPU container leading to misconfigured GC.

### Regression?

We started experiencing this issue upon migration from .NET 7 to .NET 8. 

### Known Workarounds

Set `DOTNET_PROCESSOR_COUNT` to 1 or force Workstation GC explicitly in `.csproj/.fsproj`.

### Configuration

Using .NET8 running in the official Asp NET Core 8.0 docker image. Architecture is x64. Image is run by Google Cloud Platform Cloud Run.

**Comment by mangod9** [comment]
Thanks for reporting this issue. Are you noticing this only when deploying to GCP, or do you notice the same behavior on local container environments?

**Comment by EgorBo** [comment]
Can you print what `lscpu` command outputs?

**Comment by AustinWise** [comment]
I'm not the OP but I was curious and looked into the issue.

The first thing I check was if the [execution environment)[https://cloud.google.com/run/docs/about-execution-environments] makes a difference. When running in second generation execution environment, `Environment.ProcessorCount` returns 1 when the number of CPUs is set to 1 in Cloud Run. So that is a workaround.

The reason that `Environment.ProcessorCount` is wrong in the first generation execution environment is it fails to detect the version of cgroups. Specifically in this switch statement:

https://github.com/dotnet/runtime/blob/6ebba8631a2617779162042786c015559dbbde0a/src/coreclr/pal/src/misc/cgroup.cpp#L97C2-L103C10

The value of `f_type` is `SYSFS_MAGIC` ( 0x62656572 ). If we assume that means "gcroups version 1", the CPU limit is correctly calculated. Here is my fix from my test program:

https://github.com/AustinWise/TestCpuCount/commit/2b36610e6beea973fe8542d3c459864d9ded9222

**Comment by martincostello** [comment]
Looks like that and a few other magic values that aren't in the CLR code are in this doc: https://www.kernel.org/doc/Documentation/ABI/testing/ima_policy

Whether they all _should_ be, I don't know.

**Comment by mnebes** [comment]
Thanks everyone for having a look!

> Thanks for reporting this issue. Are you noticing this only when deploying to GCP, or do you notice the same behavior on local container environments? @mangod9 

Locally (M2 Pro Mac with Colima/QEMU set up to have 1 CPU available) the correct value of `1` is returned.

> Can you print what `lscpu` command outputs? @EgorBo 

That's going to be a bit tricky as I don't know any straightforward way to ssh into a running container on Cloud Run. I'll see if I can figure something out.

Thanks @AustinWise for having a deeper look! I didn't think to check the 2nd gen environment as we rarely use those.

**Comment by mnebes** [comment]
@EgorBo I modified my repro code to spawn a shell process and run the `lscpu` command. Here's the output:

```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Address sizes:       46 bits physical, 48 bits virtual
Byte Order:          Little Endian
CPU(s):              2
On-line CPU(s) list: 0,1
Vendor ID:           AuthenticAMD
Model name:          unknown
CPU family:          175
Model:               1
Thread(s) per core:  0
Core(s) per socket:  0
Socket(s):           0
Stepping:            unknown
BogoMIPS:            3249.34
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clwb sha_ni xsaveopt xsavec xgetbv1 xsaves umip pku vaes vpclmulqdq rdpid
Virtualization:      AMD-V
```

it does look like the container thinks it has 2 CPUs, but I'm really not an expert in how to interpret this output 🙂

**Comment by tannergooding** [comment]
Might this be hyperthreading? You are allocated one physical core, which maps to 2 logical cores.

**Comment by EgorBo** [comment]
> Might this be hyperthreading? You are allocated one physical core, which maps to 2 logical cores.

in case of HP, `lscpu` usually shows `Thread(s) per core:  2`

**Comment by mangod9** [comment]
@mnebes might be worthwhile following up with GCP about how their infra is configured and whether this is expected. As a workaround you can always force your app to use WKS GC if that works best in your scenario.

**Comment by danmoseley** [comment]
Is this normal output in any circumstance?
`Thread(s) per core:  0`

**Comment by mnebes** [comment]
> @mnebes might be worthwhile following up with GCP about how their infra is configured and whether this is expected. As a workaround you can always force your app to use WKS GC if that works best in your scenario.

@mangod9 see https://github.com/googleapis/google-cloud-dotnet/issues/11404#issuecomment-1972690591

Even if Cloud Run reports these things in an unusual way it still wouldn't explain why we didn't have this issue before .NET 8, though.

As far as workarounds go, we're using the `DOTNET_PROCESSOR_COUNT` one right now as it was the easiest to deploy via terraform and things look fine atm.

**Comment by mangod9** [comment]
Thanks @AustinWise for your fix, it is now merged.

**Comment by mnebes** [comment]
Thanks @AustinWise and everyone involved!

@mangod9 will this fix be coming to some future release of .NET 8 or only in 9?

**Comment by AustinWise** [comment]
It will be in .NET 9. I have opened a PR to propose backporting the fix to .NET: #99563

**Comment by mangod9** [comment]
we would need a good case to back port. Assume the workaround is easy enough?

**Comment by mnebes** [comment]
True, the workarounds are straightforward, so for us it's fine. I'm more wondering if that isn't a surprise situation that other teams that are using .NET on Cloud Run will be hit by as well.

**Comment by glb-cblin** [comment]
I confirm 👍 

Yes, the workaround is easy to put in place

However, finding that the workaround is needed is very hard (i.e you have OOM errors, so finding that you need to change the CPU count is not the most easy to find and to understand...)
