### ISSUE TITLE
Microsoft.VisualBasic.Collection has different interfaces on ref assembly and implementation assembly.

### ISSUE THREAD

**Issue by jtschuster** [dotnet/runtime#99088]
`Microsoft.VisualBasic.Collection` implements `IEnumerable` directly in the ref assembly, but not in the implementation assembly. It relies on the implementation on `ICollection` to provide the implementation of IEnumerable.

**Comment by stephentoub** [comment]
Why is that a problem?

**Comment by jtschuster** [comment]
> Why is that a problem?

I should have mentioned in the comment, I'm not sure if this is actually a problem or not. I just noticed this when investigating a trimmer issue and it seemed odd to have this difference so I thought it would be worth bringing up.

**Comment by stephentoub** [comment]
Got it. It's not a problem. I believe there are many cases like this. The refs generally enumerate all the interfaces explicitly, whereas the implementations typically don't.
