### ISSUE TITLE
.NET 8 is not as lazy as .NET 7 when checking JSON-serializability

### ISSUE THREAD

**Issue by rummelsworth** [dotnet/runtime#99089]
### Description

Something seems to have changed in .NET 8 vs .NET 7, where JsonSerializer acts earlier (possibly correctly so?) to validate types for JSON serializability.

This is only my impression of what's happening:
- In .NET 7, JsonSerializer seems to only check serializability for types whose objects it actually encounters in the payload.
- In .NET 8, JsonSerializer seems to immediately check serializability of any type that it might possibly encounter in the payload.

### Reproduction Steps

Run the following code, targeting `net7.0` and then `net8.0`:

```csharp
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Xml.Serialization;

var options = new JsonSerializerOptions
{
    //Converters = { new FooConverter() },
    PropertyNameCaseInsensitive = true,
    WriteIndented = true,
};

var user = new User();
var userWithFoo = new User { foo = new() };
var userJson = JsonSerializer.Serialize(user, options); // fine for net7.0, exception for net8.0
Console.WriteLine(userJson);
userJson = JsonSerializer.Serialize(userWithFoo, options); // exception for both net7.0 and net8.0
Console.WriteLine(userJson);

// ---

public class User
{
    public int Id { get; set; }

    public Foo foo { get; set; }
}

public class Foo
{
    public int bar { get; set; }

    [XmlIgnore]
    public bool Bar { get => bar != 0; set => bar = value ? 1 : 0; }
}

public class FooConverter : JsonConverter<Foo>
{
    private readonly XmlSerializer serializer = new(typeof(Foo));

    public override Foo? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var xml = reader.GetString();
        var result = (Foo)serializer.Deserialize(new StringReader(xml));
        return result;
    }

    public override void Write(Utf8JsonWriter writer, Foo value, JsonSerializerOptions options)
    {
        var xmlWriter = new StringWriter();
        serializer.Serialize(xmlWriter, value);
        var xml = xmlWriter.ToString();
        writer.WriteStringValue(xml);
    }
}
```

### Expected behavior

An exception occurs when serializing `userWithFoo`, not when serializing `user`. (`net7.0` behavior)

### Actual behavior

An exception occurs when serializing either `user` or `userWithFoo`. (`net8.0` behavior)

### Regression?

Possibly? It seems unlikely that the `net7.0` behavior is intended over the `net8.0` behavior. But figuring all this out in my real codebase did lose me half a day of forward progress at work. I wish I had seen it when I read the .NET 8 "what's new" post for `JsonSerializer`. I don't think it was there, unless there was a link to some list of important resolved issues that I missed.

### Known Workarounds

I annotated the "real" `Foo` type with `JsonConverterAttribute` pointing to its converter type for all the places in my real codebase that needed the converter and didn't have it. I realize that those places probably should've had it in the first place, or the appropriate member should have been `JsonIgnore`d, but circumstances not worth going over dictated the approach I took.

### Configuration

.NET 7 and .NET 8, Windows 10 64-bit.

**Comment by eiriktsarpalis** [comment]
.NET 8 makes changes in how contract metadata gets resolved, the breaking change has been [documented here](https://learn.microsoft.com/en-us/dotnet/core/compatibility/serialization/8.0/metadata-resolving). This would still fail if you tried to deserialize the value, but it will now throw eagerly before any serialization op can be performed.
