### ISSUE TITLE
Profiler test failing with "Unable to find cdb.exe"

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#99091]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=583627
Build error leg or test failing: profiler\\multiple\\multiple\\multiple.cmd
Pull request: https://github.com/dotnet/runtime/pull/99086

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Unable to find cdb.exe at",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=583627
**Error message validated:** `[Unable to find cdb.exe at`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 2/29/2024 1:41:58 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[583627](https://dev.azure.com/dnceng-public/public/_build/results?buildId=583627)|dotnet/runtime|[profiler\\multiple\\multiple\\multiple.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=583627&view=ms.vss-test-web.build-test-results-tab&runId=14040536&resultId=114012)|dotnet/runtime#99086|
|[583523](https://dev.azure.com/dnceng-public/public/_build/results?buildId=583523)|dotnet/runtime|[profiler\\multiple\\multiple\\multiple.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=583523&view=ms.vss-test-web.build-test-results-tab&runId=14037014&resultId=114044)|dotnet/runtime#99081|
|[583409](https://dev.azure.com/dnceng-public/public/_build/results?buildId=583409)|dotnet/runtime|[GC\\LargeMemory\\API\\gc\\gettotalmemory\\gettotalmemory.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=583409&view=ms.vss-test-web.build-test-results-tab&runId=14034198&resultId=100082)|dotnet/runtime#94250|
|[583200](https://dev.azure.com/dnceng-public/public/_build/results?buildId=583200)|dotnet/runtime|[profiler\\multiple\\multiple\\multiple.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=583200&view=ms.vss-test-web.build-test-results-tab&runId=14028564&resultId=114044)|dotnet/runtime#99024|
|[583177](https://dev.azure.com/dnceng-public/public/_build/results?buildId=583177)|dotnet/runtime|[profiler\\multiple\\multiple\\multiple.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=583177&view=ms.vss-test-web.build-test-results-tab&runId=14027466&resultId=114044)|dotnet/runtime#99019|
|[583158](https://dev.azure.com/dnceng-public/public/_build/results?buildId=583158)|dotnet/runtime|[profiler\\multiple\\multiple\\multiple.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=583158&view=ms.vss-test-web.build-test-results-tab&runId=14027310&resultId=114044)|dotnet/runtime#98409|
|[582928](https://dev.azure.com/dnceng-public/public/_build/results?buildId=582928)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=582928&view=ms.vss-test-web.build-test-results-tab&runId=14018742&resultId=100024)|dotnet/runtime#99037|
|[582797](https://dev.azure.com/dnceng-public/public/_build/results?buildId=582797)|dotnet/runtime|[profiler\\multiple\\multiple\\multiple.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=582797&view=ms.vss-test-web.build-test-results-tab&runId=14017260&resultId=114044)|dotnet/runtime#99040|
|[582660](https://dev.azure.com/dnceng-public/public/_build/results?buildId=582660)|dotnet/runtime|[profiler\\multiple\\multiple\\multiple.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=582660&view=ms.vss-test-web.build-test-results-tab&runId=14010966&resultId=113310)|dotnet/runtime#96941|
|[582633](https://dev.azure.com/dnceng-public/public/_build/results?buildId=582633)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=582633&view=ms.vss-test-web.build-test-results-tab&runId=14008874&resultId=100024)|dotnet/runtime#99037|
|[582433](https://dev.azure.com/dnceng-public/public/_build/results?buildId=582433)|dotnet/runtime|[profiler\\multiple\\multiple\\multiple.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=582433&view=ms.vss-test-web.build-test-results-tab&runId=14004714&resultId=114044)|dotnet/runtime#98812|
|[582402](https://dev.azure.com/dnceng-public/public/_build/results?buildId=582402)|dotnet/runtime|[profiler\\multiple\\multiple\\multiple.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=582402&view=ms.vss-test-web.build-test-results-tab&runId=14003942&resultId=113390)||
|[582272](https://dev.azure.com/dnceng-public/public/_build/results?buildId=582272)|dotnet/runtime|[profiler\\multiple\\multiple\\multiple.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=582272&view=ms.vss-test-web.build-test-results-tab&runId=13998778&resultId=114044)|dotnet/runtime#99025|
|[582202](https://dev.azure.com/dnceng-public/public/_build/results?buildId=582202)|dotnet/runtime|[JIT/Stress/ABI/pinvokes_d/pinvokes_d.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=582202&view=ms.vss-test-web.build-test-results-tab&runId=13996494&resultId=105898)|dotnet/runtime#99026|
|[582138](https://dev.azure.com/dnceng-public/public/_build/results?buildId=582138)|dotnet/runtime|[profiler\\multiple\\multiple\\multiple.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=582138&view=ms.vss-test-web.build-test-results-tab&runId=13994014&resultId=113649)|dotnet/runtime#99024|
|[582100](https://dev.azure.com/dnceng-public/public/_build/results?buildId=582100)|dotnet/runtime|[profiler\\multiple\\multiple\\multiple.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=582100&view=ms.vss-test-web.build-test-results-tab&runId=13993034&resultId=113824)|dotnet/runtime#98812|
|[582042](https://dev.azure.com/dnceng-public/public/_build/results?buildId=582042)|dotnet/runtime|[profiler\\multiple\\multiple\\multiple.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=582042&view=ms.vss-test-web.build-test-results-tab&runId=13991644&resultId=114044)|dotnet/runtime#99019|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|15|17|17|

**Comment by hoyosjs** [comment]
@ericstj this is the merge on green infra. It means the test is crashing but things are not getting analyzed since it can't find the debugger in the machine. Looks like the path for the ARM64 debugger isn't as expected in ARM64 VMs.

**Comment by hoyosjs** [comment]
We can't use merge on green for these as it will cause things to go through just because the analysis infra isn't working properly.

**Comment by carlossanlop** [comment]
Yeah, it's going to start hiding real failures like it happened with XUnitLogChecker not being found in outerloop. So this will have to get prioritized for fixing.

This is a good argument to ensuring that the merge on green infrastructure is super stable before we enable it for everyone. Once it starts affecting all contributor PRs, they'll be opening issues for all types of failures, including infra failures like this one. So it's good that we're catching it now.

**Comment by ericstj** [comment]
I see  - @hoyosjs could we use `profiler_multiple._multiple_multiple_._multiple_multiple_cmd()` here as a pattern instead?  Just turn off this one test?

**Comment by ericstj** [comment]
May be a duplicate of https://github.com/dotnet/runtime/issues/98817.  Closing this one out for now.

**Comment by hoyosjs** [comment]
That test got fixed at night and there's another tracking issue for it. I'm using this one to remind myself to fix the infra. I started creating a VM to validate CDB.

**Comment by hoyosjs** [comment]
I had to reopen https://github.com/dotnet/arcade/issues/11868. There's an installer for this in the image generation lab, but the VMs don't have CDB installed.
