### ISSUE TITLE
System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose CI test failure

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#99142]
```
    System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose(payloadSize: 1024, closeServer: False, useDispose: False) [FAIL]
      Assert.False() Failure
      Expected: False
      Actual:   True
      Stack Trace:
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs(1308,0): at System.Net.Quic.Tests.QuicStreamTests.<>c__DisplayClass45_0.<<ReadsClosedFinishes_ConnectionClose>g__CheckReadsClosed|2>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs(1299,0): at System.Net.Quic.Tests.QuicStreamTests.<>c__DisplayClass45_0.<<ReadsClosedFinishes_ConnectionClose>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs(1299,0): at System.Net.Quic.Tests.QuicStreamTests.<>c__DisplayClass45_0.<<ReadsClosedFinishes_ConnectionClose>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(285,0): at System.Net.Quic.Tests.QuicTestBase.<>c__DisplayClass39_1.<<RunClientServer>b__1>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(120,0): at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(90,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(55,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(275,0): at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(305,0): at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(305,0): at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(269,0): at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs(1239,0): at System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose(Int32 payloadSize, Boolean closeServer, Boolean useDispose)
        --- End of stack trace from previous location ---
MsQuic Counters:
    CONN_CREATED 1580
    CONN_HANDSHAKE_FAIL 25
    CONN_APP_REJECT 8
    CONN_LOAD_REJECT N/A
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=584607
Build error leg or test failing: System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose
Pull request: https://github.com/dotnet/runtime/pull/99092

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose.*FAIL",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=584607
**Error message validated:** `[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose.*FAIL`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 3/1/2024 2:29:07 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[611434](https://dev.azure.com/dnceng-public/public/_build/results?buildId=611434)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=611434&view=ms.vss-test-web.build-test-results-tab&runId=14929410&resultId=202485)|dotnet/runtime#100066|
|[606964](https://dev.azure.com/dnceng-public/public/_build/results?buildId=606964)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=606964&view=ms.vss-test-web.build-test-results-tab&runId=14797392&resultId=206539)|dotnet/runtime#99835|
|[606497](https://dev.azure.com/dnceng-public/public/_build/results?buildId=606497)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=606497&view=ms.vss-test-web.build-test-results-tab&runId=14779934&resultId=206646)|dotnet/runtime#99866|
|[605187](https://dev.azure.com/dnceng-public/public/_build/results?buildId=605187)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=605187&view=ms.vss-test-web.build-test-results-tab&runId=14731338&resultId=206539)|dotnet/runtime#99835|
|[603632](https://dev.azure.com/dnceng-public/public/_build/results?buildId=603632)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=603632&view=ms.vss-test-web.build-test-results-tab&runId=14679780&resultId=206525)|dotnet/runtime#99628|
|[601726](https://dev.azure.com/dnceng-public/public/_build/results?buildId=601726)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=601726&view=ms.vss-test-web.build-test-results-tab&runId=14609262&resultId=206521)|dotnet/runtime#98495|
|[599346](https://dev.azure.com/dnceng-public/public/_build/results?buildId=599346)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=599346&view=ms.vss-test-web.build-test-results-tab&runId=14528796&resultId=206618)|dotnet/runtime#99590|
|[2400337](https://dev.azure.com/dnceng/internal/_build/results?buildId=2400337)|dotnet-runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng//internal/_build/results?buildId=2400337&view=ms.vss-test-web.build-test-results-tab&runId=53239659&resultId=206172)||
|[597206](https://dev.azure.com/dnceng-public/public/_build/results?buildId=597206)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=597206&view=ms.vss-test-web.build-test-results-tab&runId=14469294&resultId=207297)|dotnet/runtime#99513|
|[596663](https://dev.azure.com/dnceng-public/public/_build/results?buildId=596663)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=596663&view=ms.vss-test-web.build-test-results-tab&runId=14446490&resultId=206172)|dotnet/runtime#98559|
|[591878](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591878)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591878&view=ms.vss-test-web.build-test-results-tab&runId=14299036&resultId=206179)|dotnet/runtime#99372|
|[591807](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591807)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicCipherSuitesPolicyTests.SupportedCipher_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591807&view=ms.vss-test-web.build-test-results-tab&runId=14296908&resultId=215279)|dotnet/runtime#99371|
|[587649](https://dev.azure.com/dnceng-public/public/_build/results?buildId=587649)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=587649&view=ms.vss-test-web.build-test-results-tab&runId=14172388&resultId=206611)|dotnet/runtime#98984|
|[587140](https://dev.azure.com/dnceng-public/public/_build/results?buildId=587140)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=587140&view=ms.vss-test-web.build-test-results-tab&runId=14152254&resultId=206502)|dotnet/runtime#99211|
|[585226](https://dev.azure.com/dnceng-public/public/_build/results?buildId=585226)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=585226&view=ms.vss-test-web.build-test-results-tab&runId=14093872&resultId=206466)|dotnet/runtime#99148|
|[584607](https://dev.azure.com/dnceng-public/public/_build/results?buildId=584607)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=584607&view=ms.vss-test-web.build-test-results-tab&runId=14070406&resultId=206524)|dotnet/runtime#99092|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|5|16|

**Comment by rzikm** [comment]
My bad, there were many tests failing on those platforms due to unrelated issues
