### ISSUE TITLE
Can cross-platform cross-compilation be achieved in .net9.0

### ISSUE THREAD

**Issue by INotGreen** [dotnet/runtime#99152]

**Comment by huoyaoyuan** [comment]
Which part do you mean, CLR itself, JIT, or NativeAOT?

Cross compilation of C++ code isn't really controlled by us.

**Comment by INotGreen** [comment]
In Native AOT mode, can binary files in Linux and Macos be compiled in Windows like Golang?

**Comment by am11** [comment]
We _can_ setup cross-OS compilation toolchain using clang or multi-target gcc etc., but it is untested. e..g. linux-bionic cross-OS compilation is possible from Windows and macOS. Just pass `-p:DisableUnsupportedError=true` to enter this "I know what I'm doing" mode and use at your own risk. :)

There are no plans for full linker implementation in .NET 9: https://github.com/dotnet/runtime/issues/98627#issuecomment-1951323297. When that will happen, it would be possible.

The safe solution for now is to setup a CI pipeline (like GitHub Actions, CirrusCI etc.) to publish the binaries for target OS using their native linkers.

**Comment by MichalPetryka** [comment]
There's also [PublishAotCross](https://github.com/MichalStrehovsky/PublishAotCross) from @MichalStrehovsky but it's not officially supported and not everything works there.

**Comment by huoyaoyuan** [comment]
If I'm understanding correctly:

We have objwriter and cross-jit, so we can cross compile object files.
We use the system linker to link object files into native executable or library. This can't be truly cross platform now.

I remember that cross-platform publishing app host had issues around native resources and Windows manifest. Mac also requires a Mac for notarization etc.

**Comment by am11** [comment]
Yes, @filipnavara developed projects which allow us to do cross platform signing etc. but piecing it together is bit of a challenge at the moment. Besides, running in CI on the target OS has the benefits like we can execute unit tests against the published binary e.g. CirrucCI has osx-arm64 images on which we can publish the app, run tests and upload the artifact directly to a GitHub release (in GitHub Actions, we can run osx-arm64 tests under Rosetta emulation on osx-x64 native VM). So although it will be great to have cross-OS linker capability in NativeAOT toolset, most users will likely be interested in running the complete workflow (build, publish, test etc.) on the native CI machines.

**Comment by alexrp** [comment]
> in GitHub Actions, we can run osx-arm64 tests under Rosetta emulation on osx-x64 native VM

Just want to add that GitHub Actions has `osx-arm64` support now: https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/

**Comment by agocke** [comment]
The final answer to "Can cross-platform cross-compilation be achieved for Native AOT" is **No, as long as the following are still true**:

1. Platform C/C++ toolchains do not support cross-OS compilation
2. Native AOT relies on the platform C/C++ toolchains

There is no plan to ever change (2) and our security model will likely always require it. (1) has been true for decades and has no signs of changing.

Unless one of the above changes, most likely the C toolchain support, Native AOT will need to rely on virtualization-based solutions for cross-compilation.

**Comment by filipnavara** [comment]
In addition to all the reasons mentioned above, compiling macOS binaries on non-macOS machines is problematic due to macOS SDK license. The license allows it's usage only on Apple hardware. That's not a technical restriction but strictly a licensing restriction since cross-building toolchains exist both for Windows and Linux (although without the proprietary tools necessary to build resource files, etc.). The closest thing to making that specific cross-targeting working is the Zig linker, which ships with minimal libc bindings.
