### ISSUE TITLE
Getting .net framework error when starting ADFS  management console

### ISSUE THREAD

**Issue by bhaveshsharma** [dotnet/runtime#99155]
### Description

I got .net framework version 4.8.09067 when i have windows 2022 server installed. Later i setup this machine for ASFS setup.
But ADFS MGMT console never opens up. When verified logs it comes that there are .net failures 

i have the latest .net framework installed then that is 4.8.1.

but still i see same .net errors

Application: mmc.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFDBC696FF5 (00007FFDBC640000) with exit code 80131506.

Faulting application name: mmc.exe, version: 10.0.20348.2322, time stamp: 0xcbf39e2e
Faulting module name: clr.dll, version: 4.8.9195.0, time stamp: 0x64e92534
Exception code: 0xc0000005
Fault offset: 0x0000000000056ff5
Faulting process id: 0x3288
Faulting application start time: 0x01da6bc2abe8da43
Faulting application path: C:\Windows\system32\mmc.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Report Id: 12d146ac-32ef-44ba-bb7f-f9fc6ec5b871
Faulting package full name: 
Faulting package-relative application ID:

How to fix it? How can i get ADFS mgmt console working. How to resolve these errors.

### Reproduction Steps

On windows 2022 server have .net frameork 4.8 installed
Setup ADFS SERVER
Open ADFS mgmt console, it fails to open.

### Expected behavior

Adfs mgmt console should open

### Actual behavior

Console not opening.

### Regression?

No

### Configuration

Windows server 2022 
X64

**Comment by huoyaoyuan** [comment]
.NET Framework specific issue should be reported to [Developer Community](https://developercommunity.visualstudio.com/dotnet/report).

**Comment by jeffschwMSFT** [comment]
once you have a link, please paste it here so we can help routing

**Comment by jeffschwMSFT** [comment]
closing for now, though once you have a link please share.
