### ISSUE TITLE
[mono] Intrinsify API's in SpanHelpers.ByteMemOps.cs

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#99161]
Two new API's were added and intrinsified by CoreCLR. They are used in the library which caused Performance regression in Mono. See https://github.com/dotnet/perf-autofiling-issues/issues/29872. These new API's were added via https://github.com/dotnet/runtime/pull/98623

The API's to intrinsify are

- [ ] SpanHelpers.Memmove -> Update existing intrinsics support for `Buffer.Memmove`. See the code below
https://github.com/dotnet/runtime/blob/fd48b6f5d1ff81a81d09e9d72982cc9e8d139852/src/mono/mono/mini/intrinsics.c#L288-L310
- [ ] SpanHelpers.ClearWithoutReferences
- [ ] SpanHelpers.Fill

**Comment by lewing** [comment]
This is one of the regressions in https://github.com/dotnet/perf-autofiling-issues/issues/30686 so it is potentially quite impactful on wasm

**Comment by lewing** [comment]
https://github.com/dotnet/perf-autofiling-issues/issues/30686#issuecomment-2075932932

**Comment by lewing** [comment]
cc @EgorBo @JulieLeeMSFT

**Comment by EgorBo** [comment]
> cc @EgorBo @JulieLeeMSFT

It was decided that it should be handled on Mono side https://github.com/dotnet/runtime/pull/99059

**Comment by lewing** [comment]
> > cc @EgorBo @JulieLeeMSFT
> 
> It was decided that it should be handled on Mono side #99059

Yes, this issue is about fixing it in mono.  I pinged you because this is a ship blocking regression for wasm and I wanted to make sure that was clear.

**Comment by lewing** [comment]
It is probably worth understanding why the other mono-AOT-llvm runtimes were not impacted in the same way.

**Comment by lewing** [comment]
Iinterpreter changes were added in https://github.com/dotnet/runtime/pull/99115

**Comment by EgorBo** [comment]
> this is a ship blocking regression

I think we can just land https://github.com/dotnet/runtime/pull/99059/ if so cc @fanyang-mono

**Comment by fanyang-mono** [comment]
It is unfortunate that this wasn't flagged as a ship blocking issue for wasm at the time this regression was introduced. I could work on getting this in for Preview 5 instead of #99059.

**Comment by lewing** [comment]
> It is unfortunate that this wasn't flagged as a ship blocking issue for wasm at the time this regression was introduced. I could work on getting this in for Preview 5 instead of #99059.

We couldn't flag it then because we couldn't identify it because wasm runs in dotnet/performance were not working.  I was only able to identify it now that the performance team has backfilled the missing runs and I had time to dig into them again.

**Comment by lewing** [comment]
And thank you to the perf team for doing the backfill it made it possible to positively identify the cause.  I'm still a bit curious why it impacted wasm aot so much more heavily than the rest of mono.

cc @LoopedBard3 @DrewScoggins @sblom

**Comment by EgorBo** [comment]
I presume previously it was intrinsified to be an llvm.memset/memcpy calls. The thing is - those calls were not GC-interrupt friendly so, technically, this performance regression improves GC latency in fact.

**Comment by lewing** [comment]
> I presume previously it was intrinsified to be an llvm.memset/memcpy calls. The thing is - those calls were not GC-interrupt friendly so, technically, this performance regression improves GC latency in fact.

GC latency in single threaded wasm is not impacted at all by that

**Comment by matouskozak** [comment]
> n arm64 with Mono LLVM AOT, which doesn't have the same regression as wasm

I very much hope so. We are missing the data between February and March because Mono AOT-llvm was similarly affected as WASM was. However, since we didn't observe significant regression after we regain the measurements we didn't ask for backfill of the missing values. Do you think the measurements could be flawed?

I run a quick local measurements using `benchmarks_local.py` script for this range https://github.com/dotnet/runtime/compare/79dd9bae9bb881eb716b608577c4cedc6c9cba72...5ef47c852ffd51aaeb52e34391fe4fed261c9f26 and got 300/270ns so nowhere near the regression magnitude that WASM had.

**Comment by fanyang-mono** [comment]
I looked into this issue a little bit more and confirmed these:

- Why did `System.Collections.CopyTo<Int32>.ReadOnlySpan(Size: 2048)` regress so much on wasm AOT?
WASM AOT mode is a LLVM-AOT mode with interpreter fallback. When comparing the result between wasm AOT and wasm interpreter, the result matches. So it seems that something used to be AOT'ed wasn't AOT'ed anymore, after https://github.com/dotnet/runtime/pull/98623 was merged. In the WASM AOT chart, it also showed that with the fix here, it went back down to the performance level as before the regression.

*WASM interpreter data*
<img width="1006" alt="Screenshot 2024-04-29 at 10 26 34 AM" src="https://github.com/dotnet/runtime/assets/52458914/4cb2f45f-6167-466d-8d3e-646b45351361">

*WASM AOT data*
<img width="1007" alt="Screenshot 2024-04-29 at 10 27 54 AM" src="https://github.com/dotnet/runtime/assets/52458914/a0743883-e0b9-42fb-b812-07c7c6dd7048">

- Why didn't `System.Collections.CopyTo<Int32>.ReadOnlySpan(Size: 2048)` regress on mono LLVM-AOT?
This microbenchmark test is written with generics. Normal AOT mode usually doesn't AOT generic methods. And the relevant intrinsics are LLVM only. Additionally, the LLVM-AOT mode that we measure with microbenchmarks is LLVM-AOT mode with JIT fallback. And the number matches with JIT on x64.

*Mono LLVM-AOT*
<img width="998" alt="Screenshot 2024-04-29 at 10 51 53 AM" src="https://github.com/dotnet/runtime/assets/52458914/a4eb6042-1819-4a4d-9424-0c8484dd0013">

*Mono JIT*
<img width="1003" alt="Screenshot 2024-04-29 at 10 51 06 AM" src="https://github.com/dotnet/runtime/assets/52458914/97207c86-7a8c-4b98-8379-166126d607f3">

- Are we measuring Mono AOT-llvm correctly?
Yes. On x64, Vector4.Add is only intrinsified with LLVM. I saw that microbenchmark ran much faster on Mono LLVM-AOT than on Mono JIT.

*Mono LLVM-AOT*
<img width="1001" alt="Screenshot 2024-04-29 at 10 58 42 AM" src="https://github.com/dotnet/runtime/assets/52458914/80892c1f-3186-4263-826c-a5ce491db047">

*Mono JIT*
<img width="1003" alt="Screenshot 2024-04-29 at 10 57 55 AM" src="https://github.com/dotnet/runtime/assets/52458914/a429196d-4c8d-4347-8212-ab41ac821396">

- Why this microbenchmark triggered AOT on WASM AOT but not on Mono AOT?
I suspect that it is related to this piece of code: https://github.com/dotnet/runtime/blob/main/src/mono/mono/mini/aot-compiler.c#L5744-L5762
