### ISSUE TITLE
Configure the certificate valiation from the environment variable

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/runtime#99217]
We could set the environment variable `NODE_TLS_REJECT_UNAUTHORIZED=0` to disable TLS certificate validation in nodejs, is it possible to configure the env in dotnet

**Comment by rzikm** [comment]
There is no such environment configuration option for .NET, you need to configure the `RemoteCertificateValidationCallback` on SslStream options.

What is the use case for such an option? I personally don't like the idea of security being turned off due to a pressence of an environment variable.

**Comment by WeihanLi** [comment]
@rzikm thanks for the reply, sometimes the network may be complex.
For example, network proxy or IT network monitoring may break the ssl verify, and sometimes the ssl certificate may not get renewed in time, I want to configure the behavior without changing any code, so I want to configure the environment to bypass the certificate check.

I got an error when restore nuget packages in docker container in our network, think it's similar to this issue 
https://forums.docker.com/t/the-remote-certificate-is-invalid-because-of-errors-in-the-certificate-chain-untrustedroot/120494

So I'm trying to propose a new behavior to configure via environment variable, since it would not introduce any new API, I'm not using the api-proposal template

**Comment by Clockwork-Muse** [comment]
> For example, network proxy or IT network monitoring may break the ssl verify

If your corporate network is doing MiTM inspection, normally that should be handled transparently for you (in the sense that the remote cert should still have a valid chain).  It may mean that you need to add your corporate cert chain to your CI machines/images.

> and sometimes the ssl certificate may not get renewed in time

If this is the MiTM cert, you need to go after your network/security people with a clue-by-four.
If this is _your_ application cert, somebody need to go after _you_ with a clue-by-four.
Yes, certs expire all the time, and it can break things if they're not renewed in time.  **THAT'S THE ENTIRE POINT**.  It's there for your/everybody's protection.

**Comment by WeihanLi** [comment]
Yeah, you're right, I can access the NuGet.org from my local machine but not in the local docker container, think I should create a ticket for our IT support.

Think over it, think it's very dangerous if could configured with the environment variable, it may be abused with some libraries/apps which may cause uncensored risks

**Comment by Clockwork-Muse** [comment]
> Yeah, you're right, I can access the NuGet.org from my local machine but not in the local docker container, think I should create a ticket for our IT support.

They're almost certainly going to tell you it's something _you_ need to deal with.

More specifically, you should be adding the MiTM cert chain to your builder containers, which IT support are unlikely to do anything about directly (since it's the responsibility of whoever maintains your CI scripts).  They may be able to point you at a good source for the cert, though.

**Comment by wfurt** [comment]
It feels like this can be highly insecure. Injecting ENV is not that hard and can be done in sneaky ways. If anything I would suggest to build it to your app and use in in combination with RemoteCertificateValidationCallback @WeihanLi
