### ISSUE TITLE
> Should CA1820 be removed when all these changes defeat its perf improvement reasoning?

### ISSUE THREAD

**Issue by SimonCropp** [dotnet/runtime#99219]
> Should CA1820 be removed when all these changes defeat its perf improvement reasoning?

It's already disabled by default.  If there ends up being zero benefit after these improvements (including subsequent ones to get string.Empty and the like), we could consider deleting it entirely from the SDK.  I wouldn't rush to that, though.

_Originally posted by @stephentoub in https://github.com/dotnet/runtime/pull/63734#discussion_r784086754_

**Comment by SimonCropp** [comment]
@stephentoub but the current docs for CA1820 incorrectly recommend removing `string == ""`. ie if you read this https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1820#rule-description

> Comparing strings using the [String.Length](https://learn.microsoft.com/en-us/dotnet/api/system.string.length) property or the [String.IsNullOrEmpty](https://learn.microsoft.com/en-us/dotnet/api/system.string.isnullorempty) method is faster than using [Equals](https://learn.microsoft.com/en-us/dotnet/api/system.object.equals). This is because [Equals](https://learn.microsoft.com/en-us/dotnet/api/system.object.equals) executes significantly more MSIL instructions than either [IsNullOrEmpty](https://learn.microsoft.com/en-us/dotnet/api/system.string.isnullorempty) or the number of instructions executed to retrieve the [Length](https://learn.microsoft.com/en-us/dotnet/api/system.string.length) property value and compare it to zero.

you would incorrectly assume  `string == ""` is bad

**Comment by bartonjs** [comment]
Comparing

* string.IsNullOrEmpty
* str == ""
* str == string.Empty
* str?.Length > 0  
* str.Length > 0
* string.Equals(str, "")
* string.Equals(str, string.Empty)

(The Length ones are reversed, but, eh.)

Shows that they are all the same now on .NET Core.  However, for .NET Framework, string.Equals and == are still 2 to 4 times as expensive as the length checks.  Since the analyzers are shared for both (and for .NET Standard), I don't think we're justified in deleting it; some codebases could still find value in it.

Numbers should all be divided by 10_000:

```md
| Method             | Runtime            | Mean      | Error     | StdDev    | Ratio | RatioSD | Allocated | Alloc Ratio |
|------------------- |------------------- |----------:|----------:|----------:|------:|--------:|----------:|------------:|
| NullOrEmpty        | .NET 9.0           |  2.292 us | 0.0228 us | 0.0190 us |  1.00 |    0.01 |         - |          NA |
| NullOrEmpty        | .NET Framework 4.8 |  9.218 us | 0.0691 us | 0.0612 us |  4.02 |    0.04 |         - |          NA |
|                    |                    |           |           |           |       |         |           |             |
| EqualsLiteral      | .NET 9.0           |  2.283 us | 0.0110 us | 0.0092 us |  1.00 |    0.01 |         - |          NA |
| EqualsLiteral      | .NET Framework 4.8 | 18.511 us | 0.2290 us | 0.2142 us |  8.11 |    0.10 |         - |          NA |
|                    |                    |           |           |           |       |         |           |             |
| EqualsReference    | .NET 9.0           |  2.291 us | 0.0189 us | 0.0168 us |  1.00 |    0.01 |         - |          NA |
| EqualsReference    | .NET Framework 4.8 | 18.354 us | 0.1134 us | 0.1061 us |  8.01 |    0.07 |         - |          NA |
|                    |                    |           |           |           |       |         |           |             |
| NullableLength     | .NET 9.0           |  2.297 us | 0.0223 us | 0.0209 us |  1.00 |    0.01 |         - |          NA |
| NullableLength     | .NET Framework 4.8 |  4.492 us | 0.0423 us | 0.0396 us |  1.96 |    0.02 |         - |          NA |
|                    |                    |           |           |           |       |         |           |             |
| RiskyLength        | .NET 9.0           |  2.314 us | 0.0335 us | 0.0314 us |  1.00 |    0.02 |         - |          NA |
| RiskyLength        | .NET Framework 4.8 |  4.519 us | 0.0418 us | 0.0391 us |  1.95 |    0.03 |         - |          NA |
|                    |                    |           |           |           |       |         |           |             |
| StrEqualsLiteral   | .NET 9.0           |  2.288 us | 0.0211 us | 0.0198 us |  1.00 |    0.01 |         - |          NA |
| StrEqualsLiteral   | .NET Framework 4.8 | 18.440 us | 0.2451 us | 0.2293 us |  8.06 |    0.12 |         - |          NA |
|                    |                    |           |           |           |       |         |           |             |
| StrEqualsReference | .NET 9.0           |  2.294 us | 0.0234 us | 0.0208 us |  1.00 |    0.01 |         - |          NA |
| StrEqualsReference | .NET Framework 4.8 | 18.335 us | 0.1017 us | 0.0901 us |  7.99 |    0.08 |         - |          NA |
```

Sample benchmark:

```C#
    [Benchmark]
    public int NullableLength()
    {
        int sum = 0;

        for (int i = 0; i < 10_000; i++)
        {
            sum += Driver("");
        }

        return sum;

        static int Driver(string str)
        {
            if (str?.Length > 0)
            {
                return 5;
            }

            return -2;
        }
    }
```
