### ISSUE TITLE
Localization issue with dates in Basque (eu-ES) in Blazor .NET 8

### ISSUE THREAD

**Issue by Edgar-MP** [dotnet/runtime#99222]
### Description

I am experiencing an issue with date localization in Basque (eu-ES) in Blazor .NET 8. When the application is pre-rendered on the server, the date is correctly displayed in Basque. However, when the application reaches the client, the date is displayed in Spanish.

This issue only occurs with the “eu-ES” culture. I have tested with other cultures (such as English, French, etc.) and do not experience this issue.

### Reproduction Steps

1. Set the application culture to “eu-ES”.
2. Pre-render the application on the server.
3. Observe that the date is correctly displayed in Basque.
4. Send the application to the client.
5. Observe that the date is now displayed in Spanish.

I hope this helps you report the issue. If you have more questions, feel free to ask.

### Expected behavior

Date displayed in Basque

### Actual behavior

Date displayed in Spanish (default culture)

### Configuration

- Windows 11 Pro 23H2 x64 arch
- Visual Studio Community 2022 17.9.2
- Blazor executed with Chrome and Firefox
- Microsoft .NET 8

**Comment by maraf** [comment]
Can you please try if one the options from this comment works for you https://github.com/dotnet/runtime/issues/97252#issuecomment-1905764272 ?

**Comment by Edgar-MP** [comment]
Hi, I had already configured the csproj, and the script did not help me.

**Comment by ilonatommy** [comment]
@Edgar-MP, "eu-ES" is not supported by default on WASM, we have all supported locales listed here:
https://github.com/dotnet/icu/blob/9c4c9995bc756a01597b5efb0e452ef879a76d99/icu-filters/icudt_wasm.json#L7.

If for your app you require "eu-ES" you can prepare custom ICU bundle that includes that locale (and maybe removes these that you are not planning to use in case you want to reduce the publish size). In the issue mentioned above by @maraf the " Prepare custom ICU bundle" step is needed [doc](https://github.com/dotnet/runtime/blob/89bba37a92053f52e38d5a5c81a1f3510319dabf/docs/design/features/globalization-icu-wasm.md?plain=1#L17).

**Comment by Edgar-MP** [comment]
And why is this happening? I mean charge, the page changes the name of the month to Basque (culture not supported), but then returns to the default culture (es-ES), and the rest of the page keeps the texts of the .resx files in Basque.

https://github.com/dotnet/runtime/assets/57589251/063cac16-3cb4-42ed-927f-1b4d99adb6c8

**Comment by ilonatommy** [comment]
Server has access to full ICU data while the client has access only to limited set. The version pre-rendered using the server should then work fine as you say. To the client we load only small set of ICU (maximally 200 locales if you set `BlazorWebAssemblyLoadAllGlobalizationData` to true, so "all data" in reality means "all 200 locales data, chosen out of all possible locales". When "eu-ES" is not found, it falls back to the neural culture family which is "es".

**Comment by Edgar-MP** [comment]
And is there any way to configure it to use only the 5 cultures I use (including eu-ES if possible)?

**Comment by ilonatommy** [comment]
Yes, it's possible. You would need to build ICU from source and set the filters to locales you need + "en-US" (required for fallback scenarios). What cultures do you need beyond "eu-ES"?

**Comment by Edgar-MP** [comment]
I need this 5 cultures:

- eu-ES
- es-ES
- ca-ES
- en-US
- fr-FR

**Comment by ilonatommy** [comment]
[icudt-edgar.zip](https://github.com/dotnet/runtime/files/14493214/icudt-edgar.zip)
It is ~3 times smaller than the full ICU and contains only the locales listed by you. Now:
1) Paste it to a known path, e.g. project root
2) Add `<BlazorIcuDataFileName>$(MSBuildThisFileDirectory)icudt-edgar.dat</BlazorIcuDataFileName>` to msbuild properties.
3) Test
