### ISSUE TITLE
`AssemblyBuilderAccess` has no `Save` enum and `RunAndSave` enum

### ISSUE THREAD

**Issue by Yuisyuu** [dotnet/runtime#99224]
### Description

`AssemblyBuilderAccess` has no `Save` enum and `RunAndSave` enum.

### Reproduction Steps

None

### Expected behavior

`AssemblyBuilderAccess` has `Save` enum and `RunAndSave` enum.

### Actual behavior

`AssemblyBuilderAccess` has no `Save` enum and `RunAndSave` enum.

**Comment by huoyaoyuan** [comment]
`AssemblyBuilder.Save` is currently work in progress for .NET Core. See the tracking issue #92975.

The team decided to use separated methods instead of enums for creating the assembly builder. See discussion in #83988.
