### ISSUE TITLE
Question about Dictionary<TKey, TValue> reading order

### ISSUE THREAD

**Issue by strangeman375** [dotnet/runtime#99220]
Hello!

MSDN says "The order in which the items are returned is undefined"
https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2?view=net-8.0

Is that correct at the current time?

I've seen a lot of code that expects same read order as add order, if there were no deletions.
Are all these places in the code bugs?

**Comment by huoyaoyuan** [comment]
Current implementation uses a linear array for value and another array for hash indexing. The value array is allocated in addition order. Values will be returned in the order added.

We do not want to commit or guarantee this. If the implementation changes in future release, code depending on this is going to break. An example is Stream implementation changes broke code that expecting Read to fill the buffer.

**Comment by strangeman375** [comment]
Ok, thanks.
