### ISSUE TITLE
Mono WASM PInvoke Table generation does not handle backticks

### ISSUE THREAD

**Issue by barbieri-quisitive** [dotnet/runtime#99241]
### Description

Microsoft.CognitiveServices.Speech puts the following line into the pinvoke-table.h:

void wasm_native_to_interp_Microsoft_CognitiveServices_Speech_csharp_InteropEvent`1_FromNativeCallback (int arg0,int arg1,int arg2) { 

The backtick (`) after InteropEvent is not recognized by the C compiler.

I found the following recent resolved bug in which a character needed to be escaped, it sounds like more escaping just needs to be done: https://github.com/dotnet/runtime/issues/93999

### Reproduction Steps

Build a WASM project that includes Microsoft.CognitiveServices.Speech 1.35.0 as a dependency.

### Expected behavior

Successful build

### Actual behavior

>C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\8.0.0\Sdk\WasmApp.Native.targets(366,5): error : In file included from C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\8.0.0\runtimes\browser-wasm\native\src\pinvoke.c:15:
>C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\8.0.0\Sdk\WasmApp.Native.targets(366,5): error : obj\Debug\net8.0\browser-wasm\wasm\for-build\pinvoke-table.h:3038:6: error: variable has incomplete type 'void'
>C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\8.0.0\Sdk\WasmApp.Native.targets(366,5): error : void wasm_native_to_interp_Microsoft_CognitiveServices_Speech_csharp_InteropEvent`1_FromNativeCallback (int arg0,int arg1,int arg2) { 

### Configuration

.NET 8.0
Windows 11 x64
Avalonia WASM

**Comment by mkhamoyan** [comment]
Tried to reproduce this locally but it doesn't fail. Looks like the issue has been solved in .Net 9.
In `pinvoke_table.h`  I don't see backtick after InteropEvent but `60`

<img width="1167" alt="result" src="https://github.com/dotnet/runtime/assets/96171496/a305c585-7157-4667-aaf7-70626001893d">

**Comment by lewing** [comment]
Calling this closed, please reopen if you can reproduce the problem with recent nightly builds or preview4 when it is released
