### ISSUE TITLE
Wasm SignalRClientTests timing out

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#99268]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=588622
Build error leg or test failing: Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/99146

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": " Wasm.Build.Tests: [Long Running Test] 'Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.SignalRPassMessages', Elapsed: 01",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=588622
**Error message validated:** `[ Wasm.Build.Tests: [Long Running Test] 'Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.SignalRPassMessages', Elapsed: 01`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 3/5/2024 1:39:51 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[594832](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594832)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594832&view=ms.vss-test-web.build-test-results-tab&runId=14388652&resultId=100164)||
|[594763](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594763)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594763&view=ms.vss-test-web.build-test-results-tab&runId=14386252&resultId=100164)|dotnet/runtime#99397|
|[594273](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594273)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594273&view=ms.vss-test-web.build-test-results-tab&runId=14364658&resultId=100164)|dotnet/runtime#99267|
|[594166](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594166)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594166&view=ms.vss-test-web.build-test-results-tab&runId=14362666&resultId=100164)|dotnet/runtime#99081|
|[593674](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593674)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593674&view=ms.vss-test-web.build-test-results-tab&runId=14355594&resultId=100163)|dotnet/runtime#99351|
|[591905](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591905)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591905&view=ms.vss-test-web.build-test-results-tab&runId=14354860&resultId=100164)|dotnet/runtime#99340|
|[593606](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593606)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593606&view=ms.vss-test-web.build-test-results-tab&runId=14353264&resultId=100164)|dotnet/runtime#99392|
|[593575](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593575)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593575&view=ms.vss-test-web.build-test-results-tab&runId=14351812&resultId=100164)|dotnet/runtime#98986|
|[593498](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593498)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593498&view=ms.vss-test-web.build-test-results-tab&runId=14350626&resultId=100164)|dotnet/runtime#96332|
|[593365](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593365)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593365&view=ms.vss-test-web.build-test-results-tab&runId=14348344&resultId=100164)|dotnet/runtime#98559|
|[593229](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593229)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593229&view=ms.vss-test-web.build-test-results-tab&runId=14343096&resultId=100001)|dotnet/runtime#99403|
|[593250](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593250)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593250&view=ms.vss-test-web.build-test-results-tab&runId=14343086&resultId=100164)|dotnet/runtime#99188|
|[592824](https://dev.azure.com/dnceng-public/public/_build/results?buildId=592824)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=592824&view=ms.vss-test-web.build-test-results-tab&runId=14328852&resultId=100164)|dotnet/runtime#99397|
|[591783](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591783)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591783&view=ms.vss-test-web.build-test-results-tab&runId=14326364&resultId=100164)|dotnet/runtime#99347|
|[592048](https://dev.azure.com/dnceng-public/public/_build/results?buildId=592048)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=592048&view=ms.vss-test-web.build-test-results-tab&runId=14301554&resultId=100164)||
|[591885](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591885)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591885&view=ms.vss-test-web.build-test-results-tab&runId=14300168&resultId=100164)|dotnet/runtime#99343|
|[591609](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591609)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591609&view=ms.vss-test-web.build-test-results-tab&runId=14292718&resultId=100164)|dotnet/runtime#98981|
|[591452](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591452)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591452&view=ms.vss-test-web.build-test-results-tab&runId=14288726&resultId=100164)|dotnet/runtime#99355|
|[591326](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591326)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591326&view=ms.vss-test-web.build-test-results-tab&runId=14285026&resultId=100164)|dotnet/runtime#99188|
|[591360](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591360)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591360&view=ms.vss-test-web.build-test-results-tab&runId=14285268&resultId=100166)|dotnet/runtime#99350|
|[591287](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591287)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591287&view=ms.vss-test-web.build-test-results-tab&runId=14282156&resultId=100164)|dotnet/runtime#99273|
|[591279](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591279)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591279&view=ms.vss-test-web.build-test-results-tab&runId=14280954&resultId=100166)|dotnet/runtime#98495|
|[590802](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590802)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590802&view=ms.vss-test-web.build-test-results-tab&runId=14262902&resultId=100166)|dotnet/runtime#99277|
|[590663](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590663)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590663&view=ms.vss-test-web.build-test-results-tab&runId=14259026&resultId=100166)|dotnet/runtime#99185|
|[590220](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590220)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590220&view=ms.vss-test-web.build-test-results-tab&runId=14244378&resultId=100166)|dotnet/runtime#99296|
|[590138](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590138)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590138&view=ms.vss-test-web.build-test-results-tab&runId=14241432&resultId=100166)|dotnet/runtime#99328|
|[589678](https://dev.azure.com/dnceng-public/public/_build/results?buildId=589678)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=589678&view=ms.vss-test-web.build-test-results-tab&runId=14231798&resultId=100164)|dotnet/runtime#98495|
|[589684](https://dev.azure.com/dnceng-public/public/_build/results?buildId=589684)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=589684&view=ms.vss-test-web.build-test-results-tab&runId=14231366&resultId=100166)|dotnet/runtime#98802|
|[589664](https://dev.azure.com/dnceng-public/public/_build/results?buildId=589664)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=589664&view=ms.vss-test-web.build-test-results-tab&runId=14230990&resultId=100166)|dotnet/runtime#99259|
|[589365](https://dev.azure.com/dnceng-public/public/_build/results?buildId=589365)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=589365&view=ms.vss-test-web.build-test-results-tab&runId=14222704&resultId=100164)|dotnet/runtime#99259|
|[589211](https://dev.azure.com/dnceng-public/public/_build/results?buildId=589211)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=589211&view=ms.vss-test-web.build-test-results-tab&runId=14218884&resultId=100164)|dotnet/runtime#98492|
|[589196](https://dev.azure.com/dnceng-public/public/_build/results?buildId=589196)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=589196&view=ms.vss-test-web.build-test-results-tab&runId=14218512&resultId=100164)|dotnet/runtime#98981|
|[588964](https://dev.azure.com/dnceng-public/public/_build/results?buildId=588964)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=588964&view=ms.vss-test-web.build-test-results-tab&runId=14212924&resultId=100163)|dotnet/runtime#99185|
|[588622](https://dev.azure.com/dnceng-public/public/_build/results?buildId=588622)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=588622&view=ms.vss-test-web.build-test-results-tab&runId=14200320&resultId=100164)|dotnet/runtime#99146|
|[587649](https://dev.azure.com/dnceng-public/public/_build/results?buildId=587649)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=587649&view=ms.vss-test-web.build-test-results-tab&runId=14172898&resultId=100164)|dotnet/runtime#98984|
|[587640](https://dev.azure.com/dnceng-public/public/_build/results?buildId=587640)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=587640&view=ms.vss-test-web.build-test-results-tab&runId=14172882&resultId=100164)|dotnet/runtime#99040|
|[587609](https://dev.azure.com/dnceng-public/public/_build/results?buildId=587609)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=587609&view=ms.vss-test-web.build-test-results-tab&runId=14171776&resultId=100164)|dotnet/runtime#98986|
|[587606](https://dev.azure.com/dnceng-public/public/_build/results?buildId=587606)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=587606&view=ms.vss-test-web.build-test-results-tab&runId=14171354&resultId=100163)|dotnet/runtime#99188|
|[587228](https://dev.azure.com/dnceng-public/public/_build/results?buildId=587228)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=587228&view=ms.vss-test-web.build-test-results-tab&runId=14156056&resultId=100163)|dotnet/runtime#98866|
|[587167](https://dev.azure.com/dnceng-public/public/_build/results?buildId=587167)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=587167&view=ms.vss-test-web.build-test-results-tab&runId=14153894&resultId=100163)|dotnet/runtime#98910|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|12|40|40|

**Comment by maraf** [comment]
cc @ilonatommy

**Comment by ilonatommy** [comment]
All timeouts after the fix are now https://github.com/dotnet/runtime/issues/98721. Closing.
