### ISSUE TITLE
The error interaction between `String.EndsWith` and `\u0001` in .NET 8

### ISSUE THREAD

**Issue by InfSein** [dotnet/runtime#99279]
### Description

The problem is visualized in the following code:

```
var str = "simple string, but end with:\u0001";

var endWithColonChar = str.EndsWith(':'); // false
var endWithU0001Char = str.EndsWith('\u0001'); // true
var endWithColon = str.EndsWith(":"); // true
var endWithU0001 = str.EndsWith("\u0001"); // true
```

And, if the above code is run in `.NET CORE 3.1`, `str.EndsWith(":")` will correctly return `false`.

### Reproduction Steps

1. Create a .NET console application
2. Set target framework like `<TargetFramework>net8.0</TargetFramework>`
3. Type the code given in the Description
4. Check the result.

### Expected behavior

The `str.EndsWith(":")` should returns `false`.

### Actual behavior

The `str.EndsWith(":")` returned `true`.

### Regression?

This issue is occurs in `.NET 8`, and not occurs in `.NET Core 3.1` (`<TargetFramework>netcoreapp3.1</TargetFramework>`).

### Known Workarounds

Use `str.EndsWith(':')` can correctly get the result we want.
However, this solution is not generalizable. For example, if I need to determine if a character ends in some character instead of a certain character ......

### Configuration

1. Which version of .NET is the code running on?
`.NET 8`
2. What OS and version, and what distro if applicable?
`Windows 11 23H2 (22631.3155)`
3. What is the architecture (x64, x86, ARM, ARM64)?
`x64`
4. Do you know whether it is specific to that configuration?
`It should not be.`
5. If you're using Blazor, which web browser(s) do you see this issue in?
`I'm not using Blazor.`

**Comment by filipnavara** [comment]
This is a classic pit of failure but not a bug. The `string` overload of `EndsWith` uses Unicode collation rules and current culture for the comparison, the `char` overload does not.

You can use `EndsWith(String, StringComparison.Ordinal)` to get ordinal string comparison.

**Comment by huoyaoyuan** [comment]
See also https://github.com/dotnet/runtime/issues/97544#issuecomment-1912000665

**Comment by filipnavara** [comment]
Yeah, specifically https://github.com/dotnet/runtime/issues/72992#issuecomment-1198334822:
> You are calling the linguistic `StartsWith` and not passing the `StringComparison.Ordinal`. This means the operation will be performed according to the sorting weight of the characters. Unicode defines some characters which are marked as [ignored characters](https://www.unicode.org/charts/collation/chart_Ignored.html). Which means these characters act as if they don't exist in the string at all. If your intention is to not use the linguistic comparisons, you need to pass `StringComparison.Ordinal` to the call and you'll get the desired behavior. Review the doc https://docs.microsoft.com/en-us/dotnet/core/extensions/globalization-icu to understand the change switching using ICU instead of NLS. The doc mentioned how to get back the old behavior if desired (which we are strongly not recommending because it will deviate from the globalization Unicode standard and will lose other functionality).
