### ISSUE TITLE
[API Proposal]: ParamCollectionAttribute

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/runtime#99285]
### Background and motivation

As part of supporting [Params Collections](https://github.com/dotnet/csharplang/blob/main/proposals/params-collections.md) feature, we need a new attribute that will be applied by C# compiler to non-array params parameters. 

### API Proposal

This is effectively a clone of `ParamArrayAttribute`, different namespace, different name, different meaning.
See https://github.com/dotnet/csharplang/blob/main/proposals/params-collections.md#metadata

```csharp
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Parameter, Inherited = true, AllowMultiple = false)]
    public sealed class ParamCollectionAttribute : Attribute
    {
        public ParamCollectionAttribute() { }
    }
}
```

### API Usage

Not meant for use in C# code.

**Comment by AlekseyTs** [comment]
CC @stephentoub

**Comment by stephentoub** [comment]
@AlekseyTs, I assume this is on the same plan as with other similar attributes, where the compiler with synthesize it internally if it can't find it in the compilation? I'm asking because of the "blocking" label; the feature will be usable even before this is added to the core libraries, right?

**Comment by stephentoub** [comment]
Also, the "Inherited = true" part... I assume that was just copied from ParamArrayAttribute. Will that have any effect on the compiler? It's odd to me that it (both ParamArray and ParamCollection) would be inherited from a reflection perspective.

**Comment by AlekseyTs** [comment]
> I assume this is on the same plan as with other similar attributes, where the compiler with synthesize it internally if it can't find it in the compilation? I'm asking because of the "blocking" label; the feature will be usable even before this is added to the core libraries, right?

That is correct, but we need to make sure the API shape is approved in order to know what to synthesize.

**Comment by stephentoub** [comment]
> we need to make sure the API shape is approved in order to know what to synthesize

Ok

**Comment by 333fred** [comment]
I suspect that it is true because it is indeed inherited; we use the base definition to determine if a parameter is `params`. C# will always include `ParamArrayAttribute` on every override, but other languages or custom IL may not, and it's likely still desirable to have the attribute show up in reflection on overrides missing the attribute in IL.

**Comment by bartonjs** [comment]
* It was asked whether there should be an "s" at the end of "Param", and the answer was "no".
* We also talked about the Inherited=true, and are sticking with "match what ParamArrayAttribute does", which is true.

```c#
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Parameter, Inherited = true, AllowMultiple = false)]
    public sealed class ParamCollectionAttribute : Attribute
    {
        public ParamCollectionAttribute() { }
    }
}
```
