### ISSUE TITLE
API change: remove StringBuilder.AppendLine (IFormatProvider ...

### ISSUE THREAD

**Issue by yfital** [dotnet/runtime#99307]
Following a move towards using .net's anlayzers in recommended level
```
<PropertyGroup>
<AnalysisMode>Recommended</AnalysisMode>
</PropertyGroup>
```

I've began receiving a lot of warnings arounds StringBuilder.AppendLine with interpolated text.
Upon inspection, it seems like for some reason, interpolated text handler overload received an extra overload which receives IFormatProvider.

The above, triggers [CA1305](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1305)

Upon inspection of the actual code, it seems like:
1. StringBuilder.AppendLine (string) does not have such overload
2. StringBuilder.AppendLine($"") has such overload, and it is ignored in [code](https://github.com/dotnet/runtime/blob/7c0ed473e76a1861568fa2269f855e2d2e3f16cc/src/libraries/System.Private.CoreLib/src/System/Text/StringBuilder.cs#L1121)

As such, it seems like the additional overload was added by mistake.
Initially I thought about requesting to ignore it in the CA rules, but it seems like a mishap in the class itself, this is a request to remove it in future versions.

**Comment by stephentoub** [comment]
> and it is ignored in [code](https://github.com/dotnet/runtime/blob/7c0ed473e76a1861568fa2269f855e2d2e3f16cc/src/libraries/System.Private.CoreLib/src/System/Text/StringBuilder.cs#L1121)

It's not ignored, even though it appears as such from the code. That provider argument is passed to the interpolated string handler in the code the compiler generates for the call; that's the purpose of the [InterpolatedStringHandlerArgument] you see in the method's signature.

For example, with this code [SharpLab](https://sharplab.io/#v2:EYLgtghglgdgPgAQAwAIEEYB0BxANge2AlygC8IAXKfGAbgFgAoZNLAFQFMAPCh5gZlYA2NACYUAYRRMA3kxQK0gjCIQAWFAFkAFAGUKAJ1gBzAEIBXKLgAmHAymCWbdgDQpYFFDHNhgdgJQoALwAfPKKEY5WtgaYAIIADgkcMNYAMrAc2hLmuBTmBhwAkjAAZviYJQBuEEYQMBQ5eQUcbgAkAEQAasTmHCAoMt6+dgC+Hf58o0A):
```C#
    public static void M(StringBuilder builder, int number) =>
        builder.AppendLine(CultureInfo.InvariantCulture, $"Value: {number}");
```
the compiler emits the equivalent of this:
```C#
    public static void M(StringBuilder builder, int number)
    {
        IFormatProvider invariantCulture = CultureInfo.InvariantCulture;
        StringBuilder.AppendInterpolatedStringHandler handler = new StringBuilder.AppendInterpolatedStringHandler(7, 1, builder, invariantCulture);
        handler.AppendLiteral("Value: ");
        handler.AppendFormatted(number);
        builder.AppendLine(invariantCulture, ref handler);
    }
```

The overload was not added by mistake nor will it be removed.

**Comment by yfital** [comment]
@stephentoub first of all, thank you for the detailed response.
I'm familier with string interpolation just missed the insertion into the attribute.

I do have a few conceptual questions here though as an end user:
1. I did not "request" to move towards the new interpolation method (of course I want it for the performance boost, but its "behind the scenes" completely from a developer point of view) - e.g. string interpolation now became a sort of breaking change for **some** developers (workaround is simpe of course, as i will probably add supression either for the CA or maybe just for SB).
2. What are we "fixing"? As it is, when the original (final) string was sent in a specific format, if there was a need to provide an IFormatProvider, I would have expected to see it before as well, so, does this mean that CA1305 should have caught all string interpolations in the code and mark them as warning? I hope my point is clear.
Do you have an example see where a format provider would be passed like that (externally to the interpolation) and not inside it in specific places the developer needed it? I admit, I have a hard time picturing it

**Comment by stephentoub** [comment]
>  string interpolation now became a sort of breaking change for some developers (workaround is simpe of course, as i will probably add supression either for the CA or maybe just for SB).

Any time we add anything it can possibly break someone somewhere, e.g. if we add a new instance method C.M(), the new instance method M will now be preferred over some extension method M you may have defined over C.  In this case, we added a new method, which cause an existing analyzer (which, btw, is not a warning by default but which your project elevated to being a warning) to issue a new diagnostic.

> What are we "fixing"?

If you previously had:
```C#
stringBuilder.AppendLine($"{someNumber}");
```
that number would have been formatted according to the current culture.  You've chosen to enable https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1305, which flags when "A call is made to a method that has an overload that accepts a [System.IFormatProvider](https://learn.microsoft.com/en-us/dotnet/api/system.iformatprovider) argument, and that overload isn't called." So now you're being told that you're using `AppendLine(string)` when you could be using `AppendLine(IFormatProvider, ...)`, which gives you the ability to specify the IFormatProvider that's used as part of the formatting; you might have had a bug here where you should have been doing that number formatting with CultureInfo.InvariantCulture rather than the default of CultureInfo.InvariantCulture.

If that's not something you care about in your code base, you can re-disable the analyzer.

**Comment by yfital** [comment]
I agree, I just stated that if I would have needed it fixed now, it needed to fix it before as well.
So it starts to sound like the CA (or a new one) should have been done on any location where you used a number for instance.

Because why will this:
* `var example = $"Value: {number}"` be without a warning, even if a second after I would do sb.AppendLine(example)
* `var example = new sb($"Value: {number}")` be without a warning (I don't see it has a ref interpolation overload) (<- this sounds like a missing part in the API?)
* `new sb (); sb.AppendLine($"Value: {number}")` will produce a warning

So I guess my bottom line is that my issue is consistency.
If I had an interpolation before into a regular string and now i want to put into a SB, my behavior suddently requires a "change", I'll be frank, it sounds a bit weird.

In any case, Thank you very much for the answers, maybe the above is more of a question to the CA repo? or do you believe current analysis is correct?

**Comment by stephentoub** [comment]
> So it starts to sound like the CA (or a new one) should have been done on any location where you used a number for instance.

The analyzer is doing what it's documented to do:
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1305
```
Cause
A call is made to a method that has an overload that accepts a [System.IFormatProvider](https://learn.microsoft.com/en-us/dotnet/api/system.iformatprovider) argument, and that overload isn't called.
```

A new analyzer/diagnostic ID could be used to flag some other condition; that condition would need to be defined and vetted.

> If I had an interpolation before into a regular string and now i want to put into a SB, my behavior suddently requires a "change", I'll be frank, it sounds a bit weird.

It doesn't "require" a change: the analyzer that you enabled is flagging something you asked to be notified about, that there's now a different member you should consider calling instead.

> Thank you very much for the answers

You're welcome.
