### ISSUE TITLE
SslStream.AuthenticateAsClient() is popping up a challenge for the system keychain on MacOS

### ISSUE THREAD

**Issue by ScotMac** [dotnet/runtime#99335]
### Description

For some reason, SslStream.AuthenticateAsClient() is trying to modify the system keychain on MacOS, and if it doesn't have permission, it is popping up a UI to get an userid/password that does have permission.

Screenshot of the UI:

<img width="1226" alt="Screenshot 2024-02-27 at 3 35 34 PM" src="https://github.com/dotnet/runtime/assets/32317065/6f1bdc60-4d39-408b-85c6-795a543ce2a5">

### Reproduction Steps

Call SslStream.AuthenticateAsClient() on  MacOS sw_vers 13.6.3 (doesn't appear to happen on 13.6).

### Expected behavior

Do SSL handshake.

### Actual behavior

See popup above.

### Regression?

Yes.

### Known Workarounds

None.

### Configuration

Have tried .NET 6 and .NET 8 and both exhibit the problem, along with MacOS 13.6.3+.

**Comment by vcsjones** [comment]
I cannot reproduce this on .NET 6, 8, or 9-preview1 on macOS 14.3.1. Here is the code I used.

```C#
using System;
using System.Net;
using System.Net.Sockets;
using System.Net.Security;

using TcpClient tcpClient = new();
await tcpClient.ConnectAsync("github.com", 443);
using SslStream ssl = new(tcpClient.GetStream());

SslClientAuthenticationOptions options = new() {
    TargetHost = "github.com",
};
await ssl.AuthenticateAsClientAsync(options);
Console.WriteLine("Okay all done: cert: " + ssl.RemoteCertificate.Subject);
```

1. Can you share the code you used to reproduce the issue?
2. If you have access to more than one Mac, does this reproduce for you with other Macs?

**Comment by ScotMac** [comment]
Also, your AuthenticateAsClient is very different from mine:

          m_sslstream = new SslStream(m_client.GetStream(), false, this.ValidateRemoteCertificate, null);
         
          m_sslstream.AuthenticateAsClient(!string.IsNullOrEmpty(conOption.Hostname) ? conOption.Hostname : 
                          (conOption.Host == null ? "" : conOption.Host), new X509Certificate2Collection { x509 }, SSLProtocol, false);

**Comment by ScotMac** [comment]
@vcsjones The x509Certificate2Collection ( "new X509Certificate2Collection { x509 }") is just a public cert that is associated with our list of trusted CAs.

**Comment by rzikm** [comment]
Do you have other machines where you can try to reproduce this problem?

Also, it would be great if you provided us a fully self-contained repro project if you feel like there is some specific setup needed. Otherwise it is hard to guess what is happening.
