### ISSUE TITLE
Added `needs-breaking-change-doc-created` label because this issue has the `breaking-change` label.

### ISSUE THREAD

**Issue by Juan48302** [dotnet/runtime#99342]
Added `needs-breaking-change-doc-created` label because this issue has the `breaking-change` label. 

1. [x] Create and link to this issue a matching issue in the dotnet/docs repo using the [breaking change documentation template](https://aka.ms/dotnet/docs/new-breaking-change-issue), then remove this `needs-breaking-change-doc-created` label.

Tagging @dotnet/compat for awareness of the breaking change.

_Originally posted by @msftbot[bot] in https://github.com/dotnet/runtime/issues/98245#issuecomment-1936653401_

**Comment by blowdart** [comment]
As an FYI I did this at  https://github.com/dotnet/docs/issues/39585, I dunno why another issue got created
