### ISSUE TITLE
The project does not have a valid ProjectGuid. WorkerExtensions.csproj

### ISSUE THREAD

**Issue by pmeems** [dotnet/runtime#99352]
### Description

I have a .NET8 isolated function. We use SonarQube and Fortify for code analysis.
When building our solution in our Azure DevOps pipeline using YAML:

```YAML
  - task: DotNetCoreCLI@2
    displayName: Build solution
    condition: succeeded()
    inputs:
      command: "build"
      projects: "$(Build.Repository.LocalPath)/**/*.sln"
      arguments: '/p:Configuration=${{ parameters.BuildConfiguration }} /p:Version=$(Build.BuildNumber) --no-restore'
```

We get this warning: 

```
##[warning]D:\Data\a9\644\.sonarqube\bin\targets\SonarQube.Integration.targets(369,5): Warning : The project does not have a valid ProjectGuid. Analysis results for this project will not be uploaded. Project file: C:\Users\gmDevOpsBuild$\AppData\Local\Temp\ejqusn2h.ojs\WorkerExtensions.csproj
D:\Data\a9\644\.sonarqube\bin\targets\SonarQube.Integration.targets(369,5): warning : The project does not have a valid ProjectGuid. Analysis results for this project will not be uploaded. Project file: C:\Users\gmDevOpsBuild$\AppData\Local\Temp\ejqusn2h.ojs\WorkerExtensions.csproj [C:\Users\gmDevOpsBuild$\AppData\Local\Temp\ejqusn2h.ojs\WorkerExtensions.csproj]
  Sonar: (WorkerExtensions.csproj) Project processed successfully
  Sonar: (MyProject.csproj) Project processed successfully
  WorkerExtensions -> C:\Users\gmDevOpsBuild$\AppData\Local\Temp\aijogs5z.umh\buildout\Microsoft.Azure.Functions.Worker.Extensions.dll
```

SonarQube treats it as a warning, Fortify as an error.

Since this project is not mine, I assume it comes from .NET.

### Reproduction Steps

Create a new .NET8 isolated function app, enable SonarQube and build the solution on an agent in Azure DevOps.

I don't see this warning/error when building on my devseat using Visual Studio v17.9.2.
I do see in the Output:
```
3>Determining projects to restore...
2>Restored C:\Users\***\AppData\Local\Temp\2\5wxs0hbl.ltv\WorkerExtensions.csproj (in 2.5 sec).
2>WorkerExtensions -> C:\Users\***\AppData\Local\Temp\2\5wxs0hbl.ltv\buildout\Microsoft.Azure.Functions.Worker.Extensions.dll
3>Restored C:\Users\MEEMSPAU\AppData\Local\Temp\2\femm3y2m.jjq\WorkerExtensions.csproj (in 1.56 sec).
3>WorkerExtensions -> C:\Users\***\AppData\Local\Temp\2\femm3y2m.jjq\buildout\Microsoft.Azure.Functions.Worker.Extensions.dll
```

### Expected behavior

I expect my solution to compile without any warning and that SonarQube and Fortify don't break on generated code.

### Actual behavior

```
##[warning]D:\Data\a9\644\.sonarqube\bin\targets\SonarQube.Integration.targets(369,5): Warning : The project does not have a valid ProjectGuid. Analysis results for this project will not be uploaded. Project file: C:\Users\gmDevOpsBuild$\AppData\Local\Temp\ejqusn2h.ojs\WorkerExtensions.csproj
D:\Data\a9\644\.sonarqube\bin\targets\SonarQube.Integration.targets(369,5): warning : The project does not have a valid ProjectGuid. Analysis results for this project will not be uploaded. Project file: C:\Users\gmDevOpsBuild$\AppData\Local\Temp\ejqusn2h.ojs\WorkerExtensions.csproj [C:\Users\gmDevOpsBuild$\AppData\Local\Temp\ejqusn2h.ojs\WorkerExtensions.csproj]
  Sonar: (WorkerExtensions.csproj) Project processed successfully
  Sonar: (MyProject.csproj) Project processed successfully
  WorkerExtensions -> C:\Users\gmDevOpsBuild$\AppData\Local\Temp\aijogs5z.umh\buildout\Microsoft.Azure.Functions.Worker.Extensions.dll
```

### Regression?

Not sure. This is our first isolated function app. We do have some in-proc .NET6 function apps.
They don't show this kind of behavior.

### Known Workarounds

For now, we disable running Fortify, but that is just temporarily allowed.

### Configuration

We use this global.json:
```json
{
  "sdk": {
    "version": "8.0.200",
    "rollForward": "latestMinor",
    "allowPrerelease": false
  }
}
```

### Other information

I also reported this on SonarQube: https://community.sonarsource.com/t/azuredevops-pipeline-reports-invalid-project-guid-for-temp-generated-workerextensions-csproj/91238/12

**Comment by tannergooding** [comment]
`ProjectGuid` isn't really a thing in SDK based projects. https://github.com/dotnet/msbuild/issues/3923 has some more details

Historically it's really only been there for VS, so it sounds like the SonarQube version you're using isn't aware of modern project files.

**Comment by danmoseley** [comment]
@rainersigwald  are project GUIDs still a thing? I would have expected VS to key off the imports/SDKs

**Comment by rainersigwald** [comment]
My understanding is that VS sometimes internally synthesizes a GUID for its own purposes but I definitely don't expect one to be necessary in .NET projects these days. I agree with @tannergooding that "check version of SonarQube" is the best next step.

**Comment by pmeems** [comment]
Thanks all for your quick replies. I'll contact SonarQube and ask them to solve this.

I'll close this issue.
