### ISSUE TITLE
[Wasm][Interp] mono_raise_exception implementation problems

### ISSUE THREAD

**Issue by Nemo-G** [dotnet/runtime#99366]
### Description

When targeting HOST_WASM and compiled without AOT, when I have my customized dll and icall/pinvoke native implementation compiled together with dotnet/runtime, I would like to invoke `mono_raise_exception` to raise a managed exception and hope the program continues. 

However as the current call stack, calling mono_raise_exception will have `function signature mismatch` error. This is because the current call will finally hit https://github.com/dotnet/runtime/blob/4e86b1c63d9c41c6bfb6f42710be907199ce2671/src/mono/mono/mini/exceptions-wasm.c#L17, which doesn't even match signature `void (*mono_raise_exception) (MonoException *ex)`

I was wondering why it is implemented like this? Any plan to improve at least keep a correct function signature?

### Reproduction Steps

Invoke `mono_raise_exception` in icall/pinvoke functions

### Expected behavior

Catch exception and make program continue to run with no termination

### Actual behavior

the program will terminate

### Regression?

No. 

### Known Workarounds

1. I enable this eh https://github.com/dotnet/runtime/blob/4e86b1c63d9c41c6bfb6f42710be907199ce2671/src/mono/mono/mini/mini-exceptions.c#L248 if HOST_WASM (It does  `mono_handle_exception` and setup a managed exception ctx and throw which is all i need)
2. I wrap a try...catch block around https://github.com/dotnet/runtime/blob/4e86b1c63d9c41c6bfb6f42710be907199ce2671/src/mono/mono/mini/interp/interp.c#L2346 and https://github.com/dotnet/runtime/blob/4e86b1c63d9c41c6bfb6f42710be907199ce2671/src/mono/mono/mini/interp/interp.c#L1810 , since they both have INTERP_PUSH_LMF_WITH_CTX and pop lmf around, so I assume it can make sure the stack can be restored to make program continue.

### Configuration

.NET8 and .NET9 alpha
.\build.cmd -os browser -subset mono+libs 
It should be browser agnostic.

### Other information

I can provide PR but let's first make sure it is correct.

**Comment by vargaz** [comment]
There is no portable way to 'throw' a c# exception from native code, neither from icalls nor pinvokes. The native code should return some error information to the managed code (like a created exception object), and the managed code should throw it.

**Comment by Nemo-G** [comment]
> There is no portable way to 'throw' a c# exception from native code, neither from icalls nor pinvokes. The native code should return some error information to the managed code (like a created exception object), and the managed code should throw it.

Let me clarify the situation. It is part of unity calling convention.  Let me show you what an icall native impl looks like.

void SCRIPT_CALL_CONVENTION someIcall(ICallType_ReadOnlyUnityEngineObject_Argument obj, ICallType_String_Argument name)
{
	ScriptingExceptionPtr exception = SCRIPTING_NULL;
	{
// .. do some stack checking stuff
		Marshalling::ReadOnlyUnityObjectMarshallerNotNull<ICallType_Generated_UnityEngine_Object> obj_marshalled;
		Marshalling::StringMarshaller name_marshalled;
		Marshalling::Marshal(&obj_marshalled, &obj, &exception);
		Marshalling::Marshal(&name_marshalled, &name, &exception);
		if (exception != SCRIPTING_NULL)
		{
			goto handle_exception;
		}

		if (obj_marshalled.IsNull())
		{
			exception = Scripting::CreateNullExceptionObject(obj);
			goto handle_exception;
		}

		set_back_marshalled_obj(obj_marshalled, name_marshalled);
		return;
	}

handle_exception:
	mono_raise_exception(exception);
}

What we do is  raising exception and handle it in upper try...catch block and resume the program. What I want to confirm is that for my particular case, the workaround is correct.

**Comment by Nemo-G** [comment]
All I would like to do is just restore the stack. 
It doesn't need to be a try...catch. I've also tried setjmp/longjmp but there is another problem there.  It seems the `testSetjmp` cannot correctly match the setjmpid I set before do_icall, but that is another story.

**Comment by vargaz** [comment]
The workaround could work. You will need to pass the exception to the runtime for handling. You can do that by calling
mono_error_set_pending_exception () which will set the pending exception for the current thread.

**Comment by Nemo-G** [comment]
Thanks for the clarification! @vargaz 

Regarding `mono_error_set_pending_exception` I'm a bit confused about when shall it be called? Like after the stack restored? What if it is not called?

Another question is that, with the current workaround, the mono error will be logged twice. the first stack was like 
![image](https://github.com/dotnet/runtime/assets/4470810/178a57bd-0a82-4e74-93d6-01b990e4149f)
And the second was 
![image](https://github.com/dotnet/runtime/assets/4470810/8d10d001-8b8c-45a3-b709-ac3ee17c9131)

Only the second one is expected. The first one was logged by mono_handle_exception.

**Comment by vargaz** [comment]
On wasm, mono_raise_exception () will throw a dummy c++ exception which can be caught by calling ```mono_llvm_cpp_catch_exception()```.

So you still have to somehow send the c# exception to the runtime, and that can be done by calling mono_set_pending_exception (), the runtime code checks for pending exceptions all over the place.

So I guess a working version for the throw site would be:
```
mono_set_pending_exception (ex);
mono_raise_exception (ex);
```

**Comment by Nemo-G** [comment]
I just did a test in which I inserted mono_set_pending_exception before raising an exception. The result was that the stack trace of the managed code was duplicated in the output. There must be existing code within Unity that already performs this action.

Thanks again @vargaz  for your confirmation! 
I will conduct additional tests and close the issue if no further problems arise.
