### ISSUE TITLE
System.Security.Cryptography.Rsa.Tests.EncryptDecrypt.Decrypt_Pkcs1_ErrorsForInvalidPadding(Byte[] data)

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#99369]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=591354
Build error leg or test failing: System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_TrySpan.Decrypt_Pkcs1_ErrorsForInvalidPadding
Pull request: https://github.com/dotnet/runtime/pull/99287

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "at System.Security.Cryptography.Rsa.Tests.EncryptDecrypt.Decrypt_Pkcs1_ErrorsForInvalidPadding(Byte[] data)",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=591354
**Error message validated:** `[at System.Security.Cryptography.Rsa.Tests.EncryptDecrypt.Decrypt_Pkcs1_ErrorsForInvalidPadding(Byte[] data)`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 3/6/2024 6:01:33 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[591354](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591354)|dotnet/runtime|[System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_TrySpan.Decrypt_Pkcs1_ErrorsForInvalidPadding](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591354&view=ms.vss-test-web.build-test-results-tab&runId=14285344&resultId=175296)|dotnet/runtime#99287|
|[590185](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590185)|dotnet/runtime|[System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Span.Decrypt_Pkcs1_ErrorsForInvalidPadding](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590185&view=ms.vss-test-web.build-test-results-tab&runId=14244398&resultId=186991)|dotnet/runtime#99263|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|2|2|

**Comment by lewing** [comment]
happened twice today

**Comment by vcsjones** [comment]
Clearly my test writing efforts would be better spent on buying lottery tickets.
