### ISSUE TITLE
X509Certificate2 class cannot create cert for algorithm 1.3.101.112

### ISSUE THREAD

**Issue by xky0007** [dotnet/runtime#99388]
### Description

X509Certificate2 class cannot create cert for algorithm 1.3.101.112 pem files.
`System.Security.Cryptography.CryptographicException: ''1.3.101.112' is not a known key algorithm.'`

### Reproduction Steps

Find any `1.3.101.112` algorithm pem file and use ` X509Certificate2.CreateFromPemFile`.

### Expected behavior

Create correct cert.

### Actual behavior

`System.Security.Cryptography.CryptographicException: ''1.3.101.112' is not a known key algorithm.'`

**Comment by vcsjones** [comment]
Closing as a duplicate of https://github.com/dotnet/runtime/issues/63174.

.NET today does not support Ed25519, which is the OID indicated in the error. The primitive is not supported, nor is its use in X.509.

Please feel free to re-open the issue if you think this is different from the linked issue.
