### ISSUE TITLE
Documentation and capabilities for filtering tests to run are inadequate

### ISSUE THREAD

**Issue by davidwrighton** [dotnet/runtime#99384]
1. There is no documentation on how to run an individual test, or a filtered set of tests in https://github.com/dotnet/runtime/blob/main/docs/workflow/testing/coreclr/testing.md . The closest is a small section which says "Guide on how to run tests without a Main() Method coming soon!"

2. Said filtering that is actually possible uses the internal type/method name of the test, and not the test names which are printed to the console and visible just before any errors that occur.

**Comment by jkoritzinsky** [comment]
Fixed by #100709 and #105238
