### ISSUE TITLE
Behaviour change in HTTPHeaders.Add between .NET 6.0 and 8.0?

### ISSUE THREAD

**Issue by stewcelliott** [dotnet/runtime#99416]
After upgrading a project from .NET 6.0 to 8.0, I've noticed a behaviour change relating to HTTPHeaders.Add. Previously the below code block would run without issue, even if `string.Join("; ", cookies.Select(c => c.ToString()))` produced an empty string.

```c#
        public static bool TryRemoveCookieValue(this RequestTransformContext context, CookieHeaderValue cookie)
        {
            if (TryParseCookies(context, out var cookies)
                && cookies != null
                && cookies.Contains(cookie))
            {
                cookies.Remove(cookie);
                context.ProxyRequest.Headers.Remove(HeaderNames.Cookie);
                // Exception thrown on this line
                context.ProxyRequest.Headers.Add(HeaderNames.Cookie, string.Join("; ", cookies.Select(c => c.ToString())));

                return true;
            }
            return false;
        }
```
However since updating, this now throws a FormatException - "The format of value '' is invalid." I have reverted back to .NET 6.0 and confirmed that the issue is not present on that version. 

`context` in the above example is of type `Yarp.ReverseProxy.Transforms.RequestTransformContext`. The Yarp.ReverseProxy version in use is 2.1.0 and was unchanged during this upgrade.

The full stack trace indicates this exception is coming from HttpHeaderParser.ParseValue:

```
   at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor descriptor, String value)
   at Yarp.ReverseProxy.Transforms.RequestTransformContextExtensions.TryRemoveCookieValue(RequestTransformContext context, CookieHeaderValue cookie) in
```
I can't find anything in the release notes for .NET 7 or 8 or in the commit histories of HttpHeaderParser.cs or HttpHeaders.cs that would explain this. Have I missed anything?

### Steps to reproduce

- Attempt to add a cookie header to a RequestTransformContext.HTTPRequestMessage with an empty string as the value.

**Comment by MihaZupan** [comment]
This was introduced in 7.0 by #67455.

@ManickaP I don't think the intention was to also restrict empty values, right?
Possibly a copy-paste error that [this part of the parser](https://github.com/dotnet/runtime/blob/691b423c273a7d6108cf33f7a1ebbade6b8623a7/src/libraries/System.Net.Http/src/System/Net/Http/Headers/CookieHeaderParser.cs#L21-L26) was copied over unmodified.

**Comment by ManickaP** [comment]
Maybe, but from what I'm getting from the spec: https://httpwg.org/specs/rfc6265.html#sane-cookie It should have at least one cookie-pair.

**Comment by Neme12** [comment]
Even if the change is desired, there should probably be a test added for it?

**Comment by rokonec** [comment]
We consider current behavior as by design as it now follows specs. 
Unit test with expected behavior has been added.
