### ISSUE TITLE
[jitstressregs] Interop/Swift/SwiftErrorHandling/SwiftErrorHandling fails

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#99414]
Example run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=588357&view=results
Console log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-99093-merge-3e961c67e325430c8b/Interop/1/console.dcc96f17.log?helixlogtype=result

```
BEGIN EXECUTION
/tmp/helix/working/A16108B8/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true SwiftErrorHandling.dll ''
[createdump] Gathering state for process 61532 
[createdump] Crashing thread 40c016 signal 11 (000b)
[createdump] Writing crash report to file /cores/coredump.61532.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /cores/coredump.61532.dmp
[createdump] Written 360276104 bytes (87958 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 6660ms
Expected: 100
Actual: 139
END EXECUTION - FAILED
```

FYI @amanasifkhalid cc @dotnet/jit-contrib

**Comment by jakobbotsch** [comment]
An alternative way may be to add a `SwiftError` known argument that always is just constant 0. It's a bit odd, but I guess not too bad (and models nicely that actually the register's value matters). You would also be able to remove `GTF_CALL_M_SWIFT_ERROR_HANDLING` and switch it to a check for that well known argument.

**Comment by amanasifkhalid** [comment]
> An alternative way may be to add a SwiftError known argument that always is just constant 0

So this would behave the same way the well-known SwiftSelf arg works, right? I like that consistency; let me give it a try.

**Comment by jakobbotsch** [comment]
> So this would behave the same way the well-known SwiftSelf arg works, right?

Right.
