### ISSUE TITLE
[Windows.Networking.Connectivity.WwanDataClass] Enum is missing 5G

### ISSUE THREAD

**Issue by htcfreek** [dotnet/runtime#99420]
The `WwanDataClass` enum in `Windows.Networking.Connectivity` don't has a value for 5G (5G, 5G+; 5G, 5G FR1, 5G FR2).

This is a problem as `WwanConnectionProfileDetails.GetCurrentDataClass Method` from Namespace `Windows.Networking.Connectivity` would return `64` if connected to a 5G WWan. And for `64` the enum has no value.

**Steps to reproduce:**
1. Connect to a 5G mobile network.
2. Call `NetworkInformation.GetInternetConnectionProfile().WwanConnectionProfileDetails.GetCurrentDataClass()`.
3. Try to get the enum value for the result from step 2.

---
OS: Win10 22H2
.Net: Desktop Runtime 4.6 or higher

**Comment by teo-tsirpanis** [comment]
WinRT APIs are not being developed in this repository. I am not entirely sure of what the most appropriate venue for this issue would be, but I would suggest you to report this through the [Windows Feedback Hub app](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332).
