### ISSUE TITLE
Iterating Through Nullable Properties is Inconsistent. 

### ISSUE THREAD

**Issue by geekywarrior** [dotnet/runtime#99427]
Hello, 
I'm attempting to iterate through nullable properties on a class and am getting inconsistent results. I'm not sure if my approach to do this is incorrect or if I'm stumbling upon on a bug.

Consider these two example classes.
```
public class Example_One{

  public string p1 {get;set;} = "";

  public string? p2 {get;set;}

  public string p3 {get;set;}
}

public class Example_Two{

  public string q1 {get;set;} = "";

  public string? q2 {get;set;}

  public string? q3 {get;set;}
}
```

If I then create the following code to iterate through and identify the nullable properties, I get inconsistent results.

```using System.Runtime.CompilerServices
//Check Example One for nullable properties - Output p2
var example_one_props = typeof(Example_One).GetProperties();
foreach(var prop in example_one_props){
	if(prop.CustomAttributes.Where(p => p.AttributeType == typeof(NullableAttribute)).Any()) Console.WriteLine(prop.Name);
}


//Check Example Two for nullable properties - Output q1 which is Not Nullable
var example_two_props = typeof(Example_Two).GetProperties();
foreach (var prop in example_two_props)
{
	if (prop.CustomAttributes.Where(p => p.AttributeType == typeof(NullableAttribute)).Any()) Console.WriteLine(prop.Name);
}
```

From my testing, I can replicate the following behavior.

1. If I only have (2) properties, then if one is nullable, it will have a CustomAttribute with a type of NullableAttribute
2. If I have 3+ properties, and there are multiple non-nullable properties, then the nullable properties will have a CustomAttribute with a type of NullableAttribute
3. **If I have 3+ properties, and all but one property is nullable, the the non nullable property will have a CustomAttribute of type NullableAttribute**. This to me appears incorrect but I'm curious if I'm way offbase and using something that isn't meant to be used.

**Comment by vcsjones** [comment]
You should not be inspecting the nullable attributes yourself. You should use a [`NullabilityInfoContext`](https://learn.microsoft.com/dotnet/api/system.reflection.nullabilityinfocontext) to determine if a member is nullable or not because nullability is more complex than the presence or lack of a single attribute.

For example:


```C#
var example_one_props = typeof(Example_One).GetProperties();
var context = new NullabilityInfoContext();
foreach(var prop in example_one_props){
    var info = context.Create(prop);
    if (info.ReadState == NullabilityState.Nullable)
    {
        Console.WriteLine(prop.Name);
    }
}
```

**Comment by geekywarrior** [comment]
Ah ha! 
Perfect, thank you very much @vcsjones
