### ISSUE TITLE
Flush(true) does not call fsync on first attempt 

### ISSUE THREAD

**Issue by ashenBlade** [dotnet/runtime#99445]
### Description

`FileStream.Flush(true)` method, according to [documentation](https://learn.microsoft.com/en-us/dotnet/api/system.io.filestream.flush?view=net-8.0#system-io-filestream-flush(system-boolean)) must force flushing all buffers including OS page cache:

```
Use this overload when you want to ensure that all buffered data in intermediate file buffers is written to disk.

When you call the [Flush](https://learn.microsoft.com/en-us/dotnet/api/system.io.filestream.flush?view=net-8.0) method, the operating system I/O buffer is also flushed.
```

In unix systems this performed using `fsync` call with file descriptor specified, but in .NET 7 first call to `FileStream.Flush(true)` is just ignored - calls to this method only after first attempt lead to `fsync` invocation

### Reproduction Steps

Code:
```
using var file = new FileStream("sample.txt", FileMode.OpenOrCreate);
file.Write("hello, world"u8);
file.Flush(true);
```

Compile with .NET 7 and run with `strace` to trap syscalls
```
dotnet build -c Release -o app
strace ./app/Application
```

### Expected behavior

`fsync` syscall was invoked

### Actual behavior

no `fsync` with in whole trace

### Known Workarounds

If you add second `Flush(true)` after first, there will be `fsync` (as every `Flush(true)` after also will call `fsync`)

### Configuration

`dotnet --list-runtimes`:
- Microsoft.AspNetCore.App 6.0.22 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
- Microsoft.AspNetCore.App 7.0.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
- Microsoft.AspNetCore.App 8.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
- Microsoft.NETCore.App 6.0.22 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
- Microsoft.NETCore.App 7.0.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
- Microsoft.NETCore.App 8.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

OS:
- Ubuntu 22.04.3 LTS x86_64
- Kernel: 6.2.0-39-generic

Hardware:
- CPU: AMD Ryzen 5 6600H

**Comment by adamsitnik** [comment]
Hi @ashenBlade 

When `FileStream.Flush(true)` is invoked it calls the underlying strategy which by default is the buffered strategy:

https://github.com/dotnet/runtime/blob/d0c8f836b5d46cd7c24fb7b7a8292b45d97f8e42/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.cs#L389-L396

Which writes the data (if any):

https://github.com/dotnet/runtime/blob/d0c8f836b5d46cd7c24fb7b7a8292b45d97f8e42/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/BufferedFileStreamStrategy.cs#L762-L765

and just calls the wrapped strategy:

https://github.com/dotnet/runtime/blob/d0c8f836b5d46cd7c24fb7b7a8292b45d97f8e42/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/BufferedFileStreamStrategy.cs#L777-L778

Which on every OS just calls the helper if the `boolean` value is `true` and the `Stream.CanWrite` returns true:

https://github.com/dotnet/runtime/blob/d0c8f836b5d46cd7c24fb7b7a8292b45d97f8e42/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/OSFileStreamStrategy.cs#L137-L142

And the helper performs actual sys-call:

https://github.com/dotnet/runtime/blob/d0c8f836b5d46cd7c24fb7b7a8292b45d97f8e42/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/FileStreamHelpers.Unix.cs#L40-L42

I can't see any way for a bug here, please re-run your tests and verify what you see.

Thanks,
Adam
