### ISSUE TITLE
Add PeekByte() to BufferedStream

### ISSUE THREAD

**Issue by fawzibr** [dotnet/runtime#99450]
I don't understand why something as simple (and obvious) as PeekByte() was not added to BufferedStream. Everything is already there just removing a '++' from the ReadByte function?

This is the current ReadByte() in [BufferedStream.cs](https://github.com/microsoft/referencesource/blob/master/mscorlib/system/io/bufferedstream.cs#L803):
```
    public override Int32 ReadByte() {
        EnsureNotClosed();
        EnsureCanRead();
        if (_readPos == _readLen) {
            if (_writePos > 0) FlushWrite();
            EnsureBufferAllocated();
            _readLen = _stream.Read(_buffer, 0, _bufferSize);
            _readPos = 0;
        }
        if (_readPos == _readLen) return -1;
        Int32 b = _buffer[_readPos++];        
        return b;
    }
```

I think this would be a working PeekByte():

```
    public override Int32 PeekByte() {
        EnsureNotClosed();
        EnsureCanRead();
        if (_readPos == _readLen) {
            if (_writePos > 0) FlushWrite();
            EnsureBufferAllocated();
            _readLen = _stream.Read(_buffer, 0, _bufferSize);
            _readPos = 0;
        }
        if (_readPos == _readLen) return -1;
        Int32 b = _buffer[_readPos];        
        return b;
    }
```

**Comment by danmoseley** [comment]
I don't know, but if you want to make an API proposal you'll want to close this and use the other issue template.

**Comment by fawzibr** [comment]
I thought this was the place, for me API seemed like 'creating a full new API for something', this looks more like the 'enhancement'  or 'feature request'. So API issues is for feature requests as well?

Anyway closing this.
