### ISSUE TITLE
[mono] Missing box optimizations in the interpreter

### ISSUE THREAD

**Issue by vargaz** [dotnet/runtime#99463]
The mono JIT has a bunch of optimizations for common IL code sequences like box+brtrue, box+unbox.any. The interpreter is currently missing these.

**Comment by vitek-karas** [comment]
@BrzVlad

**Comment by BrzVlad** [comment]
Any particular test case where you see this ? MINT_BOX should produce a value that is marked as non null, which is handled during cprop when we fold branches. I see we also have a pattern for recognizing box + unbox.any in transform.c.

**Comment by vargaz** [comment]
There are a bunch of cases in method-to-ir.c in the CEE_BOX: section. An example is box+isinst, which is produced by:
```
    public static bool box<T> (T t) {
        return (t is string);
    }
```

**Comment by fanyang-mono** [comment]
This is a dup of #99379. There is a test in my PR (https://github.com/dotnet/runtime/pull/99081) that is failing without this - `Validate_RecognizedOpCodeSequences_Scenarios ` in `src/tests/Loader/classloader/generics/ByRefLike/Validate.cs`

**Comment by fanyang-mono** [comment]
Let's move future discussions to #99379, since that issue is linked to the failing test. Closing this issue now.
