### ISSUE TITLE
.NET 8.0 MAUI App has exited with code 2147943792 (0x80070570)

### ISSUE THREAD

**Issue by r2d2Proton** [dotnet/runtime#99465]
### Description

Does this (https://github.com/dotnet/core/blob/main/release-notes/8.0/known-issues.md) apply and how do I configure it in my CS project - edit the csproj file or through NuGET Package Manager for the Solution?

~~~text
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net8.0-android</TargetFrameworks>
        <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.19041.0</TargetFrameworks>
        <OutputType>Exe</OutputType>

        <UseMaui>true</UseMaui>
        <MauiVersion>8.0.7</MauiVersion>
        <UseMauiEssentials>true</UseMauiEssentials>

~~~

Also, output window shows

~~~text
(CoreCLR: DefaultDomain): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.

(CoreCLR: clrhost): Loaded 'C:\...\.build\.bin\App\Debug\net8.0-windows10.0.19041.0\win10-x64\AppX\App.dll'. Symbols loaded.

(CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\System.Runtime.dll'. Skipped loading symbols....
(CoreCLR: clrhost): Loaded 'C:\...\.build\.bin\App\Debug\net8.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.dll'....
(CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\System.Runtime.InteropServices.dll'....
(CoreCLR: clrhost): Loaded 'C:\...\.build\.bin\App\Debug\net8.0-windows10.0.19041.0\win10-x64\AppX\WinRT.Runtime.dll'....
(CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\System.Collections.Concurrent.dll'....
(CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\System.Collections.dll'....
(CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\System.Threading.dll'....
(CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\System.Runtime.CompilerServices.Unsafe.dll'....
(CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\System.Private.Uri.dll'....
(CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\System.ObjectModel.dll'....
(CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\System.ComponentModel.dll'....
(CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\System.Numerics.Vectors.dll'....
App.exe' has exited with code 2147943792 (0x80070570).
~~~

### Reproduction Steps

Not sure. 

### Expected behavior

Application should run.

### Actual behavior

Does not run.

**Comment by elinor-fung** [comment]
@r2d2Proton could you provide some more information here?

- What version of Visual Studio are you using? I'm assuming this Visual Studio based on the mention of the output window.
- What version of Windows are you on?
- Is this just a default template new MAUI app? Or something more complex?
- Can you check whether you might be hitting https://github.com/dotnet/maui/issues/12080?

**Comment by r2d2Proton** [comment]
@elinor-fung Thank you for the response Elinor.

I am using VS2022 17.9.3 Community Edition.
Windows 11 Pro. 23H2. 

When I manually tried to install another Appx the error returned was the same as my own application.

But if I try to install the C:\Users\Jerry.nuget\packages\runtime.win10-x64.microsoft.net.uwpcoreruntimesdk\2.2.12\tools\Appx\Microsoft.NET.CoreRuntime.2.2.appx by double clicking on it and choosing "Install" I get the following error :

```text
App installation failed with error message: Common::Deployment::MsixvcStagingSession::GetManifestReader in MsixvcStagingSession failed with error 0x80070570. (0x80070570)
```

Someone suggested it "maybe self-signed, developer packs aren't working?"

My check of the disk returned no errors. Microsoft Store was able to install LinkedIn.


![Disk01](https://github.com/dotnet/runtime/assets/4054178/8edfdd41-1fb8-496e-9e75-20e47ce80262)

![Disk02](https://github.com/dotnet/runtime/assets/4054178/ae2c7f83-f65e-4038-9c3c-c0458e0774dc)

![LinkedIn](https://github.com/dotnet/runtime/assets/4054178/df02517d-87b0-4131-98a7-7f3b838028e6)

![Updates](https://github.com/dotnet/runtime/assets/4054178/c3bb4905-a192-40ec-985e-b55bb5eedd76)

**Comment by r2d2Proton** [comment]
@jkotas The problem occurs also on my .NET 8.0 MAUI app. Also, noticed the exact same error occuring on an older UWP app:

https://github.com/CommunityToolkit/Lottie-Windows

**Comment by r2d2Proton** [comment]
@vcsjones @jkotas @jeffschwMSFT @elinor-fung Please note I can create and debug WinUI 3 Visual Studio 17.9.3 templates as expected. However, .NET 8.0 MAUI template failed. With the same error that has been preventing me from launching my own application. And the same error from Lottie-Windows.

![WinUIApp1-03](https://github.com/dotnet/runtime/assets/4054178/defdd64f-e903-462f-976a-24e59007f6fc)
![WinUIApp1-01](https://github.com/dotnet/runtime/assets/4054178/71d4d35e-66be-4edc-b461-e80f8f293683)
![WinUIApp1-02](https://github.com/dotnet/runtime/assets/4054178/6695cd3e-94f6-4018-b84e-9906d353f689)

**Comment by jkotas** [comment]
> However, .NET 8.0 MAUI template failed.

.NET 8.0 MAUI template works for me fine.

Could you please give us the exact steps for reproducing the problem? Check https://github.com/dotnet/maui/issues/12080#issue-1495748327 for an example of good "Repro steps".

**Comment by r2d2Proton** [comment]
@jkotas Using VS 2022 17.9.3 Community Edition I created the project using the .NET MAUI project. Pressed F5. Got the same error. WinUI templates worked fine. Setting up my laptop now, installing Visual Studio, and will try again. Will report back my findings.

**Comment by r2d2Proton** [comment]
@jkotas Works really nice on my new laptop. Shoot very nice graphics with the car :D I am going to uninstall Visual Studio from my desktop and perform a fresh install. I will report back once I am done. Maybe tomorrow. . . .

**Comment by r2d2Proton** [comment]
@jkotas thank you for the help. After formatting my internal hard-drive and reinstalling Windows 11, and Visual Studio, the build, deploy, and debug work as expected. But one notable difference is that I had upgraded to Pro as in Windows 11 Pro from Home. The newly installed version was the Home edition.

**Comment by r2d2Proton** [comment]
@jkotas thank you for the help. After formatting my internal hard-drive and reinstalling Windows 11, and Visual Studio, the build, deploy, and debug work as expected. But one notable difference is that I had upgraded to Pro as in Windows 11 Pro from Home. The newly installed version was the Home edition.
