### ISSUE TITLE
SDL signoff requirements - enable MSVC warnings C4242 and C4244 (libunwind)

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#99471]
> __Please prioritize this work.__ We want to address BinSkim alerts early in the development cycle.

Per [the SDL guidelines](https://liquid.microsoft.com/Web/Object/Read/ms.security/Requirements/Microsoft.Security.SystemsADM.10086) (MSFT internal only), C/C++ warning **C4242** and **C4244** are required to be enabled, and fixing violations of it is mandatory.

In **src/native/external/libunwind_extras/CMakeLists.txt**, we also need to delete these two lines:

https://github.com/dotnet/runtime/blob/1e2fdb51249733756b6b52a00ab3843de8d65927/src/native/external/libunwind_extras/CMakeLists.txt#L143-L144

We will need to make changes to our local copy of libunwind as part of this. See the "What about third-party code?" section below.

Thanks for your assistance!

## Quick FAQ

__What code is bound to this requirement?__

This affects only _production_ code. Production code is generally defined as code which ships as part of the product and which runs on customer machines or which manages infrastructure, such as our build labs. Unit and functional test projects are not considered production code.

__Does this need to be backported?__

No backporting plans at this time. If actual bugs are found during this process, individual product teams have discretion to selectively backport into the next downlevel servicing vehicle.

__What about third-party code?__

This requirement applies to all code that MSFT builds from source, regardless of its provenance. Ideally any changes that we make to local forked copies can be submitted upstream as a PR so that the wider ecosystem can enjoy their benefits.

The recommended pattern - and what we did with zlib a while back - is to create a .patch file which contains our local fixes to libunwind, then commit this .patch file as part of the same PR where we make the changes. See https://github.com/dotnet/runtime/pull/91245 for an example of how this was done.

If this is impractical, exceptions to this requirement can be sought on an as-needed basis. However, exceptions are: (a) not guaranteed to be granted; and (b) time-constrained. The exception process is not intended to provide a permanent deferral of this work. Please contact the _fxsecurity_ alias if an exception is needed.

__What about C# and other languages?__

This requirement only affects C/C++ code. Requirements for other languages will be filed as separate issues.

**Comment by jkotas** [comment]
Related to #90359

**Comment by tommcdon** [comment]
@AaronRobinsonMSFT @janvorli

**Comment by filipnavara** [comment]
Here's a commit with most of the work done: https://github.com/dotnet/runtime/commit/71ab5257a7418cff299f863a93f98564964b11c3

Feel free to pick it up.
