### ISSUE TITLE
DEREF_AFTER_NULL in /src/coreclr/jit/fgopt.cpp

### ISSUE THREAD

**Issue by ellena13** [dotnet/runtime#99476]
The static analyzer has detected DEREF_AFTER_NULL: after having been compared to a NULL value at fgopt.cpp:1343, pointer '_tryEntryPrev_' is dereferenced at fgopt.cpp:1356.

https://github.com/dotnet/runtime/blob/dc45e96840243b203b13e61952230e225d2aac52/src/coreclr/jit/fgopt.cpp#L1342-L1356

There is a comment from the developers at 1335-1337: it follows that in this code block developers "_rely on the validity of the operation to obtain bbprev (and bbnext)_".

https://github.com/dotnet/runtime/blob/dc45e96840243b203b13e61952230e225d2aac52/src/coreclr/jit/fgopt.cpp#L1335-L1337

Besides, there ia another comment that also expresses hope for the implementation of _'tryEntryPrev != nullptr'_ above the debug assert (at fgopt.cpp:1351).

https://github.com/dotnet/runtime/blob/dc45e96840243b203b13e61952230e225d2aac52/src/coreclr/jit/fgopt.cpp#L1348-L1351

_Dereference of nullptr_ is a serious error that needs to be monitored. 

So if you are sure that _dereference of nullptr_ is impossible here? Why do do check it at fgopt.cpp:1343 **?**

https://github.com/dotnet/runtime/blob/dc45e96840243b203b13e61952230e225d2aac52/src/coreclr/jit/fgopt.cpp#L1343

---

Found by Linux Verification Center (portal.linuxtesting.ru) with SVACE.

Author E. Bykhanova (e.bykhanova@fobos-nt.ru).

**Comment by EgorBo** [comment]
Thanks for the suggestion. I presume it's just a redundant `(tryEntryPrev != nullptr)` check in the while loop.

**Comment by ellena13** [comment]
Does it mean that you are sure that there is no nullptr dereference here?

**Comment by EgorBo** [comment]
thanks for the report, filed https://github.com/dotnet/runtime/pull/102342
