### ISSUE TITLE
Q: Is building the CoreCLR runtime on Unix supported with FEATURE_EVENT_TRACE disabled?

### ISSUE THREAD

**Issue by omajid** [dotnet/runtime#99484]
I am trying to build the runtime in an environment where lttng-ust is not available.  Is building CoreCLR with `DFEATURE_EVENT_TRACE=0` to work around the lttng-ust availability an option? I tried a hack to pass the cmake argument `-DFEATURE_EVENT_TRACE=0`  and it doesn't seem to work. The build complains about event pipe types being undefined.

**Comment by jkotas** [comment]
> Is building the CoreCLR runtime on Unix supported with FEATURE_EVENT_TRACE disabled?

It is not tested or regularly used by anybody, so it is likely bit rotten. 

> lttng-ust is not available

If you just want to trim dependency on `lttng-ust`, undefining `FEATURE_EVENTSOURCE_XPLAT should work better.

**Comment by tommcdon** [comment]
Closing since we do not currently support FEATURE_EVENT_TRACE disabled
