### ISSUE TITLE
What be the best way to read text file that was written using Encoding.Default in .NET Framework

### ISSUE THREAD

**Issue by vladimir-cheverdyuk-altium** [dotnet/runtime#99486]
Hi

We have a lot of text files that were created in .NET Framework using `Encoding.Default`. When we are trying to read these files in .NET 6 and obviously the data is not correct because .NET Framework's `Encoding.Default` depends on current code page in Windows and in .NET 6 it is always UTF8.

What be the best way to create encoding that as close as possible to .NET Framework's one? Obvious case would be this:
```
int codePage = get windows current code page
Encoding encoding = Encoding.GetEncoding(codePage);
```
but there are much more code in .NET Framework that initializes `Encoding.Default`. Also I feel I need to do something special for Chinese, Korean and Japanese languages.

Thank you

**Comment by jkotas** [comment]
Try registering additional encodings using `Encoding.RegisterProvider(CodePagesEncodingProvider.Instance)`.

**Comment by vladimir-cheverdyuk-altium** [comment]
@jkotas thank you, I already did but the main problem that code in quite different between these frameworks and I don't know how to properly create encoding in the first place.

**Comment by jkotas** [comment]
It should be as what you have written above:
```
using System.Runtime.InteropServices;

static Encoding GetEncodingForCurrentCodePage()
{
    return Encoding.GetEncoding(GetACP());

    [DllImport("kernel32.dll")]
    extern static int GetACP();
}
```
Are you running into situations where this does not work?

**Comment by jkotas** [comment]
The extra code in .NET Framework are perf optimizations - you do not need to worry about those: https://github.com/microsoft/referencesource/blob/51cf7850defa8a17d815b4700b67116e3fa283c2/mscorlib/system/text/encoding.cs#L1404-L1413

**Comment by vladimir-cheverdyuk-altium** [comment]
Hi @jkotas. No, I didn't have problems yet because I just firstly would like to know how it is correct to avoid situation that it will not work for some rare used code page.
I'm mostly concerned that code in Encoding.GetEncoding is quite different. There are some new cases in .NET 6 but there are some cases that are unique to .NET Framework.

But if you will confirm that it is the same then we will use this approach.

**Comment by jkotas** [comment]
The extra code are just perf optimizations. The above snippet should work fine.

**Comment by vladimir-cheverdyuk-altium** [comment]
Thank you very much!
