### ISSUE TITLE
[netstandard2.1] Enum.GetValues gap

### ISSUE THREAD

**Issue by mwpowellhtx** [dotnet/runtime#99488]
### Description

Target `net 8`, I have `public static TEnum[] GetValues<TEnum>() where TEnum : struct, Enum`. Not available in the same signature under `netstandard2.1`.

### Reproduction Steps

`netstandard2.1` rather offers `public static TEnum[] GetValues(Type)`, which differs from `net 8`.

### Expected behavior

Provide `public static TEnum[] GetValues<TEnum>() where TEnum : struct, Enum` for `netstandard2.1` targets.

### Actual behavior

See above.

### Regression?

Broken API surface area.

### Known Workarounds

Forced to target `net 8` in my API surface area projects, that or fall back on the old stuff, which may also not be available in `net 8`, either.

### Configuration

Targeting `net 8` in my runtimes, but I might like to provide core assemblies targeting `netstandard` in an appropriate version as well.

### Other information

Not too long ago, I voiced this concern during one of the dotnet ASP.NET standups, Damian Edwards responded in a sort of wishy washy non-commital manner. The main concern is, keeping the API surface area current, tail wagging the dog. This is one of those gaps having fallen through the cracks.

**Comment by mwpowellhtx** [comment]
`GetValues(Type)` might be the path forward there.

From the comments, I'm not sure what this means, however, hasn't `enum` traditionally been int backed, by default? _[InvalidOperationException](https://learn.microsoft.com/en-us/dotnet/api/system.invalidoperationexception) .NET 8 and later versions: enumType is a Boolean-backed enumeration type._ Perhaps that could be clarified a bit, while we're here.

```csharp
// bool backed?
public enum MyBoolBacked : bool { ... } // not sure how that makes sense, really...
```

Of course, backing type may be specified as well, yes?

```csharp
public enum MyEnum : short { ... }

public enum MyIntEnum { ... } // int backed by default
```

**Comment by teo-tsirpanis** [comment]
[No new versions of .NET Standard will be released.](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-1-0#net-5-and-net-standard) You are encouraged to target a modern framework such as .NET 8 in your libraries. If you have a reason to support earlier frameworks and want to use `Enum.GetValues`, you can shim it like this:

```csharp
public static class EnumExtensions
{
    public static TEnum[] GetValues<TEnum>() where T : struct =>
#if NET5_0_OR_GREATER
        Enum.GetValues<TEnum>();
#else
        (TEnum[])Enum.GetValues(typeof(TEnum));
#endif
}
```

**Comment by mwpowellhtx** [comment]
Thank you for that bit of background explanation. Bit dissappointing, really, but not altogether surprising, all things considered. Percentage wise, as a community customer, 40-60 understandable.
