### ISSUE TITLE
Transactional File Manager

### ISSUE THREAD

**Issue by satyajit-behera** [dotnet/runtime#99498]
This is a common scenario to copy files to disk. Dotnet framework had a transactional file manager available.

Can we have the transactional file manager in dotnet core also?

Thanks

**Comment by roji** [comment]
> Dotnet framework had a transactional file manager available.

Which manager are you referring to exactly? I'm not aware of a Microsoft-provided .NET transactional file manager (but that doesn't mean one didn't exist).

**Comment by satyajit-behera** [comment]
@roji Thanks. Transactions used to work with files also in dotnet framework because it was running only in windows environment.

In dotnet core, it would be nice to include that in the framework itself.
There is one such library available (original was in codeplex with dotnet framework):
https://github.com/chinhdo/txFileManager
It may be nice to see something similar as part of the framework.

**Comment by roji** [comment]
> Transactions used to work with files also in dotnet framework because it was running only in windows environment.

Can you please point to any documentation or a code sample for this? As far as I'm aware, file APIs in .NET Framework did not interact with .NET Transactions.

**Comment by satyajit-behera** [comment]
msdtc used to work along with this, as far as i remember. 
https://learn.microsoft.com/en-us/windows/win32/fileio/how-to-use-transactional-ntfs
It was using ntfs and msdtc.

**Comment by roji** [comment]
@satyajit-behera that is simply NTFS and MSDTC - I don't think this has anything to do with .NET Framework. Where did you see .NET Framework support for this, via .NET APIs?

**Comment by satyajit-behera** [comment]
This was possible while using .net framework. Can something like this possible with dotnet core also, it would be great.

**Comment by roji** [comment]
> This was possible while using .net framework.

The question was more if this was **supported** in .NET Framework, not whether it was possible. It's just as possible to implement this in .NET Core; in fact, [the txFileManager library](https://github.com/chinhdo/txFileManager) you linked to seems to support .NET Core just fine (via .NET Standard - but on Windows only presumably), have you tried that?

In any case, I'm going to go ahead and close this issue as this inherently (a) a Windows-only capability (relying on filesystem transactionality features only available in NTFS), and (b) this isn't something I believe belongs in .NET runtime iteslf. Of course, that doesn't mean it can't be implemented as an externallibrary (just like txFileManager). But please feel free to post back with any comments/suggestions.

**Comment by satyajit-behera** [comment]
Thanks @roji. I understand. It would indeed be interesting to explore integrating this feature into a .NET Core library offering, even if it's not a core part of the runtime, at some point in the future.
