### ISSUE TITLE
[API Proposal]: Mark WeakReference Constructors `target` Parameter as Nullable

### ISSUE THREAD

**Issue by RyanLamansky** [dotnet/runtime#99496]
### Background and motivation

_This already works as expected_, it's just not annotated correctly, resulting in unnecessary compiler warnings and potentially sub-optimal code.

By indicating that the `target` parameter is nullable, some users may realize they don't have to supply the object immediately: they can wait until first access and set it on demand. Allocating memory as late as possible (which in some cases means never) reduces garbage collection pressure.

### API Proposal

```csharp
namespace System;

public sealed class WeakReference<T> : ISerializable where T : class
{
    public WeakReference(T? target); // Changed T to T?
    public WeakReference(T? target, bool trackResurrection); // Changed T to T?
}
```

### API Usage

```csharp
static class MyClass
{
    // This is CS8625 today, but shouldn't be because it works.
    private static readonly WeakReference<dynamic> weakRef = new(null);

    public static void Process(dynamic input)
    {
        if (input.someCondition)
        {
            // Conditional logic that may frequently or always be used.
            return;
        }

        // This path might happen rarely or never.
        // Below is normal usage of a weak reference.
        // This works the same whether the target is initially null or not.
        if (!weakRef.TryGetTarget(out var value))
            weakRef.SetTarget(value = new { InitStuff = "GoesHere" });

        value.DoSubProcess(input);
    }
}

```

### Alternative Designs

Since this proposal would make the only parameter of one of the constructors optional, one of the following could be included.

```csharp
public WeakReference(); // Same as passing a null target.
public WeakReference(T? target = null); // Beised T to T?, default null is an alternative to new constructor.
```

The empty constructor, when used, has a 1-byte CIL bytecode advantage is the compiler won't need to supply the default.

### Risks

The risk profile is the same as any other instance of marking a parameter as nulllable, which the dotnet team has done many times in the past as part of the initial rollout--I think this was just a miss during those original passes.

As far as I know, nullability isn't part of the binary method signature, so this wouldn't be a binary breaking change.

I don't think this would be a code-breaking change since all previously valid input is still valid.

In theory, someone could be using reflection to find the constructor with explicit logic to exclude a nullable one, but this seems highly improbable.

**Comment by stephentoub** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/13360
