### ISSUE TITLE
[HTTP/2] Reading data assert

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#99494]
https://github.com/dotnet/runtime/blame/a566fd59fc34d3f73da1b8eeaab613ab0c1fc9b5/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs#L1127-L1127

With a recent repro from an internal customer, I'm hitting assert at this line as I'm testing with Debug build. I can share repro privately.

**Comment by ManickaP** [comment]
So the problem is the server sending DATA frame containing only padding and no data at all. We do not handle this case at all and we will unblock the user pending read with 0-bytes read (despite not being at the end of the stream).

**Comment by karelz** [comment]
Fixed in main (8.0) in PR #99502, in 6.0.30 in PR #99678 and in 8.0.5 in PR #99677
