### ISSUE TITLE
[iOS/HybridGlobalization] Force short date pattern to use yyyy

### ISSUE THREAD

**Issue by tipa** [dotnet/runtime#99515]
### Description

When using `HybridGlobalization` on iOS, the `shortdate` format does only contain just either one or two `y`'s, which result in only a two-digit year when formatting dates.

### Reproduction Steps

Set `<HybridGlobalization>true</HybridGlobalization>` in iOS csproj file and format some date with "short date" format (e.g. `DateTime.Now.ToString("d")`)

### Expected behavior

new CultureInfo("de-DE").DateTimeFormat.ShortDatePattern == "dd.MM.yyyy"
new CultureInfo("en-US").DateTimeFormat.ShortDatePattern == "M/d/yyyy"
new CultureInfo("fa-IR").DateTimeFormat.ShortDatePattern == "yyyy/M/d"

### Actual behavior

new CultureInfo("de-DE").DateTimeFormat.ShortDatePattern == "dd.MM.yy"
new CultureInfo("en-US").DateTimeFormat.ShortDatePattern == "M/d/yy"
new CultureInfo("fa-IR").DateTimeFormat.ShortDatePattern == "y/M/d"

### Configuration

.NET 8

### Other information

A similar problem was reported a while back for Linux [here](https://github.com/dotnet/runtime/issues/26088) and fixed [here](https://github.com/dotnet/coreclr/pull/18316). To code is still in the repo: https://github.com/dotnet/runtime/blob/3eb8c7f1086b79b28a27b57a935f97be3b7fcccb/src/libraries/System.Private.CoreLib/src/System/Globalization/CalendarData.Icu.cs#L166-L251

**Comment by matouskozak** [comment]
Thank you for catching this. I added fix in https://github.com/dotnet/runtime/pull/99908.

**Comment by vitek-karas** [comment]
Reopening to keep it active until it's actually fixed in 8 - https://github.com/dotnet/runtime/pull/100810

**Comment by matouskozak** [comment]
The fix was successfully backported and the .NET 8.0.5 servicing release contains the fix.
