### ISSUE TITLE
Question: zip file hash digest calculation

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/runtime#99518]
I want to use the sha256 hash code for comparing the file contents, but found that the same contents may get different hash, how could I get a hash code for comparing the zip file contents only?

Sample code as below, here I created two zip files from the same source file but got two different hash digest

```c#
var filePath = Path.Combine(Directory.GetCurrentDirectory(), "hello.txt");
if (File.Exists(filePath))
{
    File.Delete(filePath);
}
await File.WriteAllTextAsync(filePath, "Hello World");

await GetSHA256Digest();
await Task.Delay(2000);
await GetSHA256Digest();

async Task GetSHA256Digest()
{
    using var ms = new MemoryStream();
    using var zipFile = new ZipArchive(ms, ZipArchiveMode.Create, true);
    var entry = zipFile.CreateEntry("hello.txt");
    await using var stream = entry.Open();
    await using (var fs = File.OpenRead(filePath))
    {
        await fs.CopyToAsync(stream);
    }

    ms.Seek(0, SeekOrigin.Begin);
    var hashBytes = await SHA256.HashDataAsync(ms);
    Console.WriteLine(Convert.ToHexString(hashBytes));
}
```

output sample:

```
E763FEDAABFA5D0EC75254D3F302BEF17B911179C2DF56A970ECC545D832DCBF
D3E794D0CFCF43CC3B846BFF3F09B68C8797ED897ED412B6ED8A7E1249875D84
```

**Comment by WeihanLi** [comment]
@huoyaoyuan thanks very much for the quick reply, 
I have a further question, since the `ZipArchiveEntry` has `LastWriteTime` property, is it possible to set the `LastWriteTime` to a constant value and keep using the same compression setting, would that help getting the same hash, are any other factors may affect, thanks?

**Comment by huoyaoyuan** [comment]
It's up to the compression and archiving algorithm and not specified to zip(deflate). The files may have different order, which can also affect compression result if there's cross-file compression. Like compiler, different versions of zlib can also provide different result bits for the same input.

You are effectively asking for a deterministic output of zip archive. My suggestion is not to do any assumption unless the toolchain explicitly claims. For your real use case, you can do tests yourself by bitwise comparison of files and find some opportunistic assumption. The determinism is likely to break when zlib version updates, you should be aware of this and always provide some fallback.

**Comment by WeihanLi** [comment]
got it, thanks very much

**Comment by WeihanLi** [comment]
I try to calculate each entry hash code and re-calculate the final hash based on each entry hash

sample code here, hope it helps, looks good from my test, many thanks for the help from @huoyaoyuan 

https://github.com/WeihanLi/SamplesInPractice/blob/53390075c46568232fc4eddaf59804333b2c7389/BalabalaSample/ZipCheckSumSample.cs#L23
