### ISSUE TITLE
`DiagnosticListener` disposal does not remove existing subscriptions

### ISSUE THREAD

**Issue by stevejgordon** [dotnet/runtime#99523]
### Description

Despite a comment suggesting it does, the `Dispose` implementation in `DiagnosticListener` does not currently clear existing subscriptions. This causes any existing observers to continue to be notified via their `OnNext` callback.

```c#
// Indicate completion to all subscribers.
DiagnosticSubscription? subscriber = null;
Interlocked.Exchange(ref subscriber, _subscriptions);
while (subscriber != null)
{
    subscriber.Observer.OnCompleted();
    subscriber = subscriber.Next;
}
// The code above also nulled out all subscriptions.
```

The above code notifies each subscriber via `OnCompleted` but does not set `_subscriptions` to null, so any existing subscriptions remain subscribed.

### Reproduction Steps

```c#
using System.Diagnostics;
using DiagnosticsExample;

_ = DoStuff.Listener.Subscribe(new Observer("A"));
DoStuff.DoIt("After subscribing 1");
DoStuff.Listener.Dispose();
_ = DoStuff.Listener.Subscribe(new Observer("B"));
DoStuff.DoIt("After disposal");

Console.WriteLine("DONE!");

namespace DiagnosticsExample
{
    public class DoStuff
    {
        internal static readonly DiagnosticListener Listener = new("MySource");

        public static void DoIt(string msg)
        {
            if (Listener.IsEnabled("DoIt"))
                Listener.Write("DoIt", msg);
        }
    }

    public class Observer(string name) : IObserver<KeyValuePair<string, object?>>
    {
        private readonly string _name = name;

        public void OnCompleted() =>
            Console.WriteLine("DiagnosticListener was disposed!");

        public void OnError(Exception error) { }

        public void OnNext(KeyValuePair<string, object?> value) =>
            Console.WriteLine($"{_name} - {value.Key}: {(string)value.Value!}");
    }
}
```

### Expected behavior

In the above code, I would expect that after disposing of the `DiagnosticListener`, the original subscription, "A," would no longer report notifications. 

```
A - DoIt: After subscribing 1
DiagnosticListener was disposed!
DONE!
```

### Actual behavior

The original subscription still receives notifications via `OnNext`, which gets written to the console.

```
A - DoIt: After subscribing 1
DiagnosticListener was disposed!
A - DoIt: After disposal
DONE!
```

The second subscription is correctly not added after disposal. 

### Known Workarounds

The best workaround is to have each observer track completion and guard against handling notifications after completion. This has more overhead than is ideal.

```c#
public class Observer(string name) : IObserver<KeyValuePair<string, object?>>
{
    private readonly string _name = name;
    private bool _completed;

    public void OnCompleted()
    {
        Console.WriteLine("DiagnosticListener was disposed!");
        _completed = true;
    }

    public void OnError(Exception error) { }

    public void OnNext(KeyValuePair<string, object?> value)
    {
        if (_completed)
            Console.WriteLine($"{_name} - {value.Key}: {(string)value.Value!}");
    }
}
```

**Comment by stevejgordon** [comment]
cc @noahfalk

**Comment by stevejgordon** [comment]
I believe the fix would be to tweak the code [here](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticListener.cs#L184-L192) with the code below, which ensures the `_subscriptions` field is nulled out as part of disposal. I don't have runtime building locally (and I'm at 39,000ft en route to the MVP summit!), so I haven't fully verified this and run any tests.

```c#
DiagnosticSubscription? subscriber = null;
subscriber = Interlocked.Exchange(ref _subscriptions, subscriber);
while (subscriber != null)
{
    subscriber.Observer.OnCompleted();
    subscriber = subscriber.Next;
}
```

**Comment by noahfalk** [comment]
Yep, I just came to the same conclusion - that looks like it would be a good fix! If you are interested in doing a PR I'd be glad to review it, or this can wait for someone else to get to it.

**Comment by stevejgordon** [comment]
> Yep, I just came to the same conclusion - that looks like it would be a good fix! If you are interested in doing a PR I'd be glad to review it, or this can wait for someone else to get to it.

I'd be keen to try and submit a PR, probably after summit. I'll see if I can get enough of the diagnostics code building locally so I can run tests etc.
