### ISSUE TITLE
 Inconsistent handling of duplicate keys in INI configuration files

### ISSUE THREAD

**Issue by sergey-iki** [dotnet/runtime#99535]
When using `Microsoft.Extensions.Configuration.Ini 8.0.0`, I have observed inconsistent behavior regarding the handling of duplicate keys within a single INI file versus across multiple INI files.

## Reproduction Steps:
- When a section (e.g., `[Section1]`) is declared twice within a single INI file with duplicate keys, the parser throws a FormatException for duplicate keys (the same thing if two identical keys are declared inside a section declared one once).
- When the same section is declared in two different INI files with duplicate keys, the last value overrides the previous ones without throwing an exception.
## Expected Behavior
The handling of duplicate keys should be consistent regardless of whether they are within a single file or across multiple files. Either allow duplicate keys in both scenarios and use the last value (preferred), or disallow them entirely to ensure consistent behavior.
## Actual Behavior
Currently, the behavior is inconsistent, leading to potential confusion and configuration errors.
## Possible Solution
Consider removing the key duplication check in `IniStreamConfigurationProvider.Read` or refining the logic to handle duplicates consistently across multiple files.
## Code to Reproduce
```csharp
public static void Main()
{
    Parse("File1.ini", "File2.ini");
}

public static void Parse(params string[] pathStrings)
{
    pathStrings = pathStrings.Where(File.Exists).ToArray();
    var config = GetConfiguration(pathStrings);
    foreach (var configurationSection in config.GetChildren())
    {
        Console.WriteLine(configurationSection.Key);
        foreach (var value in configurationSection.GetChildren())
            Console.WriteLine($"\t{value.Key} = {value.Value}");
    }

}
private static IConfiguration GetConfiguration(IEnumerable<string> pathStrings)
{
    var builder = new ConfigurationBuilder();
    foreach (var path in pathStrings)
        builder.AddIniFile(path);
    return builder.Build();
}
```
```
File1:
[Section1]
0=1
[Section1]
0=2

Or File1:
[Section1]
0=1
0=2

File2:
[Section1]
0=2
Output:
{"Failed to load configuration from file 'File1.ini'."} {"A duplicate key 'Section1:0' was found."}
```
```
File1:
[Section1]
0=1
File2:
[Section1]
0=2
Output:
Section1
0 = 2
```

**Comment by ericstj** [comment]
It's not that you're adding 2 files - you're adding two different INI providers.  The configuration system allows for layering where one provider can override the values specified by another.

In a single file it's incorrect to define a value more than once - that's a problem with the file.  In multiple files it's completely legitimate and key part of the way configuration works.
