### ISSUE TITLE
JIT_NewS_MP_FastPortable is slow for Orchard CMS benchmark on Linux-arm64

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#99552]
Orchard CMS is one of the most complicated benchmark in our test suite (way more complicated than TE benchmarks) so, presumably, it's closer to real-world. Currently, ARM64 is twice slower than x64 (comparable HW) on it while for TE benchmark the same ARM64 hardware is typically 1.2-1.5x faster than that x64 AMD machine.
The `perf` trace is pointing to `JIT_NewS_MP_FastPortable`: 
![image](https://github.com/dotnet/runtime/assets/523221/8683ce64-56dd-441e-8d40-5833fcef5496)

(sorted by 'self' aks exclusive time).

The annoted asm for it:
![image](https://github.com/dotnet/runtime/assets/523221/6927650b-ba32-45cd-a35b-1330b5223252)
Or (output of `bjdump -d`):
```asm
000000000033fbf0 <_Z24JIT_NewS_MP_FastPortableP21CORINFO_CLASS_STRUCT_>:
  33fbf0:	a9bf7bfd 	stp	x29, x30, [sp, #-16]!
  33fbf4:	910003fd 	mov	x29, sp
  33fbf8:	aa0003e8 	mov	x8, x0
  33fbfc:	90001920 	adrp	x0, 663000 <_ZTV12EEJitManager+0x50>
  33fc00:	f947dc01 	ldr	x1, [x0, #4024]
  33fc04:	913ee000 	add	x0, x0, #0xfb8
  33fc08:	d63f0020 	blr	x1
  33fc0c:	d53bd049 	mrs	x9, tpidr_el0
  33fc10:	b940050a 	ldr	w10, [x8, #4]
  33fc14:	f8606929 	ldr	x9, [x9, x0]
  33fc18:	a945ad20 	ldp	x0, x11, [x9, #88]
  33fc1c:	cb00016b 	sub	x11, x11, x0
  33fc20:	eb0a017f 	cmp	x11, x10
  33fc24:	54000082 	b.cs	33fc34 <_Z24JIT_NewS_MP_FastPortableP21CORINFO_CLASS_STRUCT_+0x44>  // b.hs, b.nlast
  33fc28:	aa0803e0 	mov	x0, x8
  33fc2c:	a8c17bfd 	ldp	x29, x30, [sp], #16
  33fc30:	14000006 	b	33fc48 <_Z7JIT_NewP21CORINFO_CLASS_STRUCT_>
  33fc34:	8b0a000a 	add	x10, x0, x10
  33fc38:	f9002d2a 	str	x10, [x9, #88]
  33fc3c:	f9000008 	str	x8, [x0]
  33fc40:	a8c17bfd 	ldp	x29, x30, [sp], #16
  33fc44:	d65f03c0 	ret
```

If I read this correctly, we spend most of them time reading data from TLS ([to get current allocator](https://github.com/dotnet/runtime/blob/6aca07ae5e939f3f957fbe7ea94ca1cce6035024/src/coreclr/vm/jithelpers.cpp#L2437) ?) - I'd expect to see time spent inside the fallback call to gc, but it's not (if the trace is accurate). Another hint from the general trace is that we don't really spend a lot of time in GC itself.

PS: what is `blr x1` call ? I presume it should be part of the `GetThread()`

cc @mangod9 @kunalspathak

**Comment by mangod9** [comment]
would make sense to compare with a similar gen0size setting and collect hardware perf counters in case that shows any memory access issues.

**Comment by EgorBo** [comment]
And just for the reference, a hand-written asm for NEWSFAST helper on x64:

https://github.com/dotnet/runtime/blob/6aca07ae5e939f3f957fbe7ea94ca1cce6035024/src/coreclr/vm/amd64/JitHelpers_InlineGetThread.asm#L160-L211

**Comment by kunalspathak** [comment]
> And just for the reference, a hand-written asm for NEWSFAST helper on x64:
> 
> https://github.com/dotnet/runtime/blob/6aca07ae5e939f3f957fbe7ea94ca1cce6035024/src/coreclr/vm/amd64/JitHelpers_InlineGetThread.asm#L160-L211

This is the current disassembly of the C++ helper on x64:

![image](https://github.com/dotnet/runtime/assets/12488060/c4d1550f-be2d-4b41-ab42-ff169b2170bd)

**Comment by kunalspathak** [comment]
> PS: what is blr x1 call ? I presume it should be part of the GetThread()

Yes it is call to get the offset of the TLS variable

![image](https://github.com/dotnet/runtime/assets/12488060/3cf07c28-cd7b-428f-af5d-a13b6d3ebf26)

**Comment by mangod9** [comment]
so is the call inlined for arm64 but not x64 per the disasm above?

**Comment by kunalspathak** [comment]
> so is the call inlined for arm64 but not x64 per the disasm above?

Seems for unix, we should be just using the same C++ code:

https://github.com/dotnet/runtime/blob/e9e33e18939f0466e0dc72ad239c00f9ade36752/src/coreclr/vm/jitinterfacegen.cpp#L75-L79

and as seen below when I attached debugger:

![image](https://github.com/dotnet/runtime/assets/12488060/f8850d72-3bfe-4245-8783-6e96bd2d92ae)

@EgorBo - do you have similar assembly level instrumentation on which portion of the helper is hot? The instruction `ldr x0, [x9, x0]` is basically accessing the field `m_pThread` of the `gCurrentThreadInfo` and if we see lot of cache misses around here (yet to know), one theory could be that newer or lot of threads accessing the helper and are touching the memory that is not in cache?

https://github.com/dotnet/runtime/blob/e9e33e18939f0466e0dc72ad239c00f9ade36752/src/coreclr/vm/threads.inl#L29-L45

**Comment by EgorBo** [comment]
> would make sense to compare with a similar gen0size setting and collect hardware perf counters in case that shows any memory access issues.

Just made both machines to use the same gen0size - it didn't change the results, arm64 is still 2x slower

**Comment by mangod9** [comment]
> > would make sense to compare with a similar gen0size setting and collect hardware perf counters in case that shows any memory access issues.
> 
> Just made both machines to use the same gen0size - it didn't change the results, arm64 is still 2x slower

but was the memory utilization comparable?

**Comment by EgorBo** [comment]
> > > would make sense to compare with a similar gen0size setting and collect hardware perf counters in case that shows any memory access issues.
> > 
> > 
> > Just made both machines to use the same gen0size - it didn't change the results, arm64 is still 2x slower
> 
> but was the memory utilization comparable?

the working set (mainly, GC heap) was the same - 20GB for both. I'll post a detailed crank comparison between them later

**Comment by EgorBo** [comment]
![image](https://github.com/dotnet/runtime/assets/523221/01e7904e-b85f-446a-99ef-d5afe0abc3cf)

cache-misses for arm64

**Comment by EgorBo** [comment]
```
| application                             | x64                       | arm64          |            |
| --------------------------------------- | ------------------------- | -------------- | ---------- |
| Max CPU Usage (%)                       |                        92 |             99 |     +7.61% |
| Max Cores usage (%)                     |                     5,904 |          6,331 |     +7.23% |
| Max Working Set (MB)                    |                    19,888 |         19,728 |     -0.80% |
| Max Private Memory (MB)                 |                    21,529 |         20,774 |     -3.51% |
| Build Time (ms)                         |                    27,746 |              0 |            |
| Start Time (ms)                         |                     1,005 |          1,103 |     +9.75% |
| Published Size (KB)                     |                   323,361 |              0 |            |
| Symbols Size (KB)                       |                    10,032 |              0 |            |
| Runnable Periods (#)                    |                         0 |              0 |            |
| Throttled Periods (#)                   |                         0 |              0 |            |
| Throttled Time (ns)                     |                         0 |              0 |            |
| .NET Core SDK Version                   | 9.0.100-preview.2.24110.2 |              0 |            |
| Max CPU Usage (%)                       |                        92 |             99 |     +6.68% |
| Max Working Set (MB)                    |                    20,854 |         20,686 |     -0.80% |
| Max GC Heap Size (MB)                   |                    19,658 |         19,269 |     -1.98% |
| Size of committed memory by the GC (MB) |                    20,484 |         20,335 |     -0.73% |
| Max Number of Gen 0 GCs / sec           |                      2.00 |           1.00 |    -50.00% |
| Max Number of Gen 1 GCs / sec           |                      2.00 |           1.00 |    -50.00% |
| Max Number of Gen 2 GCs / sec           |                      1.00 |           1.00 |      0.00% |
| Max Gen 0 GC Budget (MB)                |                    20,132 |         20,132 |      0.00% |
| Max Time in GC (%)                      |                      1.00 |          30.00 | +2,900.00% |
| Max Gen 0 Size (B)                      |               267,528,760 |     11,781,176 |    -95.60% |
| Max Gen 1 Size (B)                      |               355,197,984 |    125,843,976 |    -64.57% |
| Max Gen 2 Size (B)                      |                69,405,088 |     75,751,064 |     +9.14% |
| Max LOH Size (B)                        |               100,027,744 |     38,871,168 |    -61.14% |
| Max POH Size (B)                        |                 8,443,856 |      8,794,056 |     +4.15% |
| Max Allocation Rate (B/sec)             |            18,375,906,248 | 10,490,177,584 |    -42.91% |
| Max GC Heap Fragmentation (%)           |                    6,862% |         1,067% |    -84.45% |
| # of Assemblies Loaded                  |                       394 |            383 |     -2.79% |
| Max Exceptions (#/s)                    |                     2,006 |          2,026 |     +1.00% |
| Max Lock Contention (#/s)               |                     1,483 |          2,253 |    +51.92% |
| Max ThreadPool Threads Count            |                        84 |             85 |     +1.19% |
| Max ThreadPool Queue Length             |                       688 |            840 |    +22.09% |
| Max ThreadPool Items (#/s)              |                   171,252 |         94,400 |    -44.88% |
| Max Active Timers                       |                         7 |              6 |    -14.29% |
| IL Jitted (B)                           |                 4,135,519 |      3,884,822 |     -6.06% |
| Methods Jitted                          |                    59,756 |         59,642 |     -0.19% |


| load                    | x64       | arm64    |          |
| ----------------------- | --------- | -------- | -------- |
| Max CPU Usage (%)       |         2 |        1 |  -50.00% |
| Max Cores usage (%)     |       256 |       78 |  -69.53% |
| Max Working Set (MB)    |        49 |       49 |    0.00% |
| Max Private Memory (MB) |       640 |      241 |  -62.34% |
| Build Time (ms)         |     2,781 |    2,718 |   -2.27% |
| Start Time (ms)         |         0 |        0 |          |
| Published Size (KB)     |    78,472 |   78,472 |    0.00% |
| Symbols Size (KB)       |         0 |        0 |          |
| .NET Core SDK Version   |   8.0.201 |  8.0.201 |          |
| First Request (ms)      |     4,133 |       88 |  -97.87% |
| Requests/sec            |    82,404 |   38,546 |  -53.22% |
| Requests                | 1,242,212 |  580,824 |  -53.24% |
| Mean latency (ms)       |     18.25 |    68.09 | +273.10% |
| Max latency (ms)        |    709.36 | 1,450.00 | +104.41% |
| Bad responses           |         0 |        0 |          |
| Socket errors           |         0 |        0 |          |
| Read throughput (MB/s)  |    484.04 |   226.49 |  -53.21% |
| Latency 50th (ms)       |     11.17 |    22.50 | +101.43% |
| Latency 75th (ms)       |     15.36 |    33.78 | +119.92% |
| Latency 90th (ms)       |     22.62 |   124.01 | +448.23% |
| Latency 99th (ms)       |    191.13 |   856.37 | +348.06% |
```
@mangod9 ^

**Comment by kunalspathak** [comment]
> ![image](https://private-user-images.githubusercontent.com/523221/311909058-01e7904e-b85f-446a-99ef-d5afe0abc3cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMTUxNjEsIm5iZiI6MTcxMDIxNDg2MSwicGF0aCI6Ii81MjMyMjEvMzExOTA5MDU4LTAxZTc5MDRlLWI4NWYtNDQ2YS05OWVmLWQ1YWZlMGFiYzNjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQwMzQxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTgzZjhjMmEwMzllODdiZTdhZjZlMTg2ODM2ZjM2ZjEzMzFhMzhiNTYwYTYwZDI1ZjZjYTJjN2ZhZDVhZDc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xaO4pGtgnL21EZX2tPm5V1Lm8vlb7H1wR8KLNanfPkk)
> 
> cache-misses for arm64

I have seen similar results for an app that I am profiling...around 3.5% cache misses. I am still trying to figure out how to get x64 cache-miss data.

**Comment by mangod9** [comment]
Adding @dotnet/gc and @MokoSan as well. Does seem like there is a large disparity in Max Gen* sizes and allocation rate. Allocation rate could point to memory throughput as well. 

@EgorBo might also make sense to capture info while sending constant RPS perhaps (maybe around 30k) to review CPU/memory utilization for each platform.

**Comment by VSadov** [comment]
> If I read this correctly, we spend most of them time reading data from TLS ([to get current allocator](https://github.com/dotnet/runtime/blob/6aca07ae5e939f3f957fbe7ea94ca1cce6035024/src/coreclr/vm/jithelpers.cpp#L2437) ?) - I'd expect to see time spent inside the fallback call to gc, but it's not (if the trace is accurate). Another hint from the general trace is that we don't really spend a lot of time in GC itself.

That is to get to the thread context which has pointers to the Thread-Local Allocation Buffer. 
Most SOH allocations should be "pointer-bump" allocations from the buffer. That amortizes the cost of getting memory from GC and makes it possible to allocate in multiple threads without any synchronization. (when you get new chunks from GC, you may need to take locks)

As we see no time spent in GC, it looks like this works as expected.

Getting to TLAB should not normally cause cache misses since the data structures involved are all per-thread. It may be possible that the budget is too big, and the buffer gets evicted between being zeroed by GC and the time we start allocating. Although it is unlikely. The budget is typically not that big.

> PS: what is blr x1 call ? I presume it should be part of the GetThread()

I think that is a part of dynamic TLS. Aarch64 defaults to TLS descriptors, and that uses a call. I do not think linker can optimize away that call in dynamic load case. 
As long as coreclr can by dynamically loaded, this might cause some extra costs in TLS. Not sure if that can explain all the difference here.

**Comment by EgorBo** [comment]
@VSadov thanks, yes, I am aware of what the allocator does and that there should be no contention for the TLS data. Still, it doesn't explain why that load it's such a big outlier in this profile (reproduces every time I try to collect a trace with `perf`).
I am currently trying to get a profile for x64, but I am struggling with getting a proper `perf` on those machines with a too-new Linux Kernel (6.7.0)

**Comment by VSadov** [comment]
This benchmark could be sensitive to allocations just because it allocates a lot (I am not familiar with the actual benchmark). Why the cost is higher on arm64 is more interesting, I guess.

**Comment by EgorBo** [comment]
@VSadov Also, i wonder if we can re-order some fields on VM side?
E.g. make `m_alloc_context` the first field in `Thread` so the load won't require an addressing mode. Not sure if that helps anyhow.

**Comment by VSadov** [comment]
```
| Max Time in GC (%)                      |                      1.00 |          30.00 | +2,900.00% |
| Max Gen 0 Size (B)                      |               267,528,760 |     11,781,176 |    -95.60% |
```

This makes an impression that arm64 may be collecting Gen0 more aggressively. Since it is the allocator who typically triggers these, the cost of Gen0 GCs could, in theory, be attributed to the allocator (if prof is confused by symbols, tailcalling, sampling rate...).

As I recall ephemeral budgets are sized based on CPU cache sizes and we did have some hardware-specific issues in the past with figuring the cache size and computing the budgets. 

Could it be interesting to rerun tests while forcing the same DOTNET_GCgen0size?

**Comment by VSadov** [comment]
> Just made both machines to use the same gen0size - it didn't change the results, arm64 is still 2x slower

Right. Something else, then.

**Comment by davidwrighton** [comment]
@kunalspathak  Looking at the slowdown, it looks like the TLS access is slow, which is incredibly weird. I wonder if we're just getting SUPER unlucky. For instance, the way the global dynamic TLS works, is that it reads from a global variable to figure out the offset to the TLS data... and that global variable is just another normal global in the libcoreclr.so module. Normally, a series of reads from any number of threads should be fast, but if some OTHER global variable that is commonly modified happens to be located in the image nearby (within 128 bytes) the tls index variable, you could get false sharing in the cache, which would explain this sort of performance cliff.

**Comment by EgorBo** [comment]
> (if prof is confused by symbols, tailcalling, sampling rate...).

That was my theory as well (as I mentioned in the description), but I don't see any other pieces of GC in the profile.

> Could it be interesting to rerun tests while forcing the same DOTNET_GCgen0size?

These are already with the same `DOTNET_GCgen0size` (otherwise, GC Heap size is 5Gb on arm64 and 20Gb on x64).

**Comment by davidwrighton** [comment]
@kunalspathak actually, looks like I am probably wrong on the cache line size. According to the docs I can find, it's probably 64bytes.

**Comment by EgorBo** [comment]
@davidwrighton I've just tried to collect a new trace with `perf c2c` command that shows more data on cache misses (see [doc](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/monitoring_and_managing_system_status_and_performance/detecting-false-sharing_monitoring-and-managing-system-status-and-performance))

![image](https://github.com/dotnet/runtime/assets/523221/4b67fffd-0a00-4fc8-b3d0-4c1e177fc34f)

L1D-misses:
![image](https://github.com/dotnet/runtime/assets/523221/135fa348-3d59-4a56-b20a-bc8238069b7b)

LLC-misses:
![image](https://github.com/dotnet/runtime/assets/523221/1e29a835-6cce-4ba8-8621-0fed11f87b05)

**Comment by EgorBo** [comment]
Annotated ASM for LLC-misses inside the allocator:

![image](https://github.com/dotnet/runtime/assets/523221/af864171-970f-47b5-9755-1314dabc528b)

same load

**Comment by EgorBo** [comment]
Hm.. actually it's not the same load here (unless it's some accuracy issue). here it's not the TLS access is it?

**Comment by EgorBo** [comment]
I presume in many cases JIT knows in advance the size of an object it will need to allocate so maybe we can avoid that load and grab the size from the parameters? cc @jkotas

**Comment by VSadov** [comment]
In a ferociously allocating benchmark, we would typically see the same few types allocated (string, byte[], Lists with same few T's) so reading from method tables is cheap.  

Some kind of deserializer scenario could allocate numerous different types. That would not be arm64 specific though.

**Comment by davidwrighton** [comment]
@EgorBo That's really interesting, and far more plausible than the TLS access being slow. Again, it's memory that isn't changing, but we have many different `MethodTable` structures in use, and I could see caching problems with them. The `MethodTable` structure is really quite large, and fairly cache-inefficient to access. Looking at the ARM documentation, it appears that their Neoverse products are 4 way set associative for the L1 data cache, and most Intel processors are 8 way set associative for the L1 cache, and some are even 12 way set associative. That could explain a fair bit of performance difference, and how it would only appear for larger applications.

**Comment by VSadov** [comment]
MethodTable is basically readonly, but could we allocate it next to some writeable data? 

@davidwrighton - are these allocated basically next to each other or could be mixed with other stuff?

**Comment by davidwrighton** [comment]
@VSadov it can be mixed with other stuff, (and often is), but relatively little of that other stuff is commonly written to. Fortunately, this one is fairly easy to check, by adding the new jit allocation helper that @EgorBo suggested which shouldn't take more than a day or two to put together.

**Comment by davidwrighton** [comment]
@EgorBo could you also get a drill down of the TLB-miss and TLB-access data? 704K TLB misses is a LOT for only 10M memory accesses.  Also, the perf c2c data on the equivalent Intel platform would be really valuable here just to help us understand if we're just making up data or not.

**Comment by EgorBo** [comment]
Here are the types of objects allocated by that allocator (I put a `fprintf` inside of it and ran the benchmark):
```
1062643 - List`1
933797  - Task`1
520940  - Enumerator
471361  - Dictionary`2
350310  - Func`2
336875  - SZGenericArrayEnumerator`1
237252  - AlternatesCollection
237252  - KeyedAlternateCollection
172567  - HashSet`1
126068  - ObjectValue
118626  - ShapeMetadata
111954  - Object
111222  - <>c__DisplayClass22_0
108929  - Func`1
100089  - IShape_get_Metadata
99918   - Action`1
97537   - StringBuilder
89981   - Stack`1
89006   - <>c__DisplayClass17_0
89003   - <>c__DisplayClass4_0
84009   - RouteValueDictionary
81562   - DisplayContext
75795   - AsyncStateMachineBox`1
69382   - <OfTypeIterator>d__64`1
67102   - Version
64164   - ArrayEnumerator
63029   - TemplateInfo
60159   - <>c__DisplayClass7_0
59323   - CopyOnWriteDictionary`2
59314   - ShapeCreatingContext
59314   - ShapeCreatedContext
56697   - Func`3
55696   - <>c__DisplayClass13_0
55615   - PlacementInfo
55605   - ShapeResult
55605   - ShapePlacementContext
54350   - ExecutionContext
52124   - <>c__DisplayClass11_0
51908   - ViewBuffer
51908   - ViewBufferTextWriter
48608   - Scope
48542   - JsonObject
48485   - StringValue
48243   - Boolean
48201   - ViewContext
48178   - StringLocalizer`1
41392   - WhereListIterator`1
41204   - AdjustmentRule
40781   - ShapeDisplayContext
40777   - FilterItem
```

> @EgorBo could you also get a drill down of the TLB-miss and TLB-access data?

sure

**Comment by VSadov** [comment]
@EgorBo - can we have the same list of types for x64. If not too difficult, mostly as a datapoint.

I expect to see the same distribution. 
Although if we see, for example, way fewer Task`T, it could be something.

**Comment by EgorBo** [comment]
> @EgorBo could you also get a drill down of the TLB-miss and TLB-access data? 704K TLB misses is a LOT for only 10M memory accesses

![image](https://github.com/dotnet/runtime/assets/523221/a8ef16b8-da63-4298-968b-4f3cd592080d)
![image](https://github.com/dotnet/runtime/assets/523221/ba7b8ad3-96d2-4ece-ad00-62fc707249f3)

Pretty much the same picture.

> Although if we see, for example, way fewer Task`T, it could be something.

Ah, interesting point, will do

**Comment by davidwrighton** [comment]
Looking at this data, its very suspicious around the memory access patterns for `MethodTable`. Tomorrow, I'll put together a change which isolates `MethodTable` into its own heap, and keeps most of the ancillary data structures allocated on the high frequency heap. I've also identified that we have a subpar algorithm guessing how many dictionary entry slots we need for a type. Currently, its guessing that we need 50 Dictionary entry slots for `List<T>`, but it looks like we actually only need something like 8-10 of them. This is wasting about 300 bytes of address space for each `MethodTable`. Now, this isn't necessarily a problem that would impact the cache miss rates, but it will increase the TLB miss rate. However, if this also causes the typical allocation size for something like a specific instantiation of `List<T>` to happen to be about a power of 2 in size, it would also increase the cache miss rate, as it will induce false sharing which would be exacerbated by having fewer ways in the L1/L2 cache on arm64 vs x64.

These are both problems that will impact performance on Arm more than X64, as the TLB cache size on X64 platforms is typically quite a bit larger as well.

I'll try this week to build tweak to our type loader to attempt to address some of the TLB problems. I hope to have something tomorrow or the day after.

**Comment by EgorBo** [comment]
So I decided to quickly introduce a new helper - [my ugly branch.](https://github.com/EgorBo/runtime-1/commit/b1bb7bdce71228869f05254976299a0d07f008d8) 

After I sent my binaries to crank and collected a new profile I no longer see that helper in the cache misses:
![image](https://github.com/dotnet/runtime/assets/523221/c7564c68-3f14-4cd5-834c-ce826467aafb)

Unfortunately, the RPS didn't improve much. So I am going to look at x64 now.

**Comment by kunalspathak** [comment]
>  I no longer see that helper in the cache misses:

Does it shows up as one of the hot helper? I assume the above profile is for lld-miss and not `cycles`?

**Comment by EgorBo** [comment]
> > I no longer see that helper in the cache misses:
> 
> Does it still show up as one of the hot helper? I assume the above profile is for lld-miss and not `cycles`?

Not anymore:

![image](https://github.com/dotnet/runtime/assets/523221/c6884f07-c19c-4e76-9f9a-af2b79e2bec9)

(I highlighted the new helper)

**Comment by mangod9** [comment]
hmm, yeah this is interesting. We should compare with constant throughput as well, so we can check whether the GC throughput is different which might point to slow memory accesses.

**Comment by EgorBo** [comment]
x64 profile:

![image](https://github.com/dotnet/runtime/assets/523221/ab7f66b5-40a1-41f8-b0c6-eee90d3f6729)

the libc one seems to be `__nss_database_lookup` (so might be some memset/memcpy in fact)

**Comment by jkotas** [comment]
> I presume in many cases JIT knows in advance the size of an object it will need to allocate so maybe we can avoid that load and grab the size from the parameters? (e.g. new kind of an allocator - CORINFO_HELP_NEWSFAST_CONSTSIZE) cc @jkotas

This will move the potential cache miss from the allocation helper to potential cache miss on extra code and to a potential cache miss on the next method table use. I think that it is likely for the object MethodTable to be used for things like virtual calls after the object has been allocated. It is not obvious to me that it is a win on average to pass the size in an extra argument if it is done everywhere.

If we want to go in this direction, it may be more profitable to inline the allocation helper as "no GC region" for very hot code. You will inline the size, but also avoid the call overhead and fuse the size as immediate into the instruction. There is more code size overhead, but it may be ok if it is done only for very hot code. It matches what we do in the inlining heuristics for the very hot code.

**Comment by EgorBo** [comment]
Well, it did improve overall cache-miss statisitcs, but didn't improve RPS so I already gave up on that helper

> "no GC region"

My understanding that this require quite a bit of work in JIT to guarantee a nongc sequence of blocks in Importer

**Comment by VSadov** [comment]
I think the disappearance of cache misses is encouraging. I did not expect that, so I think we learned something, at least on my part.  
The constructor will likely write into the instance, but the instance could be still "hot" from GC zeroing. Otherwise not everything will use MT right away, so avoiding the cache misses on fetching the instance size could make the whole allocation path mostly miss-free. 

However, I would prefer inlining the fast path as @jkotas mentioned.

**Comment by jkotas** [comment]
> @VSadov Also, i wonder if we can re-order some fields on VM side?
E.g. make m_alloc_context the first field in Thread so the load won't require an addressing mode. Not sure if that helps anyhow.

The allocation helpers in CoreCLR have an unnecessary extra indirection. The `alloc_context` can be thread static directly. The extra indirection via Thread is unnecessary. The allocation helpers in native AOT do not have this indirection. It would be nice to port the improvement to regular CoreCLR and unify how the allocation helpers work.

**Comment by davidwrighton** [comment]
@EgorBo I have a branch https://github.com/davidwrighton/runtime/tree/adjust_allocation_in_typesystem where I've done some tweaks that may increase the memory density of the `MethodTable` structures used by the runtime (you should be able to cherry pick the last two commits in the branch). In general, what the branch does is that it reduces the size of the Generic Dictionaries, which are allocated per `MethodTable` for some of the egregiously large cases like `List<T>` and `Task<T>`, and also segregates the allocation of `MethodTable` structures which are likely to be used for allocated objects so that they are slightly more likely to share a 4K page. I'm interested to know if that change has any impact on the Orchard CMS scenario. I don't expect the change to have any meaningful impact on L1 cache hit rates, but I think there is some hope that it might impact TLB cache miss rates. Also, for these numbers do you know which TLB cache is being reported as hit/miss? These processors have multiple TLB caches, an L1, L2 and possibly L3, and your numbers were not reporting a specific one which is being missed. My understanding of TLB cache misses is that an L1 cache miss is bad, but not that impactful, but a last level cache miss on the TLB cache can cause a tremendous amount of work, as that will trigger a full page table walk, which is at least 5 memory loads.

**Comment by EgorBo** [comment]
> @EgorBo I have a branch https://github.com/davidwrighton/runtime/tree/adjust_allocation_in_typesystem where I've done some tweaks that may increase the memory density of the `MethodTable` structures used by the runtime (you should be able to cherry pick the last two commits in the branch). In general, what the branch does is that it reduces the size of the Generic Dictionaries, which are allocated per `MethodTable` for some of the egregiously large cases like `List<T>` and `Task<T>`, and also segregates the allocation of `MethodTable` structures which are likely to be used for allocated objects so that they are slightly more likely to share a 4K page. I'm interested to know if that change has any impact on the Orchard CMS scenario. I don't expect the change to have any meaningful impact on L1 cache hit rates, but I think there is some hope that it might impact TLB cache miss rates. Also, for these numbers do you know which TLB cache is being reported as hit/miss? These processors have multiple TLB caches, an L1, L2 and possibly L3, and your numbers were not reporting a specific one which is being missed. My understanding of TLB cache misses is that an L1 cache miss is bad, but not that impactful, but a last level cache miss on the TLB cache can cause a tremendous amount of work, as that will trigger a full page table walk, which is at least 5 memory loads.

Will try to run the benchmark with your branch and report diffs 👍
