### ISSUE TITLE
[System.Reflection.Emit] AssemblyBuilderAccess.RunAndCollect not collecting assemblies

### ISSUE THREAD

**Issue by Slxdy** [dotnet/runtime#99559]
### Description

So I've been playing around with `AssemblyBuilderAccess.RunAndCollect`, but it turns out it's not working and has the same behavior as `Run`.
According to the docs:
```
The dynamic assembly will be automatically unloaded and its memory reclaimed,
when it's no longer accessible.
```

Even after fully unreferencing everything related to my dynamic assembly, it will not unload, even after a forced GC collection.
I have fully tested this, using the code in the section below.

### Reproduction Steps

I tested this with the following script:
```cs
int id = 0;
for (; ; )
{
    GC.Collect();

    var name = $"Test{id++}";
    var asm = AssemblyBuilder.DefineDynamicAssembly(new(name), AssemblyBuilderAccess.RunAndCollect);
    var mod = asm.DefineDynamicModule(name);

    var type1 = mod.DefineType("TestClass", TypeAttributes.Public);
    var met = type1.DefineMethod("Foo", MethodAttributes.Public | MethodAttributes.Static);
    var il = met.GetILGenerator();
    il.EmitWriteLine("Hello World!");
    il.Emit(OpCodes.Ret);
    var t = type1.CreateType();

    t.InvokeMember("Foo", BindingFlags.Static | BindingFlags.Public | BindingFlags.InvokeMethod, null, null, null);

    Console.WriteLine("----");

    foreach (var ass in AppDomain.CurrentDomain.GetAssemblies())
    {
        if (!ass.GetName().Name?.StartsWith("Test") ?? true)
            continue;

        Console.WriteLine(ass.FullName);
    }

    Thread.Sleep(100);
    Console.Clear();
}
```

### Expected behavior

After a `GC.Collect`, the AppDomain should not contain the previously loaded dynamic assembly, and the console output should only contain the latest dyanmic assembly.

Expected console output after 6th iteration:
```
Hello World!
----
Test5, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
```

### Actual behavior

The AppDomain still contains the old dynamic assemblies, even after a forced collection, as seen in the console output.

Actual console output after 6th iteration:
```
Hello World!
----
Test0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
Test1, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
Test2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
Test3, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
Test4, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
Test5, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
```

### Regression?

I have tested the same code in net48 and net472, but the results are the same.

### Configuration

net8.0
Windows 11
x64
I don't believe the issue is related to these configs.

**Comment by Slxdy** [comment]
Ok, I have done some extra research, and it turns out that `GetAssemblies` prevents collectible assemblies from being unloaded in the future.
From what I've read, that should only happen when using `Assembly.Load`. I don't think `GetAssemblies` should replicate this behavior, considering that we should have the ability to check for loaded assemblies, collectible or not, without forcing collectible assemblies to stay alive forever.
Is it worth opening another issue for this problem?

**Comment by reflectronic** [comment]
The issue does not reproduce for me after extracting the `foreach` to a separate method:
```cs
// ...
    Console.WriteLine("----");

    PrintAssemblies();

    Thread.Sleep(100);
    Console.Clear();
}


static void PrintAssemblies()
{
    foreach (var ass in AppDomain.CurrentDomain.GetAssemblies())
    {
        if (!ass.GetName().Name?.StartsWith("Test") ?? true)
            continue;

        Console.WriteLine(ass.FullName);
    }
}
``` 

Then I get output like this:
```
Hello World!
----
Test33, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
Test34, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
```

**Comment by jkotas** [comment]
Yes, `GetAssemblies()` returns the array of with all assemblies, the JIT may extend the lifetime of the array till end of the method (depends on many factors).
