### ISSUE TITLE
When will Ubuntu 22.04 (aarch64) be supported? Can I use the Ubuntu 20.04 apt repository on Ubuntu 22.04? Is that kosher?

### ISSUE THREAD

**Issue by Danrancan** [dotnet/runtime#99572]
The [official Download Mono website](https://www.mono-project.com/download/stable/#download-lin-ubuntu) lists apt repositories for Ubuntu, up until Ubuntu 20.04, which is only a year and a half from being unsupported. For those doing an early upgrade to Ubuntu 22.04 (an a Raspberry Pi 4 aarch64), I want to know if it's okay to use the official Ubuntu 20.04 Focal Apt repository on an Ubuntu 22.04 Jammy  installation? Is that okay? 

If it's not kosher or okay, and will break things, then when will an apt repository come out that supports Ubuntu 22.04 Jammy?

Please let me know. Thank.

**Comment by hoyosjs** [comment]
I think this and https://github.com/dotnet/runtime/issues/99571 belong to the `mono/mono` repos. @akoeplinger is that the right repo to get answer to these?

**Comment by Danrancan** [comment]
Thats so weird. I could have sworn I posted this in the mono/mono repo. I will repost there. Sorry.

**Comment by jkotas** [comment]
Reopened as https://github.com/mono/mono/issues/21751
