### ISSUE TITLE
Event log shows 5011 for sharepoint IIS log after the CU 

### ISSUE THREAD

**Issue by qquiuc** [dotnet/runtime#99581]
Hi Team

We're experiencing an issue with our SharePoint 2016 environment following the application of the CU (https://support.microsoft.com/en-us/topic/december-12-2023-update-for-sharepoint-enterprise-server-2016-kb5002535-69e199ca-f5bd-478d-85fe-9f62d3006957). The problem is the random stopping of the application pool, which is accompanied by an error message in the system logs.

[-](https://github.com/dotnet/runtime/issues/new?assignees=&labels=&projects=&template=04_blank_issue.md&title=#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/dotnet/runtime/issues/new?assignees=&labels=&projects=&template=04_blank_issue.md&title=#) <System>
  <Provider Name="Microsoft-Windows-WAS" Guid="{524B5D04-133C-4A62-8362-64E8EDB9CE40}" EventSourceName="WAS" /> 
  <EventID Qualifiers="32768">5011</EventID> 
  <Version>0</Version> 
  <Level>3</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2024-03-12T05:30:52.841479100Z" /> 
  <EventRecordID>1515959</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>System</Channel> 
  <Computer>***t</Computer> 
  <Security /> 
  </System>
[-](https://github.com/dotnet/runtime/issues/new?assignees=&labels=&projects=&template=04_blank_issue.md&title=#) <EventData>
  <Data Name="AppPoolID">SharePoint - **.net443</Data> 
  <Data Name="ProcessID">29128</Data> 
  <Binary>6D000780</Binary> 
  </EventData>
  </Event>
[SPEventlog.zip](https://github.com/dotnet/runtime/files/14567879/SPEventlog.zip)

Is there any clue for this issue, I could provide the sharepoint logs if you need.

**Comment by jeffschwMSFT** [comment]
This repo is related to .NET Core.  This issue seems more applicable to sharepoint.  Can you follow-up with CSS?
