### ISSUE TITLE
ECDsa instance is not usable when private key is imported a second time

### ISSUE THREAD

**Issue by dougclutter** [dotnet/runtime#99605]
### Description

I'm using .NET SDK 8.0.200.

1. Creating an instance of ECDsa and importing private key information via ImportECPrivateKey works as expected.
2. However, if the original instance is Disposed AND a new instance is created AND the same private key is imported via ImportECPrivateKey, it fails with an ObjectDisposedException.

### Reproduction Steps

``` csharp
using Microsoft.IdentityModel.JsonWebTokens;
using Microsoft.IdentityModel.Tokens;
using System.Security.Cryptography;

namespace ECDsaDisposeBug;

public class JwtSigningKeyProvider : IDisposable
{
    const string privateKeyBase64 = "MIHcAgEBBEIAsukFBinjgL9KONxPRvunQGdaTEhIL9JpwlgW0NN0XzlmbENucgw4XTczjyjlF9AnJnJHg8vXoM2bH5MJy+42OeegBwYFK4EEACOhgYkDgYYABAF8Nt5oxNZ9VwQzjPCWai7/p8hI6sbCAQI8wDcWfQ2Cddrw4G7v5wu6+z26hGJSJY66wKl0ar4fN+JrbCMIYS9UugHAs3W75a/KtiNfVJ9tYwFM0CYWP2kAKg7Kbk3SXkXMW4Gdb4XeoDO+TQVTRfWoBYXXx1iVu0dOXv5NkGZFIkKAHg==";
    readonly ECDsa algorithm = ECDsa.Create();

    public AsymmetricSecurityKey Get()
    {
        var privateKey = Convert.FromBase64String(privateKeyBase64);
        algorithm.ImportECPrivateKey(new ReadOnlySpan<byte>(privateKey), out _);
        return new ECDsaSecurityKey(algorithm);
    }
    public void Dispose()
    {
        algorithm.Dispose();
        GC.SuppressFinalize(this);
    }
}
public class UnitTest1
{
    [Fact]
    public void Test1()
    {
        // This works fine the first time
        var provider = new JwtSigningKeyProvider();
        var key = provider.Get();
        AssertKeyIsUsable(key);
        provider.Dispose();

        // It fails the second time with an ObjectDisposed exception
        provider = new JwtSigningKeyProvider();
        key = provider.Get();
        AssertKeyIsUsable(key);
        provider.Dispose();
    }
    private static void AssertKeyIsUsable(AsymmetricSecurityKey key)
    {
        var signingCredentials = new SigningCredentials(key, SecurityAlgorithms.EcdsaSha256);
        var securityDescriptor = new SecurityTokenDescriptor
        {
            SigningCredentials = signingCredentials,
        };
        var tokenHandler = new JsonWebTokenHandler();
        var token = tokenHandler.CreateToken(securityDescriptor);       // This will throw if there's a problem with the key
        Assert.NotNull(token);
    }
}

```

### Expected behavior

The sample code should work.

### Actual behavior

An ObjectDisposedException is thrown:

Message: 
System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'System.Security.Cryptography.ECDsaCng'.

Stack Trace: 
ECDsaCng.GetKey()
ECDsaCng.TrySignHashCore(ReadOnlySpan`1 hash, Span`1 destination, DSASignatureFormat signatureFormat, Int32& bytesWritten)
ECDsaCng.TrySignHash(ReadOnlySpan`1 source, Span`1 destination, Int32& bytesWritten)
ECDsa.TrySignData(ReadOnlySpan`1 data, Span`1 destination, HashAlgorithmName hashAlgorithm, Int32& bytesWritten)
AsymmetricAdapter.SignUsingSpanECDsa(ReadOnlySpan`1 data, Span`1 destination, Int32& bytesWritten)
AsymmetricAdapter.SignUsingSpan(ReadOnlySpan`1 data, Span`1 destination, Int32& bytesWritten)
AsymmetricSignatureProvider.Sign(ReadOnlySpan`1 input, Span`1 signature, Int32& bytesWritten)
JwtTokenUtilities.CreateSignature(ReadOnlySpan`1 data, Span`1 destination, SigningCredentials signingCredentials, Int32& bytesWritten)
JsonWebTokenHandler.CreateToken(SecurityTokenDescriptor tokenDescriptor, Boolean setdefaultTimesOnTokenCreation, Int32 tokenLifetimeInMinutes)
JsonWebTokenHandler.CreateToken(SecurityTokenDescriptor tokenDescriptor)
UnitTest1.AssertKeyIsUsable(AsymmetricSecurityKey key) line 31
UnitTest1.Test1() line 20
RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)

### Regression?

I didn't try this in any other version of the SDK.

### Known Workarounds

I tried a number of things to work around this, but nothing worked.

### Configuration

.NET SDK Version: 8.0.200
OS: Windows 11 Enterprise 22H2 22621.3155
Architecture: x64

Have not tried on other versions of Windows/Architecture.

**Comment by vcsjones** [comment]
This is a known behavior with IdentityModel and JWTs.

This is essentially a duplicate issue of https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1433, except for ECDSA instead of RSA.

Essentially, the IdentityModel library expects to take "ownership" of the ECDsa instance you are passing, but you are disposing of the instance out from under it. You can either not dispose of the algorithm or disable caching, as suggested in the linked issue.

**Comment by dougclutter** [comment]
@vcsjones - Thank you so much for your quick response and the link to 1433 which clearly explains the issue and a number of workarounds. I'm sure you've heard this before, but enabling caching of signing keys by default was probably a bad design choice.  Perhaps, the documentation could be updated to highlight this so other developers don't fall into the same pit of despair.  😊
