### ISSUE TITLE
ObservableGauge Tags Aren't Being Properly Passed to MeterListener

### ISSUE THREAD

**Issue by james-newell-forge** [dotnet/runtime#99629]
### Description

In .NET 8, you can pass tags to the various metric instruments on creation including `ObservableGauge`.  The list of tags will get passed to the MetricListener class when there is a new metric value.  However, MeterListener expects a `ReadOnlySpan` type instead of an `IEnumerable` which is how the list is stored.  The bug is that the list should be passed to the MetricListener as a `new Span(tags)`.  Currently, the passed tags will be interpreted as length = 0.

### Reproduction Steps

```
    [Fact]
    public void ObservableGauge_Tags_Test()
    {
        // Arrange
        Meter meter = new("Test.Metrics");
        List<KeyValuePair<string, object?>> labels =
        [
            new KeyValuePair<string, object?>("field1", "value1"),
            new KeyValuePair<string, object?>("field2", "value2")
        ];

        ObservableGauge<long> observableGauge = meter.CreateObservableGauge($"test.observable", () => (long)5, null, "Test Observable", labels);

        int tagsCount = 0;
        void CallbackLong(Instrument instrument, long measurement, ReadOnlySpan<KeyValuePair<string, object?>> tags, object? state)
        {
            tagsCount = tags.Length;
        }

        MeterListener listener = new();
        listener.SetMeasurementEventCallback<long>(CallbackLong);
        listener.EnableMeasurementEvents(observableGauge);
        listener.Start();

        // Act
        listener.RecordObservableInstruments();

        // Assert
        Assert.Equal(2, tagsCount);
    }
```

### Expected behavior

The unit test should succeed with a value of 2

### Actual behavior

The unit test will fail with a value of 0

### Regression?

Unsure, appears to be a new feature in .NET 8

### Configuration

.NET 8 core

**Comment by hoyosjs** [comment]
The labels are part of the instrument, add this to your callback:

```csharp
Console.WriteLine($"CallbackLong: {instrument.Name} {measurement} {tags.Length} {instrument.Tags?.Count() ?? 0}");
```

And you'll see `CallbackLong: test.observable 5 0 2`. That allows you to aggregate the two sets of tags as needed if you're consuming from the instrument directly.

**Comment by james-newell-forge** [comment]
Correct, I can see that the tags exist in the `instrument.Tags` var, but is this really correct behavior?  Shouldn't they be passed through the `tags` argument (the ObservableInstrument code looks like it is trying to do that [here](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/ObservableInstrument.cs#L66)).  I only noticed this issue because OTEL/Grafana will _not_ pick up these labels since the `tags` var is coming back as empty.   Whereas, if one passes the tags using this method for regular Counter: `Counter.Add(x, tags)` it is picked up fine because the code there converts these into a `Span`.

**Comment by hoyosjs** [comment]
No, this is working as designed. The line that you show is for tags on the measurement. They'd be in the measurement if your observe function was `Funct<Measurement<T>>`, so 

`meter.CreateObservableGauge<long>($"test.observable", () => { return new(5L, labels); }, null, "Test Observable");`

would give them to you on the measurement. I would need to check what the OTel sink does for aggregating Instrument and measurement tags. 

cc: @noahfalk @tarekgh

**Comment by tarekgh** [comment]
@hoyosjs is accurate in this context. The tags applied during instrument creation won't be transferred to every published measurement. This can negatively impact performance. Moreover, the collectors already possess the tags and can determine how to aggregate them.

CC @reyang @CodeBlanch @cijothomas to answer the question how OpenTelemetry handle the tags that are used during the instrumentation creation.

**Comment by CodeBlanch** [comment]
We don't have any support in OpenTelemetry .NET at the moment for [Instrument.Tags](https://learn.microsoft.com/dotnet/api/system.diagnostics.metrics.instrument.tags). We never look at them and we don't expose them to exporters. There really isn't any such concept in the OpenTelemetry Specification either. It is something we are talking about supporting but no immediate plans.

We do expose [Meter.Tags](https://learn.microsoft.com/dotnet/api/system.diagnostics.metrics.meter.tags) to exporters. In the OpenTelemetry Specification there are instrument scope attributes which allow for such a thing.

**Comment by reyang** [comment]
> We don't have any support in OpenTelemetry .NET at the moment for [Instrument.Tags](https://learn.microsoft.com/dotnet/api/system.diagnostics.metrics.instrument.tags). We never look at them and we don't expose them to exporters. There really isn't any such concept in the OpenTelemetry Specification either. It is something we are talking about supporting but no immediate plans.
> 
> We do expose [Meter.Tags](https://learn.microsoft.com/dotnet/api/system.diagnostics.metrics.meter.tags) to exporters. In the OpenTelemetry Specification there are instrument scope attributes which allow for such a thing.

@CodeBlanch is correct, check this doc https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/metrics#metrics-enrichment

**Comment by james-newell-forge** [comment]
ok, thank you for the workaround that was very helpful.  I will probably be using that to get around this issue.  OTEL expect the tags to come from the `tags` arguments as seen [here](https://github.com/open-telemetry/opentelemetry-dotnet/blob/4cccb09239aff1250967c543f7483aaf88e538a3/src/OpenTelemetry/Metrics/MeterProviderSdk.cs#L209-L229).  They are on .net 6, so I don't think they would even be able to merge-in the `Instrument.Tags`.  In my 2cents, the merging should be happening before the call to MetricsListener to keep it backwards-compatible.
