### ISSUE TITLE
Time out in Directed_3.0.1 work item

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#99638]
Pipeline: 
- [Pipelines - Runs for runtime-coreclr gcstress-extra (azure.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fdnceng-public%2Fpublic%2F_build%3FdefinitionId%3D113%26_a%3Dsummary&data=05%7C02%7CJulie.Lee%40microsoft.com%7Cb0407c0a1dc44c1b73fe08dc37b79c63%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638446508956203900%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=MfhDKrXpPGLmbHowDP4JeJgmTcNFKI%2F4aPyh7eS%2BXms%3D&reserved=0)
- [Pipelines - Runs for runtime-coreclr gcstress0x3-gcstress0xc (azure.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fdnceng-public%2Fpublic%2F_build%3FdefinitionId%3D112%26_a%3Dsummary&data=05%7C02%7CJulie.Lee%40microsoft.com%7Cb0407c0a1dc44c1b73fe08dc37b79c63%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638446508956186074%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=A1t%2Fm9NrKqEj9peujLun4fjxFyagk6sQvWWwyIZgivU%3D&reserved=0)

https://dev.azure.com/dnceng-public/public/_build/results?buildId=596943&view=results

```
> /root/helix/work/workitem/e/JIT/Directed/Directed_3/../StructABI/StructABI/StructABI.sh
22:46:14.055 Passed test: JIT/Directed/StructABI/StructABI/StructABI.cmd
22:46:14.116 Running test: JIT/Directed/tailcall/more_tailcalls/more_tailcalls.cmd
Invoking: sudo ls -l /home/helixbot/dotnetbuild/dumps/coredump.227.dmp.crashreport.json
stdout: -rw------- 1 helixbot2 adm 24482 Mar 10 22:46 /home/helixbot/dotnetbuild/dumps/coredump.227.dmp.crashreport.json

=========================================
Child process took too long. Timed out... Exiting...
App Exit Code: 110
Expected: 100
Actual: 110
END EXECUTION - FAILED
+ test_exit_code=1
+ dotnet /root/helix/work/correlation/XUnitLogChecker/XUnitLogChecker.dll --results-path JIT/Directed/Directed_3 --test-wrapper Directed_3 --dumps-path /home/helixbot/dotnetbuild/dumps
[XUnitLogChecker]: 03:43:06.41: The full run will be done.
[XUnitLogChecker]: 03:43:06.50: Item 'Directed_3' did not finish running. Checking and fixing the log...
[XUnitLogChecker]: 03:43:06.61: XUnit log file has been fixed!

237/245 tests run.
* 234 tests passed.
* 0 tests failed.
* 3 tests skipped.
```

**Comment by BruceForstall** [comment]
This is a dup of https://github.com/dotnet/runtime/issues/99410
