### ISSUE TITLE
[API Proposal]: Make `ElapsedEventArgs` constructor public

### ISSUE THREAD

**Issue by colejohnson66** [dotnet/runtime#99635]
### Background and motivation

I'm writing a wrapper around `TimerProvider`/`ITimer` that works like a "watchdog". It must be periodically "pet" to prevent it from signaling. I'd like the callback event to be an `System.Timers.ElapsedEventHandler`, but the constructor of `System.Timers.ElapsedEventArgs` is private.

### API Proposal

```csharp
namespace System.Timers;

public class ElapsedEventArgs
{
    public ElapsedEventArgs(DateTime localTime);
}
```

### API Usage

```csharp
private readonly TimeProvider _provider;
public event ElapsedEventHandler? Signaled;

Signaled?.Invoke(this, new(_provider.GetLocalNow());
```

**Comment by stephentoub** [comment]
This was already done in https://github.com/dotnet/runtime/pull/94489.
