### ISSUE TITLE
WASM: dotnet-resources cache added to every path of a SPA

### ISSUE THREAD

**Issue by onionhammer** [dotnet/runtime#99642]
### Description

Instead of reusing a cache, every route of a SPA application which loads dotnet wasm resources will create a separate cache, with duplicate data. This may be desired behavior for blazor applications, but .NET wasm isn't a blazor-only tool, and this should be configurable rather than hardcoded if you have caching enabled.

![image](https://github.com/dotnet/runtime/assets/969938/2fc496ce-15ff-4f66-8e8b-385ff5e45268)

### Reproduction Steps

- Create a simple react application which references a .NET wasm component
- Invoke loadLibrary() on the root component
- Open browser and navigate to app
  - Change path and hit refresh, should have 2 caches
  - Change path and hit refresh, should have 3 caches

### Expected behavior

dotnet.create() should have a configuration/input to provide where the cached items are, overriding this logic:

![image](https://github.com/dotnet/runtime/assets/969938/6a094ec5-1410-4654-85ab-3977ecb61e7d)

### Actual behavior

Each path re-loads the same exact dlls, even for dynamic routes which include, for example, a database ID

**Comment by maraf** [comment]
We are already tracking improvement in https://github.com/dotnet/runtime/issues/85775
