### ISSUE TITLE
[API Proposal]: SHAKE squeezing

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#99645]
### Background and motivation

In .NET 8 we introduced the `Shake128` and `Shake256` APIs, two XOFs as part of SHA-3. A XOF is designed to permit multiple extractions, or "streaming" back results, in addition to acting like a regular hash function.

This streaming behavior was not implemented at the time because OpenSSL did not support it. As of OpenSSL 3.2, it is now supported with the [`EVP_DigestSqueeze`](https://www.openssl.org/docs/manmaster/man3/EVP_DigestSqueeze.html) API. Windows already supported it from the start.

This was a somewhat notable omission from the SHAKE APIs, as being able to use them as a XOF is largely the point of them. Some specifications and designs are starting to take advantage of SHAKE being able to stream back a result. Such examples are FIPS-203 which uses SHAKE for key generation (K-PKE.KeyGen with SampleNTT). This uses rejection sampling to extract from the SHAKE XOF function until enough data has been accumulated, but you don't know how much you need to extract because of the rejection.

### API Proposal

```diff
namespace System.Security.Cryptography;

public sealed partial class Shake128 : IDisposable {
+   public byte[] Read(int outputLength);
+   public void Read(System.Span<byte> destination);
+   public void Reset();
+   public Shake128 Duplicate();
}

public sealed partial class Shake256 : IDisposable {
+   public byte[] Read(int outputLength);
+   public void Read(System.Span<byte> destination);
+   public void Reset();
+   public Shake256 Duplicate();
}
```

### API Usage

Let's say you wanted to extract from SHAKE-128 until it gives you back a positive integer that is a multiple of two.

```C#
Shake128 shake = new();
shake.AppendData(someDiscriminatorInput);
int value = 0;

do
{
    Span<byte> bytes = MemoryMarshal.AsBytes(new Span<int>(ref value));
    shake.Read(bytes);
}
while (value <= 0 || (value & 1) == 1);

// `value` is now a positive integer that is a multiple of two, squeezed out from the hash.

shake.Reset(); // Now you can use the shake instance again here.
```

Some questions and answers that are likely to come up.

1. _How does this interact with `GetHashAndReset`_?
    GetHashAndReset is basically "Read" + Reset. You might just be trying to extract a really big hash and write it to a stream. You can use GetHashAndReset to get the "last" one, and reset it. 
2. _How is this different from `GetCurrentHash`?_
    GetCurrentHash is `Read`, except that it does "reset" to the state of things right before GetCurrentHash was called, instead of resetting as if nothing was appended to the hash. In terms of the current API, consider this "Duplicate" + "Read" + "Dispose". 
3. _What does `Duplicate` do?_
    It creates a new instance of the respective shake class with all of the data appended to it.
4. _What does `AppendData` do after you call `Read`?_
    It will throw an `InvalidOperationException`. Once you start reading data, you can't write to the hash any more.
5. _Will `Duplicate` work after calling `Read`?_
    No, it will also throw.

### Alternative Designs

We (@bartonjs) and I discussed a few different names and settled on `Read`.

* `Extract` was "okay" but had a bit of overlap with other thing like HKDF and other PRFs that we wanted to avoid.
* `Squeeze` was a close consideration, but decided that squeeze is a term used by the sponge construction, not necessarily all XOFs. 
* `Xof` didn't seem right since it is a noun and not a verb.
* We contemplated variations on `Read` like `ReadNext` and `ReadHash` but they seemed redundant.
* We considered something like `Stream GetHashStream()` where the XOF is represented by a read-only, non seekable Stream. However, `Duplicate` lets people get the behavior needed, without the cost of allocating a stream or the complexity of implementing a Stream. Developers can build this abstraction on top of the shake classes if they prefer, but we did not see an obvious reason for this to conform to a Stream type.

### Risks

For Linux, a notable issue is that while SHAKE was introduced in OpenSSL 1.1.1, the squeeze API was not introduced until 3.2. That leaves a question of what this API should do if your OpenSSL version is >= 1.1.1 and < 3.2, especially in conjunction with the `IsSupported` property.

`IsSupported` returns true if you have OpenSSL 1.1.1, however we would throw anyway if the needed squeeze API is not available.

We could introduce another static property, `IsReadSupported`, which would be `IsSupported && HasTheOpenSSLApiWeNeed`. We could also do nothing and document that this method may throw anyway.

**Comment by bartonjs** [comment]
* We renamed Duplicate to Clone
  * Discussed if it needed a "Deep" or "Shallow" prefix and decided "no".
  * And IClonable is still a no-no.
* We discussed adding a capability API (IsReadSupported, CanRead, etc) and decided we will leave it out and hope that the gap is closed before it's a real problem.

```c#
namespace System.Security.Cryptography;

public sealed partial class Shake128 : IDisposable {
    public byte[] Read(int outputLength);
    public void Read(System.Span<byte> destination);
    public void Reset();
    public Shake128 Clone();
}

public sealed partial class Shake256 : IDisposable {
    public byte[] Read(int outputLength);
    public void Read(System.Span<byte> destination);
    public void Reset();
    public Shake256 Clone();
}
```
