### ISSUE TITLE
[API Proposal]: System.Globalization.CompareOptions.UseNLS

### ISSUE THREAD

**Issue by clement911** [dotnet/runtime#99646]
### Background and motivation

Using NLS instead of ICU can currently only be configured with a global flag.
See https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#use-nls-instead-of-icu
This new API would allow the use of NLS on a per API call basis.

### API Proposal

Add a new flag System.Globalization.CompareOptions.UseNLS

### API Usage

```csharp
CompareInfo.GetCompareInfo("en-US").Compare(str1, str2, CompareOptions.UseNLS)
```

### Alternative Designs

I can't think of any

### Risks

I can't think of any

**Comment by teo-tsirpanis** [comment]
I don't think we should be encouraging users to rely on NLS in the long term, especially for new apps. NLS is Windows-specific while ICU is standard and cross-platform.

**Comment by clement911** [comment]
Not encourage but it is sometimes needed to use NLS.
See https://github.com/dotnet/runtime/issues/99507

**Comment by teo-tsirpanis** [comment]
`SqlString` should call NLS APIs by itself. I don't see a reason to expose a general-purpose API for NLS comparisons.

**Comment by clement911** [comment]
`SqlString` delegates to `System.Globalization.CompareOptions` for its comparison logic.

See:
https://github.com/dotnet/runtime/blob/b181ed507c07bdcfb84e2a2b4786d3c2c763db8c/src/libraries/System.Data.Common/src/System/Data/SQLTypes/SQLString.cs#L684-L705

https://github.com/dotnet/runtime/blob/b181ed507c07bdcfb84e2a2b4786d3c2c763db8c/src/libraries/System.Data.Common/src/System/Data/SQLTypes/SQLString.cs#L401-L403

I guess it could be a new internal API, although I don't see the harm of exposing this flag since it would be off by default.
Also, there might be other public packages that might want to use it.

**Comment by MichalPetryka** [comment]
> `SqlString` should call NLS APIs by itself. I don't see a reason to expose a general-purpose API for NLS comparisons.

That probably won't happen since it'd make `SqlString` Windows only.

**Comment by jkotas** [comment]
Globalization tables are moving target. If SqlString assumes that the globalization tables are fixed, it sounds like a design flaw in SqlString that should be fixed in SqlString.

**Comment by clement911** [comment]
Any updates on this?
We continue to find more characters that are not handled properly by SqlString  (see https://github.com/dotnet/runtime/issues/99507#issuecomment-2123600875)

Can we loop in someone that owns SqlString, or knows more about it?

**Comment by jkotas** [comment]
The main issue is tracked by #99507
