### ISSUE TITLE
Undefined behavior when the number of function parameters and the number of arguments does not match

### ISSUE THREAD

**Issue by GlebSBrykin** [dotnet/runtime#99644]
I am developing a compiler for a very old programming language and have chosen .NET as a platform. In the course of work, it became necessary to call the function by pointer with the potential to pass fewer arguments than the parameters of the function. For example, there is such a function

```asm
.method public hidebysig static native int printf(native int fmt, native int a1, native int a2, native int a3, native int a4, native int a5, native int a6, native int a7, native int a8, native int a9, native int a10) cil managed
```

I call it for 3 arguments (in this case, printf is guaranteed not to access parameters for which values have not been set).

```asm
// fmt, a1, a2 are already on stack
ldftn native int printf(native int, native int, native int, native int, native int, native int, native int, native int, native int, native int, native int)
calli native int(native int, native int, native int)
```

It works as expected (fmt, a1, a2 parameters initialized) on .NET 7.0 on Linux Mint 21.3 x64 and Windows 7 x64, however, can this be considered a reliable solution? According to one data used in the .NET calling convention is resistant to mismatch in the number of parameters and arguments, but according to other data, it is not.

**Comment by MichalStrehovsky** [comment]
> however, can this be considered a reliable solution?

This is not correct CIL per [ECMA-335](https://ecma-international.org/publications-and-standards/standards/ecma-335/); see the Correctness section for the calli opcode. The behavior is not defined and depends on the underlying physical calling convention that is an implementation detail of the runtime. It may appear to work on x64. It would probably not work on WASM AOT. It may appear to work and still cause silent corruptions.

If your compiler has enough type information, it should generate a method with a correct signature that thunks to the method with more parameters (supplying the extra parameters as needed).

**Comment by colejohnson66** [comment]
Calling variable-argument functions like `printf` requires some work with undocumented features. The best you can do is examine how the C# compiler works with `__arglist` and copy that.

* https://stackoverflow.com/q/32175822/1350209
* https://web.archive.org/web/20170322203441/http://bartdesmet.net/blogs/bart/archive/2006/09/28/4473.aspx

**Comment by MichalStrehovsky** [comment]
> Perhaps a reliable (but ugly) solution would be to allocate memory on the stack via localloc when calling a function and then pass a pointer to the allocated area containing the arguments of the function to the function.

Yes, that's probably the only option. It would also be the only option on a VM like WASM. There isn't enough control over the physical calling convention to do this with proper parameters.
