### ISSUE TITLE
Is it possible to use a same dotnet.wasm with different but similary assemblies when RunAOTCompilation is true

### ISSUE THREAD

**Issue by weiyuemin** [dotnet/runtime#99668]
when RunAOTCompilation is false, using a same `dotnet.wasm` and replacing assemblies (.dll files in `managed` folder) worked. (But it's too slow)

when RunAOTCompilation is true, do the same will result in an error: "[MONO] error: /__w/1/s/src/mono/mono/mini/aot-runtime.c:2110 <disabled>", it seems the assemblies' guid are checked and don't match so the program aborted.

it seems .o files that produced from .dll are compiled into dotnet.wasm, but .dll files are still needed when running the program. My question is: which part is compiled into dotnet.wasm? Does this [article](https://www.mono-project.com/docs/advanced/runtime/docs/aot/) suitable for wasm? Is the `metadata` part compiled into dotnet.wasm? is there some way to use a same dotnet.wasm and replace a dll in wasi-wasm + RunAOT mode, when all the function signatures and import export are not changed?

**Comment by maraf** [comment]
The Mono AOT works in mixed mode. Some of the paths of the code it can compile it compiles and "bundles" into dotnet.wasm, but it reached something or gets to some state where it can't continue in native code, it falls back to interpreter.

In pure interpreter mode, the `dotnet.wasm` contains only mono runtime compiled to wasm and so it can be "reused" between different apps. In AOT mode is contains mono runtime + app code compiled to wasm.

**Comment by weiyuemin** [comment]
Thank you for the information
