### ISSUE TITLE
Avoid unnecessary extra indirection in allocation helpers

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#99661]
Context: https://github.com/dotnet/runtime/issues/99552#issuecomment-1993382384

The allocation helpers in CoreCLR have an unnecessary extra indirection. The alloc_context can be thread static directly. The extra indirection via Thread is unnecessary. The allocation helpers in native AOT do not have this indirection. It would be nice to port the improvement to regular CoreCLR and unify how the allocation helpers work.

**Comment by jkotas** [comment]
@VSadov Are you interested in looking into this?

**Comment by VSadov** [comment]
> @VSadov Are you interested in looking into this?

yes, NativeAOT approach is a lot simpler. I’d like try porting it.

**Comment by mangod9** [comment]
assume the indirection isn't arm64 specific? But in theory it might help with cache locality?

**Comment by jkotas** [comment]
> assume the indirection isn't arm64 specific? But in theory it might help with cache locality?

Right
