### ISSUE TITLE
Dotnet Package for centos not installing from https://packages.microsoft.com/centos/8/prod/Packages/d/ 

### ISSUE THREAD

**Issue by tapadarj** [dotnet/runtime#99672]
### Description

https://packages.microsoft.com/centos/8/prod/Packages/d/dotnet-runtime-8.0-8.0.3-1.x86_64.rpm

Everything was working when installing dotnet 8.0 sdk from https://packages.microsoft.com/centos/8/prod/Packages/d/ till yesterday.

Today from 13th March, 2024 its started giving issue when installing dotnet sdk 8.0 in linux. The issue is coming when downloading dependency : https://packages.microsoft.com/centos/8/prod/Packages/d/dotnet-runtime-8.0-8.0.3-1.x86_64.rpm

After spending few hours we have noticed dotnet-runtime-8.0-8.0.3-1.x86_64.rpm is added yesterday in the packages.microsoft.com and this is causing the issue. please check the issue.

Downloading packages:
warning: /var/cache/yum/x86_64/2/packages-microsoft-com-prod/packages/aspnetcore-targeting-pack-8.0-8.0.3-1.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
Public key for aspnetcore-targeting-pack-8.0-8.0.3-1.x86_64.rpm is not installed
https://packages.microsoft.com/centos/8/prod/Packages/d/dotnet-runtime-8.0-8.0.3-1.x86_64.rpm: [Errno 14] curl#92 - "HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)"
Trying other mirror.

Error downloading packages:
dotnet-runtime-8.0-8.0.3-1.x86_64: [Errno 256] No more mirrors to try.

Can you plesae look into this and provide soultion.

### Reproduction Steps

sh """
          echo "Patching container... Install dotnet 8.0.0"
          sudo rpm -Uvh https://packages.microsoft.com/config/centos/8/packages-microsoft-prod.rpm
          sudo yum -y install dotnet-sdk-8.0.0
          dotnet --version
        """

### Expected behavior

It will install dotnet 8 and dependencies
Installed:
  dotnet-sdk-8.0.x86_64 0:8.0.200-1                                             

Dependency Installed:
  aspnetcore-runtime-8.0.x86_64 0:8.0.2-1                                       
  aspnetcore-targeting-pack-8.0.x86_64 0:8.0.2-1                                
  dotnet-apphost-pack-8.0.x86_64 0:8.0.2-1                                      
  dotnet-host.x86_64 0:8.0.2-1                                                  
  dotnet-hostfxr-8.0.x86_64 0:8.0.2-1                                           
  dotnet-runtime-8.0.x86_64 0:8.0.2-1                                           
  dotnet-runtime-deps-8.0.x86_64 0:8.0.2-1                                      
  dotnet-targeting-pack-8.0.x86_64 0:8.0.2-1                                    
  libicu.x86_64 0:50.2-4.amzn2.0.1                                              
  netstandard-targeting-pack-2.1.x86_64 0:2.1.0-1                               

Complete!
+ dotnet --version
8.0.200

### Actual behavior

Downloading packages:
warning: /var/cache/yum/x86_64/2/packages-microsoft-com-prod/packages/aspnetcore-targeting-pack-8.0-8.0.3-1.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
Public key for aspnetcore-targeting-pack-8.0-8.0.3-1.x86_64.rpm is not installed
https://packages.microsoft.com/centos/8/prod/Packages/d/dotnet-runtime-8.0-8.0.3-1.x86_64.rpm: [Errno 14] curl#92 - "HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)"
Trying other mirror.

Error downloading packages:
dotnet-runtime-8.0-8.0.3-1.x86_64: [Errno 256] No more mirrors to try.

**Comment by jkoritzinsky** [comment]
cc: @NikolaMilosavljevic

**Comment by tapadarj** [comment]
We are pulling image from amazonlinux:latest when creating docker

**Comment by tapadarj** [comment]
@NikolaMilosavljevic any update?

**Comment by NikolaMilosavljevic** [comment]
> * sudo rpm -Uvh https://packages.microsoft.com/config/centos/8/packages-microsoft-prod.rpm

Sorry for late reply. This works fine using your steps. Are you still experiencing this issue?

**Comment by NikolaMilosavljevic** [comment]
Closing - please reopen if this does repro again.
