### ISSUE TITLE
[wasm] CreateGoodBreakpointAndHit failure

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#99686]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=599642
Build error leg or test failing: DebuggerTests.BreakpointTests.DebuggerTests.BreakpointTests.CreateGoodBreakpointAndHit
Pull request: https://github.com/dotnet/runtime/pull/98559

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "<CreateGoodBreakpointAndHit>b__0(JObject pause_location) in /_/src/mono/browser/debugger/DebuggerTestSuite/BreakpointTests.cs",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=599642
**Error message validated:** `[<CreateGoodBreakpointAndHit>b__0(JObject pause_location) in /_/src/mono/browser/debugger/DebuggerTestSuite/BreakpointTests.cs`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 3/13/2024 1:23:28 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[604256](https://dev.azure.com/dnceng-public/public/_build/results?buildId=604256)|dotnet/runtime|[chrome-DebuggerTests.BreakpointTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=604256&view=ms.vss-test-web.build-test-results-tab&runId=14702580&resultId=100318)|dotnet/runtime#99659|
|[602795](https://dev.azure.com/dnceng-public/public/_build/results?buildId=602795)|dotnet/runtime|[chrome-DebuggerTests.BreakpointTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=602795&view=ms.vss-test-web.build-test-results-tab&runId=14666380&resultId=100318)|dotnet/runtime#99659|
|[602027](https://dev.azure.com/dnceng-public/public/_build/results?buildId=602027)|dotnet/runtime|[chrome-DebuggerTests.BreakpointTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=602027&view=ms.vss-test-web.build-test-results-tab&runId=14621808&resultId=100318)|dotnet/runtime#99659|
|[599642](https://dev.azure.com/dnceng-public/public/_build/results?buildId=599642)|dotnet/runtime|[chrome-DebuggerTests.BreakpointTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=599642&view=ms.vss-test-web.build-test-results-tab&runId=14539984&resultId=100318)|dotnet/runtime#98559|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|3|4|

**Comment by thaystg** [comment]
Fixed.
