### ISSUE TITLE
[5.0] Versioning in the 5.0 universe

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/runtime#997]
With CoreFx moving to 5.0 branding, we have an opportunity to unify our various versioning schemes. Meaning that `ProductVersion`, `FileVersion`, `AssemblyVersion`, and `PackageVersion`s can likely all be bumped to something in the `5` band. We should come up with a plan for what this will look like so we can get into a good state before we start shipping packages to customers.

TODO:

- [x] - Update `AssemblyVersions` for all assemblies
- [x] - Update `packageIndex.json` with new AssemblyVersions
- [x] - Remove packages that we wish to dead-end (e.g. `System.Reflection.Emit.*`, `Microsoft.Bcl.*`)
- [x] - Update `ProductVersion` - done by https://github.com/dotnet/corefx/pull/39503
- [x] - Update `PackageVersions` - done by https://github.com/dotnet/corefx/pull/39503
- [x] - Update `FileVersions` - done by https://github.com/dotnet/corefx/pull/39503
- [ ] - Write a versioning doc for 5.0
- [x] - Update TFM to something like `netcoreapp5.0`
- [x] - Undo disabling PackageIndex check (https://github.com/dotnet/corefx/pull/39503/commits/7611a2e965f7389a0ad9332ffa12743cd18ebe6c)

CC @ericstj @leculver @safern @joperezr @danmosemsft

**Comment by leculver** [comment]
What will the first version range for .Net 5 look like?  I just wanted to confirm it doesn't overlap with Silverlight Watson crashes.
