### ISSUE TITLE
TimeZoneInfo_DisplayNameStartsWithOffset failures for Syria and Greenland

### ISSUE THREAD

**Issue by filipnavara** [dotnet/runtime#99727]
I started getting local failures for this test:
```
  [FAIL] System.Tests.TimeZoneInfoTests.TimeZoneInfo_DisplayNameStartsWithOffset(tzi: (UTC-03:00) Greenland)
  -03:00 != -02:00:00, dn:(UTC-03:00) Greenland, sn:Greenland Standard Time
     at System.Tests.TimeZoneInfoTests.TimeZoneInfo_DisplayNameStartsWithOffset(TimeZoneInfo tzi) + 0x838
     at System.Runtime.Tests!<BaseAddress>+0x1e6d442
     at System.Runtime.RawCalliHelper.Call(IntPtr, Void*, Byte&, Byte&, Void*) + 0x29
     at System.Reflection.DynamicInvokeInfo.InvokeWithFewArguments(IntPtr, Byte&, Byte&, Object[], BinderBundle, Boolean) + 0xaa
  [FAIL] System.Tests.TimeZoneInfoTests.TimeZoneInfo_DisplayNameStartsWithOffset(tzi: (UTC+02:00) Damascus)
  02:00 != 03:00:00, dn:(UTC+02:00) Damascus, sn:Syria Standard Time
     at System.Tests.TimeZoneInfoTests.TimeZoneInfo_DisplayNameStartsWithOffset(TimeZoneInfo tzi) + 0x838
     at System.Runtime.Tests!<BaseAddress>+0x1e6d442
     at System.Runtime.RawCalliHelper.Call(IntPtr, Void*, Byte&, Byte&, Void*) + 0x29
     at System.Reflection.DynamicInvokeInfo.InvokeWithFewArguments(IntPtr, Byte&, Byte&, Object[], BinderBundle, Boolean) + 0xaa
```

Syria changed the standard time last October. Greenland changed it on 25 March 2023.

This is on Windows 11 build 10.0.26063.1.

/cc @tarekgh

**Comment by tarekgh** [comment]
@filipnavara looks we need to fix the test. Are you interested to submit a PR?

**Comment by filipnavara** [comment]
Similar case in the past has been reported to the Windows team as OS bug. Hence why I reported it in issue first to get a proper triage

I can make a PR with workaround and/or report it as OS feedback but I would prefer someone knowledgeable to chime in first whether it’s the right approach.

**Comment by tarekgh** [comment]
@filipnavara thanks. I'll take a look when I get a chance.

**Comment by Clockwork-Muse** [comment]
.... So, given that this (and similar tests) is driven by CLDR/ICU updates, should we be pulling in/using a custom, static, data set so that we don't keep running into these issues?

**Comment by ericstj** [comment]
> .... So, given that this (and similar tests) is driven by CLDR/ICU updates, should we be pulling in/using a custom, static, data set so that we don't keep running into these issues?

I think we want to look at these to understand how things change and decide if we need to fix the tests or framework - or at least get some signal and tell customers what to expect, do you agree @tarekgh?

**Comment by tarekgh** [comment]
@ericstj I am currently looking at another time zone issue which may be related. I am not worried about this one as I am sure this is just Windows updated some data in the localized resource which not matching the current Syria's zone offset. Or Windows could already fixed it. Anyway, I'll try it but I am not seeing this is critical for 9.0 to fix.

**Comment by tarekgh** [comment]
I have run the tests on Windows 11 build 26100 and the test is not failing. I confirmed returning the correct results:

```
  Greenland Standard Time .. (UTC-02:00) Greenland .. Greenland Standard Time .. Greenland Daylight Time .. -02:00:00
  Syria Standard Time .. (UTC+03:00) Damascus .. Syria Standard Time .. Syria Daylight Time .. 03:00:00
```  

I am pretty sure it was a temporary issue on Windows build having wrong resource values. I am closing and will watch if we see the issue again.
