### ISSUE TITLE
dotnet sln add <project> throws segfault

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#9972]
@wli3 commented on [Fri Aug 25 2017](https://github.com/dotnet/core-setup/issues/3094)

_From @suvl on August 24, 2017 15:21_

## Steps to reproduce
I've ran `dotnet sln Sib.sln add src/Sib.Console.DataLoader/Sib.Console.DataLoader.csproj`
where the csproj is: 

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <StartupObject>Sib.Console.DataLoader.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" Version="2.4.4" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <None Update="musicians.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>

``` 

## Expected  behavior
Well, project gets added to the solution I believe.

## Actual behavior
`$ dotnet sln Sib.sln add src/Sib.Console.DataLoader/Sib.Console.DataLoader.csproj 
Segmentation fault
`

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     deepin
 OS Version:  15.4.1
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/jm/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

_Copied from original issue: dotnet/cli#7505_

---

@wli3 commented on [Fri Aug 25 2017](https://github.com/dotnet/core-setup/issues/3094#issuecomment-325052908)

_From @suvl on August 24, 2017 15:25_

similar behaviour for `dotnet restore` and `dotnet run`

---

@wli3 commented on [Fri Aug 25 2017](https://github.com/dotnet/core-setup/issues/3094#issuecomment-325052912)

_From @suvl on August 24, 2017 15:45_

Solved, in a bad way. Had to downgrade libcurl3 from version 7.52.1 to 7.38.0-4 (debian oldstable / jessie). Will keep it open 'cause this is not the optimal solution.

---

@pje-cloudbuy commented on [Fri Nov 03 2017](https://github.com/dotnet/core-setup/issues/3094#issuecomment-341682482)

Having a similar (intermittent) issue, only with `dotnet sln`.

In my case `dotnet sln some.solution.sln remove docker-compose.dcproj`

---

@steveharter commented on [Wed Jan 10 2018](https://github.com/dotnet/core-setup/issues/3094#issuecomment-356770403)

Is this still an issue? If so, it should be moved to the https://github.com/dotnet/sdk location

---

@davidroth commented on [Thu Jan 11 2018](https://github.com/dotnet/core-setup/issues/3094#issuecomment-356913125)

Yep it's stil an issue for us. 

---

@livarcocc commented on [Thu Mar 15 2018](https://github.com/dotnet/core-setup/issues/3094#issuecomment-373463348)

How is this an SDK issue? The SDK here is just a portable application that is failing to run on the machine due to runtime native dependencies.

@steveharter can we re-evalidate this?

---

@steveharter commented on [Mon Mar 19 2018](https://github.com/dotnet/core-setup/issues/3094#issuecomment-374371245)

I was thinking it was a segfault due to add-a-project-to-sln, but it appears it is a libcurl or other native dependency issue. Moving to coreclr

**Comment by danmosemsft** [comment]
Closing as we cannot progress without this info.
