### ISSUE TITLE
.NET6 -- Fatal error. Internal CLR error. (0x80131506)

### ISSUE THREAD

**Issue by Farb** [dotnet/runtime#99745]
### URL(s)

.net version :

839cdfb0ecca5e0be3dbccd926e7651ef50fdf10
6.0.2

### Description

I used .net6 to process some business logics.But I encountered a fatal error.

I write a method that is called "MergeDictionary" and only merges two dictionary.The stacktrace is as following:

```
   Fatal error. Internal CLR error. (0x80131506)
 -   at System.Collections.Generic.Dictionary`2[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Resize(Int32, Boolean)
 -   at System.Collections.Generic.Dictionary`2[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryInsert(System.__Canon, System.__Canon, System.Collections.Generic.InsertionBehavior)
 at MyCustomDictionaryExtensions.MergeDictionary(System.Collections.Generic.Dictionary`2<System.String,System.String>, System.Collections.Generic.Dictionary`2<System.String,System.String>, Boolean)
```

**Comment by huoyaoyuan** [comment]
Have you tested with latest patch of 6.0? 6.0.28 was released yesterday.
Does the same issue reproduce in 8.0?

**Comment by Farb** [comment]
@huoyaoyuan I asked the user to try again on the other machines. According to his feedback,Desktop PC is ok,but laptop not.
And my desktop is ok too. I have not tried other version runtimes. The following is his pc configuration:

**Comment by huoyaoyuan** [comment]
The .NET version from `dotnet --info` can produce detailed information.

This may already be fixed by earlier patches, so it's important to update and test with latest patch.

**Comment by Farb** [comment]
.Net6 info
```
\env\dotnet>dotnet --info

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 6.0.2 
```

**Comment by Farb** [comment]
Same error reproduced in the lastest version 6.0.28.
`error. Internal CLR error. (0x80131506)`

**Comment by markholst** [comment]
Please note this has been resolved on .NET 7, and, I believe has been merged into .NET 8.
I have wasted an unbelievable amount of time on this issue until I recently saw this issue under .NET 7.
The linked PR demonstrates setting $ENV:DOTNET_TC_QuickJit = 0 is a suitable work-around.
Can you please ensure this fix is merged back into .NET 6 ASAP.

**Comment by huoyaoyuan** [comment]
> Can you please ensure this fix is merged back into .NET 6 ASAP.

There's only half year remaining for .NET 6 support for today. Only security issues will be considered at this stage. An issue with viable workaround is very unlikely to be considered.

**Comment by markholst** [comment]
I'll be honest, that isn't a viable workaround.
And 6 months of support is a reasonable percentage of the 3 year support period.

**Comment by huoyaoyuan** [comment]
It's in the policy at https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core:

> During the maintenance support period, .NET releases are updated to mitigate security vulnerabilities, only.

> The maintenance support period is the final 6 months of support for any release (STS or LTS). After the maintenance period ends, the release is out of support.

There is always a workaround that is upgrading to the next LTS version.

**Comment by markholst** [comment]
Well you'd better close this issue as resolved then

**Comment by mangod9** [comment]
Closing since this is fixed in later .net 7+ versions
