### ISSUE TITLE
For `dotnet/llvm-project` only: Remove ObjWriter cpp code.

### ISSUE THREAD

**Issue by TIHan** [dotnet/runtime#99782]
It was mentioned that the LLVM ObjWriter native code is merged with `main` on [`dotnet/llvm-project`](https://github.com/dotnet/llvm-project). Now that we are no longer using LLVM ObjWriter (see https://github.com/dotnet/runtime/pull/99733), we should delete the ObjWriter native code from `main` in [`dotnet/llvm-project`.](https://github.com/dotnet/llvm-project)

**Comment by MichalStrehovsky** [comment]
Cc @akoeplinger @directhex: objwriter tree and the related patches to LLVM in llvm-project are now dead code. Any suggestions on how to get rid of it? (E.g. leave alone and drop once we update to the next LLVM version? Not sure what's our LLVM update strategy.)

**Comment by akoeplinger** [comment]
It depends a bit on whether you want to keep the llvm objwriter fallback for the 9.0 release. If yes then I'd wait until release/9.0 branching in summer and drop it in main (net10) at that point.

If you think you don't need the fallback in 9.0 then we can just delete it from main right now.

**Comment by akoeplinger** [comment]
Ah I missed that you removed the fallback in https://github.com/dotnet/runtime/pull/99733.

I'll remove the code in llvm-project then :)
