### ISSUE TITLE
[6.0] CryptographicException : Cryptography_OAEPDecoding in Rsa.Tests.EncryptDecrypt_Array.RsaDecryptAfterExport 

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#99792]
## Build Information

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=603897
Build error leg or test failing: System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Array.RsaDecryptAfterExport

## Error Message

```json
{
  "ErrorMessage" : "CapiHelper.Windows.cs(844,0): at Internal.NativeCrypto.CapiHelper.DecryptKey",
  "BuildRetry" : false,
  "ExcludeConsoleLog" : false
}
```

- PR: https://github.com/dotnet/runtime/pull/99787
- Queue: `Libraries Test Run release coreclr windows x64 Debug`
- Job result: https://dev.azure.com/dnceng-public/public/_build/results?buildId=603897&view=logs&j=55b384d0-d6b0-5894-fd8a-d754d713246e&t=8dcacd81-cb5e-5ac9-93e5-c3f19b19e19b
- Log file: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-pull-99787-merge-a81a53a685804d358a/System.Security.Cryptography.Csp.Tests/1/console.c0cf5d9b.log?helixlogtype=result
- Output:
```
    System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Array.RsaDecryptAfterExport [FAIL]
      System.Security.Cryptography.CryptographicException : Cryptography_OAEPDecoding
      Stack Trace:
        /_/src/libraries/System.Security.Cryptography.Csp/src/System/Security/Cryptography/CapiHelper.Windows.cs(844,0): at Internal.NativeCrypto.CapiHelper.DecryptKey(SafeKeyHandle safeKeyHandle, Byte[] encryptedData, Int32 encryptedDataLength, Boolean fOAEP, Byte[]& decryptedData)
        /_/src/libraries/System.Security.Cryptography.Csp/src/System/Security/Cryptography/RSACryptoServiceProvider.Windows.cs(282,0): at System.Security.Cryptography.RSACryptoServiceProvider.Decrypt(Byte[] rgb, Boolean fOAEP)
        /_/src/libraries/System.Security.Cryptography.Csp/src/System/Security/Cryptography/RSACryptoServiceProvider.Windows.cs(668,0): at System.Security.Cryptography.RSACryptoServiceProvider.Decrypt(Byte[] data, RSAEncryptionPadding padding)
        /_/src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.cs(18,0): at System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Array.Decrypt(RSA rsa, Byte[] data, RSAEncryptionPadding padding)
        /_/src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.cs(619,0): at System.Security.Cryptography.Rsa.Tests.EncryptDecrypt.RsaDecryptAfterExport()
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=603897
**Error message validated:** `[CapiHelper.Windows.cs(844,0): at Internal.NativeCrypto.CapiHelper.DecryptKey`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 3/14/2024 10:44:14 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by jeffhandley** [comment]
No recent hits
