### ISSUE TITLE
CoreFx needs to version assemblies in the shared framework past those which are OOB and have different surface area

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#998]
Previously whenever we added API to a contract or moved types down we had to version the assembly.  This was necessary because the contract was meant to be a portable representation along a single timeline of the API.

Up to this point we haven't cared about the assembly version when adding .NETCore-specific API.  This was because we were viewing .NETCore as a "fork" of the contract.  We could imagine .NETCore having more API than the portable view of the contract since the portable view was constrained by what was in other frameworks/netstandard.

Not caring about this was OK because there was never the case that someone would be getting a different assembly when targeting .NETCore: all those .NETCore specific assemblies were in the same package and/or in the framework package for targeting .NETCore.

This has changed since we started allowing framework roll-forward.  Framework roll-forward allows for a snapshot of the asset resolution for an older framework to be used on a newer framework.  This breaks the assumption I mentioned above.

This will cause a problem whenever we 
1. Permit a package to provide an asset on a previous version of  .NETCore.
2. The same assembly in that package has significantly different API that would have caused us to version the contract in the newer version of .NETCore:
  a. Added API
  b. Forwarded API in the reference assembly.
  c. *Forwarded API in the implementation assembly* - I need to think through this more to understand if this is an issue.  My gut feel is that it is, since some other assembly might be compiling against implementation assemblies and expect the type to exist at the forwarded location.  In practice we may be able to rely on B in order to force things that might compile against  implementation into non-oob mode.

This need not be in two different versions of the package and indeed is a problem at steady state.

Consider the System.Memory issue https://github.com/dotnet/corefx/issues/29032.  We build a netstandard2.0 version of System.Memory that defines all the types as living in System.Memory.  We build a netcoreapp2.1 version that has forwarded the types down to System.Runtime.  Today these have the same assembly version, and if they are from the same build have the same file version as well.  An application uses System.Memory and targets netcoreapp2.0.  At runtime the application is rolled forward to netcoreapp2.1.  Today if the version is the same the applocal copy will be preferred.  I'll assert that is a bug and inconsistent with the way build works: https://github.com/dotnet/core-setup/issues/4047.  Ignoring that, if a newer package of System.Memory was used the same will happen.  This is a problem.  At steady state the System.Memory package will contain a netstandard2.0 asset and nothing in our current versioning policy will cause us to bump the inbox version.

To address this issue I propose that we need to increase the assembly version of the implementation assembly in NETCoreApp whenever the netcoreapp version will have different API than another reference in the same package.  This is more than is needed: technically the only requirement is that we do this whenever the older API surface would have been oob-able to a previous roll-forward capable framework but that feels like too specific of a rule to maintain.

Perhaps we can implement the more specific rule in 2.1 to limit the churn, then start following the generic rule in 2.2.

/cc @weshaggard

**Comment by ViktorHofer** [comment]
@ericstj what's the remaining work that should be tracked here?

**Comment by ericstj** [comment]
I'm less inclined to add a bunch of additional validation here, instead we should aim to simplify our cross compilation cases.
