### ISSUE TITLE
Signature validation error - Microsoft Services Store Api 

### ISSUE THREAD

**Issue by DeveloperFrom81** [dotnet/runtime#99821]
### Description

I followed the following steps in order to access the Microsoft Services Store Api using Postman

https://learn.microsoft.com/en-us/gaming/gdk/_content/gc/commerce/service-to-service/xstore-authenticating-your-service

But still I have the following error when I submit a request in Postman to

https://purchase.mp.microsoft.com/v8.0/b2b/recurrences/query
{
    "code": "Unauthorized",
    "data": [],
    "details": [],
    "innererror": {
        "code": "AuthenticationFailure",
        "data": [
            "Processing of the HTTP request resulted in an error. StatusCode: Unauthorized, PurchaseFD : Unauthorized : The client is not authorized to perform the requested operation. : { : AuthenticationTokenInvalid : Authentication token supplied is invalid : { : B2B key : IDX10511: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.X509SecurityKey, KeyId: '36D101AF67A9F61B8017FB96F91EDD4B22F05804', InternalId: 'NtEBr2ep9huAF_uW-R7dSyLwWAQ'. , KeyId: 36D101AF67A9F61B8017FB96F91EDD4B22F05804\n'. \nNumber of keys in TokenValidationParameters: '4'. \nNumber of keys in Configuration: '0'. \nMatched key was in 'TokenValidationParameters'. \nkid: '36D101AF67A9F61B8017FB96F91EDD4B22F05804'. \nExceptions caught:\n '[PII of type 'System.Text.StringBuilder' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.\ntoken: '[PII of type 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'. See https://aka.ms/IDX10511 for details.}}"
        ],
        "details": [],
        "message": "The Authorization header is invalid",
        "source": "PurchaseFD"
    },
    "message": "The client is not authorized to perform the requested operation.",
    "source": "PurchaseFD"
}

using a bearer access token aquired from 
https://login.microsoftonline.com/my clientid/oauth2/token
having the resource pointing to https://onestore.microsoft.com

and I aquired a second bearer token to the same url but with resource pointing to
https://onestore.microsoft.com/b2b/keys/create/purchase
I used this bearer token in c# in order to aquire a jwt access token
        private string bearertkn = "mysecondbearertoken";
        public async void test()
        {
            StoreContext sc = StoreContext.GetDefault();
            string jwt = await sc.GetCustomerPurchaseIdAsync(bearertkn, "myemailadress");
which I used to create the store id key which is the b2bkey in my first post

As a result I am stuck now for weeks

My toolset is
Azure+VS Studio 2022 and Dotnet 8 with Postman

Please help me out asap!?

### Reproduction Steps

Reproduction is written above

### Expected behavior

I expect to 

### Actual behavior

I expect to receive query results

**Comment by jeffschwMSFT** [comment]
this is the .NET Core runtime repo, windows developer assistance is the best place for this question.  I hope that this link helps.

https://developer.microsoft.com/en-us/windows/support/?tabs=keytopics

**Comment by DeveloperFrom81** [comment]
none issue
