### ISSUE TITLE
 System.Diagnostics.Metrics does not add my counter in the instrument in case of dotnet MAUI applicaiton when running android emulator

### ISSUE THREAD

**Issue by SVerma799** [dotnet/runtime#99822]
I created a .NET MAUI application and recording metrics for both android and Windows application.

I am using this code below.

 var meterProvider = Sdk.CreateMeterProviderBuilder()
.AddMeter("MyCompany.MyProduct.MyLibrary")
.ConfigureResource(resource => resource.AddService("Test"))
.AddConsoleExporter()
.AddPrometheusHttpListener(
    options => options.UriPrefixes = new string[] { $"http://localhost:{9188}/" })
.Build();

 MyFruitCounter.Add(1, new("name", "apple"), new("color", "red"));
 MyFruitCounter.Add(2, new("name", "lemon"), new("color", "yellow"));
 MyFruitCounter.Add(1, new("name", "lemon"), new("color", "yellow"));
 MyFruitCounter.Add(2, new("name", "apple"), new("color", "green"));
 
 
 Above is the code provide (taken) from the documentation for opentelemetry in .Net Version 8.0. I tried to run this in the android emulator and counter is enabled = false and true if I run the application as windows application.
 
 Therefore, i would like to report this issue. I 
 
when I am running in android emulator in google pixel 5 with .Net 8.0. with opentelemetry to record the metric. 
![image](https://github.com/dotnet/dotnet-api-docs/assets/49226983/ed9ef1a6-8737-4ac2-9f69-f56a5a30207a)

When i am running as an windows application 
![image](https://github.com/dotnet/dotnet-api-docs/assets/49226983/51abf3c8-c4c5-44ea-a070-9334854db067)

**Comment by CarnaViire** [comment]
cc @dotnet/area-system-diagnostics-metric

**Comment by tarekgh** [comment]
@SVerma799 could you please check your MAUI app on Android if it define the config switch [`System.Diagnostics.Metrics.Meter.IsSupported`](https://github.com/dotnet/runtime/blob/main/docs/workflow/trimming/feature-switches.md)? If it does, either you need to remove it or set the value to true.

**Comment by tarekgh** [comment]
https://github.com/dotnet/runtime/issues/89880
