### ISSUE TITLE
Ping class acts differently on Linux vs Windows

### ISSUE THREAD

**Issue by rjrizzuto** [dotnet/runtime#99838]
When I set a TTL of 1 (to implement traceroute functionality), I get TimedOut with an address of 0.0.0.0 on Linux.  On Windows, I get the expected TtlExpired with the IP address of my router.

**Comment by CarnaViire** [comment]
cc @dotnet/ncl

**Comment by wfurt** [comment]
looks like dup of #73232

**Comment by rjrizzuto** [comment]
I am not sure. That ticket is talking about containers.  My issue is on Linux mint 21.3,. Net 8 with sudo for raw socket access.

**Comment by wfurt** [comment]
do you have any simple repro you can share @rjrizzuto? That would simplify the investigation.

**Comment by wfurt** [comment]
(and what .NET  version do you use)

**Comment by rjrizzuto** [comment]
dotnet --version reports  8.0.103

This is the simple test code I wrote:

using System.Net.NetworkInformation;    

var X = new Ping();
var options = new PingOptions(1, true);
byte[] buffer = new byte[0];
var reply = X.Send("8.8.8.8",5000,buffer,options);
Console.WriteLine(reply.Address.ToString());
Console.WriteLine(reply.Status.ToString());

Here's what I see on my Linux system:

using System.Net.NetworkInformation;    

var X = new Ping();
var options = new PingOptions(1, true);
byte[] buffer = new byte[0];
var reply = X.Send("8.8.8.8",5000,buffer,options);
Console.WriteLine(reply.Address.ToString());
Console.WriteLine(reply.Status.ToString());

**Comment by rjrizzuto** [comment]
My bad.  It's fixed now.

**Comment by rjrizzuto** [comment]
On Windows 11, the same code outputs this:

192.168.86.1
TtlExpired

That is the expected behavior.

**Comment by wfurt** [comment]
fixed by https://github.com/dotnet/runtime/pull/99875
