### ISSUE TITLE
[RyuJIT/arm32/arm64] CQ: implement containment for 0.0 in vcmp/fcmp

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#9983]
Related to dotnet/coreclr#17083

category:cq
theme:basic-cq
skill-level:intermediate
cost:small
impact:small

**Comment by TIHan** [comment]
Closing as we already handled the ARM64 side of this. 

The ARM32 version is still outstanding, but it's not worth the effort to put in new encodings to handle it; the impact is much much smaller now since ARM64 is done.

**Comment by TIHan** [comment]
ARM64 implementation In `genCodeForCompare`:
```cpp
...
        if (op2->IsFloatPositiveZero())
        {
            assert(op2->isContained());
            emit->emitIns_R_F(INS_fcmp, cmpSize, op1->GetRegNum(), 0.0);
        }
...
```
