### ISSUE TITLE
The `Dispose(bool)` seems not implemented correctly

### ISSUE THREAD

**Issue by skyoxZ** [dotnet/runtime#99877]
https://github.com/dotnet/runtime/blob/3eb129fd57994bb7ecfff6f93259bd829423cde1/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/SHA256.cs#L262-L266

AFAIK `managedDisposableMember.Dispose` should be called only when `disposing` is true in `Dispose(bool)` because when `Dispose(false)` is called in the finalizer (if there is), the member may have been released to be null.

I learned that nearly 10 years ago and I can't find any reference of it now. So I want to get a confirmation if I'm right. If yes, is there an analyzer for that?

`SHA256.Implementation` doesn't have a finalizer so maybe it won't be a problem.

**Comment by vcsjones** [comment]
> I learned that nearly 10 years ago and I can't find any reference of it now. 

This is called the Dispose Pattern and is described here: https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose#dispose-and-disposebool

> AFAIK managedDisposableMember.Dispose should be called only when disposing is true in Dispose(bool)

This is true for `Dispose()` however in this case the Dispose is forwarding the `disposing` value on to the helper class `HashProvider`, so this isn't really the dispose pattern. Rather just delegating the dispose pattern to a helper.

The HashProvider implementation is platform-specific, however all of them do correctly respect the `disposing` value as you expect it to: managed resources are only disposed of if `disposing` is true. For example, in the Apple implementation:

https://github.com/dotnet/runtime/blob/23514349e544583e5bad7e298fff85adfeaf0655/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/HashProviderDispenser.Apple.cs#L238-L245

> If yes, is there an analyzer for that?

This is an analyzer for that, it's [CA1063](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1063) but it is not enabled by default.

However, this is not the dispose pattern.

**Comment by skyoxZ** [comment]
Thank you. I think I misunderstood before. I used to think that when an instance finalizes, its members may have been released to an untouchable state. How could that happen? It seems definitely unreasonable if I think twice.
