### ISSUE TITLE
MemoryMappedFile.CreateViewAccessor throws System.UnauthorizedAccessException: Access to the path is denied.

### ISSUE THREAD

**Issue by Korporal** [dotnet/runtime#99879]
I've used memory mapped files extensively pre-dotnet. I'm having trouble though using dotent. In Win32 multiple processes could open and map a file (each specifying its pathname) and concurrently read/write the mapped pages, but I cannot seem how to do this using the classes/methods exposed by dotnet.

If you look at this example code from [Microsoft](https://learn.microsoft.com/en-us/dotnet/standard/io/memory-mapped-files#examples), then explain to me how that second process should be coded so it opens the file _using the pathname_, rather than the name of the mapping object.

I am trying this (using `CreateFromFile` in `Open` mode) but it fails due to access:

```cs
        static void Main(string[] args)
        {
            // Assumes another process has created the memory-mapped file.
            using (var mmf = MemoryMappedFile.CreateFromFile(@"C:\Users\Hugh\Downloads\JUNKVM", FileMode.Open, "ImgA", 4096))
            {
                using (var accessor = mmf.CreateViewAccessor(0, 4096))
                {
                    int colorSize = Marshal.SizeOf(typeof(MyColor));
                    MyColor color;

                    // Make changes to the view.
                    for (long i = 0; i < 1500000; i += colorSize)
                    {
                        accessor.Read(i, out color);
                        color.Brighten(20);
                        accessor.Write(i, ref color);
                    }
                }
            }
        }
```

![image](https://github.com/dotnet/runtime/assets/12262952/8a740a02-3e70-4c6b-8d4a-72fab6b5e847)

Is this possible?

**Comment by Korporal** [comment]
My apologies, my second process was attemption to map more pages than the file actually has, a typo! I will reopen this if I find there really is something weird going on.

**Comment by Korporal** [comment]
The problem actually remains how to have two processes each concurrently open the same file.

**Comment by Korporal** [comment]
Has nobody seen this? It seems impossible for two processes to both open and map a file, using the file's pathname. No example I could conjur up would work, so wanted confirmation that this is now impossible under .Net.

**Comment by Jozkee** [comment]
It is possible, you need to provide the FileStream or SafeFileHandle yourself with the proper FileShare/Access values, the string overload uses FileShare.Read, which may be why you get the access denied.
