### ISSUE TITLE
Native AOT: Is there any way to link to the hybrid c runtime?

### ISSUE THREAD

**Issue by Demonese** [dotnet/runtime#99895]
Currently, Native AOT executables are linked to the dynamic c runtime by default. But this will cause the executables depends on vcruntime*.dll.

[HybridCRT](https://github.com/microsoft/WindowsAppSDK/blob/main/docs/Coding-Guidelines/HybridCRT.md) introduced by WindowsAppSDK seems to be a reasonable solution, but I can't find relevant instructions in dotnet official documentation.

**Comment by MichalStrehovsky** [comment]
> But this will cause the executables depends on vcruntime*.dll.

Native AOT doesn't depend on vcruntime*.dll. We link the C runtime like this:

https://github.com/dotnet/runtime/blob/78fa5b8f9794de5dfa7ac6cd2702436e3c27f425/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Windows.targets#L103-L107

I think it's the same thing that the other doc calls "Hybrid CRT".

We require ucrt to be installed on the system (and all Windows version supported in .NET 8 have this library). We don't require vcruntime.

**Comment by MichalStrehovsky** [comment]
I think this was answered.
