### ISSUE TITLE
`Console.ReadKey` throws `InvalidOperationException` on Ctrl+S

### ISSUE THREAD

**Issue by carlreinke** [dotnet/runtime#99938]
### Description

If `Console.ReadKey` is waiting for a key and the user presses Ctrl+S, it throws `InvalidOperationException` with the message "Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read."

### Reproduction Steps

```
var key = Console.ReadKey();
```
Press Ctrl+S.

### Expected behavior

`ReadKey` returns a `ConsoleKeyInfo` with the appropriate `Modifiers` and `Key`.

### Actual behavior

`ReadKey` throws `InvalidOperationException`.  Output to the console is not written until the user presses another key, which is not returned from `ReadKey`.

### Regression?

The behavior is the same in .NET Framework 4.8.

### Configuration

* .NET 8.0.3
* Windows 11 (Build 22621)

### Other information

Somehow PowerShell maps this key combo to `fwd-i-search`.

**Comment by jeffhandley** [comment]
<kbd>Ctrl</kbd>+<kbd>S</kbd> is handled by the terminal host of the console application, and capturing or suppressing that key is not compatible with how `ReadKey` functions. As the exception message indicates, you will need to use `Console.Read()` if you want to venture into capturing or suppressing <kbd>Ctrl</kbd>+<kbd>S</kbd>. PowerShell itself does capture this keypress as you indicated. There are a few StackOverlow posts that discuss how to capture or suppress this key combination in console applications.

**Comment by carlreinke** [comment]
I see that [PowerShell unsets the `ENABLE_LINE_INPUT` flag to enable Ctrl+S](https://github.com/PowerShell/PSReadLine/blob/v2.3.4/PSReadLine/PlatformWindows.cs#L223).  We have [Console.TreatControlCAsInput](https://learn.microsoft.com/en-us/dotnet/api/system.console.treatcontrolcasinput?view=net-8.0) which sets/unsets the `ENABLE_PROCESSED_INPUT` flag.  Is it not viable to also have Console.TreatControlSAsInput that sets/unsets the `ENABLE_LINE_INPUT` flag?
