### ISSUE TITLE
ITypeLib2 COM type definition is wrong (since forever)

### ISSUE THREAD

**Issue by smourier** [dotnet/runtime#99946]
### Description

ITypeLib2 definition (in all .NET versions) here https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/ComTypes/ITypeLib2.cs is wrong as it's defined like this:

    public interface ITypeLib2 : ITypeLib
    {
       ... ITypeLib members ...

        void GetCustData(ref Guid guid, out object pVarVal);
        [LCIDConversion(1)]
        void GetDocumentation2(int index, out string pbstrHelpString, out int pdwHelpStringContext, out string pbstrHelpStringDll);
        void GetLibStatistics(IntPtr pcUniqueNames, out int pcchUniqueNames);
        void GetAllCustData(IntPtr pCustData);
    }

While it's defined in oaidl.h like this:

    ITypeLib2 : public ITypeLib
    {
    public:
        virtual HRESULT STDMETHODCALLTYPE GetCustData( 
            /* [in] */ __RPC__in REFGUID guid,
            /* [out] */ __RPC__out VARIANT *pVarVal) = 0;
        
        virtual /* [local] */ HRESULT STDMETHODCALLTYPE GetLibStatistics( 
            /* [out] */ ULONG *pcUniqueNames,
            /* [out] */ ULONG *pcchUniqueNames) = 0;
        
        virtual /* [local] */ HRESULT STDMETHODCALLTYPE GetDocumentation2( 
            /* [in] */ INT index,
            /* [in] */ LCID lcid,
            /* [annotation][out] */ 
            _Outptr_opt_  BSTR *pbstrHelpString,
            /* [out] */ DWORD *pdwHelpStringContext,
            /* [annotation][out] */ 
            _Outptr_opt_  BSTR *pbstrHelpStringDll) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE GetAllCustData( 
            /* [out] */ __RPC__out CUSTDATA *pCustData) = 0;
        
    };

so, GetLibStatistics and GetDocumentation2 have been switched which causes AV errors for example when GetLibStatistics is called.

### Reproduction Steps

In a console app (any version of .NET):

```
public partial class Program
{
    static void Main()
    {
        LoadTypeLibEx(@"d:\temp\my.tlb", 2, out var tlb); // reg none
        ((ITypeLib2)tlb).GetLibStatistics(IntPtr.Zero, out var _);
    }

    [DllImport("oleaut32", CharSet = CharSet.Auto)]
    private static extern int LoadTypeLibEx(string szFile, int regKind, out ITypeLib pptlib);
}

```

### Expected behavior

No error should been thrown.

### Actual behavior

It causes this:
```

Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at System.Runtime.InteropServices.ComTypes.ITypeLib2.GetLibStatistics(IntPtr, Int32 ByRef)
--------------------------------
   at ConsoleApp33.Program.Main()

```
And we can see in a debugger with oleaut32 symbols:

![image](https://github.com/dotnet/runtime/assets/5328574/70dbc76c-4431-4b7c-b862-aac24544f843)

### Regression?

I think it never (like in never from 25 years) worked.

### Known Workarounds

Redefine ITypeLib2 like this (PS: GetDocumentation2 is bad too):

```
[ComImport, Guid("00020411-0000-0000-C000-000000000046"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
public interface ITypeLib2 : ITypeLib
{
    [PreserveSig]
    new int GetTypeInfoCount();
    new void GetTypeInfo(int index, out ITypeInfo ppTI);
    new void GetTypeInfoType(int index, out System.Runtime.InteropServices.ComTypes.TYPEKIND pTKind);
    new void GetTypeInfoOfGuid(ref Guid guid, out ITypeInfo ppTInfo);
    new void GetLibAttr(out IntPtr ppTLibAttr);
    new void GetTypeComp(out ITypeComp ppTComp);
    new void GetDocumentation(int index, out string strName, out string strDocString, out int dwHelpContext, out string strHelpFile);
    new bool IsName([MarshalAs(UnmanagedType.LPWStr)] string szNameBuf, int lHashVal);
    new void FindName([MarshalAs(UnmanagedType.LPWStr)] string szNameBuf, int lHashVal, [Out][MarshalAs(UnmanagedType.LPArray)] ITypeInfo[] ppTInfo, [Out][MarshalAs(UnmanagedType.LPArray)] int[] rgMemId, ref short pcFound);
    [PreserveSig]
    new void ReleaseTLibAttr(IntPtr pTLibAttr);

    void GetCustData(ref Guid guid, out object pVarVal);
    void GetLibStatistics(IntPtr pcUniqueNames, out int pcchUniqueNames);

   // note this one is bad too
    void GetDocumentation2(int index, int lcid, out string pbstrHelpString, out int pdwHelpStringContext, out string pbstrHelpStringDll);
    void GetAllCustData(IntPtr pCustData);
}

```

### Configuration

Any .NET setup.

**Comment by skataben** [comment]
Conundrum... Do you leave it broken, or do you fix it and cause a breaking change? 😄

**Comment by AaronRobinsonMSFT** [comment]
This is silly. Thanks for reporting it @smourier. Unlikely we are going to port this back, but it will be fixed in .NET 9.
