### ISSUE TITLE
Build linux-x64 Debug Mono_MiniJIT_LibrariesTests failure

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#99942]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=607213&view=logs&jobId=acb13675-61ce-556b-996f-26eeb02b1259
Build error leg or test failing: System.Text.Json.Tests

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "dmesg: read kernel buffer failed: Operation not permitted",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=607213
**Error message validated:** `[dmesg: read kernel buffer failed: Operation not permitted`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 3/19/2024 1:56:21 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[620961](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620961)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620961&view=ms.vss-test-web.build-test-results-tab&runId=15197518&resultId=214273)|dotnet/runtime#100347|
|[620921](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620921)|dotnet/runtime|[JSImportGenerator.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620921&view=ms.vss-test-web.build-test-results-tab&runId=15194982&resultId=206700)|dotnet/runtime#99439|
|[620719](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620719)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620719&view=ms.vss-test-web.build-test-results-tab&runId=15190238&resultId=192874)|dotnet/runtime#99859|
|[620711](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620711)|dotnet/runtime|[System.IO.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620711&view=ms.vss-test-web.build-test-results-tab&runId=15191588&resultId=206211)|dotnet/runtime#96332|
|[620739](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620739)|dotnet/runtime|[normal-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620739&view=ms.vss-test-web.build-test-results-tab&runId=15188342&resultId=100001)|dotnet/runtime#96169|
|[620561](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620561)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620561&view=ms.vss-test-web.build-test-results-tab&runId=15182612&resultId=104414)||
|[620560](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620560)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620560&view=ms.vss-test-web.build-test-results-tab&runId=15182568&resultId=104414)||
|[620557](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620557)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620557&view=ms.vss-test-web.build-test-results-tab&runId=15182148&resultId=104515)||
|[620573](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620573)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620573&view=ms.vss-test-web.build-test-results-tab&runId=15182100&resultId=104515)||
|[620550](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620550)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620550&view=ms.vss-test-web.build-test-results-tab&runId=15182076&resultId=104515)||
|[620552](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620552)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620552&view=ms.vss-test-web.build-test-results-tab&runId=15182034&resultId=104515)||
|[620566](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620566)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620566&view=ms.vss-test-web.build-test-results-tab&runId=15181994&resultId=104541)||
|[620572](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620572)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620572&view=ms.vss-test-web.build-test-results-tab&runId=15181978&resultId=104541)||
|[620571](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620571)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620571&view=ms.vss-test-web.build-test-results-tab&runId=15181942&resultId=104541)||
|[620563](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620563)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620563&view=ms.vss-test-web.build-test-results-tab&runId=15181854&resultId=104541)||
|[620454](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620454)|dotnet/runtime|[System.Linq.Queryable.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620454&view=ms.vss-test-web.build-test-results-tab&runId=15178782&resultId=210371)|dotnet/runtime#100288|
|[620016](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620016)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620016&view=ms.vss-test-web.build-test-results-tab&runId=15167016&resultId=206674)|dotnet/runtime#100293|
|[619986](https://dev.azure.com/dnceng-public/public/_build/results?buildId=619986)|dotnet/runtime|[System.Diagnostics.Process.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=619986&view=ms.vss-test-web.build-test-results-tab&runId=15165030&resultId=207228)|dotnet/runtime#100001|
|[619690](https://dev.azure.com/dnceng-public/public/_build/results?buildId=619690)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=619690&view=ms.vss-test-web.build-test-results-tab&runId=15161960&resultId=202788)|dotnet/runtime#99596|
|[619719](https://dev.azure.com/dnceng-public/public/_build/results?buildId=619719)|dotnet/runtime|[System.Threading.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=619719&view=ms.vss-test-web.build-test-results-tab&runId=15160696&resultId=100009)|dotnet/runtime#100310|
|[619629](https://dev.azure.com/dnceng-public/public/_build/results?buildId=619629)|dotnet/runtime|[System.Globalization.Extensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=619629&view=ms.vss-test-web.build-test-results-tab&runId=15160346&resultId=100100)|dotnet/runtime#99991|
|[619593](https://dev.azure.com/dnceng-public/public/_build/results?buildId=619593)|dotnet/runtime|[System.Globalization.CalendarsWithConfigSwitch.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=619593&view=ms.vss-test-web.build-test-results-tab&runId=15158402&resultId=100099)|dotnet/runtime#100289|
|[619238](https://dev.azure.com/dnceng-public/public/_build/results?buildId=619238)|dotnet/runtime|[Microsoft.Extensions.Options.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=619238&view=ms.vss-test-web.build-test-results-tab&runId=15148990&resultId=207766)|dotnet/runtime#100300|
|[618964](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618964)|dotnet/runtime|[Microsoft.Extensions.Http.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618964&view=ms.vss-test-web.build-test-results-tab&runId=15139960&resultId=213977)|dotnet/runtime#100291|
|[618669](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618669)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618669&view=ms.vss-test-web.build-test-results-tab&runId=15133124&resultId=205701)|dotnet/runtime#99596|
|[618598](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618598)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618598&view=ms.vss-test-web.build-test-results-tab&runId=15130688&resultId=104414)||
|[618601](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618601)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618601&view=ms.vss-test-web.build-test-results-tab&runId=15130578&resultId=104414)||
|[618609](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618609)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618609&view=ms.vss-test-web.build-test-results-tab&runId=15130348&resultId=108290)||
|[618593](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618593)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618593&view=ms.vss-test-web.build-test-results-tab&runId=15130344&resultId=104570)||
|[618613](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618613)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618613&view=ms.vss-test-web.build-test-results-tab&runId=15130184&resultId=104515)||
|[618610](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618610)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618610&view=ms.vss-test-web.build-test-results-tab&runId=15130176&resultId=104515)||
|[618587](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618587)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618587&view=ms.vss-test-web.build-test-results-tab&runId=15130064&resultId=104515)||
|[618608](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618608)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618608&view=ms.vss-test-web.build-test-results-tab&runId=15130040&resultId=104515)||
|[618596](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618596)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618596&view=ms.vss-test-web.build-test-results-tab&runId=15130142&resultId=104570)||
|[618607](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618607)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618607&view=ms.vss-test-web.build-test-results-tab&runId=15129930&resultId=104541)||
|[618589](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618589)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618589&view=ms.vss-test-web.build-test-results-tab&runId=15129900&resultId=104541)||
|[618590](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618590)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618590&view=ms.vss-test-web.build-test-results-tab&runId=15129838&resultId=104541)||
|[618606](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618606)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618606&view=ms.vss-test-web.build-test-results-tab&runId=15129822&resultId=104541)||
|[618422](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618422)|dotnet/runtime|[System.Threading.Thread.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618422&view=ms.vss-test-web.build-test-results-tab&runId=15126250&resultId=207626)||
|[617751](https://dev.azure.com/dnceng-public/public/_build/results?buildId=617751)|dotnet/runtime|[Microsoft.Extensions.HostFactoryResolver.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=617751&view=ms.vss-test-web.build-test-results-tab&runId=15111792&resultId=149551)|dotnet/runtime#100169|
|[617731](https://dev.azure.com/dnceng-public/public/_build/results?buildId=617731)|dotnet/runtime|[System.Net.NameResolution.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=617731&view=ms.vss-test-web.build-test-results-tab&runId=15111052&resultId=215834)|dotnet/runtime#100260|
|[617697](https://dev.azure.com/dnceng-public/public/_build/results?buildId=617697)|dotnet/runtime|[System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=617697&view=ms.vss-test-web.build-test-results-tab&runId=15110212&resultId=215718)|dotnet/runtime#98559|
|[617471](https://dev.azure.com/dnceng-public/public/_build/results?buildId=617471)|dotnet/runtime|[System.Memory.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=617471&view=ms.vss-test-web.build-test-results-tab&runId=15103706&resultId=213129)|dotnet/runtime#100241|
|[617434](https://dev.azure.com/dnceng-public/public/_build/results?buildId=617434)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=617434&view=ms.vss-test-web.build-test-results-tab&runId=15101588&resultId=198689)|dotnet/runtime#100251|
|[617442](https://dev.azure.com/dnceng-public/public/_build/results?buildId=617442)|dotnet/runtime|[Microsoft.Extensions.Http.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=617442&view=ms.vss-test-web.build-test-results-tab&runId=15101832&resultId=211065)|dotnet/runtime#100252|
|[616583](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616583)|dotnet/runtime|[Microsoft.Extensions.Http.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616583&view=ms.vss-test-web.build-test-results-tab&runId=15076336&resultId=211087)|dotnet/runtime#100184|
|[616525](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616525)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616525&view=ms.vss-test-web.build-test-results-tab&runId=15074048&resultId=104414)||
|[616512](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616512)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616512&view=ms.vss-test-web.build-test-results-tab&runId=15073970&resultId=104414)||
|[616514](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616514)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616514&view=ms.vss-test-web.build-test-results-tab&runId=15073632&resultId=104570)||
|[616534](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616534)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616534&view=ms.vss-test-web.build-test-results-tab&runId=15073612&resultId=104515)||
|[616532](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616532)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616532&view=ms.vss-test-web.build-test-results-tab&runId=15073532&resultId=104515)||
|[616522](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616522)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616522&view=ms.vss-test-web.build-test-results-tab&runId=15073382&resultId=104515)||
|[616505](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616505)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616505&view=ms.vss-test-web.build-test-results-tab&runId=15073328&resultId=104515)||
|[616520](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616520)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616520&view=ms.vss-test-web.build-test-results-tab&runId=15073202&resultId=104541)||
|[616510](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616510)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616510&view=ms.vss-test-web.build-test-results-tab&runId=15073514&resultId=104540)||
|[616523](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616523)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616523&view=ms.vss-test-web.build-test-results-tab&runId=15073186&resultId=104541)||
|[616516](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616516)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616516&view=ms.vss-test-web.build-test-results-tab&runId=15073096&resultId=104541)||
|[616508](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616508)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616508&view=ms.vss-test-web.build-test-results-tab&runId=15073076&resultId=104541)||
|[616287](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616287)|dotnet/runtime|[System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616287&view=ms.vss-test-web.build-test-results-tab&runId=15064602&resultId=182927)|dotnet/runtime#100222|
|[616182](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616182)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616182&view=ms.vss-test-web.build-test-results-tab&runId=15060714&resultId=202500)|dotnet/runtime#100218|
|[616136](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616136)|dotnet/runtime|[System.Runtime.Serialization.Xml.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616136&view=ms.vss-test-web.build-test-results-tab&runId=15058894&resultId=207338)|dotnet/runtime#100146|
|[615911](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615911)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615911&view=ms.vss-test-web.build-test-results-tab&runId=15050258&resultId=104414)||
|[615910](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615910)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615910&view=ms.vss-test-web.build-test-results-tab&runId=15050154&resultId=104414)||
|[615925](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615925)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615925&view=ms.vss-test-web.build-test-results-tab&runId=15049930&resultId=104570)||
|[615902](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615902)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615902&view=ms.vss-test-web.build-test-results-tab&runId=15049824&resultId=104570)||
|[615899](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615899)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615899&view=ms.vss-test-web.build-test-results-tab&runId=15049734&resultId=104515)||
|[615924](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615924)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615924&view=ms.vss-test-web.build-test-results-tab&runId=15049708&resultId=104515)||
|[615909](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615909)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615909&view=ms.vss-test-web.build-test-results-tab&runId=15049688&resultId=104515)||
|[615917](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615917)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615917&view=ms.vss-test-web.build-test-results-tab&runId=15049668&resultId=104522)||
|[615922](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615922)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615922&view=ms.vss-test-web.build-test-results-tab&runId=15049544&resultId=104541)||
|[615901](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615901)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615901&view=ms.vss-test-web.build-test-results-tab&runId=15049514&resultId=104541)||
|[615904](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615904)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615904&view=ms.vss-test-web.build-test-results-tab&runId=15049488&resultId=104541)||
|[615900](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615900)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615900&view=ms.vss-test-web.build-test-results-tab&runId=15049468&resultId=104541)||
|[615699](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615699)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615699&view=ms.vss-test-web.build-test-results-tab&runId=15042610&resultId=205342)|dotnet/runtime#100194|
|[615358](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615358)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615358&view=ms.vss-test-web.build-test-results-tab&runId=15031518&resultId=104414)||
|[615362](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615362)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615362&view=ms.vss-test-web.build-test-results-tab&runId=15031454&resultId=104414)||
|[615360](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615360)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615360&view=ms.vss-test-web.build-test-results-tab&runId=15030884&resultId=104515)||
|[615344](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615344)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615344&view=ms.vss-test-web.build-test-results-tab&runId=15030910&resultId=104570)||
|[615340](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615340)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615340&view=ms.vss-test-web.build-test-results-tab&runId=15030928&resultId=104570)||
|[615336](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615336)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615336&view=ms.vss-test-web.build-test-results-tab&runId=15030768&resultId=104515)||
|[615354](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615354)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615354&view=ms.vss-test-web.build-test-results-tab&runId=15030708&resultId=104515)||
|[615337](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615337)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615337&view=ms.vss-test-web.build-test-results-tab&runId=15030688&resultId=104515)||
|[615365](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615365)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615365&view=ms.vss-test-web.build-test-results-tab&runId=15030588&resultId=104541)||
|[615339](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615339)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615339&view=ms.vss-test-web.build-test-results-tab&runId=15030620&resultId=104915)||
|[615342](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615342)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615342&view=ms.vss-test-web.build-test-results-tab&runId=15030596&resultId=104566)||
|[615346](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615346)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615346&view=ms.vss-test-web.build-test-results-tab&runId=15030548&resultId=104568)||
|[615309](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615309)|dotnet/runtime|[Microsoft.Extensions.Http.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615309&view=ms.vss-test-web.build-test-results-tab&runId=15029474&resultId=211015)|dotnet/runtime#100178|
|[615075](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615075)|dotnet/runtime|[System.Security.SecureString.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615075&view=ms.vss-test-web.build-test-results-tab&runId=15024082&resultId=207499)|dotnet/runtime#100170|
|[613929](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613929)|dotnet/runtime|[System.Linq.Queryable.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613929&view=ms.vss-test-web.build-test-results-tab&runId=14997786&resultId=210356)|dotnet/runtime#100134|
|[613910](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613910)|dotnet/runtime|[JSImportGenerator.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613910&view=ms.vss-test-web.build-test-results-tab&runId=14997566&resultId=206685)|dotnet/runtime#99956|
|[613794](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613794)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613794&view=ms.vss-test-web.build-test-results-tab&runId=14994106&resultId=116162)|dotnet/runtime#100138|
|[613655](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613655)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613655&view=ms.vss-test-web.build-test-results-tab&runId=14988580&resultId=104414)||
|[613653](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613653)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613653&view=ms.vss-test-web.build-test-results-tab&runId=14988110&resultId=104515)||
|[613637](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613637)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613637&view=ms.vss-test-web.build-test-results-tab&runId=14988208&resultId=104570)||
|[613643](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613643)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613643&view=ms.vss-test-web.build-test-results-tab&runId=14988082&resultId=104515)||
|[613650](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613650)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613650&view=ms.vss-test-web.build-test-results-tab&runId=14988042&resultId=104515)||
|[613630](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613630)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613630&view=ms.vss-test-web.build-test-results-tab&runId=14988006&resultId=104515)||
|[613638](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613638)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613638&view=ms.vss-test-web.build-test-results-tab&runId=14987882&resultId=104541)||
|[613641](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613641)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613641&view=ms.vss-test-web.build-test-results-tab&runId=14987858&resultId=104548)||
|[613633](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613633)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613633&view=ms.vss-test-web.build-test-results-tab&runId=14987838&resultId=104541)||
Displaying 100 of 155 results
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|19|119|155|

**Comment by jkotas** [comment]
> dmesg: read kernel buffer failed: Operation not permitted

This is very generic error message that is produced for most fatal crashes on macOS. This issue has picked up many unrelated crashes.

We need to open issues with more specific patterns next time.
