### ISSUE TITLE
Mono interpreter leg timing out in CI on a variety of tests

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#99940]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=606964
Build error leg or test failing: LibraryImportGenerator.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/99835

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "interpreter.*Executor timed out",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=606964
**Error message validated:** `[interpreter.*Executor timed out`]
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 3/19/2024 12:48:38 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as this has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by lewing** [comment]
closing this, there are other issues tracking timouts
