### ISSUE TITLE
[HttpStress] malloc crashes in HTTP/3 runs

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#99960]
The client process is sporadically crashing. Linux occurrences and crash dumps so far:

1. `malloc(): unaligned tcache chunk detected` 
https://github.com/dotnet/runtime/files/13979172/DumpsLinux.zip

2. `malloc(): mismatching next->prev_size (unsorted)`
https://github.com/dotnet/runtime/files/14299406/DumpsLinux.1.zip

3. `malloc(): unaligned tcache chunk detected`
[DumpsLinux-3.zip](https://github.com/dotnet/runtime/files/14652906/DumpsLinux-3.zip)
https://dev.azure.com/dnceng-public/public/_build/results?buildId=606726&view=logs&j=22fea640-1099-5f32-ec5d-316ad83f359a&t=a923b061-8445-5c16-cd6e-848990587cb0

We don't know if this happens on Windows because of #95750.

**Comment by ManickaP** [comment]
Not seen for quite a while, closing, we'll re-open if it happens again.
